### ISSUE TITLE
Document bindata update process

### ISSUE THREAD

**Issue by tboerger** [go-gitea/gitea#10]

**Comment by linquize** [comment]
The process is more complicated as we still support go < v1.4

**Comment by tboerger** [comment]
Who says that we will support it?

**Comment by linquize** [comment]
as of gogs 0.6.1, gogs can be compiled using go >= 1.2, travis tests with go 1.2, 1.3, 1.4

**Comment by tboerger** [comment]
Ok, we really need proper documentation, I already found out that the latest ```go-bindata``` version is broken. And even with older versions the new bindata looks totally different. Digging in that stuff.

**Comment by tboerger** [comment]
https://github.com/jteeuwen/go-bindata/issues/95

**Comment by tboerger** [comment]
Done with #45
