### ISSUE TITLE
Question: Primary key state location

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#10000]
Let's say we have some repositories. Each repository has an ID (1, 2, 3, etc.) If I delete the 3rd repository and create a new repository, it will get the ID 4 instead of 3. It looks like Gitea stores somewhere stores the value, and increments it when a new repository is created, giving the repository the previous value. If I remove the repository the value does not get changed back, which I completely understand why. My question is, where does this value get stored in the database / files?

**Comment by davidsvantesson** [comment]
It is a feature of SQL databases. The repo id is stored in the database and uses auto increment:
https://www.w3schools.com/sql/sql_autoincrement.asp
