### ISSUE TITLE
[Enhancement] Add a touch icon.

### ISSUE THREAD

**Issue by NiTRoeSE** [go-gitea/gitea#10003]
Please add a "apple touch Icon".
If you add gitea website as app to homscreen on ios devices there is no icon shown because of missing touch icon.

Sample:

![IMG_0322](https://user-images.githubusercontent.com/24574743/73137619-5a091380-405a-11ea-80a0-67535f59d1be.jpeg)

Should be:

![IMG_0323](https://user-images.githubusercontent.com/24574743/73137657-d26fd480-405a-11ea-9463-2f5667888b0d.png)

It would be nice and of course gitea has it deserved that also a proper icon is displayed :)

Thanks for your work, Gitea is great :)

**Comment by zeripath** [comment]
For anyone interested in providing a PR for this.

https://www.collectiveray.com/joomla/joomla-tips-and-tricks/94-creating-a-favicon-and-apple-icon-for-your-website.html

seems to describe how to do it...

**Comment by silverwind** [comment]
Assuming https://realfavicongenerator.net is up to date, it should be one 180px icon:

````html
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
````
We can add it to https://github.com/go-gitea/gitea/blob/master/Makefile#L516

**Comment by NiTRoeSE** [comment]
@silverwind / @zeripath 

Thanks guys for fast reply and commit. 😀
