### ISSUE TITLE
[Feature] Move a issue to a other repo

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#10028]
as title

Detailed: option to move a issue (and its commits) on RepoA to RepoB
if succeded Issue has new Index and is on RepoB
Issue on RepoA has deleted all its comments, is (closed or keeps state of new issue?) and has a redirect to the new position

**Comment by lunny** [comment]
I think it's a duplicated issue.

**Comment by 6543** [comment]
me too but couldn't find it jet ... so i write down my thougt for now

**Comment by lunny** [comment]
duplicated with #2991
