### ISSUE TITLE
API Features for automated build tools

### ISSUE THREAD

**Issue by Zuph** [go-gitea/gitea#10033]
- Gitea version (or commit ref): 1.12.0
- Git version: N/A
- Operating system: N/A
- Database (use `[x]`):
  - [X] PostgreSQL
  - [X] MySQL
  - [X] MSSQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:

## Description

I'm trying to adapt some Drone plugins to work with Gitea, and I'm running into some missing parts of the API. Specifically

- List Pull Request Files (/repos/:owner/:repo/pulls/:pull_number/files, https://developer.github.com/v3/pulls/#list-pull-requests-files) (Possibly addressed by #3472 ?)
- Compare two commits (/repos/:owner/:repo/compare/:base...:head, https://developer.github.com/v3/repos/commits/#compare-two-commits)

I'm happy to hack around and try and add these, but I wanted to document the want in case my Go skills aren't quite up to it :smiley:

**Comment by 6543** [comment]
as for documenting ... -> https://github.com/go-gitea/gitea/blob/master/CONTRIBUTING.md#api-v1 ;)
