### ISSUE TITLE
[Bug] Cant Force Push LFS-enabled to NON-LFS repo

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#10031]
when converting a repo to use LFS i have to create a new one. i cant reupload to the old repo ...

see: https://discourse.gitea.io/t/convert-existing-repository-in-gitea-to-one-using-git-lfs/1848

**Comment by 6543** [comment]
git push --force

produce:
```
Locking support detected on remote "origin". Consider enabling it with:
  $ git config lfs.https://code.net/user/repo.git/info/lfs.locksverify true
ref master:: Error in git rev-list --stdin --objects --not --remotes=origin --: exit status 128 fatal: bad object 5cef6f90554c99060e8de94d423b4775f92120f8

error: failed to push some refs to 'ssh://git@code.net:22/user/repo.git'
```
push to new repos works just fine

**Comment by 6543** [comment]
2nd thought: since the init commit is different this may cause the problem

**Comment by 6543** [comment]
need more time to infestiage - will look at this later ...

**Comment by 6543** [comment]
☝️

**Comment by 6543** [comment]
ping

**Comment by zeripath** [comment]
@6543 sorry I missed this. I'm not quite sure from what you've written how to reproduce this. Did you ever get to the bottom of the problem? Is the failure definitely coming from Gitea?

**Comment by 6543** [comment]
No didn't had a deeper look into this jet

**Comment by 6543** [comment]
local tested - works now with current master
