### ISSUE TITLE
[Feature] Git tag support in commits history

### ISSUE THREAD

**Issue by joseluisq** [go-gitea/gitea#10036]
- Gitea version (or commit ref): 1.10.3
- Git version: N/A
- Operating system: Linux x86_64
- Database:
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite

## Description

It would great if Gitea can support git tags as well in commits history.

## Screenshots

Current Gitea commits history:
<img width="739" alt="image" src="https://user-images.githubusercontent.com/1700322/73247318-ec233000-41b0-11ea-8f9d-79db9c1082a3.png">

[1] Here a visual example of Bitbucket Server commits history, note the tag aside.

<img width="942" alt="image" src="https://user-images.githubusercontent.com/1700322/73246240-6c946180-41ae-11ea-9286-d73faa016efc.png">

**Comment by lunny** [comment]
This feature is very useful.

**Comment by bendem** [comment]
That's one of the little things that make the overall experience better.

**Comment by joseluisq** [comment]
@bendem yeah!
Talking about subtle improvements, it can also be great if we can rename `SHA1` to just `Commit`.  Just a suggestion, but I think is not part of this feature issue.

**Comment by lunny** [comment]
Which place should we put the tags? Consider the most bad thing, one commit has been tagged as four tags.

**Comment by joseluisq** [comment]
> Which place should we put the tags?

Inside the _Message_ table cell but aligned to right and overlying the message. See screenshot below.

> Consider the most bad thing, one commit has been tagged as four tags.

Just displaying the number of tags greater than 1 for a particular commit.
Otherwise for one tag per commit, just display the tag as it is.

Here an example how is handled on Bitbucket server.

![image](https://user-images.githubusercontent.com/1700322/84947677-e344e380-b0ea-11ea-85bd-fab15cc0b62c.png)

When mouse is over the _"5 tags"_ label, a tooltip shows the 5 tags names concatenated by a separator.
Bitbucket is using a colon char like `v1.4.4:v1.4:v1:latest:stable` but Gitea can use a coma or another separator.

For Bitbucket, group of tags are not clickable, whereas for one tag per commit is possible to click on. But Gitea can take a different aproach, for example it can make clickable both kind of labels. 
Group of tags can redirect to _Tags page_, whereas single tags can redirect to the corresponding _tag page_.

I hope this can help.

**Comment by xblax** [comment]
This feature would be really useful, I'm missing that a lot with Gitea. In other Git front ends that seems to be a standard feature, just like tags are also displayed together with the commit in standard `git log` or `git log --pretty=oneline`. 

Any chance this feature could be considered for a future release?

**Comment by Richdark** [comment]
This feature would truly enhance the experience. When using Bitbucket, a quick glance at commit history allows me to see where/when exactly has previous versions of my product been released. I'd love to have that option in Gitea too.
