### ISSUE TITLE
No complex admin password at installation stage

### ISSUE THREAD

**Issue by Xumeiquer** [go-gitea/gitea#10045]
- Gitea version (or commit ref):1.12.0+dev-206-g28216bde4
- Git version:
- Operating system: MacOS
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ x] Not relevant
- Log gist:

## Description
The admin user registration form at the installation stage does not ask for a complex password, on the other hand, it does when adding a user manually in the admin site.

**Comment by bagasme** [comment]
Perhaps enforcing password complexity requirements on installation?

**Comment by 6543** [comment]
I think this this is a because the ADMIN has to decide securety settings anyway ...

For example the best is 2FA for admin accounts ... e.g.

But feel free do tell me your opinion :)

**Comment by Xumeiquer** [comment]
@6543 that is not a mandatory requirement. I installed Gitea from source and used the default app.ini and Gitea does not ask for a complex password when setting the admin account.

**Comment by wxiaoguang** [comment]
Agree with 6543, admin should know what password they should use.
