### ISSUE TITLE
Stop page reload when hiding the labels dropdown

### ISSUE THREAD

**Issue by davidglezz** [go-gitea/gitea#10056]
When displaying the labels dropdown of labels and selecting none, the page reloads.

The expected behavior is that if there are no changes do not reload the page. I realized when I was editing an issue and displayed the menu and I lost all the changes.

- Gitea version: 1.9 an 1.10
- Tested on Google Chrome

![gitea2](https://user-images.githubusercontent.com/194784/73347126-60300780-4287-11ea-8b62-325d1c8f378a.gif)

**Comment by silverwind** [comment]
Page reloads should be eliminated, they are always disruptive and unneccessary.

**Comment by wxiaoguang** [comment]
Fixed by  #23014 (a quick fix)
