### ISSUE TITLE
gitea dump does not include lfs folder if LFS_CONTENT_PATH is set to a custom folder

### ISSUE THREAD

**Issue by gtino** [go-gitea/gitea#10058]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
Running gitea on Windows Server 2019 with LFS enabled. The command:
`gitea dump ...`
does not include the lfs folder if the folder is not in the default folder (e.g. `c:\Program Files\Gitea\data\lfs`).

I have my lfs folder in a RAID 1 volume (just like the repos and everything I need to backup) at `D:/Gitea/data/lfs` and I did set:

`LFS_CONTENT_PATH = D:/Gitea/data/lfs`

Im not a go expert but by reading the dump.go code looks like it simply includes the folders under `c:\Program Files\Gitea\data` without checking if the `lfs` folder is somewhere else. Of course adding a link does not work.

...

**Comment by bagasme** [comment]
@gtino Which Gitea version did you use?

**Comment by gtino** [comment]
Gitea Version: 1.11.0+rc2

**Comment by gtino** [comment]
Looks like lfs are not dumped on official 1.11 release either. Is there maybe a setting that I am missing? I am zipping them separately myself, but it would be a lot easier if Gitea was taking care of dumping them along with the other files...

**Comment by mpb27** [comment]
I am experiencing a similar issue (no LFS in backup with custom `LFS_CONTENT_PATH=/home/git/gitea-lfs`) on version 1.10.1.

**Comment by zeripath** [comment]
@philipphomann would you like to offer your fix as a PR to Gitea?

**Comment by PhilippHomann** [comment]
@zeripath It is included in #10376 which still waits on second approval (:
