### ISSUE TITLE
API page blank

### ISSUE THREAD

**Issue by devsentient** [go-gitea/gitea#10066]
Hi,
I started up a Gitea instance using docker compose on an EC2 instance. The main site loads fine, but when I go to `/api/swagger` the page comes back blank. Log shows that it loaded successfully. Same works with no issues on localhost. What could be the problem?

**Comment by 6543** [comment]
I guess a config one

**Comment by 6543** [comment]
@devsentient did you set `ROOT_URL`  to your gitea address ?

docs: https://docs.gitea.io/en-us/config-cheat-sheet/#server-server

**Comment by devsentient** [comment]
Thanks that solved it.
