### ISSUE TITLE
Question: expected results of models.GetRepositoryAccesses()?

### ISSUE THREAD

**Issue by guillep2k** [go-gitea/gitea#10068]
- Gitea version (or commit ref): 04cbdf5c08ef7468100269935613250846e801c4 (current `master`)

While working on #9787, I need to rewrite [`models.GetRepositoryAccesses()`](https://github.com/go-gitea/gitea/blob/04cbdf5c08ef7468100269935613250846e801c4/models/access.go#L113). This function is only used by [`ListMyRepos()`](https://github.com/go-gitea/gitea/blob/04cbdf5c08ef7468100269935613250846e801c4/routers/api/v1/user/repo.go#L104) as a complement of `GetUserRepositories()`. `ListMyRepos()` works the API function:

```
// swagger:operation GET /user/repos user userCurrentListRepos
```

`GetRepositoryAccesses()` is supposed to return all the repositories that the user has access to but does not own. The problem is that the unit test goes like:

https://github.com/go-gitea/gitea/blob/04cbdf5c08ef7468100269935613250846e801c4/models/access_test.go#L90-L96

With the current data, this function should fail because `user1` is a site administrator, so it's got access to all repositories. The test asserts that the function returns zero results.

My question is: is the unit test/fixture set wrong, or is it that the function is expected to ignore the `is_admin` flag to return a shorter list?

**Comment by lunny** [comment]
I think maybe the function `GetRepositoryAccesses` is not expected.

I think we should refactor all `SearchRepository` functions.

**Comment by zeripath** [comment]
It's an old broken function that I wanted to remove when I fixed search repositories but realised I couldn't as it is part of the API. It should be deprecated.

**Comment by guillep2k** [comment]
Thanks! So, what's the API expected to do (with some detail)? Maybe it's easier for me to rewrite the endpoint rather than it parts? Where is it used?
I'm afraid that a slow deprecation spanning a couple of versions is not an option from me, since I'm removing the `access` table: I either get it right or I remove it.

**Comment by zeripath** [comment]
Ah I see. I think it literally listed if a user was a collaborator or not.

**Comment by guillep2k** [comment]
Thanks! So it deals with _explicit_ accesses. 👍

**Comment by guillep2k** [comment]
> I think we should refactor all SearchRepository functions.

@lunny I'm on it (#9787)
