### ISSUE TITLE
Allow GIF as attached files and rendered in markdown

### ISSUE THREAD

**Issue by InExtremaRes** [go-gitea/gitea#10076]
- Gitea version (or commit ref): 1.12.0+dev-221-geac5142ac

Allow to upload GIF files (or another, similar format) to issues, PR, comments, wikis and everythink that is _markdownable_, since they're very useful. At the moment gitea shows a message saying the file isn't supported.

Next screenshot is trying to upload a gif file to an issue coment:

![gitea-no-gifs](https://user-images.githubusercontent.com/1635491/73478371-b9299980-4374-11ea-9a05-c14a5a1b3246.gif)

**Comment by zeripath** [comment]
I suspect that this is your configuration.

**Comment by zeripath** [comment]
https://docs.gitea.io/en-us/config-cheat-sheet/#attachment-attachment

**Comment by InExtremaRes** [comment]
Oh, you're right. I tried in my setup but also in [try.gitea.io](https://try.gitea.io) so I thought was a missing feature, not an improper configuration . Thank you for pointing this out.
