### ISSUE TITLE
[API] Authorization token documentation incorrect

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#10072]
(basic Auth allowed only!)

swagger docs:
`curl -X GET "http://localhost:3000/api/v1/users/test01/tokens" -H "accept: application/json" -H "Authorization: dGVzdDAxOnRlc3QwMQ=="`

working solution:
`curl -X GET "http://localhost:3000/api/v1/users/test01/tokens" -H "accept: application/json" -H "authorization: Basic dGVzdDAxOnRlc3QwMQ=="`

**Comment by bagasme** [comment]
@6543 swagger one authoritative?

**Comment by 6543** [comment]
spezivied the description

**Comment by 6543** [comment]
@lunny can you add lable kind/api pleace?

**Comment by zeripath** [comment]
It's wrong documentation. I think I've tried looking into fixing this before and couldn't.

**Comment by 6543** [comment]
ping @stale

**Comment by 6543** [comment]
Some Notes from discord:

 * It looks like **swagger-ui** return wrong curl suggestion
 * we should add docu about basicAuth to https://github.com/go-gitea/gitea/blob/master/routers/api/v1/api.go#L32 and below
* rename `reqToken` to make it clear that it acept token and basic auth


* handle authorization case-insensitive (https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2)

reverences:  
https://tools.ietf.org/html/rfc7617  
https://swagger.io/docs/specification/2-0/authentication/basic-authentication/

**Comment by zeripath** [comment]
* we should add docu about basicAuth to https://github.com/go-gitea/gitea/blob/master/routers/api/v1/api.go#L32 and below

We can't add anything to that yaml bit AFAIU. The spec does not allow for a desc on type: basic.

* handle authorization case-insensitive

AFAICS we already do.
