### ISSUE TITLE
Drone: 'make: go: Command not found'

### ISSUE THREAD

**Issue by silverwind** [go-gitea/gitea#10084]
https://drone.gitea.io/go-gitea/gitea/20587/1/2

I think this is coming from line `GOPATH ?= $(shell $(GO) env GOPATH)`. Either we need to add go on the `pre-build` step, set `GOPATH` only when actually needed or maybe remove `GOPATH` altogether (assuming the user has set up `GOPATH/bin` in their `PATH`)?

cc: @sapk

**Comment by sapk** [comment]
In the long time, reference to GOPATH should be removed as we moved to modules. 
To do so, we should use module for tools (similar to https://github.com/golang/go/issues/25922#issuecomment-412992431).
Before doing so we would need to drop vendor (this is a personal choice and not a mandatory step.).
And so wait for go1.14 to be release. (Should be during this month)

In the meantime, if you set GOPATH to something like /dev/null it should not call go to determine GOPATH. (?=)

**Comment by silverwind** [comment]
> use module for tools

That'd be ideal. It will also bring the benefit of locking down tool versions in `go.sum`.

**Comment by silverwind** [comment]
Looks like the issue was introduced very recently in https://github.com/go-gitea/gitea/pull/9751.

**Comment by zeripath** [comment]
I'm not sure I understand why go would not be found?!

**Comment by zeripath** [comment]
OK I see. We run the make webpack in an environment that does not have go.

In which case we simply need to change it to:

```make
HAS_GO = $(shell hash $(GO) > /dev/null 2>&1 && echo "GO" || echo "NOGO" )

ifeq ($(HAS_GO), GO)
	GOPATH ?= $(shell $(GO) env GOPATH)
endif
```

**Comment by zeripath** [comment]
We can use a similar formation to protect the rest of the go dependent sections

**Comment by zeripath** [comment]
@sapk this variable isn't exported it's simply added so that we know where the go tools will be built to etc.

**Comment by sapk** [comment]
@zeripath yes I know but we can get ride of call to tools (build in go) to their binary path relative to GOPATH and use module build cache via go run (and version locking via go.sum). The main goal is to be independant of GOPATH defintion and it would need be kept in PATH. This bring benifit by removing a setup step (even if it was needed and setup by everyone before). 
But we cannot do it yet relative to oldest supported go version and the solution you suggest is better than the one I propose to set GOPATH to /dev/null.
