### ISSUE TITLE
Trash from Pull Request(?)

### ISSUE THREAD

**Issue by theAkito** [go-gitea/gitea#10080]
- Gitea version (or commit ref): 68e4f4efc73e06eafa6bbb0aa469e208336f84ae
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

Running
```
 find . -name "gitea" | grep "/hooks/pre-receive.d/" | xargs cat | grep tris
```
in the gitea source directory
results in:
```
"/home/tris/Projects/go/src/code.gitea.io/gitea/gitea" hook --config='/home/tris/Projects/go/src/code.gitea.io/gitea/custom/conf/app.ini' pre-receive
```

**Comment by jolheiser** [comment]
Looks like you ran Gitea from a binary built from source and created a repo?

**Comment by theAkito** [comment]
I build Gitea from source regularly, yes.

**Comment by jolheiser** [comment]
What you found is the Gitea managed git-hook in that repo. Were you expecting something else?

**Comment by theAkito** [comment]
Well, as you can see from above command, I did not look for a specific repository. Secondly, it's still a path totally irrelevant to my system and was never irrelvent in the first place. That's why I expect it to not be there in a clean installation.

**Comment by jolheiser** [comment]
I see. It looks like you found [this file](https://github.com/go-gitea/gitea/blob/master/integrations/gitea-repositories-meta/user2/repo20.git/hooks/pre-receive.d/gitea) which is part of our integration tests.

**Comment by theAkito** [comment]
That definitely sheds some file on the issue. I did not know what these files were for, particularly. I just stumbled across this and wanted to quickly inform the maintainers what I discovered.
My actual issue was [this](https://discourse.gitea.io/t/reset-pre-receive-hooks/1865).

**Comment by jolheiser** [comment]
To answer your actual issue, you can either run `gitea admin regenerate hooks` or log into the site admin page and run `Resynchronize pre-receive, update and post-receive hooks of all repositories.`
