### ISSUE TITLE
[security issue] app.ini stores smtp auth info in plaintext

### ISSUE THREAD

**Issue by andrewzah** [go-gitea/gitea#10087]
The `app.ini` stores the mailer info like:

```
[mailer]
ENABLED = true
HOST    =
FROM    =
USER    =
PASSWD  =
```

This is a security issue. Is it not possible to load environment variables in the app.ini?

**Comment by ykcab** [comment]
@azah is there an application that you have seen which uses a config file with encrypted secrets?
Please do enlight if there is one. Even if you load it via an environment variable, it will still leaven in the same server regardless. 

Maybe we want to propose to load all these secrets at initial /install and have them saved in MySQL?

**Comment by techknowlogick** [comment]
This is not a security issue as it is assumed that you have the configuration protected appropriately as the DB credentials are also stored there. Environment variables would also need to be protected in a similar fashion.

Closing this issue.
