### ISSUE TITLE
runHTTPS() on web_graceful Doesn't Check for ACL Permissions

### ISSUE THREAD

**Issue by bagasme** [go-gitea/gitea#10094]
- Gitea version (or commit ref): 1.10.3
- Git version: 2.25.0
- Operating system: Ubuntu 18.04
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:
(see description)

## Description
I'm trying set up HTTPS using Gitea's built-in server. The certificate and its private key are located in `/etc/ssl/certs/gitnode.cert.pem` and `/etc/ssl/private/gitnode.key.pem`. Gitea fails to restart with following `journalctl` log:

```
Feb 01 08:57:56 gitnode gitea[3246]: 2020/02/01 08:57:56 ...dules/setting/git.go:87:newGit() [I] Git Version: 2.25.0, Wire Protocol Version 2 Enabled
Feb 01 08:57:56 gitnode gitea[3246]: 2020/02/01 08:57:56 routers/init.go:74:GlobalInit() [T] AppPath: /opt/gitea/gitea
Feb 01 08:57:56 gitnode gitea[3246]: 2020/02/01 08:57:56 routers/init.go:75:GlobalInit() [T] AppWorkPath: /var/lib/gitea
Feb 01 08:57:56 gitnode gitea[3246]: 2020/02/01 08:57:56 routers/init.go:76:GlobalInit() [T] Custom path: /var/lib/gitea/custom
Feb 01 08:57:56 gitnode gitea[3246]: 2020/02/01 08:57:56 routers/init.go:77:GlobalInit() [T] Log path: /var/lib/gitea/log
Feb 01 08:57:56 gitnode gitea[3246]: 2020/02/01 08:57:56 ...dules/setting/log.go:230:newLogService() [I] Gitea v1.10.3 built with GNU Make 4.1, go1.13.4 : bindata
Feb 01 08:57:56 gitnode gitea[3246]: 2020/02/01 08:57:56 ...dules/setting/log.go:273:newLogService() [I] Gitea Log Mode: Console(Console:info)
Feb 01 08:57:56 gitnode gitea[3246]: 2020/02/01 08:57:56 ...les/setting/cache.go:45:newCacheService() [I] Cache Service Enabled
Feb 01 08:57:56 gitnode gitea[3246]: 2020/02/01 08:57:56 ...s/setting/session.go:44:newSessionService() [I] Session Service Enabled
Feb 01 08:57:56 gitnode gitea[3246]: 2020/02/01 08:57:56 routers/init.go:39:checkRunMode() [I] Run Mode: Development
Feb 01 08:57:57 gitnode gitea[3246]: 2020/02/01 08:57:57 cmd/web.go:151:runWeb() [I] Listen: https://0.0.0.0:8443
Feb 01 08:57:57 gitnode gitea[3246]: 2020/02/01 08:57:57 cmd/web_graceful.go:37:runHTTPS() [F] Failed to load https cert file 0.0.0.0:8443: open /etc/ssl/private/gitnode.key.pem: permission denied
Feb 01 08:57:57 gitnode systemd[1]: gitea.service: Main process exited, code=exited, status=1/FAILURE
Feb 01 08:57:57 gitnode systemd[1]: gitea.service: Failed with result 'exit-code'.
```

It turned out that `cmd/web_graceful.go` ignore ACL permissions.

ACL on the mentioned file and directory in error log:

```
# file: etc/ssl/private/
# owner: root
# group: root
user::r--
user:git:r--
group::r--
mask::r--
other::---

# file: etc/ssl/private//gitnode.key.pem
# owner: root
# group: root
user::r--
user:git:r--
group::---
mask::r--
other::---
```

Minimum `app.ini` to reproduce the issue:

```ini
[server]
PROTOCOL = https
DOMAIN = gitnode.io
HTTP_PORT = 8443
CERT_FILE = /etc/ssl/certs/gitnode.cert.pem
KEY_FILE = /etc/ssl/private/gitnode.key.pem
```

**Comment by zeripath** [comment]
Sorry I missed this.

Here's the code:

https://github.com/go-gitea/gitea/blob/6c27f3e4e557b192747d54dd61c52aeebe6e677d/modules/graceful/server.go#L90-L124

As you can see go's own ioutill is unable to read the file. We're not doing anything special to read the file at all or permission check.

So if you're sure that the Gitea process should be able to read the file I think there's a bug with go ioutil.ReadFile

**Comment by mrsdizzie** [comment]
Silly question, but is Gitea actually running as 'git' user here? I use ACL fine for certs in similar configuration it works fine

**Comment by bagasme** [comment]
@mrsdizzie Yes

**Comment by bagasme** [comment]
@zeripath can this ioutil bug forwarded [upstream](https://github.com/golang/go/issues)?

**Comment by zeripath** [comment]
@bagasme I think you would need to create a simple test case to replicate the issue and then upstream the bug. I haven't had a go at replicating it - so don't feel appropriate opening a bug.

Double check that the issue is still there in 1.12 it might be that go has fixed it or I missed that something was fixed in the interim.
