### ISSUE TITLE
Error generating hyperlink on the the branchs page of forked  Repository

### ISSUE THREAD

**Issue by a1012112796** [go-gitea/gitea#10090]
- Gitea version (or commit ref): 1.10.3
- Git version: 
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL) 
                    error link : https://try.gitea.io/a1012112796/testm/pulls/1
                   the real : https://try.gitea.io/hhm_test/testm/pulls/1
                   page:   https://try.gitea.io/a1012112796/testm/branches/
  - [ ] No      
  - [ ] Not relevant                        
- Log gist:

## Description

Hello, everyon.  I found that if an forcked Repository have make a Pull Request to the upstream of  Repository , the PR link on the branchs page still base on this Repository , not the  upstream. so 
this hyperlink obviously cannot be linked to the correct location，and an 404 error happen. Thanks.

## Screenshots
<img width="960" alt="jt1" src="https://user-images.githubusercontent.com/25342410/73581460-4596a200-44c4-11ea-8280-88665cd4f687.png">

<img width="960" alt="jt2" src="https://user-images.githubusercontent.com/25342410/73581470-4f200a00-44c4-11ea-9f65-1bc5d563aa0a.png">

**Comment by 6543** [comment]
#10090 is dublicate of #8305
