### ISSUE TITLE
number of pull request of a repo is off center

### ISSUE THREAD

**Issue by zuhairamahdi** [go-gitea/gitea#10108]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
The number of pull requests is off center if it goes to more than 3 digits
...

## Screenshots
![pull requests center](https://user-images.githubusercontent.com/6876269/73607637-a22fb500-45c9-11ea-8af2-c0be61a25d6f.PNG)

**Comment by zuhairamahdi** [comment]
removing the width from the css (width: 15%) will fix the issue but it will give an inconstant look:
![css](https://user-images.githubusercontent.com/6876269/73719708-4849ff00-4731-11ea-8f19-fb7eab0e664f.PNG)

Result:
![result](https://user-images.githubusercontent.com/6876269/73719724-526bfd80-4731-11ea-9515-031d3a840e68.PNG)

**Comment by guillep2k** [comment]
IMHO it doesn't look so bad without the width. Maybe we should compromise at a min-width value? Maybe some flexible left margin? (not too good on CSS myself).

**Comment by zeripath** [comment]
I think this might actually be fixed already...

**Comment by zeripath** [comment]
Please reopen if not
