### ISSUE TITLE
Migration doer is a participant in all conversations

### ISSUE THREAD

**Issue by guillep2k** [go-gitea/gitea#10111]
- Gitea version (or commit ref): 1.12.0+dev-212-g82a979707

## Description

When a repository is migrated, the `doer` gets added as a participant of all issues and PRs. This seems very inconvenient regarding subscriptions and notifications. Perhaps there should be a way to add those posts and comments so that the migrator doesn't become irremediably subscribed to them.

## Screenshots

![image](https://user-images.githubusercontent.com/18600385/73609232-689b8180-45aa-11ea-81b3-9a8d115f80d7.png)

**Comment by lunny** [comment]
@guillep2k Good catch!
