### ISSUE TITLE
[Feature] UserSetting to choose witch text editor is defualt (SimpleMDE, textarea, automatic)

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#10110]
enhancement of  #10099
as per lunny:
 * automatically, pc SimpleMDE and mobile textarea and this is the default.
 * always SimpleMDE
 * always textarea

**Comment by lafriks** [comment]
I would prefer it not to be user setting but being detected by device - mobile or not

**Comment by guillep2k** [comment]
Why not both? Personally I'd rather not use SimpleMDE if that leaves me out of the stock spell checker, mobile or not, but I can understand why most people will benefit from it.

**Comment by lunny** [comment]
We could have three options on user settings:

- [ ] automatically, pc SimpleMDE and mobile textarea and this is the default.
- [ ] always SimpleMDE
- [ ] always textarea

**Comment by 6543** [comment]
@lunny nice proposal! because each like it different (example i would choose 3, but most will use 1? ...)

**Comment by corneliusroemer** [comment]
What's the reason for textarea not being the default on mobile? Isn't SimpleMDE on mobile totally broken? Or does it work for most people just not me and a few unlucky other folks?

**Comment by zeripath** [comment]
No one has coded or submitted a PR to do this.

**Comment by corneliusroemer** [comment]
#14017 isn't exactly a allowing the "user" to choose default editor, but it at least disables the broken WYSIWYG on mobile.

**Comment by 6543** [comment]
@corneliusroemer the issue should not be present on master - we can consider to use it as hotfix for v1.13.x

**Comment by 6543** [comment]
didnt we migrated already on master to EasyMDE?

**Comment by henningoschwald** [comment]
I understand there is currently no way to  disable SimpleMDE either per user or globally, is this correct?

I am blind and therefore using a screen reader to interact with Gitea, unfortunately SimpleMDE is not accessible. When moving up or down with the error keys, usually screenreaders read the currently selected line, however in SimpleMDE I am not able to read the text. Furthermore, the keyboard focus is trapped within the text field. Usually the Tab key can be used to move the focus out of the editor, although SimpleMDE seems to block this, maybe to make the Tab key usable for indentation. This however breaks keyboard accessibility.

If you plan to get rid of the WYSIWYG editor anyway, I understand you don't want to put much efford into this, but at least a keyboard shortcut to switch to the plain text area would be great in the meantime. I'l see if I can come up with a PR for this.

Please let me know if there is already a way to disable SimpleMDE per user or for the whole instance. I don't need an editor tool bar with buttons to insert common formatting mark-up, a simple text area where I can enter markdown would be perfectly fine.

**Comment by delvh** [comment]
Isn't that pseudo-implemented with #23876 already?
It contains a `switch to legacy button`, which I think is the best way to handle it for anyone who wants the old easyMDE behavior (if anyone even wants that)
