### ISSUE TITLE
About The Docs Page‘s Multilingual Edits

### ISSUE THREAD

**Issue by sky5454** [go-gitea/gitea#10118]
**Here's a text translation of the machine**
At present, the contribution to the document is very inconvenient, indirectly leading to the progress gap between the language documents is too large, I hope some good-hearted men could add a button to the document page so that the document contributor can jump directly to the corresponding md file editing page.

Here's what might be useful:

 - Online document URL: https://docs.gitea.io/en-us/install-with-docker/
 - MD files for the warehouse: gitea/docs/content/doc/app/with-docker.en-us.md 
 - Github Warehouse Online Editor Mark Down Link: https://github.com/go-gitea/gitea/edit/master/docs/content/doc/installation/with-docker.en-us.md

In addition, the current documentation system is not very convenient, it is recommended to refer to [the documentation system of MDN](https://wiki.developer.mozilla.org/zh-CN/docs/learn/JavaScript/Client-side_web_APIs/Introduction) or [ArchWiki](https://wiki.archlinux.org/)

<hr>

**Chinese Text 中文原文**

目前对文档贡献非常不方便，这间接地导致各语言文档进度差距过大，希望有好心人能在文档页面上添加一个按钮，以便于文档贡献者直接跳转到对应的md文件编辑页面。

以下可能是有用的信息：

 - 在线文档URL：https://docs.gitea.io/en-us/install-with-docker/
 - 仓库里对应的MD文件： gitea/docs/content/doc/installation/with-docker.en-us.md 
 - Github 仓库在线编辑 MarkDown 链接: https://github.com/go-gitea/gitea/edit/master/docs/content/doc/installation/with-docker.en-us.md

另外，现行的文档系统其实不是很方便，建议参考 [MDN 的文档系统](https://wiki.developer.mozilla.org/zh-CN/docs/Learn/JavaScript/Client-side_web_APIs/Introduction) 或者 [ArchWiki](https://wiki.archlinux.org/)

**Comment by lunny** [comment]
We could put a button on every page and when you click that button, you will be redirected to edit page on github or gitea in future.

**Comment by delvh** [comment]
With the new page <docs.gitea.com> (i.e. <https://docs.gitea.com/#software-and-service-support>), that button exists already.
