### ISSUE TITLE
[API] Inconsistent Label Format

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#10127]
discoverd on gitea version: 1.10.3

https://try.gitea.io/api/swagger#/issue/issueListLabels
https://try.gitea.io/api/swagger#/issue/issueCreateLabel
there is one inconsistency on those calls
List Labels return the color without #
but Create Label requires the #
it's not a big deal but it is kinda boring for someone who uses it
Because then you get errors like this:
`
panic: Error creating label [Affects Agent e11d21 This will require a new release of TrustFactor agents]: 422 Unprocessable Entity: [{"fieldNames":["Color"],"classification":"SizeError","message":"Size"}]
`

**Comment by 6543** [comment]
posible solution: display issueCreateLabel example without '#' and make it pars version with and without '#' on the beginning

**Comment by SpaWn2KiLl** [comment]
Actually I was kinda thinking about appending the `#` to the List Labels response

**Comment by 6543** [comment]
this would breace backwards compatebilety :(

**Comment by jolheiser** [comment]
> posible solution: display issueCreateLabel example without '#' and make it pars version with and without '#' on the beginning

Parsing it regardless of `#` sounds reasonable to me.

**Comment by 6543** [comment]
made a "a simple aproach" -> #10129
