### ISSUE TITLE
Migrating from local path repo failed.

### ISSUE THREAD

**Issue by wgqimut** [go-gitea/gitea#10120]
- Gitea version (or commit ref): 1.10.3
- Git version: 1.8.3.1
- Operating system: Centos 7
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description
When I create a new migration repo, we fill the local path to clone, no mirror, and the migrating UI
show the message "Migrating from <local_path> failed."
...

**Comment by lafriks** [comment]
Have you enabled local path migration in app.ini?

**Comment by wgqimut** [comment]
Yes, and I've already jump the migrating page ( if disable the local path migration, you couldn't pass the check actually), but the page show the migrating failed.
