### ISSUE TITLE
[feature request] read environment variables when loading app.ini

### ISSUE THREAD

**Issue by andrewzah** [go-gitea/gitea#10123]
I can take a stab at a PR if one could give me some pointers on where to start looking at.

This PR would allow checking in app.ini to version control and use it in setting up a dockerized gitea instance.  Right now app.ini can't be stored in version control due to saving passwords in plaintext.

**Comment by guillep2k** [comment]
I can't find the reference, but I believe another `.ini` parser was considered and/or implemented that directly supported carrying settings from env variables. It was a couple of months ago. Perhaps another maintainer remembers.

**Comment by techknowlogick** [comment]
ini support was added to viper so we could switch to it and potentially use alternative formats (yaml), but also utilize env variables as well.

**Comment by zeripath** [comment]
In the meantime there is contrib/environment-to-ini

**Comment by azah** [comment]
Thanks for the input! If I get time I'll take a look at viper.

**Comment by anbraten** [comment]
Maybe #19857 will solve this issue as well

**Comment by wxiaoguang** [comment]
Dup of #10123

Will be fixed by  Make environment-to-ini support loading key value from file #24832
