### ISSUE TITLE
'docker' build target only works with TAGS="bindata"

### ISSUE THREAD

**Issue by morrildl** [go-gitea/gitea#1013]
A simple `make docker` will result in a build that does not do the bindata asset embedding, so it crashes on startup looking for `conf/locale/locale_en-US.ini`.

If you do `TAGS="bindata" make docker` the resulting image works fine.

Perhaps the line `-e TAGS="$(TAGS)"` could be changed to `-e TAGS="bindata $(TAGS)"` to guarantee the resulting container image boots, although I have not tested that.

**Comment by bkcsoft** [comment]
Closing as fixed by #1033
