### ISSUE TITLE
Map multiple login sources to a single account

### ISSUE THREAD

**Issue by FootStark** [go-gitea/gitea#10136]
- Gitea version (or commit ref): 1.11.rc2
- Git version: 2.25.0.win1
- Operating system: Win 10
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

Is it possible to map multiple login sources to a single account? 
What I want to achieve is that actually 3 login sources can be used for each user: SSPI for single sign on from Windows boxes, a basic login (local uid/pwd) for other non-windows stuff, and (in future) OpenId with AzureAD. 
Is there an option for that? I would be perfectly fine with mapping all users manually (via db or conf-file), there is  no need for an UI. The usernames (in our case) in each login source can (and should) be identical, if it helps. 
The multiple login sources would give maximum acceptance from developers, also easing any transitioning to other / additional log-ins after first rollout.

**Comment by zeripath** [comment]
Sorry I think this got missed. Presumably you mean this to be done automatically rather than by the user linking their account manually.

**Comment by FootStark** [comment]
I would already be perfectly happy with a manual option to map multiple identity providers. Purely automatic mapping (presumeably by email address) has 2 downsides:

1. Multiple accounts with same eMail address wont work (e.g. a test and a prod account)
2. If your login names are already your email addresses (or are just an alternative alias), you won't be able to link them

But in the end a solution should be choosen which is easiest to implement with the current app design. I thought just extending from a single to multiple active authentication providers would be best. Different identity names per provider must obviously be supported.
