### ISSUE TITLE
Incremental backup of gitea

### ISSUE THREAD

**Issue by jackTheStark** [go-gitea/gitea#10135]
- Gitea version (or commit ref):
- Git version: 1.10
- Operating system: docker - linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite

## Description
I am trying to do a daily backup of gitea. But the problem is that i have to backup the whole gitea everyday which is waste of storage.

Is there a possible way to progressively track and update the backup.

**Comment by wxiaoguang** [comment]
TBH, I think this proposal is out of the goal of Gitea.

Gitea can not do everything for users, and the backup methods for different systems vary a lot. The same question to MySQL, do you see MySQL provides the automatic incremental backup and restore? If MySQL doesn't, then Gitea can't.

I would suggest users to use ZFS with snapshot, it's a more general method to do backup & restore, with incremental support.

**Comment by wxiaoguang** [comment]
I would close this issue due to the discussion in #17931
* #17931
