### ISSUE TITLE
Invalid repo urls after change username

### ISSUE THREAD

**Issue by shadowspore** [go-gitea/gitea#10141]
- Gitea version (or commit ref): 1.12.0+dev-239-g391e0638c
- Git version: 2.25.0
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (https://try.gitea.io/testNewUsername)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
After change username, user repo urls wouldn't updated.

## Screenshots
![issue1](https://user-images.githubusercontent.com/42911384/73775127-21c6ab00-47a7-11ea-8f3a-1101f9c611de.png)

**Comment by mavenbline** [comment]
I fixed this by adding the following code at the end of the `models.ChangeUserName` func (tested on sqlite)
```go
sess := x.NewSession()
defer sess.Close()
if err = sess.Begin(); err != nil {
	return err
}

if _, err = sess.Exec("UPDATE `repository` SET owner_name=? WHERE owner_name=?", newUserName, u.Name); err != nil {
	return fmt.Errorf("Change repo owner name: %v", err)
}

return sess.Commit()
```

**Comment by zeripath** [comment]
any chance you could send a PR?
