### ISSUE TITLE
[API] Search Issues By Milestone

### ISSUE THREAD

**Issue by jaqra** [go-gitea/gitea#10147]
Can we add support `search issues by milestone (id or name)` to api

**Comment by 6543** [comment]
I'll take it ;)

**Comment by lunny** [comment]
@6543, I think we have to implement milestone index before this one and this also depends on #9931

**Comment by 6543** [comment]
update: still a lot to do

**Comment by 6543** [comment]
done look at #10148

It works this way:  
 comma separated list of milestone names or ids. It uses names and fall back to ids. Fetch only issues that have any of this milestones. Non existent milestones are discarded

**Comment by jaqra** [comment]
Thank you

**Comment by IvanBezrukavyiSS** [comment]
Guys, can you provide examples how to deal with that. I also wanna use it.

**Comment by 6543** [comment]
@IvanBezrukavyiSS https://try.gitea.io/api/swagger#/issue/issueListIssues


Just add `milestones` query
