### ISSUE TITLE
fatal error: runtime: out of memory

### ISSUE THREAD

**Issue by sebastianschauenburg** [go-gitea/gitea#10153]
- Gitea version: 1.10.2
- Operating system: Debian buster
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (just try to migrate/mirror https://github.com/spacewalkproject/spacewalk )
  - [ ] No
  - [ ] Not relevant
- Log gist: https://gist.github.com/sebastianschauenburg/f34d6a23c4ddaea16282978a61ef6370

## Description

Trying to migrate/mirror https://github.com/spacewalkproject/spacewalk results in:
- gitea error: fatal error: runtime: out of memory
- webinterface error: Migrating from https://github.com/spacewalkproject/spacewalk failed.

Tried increasing the RAM of my dedicated gitea machine starting at 1 GB and eventually ended up giving it 9GB of RAM, still with the same error. Using a manual git clone, the repository will take ~ 1.1GB of disk space, so I assume something else is going on here.

**Comment by zeripath** [comment]
Hi Sebastian, If I had to guess the most likely culprit would be git packing references but taking a look at your log - this seems to point at update tags... hmm...

Take a look at the git settings for packing references but I'll have a think.

**Comment by sebastianschauenburg** [comment]
Hey Zeripath, thanks for commenting. I've found another repository which fails to migrate (maybe this helps). Also tested it the migrate on try.gitea.io and there it also fails: https://github.com/vim/vim

**Comment by Aviortheking** [comment]
I don't know if it's linked but from the last Docker repo update it keep pushing my server Memory to it's full and crashing it with the same error appearing 
https://gist.github.com/Aviortheking/c90232b9107165b1cab604ed8e4f03ee

**Comment by sebastianschauenburg** [comment]
Just wanted to let you know this is still a valid issue with the current 1.11.5  version. I also saw this system notice:

> Migrate repository from https://github.com/spacewalkproject/spacewalk failed: Clone: context deadline exceeded

**Comment by zeripath** [comment]
Hi @sebastianschauenburg have you changed the timeout settings as per:

https://docs.gitea.io/en-us/config-cheat-sheet/#git---timeout-settings-gittimeout

**Comment by sebastianschauenburg** [comment]
Thanks for that pointer. I did use the default settings previously.
Now I increased all the timeouts (tenfold), which solved the issue for me. (probably due to the old and slow hardware I'm using)
