### ISSUE TITLE
Release attachments are not deleted

### ISSUE THREAD

**Issue by bu3tt1** [go-gitea/gitea#10152]
- Gitea version (or commit ref): 1.9.4 built with GNU Make 4.2.1, go1.12.10 : bindata, sqlite, sqlite_unlock_notify
- Git version: 2.22.0
- Operating system: Docker
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
When you delete a release the attachments are not deleted. It's correct?

my app.ini:
```
[attachment]
PATH = /data/gitea/attachments
ALLOWED_TYPES = application/x-zip-compressed|application/zip|application/x-compressed-tar|application/x-gzip
```

**Comment by jolheiser** [comment]
This was fixed by #6068 for `1.10.x` so updating should fix the problem. 😄
