### ISSUE TITLE
Syntx highlighting not working properly for PERL

### ISSUE THREAD

**Issue by Aranad** [go-gitea/gitea#10157]
I notice that many of my scripts in PERL have problems with the syntax highlighting, usually where there's regex involved, e.g.

![Screenshot-20200205172429-744x441](https://user-images.githubusercontent.com/1755922/73888859-6bada080-483c-11ea-9138-38df64b5ff7c.png)

**Comment by jolheiser** [comment]
This is likely due to our use of [highlight.js](https://highlightjs.org/)  
It may (or may not) be mitigated by switching to another highlighter.

Related: #7729

**Comment by silverwind** [comment]
Please show an example on https://try.gitea.io/.

**Comment by Aranad** [comment]
Ok thanks I added a couple of examples [here](https://try.gitea.io/Aranad/Test).

**Comment by silverwind** [comment]
It is detected properly as perl source (seen in HTML `<code class="perl hljs">`), so it is very likely a bug in [highlight.js](https://github.com/highlightjs/highlight.js).
