### ISSUE TITLE
A Bug in Commit views

### ISSUE THREAD

**Issue by sky5454** [go-gitea/gitea#10163]
- Gitea version (or commit ref):1.12.0+dev-244-ge959d1a48
- Git version: 
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (https://try.gitea.io/pepe111/tensorflow/commit/981051516e6f79b57173d70276ed32359d4fd519)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
**EN** After clicking this button, it should only collapse the current file, but it also directly collapses the following files ...
**CN** 这个按钮点了以后，应该是只折叠当前文件的，但却直接把下面的文件也折叠了……
...

## Screenshots
![](https://user-images.githubusercontent.com/12370628/73943873-86f7d900-492c-11ea-8205-d3bfc23bda5e.jpg)

**Comment by nickisobrien** [comment]
This isn't reproducing on https://try.gitea.io for me.

**Comment by jolheiser** [comment]
I can't either, yet I _am_ getting weird behavior. While the file collapses, it doesn't collapse the overall space it takes up, defeating the purpose of collapsing it. 😂

**Comment by sky5454** [comment]
> This isn't reproducing on https://try.gitea.io for me.

https://try.gitea.io/pepe111/tensorflow/commit/981051516e6f79b57173d70276ed32359d4fd519
