### ISSUE TITLE
Change default docker listening port

### ISSUE THREAD

**Issue by sapk** [go-gitea/gitea#10162]
As #10154 will allow us to break thing, does we need to change default docker listening port for gitea ?
Related : https://github.com/go-gitea/gitea/pull/10154#discussion_r375633883

- :+1: use :8080
- :-1: keep :3000
- :smile: random one between 1025 and 8191

Edit: feel free to propose another port (with pros and cons)
Edit: adding random

**Comment by silverwind** [comment]
Both aren't particularily appealing choices as chance of collision is high. If we can choose again, I'd pick a random one between 1025 and 8191.

**Comment by sapk** [comment]
@silverwind I added random to the choice but the goal is only for default docker port which is static defined in Dockerfile (we can disobei what we say in Dockerfile but that wouldn't be a good idea).
Maybe this could become more global but it is firstly for new docker rootless tag.

**Comment by sapk** [comment]
We already have most responses and they are for keep. I will close this issue.
