### ISSUE TITLE
Github Mirror API Sign-In will be deprecated this summer

### ISSUE THREAD

**Issue by djotaku** [go-gitea/gitea#10171]
- Gitea version (or commit ref): 1.12.0+dev-71-gd171cd41b built with GNU Make 4.2.1, go1.13.6
- Git version:  2.24.1
- Operating system: Docker
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant

Not sure I want to enter my creds there

- Log gist: No associated logs

## Description

Yesterday created a mirror of a repo I have on Github. When I went to do that in gitea it prompted me for my Github username and password. Everything worked fine and it was mirrored. Then I got the following email from Github:

"
Hi (my username),

You recently used a password to access an endpoint through the GitHub API using go-github. On July 1st, 2020, basic authentication using password to this endpoint will no longer work:

https://api.github.com/repositories/(my repository)

We recommend using a personal access token (PAT) with the appropriate scope to access this endpoint instead. Visit https://github.com/settings/tokens for more information.
"
So I think that needs to be supported rather than username password.

**Comment by guillep2k** [comment]
Thanks for the heads-up!

**Comment by djotaku** [comment]
Got a thanks for the head's up, bu don't see any comments that this was handled, so I'm doing what the stale-bot said and adding a comment

**Comment by guillep2k** [comment]
Sorry, I've set this to be solved by 1.12.0 so we don't miss it.

**Comment by djotaku** [comment]
Yeah, no worries. Just following stale-bot's instructions.

**Comment by lunny** [comment]
@djotaku @guillep2k Gitea has support put your token in the username box to migrate repository. So we only need to put some notice on the UI that `If you are migrating repository from github, Username/password will not be supported by github. You could still put your personal access token on username box to migrate your repository from github.`

**Comment by TsakiDev** [comment]
> @djotaku @guillep2k Gitea has supportted put your token in the username box to migrate repository. So we only need to put some notice on the UI that `If you are migrating repository from github, Username/password will not be supported by github. You could still put your personal access token on username box to migrate your repository from github.`

@lunny Wouldn't it be better if the Username/Password functionality got replaced altogether by Token authentication?
e.g. Remove the username and password fields and add a Token field.

**Comment by xet7** [comment]
Username / Password field text should be replaced by Token field?

**Comment by lunny** [comment]
Now we only support token. So I close this and feel free to reopen it.
