### ISSUE TITLE
bad line length character Error when no SSH key

### ISSUE THREAD

**Issue by antonio-fr** [go-gitea/gitea#10184]
On gitea master branch (commit 11995bf2ee2572995e7bc17b2b889ae33474f36c).
When a the user has no SSH key registered. The ssh access tells `fatal: protocol error: bad line length character: git@`
How can we change the effect to be more user friendly about this error message?

**Comment by zeripath** [comment]
Oh sorry I think we missed this one.

I'm not completely clear how you're receiving this error. Could you give me a longer explanation of how to reproduce this?

**Comment by antonio-fr** [comment]
Thanks. First of all, I'm not sure this is an issue with Gitea. This might be at the sshd or git side. This is more a support question.

The issue is when using gitea in a Linux sshd server. Users auth themself using git@server using SSH protocol. When a user auth, using an agent and a git desktop client, with an unknown or invalid key (a SSH key which is not corresponding to any gitea users), the server responds with the following error message : `fatal: protocol error: bad line length character: git@.`
I'd like to know, if one got any idea, what is wrong with my server config. Because this message is not explicit at all, and I expect some message like 'wrong user key" or "unknown user".
