### ISSUE TITLE
Contributing git hook scripts

### ISSUE THREAD

**Issue by 0x6d61726b** [go-gitea/gitea#10187]
## Description

I am asking if it is supported having a place to store git hook scripts that are working with Gitea. I had a discussion on the forum on how to force a commit user to match the user the credentials belong to and I would like to share that script. I think the `contrib` folder may be a good idea?

I have prepared what's in my mind on [0x6d61726b/gitea/contrib/git/git-hook-scripts](https://github.com/0x6d61726b/gitea/tree/master/contrib/git/git-hook-scripts).

Please let me know about your opinion.

**Comment by bagasme** [comment]
@0x6d61726b OK, as `contrib` contains user-contributed scripts like yours.

BTW, please open the PR and we will review it.

**Comment by 0x6d61726b** [comment]
@bagasme Thanks for the reply. I have created the PR.
