### ISSUE TITLE
[API] Get organizations API's limit parameter not working

### ISSUE THREAD

**Issue by pd4d10** [go-gitea/gitea#10199]
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)

## Description

Get organizations API's limit parameter seems not working. It always returns all organizations, which can be reproduced in https://try.gitea.io/api/swagger#/

I'm working on a [Gitea mobile client](https://github.com/pd4d10/git-touch) and find this issue.

Thanks!

**Comment by 6543** [comment]
@pd4d10 it is working as expected: `https://try.gitea.io/api/v1/orgs?page=1&limit=5`

**Comment by 6543** [comment]
can confirm that `https://try.gitea.io/api/v1/orgs?limit=5` is not working ...

**Comment by 6543** [comment]
this is intended:

https://github.com/go-gitea/gitea/blob/74a4a1e17f99d147db9329718a5ecc87984b0ecd/models/user.go#L1601-L1603

**Comment by 6543** [comment]
@pd4d10 if you got it working - can you close this issue?

**Comment by pd4d10** [comment]
After page param added it works. Thanks for the quick response!

**Comment by pd4d10** [comment]
Hi, @6543 , it works with the `page` query added. But the response header seems to lack `x-page`, `x-hasmore` and `x-total`.

Could you help to check this? Thanks!
