### ISSUE TITLE
gitignore for Eclipse IDE broken

### ISSUE THREAD

**Issue by bohni** [go-gitea/gitea#10190]
[Commit](https://github.com/go-gitea/gitea/commit/57a8440db372d3b2a01d3ef12a4a560424a08657#diff-468af0bae0cb9d0784187368f056f4aa) removed Core file `.project` and JDT file `.classpath`

@techknowlogick, @sapk: What was the intent behind this change? Now I have to alter the file `.gitignore` every time, I create a new repo for a Java project...

**Comment by bagasme** [comment]
@bohni please compare to [gitignore.io version](https://www.gitignore.io/api/eclipse).

**Comment by bohni** [comment]
Yeah, at the end I can see these two entries...

![image](https://user-images.githubusercontent.com/1252254/74081932-a38f3080-4a54-11ea-88ab-50682a8f9b77.png)

**Comment by sapk** [comment]
@bohni this change is based on the updated gitignore list repo https://github.com/github/gitignore. It came from that commit https://github.com/github/gitignore/commit/0674ff5b5c77935cbb2ea2269c001bfd84aa1aa5#diff-d8f27c2a874cffb1caf3e38c5cc6a09e. It need to be fixed there to be updated to gitea.

**Comment by bohni** [comment]
Ah, ok. I see. I usually make a maven project and import it into Eclipse. The m2e plugin generates these files. On a real Eclipse only project, these files are indeed needed.
