### ISSUE TITLE
Install page expects an email for "Sender Email".

### ISSUE THREAD

**Issue by puffybsd** [go-gitea/gitea#1019]
- Gitea version (or commit ref):
- Git version: 2.11.1
- Operating system: Arch Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

The install page SMTP configuration requires an email address for "Sender Email"; however, many SMTP services such as Spark Post and Send Grid have APIs that require user names that are not email addresses.  Configuring the user in app.ini works, but is not user-friendly.

This issue has been fixed in an accompanying pull request.

## Screenshots
![gitea-sender-email-not-valid-email](https://cloud.githubusercontent.com/assets/418252/23239107/4246df00-f933-11e6-852a-2f2a95834aab.png)

**If regarding the Web Interface, please include a screenshot**

**Comment by strk** [comment]
Makes sense to me, LGTM

**Comment by lunny** [comment]
@strk  This is the issue, not the PR.

**Comment by strk** [comment]
Yep, figured after the fact. LGTM'd the PR too...
