### ISSUE TITLE
[UI] Dont Display File-Conflicts on merged pulls

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#10192]
gitea version: 1.12.0+dev-251-g d4096ab6a
test url: https://gitea.com/gitea/go-sdk/pulls?q=&type=all&sort=&state=closed&labels=&milestone=0&assignee=0

![Bildschirmfoto zu 2020-02-08 12-40-37](https://user-images.githubusercontent.com/24977596/74084547-8700f180-4a70-11ea-931b-09cf1f4848a9.png)

**Comment by bagasme** [comment]
I disagree.

Should be still on status quo because this informs PR openers to solve the conflicts sooner, given the file count.

**Comment by 6543** [comment]
@bagasme of **ALREADY** merged pulls ?!?

**Comment by bagasme** [comment]
@6543 AHA! I don't see the context.

Anyway, conflicted files count should only on open PRs, not closed one...

**Comment by 6543** [comment]
> conflicted files count should only on open PRs, not closed one...

thats exactly what I suggest

**Comment by guillep2k** [comment]
This is not only a UI problem. My question is: why are these values even calculated for merged PRs? PRs can't be re-opened AFAIK.

**Comment by zeripath** [comment]
If I could get #10132 to work after the latest more enforce locking this should stop happening.
