### ISSUE TITLE
Bindata-less builds appear to not use the filesystem

### ISSUE THREAD

**Issue by silverwind** [go-gitea/gitea#10193]
For rapid frontend development, I'd like to use bindata-less builds that serve files directly from `public` but these don't seem to work on current master. Even if I manually delete the bindata files, disable the service worker and do a `make gitea` (without any TAGS), I still don't see changes on frontend files reflected as if gitea still would have some sort of bindata compiled in (the binary is suspectively large).

**Comment by guillep2k** [comment]
Can you check with `gitea extract list` ?

**Comment by silverwind** [comment]
`./gitea embedded list` worked and showed no files and after I've tested again it's now working as expected so probably not an actual issue.

This should enable us to use webpack dev mode and maybe even hot reloading, will check that out.

**Comment by silverwind** [comment]
I think I figured out the root cause, see https://github.com/go-gitea/gitea/issues/10196.
