### ISSUE TITLE
[Feature] check & notification symbol on open page

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#10198]
if you have a open gitea site a smal script should check from time to time if there are new notifications.
If so it would chang the notification-symbol and (optional use the browser notification for new contend)

**Comment by 6543** [comment]
if we alow base-auth on api endpoint `GET /notifications​/new` we could use this one ...

**Comment by zeripath** [comment]
now you see why I wanted the number returned... :stuck_out_tongue:

**Comment by 6543** [comment]
should be implementend in v1.13.0-rc1
