### ISSUE TITLE
make: 'go build' does not run when TAGS change

### ISSUE THREAD

**Issue by silverwind** [go-gitea/gitea#10196]
```
TAGS=bindata make build
make build
````

The intentions is to first build with bindata, then without.

I still observe a bindata executable after the second build because`go build` never ran (`make` thinks the executable is already up to date). We somehow need to trigger `go build` when the value of `TAGS` differs from the previous build.

I'm not exactly sure how to best achieve that except writing out the last TAGS to a evidence file after build and only write the file again when TAGS differs from the file's content. If there are other environment variables that can affect the build, they would need the same treatment.

cc: @guillep2k

**Comment by guillep2k** [comment]
Yes, it's a good point. I'd write the tags to an evidence file, but only if different. Something like:
```
mkdir -p "`basedir "$EVIDENCE"`"
if [ "`cat "$EVIDENCE" 2>/dev/null`" != "$TAGS" ] ; then echo "$TAGS" > "$EVIDENCE" ; fi
```

**Comment by silverwind** [comment]
I wonder if it is safe to skip the `go generate` step if the `bindata` tag is absent.

**Comment by zeripath** [comment]
No. Do not skip generate. Even if it does nothing at present - we should start using generate more.
