### ISSUE TITLE
[Feature] set CustomPath with config

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#10200]
if configfile is set (via ENV or --param) gitea should look at a setting `CUSTOM_PATH = xy` and if it exist use this as custom path

(at the moment this is only posible to set via ENV)

**Comment by 6543** [comment]
well I't looks like I have to send a pull ;)

**Comment by 6543** [comment]
nop still didnt have time

**Comment by zeripath** [comment]
@6543 I don't understand what you're proposing here.

**Comment by 6543** [comment]
you cant set CustomPath by config

**Comment by 6543** [comment]
this is because CustomPath is determined to find ConfigFile if nothing is set
but I like to be able to do it the other way around - it would be posible if 1. moving the "DeterminCustomPath" code into its own func. 2. use a temporary customPath if configFile not specified to determin config 3. read CustomPath from config - if none use temporary customPath as CustomPath

**Comment by 6543** [comment]
why I like to have this: I use the alpine package and had to edit the init script to be able to specify CustomPath but I would like to do it the "normal" linux way by just editing /etc/gitea/app.ini

**Comment by 6543** [comment]
:eyes:

**Comment by wxiaoguang** [comment]
Is it still needed? I do not understand the necessary either ....

Now the docker image uses a wrapper script, there would be no custom path problem for docker users.

**Comment by wxiaoguang** [comment]
Now we have "WORK_PATH" in ini, the custom-path is based on the work-path by default

So I think this problem should have been resolved.

**Comment by 6543** [comment]
well it was about an installation via alpine package, and it's can also be solved by re-organizing the storage structure

**Comment by wxiaoguang** [comment]
work-path is a more general path than custom-path.

Setting it in app.ini could resolve most legacy path-related problems IMO.

Or, what's the real case you would like to deal with?

**Comment by 6543** [comment]
https://gitlab.alpinelinux.org/alpine/aports/-/blob/master/community/gitea/APKBUILD#L72

`/var/lib/gitea/`

**Comment by wxiaoguang** [comment]
I see. Maybe the best approach for setting the "custom-path" is `ln -s /my/custom /var/lib/gitea/custom` .....

Although after the "path refactoring", adding a CUSTOM_PATH into "app.ini" is quite easy, but I guess we don't want to make the config system that complex.
