### ISSUE TITLE
Unable to dump: Failed to dump database: no such column: email_notifications_preference

### ISSUE THREAD

**Issue by Ghardo** [go-gitea/gitea#10207]
Hello, 
i want to backup my gitea data but i get always this error:

```
Failed to dump database: no such column: email_notifications_preference
git@tools:~$ gitea dump -c /etc/gitea/app.ini
2020/02/10 14:21:35 ...dules/setting/git.go:91:newGit() [I] Git Version: 2.11.0
Failed to dump database: no such column: email_notifications_preference
```

I have updated my gitea version from 1.9.2
```
git@tools:~$ gitea -v
Gitea version 1.11.0+rc2-24-g9169b3945 built with GNU Make 4.1, go1.13.7 : bindata, sqlite, sqlite_unlock_notify
```

- Gitea version (or commit ref): gitea-1.11-linux-arm-6
- Git version: 2.11.0
- Operating system:  Raspbian GNU/Linux 9 (stretch) (lite version)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite

**Comment by Ghardo** [comment]
ok i fixed my problem with the migrate option but the sql contains no data only the structure

**Comment by guillep2k** [comment]
I think you attempted to dump your database using a 1.10.0+ executable before executing the upgrade process, since that column was added in #7813 and did not exist in 1.9.2.

You need to dump your database only with your current version, and _then_ upgrade.
