### ISSUE TITLE
You cannot delete repositories

### ISSUE THREAD

**Issue by bitchecker** [go-gitea/gitea#10205]
- Gitea version (or commit ref): `1.11`
- Git version: `2.18.2`
- Operating system: `Centos 8`
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
I noticed that you can create repositories but you can't delete them.

Going in:
`Settings -> Dangerous Zone -> Delete this repository`

a window will exit that should allow you to confirm your choice but this window disappears shortly after not giving, in fact, the possibility to confirm your choice.
...

## Screenshots

It is not possible to take screenshots because the window in question disappears about one second after its creation.

**Comment by 6543** [comment]
@bitchecker cant reproduce on try ... did you tryed another browser to make sure it is not a problem on your side?

**Comment by bitchecker** [comment]
Hi,
i've tryed with all browser that i've installed and it happens in my installation and on your demo site.

**Comment by adrian17** [comment]
(I also cannot reproduce this on try.gitea.io.)

**Comment by bitchecker** [comment]
so, if you create a new repository and then in the settings click on the delete button, the window works correctly and can you delete it?

**Comment by guillep2k** [comment]
Some kind of extreme ad blocking?

**Comment by guillep2k** [comment]
You say you're trying with 1.11, but that's not an actual version number (1.11.0rc2? 1.11.0 have been _just_ released moments ago). Could you please paste your page footer? e.g.:

```
© Gitea Version: 1.10.3 Page: 30ms Template: 29ms 
```

or

```
Powered by Gitea Version: 1.12.0+dev-276-g9789e0ad5 Page: 1ms Template: 1ms 
```

etc.

Also, check your browser's console in case some errors are showing up.

**Comment by bitchecker** [comment]
@guillep2k i've downloaded from [here](https://dl.gitea.io/gitea/1.11/) because it was the latest version available this morning.

**Comment by 6543** [comment]
this should be equivalent with 1.11.0 as only changelog got in befor tagging

**Comment by guillep2k** [comment]
I've just installed 1.11.0 in my production site. It's working as expected. I've created a repository, then deleted it no problem.

Please check your log files (paste anything relevant here), maybe there's some error message that will hints us what the problem is.

Also please check your browser's console and let us know if you find anything.

**Comment by bitchecker** [comment]
I installed the platform on a server in another network and it works properly.
I will investigate the malfunctioning of the instance in question, surely I will have to discuss with who put hands on the proxy.
