### ISSUE TITLE
Clicking on a milestone from global/assigned issues list results in HTTP 401

### ISSUE THREAD

**Issue by nodiscc** [go-gitea/gitea#10215]
- Gitea version (or commit ref): 1.11.0
- Git version: 2.11.0
- Operating system: Debian 10 
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

```
Feb  9 18:44:53 testhost gitea 2020/02/09 18:44:53 :0: [I] 10.0.0.1 - zerodb [09/Feb/2020:18:44:53 +0100] "GET /xsrv/xsrv/gitea/issues?q=&type=all&state=open&labels=&milestone=5&assignee= HTTP/1.1" 401 0 "\" \"Mozilla/5.0 (Windows NT 10.0; rv:68.0) Gecko/20100101 Firefox/68.0"
Feb  9 18:44:53 testhost apache testhost.xlt.lan 10.0.0.1 - - [09/Feb/2020:18:44:53 +0100] "GET /gitea/xsrv/xsrv/gitea/issues?q=&type=all&state=open&labels=&milestone=5&assignee= HTTP/1.1" 401 - "-" "Mozilla/5.0 (Windows NT 10.0; rv:68.0) Gecko/20100101 Firefox/68.0"
Feb  9 18:50:43 testhost gitea 2020/02/09 18:50:43 :0: [I] 10.0.0.1 - zerodb [09/Feb/2020:18:50:43 +0100] "GET /xsrv/xsrv/gitea/issues?q=&type=all&state=open&labels=&milestone=5&assignee= HTTP/1.1" 401 0 "\" \"Mozilla/5.0 (Windows NT 10.0; rv:68.0) Gecko/20100101 Firefox/68.0"
Feb  9 18:50:43 testhost apache testhost.xlt.lan 10.0.0.1 - - [09/Feb/2020:18:50:43 +0100] "GET /gitea/xsrv/xsrv/gitea/issues?q=&type=all&state=open&labels=&milestone=5&assignee= HTTP/1.1" 401 - "-" "Mozilla/5.0 (Windows NT 10.0; rv:68.0) Gecko/20100101 Firefox/68.0"
```

## Description

My gitea instance is available under `gitea/` in my virtualhost (https://testhost.xlt.lan/gitea). All links to milestones are working fine, _except_ when clicking on a milestone from the global issues list (eg. https://testhost.xlt.lan/gitea/issues?type=assigned&repo=0&sort=&state=open). As you can see in the log above, this link incorrectly inserts `gitea/` between the repository part of the URL and the `issues/` URL component.

For me clicking on this link results in a HTTP Basic auth prompt and a 401 error.

**Comment by zeripath** [comment]
@nodiscc is this still the case?

**Comment by nodiscc** [comment]
I think it is. Didn't want to reopen until I have some time to test again (this was a temporary Gitea instance, will probably redeploy this week), I'll keep you informed.

**Comment by nodiscc** [comment]
Sorry for being late, this is still on my radar, I have an unrelated issue preventing me from installing GItea, I will come back with updates ASAP.

**Comment by zeripath** [comment]
Appears these are both broken links really. They should just redirect to the milestones page.
