### ISSUE TITLE
Change location of respositories on file system

### ISSUE THREAD

**Issue by dsmaynard** [go-gitea/gitea#10212]
- Gitea version (or commit ref): 1.10.3
- Git version: 2.25.0
- Operating system: Arch 5.5.2
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X] No
  - [ ] Not relevant
- Log gist:

## Description

This should be a simple fix, but I am banging my head trying to change the default repository location to a separate partition. I though this would be as simple as changing the default location of ROOT = /var/lib/gitea/repos in /etc/gitea/appp.ini to the desired folder, but doing so gives me a 500 error whenever I try to create a new repo. I've also tried using a symbolic link from /var/lib/gitea/repos --> /new_partition/repos but this doesn't work either. I've made sure the owner & group are both gitea, along with the correct permissions, but no luck. 

Is there something I'm missing here, such as another setting in app.ini I need to change?

**Comment by 6543** [comment]
just look at the docs :)

-> https://docs.gitea.io/en-us/config-cheat-sheet/#repository-repository
```ini
[repository]
ROOT = /data/repos
```

**Comment by 6543** [comment]
@dsmaynard if you have more questions how to setup - just as on discord

**Comment by dsmaynard** [comment]
Like I said, I tried changing the ROOT to a new folder (using an absolute path), and I get an error when trying to create a repository. The only ROOT variable that allows me to create new repose is /data/repos.

**Comment by jolheiser** [comment]
Can you provide some logs from around the time of the 500 error?  
As well, did you restart Gitea after changing the config?

**Comment by dsmaynard** [comment]
After making changes I just issue the standard `# systemctl restart gitea.service` to save the changes, which seems to work as the log registers the changes to the ROOT directory. 

Here's the output of log, noting the permissions issue:
`2020/02/10 17:42:38 models/repo.go:1452:CreateRepository() [E] initRepository: InitRepository: mkdir /run/media/myarch/part_2: permission denied
2020/02/10 17:42:38 routers/repo/repo.go:149:handleCreateError() [E] CreatePost: delete repo directory jsmith/test_repo failed(2): open /run/media/myarch/part_2/gitea_repos/jsmith: permission denied`

Currently the r/w permissions are set to 755, and the group/owner for /run/media/myarch/part_2/ is set to gitea:gitea, as are all subdirectories/files. Is there a different owner I need to be using?

**Comment by jolheiser** [comment]
Is that the same as the user running Gitea in the systemd unit?

**Comment by dsmaynard** [comment]
I'm just following the owner and permissions for /var/lib/gitea/repos, which are owner = gitea, and permissions are 755, if that's what you mean.

**Comment by guillep2k** [comment]
```
/run/media/myarch/part_2/gitea_repos/jsmith
```
Is this on a permanent disk?

Try getting us the output of:
```
ps -ef | fgrep gitea
ls -ld /run/media/myarch/part_2/gitea_repos/jsmith
df -h /run/media/myarch/part_2/gitea_repos/jsmith
```

**Comment by dsmaynard** [comment]
This is a mounted ssd. Here's are the output of the commands (note the change in the mount point from the previous posts)

`$ ps -ef | fgrep gitea
gitea      62078       1  0 09:53 ?        00:00:00 /usr/bin/gitea web -c /etc/gitea/app.ini
jsm        62227   60903  0 09:55 pts/8    00:00:00 grep -F gitea
$ ls -ld /mnt/backup/gitea_repos/
drwxr-xr-x 2 gitea gitea 4096 Feb 10 17:38 /mnt/backup/gitea_repos/
$ df -h /mnt/backup/gitea_repos/
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda1       916G  3.8G  866G   1% /mnt/backup
`

**Comment by guillep2k** [comment]
A couple things you could do:

1. Make sure `/`, `/mnt` and `/mnt/backup` are searchable by the `gitea` user, normally via the `other` permissions group.
2. Impersonate the `gitea` user (`su - gitea` to ensure no credentials remain from your starting user) and manually try to create a file or folder in `/mnt/backup/gitea_repos/`.
3. As root, do: `chown -R gitea:gitea /mnt/backup/gitea_repos/` (assuming the group is also called `gitea`).
4. Finally, perform `mount | fgrep /mnt/backup` to check whether the file-system is mounted read-only or with some special flag I can't think of ATM.

**Comment by 6543** [comment]
@dsmaynard witch filesystem has the external disc - just an iteresting question witch come in my mind...

**Comment by guillep2k** [comment]
One more thing: make sure the new disk is mounted _before_ Gitea starts.

**Comment by 6543** [comment]
reopen
