### ISSUE TITLE
Inconsistent markdown rendering of review comments

### ISSUE THREAD

**Issue by adrian17** [go-gitea/gitea#10213]
- Gitea version (or commit ref): 1.11
- Git version: -
- Operating system: -
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes https://try.gitea.io/finrod_2002/testpullrequest/pulls/1#issuecomment-26037
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
When posting a code review with the review comment containing markdown, the markdown is rendered in the automatic email notification, but not in the web interface.

Web interface:
![Zrzut ekranu z 2020-02-10 17-21-52](https://user-images.githubusercontent.com/4729533/74168447-0c7bd180-4c2a-11ea-93eb-87b366b22652.png)

Email:
![Zrzut ekranu z 2020-02-10 17-21-16](https://user-images.githubusercontent.com/4729533/74168450-0e459500-4c2a-11ea-8c1c-a0b8b27cea10.png)

**Comment by mrsdizzie** [comment]
not stale will address in #11032

**Comment by mrsdizzie** [comment]
Fixed this in #11032
