### ISSUE TITLE
Possible visual bug: There is no margin between div elements anymore

### ISSUE THREAD

**Issue by proton-ab** [go-gitea/gitea#10210]
- Gitea version (or commit ref): 1.11.0
- Git version: -
- Operating system: -
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist: -

## Description
It seems that div elements are no longer separated with margin between them.

## Screenshots
![firefox_2020-02-10_15-30-37](https://user-images.githubusercontent.com/25139420/74158573-9a4fc080-4c1a-11ea-84e5-28327dd07f54.png)

![firefox_2020-02-10_15-33-12](https://user-images.githubusercontent.com/25139420/74158609-aa67a000-4c1a-11ea-8800-10ee8c34c2a2.png)

**Comment by zeripath** [comment]
I think this is also a duplicate but, again a good reminder that we never got this fixed after the move to fomantic

**Comment by silverwind** [comment]
Example for logged in users: https://try.gitea.io/user/settings

Seems like a underlying bug in Fomantic but I guess we can workaround:

````css
.ui.attached.segment + .ui.attached.header {
  margin-top: 1rem;
}
