### ISSUE TITLE
Labels popup list has no height limit, instead it expands total page height

### ISSUE THREAD

**Issue by proton-ab** [go-gitea/gitea#10218]
- Gitea version (or commit ref): 1.11.0
- Git version: -
- Operating system: -
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist: -

## Description
`div` element containing list of labels that pops out when assigning labels on issue is not contained by page, instead it expands page height. It should be limited to some sane height and contain scrollbar.

## Screenshots
![firefox_2020-02-10_21-52-02](https://user-images.githubusercontent.com/25139420/74189045-03056000-4c50-11ea-9785-1314fde7e2ec.png)

**Comment by jolheiser** [comment]
Possibly fixed by #10216

**Comment by proton-ab** [comment]
Should indeed be fixed by linked PR.

**Comment by silverwind** [comment]
Fix has landed.
