### ISSUE TITLE
getting error 500 when trying to transfer repo from user to organization 

### ISSUE THREAD

**Issue by zuhairamahdi** [go-gitea/gitea#10230]
- Gitea version (or commit ref): 1.9
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
when trying to transfer a repo from a user to an organization we get error 500 (this is not always the case) as we transferred between organizations before.
...

**Comment by 6543** [comment]
@zuhairamahdi i higly recomend to update gitea - can you test with 1.11.0 ?

**Comment by SonGokussj4** [comment]
Hi. I've got `1.11.0` (docker image) and the /repo/transfer through API is not in swagger and don't work at all with:

```
repo_data = {'new_owner': organization}
repo_headers = {'accept': 'application/json', 'content-type': 'application/json',
                'Authorization': 'token ACCESS_TOKEN'}
res = requests.post(
    f"{SERVER}/api/v1/repos/{username}/{reponame}/transfer?access_token={GITEA_TOKEN}",
    headers=repo_headers, json=repo_data)
```

When I tried latest (26d855b611b4154598b45c4ebc299b2d4c9ce03a47ef43d573cad8d109ed2387) version (I think 1.12.0-dev) it works just fine.

But the font was very bad so we're back on 1.11.0 for now.

**Comment by 6543** [comment]
@SonGokussj4 the repo/transfere API is a feature of 1.12.x

**Comment by hrvoj3e** [comment]
> @SonGokussj4 the repo/transfere API is a feature of 1.12.x

Thanks for the hint. 
https://github.com/go-gitea/gitea/pull/9947
