### ISSUE TITLE
[Feature] [API] export repo-language info

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#10232]
since #8037 created `LanguageStat`'s for each repo ... get this info via API too

**Comment by 6543** [comment]
github has:
* https://developer.github.com/v3/repos/#list-languages
and export main language via `"language": null,` json enty on repo-responce

**Comment by lafriks** [comment]
It's not really possible to do that currently as bytes for each language are not really saved to database only percentage

**Comment by lunny** [comment]
Why not that API display number of files or lines but bytes? Is that meaningful?

**Comment by lafriks** [comment]
Because percent is calculated without loading all file from git, just by detecting file size so that is faster as to detect line count
