### ISSUE TITLE
European Portuguese translation offer

### ISSUE THREAD

**Issue by emansije** [go-gitea/gitea#10233]
Hi!

I'd like to offer my services as a translator for the European Portuguese version of Gitea, which doesn't exist at the moment.

I tried sending a request to Thomas Boerger trough the Crowdin messaging system in December 21st but never got a reply, so I decided to make a request here.

Cheers!

**Comment by guillep2k** [comment]
Hi, please contact us via our [Discord channel](https://discord.gg/dGerEs).

**Comment by emansije** [comment]
I get an error message stating that the invitation is invalid. Did it expire?

**Comment by guillep2k** [comment]
Try this (#translations): https://discordapp.com/channels/322538954119184384/327742346009640961

**Comment by 6543** [comment]
Added

**Comment by 6543** [comment]
https://crowdin.com/project/gitea/pt-PT

-> issue can be closed
