### ISSUE TITLE
IIS Reverse Proxy URL with a plus symbol results in 404

### ISSUE THREAD

**Issue by iamdoubz** [go-gitea/gitea#10236]
- Gitea version (or commit ref): **1.11.0+2-g8efd6b32e**
- Git version: **Git-Scm v2.25.0.windows.1**
- Operating system: **Windows Server 2012 R2**
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant (Windows host/IIS Reverse Proxy vs. Unix host)
- Log gist: Not Available

## Description

If there is a file in repo that contains a "+" symbol, the path will not be found, and will result in an IIS 404, _not_ a Gitea 404. If you rename the file to have an underscore in place of the plus sign (rename the file and `git push`), the file will download just fine.

## Example

I want to download a file located at `https://git.my.domain/username/Gitea4Windows/media/branch/master/v1.12/1.12.0+dev-283-gad2642a8a.7z`. It will result in IIS 404, _not_ a Gitea 404 screen. If the file was named `1.12.0_dev-283-gad2642a8a.7z`, the file would start downloading as expected.

## Screenshots

N/A

### Likely culprit

* How IIS determines the URL string with a "+" symbol in the URL string.

## Other

Gitea was compiled with/using the following:

1. Go v1.13.7 ([DL](https://golang.org/dl/))
2. Gnumake v4.3 ([DL](https://github.com/mbuilov/gnumake-windows))
3. Nodejs v13.8.0 ([DL](https://nodejs.org/en/download/current/))
4. Npm v6.13.6 (Included with Nodejs)
5. Git-Scm v2.25.0.windows.1 ([DL](https://git-scm.com/downloads))

* Compiled from source and built using `git clone https://github.com/go-gitea/gitea.git&&git checkout release/v1.11&&TAGS="bindata sqlite sqlite_unlock_notify" make build`
* IIS reverse proxy to localhost on custom port

Just looking for guidance on how to maybe URL escape this if it is an IIS issue.

**Comment by proton-ab** [comment]
Check https://docs.microsoft.com/en-us/iis/configuration/system.webserver/security/requestfiltering/#attributes

> **allowDoubleEscaping**
If set to true, request filtering will allow URLs with doubly-escaped characters. If set to false, request filtering will deny the request if characters that have been escaped twice are present in URLs.

**Comment by iamdoubz** [comment]
> Check https://docs.microsoft.com/en-us/iis/configuration/system.webserver/security/requestfiltering/#attributes
> 
> > **allowDoubleEscaping**
> > If set to true, request filtering will allow URLs with doubly-escaped characters. If set to false, request filtering will deny the request if characters that have been escaped twice are present in URLs.

Amazing! Once I checked this box, the file with the "+" downloaded. Thank you for your help @proton-ab and for always reminding me to ~~RTFM~~ RTM. 🤦‍♂ 

| ![image](https://user-images.githubusercontent.com/4871781/74289424-a740e280-4cf4-11ea-8183-fb6270b13a01.png) |
| :--: |
| **Figure 1** |
