### ISSUE TITLE
Browser's Popup Shown on editing issue title

### ISSUE THREAD

**Issue by jaqra** [go-gitea/gitea#10250]
For me in 2 cases popup shown.

1. ~~If there is a private submodule in mirror repo~~ [ConfuserEx](https://github.com/mkaring/ConfuserEx)
2. When edit issue's title. But in this case popup closing immediately

![gitea](https://user-images.githubusercontent.com/48099350/74325867-6c918580-4d9a-11ea-9f1e-b0665cf36532.png)

Edit: First case is not about private submodule
Edit 2: First case is solved on #10515 thanks @zeripath

**Comment by proton-ab** [comment]
This is caused by browser sending `POST` instead of `GET` to page after submitting form via XHR.
![Fiddler_2020-02-12_11-54-43](https://user-images.githubusercontent.com/25139420/74328812-e1f75900-4d8e-11ea-9825-6f19401a2843.png)

**Comment by jaqra** [comment]
and also second problem looks like solved. i am going to close this
