### ISSUE TITLE
Master to master replica 

### ISSUE THREAD

**Issue by Hemanthdev** [go-gitea/gitea#10259]
Master to master replication is available for gitea.

Please guide me on this setup document

**Comment by lunny** [comment]
Please give more detail.

**Comment by Hemanthdev** [comment]
We are having the 3 office. So will will install gitea in 3 office.
 We need to replication all 3 server to each other...

1 office people will connect to 1 server -- Gitea Master1.
2 office people will connect to 2 server --  Gitea Master2
3 office people will connect to  server 3 --  Gitea Master3.

Or 

all will connect to Gitea Master1 to push the code.they will pull repo for local server.

**Comment by lunny** [comment]
Why not share the same Gitea server?

**Comment by lafriks** [comment]
Gitea does not support clustering currently

**Comment by Hemanthdev** [comment]
kubernetes clustering  will work or anyother option.

3 office will connect via VPN

**Comment by lafriks** [comment]
Kibernates cluster will not work either currently

**Comment by Hemanthdev** [comment]
> Why not share the same Gitea server?

This will impact the internet bandwidth to another office.
In each office, the employer is more 150+
