### ISSUE TITLE
Embedded command doesn't work; starts the web server instead.

### ISSUE THREAD

**Issue by boughtonp** [go-gitea/gitea#10254]
- Gitea version: gitea-1.11.0-windows-4.0-amd64.exe from [releases](https://github.com/go-gitea/gitea/releases) page.

I've just been trying to figure out why the functionality documented at https://docs.gitea.io/en-us/cmd-embedded/ doesn't work on the copy of Gitea I just downloaded.

Instead of responding as the page suggests, it launches Gitea as if the "web" command was given.

Based on #9982 it seems the reason is because the embedded command functionality only exists on the unreleased 1.12 branch.

So two bugs:
* The website should be referring to the currently released version.
* Unknown commands should not start the server, they should return an appropriate error, (plus a reference to using --help to check supported commands).

And a question:
How does one get the equivalent of `gitea embedded extract --custom --rename` with the currently released Gitea v1.11?

**Comment by techknowlogick** [comment]
Embedded CLI doesn't work in 1.11, it was added 1.12. As for versioning docs there is another ticket opened for that.

If you would like embedded CLI option to work in 1.11 you would need to manually backport that PR into the release/v1.11 branch and build from source.
