### ISSUE TITLE
reverse proxy/serve static files

### ISSUE THREAD

**Issue by esosan** [go-gitea/gitea#10262]
- Gitea version (or commit ref): 1.11.0
- Operating system: Linux 
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite

## Description

I’m trying the new feature for reverse proxy and serve static files. All work as expected but I think something is missing on the Public dir. Lot’s of missing files.

On the 10.1.3 the same folder seems to be more complete.

**Comment by jolheiser** [comment]
Our static files are now generated via webpack.
`make webpack` should generate the appropriate files.

**Comment by esosan** [comment]
Ok. It’s not specified in documentation.

Thank you

**Comment by 6543** [comment]
@esosan in witch place of the docu do you look at / do you expect this info?

**Comment by esosan** [comment]
https://docs.gitea.io/en-us/reverse-proxies/

> Download a snap shot of the gitea source repository to /path/to/gitea/.
We are only interested in the public/ directory and you can delete the rest.

**Comment by esosan** [comment]
@gary-kim are you sure with the `make webpack` command?

I just cloned the repository, with this command and I have this error:

`make: *** No rule to make target 'webpack'.  Stop`

According whit the `make —help` I have try:
`make generate`
and the public directory now look good. 

But I’m not sure this is the right step to do.

**Comment by jolheiser** [comment]
In `1.11` and master it exists. 
https://github.com/go-gitea/gitea/blob/a97fe76950bf69ca71c9b790e8d0e76d5e870235/Makefile#L114

In `1.10.x` it would be `make generate`
