### ISSUE TITLE
.docx file can't use pull request

### ISSUE THREAD

**Issue by GuoQiXiaoMing** [go-gitea/gitea#10268]
- Gitea version (or commit ref):1.12.0+dev-213-gf29c30104
- Git version:2.24.0.windows.2
- Operating system:windows
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

change any docx file, than push to "xxx" branch.

use pull requests to merge from "xxx" to master branch.

report this:
   "This pull request has changes conflicting with the target branch.
testdoc.docx"

can't resolve, and didn't show conflict at local.

## Screenshots

![image](https://user-images.githubusercontent.com/58553709/74505011-f4a99380-4f30-11ea-9475-f40822281f51.png)

**Comment by 6543** [comment]
@GuoQiXiaoMing just merge master into your feature-branch or rebase it localy

**Comment by 6543** [comment]
By the way it's a bad idear to work with docx and git since git thinks of it as binary - to store it once it should make no problems but working with doc(x) on git in combination with pull requests is torture
