### ISSUE TITLE
Double activity entry

### ISSUE THREAD

**Issue by vanvanni** [go-gitea/gitea#10264]
- Gitea version (or commit ref): V1.11.0
- Git version: 2.17.1
- Operating system: Ubuntu 18.04.4 LTS (GNU/Linux 4.15.0-76-generic x86_64)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description
Creation of a repo has a double activity entry

## Screenshots

![image](https://user-images.githubusercontent.com/13612647/74476344-6e963a00-4ea9-11ea-8ef1-7a6665ab31f6.png)

**Comment by jolheiser** [comment]
I cannot re-create this on try or with a fresh `1.11.0` build.

Can you provide logs if there is anything of interest?  
As well, how are you creating the repositories? Just the web UI?

For two actions to be pushed to the DB at the same time, it's almost like there's more than one instance of Gitea running, though I'm not sure how they would both overlap without some error.

**Comment by xJoeyv** [comment]
> I cannot re-create this on try or with a fresh `1.11.0` build.
> 
> Can you provide logs if there is anything of interest?
> As well, how are you creating the repositories? Just the web UI?
> 
> For two actions to be pushed to the DB at the same time, it's almost like there's more than one instance of Gitea running, though I'm not sure how they would both overlap without some error.

I have searched the logs but they where cleared since I was playing with log rotation, have my server has been rebooted it has been solved. I cannot trace the cause. I will keep track of this and post when it occurs again
