### ISSUE TITLE
Memory usage grows without bound with a single repository

### ISSUE THREAD

**Issue by fetchinson** [go-gitea/gitea#10275]
- Gitea version (or commit ref): 1.10.3.
- Git version: 2.24.0.
- Operating system: CentOS Linux release 7.7.1908 (Core)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

I installed gitea on a shared host (hosted by webfaction in case somebody has experience with them) and so far have only one 450MB repository. There are only 4 users and only 1 of them committed anything. So we are in test mode at the moment, no heavy usage of any sort. Nevertheless the memory usage regularly goes up to 2.5GB at which point the hosting company kills the process :( This happens every 2-3 days, it looks like ever since the process gets started memory consumption just keeps growing monotonically.

Based on comments here on the issue tracker I switched to 'file' sessions but the same thing keeps happening.

Here is my app.ini:

```
APP_NAME = blabla
RUN_MODE = dev

[server]
HTTP_ADDR = 127.0.0.1
HTTP_PORT = 26888
DOMAIN    = blabla.example.com
ROOT_URL  = http://blabla.example.com/

[database]
DB_TYPE = sqlite3

[repository]
ROOT            = /path/to/repos
DEFAULT_PRIVATE = private

[security]
INSTALL_LOCK   = true
INTERNAL_TOKEN = blabla

[service]
DISABLE_REGISTRATION = true
REQUIRE_SIGNIN_VIEW = true

[oauth2]
JWT_SECRET = blabla

[session]
PROVIDER = file
PROVIDER_CONFIG = /path/to/data/sessions
GC_INTERVAL_TIME = 172800
SESSION_LIFE_TIME = 604800

```

If there is any more useful info I should send please let me know.

**Comment by zeripath** [comment]
Are there big diffs being generated or reviewed?

**Comment by lunny** [comment]
Some questions:
- [ ] Are you enabled cache system? Could you test to disable that?
- [ ] Are you enabled repo indexer? Could you test to disable that?
