### ISSUE TITLE
[Documentation] Add List of Template Options

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [go-gitea/gitea#10278]
### My problem

I am tweaking some templates so that I can see in depth license information. It seems to me the best way to do this would have the server figure it out via templating (rather than using javascript to parse the license and compare it to all other possible known license). I couldn't find anything helpful regarding templating in docs.gitea.io. Searching the gitea repo for licenses return 1655 results (919 in go) and template returns 372 results (75 in go). 

### Potential Solution

I think moving forward it would be helpful for those in the community who are interested in tweaking the way gitea looks if all template values provided by gitea were detailed in the documentation.

**Comment by Th3Whit3Wolf** [comment]
I think I found the bit I was looking for

```html
<p>{{.i18n.Tr "repo.license"}}</p>
```

but it outputs License

I am using a MIT license for the repository

**Comment by bagasme** [comment]
Perhaps like this?

![GH](https://user-images.githubusercontent.com/40219486/74652824-7ad80b00-51b9-11ea-9c4a-96fae28dfdc8.png)

**Comment by Th3Whit3Wolf** [comment]
That would be cool too. I am aiming to have something like Github's repo License page has.

**Comment by guillep2k** [comment]
```
<p>{{.i18n.Tr "repo.license"}}</p>
```
That piece of code means _"display the translated resource named 'repo.license' from the language files"_. `.18n.Tr` is the name of the translation function. If you were using Gitea in Spanish you would have got "Licencia".

When you create a repository you are given the option of choosing a license template (e.g. `MIT`); the license you choose is only used to initialize the git contents of the repository, and AFAIK is not stored anywhere else.

**Comment by Th3Whit3Wolf** [comment]
That's a bummer. I guess I would need to write the javascript to parse the file then.

**Comment by guillep2k** [comment]
Closing this as question was answered.
