### ISSUE TITLE
Config Cheat Sheet: Example for repo health check schedule seems to be wrong

### ISSUE THREAD

**Issue by neingeist** [go-gitea/gitea#10274]
## Description
The Config Cheat Sheets says the default for `[cron.repo_health_check]`'s `SCHEDULE` is `every 24h`, but I think it is `@every 24h` (note the at sign). [app.ini.sample](https://github.com/go-gitea/gitea/blob/master/custom/conf/app.ini.sample) also has the at sign.

**Comment by lafriks** [comment]
Can you please send PR to fix it?
