### ISSUE TITLE
User's Email will turn lower case automatically

### ISSUE THREAD

**Issue by prosopa** [go-gitea/gitea#10279]
- Gitea version (or commit ref): 1.11
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
When the user email contains capital letter, e.g. `BugHere@example.com`, Gitea will turn all capital letter to lower case, e.g. `bughere@example.com`
...

## Screenshots
Setting Email as `BugHere@example.com`
![圖片](https://user-images.githubusercontent.com/8914663/74584397-d31dda00-500c-11ea-8643-616d065f4fc2.png)

Result
![圖片](https://user-images.githubusercontent.com/8914663/74584382-a8cc1c80-500c-11ea-8e24-d33959e7ec66.png)

**Comment by davidsvantesson** [comment]
It is done to ensure not two registrations can be done with same email addresses. I think all mail servers/hosts treat full email address case insensitive.

**Comment by prosopa** [comment]
A little bit strange to the user.
Why not doing duplication check "background"?
I mean, just show what they are typed.

**Comment by lunny** [comment]
I think this should be a bug. We should add a new lower_email column to ensure the unique email address.

**Comment by lafriks** [comment]
I don't think it is bug as email addresses are case insensitive so I don't really see problem in lower-casing email addresses

**Comment by lafriks** [comment]
They may be but to be honest I have not seen SMTP server that would treat User@example.com and user@example.com as different email addresses. In practice you can write email address in any casing combinations and it will be delivered to same user account. Problem from security perspective is that we could end up having user with the same email address otherwise
