### ISSUE TITLE
Times API breaks after deleting repo containing issues with tracked times

### ISSUE THREAD

**Issue by bobemoe** [go-gitea/gitea#10280]
- Gitea version (or commit ref): 1.12.0+dev-307-g62a1322cf
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant

## Description

After deleting a repo the times API has become unusable:

```bash
$ curl -X GET "https://bobemoe:xxxx@try.gitea.io/api/v1/user/times" -H  "accept: application/json"
{"message":"issue does not exist [id: 9010, repo_id: 0, index: 0]","url":"https://try.gitea.io/api/swagger"}
```

I've checked the DB and indeed the `issue` records for the deleted repo have been deleted but there are still records in the `tracked_time` table that now have a non-existent `issue_id`:

```sql
mysql> select t.*,i.id from tracked_time t left join issue i on t.issue_id=i.id having i.id is null;
+----+----------+---------+--------------+-------+---------+------+
| id | issue_id | user_id | created_unix | time  | deleted | id   |
+----+----------+---------+--------------+-------+---------+------+
|  3 |     1361 |       1 |   1571125831 |  3600 |       0 | NULL |
|  4 |     1361 |       1 |   1571125838 |  1500 |       0 | NULL |
....
```

**Comment by 6543** [comment]
so on repoDeletion we have to delete tracked_time too

**Comment by bobemoe** [comment]
Still an issue, confirmed on try.gitea.io

**Comment by 6543** [comment]
I'll have a loom at it

**Comment by 6543** [comment]
ok Idear:
 * fix `models.DeleteRepository()`
 * add a task to `gitea doctor` witch check general DB consistency

**Comment by 6543** [comment]
@bobemoe -> #11110 & #11111
