### ISSUE TITLE
Add webhooks for GitKraken Glo

### ISSUE THREAD

**Issue by Terbium-135** [go-gitea/gitea#10288]
Improvement:
I like to see gitea being enabled to talk to gitkraken glo.
Especially since gitea is not supporting any project/kanban board (at leaqst to my knowledge

**Comment by bobemoe** [comment]
There is a Kanban being developed, very close to completion: https://github.com/go-gitea/gitea/pull/8346

But I'm sure more webhook support would still be good :)
