### ISSUE TITLE
FTP/ftps protocol support

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#10289]
I propose that gitea could add ftp/ftps protocol support. So that you can explore files(default branch) via ftp clients and download/put/delete files.

We could implement this feature via https://goftp.io/server and I'm the author of that library. We need to implement an interface Driver via gitea.

* Explore
- [ ] You can login the ftp/ftps via your username/password of gitea instance.
- [ ] When login succeed, and explore the path `/`, it will list all the users or orgniziations you have access permissions.
- [ ] When enter the username/orgniziation, it will list all the repositories you have access permissions on this username/orgniziation.
- [ ] When enter the repository, it will list the repository's first class directory of default branch. If the repository is empty, nothing will be displayed.

* Download
- [ ] When download from `/`, all repositories user have permission will be download.
- [ ] When download from users or orgniziation directory, all repositories of this user/orgniziation will be download.
- [ ] When download from a respository, the default branch tree files will be downloaded.
- [ ] When download from a subtree of a repository, the sub directory will be downloaded.

* Mkdir
- [ ] When mkdir on `/`, an orgnization will be created.
- [ ] When mkdir on a user/orgniziation, an empty repository will be created.
- [ ] When mkdir on a repository, a directory with a empty file `.gitkeep` will be created and the file will be hidden from ftp view.

* Upload
- [ ] When upload a file on `/` or user/orgniziation will return error.
- [ ] When upload a file on an empty repository, the repository will be initilized a master branch and save the file.
- [ ] When upload a file on an exist repository, the file will be added to default branch.

* Delete
- [ ] `/` cannot be deleted
- [ ] delete user/orgniziation direcotry, it will delete a user or an orgniziation
- [ ] delete a file or directory on a repository, it will delete the file/directory on the repository's default branch.

**Comment by sapk** [comment]
It could come handy but I would suggest to be separate to gitea main process like a proxy that leverage gitea api (maybe even internal api).
