### ISSUE TITLE
Garbage-Collection not working

### ISSUE THREAD

**Issue by somera** [go-gitea/gitea#10299]
- Gitea version (or commit ref): 1.11.0+10-gf9e66e5a4
- Git version: 2.20.1
- Operating system: Linux pi-manager 4.19.97-v7l+ #1294 SMP Thu Jan 30 13:21:14 GMT 2020 armv7l GNU/Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description

Im starting GC in the admin dashboard ("Garbage-Collection auf Repositories ausführen"). I'm hosting 929 repositories. After start this operation I see on the monitoring page, that GC is running. But after some time the admin dashboard shows

`Repository garbage collection failed: Error: context deadline exceeded`

...

## Screenshots

![image](https://user-images.githubusercontent.com/8334250/74608796-7392fd80-50e4-11ea-9b15-c358c9268c27.png)

**Comment by lunny** [comment]
We should give a different context from the default so that it has a longer timeout.

**Comment by somera** [comment]
Or run it in background withot any timeout.

**Comment by aswild** [comment]
`git gc` and `git fsck` can take a very long time to run, often several minutes, and they should be done in the background rather than between page loads.

I've done a basic implementation on my fork (https://github.com/aswild/gitea/commit/7db9db3cd3fbb538fe3c4f62a5b2520187b7854c) though it could be enhanced by firing a System Notice when complete.

**Comment by somera** [comment]
How is the status here? My hope war to get this in 1.12.0

**Comment by jolheiser** [comment]
This was reported as fixed by https://github.com/go-gitea/gitea/pull/10745

**Comment by somera** [comment]
I've tested it with 1.12.0

```
2020/06/18 23:16:11 .../repository/check.go:87:func1() [E] Repository garbage collection failed for &{6 1 gitea_admin <nil> darktable darktable   0  master 1 1 0 0 0 0 0 0 0 0 0 0 false false false true <nil> 0 map[] map[] [] <nil> false 0 <nil> false 0 <nil> 805148937 <nil> <nil> true false []  1568914924 1592466363}. Stdout:
        Error: context deadline exceeded
2020/06/18 23:16:11 ...m.io/xorm/core/db.go:277:ExecContext() [I] [SQL] INSERT INTO `notice` (`type`,`description`,`created_unix`) VALUES (?, ?, ?) [1 Repository garbage collection failed for /home/git/gitea-repositories/gitea_admin/darktable.git. Stdout:
        Error: context deadline exceeded 1592514971] - 57.066786ms
2020/06/18 23:16:11 ...m.io/xorm/core/db.go:277:ExecContext() [I] [SQL] INSERT INTO `notice` (`type`,`description`,`created_unix`) VALUES (?, ?, ?) [2 Error in Task: Garbage collect all repositories: Repository garbage collection failed in repo: gitea_admin/darktable: Error: <nil> 1592514971] - 12.903651ms
```

**Comment by zeripath** [comment]
@somera did you adjust the settings in https://docs.gitea.io/en-us/config-cheat-sheet/#cron---repository-health-check-cronrepo_health_check

**Comment by somera** [comment]
> @somera did you adjust the settings in https://docs.gitea.io/en-us/config-cheat-sheet/#cron---repository-health-check-cronrepo_health_check

I tested this in 1.12.x. And it works if I set the timeout higher. Thx!
