### ISSUE TITLE
how to update to the newest version

### ISSUE THREAD

**Issue by ltbyun** [go-gitea/gitea#10307]
- Gitea version (or commit ref):
- Git version:1.8.3
- Operating system:ubuntu18.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
my gitea is deployed by docker, and i can't find a way to upgrade to the newest version.
no docs about upgrade can find from docker page or from site https://docs.gitea.io/zh-cn/
...

**Comment by jolheiser** [comment]
Try the [english docs](https://docs.gitea.io/en-us/install-with-docker/), as our documentation isn't very up-to-date in other languages. :slightly_frowning_face:
