### ISSUE TITLE
Github API deprecation of access_token

### ISSUE THREAD

**Issue by kolaente** [go-gitea/gitea#10308]
I got an email from Github:

> Hi @kolaente,
> 
> On February 15th, 2020 at 09:04 (UTC) your application (Kolaente's git-server) used an access token (with the User-Agent Go-http-client/1.1) as part of a query parameter to access an endpoint through the GitHub API:
> 
> https://api.github.com/user
> 
> Please use the Authorization HTTP header instead as using the `access_token` query parameter is deprecated.
> 
> Depending on your API usage, we'll be sending you this email reminder on a monthly basis.
> 
> Visit https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param for more information about suggested workarounds and removal dates.
> 

I have set up my gitea instance so that people can use their github login to authenticate. If Github changes their api, this would need patching. Not sure though if it is only a third-party library we're using for this or if this is pure Gitea code.

**Comment by techknowlogick** [comment]
Thanks for the report. We've been getting these emails too. Just waiting on https://github.com/markbates/goth/pull/314 to get merged.

**Comment by techknowlogick** [comment]
closed with #10444
