### ISSUE TITLE
Instance GPG key not recognized if subkey 

### ISSUE THREAD

**Issue by cleverer** [go-gitea/gitea#10309]
- Gitea version (or commit ref): 1.11.0
- Git version: 2.17.2
- Operating system: macOS 10.13.6 (17G11023)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description
Regarding the new signing functionality introduced in #7631

Gitea only checks for the primary key when checking a commit with gpgSettings:
https://github.com/go-gitea/gitea/blob/master/models/gpg_key.go#L738-L742
If one uses a subkey to sign, this doesn't get recognized in the GUI.

## Screenshots
<img width="1143" alt="Bildschirmfoto 2020-02-17 um 08 40 17" src="https://user-images.githubusercontent.com/1735317/74633075-21dc8880-5161-11ea-970d-3b9412a05dc4.png">

**Comment by lunny** [comment]
@cleverer Could you confirm the old gitea version worked?

**Comment by cleverer** [comment]
That wouldn't make sense, as the possibility of signed merge commits, repository creations etc. was only introduced in 1.11.0.

I'm not talking about a manually signed commit but a commit automatically created and signed from the GUI.

**Comment by cleverer** [comment]
Bad bot. Could a member please reopen this?

Is there anything I can do to help get this resolved?

**Comment by b90g** [comment]
I use subkeys successfully but had issues at the beginning, i had to add the email address of the gpg key also to the account and verify it.

**Comment by zeripath** [comment]
@b90g can you put an example up on try.gitea.io?

**Comment by zeripath** [comment]
(I'm currently working on GPG verification again - so if I can get an example I can get this fixed and backported in to 1.12 PDQ.)

**Comment by b90g** [comment]
https://try.gitea.io/klaus/lhmmm

```
REDACTED@REDACTED.TDL
Key ID: REDACTEDHASH Subkeys: REDACTEDHASH REDCATEDHASH
Added on May 30, 2020 - Valid forever 
```

feel free to request more interaction (altough a lot of requests fail torwards try.gitea.io  from bad gateway to 404..)

**Comment by cleverer** [comment]
To clarify, regular git commits signed with a subkey work just fine. However you can set up Gitea so it signs commits done on the web (eg. when merging or creating a new repo).

If you configure your gitea with a subkey the verification fails. If you pull that repository and check locally with the correct public key, everything is fine.

I think the problem lies somewhere [here](https://github.com/go-gitea/gitea/blob/1f01f53c53ea75634f981611635be49c69e1920b/models/gpg_key.go#L738-L748). I think the parsing of the key doesn't work with subkeys somehow. However I'm not too familiar with Go, so I might be wrong…

**Comment by zeripath** [comment]
Hi!

So that appears to be matching and verifying fine on try

**Comment by zeripath** [comment]
@cleverer could you give me the commands used to create the subkey so I can try to repeat your problem?

**Comment by zeripath** [comment]
Ah figured it out!

**Comment by cleverer** [comment]
👍 Let me know if you still need the instructions or some help in other form! (I think I originally created the subkeys in GPG Keychain for mac, so not sure about the specific commands right now).

#11713 looks very promising though!

**Comment by zeripath** [comment]
If you could have a go with it and confirm it fixes your issue that would be good

**Comment by cleverer** [comment]
I can try to get the PR running tomorrow, but I can't promise anything, I haven't set up a gitea dev-environment and am not really familiar with Go (yet).

Thanks a lot for your effort though!

**Comment by cleverer** [comment]
I can confirm, it works like a charm! Thanks a lot!
