### ISSUE TITLE
Don't Require Login for Specific Milestones

### ISSUE THREAD

**Issue by bagasme** [go-gitea/gitea#10312]
## Description

From Discord:

```
Is it possible to configure Gitea so that Milestone pages don't require login? (for example, https://git.semicolin.games/semicolin/sneak/milestone/2 is a public repository, but you need to be logged in to see the milestone page.) It seems that by default, a not-logged-in user can see the /milestones page, and even which Issues are in which milestones, but not the page corresponding to a specific milestone.
```
Extend pages visible to non-logged-in users into specific milestone pages.
```

**Comment by kevans91** [comment]
+1, this seems like a sensible change; I'll look at fixing this if no one else is in the process of doing so.

**Comment by techknowlogick** [comment]
This is indeed sensible, however I think we should do it like github where the list of issues/PRs assigned to a milestone can be seen in the standard issues/PRs list page (ex. https://try.gitea.io/Etzelia/Test1/pulls?q=&type=all&state=open&labels=&milestone=893&assignee=0 )

**Comment by kevans91** [comment]
> This is indeed sensible, however I think we should do it like github where the list of issues/PRs assigned to a milestone can be seen in the standard issues/PRs list page (ex. https://try.gitea.io/Etzelia/Test1/pulls?q=&type=all&state=open&labels=&milestone=893&assignee=0 )

I'm afraid I'm being a bit dense here, I don't quite follow -- this example seems to already match github behavior, both allowing one to filter standard issues/PRs by milestone and displaying them in the subheading/metadata(?) area just below the title.

**Comment by techknowlogick** [comment]
@kevans91 woops. I am the dense one. Please ignore my comment above.

**Comment by kevans91** [comment]
@techknowlogick OK, phew; :-)
