### ISSUE TITLE
Embedded images not displayed in review comments

### ISSUE THREAD

**Issue by adrian17** [go-gitea/gitea#10339]
- Gitea version (or commit ref): 1.12.0+dev-331-g21e771c41
- Git version: -
- Operating system: -
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes: https://try.gitea.io/testacc1777/test-pr-with-branch-good/pulls/1
  - [ ] No
  - [ ] Not relevant

## Description
The review editor allows embedding images; however, when I submit the review, the image doesn't actually appear in the review window.

## Screenshots
![Zrzut ekranu z 2020-02-18 16-52-56](https://user-images.githubusercontent.com/4729533/74753372-53904500-5270-11ea-819a-a99107d0dace.png)

**Comment by adrian17** [comment]
That's not a proposal, that's a bug. The review editor has a button that explicitly says "insert image", but after using it, the review doesn't actually have any image inserted; there's just raw markdown instead.

**Comment by lafriks** [comment]
Yeah but that'd tricky one to display in current ui

**Comment by alexanderadam** [comment]
Isn't a tricky bug still a bug? :thinking:

**Comment by zeripath** [comment]
The answer is to then surely to just remove the insert image button ?

**Comment by fnetX** [comment]
This issue is probably about the fact, that the upload URL is not known before creating the issue? If it's not possible to upload the images immediately like GitHub does or reserving an ID for them, why not use a placeholder, like inserting an image as
~~~
![](userupload_1)
~~~
and replacing the URL upon saving.

**Comment by fnetX** [comment]
Guys, adding images works fine, but the URL in the OP is *not* an image but this Wikipedia hashtag when you open that popover view. I think there is no bug here (and my last comment is offtopic and for another matter that was most likely linked by mistake: https://codeberg.org/Codeberg/Community/issues/9#issuecomment-49466 )

@adrian17 can you confirm that this works just fine if you use the actual image url https://upload.wikimedia.org/wikipedia/commons/b/b8/Ipod_linux_booting_kernel.jpg instead?

**Comment by wxiaoguang** [comment]
The review editor could support images. Feel free to reopen if there is a problem.

![image](https://user-images.githubusercontent.com/2114189/234349899-0a48f8c6-8c10-4f08-9f3a-960b3626549c.png)
