### ISSUE TITLE
[Feature] support disable repository programing language Detection

### ISSUE THREAD

**Issue by ddatsh** [go-gitea/gitea#10335]
as title

**Comment by lafriks** [comment]
Any reason/use case on why?

**Comment by guillep2k** [comment]
Related: https://github.com/go-gitea/gitea/issues/7953

**Comment by lunny** [comment]
@lafriks Because they have small memory and don't think this feature is necessary. but have many big repo. And this feature spend many memory. 

I also think this feature is just useful for public gitea instances or big enterprise gitea instances.

**Comment by lunny** [comment]
> Related: #7953

No. That's not the same case. One is for UI language and this one is for repositories' programing languages detection.

**Comment by silverwind** [comment]
Should be per-repo. I think supporting the [linguist gitattributes](https://github.com/github/linguist#using-gitattributes) is probably a good idea which probably makes this an upstream issue.

**Comment by 6543** [comment]
upstream issue: https://github.com/src-d/enry/issues/18

**Comment by silverwind** [comment]
Copying my info from the other issue:

---

[linguist](https://github.com/github/linguist#using-gitattributes) supports various gitattributes to affect the language stats, I think we should too.

- `linguist-generated` or maybe just `generated` for generated code
- `linguist-vendored` or maybe just `vendored` for vendored code
- `linguist-language` or maybe just `language` to override detected language

Both have the effect that matching files will be excluded from language stats.

There's more but I think these two are the most commonly used ones.

**Comment by yurenchen000** [comment]
> Any reason/use case on why?

Sometimes it gets wrong language, 
maybe it is better to manually specify the value or disable it than the wrong value

**Comment by delvh** [comment]
You can use the `.gitattributes` to configure what file type gets what highlighter, if one type is consistently mis-recognized.

**Comment by yurenchen000** [comment]
> You can use the `.gitattributes` to configure what file (type) gets what highlighter.

@delvh 
thanks for your reply.

I want to Specify or Disable the language type here (in Repositories list page)
I wonder if this is possible?

![gitea_lang_type](https://user-images.githubusercontent.com/8458213/222925454-81e4a822-ce1c-45c8-b4ca-a2512f98e7ef.png)

**Comment by delvh** [comment]
Ah, you mean the global one.
Hmm…
Does https://github.com/github/linguist/blob/master/docs/overrides.md perhaps help?
I think `-linguist-detectable` or `linguist-documentation` sounds promising.

**Comment by yurenchen000** [comment]
@delvh 
Thanks for your patience, I'll try this doc.

I temporarily use sql to modify the database:

```sql
-- change one commit
update language_stat set language='Markdown'  where id=THE_ID;

-- or change all commits in one repo
update language_stat set language='Markdown'  where repo_id=THE_REPO_ID;
```

**Comment by silverwind** [comment]
I doubt we support all `linguist-*` attributes yet, but we do at least support some like `linguist-language`.

**Comment by silverwind** [comment]
`linguist-language` is supported since a while ago.
