### ISSUE TITLE
Long lines in review editor cause the window width to go past the screen edge

### ISSUE THREAD

**Issue by adrian17** [go-gitea/gitea#10338]
- Gitea version (or commit ref): 1.12.0+dev-331-g21e771c41
- Git version: -
- Operating system: -
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes
  - [ ] No
  - [ ] Not relevant

## Description

When you enter a long line into the review edit window, the windows starts extending to the left. Eventually, the window goes past the left screen edge; in particular, this eventually hides the "approve/comment/request changes" buttons, making it impossible to actually submit the review.

This is actually a realistic scenario, as the editor allows embedding images; to embed an image, you need to enter the image URL, which may be way, way longer than one screen width.

## Screenshots

![Zrzut ekranu z 2020-02-18 16-51-42](https://user-images.githubusercontent.com/4729533/74752717-6a826780-526f-11ea-8253-f24eafa4691e.png)

**Comment by zeripath** [comment]
I think if we set:

```css
    max-width: max(50vw, min(80vw, 500px));
```

on the .CodeMirror-scroll in the review box that should fix it.

**Comment by zeripath** [comment]
or something like that...
