### ISSUE TITLE
Weird handling of error message in Two Factor Authentication

### ISSUE THREAD

**Issue by strk** [go-gitea/gitea#1034]
- Gitea version (or commit ref): 1.0.0+310-gd077fd08
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes 

## Description

Enroll Two Factor Authentication, enter random Passcode: no error message is printed.
Follow any link from the left menu: the error message ("wrong passcode") is printed.

**Comment by bkcsoft** [comment]
@strk Is this still happening in v1.1?

**Comment by lunny** [comment]
I will close this. Please feel free to reopen it.
