### ISSUE TITLE
[feature] add drone template for create a repository

### ISSUE THREAD

**Issue by everhopingandwaiting** [go-gitea/gitea#10355]
- Gitea version (or commit ref): 1.12.0+dev-336-g530f8963f
- Git version: latest
- Operating system: docker
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X] No
  - [x] Not relevant
- Log gist:

## Description
In order to facilitate the integration of drone ci/cd , I suggest to add a .drone.yml file to the api of `/user/repos`.
this api looks like 
```
POST: 
{
  "auto_init": true,
  "description": "string",
  "gitignores": "string",
  "issue_labels": "string",
  "license": "string",
  "name": "string",
  "private": true,
  "readme": "string",
  "drone": "string"
}
```
...

**Comment by techknowlogick** [comment]
Thanks for opening this ticket :) We ❤️ Drone. This can currently be achieved with template repos. Another option is if you are using the API you can create this content that matches your specific drone needs, as gitignore or license come with a great defaults which may not be changed significantly, but drone yaml would certainly have to be changed from the default.
