### ISSUE TITLE
[Bug] Last commit date

### ISSUE THREAD

**Issue by TimerWolf** [go-gitea/gitea#10352]
- Gitea version (1.12.0+dev-336-g530f8963f):
- Git version: 1.12.0 Dev
- Operating system: Unknown
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
  - [x] Not relevant
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (https://try.gitea.io/TimerWolf/MarkdownBug/commits/branch/master)
  - [ ] No
- Log gist:
  - [x] Not relevant
## Description

As my native language is swedish the whole gitea page will be in swedish and that's nice, but the commit date don't seems to fallow the way the date is written here in sweden and i would imagine that this is the case for a lot languages.

I don't know if this is a bug, just bring it up to the surface and see if it worth notice, i mean the tooltip is not translated either. 

## Screenshots

![date](https://i.imgur.com/v1PMfUC.png)

**Comment by lunny** [comment]
You can change that on app.ini on section `[ui]`

**Comment by TimerWolf** [comment]
@lunny: can you be a bit more specific? I can't find anywhere where you change the "Tue" to "Tis" that would be in my native language.

**Comment by lunny** [comment]
https://docs.gitea.io/en-us/config-cheat-sheet/#time-time

**Comment by guillep2k** [comment]
I'm not sure you can translate the names of the days from our confic. If anything, I'd try setting `LC_TIME=sv_SE.utf8` in the environment before gitea runs (e.g. in the script used to launch it).
