### ISSUE TITLE
[UI] [optimization] repo settings page ui can't adaptive the screen size

### ISSUE THREAD

**Issue by everhopingandwaiting** [go-gitea/gitea#10359]
- Gitea version (or commit ref): 1.12.0+dev-336-g530f8963f
- Git version: latest
- Operating system: docker
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X] No
  - [x] Not relevant
- Log gist:

## Description

when I resize the screen , UI   is not responding correctly
url:  `http(s)://IP/user/repo/settings `
...

## Screenshots
![image](https://user-images.githubusercontent.com/6021724/74817757-6ec68780-5338-11ea-884e-85f24d58bf0d.png)

![image](https://user-images.githubusercontent.com/6021724/74818984-928acd00-533a-11ea-8a66-13b368693580.png)

**Comment by silverwind** [comment]
These tab bars being left-aligned comes from a workaround to prevent overflows on small screens. The proper fix would be `justify-content: safe center` so they center without overflowing outside the viewport, but the `safe` keyword currently is only supported on Firefox so another method (wrapper div) would be needed.

**Comment by silverwind** [comment]
This should be fixed on master now.
