### ISSUE TITLE
I can't search any code of my private repo.

### ISSUE THREAD

**Issue by imfantuan** [go-gitea/gitea#10366]
- Gitea version (or commit ref): 1.12.0+dev-340-g17445bbbf
- Git version: 2.25.0
- Operating system: CentOS 7
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:

## Description

...

**Comment by guillep2k** [comment]
Hi, have you enabled code indexing in your `app.ini`? It's disabled by default. See [`REPO_INDEXER_ENABLED`](https://docs.gitea.io/en-us/config-cheat-sheet/#indexer-indexer).

**Comment by imfantuan** [comment]
Sorry, my mistake.
Finally i found that the disk space is full.
It worked after rsync -avz /var/lib/docker/ /data/docker.
Thx very much
