### ISSUE TITLE
Users Never Signed-In, yet have repos published

### ISSUE THREAD

**Issue by sefsh** [go-gitea/gitea#10374]
- Gitea version (or commit ref):
- Git version: 1.11.1
- Operating system: ubuntu:bionic-20180821
- Database (use `[x]`): 
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:
N/A

## Description
When I check for users with the Last Sign-In status `Never Signed-In`, I find users that have published repos on the platform. This shouldn't be possible.

## Screenshots
<img width="764" alt="bild" src="https://user-images.githubusercontent.com/346211/74914376-a1b55d80-53c2-11ea-9830-a7fc2e0c5680.png">

**Comment by jolheiser** [comment]
Is there a chance someone transferred a repo to this account?  
Or that the user created the repo via push-create if enabled before logging in?

**Comment by lunny** [comment]
There is a known issue that if user only push/pull via git, the `Last Sign-In` didn't update.

**Comment by rnowak** [comment]
Chiming in to add that this is also the case if the user authenticates via a header set in REVERSE_PROXY_AUTHENTICATION_USER both for the web interface as well as git interactions over https.

![2020-02-22 14_26_46-User Accounts](https://user-images.githubusercontent.com/1057534/75093187-f5b97100-557f-11ea-9ff5-3f8e553694cc.png)

**Comment by fnetX** [comment]
AFAICT this is also the case if a user registers and does actions within pers first session (this also explains how a user could create a repo which is not possible with push / pull alone).

**Comment by zeripath** [comment]
Ok that's a much simpler bug to fix!

**Comment by furai** [comment]
I get the same issue - I have gitea behind reverse proxy and last sign-in doesn't update. 
(Also for some reason when I log-in, I get presented with a blank screen until I refresh, and I don't know why.)

**Comment by zeripath** [comment]
> AFAICT this is also the case if a user registers and does actions within pers first session (this also explains how a user could create a repo which is not possible with push / pull alone).

I think that that this has been patrially fixed already in 1.14+ probably earlier (excepting potentially ReverseProxy) 

`SetLastLogin()` does appear to be called on API logins. Is it possible therefore that these are creations from the API?

**Comment by zeripath** [comment]
> I get the same issue - I have gitea behind reverse proxy and last sign-in doesn't update.
> (Also for some reason when I log-in, I get presented with a blank screen until I refresh, and I don't know why.)

This should be fixed by #15304

**Comment by wolfogre** [comment]
> AFAICT this is also the case if a user registers and does actions within pers first session (this also explains how a user could create a repo which is not possible with push / pull alone).

The case should be fixed by #21731
