### ISSUE TITLE
Cannot view monitoring page while garbage collection running

### ISSUE THREAD

**Issue by pgaskin** [go-gitea/gitea#1037]
- Gitea version (or commit ref): d077fd0 
- Git version: 2.9.3
- Operating system: Ubuntu 16.10
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X] No (I do not have admin access)
  - [ ] Not relevant
- Log gist: Nothing out of the ordinary in the log, even in the debug messages.

## Description
I cannot access monitoring while garbage collection is running. I get this error returned instead of the page: "template: admin/monitor:52:15: executing "admin/monitor" at <.Pid>: Pid is not a field of struct type *process.Process"

How to reproduce:

1. Upload some repositories (so it takes some time to do garbage collection)
2. Run the garbage collection action in the admin
3. While it is running, try and view the monitoring page in the admin

**Comment by pgaskin** [comment]
https://github.com/go-gitea/gitea/blob/d077fd084a3cc8d96ba80d8fcf950b21523644b2/templates/admin/monitor.tmpl#L52

**Comment by lunny** [comment]
fixed by #1048
