### ISSUE TITLE
Feature: Add username to git clone url

### ISSUE THREAD

**Issue by HappyStriker** [go-gitea/gitea#10381]
I am using Gitea mainly with private repositories and all users, which may access the server, have to be signed in due to security reasons. In the repository view the clone url by default (or however it is configured in the `app.ini`) does not include the username, so it is an additional step to enter it when the credentials are needed.

So to solve this issue it would be great if there would be a template string in the `app.ini` to add the username if wanted, like:
```
[server]
ROOT_URL = %(PROTOCOL)s://%(USERNAME)@%(DOMAIN)s:%(HTTP_PORT)s/
```

Thank you for all work on Gitea so far and for considering and hopefully implementing this feature request!

Best regards,
Happy Striker.

**Comment by silverwind** [comment]
Dupe of https://github.com/go-gitea/gitea/issues/2681 I think.
