### ISSUE TITLE
Wrote a Gitea webhook to AWS S3 service

### ISSUE THREAD

**Issue by leonli** [go-gitea/gitea#10389]
Just wrote a Gitea webhook to AWS S3 service, maybe someone would be interested to check it out for the integration with AWS CodePipeline and CodeBuild.

https://github.com/leonli/webhook-to-s3

**Comment by techknowlogick** [comment]
Wonderful!

Feel free to send a PR here to add it to the list: https://gitea.com/gitea/awesome-gitea

**Comment by lunny** [comment]
Please go to https://gitea.com/gitea/awesome-gitea/pulls/11
