### ISSUE TITLE
[Feature] markdown inline style

### ISSUE THREAD

**Issue by TimerWolf** [go-gitea/gitea#10395]
- Gitea version (1.12.0+dev-349-g4efc365c0):
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
  - [x] Not relevant
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:
  - [x] Not relevant

## Description

I don't see any reason why not html inline style attribute not would be allowed in the markdown, i mean if the meaning of not allowing it would be to control the look of the repos and make sure it looks clean maybe have a setting to enable or disable it.

So it could be up to everyone to chose if you can change the colour on your text or not as it is today it's impossible to have anything other then black expect from links.

**Comment by guillep2k** [comment]
I believe that all kind of malicious manipulation can be done with styles (e.g. by absolute position things).

**Comment by silverwind** [comment]
Styles can include SVGs which can include scripts. Better not go there.

**Comment by TimerWolf** [comment]
Sure, i am no so good as this as you people are!

But are there not away to as any language you code in accept or disallow any code your like?

I mean specific files like ".svg" should be so easy to sort out and just allow clean "css" code.
