### ISSUE TITLE
Long commit messages are not truncated in overview

### ISSUE THREAD

**Issue by Windoze345** [go-gitea/gitea#10391]
- Gitea version (or commit ref): 1.11.1
- Git version: 2.20.1
- Operating system: Debian Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No (https://try.gitea.io/wwb91718/test)
  - [ ] Not relevant
- Log gist:

## Description
Long commit messages are not truncated with "..." and overflow beyond the border of the browser window. Also there is no scroll-bar so i can't see the modification time column.

## Screenshots
![2020-02-21 09_04_55-Window](https://user-images.githubusercontent.com/1225862/75016389-2cfa2600-548b-11ea-818a-20a90a85f868.png)

**Comment by zeripath** [comment]
This is already fixed in 1.11 and master

**Comment by Windoze345** [comment]
I am using 1.11.1 so it is obviously not fixed in 1.11

**Comment by jolheiser** [comment]
To clarify, it's fixed in the `1.11` branch, and will be released in `1.11.2`.

**Comment by Windoze345** [comment]
Thanks for the info. I'm waiting for the 1.11.2 release then :)
