### ISSUE TITLE
Error 500 when accessing /api/v1/repos/:org/:repo/releases after deleting user

### ISSUE THREAD

**Issue by bucciarati** [go-gitea/gitea#10392]
- Gitea version (or commit ref): 1.10.4
- Git version: 2.20.1
- Operating system: CentOS 7
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes 
  - [ ] No
  - [x] Not relevant (can't delete users on try.gitea.io)
- Log gist:

```
$ curl --include "https://XXXX/api/v1/repos/ORG/REPO/releases?access_token=XXXXXXXX"
HTTP/1.1 500 [...]
{"message":"user does not exist [uid: 16, name: , keyid: 0]","url":"https://XXXX/api/swagger"}
```

## Description

1. create a release with user `joe` in some repository
1. as instance admin, delete user `joe`
1. visit gitea/org/repo/releases, notice release is now by `Ghost`
1. curl --include "https://XXXX/api/v1/repos/ORG/REPO/releases?access_token=XXXXXXXX"
1. get error 500

Looking into the `release` table it looks like there are releases with `publisher_id=16` (where 16 was the ID of the deleted user `joe`).

**Comment by lunny** [comment]
Could you upgrade to v1.11.1?
