### ISSUE TITLE
rewrite docker stuff

### ISSUE THREAD

**Issue by xinity** [go-gitea/gitea#104]
as gitea grows, we have to rewrite docker stuff in the docker dir.

this issue will stays open until PR is merged and will serve a repo for comments.

feel free to add what you think should be done regarding docker build

**Comment by xinity** [comment]
keep s6 as an init replacement.

**Comment by xinity** [comment]
rewrite env variables

**Comment by xinity** [comment]
dockerfile cleanup

**Comment by DblK** [comment]
I would suggest to have the smaller image as possible and by doing so, the compilation should be done outside and the binary pushed to the docker (maybe from scratch instead alpine).

I could provide later a link to a docker images that can be used to build Go program and make docker images without compiler program.

Edit 11/10/16:
Here is the [link](https://github.com/CenturyLinkLabs/golang-builder) to build dockerfile for Go program with image "SCRATCH"

**Comment by tboerger** [comment]
We will use drone to build the binary outside of the docker image, the drone pipeline is in preparation ;)

**Comment by xinity** [comment]
@tboerger nice !

then @DblK send the link to me :) i'd be happy to learn moaaarrrr go :)

**Comment by willemvd** [comment]
why do we need that s6 stuff instead of setting things up in the dockerfile?

**Comment by tboerger** [comment]
@willemvd we need s6 as process manager because we will run more than a single service within the container, at least we need Gitea and openSSH.

**Comment by ghost** [comment]
I would strongly recommend against using `scratch` as that renders any form of shell scripting invalid.

**Comment by ptman** [comment]
The way you say it makes it sound like avoiding shell scripts is a bad thing

**Comment by LefsFlarey** [comment]
Yes, it removes the functionality of git hooks.

**Comment by ghost** [comment]
Yes, it breaks many things. Including git-hooks and https://github.com/go-gitea/git.

**Comment by tboerger** [comment]
Nobody wants to use scratch, alpine is a perfect base

**Comment by ghost** [comment]
@tboerger, I just wanted to let anyone that likes @DblK's idea know that it's not going to be good if we use scratch as base.

**Comment by ogarcia** [comment]
Using scratch as base not is (in this case) a good idea cause you need OpenSSH and shell scripts.

**Comment by tboerger** [comment]
We already refactored docker
