### ISSUE TITLE
Long running git diff processes

### ISSUE THREAD

**Issue by xPaw** [go-gitea/gitea#104]
It looks like there's some kind of bug that causes multiple `git diff` processes to get stuck and they never go away.

```
  │   └─gogs -- web
  │       ├─git diff -M a b
  │       ├─git diff -M a b
  │       ├─git diff -M a b
  │       ├─git diff -M a b
  │       ├─git diff -M a b
  │       ├─git diff -M a b
  │       ├─git diff -M a b
```

Some of them have been running for a couple of days now.

**Comment by lunny** [comment]
I haven't still reproduce this issue.

**Comment by xinity** [comment]
@DblK feel free to update your comment with the appropriate link :)
