### ISSUE TITLE
Feature request: integration with/for gitter

### ISSUE THREAD

**Issue by datenheim** [go-gitea/gitea#10405]
It could be interesting to offer an integration for gitter.
There are already numerous integrations for gitlab, bitbucket, goc, etc. and gitea is somehow missing.
Maybe gitter can provide some features not worth inventing again inside gitea?
Sadly I don't know where and how to start such thing....

**Comment by jolheiser** [comment]
It looks as though an issue has been filed with gitter for this at https://gitlab.com/gitlab-org/gitter/services/issues/108
