### ISSUE TITLE
[Feature Request] Webhooks message customization

### ISSUE THREAD

**Issue by davydov-vyacheslav** [go-gitea/gitea#10418]
I'd like Gitea has customized messages for Webhooks.

As for now, Gitea Webhooks messages are hardcoded and there is no way for customization.

I think that following things make Gitea Webhooks functionality much better:
- on webhooks page (maybe even better in config file) add `Custom message` field where user is able to set own message for specific action
- user should be allowed to have/use predefined "variables", like `%repo%` for link to org/repository with the name,%issue.title% - issue's title if the action type in scope of issue and so on.

And as result, I'd like to be able to set (e.g. for pull request) message like: %user% has submitted pull-request to %repo%.

**Comment by jolheiser** [comment]
This would be covered by #1089
