### ISSUE TITLE
Remove font-awesome

### ISSUE THREAD

**Issue by silverwind** [go-gitea/gitea#10410]
We currently only use 4 icons out of it. I suggest replacing it with individual SVGs using the same build process like for octicons. I did not find a maintained npm repo of FA SVGs so we need to manually collect SVGs from tools like [icomoon](http://icomoon.io/app/#/select), or even better, use existing icons from the octicons set.

Here are the unique `fa-*` strings I found in the source:

```
fa-angle-right
fa-check-square-o
fa-file
fa-square-o
```
(Last check: 2023-04-30 by @delvh)

**Comment by zeripath** [comment]
I think fomantic bundles fontawesome with it - so we could just switch to use their icons.

**Comment by silverwind** [comment]
Fomantic still uses icon fonts though which are inferior to SVGs. It will still be an improvement if to  get rid of the shipped font-awesome.

**Comment by lafriks** [comment]
They could be easily replaced using @fortawesome/fontawesome to include only needed svg icons

**Comment by silverwind** [comment]
I checked those `@fortawesome` modules but the non-deprecated ones only export JS data which would need preprocessing to get actual SVG data out of. I'd say not worth it.

**Comment by lafriks** [comment]
What is the problem with js data? This way it would be included in js file using webpack?

**Comment by silverwind** [comment]
It needs a script to extract mainly. [svg-sprite-loader](https://github.com/JetBrains/svg-sprite-loader) can only deal with plain `.svg` files. Octicons does it right, they publish a directory of `.svg` files only.

**Comment by lafriks** [comment]
You just call `dom.watch()` and it automatically injects icons in html, no need to deal with anything ;)

**Comment by silverwind** [comment]
Please no more JS injections like that, they flash empty content on page load. SVG should be server-rendered primarily with ways for scripts to access for script-generated content.

**Comment by lafriks** [comment]
I don't think that it would be too bad that icons would not show up with JavaScript disabled, especially since there is so much things that will not work without JavaScript enabled anyway ;)

**Comment by silverwind** [comment]
https://github.com/go-gitea/gitea/pull/24471
