### ISSUE TITLE
Relative image paths in readmes are incorrect

### ISSUE THREAD

**Issue by SuperSandro2000** [go-gitea/gitea#10412]
- Gitea version (or commit ref): 1.12.0+dev-354-gc8d1c3812
- Git version: irrelevant 
- Operating system: Debian
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant

## Description

When I visit https://try.gitea.io/supersandro2000/hacker-laws I get a 404 for a missing embedded image in the readme. The image is embedded like this ``<img width="480px" alt="Diagram: Amdahl's Law" src="./images/amdahls_law.png" />`` and it resolves that to https://try.gitea.io/supersandro2000/images/amdahls_law.png which is not correct. The repository is a mirror of https://github.com/dwmkerr/hacker-laws.git .

~~When I open the [readme file directly](https://try.gitea.io/supersandro2000/hacker-laws/src/branch/master/README.md) it gets resolved correctly.~~

Also this triggers a http basic auth on my private instance cause I think some api request has that activated.

**Comment by silverwind** [comment]
The issues is that the relative link resolves to `https://try.gitea.io/supersandro2000/hacker-laws/src/branch/master/images/amdahls_law.png` which is the `/src/` page while it should use `/raw/` for the actual image resource.

**Comment by SuperSandro2000** [comment]
You are right. So it does not work either way.

**Comment by zeripath** [comment]
@SuperSandro2000 

In fact you should not be using the `./raw` endpoint you should use the `./media` endpoint as that will transparently work for LFS.

Now if you want to link to an image the simplest thing is to use the `![Diagram: Amdahl's Law](images/amdahls_law.png)`

That being said we can do something better with detecting image links. So we should really make these links relative to the media link.

I wonder if the /media link of a markdown file should actually just render the markdown.

**Comment by SuperSandro2000** [comment]
This is not my repo. I just mirrored it from GitHub and I get greeted with a basic auth pop up all the time when I visit it on my private instance and only when I am not logged in on the demo instance. The pop up is the only reason why I reported this as it is very annoying and disrupts the user.

**Comment by silverwind** [comment]
> In fact you should not be using the ./raw endpoint you should use the ./media endpoint as that will transparently work for LFS.

I'd expect `./image.png` links to files in the repo to resolve to the `raw` endpoint. If the file has a URL in LFS, it could be used instead, but generally the user should not have to care whether LFS is enabled or not so those images work everywhere.

**Comment by 6543** [comment]
this is a dublicate of #8830

**Comment by guillep2k** [comment]
Close in favor of #8830
