### ISSUE TITLE
Signal 15?

### ISSUE THREAD

**Issue by YouveGotMeowxy** [go-gitea/gitea#10422]
My gitea log is filled with these, is this normal?

![image](https://user-images.githubusercontent.com/39491297/75105680-fb44a480-55db-11ea-9086-69fee9c7f2b4.png)

**Comment by lunny** [comment]
Gitea version? OS? Docker image?

**Comment by YouveGotMeowxy** [comment]
> Gitea version? OS? Docker image?

Sorry, I thought the Gitea version being in the screenshot would be enough.

Gitea Version: 1.12 Dev
OS: Docker Desktop for Windows
Yes, it's a Docker image, from the gitea/gitea repo

**Comment by zeripath** [comment]
It's not normal no and gitea is constantly restarting for some reason.

**Comment by YouveGotMeowxy** [comment]
If anyone needs any more information to help me sort this out, please just say what is needed; I'm not a techy type of person, so I have no idea where to start or what's needed.

**Comment by guillep2k** [comment]
@YouveGotMeowxy Can you please create an example in `try.gitea.io`? It's our public test site and it always runs the nigthtly build from Gitea.

**Comment by zeripath** [comment]
So I think this is more likely to be a configuration issue.

@YouveGotMeowxy could you please post a suitably sanitised copy of your app.ini?

Please describe your setup of Gitea and where and how you've configured its directories including the log directories, and finally that you've confirmed the Gitea process owns all of the appropriate directories. The final thing to ensure is that you're definitely not trying to open Gitea on a port below 1024.

**Comment by YouveGotMeowxy** [comment]
@zeripath Here's my docker compose for gitea:

```
version: '2'

services:

    gitea:
        image: 'gitea/gitea:latest'
        container_name: gitea
        environment:
            - TZ='America/Chicago'
            - PUID=197609
            - PGID=197121
        volumes:
            - 'my_gitea_data:/data'
        restart: unless-stopped
        networks:
            - default

networks:
    default:
        external:
            name: my-coding
```

I don't open any ports on the host.

Here's my app.ini

```
APP_NAME = Gitea: Git with a cup of tea
RUN_MODE = prod
RUN_USER = git

[repository]
ROOT = /data/git/repositories

[repository.local]
LOCAL_COPY_PATH = /data/gitea/tmp/local-repo

[repository.upload]
TEMP_PATH = /data/gitea/uploads
; Max number of files per upload. Defaults to 5
MAX_FILES = 500
[server]
APP_DATA_PATH    = /data/gitea
SSH_DOMAIN       = my.domain.com
HTTP_PORT        = 3000
ROOT_URL         = https://my.domain.com:4222/gitea
DISABLE_SSH      = false
SSH_PORT         = 22
LFS_CONTENT_PATH = /data/git/lfs
DOMAIN           = my.domain.com
LFS_START_SERVER = true
LFS_JWT_SECRET   = B4Y0nretretretretretretret
OFFLINE_MODE     = false

[database]
PATH     = /data/gitea/gitea.db
DB_TYPE  = sqlite3
HOST     = localhost:3306
NAME     = gitea
USER     = root
PASSWD   =
SSL_MODE = disable

[indexer]
ISSUE_INDEXER_PATH = /data/gitea/indexers/issues.bleve

[session]
PROVIDER_CONFIG = /data/gitea/sessions
PROVIDER        = file

[picture]
AVATAR_UPLOAD_PATH      = /data/gitea/avatars
DISABLE_GRAVATAR        = false
ENABLE_FEDERATED_AVATAR = true

[attachment]
PATH = /data/gitea/attachments

[log]
ROOT_PATH = /data/gitea/log
MODE      = file
LEVEL     = info

[security]
INSTALL_LOCK   = true
SECRET_KEY     = retetretrero97
INTERNAL_TOKEN = dsfsdfJoCSv0

[service]
DISABLE_REGISTRATION              = true
REQUIRE_SIGNIN_VIEW               = true
REGISTER_EMAIL_CONFIRM            = false
ENABLE_NOTIFY_MAIL                = false
ALLOW_ONLY_EXTERNAL_REGISTRATION  = false
ENABLE_CAPTCHA                    = false
DEFAULT_KEEP_EMAIL_PRIVATE        = false
DEFAULT_ALLOW_CREATE_ORGANIZATION = false
DEFAULT_ENABLE_TIMETRACKING       = true
NO_REPLY_ADDRESS                  = noreply.here.com

[oauth2]
JWT_SECRET = 4XYPNfAjTg

[mailer]
ENABLED = false

[openid]
ENABLE_OPENID_SIGNIN = true
ENABLE_OPENID_SIGNUP = false

[ui]
DEFAULT_THEME = arc-green

[metrics]
ENABLED = true

[i18n]
LANGS = en-US
NAMES = English

[i18n.datelang]
en-US = en
```

Other than that I haven't done anything special as far as changing anything else.

**Comment by zeripath** [comment]
Ok, first switch your logging config to console and ramp it up to debug or even trace. Send the xorm logs to the console too with `Xorm = console`

**Comment by YouveGotMeowxy** [comment]
@zeripath Tyvm for helping me out, I appreciate it beyond words. :)

So, I went to try to edit the app.ini to add your suggestions, and I saw that I'm getting a new error instead:

> "Git module init failed: Failed to execute 'git config --global core.quotepath false': error: failed to write new configuration file /data/git/.gitconfig.lock"

After some Googling, I saw something similar in a Gogs issue thread, and one comment said he was getting the error due to running out of disk space. So I checked how much disk space was allocate to the Hyper-V machine for my Docker and it was using like 58.6/59GB. *eek*. So I changed from 59gb to 80 and restarted my windows machine.

I don't know whether or not my original problem is solved by that however, because I still can't even SSH into the gitea container due to the same error mentioned above. *arrrgh*

When I try to SSH into the container, (using Portainer) I get this:

![image](https://user-images.githubusercontent.com/39491297/75194541-f2f48280-571d-11ea-8615-db7e425fe2ce.png)

And during that same time, doing a `docker ps` shows this:

![image](https://user-images.githubusercontent.com/39491297/75194660-2b945c00-571e-11ea-9f85-6a24492a9904.png)

I have read in some other cases, that simply deleting a .lock file can fix things like this, I don't know whether or not that would work in this case, but I can't even try it because I can't get into the container.  :/

**Comment by YouveGotMeowxy** [comment]
Update:

After re-sizing my Hyper-V VM to 100 gb, a bunch of issues with docker were fixed, but I'm still having the same issue with Gitea stopping and starting repeatedly. After adding everything except the "xorm" flag to my app.ini (not sure which section to put it under?), my log now floods me with this:

![image](https://user-images.githubusercontent.com/39491297/75294170-5b5e6500-57ed-11ea-9a73-68e8a53121a7.png)

The strange thing is I can still login to the Gitea page and navigate around as usual (while the container is briefly up; it goes up and down roughly every 30 seconds).

Any ideas?

**Comment by zeripath** [comment]
You need to delete the broken queue files in your /data/queues

**Comment by YouveGotMeowxy** [comment]
> You need to delete the broken queue files in your /data/queues

@zeripath k, just to verify, if I delete them will I lose/break anything? Like I mentioned, I'm a noob at all this, lol.

**Comment by zeripath** [comment]
Your system is borked already so no you won't lose anything more than you've already lost

**Comment by YouveGotMeowxy** [comment]
I deleted all of those folders, then started getting these:

![image](https://user-images.githubusercontent.com/39491297/75300694-581fa500-57fe-11ea-8084-dc63988fa041.png)


Deleted THOSE folders, and now I think we're good! It's not restarting over and over anymore, and after a quick look-through it doesn't *seem* like I lost anything.

Thank you for the help! :D
