### ISSUE TITLE
Gitea v1.11 UI in Docker is broken, missing CSS and JS resources

### ISSUE THREAD

**Issue by amyspark** [go-gitea/gitea#10448]
- Gitea version (or commit ref): 1.11.1
- Git version: 2.24.1
- Operating system: Docker (kunde21/gitea-arm:v1.11.1)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X] No
  - [ ] Not relevant
- Log gist:

## Description

I use Gitea through the `kunde21/gitea-arm:v1.11.1` image (ARMv7) under a Raspberry Pi 3 B+. Ever since I upgraded my services to the v1.11 images, the UI is broken, and the Dev Tools show HTTP 404 errors for `js/index.js?v=b7b0b0e0a539f1923ef5da163e614fa9` and `css/index.css?v=b7b0b0e0a539f1923ef5da163e614fa9`. Accessing these resources returns a HTTP 404 generated from within the container.

## Screenshots
![Captura de pantalla de 2020-02-24 17-34-33](https://user-images.githubusercontent.com/13498015/75189217-81700080-572c-11ea-9086-593487fb0fb1.png)

**Comment by techknowlogick** [comment]
You'll need to contact kunde21 the author of that container to update their build process. We are currently working on getting infrastructure ready to start building arm32 builds.

**Comment by silverwind** [comment]
They need to update their [Dockerfile](https://github.com/Kunde21/raspberry-dev/blob/master/gitea-arm/Dockerfile) to include new [build deps](https://github.com/go-gitea/gitea/commit/d9c67a8c903fa9927bad28f5fcb816f89f8200eb#diff-3254677a7917c6c01f55212f86c57fbf) since 1.11.

**Comment by Kunde21** [comment]
@silverwind Thanks for a pointer to the change.  I think I've got it fixed.
