### ISSUE TITLE
Cannot fork organization-owned repository to new repository with the same owner

### ISSUE THREAD

**Issue by veita** [go-gitea/gitea#10442]
- Gitea version (or commit ref): 1.11.1
- Git version: 2.11.0
- Operating system: Debian GNU/Linux 9.12 (stretch)
- Database (use `[x]`):
  - [ x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x ] Yes (https://try.gitea.io/forkorg/to-fork)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
1. Create organization `forkorg`
2. Create a repository `to-fork`
3. Transfer ownership of `to-fork` to `forkorg`
4. Try to fork `forkorg/to-fork` to `forkorg/forked`

=> The fork dialog does not allow to select `forkorg` as the owner of the `forked` repository.

**Comment by jolheiser** [comment]
Perhaps I missed a step, but this is normal behavior.  
You cannot fork a repo to the same owner, whether it be a user or an org.

**Comment by theevilcookie** [comment]
@jolheiser Could you extend on why this is considered normal behavior? Would it not make sense to fork to the same owner? Obviously the name can not be identical though.

**Comment by jolheiser** [comment]
Why would you fork it to the same owner?

If you want to work on it for merging later, a different branch would work.

If you plan on diverging work, you could possibly "migrate" it instead.

**Comment by theevilcookie** [comment]
Well "migrating" would be a lot more complex than just hitting the fork button. Also the fork workflow in my opinion correctly describes the behaviour as opposed to the "migrate" solution.
An example usecase would be using an older project as basis for a new solution. Using a branch would be not enough separation as it is a separate project. Also you might not want to alter the original project. So forking seems legit to me.

**Comment by jolheiser** [comment]
For that example you could set it as a template repository, or pull->delete .git dir->push to new repo (the latter isn't very intuitive, though)

Regardless, it seems forking will not do that. :slightly_frowning_face:

**Comment by veita** [comment]
Our use case are template projects. They contain files and directories that are common to certain types of project.

A new project of a certain type is then being created by forking the respective template. After the fork project-specific files and directories are added.

The current workaround is to fork the template to a different owner and then to transfer ownership back to the organization the template was forked from.

**Comment by theevilcookie** [comment]
Well thank you for your insights :)
I'm still not convinced that forking to the same owner does not make sense. However I understand that this is not a bug but intended behavior. We will figure out a solution.

**Comment by jolheiser** [comment]
Yeah, sorry I wasn't more help. :sweat_smile: 

Feel free to open an issue or modify this one to propose allowing that functionality.

Otherwise this issue can be closed?
