### ISSUE TITLE
How to config http direct https

### ISSUE THREAD

**Issue by jzdayz** [go-gitea/gitea#10451]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
hello,how to config direct http to https,now i setting the https. By the way, in docker.

**Comment by 6543** [comment]
the best way to get answers about how to configure gitea:
 * visit our discord server: https://discord.gg/Gitea
 * read the docs: https://docs.gitea.io/en-us/

docker specific config you can read about https://docs.gitea.io/en-us/install-with-docker/
the https setup: https://docs.gitea.io/en-us/https-setup/

**Comment by jzdayz** [comment]
> the best way to get answers about how to configure gitea:
> 
> * visit our discord server: https://discord.gg/Gitea
> * read the docs: https://docs.gitea.io/en-us/
> 
> docker specific config you can read about https://docs.gitea.io/en-us/install-with-docker/
> the https setup: https://docs.gitea.io/en-us/https-setup/

think you ! i found it .
