### ISSUE TITLE
API for List a repository's tags

### ISSUE THREAD

**Issue by jasder** [go-gitea/gitea#10453]
The api currently does not provide paging function. If there is a large amount of data, there will be problems. Can you add a paging mechanism?

![image](https://user-images.githubusercontent.com/6260038/75209417-1b7d8a80-57b9-11ea-881c-413e2e8d5c99.png)

**Comment by 6543** [comment]
I'll take this

**Comment by 6543** [comment]
@jasder feature will be in v1.12.0 :)
