### ISSUE TITLE
Web UI shakes butt when showing off languages used in repository

### ISSUE THREAD

**Issue by theAkito** [go-gitea/gitea#10474]
- Gitea version (or commit ref): 0eeee9c72
- Git version: 2.20.1
- Operating system:

Component | Version
-- | --
Kernel | 4.19.0-8-amd64 x86_64
Distro | Debian GNU/Linux 10 (buster)

- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:
All good.

## Description
(First of all, a huge thank you to whoever added the feature of seeing which languages are used in the repository. I always use this on Github and waited for this to get to Gitea, since ever.)

Whenever the language display bar is toggled, the UI shakes, as if it were freezing.
See the gif below. Open it in a new tab, because the embedded gif is a bit too small to see the shaking.

## Screenshots

![gitea-bug_20200226](https://user-images.githubusercontent.com/26848976/75337945-3a9a1c00-588e-11ea-8306-f987507ab0bc.gif)

**Comment by lafriks** [comment]
It's nice to see work done being appreciated, glad you like it ;)
