### ISSUE TITLE
More colors for language bar / language mapping like linguist

### ISSUE THREAD

**Issue by alexanderadam** [go-gitea/gitea#10476]
First of all: it's _awesome_ that @lafriks implemented this! :pray: 

- Gitea version (or commit ref): `1.12.0+dev-379-ge5944a952`
- Git version: -
- Operating system: -
- Database (use `[x]`): -
- Can you reproduce the bug at https://try.gitea.io:
  - yes, simply explore `try.gitea.io` for more examples
- Log gist: -

## Description

Languages are perfectly recognized but some colors are missing.

Maybe it would need a mapping or so?
Some examples:

| Detected language | Possible color mapping |
| ----------------- | ---------------------- |
| `HTML+ERB` | `HTML` ([example](https://try.gitea.io/AlexWayfer/flame)) |
| `Haml` | `HTML` ([example](https://try.gitea.io/alexanderadam/puzzle-puzzletime)) |
| `SCSS` | `CSS` ([example](https://try.gitea.io/alexanderadam/puzzle-puzzletime)) |

Github uses groups for this and properties are inherited from the parent group. For example [Haml inherits from HTML](https://github.com/github/linguist/blob/96ca71ab99c2f9928d5d69f4c08fd2a51440d045/lib/linguist/languages.yml#L2089-L2090).

## Screenshots

![Screenshot_20200226_140920](https://user-images.githubusercontent.com/372620/75347772-ccf7eb00-58a1-11ea-8f5c-e3513d35654b.png)

![Screenshot_20200226_141331](https://user-images.githubusercontent.com/372620/75347956-2fe98200-58a2-11ea-8266-7798a52efab0.png)

**Comment by guillep2k** [comment]
As colors are provided by the `enry` library, this should be an upstream issue. Please report to: https://github.com/src-d/enry

https://github.com/go-gitea/gitea/blob/9a476113f01602f8418f8f66e7eceac27fd480c5/models/repo_language_stats.go#L31-L35

I'm closing this.

**Comment by alexanderadam** [comment]
@guillep2k shouldn't the issue kept open? I mean the issue is technically not closed and still present, right? Also it would still need the dependency update, once this issue is fixed in [**enry**](https://github.com/src-d/enry).

**Comment by alexanderadam** [comment]
@lafriks, I can't emphasize this enough but [you are simply awesome](https://github.com/go-enry/go-enry/pull/2#issue-391860114)!

This issue should be fixed if someone is updating [`go-enry` to `2.3.0`](https://github.com/go-enry/go-enry/releases/tag/v2.3.0).

**Comment by lafriks** [comment]
Thanks :)
