### ISSUE TITLE
Few images in a row, only the first image works

### ISSUE THREAD

**Issue by kasbah** [go-gitea/gitea#10484]
- Gitea version (or commit ref): c161bb013e091c0bcc5

## Description

With a few images in a row, one per line, only the first image works. E.g. on https://try.gitea.io/kasbah/ruler , migrated from https://github.com/kitspace/ruler. On GitHub it's fine. Relevant markdown:

```markdown
![](front_no_panel.jpg)
![](back_no_panel.jpg)
![](front.jpg)
![](back.jpg)
![](front_populated.png)
```

If you put empty lines in between, it's fine. 

## Screenshots

![image](https://user-images.githubusercontent.com/206854/75371056-0179a000-58be-11ea-9bb9-25eb5a35ce59.png)

**Comment by zeripath** [comment]
Appears to be fixed on try...

**Comment by CMiksche** [comment]
I didn't had this problem on an older version of Gitea but since i have upgraded to 1.11.5 this error occurs again!
