### ISSUE TITLE
repo cann't add Gogs webhook

### ISSUE THREAD

**Issue by yw9381** [go-gitea/gitea#10490]
- Gitea version (or commit ref): 1.11.1
- Git version: 
- Operating system: Debian 10
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

i will add Gogs webhook，gitea tell me "ContentType不能为空。"，but i cann't set ContentType

...

## Screenshots
![image](https://user-images.githubusercontent.com/4542000/75388123-63b6bd00-591f-11ea-867e-e58f11324e30.png)

**Comment by jolheiser** [comment]
I believe this will be fixed by #10456
