### ISSUE TITLE
Slack webhook showing message 0 new commits pushed

### ISSUE THREAD

**Issue by cornelk** [go-gitea/gitea#10498]
- Gitea version (or commit ref): 1.11.1
- Git version:
- Operating system:
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

When deleting a branch after a PR merge, the following messages are printed from Slack webhook:

`...branchname] branch deleted by cornel`
`...branchname] 0 new commits pushed by cornel`

is the `0 new commits pushed` message intentional/needed?

**Comment by WGH-** [comment]
There're other places when this weird "0 new commits pushed" is emitted. When pushing a tag pointing to existing commit, for example.

**Comment by 6543** [comment]
@zeripath please reopen :)

**Comment by Kwarde666** [comment]
I have the same issue using the Discord webhook
