### ISSUE TITLE
Go 1.14 version check fails on Windows/amd64

### ISSUE THREAD

**Issue by filipnavara** [go-gitea/gitea#10507]
- Gitea version (or commit ref): a924a90349a78ebe8e7eb560e435a7ddc1de9b84
- Git version: 2.25
- Operating system: Windows

## Description

The check in `make go-check` fails because the regular expression for version extraction doesn't match the output of `go version`.

`go version` output is `go version go1.14 windows/amd64` which cannot be matched with `grep -Eo '[0-9]+\.?[0-9]+?\.?[0-9]?\s'`.

**Comment by silverwind** [comment]
The regex does  match and it looks to be able to cope with 2-number versions too. I'm not sure what the issue exactly is.

```console
$ printf "%03d%03d%03d" $(echo 'go version go1.13.4 linux/amd64' | grep -Eo '[0-9]+\.?[0-9]+?\.?[0-9]?\s' | tr '.' ' ')
001013004
```
```console
$ printf "%03d%03d%03d" $(echo 'go version go1.14 windows/amd64' | grep -Eo '[0-9]+\.?[0-9]+?\.?[0-9]?\s' | tr '.' ' ')
001014000
```

**Comment by filipnavara** [comment]
Interesting, in MSYS I get this:
```
bash-3.1$ printf "%03d%03d%03d" $(echo 'go version go1.14 windows/amd64' | grep -Eo '[0-9]+\.?[0-9]+?\.?[0-9]?\s' | tr '.' ' ')
000000000
bash-3.1$
```

**Comment by jolheiser** [comment]
In Git Bash on Windows I get `001014000`

**Comment by filipnavara** [comment]
I get the same garbage in Git Bash, let me check various tool versions to pinpoint which one breaks it.

**Comment by filipnavara** [comment]
Seems to be an issue with the `grep` in MSYS. I'll just close the issue, thanks for help.

**Comment by filipnavara** [comment]
For the record, the version of `grep` in Git Bash is 3.1. The one I had in my MSYS installation was version 2.5.4. The older version doesn't understand the `\s` syntax apparently, or interprets it incorrectly.

**Comment by zeripath** [comment]
hmm... I think that means we should switch away from using \s as it won't work on non-GNU systems too.

**Comment by zeripath** [comment]
We should probably use `\b`

**Comment by filipnavara** [comment]
`\b` doesn't work either. With Git Bash it matches both the version and "64" at the end. With the old MSYS grep it doesn't match anything. Putting a dumb ` ` (space) instead of `\s` works with both but not sure if it's reliable and future proof.

**Comment by zeripath** [comment]
The BSD users will complain about it too.

**Comment by guillep2k** [comment]
We should use `egrep` (a shortcut for `grep -e`) that supports the whole set of regexp syntax (grep's own, but all of it). `grep` without `-e` has a reduced set. BTW `egrep` has been around since [Unix System V](https://en.wikipedia.org/wiki/UNIX_System_V).

**Comment by silverwind** [comment]
Maybe replace `\s` with ` ` (a single space). Will break on tab thought.

**Comment by silverwind** [comment]
> We should use egrep

Our `grep -E` is equivalent to `egrep`, at least on Linux.

**Comment by zeripath** [comment]
can do [ \t] as far as I can see. I'm just trying to find the appropriate manpages.

**Comment by guillep2k** [comment]
>
> Our grep -E is equivalent to `egrep`, at least on Linux.

Oh, doh! 🤦‍♂  Of course. I just felt like remembering the good old times, that's all.

**Comment by guillep2k** [comment]
The problem is that we need to account for shell _and_ `make` escaping our characters.

**Comment by zeripath** [comment]
OK POSIX says that [:space:] should be supported in all locales so I think we can use that.

**Comment by zeripath** [comment]
as in `grep -Eo '[0-9]+\.?[0-9]+?\.?[0-9]?[[:space:]]'`
