### ISSUE TITLE
Squash merge message and compare incorrect following force-push

### ISSUE THREAD

**Issue by klinki** [go-gitea/gitea#10502]
- Gitea version (or commit ref): 1.11.1
- Git version: 2.25
- Operating system: Windows
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL) https://try.gitea.io/klinki/squash-merge-rebase-bug/pulls/1
  - [ ] No
  - [ ] Not relevant

## Description
Squash and merge functionality gets broken when branch is rebased.

It seems it caches original parent commit and when the parent changes (after rebase) it doesn't reflect those changes.

1) In commit message it shows unrelated messages from previous commits
2) After completing squash and merge it shows invalid commits in PR

Try looking at commit message on provided URL and also try doing squash and merge.

## Screenshots
![gitea-screenshot](https://user-images.githubusercontent.com/1476175/75446436-b6b46280-5967-11ea-86d0-e97950c056f3.png)

**Comment by zeripath** [comment]
Ok so presumably this is an issue with not recalculating the merge base each time.

Now this is strange because of the merge base is off then I think compare will probably be off too.

**Comment by zeripath** [comment]
So the likely problem is here:

https://github.com/go-gitea/gitea/blob/5abe1c52de533b52725b1e584db9fea6fb1b39ab/models/pull.go#L252

We should be regenerating the merge base from the base to the head.

**Comment by zeripath** [comment]
I've also changed the issue title as it is only the default suggested merge message that is incorrect.

**Comment by zeripath** [comment]
Ah there are two different issues here. Sorry I've misunderstood.

I've been looking at the merge messages only - these need to match the merge base we're actually going to use - now that could/should be precalculated in pull request checker.

Now, in the case of the compare after merge we need to use the merge base that we did use.

I think currently we may be showing commits that are on the base branch but are not on the head too - so it may be that we're doing the wrong diff.

**Comment by klinki** [comment]
wow, that was quick, thanks :) Can't wait to test new version with this fix!

**Comment by lunny** [comment]
resolved by #10605
