### ISSUE TITLE
og:image code

### ISSUE THREAD

**Issue by freecipher** [go-gitea/gitea#10528]
- Gitea version (or commit ref): 1.11.1

## Description
templates/base/head.tmpl
line 159 `<meta property="og:image" content="{{StaticUrlPrefix}}img/gitea-lg.png" />`
Should it be changed to
`<meta property="og:image" content="{{StaticUrlPrefix}}/img/gitea-lg.png" />`
？

**Comment by zeripath** [comment]
Yup.

**Comment by zeripath** [comment]
Please send a PR.

**Comment by 6543** [comment]
@lafriks why close this?

**Comment by jolheiser** [comment]
Fixed by #10531

**Comment by 6543** [comment]
ah - missed thsi pull (got merged fo fast ;) - and wasnt liked to this issue :+1:
