### ISSUE TITLE
Open issue count not updated when closing through commits/PR merges

### ISSUE THREAD

**Issue by bkraul** [go-gitea/gitea#10536]
- Gitea version (or commit ref): ge0ecddc11
- Git version: 1.12.0+dev-401
- Operating system: N/A
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes: https://try.gitea.io/bkraul/TestProject/issues/
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
Issue count indicators are not being properly updated when the issues are closed via commit messages or PR merges.

Steps to reproduce:
* Create a new issue.
* Add a commit to the project wit the `Closes #...` instruction.
* Push the commit.
* The issue will close as expected.
* The count of open issues will not be updated and you will still see the count as if the issue had not been closed.
* Restarting (recreating the docker container) updates the count.
...
### Issue created:
![image](https://user-images.githubusercontent.com/14616851/75561658-fed99080-5a0c-11ea-9ca7-2e87860cf870.png)

### Committing and pushing the change:
![image](https://user-images.githubusercontent.com/14616851/75561826-3cd6b480-5a0d-11ea-90e8-f9ab97448e1d.png)

### Issue closes, but count is not updated:
![image](https://user-images.githubusercontent.com/14616851/75561923-6394eb00-5a0d-11ea-8661-974c63434629.png)
![image](https://user-images.githubusercontent.com/14616851/75561969-77405180-5a0d-11ea-9ac1-1d070d566763.png)

This issue appears related to #10360, and was supposed to have been fixed by #10364 but it seems it is not.

**Comment by solaristhesun** [comment]
Please fix this. It makes me mad :/

**Comment by zeripath** [comment]
OK it looks to me like the correct values are calculated but then they are incorrect overwritten by another call to update repository...

**Comment by zeripath** [comment]
https://github.com/go-gitea/gitea/blob/89c94e2f8e871028492d5460fd3a10794f4ced1b/services/repository/push.go#L362-L365

Updates all the columns of the repository - overwriting the updated values.
