### ISSUE TITLE
Updating "Is Administrator" attribute for LDAP users on each login?

### ISSUE THREAD

**Issue by mikerenfro** [go-gitea/gitea#10538]
- Gitea version (or commit ref): 1.11.1
- Git version: 1.8.3.1
- Operating system: RHEL 7.7
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

It looks like the "Is Administrator" attribute for a user account is only set on initial account creation. We're authenticating all of our users from LDAP (specifically Active Directory), and we'd like to set their administrative access from the results of the Admin Filter query on each login. That is, if we remove a user from the group we use in the Admin Filter, they lose administrative access to Gitea on their next login.

**Comment by 6543** [comment]
this should be working with 1.11.1:  #8849
