### ISSUE TITLE
Bug Report : the release time does not change in mirror repositories which created in the older version gitea 

### ISSUE THREAD

**Issue by MFYDev** [go-gitea/gitea#10532]
- Gitea version (or commit ref):1.11.1
- Git version: latest
- Operating system: Ubuntu 18.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
Cause I could not create a mirror repo in 1.10 and then sync it in 1.11 
  - [ ] Not relevant
- Log gist:

## Description

Hi there,

I created a mirror repo in the Gitea 1.10 last month. Then I just found after I upgraded the Gitea to 1.11.1, the release time of the packages in the mirror repo cannot change. It remains at the same time as when it first be created. Please have a check on it and fix it. Thank you so much!

If you could not figure out what I am talking about. please refer to this URL: https://git.fanyangmeng.com/FanyangMeng/clash_for_windows_pkg/releases
...

## Screenshots
![Screenshot_2020-02-28 clash_for_windows_pkg](https://user-images.githubusercontent.com/53750381/75540291-b47d0180-5a56-11ea-82c5-24fbb7416a03.png)

**Comment by zeripath** [comment]
@FanyangMengDev is this still the case or did upgrade to 1.11.5 fix the issue?

**Comment by FanyangMengDev** [comment]
@zeripath Thank you for the update. This issue had already been fixed. I appreciate that so much.
Stay healthy mate and have a nice day!
