### ISSUE TITLE
Markdown issue for bold

### ISSUE THREAD

**Issue by alexanderadam** [go-gitea/gitea#10542]
- Gitea version (or commit ref): `1.12.0+dev-403-g154b137b6`
- Can you reproduce the bug at https://try.gitea.io:
  - yes: https://try.gitea.io/alexanderadam/636f7374-cherry.cr#user-content-contributors

## Description

Bold text within a table isn't rendered bold?

This code:
```markdown
|Bold text below|
|:---:|
|**[this should be bold](…)**|
```
should render like

|Bold text below|
|:---:|
|**[this should be bold](…)**|

## Screenshots
[github](https://github.com/636f7374/cherry.cr#contributors) on the left and [gitea](https://try.gitea.io/alexanderadam/636f7374-cherry.cr#user-content-contributors) on the right
![Screenshot_20200228_231225](https://user-images.githubusercontent.com/372620/75591431-fd957b80-5a7f-11ea-91e3-c130cfb2b2f4.png)

**Comment by sh7dm** [comment]
Looks like this is a bug in [goldmark](https://github.com/yuin/goldmark)

**Comment by alexanderadam** [comment]
Looks like or is a bug? Should I open a corresponding bug in goldmark?

**Comment by guillep2k** [comment]
@alexanderadam Does this help?
https://github.com/go-gitea/gitea/blob/421e7b7875d4ee71eeaec6e1e28a3758adcb55ce/go.mod#L99

**Comment by alexanderadam** [comment]
@yuin is incredibly fast and the [fix](https://github.com/yuin/goldmark/commit/21437947a30d8568d1fc1c4244da555c4576c6e3) is now in [goldmark version `1.1.24`](https://github.com/yuin/goldmark/tree/v1.1.24).
