### ISSUE TITLE
404 when selecting compare on code tab

### ISSUE THREAD

**Issue by KangoV** [go-gitea/gitea#1054]
- Gitea version (or commit ref): 1.0.0+323-gd4a7040
- Git version: 2.9.3
- Operating system: Ubuntu 16.10 (4.8.0-39-generic)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

Example [url](https://try.gitea.io/kango_v/testing_renamed/compare/master...kango_v:master)

## Screenshots

![image](https://cloud.githubusercontent.com/assets/3931807/23331622/921ddb52-fb61-11e6-8af2-113179d6ff55.png)

**Comment by lunny** [comment]
see #948

**Comment by KangoV** [comment]
oops, missed that, sorry.

**Comment by lunny** [comment]
Maybe you can help to confirm that.
