### ISSUE TITLE
suggest add reviewers status bar on PR page like github

### ISSUE THREAD

**Issue by a1012112796** [go-gitea/gitea#10550]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
hello , I think  that the reviewers status bar in github is usefull for  the review flow , It provide a way to request review from other people (I think it's different from Assignees , the Assignees means people who can chage this PR as author), and provide a clear summary for people who aprove and who request chages. I hope this feature can be realized on gitea. thanks.

## Screenshots
![jt1](https://user-images.githubusercontent.com/25342410/75622746-c1c4f800-5bde-11ea-9c80-c198b5fafa8e.jpg)
![jt2](https://user-images.githubusercontent.com/25342410/75622749-ca1d3300-5bde-11ea-9bd0-6190be4eaddd.jpg)
![jt3](https://user-images.githubusercontent.com/25342410/75622755-d3a69b00-5bde-11ea-9317-8df79916a7ee.jpg)

**Comment by bagasme** [comment]
@a1012112796 which milestone you'd like to see this feature?
