### ISSUE TITLE
User is unable to merge pull request when status checks are enable and selected

### ISSUE THREAD

**Issue by Codebreaker101** [go-gitea/gitea#10554]
- Gitea version: 1.11.1 
- Git version: 2.24.1
- Operating system: Alpine Linux 3.11.3 (Docker)
- Database
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
User is unable to merge pull request if status check is enabled and status checks selected whilst being in the merge whitelist individually or in a team. 

## Screenshots

When status checks are not enabled
![Screenshot from 2020-03-01 13-17-32](https://user-images.githubusercontent.com/16204269/75625566-9848a400-5bbf-11ea-99a7-d4b838395a10.png)
![Screenshot from 2020-03-01 13-17-52](https://user-images.githubusercontent.com/16204269/75625567-9aaafe00-5bbf-11ea-8046-d9ee2470df93.png)

When status checks are enabled
![Screenshot from 2020-03-01 13-18-21](https://user-images.githubusercontent.com/16204269/75625573-abf40a80-5bbf-11ea-8889-46a883a979bd.png)
![Screenshot from 2020-03-01 13-18-41](https://user-images.githubusercontent.com/16204269/75625574-ae566480-5bbf-11ea-83d8-315a6d159a24.png)

**Comment by jolheiser** [comment]
I believe this is fixed by #10318 and/or #10344, both of which should be released with `1.11.2`

**Comment by lafriks** [comment]
Closing, reopen if 1.11.2 does not fix your problem
