### ISSUE TITLE
Not possible to edit issue description anymore

### ISSUE THREAD

**Issue by MGChecker** [go-gitea/gitea#10558]
- Gitea version (or commit ref): 1.11.1
- Operating system: Debian Buster
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL): https://try.gitea.io/cezar97/Gitea_Issue_Logout/issues/4
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

In earlier versions, you were able to change the description of issues and PRs created by other users. This is no longer possible, which is very annoying for check lists etc.

**Comment by jolheiser** [comment]
This is possible if you are either an admin, or in an org team with the appropriate permission for modifying issues.

**Comment by lunny** [comment]
Posters and those who has write permissions to issue unit of the repository should be allowed to edit the issue descriptions.

**Comment by MGChecker** [comment]
@guillep2k  I think this is actually a regression.

Yes, they should be, but they are not in my experience. (I just realized, my example on `try.` is misleading there). Even though I am able to change labels, milestones, etc. I can not edit the issue description.

**Comment by silverwind** [comment]
Possibly related to https://github.com/go-gitea/gitea/pull/10576. Check if you see errors in the browser console related to `Transition`.

**Comment by silverwind** [comment]
@MGChecker please retry on try.gitea.io

**Comment by MGChecker** [comment]
> Possibly related to #10576. Check if you see errors in the browser console related to Transition.

There are quite some css errors, but I did not see anything mentioning transition. (This still works for issues you created, so I think probably some logic has changed there)

> @MGChecker please retry on try.gitea.io

I can not really create an example that is visible to all of you, since you would need to be collaborator in the repository to see this.

However, I have recreated and confirmed this behavior here: https://try.gitea.io/MGChecker/TestIssue/issues/1

**Comment by silverwind** [comment]
Ok thanks, so it sounds like a individual, unrelated issue.

**Comment by MGChecker** [comment]
Thank you very much!
