### ISSUE TITLE
Hide SVG (or more) from language stats panel.

### ISSUE THREAD

**Issue by Aragur** [go-gitea/gitea#10567]
- Gitea version (or commit ref): 1.12.0+dev-412-g4160bd6ef

## Description

It would be cool if you can configure which languages to hide in the language stats panel.  
If this is to much work, we could consider hiding svg by default, because that are mainly assets.

## Screenshots

![Screenshot_20200302_113201](https://user-images.githubusercontent.com/11004008/75668562-c8ed1400-5c79-11ea-8012-0ae5c26b7a3c.png)

**Comment by silverwind** [comment]
Agree on having an option, but nothing should be hidden by default so we stay neutral.

**Comment by ALZlper** [comment]
+1
