### ISSUE TITLE
[Bug] Incorrect Git command default timeout

### ISSUE THREAD

**Issue by camo-f** [go-gitea/gitea#10575]
Hi there,

- Gitea version (or commit ref): 1.11.1
- Git version: 2.24.1
- Operating system: Docker
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant

## Description
In the documentation, it is specified that `git.timeout.default` is set to **360** seconds. See https://docs.gitea.io/en-us/config-cheat-sheet/#git-timeout-settings-git-timeout
This is also the value documented here : https://github.com/go-gitea/gitea/blob/master/custom/conf/app.ini.sample#L877

This is not the case when starting the application without this setting, where the default is **60** :
The value is defined here : https://github.com/go-gitea/gitea/blob/master/modules/git/command.go#L25
Here default timeout is set with the previous value : https://github.com/go-gitea/gitea/blob/master/modules/setting/git.go#L53

This is quite misleading (in my case my update hook was crashing after 60 seconds without any apparent reason). Either the code or the documentation should be updated with the correct value (60 or 360).

A bit off-topic, but is there a reason why it is not possible to set every configuration value with Docker environment variables ?

Thanks in advance !

**Comment by lunny** [comment]
360 is more reasonable currently.
