### ISSUE TITLE
Feature Hidden Branches

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#10571]
Idear: like hidden issue but for a branch (to develop a securety fix or have specific secret files/infos/config versioned but be able po publish the rest ...)

**Comment by guillep2k** [comment]
I'm not sure it's possible using git. A `git fetch` will bring everything to the client. It will be more like a "treat with discretion" branch.

**Comment by 6543** [comment]
if git we can filt reverences of git I think this is posible ... but I dont know the internals how git fetch is handled so i only can gues for now

**Comment by zeripath** [comment]
At which point it starts to look a lot like a private fork...

**Comment by lunny** [comment]
We may could replace git http protocol when you read `refs/heads` and ssh protocol on `gitea serv`.

**Comment by zeripath** [comment]
It's not just the ref heads it's all the objects associated with the ref heads. You can't pack any objects from the private refs into packs that non authorized users can download.

Private branches are why gitlab can't support git v2 wire protocol. 

The best answer is probably to better support forks - allow porting of PRs between forks, perhaps allow private forks of org projects to permit team members etc.

**Comment by 6543** [comment]
I think this was a nice idear but a private fork can act similar ...

**Comment by 6543** [comment]
It looks like implementing would result in more resource usage and dev time ... so close it?

**Comment by a1012112796** [comment]
It's really attractive , but may be it was hard because of git's permission and hock system not have suport , may be we should directly do some change on git, to make it have more permission choices.
by the way, dose we have hidden issue function now, thanks.

**Comment by 6543** [comment]
@a1012112796  -> #3217 (no, we dont)
