### ISSUE TITLE
Wrong user ID throu api/v1/users/search

### ISSUE THREAD

**Issue by SonGokussj4** [go-gitea/gitea#10588]
- Gitea version (or commit ref): 1.1.1
- Git version: Docker gitea
- Operating system: docker gitea
- Database (use `[x]`): docker gitea Postres:9.6
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes (provide example URL)
    ## Python
	res = requests.get(f"https://try.gitea.io/api/v1/users/search")
    print(res.json())

## Description
Hi. I'm trying to get User IDs from api v1/users/search command.
This returns a json() of all users but all with 'id': 0

When trying through requests.get(f"{SERVER}/api/v1/admin/users?access_token={GITEA_TOKEN}"), it returns right ID.

When trying to search repos through /repos/search, it returns repositories with info of useres with their correct IDs. So it's not 'an admin thing'.

Is this a bug?
I'm trying to filter repos of conrete user. The best would be:
- /api/v1/repos/search?q={reponame}&?uname={username}
but this is not allowed so I have to find out 'uid'. But don't know how to do that if
- /api/v1/users/search
returns uids = 0 for all users.
...

**Comment by jolheiser** [comment]
If you are an admin and provide the token on the search endpoint it should return IDs as well.

**Comment by SonGokussj4** [comment]
> If you are an admin and provide the token on the search endpoint it should return IDs as well.

Yes. This works without a problem (tried that). I'm trying to have a cli app where user writes `my-gitea --list reponame username` and because /api/v1/repos doesn't support username as parameter, I need to somehow (for normal, **non-admin users**) to get user ids so I can connect username->uid.

It can be of course done by listing all existing repos, have a list of users and their IDs but that's overkill. I think when I meant in my issue is that the /api/v1/admin/users returning '0' as uid is a bug.

**Comment by jolheiser** [comment]
Currently it is considered normal behavior, though this could be a proposal to either return correct IDs or allow API endpoints to take usernames rather than (or as well as) IDs.

If I recall correctly, UIDs are not returned as a security measure.

**Comment by SonGokussj4** [comment]
If this is security measure, it shouldn't return any uid. And if that would be the case, I shouldn't get the uid from /repos/search query. 

So your proposal to return correct uids or to enable usernames rather their uid would be awesome.

**Comment by lunny** [comment]
Did you mean 1.11.1?

**Comment by SonGokussj4** [comment]
Possibly yes (I'm not near my computer now)
