### ISSUE TITLE
Cannot create pull request from V1 API

### ISSUE THREAD

**Issue by unnikrishnan-anil** [go-gitea/gitea#10592]
- Gitea version (or commit ref): 1.9.3
- Git version: 2.20.1
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:

I have been trying to create a pull request through the V1 API. The POST request I send is as follows:

http://localhost:3000/api/v1/repos/anil/test/pulls?token=<TOKEN>

Body:

> {
>   "assignee": "anil",
>   "base": "master",
>   "head": "branch2",
>   "title": "Testing PR"
> }

I get the following response:

> 422 Unprocessable Entity

> [
>     {
>         "fieldNames": [
>             "Head"
>         ],
>         "classification": "RequiredError",
>         "message": "Required"
>     },
>     {
>         "fieldNames": [
>             "Base"
>         ],
>         "classification": "RequiredError",
>         "message": "Required"
>     },
>     {
>         "fieldNames": [
>             "Title"
>         ],
>         "classification": "RequiredError",
>         "message": "Required"
>     }
> ]
> 

I tried using a git repo (https://github.com/dblueai/giteapy) and I get the same response. Has something changed or am I not passing the parameters the right way?

**Comment by jolheiser** [comment]
Are you sending the content with the correct `Content-Type` ? It should be `application/json`.  
What are you using to send the content?

**Comment by CatsNipYummy** [comment]
That's what it was! Stupid of me. Thanks @jolheiser
