### ISSUE TITLE
Theme only applies when logged out?

### ISSUE THREAD

**Issue by flatline-studios** [go-gitea/gitea#10606]
- Gitea version (or commit ref): 1.12.0+dev-429-gafa1e1af1
- Git version: 2.24.1
- Operating system: Docker - gitea/gitea:latest
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist: ???

## Description
When I change the theme in `/data/gitea/conf/app.ini`, so that it reads:
```
...

[repository.upload]
TEMP_PATH = /data/gitea/uploads

[ui]
DEFAULT_THEME = arc-green

[server]
APP_DATA_PATH    = /data/gitea
...
```
The theme will change on public facing pages, i.e., those before I've logged in... But as soon as I log in, everything returns to regular light/gitea theme.

## Screenshots

![2](https://user-images.githubusercontent.com/12387378/75917005-3f903a00-5e51-11ea-9a2b-4cc088f5cfc1.png)

![1](https://user-images.githubusercontent.com/12387378/75916894-0bb51480-5e51-11ea-9168-40636217b1b9.png)

**Comment by jolheiser** [comment]
You need to change it in your account settings, e.g. https://try.gitea.io/user/settings/account.  
Each user can change their preferred theme.

**Comment by flatline-studios** [comment]
Holy chips that was fast. Thanks. :)
