### ISSUE TITLE
SSH Address with port Error

### ISSUE THREAD

**Issue by ynifamily3** [go-gitea/gitea#10609]
- Gitea version (or commit ref):1.12.0+dev-409-g14f3593f2
- Git version: 2.24.1
- Operating system: Docker image: gitea/gitea:latest
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
If i set up ssh address, **with port**
it seems
 git@ssh://mydomain:(port number):user/repo
but it is not correct,
The correct is
➜  ssh://git@ssh.mydomain:(port number)/user/repo
...

## Screenshots
<img width="435" alt="스크린샷 2020-03-05 오전 9 26 09" src="https://user-images.githubusercontent.com/13795765/75935749-828af580-5ec3-11ea-8de3-bd52feacfff1.png">

**Comment by zeripath** [comment]
hmm... I don't understand how this has happened.

The CloneLinks are shown here:

https://github.com/go-gitea/gitea/blob/6420f17fb6351e0ed37c7fda2c5bd3746dfbea90/templates/repo/home.tmpl#L118-L122

https://github.com/go-gitea/gitea/blob/6420f17fb6351e0ed37c7fda2c5bd3746dfbea90/templates/repo/home.tmpl#L125-L127

And are generated by this code:

https://github.com/go-gitea/gitea/blob/6420f17fb6351e0ed37c7fda2c5bd3746dfbea90/modules/context/repo.go#L471

Which calls:

https://github.com/go-gitea/gitea/blob/6420f17fb6351e0ed37c7fda2c5bd3746dfbea90/models/repo.go#L875-L991

As you can see in the code there is no way for the `git@` to end up in front of the `ssh://` unless you have misconfigured your `SSH_DOMAIN`

So... what does your app.ini look like?
