### ISSUE TITLE
Allow `backticks` in issue titles, PR titles and commits(?)

### ISSUE THREAD

**Issue by alexanderadam** [go-gitea/gitea#10601]
- Gitea version (or commit ref): `1.12.0+dev-429-gafa1e1af1`
- Demo on Gitea: https://try.gitea.io/alexanderadam/spectator/issues/1

## Description

I'm not sure what's left to say but it would be great if backticks in issue titles would be supported.
According to it's maintainer, [goldmark provides an "_easy way_" to do this](https://github.com/yuin/goldmark/issues/106#issuecomment-594445602).

## Screenshots
Left is how it could be and right is [Gitea](https://try.gitea.io/alexanderadam/spectator/issues/1).
![Screenshot_20200304_084808](https://user-images.githubusercontent.com/372620/75856583-ec889980-5df4-11ea-825d-9e0dbba09fd3.png)

**Comment by lafriks** [comment]
I don't think GitHub does support that either
![image](https://user-images.githubusercontent.com/165205/75860475-8e63b280-5e04-11ea-8b93-16aa0968733a.png)

**Comment by alexanderadam** [comment]
Oh, my fault! Indeed! It came through [a browser extension](https://github.com/sindresorhus/refined-github#global) that I use! :laughing: 

What do you think about it in general.

**Comment by lafriks** [comment]
I have no much opinion tbh. It would require custom markdown rendering implemented to allow only backticks but no other markdown syntax and need to add that in quite some places where issue title is displayed to be consistent.

**Comment by silverwind** [comment]
The question is, where would it stop? If you render issue titles with `<code>`, PR titles would need the same treatment, which in turn means commit descriptions would need it too for conistency.

I really think commit descriptions should be left as-is to render the same as in a terminal. I don't really like the link replacement that both gitea and GitHub do because it makes a commit description not copyable in verbatim.

**Comment by alexanderadam** [comment]
> If you render issue titles with `<code>`, PR titles would need the same treatment, which in turn means commit descriptions would need it too for conistency.

Yes, absolutely! I totally agree that all three places should have the backtick logic. I mean, people are using them anyway in commits, as they know it from other places:

* https://github.com/go-gitea/gitea/commit/dbba46c2161c673b7818b6602ea2fb4efffe224e
* https://github.com/go-gitea/gitea/commit/55daee8d22c964f2f7b362d0f5e6a7031bbd535d
* https://github.com/go-gitea/gitea/commit/6d0f78542f4c8bc9ca73dde0c6ed3671251fed20
* https://github.com/go-gitea/gitea/commit/714dcf9dadf38841bf2ddd2a9e2633e9ad074b74
* https://github.com/go-gitea/gitea/commit/2f10bfa0f6a463eb0b890cb19e3c974a1abeaa8a
* https://github.com/go-gitea/gitea/commit/2f10bfa0f6a463eb0b890cb19e3c974a1abeaa8a
…

![Screenshot_20200304_205351](https://user-images.githubusercontent.com/372620/75917431-47081100-5e5a-11ea-9894-e5ed3ab1a3ad.png)

So I guess it would be a natural thing to render it like what people had in mind when they used the backticks.

**Comment by alexanderadam** [comment]
> I don't think GitHub does support that either
> ![image](https://user-images.githubusercontent.com/165205/75860475-8e63b280-5e04-11ea-8b93-16aa0968733a.png)

**Update:** [now it does](https://twitter.com/natfriedman/status/1372917225993080849).

Or how Nat put this:

> kind of crazy we didn't do this before

:laughing:

**Comment by silverwind** [comment]
Yeah I actually find it quite nice that GH now does it too, so I think we can go ahead with this.

**Comment by Wuzzy2** [comment]
I support this feature. It is obviously a good thing, as it makes titles more readable. If someone implements it, please don't forget to add documentation for it, otherwise it'll be a "secret feature". :D

**Comment by yardenshoham** [comment]
Does #21432 close this?

**Comment by delvh** [comment]
Yep, I think so.
