### ISSUE TITLE
feature request: add organisation wide deploy key

### ISSUE THREAD

**Issue by jclain** [go-gitea/gitea#10615]
- Gitea version (or commit ref): 1.10.3
- Git version: not relevant
- Operating system: Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

there already is org-wide webhook. have you considered adding org-wide deploy key?
I'd like to be able to automatically build / deploy all repositories in an organisation, but for now I have to add the deployment ssh key to each repo individually

TIA, regards,
Jephté

**Comment by lafriks** [comment]
As a workaround is to create service user to add to the organization team with needed rights

**Comment by jclain** [comment]
yes... indeed... don't know why I didn't think about this :-/
also, thinking about it, it's a better solution than creating a org wide deploy key, because you can track what did which service account
well... consider my feature request closed as far as I'm concerned :-)
