### ISSUE TITLE
crash: 1.11.1 randomly crash with SIGBUS when creating an issue

### ISSUE THREAD

**Issue by dujiulun** [go-gitea/gitea#10638]
- Gitea version (or commit ref): 1.11.1 - official docker image
- Git version: 2.24.1
- Operating system: Docker image (Ubuntu)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:
https://gist.github.com/dujiulun/72436d34e939b082d1fa6a36b305de05

## Description
Gitea will randomly crash when I create an issue.

It crashed earlier today; after it was restarted, I created two more issues with no problem. Tonight when I tried to create another, it crashed again.

The log shows SIGBUS, which looks like #2311, which was supposed to be fixed.

**Comment by lunny** [comment]
Looks like a bblot problem used by bleve.

**Comment by guillep2k** [comment]
My suggestion is to delete the current bleve indexes from the indexer directory so Gitea will rebuild them anew. **This procedure must be performed while the instance is shut down**. For example:

```
# cd /var/lib/gitea/indexers # Your directory may be different
# ls -l
total 0
drwx------ 2 git git  67 Oct  9 00:23 issues.bleve
drwxr-xr-x 2 git git 158 Feb  9 23:05 issues.queue
drwx------ 2 git git  67 Oct 14 22:59 repos.bleve
# rm -r issues.bleve repos.bleve
```

**Comment by bagasme** [comment]
@guillep2k thanks for the workaround

**Comment by zeripath** [comment]
I think this is fixed so I am going to close this. Please reopen if still an issue
