### ISSUE TITLE
pull request to a template repository

### ISSUE THREAD

**Issue by yee379** [go-gitea/gitea#10630]
- Gitea version (or commit ref): 1.11.1
- Git version:
- Operating system: dockerhub image
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ X ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ X ] Not relevant
- Log gist:

## Description

I'm making use of 'Make a repository a template'; there are cases where the new repos that are created with this Template has modifications that i would like to merge back 'upstream'. however, there appears to be no way to do this via the 'Pull Requests' -> 'New Pull Request'.

**Comment by jolheiser** [comment]
In this case you should fork the template repo and make a PR with changes.

Repos generated from the template aren't necessarily intended to stay true to the template repo itself and thus aren't usually considered targets for merges.
