### ISSUE TITLE
bug: protected branch: pull check

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#10636]
Gitea version: 1.12.0+dev-447-g123d38605

if you enable branch protection and leave all default beside "Enable Status Check" the pull merge-status is considderted as not mergable! (only force mergable via admin rights)

to reproduce:
A: enable branch protection
B: enable Status Check **with: no status checks found in the last week ..."

result:
* user with write access:
![Bildschirmfoto zu 2020-03-06 13-57-23](https://user-images.githubusercontent.com/24977596/76085517-7df13a80-5fb2-11ea-9a34-43a0ca795ddc.png)

* user with admin access:
![Bildschirmfoto zu 2020-03-06 13-57-55](https://user-images.githubusercontent.com/24977596/76085508-7af64a00-5fb2-11ea-9ae9-6b3340b96da5.png)

**Comment by 6543** [comment]
solution: either dont let status checks enable if there is no one or fix pull-check-mergable function

**Comment by 6543** [comment]
#10648 didnt close this!

**Comment by 6543** [comment]
you need 2 users.

1. Create a new repo (initialized)
2. change readme to new branch & open a pull request
3. add user2 to repo as colaborator with write permission
4. enable branch protection for master & set "Enable Status Check"
5. view pull with user2 you will see this:

![Bildschirmfoto zu 2020-03-07 22-16-46](https://user-images.githubusercontent.com/24977596/76152579-5b9a1280-60c1-11ea-91d7-92bc67952647.png)

**Comment by lunny** [comment]
Is this a UI problem?

**Comment by 6543** [comment]
look's like one - there is NO server error

**Comment by 6543** [comment]
stil here :(
