### ISSUE TITLE
Gitea 1.11.1 Upgrade fails because of configfile changes?

### ISSUE THREAD

**Issue by cht47** [go-gitea/gitea#10642]
- Gitea version (or commit ref): 1.11.1
- Git version: 2.16.5
- Operating system: CentOS 7.6.1810 
- Database (use `[x]`):
  - [x] PostgreSQL 10
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:
[C] Failed to start server: open /gitea/custom/custom/https/cert.pem: no such file or directory

## Description
Updating from 1.10.4 to 1.11.1 won't work out of the box in special circumstances.

as you see in the log gist it adds a second custom, I removed the custom from the config file then Gitea finds the certificate. 
Second Bug is now on the startpage instead of my old text there is only written "app_desc" as placeholder.

So I wonder how many changes has been made in the config file from 1.10 to 1.11. 
It would be very helpfull if you add the changes to breaking changes for upgrading. On monday I will compare the current config file from github with my configfile. 

## Screenshots
![image](https://user-images.githubusercontent.com/2283180/76101782-4349cb00-5fcf-11ea-835a-44d09da40aa5.png)
![image](https://user-images.githubusercontent.com/2283180/76101946-86a43980-5fcf-11ea-948a-f85af9eaae0f.png)

**Comment by jolheiser** [comment]
`app_desc` is a locale change and only affected if you use custom locales or template. This was briefly labeled as a breaking change but I think the label was removed erroneously.

The cert file change was https://github.com/go-gitea/gitea/pull/9868 which is labeled as breaking.

**Comment by jolheiser** [comment]
As well, both are correctly labeled as breaking in the blog post.
https://blog.gitea.io/2020/02/gitea-1.11.0-is-released/#1-11-0
