### ISSUE TITLE
Gitea 1.11.2 - Logout Shows 404

### ISSUE THREAD

**Issue by leomoon** [go-gitea/gitea#10643]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant (try.gitea.io is using older version)
- Log gist:

## Description
I just upgraded from gitea 1.11.0 to 1.11.2.

When clicking logout link, user will be redirected to this URL:
https://gitea-url.com/user/logout
but it will show error 404.
...

**Comment by jolheiser** [comment]
Are you using a custom template?

**Comment by leomoon** [comment]
No. I'm using the dark theme that comes with Gitea.
