### ISSUE TITLE
official docker image: tag "1" downgraded from 1.11.1 to 1.10.5

### ISSUE THREAD

**Issue by dujiulun** [go-gitea/gitea#10657]
- Gitea version (or commit ref): 1.10.5 / 1.11.1
- Git version: Not relevant
- Operating system: Docker
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
I use the official docker image (gitea/gitea)[https://hub.docker.com/r/gitea/gitea] with tag "1" because I want to stay on the 1.x branch. Previously it was mapped to 1.11.1. Today when I restart and re-pull the image, my gitea version is downgraded to 1.10.5.

IMHO semantic tags like "1" or "1.11" should always point to the latest version in that branch and not go backwards.

## Screenshots
![gitea-docker](https://user-images.githubusercontent.com/5555270/76143759-07893100-60b5-11ea-9390-0773b50da457.png)

Tag "1" has the same digest as 1.10.5.

**Comment by 0x5c** [comment]
I got the same problem on my end. The migration code wasn't happy about that

**Comment by techknowlogick** [comment]
I've re-tagged the docker images. This is now fixed.
