### ISSUE TITLE
Cannot push/pull to freshly migrated Gitea

### ISSUE THREAD

**Issue by netorica** [go-gitea/gitea#10658]
- Gitea version (or commit ref):
- Git version: 1.11.1
- Operating system: Ubuntu
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
I have successfully migrated my gitea to another server following the documentation here
https://docs.gitea.io/en-us/backup-and-restore/

The old and new server has not software difference except that the new server has bigger disk space and a additional 8GB memory from the old one.

Now I am facing issues with pushing to git repositories that i have an access to push and pull before. 

I was able to push to pull/push when i have just delete and reinsert again my old pub key. I am worrying about my other 12 users that cannot push or pull anymore as 5 of them are servers. Is there a possible way that the keys can someone be refreshed internally?

The paths are not different at all, everything is almost the same even the migrated gitea version

Any ideas that could help solve my issues?

Thanks
...

**Comment by guillep2k** [comment]
Please migrate to 1.11.2 (out as of yesterday), there are critical bugfixes that probably affect your issue.

**Comment by zeripath** [comment]
Following that you will likely need to do the Resynchronise Hooks task from the admin settings page.
