### ISSUE TITLE
ui: 1.11.2 user avatar is missed in the header navbar

### ISSUE THREAD

**Issue by RiverVanRain** [go-gitea/gitea#10659]
- Gitea version (or commit ref): 1.11.2
- Git version: 2.11.0
- Operating system: Debian
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description
User avatar is not displayed after upgrading Gitea from 1.11.1 to 1.11.2.
All caches (system / browser) were cleared but this didn't help.
...

**Comment by guillep2k** [comment]
Hi, I can't reproduce. Would you please give us more information?:

1. Is every user affected?
2. Can you change your avatar? Does that have any effect?
3. Check the generated HTML and see what URL is given for that avatar.
4. Check the network log in the browser, check the server's response for the avatar picture (is it 404?).
5. Check Gitea's logs and see if the avatar is actually served. Make sure `ENABLE_ACCESS_LOG` is set to `true` so all accesses are logged. You should see something like:

```
172.30.2.250 - - [07/Mar/2020:12:08:46 -0300] "GET /avatars/08a4754bc70fb29d15eb938b0dc5de18 HTTP/1.1" 200 3610 "\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:73.0) Gecko/20100101 Firefox/73.0"
```

A final question: are you using a docker installation?

**Comment by RiverVanRain** [comment]
1. Yes, it's.
2. I did it. Nothing. I've removed the custom avatar even but the problem is still.
3. In the browser's console is:
`<span class="text"></span>`
Instead of [source](https://github.com/go-gitea/gitea/blob/master/templates/base/head_navbar.tmpl#L80).
4. I've checked - all responses are OK with 200 status.
Also, I haven't this problem in other places on the site (e.g. in the 'Switch Dashboard Context', on the User's profile, timeline) but on the header navbar only.
5. Got it. All responses have `200` status.

No, i'm not using a docker installtion.

All browser's extensions and firewall are disabled. 
Trying with the latest Chrome on the Windows 10.

I will try on Firefox right now.

**Comment by zeripath** [comment]
hmm... I wonder if it could be related to this: #10653 
(Maybe we need this workaround in 1.11 #10655 too?)

**Comment by guillep2k** [comment]
Only thing I can think of is that you're using a custom template that relies on something that has changed? A git blame doesn't show anything useful:

https://github.com/go-gitea/gitea/blame/v1.11.2/templates/base/head_navbar.tmpl

(lines 74-79)

Even when you've linked the template from `master`, the version from `1.11.2` linked above doesn't differ much in this aspect.

The template itself doesn't have any conditionals in that part, so if `<span class="text">` appears, it _must_ be followed by `<img class="ui tiny avatar image" width="24" height="24" src="...">`, even if the image had a bad link.

Just in case, we're talking about this, aren't we?

![image](https://user-images.githubusercontent.com/18600385/76152879-87a69b00-60a3-11ea-8238-0a1e7eb7adef.png)

**Comment by guillep2k** [comment]
Did you build from sources? Because if you did, there's a 1 in 8 chance the build went wrong, as @zeripath pointed out. If you did, could you try building again (`make clean-all ; make`)? If you didn't, could you tell us the exact source of your binary? Maybe one of our generated binaries went wrong like that.

**Comment by RiverVanRain** [comment]
@guillep2k Yes, I've custom template but it doesn't change this piece of code:

```
<div class="ui dropdown jump item poping up" tabindex="-1" data-content="{{.i18n.Tr "user_profile_and_more"}}" data-variation="tiny inverted">
				<span class="text">
					<img class="ui tiny avatar image" src="{{.SignedUser.RelAvatarLink}}">
					<span class="sr-only">{{.i18n.Tr "user_profile_and_more"}}</span>
					<span class="mobile-only">{{.SignedUser.Name}}</span>
					<i class="fitted octicon octicon-triangle-down not-mobile" tabindex="-1"></i>
				</span>
				<div class="menu user-menu" tabindex="-1">
					<div class="ui header">
						{{.i18n.Tr "signed_in_as"}} <strong>{{.SignedUser.Name}}</strong>
					</div>
```
This worked on version 1.11.1 before today's updating to 1.11.2:
![screenshot-2020 03 08-01_14_26](https://user-images.githubusercontent.com/2176145/76153236-5e553180-60da-11ea-8ffa-c70d2709eeec.png)

I have been using Gitea since v1.8.6.
Gitea was installed [from binary](https://docs.gitea.io/en-us/install-from-binary/) for Linux/Debian not from sources.
Subsequent updates were the same...

**Another weird thing:**
When I go to any page on the site the avatar appears for a short time and then disappears again.
As I wrote above, I turned off all browser extensions and cleared all caches.
Something (JS? CSS?) cuts out a piece of code between these tags: `<span class="text"></span>`
I tried in different layout modes using DevTools but that also doesn't help.

I've created screencast in slow motion:
![screen](https://user-images.githubusercontent.com/2176145/76154272-949aad00-60ea-11ea-8c87-eec51d680a1d.gif)

Thanks for your great support!

**Comment by silverwind** [comment]
> Maybe we need this workaround in 1.11 #10655 too

Not needed, 1.11 still has statically vendored fomantic-ui, the custom build is only in 1.12.

Regarding this issue: Maybe is is a bad JS cache? Try setting `ui.USE_SERVICE_WORKER = false` and then force-reload the page (CTRL-Shift-R in Firefox). Also I'd try removing any custom templates.

**Comment by RiverVanRain** [comment]
@silverwind Thanks for advice but I can't find this option via `about:config` in Firefox.
Also, I `CTRL+Shift+R` always.
Maybe need to say about my browsers' versions: Chrome 80.0.3987.116 \ Firefox 73.0.1

> Also I'd try removing any custom templates.

I did it, clean the caches. Nothing.
Seems, it's the browser's issue.

**Comment by zeripath** [comment]
I wonder if it's something to do with the dropdown accessibility js?

**Comment by silverwind** [comment]
`ui.USE_SERVICE_WORKER` is in `app.ini` of Gitea. You can also temporarily disable `dom.serviceWorkers.enabled` in Firefox's `about:config`.

> I wonder if it's something to do with the dropdown accessibility js?

Certainly seems possible. I suggest https://github.com/go-gitea/gitea/issues/10672 for its removal.

**Comment by RiverVanRain** [comment]
@zeripath Ah.. Understand now. I will do it.

**Comment by RiverVanRain** [comment]
@silverwind Tricks with service worker didn't help.

**Comment by duchenpaul** [comment]
@RiverVanRain  Just try to click avatar button in the settings
![image](https://user-images.githubusercontent.com/8120099/76305143-8e314e80-62ff-11ea-9b96-6c551ed12887.png)

**Comment by RiverVanRain** [comment]
@duchenpaul Just [read this](https://github.com/go-gitea/gitea/issues/10659#issuecomment-596103318).

**Comment by silverwind** [comment]
>  Something (JS? CSS?) cuts out a piece of code between these tags: <span class="text"></span>

Check in Browser devtools if the HTML response comes with the expected tags. At least then you'll know whether JS is interfering. CSS can not remove tags so should be of no concern.

**Comment by lafriks** [comment]
I can not seem to reproduce this on 1.11.3

**Comment by RiverVanRain** [comment]
@silverwind Checked already and can' t see any errors. All responses are OK (200 or 302 statuses).
Just the missed piece of code:
![devtools](https://user-images.githubusercontent.com/2176145/76465693-34ac4b00-63f7-11ea-82b4-20183f787d2c.png)

@lafriks Updating to 1.11.3 didn't solved this issue.

**Comment by RiverVanRain** [comment]
Checked on the several OS and browsers (_even Midori ;)_) - same results.

**Comment by silverwind** [comment]
I meant yoou should go to the network tab, find the / request and check response payload and see if the missing HTML is there or not.

**Comment by RiverVanRain** [comment]
I understood what you meant and as I've answered - all responses are ok; I can't find any missed HTML.

**Comment by RiverVanRain** [comment]
Well.
Here's how I fixed it.

1 - In the `head_navbar.tmpl` changed this code:
`<img class="ui tiny avatar image" src="{{.SignedUser.RelAvatarLink}}">`
on 
`<img class="ui avatar image" src="{{.SignedUser.RelAvatarLink}}">`
2 - Stopped gitea.
3 - Cleared the caches.
4 - Started gitea again.

Now all works very well.

Thanks all for help. Issue is closed.

**Comment by guillep2k** [comment]
Now I'm **very** intrigued. It's clear that some JS was removing the image, but why? Why adding a size would help? (maybe it depends on the image type e.g. SVG has no intrinsic size?).

**Comment by RiverVanRain** [comment]
I can’t say what’s going on.

First, I replaced my avatar with the site logo and it worked:
`<img class="ui image" src="{{StaticUrlPrefix}}/img/logo.png">`

Then I decided to remove one of the classes `tiny` and it worked again:
`<img class="ui avatar image" src="{{.SignedUser.RelAvatarLink}}">`

I began to understand what was happening and found a mismatching in the source code about which I wrote in my comment above.
