### ISSUE TITLE
feature-request: Improve PR review comments

### ISSUE THREAD

**Issue by Unarelith** [go-gitea/gitea#10656]
- Gitea version (or commit ref): 1.11.0

## Description

Gitea is great, when when it comes to reviewing pull requests, there's some flaws I'd like to discuss.

- It's impossible to edit or delete a review comment from the "Conversation" tab
- There's no "Resolve conversation" button (like on GitHub), making reviewing a pain for both maintainers and contributors because it's hard to keep track of already resolved comments
- ~~The full page is reloading when adding a review comment, and then moving to back to the comment. Most of the time this is ok, but on very small machines running Gitea, it takes a lot of time...~~ Nevermind there's already https://github.com/go-gitea/gitea/issues/8861 for this.

**Comment by Unarelith** [comment]
Keep it alive

**Comment by aloosley** [comment]
I would also really like to see a resolve conversation option. 

We are working on our first decent sized PR on Gitea.  Mostly it's gone well, but the commenting is a mess!  A resolve conversation option would go along way.

**Comment by bendem** [comment]
I'm confused, are you asking for this (this is a screenshot from gitea itself)?
![image](https://user-images.githubusercontent.com/2681677/86752794-e70bbc00-c03f-11ea-804f-ede64a81a8e0.png)

**Comment by lunny** [comment]
@aloosley It's already implemented but maybe you are using an old version gitea.

**Comment by aloosley** [comment]
> @aloosley It's already implemented but maybe you are using an old version gitea.

Thanks @lunny , I didn't see it had been added.   I can confirm the feature is there when I use 1.12.1.  Thank you!
