### ISSUE TITLE
git lfs pushed files are empty

### ISSUE THREAD

**Issue by markus-seidl** [go-gitea/gitea#10665]
- Gitea version (or commit ref): 1.11.2
- Git version: 2.17.1; git-lfs 2.3.4
- Operating system: Ubuntu 18.04
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant; LFS not enabled on try.gitea.io !
- Log gist: https://gist.github.com/markus-seidl/c9f51da5e5855d811581970517e0b339

## Description

I try to push files from a client repository that has LFS enabled. LFS is enabled on the server and the push succeeds. Also the settings page of the repository lists the files as stored in the repository with their correct sizes.
However, on the next 
* clone
* Zip download of the repository
* Or direct download via web ui
the files are empty or result in a 500 error. The 500 is, because the files are not there.

**Comment by markus-seidl** [comment]
The solution is: The server didn't have access to the lfs directory and was swallowing the exception / warning / error.

I would suggest the exception about not being able to access the lfs directory should show up somewhere :)

**Comment by zeripath** [comment]
I was about to say that your logs looked a bit sparse... 

Looking at the code error should have been passed to the client at least - which is also incorrect because these errors might need sanitising.

*Sigh* I guess I'll have to go through and add logging to this.

**Comment by zeripath** [comment]
Oh yeah I remember git-lfs may keep hitting the server if it gets a 500! So returning 500 for a permanent error will cause badness.

**Comment by markus-seidl** [comment]
Thank you very much! @zeripath
