### ISSUE TITLE
heatmap: untranslated string: xx total contributions in the last 12 months

### ISSUE THREAD

**Issue by dadosch** [go-gitea/gitea#10669]
## Description

The string in the heatmap is not translated:

xx total contributions in the last 12 months

https://github.com/go-gitea/gitea/blob/062f35109df236a06a00d403d006b90760f9cfac/web_src/js/features/userHeatmap.js#L82

**Comment by a1012112796** [comment]
ping ...

**Comment by dadosch** [comment]
it is still a issue

**Comment by Ryuno-Ki** [comment]
The code was refactored into

https://github.com/go-gitea/gitea/blob/d9b50e4fd126e60fe0735bafbcb12d0e8f6dd0c2/web_src/js/components/ActivityHeatmap.vue#L3-L5

**Comment by Ryuno-Ki** [comment]
Given https://github.com/julienr114/vue-calendar-heatmap/issues/19 it might be worth looking for alternatives (once Vue 3 migration is to start).

https://github.com/go-gitea/gitea/blob/d9b50e4fd126e60fe0735bafbcb12d0e8f6dd0c2/web_src/js/components/ActivityHeatmap.vue#L8-L9

reference

https://github.com/go-gitea/gitea/blob/d9b50e4fd126e60fe0735bafbcb12d0e8f6dd0c2/web_src/js/components/ActivityHeatmap.vue#L39-L42

and wouldn't be translated either.

A fork exists as TypeScript project at https://www.npmjs.com/package/vue3-calendar-heatmap

**Comment by lunny** [comment]
> Given [julienr114/vue-calendar-heatmap#19](https://github.com/julienr114/vue-calendar-heatmap/issues/19) it might be worth looking for alternatives (once Vue 3 migration is to start).
> 
> https://github.com/go-gitea/gitea/blob/d9b50e4fd126e60fe0735bafbcb12d0e8f6dd0c2/web_src/js/components/ActivityHeatmap.vue#L8-L9
> 
> reference
> 
> https://github.com/go-gitea/gitea/blob/d9b50e4fd126e60fe0735bafbcb12d0e8f6dd0c2/web_src/js/components/ActivityHeatmap.vue#L39-L42
> 
> and wouldn't be translated either.
> 
> A fork exists as TypeScript project at https://www.npmjs.com/package/vue3-calendar-heatmap

We still stayed in Vue2 currently.

**Comment by wxiaoguang** [comment]
I have a feeling that there might not be too many blockers for upgrading to Vue3. And since the usage of Vue2 in Gitea is still at an early stage, if enough people agree, we should try to upgrade to Vue3.

**Comment by Ryuno-Ki** [comment]
I'm [migrating another project to Vue 3](https://codeberg.org/lerntools/base) currently. My learnings from there:

- make sure you are on Webpack 5 (as far as I can tell, that's already the case)
- read https://v3-migration.vuejs.org/
- introduce the migration build
- start refactoring

Can we reference this issue in a new issue about Vue 3?
There are different places (like documentation etc) that would need updates, so some kind of meta-issue could help to keep track of them.
