### ISSUE TITLE
Dropzone editing issues

### ISSUE THREAD

**Issue by silverwind** [go-gitea/gitea#10666]
There seems to be a bug when editing dropzone attachments. To reproduce:

- Create issue
- Reply to issue
- Edit the reply and add a attachment, save
- Edit the reply and remove the attachment, save
- Attachment still shows.

It does appear to work on the first message in a issue, but not on any subsequent ones.

**Comment by alexanderadam** [comment]
Is it related to #677 / #6563?

**Comment by zeripath** [comment]
Is this still an issue?

**Comment by CrustyApplesniffer** [comment]
is this still an issue ?

**Comment by 6543** [comment]
I think https://github.com/go-gitea/gitea/pull/13036 close this
