### ISSUE TITLE
Offline mode still trying to load css from googleapis

### ISSUE THREAD

**Issue by zsxsoft** [go-gitea/gitea#10679]
- Gitea version (or commit ref): 1.12.0+dev-2-g3fc4f3670
- Git version:
- Operating system: Arch Linux
- Database (use `[x]`):
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
This is **NOT** a duplicate of https://github.com/go-gitea/gitea/issues/4871

This `semantic.min.css` will still load fonts from googleapis in offline modes:
https://try.gitea.io/fomantic/semantic.min.css?v=6598fed08fd8c85879b3e60fbb9a81b3

And I found lots of googleapis in CodeMirror plugin: https://github.com/go-gitea/gitea/search?q=googleapis&type=

**Comment by silverwind** [comment]
This is a consequence of the workaround for https://github.com/go-gitea/gitea/issues/10653. We have to wait until next Fomantic UI release.
