### ISSUE TITLE
error on trying to show wiki page

### ISSUE THREAD

**Issue by spesoul** [go-gitea/gitea#10689]
After go forward to wiki page , The page shown as below

template: repo/wiki/view:48:14: executing "repo/wiki/view" at <(not $.DisableHTTP) (and (not $.DisableSSH) (or $.IsSigned $.ExposeAnonSSH))>: can't give argument to non-function not $.DisableHTTP

**Comment by sigma-frossignol** [comment]
This has been fixed by #10684
