### ISSUE TITLE
Code comments are not invalidated if the line they reference is removed

### ISSUE THREAD

**Issue by CirnoT** [go-gitea/gitea#10686]
- Gitea version (or commit ref): 288e487232e90fab04b4d69e063ae6f93af19c37
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL) https://try.gitea.io/CirnoT/checkInvalidation/pulls/1
  - [ ] No
  - [ ] Not relevant

## Description
The code comment is not invalidated (marked as outdated) if line it is referencing is removed by future commit. Example can be seen on https://try.gitea.io/CirnoT/checkInvalidation/pulls/1/commits. The comment was made against lines that were removed in `a25e77b1d3` however it is not marked as outdated and attempting to comment on it will raise HTTP 500:

```
[E] CreateCodeComment: LineBlame ... exit status 128 - fatal: file ... has only ... lines
```

**Comment by lakostin** [comment]
Have the same issue. If i commented line number 100 in file, and in next commit file was reduced to 90 lines, after which someone tries to reply to this comment he gets 500 error.

**Comment by CirnoT** [comment]
The error is partially expected, you shouldn't be able to reply on outdated code comments. The underlying issue is the fact that comment is not being marked as outdated.

**Comment by guillep2k** [comment]
Personally I'd like to reply to outdated comments, like in GitHub.

**Comment by lakostin** [comment]
> The error is partially expected, you shouldn't be able to reply on outdated code comments. The underlying issue is the fact that comment is not being marked as outdated.

500 error could not be expected.
One more time: I have 20 lines file, i comment last line, then i delete first 10 lines and get and error trying to reply on the comment to this last line. That shouldn't be an error.

**Comment by CirnoT** [comment]
https://github.com/go-gitea/gitea/issues/5455 @zeripath

**Comment by melmus** [comment]
Sometimes when I add comment in pull request, I have 500 error.

**Comment by twostarsmco** [comment]
I just encountered this exact issue. Trying to reply on the comment to 67th line of the file, which has been reduced to 66 lines on the latest commit, I get:

```
2020/06/05 09:21:37 .../repo/pull_review.go:50:CreateCodeComment() [E] CreateCodeComment: LineBlame[refs/pull/4/head, /data/git/repositories/username/reponame.git, ProjectName/Class1.cs, 67]: exit status 128 - fatal: file ProjectName/Class1.cs has only 66 lines

2020/06/05 09:21:37 ...s/context/context.go:139:HTML() [D] Template: status/500
2020/06/05 09:21:37 .../repo/pull_review.go:50:CreateCodeComment() [E] CreateCodeComment: LineBlame[refs/pull/4/head, /data/git/repositories/username/reponame.git, ProjectName/Class1.cs, 67]: exit status 128 - fatal: file ProjectName/Class1.cs has only 66 lines
```
