### ISSUE TITLE
/repos/issue/search API is broken

### ISSUE THREAD

**Issue by davydov-vyacheslav** [go-gitea/gitea#10690]
I'm trying to get list of all open PR within the system via API. When I'm trying to execute `/repos/issue/search` API request (even without search parameters, even without authentication -- just `curl -X GET "https://try.gitea.io/api/v1/repos/issues/search"`) I'm retrieving the following error: `Find: too many SQL variables`

* Gitea version: 1.12.0+dev-3-g9269b7f62
* full request:`curl -X GET "https://try.gitea.io/api/v1/repos/issues/search?state=open&type=pulls" -H "accept: application/json" -H "authorization: Basic ZGF2c0BqYXZhbml4LmNvbTpkYXZ5ZG92dnY="`

P.S. I have local system of 1.11.2 version and don't have such issue.

**Comment by jolheiser** [comment]
Underlying SQL problem is related to #7750 and #9841

**Comment by davydov-vyacheslav** [comment]
unstale please

**Comment by 6543** [comment]
Does it still happen?

**Comment by a1012112796** [comment]
> Does it still happen?

![image](https://user-images.githubusercontent.com/25342410/83025877-b3616d80-a061-11ea-8530-d0d93509b305.png)

**Comment by zeripath** [comment]
The problem is this:

```go
	for page := 1; ; page++ {
		opts.Page = page
		repos, count, err := models.SearchRepositoryByName(opts)
		if err != nil {
			ctx.Error(http.StatusInternalServerError, "SearchRepositoryByName", err)
			return
		}

		if len(repos) == 0 {
			break
		}
		log.Trace("Processing next %d repos of %d", len(repos), count)
		for _, repo := range repos {
			switch isClosed {
			case util.OptionalBoolTrue:
				issueCount += repo.NumClosedIssues
			case util.OptionalBoolFalse:
				issueCount += repo.NumOpenIssues
			case util.OptionalBoolNone:
				issueCount += repo.NumIssues
			}
			repoIDs = append(repoIDs, repo.ID)
		}
	}
```

This extracts all of the repo IDs that the search options could have found - I.e. Every repo that the user has access to... (Even worse than that it actually extracts all the repos out of the db.)

then: 
```go
	if len(keyword) > 0 && len(repoIDs) > 0 {
		issueIDs, err = issue_indexer.SearchIssuesByKeyword(repoIDs, keyword)
	}
```

plugs them all back in to a single SQL query.

On a big site like try there are likely easily >900 repos that a user could see - SQLite limits the number of variables to 999.

We shouldn't be doing it this way

**Comment by 6543** [comment]
@zeripath we could replace repoIDs with a xorm.builder query witch we can join within SearchIssuesByKeyword as we have already done elsewhere

**Comment by zeripath** [comment]
Exactly

**Comment by 6543** [comment]
are you going for it?

**Comment by zeripath** [comment]
Or should I say: genau

**Comment by zeripath** [comment]
Nope I've played enough with reposearch recently - if I touch it again :fire: may ensue

**Comment by 6543** [comment]
haha - OK I'll give it a try

**Comment by zeripath** [comment]
Remember whatever you do it needs a backport...

**Comment by 6543** [comment]
😓

**Comment by 6543** [comment]
ok the sittuation is worse than i thought

**Comment by zeripath** [comment]
Now you see why I only commented and didn't fix ...

**Comment by 6543** [comment]
> @zeripath we could replace repoIDs with a xorm.builder query witch we can join within SearchIssuesByKeyword as we have already done elsewhere

this is not posible as it use the Indexer and the whole Indexer would need arewrite/refactory
so #11664 split In query up into multible one combinde by OR
