### ISSUE TITLE
1.10.5 is not a bugfix release, it seems to be 1.12-dev

### ISSUE THREAD

**Issue by oaxiento** [go-gitea/gitea#10692]
- Gitea version (or commit ref): 1.10.5
- Git version: -
- Operating system: Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

We upgraded to 1.10.5 today and expected a bugfix release. After the upgrade we noticed major changes in the UI and several database migrations in our logfile. **This version seems to be 1.12-dev and not 1.10.5.** It should be taken down immediately.

We then "upgraded" 10.1.5 to 1.11.2, but honestly, we are not sure if this messed up our Gitea instance.

Is there any guide how to roll back Gitea including the database to an older version?

**Comment by lafriks** [comment]
I don't think there were backward incompatible changes in database but you should always do at minimum database backup before upgrade

**Comment by lafriks** [comment]
v1.10.6 tagged and fixes this issue

**Comment by oaxiento** [comment]
@lafriks Thanks for your reply and the quick fix. The database changes didn't seem to have any impact on 1.11.2 but there where several colums added. Anyway, I did a manual diff and cleanup so we do not get any problems in the future.

Believe me I know, a backup is always a good idea, and we do have backups. The problem is, that we have several commits, pushes and pulls per minute. We are also dependent on it with our build pipelines. So if I have a database backup, I would need a filesystem backup of all repositories from the same time as well. Otherwise we have some kind of "split-brain" between the database an the filesystem. After the first start, this backup would be kind of worthless, as any rollback would have several implications. I don't know of any way to "resync" repositories with the database (e.g. creating releases) as deleting the repository and pushing it again.
