### ISSUE TITLE
[Bug] Login form : "remember" checkbox not sumbitting on "Enter" when focused

### ISSUE THREAD

**Issue by KaKi87** [go-gitea/gitea#10705]
- Gitea version (or commit ref): 1.11.2
- Git version: 2.11.0
- Operating system: Debian 9.12
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (https://try.gitea.io/user/login)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

I often use keyboard-only navigation on websites forms, but Gitea's login form doesn't work properly for this matter.

Here is the detailed process of my navigation :

0. The username/e-mail input is automatically focused *(this is very great by the way)*
1. I type my username
2. I press `Tab`, thus focusing on the password input
3. I type my password
4. I press `Tab`, thus focusing on the "remember" checkbox
5. I press `Space` to toggle the checkbox *(to checked state, since since initially in unchecked state)*
6. I press `Enter` to submit the form

Expected result : the form is submitted. *(You can test the very same method on plenty of other websites without any problem)*

Actual result : the checkbox is toggled *(to unchecked state, since previously in checked state)*

Temporary solution : between step 5 and 6, I must press `Tab` again to focus on the submit button, which shouldn't normally be necessary since the checkbox is in the same form as the rest *(following the same logic, pressing `Enter` while username/e-mail and password inputs are focused will trigger submit, which is indeed a normal behavior)*.

## Screenshots

*Just displaying a screenshot of the login page wouldn't help very much since it is the same page for everyone. Ideally, I would make a video with keyboard actions in subtitles and blurred password field, but it's really overkill.*

Thanks !

**Comment by KaKi87** [comment]
Up

**Comment by vosdev** [comment]
This is still reproducable on https://try.gitea.io/user/login


I go through the exact 6 same steps as you do and it really bugs me out.. every single time i try to login.

**Comment by KaKi87** [comment]
Hello, any news on this ? Thanks

**Comment by lunny** [comment]
Nobody are working on this.

**Comment by Gusted** [comment]
Had a quick look, seems like our UI framework was causing this: #18851 disables it.
