### ISSUE TITLE
Avatars stretching issue in assignee filter in "issues" list

### ISSUE THREAD

**Issue by arianrad** [go-gitea/gitea#10702]
- Gitea version (or commit ref): 1.12.0+dev-239-g391e0638c
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description
Avatars in assignee filters are stretched. They are not square anymore. I see this issue since 2 month ago.
## Screenshots

<img width="213" alt="Screen Shot 2020-03-10 at 10 00 46 PM" src="https://user-images.githubusercontent.com/5629794/76347188-6d76f200-631b-11ea-8d4d-1e15ab282fef.png">

**Comment by zeripath** [comment]
Is this still an issue?
