### ISSUE TITLE
Forked repository's avatar missed.

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#10711]
see https://gitea.com/lunny/tea

**Comment by guillep2k** [comment]
Should the avatar be reproduced (i.e. always in sync) or copied?

**Comment by mrsdizzie** [comment]
Should be copied I think as a fork is just a copy of what it was at the time

**Comment by lafriks** [comment]
Or we could just show forked repo avatar if repo does not have its own

**Comment by lunny** [comment]
@zeripath It seems this has been resolved.
