### ISSUE TITLE
Expand/Collapse file when compare code failed

### ISSUE THREAD

**Issue by wgqimut** [go-gitea/gitea#10728]
- Gitea version (or commit ref):1.11.3
- Git version: 1.8.3.1
- Operating system: Centos7 
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ x] No
  - [ ] Not relevant
- Log gist:

## Description
When I expand file in the compare code view, it doesn't work, but at a review code view, the expand file is just fine. 

When I inspect element, I find the web report a error "ReferenceError: Can't find variable: SimpleMDE" at the `jquery.min.js:1386`
...

**Comment by guillep2k** [comment]
Currently (1.12.0+dev-211-g316db0fe7) it's not working for expansion of short chunks in the review page either:

![image](https://user-images.githubusercontent.com/18600385/80433369-19c16780-88cd-11ea-98bd-73487fdcf45c.png)

**Comment by Ibmurai** [comment]
The same problem exists in 1.12.1 - I'm not sure if the root cause is still the same.

**Comment by zeripath** [comment]
I think this is fixed already. OP please reopen if not.
