### ISSUE TITLE
Heatmap always loading.

### ISSUE THREAD

**Issue by sloong** [go-gitea/gitea#10736]
- Gitea version (or commit ref): lastest with Docker
- Git version: 2.24.1
- Operating system: Ubuntu
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:

## Description
The service is running in docker, and use Nginx as the proxy service. nginx service port NOT 80/443.
The heatmap alwasy show loading. But when I forced to refresh, It's OK.
My web browse is Edge with Chromium. 

## Screenshots

![1](https://user-images.githubusercontent.com/11831154/76738047-d68bb900-67a4-11ea-817f-98f3c162d7a8.gif)

**Comment by lunny** [comment]
This should be a known issue.

**Comment by lafriks** [comment]
check if you have any errors in browser console log

**Comment by sloong** [comment]
![image](https://user-images.githubusercontent.com/11831154/76744326-05a72800-67af-11ea-9b8b-7ff614498dcb.png)
This is the error log.  And same as the problem phenomenon, when I forced to refresh, no any errors.

**Comment by sloong** [comment]
I think the problem is the URL port NOT 80/443. but when i change port to 443, it's OK. and chenge to other port, it's happened.

**Comment by lafriks** [comment]
What is your `ROOT_URL` in app.ini?

**Comment by sloong** [comment]
![image](https://user-images.githubusercontent.com/11831154/76748752-45bdd900-67b6-11ea-8f55-550d20368548.png)

**Comment by silverwind** [comment]
URL seems fine. Does the devtools network tab reveal any error on the request for `userheatmap.js`? Maybe also try other browsers.

**Comment by sloong** [comment]
I can see two errors in network tab.
![image](https://user-images.githubusercontent.com/11831154/76815978-033de000-683a-11ea-9cd3-44355c9a3616.png)

**Comment by silverwind** [comment]
Possibly.

The dropzone error is unrelated, it was fixed in https://github.com/go-gitea/gitea/commit/984b85c1a72f9f1561447a8492bc3d33a87e3641.

**Comment by silverwind** [comment]
I had this happen once too. Clearing browser cache resolved it. Unsure what's happening, I had ServerWorker disabled.

**Comment by sloong** [comment]
In edge Version 81.0.416.72 (Official build) (64-bit), it's ok .so it should be a edge bug.
