### ISSUE TITLE
Unable to override avatar_default.png

### ISSUE THREAD

**Issue by silverwind** [go-gitea/gitea#1074]
- Gitea version (or commit ref): 1.0.2
- Git version: 2.11.1
- Operating system: Linux
- Database (use `[x]`):
  - [x] MySQL
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Not relevant

## Description

Using a build without bindata, I'm able to override images like `gitea-lg.png` and `favicon.png`, but not `avatar_default.png` through placing them in `custom/public/img`.

**Comment by pgaskin** [comment]
Do you have Gravatar enabled? If you do, then you will not be able to override the default avatar.

**Comment by tboerger** [comment]
You can overwrite any file the origins from the `public/` folder within `custom/public/`

**Comment by silverwind** [comment]
Got it fixed, it was actually my fault. My `STATIC_ROOT_PATH` was pointing to a wrong path.
