### ISSUE TITLE
Not possible to logout sometimes

### ISSUE THREAD

**Issue by chref** [go-gitea/gitea#10740]
- Gitea version (or commit ref): 1.11.3
- Git version: 1.8.3.1
- Operating system: CentOS 7.7.1908
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description

Since the logout action was turned into a POST request (i.e. since 1.11.2) I cannot reliably log out of Gitea. Sometimes it works, often it doesn't.
When it doesn't work, the browser simply refreshes the page I am currently viewing, and no POST request to /user/logout gets logged by the reverse proxy.
I have a feeling that this might be some kind of race condition, because I was able to set a breakpoint in the Javascript handler code for the link action and to single-step through it (with Firefox's built-in Inspector), which then lead to the logout request being sent successfully.

## Screenshots

n/a

**Comment by jolheiser** [comment]
Shoot, I implemented it to avoid having a blank `#` anchor, but perhaps if this issue persists it would be a better solution.

**Comment by iamdoubz** [comment]
I also experienced this behaviour. It stemmed from me having a custom template that did not reference the new code applied to logging out. For me, I had to copy the new templates, and re-add in my custom items and the logging out issue went away.

**Comment by chref** [comment]
> I also experienced this behaviour. It stemmed from me having a custom template that did not reference the new code applied to logging out. For me, I had to copy the new templates, and re-add in my custom items and the logging out issue went away.

I don't think that is the same issue. In your case you wouldn't have had the link action on the Logout menu item due to old templates. In my case the action is there, but sometimes it doesn't get executed correctly client-side.

**Comment by bugreport0** [comment]
Is it possible that this bug also holds for the Time Tracker? I'm having the described issue with 'Sign Out' not working, but I also can't seem to start the time tracker. Stopping works at times. I reverted to 1.11.1 because of this.

**Comment by jolheiser** [comment]
That sounds like a new issue, as the stopwatch is using a correct form as far as I can tell. I think it may use some JS, though, so it could be a JS problem.

**Comment by bugreport0** [comment]
@jolheiser Just upgraded to Gitea 1.11.4 and the Time Tracker works again. I'm pretty sure it might've been affected by the same bug as I couldn't get it to work on 1.11.3. Thanks for fixing this, even thought it might've been unintended!
