### ISSUE TITLE
Turn autocomplete off for branch  selection

### ISSUE THREAD

**Issue by tobias1012** [go-gitea/gitea#10757]
- Gitea version (or commit ref): Stable (1.11.1
- Git version: ALL
- Operating system: GNU/LINUX Debian
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist: Not relevant

## Description

When clicking the button to change branches the autocomplete pops off on google chrome and thus doesn't allow for the user to choose the upper branches before clicking out of that box (Wich can be hard as it needs to be done within that box)

This could be easily solved by either changing all CSS for the given class, making a new class for no autocompletion or inputting an attribute in the template file 

## Screenshots

![image](https://user-images.githubusercontent.com/29657183/76949156-6d24bb00-6908-11ea-9b45-b4e909d57d5f.png)

**Comment by zeripath** [comment]
This would likely be a very easy pr.

**Comment by aceArt-GmbH** [comment]
Input has since got `autocomplete="off"` https://github.com/go-gitea/gitea/blob/ac8d71ff07a3354a27d6a5daab45d1e79e242269/web_src/js/components/RepoBranchTagSelector.vue#L17

**Comment by wxiaoguang** [comment]
Already fixed by 

* #15809
