### ISSUE TITLE
Chrome Console log "Uncaught TypeError" when you click language-stat bar[With solution]

### ISSUE THREAD

**Issue by L0veSunshine** [go-gitea/gitea#10759]
- Gitea version (or commit ref):1.12.0-dev
- Git version:unrelated
- Operating system:unrelated
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes **every repo‘s home page**
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
When you through a link go to a repo's home page(exclude flush the repo's homepage), as you click language stat bar, the console will log error like this 
![image](https://user-images.githubusercontent.com/19653204/76960260-0d550100-6956-11ea-8b19-e8abc83137b4.png)
After you flush the page and click the bar again the error will disappear, but when you enter a new repo's homepage the error will appear again.
## Solution
https://github.com/go-gitea/gitea/blob/ed5140d2353a1d3721db73c5fcba19b67e22931d/templates/repo/sub_menu.tmpl#L36-L40
In this template the element is **a** but it misses the attributes “href”.
Two solution
1 add href="javascript:void(0);" to the a label.
2 change the a label to div, and add "cursor: pointer" in less file. So the style will not change at all.

**Comment by silverwind** [comment]
I can't seem to reproduce. Can you provide clear steps or click on the line number of the error and show the surrounding code?

**Comment by L0veSunshine** [comment]
> I can't seem to reproduce. Can you provide clear steps or click on the line number of the error and show the surrounding code?

click into a repo's homepage and click the language stat bar.The error will appear.

**Comment by L0veSunshine** [comment]
![hx199651-Gitea_-Git-with-a-cup-of-tea-Google-Chrome-2020-03-19-10-45-50](https://user-images.githubusercontent.com/19653204/77026979-f5ba5e80-69cf-11ea-9fc5-c0f8da948ba6.gif)
![image](https://user-images.githubusercontent.com/19653204/77026988-fc48d600-69cf-11ea-877d-e536ff40619c.png)
Here is the version and gif

**Comment by silverwind** [comment]
Tried that in Chrome, Firefox and Safari, no luck.

What Chrome version is that?

Also, please show a screenshot of the code the Chrome debugger shows when clicking on that `VM2412` link.

**Comment by L0veSunshine** [comment]
My chrome version is 70, i don't like the new version's layout.
Did you reproduce this error? if you did't i will close this issue.

**Comment by L0veSunshine** [comment]
![image](https://user-images.githubusercontent.com/19653204/77046731-78f2a900-69fe-11ea-82b3-1d495983b5d8.png)
I had fix this issue. If there is no one had met this error, i will close this error.

**Comment by L0veSunshine** [comment]
more digital
![image](https://user-images.githubusercontent.com/19653204/77047396-9d02ba00-69ff-11ea-8b15-f6a0ef9d5db4.png)

**Comment by silverwind** [comment]
No, I never reproduced, but I only tested Chrome 80 and the issue may be specific to that old Chrome version. That said, I think we can just change the `<a>` to `<div>`.

**Comment by L0veSunshine** [comment]
I had try firefox73 and last version of edge. the error didn't appear again. Maybe this error only on old version's chrome.

**Comment by L0veSunshine** [comment]
This issue seems don't need handle.If you willing to do change a to div, don't forget to add css sytle "cursor:pointer".
sorry for border you.😅
