### ISSUE TITLE
UI: Admin panel - Log Configuration output don't wrap

### ISSUE THREAD

**Issue by cez81** [go-gitea/gitea#1075]
- Gitea version (or commit ref): 5bd22a2f4abe69ffb23e14cacad0ff1e75ee08d4
- Git version: 2.7.4
- Operating system: Ubuntu 16.04.2 LTS (fresh install)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x ] Not relevant

## Description
Log configuration output breaks UI when using files. Line is to long and doesn't wrap.

## Screenshots
![log_configuration](https://cloud.githubusercontent.com/assets/9416498/23342038/f9850df0-fc52-11e6-8aea-ab47cc06344a.png)

**Comment by lunny** [comment]
It seems we have resolved this problem before?

**Comment by tboerger** [comment]
I can't remember that we solved that

**Comment by bkcsoft** [comment]
Maybe we can pretty-print it?

**Comment by lunny** [comment]
I don't know how to do that. :)

**Comment by tboerger** [comment]
Just parse the json and print it indented. And maybe set the column to overflow auto

**Comment by lunny** [comment]
resolved by #1097
