### ISSUE TITLE
Use scorch index type for bleve

### ISSUE THREAD

**Issue by L0veSunshine** [go-gitea/gitea#10751]
- Gitea version (or commit ref):1.12.0-dev
- Git version:2.11
- Operating system:Debian9
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:
 Don't need
## Description
The bleve indexer file was too large. 
I have found that the bleve has two index type, refer this [https://github.com/blevesearch/bleve/issues/783](https://github.com/blevesearch/bleve/issues/783)
The current index type gitea used is no longer actively maintained.
We should replace boltdb with bbolt. I had a try. It works fine, and the index file size decrease about 80%.
May i pull a request or wait someone handle it.

**Comment by techknowlogick** [comment]
We've already switched to bbolt, and you'll see that it was me that contributed most of the PR to bleve to switch for this exact purpose.

**Comment by L0veSunshine** [comment]
But i found the content in index_meta.json was not {"storage":"scorch","index_type":"scorch"} but {"storage":"boltdb","index_type":"upside_down"}.

**Comment by L0veSunshine** [comment]
> We've already switched to bbolt, and you'll see that it was me that contributed most of the PR to bleve to switch for this exact purpose.

My statement may be inaccurate, I mean we should use the new index form-Scorch.

**Comment by techknowlogick** [comment]
> My statement may be inaccurate, I mean we should use the new index form-Scorch.

In that case I will re-open. Thank you for suggestion :)

**Comment by L0veSunshine** [comment]
https://github.com/go-gitea/gitea/blob/ed5140d2353a1d3721db73c5fcba19b67e22931d/modules/indexer/code/bleve.go#L188
My attempt is use another bleve api to init a index, it can specify the storage type and index type
`indexer, err := bleve.NewUsing(path, mapping, "scorch", "scorch", nil)` 

Then you need remove the previous index file and re-index, and you will find the size of index file decrease drastically.

It was a big change to indexer, we should consider cautiously about the user update to the new index type.

**Comment by L0veSunshine** [comment]
> > My statement may be inaccurate, I mean we should use the new index form-Scorch.
> 
> In that case I will re-open. Thank you for suggestion :)

The bleve library lack concrete document, and i was confused in some concept. Sorry for this misleading title.

**Comment by lunny** [comment]
@L0veSunshine I would like you create a new indexer type `bleve-scorch` so that it will not break the previous index. Pull request is welcome!!!

**Comment by L0veSunshine** [comment]
In order to change the index type, the code only need change a little. But the index file will change completely.
You meaning give user a choice to select the index type? I think no one will select the previous index type, because of it's enormous size. I think it is necessary to change the index type thoroughly. The key issue is how to smoothly transition

**Comment by lunny** [comment]
Add a new indexer type `bleve-scorch` and make it as default if user cannot set the type. And user could delete old indexer files and set to the new type.
We can use the new implementation share most codes with the previous codes.

**Comment by lafriks** [comment]
Wouldn't it be possible to convert index file? Like opening old index, creating new with other name and then streaming all records from one to other. When successfully done old one could be deleted.

**Comment by L0veSunshine** [comment]
> Add a new indexer type `bleve-scorch` and make it as default if user cannot set the type. And user could delete old indexer files and set to the new type.
> We can use the new implementation share most codes with the previous codes.

The only difference of creating two types index is this line:
**The original type**
``indexer, err := bleve.New(path, mapping)``
content in **index_meta.json** file is``{"storage":"boltdb","index_type":"upside_down"}``
**The scorch type**
``indexer, err := bleve.NewUsing(path, mapping, "scorch", "scorch", nil)``
content in **index_meta.json** file is``{"storage":"scorch","index_type":"scorch"}``

I think lafriks's solution was the best. But i am a beginner in golang. I am afraid i can't implement this because of it needs to consider a vary of compatibility issues😅.
I found the new index type it by accident,i had try it a period of time and it has no difference with previous type meanwhile it's size decrease obviously. I open this issue aim to share this discovery with yours.
Thanks for listening❤

**Comment by L0veSunshine** [comment]
You may try it on a experimental instance, to see the actual effect, and decide whether the index type worths to change.

**Comment by guillep2k** [comment]
If different kinds of indexes will be used, we'd need to update the way we handle the rupture file (i.e. include the type of indexer).

**Comment by lafriks** [comment]
I would prefer we would support only one index type

**Comment by lunny** [comment]
So we should have a new bleve index gitea version, so that when upgrade Gitea, the index will be regenerated.

**Comment by lunny** [comment]
It seems we have upgraded to scorch when upgraded to bleve search v2, so I just close this one.
