### ISSUE TITLE
Can't use gitea for Linux kernel source code fork

### ISSUE THREAD

**Issue by fkasumovic** [go-gitea/gitea#10762]
- Gitea version (or commit ref): 1.11.3
- Git version: 2.17.1
- Operating system: ubuntu 18.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

Can't use gitea for Linux kernel source code fork or any big repository. Fails to open in web interface with error 500 and error message 'context deadline exceeded'.
I know you received similar complains before for slow load on big repositories, but I thought that it's important for you to know that gitea does not work for any larger repository. It's not just kernel, there are other projects that can't load on gitea, but kernel might be most popular choice among this big repositories :-).

One solution might be ability to turn off preview of last commit message in repository view.
I would be happy with it, its least important feature of them all, and tells nothing important about file or folder.

## Screenshots

![Screenshot 2020-03-18 at 20 24 03](https://user-images.githubusercontent.com/139872/76999161-80f70e00-6956-11ea-9427-9df2d05c8985.png)

**Comment by lunny** [comment]
You could change git.timeout to a longer time.

**Comment by zeripath** [comment]
It's also helpful to give us some of the logs so we can definitely which git command is timing out.
