### ISSUE TITLE
wiki function of migrated repo result in 500

### ISSUE THREAD

**Issue by w6m6** [go-gitea/gitea#10768]
- Gitea version (or commit ref):
- Git version: 1.11.2
- Operating system: Centos 7
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X ] No
  - [ ] Not relevant
- Log gist:

## Description

when we create a repo using New Migration function, the wiki of migrated repo results in 500, logs of gitea goes for 
`2020/03/19 17:55:20 routers/repo/wiki.go:134:renderViewPage() [E] GetBranchCommit: reference not found`
while when create a new repo. the wiki of new repo works correctly.

## Screenshots

![截屏2020-03-19下午6 04 10](https://user-images.githubusercontent.com/28854175/77055571-16a0a500-6a0c-11ea-87f1-9702431230cf.png)

**Comment by lunny** [comment]
Could you try v1.11.3?

**Comment by w6m6** [comment]
upgrade  to 1.11.3 remains the same error. 
By the way, the repo was migrated from gitlab.

**Comment by lunny** [comment]
@w6m6 Is that a private repository or a public one? If it's a public one. could you paste that link here?

**Comment by w6m6** [comment]
it's an internal repo,  i'm afraid that  i could only provide the log files if necessary. :(

**Comment by zeripath** [comment]
I suspect this is fixed by #10676 - which I will backport presently.

**Comment by lunny** [comment]
@zeripath It's a wiki related problem, maybe not.

**Comment by zeripath** [comment]
@lunny the issue is that the code explicitly checks if the ref does not exist expecting a git.ErrNotExists (or the like) but actually it receives a plumbing.ErrRefNotExists (again exact name I can't remember) this means that a server error is called instead of the error being handled.

@w6m6 would it be possible for you to check on the release/v1.11 or master branches that this is fixed?

**Comment by w6m6** [comment]
@zeripath  sorry，i dont have a compile env currently. We could take it a try  if there is a binary file.

**Comment by w6m6** [comment]
@zeripath It seemed that this bug was fixed in the latest version 1.11.4. thx a lot.
