### ISSUE TITLE
Deleting user crashes Gitea

### ISSUE THREAD

**Issue by kleszcz** [go-gitea/gitea#10770]
- Gitea version (or commit ref): 1.9.3
- Git version: 2.11.0
- Operating system: Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description
Every time I try to delete a user Gitea shutsdown and I'm getting 502 Proxy Error. Deleting repositories works fine, only users make problem.

**Comment by lunny** [comment]
@kleszcz v1.9.x is not maintained any more. Please upgrade to v1.10.6 or v.11.3. And please notice that don't upgrade to v1.10.0 ~ v1.10.5 or v1.11.0 ~ v1.11.1 .
