### ISSUE TITLE
Milestone filter in Issues section

### ISSUE THREAD

**Issue by ejouvin** [go-gitea/gitea#10777]
- Gitea version (or commit ref): 1.11.3
- Git version: 2.20.1
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
When access to Issues, we can filter them.

In section "Open", the Milestone filter display only open milestone.
In section "Closed", the Milestone filter display only closed milestone. But I was expected to be able to filter closed issue according an in progress milestone.

Notice that it is possible.
First, I go to "Open" section for issues.
Then I filter on the expected Milestone.
Then I go to "Closed" section. In this case, the Milestone filter is applyed.

...

## Screenshots

Display issues in "Open" section with a milestone selected
![image](https://user-images.githubusercontent.com/8817923/77143623-09bf9800-6a84-11ea-909a-79b06ed2e2ea.png)

Display issues in "Closed" section, same milestone filter as previous screen capture, selected milestone not displayed.
![image](https://user-images.githubusercontent.com/8817923/77143686-2c51b100-6a84-11ea-80f2-2762d2a3db92.png)

**Comment by yp05327** [comment]
If I understand correctly, I think this is fixed.
