### ISSUE TITLE
感觉官网的安装说明不是很到位，把自己的安装过程写下来，仅供参考，也希望官网能够更新一下

### ISSUE THREAD

**Issue by wuxs231** [go-gitea/gitea#10788]
文章地址：
https://blog.csdn.net/weixin_39358657/article/details/105017040

**Comment by a1012112796** [comment]
Hello , Please use english on github, because many contributors don't know chinese. suggest you add to our QQ group: 328432459. If you have some ideas about docs change , welcome to change it by PR.
