### ISSUE TITLE
can't push, web interface crash a lot

### ISSUE THREAD

**Issue by flavienhaas** [go-gitea/gitea#10783]
- Gitea version (or commit ref): 1.11.3 built with GNU Make 4.1, go1.13.8 : bindata, sqlite, sqlite_unlock_notify
- Git version:
- Operating system: Debian 9 container
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant

## Description
hi, I’m running into some issues and I’m running out of ideas to solve them.  I’m behind a NAT and I only have one IPv4 public address so the web interface is behind a reverse proxy on another machine (simple Nginx proxy_pass of the http://x.x.x.x:3000 with certificates for https). to use ssh I redirected a port on my NAT and it has been working perfectly until now: I can’t push on anything I’m getting these kind of errors:

```
 flavien@pluto | ~/S/U/2/j/Projet_JAVA_P2P_STRI2A | on refactorServerManagement ⇡1 ❯ git push
Gitea: Internal Server Error
Get http://localhost:3000/api/internal/serv/command/2/flavien/projet_java_p2p_stri2a?mode=2&verb=git-receive-pack: dial tcp [::1]:3000: connect: connection refused
fatal: Impossible de lire le dépôt distant.

Veuillez vérifier que vous avez les droits d'accès
et que le dépôt existe.
                                                                                                                                                   
 flavien@pluto | ~/S/U/2/j/Projet_JAVA_P2P_STRI2A | on refactorServerManagement ⇡1 ❯ git push
Énumération des objets: 9, fait.
Décompte des objets: 100% (9/9), fait.
Compression par delta en utilisant jusqu'à 8 fils d'exécution
Compression des objets: 100% (5/5), fait.
Écriture des objets: 100% (5/5), 434 octets | 434.00 Kio/s, fait.
Total 5 (delta 4), réutilisés 0 (delta 0)
remote: Gitea: Internal Server Error
remote: Unable to contact gitea: Post http://localhost:3000/api/internal/hook/pre-receive/flavien/projet_java_p2p_stri2a: dial tcp [::1]:3000: connect: connection refused
Gitea: Internal error
UpdatePublicKeyInRepo: Post http://localhost:3000/api/internal/ssh/2/update/28: dial tcp [::1]:3000: connect: connection refused
To git.flavien.ovh:flavien/Projet_JAVA_P2P_STRI2A.git
 ! [remote rejected] refactorServerManagement -> refactorServerManagement (pre-receive hook declined)
error: impossible de pousser des références vers 'git@git.flavien.ovh:flavien/Projet_JAVA_P2P_STRI2A.git'
```

at some point (~20 attempts) it says that everything is up to date and it has been pushed. Is there anything a can make to have it work the first time? don't hesitate to ask if I forgot to give something, thanks

**Comment by lafriks** [comment]
Please check gitea.log for errors
