### ISSUE TITLE
[Feature Request] Ability to delete commits (because sensitive information)

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#10782]
Sometimes it happens that you accidentally push some sensitive information to your git repository, like passwords or real name, etc.

On GitHub you can contact the support team and they can help you in deleting these private information and keep it without traces (it doesn't appear in commit history).

I suggest there should be a feature in Gitea so that an admin user can delete commits from both the Gitea database and the Git repository in the file system, meaning it would be just like if the commit wouldn't ever have been pushed in the first place.

Citation needed: Should the repository owner themselves be able to delete the commits?

Additionally, pull requests should also be deleteable.

**Comment by lafriks** [comment]
Most of the actions should be done by rewriting git history on client and then force pushing, same with PR
