### ISSUE TITLE
Disable login by user / password but keep openId connect

### ISSUE THREAD

**Issue by weeman1337** [go-gitea/gitea#10793]
- Gitea version (or commit ref): 1.11.3

## Description

I wonder if it's possible to remove the login fields but keep the "open id connect" login button.  
Event better would be directly trying to authenticate via "open id connect".

I've played around with the config but had no luck so far.

## Screenshots

![image](https://user-images.githubusercontent.com/6216686/77249526-e6dae280-6c41-11ea-9cb3-651cad0e42bf.png)

**Comment by lunny** [comment]
You can customerize the login page.

**Comment by weeman1337** [comment]
Thanks for the fast response.

> You can customerize the login page currently.

That means I should provide my own template for doing that?

Isn't it a valid use case for a centralized managed user base to provide an option to remove the login fields?

**Comment by guillep2k** [comment]
> Isn't it a valid use case for a centralized managed user base to provide an option to remove the login fields?

@weeman1337 yes, it is, The template edit is a suggestion in case you need a workaround.

Maybe you can send a PR for this functionality?  😁
