### ISSUE TITLE
Hitting a 401 error shows basic authentication window

### ISSUE THREAD

**Issue by xPaw** [go-gitea/gitea#108]
Try visiting `user/repo/wtf`, it will render "401 Unauthorized: no basic auth and digit auth" page, and display auth dialog.

**Comment by tboerger** [comment]
If the server sends a 401 response this is the default behavior of browsers.

**Comment by xPaw** [comment]
That's simply not true, gitea is also sending `www-authenticate:Basic realm="."` header.

**Comment by tboerger** [comment]
In general it doesn't render a nice error page.
