### ISSUE TITLE
Gitea Chocolatey package on "Installation from package" page

### ISSUE THREAD

**Issue by doggy8088** [go-gitea/gitea#10800]
- Gitea version (or commit ref):
- Git version: `git version 2.25.1.windows.1`
- Operating system: `Microsoft Windows [Version 10.0.18363.720]`
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist: `N/A`

## Description

I made a [Gitea](https://chocolatey.org/packages/gitea) package ([Chocolatey](https://chocolatey.org/)) for Windows a while ago. I also configured CI/CD that will pull latest version from Gitea website and publish to [Chocolatey](https://chocolatey.org/) automatically. The pipeline is very stable running since last year. So I'd like to ask list my package to the [Installation from package](https://docs.gitea.io/en-us/install-from-package/) page.

## Screenshots

![image](https://user-images.githubusercontent.com/88981/77291369-190b4380-6d19-11ea-9da7-ad1e02194639.png)

**Comment by appleboy** [comment]
LGTM 👍 I think this package should be listed in https://gitea.com/lunny/awesome-gitea and documentation.

**Comment by zeripath** [comment]
Hi @doggy8088 ! Why do you pop over to  https://gitea.com/lunny/awesome-gitea and create a PR there?

**Comment by jolheiser** [comment]
Please note the linked repos are forks. :wink: 

The main repo is in the Gitea org.  
https://gitea.com/gitea/awesome-gitea

**Comment by lunny** [comment]
@appleboy That's my fork! :)

@doggy8088 Thank you for your work! Could you send two PRs, one is to https://gitea.com/gitea/awesome-gitea to add your package information there. Another is to gitea installation page document to add a link to packages part on https://gitea.com/gitea/awesome-gitea.

**Comment by lunny** [comment]
And I just found NOT ALL package methods on https://docs.gitea.io/en-us/install-from-package/ are official (i.e. FreeBSD and Cloudron are also mantained by third-party). So we may also move all of them to awesome-gitea and only keep official packages.

**Comment by lunny** [comment]
In fact, we have mentioned the Chocolatey package but not link to the right place.
```
There are no published packages for Windows. This page will change when packages are published, in the form of MSI installers or via Chocolatey. In the meantime the deployment from binary guide.
```

**Comment by appleboy** [comment]
@lunny Yes, maybe we should link (gitea.com/gitea/awesome-gitea) in [install-from-package](https://docs.gitea.io/en-us/install-from-package/) page?

**Comment by doggy8088** [comment]
@zeripath @lunny [My package link](https://gitea.com/gitea/awesome-gitea/src/branch/master/README.md#user-content-packages) was already there 1 month ago.

**Comment by 6543** [comment]
@doggy8088 can you send a pull to add it to  Installation from package page ?
