### ISSUE TITLE
upgrade from 1.11 to master breaks my git-lfs authentication

### ISSUE THREAD

**Issue by sanderboer** [go-gitea/gitea#10809]
- Gitea version (or commit ref): 1.11.3+5-g602fe4593 upgrade to 1.12.0+dev-33-gc61b90253
- Git version: 2.24 (server) 2.25 (client)
- Operating system: ubuntu 18.04 (server) void (client)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ x ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ x ] Not relevant
- Log gist:
 batch response: Authentication required: Authorization error: https://server/org/repo.git/info/lfs/objects/batch
Check that you have proper access to the repository

## Description 
When upgrading to 1.12 from 1.11 git-lfs fails to pull or clone, citing authorization errors.
I do get a  legit looking json response when issuing:
 ssh  gitea@server git-lfs-authenticate org/repo download

,the response looks comparable to the response I get when I issue the same command when 1.11 is running.

**Comment by lunny** [comment]
Any logs from gitea?
