### ISSUE TITLE
try.gitea.io has some issue (just for for me?)

### ISSUE THREAD

**Issue by alexanderadam** [go-gitea/gitea#10801]
- Gitea version (or commit ref): `1.12.0+dev-30-g2fa107891`

## Description

This happens at least since last week. Everytime I try to sign in I'm getting an error.
It's reproducible when I clear my cookies and sign in again.
Seems to be browser independent (tested Firefox and Chrome).

## Screenshots

![try gitea](https://user-images.githubusercontent.com/372620/77293925-987e2000-6ce3-11ea-8d98-6927f6b14147.gif)

**Comment by techknowlogick** [comment]
Thanks for report :)

Seems people are "testing" how many times they can mirror multi-gb repos. Time for me to go clean things up.

**Comment by techknowlogick** [comment]
Closing as logins now work again.
