### ISSUE TITLE
lost users

### ISSUE THREAD

**Issue by VantaxDev** [go-gitea/gitea#10805]
- Gitea version Gitea version 1.8.3 and 1.11.3 built with GNU Make 4.1, go1.13.8 : bindata, sqlite, sqlite_unlock_notify

- Git version:2.17.1
- Operating system: Ubuntu 18.04.4 LTS 
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X ] No
  - [ ] Not relevant

## Description
I'm using gitea as personal and private self-hosted repository from 1.3 release... ( 2 years more or less )
today my user is not anymore allowed to login.

gitea admin change-password -u myuser -p whateveryouprefer

returns:

```
2020/03/23 15:35:15 main.go:111:main() [F] Failed to run app with [gitea admin change-password -u myuser -p whateveryouprefer]: user does not exist [uid: 0, name: nextgit, keyid: 0]

```

I have backup from 5 march (I'm sure that everything worked fine ) and from 22 march.

following https://docs.gitea.io/en-us/backup-and-restore/

I moved everything from gitea-dump on a fresh new ubuntu machine and still get

"Username or password is incorrect."

```bash

# GITEA_WORK_DIR=/var/lib/gitea/ /usr/local/bin/gitea web
2020/03/23 16:06:15 cmd/web.go:107:runWeb() [I] Starting Gitea on PID: 27785
2020/03/23 16:06:15 ...dules/setting/git.go:91:newGit() [I] Git Version: 2.17.1
2020/03/23 16:06:15 routers/init.go:87:GlobalInit() [T] AppPath: /usr/local/bin/gitea
2020/03/23 16:06:15 routers/init.go:88:GlobalInit() [T] AppWorkPath: /var/lib/gitea/
2020/03/23 16:06:15 routers/init.go:89:GlobalInit() [T] Custom path: /var/lib/gitea/custom
2020/03/23 16:06:15 routers/init.go:90:GlobalInit() [T] Log path: /usr/local/bin/log
[Macaron] 2020-03-23 16:06:31: Started GET / for x.x.x.x
[Macaron] 2020-03-23 16:06:31: Completed GET / 200 OK in 3.151668ms
[Macaron] 2020-03-23 16:06:33: Started GET /user/login?redirect_to= for x.x.x.x

```

I've also tried to restore with

sqlite3 gitearebuilddd.db < gitea-db.sql

and  app.ini is

```
[security]
INTERNAL_TOKEN = sssssssssssssssssssssssssssss
INSTALL_LOCK   = true
SECRET_KEY     = xxxxxxxxxxxxxxxxxx

[database]
DB_TYPE  = sqlite3
HOST     = 127.0.0.1:3306
NAME     = gitea
USER     = gitea
PASSWD   = 
SSL_MODE = disable
PATH     = /var/lib/gitea/data/gitearebuildd.db

[repository]
ROOT = /var/lib/gitea/gitea-repositories


```

any idea about what to check ?

**Comment by lunny** [comment]
You could try with `-c myconfigfile`.
```
gitea -c myconfigfile admin change-password -u myuser -p whateveryouprefer
```

**Comment by VantaxDev** [comment]
Hi Lunny,
I found 6 app.ini on my old ubuntu server. is a mess but...

so i tried all of those 6 and i always got the same result

```
[F] Failed to run app with [gitea admin change-password -u myuser -p whateveryouprefer]: user does not exist [uid: 0, name: nextgit, keyid: 0]

```


So let's discard everything.

I have a backup from day 5 of march.

I moved everything on a another server following https://docs.gitea.io/en-us/backup-and-restore/ but I'm not able to login and/or to change my password.

## Question 1

my data are in gitea.db or in gitea-db.sql ??

I'm using sqlite as db so.. why there is a gitea-db.sql ?


and if gitea-db.sql is a backup

why doing:

```
root:/var/lib/gitea# sqlite3 data/gitea.rebuilded.db < gitea-db.sql
Error: near line 10: no such column: false
Error: near line 11: no such column: false
Error: near line 12: no such column: false
Error: near line 13: no such column: false
Error: near line 37: no such column: true
Error: near line 38: no such column: true
Error: near line 39: no such column: true
....
Error: near line 1201: no such column: true
Error: near line 1202: no such column: false
Error: near line 1203: no such column: true
Error: near line 1204: no such column: false
Error: near line 1205: no such column: true


```

i got so many errors ?




## Question 2

why executing this:

```
# gitea -c /var/lib/gitea/custom/conf/app.ini web

```

i read different path ?

```
2020/03/24 11:04:36 cmd/web.go:107:runWeb() [I] Starting Gitea on PID: 21918
2020/03/24 11:04:36 ...dules/setting/git.go:91:newGit() [I] Git Version: 2.17.1
2020/03/24 11:04:36 routers/init.go:87:GlobalInit() [T] AppPath: /usr/local/bin/gitea
2020/03/24 11:04:36 routers/init.go:88:GlobalInit() [T] AppWorkPath: /usr/local/bin
2020/03/24 11:04:36 routers/init.go:89:GlobalInit() [T] Custom path: /usr/local/bin/custom
2020/03/24 11:04:36 routers/init.go:90:GlobalInit() [T] Log path: /usr/local/bin/log
2020/03/24 11:04:36 ...dules/setting/log.go:233:newLogService() [I] Gitea v1.11.3 built with GNU Make 4.1, go1.13.8 : bindata, sqlite, sqlite_unlock_notify


```



my app.ini is


```
[database]
DB_TYPE  = sqlite3
HOST     = 127.0.0.1:3306
NAME     = gitea
USER     = gitea
PASSWD   = 
SSL_MODE = disable
PATH     = /var/lib/gitea/data/gitea.rebuild.db

[repository]
ROOT = /var/lib/gitea/gitea-repositories

```

so che custom path is not the same of the gitea web command


I'm now trying to move any files according to default path

**Comment by VantaxDev** [comment]
not yet solved.

which is the simplest way to migrate all repositories to a fresh new user on a clean install ?

swapping folder in gitea-repositories/oldbackuppeduser -> gitea-repositories/newuserclea does not solved.

thanks in advance

**Comment by VantaxDev** [comment]
SOLVED.

gitea.db ( sqlite3 was **corrupted** )

gitea-db.sql is the backup but is **wrong**... you have to open it and change (almost) any 

false
with
'false'

and any
true
with 'true'


so you can reimport in a new sqlite3 database

```
# sqlite3 newgitea.db

SQLite version 3.22.0 2018-01-22 18:45:57
Enter ".help" for usage hints.
sqlite> .read gitea-db-fixed-slashes.sql
sqlite> .exit

```
so you can tell in app.ini to use the newgitea.db



this sqlite3 corruption is quite scary...

by the way migrating this sqlite into a .sql fails while importing in mysql... ( UUID is not a column type allowed into mysql )
