### ISSUE TITLE
time-to-read display shows different times for the same text

### ISSUE THREAD

**Issue by hhirtz** [go-gitea/gitea#10817]
- Gitea version (or commit ref): `1.12.0+dev-33-gc61b90253`
- Git version: N/A: web UI issue
- Operating system: N/A: web UI issue
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
  - [x] N/A: web UI issue
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No: try.gitea.io doesn't provide time-to-read display
  - [ ] Not relevant
- Log gist: N/A: web UI issue

## Description

Gitea show how long reading a comment/issue takes.  But the value that is shown changes inconsistently, and the same text can take two different times to read.

Reproduce with:

```
eeeeeeeeeeeeeeeee

e

eeeeeeeeeeeee
```

- enter the text above in a text field for an issue, or a comment on an issue.  Time is `4:13`.
- remove the `e` in the middle.  Time is `2:0` (should be shown as `02:00`, though it's not the point of this issue)
- write back the `e` at the same place.  Time is `2:1`, different from `4:13`.

## Screenshots

The three steps respectively:

![image](https://user-images.githubusercontent.com/51088794/77531568-0d3f8e80-6e8b-11ea-9665-1c090fbcda23.png)
![image](https://user-images.githubusercontent.com/51088794/77531616-1df00480-6e8b-11ea-9c28-86fff512aced.png)
![image](https://user-images.githubusercontent.com/51088794/77531655-2f391100-6e8b-11ea-89e3-9767997e9d12.png)

**Comment by jolheiser** [comment]
That isn't time to read. That's a `line:column` indicator.

Unfortunately it does seem to have some odd behavior, especially on mobile, but that would be an upstream issue.  

Hopefully we come up with a good solution in #10729
