### ISSUE TITLE
Please remove password requirements

### ISSUE THREAD

**Issue by kstenerud** [go-gitea/gitea#10810]
All modern security experts, and also NIST, agree that password requirements are an antipattern and should be avoided. Specifically: https://pages.nist.gov/800-63-3/sp800-63b.html

"Verifiers SHOULD NOT impose other composition rules (e.g., requiring mixtures of different character types or prohibiting consecutively repeated characters) for memorized secrets."

#### Gitea registration page:

![Screenshot at 2020-03-24 14-59-24](https://user-images.githubusercontent.com/245857/77433777-1f182780-6de0-11ea-9817-e8eaa7177e02.png)

**Comment by lunny** [comment]
You could config that on your gitea instance.
