### ISSUE TITLE
Unattended installation

### ISSUE THREAD

**Issue by gioppoluca** [go-gitea/gitea#10811]
- Gitea version (or commit ref): 1.11.3
- Git version:
- Operating system: Docker
- Database (use `[x]`):
  - [x ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x ] Not relevant
- Log gist:

## Description
is it possible to make an unattended installation just setting environment variables in docker?
I need to be able to fire up a gitea server configuring it in an unattended way.
Is no problem to have to set a high amount of environment variables.
Thanks

**Comment by jolheiser** [comment]
I believe the [environment-to-ini](https://github.com/go-gitea/gitea/tree/master/contrib/environment-to-ini) script should do this for you.

**Comment by gioppoluca** [comment]
Thanks,
is that tool already built in the docker image that you ship in dockerhub or we need to add it and build our own image?

**Comment by zeripath** [comment]
The decision was to leave it out of the docker by default, so unfortunately you'd have to add it and build your own image.

See #9515 and #7287.
