### ISSUE TITLE
Call to /api/v1/repos/{:user}/{:repo}/branches/{:branch} fails unexpectedly

### ISSUE THREAD

**Issue by CirnoT** [go-gitea/gitea#10823]
- Gitea version (or commit ref): 1.12.0+dev-33-gc61b90253 running from Docker
- Operating system: `Linux gitea 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11) x86_64 GNU/Linux`
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:
```
2020/03/25 05:01:05 ...ules/context/repo.go:789:func1() [E] GetCommitsCount: Unsupported cached value type: <nil>
```

## Description

The call to `/api/v1/repos/{:user}/{:repo}/branches/{:branch}` seems to fail unexpectedly and seemingly randomly, possibly due to high I/O load on machine.

It breaks havoc with [Renovate Bot](https://github.com/renovatebot/renovate) making it mark PRs for which request failed as edited.

**Comment by 6543** [comment]
do this still happen @CirnoT ?

**Comment by CirnoT** [comment]
I was unable to reproduce it ever since I've switched to memcached as cache storage and configured higher cache timeouts.
