### ISSUE TITLE
Unknown col is_active seq 0, in index is_active of table user

### ISSUE THREAD

**Issue by binfalse** [go-gitea/gitea#10820]
- Gitea version (or commit ref): gitea/gitea:latest (https://hub.docker.com/r/gitea/gitea)
- Git version: packaged in Docker image
- Operating system: Debian
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist: https://gist.github.com/binfalse/d83d5853c2a9dc2513e6140241bee524

## Description
I have a dockerized `gitea/gitea:latest` with `postgres:9.6` as database backend running for quite some time already. However, since the last update of `gitea/gitea:latest` the gitea service doesn't start properly anymore.

In the log file `/data/gitea/log` (the log is inside the container -> would be cool if the service would log to the docker daemon..) it looks like a DB upgrade is missing or failed...? It complains about

    Error: sync database struct error: Unknown col is_active seq 0, in index is_active of table user, columns []

See gist: https://gist.github.com/binfalse/d83d5853c2a9dc2513e6140241bee524

"Downgrading" to `gitea/gitea:1.11.3` solved it for the moment, but would be nice to get that fixed :)

## Screenshots
Imagine an nginx `502 Bad Gateway` error page :)

**Comment by techknowlogick** [comment]
Closed with #10819
