### ISSUE TITLE
Source compilation by gitea, web side CSS style is invalid

### ISSUE THREAD

**Issue by skye95git** [go-gitea/gitea#10827]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
Windows source compilation gitea, web side CSS style failure, how should I solve?
...

## Screenshots
![Uploading image.png…]()

**Comment by lunny** [comment]
Please give more details.

**Comment by skye95git** [comment]
> Please give more details.

![QQ20200326101545](https://user-images.githubusercontent.com/41561936/77603354-d5981b80-6f4a-11ea-96d4-167fa9fc2edb.png)
As shown, the page works fine, but there is no style effect

**Comment by lunny** [comment]
How did you compile gitea?

**Comment by skye95git** [comment]
> How did you compile gitea?

I downloaded the source code from the master branch and ran "go build" from the console, then ran "./gitea web".

**Comment by jolheiser** [comment]
`go build` by itself will definitely not be enough. :sweat_smile: 

Please follow the steps in [the documentation](https://docs.gitea.io/en-us/install-from-source/#build) regarding building from source. :slightly_smiling_face:

**Comment by kineck** [comment]
这是一个编译方法不对的问题，TAGS="bindata" make build，这是正确的方法

**Comment by skye95git** [comment]
> 这是一个编译方法不对的问题，TAGS="bindata" make build，这是正确的方法

Thanks,you are right.I follow the steps in the documentation to reconfigure the environment,and run TAGS="bindata sqlite sqlite_unlock_notify" make build,It turns out to be right.
