### ISSUE TITLE
LDAP User Filter

### ISSUE THREAD

**Issue by qequinet35** [go-gitea/gitea#10829]
Dear all,

I am creating this issue because I found any topic related to this kind of filter using OpenLDAP. 

In the official documentation (https://docs.gitea.io/en-us/authentication/), it is written that with "LDAP using simple auth" there are these following fields:
User DN (required)
User Search Base (optional)
User Filter (required)
Group Search Base (optional)
Group Name Filter (optional)
User Attribute in Group (optional)
Group Attribute for User (optional)

.... but I am not able to find the fields regarding the  Groups from the Gitea Web Interface.

I used the following version of gitea: gitea-1.11.3-linux-amd64

Did I installed a wrong version ? 

 Could you please help me.

Thanks by advance,
Regards,

**Comment by zeripath** [comment]
It looks we never implemented that despite it being in the docs for 2 years now... :man_facepalming:

**Comment by Elbandi** [comment]
Look like the group check is missing from SearchEntries()
