### ISSUE TITLE
OAuth2 OIDC singin issue - invalid character

### ISSUE THREAD

**Issue by bibiak1** [go-gitea/gitea#10836]
- Gitea version (or commit ref): 1.11.3 built with GNU Make 4.2.1, go1.13.8 : bindata, sqlite, sqlite_unlock_notify
- Git version: 2.24.1
- Operating system: docker image gitea/gitea:1
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description
I have an issue when using OIDC:
routers/user/auth.go:590:handleOAuth2SignIn() [E] UserSignIn: invalid character '<' looking for beginning of value

OIDC is configured with those options (do not know if it's relevant):
- Scope: openid
- Pre Authorized Scope: openid
- Response Types:
  - Code: Yes
  - ID Token: No
  - Token: Yes
  - Allow Introspect? No
  - Allow Refresh Grant? No
  - Token Endpoint Auth Method: clientSecretPost

Those value can be changed if needed

Please support
...

**Comment by lafriks** [comment]
This needs more information. To me it looks like OIDC server is returning html somewhere where it is expected to return json.

**Comment by bibiak1** [comment]
> 2020/03/26 12:50:39 Started GET /user/oauth2/xxx for 9.145.2.40
2020/03/26 12:50:39 Completed GET /user/oauth2/xxx 307 Temporary Redirect in 76.611366ms
2020/03/26 12:50:40 Started GET /user/oauth2/xxx/callback?code=06f6VcZ0UEheWD68TWPKiQ7KoRAImS&state=b96e0d29-0716-4b19-95d3-8910be47fb01 for 9.145.2.40
2020/03/26 12:50:41 Started GET /serviceworker.js for 9.145.2.40
2020/03/26 12:50:41 Completed GET /serviceworker.js 200 OK in 1.037095ms
2020/03/26 12:50:41 Completed GET /user/oauth2/xxx/callback?code=06f6VcZ0UEheWD68TWPKiQ7KoRAImS&state=b96e0d29-0716-4b19-95d3-8910be47fb01 500 Internal Server Error in 1.047477358s

**Comment by bibiak1** [comment]
I can provide more logs - just let me know what I need to do to get it as you want

**Comment by bibiak1** [comment]
Maybe it's a matter of application type - I have choose OTHER

![image](https://user-images.githubusercontent.com/24386585/77646911-bfe41f80-6f65-11ea-87bf-052a3a7c49d3.png)

**Comment by bibiak1** [comment]
Looks like my oauth2 service requires JWT Certificate to be present in query
