### ISSUE TITLE
Modify the login and registration page style and realize sending requests to the background

### ISSUE THREAD

**Issue by skye95git** [go-gitea/gitea#10837]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
1.I want to modify the login and registration page, but I see gitea pages implemented as templates，where should I modify the code?
2.I want to implement the login registration to send ajax requests to the background, which folder should I add the code in？
3.I read the official document "Customizing Gitea pages and resources", "Getting pages", "Customizing startpage/homepage" all mention "custom/templates", but I did not see the templates folder under the custom directory. Which folder is this folder?Do you need to create your own?
...

## Screenshots
![1](https://user-images.githubusercontent.com/41561936/77646384-6698e200-6f9f-11ea-837e-bea642f34e98.png)
![2](https://user-images.githubusercontent.com/41561936/77646387-67ca0f00-6f9f-11ea-9986-66dcb33aed88.png)

**Comment by jolheiser** [comment]
You will need to create any intermediate folders if they do not exist, yes.

**Comment by guillep2k** [comment]
Make sure to use the template from the same version of Gitea you are using. For example, this links points to `1.11.3`'s:

https://github.com/go-gitea/gitea/blob/v1.11.3/templates/user/auth/signup_inner.tmpl
