### ISSUE TITLE
API - Pull Request - Help

### ISSUE THREAD

**Issue by Madmorgan007** [go-gitea/gitea#10832]
- Gitea version (or commit ref):1.9.6
- Git version:
- Operating system: Windows
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

Hi using the Gitea API to read and update information on a repo that I have I'm stuck when trying to create a pull request. I am using the try me on the swagger UI and the information here https://docs.gitea.io/en-us/pull-request/ is not helping me.

I'm not sure what values i should be giving to the model.

{
  "assignee": "string",
  "assignees": [
    "string"
  ],
  "base": "string", --> whats this mean
  "body": "string", --> whats this mean 
  "due_date": "2020-03-26T10:31:37.711Z",
  "head": "string",  --> whats this mean
  "labels": [
    0
  ],
  "milestone": 0,
  "title": "string"
}

Thanks

**Comment by cipherboy** [comment]
Hi @Madmorgan007! I think the [GitHub docs](https://developer.github.com/v3/pulls/#create-a-pull-request) explain it very nicely:

> Name | Type | Description
> -- | -- | --
> head | string | Required. The name of the branch where your changes are implemented. For cross-repository pull requests in the same network, namespace head with a user like this: username:branch.
> base | string | Required. The name of the branch you want the changes  pulled into. This should be an existing branch on the current  repository. You cannot submit a pull request to one repository that  requests a merge to a base of another repository.
> body | string | The contents of the pull request.

So `head` is the username and branch name to pull _from_, `base` is where these changes will _go_ when merged, and `body` is just whatever content you'd put in the long text description field about the pull request ("Hi my name is .... and this pull request implements ...").

If you have suggestions of how to improve the gitea docs, feel free to open a pull request updating them :-) Sometimes the GitHub docs are a helpful comparison when they apply to Gitea.

**Comment by Madmorgan007** [comment]
thanks @cipherboy for the replay. with this detail I have got my code working now. from reading the https://docs.gitea.io/en-us/pull-request/ it was unclear how or where you are referencing this information. it might be good to put the link to the Github page on there or that table.

Thanks
if you want you can close this now

**Comment by 6543** [comment]
@Madmorgan007 https://docs.gitea.io/en-us/pull-request/ was not ment for API documnetation since we use swagger to generate it: https://try.gitea.io/api/swagger
