### ISSUE TITLE
can not git clone

### ISSUE THREAD

**Issue by LanceAdd** [go-gitea/gitea#10839]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
![image](https://user-images.githubusercontent.com/22969676/77662110-6a842e80-6fb6-11ea-8b5f-654f8b97d1ea.png)

...

**Comment by jolheiser** [comment]
What version of Gitea is this? Can you send us some logs?

**Comment by LanceAdd** [comment]
version:gitea-1.11.3-linux-amd64
sorry,the logs have been delete,but the new problems come,
I have add the ssh keys to the gitea,but i can't git git clone my repository by ssh。https is ok.
if i delete the ssh keys then git clone the public repository, then the same problem come.
you can try my public repository
```
git clone root@182.92.200.229:lanceadd/webpro.git
```
![image](https://user-images.githubusercontent.com/22969676/77842297-3df13200-71c3-11ea-9265-724d03ce6278.png)

![image](https://user-images.githubusercontent.com/22969676/77842220-4eed7380-71c2-11ea-8425-427818ff8484.png)
![image](https://user-images.githubusercontent.com/22969676/77842237-7e9c7b80-71c2-11ea-873d-a6920c6f4af3.png)

**Comment by zeripath** [comment]
What happens when you `ssh root@182.92.200.229`? If you get a shell then you have a duplicate key in your authorized_keys. (I don't think that this is the case here but it may also provide further information.)

The `invalid character '<' looking for beginning of value` suggests to me that when `gitea serv` tries to connect to your running Gitea server it cannot. Do you have the correct `LOCAL_ROOT_URL`?

**Comment by LanceAdd** [comment]
@zeripath 
The default configuration is this
```
 LOCAL_ROOT_URL   = http://localhost:80/
```
if i change it
```
LOCAL_ROOT_URL   = http://localhost:3000/
```
then
![image](https://user-images.githubusercontent.com/22969676/77850010-487eec00-7202-11ea-9c38-8cb77ed171f3.png)

**Comment by LanceAdd** [comment]
@jolheiser @zeripath 
i know what happened.
The font I use makes ":" look the same in Chinese and English, but in fact, the ":" of Chinese input method is different from that of English input method. I'm sorry that I did something stupid. Thank you for your help.
You're really great
