### ISSUE TITLE
where are issues stored?

### ISSUE THREAD

**Issue by VantaxDev** [go-gitea/gitea#10830]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

After a sqlite corruption and an hand-made translation to .sql and back to .db I lost issues history

Where are my issues stored ? which tables ?

Which is the best way to manipulate the .sqlite file ?

## Screenshots

![Screenshot from 2020-03-26 10-24-57](https://user-images.githubusercontent.com/25178906/77631105-6c190c80-6f4c-11ea-8ff5-0a69e15f00c2.png)

thanks in advance

**Comment by lafriks** [comment]
you can use `sqlite` cli tool. issues are stored in table `issues`

**Comment by lafriks** [comment]
Please use our discourse forum for such questions
