### ISSUE TITLE
 Haven't considered adding webhook for corporate WeChat？

### ISSUE THREAD

**Issue by lengyuqu** [go-gitea/gitea#10847]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

...

**Comment by alexanderadam** [comment]
People were doing this in #5252 and #9746.
But IMHO a more generic solution like [**@bkcsoft's** proposal of Webhook Templates](https://github.com/go-gitea/gitea/issues/1089) would be better and more flexible.

**Comment by delvh** [comment]
Isn't this closed by #15910?
