### ISSUE TITLE
Heatmap is gone

### ISSUE THREAD

**Issue by hasufell** [go-gitea/gitea#10846]
- Gitea version (or commit ref): cf4f2cfa3ee0e71632df971e154c7b926c39ba80
- Git version: 2.24.1
- Operating system: Alpine
- Database:
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X] No
  - [ ] Not relevant
- Log gist:

## Description

Heatmap is gone from the dashboard after upgrade. GET request succeeds and has proper payload.

Console only shows this error:

```
Failed to load ‘https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic&subset=latin&display=swap’. A ServiceWorker passed a promise to FetchEvent.respondWith() that rejected with ‘TypeError: NetworkError when attempting to fetch resource.’.
```

**Comment by silverwind** [comment]
Error should be unrelated and will be fixed with the next Fomantic-UI release.

Does clearing browser cache help?

**Comment by hasufell** [comment]
> Does clearing browser cache help?

No, but the heatmap works in chrome.

**Comment by CirnoT** [comment]
I believe this can be fixed by using `Forget about this site` in Firefox, although it does seem to show itself back again from time to time.

Try refreshing the page with developer tools opened, it should also show heatmap back again, but only for the duration of developer tools being open.

**Comment by hasufell** [comment]
> I've previously solved this by using Forget about this site in Firefox

I don't know what that is

> Try refreshing the page with developer tools opened, it should also show heatmap back again, but only for the duration of developer tools being open.

That doesn't work.

**Comment by silverwind** [comment]
What does "Heatmap is gone" mean? Does it get stuck with a loading spinner (https://github.com/go-gitea/gitea/issues/10736) or not load at all (this is normal on small screen sizes where it would not fit, btw).

**Comment by hasufell** [comment]
It's gone completely. The screen size is normal desktop screen size.

**Comment by silverwind** [comment]
What's your width exactly? It will hide below 1200px.

<img width="404" alt="image" src="https://user-images.githubusercontent.com/115237/77859024-466b5c00-7207-11ea-88ea-b8a2a90f0533.png">

**Comment by hasufell** [comment]
> What's your width exactly? It will hide below 1200px.

It seems I zoomed in too far and it got hidden :)
