### ISSUE TITLE
Commit search shows a 500er error

### ISSUE THREAD

**Issue by Bodenhaltung** [go-gitea/gitea#10840]
- Gitea version (or commit ref): Gitea version 1.11.1 built with GNU Make 4.3, go1.13.8 : bindata, sqlite, pam
- Git version: 2.26.0
- Operating system: ArchLinux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist: https://gist.github.com/Bodenhaltung/4c2fae24a5879894f8cdba3cc48c3936

## Description
The commit search shows a 500er error consistently on any searchterm

**Comment by lafriks** [comment]
What Gitea version are you using?

**Comment by Bodenhaltung** [comment]
> What Gitea version are you using?

Sorry, stupid me, fixed in issue post: `Gitea version 1.11.1 built with GNU Make 4.3, go1.13.8 : bindata, sqlite, pam`

**Comment by guillep2k** [comment]
Then closing. 😉

**Comment by guillep2k** [comment]
Sorry, I misread your comment! I thought you've fixed the issue. Reopening. :flushed:

**Comment by guillep2k** [comment]
I'd suggest you first upgrade to `1.11.3`, since `1.11.1` has some interesting issues that will affect you sooner or later.

As for your problem, I think it's worth attempting to rebuild the code indexes. Those are usually in the data folder (e.g. `/var/lib/gitea/indexers`, depending on your system configuration). You can delete the `repos.bleve` directory and Gitea will rebuild it for you. You must shutdown the instance before deleting the directory.

**Comment by lunny** [comment]
@guillep2k commits search is not code search. Commits search will search commit via git command but not indexes.

**Comment by mrsdizzie** [comment]
This is probably related to:

 https://public-inbox.org/git/87zhtbn5xb.fsf@evledraar.gmail.com/T/
 https://bugs.exim.org/show_bug.cgi?id=1749

I'm not familiar with arch linux or anything but this change might be related to fixing it:

 https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/pcre2&id=920838a6a4ca3ff466b8751d8dc4c24c5383767f

Do you have that version? Or can try updating (I don't know if git needs to then be rebuild or however arch linux works).

**Comment by Bodenhaltung** [comment]
Thanks for your help, i have `core/pcre2 10.34-3` and now also: `Gitea version 1.11.3 built with GNU Make 4.3, go1.14.1 : sqlite, pam`

But still the same error.

I understand that the problem is not gitea related more arch vs. pcre2 vs. git.
