### ISSUE TITLE
Gitea template customization does not work

### ISSUE THREAD

**Issue by tamalsaha** [go-gitea/gitea#10859]
- Gitea version (or commit ref): master
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
https://docs.gitea.io/en-us/customizing-gitea/ says that 

`Every single page of Gitea can be changed. Dynamic content is generated using go templates, which can be modified by placing replacements below the custom/templates directory.`

But reading the code and trying it, this does not work for static build. As you can see here: https://github.com/go-gitea/gitea/blob/7cd47046ea6e1fde2c88290a42f345795aee0ea4/modules/templates/static.go#L39-L115

The custom templates are appended after the built-in templates in the `NewTemplateFileSystem()`. In the `func (templates templateFileSystem) Get(name string)` method, it always searches from the index 0. So, it returns the built-in template.

...

## Proposed Solution:
`func (templates templateFileSystem) Get(name string)` should search from the end of the `files` array to return the custom template in case it exists.

**Comment by guillep2k** [comment]
But it does work and it's being used by lots of users. Check the location of your `custom` directory in your `/admin/config` page:

![image](https://user-images.githubusercontent.com/18600385/77826611-3c563a00-70ef-11ea-8ef7-59f6315e44ca.png)

You can for example create a file:

```
/var/lib/gitea/custom/templates/user/profile.tmpl
```

And modify your user profile page. This, however, perhaps requires you to restart Gitea, as the external templates I believe are read form the file-system at system startup.

When changing a template, make sure to use as a base the template from the version you're using. For example, this template is from `1.11.3`:

https://github.com/go-gitea/gitea/blob/v1.11.3/templates/user/profile.tmpl

**Comment by guillep2k** [comment]
Also, please notice that the docs are not specific to a particular version, and some instructions might be a little outdated or refer to features that were not still released (this is not the case, though).
