### ISSUE TITLE
500 Internal Server Error when accessing nonexistent commit

### ISSUE THREAD

**Issue by tobiaswiese** [go-gitea/gitea#10852]
- Gitea version (or commit ref): 1.11.3
- Git version: 2.20.1
- Operating system: Debian Buster
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes: https://try.gitea.io/go-gitea/blog/commit/aa64449a8c91c7057c89322881794caf15590eb3
  - [ ] No
  - [ ] Not relevant
- Log gist: Not relevant

## Description

When accessing a commit that doesn't exist (either by typing nonsense into the url bar, or because it was later cleaned up by the garbage collector), the server fails with a 500 error, insead of a 404.

## Screenshots

https://try.gitea.io/img/500.png

**Comment by lunny** [comment]
This may has been fixed by @zeripath .

**Comment by zeripath** [comment]
Nope I hadn't fixed this one - but it needs a similar fix to the other places.
