### ISSUE TITLE
404 Not found error on blob_excerpt expansion

### ISSUE THREAD

**Issue by sosak009** [go-gitea/gitea#10851]
- Gitea version (or commit ref): 1.11.1
- Git version:
- Operating system: Linux
- Database (use `[x]`):
  - [x] PostgreSQL
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes https://try.gitea.io/testinguserXY/my_bugtest/pulls/3#code-preview-26577
- Log gist:

## Description
Hi, gitea returns HTTP/404 not found on a blob_excerpt request while trying to expand the code in pull_request/review conversation (as seen on screenshot). This bug is also reproducable in testing gitea environment. 

Request URL example:
`Request URL: https://try.gitea.io/testinguserXY/my_bugtest/blob_excerpt/?last_left=0&last_right=0&left=35&right=35&left_hunk_size=6&right_hunk_size=7&path=testfile&style=unified&direction=up&anchor=diff-e05fcb614ab36fdee72ee1f2754ed85e2bd0e8d0K35`

Thanks in advance

## Screenshots
![blob_excerpt](https://user-images.githubusercontent.com/61889557/77759262-bbd30300-7034-11ea-8867-eb80b800c9da.png)
![image](https://user-images.githubusercontent.com/61889557/77759528-22f0b780-7035-11ea-9c0e-893f9a20c516.png)

**Comment by a1012112796** [comment]
Sadly, It still exists :(  

![image](https://user-images.githubusercontent.com/25342410/83322245-9fe41b80-a288-11ea-88b7-dcade120df73.png)

**Comment by sosak009** [comment]
Issue still present

**Comment by zeripath** [comment]
I just tried the provided url: https://try.gitea.io/testinguserXY/my_bugtest/pulls/3 and couldn't reproduce.

**Comment by zeripath** [comment]
@sosak009 what version of Gitea is this present in?

**Comment by sosak009** [comment]
> @sosak009 what version of Gitea is this present in?

I just reproduced it on the try.gitea.io ...
```
Request URL: https://try.gitea.io/testinguserXY/my_bugtest/blob_excerpt/?last_left=0&last_right=0&left=35&right=35&left_hunk_size=6&right_hunk_size=7&path=testfile&style=unified&direction=up&anchor=diff-e05fcb614ab36fdee72ee1f2754ed85e2bd0e8d0K35
Request Method: GET
Status Code: 404 
```

**Comment by lunny** [comment]
@sosak009 Cannot reproduce it on macOS & firefox

**Comment by zeripath** [comment]
Ah you mean the up arrow on https://try.gitea.io/testinguserXY/my_bugtest/pulls/3#code-preview-26577

**Comment by zeripath** [comment]
Now the question is what should that arrow do? Should it just redirect to the files page? Should it even exist?

**Comment by lunny** [comment]
Just remove that up arrow.
