### ISSUE TITLE
"$ gitea change-password" cli command not properly escaping '&'

### ISSUE THREAD

**Issue by nmartin867** [go-gitea/gitea#10857]
- Gitea version (or commit ref): Gitea version 1.10.6 built with GNU Make 4.1, go1.13.8 : bindata, sqlite, sqlite_unlock_notify
- Git version: 2.17.1
- Operating system: Ubuntu 18.04.3 (LTS) x64
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant

## Description

I noticed after completing initial configuration of Gitea my admin credentials were not accepted. In a attempt to resolve this I ran the following command at my server:

`./gitea admin change-password --config /etc/gitea/app.ini --username nmartin --password 0PSJ668FqB2*oXc&4ADi0Dqe4597W[h_[M`

Note the char '**&**' in the password.

The following success message was output to stdout:

`[1] 1064
2020/03/28 04:20:05 ...dules/setting/git.go:87:newGit() [I] Git Version: 2.17.1
2020/03/28 04:20:05 .../xorm/session_raw.go:76:queryRows() [I] [SQL] SELECT `id`, `lower_name`, 
... sql.. blah.. blah blah.. sql..
nmartin's password has been successfully updated!
4ADi0Dqeb9t7W[h_[M: command not found`

The last line reads: **4ADi0Dqe4597W[h_[M: command not found**

I noticed that this was everything after the '&' in my password. It lead me to believe that the ampersand was not correctly being escaped. I was able to login using the first part of my password. 

Anyway.. hope this help.

PS.. Yes.. I've changed my creds before posting this  ;)

**Comment by zeripath** [comment]
Are you sure that this is not your shell picking up the & ? Stick the password in quotes and try again?

**Comment by guillep2k** [comment]
As @zeripath said, you're typing that command in a shell (bash probably?). Shells process parameters before invoking the commands, and `&` is a special character in most *nix shells. You need to use single quotes to enclose strings with special characters. `&` means "execute the previous command in background and keep looking for commands in the rest of the line. For example:

```
$ echo hello1 & sleep 1 & echo hello2 & sleep 1 ; echo hello3
[1] 884                                                 <--- process ID for "echo hello1"
hello1                                                  <--- output of "hello1"
[2] 885                                                 <--- process ID for "sleep 1"
[3] 886                                                 <--- process ID for "echo hello2"
hello2                                                  <--- output of "hello2"
[1]   Done                    echo hello1               <--- message from bash saying that [1] finished
[2]-  Done                    sleep 1                   <--- message from bash saying that [2] finished
[3]+  Done                    echo hello2               <--- message from bash saying that [3] finished
hello3                                                  <--- output of "sleep 1 ; echo hello3"
```

But the time `gitea change-password` is invoked, your shell already took the `&` character and separated the tokens so there's nothing gitea can do. Usually using the `'` character to enclose the special characters will do, unless you want a `'` inside the string as well, in which case you need to use `\'`:

```
$ echo 'hello1 & sleep 1 & echo hello2 & sleep 1' ; echo hello3
hello1 & sleep 1 & echo hello2 & sleep 1
hello3
```

Other special characters you must be aware of are `\`, `$`, `(`, `)`, `^` (in some shells) and the back tick.

**Comment by nmartin867** [comment]
Of course! Haha. Wow.. I feel dumb. My bad.
