### ISSUE TITLE
[ui] make more icon types onto the time-line like github

### ISSUE THREAD

**Issue by a1012112796** [go-gitea/gitea#10864]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

Hello! I found a problem that now on gitea's time-line , we can only make ``x``, ``eye`` ``circle-slash`` on it , but ``lock`` , ``key`` , and many other types can't on it. which is doesn't look good enough. I think It will be fun if we can make them onto the time-line.  also it will be more good if we can make them style like github , which means all icons except dot combine whith a circle. but I have no idea about how to do them , so add this issue to find help. Thanks.

## Screenshots
<img width="462" alt="jft1" src="https://user-images.githubusercontent.com/25342410/77825251-0773d280-7143-11ea-9ac6-b1e8856849bc.png">

------

<img width="587" alt="jft2" src="https://user-images.githubusercontent.com/25342410/77825256-0fcc0d80-7143-11ea-9c8b-b222e85fa687.png">

**Comment by silverwind** [comment]
Yes, they need to move to the left and have a background added in the same color as the line but so far I've been unable to figure out what is causing some of these timeline entries to offset around 20px to the right.

**Comment by Sorien** [comment]
@silverwind nothing just green dots (svg.octicon-primitive-dot) are moved 35px to left  

```css
.svg.octicon-primitive-dot {
    margin-top: -1px;
    margin-left: -35.5px;
    margin-right: -1px;
    height: 30px;
    color: #6cc644;
```

**Comment by Sorien** [comment]
adding this offset `.svg` will fix timeline
```css
.repository.view.issue .comment-list .event .svg {
    width: 30px;
    float: left;
    text-align: center;
    margin-left: -35.5px; // this line
```

**Comment by silverwind** [comment]
@Sorien ah, I totally missed that rule, thanks. Those screenshots do look great, exactly what I had in mind.

**Comment by a1012112796** [comment]
@Sorien Hello, Thanks for your work. I think it's so great although I can't fully understand because of my knowledge lack. please make a PR to change it, then we can use more type icons on it, which is a very attractive thing. Thanks for your works again.

**Comment by Sorien** [comment]
@a1012112796 pls can you look at opened PR #10890 couse i can't test it right now :/
