### ISSUE TITLE
login log and operation log

### ISSUE THREAD

**Issue by MrLin-619** [go-gitea/gitea#10860]
Hello, do you have any plans to add login log and operation log?

**Comment by Joolun** [comment]
I think too, login log is necessary

**Comment by lunny** [comment]
I think this should be saved into audit log. There is already an issue to request a feature for that.

**Comment by MrLin-619** [comment]
Save as file? Will it be saved to the database?

**Comment by lafriks** [comment]
Audit log (user authorizations/sessions) should probably be saved to database so that it could be possible for user to display it's active sessions and close them if needed

**Comment by lafriks** [comment]
Duplicate of #5312 and #8
