### ISSUE TITLE
Add API endpoint for diff between two refs like GitHub and Bitbucket

### ISSUE THREAD

**Issue by rafi** [go-gitea/gitea#10871]
GitHub allows `base...head` diff comparison in their [API action /compare](https://developer.github.com/v3/repos/commits/#compare-two-commits) and appears in their go sdk as [CompareCommits](https://pkg.go.dev/github.com/google/go-github/github?tab=doc#RepositoriesService.CompareCommits) with `base` & `head` arguments.

Bitbucket has a similar [API action /diffstat](https://developer.atlassian.com/bitbucket/api/2/reference/resource/repositories/%7Bworkspace%7D/%7Brepo_slug%7D/diffstat/%7Bspec%7D) and appears in their go sdk as [RepositoriesUsernameRepoSlugDiffstatSpecGet](https://github.com/wbrefvem/go-bitbucket/blob/master/docs/DefaultApi.md#repositoriesusernamereposlugdiffstatspecget) with a 'spec' argument for things like 3a8b42..9ff173.

It would be great if someone will able to add this feature. My current use-case is analyzing the change-sets on each commit in CI.

**Comment by Coding-Kiwi** [comment]
Yes please! Maybe also include this data in commit webhooks?
