### ISSUE TITLE
SVG Support

### ISSUE THREAD

**Issue by hughesjs** [go-gitea/gitea#10882]
- Gitea version (or commit ref):  1.12.0+dev-352-gcadec9bc2
- Operating system: Arch
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite

## Description
SVG files aren't shown as images they're shown as though they're source which leads to a ridiculously long page load time and rather useless display.

## Screenshots

![image](https://user-images.githubusercontent.com/4203766/77858175-a8bd6000-71f9-11ea-9fe3-7b88ecdff919.png)

**Comment by jamesorlakin** [comment]
[External renderers](https://docs.gitea.io/en-us/external-renderers/) may be of use as a stop-gap solution.

**Comment by lunny** [comment]
This is a duplicated issue with #1095.
