### ISSUE TITLE
gitea is a Trojan? can the author explain?

### ISSUE THREAD

**Issue by VeniVidiVici9** [go-gitea/gitea#10888]
183.192.179.16
182.254.52.17
14.18.182.223
61.241.50.63
101.89.19.140
113.96.198.54
59.36.132.240
14.215.156.146

What do these address authors do?
It's like a Trojan. My firewall keeps alarming?
It always connect these addresses silently in the background, can the author explain?

This is the latest version

**Comment by lunny** [comment]
Where did you download the gitea binary? And what's the version? Have you compared the checksum?

**Comment by VeniVidiVici9** [comment]
I downloaded the docker image, not a binary file, and downloaded it on this website: https://hub.docker.com, sha256: 306e7b99e8c6f2f49c43f7ad072904b1eb741bde8314093b7cb4ffe51be508d8
![Uploading 图片.png…]()

**Comment by VeniVidiVici9** [comment]
I downloaded a docker image, not a binary file,
Downloaded on this site: https://hub.docker.com,
sha256: 306e7b99e8c6f2f49c43f7ad072904b1eb741bde8314093b7cb4ffe51be508d8
The following is the mirror information:
maintainer maintainers@gitea.io
org.label-schema.build-date 2020-03-19T21: 49: 12Z
org.label-schema.schema-version 1.0
org.label-schema.vcs-ref 7225453d5f4694f69e1a18e42204b52ed9fffc9c
org.label-schema.vcs-url https://github.com/go-gitea/gitea.git

**Comment by VeniVidiVici9** [comment]
1、I downloaded a docker image, not a binary file,
&nbsp;&nbsp;&nbsp; Downloaded on this site: https://hub.docker.com,
2、version 1.0
3、sha256: 306e7b99e8c6f2f49c43f7ad072904b1eb741bde8314093b7cb4ffe51be508d8






The following is the mirror information:
















------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Lunny Xiao"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月30日(星期一) 下午5:33
收件人:&nbsp;"go-gitea/gitea"<gitea@noreply.github.com&gt;;
抄送:&nbsp;"104561102"<104561102@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [go-gitea/gitea] gitea is a Trojan? can the author explain? (#10888)





 
Where did you download the gitea binary? And what's the version? Have you compared the checksum?

**Comment by techknowlogick** [comment]
Do you have federated avatars enabled? Can you give more details about those connections being made (for example what port is being connected to)?

**Comment by Monter** [comment]
Do you have any migrations in the repo? I have a lot of them and freshly after starting Gitea immediately tries to refresh them all, which pisses me off and almost kills the CPU in the server.
Strange outgoing connections can come from descriptions of a given repo into which their authors throw various pictures, graphics, links, etc.

**Comment by VeniVidiVici9** [comment]
My situation is similar to yours, I also encountered a situation similar to illegal login，such as belowing:







------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Mark eM"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月30日(星期一) 晚上10:03
收件人:&nbsp;"go-gitea/gitea"<gitea@noreply.github.com&gt;;
抄送:&nbsp;"104561102"<104561102@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [go-gitea/gitea] gitea is a Trojan? can the author explain? (#10888)





 
Do you have any migrations in the repo? I have a lot of them and freshly after starting Gitea immediately tries to refresh them all, which pisses me off and almost kills the CPU in the server.
 Strange outgoing connections can come from descriptions of a given repo into which their authors throw various pictures, graphics, links, etc.

**Comment by VeniVidiVici9** [comment]
Yes, I have the federated avatars enabled, these connections communicate via http port 3000 by default.
I also encountered a situation similar to illegal login，such as belowing:







=========================================================================================================================================================



 
Do you have federated avatars enabled? Can you give more details about those connections being made (for example what port is being connected to)?

**Comment by VeniVidiVici9** [comment]
I use a container, not a binary file, and the version number is: 1.12.0 + dev-69-g972b3bf3b. 

checksum is sha256:c4a654eb05c032eac9ee57de853c725de6169f93f0a45ccd506c7bf4bed03fe5


I have compared the information in the build log. 

The checksum is the same on the Docker Hub official website server.



Checksum on Docker Hub official website server:






and the following is my build image log:










I encountered a situation similar to illegal login，such as belowing:










================================================================================================================================



 
Where did you download the gitea binary? And what's the version? Have you compared the checksum?

**Comment by Monter** [comment]
Please stop spamming and cut out unnecessary items and headers before posting.

**Comment by lunny** [comment]
As @lafriks said, Gitea will not visit other special external sites. If you care about that, you can compile the binary or docker from source.
