### ISSUE TITLE
.wrap in index.css has incorrect word-break

### ISSUE THREAD

**Issue by nergdron** [go-gitea/gitea#10887]
- Gitea version (or commit ref): docker image (f0a8199e7e95)

## Description
the `.wrap` CSS property in `index.css` (in both themes) has the styles:
```
word-wrap: break-word;
    overflow-wrap: break-word;
word-break: break-all;
```
the first two are fine, but the last causes things to break mid word, impeding readability. `word-break: break-all;` should be removed so it defaults to `normal`, which has much more reasonable behaviour.

## Screenshots
![gitea-default](https://user-images.githubusercontent.com/292681/77886128-28105b00-721d-11ea-8ae7-e32c2253db7a.png)
![gitea-green](https://user-images.githubusercontent.com/292681/77886148-2f376900-721d-11ea-928f-b4c342e1cebc.png)

**Comment by silverwind** [comment]
Yes it can be removed as `overflow-wrap: break-word;` should still suffice to break long works without whitespace in them.

**Comment by silverwind** [comment]
Correction: `overflow-wrap: break-word` is not enough to break long sequences without any whitespace, e.g. `aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa` will not be broken so `word-break: break-all` is needed to ensure all strings are broken up which is important to prevent layout issues with overflown strings. I think this issue is invalid.

**Comment by zeripath** [comment]
Would `hyphens: auto;` help?

**Comment by silverwind** [comment]
`hyphens` sucks imho, it introduces additional content and not all languages even use hyphenization.

**Comment by silverwind** [comment]
Maybe `overflow-wrap` alone is actually worth a try. I can't reproduce the scenario of a uninterrupted string not breaking with it:

https://jsfiddle.net/silverwind/tzg8a6qv/
