### ISSUE TITLE
Suggest to shorten the time of stale

### ISSUE THREAD

**Issue by a1012112796** [go-gitea/gitea#10892]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

Hello, now  the stale time is two month.  I think it would be more usefull to cut it down to one month or even twenty days. because I think the stale is a way to notify users to take care of the issue or pull request  which hase been  lost focus. but I think two moths is too long to do this thing. the reason why I think about this thing is this PR (#10492) . It haven't be reviewed from 27 Feb to four days before. The author may be have lost interest about it .  thats my thinks , thanks .

**Comment by 6543** [comment]
stale is sometime anoying but it remid you, so :+1:
