### ISSUE TITLE
Error 404 with close/reopen Milestone

### ISSUE THREAD

**Issue by mbarinc** [go-gitea/gitea#10899]
- Gitea version (or commit ref): 1.11.3
- Git version: 2.23
- Operating system: Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description
This is a new issue after updated the release from 1.11.1 to 1.11.3.

I can't close/reopen a milestone.
After click on button, Gitea open a popup (see screenshot), ask me to enter credential and it redirect me on 404 error page.

This is the log with 1.11.1 (no issue):
````
[Macaron] 2020-03-31 00:22:55: Started GET /CM/DeliveryPlan/milestones/11/close for 10.247.156.10
[Macaron] 2020-03-31 00:22:55: Completed GET /CM/DeliveryPlan/milestones/11/close 302 Found in 10.538579ms
[Macaron] 2020-03-31 00:22:55: Started GET /CM/DeliveryPlan/milestones?state=closed for 10.247.156.10
[Macaron] 2020-03-31 00:22:55: Completed GET /CM/DeliveryPlan/milestones?state=closed 200 OK in 12.823443ms
[Macaron] 2020-03-31 00:22:55: Started GET /user/avatar/confman/-1 for 10.247.156.10
[Macaron] 2020-03-31 00:22:55: Completed GET /user/avatar/confman/-1 302 Found in 3.813212ms
````
This is the log with 1.11.3 (with issue):
````
[Macaron] 2020-03-31 00:37:52: Started GET /CM/DeliveryPlan/milestones/13/close for 10.247.156.10
[Macaron] 2020-03-31 00:37:52: Completed GET /CM/DeliveryPlan/milestones/13/close 404 Not Found in 178.209705ms
[Macaron] 2020-03-31 00:37:52: Started GET /user/avatar/confman/-1 for 10.247.156.10
[Macaron] 2020-03-31 00:37:52: Completed GET /user/avatar/confman/-1 302 Found in 3.92937ms
````

## Screenshots
![milestone_error](https://user-images.githubusercontent.com/3716953/77967823-38d8d380-72e6-11ea-86b3-bdd0bfeb2339.png)

**Comment by jolheiser** [comment]
Are you using a custom template? Those should be POST actions.

**Comment by mbarinc** [comment]
Thannk you @jolheiser for the tip.
I had a custom template, based on a old version.
Now works!
