### ISSUE TITLE
Autoupdateing mirrors after Gitea start

### ISSUE THREAD

**Issue by Monter** [go-gitea/gitea#10893]
- Gitea version (or commit ref): 1.12.0+dev-60-g3f0cb8b33 binary from here
- Git version: 2.11.0
- Operating system: Debian x64
- Database (use `[x]`):
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Not relevant

## Description

I have many projects (150+) in the database, most of which are migrations with the mirror option. Every time Gitea is updated, there is a problem: Gitea tries to refresh them immediately after startup, which kills the server CPU. Where can this option be turned off so that mirrors are refreshed only according to the schedule (set for me once every 24h)?

**Comment by techknowlogick** [comment]
See https://docs.gitea.io/en-us/config-cheat-sheet/#cron-cron where you can disable cron tasks from running at startup.
