### ISSUE TITLE
fatal error: 'stdlib.h' file not found

### ISSUE THREAD

**Issue by Inniss0903** [go-gitea/gitea#10891]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
fatal error: 'stdlib.h' file not found
It always happens when I use VSCode to build bindata or run test.
By the way, my computer is mac.
...

## Screenshots
![image](https://user-images.githubusercontent.com/33971175/77915221-a7f3ff00-72c9-11ea-9212-67c52592b3ce.png)

**Comment by mrsdizzie** [comment]
You probably need to install MacOS development tools:

```xcode-select --install```

**Comment by Inniss0903** [comment]
Thanks for your suggestion. I have tried, but it still not working.

**Comment by guillep2k** [comment]
`stdlib.h` is not a part of Gitea or even of Go, so it must be provided by the OS and/or the C compiler. Have you checked where in your file-system is this file located? Maybe you need to set up some variable or setting with default tool paths. VSCode tends to have its own life when it comes to settings and configuration files.

**Comment by berryamin** [comment]
@Inniss0903 This post is probably relevant:

![image](https://user-images.githubusercontent.com/37262984/78506573-b84d2380-777a-11ea-8a56-f713fdd7d6b2.png)

https://stackoverflow.com/questions/52509602/cant-compile-c-program-on-a-mac-after-upgrade-to-mojave

**Comment by zeripath** [comment]
I think @berryamin 's comment explains how to fix this problem. If it doesn't please re-open, otherwise I'm going to close it.
