### ISSUE TITLE
Default avatars load 10-20 seconds - federated avatars too slow

### ISSUE THREAD

**Issue by hrvoj3e** [go-gitea/gitea#10900]
Should federated avatars feature have a shorter timeout?

I can use Gitea but browser tab keeps on loading. 
Load time multiplies with number od different users that have the default avatar.

Gitea version (or commit ref): 1.11.3
Example URL
 - https://my.gitea.server/user/avatar/username/-1

Solved with  `ENABLE_FEDERATED_AVATAR = false`
```properties
[picture]
AVATAR_UPLOAD_PATH            = /data/gitea/avatars
REPOSITORY_AVATAR_UPLOAD_PATH = /data/gitea/repo-avatars
DISABLE_GRAVATAR              = false
## takes too long - turn off
ENABLE_FEDERATED_AVATAR       = false
```

**Comment by lafriks** [comment]
This should be resolved with #10540
