### ISSUE TITLE
[Solution] open conf/locale/locale_en-US.ini: no such file or directory

### ISSUE THREAD

**Issue by hillbicks** [go-gitea/gitea#10907]
Hey everyone,

since the original was closed a couple of days and the error mentioned in the title comes up after an update on arch, I wanted to post the solution and how I got there. Hopefully it helps some of you (although it is fairly simple)

Error in the logfile is straight forward, one specific file is not found. I then looked for the file in question on my filesystem (locate locale_en-US.ini). 

The path in arch is 
`/usr/share/gitea/options/locale/locale_en-US.ini`

arch also delivered a new app.ini file with the update. I grep'ed for /usr/share in the new app.ini file and now STATIC_ROOT_PATH  is set, in the previous version this parameter was empty. So the solution is to set 

`STATIC_ROOT_PATH                = /usr/share/gitea`

mentioning @aureooms as he had the same problem on arch

**Comment by aureooms** [comment]
Thanks @hillbicks ! Entry in Arch bug tracker is [here](https://bugs.archlinux.org/task/66011).

**Comment by frnmst** [comment]
Thanks! Saved my day
