### ISSUE TITLE
Attachment links are not human readable again

### ISSUE THREAD

**Issue by xoxys** [go-gitea/gitea#10919]
- Gitea version (or commit ref): 1.11.4
- Operating system: CentOS 7
- Database (use `[x]`):
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite

## Description
After upgrading to v1.11.3 release attachment links are not human-readable again and now looks like `https://gitea.example/attachments/a0023262-7abf-461d-9271-2e9f195ecebc` instead of `https://gitea.example/xoxys/cups-rpm/releases/download/v.1.0.0`.

**Comment by jolheiser** [comment]
The change was in #9529 and this functionality can return once #9534 is fixed.

Until then, the URL pattern still works, it's just no longer exposed on the UI. 🙁 

e.g.  
https://try.gitea.io/jolheiser/ciw/releases  
https://try.gitea.io/jolheiser/ciw/releases/download/test2/simplog.png

**Comment by 6543** [comment]
@xoxys you still can use the `https://gitea.example/xoxys/cups-rpm/releases/download/v.1.0.0`

IT STILL works - but it there is a problem with name colision/ same names...
"if #9534 got implemented we can switch back to human redable"

**Comment by xoxys** [comment]
Ok than I'll still wait

**Comment by xoxys** [comment]
Keep until fixed?

**Comment by xoxys** [comment]
Is there still no fix for it? Even if I can build the readable URLs on my own, it's pretty hard for the "normal" user. I am surprised that I am the only one who is bothered by it :smile:

**Comment by nguyenxndaidev** [comment]
I have a related issue with attachment URL. Not sure if I need to create a new ticket or this one will fix it too.

Assuming, I have the gitea configured as http://192.168.1.1:1234.
There's a revert proxy in my local network point to this server: http://gitea.home

If I open a release page http://gitea.mr.home/org/repo/releases, I will have 3 URLs:
[Source Code (ZIP)](http://gitea.home/org/repo/archive/0.0.1-SNAPSHOT.zip)
[Source Code (TAR.GZ)](http://gitea.home/org/repo/archive/0.0.1-SNAPSHOT.tar.gz)
[attachment.zip](http://192.168.1.1:1234/attachments/a3793480-68ed-48c9-ae70-e57e512383b2)

I would expect, the attachment URL use http://gitea.home, same as Source Code URLs.

**Comment by wxiaoguang** [comment]
Can we just take the simple fix in https://github.com/go-gitea/gitea/pull/13750 at the moment, and make future PRs for the remaining TODOs? @6543

**Comment by drsybren** [comment]
I would also welcome more human-readable URLs.

Maybe the URL matching patterns can be altered to accept any name after the UUID? That way a link can be constructed like `http://gitea.home/attachments/a3793480-68ed-48c9-ae70-e57e512383b2/original-filename.txt`. This ensures that the URL is still unique, but also ensures that doing a `wget {url}` saves to the correct filename.

Personally this would make my workflow of investigating Blender bug reports a lot easier. What I used to do (before moving to Gitea) was to type `wget ` in a terminal, with the current working directory already set to where I want the file to be, then drag the link from my webbrowser to the terminal (which pastes it after the `wget` command).
