### ISSUE TITLE
CSS broken, index.js is HTML

### ISSUE THREAD

**Issue by dadosch** [go-gitea/gitea#10922]
- Gitea version (or commit ref):  1.11.4 
- Git version:-
- Operating system: Arch Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description
After a upgrade to 1.11.4, the CSS is broken in Firefox, the console shows:

> Stylesheet https://host/user/login was not loaded because its MIME type, "text/html", is not "text/css". (roughly translated from German)

> SyntaxError: expected expression, got '<' (for index.js),

/js/index.js?v=[somestring] returns 
```
<a href="/user/login">Found</a>.

```

**Comment by jolheiser** [comment]
Seems this is related to this bug https://bugs.archlinux.org/task/66011

**Comment by jolheiser** [comment]
If this turns out to be something different, feel free to re-open. 😄

**Comment by dadosch** [comment]
This was https://github.com/go-gitea/gitea/issues/10907, if I'm not wrong…
But there, gitea didn't even start. I will ask on the Arch Bug Report page.
