### ISSUE TITLE
[Bug] diff_url & patch_url not accesible via token on private repos

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#10923]
diff_url & patch_url do not respect token Header

but they are exposed via api. example: https://try.gitea.io/api/v1/repos/abcKing/s/pulls/2

**Comment by 6543** [comment]
same problem with `https://gitea.com/test-organisation/TestRepo/commit/c6d7b3932327408cc495077d94ca0a0c918f6eff.(patch|diff)`

**Comment by 6543** [comment]
still here

**Comment by zeripath** [comment]
These urls are suburls of the HTMLUrl for the pull request - the simplest solution is just to provide API based endpoints which is what I've done.
