### ISSUE TITLE
Submit forms with Ctrl+Enter combination

### ISSUE THREAD

**Issue by k0va1** [go-gitea/gitea#10937]
I really enjoy to submit any form in WEB just pressing Ctrl+Enter(or Cmd+Enter on MacOS) combination. It's faster, more convenient and just better UX.

Pages where I want this feature:
* issues
* comments
* PR's    
...

BTW: #2526 fix doesn't work for me(at try.gitea.io)

**Comment by silverwind** [comment]
Can be done using [Mousetrap](https://craig.is/killing/mice) and `Mod+Enter` shortcut. Note that text elements need a [special class](https://craig.is/killing/mice#api.bind.text-fields) for it to work.
