### ISSUE TITLE
[BUG] [API] RepoInfo incorect Release Counter

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#10946]
Gitea Version: 1.12.0+dev-72-g2c25e75dc

web show 18 releases: https://gitea.com/gitnex/GitNex/releases
api 0: https://gitea.com/api/v1/repos/Gitnex/gitnex

**Comment by jolheiser** [comment]
It returns all of them for me. 

https://gitea.com/api/v1/repos/Gitnex/gitnex/releases

**Comment by jolheiser** [comment]
🤦‍♂ Ignore me, I understand now.

**Comment by 6543** [comment]
Need Backport to 1.11
