### ISSUE TITLE
Proxysupport for webhooks

### ISSUE THREAD

**Issue by Schwobaland** [go-gitea/gitea#1094]
It should be possible to set a http-proxy in app.ini for webhooks.
There should be 3 properties:
- HTTP_PROXY
- HTTPS_PROXY
- NO_PROXY

Alternatively env-variables could be used. This would ease the docker-deployment.

**Comment by tboerger** [comment]
That should already work if your system provides these environment variables?

**Comment by Schwobaland** [comment]
I tested on MacOS and Windows - and it doesn't work. I think, because of the proxy-property is always overwritten [here](https://github.com/go-gitea/gitea/blob/master/modules/httplib/httplib.go#L308). In default go-Transport-implementation `ProxyFromEnvironment` is [used](https://golang.org/src/net/http/transport.go).

**Comment by lunny** [comment]
resolved by #1096
