### ISSUE TITLE
Unable to cross compile from amd64 to arm7 with bundled assets

### ISSUE THREAD

**Issue by int3rrupted** [go-gitea/gitea#10949]
- Gitea version (or commit ref): latest from master
- Git version: 2.17.1
- Operating system: Linux Ubuntu Bionic amd64
- Database:
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

I am unable to cross compile from amd64 to arm7 with bundled assets (using the `bindata` tag). Without bundled assets cross compilation is successful, furthmore compiling to the same arch (amd64) with bundled assets is also successful.

The following command line is successful:
`GOOS=linux GOARCH=arm TAGS="sqlite sqlite_unlock_notify" make build`

The following command line is successful:
`GOOS=linux GOARCH=amd64 TAGS="bindata sqlite sqlite_unlock_notify" make build`

The following command line fails:
`GOOS=linux GOARCH=arm TAGS="bindata sqlite sqlite_unlock_notify" make build`

go version: 1.14.1 linux/amd64
## Screenshots

![image](https://user-images.githubusercontent.com/42919738/78421626-d2b4cd80-76a4-11ea-8617-b2a053f18d47.png)

**Comment by bagasme** [comment]
related discussion at [discord](https://discordapp.com/channels/322538954119184384/322538954119184384/695802972659122226)

**Comment by int3rrupted** [comment]
The proposed patch #10952 should also prevent the `CC` environment variable being passed to `generate` as this results in further cross compilation errors when `CGO` is enabled.

The following command line fails with proposed patch applied:
`CC=arm-linux-gnueabi-gcc CGO_ENABLED=1 GOOS=linux GOARCH=arm GOARM=7 TAGS="bindata sqlite sqlite_unlock_notify" make build`

**Comment by lunny** [comment]
I think if you execute the command spereately, it should work in fact.
```
make generate
CC=arm-linux-gnueabi-gcc CGO_ENABLED=1 GOOS=linux GOARCH=arm GOARM=7 TAGS="bindata sqlite sqlite_unlock_notify" make build
```

**Comment by int3rrupted** [comment]
The error persists even when `generate` is run seperately with no environment passed.

**Comment by lunny** [comment]
@int3rrupted Please try again.

**Comment by int3rrupted** [comment]
Thank you @lunny. Gitea compiles and runs as expected with the new patch.
