### ISSUE TITLE
Cross-Compilation Support

### ISSUE THREAD

**Issue by bagasme** [go-gitea/gitea#10950]
## Description

Currently to cross compile Gitea, one had to set proper variables when invoking make, like `GOOS=linux GOARCH=arm64 make generate build`.

We should add convenient makefile target that set appropriate variables above, so one can cross compile Gitea for ARM64 by invoking `make build-linux-arm64`.

Note that cross-compiling with `bindata` tag is currently broken, as reported on #10949. sqlite will not be supported since it requires `cgo`, which depend on C compilers.

**Comment by lafriks** [comment]
I think we should keep this simple as possible as we can't create all possible target compilations and keep it with sync with golang supported platforms

**Comment by lunny** [comment]
Currently `GOOS=linux GOARCH=arm64 make generate build` will not work because we should not give the `GOOS` and `GOARCH` enviorment to `generate`.

**Comment by lunny** [comment]
Closed by #10952
