### ISSUE TITLE
PR / Issue templates do not get rendered during PR creation

### ISSUE THREAD

**Issue by dirien** [go-gitea/gitea#10975]
- Gitea version (or commit ref): 1.11.3
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
We created pull request template  in the same way it is written in the documentaton https://docs.gitea.io/en-us/issue-pull-request-templates/. That worked fine.

The only issue we see now is, that wenn yo create a Pull Request the description field is empty. Only when you click in the "Write" field the tempates get rendered. Otherwise it stays empty. So the users dont have a hint to fill it out. Worst case, no description as it is not mandatory field.

In github, it gets renderd, as soon you create the PR 

## Screenshots
new PR - no template rendered:
<img width="1302" alt="new_pr" src="https://user-images.githubusercontent.com/38325136/78502669-816b1380-7762-11ea-863d-6e9996201341.png">

click on Write-Field:
<img width="1238" alt="click_of_write" src="https://user-images.githubusercontent.com/38325136/78502698-a495c300-7762-11ea-8818-5c9e0f1c741c.png">
te - templates get renderd

**Comment by 6543** [comment]
afects current master too
