### ISSUE TITLE
CSS class names concatenated together for PR merge box

### ISSUE THREAD

**Issue by taai** [go-gitea/gitea#10973]
- Gitea version (or commit ref): 1.12.0+dev-89-gb264c3039
- Git version: 2.20.1
- Operating system: Debian 10
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

In the pull request page the git icon previously was green, but now it is blue. The reason – the CSS class names "text" and "green" are concatenated together as "textgreen" (and there is no such CSS class)...

## Screenshots

![image](https://user-images.githubusercontent.com/90734/78499641-95127c00-775a-11ea-86b7-b817273a4095.png)
![image](https://user-images.githubusercontent.com/90734/78499660-b2474a80-775a-11ea-8768-24e78bca02f4.png)

**Comment by a1012112796** [comment]
It's a bug made by me, sorry. I forget to add some space. I will change it soon. Thanks for your response.
