### ISSUE TITLE
Docker image for linux/arm/v8

### ISSUE THREAD

**Issue by aboimpinto** [go-gitea/gitea#10976]
I'm trying to install the Gitea in a Raspbery Pi4 with Ubuntu server  and when I run:
$ sudo docker-compose up

I get this message
ERROR: no matching manifest for linux/arm/v8 in the manifest list entries

Is it possible to have a docker version for this architecture too?

Thanks
Paulo Aboim Pinto

**Comment by lunny** [comment]
Have you use `gitea/gitea:linux-arm64` ?

**Comment by aboimpinto** [comment]
Thanks for the answer.

I replace in my docker-compose.yaml the image to: gitea/gitea:linux-arm64
and now I get this error

Pulling server (gitea/gitea:linux-arm64)...
linux-arm64: Pulling from gitea/gitea
8a0637ca1ac9: Pull complete
3ca09696dc93: Pull complete
3c29a0809305: Pull complete
bbc6f3beb755: Pull complete
f81b55737f70: Pull complete
dd4b71381686: Pull complete
Digest: sha256:49dfd1fa87b6e7b889a0e3434ca17ca2126748549ad138852a2cd630fdef1745
Status: Downloaded newer image for gitea/gitea:linux-arm64
Creating gitea_server_1 ... error

ERROR: for gitea_server_1  Cannot create container for service server: error creating aufs mount to /var/lib/docker/aufs/mnt/58ba628f978cb42273c141fd46abfb908e32c0bf2859ac474e86498963add260-init: mount target=/var/lib/docker/aufs/mnt/58ba628f978cb42273c141fd46abfb908e32c0bf2859ac474e86498963add260-init data=br:/var/lib/docker/aufs/diff/58ba628f978cb42273c141fd46abfb908e32c0bf2859ac474e86498963add260-init=rw:/var/lib/docker/aufs/diff/f233e220455acea62b9a9002f1e249189dffa00be6f3618e290901943e0a153a=ro+wh:/var/lib/docker/aufs/diff/6680d001ede8f2b2aa3bb58d3c69759dafd919bb93e4f95e4eebc11e422dbb1f=ro+wh:/var/lib/docker/aufs/diff/bb8316ef6fc0d893c888d3b1f5d14dd64131a419c1688eb0e34bb6ab6bc5d2c3=ro+wh:/var/lib/docker/aufs/diff/299f397fee9219f8bb6768c0c1f422e23b42a0d113420d8ff29a2366040523fe=ro+wh:/var/lib/docker/aufs/diff/fdf3fa47325db96f03490bd5a89722e2a04ed1caf03d59538f0d850c2140d6c2=ro+wh:/var/lib/docker/aufs/diff/848b162a265feb76cbba0899c96415cd6217c37a4bdeef4799ffb3c1e638a3c5=ro+wh,dio,xino=/dev/shm/aufs.xino: invalid argument

ERROR: for server  Cannot create container for service server: error creating aufs mount to /var/lib/docker/aufs/mnt/58ba628f978cb42273c141fd46abfb908e32c0bf2859ac474e86498963add260-init: mount target=/var/lib/docker/aufs/mnt/58ba628f978cb42273c141fd46abfb908e32c0bf2859ac474e86498963add260-init data=br:/var/lib/docker/aufs/diff/58ba628f978cb42273c141fd46abfb908e32c0bf2859ac474e86498963add260-init=rw:/var/lib/docker/aufs/diff/f233e220455acea62b9a9002f1e249189dffa00be6f3618e290901943e0a153a=ro+wh:/var/lib/docker/aufs/diff/6680d001ede8f2b2aa3bb58d3c69759dafd919bb93e4f95e4eebc11e422dbb1f=ro+wh:/var/lib/docker/aufs/diff/bb8316ef6fc0d893c888d3b1f5d14dd64131a419c1688eb0e34bb6ab6bc5d2c3=ro+wh:/var/lib/docker/aufs/diff/299f397fee9219f8bb6768c0c1f422e23b42a0d113420d8ff29a2366040523fe=ro+wh:/var/lib/docker/aufs/diff/fdf3fa47325db96f03490bd5a89722e2a04ed1caf03d59538f0d850c2140d6c2=ro+wh:/var/lib/docker/aufs/diff/848b162a265feb76cbba0899c96415cd6217c37a4bdeef4799ffb3c1e638a3c5=ro+wh,dio,xino=/dev/shm/aufs.xino: invalid argument
ERROR: Encountered errors while bringing up the project.

**Comment by nunojusto** [comment]
I ran a manual command in Raspbian and gives the same:
```
pi@raspberrypi:~ $ sudo docker run gitea/gitea:linux-arm64
Unable to find image 'gitea/gitea:linux-arm64' locally
linux-arm64: Pulling from gitea/gitea
8a0637ca1ac9: Pull complete 
2b31396a44cb: Pull complete 
132da679572e: Pull complete 
3212eb07d3dc: Pull complete 
7db4ff6b5549: Pull complete 
7bfb9446c546: Pull complete 
Digest: sha256:431216e2eea2f2de31e137ae65f1d3d85a29aaa0a50cea81557f455c33e73fc3
Status: Downloaded newer image for gitea/gitea:linux-arm64
docker: Error response from daemon: error creating aufs mount to /var/lib/docker/aufs/mnt/0be0ca07e886e6ce3e1c790e3ffc65a1891c363693e4abe500c95b741f229258-init: mount target=/var/lib/docker/aufs/mnt/0be0ca07e886e6ce3e1c790e3ffc65a1891c363693e4abe500c95b741f229258-init data=br:/var/lib/docker/aufs/diff/0be0ca07e886e6ce3e1c790e3ffc65a1891c363693e4abe500c95b741f229258-init=rw:/var/lib/docker/aufs/diff/b13eab1ad6c6941ca84cfc38340769c26f9d577f8a3effeeea032b9031114256=ro+wh:/var/lib/docker/aufs/diff/e6c843a1a7db2d34403063de1bd52ddd35ea78b900a5cc1790504eaf4ae92a60=ro+wh:/var/lib/docker/aufs/diff/5f2703f881d96991bf2b226efa716bba3c8f15eeb09521755f2c77420e01a0bc=ro+wh:/var/lib/docker/aufs/diff/ef117f6dc51a3606a437c2f70d194d6c2ec4d09e6f3ecb0d75bef1dc4a9cf02a=ro+wh:/var/lib/docker/aufs/diff/4cc825a70255588c2729e07a6267410e4ac3b3f89406eeb588bc164f2fc78843=ro+wh:/var/lib/docker/aufs/diff/232bf22fab29bb132b60d66dac916433e0dbbfefb7be4cd290fd9d468e8895b3=ro+wh,dio,xino=/dev/shm/aufs.xino: invalid argument.
```

Does that image runs on raspberry pi 4?
Or was only tested in raspberry pi 3?

**Comment by techknowlogick** [comment]
@nunojusto you are running linux/arm version of docker and the image is linux/arm64, we don't (yet) have an image available for linux/arm.

As for @aboimpinto your issue looks like a filesystem issue, and docker is unable to create the layered FS. Per https://docs.docker.com/storage/storagedriver/aufs-driver/ it is recommended to use overlay2 in case you are using aufs.

I will close this issue now, but if the issue persists after switching to overlay2 please feel free to re-open.
