### ISSUE TITLE
mailer IS_TLS_ENABLED=true Gmail problem

### ISSUE THREAD

**Issue by mariusrugan** [go-gitea/gitea#10971]
- Gitea version (or commit ref): 1.12.0+dev-89-gb264c3039 built with GNU Make 4.2.1, go1.14.1 : bindata, sqlite, sqlite_unlock_notify 
- Git version:
- Operating system: Linux / latest docker image gitea/gitea
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description

Mailer sends email via google **only with IS_TLS_ENABLED=false**,  otherwise throws error:

`Failed to send a testing email to 'example@gmail.com': gomail: could not send email 1: NewClient: tls: first record does not look like a TLS handshake
`

I'm using this configuration:

```
ENABLED        = true
HOST           = smtp.gmail.com:587
FROM           = example@gmail.com
USER           = example@gmail.com
PASSWD         = ***
MAILER_TYPE    = smtp
IS_TLS_ENABLED = false
HELO_HOSTNAME  = example.com

```

Not using Gsuite, just a simple gmail account.

**Comment by guillep2k** [comment]
I think, you should be using port 465 instead of 587. As far as I recall 465 is TLS-only, but 587 is a cleartext SMTP port with STARTTLS support.

**Comment by mariusrugan** [comment]
Thanks @guillep2k !,  works 
i've switched port to `465` and `IS_TLS_ENABLED=true`

```
[mailer]
ENABLED        = true
HOST           = smtp.gmail.com:465
FROM           = example@gmail.com
USER           = example@gmail.com
PASSWD         = ***
MAILER_TYPE    = smtp
IS_TLS_ENABLED = true
HELO_HOSTNAME  = example.com
```

This config should make its way in docs, should i open a PR and tag you for approval ? (i'm a gitea  noob)

**Comment by zeripath** [comment]
@mariusrugan feel free to suggest changes to #10995

**Comment by Th3Whit3Wolf** [comment]
So glad I found this! I am self hosting a mailcow instance on another server. The docs make it look like it should be using port 587 when as @guillep2k mentions it should be 465. Problem solved. Thank you guys!!
