### ISSUE TITLE
Can't open gitea on Kodexplore

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#10985]
- Gitea version (or commit ref):1.12.0+dev-436-gfb76136ae 
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description
I can't browse gitea on kodexplore,the window show "refuse link",but on the browser i can open it.
...

## Screenshots
![2020-04-06_114615](https://user-images.githubusercontent.com/43057595/78521609-00148f00-77fd-11ea-8e73-35b3e3524fa1.jpg)
![2020-04-06_114552](https://user-images.githubusercontent.com/43057595/78521615-060a7000-77fd-11ea-88ce-c7279885d75c.jpg)

**Comment by jolheiser** [comment]
Are there any errors in any logs? 
Also, what _is_ kodexplorer? Is the problem perhaps on its end?

**Comment by amColinzzz** [comment]
> Are there any errors in any logs?
> Also, what _is_ kodexplorer? Is the problem perhaps on its end?

I use 'docker logs gitea' to view the logs,no error level logs on the screen.The kodexplore is a personal web disk,it has a function is desktop,can browse web page on it's inside.

**Comment by guillep2k** [comment]
Seems like it's not a problem of Gitea.
