### ISSUE TITLE
Releases page is 404 after migrating from 1.2.3 to 1.11.3

### ISSUE THREAD

**Issue by rougin** [go-gitea/gitea#10987]
- Gitea version (or commit ref): 1.11.3
- Git version: 2.22
- Operating system: CentOS 6
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

Hi, I would like to raise an issue regarding the "Releases" page being 404 after upgrading it to 1.11.3 from 1.2.3. For the upgrading process, I tried to upgrade to each version (1.2 to 1.3 then 1.3 to 1.4, etc.). Even though there are some issues encountered along the way, I managed to upgrade its version to the latest but I overlooked this one.

I initially thought this was caused by the Git version as stated on https://github.com/go-gitea/gitea/issues/1133 so I updated the Git to its latest version but the issue still persists. When I go to the FAQ page, I executed the commands found in the **Missing releases after migrating repository with tags** but with no progress. I guess this might be a UI issue so I tried to access it directly through a URL however it shows 404.

I can confirm also that the Releases page will only show on created repositories after the said upgrade. I created a new repository and pushed a single file then the Releases page shows up after. This is not the case on existing repositories though.

**Comment by lunny** [comment]
It may because you lost some data on `repo_unit`. I remember somebody has workround about that you can search on issues.

**Comment by rougin** [comment]
Hi, @lunny thanks for the response. Fortunately, I was able to fix this issue on my own. In the settings of the specified repository, I just press the **Update Settings** button in the **Advanced Settings** and both Releases and Activity tabs were now visible on the page. With this, I will now close this issue.
