### ISSUE TITLE
ci on master continue fail in two day ...

### ISSUE THREAD

**Issue by a1012112796** [go-gitea/gitea#10984]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
maybe problem is here:
<img width="669" alt="jtci" src="https://user-images.githubusercontent.com/25342410/78518056-cbe7a100-77f1-11ea-94c7-7005bab809e2.png">

**Comment by mrsdizzie** [comment]
Yes this is known issue

**Comment by a1012112796** [comment]
please solve it, It blocked docker image update, Thanks

**Comment by mrsdizzie** [comment]
fixed https://drone.gitea.io/go-gitea/gitea/23401/5/1
