### ISSUE TITLE
searching Pull Request by title

### ISSUE THREAD

**Issue by mbarinc** [go-gitea/gitea#10980]
- Gitea version (or commit ref): 1.11.4
- Git version: 2.23
- Operating system: Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
I would like to propose to add searching pull request by title in the pulls page. If possible extend the search in the conversation too.
By default the serching is by title, but with regular expression extend to the conversation (for example`title:<keyword>` `conversation:<other keyword>`

I think that would be a nice feature, it's possible?

Thanks

## Screenshots
![PR_search](https://user-images.githubusercontent.com/3716953/78509709-6c0cde00-7790-11ea-9545-32f18b10715f.png)

**Comment by 6543** [comment]
@mbarinc so this is a feature request for **extending** the search on pulls?

**Comment by mbarinc** [comment]
@6543 yes, thanks

**Comment by 6543** [comment]
@mbarinc pleace look at https://try.gitea.io/ it runns with current master version.
we already have this :). and it will be in 1.12.0

**Comment by mbarinc** [comment]
Guys you are wonderful! I tried on https://try.gitea.io/ and it is exactly what I need! I will waiting the 1.12 stable version to install it on my server.
