### ISSUE TITLE
Organization labels missing

### ISSUE THREAD

**Issue by dimmuboy** [go-gitea/gitea#10992]
- Gitea version (or commit ref): 1.11.4
- Git version: 2.25.0
- Operating system: Windows Server 2008
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant

## Description

I have no **Labels** option in my Organisation setting. In https://try.gitea.io this option is available.

## Screenshots

![image](https://user-images.githubusercontent.com/12607479/78562164-3cee7f00-7819-11ea-996d-c8c281a02b22.png)

**Comment by jolheiser** [comment]
#110814 is the PR to introduce this, it won't be available until 1.12.0

**Comment by a1012112796** [comment]
Hello, I think maybe we can do  some extend for this feature, that means we can allow users to define their own labels which can be used in all repos owned by them like an org. Thanks
