### ISSUE TITLE
Web editor indentation

### ISSUE THREAD

**Issue by joubertredrat** [go-gitea/gitea#11]
Now with web editor working fine, I think that is necessary to set configurations by default or defined by user for better experience with web editor.

On PHP, javascript and I think that Go (Unknwon talk me if I'm wrong) we prefer 4 spaces indentation.
However, HTML and CSS developers normally prefer 2 spaces indentation. Have cases on other developers prefer tabulation instead spaces.

Because this I think that web editor can be configurable, one good example for this is on Bitbucket, you can set options in own editor.

![screenshot-bitbucket org 2016-09-06 13-25-57](https://cloud.githubusercontent.com/assets/1520407/18281998/8599e9a6-7435-11e6-94a4-bc4492e2ee33.png)

Or this configuration can be defined on user settings on only on admin area.

What you think guys?

Reference: https://github.com/gogits/gogs/issues/3460#issuecomment-242807939
Reference: https://github.com/gogits/gogs/issues/3610

**Comment by metalmatze** [comment]
`gofmt` uses tabs and one tab equals 8 spaces. 
https://golang.org/cmd/gofmt/
I really like the idea to make it customizable!

**Comment by silverwind** [comment]
Customization options could be saved to `localStorage` on the client, but the defaults should come from the repository's `.editorconfig`.

**Comment by pgaskin** [comment]
What would be the scope of the saved changes? The repo? The filetype? The filepath? The session?

**Comment by silverwind** [comment]
I'd say per-user options are sufficient. If you want finer control, you're better of placing a `.editorconfig` in the repo.

**Comment by megadr01d** [comment]
>  If you want finer control, you're better of placing a `.editorconfig` in the repo.

I agree here but... when has this stopped working? I searched for open issues on editorconfig but didn't find anything and I'm positive it worked at some point.  I can confirm that `insert_final_newline = true` or `trim_trailing_whitespace = true` are not inserting or trimming anything.

https://github.com/go-gitea/gitea/blob/master/.editorconfig#L7
https://github.com/go-gitea/gitea/blob/master/main.go
