### ISSUE TITLE
Link to submodule hosted by the same server via ssh missing port/prefix

### ISSUE THREAD

**Issue by bwiethof** [go-gitea/gitea#11002]
- Gitea version (or commit ref): 1.10.0
- Git version:
- Operating system: 
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
If a submodule is hosted by the **same server** as the parent repository and is linked via ssh, the link is missing the prefix/port. 
In case of http linking, the created link is valid. 

The screenshots showing the link for http in the left corner. With ssh the port/prefix is missing.

## Screenshots

![http](https://user-images.githubusercontent.com/62421461/78654282-9bbd0280-78c4-11ea-80ad-dbcdd9f5193b.png)
![ssh](https://user-images.githubusercontent.com/62421461/78654295-9f508980-78c4-11ea-808b-d284982316ec.png)

**Comment by yoyoyonas** [comment]
I can confirm this for v1.11.3.

**Comment by MatthieuParis** [comment]
Same thing for v.1.11.4.
Seems to be linked to issue #2882
