### ISSUE TITLE
[FEATURE] Keep edit history in local storage for backup, until applied server-side

### ISSUE THREAD

**Issue by brupelo** [go-gitea/gitea#11004]
If you don't save your issue it seems there won't be any backup or way to recover the content if you make some context change (page switching) so you'll end up losing your changes (I've experienced this few minutes ago that's why opening this issue). 

It'd be awesome to achieve a similar results to github's, here's a little demo of what I mean:

![showcase](https://dl.dropboxusercontent.com/s/09ww6er7e08w2vl/2020-04-07_13-26-06.gif)

**Comment by guillep2k** [comment]
This could be implemented in local storage on the client side, I think.

**Comment by brupelo** [comment]
@guillep2k That sounds like a great idea... I'd try to implement this feature myself by there are few limitations:

1. I'm still trying to figure out how to build gitea on windows... ie: [https://stackoverflow.com/questions/61096319/how-to-use-shell-find-on-make-for-windows](https://stackoverflow.com/questions/61096319/how-to-use-shell-find-on-make-for-windows)
2. I've never coded in go
3. Even if 1&2 would be satifsfied I would need to familiarize myself with the repo so I'm not sure this would be a good "First issue" for me.

That said, I'd love to have this one implemented so hopefully someone with expertise on the repo can take this one... I titled this one as `[FEATURE]` but to be honest, maybe should be labelled as a bug? I mean, yesterday I've lost my issue content after 5 minutes editing and that's not cool at all, right?

Thanks in advance.

**Comment by guillep2k** [comment]
1. To build on Windows you do that from Git Bash (if you install git, it will normally include Bash). It will not work from `power-shell` or the old `command`.
2. For this particular task I _think_ you only need to know front-end stuff. Just check how `web_src/js/index.js` works. I'm more of a back-end guy, though, so I might be missing something.
3. Only you can be the judge of that. 😄 

As for labeling goes, we would consider this change an "enhancement" (you've got me confused with "feature" there for a moment 😁).

**Comment by brupelo** [comment]
1. Hehe, yeah, I know... I love working with conemu and normal shells such as `command` so hopefully someone will bring some light to my question [here](https://stackoverflow.com/questions/61096319/how-to-use-shell-find-on-make-for-windows)... I strongly believe we should be able to tweak the existing Makefile to make it more cross-platform so it'll work on all terminals... In any case, I must to tell you I'm not a huge fan of using Makefiles as you're just adding an extra unnecesary dependency to the project... For instance, you've got deps with node+go and you could have achieved a similar result using just node or go to write the build system.
2. Oh, that's interesting, I'll take a look, yeah, I've got some experience coding in node... if there are other places you may recommend to take a look pls let me know, I'd like to start getting familiar with the basecode.
3. Hehe, well... I wouldn't mind to give it a shot (I assume you guys make code reviews?) but you'd need to explain a bit how this task should be done roughly.

Enhacement... ok? Although I still think this is a bug though ;)

**Comment by guillep2k** [comment]
@brupelo You say you're not very comfortable with bash and Makefile? Certainly you haven't had the exquisit experience or [configuring CMake](https://cmake.org/cmake/help/v3.17/).... 😵 After using CMake for a few days you would _beg_ for a build system written in COBOL. 🤣

**Comment by a1012112796** [comment]
Hello, I thinks it's also usefull for other places which can edit messages like Pull Request , comments and so on. so maybe the title of this issue should be change. Thanks

**Comment by brupelo** [comment]
@guillep2k Hehe... actually i've submited some patches to cmake in the past ;) ... Nah, seriously, don't get me wrong, I love bash et al & unix,, I tihnk unix terminals are the best thing after sliced break. In fact, I've always missed having these type of terminals on windows. Reason why I don't use msys, cygwin, wsl et al on windows is because some of my pure win dev environment will give problems there (python, visual studio sdk, c++ and other dev tools...). So I've found using conemu + builtin windows terminals the "less bad solution". 

My point is, by getting rid of unnecesary dependencies in a project and make it as cross-platform as possible is a good thing... And again, don't get me wrong again, I like make when it comes to pure unix projects... and if i could compile gitea on `cmd` using make for windows I wouldn't have "complained" in the first place ;)

@a1012112796 Sure thing, please free to suggest a new beetter title as well as editing the initial issue to capture better the intent if you think that'll make it better.

**Comment by bryanpedini** [comment]
@brupelo
> @a1012112796 Sure thing, please free to suggest a new beetter title as well as editing the initial issue to capture better the intent if you think that'll make it better.

How "Keep edit history in local storage for backup, until applied server-side", or something like that, sounds?

**Comment by bryanpedini** [comment]
@stalebot shut up...
that's why I activated notifications.

Issue still to be solved (any news?)

**Comment by bryanpedini** [comment]
> Reason why I don't use msys, cygwin, wsl et al on windows is because some of my pure win dev environment will give problems there (python, visual studio sdk, c++ and other dev tools...). So I've found using conemu + builtin windows terminals the "less bad solution".

@brupelo PS: have you thought about a VM with a Windows inception in another Windows, to develop Gitea?
(do you need / want any help either about the VM or with coding? I'm learning go right now since three months now)

**Comment by wxiaoguang** [comment]
Dup of
* https://github.com/go-gitea/gitea/issues/1315
