### ISSUE TITLE
[FEATURE] Reference autocompletion on issues

### ISSUE THREAD

**Issue by brupelo** [go-gitea/gitea#11005]
1. It'd be really awesome having an **autocomplete dialog** when you type `#` to search issues:

![showcase](https://dl.dropboxusercontent.com/s/wt4txujdpvi73r1/2020-04-07_13-31-39.gif)

2. Also, it'd be great when mouse overing on a reference issue displaying an **information dialog**:

![showcase](https://dl.dropboxusercontent.com/s/5lscf2phsr002mf/2020-04-07_13-33-18.gif)

**Comment by jolheiser** [comment]
The hover dialog is already implemented to an extent. 
However the issue search would be cool. :smiley:

**Comment by brupelo** [comment]
@jolheiser Oh, really? How can i enable it? I'm using latest gitea version and nothing appears when i mouse over the generated link, pls take a look:

![showcase](https://dl.dropboxusercontent.com/s/jaydx18z4rfn0i4/2020-04-07_16-44-14.gif)

Am I missing something here?

And yeah... issue search would rock :)

**Comment by jolheiser** [comment]
It is in version 1.12 which hasn't been released yet.  
I thought it was in 1.11 but I was mistaken.
