### ISSUE TITLE
Don't transform quotes in Markdown

### ISSUE THREAD

**Issue by silverwind** [go-gitea/gitea#11001]
Quotes outside of code blocks ([example](https://try.gitea.io/silverwind/symlink-test/issues/5)) are currently transformed to [U+201C Left Double Quotation Mark](https://www.compart.com/en/unicode/U+201C) and [U+201D Right Double Quotation Mark](https://www.compart.com/en/unicode/U+201D). I think this transformation is generally unwanted and confusing because it alters the original content, so I'd like to see it removed. GitHub also does not do this.

**Comment by bagasme** [comment]
@silverwind keep the quotes as-is?

**Comment by silverwind** [comment]
@bagasme yes that would be my preference. The less "magic" the better.

**Comment by guillep2k** [comment]
I agree, but maybe make it optional for wikis.

**Comment by zeripath** [comment]
Changing the default now is difficult to necessarily sign off. However, #11047 shows the way to do it.

Add a new frontmatter part:
```
---
gitea:
    typography: -smartQuotes
---
```
