### ISSUE TITLE
When try to make a migration not work Error SSL

### ISSUE THREAD

**Issue by liberodark** [go-gitea/gitea#11013]
Hi,

Just im want how to bypass this : 

Is message web try to make a migration to gitea.
server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
Have try to add key in on ca file + run update-ca-certificates but not work.

Best Regards

**Comment by bagasme** [comment]
@liberodark system version?

**Comment by liberodark** [comment]
Yes the last version is not really a bug of gitea ! (1.11.4)
But my ask is how to bypass this ?
In short, the server I want to migrate is signed by an internal pki.
So that's why he doesn't recognize the ssl certificate.
But how do you tell it not to check the ssl certificate when migrating from a git repo?

Best Regard

**Comment by liberodark** [comment]
Fixed : 

```
mkdir /usr/local/share/ca-certificates/extra
mv my_ca.crt /usr/local/share/ca-certificates/extra/
update-ca-certificates
```

Need crt file no import key manually
