### ISSUE TITLE
Update notifications

### ISSUE THREAD

**Issue by pgaskin** [go-gitea/gitea#1101]
There should be a notification or a system message when an update is available. If on a released version, then when a new version is available. On a master commit, it should show when more than 10 commits are added.

**Comment by lunny** [comment]
Do you mean #518 ?

**Comment by NotAFile** [comment]
This would still be a great idea

**Comment by 6543** [comment]
if implemented, it should be able to disable this with compile flag (for gitea instances deployed by package managers)

**Comment by fnetX** [comment]
This can be closed.
