### ISSUE TITLE
asciidoc render run command asciidoc [--out-file=- -] failed

### ISSUE THREAD

**Issue by qiuzhiqian** [go-gitea/gitea#11011]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

2020/04/08 17:46:21 ...external/external.go:101:Render() [E] asciidoc render run command asciidoc [--out-file=- -] failed: exit status 1

## Description
i set asciidoc in app.ini.but render has error.i have install asciidoc in my ubuntu server.

```
[markup.asciidoc]
ENABLED = true
; List of file extensions that should be rendered by an external command
FILE_EXTENSIONS = .adoc,.asciidoc
; External command to render all matching extensions
RENDER_COMMAND = "asciidoc --out-file=- -"
; Don't pass the file on STDIN, pass the filename as argument instead.
IS_INPUT_FILE = false
```
...

## Screenshots
![2020-04-08_17-54](https://user-images.githubusercontent.com/19386888/78771289-84fcd580-79c2-11ea-8ec2-ac8451dd7ec6.png)

![2020-04-08_17-55](https://user-images.githubusercontent.com/19386888/78771304-8c23e380-79c2-11ea-9140-76ae95f6f02b.png)

**Comment by guillep2k** [comment]
Try using `asciidoc`'s full path (e.g. `/usr/bin/asciidoc` or `/usr/local/bin/asciidoc`, etc.). Check your asciidoc actual path with `type`:

```
$ type asciidoc
asciidoc is /usr/bin/asciidoc
```

**Comment by lunny** [comment]
You may also needs to configure the `[markup.sanitizer]`, see https://docs.gitea.io/en-us/config-cheat-sheet/#markup-markup

**Comment by qiuzhiqian** [comment]
> Try using `asciidoc`'s full path (e.g. `/usr/bin/asciidoc` or `/usr/local/bin/asciidoc`, etc.). Check your asciidoc actual path with `type`:
> 
> ```
> $ type asciidoc
> asciidoc is /usr/bin/asciidoc
> ```

this file render well by my vscode.but can not render in my gitea.
now i try a very simple asciidoc file in my gitea repository, it seem work ok
![2020-04-09_10-41](https://user-images.githubusercontent.com/19386888/78852450-eb2f3a00-7a4e-11ea-8aa6-0c93abd53b68.png)

**Comment by qiuzhiqian** [comment]
> You may also needs to configure the `[markup.sanitizer]`, see https://docs.gitea.io/en-us/config-cheat-sheet/#markup-markup

i have try sanitizer config.but render faild too.

**Comment by qiuzhiqian** [comment]
i solve this problem.This problem is due to a wrong syntax highlighting in my asciidoc file.

I mistyped 

```
[source,bash]
....
$ git init
....
```
 into
```
[source.bash]
....
$ git init
....
```

thank your.

**Comment by qiuzhiqian** [comment]
Since my vscode preview is ok, I failed to find this problem.
