### ISSUE TITLE
How to close the gitea process.

### ISSUE THREAD

**Issue by lygoing** [go-gitea/gitea#11010]
- Gitea version (or commit ref):  Gitea version 1.10.1 built with GNU Make 4.1, go1.13.4 : bindata, sqlite, sqlite_unlock_notify
- Git version: git version 2.11.0
- Operating system: Debian 9.0 amd 64bit
- Database (use `[x]`): 
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description

Execute the kill command, the gitea process is not closed.
...

## Screenshots

![image](https://user-images.githubusercontent.com/5944432/78755008-05afd780-79ab-11ea-9bc4-354fadb59668.png)

**Comment by zeripath** [comment]
Your screenshot clearly shows that the gitea process running on 13685 has been shutdown.

**Comment by lygoing** [comment]
@zeripath  thank you, but the problem remains.
![image](https://user-images.githubusercontent.com/5944432/78792010-28f67900-79e3-11ea-93df-0a321389534d.png)

**Comment by zeripath** [comment]
All of those processes have different PIDs. Clearly something is restarting the Gitea process.

Have you installed a system d unit file?

**Comment by lygoing** [comment]
@zeripath   I didn‘t install the systemd unit. 
![image](https://user-images.githubusercontent.com/5944432/78849481-32b1c800-7a47-11ea-9868-ea4fbe87dd68.png)

I thought gitea had a special shutdown command, but I didn't find the shutdown instructions in the official documentation. I think it may be a problem with my operating system environment, but I really don't know how to solve it. Thanks again!

**Comment by zeripath** [comment]
Something is restarting your gitea process after it dies. That's either a systemd unit, openRC or docker process. How did you start gitea?

Gitea will restart itself by design if you send it a `kill -1` but will respond to a normal sigkill by shutting down.

**Comment by lygoing** [comment]
I just download through the release page of the github repository, and then `chmod a+x` to run. Root account execution of `kill -9` can't completely terminate the process.  Since it's a production environment, I cannot restart the machine. I want to close gitea just to upgrade to the latest version.

**Comment by guillep2k** [comment]
How did you start Gitea on the first place? By hand? Did you put it under /etc/init.d? Something weird is going on in your system.

Alternatively what you can do is this, just for the sake of upgrading: rename the file (`mv gitea gitea.old`), place the new version in the exact same location (`mv /downloads/new.gitea gitea`) and kill the process. It should use the new executable when restarting.
