### ISSUE TITLE
Code Search

### ISSUE THREAD

**Issue by ptman** [go-gitea/gitea#1102]
- Gitea version (or commit ref): 1.0.2
- Git version:
- Operating system:
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

I would very much like to search for code in all the repos my user has access to. I didn't find an issue for this yet, but please point me to the correct issue if I missed it.

**Comment by lunny** [comment]
I think you mean code search.

**Comment by ptman** [comment]
sure

**Comment by lunny** [comment]
This has been resolved by #2582.

**Comment by ptman** [comment]
Code search wasn't very well documented. And in addition to using lots of storage space, it also uses too much RAM.

**Comment by lunny** [comment]
@ptman I know that. We could improve it on future PRs.

**Comment by sichkarmg** [comment]
How can I search for code across all repositories in an organization?
The search works only by the name of the repository or its description.
I know how to enable code searching in one repository, but how in all?
Performance is not critical to me.
Thanks!

**Comment by lafriks** [comment]
Please submit new feature request to be able to search by repo owner
