### ISSUE TITLE
Authentication with not set header-variable and auto-register leads authentication with user (null)

### ISSUE THREAD

**Issue by crackytsi** [go-gitea/gitea#11026]
- Gitea version (or commit ref): 1.9.6
- Operating system: RHEL
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:

## Description

When authentication using header variables, but the variable is not provided and auto-register is enabled, a user "(null)" gets registered.
I expect that instead of this illegal user (with illegal attributes) the login fails and instead the user can try to login using user/password.

**Comment by guillep2k** [comment]
I'd suggest upgrading to 1.11.4. Version 1.9.6 is too old. Less than a year, I know, but a lot of code has been written since then. 😉

**Comment by lafriks** [comment]
Please update to latest version and reopen if bug still present
