### ISSUE TITLE
basic auth when unwrapping comment in PR

### ISSUE THREAD

**Issue by browcio** [go-gitea/gitea#11022]
- Gitea version (or commit ref): 1.12.0+dev-126-g743022116
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes (provide example URL): https://try.gitea.io/ppiwowa2/testrepo/pulls/3
  - [ ] No
  - [ ] Not relevant

## Description
Steps to reproduce:
1. Create new repo with long file
2. Change something in that file and create PR
3. Create single comment in code diff
4. In conversation view press up arrow in code block
5. basic auth pops up

Looks like gitea do not allow user to access /OWNER/REPO/blob_excerpt/.

**Comment by guillep2k** [comment]
Please make your `try.gitea.io` repository public so we can access it.

**Comment by lunny** [comment]
Did you? The arrows on the conversation have been removed.

**Comment by browcio** [comment]
Strange. I really believe that I confirmed that before posting. Nevertheless we found similar issue in 1.12.3 but I cannot reproduce it on 1.13-dev so we will wait.

Thank you.
