### ISSUE TITLE
The Launch (with SQLite3) config for vscode can't start

### ISSUE THREAD

**Issue by a1012112796** [go-gitea/gitea#11021]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

Hello, I use Launch file in ``contrib\ide\vscode`` to test run with  SQLite3, but It can't start and have error output. but I don't know the reason , So write this issue to find help. Thanks

<img width="953" alt="jf" src="https://user-images.githubusercontent.com/25342410/78872117-58f15b00-7a7b-11ea-883d-15208bae349c.png">

<img width="343" alt="jf" src="https://user-images.githubusercontent.com/25342410/78872285-a40b6e00-7a7b-11ea-970c-4c69b7ff23a6.png">

**Comment by guillep2k** [comment]
I fight with that myself (although I don't use the `contrib` code). I'm not sure this would help, but try replacing the double quotes (`\"`) with single quotes (`'`) in `buildFlags`. For me, it works with _run_ but fails with _debug_; I need to change them quotes back and forth. 🙁

**Comment by a1012112796** [comment]
> I fight with that problem myself (although I don't use the `contrib` code). I'm not sure this would help, but try replacing the double quotes (`\"`) with single quotes (`'`) in `buildFlags`. For me, it works with _run_ but fails with _debug_; I need to change them quotes back and forth. 🙁

Hello, I have try your suggestion and then it can be use now, Thanks !
I think this issue can add label as ``kind/question``.
