### ISSUE TITLE
RFC: Single-User Mode

### ISSUE THREAD

**Issue by RealOrangeOne** [go-gitea/gitea#11028]
## Description

Personally, I run gitea with almost 0 intention of letting anyone else onto it. It's specifically for my own projects. It would be nice if the default user's repos were accessible through a slightly shorter url pattern

For example, this isn't really ideal:

`git.mylongdomain.com/mylonghandle/mylongusername.com`

What might be nicer is:

`git.mylongdomain.com/r/mylongusername.com`
`git.mylongdomain.com/mylongusername.com`

Coercing all repos to under that path could be quite handy (maybe leave orgs as-is?). I currently get around this by hosting cgit at the root with a [task](https://github.com/realorangeone/gitea-cgit-adapter/) to populate it based off public repos. Obviously you'd need some protections in place to prevent conflicting with existing URL patterns (static files, settings etc).

In theory this would be as simple as a URL redirect on the router, and updating the repo URLs when presenting them in the UI, I think.

I currently get around this by setting my user's username to `u`, but that makes most of the UI look kinda bad.

I realise this is a pretty niche thing, but i'm sure there are other's out there who might find this nice?

**Comment by spadino** [comment]
I'm searching for the same. +1

**Comment by spadino** [comment]
Btw, @RealOrangeOne, how to you use this task you coded? I also use cgit - by now, its root is on one organization, the one I want to let public - but I'm curious to test your approach.... ;)

**Comment by RealOrangeOne** [comment]
Offtopic, but script works by scraping the public API of the instance, and building a cgit repos list, and having cgit serve from that. [this](https://github.com/RealOrangeOne/infrastructure/blob/master/ansible/roles/docker/files/gitea/docker-compose.yml#L68) might be a slightly better example.

**Comment by guillep2k** [comment]
I think the easiest workaround would be creating an organization with name 'x' and transferring all repos to that organization.

**Comment by RealOrangeOne** [comment]
That would also work, and is actually far nicer than my current approach, but still a bit of a bodge

**Comment by guillep2k** [comment]
Also:
```
git.mylongdomain.com/mylonghandle/mylongusername.com
```
should be
```
git.mylongdomain.com/mylonghandle/mylongrepositoryname
```
Why `longusername` and why `.com`?

**Comment by RealOrangeOne** [comment]
> Why longusername and why .com?

Typo. My point still stands though, the URLs aren't the nicest.

**Comment by severinkaderli** [comment]
I'm also looking for something like this. I'm using Gitea only for myself and shorter URLs would be a nice thing to have.

**Comment by myitcv** [comment]
For anyone else arriving at this issue, I had the same requirement and have solved it using a reverse proxy (nginx in my case) in front of my `gitea` instance. My setup looks roughly like this:

```
http {
  server {
    listen              443 ssl;
    server_name         my.domain;

    ssl_certificate     /ssl/cert.pem;
    ssl_certificate_key /ssl/key.pem;
    location / {
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_ssl_server_name on;
      proxy_set_header X-Forwarded-Host $host:$server_port;
      proxy_set_header X-Forwarded-Server $host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_pass http://gitea:3000/x/;
    }
  }

  server {
    listen              443 ssl;
    server_name         api.my.domain;

    ssl_certificate     /ssl/cert.pem;
    ssl_certificate_key /ssl/key.pem;
    location / {
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_ssl_server_name on;
      proxy_set_header X-Forwarded-Host $host:$server_port;
      proxy_set_header X-Forwarded-Server $host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_pass http://gitea:3000/;
    }
  }
}
```

(I'm no nginx expert so it's entirely possible the above could be simplified).

Notice how with the server my.domain, all requests to location `/` get routed to http://gitea_3000/x/. I separated out api.my.domain in order that API traffic is directed at http://gitea:3000/

**Comment by spadino** [comment]
Pretty clever, thanks!

**Comment by stfnx** [comment]
I am looking for the same feature.

This could be a setting in `app.ini` to run Gitea in "single user mode".
Then all repositories are available via `domain.tld/repo`.

The only thing to check is if there are any organisations named `repo` so that it doesn't collide.
But in real world I guess this shouldn't happen too often?

PS: Am I right that the nginx proxy would only work for HTTP, but not for SSH?

**Comment by m455** [comment]
> This could be a setting in app.ini to run Gitea in "single user mode".
> Then all repositories are available via domain.tld/repo.

I would absolutely love this feature. It's similar to how cgit or gitweb is. I would love a single user mode :D

I wonder if you could somehow check if `domain.tld/repo.git` works if someone tried to navigate to `domain.tld/repo`, that way it could check if it's a repo, user, or org. I don't know much about this though haha.

**Comment by tarasis** [comment]
I would also echo call for single user mode. My "fix" for the moment was redirecting /user/sign_up after I created my account. 

I don't mind having a long url domain/user/repo, I just want an easy way to prevent others from signing up like a setting that just disables the signup page.

**Comment by RealOrangeOne** [comment]
> like a setting that just disables the signup page

There's already a `DISABLE_REGISTRATION` setting, see https://docs.gitea.io/en-us/config-cheat-sheet/.

This is something different.

**Comment by techknowlogick** [comment]
As a lot of the system (including routes) is tied to the concept of multiple users/orgs, changing it to even allow this would be a rather significant change/undertaking. As such, I will close this issue. If someone would like to create a PR for it we would be more than happy to review it.
