### ISSUE TITLE
Reverting a reaction gives no feedback

### ISSUE THREAD

**Issue by septatrix** [go-gitea/gitea#11036]
- Gitea version (or commit ref): 1.12.0+dev-127-gd21b974f6
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL): https://try.gitea.io/Septatrix/HelloTea/issues/3
  - [ ] No
  - [ ] Not relevant
- Browser: Chromium 80.0.3987.163

## Description
When adding an emoji reaction to an issue it gets added instantaneously. Reverting said reaction however yields no visible feedback. After clicking on the icon nothing happens until one refreshes the website.
I only noticed that it had an effect because I was double checking before creating an issue about there being no way to retract a reaction.

**Comment by mrsdizzie** [comment]
I saw this bug when working on reactions recently, it seems to be limited to removing the last reaction -- so if you have five reactions and try to remove them all one by one it will give instant feedback for the first 4 you click but not be able to remove the final one.

Will look into after #11032
