### ISSUE TITLE
Question: Don't know how to configure "Status Check"

### ISSUE THREAD

**Issue by bill828** [go-gitea/gitea#11035]
- Gitea version (or commit ref): 1.10.1
- Git version: 2.23.0
- Operating system: CentOS 7
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description
I want to make a branch with "Status Check", so I enabled the checkbox "Enable Status Check" in Branch Protection page. But I couldn't configure check rules in this page.

My question is that how can I configure the rules? For examples, blocking merging while the Jenkins pipeline runs into an error.

The attached screenshot shows that I can't configure the rules.

## Screenshots

![截屏2020-04-10 下午1 19 25](https://user-images.githubusercontent.com/37794754/78964849-ea210a00-7b2d-11ea-8ff4-c28c0bf726d6.png)

**Comment by lunny** [comment]
@bill828 You could only configure it after the first status check sent to gitea.

**Comment by bill828** [comment]
@lunny Thank you for your reply. Is there any API document for sending status check to gitea?

**Comment by lunny** [comment]
It's similiar as github's, you can also see https://gitea.com/api/swagger#/repository/repoCreateStatus or the same pathh on your gitea instance .

**Comment by bill828** [comment]
@lunny Thank you . I know how to set commit status now.

Answer provided, closed this issue.
