### ISSUE TITLE
Repository Mirror - Code not showed

### ISSUE THREAD

**Issue by matteocostantini** [go-gitea/gitea#11044]
- Gitea version (or commit ref): 1.11.4
- Git version: 2.26
- Operating system: Ubuntu LTS 18.04.3
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
Hi, i had convert a normal unitialized repository to mirror repository.  i digit "git log" command in my-converted-bare-repo dir and i check all commits from mirrored are present! It's fine, but in gitea code page is empty. why ?

**Comment by a1012112796** [comment]
Hello, first I found the gitea version you have writen is 1.14 , I promise we haven't it now :(,
Then sugget you to provide more message like screenshoot, error log , if you found , and so 
on , which will be usefull for mainters to  help you. Thanks

**Comment by guillep2k** [comment]
Yeah, I've seen this "Gitea version 1.14" several times. Maybe they mean `1.11.4`?

@matteocostantini Gitea version is at the bottom left of each page (unless you've changed the template). For example:

![image](https://user-images.githubusercontent.com/18600385/79054393-c7205400-7c1a-11ea-9f76-0fbb67143e0b.png)

In this example, the version would be `1.11.4`.

**Comment by techknowlogick** [comment]
@guillep2k it could be they are using a nightly build which is compiled with golang 1.14 (and that version number is also reported in the config page)

**Comment by matteocostantini** [comment]
i'm sorry!!!! i'm working in another project with 1.14 release !! It's mistake!!!
I'm using 1.11.4 Gitea downloaded in site .

**Comment by matteocostantini** [comment]
the field repositories.is_empty = 1!!
