### ISSUE TITLE
[BUG] Reviews not corect sorted to pulls in Pull-List-View

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#11056]
Gitea Version: 1.12.0+dev-72-g2c25e75dc

example pull https://gitea.com/gitnex/GitNex/pulls/398
has 1 aprofal and 1 rejection on pull-list-view but rejection was aproved later from same user

**Comment by 6543** [comment]
![Screenshot at 2020-04-13 04-27-10](https://user-images.githubusercontent.com/24977596/79087310-1f507680-7d3f-11ea-8b00-449bcd844112.png)
## does not match with
![Screenshot at 2020-04-13 04-27-22](https://user-images.githubusercontent.com/24977596/79087312-224b6700-7d3f-11ea-903d-19c20b19a925.png)

**Comment by 6543** [comment]
same thing if you only aprove ... I guess: approvals are als counted as change-requests - didn't looket ito the code jet

**Comment by 6543** [comment]
cant reproduce on current master - looks like the pull for review-request fixed this

**Comment by 6543** [comment]
Looks like issue is till here :/

**Comment by 6543** [comment]
as "eider" pointed out on discord:
 https://github.com/go-gitea/gitea/blob/80db44267ccb688c596e8375523af5cd92864d87/models/issue_list.go#L538
```
if i force search to give me only one PR
the count is fine
but if in list there's at least one other issue
with requested change
the count goes to wrong issue
the "1 change request"
should go to other issue in list
but it isnt there!
```

**Comment by CirnoT** [comment]
https://try.gitea.io/test_org21/test_repo/pulls
https://try.gitea.io/test_org21/test_repo/pulls?q=LICENSE
https://try.gitea.io/test_org21/test_repo/pulls?q=README.md
https://try.gitea.io/test_org21/test_repo/pulls?q=.gitignore

**Comment by 6543** [comment]
I'll take this
