### ISSUE TITLE
Unknown issue indexer type: elasticsearch

### ISSUE THREAD

**Issue by micheelengronne** [go-gitea/gitea#11059]
- Gitea version (or commit ref): 1.11.4
- Git version: 2.20.1
- Operating system: Ubuntu
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

```
2020/04/13 10:44:32 ...er/issues/indexer.go:142:func2() [I] PID 12: Initializing Issue Indexer: elasticsearch
2020/04/13 10:44:32 ...er/issues/indexer.go:168:func2() [F] Unknown issue indexer type: elasticsearch
```

## Description
I have `Unknown issue indexer type: elasticsearch` when I set `ISSUE_INDEXER_TYPE = elasticsearch` in my `app.ini`.

**Comment by guillep2k** [comment]
Elasticsearch was added in #9428 for the upcoming 1.12.0 release. It's not supported as of 1.11.4.
