### ISSUE TITLE
[UI] [Imprufement] Make Issue & Pull different view on Milestone list

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#11069]
Gitea Version: master

It's hard to see if it's a pull or an issue on milestone since there are both we should make them look different - at leas in a way to distinguish them

**Comment by mmarif4u** [comment]
Adding screenshot for better illustration.

#380 is PR in this example.
![Screenshot_20200415_005605](https://user-images.githubusercontent.com/1280585/79268331-0f0dd800-7eb4-11ea-8d3a-06fc95e5e173.png)

Suggestion: Add icons in front for PR and issue.

**Comment by 6543** [comment]
ping

**Comment by 6543** [comment]
-> #12499
