### ISSUE TITLE
FUll name in issue/PR pages

### ISSUE THREAD

**Issue by maieul** [go-gitea/gitea#11079]
- Gitea version (or commit ref):
 1.12.0+dev-153-g70fab7e26 
- Git version: try.gitea.net
- Operating system:try.gitea.net
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [X ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
In pulle request and issue pages and lists, the user name is printed instead of full, while the full name is printed in the repository page.

Example
https://try.gitea.io/Maieul/test/ (full Name)
https://try.gitea.io/Maieul/test/issues (User Name)
https://try.gitea.io/Maieul/test/issues/1 (idem)
https://try.gitea.io/Maieul/test/pulls (idem)
https://try.gitea.io/Maieul/test/pulls/1 (idem)

My user name is "Maieul" while my full name is "Maïeul Rouquette".

The main probblem is inconstitency.

...

## Screenshots

![image](https://user-images.githubusercontent.com/636640/79366704-f30a4500-7f4c-11ea-8f7b-8a483adabbfd.png)

![image](https://user-images.githubusercontent.com/636640/79366771-0d442300-7f4d-11ea-838e-603c4bfbd47f.png)
![image](https://user-images.githubusercontent.com/636640/79366818-1e8d2f80-7f4d-11ea-8c56-8014f8f82c5b.png)
![image](https://user-images.githubusercontent.com/636640/79366856-2cdb4b80-7f4d-11ea-9dc8-1279dec6e74f.png)
![image](https://user-images.githubusercontent.com/636640/79366889-3a90d100-7f4d-11ea-8788-88a6ca3746bf.png)

**Comment by a1012112796** [comment]
I think all name on UI should use  ``user.GetDisplayName`` to get .

**Comment by guillep2k** [comment]
@a1012112796 Maybe there are some places where we need the name to remain compact? But mostly yes, `GetDisplayName()` should be used when possible. 👍
