### ISSUE TITLE
Failing to use pm2 deploy feature with Gitea

### ISSUE THREAD

**Issue by gbidkar** [go-gitea/gitea#11076]
- Gitea version (or commit ref): 1.10.3
- Git version: 2.26.0
- Operating system: Ubuntu 16.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist: There are no relevant logs from that event (no errors are being logged)

## Description

Hey there folks. I'm trying to use pm2's (a nodejs production process manager) deploy feature and I've seemed to run into an issue with gitea. I have the following configuration for the server:
```javascript
deploy : {
    production : {
      key  : '<key>',
      user : 'git',
      host : [{host: '<hostname>', port: '<port>'}],
      ref  : 'origin/master',

      repo : 'git@<hostname>:<port>/guy/<reponame>.git',
      // I tried all these but non worked.
      //path : '/var/www/production',
      //path: "/",
      //path: "<actual repo's path>" 
      'post-deploy' : 'npm install && pm2 startOrRestart ecosystem.config.js --env production'
    }
  }
```

What showed up as response from PM2 was:
```
--> Deploying to production environment
--> on host <host>
  ○ hook pre-setup
Gitea: Unknown git command
Unknown git command mkdir

  setup paths failed

Deploy failed
1
```

After some snooping around, I saw that there are [certain git commands which are available in Gitea](https://github.com/go-gitea/gitea/blob/master/cmd/serv.go#L71-L76) and I was wondering if that's related to what I'm trying to do and if Gitea actually supports what I'm trying to do.

**Comment by silverwind** [comment]
I guess it'is not properly detecting the repo URL as such and falling back to some local action, maybe try prefixing it with `git://` or `https://` URL.

**Comment by gbidkar** [comment]
@silverwind - not working sadly, I think maybe PM2 is trying to execute something on Gitea's side which Gitea doesn't allow?

**Comment by silverwind** [comment]
No idea, sorry. `mkdir` is certainly not a valid git command. I guess you should dig into pm2 source to really see what it's doing or ask there.

**Comment by zeripath** [comment]
pm2 appears to be trying to put hooks on the gitea server directly! We don't support that and won't support that - GitHub, bitbucket and Gitlab would not allow this either.

Why is it trying to add hooks like this?
