### ISSUE TITLE
[BUG] [UI] review submit box is cut off

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#11075]
Gitea Version: 1.12.0+dev-142-g9b7737df2

![png](https://cdn.discordapp.com/attachments/323701541297192961/699642561438154752/Screenshot_20200414_201411.png)

**Comment by silverwind** [comment]
Another issue with that box I noticed that small diffs (1 line), it will interfere with the page footer and extend below it. I think a proper fix is to use [popper](https://github.com/popperjs/popper-core) to position the box.

**Comment by 6543** [comment]
Closed by  #11252
