### ISSUE TITLE
maybe we can extend pull request workflow

### ISSUE THREAD

**Issue by a1012112796** [go-gitea/gitea#11078]
Hello, Now we have copyed fork - pull - commit - push - pull Request workflows from github, and also copyed some limit about this workflow from github.maybe we can do some extends now.

1, I think we can use "copy" instead of "fork" , which means user can choose which branch they like to copy,   set the target repo name instead of only copy source repo name, and I also don't think copyed repo should have any  relation  with source repo after cpoy event finished.

2. I also don't think it's necessary to only allow make Pull Request from same repo, and forked repo. maybe we can allow users to make Pull Request from any branch in any repo to any other repo's branches which only should make sure they have same parent object. maybe we can even cross platform boundaries, like make pull requset from a branch on github to our platform. but maybe we should start update event by hand or by weebhook when the head branch was changed.  
As we all know, git don't support brach level read permission limit, which can see #10571, but that not mean we have no ways. I think we can do it by repos level read permission limt, like if we want do some security work or custom work for a public repo, we can copy it and set copyed repo as private, then do works on it. If it's work result can become to a part of public repo, we can make pull request from it to public repo...
3. maybe we should allow user who only have read permission to add branches in repo and continue commit or make pull request base on it if manager of repo allow.  so contributors can do small works without copy or fork repo . I learned this feature from gitee, https://gitee.com/help/articles/4291#article-header0, I'm sorry, but I haven't found english version of this message.

I know these thoughts are not enough mature and maybe a little crazy. but I realy have a dream about it.

**Comment by guillep2k** [comment]
Why did you close this? Have you changed your mind? 🤔

**Comment by a1012112796** [comment]
> Why did you close this? Have you changed your mind? 🤔

Beacuse It's only a amazing dream  ... 😉
