### ISSUE TITLE
Default MySQL to utf8mb4

### ISSUE THREAD

**Issue by silverwind** [go-gitea/gitea#11081]
https://github.com/go-gitea/gitea/pull/11032 will output unicode emoji from tokens and attempting to save such a emoji into a `utf8` table will result in error 500:

```
CreateIssueComment: Error 1366: Incorrect string value: '\xF0\x9F\x91\x8E' for column 'content' at row 1
```

I think we should:

1. default new installs to `utf8mb4`
2. mention in the release notes that MySQL users are encouraged to update their config to `utf8mb4` and then run `gitea convert` to upgrade the database.

**Comment by lafriks** [comment]
I think we already default on new installs

**Comment by silverwind** [comment]
Do we? I'm not quite sure what this does:

https://github.com/go-gitea/gitea/blob/master/modules/setting/database.go#L81

and example ini suggests it's still `utf8`:

https://github.com/go-gitea/gitea/blob/master/custom/conf/app.example.ini#L378-L380

**Comment by mrsdizzie** [comment]
I think we 'default' it by having it be the value here:

 https://github.com/go-gitea/gitea/blob/1fb783efb0dbb3cb866f37ee6b77a003b636de59/templates/install.tmpl#L76-L77

As usual sample ini file is just out of date because it wasn't updated with the commit that changed the lines above

**Comment by silverwind** [comment]
What does that install form actually do? Just write into `app.ini`?

**Comment by mrsdizzie** [comment]
It writes the settings from the form, sets install lock,  and then calls https://github.com/go-gitea/gitea/blob/1fb783efb0dbb3cb866f37ee6b77a003b636de59/routers/init.go#L113 Which will set up tables with whatever charset is chosen.

**Comment by silverwind** [comment]
I see, so `routers/install.go` writes the config, making this issue just a matter of updating the example ini.

**Comment by nampdn** [comment]
Hello, is this fix release on Docker image?

**Comment by zeripath** [comment]
Yes. This has been the default on master for 3 months and is the default in 1.12.

If you have an old MySQL database that needs converting use: `gitea convert` to convert it.
