### ISSUE TITLE
suggest allow custom default merge message template

### ISSUE THREAD

**Issue by a1012112796** [go-gitea/gitea#11089]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

Hello, I think it's usefull , if user can define merge message template, maybe we can allow user to do it by define ``.gitea/MERGE_MESSAGE_{merge_style}_TEMPLATE.md`` file in base branch. which is Similar to issue and pr template. thanks.

**Comment by zeripath** [comment]
I think this is still valid

**Comment by zeripath** [comment]
A relatively simple first solution would be to just provide per-instance templates - these could actually use gotemplates and have the models.Issue etc. passed in.

Per-repository templates would need to go into the .gitea/ folder on the $master branch using code from the issue templates and template repositories code. If we use gotemplates for this we cannot just pass in the models.Issue etc as it would not be too difficult to use methods on the Issue to then change the User etc. Therefore some kind of defined variable replacement would be needed - Again similar to that used in issue/repository templates.
