### ISSUE TITLE
Gather suggestions for gitea-vet

### ISSUE THREAD

**Issue by jolheiser** [go-gitea/gitea#11097]
Now that we implemented a custom [vet tool](https://gitea.com/jolheiser/gitea-vet) I'd like to open an issue to gather ideas on things to add to it.

For reference, I took the inspiration from a [mattermost blog post](https://mattermost.com/blog/maintaining-consistency-in-codebases-with-go-vet/) about how they use [their vet tool](https://github.com/mattermost/mattermost-govet).

As an example, currently the tool checks for [license headers in files](https://github.com/go-gitea/gitea/blob/9ffa89249e707d2f977a6fb11a1b56a527fa2640/main.go#L1-L4) and [import ordering](https://github.com/go-gitea/gitea/blob/9ffa89249e707d2f977a6fb11a1b56a527fa2640/main.go#L10-L24).

**Comment by 6543** [comment]
Check If we have xorm Insert statements witch could posibly add nil slices

**Comment by 6543** [comment]
in models: unexpoted function should always use e Engine and never x so just check if there is a
`*= x.*` in a func

**Comment by 6543** [comment]
If a exported function has Init a new Session from this line on only dont allow usage of x either

**Comment by 6543** [comment]
common xorm bugs ☝️

**Comment by lunny** [comment]
That is, in a function under `models`, when the first param is `e Engine`, then it and all invoked functions should not have a reference to `x`.

**Comment by jolheiser** [comment]
The above have been moved to the [gitea-vet repo](https://gitea.com/gitea/gitea-vet), so I will close this issue. More issues there are welcome. 🙂
