### ISSUE TITLE
Pull request is broken

### ISSUE THREAD

**Issue by kraszied** [go-gitea/gitea#11105]
- Gitea version (or commit ref): 1.11.4
- Git version: 2.24.0
- Operating system: Windows 10
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description

If a pull request (PR) is created and then a new commit is pushed to the source (head) branch the PR became broken. The newly pushed commit doesn’t appear in the PR and head branch appears as "deleted". The branch protection is set to the destination branch. In this repository all created PRs behave the same independently which are the source and destination branches. In our other repository this error never comes. This situation prevents us to fulfill an effective code review, because we need to open a new PR after every newly pushed commit related to the review.

Here is a link to my ticket on our forum: https://discourse.gitea.io/t/pull-request-is-broken/2092

**Comment by filipnavara** [comment]
Check that the git hooks are executing properly. This exact problem was happening on our installation and that was the root cause.

**Comment by kraszied** [comment]
@filipnavara thank you for your info! Actually we don't have any git hooks but updating the Gitea version and regeneration of SSH keys (Update the '.ssh/authorized_keys' file with Gitea SSH keys. (Not needed for the built-in SSH server.) on dashboard) are solved our problem.

**Comment by filipnavara** [comment]
Gitea relies on git hooks that are installed in the repositories. If they are not present then it will break in this exact way. When you create the repository in Gitea these hooks are automatically installed but someone might have broken them during some maintenance operation.
