### ISSUE TITLE
Browser and Instance freezes on long issue code comment

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#11103]
- Gitea version (or commit ref): 1.11.3 and 1.12.0+dev-8-g3378fc914
- Git version: 2.26.0 and 2.24.1
- Operating system: Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No https://try.gitea.io/testdsfdsfdsfsdf/sdf/issues/1
  - [ ] Not relevant

## Description

Commenting the output of [`pwgen 4096`](https://8-p.info/pwgen/) in a multi-line code block slows down the instance and "slows down your browser".
Opening the `...` menu to delete the comment is not possible anymore, forcing comment deletion via API or DB

**Comment by silverwind** [comment]
This should be fixed as of https://github.com/go-gitea/gitea/commit/27e3cddfbef533f783898800ac4abdd5a453b436.
