### ISSUE TITLE
No LISTEN when activating HTTPS

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#11101]
- Gitea version (or commit ref): 1.11.4
- Git version: 2.26.1
- Operating system: Arch Linux (Linux 5.6.3.a-1-hardened #1 SMP PREEMPT Wed, 08 Apr 2020 16:39:52 +0000 x86_64 GNU/Linux)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist: https://gist.github.com/grrk-bzzt/1b50425c4d3e9793f8ae091a5cacdaa6

## Description

Hello,

I've updated a working Gitea setup listening over HTTPS, which stopped working after a reboot.

Not being able to fix my setup, I've decided to start again from scratch.

Setting up Gitea on HTTP works normally, but switching to HTTPS doesn't.

Running the command `lsof -i -P -n | grep LISTEN ` returns nothing, while the Gitea logs doesn't output any error at all (se the log gist).

**Comment by guillep2k** [comment]
Is it possible you're using selinux and/or you need to enable the new executable to open the 443 port? (e.g. port labeling). If it's port labeling, it must be re-enabled every time the file contents change (e.g. upgrade).
