### ISSUE TITLE
Can we integrate Agile Scrum Board and Kanban Board?

### ISSUE THREAD

**Issue by raghulraj-sourcetopper** [go-gitea/gitea#11104]
## Description
Issues tracker can we use scrum board?

**Comment by lunny** [comment]
I think we have already an issue related as this one.

**Comment by roberChen** [comment]
There is a pull request which aims to integrate a kanban board into gitea, see #8346

**Comment by adelowo** [comment]
@lunny https://github.com/go-gitea/gitea/issues/3476 . The PR at #8346 is almost done. Just 2 UI fixes and lint fix. should be go to go

**Comment by adelowo** [comment]
You can close this one
