### ISSUE TITLE
API Generalize Header for get XY list endpoints

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#11114]
as title, if an api endpoint returns a list of objects it should:  
A: support paggination (optional)  
B: add max-obj-count to header  

* [ ] add this to API programming guidelinge
* [ ] create header for all get list endpints

* `ctx.Header().Set("X-Total-Count", fmt.Sprintf("%d", maxResults))`

**Comment by zeripath** [comment]
I would be cautious about assuming that we should always provide a full count - that can be very expensive in certain circumstances - (mostly circumstances that we've already committed to providing a count.)

**Comment by 6543** [comment]
good point ...

**Comment by 6543** [comment]
... maybe it's better to add a help function named as ``ctx.SetResultHeader(...)`` to do it.

_Originally posted by @a1012112796 in https://github.com/go-gitea/gitea/pull/16300#discussion_r662846010_
