### ISSUE TITLE
[BUG] Markdown: Inline <img .../> does nor work

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#11116]
Gitea Version: 1.12.0+dev-142-g9b7737df2

repo witch is affected: https://gitea.com/gitnex/GitNex/src/branch/master/README.md#user-content-downloads

**Comment by silverwind** [comment]
Images do appear to work for me in that link, both under Downloads and Screenshots.

**Comment by 6543** [comment]
@silverwind I noticed this with:
`[<img alt='Download APK' src='https://gitnex.com/img/download-apk.png' height="80"/>](https://gitea.com/gitnex/GitNex/releases)` look at the link above

**Comment by 6543** [comment]
@silverwind never mind sory for taking your time - I should sometimes check my uMatrix more often :/
