### ISSUE TITLE
[Idea] Web IDE using theia

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [go-gitea/gitea#11119]
Since Theia IDE 1.0 was launched I thought it might be an opportunity for a new gitea feature. 

### What is [Theia](https://github.com/eclipse-theia/theia)

> Eclipse Theia is an extensible platform to develop full-fledged multi-language Cloud & Desktop IDE-like products with state-of-the-art web technologies.

It is basically a self hosted vscode (it looks like vsocde and can use vscode extensions) and comes with it's own docker container. 

I think using this would be a better experience than gitlab's web IDE in terms of both UI and functionality.

I am unsure of how much work would be required for this but I would love to hear what people think about this idea

**Comment by lunny** [comment]
- [ ] Open a IDE on one repository with special branch(default will open default branch). (readonly mode / write mode for different permissions). Did theia support read-only mode? Maybe a read-only mode is a first step. The IDE link entry could be in repository or in branch list, the link will be a new window.
- [ ] Load repository treepath from git on the IDE.(Asynchronize load the sub tree)
- [ ] When open a file on the IDE tree, extract the file from git.
- [ ] When save/delete a file, submit a change to git. 
- [ ] Git integration. We should display the git blame on the IDE.

**Comment by roberChen** [comment]
How about the extensions support?

**Comment by sh7dm** [comment]
@lunny I experimented with Theia before, for the last (git integration) you can install GitLens VS Code extension, it's compatible, at least 70% of its main fuctions work. The most problem is security, as Theia exposes console.

**Comment by lunny** [comment]
> @lunny I experimented with Theia before, for the last (git integration) you can install GitLens VS Code extension, it's compatible, at least 70% of its main fuctions work. The most problem is security, as Theia exposes console.

Yes, some feature should be disable. Is theia a npm package?

**Comment by lunny** [comment]
> What about the extensions support?

extensions should be supported as well.

**Comment by sh7dm** [comment]
@lunny it's a set of npm packages. To create an IDE out of core, Theia extensions and VS Code ones, you need to create a `package.json` as in examples of Theia apps, define extensions and plugins there and build using their CLI. VS Code extensions can be loaded later using builtin Open-VSX registry. Security is bigger problem than you thought, there're a lot of functions relying on terminal. Probably it won't be safe to use without Docker.

**Comment by lunny** [comment]
Every user/repository branch will have one docker and it's difficult to know if it should be destroyed.

**Comment by roberChen** [comment]
I think it's better to regard theia as an editor rather than a full featured IDE, or allow gitea to integrate theia just like how it does with drone CI.

**Comment by sh7dm** [comment]
For "editor" you don't need Theia as far as I know, you need [Monaco editor](https://github.com/microsoft/monaco-editor), which is main editor of Theia.

**Comment by roberChen** [comment]
Maybe it's better to integrate Monaco editor with gitea for users who runs gitea on a Raspberry pi, I think...

**Comment by lunny** [comment]
I think that's different. `Monaco editor` could help to edit single file but theia will help to change the whole branch then you can send PR online.

**Comment by UnlimitedCookies** [comment]
Maybe there could be something similar to how [Gitpod ](https://gitpod.io/#https://github.com/eclipse-theia/theia)handles the Theia instances. It only allows for a  limited number of containers per user (this should be pre-configurable) and automatically shuts down containers when they are not being used. I think it also pre-compiles some parts to make it faster for a dev to get started.

And of course this entire online IDE should be something entirely optional so the people hosting on a Raspberry Pi don't have to worry :)

**Comment by HKMV** [comment]
Will there be in the future?

**Comment by lunny** [comment]
Reviewed again all my thought before, I changed my idea. I don't think we should embed a WebIDE into Gitea.

**Comment by techknowlogick** [comment]
Gitpod has a PR that is adding Gitea support, and I believe other web IDEs are adding the same. So I think this should be closed (at least for now).

**Comment by thomas-mc-work** [comment]
Follow up:

- https://github.com/gitpod-io/gitpod/issues/80
- https://github.com/gitpod-io/gitpod/pull/8131

**Comment by darkguy2008** [comment]
Gitpod is cool but I just came here due to a google search looking for a way to have something more alike to GitLab's Web IDE feature. A way to browse repos with an IDE-like interface, if you will. I don't think it has to be a full-fledged IDE in the sense of allowing to compile/run/etc. but just browsing would be great.

**Comment by lunny** [comment]
I currently don't think it's necessary to embed a web editor into Gitea. But we can have a better integration with other web editors/local editors. I think #22378 will be a first step to do that.
