### ISSUE TITLE
Dark theme rework

### ISSUE THREAD

**Issue by silverwind** [go-gitea/gitea#11118]
List of things I plan to do:

- Remove `THEMES` option to allow us to easily introduce new themes. This currently acts as a whitelist so new themes can currently not be introduced without a config change and I don't really see a valid reason why admin would want to disable certain themes (theme is a user's choice, not admin's).
- Figure out webpack multi-stage webpack build where theme generation can run after `public` files have been written (essentially running webpack twice).
- Resolve https://github.com/silverwind/remap-css/issues/3 for easy remapping of monochrome colors.
- Auto-generate `arc-green` using `remap-css`.
- Possibly add new `gitea-dark` theme.

**Comment by silverwind** [comment]
Not stale

**Comment by silverwind** [comment]
I'm thinking it may be time to put `arc-green` to the grave once we have the "proper" dark theme and migrate users to that new theme.

**Comment by silverwind** [comment]
https://github.com/go-gitea/gitea/pull/12448

**Comment by yardenshoham** [comment]
@silverwind is this completed?

**Comment by silverwind** [comment]
No, but I guess part of this stuff is now out of date, so I'll close it. I still would like to make a "darker" dark theme at some point, which should now be very easy since all colors are in variables.
