### ISSUE TITLE
Repo order improvement

### ISSUE THREAD

**Issue by axeloz** [go-gitea/gitea#1112]
- Gitea version (or commit ref): 1.0.0+373-gd76d67d
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite

## Description

The repository order feature works fine but I find it a little bit confusing. By default, the order is made on "Most recent" which means "Most recently **created**". But in the repository listing, there is only the last modification date which doesn't match the order.
A tiny improvement would be to add a label like so:

```
Created: 2 month ago - Updated : 2 days ago
```
I think I would be more understandable. 

## Screenshots

<img width="553" alt="explorer_-_w_git_hosting" src="https://cloud.githubusercontent.com/assets/1597611/23559287/c6fb24e0-0036-11e7-92a3-8dac13fcf209.png">

**Comment by yp05327** [comment]
Maybe we can close this issue. We have obvious sort types now.
![image](https://user-images.githubusercontent.com/18380374/235064376-e0ed9fa5-9533-4ff3-acf2-f58edc474d4b.png)
