### ISSUE TITLE
Large repo migration failed

### ISSUE THREAD

**Issue by finzzz** [go-gitea/gitea#11121]
- Gitea version (or commit ref): 1.12
- Git version: 2.24.1
- Operating system: Ubuntu 18.04
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description
always get "Connection closed by 10.10.10.3 port 40246 [preauth]" when migration almost finished.
...

**Comment by guillep2k** [comment]
Could you please post some relevant logs from Gitea? Also, where are you migrating from?

**Comment by finzzz** [comment]
nope, because I recreated the container using sqlite instead. In sqlite, it also failed several times but it eventually works. Not sure what caused it, maybe I changed postgres version to 12 if that makes any difference.

Here is the repo https://github.com/danielmiessler/SecLists

**Comment by zeripath** [comment]
This is likely a timeout issue: https://docs.gitea.io/en-us/config-cheat-sheet/#git-timeout-settings-git-timeout

In particular the MIGRATE setting.

@finzzz without logs and without a way to definitively reproduce I'm not sure we will be able to move this issue further forward.

**Comment by zeripath** [comment]
I'm closing this issue as no further action has been taken since June.
