### ISSUE TITLE
email activation (of non primary addresses) broken

### ISSUE THREAD

**Issue by stbuehler** [go-gitea/gitea#11128]
- Gitea version (or commit ref): `1.11.4`
- Git version: `1:2.20.1-2+deb10u2`
- Operating system: `debian buster`
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No: doesn't seem to require email activation, added address already is activated
  - [ ] Not relevant
- Log gist: none

## Description

Clicking `Send Activation` on `/user/settings/accounts` doesn't trigger any mail, but doesn't show any error (just "reloads" the page).

The issue is in the template: https://github.com/go-gitea/gitea/blob/16f39ce42690a57b92d8a7f1c4317f079ee842c4/templates/user/settings/account.tmpl#L95

In the generated HTML page it will show `<input name="id" type="hidden" value="}.ID">`.

Log show:
```
gitea[25052]: [Macaron] 2020-04-19 10:04:29: Completed POST /user/settings/account/email 302 Found in 2.042836ms
gitea[25052]: 2020/04/19 10:04:29 ...r/setting/account.go:121:EmailPost() [E] Send activation: email not set for activation
```

Don't think this could have ever worked since #10557.

**Comment by zeripath** [comment]
Good catch. It's almost certainly because VSCode will helpfully occasionally add a third closing curly bracket when you type two curly brackets in a row. I spotted a second one and added that to the PR.
