### ISSUE TITLE
gitea will only bind on 0.0.0.0 and is not able to bind on 127.0.0.1 only

### ISSUE THREAD

**Issue by shakeyourbunny** [go-gitea/gitea#11142]
- Gitea version (or commit ref):  1.9.6
- Git version: 2.16.6
- Operating system: CentOS Linux release 7.7.1908 (Core)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL (MariaDB)
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:
2020/04/19 21:42:39 cmd/web.go:151:runWeb() [I] Listen: http://0.0.0.0:3000
2020/04/19 21:42:39 cmd/web.go:154:runWeb() [I] LFS server enabled
2020/04/19 21:42:39 ...ce/gracehttp/http.go:142:Serve() [I] Serving 0.0.0.0:3000 with pid 3281

## Description
My setup is that I'm running gitea behind a reverse nginx proxy which handles all the SSL traffic and gitea itself should only bind on localhost, which I could not accomplish it. Gitea itself is launched as a systemd unit.

I can access Gitea fine via HTTPS (nginx), but blocking port 3000 from external sources is IMHO not a real solution. So how can I enforce Gitea only to bind to localhost / 127.0.0.1?

I read the 
- https://docs.gitea.io/en-us/config-cheat-sheet/
- https://docs.gitea.io/en-us/specific-variables/ (Macaron environment variable HOST does not work, nor in app.ini)

**systemd unit file**
[Unit]
Description=Gitea - Git with a cup of tea. A self-hosted Git service.
Documentation=https://docs.gitea.io/
After=network-online.target
Wants=network-online.target systemd-networkd-wait-online.service

[Service]
Restart=on-abnormal
StartLimitInterval=10
StartLimitBurst=3

User=gitea
Group=gitea

WorkingDirectory=/home/gitea/gitea
Environment="HOST=127.0.0.1"
ExecStart=/home/gitea/gitea/bin/gitea web --config /home/gitea/gitea/etc/app.ini
ExecReload=/bin/kill -USR1 $MAINPID

LimitNOFILE=1048576
LimitNPROC=64

**nginx configuration**
server {
    listen       443 ssl http2;
    server_name   example.com;
    server_tokens off;

    access_log /var/log/nginx/example.com-access.log main;

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }

    location ~ /\.ht {
        deny  all;
    }

    # ssl configuration
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_dhparam /etc/nginx/dhparam.pem; 
    ssl_ciphers EECDH+AESGCM:EDH+AESGCM;
    ssl_ecdh_curve secp384r1; # Requires nginx >= 1.1.0
    ssl_session_timeout  10m;
    ssl_session_cache shared:SSL:10m;
    ssl_session_tickets off; # Requires nginx >= 1.5.9
    ssl_stapling_verify off; # Requires nginx => 1.3.7
    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains";
    add_header X-Frame-Options DENY;
    add_header X-Content-Type-Options nosniff;
    add_header X-XSS-Protection "1; mode=block";

    ssl_certificate             /etc/letsencrypt/live/example.com/fullchain.pem;
    ssl_certificate_key         /etc/letsencrypt/live/example.com/privkey.pem;

    location / {
        proxy_pass              http://127.0.0.1:3000;
        proxy_http_version      1.1;
        proxy_set_header        X-Forwarded-Host $server_name:$server_port;

        proxy_hide_header       Referer;
        proxy_set_header        Referer '';
        proxy_hide_header       Origin;
        proxy_set_header        Origin '';
    }
}

**gitea app.ini**
[server]
APP_DATA_PATH    = /home/gitea/gitea/data/gitea
HOST             = 127.0.0.1
HTTP_PORT        = 3000
ROOT_URL         = https://example.com/
DISABLE_SSH      = true
START_SSH_SERVER = false
LFS_START_SERVER = true
LFS_CONTENT_PATH = /home/gitea/gitea/data/git/lfs
LFS_JWT_SECRET   = ********
DOMAIN           = example.com
OFFLINE_MODE     = true
ALLOW_GRACEFUL_RESTARTS         = true
GRACEFUL_HAMMER_TIME            = 60s
STATIC_CACHE_TIME               = 6h
LANDING_PAGE = login

Is something amiss or gitea just cannot bind itself not only to a specific interface?

**Comment by zeripath** [comment]
This should be `HTTP_ADDR = 127.0.0.1` not `HOST`

As per https://docs.gitea.io/en-us/config-cheat-sheet/#server-server
