### ISSUE TITLE
Commits avatar when email set to private, and misc.

### ISSUE THREAD

**Issue by Fastidious** [go-gitea/gitea#1115]
- Gitea version (or commit ref): `1.0.0+373-gd76d67d`
- Git version: `2.7.4`
- Operating system: `Ubuntu 16.04`
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description

If I commit, while having the email setting to keep it private, avatar will not show on commits (see https://gits.quark.business/David/collantes.us/commits/master). The one showing avatar is last commit, after unticking `Keep email address private.`

Also note the tick box on search, near `All`, it seems to be needing some padding.

## Screenshots

![screen shot 2017-03-04 at 18 11 57](https://cloud.githubusercontent.com/assets/8352292/23583019/199845be-0106-11e7-88f5-998b5ab77dca.png)

**Comment by Fastidious** [comment]
I think I figured out the avatar problem.

On `app.ini`, under `[service]` there is the `NO_REPLY_ADDRESS` setting. It is not an address what should be entered, but a not reply `domain`. I had `not-a-valid-address@quark.business` and that was causing my address to become `david@not-a-valid-address@quark.business` (saw this on the logs) which is terribly wrong. Changing `NO_REPLY_ADDRESS` to `not-a-valid-email.quark.business` fixed the problem. See screenshot:

![Shows the invalid email address](https://cloud.githubusercontent.com/assets/8352292/23583157/307d4654-010a-11e7-85ff-5ecba8a86b94.png)

The little UI glitch (tick box and `All` too close) remains.

**Comment by Fastidious** [comment]
@lunny bottom line, the setting `NO_REPLY_ADDRESS` has a misleading name. It is used to create the `private` address, but it isn't an email address what the value should be, but an invented `TLD`.

**Comment by lunny** [comment]
Yes. I see. It's a misleading name.

**Comment by Fastidious** [comment]
@lunny should I split this issue? The second part did not relate to the first, I should not have piggy bagged two completely different things into one. Let me know.

**Comment by lunny** [comment]
OK. Feel free to do that.

**Comment by mohammed90** [comment]
Isn't this a bug? When `Keep email address private` is checked, commits done via UI (file edits directly on Gitea and merging pull-requests) do not link to the user's profile. Doesn't Gitea know who the user is who committed or pushed the commit? It properly links to the user profile when the commits are directly pushed from local to Gitea.

**Comment by lafriks** [comment]
@Mohammed90 users are linked only through e-mail addresses.
