### ISSUE TITLE
Team problem

### ISSUE THREAD

**Issue by Sukaato** [go-gitea/gitea#11157]
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

I can't leave the team I created because it must have at least 1 member.
I cannot delete the team because there are users in it.
I cannot delete my account because I am in a team.

**Comment by jolheiser** [comment]
What version of Gitea is this?

That should only be true of the `owners` team, and the solution would be to delete the org or add someone else as an owner before removing yourself.
