### ISSUE TITLE
[Feature] Show long file names (when there's enough space)

### ISSUE THREAD

**Issue by UnlimitedCookies** [go-gitea/gitea#11151]
Hi! As you can see the file name is shortened for no apparent reason.
Clearly there's enough space available and I don't see a reason to shorten it. Imo many devs would benefit from not having to use the tooltip in order to see which file they have currently opened (probably among many other tabs).
When I have many nested folder it makes sense to shorten it of course.

![Long File Name Example](https://user-images.githubusercontent.com/49200216/79709557-c34b9c00-82c2-11ea-9875-7c2661b39b56.png)

Thanks for your contribution!

**Comment by zeripath** [comment]
Looking at this GH doesn't bother with breaking or truncating so I guess we don't need to either.

**Comment by UnlimitedCookies** [comment]
Repo to check Githubs behavior: https://github.com/cheecheeo/longfilenames 😄

**Comment by yp05327** [comment]
![image](https://github.com/user-attachments/assets/f53839b9-8917-471b-8b44-cee4c6a0dea0)
![image](https://github.com/user-attachments/assets/488e43ff-3c11-4c1e-afc7-d656b31a44cf)
I think this is fixed now.
