### ISSUE TITLE
Markdown parser should respect single newlines

### ISSUE THREAD

**Issue by silverwind** [go-gitea/gitea#11155]
Given markdown

```md
a
b
```

GitHub renders two lines because of `<br>`:

```html
<p>a<br>
b</p>
```

Gitea renders one line because `\n` is converted to ` ` according to HMTL whitespace rules:

```html
<p>a
b</p>
```

Might be a divergation from the spec in GFM, but it'd be more intuitive if we'd insert those `<br>` and trim the newline off the `<p>`. Alternatively, adding `white-space: pre` on the `<p>` in CSS would also work but may have more unintended side effects.

**Comment by zeripath** [comment]
@yuin what do you think about this? Is this an expected GFM diversion from the spec?

**Comment by silverwind** [comment]
Relevant section of GFM:

https://github.github.com/gfm/#soft-line-breaks

Specifically this seems to be in use:

> A renderer may also provide an option to render soft line breaks as hard line breaks.

**Comment by silverwind** [comment]
Goldmark already has [option `WithHardWraps`](https://github.com/yuin/goldmark#html-renderer-options) to cover it.

**Comment by silverwind** [comment]
Further investigation reveals we already have option `markdown.ENABLE_HARD_LINE_BREAK` that maps to `WithHardWraps` but it defaults to `false`. I think we should flip that default.

**Comment by zeripath** [comment]
ah yeah now I recall. I bet this was because of some blackfriday default. I suspect our unit tests expect not HardWraps.

**Comment by silverwind** [comment]
Will follow up with a PR that changes the default and improve the documentation around that option.

**Comment by a1012112796** [comment]
Hello, I don't think it's a wrong thing, Because in markdown usually format rulers, we should have more than two spaces after words, or mardwon won't regard it as a new line:
view:
<img width="254" alt="jm1" src="https://user-images.githubusercontent.com/25342410/79775056-3eb25980-8366-11ea-9237-ba7d32d709e7.png">
<img width="218" alt="jm2" src="https://user-images.githubusercontent.com/25342410/79775070-45d96780-8366-11ea-9522-ce1b51146957.png">
Do you think so? Thanks.

**Comment by silverwind** [comment]
The trailing whitespace "trick" is needed for the original Markdown version which, but not in GFM/Commonmark where soft-breaks can optionally be treated as hard-breaks.

**Comment by yuin** [comment]
@zeripath As @silverwind mentioned, GFM defines rendering soft line breaks as hard line breaks as an **optional** functionality.  goldmark has the WithHardWraps option. goldmark users will have the decision on which turning it on.
