### ISSUE TITLE
After private deployment, gitea cannot log in and reports 500 errors

### ISSUE THREAD

**Issue by pulei0702** [go-gitea/gitea#11175]
After clicking log in, it is always loaded. After checking the background log, I found that I would be redirected to a strange address. How can I solve this
Gitea version (or commit ref):
1.9.3
Git version:
2.22
Operating system:
Linux version 3.10.0-957.21.3.el7.x86_64
Database (use [x]):
MySQL
Can you reproduce the bug at https://try.gitea.io:
47.103.8.182:3000
Log gist:
![image](https://user-images.githubusercontent.com/35681724/79972440-8c46d780-84c8-11ea-8142-a6e38f380268.png)
[Macaron] 2020-04-22 18:21:43: Started GET / for 171.214.159.27
[Macaron] 2020-04-22 18:21:43: Completed GET / 200 OK in 1.727173ms
[Macaron] 2020-04-22 18:21:47: Started GET /user/login?redirect_to= for 171.214.159.27
[Macaron] 2020-04-22 18:21:58: Started GET /user/login?redirect_to=%2fuser%2flogin for 171.214.159.27
[Macaron] 2020-04-22 18:23:54: Completed GET /user/login?redirect_to= 500 Internal Server Error in 2m7.22149081s
[Macaron] 2020-04-22 18:23:54: Started GET /img/500.png for 171.214.159.27
[Macaron] [Static] Serving /img/500.png
[Macaron] 2020-04-22 18:23:54: Completed GET /img/500.png 200 OK in 469.343µs
[Macaron] 2020-04-22 18:24:05: Completed GET /user/login?redirect_to=%2fuser%2flogin 500 Interna

**Comment by zeripath** [comment]
Dude there's an issue template for a reason. Please use it.

What are the answers to the below?

- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

We need at least this basic information.

In addition, we need to know how you deployed Gitea. Is this docker, running from a command line, systemd etc? Are you running Gitea behind a reverse proxy eg. NGinx/Apache/IIS, if so which?

How do you access Gitea? What do you expect the url for Gitea to be? What's the contents of `custom/conf/app.ini` - Have you set the values there appropriately as per our documentation?

Have you looked at the documentation on https://gitea.io? Have you discussed this on Discord or the forums?

**Comment by pulei0702** [comment]
> Dude there's an issue template for a reason. Please use it.
> 
> What are the answers to the below?
> 
> * Gitea version (or commit ref):
> * Git version:
> * Operating system:
> * Database (use `[x]`):
>   
>   * [ ]  PostgreSQL
>   * [ ]  MySQL
>   * [ ]  MSSQL
>   * [ ]  SQLite
> * Can you reproduce the bug at https://try.gitea.io:
>   
>   * [ ]  Yes (provide example URL)
>   * [ ]  No
>   * [ ]  Not relevant
> * Log gist:
> 
> We need at least this basic information.
> 
> In addition, we need to know how you deployed Gitea. Is this docker, running from a command line, systemd etc? Are you running Gitea behind a reverse proxy eg. NGinx/Apache/IIS, if so which?
> 
> How do you access Gitea? What do you expect the url for Gitea to be? What's the contents of `custom/conf/app.ini` - Have you set the values there appropriately as per our documentation?
> 
> Have you looked at the documentation on https://gitea.io? Have you discussed this on Discord or the forums?

After clicking log in, it is always loaded. After checking the background log, I found that I would be redirected to a strange address. How can I solve this
Gitea version (or commit ref):
1.9.3
Git version:
2.22
Operating system:
Linux version 3.10.0-957.21.3.el7.x86_64
Database (use [x]):
MySQL
Can you reproduce the bug at https://try.gitea.io:
47.103.8.182:3000
Log gist:
![image](https://user-images.githubusercontent.com/35681724/79972440-8c46d780-84c8-11ea-8142-a6e38f380268.png)
[Macaron] 2020-04-22 18:21:43: Started GET / for 171.214.159.27
[Macaron] 2020-04-22 18:21:43: Completed GET / 200 OK in 1.727173ms
[Macaron] 2020-04-22 18:21:47: Started GET /user/login?redirect_to= for 171.214.159.27
[Macaron] 2020-04-22 18:21:58: Started GET /user/login?redirect_to=%2fuser%2flogin for 171.214.159.27
[Macaron] 2020-04-22 18:23:54: Completed GET /user/login?redirect_to= 500 Internal Server Error in 2m7.22149081s
[Macaron] 2020-04-22 18:23:54: Started GET /img/500.png for 171.214.159.27
[Macaron] [Static] Serving /img/500.png
[Macaron] 2020-04-22 18:23:54: Completed GET /img/500.png 200 OK in 469.343µs
[Macaron] 2020-04-22 18:24:05: Completed GET /user/login?redirect_to=%2fuser%2flogin 500 Interna

**Comment by pulei0702** [comment]
> Dude there's an issue template for a reason. Please use it.
> 
> What are the answers to the below?
> 
> * Gitea version (or commit ref):1.9.3
> * Git version:2.22
> * Operating system:Linux version 3.10.0-957.21.3.el7.x86_64
> * Database (use `[x]`):
>   
>   * [ ]  PostgreSQL
>   * [x]  MySQL
>   * [ ]  MSSQL
>   * [ ]  SQLite
> * Can you reproduce the bug at https://try.gitea.io:
>   
>   * [x]  Yes (provide example URL)
>   * [ ]  No
>   * [ ]  Not relevant
> * Log gist:
[Macaron] 2020-04-22 18:21:43: Started GET / for 171.214.159.27
[Macaron] 2020-04-22 18:21:43: Completed GET / 200 OK in 1.727173ms
[Macaron] 2020-04-22 18:21:47: Started GET /user/login?redirect_to= for 171.214.159.27
[Macaron] 2020-04-22 18:21:58: Started GET /user/login?redirect_to=%2fuser%2flogin for 171.214.159.27
[Macaron] 2020-04-22 18:23:54: Completed GET /user/login?redirect_to= 500 Internal Server Error in 2m7.22149081s
[Macaron] 2020-04-22 18:23:54: Started GET /img/500.png for 171.214.159.27
[Macaron] [Static] Serving /img/500.png
[Macaron] 2020-04-22 18:23:54: Completed GET /img/500.png 200 OK in 469.343µs
[Macaron] 2020-04-22 18:24:05: Completed GET /user/login?redirect_to=%2fuser%2flogin 500 Interna


> 
> We need at least this basic information.
> 
> In addition, we need to know how you deployed Gitea. Is this docker, running from a command line, systemd etc? Are you running Gitea behind a reverse proxy eg. NGinx/Apache/IIS, if so which?
> 
> How do you access Gitea? What do you expect the url for Gitea to be? What's the contents of `custom/conf/app.ini` - Have you set the values there appropriately as per our documentation?
> 
> Have you looked at the documentation on https://gitea.io? Have you discussed this on Discord or the forums?

**Comment by zeripath** [comment]
First of all 1.9.3 is very old - Please upgrade as we can't support that version. (You've also ticked yes you can replicate this on try.gitea.io but I think that's a mistake.)

How have you deployed Gitea? Is this docker, running from a command line, systemd etc? Are you running Gitea behind a reverse proxy eg. NGinx/Apache, if so which?

How do you access Gitea? What do you expect the url for Gitea to be? What's the contents of custom/conf/app.ini - Have you set the values there appropriately as per our documentation?
