### ISSUE TITLE
Alternate Config File Location

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#1117]
I would like to have my gitea config somewhere like `/etc/gitea.ini` or `/etc/gitea/app.ini` (somewhere under `/etc`), rather than `<binary_dirname>/custom/conf/app.ini`. It just seems cleaner, and more standard-conformant to keep configuration in `/etc`.

Ideally gitea would first look in a few places for its config: first in the directory it currently checks, then fall back to something in `$XDG_CONFIG_HOME` (`$HOME/.config`) (would be suitable for some install types), and then `/etc`, and have a CLI option to override this with a custom location for the config file (which would be handy in init scripts / systemd service files, and that sort of thing.)

This is particularly important if you want this to be packaged for distros; I doubt most maintainers would feel comfortable putting user-editable configuration files under `/usr/bin`, where the gitea binary would end up.

**Comment by tboerger** [comment]
Currently you can work around it by setting GITEA_CUSTOM_PATH environment variable, but on long term I want to provide some paths it should check like /etc/gitea, ~/.gitea, same for the custom assets but on /usr/share/gitea and ~/.gitea automatically

**Comment by tboerger** [comment]
Beside that it should also search from the current working directory and not relative to the binary.

**Comment by ghost** [comment]
thank you, that is good to know! is this documented somewhere? I didn't see it in the binary's built-in help text.

**Comment by tboerger** [comment]
I'm not sure but I think the env variable is mentioned on the docs.

**Comment by ghost** [comment]
hmm, I can't seem to get this working. is it possible this feature is broken? if i `git grep GITEA_CUSTOM_PATH` on the source tree i get nothing

**Comment by tboerger** [comment]
Sorry, my fault, it's just GITEA_CUSTOM.

**Comment by ghost** [comment]
ok, thanks!
