### ISSUE TITLE
Gitea page will render much slow when DarkReader is on

### ISSUE THREAD

**Issue by sometao** [go-gitea/gitea#11198]
Description
Gitea page(e.g. https://gitea.com/explore/users) will be render much slow when [DarkReader](https://github.com/darkreader/darkreader) is on. 

reference:
https://github.com/darkreader/darkreader/issues/2338

...

**Comment by claflico** [comment]
I can confirm this. Running in Docker on a Synology 1817+ and just even bringing up the install page took almost a minute. Getting past the install page took almost 2 minutes. Once I turned off Dark Reader it started behaving as expected.

**Comment by alexanderadam** [comment]
I may misunderstood, but gitea works fine without DarkReader, right? So there's nothing to do in the gitea repo, right?

And you even opened an issue in the _right_ place (the DarkReader repo). So it's not clear to me what the gitea maintainers should _solve_ here.

Or is there anything problematic _without_ DarkReader? :thinking:
