### ISSUE TITLE
[feature suggestion] add permission limit for reopen issue or pr

### ISSUE THREAD

**Issue by a1012112796** [go-gitea/gitea#11193]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

I think if an issue or pr is closed by admin, we should limit author who is not admin to reopen it. which is same with github. Thanks
...

**Comment by guillep2k** [comment]
I'd rather use the "locked" attribute. In a small team, the admin might just close an issue for many reasons that don't count for locking the issue.
