### ISSUE TITLE
Pull Request fails to change the target branch.

### ISSUE THREAD

**Issue by chriseaton** [go-gitea/gitea#11199]
- Gitea version (or commit ref): 1.11.4
- Git version: 1.8.3.1
- Operating system: CentOS 7
- Database (use `[x]`):
  - [x] PostgreSQL
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)

## Description
Editing an existing Pull Request target doesn't actually change the target.

Reproduce: 
1. Create 2 branches (`branch A`, `branch B`).
1. Create a new pull request to merge `branch A` into `master`.
1. Navigate to the pull request created and click "Edit".
1. Change the target from `master` to `branch B`.
1. Click "Save"
1. Notice the target branch reverts to `master`.

Expected behavior from reproduction:
The target branch should have changed from `master` to `branch B`.

**Comment by guillep2k** [comment]
Currently there's no support for moving a PR to a different branch. It's not that the branch is "reverted"; it's rather that you're not making any changes to the file so no commit is created.

There is already an issue requesting this functionality. Closing as a duplicate.

**Comment by chriseaton** [comment]
In this case then it's just bad UI since it's presented as an editable form, and the reaction by the app is to present faulty information when the form is acted upon. I think most users would expect, if this is indeed not a function that is supported, that it shouldn't be presented as such through the interface.

**Comment by guillep2k** [comment]
We could add a "File had no changes; no commit or branch was created" flash, perhaps?
