### ISSUE TITLE
reverse proxy setup instructions are incorrect

### ISSUE THREAD

**Issue by genehack** [go-gitea/gitea#11201]
- Gitea version (or commit ref): `Gitea version 1.11.4 built with GNU Make 4.1, go1.13.9 : bindata, sqlite, sqlite_unlock_notify`
- Git version: 2.20.1
- Operating system: Debian
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant

## Description

Following the instructions at https://docs.gitea.io/en-us/reverse-proxies/ for setting up to serve static resources doesn't work. Currently, if you check out the repo, or grab a snapshot of `master`, and run `make webpack`, many required files aren't generated (see attached screenshot for missing resources). 

I discovered via experimentation, that if I checked out the `v.1.11.4` tag and ran `make frontend` (`make webpack` not being available), _that_ worked. 

I wonder if the documentation has been updated to reflect changes in a forthcoming release, so they'll become correct at some point? Filing this bug mainly so, if others get stuck in the same situation, they will learn of the workaround... 

## Screenshots

<img width="1092" alt="Screen Shot 2020-04-23 at 21 03 11" src="https://user-images.githubusercontent.com/42126/80174768-8aecdc00-85a8-11ea-9daf-fb41d3a5f20d.png">

**Comment by guillep2k** [comment]
Duly noted.

Unfortunately we don't maintain a per-release docs version, so as you've said, things get confusing at some point. We've heavily rewritten the build procedure several times during the development of 1.12 (and it can still change a little more!), so the docs are kind of in a state of flux about that.
