### ISSUE TITLE
Cannot use MSSQL non default instance since Version 1.10.0

### ISSUE THREAD

**Issue by FLeven** [go-gitea/gitea#11207]
- Gitea version (or commit ref): 1.11.1+
- Git version: 2.25.1
- Operating system: 2012R2/2016/2019
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ x] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x ] Not relevant

## Description

I am using GiTea 1.10.0 with MSSQL without any problems, DB ist located on MSSQL 2016Sp3. I connect to the DB myip\myinstance and everything works fine.

If I switch to a 1.11.x Version, I can't connect to MS Sqlserver anymore and I can't install a new Gitea Instanze on my Microsoft SQL Server (Different versions tested).

In the Installer you can clearly see, that the parsing of the connectionstring has changed and it is not possible to pass "ipserver\instanzname" anymore.

It will only accept the "ip:port" part or the "/instanzname" part of the connectionstring and not the full "ip\instanzname" string.

Log:
Error: Unable to open tcp connection with host '127.0.0.1:1433'

**Comment by lunny** [comment]
Is this a problem of xorm or mssql driver? What's your database name on your `app.ini`?

**Comment by FLeven** [comment]
[database]
DB_TYPE  = mssql
HOST     = 127.0.0.1\MDT
NAME     = gitea
USER     = gitea
PASSWD   = *****
SSL_MODE = true
PATH     = data/gitea.db

[I] ORM engine initialization attempt #9/10...
2020/04/27 10:31:00 ...rm.io/xorm/engine.go:351:Ping() [I] PING DATABASE mssql
2020/04/27 10:31:01 routers/init.go:72:initDBEngine() [E] ORM engine initialization attempt #9/10 failed. Error: Unable to open tcp connection with host '127.0.0.1:1433': dial tcp 127.0.0.1:1433:

**Comment by guillep2k** [comment]
@FLeven Could you please run:
```
netstat -an | fgrep 1433
```
and post the results? We should see MSSQL listening.

**Comment by FLeven** [comment]
```
PS C:\Users\username> netstat -an | findstr.exe 1433
  TCP    0.0.0.0:1433           0.0.0.0:0              ABH?REN
  TCP    [::]:1433              [::]:0                 ABH?REN
```

**Comment by guillep2k** [comment]
Interesting... the error message suggest nobody's listening on those ports, or the port is unreachable (e.g. firewall).

A shot in the dark: since we've updated our `.ini` parser library, try `127.0.0.1\\MDT` instead of `127.0.0.1\MDT`.

**Comment by FLeven** [comment]
Ok, that worked, when using the default port 1433. THX

I tried this before, but I was using a named instance on a different port.
