### ISSUE TITLE
Gitea doesn't let create new branches on popup menu

### ISSUE THREAD

**Issue by ich777** [go-gitea/gitea#11212]
- Gitea version (or commit ref):
- Git version: 1.12.0+dev-211-g316db0fe7
- Operating system: Unraid in Docker Container
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes
  - [ ] No
  - [ ] Not relevant
- Log gist:
No log entry.

## Description

Gitea won't let me create a new branche using the webinterface.
Also this doesn't work on try.gitea.io

## Screenshots

No screenshot available

**Comment by guillep2k** [comment]
Could you be more specific? Like what steps you do to that fail? e.g. Can you push a new branch from a local git repo?

**Comment by ich777** [comment]
Sorry for beeing not specific, I tried it in the webgui.

1. Create a repo and add some files/code
2. Click on the 'branch' menu in the webgui
3. Enter a new branchname
4. Click on 'Create branch from...'
5. nothing happens

**Comment by genericusername3** [comment]
I'm having the same problem with Gitea 1.11.4 SQLite in a docker container, but I noticed that this error appears in the browser console when clicking the button: 
![image](https://user-images.githubusercontent.com/42579023/80866835-3ffe5300-8c91-11ea-9f51-1cc52b8aebab.png)

**Comment by guillep2k** [comment]
For reference, this is the menu that fails (it's failing on try.gitea.io as well):

**Comment by guillep2k** [comment]
For reference, this is the menu that fails (it's failing on try.gitea.io as well):

![image](https://user-images.githubusercontent.com/18600385/80925001-ccc51180-8d62-11ea-8176-c63147ce95ca.png)

**Comment by guillep2k** [comment]
I changed the title as the problem is not related to the docker distrubution; it happens when building from sources as well.

**Comment by zeripath** [comment]
If I  had to guess, this is probably related to the removal of the jQuery migration script.

**Comment by zeripath** [comment]
Ok, it could be that my guess is actually wrong.

Would anybody be able to adjust the code to ensure that `this.$refs.newBranchForm` is actually set properly?

It could be that there is a timing issue with Vue seeing that. 

If it is set, try wrapping that in `$(...).trigger(...)`

If it's not set try using `$('#newBranchForm').trigger(...)` or document.GetElementByID

**Comment by lafriks** [comment]
It could also be because of move from semantic-ui to fomantic-ui. If I remember correctly I had to do quite some magic back in the days to make it work correctly

**Comment by lafriks** [comment]
> Ok, it could be that my guess is actually wrong.
> 
> Would anybody be able to adjust the code to ensure that `this.$refs.newBranchForm` is actually set properly?
> 
> It could be that there is a timing issue with Vue seeing that.
> 
> If it is set, try wrapping that in `$(...).trigger(...)`
> 
> If it's not set try using `$('#newBranchForm').trigger(...)` or document.GetElementByID

I don't think there should be problem for Vue to see this.$refs as Vue is the one creating them

**Comment by zeripath** [comment]
it's the jquery issue. See the fix.
