### ISSUE TITLE
CORS for static resource

### ISSUE THREAD

**Issue by CthulhuDen** [go-gitea/gitea#11215]
- Gitea version: 1.11.4
- Git version: not relevant
- Operating system: Debian
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
When I configure `STATIC_URL_PREFIX` to another host name script links on gitea pages render like this:
```
<script src="https://cdn-gitea.cthulhuden.com/vendor/plugins/cssrelpreload/loadCSS.min.js"></script>
```
that is, without `crossorigin` attribute.

The `cors` settings seem to only apply to the API routes, hence browser refuses to load scripts and stylesheets.

**Comment by guillep2k** [comment]
This is not my field, but maybe you could create a [custom template](https://docs.gitea.io/en-us/customizing-gitea/) of the header and add the attribute?

**Comment by techknowlogick** [comment]
On gitea.com the CDN sets those headers for us.

**Comment by CthulhuDen** [comment]
I do roughly the same currently - set CORS headers on reverse proxy, however it doesn't seem right to have CORS configured in gitea config and still have this particular requests not covered.

How about just add crossorigin=anonymous for all static resources?

**Comment by jueti** [comment]
I post out my config below for gitea 1.12.2 rc on debian 10.3 armv8.

<details><summary>/etc/gitea/app.ini</summary>

```ini
server]
SSH_DOMAIN       = gitea.raspi-4b.local
DOMAIN           = gitea.raspi-4b.local
HTTP_PORT        = 3000
ROOT_URL         = http://gitea.raspi-4b.local/
STATIC_URL_PREFIX = http://cdn.raspi-4b.local/gitea
DISABLE_SSH      = false
SSH_PORT         = 22
OFFLINE_MODE     = false

```

</details>

<details><summary>/etc/nginx/sites-available/gitea</summary>

```nginx
server {
        listen          80;
        server_name     gitea.raspi-4b.local;

        location / {
                proxy_pass      http://localhost:3000;
        }
}
```

</details>

<details><summary>/etc/nginx/sites-available/cdn</summary>

```nginx
server {
        listen          80;
        server_name     cdn.raspi-4b.local;
        
        location / {
                return 404;
        }
        
        location /gitea {
                alias /var/www/cdn/gitea;
        }
        
        location ~* ^/gitea/.*\.(svg|woff2)$ {
                root /var/www/cdn;
                add_header Access-Control-Allow-Origin http://gitea.raspi-4b.local always;
        }
}

```

</details>

enable gitea: `sudo ln -s /etc/nginx/sites-available/gitea /etc/nginx/sites-enable/gitea`

enable cdn: `sudo ln -s /etc/nginx/sites-available/cdn /etc/nginx/sites-enable/cdn`

check configuration: `sudo nginx -t`

reload configuration: `sudo nginx -s reload`

**Comment by wxiaoguang** [comment]
I do not see why the `script` needs an extra `crossorigin` attribute here.

https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/crossorigin

Feel free to reopen if there are more details.
