### ISSUE TITLE
simple name and logo for gitea

### ISSUE THREAD

**Issue by sailfish009** [go-gitea/gitea#1121]
Hi, this is not question, just suggestion.

IMHO, gitea name is hard to remember and 
it's logo is somewhat not attractive and complex.
gitea has better functionality than gogs, 
so why not have more simple name and logo?

**Comment by sailfish009** [comment]
gogs: 3 characters
gitea: 5 characters :)

**Comment by lunny** [comment]
Github 6
Gitlab 6
:)

**Comment by tboerger** [comment]
And Gogs got 4 characters... So it's a single letter more

**Comment by strk** [comment]
I like the name `Gitea` too

**Comment by sailfish009** [comment]
gea gite gidea gate gote gotea gigs gags :D

**Comment by tboerger** [comment]
> gea gite gidea gate gote gotea gigs gags :D

Not any name that convince me at all :)

**Comment by thibaultmeyer** [comment]
_Gitea_ is a smart name for this project.

@sailfish009 do not think the number of letters but syllables.  Github (2 syllabes), Gitlab (2 syllabes), Gitea (2 syllabes too)

**Comment by tboerger** [comment]
But a cool gopher logo should be awesome

**Comment by sailfish009** [comment]
okay "gitea" name.

**Comment by lcges** [comment]
The "Gitea" name is very good. 
But the logo can propose better.
We can propose something better?

**Comment by lunny** [comment]
Yes, please.

**Comment by kolaente** [comment]
I've just made a quick draft, maybe it is something (or it's just garbage :D)

![logo-1 svg](https://cloud.githubusercontent.com/assets/13721712/23772062/e1577a90-0519-11e7-9426-f071a80a168e.png)

**Comment by kolaente** [comment]
Second Draft:
(This time with a gopher @tboerger )

![logo-1 svg_2](https://cloud.githubusercontent.com/assets/13721712/23772491/69bb0d42-051b-11e7-8118-40c6ed3d989f.png)

**Comment by kolaente** [comment]
New Draft:
![gitea-logo](https://cloud.githubusercontent.com/assets/13721712/23774862/30ad730e-0526-11e7-8240-a0b1f4569fa6.png)

**Comment by lunny** [comment]
But I like green tea better! :)

**Comment by pgaskin** [comment]
@kolaente I might be being a bit too picky, but can you shorten the strings on the icons to about 3/4 their current length?

**Comment by Starz0r** [comment]
I think we should use a logo without the Gopher mascot in it. Gogs has a really nice looking logo, and I really like how the Gitea logo draft looks a few replies above mine.

**Comment by lcges** [comment]
hi, this is my proposition logo:

[01]
![l3](https://cloud.githubusercontent.com/assets/19255071/23797030/2fb85e8c-059e-11e7-8a0b-409ca6fa01b6.jpg)
[02]
![l2](https://cloud.githubusercontent.com/assets/19255071/23797031/2fb9c27c-059e-11e7-923f-861b4ec6597d.jpg)
[03]
![l1](https://cloud.githubusercontent.com/assets/19255071/23797029/2fb85fae-059e-11e7-8f71-18d3da6c9980.jpg)

**Comment by lunny** [comment]
I like [03] 's icon. But where is the git ?

**Comment by axeloz** [comment]
I like @kolaente's small logo better than the full cup. The cup seems too complex to me, not easy to read nor recognize.


 I'm very bad at drawing but what's about this? 

![20170310_144854_hdr](https://cloud.githubusercontent.com/assets/1597611/23797586/e3dd3386-05a0-11e7-83e6-49ba986ac875.jpg)
 
- Removing the smoke (too complex)
- The handle of the cup becomes the G of GITEA
- Leaving the red tea bag which I find nice
- The T of GiTea might be uppercase in order to separate the words Git and Tea

And of course, much better designed than what I have done :-)

**Comment by pgaskin** [comment]
@qdbdbp I like the first icon, but it would be nice to add the git logo somewhere.

**Comment by pgaskin** [comment]
@lunny I think there should be a new issue for each logo proposal, because as people comment on the different logos, it will get very confusing.

**Comment by axeloz** [comment]
What I had in mind, I did the effort of using Photoshop ;-)
Still ugly, needs real improvements : better colors, fonts, item positions and stuff

![sans titre-1](https://cloud.githubusercontent.com/assets/1597611/23802957/46444dc0-05b5-11e7-9e94-ee7b8f80d280.png)

**Comment by lcges** [comment]
Yes, i think this is a good option separate issues.
I will add to "git" to logo and create a new issue.

**Comment by appleboy** [comment]
Move to #1260 for logo discussion.

**Comment by kolaente** [comment]
Also opened a new issue for discussion of my draft:  #1312

**Comment by lunny** [comment]
See #1260 and #1312. I will close this one.
