### ISSUE TITLE
the page show 500 error when I open my repository

### ISSUE THREAD

**Issue by stepm2** [go-gitea/gitea#11217]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description

logfile:
..ules/context/repo.go:605:func1() [E] GetBranchCommit: object not found

system notices:
Failed to health check repository (/home/ubuntu/tp/gitea/repositories/tom/jerry.web.git): exit status 2 - error: refs/heads/master: invalid sha1 pointer 0465a55c16418068b7e8100832b045db6dee5d06 error: HEAD: invalid sha1 pointer 0465a55c16418068b7e8100832b045db6dee5d06 notice: No default references

**Comment by stepm2** [comment]
I execute the gc,return(Application Version: 1.9.5):
 exec(21:Repository garbage collection) failed: exit status 128() stdout: stderr: error: refs/heads/master does not point to a valid object! error: refs/heads/master does not point to a valid object! fatal: bad object HEAD fatal: failed to run repack : error: refs/heads/master does not point to a valid object! error: refs/heads/master does not point to a valid object! fatal: bad object HEAD fatal: failed to run repack

摘要

**Comment by guillep2k** [comment]
Have you moved your repositories? Check if the files are still there... 😰

**Comment by 6543** [comment]
@stepm2 do you have changed the location where repository files are stored in your config?

or did you move this directory

**Comment by zeripath** [comment]
It looks like the repository on the filesystem has been corrupted. Are your disks fine? Have you had any unexpected shutdowns recently?

You should try going to a command line and try `git gc` in the git repository that Gitea uses. You could try pushing from a working copy again.

Please also note Gitea 1.9.5 is now quite old. We're undergoing quite rapid development and there have been several security bugs fixed since then.

**Comment by stepm2** [comment]
> It looks like the repository on the filesystem has been corrupted. Are your disks fine? Have you had any unexpected shutdowns recently?
> 
> You should try going to a command line and try `git gc` in the git repository that Gitea uses. You could try pushing from a working copy again.
> 
> Please also note Gitea 1.9.5 is now quite old. We're undergoing quite rapid development and there have been several security bugs fixed since then.

I did have an abnormal shutdown before, and I tried to use the git gc command, but returned the following message：
> error: refs/heads/master does not point to a valid object!
> error: refs/heads/master does not point to a valid object!
> fatal: bad object HEAD
> fatal: failed to run repack

**Comment by 6543** [comment]
this looks like the data broke on this abnormal shutdown :(

I hope you have a backup of it ( do you have some local repo closen) ?

**Comment by stepm2** [comment]
Probably, I have a local backup, but I still want to find before history, thank you so much.

**Comment by guillep2k** [comment]
Best of lucks!
