### ISSUE TITLE
nil pointer evaluating *models.GPGKey.KeyID

### ISSUE THREAD

**Issue by ki9us** [go-gitea/gitea#11230]
- Gitea version (or commit ref): 1.11.4
- Git version: N/A
- Operating system: CentOS
- Database:
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X] No
  - [ ] Not relevant

## Description

When I click on an unsigned commit, I get a 404 with the message: 

> template: repo/commit_page:90:57: executing "repo/commit_page" at <.Verification.SigningKey.KeyID>: nil pointer evaluating *models.GPGKey.KeyID

You can try this URL as an example: 
https://git.ki9.us/keith/compass/commit/81fd585e84edfa517b780ad52b9555b582e7d36b

I can't reproduce it on the demo site, so it must be an issue with my implementation.  

I'm running Gitea on [Uberspace](https://uberspace.de/en/), according to [these instructions](https://lab.uberspace.de/guide_gitea.html).

**Comment by guillep2k** [comment]
Is it possible you're using custom templates? Your templates might be outdated.

**Comment by keith24** [comment]
It will be a minute before I can look at this again.

**Comment by zeripath** [comment]
Sigh - go templates don't shortcut  ifs. Sorry about this.

**Comment by zeripath** [comment]
Sorry it also took me so long to recognise that this was the problem.
