### ISSUE TITLE
[Bug?] See milestone in a public should login

### ISSUE THREAD

**Issue by a1012112796** [go-gitea/gitea#11233]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

I wander why should request to login when open a milestone's detail in a public repo, I think it's not an necessary limit. Thanks

![tmp](https://user-images.githubusercontent.com/25342410/80446749-423b7700-894a-11ea-9e4c-c0e2c9b564ba.gif)

**Comment by guillep2k** [comment]
Related to #10312

**Comment by lunny** [comment]
duplicated with #10312
