### ISSUE TITLE
Commit as other user, as its using the email to lookup user

### ISSUE THREAD

**Issue by newbenji** [go-gitea/gitea#11234]
- Gitea version: 1.11.4 
- Git version: (local) 2.17.1
- Operating system: Ubuntu
- Database (use `[x]`): 
  - [ x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ x ] Not relevant
- Log gist:

## Description
  Create a repository
  Make 2 users. ex a@example.dk and b@example.dk
  create a deploy key with write accesss
  create .ssh file with the deploy key for the deploy access.
  in the gitconnfig as email write a@example.dk

 commit

Result:
  All commits from the deploy user will now stand as coming from user a@example.dk..
 Same if i change email address to b@example.dk.. as long as its real users on my gitea setup

Expected: 
Should write it comes from the deploy key .. so it seems its using the email to find user, and not the key itself.
...

**Comment by newbenji** [comment]
Also works if its users.
So i can commit as user b..

**Comment by guillep2k** [comment]
For that kind of security (i.e. commit identity), signed commits are the solution. Gitea will show a warning if any commit doesn't match the user's self-declared signature.

As for permissions, Gitea will guarantee that only people with push permissions will push commits. What those commits contain, is not for Gitea to decide.

Think about this: if you merge commits from another user in your branch, then make some changes and push that to the server, you'd be pushing the other user's commits into the main repository using your credentials.... but they will still show up the original commiter's e-mail (as it should). If you'd changed the user information, the commit would become invalid (or at least it wouldn't be the same commit).

It sounds a little counter-intuitive, I admit (I too struggled with the concept for a while), but it does make sense when you consider the big picture (after all, this architecture was designed by Linus Torvalds to better maintain the Linux kernel, and so far it's doing a great job).
