### ISSUE TITLE
Graceful restart web from UI or command line.

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#1123]
This should be part of #518 and it also useful when change some content of `config.ini` and need a restart. Of course, this restart should be graceful. The graceful maybe not only for `git web`, it's also for `git serv`/`git hook` and etc.

**Comment by strk** [comment]
Many servers provide two administrative operations: restart and reload.
The latter (reload) would be to just re-read configuration files.

**Comment by tboerger** [comment]
I'm fine with watching the config and accepting changes without restarting the server, but I would not provide any restart action on the Web ui

**Comment by bkcsoft** [comment]
Please also support SIGINT (reload config) and SIGHUP (restart web-service) :trollface:

**Comment by lunny** [comment]
@tboerger If you will support to get upgrade info via notification and maybe we can upgrade online and restart it.
