### ISSUE TITLE
Underscore at the end of URLs not displayed as link / link gets modified

### ISSUE THREAD

**Issue by cyb3rko** [go-gitea/gitea#11247]
- Gitea version (or commit ref): 1.12.0+dev-222-gd26aee383
- Git version: 2.24.3
- Operating system: Docker
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (example URL: https://try.gitea.io/nikothegreek/testtest/releases)
  - [ ] No
  - [ ] Not relevant

## Description
If you paste a link, which ends with an underscore, in a release in a repository, the underscore at the end is shown as a text and the link doesn't work anymore because of the missing underscore.

Is there a way to escape that problem or does it have to be fixed by the developers?

## Screenshots

![image](https://user-images.githubusercontent.com/46033730/80601543-3fb24d80-8a2e-11ea-923f-602d17eec81e.png)

**Comment by zeripath** [comment]
use 
```markdown
[anchor](link)
```

**Comment by nikothegreek** [comment]
Thanks!
