### ISSUE TITLE
The UI presents the option to change the target branch of a pull request, when it is not actually supported.

### ISSUE THREAD

**Issue by chriseaton** [go-gitea/gitea#11241]
- Gitea version (or commit ref): 1.11.4
- Git version: 1.8.3.1
- Operating system: CentOS 7
- Database (use `[x]`):
  - [x] PostgreSQL
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)

## Description
Editing an existing Pull Request target doesn't actually change the target.

Reproduce: 
1. Create 2 branches (`branch A`, `branch B`).
1. Create a new pull request to merge `branch A` into `master`.
1. Navigate to the pull request created and click "Edit".
1. Change the target from `master` to `branch B`.
1. Click "Save"
1. Notice the target branch reverts to `master`.

Expected behavior from reproduction:
Per the issue #11199 the feature of changing a target branch is not supported, so the UI should _not_ present the option to change the target branch. 

Suggestion: Disable the target branch dropdown upon pull request edit.

**Comment by zeripath** [comment]
I believe that this is fixed in 1.12

**Comment by lafriks** [comment]
Closing as fixed, reopen if there is still a problem.
