### ISSUE TITLE
organization listed multiple times when creating a repository

### ISSUE THREAD

**Issue by mnazarov** [go-gitea/gitea#11258]
- Gitea version (or commit ref): 1.11.4
- Operating system: ubuntu 18.04
- Database (use `[x]`):
  - [x] PostgreSQL
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes - see e.g. https://try.gitea.io/org/testMaxOrg/teams 2 teams each with 'Create repository' permission

## Description
If an organization has multiple teams with 'Create repository' permission, then whenever a user belonging to several such teams tries to create a repository they see the organization name listed multiple times under "Owner" (see screenshot). The number of times matches the number of teams they are member of.
This is probably a bug, but at the same time it would be cool if it would show team names here, and the repository would be created and added to that team automatically...

## Screenshots
![create](https://user-images.githubusercontent.com/2838666/80704920-c70ec800-8ae5-11ea-841d-6e709ee2cc3a.PNG)

**Comment by CirnoT** [comment]
Should be reopened, the mentioned PR does NOT fix this issue.

**Comment by 6543** [comment]
I found the proglem: GetOrgsCanCreateRepoByUserID return dubble entrys on described case
