### ISSUE TITLE
Add GET /admin/users/:username/keys resource to obtain SSH public keys

### ISSUE THREAD

**Issue by pelegrim** [go-gitea/gitea#11255]
It would be nice to have Gitea as an alternative to GitHub
The resource should be available with out authentication.
http://manpages.ubuntu.com/manpages/bionic/man1/ssh-import-id.1.html

**Comment by 6543** [comment]
But as far as i can tell gitea does not akt as keyserver, does gh?!?

**Comment by pelegrim** [comment]
Response should be similar to described here https://developer.github.com/v3/users/keys/

**Comment by techknowlogick** [comment]
This is implemented already at https://gitea.com/techknowlogick.keys (by appending `.keys` to a users profile)

**Comment by 6543** [comment]
API is also available: https://try.gitea.io/api/swagger#/user/userListGPGKeys

**Comment by pelegrim** [comment]
Tested.
Works correctly.
