### ISSUE TITLE
Gitea doesn't start

### ISSUE THREAD

**Issue by JayReturns** [go-gitea/gitea#11261]
- Gitea version (or commit ref): Gitea version 1.11.4 built with GNU Make 4.1, go1.13.9 : bindata, sqlite, sqlite_unlock_notify
- Git version: git version 2.20.1
- Operating system: Linux 5.3.18-1-pve
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description
Every time i try to start gitea using `sudo systemctl start gitea.service` nothing happens. I doesn't throw any erros. `systemctl status gitea.service` returns the following log:
```
Apr 30 13:47:49 McUniverse systemd[1]: Started Gitea (Git with a cup of tea).
Apr 30 13:47:49 McUniverse gitea[22057]: 2020/04/30 13:47:49 cmd/web.go:107:runWeb() [I] Starting Gitea on PID: 22057
Apr 30 13:47:49 McUniverse gitea[22057]: 2020/04/30 13:47:49 ...dules/setting/git.go:91:newGit() [I] Git Version: 2.20.1, Wire Protocol Version 2 Enabled
Apr 30 13:47:49 McUniverse gitea[22057]: 2020/04/30 13:47:49 routers/init.go:87:GlobalInit() [T] AppPath: /usr/local/bin/gitea
Apr 30 13:47:49 McUniverse gitea[22057]: 2020/04/30 13:47:49 routers/init.go:88:GlobalInit() [T] AppWorkPath: /var/lib/gitea
Apr 30 13:47:49 McUniverse gitea[22057]: 2020/04/30 13:47:49 routers/init.go:89:GlobalInit() [T] Custom path: /var/lib/gitea/custom
Apr 30 13:47:49 McUniverse gitea[22057]: 2020/04/30 13:47:49 routers/init.go:90:GlobalInit() [T] Log path: /var/lib/gitea/log
Apr 30 13:47:49 McUniverse gitea[22057]: 2020/04/30 13:47:49 ...dules/setting/log.go:233:newLogService() [I] Gitea v1.11.4 built with GNU Make 4.1, go1.13.9 : bindata, sqlite, sqlite_unlock_notify
``` 
After a clean installation everything worked perfectly. After a `systemctl restart gitea.service`it stopped working.
Let me know if you need extra information!
Thanks in advance :)

**Comment by lafriks** [comment]
check `gitea.log` for errors

**Comment by JayReturns** [comment]
Thanks! That helped a lot. I thought that it didn't even write in this file because my system time wasn't correct.
