### ISSUE TITLE
feature: Hide archived repositories from Web UI

### ISSUE THREAD

**Issue by bkraul** [go-gitea/gitea#11268]
So I have been looking at archiving a lot of our old repositories. I see the option to archive which effectively makes the repo read-only and such. However, I see no option in the UI or the gitea ini to **hide** archived repositories from the Web UI. I have checked the forums and github to figure out if anything like this is available, and the only thing I have found is the suggestion to create a new org for archived repos.

However, this does not solve my original problem, because the repos still show up in the feed list. What I am trying to do is to have them as if they are no longer there. They are archived, I don't need to see them, but I don't quite need to delete them. I figure this could be a nice option to have, a checkbox either system-wide or user-specific to "hide" archived repositories from view. 

![image](https://user-images.githubusercontent.com/14616851/80815701-c5034280-8b93-11ea-92aa-c7aaee5c7038.png)

It would greatly help organization and cleanness.

**Comment by benjamfk** [comment]
I agree, that's probably the feature I miss the most coming from GitLab CE

**Comment by bkraul** [comment]
In the meantime, the only solution for this I could come up with was to create an "archive" account, and then create an "archive" organization, and give the account ownership of it. No one else being part of the org, any repo that is transferred to that org, successfully goes away without being deleted. Kinda ugly for me, but it does the job. We just have to keep track of the password for the archive account, should we ever need to access any of those archived repos.
