### ISSUE TITLE
Timeout error attempting to create internal queue for task

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#11274]
```log
2020/05/02 17:23:02 ...ueue_disk_channel.go:144:Run() [F] Unable to create internal queue for task Error: Timedout creating queue level with cfg queue.LevelQueueConfiguration{ByteFIFOQueueConfiguration:queue.ByteFIFOQueueConfiguration{WorkerPoolConfiguration:queue.WorkerPoolConfiguration{QueueLength:1000, BatchLength:20, BlockTimeout:1000000000, BoostTimeout:300000000000, BoostWorkers:5, MaxWorkers:6}, Workers:1, Name:"task-level"}, DataDir:"/data/gitea/data/queues/task"} in task
```

**Comment by zeripath** [comment]
Presumably there are some logs preceding this. The issue is that the persistent queue for the task is locked and can't be opened.

**Comment by mbedded** [comment]
I run into this error as i updated from 1.11.3 to 1.12.3 today.
The server is not started and i can't access the website via browser.

**Comment by lunny** [comment]
> Presumably there are some logs preceding this. The issue is that the persistent queue for the task is locked and can't be opened.

But cannot know this from the log information.

**Comment by lunny** [comment]
Let's move to your issue and close this one.
