### ISSUE TITLE
Log entries displayed twice

### ISSUE THREAD

**Issue by axil** [go-gitea/gitea#11273]
- Gitea version (or commit ref): 1.11.4
 built with GNU Make 4.1, go1.13.9 : bindata, sqlite, sqlite_unlock_notify
- Git version: 2.11.0
- Operating system: 
Linux 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u2 (2017-06-26) x86_64 GNU/Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant: try.gitea.io times out
- Log gist:

## Description
Every log entry is displayed twice in the dashboard.
...

## Screenshots

![image](https://user-images.githubusercontent.com/170910/80859793-9d90a080-8c8d-11ea-91ab-fafa37101830.png)

**Comment by axil** [comment]
This affects other actions, such as creating issues. Reproduced on windows v1.11.4, not reproduced with v1.10.6 (on linux).

Steps to reproduce: register user, create new repo, open dashboard. Two log entries instead of one.

**Comment by CirnoT** [comment]
I have observed this randomly happening only once, does it happen reliably all the time for you?

**Comment by axil** [comment]
@CirnoT I didn't check extensively, but I haven't seen any single action logged once.

**Comment by ozonep** [comment]
Yep, have the same issue every time I deploy an instance of Gitea.
This bug appeared first in 1.11-rc0, 1.10.6 is fine.
I think that's because actions were refactored. in 1.10 actions were fired one by one, since 1.11 they are fired in batches.
