### ISSUE TITLE
bug: Attachments are not displayed on issues

### ISSUE THREAD

**Issue by bkraul** [go-gitea/gitea#11270]
- Gitea version (or commit ref): 1.12.0+dev-247-g1bdffefc0
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes: https://dev-git.epginsurance.com/bkraul/test/issues/1
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
Attachments added to an issue as part of comments are not being displayed. If an attachment is added by itself, the comment on the issue reads "Attached file".

## Screenshots
![Attachments gif](https://user-images.githubusercontent.com/14616851/80833635-977ac100-8bb4-11ea-9724-2b604a6a8a12.gif)

**Comment by lunny** [comment]
Will be resolved by #11272

**Comment by 6543** [comment]
should be closed now - @bkraul can you test if it works now on latest master build?

**Comment by bkraul** [comment]
Sure thing man, as soon as CI builds the docker image:

![image](https://user-images.githubusercontent.com/14616851/80866607-3951ea80-8c55-11ea-9722-66175382a41d.png)

Thanks for the quick action! 👍

**Comment by bkraul** [comment]
Ok, so try.gitea.com has been updated, and the attachments "work" to an extent. Picture attachments seem to be working OK, but uploading other formats does not work. For example, I am trying to upload a `docx` file. It does not show up or there is any trace of it being downloaded. I know it is supported:

![image](https://user-images.githubusercontent.com/14616851/80868355-aa969b00-8c5f-11ea-92e8-60f6ed7662ed.png)

![image](https://user-images.githubusercontent.com/14616851/80868409-f77a7180-8c5f-11ea-855f-2da1605f4bda.png)

**Comment by lunny** [comment]
Why did you think try.gitea.io support pdf and docx? I think it will only support images and zip files.

**Comment by bkraul** [comment]
I sent you a screenshot of what try.gitea.io says it supports.

**Comment by bkraul** [comment]
And yes, I can see there is a setting on app.ini for this:
```

**Comment by bkraul** [comment]
OK, I can verify the attachment works on my environment (because of my allowed types setting). I think you can close this issue. However, on `try.gitea.io` you might want to look at that upload component, I am not sure it is in sync with what's actually allowed (because it says it allows `docx`). 😄 

Thanks again!
