### ISSUE TITLE
DefaultRepoUnits doesn't seem to be loaded from app.ini

### ISSUE THREAD

**Issue by sadaszewski** [go-gitea/gitea#11271]
- Gitea version (or commit ref): 1.11.4
- Git version:
- Operating system: FreeBSD
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:

## Description

DEFAULT_REPO_UNITS setting seems to have no effect. A glance at:

https://github.com/go-gitea/gitea/blob/c8d7ae1ee33e31ed15632a26c74ba9a3ea115043/modules/setting/repository.go

reveals that it isn't even loaded from app.ini as far as I can tell. Please advise.

**Comment by sadaszewski** [comment]
* Type, Gitea Release 1.11.4

**Comment by guillep2k** [comment]
Maybe you're looking for this?

https://github.com/go-gitea/gitea/blob/c8d7ae1ee33e31ed15632a26c74ba9a3ea115043/modules/setting/repository.go#L213

`Cfg.Section()` will automagically fill in the values from `app.ini`.

If you make any changes to `app.ini`, make sure you restart the instance. If you're having problems, maybe checking in in our [Discord chat](https://discord.gg/Gitea) first would help.

**Comment by sadaszewski** [comment]
Hi guillep2k, thank you for your comment. Agreed, it seems as it is being loaded. Nevertheless it doesn't work, i.e. always all units are added to new repositories. The settings in app.ini seem to be correct specifying:

[repository]
DEFAULT_REPO_UNITS=repo.code

and the app has been restarted multiple times. Nevertheless, all new repositories are created with all units activated. I took another look and in:

https://github.com/go-gitea/gitea/blob/4be7cf04054e5eab3b2cf4a63ad31a9333ab4732/models/repo.go#L1054

one can see that DefaultRepoUnits are referenced but I am afraid this is not the DefaultRepoUnits from:

https://github.com/go-gitea/gitea/blob/c8d7ae1ee33e31ed15632a26c74ba9a3ea115043/modules/setting/repository.go#L41

I believe those are rather the array of all repo units from here:

https://github.com/go-gitea/gitea/blob/3c07d03c0388d3b86138572401281b51f2db9282/models/unit.go#L74

Could you please confirm and if so - is somebody working on a fix? Thank you in advance. BR, -- Stanislaw

**Comment by zeripath** [comment]
This feature was added in #8788 which is on the 1.12 milestone.
