### ISSUE TITLE
Provide multiarch Docker image

### ISSUE THREAD

**Issue by vielmetti** [go-gitea/gitea#1127]
## Description

#531 describes the need for a Raspberry Pi (armhf) Docker image. Similarly there are other needs for other Docker images supporting other non-Intel platforms, including ARMv8.

The proposed effort would build a `multiarch` Docker manifest that would allow a single Docker image serve all supported platforms. 

The analogous effort was done by Portainer in the issue https://github.com/portainer/portainer/issues/285 . 

gitea would be one of the first applications to support a multiarch Docker build, and as such the build tools are relatively unrefined and incomplete (though not all that complicated).

**Comment by tboerger** [comment]
This is more or less a duplicate of https://github.com/go-gitea/gitea/issues/53. I want to build a drone plugin that can build different architectures.

**Comment by vielmetti** [comment]
#53 does not look related, @tboerger - do you mean #31 , which is clearly related

**Comment by tboerger** [comment]
Copied the wrong link, #531

**Comment by tboerger** [comment]
You can add the 1.2.0 milestone, I will build the multi arch drone plugin

**Comment by lunny** [comment]
@tboerger any update for this?

**Comment by techknowlogick** [comment]
Unstale
