### ISSUE TITLE
Bug: DISABLED_REPO_UNITS does not diable the wiki

### ISSUE THREAD

**Issue by dschier-wtd** [go-gitea/gitea#11287]
- Gitea version (or commit ref): 1.11.4
- Git version: 1.8.3.1
- Operating system: RHEL 7.8
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
  - [x] unknown
- Log gist:

## Description

I added the option

```
[repository]
DISABLED_REPO_UNITS = repo.wiki
```

to my configuration. Unfortunately, the wiki option is still present after a restart of the service for users and administrators. Its even created by default.
...

**Comment by zeripath** [comment]
This feature was only merged with #8788 which is in 1.12 only.

**Comment by daniel-wtd** [comment]
Thanks a lot :)
