### ISSUE TITLE
RPI 4B : Gitea 1.11.4 keeps restarting every 30 seconds

### ISSUE THREAD

**Issue by agambier** [go-gitea/gitea#11281]
- Gitea version (or commit ref): gitea-1.11.4-linux-arm-6
- Git version: 2.20.1
- Operating system: Raspbian Buster
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:

## Description
Hi,

I've installed Gitea on a Raspberry Pi 4B and I noticed in the syslog file that Gitea service keeps stopping and restarting every ~30 seconds.

Here's a part of my /var/log/syslog file [log.txt](https://github.com/go-gitea/gitea/files/4569960/log.txt).

I installed it following the documentation : [Installation from binary](https://docs.gitea.io/en-us/install-from-binary/)

It works fine except every ~30 seconds it's not available while it's restarting.

Any ideas ?
thanks

**Comment by TsakiDev** [comment]
You should also check the gitea.log probably found in /var/lib/gitea/log/ or wherever is your GITEA_WORK_DIR/log.

Afterwards, search the error written in the log. There is a high possibility that someone else also stumbled to a similar issue.

PS - I think that Raspbian doesn't support MySql 8 it supports MariaDB so this might also be your problem?! Don't take my word for it. But, when I installed on my Raspberry Pi I used PostgreSQL.

**Comment by agambier** [comment]
Thanks for your reply.
I had a look at the log file one error was :

> 2020/05/02 19:18:43 ...eue/queue_wrapped.go:67:setInternal() [W] [Attempt: 798] Failed to create queue: level for task cfg: {/var/lib/gitea/data/queues/task 1000 20 1 6 1s 5m0s 5 task-level} error: leveldb: manifest corrupted (field 'comparer'): missing [file=MANIFEST-000038]

So I tried to delete index files as described here : #7013. 
But it didn't fix it, it keeps restarting.

Here's the latest gitea log file, maybe it can help...

[gitea.log.tar.gz](https://github.com/go-gitea/gitea/files/4571468/gitea.log.tar.gz)

**Comment by guillep2k** [comment]
Relevant line in the log:
```
2020/05/03 21:43:36 ...eue/queue_wrapped.go:67:setInternal() [W] [Attempt: 692] Failed to create queue: level for task cfg: {/var/lib/gitea/data/queues/task 1000 20 1 6 1s 5m0s 5 task-level} error: leveldb: manifest corrupted (field 'comparer'): missing [file=MANIFEST-000038]
```

**Comment by guillep2k** [comment]
This sounds like an abrupt shutdown corrupted your queue databases. You should try deleting the `/var/lib/gitea/data/queues/task` directory. If that is not enough, you may need to delete all the directories below `queues`.

**Comment by agambier** [comment]
Fixed.

I had to delete the index files and all the directories below `queues` and now it works fines.
Thanks for your help.

**Comment by TsakiDev** [comment]
Yaaay! 🎉
