### ISSUE TITLE
Labels disappear when "blaming" file.

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#11280]
- Gitea version (or commit ref): 1.11.4
- Git version: not relevant
- Operating system: not relevant
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

Bug was already reproduced at [gitea.com](https://gitea.com) (1.12.0-dev)

_Currently:_ When "blaming" some file the labels disappear below the repository description.
_Expected:_ Labels are still visible.

**Steps to reproduce:**
1. Navigate to 'Code'
2. Choose a file of your liking and view its source code
3. Press 'Blame'

## Screenshots

**Labels are visible**
![grafik](https://user-images.githubusercontent.com/64696032/80869250-bd30c480-8c9f-11ea-8a01-f59c39441180.png)

**Labels are missing**
![grafik](https://user-images.githubusercontent.com/64696032/80869253-c0c44b80-8c9f-11ea-886e-bef35a6fed79.png)

**Comment by 6543** [comment]
I'll have a look at this
