### ISSUE TITLE
Attempt to recover leveldb queues if they fail to open

### ISSUE THREAD

**Issue by guillep2k** [go-gitea/gitea#11284]
- Gitea version (or commit ref):

## Description

Apparently leveldb are pretty fragile when they are closed abruptly (e.g. `kill -9`). We should attempt to recover the database usinng the [`Recover()`](https://godoc.org/github.com/syndtr/goleveldb/leveldb#Recover) function from the leveldb API.

**Comment by zeripath** [comment]
https://gitea.com/lunny/levelqueue/pulls/2

and once that's in we'll need to update the dependency in gitea proper.
