### ISSUE TITLE
Dockerfile.aarch64 for building for Docker on ARMv8

### ISSUE THREAD

**Issue by vielmetti** [go-gitea/gitea#1128]
## Description

Proposed to create a `Dockerfile.aarch64` for building on ARMv8, akin to the existing Raspberry Pi image.

The current Dockerfile is built from Alpine 3.4. The current version of Alpine is 3.5.2. The supportable Alpine images on https://hub.docker.com/r/aarch64/alpine/tags/ include a 3.5 tag, but not a 3.4 tag, so there might reasonably be other issues involved in the move from 3.4 to 3.5.

Other than that I don't anticipate any big issues....

**Comment by tboerger** [comment]
Already got the plan, like Gogs at https://github.com/gogits/gogs/pull/4018

**Comment by tboerger** [comment]
And I think we will update all containers to alpine 3.5

**Comment by vielmetti** [comment]
Aha, looks like https://hub.docker.com/r/atzoum/aarch64-gitea/ is a working example from @atzoum

**Comment by lunny** [comment]
This may duplicated with #691 ?

**Comment by tboerger** [comment]
Not related to #691, this issue only wants a working Dockerfile

**Comment by lunny** [comment]
resolved by #1130
