### ISSUE TITLE
Submodule listings do not use full URL (missing port) with gitea in docker

### ISSUE THREAD

**Issue by Halfwalker** [go-gitea/gitea#11304]
- Gitea version (or commit ref): Powered by Gitea Version: 1.12.0+dev-186-g41f05588e
- Git version: git version 2.17.1
- Operating system: Ubuntu 18.04.4
- Docker version: Docker version 19.03.8, build afacb8b7f0
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant - not running docker using port 3000
- Log gist:

## Description
Running gitea in docker, started as follows
```
docker run --rm --name gitea \
    -e TZ=America/New_York \
    -e USER_UID=1001 \
    -e USER_GID=1001 \
    -p 3000:3000 \
    -p 127.0.0.1:2222:22 \
    -v /etc/localtime:/etc/localtime:ro \
    -v /etc/timezone:/etc/timezone:ro \
    -v /stuff/gitea:/data \
    gitea/gitea:latest
```
Everything runs fine, except for submodules.  They work fine, but rendering in the gui is missing the port **3000** for links.  Cannot reproduce on **try.gitea.io** as that is on regular port 443, not port 3000 as the dockerized version.

Gitea Base URL: _http://myhost.local:3000/_
SSH Server Domain: _myhost.local_

## Steps to reproduce
Create a new repo "test1"
Create a new repo "sub1" to act as submodule to test1
Clone test1 locally, then add sub1 as a submodule
```
$ git clone git@myhost.local:Halfwalker/test1.git
$ cd test1
$ mkdir subs
$ cd subs
$ git submodule add git@myhost.local:Halfwalker/sub1.git
```
Check what we've done
```
$ cd ..
$ git status

On branch master

No commits yet

Changes to be committed:
  (use "git rm --cached <file>..." to unstage)

        new file:   .gitmodules
        new file:   subs/sub1
```
Add files to repo, commit
```
$ git add .
$ git commit -m "Intial commit"

[master (root-commit) 1eae353] Intial commit
 2 files changed, 4 insertions(+)
 create mode 100644 .gitmodules
 create mode 160000 subs/sub1
```
Push to gitea
```
$ git push

Counting objects: 4, done.
Delta compression using up to 16 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (4/4), 359 bytes | 359.00 KiB/s, done.
Total 4 (delta 0), reused 0 (delta 0)
remote: . Processing 1 references
remote: Processed 1 references in total
To myhost.local:Halfwalker/test1.git
 * [new branch]      master -> master
```
Now look test1 repo on gitea - looks fine
Click into "subs" directory - works fine
  _http://myhost.local:3000/Halfwalker/test1/src/branch/master/subs_

sub1 submodule directory has link _http://myhost.local/Halfwalker/sub1_
commit has link _http://myhost.local/Halfwalker/sub1/commit/5436......_

MISSING port **3000**, should be _http://myhost.local:3000/Halfwalker/sub1_

**Comment by zeripath** [comment]
so that code is even more broken than I thought. 2 secs

**Comment by Halfwalker** [comment]
Just tested again using the _http://myhost.local:3000/Halfwalker/sub1.git_ rather than _git@myhost.local:/Halfwalker/sub1.git_ and that renders correctly, including the port **3000**.

So it's the rendering of git via ssh URLs that fails.

**Comment by zeripath** [comment]
Sorry I literally just fixed another bug in that code - I remember looking at it thinking well that can't work for ports but didn't see an issue anywhere pointing to it so assumed it was working fine.

**Comment by Halfwalker** [comment]
Whups - got stuck in lint ?

**Comment by zeripath** [comment]
That's VSCode's gopls failing to do its job!! (mostly because I keep having to switch between master and release/v1.11 etc. so the language server keeps breaking.)

**Comment by Halfwalker** [comment]
I just did a `docker pull gitea/gitea:latest` which gave me

`Powered by Gitea Version: 1.12.0+dev-268-g505e456f2`

But the links for submodules are still missing the port :(
BTW, crazy fast action - most projects drag and drag before even ack'ing an issue.

**Comment by zeripath** [comment]
@Halfwalker it's not merged yet!!
