### ISSUE TITLE
Mistake in the "SSH Container Passthrough" docs

### ISSUE THREAD

**Issue by Adrien-Luxey** [go-gitea/gitea#11318]
- Gitea version (or commit ref): latest docs
- Git version: irrelevant
- Operating system: irrelevant
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

There seems to be a mistake in the [SSH Container Passthrough](https://docs.gitea.io/en-us/install-with-docker/#ssh-container-passthrough) section of the *Installation with Docker* doc page.

We are asked to create a shell script at `/app/gitea/gitea` on the host, which does not make sense. Shouldn't it be `/usr/local/bin/gitea` instead? 

I do not find this piece of doc so clear, despite good efforts. Could you review it a bit, please?

Thanks for your hard work. Gitea rocks!

**Comment by Adrien-Luxey** [comment]
Ok, got it thanks notably to https://blog.sakuragawa.moe/gitea-in-docker-container-and-sharing-ssh-with-host/

So, inside the container, your `gitea` binary lives in `/app/gitea/gitea`. Since you share the `authorized_keys` between host and container, the host tries to call a binary at `/app/gitea/gitea`. Instead of the `gitea` binary, on the host, you set a ssh forward command.

This could be clearer in the docs, but it works! 
And, since I'm migrating from a host-based to container-based install, I expected to have to change my existing `authorized_keys`. But gitea did it for me - I was amazed :)

PS: Wouldn't it be simpler to share the host's .ssh directory with the container's, as proposed in the tutorial mentioned above? That's what I did, and I find it simpler than the `ln -s` from your docs.

**Comment by Doko-Demo-Doa** [comment]
I bumped into the same situation. I just want ssh cloning work (default port 22), and this url can be  cloned:

```
git clone git@git.testhost.com/testuser/test-repo.git
```
How did you solve that @Adrien-Luxey ? By following the guide above?

**Comment by Adrien-Luxey** [comment]
I had a working gitea setup on the host before switching to the Docker version (with `git clone` that worked). What you need is a properly configured `git` user on your host. I'd say go there to see how the `git` user should be configured: https://docs.gitea.io/en-us/install-from-binary/#prepare-environment Hope this helps! I feel the docs are quite complete, but you have to browse a bit. Good luck!
