### ISSUE TITLE
change ui to arc-green dark mode does not work on 1.11

### ISSUE THREAD

**Issue by laoshaw** [go-gitea/gitea#11322]
- Gitea version (or commit ref): 1.11.4
- Git version:
- Operating system: Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ x] Yes (provide example URL)
  - [ ] No
  - [x ] Not relevant
- Log gist:

## Description

in app.in set:

```
[ui]
DEFAULT_THEME = arc-green
```
then restart gitea and use browser to access its pages, theme not changed.

## Screenshots

same color as original default "gitea" theme, as nothing changes in color.

**Comment by zeripath** [comment]
Changing the default will not affect users who already have a default theme. You will need to change your users default theme.

**Comment by laoshaw** [comment]
Thanks! I did not even know I can choose default theme in user settings. Just did it and it works.
