### ISSUE TITLE
Rewrite Gitea fronend in react+atlaskit

### ISSUE THREAD

**Issue by taheri24** [go-gitea/gitea#11324]
Hello!
 I’ve been using Gitea for about 1 months and lately I’ve been looking at the frontend. Comrades, it seems he has lagged behind what they are doing now.
I am a front-end developer and in my free time I can do rewriting the front-end to a modern technology stack, which will be much easier to maintain.
I am going to use the API, but I think it will not be enough for my tasks. I ask the help of the community in developing additional API methods upon request for the normal functioning of the front-end.

I am going to use `parcel.js`, `react`,`redux`, `atlaskit` and typescript for front-end development. I think this should be a quick SPA. My main task is to separate the front-end from the backend to adequately support all this in the future. I think current front-end assets inside git-executable file ,

 how to **separate front-end assets** that other people can modify(rewrite) theirs.   is  it available as hidden feature(config)? 
 
What do you think about this feature? I am waiting for a community reaction in order to understand if this is necessary.

see [gitea-react](https://github.com/taheri24/gitea-react) for progress of my goal.  
I try update it daily for quick response
 
thanks for 
https://github.com/go-gitea/gitea/issues/8174

**Comment by jolheiser** [comment]
As mentioned in #8174, I believe Vue is what most maintainers seem to have the most experience in and would be preferred.

As well, with a cursory glance at `atlaskit` I'm not entirely certain where their licensing falls for a project such as ours and I was unable to find source for it, which makes me a little uneasy.

**Comment by techknowlogick** [comment]
Thanks for opening this ticket :)

As mentioned in the other ticket we aren't looking at re-writing our FE in react, and so I will close this ticket.

As for react, you may want to reach out to the authors of https://github.com/unfoldingWord/gitea-react-toolkit as I know they are doing similar things to what you are proposing.

**Comment by taheri24** [comment]
thanks @techknowlogick   for refer , but  I think `go-gitea`  will be better with react
