### ISSUE TITLE
[Bug] [Api] /orgs/{:orgname}/repos POST endpoint is broken

### ISSUE THREAD

**Issue by iondune** [go-gitea/gitea#11331]
- Gitea version (or commit ref): 1.12.0+dev-87-g665d7e91a
- Git version:
- Operating system: Ubuntu 18.04.3 LTS
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (https://try.gitea.io/api/v1/orgs/test_org_3333/repos)
  - [ ] No
  - [ ] Not relevant
- Log gist: https://gist.github.com/iondune/57330f7f5eb4f62b55992aab9b404d2b

## Description

I am having trouble using the POST `/orgs/<org_name>/repos` api endpoint. This is the response I'm getting (with http status 422):

```json
{"message":"org does not exist [id: 0, name: ]","url":"https://try.gitea.io/api/swagger"}
```

But if I switch to the deprecated `/org/<org_name>/repos` endpoint, it works just fine. It looks to me like the issue is that `CreateOrgRepo` is looking for the `:org` parameter [here](https://github.com/go-gitea/gitea/blob/master/routers/api/v1/repo/repo.go#L334) while the parameter in the route is named `:orgname` [here](https://github.com/go-gitea/gitea/blob/master/routers/api/v1/api.go#L861). The deprecated route is working because it uses `:org`.

**Comment by zeripath** [comment]
Fixed by #11339 and the breakout backport #11381
