### ISSUE TITLE
Keybase git encryption 

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#11337]
Is it possible to use end to end encryption for git repository provided by keybase ? (https://keybase.io/blog/encrypted-git-for-everyone)
If yes, how to do that? 

Thanks a lot in advance,

G.M

**Comment by SijmenSchoon** [comment]
I'm pretty sure keybase's git encryption is completely agnostic to the git hosting server. You can just stick any clone URL in there and it should work.

**Comment by lafriks** [comment]
This should be asked to keybase support
