### ISSUE TITLE
[Feature] [API] expose emoji convertion

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#11348]
#11032 added UTF-8 emoji support - add api to fully use this in clients

proposal: for **miscellaneous**

add `POST /emoji/utf` to convert an alias to utf
and `POST /emoji/alias` to get (first alias or alias list?)

idears and thoughts are welcome :)

**Comment by 6543** [comment]
modules/emoji/emoji.go has: 

https://github.com/mrsdizzie/gitea/blob/b09ec508c3f33e05d3784f96093451c463600d7b/modules/emoji/emoji.go#L77-L79

https://github.com/mrsdizzie/gitea/blob/b09ec508c3f33e05d3784f96093451c463600d7b/modules/emoji/emoji.go#L89-L92

https://github.com/mrsdizzie/gitea/blob/b09ec508c3f33e05d3784f96093451c463600d7b/modules/emoji/emoji.go#L106-L109

https://github.com/mrsdizzie/gitea/blob/b09ec508c3f33e05d3784f96093451c463600d7b/modules/emoji/emoji.go#L114-L116

**Comment by silverwind** [comment]
Can't clients just use a existing client-side library that does this conversation (which is mostly the same across libraries)?

**Comment by septatrix** [comment]
> Can't clients just use a existing client-side library that does this conversation (which is mostly the same across libraries)?

Yes I agree, AFAIK we use the aliases from the github gemoji gem or more specifialy the aliases from the included json file https://github.com/github/gemoji/blob/master/db/emoji.json. Using the JSON file to get the corresponding data is easy in most languages and should not require an extra API endpoint.

**Comment by 6543** [comment]
closed because clients can handle it itself ...
