### ISSUE TITLE
feature request : support octotree alike layout

### ISSUE THREAD

**Issue by laoshaw** [go-gitea/gitea#11344]
Is it remotely possible to have built-in support for features like https://www.octotree.io/ ?

octotree supports both github and gitlab, it's a for-profit company so it's impossible for them to consider gitea.

this feature makes browsing code super easy, considering we read more code than writing them these days, features like this will be a huge plus and can make gitea really stand out.

**Comment by wxiaoguang** [comment]
More details in
* https://github.com/go-gitea/gitea/issues/18192
