### ISSUE TITLE
Looking for help about webhooks

### ISSUE THREAD

**Issue by waset** [go-gitea/gitea#11351]
My English is not good.
I want to know why is it empty.
![image](https://user-images.githubusercontent.com/55943270/81464954-c28a9380-91f8-11ea-9b7a-0da587e89947.png)

**Comment by ZhangMingShuai** [comment]
There are modifications.
![image](https://user-images.githubusercontent.com/55943270/81465009-30cf5600-91f9-11ea-9e41-e874adceba08.png)
