### ISSUE TITLE
Rich text input fields are broken when using Google Gboard Keyboard on Android

### ISSUE THREAD

**Issue by antonsmetanin** [go-gitea/gitea#11352]
- Gitea version (or commit ref): 1.11.4
- Git version: N/A
- Operating system: N/A
- Database (use `[x]`): N/A
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (any issue page)
  - [ ] No
  - [ ] Not relevant
- Log gist:

- Android version: 6.0.1
- Chrome version: 77.0.3865.92
- Gboard version: 8.6.10.266015648-release-armeabi-v7a

## Description

Rich text input field used to write issue comments (and probably in other places, too) is broken when using Gboard. The entered text keeps getting copied over and over whenever you're typing new characters, deleting the old ones, or even just tapping somewhere else. This makes Gitea web interface pretty much unusable unless you switch to another keyboard.

## Screenshots

![20200509_142543](https://user-images.githubusercontent.com/5188942/81466026-48aed600-9209-11ea-89bf-5bc444f4bbe3.gif)

**Comment by silverwind** [comment]
SimpleMDE has a lot of issues, https://github.com/go-gitea/gitea/issues/10729 will eventually fix it.

**Comment by zeripath** [comment]
Press the last button in the toolbar - the plain black file button - it will turn off simple mde and revert to a simple textare

**Comment by antonsmetanin** [comment]
@zeripath Thanks, this helped. Still, I've read the linked issue, and I agree that SimpleMDE probably needs to be replaced.

**Comment by jswolf19** [comment]
I get a similar issue when using the file editor to create a new file. I'm using Windows 10's Japanese IME in Firefox, Gitea 1.12.2. The text becomes doubled for certain inputs. While Japanese doesn't seem to get duplicated, alphanumeric strings do.

**Comment by TheEvilSkeleton** [comment]
I get the same issue on Bromite (browser) and OpenBoard (keyboard).

**Comment by zeripath** [comment]
on the toolbar there is an icon in the far right click that to make SimpleMDE disappear and return to a simple textarea.

![Screenshot from 2020-08-06 18-07-31](https://user-images.githubusercontent.com/1824502/89560984-c6d24700-d80f-11ea-825e-38989c1d3ecd.png)

**Comment by corneliusroemer** [comment]
Why is the simple textarea not the default on mobile if SimpleMDE is so buggy on mobile?

**Comment by jolheiser** [comment]
> Why is the simple textarea not the default on mobile if SimpleMDE is so buggy on mobile?

There has not been a PR to introduce such a thing. You are welcome to make one. 🙂  

As you've noted in other issues, the long-term fix will ideally be #10729. Until that is accomplished, as noted by zeripath above there is a workaround.  
Regardless of whether that workaround is subjectively sufficient or not, none of us are paid to work on this project and so we cannot force anyone to take on the work.

**Comment by wxiaoguang** [comment]
Can you try it on https://try.gitea.io ? The editor is using contenteditable mode now.

**Comment by silverwind** [comment]
Fixed with https://github.com/go-gitea/gitea/pull/23876
