### ISSUE TITLE
Can't delete wiki page when master branch is protected

### ISSUE THREAD

**Issue by Tchoupinax** [go-gitea/gitea#11363]
- Gitea version (or commit ref):  1.11.5 
- Operating system: Docker image
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite

## Description

Hello,

I found an unexpected behaviour on my gitea instance, i can't delete a page if the master branch is protected.

I found a fix that was made for creation and write (https://github.com/go-gitea/gitea/pull/7580). Is it a bug or it is wanted that deletion is forbidden ? I do not think that repository protection could affect the wiki, but maybe it should.

Thank you :)

**Comment by lunny** [comment]
Cannot reproduce this on master b2c20b68a08e23bc952402a553d59a4613188bd0 .
