### ISSUE TITLE
Unexpected 302 redirect to /user/login when viewing raw image in repository

### ISSUE THREAD

**Issue by mappu** [go-gitea/gitea#11361]
- Gitea version (or commit ref): 1.11.4
- Git version: 2.24.1
- Operating system: Debian
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

I have a separately hosted webpage (say https://gitea-portfolio/), that embeds a lot of images from Gitea-hosted Git repositories (e.g. `<img>` tags with URLs of the form https://gitea-server/org/repo/raw/branch/master/doc/image0.png).

What I expected to see: When visiting https://gitea-portfolio/ all the images should load correctly

What I see in practice: Mostly these load correctly. But only sometimes, I will see broken images.

In this situation, checking the web inspector said this `/raw/` image URL returned a 302 to `/user/login` on the Gitea server.

I don't think I have any settings that would cause this to happen? And refreshing the separate webpage by F5 is usually enough to make this raw image URL load correctly.

I am not yet able to reproduce the issue with any tool like ab/hey, always a 200 response is given.

Is there maybe some race condition with refreshing cookies while making a lot of simultaneous image requests?

## Screenshots

![Screenshot_20200510_114551](https://user-images.githubusercontent.com/3959202/81487728-638a5480-92b4-11ea-8109-ed4291da9105.png)

**Comment by zeripath** [comment]
We would need to see some logs from Gitea when there is an unexpected 302. Otherwise we're really in the dark.

**Comment by mappu** [comment]
```plaintext
[Macaron] 2020-05-09 23:26:28: Started GET /org/repo/raw/branch/master/doc/image0.png for x.x.100.51
[Macaron] 2020-05-09 23:26:28: Completed GET /org/repo/raw/branch/master/doc/image0.png 200 OK in 4.498319ms
[Macaron] 2020-05-09 23:26:28: Started GET /user/login for x.x.100.51
[Macaron] 2020-05-09 23:26:28: Completed GET /user/login 302 Found in 5.1776ms
```

I'm also really in the dark. I think the next step is to check the source code for all the reasons why Gitea might 302 redirect to `/user/login`.
