### ISSUE TITLE
`words` and `lines` are not localized

### ISSUE THREAD

**Issue by alexanderadam** [go-gitea/gitea#11369]
- Gitea version (or commit ref): `1.12.0+dev-292-g742e26f5a`
- Can you reproduce the bug at https://try.gitea.io:

Yes, this is actually how I stumbled over it. I have some test repositories because of some previous bug reports and someone created a test issue — which I closed. Suddenly I saw that the activated locale was in german. So everything was in german _except_ "lines" and "words".

## Screenshots

![Screenshot_20200511_081224](https://user-images.githubusercontent.com/372620/81529483-36df4700-935f-11ea-8da1-44b4ca4f0a87.png)

**Comment by silverwind** [comment]
The english ones were updated in https://github.com/go-gitea/gitea/commit/28e5e7fcbca9cd2030c156ec45f6f3cf67b3682e, I guess Crowdin has not caught up yet?

**Comment by alexanderadam** [comment]
@silverwind ah, so should I rather use Crowdin instead of [the PR](https://github.com/go-gitea/gitea/pull/11370)?

**Comment by silverwind** [comment]
PR should be fine I guess. Maybe someone with a better understanding of Crowdin can comment how a case of updated english works. Given that you're seeing english, I think it invalidated all previous translations.

**Comment by alexanderadam** [comment]
@silverwind ah so @a1012112796 just wrote that I should rather use crowdin.

Also I wasn't able to find 'lines' and 'words'…

**Comment by silverwind** [comment]
Doing it on crowdin is certainly better and faster as translations don't require review.

**Comment by alexanderadam** [comment]
Okay, the first point is already translated (I update the issue accordingly) but which are the keys for `lines` and `words`?
It seems that there's no key for `words` and there's a key for `lines` but it isn't translated anyway.

**Comment by zeripath** [comment]
This is (yet another) SimpleMDE/Codemirror problem

**Comment by alexanderadam** [comment]
@zeripath so is there already an open issue for it? :thinking:

**Comment by silverwind** [comment]
I assume this is hardcoded in SimpleMDE, but fix will come with https://github.com/go-gitea/gitea/issues/10729.

**Comment by silverwind** [comment]
Fixed with https://github.com/go-gitea/gitea/pull/23876 which removes these from the default editor.
