### ISSUE TITLE
The timetracker will not be stop from a issue reference in the message of a PR

### ISSUE THREAD

**Issue by luwol03** [go-gitea/gitea#11374]
- Gitea version (or commit ref): 99082eebd76019fc608e44c4464da6398f51dccd = ~ v1.12.0 
- Git version: 2.20.1
- Operating system: Linux Debian Buster
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (https://try.gitea.io/luwol03/test/issues/1)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
the time tracker will be stoped, if I refer a issue in a pr commit message. But if I close a issue via refer it in a pr message it will not be closed!

## Screenshots
![image](https://user-images.githubusercontent.com/60048565/81560976-bcc8b580-9392-11ea-9d39-97004fd4170c.png)

**Comment by luwol03** [comment]
Thank you for fixing that bug. I appreciate your work.

**Comment by lunny** [comment]
Look like the backport is difficult. I will send another PR to v1.15
