### ISSUE TITLE
[Feature] [API] Add Endpoint for Branch creation

### ISSUE THREAD

**Issue by DominikPf** [go-gitea/gitea#11376]
We want to automatically create Dev-Stacks in our Company (new Application, Package, ....)

To create a Repository we want to create the complete basic structure.
The Api of Gitea is already very powerfull, but we also need an Endpoint to create a new Branch.

proposal for: **repository**

add `POST /repos/{owner}/{repo}/branches`

Information to create a new branch should be
- The Name of the new Branch
- The Name of the Branch the new Branch is based on

I hope i didn't forgot something

**Comment by lunny** [comment]
closed by #11607
