### ISSUE TITLE
Unable to register u2f key

### ISSUE THREAD

**Issue by a-jackson** [go-gitea/gitea#11371]
- Gitea version (or commit ref): 1.12.0+dev-292-g742e26f5a
- Can you reproduce the bug at https://try.gitea.io:
  - [ X ] Yes (provide example URL)
https://try.gitea.io/user/settings/security

## Description
I was unable to log in with my u2f security key, it would just redirect to the TOTP code option. I tried to register the key again and get the error shown below. 
Looking into the issue some I find that the message is wrong, it's a javascript error. The error message is `"$.post(...).success is not a function"` which seems to be referring to this .success [here ](https://github.com/go-gitea/gitea/blob/0396fcf4b54da7c5ff09908e23a16e96dea9cda4/web_src/js/index.js#L2291)

.success was deprecated in jquery 3 so that seems to be the problem.
...

## Screenshots
![image](https://user-images.githubusercontent.com/2199309/81536336-4791bc00-9363-11ea-8775-c245043da175.png)

**Comment by lafriks** [comment]
Duplicate of #11228
