### ISSUE TITLE
Corrupted download archives

### ISSUE THREAD

**Issue by japettyjohn** [go-gitea/gitea#11380]
- Gitea version (or commit ref): 1.11.3
- Git version: 2.11.0
- Operating system: 9.12
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

The API to download a zip/tgz archive does not cleanup the archive made in the case of an error. So while a 500 will result from the first attempt, all subsequent attempts on the same commit ID will get the corrupted file from the disk and a 200 OK. This is not addressed in [master (b7c82cd1a9)](https://github.com/go-gitea/gitea/blob/b7c82cd1a9ce4f863034a3a59312ff9402a8f72c/modules/git/commit_archive.go#L61) either. 

Reproducing this is a requires making the `git archive` command fail. In my case this was from a timeout.

## Screenshots

No UI elements involved.

**Comment by kevans91** [comment]
This can or will be alleviated by #11296, perhaps, which starts generating the archives off in tmpdir then quickly copying them over to their final location upon success.

**Comment by heindl-solutions** [comment]
timeout settings added in #6015 might help

**Comment by OzWookiee** [comment]
Can confirm I have this issue with the latest version of Gitea. We have a large repo but have limited the archive to a single directory with .gitattributes however the release archive creates a broken zip/tar of 580Mb when it should be around 1.7Gb

```
[git.timeout]
DEFAUlT = 720
MIGRATE = 1200
MIRROR = 600
CLONE = 600
PULL = 600
GC = 120
```
these changes to the app.ini have not had an impact on the archive creation.

**Comment by zeripath** [comment]
Please don't comment on closed issues - open a new one referring to the closed issue so that we get full information.

Gitea generates >100 notifications a day - commenting on closed issues is a good way to get ignored.
