### ISSUE TITLE
Specifying gitea server Gitea Base URL when it is normally accessed via SSH Local Port Forwarding?

### ISSUE THREAD

**Issue by leeand00** [go-gitea/gitea#11383]
On my gitea server, I normally access it via ssh Local Port Forwarding; and it isn't accessible from the outside because I bind it to the localhost address.

I'm accessing it from `http://127.0.0.1:8080` via "Local Port Forwarding", and it thinks that it's being accessed from `http://127.0.0.1:3000`; so certain features (the preview in the wiki and the issues for instance do not work (you can however save them, just not preview them); anyway it's mis-configured, see below, I'd like to change the `Gitea Base URL` so that anytime the server currently writes `http://127.0.0.1:3000` it will write `http://127.0.0.1:8080` instead (but that said, it would be good if it still operated off of port `3000`):

[![gitea configuration][1]][1]

What line in `gitea.ini` changes this functionality? or is it more like a situation where I need to throw a reverse proxy in front of it that rewrites the URLs for me?

  [1]: https://i.stack.imgur.com/nZ1zW.png

**Comment by zeripath** [comment]
You are essentially using your port forwarding as a reverse proxy. The correct setting to change would be `ROOT_URL` in the `[server]` section.

See https://docs.gitea.io/en-us/config-cheat-sheet/#server-server

In general for configuration queries using the forums or our discord is better.
