### ISSUE TITLE
[Question]How to compare two tag?

### ISSUE THREAD

**Issue by hisune** [go-gitea/gitea#11389]
How to compare two tag?

Similar to github

![image](https://user-images.githubusercontent.com/7941669/81696291-4a40fe00-9496-11ea-9475-aa814aa486cc.png)

**Comment by CirnoT** [comment]
There is no direct link at the moment but you can create link manually `/compare/{ref}...{ref}`

**Comment by hisune** [comment]
It would be much better if add a link

**Comment by hisune** [comment]
![image](https://user-images.githubusercontent.com/7941669/81794757-d5c19a00-953d-11ea-9e52-9bc0e4871b0c.png)

This one is also very user-friendly

**Comment by zeripath** [comment]
@hisune PRs are welcome.

**Comment by lafriks** [comment]
Still actual

**Comment by jtran** [comment]
Closed by #15695, scheduled for 1.15 release.
