### ISSUE TITLE
Git hooks are not being executed on Windows when running as a service

### ISSUE THREAD

**Issue by andreynering** [go-gitea/gitea#1139]
Similar to https://github.com/go-gitea/gitea/pull/736

When hooks call Gitea executable, it immediately stop because it conflicts with minwinsvc. If it's not running as service, it works normally.

Set env `SKIP_MINWINSVC=1` should work.

**Comment by lunny** [comment]
Should this be put to v1.1? Maybe we can move this to 1.2? @andreynering

**Comment by andreynering** [comment]
This was working before, I think we should really fix for v1.1

I'll try to fix later today, I think it's trivial.

Where are Git hooks located on source code and how can we update it on a migration?

**Comment by lunny** [comment]
See this PR https://github.com/go-gitea/gitea/pull/1006. We will wait for this issue to release 1.1 .
