### ISSUE TITLE
Translation process

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#114]
I have ever gave this idea on Gogs. Now I give it again.

I think we can develop a language editor UI on admin panel. It could simple, there are two columns, left is English, right is another, he can select one from the supported languages above right column.
Every line is a translate, left is english word, right is the special language. After finished the translation, he can save it. After that, he can go and look at the UI immediately. Of course, if he like, he can download the locale file and send a PR to gitea repo.

**Comment by strk** [comment]
Sounds like reinventing the wheel to me. This is what specialized translation code does.

**Comment by metalmatze** [comment]
I really like the idea if the tool is kept simple, yet I still don't know if that should be port of gitea.

**Comment by joubertredrat** [comment]
@lunny this Idea is good, but Gitea will lose standard among all installations, since the user will be able to customize your translations. With this, I think that will be more hard to we understand and solve possible issues about UI.

**Comment by lunny** [comment]
So we have to assign language tanslation maintainer for LGTM locale file PRs.

**Comment by joubertredrat** [comment]
@lunny Then I think that's the way it's better.

Option to change translations, a big alert stating that the layout may break if you do not use the feature with care and a resource displaying when local translation isn't default from Gitea.

Whit this I think we can avoid possible issues as this

"Problem with right menu #114"
"
Guys, my menu is bigger and ugly, I'm opening this issue to solve this
![screenshot-repo](https://cloud.githubusercontent.com/assets/1520407/20097193/59d9c666-a594-11e6-8977-0634c9cd4856.png)

"

**Comment by joubertredrat** [comment]
@lunny ah, other problem, will be more easy to use translation on admin to XSS, because current translations have some html elements. A not a nice person can put similar to `<script>getMy(document.cookie)</script>` as example. On specialized tools is more easy to translate and manager translations to avoid this problems.

**Comment by lunny** [comment]
Hi, I think that's great! Users should control the size of name themselves.

**Comment by joubertredrat** [comment]
When ins't defined this question, isn't good idea at least change manually on files from `Gogs` to `Gitea` for first release?

**Comment by bkcsoft** [comment]
My take on this is more related to backend than frontend.

Keep all translation-files in a separate repo (subtree for pulling into Gitea).
Pros:
- Each new translation-update can be done as a separate branch, without having to rebase on gitea-updates every 5 minutes.
- Each branch can be spun up as a separate container on gitea.io for easy testing (e.g. new_branch.translate.gitea.io)
- If new translations are added in en_US on master, you can easily rebase without having to update Gitea (less error prone at least)
- Translation-tools that speak git (e.g. [Weblate](https://docs.weblate.org/en/latest/vcs.html#git) ) can be used without fscking around with the gitea history

Cons:
- Someone has to merge the translations back into Gitea when they are mainlined :trollface:

Feel free to pitch in on pros/cons for this, as this list is very biased and I can't really find any cons :confused:

**Comment by tboerger** [comment]
Maybe we should also use a more mature format like gettext? :)

**Comment by joubertredrat** [comment]
@tboerger we need a colaborative platform to be easy to any Gitea collaborator help and we manage, like [Weblate](https://weblate.org/), [Pootle](http://pootle.translatehouse.org/) and [Zanata](http://zanata.org) or Crowdin.

**Comment by lunny** [comment]
I remember @tboerger has sent a request to Weblate?

**Comment by lunny** [comment]
https://weblate.org/en/hosting/ @tboerger has you apply on this?

**Comment by strk** [comment]
On Thu, Jan 05, 2017 at 07:06:02PM -0800, Lunny Xiao wrote:
> https://weblate.org/en/hosting/ @tboerger has you apply on this?

I've made a request but never got an answer.
Never deployed it either so dunno how hard or easy it would be.

**Comment by Bwko** [comment]
We could host weblate on our [own server](https://github.com/WeblateOrg/weblate/)

**Comment by joubertredrat** [comment]
Hi guys,

I can host on my servers too.


--
"O que quer que você faça na vida, será insignificante. Mas é muito
importante que você o faça... por que ninguém mais o fará." Gandhi
"Whatever you do will be insignificant, but it is very important that you
do it... because no one else will it." Gandhi
___________________________________________________________________
*Joubert "RedRat"* - Consultor em tecnologia - Technology consultant
/me at Linkedin <http://br.linkedin.com/in/joubertredrat/> and Github
<https://github.com/joubertredrat/>
*~(,,">* RedRat Consultoria


2017-01-08 7:54 GMT-02:00 Bwko <notifications@github.com>:

**Comment by lunny** [comment]
If we cannot received the response some days, we could consider host it on our server.

**Comment by joubertredrat** [comment]
This sound suggestive :+1: 

https://github.com/anthonynsimon/parrot

**Comment by metalmatze** [comment]
It was already discussed and proposed, so yes. Considering it.

**Comment by lunny** [comment]
So let's setup parrot and close this issue? @tboerger @bkcsoft any idea?

**Comment by tboerger** [comment]
Parrot doesn't support the ini format, so we most use weblate or something else

**Comment by bkcsoft** [comment]
@tboerger Are you sure it doesn't?

**Comment by tboerger** [comment]
> @tboerger Are you sure it doesn't?

Yes, I'm sure: https://github.com/anthonynsimon/parrot/tree/master/parrot-api/export

**Comment by lunny** [comment]
It seems the interface is simple so that we can write an ini one using the same library with Gitea's configuration using.

**Comment by tboerger** [comment]
> It seems the interface is simple so that we can write an ini one using the same library with Gitea's configuration using.

That sounds good, so somebody should do that and we will see how long it takes to get accepted. But beside that I personally prefer MariaDB, this supports only PostgreSQL.

**Comment by lunny** [comment]
And maybe we should move this to v1.2?

**Comment by tboerger** [comment]
Parrot is pretty chaotic to setup, weblate doesn't directly support the ini format, so I have requested an OSS project on Crowdin and it have already been approved: https://crowdin.com/project/gitea

**Comment by lunny** [comment]
Does crowdin has an API?

**Comment by tboerger** [comment]
Of course it got

**Comment by lunny** [comment]
So how should we copy TRANSLATION back to this repository?

**Comment by bkcsoft** [comment]
I'll look at integrating this during the weekend.

Seems like I need 2 commands, push and pull.
### push
- on merge `master` check if translations are updated
- upload to CrowdIn

### pull
- check if translations have been updated
- pull changes from CrowdIn
- add, commit, push, create PR (why of course, nothing gets in w/o reviews 😂 )

**Comment by bkcsoft** [comment]
further extension on `push` is if a translation other than en_US is changed
- pull
- apply change
- if no merge-conflicts, add,commit,merge,PR

**Comment by bkcsoft** [comment]
I probably won't have time to check this in the near future
