### ISSUE TITLE
[Question] Allowed environment variables when using docker

### ISSUE THREAD

**Issue by lonix1** [go-gitea/gitea#11407]
The [docs say](https://docs.gitea.io/en-us/install-with-docker/#environments-variables)
> You can configure some of Gitea’s settings via environment variables
...

I assume that means that ONLY those in that list can be set via docker. The rest must be set in the `app.ini`.

Is that correct?

(Because I noticed different behavior. I wonder whether the above is wrong, or my config is wrong.)

**Comment by zeripath** [comment]
The documentation on the website refers to the latest master version of Gitea and should be correct for those. If you are not using master, take a look at the docs for that version from their source code.

If you look at https://github.com/go-gitea/gitea/blob/master/docker/root/etc/s6/gitea/setup and https://github.com/go-gitea/gitea/blob/master/docker/root/etc/s6/openssh/setup you should be able to see how the environment variables are converted.

There is a contributed command within contrib called [environment-to-ini](https://github.com/go-gitea/gitea/tree/master/contrib/environment-to-ini) that would allow you to set any app.ini setting from the environment.

**Comment by lonix1** [comment]
Thank you @zeripath that was indeed the problem!
