### ISSUE TITLE
Add the ability to set default reviewers per project for new pull requests

### ISSUE THREAD

**Issue by akostin33** [go-gitea/gitea#11403]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [x] PostgreSQL
  - [x] MySQL
  - [x] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

The same functionality as bitbucket has:
https://confluence.atlassian.com/bitbucketserver/add-default-reviewers-to-pull-requests-834221295.html

**Comment by lakostin** [comment]
How to re-open it?

**Comment by kokarn** [comment]
This would indeed be very handy

**Comment by cp-logan** [comment]
Has there been any progress on this in the last year?  We're trying to migrate off of BitBucket Cloud, and this is the only feature that's a blocker for my team.

**Comment by ksa-real** [comment]
Can this be implemented via hooks? I feel a mechanism for webhooks should be expanded allowing synchronous responses for UI integration. I.e. Gitea could call webhook and get back a list of reviewers (team/users) which are instantly displayed in Gitea UI and look like a native Gitea feature. This would allow a more advanced use cases like load-balancing the reviewers, OWNERS files parsing, or "Smart AI" reviewers selection.

**Comment by neszt** [comment]
+1 vote, it would be a very nice feature!

**Comment by makar112233** [comment]
+1

**Comment by promiteyka** [comment]
+1 vote

**Comment by amix307** [comment]
+1

**Comment by delvh** [comment]
Doesn't this already exist now that `CODEOWNERS` have been added?

**Comment by lunny** [comment]
> Doesn't this already exist now that `CODEOWNERS` have been added?

Yes, I think this could be closed.  https://docs.gitea.com/usage/code-owners

**Comment by ksa-real** [comment]
Is there any documentation on how CODEOWNERS file affects pull requests?

**Comment by lunny** [comment]
Once the pull request's changed files matched the code owners' regex rules, the users will be set as reviewers when creating the pull request. A documentation is preferred.

**Comment by makar112233** [comment]
@lunny could you give, please, an example of .CODEOWNERS file with the rule "check any code changes"?

**Comment by lunny** [comment]
https://gitea.com/lunny/codeowner-example/src/branch/main/.gitea/CODEOWNERS and you can also send a PR as a test.

**Comment by ksa-real** [comment]
I guess it just follows whatever Github's CODEOWNERS file is doing:
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners

For format we can look into ParseCodeOwnersLine function at the moment

**Comment by neszt** [comment]
> https://gitea.com/lunny/codeowner-example/src/branch/main/.gitea/CODEOWNERS and you can also send a PR as a test.

I tried with `*.* @user` as in your example and with `.* @user` as in the documentation (regexp), neither of them worked (gitea version 1.20.3).

In your `lunny/codeowner-example` repo, I can't create a PR or create a branch.
