### ISSUE TITLE
Make Issues list more like GitHub's

### ISSUE THREAD

**Issue by Fastidious** [go-gitea/gitea#1141]
- Gitea version (or commit ref): `N/A`
- Git version: `N/A`
- Operating system: `N/A`
- Database (use `[x]`): `N/A`
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL) `N/A`
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

The `Issues` page should be made to look more like GitHub’s. As it is right now, it sticks like a sore thumb to the rest of the application (). Since `gitea`, just like `gogs`, are modelled after GitHub, why stop half way? 

Compare Gitea's:

![screen shot 2017-03-07 at 07 29 06](https://cloud.githubusercontent.com/assets/8352292/23656467/d91efd3a-0307-11e7-984c-2a55532870ac.png)

To GitHub’s:

![screen shot 2017-03-07 at 07 29 17](https://cloud.githubusercontent.com/assets/8352292/23656486/ed81b0a6-0307-11e7-8ad0-e6098b4400b2.png)

**Comment by moltam** [comment]
I don't know if you guys are aware of this, but [an exact clone could be problematic](http://gitbucket.github.io/gitbucket-news/gitbucket/2016/03/20/change-user-interface.html).

**Comment by lesderid** [comment]
@moltam That doesn't seem like a valid reason not to do it.

**Comment by moltam** [comment]
@lesderid I am not against it. Just wanted to share this, to make sure gitea stays different enough from github (as it is now).

**Comment by bkcsoft** [comment]
@Fastidious as @moltam pointed out, making an exact clone has legal implications. Also while the design is borrowed from GitHub, Gitea is not a straight up clone of GitHub, there will be subtle (or not so subtle) differences here and there 🙂

**Comment by a1012112796** [comment]
Hello, I think maybe we can try to implement #10864 first.
