### ISSUE TITLE
[Feature Request] Hide issuecomment events

### ISSUE THREAD

**Issue by lonix1** [go-gitea/gitea#11418]
These are the issuecomment events:

![image](https://user-images.githubusercontent.com/40320097/82040716-5223bc80-96a7-11ea-8526-095a87c824a6.png)

They look like this: `<div class="event" id="issuecomment-1">...</div>`

When working alone, or in a small team, these only add noise and aren't that useful.

It would be nice to have an option to hide them.

**Comment by lunny** [comment]
I think merge issue labels comment events is better. And there is already an issue to describe it.

**Comment by lonix1** [comment]
@lunny What is "merge issue comments"?

**Comment by lunny** [comment]
I mean when you create serval labels for one issue, we could just display one label comment.

**Comment by 6543** [comment]
> I mean when you create serval labels for one issue, we could just display one label comment.

done in  #13304 :tada:  - but I'll leave it open since this propose "hide all event comments"

**Comment by lonix1** [comment]
Agreed it would be nice to "hide all" - when working alone on a project, those badges don't add value.

**Comment by lunny** [comment]
I think those labels events have been grouped into one. duplicated #13268 and resolved by #13304.

**Comment by lonix1** [comment]
I think it's much nicer to have an option to hide them completely (good when working alone). But the grouping feature is a very good alternative for now. Thanks.

**Comment by wxiaoguang** [comment]
Yes, the PR is in progress:
* https://github.com/go-gitea/gitea/pull/17414

Almost done.
