### ISSUE TITLE
Manage SSH keys will accept DSA keys even if opensshd is refusing them

### ISSUE THREAD

**Issue by bjj** [go-gitea/gitea#11417]
- Gitea version (or commit ref):  1.12.0+dev-320-g4a04740da (docker image d0d4dd915d2e)
- Git version:
- Operating system: Docker on a Synology NAS
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
There is no warning if you click "Add Key" and add a valid DSA public key to your account when openssh will not accept it (that has been the default since 7.0). The result is the usual "Permission denied (publickey)" although if you ssh -v you see "not in PubkeyAcceptedKeyTypes".

**Comment by CirnoT** [comment]
This can be configured in config https://github.com/go-gitea/gitea/blob/master/custom/conf/app.ini.sample#L345
Perhaps we should consider updating defaults if that is the case however?

**Comment by bjj** [comment]
The `app.ini.sample` says `Define allowed algorithms and their minimum key length (use -1 to disable a type)`  but the code actually merges the config array with a default value ignoring -1:

	SSH.MinimumKeySizeCheck = sec.Key("MINIMUM_KEY_SIZE_CHECK").MustBool()
	minimumKeySizes := Cfg.Section("ssh.minimum_key_sizes").Keys()
	for _, key := range minimumKeySizes {
		if key.MustInt() != -1 {
			SSH.MinimumKeySizes[strings.ToLower(key.Name())] = key.MustInt()
		}
	}

The default value includes all key types: `MinimumKeySizes:    map[string]int{"ed25519": 256, "ecdsa": 256, "rsa": 2048, "dsa": 1024},` so it cannot be disabled with -1 as described.

I set it to 99999, which works, but gives this error: `Can not verify your SSH key: key length is not enough: got 1024, needs 99999`

**Comment by zeripath** [comment]
The best solution would be if you can find a command which will allow us to query the running sshd server to check whether it would accept a key.

**Comment by zeripath** [comment]
@bjj that looks like (yet another bug) do you fancy putting up a PR to fix that?

**Comment by zeripath** [comment]
Having looked at this I really don't think there is a way to get OpenSSHD to tell us if it would accept a public key or not. I would be delighted to be proven incorrect but this is therefore a configuration issue. 

If your server won't accept DSA keys or any other type of key you need to configure Gitea to refuse them.

**Comment by bjj** [comment]
The config is part of the docker image?! https://github.com/go-gitea/gitea/blob/master/docker/root/etc/templates/sshd_config

**Comment by zeripath** [comment]
Then that's different, put a pr to change the default in the docker - the file is docker/root/etc/templates/app.ini.

The information to set this is in:

https://docs.gitea.io/en-us/config-cheat-sheet/#ssh-minimum-key-sizes-sshminimum_key_sizes

**Comment by zeripath** [comment]
Here you, here's the patch:

```patch
diff --git a/docker/root/etc/templates/app.ini b/docker/root/etc/templates/app.ini
index 9b23c1270..1ca15e99c 100644
--- a/docker/root/etc/templates/app.ini
+++ b/docker/root/etc/templates/app.ini
@@ -53,3 +53,6 @@ SECRET_KEY   = $SECRET_KEY
 [service]
 DISABLE_REGISTRATION = $DISABLE_REGISTRATION
 REQUIRE_SIGNIN_VIEW  = $REQUIRE_SIGNIN_VIEW
+
+[ssh.minimum_key_sizes]
+DSA=-1
```
