### ISSUE TITLE
Deleting issue comment does not hide it until page reload

### ISSUE THREAD

**Issue by silverwind** [go-gitea/gitea#11422]
When deleting a issue comment, it stays visible after the deletion and only disappears on page reload.

**Comment by CirnoT** [comment]
Can not reproduce, are you sure you tested it on current `master`? Specifically after this commit https://github.com/go-gitea/gitea/commit/a4c7ad99e54d0835f759199599a8dcd6f5d7e90e

**Comment by silverwind** [comment]
Indeed, that was it!
