### ISSUE TITLE
Generate a sitemap for SEO

### ISSUE THREAD

**Issue by Zocker1999NET** [go-gitea/gitea#11429]
Gitea could generate a sitemap for SEO, so crawlers can search through public repositories more easily. It could be useful for some admins that their instances will be crawled and ranked by search engines. A good explanation for the format of `sitemap.xml` can be found on [Wikipedia](https://en.wikipedia.org/wiki/Sitemaps).

In my opinion this feature should do the following:
- The sitemap should be available at the path `/sitemap.xml`.
- The sitemap should at least list the main page of each public repository and group. The main page of the wiki's / all wiki's pages could be optional.
- `lastmod` should be the date of the last commit to the README file / the wiki page itself

**Comment by lafriks** [comment]
For big instances that would be large file

**Comment by Zocker1999NET** [comment]
@lafriks Yeah, that's right. Because of the size of the sitemap, this feature should be optional and disabled by default. Also a good caching system needs to be implemented, so that a few accesses to the sitemap does not overload the server.

**Comment by lunny** [comment]
If site didn't enable always login, then all public repositories' public routers could be generated to the sitemap file.

**Comment by turbopixel** [comment]
A sitemap with public repositories, profiles and organizations should suffice. Without any limitation, the sitemap will explode in size.

**Comment by Zocker1999NET** [comment]
Also, the sitemap could be limited by an additional setting defining that the sitemap only contains the N repositories with the newest changes.

**Comment by sijanec** [comment]
An alternative would be a sitemap per repository and per user. And of course a global sitemap, as sitemaps can be recursive and may specify additional sitemap files.

They could be generated dynamically.

**Comment by techknowlogick** [comment]
> may specify additional sitemap files.

An example of a sitemap that references other sitemaps: https://www.google.com/sitemap.xml
