### ISSUE TITLE
Markdown READMEs with hard line breaks aren't reflowed and look slightly ugly

### ISSUE THREAD

**Issue by thombles** [go-gitea/gitea#11434]
- Gitea version (or commit ref): 1.12.0+dev-325-gc48341918
- Git version: git version 2.20.1
- Operating system: Debian 10.4
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL): **[https://try.gitea.io/thombles/markdowntest/src/branch/master/README.md](https://try.gitea.io/thombles/markdowntest/src/branch/master/README.md)**
  - [ ] No
  - [ ] Not relevant

## Description

If you have a markdown file that is wrapped to 80 characters then those lines are not reflowed. In the case of regular text this just looks a bit ragged, however if there is significant markup such as an embedded URL then it really messes with the flow of the text.

**Expected behaviour:** Lines separated by a single line break in the markdown source would be kept on the same line in HTML. You would need to add two spaces to the end of the line to force a line break.

**Actual behaviour:** Line breaks are passed through directly.

## Screenshots

![Screenshot_20200516_213704](https://user-images.githubusercontent.com/5511175/82118908-7d98cb00-97bd-11ea-9d5a-b0ffd185a55c.png)

**Comment by zeripath** [comment]
See: https://docs.gitea.io/en-us/config-cheat-sheet/#markdown-markdown

``ini
[markdown]
ENABLE_HARD_LINE_BREAK = false
```

**Comment by thombles** [comment]
Aha thanks very much, that works great! It didn't occur to me that it might be intentional.
