### ISSUE TITLE
Signing in with OAuth2 does not really sign  you in until you click on it again

### ISSUE THREAD

**Issue by strk** [go-gitea/gitea#1144]
- Gitea version (or commit ref): 7ed00b6e8d571ab8efc99aa69d545cce609dd900
- Can you reproduce the bug at https://try.gitea.io:
  - [x ] Yes

## Description

When you sign-in using GitHub the very first time you are asked to "register".
Upon registering, you are redirected to login again and there you have to click on "sign-in via GitHub" again. I think it would make more sense to directly being logged in, unless email confirmation is enabled.

\cc @willemvd

**Comment by lunny** [comment]
~I think this is not a question and should be closed.~

**Comment by strk** [comment]
"not a question" ? It's a report of a weird behavior. I'm "signing in", using OAuth2, why am I not being signed in ? (now there are two questions :)

**Comment by lunny** [comment]
OK. We need a PR.

**Comment by strk** [comment]
Hopefully the `OAuth2` author would provide it. @willemvd do you have time for this ?
