### ISSUE TITLE
[Feature Request] Import labels from another repository

### ISSUE THREAD

**Issue by lonix1** [go-gitea/gitea#11454]
## Problem
Many repos are very similar, with similar or identical labels.

But recreating labels in each one is time consuming.

An option is to use the [custom labels](https://docs.gitea.io/en-us/customizing-gitea/#labels) feature, but that isn't user friendly, and doesn't help when there are many repos with many labels which change often.

## Solution
Please consider adding an "import labels" feature.

Workflow:
- assuming I have admin rights for a repo
- open repo
- click "import labels" dropdown (similar to "use label set" feature on labels page)
- select another repo
- all that other repo's labels (which don't exist in current repo) are imported

**Comment by 6543** [comment]
I think you could use org-wide labels, also if you use `tea labels --save labels; tea labels create --file labels` can do the job

So in my opinion I wont need this - but others do perhaps ... :)

**Comment by lonix1** [comment]
@6543 Thanks I didn't know about that option! Very useful for my needs.

However in defence of my proposal:
- Much easier
- Available to non-admin users who can't administer gitea from the shell

**Comment by lunny** [comment]
@lonix1 Another better solution is to create a template repository. See https://docs.gitea.io/en-us/template-repositories/ And I think this issue could be closed.
