### ISSUE TITLE
Upgrade to 1.11.4 now shows 500 error on repos but no repo health check errors from ui

### ISSUE THREAD

**Issue by sachin-gupta** [go-gitea/gitea#11452]
- Gitea version (or commit ref): 1.11.4, and 1.11.5
- Git version: 2.24.0.windows.2
- Operating system: Win 10 (x64)
- Database (use `[x]`): SQLite3
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

```
2020/05/17 13:45:56 ...ules/context/repo.go:745:func1() [E] GetCommitsCount: exit status 128 - fatal: bad object f5c7120af8488d04255b3e4492f4fb214d80b6ff
```

## Description

As i replaced gitea vith v1.11.4 some repo not shown instead 500 error on screem with above log for those repo _(issue remains with using 1.11.5 and also comes back on replacing older exe)_

When ran garbage collect or repository health check from dashboard no error is returned. Is there any command line to recover from folder "project.git" or a fix. Am in bad soup now :( as 20+ repo are gone. This error is on desktop, there was no disk faliure just happened on runtine version before 1.114 was fine.

## Screenshots

Standard 500 screen of gitea

**Comment by lunny** [comment]
Roll back to an old v1.11.x version work for you now?

**Comment by sachin-gupta** [comment]
I've downgraded back 1.10.2 and few other versions same issue - Ahh!
