### ISSUE TITLE
 [Feature Request] Remove LFS files which are not used by any repository

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#11478]
- Gitea version (or commit ref): 1.11.5
- Git version: Not relevant
- Operating system: Not relevant
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist: Not relevant

## Description

It would be great if gitea can provide something like a LFS clean up button that can remove LFS files from the `/git/lfs` folder which are not used by any repository

**Comment by zeripath** [comment]
There literally shouldn't be any in there that don't belong to repositories... They can't get in without being associated with a repoid and should be deleted with repo deletion. I suppose a doctor command could check if there's any which don't have an associated repoid quite easily.

If your Gitea dates from pre 1.8 I seriously suggest you double check that all the files are properly associated. I had to fix a critical issue with pointer files losing their associated LFS objects.

Again a doctor command could do this - but it could be very slow on large repositories.

**Comment by simon-on-gh** [comment]
Get it. Thanks!
