### ISSUE TITLE
[Bug] REPO_INDEXER doesn't index mirrored repository, even if the NotifySyncPushCommits is called

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#11479]
- Gitea version (or commit ref): 1.11.5
- Git version: Not relevant
- Operating system: docker image
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist: Not relevant

## Description

Looks like #11200 wasn't a fix to this bug. 

Can we trigger the indexing manually on a selected repository? Or is it possible to call ``NotifyPushCommits`` manually form GUI, or via some command-line?
https://github.com/go-gitea/gitea/blob/310699bca71f15cc7b46363800574ba6e74d8c5c/modules/notification/indexer/indexer.go#L126

**Comment by zeripath** [comment]
Please could you check on master/1.12 if the current fix is sufficient.

Things in the indexer changed quite a between those two.

**Comment by simon-on-gh** [comment]
Current master can't be built, it seems. Is there any build artifacts for 1.12?

**Comment by techknowlogick** [comment]
Current master can be found here: https://dl.gitea.io/gitea/master/

**Comment by simon-on-gh** [comment]
@techknowlogick Thanks!
I have just tried the artifacts, and it seems that the bug persists. 
It's a bit strange that it only happens to the mirrored repos, and the indexing of normal repos aren't influenced.

**Comment by simon-on-gh** [comment]
@zeripath is there anything like "gitea doctor" for repo indexes?

**Comment by simon-on-gh** [comment]
Any update on this?

**Comment by simon-on-gh** [comment]
solved
