### ISSUE TITLE
Mass import existing repositories from file system

### ISSUE THREAD

**Issue by replay111** [go-gitea/gitea#11473]
- Gitea version (or commit ref): 1.11.5
- Git version: 2.26.x
- Operating system: Centos 7
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
Hi - I was asking about this functionality soooome time ago, but suggestion to use "migration" is quite difficult to me.
My case is: I have main repo hosted on gitlab.com - but it is replicated locally to server (git clone --mirror). So when I have it locally I wanted to run some nice interface to be able to use it locall but without changes. All changes and review done by developers have to go to public repository. 
I was using for some time gitlab as "let's say" read-only interface localy. But this solution is have, veeery heavy, and I wonder if there is possibility to use gitea for such case.

I just need to start gitea and expose about 500 git projects. Thing is I dont want to change anything inside clonned repository I just want to read them from disk and show on the interface, and also I do not want to do that manually (first: more than 500 is a quite a lot of work, second: if new repo appear on gitlab.com I will have to add it manually - I prefer more automatic way)

So I am just asking if gitea offer some nice/neat sollution for such case :D

**Comment by replay111** [comment]
yes - for me is still valid as I did not get any useful information

**Comment by zeripath** [comment]
I guess you want some way of Gitea automatically adopting repositories that are in its repositories filesystem.

When do you think Gitea should offer to adopt these?

We can't do it on install because we don't have users for these repos. We'd have to offer to create a series of users too?

Should we do it on user creation? What permissions should the repository then get? I guess private?

Should we do it on repository creation? Well I guess that would be one option ?

Maybe it should be a command line option?

**Comment by replay111** [comment]
Hi,
I was using gitlab - and there was commands like

for importing all repos as a private, available for root/admin user:
```bash
gitlab-rake gitlab:import:repos['/path/to/repo']
```

Granting all access to all users in gitlab:
```
gitlab-rake gitlab:import:all_users_to_all_projects
```

I was using gitlab as a interface to backuped repositories (different sources). But now it becomes so heavy solution that I want to change it to something fast, light and with nice interface - like gitea ;-)

I was wondering if it would be possible to add param for gitea bin file like:

gitea crate-repo-from-fs "/path/on/fs"

so it could update app.conf file with proper path, and create all repositoies based on filesystem structure.
I would be also great feature just in case if something would go wrong with server. For restoring repo backups without having buckup of gitea bin files

I hope you unterstood my point 👍

**Comment by zeripath** [comment]
Yeah I understand. I think this is likely to become a tea command tbh rather than a gitea command per se.

The first step is to allow adoption of repositories that are already present: #12409 is the first step in doing that.

**Comment by replay111** [comment]
OK - but if I will start right now gitea with repo on filesystem-  will it be added to database and gitea will be aware of it? Or still I need to take some action to add this repo from file system so gitea could interact with it?

**Comment by zeripath** [comment]
Er... #12409 is not merged yet, but yes even when it is merged you would still need to do something.

Mostly because you need to decide which are users and which are organizations, and which repos are public or private and so on.

The above is not determined by the filesystem.

**Comment by replay111** [comment]
Yes - it is not merged. But I was curious if it will be enough. Regarding user and permissions I would assume 2 approaches:

1. import as a private repos and add full permission only to admin user

2. pass visibility and ownership for (all) imported repos with cmd smth like:
```bash
tea import-from-fs --user=replay111 --visibility=public 
```

but this is just I see this - I am not developer, didn't see the code co for me it is easy to define all this above - but how it looks like from your perspective probably looks different.

**Comment by replay111** [comment]
Hi,

will it be this feature implemented? Do you knows any ETA for this?
I am not trying to speed you up..., just asking ;-)

**Comment by jolheiser** [comment]
This is (at least partially) covered by #12920, which will be in 1.13

**Comment by replay111** [comment]
as this is covered partially then why closing it?
