### ISSUE TITLE
Provide full width split diff in Pull Request/Files Changed tab

### ISSUE THREAD

**Issue by KangoV** [go-gitea/gitea#1148]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

When viewing the files changed in a PR the split view does not resize full width. When viewing a commit it does. I've provided some screenies:

### Split View in PR

![image](https://cloud.githubusercontent.com/assets/3931807/23710874/14968fa4-0416-11e7-8bf7-bd9b9d7000d2.png)

### Split View in Commit

![image](https://cloud.githubusercontent.com/assets/3931807/23710983/6edfb9cc-0416-11e7-8624-003c07809a00.png)

**Comment by BhaaLseN** [comment]
The commit diff already does this for split view, but the Pull Request still doesn't. IMO thats the more important location to have this.

**Comment by lunny** [comment]
@internalfx could you send a PR? or you can paste your changes.

**Comment by mrsdizzie** [comment]
fixed in  #8114
