### ISSUE TITLE
gitea.com New Migration appears to have a hidden limit

### ISSUE THREAD

**Issue by ssb22** [go-gitea/gitea#11495]
As my first experiment with Gitea, I tried to mirror some of my public repositories from https://github.com/ssb22 to https://gitea.com/ssb22/.

I used the "New Migration" tool to create mirrors for about 10 of my public repositories, but the only one that persisted was the first one I mirrored (CedPane).  The other repositories got stuck on the tea-cup animation and later went to "404" pages.

I was unable to find anything obvious to tell me why this happened.  Perhaps I went over a limit (number of repositories? number of mirrors? number of new ones per day? total size?), but nothing told me what limit that was, so I'm none the wiser.

**Comment by zeripath** [comment]
It's probably a timeout.

https://docs.gitea.io/en-us/config-cheat-sheet/#git---timeout-settings-gittimeout

**Comment by ssb22** [comment]
Thanks.  It would be nice to have an email notification when a timeout happens, so we know that's what it was.

Today I tried to mirror just one repository, `adjuster`, which GitHub says is considerably smaller than the successfully-mirrored `CedPane` repository (GitHub says adjuster=3.08M and CedPane=11.1M).  After the teacup animation had played for over an hour, I noticed the message `Migrating from https://github.com/ssb22/adjuster failed.` had appeared below it.  (No reason was stated.  And since the teacup animation was still playing, the message below it could easily have gone unnoticed; replacing the animation with the message might be better.  Additionally, if navigating away from that page and reloading it later, I get only a 404 and nothing else, and neither do I get any email, neither in my inbox nor in the spam.)

If it *is* a timeout, then I don't understand why an 11.1M repository from GitHub successfully mirrors but smaller repositories repeatedly fail.  Is the connectivity between GitHub and Gitea that intermittent?  Alternatively it might be some other root cause.

**Comment by zeripath** [comment]
PRs are welcome.

**Comment by lunny** [comment]
@ssb22 Please fire an issue on https://gitea.com/gitea/gitea.com/issues

**Comment by ssb22** [comment]
The GitHub-Gitea connections seem to be working better today: I was able to mirror 23 more of my repositories (24 in total), one at a time, without hitting the timeout issue (although sometimes pages did take a while to load).
