### ISSUE TITLE
Gitea doesn't handle newline ('\n') in file specified by INTERNAL_TOKEN_URI

### ISSUE THREAD

**Issue by paradon** [go-gitea/gitea#11498]
- Gitea version (or commit ref): 1.11.5
- Git version: 2.24.1
- Operating system: Docker
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist: https://gist.github.com/paradon/c48ab42740c8731b625313cf9d66e41c

## Description
If the content in the file referenced by INTERNAL_TOKEN_URI ends with a newline, all commits fail with an internal server error.

As `gitea generate secret` appends a newline to its output, this means that, (where app.ini contains `INTERNAL_TOKEN_URI = file:/data/gitea/conf/internal-token`), generating this file as below will cause this error:

```
gitea generate secret INTERNAL_TOKEN >/data/gitea/conf/internal-token
```

## Screenshots
![image](https://user-images.githubusercontent.com/31676142/82269096-b0f97680-99c4-11ea-8b1e-311ed45f2118.png)

**Comment by zeripath** [comment]
I also note that this uses ioutil.ReadAll which will not work on Symlinks...
