### ISSUE TITLE
Show commit js bug

### ISSUE THREAD

**Issue by FalconWu2017** [go-gitea/gitea#11518]
gitea:1.11.5
chrome:80.0.3987.163

![bug](https://user-images.githubusercontent.com/34147999/82393012-d6938800-9a77-11ea-82ce-7bcdf6c64b1c.png)

**Comment by silverwind** [comment]
Need to backport part of https://github.com/go-gitea/gitea/commit/fd094eea959a235654b7591da066dcbbee11fc25.
