### ISSUE TITLE
Wrong links for breadcrumbs in edit file view

### ISSUE THREAD

**Issue by pgaskin** [go-gitea/gitea#1151]
- Gitea version (or commit ref): 5d40db6
- Git version: 2.9.3
- Operating system: Ubuntu 16.10
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes (Just edit any file more than 1 directory deep)
  - [ ] No
  - [ ] Not relevant
- Log gist: Not relevant

## Description

The breadcrumb links on the edit file view are invalid. See the example below.

Example:

````
   Link Text: TestRepo                                       / Folder1                                               / Folder2
    Link URL: http://localhost/geek1011/TestRepo/src/master    http://localhost/geek1011/TestRepo/src/master/Folder1   http://localhost/geek1011/TestRepo/src/master/Folder2
Expected URL: http://localhost/geek1011/TestRepo/src/master    http://localhost/geek1011/TestRepo/src/master/Folder1   http://localhost/geek1011/TestRepo/src/master/Folder1/Folder2
````

**Comment by pgaskin** [comment]
This does not happen when you put a slash in the textbox, it is only on the initial render of the page.

**Comment by ghost** [comment]
I posted the [same issue](https://github.com/gogits/gogs/issues/3859) on Gogs a while ago and Unknwon fixed it with  [this](https://github.com/gogits/gogs/commit/f129e0ecb57634bc02972b7ff5a3175a829c0534) commit.

Looking forward for this fix in Gitea too.
