### ISSUE TITLE
ErrNameCharsNotAllowed is raised even though username is possible

### ISSUE THREAD

**Issue by DasRoteSkelett** [go-gitea/gitea#11522]
- Gitea version (or commit ref): master (0903b1ac8c7b64bb571d02cdd69fa671cc1c18c1)
- Git version: 2.25.1
- Operating system: Ubuntu 20.04
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:
`2020/05/20 12:46:17 ...dels/login_source.go:804:UserSignIn() [W] Failed to login 'matthias.schöpfer' via 'ithinx ldap': User name is invalid [Matthias.Schöpfer]: must be valid alpha or numeric or dash(-_) or dot characters`

## Description

One of my former, brain dead administrators gave me a username containing a special german letter. Now, ldap will not function because my user name gets rejected by gitea. 

To my understanding, in user.go, line 92 / 93 must be patched for that to work:
`// Characters prohibited in a user name (anything except A-Za-z0-9_.-)
alphaDashDotPattern = regexp.MustCompile(``[^\w-\.]``)`
I do not know how go works, so this will probably not be a big deal I guess?!

**Comment by lafriks** [comment]
we support only alphanumeric characters. We could probably add support for ASCII transliteration so that as your example `matthias.schöpfer` would be transformed into `matthias.schopfer` that would be valid
