### ISSUE TITLE
Fire webhooks when repo is created from a template

### ISSUE THREAD

**Issue by joshbalfour** [go-gitea/gitea#11534]
- Gitea version (or commit ref): 0b8b81e
- Git version: 
- Operating system: arch
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
As requested from #9126 
Currently webhooks aren't being fired when a repository is created from a template.
The same webhooks which are fired when a repository is created not via a template should be fired.

**Comment by mrsdizzie** [comment]
Looking at this, when I create repo from a template I get a 'repo created' webhook same as if I use the Web site. I'm not sure how to reproduce this or whats expected/not working.

I guess to be clear we only support repo created webhooks for organization owned repos and not individual users as far as I can tell: 

https://github.com/go-gitea/gitea/blob/777015c2c2d2d74d98d15e145f9f8af04f1d9c8f/modules/notification/webhook/webhook.go#L100-L112

Is there a more detailed description of whats expected vs whats happening?

**Comment by ptman** [comment]
so not an issue?

**Comment by joshbalfour** [comment]
sorry fired this off in a rush, the ‘push’ event is the one I’m thinking of:
I have a system webhook, it gets triggered with a ‘push’ event if you create a new repo but not if you create a new repo from a template.

**Comment by jolheiser** [comment]
When commits are created via repo creation (template or not), this function is used to set the environment, which would stop hooks from firing.

https://github.com/go-gitea/gitea/blob/0b8b81e02902a5c11829cce7f439f84731a8eaeb/models/helper_environment.go#L26-L34

https://github.com/go-gitea/gitea/blob/0b8b81e02902a5c11829cce7f439f84731a8eaeb/cmd/hook.go#L136-L139

https://github.com/go-gitea/gitea/blob/0b8b81e02902a5c11829cce7f439f84731a8eaeb/cmd/hook.go#L271-L274

I believe you could get a `push` event to fire if using the push-create feature, however.

**Comment by mrsdizzie** [comment]
Push event will trigger when use push to create and files are added, which seems right in the sense that somebody actually ran 'git push' in that situation. The create repo hook is still not a push event, but Gitea will consider the file commits (if there are any) as separate push events in that scenario -- they were manually pushed so that seems somewhat correct.

So if something should be triggered specifically by repo creation it should look for repository event which is what the 'repo creation' hook is considered and the only hook guaranteed to run when a new repo is created no matter how.

**Comment by joshbalfour** [comment]
@mrsdizzie ahh ok, but the repo creation webhook is only supported in an organisation context - so using a system webhook, creating a repo as a user (not in an org), then expecting to see any webhook fired is expected behaviour right now? (until the work is done to support that on the user level)

If so looks like this is a feature request rather than a bug report - apologies for the confusion & back-and-forth everyone!

**Comment by jolheiser** [comment]
I'm going to move this to 1.13 as it's currently intended behavior.  🙂
