### ISSUE TITLE
[Bug] commits history comment on PR show unrelated after merge

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#11536]
a merge will display all comits

what I expect: only chow the merge commit

demo: https://gitea.com/gitea/go-sdk/pulls/273#issuecomment-113383

function introduced in #11167

**Comment by a1012112796** [comment]
Maybe the reason is that the branch name is wrong... 🤔

![image](https://user-images.githubusercontent.com/25342410/82565164-8b2ec600-9bac-11ea-95f4-e9203909810f.png)

**Comment by a1012112796** [comment]
I have no idea why... :(

**Comment by a1012112796** [comment]
I found the reason now, if use merge like this style, commit B can't be skipped. But I have no idea how to find it.... 
![image](https://user-images.githubusercontent.com/25342410/82578026-6cd1c600-9bbe-11ea-94b5-b244c1167394.png)

**Comment by 6543** [comment]
@a1012112796 if a commit have more than 1 parent just show that comment without the parents?
