### ISSUE TITLE
`?` being appended on the frontpage URL

### ISSUE THREAD

**Issue by silverwind** [go-gitea/gitea#11543]
1. Open https://try.gitea.io/
2. Notice URL changes to `https://try.gitea.io/?`

I think some script is causing this, maybe the heatmap?

**Comment by zeripath** [comment]
It's the repo list.

**Comment by JaneYork** [comment]
It happened to me, too.
So this is normal, not a bug? @zeripath

**Comment by zeripath** [comment]
It's not serious problem, but it is an unintended ugly side effect of making the repo list store history in the query part of the URL.

Someone, likely myself, will have to take a look to see if it can be stopped.

**Comment by silverwind** [comment]
Some combination of writing `location.search` or `replaceState` / `pushState` should get you there. I remember dealing with a similar issue for issue hash links where pushing a empty string apparently made a difference:

https://github.com/go-gitea/gitea/blob/6af13dbac2179c8fd2c63bcf175c04a112f8c080/web_src/js/index.js#L692-L694
