### ISSUE TITLE
Automatically update times in web ui

### ISSUE THREAD

**Issue by pgaskin** [go-gitea/gitea#1155]
- Gitea version (or commit ref): d2b2881
- Git version: 2.9.3
- Everything else not relevant

## Description

The timestamps on the web ui should automatically update as time passes, instead of remaining the same.

**Comment by bkcsoft** [comment]
Not exactly a fan of having _some_ things update and other not. I'd rather have entirely static pages than only updating some parts

**Comment by OvermindDL1** [comment]
> Not exactly a fan of having _some_ things update and other not. I'd rather have entirely static pages than only updating some parts

The way github does it is to put a static datetime in a `relative-time` custom element (which is open source so can be included, it's a single javascript file, just include and use it), it updates about once a minute when the page is up otherwise sans javascript it displays the actual date/time.

**Comment by adelowo** [comment]
Here is what Github uses apparently https://github.com/github/time-elements

**Comment by yp05327** [comment]
Fixed by #23988
