### ISSUE TITLE
Enable Update PR base branch through API

### ISSUE THREAD

**Issue by blaggacao** [go-gitea/gitea#11552]
https://github.com/go-gitea/gitea/blob/88fe7b5a720365e5c8f0a347730f895263465311/routers/api/v1/repo/pull.go#L351

This API method, together with it's implementation in https://gitea.com/gitea/go-sdk should implement mutating the `base` branch just as available on the UI, based on adding this field into the following struct
https://github.com/go-gitea/gitea/blob/88fe7b5a720365e5c8f0a347730f895263465311/modules/structs/pull.go#L82-L93

This is required for full git-town support https://github.com/git-town/git-town/issues/1451 since git town extensively uses branch hierarchy: if the an ancestor get's merged, all it's children branches must be reassigned to the ancestor's target merge branch.

**Comment by 6543** [comment]
@blaggacao If I can remember correctly UI dont support this

and why exactly do you need this?
you can Create/Update/Close a Pull via API ...

**Comment by blaggacao** [comment]
I just check, in UI you can do this.

The use case is the following:

1. As colleague B, I want to complement colleague A with a sub-feature on his feature branch `fbA`, so I'm working on sub-feature-branch `sfbB` based off `fbA`.

2. Since, I'm a good dev citizen in my team, I opened a WIP branch early on with the intent to ,erge into `fbA`, so everybody could ealy track changes and advancements.

3. Now, his feature was accepted into master, but my lower priority `sfbB` didn't make it in time and I'm still developing.

4. Result: my base branch is gone, therefore my PR would need to be retargeted to `master`.

Note: nesting is not limited to just one level, if it's a big feature in the making.

`git town` has first class API support in github for this workflow. IN big teams, such as where git town is used, this is a not so uncommon occurrence.

@kevgo did I miss something?

**Comment by 6543** [comment]
@blaggacao sorry didnt noticed this feature exist, since it exist on UI it is relatifely easy to do so via API

**Comment by 6543** [comment]
@blaggacao -> #11666

**Comment by kevgo** [comment]
Another use case is described [here](https://medium.com/hackernoon/high-velocity-software-development-using-nested-git-branches-69bfc2d1e54d): developing a complex feature as a series of branches, each one implementing one change and potentially being reviewed by different people.

**Comment by blaggacao** [comment]
@6543 Thanks for the quick effort
@kevgo Thanks for the good read

**Comment by blaggacao** [comment]
@6543 Once this is closed, should I open a follow up issue in https://gitea.com/gitea/go-sdk ?

**Comment by blaggacao** [comment]
https://gitea.com/gitea/go-sdk/pulls/353

**Comment by blaggacao** [comment]
https://github.com/git-town/git-town/pull/1518 has been merged, gitea is no supported in git town, still awaiting to get this closed asap!

**Comment by blaggacao** [comment]
https://gitea.com/gitea/go-sdk/pulls/353 has been merged too! Nice

**Comment by blaggacao** [comment]
So we are waiting for https://github.com/go-gitea/gitea/pull/11666 ... :hourglass:

**Comment by blaggacao** [comment]
Wondeful, and thank you for retargeting to 1.12.0 !
