### ISSUE TITLE
New user recommended setting password question

### ISSUE THREAD

**Issue by JaneYork** [go-gitea/gitea#11554]
- Gitea version (or commit ref): 1.12
- Git version: 2.26.2
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
The newly created user checked "recommended password setting". However, after the user has changed the password when logging in, he/she jumps to the event page and cannot open it. The diagram below:
the demo url like this:https://domain.com/user/events
dont tell is session??
@zeripath @GiteaBot 
...

## Screenshots
![image](https://user-images.githubusercontent.com/29787967/82655053-2fb81300-9c54-11ea-8bc8-b27d11d03497.png)

**Comment by zeripath** [comment]
Oh interesting! Why does it do that?!
