### ISSUE TITLE
Session issues may occur after multiple reloads, resulting in failed installation

### ISSUE THREAD

**Issue by JaneYork** [go-gitea/gitea#11553]
- Gitea version (or commit ref):1.12
- Git version:2.26.2
- Operating system:centos6.9 64bit
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
Session issues may occur after multiple reloads, resulting in failed installation.
The first installation can be successful, the second error session exists. Is it a browser session issue
...

## other
error log:
`2020/05/22 15:28:01 ...dules/setting/git.go:93:newGit() [I] Git Version: 2.26.2, Wire Protocol Version 2 Enabled
2020/05/22 15:28:01 routers/init.go:127:GlobalInit() [I] Delete all repository archives
[Macaron] PANIC: session(release): new sid '550c379f4aaa1893' already exists
/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/session/session.go:199 (0x111efe4)
/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:79 (0xc2f690)
/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:157 (0xc145e7)
/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:135 (0xc14388)
/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:121 (0xc2f7e8)
/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:112 (0xc40c15)
/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/recovery.go:161 (0xc40c08)
/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/logger.go:40 (0xc33253)
/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:157 (0xc145e7)
/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:135 (0xc14388)
/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:121 (0xc2f7e8)
/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:112 (0xc3ff40)
/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/logger.go:52 (0xc3ff2b)
/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/logger.go:40 (0xc33253)
/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:157 (0xc145e7)
/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:135 (0xc14388)
/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:121 (0xc2f7e8)
/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/router.go:187 (0xc41e26)
/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/router.go:294 (0xc3b8cd)
/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/macaron.go:218 (0xc345aa)
/go/src/code.gitea.io/gitea/vendor/github.com/gorilla/context/context.go:141 (0xea5f83)
/usr/local/go/src/net/http/server.go:2012 (0x7506a3)
/usr/local/go/src/net/http/server.go:2807 (0x753a32)
/usr/local/go/src/net/http/server.go:1895 (0x74f4ab)
/usr/local/go/src/runtime/asm_amd64.s:1373 (0x46ef70)
[Macaron] 2020-05-22 15:28:02: Completed POST /install 500 Internal Server Error in 8.66900989s
`
@zeripath  Hi guys ,help!

**Comment by JaneYork** [comment]
But it looks like the installation is done and it works. Because I can go to the front page.
![image](https://user-images.githubusercontent.com/29787967/82643857-deebee80-9c42-11ea-8b8b-6f0b9dcfbd3f.png)

**Comment by kdomanski** [comment]
I'm getting a similar stack trace when re-logging in. Running `master` on an alpine container.
Bisect points to commit `76053ac31afccefc0335977a131089e696b46eab` being the culprit.

**Comment by zeripath** [comment]
Fixed by #11590
