### ISSUE TITLE
Can not verify your SSH key: extractTypeFromBase64Key: invalid key format:

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#11556]
- Gitea version (or commit ref): 1.13.0+dev-30-gb02d2c377
- Git version: N/A
- Operating system: N/A
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
  - [x] N/A
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
  - [x] Was tested at https://gitea.com
- Log gist:
N/A

## Description

I was trying to create a deploy key with the following data:

![grafik](https://user-images.githubusercontent.com/64696032/82660165-244ff200-9c2a-11ea-93c0-a10f0ca30064.png)

Result can be seen below:

## Screenshots

![grafik](https://user-images.githubusercontent.com/64696032/82660047-f074cc80-9c29-11ea-8e67-5b5ebc476bfe.png)

**Comment by opyale** [comment]
Ok, this is my fault. I thought the field 'content' is only used for a description of some sort.
