### ISSUE TITLE
[remote rejected] master -> master (pre-receive hook declined)

### ISSUE THREAD

**Issue by patrickmhaller** [go-gitea/gitea#11576]
- Gitea version (or commit ref): 1.11.5
- Git version:git version 2.26.2
- Operating system:Gentoo/Linux (rolling)
- Database (use `[x]`):
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:

## Description

All `git push` fail with

```
user@host ~/workspace/myproject $ git push
Enumerating objects: 4, done.
Counting objects: 100% (4/4), done.
Compressing objects: 100% (2/2), done.
Writing objects: 100% (3/3), 278 bytes | 278.00 KiB/s, done.
Total 3 (delta 1), reused 0 (delta 0), pack reused 0
To ssh://giteahost/srv/gitea/gitea-repositories/user/myproject
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'ssh://giteahost/srv/gitea/gitea-repositories/user/myproject'
```

Moving `/srv/gitea/gitea-repositories/user/myproject.git/hooks/pre-receive.d/gitea` out of the way to prevent the execution of the hook, then the git push works. So the hook gets executed, but fails.

The hook code is standard; it has been regenerated:
`"/usr/bin/gitea" hook --config='/etc/gitea/app.ini' pre-receive`

When the pre-receive hook is executed, the gitea web service does not log any activity, despite debug logging is turned on *everywhere*. Interactions with the Web UI do show activity in the logs.

I therefore assume, that the "gitea hook" is unable to contact the running "gitea web" service instance.

How to diagnose this issue?
How to capture information about the executing "gitea hook"?

Thanks, Patrick

**Comment by jolheiser** [comment]
Can you verify the Gitea binary lives at `/usr/bin/gitea` and the config at `/etc/gitea/app.ini`?

Alternatively, is the hook file not executable for some reason?

**Comment by zeripath** [comment]
Ok, so we need to check a few things:

* Double check that the contents of the hook files are exactly what you expect them to be. Make sure that they're pointing to the correct app ini and Gitea.
* Ensure that you have bash installed
* Ensure that the Gitea repositories are mounted on a drive that is not noexec
* Double check that there are not other hooks in the hooks directories that are executing.
* You can add some echo statements to the bash files to ensure that they are being executed.
* I think I added --debug to the hooks so you should be able to add that to the gitea hook command.

**Comment by patrickmhaller** [comment]
Thanks.

- Can you verify the Gitea binary lives at /usr/bin/gitea and the config at /etc/gitea/app.ini?
&rarr; confirmed
- Double check that the contents of the hook files are exactly what you expect them to be. Make sure that they're pointing to the correct app ini and Gitea.
&rarr; confirmed
- Ensure that you have bash installed
&rarr; confirmed
- Ensure that the Gitea repositories are mounted on a drive that is not noexec
&rarr; confirmed, the ./pre-receive.d/gitea script does get executed
- Double check that there are not other hooks in the hooks directories that are executing.
&rarr; confirmed: if the script ./pre-receive.d/gitea is disabled, the git push works fine. This is an indication that the script *is attempted* to be executed. This is also a fresh, initial installation of gitea. I just recently upgraded from gitea 1.10.6 to 1.11.5. 1.10.6 worked fine, failure started with 11.1.5. I suspect something might have went wrong when upgrading the configuration. But with clear logs, I'm just not finding the issue.

> You can add some echo statements to the bash files to ensure that they are being executed.

Good idea. Both, ./hooks/pre-receive and hooks/pre-receive.d/gitea get executed.

The `./hooks/pre-receive` script is executing `2ac3b1186cad2fba6d804308230e1c41c077c053 e29ee4ba381554195dad45d73f91c2206f5ca8c3 refs/heads/master | ./hooks/pre-receive.d/gitea`, which is returning with exit code 1.

> I think I added --debug to the hooks so you should be able to add that to the gitea hook command.

This seems not to be available in 1.11.5 yet, right?

**Comment by zeripath** [comment]
Damn! I just saw this:

```
ssh://giteahost/srv/gitea/gitea-repositories/user/myproject
```

What's going on? Are you trying to push to gitea's repositories with a key that is not controlled by Gitea? That is not supported.

You must only push to Gitea's repositories with a key managed by Gitea. (There are ways to do it with an unmanaged key but discuss these on discord as it's not formally supported.)

The simplest check is what happens if you ssh to giteahost plain - if you get a prompt then you're using a key not managed by Gitea.

**Comment by patrickmhaller** [comment]
Good catch, thank you for your help.
I had not yet set up any ssh-keys and was using password authentication.

With the ssh-key in place in both, ./ssh and gitea profile, things work nicely!

**Comment by zeripath** [comment]
From the looks of the last comment it appears that this issue was solved therefore I'm closing it.
