### ISSUE TITLE
Language Statistics - Hiding languages

### ISSUE THREAD

**Issue by alexander-zierhut** [go-gitea/gitea#11580]
- Gitea version (or commit ref): 1.12.0-rc1
- Feature reference: #8037 
- Git version: /
- Operating system: /
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

I love this new feature, but is it possible to hide some languages? Maybe have some settings for which languages to hide. I suppose SVG could be off by default.

## Screenshots
![image](https://user-images.githubusercontent.com/26348781/82731390-c3e2b280-9d06-11ea-9a4a-fe5621393f60.png)

**Comment by jolheiser** [comment]
I see this is a duplicate of https://github.com/go-gitea/gitea/issues/10567, however it was closed by the stale bot :slightly_frowning_face: 
Since that issue already has some feedback, I'm going to re-open it in lieu of this one and scare away the bot.
