### ISSUE TITLE
replace gitea wiki with kanboard

### ISSUE THREAD

**Issue by sailfish009** [go-gitea/gitea#1159]
Hi, this is not question, just suggestion.

i don't know how to use gitea and gogs wiki page.
personally i am using kanboard and gitea in my personal linux local server.
https://kanboard.net/

it would be nice if gitea collaborate with kanboard.

**Comment by tboerger** [comment]
A wiki got a totally different usage than kanboard, I have no idea how you want to compare that. A kanboard integration should be done on kanboard, it got a pretty simple php plugin architecture. But kanboard will never replace the wiki.

**Comment by sailfish009** [comment]
i am using kanboard for everything include wiki but except git server like gitea or gogs.

**Comment by tboerger** [comment]
Kanboard is not a wiki.

**Comment by sailfish009** [comment]
i doubt that gitea or gogs wiki is really wiki.
after all, we needs place that something to note or record.
