### ISSUE TITLE
Random 500 errors

### ISSUE THREAD

**Issue by sshaikh** [go-gitea/gitea#11606]
- Gitea version (or commit ref): 1.12.0
- Git version: 2.20.1
- Operating system: Debian
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

2020/05/24 15:43:18 ...sitory/repository.go:23:CreateRepository() [E] Rollback deleteRepository: repository does not exist [id: 31, uid: 2, owner_name: , name: ]
2020/05/24 15:43:18 routers/repo/repo.go:175:handleCreateError() [E] CreatePost: initRepository: createDelegateHooks: Unable to set /appdata/repositories/atal/omv-config.git/hooks/pre-receive executable. Error stat /appdata/repositories/atal/omv-config.git/hooks/pre-receive.d/gitea: interrupted system call

https://gist.github.com/sshaikh/4bfd4219e4dcdfa2a8c96893c5c02c56

## Description

We get 500 errors on the webUI at what appears to be random points.  Sometimes when viewing a repo - but then F5 would fix it. A lot more often when creating repos, but eventually things go through. Also at various points in the usage.

Git pulls and pushes seem to work all the time.

I can't see what causes the error from the logs.

## Environment

I'm running Gitea in an LXC container, and my repos are on a bind mount (which in turn is an autofs CIFS mount on the LXC host). I do not think there is an access issue as the file system appears to be available at all times (and the creating repo consistently fails until it works).

**Comment by ALZlper** [comment]
+1
Had a 500 error when trying to enable 2FA.

**Comment by ALZlper** [comment]
Still open to my knowledge
