### ISSUE TITLE
MAX_CREATION_LIMIT  does not work for fork

### ISSUE THREAD

**Issue by oicu** [go-gitea/gitea#11603]
- Gitea version (or commit ref): gitea-1.12-windows-4.0-amd64.exe
- Git version:  2.25.1
- Operating system: Windows 10 LTSC 2019
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description

```
MAX_CREATION_LIMIT = 0 
```
But user can create a repositorie through `fork` or `New Migration`.

I wan to disable `fork` and  `New Migration`.

**Comment by zeripath** [comment]
Duplicated with #4586
