### ISSUE TITLE
Anchor rewrite breaks AsciiDoc documents

### ISSUE THREAD

**Issue by tastytea** [go-gitea/gitea#11617]
- Gitea version (or commit ref): 1.11.5
- Git version: 2.26.2
- Operating system: gentoo Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Asciidoctor: 2.0.10

## Description

Since 1.11.0 `user-content-` is prepended to anchors (#9673). An AsciiDoc document with a TOC will link to `#_install` but the anchor is `#user-content-_install`. There seems to be no way to modify the naming rules in asciidoc(tor). The change breaks existing links and bookmarks. Please allow me to turn it off.

You can observe the behavior at <https://schlomp.space/tastytea/gentoo-xcursors/src/branch/main/README.adoc>.

**Comment by zeripath** [comment]
https://asciidoctor.org/docs/user-manual/#auto-generated-ids

Set the idprefix appropriately.

We cannot allow rendered documents to set arbitrary IDs - a user could hijack JavaScript scripts, rewrite window objects etc.

**Comment by tastytea** [comment]
Thanks. Had to change `idseparator` too. 

In case someone else with the same problem finds this: Add `--attribute=idseparator=- --attribute=idprefix=user-content-` to `RENDER_COMMAND`.
