### ISSUE TITLE
Gitea Login Page Login when entering a specific word

### ISSUE THREAD

**Issue by lsy2534** [go-gitea/gitea#11629]
- Gitea version (or commit ref): 1.9.5
- Git version:
- Operating system: linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Not relevant
  - [ ] Yes (provide example URL)
  - [x] No
- Log gist:

## Description

Hello! 
I'm studying Gitea. 
I want to make you log in when you enter a specific password on the login page.  
But I can't find the part where I'm modifying Query, so I'm here to ask for your help.  
Sorry for my poor English.

**Comment by techknowlogick** [comment]
If you want to enable login into Gitea for everyone with same password, I recommend connecting to a different tool using OIDC (openid connect), and have that 3rd party tool accept the sole password. This is because you don't want to have to modify Gitea code and patch each upgrade with custom code.

**Comment by lsy2534** [comment]
Thank you. 
But I also wanted to use an open ID, but I don't know how to use it. Can you show me an example of connecting with something else?
