### ISSUE TITLE
Port used for MSSQL databases

### ISSUE THREAD

**Issue by jeffest** [go-gitea/gitea#11633]
- Gitea version (or commit ref): 1.12
- Git version: 2.22
- Operating system: Windows 10
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

The installation process assumes that the MSSQL server instance provided by the user will listen on the default port 1433. This is defined in  function [ParseMSSQLHostPort](https://github.com/go-gitea/gitea/blob/5cb201dc93bf41556556f2154ea28755907fd550/modules/setting/database.go#L165).
By doing so, it prevents the mssql driver from actually detecting the port automatically. This has a major impact if the db server is hosting multiple instances of SQL Server. The port 1433 is being used by the default instance and all other instances will use dynamic ports. In order to determine  the correct port for a particular instance (the one supplied by the end user), the driver is querying the SQL Server's Browser service ([here](https://github.com/go-gitea/gitea/blob/5cb201dc93bf41556556f2154ea28755907fd550/vendor/github.com/denisenkom/go-mssqldb/tds.go#L844)). But it only does that if the port is not specified ( `p.port == 0` ) which never happens considering the default value of 1433.

IMHO, there should not be a default port for mssql driver if not provided by the user and the driver should be responsible for finding it.

**Comment by jolheiser** [comment]
This is the install page regarding MSSQL options:

![mssql](https://user-images.githubusercontent.com/42128690/82917818-83b74600-9f39-11ea-8cb2-1c39f181c09d.png)

And then after installation, when the config is loaded, the host would be parsed like so:

https://github.com/go-gitea/gitea/blob/5cb201dc93bf41556556f2154ea28755907fd550/modules/setting/database.go#L164-L177

Port 1433 does serve as default, but only if none of the following if-else match. If you set it as `127.0.0.1:0` then it would parse the port as `0` afaik

**Comment by zeripath** [comment]
But if we change the port in line 167 to 0 then they never have to put the port in and, it will still work for those who have it on 1433... (AFAICS)

**Comment by jeffest** [comment]
Yes @zeripath, this is how it should work. 
@jolheiser, your remark is 100% valid but it's neither intuitive or user-friendly (AFAICT)
