### ISSUE TITLE
release v1.1.0 on docker hub

### ISSUE THREAD

**Issue by avelino** [go-gitea/gitea#1165]
Generate release 1.1.0 (https://github.com/go-gitea/gitea/releases/tag/v1.1.0) by @tboerger not send to docker hub, got date?

**Comment by tboerger** [comment]
<img width="1254" alt="bildschirmfoto 2017-03-09 um 22 56 45" src="https://cloud.githubusercontent.com/assets/156964/23772580/b94c7a76-051b-11e7-970b-4daacebd16fb.png">
