### ISSUE TITLE
Problem with permisions

### ISSUE THREAD

**Issue by y0rune** [go-gitea/gitea#11654]
- Gitea version (or commit ref): Gitea version 1.11.5
- Git version: git version 2.26.2
- Operating system: Gentoo
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X] No
  - [ ] Not relevant
- Log gist:

## Description

...

## Screenshots
![image](https://user-images.githubusercontent.com/10187235/83140545-860ed100-a0ee-11ea-95a8-bea7a6ec648a.png)

![image](https://user-images.githubusercontent.com/10187235/83140714-ccfcc680-a0ee-11ea-931a-731d4862e253.png)

**Comment by jolheiser** [comment]
We'll need a scrubbed config if possible and maybe some log errors.

Permission denied is usually a pretty straightforward error, though.

Are you running Gitea with the `git` user? Furthermore, based on the perms screenshot, the `git` user only has read access to those directories.

**Comment by y0rune** [comment]
Yeah I used the git user but now I move to 'normal gitweb'

**Comment by y0rune** [comment]
After contact with the maintainer, he give me advise about using the binary and yeah binary solved everything.
