### ISSUE TITLE
Integrate an OIDC provider

### ISSUE THREAD

**Issue by droplet-js** [go-gitea/gitea#11652]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

...

**Comment by lafriks** [comment]
Gitea already allows authorization with OIDC but if you mean for Gitea to act as one, than this is probably duplicate of #8775

**Comment by v7lin** [comment]
oidc provider like oauth2 provider(https://docs.gitea.io/en-us/oauth2-provider/)

**Comment by techknowlogick** [comment]
Closing as duplicate of #8775
