### ISSUE TITLE
PR Approvals don't count towards minimum required

### ISSUE THREAD

**Issue by abread** [go-gitea/gitea#11675]
- Gitea version (or commit ref): 1.11.5
- Git version: 2.24.3
- Operating system: Gentoo Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes [example](https://try.gitea.io/truta43/puzzle-puzzletime/pulls/2)
  - [ ] No
  - [ ] Not relevant
## Description
When a PR is approved and only after is branch protection enabled with a minimum approval count, this previous approval doesn't seem to count.

**Comment by CirnoT** [comment]
Looks like reviews are always considered non-official until branch protection is enabled.

https://github.com/go-gitea/gitea/blob/6e4480835f7688a089f6c018f97333138f64bd87/models/review.go#L206-L219

We should most likely assume all people with write access are official reviewers if branch protection which tells us otherwise is not present.

**Comment by davidsvantesson** [comment]
I think there was a discussion about this when the feature was added. The argument was that it might be confusing if a review that was previously not "official" suddently become that. So if branch protection is added or a reviewer is added to whitelist, (s)he has to make a new review. In same way I think an official review will remain even if user is removed from whitelist (?). I think this behaviour makes sense.

I am not sure how GH is doing here?

**Comment by abread** [comment]
To the user, this distinction between official and non-official is invisible. I did not know this concept of official review before reading this, but it makes perfect sense given the option to whitelist reviewers and still allow feedback from other users.

A visual indication of which reviews are official (and update the language in the settings to mention that the whitelists determine which reviews are official) would help a lot.

In this case, I'd expect every review to be official before branch protection is removed. If I remove a reviewer from the whitelist, their reviews up to that moment would still count right now, right? So it shouldn't be different from enabling branch protection.
