### ISSUE TITLE
Option to disable/limit private repository

### ISSUE THREAD

**Issue by sniffingsugar** [go-gitea/gitea#11694]
Hello,
we have already a force repository to be a private option, it would be nice to limit or disable the private repository limit user wise, so you can manage a public instance better.

Kindly Regards,
Phil

- Gitea version (or commit ref): Not related
- Git version: Not related
- Operating system: Not related
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant

**Comment by mvdkleijn** [comment]
I believe this duplicates #3653 ?
