### ISSUE TITLE
GPG key for checking download integrity missing

### ISSUE THREAD

**Issue by muellert** [go-gitea/gitea#11699]
- Gitea version (or commit ref): 1.11.6
- Git version: n/a
- Operating system: n/a
- Database (use `[x]`):
  - [x ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x ] Not relevant
- Log gist:

## Description

When I go to dl.gitea.io/gitea to download a binary, there are .asc files with cryptographic signatures, but there is no obvious key listed in the documentation, which should be used to verify these. Trying to automatically download them, might quite well fail for a variety of reasons, too.

**Comment by techknowlogick** [comment]
Please see https://docs.gitea.io/en-us/install-from-binary/ for documentation.
