### ISSUE TITLE
Seperate the issue management and wiki as 'plugins'

### ISSUE THREAD

**Issue by ChangePlaces** [go-gitea/gitea#1169]
I'd like to suggest that issue managment and the wiki be pulled out of the core code and added as optional plugins. This will help keep gogs even more trim.

In my use case, I want just a git repository manager with a basic web UI that allows me to create repos, push and view contents of the files.

I've grown tired of gogs development slowing down to a snail pace, but I think this plugin separation would allow gogs to be developed separately and allow it to be more useful to many more developers.

**Comment by geek1011** [comment]
What do you mean by slowing down to a snail pace? I have never had performance issues, even around 2 weeks.

**Comment by tboerger** [comment]
We want to introduce a plugin system, but it's always difficult to drop functionality that is already part of the core.

**Comment by ChangePlaces** [comment]
@geek1011 I actually meant "tired of gogs development slowing down"

**Comment by lunny** [comment]
You can disable them on the repo settings. @ChangePlaces And we have introduced a unit concept to make a basic of plugin. #947 will let you define a team who only see codes or issues or wiki. Of course, this could be a global options then you could disable all repo issues or wiki.

**Comment by ChangePlaces** [comment]
I know you can disable them per repo, but that's still checking for issues that may be assigned to you. I was envisioning a global removal, rather than a disabling. e.g. the core system is installed, and plugins such as different types of issue trackers could be used depending on your needs, different wiki's etc.

**Comment by lunny** [comment]
depends on #2222

**Comment by wxiaoguang** [comment]
Is it still feasible? Especially for the issue part, the PR system directly depends on it.

**Comment by tboerger** [comment]
IMHO it's still valid. Somebody would potentially replace the builtin issues with another system similar to jira. And in general gitea should still provide a big plugin system.

**Comment by wxiaoguang** [comment]
But, how to ? If not feasible, is it worth to keep it open?

**Comment by delvh** [comment]
I agree with @wxiaoguang.
Especially since there are already dedicated issues for plugins like #20126.
The only portion that isn't covered by this issue is the "remove issues and wiki from core" part.
And like @wxiaoguang, I doubt that that is really possible.
