### ISSUE TITLE
After deleting wiki repo manually, main repository won't load

### ISSUE THREAD

**Issue by xPaw** [go-gitea/gitea#117]
Ends up with this error:
```
[Macaron] Started GET /xxx/xxx for xxx
2015/07/20 09:32:24 [repo.go:301 func·009()] [E] GetWikiRepo: repository does not exist [id: 10, uid: 0, name: ]
```

**Comment by tboerger** [comment]
How did you delete that manually?

**Comment by xPaw** [comment]
It let me open `xxx.wiki` repository, and settings opened fine for that repository too.

**Comment by tboerger** [comment]
OMG, that should be not allowed. Thanks...

**Comment by tboerger** [comment]
So  we need to restrict the repo view to real repositories and not for wiki repositories.

**Comment by lunny** [comment]
Yes. @tboerger @makhov

**Comment by xPaw** [comment]
This is not really fixed, my repository is still broken using latest dev branch.

`[repo.go:302 func·009()] [E] GetWikiRepo: repository does not exist [id: 10, uid: 0, name: ]`

**Comment by lunny** [comment]
I fixed this issue via hidden the delete operation of wiki repository on web ui. And if you have deleted it, you have to update wiki_repo_id = 0 on database.
