### ISSUE TITLE
Can't connect to MySQL via TCP, I need to use UNIX socket

### ISSUE THREAD

**Issue by AlphaJack** [go-gitea/gitea#11707]
- Gitea version (or commit ref): `Gitea version 1.11.0 built with GNU Make 4.3, go1.13.8 : bindata, sqlite, pam`
- Git version: `git 2.26.2-1`
- Operating system: `Linux 5.4.40-1-ARCH #1 SMP PREEMPT Thu May 14 01:48:56 UTC 2020 armv7l GNU/Linux`

- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL `mariadb 10.4.13-1`
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant

## Description
I tried to move to MySQL after the some time using SQLite. I did
```bash
sudo -u gitea gitea dump -d mysql -c /etc/gitea/app.ini
sudo mariadb -u root
```
On the DB shell, 
```mysql
CREATE DATABASE gitea-db;
CREATE USER 'gitea'@'localhost' IDENTIFIED BY 'XXXXXX';
GRANT ALL ON gitea-db.* TO 'gitea'@'localhost' IDENTIFIED BY 'XXXXXX' WITH GRANT OPTION;
FLUSH PRIVILEGES;
EXIT;
```

Again in bash
```bash
mysql -u gitea -p gitea-db < gitea-db.sql 
```
The command exited without errors. I stopped Gitea and changed in `app,ini` from this
```ini
[Database]
DB_TYPE = sqlite3 
HOST =
NAME =
USER =
PASSWD =
SSL_MODE = disable
```
to this 
```ini
DB_TYPE             = mysql
HOST                = localhost
NAME                = gitea-db
USER                = gitea
PASSWD              = XXXXXX
SSL_MODE            = false
CHARSET             = utf8mb4

ITERATE_BUFFER_SIZE = 50
; Show the database generated SQL
LOG_SQL             = false
; Maximum number of DB Connect retries
DB_RETRIES          = 10
; Backoff time per DB retry (time.Duration)
DB_RETRY_BACKOFF    = 3s
; Max idle database connections on connnection pool, default is 2
MAX_IDLE_CONNS      = 2
; Database connection max life time, default is 0 or 3s mysql (See #6804 & #7071 for reasoning)
CONN_MAX_LIFETIME   = 3s
; Database maximum number of open connections, default is 0 meaning no maximum
MAX_OPEN_CONNS      = 0
```

When I tried to restart Gitea system service, it failed with result 'exit-code'. `gitea.log` reports:
<details>
 <summary>`gitea.log`</summary>
<pre>
2020/05/31 15:33:07 ...eful/manager_unix.go:133:handleSignals() [W] PID 549. Received SIGTERM. Shutting down...
2020/05/31 15:33:07 cmd/web.go:206:runWeb() [I] HTTP Listener: 127.0.0.1:3000 Closed
2020/05/31 15:33:07 ...eful/server_hooks.go:47:doShutdown() [I] PID: 549 Listener (127.0.0.1:3000) closed.
2020/05/31 15:33:07 ...rvices/pull/check.go:212:TestPullRequests() [I] PID: 549 Pull Request testing shutdown
2020/05/31 15:33:08 .../graceful/manager.go:184:doHammerTime() [W] Setting Hammer condition
2020/05/31 15:33:09 .../graceful/manager.go:198:doTerminate() [W] Terminating
2020/05/31 15:33:09 ...er/issues/indexer.go:161:1() [I] PID: 549 Issue Indexer closed
2020/05/31 15:33:09 cmd/web.go:208:runWeb() [I] PID: 549 Gitea Web Finished
2020/05/31 15:34:26 ...dules/setting/log.go:276:newLogService() [I] Gitea Log Mode: File(File:info)
2020/05/31 15:34:26 ...les/setting/cache.go:45:newCacheService() [I] Cache Service Enabled
2020/05/31 15:34:26 ...s/setting/session.go:44:newSessionService() [I] Session Service Enabled
2020/05/31 15:34:26 ...es/setting/mailer.go:106:newMailService() [I] Mail Service Enabled
2020/05/31 15:34:26 ...es/setting/mailer.go:117:newRegisterMailService() [I] Register Mail Service Enabled
2020/05/31 15:34:26 ...es/setting/mailer.go:128:newNotifyMailService() [I] Notify Mail Service Enabled
2020/05/31 15:34:26 routers/init.go:59:initDBEngine() [I] Beginning ORM engine initialization.
2020/05/31 15:34:26 routers/init.go:66:initDBEngine() [I] ORM engine initialization attempt #1/10...
2020/05/31 15:34:26 ...orm@v0.8.1/engine.go:351:Ping() [I] PING DATABASE mysql
2020/05/31 15:34:26 routers/init.go:72:initDBEngine() [E] ORM engine initialization attempt #1/10 failed. Error: commands out of sync. Did you run multiple statements at once?
2020/05/31 15:34:26 routers/init.go:73:initDBEngine() [I] Backing off for 3 seconds
2020/05/31 15:34:29 routers/init.go:66:initDBEngine() [I] ORM engine initialization attempt #2/10...
2020/05/31 15:34:29 ...orm@v0.8.1/engine.go:351:Ping() [I] PING DATABASE mysql
2020/05/31 15:34:29 routers/init.go:72:initDBEngine() [E] ORM engine initialization attempt #2/10 failed. Error: commands out of sync. Did you run multiple statements at once?
2020/05/31 15:34:29 routers/init.go:73:initDBEngine() [I] Backing off for 3 seconds
2020/05/31 15:34:32 routers/init.go:66:initDBEngine() [I] ORM engine initialization attempt #3/10...
2020/05/31 15:34:32 ...orm@v0.8.1/engine.go:351:Ping() [I] PING DATABASE mysql
2020/05/31 15:34:32 routers/init.go:72:initDBEngine() [E] ORM engine initialization attempt #3/10 failed. Error: commands out of sync. Did you run multiple statements at once?
2020/05/31 15:34:32 routers/init.go:73:initDBEngine() [I] Backing off for 3 seconds
2020/05/31 15:34:35 routers/init.go:66:initDBEngine() [I] ORM engine initialization attempt #4/10...
2020/05/31 15:34:35 ...orm@v0.8.1/engine.go:351:Ping() [I] PING DATABASE mysql
2020/05/31 15:34:35 routers/init.go:72:initDBEngine() [E] ORM engine initialization attempt #4/10 failed. Error: commands out of sync. Did you run multiple statements at once?
2020/05/31 15:34:35 routers/init.go:73:initDBEngine() [I] Backing off for 3 seconds
2020/05/31 15:34:38 routers/init.go:66:initDBEngine() [I] ORM engine initialization attempt #5/10...
2020/05/31 15:34:38 ...orm@v0.8.1/engine.go:351:Ping() [I] PING DATABASE mysql
2020/05/31 15:34:38 routers/init.go:72:initDBEngine() [E] ORM engine initialization attempt #5/10 failed. Error: commands out of sync. Did you run multiple statements at once?
2020/05/31 15:34:38 routers/init.go:73:initDBEngine() [I] Backing off for 3 seconds
2020/05/31 15:34:41 routers/init.go:66:initDBEngine() [I] ORM engine initialization attempt #6/10...
2020/05/31 15:34:41 ...orm@v0.8.1/engine.go:351:Ping() [I] PING DATABASE mysql
2020/05/31 15:34:41 routers/init.go:72:initDBEngine() [E] ORM engine initialization attempt #6/10 failed. Error: commands out of sync. Did you run multiple statements at once?
2020/05/31 15:34:41 routers/init.go:73:initDBEngine() [I] Backing off for 3 seconds
2020/05/31 15:34:44 routers/init.go:66:initDBEngine() [I] ORM engine initialization attempt #7/10...
2020/05/31 15:34:44 ...orm@v0.8.1/engine.go:351:Ping() [I] PING DATABASE mysql
2020/05/31 15:34:44 routers/init.go:72:initDBEngine() [E] ORM engine initialization attempt #7/10 failed. Error: commands out of sync. Did you run multiple statements at once?
2020/05/31 15:34:44 routers/init.go:73:initDBEngine() [I] Backing off for 3 seconds
2020/05/31 15:34:47 routers/init.go:66:initDBEngine() [I] ORM engine initialization attempt #8/10...
2020/05/31 15:34:47 ...orm@v0.8.1/engine.go:351:Ping() [I] PING DATABASE mysql
2020/05/31 15:34:47 routers/init.go:72:initDBEngine() [E] ORM engine initialization attempt #8/10 failed. Error: commands out of sync. Did you run multiple statements at once?
2020/05/31 15:34:47 routers/init.go:73:initDBEngine() [I] Backing off for 3 seconds
2020/05/31 15:34:50 routers/init.go:66:initDBEngine() [I] ORM engine initialization attempt #9/10...
2020/05/31 15:34:50 ...orm@v0.8.1/engine.go:351:Ping() [I] PING DATABASE mysql
2020/05/31 15:34:50 routers/init.go:72:initDBEngine() [E] ORM engine initialization attempt #9/10 failed. Error: commands out of sync. Did you run multiple statements at once?
2020/05/31 15:34:50 routers/init.go:73:initDBEngine() [I] Backing off for 3 seconds
2020/05/31 15:34:53 routers/init.go:66:initDBEngine() [I] ORM engine initialization attempt #10/10...
2020/05/31 15:34:53 ...orm@v0.8.1/engine.go:351:Ping() [I] PING DATABASE mysql
2020/05/31 15:34:53 routers/init.go:101:GlobalInit() [F] ORM engine initialization failed: commands out of sync. Did you run multiple statements at once?
2020/05/31 15:34:58 ...dules/setting/log.go:276:newLogService() [I] Gitea Log Mode: File(File:info)
2020/05/31 15:34:58 ...les/setting/cache.go:45:newCacheService() [I] Cache Service Enabled
2020/05/31 15:34:58 ...s/setting/session.go:44:newSessionService() [I] Session Service Enabled
2020/05/31 15:34:58 ...es/setting/mailer.go:106:newMailService() [I] Mail Service Enabled
2020/05/31 15:34:58 ...es/setting/mailer.go:117:newRegisterMailService() [I] Register Mail Service Enabled
2020/05/31 15:34:58 ...es/setting/mailer.go:128:newNotifyMailService() [I] Notify Mail Service Enabled
2020/05/31 15:34:58 routers/init.go:59:initDBEngine() [I] Beginning ORM engine initialization.
2020/05/31 15:34:58 routers/init.go:66:initDBEngine() [I] ORM engine initialization attempt #1/10...
2020/05/31 15:34:58 ...orm@v0.8.1/engine.go:351:Ping() [I] PING DATABASE mysql
2020/05/31 15:34:58 routers/init.go:72:initDBEngine() [E] ORM engine initialization attempt #1/10 failed. Error: commands out of sync. Did you run multiple statements at once?
2020/05/31 15:34:58 routers/init.go:73:initDBEngine() [I] Backing off for 3 seconds
2020/05/31 15:35:01 routers/init.go:66:initDBEngine() [I] ORM engine initialization attempt #2/10...
2020/05/31 15:35:01 ...orm@v0.8.1/engine.go:351:Ping() [I] PING DATABASE mysql
2020/05/31 15:35:01 routers/init.go:72:initDBEngine() [E] ORM engine initialization attempt #2/10 failed. Error: commands out of sync. Did you run multiple statements at once?
2020/05/31 15:35:01 routers/init.go:73:initDBEngine() [I] Backing off for 3 seconds
2020/05/31 15:35:04 routers/init.go:66:initDBEngine() [I] ORM engine initialization attempt #3/10...
2020/05/31 15:35:04 ...orm@v0.8.1/engine.go:351:Ping() [I] PING DATABASE mysql
2020/05/31 15:35:04 routers/init.go:72:initDBEngine() [E] ORM engine initialization attempt #3/10 failed. Error: commands out of sync. Did you run multiple statements at once?
2020/05/31 15:35:04 routers/init.go:73:initDBEngine() [I] Backing off for 3 seconds
2020/05/31 15:35:07 routers/init.go:66:initDBEngine() [I] ORM engine initialization attempt #4/10...
2020/05/31 15:35:07 ...orm@v0.8.1/engine.go:351:Ping() [I] PING DATABASE mysql
2020/05/31 15:35:07 routers/init.go:72:initDBEngine() [E] ORM engine initialization attempt #4/10 failed. Error: commands out of sync. Did you run multiple statements at once?
2020/05/31 15:35:07 routers/init.go:73:initDBEngine() [I] Backing off for 3 seconds
2020/05/31 15:35:10 routers/init.go:66:initDBEngine() [I] ORM engine initialization attempt #5/10...
2020/05/31 15:35:10 ...orm@v0.8.1/engine.go:351:Ping() [I] PING DATABASE mysql
2020/05/31 15:35:10 routers/init.go:72:initDBEngine() [E] ORM engine initialization attempt #5/10 failed. Error: commands out of sync. Did you run multiple statements at once?
2020/05/31 15:35:10 routers/init.go:73:initDBEngine() [I] Backing off for 3 seconds
2020/05/31 15:35:13 routers/init.go:66:initDBEngine() [I] ORM engine initialization attempt #6/10...
2020/05/31 15:35:13 ...orm@v0.8.1/engine.go:351:Ping() [I] PING DATABASE mysql
2020/05/31 15:35:13 routers/init.go:72:initDBEngine() [E] ORM engine initialization attempt #6/10 failed. Error: commands out of sync. Did you run multiple statements at once?
2020/05/31 15:35:13 routers/init.go:73:initDBEngine() [I] Backing off for 3 seconds
2020/05/31 15:35:16 routers/init.go:66:initDBEngine() [I] ORM engine initialization attempt #7/10...
2020/05/31 15:35:16 ...orm@v0.8.1/engine.go:351:Ping() [I] PING DATABASE mysql
2020/05/31 15:35:16 routers/init.go:72:initDBEngine() [E] ORM engine initialization attempt #7/10 failed. Error: commands out of sync. Did you run multiple statements at once?
2020/05/31 15:35:16 routers/init.go:73:initDBEngine() [I] Backing off for 3 seconds
2020/05/31 15:35:19 routers/init.go:66:initDBEngine() [I] ORM engine initialization attempt #8/10...
2020/05/31 15:35:19 ...orm@v0.8.1/engine.go:351:Ping() [I] PING DATABASE mysql
2020/05/31 15:35:19 routers/init.go:72:initDBEngine() [E] ORM engine initialization attempt #8/10 failed. Error: commands out of sync. Did you run multiple statements at once?
2020/05/31 15:35:19 routers/init.go:73:initDBEngine() [I] Backing off for 3 seconds
2020/05/31 15:35:22 routers/init.go:66:initDBEngine() [I] ORM engine initialization attempt #9/10...
2020/05/31 15:35:22 ...orm@v0.8.1/engine.go:351:Ping() [I] PING DATABASE mysql
2020/05/31 15:35:22 routers/init.go:72:initDBEngine() [E] ORM engine initialization attempt #9/10 failed. Error: commands out of sync. Did you run multiple statements at once?
2020/05/31 15:35:22 routers/init.go:73:initDBEngine() [I] Backing off for 3 seconds
2020/05/31 15:35:25 routers/init.go:66:initDBEngine() [I] ORM engine initialization attempt #10/10...
2020/05/31 15:35:25 ...orm@v0.8.1/engine.go:351:Ping() [I] PING DATABASE mysql
2020/05/31 15:35:25 routers/init.go:101:GlobalInit() [F] ORM engine initialization failed: commands out of sync. Did you run multiple statements at once?
2020/05/31 15:35:29 ...dules/setting/log.go:276:newLogService() [I] Gitea Log Mode: File(File:info)
2020/05/31 15:35:29 ...les/setting/cache.go:45:newCacheService() [I] Cache Service Enabled
2020/05/31 15:35:29 ...s/setting/session.go:44:newSessionService() [I] Session Service Enabled
2020/05/31 15:35:29 ...es/setting/mailer.go:106:newMailService() [I] Mail Service Enabled
2020/05/31 15:35:29 ...es/setting/mailer.go:117:newRegisterMailService() [I] Register Mail Service Enabled
2020/05/31 15:35:29 ...es/setting/mailer.go:128:newNotifyMailService() [I] Notify Mail Service Enabled
2020/05/31 15:35:29 routers/init.go:59:initDBEngine() [I] Beginning ORM engine initialization.
2020/05/31 15:35:29 routers/init.go:66:initDBEngine() [I] ORM engine initialization attempt #1/10...
2020/05/31 15:35:29 ...orm@v0.8.1/engine.go:351:Ping() [I] PING DATABASE mysql
2020/05/31 15:35:29 routers/init.go:72:initDBEngine() [E] ORM engine initialization attempt #1/10 failed. Error: commands out of sync. Did you run multiple statements at once?
2020/05/31 15:35:29 routers/init.go:73:initDBEngine() [I] Backing off for 3 seconds
2020/05/31 15:35:32 routers/init.go:66:initDBEngine() [I] ORM engine initialization attempt #2/10...
2020/05/31 15:35:32 ...orm@v0.8.1/engine.go:351:Ping() [I] PING DATABASE mysql
2020/05/31 15:35:32 routers/init.go:72:initDBEngine() [E] ORM engine initialization attempt #2/10 failed. Error: commands out of sync. Did you run multiple statements at once?
2020/05/31 15:35:32 routers/init.go:73:initDBEngine() [I] Backing off for 3 seconds
2020/05/31 15:35:35 routers/init.go:66:initDBEngine() [I] ORM engine initialization attempt #3/10...
2020/05/31 15:35:35 ...orm@v0.8.1/engine.go:351:Ping() [I] PING DATABASE mysql
2020/05/31 15:35:35 routers/init.go:72:initDBEngine() [E] ORM engine initialization attempt #3/10 failed. Error: commands out of sync. Did you run multiple statements at once?
2020/05/31 15:35:35 routers/init.go:73:initDBEngine() [I] Backing off for 3 seconds
2020/05/31 15:35:38 routers/init.go:66:initDBEngine() [I] ORM engine initialization attempt #4/10...
2020/05/31 15:35:38 ...orm@v0.8.1/engine.go:351:Ping() [I] PING DATABASE mysql
2020/05/31 15:35:38 routers/init.go:72:initDBEngine() [E] ORM engine initialization attempt #4/10 failed. Error: commands out of sync. Did you run multiple statements at once?
2020/05/31 15:35:38 routers/init.go:73:initDBEngine() [I] Backing off for 3 seconds
2020/05/31 15:35:41 routers/init.go:66:initDBEngine() [I] ORM engine initialization attempt #5/10...
2020/05/31 15:35:41 ...orm@v0.8.1/engine.go:351:Ping() [I] PING DATABASE mysql
2020/05/31 15:35:41 routers/init.go:72:initDBEngine() [E] ORM engine initialization attempt #5/10 failed. Error: commands out of sync. Did you run multiple statements at once?
2020/05/31 15:35:41 routers/init.go:73:initDBEngine() [I] Backing off for 3 seconds
2020/05/31 15:35:44 routers/init.go:66:initDBEngine() [I] ORM engine initialization attempt #6/10...
2020/05/31 15:35:44 ...orm@v0.8.1/engine.go:351:Ping() [I] PING DATABASE mysql
2020/05/31 15:35:44 routers/init.go:72:initDBEngine() [E] ORM engine initialization attempt #6/10 failed. Error: commands out of sync. Did you run multiple statements at once?
2020/05/31 15:35:44 routers/init.go:73:initDBEngine() [I] Backing off for 3 seconds
2020/05/31 15:35:47 routers/init.go:66:initDBEngine() [I] ORM engine initialization attempt #7/10...
2020/05/31 15:35:47 ...orm@v0.8.1/engine.go:351:Ping() [I] PING DATABASE mysql
2020/05/31 15:35:47 routers/init.go:72:initDBEngine() [E] ORM engine initialization attempt #7/10 failed. Error: commands out of sync. Did you run multiple statements at once?
2020/05/31 15:35:47 routers/init.go:73:initDBEngine() [I] Backing off for 3 seconds
2020/05/31 15:35:50 routers/init.go:66:initDBEngine() [I] ORM engine initialization attempt #8/10...
2020/05/31 15:35:50 ...orm@v0.8.1/engine.go:351:Ping() [I] PING DATABASE mysql
2020/05/31 15:35:50 routers/init.go:72:initDBEngine() [E] ORM engine initialization attempt #8/10 failed. Error: commands out of sync. Did you run multiple statements at once?
2020/05/31 15:35:50 routers/init.go:73:initDBEngine() [I] Backing off for 3 seconds
2020/05/31 15:35:53 routers/init.go:66:initDBEngine() [I] ORM engine initialization attempt #9/10...
2020/05/31 15:35:53 ...orm@v0.8.1/engine.go:351:Ping() [I] PING DATABASE mysql
2020/05/31 15:35:53 routers/init.go:72:initDBEngine() [E] ORM engine initialization attempt #9/10 failed. Error: commands out of sync. Did you run multiple statements at once?
2020/05/31 15:35:53 routers/init.go:73:initDBEngine() [I] Backing off for 3 seconds
2020/05/31 15:35:56 routers/init.go:66:initDBEngine() [I] ORM engine initialization attempt #10/10...
2020/05/31 15:35:56 ...orm@v0.8.1/engine.go:351:Ping() [I] PING DATABASE mysql
2020/05/31 15:35:56 routers/init.go:101:GlobalInit() [F] ORM engine initialization failed: commands out of sync. Did you run multiple statements at once?
2020/05/31 15:36:00 ...dules/setting/log.go:276:newLogService() [I] Gitea Log Mode: File(File:info)
2020/05/31 15:36:00 ...les/setting/cache.go:45:newCacheService() [I] Cache Service Enabled
2020/05/31 15:36:00 ...s/setting/session.go:44:newSessionService() [I] Session Service Enabled
2020/05/31 15:36:00 ...es/setting/mailer.go:106:newMailService() [I] Mail Service Enabled
2020/05/31 15:36:00 ...es/setting/mailer.go:117:newRegisterMailService() [I] Register Mail Service Enabled
2020/05/31 15:36:00 ...es/setting/mailer.go:128:newNotifyMailService() [I] Notify Mail Service Enabled
2020/05/31 15:36:00 routers/init.go:59:initDBEngine() [I] Beginning ORM engine initialization.
2020/05/31 15:36:00 routers/init.go:66:initDBEngine() [I] ORM engine initialization attempt #1/10...
2020/05/31 15:36:00 ...orm@v0.8.1/engine.go:351:Ping() [I] PING DATABASE mysql
2020/05/31 15:36:00 routers/init.go:72:initDBEngine() [E] ORM engine initialization attempt #1/10 failed. Error: commands out of sync. Did you run multiple statements at once?
2020/05/31 15:36:00 routers/init.go:73:initDBEngine() [I] Backing off for 3 seconds
2020/05/31 15:36:01 ...eful/manager_unix.go:133:handleSignals() [W] PID 885. Received SIGTERM. Shutting down...
2020/05/31 15:36:01 .../graceful/manager.go:184:doHammerTime() [W] Setting Hammer condition
2020/05/31 15:36:02 .../graceful/manager.go:198:doTerminate() [W] Terminating
2020/05/31 15:36:03 routers/init.go:101:GlobalInit() [F] ORM engine initialization failed: Aborted due to shutdown:
	in retry ORM engine initialization
</pre></details>

**Comment by techknowlogick** [comment]
Looking at your logs it looks like the only SQL statement that is run is `PING DATABASE mysql` and that is what it is failing on. Are you able to run this query directly against your database?

**Comment by AlphaJack** [comment]
Do you mean running it in MariaDB shell? I get the following error:
```mysql
MariaDB [(none)]> show databases;
+--------------------+
| Database           |
+--------------------+
| gitea-db           |
| information_schema |
| mysql              |
| performance_schema |
+--------------------+
8 rows in set (2.531 sec)


MariaDB [(none)]> PING DATABASE mysql;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'PING DATABASE mysql' at line 1
```


If I remove the install lock and try to setup the database from the web gui I get the error I encountered the first time I installed Gitea:

```
The database settings are invalid: commands out of sync. Did you run multiple statements at once?
```

**Comment by AlphaJack** [comment]
Tried #9279, I can use MySQL if I set the sock binding
in `/etc/my.cnf`:
```ini
[mysqld]
socket = /var/run/mysqld/mysqld.sock
```

in `/etc/gitea/app.ini`:
```ini
HOST                = /var/run/mysqld/mysqld.sock
;HOST                = 127.0.0.1:3306
```

Why?

**Comment by zeripath** [comment]
I suspect you need to set: 

``ini
[database]
NAME=gitea-db
...
```

**Comment by zeripath** [comment]
I suspect the issue is the lack of permission to connect over TCP. I note that you said you ran:

```sql
GRANT ALL ON gitea-db.* TO 'gitea'@'localhost' IDENTIFIED BY 'XXXXXX' WITH GRANT OPTION;
FLUSH PRIVILEGES;
EXIT;
```

This does not necessarily give access to tcp connection over 127.0.0.1

See https://stackoverflow.com/questions/19712307/mysql-localhost-127-0-0-1

I suggest you try:

```sql
GRANT ALL ON gitea-db.* TO 'gitea'@127.0.0.1 IDENTIFIED BY 'XXXXXX' WITH GRANT OPTION;
FLUSH PRIVILEGES;
EXIT;
```

I appreciate that`mysql -u gitea -p gitea-db` may work but that is connecting to mysql over its unix socket you would need to use `mysql --protocol=TCP -u gitea -p gitea-db` to force mysql's client to go over TCP.

**Comment by AlphaJack** [comment]
`mysql --protocol=TCP -u gitea -p gitea-db` returns
```
ERROR 1130 (HY000): Host '127.0.0.1' is not allowed to connect to this MariaDB server
```
I noticed the same error for other users. 

[This answer](https://stackoverflow.com/a/46045880) from the link you posted helped me, I had `skip-name-resolve = 1` in `/etc/my.cnf`

Thank you
