### ISSUE TITLE
Filter repositories by type

### ISSUE THREAD

**Issue by pgaskin** [go-gitea/gitea#1170]
An option to filter the repositories (on user and explore pages) by type (mirror, repository, fork, private, public) would be useful.

**Comment by thejavascriptman** [comment]
I was just able to make a mockup which should address this issue and make #1318 a duplicate if implemented, hope it helps someone who wants to implement this feature.

![mockup](https://user-images.githubusercontent.com/46071365/61579089-8ab44180-ab3b-11e9-8405-9b73ce587e02.png)
