### ISSUE TITLE
Weird behavior when migrating from Github to gitea.com

### ISSUE THREAD

**Issue by j-be** [go-gitea/gitea#11705]
- Gitea version (or commit ref): 1.13.0+dev-30-gb02d2c377
- Git version: whatever gitea.com runs on
- Operating system: whatever gitea.com runs on
- Database (use `[x]`): whatever gitea.com runs on
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant

## Description

While working on #8380 I migrated https://github.com/go-gitea/test_repo to https://gitea.com/j-be/test_repo/ and took that for unit tests. I am now a bit confused on how some stuff is handled when migrating:

* `Reactions`:
  * `lunny` is taken over as `UserID: 1, UserName: "lunny"`, as that user exists on Gitea too 
  * `mrsdizzie` as user in `Reactions` is migrated as `UserID: -1, UserName: "mrsdizzie(github)"`, which looks really good in the UI, but `mrsdizzie` would exist on Gitea as well - I guess OIDC is involved here, but how does it know? Do I need to take into account something here as well?
* `Review` - here is where it gets really confusing:
  * `lunny` and `jolheiser` are both taken over as `ReviewerID: 0`, even though the accounts would exist on gitea.com
  * `Review`s from both `zeripath` and `lafriks` are suddenly mine (`ReviewerID: 5610, ReviewerName: "j-be"`), again, even though these users exist on gitea.com

* `Release`, `PullRequest`, and `Comment`s thereof are all `PublisherID: 5610, PublisherName:   "j-be"` and `PosterID: 5610, PosterName:  "j-be"`, even though they should still be owned by their initial authors.

**Comment by lunny** [comment]
Because `lunny` on gitea.com (that's me :)) has binding github login, so we can replace the external account as an internal account, but mrsdizzie hasn't binding github login, so It displayed as external account.

**Comment by lunny** [comment]
<img width="900" alt="图片" src="https://user-images.githubusercontent.com/81045/83366524-38da7a00-a3e2-11ea-9b2e-23a50db78108.png">
It should have some bugs here.
