### ISSUE TITLE
[BUG] The information in commit detail page was incorrect

### ISSUE THREAD

**Issue by L0veSunshine** [go-gitea/gitea#11709]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes (provide example URL) https://gitea.com/gitnex/GitNex/commit/7f0689524f2132cd52042f53eee93c43778358b8?lang=en-US
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

When you visit a commit's detail page, if this commit is a merge opeation. The information on the page was a bit incorrect.
As you can see in this screenshot:
The parent commit is incorrect.
![image](https://user-images.githubusercontent.com/19653204/83357096-f04c9d80-a39c-11ea-8570-6e0c4b3d3402.png)

**Comment by CirnoT** [comment]
What exactly do you mean by that?
The commit `7f0689524f2132cd52042f53eee93c43778358b8` has two parents: `29756511f3f3c2e32a7d89bb051a2494cc942211` and `a4afa5fbc2fe9e6fea17788975987cf6faab382f`

You should get same result by doing `git log -1 7f0689524f2132cd52042f53eee93c43778358b8`

![chrome_2020-05-31_22-55-23](https://user-images.githubusercontent.com/1447794/83362474-da85ab00-a391-11ea-8d4b-2f3e0a15d345.png)

**Comment by L0veSunshine** [comment]
> What exactly do you mean by that?
> The commit `7f0689524f2132cd52042f53eee93c43778358b8` has two parents: `29756511f3f3c2e32a7d89bb051a2494cc942211` and `a4afa5fbc2fe9e6fea17788975987cf6faab382f`
> 
> You should get same result by doing `git log -1 7f0689524f2132cd52042f53eee93c43778358b8`
> 
> ```
> commit 7f0689524f2132cd52042f53eee93c43778358b8
> Merge: 2975651 a4afa5f
> Author: M M Arif <mmarif@swatian.com>
> Date:   Fri May 15 22:08:29 2020 +0000
> 
>     Merge pull request 'Add corners to popup dialogs' (#495) from ui-enhancements into master
> 
>     Reviewed-on: https://gitea.com/gitnex/GitNex/pulls/495
>     Reviewed-by: opyale <opyale@noreply.gitea.io>
> ```
> 
> ![chrome_2020-05-31_22-55-23](https://user-images.githubusercontent.com/1447794/83362474-da85ab00-a391-11ea-8d4b-2f3e0a15d345.png)

I am very sorry for the late reply.
After checking about this again, i confirm you are right, that is only a ui issue.
Thanks for your pr!
