### ISSUE TITLE
Multiple `git blame` processes stick around

### ISSUE THREAD

**Issue by mqudsi** [go-gitea/gitea#11716]
- Gitea version (or commit ref): 08208cdfb87bc3f0b534eda9d9ef265dcfbc18c3
- Git version: 2.25.0
- Operating system: FreeBSD 12
- Database (use `[x]`):
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:

## Description

I often find multiple `git blame` instances launched by `gitea` sticking around forever. They're not unreaped child processes, they're actually still running.

Sometimes attaching truss/strace/dtrace shows nothing, but other times it shows that they are actively writing:

```
mqudsi@freebsd> sudo truss -p 9222  # this is one of the "stuck" `git blame` processes
write(1,"<\\/tr><tr><td style=\\"text-ali"...,3718) = 3718 (0xe86)
write(1,"-align:middle;\\" width=\\"28\\""...,4096) = 4096 (0x1000)
write(1,"">24<\\/td><td style=\\"text-ali"...,4096) = 4096 (0x1000)
write(1,"er;vertical-align:middle;\\" wid"...,4096) = 4096 (0x1000)
write(1,"h=\\"28\\">33<\\/td><td style=\\"...,4096) = 4096 (0x1000)
write(1,"ical-align:middle;\\" rowspan=\\"...,4096) = 4096 (0x1000)
write(1,"\\" style=\\"text-align:center;v"...,4096) = 4096 (0x1000)
write(1,"l-align:middle;\\">33<\\/td><td "...,4096) = 4096 (0x1000)
write(1,"8\\" style=\\"text-align:center;"...,4096) = 4096 (0x1000)
write(1,"n:middle;\\">33<\\/td><\\/tr><tr"...,4096) = 4096 (0x1000)
write(1," style=\\"text-align:center;vert"...,4096) = 4096 (0x1000)
write(1,"e=\\"text-align:center;vertical-"...,4096) = 4096 (0x1000)

```

## Screenshots
![image](https://user-images.githubusercontent.com/606923/83363462-4ac70900-a35f-11ea-887c-1a84a64de109.png)

**Comment by lunny** [comment]
```go
func createBlameReader(dir string, command ...string) (*BlameReader, error) {
	// FIXME: graceful: This should have a timeout
	ctx, cancel := context.WithCancel(DefaultContext)
```

**Comment by mqudsi** [comment]
Thanks. I opened #11727 as a "better than what we have now" solution.
