### ISSUE TITLE
[REQ] Add the DBAD license

### ISSUE THREAD

**Issue by TheTechRobo** [go-gitea/gitea#11710]
- Gitea version (or commit ref): 1.11.6
- Git version: 2.26.2
- Operating system: Debian
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MSSQL
  - [X] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant

## Description
I was wondering if you could add the [DBAD (Don't Be a Dick) Public License](https://github.com/thetechrobo/dbad). (My fork contains an extra clause.)

**Comment by techknowlogick** [comment]
Thank you for your ticket, we pull licenses from the upstream repo: https://github.com/spdx/license-list-data and so if you'd like to be included in the list that is the place to contribute. However, if you want it to just be on your list just on your instance you can look into https://docs.gitea.io/en-us/customizing-gitea/ and add the file in your custom dir at options/licenses.

I will close this ticket now, please re-open if the license has been merged upstream.
