### ISSUE TITLE
Deleting image attachment from issue continues to show attachment until page reload

### ISSUE THREAD

**Issue by bjj** [go-gitea/gitea#11711]
- Gitea version (or commit ref):  1.12.0+dev-320-g4a04740da (docker image d0d4dd915d2e)
- Git version:
- Operating system: Docker on a Synology NAS
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (below from https://try.gitea.io/bjj/x/issues/1 )
  - [ ] No
  - [] Not relevant
- Log gist:

## Description

Deleting attachment from an issue continues to show the attachment until the page is reloaded. Attachment link actually continues to work.

...

## Create issue and drag in attachment:

![image](https://user-images.githubusercontent.com/62541/83359379-b9d83980-a32e-11ea-87f6-4a04b406bcab.png)

## Edit, remove attachment

![image](https://user-images.githubusercontent.com/62541/83359383-c5c3fb80-a32e-11ea-9905-4cc6efce34c6.png)

## (note attachment still showing) Hit Save

![image](https://user-images.githubusercontent.com/62541/83359390-d07e9080-a32e-11ea-84bf-f103db5ab7d1.png)

## Attachment still visible (and link still works!)

![image](https://user-images.githubusercontent.com/62541/83359400-d8d6cb80-a32e-11ea-9d63-6bb24df17f7e.png)

## Looks correct after reloading

![image](https://user-images.githubusercontent.com/62541/83359407-dffdd980-a32e-11ea-92f4-b494abe9ad69.png)

**Comment by lunny** [comment]
I think this has been resolved. Please feel free to reopen it if it's still a problem.
