### ISSUE TITLE
password decryption

### ISSUE THREAD

**Issue by lsy2534** [go-gitea/gitea#11719]
- Gitea version (or commit ref): 1.9.3
- Git version:
- Operating system: ubunt
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
Can you help me decipher the password in the user table?
The algorithm says, "pbkdf2."

**Comment by a1012112796** [comment]
Hello. In general, it can't be decipher. But you can change it by setting a new passwd, Thanks 
By the way, the ``1.9.3`` is an old version, suggest update to ``1.11.x``.

**Comment by lsy2534** [comment]
Thank you.
Can I know how to change it by setting the new password?

**Comment by techknowlogick** [comment]
@lsy2534 please refer to CLI docs on how to change password: https://docs.gitea.io/en-us/command-line/

I will close this ticket now.
