### ISSUE TITLE
Support "Viewed" option in Pull Requests

### ISSUE THREAD

**Issue by VishwasShashidhar** [go-gitea/gitea#11730]
- Gitea version (or commit ref): 1.8.2
- Git version: N/A
- Operating system: N/A

## Description

For Pull Requests that contain a lot of files being changed / added, it helps to have an option (like in GitHub) where in you can mark the file as `viewed` and review the remaining files in multiple sessions.
...

## Screenshots

<img width="1390" alt="Screenshot 2020-06-02 at 12 42 25" src="https://user-images.githubusercontent.com/5968790/83490975-99df7c00-a4ce-11ea-9109-9e58776440f7.png">

**Comment by a1012112796** [comment]
ping :)

**Comment by 6543** [comment]
for the Backend Part who notice changes to files, there are 2 TODOs:
 * extend checkIfPRContentChanged to return file list
 * move AddTestPullRequestTask into queue

revs:
https://github.com/go-gitea/gitea/blob/master/services/pull/pull.go#L233
https://github.com/go-gitea/gitea/blob/a598877fdf64a37b20eb1bf4372cbe798fc94486/services/pull/pull.go#L368-L378
