### ISSUE TITLE
Commit URL environment variable

### ISSUE THREAD

**Issue by sshaikh** [go-gitea/gitea#11738]
As well as GITEA_REPO_NAME and GITEA_REPO_USER_NAME, something like GITEA_COMMIT_URL would be great to push out by post_receive scripts. At the moment I'm constructing them (not a big deal).

**Comment by sshaikh** [comment]
I'd still find this useful

**Comment by zeripath** [comment]
@sshaikh Do you mean you'd like the environment variable GITEA_COMMIT_URL to be set to say: https://gitea.com/xorm/xorm/commit/76d6b9fdf55b1cc4ed9a8bb8b1cdc0910cdff92e

That doesn't make sense. The best we could provide would be to set the gitea APP_URL as an environment variable.

Git's post-receive scripts receive on stdin the list of refs changed: [1]

```
<old-SHA> SP <new-SHA> SP <ref-name> LF
```

Any number of commits may have occurred between old-SHA and new-SHA and any number of refs might be updated. You will always have to regenerate the urls yourself.

[1] https://git-scm.com/docs/githooks#pre-receive

**Comment by sshaikh** [comment]
Yes, I actually meant the URL up until the username part, so APP_URL would probably be a better name.
