### ISSUE TITLE
Make the version within makefile overwriteable

### ISSUE THREAD

**Issue by tboerger** [go-gitea/gitea#1173]
The maintainers of the Alpine package asked to make the version overwriteable to match the version format required by APK.

**Comment by clandmeter** [comment]
The makefile will try to lookup the version from git, but when building from tarball it will find the git information from the parent git repo (in this case Alpine Linux aports).

We now try to fix it by using:

https://github.com/alpinelinux/aports/blob/master/community/gitea/allow-to-set-version.patch
