### ISSUE TITLE
Add tag comparison

### ISSUE THREAD

**Issue by TheTechRobo** [go-gitea/gitea#11743]
## Description

When I click on "x commits to master since this release" in a Gitea release, it isn't a link. When I compare two branches but replace a branch name with the tag, it says everything is up-to-date even though 22 commits have been pushed since. I don't think this is a bug, so could you add it? Thanks! :)

(I was using the web version of Gitea (gitea.com) on a tested migration repo.)

## Screenshots

![not a link](https://user-images.githubusercontent.com/52163910/83584119-2fe9c580-a514-11ea-9ddd-f17f3bb217e9.jpg)
![not able to compar](https://user-images.githubusercontent.com/52163910/83584123-311af280-a514-11ea-849f-aa11b66a76a7.jpg)

**Comment by TheTechRobo** [comment]
The first image shows that I just get a text cursor when I hover over the "x commits to master" text, the second shows how there is "no need to create a PR".

**Comment by jolheiser** [comment]
The first is a feature request, however the second is because you have base/head mixed up.

https://gitea.com/TheTechRobo/palc-attempt2/compare/v.0.8.4-stable...master

**Comment by a1012112796** [comment]
Suggest add compare link in release page like github. 
![image](https://user-images.githubusercontent.com/25342410/84508531-017aa000-acf5-11ea-9186-b890150e9d5d.png)

**Comment by jtran** [comment]
See PR #15695.
