### ISSUE TITLE
Wrong link in activity tab

### ISSUE THREAD

**Issue by nidgetgod** [go-gitea/gitea#1174]
- Gitea version (or commit ref): 1.1.0+4-g05f0c4bb
- Git version: 1.7.4
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)

## Description

In anyone's activity tab, someone like this: [lalaland - Gitea: Git with a cup of tea](https://try.gitea.io/lalaland?tab=activity))

Click on the link like [lalaland/gitea](https://try.gitea.io/%5C%22/lalaland/gitea%5C%22) or [lalaland/test](https://try.gitea.io/%5C%22/lalaland/test%5C%22) will redirect to 404 page.

**Comment by lunny** [comment]
It seems the translation bugs
