### ISSUE TITLE
0x17d2430 next to notifications

### ISSUE THREAD

**Issue by Jab2870** [go-gitea/gitea#11750]
- Gitea version (or commit ref):     1.13.0+dev-60-g0a7c5623d built with GNU Make 4.2.1, go1.14.3 : bindata, sqlite, sqlite_unlock_notify
- Operating system: Docker
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description

I am seeing what looks like a hex value next to the notifications.  0x17d2430

## Screenshots

![image](https://user-images.githubusercontent.com/1909202/83685318-655be500-a5e0-11ea-9a36-f897792e147c.png)

**Comment by zeripath** [comment]
Could you check your web console? There's likely to be an error. 

We could also do with some logs and what browser you're running this on.

**Comment by Jab2870** [comment]
Thanks for your help. I am using Firefox:

![image](https://user-images.githubusercontent.com/1909202/83731921-3034ae80-a643-11ea-8e6e-97cb29b7fc28.png)

I notice it says about private browsing mode, I am using a normal (not private) window.

As for logs, I have attached the docker log output. I hope that is what you are after

[gitea.log](https://github.com/go-gitea/gitea/files/4728501/gitea.log)

**Comment by lafriks** [comment]
Are you using any firefox extensions that could be affecting this?

**Comment by Jab2870** [comment]
I use very few plugins. Disabling all of them doesn't fix the issue

**Comment by silverwind** [comment]
Do you have "Delete cookies and site data when Firefox is closed" enabled in Firefox? See https://dev.webonomic.nl/fixing-firefox-failed-to-register-update-a-serviceworker-for-scope if that's the case.

Thought I generally don't think the blockage of the serviceworker is related to this particular issue, but we should attempt to catch this error.

**Comment by AlmCoder** [comment]
I am also experiencing the same problem after updating to Gitea 1.12.0 rc2. This error also occurs when using Safari web browser.

**Comment by Jab2870** [comment]
Yes, I do have cookies delete when Firefox is closed.

I have added an exception for my gitea instance. Here are the dev tools now:

![image](https://user-images.githubusercontent.com/1909202/84175269-a2f4be00-aa77-11ea-8a73-9bb2b6a76711.png)

**Comment by silverwind** [comment]
Did it change anything about the hex value?

**Comment by silverwind** [comment]
BTW, the serviceworker error seems to be considered a bug in Firefox and they do want to allow service workers with that setting enabled (but not in private mode). The error spam can not be suppressed (except one line that we do log ourselves) because it's the browser logging the error.

**Comment by Jab2870** [comment]
@silverwind , no, it didn't fix the issue. I am still seeing the hex value.

Please do let me know if there is anything else I can do to help with this issue.

**Comment by zeripath** [comment]
@Jab2870 are you able to build Gitea? would it be possible to add some logging in to `web_src/js/features/notification.js`  to try to figure out what the problem is?

**Comment by zeripath** [comment]
Oh one other thing is do you have your own templates?

That may be the problem

**Comment by Jab2870** [comment]
@zeripath

> Oh one other thing is do you have your own templates?

Yes, I do. I have just updated it and the error has gone. Thanks very much for your help
