### ISSUE TITLE
Icon at wrong position

### ISSUE THREAD

**Issue by nidgetgod** [go-gitea/gitea#1175]
- Gitea version (or commit ref): 1.1.0+4-g05f0c4bb
- Git version: 1.7.4
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes [https://try.gitea.io/lunny?tab=activity](https://try.gitea.io/lunny?tab=activity)

## Description

Icon should at right-top of activity.

## Screenshots

![2017-03-10 11-48-33](https://cloud.githubusercontent.com/assets/4176953/23781418/209aadbc-0588-11e7-948c-3234a5d1c315.png)

**Comment by lunny** [comment]
should be closed by #1177
