### ISSUE TITLE
Gitea crashes on startup after running "Delete all repository archives" (view logs)

### ISSUE THREAD

**Issue by Nathan13888** [go-gitea/gitea#11754]
- Gitea version (or commit ref): `v1.13.0+dev-117-ga3b185d54`
- Git version: `2.20.1 (for host)`
- Operating system: `Docker (Debian Buster)`
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x ] Not relevant
- Log gist:

## Description

Gitea worked perfectly fine before I changed some settings under the `server` section in `app.ini`. After I noticed this crashing, I immediately changed all the settings back to the original settings but the same problem would arise. I'm not sure but I believe that this would have happened even if I didn't change these settings.

`app.ini`:
[app.zip](https://github.com/go-gitea/gitea/files/4726590/app.zip)

Log from inside the Gitea container:
[gitea.log](https://github.com/go-gitea/gitea/files/4726604/gitea.log)

Log before crashing (in docker)
:
```
03 17:24:08 routers/init.go:120:GlobalInit() [T] AppWorkPath: /app/gitea


2020/06/03 17:24:08 routers/init.go:121:GlobalInit() [T] Custom path: /data/gitea


2020/06/03 17:24:08 routers/init.go:122:GlobalInit() [T] Log path: /data/gitea/log


2020/06/03 17:24:08 routers/init.go:127:GlobalInit() [I] Delete all repository archives


2020/06/03 17:24:08 ...dules/setting/log.go:233:newLogService() [I] Gitea v1.13.0+dev-117-ga3b185d54 built with GNU Make 4.3, go1.14.4 : bindata, sqlite, sqlite_unlock_notify


panic: runtime error: index out of range [0] with length 0



goroutine 1 [running]:


code.gitea.io/gitea/modules/setting.DBConnStr(0xff55927, 0x55934c0, 0xc0005a54f0, 0x6d0a47)


	/go/src/code.gitea.io/gitea/modules/setting/database.go:108 +0x93c


code.gitea.io/gitea/models.getEngine(0x0, 0x0, 0x0)


	/go/src/code.gitea.io/gitea/models/models.go:137 +0x26


code.gitea.io/gitea/models.SetEngine(0x2, 0x2)


	/go/src/code.gitea.io/gitea/models/models.go:168 +0x34


code.gitea.io/gitea/models.NewEngine(0x3f4e8c0, 0xc002da9dc0, 0x3aae5b8, 0x2b, 0xc0001f3000)


	/go/src/code.gitea.io/gitea/models/models.go:190 +0x26


code.gitea.io/gitea/routers.initDBEngine(0x3f4e8c0, 0xc002da9dc0, 0x21b6d0c, 0x2)


	/go/src/code.gitea.io/gitea/routers/init.go:72 +0x1f2


code.gitea.io/gitea/routers.GlobalInit(0x3f4e8c0, 0xc002da9dc0)


	/go/src/code.gitea.io/gitea/routers/init.go:135 +0x81f


code.gitea.io/gitea/cmd.runWeb(0xc0000d8f20, 0x0, 0x0)


	/go/src/code.gitea.io/gitea/cmd/web.go:116 +0x2c1


github.com/urfave/cli.HandleAction(0x1e507c0, 0x3aae538, 0xc0000d8f20, 0xc001738400, 0x0)


	/go/src/code.gitea.io/gitea/vendor/github.com/urfave/cli/app.go:490 +0xc8


github.com/urfave/cli.Command.Run(0x21bdcd6, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x22d6d5c, 0x16, 0x0, ...)


	/go/src/code.gitea.io/gitea/vendor/github.com/urfave/cli/command.go:210 +0x9e8


github.com/urfave/cli.(*App).Run(0xc000c6b6c0, 0xc00000e080, 0x2, 0x2, 0x0, 0x0)


	/go/src/code.gitea.io/gitea/vendor/github.com/urfave/cli/app.go:255 +0x741


main.main()


	/go/src/code.gitea.io/gitea/main.go:109 +0x8a3


Received signal 15; terminating.
...

**Comment by Nathan13888** [comment]
Does anyone have any idea of perhaps resetting something that way I could get gitea back up and running?? I am running the Gitea instance in Docker and I also have complete access to the external MySQL database which Gitea uses.

**Comment by Nathan13888** [comment]
It seems that Gitea crashes after running "Delete all repository archives". Is there a way to stop that?

**Comment by zeripath** [comment]
@Nathan13888 are you still getting the same panic? 

```
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
code.gitea.io/gitea/modules/setting.DBConnStr(0xff55927, 0x55934c0, 0xc0005a54f0, 0x6d0a47)
	/go/src/code.gitea.io/gitea/modules/setting/database.go:108 +0x93c
code.gitea.io/gitea/models.getEngine(0x0, 0x0, 0x0)
	/go/src/code.gitea.io/gitea/models/models.go:137 +0x26
code.gitea.io/gitea/models.SetEngine(0x2, 0x2)
	/go/src/code.gitea.io/gitea/models/models.go:168 +0x34
...
```

have you actually looked at the code for: `/go/src/code.gitea.io/gitea/modules/setting/database.go:108` ?

https://github.com/go-gitea/gitea/blob/4a4977a1f0232bcef474495b8e2e2b4e3ce12c49/modules/setting/database.go#L108


Looking at your provided app.ini: ```ini
...
[database]
PATH     = /data/gitea/gitea.db
DB_TYPE  = mysql
USER     = gitea
PASSWD   = **OMITTED**
SCHEMA   = 
SSL_MODE = disable
CHARSET  = utf8mb4

[indexer]
...
```

I see that HOST is not set. We don't provide a default:

https://github.com/go-gitea/gitea/blob/4a4977a1f0232bcef474495b8e2e2b4e3ce12c49/modules/setting/database.go#L73

Therefore your problem is that you haven't set a HOST

**Comment by Nathan13888** [comment]
Hi @zeripath, you were right about the `HOST` property as I seem to have accidentally removed this line along with another line `NAME` in `[database]`.

After these changes, the container no longer crashes instantly but after half a minute.

There are no details in the Docker log but I found this in the log within the container (view the end of the message).

I also compared an old working version of the config and there seems to have no more differences from the current config.

From the logs, it seems that Gitea is unable to communicate with MYSQL but the mysql container has been running non-stop for a month or two already without problems and haven't been changed by me either.

```
2020/06/11 10:03:40 ...rm/session_schema.go:25:Ping() [I] PING DATABASE mysql
2020/06/11 10:03:40 ...m.io/xorm/core/db.go:154:QueryContext() [I] [SQL] SELECT `TABLE_NAME` from `INFORMATION_SCHEMA`.`TABLES` WHERE `TABLE_SCHEMA`=? and `TABLE_NAME`=? [ version] - 445.593µs
2020/06/11 10:03:40 ...m.io/xorm/core/db.go:277:ExecContext() [I] [SQL] CREATE TABLE IF NOT EXISTS `version` (`id` BIGINT(20) PRIMARY KEY AUTO_INCREMENT NOT NULL, `version` BIGINT(20) NULL) DEFAULT CHARSET utf8mb4 ROW_FORMAT=DYNAMIC [] - 92.163µs
2020/06/11 10:03:40 routers/init.go:77:initDBEngine() [E] ORM engine initialization attempt #9/10 failed. Error: migrate: sync: Error 1046: No database selected
2020/06/11 10:03:40 routers/init.go:78:initDBEngine() [I] Backing off for 3 seconds
2020/06/11 10:03:43 routers/init.go:71:initDBEngine() [I] ORM engine initialization attempt #10/10...
2020/06/11 10:03:43 ...rm/session_schema.go:25:Ping() [I] PING DATABASE mysql
2020/06/11 10:03:43 ...m.io/xorm/core/db.go:154:QueryContext() [I] [SQL] SELECT `TABLE_NAME` from `INFORMATION_SCHEMA`.`TABLES` WHERE `TABLE_SCHEMA`=? and `TABLE_NAME`=? [ version] - 483.875µs
2020/06/11 10:03:43 ...m.io/xorm/core/db.go:277:ExecContext() [I] [SQL] CREATE TABLE IF NOT EXISTS `version` (`id` BIGINT(20) PRIMARY KEY AUTO_INCREMENT NOT NULL, `version` BIGINT(20) NULL) DEFAULT CHARSET utf8mb4 ROW_FORMAT=DYNAMIC [] - 119.583µs
2020/06/11 10:03:43 routers/init.go:138:GlobalInit() [F] ORM engine initialization failed: migrate: sync: Error 1046: No database selected
```

**Comment by Nathan13888** [comment]
Btw, I retried multiple times and have come to the same error in the log

**Comment by zeripath** [comment]
Gitea cannot connect to your database. You need to check the rest of your config.

I suspect the hint is here: `PING DATABASE mysql` - implying that you've set `NAME=mysql`

But that's very unlikely to the name of the Gitea database.

I suggest you check the results of `SHOW DATABASES` from mysql.
