### ISSUE TITLE
bug:ui bug on merge way choose box

### ISSUE THREAD

**Issue by a1012112796** [go-gitea/gitea#11759]
- Gitea version (or commit ref): 1.13.0+dev-120-gb534a5164 (master last commit)
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

See Screenshots

## Screenshots

![image](https://user-images.githubusercontent.com/25342410/83770514-bbe62380-a6b3-11ea-980a-5de6cf7d500a.png)

**Comment by CirnoT** [comment]
Introduced by https://github.com/go-gitea/gitea/commit/3affe9516afd224a85572f72878fd2ae7e4d58b6
