### ISSUE TITLE
Deprecate and remove shared secret from webhook payloads

### ISSUE THREAD

**Issue by JustAnotherArchivist** [go-gitea/gitea#11755]
Gitea currently sends the `secret` in the webhook payload in plaintext. This renders signature validation entirely useless since an attacker could freely manipulate the payload without detection.

Signatures were originally requested in #3901 and added in #6428. This problem was also mentioned in a comment in the former, but no separate issue for this security problem has been filed. Since then, it has been mentioned in a few comments that the `secret` is deprecated and will be removed (e.g. <https://github.com/go-gitea/gitea/issues/7487#issuecomment-629673826>, <https://github.com/go-gitea/gitea/issues/5173#issuecomment-618408121>). However, a deprecation notice in the changelog and the documentation is missing, so only few people will notice.

An official deprecation warning should be added to the changelog as soon as possible, ideally with the release of 1.12.0. This should also include information on when the field will be removed entirely.

**Comment by JustAnotherArchivist** [comment]
A note on the webhook documentation: that's already quite outdated (missing fields, headers, etc.) and very incomplete. I'm working on a full rewrite (cf. #9485), but I currently don't know when that will be finished. Until then, I'd suggest simply adding a deprecation warning above the push example with a reference to the `X-Gitea-Signature` header. I will be adding a full description in my rewrite, but until then, the PHP example already illustrates how to validate that.

**Comment by JustAnotherArchivist** [comment]
Yes, this is still valid.

**Comment by zeripath** [comment]
AFAICS this is still present but it needs a security tag.

I don't understand completely why this was ever put there, and therefore I don't know why it hasn't been removed - but clearly it needs to be dealt with.

Now this is too late for 1.13 but I think we can just deprecate the secret from 1.13 so that it will be gone from 1.14 and anyone requiring it just has to do something about it.

**Comment by rakshith-ravi** [comment]
@zeripath shouldn't this be moved to `1.14.0` milestone instead of `1.14`? (Why do we even have `1.14` in the first place?) Just making sure there's no duplicate milestones created

**Comment by techknowlogick** [comment]
for milestones 1.14==1.14.0 but we have it so it includes what makes it into the RCs too

**Comment by JustAnotherArchivist** [comment]
Shouldn't this be on the 1.13.0 milestone until the deprecation warnings are in? Just trying to make sure this isn't delayed by another version due to this.

**Comment by techknowlogick** [comment]
@JustAnotherArchivist we will mention in 1.13.0 blog post

**Comment by JustAnotherArchivist** [comment]
I see. I feel like a warning should also be added to the webhook docs and config page.

**Comment by techknowlogick** [comment]
That's reasonable. Would you be open to making a PR :)

**Comment by JustAnotherArchivist** [comment]
Sure. I'll need some guidance on how to integrate it into the web UI though.

Also, I noticed that the secret is also included on Gogs webhooks. It appears like Gogs itself didn't have it in the payload since early 2017 (https://github.com/gogs/gogs/issues/3692), but that should be verified first to avoid breaking existing hooks.

**Comment by JustAnotherArchivist** [comment]
Checklist:

- [x] Add deprecation notice to the webhook docs in v1.13.0 – done in #13329
- [ ] Add deprecation warning to the webhook configuration page in v1.13.0 – please advise how such a warning should be integrated into the web UI; I assume there are already elements defined for warnings/errors but currently don't have time to dig into the source code and find this myself.
- [ ] Add deprecation notice in v1.13.0 release notes/announcement – @techknowlogick will do this.
- [ ] Remove field on master branch before v1.14 (including docs update)
- [ ] Breaking change notice in v1.14.0 release notes/announcement

**Comment by zeripath** [comment]
> Add deprecation warning to the webhook configuration page in v1.13.0 – please advise how such a warning should be integrated into the web UI; I assume there are already elements defined for warnings/errors but currently don't have time to dig into the source code and find this myself.

I don't think there's a sensible place for that - the webhook page simply links to gitea.io. I would guess that means we don't need to do anything about that.

**Comment by JustAnotherArchivist** [comment]
Thinking about it again, yeah, I guess you're right. The secret itself isn't being deprecated, only its inclusion in the payload, and the web interface makes no attempt to describe what the payload is (except that you can look at the payloads on delivered hooks).

**Comment by CirnoT** [comment]
Just FYI this will require appropriate PR for `go-scm` for Drone

https://github.com/drone/go-scm/blob/427b8a85897c892148801824760bc66d3a3cdcdb/scm/driver/gitea/webhook.go#L62-L72

**Comment by techknowlogick** [comment]
@CirnoT https://github.com/drone/go-scm/blob/427b8a85897c892148801824760bc66d3a3cdcdb/scm/driver/gitea/webhook.go#L76 should already be suitable, no?

**Comment by CirnoT** [comment]
Ah sorry, yes. That's `&&` there not `||`.

Also it uses `FormValue` so it looks for `?secret=` instead of actually examining Gitea's webhook body, meh...

**Comment by techknowlogick** [comment]
@CirnoT no worries, I added in support for the signature checking via header so I was worried I missed something haha. 

`FormValue` is from before my PR so I don't think that needs changing from querystring to webhook body, as that means it has been working that way since the start

**Comment by JustAnotherArchivist** [comment]
I believe `secret` was never in the query parameters at all. It was originally implemented in Gogs in commit e573855a and was in the payload back then already.

**Comment by CirnoT** [comment]
> I believe secret was never in the query parameters at all. It was originally implemented in Gogs in commit e573855 and was in the payload back then already.

It's part of URI that Drone installs as webhook; like I said, most likely workaround from when there was no support for signature in Gitea

**Comment by JustAnotherArchivist** [comment]
@techknowlogick It appears this was missed on the blog post unless I'm blind?

**Comment by techknowlogick** [comment]
@JustAnotherArchivist Thanks for reminder. I've just pushed up an update to the release blog post.
