### ISSUE TITLE
gitea 1.11.6 with drone: fetch fails

### ISSUE THREAD

**Issue by esosan** [go-gitea/gitea#11775]
- Gitea version (or commit ref): 1.11.6
- Git version: git version 2.17.1
- Operating system: ubuntu 18.04
- Database (use `[x]`):
  - MySQL

## Description
Starting with gitea 1.11.6 I have some problems with some repository: drone it's unable to fetch the repo and fail with this error:
+ git fetch origin +refs/heads/develop:
fatal: could not read Username for 'https://gitea.XXX.net': terminal prompts disabled

With gitea 1.11.5... everything work smoothly. With the same user other repository work fine.

**Comment by techknowlogick** [comment]
Is the repository "private", belong to a "limited" or "private" org? If so you may need to set `DRONE_GIT_ALWAYS_AUTH` on drone to true. This is due to security measures implemented in Gitea 1.11.6.

I will close this now, but if that doesn't work please feel free to re-open.
