### ISSUE TITLE
[Bug] Clicking Sign Out but Still Logged In

### ISSUE THREAD

**Issue by bagasme** [go-gitea/gitea#11787]
- Gitea version (or commit ref): 1.12.0+rc1 (compiled with Go 1.14.2, `TAGS=bindata`)
- Git version: 2.26.2
- Operating system: Debian 10
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist: [paste.ubuntu.com](https://paste.ubuntu.com/p/hphF4N5NCv/)

## Description
Sign out from Gitea will instead keep the user logged in.

However, I didn't see any symptoms in the log gist I attached.

Firefox DevTools logged JS `areYouSure` errors and warnings, possibly related to the bug:
```
jQuery.Deferred exception: $(...).areYouSure is not a function @https://gitnode.io/js/index.js?v=9245442d00d25735b3aa4bc8621e29f9:1:188176
l@https://gitnode.io/js/jquery.js?v=9245442d00d25735b3aa4bc8621e29f9:1:31032
a/</c<@https://gitnode.io/js/jquery.js?v=9245442d00d25735b3aa4bc8621e29f9:1:31334
setTimeout handler*a/<@https://gitnode.io/js/jquery.js?v=9245442d00d25735b3aa4bc8621e29f9:1:31543
u@https://gitnode.io/js/jquery.js?v=9245442d00d25735b3aa4bc8621e29f9:1:29314
fireWith@https://gitnode.io/js/jquery.js?v=9245442d00d25735b3aa4bc8621e29f9:1:30062
fire@https://gitnode.io/js/jquery.js?v=9245442d00d25735b3aa4bc8621e29f9:1:30098
u@https://gitnode.io/js/jquery.js?v=9245442d00d25735b3aa4bc8621e29f9:1:29314
fireWith@https://gitnode.io/js/jquery.js?v=9245442d00d25735b3aa4bc8621e29f9:1:30062
ready@https://gitnode.io/js/jquery.js?v=9245442d00d25735b3aa4bc8621e29f9:1:33048
_@https://gitnode.io/js/jquery.js?v=9245442d00d25735b3aa4bc8621e29f9:1:32826
EventListener.handleEvent*304/<@https://gitnode.io/js/jquery.js?v=9245442d00d25735b3aa4bc8621e29f9:1:33197
304/<@https://gitnode.io/js/jquery.js?v=9245442d00d25735b3aa4bc8621e29f9:1:1149
304@https://gitnode.io/js/jquery.js?v=9245442d00d25735b3aa4bc8621e29f9:1:1262
n@https://gitnode.io/js/jquery.js?v=9245442d00d25735b3aa4bc8621e29f9:1:110
1012@https://gitnode.io/js/jquery.js?v=9245442d00d25735b3aa4bc8621e29f9:1:1004
n@https://gitnode.io/js/jquery.js?v=9245442d00d25735b3aa4bc8621e29f9:1:110
1011@https://gitnode.io/js/jquery.js?v=9245442d00d25735b3aa4bc8621e29f9:1:947
n@https://gitnode.io/js/jquery.js?v=9245442d00d25735b3aa4bc8621e29f9:1:110
@https://gitnode.io/js/jquery.js?v=9245442d00d25735b3aa4bc8621e29f9:1:902
@https://gitnode.io/js/jquery.js?v=9245442d00d25735b3aa4bc8621e29f9:1:914
 undefined jquery.js:1:32593
```

```
Uncaught TypeError: $(...).areYouSure is not a function
    <anonymous> index.js:2664
    jQuery 20
index.js:2664:33
```

The bug does not occured on 1.13.0+dev-62-g8443ca109 on my LXD development container.

## Screenshots

![gitea-bug](https://user-images.githubusercontent.com/40219486/83965353-4c537c80-a8dd-11ea-9ca7-30225d7c657a.gif)

**Comment by hmht** [comment]
I have the same in 1.11.6.  I've logged out frequently in 1.10.3

**Comment by zeripath** [comment]
@bagasme I think there's possibly an issue with caching here. 

Certainly jquery.are-you-sure is listed as a dependency in the index.js and the package.json. 

Is there any way you could actually check if the areYouSure function is defined in the index.js that is served? e.g.

```bash
curl URL/js/index.js | grep -o 'areYouSure=function'
```

e.g. for try this is:

```bash
$ curl https://try.gitea.io/js/index.js | grep -o 'areYouSure=function'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  549k  100  549k    0     0   620k      0 --:--:-- --:--:-- --:--:--  619k
areYouSure=function
```

showing that it is defined and therefore the problem is caching.

**Comment by hmht** [comment]
in my installation the following command returns nothing:

```
curl http://example.com./js/index.js | grep -o 'areYouSure=function'
```

**Comment by zeripath** [comment]
@hmht No that shouldn't be a problem.

**Comment by zeripath** [comment]
@hmht 1.11 doesn't web pack the are you sure function so that grep wouldn't work for you. I still think this is very likely to be a caching issue.

**Comment by hmht** [comment]
Turns out the problem is that you need javascript enabled to log out.

**Comment by bagasme** [comment]
@hmht js is enabled by default on most browsers, unfortunately. Also, I had tested on both normal and private windows on my browser, and the problem still exists.

**Comment by zeripath** [comment]
@bagasme did you try the curl I mentioned?

**Comment by bagasme** [comment]
@zeripath nothing happened
