### ISSUE TITLE
locale_en-US.ini: file not found

### ISSUE THREAD

**Issue by Martmists-GH** [go-gitea/gitea#11790]
System last updated: June 7, 2020, 12:00 CEST
- Gitea version (or commit ref): Latest from Arch Repos 
- Git version: Latest from Arch Repos
- Operating system: Arch Linux
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist: [link](https://hastebin.com/osunirorog.rb)

## Description

Gitea errors without a clear indication of the absolute path of where the file is missing, but it is present in `/usr/share/gitea/options/locale/locale_en-US.ini`

My gitea has been running for months without issues.

**Comment by bagasme** [comment]
What are latest Git/Gitea version in your repo?

**Comment by martmists** [comment]
```
[mart@dilaton ~]$ git --version
git version 2.27.0
[mart@dilaton ~]$ gitea --version
Gitea version 1.11.6 built with GNU Make 4.3, go1.14.3 : sqlite, pam
```

**Comment by techknowlogick** [comment]
This is a downstream issue with arch. You’ll need to reach out to the package maintainers.

**Comment by martmists** [comment]
How is this an Arch issue? Gitea was working fine for months and without updating it, the issue occurred, so clearly this is a Gitea issue. Updating the package did not work either.

**Comment by techknowlogick** [comment]
This is an arch issue as they changed how they package gitea, and we have no control over that, and because of their change everyone who uses arch now has the issue you are experiencing. What is happening with the new package is that the gitea binary is not being told the correct location of these assets. As such there is nothing that Gitea the project can fix, and it would need to be resolved by the arch package maintainer.

Please reach out to the arch package maintainer to let them know your issue.

**Comment by zeripath** [comment]
hmm... you may be able to work around it by setting the GITEA_CUSTOM variable or adding --custom-path / -C options to your gitea call.

if you run `gitea --help` it should tell you where it is trying to find its files.

Likely something has gone awry with the settings for these things in the package - perhaps previously the package was overriding them with LDFLAGS which have now been dropped or changed.

**Comment by zeripath** [comment]
Please see: https://github.com/go-gitea/gitea/issues/11756#issuecomment-642684139

**Comment by zeripath** [comment]
Duplicated with #11756
