### ISSUE TITLE
Page with about Gitea project

### ISSUE THREAD

**Issue by joubertredrat** [go-gitea/gitea#118]
Hi Guys,

Before create new version of Gitea, I think that create a page explaining the reasons to create Gitea fork from Gogs, so it will be easier to understand and accept our community project

Look this examples:
Observium ==(fork)=> LibreNMS: http://docs.librenms.org/General/Welcome-to-Observium-users/
Zpanel ==(fork)=> Sentora: http://sentora.org/about
ownCloud ==(fork)=> NextCloud: http://karlitschek.de/2016/06/nextcloud/

What you think guys?

**Comment by alvaroaleman** [comment]
I'd really like that as well and also I'd like Gitea to use its own name in the docs instead of Gogs, so people can differentiate.

**Comment by metalmatze** [comment]
This will go into our [website](https://github.com/go-gitea/website) or [blog](https://github.com/go-gitea/blog) repos. Please find out the correct one on gitter and create an issue there.
