### ISSUE TITLE
Wiki repos should be hidden in repo lists.

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#118]
On home page, on my repositories, wiki repositories shows. @makhov 
![image](https://cloud.githubusercontent.com/assets/81045/8865784/dcfa5c54-31e6-11e5-891f-321ee58065d6.png)

**Comment by tboerger** [comment]
@lunny I can not reproduce it on latest develop. What have you done? I have created multiple repositories and added 2 wiki pages to the first repository.

**Comment by linquize** [comment]
Do you connect to DB to query repository table to see if any unusual value?
especially SQLite

**Comment by tboerger** [comment]
I just tried it locally with mysql

**Comment by lunny** [comment]
Hi, I find this on branch pr. @tboerger, maybe I need merge develop to pr.

**Comment by tboerger** [comment]
> Hi, I find this on branch pr. @tboerger, maybe I need merge develop to pr.

Maybe there is already one fix merged :)

**Comment by lunny** [comment]
Yeah.

**Comment by lunny** [comment]
This issue is not found on branch develop. So I close this issue.
