### ISSUE TITLE
Proposal: Support Well-Known URL for Password Change

### ISSUE THREAD

**Issue by Zocker1999NET** [go-gitea/gitea#11804]
## Description

Employees from Apple proposed to add a Well-Known URL for "Change Password" sites, so password managers could help the users to change their passwords more often (see https://wicg.github.io/change-password-url/index.html). This is still a draft itself, but supporting this feature could be fancy and should not be complicated. Following the draft itself, a redirect is allowed. Adding this feature should be easy (for go developers) and not have any disadvantages, if I'm not wrong.

For Gitea, this means that all requests at the URL `/.well-known/change-password` only must be forwarded to `/user/settings/account`.

**Comment by silverwind** [comment]
Sounds good to have, should probably be a 307 redirect.
