### ISSUE TITLE
[Bug] [API] make pagination optional for GET /api/user/repos

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#11800]
come up with #9452 in v1.12
ref https://github.com/go-gitea/gitea/pull/9452#issuecomment-640319866

**Comment by CirnoT** [comment]
Disagree, the mentioned comment clearly points at issue in Drone implementation which is missing pagination enumeration. We don't explicitly require pagination options to be set and with or without we need some sane limit on what we return. The instance might have 10 repos or it might have 2000 repos.

**Comment by 6543** [comment]
I'd like to have both

**Comment by 6543** [comment]
-> I'll take the gitea part

**Comment by CirnoT** [comment]
We definitely should NOT return all repos on API, instances can be small or can be huge.

This is not a bug but breaking change on our part since we added pagination; tools should now be updated to use it properly.

**Comment by lafriks** [comment]
@CirnoT yeah but we can not just break drone integration. We can add deprecation notice and ask for drone developers to use paging and later in next version drop that. I think drone integration is used quite extensively to just break it

**Comment by techknowlogick** [comment]
@lafriks the recent PR by @CirnoT provides a good way forward as it relies on app.ini setting for default response size, as if we don't have pagination then users with many repos could DOS themselves and run out of memory.

**Comment by 6543** [comment]
-> #11808

and for the DOS at witch point it get critical, we could add a hardcoded lim at 50/100/200 ...

**Comment by 6543** [comment]
#11805 ...

**Comment by lafriks** [comment]
@techknowlogick Yes but currently we do return all repos in versions <=v1.11

**Comment by CirnoT** [comment]
I think 30 is a sane default till a fix is pushed to `go-scm` for pagination support. People that can not update Drone for some reason will be able to adjust the default and max limits to their needs.

**Comment by lafriks** [comment]
At my company git I have about 100 repos so that will break drone integration for me ;)

**Comment by lafriks** [comment]
And as not everyone read changelog it will make a lot users not knowing why repos is not syncing anymore in drone and most probably they will complain to drone devs

**Comment by lafriks** [comment]
To give a point it is already creating confusion, see article comment: https://dev.to/ruanbekker/self-hosted-cicd-with-gitea-and-drone-ci-200l

**Comment by techknowlogick** [comment]
@lafriks with @CirnoT's PR you can change settings to increase value to 100 so that all your repos show up. All we can do is to put out the information, and send corrections to articles we see wrong. There are so many Gitea articles that say to wget version 1.2 of Gitea 😬

**Comment by lafriks** [comment]
I know that and I will do that but for many this will cause confusion, someone should really send PR to fix drone/gitea integration before we release 1.12

**Comment by ptman** [comment]
Are the drone developers even aware of this ongoing discussion? I too feel like deprecation first and removal later is the right approach. Maybe allow turning off compat for deprecated features in config?

**Comment by lafriks** [comment]
@ptman there is already PR that will fix drone support so that no changes in drone are needed
