### ISSUE TITLE
Repositories links not working from dashboard

### ISSUE THREAD

**Issue by axeloz** [go-gitea/gitea#1181]
- Gitea version (or commit ref): 1.1.0
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

On the dashboard, clicking on a repo name leads to a 404 error. 

The link is on:
axeloz "a poussé dans master sur agence/maison"
The link is:
https://git.xxxx.io/%5C%22/agence/maison%5C%22
The link should be:
https://git.xxxx.io/agence/maison

It doesn't seem related to translations. The source is:
`pushed to <a href="%[1]s/src/%[2]s">%[3]s</a> at <a href="%[1]s">%[4]s</a>`
The translation is:
`a poussé dans <a href="%[1]s/src/%[2]s">%[3]s</a> sur <a href="%[1]s">%[4]s</a>`

Also, I don't understand why there are " or ` in the source strings. Doesn't look very nice. 

## Screenshots

<img width="723" alt="axel_de_vignon_-_tableau_de_bord_-_w_git_hosting" src="https://cloud.githubusercontent.com/assets/1597611/23789287/7aa0a40a-057a-11e7-9031-a2c4ecb02bfb.png">

**Comment by lunny** [comment]
duplicated with #1174 and should be fixed by #1177
