### ISSUE TITLE
401 Unauthorized for Team API

### ISSUE THREAD

**Issue by markusschaefer** [go-gitea/gitea#11817]
- Gitea version (or commit ref): 1.12.0+rc2
- Git version: 
- Operating system: DockerImage
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x ] Yes https://try.gitea.io/api/v1/orgs/000/teams
  - [ ] No
  - [ ] Not relevant

## Description
When invoking some API urls the response code is 401

GET ​/orgs​/{org}​/teams
GET /teams/{id}
GET /teams/{id}/members

**Comment by techknowlogick** [comment]
Do you belong to that org & are you passing an auth token?

**Comment by markusschaefer** [comment]
yes, an auth token is passed and the user is member of the owners group for that org
