### ISSUE TITLE
Update repository template to match Githubs' upcoming UI change

### ISSUE THREAD

**Issue by DefinitelyADev** [go-gitea/gitea#11829]
![screenshot](https://user-images.githubusercontent.com/20267678/84264105-494ccc00-ab29-11ea-82a0-b150c3a29c48.png)

**Comment by TimerWolf** [comment]
Personally i don't like the new GitHub style...

If this is something that would be done i suggest that it should be optional if your would prefer the old or the new style.

**Comment by lunny** [comment]
It's an opportunity to find Gitea's style!!!
