### ISSUE TITLE
Code blocks in Wiki are rendered with arbitrary syntax highlighting instead of none

### ISSUE THREAD

**Issue by qwertfisch** [go-gitea/gitea#11825]
- Gitea version (or commit ref): 1.11.5
- Can you reproduce the bug at https://try.gitea.io: 
  - [X] Yes: https://try.gitea.io/qwertfisch/markdown-test/wiki/Code-blocks
  - [ ] No
  - [ ] Not relevant

## Description

When adding a code block on a page in the built-in wiki, but with no language given for syntax highlighting, this block will be rendered using an arbitrarily chosen highlighting. Code blocks without selected syntax I will set like this:

~~~
```
This is simple text rendered with fixed-width font,
but no syntax highlighting.
```
~~~

Even if the text inside the block would contain keywords for *some* languages, I do not expect them to be highlighted or rendered other than as fixed-width font. In fact when given no language for the code block, I expect the language to be *None*.

### Actual result
When selecting the preview window, or after storing the page, a second later a seemingly arbitrarily chosen syntax highlighting is applied to the block. On the [example page](https://try.gitea.io/qwertfisch/markdown-test/wiki/Code-blocks) I added some keywords (for some languages), and the two blocks are rendered as Cal and Vim, respectively. It seems the highlighting is selected automatically given the content of the block.

### Workaround
I can enclose the block with `<pre>` / `</pre>` instead of Markdown. Is there otherwise a possibility to have a non-syntaxed code block with Markdown syntax?
**Edit:** `<pre>` does not set the content to a fixed-width font, so this is unfortunately no solution.

Is this a bug for Gitea? Or should I file a bug on the Markdown interpreter used (goldmark?).

**Comment by zeripath** [comment]
This is not the fault of goldmark.

Gitea uses highlightjs for syntax highlighting of code blocks and as far as I understand highlightjs will automatically attempt to detect the language.

It's probable that if you put `plaintext` after the backticks that would turn it off.

**Comment by silverwind** [comment]
We should put the `plaintext` class on `<code>` to prevent hljs from autodetection.

**Comment by qwertfisch** [comment]
An automatically selected highlighting is welcome – just not when it is not expected. I could not find a documentation of this feature before. 

`plaintext` works and selects the plaintext syntax from hljs, thanks for the advice. Also any other name unknown for hljs would work and use a `language-[name]` class, which defaults to no highlighting.
