### ISSUE TITLE
[Question] why does it need a username to display the migration items?

### ISSUE THREAD

**Issue by alexanderadam** [go-gitea/gitea#11826]
Is it really necessary to have the username available first?

And is it possible to add or remove those items from a mirror afterwards in the mirror settings?
At the moment releases and milestones are synced with the mirroring functionality but issues aren't, right?

If it's not possible to sync issues, it would be great to have an option for default external issues (see [4750](https://github.com/go-gitea/gitea/issues/4750#issuecomment-641811195)).

**Comment by lunny** [comment]
Currently you have to put a token on the username box to display the migration items. Because github has a rate limit for public API request with no token as 60 times per hour. So in fact if you didn't put a token there, even migrating a small repository, you have to wait for about an hour.

**Comment by alexanderadam** [comment]
Okay, thank you for your response :+1:
