### ISSUE TITLE
Missing "back" (octicon-mail-reply) icon in link to parent directory of repo files

### ISSUE THREAD

**Issue by richmahn** [go-gitea/gitea#11820]
- Gitea version (or commit ref): 1.13.0+dev-156-g777015c2c
- Git version: N/A
- Operating system: N/A
- Database (use `[x]`): N/A
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

When in a repo's file listing, in a subdirectory, it looks like it was meant to show a back arrow icon next to the "`..`" at the top of the list to go back to the parent directory.

The code shows it should have octicon-mail-reply: 

https://github.com/go-gitea/gitea/blob/777015c2c2d2d74d98d15e145f9f8af04f1d9c8f/templates/repo/view_list.tmpl#L39

which is this icon: https://commons.wikimedia.org/wiki/File:Octicons-mail-reply.svg 

but it comes up empty on both my copy of Gitea and on try.gitea.io: https://try.gitea.io/richmahn/cecil/src/branch/master/Mono

## Screenshots

<img width="1196" alt="Screen Shot 2020-06-09 at 10 20 27 AM" src="https://user-images.githubusercontent.com/2839925/84159636-48d60780-aa3b-11ea-9245-4827554bf488.png">

**Comment by jolheiser** [comment]
Looks like they changed the name to just "reply"

https://primer.style/octicons/reply
