### ISSUE TITLE
Repository listing filter broken after upgrading from gogs 0.11.91 to gitea 1.12.0-rc2 

### ISSUE THREAD

**Issue by moepman** [go-gitea/gitea#11824]
- Gitea version (or commit ref): 0.12.0-rc2
- Git version: 2.20.1
- Gogs version: 0.11.91
- Operating system: Debian Buster (stable with all current updaes installed)
- Database:
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

After migrating from gogs 0.11.91 to gitea 1.12.0-rc2 the "Repositories" list to the right is broken. It was still working with 1.11.6. It seems to be a filtering issue: if I select archived (✓) or not archived (-) it works - with the empty checkbox (which should list both archived and non-archived) I get an empty list as per the attached screenshot.

Steps taken for the migration:
* stop gogs
* create a new minimal app.ini
* set DB version to 13 as per #5318
* start gitea 1.6.4 (since #5318 seems to imply this is supported without going through previous versions)
* sop gitea
* start gitea 1.11.6 (with #10026 dropping migrations from before 1.6.x in current code that to me implies going from 1.6.4 to 1.11.6 should be safe)
* Run "Reinitialize all missing Git repositories for which records exist"
* Remove gogs hooks: find $REPO_DIR -path \*-receive.d/\*-receive -delete (see #3558 for Details)
* Run "Resynchronize pre-receive, update and post-receive hooks of all repositories" (or PRs will break #8208)
* stop gitea
* start gitea 1.12.0-rc2

## Screenshots

![gitea-repositories-empty](https://user-images.githubusercontent.com/619759/84180624-1bfc1180-aa88-11ea-93c4-171a78b5daaa.png)

**Comment by zeripath** [comment]
OK it looks like we could add another migration v142.go which does this step.

Probably reasonable to do it as we never really want is_archived to be NULL

**Comment by zeripath** [comment]
For 1.12 unfortunately we can't backport the auto-migration but the gitea doctor command could be used to fix this.
