### ISSUE TITLE
Quotes appearing in the GUI in french

### ISSUE THREAD

**Issue by axeloz** [go-gitea/gitea#1183]
- Gitea version (or commit ref): 1.1.0

## Description

Here is what I get in the GUI
<img width="244" alt="capture d ecran 2017-03-10 a 10 49 33" src="https://cloud.githubusercontent.com/assets/1597611/23790488/8d04c806-057f-11e7-944d-a8accc842815.png">
There are " 
Here is what there is into the translations
<img width="403" alt="capture d ecran 2017-03-10 a 10 49 38" src="https://cloud.githubusercontent.com/assets/1597611/23790498/96b79ae0-057f-11e7-840d-b4601f9edd5e.png">
There is no "

There are quite a lot of places where " or ' or ` are added in the string, dunno why. Any idea?
Thks

**Comment by axeloz** [comment]
Switching language to EN or ES: all the double quotes " disappear. So it seems to be related to the french translation

**Comment by Dodger77** [comment]
Same problem in German translation. Seems to be related to #1181

**Comment by lunny** [comment]
and should be fixed in #1177
