### ISSUE TITLE
gitgraph.js could not be served by webserver

### ISSUE THREAD

**Issue by MonkeySon** [go-gitea/gitea#11839]
- Gitea version (or commit ref): 1.11.6
- Git version: 2.20.1
- Operating system: Ubuntu 19.10 Server
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description

I am hosting a gitea instance with apache2 on a sub-path using a reverse proxy.

Since version 1.11.5 the commit graph cannot be displayed because the file gitgraph.js was not found.
Comparing with try.gitea.io, the file should be served on /js/girgraph.js.
It is found when manually requesting it on my domain, but navigating to the commit graph page requests it from /gitgraph.js (missing the js subfolder).

Since it was working before 1.11.5 and other files in sub-paths are correctly requested (i.e. /img/favicon.png), I don't think it is the fault of my reverse proxy settings.

Any ideas on that?

**Comment by SlavekB** [comment]
I observe the same problem on our instance and STATIC_URL_PREFIX we have empty – i.e. according to the url of the application. See: https://mirror.git.trinitydesktop.org/gitea/TDE/kchmviewer/graph
... while our second instance, where the update has not yet been performed, works correctly. See: https://scm.trinitydesktop.org/gitea/TDE/kchmviewer/graph

**Comment by silverwind** [comment]
Ah, I see the issue. 1.11 still uses `chunkFilename: '[name].js'` while on 1.12 we have `chunkFilename: 'js/[name].js'`. Backport was done assuming the second case.

**Comment by silverwind** [comment]
> STATIC_URL_PREFIX we have empty

It shows up as `/gitea` in your index.html thought. Is it really empy/unset in the configuration?

**Comment by SlavekB** [comment]
> > STATIC_URL_PREFIX we have empty
> 
> It shows up as `/gitea` in your index.html thought. Is it really empy/unset in the configuration?

Yes, we have the prefix specified as part of the application url:
```
ROOT_URL                   = https://%(DOMAIN)s/gitea/
```

**Comment by MonkeySon** [comment]
I don't have STATIC_URL_PREFIX set either.

This is my gitea-side server configuration:

```
[server]
DOMAIN           = example.domain.com
SSH_DOMAIN       = %(DOMAIN)s
HTTP_PORT        = 3000
ROOT_URL         = https://example.domain.com/git/
DISABLE_SSH      = false
SSH_PORT         = 22
LFS_START_SERVER = true
LFS_CONTENT_PATH = /var/lib/gitea/data/lfs
LFS_JWT_SECRET   = ***
OFFLINE_MODE     = false
```

In the apache config, I am redirecting my /git to localhost:3000

Log files don't show any errors, just database queries.

**Comment by silverwind** [comment]
It's fine. Internally, STATIC_URL_PREFIX is assigned a default even when unset which just means we can probably simplify the logic in JS later on the assumption that it will always be set.

Bug will be fixed in 1.11.7.

**Comment by MonkeySon** [comment]
@silverwind 

Thanks for the update, I just did the upgrade!

Sorry to bother you again, but the request still fails:

```
Jun 18 19:25:03 * gitea[678]: [Macaron] [Static] Serving /img/favicon.png
Jun 18 19:25:03 * gitea[678]: [Macaron] 2020-06-18 19:25:03: Completed GET /img/favicon.png 304 Not Modified in 207.801µs
Jun 18 19:25:03 * gitea[678]: [Macaron] 2020-06-18 19:25:03: Started GET /jsgitgraph.js for ***.***.***.***
Jun 18 19:25:03 * gitea[678]: [Macaron] 2020-06-18 19:25:03: Completed GET /jsgitgraph.js 404 Not Found in 9.521019ms
```

Looking at `/jsgitgraph.js 404 Not Found`, it seems that the **js** folder is no prepended, but is is missing a slash.

I haven't change anything besides replacing the executable and doing a reboot.

**Comment by techknowlogick** [comment]
Now that 1.12.0 is out, are you able to verify the behaviour with that version?

**Comment by MonkeySon** [comment]
There are no binaries for the 1.12.0 release yet, but I tried 1.12.0-rc2 instead and the gitgraph is working there again.

**Comment by MonkeySon** [comment]
Ok binaries for 1.12.0 just arrived, gitgraph is also working for me with the new release :)

Thanks a lot!

**Comment by silverwind** [comment]
I'm sorry, I did not actually test that fix. Correction in https://github.com/go-gitea/gitea/pull/11961. Thought, upgrading to 1.12 is of course a even better solution.
