### ISSUE TITLE
Some projects have two "Tickets" tab

### ISSUE THREAD

**Issue by axeloz** [go-gitea/gitea#1184]
- Gitea version (or commit ref): 1.1.0
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description

On one of my projects, I have twice the "Tickets" tab. 
Using external bug tracker for this project. 
Both tab links are working and redirecting to the external bug tracker

## Screenshots

<img width="913" alt="capture d ecran 2017-03-10 a 10 59 07" src="https://cloud.githubusercontent.com/assets/1597611/23790829/095c5b8e-0581-11e7-98d8-97eff03c35d3.png">

**Comment by lunny** [comment]
This should also be fixed by #1215

**Comment by axeloz** [comment]
Fixed on version 1.1.0+24-g8746fb3
But I must re-save the repo settings to make the second tab disappear.
