### ISSUE TITLE
gitea and read-only filsystems

### ISSUE THREAD

**Issue by micheelengronne** [go-gitea/gitea#11855]
Gitea wants to modify files even if they are present and with the content gitea wants to put in.

Therefore, Gitea breaks on read-only filesystems (like an hardened docker container.)

My problem is simple.

This method wants to modify a `.gitconfig` file:

https://github.com/go-gitea/gitea/blob/9a2e47b23a6d460acfce9b1b77e6f9fb06ca1b75/modules/git/git.go#L109

It runs even if the `.gitconfig` file exists with the correct content.

Is it possible to stop that behaviour ?

Thanks.

**Comment by CirnoT** [comment]
We rely on `git config --global` to make changes to Git config file

**Comment by micheelengronne** [comment]
Yes, but can we disable this method when the file already exists ?

**Comment by zeripath** [comment]
Just set the HOME environment variable as appropriate to somewhere that can be changed.

**Comment by CirnoT** [comment]
>Yes, but can we disable this method when the file already exists ?

No, because we don't know whether correct values are set or not. The fact that file exists tells us nothing.

**Comment by micheelengronne** [comment]
My usecase happens in a container environment. A new version is introduced by creating a new container image, not updating the existing one.

**Comment by micheelengronne** [comment]
I tried to do an init container that sets everything and a container with `gitea web` but still the `gitea web` cli wants to use this method.

It is a security issue as it forces to use a read-write filesystem for just a file that can easily be commmited in a git.

Can we, at least, have an option to use `gitea web` and other production-running state commands in a read-only filesystem ?

**Comment by zeripath** [comment]
@micheelengronne have you set the HOME environment variable appropriately?

**Comment by micheelengronne** [comment]
Changing the HOME variable is not a solution either. In an immutable hardened container, only data should change, nothing else.

**Comment by micheelengronne** [comment]
So, what can change is the content of `ROOT` according to the [config cheat sheet](https://docs.gitea.io/en-us/config-cheat-sheet/).

**Comment by micheelengronne** [comment]
I am sorry to be strict on that. But this is an absolute condition to make gitea run in security hardened infrastructure. Containers must work with read-only FS and read-only configurations and secrets.

**Comment by zeripath** [comment]
Right the issue is that Git is making the change to the file.

We are limited in how we can tell Git to look for its .gitconfig.

Git uses HOME to determine the global gitconfig which we use to set various global settings and to look up various things.

So I ask again, have you tried setting the HOME variable to a mutable place?

**Comment by zeripath** [comment]
If that works then can consider if there is a place for using ROOT to artificially change the HOME for git etc. but without knowing that then we're likely leading down a blind alley and we might have to think about if we need to set things a different way eg. through the default args system

**Comment by micheelengronne** [comment]
To be sure we talk about the same thing. If I move `HOME`, I move my user directory, right ? So, I move all configurations in it ?

Did I understand correctly ?

In that way, configurations are not immutables and that will not pass hardened security tests.

Why, can't we have a way to include a file containing the same content and for the method to check if the file exists with the correct content prior to create it ?

**Comment by zeripath** [comment]
No I mean just set the HOME environment variable when you run gitea

**Comment by micheelengronne** [comment]
But that will screw up my user directory.

For instance, my user is `git`. I put this file content in `/home/git/.gitconfig`.

```
[user]
	name = Gitea
	email = gitea@fake.local
[core]
	quotepath = false
	commitGraph = true
[gc]
	writeCommitGraph = true

```

Then the init method should not try to write this file.

Do you suggest, I move `HOME` to `/home/git/mutable` and make this directory writable ?

If it works that's better than nothing but that will still break the security hardening check as `.gitconfig` is also a configuration file.

I try.

**Comment by micheelengronne** [comment]
That works but that's not really the best solution. It would be far better to test if the file exists with the correct values before trying to create it.

If a gitea update occurs that change the file content, the CI job that creates the docker (podman) image would break so future compatibilities would be ensured by that way.

**Comment by micheelengronne** [comment]
BTW, the 2 first git executions do what I think is the correct way to do. https://github.com/go-gitea/gitea/blob/83e9ac57a116be910ca3fb0c2b33f64ffae0dc3e/modules/git/git.go#L112

They check if the values exist and they are the same than the ones provided and they execute the git command if one of these assertions is false.

The problem is for these lines:

https://github.com/go-gitea/gitea/blob/83e9ac57a116be910ca3fb0c2b33f64ffae0dc3e/modules/git/git.go#L126

https://github.com/go-gitea/gitea/blob/83e9ac57a116be910ca3fb0c2b33f64ffae0dc3e/modules/git/git.go#L132

https://github.com/go-gitea/gitea/blob/83e9ac57a116be910ca3fb0c2b33f64ffae0dc3e/modules/git/git.go#L138

They do not check so they always try to write.

**Comment by zeripath** [comment]
So any configuration in `$HOME/.gitconfig` can be overridden by a repository's local "project" git config (`$GITEA_REPOSITORIES/owner/name.git/config`) including in particular `diff.tool`. Gitea needs to be able to change these config files in order to manage mirrors and remotes amongst other things - and we regularly create temporary repositories which git gives a local project config. I'm not saying that we shouldn't make changing `$HOME/.gitconfig` unnecessary - but unless you can get to the point that these local project config files are controllable or removable - which I haven't been able to find a way of doing - locking down the `$HOME/.gitconfig` is of very limited use. `$HOME/.gitconfig` is the GLOBAL config only in that it provides defaults to the local project git configs - it cannot and does not override local project git config.

**Comment by micheelengronne** [comment]
I know that. But that was not the point. Anyway, thanks for the commit.
