### ISSUE TITLE
Cannot enable external tracker

### ISSUE THREAD

**Issue by axeloz** [go-gitea/gitea#1185]
- Gitea version (or commit ref): 1.1.0
- Operating system: Ubuntu 14.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant

### Steps to reproduce

My project has 
- Wiki enabled 
- Bug tracker disabled

What to do:

- I disable the Wiki
- I save
- It works
- Then I enable the internal bug tracker
- I save
- It works
- Then I change the internal bug tracker to external bug tracker
- I save
- It doesn't work, the Wiki is enabled again, the bugtracker is disabled again, all changes are lost.

## Screenshots

**If this issue involves the Web Interface, please include a screenshot**

**Comment by axeloz** [comment]
Hey, 

Thanks for the pull request. However I'm a little bit surprised that such bugs (quite severe) are planned on being fixed on the 24th of April, not before. Not the only bug in this case. Can't you plan it for 1.1.1? 
Thanks again

**Comment by lunny** [comment]
Yes. We will include this on 1.1.1.

**Comment by axeloz** [comment]
Using version  1.1.0+24-g8746fb3, this issue is not quite fixed. I'm now able to save the external tracker settings but once saved, the form is greyed out

![capture](https://cloud.githubusercontent.com/assets/1597611/23895729/1179c33c-08a7-11e7-8b67-2e18c28505f7.png)

If I want to change a setting, I must click "Enable the issue tracking system" twice.

**Comment by lunny** [comment]
Yes. It seems a UI problem, but the settings should be available. Could you confirm that?

**Comment by axeloz** [comment]
Settings are available, when not greyed out.
Thanks

**Comment by xPaw** [comment]
This is not fixed in v1.1.0 at all. Enabling external issue tracker and entering an URL, then saving, results in wiki being enabled. External URLs are not saved, and issues are disabled.

**Comment by lunny** [comment]
This will be fixed in v1.1.1 and v1.2.0
