### ISSUE TITLE
Is is possible to count commit times rather than push times in user heatmap?

### ISSUE THREAD

**Issue by nbdavied** [go-gitea/gitea#11861]

**Comment by lafriks** [comment]
User heatmap calculates user activity in gitea not in git repositories. This also includes comments/reviews etc from Gitea database. I don't think it would be possible to count commits

**Comment by silverwind** [comment]
Duplicate of https://github.com/go-gitea/gitea/issues/8178. Issue it heatmap counts the pusher, not the author of a commit.
