### ISSUE TITLE
Recover lost code

### ISSUE THREAD

**Issue by romantictravel01** [go-gitea/gitea#11866]
I used the docker installation. The directory / storage / tools / gitea: / data was mounted. The database was accidentally lost

How to find the code in it

**Comment by techknowlogick** [comment]
Browse `/storage/tools/gitea`, you're repositories will be stored in there in a directory called "gitea-repositories" as bare git repos. If nothing exists in that directory then your data may not have been mounted.

I'm going to close this now, but please feel free to ask questions in our forum at https://discourse.gitea.io/ or our chat at https://discord.gg/gitea.
