### ISSUE TITLE
Segfault in gitea/gitea:1.11.3 amd64 container in WorkerPool

### ISSUE THREAD

**Issue by mappu** [go-gitea/gitea#11860]
- Gitea version (or commit ref): Official docker tag `gitea/gitea:1.11.3`
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description

My gitea server was down unexpectedly. I checked the logs and saw a SIGSEGV panic. Restarted the container and it works OK again.

The segfault happened to the goroutine that was running a WorkerPool, I haven't checked the code but maybe there is some race condition there.

Panic trace:

```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x438e99]

goroutine 126 [running]:
runtime.throw(0x1e26d94, 0x2a)
        /usr/local/go/src/runtime/panic.go:774 +0x72 fp=0xc001744bf8 sp=0xc001744bc8 pc=0x4371d2
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:378 +0x47c fp=0xc001744c28 sp=0xc001744bf8 pc=0x44c8ac
runtime.acquirem(...)
        /usr/local/go/src/runtime/runtime1.go:445
runtime.gopark(0x2de62f0, 0x0, 0x1809, 0x1)
        /usr/local/go/src/runtime/proc.go:291 +0x39 fp=0xc001744c48 sp=0xc001744c28 pc=0x438e99
runtime.selectgo(0xc001744e78, 0xc001744e00, 0x3, 0x2, 0xc00176b500)
        /usr/local/go/src/runtime/select.go:313 +0xc9b fp=0xc001744d70 sp=0xc001744c48 pc=0x448a4b
code.gitea.io/gitea/modules/queue.(*WorkerPool).doWork(0xc0002fa000, 0x327e980, 0xc0016b8100)
        /go/src/code.gitea.io/gitea/modules/queue/workerpool.go:278 +0x6f5 fp=0xc001744f78 sp=0xc001744d70 pc=0x13a6fa5
code.gitea.io/gitea/modules/queue.(*WorkerPool).addWorkers.func1(0xc0002fa000, 0x327e980, 0xc0016b8100)
        /go/src/code.gitea.io/gitea/modules/queue/workerpool.go:201 +0x43 fp=0xc001744fc8 sp=0xc001744f78 pc=0x13a82a3
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc001744fd0 sp=0xc001744fc8 pc=0x466fb1
created by code.gitea.io/gitea/modules/queue.(*WorkerPool).addWorkers
        /go/src/code.gitea.io/gitea/modules/queue/workerpool.go:200 +0x56
```

Full panic log attached.
[2020-06-12-gitea-server-panic.log](https://github.com/go-gitea/gitea/files/4767269/2020-06-12-gitea-server-panic.log)

**Comment by lafriks** [comment]
Please check with latest 1.11.5

**Comment by zeripath** [comment]
I'm not sure how this can happen. This panic appears to be arising from the select:

https://github.com/go-gitea/gitea/blob/f3cacf13322d869dd7c6146ff58774ba8e27040c/modules/queue/workerpool.go#L278

And in particular the taking of the lock in the select...

This looks like a go bug to me.

In any case upgrade to the 1.11.6 and see if that fixes it.

**Comment by 6543** [comment]
@mappu do you have similar problems with / does the problem still exist in latest stable (1.12.3) ?

**Comment by mappu** [comment]
I haven't seen it reoccur since, on any 1.11.x or 1.12.x version.

But I do only have that one panic trace, not any repeatable reproducer, so it might still be lurking somewhere.

**Comment by zeripath** [comment]
OK I'm gonna close this issue as it appears not to have occurred again - if it does happen again please reopen - or open another issue.
