### ISSUE TITLE
Some features

### ISSUE THREAD

**Issue by sysdl132** [go-gitea/gitea#11867]
Can you take a look?
If gitea already had these features or support it in the future,tick it.
If don't,leave a comment.
# not checked

- [x] CI support (drone)
- [ ] "gitea pages"
- [ ] report abuses
- [x] custom things(icon,login page text,etc.)
- [ ] sidebar
- [ ] "sponsor" button
- [x] insights page
- [ ] include plugins(themes, travis,etc.)
- [x] projects on main index page(like: https://gitea.com)
- [x] quotes
- [x] program language display

# checked
- [x] user manage

That's all

**Comment by 6543** [comment]
Themse, yes

**Comment by lafriks** [comment]
Don't know about what you meant about "chat system"

**Comment by lafriks** [comment]
You can check https://docs.gitea.io/en-us/comparison/ about features gitea supports compared to other self-hosted git platforms

**Comment by a1012112796** [comment]
> Don't know about what you meant about "chat system"

Maybe he means a built-in forum... :)

**Comment by 6543** [comment]
well if we would build all in gitea would be overloaded very quicly + we have to maintain all of it :/
so why we ever would build in a chat or a forum? gitea could be setup as oauth profider and there is plenty of good software witch can be integrated via custom http+js or a subdomain etc ...

**Comment by sysdl132** [comment]
oh...Yesterday I went to the forum.But I couldn't see anything...

**Comment by techknowlogick** [comment]
not sure what you mean by "sidebar", or what functionality that would include. As for pages, we recommend users use a CI, and a static html hoster to update pages.

I'm going to close this ticket now, however if you have future questions about what is included in gitea I recommend asking on the forum at https://discourse.gitea.io/
