### ISSUE TITLE
[BUG]When view commit detail it returns 500

### ISSUE THREAD

**Issue by L0veSunshine** [go-gitea/gitea#11869]
- Gitea version (or commit ref):1.13.0+dev-183-gbc4f7ba69
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
  - [X] Not relevant
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes (provide example URL) https://try.gitea.io/sakalabid77/CaraMerawatAlatLab/commit/0c57fe15ce3a806afb1730fb9ed551cb0866bf4f,
https://try.gitea.io/matze1128/Virus_Programm_Matthias/commit/ad2488328cbc7bae3cc1ab184fa422f77bdef205
...
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

After my test. I suspect this issue may be caused by this pr (#11847).
This issue is same to  #11868
Please have a review.

## Screenshots
![image](https://user-images.githubusercontent.com/19653204/84522335-fe89aa80-ad08-11ea-9439-e168f04af6a4.png)

**Comment by mrsdizzie** [comment]
This is
```2020/06/12 12:27:54 ...uters/repo/commit.go:317:Diff() [E] commit.GetTagName: exit status 128 - fatal: No names found, cannot describe anything.```

From  #11846
