### ISSUE TITLE
Make the dashboard filter bar ignore case

### ISSUE THREAD

**Issue by donnex** [go-gitea/gitea#1187]
The new repository filter bar implemented in 1.1 is really great but it would be really handy if this bar filtered repos by ignoring case. Right now it seems that you need to match the exact casing on your repositories names if you want a match.

**Comment by lunny** [comment]
@appleboy maybe you can do this.

**Comment by appleboy** [comment]
@donnex @lunny I will take it.

**Comment by appleboy** [comment]
https://try.gitea.io/appleboy?q=xd I think this bar filtered repos by ignoring case.

**Comment by pgaskin** [comment]
I will do this, my fix also fixes my other bug #1205 .

**Comment by pgaskin** [comment]
I have opened PR #1207
