### ISSUE TITLE
Untranslatable string

### ISSUE THREAD

**Issue by axeloz** [go-gitea/gitea#1188]
- Gitea version (or commit ref): 1.1.0

## Description

I can't find the following strings into Crowdin: 

`The default branch is considered the "base" branch in your repository, against which all pull requests and code commits are automatically made, unless you specify a different branch.`

`Branch Protection`

`There is no protected branch`

URL: /org/repo/settings/branches

**Comment by pgaskin** [comment]
I have opened a PR
