### ISSUE TITLE
Documentation: redis, sshd and elastic

### ISSUE THREAD

**Issue by dschier-wtd** [go-gitea/gitea#11898]
Hi everybody,

currently, I can see support for sshd, redis (queuing) and elastic (indexer). The documentation does not state, when or why it is a good idea to use one of these over the built-ins. From an operator perspective, it would be awesome to see some examples why I should use elastic, sshd or redis.

**Comment by daniel-wtd** [comment]
At least there must have been some reason to implement these in the first place, I assume :/

**Comment by lunny** [comment]
Since the new documentation site https://docs.gitea.com is up. I think we can close this one now.
