### ISSUE TITLE
git name-rev --exclude is not available in git <2.13 - breaking commit history

### ISSUE THREAD

**Issue by Ulyev-ad** [go-gitea/gitea#11917]
I can't view the commit history, error.
![image](https://user-images.githubusercontent.com/13260152/84827233-33fa0500-b035-11ea-8ad4-01b1d5c20e48.png)
Error:
![image](https://user-images.githubusercontent.com/13260152/84827290-4aa05c00-b035-11ea-8db1-7334b718187e.png)

In logs:
`2020/06/16 23:49:56 ...uters/repo/commit.go:311:Diff() [E] commit.GetBranchName: exit status 129 - error: unknown option `exclude'
	usage: git name-rev [options] <commit>...
	   or: git name-rev [options] --all
	   or: git name-rev [options] --stdin
	
	    --name-only           print only names (no SHA-1)
	    --tags                only use tags to name the commits
	    --refs <pattern>      only use refs matching <pattern>
	
	    --all                 list all commits reachable from all refs
	    --stdin               read from stdin
	    --undefined           allow to print `undefined` names
	    --always              show abbreviated commit object as fallback
`

**Comment by zeripath** [comment]
What version of git do you have?

**Comment by Ulyev-ad** [comment]
Oh, I forgot to update. Yes, thank you!

**Comment by bobemoe** [comment]
Which version is needed? I'm getting this error but no git updates: 
`git is already the newest version (1:2.11.0-3+deb9u7).`

**Comment by bobemoe** [comment]
I'm using Debian 9. I've enabled the backports repo and managed to install Git 2.20.1 All is working now :)

**Comment by zeripath** [comment]
OK I'm reopening this as `git name-rev --exclude` is not available in git <2.13.

**Comment by zeripath** [comment]
Bug introduced by #11847
