### ISSUE TITLE
Return all repositories in user repos API endpoint for Gitea administrators

### ISSUE THREAD

**Issue by lafriks** [go-gitea/gitea#11913]
Currently there is no way for Gitea server administrator to see or access repositories in drone, only where he is directly added in organization even he can access them from Gitea web interface. This makes it very hard to administer drone with large number of repositories.

**Comment by mrsdizzie** [comment]
http://example.com/admin/repos shows all repos for server admin in Gitea Web interface:

 https://github.com/go-gitea/gitea/blob/6a4de37f7e790716c35f1dc4a0aeacfe4b4a1415/routers/admin/repos.go#L22-L32

Should be possible to refactor that so you could then have the API return just the repos list and not the entire template

**Comment by CirnoT** [comment]
Drone uses same logic as collaboration, hence why.

This is very dangerous procedure; enabling repository via admin account will mark you as repository owner within Drone database!

**Comment by CirnoT** [comment]
Also note that Gitea is not Drone; doing this would affect all Drone instances, even those owned by user, leaking data to them by creating entry for repository name and their owner in Drone's database.

**Comment by 6543** [comment]
we can create a new api endpoint similar to https://try.gitea.io/api/swagger#/admin/adminGetAllUsers

**Comment by 6543** [comment]
`GET /admin/repos`

**Comment by lafriks** [comment]
As per discussion in Discord with @CirnoT it should most probably be implemented in Drone side.

Other option could be to have this as setting (disabled by default) when Gitea is used as private instance with single gitea and drone instances.

**Comment by 6543** [comment]
I would never return all repos via **USER Repo** API but in generel it would be a good feature for an Admin api endpoint - will create a pull

and yes this has nothing to do with the main issue witch should be implemented by drone

**Comment by CirnoT** [comment]
I agree, would be nice if Drone could allow admin user to view all repos that are currently in database.

**Comment by lafriks** [comment]
Closing this as my use-case has been covered by drone/drone-ui#334
