### ISSUE TITLE
Language statistics hidden languages

### ISSUE THREAD

**Issue by lafriks** [go-gitea/gitea#11914]
Currently we use languages hard coded in Gitea code. We should probably switch to using go-enry method to get language type and include only **programming** and **markup** languages in stats:
https://github.com/go-enry/go-enry/blob/dc6fc02209b37a02b64eed383a5f281059e86eac/common.go#L453

**Comment by CirnoT** [comment]
Markup should be included too (HTML, CSS)

**Comment by silverwind** [comment]
FWIW, GitHub does not hide either HTML or CSS from their stats.

**Comment by CirnoT** [comment]
Yes, hence why should most likely allow Markup along with Programming type.

**Comment by silverwind** [comment]
Ah, misunderstood you. I wonder if we would have to include more then we currently exclude.

**Comment by CirnoT** [comment]
No, just two types
https://github.com/go-enry/go-enry/blob/dc6fc02209b37a02b64eed383a5f281059e86eac/common.go#L444

But it doesn't seem like they're exported and `GetLanguageType` returns int, so we'll have to hardcode it and hope it never changes.

**Comment by 6543** [comment]
@lafriks if we only include programming languages, then https://gitea.com/gitea/blog would be a go project ... - dont know if this is the right way ... can we add a reposetting "excluded lang in status: xy, abc, ..."

**Comment by silverwind** [comment]
> Idear: can we add a reposetting "excluded lang in status: xy, abc, ..."

I'd just do it via `.gitattributes`, that way it's portable and would work both on GitHub and Gitea. The relevant attribute to mark a glob undetectable is [`-linguist-detectable`](https://github.com/github/linguist#detectable)

**Comment by lafriks** [comment]
@6543 no it would be HTML project :) We do already exclude Markdown: https://github.com/go-gitea/gitea/blob/dc812f8ba5bf1c123fa948afed15c4309da8fb45/modules/git/repo_language_stats.go#L33

**Comment by lafriks** [comment]
first we need .gitattributes parser ;) tho it should probably be part of `go-git` project

**Comment by silverwind** [comment]
`go-enry` indicates in the README that it wants to support `.gitattributes`, maybe it shoud be there:

https://github.com/go-enry/go-enry#divergences-from-linguist
