### ISSUE TITLE
Cannot change PR target branch (causes 100% CPU)

### ISSUE THREAD

**Issue by danwilliams** [go-gitea/gitea#11911]
- Gitea version (or commit ref): 1.13.0+dev-199-g80a3745fc
- Git version: 2.11.0
- Operating system: Debian Stretch (up-to-date)
- Database:
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description

If I try to change the target ("merge into") branch for an existing PR, it calls `POST /project-name/repo-name/pull/{pull-id}/target_branch`, but the XHR request never finishes (just says "pending" forever). So the target branch doesn't get updated.

Doing this also causes the `gitea` process to max out a CPU core. If tried repeatedly, it maxes out another core each time, getting to and maintaining 100% if you try to change the target branch multiple times. This seems to never end (has been observed going on for days). Presumably each attempt uses a thread.

There is nothing listed in Running Processes under the Gitea admin panel.

If I restart Gitea and use it as normal, the CPU doesn't spike. It only happens when I try to change the target branch of a PR.

I have the logging set to `Trace`, but am not seeing any errors, and also not seeing an `UPDATE` query being executed against the `pull_request` table, which is where I'd expect it to update the `base_branch` column.

So something is going wrong in between the start of the request, and the place in the code where it would run that query.

This has been reproduced on a number of repositories on the same server. Each has had `gc` etc. run and is clean.

Out of interest this bug has been around for many months - I thought the branch changing was simply broken, and that a fix would be along at some point. In noticing the CPU usage and investigating further today, the full behaviour has become apparent. Gitea is kept up-to-date regularly (every week or two against master).

**Comment by zeripath** [comment]
This is weird I can't seem to replicate the problem.

Are you able to build Gitea from source code? You could apply the below patch to determine where the sticking point is:

```diff
diff --git a/services/pull/pull.go b/services/pull/pull.go
index b94a46639..1aee4b865 100644
--- a/services/pull/pull.go
+++ b/services/pull/pull.go
@@ -156,11 +156,15 @@ func ChangeTargetBranch(pr *models.PullRequest, doer *models.User, targetBranch
        oldBranch := pr.BaseBranch
        pr.BaseBranch = targetBranch
 
+       log.Debug("About to test patch: pr [%d] in %-v", pr.Index, pr.BaseRepo)
+
        // Refresh patch
        if err := TestPatch(pr); err != nil {
                return err
        }
 
+       log.Debug("Done testing patch: pr [%d] in %-v", pr.Index, pr.BaseRepo)
+
        // Update target branch, PR diff and status
        // This is the same as checkAndUpdateStatus in check service, but also updates base_branch
        if pr.Status == models.PullRequestStatusChecking {
@@ -175,9 +179,12 @@ func ChangeTargetBranch(pr *models.PullRequest, doer *models.User, targetBranch
        pr.CommitsAhead = divergence.Ahead
        pr.CommitsBehind = divergence.Behind
 
+       log.Debug("Got divergence: pr [%d] in %-v", pr.Index, pr.BaseRepo)
+
        if err := pr.UpdateColsIfNotMerged("merge_base", "status", "conflicted_files", "base_branch", "c>
                return err
        }
+       log.Debug("UpdatedCols: pr [%d] in %-v", pr.Index, pr.BaseRepo)
 
        // Create comment
        options := &models.CreateCommentOptions{
```

**Comment by tsynaev** [comment]
I have the same issue. I cannot build Gitea from source code. Can someone make the patched version for windows for my test?

**Comment by dseynaev** [comment]
we are also seeing this running in docker (gitea/gitea:1.11.8) with a postgresql backend

**Comment by zeripath** [comment]
could you please upgrade to the latest version (currently 1.12.5) and see if this occurs on that version.
