### ISSUE TITLE
Milestone filter for pull requests shows either only open or closed milestones

### ISSUE THREAD

**Issue by otbutz** [go-gitea/gitea#11924]
- Gitea version (or commit ref): 1.11.4 
- Git version: 2.26.2
- Operating system: Ubuntu 18.04
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (https://try.gitea.io/otbutz99/broken-milestones/pulls)
  - [ ] No
  - [ ] Not relevant

## Description

While browsing open PRs i'm only able to select open milestones in the filter and vice-versa. This way i'm unable to search for old PRs which targeted a milestone which is closed now or search for open PRs targeting a closed milestone.

The milestone filter should behave similar to the dropdown which is used to select the target milestone of a pull request. It should display all milestones but could provide a visual separation for open/closed ones:

![milestone-dropdown](https://user-images.githubusercontent.com/22315436/84887367-e9f53b80-b095-11ea-8fcb-9a08544ca6aa.png)

## Screenshots

![open-prs](https://user-images.githubusercontent.com/22315436/84886667-05137b80-b095-11ea-9c20-11d357d7aa25.png)
In this case i'm unable to filter open PRs targeting `v1.0.0` because it's a closed milestone.

![closed-prs](https://user-images.githubusercontent.com/22315436/84886663-047ae500-b095-11ea-877a-06c9683843a1.png)
Here i'm unable to filter PRs targeting milestone `v4.0.0` which is still open.

**Comment by 6543** [comment]
ping - still here

**Comment by dexterxx-pl** [comment]
+1

**Comment by otbutz** [comment]
@6543 the label `kind/enhancement` doesn't really fit. This is a bug.

**Comment by lunny** [comment]
So when filter on opened issues, we could just list opened milestones because closed milestones should not have opened issues. When filter on closed issues, we should list all milestones.

**Comment by otbutz** [comment]
>  closed milestones **should** not have opened issues

As long as i can close a milestone with open issues, i should be able to filter accordingly. And closing a milestone could be also interpreted as not accepting new issues.

**Comment by lunny** [comment]
That sounds not a normal operation, once closed a milestone, the first step you should do is to move open issues to other milestone.

Not list all the milestones here because some repositories have many milestones and most of them closed.

**Comment by dexterxx-pl** [comment]
The case is when you add new milestone while you already have some closed issues and you want to assign them to it.

Eg.

You're starting development without milestones
Closing some issues while still working eg. on v1.0
Then you realize that you need milestones and you create such one for our WIP v1.0 version.


Already filtered milestones might be displayed below that <of current state> oppened/closed... just to be able to use them if I want.
