### ISSUE TITLE
Use default value for -webkit-font-smoothing

### ISSUE THREAD

**Issue by mrsdizzie** [go-gitea/gitea#11931]
Its been bugging me for a wile why I think fonts on Gitea look off compared to other sites even though most things seem the same but I realized it is because we use ```-webkit-font-smoothing: antialiased;```

I don't see many other sites that use this and for me it just makes the fonts look too thin and unattractive. I guess part of the negative effect is that Gitea uses fonts/sizes I recognize but they look different than in every other place I see them which gives it a feeling of being 'off'.

Looking at the original issue https://github.com/go-gitea/gitea/pull/489 and https://github.com/go-gitea/gitea/pull/763 I don't experience that the fonts look bad or like that on a mac without -webkit-font-smoothing: antialiased; I have a retina display too and think it looks better with the default subpixel-antialiased value.

Is this something we could revisit? Or do most people think it looks better in general as is? Maybe it makes more of a difference on other systems/browsers? Some font weights need to be adjusted to look right with the default subpixel-antialiased value; setting since they are now compensating for us making fonts thinner and would be too bold otherwise. 

This is from 2012 so who knows but seems to match what it feels like to me:

 https://usabilitypost.com/2012/11/05/stop-fixing-font-smoothing/

https://developer.mozilla.org/en-US/docs/Web/CSS/font-smooth also suggests this has been removed from standards and not recommended in production. Other searches seem to suggest it is preferred practice to alter font weights instead of using this too.

fwiw this feels most noticeable to me when looking at code since I expect it to look the exact same as everywhere else that uses the same font/size but still think most text looks generally a bit worse in lots of places. Some of it is OK because we just boost the font weight to make up for the thinness.

For something that makes Gitea look different than many other sites theres not really any detailed discussion or reasoning on why we added this other than one person thought it looked better and it got a few positive and negative reactions. Any thoughts welcome : )

**Comment by silverwind** [comment]
👍 from me, the closer we are to browser defaults, the better.
