### ISSUE TITLE
Update to 1.12.0: 

### ISSUE THREAD

**Issue by somera** [go-gitea/gitea#11966]
- Gitea version (or commit ref): 1.12.0
- Git version: 2.20.1
- Operating system: Linux pi-manager 4.19.118-v7l+ #1311 SMP Mon Apr 27 14:26:42 BST 2020 armv7l GNU/Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

root@pi-manager:/var/lib/gitea/log# grep "ORM" gitea.log
2020/06/18 19:48:40 routers/init.go:59:initDBEngine() [I] Beginning ORM engine initialization.
2020/06/18 19:48:40 routers/init.go:66:initDBEngine() [I] ORM engine initialization attempt #1/10...
2020/06/18 19:48:40 routers/init.go:99:GlobalInit() [I] ORM engine initialization successful!
2020/06/18 19:53:19 routers/init.go:59:initDBEngine() [I] Beginning ORM engine initialization.
2020/06/18 19:53:19 routers/init.go:66:initDBEngine() [I] ORM engine initialization attempt #1/10...
2020/06/18 19:53:19 routers/init.go:99:GlobalInit() [I] ORM engine initialization successful!
2020/06/18 20:31:06 routers/init.go:59:initDBEngine() [I] Beginning ORM engine initialization.
2020/06/18 20:31:06 routers/init.go:66:initDBEngine() [I] ORM engine initialization attempt #1/10...
2020/06/18 20:31:06 routers/init.go:99:GlobalInit() [I] ORM engine initialization successful!
2020/06/18 21:07:33 routers/init.go:59:initDBEngine() [I] Beginning ORM engine initialization.
2020/06/18 21:07:33 routers/init.go:66:initDBEngine() [I] ORM engine initialization attempt #1/10...
2020/06/18 21:07:33 routers/init.go:99:GlobalInit() [I] ORM engine initialization successful!
2020/06/18 21:17:38 routers/init.go:64:initDBEngine() [I] Beginning ORM engine initialization.
2020/06/18 21:17:38 routers/init.go:71:initDBEngine() [I] ORM engine initialization attempt #1/10...
2020/06/18 21:20:46 routers/init.go:136:GlobalInit() [I] ORM engine initialization successful!
2020/06/18 21:23:39 routers/init.go:64:initDBEngine() [I] Beginning ORM engine initialization.
2020/06/18 21:23:39 routers/init.go:71:initDBEngine() [I] ORM engine initialization attempt #1/10...
2020/06/18 21:23:39 routers/init.go:136:GlobalInit() [I] ORM engine initialization successful!
2020/06/18 21:25:46 routers/init.go:64:initDBEngine() [I] Beginning ORM engine initialization.
2020/06/18 21:25:46 routers/init.go:71:initDBEngine() [I] ORM engine initialization attempt #1/10...
2020/06/18 21:25:46 routers/init.go:136:GlobalInit() [I] ORM engine initialization successful!
2020/06/18 21:28:09 routers/init.go:64:initDBEngine() [I] Beginning ORM engine initialization.
2020/06/18 21:28:09 routers/init.go:71:initDBEngine() [I] ORM engine initialization attempt #1/10...
2020/06/18 21:28:09 routers/init.go:136:GlobalInit() [I] ORM engine initialization successful!
2020/06/18 21:30:34 routers/init.go:64:initDBEngine() [I] Beginning ORM engine initialization.
2020/06/18 21:30:34 routers/init.go:71:initDBEngine() [I] ORM engine initialization attempt #1/10...
2020/06/18 21:30:34 routers/init.go:136:GlobalInit() [I] ORM engine initialization successful!
2020/06/18 21:31:49 routers/init.go:64:initDBEngine() [I] Beginning ORM engine initialization.
2020/06/18 21:31:49 routers/init.go:71:initDBEngine() [I] ORM engine initialization attempt #1/10...
2020/06/18 21:31:49 routers/init.go:136:GlobalInit() [I] ORM engine initialization successful!
2020/06/18 21:32:51 routers/init.go:64:initDBEngine() [I] Beginning ORM engine initialization.
2020/06/18 21:32:51 routers/init.go:71:initDBEngine() [I] ORM engine initialization attempt #1/10...
2020/06/18 21:32:51 routers/init.go:136:GlobalInit() [I] ORM engine initialization successful!
2020/06/18 21:33:39 routers/init.go:64:initDBEngine() [I] Beginning ORM engine initialization.
2020/06/18 21:33:39 routers/init.go:71:initDBEngine() [I] ORM engine initialization attempt #1/10...
2020/06/18 21:33:39 routers/init.go:136:GlobalInit() [I] ORM engine initialization successful!
2020/06/18 21:34:21 routers/init.go:64:initDBEngine() [I] Beginning ORM engine initialization.
2020/06/18 21:34:21 routers/init.go:71:initDBEngine() [I] ORM engine initialization attempt #1/10...
2020/06/18 21:34:22 routers/init.go:136:GlobalInit() [I] ORM engine initialization successful!
2020/06/18 21:35:54 routers/init.go:64:initDBEngine() [I] Beginning ORM engine initialization.
2020/06/18 21:35:54 routers/init.go:71:initDBEngine() [I] ORM engine initialization attempt #1/10...
2020/06/18 21:35:54 routers/init.go:136:GlobalInit() [I] ORM engine initialization successful!
2020/06/18 21:36:43 routers/init.go:64:initDBEngine() [I] Beginning ORM engine initialization.
2020/06/18 21:36:43 routers/init.go:71:initDBEngine() [I] ORM engine initialization attempt #1/10...
2020/06/18 21:36:43 routers/init.go:136:GlobalInit() [I] ORM engine initialization successful!
2020/06/18 21:38:00 routers/init.go:64:initDBEngine() [I] Beginning ORM engine initialization.
2020/06/18 21:38:00 routers/init.go:71:initDBEngine() [I] ORM engine initialization attempt #1/10...
2020/06/18 21:38:00 routers/init.go:136:GlobalInit() [I] ORM engine initialization successful!
2020/06/18 21:39:17 routers/init.go:64:initDBEngine() [I] Beginning ORM engine initialization.
2020/06/18 21:39:17 routers/init.go:71:initDBEngine() [I] ORM engine initialization attempt #1/10...
2020/06/18 21:39:17 routers/init.go:136:GlobalInit() [I] ORM engine initialization successful!
2020/06/18 21:40:55 routers/init.go:64:initDBEngine() [I] Beginning ORM engine initialization.
2020/06/18 21:40:55 routers/init.go:71:initDBEngine() [I] ORM engine initialization attempt #1/10...
2020/06/18 21:40:55 routers/init.go:136:GlobalInit() [I] ORM engine initialization successful!
2020/06/18 21:41:47 routers/init.go:64:initDBEngine() [I] Beginning ORM engine initialization.
2020/06/18 21:41:47 routers/init.go:71:initDBEngine() [I] ORM engine initialization attempt #1/10...
2020/06/18 21:41:47 routers/init.go:136:GlobalInit() [I] ORM engine initialization successful!
2020/06/18 21:43:03 routers/init.go:64:initDBEngine() [I] Beginning ORM engine initialization.
2020/06/18 21:43:03 routers/init.go:71:initDBEngine() [I] ORM engine initialization attempt #1/10...
2020/06/18 21:43:03 routers/init.go:136:GlobalInit() [I] ORM engine initialization successful!
2020/06/18 21:44:33 routers/init.go:64:initDBEngine() [I] Beginning ORM engine initialization.
2020/06/18 21:44:33 routers/init.go:71:initDBEngine() [I] ORM engine initialization attempt #1/10...
2020/06/18 21:44:33 routers/init.go:136:GlobalInit() [I] ORM engine initialization successful!
2020/06/18 21:46:00 routers/init.go:64:initDBEngine() [I] Beginning ORM engine initialization.
2020/06/18 21:46:00 routers/init.go:71:initDBEngine() [I] ORM engine initialization attempt #1/10...
2020/06/18 21:46:00 routers/init.go:136:GlobalInit() [I] ORM engine initialization successful!
2020/06/18 21:49:10 routers/init.go:64:initDBEngine() [I] Beginning ORM engine initialization.
2020/06/18 21:49:10 routers/init.go:71:initDBEngine() [I] ORM engine initialization attempt #1/10...
2020/06/18 21:49:10 routers/init.go:136:GlobalInit() [I] ORM engine initialization successful!

## Description

After switch from Gitea 1.11.6 to 1.12.0 I'm missing the finish of the "ORM engine initialization". Gitea is working. But I'm wondering about the log entries:

2020/06/18 21:49:10 routers/init.go:64:initDBEngine() [I] Beginning ORM engine initialization.
2020/06/18 21:49:10 routers/init.go:71:initDBEngine() [I] ORM engine initialization attempt #1/10...
2020/06/18 21:49:10 routers/init.go:136:GlobalInit() [I] ORM engine initialization successful!

Is this ok. cause I'm waiting for #2/10, #3/10 ... #10/10

If it's ok. Than please close this issue.

**Comment by techknowlogick** [comment]
1/10 is expected as it is attempt 1 out of 10 to connect to your database (in case your database was slow to start).

I will close this now.
