### ISSUE TITLE
Sqlite VACUUM - Is it safe to run?

### ISSUE THREAD

**Issue by salesgroup** [go-gitea/gitea#11968]
We are using Gitea with sqlite3.
Since we have several delete operations (repos, users, webhooks, etc) we would like to run a cron job every day, to clean the database file.
Sqlite vacuum has some potencial problems with tables without "INTEGER PRIMARY KEY" 

I think these tables are: gpg_key_import, external_login_user, oauth2_session, email_hash
details:
`
CREATE TABLE `gpg_key_import` (`key_id` TEXT PRIMARY KEY NOT NULL, `content` TEXT NOT NULL);
`
`
CREATE TABLE `external_login_user` (`external_id` TEXT NOT NULL, `user_id` INTEGER NOT NULL, `login_source_id` INTEGER NOT NULL, `raw_data` TEXT NULL, `provider` TEXT NULL, `email` TEXT NULL, `name` TEXT NULL, `first_name` TEXT NULL, `last_name` TEXT NULL, `nick_name` TEXT NULL, `description` TEXT NULL, `avatar_url` TEXT NULL, `location` TEXT NULL, `access_token` TEXT NULL, `access_token_secret` TEXT NULL, `refresh_token` TEXT NULL, `expires_at` DATETIME NULL, PRIMARY KEY ( `external_id`,`login_source_id` ));
`
`
CREATE TABLE `oauth2_session` (`id` TEXT PRIMARY KEY NOT NULL, `data` TEXT NULL, `created_unix` INTEGER NULL, `updated_unix` INTEGER NULL, `expires_unix` INTEGER NULL);
`
`
CREATE TABLE `email_hash` (`hash` TEXT PRIMARY KEY NOT NULL, `email` TEXT NOT NULL);
`

Is it safe to run sqlite vacuum every day?

**Comment by salesgroup** [comment]
any updates on this?

**Comment by zeripath** [comment]
In my quick searches I can't see an obvious problem with VACUUM. How would you be running VACUUM?

**Comment by salesgroup** [comment]
I didn't activated it on my cron scripts.
I will change the script to run VACUUM daily, thanks
