### ISSUE TITLE
Garbage-Collection not working

### ISSUE THREAD

**Issue by somera** [go-gitea/gitea#11967]
- Gitea version (or commit ref): 1.12.0
- Git version: 2.20.1
- Operating system: Linux pi-manager 4.19.118-v7l+ #1311 SMP Mon Apr 27 14:26:42 BST 2020 armv7l GNU/Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

```
2020/06/18 23:16:11 .../repository/check.go:87:func1() [E] Repository garbage collection failed for &{6 1 gitea_admin <nil> darktable darktable   0  master 1 1 0 0 0 0 0 0 0 0 0 0 false false false true <nil> 0 map[] map[] [] <nil> false 0 <nil> false 0 <nil> 805148937 <nil> <nil> true false []  1568914924 1592466363}. Stdout:
        Error: context deadline exceeded
2020/06/18 23:16:11 ...m.io/xorm/core/db.go:277:ExecContext() [I] [SQL] INSERT INTO `notice` (`type`,`description`,`created_unix`) VALUES (?, ?, ?) [1 Repository garbage collection failed for /home/git/gitea-repositories/gitea_admin/darktable.git. Stdout:
        Error: context deadline exceeded 1592514971] - 57.066786ms
2020/06/18 23:16:11 ...m.io/xorm/core/db.go:277:ExecContext() [I] [SQL] INSERT INTO `notice` (`type`,`description`,`created_unix`) VALUES (?, ?, ?) [2 Error in Task: Garbage collect all repositories: Repository garbage collection failed in repo: gitea_admin/darktable: Error: <nil> 1592514971] - 12.903651ms
```

## Description

I reported the problem in #10299. And in #10745 it war reported as fixed. But this is still not working.

**Comment by lunny** [comment]
The timeout may be too short.

**Comment by somera** [comment]
> The timeout may be too short.

Thx. I try this. It was set only to 60 Seconds.

What mean this:

`Task: Garbage collect all repositories%!(EXTRA string=gitea_admin)`

this will garbage all repositoreis or only repositories for gitea_admin user?

**Comment by somera** [comment]
Looks good. Thx!
