### ISSUE TITLE
Switching Authentication Source for existing user - prev source still works

### ISSUE THREAD

**Issue by markuman** [go-gitea/gitea#11979]
- Gitea version (or commit ref): 1.12.0
- Git version:
- Operating system: docker
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
  - [x] MariaDB
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

My user was a "local" user. With the update to 1.12, I enabled oauth2 nextcloud auth (works fine).  
So I switched the " Authentication Source " for my existing user to the oauth2 method (works fine too).  
But now I'm still able to login into that account using the previous "local" source (username and password).  
Is it by design, because the user exists before? Or is it a bug?

**Comment by lunny** [comment]
I think this is by design. Every user will always have a local user account.

**Comment by markuman** [comment]
So to disable the local auth, I can do 

```sql
update user set passwd = "" where id = 1
```

Is it fine? Or a security nightmare? Any other idea?
