### ISSUE TITLE
GPG Commit Signatures from Gitea 1.12.0

### ISSUE THREAD

**Issue by wkobiela** [go-gitea/gitea#11973]
- Gitea version (or commit ref): 1.12.0
- Git version: 2.26.2
- Operating system: Synology
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

I have a question about setting [repository.signing] i app.ini.

On my account I have GPG set and working - I can sign commits and push it to gitea and they are marked as signed. But Im more intrested of signing merges from PR and other actions made from gitea level.

My app.ini conf looks like this:

    [repository.signing]
    SIGNING_KEY = default
    INITIAL_COMMIT = pubkey
    CRUD_ACTIONS = pubkey
    WIKI = never
    MERGES = pubkey

After setting this, it shows 
![](https://i.imgur.com/hyhlEgA.png)
As it is said here [click](https://github.com/go-gitea/gitea/blob/master/docs/content/doc/advanced/signing.en-us.md) this configuration should

> The  `default`  option will interrogate  `git config`  for  `commit.gpgsign`  option - if this is set, then it will use the results of the  `user.signingkey` ,  `user.name`  and  `user.email`  as appropriate.

So, I edited config file inside selected repository in /gitea-repositories/ and added:

    [commit]
        gpgsign = true
    [user]
        signingkey = D8CC0A720BA8380B
This signkey matches my GPG user key, that works with commits. After this, there is information:
![i.imgur.com/GWdQ1Y3.png](https://i.imgur.com/GWdQ1Y3.png)
If I select Merge PR, I get error 500 and nothing happens. 
![i.imgur.com/V7145al.png](https://i.imgur.com/V7145al.png)
I can't edit files inside this repo too, as I get
![i.imgur.com/BlBhdv4.png](https://i.imgur.com/BlBhdv4.png)

I made some changes in another Test repo (where I didnt change any configuration) and there I can add and edit files from gitea, ofc. they wont be signed. I cloned it and checked `git log --show-signature` and commits from gitea have author with my user name (correct) and email set as username@noreply.domain.com. I assume, that this is because I have my email address set as private. But there is NO WAY to add GPG signature containing @noreply address, as Gitea says that this email address is not connected with my profile!

So, I set my email as visible. Now, commits from gitea are marked with my correct username and email. Still, wont get signed. I've set up everything as mentioned above and then I can't add file, or merge PR as some kind of GPG error.

What am I doing wrong? There must be something wrong with GPG key, but instructions provided are unclear to me. I thought that Gitea would use my user GPG key attached to my accound from which I try to do some action and signature from repo config matches my key. But it doesnt work that way.

I've seen here [github.com/go-gitea/gitea/pull/9784](github.com/go-gitea/gitea/pull/9784) that he uses email address as key(?) but I have no idea how to set that.

**Comment by a1012112796** [comment]
ping, I think we need more check.

**Comment by zeripath** [comment]
From https://docs.gitea.io/en-us/signing/

The default option will interrogate git config for commit.gpgsign option - if this is set, then it will use the results of the user.signingkey, user.name and user.email as appropriate.

If you want the default to sign you need to set commit.gpgsign in your .gitconfig

**Comment by lunny** [comment]
@Wuszek Is this still a problem?

**Comment by techknowlogick** [comment]
closing. please re-open if still an issue
