### ISSUE TITLE
Protect tags push

### ISSUE THREAD

**Issue by micheelengronne** [go-gitea/gitea#11985]
- Gitea version (or commit ref): v1.12.0
- Git version: 2.25.1
- Operating system: ubuntu
- Database (use `[x]`):
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:

## Description

There is currently no way (AFAIK) to disable tag push via git cli. That means a user who can push code to a repository can always push tags.

Is there a way to protect tags creation the same way than branches and the same way than Github or Gitlab ?

Thanks.

**Comment by achikhv** [comment]
In our pipeline tags must be created only by CI/CD user. It would be great if we could restrict uses who can push tags to repo.

**Comment by lunny** [comment]
This has been fixed by #15545
