### ISSUE TITLE
Add LibreJS support

### ISSUE THREAD

**Issue by strk** [go-gitea/gitea#1200]
This was added in Gogs on February 8 2017:
https://github.com/gogits/gogs/pull/4092

Would be good to have that PR ported to Gitea too.

**Comment by tboerger** [comment]
I still got the opinion that this is a pretty useless feature.

**Comment by lunny** [comment]
Why we need add this lib?

**Comment by strk** [comment]
@tboerger it is as useful as having a LICENSE file in the Gitea source code, and all those copyright info.

**Comment by strk** [comment]
NOTE: there's no `lib` being added, just information about the license covering the Javascript code distributed by the service
