### ISSUE TITLE
Upgrade breaks layout

### ISSUE THREAD

**Issue by cylott** [go-gitea/gitea#12001]
Hi, I recently upgraded gitea from 1.9.3 to 1.12.0. I assumed I could simply drop in the new binary as before. This did not work well. I loaded the repo in a browser and the layout was all broken - looking at the console the page was trying to load all sorts of js and css resources that were 404: polyfill, semantic, cssrel something etc

I then ran gitea —migrate which seemed to do something to my sqlite db. Loading the page afterwards, I could see fewer 404s, now just looking for semantic.js, but the page was still broken. Everything was working, but obviously key css resources were not found.

I also tried building from source with the same results. Any ideas? I'm on a mac.

**Comment by lunny** [comment]
Have you cleared your browser cache?

**Comment by zeripath** [comment]
And are you using custom templates?

**Comment by cylott** [comment]
> Have you cleared your browser cache?

Yes.

**Comment by cylott** [comment]
> And are you using custom templates?

I'm using arc-green theme and a custom header.

**Comment by cylott** [comment]
Ah ok, I turned off the custom header and it seems to be working now. All that was in there was a Matomo JS.

What does "gitea --migrate" do? Was there any reason to run that on my db?

**Comment by zeripath** [comment]
Have you checked that your custom header is not out of sync with what we have in 1.12?

In 1.12/master we also changed the serviceworker so clearing the cache is actually slightly more difficult than you might initially think. (That would resolve itself in 24 hours...) Have you tried browsing on an incognito session or different browser just to confirm that the cache is definitely not involved?

**Comment by silverwind** [comment]
A common issue is that people still build with `make generate build`. Please update that to `make build` if you're doing that.

**Comment by zeripath** [comment]
@cylott the migration occurs automatically because between versions we often change the database slightly.

It appears though we've answered your problem. I'm not sure what Matamo js is it how it causes problems but I guess you need to check your browser console to work that out. 

I'll close this issue now.
