### ISSUE TITLE
Docker tag gitea/gitea:1 is not monotonic

### ISSUE THREAD

**Issue by hweidner** [go-gitea/gitea#12008]
- Gitea version (or commit ref): 1.12.0 / 1.11.8
- Git version: 2.20.1
- Operating system: Debian GNU/Linux 10
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

I ran Gitea from the Docker Hub image gitea/gitea:1. Until now, this was Gitea 1.12.0. After a docker pull today, it downgraded to Gitea 1.11.8. This is unexpected, I always thought that the tag does not downgrade.

I'd suggest making the tag gitea/gitea:1 monotonic. I.e. even when newer versions of 1.11.x come out, gitea/gitea:1 stays 1.12.0 until 1.12.1 gets released.

**Comment by pablofsf** [comment]
This could possibly be fixed by #11897 or is at least related

**Comment by lafriks** [comment]
It should be now 1.12.1. It was just pointing to 1.11.8 in between while drone does build version. When releasing versions in multiple releases branches like this time v1.11.8 and v1.12.1 it could point to wrong version for some time as Gitea release process takes more than hour to finish. It should not happen often as we rarely do minor versions to two major version branches.

**Comment by lafriks** [comment]
Closing this as fixed as now it points correctly but in long term should be fixed in #11897
