### ISSUE TITLE
No notification bell, plus icon and others

### ISSUE THREAD

**Issue by dimmuboy** [go-gitea/gitea#12012]
- Gitea version (or commit ref): 1.12.1
- Git version: 2.25.0
- Operating system: Windows Server 2008
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:
 no relevant log was founded

## Description

After upgrate to version 1.12.0 ring bell icon from notification button disappeared and error is shown instead. Plus icon and dropdown carret is missing too same as some icons from dropdown menu.

## Screenshots

![image](https://user-images.githubusercontent.com/12607479/85273478-f1458c00-b47d-11ea-9944-b73ce0a1690a.png)

![image](https://user-images.githubusercontent.com/12607479/85274014-a8da9e00-b47e-11ea-906a-afdfeb610b73.png)

**Comment by oaxiento** [comment]
+1 ... we're having the same issue

**Comment by silverwind** [comment]
Check in browser devtools if `/img/svg/icons.svg` did load correctly.

**Comment by oaxiento** [comment]
> Check in browser devtools if `/img/svg/icons.svg` did load correctly. If this is a custom build, make sure it's built via `make build`, not `make generate build`.

`/img/svg/icons.svg` loads just fine. I used the release from github. I even did a fresh install of gitea, but without any luck.

**Comment by oaxiento** [comment]
Solved it on our side. The issue was a custom Template for the Navbar (head_navbar.tmpl).
@dimmuboy check if you're using a Templat for your Navbar.

**Comment by dimmuboy** [comment]
Thank you @oaxiento that's really what break my git. I update all used tmpl files.
