### ISSUE TITLE
Migration does not clone repository from the proxy

### ISSUE THREAD

**Issue by Zoranner** [go-gitea/gitea#12018]
- Gitea version (or commit ref): 1.12.1
- Git version: 2.27.0
- Operating system: Windows 10
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:
Nothing.

## Description
I configured git's global http & https proxy to http://127.0.0.1:1086, but it seems that migration does not clone repository from the proxy.

## Screenshots

Nothing.

**Comment by lunny** [comment]
We need a global proxy setting for all the external http request not only webhook.

**Comment by Zoranner** [comment]
@lunny 麻烦问一下，现阶段有没有什么临时的解决方案可以解决Gitea迁移仓库不走全局代理设置的问题，大部分时候在国内Clone Github的项目都会特别慢，没有代理迁移项目太难了😣

**Comment by lunny** [comment]
I think we need a global proxy setting.

**Comment by zeripath** [comment]
This would likely be a good first issue
