### ISSUE TITLE
Complete convert method (add alter  ROW_FORMAT=DYNAMIC)

### ISSUE THREAD

**Issue by camlafit** [go-gitea/gitea#12019]
-  Gitea version (or commit ref): 1.11.5 P
- Git version: 2.x
- Operating system: Debian
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
[gitea convert](https://docs.gitea.io/en-us/command-line/#convert)` break on conversion with oauth_* tables about key length. 

Server is correctly set with  mysqld options : 
- innodb_large_prefix=true
- innodb_file_format=barracuda
- innodb_file_per_table=1

Gitea can't alter charset  because row_format is not updated.

## To solve

To allow gitea to convert without error, could be nice to set row_format=dynamic before all charset/collate change.
`alter table oauth_table ROW_FORMAT=DYNAMIC; is enough.`

Second point when conversion is done , a link to https://github.com/go-gitea/gitea/blob/master/custom/conf/app.example.ini#L378-L380 could usefull to administrator to know how to change gitea config.

thanks

**Comment by lunny** [comment]
@camlafit Could you send a PR for that?

**Comment by camlafit** [comment]
Hello

I could be but I need at least a pointer to know where to start. I'm not 
golang/gitea fluent :)
I think could be a trivial patch.

Km

**Comment by camlafit** [comment]
Hello

I've forgot this issue. I can redo a check. Any idea how to start this PR ?

**Comment by lunny** [comment]
resolved by #12804
