### ISSUE TITLE
Small layout error when repository is presented in landscape on mobile

### ISSUE THREAD

**Issue by carlonluca** [go-gitea/gitea#12025]
- Gitea version (or commit ref): 1.12.1
- Git version: 
- Operating system: Raspbian
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL): https://try.gitea.io/carlonluca/Test2
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

When seen in landscape on a mobile phone, there is a minor problem with the layout. Attached is a screenshot of the view that does not fit properly. The screen here is 2960x1440, 516ppi.

## Screenshots

![Screenshot_20200622-225127_Chrome](https://user-images.githubusercontent.com/3678828/85335949-22ee3f80-b4de-11ea-8aa1-4d74c18210a1.jpg)

**Comment by carlonluca** [comment]
Issue is still valid.

**Comment by denyskon** [comment]
This issue is no longer present.
