### ISSUE TITLE
Support multiple forks within the same organization

### ISSUE THREAD

**Issue by flomontl** [go-gitea/gitea#12021]
- Gitea version (or commit ref): 1.12.0
- Can you reproduce the bug at https://try.gitea.io:
  - [x ] Yes (provide example URL)

## Description
This is not possible with GITea to fork a repo twice (or more) within the same organization.
Whereas it seems to be possible in GITLab:
https://gitlab.com/gitlab-org/gitlab-foss/-/issues/36268

**Comment by lunny** [comment]
I don't think github will allow you do that.

**Comment by 6543** [comment]
I dont see an good usecase in this

**Comment by flomontl** [comment]
@lunny , I read this link: https://gitlab.com/gitlab-org/gitlab-foss/-/issues/36268
