### ISSUE TITLE
User created by admin goes to 403 when password changed

### ISSUE THREAD

**Issue by micheelengronne** [go-gitea/gitea#12035]
- Gitea version (or commit ref): 1.12.1
- Git version: not relevant
- Operating system:
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X] No
  - [ ] Not relevant
- Log gist:

Given an admin creates a user and force the user to change its password
When the user log in, is automatically redirected to the password change form and change its password
Then the page is redirected to `/admin/users/USERID` so 403 for the user.

**Comment by micheelengronne** [comment]
If I do other stuff between the user creation and the `logout/login/password update` that works.

**Comment by micheelengronne** [comment]
I think these commit cause the bug somehow:

https://github.com/go-gitea/gitea/commit/a00974c3b8a589677c508c522d3aab8b57b839f3

https://github.com/go-gitea/gitea/commit/017f314b5a0f930b477efa1c2a5309f8cdd6d3c3#diff-674a60493626b4320fa19856b43c9472

**Comment by zeripath** [comment]
This appears to work on 1.13 - is this still a problem?

**Comment by lafriks** [comment]
marking as fixed, please repoen if it is still problem in latest development version
