### ISSUE TITLE
.png file: UploadAvatar: DecodeConfig: image: unknown format

### ISSUE THREAD

**Issue by turbopixel** [go-gitea/gitea#12033]
- Gitea version (or commit ref): https://gitea.com/user/settings
- Database (use `[x]`):
  - [X] Not relevant
- Can you reproduce the bug at
  - [x] Yes on: https://gitea.com

## Description

I just download a png file [1] from iconfinder.com and try to upload the image as my profile picture and organisation picture. At both places I get the error message: `UploadAvatar: DecodeConfig: image: unknown format`.

I can reproduce the problem on gitea.com and also on my self-hosting instance.

[1] https://www.iconfinder.com/icons/998682/browser_internet_icon

## Screenshots

1. download file
![grafik](https://user-images.githubusercontent.com/15839724/85518478-90928c80-b600-11ea-9fc2-2df664f16f5e.png)

2. select file
![grafik](https://user-images.githubusercontent.com/15839724/85518380-76f14500-b600-11ea-8c62-bba274526855.png)

3. upload file
![grafik](https://user-images.githubusercontent.com/15839724/85518397-7a84cc00-b600-11ea-8801-6362438e7e8b.png)

windows can open it
![grafik](https://user-images.githubusercontent.com/15839724/85518910-10205b80-b601-11ea-9a1c-b6f2ad2ed8f2.png)

**Comment by turbopixel** [comment]
Oh great.. When I select the **128x128px** size from iconfinder, I can upload the image.
I think its a image size problem.

**Comment by netthier** [comment]
Cannot reproduce in 1.13.0+dev-266-gcd994f635 (docker container).
I tried setting both the 256px and the 512px icon as a profile picture, both of which worked without a problem
![](https://i.imgur.com/dxR7xo9.png)
![](https://i.imgur.com/3C7Hzs4.png)

**Comment by mrsdizzie** [comment]
Same here can't reproduce -- perhaps there was just an issue when you downloaded the image originally and it was corrupt/incomplete?

**Comment by turbopixel** [comment]
It is possible that the file is broken. Only the 256px version cannot be uploaded. 
From home I can upload the file. Maybe the problem is my pc at work.

Thanks, I guess it's a local problem.

**Comment by bobemoe** [comment]
Just experienced this too. Turns out the .png was actually a RIFF.
