### ISSUE TITLE
Admin navbar menu entries are innaccesible on WXGA screens and certain locales.

### ISSUE THREAD

**Issue by codestation** [go-gitea/gitea#12031]
- Gitea version (or commit ref): 1.12.1
- Git version: not relevant
- Operating system: Docker image
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:
Not relevant.

## Description

The admin dashboard on a WXGA screen (1366x768) while using the _Español_ (Spanish) language makes impossible to access some menu entries. On my screenshot the _Panel de Control_ (Dashboard) and _Monitorización_ (Monitoring) entries are outside the screen, thus cannot be selected. Cannot try on the try.gitea.io site because it requires access to the admin dashboard.

This seems more like a UX problem than a layout/locale one because even if a menu entry is removed or the text shortened then another language similar resolution could cause the same problem again.

Maybe rolling back to a vertical menu would be the solution as other platforms does the same for their settings pages.

## Screenshots

![Screenshot_20200623_184813](https://user-images.githubusercontent.com/61178/85485316-1b866f00-b58e-11ea-8e64-d11e568f2d41.png)

**Comment by kolaente** [comment]
Somewhat related to #12025

**Comment by mateusza** [comment]
![image](https://user-images.githubusercontent.com/7002/86270084-f667b100-bbca-11ea-8208-9f745dc6eb79.png)

The same here

**Comment by silverwind** [comment]
Those menu overflows should all be fixed on master and upcoming 1.14. It will wrap to second line on small screens while being horizontally scrollable on bigger ones.
