### ISSUE TITLE
User dashboard repositories filter incorrectly handles repos with NULL "is_archived" column

### ISSUE THREAD

**Issue by oreineke** [go-gitea/gitea#12037]
- Gitea version (or commit ref): 1.12.1
- Git version:
- Operating system: Ubuntu 18.04
- Database (use `[x]`):
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
If you have repos that have a NULL "is_archived" value in the "repositories" table, they are not shown if you filter for not-archived repositories in the user's dashboard repositories widget. 

This is because the related SQL queries filter for "is_archived=false", which does not match NULL.

Repos that have a NULL "is_archived" value are those created before the archive feature was introduced in Gitea I suspect.

A possible solution might be to automatically migrate "is_archived=NULL" to "is_archived=false" in the "repositories" table.

**Comment by kolaente** [comment]
I think migrating `is_archived=NULL` to `is_archived=false` is the way to go here.

**Comment by 6543** [comment]
will create a pull

**Comment by mrsdizzie** [comment]
Hmm we did this:


 https://github.com/go-gitea/gitea/pull/11853

**Comment by 6543** [comment]
@oreineke are you sure you are on 1.12.1 ?

**Comment by oreineke** [comment]
Yes, I am sure, this is a copy and paste from the web page: "Powered by Gitea Version: 1.12.1"

**Comment by oreineke** [comment]
Maybe also relevant: I am running Gitea in Docker, so I pulled image gitea/gitea:1.12 (before, I was running gitea/gitea:1.11).

**Comment by oreineke** [comment]
I also ran "gitea doctor --all" in the container and that did not help (or complain, all reported as "OK").

**Comment by oreineke** [comment]
Please disregard my last comment: On closer inspection I now see in the "gitea doctor --all" output

    [ 3 ] Check consistency of database
    - 13 repositories with null is_archived
    OK.

The "OK" is kind of misleading.

**Comment by oreineke** [comment]
These are the Migrations I see in the log:
```
gitea.log:2020/06/24 08:46:14 ...ations/migrations.go:300:Migrate() [I] Migration[118]: Add commit id and stale to reviews
gitea.log:2020/06/24 08:46:16 ...ations/migrations.go:300:Migrate() [I] Migration[119]: Fix migrated repositories' git service type
gitea.log:2020/06/24 08:46:17 ...ations/migrations.go:300:Migrate() [I] Migration[120]: Add owner_name on table repository
gitea.log:2020/06/24 08:46:18 ...ations/migrations.go:300:Migrate() [I] Migration[121]: add is_restricted column for users table
gitea.log:2020/06/24 08:46:19 ...ations/migrations.go:300:Migrate() [I] Migration[122]: Add Require Signed Commits to ProtectedBranch
gitea.log:2020/06/24 08:46:20 ...ations/migrations.go:300:Migrate() [I] Migration[123]: Add original informations for reactions
gitea.log:2020/06/24 08:46:22 ...ations/migrations.go:300:Migrate() [I] Migration[124]: Add columns to user and repository
gitea.log:2020/06/24 08:46:22 ...ations/migrations.go:300:Migrate() [I] Migration[125]: Add some columns on review for migration
gitea.log:2020/06/24 08:46:23 ...ations/migrations.go:300:Migrate() [I] Migration[126]: Fix topic repository count
gitea.log:2020/06/24 08:46:23 ...ations/migrations.go:300:Migrate() [I] Migration[127]: add repository code language statistics
gitea.log:2020/06/24 08:46:26 ...ations/migrations.go:300:Migrate() [I] Migration[128]: fix merge base for pull requests
gitea.log:2020/06/24 08:46:26 ...ations/migrations.go:300:Migrate() [I] Migration[129]: remove dependencies from deleted repositories
gitea.log:2020/06/24 08:46:26 ...ations/migrations.go:300:Migrate() [I] Migration[130]: Expand webhooks for more granularity
gitea.log:2020/06/24 08:46:26 ...ations/migrations.go:300:Migrate() [I] Migration[131]: Add IsSystemWebhook column to webhooks table
gitea.log:2020/06/24 08:46:27 ...ations/migrations.go:300:Migrate() [I] Migration[132]: Add Branch Protection Protected Files Column
gitea.log:2020/06/24 08:46:27 ...ations/migrations.go:300:Migrate() [I] Migration[133]: Add EmailHash Table
gitea.log:2020/06/24 08:46:27 ...ations/migrations.go:300:Migrate() [I] Migration[134]: Refix merge base for merged pull requests
gitea.log:2020/06/24 08:46:27 ...ations/migrations.go:300:Migrate() [I] Migration[135]: Add OrgID column to Labels table
gitea.log:2020/06/24 08:46:27 ...ations/migrations.go:300:Migrate() [I] Migration[136]: Add CommitsAhead and CommitsBehind Column to PullRequest Table
gitea.log:2020/06/24 08:46:27 ...ations/migrations.go:300:Migrate() [I] Migration[137]: Add Branch Protection Block Outdated Branch
gitea.log:2020/06/24 08:46:27 ...ations/migrations.go:300:Migrate() [I] Migration[138]: Add ResolveDoerID to Comment table
gitea.log:2020/06/24 08:46:27 ...ations/migrations.go:300:Migrate() [I] Migration[139]: prepend refs/heads/ to issue refs
gitea.log:2020/06/24 08:46:27 ...ations/migrations.go:300:Migrate() [I] Migration[140]: Save detected language file size
```

**Comment by mrsdizzie** [comment]
This is not a migration on Gitea 1.12 (see previously linked issue) thats why it was added to the doctor command. Looks like it worked based on the doctor output above?

**Comment by oreineke** [comment]
OK, I see!

Running `gitea doctor --all --fix`, just fixed it, thanks!
