### ISSUE TITLE
Custom meta description

### ISSUE THREAD

**Issue by pgaskin** [go-gitea/gitea#1204]
It would be better if there could be a custom meta description because right now, it is always the same.

**Comment by lunny** [comment]
What do you mean?

**Comment by pgaskin** [comment]
In the head element, the tag meta[name=description] will contain the description of gitea by default. Since this shows on search results, it would be good to be able to change this default message.

**Comment by lunny** [comment]
A custom http meta? Maybe put it in app.ini?

**Comment by pgaskin** [comment]
Yes, and probably in the same section as the app name.

On Mar 11, 2017 8:29 AM, Lunny Xiao <notifications@github.com> wrote:

A custom http meta? Maybe put it in app.ini?

**Comment by pgaskin** [comment]
Fixed by #1423

**Comment by danger89** [comment]
@pgaskin This is not documented. Can somebody add this to the docs? https://docs.gitea.io/en-us/config-cheat-sheet/

**Comment by zeripath** [comment]
PR s are welcome

**Comment by danger89** [comment]
@zeripath  Created :+1:   https://github.com/go-gitea/gitea/pull/12946

**Comment by zeripath** [comment]
Thanks!
