### ISSUE TITLE
Sometimes, pages load for an infinite amount of time.

### ISSUE THREAD

**Issue by mind-overflow** [go-gitea/gitea#12045]
- Gitea version (or commit ref): started noticing it in 1.10, but still happening in 1.12.1
- Git version: 2.25.1
- Operating system: Ubuntu server 20.04 LTS
- Database: MySQL ver 15.1 (10.3.22-MariaDB)

## Description

Gitea is running behind an Apache2 reverse proxy, at git.domain.com.

Usually, while browsing pages in my Gitea installation, the web browser almost instantly loads the destination page without any problem, showing only for a very small amount of time the "loading" tab icon. However, in a seemingly random pattern, sometimes pages never finish loading. I am just stuck on a white blank page with the "loading" tab icon spinning forever. During this time, no page is accessible and everything I click on takes forever to load.

My pages take about 150ms to generate, plus about 50ms for template. If I close and re-open the same page, it almost always works, however I have to wait a few seconds before retrying, since it looks like the whole Gitea server is frozen.

My server RAM and CPU usages are always below 30%; the disk usage is at 10%. Network bandwidth is also not a problem.
I am hosting Grafana on the same server (also behind a reverse proxy), and while Gitea is frozen, I can still navigate through Grafana pages, so it means the problem is not related to hardware or connectivity.

**Comment by zeripath** [comment]
I'm betting this a duplicate of #11978

**Comment by mind-overflow** [comment]
Looks like it. I have testes opening multiple tabs, and after opening 5, the 6th one hangs and loads forever.
I'll be following and participating in the correct issue from now on. Thanks!
