### ISSUE TITLE
Could you please help me compile gitea to 32-bit windows system by make?

### ISSUE THREAD

**Issue by Zoranner** [go-gitea/gitea#12042]
- Gitea version (or commit ref): 1.12.1
- Git version: 2.27.0
- Operating system: Windows 10
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

As the title says: Could you please help me compile gitea to 32-bit windows system by make? Thank you very much.

**Comment by lunny** [comment]
What's the problem when you run `make build` on target system?

**Comment by Zoranner** [comment]
> What's the problem when you run `make build` on target system?

```bash
KimoTech@KIMOZORAN  D:\Personals\Desktop\others\gitea   master ≣ ~1 -0 !                                   [12:45]
❯ make build
系统找不到指定的路径。
'C:' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
系统找不到指定的路径。
'sed' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
FIND: 参数格式不正确
拒绝访问 - CMD
拒绝访问 - INTEGRATIONS
拒绝访问 - MODELS
拒绝访问 - MODULES
拒绝访问 - ROUTERS
拒绝访问 - BUILD
拒绝访问 - SERVICES
拒绝访问 - VENDOR
找不到文件 - -TYPE
找不到文件 - F
找不到文件 - -NAME
找不到文件 - -NOT
找不到文件 - -PATH
找不到文件 - -NOT
找不到文件 - -PATH
找不到文件 - -NOT
找不到文件 - -PATH
系统找不到指定的路径。
'cut' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'printf' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
系统找不到指定的路径。
此时不应有 ""。
Makefile:191: recipe for target 'node-check' failed
make: *** [node-check] Error 255
```

**Comment by MaiReo** [comment]
> > What's the problem when you run `make build` on target system?
> 
> @lunny 我尝试使用PowerShell Core执行 `make build` 得到以下错误：
> 
> ```shell
> KimoTech@KIMOZORAN  D:\Personals\Desktop\others\gitea   master ≣ ~1 -0 !                                   [12:45]
> ❯ make build
> 系统找不到指定的路径。
> 'C:' 不是内部或外部命令，也不是可运行的程序
> 或批处理文件。
> 系统找不到指定的路径。
> 'sed' 不是内部或外部命令，也不是可运行的程序
> 或批处理文件。
> FIND: 参数格式不正确
> 拒绝访问 - CMD
> 拒绝访问 - INTEGRATIONS
> 拒绝访问 - MODELS
> 拒绝访问 - MODULES
> 拒绝访问 - ROUTERS
> 拒绝访问 - BUILD
> 拒绝访问 - SERVICES
> 拒绝访问 - VENDOR
> 找不到文件 - -TYPE
> 找不到文件 - F
> 找不到文件 - -NAME
> 找不到文件 - -NOT
> 找不到文件 - -PATH
> 找不到文件 - -NOT
> 找不到文件 - -PATH
> 找不到文件 - -NOT
> 找不到文件 - -PATH
> 系统找不到指定的路径。
> 'cut' 不是内部或外部命令，也不是可运行的程序
> 或批处理文件。
> 'printf' 不是内部或外部命令，也不是可运行的程序
> 或批处理文件。
> 系统找不到指定的路径。
> 此时不应有 ""。
> Makefile:191: recipe for target 'node-check' failed
> make: *** [node-check] Error 255
> ```
> 
> 我尝试使用 `GOOS=windows GOARCH=386 go build` 进行编译，得到一个65.9M大小的可执行文件，但只能在本地运行，无法部署到其他计算机。大概是没有将外部资源一块打包的原因。

尝试使用mingw代替msvc编译

**Comment by lunny** [comment]
Don't run the make build on powershell. You should run it on `cywin` or like shell.
