### ISSUE TITLE
GPG key expired

### ISSUE THREAD

**Issue by solacelost** [go-gitea/gitea#12054]
- Gitea version (or commit ref): 1.12.1
- Git version: N/A
- Operating system: N/A
- Database (use `[x]`): N/A
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist: N/A

## Description

GPG key used for signing releases expired two days after release published.
```
# gpg --list-keys
/root/.gnupg/pubring.kbx
------------------------
pub   rsa4096 2018-06-24 [SC] [expired: 2020-06-23]
      7C9E68152594688862D62AF62D9AE806EC1592E2
uid           [ expired] Teabot <teabot@gitea.io>
```

Would just like to make sure it's tracked, renewed, and published before the next release. Thanks for all you do! :)

**Comment by lunny** [comment]
We have renewed it. Could you try to refresh the keys?
