### ISSUE TITLE
First system user created upon logging in via LDAP is not marked as admin

### ISSUE THREAD

**Issue by strk** [go-gitea/gitea#1206]
Version 1.1.0.
Start with an empty database, configure usage of LDAP.
Login via LDAP results in automatic creation of local user record corresponding to the LDAP record, but even if that's the very first local user created, such user is *not* marked as administrator, which results in a system with no administrator users.

I'm not sure if this is a regression or not, didn't try with 1.0.x

**Comment by pgaskin** [comment]
I don't think it's a regression, I just tried it myself. 

Also, can you review go-gitea/docs#99 and go-gitea/gitea#1207 :smile:

**Comment by lunny** [comment]
How does first user login via LDAP?

**Comment by strk** [comment]
@lunny now this is a good question. In my case I created an admin user, added the loginSource then removed the admin user. But in general you're right that's currently not straightforward to enable LDAP w/out first creating an admin user. That's a problem addressed in #183

**Comment by lunny** [comment]
So delete the last user is a deny operation we should send a PR to do that.
