### ISSUE TITLE
API raw route should support tags/branches

### ISSUE THREAD

**Issue by brandonkal** [go-gitea/gitea#12066]
- Gitea version (or commit ref): master

## Description

/repos/{owner}/{repo}/raw/{filepath} only supports the master branch. It should also support specifying branch and tag.

As far as I can tell, I have to use the /repos/{owner}/{repo}/contents/{filepath} route and then decode the base64 contents.

For my specific use case, I would also like to see the raw download url accept Authorization token headers.

**Comment by zeripath** [comment]
Why can't you use the `?ref=` parameter.

**Comment by neolithos** [comment]
Because is not mentioned in the swagger help page.

**Comment by zeripath** [comment]
Actually I'm wrong the ref Param isn't used on this path. Apologies.

However looking at the code, I think the file path needs to be the same as on the actual site.

That is:

/api/v1/repos/{owner}/{name}/raw/branch/{branch name}/{file path}

And so on for tags and commits

**Comment by d-lunyov** [comment]
Looks like it is duplicate https://github.com/go-gitea/gitea/issues/14597
