### ISSUE TITLE
Create a admin user in gitea postgres

### ISSUE THREAD

**Issue by BagaSiva** [go-gitea/gitea#12076]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

Hi All

I have deployed a Gitea POD. The backend is Postgres. 

I need to create a admin user for Gitea. As its a first user, am not able to create it from GIT Rest API.

Please help how to create a first user from either gitea or postgres container.

Thanks in advance
Thanks
Siva
...

**Comment by lafriks** [comment]
You can use gitea cli to do that check docs.gitea.io for more info
