### ISSUE TITLE
Can't push to project (mirror) in Gitea 1.12.1

### ISSUE THREAD

**Issue by somera** [go-gitea/gitea#12075]
- Gitea version (or commit ref): 1.12.1
- Git version: 2.20.1
- Operating system: Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

I have project mirror in my Gitea. This project is assigned to an organization. I created new Dev-TEAM with two developers in this organisation.

![image](https://user-images.githubusercontent.com/8334250/85931744-edbf6400-b8c6-11ea-890a-cb9ce50e6c9b.png)

Now I will push some changes in extra branch. But I get:

```
$ git push -u origin new_branch
Gitea: Unauthorized
Mirror Repository frameworks/name-machine is read-only
fatal: Could not read from remote repository.
```

In the gitea.log I see this query:

`2020/06/27 22:39:48 ...m.io/xorm/core/db.go:154:QueryContext() [I] [SQL] SELECT repository.* FROM `repository` INNER JOIN `user` ON `user`.id = repository.owner_id WHERE (repository.lower_name = ?) AND (`user`.lower_name = ?) LIMIT 1 [name-machine frameworks] - 772.797µs`

The same gitea user is added do the owners team in this organization.

Please make sure you have the correct access rights
and the repository exists.

**Comment by zeripath** [comment]
As currently coded mirrors are read-only. You can fork the mirror and make changes with that.

There's an idea that mirrors should instead mirror the mirrored branches to a prefixed branch namespace: say "upstream/". Then we could allow users to push to the non-mirrored branches.

That doesn't get you much further though - clearly what most users would prefer would be some way of auto-tracking of upstream with their changes and some way of auto pushing those changes back up. That is a much harder problem which is under-specified at present.

**Comment by somera** [comment]
@zeripath thx!
