### ISSUE TITLE
Pull Request ref not available immediatly after pushing

### ISSUE THREAD

**Issue by kolaente** [go-gitea/gitea#12074]
- Gitea version (or commit ref): 1.13.0+dev-221-g6891b9030
- Git version: 
- Operating system: official docker container
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description

Most of the time when I push an update to an existing PR in Gitea, a webhook for drone is fired immediatly even if the pull ref is not (yet) available. Thus, the drone clone step fails with something like this:
```
Initialized empty Git repository in /go/src/repo/.git/
+ git fetch origin +refs/heads/master:
From <repo url>
 * branch            master     -> FETCH_HEAD
 * [new branch]      master     -> origin/master
+ git checkout master
Branch 'master' set up to track remote branch 'master' from 'origin'.
Already on 'master'
+ git fetch origin refs/pull/594/head:
fatal: Couldn't find remote ref refs/pull/594/head
```

The PR reflects that:
![image](https://user-images.githubusercontent.com/13721712/85926942-0453c400-b8a3-11ea-8b36-870a90edae86.png)

After a few seconds, it goes back to normal:
![image](https://user-images.githubusercontent.com/13721712/85926970-36fdbc80-b8a3-11ea-8f20-c0627cf12123.png)

If I then manually restart the build in drone, everything works as expected.

It seems to be an issue with my server performance which takes the ref so long to be available, but IMHO Gitea should not fire the webhook until the ref is available.

**Comment by CirnoT** [comment]
https://github.com/go-gitea/gitea/blob/262fce6db4ab87e03926ac7a21bc5e4bea7ea815/services/pull/pull.go#L281 happens before https://github.com/go-gitea/gitea/blob/262fce6db4ab87e03926ac7a21bc5e4bea7ea815/services/pull/pull.go#L286 and even if it didn't, the head repo tasks are async.
