### ISSUE TITLE
migrating to new server/domain caused links to break

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#12071]
- Gitea version (or commit ref):  1.12.1
- Git version:2.20.1
- Operating system: debian 10
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

I used `gitea dump` to backup gitea installation (as documented @ https://docs.gitea.io/en-us/backup-and-restore/) and installed on a different server w/ the exact same configuration as the old one, except w/ a different domain name, e.g. git.B.com rather than git.A.com. This caused various hyperlinks to break on the new install.  The links for repos within organizations are just https://{reponame} instead of https://git.B.com/{org}/{reponame}, and links to issues are https://{reponame}/issues. Upon creating new organizations and repositories, the new links work fine, while the old ones are still broken. I have tried the various maintenance options in the panel.

Any insight into why this would be happening?

**Comment by legovaer** [comment]
I got exactly the same issue. I was using version `1.8.1` and upgrade towards `1.12.1`.

**Comment by rj1** [comment]
@legovaer I'm not sure which version of gitea I was using on the previous setup, but it was setup 6-8 months ago so it was probably an older version, maybe even the same. 

I did a workaround by creating a new org, transferring repos to that org, deleting original org, then renaming the new org to the old name. Now the links are working fine.

**Comment by lafriks** [comment]
As this was probably migration issue I will close this issue for now
