### ISSUE TITLE
Command line option for the custom directory path

### ISSUE THREAD

**Issue by silverwind** [go-gitea/gitea#1208]
To keep the gitea directory pristine, I currently symlink the `custom` directory to a directory outside which contains my config and various overrides.

I think it would be useful if one could specify the path to the custom directory, for example through a `-c <custom-dir>` switch  (which would enable me to skip the symlink step).

**Comment by tboerger** [comment]
Just define the GITEA_CUSTOM environment variable to set this path. We won't break this behavior for minor releases.

**Comment by silverwind** [comment]
Thanks, I wasn't aware of that variable. Probably a good idea to add supported environment variables to `--help` to raise awareness.

**Comment by pgaskin** [comment]
I am currently working on documenting these lesser known features of gitea.

**Comment by gsantner** [comment]
I would too suggest to add it at least to the `--help` help, as this is the command most likely used first to find out which argument needs to be set, after trying `--config=` and seeing it does not work 😄
