### ISSUE TITLE
It's possible set the cron.* values to special time?

### ISSUE THREAD

**Issue by somera** [go-gitea/gitea#12083]
- Gitea version (or commit ref): 1.12.1
- Git version: 2.20.1
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

My actual cron.update_mirrors configurations is:

```
; Update mirrors
[cron.update_mirrors]
SCHEDULE = @every 24h
```

But @every 24h depends when Gitea was started. It's possible to set this to special time? I will that the mirror update should only  run at night.

**Comment by zeripath** [comment]
Yes. Just use normal Cron notation.

**Comment by somera** [comment]
hm ... I changed it and restarted Gitea. But ...

![image](https://user-images.githubusercontent.com/8334250/86251998-e9d75e80-bbb2-11ea-8a80-30198ae85d00.png)

Is just the info abou the next cron start wrong?

**Comment by somera** [comment]
> Yes. Just use normal Cron notation.

Can you give me some working example please?! It didn't work for me.

**Comment by lunny** [comment]
We use https://github.com/gogs/cron which is a fork of github.com/robfig/cron and you can find the syntax https://godoc.org/github.com/robfig/cron .

**Comment by somera** [comment]
> We use https://github.com/gogs/cron which is a fork of github.com/robfig/cron and you can find the syntax https://godoc.org/github.com/robfig/cron .

Thy. this is very helpful.
