### ISSUE TITLE
Commit/push error

### ISSUE THREAD

**Issue by obi1** [go-gitea/gitea#12085]
- Gitea version (or commit ref): 1.11.6
- Git version: 2.26.2
- Operating system: Gentoo Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

I haven't been using Gitea for anything but pulls since may, when I had versions <1.11.5. Everything worked fine. In this time I've updated to 1.11.5 and most recently to 1.11.6. Today I wanted to make a push to the server and I was greeted with
`remote: fatal: not a git repository: '.'` After that I've tried to create a new test file directly in the web interface and get the following error: `Failed to update/create file 'test' with error: Clone: exit status 128 - Cloning into bare repository '/var/lib/gitea/data/tmp/local-repo/upload.git927228562'...
fatal: unable to access '/var/lib/gitea/data/tmp/local-repo/upload.git927228562/config': Permission denied
exit status 128 - Cloning into bare repository '/var/lib/gitea/data/tmp/local-repo/upload.git927228562'...
fatal: unable to access '/var/lib/gitea/data/tmp/local-repo/upload.git927228562/config': Permission denied`.
The permissions seem to be in order and even if I set them to 777 I still get the same error.

**Comment by obi1** [comment]
I figured out it's because apparently the new version is forcing me to enable xattr which I had disabled in the kernel. It works if I recompile the kernel with xattr support for my file system. Maybe this could be an optional setting at compile time?

**Comment by lunny** [comment]
Maybe it's a problem of Golang v1.14?
