### ISSUE TITLE
Cannot delete tags

### ISSUE THREAD

**Issue by IzzySoft** [go-gitea/gitea#12081]
- Gitea version (or commit ref): 1.12
- Git version: ?
- Operating system: Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
Once a tag has been pushed, it cannot be removed anymore. Gitea doesn't offer that from the UI (or I didn't find where) – and deleting the tag locally plus using `git push --tags` doesn't remove it either.

Left some of the check-marks open as I'm not sure what Codeberg is running (@lunny probably knows, else @ashimokawa can tell if it's needed).

## Screenshots
cannot screenshot what's not there (oops), sorry.

**Comment by a1012112796** [comment]
you can try ``git push origin --delete tag <tagname>``

**Comment by IzzySoft** [comment]
Thanks, that worked! So this issue should rather be seen as asking for an improvement (adding the posibility to delete a tag via the WebUI, as e.g. Github and IIRC also GitLab have it). Certainly lowers the prio for me, thanks again!

**Comment by a1012112796** [comment]
@IzzySoft How about this solution? Thanks. #12096

**Comment by IzzySoft** [comment]
THAT I'd call a solution – and wow have you been fast with it, thanks a lot! You can set it to close this issue on merge :smiley:
