### ISSUE TITLE
Can't dump gitea on v1.4.0

### ISSUE THREAD

**Issue by jayjiangsamuel** [go-gitea/gitea#12088]
- Gitea version (or commit ref): v1.4.0
- Git version: 2.16.6
- Operating system: CentOS 7 x86_64
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description
Gitea dump file have some error. The command and error message is in Screenshots.
## Screenshots
![IMG_0597](https://user-images.githubusercontent.com/67099584/85986548-06db2880-ba1f-11ea-9cbc-aff7918645d3.JPG)

**Comment by lafriks** [comment]
That's awfully old version. Please do manual backup in this case and update to more recent version
