### ISSUE TITLE
Release text area is not the new Markdown editor as in issues text area

### ISSUE THREAD

**Issue by lapin-b** [go-gitea/gitea#12098]
- Gitea version (or commit ref): 1.12.1
- Git version: 2.20.2
- Operating system: Debian 10 (buster)
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (can't provide URL since it's in creating / editing an issue / release)
  - [ ] No
  - [ ] Not relevant
- Log gist:
*Irrelevant since this issue is about the web UI*

## Description
When writing a draft release on my own Gitea instance, I have noticed the "Releases" text field is not the same as the "Issues" text field, as demonstrated in the screenshots, below. This also applies to editing an existing issue and release.

### Creating a new issue
![Screencapture of the "New Issue" page on the test Gitea instance. The text field is the new, rich one](https://user-images.githubusercontent.com/3647174/86184601-cff73680-bb34-11ea-95be-3b2301b30359.png)

### Creating a new release
![Screencapture of the "New Release" page on the test Gitea instance. The text field is the good ol' one, not a Markdown editor](https://user-images.githubusercontent.com/3647174/86184641-e2717000-bb34-11ea-9dc3-26fade88bd0e.png)

**Comment by luwol03** [comment]
I think its still an issue.

**Comment by danger89** [comment]
Too bad.. I'm also missing the markdown editor, when I edit... Markdown files (md) in the repo.

**Comment by luwol03** [comment]
It's still an issue

**Comment by danger89** [comment]
Still an issue..!

**Comment by wxiaoguang** [comment]
It is now.

![image](https://user-images.githubusercontent.com/2114189/165953275-a8f3af5d-4b57-48f5-8cff-c8a3c68cb52b.png)

**Comment by danger89** [comment]
Nice!
