### ISSUE TITLE
load api swager failed

### ISSUE THREAD

**Issue by a1012112796** [go-gitea/gitea#12106]
- Gitea version (or commit ref): 1.13.0+dev-306-g134bfd3e5 (master lasat commit)
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Screenshots
![image](https://user-images.githubusercontent.com/25342410/86253309-f5447d00-bbe6-11ea-94fa-0b56a95b2541.png)

**Comment by silverwind** [comment]
Does opening `/swagger.v1.json` do anything?

fetch is here: https://github.com/go-gitea/gitea/blob/master/web_src/js/standalone/swagger.js#L6

**Comment by a1012112796** [comment]
Oh, sorry, that's because of the wrong ip config in app.ini. I forgot about it. Thanks.
