### ISSUE TITLE
Notification header text v1.12.1

### ISSUE THREAD

**Issue by givemeurhats** [go-gitea/gitea#12101]
- Gitea version (or commit ref): 1.12.1
- Git version: 2.18.4
- Operating system: centos 8
- Database (use `[x]`):
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:

## Description
After updating from 1.11.5 to 1.12.1 I get the following for notifications:

## Screenshots
![error](https://user-images.githubusercontent.com/24483075/86230653-a6b8c380-bb91-11ea-98e1-e052f7564f90.PNG)

**Comment by lafriks** [comment]
Are you using custom header template?

**Comment by givemeurhats** [comment]
oh right! Forgot about that! :) Thats it! :)
