### ISSUE TITLE
Problems, when open some gitea tabs in Chrome/FF

### ISSUE THREAD

**Issue by somera** [go-gitea/gitea#12110]
- Gitea version (or commit ref): 1.12.1
- Git version: 2.20.1
- Operating system: Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant

## Description

I open often some Gitea tabs in browser. I'm wirking with chrome. But the same problem exists with FF too.

![image](https://user-images.githubusercontent.com/8334250/86264015-42622800-bbc2-11ea-9b55-02b6cf48ca8a.png)

![image](https://user-images.githubusercontent.com/8334250/86264044-4db55380-bbc2-11ea-86ac-b67bc7c9c7e4.png)

Not all tabs will be loaded. When I close the loaded tabs, gitea is sending response. I got the same experience with Ngixx as proxy and without proxy.

And I'm sure, that is worked in Gitea 1.11.x. But I can't go back from 1.12.x to 1.11.x

**Comment by zeripath** [comment]
This is a duplicate with #11978
