### ISSUE TITLE
Startup error

### ISSUE THREAD

**Issue by overpulls** [go-gitea/gitea#1212]
Who is it?

```
./gitea web
2017/03/11 00:48:34 [T] Custom path: /home/gitea/custom
2017/03/11 00:48:34 [T] Log path: /home/gitea/log
2017/03/11 00:48:34 [I] Gitea v
2017/03/11 00:48:34 [I] Log Mode: File(Info)
2017/03/11 00:48:34 [I] Cache Service Enabled
2017/03/11 00:48:34 [I] Session Service Enabled
2017/03/11 00:48:34 [...itea/routers/init.go:53 GlobalInit()] [E] Fail to initialize ORM engine: Error 1045: Access denied for user 'root'@'localhost' (using password: YES)
```

Config path:
gitea/conf/app.ini

    Gitea version (or commit ref): 1.0.1
    Git version: 2.7.4
    Operating system: Ubuntu 16.04
    Database (use [x]):
        MySQL

Is there somewhere else a config? ...
It feels like it does not work :)

**Comment by denji** [comment]
> Access denied for user 'root'@'localhost' (using password: YES)

Incorrect password/account/host-mask

**Comment by overpulls** [comment]
Both the password and the account are correct

**Comment by geek1011** [comment]
Try removing the quotes from the config file, or use backticks instead: `

**Comment by lunny** [comment]
`gitea/conf/app.ini` and `gitea/custom/conf/app.ini`, later will override previous.
