### ISSUE TITLE
OAuth2 access token call /login/oauth/access_token always returns unsupported_grant_type

### ISSUE THREAD

**Issue by shaikhshahidg** [go-gitea/gitea#12126]
- Gitea version (or commit ref): gitea-master-linux-amd64
- Git version:NA
- Operating system: Cent OS
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x ] Not relevant
- Log gist:

## Description
I have been trying accessing to obtain access token for Gitea , I have invoked "**/login/oauth/access_token**" as post API with 
request body as below 
{
	"grant_type": "authorization_code",
	"code": "",
	"redirect_uri": "http://localhost:8080/js/qa/oauth2.jsp",
	"client_id": "",
	"client_secret",""
}
 
Possible options tried for grant_type is "**authorization_code**" & "**refresh_token**" with valid details for code , client_id & client_secret.

for all invocations i get 

"
**_{
    "error": "unsupported_grant_type",
    "error_description": "Only refresh_token or authorization_code grant type is supported"
}_**
"
...

## Screenshots
![image](https://user-images.githubusercontent.com/3368971/86429723-020fc080-bd0e-11ea-9c06-10b3caf903b3.png)
![image](https://user-images.githubusercontent.com/3368971/86429981-b6a9e200-bd0e-11ea-970b-b5fae1b8659b.png)

**Comment by lunny** [comment]
Please take https://gitea.com/lunny/testGiteaOauth2 as an example.
