### ISSUE TITLE
docs: responsive css breaks header layout and disables selection

### ISSUE THREAD

**Issue by piersh-aetheros** [go-gitea/gitea#12132]
this is an issue with the docs, specifically: https://docs.gitea.io/en-us/config-cheat-sheet/

there's a weird issue with the CSS on the docs where setting the window width in a certain range disables selection of text in the docs. there's an anti-goldilocks situation going on...

1. if the window is set *large* enough, the header looks like this and selection in the doc works fine:
![image](https://user-images.githubusercontent.com/66884198/86496631-292cb900-bd33-11ea-8174-95f42bb562f5.png)

2. if the window is set *small* enough, the header looks like this and selection also works fine:
![image](https://user-images.githubusercontent.com/66884198/86496664-45c8f100-bd33-11ea-8c29-94ad14b816b2.png)

3. however... if the window is set at just the right ~~temperature~~ width, then it looks like this and selection in the doc is disabled:
![image](https://user-images.githubusercontent.com/66884198/86496725-714bdb80-bd33-11ea-9113-f4a4eeacb261.png)

**Comment by techknowlogick** [comment]
Thanks for issue, would you be able to open it in the theme repo where this is managed? Found at: https://gitea.com/gitea/theme/
