### ISSUE TITLE
Code change for 'The SSH keys can potentially break, make sure to regenerate the authorized keys'

### ISSUE THREAD

**Issue by Commenter123** [go-gitea/gitea#1213]
Where can I find the commit which fixes this issue in the changelogs "Code change for 'The SSH keys can potentially break, make sure to regenerate the authorized keys"?

**Comment by lunny** [comment]
It's a potentially break. But I think mostly it should work smoothly. You can find the code on this PR https://github.com/go-gitea/gitea/pull/906
