### ISSUE TITLE
commit graph: branches change color page-to-page

### ISSUE THREAD

**Issue by piersh-aetheros** [go-gitea/gitea#12134]
- Gitea version (or commit ref): 1.11.6

when paging through the commit graph, the branches have random colors which makes it difficult to track long-running branches. also, refreshing the page changes the colors randomly. maybe a deterministic coloring scheme should be used?

**Comment by silverwind** [comment]
https://github.com/zenozeng/color-hash could be used. Also, colors should generate with sufficient contrast over the background, which often is not the case.

**Comment by kjellkvinge** [comment]
Good issue. Now that the gitgraph is rewritten (#12137) this will probably be more easy to handle.

**Comment by zeripath** [comment]
Fixed already.
