### ISSUE TITLE
Gitea slow loading pages

### ISSUE THREAD

**Issue by sIspravnikov** [go-gitea/gitea#12140]
- Gitea version (or commit ref):
Gitea version 1.12.1
- Git version:
git version 2.24.3
- Operating system:
Alpine Linux in docker
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description
I have an instance of Gitea with 36 organizations, 286 repositories
This instance is in Azure Cloud, running in kubernetes on node with 2vCPU, 4Gb RAM with no other services running on that node, and via prometheus i can see, that CPU and memory load is in normal conditions. CPU ~10% stable, RAM 700-1000 MB consumed.

Loading some pages is very long, for example:

Sample project page(40000+ commits):
Page: 4949ms Template: 220ms

Pull-requests(with 0 open requests):
Page: 13865ms Template: 553ms

Site administration:
Page: 5878ms Template: 12ms

But main page(Dashboard) seems to load normally(well, it's too long, but compared to others, it's normal)
Page: 854ms Template: 469ms

What i've already tried:

Disabled avatars features:

>    [picture]
      REPOSITORY_AVATAR_FALLBACK=none
      DISABLE_GRAVATAR=true
      ENABLE_FEDERATED_AVATAR=false
      AVATAR_MAX_FILE_SIZE=512000

nothing changed

Enabled caching:

> [cache]
      ENABLED = true
      ADAPTER = memory
      INTERVAL = 60
      ITEM_TTL = 16h
      [cache.last_commit]
      ENABLED = true
      ITEM_TTL = 8760h
      COMMITS_COUNT = 500

With no effect. Based on RAM consume, i can't see if caching really working, walked through some repos with thousand of commits and total size 20+ GB, and i can't see memory consume increase.

Checked PostgreSQL, all queries running fast enough.

Maybe it can be disk speed related thing?
Is there any additional logging, that i can enable, to check, what's going on? Now i'm only can see 

All i can see now is:

> [Macaron] 2020-07-04 21:18:18: Started GET /pulls for 84.17.25.145
[Macaron] 2020-07-04 21:18:19: Started GET /serviceworker.js for 84.17.25.145
[Macaron] [Static] Serving /serviceworker.js
[Macaron] 2020-07-04 21:18:19: Completed GET /serviceworker.js 200 OK in 4.864414ms
[Macaron] 2020-07-04 21:18:20: Started GET /api/internal/serv/command/4/pfr-process-engine/auth-uaa?mode=1&verb=git-upload-pack for 127.0.0.1
[Macaron] 2020-07-04 21:18:20: Completed GET /api/internal/serv/command/4/pfr-process-engine/auth-uaa?mode=1&verb=git-upload-pack 200 OK in 58.186274ms
[Macaron] 2020-07-04 21:18:20: Started POST /api/internal/ssh/4/update/108 for 127.0.0.1
[Macaron] 2020-07-04 21:18:20: Completed POST /api/internal/ssh/4/update/108 200 OK in 23.144469ms
[Macaron] 2020-07-04 21:18:20: Started GET /api/internal/serv/command/4/pfr-process-engine/journal-client?mode=1&verb=git-upload-pack for 127.0.0.1
[Macaron] 2020-07-04 21:18:20: Completed GET /api/internal/serv/command/4/pfr-process-engine/journal-client?mode=1&verb=git-upload-pack 200 OK in 56.74407ms
[Macaron] 2020-07-04 21:18:20: Started POST /api/internal/ssh/4/update/231 for 127.0.0.1
[Macaron] 2020-07-04 21:18:20: Completed POST /api/internal/ssh/4/update/231 200 OK in 20.430062ms
[Macaron] 2020-07-04 21:18:21: Started GET /api/internal/serv/command/4/pfr-process-engine/document-db?mode=1&verb=git-upload-pack for 127.0.0.1
[Macaron] 2020-07-04 21:18:21: Started GET /api/internal/serv/command/4/pfr-process-engine/menu-db?mode=1&verb=git-upload-pack for 127.0.0.1
[Macaron] 2020-07-04 21:18:21: Completed GET /api/internal/serv/command/4/pfr-process-engine/document-db?mode=1&verb=git-upload-pack 200 OK in 66.258699ms
[Macaron] 2020-07-04 21:18:21: Started POST /api/internal/ssh/4/update/162 for 127.0.0.1
[Macaron] 2020-07-04 21:18:21: Completed POST /api/internal/ssh/4/update/162 200 OK in 24.699874ms
[Macaron] 2020-07-04 21:18:21: Started GET /api/internal/serv/command/4/pfr-process-engine/ice-client?mode=1&verb=git-upload-pack for 127.0.0.1
[Macaron] 2020-07-04 21:18:21: Completed GET /api/internal/serv/command/4/pfr-process-engine/ice-client?mode=1&verb=git-upload-pack 200 OK in 82.673748ms
[Macaron] 2020-07-04 21:18:21: Started POST /api/internal/ssh/4/update/214 for 127.0.0.1
[Macaron] 2020-07-04 21:18:21: Completed POST /api/internal/ssh/4/update/214 200 OK in 105.375216ms
[Macaron] 2020-07-04 21:18:22: Completed GET /api/internal/serv/command/4/pfr-process-engine/menu-db?mode=1&verb=git-upload-pack 200 OK in 929.864486ms
[Macaron] 2020-07-04 21:18:22: Started POST /api/internal/ssh/4/update/243 for 127.0.0.1
[Macaron] 2020-07-04 21:18:22: Completed POST /api/internal/ssh/4/update/243 200 OK in 29.385688ms
[Macaron] 2020-07-04 21:18:29: Completed GET /pulls 200 OK in 10.561754948s

...

**Comment by sIspravnikov** [comment]
update: Changed some DB-related settings(idle connects and so on)
Now i have totally slow(8-15 seconds): issues and pull requests, other pages runs fast now. What can be done with issues and PR, i have no idea...

**Comment by lunny** [comment]
The bottleneck of the dashboard page is database speed.

```[cache.last_commit]``` will speed up when second time to visit the homepage of repositories.

**Comment by sIspravnikov** [comment]
Forgot to update. Problem was in database performance, so this issue can be closed.
