### ISSUE TITLE
Can we create publicly access repos while creating repos using git push from command line

### ISSUE THREAD

**Issue by aakash-v-virani** [go-gitea/gitea#12160]
- Gitea version (or commit ref): 1.13.0+dev-234-gd9aa007a9
- Git version: 2.26.2 
- Operating system: ubuntu-18.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ x] Not relevant
- Log gist:

## Description
After enabling **ENABLE_PUSH_CREATE_USER** option in app.ini, I am able to create repo using git push but it is always created as private repo. 
_I am awear that i am update repository visibility using UI after repo creation but is there a way where i can create publicly access repos from command line itself ?_
...

**Comment by a1012112796** [comment]
Maybe we can add "push options" features like gitlab(https://docs.gitlab.com/ee/user/project/push_options.html),
Then we can get user choices about new repo from it.
