### ISSUE TITLE
the review comment on a pr is always in pending status

### ISSUE THREAD

**Issue by bigwhite** [go-gitea/gitea#12165]
- Gitea version (or commit ref): Gitea version 1.12.1 built with GNU Make 4.1, go1.14.4 : bindata, sqlite, sqlite_unlock_notify
- Git version: git version 2.20.1 (Apple Git-117)
- Operating system: macos
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

the review comment on a pr is always in pending status. and after update the pr, these comments all disappeard.

bs. the try.gitea.io is accessed too slow . I did not try to reproduce in this site.

## Screenshots

![image](https://user-images.githubusercontent.com/419088/86584868-242c6b80-bfb8-11ea-9de9-4f1de484cf22.png)

**Comment by bigwhite** [comment]
i am sure the database is running ok.

**Comment by a1012112796** [comment]
hello, I think you should submit your review after add comments.

**Comment by zeripath** [comment]
This is a common problem -  I think this UI is poor (although it essentially replicates GHs behaviour).

@bigwhite you need to click the Review button in the top right and press one of approve, comment, request changes.

**Comment by bigwhite** [comment]
> This is a common problem - I think this UI is poor (although it essentially replicates GHs behaviour).
> 
> @bigwhite you need to click the Review button in the top right and press one of approve, comment, request changes.

@zeripath got it , thank you
