### ISSUE TITLE
Emoticon in pull request comment 500 error

### ISSUE THREAD

**Issue by stu1811** [go-gitea/gitea#12178]
I've tried adding multiple different emoticons in pull request comments and approval and I always get a 500 error. This worked in the 1.11.5.. We skipped from 1.11.5 to 1.12.1. Did not try 1.12.0 or later 1.11.x versions.

- Gitea version (or commit ref): 1.12.1 with go 1.14.4
- Git version: 2.16.5
- Operating system: Server running gitea service is RHEL 7.2. Client is CentOS 7.7.
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X ] No
  - [ ] Not relevant

**Comment by zeripath** [comment]
This is likely to be yet another MySQL issue with character encodings.

On MySQL we require utf8mb4 as the character encoding. There is a command called `gitea convert` that should set this for you.

**Comment by lunny** [comment]
@zeripath But he said 1.11.5 is work

**Comment by stu1811** [comment]
```
gitea convert -c /etc/gitea/app.ini
Converted successfully, please confirm your database's character set is now utf8mb4
```

```
MySQL>select SCHEMA_NAME 'database', default_character_set_name 'charset', DEFAULT_COLLATION_NAME 'collation' from information_schema.SCHEMATA;
database | charset|collation
giteadb|utf8mb4|utf8mb4_general_ci
```

Emoticons still do not work

**Comment by lunny** [comment]
You should also change your `app.ini` CHARSET item on DATABASE section.

**Comment by stu1811** [comment]
Setting CHARSET in DATABASE fixed it. Was UTF8 previously. Thanks!

**Comment by apiraino** [comment]
The fix works for us too, we have gitea installed using a docker container on an existing DB and didnt pay attention to the documentation :-)

https://docs.gitea.io/en-us/database-prep/#mysql
