### ISSUE TITLE
Git to Gitea migration

### ISSUE THREAD

**Issue by kinos9** [go-gitea/gitea#12177]
- Gitea version (or commit ref): 1.12.1
- Git version: 2.7.4
- Operating system: Ubuntu 16.04 Server
- Database:
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant

## Description

I actually have a git server (git version 2.7.4) with some repositories. They are maintained under `git` user.
Now I have installed gitea (with dedicated `gitea` user) I would like to access to existent repositories for example linking the directory where they are stored now: `/home/gitea/gitea-repositories/kinos -> /srv/git` (this is the first thing that I thought).
Is this possible?

Thx,
K

**Comment by lunny** [comment]
It will not work. Gitea will save repository information on database for display them on web UI.

**Comment by kinos9** [comment]
> It will not work. Gitea will save repository information on database for display them on web UI.

Ok, thanks. And is it possible to exclusively import an existent repository to gitea, forcing gitea to regenerate db information?

Thx

**Comment by lunny** [comment]
You can do that via `git push`. and if you enabled `automatically create repository when push`. It will become more easy.

**Comment by kinos9** [comment]
> You can do that via `git push`. and if you enabled `automatically create repository when push`. It will become more easy.

Ah ok, so I have to change remote and push all the repository content, re-creating a new git repo, and is not possible to directly move the server-side content?
