### ISSUE TITLE
Paste image (via CTRL+V) not working when adding review comment

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#12183]
- Gitea version (or commit ref):
- Git version: 1.12.0
- Operating system: Windows
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes: https://try.gitea.io/Luke2/Repo2/pulls/1/files
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

Leaving an image using CTRL+V does not work here:
![image](https://user-images.githubusercontent.com/2737900/86884013-39f27b80-c0f3-11ea-9dff-a2b881f54d0c.png)

**Comment by a1012112796** [comment]
Sadly Code comment and review do not support attachment now.

**Comment by LukeOwlclaw** [comment]
@a1012112796 Please do not be rude. I could say: There is no "Code comment" anywhere in my post. But I don't because that it rude. Thanks.

**Comment by lafriks** [comment]
Should be fixed by #29220, please reopen if not working
