### ISSUE TITLE
Can you provide an example of the "Profile URL" interface?

### ISSUE THREAD

**Issue by liergou99** [go-gitea/gitea#12197]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

In the <oauth2-provider> of the official document, only the "Authorization Endpoint" and "Access Token Endpoint" are described, and there is no information about the "Profile URL". I want to know the return data format information of this "Profile URL".
https://docs.gitea.io/en-us/oauth2-provider/

**Comment by wxiaoguang** [comment]
No such `Profile URL`, only:

OpenID Connect UserInfo | /login/oauth/userinfo
-- | --
