### ISSUE TITLE
Upload does not work

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#12199]
- Gitea version (or commit ref): 1.13.0+dev-294-ga6168fa25
- Git version: N/A (https://gitea.com doesn't provide this info)
- Operating system: N/A (https://gitea.com doesn't provide this info)
- Database (use `[x]`): N/A (https://gitea.com doesn't provide this info)
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io: Not relevant (https://gitea.com uses the same version as the test one)
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist: N/A (https://gitea.com doesn't provide this info)

## Description

Attempting to upload file(s) to a repo from the web UI is impossible, neither clicking nor dragging'n'dropping does anything.

## Screenshots

I think a video demonstration of the issue would be better than a screenshot, so I posted it on YouTube (non-public): https://youtu.be/govPaKxUewk

**Comment by lunny** [comment]
I cannot reproduce this on macOS + firefox 78.0.1. It seems you are using windows? What's your OS version and what's your web browser version?

**Comment by BlackWinnerYoshi** [comment]
Yes, I am using Windows. Windows 7 64-bit, to be exact. I used Firefox 78.0.1 in that video, but I also managed to reproduce this issue on ungoogled-chromium 80.0.3987.132 (both browsers use 64-bit).

**Comment by silverwind** [comment]
Anything in the browser console? (F12)

**Comment by BlackWinnerYoshi** [comment]
This is weird, it looks like the issue went away. _Is this one of those bugs that randomly pop in and pop out? Ugh._ Unfortunately, I didn't check the browser console when the issue was still here.

**Comment by silverwind** [comment]
Did the server update recently? We sometimes get reports of UI bugs right after update and I think they are related to serviceworker. Those bugs usually go away 24h after the service worker refreshes.

**Comment by BlackWinnerYoshi** [comment]
I don't remember, and all of the past, archived versions of https://gitea.com that I checked are too far apart from the current version (`1.13.0+dev-294-ga6168fa25`, compared to [`1.12.0+dev-142-g9b7737df2`](https://web.archive.org/web/20200423041233/https://gitea.com)

**Comment by lunny** [comment]
@BlackWinnerYoshi I upgrade gitea.com to 1.13.0+dev-294-ga6168fa25 yesterday, maybe it's upgrading when you visit it?

**Comment by BlackWinnerYoshi** [comment]
I guess it's the only way, uploading files to a repository just doesn't break and unbreaks when it wants to.
