### ISSUE TITLE
Support OKTA and KeyCloak as OAuth2 Server

### ISSUE THREAD

**Issue by andyzhaozhao** [go-gitea/gitea#12198]
Can Gitee Support OkTA or KeyCLoak as OAuth2 Server ?

**Comment by veita** [comment]
We run Gitea with authentication via Keycloak at our company.

**Comment by Hokwang** [comment]
@veita can you tell how to do that?

**Comment by veita** [comment]
> @veita can you tell how to do that?

I don't know how they've done it, but I guess they've just added Keycloak as an OpenID Connect authentication source in the web configuration page of Gitea.
