### ISSUE TITLE
Delphi/Pascal files identified as GDB files

### ISSUE THREAD

**Issue by knippers** [go-gitea/gitea#12206]
## Description

Delphi pascal files (forms and the code) are identified as GDB files and not Pascal. The samples folder for linguist does contain valid exampled: https://github.com/github/linguist/tree/master/samples/Pascal.

From what I have read the language statistics code is based on go-enry which seems to have looked at linquist. 

## Screenshots

![image](https://user-images.githubusercontent.com/69477/87170296-711e8380-c2d1-11ea-82d0-e77cf8c2e412.png)

**Comment by CirnoT** [comment]
You'll have to report your issue to upstream on https://github.com/github/linguist and then to https://github.com/go-enry/go-enry for syncing changes from Linguist.

After you confirm locally that Linguist and go-enry properly see code snippets you can open PR here to update go-enry version we use.

**Comment by delvh** [comment]
Does your problem still occur or was it fixed upstream?
Either way, that's not really something Gitea can fix.
