### ISSUE TITLE
Request: Disable certain merge strategies in pull requests

### ISSUE THREAD

**Issue by lumio** [go-gitea/gitea#12208]
- Gitea version (or commit ref): 1.13.0+dev-242-g0b1bb9644 built with GNU Make 4.3, go1.14.4 : bindata, sqlite, sqlite_unlock_notify (latest docker container)
- Git version: 2.26.2
- Operating system: (latest docker container)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

It is great to be able to chose the merge strategy for a pull request, similar like GitHub.
However, it would be great to be able to disable certain merge strategies all together. We enforce commit signatures  and allowing a PR to be squashed would also more or less remove those signatures, leaving one single commit with the default key.

I thought of new options for `[repository.pull-request]` like the following:

- `DISABLE_STRATEGY_REBASE`
- `DISABLE_STRATEGY_REBASE_NO_FF`
- `DISABLE_STRATEGY_SQUASH`
- `DISABLE_STRATEGY_RECURSIVE` (default merge strategy - could be left out in my opinion)

**Comment by jolheiser** [comment]
This is already available through repository settings.

**Comment by lumio** [comment]
Ah I was looking on the wrong section. I thought I would find it in the `Branch` section. Thank you
