### ISSUE TITLE
Block non-signed commits per-repo or per-instance

### ISSUE THREAD

**Issue by benyanke** [go-gitea/gitea#12204]
Feature request: my team has begun using signed commits for some projects. It would be useful to have a checkbox in the repo to reject non-signed commits to enforce this server side, perhaps with a less strict (only users with a key in their profile have this checked) and more strict mode (any commit must be signed).

**Comment by jolheiser** [comment]
Do you mean #9708? That PR should be included in `1.12.x`

**Comment by benyanke** [comment]
Yup, that's basically what I had in mind. 

Good work as always!
