### ISSUE TITLE
Installer fails to create directory when using docker

### ISSUE THREAD

**Issue by evilstiefel** [go-gitea/gitea#1221]
- Gitea version (or commit ref): 1.1.0+3-gfac75b80
- Git version: 2.8.3
- Operating system: Linux Xubuntu 4.4.0-66-generic #87-Ubuntu
- Database (use `[x]`):
  - [x ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x ] No
  - [ ] Not relevant
- Log gist:

## Description
When using the **docker image**, the folder /data is owned by root (if using regular containers). Installing gitea now enables you to choose a folder for lfs, but if you input something like /data/lfs, the installation will fail with the following:

`invalid_lfs_path%!(EXTRA *os.PathError=mkdir /data/lfs: permission denied)`

Choosing one of the pre-existing directories and adding a subdirectory is fine (like /data/git/lfs), but it is unclear if that is advisable. Since the installer doesn't run as root, it can't create directories under /data. Maybe this can be fixed or clarified?

To solve this problem locally, I used created the directory /data/lfs and chown'd it to the user git manually and ran the installation.
## Screenshots

![Screenshot of the installer error](https://cloud.githubusercontent.com/assets/8029370/23822879/3fc303b4-0656-11e7-8561-9b3ef74d23d0.png)

**Comment by lunny** [comment]
You can specify any directory `git` has permissions.

**Comment by evilstiefel** [comment]
Sure, but the user doesn't know that /data isn't owned by git in a docker-environment and it might be inappropriate to just add another subfolder to /data/git oder /data/gitea.

**Comment by ghost** [comment]
Why isn't there just an LFS directory by default? Enabling LFS doesn't do anything for people who don't use it, and it would no longer require the user to change this setting and possibly create a directory just to enable it.

**Comment by sapk** [comment]
This could maybe fix simply fixed  by adding "/data/lfs" to https://github.com/go-gitea/gitea/blob/master/docker/usr/bin/entrypoint#L3 and https://github.com/go-gitea/gitea/blob/master/docker/etc/s6/gitea/setup#L18 ? I can't test it right now but this should work.

**Comment by ghost** [comment]
@sapk sounds like a splendid idea! However, the startup wizard should also be changed to have "/data/lfs" as a default path instead of an empty text field as of right now. Then people could simply launch with default settings and LFS would work out-of-the-box

**Comment by lunny** [comment]
This seems be fixed some time and please feel free to reopen it.

**Comment by m-a-v** [comment]
@lunny It doesn't work with version v1.7.1. I think the solution from @sapk and @JonasT would be the best. In my point of view it makes sense to put lfs in a separate directory (/data/lfs).
