### ISSUE TITLE
Can't migrate 8,8GB project

### ISSUE THREAD

**Issue by somera** [go-gitea/gitea#12225]
- Gitea version (or commit ref): 1.12.2
- Git version: 2.25.1
- Operating system: Linux nuc-mini-server 5.4.0-40-generic #44-Ubuntu SMP Tue Jun 23 00:01:04 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant

I try mirror huge project in Gitea.

https://github.com/0ad/0ad

Localy on the machine, where Gitea is installed it needs ~15 minutes:

```
mini-server:/data-files/tmp$ date ; git clone https://github.com/0ad/0ad.git ; date
**So 12. Jul 19:43:50 CEST 2020**
Cloning into '0ad'...
remote: Enumerating objects: 41, done.
remote: Counting objects: 100% (41/41), done.
remote: Compressing objects: 100% (36/36), done.
remote: Total 463029 (delta 7), reused 17 (delta 5), pack-reused 462988
Receiving objects: 100% (463029/463029), 4.39 GiB | 5.46 MiB/s, done.
Resolving deltas: 100% (357807/357807), done.
Updating files: 100% (33849/33849), done.
**So 12. Jul 19:58:03 CEST 2020**
```

My git timeouts are set to

```
; Operation timeout in seconds
[git.timeout]
DEFAULT = 360
MIGRATE = 600
MIRROR = 1200
CLONE = 1200
PULL = 300
GC = 240
```

Why it's now working?

**Comment by somera** [comment]
Ist there any solution to do this?

**Comment by lunny** [comment]
gitea clone is not a plain clone, it will clone all the branches, so it may spend more time than your command line.

**Comment by somera** [comment]
> gitea clone is not a plain clone, it will clone all the branches, so it may spend more time than your command line.

Time is not the problem for me. ;)

But it's not working when I increase the timeout settings. The proces is brocken earlier. Is there other internal timeout?

**Comment by lunny** [comment]
So there should be another context to cancel the process.

**Comment by somera** [comment]
> So there should be another context to cancel the process.

Means I can't mirror it?

**Comment by somera** [comment]
@lunny and will ir be possible to mirror project like this?

**Comment by 6543** [comment]
This is some configuration issue i think.

it woks for me:
 * https://code.obermui.de/test/0ad_migrate
 * https://code.obermui.de/test/0ad_mirror

git config:
```
Migration Timeout                6000 seconds
Mirror Update Timeout         3000 seconds
Clone Operation Timeout    3000 seconds
Pull Operation Timeout        3000 seconds
GC Operation Timeout          600 seconds
```

if you need help with configuration pleace ask for help on your discord server ;)

**Comment by somera** [comment]
> This is some configuration issue i think.
> 
> it woks for me:
> 
> * https://code.obermui.de/test/0ad_migrate
> * https://code.obermui.de/test/0ad_mirror
> 
> git config:
> 
> ```
> Migration Timeout                6000 seconds
> Mirror Update Timeout         3000 seconds
> Clone Operation Timeout    3000 seconds
> Pull Operation Timeout        3000 seconds
> GC Operation Timeout          600 seconds
> ```
> 
> if you need help with configuration pleace ask for help on your discord server ;)

Works for me too!
