### ISSUE TITLE
Generic User/Repo Settings system

### ISSUE THREAD

**Issue by zeripath** [go-gitea/gitea#12227]
- Gitea version (or commit ref): 1.13

## Description

There are a number of places where we allow systems, repositories and users to have different default settings.

For example, User.Avatar, Repository.Description, Repository.Website, Repository.Topics, User.DiffStyle, User.Theme, User.Language, User.Website, User.Description.

And a number of places where we might want to allow differing settings, e.g. in the ini sections: [repository.editor], [repository.pull-request], some values of [repository.upload], [repository.issue], [repository.signing], some values in [markdown], potentially wanting to further restrict values in [attachment]

At present our schema has to change every time we want to add another setting - and every time we want to just grab a User or Repository we're potentially loading lots of unnecessary data. 

I propose we instead provide a generic Settings table:

```go
type Settings struct {
  UserID int64
  RepoID int64
  Name string
  Value []byte
}
```

We can add an ini section say, `[repository.settings]` and `[user.settings]` which could have settings like:

```ini
[user.settings]
default.diffstyle=...
overridable.diffstyle=true/false
``` 

and so on...

We could then allow per user per repository settings and provide options for relaxing or locking down variables as necessary.

**Comment by silverwind** [comment]
Kind of unrelated but some settings like theme doesn't even need to be stored on the server and can be client-only in Browser's `localStorage`. For example if a user prefers dark theme on one device but light on another.

**Comment by zeripath** [comment]
No it's exactly related - diffstyle probably should also be stored in localstorage too

**Comment by silverwind** [comment]
language might also be a candidate for localStorage.

**Comment by lunny** [comment]
The database struct is not a problem. But how to change them and when to load them is. And you have to consider the situation when there are serval gitea instance in one system.

If we always load the setting from database per page, the preformance is not prefect.

We could save these settings on database or etcd/redis per how the instances install. For a small instance, every time load them from database is enough and no extra service. for a bigger instance, save them to etcd/redis will get better performance.

**Comment by silverwind** [comment]
If it's only one query and it's sufficiently optimized, shouldn't performance be pretty similar to pulling it from a key/value store?
