### ISSUE TITLE
Octicons are missing for dashboard repolist

### ISSUE THREAD

**Issue by CirnoT** [go-gitea/gitea#12226]
- Gitea version (or commit ref): bac57ab5900672357fb0a36f9433e516088bd21b
- Git version: `gitea:latest`
- Operating system: `gitea:latest`
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant

## Description

https://github.com/go-gitea/gitea/pull/12157 introduced direct SVG rendering however no appropriate changes were made to dashboard repolist https://github.com/go-gitea/gitea/blob/bac57ab5900672357fb0a36f9433e516088bd21b/templates/user/dashboard/repolist.tmpl#L64

**Comment by silverwind** [comment]
There's more:

https://github.com/go-gitea/gitea/blob/bac57ab5900672357fb0a36f9433e516088bd21b/templates/user/dashboard/repolist.tmpl#L106

A template language inside another template language. I don't think it's such a great idea.

**Comment by silverwind** [comment]
I really wonder why there is even vue templates mixed in the go templates using pseudo-global JS functions. Those should be standalone `.vue` files.
