### ISSUE TITLE
try.gitea.io is not sending emails ?

### ISSUE THREAD

**Issue by strk** [go-gitea/gitea#1223]
I've tried using the `forgot password` feature on try.gitea.io but haven't received any email, nor the system told me about the service being disabled. Is it supposed to work ? Can you check why it isn't working ?
My username is `strkhub`, created by logging in via GitHub

**Comment by strk** [comment]
Note that I get a message like this: `A new confirmation email has been sent to xxx@xxx. Please check your inbox within the next 3 hours to complete the registration process.` so everything makes me think it's supposed to work. Will wait these 3 hours and report you back if I still don't get the mail.

**Comment by strk** [comment]
\cc @tboerger

**Comment by strk** [comment]
3 hours are gone (4, at this time) but I hadn't received any mail yet.
@go-gitea/owners can you take a look at the logs (according to @tboerger on Gitter, the server is configured to send those mails)

**Comment by techknowlogick** [comment]
As try.gitea.io sends emails now, can this be closed?
