### ISSUE TITLE
Change font back to Lato?

### ISSUE THREAD

**Issue by andreymal** [go-gitea/gitea#12236]
Related to #9801

Lato 2 supports 4551 characters — 1.7x more than Roboto! The current version of Roboto used by Gitea supports only 2688 characters.

And Roboto looks awful :(

<img src="https://i.imgur.com/Op1riIU.png" width="400" height="360" />

**Comment by silverwind** [comment]
Actually we've removed Roboto in 1.13 so it's only system-native fonts now and I don't see us going back to webfonts. You can of course add a custom CSS file/template to your installation that changes the font to your liking.

**Comment by andreymal** [comment]
@silverwind ok I left comment there https://github.com/go-gitea/gitea/issues/11818#issuecomment-657661674

**Comment by andreymal** [comment]
If the main goal is to support "many more language glyphs", then "system-native" fonts may be a better choice, so okay
