### ISSUE TITLE
Problem with formatting some phrases only for the Russian language. Other languages is OK.

### ISSUE THREAD

**Issue by small75** [go-gitea/gitea#12237]
- Gitea version (or commit ref): from 1.12.x (current 1.12.2)
- Git version: 2.20.1
- Operating system: Debian 9.1
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
https://try.gitea.io/Small75/my/issues?q=&type=all&sort=&state=closed&labels=&milestone=0&assignee=0
previous set language in settings page: русский(russian)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
Problem with formatting some phrases only for the Russian language. Other languages is OK.
**I have this:**
![image](https://user-images.githubusercontent.com/37901315/87312633-7d048280-c529-11ea-8f7b-ec1961724652.png)

**instead this:**
![image](https://user-images.githubusercontent.com/37901315/87312765-aae9c700-c529-11ea-9644-5a9c7460a2d9.png)

**in crowdin.com it's OK**
![image](https://user-images.githubusercontent.com/37901315/87313181-2cd9f000-c52a-11ea-9017-e31322adcae2.png)

**Comment by small75** [comment]
In meged pull https://try.gitea.io/Small75/my/pulls/2
![image](https://user-images.githubusercontent.com/37901315/87314706-4bd98180-c52c-11ea-9e46-307bc5911b91.png)

**Comment by zeripath** [comment]
Crowdin is not correct:

```
... %[3]c ...
```

Should be `%[3]s`

**Comment by zeripath** [comment]
I've fixed 19 strings on crowdin and used my approving powers to reapprove the fixed strings.

**Comment by small75** [comment]
thanks
