### ISSUE TITLE
Diff syntax highlighting HTML spilling into content

### ISSUE THREAD

**Issue by silverwind** [go-gitea/gitea#12235]
https://try.gitea.io/silverwind/updates/commit/9f342114d7a6bb087ff777a983d0e03b41873b07
https://github.com/silverwind/updates/commit/9f342114d7a6bb087ff777a983d0e03b41873b07

On Line 88 of `test.js` the parts `nx">` and `k">` related to syntax highlighting markup should not be visible. Source HTML:

````html
<span class="<span class=" removed-code"="">nx"&gt;resultValue</span>
````
````html
<span class="<span class=" added-code"="">k"&gt;typeof</span>
````

cc: @mrsdizzie

**Comment by mrsdizzie** [comment]
Good catch, this is side effect from #12205

Made a PR that should fix this if you could please test
