### ISSUE TITLE
Archiving a repo pushes it above active repos

### ISSUE THREAD

**Issue by the1ts** [go-gitea/gitea#12246]
- Gitea version (or commit ref): 1.13.0+dev-307-g633f52c22
- Git version: 2.20.1
- Operating system: Linux
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL) https://try.gitea.io/the1ts
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
I have just archived a large number of repos in a project. Rather confusingly this adds the archived tag to the repo which is great and expected, but changes the updated time and moves the repo above the current active repos which to my mind is confusing at best.

In my mind the archive process should not change the updated time on the repo since I now have archived repos at the top of the project repos list. If this is not possible, could repos be sorted by active or archived then time within those categories, this would put archived repos be below those that are still active?

This I think is more a UX issue since archiving means the user has said this repo is no longer important, but we appear to push it up the list of repos which does the opposite and makes it look more important.

I have not changed the sort from the default "recently updated"
...

## Screenshots
From try.gitea.io, archive_test1 moved above archive_test2 after I archived it since the archive process touched the changed time.
![image](https://user-images.githubusercontent.com/84956/87441489-0d56cc00-c5eb-11ea-99de-a148881cfa29.png)

**Comment by lunny** [comment]
We just need add `NoAutoTime().` when we update the `is_archive` column. Then `updated` will not be updated.
