### ISSUE TITLE
Cannot update existing repo after upgrade to v1.1

### ISSUE THREAD

**Issue by tullo** [go-gitea/gitea#1224]
Just updated to 1.1 and tried to update a wiki page through the browser for a quick test. That failed!

Then I cloned the wiki repo to my laptop, updated the wiki page. Pushing the change to server failed! Se error log below.

The Release Notes say: "The SSH keys can potentially break, make sure to regenerate the authorized keys" so I run the command through the Admin Panel.
Also removed my public ssh key from the user and added it again.

What else can I do? I am still not able to update the existing wiki / repo

OTOH creating a NEW repo and updating that works!

-----------------------
git push -v
Pushing to ssh://git@code.myserver.net:10022/anda/devtools.wiki.git
Counting objects: 3, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 307 bytes | 0 bytes/s, done.
Total 3 (delta 2), reused 0 (delta 0)
remote: No help topic for 'update'
remote: error: hook declined to update refs/heads/master
To ssh://git@code.myserver.net:10022/anda/devtools.wiki.git
 ! [remote rejected] master -> master (hook declined)

-----------------------
- Gitea version (or commit ref): docker pull gitea/gitea:1.1
- Git version: 2.8.3
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

...

## Screenshots

**If this issue involves the Web Interface, please include a screenshot**

**Comment by strk** [comment]
Anything interesting in the server logs ?
Make sure to raise log level to Trace.

**Comment by lunny** [comment]
I think I know what's happened. I will send a PR to fix this.

**Comment by lunny** [comment]
@tullo, you can resolve this on your Admin Panel, execute `Resync pre-receive, update and post-receive hooks of all repositories.` will resolve your problem.

**Comment by tullo** [comment]
@lunny tried that, but did not help unfortunately

**Comment by mmozeiko** [comment]
I see same error happening for my wiki pages after upgrade to 1.1.0. But I can push to repositories. Only editing wiki pages makes server show http 500 error page.

Log shows:

    2017/03/13 08:09:35 [...routers/repo/wiki.go:487 EditWikiPost()] [E] EditWikiPage: Push: exit status 1 - remote: No help topic for 'update'
    remote: error: hook declined to update refs/heads/master
    To /var/lib/gitea/git/USER/REPO.wiki.git
     ! [remote rejected] master -> master (hook declined)
    error: failed to push some refs to '/var/lib/gitea/git/USER/REPO.wiki.git'

**Comment by lunny** [comment]
@mmozeiko are you sure `Resync pre-receive, update and post-receive hooks of all repositories.` can not resolve this?

**Comment by mmozeiko** [comment]
Yes, tried running running resync hooks, nothing changed.

Now I've noticed that `hooks/update` file is different for newly created repository wiki.
I copied this newly created update file to all  the old repositories (only wiki page repos) and now editing works for me!

**Comment by lunny** [comment]
@mmozeiko Yes. manually do that will let you work. But it's strange why the `Resync pre-receive, update and post-receive hooks of all repositories.` didn't work.

**Comment by lunny** [comment]
@tullo #1227 should fix this issue
