### ISSUE TITLE
Using Firefox - Page fails to load when press edit.

### ISSUE THREAD

**Issue by mcuix** [go-gitea/gitea#12257]
- Gitea version (or commit ref): 1.12.2
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x ] Not relevant
- Log gist:

## Description
Using Firefox - Page fails to load when press edit.
Using Chrome - Very slow render of page when trying to edit page.

**Comment by lunny** [comment]
It should be caused by new code editor which will load gzipped 872.88 KB (original 3.71 MB) static files from the server when you first visit the website. But it should be cached after that. When you second visit the site, it should be faster.

**Comment by mcuix** [comment]
> It should be caused by new code editor which will load gzipped 872.88 KB (original 3.71 MB) static files from the server when you first visit the website. But it should be cached after that. When you second visit the site, it should be faster.

This seems to fix the issue.
