### ISSUE TITLE
Microsoft Teams on-multiple-commit message hard to read

### ISSUE THREAD

**Issue by vijfhoek** [go-gitea/gitea#12255]
- Gitea version (or commit ref): 1.12.2
- Git version: (don't think that's relevant)
- Operating system: Linux
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant

## Description

Currently, the message that's sent when multiple commits puts all commits on a single line, while showing everything in a multi-line commit. This makes them rather hard to read.

May I suggest changing the messages to add a newlines after every commit, and only showing the first line of each commit to reduce noise. If users want to read the rest of the commit, they can just click "View in Gitea".

## Screenshots
<details>
<summary>Current situation:</summary>

![image](https://user-images.githubusercontent.com/345785/87597158-9a844880-c6f1-11ea-8f2a-73e7fc7b47bf.png)

![image](https://user-images.githubusercontent.com/345785/87596409-5775a580-c6f0-11ea-87b2-85a335f32e32.png)
</details>

<details>
<summary>Suggestion:</summary>

![image](https://user-images.githubusercontent.com/345785/87597254-c69fc980-c6f1-11ea-88ed-9498f9b0dbfb.png)

![image](https://user-images.githubusercontent.com/345785/87596926-38c3de80-c6f1-11ea-948c-4cb18d08cef9.png)
</details>

**Comment by zeripath** [comment]
This would likely be a very easy pr

**Comment by sijmn** [comment]
I have in fact already fixed this, but haven't been able to test it yet (it's kind of bothersome to set everything up for testing).

I can try to set up a test env sometime this week
