### ISSUE TITLE
Pull request labels link to issue links

### ISSUE THREAD

**Issue by MGChecker** [go-gitea/gitea#12254]
- Gitea version (or commit ref): 1.12.2
- Operating system: Debian Buster

## Description

If you visit a pull request and click at one of the labels, you get to a list of issues with this label. You would expect getting to a list of PRs instead.

**Comment by MGChecker** [comment]
For some reason, I am not able to activate PRs at try.gitea.io .

**Comment by jolheiser** [comment]
I can confirm for you, going to https://try.gitea.io/jolheiser/ciw/pulls/22 and clicking the label will indeed take you to the issues page, filtering for that label. 🙂
