### ISSUE TITLE
No CSS or JS files running on windows

### ISSUE THREAD

**Issue by michaelalpine** [go-gitea/gitea#12265]
Hi, I'm trying to run this on windows via this tutorial

https://drizin.io/installing-gitea-git-server-developed-in-go-in-windows/

I get the site up and running just fine, but it's getting a 404 when it tries to find the index.css. Here is what it looks like

https://i.imgur.com/cBsayKw.png

And here is my console. 

https://i.imgur.com/0Nt0GEo.png

I can't get it configured because the checkboxes won't show up. What am I missing here?

**Comment by techknowlogick** [comment]
That blog post is out of date. You have a few options,
1. download a pre-compiled version: https://dl.gitea.io/gitea/1.12.2
2. use a package managed version: https://chocolatey.org/packages/gitea
3. use nodejs and build the js/css your self (here are directions on how to build from source)
