### ISSUE TITLE
After migrating to 1.1.0 every push has a remote hook-related error

### ISSUE THREAD

**Issue by milanaleksic** [go-gitea/gitea#1226]
- Gitea version (or commit ref): 1.1.0
- Git version: 2.1.4
- Operating system: linux arm
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:
```
milan@phobos ~/SourceCode/chef-repo → g p
Counting objects: 6, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (5/5), done.
Writing objects: 100% (6/6), 1.08 KiB | 0 bytes/s, done.
Total 6 (delta 4), reused 0 (delta 0)
remote: ls: cannot access <REPOLOCATION>chef-repo.git/hooks/pre-receive.d/pre-receive.d: No such file or directory
remote: ls: cannot access <REPOLOCATION>chef-repo.git/hooks/post-receive.d/post-receive.d: No such file or directory
To <GITSERVER>/milanaleksic/chef-repo.git
   f5c53b8..efd304e  master -> master
```
## Description

After the installation of the new version (1.0.1 -> 1.1.0) has been completed I seem to have the issue as explained above.

Is this a migration went bad? If so, may I just update in postgre the version to some other value and hope this to be fixed automatically? If not, can you give me a fix please?

This is not critical since push ends up being in the repository, but very annoying

**Comment by lunny** [comment]
This is a warning and will not let your push failed. This may because you have executed the migrations twice. You can edit this repo's hooks on settings and let `pre-receive` and `post-receive` blank. then it should resolved your problem.

**Comment by milanaleksic** [comment]
I have fixed this locally using:

```bash
find -type f -wholename '*pre-receive.d/pre-receive' | xargs -I{} sudo rm {}
find -type f -wholename '*post-receive.d/post-receive' | xargs -I{} sudo rm {}
```

I don't get warnings/errors any more, but is this a correct solution? All pre-receive.d and post-receive.d folders had similar files, like this:

```
#!/usr/bin/env bash
ORI_DIR=`pwd`
SHELL_FOLDER=$(cd "$(dirname "$0")";pwd)
cd "$ORI_DIR"
for i in `ls "$SHELL_FOLDER/post-receive.d"`; do
    sh "$SHELL_FOLDER/post-receive.d/$i"
done
```

It seems to me that only `gitea` should've been copied into the subfolder, not also this wrapper script hook.

And yes, because of issue https://github.com/go-gitea/gitea/issues/1225 it might be multiple startups caused multiple migration runs, although I don't have that proof.

In theory, if migrations were made idempotent this couldn't happen

**Comment by lunny** [comment]
You did the right things!  #1225 is another problem.
