### ISSUE TITLE
Codecov doesn't seem to be working properly

### ISSUE THREAD

**Issue by a1012112796** [go-gitea/gitea#12262]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

As title, can't get coverage report for recently commits on codecov, maybe have some bug. 
example link:
https://codecov.io/gh/go-gitea/gitea/commit/3cfd04feca7f0e3dba1281dfa4c1f8905d59e054
view:
![image](https://user-images.githubusercontent.com/25342410/87686247-dcc38d80-c7b6-11ea-8c82-50ed454c5ef0.png)

https://codecov.io/gh/go-gitea/gitea/commits?page=71

![image](https://user-images.githubusercontent.com/25342410/87687017-cff36980-c7b7-11ea-93e2-a7af4f111530.png)

https://github.com/go-gitea/gitea/pull/12261#issuecomment-659483724

**Comment by HarvsG** [comment]
I am the author of #12261 - I initially created the pull request and then, very soon after, converted it to a draft. Perhaps that is the cause?

**Comment by a1012112796** [comment]
I have sent a issue to codecov, 
https://community.codecov.io/t/need-help-look-forward-help-about-a-transform-issue-in-gitea-repo/1848

@lunny @lafriks @techknowlogick Please have a look, Thanks.

**Comment by techknowlogick** [comment]
could be related to docker image we are using: https://github.com/go-gitea/gitea/blob/master/.drone.yml#L243, perhaps we need to switch to drone community plugin: https://github.com/drone-plugins/drone-codecov

Here is a link to a sample build that says coverage was indeed posted: https://drone.gitea.io/go-gitea/gitea/28712/2/14
