### ISSUE TITLE
Let users identify refused SSH public key

### ISSUE THREAD

**Issue by veita** [go-gitea/gitea#12274]
- Gitea version (or commit ref): 1.12.2

## Description

Try to add an SSH key that is already used on the current Gitea server to your account.

Then Gitea refuses to add the key saying that "this key is already being used on this server".

However, the message displayed does not provide a means to unambiguously identify the key on the server. The list of keys in an account's settings only shows SHA256 fingerprints. And there's no one-to-one correspondence between the key comment and the key either.

It would be nice to show some additional information that allows users to find out where the key is already used. E.g.

* show the SHA256 fingerprint of the refused key, or
* if the key is already in the current user's list, show it somehow.

**Comment by WildCryptoFox** [comment]
There is another issue here. If an attacker scrapes GitHub for all public keys, they may associate them to their own account to block users from adding their keys. It may be worth considering an alternative to add the keys which requires you to prove access to the secret key. If the key has already been added, it wouldn't need to say anything more than who the account is associated with and which index it has. I.e. Bob's 3rd key.

```
$ ssh git@gitea.com -i my-identity-key
Welcome to Gitea. To associate your key with your account enter your username and
password (or an association key generated on the website).
```

**Comment by zeripath** [comment]
If you have the key you can simply ssh -i private_key git@gitea and it will tell you who you are authenticating as.
