### ISSUE TITLE
[Suggestion] Crate all base backup through Gitea interface.

### ISSUE THREAD

**Issue by VitaliyAT** [go-gitea/gitea#12277]
I want create back up, but gitea don't do it under root through ssh. It's waiting gitea user. I can't login to ssh like gitea user. Loop. 
I am gitea user only when I am in Gitea. Why Gitea interface have no such usable feacher like create all base back-up through administrative interface?

**Comment by lunny** [comment]
I think this is a feature that will backup one repository as a zip file which contains git data/issues/comments and etc. It's related with #12244

**Comment by 6543** [comment]
yes a good idear! an "Download Backup" botton for repoAdmins at RepoSettings would be greate

**Comment by 6543** [comment]
ping
