### ISSUE TITLE
Github's basic authentication using a password to the API is deprecated and will soon no longer work

### ISSUE THREAD

**Issue by kkzhang** [go-gitea/gitea#12278]
- Gitea version (or commit ref): 1.12.1
- Git version: 1.7.1
- Operating system: ubuntu
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ x] Not relevant
- Log gist:

## Description
When i cloned a private repo from github, I received a email from Github, says "Basic authentication using a password to the API is deprecated and will soon no longer work".

How can i overcome this problem after that?
...

**Comment by mrsdizzie** [comment]
We already support using an application key from Github if you put it in the user name spot. We Just need to update the UI to not ask for username/password

**Comment by IdlePhysicist** [comment]
@lunny I am not the person who opened this issue, but I can confirm putting you Personal Access Token into the username field will work for migrations from GitHub.

**Comment by jolheiser** [comment]
Fixed by #12619
