### ISSUE TITLE
Language statistics: define own languages

### ISSUE THREAD

**Issue by J-U-B** [go-gitea/gitea#12280]
- Gitea version (or commit ref): 1.12.2
- Git version: 2.11.0
- Operating system: Debian Buster
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
I know currently you are using hard coded languages for the language statistics. But it would be helpful if I could define my own languages (at least by their file extensions).

### Background
Most of our projects are written in a script language which is not known to the used library. But just these scripts should be measured.
Therefore at present the statistics given are not really useful and a wrong impression of the code is created.

**Comment by lafriks** [comment]
What do you mean by defining? By file extension?

**Comment by J-U-B** [comment]
To "define" a language by a list of file extensions would be okay.
I think it is too much work to recognize the language by the file content.

In our case for example we are talking about [opsi-script](http://download.uib.de/opsi_stable/doc/html/en/opsi-winst-manual/opsi-winst-manual.html).
Currently, in the projects most of the script code seems to be detected as _Makefile_, is other cases as _Shell_. None of this is correct.

**Comment by lunny** [comment]
Maybe you mean language alias.

**Comment by J-U-B** [comment]
On a first look at [go-enry](https://github.com/go-enry/go-enry) I think `LanguagesByExtension` might be the right one.
