### ISSUE TITLE
Password complexity harms memorability

### ISSUE THREAD

**Issue by WildCryptoFox** [go-gitea/gitea#12284]
Please remove the password complexity constraint on registration. A variety of symbols doesn't improve security. If you want to promote good password management, offer the user a generated passphrase of **sufficient entropy** without forcing their hand. I.e. 6 dice words from EFF's dice word list. https://eff.org/dice

[![XKCD: Password Strength](https://imgs.xkcd.com/comics/password_strength.png)](https://xkcd.com/936/)

**Comment by lunny** [comment]
It could be changed on your `app.ini`.

**Comment by WildCryptoFox** [comment]
@lunny I advise changing the default and Gitea.com to remove the complexity requirement. It is fine to keep as a feature because some organizations do have similar unhelpful policies.
