### ISSUE TITLE
snap packge pre-seeds /var/snap/gitea/$version/ in install page breaking snap updates

### ISSUE THREAD

**Issue by ogra1** [go-gitea/gitea#12292]
- Gitea version (or commit ref): v1.12.2 (stable snap channel)
- Git version:
- Operating system: Ubuntu Core 18
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

When starting the /install page for a fresh installation the writable snap directories are properly set as default (assuming from the $SNAP_DATA variable which contains these versions) i.e.:

    /var/snap/gitea/4837/data/gitea.db (when using sqlite)
    /root/snap/gitea/4837/gitea-repositories
    /var/snap/gitea/4837/lfs
    /var/snap/gitea/4837/log

The problem here is that the version numbers end up in app.ini. 
Upgrading the snap will fail because when upgrading the version number of the directory name is bumped and read access to the old versioned directory gets denied (the versioned dirs are fully bound to the binary versions of a snap)

Snapd creates symlinks by default to avoid such issues, the pre-seeded values in the install page should instead point to the directory names involving these symlinks i.e.:

    /var/snap/gitea/current/data/gitea.db
    /root/snap/gitea/current/gitea-repositories
    /var/snap/gitea/current/lfs
    /var/snap/gitea/current/log
    ...

...this way upgrades and roll-back will be possible.
...

**Comment by 6543** [comment]
@ogra1 feel free to create a pull
or may @popey could have a look at it - since it looks like no gitea maintainer realy use snap :/

**Comment by techknowlogick** [comment]
@ogra1 is `/var/snap/gitea/current` kept the same between upgrades?

**Comment by ogra1** [comment]
yup, the /var/snap/gitea/current symlink gets rolled back and forth between update/rollback so you get always the right data dir matching the currently running version by design.

**Comment by techknowlogick** [comment]
I suspect we could do something with https://github.com/go-gitea/gitea/blob/master/snap/snapcraft.yaml#L68 the compilation here where we could set `/var/snap/gitea/current` as the directory to use.

**Comment by techknowlogick** [comment]
Investigating this, Gitea is referencing $HOME for reporoot path on install page, which is equal to $SNAP_DATA , so the original value of snap data is stored in config on install. After testing how changing this default would impact various downstream distributions I will send a PR for a possible solution.
