### ISSUE TITLE
Signed commits reveal email addresses (and spammers are scraping Gitea for email addresses)

### ISSUE THREAD

**Issue by WildCryptoFox** [go-gitea/gitea#12296]
I've been testing Gitea for just one week today and I just received spam on an address dedicated to catch this exact event and tell me where it was sourced. It is already default to hide the user's email address on their profile but anyone who signs their code has their email address broadcast to anyone scraping the service.

It is sufficient to say the email address has been verified for an account on Gitea. It is unnecessary to include the email address in the web interface.

Please remove the email address from the interface. Thank you.

**Edit**: @canarysnort01 has found another leak. On the /commits/ page if you hover over signed commits the leaked email address will match your account's primary email address instead of the address on the PGP key.

**Comment by bryanpedini** [comment]
> Please remove the email address from the interface. Thank you.

I hope you also did consider the possibility for malicious users to just `git clone` via HTTPS, and `git log` your e-mail address (I put together a [bash script](https://gist.github.com/bryanpedini/3d65f88700202376ea6b0ac11993459b) in less than half an hour, pretty funny but also dangerous, it got 909 email addresses from go-gitea/gitea)

**Comment by WildCryptoFox** [comment]
@bryanpedini Of course; but fortunately after many years I've never seen spammers actually do this.
