### ISSUE TITLE
Allow to specify default PR merge option

### ISSUE THREAD

**Issue by MGChecker** [go-gitea/gitea#12293]
Currently, there are four different ways to merge PRs
* Merge pull request
* Rebase and merge
* Rebase and merge (--no-ff)
* Squash and merge

Usually, the first one in the list which has been activated via repository settings is the default and is achieved when clicking on the big button. I would like to be able to specify the default action for the large button in the repository settings.

**Comment by lafriks** [comment]
Usually only one per repo should be used so imho best practice would be to disable all other options in repository settings
