### ISSUE TITLE
Milestone card view

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#123]
Currently we can list the issues of one milestone, but I think if we can set some progress and provide a card view, we will manage it well. A milestone like a project on github. So if you create a milestone, you have created a project, it's no need an extra UI to do that.

**Comment by jeppech** [comment]
Sounds like a really nice feature! 👍 

So to be sure, you'd like a card view of the milestones in a repo, and furthermore a project card view also, yea?

**Comment by lunny** [comment]
Yes. It's more flexible.

**Comment by 6543** [comment]
projects can be used like milestones - do v1.13.0 solve this?!?

**Comment by lunny** [comment]
I think we can close this since projects & projectboards merged. But I think we could make some relation between milestones and projects. But that should be another issue.
