### ISSUE TITLE
Option to show stack traces on the 500 page

### ISSUE THREAD

**Issue by silverwind** [go-gitea/gitea#12304]
It'd be useful for debugging to have stack traces available on the 500 page to give an indication on where/why the error occured without having to dig into the logs, maybe in a expandable box. I'd even lean to having that option on by default.

**Comment by jolheiser** [comment]
> I'd even lean to having that option on by default.

Perhaps for admin users? Similar to the report message.

**Comment by silverwind** [comment]
Yeah, admins should always see it. I guess there could be options:

````
ui.SHOW_STACK_TRACES = true
ui.SHOW_STACK_TRACES_USERS = all | admin-only

**Comment by veita** [comment]
Note that showing stack traces with error messages to the client has the potential to weaken the security of web applications, e.g, through CWE-79.

**Comment by silverwind** [comment]
XSS should of course be avoided with HTML escaping. Other than that, my only concern is a "leakage" of file system paths, but I don't think this would give much of an attack vector of its own.

**Comment by veita** [comment]
HTML escaping does not help since the server generally does not have control about the context in which the data are processed by the client.

**Comment by bryanpedini** [comment]
> I guess there could be options:

I'm with @veita here, even having an option to show the stack traces to everybody is a potential security flaw, not so much about your instance per se, as much about the application itself in general, leaving more room to malitious users to find a way in (potentially) **all** instances.

(I know the entire project is open source, but digging into Golang code to find a breach is much harder than having a direct path in shown directly by the server itself you're trying to breach 😉)

**Comment by lafriks** [comment]
Stack trace could be shown if Gitea is run in development mode

**Comment by bryanpedini** [comment]
> Stack trace could be shown if Gitea is run in development mode

Would agree: temp move Gitea to dev -> solve issue -> go back to production

**Comment by silverwind** [comment]
That would for example not really help developers that want to debug errors seen on try.gitea.io for example, unless we permanently run it on dev mode.

I still think it's kind of pointless trying to hide internals when the whole source code is open source. Paths could potentially be sanitized as well.

**Comment by bryanpedini** [comment]
> unless we permanently run it on dev mode.

I think it **is** in dev mode... correct me if I'm wrong @lafriks.

> I still think it's kind of pointless trying to hide internals when the whole source code is open source.

As said before, it's not so much as the source is open, but rather as it would lead to a "come here, open entrance" message directly from your server...

**Comment by silverwind** [comment]
I'm not sure what dev mode entails but I could see a toggle in the admin settings UI to temporary switch then run mode. Of course it should be turned off after debugging. We can't really restrict it to logged in admin users because some errors can happen before login.

**Comment by 6543** [comment]
as for api: #13115

**Comment by bryanpedini** [comment]
> as for api: #13115

Is this solved then?

**Comment by silverwind** [comment]
I have not tesed that PR but I think it enables stack traces for admin users. I guess a option to show it to all users may still be handy sometimes, for example if an error is only reproducible under a certain user so admin could temporarily flip that option.

There should be a warning in the option description that it might expose secrets/internals so it has to be enabled with care. I'd call it `ALWAYS_SHOW_STACK_TRACES` or similar.

**Comment by 6543** [comment]
I think showing the stack trace to a normal user is a bad Idear!
It can print data the user should not have access to!

But If you are admin It should be fine

**Comment by silverwind** [comment]
Yeah I guess admin-only is good enough and certainly would fit my requirement, so yes, I think this is resolved.
