### ISSUE TITLE
Docsy integration

### ISSUE THREAD

**Issue by ShalokShalom** [go-gitea/gitea#12303]
https://www.docsy.dev/

Docsy is a wiki in form of a Hugo template.
We could integrate it on our Gitea instance, although I think some code could be needed on their side to seamlessly integrate it.

As such, the Jekyll port of Docsy supports creating issues on Github, if they are hosted there.

The same way could we integrate, so that people could raise issues about the documentation in Gitea with the click of a button.

**Comment by 6543** [comment]
@ShalokShalom do we have to add some API's?
-> since I think github integration was done by utilizing the github-api. gitea has a realy similar api ... so I think this os more a Docsy issue.

@ShalokShalom did you open an issue on Docsy Issue Tracker?

**Comment by ShalokShalom** [comment]
1) No idea. It is a static web page. Created by Hugo.
2) No, I thought its here more appropriate.

**Comment by 6543** [comment]
@ShalokShalom created https://github.com/google/docsy/issues/355 ...
