### ISSUE TITLE
Webhook sends wrong "assigned to" user in issue assigned change triggered message.

### ISSUE THREAD

**Issue by chriseaton** [go-gitea/gitea#12309]
- Gitea version (or commit ref): 1.12.2
- Git version: 1.8.3.1
- Operating system: CentOS 7
- Database (use `[x]`):
  - [x] PostgreSQL
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes

## Description
Likely a similar issue as #11295, the webhook (tested on Slack) sends the the incorrect user name of whom the issue is assigned to, instead it sends the user name of the user making the change. 

Let's say user john.smith...
1. assigns user jane.doe.
2. unassigns himself from issue "Need to upgrade to ES6".

The webhooks will send a message not even mentioning jane.doe - example output:    
> [code/sample-nodejs] Issue assigned to **john.smith**: # 2 Need to upgrade to ES6. by john.smith
> [code/sample-nodejs] Issue unassigned: # 1 Need to upgrade to ES6. by john.smith

**Expected result:**    
A webhook message is sent saying:     
> [code/sample-nodejs] Issue assigned to **jane.doe**: # 2 Need to upgrade to ES6. by john.smith
> [code/sample-nodejs] Issue unassigned: # 1 Need to upgrade to ES6. by john.smith

**Comment by zeripath** [comment]
Does this still happen?

If so it likely needs a similar fix - we need to set the assignee before we send the webhook.

**Comment by chriseaton** [comment]
Yes - still happens!

**Comment by wxiaoguang** [comment]
IIRC there were more fixes to this this problem. Feel free to reopen if the bug still exists.
