### ISSUE TITLE
`make generate-images` fails with newer inkscape versions

### ISSUE THREAD

**Issue by stertingen** [go-gitea/gitea#12314]
- Gitea version (or commit ref): 7744b36
- Git version: not relevant
- Operating system: not relevant
- Database (use `[x]`): not relevant
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

`make generate-images` fails with newer inkscape versions (version 1.0) because some CLI arguments have changed.

References: 
https://inkscape.org/sk/doc/inkscape-man.html
https://wiki.inkscape.org/wiki/index.php/Using_the_Command_Line#Changes_from_0.92

Instead of `inkscape -f <infile> ... -e <outfile>`, it should be `inkscape <infile> ... --export-file=<outfile>`.

(I stumbled upon this when creating my own Gitea logo)

This could be helpful:
`inkscape --version 2>/dev/null | cut -d ' ' -f 2 | cut -d . -f 1` prints the major inkscape version which then can be compared to '0' or '1'.

**Comment by silverwind** [comment]
Should be resolved with https://github.com/go-gitea/gitea/pull/12316 if you want to give it a try.

**Comment by stertingen** [comment]
> Should be resolved with #12316 if you want to give it a try.

This works, thanks!
