### ISSUE TITLE
404 for css/js files after Installation

### ISSUE THREAD

**Issue by HerrHase** [go-gitea/gitea#12313]
- Gitea version (or commit ref): v1.12.2
- Git version: 
- Operating system: Ubuntu 18.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

I have used the installation of your documentation for the binary https://docs.gitea.io/en-us/install-from-binary/, but after this, each asset give me a 404.

## Screenshots

![Screenshot at 2020-07-24 12-39-15](https://user-images.githubusercontent.com/5207733/88384012-e5662600-cdab-11ea-94d3-d0c8010eb784.png)

**Comment by bryanpedini** [comment]
How do you access the Gitea instance?
  - http://gitea.domain.tld:3000?
  - http://gitea.domain.tld with Nginx reverse proxy on http://localhost:3000 for example?
  - http://gitea.domain.tld with Nginx as reverse proxy on a Unix socket (`HTTP_ADDR = /var/run/gitea/gitea.sock` in `app.ini`)?

**Comment by HerrHase** [comment]
With a nginx reverse proxy. Try already some variants in the nginx configuration, but nothing changes.

**Comment by bryanpedini** [comment]
> With a nginx reverse proxy.

Did you follow either the official reverse proxy(es) guide (https://docs.gitea.io/en-us/reverse-proxies/) or a well-known good and working config example? I can drop a gist with mine if you need, I have both localhost:3000 config and Unix path, as I'm migrating the server from the first to the latter.

**Comment by HerrHase** [comment]
Both and i have gitea installed not the first time. I have build all assets from the source and serve them from another subdomain, that works. A gist would be great, maybe there is a hint what went wrong.

**Comment by bryanpedini** [comment]
There you have it, both work fine in their deployment, feel free to ask for any snippet I included if it isn't clear what it does: https://gist.github.com/bryanpedini/0ffa556abd742078c27e813b4fc9f6f2

**Comment by silverwind** [comment]
Check your `STATIC_URL_PREFIX` configuration, it's what most assets use.

**Comment by HerrHase** [comment]
I have, but the best solution was to build all assets and place them in a sub directory. I tried the configuration from @bryanpedini but, the problem was the same, 404 errors for all assets. Thanks for your help!

**Comment by bryanpedini** [comment]
> I tried the configuration from @bryanpedini but, the problem was the same, 404 errors for all assets.

Both of the provided configurations work fine for me in both of my completely different servers...
Tho, I don't either serve files from a different subdomain nor a different directory than the standard /static/ (I think) from the Gitea server itself, so I can't help in that way. Maybe just use the Gitea instance static serving from the Golang server, no?

**Comment by HerrHase** [comment]
Ah, no Problem :) I only wondering why it didn't work for me in "basic" Version. But now its even faster with the static files ;-)

**Comment by bryanpedini** [comment]
I told ya'... use the Go server builtin static file serving... 😉
