### ISSUE TITLE
smart way to debug 

### ISSUE THREAD

**Issue by zhoutt96** [go-gitea/gitea#12318]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
Hi gitea team, sorry to bother. 
I am creating this issue to ask is there any smart way for debugging?
For now, when I do a change in backend, I need to rebuild the project everytime. 
thanks. 
...

**Comment by a1012112796** [comment]
Hello, you can try ``make help`` to get all build options, thanks.

**Comment by lunny** [comment]
@a1012112796 @zhoutt96 I think debug is a low efficient development and it's not recommand by golang team. The best practice is writing unit test and add logs.

**Comment by silverwind** [comment]
I'd appreciate a `watch-backend` mode that rebuilds and runs whenever source files change.
