### ISSUE TITLE
+1, -1, and other reactions on issues and issue comments

### ISSUE THREAD

**Issue by pgaskin** [go-gitea/gitea#1232]
There should be +1, -1, and other reactions on issues and issue comments just like GitHub and GitLab.

**Comment by jcgruenhage** [comment]
@bkcsoft Why are you opposed to this?
Edit: Expressing being opposed to something by using that thing also seems kinda strange :P

**Comment by bkcsoft** [comment]
@jcgruenhage Because I'm a :trollface: perhaps? I really have nothing against this. I think I even :+1:'d it on the original Gogs-issue 😉 (I pretty much abuse this feature at work, so I'm all for having this in Gitea as well)

**Comment by jcgruenhage** [comment]
I hoped so, wasn't sure though, so I thought I might ask ^^

**Comment by lafriks** [comment]
Fixed with #2856
