### ISSUE TITLE
Error when uploading images

### ISSUE THREAD

**Issue by donnyv** [go-gitea/gitea#12339]
- Gitea version (or commit ref): 1.12.2 built with GNU Make 4.1, go1.14.4 : bindata, sqlite, sqlite_unlock_notify
- Git version: 2.27.0
- Operating system: Windows Server 2019
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x ] No
  - [ ] Not relevant
- Log gist:

## Description
Every time I upload an image I get this error. Weird thing is it uploads the file fine and I can use it. I'm guessing its having issues deleting this temp file. Not sure why since I have not had any issues creating repositories on this server or pushing updates.

![image](https://user-images.githubusercontent.com/2224189/88573888-72f58000-d00f-11ea-805d-a79b87843661.png)

...

**Comment by shenlijun** [comment]
linux server would be fine

I tested both windows and linux，clean windows and Linux with Anti-virus software

**Comment by zeripath** [comment]
do you have antivirus running?

**Comment by donnyv** [comment]
> do you have antivirus running?

No

**Comment by zeripath** [comment]
Something must be holding on to the file but I'm not certain what could be doing that. Could you try a build of pr #12447 ?
