### ISSUE TITLE
wrong url for submodule when using reverse proxy in 1.11 and newer

### ISSUE THREAD

**Issue by shenlijun** [go-gitea/gitea#12345]
- Gitea version (or commit ref): 1.11 and newer
- Git version: 2.18.4
- Operating system: CentOS 8
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

I have a gitea with base URL https://xxxx.yyy/git, using Nginx as a reverse proxy 

same repository, when using 1.11 and newer, the submodule URL will be https://xxxx.yyy/git/git/zzz,  click it just give me 404 because duplicated “git”

but 1.10 works fine, just  https://xxxx.yyy/git/zzz
...

**Comment by shenlijun** [comment]
@lunny

**Comment by shenlijun** [comment]
？

**Comment by zeripath** [comment]
Please tell us what git thinks the submodule is and then we can work out how to fix this.

The mapping of submodules to urls is complex and extremely fiddly - it's really very complex and our problem is that we don't have good testcases for any of this.

**Comment by shenlijun** [comment]
> Please tell us what git thinks the submodule is and then we can work out how to fix this.
> 
> The mapping of submodules to urls is complex and extremely fiddly - it's really very complex and our problem is that we don't have good testcases for any of this.

That just different behavior between 1.10 and newer，so I think a code comparison would fix it out @zeripath

**Comment by lunny** [comment]
Could you provide your submodule file example.

**Comment by shenlijun** [comment]
> Could you provide your submodule file example.

只是浏览器打开的时候url有问题，Git和仓库本身行为没有异常
如果客户端用命令行git clone --recursive或者git pull的话是正常的

1.11之后开始出现这个现象，可能问题只出在web interface相关的代码改动？

一个废弃仓库实例，不要在意代码水平，哇哈哈

[ProofProxyClassic.zip](https://github.com/go-gitea/gitea/files/5061551/ProofProxyClassic.zip)

**Comment by zeripath** [comment]
> > Please tell us what git thinks the submodule is and then we can work out how to fix this.
> > The mapping of submodules to urls is complex and extremely fiddly - it's really very complex and our problem is that we don't have good testcases for any of this.
> 
> That just different behavior between 1.10 and newer，so I think a code comparison would fix it out @zeripath

No because the 1.10 code was also incorrect so just reverting to the old code is no more correct than the new code.

Looking at your provided zip it appears that the git url for the submodule is:

https://www.micro-visions.org/git/MiRA/MiraDatabase-Proto.git

Presumably you are hosting gitea on https://www.micro-visions.org/git/

and when you try to click on the submodule you get linked to:

https://www.micro-visions.org/git/git/MiRA/MiraDatabase-Proto
