### ISSUE TITLE
MAX_CREATION_LIMIT when set doesn't show in UI

### ISSUE THREAD

**Issue by donnyv** [go-gitea/gitea#12354]
- Gitea version (or commit ref): 1.12.2 built with GNU Make 4.1, go1.14.4 : bindata, sqlite, sqlite_unlock_notify
- Git version: 2.27.0
- Operating system: Windows Server 2019
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x ] No
  - [ ] Not relevant
- Log gist:

## Description
I set MAX_CREATION_LIMIT in the .ini file = 0 and restarted the service. Created a new user using the UI and still see the default value as -1. Since I set it in the ini file shouldn't it show it as 0?
...

## Screenshots

![image](https://user-images.githubusercontent.com/2224189/88709340-fcc24d80-d0e2-11ea-80ef-3cfd4eef8ba0.png)

**Comment by jolheiser** [comment]
> Enter -1 to use the global default limit.

As far as I know, `-1` will default to the global limit.
