### ISSUE TITLE
How to run frontend seperatly

### ISSUE THREAD

**Issue by zhoutt96** [go-gitea/gitea#12353]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
Hi team, I am trying to customize the frontend page, how to build and run the vue.js project separately?  Without involving backend. thanks.  

...

**Comment by techknowlogick** [comment]
If you'd like to run the webpack/npm build process independently you run `make frontend` or `make watch-frontend`

The https://docs.gitea.io/en-us/hacking-on-gitea page has a lot more documentation on these commands.

**Comment by zhoutt96** [comment]
but how to serve it on local port?

**Comment by techknowlogick** [comment]
The frontend receives configuration from Gitea when running (via templates, etc..), and so you'll have gitea running too.

If you are looking to host the CSS/JS files on a CDN, the STATIC_PREFIX config option is likely what you are looking for.

**Comment by zhoutt96** [comment]
thanks, i know.
