### ISSUE TITLE
setting ENABLE_PUSH_CREATE_ORG - appears to have no effect

### ISSUE THREAD

**Issue by voobscout** [go-gitea/gitea#12355]
- Gitea version (or commit ref): 1.12.2
- Git version: 2.27.0
- Operating system: NixOS
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
Relevant part of the ini
```ini
[repository]
ENABLE_PUSH_CREATE_ORG  = true
ENABLE_PUSH_CREATE_USER = true
```
Now, let's try and auto-create org/repo on push
```bash
git remote add gitea-remote-new-org gitea@my.git.fqdn:neworgname/reponame.git
git push -u --set-upstream gitea-remote-new-org master
```
Unfortunately, the result is
```
Unable to get owner: neworgname user does not exist [uid: 0, name: neworgname, keyid: 0]
```
**However**, this works:
```bash
git remote add gitea-remote-existing-org gitea@my.git.fqdn:existingorgname/reponame.git
git remote add gitea-remote-existing-user gitea@my.git.fqdn:existinguser/reponame.git
git push -u gitea-remote-existing-org master
git push -u gitea-remote-existing-user master
```
Imho, I miss knowledge/expertise, misunderstand the purpose of ENABLE_PUSH_CREATE or a bug has been discovered.
In case, the purpose of those switches are granular control, ie, already existing user/organization namespaces and absent repos, then this is likely a feature request.

Desired result - whatever is pushed to gitea should auto-create namespaces, provided the user has enough permissions.
Any advise/comment is much appreciated!

**Comment by zeripath** [comment]
PUSH_CREATE_ORG allows you to create repositories for an existing organizations. It cannot just create organizations. 

Similarly PUSH_CREATE_USER allows you to create repositories for existing users themselves.
