### ISSUE TITLE
gitea dump is broken when total size of repositories is bigger than half of memory

### ISSUE THREAD

**Issue by basilrabi** [go-gitea/gitea#12363]
- Gitea version (or commit ref): 1.12.2
- Git version: 2.26.2
- Operating system: Fedora 32
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant

## Description

`gitea dump -c /etc/gitea/app.ini` uses `/tmp` to temporarily store the zip dump. This method is broken once the zip is larger than half of memory since modern OS uses `tmpfs` for `/tmp` which has a capacity of equal to half of memory. According to the [documentation](https://fedoraproject.org/wiki/Features/tmp-on-tmpfs), `/var/tmp` can be used for large files.

**Comment by warnat** [comment]
this is a fedora thing and has nothing to do with gitea. please close.

**Comment by zeripath** [comment]
There is a `--tempdir` option to set this to whatever is required:

https://docs.gitea.io/en-us/command-line/#dump
