### ISSUE TITLE
Duplicate headlines in commit message after pull merge

### ISSUE THREAD

**Issue by typeless** [go-gitea/gitea#12365]
- Gitea version (or commit ref):
1.13.0+dev-258-g8f489131f

- Git version:
2.26.2

- Operating system:
x86_64 GNU/Linux synology_avoton_1817+

- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
![image](https://user-images.githubusercontent.com/2606021/88794495-22c61b80-d1d1-11ea-870c-556d3da8c280.png)

As you can see, the headline `Upgrade mtd-utils to 2.1.2 for UBIFS authentication` is repeated.  
It's okay to remove it manually. But the UX would be nicer if no such step is required.
...

**Comment by typeless** [comment]
The message shown in the snapshot is a merge-by-squash pull.

It seems that the current behavior makes sense under most circumstances like when the PR has a title independent of the individual commits. Probably manually removing the repeated lines is the best way one can do?

If there is any good idea to improve, I can give it a look.

**Comment by silverwind** [comment]
GitHub also has this issue. It may actually be a side effect of git squashing, not sure.

**Comment by typeless** [comment]
@silverwind hmm, if Github has the same issue and no one complains about it, it’s probably good enough for most people.

Let me see if there is any possible improvement.

**Comment by zeripath** [comment]
Tbh I've been thinking about this and I think the way GitHub and Gitea do this is incorrect. We really should be offering the content of the PRs headline comment as the commit comment instead of the git commits.

The PR headline is the description of what this PR does - therefore it's what the squash commit should have as its comment.
