### ISSUE TITLE
goldmark default table can't deal this correctly, **xxx** before table with only \n 

### ISSUE THREAD

**Issue by jacky-2014-sn** [go-gitea/gitea#12376]
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (example URL: https://try.gitea.io/jacky-2014-sn/testgit/src/branch/master/table.md)
  - [ ] No
  - [ ] Not relevant

## Description
```
**xxx**
| hello |   hi  |
| :----: | :----:|
```
text as this, will show incorrectly in try.gitea.io

## Screenshots
![LXTFV%BAKTC1L 2)`QSYVRT](https://user-images.githubusercontent.com/10017293/88896194-1519a000-d27c-11ea-868d-05220226d83b.png)

![NWG4XER675O~I$ VPD`H0GF](https://user-images.githubusercontent.com/10017293/88896077-ea2f4c00-d27b-11ea-8802-503b9c67286a.png)

**Comment by zeripath** [comment]
This appears to be a bug in the underlying library - Goldmark and I've opened an issue there.

**Comment by yuin** [comment]
goldmark author here.

Thanks for reporting this.
I've fixed the issue and made a new release.
