### ISSUE TITLE
Snap-package broken MySQL TLS, HTTPS repo-migration

### ISSUE THREAD

**Issue by WereCatf** [go-gitea/gitea#12388]
- Gitea version (or commit ref): 1.12.3
- Git version:
- Operating system: Ubuntu 20.04 Focal Fossa
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
TLS-connection to MySQL-server only works with skip-verify option because Gitea is unable to verify certificate-authority. The server uses a Let's Encrypt - certificate, so no idea if that is relevant or not. TLS-connection works fine with the non-snap version.

Trying to migrate a repo from Gogs or Github with an HTTPS URL fails with Gitea-log complaining about "warning: templates not found /usr/share/git-core/templates" and "fatal: Unable to find remote helper for 'https'"

This is with a fresh install of Gitea; no previous settings, database or anything else used.

**Comment by zeripath** [comment]
I guess we're not allowing gitea to get to the root certificates in the snap version. I bet we need to add another directory to snap but quite which I don't know.

I'm gonna prod @popey who might know the simplest thing to do here.

**Comment by wmutschl** [comment]
Any progress here? Is there a workaround?

**Comment by WereCatf** [comment]
> 
> 
> Any progress here? Is there a workaround?

I have no idea. I decided to just run Gitea without Snap, since the Snap-package is too broken to be useable for my needs.
