### ISSUE TITLE
Search commits cosmetic

### ISSUE THREAD

**Issue by Fastidious** [go-gitea/gitea#1238]
- Gitea version (or commit ref): `1.1.0`
- Git version: `N/A`
- Operating system: `N/A`
- Database (use `[x]`): `N/A`
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL) `https://try.gitea.io/Fastidious/Test-15/commits/master`
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
The ticked box to search `All` is too close to its label. I think the tick box and label should be moved to before the search field instead, and the `Find` button replaced with `Search`, to make it consistent with the rest of search boxes used.

**Screenshot:**

![search_bug](https://cloud.githubusercontent.com/assets/8352292/23849312/7e17f618-07b1-11e7-9dd7-85346ecbe4c0.png)

**Comment by pgaskin** [comment]
I have submitted PR #1254
