### ISSUE TITLE
About gitea free-hosting - is there any service like that?

### ISSUE THREAD

**Issue by sysdl132** [go-gitea/gitea#12394]
I think the gitea hosting is easy to found.But...most of them are expensive.So is there any service to host gitea without pay? 🥇

**Comment by mmarif4u** [comment]
codeberg.org, gitea.com to name a few.

**Comment by techknowlogick** [comment]
https://gitea.com/gitea/awesome-gitea/#user-content-organizations

You could even run gitea on your own computer for free too!
