### ISSUE TITLE
How to check an issue in a public Gitea instance that you do not host in?

### ISSUE THREAD

**Issue by TheEvilSkeleton** [go-gitea/gitea#12393]
I hope it isn't a problem asking the question here: is there a way a person that doesn't host his Gitea instance check what Gitea version they are using? I'm trying to check https://codeberg.org/'s version, but I cannot find its Gitea version.

If it cannot be done, can it be added as a feature?

**Comment by techknowlogick** [comment]
@Codeberg-org has hidden thier version. So they've chosen not to show it to the end user. There is an option to hide/show version already.

If you have questions about codeberg you are able to ask here: https://codeberg.org/Codeberg/Community/issues

**Comment by TheEvilSkeleton** [comment]
Thank you. I appreciate the very quick response
