### ISSUE TITLE
[CI/Build] Provide build artifacts for pull requests

### ISSUE THREAD

**Issue by pgaskin** [go-gitea/gitea#1239]
It would be nice if the build artifacts from the drone CI were downloadable, because then pull requests would be faster to test.

**Comment by bkcsoft** [comment]
Just wanna point out it's about testing, _not_ Gitea itself

**Comment by lunny** [comment]
I think this feature belongs to CI/CD system, should be a part of #13539

**Comment by lunny** [comment]
Should be fixed by #22738
