### ISSUE TITLE
Right menu block is going down

### ISSUE THREAD

**Issue by axeloz** [go-gitea/gitea#1240]
- Gitea version (or commit ref): 1.1.0

## Description

The dashboard's right menu block is going down. 
Chrome for Mac: version 56
On a 24' wide screen

## Screenshots

![capture](https://cloud.githubusercontent.com/assets/1597611/23859676/b9a247bc-0804-11e7-9656-e1939b7f7438.png)

**Comment by lunny** [comment]
maybe this is a duplicated with #1175

**Comment by axeloz** [comment]
It seems due to a `<a href` link misplaced between the two blocks

![capture](https://cloud.githubusercontent.com/assets/1597611/23862521/80bfd1e0-080d-11e7-9a44-66ba7d8df201.png)

Getting rid of it fixes the UI. 
Probably the translation related issue https://github.com/go-gitea/gitea/issues/1183

**Comment by lunny** [comment]
Could you confirm #1177 fix this?

**Comment by axeloz** [comment]
Version 1.1.0+24-g8746fb3 (master build) fixes the issue, yes.
