### ISSUE TITLE
Changing the language should not use GET

### ISSUE THREAD

**Issue by silverwind** [go-gitea/gitea#12403]
Changing the language in the footer dropdown sends of a GET that potentially also writes to the database. This is non-semantic use of GET that should be eliminated. Also, the query string parameter should be removed after changing language, it's just unecessary.

Possible prerequistite for https://github.com/go-gitea/gitea/issues/11188.

**Comment by techknowlogick** [comment]
closing as dupe of https://github.com/go-gitea/gitea/issues/10725
