### ISSUE TITLE
404 for Repository Page

### ISSUE THREAD

**Issue by HerrHase** [go-gitea/gitea#12408]
- Gitea version (or commit ref): 1.12.3
- Git version: 2.17.1
- Operating system: Ubuntu 18.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description

That's really strange, all other Repository Pages are Working, but i have one, i get always a 404 from Nginx, not from Gitea,

If the url looks like this, i get a 404
crispy-css

If i change the ending, i get the page
crispy-css/

If i change the name, i get the page,
crispy-csss

I have no idea how to track this down, there is no entry in the logs about this.
...

**Comment by Masgalor** [comment]
I would assume you have a location block similar to this one in your nginx config.

```
location ~ (css|js|img) {

        try_files $uri $uri/ =404;

} 
```
That would match `crispy-css` and return 404 since its not a file.

**Comment by HerrHase** [comment]
Even worse! It was a default include file with "expires" statements, for static files i used a alias, but the "expires" statement handle it like a file that never showed up. Thank you! I feel a little bit stupid... :D
