### ISSUE TITLE
Allow prebaked application token in environment variables

### ISSUE THREAD

**Issue by izelnakri** [go-gitea/gitea#12414]
Hi there,

I know that gitea currently provides a UI to generate application tokens. However it also needs one application token(a master API key/token perhaps) as environment variable, this way I can deploy gitea in an automated fashion without utilizing the UI. 

In addition, in my own situation I built a microservice that interacts with gitea over webhooks(it posts CI jobs, and makes PR comments on CI running/results), this microservice/k8s deployment uses `$GITEA_SERVER_TOKEN` env variable to interact with the gitea API(to post a PR comment, get open PRs etc). Therefore, this makes the current deployment very challenging without having a prebaked/predetermined application master API token, as that deployment needs to be restarted with the application token in the environment variable when I generate it from the UI currently. Having one token as an environment variable can solve all these problems.

**Comment by lunny** [comment]
You can create a token at first via API.

**Comment by izelnakri** [comment]
POST /users/{username}/token requires an authentication token, it gives 401. How can I generate a token without an authentication token?

**Comment by zeripath** [comment]
POST /user/{username}/token requires BASIC authentication not Token.

**Comment by izelnakri** [comment]
@zeripath this works, thank you! Let's also document it, closing this issue.
