### ISSUE TITLE
Support logging to syslog (/dev/log)

### ISSUE THREAD

**Issue by dmolik** [go-gitea/gitea#1242]
## Description

Configuration should support multiple levels, facilities, and tags depending on the subsystem that is generating output.

tags could be:
[gitea-web|$PID]
[gitea-serv]
[gitea-xorm]
etc.

**Comment by strk** [comment]
\cc @geek1011

**Comment by pgaskin** [comment]
See the part at the end of https://github.com/go-gitea/gitea/issues/8#issuecomment-286474772
