### ISSUE TITLE
Repos not showing properly under dashboard after migration from 1.11.4 to 1.12.x

### ISSUE THREAD

**Issue by mbarinc** [go-gitea/gitea#12429]
- Gitea version (or commit ref): 1.12.3
- Git version: 2.23
- Operating system: Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description

I upgraded from 1.11.4 to 1.12.3 (previous I tried with 1.12.0/1.12.1/1.12.2 too) and in every upgrade the Organizations are missing in the dashboard. All the links are broken, but if I paste the correct link in the URL, Gitea show me the repository.

1.11.4
![image](https://user-images.githubusercontent.com/3716953/89348491-edc43800-d6ac-11ea-8170-301b5b10cd60.png)

1.12.3
![image](https://user-images.githubusercontent.com/3716953/89348602-1a784f80-d6ad-11ea-8824-5260c5939a41.png)

Can you please help me to find where is the problem?
...

**Comment by zeripath** [comment]
It looks like Migration 128 has only been partially applied.

https://github.com/go-gitea/gitea/blob/dc812f8ba5bf1c123fa948afed15c4309da8fb45/models/migrations/v128.go

Now I suspect that's because you switched between. 1.11 and master and back again at some point. 

Do you have a back up from before you migrated back to 1.12.3?

It might be useful to check which other migrations you have accidentally skipped. 

To fix this issue you simply need to run a query:

```sql
UPDATE repository INNER JOIN `user` ON `user`.id = repository.owner_id SET owner_name = `user`.name
```

Or thereabouts...

But I don't know what other migrations you may have missed.

**Comment by mbarinc** [comment]
Thank you @zeripath .

I haven't backup before 1.12.3 migration.
In order I have:

- upgraded from 1.11.4 to 1.11.5 (rollbacked for a problem with a few templates that I've modified)
- waited in 1.11.4 until the release of 1.12.0 (in the meantime fixed the templates), then:
- upgraded from 1.11.4 to 1.12.0 (rollbacked for the problem above)
- upgraded from 1.11.4 to 1.12.1 (rollbacked for the problem above)
- upgraded from 1.11.4 to 1.12.3 (rollbacked for the problem above)

I checked repository.owner_name on DB and the values are null. 
Then your statement will fix the error.
I will try the upgrade again as soon as possible (I have to agree with the developers)

In order to be sure that is all ok, there are others checks to be planned?

Thanks in advance

**Comment by zeripath** [comment]
When you "rolled-back" did you actually roll back the DB completely? Do you have a copy of the db before you ran the last migration? It would be helpful to note the Version table - A version 1.11 gitea system should have Version <= 118. If it's greater than that you might be able to force it back to 118 but please reply with what version the DB thinks it is before you attempt to migrate again.

**Comment by mbarinc** [comment]
I only rollbacked the binary. The DB was never rollbacked. 
Actually in the table "version" the max id have version = 118

**Comment by zeripath** [comment]
OK then `gitea migrate` should cause the db to update.

**Comment by 6543** [comment]
just to mention, a real rollback include restoring old state of database ...

related:  #13107

**Comment by zeripath** [comment]
I'm closing this as it has been awaiting further feedback for over a month
