### ISSUE TITLE
Support pulling configuration via consul/etcd

### ISSUE THREAD

**Issue by dmolik** [go-gitea/gitea#1244]
## Description
given a consul/etcd endpoint given as a command line parameter, gitea should be able to pull further configuration via an api. Furthermore, gitea could register itself and monitoring checks.

**Comment by bkcsoft** [comment]
If we supported more env-vars (using e.g. https://github.com/kelseyhightower/envconfig) one could use https://github.com/mattn/etcdenv for this. As for `SIGHUP`ing gitea when config changes, that's up to etcdenv (or similar tooling) IMO

**Comment by dmolik** [comment]
I've moved to
