### ISSUE TITLE
Mirror Task: System message say: "finished" but the task is still running

### ISSUE THREAD

**Issue by somera** [go-gitea/gitea#12442]
- Gitea version (or commit ref): 1.12.3
- Git version: 2.25.1
- Operating system: Ubuntu 20.04
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

I have only screenshots. I started it mynually (why there is no system message, that the task was started?). Than I saw the message:

`Task: Update Mirrors started by gitea_admin has finished`

and wanted shutdown the server. But ... the monitoring page say: "Stop, the task is still running."

And I'm missing the time Information in the detail status to the action. Will be helpfull if you will match this with the logs.

## Screenshots

![image](https://user-images.githubusercontent.com/8334250/89528620-a395a080-d7eb-11ea-854b-c6015293296a.png)

![image](https://user-images.githubusercontent.com/8334250/89528633-a7c1be00-d7eb-11ea-9991-25cbb4764f23.png)

![image](https://user-images.githubusercontent.com/8334250/89528906-1e5ebb80-d7ec-11ea-953f-a4198eb13d8d.png)

**Comment by somera** [comment]
Some minutes after the post ...

![image](https://user-images.githubusercontent.com/8334250/89529180-93ca8c00-d7ec-11ea-9a5f-099f2267401f.png)

Still running.

**Comment by somera** [comment]
... running

![image](https://user-images.githubusercontent.com/8334250/89529371-e86e0700-d7ec-11ea-9482-5a0f1e39d5d5.png)

**Comment by zeripath** [comment]
Please ignore the system notices for UpdateMirror they don't mean what they imply they do and therefore I've just merged a PR that means they are going to stop appearing soon.

**Comment by somera** [comment]
Ok. Bit and information, that the process is finished will be better/helpful.

**Comment by zeripath** [comment]
The issue is that the UpdateMirror task simply adds the repo ID to a queue of mirrors to be updated - that's all that the task does. The actual work of updating mirrors is done by the syncMirror function. That's the place that should be sending a repository notice to say it's been updated and by how much - however, as we've noted that could cause a lot of messages. We need to think a bit more about these things.

**Comment by somera** [comment]
thx for the feedback!
