### ISSUE TITLE
Adding SSH key doesn't work if JavaScript is disabled

### ISSUE THREAD

**Issue by JeremyRand** [go-gitea/gitea#12444]
- Gitea version (or commit ref): 1.12.2 built with Go 1.14.4 (as packaged in Void)
- Git version: 2.28.0 (as packaged in Void)
- Operating system: Void Linux for PowerPC/Power ISA (ppc64le musl)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL): https://try.gitea.io/user/settings/keys
  - [ ] No
  - [ ] Not relevant
- Log gist: Issue is client-side; no errors appears in browser console logs, client does not issue any network traffic to server.

### Instructions to reproduce

1. Put Tor Browser in "Safest" security mode.  Among other things this disables JavaScript.
2. Log into Gitea.
3. Visit the `user/settings/keys` path.
4. Click `Add Key` to add an SSH key.

### Expected results

Gitea should prompt me for an SSH key.

### Observed results

Clicking the `Add Key` button has no effect.

### Other notes

Putting Tor Browser into "Safer" security mode, which enables JavaScript, results in the `Add Key` button working as intended.  This also affects GPG keys; not sure if I should open a separate bug for that.

## Screenshots

![Gitea-Add-SSH-Key-Broken-with-JS-Disabled](https://user-images.githubusercontent.com/244188/89553907-aa2d1380-d7fd-11ea-8efe-c8e1a96bb96c.png)

**Comment by zeripath** [comment]
Gitea requires JS to function. There are multiple parts of the site that will not function without JS.
