### ISSUE TITLE
Proposal - api - add more details to "type StopWatch" [WIP]

### ISSUE THREAD

**Issue by alltagshack** [go-gitea/gitea#12457]
- Gitea version (or commit ref): 96add8c319bd8299bfb8fdd4d98c6f71407e2475
- Git version: 
- Operating system: Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

It is not possible to get more info via swagger API for a "StopWatch" (especially the repository assigned to its issue) after a API GET request `/user/stopwatches`. Actual I am getting this StopWatch type after a request:
```
{
  created        string($date-time)
  issue_index  integer($int64)
}
```
The issue index is assigned to a repo, but repo data is not part of the type/data. I want to change this type to:

```
{
  created | string($date-time)
  issue_index  integer($int64)
  issue_title  string
  repo_name  string
  repo_owner_name  string
}
```

here my fork: https://github.com/no-go/gitea

### Possible problems after that "hack"

- Other Code, that suggests the old/reduced `type StopWatch`
- Security problems: Access Issue data to a StopWatch, but user is not allowed to see the issue/repo anymore

**Comment by no-go** [comment]
Please find someone to review and test my pull request :-)

**Comment by no-go** [comment]
Please find someone to review and test my pull request :-)

**Comment by no-go** [comment]
:-D
