### ISSUE TITLE
Sending emails Bug

### ISSUE THREAD

**Issue by suyanlin** [go-gitea/gitea#12456]
- Gitea version (or commit ref):1.12.3
- Git version:2.22.0
- Operating system:CentOS7.8
- Database :MySql8.0.20
- Can you reproduce the bug at https://try.gitea.io:No

## Description
Sending emails for the first test will fail and prompt "Invalid csrf token."，Normal at other times。

**Comment by bagasme** [comment]
@suyanlin where are mailer settings?

**Comment by lunny** [comment]
Closed as absent detail information. Please feel free to reopen it.
