### ISSUE TITLE
gitea not send tag events to webhook wen sync mirror 

### ISSUE THREAD

**Issue by fanux** [go-gitea/gitea#12482]
- Gitea version (or commit ref): v1.12.3
- Git version:
- Operating system: centos7
![image](https://user-images.githubusercontent.com/8912557/90142082-84c87880-ddae-11ea-9c45-f92d717526bc.png)
![image](https://user-images.githubusercontent.com/8912557/90142175-a6c1fb00-ddae-11ea-9eed-30858d5aa70e.png)
![image](https://user-images.githubusercontent.com/8912557/90142258-bc372500-ddae-11ea-9e73-4aa7b5ca3ddc.png)

1. Creaet gitea mirror from gitlab
2. Create a webhook on gitea
3. Push tag to gitlab
4. Sync on gitea 
5. The git tag event not send to the webhook

**Comment by dbowring** [comment]
Adding a comment to keep this alive, this is also present in `1.12.15`. It's possibly related that the webhook isn't fired for forced pushes (rewrites).
