### ISSUE TITLE
View caching old data after update file in repository

### ISSUE THREAD

**Issue by yukisnowflake** [go-gitea/gitea#12484]
- Gitea version (or commit ref): 1.12.1
- Git version: never mind
- Operating system: Ubuntu 18.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description
When I update a file, the old content remains in place, and the new one can only be viewed in `/:org/:name/commit/:ID`

## Screenshots
Data to be changed
![image](https://user-images.githubusercontent.com/32297717/90166803-3322ec80-ddb4-11ea-8a32-eea1c4fbe34c.png)

Modified data
![image](https://user-images.githubusercontent.com/32297717/90166824-3a49fa80-ddb4-11ea-8759-71251a4be1ba.png)

And i re-login to another user (why???)
- My account
![image](https://user-images.githubusercontent.com/32297717/90166965-75e4c480-ddb4-11ea-96f6-dfdc1edcbfab.png)

- When viewing old content
![image](https://user-images.githubusercontent.com/32297717/90167007-88f79480-ddb4-11ea-8f97-30f5179388bc.png)

**Comment by vladciphersky** [comment]
Hah, thanks for help. Really.
