### ISSUE TITLE
[1.12] - Can't merge PR with API

### ISSUE THREAD

**Issue by Tchoupinax** [go-gitea/gitea#12496]
- Gitea version (or commit ref): 1.12.3
- Git version: 2.28.0 (on my computer)
- Operating system: MacOS / Linux
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No (It works with try.gitea.io
  - [ ] Not relevant
- Log gist:

## Description

I'm not able to merge a PR via the API

```bash
あ→ curl -X POST "https://my.server.com/api/v1/repos/organization/myrepo/pulls/80/merge?access_token=mytoken" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"Do\": \"merge\", \"MergeMessageField\": \"string\", \"MergeTitleField\": \"string\", \"force_merge\": true}"

# On my server
[Macaron] 2020-08-16 08:35:22: Completed POST /api/v1/repos/organization/myrepo/pulls/80/merge?access_token=40571200ebb3e7a1144ae50898d5790b8bdd1b3a 405 Method Not Allowed in 118.893987ms
```
However, i made the test on try.gitea.io and it works perfectly.. 

```bash
curl -X POST "https://try.gitea.io/api/v1/repos/toto/test/pulls/1/merge?access_token=myToken" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"Do\": \"merge\", \"MergeMessageField\": \"string\", \"MergeTitleField\": \"string\", \"force_merge\": true}"
```

Is the version 1.13 fixing the issue ?

**Comment by zeripath** [comment]
What is the server response?

All of our errors should give a JSON output: `{"Message":"message", "URL": "url"}`

**Comment by Tchoupinax** [comment]
There was not answer, it is why i were on my server to inspect the logs

**Comment by 6543** [comment]
@Tchoupinax if a InternalServerError ocure the API only will tell the error if it is in Devmode vor sec-reasons

so you either have to switch to devmode on the instance or look at the logs

**Comment by Tchoupinax** [comment]
Thank you for the tip !

But it appears that i have not returned answer with my issue.

When i change the name of my repo for a wrong name, i have the following issue
```
{"documentation_url":"https://my.server.com/api/swagger","errors":null,"message":"Not Found"}
```

When i remove one character in my token, i have the following issue
```
{"message":"Only signed in user is allowed to call APIs."}
```

But with the "correct" query, i have no returned answer. Always the same "405 Method not allowed" in the server logs. (And this query is copied from Swagger page :) )

**Comment by zeripath** [comment]
Then you are getting the error reported from either L680:

https://github.com/go-gitea/gitea/blob/ec48618d40c12cc14e902062f6393ebeb9b0e365/routers/api/v1/repo/pull.go#L679

or L732 here:

https://github.com/go-gitea/gitea/blob/ec48618d40c12cc14e902062f6393ebeb9b0e365/routers/api/v1/repo/pull.go#L730-L734


So either the pr is not mergable yet, is already merged or is a work in progress, or the provided merge style is invalid. Not sure why that is the case at the moment.

Clearly those lines should report back which one is the problem - it's just bad form to not say.

**Comment by Tchoupinax** [comment]
Ok, thank you a lot for diving into the code. What i did not understand is that all seem to be good for the PR and when i click on the merge button with the UI, it works as expected.

My settings is configured as this
![image](https://user-images.githubusercontent.com/9136206/90488312-08ca8980-e13c-11ea-810a-7ec221eed922.png)

Maybe the ```"Do": "Merge"``` action in the payload means the "commit merging" action and like i deactivated it, it does not work. Should i do a ```"Do": "Squash"``` ? (I juste realized it)

**Comment by Tchoupinax** [comment]
Ok, it is that. I'm sorry to did not realize it before ><'

Maybe the action to improve this issue is to make a more specific log for this kind of error ?

Anyway it works well !

**Comment by zeripath** [comment]
OK I'm going to close this issue - but I've sent a PR that should mean we return something a lot clearer in future.

**Comment by Tchoupinax** [comment]
Thank you a lot 👍
