### ISSUE TITLE
Add NPM AUDIT FIX to resolve node vulns (200+) to makefile?

### ISSUE THREAD

**Issue by symgryph** [go-gitea/gitea#12494]
Simple fix would be to add 'npm audit fix' after make build to remove most of the node vulns.

**Comment by silverwind** [comment]
Dependency updates must be a concious choice and need to be tested, not something that runs automatically. I try to update regularily. Most if not all of these "vulnerabilities" are not really applicable to our use case anyways.

**Comment by symgryph** [comment]
I think most of my just noticing that there was 232 of them made me blink a couple times

**Comment by silverwind** [comment]
The master branch [is clean](https://drone.gitea.io/go-gitea/gitea/28933/1/2). Older release branches probably have accumulated some of these "issues" and I guess we would not be opposed to PRs that does `npm audit fix` on those branches. It will certainly need to reviewed in case there are any breaking changes.
