### ISSUE TITLE
[Question] Can't use Kanban board in existing repo

### ISSUE THREAD

**Issue by a1012112796** [go-gitea/gitea#12504]
- Gitea version (or commit ref): 1.13.0+dev-419-g4027c5dd7
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
As title.
## Screenshots

in existing repo
![image](https://user-images.githubusercontent.com/25342410/90382263-1be44780-e0b1-11ea-83a3-f754e911b3ff.png)

in new repo:
![image](https://user-images.githubusercontent.com/25342410/90382370-3f0ef700-e0b1-11ea-8ce4-c57f56dcfeac.png)

## solution
That's because ``projects`` units are not auto enabled in existing repo, so you should enable it manually if you want to use it. example view:
![tmp](https://user-images.githubusercontent.com/25342410/90386773-a2038c80-e0b7-11ea-8e0c-36116da3447c.gif)

**Comment by a1012112796** [comment]
@6543 @adelowo Please have a look, Thanks.

**Comment by a1012112796** [comment]
I'm sorry. I haven't checked it carefully. should enable it manually a first before using the kankan Board in existing reos. 
![image](https://user-images.githubusercontent.com/25342410/90384280-e4c36580-e0b3-11ea-99c9-6884130fe748.png)

**Comment by 6543** [comment]
@a1012112796 this is intended

Because:
 * makes migration step easyer
 * It's easyer to enable on-demand on old as disable it on all old repos

**Comment by a1012112796** [comment]
@lunny maybe need question label. Thanks :)
