### ISSUE TITLE
Add Healthy check

### ISSUE THREAD

**Issue by memiks** [go-gitea/gitea#12502]
Hi Gitea Team,

To improve usage in Docker after Entrypoint line you could add an Health check line :

https://github.com/go-gitea/gitea/blob/d285b5d35a44bf9fde0682532aeef9550f78cf83/Dockerfile#L62

`HEALTHCHECK --interval=30s --timeout=3s \
  CMD /bin/s6-svok /etc/s6/gitea || exit 1`

BR,
Memiks

**Comment by Toucan-Sam** [comment]
Dupe of #12443 
But also has suggested solution.
