### ISSUE TITLE
Gitea Backup Script for Docker

### ISSUE THREAD

**Issue by bst27** [go-gitea/gitea#12519]
## Description
I created a **Gitea backup script for Docker**: 
https://gist.github.com/bst27/1bf1590c5ec0b8b1c331d2a03e237894

Do you think it's worth to have it mentioned in the **Backup and Restore** section of the Gitea docs?

**Comment by quoing** [comment]
Some ideas:
1. not everyone container is "gitea_server_1", would be nice to change this to script variable or as script parameter
2. would be good to prevent running the script multiple time, either by checking presence of /tmp/gitea-dump.zip or some kind of lock file

**Comment by wxiaoguang** [comment]
There is https://docs.gitea.io/en-us/backup-and-restore/#using-docker-dump
