### ISSUE TITLE
Show outdated comments in pull request

### ISSUE THREAD

**Issue by melmus** [go-gitea/gitea#12523]
- Gitea version (or commit ref):
1.13.0+dev-295-g16980d13c

- Git version:
2.17.1

- Operating system: 
Ubuntu 18.04.3 LTS

- Database (use `[x]`):
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:

## Description
If I get comment and make change, this comment will close, and I need to click button "**Show outdated**" for see it. It is a problem. I must see the comments.

## Screenshots
![1](https://user-images.githubusercontent.com/15018126/90522502-772b3e00-e174-11ea-8163-dd113fbf84b4.png)
![2](https://user-images.githubusercontent.com/15018126/90522507-78f50180-e174-11ea-866c-acff02f884dd.png)

**Comment by lafriks** [comment]
It becomes outdated if someone pushes commit that changes commented line. It is intentional so that it could be easy to see review comments that still needs to be fixed and that are already fixed. You still can see comment by clicking on `Show outdated`

**Comment by melmus** [comment]
@lafriks, Yes, you are right. But comment does not resolved. Clicking the button every time is not comfortable.

**Comment by deptyped** [comment]
The button to make the selected outdated comment unresolved and active again will be useful.

**Comment by davidglezz** [comment]
It would be useful to show if it is resolved or not without having to click "show outdated" btn

**Comment by lakostin** [comment]
i agree, its very annoying when all the comments are hidden!!! i can decide by myself if the comment to the necessary line is outdated or not!

**Comment by zeripath** [comment]
This would be a very easy pr

**Comment by lakostin** [comment]
> This would be a very easy pr

is there any way to force its creation?

**Comment by techknowlogick** [comment]
> is there any way to force its creation?

start a bounty?

**Comment by lakostin** [comment]
> > is there any way to force its creation?
> 
> start a bounty?

you're welcome
