### ISSUE TITLE
Can’t choose branch for merge.

### ISSUE THREAD

**Issue by melmus** [go-gitea/gitea#12525]
- Gitea version (or commit ref):
1.13.0+dev-295-g16980d13c

- Git version:
2.17.1

- Operating system:
Ubuntu 18.04.3 LTS

- Database (use `[x]`):
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:

## Description

In the Pull Request if you go to Files Changed and choose “editing”, you can’t choose branch for merge.

List of browsers:
- Google Chrome Version 84.0.4147.105 (Official Build) (64-bit), 84.0.4147.125 (Official Build) (64-bit)
- Opera Version: 70.0.3728.106 (64-bit), 70.0.3728.119 (64-bit)
- Safari Version: 13.1.2 (13609.3.5.1.5) (64-bit), 13.1.2 (15609.3.5.1.3) (64-bit)
- Firefox Version: 79.0 (64-bit)
## Screenshots
![1](https://user-images.githubusercontent.com/15018126/90532974-8c0dce80-e180-11ea-99f3-220574ce2929.png)
![2](https://user-images.githubusercontent.com/15018126/90532978-8d3efb80-e180-11ea-9694-d1a00d0b4bbf.png)
![3](https://user-images.githubusercontent.com/15018126/90532979-8d3efb80-e180-11ea-9180-42f2b4b978a0.png)

**Comment by jolheiser** [comment]
It lost the `z-index` battle. 😢 

Branch selection
![z](https://user-images.githubusercontent.com/42128690/90536660-f7847b80-e141-11ea-928f-6202ee789e6b.png)

vs sticky details
https://github.com/go-gitea/gitea/blob/61a172900e871e4151c804f4dc242e8c4895a4d3/web_src/less/_repository.less#L1582

I'm not sure the best way to fix it other than fighting `z-index` with a higher `z-index`, but that feels almost as dirty as an `!important` battle.

@silverwind @CirnoT Thoughts? You two seem to have a better grasp than I do when it comes to these things.

**Comment by silverwind** [comment]
I'd say that diff bar should not set a `z-index` when it's not in the sticky state, avoiding this issue altogether.

**Comment by CirnoT** [comment]
>I'd say that diff bar should not set a z-index when it's not in the sticky state

That would require JavaScript hacks which we wanted to avoid.

>I'm also not sure why the sticky details are at 800. Since we can't really change semantic, the conclusion would be to change the sticky details to <=10, but I'm not sure what else that might break in a z-index battle.

Quick test shows that it can be safely reduced to 8.
