### ISSUE TITLE
Icon has disappeared or has been replaced by a hexadecimal code after upgrading to 1.12.3

### ISSUE THREAD

**Issue by CrustyApplesniffer** [go-gitea/gitea#12539]
- Gitea version (or commit ref): 1.12.3
- Git version: 2.10.2.windows.1
- Operating system: Windows 2008 R2
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:

## Description

Last week I've upgraded my onsite gitea to version 1.12.3
I notice the ```+``` icon disappeared and the notification bell icon has been replace with an hexadecimal code.

## Screenshots

![image](https://user-images.githubusercontent.com/37656975/90732582-9be5f980-e2cb-11ea-85a2-01b74192ce3c.png)

**Comment by zeripath** [comment]
Check your custom templates are correct.

**Comment by CrustyApplesniffer** [comment]
It seems to be the cause ... 
I removed my custom templates and all start to work.
I'll check my template tomorrow.

Thank you
