### ISSUE TITLE
Cleaner UI for explore page

### ISSUE THREAD

**Issue by pgaskin** [go-gitea/gitea#1253]
Does anyone else like my cleaner design? If so, I will submit a PR.

Screenshots on try.gitea.io

| Old | New |
| - | - |
|![screenshot_00005](https://cloud.githubusercontent.com/assets/13909717/23919233/73a7e6b8-08cc-11e7-9b49-c8a01f5a527a.png)|![screenshot_00004](https://cloud.githubusercontent.com/assets/13909717/23919232/73a24226-08cc-11e7-8d5d-fc074e467242.png)|
|![screenshot_00007](https://cloud.githubusercontent.com/assets/13909717/23919289/b298dfd0-08cc-11e7-9c95-2e858a601f3e.png)|![screenshot_00006](https://cloud.githubusercontent.com/assets/13909717/23919288/b295e35c-08cc-11e7-8b0b-a29b62d0908f.png)|
|![screenshot_00009](https://cloud.githubusercontent.com/assets/13909717/23919340/e0f577da-08cc-11e7-813a-c933d850e4da.png)|![screenshot_00008](https://cloud.githubusercontent.com/assets/13909717/23919341/e0f5cbf4-08cc-11e7-9f7c-4d9baafe3f39.png)|

**Comment by pgaskin** [comment]
How I did it:

1. Move content and menu out of grid
2. Menu css: justify-content: center;margin-bottom: 10px;
3. Menu classes: ui secondary pointing tabular top attached borderless menu navbar
4. Remove `explore:` header from menu


To make it look like this so you can try it, use the following js (yes, I know it does not do the exact changes above, but it essentially does the same thing):
````javascript
$(".explore>.ui.container>.ui.grid").removeClass("grid");
$(".four.wide.column>.menu").attr("style", "justify-content: center;margin-bottom: 10px;").attr("class", "ui secondary pointing tabular top attached borderless menu navbar");
$(".ui.menu .header.item").remove();
````

**Comment by pgaskin** [comment]
This modification will also make the ui look better on smaller screens.

**Comment by tboerger** [comment]
Basically it looks better, but the horizontal nav can be done better

**Comment by pgaskin** [comment]
@tboerger What should I change?

**Comment by tboerger** [comment]
Maybe a different background on the full width for this top navigation

**Comment by pgaskin** [comment]
@tboerger Like this:
![screenshot_00011](https://cloud.githubusercontent.com/assets/13909717/23920368/be1e7c08-08d0-11e7-8168-0d14a6fa6477.png)


After moving it above the .ui.container, I added the css:
````css
justify-content: center;
padding-top: 15px;
margin-top: -15px;
margin-bottom: 15px;
background-color: #FAFAFA;
border-width: 1px;
````

**UPDATED**: according to the next comment

**Comment by tboerger** [comment]
Yes, and maybe more space around the search

**Comment by tboerger** [comment]
I can't remember the html structure, but is it easily possible to list two columns on large displays?

**Comment by pgaskin** [comment]
@tboerger Done, see new screenshot

**Comment by pgaskin** [comment]
@tboerger not easily

**Comment by pgaskin** [comment]
@tboerger Should I submit a PR now?

**Comment by tboerger** [comment]
From my side: yes.

**Comment by pgaskin** [comment]
https://github.com/go-gitea/gitea/pull/1255

**Comment by lcges** [comment]
In general is good. 
@geek1011 what do you think about split in half use Grids, sections: user, organization, repository)?
Will be better filled free space.

**Comment by lunny** [comment]
Maybe aligned left is better.
