### ISSUE TITLE
Multiple review textarea after comment code

### ISSUE THREAD

**Issue by davidglezz** [go-gitea/gitea#12573]
- Gitea version (or commit ref): 12.3 +
- Git version: 
- Operating system: Ubuntu
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
Adding or editing a code comment causes multiple textarea fields to appear in the review button popover.

## Screenshots
![image](https://user-images.githubusercontent.com/194784/90975369-cf2ac180-e533-11ea-8683-88bf8a126c42.png)

**Comment by zeripath** [comment]
does this still occur on 1.12.5? I'm fairly certain I've already fixed this.

**Comment by davidglezz** [comment]
Sorry, the problem stills in 1.12.5.
Adding comments seems to work fine, but editing one shows that the problem is still present.

**Comment by zeripath** [comment]
Can you get it to occur on try?

**Comment by davidglezz** [comment]
I have never compiled gitea, is there any way, for example with a docker, to compile without having to install all the tools?
https://docs.gitea.io/en-us/install-from-source/

**Comment by zeripath** [comment]
Oh actually thinking on I think the attached pr is likely fixing a different problem... your problem appears to be in the review comment box on the files page of a pr right?


In terms of compiling Gitea - unfortunately you'd need to install the tools. Were you thinking of compiling on doze?

**Comment by davidglezz** [comment]
> Oh actually thinking on I think the attached pr is likely fixing a different problem... your problem appears to be in the review comment box on the files page of a pr right?

Yes

**Comment by zeripath** [comment]
Can you tell me exactly how to replicate on try.gitea.io ? I'm struggling to replicate this.

**Comment by davidglezz** [comment]
Cant reproduce in Gitea Version: 1.13.0+dev-737-gc584364b9
https://try.gitea.io/davidglezz2/issue-12573/

**Comment by davidglezz** [comment]
But the problem may not appear because a javascript error occurs when saving or canceling the comment edition.
![image](https://user-images.githubusercontent.com/194784/95189912-d3066080-07ce-11eb-89e0-8b92cd4ee749.png)

**Comment by zeripath** [comment]
OK the emit error appears to be another issue with dropzone that's quite easy to fix and I've copied it in to #13036

**Comment by wxiaoguang** [comment]
Outdated
