### ISSUE TITLE
`$.i18n.Tr` should not output fallback strings in production mode

### ISSUE THREAD

**Issue by silverwind** [go-gitea/gitea#12579]
Extracted from https://github.com/go-gitea/gitea/pull/12564

If an invalid translation key is passed, the function will render strings like `signing.wont_sign.%!s(<nil>)` into HTML which is ugly. We should only do that when gitea is in development mode, otherwise output empty string only.

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
I believe  #12581 solves this in a way..

**Comment by silverwind** [comment]
The PR solves that one case but similar cases can pop up somewhere else anytime.

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
> The PR solves that one case but similar cases can pop up somewhere else anytime.

That's true.
Sorry, my bad 🙈

**Comment by wxiaoguang** [comment]
The fallback string should always be outputed, otherwise users would see nothing and know nothing, they would report issues like "I see empty UI", which is worse than reporting the invalid translation key.

And the i18n module has been refactored recently.
