### ISSUE TITLE
Gitea apparently not respecting set cache TTL

### ISSUE THREAD

**Issue by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [go-gitea/gitea#12587]
- Gitea version (or commit ref): [`1.13.0+dev-462-gee047312a`](https://github.com/go-gitea/gitea/commit/ee047312a)
- Git version: `2.28.0`
- Operating system: Arch Linux (`linux-5.8.1-arch1-2`)
- Database:
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant

## Description

There seems to be a discrepancy in how Gitea handles cache TTL, or at least in how it displays the info.
As illustrated below, WebUI shows the cache TTL to be `16h0m0s`, whereas it's clearly set to something else in the `app.ini` (in this case `72h`, doesn't work with any other value I tried).

Which brings me to the question.
Does Gitea not respect the value from the config or is there a hardcoded value somewhere that just gets displayed in the WebUI?
Or is it just me? 🙈 

## Screenshots
WebUI:
![webui](https://user-images.githubusercontent.com/61180606/91057574-aab01180-e627-11ea-8ab2-77b0453dcc6e.png)

`app.ini`:
![config](https://user-images.githubusercontent.com/61180606/91057527-966c1480-e627-11ea-9887-cc43f00fd849.png)

**Comment by techknowlogick** [comment]
For anyone looking to fix this, it could be the following line https://github.com/go-gitea/gitea/blob/master/modules/setting/cache.go#L38 needing "\`ini:"ITEM_TTL"\`" added to end of the line (please test that this changes the value in admin section.

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
> For anyone looking to fix this, it could be the following line https://github.com/go-gitea/gitea/blob/master/modules/setting/cache.go#L38 needing "`ini:"ITEM_TTL"`" added to end of the line (please test that this changes the value in admin section.

Thanks for the reply.
Let me see.

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
Alright, this didn't work for me.
![image](https://user-images.githubusercontent.com/61180606/91149196-11cad600-e6bb-11ea-9258-ee4dc240b2f9.png)
Fails to build.
It says it's due to a missing comma at the end
Adding a comma to the end of the line makes it fail to build with this:
![image](https://user-images.githubusercontent.com/61180606/91149385-4b034600-e6bb-11ea-9449-ae21b00d2528.png)

**Comment by warnat** [comment]
First of all: I am no GO programm guy !
But I can see two different entries for TTL in the ini file:
one inside the section [cache] and one inside [cache.last_commit]
and as far as I can see last_commit-TTL, is taken from ini like this: (line 28-32, specific line 32)
```go
LastCommit struct {
	Enabled      bool
	TTL          time.Duration `ini:"ITEM_TTL"`
	CommitsCount int64
} `ini:"cache.last_commit"`
```
shouldn't there be this in line 15-21 (added  ``` `ini:"cache"` ``` at the end of 21)  ?
```go
type Cache struct {
	Enabled  bool
	Adapter  string
	Interval int
	Conn     string
	TTL      time.Duration `ini:"ITEM_TTL"`  
}  `ini:"cache"` 
```

line 38 seems to be only program generated defaults.

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
> First of all: I am no GO programm guy !
> But I can see two different entries for TTL in the ini file:
> one inside the section [cache] and one inside [cache.last_commit]
> and as far as I can see last_commit-TTL, is taken from ini like this: (line 28-32, specific line 32)
> 
> ```go
> LastCommit struct {
> 	Enabled      bool
> 	TTL          time.Duration `ini:"ITEM_TTL"`
> 	CommitsCount int64
> } `ini:"cache.last_commit"`
> ```
> 
> shouldn't there be this in line 15-21 (added `` `ini:"cache"` `` at the end of 21) ?
> 
> ```go
> type Cache struct {
> 	Enabled  bool
> 	Adapter  string
> 	Interval int
> 	Conn     string
> 	TTL      time.Duration `ini:"ITEM_TTL"`  
> }  `ini:"cache"` 
> ```
> 
> line 38 seems to be only program generated defaults.

I am no GO programmer myself :)
it's possible we're missing something.
you are right that line 38 just sets the default value to 16 hours, your suggestion to add "`ini:"cache"`" after the `type Cache` declaration didn't work, though.
it's either there's something missing or we're missing something or both :(

**Comment by techknowlogick** [comment]
ah, no you are both right. I messed up when looking at the code and @warnat is right it'll fail to compile. I should've spent longer attempting to point someone in right direction.

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
> ah, no you are both right. I messed up when looking at the code and @warnat is right it'll fail to compile. I should've spent longer attempting to point someone in right direction.

no worries, I'll wait here for the next set of instructions and may attempt to fix it
