### ISSUE TITLE
fatal: the remote end hung up unexpectedly fatal: early EOF fatal: index-pack failed

### ISSUE THREAD

**Issue by shijunti19** [go-gitea/gitea#12584]
- Gitea version (or commit ref): : 1.12.3
- Git version:newest
- Operating system:linux
- Database (use `[x]`):SQLite
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

git 未能顺利结束 (退出码 128) (26438 ms @ 2020/8/24 16:28:46)

## Screenshots

![image](https://user-images.githubusercontent.com/5392211/91022017-2e1d3300-e627-11ea-8888-a16df747b348.png)

![image](https://user-images.githubusercontent.com/5392211/91022057-3a08f500-e627-11ea-8942-fd04d186d2a8.png)

**Comment by shijunti19** [comment]
* upload completely sent off: 175 out of 175 bytes
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Type: application/x-git-upload-pack-result
< Set-Cookie: lang=en-US; Path=/; Max-Age=2147483647
< Set-Cookie: i_like_gitea=b0ffc3713ce56658; Path=/; HttpOnly
< Set-Cookie: _csrf=qz6MrOzaOeq8OaE44qR9UeCFsqc6MTU5ODI1ODQwNzM1NTk5MTc4Nw; Path=/; Expires=Tue, 25 Aug 2020 08:40:07 GMT; HttpOnly
< X-Frame-Options: SAMEORIGIN
< Date: Mon, 24 Aug 2020 08:40:07 GMT
< Transfer-Encoding: chunked
<
remote: Enumerating objects: 7759, done.
remote: Counting objects: 100% (7759/7759), done.
remote: Compressing objects: 100% (6004/6004), done.
16:40:06.282202 run-command.c:663       trace: run_command: git index-pack --stdin -v --fix-thin '--keep=fetch-pack 27376 on xiaolu' --check-self-contained-and-connected --pack_header=2,7759
16:40:06.296202 exec-cmd.c:237          trace: resolved executable dir: E:/Program Files/Git/mingw64/libexec/git-core
16:40:06.299201 git.c:442               trace: built-in: git index-pack --stdin -v --fix-thin '--keep=fetch-pack 27376 on xiaolu' --check-self-contained-and-connected --pack_header=2,7759
* transfer closed with outstanding read data remaining KiB/s
* Closing connection 0
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

**Comment by zeripath** [comment]
Something seems to be causing your Gitea process to be killed and restarted but the logs aren't shown.

We need the Gitea logs.

Are your main Gitea logs sent to a file? Can we see that?

What is your logging configuration?

**Comment by shijunti19** [comment]
@zeripath 
I found out that he didn't report any mistakes and then stopped
Every time I upgrade, I replace the file and run it

![image](https://user-images.githubusercontent.com/5392211/91114104-af250a80-e6b9-11ea-8103-195de5595d3c.png)


or supervisord:

![image](https://user-images.githubusercontent.com/5392211/91114339-412d1300-e6ba-11ea-92ef-8556926cbfa5.png)
![image](https://user-images.githubusercontent.com/5392211/91114354-4b4f1180-e6ba-11ea-8806-55573c8683d1.png)
![image](https://user-images.githubusercontent.com/5392211/91114417-73d70b80-e6ba-11ea-98b5-b389281aaace.png)

[program:gitea]
directory=/xiaolu/soft/gitea
command=/xiaolu/soft/gitea/gitea web
autostart=true
autorestart=true
startsecs=10
stdout_logfile=/xiaolu/soft/gitea/log/stdout.log
stdout_logfile_maxbytes=1MB
stdout_logfile_backups=10
stdout_capture_maxbytes=1MB
stderr_logfile=/xiaolu/soft/gitea/log/stderr.log
stderr_logfile_maxbytes=1MB
stderr_logfile_backups=10
stderr_capture_maxbytes=1MB
user = git
environment = HOME="/xiaolu/soft/gitea", USER="git"
------------------

stdout.log:
[36m2020/08/25 10:01:57 [0m[32mcmd/web.go:107:[32mrunWeb()[0m [1;32m[I][0m Starting Gitea on PID: [1m4573[0m
[36m2020/08/25 10:01:57 [0m[32m...dules/setting/git.go:93:[32mnewGit()[0m [1;32m[I][0m Git Version: [1m2.23.0[0m, Wire Protocol [1mVersion 2[0m Enabled
[36m2020/08/25 10:01:57 [0m[32mrouters/init.go:118:[32mGlobalInit()[0m [1;36m[T][0m AppPath: [1m/xiaolu/soft/gitea/gitea[0m
[36m2020/08/25 10:01:57 [0m[32mrouters/init.go:119:[32mGlobalInit()[0m [1;36m[T][0m AppWorkPath: [1m/xiaolu/soft/gitea[0m
[36m2020/08/25 10:01:57 [0m[32mrouters/init.go:120:[32mGlobalInit()[0m [1;36m[T][0m Custom path: [1m/xiaolu/soft/gitea/custom[0m
[36m2020/08/25 10:01:57 [0m[32mrouters/init.go:121:[32mGlobalInit()[0m [1;36m[T][0m Log path: [1m/xiaolu/soft/gitea/log[0m
[Macaron] 2020-08-25 10:01:59: Started GET /user/events for 115.198.98.103
[Macaron] 2020-08-25 10:01:59: Started GET /user/events for 121.236.110.62
[Macaron] 2020-08-25 10:01:59: Started GET /user/events for 58.16.230.41


-----------------
gitea.log:

2020/08/25 10:02:29 ...rm/session_schema.go:339:Sync2() [W] Table review column type db type is TEXT, struct type is INTEGER
2020/08/25 10:02:29 ...m.io/xorm/core/db.go:154:QueryContext() [I] [SQL] SELECT sql FROM sqlite_master WHERE type='table' and name = ? [oauth2_application] - 32.668µs
2020/08/25 10:02:29 ...m.io/xorm/core/db.go:154:QueryContext() [I] [SQL] SELECT sql FROM sqlite_master WHERE type='index' and tbl_name = ? [oauth2_application] - 27.325µs
2020/08/25 10:02:29 ...m.io/xorm/core/db.go:154:QueryContext() [I] [SQL] SELECT sql FROM sqlite_master WHERE type='table' and name = ? [oauth2_authorization_code] - 27.225µs
2020/08/25 10:02:29 ...m.io/xorm/core/db.go:154:QueryContext() [I] [SQL] SELECT sql FROM sqlite_master WHERE type='index' and tbl_name = ? [oauth2_authorization_code] - 22.581µs
2020/08/25 10:02:29 ...m.io/xorm/core/db.go:154:QueryContext() [I] [SQL] SELECT sql FROM sqlite_master WHERE type='table' and name = ? [oauth2_grant] - 76.824µs
2020/08/25 10:02:29 ...m.io/xorm/core/db.go:154:QueryContext() [I] [SQL] SELECT sql FROM sqlite_master WHERE type='index' and tbl_name = ? [oauth2_grant] - 34.739µs
2020/08/25 10:02:29 ...m.io/xorm/core/db.go:154:QueryContext() [I] [SQL] SELECT sql FROM sqlite_master WHERE type='table' and name = ? [task] - 30.794µs
2020/08/25 10:02:29 ...m.io/xorm/core/db.go:154:QueryContext() [I] [SQL] SELECT sql FROM sqlite_master WHERE type='index' and tbl_name = ? [task] - 38.183µs
2020/08/25 10:02:29 ...m.io/xorm/core/db.go:154:QueryContext() [I] [SQL] SELECT sql FROM sqlite_master WHERE type='table' and name = ? [language_stat] - 27.701µs
2020/08/25 10:02:29 ...m.io/xorm/core/db.go:154:QueryContext() [I] [SQL] SELECT sql FROM sqlite_master WHERE type='index' and tbl_name = ? [language_stat] - 23.922µs
2020/08/25 10:02:29 ...m.io/xorm/core/db.go:154:QueryContext() [I] [SQL] SELECT sql FROM sqlite_master WHERE type='table' and name = ? [email_hash] - 27.13µs
2020/08/25 10:02:29 ...m.io/xorm/core/db.go:154:QueryContext() [I] [SQL] SELECT sql FROM sqlite_master WHERE type='index' and tbl_name = ? [email_hash] - 33.623µs
2020/08/25 10:02:29 ...m.io/xorm/core/db.go:154:QueryContext() [I] [SQL] SELECT sql FROM sqlite_master WHERE type='table' and name = ? [topic] - 25.943µs
2020/08/25 10:02:29 ...m.io/xorm/core/db.go:154:QueryContext() [I] [SQL] SELECT sql FROM sqlite_master WHERE type='index' and tbl_name = ? [topic] - 26.289µs
2020/08/25 10:02:29 ...m.io/xorm/core/db.go:154:QueryContext() [I] [SQL] SELECT sql FROM sqlite_master WHERE type='table' and name = ? [repo_topic] - 23.378µs
2020/08/25 10:02:29 ...m.io/xorm/core/db.go:154:QueryContext() [I] [SQL] SELECT sql FROM sqlite_master WHERE type='index' and tbl_name = ? [repo_topic] - 34.067µs
2020/08/25 10:02:29 routers/init.go:133:GlobalInit() [I] ORM engine initialization successful!
2020/08/25 10:02:29 ...m.io/xorm/core/db.go:154:QueryContext() [I] [SQL] SELECT name FROM sqlite_master WHERE type='table' [] - 38.487µs
2020/08/25 10:02:29 ...m.io/xorm/core/db.go:154:QueryContext() [I] [SQL] SELECT sql FROM sqlite_master WHERE type='table' and name = ? [oauth2_session] - 24.038µs
2020/08/25 10:02:29 ...m.io/xorm/core/db.go:154:QueryContext() [I] [SQL] SELECT sql FROM sqlite_master WHERE type='index' and tbl_name = ? [oauth2_session] - 26.912µs
2020/08/25 10:02:29 ...m.io/xorm/core/db.go:154:QueryContext() [I] [SQL] SELECT `id`, `type`, `name`, `is_actived`, `is_sync_enabled`, `cfg`, `created_unix`, `updated_unix` FROM `login_source` WHERE (is_actived = ? and type = ?) [true 6] - 55.345µs
2020/08/25 10:02:29 ...m.io/xorm/core/db.go:277:ExecContext() [I] [SQL] DELETE FROM `deleted_branch` WHERE (deleted_unix < ?) [1598234549] - 98.138µs
2020/08/25 10:02:29 ...m.io/xorm/core/db.go:277:ExecContext() [I] [SQL] INSERT INTO `notice` (`type`,`description`,`created_unix`) VALUES (?, ?, ?) [2 Cron: Clean-up deleted branches has finished 1598320949] - 11.871487ms
2020/08/25 10:02:29 ...m.io/xorm/core/db.go:154:QueryContext() [I] [SQL] SELECT repo.id FROM `repository` repo WHERE repo.num_watches!=(SELECT COUNT(*) FROM `watch` WHERE repo_id=repo.id AND mode<>2) [] - 160.036µs
2020/08/25 10:02:29 ...m.io/xorm/core/db.go:154:QueryContext() [I] [SQL] SELECT `id`, `owner_id`, `owner_name`, `lower_name`, `name`, `description`, `website`, `original_service_type`, `original_url`, `default_branch`, `num_watches`, `num_stars`, `num_forks`, `num_issues`, `num_closed_issues`, `num_pulls`, `num_closed_pulls`, `num_milestones`, `num_closed_milestones`, `is_private`, `is_empty`, `is_archived`, `is_mirror`, `status`, `is_fork`, `fork_id`, `is_template`, `template_id`, `size`, `is_fsck_enabled`, `close_issues_via_commit_in_any_branch`, `topics`, `avatar`, `created_unix`, `updated_unix` FROM `repository` WHERE (id > 0) [] - 239.696µs
2020/08/25 10:02:29 ...m.io/xorm/core/db.go:154:QueryContext() [I] [SQL] SELECT `external_id`, `user_id`, `login_source_id`, `raw_data`, `provider`, `email`, `name`, `first_name`, `last_name`, `nick_name`, `description`, `avatar_url`, `location`, `access_token`, `access_token_secret`, `refresh_token`, `expires_at` FROM `external_login_user` WHERE provider=? ORDER BY login_source_id ASC, external_id ASC LIMIT 100 [github] - 348.755µs
2020/08/25 10:02:29 ...er/issues/indexer.go:142:func2() [I] PID 4706: Initializing Issue Indexer: bleve
2020/08/25 10:02:29 ...m.io/xorm/core/db.go:154:QueryContext() [I] [SQL] SELECT repo.id FROM `repository` repo WHERE repo.num_stars!=(SELECT COUNT(*) FROM `star` WHERE repo_id=repo.id) [] - 137.836µs
2020/08/25 10:02:29 ...m.io/xorm/core/db.go:154:QueryContext() [I] [SQL] SELECT label.id FROM `label` WHERE label.num_issues!=(SELECT COUNT(*) FROM `issue_label` WHERE label_id=label.id) [] - 38.87µs
2020/08/25 10:02:29 ...m.io/xorm/core/db.go:154:QueryContext() [I] [SQL] SELECT `user`.id FROM `user` WHERE `user`.num_repos!=(SELECT COUNT(*) FROM `repository` WHERE owner_id=`user`.id) [] - 46.699µs
2020/08/25 10:02:29 ...m.io/xorm/core/db.go:154:QueryContext() [I] [SQL] SELECT `issue`.id FROM `issue` WHERE `issue`.num_comments!=(SELECT COUNT(*) FROM `comment` WHERE issue_id=`issue`.id AND type=0) [] - 49.537µs
2020/08/25 10:02:29 ...m.io/xorm/core/db.go:154:QueryContext() [I] [SQL] SELECT repo.id FROM `repository` repo WHERE repo.num_closed_issues!=(SELECT COUNT(*) FROM `issue` WHERE repo_id=repo.id AND is_closed=? AND is_pull=?) [true false] - 49.276µs
2020/08/25 10:02:29 ...m.io/xorm/core/db.go:154:QueryContext() [I] [SQL] SELECT repo.id FROM `repository` repo WHERE repo.num_closed_pulls!=(SELECT COUNT(*) FROM `issue` WHERE repo_id=repo.id AND is_closed=? AND is_pull=?) [true true] - 54.238µs
2020/08/25 10:02:29 ...m.io/xorm/core/db.go:154:QueryContext() [I] [SQL] SELECT repo.id FROM `repository` repo WHERE repo.num_forks!=(SELECT COUNT(*) FROM `repository` WHERE fork_id=repo.id) [] - 41.192µs
2020/08/25 10:02:29 ...m.io/xorm/core/db.go:154:QueryContext() [I] [SQL] SELECT `external_id`, `user_id`, `login_source_id`, `raw_data`, `provider`, `email`, `name`, `first_name`, `last_name`, `nick_name`, `description`, `avatar_url`, `location`, `access_token`, `access_token_secret`, `refresh_token`, `expires_at` FROM `external_login_user` WHERE provider=? ORDER BY login_source_id ASC, external_id ASC LIMIT 100 [gitlab] - 27.166297ms
2020/08/25 10:02:29 ...m.io/xorm/core/db.go:277:ExecContext() [I] [SQL] INSERT INTO `notice` (`type`,`description`,`created_unix`) VALUES (?, ?, ?) [2 Cron: Check all repository statistics has finished 1598320949] - 24.516779ms
2020/08/25 10:02:29 ...xer/stats/indexer.go:38:populateRepoIndexer() [I] Populating the repo stats indexer with existing repositories
2020/08/25 10:02:29 ...m.io/xorm/core/db.go:277:ExecContext() [I] [SQL] INSERT INTO `notice` (`type`,`description`,`created_unix`) VALUES (?, ?, ?) [2 Cron: Update migration poster IDs has finished 1598320949] - 21.193461ms
2020/08/25 10:02:29 ...m.io/xorm/core/db.go:154:QueryContext() [I] [SQL] SELECT * FROM `repository`  LIMIT 1 [] - 20.068821ms
2020/08/25 10:02:29 ...m.io/xorm/core/db.go:154:QueryContext() [I] [SQL] SELECT MAX(id) FROM `repository` LIMIT 1 [] - 71.976µs
2020/08/25 10:02:29 ...m.io/xorm/core/db.go:154:QueryContext() [I] [SQL] SELECT `repository`.`id` FROM `repository` LEFT OUTER JOIN `repo_indexer_status` ON repository.id = repo_indexer_status.repo_id AND repo_indexer_status.indexer_type = ? WHERE repo_indexer_status.id IS NULL AND repository.is_empty=? AND repository.id<=? ORDER BY `repository`.`id` DESC LIMIT 50 [1 false 88] - 116.802µs
2020/08/25 10:02:29 ...xer/stats/indexer.go:84:populateRepoIndexer() [I] Done (re)populating the repo stats indexer with existing repositories
2020/08/25 10:02:29 ...m.io/xorm/core/db.go:154:QueryContext() [I] [SQL] SELECT `id`, `repo_id`, `hook_id`, `uuid`, `type`, `url`, `signature`, `payload_content`, `http_method`, `content_type`, `event_type`, `is_ssl`, `is_delivered`, `delivered`, `is_succeed`, `request_content`, `response_content` FROM `hook_task` WHERE (is_delivered=?) [false] - 21.61511ms
2020/08/25 10:02:29 routers/init.go:162:GlobalInit() [I] SQLite3 Supported
2020/08/25 10:02:29 routers/init.go:50:checkRunMode() [I] Run Mode: Production
2020/08/25 10:02:29 ...m.io/xorm/core/db.go:277:ExecContext() [I] [SQL] INSERT INTO `notice` (`type`,`description`,`created_unix`) VALUES (?, ?, ?) [2 Cron: Delete old repository archives has finished 1598320949] - 23.403778ms
2020/08/25 10:02:29 ...m.io/xorm/core/db.go:154:QueryContext() [I] [SQL] SELECT `pull_request`.`id` FROM `pull_request` WHERE (status=?) [1] - 23.118762ms
2020/08/25 10:02:29 cmd/web.go:161:runWeb() [I] Listen: http://0.0.0.0:3000
2020/08/25 10:02:29 cmd/web.go:164:runWeb() [I] LFS server enabled
2020/08/25 10:02:29 ...s/graceful/server.go:55:NewServer() [I] Starting new server: tcp:0.0.0.0:3000 on PID: 4706
2020/08/25 10:02:30 ...m.io/xorm/core/db.go:154:QueryContext() [I] [SQL] SELECT `id`, `lower_name`, `name`, `full_name`, `email`, `keep_email_private`, `email_notifications_preference`, `passwd`, `passwd_hash_algo`, `must_change_password`, `login_type`, `login_source`, `login_name`, `type`, `location`, `website`, `rands`, `salt`, `language`, `description`, `created_unix`, `updated_unix`, `last_login_unix`, `last_repo_visibility`, `max_repo_creation`, `is_active`, `is_admin`, `is_restricted`, `allow_git_hook`, `allow_import_local`, `allow_create_organization`, `prohibit_login`, `avatar`, `avatar_email`, `use_custom_avatar`, `num_followers`, `num_following`, `num_stars`, `num_repos`, `num_teams`, `num_members`, `visibility`, `repo_admin_change_team_access`, `diff_view_style`, `theme` FROM `user` WHERE `id`=? LIMIT 1 [18] - 181.164µs
2020/08/25 10:02:30 ...m.io/xorm/core/db.go:154:QueryContext() [I] [SQL] SELECT `id`, `lower_name`, `name`, `full_name`, `email`, `keep_email_private`, `email_notifications_preference`, `passwd`, `passwd_hash_algo`, `must_change_password`, `login_type`, `login_source`, `login_name`, `type`, `location`, `website`, `rands`, `salt`, `language`, `description`, `created_unix`, `updated_unix`, `last_login_unix`, `last_repo_visibility`, `max_repo_creation`, `is_active`, `is_admin`, `is_restricted`, `allow_git_hook`, `allow_import_local`, `allow_create_organization`, `prohibit_login`, `avatar`, `avatar_email`, `use_custom_avatar`, `num_followers`, `num_following`, `num_stars`, `num_repos`, `num_teams`, `num_members`, `visibility`, `repo_admin_change_team_access`, `diff_view_style`, `theme` FROM `user` WHERE `id`=? LIMIT 1 [1] - 252.699µs
2020/08/25 10:02:30 ...m.io/xorm/core/db.go:154:QueryContext() [I] [SQL] SELECT `id`, `lower_name`, `name`, `full_name`, `email`, `keep_email_private`, `email_notifications_preference`, `passwd`, `passwd_hash_algo`, `must_change_password`, `login_type`, `login_source`, `login_name`, `type`, `location`, `website`, `rands`, `salt`, `language`, `description`, `created_unix`, `updated_unix`, `last_login_unix`, `last_repo_visibility`, `max_repo_creation`, `is_active`, `is_admin`, `is_restricted`, `allow_git_hook`, `allow_import_local`, `allow_create_organization`, `prohibit_login`, `avatar`, `avatar_email`, `use_custom_avatar`, `num_followers`, `num_following`, `num_stars`, `num_repos`, `num_teams`, `num_members`, `visibility`, `repo_admin_change_team_access`, `diff_view_style`, `theme` FROM `user` WHERE `id`=? LIMIT 1 [16] - 701.63µs
2020/08/25 10:02:39 ...m.io/xorm/core/db.go:154:QueryContext() [I] [SQL] SELECT user_id, count(*) AS count FROM notification WHERE user_id IN (SELECT user_id FROM notification WHERE updated_unix >= ? AND updated_unix < ?) AND status = ? GROUP BY user_id [1598320947 1598320957 1] - 208.523µs

**Comment by shijunti19** [comment]
[2.zip](https://github.com/go-gitea/gitea/files/5120992/2.zip)

**Comment by zeripath** [comment]
Ok it looks like your supervisor is killing Gitea. Presumably because of memory limits or the like.

I recommend adjusting your log settings a little:

```ini
[database]
LOG_SQL = false

**Comment by shijunti19** [comment]
@zeripath 

100%, my server memory is absolutely enough


[2.zip](https://github.com/go-gitea/gitea/files/5122240/2.zip)

**Comment by shijunti19** [comment]
@zeripath

**Comment by zeripath** [comment]
```
2020/08/25 16:06:22 ...er/issues/indexer.go:228:func3() [F] Issue Indexer Initialization timed-out after: 30s
```

**Comment by zeripath** [comment]
The problem is that the issue indexer is not able to be created.

The appearance of your issue has zero to do with index-pack failing or otherwise. The issue is that Gitea is restarting every 90s and you have not noticed it.

I would ensure that `indexers/issues.bleve` can be created, if not that is the cause of your problem. If it is present consider deleting it - as it may be corrupted.

**Comment by shijunti19** [comment]
@zeripath 
Thank you. It's valid after deletion

This is bad:
![image](https://user-images.githubusercontent.com/5392211/91504587-2cda5780-e900-11ea-93b5-655477fb10b3.png)

This is regenerated
![image](https://user-images.githubusercontent.com/5392211/91504626-4aa7bc80-e900-11ea-902d-a1bb17b62302.png)


This error can only be detected by software and prompted us to fix it! It's hard for us to find out, and we can't understand the log
