### ISSUE TITLE
JWT_SECRET is set to a known value by default

### ISSUE THREAD

**Issue by nodiscc** [go-gitea/gitea#12590]
- Gitea version (or commit ref): master
- Git version: any
- Operating system: any
- Database (use `[x]`): any
- Can you reproduce the bug at https://try.gitea.io: Not relevant

## Description

The default configuration ([app.ini](https://raw.githubusercontent.com/go-gitea/gitea/master/custom/conf/app.example.ini)) sets a predetermined OAuth2 secret:

```
; OAuth2 authentication secret for access and refresh tokens, change this to a unique string.
JWT_SECRET=Bk0yK7Y9g_p56v86KaHqjSbxvNvu3SbKoOdOt2ZcXvU
```

The default configuration should not contain cleartext, hardcoded secrets. The value should be blank by default, and the user should set this manually, or let gitea generate a unique, random secret on startup.

**Comment by techknowlogick** [comment]
That is not the default configuration, but rather an sample of what config could look like, it should not be used as a base. If that option is not set then Gitea will generate a random unique variable on startup.

**Comment by nodiscc** [comment]
Good news :) can we change it so that the sample file doesn't set this value? `LFS_JWT_SECRET` example is fine, in comparison:

```
; LFS authentication secret, change this yourself
LFS_JWT_SECRET =
```

Having a preset, sensitive value in the example config file will lead users to forget changing it (I just did).

**Comment by techknowlogick** [comment]
Just created a PR to do exactly that. Thanks for suggestion :)

**Comment by zeripath** [comment]
Please look at what you've set by copying over that app.example.ini as your app.ini and genuinely decide if you want those settings or not. 

The logging section in that file is only meant to act as further documentation and does not really function.

In general if you don't understand what you're setting you should not be setting it.

**Comment by nodiscc** [comment]
I have to copy the whole `app.ini` because I'm working on an [ansible role](https://github.com/nodiscc/xsrv/tree/fix-gitea/roles/gitea) that preconfigures gitea. Gitea does _not_ have write access to the config file on my setup, hence all settings must be set beforehand in `app.ini`.

Unless you're telling me that gitea will work fine if I only the settings I care about are set in `app.ini`?

**Comment by zeripath** [comment]
Yes Gitea will work fine with only a few settings set - basically the ones which install would set. (In fact even that sets ROOT_URL when it need not do so.)

**Comment by nodiscc** [comment]
> Yes Gitea will work fine with only a few settings set

Thanks, I can confirm this works. https://github.com/nodiscc/xsrv/blob/master/roles/gitea/templates/etc_gitea_app.ini

> only configure a subset of gitea settings in the configuration file, let gitea use default values for other settings
