### ISSUE TITLE
Request timeout when uploading large objects with git lfs

### ISSUE THREAD

**Issue by carlonluca** [go-gitea/gitea#12595]
- Gitea version (or commit ref): 1.12.3 docker
- Git version: 2.24.3
- Operating system: Docker image built for raspberry pi
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant

## Description
The issue is very similar to #11906 , but is happening with lfs objects:

```
[Macaron] 2020-08-24 22:33:42: Started PUT .../info/lfs/objects/81fc15137be1a4264ea33370250f8253528370223dc1e8b175815ae84b1a78df for 172.24.0.3
[Macaron] 2020-08-24 22:34:10: Started POST .../info/lfs/objects/batch for 172.24.0.3
[Macaron] 2020-08-24 22:34:10: Completed POST .../info/lfs/objects/batch 200 OK in 267.707332ms
[Macaron] 2020-08-24 22:34:11: Completed PUT .../info/lfs/objects/81fc15137be1a4264ea33370250f8253528370223dc1e8b175815ae84b1a78df 500 Internal Server Error in 29.202370851s
```

I think push is also retrying the upload multiple times,
I tried to search the docs for some configuration of a timeout but couldn't find it.
Reproducing online is a bit difficult: I'm trying to upload a few GBs, and the push ends up uploading more than 10 GBs without ending.

**Comment by lafriks** [comment]
`500 Internal Server Error` indicates server error. Can you check gitea.log file for additional error details

**Comment by carlonluca** [comment]
I didn't know there were other logs. Now I see this error:

`2020/08/29 01:18:23 ...lfs/content_store.go:71:Put() [E] Whilst putting LFS OID[37e9651bf0a29f3274cefd322d3e4ddd34860657459f446c40ccb6138e1ef477]: Failed to copy to tmpPath: /data/git/lfs/37/e9/651bf0a29f3274cefd322d3e4ddd34860657459f446c40ccb6138e1ef477.tmp Error: unexpected EOF`

**Comment by lafriks** [comment]
Just to rule it out, can this be disk space error?

**Comment by carlonluca** [comment]
Unfortunately no, that is the first thing I checked. I also tried to go to git/lfs/37/e9 and I created a test file of 2GB without errors.

**Comment by zeripath** [comment]
Are you running with a proxy?

**Comment by carlonluca** [comment]
Yes, gitea is behind nginx.
