### ISSUE TITLE
README viewer: Issue 500

### ISSUE THREAD

**Issue by a-n-dokuchaev** [go-gitea/gitea#12599]
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes ([URL](https://try.gitea.io/ahaha/testlinks/src/branch/bug500))
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

There are 2 repos:
- [https://try.gitea.io/ahaha/testlinks](https://try.gitea.io/ahaha/testlinks)
- [https://try.gitea.io/ahaha/linksubmodule](https://try.gitea.io/ahaha/linksubmodule) - available as `testlinks/linksubmodule/`

In the branch `bug500` ([https://try.gitea.io/ahaha/testlinks/src/branch/bug500](https://try.gitea.io/ahaha/testlinks/src/branch/bug500)) we have symlink `README->linksubmodule/README.md` and internal server error 500.

**Comment by silverwind** [comment]
It also highlights this regression from https://github.com/go-gitea/gitea/commit/dd8ec121880fda03691cf9f4b17be88e1d4be030:

<img width="568" alt="image" src="https://user-images.githubusercontent.com/115237/91202965-d2c07300-e702-11ea-806e-b83b93f95953.png">
