### ISSUE TITLE
Add file to "downloads" area - how?

### ISSUE THREAD

**Issue by salesgroup** [go-gitea/gitea#12598]
Bitbucket has a "downloads" area where we can uploads files, for example a DB dump.
We need this feature, but we don't know how we can achieve this with Gitea.

In Gitea, Issues and releases are the only places where we can upload files?
Is there any workaround for uploading a file to the REPO and being available only for the web interface and not with the git command?

**Comment by lafriks** [comment]
Yes, your mentioned places are only ones where files can be uploaded
