### ISSUE TITLE
Versions in Pull requests.

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#12604]
After someone opened a PR from a branch every push that introduces new commits (including the cases where some or all of the previous commits are removed/changed) should generate an entry, a kind of "new version" in the Pull Request's page.

It should be possible to quickly look at this entry generated and find out what has changed between the versions (by taking the user to a diff/compar page)

This is supported in Github, Gitlab, and Gerrit. 

Also on the changes _Files changed_ tab the user should be able to compare any two versions and see what has changed between those versions.
(This is supported in Gitlab and Gerrit but not in Github at the moment, or at least its not clearly reachable from the PR's page).

**Comment by jolheiser** [comment]
For the first part, do you mean the [commits tab](https://try.gitea.io/jolheiser/normal/pulls/1/commits)?  
Or the conversation tab, which shows a timeline of commits?

The second part is achievable by manually building the URL, however similar to GH there isn't an easy way to do it from the UI.

**Comment by alvardes** [comment]
@jolheiser Does the commit tab show the changes between the old version of a branch and a new version of a branch if I do a `git push --force`? I don't think so.

**Comment by alvardes** [comment]
> The second part is achievable by manually building the URL, however similar to GH there isn't an easy way to do it from the UI.

Yes that is the point of this issue, to add a something like what's in gerrit (or I think a similar feature exists in reviewboard too)

**Comment by alvardes** [comment]
To be able to store replaced commits an extra `ref` would need to be created by gitea. This is how it is done by gerrit:

https://gerrit-review.googlesource.com/Documentation/concept-refs-for-namespace.html

> In fact, for each commit pushed to this ref, Gerrit creates a new ref under a refs/changes/ namespace, which Gerrit uses to track these commits. These references use the following format:
> 
> `refs/changes/[CD]/[ABCD]/[EF]`
> 
> Where:
> 
>     [CD] is the last two digits of the change number
> 
>     [ABCD] is the change number
> 
>     [EF] is the patch set number
> 
> For example:
> 
> `refs/changes/20/884120/1`

**Comment by alvardes** [comment]
Also you can see an explanation of how this works in gerrit here: https://www.beepsend.com/2016/04/05/abandoning-gitflow-github-favour-gerrit/
in the **Updating a code review**, **What is a patch set** and **Working with patch sets** sections.

**Comment by a1012112796** [comment]
Ping stale bot
