### ISSUE TITLE
[FEATURE] Contributor License Agreement

### ISSUE THREAD

**Issue by belliash** [go-gitea/gitea#12606]
Hey, would it be possible to implement the CLA into Gitea? Each project should have it enabled separately with its own terms and conditions as well as users whitelist. It should block merge requests until requesting users accept the CLA.

**Comment by silverwind** [comment]
I personally hate these and they can certainly discourage someone from contributing.

**Comment by belliash** [comment]
> I personally hate these and they can certainly discourage someone from contributing.
> 
> Edit: Ah misunderstood you. You mean as an feature in Gitea. That might be an option.

Yes, I meant this would be nice feature in self-hosted Gitea.

**Comment by techknowlogick** [comment]
Thanks for the suggestion. This would be best implemented as a third party tool as then it can be set up to whichever customization the user requires.
