### ISSUE TITLE
New Logo Gitea

### ISSUE THREAD

**Issue by lcges** [go-gitea/gitea#1260]
This is my proposal for the logo.
I am waiting to feedback and suggestions.

This is a continuation of the issues https://github.com/go-gitea/gitea/issues/1121 

![gitea_icon](https://cloud.githubusercontent.com/assets/19255071/23940392/fe9ea304-0964-11e7-92f4-e8304c5360b4.jpg)

**Comment by davydov-vyacheslav** [comment]
I like this one

![image](https://cloud.githubusercontent.com/assets/9931946/23941519/c19b643a-0971-11e7-97be-ec53cb9fa66f.png)

**Comment by lunny** [comment]
@qdbdbp how about deep green one? or red cup and green tea pack

**Comment by lunny** [comment]
agree with @davydov-vyacheslav

**Comment by andreynering** [comment]
I also like [this one](https://cloud.githubusercontent.com/assets/9931946/23941519/c19b643a-0971-11e7-97be-ec53cb9fa66f.png).

But maybe with Gitea green as @lunny said #8BC34A

**Comment by tboerger** [comment]
I also like the mentioned one

**Comment by pgaskin** [comment]
I like the mentioned one, but green. I also like the first top one, but maybe make everything lowercase.

**Comment by metalmatze** [comment]
Yes, a green version would be very nice. And just an idea: How about we move the git logo into the center of the cup?.
For lower resolutions the logo without the string to the git logo would be nice, and for really small logo sizes, like favicons, maybe just the cup, without anything else?!

**Comment by lcges** [comment]
Another proposal logo. I look forward to the discussions.

@metalmatze I think so, with a low resolution, details will disappear.
Good movement will be making, few levels in graphic logo.

![gitea_logo](https://cloud.githubusercontent.com/assets/19255071/23969762/d9db0e8c-09c7-11e7-815b-d7f17d168ce4.png)

**Comment by davydov-vyacheslav** [comment]
We do need some kind of voting plugin :)
as for me, I like 1 and 5 .... the next closest is 2 , but there is something I can't explain which is repels me :(

**Comment by sailfish009** [comment]
i like 5.

**Comment by lunny** [comment]
1

**Comment by lunny** [comment]
2

**Comment by lunny** [comment]
3

**Comment by lunny** [comment]
4

**Comment by lunny** [comment]
5

**Comment by lunny** [comment]
6

**Comment by bkcsoft** [comment]
I like 5 with the logo from 2 but the logo being red from 1 :trollface:  (really though, I like 5)

Maybe a black/white version as well for icons? 😄

**Comment by lunny** [comment]
@bkcsoft `add your reaction` to vote.

**Comment by lotus-king** [comment]
I like 6

**Comment by lunny** [comment]
@lotus-king please `add your reaction` on my commented 6.

**Comment by grissiom** [comment]
I'm in favor of 5 but it give me a feeling that the git logo is turning over. So I rotate the logo a bit in order to make it more balanced:

![image](https://cloud.githubusercontent.com/assets/36101/24045099/e3ae22b8-0b58-11e7-8dd1-cc05f904c941.png)

This is just a proposal any way ;-)

**Comment by andreynering** [comment]
I like 2, but maybe with a stronger orange (like 1) and green (like 5).

**Comment by ptman** [comment]
Red-green color blindness is the most common form of color blindness

**Comment by kolaente** [comment]
I think the fifth' green is a bit to sharp and won't match the overall "look and feel" of gitea (Flat, light colors, etc)

Therefore i'd rather go for the 2 or 4

**Comment by bkcsoft** [comment]
@grissiom others logos should be used as-is if at all, so rotating it is a bad idea 🙂

**Comment by lcges** [comment]
I present an example of scaling the logo.
16x16 offers without teabag.

![logo6](https://cloud.githubusercontent.com/assets/19255071/24450561/a14d7564-147b-11e7-8ae4-10ec46479cce.jpg)

**Comment by lcges** [comment]
Any decisions we make about the future logo?
Would I suggest voting between the two types of logo?

**Comment by lunny** [comment]
I think close all the old related issues and make a new issue to vote between the two is a good idea.

**Comment by lunny** [comment]
Both the two design in #1260 and #1312 are very excellent, but only one could become the official LOGO. I think the Green Tea Cup in this issue win the votes, it retrieves 24 votes but in #1312 the red one retrieves 15 and green on retrieves 14. @qdbdbp @kolaente So @qdbdbp please send a PR to replace the old LOGO to the new one so that we can merge it in v1.2. Please discuss here if you have any new opinion.

**Comment by jhasse** [comment]
> I think the Green Tea Cup in this issue win the votes, it retrieves 24 votes but in #1312 the red one retrieves 15 and green on retrieves 14.

I don't think that's fair as this issue has got a lot more attention then #1312.

**Comment by lunny** [comment]
@jhasse where is the unfair?

**Comment by jhasse** [comment]
@lunny For example you posted only this issue in the gitter channel.

Also it was never said that voting for a variant of this logo would also count as a vote vote against the logo in #1312.

Last but not least I was waiting for "I think close all the old related issues and make a new issue to vote between the two is a good idea." ;)

**Comment by lunny** [comment]
Please go to #1516 to vote.

**Comment by ulm0** [comment]
I like this very much, though what if you placed the rope in the top corner of the polygon? Idk if it's just me but the way it is now doesn't feel like a tea tag

**Comment by lafriks** [comment]
@qdbdbp could you give SVG files for logo?

**Comment by mmendescortes** [comment]
I liked

> I present an example of scaling the logo.
> 16x16 offers without teabag.
> 
> ![logo6](https://cloud.githubusercontent.com/assets/19255071/24450561/a14d7564-147b-11e7-8ae4-10ec46479cce.jpg)

Dude, someone provide the svg files for this logo, I liked it a lot!
