### ISSUE TITLE
App crash on startup for new install on tablet

### ISSUE THREAD

**Issue by zahidhanif** [go-gitea/gitea#12600]
Just installed the app on my tablet and it crashes. Emailed stack trace report and was advised by Arif to open issue here.

- Gitea version (or commit ref): 3.1.0-rc2
- Operating system: Android 9
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X ] Not relevant

**Comment by jolheiser** [comment]
We will need the error logs and Gitea version.
The version you provided isn't for Gitea. 
You mentioned Arif, so perhaps that's your Gitnex version?

**Comment by zahidhanif** [comment]
Apologies, I have created this on the wrong project. I will close.
