### ISSUE TITLE
After 1.1.0 upgrade: relation "IDX_repo_unit_S" already exists

### ISSUE THREAD

**Issue by rain0r** [go-gitea/gitea#1261]
- Gitea version (or commit ref): 1.1.0
- Git version: 2.12.0
- Operating system: Gentoo Linux
- Database (use `[x]`):
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:

## Description
After upgrading to 1.1.0 via Gentoo portage I can't start gitea because of:

`2017/03/15 12:27:52 [...itea/routers/init.go:54 GlobalInit()] [E] Failed to initialize ORM engine: migrate: do migrate: CreateIndexes RepoUnit: pq: relation "IDX_repo_unit_S" already exists
`...

**Comment by lunny** [comment]
Please drop the table `repo_unit` manually and start again.

**Comment by rain0r** [comment]
That worked.

**Comment by strk** [comment]
@lunny any way to make our migrations immune from this issue ? (might help when people try to migrate from a newer Gogs, for example)

**Comment by lunny** [comment]
It's hard to resolve this problem. Many operations cannot be reverted.
