### ISSUE TITLE
IIS Redirect Loop Gravatar

### ISSUE THREAD

**Issue by gumsanaung** [go-gitea/gitea#12618]
- Gitea version (or commit ref): 1.12.3
- Git version: 2.28.0.windows.1
- Operating system: Microsoft Windows Server 2012 R2 Standard
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
Profile avatars from gravatar are in a redirect loop.
I am using IIS Reverse Proxy with an outbound rule that rewrites to a host name.
instead of going to https://secure.gravatar.com/avatar/XXXXXXXXXXX...X?d=identicon
the redirect is to http://hostname/XXXXXXXXXXX...X?d=identicon and ends up in a loop.
The error does not exits while accessing the Gitea from localhost.
The IIS rewrite and config is from [#10748 ](url)
...

**Comment by kevinlin18** [comment]
Try this
UNCHECK 'Reverse rewrite host in response headers'
in Application Request Routing>Server Proxy Settings

**Comment by gumsanaung** [comment]
It worked! Thanks for the help!
