### ISSUE TITLE
Problem with restore gitea from backup in docker

### ISSUE THREAD

**Issue by melmus** [go-gitea/gitea#12614]
- Gitea version (or commit ref):
1.13.0+dev-295-g16980d13c
- Git version:
2.17.1
- Operating system:
Ubuntu 18.04.4 LTS
- Database (use `[x]`):
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:

## Description

HI! I have a problem with restore gitea from backup.
I made backup and restore command:
1. docker exec -t -u git -w /data/dirtmp/ $(docker ps -qf name="gitea_server_1") sh -c "/app/gitea/gitea dump -c /data/gitea/conf/app.ini"
2. sent gitea dump to remote server
3. unzip gitea dump
4. on new server I installed gitea(version) in docker(version)
5. stopped gitea web:  docker stop gitea_server_1
6. Restore database: cat gitea-db.sql | docker exec -i gitea_db_1 psql -Ugitea
7. copied repositories in data gitea
8. started gitea web: docker start gitea_server_1

But I have a problem:
I don’t see visible repository, not visible organizations, users ssh keys, pull requests, webhooks.  On page with statistics I see some repos, keys, webhooks.
If I go to page Explore, i see: 

**template: explore/repo_list:24:17: executing "explore/repo_list" at <.Owner.Visibility.IsPrivate>: nil pointer evaluating models.User.Visibility**

I read documentation before make this. Please advise If I make something wrong?
How can i migrate gitea to new server in docker?
I see this problem on gitea version 1.12.3, and latest: 1.13.0+dev-295-g16980d13c, 1.13.0+dev-471-gb611ae190
## Screenshots

![Снимок экрана 2020-08-25 в 8 17 41](https://user-images.githubusercontent.com/15018126/91315931-ecc08b00-e7c0-11ea-8aba-b86da340dfd0.png)
![Снимок экрана 2020-08-26 в 18 08 14](https://user-images.githubusercontent.com/15018126/91321647-85f2a000-e7c7-11ea-8e0c-4321de410480.png)

**Comment by melmus** [comment]
This issue is actual now.

**Comment by 6543** [comment]
@melmus did you use the **SAME** version for dump & restor
and did you copy the app.ini too?

**Comment by melmus** [comment]
@6543, yes, I used the same version for dump & restore, and I copyed the app.ini too

**Comment by lakostin** [comment]
have the same problem

**Comment by 6543** [comment]
@melmus lots of patches have happend can you upgrade the gitea who executes the dump comand?
PS: backup via simply copy data and dump DB mannualy should do it too

still, if this is a problem it should be solved ...

**Comment by melmus** [comment]
@6543, I dumped DB manually, 
```bash
docker exec -i gitea_db_1 /bin/bash -c "export PGPASSWORD=giteapassword && /usr/bin/pg_dump -U gitea gitea"  > dump_DB.sql
```
And restored DB:
```bash
docker stop gitea_server_1
cat dump_DB.sql | docker exec -i gitea_db_1 psql -Ugitea
```
After I copied repositories:
```bash
cp repositories /data/git/git/repositories
```
And started gitea web
```bash
docker start gitea_server_1
```

This is working decision...

**Comment by wxiaoguang** [comment]
Outdated

**Comment by HiranChaudhuri** [comment]
How come this is outdated? Does such a command exist meanwhile? 8-)

**Comment by wxiaoguang** [comment]
This issue was asking about the restore for 1.13.0, it's outdated.

The suggestion in comment is not obvious to maintainers, it may be worth to be a separate proposal issue if you like.
