### ISSUE TITLE
I want to add pages to make it easier for product people to share static pages

### ISSUE THREAD

**Issue by Jengro777** [go-gitea/gitea#12627]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

...

**Comment by jolheiser** [comment]
Can you explain this a little more?

Are you referring to something like GitHub pages, or just adding static files to Gitea itself?

For the former, there is #3834 open.
For the latter, we have a way to [add custom static content](https://docs.gitea.io/en-us/customizing-gitea/#serving-custom-public-files), however none that a user can initiate.
