### ISSUE TITLE
Snap: how to change user from root to git

### ISSUE THREAD

**Issue by wmutschl** [go-gitea/gitea#12621]
- Gitea version (or commit ref): 2.17.1
- Git version: 2.25.1
- Operating system: Ubuntu 20.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
In my configuration file `/var/snap/gitea/common/conf/app.ini` the `RUN_USER` is set to `root`. Thus my clone urls via ssh look like e.g. `ssh://root@git.mutschler.eu:2222/wmutschl/dsge.git`. Now, is it possible to change the user to another user-name, for instance set it to `git`? Or is it that due to snap limitations this has to be set to `root`? Will there be any caveats by using a different user here?

**Comment by wmutschl** [comment]
Just an update, it was no problem to change the name. However, I don't use the snap version anymore due to other issues.

**Comment by spacehobo** [comment]
I appreciate that the original poster no longer needs this, but it is a valid concern.  I understand that apparmor is protecting things here, but I would prefer not to have things running as root when all they need is filesystem access and (in my case) high-numbered ports.

**Comment by lunny** [comment]
It seems no user defined on `snapcraft.yml`?

**Comment by spacehobo** [comment]
It's possible that's related.  Note that I don't mind if by default it runs as root, so long as I can configure it not to via the `/var/snap/gitea/common/conf/app.ini` file.

**Comment by wmutschl** [comment]
Exactly, one can simply configure it in the app.ini.
