### ISSUE TITLE
accessibility issues

### ISSUE THREAD

**Issue by lilmike** [go-gitea/gitea#1263]
- Gitea version (or commit ref): 1.1.0
- Git version: 2.12.0
- Operating system: arch linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist: not needed

## Description

Gitea, as with gogs which it was forked from, has many accessibility issues with screen readers including:

1. The dropdown menus are clickables, so many screen readers do not know what to do with them as they do not use the mouse cursor.
2. The license selection/.gitignore selection (and most other menus of that type) are inaccessible, as they all use mouse oriented actions.
3. Possibly others I haven't seen yet.

Unfortunately, this is caused by the toolkit you use, which does not seem interested in making their toolkit accessible. It can be worked around with aria markup, or by changing  toolkits (the first of which is easier to begin with but requires more maintenance over time, the second of which is of course much harder, but once you get it done it's done pretty much forever).

See the original issue on gogs for more info: https://github.com/gogits/gogs/issues/3340

Looking forward to seeing if anything can be done about this.
-Michael.

**Comment by lilmike** [comment]
Hi,
I was just revisiting this issue as I was trying to find a git manager that had some of the features of gitlab enterprise (which gitea does). Any news on this?
-Michael.

**Comment by lilmike** [comment]
I did a simple try of adding role="listbox" to all items that act as listboxes in gitea, and role="option" to every option in those menues, just to see if it would even help at all. Turns out it won't. So the long and short of it is... semantic UI will need to go if this project is to become accessible. I'd honestly be willing to give converting the project over to another framework my best try, though I'm honestly not super familiar with css, js, or go, but I don't want to do the work if the prospect won't be accepted anyway. So the questions:
1. Is changing framework (even if I do the brunt of the work) even on the table?
2. Are there prefered frameworks if so?

At the worst I can always fork gitea and make my changes even if they won't be merged back in -- that's the beauty of open source. But I'd like to get my changes merged into gitea if possible, if only because it already has a following and so everyone can benefit.
-Michael.

**Comment by lafriks** [comment]
It is possible for switching framework but the problem is that for functionality we need simple dropdown list wont help much anyway for most of the dropdowns as we need them searchable and more advanced.

For me preferable would be bulma + vue but that's just for me :)

**Comment by lunny** [comment]
I like bootstrap3/4 + vue :)

**Comment by lafriks** [comment]
It will be quite big task as quite much all html markdown and javascript functionality needs to be changed
