### ISSUE TITLE
Number of commits format

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#12637]
Use some formatting to improve readability of the number of commits.

Currently it looks like this: 
![commits](https://user-images.githubusercontent.com/62710862/91638712-ba599c80-ea11-11ea-9dd5-245bef3fa9ff.png)

Instead it should look something like this:

`10 006 Commits` or
`10,006 Commits` or
`10.00K Commits`

**Comment by Extarys** [comment]
This could be shown based on localization/language chosen or configurable independently maybe?
