### ISSUE TITLE
[Bug] DB Deadlock on de-/assigning miltiple lables at once

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#12643]
gitea version: == 1.12.x

source: https://codeberg.org/Codeberg/Community/issues/123 (Multiple labels for an issue can't be choose at the same time)

To Reproduce: de-/select more than 1 lable and reload (you wont get the expected result)

posible solutions:
 1. change the js code to submit lable chois on click (there is time between each de-/selection) <- like asignee selection work
 2. make router endpoint accept a bundle of lable-id’s at once

**Comment by a1012112796** [comment]
GH is same ...
![tmp](https://user-images.githubusercontent.com/25342410/91730046-02c2b700-ebd8-11ea-8d6b-e1324dd10ba7.gif)

**Comment by a1012112796** [comment]
I can choose more than one labels one time. Do you means this?
![tmp1](https://user-images.githubusercontent.com/25342410/91731631-a6609700-ebd9-11ea-852e-4118b8cb8188.gif)

**Comment by 6543** [comment]
@a1012112796 I mean this feature yes, it sometimes is not working properly
