### ISSUE TITLE
OAuth access token and refresh token expiration times

### ISSUE THREAD

**Issue by gempain** [go-gitea/gitea#12641]
- Gitea version (or commit ref): 1.13.0+dev-371-g4d9f59a45
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant

## Description

The [OAuth2 docs](https://docs.gitea.io/en-us/config-cheat-sheet/#oauth2-oauth2) describe `REFRESH_TOKEN_EXPIRATION_TIME` as the **Lifetime of an OAuth2 access token in hours**. This seems incorrect looking at the name of the variable.

That aside, I find it strange to have different expiration times for the refresh token and the access token. When you get an access token via the [OAuth authorization flow](https://docs.gitea.io/en-us/oauth2-provider/#example), you get this answer:
```json
{
"access_token":"eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJnbnQiOjIsInR0IjowLCJleHAiOjE1NTUxNzk5MTIsImlhdCI6MTU1NTE3NjMxMn0.0-iFsAwBtxuckA0sNZ6QpBQmywVPz129u75vOM7wPJecw5wqGyBkmstfJHAjEOqrAf_V5Z-1QYeCh_Cz4RiKug",  
"token_type":"bearer",  
"expires_in":3600,  
 "refresh_token":"eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJnbnQiOjIsInR0IjoxLCJjbnQiOjEsImV4cCI6MTU1NzgwNDMxMiwiaWF0IjoxNTU1MTc2MzEyfQ.S_HZQBy4q9r5SEzNGNIoFClT43HPNDbUdHH-GYNYYdkRfft6XptJBkUQscZsGxOW975Yk6RbgtGvq1nkEcklOw"  
}
```

The `expires_in` property is the expiration time of the access token (per specification). Hence, a third party application would expect to be able to refresh the access token within 3600 seconds. But in reality, that won't work as the refresh token expires in `REFRESH_TOKEN_EXPIRATION_TIME`.

**Comment by zeripath** [comment]
it looks like the docs are incorrect here. The name is correct - it sets the REFRESH_TOKEN_EXPIRATION_TIME not the ACCESS token expiration time. I've sent a PR to update them.

**Comment by gempain** [comment]
@zeripath thanks for the fix ! That was quick 😄 Do you have any comment regarding the fact that there are two settings for those timeouts. How is a third party app expected to refresh the token since the refresh token will have expired long before the 3600 seconds mentioned in the payload as `expire_time` ? Shouldn't Gitea either return the expiration of the refresh token as well ?

**Comment by zeripath** [comment]
The refresh token is in hours - not seconds

**Comment by gempain** [comment]
@zeripath I see. Do you think it would be possible to include in the OAuth response a property named `refresh_token_expires_in` which has that value ? Github [does this](https://developer.github.com/apps/building-github-apps/refreshing-user-to-server-access-tokens/#response):

```json
{
  "access_token": "e72e16c7e42f292c6912e7710c838347ae178b4a",
  "expires_in": "28800",
  "refresh_token": "r1.c1b4a2e77838347a7e420ce178f2e7c6912e1692",
  "refresh_token_expires_in": "15811200",
  "scope": "",
  "token_type": "bearer"
}
```

**Comment by zeripath** [comment]
You would probably have to add it here :

https://github.com/go-gitea/gitea/blob/d3b5edacb655ced0135ca5f48544612ccc38890e/routers/user/oauth.go#L109

And here

https://github.com/go-gitea/gitea/blob/d3b5edacb655ced0135ca5f48544612ccc38890e/routers/user/oauth.go#L160

Would be a 2 line pr. (Barring formatting changes.)

Feel free to submit a PR.
