### ISSUE TITLE
Space in name of authentication source causes problems for Keycloak

### ISSUE THREAD

**Issue by jcollie** [go-gitea/gitea#12647]
- Gitea version (or commit ref): 1.12.3
- Git version: 2.24.3
- Operating system: Docker
- Database (use `[x]`):
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X] No
  - [ ] Not relevant
- Log gist:

## Description

I created an OAuth2/OpenID Connect authentication source to test out authentication with my new Keycloak server. When assigning an Authentication Name I used "keycloak test". This appears to have caused problems with Keycloak because of the space in the name. Changing the space to a dash character in Gitea fixes the error. I would think that url-encoding the space would have fixed the problem as well. Here's the error that I see in Keycloak's log:

03:07:45,157 WARN  [org.keycloak.events] (default task-38) type=LOGIN_ERROR, realmId=test, clientId=gitea, userId=null, ipA
ddress=127.0.0.1, error=invalid_redirect_uri, redirect_uri='https://git.example.com/user/oauth2/keycloak test/callback'

**Comment by zeripath** [comment]
Thanks for alerting us.

**Comment by jcollie** [comment]
Thanks for fixing so quickly!
