### ISSUE TITLE
Using IPFS for Federation

### ISSUE THREAD

**Issue by zyansheep** [go-gitea/gitea#12645]
IPFS could be easily used for Federation. It would allow for projects to be shared and viewed across all instances. Cross-instance pull requests, issue opening as well as watching repositories on other instances could be accomplished using the Inter-Planetary Name System and IPFS's PubSub System.
I originally brought up this idea on #1612 but someone suggested to open a new issue.

**Comment by maisiliymBridj** [comment]
The problem isn't so much how to store the data, but how to merge between entities.
This would be a first step, an easy one at that - https://github.com/go-gitea/gitea/issues/1872#issuecomment-504390540
But the gitea project hasent taken it seriously. Perhaps @zyansheep can be more convincing to the project.

**Comment by zyansheep** [comment]
Looking at the code, gitea would need a pretty large code refactoring to support suborganizations. Currently, the [routing file](https://github.com/go-gitea/gitea/blob/master/routers/routes/routes.go) directly supports "/:username/:reponame" route match.
However, I'm more focused on the ability for viewing and contributing to repositories regardless of what gitea instance you have an account with. If repository objects as well as other information (issue threads, pull requests, stars, forks, etc.) were made available on IPFS, they could be viewed from other gitea repositories if you knew the IPNS or IPFS address. If the entirety of gitea's repository storage was based on IPFS, it would allow for local forking without having to duplicate the data in storage.

**Comment by 6543** [comment]
@zyansheep this would need a lot of rewrite or "adapters" to warp things into IPFS/IPNS

and it only would make it posible to federate between gitea
a bad idear ... just have a look how Diaspora has a great protocoll but they where the first and no standard was established.
Nowerdays it's still here but most new Distributed platforms only support/focus on ActivePub

so [ForgeFed](https://forgefed.peers.community) is more interesting than IPFS ...

by the way I personaly find IPNS very slow so It could slow down big instances.
