### ISSUE TITLE
Error when trying to reply to a comment in an outdated file

### ISSUE THREAD

**Issue by davidglezz** [go-gitea/gitea#12658]
- Gitea version (or commit ref): 1.12.3
- Git version: 
- Operating system: Ubuntu
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MSSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

During a review: when trying to reply to a comment in an outdated file, a 500 error occurs.

The file originally had many lines, ex 100
A comment is made on a line, ex 90
The file is modified so that it has less than 90 lines, example 50
When trying to reply to the comment the following error occurs:

```
2020/08/31 10:07:45 .../repo/pull_review.go:50:CreateCodeComment() [E] CreateCodeComment: LineBlame[refs/pull/23/head, /data/git/repositories/xxxx/test.git, views/js/test.js, 98]: exit status 128 - fatal: file views/js/test.js has only 50 lines
```

## Screenshots
Error 500 page

**Comment by lhinderberger** [comment]
I can confirm - this bug happened to me as well.

Reproduction on try.gitea.io: https://try.gitea.io/knut/issue-12658/pulls/1
When trying to comment the outdated review comment, Gitea returns Error 500.

Parallel discussion: https://codeberg.org/Codeberg/Community/issues/299

**Comment by zeripath** [comment]
https://github.com/go-gitea/gitea/blob/ae23bbdae3102ebc187ff504fe07d75116815ff4/services/pull/review.go#L130

Needs to do the same check I added in #11882:

https://github.com/zeripath/gitea/blob/f847f0acfe0e94372a334b4f3bf0beed999e7509/models/issue_comment.go#L509

https://github.com/zeripath/gitea/blob/f847f0acfe0e94372a334b4f3bf0beed999e7509/models/issue_comment.go#L514

This is therefore likely a 2 line PR to fix.

**Comment by 6543** [comment]
@zeripath 4Lines ;) - thx for the hint

and yes this was it -> #13041

(tested localy)
