### ISSUE TITLE
Instance migrated from server to server, 1.11.x to 1.12.2, ROOT_URL ignored

### ISSUE THREAD

**Issue by kode54** [go-gitea/gitea#12656]
- Gitea version (or commit ref): 1.12.2
- Git version: 2.25.1
- Operating system: Ubuntu LTS 20.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:
https://gist.github.com/kode54/1056b3778e006e3b4a12276536ff75b5

## Description
Upon migrating our server configuration from 18.04 running Gitea 1.11.x to 20.04 running 1.12.2, the server now returns incorrect URLs for all links.

Instead of linking to https://example.com/user/repo, it links to //repo. Literally, the anchor tag's href= is "//repo"

## Screenshots
![gitea_breakage](https://user-images.githubusercontent.com/796316/91677619-1991dc80-eaf8-11ea-9704-65aade4b0b9a.png)

## Configuration

Here, you can have my configuration, with the secret bits redacted:

```
APP_NAME = López-Snowhill Gitea
RUN_USER = git
RUN_MODE = prod

[oauth2]
JWT_SECRET = [redacted]

[security]
INTERNAL_TOKEN = [redacted]
INSTALL_LOCK   = true
SECRET_KEY     = [redacted]

[database]
DB_TYPE  = sqlite3
HOST     = 127.0.0.1:3306
NAME     = gitea
USER     = gitea
PASSWD   = 
SSL_MODE = disable
CHARSET  = utf8
PATH     = /var/lib/gitea/data/gitea.db
SCHEMA   = 

[repository]
ROOT = /home/git/gitea-repositories/

[server]
PROTOCOL         = http
SSH_DOMAIN       = example.com
DOMAIN           = example.com
HTTP_PORT        = 3000
ROOT_URL         = https://example.com/
LOCAL_ROOT_URL   = http://localhost:3000/
DISABLE_SSH      = false
SSH_PORT         = 22
LFS_START_SERVER = true
LFS_CONTENT_PATH = /var/lib/gitea/data/lfs
LFS_JWT_SECRET   = [redacted]
OFFLINE_MODE     = false

[mailer]
ENABLED = false

[service]
REGISTER_EMAIL_CONFIRM            = false
ENABLE_NOTIFY_MAIL                = false
DISABLE_REGISTRATION              = false
ALLOW_ONLY_EXTERNAL_REGISTRATION  = false
ENABLE_CAPTCHA                    = true
REQUIRE_SIGNIN_VIEW               = false
DEFAULT_KEEP_EMAIL_PRIVATE        = true
DEFAULT_ALLOW_CREATE_ORGANIZATION = true
DEFAULT_ENABLE_TIMETRACKING       = true
NO_REPLY_ADDRESS                  = example.com

[picture]
DISABLE_GRAVATAR        = false
ENABLE_FEDERATED_AVATAR = true

[openid]
ENABLE_OPENID_SIGNIN = true
ENABLE_OPENID_SIGNUP = true

[session]
PROVIDER = file

[log]
MODE      = file
LEVEL     = info
ROOT_PATH = /var/lib/gitea/log
```

**Comment by kode54** [comment]
Issue goes away if I downgrade to 1.11.8. Clearly, there's a configuration variable that I'm missing that was added in 1.12.

**Comment by techknowlogick** [comment]
from @CirnoT who posted the below to someone who experienced a similar issue, and this may apply to you too?
```
there was a migration that added ownername to repo table
but it seems that recommended way to migrate instances is to make backup via gitea command, start new instance and restore using gitea command
now, the important thing to note is that starting new instance instantly creates schema up to current version
and restore will fill it with data from old version
hence migrations are skipped entirely
data is not-migrated and new fields are just null
we should really, REALLY warn users about this or
1) restore should not accept db from older version
2) restore should destroy db and recreate along with old schema fully, hence on next start gitea will perform migrations itself
restoring old data onto new schema will never work properly really
```

How did you upgrade to the latest version?

**Comment by kode54** [comment]
I didn't realize I was running an old version, and just restored the database up from the previous version, then launched the new version.

I don't really feel like debugging this anyway, as I've now migrated all of my data to a fresh Gitlab instance.
