### ISSUE TITLE
markdown mixed lists render problem

### ISSUE THREAD

**Issue by m0xf** [go-gitea/gitea#1265]
- Gitea version (or commit ref): 1.1.0
- Git version: 2.1
- Operating system: All
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes 
  - [ ] No
  - [ ] Not relevant
- Log gist:

When i use unordered list inside ordered list markdown not rendered properly. 
Sample:
https://try.gitea.io/m0xf/markdown/src/master/test.md
Excepted results:
https://try.gogs.io/mmxf/test11/src/master/test.md
https://github.com/m0xf/md_test/blob/master/test.md

**Comment by ethantkoenig** [comment]
Fixed by #1530?

**Comment by ethantkoenig** [comment]
@lafriks Why reopened?

**Comment by lafriks** [comment]
I accidently closed it, have not tested if it is fixed

**Comment by lafriks** [comment]
Sorry, it is fixed,  just checked on try.gitea.io
