### ISSUE TITLE
how to manipulate the database

### ISSUE THREAD

**Issue by Leovoki** [go-gitea/gitea#12661]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X ] No
  - [ ] Not relevant
- Log gist:

## Description
which folder is about database?
...

**Comment by techknowlogick** [comment]
To edit the database (looks like you are using mysql) please use a mysql client, such as MySQL workbench, the mysql cli tool, or another one.
