### ISSUE TITLE
Kubernetes helm chart install failed to start mariadb on Raspberry Pi 4

### ISSUE THREAD

**Issue by babvin** [go-gitea/gitea#12666]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:
- helm chart: https://hub.helm.sh/charts/k8s-land/gitea

## Description

`NAME                              READY   STATUS             RESTARTS   AGE         
pod/gitea-gitea-b7c8d6748-fk4q4   2/2     Running            0          15m         
pod/gitea-mariadb-0               0/1     CrashLoopBackOff   7          15m         
                                                                                    
NAME                       TYPE           CLUSTER-IP       EXTERNAL-IP      PORT(S) 
       AGE                                                                          
service/gitea-gitea-http   ClusterIP      10.152.183.134   <none>           3000/TCP
       15m                                                                          
service/gitea-gitea-ssh    LoadBalancer   10.152.183.239   192.168.15.203   22:30068
/TCP   15m                                                                          
service/gitea-mariadb      ClusterIP      10.152.183.88    <none>           3306/TCP
       15m                                                                          
                                                                                    
NAME                          READY   UP-TO-DATE   AVAILABLE   AGE                  
deployment.apps/gitea-gitea   1/1     1            1           15m                  
                                                                                    
NAME                                    DESIRED   CURRENT   READY   AGE             
replicaset.apps/gitea-gitea-b7c8d6748   1         1         1       15m             
                                                                                    
NAME                             READY   AGE                                        
statefulset.apps/gitea-mariadb   0/1     15m                                        

ubuntu@k8s-pi-master:~$ kubectl describe pod gitea-mariadb-0 -n gitea
Name:         gitea-mariadb-0
Namespace:    gitea
Priority:     0
Node:         k8s-pi-wrkr01/192.168.15.17
Start Time:   Mon, 31 Aug 2020 15:13:49 +0000
Labels:       app=mariadb
              chart=mariadb-7.3.0
              component=master
              controller-revision-hash=gitea-mariadb-594cb7b487
              release=gitea
              statefulset.kubernetes.io/pod-name=gitea-mariadb-0
Annotations:  <none>
Status:       Running
IP:           10.1.91.99
IPs:
  IP:           10.1.91.99
Controlled By:  StatefulSet/gitea-mariadb
Containers:
  mariadb:
    Container ID:   containerd://eb2de482095206b5ad3e1b3481e2d15e1a2341572fb281e9239be6c39b939fe3
    Image:          docker.io/bitnami/mariadb:10.3.20-debian-9-r19
    Image ID:       docker.io/bitnami/mariadb@sha256:f582aaa5672e3055c769d98ce1ed6a22140137232b8d012944abd7918c3b37bf
    Port:           3306/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Mon, 31 Aug 2020 15:29:52 +0000
      Finished:     Mon, 31 Aug 2020 15:29:52 +0000
    Ready:          False
    Restart Count:  8
    Liveness:       exec [sh -c password_aux="${MARIADB_ROOT_PASSWORD:-}"
if [ -f "${MARIADB_ROOT_PASSWORD_FILE:-}" ]; then
    password_aux=$(cat $MARIADB_ROOT_PASSWORD_FILE)
fi
mysqladmin status -uroot -p$password_aux
] delay=120s timeout=1s period=10s #success=1 #failure=3
    Readiness:  exec [sh -c password_aux="${MARIADB_ROOT_PASSWORD:-}"
if [ -f "${MARIADB_ROOT_PASSWORD_FILE:-}" ]; then
    password_aux=$(cat $MARIADB_ROOT_PASSWORD_FILE)
fi
mysqladmin status -uroot -p$password_aux
] delay=30s timeout=1s period=10s #success=1 #failure=3
    Environment:
      MARIADB_ROOT_PASSWORD:  <set to the key 'mariadb-root-password' in secret 'gitea-mariadb'>  Optional: false
      MARIADB_USER:           gitea
      MARIADB_PASSWORD:       <set to the key 'mariadb-password' in secret 'gitea-mariadb'>  Optional: false
      MARIADB_DATABASE:       gitea
    Mounts:
      /bitnami/mariadb from data (rw)
      /opt/bitnami/mariadb/conf/my.cnf from config (rw,path="my.cnf")
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-swhkg (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      gitea-mariadb
    Optional:  false
  data:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  default-token-swhkg:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-swhkg
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                 From                    Message
  ----     ------     ----                ----                    -------
  Normal   Scheduled  16m                 default-scheduler       Successfully assigned gitea/gitea-mariadb-0 to k8s-pi-wrkr01
  Normal   Pulled     14m (x5 over 16m)   kubelet, k8s-pi-wrkr01  Container image "docker.io/bitnami/mariadb:10.3.20-debian-9-r19" already present on machine
  Normal   Created    14m (x5 over 16m)   kubelet, k8s-pi-wrkr01  Created container mariadb
  Normal   Started    14m (x5 over 16m)   kubelet, k8s-pi-wrkr01  Started container mariadb
  Warning  BackOff    92s (x76 over 16m)  kubelet, k8s-pi-wrkr01  Back-off restarting failed container
ubuntu@k8s-pi-master:~$

ubuntu@k8s-pi-master:~$ uname -a
Linux k8s-pi-master 5.4.0-1015-raspi #15-Ubuntu SMP Fri Jul 10 05:34:24 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux
ubuntu@k8s-pi-master:~$
`

**Comment by techknowlogick** [comment]
Please use official helm chart, as well report any issues with it there: https://gitea.com/gitea/helm-chart/ 

Bitnami may not provide a mysql chart that supports arm64, which would cause this problem, a workaround would be to use an external mysql db (https://github.com/presslabs/mysql-operator/ is an operator that I can personally recommend)
