### ISSUE TITLE
Cannot import local repositories

### ISSUE THREAD

**Issue by johnnybubonic** [go-gitea/gitea#12678]
- Gitea version (or commit ref): `1.12.3 built with GNU Make 4.1, go1.14.6 : bindata, sqlite, sqlite_unlock_notify` (via [precompiled binary](https://dl.gitea.io/gitea/1.12.3/gitea-1.12.3-linux-amd64))
- Git version:2.18.4
- Operating system: CentOS 8.2.2004
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X] No
  - [ ] Not relevant
- Log gist: N/A

## Description

I am unable to perform local imports.

When going to `/repo/migrate` and using `file:///tmp/test.git``` as the clone-from URL, I get the following error:

`The local path is invalid. It does not exist or is not a directory.`

yet:

```
[git@git ~]$ file /tmp/test.git/
/tmp/test.git/: directory
[git@git ~]$ cd /tmp/
[git@git tmp]$ git clone file:///tmp/test.git test2
Cloning into 'test2'...
remote: Enumerating objects: 120, done.
remote: Counting objects: 100% (120/120), done.
remote: Compressing objects: 100% (100/100), done.
remote: Total 120 (delta 40), reused 0 (delta 0)
Receiving objects: 100% (120/120), 11.35 KiB | 1.03 MiB/s, done.
Resolving deltas: 100% (40/40), done.
[git@git tmp]$ ls test.git test2
test2:
date  test.py  test.txt

test.git:
branches  config  description  gl-conf  HEAD  hooks  info  objects  refs
```

## Screenshots

![Screenshot from 2020-09-02 05-11-42](https://user-images.githubusercontent.com/8520897/91963023-4fdb8180-ecdb-11ea-87b3-b768599d9064.png)

Scrubbed app.ini:
[app.ini.txt](https://github.com/go-gitea/gitea/files/5161252/app.ini.txt)

Interestingly, I have `May Import Local Repositories` checked in the user settings for that profile, yet:

```
ariaDB [git]> SELECT max_repo_creation,is_active,is_admin,is_restricted,allow_import_local FROM user WHERE name LIKE 'brent.s%';
+-------------------+-----------+----------+---------------+--------------------+
| max_repo_creation | is_active | is_admin | is_restricted | allow_import_local |
+-------------------+-----------+----------+---------------+--------------------+
|                -1 |         1 |        1 |             0 |                  0 |
+-------------------+-----------+----------+---------------+--------------------+
1 row in set (0.001 sec)
```

It appears the database does not actually update that if the permission is granted **after** user creation (untested for new accounts). Even when I change `allow_import_local` to `1`, however, the same behaviour occurs (`The local path is invalid. It does not exist or is not a directory.`).

**Comment by lunny** [comment]
Could you try `/tmp/test.git`?

**Comment by johnnybubonic** [comment]
On Sep 2, 2020 08:56, Lunny Xiao <notifications@github.com> wrote:
Could you try /tmp/test.git?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
...Embarrassingly, that works. I don't know why I didn't try that.Could support for RFC 3986 (file://<absolute path> URI) be added, since that URI works with git proper?

**Comment by KN4CK3R** [comment]
Could you try it again? This problem should be fixed already. It works for me with and without slash and the plain Git migration.
