### ISSUE TITLE
"invalid character '<' looking for beginning of value" (Failure when pushing to empty repo)

### ISSUE THREAD

**Issue by johnnybubonic** [go-gitea/gitea#12676]
**NOTE:** All references to the real URL/domain have been replaced with **git.foo.bar**.

- Gitea version (or commit ref): `1.12.3 built with GNU Make 4.1, go1.14.6 : bindata, sqlite, sqlite_unlock_notify` (via [precompiled binary](https://dl.gitea.io/gitea/1.12.3/gitea-1.12.3-linux-amd64))
- Git version:2.18.4
- Operating system: CentOS 8.2.2004
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X] No
  - [ ] Not relevant
- Log gist: N/A

## Description

I am trying to migrate repositories from a gitolite instance into gitea.

I am able to create the repositories just fine from the Swagger API, but when I add the SSH URL as a remote and attempt to push to it:

```
$ git push --porcelain gitea master
Gitea: Internal Server Error
invalid character '<' looking for beginning of value
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
Which is, of course, weird. SSH even does it:

```
$ ssh git@git.foo.bar
PTY allocation request failed on channel 0
Gitea: Internal error
Failed to check provided key: invalid character '<' looking for beginning of value
Connection to git.foo.bar closed.
```

Okay, so a little more information this time, but nothing terribly helpful on my end. (Worth nothing that I am not using the internal SSH server, I'm using the host's. Yes, I've run **all** of the `Maintenance Operations` under `https://git.foo.bar/admin` several times, including `Update the '.ssh/authorized_keys' file with Gitea SSH keys. (...)` and `Resynchronize pre-receive, update and post-receive hooks of all repositories.`.)

To rule it out, I generated a fresh SSH key via `ssh-keygen -t rsa -b 4096`, nothing fancy. Still no dice, same behaviour.

The logs, even when cranked up to `trace`, provide no helpful info (but can confirm they are, indeed, logging at trace level) - they don't even show any acknowledgment of the connection attempt.

It seems to happen regardless if I push to a repo with custom hooks or none at all, a personal repo or org/team repo, etc.

And just in case,

```
# sudo -u git USER=git HOME=/opt/git GITEA_WORK_DIR=/opt/git /usr/local/bin/gitea --config /etc/gitea/app.ini doctor
[ 1 ] Check paths and basic configuration
- Configuration File Path:   '/etc/gitea/app.ini'
- Repository Root Path:      '/opt/git/repos'
- Data Root Path:            '/opt/git/data'
- Custom File Root Path:     '/opt/git/custom'
- Work directory:            '/opt/git'
- Log Root Path:             '/opt/git/log'
OK.

[ 2 ] Check Database Version
OK.

[ 3 ] Check if OpenSSH authorized_keys file is up-to-date
OK.
```

## Screenshots

N/A

**Comment by johnnybubonic** [comment]
Scrubbed app.ini:

[app.ini.txt](https://github.com/go-gitea/gitea/files/5160942/app.ini.txt)

**Comment by johnnybubonic** [comment]
AHA! FOUND IT.

It's the socket. Reproducible.

```
PROTOCOL = fcgi+unix
HTTP_ADDR = /run/gitea/gitea.sock
UNIX_SOCKET_PERMISSION = 660
```

with the following Nginx configuration:

```
# Standard Nginx virtualhost boilerplate on CentOS 8 here
# ...
location / {
                include /etc/nginx/fastcgi_params;
                fastcgi_pass unix:/var/run/gitea/gitea.sock;
}
```

(You will need to alter some Nginx contexts and booleans if you have SELinux enabled. I can't recall them off the top of my head, but I wasn't getting anything in the SELinux audit log so it's unrelated. I have confirmed it is reproducible with SELinux disabled.)

Reverse-proxying via Nginx to an fcgi+unix socket will let the web app work just fine, but for whatever reason it seems gitea *hates* being run in `fcgi+unix` mode when it comes to SSH.

It's not a big deal, I can just use HTTP instead, but I was hoping to take advantage of some of the performance benefits that a socket would have. It'd be fantastic if this could be resolved. 👍

**Comment by zeripath** [comment]
The problem likely lies in here:

https://github.com/go-gitea/gitea/blob/702e98c5ec7b11f3c988d61dccbec71e1e69a8bd/modules/private/internal.go#L37-L50

**Comment by zeripath** [comment]
Now it's difficult because with fcgi you're not necessarily supposed to talk directly to the Gitea socket - be it a TCP port or a Unix port.

So if Gitea serv is going to be able to talk to the running Gitea server you have to allow local services to talk to the fcgi server - nginx in your case. 

Now I see that you do not set a LOCAL_ROOT_URL so the Gitea serv process is trying to talk directly to your ROOT_URL as determined here:

https://github.com/go-gitea/gitea/blob/fb70b5d207d8a0c3c2ce9eb04b361146a347d894/modules/setting/setting.go#L637

And 

https://github.com/go-gitea/gitea/blob/fb70b5d207d8a0c3c2ce9eb04b361146a347d894/modules/setting/setting.go#L646

Presumably this is not allowed or accounted for by your network and nginx configuration. So you need to set your LOCAL_ROOT_URL appropriately.

**Comment by johnnybubonic** [comment]
i was under the impression i was *not* to set a LOCAL_ROOT_URL if using IPC sockets?

**Comment by zeripath** [comment]
You need to be able to get to the nginx server - so if the standard ROOT_URL cannot be used to get to the gitea server then... you need to set LOCAL_ROOT_URL to something that will get you there.

(I'm kinda guessing because I don't know what is being returned when gitea tries to talk to the server - you could adjust the authorized_keys to call curl on the ROOT_URL/api/internal/serv/none/{:keyid} with a header: Authorization: Bearer {;InternalToken}.)

**Comment by johnnybubonic** [comment]
Aha- it looks like `gitea serve` does indeed need to reach Nginx if it's running in socket mode. Found this in my Nginx logs:

`"GET /api/internal/serv/none/6 HTTP/1.1" 200 2213 "-" "GiteaServer"`

That... seems wrong. Why wouldn't `gitea serve` just pull the key info and ACL directly from gitea's database instead of making a call to the API?

**Comment by techknowlogick** [comment]
>  directly from gitea's database instead of making a call to the API?

it's to reduce duplication of code and make things more robist, this way SSH connections and http connections both use same logic. Otherwise on connections a new DB connection would be required, this is especially bad for sqlite as it can cause deadlocks.

**Comment by zeripath** [comment]
It also means you don't have to have SSH running in the same place as your server.

**Comment by johnnybubonic** [comment]
At the cost of performance, but yeah, I guess that makes sense. I'll just stick with the http reverse proxy then; there's no benefit to me proxying to a FastCGI socket if it's just making another HTTP call anyways.

Thanks.

**Comment by zeripath** [comment]
Use the Unix socket with the  proxy that's likely to be faster and has less chance of running out of TCP ports. Gitea serv will then be able to talk to that socket directly
