### ISSUE TITLE
Kubernetes helm chart install failed to start PODs on Raspberry Pi 4

### ISSUE THREAD

**Issue by babvin** [go-gitea/gitea#12671]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:
- Chart:   helm repo add gitea-charts https://dl.gitea.io/charts/
               helm install gitea gitea-charts/gitea --namespace gitea --values gitea-values.yaml
## Description

...
`
NAME                                   READY   STATUS                  RESTARTS   AGE
pod/gitea-0                            0/1     Init:CrashLoopBackOff   4          2m54s
pod/gitea-memcached-54b5f9d7c7-8jx48   0/1     CrashLoopBackOff        4          2m54s
pod/gitea-postgresql-0                 0/1     CrashLoopBackOff        4          2m54s

NAME                                TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)     AGE
service/gitea-http                  ClusterIP   None             <none>        3000/TCP    2m54s
service/gitea-memcached             ClusterIP   10.152.183.129   <none>        11211/TCP   2m54s
service/gitea-postgresql            ClusterIP   10.152.183.223   <none>        5432/TCP    2m54s
service/gitea-postgresql-headless   ClusterIP   None             <none>        5432/TCP    2m54s
service/gitea-ssh                   ClusterIP   None             <none>        22/TCP      2m54s

NAME                              READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/gitea-memcached   0/1     1            0           2m54s

NAME                                         DESIRED   CURRENT   READY   AGE
replicaset.apps/gitea-memcached-54b5f9d7c7   1         1         0       2m54s

NAME                                READY   AGE
statefulset.apps/gitea              0/1     2m54s
statefulset.apps/gitea-postgresql   0/1     2m54s
Name:         gitea-0
Namespace:    gitea
Priority:     0
Node:         k8s-pi-wrkr01/192.168.15.17
Start Time:   Tue, 01 Sep 2020 07:14:00 +0530
Labels:       app.kubernetes.io/instance=gitea
              app.kubernetes.io/name=gitea
              controller-revision-hash=gitea-7655cb7b7c
              statefulset.kubernetes.io/pod-name=gitea-0
Annotations:  checksum/config: 9b8dbebfdbf02a13618d9a9f7388fb587e0841bb598f4c4b218f989b9ab127c2
Status:       Pending
IP:           10.1.91.110
IPs:
  IP:           10.1.91.110
Controlled By:  StatefulSet/gitea
Init Containers:
  init:
    Container ID:  containerd://ff684db2cb5c762641a7018f8465c61ef8dec24d332dd3b3b585c3fe4e576e8f
    Image:         gitea/gitea:1.12.3
    Image ID:      docker.io/gitea/gitea@sha256:a94e3542a9b5967d9ba3b7d2eb8630c1d7b61776326addcfd4fba6ab4f4f91db
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/sh
      -c
      mkdir -p /data/gitea/conf
      cp /etc/gitea/conf/app.ini /data/gitea/conf/app.ini
      chmod a+rwx /data/gitea/conf/app.ini
      nc -v -w2 -z gitea-postgresql 5432 && \
      su git -c ' \
      set -x; \
      gitea migrate; \
      gitea admin create-user --username  gitea_admin --password 'r8sA8CPHD9!bt6d' --email gitea@local.domain --admin \
      || \
      gitea admin change-password --username gitea_admin --password 'r8sA8CPHD9!bt6d'; \
      '
    State:          Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Tue, 01 Sep 2020 07:17:06 +0530
      Finished:     Tue, 01 Sep 2020 07:17:07 +0530
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Tue, 01 Sep 2020 07:15:43 +0530
      Finished:     Tue, 01 Sep 2020 07:15:44 +0530
    Ready:          False
    Restart Count:  5
    Environment:
      SCRIPT:  mkdir -p /data/gitea/conf
               cp /etc/gitea/conf/app.ini /data/gitea/conf/app.ini
               chmod a+rwx /data/gitea/conf/app.ini
               nc -v -w2 -z gitea-postgresql 5432 && \
               su git -c ' \
               set -x; \
               gitea migrate; \
               gitea admin create-user --username  gitea_admin --password 'r8sA8CPHD9!bt6d' --email gitea@local.domain --admin \
               || \
               gitea admin change-password --username gitea_admin --password 'r8sA8CPHD9!bt6d'; \
               '
    Mounts:
      /data from data (rw)
      /etc/gitea/conf from config (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-kr5zw (ro)
Containers:
  gitea:
    Container ID:   
    Image:          gitea/gitea:1.12.3
    Image ID:       
    Ports:          22/TCP, 3000/TCP
    Host Ports:     0/TCP, 0/TCP
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Liveness:       tcp-socket :http delay=200s timeout=1s period=10s #success=1 #failure=10
    Readiness:      tcp-socket :http delay=5s timeout=1s period=10s #success=1 #failure=3
    Environment:
      SSH_LISTEN_PORT:  22
      SSH_PORT:         22
    Mounts:
      /data from data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-kr5zw (ro)
Conditions:
  Type              Status
  Initialized       False 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  data-gitea-0
    ReadOnly:   false
  config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      gitea
    Optional:  false
  default-token-kr5zw:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-kr5zw
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                  From                    Message
  ----     ------     ----                 ----                    -------
  Normal   Scheduled  3m9s                 default-scheduler       Successfully assigned gitea/gitea-0 to k8s-pi-wrkr01
  Normal   Pulled     87s (x5 over 3m7s)   kubelet, k8s-pi-wrkr01  Container image "gitea/gitea:1.12.3" already present on machine
  Normal   Created    87s (x5 over 3m7s)   kubelet, k8s-pi-wrkr01  Created container init
  Normal   Started    86s (x5 over 3m6s)   kubelet, k8s-pi-wrkr01  Started container init
  Warning  BackOff    57s (x10 over 3m1s)  kubelet, k8s-pi-wrkr01  Back-off restarting failed container
Name:         gitea-memcached-54b5f9d7c7-8jx48
Namespace:    gitea
Priority:     0
Node:         k8s-pi-wrkr01/192.168.15.17
Start Time:   Tue, 01 Sep 2020 07:14:00 +0530
Labels:       app.kubernetes.io/instance=gitea
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=memcached
              helm.sh/chart=memcached-4.2.20
              pod-template-hash=54b5f9d7c7
Annotations:  <none>
Status:       Running
IP:           10.1.91.109
IPs:
  IP:           10.1.91.109
Controlled By:  ReplicaSet/gitea-memcached-54b5f9d7c7
Containers:
  memcached:
    Container ID:  containerd://c44f2d4ea9abfd5306ccb0db8918fab6acd86fb0f83366e06797556c47d80026
    Image:         docker.io/bitnami/memcached:1.6.6-debian-10-r54
    Image ID:      docker.io/bitnami/memcached@sha256:d74d2d6594054a56c1ccca816ee52fa8bdf26ed42d363c2bf7ba0c5caba6125c
    Port:          11211/TCP
    Host Port:     0/TCP
    Args:
      /run.sh
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Tue, 01 Sep 2020 07:17:12 +0530
      Finished:     Tue, 01 Sep 2020 07:17:12 +0530
    Ready:          False
    Restart Count:  5
    Requests:
      cpu:      250m
      memory:   256Mi
    Liveness:   tcp-socket :memcache delay=30s timeout=5s period=10s #success=1 #failure=6
    Readiness:  tcp-socket :memcache delay=5s timeout=3s period=5s #success=1 #failure=3
    Environment:
      BITNAMI_DEBUG:       false
      MEMCACHED_USERNAME:  
      MEMCACHED_PASSWORD:  <set to the key 'memcached-password' in secret 'gitea-memcached'>  Optional: false
    Mounts:
      /tmp from tmp (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-kr5zw (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  tmp:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  default-token-kr5zw:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-kr5zw
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                    From                    Message
  ----     ------     ----                   ----                    -------
  Normal   Scheduled  3m23s                  default-scheduler       Successfully assigned gitea/gitea-memcached-54b5f9d7c7-8jx48 to k8s-pi-wrkr01
  Warning  BackOff    114s (x10 over 3m18s)  kubelet, k8s-pi-wrkr01  Back-off restarting failed container
  Normal   Pulled     100s (x5 over 3m22s)   kubelet, k8s-pi-wrkr01  Container image "docker.io/bitnami/memcached:1.6.6-debian-10-r54" already present on machine
  Normal   Created    99s (x5 over 3m21s)    kubelet, k8s-pi-wrkr01  Created container memcached
  Normal   Started    99s (x5 over 3m20s)    kubelet, k8s-pi-wrkr01  Started container memcached
Name:         gitea-postgresql-0
Namespace:    gitea
Priority:     0
Node:         k8s-pi-wrkr01/192.168.15.17
Start Time:   Tue, 01 Sep 2020 07:14:00 +0530
Labels:       app=postgresql
              chart=postgresql-8.6.4
              controller-revision-hash=gitea-postgresql-79c8f79fc8
              heritage=Helm
              release=gitea
              role=master
              statefulset.kubernetes.io/pod-name=gitea-postgresql-0
Annotations:  <none>
Status:       Running
IP:           10.1.91.111
IPs:
  IP:           10.1.91.111
Controlled By:  StatefulSet/gitea-postgresql
Containers:
  gitea-postgresql:
    Container ID:   containerd://b116e52162e99c9f652556c71fa16b444782bf18cee4684ab2963a2db1c64ecf
    Image:          docker.io/bitnami/postgresql:11.7.0-debian-10-r26
    Image ID:       docker.io/bitnami/postgresql@sha256:b9ad60ddf0acd04ae559770314c6d97393cc92d4fd057f9b92b2947a80a26cc9
    Port:           5432/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Tue, 01 Sep 2020 07:17:10 +0530
      Finished:     Tue, 01 Sep 2020 07:17:10 +0530
    Ready:          False
    Restart Count:  5
    Requests:
      cpu:      250m
      memory:   256Mi
    Liveness:   exec [/bin/sh -c exec pg_isready -U "gitea" -d "gitea" -h 127.0.0.1 -p 5432] delay=30s timeout=5s period=10s #success=1 #failure=6
    Readiness:  exec [/bin/sh -c -e exec pg_isready -U "gitea" -d "gitea" -h 127.0.0.1 -p 5432
[ -f /opt/bitnami/postgresql/tmp/.initialized ] || [ -f /bitnami/postgresql/.initialized ]
] delay=5s timeout=5s period=10s #success=1 #failure=6
    Environment:
      BITNAMI_DEBUG:           false
      POSTGRESQL_PORT_NUMBER:  5432
      POSTGRESQL_VOLUME_DIR:   /bitnami/postgresql
      PGDATA:                  /bitnami/postgresql/data
      POSTGRES_USER:           gitea
      POSTGRES_PASSWORD:       <set to the key 'postgresql-password' in secret 'gitea-postgresql'>  Optional: false
      POSTGRES_DB:             gitea
      POSTGRESQL_ENABLE_LDAP:  no
    Mounts:
      /bitnami/postgresql from data (rw)
      /dev/shm from dshm (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-kr5zw (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  data-gitea-postgresql-0
    ReadOnly:   false
  dshm:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     Memory
    SizeLimit:  1Gi
  default-token-kr5zw:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-kr5zw
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                    From                    Message
  ----     ------     ----                   ----                    -------
  Normal   Scheduled  3m35s                  default-scheduler       Successfully assigned gitea/gitea-postgresql-0 to k8s-pi-wrkr01
  Warning  BackOff    2m9s (x10 over 3m29s)  kubelet, k8s-pi-wrkr01  Back-off restarting failed container
  Normal   Pulled     114s (x5 over 3m32s)   kubelet, k8s-pi-wrkr01  Container image "docker.io/bitnami/postgresql:11.7.0-debian-10-r26" already present on machine
  Normal   Created    114s (x5 over 3m32s)   kubelet, k8s-pi-wrkr01  Created container gitea-postgresql
  Normal   Started    113s (x5 over 3m31s)   kubelet, k8s-pi-wrkr01  Started container gitea-postgresql
# Default values for gitea.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: gitea/gitea
  version: 1.12.3
  pullPolicy: Always

imagePullSecrets: []

service:
  http:
    type: ClusterIP
    port: 3000
  ssh:
    type: ClusterIP
    port: 22
    #loadBalancerIP:
    #nodePort:
    annotations:

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - git.example.com
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - git.example.com

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

statefulset:
  terminationGracePeriodSeconds: 60

persistence:
  enabled: true
  # existingClaim: gitea
  size: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClass: nfs-client

gitea:
  admin:
    username: gitea_admin
    password: r8sA8CPHD9!bt6d
    email: "gitea@local.domain"

  ldap:
    enabled: false
    name: ""
    securityProtocol: ""
    host: ""
    port: ""
    userSearchBase: ""
    userFilter: ""
    adminFilter: ""
    emailAttribute: ""
    bindDn: ""
    bindPassword: ""
    usernameAttribute: ""

  config: {}
  #  APP_NAME: "Gitea: Git with a cup of tea"
  #  RUN_MODE: dev   
  #   
  #  server:
  #    SSH_PORT: 22
  #
  #  security:
  #    PASSWORD_COMPLEXITY: spec

  database:
    builtIn:
      postgresql:
        enabled: true
      mysql:
        enabled: false

  cache:
    builtIn:
      enabled: true

memcached:
  service:
    port: 11211

postgresql:
  global:
    postgresql:
      postgresqlDatabase: gitea
      postgresqlUsername: gitea
      postgresqlPassword: gitea
      servicePort: 5432
  persistence:
    size: 10Gi
    accessModes:
      - ReadWriteOnce
    storageClass: nfs-client
mysql:
  root:
    password: gitea
  db:
    user: gitea
    password: gitea
    name: gitea
  service:
    port: 3306
  persistence:
    size: 10Gi

NAME                      STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS        AGE
data-gitea-0              Bound    pvc-4192543e-b50a-4bd7-a36d-45b779b7d484   10Gi       RWO            nfs-client          29m
data-gitea-postgresql-0   Bound    pvc-366d93bd-2d54-443e-9bc7-5cf8a2c8d38f   10Gi       RWO            microk8s-hostpath   29m

`

**Comment by lunny** [comment]
Please send report to https://gitea.com/gitea/helm-chart
