### ISSUE TITLE
Github Actions-like CI/CD files

### ISSUE THREAD

**Issue by lstolcman** [go-gitea/gitea#12673]
Hi

Recently I discovered https://github.com/nektos/act which tries to parse and execute github actions files (`.github/workflows`).
The tool is written in Go

Thought about using github actions workflows within gitea similarily they do in github, so here I am creating feature issue for this :)

*Example screenshots*

gitea:
<img width="963" alt="obraz" src="https://user-images.githubusercontent.com/4583553/91873858-d52e4a00-ec79-11ea-912d-36f6ebebfef1.png">

github:
<img width="1059" alt="obraz" src="https://user-images.githubusercontent.com/4583553/91873933-ebd4a100-ec79-11ea-9888-c3ebadf6235b.png">
--
<img width="1265" alt="obraz" src="https://user-images.githubusercontent.com/4583553/91873973-f4c57280-ec79-11ea-961f-1415016b3165.png">
--
<img width="1649" alt="obraz" src="https://user-images.githubusercontent.com/4583553/91874071-10307d80-ec7a-11ea-9c0b-43fff0ede776.png">

**Comment by techknowlogick** [comment]
Thanks for this request. Currently we are attempting to keep the scope of gitea limited as we only have so much developer capacity for the project and recommend utilizing a purpose built CI/CD tool (there are several that support Gitea listed here: https://docs.gitea.io/en-us/ci-cd/). We are very happy with Drone specifically and use it for the Gitea project itself (some Gitea contributors also contribute to drone)

Perhaps we will revisit this in future, but for now I will close this.
