### ISSUE TITLE
Dropzone.js error on uploading file with 32MB+ size

### ISSUE THREAD

**Issue by SatoshiOokami** [go-gitea/gitea#12680]
- Gitea version (or commit ref): 1.12.3
- Git version: 2.28
- Operating system: win10 station, win server 2008 server
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

I'm unable to upload any files above 32MB despite setting the MAX_SIZE attribute.
Whenever I try to upload anything bigger than 32MB, the dropzone.js throws an error (see below).
Anything below 32MB works well. Is there a hard limit that cannot be reconfigured? 

This is my attachment section in **app.ini**.
`[attachment]`
`ENABLED = true`
`MAX_SIZE = 512`
`MAX_FILES = 2`
`STORE_TYPE = local`
`PATH = D:\GiteaAttachments`
`ALLOWED_TYPES = */*`

## Screenshots

![image](https://user-images.githubusercontent.com/46527284/91980574-c605d580-ed27-11ea-9083-93cd653022c1.png)
![image](https://user-images.githubusercontent.com/46527284/91980604-d027d400-ed27-11ea-8630-2c8215bd3a0c.png)

**Comment by techknowlogick** [comment]
Are you using a reverse proxy such as Nginx or Apache HTTPD?

**Comment by SatoshiOokami** [comment]
> Are you using a reverse proxy such as Nginx or Apache HTTPD?

Yes, we are hosting Gitea on an IIS server so the upload limit was due to IIS settings.
We have changed the upload limit in the web.config and now the upload is correct.

Thank you for helping!
