### ISSUE TITLE
Cleaner ui for admin, repo settings, and user settings page

### ISSUE THREAD

**Issue by pgaskin** [go-gitea/gitea#1269]
Same as #1253 but for other pages. Also will made repo ui more responsive.

### New look:

![kazam_screenshot_00013](https://cloud.githubusercontent.com/assets/13909717/23967030/cf2a6cc8-0993-11e7-9a29-fe4e4dd42f9a.png)
![kazam_screenshot_00014](https://cloud.githubusercontent.com/assets/13909717/23967029/cf29cbb0-0993-11e7-9991-ccaa2a1749b9.png)
![kazam_screenshot_00015](https://cloud.githubusercontent.com/assets/13909717/23967031/cf2b27e4-0993-11e7-8440-b71872d77059.png)
![kazam_screenshot_00016](https://cloud.githubusercontent.com/assets/13909717/23967032/cf30827a-0993-11e7-8229-8333886f3beb.png)
![kazam_screenshot_00017](https://cloud.githubusercontent.com/assets/13909717/23967034/cf3793e4-0993-11e7-82bb-bdc02df6b83c.png)
![kazam_screenshot_00018](https://cloud.githubusercontent.com/assets/13909717/23967033/cf3755fa-0993-11e7-91c0-5538656c740d.png)

**Comment by pgaskin** [comment]
Requested by @bkcsoft : https://github.com/go-gitea/gitea/pull/1255#issuecomment-286844405

\cc @bkcsoft @tboerger @strk

**Comment by pgaskin** [comment]
1. Move content and menu out of grid
2. Menu css: `justify-content: center;padding-top: 15px;margin-top: -15px;margin-bottom: 15px;background-color: #FAFAFA;border-width: 1px;`
3. Menu classes: `ui secondary pointing tabular top attached borderless menu stackable navbar`
4. Remove .header.item and move menu up above the container

And on the repo view, also add class stackable to the tabs too.

**Comment by pgaskin** [comment]
Also fixes a lot of issues for #35

**Comment by bkcsoft** [comment]
@geek1011 Now that I get to see the mobile version as well. Is there any way to make the navbar tabs a dropdown?

**Comment by pgaskin** [comment]
@bkcsoft Yes, and I'll do that in my next PR. Also, I need to add the meta responsive tags as soon as I finish a few more fixes.

**Comment by tboerger** [comment]
:100:
