### ISSUE TITLE
Possible improvements to YAML frontmatter handling?

### ISSUE THREAD

**Issue by TrollDecker** [go-gitea/gitea#12703]
- Gitea version (or commit ref): 1.12.3

## Description

:wave: :slightly_smiling_face:  

Thank you for the frontmatter formatting thingy for Markdown files. Really helps to tidy things up.
Only thing is, I think there's a bit of room for improvement?

For a start, I'm not keen on having each field be a column, because it squishes everything up when it reaches page width and just makes things messy, like in the screenshot below. Would it not make more sense to have each field be a row instead? If need be, possibly collapsible ones?

And in addition,  I feel like YAML collections should be treated more like lists? in the below screenshot, they just render as something akin to an array without any comma separation, making it near impossible to tell single- and multi-word items apart. Less than ideal.

## Screenshots

![Screenshot_2020-09-03 BookData(1)](https://user-images.githubusercontent.com/4513715/92164482-5417b400-ee2d-11ea-8185-af4f8bc4da6a.png)

**Comment by zeripath** [comment]
The rendering essentially comes from yuin/goldmark-meta so it might be better to put a feature request there.

However there are a couple of options which gitea provides: setting the gitea value or the gitea meta value to none will hide it, table will show the  table and details will hide the table behind a details and summary.

**Comment by TrollDecker** [comment]
Ah, fair enough, thanks. :sweat_smile:

**Comment by 6543** [comment]
not opsible for now see https://github.com/yuin/goldmark-meta/pull/6
