### ISSUE TITLE
rendering of org readme files, in particular headings bullets and codeblocks

### ISSUE THREAD

**Issue by olymk2** [go-gitea/gitea#1272]
I noticed that gitea does not render org files which would be rendered on github I would like to see this supported.

Is this something that would be reasonably easy to add, anyone able to outline what might be needed in case I decide to tackle the issue.

I generally use org over md because it has better table support and allows you to run the code blocks directly instead of copying and pasting.

not sure if golang has an org parser currently to aid in adding this feature ?

**Comment by sondr3** [comment]
I wa looking for this as well, but primarily for my dotfiles. I now there's a Org mode parser called [Goorgeous](https://github.com/chaseadamsio/goorgeous), but I'm not sure how easy it would be to hook up to Gitea.

**Comment by lunny** [comment]
I think maybe it's not too difficult to support that with a `.org` file extension?

**Comment by sondr3** [comment]
Apparently the author of Gogs has created a branch for this and the bug that as blocking it has been fixed, so you could potentially just use that (https://github.com/go-gitea/gitea/issues/1424). I'd love to help but I'm currently traveling and without a computer.

**Comment by lunny** [comment]
So this is a duplicated with #1424 ?

**Comment by lunny** [comment]
resolved by #2525
