### ISSUE TITLE
Add Kanban/project management features to comparison table

### ISSUE THREAD

**Issue by Extarys** [go-gitea/gitea#12720]
## Description

Please add project management features/kanban to the [gitea comparison table](https://docs.gitea.io/en-us/comparison/).

For reference: 
[GitLab self-hosted comparison](https://about.gitlab.com/pricing/self-managed/feature-comparison/)
[GitHub project management features](https://github.com/features/project-management/)

**Comment by techknowlogick** [comment]
Closing as it exists there under the name of "Issue Boards"

**Comment by Extarys** [comment]
Missed that, I'm sorry!

But for SEO/people searching for this on the internet with keywords, they might miss how this is implemented? I'm not an expert though I'm not sure.

I believe having project management features to Gitea will improve it's user base - if they can find Gitea :yum: What I mean is, Github sells this as a **project management** feature - not as an issue board. Just by how it sounds, github feels more... complete in that sense

I do know that feature was merged recently though and people will most likely still work on extending it's features.

**Comment by techknowlogick** [comment]
@Extarys thanks for details. I've created a PR to at least connect the two in case of a user searching.
