### ISSUE TITLE
update go-org module to latest release

### ISSUE THREAD

**Issue by Iced-Sun** [go-gitea/gitea#12727]
go-org receives quite a few bug-fixes and enhancements since v0.1.9. Would it be possible to update go-org to the latest version? Thanks.

**Comment by zeripath** [comment]
Hi! 

For future reference should you want to create a PR that updates a dependency do:

```
git checkout -b update-${dependency} master
go get -u ${dependency}
make vendor
git status
# add missing files with git add
git commit -sm'Update ${dependency}

This PR updates the ${dependency} to version ${version}.
'
git push your-fork update-${dependency}
```

and then open a PR for us.

It's helpful if you can add a few details about the versions changed so we can really see if they're up to date.
