### ISSUE TITLE
Markdown list rendering

### ISSUE THREAD

**Issue by cez81** [go-gitea/gitea#1273]
- Gitea version (or commit ref): 1.1.0+32-g03d7998
- Git version: 2.7.4
- Operating system: Ubuntu 16.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io: (currently 404)
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant

## Description
1. Clone Rails repo, git@github.com:rails/rails.git
2. Check Getting Started section in README.md
3. Compare with https://github.com/rails/rails/blob/master/README.md

Might be related to #1265 but not same problem.

## Screenshots
![rails](https://cloud.githubusercontent.com/assets/9416498/23973668/8726c3d8-09d7-11e7-920d-5d51a8f32814.png)

**Comment by Fastidious** [comment]
Yet, this works: https://try.gitea.io/Fastidious/Test-15/src/master/README.md

It is the space and the new line (see raw).

**Comment by lunny** [comment]
see https://try.gitea.io/lunny/rails/src/master/README.md
@Fastidious did you mean this is because the original markdown file is a wrong format?

**Comment by Fastidious** [comment]
@lunny no, there are parsing issues, I think. What I did is just a workaround.
