### ISSUE TITLE
How to comment to a PR from drone?

### ISSUE THREAD

**Issue by DefinitelyADev** [go-gitea/gitea#12733]
- Gitea version (or commit ref): 1.12.4
- Git version: 2.18.4
- Operating system: Centos
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
Hello, I’m using Gitea as my version control system and Drone as CI for .Net Core projects. Is there an equivalent plugin like the Github Comment for interacting with Gitea or another way to create a comment to the original PR?

Also after a quick look on swagger I did not find an endpoint for ​POST /repos​/{owner}​/{repo}​/pulls​/{index}​/comments

**Comment by 6543** [comment]
this is a usefull idear for [TEA](https://gitea.com/gitea/tea/issues/172) ...

I dont know souch an plugin/image.
What I would do: use an image witch contain curl and use the API

**Comment by TsakiDev** [comment]
@6543 That's what I thought about the api but there isn't an endpoint for POST ​/repos​/{owner}​/{repo}​/pulls​/{index}​/comments

**Comment by 6543** [comment]
@TsakiDev -> https://try.gitea.io/api/swagger#/issue/issueCreateComment

**Comment by 6543** [comment]
it works for both issues & pulls

**Comment by 6543** [comment]
because pulls are extended issues in gitea ...

**Comment by TsakiDev** [comment]
That's great thank you very much for the help and the clarification. 
I will close this now.
