### ISSUE TITLE
"Repository name has already been used" when migrating

### ISSUE THREAD

**Issue by cez81** [go-gitea/gitea#1274]
- Gitea version (or commit ref): 1.1.0+32-g03d7998
- Git version: 2.7.4
- Operating system: Ubuntu 16.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io: (currently 404)
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
1. Start new migration
2. Enter URL of repo (I used https://github.com/puikinsh/Dazzling.git)
3. Enter Repository Name same as original repo
4. Click migrate
5. Error message saying "Repository name has already been used" even though it doesn't
6. Repo is still properly migrated

## Screenshots
![migration](https://cloud.githubusercontent.com/assets/9416498/23974025/6789005c-09d9-11e7-827a-09774a545594.png)

**Comment by lunny** [comment]
maybe you can check if there is the same name directory on the your repos directory

**Comment by cez81** [comment]
I tried multiple times with different random repos that definately didn't already exist. Can't reproduce on https://try.gitea.io now so might be something with my setup.
Closing this for now.
