### ISSUE TITLE
DS918+ - Impossible to clone / pull / push via SSH Gitea

### ISSUE THREAD

**Issue by sebsn86** [go-gitea/gitea#12755]
- Gitea version (or commit ref): 1.12.3
- Git Server version: 2.26.2 
- Operating system: DSM 6.2.3-25426 Update 2 (x64)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description

As [this issue](https://github.com/go-gitea/gitea/issues/5497), I cannot clone, pull / push via SSH Gitea on my Synology
I did all the steps described in the ticket 5497, but I have this error :

`
git clone ssh://gitea@domain.local:7999/xxxxxx/project-example.git
Clonage dans 'project-example'...
Permission denied, please try again.
fatal: Impossible de lire le dépôt distant.

Veuillez vérifier que vous avez les droits d'accès
et que le dépôt existe.
`

But when i try to clone by HTTP mode, it's working perfectly.

**What I have done :**

I installed Gitea on my Synology by following these steps :

- Create .spk file with https://github.com/flipswitchingmonkey/gitea-spk
- Install MariaDB 10, Git Server, PHPMyAdmin, Web Station and Gitea spk on my Synology
- I created my MySQL Database called "gitea" and created User mysql called "gitea"
- I configured Gitea during install process with my private domain and custom HTTP and SSH ports.
- I configured SSH port on my Synology so that it's identical to the one indicated in gitea
- I copied / pasted the public SSH key from my local machine in Gitea UI profile.
- I applied rights on /usr/local/gitea/gitea/.ssh (700) and /usr/local/gitea/gitea/.ssh/authorized_keys (600)
- I runed "Update the '.ssh/authorized_keys' file with gitea SSH keys"
- I added /gitea in /etc/passwd after /var/packages/Gitea/target
- I changed /sbin/nologin by /bin/sh in /etc/passwd
- I checked wheter PubkeyAuthentication is enabled in /etc/sshd_config
- I appended gitea to the administrators group in /etc/group

**Here my app.ini :**

```ini
...
[server]
SSH_DOMAIN                  = domain.local
DOMAIN                            = domain.local
HTTP_PORT                     = 8080
ROOT_URL                       = https://domain.local/
DISABLE_SSH                  = false
SSH_PORT                       = 7999
LFS_START_SERVER      = true
LFS_CONTENT_PATH      = /usr/local/gitea/gitea/data/lfs
LFS_JWT_SECRET          = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
OFFLINE_MODE               = false
START_SSH_SRVER        = true
BUILTIN_SSH_SERVER_USER = 
SSH_LISTEN_PORT          = %(SSH_PORT)s
SSH_CREATE_AUTHORIZED_KEYS_FILE = true
...
```

**Comment by sebsn86** [comment]
Here my ssh log : 
`OpenSSH_8.2p1 Ubuntu-4ubuntu0.1, OpenSSL 1.1.1f  31 Mar 2020
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: include /etc/ssh/ssh_config.d/*.conf matched no files
debug1: /etc/ssh/ssh_config line 21: Applying options for *
debug1: Connecting to domain.local [192.168.1.33] port 7999.
debug1: Connection established.
debug1: identity file /home/<user>/.ssh/id_rsa type 0
debug1: identity file /home/<user>/.ssh/id_rsa-cert type -1
debug1: identity file /home/<user>/.ssh/id_dsa type -1
debug1: identity file /home/<user>/.ssh/id_dsa-cert type -1
debug1: identity file /home/<user>/.ssh/id_ecdsa type -1
debug1: identity file /home/<user>/.ssh/id_ecdsa-cert type -1
debug1: identity file /home/<user>/.ssh/id_ecdsa_sk type -1
debug1: identity file /home/<user>/.ssh/id_ecdsa_sk-cert type -1
debug1: identity file /home/<user>/.ssh/id_ed25519 type -1
debug1: identity file /home/<user>/.ssh/id_ed25519-cert type -1
debug1: identity file /home/<user>/.ssh/id_ed25519_sk type -1
debug1: identity file /home/<user>/.ssh/id_ed25519_sk-cert type -1
debug1: identity file /home/<user>/.ssh/id_xmss type -1
debug1: identity file /home/<user>/.ssh/id_xmss-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_8.2p1 Ubuntu-4ubuntu0.1
debug1: Remote protocol version 2.0, remote software version OpenSSH_7.4
debug1: match: OpenSSH_7.4 pat OpenSSH_7.0*,OpenSSH_7.1*,OpenSSH_7.2*,OpenSSH_7.3*,OpenSSH_7.4*,OpenSSH_7.5*,OpenSSH_7.6*,OpenSSH_7.7* compat 0x04000002
debug1: Authenticating to domain.local:7999 as 'gitea'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: ecdsa-sha2-nistp256
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:PkEQMVjoBj7jO+z7HT/rsryBkJ+TK00WFuiDQ7TjYmw
debug1: Host '[domain.local]:7999' is known and matches the ECDSA host key.
debug1: Found key in /home/<user>/.ssh/known_hosts:5
debug1: rekey out after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey in after 134217728 blocks
debug1: Will attempt key: /home/<user>/.ssh/id_rsa RSA SHA256:Lu4KT00G1PKNxX4PtshTNgygI7bSB1pBGQ2Nd+FM0Is agent
debug1: Will attempt key: /home/<user>/.ssh/id_dsa 
debug1: Will attempt key: /home/<user>/.ssh/id_ecdsa 
debug1: Will attempt key: /home/<user>/.ssh/id_ecdsa_sk 
debug1: Will attempt key: /home/<user>/.ssh/id_ed25519 
debug1: Will attempt key: /home/<user>/.ssh/id_ed25519_sk 
debug1: Will attempt key: /home/<user>/.ssh/id_xmss 
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519,ssh-rsa,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521>
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey,password
debug1: Next authentication method: publickey
debug1: Offering public key: /home/<user>/.ssh/id_rsa RSA SHA256:Lu4KT00G1PKNxX4PtshTNgygI7bSB1pBGQ2Nd+FM0Is agent
debug1: Server accepts key: /home/<user>/.ssh/id_rsa RSA SHA256:Lu4KT00G1PKNxX4PtshTNgygI7bSB1pBGQ2Nd+FM0Is agent
debug1: Authentication succeeded (publickey).
Authenticated to domain.local. ([192.168.1.xx]:7999).
debug1: channel 0: new [client-session]
debug1: Requesting no-more-sessions@openssh.com
debug1: Entering interactive session.
debug1: pledge: network
debug1: client_input_global_request: rtype hostkeys-00@openssh.com want_reply 0
debug1: Remote: Forced command.
debug1: Remote: Port forwarding disabled.
debug1: Remote: X11 forwarding disabled.
debug1: Remote: Agent forwarding disabled.
debug1: Remote: PTY allocation disabled.
debug1: Remote: Forced command.
debug1: Remote: Port forwarding disabled.
debug1: Remote: X11 forwarding disabled.
debug1: Remote: Agent forwarding disabled.
debug1: Remote: PTY allocation disabled.
debug1: Sending environment.
debug1: Sending env LANG = fr_FR.UTF-8
Permission denied, please try again.
debug1: client_input_channel_req: channel 0 rtype exit-status reply 0
debug1: client_input_channel_req: channel 0 rtype eow@openssh.com reply 0
debug1: channel 0: free: client-session, nchannels 1
Transferred: sent 2848, received 3232 bytes, in 0.1 seconds
Bytes per second: sent 50033.3, received 56779.3
debug1: Exit status 1`

**Comment by zeripath** [comment]
> debug1: Sending env LANG = fr_FR.UTF-8
> Permission denied, please try again.

That suggests that the setting of the environment variable is the problem.

Now why it should be I'm not sure.

The code for the internal SSH server is:

https://github.com/go-gitea/gitea/blob/e4b3f35b8d68d6409a280a8e644759e10b091cb1/modules/ssh/ssh.go#L151-L188

And doesn't have any code that would clearly reject based on environment variables being sent - but equally doesn't have a handler for it.

If there is any way to test not sending the LANG that would be useful to confirm that this is the problem. I will take a look at the SSH dependency.

**Comment by zeripath** [comment]
Interestingly there shouldn't be any negative response against the Lang environment request:

https://github.com/gliderlabs/ssh/blob/76cadaa318fd00fe3936af0243cb5daa9df84c73/session.go#L286-L294

Implies that it just gets set - even if we ignore it at present

**Comment by zeripath** [comment]
Ok ignore my first few comments.

Could you please explain which server is intended to service SSH requests? Is it Gitea's internal SSH server or an openSSH server that is running on Synology.

Gitea can run its own SSH server or it can integrate with an already running openSSH server.

`START_SSH_SERVER=true` would be used to switch on the internal server and it looks from your app.ini that you were intending this but then from your comments above it looks like you're trying to set up openSSH.

Which is ir

**Comment by zeripath** [comment]
Assuming you actually intend to use openSSH get rid of the `START_SSH_SRVER` line in your config as it is a) incorrect b) unnecessary and c) confusing.

Now, searching for this exact bug implies that there might be some firewall rules that your Synology has.

https://www.nas-forum.com/forum/topic/56853-r%C3%A9solussh-permission-denied-connection-closed/

> J'ai enlevé toutes les règles sur mon routeur, et du coup j'ai récupéré mon accès SSH :

Implying that these might be the problem but read the earlier comments in that thread in case there's something else missing.

**Comment by sebsn86** [comment]
Hi,

I tried to deactivate SSH in DSM Panel to use gitea SSH server and now, the SSH connection failed. I tried to change SSH port to :

OpenSSH_8.2p1 Ubuntu-4ubuntu0.1, OpenSSL 1.1.1f  31 Mar 2020
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: include /etc/ssh/ssh_config.d/*.conf matched no files
debug1: /etc/ssh/ssh_config line 21: Applying options for *
debug1: Connecting to domain.local [192.168.1.33] port 7998.
debug1: connect to address 192.168.1.xx port 7998: Connection refused
ssh: connect to host domain.local port 7998: Connection refused

The Synology's Firewall is currently deactivated but it's change nothing.

**Comment by sebsn86** [comment]
I deleted the START_SSH_SERVER line too, stop and restart Gitea service, but nothing change

**Comment by sebsn86** [comment]
Here my complete app.ini file : 

APP_NAME = Gitea: Näser repo
RUN_USER = gitea
RUN_MODE = prod

[oauth2]
JWT_SECRET = xbvtK9d_3e7CimTOsdXSc8WEndLfXMpdzbNcv_Wt-tc

[security]
INTERNAL_TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYmYiOjE1OTkxMzIyNjJ9.m9FRHwGsjjCT81EuzkO6YSE5TYtLVWi466V1TIWwLyg
INSTALL_LOCK   = true
SECRET_KEY     = h9aGevWRCQ9n1kCNr6BhHAZI9u4JsPPItPVCKMfT0glITK9OjyVz9xPK0JTrSLSU

[database]
DB_TYPE  = mysql
HOST     = 127.0.0.1:3307
NAME     = gitea
USER     = gitea
PASSWD   = xxxxxxxxx
SCHEMA   = 
SSL_MODE = disable
CHARSET  = utf8
PATH     = /usr/local/gitea/gitea/data/gitea.db

[repository]
ROOT = /usr/local/gitea/gitea/gitea-repositories

[server]
SSH_DOMAIN       = domain.local
DOMAIN           = domain.local
HTTP_PORT        = 8080
ROOT_URL         = https://domain.local/
DISABLE_SSH      = false
SSH_PORT         = 7999
LFS_START_SERVER = true
LFS_CONTENT_PATH = /usr/local/gitea/gitea/data/lfs
LFS_JWT_SECRET   = Ut7NiN7uPxO-5BuLhtz81WX9qkKn7X1oeVjBGGPxTvs
OFFLINE_MODE     = false
BUILTIN_SSH_SERVER_USER = 
SSH_LISTEN_PORT  = %(SSH_PORT)s
SSH_CREATE_AUTHORIZED_KEYS_FILE = true

[mailer]
ENABLED = true
HOST    = mail.infomaniak.com
FROM    = synology@domain.local
USER    = synology@domain.local
PASSWD  = xxxxxxxxxxxxxx

[service]
REGISTER_EMAIL_CONFIRM            = true
ENABLE_NOTIFY_MAIL                = true
DISABLE_REGISTRATION              = false
ALLOW_ONLY_EXTERNAL_REGISTRATION  = false
ENABLE_CAPTCHA                    = false
REQUIRE_SIGNIN_VIEW               = true
DEFAULT_KEEP_EMAIL_PRIVATE        = false
DEFAULT_ALLOW_CREATE_ORGANIZATION = true
DEFAULT_ENABLE_TIMETRACKING       = true
NO_REPLY_ADDRESS                  = noreply.localhost

[picture]
DISABLE_GRAVATAR        = false
ENABLE_FEDERATED_AVATAR = true

[openid]
ENABLE_OPENID_SIGNIN = true
ENABLE_OPENID_SIGNUP = true

[session]
PROVIDER = file

[log]
MODE      = file
LEVEL     = info
ROOT_PATH = /usr/local/gitea/gitea/log

**Comment by sebsn86** [comment]
> Assuming you actually intend to use openSSH get rid of the `START_SSH_SRVER` line in your config as it is a) incorrect b) unnecessary and c) confusing.
> 
> Now, searching for this exact bug implies that there might be some firewall rules that your Synology has.
> 
> https://www.nas-forum.com/forum/topic/56853-r%C3%A9solussh-permission-denied-connection-closed/
> 
> > J'ai enlevé toutes les règles sur mon routeur, et du coup j'ai récupéré mon accès SSH :
> 
> Implying that these might be the problem but read the earlier comments in that thread in case there's something else missing.

If I had this person's concern, the classic SSH connection should be refused too, right?

**Comment by sebsn86** [comment]
Here all files :

/var/packages/Gitea/target/gitea :
![permission-ssh-folder](https://user-images.githubusercontent.com/17740746/92449967-1fa05100-f1bb-11ea-90f1-fa2039750a69.png)

/var/packages/Gitea/target/gitea/.ssh/ :
![permission-authorized-keys](https://user-images.githubusercontent.com/17740746/92450119-52e2e000-f1bb-11ea-8af8-aa3c597c246f.png)

/etc/group :
![synology-administrator-group](https://user-images.githubusercontent.com/17740746/92450904-4c089d00-f1bc-11ea-86af-d8ed80ed6f41.png)

/etc/ssh/sshd_config :
Ciphers aes128-ctr,aes128-gcm@openssh.com,aes192-ctr,aes256-ctr,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com
KexAlgorithms curve25519-sha256,curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512
MACs hmac-sha2-256,hmac-sha2-256-etm@openssh.com,hmac-sha2-512,hmac-sha2-512-etm@openssh.com,umac-128-etm@openssh.com,umac-128@openssh.com
#	$OpenBSD: sshd_config,v 1.100 2016/08/15 12:32:04 naddy Exp $

# This is the sshd server system-wide configuration file.  See
# sshd_config(5) for more information.

# This sshd was compiled with PATH=/usr/bin:/bin:/usr/sbin:/sbin

# The strategy used for options in the default sshd_config shipped with
# OpenSSH is to specify options with their default value where
# possible, but leave them commented.  Uncommented options override the
# default value.

#Port 22
#AddressFamily any
#ListenAddress 0.0.0.0
#ListenAddress ::

#HostKey /etc/ssh/ssh_host_rsa_key
#HostKey /etc/ssh/ssh_host_dsa_key
#HostKey /etc/ssh/ssh_host_ecdsa_key
#HostKey /etc/ssh/ssh_host_ed25519_key

# Ciphers and keying
#RekeyLimit default none

# Logging
SyslogFacility AUTH
LogLevel VERBOSE

# Authentication:

#LoginGraceTime 2m
#PermitRootLogin prohibit-password
#StrictModes yes
#MaxAuthTries 6
#MaxSessions 10

PubkeyAuthentication yes

# The default is to check both .ssh/authorized_keys and .ssh/authorized_keys2
# but this is overridden so installations will only check .ssh/authorized_keys
# AuthorizedKeysFile	.ssh/authorized_keys

#AuthorizedPrincipalsFile none

#AuthorizedKeysCommand none
#AuthorizedKeysCommandUser nobody

# For this to work you will also need host keys in /etc/ssh/ssh_known_hosts
#HostbasedAuthentication no
# Change to yes if you don't trust ~/.ssh/known_hosts for
# HostbasedAuthentication
#IgnoreUserKnownHosts no
# Don't read the user's ~/.rhosts and ~/.shosts files
#IgnoreRhosts yes

# To disable tunneled clear text passwords, change to no here!
PasswordAuthentication yes
#PermitEmptyPasswords no

# Change to no to disable s/key passwords
ChallengeResponseAuthentication no

# Kerberos options
#KerberosAuthentication no
#KerberosOrLocalPasswd yes
#KerberosTicketCleanup yes
#KerberosGetAFSToken no

# GSSAPI options
#GSSAPIAuthentication no
#GSSAPICleanupCredentials yes

# Set this to 'yes' to enable PAM authentication, account processing,
# and session processing. If this is enabled, PAM authentication will
# be allowed through the ChallengeResponseAuthentication and
# PasswordAuthentication.  Depending on your PAM configuration,
# PAM authentication via ChallengeResponseAuthentication may bypass
# the setting of "PermitRootLogin without-password".
# If you just want the PAM account and session checks to run without
# PAM authentication, then enable this but set PasswordAuthentication
# and ChallengeResponseAuthentication to 'no'.
UsePAM yes

#AllowAgentForwarding yes
AllowTcpForwarding no
#GatewayPorts no
#X11Forwarding no
#X11DisplayOffset 10
#X11UseLocalhost yes
#PermitTTY yes
#PrintMotd yes
#PrintLastLog yes
#TCPKeepAlive yes
#UseLogin no
#UsePrivilegeSeparation sandbox
#PermitUserEnvironment no
#Compression delayed
#ClientAliveInterval 0
#ClientAliveCountMax 3
#UseDNS no
#PidFile /var/run/sshd.pid
#MaxStartups 10:30:100
#PermitTunnel no
ChrootDirectory none
#VersionAddendum none

# no default banner path
#Banner none

# override default of no subsystems
#Subsystem	sftp	/usr/libexec/sftp-server
Subsystem       sftp    internal-sftp -f DAEMON -u 000

# Example of overriding settings on a per-user basis
#Match User anoncvs
#	X11Forwarding no
#	AllowTcpForwarding no
#	PermitTTY no
#	ForceCommand cvs server
Match User root
	AllowTcpForwarding yes
Match User admin
	AllowTcpForwarding yes
Match User anonymous
	AllowTcpForwarding no
	GatewayPorts no

/etc/passwd :
![synology-passwd](https://user-images.githubusercontent.com/17740746/92451322-db15b500-f1bc-11ea-89c1-5fe06cae49a7.png)

**Comment by sebsn86** [comment]
@zeripath Do you have any idea ? What have I missed ?

**Comment by sebsn86** [comment]
okay... weird !
I just restart the synology and all works perfectly !!

Thanks a lot @zeripath to helped me !
