### ISSUE TITLE
[FR] Sort branches by latest modified + user avatar

### ISSUE THREAD

**Issue by made2140** [go-gitea/gitea#12763]
## Description

Currently in Bitbucket it is possible to see branches sorted by latest modified date (top -> bottom).
Of course, BB has it by default, though I would propose to have a sort option to enable sorting in various modes.

In addition, would be quite cool to have last commit's user avatar available to each branch.
This would give easier view of who was last working with specific branch, without clicking into each branch separately

## Screenshots

- Bitbucket
![image](https://user-images.githubusercontent.com/32461144/92473553-73269500-f1e3-11ea-8ae0-58af5a7c76f2.png)

- Gitea
![image](https://user-images.githubusercontent.com/32461144/92473234-19be6600-f1e3-11ea-8e76-eb566c51165c.png)

**Comment by lunny** [comment]
depends on #22743

**Comment by lunny** [comment]
#22743 have implemented sort by last modified desc, more sort options could be another PRs.

**Comment by lunny** [comment]
I think this has been resolved by #22743
