### ISSUE TITLE
Question: Why is adding a Member to Team set the watch to every Repo?

### ISSUE THREAD

**Issue by MarcelHillmann** [go-gitea/gitea#12767]
Hi,

I have a local instanze of gitea (1.14.1 and 1.15.x).
If I'm adding a Member to a Team, the member has "active" the Watch the repo without hint or any chance to disable this behavior.

I could reproduce this behavior with the WebGUI and with the REST call.

Woud it be possible, to add a parameter to enable this feature?

Thx
Marcel

**Comment by techknowlogick** [comment]
This is already complete. The option is `AUTO_WATCH_NEW_REPOS`. More info here: https://docs.gitea.io/en-us/config-cheat-sheet/#service-service
