### ISSUE TITLE
Image thumbnails will leave in the issue comment after edit existed issue comment

### ISSUE THREAD

**Issue by BLumia** [go-gitea/gitea#12764]
- Gitea version (or commit ref): 1.12.4, can also be reproduce on try.gitea.io with 1.13.0+dev-573-g489c8a147
- Git version: 2.20.1
- Operating system: Linux for my self-hosted instance.
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (example URL: https://try.gitea.io/ffffff/ffffff/issues/1 , please notice that reproduce steps is **required** since the bug cannot be seen once you refresh the page)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

In the issue board, if I paste some images in the issue thread (whatever in the description or in the comments), once I submit the issue or comment, after re-edit the issue or comment which contains images, there will have some image thumbnails leaves in the bottom of the comment block, which can be seen in the screenshot:

![image](https://user-images.githubusercontent.com/10095765/92486526-cbc75380-f21e-11ea-87bd-1000709adaac.png)

And once we refresh the page, these thumbnails will be gone and looks normal again.

### To reproduce:

1. Create a new issue in any repo, with one or more images in the issue content.
2. Submit the issue.
3. Go to the page of the issue which you just created, click Edit.
   ![image](https://user-images.githubusercontent.com/10095765/92486972-42fce780-f21f-11ea-9939-a9ac58ec8f57.png)
4. Do any change and keep the image as-is. You can even paste some new images in the content, but just don't remove the original images in the content.
5. Click "Save"
6. See the result.
   ![image](https://user-images.githubusercontent.com/10095765/92487582-ffef4400-f21f-11ea-93b9-bb20cf420b33.png)

## Screenshots

See above. Let me know if you need any additional info.

**Comment by lunny** [comment]
Is this still a problem? @BLumia

**Comment by BLumia** [comment]
Seems no longer valid in 1.14.0, closing then, thanks!
