### ISSUE TITLE
gitlab migration: fals token error is not reported

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#12779]
gitea v:  1.13.0+dev-583-g090024db3

`Migrate repository from https://gitlab.com/gitea/test_repo failed: error: GitlabDownloader is nil`

**Comment by jolheiser** [comment]
Doing a little testing on try, it seems to work with a token. But migrating fails if using GitLab without a token.

**Comment by jolheiser** [comment]
I think what needs to happen here is that if no auth is passed, we should use the plain git downloader because the GitLab client expects to log into GL.

**Comment by 6543** [comment]
@jolheiser the first api call retuned this: `{message: 401 Unauthorized}` - if token is wrong/outdated -> 
currently it only will thell Downloader == nil but not the reason

**Comment by jolheiser** [comment]
Gotcha. Alright, so then it needs a small refactor as well.

**Comment by 6543** [comment]
also notized we need a collor-code noramlizer: ( gitlab allow code #fde -> #ffddee )
