### ISSUE TITLE
"Only Email on Mention" settings is broken

### ISSUE THREAD

**Issue by ashimokawa** [go-gitea/gitea#12774]
- Gitea version (or commit ref): 1.12.4
- Git version: 2.20.1
- Operating system: Debian 10
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

When going to your account settings and choosing the “Only Email on Mention” settings, the will be no Emails sent at all, even if mentioned

We tried this on try.gitea.io and had the same problem. EMails are send out if you choose the standard setting to get notified always. And in that case the Emails also says that you have been mentioned.

https://codeberg.org/Codeberg/Community/issues/257

**Comment by lunny** [comment]
We need a new mock mail sender for tests.

**Comment by a1012112796** [comment]
ref #7813

**Comment by StrangeZak** [comment]
Hi guys, I'm getting this exact issue in 1.13 RC1 as well. I think this patch would be in 1.13, but maybe I'm missing something, or maybe this is a new bug.

Thanks in advance,
