### ISSUE TITLE
I created a plugin for drone or any docker based pipeline that comments in the Gitea PR

### ISSUE THREAD

**Issue by DefinitelyADev** [go-gitea/gitea#12770]
Hello! I don't know is this is the right place to post this, if it isn't you're more than welcome to close the issue but I would like if you could point me to a correct location. Thanks in advance.

This is the repo: [Gitea Comment](https://github.com/TsakiDev/gitea-comment)
Any issues, requests or PRs are more than welcome!

The requirement for this plugin arose when I needed to post the contents of a file, in the PR it originated, during the build process.

**Comment by jolheiser** [comment]
Perhaps you could make a PR to [awesome-gitea](https://gitea.com/gitea/awesome-gitea)?  

That sounds pretty useful, though! 🚀

**Comment by techknowlogick** [comment]
You may also want to create a PR on the following repo https://github.com/drone/drone-plugin-index so it gets listed on the drone plugins website.
