### ISSUE TITLE
Open Graph dont show Org Avatars

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#12778]
gitea: v1.12.4

wrong metadata is returnd for org pages

**Comment by aschrijver** [comment]
Hi @zeripath just a FYI: In codeberg I [reopened the issue](https://codeberg.org/Codeberg/Community/issues/256#issuecomment-158215) that led @6543 to create this one. The opengraph for organizations seems to give the opengraph of codeberg instead.
