### ISSUE TITLE
Avoid page reloads on unchanged assignee/labels

### ISSUE THREAD

**Issue by silverwind** [go-gitea/gitea#12783]
STR:

1. View any issue
2. Double click on "Assignees" or "Labels" in the sidebar, e.g. don't change anything
3. Page unnecessarily reloads

Should ideally also eliminate the page reloads when values actually change and just update DOM accordingly in JS.

**Comment by silverwind** [comment]
👍

**Comment by jolheiser** [comment]
This is mostly fixed by https://github.com/go-gitea/gitea/pull/23014 
It doesn't cover the "update the DOM" case, please re-open if you think it should be part of this issue or if we should have a specific issue for it now that this is partially fixed.

**Comment by wxiaoguang** [comment]
I also agree to "just update DOM accordingly in JS", but those dropdowns are much more complex than I thought, so I left them as they were. To touch them .... it needs another (big) refactoring PR.

**Comment by silverwind** [comment]
Should probably rewrite them to something non-imperative like Vue/React/... 😉
