### ISSUE TITLE
Missing advanced settings (PR and project)

### ISSUE THREAD

**Issue by LecrisUT** [go-gitea/gitea#12788]
- Gitea version (or commit ref): Gitea version 1.13.0+dev-353-g1de19e0c7 built with GNU Make 4.2.1, go1.13.4 : bindata
- Git version: 
- Operating system: Centos 8
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

In the advanced settings of a new or migrated repository the option to enable Pull requests and/or projects is missing.

## Screenshots
![Screen Shot 2020-09-10 at 11 26 27](https://user-images.githubusercontent.com/25577083/92674903-44322f80-f359-11ea-8b0b-874107955d4c.png)

**Comment by zeripath** [comment]
So empty repositories don't display the pull requests setting - this is a bug and I'll submit a PR for that now.

In terms of projects you will need to check your app.ini - you may have set:

```
DISABLED_REPO_UNITS = ...
DEFAULT_REPO_UNITS = ...
```

The provided app.example.ini is **NOT** meant to be copied across and used as your default app.ini. Do have settings in your app.ini that you do not understand.

**Comment by LecrisUT** [comment]
Those were the config I needed to know thanks. A bit unintuitive with how the example.app.ini is presented. I guess it should read as the default settings that are already set, and not as the default settings to be set.

**Comment by LecrisUT** [comment]
I've just double checked and with empty `DISABLED_REPO_UNITS = ` and the `DEFAULT_REPO_UNITS = ...,repo-projects` still the projects do not show up. I have also checked-out the linked PR and the same behaviour on both already made repos and new repos. Are there any specific logs I should provide?
