### ISSUE TITLE
How to/Request Lock Issues after configurable amount of time

### ISSUE THREAD

**Issue by iamdoubz** [go-gitea/gitea#12799]
- Gitea version (or commit ref): 1.12.4+6-g0ee823be0
- Git version: git version 2.28.0.windows.1
- Operating system: Windows Server 2012 R2
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist: N/A

## Description

Question: how do I set up either a webhook or "bot" that will automatically close issues, etc. after a specified amount of time? If it does not exist, could it be set up as 1) if issue is Closed specify lock reason 2) if not closed, different lock reason 3) if a title tag specified, ignore the lock criteria.

## Screenshots

N/A

**Comment by Masgalor** [comment]
There is a stalebot listed in [awsome-gitea](https://gitea.com/gitea/awesome-gitea).
Maybe this is what you are looking for.
