### ISSUE TITLE
Support transfer projects from gitlab

### ISSUE THREAD

**Issue by luffyke** [go-gitea/gitea#1280]
As title mentioned, we used gitlab before and wanna to use gitea now, but there are many projects in our gitlab, and I can't find any tool of gitea to transfer projects from gitlab, please tell me how to transfer quickly or do you plan to produce a tool to do it?

**Comment by hughesjs** [comment]
Doesn't the migrate function work?

**Comment by lunny** [comment]
If there are many repositories, you could write a tool via Gitea's API to do that. @luffyke

**Comment by luffyke** [comment]
where i can find the Gitea's API, @lunny

**Comment by lunny** [comment]
github.com/go-gitea/go-sdk
