### ISSUE TITLE
sqlite db  delete user error

### ISSUE THREAD

**Issue by zileyuan** [go-gitea/gitea#1281]
admin delete log:
2017/03/16 15:23:00 [...uters/admin/users.go:257 DeleteUser()] [E] DeleteUser: ExternalLoginUser: database table is locked

user delete self:
2017/03/16 15:25:15 [...ters/user/setting.go:707 SettingsDelete()] [E] DeleteUser: ExternalLoginUser: database table is locked

**Comment by crocket** [comment]
I couldn't delete a user because of this bug.

**Comment by strk** [comment]
Duplicate of #1145

**Comment by lunny** [comment]
go #1145 to discuss further.
