### ISSUE TITLE
Gitea 1.12.4 always restart  and see 502 Bad Gateway

### ISSUE THREAD

**Issue by fansat** [go-gitea/gitea#12812]
- Gitea version (or commit ref):
- Git version:1.12.4
- Operating system:linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

2020/09/11 02:15:02 ...m.io/xorm/core/db.go:154:QueryContext() [I] [SQL] SELECT * FROM `team` INNER JOIN `team_user` ON team_user.team_id = team.id INNER JOIN `team_repo` ON team_repo.team_id = team.id WHERE (team.org_id = ?) AND (team_user.uid=?) AND (team_repo.repo_id=?) [3 5 124] - 364.565964ms
2020/09/11 02:15:02 ...er/issues/indexer.go:228:func3() [F] Issue Indexer Initialization timed-out after: 30s
2020/09/11 02:16:21 ...dules/setting/log.go:279:newLogService() [I] Gitea Log Mode: File(File:info)
2020/09/11 02:16:21 ...les/setting/cache.go:70:newCacheService() [I] Cache Service Enabled
2020/09/11 02:16:21 ...les/setting/cache.go:81:newCacheService() [I] Last Commit Cache Service Enabled
2020/09/11 02:16:21 ...s/setting/session.go:63:newSessionService() [I] Session Service Enabled
2020/09/11 02:16:21 routers/init.go:63:initDBEngine() [I] Beginning ORM engine initialization.
2020/09/11 02:16:21 routers/init.go:70:initDBEngine() [I] ORM engine initialization attempt #1/10...
2020/09/11 02:16:21 ...rm/session_schema.go:25:Ping() [I] PING DATABASE mysql

## Description
gitea often restart  and see 502 Bad Gateway. see in log: er/issues/indexer.go:228:func3() [F] Issue Indexer Initialization timed-out after: 30s

[indexer]
REPO_INDEXER_ENABLED = false

Add this config, it did not work also.

**Comment by lunny** [comment]
It is said `Issue Indexer Initialization timed-out after: 30s` but not repository indexer.

**Comment by zeripath** [comment]
Just to be clearer **ISSUE** indexer not repository.

It's likely that the data in data/indexers/issues.* is corrupt and you should just delete them.
