### ISSUE TITLE
Server Complains About Missing JS / CSS After Build and Cannot Serve Them

### ISSUE THREAD

**Issue by TheDiscordian** [go-gitea/gitea#12818]
- Gitea version (or commit ref): c18c6cf4cf31260746b527f83e4ca4b4703c3f29
- Git version: 2.20.1
- Operating system: Debian 10 (Buster)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL (not relevant, as it's not connected to a DB yet)
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

After installation the server can't find any JS or CSS.

I ran:

```
git clone https://github.com/go-gitea/gitea.git
cd gitea
TAGS="bindata" make build
make backend
make frontend
./gitea web
```

Log when viewing a page:

```
[Macaron] 2020-09-11 23:04:08: Started GET /js/index.js?v=1c6281b1bbc024e3659c0eae953d6c62 for [2607:f2c0:e28a:17:997:34a5:8339:763a]
[Macaron] 2020-09-11 23:04:08: Completed GET /js/index.js?v=1c6281b1bbc024e3659c0eae953d6c62 404 Not Found in 216.711µs
[Macaron] 2020-09-11 23:04:08: Started GET /css/index.css?v=1c6281b1bbc024e3659c0eae953d6c62 for [2607:f2c0:e28a:17:997:34a5:8339:763a]
[Macaron] 2020-09-11 23:04:08: Completed GET /css/index.css?v=1c6281b1bbc024e3659c0eae953d6c62 404 Not Found in 123.341µs
```

I followed the instructions [here](https://github.com/go-gitea/gitea/blob/master/README.md), not sure what I should be doing differently.

## Screenshots

![Page missing CSS and JS](https://i.imgur.com/asSY83I.png)

**Comment by jolheiser** [comment]
```
TAGS="bindata" make build
make backend
make frontend
```

`make build` runs `frontend` followed by `backend`

Essentially you made a fully working binary, then you made a binary without any assets, then you made the assets.

The `bindata` tags embeds the assets into the binary.
However, making only the backend requires the frontend to exist somehow, either by making the frontend or having the sources available.

If you have all of the source available and don't mind generating assets, simply use
```
TAGS="bindata" make build
```

**Comment by TheDiscordian** [comment]
I have attempted the following steps:

```
TAGS="bindata" make build
./gitea web
```

I still get:

```
[Macaron] 2020-09-11 23:19:32: Started GET /css/index.css?v=1c6281b1bbc024e3659c0eae953d6c62 for [2607:f2c0:e28a:17:997:34a5:8339:763a]
[Macaron] 2020-09-11 23:19:32: Completed GET /css/index.css?v=1c6281b1bbc024e3659c0eae953d6c62 404 Not Found in 182.951µs
[Macaron] 2020-09-11 23:19:32: Started GET /js/index.js?v=1c6281b1bbc024e3659c0eae953d6c62 for [2607:f2c0:e28a:17:997:34a5:8339:763a]
[Macaron] 2020-09-11 23:19:32: Completed GET /js/index.js?v=1c6281b1bbc024e3659c0eae953d6c62 404 Not Found in 199.941µs
```

Should I be performing some sort of cleanup? I'm trying to follow along, just can't seem to get it to work.

> The `bindata` tags embeds the assets into the binary.

Thank you for that info, I think that should be in the README. I had no idea what the different commands did, and had a loose understanding at best of what's going on.

**Comment by TheDiscordian** [comment]
In case it's relevant, this is all my output for my last build:

```
gitea@localhost:~/gitea$ TAGS="bindata" make build
rm -rf public/js public/css public/fonts public/img/webpack public/serviceworker.js
npx webpack --hide-modules --display-entrypoints=false
make: *** [Makefile:650: public/js/index.js] Killed
```

**Comment by zeripath** [comment]
I suspect you're now hitting the problem that make thinks nothing has changed. make clean should sort that.

**Comment by TheDiscordian** [comment]
>I suspect you're now hitting the problem that make thinks nothing has changed. make clean should sort that.

Correct, thank you. However, I still cannot seem to follow the guide:

```
gitea@localhost:~/gitea$ make clean
go clean -i ./...
rm -rf gitea dist modules/public/bindata.go modules/options/bindata.go modules/templates/bindata.go modules/public/bindata.go.hash modules/options/bindata.go.hash modules/templates/bindata.go.hash \
        integrations*.test \
        integrations/gitea-integration-pgsql/ integrations/gitea-integration-mysql/ integrations/gitea-integration-mysql8/ integrations/gitea-integration-sqlite/ \
        integrations/gitea-integration-mssql/ integrations/indexers-mysql/ integrations/indexers-mysql8/ integrations/indexers-pgsql integrations/indexers-sqlite \
        integrations/indexers-mssql integrations/mysql.ini integrations/mysql8.ini integrations/pgsql.ini integrations/mssql.ini
gitea@localhost:~/gitea$ TAGS="bindata" make build
rm -rf public/js public/css public/fonts public/img/webpack public/serviceworker.js
npx webpack --hide-modules --display-entrypoints=false
make: *** [Makefile:650: public/js/index.js] Killed
gitea@localhost:~/gitea$ ./gitea web
bash: ./gitea: No such file or directory
```

Wondering if the binary went into a lower directory I ran `ls * | grep gitea`, but that only yields:
```
gitea-repositories-meta
code.gitea.io
gitea.com
```

Am I straying from the norm? It feels weird being the only one with issues following the README hehe.

**Comment by techknowlogick** [comment]
The hint is in your terminal `make: *** [Makefile:650: public/js/index.js] Killed` the process that builds the JS & CSS was killed

**Comment by TheDiscordian** [comment]
> The hint is in your terminal `make: *** [Makefile:650: public/js/index.js] Killed` the process that builds the JS & CSS was killed

Okay, I figured I'd get a louder complain on build error. Where would I investigate why that was killed?

**Comment by techknowlogick** [comment]
Could be many reasons, OOM killed, accidental ctrl-c, or something else. I recommend moving this discussion over to discord or the forums as several hundred people get emails when a message is added to the thread. Here are links to places you can continue: https://docs.gitea.io/en-us/seek-help/
