### ISSUE TITLE
Error 500 when try to view changes of a commit

### ISSUE THREAD

**Issue by finn-liebner** [go-gitea/gitea#12823]
- Hardware: BeagleBone Black
- Gitea version: 1.12.4 (arm6)
- Git version: 2.28.0-1
- Operating system: ArchLinux ARM (armv7l)
- Database:
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

If you try to view the changes of a commit (e.g. click on `0de1dbe954`), you will get `Error 500`. The problem affects only one repository, and several, but not all commits. `git clone` followed by `git log` provide correct results.

## Screenshots

![Gitea-01](https://user-images.githubusercontent.com/60413421/93000721-78a91580-f52a-11ea-96f4-0def850bfadc.png)
![Gitea-02](https://user-images.githubusercontent.com/60413421/93000724-7941ac00-f52a-11ea-8479-47af69806121.png)

**Comment by zeripath** [comment]
This is a duplicate #12816 which is already fixed in master and origin/release/v1.12

**Comment by zeripath** [comment]
Fixed by #12771 and its backport #12776
