### ISSUE TITLE
MYSQL: Database error on installation 

### ISSUE THREAD

**Issue by pree** [go-gitea/gitea#1283]
- Gitea version (or commit ref): 447c9b428f4cf50174ef7f3fbea56b5405f6bbf8
- Git version: 2.1.4
- Operating system: Debian
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist: https://gist.github.com/Schizopriest/d6ccdad0170812dfb5bc510f8c283d76

## Description

Getting the following Database Error when installing on a empty Database.
`Database setting is not correct: Error 1170: BLOB/TEXT column 'key_id' used in key specification without a key length`

MySQL-Server Version: `10.0.30-MariaDB-0+deb8u1`

## Screenshots
![image](https://cloud.githubusercontent.com/assets/9799276/23990790/65827e74-0a37-11e7-9733-adf97f278b9f.png)

**Comment by lunny** [comment]
We haven't tested on Mariadb although it should be the same as MySQL.

**Comment by cez81** [comment]
Just tested this on a fresh install of prebuilt 1.1.0 with 10.0.29-MariaDB-0ubuntu0.16.04.1 on Ubuntu 16.04. InnoDB as engine.
It installs without any errors for me. Been using MariaDB on my production setup without any problems.

Edit:: But 1.1.0+38-gf1d2f16 fails...

**Comment by Diablofan** [comment]
I can confirm this happening with MariaDB as well. Tried using the docker image 81f5b797cd07 (latest as of March 16 at 5:41 PM EST), and I was getting this error when trying a fresh install of gitea. Trying with the image tagged 1.1.0 works just fine.

**Comment by lunny** [comment]
Oh, maybe it's effected by GPG PR. Let me check.

**Comment by lunny** [comment]
This is the bug here. A `text` column should not be a `index`. https://github.com/go-gitea/gitea/blob/master/models/gpg_key.go#L23 @sapk what's the max length of a `key_id`?

**Comment by sapk** [comment]
From https://tools.ietf.org/html/rfc4880#section-12.2 "The Key ID is the
   low-order 64 bits of the fingerprint." So in hex 64/4 = 16 char

**Comment by sapk** [comment]
and in fact it's not even usefull to be a index since. I don't use the keyid to find key.

**Comment by gzsombor** [comment]
Changing from "INDEX TEXT NOT NULL" to "TEXT NOT NULL" solves the problem - at least for me.

**Comment by lunny** [comment]
@sapk so maybe we change the tag from `INDEX TEXT NOT NULL` to `CHAR(16) NOT NULL` to resolve this?

**Comment by sapk** [comment]
it should but I can't test right now.

**Comment by lunny** [comment]
I will send a PR to fix this.

**Comment by sapk** [comment]
In fact we could even use a uint64 ?

**Comment by sapk** [comment]
I have found maybe a optimization for validating more "quickly" since keyid is in signature but not I will have to test it a lot. So repassing #1150 in WIP

**Comment by sapk** [comment]
I use string because I use it as a string but the value is a uint64 even for primaryId. @lunny you can PR the change proposed CHAR(16) NOT NULL I will test it more of we can optimize DB for validation in #1150

**Comment by lunny** [comment]
OK

**Comment by sapk** [comment]
To be more simple it will stay in string format for DB since it will limit format at display but I will use https://github.com/golang/crypto/blob/master/openpgp/packet/public_key.go#L705 the same func to transform uint64 of the keyid store in sign to search only for the good key and not pass over each key of user.
