### ISSUE TITLE
Migration: add Cancel button

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#12845]
currently you you have to go to `<gitea-url>/<owner>/<migrating-repo>/settings` and use the "Delete Repo" button, to cancel migration

A cancel Button would be nice

**Comment by 6543** [comment]
-> #12904

**Comment by 6543** [comment]
pull 12917 moved to v1.15 ...

**Comment by Corship** [comment]
I tried mirroring a repo, and it failed.

If I visit <gitea-url>/<owner>/<migrating-repo>/settings I get the http 500 page
The repo is still in my list of repos, and if I click it the repo being mirrored animation is still shown.
