### ISSUE TITLE
/explore/code rendering slowly when there are many repositories (> 2000) and a logged in user

### ISSUE THREAD

**Issue by jnlin** [go-gitea/gitea#12849]
- Gitea version (or commit ref): 6a1a6332de5b5000d31ec26efaef6f78a4ee10f0
- Git version: 2.11.0
- Operating system: Docker
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist: N/A

## Description

We have a lot of repositories (>2000), and the rendering of `/explore/code` is slow (see the attached screenshot, > 17 seconds) with a logged in user.

We tried to remove some permission checking feature and the speed becomes good, however we are not sure which is the slowest part. The removed code is: https://github.com/go-gitea/gitea/compare/master...jnlin:jnlin_test

The possible parts under suspicion are:
https://github.com/go-gitea/gitea/blob/master/routers/home.go#L330
https://github.com/go-gitea/gitea/blob/master/routers/home.go#L338-L343

## Screenshots
<img width="1243" alt="截圖 2020-09-15 上午10 13 02" src="https://user-images.githubusercontent.com/284245/93163982-0d8a5980-f74b-11ea-90f0-0093294304fe.png">

**Comment by lunny** [comment]
The differences are `GetRepositoriesMapByIDs` and `ctx.Data["RepoMaps"] = rightRepoMap`.

**Comment by jnlin** [comment]
> https://github.com/go-gitea/gitea/blob/master/routers/home.go#L330
This spends < 0.5 secs

> https://github.com/go-gitea/gitea/blob/master/routers/home.go#L338-L343
This spends 17 secs, there may be some N+1 queries in `CheckUnitUser()`

**Comment by a1012112796** [comment]
> > https://github.com/go-gitea/gitea/blob/master/routers/home.go#L330
> 
> This spends < 0.5 secs
> 
> > https://github.com/go-gitea/gitea/blob/master/routers/home.go#L338-L343
> 
> This spends 17 secs, there may be some N+1 queries in `CheckUnitUser()`

How about #12854 ?

**Comment by jnlin** [comment]
> 
> How about #12854 ?
Still needs 15 secs

![image](https://user-images.githubusercontent.com/284245/93222884-06426a80-f7a2-11ea-8e85-4b622ae74ca3.png)

**Comment by lunny** [comment]
We need more PRs here, but let's merge this one at first.

**Comment by a1012112796** [comment]
Now the main issue is how to quickly find out all repos that the user has code read permission?

**Comment by jnlin** [comment]
@a1012112796 yes

**Comment by lafriks** [comment]
Up
