### ISSUE TITLE
Activity page-  broken urls - in 1.1.0

### ISSUE THREAD

**Issue by yusefmaali** [go-gitea/gitea#1286]
- Gitea version (or commit ref):  1.1.0 built with: bindata, sqlite (as seen in admin panel)
- Git version: 2.7.4
- Operating system: Ubuntu
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description

In the activity page all the links provided are broken.

in my installation (italian language) I have:

> yma "ha creato il repository yma/BugHunting"

in try.gitea.io I have:

> yma ha creato il repository yma/BugHunting

(please note the quotation marks).

The problem goes deeper in the urls. 
In my installation I have (I've replace my real hostname with a placeholder):

http://host_name/%5C%22/yma/BugHunting%5C%22

in try.gitea.io I have:

https://try.gitea.io/yma/BugHunting

This issue wasn't present in the previous version (1.0.2) and is affecting every kind of urls: issue, commits, repo creatiions, etc...

**Comment by yusefmaali** [comment]
Looking into Gitea code seems to me the issue happens here in this template:

https://github.com/go-gitea/gitea/blob/master/templates/user/dashboard/feeds.tmpl

The example I provide happens when GetOpType == 6

**Comment by yusefmaali** [comment]
Ok, found the issue (or a part of it).

https://github.com/go-gitea/gitea/blob/7d8f9d1c46e38681f2a4033a7da811ab7562d953/options/locale/locale_it-IT.ini

The it-IT localization is incorrect:
in "action" section you can see that the "create_issue" statement starts with a double quotation mark. This may be escaped into HTML %5C%22.
That quotation mark is surely wrong and it is present also in other statements.

**Comment by tboerger** [comment]
Damn crowdin -.-

**Comment by yusefmaali** [comment]
Ok, the it_IT localization has been corrected in master.
As soon as you release the new version, the issue will be resolved.

BTW the current v1.1.0 has this issue.

**Comment by lunny** [comment]
Master and release/v1.1 has fixed this problem and will be released on v1.1.1

**Comment by IzzySoft** [comment]
Funny thing is that I have a similar issue in my activities list: all links to repos and branches have that `%5C%22/user/repo%5C%22` even if there are no quotation marks in the names. Not Italian here (German was used when setting things up and logging in), but it's fixed when switching the browser language to English (and removing the `lang` cookie).

Running 1.1.0/ARM here currently. Is that the same issue (and thus fixed), or shall I open a separate issue for that?

**Comment by lunny** [comment]
This is a duplicated issue and fixed in release/v1.1

**Comment by IzzySoft** [comment]
@lunny thanks! Thought so already but just wanted to make sure.

**Comment by yusefmaali** [comment]
Fixed with the 1.1.1 release.
Thanks
