### ISSUE TITLE
Cannot create pull request from Forked repo

### ISSUE THREAD

**Issue by iamdoubz** [go-gitea/gitea#12871]
- Gitea version (or commit ref): 1.13.0+dev-642-gd8b5235de
- Git version: N/A
- Operating system: Windows 10
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description

Cannot create pull request on https://gitea.com but, I can create one try.gitea.io. There is lot's of javascript issues in my console.

## Screenshots

![2020-09-16_12-01-48](https://user-images.githubusercontent.com/4871781/93369335-db452e80-f814-11ea-8354-e138e3fedd9b.png)

**Comment by jolheiser** [comment]
You may have to clear your cache, this is probably a serviceworker issue

**Comment by iamdoubz** [comment]
Just throw grenades at me...
