### ISSUE TITLE
Implement `Draft Pull Request`

### ISSUE THREAD

**Issue by Kreyren** [go-gitea/gitea#12874]
Transfer from https://codeberg.org/Codeberg/Community/issues/260

## Description

Proposing to implement `Draft Pull Request` similar way as GitHub meaning:

Ability to submit **unmergable** pull request made to allow multiple people to work on one issue at the same time that doesn't trigger the Continuos Integration (CI).

The issue with this on GitHub is that these kinds of pull requests are spamming the maintainers so there should be a method to adapt the notifications in Gitea.

**Comment by Kreyren** [comment]
FWIW there is `WIP:` and `[WIP]:` prefix to the pull request title that is not sufficient as it doesn't prevent merges and spams the maintainers.

**Comment by techknowlogick** [comment]
Closing as WIP is our version of draft pull requests. It should prevent merges and if it doesn’t the. That is a bug and should be filed as much.

**Comment by Kreyren** [comment]
Assuming `won't fix`, but what about the notifications?
