### ISSUE TITLE
Fix the GitHub defined terms for requests

### ISSUE THREAD

**Issue by Kreyren** [go-gitea/gitea#12873]
## Description

GitHub is using the term `Pull Request` for merge requests which makes no sense assuming that it implies to send a request to pull from something.

Proposing to use the term `Merge Request`

**Comment by techknowlogick** [comment]
This request has been made in the past and to reiterate we would prefer not to as we have routes and whatnot that use “pulls” and it would be a breaking change to switch to merge.

**Comment by Kreyren** [comment]
Transferred in https://codeberg.org/Codeberg/Community/issues/273 then
