### ISSUE TITLE
Re-request review do not work

### ISSUE THREAD

**Issue by melmus** [go-gitea/gitea#12878]
- Gitea version (or commit ref):
1.13.0+dev-600-g4f8dad37f

- Git version host system:
2.17.1

- Git version in docker gitea_server_1:
2.26.2

- Operating system:
Ubuntu 18.04.3 LTS

- Database (use `[x]`):
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

When I created pull request, my colleagues saw this and review. After review, I need inserted new changes. I press the Re-Request Button, and nothing changes.

## Screenshots
![Снимок экрана 2020-09-17 в 11 48 35](https://user-images.githubusercontent.com/15018126/93448343-28d89e80-f8dc-11ea-8b8d-ee11e5655961.png)
![Снимок экрана 2020-09-17 в 11 48 56](https://user-images.githubusercontent.com/15018126/93448353-2d9d5280-f8dc-11ea-8888-971a9b747d0a.png)

**Comment by 6543** [comment]
fixed by #12039
