### ISSUE TITLE
Concerns about The Onion Router (Tor)

### ISSUE THREAD

**Issue by Kreyren** [go-gitea/gitea#12876]
As discussed on https://codeberg.org/Codeberg/Community/issues/50 there is a very unlikely scenario where Tor and/or clearweb could be used as a (D)DoS to a Gitea service.

See https://codeberg.org/Codeberg/Community/issues/50#issuecomment-80942 for explanation of the approach

### Suggestions
1. Implement a method that would allow submitting a proof-of-work on registration
2. Optimize the application to handle (D)DoS in general

**Comment by techknowlogick** [comment]
Closing as “handle DDOS attack” is very broad, and tbh if someone has several TB/s of bandwidth to attack someone with likely only a paid network provider could provide mitigation.

**Comment by Kreyren** [comment]
Disagree for reasons provided.

One thing is doing (D)DoS through pinging and the other is taking down application and it's components i.e blocking new users from creating a new account while the instance itself it working without issues.

The (D)DoS through pinging can be optimized on the end-user system, but the application should be adapted upstream.

**Comment by techknowlogick** [comment]
Regardless, as mentioned “handle (d)dos” is waaaaay to broad of a request. We have made optimizations already to combat issues codeberg is facing, as well they already have our plans to deal with their issues.

Please don’t open requests on behalf of Codeberg as you are duplicating communication efforts we have with them which takes away time from resolving issues they have.
