### ISSUE TITLE
Activity feed is unreadable when a long text is submitted

### ISSUE THREAD

**Issue by Kreyren** [go-gitea/gitea#12870]
Issue transferred from https://codeberg.org/Codeberg/Community/issues/270#issuecomment-80985

- Gitea version (or commit ref): Codeberg
- Git version: Codeberg
- Operating system: Unknown
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
  - [X] Unknown
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes (provide example URL)
    - Based on codeberg present in upstream as well
  - [ ] No
  - [ ] Not relevant
- Log gist: Not relevant

## Description

Should probably show only a summary of the content submitted or allow it to be expandable?

## Screenshots

![](https://codeberg.org/attachments/45efa62a-7f91-4da3-a858-7274299ef0ce)

**Comment by silverwind** [comment]
Yeah, these need to truncate to a single line. I think there is existing truncation code for in-issue references that does just that there.
