### ISSUE TITLE
Can not create repository

### ISSUE THREAD

**Issue by melmus** [go-gitea/gitea#12888]
- Gitea version (or commit ref):
1.13.0+dev-648-g5995326d5

- Git version host system:
2.17.1

-Git version in docker gitea:
2.26.2

- Operating system:
Ubuntu 18.04.3 LTS

- Database (use `[x]`):
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:

## Description

I can't create new repository in gitea. I see 500-error, after created repo.

**Comment by a1012112796** [comment]
Please check the error history in the log file. Thanks.

**Comment by melmus** [comment]
@a1012112796, I see mistake, I'm sorry
