### ISSUE TITLE
[Bug] Click `Reviewers` to add PR review do nothing

### ISSUE THREAD

**Issue by bagasme** [go-gitea/gitea#12887]
- Gitea version (or commit ref): 1.13.0+dev-647-g1fb5bbd09
- Git version: 2.27.0 (Debian Backports)
- Operating system: Debian 10
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:
https://paste.ubuntu.com/p/y5bjrSx4W2/

## Description
When I tried to add PR review by clicking `Reviewers` on the right sidebar, nothing happen. It should have opened the dropdown when I can click desired reviewer.

## Screenshots

![PR request review bug](https://user-images.githubusercontent.com/40219486/93563621-79bac680-f9b2-11ea-8759-bd72af425873.gif)

**Comment by mrsdizzie** [comment]
This is the behavior when there are no other possible reviewers. Are there other users who have write access to "test-pr-select-branch" here? For reviewers the requirement is that you have to have write access or be watching:

 https://github.com/go-gitea/gitea/blob/54ae4485881664715d615037f1ab48d50044b0a0/models/repo.go#L703-L710

**Comment by bagasme** [comment]
@mrsdizzie ack and thanks for your reply. so in my sistem i logged in as admin and watch the repo, then i can request review to that admin user.

btw, closing.
