### ISSUE TITLE
Display error reason, in case GIT repository being corrupted.

### ISSUE THREAD

**Issue by memdealer** [go-gitea/gitea#12880]
- Gitea version (or commit ref):     image: gitea/gitea:1.12.3
- Git version: 2.28.0
- Operating system: RosberyPi64
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X] No
  - [ ] Not relevant
- Log gist:

## Description

Hi People, 

I wonder if you can add a description on what's going on when a certain repository cannot be reached due to the fact that data is corrupted. This day I found out that one of my local repositories returning 500 whenever I try to see it in the web. The issue was unclear until I tried to push/pull from that repo. 

As revealed some objects were corrupted/empty inside of the container, but they're seems to be NOT empty and fine in the local copy. Still not sure why, perhaps due to the power outage/improperly powering off RosberyPi.

PS: I tried to git fisck --full/removing corrupted/empty objects - still no way to reach repository. 

## Screenshots
![image](https://user-images.githubusercontent.com/21087423/93468327-757da300-f8f7-11ea-8632-78ebff66736f.png)
![image](https://user-images.githubusercontent.com/21087423/93468464-af4ea980-f8f7-11ea-9031-911f262fc12b.png)
![image](https://user-images.githubusercontent.com/21087423/93468515-c5f50080-f8f7-11ea-8e75-2523b3a920c7.png)
![image](https://user-images.githubusercontent.com/21087423/93468892-5cc1bd00-f8f8-11ea-8ff1-71b82d783cbd.png)

**Comment by lunny** [comment]
If you run gitea in development mode, it will be displayed.
