### ISSUE TITLE
The editing window doesn't show everything in certain cases

### ISSUE THREAD

**Issue by DuckDuckWhale** [go-gitea/gitea#12896]
- Gitea version (or commit ref): 1.12.4 built with GNU Make 4.1, go1.14.8 : bindata, sqlite, sqlite_unlock_notify
- Git version: 2.25.1
- Operating system: Ubuntu 20.04
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes: <https://try.gitea.io/DuckDuckWhale/gitea-bug-reports/issues/1>
  - [ ] No
  - [ ] Not relevant
- Log gist: N/A

## Description

The editing window doesn't show everything in certain cases; a click is required before it shows.

Paste all of the following verbatim into the comment, refresh the page and click edit.

```
- There is an extra block at the end of comments after saving edits.
	- Filed at [Extra block at the end of comment after saving an edit #12895](https://github.com/go-gitea/gitea/issues/12895)
- The edits won't change any timestamps; you never know if the comment you saw really was only changed at the time of creation.  People can sneak in changes undetected.
	- Issue already exists at [Issue/comment edit history #12886](https://github.com/go-gitea/gitea/issues/12886)
- The editing window doesn't show everything in certain cases; a click is required before it shows
	- Testing

This test sample is specifically selected so it works; any subtle change may cause it to be unreproducible.

Stuff:
- The editing window doesn't show everything in certain cases; a click is required before it shows
	- The editing window doesn't show everything in certain cases; a click is required before it shows
    - The editing window doesn't show everything in certain cases; a click is required before it shows
	- The editing window doesn't show everything in certain cases; a click is required before it shows
    - The editing window doesn't show everything in certain cases; a click is required before it shows
- Lorem ipsum
	- dolor sit amet, consectetur adipiscing elit.
    - sed porttitor elit pharetra quis. Sed sed sem neque. Nunc in augue nec quam mattis porta
    - Vivamus vel luctus elit. Nulla tempus metus nunc, vitae suscipit est blandit auctor.

Donec laoreet ut justo vel lobortis.
- The stuff after this line goes missing.
- There is an extra block at the end of comments after saving edits.
	- Filed at [Extra block at the end of comment after saving an edit #12895](https://github.com/go-gitea/gitea/issues/12895)
- The edits won't change any timestamps; you never know if the comment you saw really was only changed at the time of creation.  People can sneak in changes undetected.
	- Issue already exists at [Issue/comment edit history #12886](https://github.com/go-gitea/gitea/issues/12886)
- The editing window doesn't show everything when it is too long; a click is required before it shows
	- Testing
```

## Screenshots

After clicking edit:
![bug](https://user-images.githubusercontent.com/28813824/93638110-94d60800-f9ab-11ea-9463-69b5f7fa134a.png)

After clicking:
![after clicking](https://user-images.githubusercontent.com/28813824/93638159-a9b29b80-f9ab-11ea-8e71-33f6c0942bfa.png)

**Comment by bagasme** [comment]
@DuckDuckWhale editing window on what page did you notice the issue? Issue form? PR?

**Comment by DuckDuckWhale** [comment]
When editing the first comment of an issue. I suspect that it could also happen when editing comments in other positions but I have not tested it.

**Comment by DuckDuckWhale** [comment]
Reproducted on <https://try.gitea.io/DuckDuckWhale/gitea-bug-reports/issues/1>.

**Comment by DuckDuckWhale** [comment]
Unable to reproduce since I switched to Firefox on Ubuntu with X11. Not sure if it is still relevant on Firefox on Windows 10. Might reopen if I am able to reproduce it again.
