### ISSUE TITLE
Mastodon OAuth2 Provider

### ISSUE THREAD

**Issue by OmmyZhang** [go-gitea/gitea#12897]
I hope gitea can configure custom OAuth2 Provider instead of only provide limited choices.
With custom `authorizeUrl`, `tokenUrl`, `profileURL`, `scopes` , `subjectClaim`( it's `sub` for oidc) and `usernameTemplate`, almost any OAuth2/OpenId can work. (That's how `synapse` porject does)

My problem is that I want to use Mastodon as  OAuth2 Provider but failed, but I think this feature can be widely useful.

**Comment by techknowlogick** [comment]
OAuth2 itself is implemented with many differences between providers, we use https://github.com/markbates/goth/tree/master/providers for connecting to various providers, and as you can see there are many listed there as they are all implemented differently. If you'd like Mastodon to be implemented please open an issue/PR upstream, and once supported we'd be happy to add support.

**Comment by techknowlogick** [comment]
Re-opening as Goth now supports Mastodon as an OAuth2 provider, which means with a PR we can support Mastodon as well

**Comment by techknowlogick** [comment]
Closed per linked PR
