### ISSUE TITLE
Wrong link generation of some URLs

### ISSUE THREAD

**Issue by andreynering** [go-gitea/gitea#1289]
- Gitea version (or commit ref): Current master: f1d2f16b544ef5ef66a45d0a8859d133c46979a4
- Git version: Not relevant
- Operating system: Not relevant
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant

## Description

Take as example these links:

```
https://foo.bar.com/post/2017/03/16

https://foo.bar.com/post/2017/03/16/index.html

https://foo.bar.com/post/2017.03.16
```

They're not Gitea/GitHub issues, but Gitea thinks it is. Screenshot:

![g1](https://cloud.githubusercontent.com/assets/7011819/24015157/5741ddbc-0a66-11e7-8245-eb8435813f4d.png)

try.gitea.io link: https://try.gitea.io/andreynering/issue-test/issues/1

**Comment by bkcsoft** [comment]
There's also the slight annoyance where just typing `#1337` becomes a broken link since it's not a valid issue/PR-number 😅

**Comment by andreynering** [comment]
FIxed by https://github.com/go-gitea/gitea/pull/2292
