### ISSUE TITLE
Extra block at the end of comment after saving an edit

### ISSUE THREAD

**Issue by DuckDuckWhale** [go-gitea/gitea#12895]
- Gitea version (or commit ref): 1.12.4 built with GNU Make 4.1, go1.14.8 : bindata, sqlite, sqlite_unlock_notify
- Git version: 2.25.1
- Operating system: Ubuntu 20.04
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes
  - [ ] No
  - [ ] Not relevant
  - [x] Have not tried
- Log gist: N/A

## Description

There is an extra block at the end of comments after saving edits, which disappears after an refresh. Reproducible on mobile.

## Screenshots

![图片](https://user-images.githubusercontent.com/28813824/93635540-53435e00-f9a7-11ea-9b0d-5a67107661f1.png)

**Comment by 6543** [comment]
fixed in master

**Comment by zeripath** [comment]
You mean #12404?

Feel free to backport
