### ISSUE TITLE
MacOS brew install gitea failed

### ISSUE THREAD

**Issue by dororojames** [go-gitea/gitea#12903]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

I flowed install script in the doc:
`brew tap go-gitea/gitea
brew install gitea`

and terminal(brew) return this error
Error: gitea: Calling 'devel' blocks in formulae is disabled! Use 'head' blocks or @-versioned formulae instead.
Please report this issue to the go-gitea/gitea tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/go-gitea/homebrew-gitea/gitea.rb:13

**Comment by zeripath** [comment]
Please open an issue at https://gitea.com/gitea/homebrew-gitea

**Comment by zeripath** [comment]
Actually as far as I can see we should have already fixed this with https://gitea.com/gitea/homebrew-gitea/pulls/109
