### ISSUE TITLE
Use a latest specification compliant TOML implementation package

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#12911]
https://github.com/toml-lang/toml/wiki#v100-rc1-compliant

**Comment by jolheiser** [comment]
As far as I know, we only use TOML for the linter config `.revive.toml`

Our config format is currently `ini`

**Comment by qlcom** [comment]
> we only use 

only use means you use. so it would be better if you use one that is latest spec compliant

**Comment by 6543** [comment]
@qlcom it's just not needed at the moment

**Comment by techknowlogick** [comment]
The linter we use (not gitea itself) uses toml, and the upstream libraries that have some toml support (which gitea doesn't leverage) use https://github.com/pelletier/go-toml which is spec compliant.
