### ISSUE TITLE
cannot clone large repo.

### ISSUE THREAD

**Issue by retX0** [go-gitea/gitea#12914]
- Gitea version (or commit ref): 1.13.0+dev-664-g2dbca92a0
- Operating system: DSM 6.2.3-25426 Update 2 with docker
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (https://try.gitea.io/test006/webkit)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

When I try to clone https://github.com/WebKit/webkit, I just direct add it form migrate, and it'll start clone, after a while, it'll be 404 when I try to open the url of the webkit on my own website. and there is no log with docker just have visit log. And I tried to edit the `app.ini` for section `[timeout]`, not working.

**Comment by lunny** [comment]
You can find some logs on `admin panel` about task log

**Comment by xnxin** [comment]
Got it, it says  `Migrate repository from https://github.com/WebKit/webkit failed: Clone: context deadline exceeded - fatal: early EOF`, and I search this error again with the exist issue, it's problem with `git.timeout` section, and I will extend this number to bigger and try again.

**Comment by xnxin** [comment]
OK, It has been done.
This is my custom section with `git.timeout`

```conf
[git.timeout]
DEFAULT = 720
MIGRATE = 30000
MIRROR = 72000
CLONE = 30000
PULL = 30000
GC = 60
```
