### ISSUE TITLE
If adding two images in the description when creating a new issue, only the first is clickable.

### ISSUE THREAD

**Issue by Floaf** [go-gitea/gitea#12925]
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes https://try.gitea.io/floaf/test/issues/2
  - [ ] No
  - [ ] Not relevant

If adding two images (by pasting them in the text field) in the description when creating a new issue, only the first is clickable.

![image](https://user-images.githubusercontent.com/27698216/93988765-67150880-fd89-11ea-848e-f40d35f3ca28.png)
![image](https://user-images.githubusercontent.com/27698216/93988870-84e26d80-fd89-11ea-8905-f309d223a234.png)
Only 1 is clickable, not 2.

**Comment by bagasme** [comment]
@Floaf on which previous version this issue doesn't occur?

**Comment by Floaf** [comment]
I have no idea, I just noticed it and assumed it was a bug since it makes not sense to only have the first image clickable.

**Comment by bagasme** [comment]
@Floaf can you test latest stable version (1.12.4)?

**Comment by Floaf** [comment]
@bagasme Not easily :-/

But i am running 1.12.1 (stable) in my environment and the same bug is there so maybe it never worked.

**Comment by bagasme** [comment]
@bagasme I can confirm the issue. On my case, the issue appeared on latest master (commit 3c360801b3547cba80766403c0ee2835cb81272d).

**Comment by bagasme** [comment]
@Floaf As workaround try to right-click second image and click `View image` (if you're on Firefox)

**Comment by Floaf** [comment]
@bagasme Yes, thanks. The links under the comment, "image.png", works too.
I just wanted to mention it if no one has noticed it.

**Comment by zeripath** [comment]
if you add a blank line between the two images the images are linked.

**Comment by bagasme** [comment]
@zeripath Your workaround also worked too

**Comment by fnetX** [comment]
I'd nevertheless say this is a bug, right? :sweat_smile: Still reproducible on https://try.gitea.io/fnetx/general/issues/1 (with html linebreak)

Came to this via https://codeberg.org/Codeberg/Community/issues/340
