### ISSUE TITLE
Migrate backup/restore from Gogs

### ISSUE THREAD

**Issue by bkcsoft** [go-gitea/gitea#1292]
https://github.com/gogits/gogs/commit/ca2cfaf71e33f42c00f5baf4792ba8396e6d0042

PR https://github.com/go-gitea/gitea/pull/1637

**Comment by bkcsoft** [comment]
@tboerger @lunny @andreynering @metalmatze Anything I've missed in the todo-list?

**Comment by pgaskin** [comment]
Add to features list: https://github.com/go-gitea/docs/blob/master/content/page/index.en-us.md

**Comment by lunny** [comment]
Add deprecation notice to `gogs dump` maybe you mean `gitea dump`?

**Comment by strk** [comment]
Doesn't this need to be reopened @lunny ?

**Comment by GitMensch** [comment]
@strk said
> Doesn't this need to be reopened @lunny ?

No, as this is now handled completely different and is tracked in the PR #2917, which currently has conflicting files.

**Comment by lunny** [comment]
We should support Gitea backup/restore, but for Gogs I will say it's difficult because we don't know how Gogs changed.
