### ISSUE TITLE
Corrupted repository (Exit status 128)

### ISSUE THREAD

**Issue by finn-liebner** [go-gitea/gitea#12935]
- Hardware: BeagleBone Black
- Gitea version: 1.12.4 (arm6)
- Git version: 2.28.0-1
- Operating system: ArchLinux ARM (armv7l)
- Database:
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log (System Notice):
```
Failed to health check repository (finn.liebner/Git): exit status 128 - error: object file ./objects/7d/6c3efa05084fe4eb8390e66166d3346b9a63e5 is empty
error: unable to mmap ./objects/7d/6c3efa05084fe4eb8390e66166d3346b9a63e5: No such file or directory
error: 7d6c3efa05084fe4eb8390e66166d3346b9a63e5: object corrupt or missing: ./objects/7d/6c3efa05084fe4eb8390e66166d3346b9a63e5
error: object file ./objects/95/5796081db2d6a36fc5ae7a25d381de7633a2b6 is empty
error: unable to mmap ./objects/95/5796081db2d6a36fc5ae7a25d381de7633a2b6: No such file or directory
error: 955796081db2d6a36fc5ae7a25d381de7633a2b6: object corrupt or missing: ./objects/95/5796081db2d6a36fc5ae7a25d381de7633a2b6
error: object file ./objects/d2/f6f8d0f3d67fff649b434fe1f48748f98fce3b is empty
error: unable to mmap ./objects/d2/f6f8d0f3d67fff649b434fe1f48748f98fce3b: No such file or directory
error: d2f6f8d0f3d67fff649b434fe1f48748f98fce3b: object corrupt or missing: ./objects/d2/f6f8d0f3d67fff649b434fe1f48748f98fce3b
error: object file ./objects/7d/6c3efa05084fe4eb8390e66166d3346b9a63e5 is empty
error: object file ./objects/7d/6c3efa05084fe4eb8390e66166d3346b9a63e5 is empty
fatal: loose object 7d6c3efa05084fe4eb8390e66166d3346b9a63e5 (stored in ./objects/7d/6c3efa05084fe4eb8390e66166d3346b9a63e5) is corrupt
```

## Description

After editing a file in the integrated text editor and then committing it, the entire repository was corrupted. When trying to open the link to the repository you get the HTTP error 500 and in the system notice you get the above mentioned error. This failure occured twice in my system.

**Comment by zeripath** [comment]
Ok that looks like an issue with the stability of your system. Gitea is simply using git underneath this and in fact when it edits code it does it a clean clone of the repo before pushing changes back up. 

There's one potential golang 1.14 issue to do with prempts that could be a cause - the nighties are compiled with 1.15.2 which you might try to see if it prevents the problem.

**Comment by finn-liebner** [comment]
If it is related to the stability of my system, how could I probably fix it (more powerful platform/board)?

And thanks for the hint with the Go version, I will try that.

**Comment by finn-liebner** [comment]
I tested it for some time now. And I was able to fix it by an update of the operating system, the error didn't occur again since then.
