### ISSUE TITLE
I can not push content via ssh, just return error message :"Permission denied, please try again."

### ISSUE THREAD

**Issue by be-engineer** [go-gitea/gitea#12930]
- Gitea version (or commit ref):
- Git version:1.11.4
- Operating system:Debian 10
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description
I use ssh to push content to gitea server,but I when I input password for gitea account, it responce "Permission denied", but my account is administraor.I don't know how to solve this problem.
My gitea installed on vmware on windows. It downloaded from https://www.turnkeylinux.org/gitea. 
...

## Screenshots
**The log of my operation in the console is as follows use windows wsl：**

**leon@lijiwei:/mnt/d/temp/1/SY-1UJKMB01B$ git branch -r**
  origin/HEAD -> origin/master
  origin/master
leon@lijiwei:/mnt/d/temp/1/SY-1UJKMB01B$ git branch
* master

**leon@lijiwei:/mnt/d/temp/1/SY-1UJKMB01B$ git remote -v**
origin  http://192.168.152.138/gitea/SY-1UJKMB01B.git (fetch)
origin  http://192.168.152.138/gitea/SY-1UJKMB01B.git (push)
leon@lijiwei:/mnt/d/temp/1/SY-1UJKMB01B$ git push -u origin master
fatal: unable to access 'http://192.168.152.138/gitea/SY-1UJKMB01B.git/': Failed to connect to 192.168.152.138 port 80: Connection refused

**leon@lijiwei:/mnt/d/temp/1/SY-1UJKMB01B$ ssh -v git@192.168.152.138**
OpenSSH_7.6p1 Ubuntu-4ubuntu0.4, OpenSSL 1.0.2n  7 Dec 2017
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: Connecting to 192.168.152.138 [192.168.152.138] port 22.
debug1: Connection established.
debug1: identity file /home/leon/.ssh/id_rsa type 0
debug1: key_load_public: No such file or directory
debug1: identity file /home/leon/.ssh/id_rsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/leon/.ssh/id_dsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/leon/.ssh/id_dsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/leon/.ssh/id_ecdsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/leon/.ssh/id_ecdsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/leon/.ssh/id_ed25519 type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/leon/.ssh/id_ed25519-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_7.6p1 Ubuntu-4ubuntu0.4
debug1: Remote protocol version 2.0, remote software version OpenSSH_7.9p1 Debian-10+deb10u2
debug1: match: OpenSSH_7.9p1 Debian-10+deb10u2 pat OpenSSH* compat 0x04000000
debug1: Authenticating to 192.168.152.138:22 as 'git'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: ecdsa-sha2-nistp256
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:************
debug1: Host '192.168.152.138' is known and matches the ECDSA host key.
debug1: Found key in /home/leon/.ssh/known_hosts:7
debug1: rekey after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey after 134217728 blocks
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519,ssh-rsa,rsa-sha2-256,rsa-sha2-512,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521>
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey,password
debug1: Next authentication method: publickey
debug1: Offering public key: RSA SHA256:********* /home/leon/.ssh/id_rsa
debug1: Authentications that can continue: publickey,password
debug1: Trying private key: /home/leon/.ssh/id_dsa
debug1: Trying private key: /home/leon/.ssh/id_ecdsa
debug1: Trying private key: /home/leon/.ssh/id_ed25519
debug1: Next authentication method: password
git@192.168.152.138's password:
debug1: Authentications that can continue: publickey,password
Permission denied, please try again.

**Comment by zeripath** [comment]
This does not appear to be a bug but rather a configuration issue.

Please use the forums or better the #configuration channel on discord (https://discord.gg/Gitea ) We also have an active #chinese channel.
