### ISSUE TITLE
LDAP regular Sync of User attributes

### ISSUE THREAD

**Issue by liszca** [go-gitea/gitea#12934]
- Gitea version (or commit ref):
- Git version: 1.12.4
- Operating system: Debian 10
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:

## Description
The user attribute synchronisation does not work as expected:
If I change my E-Mail address in LDAP, it will never change in Gitea, same for removed users. A test against deaktivated users by LDAP shows they cannot login (which is good), but in the Users account it will stay listed as "Activated".

Is it posible to trigger a periodical sync to have all "Mail" and LDAP-Account status synchronized?

...

## Screenshots
![image](https://user-images.githubusercontent.com/32976532/94158207-6ad88600-fe82-11ea-979b-641954499108.png)

**Comment by liszca** [comment]
Ok, shame on me I found a button, but how can I let cron do this Job:
![image](https://user-images.githubusercontent.com/32976532/94159798-44b3e580-fe84-11ea-94eb-1af5d7fcbb39.png)

**Comment by lafriks** [comment]
By default it would synchronize users every 24h if you have enabled it in authorization source:
![image](https://user-images.githubusercontent.com/165205/94165116-8cda0480-fe92-11ea-9e2d-020cd414d001.png)

https://github.com/go-gitea/gitea/blob/master/custom/conf/app.example.ini#L921

**Comment by liszca** [comment]
Thanks for the code in the app.ini, that was what i was looking for.
Is refresh every 30 Minutes "30m" ?

Is it possible to do the LDAP configuration in this file too?

**Comment by olexiyb** [comment]
@lafriks default is good, but it looks like the example from config does not work anymore. We need to sync from LDAP every several minutes to get the latest ssh keys, I remember it worked fine but does not in the latest release.

**Comment by olexiyb** [comment]
> Thanks for the code in the app.ini, that was what i was looking for.
> Is refresh every 30 Minutes "30m" ?
> 
> Is it possible to do the LDAP configuration in this file too?

https://docs.gitea.io/en-us/authentication/

**Comment by liszca** [comment]
https://github.com/go-gitea/gitea/blob/master/custom/conf/app.example.ini#L921

I configured it like the following but it didn't work as expected, my expectations where after Gitea restart it would do a sync befause of `RUN_AT_START = true`, but that didn't happen 90 minutes later nothing changed. 
```
[cron.sync_external_users]
RUN_AT_START = true
SCHEDULE = @every 24h
UPDATE_EXISTING = true
```

**Comment by liszca** [comment]
> @lafriks default is good, but it looks like the example from config does not work anymore. We need to sync from LDAP every several minutes to get the latest ssh keys, I remember it worked fine but does not in the latest release.

Which release was it, so I can switch if its not to old ...

**Comment by olexiyb** [comment]
> > @lafriks default is good, but it looks like the example from config does not work anymore. We need to sync from LDAP every several minutes to get the latest ssh keys, I remember it worked fine but does not in the latest release.
> 
> Which release was it, so I can switch if its not to old ...

The last release it was working fine was 1.10, but this one missing many features

**Comment by liszca** [comment]
> The last release it was working fine was 1.10, but this one missing many features

Is Migration missing?

**Comment by olexiyb** [comment]
> > The last release it was working fine was 1.10, but this one missing many features
> 
> Is Migration missing?

No

**Comment by liszca** [comment]
About 1.10.6 I can already say that `RUN_AT_START = true` is not working

**Comment by liszca** [comment]
Couldn't I hit the button via a curl script until you have a fix for the bug?

**Comment by liszca** [comment]
1.9.6 is working, changed Mail address is already changed after server is started.

**Comment by olexiyb** [comment]
I tried to debug and it looks like the bug is in

https://github.com/go-ini/ini/issues/240

This function

```
func GetCronSettings(name string, config interface{}) (interface{}, error) {
	cfg := Cfg.Section("cron." + name)
	log.Info("GetCronSettings name=%s cfg=%+v", name, cfg)
	err := cfg.MapTo(config)
	log.Info("GetCronSettings name=%s err=%+v config=%+v", name, err, config)
	return config, err
}
```
I can see data reading fine, but result of **MapTo** is wrong

**Comment by liszca** [comment]
How does it look if you debug 1.9.6?

**Comment by zeripath** [comment]
1.9.6 has completely different code so this would not be the same.

**Comment by olexiyb** [comment]
[cron.update_mirrors]
ENABLED = false
SCHEDULE = @every 2m

using 

```
type BaseConfig struct {
	Enabled         bool
	RunAtStart      bool
	Schedule        string
	NoSuccessNotice bool
}
```
is reading and mapping fine, but all other structs not working.

**Comment by zeripath** [comment]
yeah just testing this and it seems like the mapping to the extended structs isn't working.

**Comment by zeripath** [comment]
hmm...

That's annoying.

**Comment by zeripath** [comment]
Simplest fix is to just expand out the configs completely - (and of course fix go-ini to cope with the structs as another pr)

**Comment by zeripath** [comment]
We need an `ini:"extends"` option similar to `xorm` - that's gonna need a PR to ini

**Comment by zeripath** [comment]
https://github.com/go-ini/ini/pull/269

**Comment by zeripath** [comment]
I've put in a workaround in as #12939
