### ISSUE TITLE
Phone scrolling mistriggers label selection

### ISSUE THREAD

**Issue by DuckDuckWhale** [go-gitea/gitea#12945]
- Gitea version (or commit ref): ?
- Git version: ?
- Operating system: ?
- Database: ?
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes: <https://try.gitea.io/DuckDuckWhale/gitea-bug-reports/issues>
  - [ ] No
  - [ ] Not relevant
- Log gist: N/A

## Description

When scrolling on mobile and if starting the swipe down gesture on the issue filters or the other three, the menu pops up and the screen doesn't scroll as expected. Was expecting only a proper click can trigger the filter menu and the swipe to succeed.

**Comment by bagasme** [comment]
@DuckDuckWhale I can't reproduce the issue on current master (commit 95ff55991e20d1ebb1dcfeb1c1ff5ac0127211fc).

I'm testing on Firefox Desktop (with DevTools Responsive Design Mode and enable touch simulation).

**Comment by bagasme** [comment]
@DuckDuckWhale Which version did you notice this issue?

**Comment by DuckDuckWhale** [comment]
Can reproduce both from Gitea 1.12.4 and try.gitea.io. I'm using the new version of Firefox for Android.

**Comment by DuckDuckWhale** [comment]
Weird... I tried your setup (Firefox Desktop with DevTools Responsive Design Mode and enable touch simulation) and can reproduce the bug on 1.12.4 but not try.gitea.io. Still can reproduce both ways on mobile.

**Comment by bagasme** [comment]
@DuckDuckWhale Try clearing cache on Firefox mobile.

I think it's weird to see an UI bug occur on mobile when it doesn't appeared on DevTools.

**Comment by bagasme** [comment]
@DuckDuckWhale Whoops, sorry for inaccuracy. What I previously mean that the issue is on global `issues/` page, while you mean specific repo's page (`repo/issues`).

Anyway, I can reproduce the issue on DevTools by your means.

**Comment by DuckDuckWhale** [comment]
Interesting... Just rechecked the desktop dev tools, seems that I can't reproduce this on the link I provided but can on <https://try.gitea.io/josuealcalde/Gitea_Issue_Logout/issues>. Maybe it has something to do with having more than one issue? Can reproduce on both pages on real mobile.

**Comment by DuckDuckWhale** [comment]
Checked the personal /issues page and seems that starting the swipe action on the sort button activates it as well. Maybe there are some more instances scattered around the site.

**Comment by DuckDuckWhale** [comment]
Reproduced on version 1.13.0.

**Comment by DuckDuckWhale** [comment]
Reproduced on 1.14.3 on Android Firefox 89.1.1 but not from Dev Tools (weird).

**Comment by lunny** [comment]
I think this has been resolved.
