### ISSUE TITLE
Commit signature avatar stretched out

### ISSUE THREAD

**Issue by NULLx76** [go-gitea/gitea#12959]
- Gitea version 1.12.4
- Git version: N/A
- Operating system: Archlinux, Firefox 83.0a1
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes: https://try.gitea.io/0x76/test-repo
  - [ ] No
  - [ ] Not relevant

## Description
The profile image inside the commit signature message is stretched.

It seems if I change this width to `16px` using inspect element that the error is fixed. I haven't tried editing the less file and recompiling yet though.
https://github.com/go-gitea/gitea/blob/14e718695a999be199b61b57d60e9760d70ef439/web_src/less/_repository.less#L1484

## Screenshots
Image on my gitea instance (1.12.4)
![image](https://user-images.githubusercontent.com/1809198/94415077-63b0c100-017d-11eb-9cab-93eee4307208.png)

Image from try.gitea.io:
![image](https://user-images.githubusercontent.com/1809198/94415123-75926400-017d-11eb-85bb-d56b4a76b9fa.png)

---

If I apply this change  (`width: 16px`)
![image](https://user-images.githubusercontent.com/1809198/94415301-b1c5c480-017d-11eb-9f9e-a145713ed1fe.png)

the avatar seems to be correct again:
![image](https://user-images.githubusercontent.com/1809198/94415372-c0ac7700-017d-11eb-9ed9-81c95c8652c8.png)

**Comment by a1012112796** [comment]
@NULLx76 Hello, Would you please send a pull request to fix it? Thanks :)

**Comment by NULLx76** [comment]
@a1012112796 done :) #12961
