### ISSUE TITLE
The repository can be pushed successfully, but there is a 401 report in log

### ISSUE THREAD

**Issue by sanigo** [go-gitea/gitea#12951]
The repository can be pushed successfully, but there is a 401 report in log, like this:
```
[Macaron] 2020-09-27 10:19:16: Completed GET /gitadmin/demo-web1.git/info/refs?service=git-receive-pack 401 Unauthorized in 1.473705ms
```

- Gitea version (or commit ref):1.12.4
- Git version:2.12.2
- Operating system: Mac OS 10.15.6
- Database (use `[x]`): tested with postgresql and SQLite
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

**Comment by bagasme** [comment]
@sanigo Push via SSH or HTTPS?

**Comment by zeripath** [comment]
This is normal. Git always attempts things without authorization first.
