### ISSUE TITLE
Does not work search for repositories by description if the word contains an uppercase letter (russian language)

### ISSUE THREAD

**Issue by AKusov** [go-gitea/gitea#12958]
- Gitea version (or commit ref): 1.12.4
- Git version: 2.28.0
- Operating system: Windows Server 2019
- Database (use `[x]`): 
  - [x] SQLite
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
- Can you reproduce the bug at https://try.gitea.io: 
  - [x] Yes: https://try.gitea.io/explore/repos?tab=&sort=recentupdate&q=%D0%A2%D0%B5%D1%81%D1%82%D0%BE%D0%B2%D1%8B%D0%B9
  - [ ] No
  - [ ] Not relevant

## Description
Does not work search for repositories by description if the word contains an uppercase letter (russian language)
## Screenshots
![image](https://user-images.githubusercontent.com/4187588/94391791-f2b6dc80-016f-11eb-9944-75d5efc9ea6a.png)

![image](https://user-images.githubusercontent.com/4187588/94420552-c44ff600-019d-11eb-8255-06594cc2d027.png)

**Comment by zeripath** [comment]
Assuming that you haven't changed the default issue indexer, think this is not necessarily a bug. 

This is a limitation of SQLite:

https://www.sqlite.org/lang_expr.html#the_like_glob_regexp_and_match_operators

> The LIKE operator does a pattern matching comparison. The operand to the right of the LIKE operator contains the pattern and the left hand operand contains the string to match against the pattern. A percent symbol ("%") in the LIKE pattern matches any sequence of zero or more characters in the string. An underscore ("_") in the LIKE pattern matches any single character in the string. Any other character matches itself or its lower/upper case equivalent (i.e. case-insensitive matching). Important Note: SQLite only understands upper/lower case for ASCII characters by default. The LIKE operator is case sensitive by default for unicode characters that are beyond the ASCII range. For example, the expression 'a' LIKE 'A' is TRUE but 'æ' LIKE 'Æ' is FALSE. The ICU extension to SQLite includes an enhanced version of the LIKE operator that does case folding across all unicode characters.

This would be reason to use a different db or index the issues using bleve or elasticsearch.

We could/should check how easy it is to build Gitea with the ICU extension but I think it would equally be reasonable to say this is a limitation of SQLite and the db indexer backend.

**Comment by wxiaoguang** [comment]
Since it's database related, I think it's fine to close this issue.

Using a correct database or search engine should resolve the problem.
