### ISSUE TITLE
brew install failing on mac osx

### ISSUE THREAD

**Issue by bala-v** [go-gitea/gitea#12957]
- Gitea version (or commit ref):
- Git version:
- Operating system: mac osx
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X] No
  - [ ] Not relevant
- Log gist:

## Description
When trying to install gitea via brew, get the below error - 

Error: Invalid formula: /usr/local/Homebrew/Library/Taps/go-gitea/homebrew-gitea/tea.rb
tea: Calling 'devel' blocks in formulae is disabled! Use 'head' blocks or @-versioned formulae instead.
Please report this issue to the go-gitea/gitea tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/go-gitea/homebrew-gitea/tea.rb:13
...

**Comment by techknowlogick** [comment]
Thanks for this issue. You should use the tap from gitea.com found here: https://gitea.com/gitea/homebrew-gitea/ where the issue has been resolved.
