### ISSUE TITLE
Gitea sends webhooks to jenkins thought there are none of them

### ISSUE THREAD

**Issue by lakostin** [go-gitea/gitea#12965]
- Gitea version (or commit ref):
1.13.0+dev-683-gb725c4ee5
- Git version:
2.26.2
- Operating system:
Alpine Linux
- Database (use `[x]`):
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:

## Description
I use gitea plugin in jenkins. Webhook was enabled in the project to send events to jenkins. I removed webhook, however gitea still sends webhooks to jenkins.
...

**Comment by justusbunsi** [comment]
Have you checked the organization webhooks as well (if it's an org)? AFAIK the Jenkins plugin adds webhooks to both organization and repository if configured to "manage hooks" from inside Jenkins. This will happen on repository and organization scans. So it might be that your webhooks were re-enabled by Jenkins.
