### ISSUE TITLE
Running in Docker, want to generate self-signed SSL certificate INSIDE the container

### ISSUE THREAD

**Issue by loganmarchione** [go-gitea/gitea#12977]
- Gitea version (or commit ref): 1.12.4
- Git version: 2.24.3
- Operating system: Docker on AMD64 host
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

This might be an edge use-case.

I run Gitea in Docker, and use Nginx as a reverse proxy for HTTPS. However, the communication between Gitea and Nginx is over HTTP. I would like this communication to be HTTPS.

```
----------               ----------              ----------
|        |               |        |              |        |
| Users  | ----HTTPS---- | Nginx  | ----HTTP---- | Gitea  |
|        |               |        |              |        |
----------               ----------              ----------
```

Thinking out loud, my options are:
1. Mount an existing certificate from the host to the container (I tried using a Let's Encrypt certificate, but the `privkey.pem` is mode `600`, which the `git` user inside Gitea can't read)
2. Generate a self-signed SSL certificate INSIDE the container

For option 2, I know I can run `gitea cert --host git.example.com --ca` to generate a SSL certificate, but how does that work in Docker? That command would be for a traditional Gitea install on a regular OS.

Docker Compose allows you to overwrite the [default command](https://docs.docker.com/compose/compose-file/#command), but I don't want to overwrite the default command to start Gitea itself (`/app/gitea/gitea web`). Also, you're using s6, which would prevent this from working anyway.

Is there a way to generate a self-signed SSL certificate inside the container? I don't care if it re-generates at every startup, since no user will be visiting this location, they'll be hitting the Nginx reverse proxy.
## Screenshots
N/A

**Comment by 6543** [comment]
@loganmarchione I would manualy create it outside and add it to the data storage where all data live :)
set config to it, and that should it be

**Comment by johanvdw** [comment]
> 1. Mount an existing certificate from the host to the container (I tried using a Let's Encrypt certificate, but the `privkey.pem` is mode `600`, which the `git` user inside Gitea can't read)

chown 1000:1000 (or whatever useruid you use for git in your container). 1000 is the default if you follow https://docs.gitea.io/en-us/install-with-docker/

**Comment by loganmarchione** [comment]
@johanvdw  - Thanks, this is what I ended up doing.
