### ISSUE TITLE
Gitea webserver fails when using certificate chain

### ISSUE THREAD

**Issue by PE1NUT** [go-gitea/gitea#12972]
- Gitea version (or commit ref): 1.12.3
- Git version: 2.25.1
- Operating system: Ubuntu 20.04 LTS
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant

## Description

We are self-hosting gitea with a (not self signed) x509 certificate for https encryption.
The website works fine in a webbrowser, without needing to install a certificate or CA. The root of the CA tree is included in Linux /etc/ssl/certs/ca-certificates.crt.

However, when trying to run ‘git clone https://’ from anywhere, it fails with ‘fatal: unable to access : server certificate verification failed. CAfile: none CRLfile: none’

After some research, this is apparently due to the fact that we are only serving the certificate, not the chain including intermediaries. This is verified by testing with e.g. ‘https://whatsmychaincert.com’. However, if I replace the cert.pem in the gitea configuration with ‘chain.pem’, gitea fails to start webserver, with the message ‘tls: private key does not match public key’. I’ve verified (using 'diff') that the certificate itself, at the end of chain.pem, is exactly the same as the contents of ‘cert.pem’. I've also tried moving the certificate to the front of chain.pem, with the intermediaries behind, and the result is the same.
 
Gitea should properly serve the certificate chain, or at least the chain starting with the intermediate signers. It seems that this is needed for better browser support, and ‘git clone’ from the command line.

Note that in (closed) issue #4441 the recommendation is to have the configuration CERT_FILE point to the fullchain.pem, which is exactly what I've tried, but this results in the following error message:

...s/graceful/server.go:119:ListenAndServeTLS() [E] Failed to create certificate from cert file /var/lib/gitea/ssl/code-gitea-https-chain.pem and key file /var/lib/gitea/ssl/code-gitea-https-key.pem for tcp:0.0.0.0:443: tls: private key does not match public key

I've also verified that the file permissions and ownership on chain.pem and cert.pem are exactly the same.

**Comment by zeripath** [comment]
The certificate chain needs to have the final certificate - the one encoded with your private key - as the first certificate. 

Go's documentation states:

> // LoadX509KeyPair reads and parses a public/private key pair from a pair
> // of files. The files must contain PEM encoded data. The certificate file
> // may contain intermediate certificates following the leaf certificate to
> // form a certificate chain. On successful return, Certificate.Leaf will
> // be nil because the parsed form of the certificate is not retained.

**Comment by PE1NUT** [comment]
Thanks for the feedback. The certificate chain we got from the vendor was in reversed order. Although I suspected this to be the issue, I initially failed in reversing the ordering myself, so my earlier statement that it also doesn't work when moving the certificate to the front of the chain was wrong: I have now done so, and our gitea server is now happy to accept the chain. External programs other than webbrowsers are now also happy to connect to it.

I do suggest adding a bit of documentation to point out that cert.pem can be a chain, not just a cert, and that the ordering matters. I've created a small pull request. If this is considered self-evident when dealing with x509 certificates, feel free to reject it.

**Comment by zeripath** [comment]
Thanks for the docs PR - I think the ordering of certificate chain is a common problem. I definitely recall having a similar issue with nginx at some point.

To be honest it would be even nicer if go would just sort the provided chain, proved that it had a single leaf and that the provided key solves that leaf - it's pretty unfriendly to enforce that this stuff has to be in some, frankly opaque, order.

If it annoys me enough I'll take a look at seeing how difficult it is to do just that.

**Comment by techknowlogick** [comment]
Closed with linked PR. thanks for the submission :)
