### ISSUE TITLE
Hyperlinks in comments to source code in pull request are rendered grey, they are difficult to spot

### ISSUE THREAD

**Issue by shaoran** [go-gitea/gitea#12995]
- Gitea version: 1.12.2
- Git version:
- Operating system:
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes, https://try.gitea.io/shaoran/hyperlink-test/pulls/2 
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

The hyperlinks inside review comments in pull request get the `.text.grey` class and the hyperlink are hard to see.

If you go to the [Files Changed](https://try.gitea.io/shaoran/hyperlink-test/pulls/2/files) section of the pull request, you'll see that the style of the hyperlink is blue, so it is easy to read.

However, if you go to the [Conversation](https://try.gitea.io/shaoran/hyperlink-test/pulls/2) tab of the same pull request, it's hard to realize that this is a hyperlink because it's almost black and matches the color of the surrounding text. That happens because the `<a href="...">` tag is inside a `<span class="text grey">` tag as you can see here:

![](https://user-images.githubusercontent.com/113313/94786491-555ae300-03d1-11eb-982a-0ac9aba80971.png)

It seems to me that there is an error with the ending tag of the `<span class="text grey">` tag. Notice that there are also block elements (like `<div>`) inside the `<span>`, which are not allowed in an inline element like `<span>` anyway. See https://github.com/go-gitea/gitea/blob/master/templates/repo/issue/view_content/comments.tmpl#L488

## Screenshots

![hyperlink-test-side-by-side](https://user-images.githubusercontent.com/113313/94785624-327bff00-03d0-11eb-9992-6d37c70c2e1c.png)

**Comment by mrsdizzie** [comment]
Closed by linked pr
