### ISSUE TITLE
how to manage a 'code freeze' situation?

### ISSUE THREAD

**Issue by flobee** [go-gitea/gitea#13014]
Feature/ Usage request:

Hi there

I thought i could add a pre-recieve hook  to tell every one that the code is currently in 'code freeze' mode and exit the request so that pushes will not get into a master repository.

But: "pull request" from forks also breaking that way.

Have you an idea how to do things like this? Allow pulls and "pull requests" form forks but deny pushes until code freeze ends.

Kind regards
Florian

**Comment by a1012112796** [comment]
Do you means an option to not allow user to create pr to this branch? thanks

**Comment by flobee** [comment]
> Do you means an option to not allow user to create pr to this branch? thanks
no
- create a 'pull request' from a fork: Yes 
- push directly to a specific repository: No

**Comment by a1012112796** [comment]
Hmm, You can set this branch as protected, and disable push.Thanks!
![IMG_20201002_194341](https://user-images.githubusercontent.com/25342410/94919783-9cd39300-04e7-11eb-8241-3fa3aa2f17a8.jpg)

**Comment by flobee** [comment]
Yepp! Thats it! Thank you!
