### ISSUE TITLE
Git Difference Not Available

### ISSUE THREAD

**Issue by w-firm** [go-gitea/gitea#13012]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

DISCLAIMER: This issue has been rephrased by @kreyren hoping to make it more understandable as the issuer is not native english speaker

I have a website where i want to show a difference of two files which doesn't seem to be possible to do through Gitea API.

### Steps to reproduce
1. Create a new repository with any non-empty file
2. Change the file content and push it
3. Try to use GiteaAPI to return a usable call that would allow to show the difference of two files on a website

**Comment by w-firm** [comment]
also we have installed gitea in our server so is it affect when you migrate your stuff from github to gitea.com?

**Comment by Kreyren** [comment]
To clarify the end-user was asking on the discord server, but was unable to get the answer that they were looking for so he asked me if i can go on call with him to explain the issue and after the call i suggested filing an issue in case i am providing an inaccurate information and did my best to rephrase the original issue to make it more understandable.

It seems that GiteaAPI is unable to show file difference when the file changes.

I've suggested:
https://gitea.com/api/swagger#/repository/repoGetAllCommits
https://gitea.com/api/swagger#/repository/repoGetSingleCommit

which doesn't seem to resolve the issue for the end-user.

Hope it helps ^-^

**Comment by 6543** [comment]
Related:  #10921

I'll have a look at it :)

**Comment by yardenshoham** [comment]
Should this be closed as https://github.com/go-gitea/gitea/pull/17095 is merged?
