### ISSUE TITLE
Visual cue for Organization with Visibility Limited + Private

### ISSUE THREAD

**Issue by aschrijver** [go-gitea/gitea#13017]
- Gitea version (or commit ref): `master`

## Description

There is no visual indicator that an Organization has Visibility set to Limited or Private. Only when going to Settings this becomes apparent. There should be a visual cue (an icon or label) on the organization page and in the organization list on the dashboard.

### Background info

This caused confusion with me, and I reported an OpenGraph bug to [Codeberg](https://codeberg.org/Codeberg/Community/issues/256#issuecomment-95120) (No Discourse onebox when pasting links, and OpenGraph checker gave me 404 error). However, I forgot that upon creation I had set my org to be Limited visible, and afterwards never noticed this was still the case.

**Comment by smtaylorslc** [comment]
I'd be interested in trying this one. I'm admittedly not a UX expert -- do you think the best way to do this would be to put labels next to the Organization name in the places mentioned above (similar to the label display on this page)? Open to any ideas.

**Comment by techknowlogick** [comment]
@smtaylorslc yeah, similar to how it is on repos would be great!

**Comment by smtaylorslc** [comment]
@techknowlogick great! I've started on this and things are looking promising -- however, I don't think there's a shortened descriptor for "Visibility" in the locales (for instance, [the US locale file](https://github.com/go-gitea/gitea/blob/master/options/locale/locale_en-US.ini#L1871) sets `settings.visibility.limited` to `Limited (Visible to logged in users only)`). Should I add visibility shortnames to the English .ini file and have future translations for the short name be another ticket?

**Comment by zeripath** [comment]
yeah just add another item to the locale file. Crowdin will pick it up and translators will translate.

Speaking of which I should do a check up on crowdin...

**Comment by smtaylorslc** [comment]
Implemented in #13040 .

**Comment by aschrijver** [comment]
Super! You rock 👍
