### ISSUE TITLE
Comparison page is outdated for GitLab CE

### ISSUE THREAD

**Issue by claell** [go-gitea/gitea#13018]
Browsing the [comparison page](https://docs.gitea.io/en-us/comparison/), I found some outdated things for GitLab CE. Opening this issue according to the page. There might be more, but a short list:

- Related issues are supported now
- Service Desk is supported now
- Squash merging should be supported now

Let me know if you need references for those.

**Comment by techknowlogick** [comment]
Thanks for issue :) Would you be open to creating a PR to update docs? The source for that page can be found in: https://github.com/go-gitea/gitea/blob/master/docs/content/doc/features/comparison.en-us.md

**Comment by claell** [comment]
Done. I added references as well. Hopefully all provided information is correct.
