### ISSUE TITLE
User dashboard scrolls to bottom on refresh

### ISSUE THREAD

**Issue by pgaskin** [go-gitea/gitea#1301]
- Gitea version (or commit ref): 1.1.0
- Database (use `[x]`):
  - [X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes (provide example URL)

## Description

User dashboard scrolls to bottom on refresh

https://transfer.sh/Pi18Y/scrollbug.mp4

**Comment by uncled1023** [comment]
I am seeing the same thing.  Any updates on this issue?

**Comment by bkcsoft** [comment]
Likewise, on Firefox 53.0.3 - Linux

**Comment by 5im-0n** [comment]
adding `window.scrollTo(0, 0);` to every page solves the issue

**Comment by katanacrimson** [comment]
However, that's probably not the best fix - determining why we're scrolling to the bottom would be far better.

**Comment by daviian** [comment]
It is default behaviour for autofocus in certain browsers. That's not a bug in gitea.

**Comment by pgaskin** [comment]
@daviian what would it be autofocusing to? There are no form elements at the bottom.

**Comment by daviian** [comment]
@geek1011 Is it possible for you to reup your scrollbug video?

I can only reproduce the bug if I make the window so small that it has to scroll to the "Find repositories" input field.

**Comment by 5im-0n** [comment]
here is the jumping after login, and when going to my profile page:
https://fcku.it/files/1/file-1507050345650.mp4

**Comment by daviian** [comment]
Seems to be fixed with #1652

**Comment by lunny** [comment]
Please feel free to reopen it.
