### ISSUE TITLE
Feature request: SQRL login

### ISSUE THREAD

**Issue by nimo-labs** [go-gitea/gitea#13021]
Hi, this is my first Gitea feature request so apologies if it's in the wrong format or location, I did try googling a feature request procedure.

Would it be possible to add SQRL login as an option to Gitea?

https://www.grc.com/sqrl/sqrl.htm

**Comment by zeripath** [comment]
SQRL appears to be an OAuth2 provider - can't you just use the OAuth2 provider part of it?

**Comment by nimo-labs** [comment]
SQRL isn't an oath provider itself, it's supposed to be designed into the website.
There is an external service that provides a mapping between sqrl and oauth, but that's meant to be a last resort / intermediate service until it's adopted natively by websites and apps.

One issue with using oauth, is that doesn't work on networks, that aren't connected to the internet. A very remote corner case admittedly, but one could imagine a private zerotier network for example with no internet bridge.

Sadly I know less than nothing about programming in Go, however I have found this package which may help? https://godoc.org/github.com/elgris/sqrl

**Comment by 6543** [comment]
* https://github.com/sedalu/sqrl
* https://github.com/RaniSputnik/sqrl-go
