### ISSUE TITLE
Cannot remove a user from an organization, cannot leave an organization

### ISSUE THREAD

**Issue by argentini** [go-gitea/gitea#13034]
- Gitea version (or commit ref): 1.12.4, 1.12.5
- Git version: any
- Operating system: any
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [X ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X ] No (try.gitea.io does not provide admin access)
  - [ ] Not relevant
- Log gist:

## Description
When I try to remove a user from an org it spins forever and locks up the app, never completing. When I sign in as the user and try to leave the org the same thing happens. Sometimes it will timeout and yield a 502 error.
...

**Comment by zeripath** [comment]
Would it be possible to see some logs and a suitably sanitized copy of your app.ini please.
