### ISSUE TITLE
Clickable area on files table links seems to have shrinked

### ISSUE THREAD

**Issue by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [go-gitea/gitea#13038]
- Gitea version (or commit ref): [`Gitea Version: 1.13.0+dev-731-g5e1c51cdb`](https://github.com/go-gitea/gitea/commit/5e1c51cdb)
- Git version: `2.28.0.1022.gfdf196b997`
- Operating system: Arch Linux
- Database:
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes - [any repo](https://try.gitea.io/JonasFranzDEV/drone-gitea-release/src/branch/master/.github) (also ideally with at least *some* folder structure for the `..` case) will do

## Description
As discussed in discord with @jolheiser (etzelia/rooibos).

At the moment, try.gitea.io is running the same Gitea version as my instance, so I am also (as of now) able to "replicate" it there.

The #12553 was supposed to increase clickable link area, but, unfortunately, seems to have stopped working in the meanwhile.

When pointing the cursor even a little off a link's text, it's not possible to click the link anymore, so there's been a regression apparently since the subject PR.

One especially curious example is the `"go to a parent folder"` (see screenshot) case, where one is forced to point the cursor at a really small `..` area or the link is not active.

This is not in fact a new issue to me, I just recently got to asking about it, so chances are a possible regression was introduced - if memory serves - up to a month ago, so that is possibly fairly recently after the improvement has been introduced.

## Screenshots
![image](https://user-images.githubusercontent.com/61180606/95128549-e1666500-0759-11eb-85c9-cc87c7f1c778.png)

**Comment by silverwind** [comment]
https://github.com/go-gitea/gitea/pull/12617 is the latest iteration of this. It had to be reverted from the initial full-width area to just a vertical enlargement because I was not able to get the text ellipsis to work with a fully streched `<a>`, it's a very tricky issue.

Parent link seems like a bug, it should be at least as high as the other rows and can possibly be made full-width.
