### ISSUE TITLE
Support setting SCHEMA by environment variables in docker app.ini template

### ISSUE THREAD

**Issue by gioppoluca** [go-gitea/gitea#13033]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
I'm installing GITEA using docker.
I'm using postgresql with a dedicated schema "gitea" and not public.
There is not the SCHEMA option in the app.ini and so the application canno start creating the db:
```
git_1        | 2020/10/05 13:39:31 ...rm/session_schema.go:25:Ping() [I] PING DATABASE postgres
git_1        | 2020/10/05 13:39:31 ...m.io/xorm/core/db.go:154:QueryContext() [I] [SQL] SELECT tablename FROM pg_tables WHERE schemaname = $1 AND tablename = $2 [public version] - 3.855193ms
git_1        | 2020/10/05 13:39:31 ...m.io/xorm/core/db.go:277:ExecContext() [I] [SQL] CREATE TABLE IF NOT EXISTS "version" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "version" BIGINT NULL) [] - 552.738µs
git_1        | 2020/10/05 13:39:31 ...m.io/xorm/core/db.go:154:QueryContext() [I] [SQL] SELECT column_name FROM INFORMATION_SCHEMA.COLUMNS WHERE table_schema = $1 AND table_name = $2 AND column_name = $3 [public version id] - 10.913145ms
git_1        | 2020/10/05 13:39:31 ...m.io/xorm/core/db.go:277:ExecContext() [I] [SQL] ALTER TABLE "version" ADD "id" BIGSERIAL PRIMARY KEY  NOT NULL  [] - 2.661464ms
git_1        | 2020/10/05 13:39:31 routers/init.go:135:GlobalInit() [F] ORM engine initialization failed: migrate: sync: pq: column "id" of relation "version" already exists
```

If I add the schema to the ini file:

```ini
SCHEMA  = gitea
```

The installation of the DB proceed as expected

Please add to the template file the following:

```
SCHEMA = $SCHEMA
```

 so that it will be possible to add the env var through docker

**Comment by kasbah** [comment]
Hey, I [thought the same](https://github.com/go-gitea/gitea/pull/15215) but found out you can now set it in the docker images with a `GITEA__DATABASE__SCHEMA` env variable (at least if you build from master, not sure about release status). I think this issue can be closed.
