### ISSUE TITLE
Editing issue comments is hard in mobile

### ISSUE THREAD

**Issue by DuckDuckWhale** [go-gitea/gitea#13047]
- Gitea version (or commit ref): 1.12.5
- Git version: 2.25.1
- Operating system: Ubuntu 20.04
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
  - [x] Haven't tried
- Log gist: N/A

## Description

The edit comment button in issue comments along two others are half hidden and hard to press accurately when used on mobile, requiring multiple clicks and can be quite annoying.

Reproduced on desktop with Firefox dev tools in English and mobile in Chinese but not mobile in English. Clicks can sometimes blacken the three dots but not activate them, and a successful click need not blacken the three dots.

## Screenshots

![Screenshot_20201005_213715_org mozilla firefox](https://user-images.githubusercontent.com/28813824/95160150-a281e080-0754-11eb-98cb-6c3198af44ca.png)

**Comment by DuckDuckWhale** [comment]
Can't reproduce on 1.13.0 due to the vertical `Poster` tags in Chinese, but not sure if it is reproducible without the tags.

**Comment by septatrix** [comment]
In general I think the mobile view for comment should be overhauled. 20% of vertical space is wasted due to the user icon and there is a lot going on inside the comment header.

**Comment by yp05327** [comment]
![image](https://github.com/user-attachments/assets/dc0e0066-80ea-400b-87b1-fc5fff64b1d4)
I think this has been fixed.
