### ISSUE TITLE
[NOT BUG] csrf check faild in add new commet

### ISSUE THREAD

**Issue by a1012112796** [go-gitea/gitea#13051]
- Gitea version (or commit ref):  ``version 1.13.0+dev-735-gdf4bbcd23`` built with GNU Make 4.2.1, go1.14.9 : bindata, sqlite, sqlite_unlock_notify (Build with last commit: df4bbcd235cec8708cd0cbdd9bcbdd00f5db4fd5)
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
Get``Invalid csrf token.`` when add code comment. view:
![Peek 2020-10-06 14-59](https://user-images.githubusercontent.com/25342410/95169597-b88bb180-07e5-11eb-920d-8e8f7413a1f1.gif)

log:
```SHELL
[Macaron] 2020-10-06 14:59:24: Started POST /testg/test_repo/pulls/5/files/reviews/comments for 192.168.1.4
[Macaron] 2020-10-06 14:59:24: Completed POST /testg/test_repo/pulls/5/files/reviews/comments 400 Bad Request in 338.589µs
2020/10/06 14:59:24 ...s/context/context.go:332:func1() [D] Session ID: 87d1841579ba977c
2020/10/06 14:59:24 ...s/context/context.go:333:func1() [D] CSRF Token: bR_QLYCBp6bLpxZQHFc4FNzrJ4Y6MTYwMTk2NzU2NDc0ODM4NzM3NA
```
...

**Comment by 6543** [comment]
clean cache & login -> test again

**Comment by otbutz** [comment]
> clean cache & login -> test again

That's a workaround but not a solution.

**Comment by 6543** [comment]
If this fix it, there is already an issue about it ...

**Comment by 6543** [comment]
also interesting #11188

**Comment by a1012112796** [comment]
Sadly it's not usefull, And I found an amazing thing. The submit review is usefull which is using same csrf value...
![Peek 2020-10-06 16-52](https://user-images.githubusercontent.com/25342410/95180600-c7c62b80-07f4-11eb-81a8-971a931d1621.gif)

**Comment by a1012112796** [comment]
Sorry, It's my config fault.

**Comment by otbutz** [comment]
> Sorry, It's my config fault.

Could you explain?
