### ISSUE TITLE
Javascript error when load page

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#13057]
<img width="1322" alt="图片" src="https://user-images.githubusercontent.com/81045/95294258-8c386980-08a7-11eb-9043-0c0cd6de8879.png">

**Comment by silverwind** [comment]
Known Firefox bug. The font is loaded to support Chrome on Linux where there might not be a system emoji font but I think generally that is a weak argument to ship that 9MB font so we may as well just remove it.
