### ISSUE TITLE
401 when attempting to unfold hidden code in diffs

### ISSUE THREAD

**Issue by Ibmurai** [go-gitea/gitea#13053]
- Gitea version (or commit ref): 1.12.4 built with GNU Make 4.2.1, go1.14.8 : bindata, sqlite, sqlite_unlock_notify
- Git version: 2.24.3
- Operating system: Ubuntu 18.04.5 / Docker 19.03.12, build 48a66213fe
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

Whenever we click the code folding icon, i.e. `<svg class="svg octicon-fold" width="16" height="16" aria-hidden="true"><use xlink:href="#octicon-fold"></use></svg>`, a standard HTTP auth login modal dialog appears.

When we cancel that dialog, the log shows 401 errors on resources like these: `http://gitea.internal/org/repo/pulls/794/undefined?undefined&anchor=undefined`

## Screenshots

I would if I could, but I believe my description is very precise.

**Comment by wxiaoguang** [comment]
Outdated, the code has changed a lot.
