### ISSUE TITLE
Build error: Trying to touch file below public/js after  "rm -rf public/js"

### ISSUE THREAD

**Issue by pawsey-kbuckley** [go-gitea/gitea#13052]
- Gitea version (or commit ref): 77f3dbe
- Git version: 1.7.1
- Operating system: CentOS 6.10
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x ] Not relevant
- Log gist:

## Description

Searched issues for "UnhandledPromiseRejectionWarning" but turned up nothing

Building against 

- node-v10.22.1-linux-x64.tar.xz
- go1.15.2.linux-amd64.tar.gz

```
# go version
go version go1.15.2 linux/amd64

# node --version
v10.22.1

# npm --version
6.14.6

# git version
git version 1.71

# cd /usr/local/gitea
# git branch -v
* master 77f3dbe latest version is 1.12.5 (#13005)

# TAGS="bindata" make build

... puls down a load of stuff ..

... Starts building ...

... then fails ...

[15:01:40] Created: ../../web_src/fomantic/build/themes/material/assets/fonts/ic
ons.woff2
[15:01:40] Finished 'Building Assets' after 118 ms
[15:01:40] Finished 'build-assets' after 119 ms
[15:01:40] Finished 'build' after 50 s
rm -rf public/js public/css public/fonts public/img/webpack public/serviceworker.js
npx webpack --hide-modules --display-entrypoints=false
(node:2419) UnhandledPromiseRejectionWarning: Error: "version" is a required argument.
(node:2419) UnhandledPromiseRejectionWarning: Error: "version" is a required argument.
    at Object.getArg (/usr/local/gitea/node_modules/webpack-sources/node_modules/source-map/lib/util.js:24:11)
    at new BasicSourceMapConsumer (/usr/local/gitea/node_modules/webpack-sources/node_modules/source-map/lib/source-ap-consumer.js:294:22)
    at new SourceMapConsumer (/usr/local/gitea/node_modules/webpack-sources/node_modules/source-map/lib/source-map-onsumer.js:22:7)
    at SourceMapSource.node (/usr/local/gitea/node_modules/webpack-sources/lib/SourceMapSource.js:32:62)
    at SourceMapSource.proto.sourceAndMap (/usr/local/gitea/node_modules/webpack-sources/lib/SourceAndMapMixin.js:29:18)
    at getTaskForFile (/usr/local/gitea/node_modules/webpack/lib/SourceMapDevToolPlugin.js:65:30)
    at files.forEach (/usr/local/gitea/node_modules/webpack/lib/SourceMapDevToolPlugin.js:215:20)
    at Array.forEach (<anonymous>)
    at compilation.hooks.afterOptimizeChunkAssets.tap (/usr/local/gitea/node_modules/webpacklib/SourceMapDevToolPlugin.js:186:12)
    at SyncHook.eval [as call] (eval at create (/usr/local/gitea/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:1)
    at SyncHook.lazyCompileHook (/usr/local/gitea/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.optimizeChunkAssets.callAsync.err (/usr/local/gitea/node_modules/webpack/lib/Compilation.js:1413:42)
    at _promise2.then._result2 (eval at create (/usr/local/gitea/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:14:1)
(node:2419) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2419) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
touch: cannot touch `public/js/index.js': No such file or directory
touch: cannot touch `public/css/index.css': No such file or directory
make: *** [public/js/index.js] Error 1
```

## Notes

Bit further back up the build, we saw

```
added 1811 packages from 1184 contributors and audited 1821 packages in 38.437s

116 packages are looking for funding
  run `npm fund` for details

found 6 vulnerabilities (5 low, 1 high)
```

sugesting it did a fair bit, though of course, after the 

```
rm -rf public/js public/css public/fonts public/img/webpack public/serviceworker.js
```

it comes as little surprise to see

```
# ls public/
img  vendor
```

which suggests that any attempt to do this

```
touch: cannot touch `public/js/index.js': No such file or directory
touch: cannot touch `public/css/index.css': No such file or directory
```

is bound to fail.

So what did I miss?

**Comment by silverwind** [comment]
The `touch` is only there to help `make` keep track of build dependencies. Ideally `make` should have failed and exited after the webpack error.

Now that webpack error is strange, I'm not sure why it's happening. It seems to come from [here](https://github.com/mozilla/source-map#new-sourcemapconsumerrawsourcemap).

**Comment by pawsey-kbuckley** [comment]
> Ideally make should have failed and exited after the webpack error.

Given that it does say that 

"Unhandled promise rejections are deprecated. In the future, .."

then the

"UnhandledPromiseRejectionWarning: Error:"

is not really an error, but a warning, then I think make is only doing
what's it being told, no?

Once unhandled promise rejections are obsolete, and the warning 
becomes an error, I am sure make, in which I have a lot of cofindence, 
will do the right thing.

Would you advise a "make -k" ?

**Comment by silverwind** [comment]
Yeah I guess it may be Node's weird way of handling such unhandled rejections that don't cause the process to exit properly. Normally one would run `node --unhandled-rejections=strict` for more sane behaviour but that's not easily possible with package binaries like webpack.

**Comment by pawsey-kbuckley** [comment]
FWIW,

TAGS="bindata" make -k build

run without cleaning anything up from before, has
see it move along a lot further ...

.. to the extent of filling up the disk of the VM I was building it on.

I wonder how much space it needs: didn't see anything in the docs.

**Comment by pawsey-kbuckley** [comment]
Not much more space than I had it turns out, so it seems as though a

TAGS="bindata" make -k build

does do what's required.

Talking of what's required though, when i came to do 

./gitea web

i was told 

```
2020/10/08 16:40:06 cmd/web.go:108:runWeb() [I] Starting Gitea on PID: 2536
2020/10/08 16:40:06 ...s/setting/setting.go:509:NewContext() [W] Custom config '/usr/local/gitea/custom/conf/app.ini' not found, ignore this if you're running first time
2020/10/08 16:40:06 ...dules/setting/git.go:68:newGit() [F] Failed to initialize Git settings%!(EXTRA *log.ColoredValue=Git version not supported. Requires version > 1.7.2)
```

Didn't mention that requirement in the docs either ?

**Comment by silverwind** [comment]
It's documented: https://docs.gitea.io/en-us/#system-requirements

I'd not recommend `-k`. If webpack fails to build, you'll end up with a broken web interface. You can alternatively use the `src` tarball downloads that include precompiled frontend files.

**Comment by pawsey-kbuckley** [comment]
Because I'd started out building from source, I'd been refering to the

https://docs.gitea.io/en-us/install-from-source/

doc, where it only specifies minimum versions for NodeJS and Go.

As I said, it - `make -k` - appears to have worked, not that I have
got that far into the web interface yet.

**Comment by wchen342** [comment]
I had the same problem, and I accidently fixed it by replacing `--hide-modules --display-entrypoints=false` with `--unhandled-rejections=strict`. Don't know why though.

**Comment by wxiaoguang** [comment]
Out dated, the code base has changed a lot
