### ISSUE TITLE
'Add single comment' and 'Start review' 404 error

### ISSUE THREAD

**Issue by EniacMlezi** [go-gitea/gitea#13059]
- Gitea version (or commit ref):
1.12.5
- Git version:
2.28.0.windows.1

- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
When reviewing a PR, both the 'Add single comment' and 'Start review' buttons ask me to reauthenticate and subsequently show a 404 error.  The URL format it redirects to is: domain/ORG/REPO/pulls/3/files#ZgotmplZ/files/reviews/comments. I can't find relevant logs with level set to trace.

Might be unrelated; but after writing a comment, the Preview tab shows up as empty.
...

**Comment by LarsGardien** [comment]
My ROOT_URL was missing a trailing forward slash.
Was:                http://[domain]:3000
Had to be:       http://[domain]:3000/
