### ISSUE TITLE
Issue comment issue: Unwanted empty lines in multi level lists

### ISSUE THREAD

**Issue by per-ok** [go-gitea/gitea#13054]
- Gitea version (or commit ref): 1.12.4 (try.gitea.io: 1.13.0)
- Git version: Not relevant
- Operating system: Not relevant
- Database (use `[x]`): Not relevant
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (https://try.gitea.io/per-ok/test/issues/1, https://try.gitea.io/per-ok/test/src/commit/89c8f09e1456058abfc26b992ce1c7ad0db4d52c/README.md)
  - [ ] No
  - [ ] Not relevant
- Log gist: Not relevant

## Description
This applies to the Issue editor and the Markdown file editor.
Open an issue in gitea and add the this text.  
In write view: an extra intended empty line between "level 2f" and "level 1c" 
In preview view: extra empty lines between "level 1b" and "level 2d", and "level 1c" and "level 2g".  The intended empty line is not present.

* level 1a 
   * level 2a
   * level 2b
   * level 2c
* level 1b
   * level 2d
   * level 2e
   * level 2f
   
* level 1c
   * level 2g
   * level 2h
   * level 2i

## Screenshots
![markdown-issue-write](https://user-images.githubusercontent.com/12234217/95202653-e7078d80-07e1-11eb-8bab-71130cb4ee34.png)
![markdown-issue-preview](https://user-images.githubusercontent.com/12234217/95202646-e3740680-07e1-11eb-9e2d-ff67003cad21.png)

**Comment by zeripath** [comment]
From the common mark js dingus:  (https://spec.commonmark.org/dingus/)

![Screenshot from 2020-10-06 17-24-22](https://user-images.githubusercontent.com/1824502/95229772-e62e2600-07f8-11eb-988d-6bd9c18ab34d.png)

**Comment by zeripath** [comment]
Even Github looks very similar to me...

* level 1a 
   * level 2a
   * level 2b
   * level 2c
* level 1b
   * level 2d
   * level 2e
   * level 2f
   
* level 1c
   * level 2g
   * level 2h
   * level 2i

**Comment by per-ok** [comment]
Compare with no empty lines between the bulletpoints:

https://try.gitea.io/per-ok/test/issues/1#issuecomment-32129

**Comment by silverwind** [comment]
Could fix with this, but I'm not sure if we violate any specs with that.

```css
.markdown:not(code) ul li p {
  margin-bottom: 0;
}
```

**Comment by wxiaoguang** [comment]
I think this problem has been fixed:

<img width="398" alt="image" src="https://user-images.githubusercontent.com/2114189/145052124-d36c7c83-b75e-4651-b715-49c10d69b6dc.png">
