### ISSUE TITLE
error: open /data/gitea/LOG: is a directory

### ISSUE THREAD

**Issue by chrisbra** [go-gitea/gitea#13061]
- Gitea version (or commit ref): no idea, I just pulled a new image using gitea/gitea:latest I suppose this is: (Digest: sha256:65870adb04410220b2f90ed61ae6ed539a4dc01ebd505a6e7ee83fed2121c6cc)
- Git version: git version 2.27.0.windows.1.7.g3c88881ab7.20200616203852
- Operating system: Microsoft Windows [Version 10.0.18362.1082]
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist: https://gist.githubusercontent.com/chrisbra/bc0e1c415e834c8d018f219d2cfef0e1/raw/a459b8427b2c15100986e10163dae4c9ddc46e03/gitea.log

## Description

The container dies with: 
```log
Error: Unable to create queue level for issue_indexer with cfg {"Addresses":"","BatchLength":20,"BlockTimeout":1000000000,"BoostTimeout":300000000000,"BoostWorkers":5,"ConnectionString":"/data/gitea","DBIndex":0,"DataDir":"/data/gitea/indexers/issues.queue","MaxWorkers":10,"Name":"issue_indexer","Network":"","Password":"","QueueLength":20,"QueueName":"issue_indexer_queue","SetName":"","Workers":1} by max attempts: error: open /data/gitea/LOG: is a directory
```

Here is my app.ini
```ini
APP_NAME = Gitea: Git with a cup of tea
RUN_MODE = prod
RUN_USER = git

[repository]
ROOT = /data/git/repositories

[repository.local]
LOCAL_COPY_PATH = /data/gitea/tmp/local-repo

[repository.upload]
TEMP_PATH = /data/gitea/uploads

[server]
APP_DATA_PATH    = /data/gitea
SSH_DOMAIN       = localhost
HTTP_PORT        = 3000
ROOT_URL         = http://localhost:3000/
DISABLE_SSH      = false
SSH_PORT         = 3022
SSH_LISTEN_PORT  = 22
LFS_START_SERVER = false
LFS_CONTENT_PATH = /data/git/lfs
DOMAIN           = localhost
OFFLINE_MODE     = false

[database]
PATH     = /data/gitea/gitea.db
DB_TYPE  = sqlite3
HOST     = localhost:3306
NAME     = gitea
USER     = root
PASSWD   = 
SCHEMA   = 
SSL_MODE = disable
CHARSET  = utf8

[indexer]
ISSUE_INDEXER_PATH = /data/gitea/indexers/issues.bleve

[session]
PROVIDER_CONFIG = /data/gitea/sessions
PROVIDER        = file

[picture]
AVATAR_UPLOAD_PATH            = /data/gitea/avatars
REPOSITORY_AVATAR_UPLOAD_PATH = /data/gitea/repo-avatars
DISABLE_GRAVATAR              = false
ENABLE_FEDERATED_AVATAR       = true

[attachment]
PATH = /data/gitea/attachments

[log]
ROOT_PATH = /data/gitea/log
MODE      = file
LEVEL     = info

[security]
INSTALL_LOCK   = true
SECRET_KEY     = Vn3Ff4jJenju2JBTFsgtIudUiDaOtByXUZE1PYeeHs8ah6nrBl6NVA1c0siVMU1X
INTERNAL_TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYmYiOjE1ODY4NTY0MzV9.8xG1lBblY8VUKe4ERBynAQQeiTPkWqnp0hUAlaqVY34

[service]
DISABLE_REGISTRATION              = false
REQUIRE_SIGNIN_VIEW               = false
REGISTER_EMAIL_CONFIRM            = false
ENABLE_NOTIFY_MAIL                = false
ALLOW_ONLY_EXTERNAL_REGISTRATION  = false
ENABLE_CAPTCHA                    = false
DEFAULT_KEEP_EMAIL_PRIVATE        = false
DEFAULT_ALLOW_CREATE_ORGANIZATION = true
DEFAULT_ENABLE_TIMETRACKING       = true
NO_REPLY_ADDRESS                  = noreply.localhost

[oauth2]
JWT_SECRET = xwH0R481nXVt5XBAEg2e_BKG54zql5jANVU6gDNIgRU

[mailer]
ENABLED = false

[openid]
ENABLE_OPENID_SIGNIN = true
ENABLE_OPENID_SIGNUP = true
```

Now I saw https://github.com/go-gitea/gitea/issues/13023, but the ticket is closed, claiming this is fixed. But for me, I still see the same error. Any advises?

**Comment by chrisbra** [comment]
I tried the suggestion from https://github.com/go-gitea/gitea/issues/13023#issuecomment-703220487

    [queue]
    CONN_STR=/data/gitea/queues

This does not fix the issue, it still terminates with signal15 after 1 minute.

**Comment by chrisbra** [comment]
I went back to image gitea/gitea:1.12.5 and this works.

**Comment by segfaultex** [comment]
I am also seeing this in my k8s deployment.
Everything seems to "work" until the pod fails and restarts. ~1 minute

`
2020/10/07 19:27:01 ...eue/queue_wrapped.go:73:setInternal() [W] [Attempt: 5] Failed to create queue: level for issue_indexer cfg: {"Addresses":"","BatchLength":20,"BlockTimeout":1000000000,"BoostTimeout":300000000000,"BoostWorkers":5,"ConnectionString":"/data/gitea","DBIndex":0,"DataDir":"/data/gitea/indexers/issues.queue","MaxWorkers":10,"Name":"issue_indexer","Network":"","Password":"","QueueLength":20,"QueueName":"issue_indexer_queue","SetName":"","Workers":1} error: open /data/gitea/LOG: is a directory
`
I tried to go back to 1.12.5 but the web interface throws 500 errors and it doesn't see the repositories anymore.
`
2020/10/07 19:32:02 ...les/context/panic.go:35:1() [E] PANIC:: unrecognized repo unit type: 8
`

**Comment by zeripath** [comment]
I need to know the digest of your gitea docker to ensure that you have the latest version.

**Comment by zeripath** [comment]
OK. Around workaround:

```ini
[indexer]
ISSUE_INDEXER_QUEUE_CONN_STR="/data/gitea/indexers/issues.queue"
```

If you drop back to 1.12 you will end up with unmigrated data. This is back thing to do.

**Comment by zeripath** [comment]
@segfaultex - You need to look carefully at the data generated between running master and dropping back to 1.12.5. This data will need to be manually migrated or you will suffer multiple hard to fix and difficult to understand problems in future.

**Comment by segfaultex** [comment]
That workaround fixed it for me. Thanks

**Comment by chrisbra** [comment]
thanks, #13069 seems to have fixed it
