### ISSUE TITLE
Make Email optional for registration?

### ISSUE THREAD

**Issue by gh1593** [go-gitea/gitea#13066]
Just trying to run a small git server, and make the registration process easier.
Is it easy to just skip email check, minimum amount of information required?

**Comment by techknowlogick** [comment]
Email is required for git operations and Gitea performs those operations internally so email is required for gitea. Email doesn't need to be a real address, and you don't need to have gitea send emails.

**Comment by a1012112796** [comment]
@techknowlogick But not all users need to do git operations in the system, Maybe just limmit user to do things about git operations (like create or fork repo, push code) before they add email setting is enough.
