### ISSUE TITLE
[Feature Request] Webhook for google chat (hangout)

### ISSUE THREAD

**Issue by newbenji** [go-gitea/gitea#13063]
It would be nice to have a webhook for google chat (Google Suite)

Right now gitea support slack, teams etc.

https://developers.google.com/hangouts/chat/how-tos/webhooks

**Comment by alexanderadam** [comment]
I guess this could easily be done by your own, once [custom webhook templates are integrated](https://github.com/go-gitea/gitea/issues/1089).
But this probably will still take a while… :wink:

**Comment by techknowlogick** [comment]
Closing in favour of https://github.com/go-gitea/gitea/issues/1089
