### ISSUE TITLE
No permissions to write in /var/lib/

### ISSUE THREAD

**Issue by Quixus** [go-gitea/gitea#13075]
- Gitea version (or commit ref): 1.12.5
- Git version: 2.20.1
- Operating system: debian buster
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist: 2020/10/08 16:28:10 ...eue/queue_wrapped.go:75:setInternal() [W] [Attempt: 236768] Failed to create queue: unique-level for repo_stats_update cfg: queue.LevelUniqueQueueConfiguration{ByteFIFOQueueConfiguration:queue.ByteFIFOQueueConfiguration{WorkerPoolConfiguration:queue.WorkerPoolConfiguration{QueueLength:20, BatchLength:20, BlockTimeout:0, BoostTimeout:0, BoostWorkers:0, MaxWorkers:1}, Workers:1, Name:"repo_stats_update-level"}, DataDir:"/var/lib/gitea/data/queues/repo_stats_update"} error: mkdir /var/lib/gitea/data/queues/repo_stats_update: permission denied

## Description

The /lib/gitea/log/gitea.log is filled with similar entries as above. The files cannot be created because of a permission issue. the owner of the var/lib/gitea/data Folder and subfolders and files is git. Apparently gitea tries to write with a different user. Which user is that? Should I allow this user to write in the folders or should I change the writing user to git. If the latter where do I make that adjustment?

Thanks in advance and best regards

**Comment by jolheiser** [comment]
Gitea runs as the user that runs Gitea.
So what user is running Gitea?

You can check by going to `/admin/config` and looking for `Run As Username`

**Comment by Quixus** [comment]
> You can check by going to `/admin/config` and looking for `Run As Username`
Where should I look? There is no /admin/config. 

I am running it as a sytemd service using the [appropriate guide](https://docs.gitea.io/en-us/linux-service/). in that service file I got
````
Environment=USER=git HOME=/home/git GITEA_WORK_DIR=/var/lib/gitea
````

**Comment by jolheiser** [comment]
My apologies, `/admin/config` as a URL from your base URL. I realize now it looks like a unix path. 🤦‍♂️

**Comment by Quixus** [comment]
Yeah I looked for a unix/linux path. 

The admin/config page says what I expected:

Run As Username   git

I think I found the issue. gitea/data/queues is owned by root instead of git. I have no idea how that happened. I didn't even manually create that folder. Should I simply change ownership to git?

Permissions look as follows:
````
root@gitea:/var/lib/gitea# ls -lad */
drwxr-x--- 2 git git 4096 Oct  7 16:45 custom/
drwxr-x--- 7 git git 4096 Oct  8 09:53 data/
drwxr-x--- 2 git git 4096 Oct  9 13:12 log/
root@gitea:/var/lib/gitea# ls -la */
custom/:
total 8
drwxr-x--- 2 git git 4096 Oct  7 16:45 .
drwxr-x--- 5 git git 4096 Oct  7 16:45 ..

data/:
total 28
drwxr-x---  7 git  git  4096 Oct  8 09:53 .
drwxr-x---  5 git  git  4096 Oct  7 16:45 ..
drwxr-xr-x  2 git  git  4096 Oct  8 10:32 avatars
drwxr-xr-x  4 git  git  4096 Oct  7 17:39 indexers
drwxr-xr-x  2 git  git  4096 Oct  7 17:30 lfs
drwxr-xr-x  3 root root 4096 Oct  7 16:52 queues
drwx------ 11 git  git  4096 Oct  9 12:08 sessions

log/:
total 263640
drwxr-x--- 2 git git      4096 Oct  9 13:12 .
drwxr-x--- 5 git git      4096 Oct  7 16:45 ..
-rw-r----- 1 git git 223945163 Oct  9 15:57 gitea.log
-rw-r----- 1 git git   3225757 Oct  7 20:24 gitea.log.2020-10-07.001.gz
-rw-r----- 1 git git   3094436 Oct  7 23:01 gitea.log.2020-10-07.002.gz
-rw-r----- 1 git git   1142444 Oct  8 00:00 gitea.log.2020-10-08.001.gz
-rw-r----- 1 git git   3094305 Oct  8 02:37 gitea.log.2020-10-08.002.gz
-rw-r----- 1 git git   3109907 Oct  8 05:14 gitea.log.2020-10-08.003.gz
-rw-r----- 1 git git   3077791 Oct  8 07:51 gitea.log.2020-10-08.004.gz
-rw-r----- 1 git git   3368601 Oct  8 10:36 gitea.log.2020-10-08.005.gz
-rw-r----- 1 git git   3496837 Oct  8 13:52 gitea.log.2020-10-08.006.gz
-rw-r----- 1 git git   3306903 Oct  8 17:10 gitea.log.2020-10-08.007.gz
-rw-r----- 1 git git   3156921 Oct  8 20:28 gitea.log.2020-10-08.008.gz
-rw-r----- 1 git git   3159872 Oct  8 23:47 gitea.log.2020-10-08.009.gz
-rw-r----- 1 git git    203923 Oct  9 00:00 gitea.log.2020-10-09.001.gz
-rw-r----- 1 git git   3135152 Oct  9 03:18 gitea.log.2020-10-09.002.gz
-rw-r----- 1 git git   3099933 Oct  9 06:36 gitea.log.2020-10-09.003.gz
-rw-r----- 1 git git   3090437 Oct  9 09:55 gitea.log.2020-10-09.004.gz
-rw-r----- 1 git git   3217055 Oct  9 13:12 gitea.log.2020-10-09.005.gz
````

**Comment by jolheiser** [comment]
Yes, it should be owned by git.

It may have been that you ran Gitea as root to test it out or something before setting up the service. 🙂 

I'm going to close this since we found the permission issue.

**Comment by Quixus** [comment]
> It may have been that you ran Gitea as root to test it out or something before setting up the service. 🙂

Yup, that was exactly it. Thanks for the help.
