### ISSUE TITLE
head_navbar.tmpl not working as expected

### ISSUE THREAD

**Issue by embeddedpenguin** [go-gitea/gitea#13076]
- Gitea version (or commit ref):
1.12.2
- Git version:
2.20.1
- Operating system:
GNU/Linux (Arch)
- Database (use `[x]`):
  - [x ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ x] Not relevant
- Log gist:

## Description

I am using the template found [here](https://raw.githubusercontent.com/go-gitea/gitea/master/templates/base/head_navbar.tmpl) using [this guide](https://www.thedroneely.com/posts/lets-customize-gitea/#the-customization) to customize gitea. I just wanted to change the favicon and the logo in the top left for now. But I can't even get the template to work. I've placed that template in custom/template/base/ as head_navbar.tmpl and I get the error seen below:

```
template: base/head_navbar:154:7: executing "base/head_navbar" at <svg>: wrong number of args for svg: want 2 got 1
```

**Comment by jolheiser** [comment]
That template is for master (1.13) rather than your version (1.12).

The template you want is https://github.com/go-gitea/gitea/blob/release/v1.12/templates/base/head_navbar.tmpl
