### ISSUE TITLE
‘cron.update_mirrors’ can not be set to ‘@every 1d’

### ISSUE THREAD

**Issue by blueskink** [go-gitea/gitea#13086]
- Gitea version (or commit ref): 1.13.0+dev-664-g2dbca92a0
- Git version:
- Operating system: docker
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
[cron.update_mirrors]
SCHEDULE = @every 1d

h m is ok

...

**Comment by jolheiser** [comment]
My initial guess is because it uses `time.ParseDuration` internally, which says

> Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h".

If that's the case, we could update the docs accordingly.

**Comment by zeripath** [comment]
The internal system is: https://godoc.org/github.com/gogs/cron


You can use `@daily`, `@every 24h`, `0 0 0 * * *`.

**Comment by 6543** [comment]
I'll close this.

@blueskink if it did not work ask for reopen it
