### ISSUE TITLE
http page request https resources

### ISSUE THREAD

**Issue by blueskink** [go-gitea/gitea#13087]
- Gitea version (or commit ref): 1.13.0+dev-664-g2dbca92a0
- Git version:
- Operating system:
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description
open http://domain/api/swagger
page request https://domain/swagger.v1.json
...

**Comment by 6543** [comment]
I think you have set the ROOT_URL wrong in your config
