### ISSUE TITLE
Mozilla firefox browser crashing everytime trying to create a new organization

### ISSUE THREAD

**Issue by loannaflip** [go-gitea/gitea#13082]
- Firefox:
  - Version: `81.0.1`
  <img src="https://i.imgur.com/FMp502x.png">

- Compiler used: `clang`
  - clang version: `10.0.1`

- Gitea version (or commit ref): `1.12.5`
- Git version: `2.28.0`
- Operating system: Gentoo Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description
Mozilla firefox browser crashes/closes when the `+` button is pressed for creating a new organization. Tested using admin user. I can't reproduce the bug at `https://try.gitea.io`, although it's always reproducible on my local system.

## Screenshots
A Screen of the button which causes the crash/close (Mozilla firefox browser) is given below.
<img src="https://i.imgur.com/m6z83hg.png">

**Comment by Uniminin** [comment]
Turned out to be other fault. I've fixed it.
