### ISSUE TITLE
[Feature Request] Better sorting when chose the owner from the list

### ISSUE THREAD

**Issue by somera** [go-gitea/gitea#13090]
- Gitea version (or commit ref): 1.12.5
- Git version: 2.25.1
- Operating system: Ubuntu 20.04
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite

## Description

In my local Gitea instance I had a lot of organizations. Whe I have to add new mirror project than I have to chose the organzation. I know, that the organization exists. I press first letter, i.e. h. And Gitea shows me hpc. But I look for other organization which starts with h. Than I had to scroll whole list, to search for the right organization.

As user I expect to see only organizations which starts with h or whole list with all organizations but all with h at the beginning should be first in the list.

## Screenshots

![image](https://user-images.githubusercontent.com/8334250/95654286-55f52700-0aff-11eb-8812-7a7b26cc4ac2.png)

**Comment by somera** [comment]
Or the other Feature Requst #13091

**Comment by eneuschild** [comment]
## What do we want here?
It seems to me like the list of possible Owners is sorted by "most recent". Do we want an alphabetical order instead? By default?

## Option 1
Sort list of possible owners alphabetically by default. Then, when typing, the highlight would move to the block of entries starting with the user's input, thereby addressing @somera's issue.

## Option 2
Keep list sorted by most recent, but switch to alphabetical order when user starts typing. Same benefit as option 1, but probably pretty confusing.

## Option 3
Keep list sorted by most recent, but limit entries to those that match what the user is typing and remove all that don't.

**Comment by somera** [comment]
On my local Gitea instance I have 160 organisations. ;)

Option 1 is what I personally prefer.

The goal is to find "fast" the right organisation which starts with X character.
