### ISSUE TITLE
[Feature Request] New "Add Mirror" Button in the Organization view

### ISSUE THREAD

**Issue by somera** [go-gitea/gitea#13091]
- Gitea version (or commit ref): 1.12.5
- Git version: 2.25.1
- Operating system: Ubuntu 20.04
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite

## Description

At the moment it possible to create new repo in the organization. It will be nice to have an "Add new mirror" action. In this view. After click the "migrate" view will open and the right organization will be selected.

## Screenshots

![image](https://user-images.githubusercontent.com/8334250/95654412-1418b080-0b00-11eb-9d0d-1f8e3cb20098.png)

**Comment by divbhasin** [comment]
Hi, new contributor here 👋  I can have a crack at this.

**Comment by zeripath** [comment]
PRs are welcome
