### ISSUE TITLE
Duplicating a gitea repo (+setup) ?

### ISSUE THREAD

**Issue by chrisbward** [go-gitea/gitea#13099]
Hi, not a bug - but just wondering if it's possible to copy an existing gitea repo/setup?

I have a project that I want to clone (copy) on the fly, and may need to do this multiple times.

I've noticed there's the fork method in the API (https://try.gitea.io/api/swagger#/repository/createFork), but it appears I'll only be able to do this once per organisation?

**Comment by zeripath** [comment]
You can fork and then make it not a fork?

**Comment by chrisbward** [comment]
Thanks - is this a newer feature? I can't seem to find it on 1.8.3.

I was able to fork the repo using the API, but only once...

**Comment by 6543** [comment]
@chrisbward could be, i recomend you to upgrade anyway ...

**Comment by 6543** [comment]
and if you like to create "closes" of a repo without having it liked as fork you can use the "migrate" feature/api

**Comment by lunny** [comment]
Use template projects

**Comment by zeripath** [comment]
> Thanks - is this a newer feature? I can't seem to find it on 1.8.3.

Please upgrade.

There are 1880 lines of CHANGELOG.md between 1.8.3 and 1.12.5. 39 of those lines refer to Security issues. Over 8000 files have been changed with over a million lines with code insertion and nearly half a million lines, at least partly, deleted.

We can't support such old Giteas.

**Comment by chrisbward** [comment]
Hi thanks - I upgraded, can now see the feature - but it isn't available in the API?

**Comment by chrisbward** [comment]
> and if you like to create "closes" of a repo without having it liked as fork you can use the "migrate" feature/api

thanks - I will give that a try - assuming it does gitea to gitea migrations?

**Comment by 6543** [comment]
@chrisbward gitea2gitea migration current state: only git repo itselve ... full migration will come soon ;)

**Comment by 6543** [comment]
> Hi thanks - I upgraded, can now see the feature - but it isn't available in the API?

I dont think converting a fork into a normal repo can be done via api at the moment

**Comment by 6543** [comment]
(close because question was answerd)
