### ISSUE TITLE
why PushToBaseRepo

### ISSUE THREAD

**Issue by zhoutt96** [go-gitea/gitea#13106]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
Hi team, can anyone explain why do we need the PushToBaseRepo when creating a new pull request, can not understand this very well, thanks. 
...

**Comment by zeripath** [comment]
We make corresponding branches in the base repo for each pr. So for example pr number 6 would have a branch refs/pulls/6/head.

**Comment by zhoutt96** [comment]
thanks for your quick reply, also, I know what does baseBranch and headBranch mean, we need to merge headBranch to baseBranch, but what does headRepo and baseRepo mean and HeadRepo.RepoPath() mean?  thanks!

**Comment by zeripath** [comment]
You are merging the head branch from the head repo to the base branch in the base repo.

(Imagine a situation where you are doing a pr from your forked repository `zhoutt96/fork` to `zeripath/base`.)

`HeadRepo.RepoPath()` is simply the filesystem path of the head repo.

**Comment by zhoutt96** [comment]
Thanks, Does it mean if I did not fork the repository and only create a branch on headRepo, then creating a PR for this repo, the PushToBaseRepo operation can be skipped?
