### ISSUE TITLE
Adding deploy key with duplicate name: unclear error message

### ISSUE THREAD

**Issue by chrisshyi** [go-gitea/gitea#13110]
- Gitea version (or commit ref): 845d0afb3326f147dc78059bbdcecf45c3a9a0df
- Git version: 2.25.1
- Operating system: Ubuntu 20.04.1
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
Gitea only displays a HTTP 500 error page when the user attempts to add a deploy key that has the same name as an existing key (the keys themselves are different). I'd like to work on the displaying of a more informative error message when this occurs.

## Screenshots

![image](https://user-images.githubusercontent.com/24416618/95720457-d94f7d80-0ca3-11eb-8d10-047e4348858c.png)

**Comment by techknowlogick** [comment]
We'd be happy to receive a PR for this :)

**Comment by chrisshyi** [comment]
Fantastic. I was wondering if you could give me some tips on how I get `dlv` or `vscode` set up to debug Gitea. I tried the `launch.json` files provided by the project and couldn't get debugging to work on vscode.

**Comment by 6543** [comment]
I dont think you will have to debug a lot of go code ...
the easyest way is to add some `fmt.println(var-you-like-to-konw-value-of)` in the code ...

**Comment by chrisshyi** [comment]
gotcha, I'll give it a try!
