### ISSUE TITLE
[PROPOSAL] Issue groups - refer to GitLab

### ISSUE THREAD

**Issue by bryanpedini** [go-gitea/gitea#13117]
- Gitea version (or commit ref): master
- Git version: N/A
- Operating system: N/A
- Database (use `[x]`): N/A
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist: N/A

## Description

It would be nice to have in a distant future, for better management and bot integrations like on single categories, label groups via `::` in the middle of a label name, signaling the software "use the first part before the "keyword" as group name and the second part as the group member", or something like that.
See attached screenshots of GitLab.com:

## Screenshots

![Screenshot_20201012_194954](https://user-images.githubusercontent.com/45012292/95776369-77534000-0cc4-11eb-9f65-1d808d7fe597.png)

**Comment by lafriks** [comment]
imho we should use `/` as label group separator. Does this only affect how they are displayed?

**Comment by bryanpedini** [comment]
> imho we should use `/` as label group separator.

Whatever makes the backend distinguish between the group name and the group member should be all right to me...

> Does this only affect how they are displayed?

I think so, in the list they're still the same (complete text also with separator):<br>
![Screenshot from 2020-10-13 11-40-57](https://user-images.githubusercontent.com/45012292/95844276-04d87380-0d49-11eb-8762-c6003e294c5e.png)

**Comment by koalp** [comment]
I may use label groups to interact with kanban/projects in the future (with a bot) : *for example, putting the label `scope/X` would automatically send the issue in the project `X` and `status/Y` would be set when moving the issue in the column.*
I think a way to display those groups in the interface is indeed a good idea.
I also use scoped labels for priorities. (and currently use the "::" separator from gitlab)

**Comment by bryanpedini** [comment]
It is useless to note, that better integrations would benefit everyone, using `::` as delimiter, exactly like GitLab would render bots and plugins much easier for both parties since they share the same "principle technology behind" 😃

**Comment by koalp** [comment]
> Does this only affect how they are displayed?

Actually, in gitlab labels that are in the same "scope/group" are mutually exclusive and can't be present on the same issue. But a display-only would be enough I think.

**Comment by bryanpedini** [comment]
> But a display-only would be enough I think.

I agree, with the ability to perform external hooks when a label gets added / removed to an issue, but that I think it's probably a different issue altogether.

**Comment by bryanpedini** [comment]
is bumping legal here?
on a more serious note: is this FR still in consideration in the future? it would be a nice-to-have

(no, I haven't learned Go that well yet to even draft a PR... sadly...)

**Comment by bryanpedini** [comment]
Thank you for pointing that out.

**Comment by brechtvl** [comment]
I believe this can be closed now, further improvements to this are being tracked in #22974.
