### ISSUE TITLE
Gitea should prohibit restoring backup of older schema than currently installed

### ISSUE THREAD

**Issue by CirnoT** [go-gitea/gitea#13113]
Backup should store its schema version and restore tool should not allow restoring data onto already existing database schema that is of newer version that that of backup.

Such action results in data being migrated without necessary migrations. User should be advised to restore backup on the same version of Gitea as it was made to, and only then upgrade to newer version.

**Comment by 6543** [comment]
@CirnoT we have no restore command at the the moment

and since #12760 we do store database version within the dump

**Comment by zeripath** [comment]
I think now we store the version in the version table that we're safe now. Therefore I think this issue can be closed.
