### ISSUE TITLE
Description for issues.ref_closing_from ambiguous and incorrectly localized

### ISSUE THREAD

**Issue by qwertfisch** [go-gitea/gitea#13123]
- Gitea version (or commit ref): 1.12.3
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

After a pull request is added by a user and linked to an issue, the following reference is then described in the given format:
> `user` referenced a pull request that will close this issue `time of reference`

A specific example would be:
> **qwertfisch** referenced a pull request that will close this issue 1 week ago

### Ways of reading

  1. The **meaning** of it, as I understand, is that a user has referenced a pull request 1 week ago, and this pull request will (at some other time in the future) close this issue.
  1. But the **actual reading** tells me that a user referenced a pull request, and this pull request will close this issue 1 week ago (which doesn’t make any sense, at least for me).

This is quite ambiguous. Even more so in German, which clearly is translated unambiguously by the second form (considering the position of the comma and the date inside the subordinate clause).

> qwertfisch hat auf einen Pull Request verwiesen, welcher das Issue vor 1 Woche schließen wird

Unfortunately English does not enforce commas and also puts the date at the end of the sentence.

## Screenshots

![scr_20201013-002146](https://user-images.githubusercontent.com/4212687/95795277-438b1100-0cea-11eb-8e9f-89e5fb882b65.png)
![scr_20201013-002200](https://user-images.githubusercontent.com/4212687/95795275-42f27a80-0cea-11eb-8a9d-daa1b1a43aa8.png)

## Possible solution

I am not sure if this is a definitive bug or just an ambiguous way of reading (for English). At least the German translation should be changed to not represent the second form semantically.

An umambiguous reading could be something like this:
> **qwertfisch** has referenced a pull request 1 week ago, that will close this issue

This way only the part “has referenced a pull request” can be an href link, not the text “that will close this issue” after the date. This behaviour is already present at the incorrect German translation, where “schließen wird” (after the date) is just text, not an href.

**Comment by 6543** [comment]
solution: fix template to: add a check if time is in the past ... if true, use new translation strings <- has to be added

**Comment by qwertfisch** [comment]
The date will *always* be in the past because it references the date when the pull request was added.

**Comment by 6543** [comment]
oh missed that ... then it's easy: fix the english translation by creating a pull and the rest is done via crowdin

**Comment by ivanvc** [comment]
Rather than changing the ordering of the words, I think a good solution would be maybe adding a hyphen before the time of reference.

i.e.
> `user` referenced a pull request that will close this issue – `time of reference`
> **qwertfisch** referenced a pull request that will close this issue – 1 week ago

But then, this will mean that many actions that have the time reference at the end would need an update, not just the reference to the pull request. Does this sound like something feasible? I can do the PR to address this. Just want to know this sounds like the correct decision (cc. @6543)

**Comment by zeripath** [comment]
I think adding an em-dash — (U+2014) (not hyphen) would be a good idea

**Comment by eneuschild** [comment]
I've been thinking the same thing as @ivanvc. The English version is ambiguous, yes, but not a bad wording per se. Visually setting off the date string rather than incorporating it into the sentence looks to me like a good way to resolve the ambiguity and also make sure that date strings can be at the end of the message in all languages alike.

I have also suggested a correction of the faulty German translation on Crowdin, which still needs to be reviewed there. Let's see how quick they are. ;)

**Comment by ivanvc** [comment]
I'm hesitating about this change... If the localization has an em-dash, then it will be inconsistent with the text from other events on the issues and pull requests pages.

It immediately looks inconsistent with the header of the comment:
![Screenshot from 2020-10-15 09-21-17](https://user-images.githubusercontent.com/27286/96158140-07ada280-0ec8-11eb-91a4-f4b668992a1c.png)

Perhaps a better solution would be to standardize the colors from the strings in the actions section with the rest of them? I think it looks fine and helps differentating the timestamp from the actual text, i.e.:
![Screenshot from 2020-10-15 09-24-49](https://user-images.githubusercontent.com/27286/96158371-4c393e00-0ec8-11eb-848a-542cb8e66a53.png)

And the rest of the events even in issues could benefit from this:
![Screenshot from 2020-10-15 09-26-13](https://user-images.githubusercontent.com/27286/96158621-8c002580-0ec8-11eb-998f-6f834168002e.png)

**Comment by eneuschild** [comment]
> I'm hesitating about this change... If the localization has an em-dash, then it will be inconsistent with the text from other events on the issues and pull requests pages.

True, if we only change it for **this** message. 
But what if we apply this to **all** event texts?

**Comment by ivanvc** [comment]
That was what I initially was doing, changing it from all the event texts. However, I noticed that it looked somewhat incosistent with the text from the section headers. I guess there are two improvements here. One is to standardize the style across those texts, and another is to add the dash to the localization files.

**Comment by qwertfisch** [comment]
In most cases as in „added 2 commits 22 hours ago“ the timestamp at the end of the sentence looks good and is sementically correct. It works well in English, whereas e.g. in German the timestamp always comes before the participle. The ambiguity in English for this specific case might just be kept. If one has understood the message once, one will most likely not misread on further occurences.

Also I did not intent to start a general discussion about wording and structure. My initial report was just to confirm I understood the meaning correctly, and that the German translation should be fixed. 

@eneuschild Is there an accessible link on Crowdin to the proposed German translation? I did not post my translation in this issue yet and would just move the timestamp after the main verb:
> qwertfisch hat vor einer Woche auf einen Pull Request verwiesen, welcher das Issue schließen wird

**Comment by eneuschild** [comment]
@qwertfisch The link is https://crowdin.com/translate/gitea/68/enus-de?filter=basic&value=0#74642, but it requires login.

My suggestion on crowdin was to move the timestamp to the end:

> qwertfisch hat auf einen Pull Request verwiesen, welcher das Issue schließen wird vor einer Woche

Now that I look at it in a proper sentence, that looks terrible. Your way is clearly better for German, but there's still the timestamp-at-the-end consistency issue. I'm unsure which way to go.

**Comment by qwertfisch** [comment]
As I said previously, the timestamp is in many German translations already not at the end, because of the language itself. I see no reason why to start with awkwardly sounding sentences now.

Would you change your suggestion on Crowdin or how does this work?

**Comment by eneuschild** [comment]
> Would you change your suggestion on Crowdin 

Yes, I agree. Done.
