### ISSUE TITLE
Backtick in mailer passwd

### ISSUE THREAD

**Issue by openscript** [go-gitea/gitea#13126]
- Gitea version (or commit ref): 1.12.4 
- Git version: not relevant
- Operating system: not relevant
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
We use a email password with back ticks inside. According to https://docs.gitea.io/en-us/config-cheat-sheet/, for complex mailer `passwd` back ticks should be used. How to deal with back ticks within the password?

**Comment by zeripath** [comment]
try putting it in `"""`

**Comment by openscript** [comment]
> try putting it in `"""`

Like 

    passwd = """nasd´$asd92mc"asdkasd"""

?

**Comment by zeripath** [comment]
yes

**Comment by openscript** [comment]
Great that works! I'll add this to the documentation.
