### ISSUE TITLE
Docker-compose files listed for MySQL database in documentation doesn't work out of the box

### ISSUE THREAD

**Issue by ElTimablo** [go-gitea/gitea#13122]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:

## Description
In both the Docker hub page and the official documentation, YAML files are provided that do not and will not work due to a carousel of errors that occur whenever I attempt to run the installer. This is my docker-compose.yml:
```version: "3"

networks:
  gitea:
    external: false

services:
   server:
     image: gitea/gitea:latest
     container_name: gitea
     environment:
       - USER_UID=1000
       - USER_GID=1000
       - DB_TYPE=mysql
       - DB_HOST=db:3306
       - DB_NAME=gitea
       - DB_USER=gitea
       - DB_PASSWD=gitea
     restart: always
     networks:
       - gitea
     volumes:
       - ./gitea:/data
       - /etc/timezone:/etc/timezone:ro
       - /etc/localtime:/etc/localtime:ro
     ports:
       - "3000:3000"
       - "11222:22"
     depends_on:
       - db

   db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=gitea
      - MYSQL_DATABASE=gitea
    networks:
      - gitea
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3307:3306"
```
Most frequently and infuriatingly, I get "The database settings are invalid: dial tcp 172.24.0.2:3307: connect: connection refused" despite being able to reach it using the mysql command on the host. The port is set to 3307 because there's another MySQL container on the same system. Running two databases on the same server has never, ever presented a problem for me before and I don't expect it to start now.

**Comment by techknowlogick** [comment]
When you run the installer are you saying use port 3307? Because the image itself listens on 3306 via the docker network, so you should use that. As 400+ receive these emails, please continue over at https://discord.gg/gitea or https://discourse.gitea.io/ for help configuring your install. I'm going to close this issue now.

**Comment by ElTimablo** [comment]
**The port is set to 3307 because there's another MySQL container on the same system**

**Comment by techknowlogick** [comment]
Yes, but the mysql is listening on 3306 inside the container *AND* on the docker network. It is only listening to 3307 on your host. The error you gave reports trying to connect to `172.24.0.2:3307` which is via the docker network, not via your host. Our examples don't provide the port setting for the DB as the documentation directs users to use the docker network. As said, please continue this in the other support locations, this isn't an error with the documentation.
