### ISSUE TITLE
gitea.com不能访问了！！！

### ISSUE THREAD

**Issue by xiaofeige** [go-gitea/gitea#13130]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

...

**Comment by jolheiser** [comment]
`gitea.com` is currently down while we switch providers.

**Comment by xiaofeige** [comment]
> `gitea.com` is currently down while we switch providers.
sorry, I just wonder will it recover? how long?

**Comment by jolheiser** [comment]
You can follow #13131 for updates. 🙂
