### ISSUE TITLE
Comment text editor is broken on mobile

### ISSUE THREAD

**Issue by kolaente** [go-gitea/gitea#13132]
- Gitea version (or commit ref): 1.13.0+dev-682-g95ff55991
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant

## Description

The text editor (the one used for comments and issues/PRs) is pretty much unusable on mobile. See the videos below:

![ezgif-7-8713f1a4508d](https://user-images.githubusercontent.com/13721712/95870246-92798a80-0d6c-11eb-8e6c-ba0eb01854ae.gif)

It is especially bad when using the autocompletion for words:

![ezgif-7-70e8d12aa6c6](https://user-images.githubusercontent.com/13721712/95870633-01ef7a00-0d6d-11eb-95c6-e2f24d235e6a.gif)

I suspect this is due to some gitea made csutomizations of the text editor, maybe the file upload.
I will try to verify this with all plugins disabled.

**Comment by 6543** [comment]
@kolaente a bit unrelated but have you tryed [GitNex](https://gitnex.com/)?

**Comment by jolheiser** [comment]
Also, that button at the end of the header is your best friend. It reverts it to a normal textarea. 🙏

**Comment by kolaente** [comment]
@6543 I even have it installed, but I'm a lazy person and links open right away in my browser from my mail app 😀 

@jolheiser I actually found that a few minutes after I opened this issue, more or less by accident. I guess I'm stuck with that for now it kind of is only a workaround

**Comment by silverwind** [comment]
Related: https://github.com/go-gitea/gitea/issues/10729

**Comment by corneliusroemer** [comment]
I reproduced the issue on a variety of browsers (Chrome, Brave, Edge, Opera) based on Chrome86/87 on Android 11, Oneplus 8T on codeberg.org: https://codeberg.org/Codeberg/Community/issues?labels=338

Haven't found a browser that works with the editor.

Have you made any progress on fixing it? Issues are often the first point of contact with hosted Git services - so to not repel new potential users you may want to prioritise fixing this soon - maybe even disabling WYSIWYG on mobile by default until fixed.

**Comment by corneliusroemer** [comment]
> * Gitea version (or commit ref): 1.13.0+dev-682-g95ff55991
> * Can you reproduce the bug at https://try.gitea.io:
>   
>   * [x]  Yes (provide example URL)
>   * [ ]  No
>   * [ ]  Not relevant

I think these boxes should be radios not checkboxes, the fact that they are checkboxes makes the issue overview show "1/3 completed" when this is absolutely not what the boxes represent. This could be due to the checkboxes being part of a template.

**Comment by 6543** [comment]
-> #12146
