### ISSUE TITLE
Pull Request Ref is not deleted when PR is closed or merged

### ISSUE THREAD

**Issue by zhoutt96** [go-gitea/gitea#13135]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
Your Pull Request Ref refs/pull/1/head is still there even when the PR is closed or merged, should it be deleted? 

...

**Comment by zeripath** [comment]
No. It's deliberate so you can go back and see what the ref was.
