### ISSUE TITLE
gitea.com is migrating to a new provider

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#13131]
Since our donated cloud provider of gitea.com will not provide us any more, we will move gitea.com to a new place. The move will be taken for many hours.

**Comment by jolheiser** [comment]
The database has finished, now we are syncing git data. :slight_smile:

**Comment by xiaofeige** [comment]
> The database has finished, now we are syncing git data. 🙂

syncing takes how long?

**Comment by xiaofeige** [comment]
> The database has finished, now we are syncing git data. 🙂

how long will it take?

**Comment by 6543** [comment]
1.1T ...

**Comment by renothing** [comment]
maybe you should consider store the repositories into object service such as S3/wasabi etc..

**Comment by lunny** [comment]
@renothing Yes, we will. But gitea just support S3 in unreleased v1.13

**Comment by 6543** [comment]
... Drone database moved ...

**Comment by 6543** [comment]
"Gitea.com is up again. We have migrated to a new cloud provider, but missed serval days git data. We are sorry for that. Please check your repositories, the missed commits could be pushed from your local."
