### ISSUE TITLE
original url not changed

### ISSUE THREAD

**Issue by lion187chen** [go-gitea/gitea#13151]
- Gitea version (or commit ref):  1.12.4
- Operating system: Linux
- Database (use `[x]`): SQLite

## Description

"mirror of" and "original url" not changed after "Clone From URL" in setting page is modified.

**Comment by lunny** [comment]
Please give more details

**Comment by lion187chen** [comment]
1. Create a "New Migration" and select "This repository will be a mirror"
2.Go to the setting page of this repository
3. Change the "Clone From URL"
The "mirror of" of this repository not changed.

**Comment by 6543** [comment]
I created a issue for that - so it is a dublicate ...

**Comment by 6543** [comment]
@lion187chen thanks for reporting issues. But pleace first have a look if there is a new stable version :)

THIS issue was first reported at  #12962 and is fixed in v1.12.5 via #12967

**Comment by lion187chen** [comment]
I agree :)

**Comment by lion187chen** [comment]
> @lion187chen thanks for reporting issues, we appreciate it.
> 
> But pleace first have a look if there is a new stable version :)
> 
> Issue was first reported at #12962 and is fixed in v1.12.5 via #12967

I agree :)
