### ISSUE TITLE
Archived repos visible on issues overview page

### ISSUE THREAD

**Issue by tinxx** [go-gitea/gitea#13171]
- Gitea version (or commit ref): 1.12.5
- Git version: 2.26.2
- Operating system: Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

If you archive a repo it is still taken into account for the issue overview at `/issues`.

I would expect it to be hidden like it is hidden e.g. from the repo list on the dashboard. 

## Screenshots

![Screenshot_2020-10-16 Gitea Git with a cup of tea](https://user-images.githubusercontent.com/13608545/96220116-6e929080-0f88-11eb-84ea-a7414e63e4e5.png)

![Screenshot_2020-10-16 Repo_B](https://user-images.githubusercontent.com/13608545/96220130-72261780-0f88-11eb-992f-609ac66cb508.png)

**Comment by eneuschild** [comment]
Some noob questions on how to tackle this:
* Apparently, the code that corresponds to this feature is a [360-lines-long function](https://github.com/go-gitea/gitea/blob/master/routers/user/home.go#L324). Would it be acceptable for me to refactor this into several smaller funcs, before I hunt down the actual bug?
  * If so, would I make two separate PRs for the refac and the bug fix?
* Am I right in assuming that, in order to filter issues, I'd use the `IssuesOptions`, and extend those with a field like `DisallowArchived`?

**Comment by zeripath** [comment]
@eneuschild if you can refactor it I'd say do so - but you may find yourself having to deal with the law of unintended consequences multiple steps along the way and you'll find multiple stylistic differences between the various reviewers.

* One thing I would recommend is to spread comments liberally through the code first to explain what you understand is going on, especially if the code is not immediately understandable. Whole sections of code might need preceding paragraphs to explain what they're doing. (You're spending all of this time to understand this code so you may as well help others)
* Once you have a good grasp of each bit consider if the piece of code you're seeing could be a function.
* I personally would prefer if we avoided functions that write to the `ctx` with `ctx.ServerError()`, `ctx.HTML()` or the like unless they're terminal and genuinely taking over the control flow. If you can avoid these please do! If you pass the modules/context/context.Context to a function you either need to follow a call to it with 

``go
_, ...  = fn(ctx, ...)
if ctx.Written() {
  return
}
// do stuff with your _, ...
```

Or write in a comment on the function something along the lines of `// DO NOT WRITE TO THE CONTEXT`. (I do wonder if we can use the type system to fix this.)

In terms of one or two PRs - it might be reasonable to open two but ensure that the second contains the first. The other thing is that a nice clean history in refactor case would be (at least until someone has reviewed) Rewrite your history using rebase if necessary to make the commits look clean and logical. Once someone has reviewed though please ask reviewers before rebasing as it especially with large reviews it can make it very difficult indeed.

**Comment by lunny** [comment]
Should this be a filter option or just hide all archived repositories?

**Comment by eneuschild** [comment]
> Should this be a filter option or just hide all archived repositories?

Since this is about the issues overview, I'd say entirely hiding issues from archived repos is a good way to go.

**Comment by tinxx** [comment]
There is a [Merge Request](https://github.com/go-gitea/gitea/pull/13220) being worked on so this issue is not stale. Thanks @eneuschild :)   
Just posting this to keep the bot happy...
