### ISSUE TITLE
diff view leaks some html code

### ISSUE THREAD

**Issue by zig** [go-gitea/gitea#13177]
- Gitea version (or commit ref): 1.13.0+dev-593-g0db9043aa built with GNU Make 4.3, go1.15.2 : bindata, sqlite, sqlite_unlock_notify
- Git version: 2.26.2
- Operating system: gitea official docker
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes : https://try.gitea.io/zigg/testme/commit/9bd6915f409b3ae13dd284a716212059129c8dfe
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

Diff view sometimes show additional html tag that should not be visible

## Screenshots

![image](https://user-images.githubusercontent.com/85303/96274481-1d73b280-1003-11eb-8036-a6f1e775b130.png)

But it should be : 

```
-    print "// ", sys.argv
+    print("// ", sys.argv)
```

Note however that the extra tag is not visible in the file view : 
![image](https://user-images.githubusercontent.com/85303/96275013-c9b59900-1003-11eb-9d6f-b384a5892892.png)

**Comment by zeripath** [comment]
Heya @mrsdizzie are you able to take a look?

**Comment by techknowlogick** [comment]
@zig as you are running a development version, could you upgrade to the latest commit? There have been some changes to the above (specifically diff handling & chroma)

**Comment by mrsdizzie** [comment]
This was a bug that was fixed a few months ago during syntax highlighting transition and shouldn't be present anymore. Can you link to a current example of this? Or put up an example on try.gitea.io. If it isn't private you could just push the repo and it would retain the commit history that should produce the diff.

I tried to reproduce with the small example given but it looks ok to me:

 https://try.gitea.io/mrsdizzie/testme/commit/3d06f1f836fc248bbba9be7a8c18d019559e7ccb

But it might depend on other information so an example to see would be best. Thanks!

**Comment by zig** [comment]
@mrsdizzie  thanks for looking into this, in your test you added a space between `print` and the `(`, without a space, the bug occurs : 

https://try.gitea.io/zigg/testme/commit/9bd6915f409b3ae13dd284a716212059129c8dfe

**Comment by mrsdizzie** [comment]
@zig thanks, will look into
