### ISSUE TITLE
cron execute non enabled tasks

### ISSUE THREAD

**Issue by rozhuk-im** [go-gitea/gitea#13174]
- Gitea version (or commit ref): 1.12.4 
- Git version: 2.28.0
- Operating system: FreeBSD 12.2 amd64
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description

Some disabled cron tasks always run at 11.40.

We got in logs:
```
Cron: Reinitialize all missing Git repositories for which records exist has finished
Cron: Delete all repositories missing their Git files has finished
```

But we have set in config:
```
; Reinitialize all missing Git repositories for which records exist
[cron.reinit_missing_repos]
ENABLED = false
RUN_AT_START = false
NO_SUCCESS_NOTICE = true
SCHEDULE = @every 72h

; Delete all repositories missing their Git files
[cron.delete_missing_repos]
ENABLED = false
RUN_AT_START = false
NO_SUCCESS_NOTICE = true
SCHEDULE = @every 72h
```
and even without this tasks run.

URL: admin/monitor - show that tasks never run and no 'Next Time' = Mon, 01 Jan 0001 00:00:00 +0000.

I am suspect that all tasks that have ```Schedule:   "@every 72h"``` run in any case, even if ```Enabled:    false``` set.

**Comment by rozhuk-im** [comment]
@zeripath Can you look into this?

**Comment by techknowlogick** [comment]
Are you able to update to the latest stable version (1.12.5) as there were fixes in that related to your issue

**Comment by rozhuk-im** [comment]
I do it right now, and will see results at least after 72h.

IMHO you can simple reproduce this: change in ```modules/cron/tasks_extended.go``` all ```@every 72h``` to something like ```@every 1m``` and see what happen and same in ```app.ini```.

**Comment by rozhuk-im** [comment]
Also I see ```Cron: Update Mirrors has finished``` but ```NO_SUCCESS_NOTICE = true``` is set.

**Comment by zeripath** [comment]
In terms of the configuration issue that was solved with #12939 and its backport #12943 - I'm sorry that was there for so long - but it's really helpful if when you find a bug if you could please check the changelog of the newest version or consider upgrading to it.

Regarding Reinit missing repositories, the code is very simple:

* For each repository in the db
* Check if its directory exists
* Reinitialise if not.

Why are your directories disappearing? That's the more important question.

**Comment by rozhuk-im** [comment]
I have seen these changes before open this issue.
I am not sure that these changes fix this issue.

**Comment by zeripath** [comment]
Please upgrade to 1.12.5 as it *will* fix the issue of the execution of non-enabled tasks.

**Comment by rozhuk-im** [comment]
Sorry for noise, looks like it fixed.

I start another bug with cron staff: https://github.com/go-gitea/gitea/issues/13179
