### ISSUE TITLE
Pull Request from URL

### ISSUE THREAD

**Issue by CodeDoctorDE** [go-gitea/gitea#13173]
Please add an option to add pull requests from url. With this option you can create a private gitea instance and people who do not have rights to create repos have an option to contribute!

**Comment by 6543** [comment]
@CodeDoctorDE sorry i do not quit understand what feature you propose :/

Witch gitea version do you use?
Do you mean a repo invite link option?!?

**Comment by CodeDoctorDE** [comment]
It's a feature request. I use the latest gitea version.
I want to have an option to give the users the option to create a pull request with an url (for example github).

**Comment by 6543** [comment]
Smal explanation: code is on gitea, people can "fork" to a repo on github and create a pull from github back to gitea

**Comment by zeripath** [comment]
So I think the apply-patch PR would form an integral part of this - creating a branch from a patch and a PR from that would then work.

**Comment by techknowlogick** [comment]
I'm going to close this as duplicate, as it is what will be achieved with federation (making PRs from other instances).
