### ISSUE TITLE
Cron ignores NO_SUCCESS_NOTICE = true setting

### ISSUE THREAD

**Issue by rozhuk-im** [go-gitea/gitea#13179]
- Gitea version (or commit ref): 1.12.5
- Git version: 2.28.0
- Operating system: FreeBSD 12.2 amd64
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description

I have set all ```NO_SUCCESS_NOTICE = true``` but got in logs:
```
Cron: Reinitialize all missing Git repositories for which records exist has finished
Cron: Delete all repositories missing their Git files has finished
Cron: Delete old repository archives has finished
Cron: Check all repository statistics has finished
Cron: Update migration poster IDs has finished
Cron: Clean-up deleted branches has finished
Cron: Update Mirrors has finished
Cron: Update Mirrors has finished
```

I prefer not see this, and see only errors in log, that requires some actions from me.
It is hard to filter spam from Cron to find important events.

**Comment by zeripath** [comment]
In the logs or in the system notice?

**Comment by rozhuk-im** [comment]
In "System Notices".

**Comment by rozhuk-im** [comment]
https://github.com/go-gitea/gitea/blob/48598a7e835cf9da87ef4d928fbd23fb0c5f5ea6/modules/cron/tasks.go#L101
https://github.com/go-gitea/gitea/blob/48598a7e835cf9da87ef4d928fbd23fb0c5f5ea6/modules/cron/setting.go#L59
But I see no ```sec.Key("NO_SUCCESS_NOTICE").MustBool(true)``` in project, like all other cron tasks variables.

**Comment by zeripath** [comment]
That's because it is not set to true by default.

**Comment by rozhuk-im** [comment]
https://github.com/go-gitea/gitea/blob/48598a7e835cf9da87ef4d928fbd23fb0c5f5ea6/modules/cron/tasks_basic.go#L22
It set in sources, at least for ```Update Mirrors```, and set in config - not help.

**Comment by rozhuk-im** [comment]
https://github.com/go-gitea/gitea/pull/12438 - not complete

**Comment by zeripath** [comment]
No #12438 only changes the update mirrors setting. That was it's purpose as it clearly states in its comment.

The rest of the cron settings are not set to NO_SUCCESS= true by default. 

If you don't want them set them yourself.

**Comment by rozhuk-im** [comment]
Sorry, I miss that last release does not include https://github.com/go-gitea/gitea/pull/12438
