### ISSUE TITLE
Reject newlines in email addresses

### ISSUE THREAD

**Issue by NotAFile** [go-gitea/gitea#13182]
- Gitea version (or commit ref): 1.12.5
- Git version: n/a
- Operating system: Linux
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist: n/a

## Description

When clearing out some spam accounts, I noticed that many of them had email addresses that ended with an "\r\n" character sequence, seemingly as one of several strategies of circumventing email address reuse detection.

Gitea should probably not accept email addresses with newlines in them as valid.

**Comment by 6543** [comment]
I would say: white & blacklist func for email addresses

**Comment by techknowlogick** [comment]
@6543 we currently have that for emails, but the email validity should just know that those characters are invalid

**Comment by zeripath** [comment]
OK if we want to get in to this we will need to read:

https://en.wikipedia.org/wiki/Email_address

https://tools.ietf.org/html/rfc3696

https://tools.ietf.org/html/rfc5321

https://tools.ietf.org/html/rfc5322

**Comment by NotAFile** [comment]
I should note that the format was `localpart@domain\r\n`, which does not make sense and is definitely not valid.

**Comment by chrisshyi** [comment]
I can work on this if nobody's been assigned yet!

**Comment by 6543** [comment]
@chrisshyi go on for it 👍

If you have questions just ask us on discord ...

**Comment by 6543** [comment]
email is now Validated via `models.ValidateEmail()` witch use `mail.ParseAddress()`

-> https://golang.org/pkg/net/mail/#ParseAddress
