### ISSUE TITLE
SQL log flood

### ISSUE THREAD

**Issue by zig** [go-gitea/gitea#13189]
- Gitea version (or commit ref): 1.14.0+dev-18-gd453533be built with GNU Make 4.3, go1.15.3 : bindata, timetzdata, sqlite, sqlite_unlock_notify
- Git version: 2.26.2
- Operating system: gitea official docker
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes
  - [ ] No
  - [X] Not relevant
- Log gist:

## Description

Using the gitea:latest docker image, there is a log appearing every 10 seconds, is there a way to disable it ?

```
oct. 17 17:26:05 xxx-server-1 docker-compose[27711]: server_1  | 2020/10/17 17:26:05 ...m.io/xorm/core/db.go:286:afterProcess() [I] [SQL] SELECT user_id, count(*) AS count FROM notification WHERE user_id IN (SELECT user_id FROM notification WHERE updated_unix >= ? AND updated_unix < ?) AND status = ? GROUP BY user_id [1602948353 1602948363 1] - 1.297709ms
```

**Comment by lunny** [comment]
You cannot disable only this log. When anyone stay on the notification page, it will display.

**Comment by zig** [comment]
@lunny thanks for your answer. Is there a way to disable all SQL logs ?

**Comment by zig** [comment]
OK I think I found in the doc : https://docs.gitea.io/en-us/logging-configuration/#:~:text=It%20is%20enabled%20by%20default,log%20SQL%20events%20by%20default.

Thanks for your attention, I guess I can close this bug :)
