### ISSUE TITLE
UI bug on Explore

### ISSUE THREAD

**Issue by Fastidious** [go-gitea/gitea#1319]
- Gitea version (or commit ref): `N/A`
- Git version: `N/A`
- Operating system: `N/A`
- Database (use `[x]`): `N/A`
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL) `https://try.gitea.io/explore/repos`
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

Icon too close to label.

## Screenshots

![screen shot 2017-03-18 at 13 21 26](https://cloud.githubusercontent.com/assets/8352292/24074435/b0222cd8-0bde-11e7-9111-572ae8fa8402.png)

**Comment by pgaskin** [comment]
The reason is because the icon is wider then the normal width.

**Comment by Fastidious** [comment]
@geek1011 I fail to see your point. Just fix it! 😆

**Comment by lunny** [comment]
any update? maybe change a new icon or it's not mind?

**Comment by lunny** [comment]
This is not a bug but an enhancement.

**Comment by Fastidious** [comment]
@lunny if the icon showed fine, but when the UI was changed, it started showing badly, it is a bug. 

There are many bugs UI (or enhancements, as you call it) that have been introduced by UI changes, and the OpenID implementation.

**Comment by techknowlogick** [comment]
Can this ticket be closed?
