### ISSUE TITLE
Prompt users to create a new PR after pushing to a new branch

### ISSUE THREAD

**Issue by kolaente** [go-gitea/gitea#13196]
As a user, I would like to see a prompt on the home page or repository page to create a new PR if I recently pushed to a new branch for which no PR exists yet so that I save clicking on the "new PR" button on the repo page.

This could be done purely through the db without any git calls since we already have all the data in the `action` table.

I think we can always assume the user has the rights to create a PR if they have the right to push to a new branch in that repo, so no need to check that.
We would just need another check if the repo pushed to is a fork to check with the head repo if a PR exists there and not in the fork repo.

**Comment by lunny** [comment]
This is duplicated with #311

**Comment by kolaente** [comment]
I'm working on this.

**Comment by lunny** [comment]
Let's close #311 .
