### ISSUE TITLE
Remote unpack failed: unpack-objects abnormal exit

### ISSUE THREAD

**Issue by belliash** [go-gitea/gitea#13203]
- Gitea version (or commit ref): 1.12.4
- Git version: 2.28.0
- Operating system: Linux
- Go version: 1.15.3
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
- Log gist:
I have not found any errors in gitea.log.

## Description
After updating Gitea from 1.12.1 to 1.12.4 I am unable to push changes. Everytime I try to do that I got the following error:

Enter passphrase for key '/path/to/.ssh/id_rsa': 
Enumerating objects: 29, done.
Counting objects: 100% (29/29), done.
Delta compression using up to 16 threads
Compressing objects: 100% (14/14), done.
Writing objects: 100% (15/15), 5.13 KiB | 5.13 MiB/s, done.
Total 15 (delta 13), reused 3 (delta 1), pack-reused 0
remote: fatal: not a git repository: '.'
error: remote unpack failed: unpack-objects abnormal exit
To ssh://git.com:9999/group/repo.git
 ! [remote rejected]       master -> master (unpacker error)
error: failed to push some refs to 'ssh://git.com:9999/group/repo.git'

This happens to all repositories hosted at Gitea. I tried to launch git fsck on server side and found no errors. I can clone repository, browse it via webui, etc, just cannot push changes back to remote.
I am pretty sure, you will need some additional data. Please let me know what I can do in order to investigate this.

**Comment by 6543** [comment]
@belliash do you use the build in ssh server?

**Comment by belliash** [comment]
> @belliash do you use the build in ssh server?

Yes, I use ssh server that is built into gitea, listening on custom port.

**Comment by belliash** [comment]
I have just found out that I cannot edit files online via web interface, because I got another error:

```
Failed to update/create file '.clang-format' with error: Clone: exit status 128 - Cloning into bare repository '/path/to/gitea/data/tmp/local-repo/upload.git925909720'...
fatal: unable to access '/path/to/gitea/data/tmp/local-repo/upload.git925909720/config': Permission denied
exit status 128 - Cloning into bare repository '/path/to/gitea/data/tmp/local-repo/upload.git925909720'...
fatal: unable to access '/path/to/gitea/data/tmp/local-repo/upload.git925909720/config': Permission denied
```

I checked permissions and they look ok. I can write under that path as well as git user. On the other hand setting chmod recursively to 777 does not resolve this.

**Comment by belliash** [comment]
The second problem looks somehow similar to #12085 except I got xattr enabled. I wonder if both are connected...

**Comment by jrop** [comment]
I got the same error when I tried to push my dotfiles to the try.gitea.io instance:

```sh
❯ yadm push gitea master
fatal: loose object 85564fc4d34c2a38b9277a6d2fe8f0cf3939acf1 (stored in /Users/me/.config/yadm/repo.git/objects/85/564fc4d34c2a38b9277a6d2fe8f0cf3939acf1) is corrupt
error: remote unpack failed: eof before pack header was fully read
To try.gitea.io:jrop/dotfiles.git
 ! [remote rejected] master -> master (unpacker error)
error: failed to push some refs to 'try.gitea.io:jrop/dotfiles.git'
```

The repo is also hosted here: https://gitlab.com/jrop/dotfiles

**Comment by jolheiser** [comment]
> fatal: loose object 85564fc4d34c2a38b9277a6d2fe8f0cf3939acf1 (stored in /Users/me/.config/yadm/repo.git/objects/85/564fc4d34c2a38b9277a6d2fe8f0cf3939acf1) is corrupt

This leads me to believe it isn't entirely related to Gitea.
I'm unfamiliar with `yadm`, but it looks like your local repo has some tree corruption.

**Comment by jrop** [comment]
@jolheiser yadm is just a git wrapper approximated by:

```
git --git-dir /Users/me/.config/yadm/repo.git/ --work-tree /Users/me
```

...plus a few other niceties that lets you manage dotfiles.  Anyways, that is neither here nor there, but is there a way to have Git "clean" a repo?  I'll search around and see what I can find, but if you know any tricks yourself, please let me know!

**Comment by jrop** [comment]
@jolheiser That was it.  I restored a few files from a clean checkout, and I was able to push to gitea.  Thanks for suggesting.

**Comment by 6543** [comment]
@belliash does your issue still exist on v1.13.2 ?

**Comment by belliash** [comment]
No, I think it's been solved.
