### ISSUE TITLE
Activity shows push, not commit.

### ISSUE THREAD

**Issue by spacehobo** [go-gitea/gitea#13209]
- Gitea version (or commit ref): `b2aa478`
- Git version: `2.28.0`
- Operating system: `android (running in termux)`
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No `(would take days)`
- Log gist: `N/A`

## Description

The "Activity" heat map seems to show commits on the day they were pushed, rather than the day they were committed.  If you start a repo, commit something every day for a week, and push to gitea after seven days, it shows a seven-commit block on the current day instead of a one-commit block across the whole week.

I don't use github when I can help it, so I don't know if this is expected behaviour to github users, but it seems entirely misleading about when the work was actually done, and does not help me in the slightest.

## Screenshots

![A screenshot showing a week's worth of commits compressed down to the one day I pushed them to gitea.](https://user-images.githubusercontent.com/8015250/96415318-50c26700-11e6-11eb-929d-7b032e922753.png)

**Comment by lafriks** [comment]
That's because they are calculated from database not git data and database does not contain such data about commit time. Calculating such data from git would take too much time

**Comment by techknowlogick** [comment]
Closing per @lafriks comment. If you are inclined to have it for before your import you could parse git dat and insert items into the DB that way.
