### ISSUE TITLE
Add Fallback for Pulls Diff when missing commits

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#13216]
if a pull was **merged** and the pull head branch ref got missing or point to commits who are missimg, use the merged-sha as fallback to generate the diff view

To Test:
1. create repo A
2. frok repo A to repo B
3. backup bare repo A
4. create feature branch on B and add some commits
5. create pull from B to A & squash-merge
6. clone A to local disk
7. restore backup of A
8. push local clone back to gitea

what I expect -> cliking on Files-Changed will show the diff based on merged-commit as **fallback**

**Comment by 6543** [comment]
reopen as per comment on #13218

**Comment by techknowlogick** [comment]
closed per linked PR
