### ISSUE TITLE
Add visibility at the team or org level

### ISSUE THREAD

**Issue by PE1NUT** [go-gitea/gitea#13210]
- Gitea version (or commit ref): 1.12.3
## Description

Repositories are either owned by a user, or by an organization. And they can either be private (to their owner), or completely public.

I'd like to propose another level of visibility: Private, but visible to an organization, or the members of a team.

Use case: We would like to use gitea both as an internal repository, and public repository of our software. For an internal repository, it is very useful that other users can see which repositories exist. But at the moment this can only be achieved by either making a repository public to everyone in the world, or transferring ownership of the repository to the organization. The first option is not desirable for internal projects, and using the second option, we lose the information about the maintainer of the project.

Adding an option 'visible to these teams' or 'visible to members of this organization' would make Gitea more useful when self-hosting it. Additionally, to make this automated, one could add a configuration to the team or organization, that new repositories created by members of this team will automatically inherit the default value for this option.

An alternative implementation could be to allow adding a team as a read-only collaborator to a repository.

**Comment by lafriks** [comment]
Gitea 1.12 already has such visibility level called Internal

**Comment by PE1NUT** [comment]
Thanks for the quick reply. Despite studying the documentation and the cheat sheet, I've been unable to find how to use or enable this?

**Comment by 6543** [comment]
@PE1NUT repos **owned by** users: can be either public or private

repos **owned by** orgs: can be public, limited, private (they are limited if the org visible mode is limited and repo is public)

limited = only logged in users are able to see

if you like to have it internal ... I think you mean: all members of a org can see it nobody else will see it, and only a specific team can modify/push to it?
:point_up: in this case you have to set the org-visible mode to private and create a team who contain all users who are part of the org ... this team permissions is set to read access only
and new teams are created for specific repos witch have more rights ... <- team permissions are either org wide or must be enabled to each repo indifidualy

**Comment by 6543** [comment]
this is sure not the easyest configuration ... but it can cover a lot of edge/use-cases :)

**Comment by PE1NUT** [comment]
Thanks for your description, 6543. I understand that the current model is as you describe. But  my proposal is to add the following:
The ability to make a repo visible only to logged in users, and/or logged in users of a particular team. In that way, repositories can remain with their current owners, and we can still share our work internally.

**Comment by 6543** [comment]
users cant have teams at the moment, for org-repos this is already posbile

so you propose: add team function to normal users **and** same visible modes for normal repos as you can have for org-repos ...
