### ISSUE TITLE
Migrate From Gitea not working for me

### ISSUE THREAD

**Issue by airdogvan** [go-gitea/gitea#13227]
Already have a working Gitea site.  Trying to mirror some repositories to new instance via Migrate.

Both source and destination: (different machines and urls)
Git version 1.14.0+dev-33 running on docker (Ubuntu)

Steps:
- New migration
- Gitea
- https url of existing repo
- Access token (generated on source instance (setting, generate token)

Click on Migrate Repository
New screen comes with animated cup of tea.
**Migration failed.**
![image](https://user-images.githubusercontent.com/31630759/96649622-5b642580-12e6-11eb-8b31-6143751e184c.png)

**Comment by techknowlogick** [comment]
Are you able to provide relevant logs?

**Comment by airdogvan** [comment]
2020/10/20 17:05:17 Completed GET /user/events 200 OK in 24.188209361s
2020/10/20 17:05:17 Started POST /repo/migrate for 172.21.0.1
2020/10/20 17:05:17 Completed POST /repo/migrate 302 Found in 125.179689ms
2020/10/20 17:05:17 Started GET /user/samba for 172.21.0.1
2020/10/20 17:05:17 Completed GET /user/samba 200 OK in 8.662384ms
2020/10/20 17:05:18 Started GET /user/avatar/userx/-1 for 172.21.0.1
2020/10/20 17:05:18 Completed GET /user/avatar/userx/-1 302 Found in 3.69346ms
2020/10/20 17:05:18 Started GET /user/samba/status?_csrf=df8zVeNob7xHGSM4sHyZTtNHxpI6MTYwMzIzODYzMjg5NjkyMTQ4Ng for 172.21.0.1
2020/10/20 17:05:18 Completed GET /user/samba/status?_csrf=df8zVeNob7xHGSM4sHyZTtNHxpI6MTYwMzIzODYzMjg5NjkyMTQ4Ng 200 OK in 12.861725ms
2020/10/20 17:05:18 Started GET /manifest.json for 172.21.0.1
2020/10/20 17:05:18 Completed GET /manifest.json 200 OK in 1.64126ms
2020/10/20 17:05:18 Started GET /user/events for 172.21.0.1
2020/10/20 17:05:19 modules/task/task.go:51:handle() [E] Run task failed: 404 Not Found
2020/10/20 17:05:19 Started GET /serviceworker.js for 172.21.0.1
2020/10/20 17:05:19 ...les/public/public.go:156:handle() [I] [Macaron] [Static] Serving /serviceworker.js
2020/10/20 17:05:19 Completed GET /serviceworker.js 304 Not Modified in 181.654µs
2020/10/20 17:05:20 Started GET /user/samba/status?_csrf=df8zVeNob7xHGSM4sHyZTtNHxpI6MTYwMzIzODYzMjg5NjkyMTQ4Ng for 172.21.0.1
2020/10/20 17:05:20 Completed GET /user/samba/status?_csrf=df8zVeNob7xHGSM4sHyZTtNHxpI6MTYwMzIzODYzMjg5NjkyMTQ4Ng 404 **Not Found** in 6.652601ms

I did provide the correct repo url (double checked both in browser and from cli with git clone.

**Comment by techknowlogick** [comment]
These are the web requests, but we need to see what is going on with Gitea itself. Here is a guide on how to enable that information via logging: https://docs.gitea.io/en-us/logging-configuration/#debugging-problems

**Comment by 6543** [comment]
@airdogvan in general if a migration has a problem ... you should find the reason in **System Notices** (lhttp://localhost:3000/admin/notices)

**Comment by airdogvan** [comment]
give me a moment, as said running docker here, what I posted was the result of docker logs.  When I go inside the container, nothing in the log direcoty

**Comment by airdogvan** [comment]
ok not crazy to share my info like this but here goes:
https://git.airdog.site/fossilfranv/freshrss.git
this one is public

**Comment by airdogvan** [comment]
no notifs to clear

**Comment by airdogvan** [comment]
and according to docs, if logs not started in running system, have to restart to get logs...

**Comment by airdogvan** [comment]
if you got the info to my site, can I delete that post?

**Comment by techknowlogick** [comment]
> and according to docs, if logs not started in running system, have to restart to get logs...

correct. any config change to app.ini requires a restart of the binary (slight note: there are CLI commands that don't make this 100% accurate)

**Comment by 6543** [comment]
@airdogvan I can confirm this bug and it do not log an error at all, witch should not be the case

**Comment by airdogvan** [comment]
only notices in /admin/notices are about cron

**Comment by techknowlogick** [comment]
@airdogvan your instance is running a development version from august, are you able to update to the latest RC for 1.13?

**Comment by airdogvan** [comment]
as said this is docker, just pulled the most recent image 2 hours ago

**Comment by 6543** [comment]
@techknowlogick do we have an issue on the docker side too?

**Comment by airdogvan** [comment]
you don't need my site anymore right, made the repo private again... if that's ok

**Comment by 6543** [comment]
note: pure git migration works, gitea without options don't!

**Comment by techknowlogick** [comment]
If you go to `/api/v1/version` it says `1.13.0+dev-404-g4e1c7cc4e` is the version which is a commit from august 12. Is there any caching with your docker images? try.gitea.io checks every 5 minutes for a new image and updates it. and the latest image is reporting `1.14.0+dev-36-gb9850375f ` as the version.

**Comment by 6543** [comment]
@airdogvan I'd like to test against this if I'm allowed to - you can make it private and add me as colaborator with read access :)

**Comment by airdogvan** [comment]
who do I add 6543?

**Comment by 6543** [comment]
@airdogvan https://git.airdog.site/fossilfranv/freshrss/settings/collaboration

**Comment by airdogvan** [comment]
yes I know but I need to know who to add...
you can send details at airdogvan@mailinator.com

**Comment by 6543** [comment]
@airdogvan created an account -> https://git.airdog.site/6543

**Comment by airdogvan** [comment]
or do I just add 6543?

**Comment by airdogvan** [comment]
done

**Comment by 6543** [comment]
I'll try to find the issue :)

**Comment by airdogvan** [comment]
would be grateful if you removed public references to my site...

**Comment by airdogvan** [comment]
thanks

**Comment by airdogvan** [comment]
ok I'll leave you to it.  Let me know if I can do something to help.

And thanks so much for the prompt reaction...

**Comment by 6543** [comment]
gitea version: `1.13.0+dev-404-g4e1c7cc4e` as source - who fail to migrate

**Comment by 6543** [comment]
found two issues ...

**Comment by 6543** [comment]
...  #13229 <- if you are in the middle of nowere checking version makes no sence ...
...  #13230 <- error is not getting loged

**Comment by airdogvan** [comment]
going to have to wait till a new docker image is online, just pulled a minute ago and same version as yesterday...
