### ISSUE TITLE
arc-green theme code display bug

### ISSUE THREAD

**Issue by wolfpackmars2** [go-gitea/gitea#13228]
- Gitea version (or commit ref): 1.12.5
- Git version: 2.25.1
- Operating system: Ubuntu 20
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X ] No - appears to have been fixed in newer base.less style sheet
![gitea_arc_green_Code_display](https://user-images.githubusercontent.com/1011130/96657331-87dc6980-1307-11eb-8c25-f74060a98167.jpg)

## Description

The code lines don't line up with the line numbers when using Chrome and the Arc-Green theme. I've traced the problem down to Chrome's built in style-sheet using "vertical-align: inherit;" as default for the <td> tag. Adding the following css to the arc-green theme would resolve the issue.

`.lines-code{vertical-align: top}`

## Screenshots

screen shot included

**Comment by techknowlogick** [comment]
@wolfpackmars2 does this also happen for standard (non arc-green) theme?

**Comment by wolfpackmars2** [comment]
no, only arc-green. Doesn't seem to happen on the test server running 1.14 dev - maybe fixed in a newer version?

**Comment by wolfpackmars2** [comment]
I confirmed this is fixed in 1.13.0-rc1

**Comment by techknowlogick** [comment]
@wolfpackmars2 awesome! thanks for checking :)
