### ISSUE TITLE
[Feature Request] Is there a way to support Code navigation like github does for C# now?

### ISSUE THREAD

**Issue by DefinitelyADev** [go-gitea/gitea#13223]
More info [here](https://github.blog/changelog/2020-10-19-code-navigation-for-c-repositories/)

**Comment by 6543** [comment]
the best way to aceave it would be to implement [sourcegraph](https://about.sourcegraph.com/) intergration

-> #5010
-> https://github.com/sourcegraph/sourcegraph/issues/343

**Comment by techknowlogick** [comment]
Thanks for ticket. Closing as sourcegraph would be best way to accomplish this.

**Comment by lunny** [comment]
But I think we could also add some simple function/defination jump feature. This could be based on language server protocol directly.  Currently, we have to wait for a sourcegraph webbrowser extenstion to do that.
