### ISSUE TITLE
[Question] Auto-installation of gitea

### ISSUE THREAD

**Issue by erikh** [go-gitea/gitea#13231]
Hi. Me again. ;) I hope these are ok questions to ask, and this is an appropriate forum for them.

I'm looking to automate the installation of gitea for build/test and CI/CD integrations (for ... a CI I'm building that runs against gitea). What I'd basically like to do is POST to the /install endpoint and have it DWIM, but that seems dodgy. I didn't see anything in the API that fit the bill, so I thought I'd ask here. Is there a tool for this? How hard would it be to add one?

Thanks!

**Comment by jolheiser** [comment]
Would you mind asking in our [Discord](https://discord.gg/Gitea) or [Discourse Forum](https://discourse.gitea.io)?
That might be a better spot for ongoing discussion.

**Comment by jolheiser** [comment]
Closing since you landed in the Discord. 🙂
