### ISSUE TITLE
Keep email private unchecked, but email not shown in profile

### ISSUE THREAD

**Issue by strk** [go-gitea/gitea#1323]
1. Please speak English, this is the language all of us can speak and write.
2. Please ask questions or configuration/deploy problems on our Gitter channel: https://gitter.im/go-gitea/gitea
3. Please take a moment to search check that your issue doesn't already exist.
4. Please give all relevant information below for bug reports, because incomplete details will be handled as an invalid report.

**You MUST delete the content above including this line before posting, otherwise your issue will be invalid.**

- Gitea version (or commit ref): 1.1.0+47-g1c3bd436
- Can you reproduce the bug at https://try.gitea.io:
  - [ x] Yes: https://try.gitea.io/strk

## Description

Despitie the "Keep email private" checkbox being NOT checked in user settings (under "Profile" tab),
both the profile page and the explore/user page still doesn't show my email 
...

## Screenshots

![profile-settings](https://cloud.githubusercontent.com/assets/289678/24078961/7caa24e8-0c7c-11e7-824c-1e5b4a04fb1b.png)

![profile](https://cloud.githubusercontent.com/assets/289678/24078966/802669f6-0c7c-11e7-8d4e-8b3010f7621b.png)

**Comment by lunny** [comment]
Because there is a global config on app.ini to do that. I remember.

**Comment by strk** [comment]
SHOW_USER_EMAIL

So do you confirm that's set to false in the custom/conf/app.ini
of try.gitea.io ? Becasue the default would be true...

**Comment by strk** [comment]
Locally I do indeed see my email in profile, so must be global configuration. @tboerger do you confirm SHOW_USER_EMAIL is false in custom config on try.gitea.io ?

**Comment by lunny** [comment]
This is another thing. If global SHOW_USER_EMAIL is false, then user will not allowed to change their email's visibility.

**Comment by bkcsoft** [comment]
@strk I can confirm that `SHOW_USER_EMAIL` does not exist in `app.ini` on `try.gitea.io`. Hence it should be set to the default (`true`).

**Comment by lunny** [comment]
@strk what do you think?
