### ISSUE TITLE
Definite comment

### ISSUE THREAD

**Issue by melmus** [go-gitea/gitea#13236]
- Gitea version (or commit ref):
1.14.0+dev-18-gd453533be
- Git version:
2.26.2
- Operating system:
Ubuntu 18.04.4 LTS
- Database (use `[x]`):
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X] No
- Log gist:

## Description

When I open page https://gitea/devops/repo1/pulls/123#issuecomment-5766, I want to see definite comment, but It direct me to the top of the page.

**Comment by zeripath** [comment]
This appears to work on try:

https://try.gitea.io/arandomer/pathological/issues/2#issuecomment-30678

**Comment by denyskon** [comment]
Closing as stale and not able to reproduce.
