### ISSUE TITLE
LANDING_PAGE ignores default theme

### ISSUE THREAD

**Issue by JustasStankunas** [go-gitea/gitea#13238]
- Gitea version (or commit ref): 1.12.5
- Git version:
- Operating system: Docker
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
- Log gist:

## Description
when setting `DEFAULT_THEME = arc-green` & `LANDING_PAGE = login` - landing page (login page) will open with white theme ignoring `DEFAULT_THEME` parameter. when logged in, user preferences applies. 
if `LANDING_PAGE` is not specified, `DEFAULT_THEME` parameter works fine.

**Comment by delvh** [comment]
Does this issue still occur?
If yes, feel free to reopen this issue.
