### ISSUE TITLE
Migrations: Error on download factory creation is not loged

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#13230]
if an error ocure here: 
https://github.com/go-gitea/gitea/blob/965861043ae4daf7ae50460edf5533e52980bdb1/modules/migrations/migrate.go#L41-L42

there is no report in logs nor in "System Notices"!

**Comment by 6543** [comment]
I think this should be Info level and Debug with more details
https://github.com/go-gitea/gitea/blob/327f18c3b28225dcfcaa0409b880136f7e1d1bf6/modules/task/migrate.go#L99

**Comment by zeripath** [comment]
This should be fixed by #13246
