### ISSUE TITLE
GitHub migration: Show "API rate limit of 5000 still exceeded" to user

### ISSUE THREAD

**Issue by davidak** [go-gitea/gitea#13242]
- Gitea version (or commit ref): 1.13.0+rc1
- Git version: 2.20.1
- Operating system: debian stable 10.6
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] i get migration failed too, but can't look into your logs ;)

## Description

When i try to migrate a big GitHub repo, i see that the API limit is reached in the logs, but as an end-user, i see just "migration failed" without reason.

Please show it also to the user and what they can do.

> API rate limit of 5000 still exceeded until 2020-10-21 16:33:28 +0200 CEST

Just wait and try again.

Related to https://github.com/go-gitea/gitea/issues/13241

## Log

`modules/task/task.go:51:handle() [E] Run task failed: GET https://api.github.com/repos/NixOS/nixpkgs: 403 API rate limit of 5000 still exceeded until 2020-10-21 16:33:28 +0200 CEST, not making remote request. [rate reset in 34m49s]`

## Screenshots

![Screenshot from 2020-10-21 17-31-45](https://user-images.githubusercontent.com/91113/96746039-119f3c00-13c7-11eb-9af4-b17d613d233d.png)

**Comment by zeripath** [comment]
A repository notice is always created if there is a failure.

https://github.com/go-gitea/gitea/blob/f0fe5683feb2799e3ca467bc75fd77871b65452b/modules/migrations/migrate.go#L71

That is of course slightly opaque.

**Comment by zeripath** [comment]
Ah, but the error should be being set on the task... 

https://github.com/go-gitea/gitea/blob/f0fe5683feb2799e3ca467bc75fd77871b65452b/modules/task/migrate.go#L57

**Comment by Codeberg-org** [comment]
> Just wait and try again.

For big repos retry will fail too -- something like sleep+resume migration might work?

**Comment by zeripath** [comment]
let's deal with one problem at a time
