### ISSUE TITLE
Issues page seem to list projects with wrong numbers

### ISSUE THREAD

**Issue by milanaleksic** [go-gitea/gitea#1325]
- Gitea version (or commit ref): 1.1.0
- Git version: 2.1.5
- Operating system: Linux (Debian)
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (https://try.gitea.io/issues, as user milanaleksic)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

I have 2 repositories with 19 issues in total (10 in repo1, 9 in repo2). Page "https://try.gitea.io/issues" lists that indeed 9 issues are present in repo2 and 10 in repo1. It says that since the page lists issues that belong to repo2 and repo1 (all 9 from repo2 and 1 from repo1).

If I now add another issue to repo2, it will "kick out" issue listed from repo1, listing only issues from repo2. The total count will say 20 issues, but the list per project (left side of the screen) will list **only repo2**. I believe this is bug, since by adding 1 issue all of a sudden entire project is missing from the list of subprojects. I use issues a lot to organize my work and this is counter-productive since I have to fallback to my own SQLs against the database.

### Case 1

when I have only 9 issues from repo2+1 issue from repo1 listed, both repo1 and repo2 are listed on the left side:
![when I have only 9 issues from repo2+1 issue from repo1 listed](https://cloud.githubusercontent.com/assets/50055/24079650/da94efa6-0c8c-11e7-9b89-842df3bff526.png)

### Case 2

when I have 10 issues from repo2, only repo2 is listed on the left side:
![when I have 10 issues from repo2](https://cloud.githubusercontent.com/assets/50055/24079649/da9265ec-0c8c-11e7-8cd8-70c78586a71e.png)

**Comment by gerricom** [comment]
I can reproduce that. The counters on the left side are corresponding to that, what is showed at the current page. If there is just one repo visible, there will only be this repo visible on the left side. If I paginate to the next page, this changes. I believe, the repo-overview on the left side is filtered false.
