### ISSUE TITLE
API for getting PullRequest/Issue timeline data.

### ISSUE THREAD

**Issue by chriseaton** [go-gitea/gitea#13250]
- Gitea version (or commit ref): 1.12.5
- Git version: 
- Operating system: CentOS 8.1, via systemd, binary release.
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io: N/A

## Description
Proposed API route: GET `​/repos​/{owner}​/{repo}​/issues​/{index}/timeline`

Currently, there is no way to get a timeline of issue events (differing comment types in the database) via the API. I am proposing a new API route on repo issues that gets the same data as-is displayed on the GUI below the issue description (see screenshot), similar to the content rendered by the [comments template (`comments.tmpl`)](https://github.com/go-gitea/gitea/blob/master/templates/repo/issue/view_content/comments.tmpl).

The returned result could be an array of objects with the essential information from the timeline object.     
For example:    
```js
[
    {
        "id": "2",
        "type": "7",
        "original_author": "NULL",
        "original_author_id": "0",
        "issue_id": "2",
        "label_id": "20",
        "old_milestone_id": "0",
        "milestone_id": "0",
        "assignee_id": "0",
        "removed_assignee": "False",
        "old_title": "NULL",
        "new_title": "NULL",
        "old_ref": "NULL",
        "new_ref": "NULL",
        "dependent_issue_id": "0",
        "date_created": "",
        "date_updated": ""
    },
  // ...
]
```

## Screenshots
![image](https://user-images.githubusercontent.com/5247568/96787669-fcb2b080-13a6-11eb-864e-4bda99f8451d.png)

**Comment by zeripath** [comment]
Seems reasonable to me but is there a github API we could implement instead?

**Comment by chriseaton** [comment]
[This might be related from GitHub/API](https://developer.github.com/v3/issues/timeline/)
