### ISSUE TITLE
[question] PAM support in pre-build binary?

### ISSUE THREAD

**Issue by rmbleeker** [go-gitea/gitea#13257]
- Gitea version (or commit ref): 1.12.5
- Git version: 2.18.4
- Operating system: RHEL 7.8
- Database:
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite

## Description

As per issue #865, I'm guessing PAM authentication is still not supported in the downloadable binaries? I'm getting the same error at least:
```
routers/user/auth.go:194:SignInPost() [E] UserSignIn: PAM not supported
```
If so, I'm curious why PAM authentication can be configured from the Authentication Sources section. This led me to believe it was now available.

**Comment by zeripath** [comment]
Unfortunately because of the way this code has been built there is no self-registering of authentication modules. It's a flaw.

**Comment by rmbleeker** [comment]
Thanks, I guess that at least answers my question. I guess I'll have to get LDAP working then.
