### ISSUE TITLE
How to migrate gitea？

### ISSUE THREAD

**Issue by linsu2223** [go-gitea/gitea#13252]
I want to migrate gitea from one server to another. I want to keep the original data. What should I do? Is there any good way, I hope to communicate together, thank you!

**Comment by lunny** [comment]
Copy the data directory and all the databases.

**Comment by 6543** [comment]
@linsu2223 in short: save&restore data, app.ini, database

in long: we need more info how your setup looks like do the old and new system have same database-management, OS, ...?
