### ISSUE TITLE
Incorrect "merged by" value in pull requests list

### ISSUE THREAD

**Issue by lakostin** [go-gitea/gitea#13260]
- Gitea version (or commit ref):
1.14.0+dev-18-gd453533be
- Git version:
2.26.2
- Operating system:
docker Alpine Linux
- Database (use `[x]`):
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
- Log gist:

## Screenshots

![Screenshot from 2020-10-21 18-17-42](https://user-images.githubusercontent.com/29179059/96848546-3cd46a80-145d-11eb-8a7f-69c786532a86.png)
![Screenshot from 2020-10-21 18-17-55](https://user-images.githubusercontent.com/29179059/96848548-3d6d0100-145d-11eb-8763-2b58fc9d2a32.png)

**Comment by zeripath** [comment]
One is likely to be the person who opened the PR and one is the person who merged the PR.

**Comment by lakostin** [comment]
the problem is that it's written "merged by %person who opened pull request%"
but actually other person merged it

**Comment by zeripath** [comment]
So it's not an incorrect value but rather that the label is unclear. The pulls list has to have the pr author on it - the person who merged it is irrelevant.

The string should be changed to be:

by andrei.kirin merged 11 minutes ago

**Comment by lakostin** [comment]
i would use this variant which is much more clear in my opinion:
opened by andrey.kirin; merged 11 minutes ago by anton.kostin
