### ISSUE TITLE
Issue/PR labels arc-green contrast issue introduced by #13181

### ISSUE THREAD

**Issue by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [go-gitea/gitea#13263]
- Gitea version (or commit ref): `Gitea version 1.14.0+dev-56-ge964c6ec1 built with GNU Make 4.3, go1.15.3 : bindata, sqlite, sqlite_unlock_notify`
- Git version: `git version 2.29.0.311.g38ddec7408`
- Operating system: Arch Linux
- Built from source:
  - [x] Yes
- Run with:
  - [x] systemd
- Database:
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] No

## Description
I just recently noticed there has been a change to how labels are displayed in Issue/PR feeds when using `arc-green` theme.
Colourful labels are gone due to an addition from #13181 , precisely - [file `theme-arc-green.less`, line 622](https://github.com/go-gitea/gitea/pull/13181/files#diff-b6a7d7461f3f50080599d288d49112f39678fec7ce75603a3b9bc1511be2a87bR622).
This overrides the labels original colours and everything now looks grim.
While I understand the line was added for a reason, this most certainly was not it.

## Screenshots
now - grim:
![image](https://user-images.githubusercontent.com/61180606/96875579-a5304580-1477-11eb-9cc5-41a11841864f.png)
![image](https://user-images.githubusercontent.com/61180606/96875628-b7aa7f00-1477-11eb-89f4-0c2f713fb2a8.png)
![image](https://user-images.githubusercontent.com/61180606/96875897-0ce69080-1478-11eb-8946-0101608e55c5.png)

before - colourful:
![image](https://user-images.githubusercontent.com/61180606/96875688-cc871280-1477-11eb-8b8c-460e69d1b17d.png)
![image](https://user-images.githubusercontent.com/61180606/96875718-dad52e80-1477-11eb-93f6-17dfa18c35f2.png)
![image](https://user-images.githubusercontent.com/61180606/96875802-f3dddf80-1477-11eb-9fd4-f75b95ad0f48.png)

**Comment by 6543** [comment]
ping @ivanvc

**Comment by zeripath** [comment]
And now we see why `!important` is a bad idea...

**Comment by ivanvc** [comment]
Darn, I had to add `!important` as another style was overriding the color for the labels I added. I can take this issue :D
