### ISSUE TITLE
Unicode Fullname 500

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#13261]
- Gitea version (or commit ref): 1.12.5
- Git version:    2.24.3
- Operating system: Ubuntu - Docker image
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Seems down? "Bad Gateway"
- Log gist:
>2020/10/22 11:15:13 ...r/setting/profile.go:105:ProfilePost() [E] UpdateUser: Error 1366: Incorrect string value: '\xF0\x9D\x96\x91\xF0\x9D...' for column 'full_name' at row 1

## Description
Go to own profile, set "Full Name" to some Unicode Chars like `𝖑𝖚𝖑` and hit save.

500 internal server error

## Priority

not important. Even not allowing Unicode at all would be fine ;)

**Comment by zeripath** [comment]
This is yet another yet another MySQL utf8 - utf8mb4 issue.

You need to migrate your db, the tables and the columns to utf8mb4. You should ensure that `CHARSET=utf8mb4` in the `[database]` section of the app.ini.

**Comment by peterscheu-aceart** [comment]
See FAQ here: https://docs.gitea.io/en-us/faq/#why-are-emoji-broken-on-mysql 
Works just fine!

Can be closed.
