### ISSUE TITLE
Gitea --port rewrites app.ini on it's own, breaks SSH access, API not working & no error logged.

### ISSUE THREAD

**Issue by gsantner** [go-gitea/gitea#13277]
- Gitea version (or commit ref): g26d6c1530
- Git version: 2.17.1
- Operating system: Ubuntu 18.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite

## Description
I have updated to [latest nightly build](https://dl.gitea.io/gitea/master) today and since that I cannot pull over SSH anymore suddenly. Has been working for years however.

I removed all old logs and checked log dir, appareantly NO relevant error is logged at all. Not even a authentication attempt, seemingly that point is not reached in code. Also not shows any error in shell. I tried like 5 times to pull in the meantime log-tail is running, the only thing that comes up is about notifications cron.

The git pull says:
```
parse "://:9003/api/internal/serv/command/3/ORGNAME/REPONAME?mode=1&verb=git-upload-pack": missing protocol scheme
```
So gitea somehow tries to connect to http interface, even though I cleary pull over SSH, wut? The port for http listener is 9003.  

Screenshot attached.
Build with issue is:  
```
Powered by Gitea Version: 1.14.0+dev-63-g26d6c1530
gitea-master-linux-amd64  10/22/2020 08:47:08 PM +00:00
```

My old version, nightly build from 19. October has been (no issue / bug not present there):
```
./gitea-2020-10-19 --version
Gitea version 1.14.0+dev-25-g9fe4b7b69
```

## Screenshots
![Screenshot_20201023-055106](https://user-images.githubusercontent.com/6735650/96954852-96d43f00-14f4-11eb-9936-c6be6e8bd9aa.png)

**Comment by gsantner** [comment]
The issue is that gitea now does !!write!! the app.ini config when restarting gitea.

I saw 

![grafik](https://user-images.githubusercontent.com/6735650/97057670-09442e00-158c-11eb-93c0-827edb0b5261.png)

Wrote the [default config](https://github.com/go-gitea/gitea/blob/master/custom/conf/app.example.ini#L280) value again (checked diff, it was there also before updating gitea)

![grafik](https://user-images.githubusercontent.com/6735650/97057766-43adcb00-158c-11eb-8be3-b9c7cc4ed5bc.png)


Pressed save, then restart gitea with systemctl:

![grafik](https://user-images.githubusercontent.com/6735650/97057686-1234ff80-158c-11eb-88d6-57c7855cbe0d.png)

Suddenly vim says file has changed since last write...and wonder..the :9003 value is there again (why gitea rewrites the config file and saves it to disk??)

![grafik](https://user-images.githubusercontent.com/6735650/97057843-7eaffe80-158c-11eb-9862-35bc9621b1d3.png)


systemctl file, pretty standard, always used it in this way:
![grafik](https://user-images.githubusercontent.com/6735650/97057892-9e472700-158c-11eb-8aba-f608d53676b7.png)

**Comment by gsantner** [comment]
When I comment the setting completely I get:

![Screenshot_20201024-001239](https://user-images.githubusercontent.com/6735650/97058327-c84d1900-158d-11eb-9bbb-dab80f4a207c.png)

No errors logged to gitea log files.

**Comment by gsantner** [comment]
Also broken on master release amd64 from `10/23/2020 06:53:55 PM +00:00`.

**Comment by zeripath** [comment]
Ok so this must be related to my recent pr on the install page. I'm not sure how this was ever working for you though because this code should not have significantly changed things

**Comment by zeripath** [comment]
Oh crap.

**Comment by zeripath** [comment]
https://github.com/go-gitea/gitea/blob/f40a2a4404e3eabf5e28ae43e1f395bb13176307/cmd/web.go#L119-L124

Needs to be after https://github.com/go-gitea/gitea/blob/f40a2a4404e3eabf5e28ae43e1f395bb13176307/cmd/web.go#L126-L127

**Comment by zeripath** [comment]
I think this option is somewhat broken to be honest.

The command line documentation states that it should be temporary - however, the previous code (and current code) writes this value to the configuration - so it's not temporary!

The reasoning of course is that gitea serv, gitea hook, gitea admin, gitea manager, etc. all have to communicate with the gitea process over its internal port and if this value is not saved then there will be an issue.

If we therefore want this --port to be temporary as it states we will need to add this --port option to all of those commands too...

but the question comes when gitea web writes its authorized_keys and hooks files - should it also write the --port ? It's supposed to be temporary so really it shouldn't be making permanent changes like that - but then unless you run with --port = PORT in the conf file then its all going to be broken.

I can see a point for the install-page to have an option to override the port settings and I've added an --install-port option for that but the question remains whether this value should be written to the file or not...

**Comment by gsantner** [comment]
To be honest, I don't care whether or not something is written/cached. It's only a problem when gitea makes wrong configuration based upon the parameters, while it would be correct from config file as is.

I would recommend for future work: Not touch the config file at all! It's there for service configuration, not state management or caching. On some devices the file might even be marked as read-only so you can't overwrite it simply.  
Instead if really required to read/save some file, why not read config file, make changes in memory, and save the file to some cache/tmp folder?

**Comment by lunny** [comment]
But the installation will have to create/update the configuration file at once.

**Comment by gsantner** [comment]
Agreeing, but thats at setup/installation, where it also written once at other projects
