### ISSUE TITLE
[Feature request] Use cdn to load large static resource file.

### ISSUE THREAD

**Issue by Basstorm** [go-gitea/gitea#13278]
- Gitea version (or commit ref): latest
- Git version: latest
- Operating system: OS X
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
## Description
 I am using the official docker image running in a 4 cores ARMv8l cpu, 2GB ram device. Since I don't have a public IP, I use NPS for intranet penetration. But my server bandwidth is only 1mbps because it is a tiny server for study. I found that the first time the page loads, it loads a huge ttf file called NotoColorEmoji.ttf. This takes a lot of time to load, and when the font file is loaded, everything goes very smoothly. So I'm wondering if it's possible to use cdn for such a large static resource file?

## Screenshots

![image](https://user-images.githubusercontent.com/37471354/96983432-b5692300-1552-11eb-8682-6e1cefe9fa1e.png)

**Comment by lunny** [comment]
You can do that, just set `STATIC_URL_PREFIX` on `[server]`.

**Comment by Basstorm** [comment]
Thanks for reply! But I got this: Package size exceeded the configured limit of 50 MB. Try https://github.com/go-gitea/gitea/tree/v1.12.5/public/css/index.css instead. 
My app.ini: STATIC_URL_PREFIX = https://cdn.jsdelivr.net/gh/go-gitea/gitea@v1.12.5/public

**Comment by lunny** [comment]
That error returned from jsdelivr.net I think you have to let them know or you can upload the static files to another CDN service.

**Comment by Basstorm** [comment]
Static resource like css is not pre-placed in the source code but it is compiled by *.less. I found that ttf file is requested by index.css, and the codes which send the request are come from `_base.less`.  However, there is only a binary file after compile..

_base.less
```css
@font-face {
  font-family: "Noto Color Emoji";
  src:
    local("Noto Color Emoji"),
    local("Noto-Color-Emoji"),
    url("../fonts/noto-color-emoji/NotoColorEmoji.ttf") format("truetype");
}
```
So is there a easy way or futher updates about CDN?
Thanks for your reply again!

**Comment by lunny** [comment]
Except we upload the static resources to a public CDN, I think you have to set up a CDN yourself.

**Comment by Basstorm** [comment]
> Except we upload the static resources to a public CDN, I think you have to set up a CDN yourself.

I decide to build docker image myself. Thanks!
