### ISSUE TITLE
Error at start with latest version

### ISSUE THREAD

**Issue by DeltaEvo** [go-gitea/gitea#1327]
- Gitea version (or commit ref): 8bcb643a031e4739ca8ead8351ef7f9092969299
- Git version: 2.12.0
- Operating system: archlinux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log:
```
2017/03/19 15:55:17 [I] Log Mode: File(Trace)
2017/03/19 15:55:17 [I] XORM Log Mode: File(Trace)
2017/03/19 15:55:17 [I] Cache Service Enabled
2017/03/19 15:55:17 [I] Session Service Enabled
2017/03/19 15:55:17 [I] Mail Service Enabled
2017/03/19 15:55:17 [I] Notify Mail Service Enabled
2017/03/19 15:55:17 [...itea/routers/init.go:54 GlobalInit()] [E] Failed to initialize ORM engine: sync database struct error: Error 1170: BLOB/TEXT column 'key_id' used in key specification without a key length
```
## Description
Gitea with latest version built from git fail to start with an error (exit code: -1)

**Comment by shyim** [comment]
I guess its fixed with https://github.com/go-gitea/gitea/pull/1303 i have the same error

**Comment by lunny** [comment]
see #1283
