### ISSUE TITLE
Migration: migrating migrated repo fail

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#13271]
while try to migrate from gitea ( 1.14.0+dev-63-g26d6c1530) to gitea (1.14.0+dev-44-gf0fe5683f) a db deadlock ocure (mysql)

source repo: https://try.gitea.io/abcKing/GitNex

**Comment by zeripath** [comment]
Dude!! Seriously this is a bad bad bad issue report!

I presume you mean that you were trying to migrate the repository https://try.gitea.io/abcKing/GitNex from try.gitea.io to a local server and the local server deadlocked? Or do you mean that try deadlocked?

I'm guessing you meant your local server's database is MySQL? (I note try uses MySQL too)

Do you have any logs around this point?

Are you sure it's a DB deadlock and not some kind of http loop or other code deadlock? MySQL should have a deadlock breaker meaning that at least one of the deadlocking queries/transactions should get broken.

Have you repeated the procedure with:

``ini
[database]
LOG_SQL=true
...
```

to get the SQL logs for this?

**Comment by lunny** [comment]
@zeripath try uses sqlite, so it's easy to let the DB deadlock.

**Comment by 6543** [comment]
I'll shuld be more specific :sweat: - but do not have logs at the moment, so I only can gess ...

... I'll work on this issue - and if I konw more I'll let you konw

**Comment by zeripath** [comment]
no worries - it's just that if a user had made this report we'd be all stuck scratching our heads!

**Comment by 6543** [comment]
@zeripath I have an error leged :tada: - thanks for the error screen on migrations :)

`Error 1062: Duplicate entry '+1-13037-0-1--1' for key 'UQE_reaction_s'`

**Comment by 6543** [comment]
so I guess: since source repo is already a migrated repo: api returns some entrys who make no sence

the question is how to treat them: drop/show as GhotUser/ ?!?
