### ISSUE TITLE
Add List-Unsubscribe-Header to activation and notification emails

### ISSUE THREAD

**Issue by Codeberg-org** [go-gitea/gitea#13283]
- Gitea version (or commit ref): 1.12.5
- Git version: any
- Operating system: any
- Database (use `[x]`):
  - [X] PostgreSQL
  - [X] MySQL
  - [X] MSSQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
- Log gist:

## Description

Email testing tools complain that gitea emails are classified as bulk emails but do not have a `List-Unsubscribe-Header`. It might make sense to link the "unfollow", or "unwatch issue" link to notifications, and for activation emails provide something like "I did not register. Please delete the account".

_Some background on the latter issue: On Codeberg.org we see abusive registration attempts where some guys start a registration with an email address obviously not under their control. Albeit this sounds weird, there is some evil logic in this behavior: even a small numbers of those who receive the email address and click the activation button is sufficient to create totally anonymous accounts that can later be used for all kind of vandalism. But even near-term, for the platform, this is causing all kinds of headaches related to email reputation, as many email recipients are not aware what this email is about, and hit the spam button. An `unsubscribe/delete-this-account` link might provide a nice user interface to minimize this accidental spam classification. (and yeah, even if the platform is completely out of the loop, from the perspective of the accidental recipient this is unwanted spam. We acknowledge this.)._

**Comment by mscherer** [comment]
Also discussed on #10808
