### ISSUE TITLE
Last update date for mirror in explore list

### ISSUE THREAD

**Issue by cez81** [go-gitea/gitea#1329]
- Gitea version (or commit ref): 1.1.0+32-g03d7998
- Git version: 2.7.4
- Operating system: Ubuntu 16.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
I don't think the "Updated 1 xx ago" in the explore list makes much sense for mirrors as it is now. The date is when the migration was made. I think it would make more sense to show when last synced and when last commit was made.

Also there is no way (that I know) to find out when a mirror was last synced unless you have access to the settings. Maybe show it somewhere on the repository "front page"?

## Screenshots
Recent screen shot from https://try.gitea.io/explore/repos. "Updated" 2 days ago but last commit 10h ago.
![mirror_updated2](https://cloud.githubusercontent.com/assets/9416498/24083768/c2d864be-0cdd-11e7-8bdb-64ea86f51b66.png)

**Comment by appleboy** [comment]
@lunny I think this should be resolved.

**Comment by lunny** [comment]
resolved by #3551
