### ISSUE TITLE
Gitea sendmail command fails mysteriously

### ISSUE THREAD

**Issue by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [go-gitea/gitea#13306]
- Gitea version (or commit ref): [`1.14.0+dev-84-ge2740b32b`](go-gitea/gitea/commit/e2740b32b)
- Git version: `git version 2.29.1.341.ge80a0c044a`
- Operating system: Arch Linux
- Built from source
  - [x] Yes
- Run with
  - [x] systemd
- Database:
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] No

## Description
I have been testing the [recently introduced sendmail functionality](#13079 ) and my instance doesn't want to proceed with the following error
```log
[gitea@nebula ~]$ gitea admin sendmail --title "[Test] Gitea sendmail" --content "Please disregard this email as it is just a test of Gitea sendmail functionality."
Proceed with sending email? [Y/n] y
error: Unable to contact gitea: Post "api/internal/mail/send": unsupported protocol scheme ""
```
The error does not disappear even when I explicitly point the command to a valid config, which does have the data necessary to speak to Gitea and are apparently missing in the POST request being sent out (namely protocol scheme and app URL), as documented below
```log
[gitea@nebula ~]$ gitea admin sendmail --config /etc/gitea/app.ini --title "[Test] Gitea sendmail" --content "Please disregard this email as it is just a test of Gitea sendmail functionality."
Proceed with sending email? [Y/n] y
error: Unable to contact gitea: Post "api/internal/mail/send": unsupported protocol scheme ""
```
Also, logs (set to debug) with gitea in dev mode don't yield anything.

**Comment by lunny** [comment]
Please confirm your app.ini `LOCAL_ROOT_URL` on `[server]` has set correct value. In fact, once the error occupied, your gitea instance should not work normally.

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
> Please confirm your app.ini `LOCAL_ROOT_URL` on `[server]` has set correct value. In fact, once the error occupied, your gitea instance should not work normally.

In fact I think it's set to the default value
![image](https://user-images.githubusercontent.com/61180606/97148607-b3c67780-176b-11eb-83f7-4aaba92bb81f.png)

**Comment by lunny** [comment]
@wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf Please see #13312

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
> @wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf Please see #13312

Thanks.
I applied the patch you wrote and left a comment there - the emails are still not going through.
