### ISSUE TITLE
Add category "Opened and Closed Issues" to activity overview

### ISSUE THREAD

**Issue by MGChecker** [go-gitea/gitea#13309]
Currently, the gitea activity overview does not allow to calculate how the amount of open issues has changed over a certain timeframe, since issues that have been opened and closed in this time are only counted as closed issues.

This could be fixed by either listing these issues as new and as closed, or by introducing a third category for those. For PRs, it is basically the same issue.

**Comment by lafriks** [comment]
Yeah, probably new category would be most useful

**Comment by MGChecker** [comment]
I would still really appreciate for this to be done.

**Comment by tmnvanderberg** [comment]
I nobody objects, I'll see how easy it is to add a third category

**Comment by lunny** [comment]
Closed by #31776
