### ISSUE TITLE
Username issue with migrated reactions

### ISSUE THREAD

**Issue by mrsdizzie** [go-gitea/gitea#13317]
Small UI issue there seems to be a () after usernames when hovering over migrated reactions. Seems ok with normal ones.

<img width="855" alt="Screen Shot 2020-10-26 at 10 48 15 AM" src="https://user-images.githubusercontent.com/1669571/97187658-0a867e00-1779-11eb-887c-65abc27b0861.png">

**Comment by lunny** [comment]
Is this still a problem? Could you give the link of the screen shot?

**Comment by lunny** [comment]
Close as outdated.
