### ISSUE TITLE
Issue with comment header display after change to flex

### ISSUE THREAD

**Issue by mrsdizzie** [go-gitea/gitea#13316]
<img width="851" alt="Screen Shot 2020-10-26 at 10 36 47 AM" src="https://user-images.githubusercontent.com/1669571/97186030-2b4dd400-1777-11eb-9e46-43e83a1f5769.png">

Seems to come from @kolaente PR #13039

https://github.com/go-gitea/gitea/blob/dbebc6b0e3a54b39c92a026be7b9ac270a20ea27/web_src/less/_repository.less#L1046-L1047

**Comment by silverwind** [comment]
Probably need to put left-aligned content into it's own flexbox to prevent this, e.g. flex parent has two children, left and right-aligned).
