### ISSUE TITLE
Bug: cannot upload .zip file in issue on Gitea.com on Windows10

### ISSUE THREAD

**Issue by gymgym1212** [go-gitea/gitea#13323]
- Gitea version (or commit ref):the version of Gitea.com - go1.15.3
- Operating system: failed on windows but succeeded on macOS
  
  
  
- Can you reproduce the bug at https://gitea.com:
  - Yes

**Comment by 6543** [comment]
`"allowed_types": "image/*,application/zip,application/gzip,application/octet-stream,text/plain",`
*curl -X GET "https://gitea.com/api/v1/settings/attachment" -H  "accept: application/json"*

**Comment by gymgym1212** [comment]
@6543 It seems that the `application/zip` doesn't work in windows. BTW, out of curiosity why the attachment types are different between issues and commits.

**Comment by 6543** [comment]
linux works too ... Tested it on Win10: I can confirm it - so its a Windows-Only-Problem

**Comment by silverwind** [comment]
gitea.com's config needs to be updated to extension-based allowed types as per https://github.com/go-gitea/gitea/commit/cda44750cbdc7a8460666a4f0ac7f652d84a3964 to fix this. Or just use the defaults which match GH.

**Comment by lunny** [comment]
I have updated allowed_types to allow .zip on https://gitea.com . And please create issues on https://gitea.com/gitea/gitea.com if the issue is gitea.com special one.

**Comment by silverwind** [comment]
@gymgym1212 can you confirm it works now?

**Comment by gymgym1212** [comment]
Sorry for my silence, and it works now.
