### ISSUE TITLE
Question : blog url as GitHub

### ISSUE THREAD

**Issue by tboulogne** [go-gitea/gitea#13322]
Hello,

I'd like to know how i could access a commit file like on GitHub with :

``
'https://{host}/{repo}/blob/{sha}/{path}#L{lineno}'
``

I'd like to have to write a source_linker for pydoc-markdown.

Thanks for help.

regards

**Comment by 6543** [comment]
@tboulogne yes

`'https://{host}/{repo}/src/branch/{branch}/{path}#L{lineno}'`
or
`'https://{host}/{repo}/src/commit/{sha}/{path}#L{lineno}'`

**Comment by tboulogne** [comment]
@6543 let me try this :-).

thanks !
