### ISSUE TITLE
migration: pull requests show broken but they dont

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#13321]
gitea version: v1.13

gitea_uploader.go has to trigger `Merge conflict checking is in progress` for each pull after migration.

workaround: close & reopen a pull

**Comment by ramasoft-dv** [comment]
We do have that issue also and it's quite annoying.
The workaround from @6543 does not work for us. When we close the PR, we cannot reopen it : "This pull request cannot be reopened because the branch was deleted." (of course the branch was not deleted)
The only workaround we found is to merge the PR manually.

**Comment by 6543** [comment]
@ramasoft-dv another workaround should be to push a new commit to the pull (could be an empty one too)

**Comment by zeripath** [comment]
```
diff --git a/modules/migrations/gitea_uploader.go b/modules/migrations/gitea_uploader.go
index cd1fd5cb8..466c83275 100644
--- a/modules/migrations/gitea_uploader.go
+++ b/modules/migrations/gitea_uploader.go
@@ -28,6 +28,7 @@ import (
        "code.gitea.io/gitea/modules/storage"
        "code.gitea.io/gitea/modules/structs"
        "code.gitea.io/gitea/modules/timeutil"
+       "code.gitea.io/gitea/services/pull"
 
        gouuid "github.com/google/uuid"
 )
@@ -524,6 +525,7 @@ func (g *GiteaLocalUploader) CreatePullRequests(prs ...*base.PullRequest) error
        }
        for _, pr := range gprs {
                g.issues.Store(pr.Issue.Index, pr.Issue.ID)
+               pull.AddToTaskQueue(pr)
        }
        return nil
 }
```
