### ISSUE TITLE
Duplicated and obsolete email change on user profile page

### ISSUE THREAD

**Issue by WildCryptoFox** [go-gitea/gitea#13336]
REDACTED. See email to security@gitea.io.

**Comment by ashimokawa** [comment]
What we did on codeberg.org is to just forbid to change the email there, it must be done in the account settings and then the primary email can be switched after confirming. So we just patched out the feature to do it in the settings directly.

We did not open an issue here but contacted you in January via the official way of reporting security problems.

**Comment by WildCryptoFox** [comment]
(Whoops.) Thank you @ashimokawa for the information (and hint there is an official channel for this which I admit I should have checked for...)

**Comment by WildCryptoFox** [comment]
(Redacted and history deleted. Too late... but hopefully this will be fixed soon.)

**Comment by zeripath** [comment]
Do you know if the API is similarly affected?
