### ISSUE TITLE
new hook post-receive dont accept python

### ISSUE THREAD

**Issue by tofulm** [go-gitea/gitea#1334]
hi,
On last release v1.1.0,
the new hook post-receive does not allow we to execute scripts in python.
L6  : `sh "$SHELL_FOLDER/post-receive.d/$i`"
If we delete `sh` it's ok

**Comment by strk** [comment]
+1 to remove the sh call.
Hooks can be in any language, as long as they are executables, they
should be executed.

**Comment by lunny** [comment]
So anyone could send a PR to fix that?

**Comment by strk** [comment]
Please anyone doing a PR: wrap the execution in a function as there
are currently 3 different places where that overcomplex shell script
is executed

**Comment by philfry** [comment]
anything wrong with #1257?
(see also #1250 )

**Comment by lunny** [comment]
Let's move that issue and PR to discuss continue.
