### ISSUE TITLE
Diff in the web interface

### ISSUE THREAD

**Issue by savatin** [go-gitea/gitea#13342]
- Gitea version (or commit ref):
1.14.0+dev-18-gd453533be
- Git version:
2.26.2
- Operating system:
Ubuntu 18.04.3 LTS
  
  
  
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
- Log gist:

## Description

The \' and \" characters are displayed incorrectly when diff files are displayed in the web interface:
https://try.gitea.io/sergey.savatin/test_diff/commit/62d96b3486efecfce9736c7c3382077c10bfa6c4

## Screenshots

![image](https://user-images.githubusercontent.com/1937631/97482183-e25c7200-1966-11eb-86c7-a6bfe838ee0d.png)

**Comment by silverwind** [comment]
HTML source looks rather broken too with a 0x03 character in there:

```
<span class="mono wrap">    sh <span class="added-code">9;useradd -u $(stat -c "%u" .gitignore) jenkins'</span>;</span>
```

**Comment by zeripath** [comment]
The issue is that the diff library appears to be diffing the html entities at the subentity level. 

so &#34; is being compared with &#39; which means you get &#3 separated from the 9; one side and 4; on the other.

**Comment by zeripath** [comment]
I think we should just be letting chroma do the highlighting by passing in a HighlightRanges() and adjusting the format that chroma.LineHighlight sets.

**Comment by zeripath** [comment]
I'm too tired to do this right now but the idea would be rewrite gitdiff.go GetComputedInlineDiffFor to generate the line patches first and then pass to another highlight.Code - which would do the addition and deletion bits with the appropriate bits highlighted.

**Comment by zeripath** [comment]
(@mrsdizzie you don't have to fix - but if you understand what I'm getting at feel free to have a go.)

**Comment by mrsdizzie** [comment]
Grr yea : ( I'm away for a few days but could take a look after

**Comment by zeripath** [comment]
ugh the highlight trick suggested above doesn't work.

**Comment by zeripath** [comment]
OK I worked it - we just have to iterate through the diffs and run a fix up for the broken entities.

Now doing this I note that we end up creating these line diffs twice - which seems excessive to me - so clearly there are improvements to be made here.
