### ISSUE TITLE
API: PR #9452 made breaking changes

### ISSUE THREAD

**Issue by PhilippHomann** [go-gitea/gitea#13351]
- Gitea version (or commit ref): v1.12.5
- Git version: does not matter
- Operating system: linux (docker on CentOS)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No, but just because I haven't found any user with more than 30 repos
- Log gist:

## Description

PR #9452 added pagination to several API calls.
This change was meant to be non-breaking, but as @richmahn already mentioned in the PRs comments, it is!
Even when not using pagination in the API query the default pagination (DEFAULT_PAGING_NUM) is used, which defaults to 30.

In my use case this breaks the [jenkins plugin](https://github.com/jenkinsci/gitea-plugin/), which caused my jenkins instance to delete jobs....
Currently worked around that by setting DEFAULT_PAGING_NUM to 999, but I think we should prevent others from stumbling on this..

@SpaWn2KiLl @zeripath

**Comment by zeripath** [comment]
There is a pull request to https://github.com/jenkinsci/gitea-plugin/pull/25 fix this.

**Comment by zeripath** [comment]
I was sure that this was a duplicate but I can't quite find the issue related to this.

**Comment by 6543** [comment]
@PhilippHomann If you have an issue with a specific api pleace create an issue.

Since v1.12.x has been released quite some time, adding a breaking changes lable to the pull wont make anything different.

I'll close this issue because I can not detect a specific issue nor some proposal - hope #9452 didn't breace too mouch for you :)

**Comment by PhilippHomann** [comment]
Fine for me as I found a workaround until the plugin is patched.
Just wanted to report that issue as I haven't found one in giteas issues that prevents someone else from doing long research :)
