### ISSUE TITLE
Creating mirror from Gitlab.com fails

### ISSUE THREAD

**Issue by cdlm** [go-gitea/gitea#13365]
- Gitea version (or commit ref): 1.12.5
- Operating system: Synology DS415+ (x86_64), DSM 6.2, Gitea installed via https://github.com/flipswitchingmonkey/gitea-spk
- Database: MySQL
- Can you reproduce the bug at https://try.gitea.io: I didn't try, it's a private project
- Log: here's what looks the most suspect in the log…
```
2020/10/30 19:33:47 ...m.io/xorm/core/db.go:277:ExecContext() [I] [SQL] UPDATE `task` SET `status` = ?, `end_time` = ?, `errors` = ? WHERE `id`=? [3 1604082826 Handler crashed with error: /usr/local/go/src/runtime/panic.go:212 (0x453189)
        /usr/local/go/src/runtime/signal_unix.go:695 (0x452fd8)
        /go/src/code.gitea.io/gitea/modules/migrations/gitlab.go:126 (0x1923d45)
        /go/src/code.gitea.io/gitea/modules/migrations/base/downloader.go:58 (0x188e196)
        /go/src/code.gitea.io/gitea/modules/migrations/migrate.go:73 (0x1927aed)
        /go/src/code.gitea.io/gitea/modules/task/migrate.go:99 (0x193b7af)
        /go/src/code.gitea.io/gitea/modules/task/task.go:28 (0x193c017)
        /go/src/code.gitea.io/gitea/modules/task/task.go:50 (0x193c2d1)
        /go/src/code.gitea.io/gitea/modules/queue/workerpool.go:383 (0x16a9411)
        /go/src/code.gitea.io/gitea/modules/queue/workerpool.go:238 (0x16ab792)
        /usr/local/go/src/runtime/asm_amd64.s:1373 (0x46f370)
         22] - 676.276576ms
```

## Description

I'm trying to mirror a gitlab.com repo to my self-hosted Gitea instance. I use 2FA on Gitlab, and already have a few mirror repos from that account, that seem to update fine. However, creating a new mirror fails.

Because the docs are very incomplete about how to create and use the 2FA token, I had to do some guesswork and tried several combinations (somewhere it says the token should go in the username field). In the end, I'm using a 2FA token with `read_repository` scope, freshly created on gitlab, and giving my gitlab username and the token as password in the clone authorization form.

I've checked it's not a problem with the token itself by revoking my old token and replacing it with the new one on existing mirrors seems to have worked (they continue updating).

**Comment by zeripath** [comment]
```
/go/src/code.gitea.io/gitea/modules/migrations/gitlab.go:126 (0x1923d45)
```

https://github.com/go-gitea/gitea/blob/aa1d9ef6cba71c80170ec8c9ef424cb780fa6481/modules/migrations/gitlab.go#L126

This implies that `g` here is `nil`.

However, I am uncertain as to why that might be.

**Comment by 6543** [comment]
> Can you reproduce the bug at https://try.gitea.io: I didn't try, it's a private project

@cdlm can you run current master localy to test this?

**Comment by cdlm** [comment]
Not easily, as I don't have a good workflow for deploying stuff… so that would be under Docker and probably with sqlite instead of mysql. In fact I'm planning to migrate my instance from the Synology SPK to docker compose, but didn't find the time to learn the tools and arrange that in the last few months :-(

**Comment by cdlm** [comment]
FIY issue is still there with 1.12.6

**Comment by 6543** [comment]
@cdlm does it still show the same tracelog?

**Comment by lunny** [comment]
Is this still a problem?

**Comment by cdlm** [comment]
I'll try again, I've migrated to the latest releases since then.

**Comment by lunny** [comment]
I will close this and Please feel free to reopen it or create a new issue for a different issue.

**Comment by 6543** [comment]
@cdlm i dont know where we should put a hint, if you have  a good idear please open a pull :)

**Comment by cdlm** [comment]
There's a circled question mark when one initially creates the migration, that points to gitlab's docs about creating the personal token. That could instead show an overlay with some help about the token scopes (and the link to gitlab's docs).

Another similar icon could be besides the credential fields explaining which combinations of username / "oauth2" fixed string + password / token are expected to work in which cases. As a user I get the point of tokens, but not the details of gitlab's API scopes or how exactly OAuth2 authenticates me, that's all :-)

I can open a feature request issue, but implementing it myself means spending a few days on learning Go first…
