### ISSUE TITLE
Incorrect colors on big teacup logo (arc-green theme)

### ISSUE THREAD

**Issue by cdlm** [go-gitea/gitea#13366]
- Gitea version (or commit ref): 1.12.5

## Description

The big teacup animation displayed when creating a migration has incorrect colors (wrong green on the handle) and funky transparency (see screenshot below).

## Screenshots

<img width="552" alt="Screenshot 2020-10-30 at 19 43 12" src="https://user-images.githubusercontent.com/136339/97746748-26787f80-1aeb-11eb-86ac-1c2b4b5d5f8e.png">

**Comment by silverwind** [comment]
Should convert this animation to SVG SMIL.

**Comment by yp05327** [comment]
![image](https://github.com/user-attachments/assets/9f30a5fc-3d2b-48de-a378-02d82aea543e)
It is correct now.
