### ISSUE TITLE
docker image Could not load host certificate

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#13384]
- Gitea version (or commit ref): 1.14.0+dev-130-g543697e61 
- Git version:
- Operating system:
  
  
  
I am using the latest docker image 

Digest:sha256:08ec48ce917f718771f7f5a55fec0db03ab82a70d4da6240f5067951b5a7c276

- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
- Log gist:

## Description
The ssh host keys cannot be loaded

>server_1  | Could not load host certificate "/data/ssh/ssh_host_ed25519_cert": No such file or directory
server_1  | Could not load host certificate "/data/ssh/ssh_host_rsa_cert": No such file or directory
server_1  | Could not load host certificate "/data/ssh/ssh_host_ecdsa_cert": No such file or directory
server_1  | Could not load host certificate "/data/ssh/ssh_host_dsa_cert": No such file or directory

I moved the ssh directory and new ones were created but the newly created ones cannot be found either.

The sshd_config in the image points to the correct location and a ls command also finds them. Permissions seem to fine
The directory is owned by root

>ls -la gitea/ssh
total 40
drwx------ 2 root root 4096 Nov  1 15:25 .
drwxr-xr-x 6 git  git  4096 Nov  1 15:25 ..
-rw------- 1 root root 1381 Nov  1 15:25 ssh_host_dsa_key
-rw------- 1 root root  607 Nov  1 15:25 ssh_host_dsa_key.pub
-rw------- 1 root root  513 Nov  1 15:25 ssh_host_ecdsa_key
-rw------- 1 root root  179 Nov  1 15:25 ssh_host_ecdsa_key.pub
-rw------- 1 root root  411 Nov  1 15:25 ssh_host_ed25519_key
-rw------- 1 root root   99 Nov  1 15:25 ssh_host_ed25519_key.pub
-rw------- 1 root root 1823 Nov  1 15:25 ssh_host_rsa_key
-rw------- 1 root root  399 Nov  1 15:25 ssh_host_rsa_key.pub

I have not changed my config for gitea

>grep -i ssh  gitea/gitea/conf/app.ini 
SSH_DOMAIN       = git.domain.tld
DISABLE_SSH      = false
SSH_PORT         = 22
SSH_LISTEN_PORT  = 22

Do I need another configuration now? I have seen the commit history for app.ini but I am not sure what is missing

**Comment by zettelzottel** [comment]
Ok. The "certs" are missing. I don't get it. For what is this used and how can I get rid of those lines? Which option do I have to use?

**Comment by lunarys** [comment]
Did you close the issue because you solved it? What did you do?
I'm having the same issue, though apart from those messages everything seems to be working normally.

**Comment by zeripath** [comment]
Ignore those warnings they're just there so you can install certificates if you want them easily.

**Comment by euh2** [comment]
I can't push through SSH anymore. Using rc2 now. Logs show `Could not load host certificate "/data/ssh/ssh_host_dsa_cert"`. Shouldn't Gitea handle OpenSSH. I'm using the docker-image as well.

**Comment by zeripath** [comment]
Those log lines are not relevant to your problem @euh2. 

You should open a new issue - complete with logs and full information as to which docker version you are using and its configuration.
