### ISSUE TITLE
Allow secondary actions for review comments

### ISSUE THREAD

**Issue by MGChecker** [go-gitea/gitea#13394]
Currently, review comments are missing the quote, edit, delete and reaction buttons present for other comments. It would be nice if these could be added.

**Comment by silverwind** [comment]
Reaction button is fixed on latest master. As for other differences, those two boxes use different templates and they are bound to drift apart in functionality because of that, we should unify them to a single template.

**Comment by MathJoDE** [comment]
I'm absolutely new to Go and new to this repo, but am basically interested in tackling this.

Could someone kindly point me to the relevant templates/code points where to make this change?

**Comment by lafriks** [comment]
Already fixed in #14339

**Comment by MathJoDE** [comment]
(Assuming this PR is already live on try.gitea.io)

It would really appreciate to also have this action menu in the "header comment" (upper comment in the screenshot) of a review, and not only at the inline comments.

![Screenshot_20210123_163124](https://user-images.githubusercontent.com/59893632/105606348-21993400-5d99-11eb-9ee2-7dcc0debb77e.png)

**Comment by MGChecker** [comment]
@lafriks Please reopen issue – as pointed out by @MathJoDE, this has not been resolved by this PR.

**Comment by MGChecker** [comment]
This has been realized by now.
