### ISSUE TITLE
Missing/Duplicate issue when sorting by nearest due date

### ISSUE THREAD

**Issue by DuckDuckWhale** [go-gitea/gitea#13395]
- Gitea version (or commit ref): 1.12.5
- Git version: 2.25.1
- Operating system: Ubuntu Server 20.04
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Haven't tried
- Log gist: N/A

## Description

When sorting by nearest due date, some issues are duplicated and some cannot be found when going through pages. In my case the first page contains issue 108 and 118, and the second page still contains them but in a different order mixed with other issues. The overall issue count remains the same, but since some are duplicated some can't be found. This can be reproduced both at the per user issues page and the repository issues page.

One thing to note is that they all have the same due date and are all past due by less than a day.

## Screenshots

Page 1:
![image](https://user-images.githubusercontent.com/28813824/97832924-e7803080-1c88-11eb-883f-29a620724b7b.png)
Page 2:
![image](https://user-images.githubusercontent.com/28813824/97832946-f49d1f80-1c88-11eb-98e3-b4d08fb7f97e.png)

**Comment by DuckDuckWhale** [comment]
Reproduced after upgrading to 1.13.0.

**Comment by DuckDuckWhale** [comment]
Reproduced after upgrading to 1.14.3, seems that it doesn't matter to be past due by a day. This sample is past due by a long while but still on the same day.
![page 6](https://user-images.githubusercontent.com/28813824/124995932-f465d880-dffc-11eb-9aa4-a86c4866e0f4.png)
![page 7](https://user-images.githubusercontent.com/28813824/124995934-f4fe6f00-dffc-11eb-8c0c-3dd67c7e63ce.png)

**Comment by lafriks** [comment]
Probably need to add ID as second sort parameter

**Comment by DuckDuckWhale** [comment]
Just encountered a duplicate issue that is not past due. So it seems that the only requirement is that they must be due on the same day, so my best guess is temporally inconsistent sorting across pages.
