### ISSUE TITLE
Mirror release commit count issue

### ISSUE THREAD

**Issue by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [go-gitea/gitea#13398]
- Gitea version (or commit ref): `Gitea version 1.14.0+dev-132-g8176ba657 built with GNU Make 4.3, go1.15.3 : bindata, sqlite, sqlite_unlock_notify`
- Git version: `git version 2.29.2.222.g5d2a92d10f`
- Operating system: Arch Linux
- Database:
  - [x] SQLite
- Build from source:
  - [x] Yes
- Run with:
  - [x] systemd
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes --> https://try.gitea.io/nuone/gitea/releases

## Description
I believe the commit count in the release area of a mirror is off.
For instance while the release page of a `go-gitea/gitea` mirror shows there have been 0 commits to master since `v1.14.0-dev`, the Gitea version string (`1.14.0+dev-132-g8176ba657`) says there in fact have been 132 commits to master.
I think the latter is correct.

## Screenshots
my instance:
![image](https://user-images.githubusercontent.com/61180606/97856814-1afca280-1cfd-11eb-9a13-571a232fb802.png)
try.gitea.io
![image](https://user-images.githubusercontent.com/61180606/97860299-34541d80-1d02-11eb-8f05-6f31bcaaa17c.png)

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
this still holds btw, even with great improvements to the UI such as #13428 ("Tags cleanup").
The count is still off.

**Comment by conor-byrne** [comment]
Has anyone else noticed negative commit count? The tag is also on a different branch to master in my case.

![image](https://user-images.githubusercontent.com/15220966/116363729-59ca6b80-a7fb-11eb-8126-67d61a421cca.png)

Version: 1.15.0+dev-189-gcc7d118b1

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
Currently running `Gitea Version: 1.15.0+dev-188-gf31443d6a` I can't reproduce the original issue anymore, probably because the tags/releases pages there have undergone some changes and the "$X commits to $branch since this release" isn't even displayed for mirrors.

Note that initially the issue was only pertaining mirrored repositories.

I haven't come across your issue yet (looks like this is a regular repository, not a mirror), although that'd probably presume me reproducing the commit count etc. @conor-byrne 

Just out of curiosity, what happens when you tag a commit that's 256 commits behind current HEAD? How will Gitea display that?

Smaller number (37<256<272) gets shown just fine
![image](https://user-images.githubusercontent.com/61180606/116375217-5ccf5700-a80f-11eb-934a-3212939bd9ca.png)

**Comment by lunny** [comment]
Close as outdated. Please open a new issue if this happen again.
