### ISSUE TITLE
Project boards / kanban: Support for organization-level boards

### ISSUE THREAD

**Issue by mappu** [go-gitea/gitea#13405]
- Gitea version (or commit ref): 1.13.0-rc1

## Description

Hi, the new Project feature is wonderful, a huge thanks to everyone who helped develop it.

As part of the big #8346 PR there was some support for organization boards and user boards (if a project is `OrganizationType`), but it's not exposed in the UI as far as I can tell (e.g. see also https://github.com/go-gitea/gitea/pull/11293#issuecomment-623670239 ).

I think the most recent status is from this comment: https://github.com/go-gitea/gitea/pull/8346#pullrequestreview-464238421 

> - cleanup some left over for ProjectTypeIndividual and ProjectTypeOrganization
>     - or finish to implement the ui
>
> I still would prefer to remove (or at least comment) the code related to User and Org project since it is not fully implemented before merging but I would not be against merging this PR like this since it would help to have other work on this.

---

This issue is a feature request to track exposing organization board support in the UI,

**Comment by esend7881** [comment]
I would also benefit for an issue board that is at the Organization level. This will allow issues to be reference by multiple sub-repositories within the organization.

**Comment by genofire** [comment]
One reason, why i still prefer gitlab (beside the good ci integration)

**Comment by zander** [comment]
A handy usecase written out on a seperate issue (#20203) copied here may be useful;

Imagine the usecase of an organization that uses a shared library git repo as well as a couple of application repositories which all get released at the same time.
Repos are grouped by who develops in them, afterall.

A new feature could be a "project" and that might touch multiple repositories in such an organization and while issues can have dependencies this doesn't solve the issue of having a nice overview of all the issues across all the repositories.

Similarly, a milestone could be used to identify all the remaining issues for "the next release", which covers multiple repositories. It would be very useful to list all the issues assigned to this milestone in an organization and not having to go to each repo where this is duplicated.

**Comment by 6543** [comment]
projects are structured in backend already ... just need some work in go code and frontend templates ...

**Comment by 6543** [comment]
lunny did got it first :D https://github.com/go-gitea/gitea/pull/22235
