### ISSUE TITLE
Tooltips go out of the screen

### ISSUE THREAD

**Issue by POPSuL** [go-gitea/gitea#13400]
- Gitea version (or commit ref): 1.13.0-rc1
- Git version: 2.18.4
- Operating system: CentOS 8, bare binary
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No (need admin permissions)
- Log gist: N/A

## Description

Left side of tooltip for "May Create Git Hooks" went beyond

## Screenshots

Google Chrome 85.0:

Edit user form:
![image](https://user-images.githubusercontent.com/683358/97865033-a9a10c00-1d5d-11eb-9596-dcb70fd672cb.png)

**Comment by silverwind** [comment]
Those tooltips are very crudely implemented. Need to use something better like https://github.com/atomiks/tippyjs.

**Comment by zeripath** [comment]
Why not just set `poping up`:

```diff
diff --git a/templates/admin/user/edit.tmpl b/templates/admin/user/edit.tmpl
index a0edd68e4..ec89db183 100644
--- a/templates/admin/user/edit.tmpl
+++ b/templates/admin/user/edit.tmpl
@@ -90,7 +90,7 @@
 					</div>
 				</div>
 				<div class="inline field">
-					<div class="ui checkbox" data-tooltip="{{.i18n.Tr "admin.users.allow_git_hook_tooltip"}}">
+					<div class="ui checkbox poping up" data-content="{{.i18n.Tr "admin.users.allow_git_hook_tooltip"}}" data-variation="wide">
 						<label><strong>{{.i18n.Tr "admin.users.allow_git_hook"}}</strong></label>
 						<input name="allow_git_hook" type="checkbox" {{if .User.CanEditGitHook}}checked{{end}} {{if DisableGitHooks}}disabled{{end}}>
 					</div>
```

**Comment by silverwind** [comment]
If you search "data-tooltip", you'll find 8 more similar cases in the source. Maybe fix all of them at once?

**Comment by zeripath** [comment]
I think data-tooltip still has a place - they're both provided by fomantic

**Comment by silverwind** [comment]
Ah, thought it was a custom implementation. Still, I'd get rid of it for our own usage or at least add a `max-width: 50vw` or something to force wrapping.
