### ISSUE TITLE
[UI] Link in Repo Description with tailing '_' do not work

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#13404]
Gitea v1.12.5 (codeberg)

IF you put a link witch end with `_` in the repo description the link you get to klick has no `_` at the end.

demo: https://codeberg.org/jolson/relativitetsanteckningar
issue source: https://codeberg.org/Codeberg/Community/issues/330

**Comment by techknowlogick** [comment]
Are you able to replicate this on try.gitea.io?

**Comment by 6543** [comment]
@techknowlogick good catch!

**Comment by mrsdizzie** [comment]
Was fixed by xurls update here https://github.com/go-gitea/gitea/commit/12a1f914f443cc31af4bc54ab43802a75742cd57

https://github.com/mvdan/xurls/commit/f319907e545cb8b069f97436c26c0aa60d80775a

**Comment by zeripath** [comment]
I don't think we can backport that to 1.12.6 - a backport to 1.13 for xurls alone is probably reasonable.

**Comment by 6543** [comment]
I'll take this :) - and test if it's doable for 1.12.6 ...

**Comment by 6543** [comment]
@mrsdizzie thanks for the hint!!! - It would not be solved that quick otherwise :tada: 

It realy was ...
 -> #13407
 -> #13408
