### ISSUE TITLE
Tag tweaks

### ISSUE THREAD

**Issue by jolheiser** [go-gitea/gitea#13426]
- Gitea version (or commit ref): `1.14.0+dev-148-gfb756e773`
- Git version: Whatever try uses
- Operating system: Whatever try uses
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite (does try still use SQLite, or did we change it?)
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes https://try.gitea.io/Etzelia/arikawa
  - [ ] No
- Log gist:
N/A

## Description

As noted in the above link, the repo has 89 _tags_, but none are _true_ Gitea releases.

Previously this was inconsequential because we showed both (and we still treat tags as releases in the DB, albeit with `IsTag: true`)

However, now that we distinguish tags on a separate page and added the number to the sub menu, we should specifically calculate how many _true_ releases we have vs how many are simple tags, and show them in the corresponding spot on the UI.

imo the sub menu (next to branches) should show the number of all tags (because releases are tags, but tags aren't _true_ releases)
The top menu should only show the number of _real_ releases.

The sub menu should also be renamed "tags"

## Screenshots

![kawa](https://user-images.githubusercontent.com/42128690/98130669-21ffee00-1e80-11eb-975c-4bf4ca5edb6a.png)

**Comment by silverwind** [comment]
Yes, we need separate counters for both releases and tags.

**Comment by jolheiser** [comment]
> Yes, we need separate counters for both releases and tags. I guess to not add a 5th duplicating entry in the second list, it's fine to just rename that to Tags.

My reasoning is that the second (sub) menu relates to git data, in which case tags makes sense because git has no concept of a formal release.

Top menu calculation is the current `NumReleases`, but the second (sub) menu calculation is only releases where `IsTag: true`

**Comment by silverwind** [comment]
My thoughts. Git does have annotated tags but I guess only 1% of users would know the difference between a lightweight and an annotated tag so I guess we follow what GitHub does here.

**Comment by jolheiser** [comment]
Even with annotated tags, git doesn't track attachments, pre-release, etc.

(But I do agree having a Gitea release created by pushing an annotated tag would be 👌 )

Once Gitea can distinguish between lightweight and annotated we could certainly revisit the counts.

**Comment by silverwind** [comment]
One slightly related topic is also to display tags on the release list in a deemphasized form like GitHub does, I think it's a nice feature.

![image](https://user-images.githubusercontent.com/115237/98147211-8183eb00-1ecc-11eb-8ab7-969c5b166c86.png)

**Comment by jolheiser** [comment]
> One slightly related topic is also to display tags on the release list in a deemphasized form like GitHub does, I think it's a nice feature.

I chose not to implement this in the linked PR, but I do agree it's nice to have. Might be worth adding in another PR.
