### ISSUE TITLE
gitee cannot synchronize mirror warehouse

### ISSUE THREAD

**Issue by niaiwomattt** [go-gitea/gitea#13420]
gitea cannot mirror the git repository. I use gitee enterprise version (https://gitee.com/). I have used all mirroring methods and failed. What should I do?

**Comment by a1012112796** [comment]
Hello, saddly we not support migrate gitee now, you can use git type to mirroring git data only. thanks.

**Comment by niaiwomattt** [comment]
> Hello, saddly we not support migrate gitee now, you can use git type to mirroring git data only. thanks.

I used git type, but the migration failed

![image](https://user-images.githubusercontent.com/2947859/98070164-8ed4b180-1e9b-11eb-8607-532aa958cba7.png)
![image](https://user-images.githubusercontent.com/2947859/98070183-9a27dd00-1e9b-11eb-808e-67099131b856.png)

**Comment by techknowlogick** [comment]
Which version of Gitea do you use? Are you able to fill out the default template as it provides us with a lot of information so we can help you better.

**Comment by techknowlogick** [comment]
Also you are filling out the email in user, but could you use just the username?

**Comment by niaiwomattt** [comment]
- Gitea version (or commit ref):  Gitea版本
1.13.0+dev-791-g76ac83402 built with GNU Make 4.3, go1.15.2 : bindata, timetzdata, sqlite, sqlite_unlock_notify
- Git version:  git version 2.23.0
- Operating system: ubuntu 18.04 server ,docker run
- Database (use `[x]`):
  - [ √] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ √] No
- Log gist:
```bash
2020/11/04 05:06:06 ...er/issues/indexer.go:142:func2() [I] PID 20: Initializing Issue Indexer: bleve
2020/11/04 05:06:06 ...er/issues/indexer.go:221:func3() [I] Issue Indexer Initialization took 131.751187ms
2020/11/04 05:06:06 ...xer/stats/indexer.go:38:populateRepoIndexer() [I] Populating the repo stats indexer with existing repositories
2020/11/04 05:06:07 ...xer/stats/indexer.go:84:populateRepoIndexer() [I] Done (re)populating the repo stats indexer with existing repositories
2020/11/04 05:06:07 routers/init.go:171:GlobalInit() [I] SQLite3 Supported
2020/11/04 05:06:07 routers/init.go:53:checkRunMode() [I] Run Mode: Development
2020/11/04 05:06:07 ...macaron/i18n/i18n.go:68:initLocales() [I] ERROR: failed to set message file(it-IT) for language italiano: key-value delimiter not found: Contextrequest"
2020/11/04 05:06:07 cmd/web.go:163:runWeb() [I] Listen: http://0.0.0.0:3000
2020/11/04 05:06:07 cmd/web.go:166:runWeb() [I] LFS server enabled
2020/11/04 05:06:07 ...s/graceful/server.go:55:NewServer() [I] Starting new server: tcp:0.0.0.0:3000 on PID: 20
2020/11/04 05:07:55 ...ules/task/migrate.go:64:func1() [E] DeleteRepository: repository does not exist [id: 13, uid: 1, owner_name: , name: ]
2020/11/04 05:07:55 modules/task/task.go:51:handle() [E] Run task failed: Migration failed: Clone: exit status 128 - fatal: invalid server response; got 'a4e8a9a1460752b728330025c0126f95e3ac7f69 HEAD'
```

## Description

...


## Screenshots

**Comment by niaiwomattt** [comment]
> Also you are filling out the email in user, but could you use just the username?

I try username

**Comment by niaiwomattt** [comment]
Same failure

**Comment by 6543** [comment]
@niaiwomattt but you can `git clone --mirror <url>` to you local computer?

It you only have a problem with this specific repo you can clone-mirror it and push it to a new uninitialized gitea repo afterwards

**Comment by niaiwomattt** [comment]
> @niaiwomattt but you can `git clone --mirror <url>` to you local computer?
> 
> It you only have a problem with this specific repo you can clone-mirror it and push it to a new uninitialized gitea repo afterwards

![image](https://user-images.githubusercontent.com/2947859/98512643-98965480-22a1-11eb-8e33-9046c78895b7.png)

done.

**Comment by lunny** [comment]
@niaiwomattt Could you try the latest version to mirror that?

**Comment by niaiwomattt** [comment]
> @niaiwomattt Could you try the latest version to mirror that?

`2021/01/27 03:24:57 ...ules/task/migrate.go:67:func1() [E] DeleteRepository: repository does not exist [id: 82, uid: 1, owner_name: , name: ]
2021/01/27 03:24:57 modules/task/task.go:51:handle() [E] Run task failed: Authentication failed: Clone: exit status 128 - fatal: could not read Username for 'https://xxxx:3443': No such device or address`

xxx is the address of our original git warehouse. I can pull it locally without a password. I have tested both with and without a password in gitea. Both are not possible. This error is reported in the log file without a password. Wrong, and if the mirroring fails, can the error be printed on the current interface? If I weren't the maintainer, I didn't know what was wrong with him?

**Comment by 6543** [comment]
I think gitee has a other\no way to encode basic auth into url as default

**Comment by lunny** [comment]
I think because there is a `@` on his username which should be treated different. Could you try use token to mirror?
