### ISSUE TITLE
HTML emails are sent as text/plain

### ISSUE THREAD

**Issue by cez81** [go-gitea/gitea#1342]
- Gitea version (or commit ref): 1.1.0+61-g888dee3b
- Git version: N/A
- Operating system: N/A
- Database (use `[x]`): N/A
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
Email templates are html but emails are sent as text/plain unless ENABLE_HTML_ALTERNATIVE = true

## Screenshots
![email](https://cloud.githubusercontent.com/assets/9416498/24110563/0d5a6dd2-0d94-11e7-92ed-5ff9bf152180.png)

**Comment by strk** [comment]
So what ? That's intentional
If you really want your users to suffer more, then
you can enable HTML mails ...

**Comment by cez81** [comment]
Ok fair enough. I don't really care as I'm the only user. Just seems a bit odd to have html templates and then have the default setting to send as plain text.

**Comment by strk** [comment]
Yeah, that's bad, and doesn't even work very nicely.
The problem has been we didn't want to invalidate existing
custom templates. Nowadays it could be a moot point as templates
changed a lot.

**Comment by tboerger** [comment]
IMHO it should be sent as multipart by default. Most users like nicer emails :)
