### ISSUE TITLE
How to migrate postgresql databases, questions about documentation

### ISSUE THREAD

**Issue by Quixus** [go-gitea/gitea#13430]
- Gitea version (or commit ref): 1.12.5
- Git version: 2.20.1
- Operating system: debian 10
  
  
  
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No, not a bug
- Log gist:

## Description

The documentation [here](https://docs.gitea.io/en-us/backup-and-restore/) only mentions how to restore mysql and sqlite databases. Please add how to restore postgresql databases.

Additionally the instructions tell us to change ownership of ``/etc/gitea/conf/app.ini``,  ``/var/lib/gitea/repositories/`` and the files therein to ``gitea:gitea``. Shouldn't it be ``git:git`` as this is the default user for gitea?

Thanks in advance and best regards

**Comment by 6543** [comment]
> Shouldn't it be `git:git` as this is the default user for gitea?

It really depend the setup you have

### [Backup and Restore postgresql](https://www.postgresql.org/docs/9.1/backup.html)
