### ISSUE TITLE
Allow account creation from only a given domain name

### ISSUE THREAD

**Issue by acagastya** [go-gitea/gitea#13449]
Hi, I wanted to know if there exists, (and if not, could this be a feature in future) that on my instance of gitea -- say `git.example.com`, only those accounts can be created which have `@example.com` emails?

**Comment by mrsdizzie** [comment]
I think this exists with:
```
[service]
EMAIL_DOMAIN_WHITELIST = example.com
```

**Comment by lafriks** [comment]
Closing, please reopen if needed
