### ISSUE TITLE
Settings UI needs work

### ISSUE THREAD

**Issue by Fastidious** [go-gitea/gitea#1346]
- Gitea version (or commit ref): `N/A`
- Git version: `N/A`
- Operating system: `/N/A`
- Database (use `[x]`): `/N/A`
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL) https://try.gitea.io/user/settings
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

Settings fields are all hugely long. The whole interface looks rather discordant (and I know this is, like art, subjective). The OpenID "tab" is completely different, the verbiage in it is also odd. Verbiage is not fully right (English) in more than one screen, under `Settings`.

## Screenshots

See URL at https://try.gitea.io/settings.

**Comment by strk** [comment]
@geek1011 do you agree about making those fields narrower ? (sounds good to me).
@Fastidious do you have proposals about better phrasing where you see them broken (PR as preferred over issues :)

**Comment by bkcsoft** [comment]
> Settings fields are all hugely long. 

While I agree, you still have to consider other languages than English.

**Comment by Fastidious** [comment]
I believe this was fixed (but nobody has closed the ticket). Closing it. Will create a new one if I see something odd.
