### ISSUE TITLE
Missing indentation

### ISSUE THREAD

**Issue by cyb3rko** [go-gitea/gitea#13466]
- Gitea version (or commit ref): 1.14.0+dev-59-ga67b2bc30
- Git version: Git for Windows 2.28
- Operating system:
  downloaded via / running on docker
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL (MariaDB)
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No

## Description

If you open files which contain code with indentation the very first indentation is just one space, every other indentation is just ignored.

## Screenshots
**Gitea Interface**:
![Gitea Issue1](https://user-images.githubusercontent.com/46033730/98468980-3b38cf80-21dd-11eb-8887-bd3a5a7ad218.PNG)  

**Raw Content**:
![Gitea Issue2](https://user-images.githubusercontent.com/46033730/98468989-47249180-21dd-11eb-9ede-4f74bf64029d.PNG)

**Comment by zeripath** [comment]
this is a duplicate and is already fixed.

**Comment by cyb3rko** [comment]
Which version will it have included?

**Comment by zeripath** [comment]
try.gitea.io is on  1.14.0+dev-168

you should update.

**Comment by cyb3rko** [comment]
@zeripath 
We now are on 1.14.0+dev-215-gd025d84d9, it's still not working.
dev-215 is even newer than dev-168, right?

Is it broken again?

**Comment by mrsdizzie** [comment]
You would need to put up an example on try.gitea.io or at least something to copy/paste from here that should help reproduce it. There isn't anything easily reproducible with screenshots of text. I couldn't reproduce this based on the example of 

>files which contain code with indentation the very first indentation is just one space
