### ISSUE TITLE
Administratos are refered to as owners in comment headings

### ISSUE THREAD

**Issue by MGChecker** [go-gitea/gitea#13460]
Comments for issues and PRs written by Collaborators in a project are tagged with "Owner" in the heading, if the collaborators have global admin access. I think this is not intended.

**Comment by lunny** [comment]
This should be a bug but not an enhancement.

**Comment by silverwind** [comment]
Isn't it just reflecting their role in the organization, if it is one?

**Comment by MGChecker** [comment]
> Isn't it just reflecting their role in the organization, if it is one?

I do not understand. Admin access is not on organization level, and I do not see why someone should be designated as "Owner" of a project, only because he can in principle do everything an owner could. It might not reflect the role of this user in the context of the given organization.
