### ISSUE TITLE
googs reference in title

### ISSUE THREAD

**Issue by 5im-0n** [go-gitea/gitea#1347]
- Gitea version (or commit ref): 1.1.0

there is still a googs reference in the title of the page:
![2](https://cloud.githubusercontent.com/assets/2580993/24135822/36205934-0e0c-11e7-8b45-9944375d7c62.png)
![1](https://cloud.githubusercontent.com/assets/2580993/24135821/361f9922-0e0c-11e7-9472-b3c43271cbc4.png)

**Comment by ptman** [comment]
Can you link to the line in the source where this is? Or is it just in your old config?

**Comment by cez81** [comment]
Should be this one, https://github.com/go-gitea/gitea/blob/release/v1.1/templates/base/head.tmpl#L6
I'm guessing old config. Check the APP_NAME setting.

**Comment by ptman** [comment]
Yes, I think it's from here: https://github.com/gogits/gogs/blame/f35bd3400206bf4c1b19050dba99fd3dc5d6edc4/conf/app.ini#L6

**Comment by 5im-0n** [comment]
yes, it was an old config. sorry for the noise.
