### ISSUE TITLE
Web View not updated by commit

### ISSUE THREAD

**Issue by leaderred** [go-gitea/gitea#13479]
- Gitea version (or commit ref): Gitea Version: 1.14.0+dev-179-gb091c994b
- Operating system: Official Gitea Docker Image
- Database (use `[x]`):
- [X] PostgreSQL

## Description
When i commit changes and push them by console from my local system to gitea docker on my server, data is send without an error. I can't see this commit, when i open gitea web view an my server. The project with files is visible, but no new commit is listet. But when i clone this repo to my local system in an other folder, all new changes are downloaded.

Here is the output of git push:

git push origin master
Enumerating objects: 217, done.
Counting objects: 100% (217/217), done.
Delta compression using up to 8 threads
Compressing objects: 100% (125/125), done.
Writing objects: 100% (135/135), 148.76 KiB | 4.65 MiB/s, done.
Total 135 (delta 29), reused 2 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (29/29), completed with 27 local objects.
hint: The 'hooks/pre-receive' hook was ignored because it's not set as executable.
hint: You can disable this warning with `git config advice.ignoredHook false`.
hint: The 'hooks/update' hook was ignored because it's not set as executable.
hint: You can disable this warning with `git config advice.ignoredHook false`.
hint: The 'hooks/post-receive' hook was ignored because it's not set as executable.
hint: You can disable this warning with `git config advice.ignoredHook false`.
To ssh://git.xxx.xx:7022/xx/project.git

I have problems since i have a new fritzbox router. I have port 7022 fowarded to my local server and passed them to the docker container. In the past, everything was working well.

Do you have an idea, why web version auf gitea is not updated by new commits? Can i get any logs to localize the problem?

Thank you for your help

**Comment by techknowlogick** [comment]
The logs above have the issue being reported. That the githooks are unable to execute, do you have your repos mounted on a partition that is flagged as noexec?

**Comment by leaderred** [comment]
> The logs above have the issue being reported. That the githooks are unable to execute, do you have your repos mounted on a partition that is flagged as noexec?

Hi,

i have found this description on google too, but i dont know, where i should go with this info, because i use the official docker image. I can't change anything to this partition. Or does it mean, that i have to set this flag on my server ssd too, where i have my docker shares mounted? Is a separate ssd, not system, only data and ssd.

defaults,nofail,user_xattr,noexec,usrjquota=aquota.user,grpjquota=aquota.group,jqfmt=vfsv0,acl

Do i have to remove noexec from /etc/fstab?

Greetings

**Comment by techknowlogick** [comment]
yes, `noexec` will need to be removed. If the same log lines happen above then you'll need to ensure that the githooks can execute.

I will close this now, but if you need any more assistance please reach out via our forum or chat where links can be found at: https://docs.gitea.io/en-us/seek-help/#support-options

**Comment by leaderred** [comment]
Thank you very much, it works.

But i dont know, why it have worked before, because i havent changed anything at my partition.
