### ISSUE TITLE
Set ignore whitespace via configuration

### ISSUE THREAD

**Issue by arpan34** [go-gitea/gitea#13472]
Hi gitea team!

Was wondering if it is possible to set "ignore whitespace" to true via the configuration file/CLI. I know this can be done via the UI.

Thanks in advance!

**Comment by mrsdizzie** [comment]
There isn't a way to set that -- it isn't a setting that is saved anywhere just a query passed to the URL.

**Comment by arpan34** [comment]
thanks @mrsdizzie !

It is possible to set this flag when creating a pull request via API?

**Comment by mrsdizzie** [comment]
It isn't a flag, its just a query on the URL when viewing a diff. Ex:

 https://try.gitea.io/mrsdizzie/tea/pulls/26/files?style=unified&whitespace=ignore-all

It isn't stored anywhere -- just clicking the "whitespace->ignore all whitespace" button on the files tab adds that query to the URL and reloads the page. There is no saved state for it anywhere.

**Comment by arpan34** [comment]
Thanks again @mrsdizzie for the quick help! :)
