### ISSUE TITLE
[API] admin create user: return usefull error if passwordcheck not pass

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#13480]
source: https://gitea.com/gitea/go-sdk/issues/389

post /admin/users to create a new user.
i got response: code=400, message=Bad Request, the request body: 
```json
{
    "email":"debugcool@126.com",
    "full_name":"debugcool",
    "login_name":"debugcool",
    "must_change_password":true,
    "password":"123456",
    "send_notify":true,
    "source_id":0,
    "username":"debugcool"
}
```

i want to know what's wrong with my request or where is the open api log

-> password complexity dont match

**Comment by 6543** [comment]
@debugcool ping :)

**Comment by zeripath** [comment]
AFAICS the API returns some JSON with the message: "PasswordComplexity" or "PasswordPwned" so I'm not certain what's wrong here.

**Comment by 6543** [comment]
let me have a look ...
