### ISSUE TITLE
Disable Browser Caching for RAW view

### ISSUE THREAD

**Issue by liszca** [go-gitea/gitea#13499]
- Gitea version (or commit ref):
- Git version: 1.12.5
- Operating system: Debian 10
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
- Log gist:

## Description
Because of browser caching (in this case Firefox 82.0.2), the RAW file view may not represent the actual file content when Edit was done in browser beforehand.

The first screenshot shows what was saved, the second is Raw view.

It can be solved by clearing the cache of the browser, but is it possible to solve this on the server side?
...

## Screenshots
![grafik](https://user-images.githubusercontent.com/32976532/98706155-cc937780-237e-11eb-9d89-f663244f2862.png)
![grafik](https://user-images.githubusercontent.com/32976532/98706416-1bd9a800-237f-11eb-9b48-9027d8c0fa9a.png)

**Comment by Codeberg-org** [comment]
It might make sense to version these files with `Etag`, as we do in codeberg pages: https://codeberg.org/Codeberg/build-deploy-gitea/src/branch/master/var/www/pages/index.php#L146, so that they are cached, but the cache is invalidated with a new commit.
