### ISSUE TITLE
request: user email redirect

### ISSUE THREAD

**Issue by Spongman** [go-gitea/gitea#13509]
we have a CI system and we'd like to include links in the build emails that get sent out that include a link to the committer's gitea profile page. however, the CI system doesn't know about LDAP and/or gitea users, it just knows the user's email address...

can you please add a redirect URL that redirects from a gitea user's email address to their user profile?

eg. `https://gitea.company.com/user/myemail@company.com` -> `https://gitea.company.com/myuser`

**Comment by techknowlogick** [comment]
This was double submitted so I will close this one and we can use the other one to discuss

**Comment by Spongman** [comment]
sorry, yes, github 404d me...
