### ISSUE TITLE
[Feature] Let gitea recover from DB deadlocks

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#13515]
Taken from https://github.com/go-gitea/gitea/issues/13513#issuecomment-725451964

"... SQLite makes it easy for gitea to fail, then gitea should probably have error-correcting logic to correct any errors SQLite might cause. ..."

aka be more `Fault tolerance`

**Comment by zeripath** [comment]
The only option for detecting deadlocks would be to have a timer in Xorm that would limit the length of time that a query could take and to kill it if it took too long. We'd need to have some way of actually ensuring that the killing of the query actually killed the SQLite C query too.

**Comment by zeripath** [comment]
yet again this is another example of why models.x must die.

We can have send in a context with our requests to the db which would allow us to query dbs only within the context, killing our context should kill the request.

from mattn/go-sqlite3:sqlite3.go:1921:
```go
// exec executes a query that doesn't return rows. Attempts to honor context timeout.
func (s *SQLiteStmt) exec(ctx context.Context, args []namedValue) (driver.Result, error) {
	if ctx.Done() == nil {
		return s.execSync(args)
	}

	type result struct {
		r   driver.Result
		err error
	}
	resultCh := make(chan result)
	go func() {
		r, err := s.execSync(args)
		resultCh <- result{r, err}
	}()
	select {
	case rv := <-resultCh:
		return rv.r, rv.err
	case <-ctx.Done():
		select {
		case <-resultCh: // no need to interrupt
		default:
			// this is still racy and can be no-op if executed between sqlite3_* calls in execSync.
			C.sqlite3_interrupt(s.c.db)
			<-resultCh // ensure goroutine completed
		}
		return nil, ctx.Err()
	}
}
```

**Comment by zeripath** [comment]
(which hopefully would break the deadlock.

**Comment by wxiaoguang** [comment]
Deadlock should be handled by callers/developers, not by framework.

**Comment by alxpettit** [comment]
I am running into this problem, using Postgres. Server has a long-running migration. Deployment engine restarts it automatically. The repo is broken and nothing in the web UI will let me fix it. It is 'migrating' forever. :/

**Comment by wxiaoguang** [comment]
@alxpettit that's not database deadlock ....

I guess it's a bug in migration module.
