### ISSUE TITLE
[FEATURE] Let Gitea show issue assignee(s) in project veiw

### ISSUE THREAD

**Issue by dusatvoj** [go-gitea/gitea#13517]
- Gitea version (or commit ref): `1.13.0-rc1`
- Git version: `2.20.1`
- Operating system: Debian 10
  
  
  
- Database (use `[x]`):
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes (https://try.gitea.io/dusatvoj/test/projects/1)
  - [ ] No
- Log gist:

## Description

As written in name: we want to have shown issue assignees in project view but we haven't found any solution in this gitea release

## Screenshots

![image](https://user-images.githubusercontent.com/11560794/98834658-c1ece700-243f-11eb-8102-fe891440c014.png)

**Comment by GroundTotems** [comment]
This can be done fairly easely with just the templates that are provided. 
Attached is the template for gitea 1.16.5 where its working 

[view.txt](https://github.com/go-gitea/gitea/files/8463843/view.txt)

![image](https://user-images.githubusercontent.com/103428054/162737287-8d642d88-a70c-4eaa-9eda-acbd90b0e3c7.png)

**Comment by wxiaoguang** [comment]
It has been done in 1.17-dev

* https://github.com/go-gitea/gitea/pull/15232
