### ISSUE TITLE
MSSQL:An existing connection was forcibly closed by the remote host.

### ISSUE THREAD

**Issue by CHN-STUDENT** [go-gitea/gitea#13512]
- Gitea version (or commit ref): 1.12.5
- Git version: 2.29.2
- Operating system: Win Server 2012 R2
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
- Log gist:

## Description
Can not install with MSSQL 2008 R2, Error info: An existing connection was forcibly closed by the remote host.
Then i try check user sa access, it does not have problem. 
I also try to trun on all mssql tcp/ip settings and create a new user, it does not work so.
At last, i try connect another ms sql server (2008 R2 too), not work.

## Screenshots

![image](https://user-images.githubusercontent.com/21209416/98749549-d953b200-23f6-11eb-8984-7c255728408d.png)
![image](https://user-images.githubusercontent.com/21209416/98749561-e1abed00-23f6-11eb-80b2-6e040a97156e.png)
![image](https://user-images.githubusercontent.com/21209416/98749618-fee0bb80-23f6-11eb-82ef-af14cf454156.png)

I see a post said because the sql connect use encrypt so it not work, but i do not know how to try it, could you help me? Thanks!

**Comment by CHN-STUDENT** [comment]
This is wireshark screenshots.
![image](https://user-images.githubusercontent.com/21209416/98749841-7c0c3080-23f7-11eb-84ee-eff916d6999d.png)

**Comment by lunny** [comment]
You should set up SP1 of mssql server. see https://github.com/denisenkom/go-mssqldb#known-issues

**Comment by CHN-STUDENT** [comment]
@lunny  hi lunny, i have installed SQL SERVER 2008 SP2 Update, but when i try to intall, gitea may crash without no log, and i try to restart it again, but not work, could you give me some advice? Thanks!
```
C:\gitea>gitea.exe web
2021/01/12 16:42:10 cmd/web.go:108:runWeb() [I] Starting Gitea on PID: 33584
2021/01/12 16:42:10 ...dules/setting/git.go:91:newGit() [I] Git Version: 2.29.2,
 Wire Protocol Version 2 Enabled
2021/01/12 16:42:10 ...es/setting/markup.go:61:newMarkupSanitizer() [W] Skipping
 empty section: markup.sanitizer.1.
2021/01/12 16:42:10 routers/init.go:130:GlobalInit() [T] AppPath: C:/gitea/gitea
.exe
2021/01/12 16:42:10 routers/init.go:131:GlobalInit() [T] AppWorkPath: C:/gitea
2021/01/12 16:42:10 routers/init.go:132:GlobalInit() [T] Custom path: C:/gitea/c
ustom
2021/01/12 16:42:10 routers/init.go:133:GlobalInit() [T] Log path: C:/gitea/log
```

**Comment by zeripath** [comment]
I'm closing this issue as it has been awaiting further feedback for several months. @CHN-STUDENT please open another issue if you are still having problems.
