### ISSUE TITLE
Heatmap Color Shade

### ISSUE THREAD

**Issue by bagasme** [go-gitea/gitea#13529]
- Gitea version (or commit ref): 1.14.0+dev-196-g4117a443c (built from source with `TAGS=bindata make generate build`)
- Git version: 2.28.0
- Operating system: Debian 10 (run via systemd)
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No (not relevant)
- Log gist:
(not relevant)

## Description
Consider following heatmap screenshot from my instance:
![heatmap](https://user-images.githubusercontent.com/40219486/98911854-e0161e00-24f7-11eb-872f-d21e52655bfa.png)

The gradation between level-2 and level-1 color shade is subtle; I can hardly differentiate both of them. The shade for the heatmap should be distinct enough per level, so that the colors can be differentiated easily.

Color for level-1 is `#8db4db`, and for level-2 is `#5791cb`

## Screenshots
(see above)

**Comment by silverwind** [comment]
Agree, might need to do either 20% or 15% opacity steps, they are currently 10%.

**Comment by silverwind** [comment]
https://github.com/go-gitea/gitea/pull/13533
