### ISSUE TITLE
Feature request: time tracking analytics/report

### ISSUE THREAD

**Issue by DuckDuckWhale** [go-gitea/gitea#13531]
I personally think it would be awesome if there is a way on the web GUI side to see time spent in the last 24 hours (for either the current user or in a repository). A graph showing that with custom start/end date/time would be even better. Seems to be a wanted feature on the GitLab side, see <https://gitlab.com/gitlab-org/gitlab-foss/-/issues/25532> and <https://gitlab.com/gitlab-org/gitlab/-/issues/25266>,

**Comment by noerw** [comment]
related: #8684

**Comment by noerw** [comment]
closing as duplicate / related to #4870
