### ISSUE TITLE
API: RFC 3339 time format as specified by Swagger not accepted

### ISSUE THREAD

**Issue by DuckDuckWhale** [go-gitea/gitea#13530]
- Gitea version (or commit ref): 1.12.5
- Git version: N/A
- Operating system: Ubuntu Server 20.04
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Haven't tried
- Log gist: N/A

## Description

When making a request using the API to `/user/times` and parameter `since` using RFC 3339 with space instead of `T`, the API returns an empty message, but when using `T` it works fine. Lower case `t` also as permitted by the RFC doesn't work either.

**Comment by lafriks** [comment]
RFC 3339 specifies that `T` should be used. It states that space or lowercase MAY be accepted but that in now way means it should be accepted to be compatible with spec.
