### ISSUE TITLE
feature: archive repository

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#1353]
I have some repositories uploaded to my gitea installation which are not used any longer but to which I need read access. We should implement a feature which makes it possible to "archive" a repository so you cannot push, create issues, comment or do anything else which may change it. There should be a notice "This project is archived." but you should be able to access everything in a read-only mode.

This prevents these repos from accidental pushes and a visitor will see that this repo is not maintained.

**Comment by bkcsoft** [comment]
Should be fairly simple to just add a `Archived`-flag in the DB :)

**Comment by monkeyhybrid** [comment]
GitLab has such a feature and if I remember correctly, as well as making the repo read-only, it hides it from the dashboard and removes it from searches too, which keeps things really tidy. This is a real bonus when you have many more 'stale' repos than active ones. And of course, you can always un-archive it in the future if you wish to continue work on the repo.

GitHub does something similar, but doesn't remove the archived repo from the dashboard (which can be annoying when you have lots of archived repos).

As it stands now in Gitea, I currently rename my stale repositories, adding `-Archive-2017` to their name, for example, but this still leaves them cluttering the dashboard and obviously does nothing to make them read-only. I'd love for Gitea to offer archive functionality in the same manner as GitLab does it. If I can help by providing any further details or testing, I will gladly do so.

**Comment by lafriks** [comment]
@monkeyhybrid what do you mean with dashboard?

**Comment by monkeyhybrid** [comment]
@lafriks In the Gitea web app, you have a Dashboard link at the top. Clicking this brings up a page showing recent activity in the main content area, and a list of repositories on the right hand side. It may be called something else in GitHub, although I think the same in GitLab, but roughly the same thing exists in both.

A list of repositories is also shown when clicking on Explore.

If an archive feature is added to Gitea, as well as making a repo read-only, it would be nice if archived repositories are not shown in these lists, and search results, or at least have an option to include / exclude archived repositories. This would remove a lot of clutter for those of us with lots of stale repositories (that we don't want to delete).

**Comment by AndyHee** [comment]
The possibility of irreversibly setting a repo to _read-only_ would definitely be a very useful feature for archiving purposes.

**Comment by bram-dingelstad** [comment]
This feature would mean a world of difference for me, I have a lot of smaller ideas that I want to keep around but not cluttering the rest of the application/repositories!

**Comment by adelowo** [comment]
This can be closed
