### ISSUE TITLE
[ui] the labels in issue sidebar view is too close

### ISSUE THREAD

**Issue by a1012112796** [go-gitea/gitea#13545]
- Gitea version (or commit ref):
- Git version:
- Operating system:
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
- Log gist:

## Description

now:
![image](https://user-images.githubusercontent.com/25342410/99090462-a5040f80-2609-11eb-98fd-9f03a3fb0dee.png)

suggest:
![image](https://user-images.githubusercontent.com/25342410/99090801-07f5a680-260a-11eb-94e8-f1897edf4788.png)

**Comment by mrsdizzie** [comment]
Seems OK in 1.13, should be from more recent change
