### ISSUE TITLE
BoltDB panic: runtime error: index out of range

### ISSUE THREAD

**Issue by psolyca** [go-gitea/gitea#1354]
- Gitea version (or commit ref): 9a9f8fa
- Git version: 2.12.0
- Operating system: Arch Linux armv5tel
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:
https://gist.github.com/psolyca/75f72eda0abc81ed95aa63991ffa2a81#file-gitea_boltdb_bug-log
## Description
Launching gitea on my armv5 board fail due to a bug in Bolt DataBase see Log.

Alse see : https://github.com/boltdb/bolt/issues/327 and https://github.com/boltdb/bolt/issues/430

**Comment by lunny** [comment]
closed by #1355
