### ISSUE TITLE
Syntax highlighting problem for Golang

### ISSUE THREAD

**Issue by Maxi-Mega** [go-gitea/gitea#13541]
I think there is a problem with syntax highlighting for Golang, more precisely with backslashes.

As you can see in the following picture, I protected a backslash with another backslash, but the syntax highlighter _thinks_ that I also protected the following quote (**'**)... so _he_ marks all the rest of the file as a string.
![gitea](https://user-images.githubusercontent.com/52792549/99071762-0947b480-25b3-11eb-95c2-f928f8e5f9ba.png)

The Gitea version where the problem occurred is 1.11.8

Thank you in advance,
Maxi_Mega

**Comment by lafriks** [comment]
I think this problem is resolved already in 1.13.0-rc2. Please reopen if not
