### ISSUE TITLE
API Call /admin/users/{username} does not work without email.

### ISSUE THREAD

**Issue by gabyx** [go-gitea/gitea#13543]
- Gitea version 1.12.5
- Git version: 2.29.2
- Operating system:
  Linux Alpine Docker Image.
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes [https://try.gitea.io/api/swagger#/admin/adminEditUser](https://try.gitea.io/api/swagger#/admin/adminEditUser)
  - [ ] No

## Description
API Call [https://try.gitea.io/api/swagger#/admin/adminEditUser](https://try.gitea.io/api/swagger#/admin/adminEditUser)
does not succeed with out email:
```
{
  "active": true,
  "email": "user@example.com"
}
```

Cannot provide a test, since I the admin user on https://try.gitea.io is not known (?)

**Comment by 6543** [comment]
@gabyx thanks for checking :)

**Comment by gabyx** [comment]
Testet it with the curl command from Swagger locally, and with
Gitea Python API `https://github.com/dblueai/giteapy/blob/1.0.8/docs/EditUserOption.md`
which says email is required too...

**Comment by 6543** [comment]
looks like it was intended in the past ... pull: #13562
