### ISSUE TITLE
Issue label spacing shifting

### ISSUE THREAD

**Issue by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [go-gitea/gitea#13566]
- Gitea version (or commit ref): `Gitea version 1.14.0+dev-212-g374ff6046 built with GNU Make 4.3, go1.15.5 : bindata, sqlite, sqlite_unlock_notify`
- Git version: `git version 2.29.2.454.gaff20da3a2`
- Operating system: Arch Linux
- Built from
  - [x] source
- Run with
  - [x] systemd
- Database:
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes

## Description
While the screenshots in the subject PR look alright, after applying #13553 I have come across labels (most of them, really) being out of place and with weird spacing introduced.
Standard arc-green, no custom templates in the subject area are being used, this is how the page is shown in both ff and chromium.

Please see screenshots below.
Overlapping labels were not the best either, but this looks worse IMO.

## Screenshots
anomaly 1
![image](https://user-images.githubusercontent.com/61180606/99153193-5ad16b80-26a7-11eb-815a-e4164d36080e.png)
anomaly 2
![image](https://user-images.githubusercontent.com/61180606/99153229-7f2d4800-26a7-11eb-928a-5748a7fa8782.png)
anomaly 3
![image](https://user-images.githubusercontent.com/61180606/99153246-9b30e980-26a7-11eb-983e-27e2741a260b.png)
anomaly 4
![image](https://user-images.githubusercontent.com/61180606/99153258-af74e680-26a7-11eb-9863-05e0a10aa679.png)
anomaly 5
![image](https://user-images.githubusercontent.com/61180606/99153289-cddae200-26a7-11eb-94e4-68cb5653a84a.png)

Edit: can reproduce on try.gitea.io

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
also, in more cases than not, this apparently affects the space after the labels as well (the big vertical gap between Labels and Milestones).
Shown in PR view, too.

anomaly 6
![image](https://user-images.githubusercontent.com/61180606/99153611-b4d33080-26a9-11eb-9f5d-4b58ad66c8b4.png)

**Comment by silverwind** [comment]
Can you try to reproduce on https://try.gitea.io/?

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
> Can you try to reproduce on https://try.gitea.io/?

sure

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
https://try.gitea.io/nuonedammittakenalready/ultimatetestrepo/issues/2#issuecomment-70319

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
![image](https://user-images.githubusercontent.com/61180606/99155322-1ea60700-26b7-11eb-91ba-c51ef099fe27.png)
![image](https://user-images.githubusercontent.com/61180606/99155323-2665ab80-26b7-11eb-91fa-cf62e642cba2.png)

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
https://try.gitea.io/nuonedammittakenalready/ultimatetestrepo/issues/4
![image](https://user-images.githubusercontent.com/61180606/99155650-18655a00-26ba-11eb-8860-92850f4eaa6c.png)

**Comment by silverwind** [comment]
Two bugs here:

1. Backend is rendering empty labels (which cause the spacing issue)
2. Labels should be inlined

I can fix the second case.

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
should #13570 really close this, though, if it only fixes one of the issues you named? @silverwind

**Comment by silverwind** [comment]
It actually fixes both.

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
> It actually fixes both.

I first wrote it, then went on to check it..my bad.
Cheers then! 🎉
