### ISSUE TITLE
Automatic Deletion of Unprotected branches on PR merge with toggleable switch

### ISSUE THREAD

**Issue by iarepandemonium** [go-gitea/gitea#13568]
- Gitea version (or commit ref): 1.14.0+dev-208-g6280af032
- Git version: 2.29.0
- Operating system: Linux Ubuntu 16.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No (not a bug.)
- Log gist:

## Description

* Toggleable switch at project level for use
* if an **unprotected** branch is merged while switch is set to true, that branch gets deleted
* protected branches are unaffected

**Comment by 6543** [comment]
similar  #3905

**Comment by 6543** [comment]
I think merge option will get to overloaded, should we make this a user and/or repo setting?

**Comment by iarepandemonium** [comment]
Yes I intended it to be togglable in the repo's own settings. I don't user repos that often, I considered one at organization level, because I will be personally enabling them in most of our projects but figured it would be too annoying to have 3 options of 'organization default', on, off

**Comment by lunny** [comment]
Assume the situations:

- [ ] The branch is a default branch on the same repository.
- [ ] The branch is a default branch on the forked repository.
- [ ] The branch on forked repository has also been sent to another upstream.
- [ ] There are some PRs sent to the branch.

**Comment by lunny** [comment]
> @lunny Can't forked repositories change the fork repo settings? I would have thought so…

@delvh You can, but if you have many forks, you may have to change every repository. Since the fork repositories is your copy of original repositories, so the settings depends on your personal usage habit.

**Comment by jpraet** [comment]
A checkbox like this on the merge form could already be an easy win. Even if it would be disabled by default, at least it saves you from scrolling down to the bottom of the page, clicking the delete branch button and the confirmation dialog. And it serves as a reminder too.

![afbeelding](https://user-images.githubusercontent.com/2212615/119569640-505b0180-bdaf-11eb-9b5b-e19cd67840f6.png)

**Comment by lunny** [comment]
> A checkbox like this on the merge form could already be an easy win. Even if it would be disabled by default, at least it saves you from scrolling down to the bottom of the page, clicking the delete branch button and the confirmation dialog. And it serves as a reminder too.
> 
> ![afbeelding](https://user-images.githubusercontent.com/2212615/119569640-505b0180-bdaf-11eb-9b5b-e19cd67840f6.png)

Maybe the text could be `Delete head branch if not protected or default`.

**Comment by 6543** [comment]
I would prefere @jpraet way but hide it if the branch is protected ...

**Comment by lunny** [comment]
Or disable the checkbox and display the reason
