### ISSUE TITLE
Login via LDAP leads to segmentation fault

### ISSUE THREAD

**Issue by ypnos** [go-gitea/gitea#1356]
- Gitea version (or commit ref): 1.1.0
- Git version:
- Operating system: Arch Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:
https://gist.github.com/ypnos/afb85db6722398f6d22b803c4879dfbf

## Description

I migrated from a gogs installation with LDAP authentication. Gitea starts fine without any unusual output. The login page loads fine. However, the POST with user+passwd leads to a crash. It is irrelevant which login information is sent.

If I set is_activated to 0 in the database login_source row, the crash does not happen. Instead I get:

> 2017/03/21 16:43:09 [...routers/user/auth.go:150 SignInPost()] [E] UserSignIn: Login source is not actived

which is expected.

**Comment by lunny** [comment]
It's difficult to find where the error is from gist. So I move this from 1.2.0 to 1.x.x

**Comment by thehowl** [comment]
@ypnos can't reproduce anymore?

**Comment by ypnos** [comment]
This was almost a year ago, so no. I had to find a solution for myself and move on.
