### ISSUE TITLE
Docker rootless image size close to twice as big

### ISSUE THREAD

**Issue by lafriks** [go-gitea/gitea#13577]
Looks like dockerfile command `chown & chmod` creates new layer in size of gitea binary that makes image close to twice as big.
see: https://github.com/go-gitea/gitea/blob/master/Dockerfile.rootless#L54 
and: https://hub.docker.com/layers/gitea/gitea/latest-rootless/images/sha256-b55c30e134a5ce42aaf3cb94402c3ac98294ffbbb82ea1a70e9c669a586b0441?context=explore

Maybe file could be chown'ed and chmod'ed before building docker image?

**Comment by lafriks** [comment]
ping @sapk

**Comment by silverwind** [comment]
There's `docker build --squash` to merge layers but it's been considered experimental for years. Interestingly, it seems not experimental on `docker buildx`.

**Comment by lafriks** [comment]
yes but that will squash all layers that is not so good as base layers are not reused anymore

**Comment by lafriks** [comment]
btw why *linux-amd64|*linux-arm64 tags are needed when there is already tag that has both archs in it?

**Comment by techknowlogick** [comment]
> btw why *linux-amd64|*linux-arm64 tags are needed when there is already tag that has both archs in it?

@lafriks docker manifest needs images to already exist

**Comment by lafriks** [comment]
oh, ok

**Comment by silverwind** [comment]
Should probably switch to `docker buildx` for cross-platform builds at some point.
