### ISSUE TITLE
 API: RFC 3339 time format weirdness

### ISSUE THREAD

**Issue by DuckDuckWhale** [go-gitea/gitea#13573]
- Gitea version (or commit ref): 1.12.5
- Git version: N/A
- Operating system: Ubuntu Server 20.04
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Haven't tried
- Log gist: N/A

## Description

I was making a request using the API to `/user/times` and parameter `since` using RFC 3339. When I use `2002-10-02T10:00:00-00:00` and `2002-10-02T10:00:00Z` it works fine, but when I use `2002-10-02T10:00:00+00:00` (with a plus) the API returns an empty message with a error code of 500.

**Comment by 6543** [comment]
its a bug and its fixed

**Comment by 6543** [comment]
Backport #13560 will fix it for 1.12.6 too
