### ISSUE TITLE
Unauthorized error when owner is not a user in gitea

### ISSUE THREAD

**Issue by evroon** [go-gitea/gitea#13589]
- Gitea version (or commit ref): 1.12.6
- Git version: 2.17.1
- Operating system: Ubuntu 18.04
  
  
  
- Database:
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
- Log gist:

## Description
Since 1.12.6, [private/serv.go](https://github.com/go-gitea/gitea/blob/master/routers/private/serv.go#L117) introduces a bug where the owner of the repository is checked to be active. However, in our case, we cannot clone or pull repositories because of this if statement and we had to downgrade to gitea 1.12.5. We get the following error for gitea 1.12.6 when using `git pull` on a repository that can be pulled with gitea 1.12.5:

```
Gitea: Unauthorized
Repository cannot be accessed, you could retry it later
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Our repositories are all part of the same organisation, so I assume that organisation is the owner. From what I understand, organisations don't have an `active` property, so this check will always fail.

**Comment by wgevaert** [comment]
The organisational owners do have a property `is_active`, but there is no means to change this from false to true
