### ISSUE TITLE
"UpdateRepository: database table is locked" error on git push

### ISSUE THREAD

**Issue by sbourdeauducq** [go-gitea/gitea#13581]
- Gitea version (or commit ref):  1.12.5 
- Git version: 2.28.0
- Operating system: NixOS 20.09.1758.3090c650411
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X] No

## Description

When pushing to a repository, this error happened:

```
Enumerating objects: 22, done.
Counting objects: 100% (22/22), done.
Delta compression using up to 16 threads
Compressing objects: 100% (14/14), done.
Writing objects: 100% (14/14), 1.20 KiB | 1.20 MiB/s, done.
Total 14 (delta 12), reused 0 (delta 0), pack-reused 0
remote: Gitea: Internal Server Error
remote: Failed to Update: m-labs/artiq-zynq Error: CommitRepoAction: UpdateRepository: database table is locked
Gitea: Internal error
UpdatePublicKeyInRepo: Failed to update public key: database table is locked
To git.m-labs.hk:M-Labs/artiq-zynq.git
   32048ea..07b425a  master -> master
error: failed to push some refs to 'git.m-labs.hk:M-Labs/artiq-zynq.git'
```

The git repository otherwise appears to be fine and the push successful, except that some parts of the web interface like the commit list on the Gitea homepage failed to be updated.

This only occurred once during more than a year of using Gitea, and I cannot reproduce it, so I am not sure how debuggable this is at this point. I just wanted to open an issue so that more information can be added later, if I or others experience the same problem. Thanks for developing this nice application.

**Comment by qubist-pixel-ux** [comment]
I experienced it too and now new commits are not shown in web interface. How to fix it ?

**Comment by 6543** [comment]
looks like internal hook's cause a concurrency issue :/

the best workaround is to avoid sqlite3 as dbms

**Comment by qubist-pixel-ux** [comment]
> looks like internal hook's cause a concurrency issue :/
> 
> the best workaround is to avoid sqlite3 as dbms

I restarted gitea then pushed the repository. I can see all commits on gitea.

**Comment by sbourdeauducq** [comment]
Likely duplicate of #14274
