### ISSUE TITLE
500 on org private to public, public to private and public to limited

### ISSUE THREAD

**Issue by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [go-gitea/gitea#13587]
- Gitea version (or commit ref): `Gitea version 1.14.0+dev-224-g586bfb9f3 built with GNU Make 4.3, go1.15.5 : bindata, sqlite, sqlite_unlock_notify`
- Git version: `git version 2.29.2.454.gaff20da3a2`
- Operating system: Arch Linux
- Built from
  - [x] source
- Run with
  - [x] systemd
- Database:
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes

## Description
After setting a private org to public I am met with a 500 (verified both locally and on try.gitea.io).
The same is true for public org set to private or public org set to limited.

https://try.gitea.io/nuoneplstest500
https://try.gitea.io/nuoneplspublic500

links to short videos of the issue
http://ix.io/2Eoa

**Comment by 6543** [comment]
caused by #13475

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
> caused by #13475
> 
> error: `e-mail invalid [email: ]`

right..org cannot have an email so that's a special case.
also, what are the allowed email addresses now as introduced by the subject PR?
