### ISSUE TITLE
Occasional error 500 when trying to view a certain commit

### ISSUE THREAD

**Issue by arnova** [go-gitea/gitea#13583]
- Gitea version (or commit ref): 1.12.5 (downloaded binary)
- Git version: 2.20.1
- Operating system: Debian 10-AMD64
- Gitea running using systemd + nginx proxy + MariaDB
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
- Error in gitea.log:
`
2020/11/16 12:12:07 ...m.io/xorm/core/db.go:154:QueryContext() [I] [SQL] SELECT `id`, `lower_name`, `name`, `full_name`, `email`, `keep_email_private`, `email_notifications_preference`, `passwd`, `passwd_hash_algo`, `must_change_password`, `login_type`, `login_source`, `login_name`, `type`, `location`, `website`, `rands`, `salt`, `language`, `description`, `created_unix`, `updated_unix`, `last_login_unix`, `last_repo_visibility`, `max_repo_creation`, `is_active`, `is_admin`, `is_restricted`, `allow_git_hook`, `allow_import_local`, `allow_create_organization`, `prohibit_login`, `avatar`, `avatar_email`, `use_custom_avatar`, `num_followers`, `num_following`, `num_stars`, `num_repos`, `num_teams`, `num_members`, `visibility`, `repo_admin_change_team_access`, `diff_view_style`, `theme` FROM `user` WHERE `lower_name`=? LIMIT 1 [arnova] - 215.131µs
2020/11/16 12:12:07 ...m.io/xorm/core/db.go:154:QueryContext() [I] [SQL] SELECT `id`, `owner_id`, `owner_name`, `lower_name`, `name`, `description`, `website`, `original_service_type`, `original_url`, `default_branch`, `num_watches`, `num_stars`, `num_forks`, `num_issues`, `num_closed_issues`, `num_pulls`, `num_closed_pulls`, `num_milestones`, `num_closed_milestones`, `is_private`, `is_empty`, `is_archived`, `is_mirror`, `status`, `is_fork`, `fork_id`, `is_template`, `template_id`, `size`, `is_fsck_enabled`, `close_issues_via_commit_in_any_branch`, `topics`, `avatar`, `created_unix`, `updated_unix` FROM `repository` WHERE `owner_id`=? AND `lower_name`=? LIMIT 1 [1 pulse-compressor] - 154.31µs
2020/11/16 12:12:07 ...m.io/xorm/core/db.go:154:QueryContext() [I] [SQL] SELECT `id`, `repo_id`, `type`, `config`, `created_unix` FROM `repo_unit` WHERE (repo_id = ?) [89] - 85.244µs
2020/11/16 12:12:07 ...m.io/xorm/core/db.go:154:QueryContext() [I] [SQL] SELECT count(*) FROM `release` WHERE repo_id=? AND is_draft=? [89 false] - 93.924µs
2020/11/16 12:12:07 ...m.io/xorm/core/db.go:154:QueryContext() [I] [SQL] SELECT max( id ) as id FROM `commit_status` WHERE (repo_id = ?) AND (sha = ?) GROUP BY context_hash ORDER BY max( id ) desc LIMIT 10 [89 340f0e142511c91a7186d444675323c9076d54ac] - 130.7µs
2020/11/16 12:12:07 ...les/context/panic.go:35:1() [E] PANIC:: runtime error: index out of range [4] with length 4
        /usr/local/go/src/runtime/panic.go:88 (0x439ff2)
        /go/src/code.gitea.io/gitea/services/gitdiff/gitdiff.go:452 (0x12ceba6)
        /go/src/code.gitea.io/gitea/services/gitdiff/gitdiff.go:750 (0x12cf18d)
        /go/src/code.gitea.io/gitea/services/gitdiff/gitdiff.go:696 (0x12cfa3c)
        /go/src/code.gitea.io/gitea/services/gitdiff/gitdiff.go:770 (0x12cf9d1)
        /go/src/code.gitea.io/gitea/routers/repo/commit.go:253 (0x19cd21c)
        /usr/local/go/src/reflect/value.go:460 (0x49cf7a)
        /usr/local/go/src/reflect/value.go:321 (0x49c483)
        /go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:177 (0xc2ba8b)
        /go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:137 (0xc2b469)
        /go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:121 (0xc469b8)
        /go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:112 (0x12628d4)
        /go/src/code.gitea.io/gitea/modules/context/repo.go:797 (0x12628bd)
        /usr/local/go/src/reflect/value.go:460 (0x49cf7a)
        /usr/local/go/src/reflect/value.go:321 (0x49c483)
        /go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:177 (0xc2ba8b)
        /go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:137 (0xc2b469)
        /go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:121 (0xc469b8)
        /go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:112 (0x1260fbf)
        /go/src/code.gitea.io/gitea/modules/context/repo.go:579 (0x1260fa8)
        /usr/local/go/src/reflect/value.go:460 (0x49cf7a)
        /usr/local/go/src/reflect/value.go:321 (0x49c483)
        /go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:177 (0xc2ba8b)
        /go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:137 (0xc2b469)
        /go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:121 (0xc469b8)
        /go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:112 (0x125e8b4)
        /go/src/code.gitea.io/gitea/modules/context/panic.go:39 (0x125e8a5)
        /usr/local/go/src/reflect/value.go:460 (0x49cf7a)
        /usr/local/go/src/reflect/value.go:321 (0x49c483)
        /go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:177 (0xc2ba8b)
        /go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:137 (0xc2b469)
        /go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:121 (0xc469b8)
        /go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:112 (0x1216435)
        /go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/session/session.go:192 (0x1216420)
        /go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:79 (0xc46860)
        /go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:157 (0xc2b7b7)
        /go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:135 (0xc2b558)
        /go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:121 (0xc469b8)
        /go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:112 (0xc57e05)
        /go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/recovery.go:161 (0xc57df8)
        /go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/logger.go:40 (0xc4a423)
        /go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:157 (0xc2b7b7)
        /go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:135 (0xc2b558)
        /go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:121 (0xc469b8)
        /go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:112 (0xc57130)
        /go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/logger.go:52 (0xc5711b)
        /go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/logger.go:40 (0xc4a423)
        /go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:157 (0xc2b7b7)
        /go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:135 (0xc2b558)
        /go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:121 (0xc469b8)
        /go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/router.go:187 (0xc59016)
        /go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/router.go:303 (0xc52a15)
        /go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/macaron.go:218 (0xc4b79a)
        /go/src/code.gitea.io/gitea/vendor/github.com/gorilla/context/context.go:141 (0xebd7f3)
        /usr/local/go/src/net/http/server.go:2041 (0x750e63)
        /usr/local/go/src/net/http/server.go:2836 (0x7541f2)
        /usr/local/go/src/net/http/server.go:1924 (0x74fc5b)
        /usr/local/go/src/runtime/asm_amd64.s:1373 (0x46f370)

2020/11/16 12:12:15 ...m.io/xorm/core/db.go:154:QueryContext() [I] [SQL] SELECT user_id, count(*) AS count FROM notification WHERE user_id IN (SELECT user_id FROM notification WHERE updated_unix >= ? AND updated_unix < ?) AND status = ? GROUP BY user_id [1605525123 1605525133 1] - 213.501µs
2020/11/16 12:12:25 ...m.io/xorm/core/db.go:154:QueryContext() [I] [SQL] SELECT user_id, count(*) AS count FROM notification WHERE user_id IN (SELECT user_id FROM notification WHERE updated_unix >= ? AND updated_unix < ?) AND status = ? GROUP BY user_id [1605525133 1605525143 1] - 217.881µs
`

## Description
Every now and then when clicking on a specific commit in the webinterface I get a 500-error. There's no pattern when it occurs but when it occurs with a specific commit it will keep doing that, even when other commits are added.

**Comment by lunny** [comment]
It seems this has been fixed in branch v1.12

**Comment by arnova** [comment]
> It seems this has been fixed in branch v1.12

But there's no 1.12.x release for it yet?

**Comment by lunny** [comment]
Please wait that v1.12.6 is releasing.

**Comment by arnova** [comment]
Ok, will do. Thanks for the info.

**Comment by wxiaoguang** [comment]
Outdated
