### ISSUE TITLE
standard_init_linux.go:178: exec user process caused "exec format error"

### ISSUE THREAD

**Issue by ulm0** [go-gitea/gitea#1358]
- Gitea version (or commit ref):
Docker image with ```latest``` tag from docker hub, built 9 hours ago (at the time of this writing)
- Git version:
2.8.3 bundled within the image
- Operating system:
Container: Alpine 3.4.6
Host: CoreOS Stable channel
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:
```docker logs service_container_name``` outputs: 
```standard_init_linux.go:178: exec user process caused "exec format error"```

## Description
Just updated a gitea instance i have to the latest image available, and the service was unable to start

```docker stack services gitea```:
```
ID            NAME                    MODE             REPLICAS      IMAGE
njn2n9alnrg0  gitea_backend           replicated       0/1           gitea/gitea:latest
mhw4lxjig93e  gitea_db                replicated       1/1           postgres:9.6-alpine
```
When i see the logs ```docker logs service_container_name``` it outputs: 
```standard_init_linux.go:178: exec user process caused "exec format error"```

So i had to roll back the to the ```1.1.0``` tag.

**Comment by techknowlogick** [comment]
Unable to replicate, please re-open if needed
