### ISSUE TITLE
Error 500 when trying to create some pull requests in Gitea 1.12.5+

### ISSUE THREAD

**Issue by parnic-sks** [go-gitea/gitea#13597]
- Gitea version (or commit ref): 1.12.5, 1.12.6
- Git version: 2.29.2.windows.1
- Operating system: Windows Server 2019
Gitea downloaded from GitHub releases. It is being run as a Windows service using nssm.
- Database:
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
- Log gist:
https://gist.github.com/parnic-sks/224a382950f262c220f681f3b7b762fc

## Description
Frequently, when creating a PR on any release higher than 1.12.4, we receive an error 500 followed by `exit status 1` and a long, repeating set of logs
> batch request: missing protocol: ""

Creating the same PR from the same branch on Gitea 1.12.4 works fine. 1.12.5 and 1.12.6 both have this problem 100% for certain branches. Other branches can create PRs without issue. I have not been able to identify the difference that causes some branches to work and others not. We use submodules and LFS, but there doesn't seem to be a common thread between successes and failures.

## Screenshots

When creating the PR:

![image](https://user-images.githubusercontent.com/62021255/99342962-9b211d00-2852-11eb-919a-486a803cca1d.png)

When viewing the PR (one does get created and sends notifications to watchers, but it's empty):
![image](https://user-images.githubusercontent.com/62021255/99343013-b2f8a100-2852-11eb-9cdf-08d9a530e9b9.png)

**Comment by lunny** [comment]
It's related with git-lfs

**Comment by parnic-sks** [comment]
Thanks, @lunny ! Is that the case even if this PR/branch had no LFS-controlled files in the set of changes?

**Comment by zeripath** [comment]
@parnic-sks Sorry this has taken me so long to notice this.

It's clear from your logs that your server is running on Windows.

The error is coming from:

```go
if err := git.Push(headRepoPath, git.PushOptions{
		Remote: baseRepoPath,
		Branch: pr.HeadBranch + ":" + gitRefName,
		Force:  true,
		// Use InternalPushingEnvironment here because we know that pre-receive and post-receive do not run on a refs/pulls/...
		Env: models.InternalPushingEnvironment(pr.Issue.Poster, pr.BaseRepo),
	}); err != nil {
```

This is essentially calling:

```bash
# bashish code
cd $headRepoPath
git push -- $headRepoPath  $prHeadBranch":"$gitRefName
```

My guess is that the headRepoPath which comes from `filepath.Join(filepath.Join(setting.RepoRootPath, strings.ToLower(userName)), strings.ToLower(repoName)+".git")` doesn't look reasonable to git.

Now `setting.RepoRootPath` comes from:

```
	RepoRootPath = sec.Key("ROOT").MustString(path.Join(homeDir, "gitea-repositories"))
	forcePathSeparator(RepoRootPath)
	if !filepath.IsAbs(RepoRootPath) {
		RepoRootPath = filepath.Join(AppWorkPath, RepoRootPath)
	} else {
		RepoRootPath = filepath.Clean(RepoRootPath)
	}
```

From your logs it looks like that that is set to `d:\gitea\data\repositories\` ?

So that leaves a few questions:

* Does changing the ROOT to use forward-slashes make it work? 
* Which type of git are you using?
* Would you be able to replicate the command on a command line to work out how it would need to be changed to make it work?

**Comment by parnic-sks** [comment]
Worked through this with @zeripath on Discord and the issue was identified as an LFS problem, just as @lunny thought. The repo in question had several hooks installed, specifically a `pre-push` hook, that was causing LFS to try and upload if there were LFS-controlled file changes between the source and target branch.

The local fix we came up with was to delete the `pre-push` hook as well as any other hooks in the gitea repo that were calling out to LFS to do anything. It's unclear how these hooks got there in the first place, so there's probably some user error involved. It would be nice if Gitea could present this info to the user in some way, but for now this fix gets us unstuck.

@zeripath also identified #12839 as the likely cause of this being the reason it appears in 1.12.5 and not 1.12.4 since the clone would not have brought the hooks over, thereby bypassing the issue.

Thanks a ton to @zeripath for helping me through this on Discord and @lunny for the original quick diagnosis!

**Comment by zeripath** [comment]
I'm gonna close this as repositories created by Gitea should not have git LFS hooks installed. Hopefully your comment above should be enough to fit anyone else who experienced this in future to work out how to fix.

**Comment by NepPure** [comment]
> I'm gonna close this as repositories created by Gitea should not have git LFS hooks installed. Hopefully your comment above should be enough to fit anyone else who experienced this in future to work out how to fix.

@zeripath 

I removed `hooks/pre.push`, everything seems ok.

But I still wonder, what is the correct way to use LFS in Gitea?

**Comment by zeripath** [comment]
Gitea is its own lfs server. As a client you just use LFS as normal - but Gitea's own copy of the repositories must not have LFS hooks installed.

**Comment by NepPure** [comment]
> Gitea is its own lfs server. As a client you just use LFS as normal - but Gitea's own copy of the repositories must not have LFS hooks installed.

Thank you very much, I understand.
