### ISSUE TITLE
Telegram Webhook add Custom api url [Feature Request]

### ISSUE THREAD

**Issue by mrbesen** [go-gitea/gitea#13592]
Telegram introduced a new [selfhosted telegramApi](https://core.telegram.org/bots/api#november-4-2020) to use that you need to specify a api-url (instead of `https://api.telegram.org/bots` you may want ot do something like this: `http://127.0.0.1:8080/bot`)
It would be helpful to add a text input in the webinterface to enter a custom url maybe with the default api as placeholder.

I could get it working by just replacing all the apiurls in the database by hand, so i guess a little Webinterface tweak should do the trick.

**Comment by alexanderadam** [comment]
I guess this could easily be done by your own, once [custom webhook templates are integrated](https://github.com/go-gitea/gitea/issues/1089).
But this probably will still take a while… :wink:

**Comment by techknowlogick** [comment]
Closing in favour of https://github.com/go-gitea/gitea/issues/1089
