### ISSUE TITLE
Code Owner Review

### ISSUE THREAD

**Issue by keinou** [go-gitea/gitea#13603]
Add the need for the code owner to review before the merge.

**Comment by jolheiser** [comment]
This can be accomplished via branch protection or manually requesting for review.

**Comment by keinou** [comment]
It is possible to add the reviewer via api?

**Comment by jolheiser** [comment]
It will be available in 1.14 with #11355 
https://try.gitea.io/api/swagger#/repository/repoCreatePullReviewRequests
