### ISSUE TITLE
Failed to open profile page, /explore/repos ,own repositry list in empty

### ISSUE THREAD

**Issue by kuznetz** [go-gitea/gitea#13605]
- Gitea version (or commit ref): 1.12.6 
- Git version: 2.24.3
- Operating system: official docker, hosted on Debian GNU/Linux 10 (buster)
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
- Log gist:
2020/11/17 19:10:00 ...les/context/panic.go:35:1() [E] PANIC:: unrecognized repo unit type: 8
	/go/src/code.gitea.io/gitea/models/repo_unit.go:132 (0x11b3282)
	/go/src/code.gitea.io/gitea/vendor/xorm.io/xorm/session.go:409 (0xbf6ada)
	/go/src/code.gitea.io/gitea/vendor/xorm.io/xorm/session.go:374 (0xbf655e)
	/go/src/code.gitea.io/gitea/vendor/xorm.io/xorm/session_find.go:232 (0xc0acee)
	/go/src/code.gitea.io/gitea/vendor/xorm.io/xorm/session_find.go:148 (0xc09e2e)
	/go/src/code.gitea.io/gitea/vendor/xorm.io/xorm/session_find.go:31 (0xc09523)
	/go/src/code.gitea.io/gitea/models/repo_unit.go:174 (0x11b36ef)
	/go/src/code.gitea.io/gitea/models/repo.go:407 (0x1188523)
	/go/src/code.gitea.io/gitea/models/repo_permission.go:186 (0x11aec39)
	/go/src/code.gitea.io/gitea/models/repo_permission.go:142 (0x19ee100)
	/go/src/code.gitea.io/gitea/routers/repo/http.go:256 (0x19ee132)
	/usr/local/go/src/reflect/value.go:460 (0x49d38a)
	/usr/local/go/src/reflect/value.go:321 (0x49c893)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:177 (0xc3275b)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:137 (0xc32139)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:121 (0xc4d688)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:112 (0x1265f34)
	/go/src/code.gitea.io/gitea/modules/context/panic.go:39 (0x1265f25)
	/usr/local/go/src/reflect/value.go:460 (0x49d38a)
	/usr/local/go/src/reflect/value.go:321 (0x49c893)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:177 (0xc3275b)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:137 (0xc32139)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:121 (0xc4d688)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:112 (0x121d105)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/session/session.go:192 (0x121d0f0)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:79 (0xc4d530)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:157 (0xc32487)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:135 (0xc32228)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:121 (0xc4d688)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:112 (0xc5ead5)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/recovery.go:161 (0xc5eac8)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/logger.go:40 (0xc510f3)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:157 (0xc32487)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:135 (0xc32228)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:121 (0xc4d688)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:112 (0x1b7cf2c)
	/go/src/code.gitea.io/gitea/routers/routes/routes.go:103 (0x1b7cf17)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:79 (0xc4d530)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:157 (0xc32487)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:135 (0xc32228)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:121 (0xc4d688)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/router.go:187 (0xc5fce6)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/router.go:303 (0xc596e5)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/macaron.go:218 (0xc5246a)
	/go/src/code.gitea.io/gitea/vendor/github.com/gorilla/context/context.go:141 (0xec44c3)
	/usr/local/go/src/net/http/server.go:2041 (0x756e33)
	/usr/local/go/src/net/http/server.go:2836 (0x75a1c2)
	/usr/local/go/src/net/http/server.go:1924 (0x755c2b)
	/usr/local/go/src/runtime/asm_amd64.s:1373 (0x46f780)

## Description

After switch from latest Docker to 1.12, not opening profile page, /explore/repos. Showing message:
**template: explore/repo_list:32:9: executing "explore/repo_list" at <.DescriptionHTML>: error calling DescriptionHTML: unrecognized repo unit type: 8**

List own repos on main pasge also broken: showing 0 repos, ajax return return 500.:
/api/v1/repos/search?sort=updated&order=desc&uid=1&q=&page=1&limit=15&mode=&archived=false

But collaborative repos is ok:
/api/v1/repos/search?sort=updated&order=desc&uid=1&q=&page=1&limit=15&mode=collaborative&exclusive=1&archived=false

**Comment by duchenpaul** [comment]
Same here, and when I fall back to  1.12.3, own repositry list in empty remains.
Linus hosted, not docker

**Comment by duchenpaul** [comment]
Use version [1.13.0-rc2](https://dl.gitea.io/gitea/1.13.0-rc2) instead

**Comment by zeripath** [comment]
Have you at some point updated to 1.13 and then downgraded to 1.12?

**Comment by duchenpaul** [comment]
> Have you at some point updated to 1.13 and then downgraded to 1.12?
Nope, I feel confortable at 1.13 😃

**Comment by kuznetz** [comment]
>Have you at some point updated to 1.13 and then downgraded to 1.12?
I create another issue for version 1.13.0+rc2, (#13718), it consumes all memory, and then not processing requests from git or start working too slow. That's why i trying downgrade to 1.12

**Comment by zeripath** [comment]
OK the issue is that there are data migrations between 1.12 and 1.13. These are not compatible with 1.12 and downgrading is not supported. 

You have to restore from the backup that you made before you updated to 1.13.

If you haven't made backups - well... you're gonna have to manually back out the changes made with the migrations between 1.12 and 1.13 - I'm not going to go into those here - you can ask for help on discord.

In terms of the problem you're experiencing on 1.13-rc2 - well I've made a comment on that issue - really we need logs.
