### ISSUE TITLE
ssh  connect to host xx port 3022: Operation timed out

### ISSUE THREAD

**Issue by leo-lu** [go-gitea/gitea#13608]
- Gitea version (or commit ref): 1.12.6
- Git version: 1.8.3.1
- Operating system:
    from docker.
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x ] No

    ssh  connect to host xx port 3022: Operation timed out.  Custom ports never work~

    Please help me. 
    Thank you!

**Comment by techknowlogick** [comment]
Can you use netstat to ensure that something is listening on 3022, or could be that the firewall is blocking the request.
