### ISSUE TITLE
[error] Sudden run flash back on the SQLite database

### ISSUE THREAD

**Issue by ZhangJiaLei123** [go-gitea/gitea#13616]
Today I found that my gitea Server has suddenly stopped.But looking at the log file, no exception information was found.
So I created a [gitEA Server], and found that after normal operation, I replaced the wrong service database with the normal one, and found that the service using the new data could run normally, while the service using the original database would flash back and fail to run.
There is no information for [e] in the log file.

**Comment by lunny** [comment]
Are there any logs when you run gitea failed?
