### ISSUE TITLE
Unrelated validation error while trying to upload organization avatar

### ISSUE THREAD

**Issue by Palethorn** [go-gitea/gitea#13617]
- Gitea version (or commit ref): Docker image gitea/gitea:latest, Gitea version 1.14.0+dev-233-g0615b668d built with GNU Make 4.3, go1.15.5 : bindata, timetzdata, sqlite, sqlite_unlock_notify
- Git version: git version 2.26.2
- Operating system: ArchLinux Host Docker version 19.03.13, build 4484c46d9d
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (https://try.gitea.io/org/wizzard405_yahoo_com/settings)
  - [ ] No
- Log gist:

https://gist.github.com/Palethorn/febb4d5d8757488c98273cd8077cf05f
## Description
Action returns validation error message: UploadAvatar: updateUser: e-mail invalid [email: ]
...

## Screenshots
![Screenshot_20201118_120403](https://user-images.githubusercontent.com/671689/99522631-2ce57300-2996-11eb-9c7b-b5feec60cd71.png)

**Comment by andreyddk** [comment]
I have same problem.

**Comment by 6543** [comment]
closed by #13627
