### ISSUE TITLE
BUG-Wrong feedback about oauth2's authentication source configuration mastodon

### ISSUE THREAD

**Issue by trainliang** [go-gitea/gitea#13636]
- Gitea version (or commit ref):
- Git version:
- Operating system:
  
  
  
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
- Log gist:

## Description

1. The interface cannot be updated after the authentication is derived from the definition URL modification;
2. The icon cannot be customized in the background of the self-built oauth2 server;
3. The own oauth2 server returns code but the page prompts a 500 error

## Screenshots

![20201119164527](https://user-images.githubusercontent.com/31426676/99643930-41a23380-2a88-11eb-99c3-b8416edca4a4.png)

**Comment by techknowlogick** [comment]
Are you able to provide any logs?

**Comment by trainliang** [comment]
This version has been updated, the log data is not currently available

**Comment by techknowlogick** [comment]
We are unable to assist you if you do not provide details. Please complete the default issue template, and to provide logs here is some documentation on how to do that: https://docs.gitea.io/en-us/logging-configuration/#debugging-problems

until then I will close this issue, please re-open once you have provided the needed details.
