### ISSUE TITLE
Issue - heatmap is mini-heatmap

### ISSUE THREAD

**Issue by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [go-gitea/gitea#13634]
- Gitea version (or commit ref): `Gitea version 1.14.0+dev-239-gad2a28862 built with GNU Make 4.3, go1.15.5 : bindata, sqlite, sqlite_unlock_notify`
- Git version: `git version 2.29.2.497.ga2da47d1e7`
- Operating system: Arch Linux
- Built from:
  - [x] source
- Run with:
  - [x] systemd
- Database:
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes

## Description
Appears to be introduced by #13623 .
The issue is that the heatmap appears really small.
I have tried to reproduce it in chromium, firefox and brave (chromium-based) and this issue only pertains in chromium (consistently).
For the user dashboard to pop up you have to be logged in, in chromium, though, you can also see the issue when navigating to user's 'Public Activity' page (https://try.gitea.io/kjhfdskahhjksdf?tab=activity), for which you, obviously, don't have to be logged in.

## Screenshots
my instance
![image](https://user-images.githubusercontent.com/61180606/99638383-7097b580-2a46-11eb-911e-218b2882a18e.png)
try.gitea.io logged in (Public Activity) pic1
![image](https://user-images.githubusercontent.com/61180606/99640463-3380f280-2a49-11eb-9b9b-cc7eb53642fd.png)
try.gitea.io logged in (dashboard) pic2
![image](https://user-images.githubusercontent.com/61180606/99640543-51e6ee00-2a49-11eb-9b83-400651de298d.png)
try.gitea.io logged out (activity)
![image](https://user-images.githubusercontent.com/61180606/99641311-61b30200-2a4a-11eb-9e56-bff0d44fbd05.png)

edit: missing parenthesis (image not showing properly)
edit2: add blame

**Comment by 6543** [comment]
@wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf I dont have this issue :/ it looks like you have to clear your browser cache

**Comment by 6543** [comment]
@silverwind some sort of chrome css incompatiblety?

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
> @wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf I dont have this issue :/ it looks like you have to clear your browser cache

I already did...

**Comment by 6543** [comment]
@wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf sorry - didnt read the " ... chrome ..."  the first time ...

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
> @wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf sorry - didnt read the " ... chrome ..." the first time ...

no worries.
and I only tried chromium.
don't use chrome so can't confirm it's present there (since the issue is e.g. not present in chromium-based brave).

**Comment by silverwind** [comment]
I think I only tested this in Firefox if I recall correctly.

**Comment by bkraul** [comment]
Any chance #13645 be merged soon? I'd be happy with the current heatmap if I was an ant right now, but since I am not... 🙂

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
> Any chance #13645 be merged soon? I'd be happy with the current heatmap if I was an ant right now, but since I am not...

for now, you could build Gitea with the patch (that's what I've done)...
```sh
cd gitea-src-folder
curl -O https://patch-diff.githubusercontent.com/raw/go-gitea/gitea/pull/13645.patch
git am 12645
make build # specify desired TAGS before this...
```
@bkraul
