### ISSUE TITLE
Recommendation-About custom configuration and automatic docker update deployment

### ISSUE THREAD

**Issue by trainliang** [go-gitea/gitea#13635]
- Gitea version (or commit ref):
- Git version:
- Operating system:
  
  
  
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
- Log gist:

## Description

The interface configuration is persistent. At present, docker deployment and watchtower are automatically updated, but the home page cannot be customized, so the application cannot serve externally well.

**Comment by lafriks** [comment]
You can mount volume for custom folder that can be used to place customized files and won't be lost between updates
