### ISSUE TITLE
Disabling signup in the web installer doesn't disable signups through OpenID

### ISSUE THREAD

**Issue by Schnouki** [go-gitea/gitea#1363]
- Gitea version (or commit ref): 1.1.0+66-gc05bd178 (via Docker)
- Git version: 2.8.3
- Operating system: Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:

## Description

I installed Gitea through Docker on my laptop. During the initial configuration, I disabled signup through the web interface. There was nothing about OpenID. As expected, when logged out, there's no "signup" button, only "sign in".

However, I was able to login through OpenID. As the OpenID was unknown, I was redirected to a page where I could choose between connecting this ID to an existing account, or creating a new account. Using this form I was able to create a new account on my local instance, even if signup is disabled.

I checked the config file, and sure enough there was no `[openid]` section.

After creating a new instance and re-running the setup, I edited the config file and added the following:

    [openid]
    ENABLE_OPENID_SIGNUP = true

(as seen [here](https://github.com/go-gitea/gitea/blob/f00a4c8078a74a6cdf64e902b7c8952e3bf4c18c/conf/app.ini#L206))
which fixed the issue.

So:
- either the web installer should include a section about OpenID, and make it possible to disable OpenID and/or signups,
- or the global `DISABLE_REGISTRATION` flag should also disable OpenID signups.

Thanks!

## Screenshots

Disabling signup during setup:
![2017-03-22-09_36_08](https://cloud.githubusercontent.com/assets/64833/24189119/18bad378-0ee4-11e7-8fdf-07de8da68ad1.png)

Login with OpenID:
![2017-03-22-09_37_01](https://cloud.githubusercontent.com/assets/64833/24189139/2949bb00-0ee4-11e7-9e2c-4f464bb54d24.png)

Create new account with OpenID:
![2017-03-22-09_37_29](https://cloud.githubusercontent.com/assets/64833/24189148/3200e250-0ee4-11e7-98b0-ea63ddf3f8de.png)

Logged in!
![2017-03-22-09_38_05](https://cloud.githubusercontent.com/assets/64833/24189158/3a443520-0ee4-11e7-9582-33d17fe1cb93.png)

**Comment by strk** [comment]
This was actually meant to be a feature, as someone theorized that
spammers would less likely setup an OpenID service.

But I'll agree now that if a "DISABLE_REGISTRATION" variable exists
it should probably be global. That means we'd still need another
variable to allow sysadmin to only allow registration via OpenID
(which is an interesting excercise for some crazy ones, like me :)

**Comment by strk** [comment]
BTW, you meant you added `ENABLE_OPENID_SIGNUP = false`, right ? (not `= true`)
I also agree the option should be presented at install time. I'll give that a try now.

**Comment by strk** [comment]
@Schnouki please see how you like #1365

**Comment by Schnouki** [comment]
Yeah I doubt that spammers use OpenID :)
But allowing OpenID would break my use case: I want to self-host a tiny gitea instance with just a few repositories of mine, but without allowing *anyone* else to create an account... I don't want to host their repositories :)

I agree that `DISABLE_REGISTRATION` should be global. If you need some help I can have a look at it (but someone who's familiar with the code will definitely be faster).

Thanks!

**Comment by strk** [comment]
Lets continue discussion in #1365

**Comment by strk** [comment]
So in #1369 I made the code just honor the `DISABLE_REGISTRATION` global *unless* `ENABLE_OPENID_SIGNUP` setting is present, in which case it drives the behavior.
