### ISSUE TITLE
Howto display source code of markdown files?

### ISSUE THREAD

**Issue by fhgd** [go-gitea/gitea#13640]
When I browse through the file tree of my repo I find some markdown files (*.md). And when I click on it they are rendered (bold head lines, nice bullet lists, and so on...) which is nice for the most cases.

But in my case I just want to see the plain source code of the *.md file. How can I switch?

**Comment by khmarbaise** [comment]
usually in the upper area there are shown links "Raw Permalink Blame History" just use `RAW` than you see the source code of the markdown file.

**Comment by fhgd** [comment]
Unfortunately, no. For example, on

https://gitea.com/gitea/tea/src/branch/master/CHANGELOG.md

you see the rendered md-file which is nice. But when you click on the first raw-button you get nearly the same rendered result and not the source code of the md-file.

The only work-around for the source code is the blame-button but it could be hard to read.

**Comment by khmarbaise** [comment]
I see in your example in the line "3.4 KiB" going to the right those links see the image `Raw Permalink Blame History`
![rendered md](https://user-images.githubusercontent.com/42484/99673837-87a1cc00-2a75-11eb-9d90-6b4ff619c6f6.png)

**Comment by khmarbaise** [comment]
I checked the output of the "Raw" link and I get correctly the source code of the markdown file?... Maybe you have installed a markdown plugin in your browser? 

![source-markdown](https://user-images.githubusercontent.com/42484/99674305-2b8b7780-2a76-11eb-9330-3a101301a1ac.png)

**Comment by fhgd** [comment]
Oh, you are right - when I deactivated the markdown add-on I get the same raw output as you. Many thanks for that advice!

Nonetheless, I would like to propose an extra source-code-button next to the raw-button which displays the file with line numbers and syntax highlighting. Is there an existing configuration option for that or is it a new feature request?

**Comment by lunny** [comment]
For those files who can be rendered, it will be rendered when you visit the file. For other text files, it will be a highlight code review. So I think it's may useful sometimes to view a hightlight code of the markdown file.

@jolheiser I think this should be a proposal but not a question. I will change that.

**Comment by silverwind** [comment]
Essentiall this needs a rendered/source view, similar to SVG files which also suffer from this issue.

**Comment by wxiaoguang** [comment]
Fixed by
* https://github.com/go-gitea/gitea/pull/19356
