### ISSUE TITLE
Filtering in Pull Request kept all the time.

### ISSUE THREAD

**Issue by khmarbaise** [go-gitea/gitea#13641]
- Gitea version (or commit ref):  1.14.0+dev-239-gad2a28862
- Git version: See try.gitea.io (also 1.13.0-rc2)
- Operating system:
   - See try.gitea.io

- Database (use `[x]`):
  - [x ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes 
  - [ ] No
  URL to reproduce: https://try.gitea.io/khmtestorga/testrepo/pulls
 
## Description
If you goto the URL for the pull request you see a list (in this case exactly one) of pull request.

Now you can filter those entries by the Type as shown in the image:

![pull-reqest-1](https://user-images.githubusercontent.com/42484/99683046-34814680-2a80-11eb-8eed-cc08ce898a94.png)

After the selection (as shown next) you will not see any entry which is perfectly fine:

![pull-request-2](https://user-images.githubusercontent.com/42484/99683247-6c888980-2a80-11eb-93db-2cbbae33c7c2.png)

But now the problem arises: If you select from the "Type" -> `All Issues` the result kept empty in contradiction to before cause there was exactly one entry: (See the screen shot):

![pull-request-3](https://user-images.githubusercontent.com/42484/99683565-c721e580-2a80-11eb-9bef-89e3c4e12fcc.png)

Any selection of the filters does  not change the filter given in the URL (as you can see in the last screen shot) which results in not being able to remove all the filters and going back to the beginning with the plain url `https://try.gitea.io/khmtestorga/testrepo/pulls` ...which can only be achieved if you manually select a complete different part and going back to pull requests.... 

The point seemed to be that if I select of "Type" -> "Assigned to you" a parameter `assignee=42393` will be added to the URL. But that parameter can not be removed via "Type" -> "All Issues". 

This can only be achieved if I select from "Assignee" manually "All Assignees" ... 

Selecting the "Type->All Issues" could set the `assignee=0` in the URL. This would resolve this inconvenience? 

The question is: Is this a bug or intended behaviour?

**Comment by jolheiser** [comment]
This is a bug. 
It happens because in the template we are setting the assignee to the signed in user and it never gets cleared until the URL is changed.

https://github.com/go-gitea/gitea/blob/ad2a288622c7bbf53b8670e136e2e1418331b121/templates/repo/issue/list.tmpl#L96

What we should do is switch to using the same logic the other filters use

https://github.com/go-gitea/gitea/blob/ad2a288622c7bbf53b8670e136e2e1418331b121/routers/repo/issue.go#L128-L135

I should be able to make a PR for this later today (or anyone else is welcome to as well!) 🙂

**Comment by khmarbaise** [comment]
If it would be ok I would like to take a look.....

**Comment by jolheiser** [comment]
> If it would be ok I would like to take a look.....

Absolutely!
