### ISSUE TITLE
Migration failed due to "Data too long"

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#13648]
gitea version: 1.14.0+dev-241-gd9c445de1
DBMS: 10.5.8-MariaDB

Migrate source: https://gitlab.com/Remmina/Remmina

Error: `Migrate repository from https://gitlab.com/Remmina/Remmina failed: Error 1406: Data too long for column 'content' at row 1`
Log:
```
2020/11/19 21:28:52 ...ules/task/migrate.go:65:func1() [E] DeleteRepository: Error 1205: Lock wait timeout exceeded; try restarting transaction    
2020/11/19 21:28:52 modules/task/task.go:51:handle() [E] Run task failed: Error 1406: Data too long for column 'content' at row 1
```

**Comment by wxiaoguang** [comment]
Already fixed
