### ISSUE TITLE
Misleading reason, why merging a PR is blocked

### ISSUE THREAD

**Issue by ckittl** [go-gitea/gitea#13655]
- Gitea version (or commit ref): 1.12.1
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (https://try.gitea.io/ckittl/PRMergeBlockedMessage/pulls/1)
  - [ ] No

_Sorry, cannot answer the following information, as I'm not hosting the Gitea instance myself. AFAIK, it doesn't play a role either._

- Git version:
- Operating system:
- Database
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Log gist:

## Description

With #9592, blocking merging a pull request was enabled, if one reviewer requested changes on the code. However, with ef89e75d0eb232e98ca7a7ef278b8681c7f4fe50 (regarding #10756) the checks got extended to also cover the case if one explicitly requested reviewer hasn't given any comments yet. I feel a bit confused about this in two ways.

Think of the following test case (cf. also the test repo):

- Globally I require at least 1 review
- In a specific PR I ask two people to review
- One hasn't answered, yet. The other has approved without any change request

### The information, why merging is blocked is misleading
As far as I was able to get from your code, the reason, why a pull request merge is blocked, is determined here:

https://github.com/go-gitea/gitea/blob/1bb5c09b5d973ac184922380b1e6379875ac5fa7/routers/repo/issue.go#L1435-L1445

However, obviously the condition is true also, if nobody requested changes, but still one of the explicitly requested reviewers didn't answer yet. This leads to the misleading prompt, that requested changes not have been addressed, yet.

My suggestion would be to spin of `Branch#MergeBlockedByExplcitReviewRequest` from  `Branch#MergeBlockedByRejectedReview` and have both conditions separated.

### The explicit review request override my global config
As with GitHub, I would expect, that everything is fine to be merged, as long as one reviewer has replied with approval. However, current implementation blocks the merge with no need. Despite me not finding it handy to require all requested reviews, at least it is not clear, that this is the case. Maybe a renaming of the label for review requests from "Reviewers" to "Mandatory Reviewers" would point out clearly, what it's about (cf. Screenshot).

## Screenshots

![image](https://user-images.githubusercontent.com/44838605/99802889-c482c700-2b38-11eb-8d6e-16cf22220b99.png)

**Comment by davidsvantesson** [comment]
It would be better to only add a warning "Not all requested reviewers have reviewed.", but still allow merge. As it was anyhow the writer of the PR that made the review requests.

**Comment by 6543** [comment]
I think this is an expected behaviour ...

and repoAdmins + requested reviwer can dismiss request to review if needed.

**Comment by 6543** [comment]
@ckittl you you propose to allow a review-request-creator to dismis those requests he had maid?

**Comment by ckittl** [comment]
> @ckittl you you propose to allow a review-request-creator to dismis those requests he had maid?

Thank you for your consideration, @6543! I think, revoking a review request is still possible, yet. I don't really bother about the pull request being blocked. If this is intended behaviour, I'm fine with it. It is just that I didn't _expect_ this behaviour, as it is different for famous github. I would more wish for a clarification, by e.g. renaming the headline shown in the screenshot I made.

**Comment by wxiaoguang** [comment]
Outdated, the code has changed a lot
