### ISSUE TITLE
Not all text showing in issue 'Edit'-mode

### ISSUE THREAD

**Issue by aschrijver** [go-gitea/gitea#13652]
- Gitea server: [Codeberg](https://codeberg.org)
- Gitea version (or commit ref): v1.12.6

## Description

This is a minor issue. I keep track of [delightful-funding](https://codeberg.org/teaserbot-labs/delightful-funding) resources in [an issue](https://codeberg.org/teaserbot-labs/delightful-funding/issues/1) that I regularly update with new entries.

Recently when clicking 'Edit' the text-entry window no longer shows the full text. The full text only appears after a click inside the input area. After this a subsequent Save or Cancel and pressing Edit again will yield all text as expected, but after reloading the page the issue can again be reproduced.

I am using Firefox 73.0.1 on Ubuntu 18.

(Note: I created an issue at Codeberg that points to this: https://codeberg.org/Codeberg/Community/issues/338 )

## Screenshots

![codeberg-gitea-bug-edit-issue-text-missing](https://user-images.githubusercontent.com/5111931/99769652-ed8a6400-2b06-11eb-84b8-6c683a48b316.png)

**Comment by silverwind** [comment]
Probably another one of those EasyMDE/SimpleMDE bugs. Long term solution will be https://github.com/go-gitea/gitea/issues/10729 and I plan to take a shot at that soon.

**Comment by corneliusroemer** [comment]
Thanks for working on a long term solution @silverwind - what do you estimate the timeline to be?

Is there a short-term solution for fixing SimpleMDE bugs? Why did you give up on EasyMDE?

**Comment by wxiaoguang** [comment]
This issue seems pretty old, maybe it has been fixed?

And the edit mode has been switched to editable content mode and deployed on try.gitea.io

Feel free to try it and report bugs.

**Comment by aschrijver** [comment]
Thank you. Yes, this is the right action. I have not experienced the issue anymore and also closed the downstream Codeberg issue that is related.
