### ISSUE TITLE
500 with "UpdateUser: e-mail invalid [email: ]" when updating org

### ISSUE THREAD

**Issue by silverwind** [go-gitea/gitea#13653]
- Gitea version (or commit ref): latest master

## Description

When updating a org like https://try.gitea.io/org/silverwind-org/settings and trying to set description or full name, a 500 is seen on save and the org settings are not saved. In the log I see 

````
...uters/org/setting.go:94:SettingsPost() [E] UpdateUser: e-mail invalid [email: ]
````

The form does not contain a email field. Probably affects 1.13 and 1.14.

**Comment by mrsdizzie** [comment]
Is this fixed by https://github.com/go-gitea/gitea/pull/13627 ?

**Comment by 6543** [comment]
yes it will be :)
