### ISSUE TITLE
live issue comments / chats

### ISSUE THREAD

**Issue by jcw** [go-gitea/gitea#13650]
On GitHub, issues and their comments are "live". You can keep an issue page open, and use it as a chat. This is most convenient for active discussion such as bug resolution, but also for discussing new features, design choices, etc.

I may have missed it, but as far as I can tell Gitea (1.12.x) does not support this.

It may involve a lot of work, since it needs a real-time WebSocket or SSE connection, so my first question is simply: is this feature being considered? Or does the upcoming Kanban subsystem have such a capability, perhaps? With source code + issues + wiki, Gitea is already a fairly complete self-hostable system. Live chat, with the issue tracker doing so much of the heavy-lifting (notifications & image uploads), would in my opinion make Gitea an even more complete and self-supporting setup.

I for one, would be thrilled to see this capability come to Gitea.

**Comment by anbraten** [comment]
similar to #2287
