### ISSUE TITLE
Mirrors without matching default branch are shown as empty

### ISSUE THREAD

**Issue by alexanderadam** [go-gitea/gitea#13654]
- Gitea version (or commit ref): `1.14.0+dev-243-g1bb5c09b5`

## Description

If a mirror without matching default branch are shown like empty repositories.
You can compare these two for instance:

**source:** https://git.baguette.netlib.re/Baguette/networkctl
**mirror:** https://try.gitea.io/alexanderadam/git-baguette-netlib-re-Baguette-networkctl

**Comment by 6543** [comment]
when I try to clone localy (`git clone https://git.baguette.netlib.re/Baguette/networkctl`): 

`warning: remote HEAD refers to nonexistent ref, unable to checkout.`

and get an empty directory (`.git` as only content)

I manualy have to `checkout dev` to see the content

note https://git.baguette.netlib.re is "1.12.4"

**Comment by 6543** [comment]
@alexanderadam if you are the owner of git.baguette.netlib.re, can you move to 1.12.6, create a second branch (temporary), set default branch to tmporary branch and back to dev?

**Comment by alexanderadam** [comment]
I'm not the owner of the instance

**Comment by 6543** [comment]
if normal git can't get the default branch ether - how should gitea?
