### ISSUE TITLE
Render issue references in pull request titles as clickable links

### ISSUE THREAD

**Issue by jpraet** [go-gitea/gitea#13658]
- Gitea version: 1.12.6
- Operating system: docker
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (https://try.gitea.io/jpraet/test/pulls/2)
  - [ ] No

## Description

Issue references in pull request titles are currently not rendered as clickable links. It would be nice if this could be implemented, just like they are rendered as clickable links in commit messages and review comments. In my particular case I am using an external issue tracker. But it doesn't work when using the internal issue tracker either.

## Screenshots

![image](https://user-images.githubusercontent.com/2212615/99817593-6c09f480-2b4d-11eb-8d13-8b712c5fa001.png)

and in the pull request list view as well:

![image](https://user-images.githubusercontent.com/2212615/99817732-98be0c00-2b4d-11eb-92a1-4f4164382ff1.png)

**Comment by 6543** [comment]
If you like just send a pull
