### ISSUE TITLE
Issue search for part of a word, case sensitivity

### ISSUE THREAD

**Issue by johannes-nivus** [go-gitea/gitea#13663]
- Gitea version (or commit ref): 1.12.5 built with GNU Make 4.1, go1.14.9
- Git version: 2.25.1
- Operating system:  Ubuntu 20.04.1 LTS, no docker
  
  
  
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
- Log gist:

## Description
Searching for parts of a word in Issues is not possible. I tried both bleeve and db as indexer. Even worse: Using db, the search becomes case sensitive.
Since elastic search seems to have this problem as well (see #11977), I have not tried this yet.

For us it's really a problem, since German language uses many compound nouns. And you would always have to search for the exact composition now.

Since it seems to work in https://try.gitea.io, which search indexer and which database is used there?

## Screenshots
All screenshots done with db as indexer, but search for part of word is not possible with bleeve as well.
![Temperatur](https://user-images.githubusercontent.com/19533883/99872313-43333f00-2be1-11eb-8174-5f98ef66d34c.PNG)
![Temp](https://user-images.githubusercontent.com/19533883/99872306-39114080-2be1-11eb-8bbf-6ecb420233d4.PNG)
![Temperatur_small](https://user-images.githubusercontent.com/19533883/99872316-462e2f80-2be1-11eb-9f57-def248b8c35e.PNG)

**Comment by lunny** [comment]
try.gitea.io use sqlite as database.

**Comment by johannes-nivus** [comment]
> 
> 
> try.gitea.io use sqlite as database.

Is there a possibility to migrate an existing database from postgres to sqlite? I had only chosen Postgres because of a parallel Open Project installation.

**Comment by johannes-nivus** [comment]
Attention: I have neither experience with databases nor with go.
But nevertheless a question:
What would need to be done to use pg_trgm and the % operator for issue searching? Am I right that currently LIKE is used (which would explain the sudden case sensitivity with postgresql)?
If this would be possible at all, it would be nice to have this configurable in app.ini.

**Comment by johannes-nivus** [comment]
> Is there a possibility to migrate an existing database from postgres to sqlite? I had only chosen postgres because of a parallel Open Project installation.

I managed to migrate from postgres to sqlite, by using
```./gitea dump -c /path/to/app.ini -d sqlite3```
Then I extracted only the database dump and used
```sqlite3 gitea.db <gitea-db.sql```
After editing app.ini and restarting gitea everything is working for now.

**Comment by ngugcx** [comment]
Why is part-word search not supported when using Postgres?

**Comment by ngugcx** [comment]
> > Is there a possibility to migrate an existing database from postgres to sqlite? I had only chosen postgres because of a parallel Open Project installation.
> 
> I managed to migrate from postgres to sqlite, by using
> `./gitea dump -c /path/to/app.ini -d sqlite3`
> Then I extracted only the database dump and used
> `sqlite3 gitea.db <gitea-db.sql`
> After editing app.ini and restarting gitea everything is working for now.

Did you meet this problem?
```
bash-5.0$ sqlite3 gitea.db <gitea-db.sql
Error: near line 16: no such function: setval
Error: near line 23: no such function: setval
Error: near line 30: no such function: setval
Error: near line 72: no such function: setval
Error: near line 78: no such function: setval
Error: near line 84: no such function: setval
Error: near line 116: no such function: setval
Error: near line 120: no such function: setval
Error: near line 153: no such function: setval
Error: near line 157: no such function: setval
Error: near line 161: no such function: setval
Error: near line 1380: no such function: setval
```

**Comment by lunny** [comment]
> Why is part-word search not supported when using Postgres?

part word should have been supported by Postgres but not Case sensitivity. Maybe we need a PR to improve issue db indexer to support that.

**Comment by ngugcx** [comment]
Bleve indexer does not support both part-word and Case-insensitive? @lunny

**Comment by johannes-nivus** [comment]
> part word should have been supported by Postgres but not Case sensitivity. Maybe we need a PR to improve issue db indexer to support that.

Part of word search had not been possible with Postgres when I opened the issue (see screenshots).
Postgres: No part of word, case sensitive.
Bleve: No part of word.

**Comment by johannes-nivus** [comment]
> Did you meet this problem?
> 
> ```
> bash-5.0$ sqlite3 gitea.db <gitea-db.sql
> Error: near line 16: no such function: setval
> Error: near line 23: no such function: setval
> Error: near line 30: no such function: setval
> Error: near line 72: no such function: setval
> Error: near line 78: no such function: setval
> Error: near line 84: no such function: setval
> Error: near line 116: no such function: setval
> Error: near line 120: no such function: setval
> Error: near line 153: no such function: setval
> Error: near line 157: no such function: setval
> Error: near line 161: no such function: setval
> Error: near line 1380: no such function: setval
> ```

Yes, but I ignored it. And it worked.

**Comment by ngugcx** [comment]
Any update here?

**Comment by zeripath** [comment]
For postgres we would just have to emit ILIKE instead of LIKE

**Comment by zeripath** [comment]
However a cross dB solution would be to change

models.SearchIssueIDsByKeyword()

To use lower(...) on the fields and lower case the keyword too.

**Comment by zeripath** [comment]
This would be a three line pr

**Comment by ngugcx** [comment]
@zeripath , I prefer upper() over lower(). 
https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1308
https://en.wikipedia.org/wiki/%C3%9F#Capital_form

**Comment by ngugcx** [comment]
After upgrading to v1.14.1, search for part of a word is still not working.
I'm using postgres.

**Comment by 6543** [comment]
@ngugcx can you file a new issue & reverence this closed one :)

**Comment by ngugcx** [comment]
@6543 , filed a new one.
