### ISSUE TITLE
SQL for moving from Gogs to Gitea

### ISSUE THREAD

**Issue by lesh59** [go-gitea/gitea#13667]
- Gitea version (or commit ref): 1.12.5
- Git version:
- Operating system: Raspberry Pi OS (Buster)
 Gitea binary install (Arm 6)  
SystemD - v241
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
- Log gist:

## Description
I have created a SQL script to migrate a Gogs installation to Gitea.

Only tested on MariaDB.

* Gogs Application version 0.12.3 (Database version 1.19)
* Gitea Application version 1.12.5 (Database version 1.141)

Should be Ok with Gitea 1.12.6 as well.

If anyone wants to use it, I have published it at https://github.com/lesh59/Gogs2Gitea.git

Information is provided in the README.md file.

Hope it helps.

Regards  

Lesh59

**Comment by 6543** [comment]
I think this something for https://gitea.com/gitea/awesome-gitea, @lesh59 can you create a pull?
