### ISSUE TITLE
Allow custom oauth

### ISSUE THREAD

**Issue by wireva** [go-gitea/gitea#13665]
It would be nice if you could use a custom oauth config, like the Nextcloud Oauth plugin for example.
Specifically, I want to use mailcow as an oauth provider, but I think it would make more sense to make a general custom option instead of adding services one-by-one.

**Comment by techknowlogick** [comment]
This is what OIDC is for, Oauth2 doesn't allow for a generic connector.

**Comment by Niwla23** [comment]
Some Web Apps offer custom oauth, you can then configure the URLs for profile and tokens. Also there should be a setting to specify which field should be used as the identity

**Comment by Niwla23** [comment]
see e.g. CodiMD / HedgeDoc
