### ISSUE TITLE
/ROOTURL/issues/ : Issue URLs with host since #10158

### ISSUE THREAD

**Issue by floemker** [go-gitea/gitea#13677]
- Gitea version:  1.13.0+rc2-13-gef7a52826

## Description

The page /ROOTURL/issues/ has since #10158 issue URLs which include the host part, e.g.

    <a class="title" href="http://localhost:3000/ROOTURL/user/RVM/issues/2">Test issue</a>

This does not work correctly if the site is behind a reverse-proxy.
Everywhere else URLs without the host part are used. Would be great
if the host could be removed again.

**Comment by 6543** [comment]
> This does not work correctly if the site is behind a reverse-proxy.

you just have to correct your configuration:
`ROOT_URL` in `[server]` section.

for more info read https://docs.gitea.io/en-us/config-cheat-sheet and contact us via discord in the #configuration channel if you have problems :)

**Comment by floemker** [comment]
Would work for me, thank you.

But the disadvantage is that gitea than depends on the reverse proxy configuration
and the gitea instance can't be used directly anymore.

**Comment by 6543** [comment]
if you have a good enhancement, just submit a pull :) & good to hear it works now @floemker
