### ISSUE TITLE
Deleted commits are visible and accessible, if they are referenced in an issue

### ISSUE THREAD

**Issue by Codeberg-org** [go-gitea/gitea#13674]
- Gitea version (or commit ref): 1.12.6
- Git version: 2.20.1
- Operating system: Linux/Debian-stable, build-deploy-gitea deployment on Codeberg.org (production) 
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not tried

## Description

With pushed commits that had to be deleted using git reset --hard and a forced push to the remote. They aren’t in the repository anymore, but still visible in the issue where they are referenced. The issue in question is this one:

https://codeberg.org/ncc1988/moeripper/issues/2

To confirm the commits are gone, I checked out the repository in another directory. When trying to checkout the last commit-IDs from the issue in the repository, git tells me that the reference is not a tree, so they are definetly deleted. The deleted commits also aren’t visible in the project’s commit history.

**Comment by techknowlogick** [comment]
The git gc cron task would clean this up. If needed you could also force the cron to happen.

**Comment by Codeberg-org** [comment]
Considering that force-push is then and when used to undo accidental commits containing sensitive information, should this possibly automatically trigger the gc task for the repo in question?

**Comment by lafriks** [comment]
gc can be quite resource intensive, especially on big repos
