### ISSUE TITLE
Buggy CSS when browsers are not maximised, needs more wrap-around

### ISSUE THREAD

**Issue by Evrey** [go-gitea/gitea#13671]
- Gitea version (or commit ref): 1.14.0+dev-215-gd025d84d9, official docker image
- Git version: (irrelevant)
- Operating system: (irrelevant)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (Screenshot below)
  - [ ] No
- Log gist: (irrelevant)

## Description

Many websites falsely assume that people run their browsers maximised, taking the entire available monitor area for themselves. I am one of these people who instead tile their browser window, making it take up only half a motinor column. The resolution of the monitor in question is 1080p.

The fix is to make all horizontal flexboxes wrap around once the window width is reached.

## Screenshots

All screenshots made at the same resolution. You can see a bit of my desktop background on some of them, and the next monitor to the right.

![Bildschirmfoto_2020-11-22_12-59-54](https://user-images.githubusercontent.com/6483505/99903633-cb8b1000-2cc5-11eb-9493-4bd333b8ea78.png)
![Bildschirmfoto_2020-11-22_13-04-17](https://user-images.githubusercontent.com/6483505/99903636-d04fc400-2cc5-11eb-96af-59cf95eca9d5.png)
![Bildschirmfoto_2020-11-22_13-04-39](https://user-images.githubusercontent.com/6483505/99903639-d2b21e00-2cc5-11eb-8f54-c9a2805dd0b5.png)
![Bildschirmfoto_2020-11-22_13-11-31](https://user-images.githubusercontent.com/6483505/99903640-d5ad0e80-2cc5-11eb-80d2-f7cba3d0cdda.png)

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
I second this, also noticed it.

**Comment by silverwind** [comment]
Need to switch that to two-row layout on small screens like it's already done for PR review toolbar, e.g. https://try.gitea.io/silverwind/symlink-test/pulls/8/files.

**Comment by Evrey** [comment]
Addendum:

Horizontal scroll bars are needed for tables, such as the user table in the admin area.

**Comment by edgar-bonet** [comment]
This issue has become more obvious with the extra buttons brought by 1.17.0. Now I experience a broken layout for all window widths in the range 768px–1199px, both on Firefox and Chromium.

**Comment by silverwind** [comment]
Yes, agree there is too many buttons already. https://github.com/go-gitea/gitea/pull/20375 will remove one of them.

**Comment by silverwind** [comment]
https://github.com/go-gitea/gitea/pull/20602 will consolidate a few more.
