### ISSUE TITLE
Issue template labels only get applied from default label set and org label set is ignored

### ISSUE THREAD

**Issue by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [go-gitea/gitea#13688]
- Gitea version (or commit ref): [`Gitea Version: 1.14.0+dev-253-g24330f71b`](https://github.com/go-gitea/gitea/commit/24330f71b6ee874debec273952579c7c07d61140)
- Git version: `git version 2.29.2.526.gbb4321173f`
- Operating system: Arch Linux
- Built from
  - [x] source
- Run with
  - [x] systemd
- Database:
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] No

## Description
When specifying a label that is not present in the default label set and is only present in the org label set, it is ignored and the issue is open without that label.
The subject repo is not even using the default set of labels, it has been created without any labels and the only ones available to it are the labels of the org it is a part of.

example issue template:
```markdown
---
name: "Proposal :bulb:"
title: "[Proposal] "
about: "A proposal :bulb: template"
labels:
  - proposal
---
<!--
 This is a proposal template.
 Please, describe what your idea is trying to solve, who is it going to benefit,
 how do you imagine it gets done and how you yourself could contribute.

 Delete this commented section before posting.
-->
```
the issue template is registered by Gitea
![image](https://user-images.githubusercontent.com/61180606/100091151-8812dc00-2e54-11eb-90ea-47e0e70a63cf.png)
the label in question is not chosen because it's an org label
![image](https://user-images.githubusercontent.com/61180606/100091244-a547aa80-2e54-11eb-86d0-6b2e6d4b9a58.png)

**Comment by jk-nilo** [comment]
I confirm this issue for stable release binary 1.13.0 for Windows platform with MariaDB.

And, I was able to reproduce it on try.gitea.io too. See: https://try.gitea.io/TemplateOrg/TemplateRepo
It should add "bug" and "repoonly" labels, but is added only "repoonly".

**Comment by dusatvoj** [comment]
Same in 1.13.1, It's blocking issue for our workflow. Is there a chance to complete intergration org wide labels into gitea?

**Comment by lunny** [comment]
Please confirm #14593 resolved the problem.

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
> Please confirm #14593 resolved the problem.

Just applied the patch and tried it out.
Yes, #14593 does indeed fix the problematic behaviour.
Cheers. 🎉

**Comment by richmahn** [comment]
@zeripath Backport for v1.13 please. :)

**Comment by dusatvoj** [comment]
@richmahn I can see `Milestone 1.13.3` :thinking:

**Comment by richmahn** [comment]
@dusatvoj Not sure I understand. Yes, it is in the v1.13.3 milestone, so reminding to make a back port to the v1.13 branch.
