### ISSUE TITLE
No way to get current user 'active' state and other settings via API

### ISSUE THREAD

**Issue by WilixLead** [go-gitea/gitea#13681]
- Gitea version (or commit ref): 1.12.6 (release)
- Git version: 2.25.1
- Operating system: Linux 5.4.0-48-generic x86_64
- I get Gitea binnary from releases in Github
- Run gitea from systemd (used config from gitea docs)
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No (need admin rights)
- Log gist: --

## Description
I can't find any way for admin api to get user state like 'active', 'prohibit_login' and other checkboxes in admin page.
I thing it should be under /admin/users/{username} or /users/{username} (but it require additional role checking and changing output model)

**Comment by 6543** [comment]
I think we can ad something like `type` to specify if it's a "normal" user or a "restricted" one ... (this way we can extend it to "bot", ...)

and 'active', 'prohibit_login' should just be exposed like is_admin ...
