### ISSUE TITLE
arc-green Theme

### ISSUE THREAD

**Issue by Lure5134** [go-gitea/gitea#13690]
On the wiki in a repo the style is wrong.

![image](https://user-images.githubusercontent.com/54278236/100099768-2c4e5000-2e60-11eb-80bb-c4aa7acf4d10.png)

If the background color ("dcddde") in the class "text right grey" get's removed, it looks fine.

![image](https://user-images.githubusercontent.com/54278236/100100055-8222f800-2e60-11eb-915f-c6c955c7b601.png)

**Comment by 6543** [comment]
@Hummel37 witch version?

**Comment by Hummel37** [comment]
I have the docker version for arm https://hub.docker.com/r/kunde21/gitea-arm

**Comment by 6543** [comment]
@Hummel37 I mean gitea's version. It should stand in the footer or you can get it via api: `http(s)://<your-domain>/api/v1/version`

**Comment by Hummel37** [comment]
v1.12.6

**Comment by silverwind** [comment]
I think we eliminated all these type of issues likely in 1.13 and almost certainly in 1.14, so I think the best course of action is to upgrade once 1.13. is stable which should be pretty soon.

**Comment by techknowlogick** [comment]
I will close this now, but @Hummel37 you can see what the changes look like at https://try.gitea.io

**Comment by silverwind** [comment]
Actually no, this is in 1.14 too coming from a Fomantic style:

https://try.gitea.io/silverwind/symlink-test/wiki/_pages

Let's reopen.

**Comment by Hummel37** [comment]
1.14 looks much better. But in mobile view there are a lot of glitches from the design...
But I am using at most of the time my laptop and if I need to see something from my phone, I am using an app.

![Screenshot_2020-11-24-16-43-56-40](https://user-images.githubusercontent.com/54278236/100116727-60337080-2e74-11eb-82e2-18aad621c7c6.jpg)

![Screenshot_2020-11-24-16-44-03-39](https://user-images.githubusercontent.com/54278236/100116746-64f82480-2e74-11eb-8124-3845429b247f.jpg)

**Comment by 6543** [comment]
@Hummel37 just a hinf for mobile: GitNex is nice if you arebon Android ;)

**Comment by Hummel37** [comment]
I am and I am using it😉

**Comment by silverwind** [comment]
Yes, mobile layout is rather broken in many places because the layout is pretty much Desktop-first.
