### ISSUE TITLE
support for id_ecdsa_sk key

### ISSUE THREAD

**Issue by markuman** [go-gitea/gitea#13691]
- Gitea version (or commit ref): docker gitea/gitea:1.12.6  
- Git version:
- Operating system: Linux

- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
  - [x] mariadb
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No

## Description

When try to add `id_ecdsa_sk` public key try.gitea.io results in error  
`Can not verify your SSH key: key type is not allowed: ecdsa-sk`  

while my gitea 1.12.6 results in `Can not verify the SSH key; double-check it for mistakes.`

**Comment by silverwind** [comment]
See https://github.com/go-gitea/gitea/pull/13462

**Comment by noerw** [comment]
closing as duplicate of #13462

**Comment by markuman** [comment]
why closing? the pr is not merged yet.

**Comment by noerw** [comment]
sorry, my mistake

**Comment by mscherer** [comment]
Since #13462 is merged, I think this bug can be closed.

**Comment by markuman** [comment]
Indeed, works for me.
