### ISSUE TITLE
Detection of renamed files not working with Git 1.9.1

### ISSUE THREAD

**Issue by jhasse** [go-gitea/gitea#137]
- Gitea version (or commit ref): 0.9.99.0903
- Git version: 1.9.1
- Operating system: Ubuntu 14.04.5 LTS
- Database:
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite

## Description

I have a commit with a file A which get's renamed to B. Instead of showing that, Gogs/Gitea just shows me A with all it content removed and added again.

This Gogs commit added support for detecting file renames: https://github.com/go-gitea/gitea/commit/bc8215721627fcdeaa23c6e3bf625e0c4e5c3407

I couldn't reproduce this on https://try.gogs.io, so I think it has something to do with my older Git version.

**Comment by strk** [comment]
The commit you reference is already also in Gitea. Can you reproduce locally ?
Non-reproducible bugs would be nearly impossible to fix. Ideally a failing automated test would be provided, can you try that ?

**Comment by tboerger** [comment]
> Ideally a failing automated test would be provided, can you try that ?

How could he provide a failing test with specific Git versions?

**Comment by jhasse** [comment]
> How could he provide a failing test with specific Git versions?

I could set up a Dockerfile.

Is there an automated test for file renames?

**Comment by strk** [comment]
I don't think there's an automated test for file renames. Such test would be enough, then the _testers_ would have to deal with different Git versions.

**Comment by bkcsoft** [comment]
@strk _testers_ (as in Drone) should test using different git-versions yes :wink:

**Comment by bkcsoft** [comment]
@jhasse 

> I think it has something to do with my older Git version.

Please try that first :wink:

**Comment by jhasse** [comment]
I couldn't reproduce with git version 2.7.4. I'll try again with a virtual machine, might take a while ...

**Comment by jhasse** [comment]
Okay I've could not reproduce, even with the older Git version :( There seems to be something special about that commit, maybe I have time to create a minimal example. I would create a new bug report then.
