### ISSUE TITLE
Can't update to 1.1.x version : duplicat key

### ISSUE THREAD

**Issue by camlafit** [go-gitea/gitea#1370]
- Gitea version (or commit ref): 1.0.2 to 1.1.x
- Git version: 2.1.4
- Operating system: Jessie 386
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant

## Description

When I update binary from dl.gitea.org and overwrite gitea binary, I can't execute it.
```
2017/03/20 17:30:58 [I] Log Mode: File(Info)
2017/03/20 17:30:58 [I] XORM Log Mode: File(Info)
2017/03/20 17:30:58 [I] Cache Service Enabled
2017/03/20 17:30:58 [I] Session Service Enabled
2017/03/20 17:30:58 [I] Migration: create repo unit table and add units for all repos
2017/03/20 17:30:58 [...itea/routers/init.go:54 GlobalInit()] [E] Failed to initialize ORM engine: migrate: do migrate: CreateIndexes RepoUnit: Error 1061: Duplicate key name 'IDX_repo_unit_S'
```

**Comment by cez81** [comment]
I think this is same issue as #1261, just different database.
