### ISSUE TITLE
Commit hash and commiter avatar off in the PR view

### ISSUE THREAD

**Issue by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [go-gitea/gitea#13704]
- Gitea version (or commit ref): `1.14.0+dev-258-g03fa2eccb`
- Git version: `git version 2.29.2.526.gbb4321173f`
- Operating system: Arch Linux
- Built from
  - [x] source
- Run with
  - [x] systemd
- Database:
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] No

## Description
Recently I have noticed this anomalously off-set commit hash+avatar labels in the PR view (see screenshots below).
Could this be somehow linked to the recent and otherwise awesome improvements brought by https://github.com/go-gitea/gitea/issues/13594?

## Screenshots
![image](https://user-images.githubusercontent.com/61180606/100299931-2d34ce00-2f95-11eb-9546-aaeda49b106c.png)
![image](https://user-images.githubusercontent.com/61180606/100300000-5a817c00-2f95-11eb-82c0-6b70d74107d6.png)

**Comment by silverwind** [comment]
Possible, those SHA boxes are currently a bit of a pain because they use like three different templates and three different CSS sections so issues like that are bound to arise eventually until they properly share template and CSS.

**Comment by CirnoT** [comment]
Caused by https://github.com/go-gitea/gitea/pull/13594 by blindly forcing `display: inline` on Fomantic's `ui.label` element. Fomantic's label element can contain additional elements (such as `.detail` which is used here) which breaks when `inline`.

**Comment by CirnoT** [comment]
Additionally it seems that the `.detail` element is now not matching with box itself (for some reason we're using padding and margin hack there), a quick fix would be to change it to:
```css
margin: -3px -6px -3px 0;
padding: 3px 6px 3px 6px;```

however I fear this might be font-related.

**Comment by silverwind** [comment]
That `display: inline` is for issue label lists only, it shoul not match on that shabox.
