### ISSUE TITLE
Release publisher is not right when publish a release in UI

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#13713]
It points to the author of the commit but not the real publisher.

![image](https://user-images.githubusercontent.com/81045/100401531-b979ea80-3094-11eb-9acc-0a26dab41992.png)

**Comment by a1012112796** [comment]
@lunny
releated pr
https://github.com/go-gitea/gitea/pull/6025/files#diff-8962bac89952027d50fa51f31f59d65bedb4c02bde0265eced5cf256cbed306dR61-R66

**Comment by lunny** [comment]
Still a problem?
