### ISSUE TITLE
How to limit file size on commit?

### ISSUE THREAD

**Issue by wjx0912** [go-gitea/gitea#13712]
hi,  i can set githook  on client side,  but it need set for every repository.

can i set default limit filesize on gitea server(filter Junk files)?

thanks.

**Comment by zeripath** [comment]
Hmm... What do you mean by limit file size?

To do this in a pre-receive hook - (the place you'd run the test on a server) - you need to get all the objects (not just the blobs) created between the updated refs and check their file size - you'd likely have to consider checking the tree object size and commit object size too as a clever attacker could just skirt your file check by abusing those. (Please note there is nothing in the git spec preventing you from having the complete works of Shakespeare as a file name - although please don't try it as I expect Gitea would not like it.)

So for every ref updated you're looking at running:

```bash
 git rev-list --objects old..new | cut -d\  -f1 | git cat-file --batch-check
```

And then checking each size in turn to ensure that they are not too large. (This could still be done in bash...)

If you wanted to restrict to blobs you could get away with passing that through `grep blob`.

Making ths a default hook I'm not sure - I think there are ways of making hooks be part of a template though and you could just copy the hook to every repo using the command line.

**Comment by lafriks** [comment]
I think we had option to set server side git hooks

**Comment by techknowlogick** [comment]
If you wish to use git hooks please set `DISABLE_GIT_HOOKS` to true (more details here: https://docs.gitea.io/en-us/config-cheat-sheet/#security-security ) please note WARNING: Custom git hooks can be used to perform arbitrary code execution on the host operating system. This enables the users to access and modify this config file and the Gitea database and interrupt the Gitea service. By modifying the Gitea database, users can gain Gitea administrator privileges. It also enables them to access other resources available to the user on the operating system that is running the Gitea instance and perform arbitrary actions in the name of the Gitea OS user. This maybe harmful to you website or your operating system.
