### ISSUE TITLE
Question: Hide Links for unregistered users

### ISSUE THREAD

**Issue by sonicnkt** [go-gitea/gitea#13717]
- Gitea version: 1.12

## Description
We are using Gitea besides some code hosting as an issue system for the it. Because of this i would like to add some custom links to the top menu for common management urls `extra_links.tmpl`.
Since we want to be able to access gitea from outside our network without a VPN i was wondering if it is possible to hide those extra links for anyone who isn't logged in?

At the moment those are always visible to anyone and even tho those service are mostly usable only with a vpn i would like to hide the urls from the public anyway.

## Screenshots
![grafik](https://user-images.githubusercontent.com/5454622/100438348-4d9e7e80-30a2-11eb-9852-dabad4313f30.png)

**Comment by Masgalor** [comment]
I guess you could use the following in your template.
Thats what is used in `head_navbar.tmpl`, to hide/show links depending on a logged in user.

`{{if and .IsSigned .MustChangePassword}}`
`{{/* No links */}}`
`{{else if .IsSigned}}`
`{{/* Your links go here */}}`
`{{end}}`

**Comment by sonicnkt** [comment]
Thanks you for the fast reply, works like a charm :)
