### ISSUE TITLE
Docker: Issues with file-based logging

### ISSUE THREAD

**Issue by pat-s** [go-gitea/gitea#13715]
- Gitea version (or commit ref): 1.14.0+dev-260-g7bc0c8cff
- Git version: 2.2.6.2
- Operating system: docker
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
- Log gist:

## Description

I am struggling to set up logging in a docker-based Gitea install.

In `app.ini` I have

```
[log]
ROOT_PATH =
; Either "console", "file", "conn", "smtp" or "database", default is "console"
; Use comma to separate multiple modes, e.g. "console, file"
MODE = console, file

[log.file]
LEVEL = debug
; Set the file_name for the logger. If this is a relative path this
; will be relative to ROOT_PATH
FILE_NAME = log.txt
```

and I expect a `data/gitea/log/log.txt` to be written.

However, this file never appears (anywhere). 
The console log appears in `debug` level just fine.
What is wrong in my config?

**Comment by zeripath** [comment]
Setting the `ROOT_PATH =` means that the `ROOT_PATH` will default to:

```
LogRootPath = Cfg.Section("log").Key("ROOT_PATH").MustString(path.Join(AppWorkPath, "log"))
```

Where `AppWorkPath`  is the environment variable `$GITEA_WORK_DIR` or the directory of the gitea binary.

**Comment by pat-s** [comment]
Thanks. I forgot to mention that I tried this already without success.

**Comment by zeripath** [comment]
Do you have any other [log.file] sections in your app.ini? Testing on a non-docker build here those settings above seem to work.

Is it possible that the /data/gitea/log directory is in some temporary place which get overwritten on restart of the container?

**Comment by pat-s** [comment]
> Do you have any other [log.file] sections in your app.ini? 

No. I am also out of ideas why nothing is written to a file (anywhere). 
Directory permissions are also ok (git user).

**Comment by pat-s** [comment]
I think this does not apply anymore for me - probably a misconfigured config file on my side?
