### ISSUE TITLE
Please allow to use some API without authentication / document that it is possible, if it is already implemented

### ISSUE THREAD

**Issue by KOLANICH** [go-gitea/gitea#13714]
My use case is fetching the latest tag on a branch.  I have a lib implementing doing that with API of different services. It is needed for the software building packages from sources.

**Comment by lafriks** [comment]
It should be possible if repository is public imho

**Comment by techknowlogick** [comment]
It is documented here: https://try.gitea.io/api/swagger#/repository/repoListTags
