### ISSUE TITLE
Prevent hook behavior on downgrade binary

### ISSUE THREAD

**Issue by camlafit** [go-gitea/gitea#1371]
- Gitea version (or commit ref): 1.1.x to 1.0.x
- Git version: 2.1.4
- Operating system: Jessi 386
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

If to any reason we get any error during upgrade binary, we broke all repositories on downgrade.

In 1.1.x , new hook are provide as pre-receive, if to any reason we can't upgrage (#1370) we restore previous version 1.0.2. 
In this case hook are updated on each repository and admin option can't repair this action.

Then a manual clean on each repositories is required.

**Comment by lunny** [comment]
Currently, Gitea didn't support downgrade. So every time you upgrade, please backup old system at first.

**Comment by bkcsoft** [comment]
I agree with @lunny. Gitea currently does not support downgrades, and downgrading might in fact break much worse than just invalid git-hooks.

**Comment by camlafit** [comment]
Hi

We can reformulate as "do any thing if upgrade is wrong". In this use, I've
update binary. Get some error about mysql change as #/1261, without any
information. Solution was to restore previous binary.

It's later when an user has tried to push a commit, we have get error about
hooks. Without any information during update process, was a bit complicated
to understand.  As in same time wiki was updated then a simple restore
backup was not possible.


Purpose is to prevent any problem during an update and restore a previous
correct state. In this use case restore hook state. Maybe should be not
update any hook before check if update is ok.

Thanks

**Comment by bkcsoft** [comment]
@camlafit 

>  reformulate as "do any thing if upgrade is wrong"

There's no way of knowing if the upgrade was successful. And not doing migrations will leave the system in a broken state which would be counter-productive.

> Without any information during update process, was a bit complicated to understand.

Migrations do need an overhaul in my opinion. Downgrading is one thing I had in mind. Another thing is better messages about which migrations are ran, and maybe why (print a link to the PR that introduced the migration)

> Maybe should be not update any hook before check if update is ok.

How would we know if an update is okey?

**Comment by camlafit** [comment]
Hi

Get a perfect migration looks impossible but we can improve this.
Maybe we can have a checklist process, In log should be interessting to
display :

```
Ok was X version, I update to Y and will do :
* Update database
* Update hooks
* update repository structure ...
```

Of course this checklist is incomplete and can be evolve step by step.

If update follow a procedural process, maybe also display all step started
and ended.

On any error, as database pb, admin get information about other step and
can check these. And if a step was ok. Display an ok step.

To some step as database update, looks possible to get a control as
database structure waiting, on hooks check if some file are presents on
each repo, .... To other I've any idea how to said "ok step passed" :)
