### ISSUE TITLE
mathjax in markdown

### ISSUE THREAD

**Issue by hpodhaisky** [go-gitea/gitea#13710]
I would like to use mathematical formulas in markdown (such as readme.md) being displayed in gitea.
The Config Cheat Sheet mentions external renderers -- but using for example `pandoc -f html -t markdown -mathjax` doesn't seem to work as the javascript MathJax.js is not included in the head of the html document. Can you provide templates / or documentation how to achieve this?

**Comment by Codeberg-org** [comment]
See https://codeberg.org/Codeberg/build-deploy-gitea/commit/9532f25178438cde904bc82fc8a9ec04f821c625 for sample integration into `header.tmpl`

**Comment by mrsdizzie** [comment]
There is information at https://docs.gitea.io/en-us/customizing-gitea/ as well, above example is a simple/good one for this issue
