### ISSUE TITLE
How to migrate GitHub repo issue&PR to gitea

### ISSUE THREAD

**Issue by ffbh123456** [go-gitea/gitea#13729]
- Gitea version (or commit ref): docker image id  9058d7d9f1a1
- Git version: 2.28.0
- Operating system: macOS 11.0.1
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite

## Description
I want to migrate the issues from the Github project to my gitea. I created the access token with the highest authority, but I can only migrate the WIKI. Does gitea now support the migration of Github issues and Pull Request?

<img width="746" alt="截屏2020-11-28 13 11 44" src="https://user-images.githubusercontent.com/20750357/100494275-45fed880-317b-11eb-93ad-9fb5936a3b91.png">

**Comment by techknowlogick** [comment]
Migration of issues is possible, mirroring issues is not possible (please uncheck the mirror option to allow migration)
