### ISSUE TITLE
Migration big project failed

### ISSUE THREAD

**Issue by ffbh123456** [go-gitea/gitea#13730]
- Gitea version (or commit ref): docker image id  9058d7d9f1a1
- Git version: 2.28.0
- Operating system: macOS 11.0.1
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
- Log gist:
I tried to migrate a project of mine on Github. My project is a bit big,  about 400M. I migrated everything (issue, label, pull request). At the beginning, I can see the picture of the green water cup below, and then I waited for 10 minutes to refresh the page again, a 404 error was reported, and the project did not migrate.
<img width="694" alt="截屏2020-11-28 15 23 50" src="https://user-images.githubusercontent.com/20750357/100496287-b9a9e100-318d-11eb-8af3-ad6c72a99201.png">

**Comment by ZhouJiaZhi** [comment]
And I found two error in log
2020/11/28 07:29:26 ...ules/task/migrate.go:65:func1() [E] DeleteRepository: repository does not exist [id: 5, uid: 2, owner_name: , name: ]
2020/11/28 07:29:26 modules/task/task.go:51:handle() [E] Run task failed: Migration failed: Clone: context deadline exceeded - fatal: early EOF

**Comment by techknowlogick** [comment]
Please tweak git timeout options as needed: https://docs.gitea.io/en-us/config-cheat-sheet/#git---timeout-settings-gittimeout
