### ISSUE TITLE
The color of the button obscures the text content

### ISSUE THREAD

**Issue by ffbh123456** [go-gitea/gitea#13731]
- Gitea version (or commit ref): docker image id  9058d7d9f1a1
- Git version: 2.28.0
- Operating system: macOS 11.0.1
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
## Description
This button does not display the master text by default, and the master text can only be displayed when I select the button text
![image](https://user-images.githubusercontent.com/20750357/100497579-502ed000-3197-11eb-8d30-0e5a730cd691.png)
![image](https://user-images.githubusercontent.com/20750357/100497590-5d4bbf00-3197-11eb-9450-cfc0ff576d01.png)

**Comment by silverwind** [comment]
Fix for this added on https://github.com/go-gitea/gitea/pull/13733.

**Comment by ZhouJiaZhi** [comment]
@silverwind 
Great, I am using a white theme, how can I change it to dark?

**Comment by silverwind** [comment]
User menu, setting, account.

**Comment by ZhouJiaZhi** [comment]
@silverwind 
Hi, I found another interface problem. The two buttons below are pasted together. This looks strange. I hope these two buttons can be separated.
<img width="229" alt="截屏2020-11-29 16 06 09" src="https://user-images.githubusercontent.com/20750357/100536679-263fe100-325d-11eb-8bc3-a29f4ef2aa59.png">

**Comment by silverwind** [comment]
Addressed in https://github.com/go-gitea/gitea/pull/13744.
