### ISSUE TITLE
Take milestone due date into account when sorting issues

### ISSUE THREAD

**Issue by locnide** [go-gitea/gitea#13738]
When we sort issues by "Nearest due date" or "Farthest due date", only issues due dates are taken into account.
I think it would be nice to take the milestone due date into account. 

Maybe it could be implemented in the following way : when the milestone due date is further than the issue due date, the later is taken into account, and if the milestone due date is nearer, then the milestone is taken into account for sorting.

I've tried an implementation in this commit : https://github.com/koalp/gitea/commit/126d3caecedc0deed9dbd8cc0d6dff4cdba2e0e9 and can make a PR if this issue is accepted.

*My use case: when I'm looking for the next issue to work on, I go in the issue tab, look at assigned issues and sort by "Nearest due date". But when due dates have been set using milestones, I don't see them and have to look in each milestone manually.*

**Comment by noerw** [comment]
Nice, please send a PR!

**Comment by koalp** [comment]
> edit: could you check if your change fixes #13395 too?

I couldn't reproduce the issue : I tried to create a lot of issue with the same due date (with a due date with a due past by less than a day), but the issues where sorted according to their number.
