### ISSUE TITLE
Issue tracker url doen not support jira

### ISSUE THREAD

**Issue by ffbh123456** [go-gitea/gitea#13742]
- Gitea version (or commit ref): docker image id  9058d7d9f1a1
- Git version: 2.28.0
- Operating system: macOS 11.0.1
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No

## Description
My issue is recorded in the Jira system. When I set up the issue tracker of gitea, it reported an error saying that the URL is illegal, but I don’t think gitea needs to have this URL verification, because gitea just uses a new page to open the URL, I hope this URL can support any issue management system
## Screenshots

![image](https://user-images.githubusercontent.com/20750357/100532995-5de96180-323a-11eb-8f2c-b4ae99a17203.png)
<img width="1190" alt="截屏2020-11-29 11 57 09" src="https://user-images.githubusercontent.com/20750357/100533002-722d5e80-323a-11eb-8b5a-4d2afbd975ce.png">

**Comment by techknowlogick** [comment]
When providing Gitea version please use the output of `gitea --version` as docker image IDs aren't easily determined.

**Comment by ZhouJiaZhi** [comment]
@techknowlogick 
Hi,
Gitea version 1.14.0+dev-265-g742e21aeb built with GNU Make 4.3, go1.15.5 : bindata, timetzdata, sqlite, sqlite_unlock_notify
But I think the above problem exists in most gitea versions

**Comment by techknowlogick** [comment]
Per this code https://github.com/go-gitea/gitea/blob/de6ef14d04c36272143ad822bf5903f84c7f238b/modules/validation/helpers.go#L72 this is expected for security reasons.

**Comment by ZhouJiaZhi** [comment]
@techknowlogick 
I deploy both jira and gitea on my personal computer, I don’t understand why localhost has security issues
