### ISSUE TITLE
Licence text without horizontal scrolling

### ISSUE THREAD

**Issue by xoxys** [go-gitea/gitea#1374]
- Gitea version (or commit ref): 1.1.0
- Git version: not relevant
- Operating system: not relevant
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
Would it be possible to break line in the licence text view instead of scrolling horizontal? I know, its a small thing but i think without scrolling it is better readable.

## Screenshots
![licence_text](https://cloud.githubusercontent.com/assets/3391958/24236659/1a230388-0fa3-11e7-839b-e09cf04def2e.png)

**Comment by tboerger** [comment]
It's just a matter how it gets formatted, that's just my opinion

**Comment by xoxys** [comment]
Sure. I think word-wrap/word-break can do the trick

**Comment by bkcsoft** [comment]
We could have a JS-powered checkbox addind a wordwrap-class to the text-box 🤔

**Comment by xoxys** [comment]
I would prefer this as a global setting not per repo

**Comment by bkcsoft** [comment]
@xoxys Obviously 🙂

**Comment by zeripath** [comment]
Fixed by #5558
