### ISSUE TITLE
System-wide OAuth2 applications support

### ISSUE THREAD

**Issue by v-byte-cpu** [go-gitea/gitea#13756]
As Gitea admin user, I want to create a single drone server instance for **multiple** Gitea users. It means to access the repositories of multiple gitea users from a single drone-server instance. Looking at the drone server configuration, I find a single `DRONE_GITEA_CLIENT_ID`/`DRONE_GITEA_CLIENT_SECRET` configuration pair. Right now on gitea-side, the OAuth2 configuration is done in the context of a single user, it doesn’t seem possible to access repositories of other users.

Is this a restriction of the drone/gitea combination ? Gitlab supports system-wide oauth2 apps.

**Comment by techknowlogick** [comment]
Gitea's oauth apps are same as gitlab's in terms of functionality, and if you compare both when using Drone you won't see any difference.

When logging into Drone, it fetches the repos of each the specific user that logged in. Drone only syncs repos for users that they have collaborator permissions for, so if you want to configure a repo in drone you'll need to make sure a repo admin logs in and configures it.

For Drone configuration questions please use their forum at https://discourse.drone.io

**Comment by v-byte-cpu** [comment]
Ok, thank you for the clarifications
