### ISSUE TITLE
Can't create user account from CLI

### ISSUE THREAD

**Issue by alexeysmovzh** [go-gitea/gitea#13757]
- Gitea version (or commit ref): 1.12.6
- Git version: 2.20.1
- Operating system: Debian 10 Buster (amd64)
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ x ] MariaDB 10.5.8 buster amd64
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ x ] No
- Log gist:

## Description
Trying to create user via CLI:

$ sudo -u git /opt/gitea/gitea admin user create --username myname --password asecurepassword --email me@example.com -c /opt/gitea/app.ini
No help topic for 'user'

In Gitea log appear the following message:

$ sudo -u git tail /opt/gitea/log/gitea.log 
2020/11/30 12:01:56 ...ource/manager_run.go:41:Run() [E] Unable to get UIDcounts: Error 1146: Table 'giteadb.notification' doesn't exist
2020/11/30 12:02:06 ...ource/manager_run.go:41:Run() [E] Unable to get UIDcounts: Error 1146: Table 'giteadb.notification' doesn't exist

Table 'notification' in database exists:

$ mariadb -u gitea -palex giteadb -e 'show tables;'

| mirror                    |
| notice                    |
| notification              |
| oauth2_application        |
| oauth2_authorization_code |
| oauth2_grant              |

From web interface I create user successfully without any error. Just can't create from CLI.

**Comment by 6543** [comment]
the cli got restructured ...

## gitea > 1.13.0
`./gitea admin user create --help`

## gitea <= 1.13.0
`./gitea admin create-user --help`

**Comment by 6543** [comment]
@alexeysmovzh feel fre to ask for repoen if this did not fix it

**Comment by alexeysmovzh** [comment]
Thank you! 
This works well
I'm understand my mistake

**Comment by 6543** [comment]
@alexeysmovzh happy to help - If you have similar questions just as on discord :)
