### ISSUE TITLE
No repositories displayed on homepage anymore

### ISSUE THREAD

**Issue by pokapow** [go-gitea/gitea#13770]
- Gitea version (or commit ref): 1.12.6
- Git version: 2.11.0
- Operating system: Debian 9
I migrated from Gogs 12.1 to gitea, following step by step [the documentation](https://docs.gitea.io/en-us/upgrade-from-gogs/).
Everything was perfect until Gitea version 1.11.8
- Database:
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No

After upgrade from 1.11.8 to 1.12.6, I have no repositories displayed on homepage anymore:

![image](https://user-images.githubusercontent.com/30467320/100671723-3ccf6080-3361-11eb-96b4-a218bdbb0739.png)

While there are 39 as you can see, 12 of which are owned by my user.

Until then I saw all the deposits displayed here.

**Comment by techknowlogick** [comment]
Please fill out the default issue template, it helps us help you.

**Comment by pokapow** [comment]
I just did it.

Here is the rendering in version 1.11.8 :
![image](https://user-images.githubusercontent.com/30467320/100678913-98541b00-336e-11eb-8044-d979ac421f4f.png)

**Comment by pokapow** [comment]
Ok seems to be fix in v1.13.0
Thanks for your work.
