### ISSUE TITLE
LFS files missing in downloaded repository

### ISSUE THREAD

**Issue by BitBlit88** [go-gitea/gitea#13773]
When using the "Download Repository" button next to the repository url and saving the repo as "zip" or "tar.gz", the resulting artifact doesn't contain any files that are stored in LFS.

Steps to reproduce:
git init
git lfs track ".mp3"
git add test.mp3
git commit -m "lfs test"
git remote add origin http://server:3001/apps/test.git
git push -u origin master

Try and download the pushed repo from the web interface.
The resulting "test.zip" contains the file "test.mp3" but its content is like

version https://git-lfs.github.com/spec/v1
oid sha256:8437dccdf0c9966893404f1537b6bffb51cd189e0ac19d57f49cba97acb7ff3d
size 5282118 

So instead of including the LFS file itself, only the pointer is included.
The calculated repository size doesn't fit either. The Web interface shows 18kb, although the size with LFS objects are about 5MB.

I'm using Gitea 1.12.6 (arm-6)

**Comment by zeripath** [comment]
This is unfortunately a known issue and duplicated with #4773
