### ISSUE TITLE
Bring back attachment preview/thumbnails

### ISSUE THREAD

**Issue by bobemoe** [go-gitea/gitea#13786]
In older versions of Gitea (1.11) there was  image thumbnail/preview for attachments. My team found it really useful and since it's been removed in later version (1.12) (by PR #6089 ?) we really miss it! Any chance of seeing it re-implemented?

---

### Gitea 1.11.8
![Screenshot_2020-12-02 test(1)](https://user-images.githubusercontent.com/2304970/100869103-75238b80-3494-11eb-9e0e-55706e924198.png)

---
### Gitea 1.12.6
![Screenshot_2020-12-02 test](https://user-images.githubusercontent.com/2304970/100869027-591fea00-3494-11eb-977a-4d318a97bf6c.png)

**Comment by lunny** [comment]
But not all attachments are images? How to handle non-images? We change that because it's ugly for non-images. 
Hm, for non-images, we can generate an alphabet image automatically.

**Comment by bobemoe** [comment]
Maybe something similar to what happens if I click to edit the comment? I've attached a zip too to my example to demonstrate a non-image.

![image](https://user-images.githubusercontent.com/2304970/100877008-18c66900-34a0-11eb-82dc-67092ba31eea.png)

Here we have this list of filename and filesize which, and also thumbnails.  

So **all** files would be in the list, and image files would also have a thumbnail in a separate panel?

**Comment by bobemoe** [comment]
So with more attachemtns and a mockup:

### Old
![Screenshot_2020-12-02 test(2)](https://user-images.githubusercontent.com/2304970/100878742-7bb8ff80-34a2-11eb-95cf-8484cae34358.png)

### Current
![Screenshot_2020-12-02 test(3)](https://user-images.githubusercontent.com/2304970/100878760-81aee080-34a2-11eb-8f86-6ab69f710e57.png)

### Proposed
![proposed](https://user-images.githubusercontent.com/2304970/100878786-87a4c180-34a2-11eb-8e86-212b82d10361.png)

**Comment by bobemoe** [comment]
I will have a go at implementing this tonight
