### ISSUE TITLE
Css specifies emoji fonts for body text

### ISSUE THREAD

**Issue by Oreolek** [go-gitea/gitea#13784]
- Gitea version: 1.13.0
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes: https://try.gitea.io/explore/repos
  - [ ] No

## Description

`_base.less` specifies the body and headings font family as:

> -apple-system,BlinkMacSystemFont,system-ui,Segoe UI,Roboto,Helvetica,Arial, **Apple Color Emoji,Segoe UI Emoji,Noto Color Emoji,Twemoji Mozilla,** sans-serif

This looks fine on Chrome but I guess you didn't test on Firefox because Firefox prints all numbers as emoji. Everywhere. It's hideous.

## Screenshots

![1](https://user-images.githubusercontent.com/308627/100838679-c9b21100-346a-11eb-8012-e00fed2d5bf8.png)

Also see #12966 because that bug is about the same CSS line.

**Comment by techknowlogick** [comment]
I am using FF but am not seeing what you see in screenshots, could you confirm the operating system and version of FF you are using?

**Comment by Oreolek** [comment]
Linux, Firefox beta 84.0. It's fine on a Windows virtual machine.

I guess the `Noto Color Emoji` is the first font installed on my system because it obviously has no Microsoft, Apple or Google fonts.

**Comment by itsdeadguy** [comment]
I'm seeing this as well, similar setup as @Oreolek

**Comment by silverwind** [comment]
Is it only numbers? I guess one could use [CSS unicode-range](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/unicode-range) to just exclude glylphs 1-9 thought I wonder if there are better solutions.

**Comment by silverwind** [comment]
Can someone test if putting `sans-serif` before the emoji fonts solves this?

**Comment by itsdeadguy** [comment]
@silverwind that works but it's not the proper way to define a font stack and might break something else down the line, possibly

**Comment by silverwind** [comment]
What do you suggest? We can't really wrap all emoji in their own elements after all.

**Comment by itsdeadguy** [comment]
are they being used elsewhere? this is honestly the first time i noticed them. all other icons i've seen on the web interface seem to come from an icon font and are contained in elements

**Comment by silverwind** [comment]
Emoji can of course appear anywhere where there is user content and we might even use them at some point in our own templates. I think it's unavoidable to have those fonts in the font stack.

**Comment by silverwind** [comment]
Please try https://github.com/go-gitea/gitea/pull/13834.
