### ISSUE TITLE
Cannot add or edit a file via web gui

### ISSUE THREAD

**Issue by commel** [go-gitea/gitea#13799]
- Gitea version (or commit ref): 1.13.0
- Git version: 2.7.4
- Operating system: Ubuntu 16.04.7 LTS
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
- Log gist:

## Description
The editor for live editing or creating new files in a repo does not work anymore. It works with gitea 1.14 on try.gitea.io tho. The javascript console shows:
```
Uncaught (in promise) ChunkLoadError: Loading chunk 7 failed.
(missing: https://git.holarse-linuxgaming.de/js/monaco.js)
```
The monaco-file is available if i request it in the browser. This only fails on new or editing a file, showing files work fine.

## Screenshots
![image](https://user-images.githubusercontent.com/1015465/100924388-d5401f00-34e0-11eb-841b-7be643b4024c.png)

**Comment by 6543** [comment]
@commel how did you got gitea | what is your setup?

**Comment by commel** [comment]
See above. It's a Ubuntu 16.04 LTS with MySQL backend.

**Comment by 6543** [comment]
@commel can you clear all related browser cache?

**Comment by commel** [comment]
@6543 oh god, I am so sorry. Running the website in private mode works fine. So it's a cache issue. So sorry for wasting your time and thanks for helping!
