### ISSUE TITLE
[Suggestion] Create profile README that shows up in your profiles

### ISSUE THREAD

**Issue by TheEvilSkeleton** [go-gitea/gitea#13798]
GitHub has this awesome feature that you can create a README that shows up in your profiles.

You just have to reuse your username as the name of the repo and create a `README.md` so it shows up in your profile.

Here's how mine looks for example:
![image](https://user-images.githubusercontent.com/50847364/100922179-904dc580-34ab-11eb-8435-8cfa9636e258.png)

**Comment by 6543** [comment]
-> #12233
