### ISSUE TITLE
[Suggestion] Create feedback/suggestion/proposal template

### ISSUE THREAD

**Issue by TheEvilSkeleton** [go-gitea/gitea#13797]
As the title suggests.

**Comment by techknowlogick** [comment]
Could you clarify, do you mean an issue template that is specifically for suggestions/feedback rather than the default that includes information for bugs?

**Comment by TheEvilSkeleton** [comment]
> Could you clarify, do you mean an issue template that is specifically for suggestions/feedback rather than the default that includes information for bugs?

Yes, that is exactly what I meant. The issue of this repo only has for bug reports, but by looking through the issue tracker, people suggest additions/removals/changes as well. It would be nice to have a template so they can be more verbose to what they are talking about and why it would benefit the community.

**Comment by lunny** [comment]
I think we have done that.
