### ISSUE TITLE
[API] Get/Set User settings

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#13807]
add new endpoint to set/get user settings:
 * Location
 * Language
 * Biography
 * Privacy settings (hide activity)
 * ~~selected theme~~

**Comment by silverwind** [comment]
I plan to remove theme from the database and make it a client-side only settings, so probably remove that one.

**Comment by lunny** [comment]
@silverwind So that user would not save his theme on settings?

**Comment by lafriks** [comment]
Why would not save selected theme in settings? If I use multiple devices that would require for me switching for every new device. Also for my development browser I use setting that deletes all local storage etc when I exit browser, that would require me changing theme every time :(

**Comment by 6543** [comment]
I think browser storage is a nice option but I would still like to store it into DB as default falue for new browsers (cleared browsers) ...

**Comment by silverwind** [comment]
Yeah I guess on second thought, it might be inconvenient to some. Not sure how else to handle the case of logged out user theme. I guess one approach could be localStorage synced with the DB but any kind of localStorage use brings the issue that it can't cleanly be applied during page load, maybe it needs to go into the cookie after all.
