### ISSUE TITLE
Missing repository created before the introduction archival function in sidebar

### ISSUE THREAD

**Issue by mixman68** [go-gitea/gitea#13804]
- Gitea version (or commit ref): 1.12.6
- Git version: 2.20.1
- Operating system: Debian buster
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
- Log gist:

## Description
I see this bug today but it was here since log time ago, since the possibility of archive a repo.

If il do a select
```
 select is_archived from repository group by is_archived
```

It was returned

```
+-------------+
| is_archived |
+-------------+
|        NULL |
|           0 |
+-------------+

```

So some repo was missing on the sidebar, i have only 21 of 71 repos

Doing this query restore database consistently

`update repository set is_archived=0 where is_archived is null;`

And my repos are all here :)

...

**Comment by jolheiser** [comment]
This is fixed in 1.13 with #11853

The backport was a doctor check in #11859
