### ISSUE TITLE
installer: Current handling of form "Domain" seems questionable

### ISSUE THREAD

**Issue by pmattern** [go-gitea/gitea#1381]
- Gitea version (or commit ref): 6a451a2b
- Git version: 2.12.1
- Operating system: Arch Linux x86_64
- Database (use `[x]`):
  - [x] PostgreSQL 9.6.1
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant

## Description

The value of form "Application General Settings" - "Domain" is currently assigned to directive `[server]` - `SSH_DOMAIN` in `app.ini`. According to the [template](https://github.com/go-gitea/gitea/blob/6a451a2b5986bf5c27f20a00000495da1064c386/conf/app.ini) directive `SSH_DOMAIN` is by default adopting the value of `DOMAIN`, but not the other way around. All in all just using the installer and filing a custom value in form "Domain" results in an instance using different values of the two directives `{SSH_,}DOMAIN`.

So far I haven't seen any malfunction due to this, yet I think it's weird behaviour. I guess it would be better to assign the value of form "Domain" to `DOMAIN` as this results in consistency when a custom value is filed in form "Domain" and no further tweaking of `app.ini` takes place.

Similar problems have been addressed in #785 and #552.

**Comment by lunny** [comment]
I think this should not be a problem any more.
