### ISSUE TITLE
[Enhancement] Project boards / KanBan: Batch assign issues to project / board

### ISSUE THREAD

**Issue by dphdave** [go-gitea/gitea#13815]
I've just started trying out the new Project boards / KanBan feature, which is really great, however there are a number of things that would need to be improved before it is really usable for me:

In particular, when migrating an existing project to use this new feature it is extremely cumbersome to:
(1) add each issue separately to a 'project'
(2) then within the project, move each issue to the appropriate board

It would be much more useful if we could assign a batch of issues to a project and board in one action.
For example, I currently have a label `TODO: test`, which can logically become a `Test` 'board' of a 'project' (or column of a board depending on your preferred nomenclature...).  If I could simply filter by that label, then assign all of those issues to a project / board, it would save a lot of hassle.

![Gitea feedback 2](https://user-images.githubusercontent.com/58987011/101020026-c485bc80-3565-11eb-993c-0f1dcd3356c5.png)

**Comment by themikemayer** [comment]
This feature would be extremely helpful. Any anticipation whether this will be included in a future update?

**Comment by themikemayer** [comment]
Seems to be redundant to issue #17216 which has already been merged.

**Comment by wxiaoguang** [comment]
It has been implement in https://github.com/go-gitea/gitea/pull/17226 

![image](https://user-images.githubusercontent.com/51889757/136448753-ec55a5f0-f431-43ea-bc8e-d5c9e6456ce9.png)


I think  we  can close this issue. If there is any new problems, feel free to open a new one.
