### ISSUE TITLE
Nearly Empty Elasticsearch gitea_codes index 

### ISSUE THREAD

**Issue by mwhamilton** [go-gitea/gitea#13823]
- Gitea version (or commit ref): 1.13.0, from download, using systemd
- Git version: 2.17.1
- Operating system: Ubuntu 18.04.3 LTS
  
  
  
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
- Log gist:

## Description
I switched to using Elasticsearch, but the index is only populating with results from commits after the index was created. This makes the Explore > Code functionality not very useful in the short-term.  Is there a way to force gitea to add every file to the Elasticsearch index at once?
...

**Comment by lunny** [comment]
Just rename the old index name and restart the Gitea, it should create the new index and populate all old git datas.

**Comment by mwhamilton** [comment]
Thank you. Restarting worked! I'm sorry for not trying that before.
