### ISSUE TITLE
Unable to select issue branch

### ISSUE THREAD

**Issue by xtprox** [go-gitea/gitea#13825]
- Gitea version (or commit ref): 1.13.0
- Git version: 2.7.4
- Operating system:
    - Ubuntu 16.04
    - Using `gitea-1.13.0-linux-amd64` binary
    - Starting with systemd

- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL) - https://try.gitea.io/prox/qwook/issues/1
  - [ ] No

## Description
Unable to select a repository branch in the issue creation dialog. After the branch is selected, the page is simply reloaded, no branch change is done (value returned to "No Branch/Tag Specified"). I'm able though to change the branch after the issue is created.

## Screenshots
https://i.imgur.com/K1P9u2F.png

**Comment by wxiaoguang** [comment]
Outdated
