### ISSUE TITLE
1.13.0 can no longer "Migrate from Git" with private ip-address

### ISSUE THREAD

**Issue by EFX-PXT1** [go-gitea/gitea#13822]
- Gitea version (or commit ref): 1.13.0
- Git version: 2.24.1
- Operating system: CentOS 7.9.2009
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No

## Description

Migration from bitbucket with username/password working fine.
Following upgrade to 1.13.0 attempts to "Migrate from Git" with username/password
always results in a 404 
The page you are trying to reach either does not exist or you are not authorized to view it.
Gitea Version: 1.13.0

Logs report
task.go:51:handle() [E] Run task failed: migrate from "private" is not allowed: the host resolve to a private ip address

**Comment by gary-kim** [comment]
Take a look at `ALLOW_LOCALNETWORKS` here: https://docs.gitea.io/en-us/config-cheat-sheet/#migrations-migrations

**Comment by zeripath** [comment]
There are very good reasons for not allowing this by default - and we should have disallowed these from the start. I do, however, apologize for the very late merging of this change. I can see that this would be surprising if you were following the RCs or master closely.
