### ISSUE TITLE
Commits log remains blank.

### ISSUE THREAD

**Issue by MNickelson** [go-gitea/gitea#1384]
- Gitea version (or commit ref): 1.1.0+75-g6a451a2b
- Git version: 2.8.3
- Operating system: Docker (latest), Debian testing host
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X] No
  - [ ] Not relevant
- Log gist:

## Description
When I create a new repository I can push/pull and everything seems to be working, but the commit log never updates (when I go to the code tab I see the Quick Guide and how to clone the repo).
I saw a similar issue with gogs when the first push used ssh but was able to work around it by using http. Neither way seems to help with gitea.

**Comment by lunny** [comment]
Do you have follow the upgrade docs? https://docs.gitea.io/en-us/upgrade-from-gogs/

**Comment by MNickelson** [comment]
I didn't actually end up running an upgrade from GoGs, since I'm using docker and didn't have too many repositories yet, I just started over with a fresh container. Repositories that are mirrored from github seem to work fine, it's newly created Gitea repositories that are having this issue.

I did just go check the directory structure and app.ini file just to be sure though, and everything there seems to be in order.

**Comment by lunny** [comment]
And there is any log?

**Comment by MNickelson** [comment]
I cleared out gitea/log then created and pushed to a new repository.
It created an empty serv.log file and an xorm.log file that has 5 SQL select statments and one update statement that doesn't look particularly interesting, but I can upload if it might help.

**Comment by MNickelson** [comment]
I found part of the problem.
If I have "Initialize this repository with selected files and template" when it is created in gitea everything works as expected, but merging in my original branch is giving problems.
If that box is not checked I never see anything in the commit log.
