### ISSUE TITLE
CLI usage docs appear to be wrong/misleading

### ISSUE THREAD

**Issue by bugsduggan** [go-gitea/gitea#13859]
- Gitea version (or commit ref): 1.12.6
- Git version: 2.25.1
- Operating system: Ubuntu 20.04.1 LTS
- Installed from binary download
- Running on the command line
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
- Log gist: N/A

## Description

I was looking to list all users at the command line, which (according to the [docs](https://docs.gitea.io/en-us/command-line/#admin) ), should be as easy as running `gitea admin user list`. However, when I do that, I get `No help topic for 'user'`.

Running `gitea admin --help` only lists the following subcommands:

- `create-user`
- `change-password`
- `repo-sync-releases`
- `regenerate`
- `auth`

**Comment by techknowlogick** [comment]
This has changed in a later version, and the docs match that version. The PR where this has changed is: https://github.com/go-gitea/gitea/pull/10492
