### ISSUE TITLE
UI broken at the installation page.

### ISSUE THREAD

**Issue by YamiOdymel** [go-gitea/gitea#1385]
- Gitea version (or commit ref):  1.1.0+75-g6a451a2b 

## Description

UI broken at the installation page.

## Screenshots

![screen shot 2017-03-26 at 2 49 35 am](https://cloud.githubusercontent.com/assets/7308718/24325214/011c316a-11cf-11e7-8f44-d3cf7cd9e6de.png)

**Comment by tboerger** [comment]
Duplicate of https://github.com/go-gitea/gitea/issues/1343
