### ISSUE TITLE
PR inline comments shown off by one line

### ISSUE THREAD

**Issue by noerw** [go-gitea/gitea#13866]
- Gitea version (or commit ref): 1.14.0+dev-290-gb1cf7f4df (current gitea.com)

## Description
In the main view of a PR, inline comments are attached to one line below where they were created

## Screenshots
PR files view
![grafik](https://user-images.githubusercontent.com/7880552/101267094-1b011f80-374d-11eb-8d77-e639688efdfb.png)

PR main view
![grafik](https://user-images.githubusercontent.com/7880552/101267100-35d39400-374d-11eb-9e84-12d3aceb1e2d.png)

**Comment by noerw** [comment]
Actually, the line this is attached to does not exist at all in the final PR, only in an intermediate commit (which was pushed earlier than the comment was made)

**Comment by jpraet** [comment]
Same as #13683 I think.

**Comment by noerw** [comment]
indeed, thank you. closing as duplicate
