### ISSUE TITLE
GITEA - Localhost was not loaded because its mime is not text/css

### ISSUE THREAD

**Issue by pnvsri** [go-gitea/gitea#13874]
I have installed GITEA through docker in the docker-compose.yml file and able to open the url using the local host but the page is not loading properly and when verified we found as Localhost was not loaded because its mime is not text/css, could anyone help us how to resolve this.
![Style sheet](https://user-images.githubusercontent.com/56759923/101279731-438b2700-37ea-11eb-8389-62a8a5468a25.jpg)

**Comment by lafriks** [comment]
Looks like invalid proxy cobfiguration

**Comment by pnvsri** [comment]
Hi lauris,

We are using any proxy

Thanks
Paramesh



Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by bobemoe** [comment]
Gitea loads its CSS from `/css/index.css?v=xxx` but your error looks like the browser is trying to load `/` as a CSS file? 

I would expect `/` to be HTML.

What page are you on? Can you view the source and verify what any `<link rel="stylesheet" href="???">` tags say?

**Comment by jhult** [comment]
Not sure if this is related to #15655.
