### ISSUE TITLE
Grant admin based on group member in LDAP Autthenication

### ISSUE THREAD

**Issue by badjman** [go-gitea/gitea#13878]
- Gitea version (or commit ref): 1.30.0
- Git version: N/A
- Operating system:
  N/A
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] N/A
  - [ ] Yes (provide example URL)
  - [ ] No
- Log gist:
  N/A
## Description

It would be nice to extend the "Verify Group Membership" option in LDAP Authentication to allow for us to search for Group Member for Admins. IE;

- dc=test,dc=local
  - ou=Groups
    - cn=admin
    - cn=user
  - ou=Users
    - cn=Admin
    - cn=User

Admin is apart of the admin group,
User is apart of the user group.

Admin has site admin privileges, whereas users only have user privilege.
This could be also useful to extend it on restricted and disabled users.

## Screenshots

N/A

**Comment by zeripath** [comment]
Can't you use the admin filter?

**Comment by badjman** [comment]
The admin filter, if I understood the documentation correctly, only looks at the users attributes, not looking through groups for a matching user.

**Comment by wxiaoguang** [comment]
Now there is a group mapping feature.

**Comment by wxiaoguang** [comment]
![image](https://user-images.githubusercontent.com/2114189/163669094-833d1b93-c886-4815-9901-9071365e7368.png)


The admin filter should work. You can use the filter to match the group
