### ISSUE TITLE
Hosting Gitea on a web server like GoDaddy etc.

### ISSUE THREAD

**Issue by 0xC0ba1t** [go-gitea/gitea#13870]
Hi,
When I run the Gitea binary for my platform,
In the installation page I give my domain name (www.codehub.cybersafe.ezyro.com),
It does not work,
If I go to the page (www.codehub.cybersafe.ezyro.com) it won't load Gitea interface, just the "Directory Listing".
I search on Google this same thing but there's no article that shows me how to do it.
Thanks!

**Comment by 6543** [comment]
@AdityaCyberSafe you do **not** need a webspace, you need a server you can run gitea on

search vor vServer Hosting :)

**Comment by AdityaCyberSafe** [comment]
Thanks

**Comment by AdityaCyberSafe** [comment]
But isn't there a way to host on a cpanel hosting?
Thanks in advance

**Comment by AdityaCyberSafe** [comment]
@6543 hello?

**Comment by silverwind** [comment]
No, Gitea does not run on PHP hosting services, you need a virtual machine.
