### ISSUE TITLE
On dashboard feed, avatar func create nil exeption

### ISSUE THREAD

**Issue by wanhuasong** [go-gitea/gitea#13883]
- Gitea version (or commit ref): latest docker image comment 1.14.0+dev-325-gf74a094fd
- Git version: ignore
- Operating system: ignore
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
- Log gist:

## Description

I upgrade from gitea/gitea@sha256:daf33224f2a2b186eb8de97814c1d1934038c2ba08627dca5967109cae3f2829(`1.13.0+dev-276-g217647f33`) to gitea/gitea:latest(`1.14.0+dev-325-gf74a094fd`), appeared follow problem when I visit the index page of selfhosted gitea

```
template: user/dashboard/feeds:4:5: executing "user/dashboard/feeds" at <avatar .ActUser>: error calling avatar: runtime error: invalid memory address or nil pointer dereference

```

## Screenshots

screenshots shows content above

**Comment by lunny** [comment]
It may related with #13649

**Comment by techknowlogick** [comment]
Do you use custom templates?

**Comment by 6543** [comment]
we have to look why .ActUser is nil & make the avatar function resistant against nil argument ...
cc @silverwind

**Comment by silverwind** [comment]
Hmm, might have something to do with `a.loadActUser()` which the previous implementation did call but the current one doesn't.

https://github.com/go-gitea/gitea/pull/13649/files#diff-94580350088fd8ad06447d2eb73bc35e1fd2372f11078a0f9142038808328d13L145

**Comment by silverwind** [comment]
May need to introduce a `avatarByAction` that does this `.loadActUser()`. Are there any steps to reproduce the issue? It didn't show up during my testing.

**Comment by silverwind** [comment]
https://github.com/go-gitea/gitea/pull/13909

**Comment by wanhuasong** [comment]
Fixed, thanks.
