### ISSUE TITLE
Edit new wiki page is not working in binary package installation

### ISSUE THREAD

**Issue by strusberg** [go-gitea/gitea#13889]
- Gitea version (or commit ref): 1.13.0
- Git version: 2.25.1
- Operating system: Linux (Ubuntu 20.04 LTS)
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
- Log gist:

## Description

When you try to create a new wiki page the edit area is not showing.
...

**Comment by jolheiser** [comment]
What errors are you getting? I cannot reproduce on try or my 1.13.0 instance.

**Comment by strusberg** [comment]
Just do not show the edition area:

![image](https://user-images.githubusercontent.com/295511/101387297-a20cdf80-3894-11eb-8f54-c4482f6a59cf.png)

the server report:

![image](https://user-images.githubusercontent.com/295511/101387155-74279b00-3894-11eb-9749-e335b86ddd68.png)

the 1.13.0 instance is running from binary installation gitea-1.13.0-linux-386

**Comment by jolheiser** [comment]
Are you using custom templates? As I mentioned in #13888, EasyMDE was added to 1.14, it should not be in any 1.13 templates.

**Comment by strusberg** [comment]
No, I am not using custom templates yet. It is the original installation.

**Comment by jolheiser** [comment]
Are you sure you're running 1.13, then?

Downloading and extracting https://dl.gitea.io/gitea/1.13.0/gitea-src-1.13.0.tar.gz I see simplemde.

The version should be in the footer of any page. Alternatively, you can see the entire version at `https://domain.tld/admin/config`

**Comment by jolheiser** [comment]
Alternatively, you can try to re-download a binary, but as far as I can tell no 1.13.0 binary should be pointing to easymde.

**Comment by strusberg** [comment]
> Are you sure you're running 1.13, then?
> 
> Downloading and extracting https://dl.gitea.io/gitea/1.13.0/gitea-src-1.13.0.tar.gz I see simplemde.
> 
> The version should be in the footer of any page. Alternatively, you can see the entire version at `https://domain.tld/admin/config`

Yes, 

![image](https://user-images.githubusercontent.com/295511/101388774-ccf83300-3896-11eb-92e8-abed51c8e4d0.png)

**Comment by strusberg** [comment]
> Alternatively, you can try to re-download a binary, but as far as I can tell no 1.13.0 binary should be pointing to easymde.

I did it.  I tried the development branch binary. Same issue.

**Comment by jolheiser** [comment]
My only other guess then is a custom template (again)? You don't have any templates in your custom directory?
The path for the custom directory should also be shown on that `admin/config` page.

**Comment by strusberg** [comment]
You are right. A new footer.tpl was in the custom directory and reference the wrong file (easymde.js). I really appreciate your time for this support. My apologies.

The wiki area is working now.

**Comment by jolheiser** [comment]
Happy to help! 🙂
