### ISSUE TITLE
Project boards: Emojis in Labels missing

### ISSUE THREAD

**Issue by modmew8** [go-gitea/gitea#13880]
- Gitea version (or commit ref): 1.13.0
- Git version: 2.14.3
- Operating system: Ubuntu Server 18.04.5
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL) https://try.gitea.io/modmew8/LabelEmojiTest/projects/400
  - [ ] No

## Description

Currently emojis in labels on project boards are not being replaced:

![grafik](https://user-images.githubusercontent.com/6024058/101301299-ad322200-3838-11eb-9a11-db32d933c68f.png)

In comparison to the issue list:

![grafik](https://user-images.githubusercontent.com/6024058/101301337-c76c0000-3838-11eb-977a-c92bd8fcc681.png)

## The fix

I'm currently unable to deploy and create a pull request myself, but this one line in `templates/repo/projects/view.tmpl` would need a replacement (line 163 on master): (replacing `{{.Name}}` with `{{.Name | RenderEmoji}}`)

```
<a class="ui label has-emoji" href="{{$.RepoLink}}/issues?labels={{.ID}}" style="color: {{.ForegroundColor}}; background-color: {{.Color}}; margin-bottom: 3px;" title="{{.Description}}">{{.Name}}</a>
```
to
```
<a class="ui label has-emoji" href="{{$.RepoLink}}/issues?labels={{.ID}}" style="color: {{.ForegroundColor}}; background-color: {{.Color}}; margin-bottom: 3px;" title="{{.Description}}">{{.Name | RenderEmoji}}</a>
```

Maybe someone can try out and validate, I just tested it by creating `custom/templates/repo/projects/view.tmpl` and replacing this single line, resulting in the correct behaviour:

![grafik](https://user-images.githubusercontent.com/6024058/101301563-832d2f80-3839-11eb-869f-bafc609cc749.png)

**Comment by 6543** [comment]
@modmew8 can you send a pull :)
