### ISSUE TITLE
easymde.js missing in amd64 binary package for v1.13.0

### ISSUE THREAD

**Issue by strusberg** [go-gitea/gitea#13888]
- Gitea version (or commit ref): 1.13.0
- Git version: 2.25.1
- Operating system: Linux (Ubuntu 20.04 LTS)
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ x] No
- Log gist:

## Description
The easymde.js file is missing in binary gitea-1.13.0-linux-amd64 therefore wiki page edition is not working.

GET /js/easymde.js?v=a4729905ff114b8772756edddf6ef3f4 404 Not Found

...

**Comment by jolheiser** [comment]
That's because EasyMDE is going to be in [1.14.0](https://github.com/go-gitea/gitea/pull/13333).
