### ISSUE TITLE
mirror a repositoriy does sync anymore after updating to 1.13.0

### ISSUE THREAD

**Issue by markuman** [go-gitea/gitea#13899]
- Gitea version (or commit ref): gitea/gitea:1.13.0 
- Git version:
- Operating system:
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
  - [x] Mariadb
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
- Log gist:

## Description

Since I've updated from 1.12.6 to 1.13.0, all mirror repositories does not sync anymore.

Example https://git.osuv.de/mirror/gitea

"Synchronize Now" does not change this behaviour. Furthermore, there isn't any error in the logs.

![Screenshot_2020-12-08 gitea](https://user-images.githubusercontent.com/3920157/101467564-c1fadc80-3942-11eb-962c-ad9e4655943a.png)

**Comment by 6543** [comment]
@markuman have you checked the cron settings?

https://docs.gitea.io/en-us/config-cheat-sheet/#cron-cron

**Comment by markuman** [comment]
It was not defined.  
After set it to

```
[cron]
ENABLED = true

[cron.update_mirrors]
SCHEDULE = @every 10m
```

it worked again.

**Comment by markuman** [comment]
This does not seems to fix this issue permanentely.  
After update the configuration as mentioned above, I've restarted the gitea container which result in syncing all repositories once.  
Now they are all outdated again and nothing happens.  
Any ideas?

**Comment by zeripath** [comment]
I'll need to see your app.ini.

On gitea/admin/monitor when is the next time this is due to run?

**Comment by markuman** [comment]
![Screenshot_2020-12-18 Gitea Git with a cup of tea](https://user-images.githubusercontent.com/3920157/102612012-4e21b680-4130-11eb-91d8-5f5bc2681b05.png)

![Screenshot_2020-12-18 Gitea Git with a cup of tea(1)](https://user-images.githubusercontent.com/3920157/102612017-4feb7a00-4130-11eb-8779-d53c51d09e2b.png)

**Comment by markuman** [comment]
@zeripath 

```
$ sudo cat app.ini 
APP_NAME = Gitea: Git with a cup of tea
RUN_MODE = prod

[repository]
ROOT = /data/git/

[repository.local]
LOCAL_COPY_PATH = /data/gitea/tmp/local-repo

[repository.upload]
TEMP_PATH = /data/gitea/uploads

[server]
APP_DATA_PATH    = /data/gitea
SSH_DOMAIN       = git.osuv.de
HTTP_PORT        = 3000
ROOT_URL         = https://git.osuv.de/
DISABLE_SSH      = false
SSH_PORT         = 22
LFS_CONTENT_PATH = /data/git/lfs

[database]
PATH    = /data/gitea/gitea.db
DB_TYPE = mysql
HOST    = mariadb
NAME    = gitea
USER    = gitea
PASSWD  = ...
LOG_SQL = false
CHARSET = utf8mb4

[indexer]
ISSUE_INDEXER_PATH = /data/gitea/indexers/issues.bleve

[session]
PROVIDER_CONFIG = /data/gitea/sessions

[picture]
AVATAR_UPLOAD_PATH = /data/gitea/avatars

[attachment]
PATH = /data/gitea/attachments

[log]
ROOT_PATH = %(GITEA_WORK_DIR)/log
MODE = console
LEVEL = Info
STACKTRACE_LEVEL = None
REDIRECT_MACARON_LOG = false
ENABLE_ACCESS_LOG = false
ENABLE_XORM_LOG = true
XORM = ,
ACCESS = ,

[log.console]
MODE                = console
LEVEL               = info
PREFIX              = 
COLORIZE            = true
ACCESS_LOG_TEMPLATE = {{.Ctx.RemoteAddr}} {{.Ctx.Req.Method}} {{.Ctx.Req.RequestURI}} {{.ResponseWriter.Status}} "{{.Ctx.Req.Referer}}\" \"{{.Ctx.Req.UserAgent}}"

[security]
INSTALL_LOCK   = true
SECRET_KEY     = ...
INTERNAL_TOKEN = ...

[service]
DISABLE_REGISTRATION = true
REQUIRE_SIGNIN_VIEW  = false

[oauth2]
JWT_SECRET = ...

[cron]
ENABLED = true

[cron.update_mirrors]
SCHEDULE = @every 10m

[cron.git_gc_repos]
ENABLED = true
```

**Comment by markuman** [comment]
I deleted the ara mirror and restart the container.  
No idea what was wrong with that mirror. There is no error log about it.  
I hope mirroring is working now.

**Comment by markuman** [comment]
it seems there was one repo which was blocking everything.  
I cannot say what was happen again, because there are no error logs about it.
