### ISSUE TITLE
Webhooks api stopped working

### ISSUE THREAD

**Issue by bobemoe** [go-gitea/gitea#13907]
- Gitea version (or commit ref): 1.14.0+dev-337-g42354dfe4
- Git version:
- Operating system:
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
- Log gist:

## Description

After upgrading from a db version 160 to 162 I get the following error when trying to add a new webhook:

`Error 1366: Incorrect integer value: 'gitea' for column git.webhook.hook_task_type`

Also Drone integration hooks are failing. Probably others too.

Maybe the migration is incomplete? https://github.com/go-gitea/gitea/pull/13664

**Comment by bobemoe** [comment]
Thanks @lunny, the error has changed now, looks like the DB is good and I can create webhook from the web interface. :)

I'm still having trouble getting Drone to create its webhook over the API. Its getting `There was a problem enabling your repository. Unprocessable Entity.`  Not many clues in the logs but if I try to create webhook using swagger the response is: `{"  "message": "Invalid hook type"}` which looks like it is being thrown from https://github.com/go-gitea/gitea/blob/bc1cf6e5d365265d18144a2afae25ca04df691b8/routers/api/v1/utils/hook.go#L54-L58

**Comment by bobemoe** [comment]
What are the valid hook types? I tried `gitea`, `Gitea` and `3` from the API, all with same response.  Has it changed? Wondering if this is a BC break and Drone itself will need updating?

**Comment by bobemoe** [comment]
I might have fixed this... just testing, will PR soon

**Comment by bobemoe** [comment]
Nope. Ignore previous message, I can't get it to work. No PR coming :(

**Comment by lunny** [comment]
@bobemoe Please confirm #13937 fixed this.

**Comment by bobemoe** [comment]
I think the error is still there but I'm having trouble getting a complied version to work in my drone environment. I don't supposed there is a linux-amd64 compiled version available for download?

**Comment by pat-s** [comment]
I also see issues enabling drone repos on latest gitea master - could be related to this issue here.

**Comment by bobemoe** [comment]
I can confirm the bug is still present on #13937 and master.

Using older version (1.12.6) I am able to create webhook over api using swagger ​/repos​/{owner}​/{repo}​/hooks
 and body:

```
{
  "active": true,
  "branch_filter": "master",
  "config": {
      "url":"http://test.local",
     "content_type":"json"
  },
  "events": [
    "push"
  ],
  "type": "gitea"
}
```

But on  #13937 and master I get the `{"message": "Invalid hook type"}` response
