### ISSUE TITLE
API endpoints not returning issue tag/branch

### ISSUE THREAD

**Issue by dusatvoj** [go-gitea/gitea#13918]
- Gitea version (or commit ref):  1.13.0
- Git version: 2.20.1
- Operating system: Debian 10
  
  
  
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
- Log gist:

## Description

If I'm not blind, Gitea API not returning tag / branch assigned to the issue
I've tried:
 - https://try.gitea.io/api/swagger#/issue/issueListIssues
 - https://try.gitea.io/api/swagger#/issue/issueGetIssue

... And searching through whole page but not found

**Comment by a1012112796** [comment]
It's here, aren't them?
![2020-12-10 11-23-47屏幕截图](https://user-images.githubusercontent.com/25342410/101717629-9a3e7c80-3ada-11eb-90e2-4b388a6c4a62.png)

**Comment by zeripath** [comment]
OK so this is partly because github does not have assigned tag/branch in its API - so we'd need to add it.
