### ISSUE TITLE
git push never finishes

### ISSUE THREAD

**Issue by SigiSigMi** [go-gitea/gitea#13916]
- Gitea version (or commit ref): 1.12.6
- Git version: 2.11.0
- Operating system: Debian GNU/Linux 9 (stretch)
  
  
  
I run the download version, starting as service with systemd.
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
- Log gist:

## Description
Pushing to a repository does not finish.
Same on using ssh or https (unfortunately in German):
```
$ git push gitea
Objekte aufzählen: 112, Fertig.
Zähle Objekte: 100% (108/108), Fertig.
Delta-Kompression verwendet bis zu 8 Threads.
Komprimiere Objekte: 100% (68/68), Fertig.
Schreibe Objekte: 100% (102/102), 278.02 KiB | 27.80 MiB/s, Fertig.
Gesamt 102 (Delta 13), Wiederverwendet 84 (Delta 1), Pack wiederverwendet 0
remote: Resolving deltas: 100% (13/13), completed with 5 local objects.
```
after a long time i get:
```
client_loop: send disconnect: Broken pipe
fatal: Die Gegenseite hat unerwartet abgebrochen.
fatal: Die Gegenseite hat unerwartet abgebrochen.
```
but this seems to be a ssh timeout.
Using http is the same, push does not finish.

However, i can push to other repos without any problem.

Starting with 'RUN_MODE=dev' does not increase log output:

/var/log/daemon.log:
```
Nov 27 10:17:40 mn-srv1 systemd[1]: Started Session 9182 of user gitea.
Nov 27 10:17:41 mn-srv1 gitea[19854]: [Macaron] 2020-11-27 10:17:41: Started GET /api/internal/serv/command/3/<username>/atbqt?mode=2&verb=git-receive-pack for [::1]
Nov 27 10:17:41 mn-srv1 gitea[19854]: [Macaron] #033[1;32m2020-11-27 10:17:41: Completed GET /api/internal/serv/command/3/<username>/atbqt?mode=2&verb=git-receive-pack 200 OK in 10.368971ms#033[0m
Nov 27 10:17:43 mn-srv1 gitea[19854]: [Macaron] 2020-11-27 10:17:43: Started POST /api/internal/hook/pre-receive/<username>/atbqt for [::1]
Nov 27 10:17:43 mn-srv1 gitea[19854]: [Macaron] #033[1;32m2020-11-27 10:17:43: Completed POST /api/internal/hook/pre-receive/<username>/atbqt 200 OK in 5.528467ms#033[0m
```
./log/gitea.log seems to be in an endless sql loop, but perhaps this does not have to do anything with my push:
```
2020/11/27 10:18:52 ...m.io/xorm/core/db.go:154:QueryContext() [I] [SQL] SELECT user_id, count(*) AS count FROM notification WHERE user_id IN (SELECT user_id FROM notification WHERE updated_unix >= ? AND updated_unix < ?) AND status = ? GROUP BY user_id [1606468720 1606468730 1] - 378.451µs
2020/11/27 10:19:02 ...m.io/xorm/core/db.go:154:QueryContext() [I] [SQL] SELECT user_id, count(*) AS count FROM notification WHERE user_id IN (SELECT user_id FROM notification WHERE updated_unix >= ? AND updated_unix < ?) AND status = ? GROUP BY user_id [1606468730 1606468740 1] - 348.02µs
2020/11/27 10:19:12 ...m.io/xorm/core/db.go:154:QueryContext() [I] [SQL] SELECT user_id, count(*) AS count FROM notification WHERE user_id IN (SELECT user_id FROM notification WHERE updated_unix >= ? AND updated_unix < ?) AND status = ? GROUP BY user_id [1606468740 1606468750 1] - 322.885µs
2020/11/27 10:19:22 ...m.io/xorm/core/db.go:154:QueryContext() [I] [SQL] SELECT user_id, count(*) AS count FROM notification WHERE user_id IN (SELECT user_id FROM notification WHERE updated_unix >= ? AND updated_unix < ?) AND status = ? GROUP BY user_id [1606468750 1606468760 1] - 345.685µs
```

Are there any other logs i can provide?
Before this, the system run without any problem for years and also this repository could be used for long time without any problem.

...

**Comment by SigiSigMi** [comment]
I did some further checks:

- Cloning into a new repository and pushing to this works correctly.

- Yesterday i upgraded to Gitea 1.13.0 but still same issue. Today also with the cloned repository.

**Comment by zeripath** [comment]
Please check and ensure that there aren't other hooks in the pre-receive.d/ and post-receive.d/ folders.

Please read https://docs.gitea.io/en-us/logging-configuration/#debugging-problems and set your logging to debug with the configuration recommended by the issue template.

**Comment by SigiSigMi** [comment]
@zeripath: Thanks for this hint.
It is indeed a repository with a pre-receive hook.
I removed all files in pre-receive.d/ folder and i can push now my changes without any problem.

Anyway, some additional observations:

- I had a lot of `git diff` processes on the machine, supposedly from unfinished push operations...

- The tab 'hooks' in repository settings i not available anymore. I can not say when it has disappeared. But i am not able to access hooks via the web interface.

- Regarding the running git diff processes and because i have not changed my pre-receive hook for month. It is somehow weird and i wonder what caused the issue.

Currently, for me, this issue can be regarded as closed but some day i want to reuse my hook and do some debug.
Please let me know, if i can provide further logs or some additional info.

**Comment by zeripath** [comment]
> @zeripath: Thanks for this hint.
> It is indeed a repository with a pre-receive hook.
> I removed all files in pre-receive.d/ folder and i can push now my changes without any problem.

Hopefully not all of them - gitea still needs its hook.

> Anyway, some additional observations:
> 
> * I had a lot of `git diff` processes on the machine, supposedly from unfinished push operations...

If these were started by Gitea they're very likely listed in the process manager. If they weren't just kill them or restart the server.

> * The tab 'hooks' in repository settings i not available anymore. I can not say when it has disappeared. But i am not able to access hooks via the web interface.

https://docs.gitea.io/en-us/config-cheat-sheet/#security-security

`DISABLE_GIT_HOOKS` now defaults to `true`. If you want to be able to edit them from within Gitea - and are aware of the risks - switch that back to `false`

> * Regarding the running git diff processes and because i have not changed my pre-receive hook for month. It is somehow weird and i wonder what caused the issue.

Without seeing the hook code I couldn't possibly comment as to what the issue would be.

> Currently, for me, this issue can be regarded as closed but some day i want to reuse my hook and do some debug.
> Please let me know, if i can provide further logs or some additional info.

Could take the code to discord to discuss further. However, I'll close this issue now.
