### ISSUE TITLE
rootless docker images are not tagged with a version number

### ISSUE THREAD

**Issue by nmasse-itix** [go-gitea/gitea#13914]
## Description

I'm using the Gitea "rootless" docker images from https://hub.docker.com/r/gitea/gitea/tags?page=1&ordering=last_updated

There are `latest-rootless`, `linux-amd64-rootless` and `linux-arm64-rootless` tags but it seems to be a nightly build. 

For the released versions (`1.13`, `1.12`, ...) I could not find the matching "-rootless" tag.

Would it be possible to also generate and tag images for the released versions of Gitea ? For instance, `1.13-rootless`, `1.12-rootess`...

**Comment by zeripath** [comment]
The rootless docker was created in #10154 which is after 1.13 was branched. It is not present in 1.12 or 1.13. 

(It could be backported to 1.13 as far as I can see - but you would be better off commenting on the PR directly asking for a backport I think.)

**Comment by nmasse-itix** [comment]
Oh, I missed that point. So it means rootless images will be correctly tagged for the upcoming releases. Thanks for the precision !
