### ISSUE TITLE
Error on PR creating with previously forked repository

### ISSUE THREAD

**Issue by gruo** [go-gitea/gitea#13910]
- Gitea version (or commit ref): 1.13.0
- Git version:
- Operating system: Debian 10.6, binary release using systemd
  
  
  
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
- Log gist:

```
2020/12/09 07:58:56 ...ervices/pull/pull.go:421:PushToBaseRepo() [E] Unable to push PR head for LVTemplate/1900#382 (146:LVTemplate/1900:refs/pull/382/head) due to Error: exit status 1 - Invalid remote name "/srv/repositories/lvtemplate/1900.git": Invalid remote name: "/srv/repositories/lvtemplate/1900.git"
2020/12/09 07:58:56 routers/repo/pull.go:1039:CompareAndPullRequestPost() [E] NewPullRequest: Push: LVTemplate/1900:bugfix/inertGas LVTemplate/1900:refs/pull/382/head exit status 1 - Invalid remote name "/srv/repositories/lvtemplate/1900.git": Invalid remote name: "/srv/repositories/lvtemplate/1900.git"
```

## Description

There is a repository which once had some forks around. This usage scenario did not quite match our requirements, so I manually removed the forks once. The web interface shows no forks, so does the database in the table `repository` with columns `is_fork`, `fork_id` and `num_forks`.

When creating a PR inside this particular repository the user gets a 500. The PR is created nethertheless in the background, but shows message attached as screenshot.

The log information do not help either, because the remote seems right. The path exists and is the correct one.

How to fix this behavior? There must be some fork information which I did not remove yet.

Thanks in advance.

## Screenshots

![fork-error](https://user-images.githubusercontent.com/10697822/101600708-fb435300-39fb-11eb-8232-2cc93efc187e.png)

**Edit:** Fixed gitea version.

**Comment by zeripath** [comment]
Does /srv/repositories/lvtemplate/1900.git still exist?

**Comment by techknowlogick** [comment]
`Gitea version 1.15.0` doesn't exist, I suspect you are referencing golang version. Could you provide the version of Gitea you are using?

**Comment by NepPure** [comment]
v1.13.0 face the same problem for a normal repo.

Other repos are able to create merge requests normally.

Logs like
```
 Invalid remote name: "XX"
```
Actually the path XX exists.

No other special logs were found.

**Comment by NepPure** [comment]
May be related to #13597 

Probolem repo has LFS.

**Comment by gruo** [comment]
Fixed the wrong version. The problem was firsted visible in 1.12.5 and now in the most recent release.

@zeripath The path does exist and is writable. It is a single repository which works in every aspect except PRs. It once had forks.

@NepPure The repository is using LFS.

I now notice the other issue, which seems to be the problem. I'll investigate in a second.

**Comment by gruo** [comment]
I removed a bunch of hooks which did only check for LFS. Now the PR (created again) does not show this particular error message anymore.

Thanks, especially @NepPure. Sorry for the diplicate.
