### ISSUE TITLE
Skip 2FA with OpenID Connect 

### ISSUE THREAD

**Issue by kowalski7cc** [go-gitea/gitea#13939]
- Gitea version (or commit ref): 1.14.0+dev-353-gccfa40889

## Description

I have my OIDC provider which already asks for 2FA, but having 2FA enabled in Gitea makes users go through double 2FA authentication, which can be annoying.
Can you add an option to skip Gitea's 2FA when login in from an OIDC provider?

Thanks

**Comment by asifbacchus** [comment]
Any updates on this or ideas for a work-around?
