### ISSUE TITLE
Docker: Environment variables to set openssh server port / disable openssh

### ISSUE THREAD

**Issue by FredFoo** [go-gitea/gitea#13944]
- Gitea version (or commit ref): latest image from hub.docker.com

## Description
I would like to disable the start of opensshd in the docker image and use the gitea built-in ssh. Perhaps the shortest way would be by an environment variable or a small config that you could put into /data/gitea/ssh.

At the same time you could think of allowing the port for the openssh to be configured the same way - i.e enviroment or config file - so that ppl who want to use the built-in ssh for git operations but provide openssh on a different port in case anyone would need to provide shell access. 

Just an idea.

And just to be complete: currently I build my own image from gitea/gitea:latest and move /etc/s6/openssh to /root. Does do the job, but was just thinking I might not be alone with the wish to keep it down. 

...

**Comment by zeripath** [comment]
have you considered using the rootless docker?
