### ISSUE TITLE
Block password-only auth when 2FA is enabled

### ISSUE THREAD

**Issue by rugk** [go-gitea/gitea#1394]
- Gitea version (or commit ref): 1.1.0
- Operating system: Debian
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
  - [x] Not tested yet

## Description

When 2FA is enabled Gitea should block the authentication via password and require auth tokens.
The current behaviour is to allow authentication via git even with 2FA enabled. This, however, defeats the whole point of 2FA: This way users/attackers can perform git actions (aka login, push code, etc.) without authenticating with the 2FA method.

**Comment by lunny** [comment]
@minecrafter maybe you can see this issue.

**Comment by minecrafter** [comment]
I might be able to find time to work on this next week.

**Comment by moritzheiber** [comment]
@minecrafter This is a serious security issue, as users are able to circumvent 2FA with regular Git commands .. could this be re-prioritized? IMHO it needs fixing yesterday :frowning:
