### ISSUE TITLE
panic on git push --tags origin

### ISSUE THREAD

**Issue by yukunyi** [go-gitea/gitea#13940]
- Gitea version (or commit ref): 1.14.0+dev-359-gc11cf4bb3
- Git version: 2.26.2
- Operating system: docker of debian
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
- Log gist:

## Description

when do `git push --tags origin`
console output
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x188e394]

goroutine 102 [running]:
code.gitea.io/gitea/modules/notification/action.(*actionNotifier).NotifyCreateRef(0x540fc78, 0x0, 0xc00000cb40, 0x29cab51, 0x3, 0xc008f26540, 0x1b)
	/go/src/code.gitea.io/gitea/modules/notification/action/action.go:317 +0x74
code.gitea.io/gitea/modules/notification.NotifyCreateRef(0x0, 0xc00000cb40, 0x29cab51, 0x3, 0xc008f26540, 0x1b)
	/go/src/code.gitea.io/gitea/modules/notification/notification.go:248 +0xae
code.gitea.io/gitea/services/repository.pushUpdates(0xc0079435e8, 0x1, 0x1, 0x0, 0x0)
	/go/src/code.gitea.io/gitea/services/repository/push.go:106 +0x7d6
code.gitea.io/gitea/services/repository.handle(0xc00255a000, 0x1, 0x14)
	/go/src/code.gitea.io/gitea/services/repository/push.go:32 +0x87
code.gitea.io/gitea/modules/queue.(*WorkerPool).doWork(0xc0011b8380, 0x3d06360, 0xc001324300)
	/go/src/code.gitea.io/gitea/modules/queue/workerpool.go:383 +0x896
code.gitea.io/gitea/modules/queue.(*WorkerPool).addWorkers.func1(0xc0011b8380, 0x3d06360, 0xc001324300)
	/go/src/code.gitea.io/gitea/modules/queue/workerpool.go:238 +0x45
created by code.gitea.io/gitea/modules/queue.(*WorkerPool).addWorkers
	/go/src/code.gitea.io/gitea/modules/queue/workerpool.go:237 +0x56
Received signal 15; terminating.

```
After the automatic restart, there is no related operation prompt in the UI list, nor in the tags list of the warehouse.

**Comment by zeripath** [comment]
It looks like this is a result of #13381.

---

The panic occurs here:

https://github.com/go-gitea/gitea/blob/b35546631e1efecbdae905d3925c5d76f9b96ded/modules/notification/action/action.go#L317

this implies that doer is nil... The function is called by:

https://github.com/go-gitea/gitea/blob/b35546631e1efecbdae905d3925c5d76f9b96ded/modules/notification/notification.go#L248

and

https://github.com/go-gitea/gitea/blob/master/services/repository/push.go#L106


However as we can see here: 

https://github.com/go-gitea/gitea/blob/b35546631e1efecbdae905d3925c5d76f9b96ded/services/repository/push.go#L92

pusher doesn't get set by anything for this call...

https://github.com/go-gitea/gitea/blob/b35546631e1efecbdae905d3925c5d76f9b96ded/services/repository/push.go#L109-L114 needs to be copied to line100 .
