### ISSUE TITLE
Support for LDAP and AD Group sync

### ISSUE THREAD

**Issue by mbuchner** [go-gitea/gitea#1395]
## Description

Add support for LDAP and Active Directory Groups:

see: https://github.com/gogits/gogs/issues/662#issuecomment-227384886

Other good example is the Jenkins LDAP plugin:
https://wiki.jenkins-ci.org/display/JENKINS/LDAP+Plugin

**Comment by tboerger** [comment]
I'm missing exactly this feature now. Difficult to add users to orgs or groups if they have not been signed in at any time

**Comment by divansantana** [comment]
https://github.com/tws-inc/gitea-group-sync exists.

Would be nice if it was merged upstream.

**Comment by pbodnar** [comment]
@divansantana, yes, the *gitea-group-sync* looks like a promising and logical approach until something better gets implemented. I. e. a cron job needs to be setup that does the following:

1. Iterate over existing Organizations and Teams.
2. For every Team, lookup matching Users via a LDAP query.
3. Add / remove corresponding Users in the Team.

For steps 1 and 3, Gitea API (RESTful services) can be used. Not sure if direct access Gitea database would be safe as well. Anyway, for bigger structures the queries to LDAP could be possibly optimized...

Any more ideas?

**Comment by Elias481** [comment]
We are also wanting this feature.
Optimally there would be a field on a team to link it to an explicit ldap group or userfilter.

Otherwise the gitea-group-sync is a quite usefull approach and would be sufficent for at least something. It should include a separate placeholder for organisation and team-name then at least.
And possibly consolidate the list of resulting queries first because I think it wil be quite common to have some same teams in different organisations.

**Comment by pgollor** [comment]
We are also wanting this feature.

**Comment by MasterGroosha** [comment]
We also want this feature

**Comment by ethanmassie** [comment]
We also want this feature

**Comment by eummitu** [comment]
We also want this feature

**Comment by eummitu** [comment]
We also want this feature

**Comment by n-st** [comment]
To express interest, please use the "+1" reaction feature on the first post (as several users have done already). Comments should be preferred for on-topic suggestions and discussions, to avoid unnecessary clutter and notifications for everyone subscribed to this issue.

**Comment by husnusenturk** [comment]
This feaute will be very usefull.

**Comment by EmrahKK** [comment]
+1

**Comment by zeripath** [comment]
There is: https://github.com/tws-inc/gitea-group-sync

**Comment by pgollor** [comment]
I know this project but it didd't work very well for my gitea server and a native integration in gitea itself would be better.

**Comment by zeripath** [comment]
OK - suggest a workable UI and how it could work then it could potentially be implemented.

**Comment by localleon** [comment]
It's semms like [Gitea Group-Sync](https://github.com/tws-inc/gitea-group-sync) is currently the only project that provides this kind of functionality for the Gitea Project. 

We are currently looking for maintainers, because tws-inc can't provide ressources for the project. We are discussing in [tws-inc/gitea-group-sync#9](https://github.com/tws-inc/gitea-group-sync/issues/9)

Is this still a feature that the community would like to see in the official Gitea Project?

**Comment by lachnerd** [comment]
With 1.13.0 there  was a "check for LDAP group membership (#10869)" added - how does this relate to this feature request ?

**Comment by pgollor** [comment]
> 
> 
> With 1.13.0 there was a "check for LDAP group membership (#10869)" added - how does this relate to this feature request ?

I think this is only for the login and not to check the rights for a organisation, or not?

**Comment by svenseeberg** [comment]
How should this work? Some programs have a mapping field, where for example internal attributes are mapped to LDAP attributes. Mapping LDAP groups to Gitea organisations could work the same way. We would then require an input field in the LDAP settings, which for example contains a JSON with the following information: `{"My_Gitea_Org": "cn=MyGroup,cn=groups,dc=example,dc=org"}`. Alternatively, Organisations would need a field in their settings where one could enter LDAP group names?

**Comment by Morriz** [comment]
Why is this still open after 4 years ;(

**Comment by lunny** [comment]
PRs are welcome!

**Comment by Elias481** [comment]
@lunn

> PRs are welcome!

but would that have meant, after another 3 years it's still not merged because of whatever?

**Comment by jolheiser** [comment]
> but would that have meant, after another 3 years it's still not merged because of whatever?

This is an incredibly unhelpful comment. 

None of us are paid to work on this project, and we try to accommodate PRs as much as we can when they come in. 

I suggest putting a bounty on the issue if you would like to incentivize someone to pick it up.

**Comment by Elias481** [comment]
> > but would that have meant, after another 3 years it's still not merged because of whatever?
> 
> This is an incredibly unhelpful comment.
> 
> None of us are paid to work on this project, and we try to accommodate PRs as much as we can when they come in.
> 
> I suggest putting a bounty on the issue if you would like to incentivize someone to pick it up.

You are completely right. I did not really meant this project, on the other hand you also see it here, that kind of slowing things in regards to very helpful ERs.
But definitely, much to many enterprises just leech open source and but it, but not invest even some time the last year's. Horrible wronglyness. On the other hand we have perfect IT above, so for me personally same same is.

**Comment by svenseeberg** [comment]
I started working on this. Feel free to provide feedback or contribute. https://github.com/netzbegruenung/gitea/pull/1. No guarantees if and when this will ever be finished.

**Comment by svenseeberg** [comment]
I think I got the main parts figured out. As I'm totally new to Go and the Gitea code base, I'm accepting advice unconditionally. Feel free to comment in the WiP PR.
