### ISSUE TITLE
Add assignees support to Issue template

### ISSUE THREAD

**Issue by jk-inazczech** [go-gitea/gitea#13955]
- Gitea version (or commit ref): 1.13.0
- Git version: n/a
- Operating system: n/a
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
- Log gist:

## Description
Add support for assignees in ISSUE_TEMPLATE.md in order to add a user directly when creating an issue from a template. This is supported in GitHub ([see docs](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/manually-creating-a-single-issue-template-for-your-repository)).

Example of usage: My colleague is also responsible for a server of the product. Issues related to the server will be always assigned to him. This could ease the process of creation of the issue.

Proposed format:

```
---

name: "Template Name"
about: "This template is for testing!"
title: "[TEST] "
labels:

- bug
- "help needed"

assignees:

- user1

---

This is the template!
```

**Comment by pouya-loyall** [comment]
is there a light at the end of tunnel? 😊

**Comment by lunny** [comment]
I don't think it's very hard but nobody is working on this issue.

**Comment by pouya-loyall** [comment]
Thanks for fixing this.

**Comment by jk-nilo** [comment]
Thanks @Zettat123 for implementation.
