### ISSUE TITLE
create git warehouse exception after running gitea on aarch armx64 platform

### ISSUE THREAD

**Issue by mirroro** [go-gitea/gitea#13965]
- Gitea version (or commit ref):1.13.0
- Git version:2.23.0
- Operating system:aarch armx64
  
  
  
- Database (use `[4]`):
  - [ 1] PostgreSQL
  - [ 2] MySQL
  - [ 3 ] MSSQL
  - [ 4] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ YES] Yes (provide example URL)
  - [ ] No
- Log gist:

## Description
There was an error when I created a git repository，The error message is as follows
...
routers/repo/repo.go:183:handleCreateError() [E] CreatePost: initRepository: initRepoCommit: git push: exit status 1 - remote: env: can't execute 'bash': No such file or directory        
        To /data/repository/GitRepository/caifenglin/test.git
         ! [remote rejected] HEAD -> master (pre-receive hook declined)
        error: failed to push some refs to '/data/repository/GitRepository/caifenglin/test.git'

2020/12/12 16:17:02 Completed POST /repo/create 500 Internal Server Error in 254.725283ms
2020/12/12 16:17:02 Started GET /user/avatar/caifenglin/-1 for 192.168.8.245
2020/12/12 16:17:02 Completed GET /user/avatar/caifenglin/-1 302 Found in 26.654949ms
2020/12/12 16:17:02 Started GET /user/events for 192.168.8.245
2020/12/12 16:17:37 Completed GET /user/events 200 OK in 35.456514441s
...

**Comment by caifenglin** [comment]
The reason is that Bash is not installed on my system. Sorry
