### ISSUE TITLE
Gitea as service not starting after reboot

### ISSUE THREAD

**Issue by somera** [go-gitea/gitea#13963]
- Gitea version (or commit ref): 1.13.0
- Git version: git version 2.25.1
- Operating system: Linux nuc-mini-server 5.4.0-58-generic #64-Ubuntu SMP Wed Dec 9 08:16:25 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
  
  
  
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
- Log gist:

After reboot my system, gitea is not starting automaticaly. I didn't chage the configuration. Some days ago I updated to 1.13.0.

```
$ sudo systemctl status gitea
gitea.service - Gitea
     Loaded: loaded (/etc/systemd/system/gitea.service; enabled; vendor preset: enabled)
     Active: inactive (dead)

```

And this my gitea.sercice configuration

```
$ more /etc/systemd/system/gitea.service
[Unit]
Description=Gitea
After=syslog.target
After=network.target
After=docker.service
After=postgresql.service
#After=mariadb.service mysqld.service postgresql.service memcached.service redis.service

[Service]
# Modify these two values and uncomment them if you have
# repos with lots of files and get an HTTP error 500 because
# of that
###
#LimitMEMLOCK=infinity
#LimitNOFILE=65535
RestartSec=2s
Type=simple
User=git
Group=git
WorkingDirectory=/var/lib/gitea
ExecStart=/home/git/bin/gitea web -c /etc/gitea/app.ini
Restart=always
Environment=USER=git HOME=/home/git GITEA_WORK_DIR=/var/lib/gitea
# If you want to bind Gitea to a port below 1024 uncomment
# the two values below
###
#CapabilityBoundingSet=CAP_NET_BIND_SERVICE
#AmbientCapabilities=CAP_NET_BIND_SERVICE

[Install]
WantedBy=multi-user.target
```

I can't see any problems in logs. Looks like the service will be not started. Manual start is working.

Has anyone any idea?

**Comment by TsakiDev** [comment]
Maybe check journalctl for any errors?

**Comment by somera** [comment]
@TsakiDev there was no error.

After I removed

`After=docker.service`

looks like it started. This is strange, cause I didn't change the config for months.
