### ISSUE TITLE
Simpler Custom Logo Workflow

### ISSUE THREAD

**Issue by kdumontnu** [go-gitea/gitea#13969]
- Gitea version (or commit ref): develop, ee7133d135e1bf746ccd558371edd4fcdf185e7f

## Description

`generate-images.js` (which is an incredible piece of code!) creates logo pngs with 'gitea' in the title (ex. `gitea-lg.png`). I propose we use generic naming 'logo' (ex. `logo-lg.png`) to allow users to take advantage of the `generate-images` code and update the logo without having to customize the template file for each logo image reference.

Specifically, users would be able to replace `assets/logo.svg` with a custom logo and run `make generate-images` to have the logo updated across the app. Admittedly, we COULD use the code as is, but the logo name reference `gitea...` would technically not be correct.

I would add that this might be considered a breaking change, as it would result in many existing HTML template references to break. I'm not sure if the gitea community considers this when creating releases. 

I'm happy to implement a change if I can get some initial feedback.

Ex. code from `home.tmpl`
```
{{template "base/head" .}}
<div class="home">
	<div class="ui stackable middle very relaxed page grid">
		<div class="sixteen wide center aligned centered column">
			<div>
				<img class="logo" src="{{StaticUrlPrefix}}/img/gitea-lg.png" />
			</div>
			<div class="hero">
				<h1 class="ui icon header title">
					{{AppName}}
				</h1>
				<h2>{{.i18n.Tr "startpage.app_desc"}}</h2>
			</div>
		</div>
	</div>
```

**Comment by zeripath** [comment]
Unfortunately we break templates all the time as they're still rather tightly integrated with our rendering code. Therefore this proposal is a +1 from me.
