### ISSUE TITLE
Gateway 500 error on git push

### ISSUE THREAD

**Issue by snaildos** [go-gitea/gitea#13964]
Hello everyone, After hours, days, (feels like months,) I have finally managed to pinpoint what is going on here.
Let me just tell me what's going on here.
I have gitea, running on docker-compose, The database is MariaDB and runs perfectly, HOWEVER, When I upload more then ~1.5GB (with git push), I get a 500 error on git, or github assistance. **This is not a reverse proxy issue, I can confirm this. I pushed with localhost, and it is still not working.**

- Gitea version (or commit ref): Latest gitea on docker to this day
- Git version:
- Operating system: Ubuntu 20.04LTS
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
- Log gist:
I do not know how to get to the logs.

## Description

I do not know what's going on here, but I really need some help here.

## Screenshots
![image](https://user-images.githubusercontent.com/46210117/101987704-cae80700-3cd0-11eb-8554-7f3721e7f9ca.png)

As you can see;
https://git.snaildos.tk/snaildos/FatSnail
This commit came through,
however,
the 1.5GB commit, did not. Because of a error 500

**Comment by kolaente** [comment]
If you did not configure `log.ROOT_PATH` the logs should be in `data/gitea/logs` - the logs directory is on the same level as the `conf` directory which is where your `app.ini` lives.

**Comment by techknowlogick** [comment]
>  I do not know how to get to the logs.

In the issue template there is a link to how to get exactly logs that would be helpful. We cannot help you without information. Also we are all volunteers working on this, so your demand of support and flooding of chat, and not listening to us when we do ask you to do something that would fix your issue is more than a bit rude.
