### ISSUE TITLE
DEFAULT_MERGE_MESSAGE_ALL_AUTHORS configuration during squash commit PR

### ISSUE THREAD

**Issue by TicoDePano** [go-gitea/gitea#13976]
- Gitea version (or commit ref):
1.13.0
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
## Description
From version 1.13.0, the configuration _[repository.pull-request] DEFAULT_MERGE_MESSAGE_ALL_AUTHORS_, used as default (false), is not being honoured in a squash commit type of PR.
I just want the commit title in the commit message, as in the earlier versions. Cleaning the message with the Co-Authored-By lines doesn't work, these are appended again to squash commit message.

**Comment by zeripath** [comment]
DEFAULT_MERGE_MESSAGE_ALL_AUTHORS=false means only collect authors for the DEFAULT_MERGE_MESSAGE_COMMITS_LIMIT.

**Comment by TicoDePano** [comment]
Sorry, my bad. Probably the new behaviour has no connection with the configuration.
But from 1.13.0 version the message about Co-Authors is being appended automatically.
![image](https://user-images.githubusercontent.com/22637426/102851128-c4a50980-43f9-11eb-8d77-fc8d383bd762.png)
I am amending my commits to get the title only, as in previous 1.12 versions when no message was inserted.

**Comment by TicoDePano** [comment]
@zeripath 
Reading your post at https://github.com/go-gitea/gitea/issues/15914#issuecomment-885308087 i thought that the body of the squash merge message would be removed with the new setting.
In 1.15, are there any way to achieve a single message in a squash merge?
Is a lot boring do a force push after every PR merge. And branch protection needs to be disabled to do that.

**Comment by TicoDePano** [comment]
Fixed in [v1.16.0](https://github.com/go-gitea/gitea/releases/tag/v1.16.0) by PR #17848.
