### ISSUE TITLE
Add Pull Request Approval to API

### ISSUE THREAD

**Issue by delvh** [go-gitea/gitea#13972]
- Gitea version (or commit ref): 1.13.0
- Operating system: all

## Description

Currently, one of the major downsides of Gitea is that Pull Requests cannot be approved using the API. 
As far as I have seen, this is because there is no pull request approval hook in the API.
This limits the usability of Gitea from outside, for example from within an app, by a lot because that is in my opinion the main point of using the API at all.

### Changes to be implemented
* Add Approve Pull Request hook in the API
* Add Request Changes hook in the API

**Comment by a1012112796** [comment]
Hmm, If I understood, They are exist now
- https://gitea.com/api/swagger#/repository/repoCreatePullReview
- https://gitea.com/api/swagger#/repository/repoCreatePullReviewRequests

see https://github.com/go-gitea/gitea/blob/master/integrations/api_pull_review_test.go for how to use them. Thanks :)

**Comment by zeripath** [comment]
as @a1012112796 says these exist already. They may be in an unreleased version. Please re-open if these APIs do not do what you want.

**Comment by delvh** [comment]
Well, while they do exist, they are poorly documented. 
The question is: Should this issue be reopened by stating to add documentation for it?

**Comment by zeripath** [comment]
As far as I can see they are as documented as the rest of the API. If you would like to improve API documentation I would suggest either adding a page to docs/content/doc/advanced and/or improving the documentation in that is in code. Feel free to open another PR or issue with suggested documentation though.
