### ISSUE TITLE
Cannot delete branch with slash in name after PR

### ISSUE THREAD

**Issue by Aarup** [go-gitea/gitea#1397]
- Gitea version (or commit ref):1.1.0
- Git version:
- Operating system: Ubuntu
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL) https://try.gitea.io/username/branch-slash/pulls/1
  - [ ] No
  - [ ] Not relevant
- Log gist:
https://gist.github.com/Aarup/75908798b147e91ffb1133357acb44a1

## Description
If a branch has has a slash in the name like
  - bug/bugsId
  - feature/featureName
It is impossible to delete this branch using the web UI after a PR has been merged into the repository.
When clicking the "Delete branch" button a generic popup comes, but after entering username and password nothing happens - a 404 is received from the post

## Screenshots
![image](https://cloud.githubusercontent.com/assets/1222464/24392994/a1fea220-1396-11e7-882a-0f52f6a642fe.png)
![image](https://cloud.githubusercontent.com/assets/1222464/24393236/981af38e-1397-11e7-96f4-ea15d09755d6.png)

**Comment by lunny** [comment]
https://github.com/go-gitea/gitea/pull/1689/cleanup, it seems Gitea has a different URL with github's URL on this feature.
