### ISSUE TITLE
404 error when opening a branch on the dashboard

### ISSUE THREAD

**Issue by atomlong** [go-gitea/gitea#13979]
- Gitea version (or commit ref): 1.14.0+dev-381-g633dc80077
- Git version:  2.29.2
- Operating system: ArchLinuxARM (aarch64)
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x ] Yes (provide example URL) https://try.gitea.io/atomlong/WiFiManager/src/branch/refs/heads/master
  - [ ] No
- Log gist:

## Description

1) Push master branch to https://try.gitea.io/atomlong/WiFiManager
2) open the dashboard on page https://try.gitea.io
3) click "refs/heads/master" link
![image](https://user-images.githubusercontent.com/3690342/102063238-ba4ea280-3e30-11eb-9e7a-b2a2d9105319.png)
4) "Page Not Found" will come
![image](https://user-images.githubusercontent.com/3690342/102063451-04d01f00-3e31-11eb-86b0-6a4b6522cb6a.png)

My guess is that the branch name on the Dashboard panel is wrong, it should be 'master', not 'refs/heads/master'.

**Comment by zeripath** [comment]
the `refs/heads/` should be being Trimmed

**Comment by zeripath** [comment]
This is happening because of #13882

**Comment by zeripath** [comment]
I think the best solution is actually to simply TrimPrefix the `refs/heads/` in action.GetBranch(). The argument being that we can do this safely as this will always have been correct and will be correct in future too.

**Comment by atomlong** [comment]
Your PR doesn't solve the issue. Now the branch name becomes 'refs/heads/'.
![image](https://user-images.githubusercontent.com/3690342/102081045-841e1c80-3e4a-11eb-9b78-491fb773e759.png)

This gitea version comes from your branch：https://github.com/zeripath/gitea/tree/fix-13979-action-branch-trim-BranchPrefix
![image](https://user-images.githubusercontent.com/3690342/102081339-09a1cc80-3e4b-11eb-99b2-50d7830a175c.png)

**Comment by zeripath** [comment]
> @zeripath Your PR doesn't solve the issue. Now the branch name becomes 'refs/heads/'.


that's because I'm an idiot who got the arguments to TrimPrefix the wrong way round.

Try again

**Comment by atomlong** [comment]
@lafriks  The issue has not been completely solved.  If I push a label to the repository, there will be redundant 'ref/tags'. 
In addition, why there are two items on the Dashboard?
![image](https://user-images.githubusercontent.com/3690342/102679161-97cdd800-41e8-11eb-8e8a-e4f60bf1e69d.png)

Please reopen this issue, or I will create another issue?

**Comment by zeripath** [comment]
So that's a different problem. Similar but different and it would have been better to open another issue.

**Comment by lunny** [comment]
Cannot reproduce this on 4aabbacdf

**Comment by atomlong** [comment]
@lunny I confirm that even the latest commit has not completely solved the issue.
![image](https://user-images.githubusercontent.com/3690342/102691575-77ce0100-4248-11eb-8c27-f19a685881da.png)
