### ISSUE TITLE
Team dashboards

### ISSUE THREAD

**Issue by jpraet** [go-gitea/gitea#13980]
The "Switch Dashboard Context" dropdown lists your user and your organisations.

As far as I can tell we currently cannot view the Activities, Issues, Pull Requests, and Milestones per team. Only per user / organisation.

![image](https://user-images.githubusercontent.com/2212615/102064638-d8e47780-3df7-11eb-99c8-0228012c7483.png)

**Comment by noerw** [comment]
see also #5440
