### ISSUE TITLE
Lots of zombie Git processes

### ISSUE THREAD

**Issue by Trumeet** [go-gitea/gitea#13987]
- Gitea version (or commit ref): 1.13.0
- Git version: 2.29.2
- Operating system: Arch Linux (Running inside a Podman container), but I run gitea directly without using systemd.
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
- Log gist: https://gist.github.com/Trumeet/ca129caa2a5f15822aa4bc5ae7391548

## Description

It's still not clear what is happening, but after I started the website days ago, I found there's a bunch of (currently 263) zombie git processes under gitea (Look at the htop result), and the memory usage is high (not sure if this is intended).

I have some repos in this install, and one of them is a mirror of [youtube-dl](https://github.com/youtube-dl2/youtube-dl). I spotted some errors pulling this repo (just found this repo is disabled). I have another install but has lesser visits and does not have mirrors, and there's no such problem.

## Screenshots

![image](https://user-images.githubusercontent.com/17158086/102134231-1c94ac80-3e0b-11eb-827c-f0c093731e96.png)

**Comment by zeripath** [comment]
Unfortunately I can't look at your log gist on my phone as it is too large however, I will try to look at it tomorrow to attempt to discover if there is a reason for these dangling processes.

On the admin pages there is process subpage that will be able to tell you what those git tasks are supposed to be doing and give you the a button to cancel them (or at least attempt to)

That would be the quickest way to report what was causing these processes.

**Comment by zeripath** [comment]
Ah so it looks like it's related to your broken mirrors.

**Comment by zeripath** [comment]
And I think I've worked it out.

**Comment by Trumeet** [comment]
> Ah so it looks like it's related to your broken mirrors.

Thanks. Unfortunately I just rebooted the system so I cannot confirm that, but since I had already updated the link to the mirror, I checked and confirmed that there's no zombie git processes since the last boot.
