### ISSUE TITLE
Sanitize SSH pubkeys (and Support multiple) when sync from LDAP

### ISSUE THREAD

**Issue by strk** [go-gitea/gitea#13984]
In our setup we allow multiple SSH keys to be entered in the LDAP database, for each user.
When Gitea synchonizes those keys it does so by creating a wrong configuration, including newlines (which separate the SSH keys) in the authorized_key, basically allowing direct ssh access.

**Comment by strk** [comment]
The above behaviour was tested with version 1.12.3

**Comment by zeripath** [comment]
Gitea asks LDAP to provide it with the SSHPublicKey attributes and collects them as a []string

https://github.com/go-gitea/gitea/blob/729f0f5f7ba98e9472d69f30a6c9433039f5e0a0/modules/auth/ldap/ldap.go#L336

https://github.com/go-gitea/gitea/blob/729f0f5f7ba98e9472d69f30a6c9433039f5e0a0/modules/auth/ldap/ldap.go#L387-L389

It then passes that array to and individually adds them as separate  public keys:

https://github.com/go-gitea/gitea/blob/729f0f5f7ba98e9472d69f30a6c9433039f5e0a0/models/user.go#L1588-L1609

The issue here must be that instead of having separate attributes for each public key you must just have a single attribute containing all of the public keys. Is that really the correct way to store these?

**Comment by strk** [comment]
On Mon, Dec 14, 2020 at 06:55:29AM -0800, zeripath wrote:
> The issue here must be that instead of having separate attributes for each public key you must just have a single attribute containing all of the public keys. Is that really the correct way to store these?

I don't know if it's correct or not, possibly not, but still I think
Gitea should be made more tolerant to these kind of errors, checking
that the each element of the retrived array is a valid single-line ssh
key, to avoid assumptions which may open security holes.

**Comment by zeripath** [comment]
so it's strange because at first glance Gitea is attempting to assert that thing is a valid public key

https://github.com/go-gitea/gitea/blob/729f0f5f7ba98e9472d69f30a6c9433039f5e0a0/models/user.go#L1591

but the problem is that line is an abuse of that function. That function is there parse out the valid ssh-key lines one by one.

I think this should just be fixed to just parse the string reading in all of the keys one by one

**Comment by zeripath** [comment]
We could go further than the attached PR - we use this function in one other place

https://github.com/go-gitea/gitea/blob/c3fc190372cb525fdacf60606bf8aaf1c33e7da7/models/ssh_key.go#L110-207

This has a different set of acceptable SSH keys. 

Likely these two functions should be made more similar.

**Comment by strk** [comment]
I'm reopening this as I just had a chance to test 1.14.0+dev-423-gb4f8da533e and it still doesn't seem to support multiple keys in a single attribute. Nothing is printed in logs about the reason why a single key is extracted when there are two in the ldap database. Both keys are in the same element of the attribute array (array of a single attribute)

**Comment by zeripath** [comment]
@strk you're gonna have to give us an example of a value that doesn't work.

**Comment by strk** [comment]
This is what I'm getting out of LDAP:
```
ssh-rsa FIRSTKEY strk@cin\01503d
        ssh-rsa SECONDKEY strk@cdb
```

**Comment by strk** [comment]
The above string is what is printed upon login with this patch:
```
diff --git a/models/login_source.go b/models/login_source.go
index 1de24a9cf7..687eb8597b 100644
--- a/models/login_source.go
+++ b/models/login_source.go
@@ -458,11 +458,14 @@ func composeFullName(firstname, surname, username string) string {
 // and create a local user if success when enabled.
 func LoginViaLDAP(user *User, login, password string, source *LoginSource) (*User, error) {
        sr := source.Cfg.(*LDAPConfig).SearchEntry(login, password, source.Type == LoginDLDAP)
+
        if sr == nil {
                // User not in LDAP, do nothing
                return nil, ErrUserNotExist{0, login, 0}
        }
 
+       log.Warn("User: %s publicKey: %s", sr.Username, sr.SSHPublicKey)
+
        var isAttributeSSHPublicKeySet = len(strings.TrimSpace(source.LDAP().AttributeSSHPublicKey)) > 0
 
        // Update User admin flag if exist
```

I don't know what the `\01503d` string is about

**Comment by strk** [comment]
Interesting enough, google finds the `\01503d` string only in relation to Gitea: https://www.google.com/search?q=+%22\01503d%22

**Comment by strk** [comment]
Basically: GetAttributes returns a single attribute being a concatenation of 2 public keys. I guess Gitea is discarding anything after the first space (before the comment). I agree this is most probably a WRONG way to store public ssh keys in LDAP but would be nice if Gitea could report a problem of some kind (spurious comment? Unexpected newline ?)

**Comment by strk** [comment]
For the record: the probably WRONG format for ssh keys in our LDAP is discussed in https://trac.osgeo.org/osgeo/ticket/2542

**Comment by strk** [comment]
I finally fixed the way we store SSH keys in LDAP, and I confirm the support for multiple keys is working in master branch. And I confirm multiple keys support did NOT work in version 1.12.3 - Great work !

**Comment by strk** [comment]
For the record: I was wrong, 1.12.3 supports multiple keys just fine too, once they are correctly stored in LDAP

**Comment by zeripath** [comment]
I guess I just have no idea where that `\01503d` is coming from or what it should be interpreted as. May be it's some sort of escaped `\r`?

**Comment by strk** [comment]
For the record, I re-checked and once SSH keys are correctly stored in LDAP even the 1.12.3 version works fine

**Comment by strk** [comment]
> I guess I just have no idea where that `\01503d` is coming from or what it should be interpreted as. Maybe it's some sort of escaped `\r`?

Probably, yes. or escaped `\r\n`. But the fact that Google only returns pages about `Gitea` makes me suspect escaping/decoding is somehow done in a wrong way ? I think LDAP used to return the field in base64 encoding, due to the presence of newlines. The decoding of base64 might have lost a carriage-return (the newline seemed to be there though)

**Comment by zeripath** [comment]
Hmm... now you say base64 - well that would explain the 03d which would probably represent an `=` and 015 represent a `\r`.

That would imply that the items are being split by `\n` (not `\r\n`) and then individually base64 encoded with the trailing `\r` forming part of the preceding block but it being an incomplete base64 triplet requiring a `=` for padding?

**Comment by strk** [comment]
Sounds very likely, yes. Now that I fixed the LDAP storage I indeed had to split by `\r\n` for it to work correctly and avoid the base64 encoding (not sure I understood the `=` part of this). In case this is helpful for handling such cases in LDAP this is all good info
