### ISSUE TITLE
SSH keys should not be allowed to be deleted when coming from LDAP

### ISSUE THREAD

**Issue by strk** [go-gitea/gitea#13983]
When SSH keys are retrived from LDAP it makes no sense to allow removing them in Gitea (as they would be re-added anyway on next login). I would also go a step further and disallow also _adding_ them, as LDAP would then be the only point-of-truth.

**Comment by zeripath** [comment]
the simplest (albeit temporary) solution is to change the templates to remove the option of deleting and adding ssh_keys.

**Comment by strk** [comment]
@zeripath in our case we'll want to keep the "Add" button, just having it take the user to our LDAP editing screen. This is possibly too custom to support, unless we want to add a configuration item for that (ssh key add link...)

**Comment by zeripath** [comment]
Yup you should do that with a custom template
