### ISSUE TITLE
Status of SimpleMDE->EasyMDE replacement

### ISSUE THREAD

**Issue by corneliusroemer** [go-gitea/gitea#13998]
There once was a PR "WIP: EasyMDE" back in January, but it got closed with a comment:
>SimpleMDE will be ripped out eventually, so I guess we can close this.
_Originally posted by @silverwind in https://github.com/go-gitea/gitea/issues/9973#issuecomment-628643819_

What's the status of this replacement program? Maybe EasyMDE should be reconsidered if the rip-out isn't taking place very soon.

Was it so difficult to move to EasyMDE?

**Comment by jolheiser** [comment]
We have already moved to EasyMDE per #13333

**Comment by corneliusroemer** [comment]
Great! Couldn't find that info until now. Hope that fixes most mobile editor issues.
