### ISSUE TITLE
Enhace PR automerging

### ISSUE THREAD

**Issue by hhenkel** [go-gitea/gitea#1399]
- Gitea version (or commit ref): 1.1.0+75-g6a451a2b
- Git version:  2.8.3
- Operating system: Upstream docker container
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant

## Description

A colleague of mine produced a problem in a file (the content is one line off the master). He then opened up a PR which got the state "This pull request cannot be merged automatically because there are conflicts."

Looking at the log I see the following error:
```
Mar 28 09:28:37 dockert docker-compose: gitea_1   error: patch failed: 90_common/role.yaml:550
Mar 28 09:28:37 dockert docker-compose: gitea_1   error: 90_common/role.yaml: patch does not apply
```

I'm able to reproduce this error on the CLI when I create a patch and try to apply it manually:
```
$ git apply --check ../changes.diff
error: patch failed: 90_common/role.yaml:550
error: 90_common/role.yaml: patch does not apply
```

However when I do a direct merge of the branch git is able to resolve the issue:
```
$ git merge pr/590
Auto-merging 90_common/role.yaml
Merge made by the 'recursive' strategy.
```

I guess it would be good to make use of this from gitea.

**Comment by hhenkel** [comment]
@lunny I'm currently no longer work with gitea as I changed jobs, not sure if this is already fixed or not.

**Comment by lunny** [comment]
Cannot reproduce that. Let's close now and please feel free to reopen it.
