### ISSUE TITLE
Loading progressbar on Gitea

### ISSUE THREAD

**Issue by joubertredrat** [go-gitea/gitea#14]
Hi guys,

This is a small Feature suggestion for Gogs UX. On my projects, I use page loading progress bar and is simple to use, similar from Youtube, when page is loading, is possible to see loading progressbar on top page.

I use [this plugin ](https://github.com/HubSpot/PACE) with theme `Flash` and worked very fine here. 

What you think?

Reference: https://github.com/gogits/gogs/issues/3693

**Comment by metalmatze** [comment]
Something like that would be really nice, but not a must have.
I'd say go for it! :blush:

**Comment by jhasse** [comment]
I think such a thing should be inplemented by the browser, not by every website for itstelf.

**Comment by metalmatze** [comment]
But currently it isn't implemented by every browser. I don't see anything against this.

**Comment by jhasse** [comment]
- Code complexity
- Some browsers (e. g. Epiphany) already have a progress bar where this will look ugly
- Increased load time
- Some people might not visually like it (like myself)

**Comment by joubertredrat** [comment]
- Is easy, you add only 2 files and nothing else

```
<script src="/pace/pace.js"></script>
<link href="/pace/themes/pace-theme-barber-shop.css" rel="stylesheet" />
```
- I didn't know that have browsers with progress bar
- On my projects, don't have relevant increase load time
- We can put this on vote, the biggest wins.

**Comment by tboerger** [comment]
I don't have a strong opinion on that but generally I don;t think that this is a bad idea. For the people that don't like it it should also be an option to provide a flag to enable/disable it.

**Comment by xinity** [comment]
what would this progress bar helps with ? 
don't get me wrong, it a good idea, i'm just wondering what i would help with in using gitea on a daily driver

**Comment by jhasse** [comment]
> Is easy, you add only 2 files and nothing else

Of course you need to take the code inside pace.js and the css file into account. What if there's a security risk inside pace.js?

Btw: You forgot that Gogs can run on a subfolder of a domain, so these two lines already introduce a bug.

> On my projects, don't have relevant increase load time

People on mobile connections? Also people with slower PCs? The js file needs to be parced. The progress bar needs to be drawn. It has a glow effect which uses alpha values if I'm not mistaken. This will cause more CPU / GPU load.

You might also try https://addons.mozilla.org/en-US/firefox/addon/progre. Works with Gogs/Gitea. And you can theme it.

**Comment by joubertredrat** [comment]
>  Of course you need to take the code inside pace.js and the css file into account. What if there's a security risk inside pace.js?

Any library component for any language can have this risk

> People on mobile connections? Also people with slower PCs? The js file needs to be parced. The progress bar needs to be drawn. It has a glow effect which uses alpha values if I'm not mistaken. This will cause more CPU / GPU load.

Yes, both on mobile using 3g and PC's with 1Gb RAM only, work normally.

How do we need the new relase of Gitea, we see other more important things, in future if is necessary, we reopen this.

**Comment by tboerger** [comment]
Please keep enhancements open for not, it's tagged with a future milestone on purpose. If it's closed nobody will ever discuss about it or implement it.

**Comment by bkcsoft** [comment]
@jhasse 

>  You forgot that Gogs can run on a subfolder of a domain, so these two lines already introduce a bug.

That would've been caught in code-review, no need for nit-picking on pseudo-code in issues :wink: 

> People on mobile connections? Also people with slower PCs? The js file needs to be parced. The progress bar needs to be drawn. It has a glow effect which uses alpha values if I'm not mistaken. This will cause more CPU / GPU load.

Could be disabled in user-settings. Also it works on **Edge** (GPRS++) without noticeably slowing it down :slightly_smiling_face:

**Comment by jhasse** [comment]
> That would've been caught in code-review, no need for nit-picking on pseudo-code in issues 😉 

Just wanted to point out that there's more to it then initially thought.

Firefox for Android also has a progress bar btw.

**Comment by bkcsoft** [comment]
> Firefox for Android also has a progress bar btw.

Yes I know, this one hi-jacks it :wink:

**Comment by jhasse** [comment]
Another browser with a built-in progress-bar: Vivaldi

**Comment by joubertredrat** [comment]
I will provide this as optional defined on configuration with default disabled, if you want to enable, set this on config
