### ISSUE TITLE
Cannot add GPG signing sub-key

### ISSUE THREAD

**Issue by etanot** [go-gitea/gitea#14009]
- Gitea version (or commit ref): 1.14.0+dev-389-g88b585c2e (https://try.gitea.io)
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (https://try.gitea.io/user/settings/keys)
  - [ ] No

##### Type:
Bug report

## Description
When I'm trying to add my GPG signing sub-key, Gitea shows me this error message:

`This GPG key is not usable with any email address associated with your account.`

Basically, I run `gpg --armor --export <signing-sub-key-id>!` (notice, I've added a `!` at end of ID, to tell GPG to only export my master key and specific sub-key information, see [this gnupg-users](https://lists.gnupg.org/pipermail/gnupg-users/2017-January/057400.html) mailing list thread). I've no issue with adding my sub-key this way to Github and Gitlab.

### Steps to Reproduce
- Run `gpg --armor --export <signing-sub-key-id>!` command.
- Copy the output of the command (public key).
- Go `Settings -> SSH/GPG keys -> Manage GPG keys`.
- Click on `Add key` button in `Manage GPG keys` section.
- Paste the copied public key.
- Now, click on green `Add key` button.

### Expected Output
Key should be added successfully.

### Actual Output
Getting this error message, `This GPG key is not usable with any email address associated with your account.`

**Comment by a1012112796** [comment]
hello, Now gitea only allow add public gpg keys bounded with the user's email.

**Comment by finn0** [comment]
Thanks @a1012112796, then closing this bug report and opening another issue for the feature request.
