### ISSUE TITLE
Database error after upgrade

### ISSUE THREAD

**Issue by wireva** [go-gitea/gitea#14007]
- Gitea version (or commit ref):
- Git version:
- Operating system: Ubuntu 20.04, Docker
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not possible
- Log gist:
https://paste.cloudserver.click/eyarubakoq.sql

## Description
I just updated the instance by pulling the new image from Docker HUB and I get the issues you can see in the logs.

**Comment by techknowlogick** [comment]
Please fill in the whole issue template, you can get the remaining information from https://gitea.example.com/admin/config

As for the error you are receiving you can review https://mariadb.com/kb/en/troubleshooting-row-size-too-large-errors-with-innodb/ for more information.

**Comment by zeripath** [comment]
Run `gitea convert`

See: https://docs.gitea.io/en-us/faq/#upgrade-errors-with-mysql

**Comment by 6543** [comment]
If you had a look at giteas docs, can you give us a hint what pages you have looked so we can add this hint to it

**Comment by Niwla23** [comment]
> Run `gitea convert`
> 
> See: https://docs.gitea.io/en-us/faq/#upgrade-errors-with-mysql


Thanks, that one fixed it.
For docker-compose it is `sudo docker-compose exec --user git app gitea convert`
