### ISSUE TITLE
Different size on pull request review UI

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#14014]
![image](https://user-images.githubusercontent.com/81045/102346027-38e64400-3fd9-11eb-99c8-a693cb2e215b.png)

**Comment by a1012112796** [comment]
@lunny Suggest add more details description, Thanks.

**Comment by silverwind** [comment]
I know this one. Essentially the dropdown icon is causing the button to enlarge vertically. Not sure what a clean solution would be.
