### ISSUE TITLE
No notifications are sent for mentions in review comments

### ISSUE THREAD

**Issue by jpraet** [go-gitea/gitea#14013]
- Gitea version (or commit ref): 1.13.0
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No

## Description

When `@mentioning` someone in a code review comment, no notification is sent.

**Comment by a1012112796** [comment]
Not support it now.

**Comment by a1012112796** [comment]
suggest label this issue as ``good first issue``.
