### ISSUE TITLE
Convert existing database to mb4

### ISSUE THREAD

**Issue by iamdoubz** [go-gitea/gitea#14030]
I use in my `app.ini` right now `utf8`. What command do I need to run on my **mysql** database to convert the tables to utf8mb4?

Thank you in advance.

**Comment by jolheiser** [comment]
The second half of https://docs.gitea.io/en-us/faq/#why-are-emoji-broken-on-mysql should resolve this for you. 🙂 

Essentially `gitea convert` (with the config flag) and changing `CHARSET` in the `app.ini`

**Comment by zeripath** [comment]
Please see https://docs.gitea.io/en-us/faq/#why-are-emoji-broken-on-mysql
