### ISSUE TITLE
can I add a binary package file of mipsel architecture?

### ISSUE THREAD

**Issue by mirroro** [go-gitea/gitea#14034]
Hello, can I add a binary package file of mipsel architecture? I'd like to use gitea very much, but I don't know how to compile it. It runs on my device, but I checked the information and found that my device belongs to the mipsel architecture, and I don't have a lot of information to try cross compiling. I really hope that we can have more of this architecture, so that our small number of devices can also use gitea

**Comment by 6543** [comment]
as far as i know there was a mipsel package on alpine but it was droped for some reason ...

**Comment by 6543** [comment]
@caifenglin witch distribution do you use?

**Comment by techknowlogick** [comment]
We've discontinued our builds on mips devices as we lack devices to test the builds on them, and also the single digit downloads on those platforms. AFAIK alpine dropped mips & go programs due to some incompatibility issues.

**Comment by techknowlogick** [comment]
For attempting to compile this on your platform you can follow these instructions: https://docs.gitea.io/en-us/install-from-source/
