### ISSUE TITLE
gitea gogs merge?

### ISSUE THREAD

**Issue by nictaylr** [go-gitea/gitea#1403]
is gitea same up to date with gogs project ?
gitea has feature that i want that gogs missing, but i already have gogs
if i switch to gitea will i still have new features added to gogs ?
is gogs updates be merged into gitea project ?

sorry ,about english

**Comment by pgaskin** [comment]
Gitea is now mostly separate from Gogs (except for small bugfixes and small features). Most of the features added here will not be merged with Gogs, and the same way the other way around. Gitea has many features which Gogs does not, and Gogs has a few features Gitea does not.

**Comment by nictaylr** [comment]
`Gogs has a few features Gitea does not`

- Can you give please example ?

**Comment by ulm0** [comment]
@nictaylr just name a few: notificactions, TOTP, OpenID, external accounts linked. I'm literally comparing them side by side in my pc screen right now, so i'm sorry if i miss anything. Although you can try them by yourself in each project site.

**Comment by strk** [comment]
@nictaylr you're very welcome to port Gogs features to Gitea, when missing

**Comment by nictaylr** [comment]
thank you both !
i just thining gitea logo looks "dated", maybe consider design new ? gogs new logo look very nice.
gitea has two factor aut, i use for security, gogs missing feature

**Comment by appleboy** [comment]
@nictaylr See the new logo threads

https://github.com/go-gitea/gitea/issues/1312
https://github.com/go-gitea/gitea/issues/1260
