### ISSUE TITLE
Heatmap not reflecting past days commits

### ISSUE THREAD

**Issue by omgitsalexl** [go-gitea/gitea#14051]
- Gitea version (or commit ref): 1.13.0
- Git version: 2.24.3
- Operating system: Ubuntu 20.04 as Hyper-V guest
  
  
  
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
- Log gist:

## Description
The contribution heatmap does not reflect previous days commits, only adds a mark for the day the commit was pushed. 

Example: I make various commits to my local repository over four days and on the fifth day I push to my Gitea instance. The contribution heatmap only adds a single tick for the day that I pushed the local commits to the remote, but does not show any ticks for the four previous days of local work despite commits being made on the local machine.

I would expect that Gitea would create a tick for every contribution made to a repository, regardless of when these changes are pushed. This issue really shows when pushing a repository that is new to a Gitea instance, but has been worked on (or cloned from another repository) for any length of time prior to pushing.

I apologize if this issue has been brought up before, I did a quick search and was unable to find anything.

## Screenshots
![Screen Shot 2020-12-18 at 8 38 29 AM](https://user-images.githubusercontent.com/6470175/102638518-75668c80-410c-11eb-8cbc-af9d26302ac5.png)

**Comment by lafriks** [comment]
See my comment on duplicate #11861 issue https://github.com/go-gitea/gitea/issues/11861#issuecomment-643162143
