### ISSUE TITLE
Administrative task for recalculating cached database counters

### ISSUE THREAD

**Issue by gerricom** [go-gitea/gitea#1406]
- Gitea version (or commit ref): 1.1
- Git version: 2.7.4
- Operating system: CentOS 6
- Database (use `[x]`):
  - [x] PostgreSQL
  - [x] MySQL
  - [x] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

The database holds a number of different cached counters e.g. `num_comments` in the issue table, or `num_issues`, `num_closed_issues`, ... in die repo table. If for any reason (migration failed, backup failed, ...) the original values are changed those num_-values won't change with them.

There should be an administrative task that recalculate all those values.

**Comment by strk** [comment]
Would you be up to give this a try ?

**Comment by gerricom** [comment]
Unfortunately I'm not into go (this is my very first contact). I could provide raw (My)SQL-Queries to recalculate those values if this helps?
