### ISSUE TITLE
:TOC: label in "org mode" readme files should be hidden

### ISSUE THREAD

**Issue by finex** [go-gitea/gitea#14074]
- Gitea version (or commit ref): 1.13.0
- Git version: 2.11.0
- Operating system: Debian (official gitea **docker** image)

- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [X] SQLite

## Description

I've created a `README.org` file using Emacs org mode. The file is something like:

```
#TITLE: file title

* Table of contents :TOC:
- [[#title][Title]]

* Title
Lorem ipsum...
```

Usually github/gitlab doesn't show the `:TOC:` attribute, which is used by Emacs to regenerate the table of contents on save.

### Actual result:

![image](https://user-images.githubusercontent.com/287009/102715090-cfad4c00-42ca-11eb-9bee-ede45ef7aede.png)

### Desidered behaviour:
![image](https://user-images.githubusercontent.com/287009/102715100-e489df80-42ca-11eb-8677-3055d01b6f7c.png)

# Extra issues
I've found other two "bugs", the first is that if the README already has a TOC, gitea shouldn't render his own index. The second is that the anchors generated using org mode doesn't works. Should I open two separate issues for this two bug? 

Thank you.

**Comment by a1012112796** [comment]
@finex  because gitea not support this format now, it consider this file as an simple markdown file.
 related issue :#12832. Thanks.

**Comment by lunny** [comment]
@a1012112796 In fact, we support org-mod on git files but not wikis. This should be a problem of upstream library which Gitea depends on.

**Comment by a1012112796** [comment]
ok, I see, I will check it and send issue to upstream repo.

**Comment by finex** [comment]
Thanks!

**Comment by niklasfasching** [comment]
> Usually github/gitlab doesn't show the :TOC: attribute, which is used by Emacs to regenerate the table of contents on save.

I couldn't find anything on the `:TOC:` label in the [org mode docs](https://orgmode.org/manual/Table-of-Contents.html) and haven't seen it before. Could you link me to documentation / example markup that modifies the TOC html in emacs org export?

**Comment by finex** [comment]
Hi, you're right, I was using Doom Emacs and I didn't know (until now) that this feature is not default but it's from the following package installed by Doom: https://github.com/snosov1/toc-org

**Comment by niklasfasching** [comment]
thx. 
as org mode supports positioning the toc using `#+TOC` I'd opt for implementing that - that would also get rid of the default toc. Fixing the links is up to gitea - they work in raw go-org output. 

Would that solve your problem? No promises, would have to check if this is as low hanging fruit as I'm expecting.

**Comment by finex** [comment]
Hi, yes, it should be good :-)

**Comment by niklasfasching** [comment]
https://github.com/niklasfasching/go-org/commit/7c239a7aeb26a3de2027838d31d22d60828ce17e
go-org now supports `#+TOC: headlines $n` - `$n` being the max headline lvl to include (0 being all). 
The default toc has to be disabled manually (`#+OPTIONS: toc:nil`) as that's the way org mode [does it](https://orgmode.org/manual/Table-of-Contents.html)
https://github.com/niklasfasching/go-org/commit/7c239a7aeb26a3de2027838d31d22d60828ce17e

**Comment by finex** [comment]
Thank you :smile:

**Comment by lunny** [comment]
Once go-org released, we can upgrade the vendor.

**Comment by braoult** [comment]
There are many reasons to upgrade go-org, many features supported [here](https://niklasfasching.github.io/go-org/) are not in gitea (VERSE and EXPORT blocks, TODO separate class, ATTR_HTML, etc...).

**Comment by zeripath** [comment]
#18824 could be backported to 1.16 - but users of org should confirm that it doesn't cause regressions.

**Comment by braoult** [comment]
> #18824 could be backported to 1.16 - but users of org should confirm that it doesn't cause regressions.

I can confirm that on go-org test page (https://niklasfasching.github.io/go-org/)
```
#+TITLE: file title

* Table of contents :TOC:
- [[#title][Title]]

* Title
Lorem ipsum...
```
Gives the expected result:
![Screenshot_2022-02-19_16-43-15](https://user-images.githubusercontent.com/8958429/154807989-bfe58690-824d-4021-a603-6bb3e422776f.png)

**Comment by zeripath** [comment]
This was not what I meant. I meant testing #18824, either once it is in or by downloading 18824 and building and/or download the gitea 1.16 source code, and run:

```
go get -d github.com/niklasfasching/go-org
make vendor
make
```

to then test gitea to see if there were significant downgrade

**Comment by braoult** [comment]
> This was not what I meant. I meant testing #18824, either once it is in or by downloading 18824 and building and/or download the gitea 1.16 source code, and run:

I tried to compile, but there too many dependencies, I am afraid to break something here if I upgrade stuff like npm. What do you mean by `once it is in` ? Is there a place where I could download a gitea binary version (linux x86_64) with #18824 patch ?
