### ISSUE TITLE
Does not support viewing the content of force push

### ISSUE THREAD

**Issue by ffbh123456** [go-gitea/gitea#14070]
Please see the picture below, github can view the updated content by clicking force-push, but gitea does not support
![image](https://user-images.githubusercontent.com/20750357/102708695-553af700-42df-11eb-92af-9ea612b63bb3.png)

**Comment by s-weigand** [comment]
Just had the same issue, I added a commit to my feature branch with an already opened PR and since it got out of sync I rebased it and force pushed. When I wanted to tell the reviewer which commit addressed the requested changes I couldn't find it in the list of commits shown on the PR page.

**Comment by M1CK431** [comment]
Same here and this is excessively annoying because rewrite history / force push is a very common practice on feature branch when some want to have a clear commit history (very useful in case of revert for example).

**Comment by smartEBL** [comment]
I think this one was implemented in https://github.com/go-gitea/gitea/pull/22857
Now (starting with 1.20.0) you can view the diff of a force push like so:
![image](https://github.com/go-gitea/gitea/assets/79155718/8ca64125-45f2-40f7-89c7-d3b2c0a42589)

I guess this ticket can be closed then.
