### ISSUE TITLE
urls in markdown are broken - arguments are sorted

### ISSUE THREAD

**Issue by hrvoj3e** [go-gitea/gitea#14090]
## Problem
When I use this markdown 

```md
Bug markdown links
 - https://example.com/?route=action&id=999
 - <https://example.com/?route=action&id=999>
 - [https://example.com/?route=action&id=999](https://example.com/?route=action&id=999)
```

I get in html

```
<p>Bug markdown links</p>
<ul>
<li><a href="https://example.com/?id=999&amp;route=action" rel="nofollow">https://example.com/?route=action&amp;id=999</a></li>
<li><a href="https://example.com/?id=999&amp;route=action" rel="nofollow">https://example.com/?route=action&amp;id=999</a></li>
<li><a href="https://example.com/?id=999&amp;route=action" rel="nofollow">https://example.com/?route=action&amp;id=999</a></li>
</ul>
```

As you can see `href` is malformed (order of arguments is wrong).

## try.gitea.io

https://try.gitea.io/hrv3/issue-14090/src/branch/master/bug.md

## Versions
Gitea: 1.13.0

**Comment by a1012112796** [comment]
Hello, Why you think it's a bug? in my opinion, ``A&B`` is same with ``B&A``, aren't it? :)

**Comment by hrvoj3e** [comment]
Well - it is not the same.
In our case we have an older app with routing which requires that the first argument does the routing.
We have docs in markdown and hosted in local Gitea. All our links in docs stopped working because of this (at least in Gite UI when viewing markdown files).

Think like this
```shell
## modern app
/user/edit/999

## our older app
/?user=edit&id=999

## if the url changes then the app will not route the request to "user" controller
/?id=999&user=edit
```

In any case - what is the reason to change user data when rendering URLs?
My data should stay the same. I think it sets a dangerous precedent.

Btw. this worked OK a few versions back. I don't know the exact version but I think 1.12.11 worked OK (not sure which).

**Comment by silverwind** [comment]
Agree, URLs should not be altered like this.

**Comment by zeripath** [comment]
OK it looks like that they're being added to the html.Nodes correctly, for example here:

https://github.com/go-gitea/gitea/blob/cd607b5f98ccf66acd99a47309a3411a8e5c8993/modules/markup/html.go#L511

the href argument has the correct ordering.

At some point they're then being munged to emit the attributes in alphabetical order. 

Not certain where at present.

**Comment by zeripath** [comment]
OK, so not all Links are created with the unchanged order - I think part of the issue is going to be the use of url.Values at some point in the chain.

url.Values has no concept of ordering of query parameters and just emits in alphabetical order.

**Comment by silverwind** [comment]
> url.Values has no concept of ordering

Sounds like we need a variant that preserves insertion order.

**Comment by lunny** [comment]
Problem is here https://github.com/microcosm-cc/bluemonday/blob/3cce251c9ed2a9ee66c8f8984fff3d19d45999df/sanitize.go#L131

**Comment by zeripath** [comment]
There's a place in goldmark (or at least our extensions) that does the same thing too IIRC. 

@lunny thanks for finding that - I knew I'd seen it before when looking at this.

**Comment by lunny** [comment]
@hrvoj3e Could you confirm #14156 fix this?

**Comment by hrvoj3e** [comment]
I am using docker deploy so I tried `gitea:latest` - bug is still here.
`Gitea Version: 1.14.0+dev-476-g3175d0862`

Could you test on https://try.gitea.io/hrv3/issue-14090 or just clone that repo to see if it works?
All 3 URLs should have href like this `https://example.com/?route=action&id=999` (`route` before `id`)

**Comment by lunny** [comment]
@hrvoj3e We haven't merge it on master or release/v1.13. I have tested https://try.gitea.io/hrv3/issue-14090, it works on my PR now.
