### ISSUE TITLE
The API fails at displaying tags

### ISSUE THREAD

**Issue by Idrinth** [go-gitea/gitea#14092]
- Gitea version (or commit ref): 1.14.0+dev-414-g4ef751215
- OS: Docker
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X] No Can't migrate expample repo

## Description

The API fails at displaying tags at https://*/api/v1/repos/nesbot/carbon/tags

### Migrated Repo to test

https://github.com/briannesbitt/Carbon.git

### Migration Error on try.gitea.io

Migrieren von https://github.com/briannesbitt/Carbon.git fehlgeschlagen.
PANIC whilst trying to do migrate task: runtime error: slice bounds out of range [130:129]

### API-Error on Self--hosted instance

PANIC: runtime error: slice bounds out of range [130:129]
/usr/local/go/src/runtime/panic.go:116 (0x43cf84)
/go/src/code.gitea.io/gitea/modules/git/tag.go:67 (0x8d2fb8)
/go/src/code.gitea.io/gitea/modules/git/repo_tag.go:104 (0x8cbde4)
/go/src/code.gitea.io/gitea/modules/git/repo_tag.go:173 (0x8cd1db)
/go/src/code.gitea.io/gitea/modules/git/repo_tag.go:208 (0x8cd6f4)
/go/src/code.gitea.io/gitea/routers/api/v1/repo/tag.go:48 (0x20973bd)
/usr/local/go/src/reflect/value.go:476 (0x4a4d26)
/usr/local/go/src/reflect/value.go:337 (0x4a4218)
/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:177 (0xc65ed9)
/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:137 (0xc658aa)
/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:126 (0xc673fc)
/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:116 (0x155bc08)
/go/src/code.gitea.io/gitea/modules/context/api.go:234 (0x155bbf6)
/usr/local/go/src/reflect/value.go:476 (0x4a4d26)
/usr/local/go/src/reflect/value.go:337 (0x4a4218)
/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:177 (0xc65ed9)
/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:137 (0xc658aa)
/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:126 (0xc673fc)
/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:116 (0x1510864)
/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/session/session.go:192 (0x151084d)
/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:82 (0xc67272)
/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:157 (0xc65bf4)
/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:135 (0xc65999)
/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:126 (0xc673fc)
/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/router.go:187 (0xc78d30)
/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/router.go:303 (0xc733e5)
/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/macaron.go:218 (0xc6c5ed)
/go/src/code.gitea.io/gitea/routers/routes/chi.go:289 (0x217d347)
/usr/local/go/src/net/http/server.go:2042 (0x1f7d2b1)
/go/src/code.gitea.io/gitea/vendor/github.com/go-chi/chi/mux.go:437 (0x1f7d2b2)
/usr/local/go/src/net/http/server.go:2042 (0x77d083)
/go/src/code.gitea.io/gitea/vendor/github.com/go-chi/chi/mux.go:70 (0x1f7b04b)
/go/src/code.gitea.io/gitea/vendor/github.com/go-chi/chi/mux.go:298 (0x1f81301)
/usr/local/go/src/net/http/server.go:2042 (0x77d083)
/go/src/code.gitea.io/gitea/vendor/github.com/go-chi/chi/mux.go:431 (0x1f7d2ea)
/usr/local/go/src/net/http/server.go:2042 (0x77d083)
/go/src/code.gitea.io/gitea/routers/routes/chi.go:160 (0x217c231)
/usr/local/go/src/net/http/server.go:2042 (0x77d083)
/go/src/code.gitea.io/gitea/routers/routes/chi.go:160 (0x217c231)
/usr/local/go/src/net/http/server.go:2042 (0x77d083)
/go/src/code.gitea.io/gitea/modules/public/public.go:84 (0x13c7747)
/usr/local/go/src/net/http/server.go:2042 (0x77d083)
/go/src/code.gitea.io/gitea/modules/public/public.go:84 (0x13c7747)
/usr/local/go/src/net/http/server.go:2042 (0x77d083)
/go/src/code.gitea.io/gitea/routers/routes/chi.go:113 (0x217b7dd)
/usr/local/go/src/net/http/server.go:2042 (0x77d083)
/go/src/code.gitea.io/gitea/routers/routes/chi.go:90 (0x217aa5c)
/usr/local/go/src/net/http/server.go:2042 (0x77d083)
/go/src/code.gitea.io/gitea/vendor/github.com/go-chi/chi/middleware/realip.go:34 (0x1f8687c)
/usr/local/go/src/net/http/server.go:2042 (0x77d083)
/go/src/code.gitea.io/gitea/vendor/github.com/go-chi/chi/mux.go:86 (0x1f7ae10)
/go/src/code.gitea.io/gitea/vendor/github.com/gorilla/context/context.go:141 (0x1182bd3)
/usr/local/go/src/net/http/server.go:2042 (0x77d083)
/usr/local/go/src/net/http/server.go:2843 (0x780682)
/usr/local/go/src/net/http/server.go:1925 (0x77be8c)
/usr/local/go/src/runtime/asm_amd64.s:1374 (0x477dc0)

**Comment by 6543** [comment]
@Idrinth is this issue about not be able to migrate or the api throwing a stacktrace?

**Comment by 6543** [comment]
confirm:
```
slice bounds out of range [130:129]
	Stacktrace: /usr/lib/go/src/runtime/panic.go:116 (0x4372e4)
		goPanicSliceB: panic(boundsError{x: int64(x), signed: true, y: y, code: boundsSliceB})
	/gitea/modules/git/tag.go:67 (0x8cc778)
		parseTagData: tag.Message = string(data[nextline+1 : len(data)-1])
	/gitea/modules/git/repo_tag.go:84 (0x8c556a)
		(*Repository).getTag: tag, err := parseTagData(data)
	/gitea/modules/git/repo_tag.go:153 (0x8c68b6)
		(*Repository).GetTag: tag, err := repo.getTag(id, name)
	/gitea/modules/repository/repo.go:234 (0x13fb6dc)
		PushUpdateAddTag: tag, err := gitRepo.GetTag(tagName)
	/gitea/modules/repository/repo.go:224 (0x13fb4d8)
		SyncReleasesWithTags: if err := PushUpdateAddTag(repo, gitRepo, tagName); err != nil {
	/gitea/modules/repository/repo.go:119 (0x13f9ce9)
		MigrateRepositoryGitData: if err = SyncReleasesWithTags(repo, gitRepo); err != nil {
	/gitea/modules/migrations/gitea_uploader.go:128 (0x1cf297a)
		(*GiteaLocalUploader).CreateRepo: r, err = repository.MigrateRepositoryGitData(g.ctx, owner, r, base.MigrateOptions{
	/gitea/modules/migrations/migrate.go:138 (0x1d06d34)
		migrateRepository: if err := uploader.CreateRepo(repo, opts); err != nil {
	/gitea/modules/migrations/migrate.go:110 (0x1d06437)
		MigrateRepository: if err := migrateRepository(downloader, uploader, opts); err != nil {
	/gitea/modules/task/migrate.go:109 (0x1d262b7)
```

**Comment by zeripath** [comment]
It would be very helpful to discover exactly which tag is causing this.

**Comment by zeripath** [comment]
it is likely to be one of tag 1.22.0 or 1.22.1

**Comment by zeripath** [comment]
OK so the issue is that parseTagData was written and assumes a terminal newline at the end of the mssage

**Comment by 6543** [comment]
@zeripath https://github.com/go-gitea/gitea/pull/14105
