### ISSUE TITLE
Add Repository button missing in latest 1.13 (1.13.0)

### ISSUE THREAD

**Issue by joshmorel** [go-gitea/gitea#14093]
- Gitea version (or commit ref): 1.13.0
- Git version: n/a (template issue) but 2.26.2
- Operating system: Running on Ubuntu 18.04. docker-compose following instructions here - https://docs.gitea.io/en-us/install-with-docker/#basics
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No - it is already on 1.14
- Log gist:

## Description

Version 1.13.0 does't have Add Repository button. You can see here also as well as screenshot below: https://github.com/go-gitea/gitea/blob/70038719bf29b19c0be8d06df47984b104693c04/templates/user/dashboard/repolist.tmpl#L26

It is in 1.12.* and back in 1.14.*. Not a good one to use for docker install example. I got to the page and was scratching my head. 

### 1.13.0

![image](https://user-images.githubusercontent.com/10546720/102800567-0db97700-4382-11eb-89cc-790fe63fbf4d.png)

### 1.14.*

![image](https://user-images.githubusercontent.com/10546720/102800053-591f5580-4381-11eb-9b4a-7f955141c014.png)

**Comment by lunny** [comment]
Hm, This should be removed from v1.14.

**Comment by joshmorel** [comment]
@lunny :man_shrugging: I see also the add repo in the header (1.14) which is fine (like GitHub).

But in 1.13.0 (suggested with docker install docs) it was very confusing. I can add an organization but not a repository? What is going on here...

**Comment by lunny** [comment]
I remember there is an issue or pull request to say that but cannot find it.

**Comment by silverwind** [comment]
The button was added as a "feature" in 1.14, it was never there in 1.13 or below. As it was part of a bigger refactor to that box, I decided not to backport to 1.13.

**Comment by joshmorel** [comment]
Whatever you decide to do it would be good to consistently have the + sign for not for that box for Repository & Organization.

This UX was confusing. Because there was a + for Organization and not Repository I didn't even notice the the navbar + icon as I tried to figure out what had gone wrong such that I couldn't add a Repository.

![gitea-ux-issue](https://user-images.githubusercontent.com/10546720/102810159-35640b80-4391-11eb-80e3-21e2fe74eb2a.gif)

**Comment by silverwind** [comment]
I don't think I will backport this one. If you want the button upgrade to 1.14 or wait for the stable release. Historically the primary way to create a repo is the `+` button in the header, these buttons here came later as an alternative.

**Comment by joshmorel** [comment]
@silverwind it's not for for my sake at this point since I get what's going on. It's just a potential UX turn off for potential new users.
