### ISSUE TITLE
DB topic.name uses varying(25) which makes mirrors of repos with long topics fail

### ISSUE THREAD

**Issue by michaelx** [go-gitea/gitea#14108]
- Gitea version: 1.13.0 (also fails on latest dev)
- Git version: 2.26.2
- Operating system:
  - `docker-compose` with the image `gitea/gitea:1`
- Database:
  - [x] PostgreSQL

## Description

1. Create new migration
2. Select GitHub
3. Clone `https://github.com/survivejs/webpack-book` as a **mirror**
4. Will fail with: 

```
Migrate repository from https://github.com/survivejs/webpack-book failed: pq: value too long for type character varying(25)
```

Can be solved by using `varying(255)` on `topic.name`. Is there a reason it's limited to 25?

**Comment by lunny** [comment]
We need index the column, so it shouldn't too big. How many characters with Github Topic name? 🤔

**Comment by michaelx** [comment]
The one it fails with is 26, but I think it would be fine to just drop topics that are too long on migration. Gitea shouldn't fail just because of it though. What do you think?

**Comment by lunny** [comment]
@michaelx Good idea! We need a PR to fix that.

**Comment by michaelx** [comment]
PR is up for grabs as this isn't my stack, I am afraid. Thanks.

**Comment by zeripath** [comment]
it certainly appears that there is no limit in GH

**Comment by Vitexus** [comment]
I confirm that error:


```
2020/12/23 00:03:39 ...ules/task/migrate.go:67:func1() [E] DeleteRepository: repository does not exist [id: 35, uid: 2, owner_name: , name: ]
```

2020/12/23 00:03:39 modules/task/task.go:51:handle() [E] Run task failed: Error 1406: Data too long for column 'name' at row 1



**Is it an typo ?** All other `name`s in database are 255 chars long. 
I'll fix it manually in my db using 

```mysql
ALTER TABLE `topic` CHANGE `name` `name` VARCHAR(255); 
```

After that migration was successfull

**Comment by zeripath** [comment]
it's partly to do with the fact that they're indexed but I suspect it's an incorrect decision and we should just increase that field and either make it be indexed with bleve or just deal with it.

**Comment by Vitexus** [comment]
I didn't provide pull request cause i don't know right final solution. It was only dirty hotfix. I'm looking forward fixed version.

**Comment by Vitexus** [comment]
Please note:  **NOT ONLY POSTGRES**
I use MariaDB with the same problem.

**Comment by somera** [comment]
In which Gitea version it will be fixed?

**Comment by lunny** [comment]
A simple solution is to change to a big size i.e. 50 , but that may also not enough?
