### ISSUE TITLE
Plan to start time and end time on issue

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#1411]
When create or update an issue, we can assign a planned start time and end time.

**Comment by bkcsoft** [comment]
Doesn't most workflows use Milestones? Milestones already have due-dates AFAIK :)

**Comment by lunny** [comment]
Milestones have due-dates but issues have not. This feature will plan the work more detail. Like a project management program.

**Comment by kolaente** [comment]
I think this is related to  #2533

**Comment by lunny** [comment]
@kolaente yes, right.
