### ISSUE TITLE
[FEATURE] Add "ignore whitespace" option in diff

### ISSUE THREAD

**Issue by dusatvoj** [go-gitea/gitea#14117]
- Gitea version (or commit ref): 
- Git version: 1.13.0
- Operating system: any
  
  
  
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
- Log gist:

## Description
`Ignore whitespace` option in diff like in bitbucket, etc.

## Screenshots
![image](https://user-images.githubusercontent.com/11560794/102930701-3f733080-449d-11eb-84f0-e37a442f9427.png)

**Comment by techknowlogick** [comment]
This already exists in Gitea.

you can see it in action in this diff: https://gitea.com/gitea/theme/pulls/92/files

**Comment by dusatvoj** [comment]
@techknowlogick Is it in stable version or dev? I can't see this feature in our self-hosted gitea `1.13.0`
I've tried smth like "Click on commit in repo" ... there's no action to ignore whitespace (even on gitea.com instace https://gitea.com/gitea/theme/commit/4d5fbe24b80542109690c95ab53461c4ec6cba9e)
Now I'm looking to our self-hosted gitea to commit view and there's no action even with whitespace only diff lines
![image](https://user-images.githubusercontent.com/11560794/102937159-d0500900-44a9-11eb-9bd0-229ddf591e0e.png)
