### ISSUE TITLE
Error pagination on Adopt repositories admin page

### ISSUE THREAD

**Issue by camlafit** [go-gitea/gitea#14111]
- Gitea version (or commit ref): 1.13.0
- Git version:
- Operating system: Debian
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
- Log gist:
Not relevant
## Description

On /admin/repos/unadopted?search=true&q= pagination doesn't work. Only first page propose abandonned repository.

I presume it's related to #12920

## Screenshots

![Capture d’écran de 2020-12-22 15-46-52](https://user-images.githubusercontent.com/209915/102900765-0fac3480-446d-11eb-937d-ca719b3ecb1f.png)
![Capture d’écran de 2020-12-22 15-47-00](https://user-images.githubusercontent.com/209915/102900763-0f139e00-446d-11eb-8a87-08fcf56cd594.png)

**Comment by zeripath** [comment]
The problem is that the page turns are missing the search=true parameter
