### ISSUE TITLE
Feature request: Show linked PRs (if any) in Projects

### ISSUE THREAD

**Issue by nadiamoe** [go-gitea/gitea#14127]
- Gitea version (or commit ref): v1.13.0

## Description

At this moment, both PRs and Issues can be added to Projects, which I think it's a nice feature. However, issues being tracked in a Project do not reflect having any PRs attached to them. This makes navigation a bit cumbersome, specially if one is making use of the popular "Ready for review" column, as a reviewer has to navigate to the issue and then to the PR linked in it.

I think it would be nice if PRs showed as an add-in to issue cards in the Project view. This is similar to what github does.

## Screenshots

| How it looks now | How I think it could be improved (from Github.com) |
|---|---|
| ![Current state](https://user-images.githubusercontent.com/969721/103005745-50ba4c80-4532-11eb-9302-d3b7979b4aa3.png)   | ![DeepinScreenshot_select-area_20201223152148](https://user-images.githubusercontent.com/969721/103006795-99720580-4532-11eb-973b-44bca55387da.png) |

**Comment by roobre** [comment]
I forgot to mention that I can try to work on a PR for this if you think it'd be a useful feature, and give me some pointers on where to get started!

**Comment by lunny** [comment]
@roobre I think we have stored the information on comment table but they have neither been displayed on issue page right sidebar nor projects, dashboard. But it's useful I think.
