### ISSUE TITLE
Error on Issue-Events

### ISSUE THREAD

**Issue by Schwobaland** [go-gitea/gitea#1413]
- Gitea version (or commit ref): 1.1.0
- Operating system: Windows
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite

## Description

There are some html-structure-errors, when editing an issue, see screenshot. 
...

## Screenshots
![issue_error](https://cloud.githubusercontent.com/assets/5707405/24496141/b831e870-1537-11e7-83e1-4f46a87c0b01.png)

**Comment by lunny** [comment]
This has been reported by #1174 and resolved by #1177

**Comment by Schwobaland** [comment]
@lunny Thanks! Are there plans to release a bugfix 1.1.x-release? if (true) -> any time schedule?

**Comment by lunny** [comment]
Yes. 1.1.1 will be released soon, just these days.
