### ISSUE TITLE
Green primary color on light theme

### ISSUE THREAD

**Issue by silverwind** [go-gitea/gitea#14149]
On the [logged out frontpage](https://try.gitea.io/), links are green but nearly everything else on the site uses blue links which creates a inconsistency.

![image](https://user-images.githubusercontent.com/115237/103135039-cef32c00-46b5-11eb-92b3-0c7f844a5d22.png)
![image](https://user-images.githubusercontent.com/115237/103135043-dadeee00-46b5-11eb-9a1e-5c705b120c56.png)

I wonder how people feel about either changing the primary color on the base theme to a green (slightly darker to conform WCAG contrast requirements) or alternatively changing the frontpage to also use blue links.

React with 👍 if you like to see green primary color and 👎 if not.

**Comment by pat-s** [comment]
I am wondering if only one shade of green should be used (e.g. the one from the logo). Currently the green for link is different to the one of the logo.

**Comment by techknowlogick** [comment]
I think it makes sense, for accessibility we should have all links be presented similarly anyway. Also in arc-green the links in footer are green, so updating the main theme to be consistent is a good idea.

**Comment by silverwind** [comment]
The chosen primary color should be around the middle of the lighness spectrum while still having enough contrast over the `#fff` background.

Once everything is migrated, we could maybe even have a option for that color.

**Comment by k9t9** [comment]
I totally agree there should be a consistency. 
It somehow always bugged me.

But instead of each one proposing different colors isn't it more efficient to just add some  `customization` color settings where each self-hosted operator could choose their own color ( without tempering with code ) ? 

I am not sure if there is already such a n option - I did not find it on the "Customizing Gitea " page on site - if it's there then please ignore .

**Comment by pat-s** [comment]
@silverwind Are you planning to tackle this in the future? The voting in the OP is roughly 50:50 so hard to decide what to do.

**Comment by silverwind** [comment]
Hmm I guess we leave it at blue then unless there is a overwhelming majority, which there seems to not.
