### ISSUE TITLE
DISABLE_GIT_HOOKS env variable is ignored

### ISSUE THREAD

**Issue by lalelunet** [go-gitea/gitea#14151]
- Gitea version (or commit ref): 1.14.0+dev-461-ga19447aed
- Git version: 2.20.1
- Operating system: Debian 10
   Docker version 20.10.1, build 831ebea
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X] No

## Description
I start a fresh installation from gitea server with docker and provide a empty directory as volume to gitea. As decribed I set the enviroyment variable DISABLE_GIT_HOOKS to false. I am awaiting a "Git-Hooks" button in the project settings.

/usr/bin/docker run \
    .... more parameter like network, dns, ip etc ....
    -v /emptydirectory/:/data/ \
    -e DISABLE_GIT_HOOKS=false \
    gitea/gitea:latest

This creates a default ini file with no DISABLE_GIT_HOOKS entry under security
<img width="475" alt="auto-created-default-ini-file" src="https://user-images.githubusercontent.com/4786404/103153320-16e68180-4790-11eb-8f8e-20ae9d3fdb2e.png">

The parameter is a env variable inside the container but it seems that it is ignored. There is no Git-Hooks option in the web user interface
<img width="199" alt="env-variable-DISABLE_GIT_HOOKS-is-set" src="https://user-images.githubusercontent.com/4786404/103153348-3da4b800-4790-11eb-96f5-be583ed73487.png">
<img width="555" alt="ui-without-git-hook-option" src="https://user-images.githubusercontent.com/4786404/103153356-485f4d00-4790-11eb-859a-e48f8b8fe90c.png">

Then I edit the persistent ini file and add the missing DISABLE_GIT_HOOKS under security and restart the container. After setting the value in the ini file I am able to use Git-Hooks in the user interface.
<img width="497" alt="manual-edited-ini-file" src="https://user-images.githubusercontent.com/4786404/103153376-5f9e3a80-4790-11eb-8c0a-14c6041c42f5.png">
<img width="638" alt="option-git-hook-is-available-after-setting-the-parameter-in-ini-file" src="https://user-images.githubusercontent.com/4786404/103153394-78a6eb80-4790-11eb-8db6-7fc4219f4a41.png">

**Comment by techknowlogick** [comment]
DISABLE_GIT_HOOKS is not an env var that the docker image accepts. Please read the Gitea docker documentation for the list of env vars that are available for initial configuration.
