### ISSUE TITLE
[Feature request] make a milestone edit box also a rich edit box (as the one for a wiki page or an issue)

### ISSUE THREAD

**Issue by mxp1983** [go-gitea/gitea#14158]
It would be great if the edit box for the milestone's description would be also a rich edit box - the same as for a wiki page or an issue.

**Comment by silverwind** [comment]
We're planning to move away from the bug-ridden "rich" box back to a plain textarea, so this is unlikely to happen. See https://github.com/go-gitea/gitea/issues/10729 and linked issues.

**Comment by maksymilian-palka** [comment]
From my point of view, some basic WYSIWYG features would be nice - no matter what editor is used. Even some buttons to add snippets, like link, code, headers would be enough. 
But having side-by-side text area and preview area would be a luxury :)

**Comment by silverwind** [comment]
A markdown preview tab can of course be done, maybe even with an option to have it side by side, but the edit area will remain a simple textarea.

**Comment by maksymilian-palka** [comment]
Well, then I hope for the best - that side by side view will arrive soon.
