### ISSUE TITLE
Can't execute APK file downloaded from assets in versions page, on Android

### ISSUE THREAD

**Issue by pokapow** [go-gitea/gitea#14164]
- Gitea version (or commit ref): 1.13
- Operating system: Debian 10
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes : https://try.gitea.io/poka/test-apk/releases
  - [ ] No

## Description

When download APK android installer from version assets in Gitea **on mobile**, when click the link from APK we can't juste download and execute to install the app.

Instead, browser want to open it with archive unzipper.

If we download the same APK form nextcloud for exemple, Android try to install it directly...

It's not very usefull when we want to share our mobile app from github versions page...

<img src="https://user-images.githubusercontent.com/30467320/103182744-01677980-48ae-11eb-8cb8-d38d47d48218.jpg" width="300" />

**Comment by gsantner** [comment]
probably only a matter of mime type response header

**Comment by pokapow** [comment]
I think so yes, maybe it can be fix by changing mime type in gitea links ?

**Comment by Seil0** [comment]
I got the same issue. When downloading a .apk file it is downloaded as .zip file.

Gitea version (or commit ref): 1.13.1

**Comment by gsantner** [comment]
Mime Type should be:  
`application/vnd.android.package-archive`

**Comment by zeripath** [comment]
Are you using an http proxy?

**Comment by pokapow** [comment]
Yes nginx.

I tried solutions write here: https://stackoverflow.com/questions/46285863/set-headers-for-apk-files-served-by-nginx

But it's doesn't work for me, since Gitea .apk download URL doesn't have the extension inside URL, I think that's the problem.

**Comment by gsantner** [comment]
I have gitea with [apache](https://docs.gitea.io/en-us/reverse-proxies/#apache-httpd-with-a-sub-path)

**Comment by zeripath** [comment]
So you're trying to download the automatically generated archive files which have filenames *.zip as .apk?

**Comment by techknowlogick** [comment]
The below is out put from querying the apk from the try.gitea.io link above, seems the content type we are providing is `Content-Type: application/zip`, I think we are getting the content type from `net/http`'s `DetectContentType`. A quick/dirty way would be to check if file is determined to be a zip, but has an extension of `.apk` then we modify the content-type response.

```
> http https://try.gitea.io/attachments/8d500ecf-0c93-4409-9f94-8801ba4000c0  ~
HTTP/1.1 200 OK
Access-Control-Expose-Headers: Content-Disposition
Cache-Control: public,max-age=86400
Content-Disposition: attachment; filename="Speed Check Light 5G 4G LTE WiFi_v2.1.1.0_apkpure.com.apk"
Content-Type: application/zip
Date: Sun, 10 Jan 2021 02:25:51 GMT
...
```
