### ISSUE TITLE
Why timeout？

### ISSUE THREAD

**Issue by yuyu414** [go-gitea/gitea#14168]
The configuration of the machine is enough, about seven or eight people use it together. What is the possible reason? If it is improved?

**Comment by lunny** [comment]
Please give more details.

**Comment by yuyu414** [comment]
Push failed
			Unable to access 'http://xxxxx/xxx/xxx-mall-app.git/': Failed to connect to xxxxxx.xxx.com port 80: Timed out

**Comment by 6543** [comment]
@yuyu414 do you use a reverse proxy?

I think this is a configuration issue

**Comment by yuyu414** [comment]
大概十几个人在用， 推送比较频繁，经常性的出现上述情况，不知道什么原因，或者在哪可以排查到，现在的处理方式是间隔一段时间多推送几次就可以成功，如何配置？

**Comment by yuyu414** [comment]
> 大概十几个人在用， 推送比较频繁，经常性的出现上述情况，不知道什么原因，或者在哪可以排查到，现在的处理方式是间隔一段时间多推送几次就可以成功，如何配置？
About a dozen people are using it, and the push is quite frequent,
Frequent occurrence of the above situation, do not know what reason
The current processing method is to push several more times in a period of time
And when it happens, the web page cannot be accessed

**Comment by yuyu414** [comment]
Does he need a lot of bandwidth？

**Comment by 6543** [comment]
@yuyu414 we need more information how your gitea inctance is setup:
* what OS it runns on? [Window|Linuy|Mac|BSD|...]
* what version (can be obtained via `http(s)://your.gitea.com/api/v1/version`
* whitch reverse proxy is used? _**[more info](https://docs.gitea.io/en-us/reverse-proxies/)**_

**Comment by yuyu414** [comment]
`APP_NAME = XXXXXX
RUN_USER = XXXX
RUN_MODE = XXXXX

[oauth2]
JWT_SECRET = XXXXXXXXXXXXXXXX

[security]
INTERNAL_TOKEN = XXXXX
INSTALL_LOCK   = true
SECRET_KEY     = XXXXX

[database]
DB_TYPE  = mysql
HOST     = XXXXXXX
NAME     = XXXXX
USER     = XXXXX
PASSWD   = XXXXX
SSL_MODE = XXXXX
CHARSET  = XXXXX
PATH     = XXXXX

[repository]
ROOT = /XXX/XXX-XXXX

[server]
SSH_DOMAIN       = git.XXXX.cn
DOMAIN           = git.XXXX.cn
HTTP_PORT        = 3000
ROOT_URL         = http://git.XXXXX.cn/
DISABLE_SSH      = false
SSH_PORT         = 6000
LFS_START_SERVER = true
LFS_CONTENT_PATH = /opt/gitea/data/lfs
LFS_JWT_SECRET   = XXXXXXXXXX
OFFLINE_MODE     = false

[mailer]
ENABLED = false

[service]
REGISTER_EMAIL_CONFIRM            = false
ENABLE_NOTIFY_MAIL                = false
DISABLE_REGISTRATION              = true
ALLOW_ONLY_EXTERNAL_REGISTRATION  = false
ENABLE_CAPTCHA                    = false
REQUIRE_SIGNIN_VIEW               = true
DEFAULT_KEEP_EMAIL_PRIVATE        = false
DEFAULT_ALLOW_CREATE_ORGANIZATION = true
DEFAULT_ENABLE_TIMETRACKING       = true
NO_REPLY_ADDRESS                  = noreply.localhost

[picture]
DISABLE_GRAVATAR        = true
ENABLE_FEDERATED_AVATAR = false

[openid]
ENABLE_OPENID_SIGNIN = false
ENABLE_OPENID_SIGNUP = false

[session]
PROVIDER = file

[log]
MODE      = file
LEVEL     = info
ROOT_PATH = /opt/gitea/log

`

**Comment by 6543** [comment]
ok :point_up_2: with this info you **DO USE** a reverce proxy ... so it is either a timeout on the proxy side or one via git config

**Comment by yuyu414** [comment]
> @yuyu414 we need more information how your gitea inctance is setup:
> 
> * what OS it runns on? [Window|Linuy|Mac|BSD|...] LINUX
> * what version (can be obtained via `http(s)://your.gitea.com/api/v1/version` Go1.13.9
> * whitch reverse proxy is used? _**[more info](https://docs.gitea.io/en-us/reverse-proxies/)**_  NO

**Comment by yuyu414** [comment]
> ok 👆 with this info you **DO USE** a reverce proxy ... so it is either a timeout on the proxy side or one via git config
> 
> * change git timeout settings: https://docs.gitea.io/en-us/config-cheat-sheet/#git---timeout-settings-gittimeout
> * change nginx proxy timeout settings: https://subscription.packtpub.com/book/networking_and_servers/9781849514965/7/ch07lvl1sec72/setting-up-correct-reverse-proxy-timeouts
Thank you. I'll try

**Comment by 6543** [comment]
if you dont use reverse proxy you should set `HTTP_PORT = 3000` to `HTTP_PORT = 80` and make sure it is allowed to lisen to this port if running onlinux: https://unix.stackexchange.com/questions/10735/allowing-a-user-to-let-listen-to-a-port-below-1024#10737
