### ISSUE TITLE
docker version send email timeout

### ISSUE THREAD

**Issue by louandme** [go-gitea/gitea#14181]
read udp 172.17.0.3:49043->114.114.114.114:53: i/o timeout,so what is the port 49043?  i use telnet 172.17.0.3 49043 that reponse me connection refused ,but in document i only find -p 10022:22 -p 10080:3000 .

**Comment by techknowlogick** [comment]
Your DNS is failing to resolve `:53` is the DNS port.

According to a quick whois 114.114.114.114 belongs to 114dns.com, which I assume is your DNS provider. It is likely having issues, or a network issue (such as a firewall) is preventing you from connecting. Either way we are unable to assist in debugging.

**Comment by louandme** [comment]
> Your DNS is failing to resolve `:53` is the DNS port.
> 
> According to a quick whois 114.114.114.114 belongs to 114dns.com, which I assume is your DNS provider. It is likely having issues, or a network issue (such as a firewall) is preventing you from connecting. Either way we are unable to assist in debugging.
 
In fact ,telnet 114.114.114.114 53 is ok , and 172.17.0.3 is the ip of contanier .
 I was used my computer local vm to build gitea server whith stopped firewalld.
In my test,just only ping 172.17.0.3 is ok ,but telnet 172.17.0.3 whith port 49043 is not.


![1609225215(1)](https://user-images.githubusercontent.com/53675908/103265056-a6d23880-49e7-11eb-9ab7-b38e9e1dd009.png)
![1609225336(1)](https://user-images.githubusercontent.com/53675908/103265059-a89bfc00-49e7-11eb-8419-d9e2e1c46ed4.png)
![1609225510(1)](https://user-images.githubusercontent.com/53675908/103265060-a9349280-49e7-11eb-8eb5-a7c38c5accdf.png)
![1609225610(1)](https://user-images.githubusercontent.com/53675908/103265062-a9cd2900-49e7-11eb-8d9f-2bec2225d97b.png)

**Comment by techknowlogick** [comment]
When creating a network connection there is a four-tuple needed. A source ip & port, and a destination ip & port. The source port is an ephemeral port used and is not serving anything but rather for receiving the results of the request (this is a simplified description and there is a bit of nuance that is missed, but is mostly right). You'll see in your first screenshot that a different source port is used when attempting to make a DNS lookup.

The error being shown in your logs is that DNS is failing to connect on port 53. For debugging I recommend using the linux `dig` tool, or perhaps changing your DNS settings to a different DNS provider to see if the error in your logs is the same.

**Comment by louandme** [comment]
thanks for your advice :)
