### ISSUE TITLE
mentions are not persisted when ENABLE_NOTIFY_MAIL=false

### ISSUE THREAD

**Issue by jpraet** [go-gitea/gitea#14187]
Gitea version (or commit ref): 1.14.0

## Description

When ENABLE_NOTIFY_MAIL in app.ini is set to false, mentions in issues / pulls are not persisted (so not listed in the "Mentioning You" filter on the dashboard).

**Comment by zeripath** [comment]
https://github.com/go-gitea/gitea/blob/ac88b0ee839bfbfae5759e211d0f9a69abe4d8f7/services/mailer/mail_comment.go#L21-L29 

This logic does not belong in mail_comment.go

**Comment by jpraet** [comment]
I'm working on a PR, combined with #14013.

**Comment by zeripath** [comment]
I would not be at all surprised if that had the same root cause
