### ISSUE TITLE
Settings->Repositories causing "500" error if the user (the user is an admin) has not created/owned any repository

### ISSUE THREAD

**Issue by georgewayne** [go-gitea/gitea#14189]
- Gitea version (or commit ref): 1.13.1 built with GNU Make 4.3, go1.15.6 : bindata, timetzdata, sqlite, sqlite_unlock_notify
- Git version: 2.26.2
- Operating system: Linux
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x
![Capture](https://user-images.githubusercontent.com/15681127/103335886-4d8bf880-4a2b-11eb-910d-7d838a67e77c.JPG)
] No
- Log gist:

## Description

logged in user is a site admin who has not created or own any repository. Would get "500" error (screen shot attached) when choose Settings->Repositories tab.

**Comment by zeripath** [comment]
please give us logs,

**Comment by zeripath** [comment]
seriously if you just gave us logs I would be able to sort this out without having to fire up a gitea instance.

**Comment by zeripath** [comment]
2020/12/30 16:54:48 ...r/setting/profile.go:257:Repos() [E] filepath.Walk: lstat /data/git/repositories/administrator: no such file or directory

**Comment by zeripath** [comment]
which comes from:

https://github.com/go-gitea/gitea/blob/632800eda7108e5e8d90dd9e3e985da3deecf365/routers/user/setting/profile.go#L257
