### ISSUE TITLE
Wrong repository size shown

### ISSUE THREAD

**Issue by nicorac** [go-gitea/gitea#14182]
- Gitea version (or commit ref): 1.13.1
- Git version: 2.7.4
- Operating system: Ubuntu Server 16.04.7 LTS x64
- Gitea official release: https://github.com/go-gitea/gitea/releases/tag/v1.13.1
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No

## Description
I have a repository that contained a lot of commits and branches.
Now I've cleaned it up leaving only a single _master_ branch with a single commit.
Repo statistics still show the previous size (204MB)... but it actually should be 0 😉.

This is `du` run on repo directory:
```
# du -h /var/git/repositories/abcd/efgh.git
8.0K    ./objects/info
12K     ./objects/pack
24K     ./objects
8.0K    ./hooks/pre-receive.d
8.0K    ./hooks/post-receive.d
8.0K    ./hooks/update.d
80K     ./hooks
4.0K    ./branches
12K     ./info
4.0K    ./refs/heads
4.0K    ./refs/tags
12K     ./refs
152K    .
```
As you can see the repo is empty, nothing inside it.

I've waited for the _statistics update_ task to complete (@every 24h) but it still shows 204MB.
(`void` is a plain UTF-7 file that contains the "void" chars: 7 bytes long)
![immagine](https://user-images.githubusercontent.com/2361673/103288413-185cb780-49e5-11eb-8643-ff14b4ee466f.png)

I've run the task manually (several times); it completes without errors but Gitea still shows 204MB usage.
![immagine](https://user-images.githubusercontent.com/2361673/103288182-9ec4c980-49e4-11eb-8ac3-469f0080ce4d.png)

**Comment by zeripath** [comment]
how did you "clean" the repository?

**Comment by nicorac** [comment]
I've just deleted all branches but `master`, set `master` on first commit then pushed to Gitea (with --force)

**Comment by halx99** [comment]
Does this issue solved, I also meet it

**Comment by wxiaoguang** [comment]
Please try the latest release and feel free to reopen.

**Comment by microcai** [comment]
好像没修好啊, 还是不更新的
