### ISSUE TITLE
Migrate from one gitea instance to another

### ISSUE THREAD

**Issue by Madmorgan007** [go-gitea/gitea#14195]
- Gitea version (or commit ref): 1.13.1
- Git version:
- Operating system: Windows 10
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x ] SQLite

I'm trying to move all my git projects off the current pc where they are been hosted onto a new machine.

I'm trying to migrate the data from the old server to the new machine using the UI and selecting new migrate > gitea.

it will not copy the data over because it says.

migrate from 'macmini:3000' is not allowed: the host resolve to a private ip address '192.168.1.232'

can you please tell me how to allow this.

Thanks

**Comment by lunny** [comment]
You can temporarily change the app.ini
```
[migrations]
BLOCKED_DOMAINS=
```

**Comment by Madmorgan007** [comment]
hi that does not seem to work can you please give a better example.

I have tried like this:
[migrations]
BLOCKED_DOMAINS = 192.168.1.232

[migrations]
BLOCKED_DOMAINS = false

[migrations]
BLOCKED_DOMAINS =

**Comment by jolheiser** [comment]
This is the [documentation](https://docs.gitea.io/en-us/config-cheat-sheet/#migrations-migrations).
I believe what you actually want is `ALLOW_LOCALNETWORKS = true`

**Comment by Madmorgan007** [comment]
thanks @jolheiser that fixed it now
