### ISSUE TITLE
[UI / Proposal] Just ask me to click yes

### ISSUE THREAD

**Issue by bryanpedini** [go-gitea/gitea#14192]
- Gitea version (or commit ref): 1.12.5
- Git version: 2.18.4
- Operating system: CentOS 8 (core) LXC container on Proxmox VE 6.2 (`Linux <hostname> 5.4.73-1-pve #1 x86_64`)
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (any URL)
  - [ ] No
- Log gist:
Doesn't matter

## Description
I would like to have the option to disable the need to type in the repository name when asked about "dangerous commands" confirmation.
(interestingly enough, "Archive this repo" only requires a "click" confirmation, not to type in the repo name, which is what I would like to happen globally)

Possibly this can be a user-specific setting instead of `app.ini`; since it may be awkward to either enforce users to type in the repo name, or otherwise risk to have them complaining about the fact they clicked "yes" (**two** times) as an "accident"... 🤦🏻‍♂️ 

## Screenshots
![Screenshot_20201230_100636](https://user-images.githubusercontent.com/45012292/103341429-324ed680-4a87-11eb-9f64-1c0143388344.png)
![Screenshot_20201230_100650](https://user-images.githubusercontent.com/45012292/103341431-34b13080-4a87-11eb-99fa-d85551f432ac.png)

---

Thanks in advance!

**Comment by lunny** [comment]
I don't think this is a good idea. `Archive` is an recoverable operation but `Delete` is not.

**Comment by bryanpedini** [comment]
I can understand the dangerous situation, tho maybe I didn't explain it enough: I didn't ask for a default, but for a user option to enable this behavior, something every logged in user can change for themselves, like i.e. themes.
Of course it would be bad for a system administrator to either receive complains about accidental confirmations (in case this was enforced), so like more of a "do whatever you want" approach...

Thank you!

**Comment by lunny** [comment]
@bryanpedini Hm, I don't think we should give too many options for user. Themes options are necessary, but for this one, I personally think it's unnecessary to give an option.

**Comment by techknowlogick** [comment]
Deleting repos is a massively destructive action as not just code would be lost, but also issues, PRs, labels, milestones and a lot more, and even adding it as an option makes it much easier for unexpected data loss. Perhaps this option is enabled and a user wants to click "make private" but instead clicks delete, and not read the yes/no prompt. If you'd like to customize this you can do so using https://docs.gitea.io/en-us/customizing-gitea/ and update templates/add JS to modify this behaviour.

**Comment by bryanpedini** [comment]
> @bryanpedini Hm, I don't think we should give too many options for user.

I see.. understood.

> Deleting repos is a massively destructive action as not just code would be lost, but also issues, PRs, labels, milestones and a lot more, and even adding it as an option makes it much easier for unexpected data loss.

Fair point, I guess 😅

> If you'd like to customize this you can do so using https://docs.gitea.io/en-us/customizing-gitea/ and update templates/add JS to modify this behaviour.

Thanks for the info, I thought only like look and stuff could be edited, not the "core functionality" of the app.

Sorry if I made you waste some time, I thought this since I primarily use Gitea either as a mirror for my personal repositories on GitHub (and registration is disabled) and/or for my very very private code that does **not** go on GitHub for _various_ reasons.
Then I thought somebody else could appreciate, but clearly (I see now, and can understand perfectly) data loss prevention is a lot more important than user sactisfaction in needing to press two or three less keystrokes.
