### ISSUE TITLE
Mobile doesn't use language set in profile consistently

### ISSUE THREAD

**Issue by DuckDuckWhale** [go-gitea/gitea#14190]
- Gitea version (or commit ref): 1.13.1
- Git version: 2.25.1
- Operating system: Ubuntu Server 20.04
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Haven't tried
- Log gist: N/A

## Description

I have observed this happening in 1.12.5 and reproduced in 1.13.0 and 1.13.1. My profile language is set to be different from my system language on the phone, but often times the language that ends up getting used is the system language. If I log out then log in, the language used is the language set in profile as expected, but after restarting Firefox on Android 84.1.2 it changes back to the system language.

**Comment by silverwind** [comment]
Language is stored in a cookie. Is the browser configured to clear cookies on restart?

**Comment by MathJoDE** [comment]
> Language is stored in a cookie. Is the browser configured to clear cookies on restart?

This may be due to #14482 ?

**Comment by lunny** [comment]
@MathJoDE No. It's another one.

**Comment by DuckDuckWhale** [comment]
> Language is stored in a cookie. Is the browser configured to clear cookies on restart?

It is not; there is no special configuration on the browser. Reproduced on Firefox Android 89.1.1 and Gitea 1.14.3.

**Comment by delvh** [comment]
Does this issue still occur?
Feel free to reopen if it does.
