### ISSUE TITLE
Default Explore to moststars

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#14209]
- Gitea version (or commit ref): 1.13.0
- Git version: ¯\_(ツ)_/¯
- Operating system: Ubuntu 20.10 x64 (Gitea Helm/K3s)
- Database:
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not applicable
- Log gist: N/A

## Description

I'd like a way to default sort items by `moststars` descending when landing users on `explore` via `LANDING_PAGE` param.

**Comment by balibebas** [comment]
I changed my mind. :D
