### ISSUE TITLE
Poster-Marking on Issue Comment without being the Poster

### ISSUE THREAD

**Issue by fossdd** [go-gitea/gitea#14205]
- Gitea version (or commit ref): 1.14.0+dev-486-gef825bd24
- Git version: Not relevant
- Operating system: Unknown (try.gitea.com)
  
  
  
- Database: Unknown (try.gitea.com)
- Can you reproduce the bug at https://try.gitea.io:
  - Yes: https://try.gitea.io/test_account/test_repo/issues
- Log gist: Unknown (try.gitea.com)

#### 1. problem

I've sign up on try.gitea.com, created a repository and a issue. Next i've logged out and sign up another account and writtern a reply on the issue.

The reply message was marked as `Poster` but he is not the Poster of the issue.

#### 2. problem

Now i've created a issue with the 2. account and the message is not marked as `Poster`. The Repo-Owner Account replied and is marked as `Poster` and `Owner`. 

## Screenshots

`test_account` is the Repo-Owner.
`test_account_2` is a random account.

Can also seen in https://try.gitea.io/test_account/test_repo/issues

![Screenshot showing the explained 1. issue](https://user-images.githubusercontent.com/76472134/103419458-7b8c4c80-4b93-11eb-9b93-2f6f51fd651e.png)

![Screenshot showing the explained 2. issue](https://user-images.githubusercontent.com/76472134/103420680-c5c3fc80-4b98-11eb-9178-2c880d630cae.png)

**Comment by 42wim** [comment]
Can not be reproduced anymore, closing
