### ISSUE TITLE
issue count gets stuck when closing an issue via commit log

### ISSUE THREAD

**Issue by strk** [go-gitea/gitea#14204]
Commits which `close #xx` do close the issue, but from the web the issue count does not update, even on reload. See screenshot

![stuck_issue_count](https://user-images.githubusercontent.com/289678/103415672-83dc8b80-4b83-11eb-9c9b-c8422b4a49ab.png)

This is with Gitea 1.12.3 I haven't tested on try.gitea.io

**Comment by lunny** [comment]
I remember this bug. Please help to confirm this has been resolved. on 1.13 or master.

**Comment by zeripath** [comment]
the issue proforma is there for a reason.

we've already fixed this problem recently - so it would be very helpful to know if we can just close this issue as an already fixed duplicate

**Comment by strk** [comment]
If there's another ticket please just link the ticket number here and
close this. I don't see testing this any soon so I won't be of help.
Sorry for not having tested on try.gitea.io before filing this ticket.

**Comment by zeripath** [comment]
#11786

#10536

Fixed by myself in #12900
