### ISSUE TITLE
Wrong link generation of some URLs

### ISSUE THREAD

**Issue by tofulm** [go-gitea/gitea#1422]
Hi,
when I create a new repository,
in the dashboard view, URLs are wrong: 

`Tofulm created repository Gamuza/planning_room`

and the link on **Gamuza/planning_room** is : 
 
`http://mon_domaine.fr/\"/Gamuza/planning_room\"`

- Gitea version : 1.1.0
- Git version: 2.12
- Operating system: Debian 8  / apache2
- Database: mysql

- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X] No
  - [ ] Not relevant

**Comment by tofulm** [comment]
this problem is ONLY in French language !

When I switch to English language, URLs are OK

**Comment by tofulm** [comment]
and : 
`Tofulm created repository Gamuza/planning_room`
in French : 
`Tofulm "a créé le dépôt Gamuza/planning_room"`
There are also double quotes

**Comment by lunny** [comment]
This has been reported by #1174 and resolved by #1177

**Comment by FM-96** [comment]
Has this been fixed for all languages? I know that apart from French the problem existed at least also for German and Dutch.

**Comment by lunny** [comment]
Oh? I think maybe I have fixed all the languages. If I'm not, please fire a concreted issue.

**Comment by FM-96** [comment]
Alright, the problem seems to be fixed for all languages in v1.1.1.

(I guess this issue can be closed now?)

**Comment by tofulm** [comment]
Thanks !
