### ISSUE TITLE
The button to merge the code can be double-clicked

### ISSUE THREAD

**Issue by ffbh123456** [go-gitea/gitea#14242]
When I quickly click the button for merging code multiple times, the webpage will get 404. I suggest that this button can refer to GitHub button, and it can only be clicked once. When I click this button, the button will change to another color and this button is not clickable
![image](https://user-images.githubusercontent.com/20750357/103534796-8bc16600-4eca-11eb-972c-b757ab021403.png)

**Comment by lunny** [comment]
Not only this button ...

**Comment by ZhouJiaZhi** [comment]
@lunny 
Yes, this seems to be a lot of work, are you planning to fix this recently?

**Comment by wxiaoguang** [comment]
Duplicate of

* https://github.com/go-gitea/gitea/issues/17111 (with more details)

Unfortunately, no ideal plan to fix it yet ....
