### ISSUE TITLE
 CLI usage docs appear to be wrong

### ISSUE THREAD

**Issue by rscmbbng** [go-gitea/gitea#14249]
- Gitea version (or commit ref): 1.13.1
- Git version: 2.20.1
- Operating system: Debian Stable

Gitea installed via binary as per instructions on the docs

- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] MSSQL
  - [ x ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ x ] No
- Log gist:

```
root@server:~# which gitea
/usr/local/bin/gitea
root@server:~# `which gitea` --version
Gitea version 1.13.1 built with GNU Make 4.1, go1.15.6 : bindata, sqlite, sqlite_unlock_notify
root@server:~# gitea admin user 
No help topic for 'user'
root@server:~# gitea admin user list
No help topic for 'user'
root@server:~# gitea admin --config '/etc/gitea/app.ini' user list
No help topic for 'user'
root@server:~# gitea admin --help
NAME:
   Gitea admin - Command line interface to perform common administrative operations

USAGE:
   Gitea admin command [command options] [arguments...]

COMMANDS:
     create-user         Create a new user in database
     change-password     Change a user's password
     repo-sync-releases  Synchronize repository releases with tags
     regenerate          Regenerate specific files
     auth                Modify external auth providers

OPTIONS:
   --custom-path value, -C value  Custom path file path (default: "/usr/local/bin/custom")
   --config value, -c value       Custom configuration file path (default: "/usr/local/bin/custom/conf/app.ini")
   --version, -v                  print the version
   --work-path value, -w value    Set the gitea working path (default: "/usr/local/bin")
   --help, -h                     show help
   

DEFAULT CONFIGURATION:
     CustomPath:  /usr/local/bin/custom 
     CustomConf:  /usr/local/bin/custom/conf/app.ini
     AppPath:     /usr/local/bin/gitea
     AppWorkPath: /usr/local/bin
```

## Description

Hi, first thanks for your work on this great software!

Like #13859 I was looking to list all users via the CLI, which (according to the [docs](https://docs.gitea.io/en-us/command-line/#admin) ), should be done with `gitea admin user list`. However, when I do that, I get `No help topic for 'user'`. See logs above.

However, I am running version 1.13.1 which is the version that the documentation is about so I believe either the CLI docs are wrong or 1.13.1 is not working as intended. 

thanks!

**Comment by bagasme** [comment]
@rscmbbng the docs is for master

**Comment by rscmbbng** [comment]
This is not obvious as the docs do instruct to install particular releases: e.g. https://docs.gitea.io/en-us/install-from-binary/#download

However, I now understand that this feature will only be part of [1.14 release](https://github.com/go-gitea/gitea/milestone/76?closed=1)

**Comment by lunny** [comment]
@rscmbbng Thanks! I think we should have a versioned document.
I'll close this one, please feel free to reopen it.
