### ISSUE TITLE
orgmode support

### ISSUE THREAD

**Issue by 098uhfhgrdgh** [go-gitea/gitea#1424]
Add support for org mode. [See this discussion](https://notabug.org/hp/gogs/issues/18)

**Comment by strk** [comment]
From the external discussion, formal specs are here:
http://orgmode.org/worg/dev/org-syntax.html

This is about handling .org files, basically

**Comment by strk** [comment]
Unknwon made some progress on this: https://github.com/gogits/gogs/issues/4373 which is blocked on an external library bug

**Comment by lunny** [comment]
Oh. It's a duplicated issue to #1272
