### ISSUE TITLE
List of repos (via API) an other user has access to

### ISSUE THREAD

**Issue by jk-inazczech** [go-gitea/gitea#14257]
- Gitea version (or commit ref): 1.13.1
- Git version: not relevant
- Operating system: Windows 2008 R2
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL): https://try.gitea.io/api/v1/users/111aaaqqq/repos
  - [ ] No
- Log gist:

## Description

I'm a global admin on my installation of Gitea and I need to generate a report of permissions by API for a specific user.

However, the API method `users/{username}/repos` does not list user's repositories where the user has access to, even with my token. It returns HTTP 200 with empty JSON array `[]`. My guess is that the user is collaborator or team member in repositories, not their owner, and this method ignores it. However, there is no other way how to retrieve such info.

Above try.gitea.io URL does not list my repository (https://try.gitea.io/jk-nilo/PerformanceApi) to which I give the user a write access.

Thank you

**Comment by 6543** [comment]
`users/{username}/repos` only list the repos a user own ...

@jk-nilo a working solution would be the https://try.gitea.io/api/swagger#/user/userCurrentListRepos with sudo header
this is a privacy feature ... :point_up: only admins can use sudo header ;)

**Comment by jk-nilo** [comment]
Thanks for pointing about "sudo header" what is it for :)

For others, in docs, https://docs.gitea.io/en-us/api-usage/#sudo
