### ISSUE TITLE
Markdown: Anchor links are cut off by container

### ISSUE THREAD

**Issue by j2L4e** [go-gitea/gitea#14255]
- Gitea version (or commit ref): 4ef5f17

## Description
Auto-generated anchor-links for headings are cut off as the container (`.render-content.markdown`) has `overflow: hidden;`

https://try.gitea.io/abhishek-8/testing/issues/1

## Screenshots
![image](https://user-images.githubusercontent.com/13417122/103657105-c3331f80-4f69-11eb-8c7d-be4563fcfc5d.png)

**Comment by wxiaoguang** [comment]
It seems no problem now

![image](https://user-images.githubusercontent.com/2114189/234658203-212517d3-c643-421e-8db6-43ce7ccd36d5.png)
