### ISSUE TITLE
Change to CHI misses some updates required for windows

### ISSUE THREAD

**Issue by blazecoding2009** [go-gitea/gitea#14259]
- Gitea version (or commit ref): latest
- Git version:
- Operating system: Windows
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X ] No
- Log gist:

## Description

Got this error when I run go run main.go

```C:\Users\arnna\Desktop\CodeShare\App>go run main.go
# code.gitea.io/gitea/modules/auth/sso
modules\auth\sso\sspi_windows.go:69:27: undefined: ctx
modules\auth\sso\sspi_windows.go:79:56: undefined: ctx
modules\auth\sso\sspi_windows.go:82:37: undefined: ctx
modules\auth\sso\sspi_windows.go:87:15: undefined: ctx
modules\auth\sso\sspi_windows.go:88:3: undefined: ctx
modules\auth\sso\sspi_windows.go:89:3: undefined: ctx
modules\auth\sso\sspi_windows.go:90:3: undefined: ctx
modules\auth\sso\sspi_windows.go:94:37: undefined: ctx
modules\auth\sso\sspi_windows.go:113:24: too many arguments in call to s.newUser
modules\auth\sso\sspi_windows.go:113:25: undefined: ctx
modules\auth\sso\sspi_windows.go:113:24: too many errors```
## Screenshots

<!-- **If this issue involves the Web Interface, please include a screenshot** -->

**Comment by techknowlogick** [comment]
My recent PR https://github.com/go-gitea/gitea/pull/14260 won't resolve this, however it'll catch similar issues in the future, and it successfully replicates this issue which is a good test that the PR is good to have.
