### ISSUE TITLE
Add a character count or visible warning to repo descriptions

### ISSUE THREAD

**Issue by cooperg2001** [go-gitea/gitea#14251]
- Gitea version (or commit ref): 1.13.1
- Git version: N/A
- Operating system: N/A

## Description
When entering a description for a repository a user may not know of the 255 character limit until after attempting to save their description. If a description exceeds 255 characters it is cleared when the user attempts to save. A character count should be added (or a visible warning of the limit) to the web interface to avoid having users retype descriptions if they forget or do not know of this limit. Potentially for long descriptions the warning could advise users to put information in the repo README instead.

## Screenshots
Example of proposed change on Imgur: https://imgur.com/a/y5NcnGS

**Comment by kins-dev** [comment]
While a UI would be nice, I'm curious why there is a limit at all.

Is there a reason that this field is limited, or why the count is so low?

I was able to remove this limit in a test build with no ill effects for SQLite3.  I don't think any of the other DB types would care either.

**Comment by kins-dev** [comment]
I removed all the limits from my test instance and it has been great.  Given Jenkins pulls the repo description over automatically, (pipelines based on an organization) it gives me one version of the truth over multiple systems.

I don't mind if this is configurable as long as no limit is an option.

**Comment by fnetX** [comment]
Just reported on [Codeberg](https://codeberg.org/Codeberg/Community/issues/470)

I just confirmed on try.gitea.io this also affects other input boxes (e.g. name), so an improvement should take care of all the input boxes there.

Also, I noticed that spellcheck is disabled, does anyone know why this is explicitly set?

**Comment by fnetX** [comment]
Does anyone know a place in the Gitea Codebase where such a limit is already in place so that this could be copied / adapted? I just tried to adapt the checker on the repo tag code, but didn't get it to work. I'm also not really a frontend guy, but if pointed to some good resources I might be able to pick this up.

**Comment by CypherpunkSamurai** [comment]
Searching the Repository for [MaxSize](https://github.com/go-gitea/gitea/search?q=%3BMaxSize) reveals that there's a handful of cases.

Are we planning to replace the UI with JS validation for all these cases, or just the repository setting related UI?

**Comment by delvh** [comment]
1. See #21119 and the subsequent #21194
2. Isn't that issue now implemented by using the browser native restriction?
