### ISSUE TITLE
upgrading gitea from 1.12.3 to 1.13.1

### ISSUE THREAD

**Issue by thisisusernameforgit** [go-gitea/gitea#14253]
- Gitea version (or commit ref):
- Git version: 1.12.3
- Operating system: Centos 7
- Database:
  - [x] PostgreSQL

## Description

Hello!

tried to upgrade from gitea 1.12.3 to 1.13.1 according to the official documentation. updated immediately from 1.12.3 to 1.13. version. but after updating I get 502 http error code when accessing mygiteadomain.com home page

in the gitea logs iI see messages:

2021/01/04 19:39:35 ... ations/migrations.go: 538: recreateTable () [E] Unable to rename IDX_topic_updated_unix to IDX_topic_updated_unix. Error: pq: relationship "IDX_topic_updated_unix" does not exist

2021/01/04 19:39:35 ... ations/migrations.go: 382: recreateTable () [E] Unable to create table tmp_recreate__repo_topic. Error: pq: current transaction aborted, commands until the end of the transaction block are ignored

2021/01/04 19:39:35 routers/init.go: 88: initDBEngine () [E] ORM engine initialization attempt # 9/10 failed. Error: migrate: do migrate: pq: Could not complete operation in a failed transaction

I have another gitea build with similar settings and characteristics. on this assembly from version 1.12.3 to 1.13.1 I updated without problems

What can be wrong?

**Comment by 6543** [comment]
@graceastrid do you have a backup of the state before upgrading? (1.12.3)

**Comment by graceastrid** [comment]
> @graceastrid do you have a backup of the state before upgrading? (1.12.3)

Yes, i have

**Comment by 6543** [comment]
1. ok switch back to that state
2. upgrade to 1.12.6
3. run ./gitea doctor --all --fix --config <your-config>

**Comment by 6543** [comment]
backup this state & try migration again

**Comment by graceastrid** [comment]
> backup this state & try migration again

thank you for your advice!

1.I have successfully updated to version 1.12.6 and then did ./gitea doctor --all --fix --config and no errors were found
2. then I updated to 1.13.1 and my gitea doesn't work again.
did ./gitea doctor --all --fix --config
and in the end I get:

[2] Check Database Version
- WARN: Got Error migrate: Current database version 150 is not equal to the expected version 156. Please run "gitea [--config /path/to/app.ini] migrate" to update the database version during ensure up to date
- Attempting to migrate to the latest DB version to fix this.
Error: migrate: do migrate: pq: Could not complete operation in a failed transaction

[3] Check consistency of database
Error: model version on the database does not match the current Gitea version. Model consistency will not be checked until the database is upgraded

[4] Check if OpenSSH authorized_keys file is up-to-date
OK.

[5] Check if SCRIPT_TYPE is available
- ScriptType bash is on the current PATH at / bin / bash
OK.

[6] Check if hook files are up-to-date and executable
Error: pq: column "trust_model" does not exist

[7] Recalculate merge bases
- 0 PR mergebases updated of 0 PRs total in 0 repos
Error: pq: column "trust_model" does not exist

[8] Recalculate Stars number for all user
OK.

[9] Enable push options
- Enabled push options for 0 repositories.
Error: pq: column "trust_model" does not exist

**Comment by zeripath** [comment]
try to do gitea migrate again but you need to give us the first error. You've only given us the 9th error which is likely different & unhelpful.

**Comment by graceastrid** [comment]
> try to do gitea migrate again but you need to give us the first error. You've only given us the 9th error which is likely different & unhelpful.

Hi! the first error is OK

```
[root @ git gitea] # ./gitea doctor --all --fix -c /opt/gitea/custom/conf/app.ini
[1] Check paths and basic configuration
- Configuration File Path: '/opt/gitea/custom/conf/app.ini'
- Repository Root Path: '/mnt/git/users'
- Data Root Path: 'data'
- Custom File Root Path: '/opt/gitea/custom'
- Work directory: '/opt/gitea'
- Log Root Path: '/var/log/gitea'
OK.

[2] Check Database Version
- WARN: Got Error migrate: Current database version 150 is not equal to the expected version 156. Please run "gitea [--config /path/to/app.ini] migrate" to update the database version during ensure up to date
- Attempting to migrate to the latest DB version to fix this.
Error: migrate: do migrate: pq: Could not complete operation in a failed transaction

[3] Check consistency of database
Error: model version on the database does not match the current Gitea version. Model consistency will not be checked until the database is upgraded

[4] Check if OpenSSH authorized_keys file is up-to-date
OK.

[5] Check if SCRIPT_TYPE is available
- ScriptType bash is on the current PATH at /bin/bash
OK.

[6] Check if hook files are up-to-date and executable
Error: pq: column "trust_model" does not exist

[7] Recalculate merge bases
- 0 PR mergebases updated of 0 PRs total in 0 repos
Error: pq: column "trust_model" does not exist

[8] Recalculate Stars number for all user
OK.

[9] Enable push options
- Enabled push options for 0 repositories.
Error: pq: column "trust_model" does not exist
```

**Comment by 6543** [comment]
looks like migration of #12639 is the problem?

**Comment by 6543** [comment]
before manually altering the db to fix ... you could try to compile gitea 4f8dad37f834833012004bf5b158e5129af4b610 migrate to it
and use  `./gitea doctor recreate-table topic` before migrating to v1.13.1 ...

**Comment by graceastrid** [comment]
> before manually altering the db to fix ... you could try to compile gitea 4f8dad37f834833012004bf5b158e5129af4b610 migrate to it
> 
> and use  `./gitea doctor recreate-table topic` before migrating to v1.13.1 ...

I'm sorry, but I don't quite understand what I need to do now, maybe I don't have enough experience and knowledge.  Could you describe in more detail what I should do and what commands to enter to solve the problem?

**Comment by techknowlogick** [comment]
> I don't have enough experience and knowledge.

That's ok. We are happy to help!

What @6543 is asking for is if you could build Gitea (docs on how to do that here: https://docs.gitea.io/en-us/install-from-source/ ) for a specific commit, use that binary and migrate your database use the [CLI migrate command ](https://docs.gitea.io/en-us/command-line/#migrate), and attempt to use the doctor to recreate a specific table, then migrate to 1.13.1.

If you have any issues/questions with the above, please hop into our chatroom where there will be someone who can help.

**Comment by zeripath** [comment]
And what I was suggesting was to try to run gitea 1.13.1 again but this time actually give us all of the output not just the ninth error that was reported. The first error is the most important and helpful for figuring out what the problem is.

**Comment by graceastrid** [comment]
> And what I was suggesting was to try to run gitea 1.13.1 again but this time actually give us all of the output not just the ninth error that was reported. The first error is the most important and helpful for figuring out what the problem is.

i tried running 1.13.1 over and over again but the errors are still the same.

```
./gitea doctor --all --fix -c /opt/gitea/custom/conf/app.ini

[1] Check paths and basic configuration
- Configuration File Path: '/opt/gitea/custom/conf/app.ini'
- Repository Root Path: '/mnt/git/users'
- Data Root Path: 'data'
- Custom File Root Path: '/opt/gitea/custom'
- Work directory: '/opt/gitea'
- Log Root Path: '/var/log/gitea'
OK.

[2] Check Database Version
- WARN: Got Error migrate: Current database version 150 is not equal to the expected version 156. Please run "gitea [--config /path/to/app.ini] migrate" to update the database version during ensure up to date
- Attempting to migrate to the latest DB version to fix this.
Error: migrate: do migrate: pq: Could not complete operation in a failed transaction

[3] Check consistency of database
Error: model version on the database does not match the current Gitea version. Model consistency will not be checked until the database is upgraded

[4] Check if OpenSSH authorized_keys file is up-to-date
OK.

[5] Check if SCRIPT_TYPE is available
- ScriptType bash is on the current PATH at /bin/bash
OK.

[6] Check if hook files are up-to-date and executable
Error: pq: column "trust_model" does not exist

[7] Recalculate merge bases
- 0 PR mergebases updated of 0 PRs total in 0 repos
Error: pq: column "trust_model" does not exist

[8] Recalculate Stars number for all user
OK.

[9] Enable push options
- Enabled push options for 0 repositories.
Error: pq: column "trust_model" does not exist
```

**Comment by lunny** [comment]
Once you downgrade, you have to change your version from 156 to 150 manually and then run gitea again.

**Comment by graceastrid** [comment]
> Once you downgrade, you have to change your version from 156 to 150 manually and then run gitea again.

yes, i did it and now i run gitea on 1.12.6...

**Comment by zeripath** [comment]
@graceastrid You keep posting the same unhelpful logs without the underlying error that causes the migration to fail. When I said run gitea 1.13.1 again - I did not mean run `gitea doctor` again I meant `gitea web`.

If we are to have any chance to help you we need to see the logs from what happens when the migration is attempted. 

These logs:

```
2021/01/04 19:39:35 ... ations/migrations.go: 538: recreateTable () [E] Unable to rename IDX_topic_updated_unix to IDX_topic_updated_unix. Error: pq: relationship "IDX_topic_updated_unix" does not exist

2021/01/04 19:39:35 ... ations/migrations.go: 382: recreateTable () [E] Unable to create table tmp_recreate__repo_topic. Error: pq: current transaction aborted, commands until the end of the transaction block are ignored

2021/01/04 19:39:35 routers/init.go: 88: initDBEngine () [E] ORM engine initialization attempt # 9/10 failed. Error: migrate: do migrate: pq: Could not complete operation in a failed transaction
```

are from the 9th attempt - and it is too late for us to figure out what the problem.

We need the first error - not the 9th.

**Comment by graceastrid** [comment]
> @graceastrid You keep posting the same unhelpful logs without the underlying error that causes the migration to fail. When I said run gitea 1.13.1 again - I did not mean run `gitea doctor` again I meant `gitea web`.
> 
> If we are to have any chance to help you we need to see the logs from what happens when the migration is attempted.
> 
> These logs:
> 
> ```
> 2021/01/04 19:39:35 ... ations/migrations.go: 538: recreateTable () [E] Unable to rename IDX_topic_updated_unix to IDX_topic_updated_unix. Error: pq: relationship "IDX_topic_updated_unix" does not exist
> 
> 2021/01/04 19:39:35 ... ations/migrations.go: 382: recreateTable () [E] Unable to create table tmp_recreate__repo_topic. Error: pq: current transaction aborted, commands until the end of the transaction block are ignored
> 
> 2021/01/04 19:39:35 routers/init.go: 88: initDBEngine () [E] ORM engine initialization attempt # 9/10 failed. Error: migrate: do migrate: pq: Could not complete operation in a failed transaction
> ```
> 
> are from the 9th attempt - and it is too late for us to figure out what the problem.
> 
> We need the first error - not the 9th.

sorry to misunderstand you

here are the logs that are needed

```
2021/01/05 20:55:04 routers/init.go:89:initDBEngine() [I] Backing off for 3 seconds
2021/01/05 20:55:07 routers/init.go:82:initDBEngine() [I] ORM engine initialization attempt #2/10...
2021/01/05 20:55:07 ...rm/session_schema.go:25:Ping() [I] PING DATABASE postgres
2021/01/05 20:55:07 ...m.io/xorm/core/db.go:286:afterProcess() [I] [SQL] SELECT tablename FROM pg_tables WHERE schemaname = $1 AND tablename = $2 [public version] - 2.855425ms
2021/01/05 20:55:07 ...m.io/xorm/core/db.go:286:afterProcess() [I] [SQL] SELECT column_name FROM INFORMATION_SCHEMA.COLUMNS WHERE table_schema = $1 AND table_name = $2 AND column_name = $3 [public version id] - 7.9738ms
2021/01/05 20:55:07 ...m.io/xorm/core/db.go:286:afterProcess() [I] [SQL] SELECT column_name FROM INFORMATION_SCHEMA.COLUMNS WHERE table_schema = $1 AND table_name = $2 AND column_name = $3 [public version version] - 3.943865ms
2021/01/05 20:55:07 ...m.io/xorm/core/db.go:286:afterProcess() [I] [SQL] SELECT "id", "version" FROM "version" WHERE "id"=$1 LIMIT 1 [1] - 1.087614ms
2021/01/05 20:55:07 ...ations/migrations.go:336:Migrate() [I] Migration[150]: add primary key to repo_topic
2021/01/05 20:55:07 ...m.io/xorm/core/db.go:286:afterProcess() [I] [SQL] BEGIN TRANSACTION [] - 310.234µs
2021/01/05 20:55:07 ...m.io/xorm/core/db.go:286:afterProcess() [I] [SQL] CREATE TABLE IF NOT EXISTS "tmp_recreate__topic" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "name" VARCHAR(25) NULL, "repo_count" INTEGER NULL, "created_unix" BIGINT NULL, "updated_unix" BIGINT NULL) [] - 23.10632ms
2021/01/05 20:55:07 ...m.io/xorm/core/db.go:286:afterProcess() [I] [SQL] CREATE UNIQUE INDEX "UQE_tmp_recreate__topic_name" ON "tmp_recreate__topic" ("name") [] - 15.275118ms
2021/01/05 20:55:07 ...m.io/xorm/core/db.go:286:afterProcess() [I] [SQL] CREATE INDEX "IDX_tmp_recreate__topic_created_unix" ON "tmp_recreate__topic" ("created_unix") [] - 23.4495ms
2021/01/05 20:55:07 ...m.io/xorm/core/db.go:286:afterProcess() [I] [SQL] CREATE INDEX "IDX_tmp_recreate__topic_updated_unix" ON "tmp_recreate__topic" ("updated_unix") [] - 17.017881ms
2021/01/05 20:55:07 ...m.io/xorm/core/db.go:286:afterProcess() [I] [SQL] INSERT INTO "tmp_recreate__topic" ("id", "name", "repo_count", "created_unix", "updated_unix") SELECT "id", "name", "repo_count", "created_unix", "updated_unix" FROM "topic" [] - 760.532µs
2021/01/05 20:55:07 ...m.io/xorm/core/db.go:286:afterProcess() [I] [SQL] DROP TABLE "topic" CASCADE [] - 1.745819ms
2021/01/05 20:55:07 ...m.io/xorm/core/db.go:286:afterProcess() [I] [SQL] ALTER TABLE "tmp_recreate__topic" RENAME TO "topic" [] - 447.787µs
2021/01/05 20:55:07 ...m.io/xorm/core/db.go:286:afterProcess() [I] [SQL] SELECT "indexname" FROM "pg_indexes" WHERE (tablename = $1 ) [topic] - 1.911095ms
2021/01/05 20:55:07 ...m.io/xorm/core/db.go:286:afterProcess() [I] [SQL] ALTER INDEX "IDX_topic_updated_unix" RENAME TO "IDX_topic_updated_unix" [] - 46.959884ms
2021/01/05 20:55:07 ...ations/migrations.go:538:recreateTable() [E] Unable to rename IDX_topic_updated_unix to IDX_topic_updated_unix. Error: pq: relationship "IDX_topic_updated_unix" does not exist
2021/01/05 20:55:07 ...m.io/xorm/core/db.go:286:afterProcess() [I] [SQL] CREATE TABLE IF NOT EXISTS "tmp_recreate__repo_topic" ("repo_id" BIGINT NOT NULL, "topic_id" BIGINT NOT NULL, PRIMARY KEY ( "repo_id","topic_id" )) [] - 489.304µs
2021/01/05 20:55:07 ...ations/migrations.go:382:recreateTable() [E] Unable to create table tmp_recreate__repo_topic. Error: pq: тthe current transaction is aborted, commands until the end of the transaction block are ignored
2021/01/05 20:55:07 ...m.io/xorm/core/db.go:286:afterProcess() [I] [SQL] COMMIT [] - 192.699µs
2021/01/05 20:55:07 routers/init.go:88:initDBEngine() [E] ORM engine initialization attempt #2/10 failed. Error: migrate: do migrate: pq: Could not complete operation in a failed transaction
2021/01/05 20:55:07 routers/init.go:89:initDBEngine() [I] Backing off for 3 seconds
```

**Comment by 6543** [comment]
@graceastrid this is the second atempt, the first one would be nice :)

**Comment by zeripath** [comment]
OK assuming that the first error is the same. I think there's something odd going on with recreate table here.

`DROP TABLE "topic" CASCADE` should cause all of the indices on topic to be dropped.

As we can see above all of the indices on the temporary table are created properly with the appropriate prefix and when the table is renamed with `ALTER TABLE "tmp_recreate__topic" RENAME TO "topic" ` its indices should not be renamed along with it.

So why is `SELECT "indexname" FROM "pg_indexes" WHERE (tablename = $1 ) [topic] ` detecting an index with name `IDX_topic_updated_unix` already?

Is the cascade index drop failing for some reason? - I guess it's possible if they were in a different schema? Is that possible @graceastrid ?

Are the indices automatically renaming with the table name change? Do you have some option set?

Now, how to ameliorate? If we look at:

https://github.com/go-gitea/gitea/blob/872d3088920f8da2070f497f40d89d35fff9679f/models/migrations/migrations.go#L562-L574

we could skip any rename to itself here - but perhaps we need to check what has been detected. It's all a bit weird.

**Comment by mimic-jz** [comment]
I have a similar issue. Upgraded from 1.12.1 all the way up to 1.12.6, then 1.13.0 - did not help.
Log for the migration from 1.12.6 to 1.13.0:
[gitea-upgrade.log](https://github.com/go-gitea/gitea/files/5947126/gitea-upgrade.log)
