### ISSUE TITLE
Gitea shows html tags in diff with quotes

### ISSUE THREAD

**Issue by lakostin** [go-gitea/gitea#14269]
- Gitea version (or commit ref):
1.14.0+dev-514-gd2ee1221c
- Git version:
2.26.2
- Operating system:
docker Alpine Linux v3.12
- Database (use `[x]`):
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
- Log gist:

## Description
Only quotes were added in commit. Gitea shows also html tags in diff.
...

## Screenshots
gitea diff:
![Screenshot from 2021-01-06 14-29-47](https://user-images.githubusercontent.com/29179059/103764160-00f87c80-502c-11eb-8678-89bf2ef724bd.png)

git diff:
![Screenshot from 2021-01-06 14-31-00](https://user-images.githubusercontent.com/29179059/103764166-03f36d00-502c-11eb-9d9c-2ad57dfb435b.png)

**Comment by zeripath** [comment]
Related #14321

**Comment by noerw** [comment]
zeripath meant #14231. I'll close this as duplicate
