### ISSUE TITLE
Can I update the wiki using git?

### ISSUE THREAD

**Issue by martinellison** [go-gitea/gitea#1426]
(This is a support question; usually I ask support questions on a forum but gitea does not appear to have a forum; apologies then if this is the wrong place, but please advise the correct place and update the documentation).

Can I update the wiki by cloning the wiki repository, adding pages and pushing the changes back? Will it cause any problems if I do so?

**Comment by Fastidious** [comment]
@martinellison I do not think cloning (or forking) a repository clones the wiki. You can keep all documentation within a repository, as if it were a wiki. That way it will work.

**Comment by typeless** [comment]
Wiki is stored at a companying repository besides the normal repository. For example, if you have a repository called Foo, the git directory of the repository is called Foo.git, and the wiki's repository would be called Foo.wiki.git (IIRC). So you can use git to access the wiki if you're using SSH. Not sure about HTTP though.

**Comment by lunny** [comment]
@martinellison @typeless You can both SSH and HTTP(S) like @typeless said.. If you cannot, please fire an issue.

**Comment by martinellison** [comment]
Thanks for the responses so far @typeless @lunny @Fastidious. So far, I have cloned the wiki repo for my repo. I would like to know if gitea keeps any data about the wiki (e.g. in the database) that could be corrupted (or not updated properly) if I update the wiki through my wiki repo clone. Actually, I want to copy some pages from an old repo's wiki to a new repo's wiki, and of course that is easiest to do using wiki repo clones and bash `cp`. But I don't want to cause any problems.

**Comment by lunny** [comment]
You can clone/push/pull the wiki like a normal git repo but only `*.md` files on the root dir.

**Comment by martinellison** [comment]
@lunny ok thanks
