### ISSUE TITLE
Internal server error when elastic is not available

### ISSUE THREAD

**Issue by lafriks** [go-gitea/gitea#14275]
Currently if code and issues are indexed to elastic and elasticsearch server is not available it should:
* [ ] pause indexers (code and issue) and keep not indexed items in queue until elastic is again available otherwise index get's out of sync with database/code
* [ ] not show 500 error when searching but some more user readable error about functionality currently not available

**Comment by wxiaoguang** [comment]
I guess it should have been fixed. The newly written queue can push the failed items back to the queue.
