### ISSUE TITLE
2FA issues in dev version

### ISSUE THREAD

**Issue by binfalse** [go-gitea/gitea#14271]
- Gitea version (or commit ref): 1.14.0+dev-514-gd2ee1221c (Docker `:latest`)
- Git version: irrelevant I guess
- Operating system: Dockerized installation
  
  
  
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (at least is gives me a 500 as well)
  - [ ] No
- Log gist: https://gist.github.com/binfalse/2ca6706fb1244545649f218af1c6bce2

## Description

2FA seems to be broken in the current dev version.

I've had 2FA enabled and couldn't log in anymore after I updated the Docker image. After some debugging I disabled 2FA for my account (by deleting the corresponding line in the `two_factor` table) and was able to login again. (Actually, I needed to clean cookies as well, as it was then asking me for a scratch code...)

When trying to re-enable 2FA I get a 500 at the frontend (I can reproduce that at https://try.gitea.io -- at least I'll get a 500 as well if I try to setup 2FA there). The logs show

    [E] PANIC: interface conversion: interface {} is nil, not string

see: https://gist.github.com/binfalse/2ca6706fb1244545649f218af1c6bce2  -- please note:
* I replaced sensitive information with placeholders
* even though I set `COLORIZE  = false` the messages are apparently still colorized.. not sure what's going wrong there...? Just ignore the `#011` commands..
* logs went through rsyslog -> extra syslog prefixes, see https://binfalse.de/2018/02/21/logging-with-docker/

To me it looks like there is an issue with 2FA...? Let me know if you need further information or if I can do anything else to debug the issue! :)

## Screenshots
Web interface just shows a 500..

**Comment by techknowlogick** [comment]
The specific line that is erroring is https://github.com/go-gitea/gitea/blob/master/routers/user/setting/security_twofa.go#L192

**Comment by 6543** [comment]
@binfalse can you use `memory` instead of file to fix it until it is fixed on master?

https://docs.gitea.io/en-us/config-cheat-sheet/#session-session

**Comment by 6543** [comment]
fix: #14287

**Comment by binfalse** [comment]
sure! thanks for the quick response!

you're doing great and important work guys!! :)
