### ISSUE TITLE
Setting a User as "Restricted User" via API is missing.

### ISSUE THREAD

**Issue by bwiethof** [go-gitea/gitea#14276]
- Gitea version (or commit ref): 1.13.0
- Git version:
- Operating system:
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
- Log gist:

## Description
Setting a User as "Restricted User" is only possible via Web Interface not via API.

**Comment by 6543** [comment]
#14630 is a nice example how to extend api with a field to expose info and to edit info
