### ISSUE TITLE
Template files/directories with customisable names

### ISSUE THREAD

**Issue by clarfonthey** [go-gitea/gitea#14273]
## Description

Right now, template variables are only expanded within file contents. It would be nice to be able to also expand them inside file names. One potential use case for this is to create a `$REPO_NAME` directory for storing a template Python module with the same name as the repository.

One potential issue with directly allowing variables in file names is that this could potentially induce non-determinant behaviour depending on the order in which the files are renamed. We could simply error if renaming a file results in overwriting another file, however.

**Comment by bilderbuchi** [comment]
This would indeed be a very useful feature, [cookiecutter](https://cookiecutter.readthedocs.io/en/1.7.3/first_steps.html) can also do that, and is probably the reference solution for Python project templates.

**Comment by ddi-acassidy** [comment]
An alternate route could be a gitea actions trigger for when a template is uses. That would allow for completely customizable behavior when using templates

**Comment by bilderbuchi** [comment]
https://github.com/go-gitea/gitea/pull/25294 adds this to Gitea 1.21.0, so it should be possible to implement this now.
