### ISSUE TITLE
Add more info about project management to CONTRIBUTING.md

### ISSUE THREAD

**Issue by strk** [go-gitea/gitea#1427]
The `CONTRIBUTING.md` file only partially describe the project management policy:
 - it doesn't mention who has merge powers and how such powers are obtained
 - it does not say that maintainers have veto powers on pull requests ("requested change" effectively gives veto powers at the moment)
 - it doesn't describe any way to deal with stale PRs/issues or inactive maintainers (minor issue at this moment, but still useful to have)

**Comment by bkcsoft** [comment]
Anyone can use "request change" AFAIK, if not everyone _should_ have that.

As for stale PRs/issues, anyone can pro-actively ask for feedback, if nothing is done for a month I propose closing it. Reporter/Contributor can re-open if the become active again. (Not documented, only proposed, should be documented if agreed opon)

**Comment by strk** [comment]
On Tue, Apr 18, 2017 at 12:20:08AM -0700, bkcsoft wrote:
> Anyone can use "request change" AFAIK, if not everyone _should_ have that.

You mean any *maintainer*, right ?
While I agree it's important that anyone can request changes, making it
easy to raise a barrier would basically let a minority block what the
majority would agree to instead merge.
How can a change request be set off by others ?

> As for stale PRs/issues, anyone can pro-actively ask for feedback, if nothing is done for a month I propose closing it. Reporter/Contributor can re-open if the become active again. (Not documented, only proposed, should be documented if agreed opon)

I agree on automatically closing after a period of silence from the
proponent (which we need to allow changing over time). Maybe the period
could be 2 weeks too, but I'm ok with 1 month if that helps reaching
an agreement sooner.

**Comment by bkcsoft** [comment]
> You mean any *maintainer*, right ?

Haven't looked into the permissions, but IMO yes, any *maintainer*.

> would let a minority block what the majority would agree to instead merge.

This is where it gets tricky, what if the minority block is correct in blocking it? (see my Status-API PR for example where I'm using `TEXT INDEX` which isn't possible on MySQL). Once the PR has been updated to fix the issue any Owner can simply reject the request if the requester doesn't approve it themselfs.

**Comment by lunny** [comment]
@strk is this still an issue?
