### ISSUE TITLE
Migration: Make migration script tolerant of pre-existing indexes

### ISSUE THREAD

**Issue by sbrl** [go-gitea/gitea#1428]
As per the conversation on gitter, the migration script should not error out if the index `IDX_repo_unit_S` or `IDX_repo_unit_created_unix` already exists. Here's an error I get during the migration process:

```
2017/04/01 11:31:11 [...itea/routers/init.go:54 GlobalInit()] [E] Failed to initialize ORM engine: migrate: do migrate: CreateIndexes RepoUnit: index IDX_repo_unit_S already exists
```

**Gogs version:** 0.10.1.0228

**Comment by strk** [comment]
@lunny is there any way to check if an index exist via XORM ?

**Comment by tboerger** [comment]
I think this will be fixed with 1.1.1

**Comment by strk** [comment]
@tboerger you mean it's already fixed in 1.1 branch or do you know of a work in progress ? In either case, do you have links ?

**Comment by sbrl** [comment]
I'm using GItea 1.1.0, so I don't think it's fixed in the 1.1.x branch.

**Comment by strk** [comment]
`release/v1.1` branch is 9 commits ahead of `1.1.0`

**Comment by sbrl** [comment]
@lunny What's this a duplicate of?
