### ISSUE TITLE
Adopt repository case errors

### ISSUE THREAD

**Issue by LukeMauldin** [go-gitea/gitea#14281]
- Gitea version (or commit ref): 1.13.0 - downloaded from Github release, running via systemd
- Git version: 2.27
- Operating system: RHEL 8.3
- Database (use `[x]`):
  - [ X ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ X ] No

## Description
When using the Adopt repository functionality I have run into 2 bugs.
1) When the repository name is mixed case, it does not show up on the "Adopt Repositories" web page and it will not work via the API. Example: If the repository is named: `/var/lib/gitea/repos/archive/TestRepo/`, it will not show up on the web page and not work via the API.  If the repository is named `/var/lib/gitea/repos/archive/testrepo/`then the adoption functionality will work as expected.  A work-around is to name the repository as lower-case for the import and then do an API call to update the name to mixed case.
2) When the organization name is mixed case, it does show up on the "Adopt Repositories" web page but the Adopt fails without an error and refreshes the screen.  Also, it will not work via the API.  Example: If the repository is named `/var/lib/gitea/repos/Archive/testrepo/`, it will show up on the web page but the Adopt will not work and the API will not work.  There is no practical work-around for this issue except to have all organizations named lower case but that would break other applications that depend on the correct casing.

**Comment by zeripath** [comment]
That is because Gitea does not and will not create repositories with capitals in their folder names.

**Comment by zeripath** [comment]
And the repo is suppose to be a bare repo like testrepo.git

**Comment by zeripath** [comment]
Gitea's repos are meant to be Gitea's alone - it is not intended that other applications are to be allowed to use its repos without deep understanding of how Gitea uses its repos.

**Comment by LukeMauldin** [comment]
By using lower case organization and repository names I was able to work around the errors I was getting previously.
