### ISSUE TITLE
Migration of my project doesn't stop anymore.

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#14289]
Hi there,
here is my account: https://forge.chapril.org/miamondo/labortablo.

I am trying to migrate some files and repos from gitlab, but the "cup of tea" is loading, loading and loading, perhaps until the end of the world. So, I wanted to close my account but I am told to close my projects before. The problem is that I can't close my project because it is loading... So, I am in a sort of loop. 
Can anyone help me? Thanks
Benoît

**Comment by zeripath** [comment]
1. We do not run forge.chapril.org - you should contact their admins in the first instance not the gitea devs.
2. Clicking on the provided link shows an upturned cup demonstrating that the migration failed - it is clearly not running forever.
3. IIRC you should still have access to the settings page: https://forge.chapril.org/miamondo/labortablo/settings where you can delete the repo. We should probably provide a direct button to delete the failed migration - please open an issue for that or change the title and information here.
4. You absolutely must fill out the issue proforma. Deleting it is an unacceptable waste of our time and therefore until it is completed I am closing this issue.

**Comment by mia-mondo** [comment]
So sorry to waste your precious time. Thanks for the provided informations. I will never disturb you anymore.
Have a nice day (or night... It depends on your location)

**Comment by 6543** [comment]
@mia-mondo you are welcome to report bugs, but pleace do it properly next time ... :)

**Comment by mia-mondo** [comment]
@6543 It's OK. I will follow the instructions, next time.

**Comment by zeripath** [comment]
Or even come to our discord to ask for help too! 

But in general you need to give us the information we need to help you. We would need information from the server logs to get more idea of what's going on etc. without it we're blind.
