### ISSUE TITLE
Can't see and filter issues by project in issue view

### ISSUE THREAD

**Issue by dusatvoj** [go-gitea/gitea#14298]
- Gitea version (or commit ref): 1.13.1
- Git version: 2.20.1
- Operating system: any
  
  
  
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
- Log gist:

## Description
When I list issues (page `<PROJECT_BASE_URI>/issues`) I can't see relations of issues to project and I can't apply filter like `Project: none` or `Project: 2021-Q1`

Expected:
 - being able to see project membership (if any) in this view
 - being able to filter issues by project

**Comment by delvh** [comment]
Closed by #22544
