### ISSUE TITLE
[Feature Request] Drag and drop image in comment

### ISSUE THREAD

**Issue by meaz** [go-gitea/gitea#14291]
## Description
It would be awesome if a user could directly drag and drop an image from his computer into a comment.
At the moment, the only way to embed an image in a comment is to upload the image somwhere on the web, then add its link into the comment.

**Comment by noerw** [comment]
This is not correct, each comment has an attachment form, where images can be dragged into. If this is not available, your instance may have the feature disabled (`[attachment]` section in config)

**Comment by meaz** [comment]
Hi, when I click on the Image logo, I get `![](http://)` but no possibility to add an image from my computer directly. And If I try to drag and drop, nothing happens.

**Comment by moqmar** [comment]
We had this in https://codeberg.org/Codeberg/Community/issues/9 as well - how shall attachments be referenced if the issue/comment hasn't been created yet? AFAIK, the URL is unknown then - would it be a possible solution to drag images from the attachment section into the text area? That would make it a lot easier & more intuitive.

**Comment by tyroneyeh** [comment]
This #20263 edit should fix the issue
Demo https://user-images.githubusercontent.com/1255041/176474223-e4ad12fb-3bfb-4811-a0b2-12555965655b.mov

**Comment by meaz** [comment]
that is perfect!

**Comment by wxiaoguang** [comment]
Great thanks to tyroneyeh, and after many refactoring PRs, it is implemented in main branch and will be available in next release (1.23). You could also use main-nightly build to test the enhancement.
