### ISSUE TITLE
Migration: Failed to initialize ORM engine: strconv.ParseInt: parsing invalid syntax

### ISSUE THREAD

**Issue by sbrl** [go-gitea/gitea#1429]
As per the conversation on gitter, another error has cropped up when migrating my gogs instance. Here it is:

```
2017/04/01 11:45:35 [...itea/routers/init.go:54 GlobalInit()] [E] Failed to initialize ORM engine: migrate: do migrate: strconv.ParseInt: parsing "d0068f4327d3e71625b373c4db7b689e": invalid syntax
```

**Gogs version:** 0.10.1.0228

Filed upon request from @strk.

**Comment by strk** [comment]
@lunny any idea about obtaining more details in the log ? That error message says nothing about which migration is failing and where

@sbrl maybe you can raise log level to TRACE ?

**Comment by strk** [comment]
This is probably line `42` of `models/migrations/v20.go`:
```
       for _, name := range names {                                            
                userID, err := strconv.ParseInt(name, 10, 64)                   
                if err != nil {                                                 
                        log.Warn("ignore avatar %s rename: %v", name, err)      
                        continue                                                
                }                   
```

The error check seems to reveal it *was* intended to skip errors, but maybe ParseInt is a fatal rather than raising an error ?

**Comment by sbrl** [comment]
@strk How do I raise the log level?

**Comment by strk** [comment]
@sbrl `LEVEL = Trace` under `[log]` section of `custom/conf/app.ini`, see https://docs.gitea.io/en-us/config-cheat-sheet/

**Comment by sbrl** [comment]
Updating to 1.1 from 1.1.0 appears to have resolved this issue.

**Comment by tboerger** [comment]
Perfect, so 1.1.1 will solve another issue
