### ISSUE TITLE
Ability to edit attached files in Issues

### ISSUE THREAD

**Issue by jhasse** [go-gitea/gitea#143]
When editing an issue it would be great if it was also possible to remove or edit the attached files.

**Comment by delvh** [comment]
According to [try.gitea.io](https://try.gitea.io), deleting attachments is possible, and editing is implicitly possible by deleting and reuploading an attachment (I don't know whether using any more advanced mechanism would be so beneficial here, current solution is pretty understandable).
I'd say that this issue can then be closed.

**Comment by zeripath** [comment]
@delvh I think you're correct this has been solved.
