### ISSUE TITLE
Make use of the race detector

### ISSUE THREAD

**Issue by typeless** [go-gitea/gitea#1430]
The race detector is helpful for discovering race conditions in concurrent programs. The easiest way I can think of is to add a new target or some kind of env. variable in the Makefile to enabe `-race`. We could also begin running try.gitea.io with the race detector enabled.

Edit:this is not just a proposal, but also a call for ideas about how we are going to do it.

**Comment by tboerger** [comment]
An env variable which is enabled on the ci makes sense

**Comment by strk** [comment]
How about GOFLAGS ?

**Comment by typeless** [comment]
@strk ~I don't understand how to apply GOFLAGS to the Makefile. Can you elaborate?~

I submitted a PR for it.

**Comment by strk** [comment]
Yes, I meant something like that.
I'm not sure $(GOFLAGS) would expand to the env variable, give it a try.
If it doesn't work, try ${GOFLAGS}
