### ISSUE TITLE
The service has no response control capability.

### ISSUE THREAD

**Issue by btwise** [go-gitea/gitea#14300]
Gitea service cannot be started as a service under Windows using The latest source code compilation. The service has no response control capability.

**Comment by a1012112796** [comment]
hello. please give us more information like the error log,  or we can't help you to solve your problem. Thanks.

**Comment by btwise** [comment]
> hello. please give us more information like the error log, or we can't help you to solve your problem. Thanks.

How to view the log? Windows system log only show the `startup service timeout`!
If I run `gitea web`  manually, it will work fine, but it will not start properly as a Windows service. This phenomenon has not been seen in previous versions!

**Comment by btwise** [comment]
@a1012112796 
![image](https://user-images.githubusercontent.com/38809560/104830113-8d216400-58b6-11eb-8776-8210041fd0f1.png)
使用`gitea web`可以正常运行，但使用`net start gitea`启动服务，无法正常工作，1.13的版本工作正常！_

**Comment by lafriks** [comment]
How was Gitea installed as service?

**Comment by btwise** [comment]
> How was Gitea installed as service?

`sc create gitea start= auto binPath= "\"C:\gitea\gitea.exe\" web --config \"C:\gitea\custom\conf\app.ini\""`

**Comment by lunny** [comment]
As this is not related with Gitea development. Please send this to https://discourse.gitea.io if you have further problem.
