### ISSUE TITLE
Index repositories after adoption

### ISSUE THREAD

**Issue by LukeMauldin** [go-gitea/gitea#14304]
- Gitea version (or commit ref): 1.13.1
- Git version: 2.29
- Operating system: RHEL8

- Database (use `[x]`):
  - [ X ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ X ] No

## Description
Provide a way to manually trigger source code indexing of repositories.  In my scenario, I have used the Adopt functionality to import a large number of repositories (over 500) but they are not indexed.  If I make a commit then it does appear the indexing functionality is working as expected but it is not practical to make commits to 500+ repos.  Need an admin API that would trigger the indexing process.  
As an enhancement to the adoption process, indexing could/should be triggered as a part of that process too.

**Comment by zeripath** [comment]
mea culpa - probably need to ensure that something like:

https://github.com/go-gitea/gitea/blob/9659808172b0d33a79eca44e37cabaf33fbf1b8b/routers/private/hook.go#L373

is called for each branch in the adopted repo.

**Comment by LukeMauldin** [comment]
Is there any work around after I have imported them?

**Comment by zeripath** [comment]
Push an empty commit should do it
