### ISSUE TITLE
Issue edit button broken on gitea 1.13 on Pale Moon web browser

### ISSUE THREAD

**Issue by wolfbeast** [go-gitea/gitea#14308]
- Gitea version (or commit ref): 1.13.1
- Git version: 2.24.3
- Operating system: CentOS 7
- Gitea installed from binary linux x64 download on releases page
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
- Log gist:

## Description
on an existing issue, pressing the edit button (to edit the issue title) does nothing
...

## Screenshots
Should be self-explanatory

**Comment by noerw** [comment]
Can't reproduce this in current Firefox. Which browser are you using?

**Comment by wolfbeast** [comment]
Pale Moon.
I checked the devtools for any hint but there doesn't seem to be anything there that's helpful.
1.14 as on the try server seems to be fine -- Unfotunately this did mean I had to revert to 1.12 on our production server since mos of us are using Pale Moon there.

**Comment by wxiaoguang** [comment]
Outdated, need more clues
