### ISSUE TITLE
Various font/alignment issues on 1.13

### ISSUE THREAD

**Issue by wolfbeast** [go-gitea/gitea#14309]
- Gitea version (or commit ref): 1.13.1
- Git version: 2.24.3
- Operating system: CentOS 7
- Installed from Gitea binary package from releases page (amd64-linux)
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL) https://try.gitea.io/Moonchild/testrepo/issues/1
  - [ ] No
- Log gist:

## Description
Font on buttons in Windows browsers are seriously misaligned. When disabling the custom fonts (via devtools) from the wallpaper rule in index.css, things look fine -- In addition the issue title fonts are terribly thin in comparison to 1.12
...

## Screenshots

![Image1](https://user-images.githubusercontent.com/3359132/104239601-0f46fe00-545b-11eb-9326-76c255728bac.png)

**Comment by wxiaoguang** [comment]
Some of them have been fixed.

Feel free to open new issues with new problems.
