### ISSUE TITLE
Copy branch configuration from the template

### ISSUE THREAD

**Issue by tomaswarynyca** [go-gitea/gitea#14303]
## Description

Having a configuration for the main branch in a template should be copied when one creates a repository from that template.
This was discussed at the time in #9126 but it was left abandoned, I create these issues to see if it can be reactivated because it is a functionality that is very useful to devops.

**Comment by zeripath** [comment]
are you sure that this is not already the case following #10803?

**Comment by jolheiser** [comment]
Hello! I am currently working on this (and I will re-open #9126, I forgot to keep the stalebot away 😓 )

One caveat is whitelisted users/teams, as those could be infeasible depending on who is using the template and what type of access they have compared to the template owner.
For the initial version I don't think those will be carried over. 
Some fancy code could probably determine an intersection of valid values, but that's likely more complex than necessary.

**Comment by lunny** [comment]
You can read the template repositories, but maybe you have no permissions knows how the protected branches configured because this is a feature of owners of that repository.

@jolheiser I think this is a point we should be careful.

**Comment by tomaswarynyca** [comment]
Not all should be copied, but the main protected files, required approvals, status check, among others.
![Captura de pantalla_área-de-selección_20210113142343](https://user-images.githubusercontent.com/41587659/104487073-66f47f00-55ab-11eb-92b6-58f4709656d6.png)

**Comment by tomaswarynyca** [comment]
Hi, I saw that the pr was already made but was abandoned, it is a tool that I need at work, is it possible to implement it now?

**Comment by jolheiser** [comment]
What makes you think #14334 is abandoned? 🤔

**Comment by tomaswarynyca** [comment]
> What makes you think #14334 is abandoned?

The last commit was 13 days ago, I thought it was already finished
As I had no news about the pr or issues I decided to send the message

**Comment by jolheiser** [comment]
We are currently in a freeze to get 1.14 polished up, and the reference PR is slated for 1.15 as a result. 
It may take a while for it to get reviewed. 🙂

**Comment by tomaswarynyca** [comment]
When is it planned to release the final v1.14 to start with v1.15?
I'm sorry if I'm pushing too hard, but I'm needing the function for several projects at work.

**Comment by jolheiser** [comment]
Unfortunately it's very hard to pin down a day. We are entirely run by volunteer time, so the best we can do is a general timeframe. 

The milestone for [1.14](https://github.com/go-gitea/gitea/milestone/76) is past due by 4 days (at time of this writing), however there will still need to be RCs prior to a stable release, etc.

If you are needing this sooner than later, I would suggest instead writing a script to copy branch protection from one repo to another.
You can use the API to [get branch protection](https://try.gitea.io/api/swagger#/repository/repoGetBranchProtection) from a repo, and then use the API to [create branch protection](https://try.gitea.io/api/swagger#/repository/repoCreateBranchProtection) for another repo.

**Comment by tomaswarynyca** [comment]
Ohh great I hadn't considered the option of using the API.
So thanks for the functionality and I look forward to v1.15 to try it out.

**Comment by ztrnr** [comment]
@tomaswarynyca have you created this script? I'm looking for the same functionality at my work.

**Comment by GregJCook** [comment]
I just stumbled across this missing feature as well. Any update on getting branch protection policies to carry forward from a template?

**Comment by Calvin-Hill** [comment]
Is this still in the works? Just stumbled on this issue when creating a repo from my template and realising none of my branch protection rules had copied over

**Comment by Barsay** [comment]
Any news on this? same as @Calvin-Hill , found this while setting up a template

**Comment by w4dd325** [comment]
Any further developments on this? Interested to get this setup...

**Comment by fuzunspm** [comment]
this is a must have feature. I would like to copy master/main rule set from a repository to all other repositories

**Comment by lmandon** [comment]
Hello,
This would be beneficial to our teams as well, looking forward to the implementation.
