### ISSUE TITLE
push files are not displayed in repo | when push by ssh login and password are requested

### ISSUE THREAD

**Issue by thisisusernameforgit** [go-gitea/gitea#14313]
- Gitea version (or commit ref): 1.12.3, 1.13.1
- Git version: 2.22
- Operating system: Centos 7

- Log gist:
no errors were found in the application logs when trying to uploads files in to repo from CLI

## Description
Hello!

_What I have:_
- authorization by LDAP is enabled and works correctly
- ssh key added to my gitea account
- entering the command 
```
ssh -T git@mygitea.ru
Hi there, Graceastrid! You've successfully authenticated with the key named Graceastrid@mygitea.ru, but Gitea does not provide shell access.
If this is unexpected, please log in with password and setup Gitea under another user.
```

_What am I doing:_
1. create a new repository via web-gitea
2. according to the Quick Guide, with CLI I add README.md to the repository
3. after git push -u origin master, I am prompted for the LDAP login and password (it is not known why this happens if there is ssh access)
4. a message appears about the successful download of files
5. However, when browsing the repository through the Gitea web interface, the repository is empty and shows the Quick Guide.
6. in the meantime, if you clone this repository, then it is actually not empty - it has README.md

at the same time, if during the creation of a new repository check the box "Initialize Repository (Adds .gitignore, License and README)", then the files uploaded to the repository are displayed correctly, but all the same, when running git push -u origin master, I am prompted login and password.

**Comment by rmbleeker** [comment]
Can you please provide the output of `git remote -v` when in your repository directory? I suspect that you're actually pushing your repo to a different location from your Gitea server.

**Comment by graceastrid** [comment]
> Can you please provide the output of `git remote -v` when in your repository directory? I suspect that you're actually pushing your repo to a different location from your Gitea server.

here is the command output
```
origin  http://mygitea.ru/graceastrid/test.git (fetch)
origin  http://mygitea.ru/graceastrid/test.git (push)
```

**Comment by rmbleeker** [comment]
You are using http to access the repo, not ssh. That's why the ssh key is not used and you are prompted for a username and password. Why any committed files are not showing up in Gitea after pushing though I can't tell from this information, also it does seem they should be there since you say that you do see them after cloning the repository again.

**Comment by graceastrid** [comment]
> You are using http to access the repo, not ssh. That's why the ssh key is not used and you are prompted for a username and password. Use a `git@mygitea.ru:graceastrid/test.git` style url instead.
> 
> Why any committed files are not showing up in Gitea after pushing though I can't tell from this information, also it does seem they should be there since you say that you do see them after cloning the repository again.

re-created the repository and did everything via ssh - login and password are not requested, thanks.

but still: after git push -u origin master I see a series of unknown lines in the git response

```
Object enumeration: 3, done.
Counting objects: 100% (3/3), done.
Recording objects: 100% (3/3), 207 bytes | 207.00 KiB / s, done.
Total 3 (changes 0), reused 0 (changes 0)
hint: The hooks / pre-receive interceptor was ignored because it is not installed as executable.
hint: You can turn off this warning with the command "git config advice.ignoredHook false".
hint: The "hooks / update" interceptor was ignored because it is not installed as executable.
hint: You can turn off this warning with the command "git config advice.ignoredHook false".
hint: The hooks / post-receive interceptor was ignored because it is not installed as executable.
hint: You can turn off this warning with the command “git config advice.ignoredHook false”.
To mygitea.ru: graceastrid / test.git
 * [new branch] master -> master
The master branch tracks the external master branch from origin.
```


the files are not displayed in the repository. when cloning a repository - they are in the directory where I cloned it - so they are in the repository, just for some reason they are not displayed in it ...

**Comment by lunny** [comment]
`chmod +x hooks/pre-receive`

**Comment by graceastrid** [comment]
> chmod +x hooks/pre-receive

files in this directory already have the appropriate permissions ...
```
ls -l

-rwxr-xr-x 1 git git 478 Jan 13 15:53 ​​applypatch-msg.sample
-rwxr-xr-x 1 git git 896 Jan 13 15:53 ​​commit-msg.sample
-rwxr-xr-x 1 git git 3327 Jan 13 15:53 ​​fsmonitor-watchman.sample
-rwxr-xr-x 1 git git 324 Jan 13 16:12 post-receive
drwxr-xr-x 2 git git 4096 Jan 13 16:12 post-receive.d
-rwxr-xr-x 1 git git 189 Jan 13 15:53 ​​post-update.sample
-rwxr-xr-x 1 git git 424 Jan 13 15:53 ​​pre-applypatch.sample
-rwxr-xr-x 1 git git 1638 Jan 13 15:53 ​​pre-commit.sample
-rwxr-xr-x 1 git git 1492 Jan 13 15:53 ​​prepare-commit-msg.sample
-rwxr-xr-x 1 git git 1348 Jan 13 15:53 ​​pre-push.sample
-rwxr-xr-x 1 git git 4898 Jan 13 15:53 ​​pre-rebase.sample
-rwxr-xr-x 1 git git 324 Jan 13 16:12 pre-receive
drwxr-xr-x 2 git git 4096 Jan 13 16:12 pre-receive.d
-rwxr-xr-x 1 git git 544 Jan 13 15:53 ​​pre-receive.sample
-rwxr-xr-x 1 git git 304 Jan 13 16:12 update
drwxr-xr-x 2 git git 4096 Jan 13 16:12 update.d
-rwxr-xr-x 1 git git 3610 Jan 13 15:53 ​​update.sample

```

so `chmod + x hooks/pre-receive` doesn't help

**Comment by zeripath** [comment]
are your gitea repositories on a disk mounted with `noexec`?

**Comment by graceastrid** [comment]
> are your gitea repositories on a disk mounted with `noexec`?

no, my gitea repositories is on the same server where gitea is deployed /opt/gitea_repo/

**Comment by zeripath** [comment]
Well something in your setup is preventing the repository hooks from being executed - Gitea requires the hooks in its git repositories to be executed on push.

That's the ultimate cause of your problem.

**Comment by graceastrid** [comment]
> Well something in your setup is preventing the repository hooks from being executed - Gitea requires the hooks in its git repositories to be executed on push.
> 
> 
> 
> That's the ultimate cause of your problem.

The most interesting thing is that some time ago everything worked correctly, but suddenly this problem appeared ... thanks for your help
