### ISSUE TITLE
[Feature Request] Comment - Reference in new issue

### ISSUE THREAD

**Issue by kdumontnu** [go-gitea/gitea#14315]
GitHub introduced a new feature to create a new issue from a PR comment.
![53243733-97fdfa80-3687-11e9-9512-9aeb3c0ffa80](https://user-images.githubusercontent.com/12700993/104357798-e2caca80-54ca-11eb-8a33-dc44459fdc30.png)
Clicking the option opens up a modal
![53243797-c4197b80-3687-11e9-883a-9ed2a24cfd47](https://user-images.githubusercontent.com/12700993/104357849-ee1df600-54ca-11eb-91e1-77c3cf9c0558.png)

I've found this feature to be quite a time-saver, helpful for providing additional context for why the issue was opened, and helpful in continuing long discussions in PRs. Would be a great addition to see in Gitea.

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=95865752)](https://www.bountysource.com/issues/95865752-feature-pull-request-comment-reference-in-new-issue)

**Comment by kdumontnu** [comment]
Bounty available: https://www.bountysource.com/issues/95865752-feature-pull-request-comment-reference-in-new-issue

### Requirements:
 - As in GH, user can select from the dropdown from any comment (PR or issue) to create a new issue from the comment, in which case the modal will display (as shown below)
 - As in GH, the Title should populate with the first X (80? or anything we use as default) characters of the first comment
 - As in GH, the Body should populate with all comments and the link to author & origin
 - Unlike GH, the option to create new issue should also be included next to the option to "Resolve conversation" (as shown below)

### Requested (but optional)
 - As in GH, the Repository can be selected from a dropdown in the modal and by default uses the current repository

![image (14)](https://user-images.githubusercontent.com/12700993/104381043-28968b80-54e9-11eb-9e72-ed7512c59bbc.png)

**Comment by Daxigua443** [comment]
1111111

**Comment by KN4CK3R** [comment]
I have implemented this feature in https://github.com/KN4CK3R/gitea/tree/feature-reference-in-issue 

> Unlike GH, the option to create new issue should also be included next to the option to "Resolve conversation" (as shown below)

What if there are multiple comments? Which text should be used to create the issue? On the `Files Changed` tab you can create issues from single comments: 
![grafik](https://user-images.githubusercontent.com/1666336/104794782-41819400-57aa-11eb-82d5-3f0c966c48dc.png)

**Comment by kdumontnu** [comment]
Awesome!
> What if there are multiple comments? Which text should be used to create the issue? On the `Files Changed` tab you can create issues from single comments:

I would default to the first comment in the Title and the whole comment thread in the body of that's what you mean.

**Comment by KN4CK3R** [comment]
How about this:
![grafik](https://user-images.githubusercontent.com/1666336/104852325-b19f2f80-58fa-11eb-9de4-2133d1f880b2.png)

I have implemented the contex menu bubbles on file comments. Now it works like in all other places.

**Comment by kdumontnu** [comment]
@KN4CK3R I just realized that in GH you can also reference code in new issues (see below). I decided to post here to keep your existing PR clean. I think this can be resolved in a future PR, but I figured I'd let you know in case you wanted to tackle it now.
![image](https://user-images.githubusercontent.com/12700993/105110861-d8856f00-5a7c-11eb-93c7-2c1a4ca52197.png)

**Comment by 6543** [comment]
closed with #14366 by @KN4CK3R

**Comment by 6543** [comment]
@KN4CK3R you may wana claim https://www.bountysource.com/issues/95865752-feature-request-comment-reference-in-new-issue
