### ISSUE TITLE
Incomplete repo creation not visible in web-ui

### ISSUE THREAD

**Issue by BarrOff** [go-gitea/gitea#14317]
## Description

I tried to create a repo on the [official gitea instance](https://gitea.com/) using the official [tea cli](https://gitea.com/tea).
The exact command was: `tea repo c --name nim-olm --private --labels "nim,olm,cryptography"`.  This seems to have failed, as the only response was a single line stating `Error:` and nothing more.
Trying to create the repository using the web client, I now get a message that "The data for the repository already exists. Please contact a system administrator", see the screenshot down below.
However the repository is not visible in the webui or using the tea cli.

Also, if some gitea.com-admin is reading this, it would be great if he could remove the data, so I can properly create the repository. My account name is [BarrOff](https://gitea.com/BarrOff), and I tried to create a repo named "nim-olm".

## Screenshots

![gitea](https://user-images.githubusercontent.com/58253563/104369582-9193f880-5515-11eb-95df-4abb720f662e.png)

**Comment by techknowlogick** [comment]
for issues with gitea.com please report at https://gitea.com/gitea/gitea.com
