### ISSUE TITLE
Rename gitea/conf/app.ini to app.ini.example

### ISSUE THREAD

**Issue by cez81** [go-gitea/gitea#1432]
The app.ini found in gitea/conf is not an active configuration file. To save the confusion it might be a good idea to rename it to app.ini.example.

**Comment by tboerger** [comment]
Why is it confusing? It's even not shipped with the binary.

**Comment by andreynering** [comment]
@tboerger Many people compile from source. I actually liked the idea. Alternatively could be an "example" folder.

**Comment by strk** [comment]
As far as I know conf/app.ini is actually what gets compiled into bindata,
for builds with the `bindata` tag, and is otherwise read from FS before
the custom one for other builds.

If that's confirmed, I think it shouldn't be renamed.

Note that bindata builds should not even have a conf/ directory as the
binary would be enough to run.

**Comment by cez81** [comment]
Yes, that's what I thought but if I have understood it correctly all defaults are loaded from modules/setting/setting.go.  Only reference that I can find is in gogs_migration.sh

In Gogs it works like you have described it.

**Comment by strk** [comment]
Interesting, I confirm you can actually move away the conf/ directory
even with non-bindata build. I'm not sure renaming to .example but keeping
it in that dir helps anyone though, because dropping the .example part
would still have no effect unless it's moved to the custom dir.

**Comment by cez81** [comment]
Good point. Renaming the folder and explaining the purpose of the file might be a better idea.

**Comment by bkcsoft** [comment]
You have my 👍 on changing the name of the file/folder

@tboerger We still have to consider people that don't install from binary 😉

**Comment by cez81** [comment]
Closed by #1522
