### ISSUE TITLE
Failed to update mirror repository in local network

### ISSUE THREAD

**Issue by glogar** [go-gitea/gitea#14325]
- Gitea version (or commit ref): 1.13.1
- Git version: 2.19.0
- Operating system:
   CentOS 7, systemd, https://dl.gitea.io/gitea/1.13.1/gitea-1.13.1-linux-amd64
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
- Log gist:

## Description
Mirrors do not synchronize even after setting `ALLOW_LOCALNETWORKS = true`. I do not have problems with external repositories like (GitHub, GitLab,...). Problems occur when I want to migrate a repository inside the same local network. For the test, I tried and failed to move the repository from one organization to another within the same instance of Gitea.

## Log
```
2021/01/13 11:19:17 ...ces/mirror/mirror.go:243:runSync() [E] Failed to update mirror repository &{126 35 ***** <nil> thirdparty-illd thirdparty-illd   0 http://*****:*****@*****.local/*****/thirdparty-illd.git master 12 0 0 2 1 1 0 0 0 0 0 0 0 0 0 false false false true <nil> 0 map[] map[] [] <nil> false 0 <nil> false 0 <nil> 29362564 <nil> <nil> false false [] default  1569935076 1610529628}:
	Stdout: Fetching origin
	
	Stderr: error: RPC failed; HTTP 417 curl 22 The requested URL returned error: 417 Expectation Failed
	fatal: expected flush after ref listing
	error: Could not fetch origin
	
	Err: <nil>
2021/01/13 11:19:17 ...m.io/xorm/core/db.go:286:afterProcess() [I] [SQL] INSERT INTO `notice` (`type`,`description`,`created_unix`) VALUES (?,?,?) [1 Failed to update mirror repository '/home/edgitea/gitea-repositories/*****/thirdparty-illd.git': error: RPC failed; HTTP 417 curl 22 The requested URL returned error: 417 Expectation Failed
	fatal: expected flush after ref listing
	error: Could not fetch origin
	 1610533157] - 2.692132ms
```

## Screenshots

![image](https://user-images.githubusercontent.com/22919879/104445038-ec226880-5598-11eb-84e2-3e1e2a0c69bf.png)

**Comment by zeripath** [comment]
This error is coming directly from git 

The git version is entirely relevant.

**Comment by glogar** [comment]
Tnx @zeripath after updating git from 1.19.0 to the latest (2.29.2) everything works as expected. I'm closing the issue.
