### ISSUE TITLE
API: create repo with invalid label set hangs gitea

### ISSUE THREAD

**Issue by noerw** [go-gitea/gitea#14327]
- Gitea version (or commit ref): 1.14.0+dev-454-g19ae6439b 
- Git version: 2.29.2
- Operating system: fedora linux
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (probably, at least on gitea.com, see https://gitea.com/gitea/gitea.com/issues/21
  - [ ] No
- Log gist: https://pastebin.com/eXZc273c

## Description
Using the API to create a repo with a non-existent label-set makes gitea hang, and leaves a partially initialized repo.

On gitea.com the repo is partially created, and an empty error message is returned.
Testing locally with 9659808172b0d33a79eca44e37cabaf33fbf1b8b, Gitea hangs indefinitely instead of finishing the request.

Following requests give `repository files already exist`.

To reproduce:
```
tea repo create --name foo --labels asdfasdf404
```

ref: https://gitea.com/gitea/gitea.com/issues/21

**Comment by lunny** [comment]
I got the error message
```
2021/01/14 00:27:01 Failed to run app with [tea repo create --login=local --name foo --labels asdfasdf404]: InitializeLabels: Failed to load label template file 'asdfasdf404': GetRepoInitFile: Asset file does not exist: label/asdfasdf404
```

**Comment by lunny** [comment]
When create a repository with labels, `opts.IssueLabels` is the label template name but not labels themselves. So I think the response error `Failed to load label template file 'asdfasdf404'` is right.

**Comment by lunny** [comment]
@noerw I can confirm the bug also affect v1.13 so I changed the milestone.

**Comment by 6543** [comment]
could not reporduce it, so #14384 is only a **draft** ... would be nice if those who can reproduce could test it ...

**Comment by 6543** [comment]
Edit: I think this is a sqlite deadlock ...
wait ... I'll setup a extra test instance

**Comment by lunny** [comment]
The problem is the parameter of `tea` think it's a label value, but `Gitea` think the parameter is a label set template name.

**Comment by 6543** [comment]
This is caused by a weak struct field description ... changed this in my pull too

**Comment by 6543** [comment]
#14384 is ready :rocket:
