### ISSUE TITLE
"Renamed Repo" action does not display correctly in japanese

### ISSUE THREAD

**Issue by ssttevee** [go-gitea/gitea#1433]
- Gitea version (or commit ref): `Gitea version 1.1.0 built with: bindata, sqlite`
- Git version: `git version 2.1.4`
- Operating system: Debian GNU/Linux 8 (jessie)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:
N/A
## Description
The "renamed repo" action on the dashboard does not display correctly in japanese

## Screenshots
![image](https://cloud.githubusercontent.com/assets/434125/24583751/35607edc-170a-11e7-87fa-b2abd94b2a5f.png)
![image](https://cloud.githubusercontent.com/assets/434125/24583760/86f2acfc-170a-11e7-869a-60bd116a4732.png)

**If this issue involves the Web Interface, please include a screenshot**

**Comment by lunny** [comment]
This should be a translation issue. Please go to https://crowdin.com/translate/gitea/68/enus-ja to submit translation.
