### ISSUE TITLE
Allow changing the default branch of a repository

### ISSUE THREAD

**Issue by strk** [go-gitea/gitea#14330]
I haven't found a way to change the "default branch" for a repository.
Tried on try.gitea.org with no luck.
The "default branch" is specified when the repository is created and there seems to be no way to update it afterwards.

NOTE github is implementing renaming the default branch: https://github.com/github/renaming

For a start it would be ok to just _specify_ which branch is the default branch, which is what I was after for this ticket.

**Comment by jolheiser** [comment]
You can change it on the branch settings page. 
https://try.gitea.io/strk/test2/settings/branches

**Comment by strk** [comment]
Oh, it looks like you're right. It just wasn't very clear to me :)
