### ISSUE TITLE
Error 500 when creating new pull request

### ISSUE THREAD

**Issue by tobias--** [go-gitea/gitea#1434]
- Gitea version (or commit ref): 1.1.0
- Git version: 
- Operating system: Windows 2008 R2
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

```
2017/04/03 15:01:21 [T] PullRequest[0].testPatch (patchPath): E:\gogs-repositories\XXX\XXX.git\pulls\34.patch
2017/04/03 15:01:21 [T] NewMessageFrom (htmlBody):
[E-Mail contents]
2017/04/03 15:01:21 [T] New e-mail sending request [XXXX@XXX]: Subject: [XXX] XXXXX (#34), issue comment
2017/04/03 15:01:22 [T] PushToBaseRepo[7]: pushing commits to base repo 'refs/pull/34/head'
2017/04/03 15:01:22 [T] DeliverHooks [repo_id: 7]
2017/04/03 15:01:23 [T] E-mails sent [XXXX@XXX]: Subject: [XXX] XXXXXX (#34), issue comment
2017/04/03 15:01:24 [T] Pull request created: 7/45
2017/04/03 15:01:24 [D] Session ID: 69b660ffed886882
2017/04/03 15:01:24 [D] CSRF Token: eiBhxp_6MTDX7ZVZMbbfWgZRKP46MTQ5MTIwMTMyODYxMTk1NDgwMA==
2017/04/03 15:01:24 [...user/notification.go:33 GetNotificationCount()] [E] GetNotificationCount: database table is locked: notification
2017/04/03 15:01:24 [D] Template: status/500
```

## Description

Creating a new PR will sometimes result in a 500 error. The PR seems to be alright and can be merged. It seems that updating notifications table does not work.

**Comment by plessbd** [comment]
duplicate of #1372 ?

**Comment by lunny** [comment]
seems not.

**Comment by plessbd** [comment]
You are right, didnt fully see the end of error line.
Seem related though, both are because of a table lock.
This one on `notification`, #1372 because of `repository`

**Comment by bkcsoft** [comment]
Could you test if this fixes the issue? #1961 (applying the diff and building on v1.1.2 should be straight forward)

**Comment by lunny** [comment]
@bkcsoft I think #1961 didn't resolve the database lock problem. And move all database lock issues to v1.3.

**Comment by lunny** [comment]
continue via #2040
