### ISSUE TITLE
issue_label and issue_milestone webhooks not triggered on new issue

### ISSUE THREAD

**Issue by jpraet** [go-gitea/gitea#14352]
- Gitea version (or commit ref): 1.13.1
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes

## Description

The issue_label, issue_milestone, pull_request_label and pull_request_milestone webhooks are not triggered when you immediately provide the label or milestone when creating the new issue/pr. When adding the label or milestone AFTER the issue/pr has already been created it works fine.

This is not consistent with the issue_assign/pull_request_assign webhooks: these also get triggered if you provide the assignee immediately when creating the new issue/pr.

## Screenshots

![image](https://user-images.githubusercontent.com/2212615/104779837-1a15d180-5780-11eb-8bde-48b5aa2c13eb.png)

The webhook:

![image](https://user-images.githubusercontent.com/2212615/104779939-429dcb80-5780-11eb-8a0b-7b88108539e2.png)

Only receives the notification for the issue_assign. 

![image](https://user-images.githubusercontent.com/2212615/104780050-711ba680-5780-11eb-93a8-d52a1b659cc4.png)

**Comment by lunny** [comment]
Should we remove all extra events when create an issue/pull request or add them all?

**Comment by jpraet** [comment]
Emitting the labeled/milestoned/assigned events regardless of whether they were added at creation time or afterwards seems most intuitive to me, from the point of view of configuring and implementing a webhook.
