### ISSUE TITLE
[Feature] New mirror ->list with > 200 organisations opens too slow

### ISSUE THREAD

**Issue by somera** [go-gitea/gitea#14356]
- Gitea version (or commit ref): 1.13.1
- Git version: 2.25.1
- Operating system: Ubuntu 20.04.1
  
  
  
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
  - [ ] 
## Description

My local Gitea instance has at the moment 245 organisations. I had a lot of mirrors from Github. When I'm adding new mirror and open the list with the 245 organisations (this will grow) it's took ~1,5 seconds. It will be better to change this to input field and when I start to type I get some suggestions. Like google search.

## Screenshots

![image](https://user-images.githubusercontent.com/8334250/104810231-87167f00-57f3-11eb-8604-fd36427fe6c5.png)

**Comment by lunny** [comment]
Maybe an input-search box here is better?

**Comment by somera** [comment]
> Maybe an input-search box here is better?

Yes. And when you type s you get ...

simulation
server

sorted back.

When you type si you get only

simulation

back.

Some weeks ago I opened #13090

**Comment by lunny** [comment]
Ok. That issue is about sort, this one is about performance. :(

**Comment by somera** [comment]
I'm working now with Gitea 1.15.6 and I have 1233 organisations. The list is sorted and it works fine.

I'm closing it now.
