### ISSUE TITLE
Deactivating Gravatar makes web-front-end unusable

### ISSUE THREAD

**Issue by distinguiert** [go-gitea/gitea#14369]
- Gitea version (or commit ref): 1.13.1 (download package from github)
- Git version: 
- Operating system: Debian Buster (amd64)
  
  
  
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
- Log gist:

## Description

Deactivating Gravatar in app.ini makes the web-front-end unusable, due to the fact the first page request always stucks on loading avatar or dom for 30 seconds. The next page requests work fine, until some time has gone. Looks like there is a cache involved which expires. Gogs shows the exact same behavior, as well as previous gitea versions.

**Comment by wxiaoguang** [comment]
I also disabled Gravatar, can not reproduce the problem.

Feel free to reopen with more clues.
