### ISSUE TITLE
Cron task hanging when mirroring repositories

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#14362]
- Gitea version (or commit ref): v1.13.1
- Git version: git version 2.20.1
- Operating system: Debian
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
- Log gist:
```
Jan 17 10:43:15  gitea[3279]: 2021/01/17 10:43:15 ...ces/mirror/mirror.go:350:Update() [T] Doing: Update
<truncated>
Jan 17 10:43:15  gitea[3279]: 2021/01/17 10:43:15 ...ces/mirror/mirror.go:388:syncMirror() [T] SyncMirrors [repo_id: 1455]
<truncated>
Jan 17 10:43:15  gitea[3279]: 2021/01/17 10:43:15 ...ces/mirror/mirror.go:406:syncMirror() [T] SyncMirrors [repo: 1455:Mirror/<repo>]: Running Sync
Jan 17 10:43:15  gitea[3279]: 2021/01/17 10:43:15 ...ces/mirror/mirror.go:215:runSync() [T] SyncMirrors [repo: 1455:Mirror/<repo>]: running git remote update...
<truncated>
Jan 17 10:43:16  gitea[3279]: 2021/01/17 10:43:16 ...ces/mirror/mirror.go:258:runSync() [T] SyncMirrors [repo: 1455:Mirror/<repo>]: syncing releases with tags...
<truncated>
Jan 17 10:43:16  gitea[3279]: 2021/01/17 10:43:16 ...ces/mirror/mirror.go:265:runSync() [T] SyncMirrors [repo: 1455:Mirror/<repo>]: updating size of repository
<truncated>
Jan 17 10:43:17  gitea[3279]: 2021/01/17 10:43:17 ...ces/mirror/mirror.go:271:runSync() [T] SyncMirrors [repo: 1455:Mirror/<repo> Wiki]: running git remote update...
Jan 17 10:43:18  gitea[3279]: 2021/01/17 10:43:18 ...ces/mirror/mirror.go:301:runSync() [T] SyncMirrors [repo: 1455:Mirror/<repo> Wiki]: git remote update complete
Jan 17 10:43:18  gitea[3279]: 2021/01/17 10:43:18 ...ces/mirror/mirror.go:304:runSync() [T] SyncMirrors [repo: 1455:Mirror/<repo>]: invalidating mirror branch caches...
Jan 17 10:43:18  gitea[3279]: 2021/01/17 10:43:18 ...ces/mirror/mirror.go:412:syncMirror() [T] SyncMirrors [repo: 1455:Mirror/<repo>]: Scheduling next update
<no more logs>
```

## Description

Hi all, I have a strange issue, when the scheduled update mirrors cron task is executed, it will get stuck and the queue will be completely blocked.

But when I do a manual update of the repository, it doesn't have any problems.

I can always reproduce it on any repository.

It always gets stuck here:
https://github.com/go-gitea/gitea/blob/632800eda7108e5e8d90dd9e3e985da3deecf365/services/mirror/mirror.go#L411-L417

I have 1324 mirrors and the db file is about 90mb.

Can anyone give some advice on how to fix it?

**Comment by zeripath** [comment]
increase the value of `MIRROR_QUEUE_LENGTH` in `[repository]`

We need to migrate the mirror queue to use the real queue infrastructure.

**Comment by yasuokav** [comment]
> increase the value of `MIRROR_QUEUE_LENGTH` in `[repository]`
> 
> We need to migrate the mirror queue to use the real queue infrastructure.

@zeripath 

I tried to increase this value but it did not help.

I can reproduce it when I manually execute the "Update Mirrors" cron task, but I don't any problem when I manually update a single repository.

```
gitea[4151]: 2021/01/17 16:12:40 ...ces/mirror/mirror.go:304:runSync() [T] SyncMirrors [repo: 885:Mirror/]: invalidating mirror branch caches...
gitea[4151]: 2021/01/17 16:12:40 ...ces/mirror/mirror.go:412:syncMirror() [T] SyncMirrors [repo: 885:Mirror/]: Scheduling next update
```
![1](https://user-images.githubusercontent.com/2960293/104848996-d3b0a600-592a-11eb-9780-a30c96574fc8.png)
Is there some reason the sql request is causing blocking?

**Comment by zeripath** [comment]
what did you increase it to?

**Comment by yasuokav** [comment]
> what did you increase it to?

@zeripath 

```
MIRROR_QUEUE_LENGTH = 6000
PULL_REQUEST_QUEUE_LENGTH = 6000
```

**Comment by yasuokav** [comment]
It seems that I have too many repositories that need to be synchronized.

```
SELECT * FROM mirror WHERE next_update_unix<=strftime('%s', 'now') AND next_update_unix!=0;
Result: 1272 rows returned in 12ms
```

But increasing `MIRROR_QUEUE_LENGTH` doesn't seem to help.

I increased the `next_update_unix` of some repositories as a workaround. Thanks for helping anyways.
