### ISSUE TITLE
ERROR: This SSH key has already been added to the server.

### ISSUE THREAD

**Issue by ffbh123456** [go-gitea/gitea#14360]
I created two users A and B. I am setting up ssh for them. I first set up the ssh key for user A. The setting is successful, and then I assign the same ssh key to B. At this time, an error message This SSH key has already been added to the server.
![image](https://user-images.githubusercontent.com/20750357/104831685-2ad05f80-58c6-11eb-94dc-d61e240eabc2.png)

**Comment by techknowlogick** [comment]
The same SSH key cannot be added to different users.

In future please ensure you fill out the entire issue template.
