### ISSUE TITLE
Webhooks to Discord not working.

### ISSUE THREAD

**Issue by ziplock9000** [go-gitea/gitea#14379]
Gita Version: 1.13.0
OS: Windows 10, Using pre-compiled binary

The webhook does not work and comes back with the response / error `{"embeds": ["0"]}`

I have Gitea set up on a private LAN that is not accessible from the internet. I've set up webhooks to talk to a Discord server. The JSON that is generated to be sent to the Discord server from the Gitea server has several URLs that are only accessible and valid within the LAN, which a Discord server won't have access to.

URLS such as `"url": "http://myserver:myport/myuser"`

If the issue is that the Gitea server is hidden on the LAN, then a configuration option should be available to remove any JSON entries that require this. So a less functional, but still working version of the Discord message.

**Comment by techknowlogick** [comment]
This is an error with Discord, as if they can't fetch a link inside an API call then they refuse to publish content as is. I'm going to close this as customization on this level would be better suited to the webhook template issue.

**Comment by ziplock9000** [comment]
Which "webhook template issue"? Can you provide a link at least?

Searching for template or webhook does not bring up any obvious issues that would solve this problem

@techknowlogick

**Comment by jolheiser** [comment]
@ziplock9000 https://github.com/go-gitea/gitea/issues/1089 (also included in the list in https://github.com/go-gitea/gitea/issues/3998)
