### ISSUE TITLE
Proposal: Bug bounties on gitea?

### ISSUE THREAD

**Issue by Kreyren** [go-gitea/gitea#14376]
Proposing to implement handling to allow anyone to submit a bug bounty on gitea issues that they care about to influence it's priority and handling in case the issue:
1. affects small user base (low priority issues in general)
2. is not economical for (F)LOSS development as it's too complicated e.g. https://github.com/QubesOS/qubes-issues/issues/4318
3. is for Libre Open Source Software (LOSS) project that depends on business plan in place which bug bounties would allow for.

**Comment by noerw** [comment]
To clarify: with "on gitea issues" do you mean Gitea the project, or Gitea the software?

**Comment by Kreyren** [comment]
> To clarify: with "on gitea issues" do you mean Gitea the project, or Gitea the software? @noerw

Gitea the software as i would like to use this for my projects.

**Comment by techknowlogick** [comment]
Closing this ticket as bounties for the Gitea project are a thing already (please see the link in README, https://www.bountysource.com/teams/gitea). Last week there were two large ones made. As well, commissioning developers directly is also possible.

**Comment by noerw** [comment]
As @Kreyren clarified, this is about integrating bug bounty programs with gitea's issue tracker, not about bounties on issues of the gitea project.

**Comment by techknowlogick** [comment]
I think then this would be in scope for the bounty projects of potentially using oauth to edit tickets to insert a link into the ticket, and labelling issues appropriately. If this is a request for the bounty logic to be put directly into Gitea I think that is out of scope as dealing with being a bank and storing funds is significant undertaking.

**Comment by Kreyren** [comment]
> I think then this would be in scope for the bounty projects of potentially using oauth to edit tickets to insert a link into the ticket, and labelling issues appropriately. If this is a request for the bounty logic to be put directly into Gitea I think that is out of scope as dealing with being a bank and storing funds is significant undertaking.

We dont have to deal with a bank if it was using cryptocurrency e.g. monero which would allow handling the funds through the instance quite nicely.

**Comment by 6543** [comment]
I think this is outside of gitea's scope too .. but would be a nice smal project ...

something like a **"gitea bounty bot"** ... since it also has to connect to cryptocurrency nodes + manage wallets, ...
