### ISSUE TITLE
Reactivating Gravatar in app.ini has no effect

### ISSUE THREAD

**Issue by distinguiert** [go-gitea/gitea#14370]
- Gitea version (or commit ref): 1.13.1 (download package from github)
- Git version: 
- Operating system: Debian Buster (amd64)
  
  
  
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
- Log gist:

## Description

I deactivated Gravatar during the installation process in the web-front-end and found myself unable to reactivate it. Setting "Disable Gravatar" to false and restart gitea is neither recognized in the admin section of the web-front-end nor does it has any effect. Any other change in app.ini, like changing the instance title, is recognized.

**Comment by noerw** [comment]
This setting is overridden by `OFFLINE_MODE` (if true, gravatar will stay disabled) and `ENABLE_FEDERATED_AVATAR`, try to set
```ini
[server]
OFFLINE_MODE = false

[picture]
ENABLE_FEDERATE_AVATAR = true
DISABLE_GRAVATAR = false
```

**Comment by zeripath** [comment]
I think the above comment explains how to solve the issue. If this doesn't work please reopen the issue.
