### ISSUE TITLE
Proposal: Decentralization of gitea repositories?

### ISSUE THREAD

**Issue by Kreyren** [go-gitea/gitea#14380]
Inspired by zeronet's git service proposing to implement decentralization of repositories so that the instance doesn't have to host everything by themselves.

**Comment by techknowlogick** [comment]
For hosting repos not on the users current instance we have issues open about federation this would be our desired approach.

**Comment by 6543** [comment]
just a side note ... if you look on a repo at "Git Center" it download the whole thing ...

@Kreyren 
so it's not a decentralized file storing in that sence ... and there is a consensus to adopt ForgeFed (#14186, ...) at some point ...

**Comment by Kreyren** [comment]
Why not implementing or at least tracking this interpretation as well? Could be configurable thing

**Comment by 6543** [comment]
1.4k issues ...
