### ISSUE TITLE
[Feature] Custom order of issues

### ISSUE THREAD

**Issue by lyz-code** [go-gitea/gitea#14382]
Hi, we're currently managing around 200 issues on a gitea repository and it's getting increasingly difficult to manage which issues are more important than others. We're currently using labels like `Priority: High` to give us some level of granularity, but it would be easier if we could sort them manually to have a priorized backlog.

If #11161 get's merged, we could do it in a project with only one column if the issues are shown one above the other.

Or maybe currently there is a way to do it that I'm unaware of.

Thanks

**Comment by delvh** [comment]
Isn't this issue a duplicate of #14377?

**Comment by lyz-code** [comment]
Indeed it is, sorry for the duplication
