### ISSUE TITLE
Unable to set file size for drag-n-drop uploading

### ISSUE THREAD

**Issue by plaidshirtakos** [go-gitea/gitea#14381]
- Gitea version (or commit ref): 1.8.3
- Git version: 2.17.1
- Operating system: Ubuntu 18.04.5 LTS,  4.15.0-126-generic
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ x ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ x ] No
- Log gist:

## Description
Unable to upload file, that is bigger than 3 MB. I have set FILE_MAX_SIZE parameter(https://docs.gitea.io/en-us/config-cheat-sheet/) in /etc/gitea/app.ini config file to 20, but it doesn't have any effect.

**Comment by silverwind** [comment]
I think you need `attachment.MAX_SIZE` for this.

**Comment by lunny** [comment]
Hi, v1.8.3 is outdated. Please upgrade your Gitea and try again.

**Comment by plaidshirtakos** [comment]
I have already tried to update version(changing binary), but it didn't work. I got error 502 after service restart, I was unable to fix it.

**Comment by zeripath** [comment]
if you give us some logs we might be able to help you.
