### ISSUE TITLE
Login 500 after gitea installation

### ISSUE THREAD

**Issue by mirroro** [go-gitea/gitea#14393]
- Gitea version (or commit ref):1.13.0,1.13.1
- Git version:2.25.1
- Operating system:ubuntu20.04 lts
  - [ ] PostgreSQL
  - [ x] MySQL 
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
- Log gist:

## Description
2021/01/19 08:19:22 ...c/net/http/server.go:3095:logf() [I] http: superfluous response.WriteHeader call from code.gitea.io/gitea/vendor/gitea.com/macaron/macaron.(*responseWriter).WriteHeader (response_writer.go:60)
[Macaron] 2021-01-19 08:19:22: Completed GET / 500 Internal Server Error in 55.284196671s
^C2021/01/19 08:19:31 ...eful/manager_unix.go:124:handleSignals() [W] PID 5323. Received SIGINT. Shutting down...
2021/01/19 08:19:31 cmd/web.go:208:runWeb() [I] HTTP Listener: 0.0.0.0:3000 Closed
2021/01/19 08:19:31 ...eful/server_hooks.go:47:doShutdown() [I] PID: 5323 Listener ([::]:3000) closed.
2021/01/19 08:19:31 .../graceful/manager.go:217:doHammerTime() [W] Setting Hammer condition
2021/01/19 08:19:32 .../graceful/manager.go:231:doTerminate() [W] Terminating
2021/01/19 08:19:32 ...er/issues/indexer.go:169:2() [I] PID: 5323 Issue Indexer closed
2021/01/19 08:19:32 cmd/web.go:210:runWeb() [I] PID: 5323 Gitea Web Finished

mysql:  utf8mb4  utf8mb4_0900_ai_ci
...

**Comment by 6543** [comment]
@caifenglin could you enable logging in a more verbose mode?

https://docs.gitea.io/en-us/logging-configuration/

**Comment by caifenglin** [comment]
./gitea web
2021/01/20 13:11:20 cmd/web.go:108:runWeb() [I] Starting Gitea on PID: 10814
2021/01/20 13:11:20 ...dules/setting/git.go:91:newGit() [I] Git Version: 2.25.1, Wire Protocol Version 2 Enabled
2021/01/20 13:11:20 routers/init.go:130:GlobalInit() [T] AppPath: /opt/Gitea/gitea
2021/01/20 13:11:20 routers/init.go:131:GlobalInit() [T] AppWorkPath: /opt/Gitea
2021/01/20 13:11:20 routers/init.go:132:GlobalInit() [T] Custom path: /opt/Gitea/custom
2021/01/20 13:11:20 routers/init.go:133:GlobalInit() [T] Log path: /opt/Gitea/log
2021/01/20 13:11:21 ...dules/setting/log.go:297:newLogService() [I] Gitea v1.13.1 built with GNU Make 4.1, go1.15.6 : bindata, sqlite, sqlite_unlock_notify
2021/01/20 13:11:21 ...dules/setting/log.go:343:newLogService() [I] Gitea Log Mode: Console(Console:debug)
2021/01/20 13:11:21 ...dules/setting/log.go:249:generateNamedLogger() [I] Macaron Log: Console(console:debug)
2021/01/20 13:11:21 ...dules/setting/log.go:249:generateNamedLogger() [I] Router Log: Console(console:debug)
2021/01/20 13:11:21 ...les/setting/cache.go:70:newCacheService() [I] Cache Service Enabled
2021/01/20 13:11:21 ...les/setting/cache.go:81:newCacheService() [I] Last Commit Cache Service Enabled
2021/01/20 13:11:21 ...s/setting/session.go:63:newSessionService() [I] Session Service Enabled
2021/01/20 13:11:21 ...es/setting/mailer.go:109:newMailService() [I] Mail Service Enabled
2021/01/20 13:11:21 ...es/setting/mailer.go:131:newNotifyMailService() [I] Notify Mail Service Enabled
2021/01/20 13:11:21 ...s/storage/storage.go:151:initAttachments() [I] Initialising Attachment storage with type: 
2021/01/20 13:11:21 ...les/storage/local.go:43:NewLocalStorage() [I] Creating new Local Storage at /opt/Gitea/data/attachments
2021/01/20 13:11:21 ...s/storage/storage.go:145:initAvatars() [I] Initialising Avatar storage with type: 
2021/01/20 13:11:21 ...les/storage/local.go:43:NewLocalStorage() [I] Creating new Local Storage at /opt/Gitea/data/avatars
2021/01/20 13:11:21 ...s/storage/storage.go:163:initRepoAvatars() [I] Initialising Repository Avatar storage with type: 
2021/01/20 13:11:21 ...les/storage/local.go:43:NewLocalStorage() [I] Creating new Local Storage at /opt/Gitea/data/repo-avatars
2021/01/20 13:11:21 ...s/storage/storage.go:157:initLFS() [I] Initialising LFS storage with type: 
2021/01/20 13:11:21 ...les/storage/local.go:43:NewLocalStorage() [I] Creating new Local Storage at /opt/Gitea/data/lfs
2021/01/20 13:11:21 ...ueue_disk_channel.go:137:Run() [D] PersistableChannelQueue: push_update Starting
2021/01/20 13:11:21 ...ue/queue_bytefifo.go:95:Run() [D] level: push_update-level Starting
2021/01/20 13:11:21 ...ueue_disk_channel.go:137:Run() [D] PersistableChannelQueue: mail Starting
2021/01/20 13:11:21 ...ue/queue_bytefifo.go:95:Run() [D] level: mail-level Starting
2021/01/20 13:11:21 ...ueue_disk_channel.go:137:Run() [D] PersistableChannelQueue: notification-service Starting
2021/01/20 13:11:21 ...ue/queue_bytefifo.go:95:Run() [D] level: notification-service-level Starting
2021/01/20 13:11:21 routers/init.go:75:initDBEngine() [I] Beginning ORM engine initialization.
2021/01/20 13:11:21 routers/init.go:82:initDBEngine() [I] ORM engine initialization attempt #1/10...
2021/01/20 13:11:21 ...rm/session_schema.go:25:Ping() [I] PING DATABASE mysql
2021/01/20 13:11:21 routers/init.go:145:GlobalInit() [I] ORM engine initialization successful!
2021/01/20 13:11:21 ...odules/cron/tasks.go:120:RegisterTask() [D] Registering task: update_mirrors
2021/01/20 13:11:21 ...odules/cron/tasks.go:120:RegisterTask() [D] Registering task: repo_health_check
2021/01/20 13:11:21 ...odules/cron/tasks.go:120:RegisterTask() [D] Registering task: check_repo_stats
2021/01/20 13:11:21 ...odules/cron/tasks.go:120:RegisterTask() [D] Registering task: archive_cleanup
2021/01/20 13:11:21 ...odules/cron/tasks.go:120:RegisterTask() [D] Registering task: sync_external_users
2021/01/20 13:11:21 ...odules/cron/tasks.go:120:RegisterTask() [D] Registering task: deleted_branches_cleanup
2021/01/20 13:11:21 ...odules/cron/tasks.go:120:RegisterTask() [D] Registering task: update_migration_poster_id
2021/01/20 13:11:21 ...odules/cron/tasks.go:120:RegisterTask() [D] Registering task: delete_inactive_accounts
2021/01/20 13:11:21 ...odules/cron/tasks.go:120:RegisterTask() [D] Registering task: delete_repo_archives
2021/01/20 13:11:21 ...odules/cron/tasks.go:120:RegisterTask() [D] Registering task: git_gc_repos
2021/01/20 13:11:21 ...odules/cron/tasks.go:120:RegisterTask() [D] Registering task: resync_all_sshkeys
2021/01/20 13:11:21 ...odules/cron/tasks.go:120:RegisterTask() [D] Registering task: resync_all_sshprincipals
2021/01/20 13:11:21 ...odules/cron/tasks.go:120:RegisterTask() [D] Registering task: resync_all_hooks
2021/01/20 13:11:21 ...odules/cron/tasks.go:120:RegisterTask() [D] Registering task: reinit_missing_repos
2021/01/20 13:11:21 ...odules/cron/tasks.go:120:RegisterTask() [D] Registering task: delete_missing_repos
2021/01/20 13:11:21 ...odules/cron/tasks.go:120:RegisterTask() [D] Registering task: delete_generated_repository_avatars
2021/01/20 13:11:21 ...er/issues/indexer.go:142:func2() [I] PID 10814: Initializing Issue Indexer: bleve
2021/01/20 13:11:21 ...er/issues/indexer.go:171:func2() [D] Created Bleve Indexer
2021/01/20 13:11:21 ...er/issues/indexer.go:221:func3() [I] Issue Indexer Initialization took 4.471717ms
2021/01/20 13:11:21 ...ue/queue_bytefifo.go:95:Run() [D] level: issue_indexer Starting
2021/01/20 13:11:21 ...xer/stats/indexer.go:38:populateRepoIndexer() [I] Populating the repo stats indexer with existing repositories
2021/01/20 13:11:21 ...ueue_disk_channel.go:157:Run() [D] PersistableChannelUniqueQueue: repo_stats_update Starting
2021/01/20 13:11:21 ...ue/queue_bytefifo.go:95:Run() [D] unique-level: repo_stats_update-level Starting
2021/01/20 13:11:21 ...ueue_disk_channel.go:157:Run() [D] PersistableChannelUniqueQueue: pr_patch_checker Starting
2021/01/20 13:11:21 ...ue/queue_bytefifo.go:95:Run() [D] unique-level: pr_patch_checker-level Starting
2021/01/20 13:11:21 routers/init.go:174:GlobalInit() [I] SQLite3 Supported
2021/01/20 13:11:21 routers/init.go:56:checkRunMode() [I] Run Mode: Production
2021/01/20 13:11:21 ...ueue_disk_channel.go:137:Run() [D] PersistableChannelQueue: task Starting
2021/01/20 13:11:21 ...ue/queue_bytefifo.go:95:Run() [D] level: task-level Starting
2021/01/20 13:11:22 cmd/web.go:163:runWeb() [I] Listen: http://0.0.0.0:10000
2021/01/20 13:11:22 cmd/web.go:166:runWeb() [I] LFS server enabled
2021/01/20 13:11:22 ...s/graceful/server.go:55:NewServer() [I] Starting new server: tcp:0.0.0.0:10000 on PID: 10814
2021/01/20 13:11:22 ...s/graceful/server.go:66:func1() [D] Starting server on tcp:0.0.0.0:10000 (PID: 10814)
2021/01/20 13:11:28 Started GET / for 127.0.0.1
2021/01/20 13:11:28 ...s/context/context.go:332:func1() [D] Session ID: 267ccd997a695ac2
2021/01/20 13:11:28 ...s/context/context.go:333:func1() [D] CSRF Token: WRDg5_TXbYaBcyrec2vCAM6b2906MTYxMTExODU1NzY5NDAzMzQ4MA
[mysql] 2021/01/20 13:11:28 packets.go:36: unexpected EOF
2021/01/20 13:11:28 routers/user/home.go:60:getDashboardContextUser() [E] GetOrganizations: invalid connection
2021/01/20 13:11:28 ...s/context/context.go:139:HTML() [D] Template: status/500
2021/01/20 13:11:28 ...user/notification.go:38:func1() [E] GetNotificationCount: dial tcp 127.0.0.1:3306: connect: connection refused
2021/01/20 13:11:28 ...s/context/context.go:139:HTML() [D] Template: status/500
2021/01/20 13:11:28 ...user/notification.go:38:func1() [E] GetNotificationCount: dial tcp 127.0.0.1:3306: connect: connection refused
2021/01/20 13:11:28 ...s/context/context.go:139:HTML() [D] Template: status/500
2021/01/20 13:11:28 ...user/notification.go:38:func1() [E] GetNotificationCount: dial tcp 127.0.0.1:3306: connect: connection refused
2021/01/20 13:11:28 ...s/context/context.go:139:HTML() [D] Template: status/500
2021/01/20 13:11:28 ...user/notification.go:38:func1() [E] GetNotificationCount: dial tcp 127.0.0.1:3306: connect: connection refused
2021/01/20 13:11:28 ...s/context/context.go:139:HTML() [D] Template: status/500
2021/01/20 13:11:28 ...user/notification.go:38:func1() [E] GetNotificationCount: dial tcp 127.0.0.1:3306: connect: connection refused
2021/01/20 13:11:28 ...s/context/context.go:139:HTML() [D] Template: status/500
2021/01/20 13:11:28 ...user/notification.go:38:func1() [E] GetNotificationCount: dial tcp 127.0.0.1:3306: connect: connection refused
2021/01/20 13:11:28 ...s/context/context.go:139:HTML() [D] Template: status/500
2021/01/20 13:11:28 ...user/notification.go:38:func1() [E] GetNotificationCount: dial tcp 127.0.0.1:3306: connect: connection refused
2021/01/20 13:11:28 ...s/context/context.go:139:HTML() [D] Template: status/500
2021/01/20 13:11:28 ...user/notification.go:38:func1() [E] GetNotificationCount: dial tcp 127.0.0.1:3306: connect: connection refused
2021/01/20 13:11:28 ...s/context/context.go:139:HTML() [D] Template: status/500
2021/01/20 13:11:28 ...user/notification.go:38:func1() [E] GetNotificationCount: dial tcp 127.0.0.1:3306: connect: connection refused
2021/01/20 13:11:28 ...s/context/context.go:139:HTML() [D] Template: status/500
2021/01/20 13:11:28 ...user/notification.go:38:func1() [E] GetNotificationCount: dial tcp 127.0.0.1:3306: connect: connection refused
2021/01/20 13:11:28 ...s/context/context.go:139:HTML() [D] Template: status/500
2021/01/20 13:11:28 ...user/notification.go:38:func1() [E] GetNotificationCount: dial tcp 127.0.0.1:3306: connect: connection refused
2021/01/20 13:11:28 ...s/context/context.go:139:HTML() [D] Template: status/500
2021/01/20 13:11:28 ...user/notification.go:38:func1() [E] GetNotificationCount: dial tcp 127.0.0.1:3306: connect: connection refused
2021/01/20 13:11:28 ...s/context/context.go:139:HTML() [D] Template: status/500
2021/01/20 13:11:28 ...user/notification.go:38:func1() [E] GetNotificationCount: dial tcp 127.0.0.1:3306: connect: connection refused
2021/01/20 13:11:28 ...s/context/context.go:139:HTML() [D] Template: status/500
2021/01/20 13:11:28 ...user/notification.go:38:func1() [E] GetNotificationCount: dial tcp 127.0.0.1:3306: connect: connection refused
2021/01/20 13:11:28 ...s/context/context.go:139:HTML() [D] Template: status/500
2021/01/20 13:11:28 ...user/notification.go:38:func1() [E] GetNotificationCount: dial tcp 127.0.0.1:3306: connect: connection refused
2021/01/20 13:11:28 ...s/context/context.go:139:HTML() [D] Template: status/500
2021/01/20 13:11:28 ...user/notification.go:38:func1() [E] GetNotificationCount: dial tcp 127.0.0.1:3306: connect: connection refused
2021/01/20 13:11:28 ...s/context/context.go:139:HTML() [D] Template: status/500
2021/01/20 13:11:28 ...user/notification.go:38:func1() [E] GetNotificationCount: dial tcp 127.0.0.1:3306: connect: connection refused
2021/01/20 13:11:28 ...s/context/context.go:139:HTML() [D] Template: status/500
2021/01/20 13:11:28 ...user/notification.go:38:func1() [E] GetNotificationCount: dial tcp 127.0.0.1:3306: connect: connection refused
2021/01/20 13:11:28 ...s/context/context.go:139:HTML() [D] Template: status/500
2021/01/20 13:11:28 ...user/notification.go:38:func1() [E] GetNotificationCount: dial tcp 127.0.0.1:3306: connect: connection refused
2021/01/20 13:11:28 ...s/context/context.go:139:HTML() [D] Template: status/500
2021/01/20 13:11:28 ...user/notification.go:38:func1() [E] GetNotificationCount: dial tcp 127.0.0.1:3306: connect: connection refused
2021/01/20 13:11:28 ...s/context/context.go:139:HTML() [D] Template: status/500
2021/01/20 13:11:28 ...user/notification.go:38:func1() [E] GetNotificationCount: dial tcp 127.0.0.1:3306: connect: connection refused
2021/01/20 13:11:28 ...s/context/context.go:139:HTML() [D] Template: status/500
2021/01/20 13:11:28 ...user/notification.go:38:func1() [E] GetNotificationCount: dial tcp 127.0.0.1:3306: connect: connection refused
2021/01/20 13:11:28 ...s/context/context.go:139:HTML() [D] Template: status/500
2021/01/20 13:11:28 ...user/notification.go:38:func1() [E] GetNotificationCount: dial tcp 127.0.0.1:3306: connect: connection refused
2021/01/20 13:11:28 ...s/context/context.go:139:HTML() [D] Template: status/500
2021/01/20 13:11:28 ...user/notification.go:38:func1() [E] GetNotificationCount: dial tcp 127.0.0.1:3306: connect: connection refused
2021/01/20 13:11:28 ...s/context/context.go:139:HTML() [D] Template: status/500
2021/01/20 13:11:28 ...user/notification.go:38:func1() [E] GetNotificationCount: dial tcp 127.0.0.1:3306: connect: connection refused
2021/01/20 13:11:28 ...s/context/context.go:139:HTML() [D] Template: status/500
2021/01/20 13:11:28 ...user/notification.go:38:func1() [E] GetNotificationCount: dial tcp 127.0.0.1:3306: connect: connection refused
2021/01/20 13:11:28 ...s/context/context.go:139:HTML() [D] Template: status/500
2021/01/20 13:11:28 ...user/notification.go:38:func1() [E] GetNotificationCount: dial tcp 127.0.0.1:3306: connect: connection refused
2021/01/20 13:11:28 ...s/context/context.go:139:HTML() [D] Template: status/500
2021/01/20 13:11:28 ...user/notification.go:38:func1() [E] GetNotificationCount: dial tcp 127.0.0.1:3306: connect: connection refused
2021/01/20 13:11:28 ...s/context/context.go:139:HTML() [D] Template: status/500
2021/01/20 13:11:28 ...user/notification.go:38:func1() [E] GetNotificationCount: dial tcp 127.0.0.1:3306: connect: connection refused
2021/01/20 13:11:28 ...s/context/context.go:139:HTML() [D] Template: status/500
2021/01/20 13:11:28 ...user/notification.go:38:func1() [E] GetNotificationCount: dial tcp 127.0.0.1:3306: connect: connection refused
2021/01/20 13:11:28 ...s/context/context.go:139:HTML() [D] Template: status/500
2021/01/20 13:11:28 ...user/notification.go:38:func1() [E] GetNotificationCount: dial tcp 127.0.0.1:3306: connect: connection refused
2021/01/20 13:11:28 ...s/context/context.go:139:HTML() [D] Template: status/500
2021/01/20 13:11:28 ...user/notification.go:38:func1() [E] GetNotificationCount: dial tcp 127.0.0.1:3306: connect: connection refused
2021/01/20 13:11:28 ...s/context/context.go:139:HTML() [D] Template: status/500
2021/01/20 13:11:28 ...user/notification.go:38:func1() [E] GetNotificationCount: dial tcp 127.0.0.1:3306: connect: connection refused
2021/01/20 13:11:28 ...s/context/context.go:139:HTML() [D] Template: status/500
2021/01/20 13:11:28 ...user/notification.go:38:func1() [E] GetNotificationCount: dial tcp 127.0.0.1:3306: connect: connection refused
2021/01/20 13:11:28 ...s/context/context.go:139:HTML() [D] Template: status/500
2021/01/20 13:11:28 ...user/notification.go:38:func1() [E] GetNotificationCount: dial tcp 127.0.0.1:3306: connect: connection refused
2021/01/20 13:11:28 ...s/context/context.go:139:HTML() [D] Template: status/500
2021/01/20 13:11:28 ...user/notification.go:38:func1() [E] GetNotificationCount: dial tcp 127.0.0.1:3306: connect: connection refused
2021/01/20 13:11:28 ...s/context/context.go:139:HTML() [D] Template: status/500
2021/01/20 13:11:28 ...user/notification.go:38:func1() [E] GetNotificationCount: dial tcp 127.0.0.1:3306: connect: connection refused
2021/01/20 13:11:28 ...s/context/context.go:139:HTML() [D] Template: status/500
2021/01/20 13:11:28 ...user/notification.go:38:func1() [E] GetNotificationCount: dial tcp 127.0.0.1:3306: connect: connection refused
2021/01/20 13:11:28 ...s/context/context.go:139:HTML() [D] Template: status/500
2021/01/20 13:11:28 ...user/notification.go:38:func1() [E] GetNotificationCount: dial tcp 127.0.0.1:3306: connect: connection refused
2021/01/20 13:11:28 ...s/context/context.go:139:HTML() [D] Template: status/500
2021/01/20 13:11:28 ...user/notification.go:38:func1() [E] GetNotificationCount: dial tcp 127.0.0.1:3306: connect: connection refused
2021/01/20 13:11:28 ...s/context/context.go:139:HTML() [D] Template: status/500
2021/01/20 13:11:28 ...user/notification.go:38:func1() [E] GetNotificationCount: dial tcp 127.0.0.1:3306: connect: connection refused
2021/01/20 13:11:28 ...s/context/context.go:139:HTML() [D] Template: status/500
2021/01/20 13:11:28 ...user/notification.go:38:func1() [E] GetNotificationCount: dial tcp 127.0.0.1:3306: connect: connection refused
2021/01/20 13:11:28 ...s/context/context.go:139:HTML() [D] Template: status/500
2021/01/20 13:11:28 ...user/notification.go:38:func1() [E] GetNotificationCount: dial tcp 127.0.0.1:3306: connect: connection refused
2021/01/20 13:11:28 ...s/context/context.go:139:HTML() [D] Template: status/500
2021/01/20 13:11:28 ...user/notification.go:38:func1() [E] GetNotificationCount: dial tcp 127.0.0.1:3306: connect: connection refused
2021/01/20 13:11:28 ...s/context/context.go:139:HTML() [D] Template: status/500
2021/01/20 13:11:28 ...user/notification.go:38:func1() [E] GetNotificationCount: dial tcp 127.0.0.1:3306: connect: connection refused
2021/01/20 13:11:28 ...s/context/context.go:139:HTML() [D] Template: status/500
2021/01/20 13:11:28 ...user/notification.go:38:func1() [E] GetNotificationCount: dial tcp 127.0.0.1:3306: connect: connection refused
2021/01/20 13:11:28 ...s/context/context.go:139:HTML() [D] Template: status/500
2021/01/20 13:11:28 ...user/notification.go:38:func1() [E] GetNotificationCount: dial tcp 127.0.0.1:3306: connect: connection refused
2021/01/20 13:11:28 ...s/context/context.go:139:HTML() [D] Template: status/500
2021/01/20 13:11:28 ...user/notification.go:38:func1() [E] GetNotificationCount: dial tcp 127.0.0.1:3306: connect: connection refused
2021/01/20 13:11:28 ...s/context/context.go:139:HTML() [D] Template: status/500
2021/01/20 13:11:28 ...user/notification.go:38:func1() [E] GetNotificationCount: dial tcp 127.0.0.1:3306: connect: connection refused
2021/01/20 13:11:28 ...s/context/context.go:139:HTML() [D] Template: status/500
2021/01/20 13:11:28 ...user/notification.go:38:func1() [E] GetNotificationCount: dial tcp 127.0.0.1:3306: connect: connection refused
2021/01/20 13:11:28 ...s/context/context.go:139:HTML() [D] Template: status/500
2021/01/20 13:11:28 ...user/notification.go:38:func1() [E] GetNotificationCount: dial tcp 127.0.0.1:3306: connect: connection refused
2021/01/20 13:11:28 ...s/context/context.go:139:HTML() [D] Template: status/500
2021/01/20 13:11:28 ...user/notification.go:38:func1() [E] GetNotificationCount: dial tcp 127.0.0.1:3306: connect: connection refused
2021/01/20 13:11:28 ...s/context/context.go:139:HTML() [D] Template: status/500
2021/01/20 13:11:28 ...user/notification.go:38:func1() [E] GetNotificationCount: dial tcp 127.0.0.1:3306: connect: connection refused
2021/01/20 13:11:28 ...s/context/context.go:139:HTML() [D] Template: status/500
2021/01/20 13:11:28 ...user/notification.go:38:func1() [E] GetNotificationCount: dial tcp 127.0.0.1:3306: connect: connection refused
2021/01/20 13:11:28 ...s/context/context.go:139:HTML() [D] Template: status/500
2021/01/20 13:11:28 ...user/notification.go:38:func1() [E] GetNotificationCount: dial tcp 127.0.0.1:3306: connect: connection refused
2021/01/20 13:11:28 ...s/context/context.go:139:HTML() [D] Template: status/500
2021/01/20 13:11:28 ...user/notification.go:38:func1() [E] GetNotificationCount: dial tcp 127.0.0.1:3306: connect: connection refused
2021/01/20 13:11:28 ...s/context/context.go:139:HTML() [D] Template: status/500
2021/01/20 13:11:28 ...user/notification.go:38:func1() [E] GetNotificationCount: dial tcp 127.0.0.1:3306: connect: connection refused
2021/01/20 13:11:28 ...s/context/context.go:139:HTML() [D] Template: status/500
2021/01/20 13:11:28 ...user/notification.go:38:func1() [E] GetNotificationCount: dial tcp 127.0.0.1:3306: connect: connection refused
2021/01/20 13:11:28 ...s/context/context.go:139:HTML() [D] Template: status/500
2021/01/20 13:11:28 ...user/notification.go:38:func1() [E] GetNotificationCount: dial tcp 127.0.0.1:3306: connect: connection refused
2021/01/20 13:11:28 ...s/context/context.go:139:HTML() [D] Template: status/500
2021/01/20 13:11:28 ...user/notification.go:38:func1() [E] GetNotificationCount: dial tcp 127.0.0.1:3306: connect: connection refused
2021/01/20 13:11:28 ...s/context/context.go:139:HTML() [D] Template: status/500
2021/01/20 13:11:28 ...user/notification.go:38:func1() [E] GetNotificationCount: dial tcp 127.0.0.1:3306: connect: connection refused
2021/01/20 13:11:28 ...s/context/context.go:139:HTML() [D] Template: status/500
2021/01/20 13:11:28 ...user/notification.go:38:func1() [E] GetNotificationCount: dial tcp 127.0.0.1:3306: connect: connection refused
2021/01/20 13:11:28 ...s/context/context.go:139:HTML() [D] Template: status/500
2021/01/20 13:11:28 ...user/notification.go:38:func1() [E] GetNotificationCount: dial tcp 127.0.0.1:3306: connect: connection refused
2021/01/20 13:11:28 ...s/context/context.go:139:HTML() [D] Template: status/500
2021/01/20 13:11:28 ...user/notification.go:38:func1() [E] GetNotificationCount: dial tcp 127.0.0.1:3306: connect: connection refused
2021/01/20 13:11:28 ...s/context/context.go:139:HTML() [D] Template: status/500
2021/01/20 13:11:28 ...user/notification.go:38:func1() [E] GetNotificationCount: dial tcp 127.0.0.1:3306: connect: connection refused
2021/01/20 13:11:28 ...s/context/context.go:139:HTML() [D] Template: status/500
2021/01/20 13:11:28 ...user/notification.go:38:func1() [E] GetNotificationCount: dial tcp 127.0.0.1:3306: connect: connection refused
2021/01/20 13:11:28 ...s/context/context.go:139:HTML() [D] Template: status/500
2021/01/20 13:11:28 ...user/notification.go:38:func1() [E] GetNotificationCount: dial tcp 127.0.0.1:3306: connect: connection refused
2021/01/20 13:11:28 ...s/context/context.go:139:HTML() [D] Template: status/500
2021/01/20 13:11:28 ...user/notification.go:38:func1() [E] GetNotificationCount: dial tcp 127.0.0.1:3306: connect: connection refused
2021/01/20 13:11:28 ...s/context/context.go:139:HTML() [D] Template: status/500
2021/01/20 13:11:28 ...user/notification.go:38:func1() [E] GetNotificationCount: dial tcp 127.0.0.1:3306: connect: connection refused
2021/01/20 13:11:28 ...s/context/context.go:139:HTML() [D] Template: status/500
2021/01/20 13:11:28 ...user/notification.go:38:func1() [E] GetNotificationCount: dial tcp 127.0.0.1:3306: connect: connection refused
2021/01/20 13:11:28 ...s/context/context.go:139:HTML() [D] Template: status/500
2021/01/20 13:11:28 ...user/notification.go:38:func1() [E] GetNotificationCount: dial tcp 127.0.0.1:3306: connect: connection refused
2021/01/20 13:11:28 ...s/context/context.go:139:HTML() [D] Template: status/500
2021/01/20 13:11:28 ...user/notification.go:38:func1() [E] GetNotificationCount: dial tcp 127.0.0.1:3306: connect: connection refused
2021/01/20 13:11:28 ...s/context/context.go:139:HTML() [D] Template: status/500
2021/01/20 13:11:28 ...user/notification.go:38:func1() [E] GetNotificationCount: dial tcp 127.0.0.1:3306: connect: connection refused
2021/01/20 13:11:28 ...s/context/context.go:139:HTML() [D] Template: status/500
2021/01/20 13:11:28 ...user/notification.go:38:func1() [E] GetNotificationCount: dial tcp 127.0.0.1:3306: connect: connection refused
2021/01/20 13:11:28 ...s/context/context.go:139:HTML() [D] Template: status/500
2021/01/20 13:11:28 ...user/notification.go:38:func1() [E] GetNotificationCount: dial tcp 127.0.0.1:3306: connect: connection refused
2021/01/20 13:11:28 ...s/context/context.go:139:HTML() [D] Template: status/500
2021/01/20 13:11:28 ...user/notification.go:38:func1() [E] GetNotificationCount: dial tcp 127.0.0.1:3306: connect: connection refused
2021/01/20 13:11:28 ...s/context/context.go:139:HTML() [D] Template: status/500
2021/01/20 13:11:28 ...user/notification.go:38:func1() [E] GetNotificationCount: dial tcp 127.0.0.1:3306: connect: connection refused
2021/01/20 13:11:28 ...s/context/context.go:139:HTML() [D] Template: status/500
2021/01/20 13:11:28 ...user/notification.go:38:func1() [E] GetNotificationCount: dial tcp 127.0.0.1:3306: connect: connection refused
2021/01/20 13:11:28 ...s/context/context.go:139:HTML() [D] Template: status/500
2021/01/20 13:11:28 ...user/notification.go:38:func1() [E] GetNotificationCount: dial tcp 127.0.0.1:3306: connect: connection refused
2021/01/20 13:11:28 ...s/context/context.go:139:HTML() [D] Template: status/500
2021/01/20 13:11:28 ...user/notification.go:38:func1() [E] GetNotificationCount: dial tcp 127.0.0.1:3306: connect: connection refused
2021/01/20 13:11:28 ...s/context/context.go:139:HTML() [D] Template: status/500
2021/01/20 13:11:28 ...user/notification.go:38:func1() [E] GetNotificationCount: dial tcp 127.0.0.1:3306: connect: connection refused
2021/01/20 13:11:28 ...s/context/context.go:139:HTML() [D] Template: status/500

**Comment by caifenglin** [comment]
mysql Server version: 8.0.22 MySQL Community Server - GPL

**Comment by caifenglin** [comment]
Hello, what's the reason and how to solve it

**Comment by lunny** [comment]
I think that's because you input wrong database information when installation?

**Comment by caifenglin** [comment]
I started to use utf8mb4 to report an error, and then I couldn't use utf8

**Comment by caifenglin** [comment]
I think we should upgrade the MySQL driver. Is my version of MySQL too new

**Comment by zeripath** [comment]
utf8mb4 is irrelevant here and you should stick with it. 

The problem is you have the incorrect database configuration. 

You need to set within your app.ini `[database]` section the correct values for (at least):

DB_TYPE
HOST
NAME
USER
PASSWD

https://docs.gitea.io/en-us/config-cheat-sheet/#database-database

It would be likely more appropriate for you to ask for help on our discord.

**Comment by zeripath** [comment]
Due to lack of further comments I'm closing this issue. @mirroro if you need further help please reopen this issue or come to discord to ask for help.
