### ISSUE TITLE
[UI] Comment dropdown not aligned

### ISSUE THREAD

**Issue by kdumontnu** [go-gitea/gitea#14404]
- Gitea version (or commit ref): 1.14.0+dev-566-ge05670da8 (latest master)
- Git version: 
- Operating system:
Windows, Chrome + Firefox
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes: https://try.gitea.io/kdumontnu/testRepo/issues/1
  - [ ] No

## Description

Dropdown for comments (and perhaps elsewhere?) are not aligned with the parent element.

Should be a simple fix of adding `top right` to the semantic class definition.

## Screenshots

![image](https://user-images.githubusercontent.com/12700993/105085669-45850e80-5a55-11eb-9c6f-4d244b47e2da.png)

**Comment by zeripath** [comment]
this one could be solved with "top left" actually, but the smiley one needs "top right" which breaks because of our less abuse of .right.

We'd need to do some javascript or less changes I think or figure out how to set this some other way

**Comment by kdumontnu** [comment]
> "top right" breaks because of our less abuse of .right.

Yeah, I found that out the hard way :/

I like the look of `right` better than `left` and it's consistent.

I have a patch-fix using `.right:not(.dropdown)` in less, but would like to improve it
