### ISSUE TITLE
[doc] unclear guidance on the https server setup

### ISSUE THREAD

**Issue by cdluminate** [go-gitea/gitea#14401]
In the documentation (https://docs.gitea.io/en-us/https-setup/), it is said that the configuration should look like this to get https working:

```
[server]
PROTOCOL  = https
ROOT_URL  = https://git.example.com:3000/
HTTP_PORT = 3000
CERT_FILE = cert.pem
KEY_FILE  = key.pem
```

Then it took me quite a while to get it working until I realized that the values for the `CERT_FILE` and `KEY_FILE` should be absolute paths instead of the literal relative path.

**Comment by 6543** [comment]
whould this had helped you ?
```diff
-CERT_FILE = cert.pem
-KEY_FILE  = key.pem
+CERT_FILE = /path/cert.pem
+KEY_FILE  = /path/key.pem
```
without  absolute it's relative to $CUSTOM_ROOT ...

**Comment by cdluminate** [comment]
@6543 Yes. I think that `/path/` hint is enough to help people understand it correctly. And probably `CUSTOM_ROOT` should be documented somewhere as well.

**Comment by 6543** [comment]
I have to correct myselve ... it's called `GITEA_CUSTOM` ... @cdluminate would you mind to create/propose a pull for the docs?

(It's generated by hugo, you find the files at [/docs/](https://github.com/go-gitea/gitea/tree/master/docs)
