### ISSUE TITLE
FR: "Close with comment" instead of "close" for Issues

### ISSUE THREAD

**Issue by pat-s** [go-gitea/gitea#14407]
I like how GitHub changes the "close" button in issues when there is content in the comment box from "close" to "close with comment".

No idea how hard that would be to implement in such a dynamic way but I got quite used to it lately and was unsure what would happen in Gitea if I entered a comment and hit the "close" button in the next step (which does the right thing, i.e. "close with comment").

<img width="249" alt="image" src="https://user-images.githubusercontent.com/8430564/105141766-f5ac5300-5af9-11eb-86c8-7e34440cb64a.png">

**Comment by a1012112796** [comment]
It's an exist feature, But seem has bug now..

https://github.com/go-gitea/gitea/blob/1c230f69d9951af1174f2956064f18e2d135723d/web_src/js/index.js#L1124-L1132
/cc @silverwind

**Comment by 6543** [comment]
@pat-s witch version did you test?

**Comment by pat-s** [comment]
1.13.1
