### ISSUE TITLE
Will TOC tags be supported in Markdown?

### ISSUE THREAD

**Issue by a96219** [go-gitea/gitea#14411]
Or is there another solution?

**Comment by noerw** [comment]
What are TOC tags?
If it's not standard syntax in a popular markdown flavour, it probably won't be supported.

**Comment by techknowlogick** [comment]
If you'd like to modify how the markdown rendering happens you can use an external renderer that supports the flavour you prefer. See more at: https://docs.gitea.io/en-us/external-renderers/

**Comment by zeripath** [comment]
An automatic ToC is already possible add the frontmatter:

```
---
gitea: none
include_toc: true
---
```

the `gitea:` tells gitea to not present the frontmatter in a table form.

Documentation for the frontmatter ToC was missed in its PR - and I've been too busy to sort it out.
