### ISSUE TITLE
how to backfill contributions graph

### ISSUE THREAD

**Issue by meonkeys** [go-gitea/gitea#14416]
- Gitea version (or commit ref): 1.13.1
- Git version: 2.26.2
- Operating system: Docker, image is `gitea/gitea:1`. Host OS is Ubuntu GNU/Linux 20.04 LTS, 64-bit Intel
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL (mariadb)
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No - haven't tried
- Log gist:

## Description

This is really more of a question... is there some way to backfill the contributions graph? I tried asking in the Gitea channel on Matrix but nobody knew. I tried manually running `Check all repository statistics` on `/admin/monitor` but that didn't have any effect.

## Screenshots

I should have many commits, but it only seems to show commits since the day I installed and set up gitea (two days ago):

![Screenshot from 2021-01-21 08-50-29](https://user-images.githubusercontent.com/50639/105383262-c6fbae80-5bc5-11eb-86e1-f427726276bc.png)

**Comment by techknowlogick** [comment]
The matrix room is currently in unofficial status, and official community support happens in our discord/discourse (see https://docs.gitea.io/en-us/seek-help/ )

As for "backfilling" the contributions graph, it is populated by the actions table which record actions that happen in gitea. Having it parse through each commit on push would significantly increase resource usage, as well as would require storing each commit in the DB (vs each push), which would cause an increase in disk space required.

If you'd like to manually do it, then you could try inserting rows into the actions table, however that is not recommend in case it causes unintended side-effects (generally it is better for application being the only thing that touches DB).
