### ISSUE TITLE
Gitea HTTPS setup as docker image on a synology nas

### ISSUE THREAD

**Issue by visuall** [go-gitea/gitea#14414]
Hi,

Using docker image available for synology I was able to run gitea with no problem. However the https mode is quite unclear. Is there a good reference for running gitea on synology with https ? Self signed cert will be enough for our needs.

Nick

**Comment by noerw** [comment]
For general TLS documentation, there is https://docs.gitea.io/en-us/https-setup/
You probably want to mount the certificates via a docker volume into the container for persistence.
For more detailed questions, please ask on our discord in `#configuration` channel
