### ISSUE TITLE
Strange email from noreply@gitea.com

### ISSUE THREAD

**Issue by lcnittl** [go-gitea/gitea#14415]
I have just received this strange email – strange because the broken line breaks and the broken english:

![image](https://user-images.githubusercontent.com/23134999/105354649-24592500-5bf1-11eb-956a-6a86353fd3e4.png)

Is this real, or is gitea.com subject to some sort of phishing attempt?

**Comment by noerw** [comment]
If you have questions about gitea.com, our discord or https://gitea.com/gitea/gitea.com/issues is a good place to ask.

Thanks for the typo / formatting / spamfilter heads-up anyway :)
