### ISSUE TITLE
show absolute commit dates ( not eg 3 weeks ago)

### ISSUE THREAD

**Issue by petercutting** [go-gitea/gitea#14423]
It would be nice if I could check commit dates to see if I was working some day in the past. But the commits are marked eg "3 weeks ago" which makes that impossible. Please add a toggle switch so that I can see abs dates

**Comment by delvh** [comment]
If I understand your intention correctly, you want to see when exactly a commit was made/ pushed in the `Commit` View of any project, right?
If that is the case, it is already possible by hovering over any commit data (i.e. `12 hours ago`) and a Tooltip will pop up describing the exact date the commit has been made.

**Comment by petercutting** [comment]
Hi yes it is enough. However a toggle would be nice. (also one can use the terminal - git history )
