### ISSUE TITLE
Chrome tries to load .../gitea/gitea/img/logo.png, Firefox loads .../gitea/img/logo.png

### ISSUE THREAD

**Issue by uli-heller** [go-gitea/gitea#14422]
- Gitea version (or commit ref): 1.14.0+dev-575-g1c230f69d 
- Git version: 2.25.1
- Operating system: ubuntu-20.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
- I'm using the context /gitea for my instance

## Description

After clicking on the upper left logo, chrome tries to load several urls. There are two logo urls:

- logo.svg ... this is ok - https://hetzner-de.daemons-point.com/gitea/img/logo.svg
- logo.png ... this is KO, it contains the context "/gitea" twice - https://hetzner-de.daemons-point.com/gitea/gitea/img/logo.png

For firefox the error doesn't happen. Firefox does not try to load the PNG logo.

## Screenshots

Chrome:

![image](https://user-images.githubusercontent.com/1677414/105461506-9b43fb80-5c8d-11eb-80b2-1ba4ac533ac5.png)

Firefox:

![image](https://user-images.githubusercontent.com/1677414/105462001-540a3a80-5c8e-11eb-94c0-e1883d3fb47c.png)

**Comment by silverwind** [comment]
The only place where we still use the PNG should be the meta tag `<meta property="og:image" content="/img/logo.png" />`. What does that tag's URL look like in your case?

**Comment by uli-heller** [comment]
I see these two pngs 

```
$ curl -s https://hetzner-de.daemons-point.com/gitea|grep png
	<link rel="alternate icon" href="/gitea/img/favicon.png" type="image/png">
	<meta property="og:image" content="/gitea/img/logo.png" />
```

The SVG looks similar:

```
       <link rel="icon" href="/gitea/img/logo.svg" type="image/svg+xml">
```
Maybe for the PNG, og:url and og:image are contatenated somewhere somehow?

```
        <meta property="og:image" content="/gitea/img/logo.png" />
        <meta property="og:url" content="https://hetzner-de.daemons-point.com/gitea/" />
```

**Comment by uli-heller** [comment]
The manifest looks like this:

```
       <link rel="manifest" href="data:application/json;base64,eyJuYW1lIjoiR2l0ZWE6IEdpdCB3aXRoIGEgY3VwIG9mIHRlYSIsInNob3J0X25hbWUiOiJHaXRlYTogR2l0IHdpdGggYSBjdXAgb2YgdGVhIiwic3RhcnRfdXJsIjoiaHR0cHM6Ly9oZXR6b
mVyLWRlLmRhZW1vbnMtcG9pbnQuY29tL2dpdGVhLyIsImljb25zIjpbeyJzcmMiOiJodHRwczovL2hldHpuZXItZGUuZGFlbW9ucy1wb2ludC5jb20vZ2l0ZWEvZ2l0ZWEvaW1nL2xvZ28ucG5nIiwidHlwZSI6ImltYWdlL3BuZyIsInNpemVzIjoiNTEyeDUxMiJ9LHsic3JjIj
oiaHR0cHM6Ly9oZXR6bmVyLWRlLmRhZW1vbnMtcG9pbnQuY29tL2dpdGVhL2dpdGVhL2ltZy9sb2dvLnN2ZyIsInR5cGUiOiJpbWFnZS9zdmcreG1sIiwic2l6ZXMiOiI1MTJ4NTEyIn1dfQ=="/>
```

or:

```
{
    "icons": [
        {
            "sizes": "512x512",
            "src": "https://hetzner-de.daemons-point.com/gitea/gitea/img/logo.png",
            "type": "image/png"
        },
        {
            "sizes": "512x512",
            "src": "https://hetzner-de.daemons-point.com/gitea/gitea/img/logo.svg",
            "type": "image/svg+xml"
        }
    ],
    "name": "Gitea: Git with a cup of tea",
    "short_name": "Gitea: Git with a cup of tea",
    "start_url": "https://hetzner-de.daemons-point.com/gitea/"
}
```

**Comment by silverwind** [comment]
Thanks. pretty certain it's a bug in the manifest generation.

**Comment by uli-heller** [comment]
I looked at modules/setting/setting.go and it seems that MakeAbsoluteAssetURL is called with
appURL: https://hetzner-de.daemons-point.com/gitea/, staticURLPrefix: /gitea
and it returns the concatenation of these...

**Comment by lunny** [comment]
@uli-heller Could you try this patch

```diff
diff --git a/modules/setting/setting.go b/modules/setting/setting.go
index be7ec16e1..1f05bd7b6 100644
--- a/modules/setting/setting.go
+++ b/modules/setting/setting.go
@@ -1070,12 +1070,7 @@ func MakeAbsoluteAssetURL(appURL string, staticURLPrefix string) string {
        }

        if err == nil && parsedPrefix.Hostname() == "" {
-               if staticURLPrefix == "" {
-                       return strings.TrimSuffix(appURL, "/")
-               }
-
-               // StaticURLPrefix is just a path
-               return strings.TrimSuffix(appURL, "/") + strings.TrimSuffix(staticURLPrefix, "/")
+               return strings.TrimSuffix(appURL, "/")
        }

        return strings.TrimSuffix(staticURLPrefix, "/")
```

**Comment by uli-heller** [comment]
@lunny Your patch looks good!

- Checked out master
- Applied your patch - https://github.com/uli-heller/gitea/tree/logo.png-2
- Built
- Run and tested: OK

![image](https://user-images.githubusercontent.com/1677414/108585006-f9740500-7345-11eb-9076-852f473d1407.png)
