### ISSUE TITLE
Can't use LFS in organization's repo, even though user is owner

### ISSUE THREAD

**Issue by lonix1** [go-gitea/gitea#14424]
- Gitea version (or commit ref): 1.13.1
- Git version: 2.25.1
- Operating system: linux ubuntu, gitea running locally in docker
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No It didn't work for me, maybe it's a different version?
- Log gist:

## Description

This bug has come up many times, e.g. #5920, and seems to be resolved, but it still exists (At least for me).

- GITEA: create organization
- GITEA: create repo within that organization; I am now an "Owner" of that org and repo
- LOCAL: create repo with lfs support: `git init; git lfs install`
- LOCAL: setup lfs: `git lfs track '*.bin'; git add .gitattributes`
- LOCAL: create binary file: `echo foo > foo.bin; git add foo.bin`
- LOCAL: commit: `git commit -m 'initialize'`
- LOCAL: `git remote add origin http://example.com:1234/foo/bar.git; git push -u origin master`

Asks for username and password, then asks again, and again, etc. Doesn't push.

If I add myself as a "Collaborator" of the repo, then it starts working. Surely this is not necessary, because I am already an "Owner"?

**Comment by lonix1** [comment]
UPDATE: I'm not sure if this is a bug or not after all.

When doing `git push -u origin master`, it asks for username/password THREE times. Then it succeeds.

Then when I do `git push`, it asks for username/password TWO times. Then it succeeds.

I'm not making typos. What is the reason?

**Comment by lunny** [comment]
Maybe because `git` prompt you once and `git lfs` prompt another ? `git` and `git lfs` don't share the secrets?

**Comment by lonix1** [comment]
@lunny That's an interesting theory, it makes sense!

I'll close, and if anyone else has this problem we can discuss. Thanks.
