### ISSUE TITLE
U2F/FIDO Token not supported in Safari browser, despite API being present

### ISSUE THREAD

**Issue by cortices** [go-gitea/gitea#14456]
- Gitea version (or commit ref): 1.14.0+dev-598-g4acb499f3 (Docker)
- Git version: 2.30.0
- Operating system: Gitea under Docker (gitea/gitea, tag: latest), User browser Safari 14.0 under macOS 10.15.7
  
  
Gitea docker is behind an nginx reverse proxy on HTTPS only (not accessible over HTTP), on a dedicated subdomain.
  
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
- Log gist:

## Description

Safari 14 supports U2F keys (see https://caniuse.com/u2f), but Gitea's U2F plugin doesn't allow it, and says it is unsupported.

I can add my keys in Firefox or Chrome, and other websites can use the same keys in Safari.

## Screenshots

<img width="776" alt="image" src="https://user-images.githubusercontent.com/1159183/105701484-7934cc80-5f5e-11eb-8ac0-66f4100c5e1d.png">

**Comment by cortices** [comment]
So this is a result of the old google u2f API being dropped by Safari in favour of WebAuthn and Gitea not being on WebAuthn yet, as discussed & worked on here https://github.com/go-gitea/gitea/pull/9451

I will see if I can get the time to look at contributing to @e3b0c442's work

**Comment by 6543** [comment]
#17957
