### ISSUE TITLE
Delete review requests as non-admin

### ISSUE THREAD

**Issue by jpraet** [go-gitea/gitea#14459]
- Gitea version (or commit ref): 1.14
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes 

## Description

When I request a review, I am not able to delete this review request if I am no administrator. I would expect at least to be able to delete a review request I created myself in case I selected the wrong person by accident. But I think even someone else should be able to delete the review request as well. Everyone that can add reviewers should also be able to delete them in my opinion?

## Screenshots

I add a review request:

![image](https://user-images.githubusercontent.com/2212615/105752677-e38e4280-5f47-11eb-99c9-918c1bb1532c.png)

But I cannot delete it:

![image](https://user-images.githubusercontent.com/2212615/105752748-facd3000-5f47-11eb-9bfa-352d3b0a9ab9.png)

Unless when I am admin:

![image](https://user-images.githubusercontent.com/2212615/105752823-0e789680-5f48-11eb-9d51-3858e342d377.png)

**Comment by a1012112796** [comment]
That't follow github style.
see:
https://github.com/go-gitea/gitea/pull/10756#discussion_r396892580

**Comment by PaulBol** [comment]
> That's follow github style. see: [#10756 (comment)](https://github.com/go-gitea/gitea/pull/10756#discussion_r396892580)

My understanding may be wrong. But to me it seems like the comment refers to review requests that have already been processed, i.e. approved or rejected by the reviewer. This issue mentions a pending review request.

I agree with jpraet that the person who requested the review should be able to delete the review request as long as it's not more than a request. What would be the reason do deny this?

**Comment by jpraet** [comment]
I want to create a PR to allow the person who requested the review to be able to delete the review request.
But it looks like I cannot easily determine the author of the review request. It's not stored in the review table.

Would a PR get accepted that allows review request deletion to anyone that has permission to add review requests?

**Comment by jbartlau** [comment]
Any news on this? Just landed here and would support such a change. @jpraet did you ever hear back from anyone?

**Comment by lunny** [comment]
Maybe we can accept the person himself could remove the review request?

**Comment by lunny** [comment]
Looks like the code is there, but I don't know whether there are some bugs.

https://github.com/go-gitea/gitea/blob/main/routers/web/repo/issue.go#L634-L644

**Comment by KevinBaileyCrum** [comment]
this would be great, i have opened a pr in gitea, accidentally assigned a reviewer, then i cannot remove the reviewer,

i have had pr's get stuck because i added a reviewer who may be away from their computer for a long time and this completly blocks the merge (merge when all checks pass but an accidentally requested reviewer will always block)

**Comment by hawicz** [comment]
The actual validation check seems to be in `IsValidReviewRequest()` at https://github.com/go-gitea/gitea/blob/main/services/issue/assignee.go#L157 (called from `UpdatePullReviewRequest()` at https://github.com/go-gitea/gitea/blob/main/routers/web/repo/issue.go#L2475), and only allows you to remove yourself, unless you're an admin.
This seems unnecessarily restrictive to me too.

**Comment by lunny** [comment]
How about everyone who is a member of that repository with read-permissions can add/remove reviewer requests of every pull requests and the PR creators can also do that for their created PRs? If nobody against, I will send a PR to fix that.

**Comment by KevinBaileyCrum** [comment]
I think that is a good idea, if you opened the PR and you assigned someone,
you should have the ability to remove them.
