### ISSUE TITLE
Render LFS text file on diff page

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#14452]
Currently all LFS files are considered as binary files but in fact it's not true. We have implemented render LFS file on tree view, so in diff page, we should also implement it.

**Comment by delvh** [comment]
To save on computing power, we could also implement a mechanism similar to that used by GitHub where, if a file is too large/ contains to many differences, then the user has too manually click on "Load File" - "Large diffs are not rendered by default"

**Comment by lunny** [comment]
I think it's very difficult because LFS storage is very different from git data. There is no patch, we need a diff tool but it maybe very slow. I think maybe we can close this one.
