### ISSUE TITLE
Assignee filter does not show usernames

### ISSUE THREAD

**Issue by CirnoT** [go-gitea/gitea#14469]
- Gitea version (or commit ref): 1.14.0+dev-607-g012bf388a
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL) https://try.gitea.io/test_org21/test_repo/issues
  - [ ] No

## Description

Assignee filter does not show usernames

## Screenshots

![firefox_2021-01-26_12-28-35](https://user-images.githubusercontent.com/1447794/105839708-33195080-5fd2-11eb-88a7-ad7f19b9a00b.png)

**Comment by lunny** [comment]
missed on https://github.com/go-gitea/gitea/commit/9269a038a4e904bdeaf5470e76e3a4f8a2a4685b#r46412179
