### ISSUE TITLE
Template panic is shown to user in production mode

### ISSUE THREAD

**Issue by CirnoT** [go-gitea/gitea#14467]
- Gitea version (or commit ref): 1.14.0+dev-605-gd2ea21d0d

## Description

Panic message from template should not be shown to end-user in production mode, we should recover and try to render nice 500 page, alternatively if that also fails just send empty content with 500.

**Comment by CirnoT** [comment]
Bumping since no labels were assigned. I really don't think full panic message should be shown to user in production mode, in very rare cases it can expose some details that should not be,

**Comment by zeripath** [comment]
Agreed it needs sorting.

Sorry it was missed - personally I have 960 notifications in my GitHub notification list, have recently broken my hand and none of us paid to work on Gitea.

Now I know about it I'll take a look at it.

(If you happen to know the other issue number that was initially regarding writeheader could you link it here for me and I'll get that closed at the same time.)
