### ISSUE TITLE
When create new release,extracting zip work well but tar.gz not work  as EOF error. 

### ISSUE THREAD

**Issue by hooklee2000** [go-gitea/gitea#14465]
- Gitea version (or commit ref): 1.13.1 
- Git version: 2.26.0 
- Operating system: CentOS7.8  
- Database use  MySQL

When create new release, extracting zip file (386MB) work well but tar.gz file (236MB) not work as EOF error. 
I have some  filename with chinese character such as dns测试.md .

**Comment by chenwd2012** [comment]
我使用的gitea 1.13.1 是zip 不行，下载时文件缺失，tar.gz 正常

**Comment by hooklee2000** [comment]
Using Gitea 1.14.3 and host  can access Internet, after some security check, 
tar.gz  and zip are all correct.
