### ISSUE TITLE
Tab Support

### ISSUE THREAD

**Issue by Itege** [go-gitea/gitea#14464]
Gitea Version: 1.14.0+dev-607-g012bf388a (downloaded the arm6 build from the gitea website)
git version: 2.20.1
OS: Raspberry Pi OS
Run via systemd
- Database:
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No

Are there plans to support the use of tabs in repo view? I know they display fine in the editor, but my code is almost completely flat due to tabs being squashed. I've seen some people suggesting tabs are already supported, but I am unsure how?

![image](https://user-images.githubusercontent.com/844708/105806329-c4a4a600-5f71-11eb-84cc-cd00bfec91f7.png)

**Comment by lunny** [comment]
Do you mean display the tab character?

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
I do recall setting up something additionally (tab size - 8 characters) somewhere - and maybe I don't remember it so well but here's what I've got.

![image](https://user-images.githubusercontent.com/61180606/105816285-677e1400-5fb4-11eb-8ecc-dd487519efe1.png)

wouldn't hurt to provide your Gitea version, OS, possibly info on whether you have custom templates etc..
for instance:
Gitea Version: `1.14.0+dev-604-gbc05ddc0e`
git version: `git version 2.30.0.365.g02bc693789`
OS: `Arch Linux`

**Comment by lunny** [comment]
You can change tabsize via `.editorconfig`

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
> You can change tabsize via `.editorconfig`

does it have to be placed in Gitea's home?
because I don't have it and my java code shows tab width properly, whereas it doesn't work for OP (I assume they don't have `.editorconfig` either)..

**Comment by lunny** [comment]
Put the file on repository's root path.

**Comment by Itege** [comment]
Gitea Version: 1.14.0+dev-607-g012bf388a 
git version 2.20.1
OS: Raspberry Pi OS

**Comment by Itege** [comment]
> > You can change tabsize via `.editorconfig`
> 
> does it have to be placed in Gitea's home?
> because I don't have it and my java code shows tab width properly, whereas it doesn't work for OP (I assume they don't have `.editorconfig` either)..

I've tried adding an `.editorconfig` to one of my projects and it didn't do anything.

**Comment by lunny** [comment]
I have tested to add an `.editorconfig` in a golang project. It's work.

```
# http://editorconfig.org
root = true

[*]
indent_style = space
indent_size = 2
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true
```

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
ping @Itege see above.

why does it shows proper tab width indentation on my instance without `.editorconfig` (in, e.g. a {c,java,c#} project) though? @lunny

**Comment by lunny** [comment]
The default value should be `"tab-size-8"` if there is no `.editorconfig`.

**Comment by Itege** [comment]
> I have tested to add an `.editorconfig` in a golang project. It's work.
> 
> ```editorconfig
> # http://editorconfig.org
> root = true
> 
> [*]
> indent_style = space
> indent_size = 2
> end_of_line = lf
> charset = utf-8
> trim_trailing_whitespace = true
> insert_final_newline = true
> ```

What happens if you change that to `indent_style = tab` and `tab_width = 4`? That is what I attempted and it didn't work.

**Comment by zeripath** [comment]
@Itege you must update the initial issue comment to fit the proforma. In particular you must tell us what version you are using.

**Comment by Itege** [comment]
@zeripath I've updated it as requested, sorry for not doing that correctly in the first place.

**Comment by zeripath** [comment]
Is it true that you cannot replicate this on try.gitea.io?

**Comment by zeripath** [comment]
for example: https://try.gitea.io/arandomer/cub3d/src/branch/cub3d/src/main.c looks normal to me.

**Comment by Itege** [comment]
I could not replicate the issue on try.gitea.io, I created a repo and added an editor config, then inserted a tab into a file and it worked as expected.

**Comment by zeripath** [comment]
https://try.gitea.io/arandomer/spring-framework/src/branch/master/spring-jms/src/main/java/org/springframework/jms/core/JmsOperations.java similarly looks normal.

Try updating your gitea

**Comment by Itege** [comment]
Just updated to 1.14.0+dev-624-ga51cc6dea (today's build) and the issue is persisting.

**Comment by Itege** [comment]
Looking at the source code in chrome, it seems like all whitespace preceding a line of code is being replaced by a singular space.

**Comment by zeripath** [comment]
You're using cloudfare whitespace optimization.

Turn it off.

**Comment by Itege** [comment]
Oh wow... thanks I didn't even think to look at that.

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
> You're using cloudfare whitespace optimization.
> 
> Turn it off.

well damn me, not this again..
now anyone tell me to not put it in the issue template...
