### ISSUE TITLE
Creating pull request returns 500 error because of commit symbol

### ISSUE THREAD

**Issue by lakostin** [go-gitea/gitea#14470]
- Gitea version (or commit ref):
1.14.0+dev-534-gedbc5c86d
- Git version:
2.26.2
- Operating system:
docker Alpine Linux v3.12
- Database (use `[x]`):
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
- Log gist:
2021/01/26 14:11:06 ...ters/repo/compare.go:477:PrepareCompareDiff() [E] GetCommit: encoding/hex: invalid byte: U+004B 'K'

## Description

...

## Screenshots

![Screenshot from 2021-01-26 14-18-12](https://user-images.githubusercontent.com/29179059/105840486-27368a00-5fe4-11eb-98fa-5f9b3fbf5a20.png)

**Comment by lunny** [comment]
If is this repository a public one?

**Comment by lakostin** [comment]
> If is this repository a public one?

private

**Comment by zeripath** [comment]
I bet the issue is that the name of the branch contains exactly 40 characters

**Comment by zeripath** [comment]
Apologies for this I've predicted this issue for a very long time but haven't told anyone about it or fixed it.

The provided fix is by no means perfect as a branch whose name matches the sha pattern could still collide in interesting and undefined ways and so we will need deeper testing to figure out what we want.

**Comment by richmahn** [comment]
@zeripath this is also on the v1.13.3 milestones so needs a backport.

**Comment by zeripath** [comment]
Feel free to send some of these backports. I don't mind.
