### ISSUE TITLE
Orphaned/zombie releases

### ISSUE THREAD

**Issue by pat-s** [go-gitea/gitea#14471]
- Gitea version (or commit ref): 1.13.1
- Git version: 2.26.0
- Operating system: docker
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
- Log gist:

## Description

In some repo imports from GitLab (not a recent import) we have orphaned/zombie releases, meaning they show up in the "releases" section and one can click on them/their tag, but their redirect back to the main page of that repo.

I tried finding and deleting these releases via the API however they are not listed as releases (not even the tags exist).

I am wondering how I can get rid of these zombie objects?

Do I need to remove them within the DB somehow?

## Screenshots

<img width="296" alt="image" src="https://user-images.githubusercontent.com/8430564/105860056-78974700-5fed-11eb-827e-8dd85ee2b3a7.png">

**Comment by lunny** [comment]
If there is no release notes that means they are just tags, I think you can delete from database safely.

**Comment by pat-s** [comment]
Thanks!

```
git push --delete origin <tagname>
```

did it.
