### ISSUE TITLE
[Suggestion] Add or edit the existing heatmap to show commits, not pushes.

### ISSUE THREAD

**Issue by ziplock9000** [go-gitea/gitea#14472]
It would be really useful to be able to have a heatmap similar to the existing one that shows activity/pushes, but instead shows commits. 
In fact, I think most people would find it more useful as it's a much better indicator of your activity levels.

For example, I could locally commit 1000 times in a day and push once, the current heatmap would only show 1 activity.
While this is due to it being based off the feed, it's still not nearly as useful as showing a heatmap of commits.

**Comment by lafriks** [comment]
It could be probably calculated for single repository but not for user as that would mean scanning history of all servers repositories

**Comment by ziplock9000** [comment]
Some servers may only have a few repos.
Some may run on very powerful hardware.
The scanning could be done as a low priority task and infrequently.
That choice is based on resources and should be made by the server administrator, not the architecture of Gitea.

**Comment by lunny** [comment]
If the commits counts are stored on action table then we can do that.

**Comment by lafriks** [comment]
Commits can be force pushed thus invalidating a lot of commits, new repositories can be imported, deleted etc. There are just so many cases where commit history can change that it would be hard to keep these numbers useful imho
