### ISSUE TITLE
Creating release from git command line results in Release webhook not triggered

### ISSUE THREAD

**Issue by kplese** [go-gitea/gitea#14489]
- Gitea version (or commit ref):
1.13.1
- Git version:
2.25.1
- Operating system:
CentOS
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No

## Description
Creating release from git command line, results in Release webhook not triggered, and also, different view in Releases tab.

So, If I create the Release from the Gitea UI, Release webhook is triggered correctly and one type of view is created.
But if I create Release using git tag (both annotated and lightweight), and then push to repo, Release webhook is not created and view of the release in Release tab is different.
...

## Screenshots
![image](https://user-images.githubusercontent.com/47209169/105996366-8232b480-60aa-11eb-84bc-b8b6b53f0103.png)

**Comment by lunny** [comment]
I think you can just push a tag via git command line but that's not a release for Gitea .

**Comment by techknowlogick** [comment]
As @lunny mentioned, you create tags via cli, but releases via GUI. If you'd like to create a release via CLI I recommend you take a look at our "tea" cli tool.
