### ISSUE TITLE
Imprufe router related code

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#14486]
Since we moved to chi,  we do not have dependency to macaron anymore ... ( @zeripath you talked about some "cant do because of macaron...", can you describe these if you remember?)

also we do use context package more heavily, we should have a look what we could optimize there.

 * [ ] look at https://gitea.com/go-chi/ and improve/refactor all of it (now we dont have to care about breaking changes)

**Comment by wxiaoguang** [comment]
Our route code has been hugely refactored by #24080  , I think there won't be blockers, we are on our own way.

So this issue could be closed?

**Comment by 6543** [comment]
yes we finaly got dir of that
