### ISSUE TITLE
Support hg:: and and bzr:: repo URLs

### ISSUE THREAD

**Issue by lofidevops** [go-gitea/gitea#1449]
- Gitea version (or commit ref): 1.1.0
- Git version: 2.9.3
- Operating system: Ubuntu 16.10
- Database (use `[x]`):
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Not relevant
- Log gist: N/A

## Steps to reproduce

* Install `git-remote-hg` package
* Confirm `git clone "hg::http://selenic.com/repo/hello"` works from the command line
* Open Gitea
* Attempt to create a repository mirror
* Enter `hg::http://selenic.com/repo/hello` as URL

(Repeat with `git-remote-bzr` package and `git clone "bzr::lp:ubuntu/hello"` for Bazaar support)

## What should happen

* Create a Git mirror of the Mercurial repo
* Regularly update the mirror (like any other mirror)

## What happens instead

* Error message: "You are not allowed to import local repositories."

**Comment by 6543** [comment]
I dont see this integrated in the near future and mostly you have to fix things localy ... so it's best to use existing tools to convert them localy and push the converted git

can we close this?

**Comment by lofidevops** [comment]
I don't personally have a use-case for this anymore, so happy to close. If only I could search the whole ticket-verse for such issues ;)

**Comment by lofidevops** [comment]
(For others that do still have a use-case, I imagine 6543's suggestion is more reliable than ad-hoc support in Gitea.)
