### ISSUE TITLE
Get 401 if you have a CSRF cookie and use Basic auth and are already logged in

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#14498]
Well.. you get 401 if you have a CSRF cookie and use Basic auth but not if you use other auth options...
Is this not considered a bug?

_Originally posted by @AllTaken in https://github.com/go-gitea/gitea/issues/13484#issuecomment-768549291_

**Comment by lunny** [comment]
We should leave some comments here if we change them.

**Comment by zeripath** [comment]
Gonna need some more details here. Presumably this is on the API?

**Comment by 6543** [comment]
the issue occurred on a GET api witch require auth

**Comment by dr-consit** [comment]
Also there's quite a lot more information in the original issue: #13484 

But yeah, the gist is:

If you try to use the API from with basic auth, but happen to have a CSRF cookie set, it breaks.

This will be the case if you try to test the API from the auto generated swagger page (e.g. https://try.gitea.io/api/swagger) after having logged in / getting the CSRF cookie in your browser.
So if you choose to authorize with Basic authorization in the swagger page, you get 401, even though you have entered valid credentials. But if you chose one of the other authorizations, it works as expected.
At least this was the case when I created the original issue.

**Comment by wxiaoguang** [comment]
Now there is no call to API from UI
