### ISSUE TITLE
Add support for creating pull requests via git push options

### ISSUE THREAD

**Issue by strk** [go-gitea/gitea#14493]
Gitea 1.3 added support for push options: https://docs.gitea.io/en-us/push-options/
It would be nice if pull requests could be opened via push options, like it's done for gitlab: https://docs.gitlab.com/ce/user/project/push_options.html

**Comment by 6543** [comment]
I would use **tea** or just klick on the link the git push returns ...

**Comment by strk** [comment]
@tea requires installing another tool, while git push options are supported by git core itself.

**Comment by BrainWart** [comment]
The "Agit Setup" page in the documentation shows something very close to this. It will work for me. It allows you to create a PR using the ref.

https://docs.gitea.com/usage/agit-setup

**Comment by 6543** [comment]
I guess we can close this issue now :)
