### ISSUE TITLE
got an error message when i built from source

### ISSUE THREAD

**Issue by lambdaR** [go-gitea/gitea#14509]
- Gitea version (or commit ref): git clone https://github.com/go-gitea/gitea
- Git version: 2.25.1
- Operating system: Ubuntu LTS 20
- Go: go1.15.7
- Nodejs: v15.7.0
- command: TAGS="bindata sqlite sqlite_unlock_notify" make build
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] N
- Log gist:
0 verbose cli [
0 verbose cli   '/usr/bin/node',
0 verbose cli   '/usr/lib/node_modules/npm/bin/npm-cli.js',
0 verbose cli   'exec',
0 verbose cli   '--',
0 verbose cli   'webpack'
0 verbose cli ]
1 info using npm@7.4.3
2 info using node@v15.7.0
3 timing config:load:defaults Completed in 4ms
4 timing config:load:file:/usr/lib/node_modules/npm/npmrc Completed in 1ms
5 timing config:load:builtin Completed in 1ms
6 timing config:load:cli Completed in 3ms
7 timing config:load:env Completed in 1ms
8 timing config:load:file:/home/ubuntu/gitea/.npmrc Completed in 4ms
9 timing config:load:project Completed in 5ms
10 timing config:load:file:/home/ubuntu/.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:/usr/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 1ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 2ms
16 timing config:load:setUserAgent Completed in 2ms
17 timing config:load:setEnvs Completed in 2ms
18 timing config:load Completed in 22ms
19 verbose npm-session 25087d9d3718adc4
20 timing npm:load Completed in 40ms
21 timing command:exec Completed in 292959ms
22 verbose stack Error: command failed
22 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
22 verbose stack     at ChildProcess.emit (node:events:379:20)
22 verbose stack     at maybeClose (node:internal/child_process:1069:16)
22 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:300:5)

## Description
got an error message when i built from source

## Screenshots

![Screenshot from 2021-01-28 17-02-42](https://user-images.githubusercontent.com/7769368/106148929-b54c7500-618a-11eb-96c9-1813cddc4b5d.png)

**Comment by delvh** [comment]
I think the log mentioned (`/home/ubuntu/.npm/_logs/2021-01-28T13_46_18_097Z-debug.log`) might be useful to help you find the problem…

**Comment by delvh** [comment]
I think the log mentioned (/home/ubuntu/.npm/_logs/2021-01-28T13_46_18_097Z-debug.log) might be useful to help you and everyone else find the problem…

**Comment by techknowlogick** [comment]
Error code 137 is due to linux killing the process from running out of memory. Webpack manages that itself, and we don't control its memory use.

**Comment by lambdaR** [comment]
i have 1.5G of memory and 2 cpu reserved for ubuntu instance, **do i need more** ?

**Comment by techknowlogick** [comment]
Webpack sometimes uses a lot of memory, our use of it is a fairly vanilla. If you'd like to skip the building of CSS and JS, we do distribute pre-built versions of the JS/CSS itself on dl.gitea.io. To continue this discussion please reach out to us on our discord in the #develop channel.
