### ISSUE TITLE
List of branches always shows one branch less

### ISSUE THREAD

**Issue by CirnoT** [go-gitea/gitea#14503]
- Gitea version (or commit ref): 1.14.0+dev-626-ga7cfb9f2c
- Git version: 2.30.0
- Operating system: Docker
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL) https://try.gitea.io/test_org21/test_repo/branches
  - [ ] No

## Description

List of branches always shows one branch less. In the example linked, branch `refs/pull/7/head` is invisible.

**Comment by a1012112796** [comment]
? ``refs/pull/{{id}}/head`` is not a branch, it's a special ref.

**Comment by 6543** [comment]
Is not the case anymore :)

**Comment by CirnoT** [comment]
Which commit was this fixed in?

**Comment by 6543** [comment]
a good question ... - I think one of the paginate branches did it ... (not sure throu ...)

**Comment by zeripath** [comment]
If you really are interested git bisect would be the way to do it but it's fairly academic at this point.

**Comment by lunny** [comment]
@6543 I think maybe that pull caused the problem but not fix this one.

**Comment by 6543** [comment]
I dont look back, until one can reproduce the issue with current master ...
