### ISSUE TITLE
No commits in common is shown when comparing identical branches

### ISSUE THREAD

**Issue by CirnoT** [go-gitea/gitea#14502]
- Gitea version (or commit ref): 1.14.0+dev-622-g41c077656
- Git version: 2.30.0
- Operating system: Docker
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL) https://try.gitea.io/test_org21/test_repo/compare/master...master
  - [ ] No

## Description

>No commits in common. 'master' and 'master' have entirely different histories.

**Comment by lunny** [comment]
I think this is a typo
