### ISSUE TITLE
projects.desc does not exist in translation files

### ISSUE THREAD

**Issue by CirnoT** [go-gitea/gitea#14512]
- Gitea version (or commit ref): 1.14.0+dev-626-ga7cfb9f2c
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No

## Screenshots

![firefox_2021-01-29_01-19-20](https://user-images.githubusercontent.com/1447794/106214880-0763b980-61d0-11eb-8d69-f82331821369.png)

**Comment by delvh** [comment]
My bad. I did not know that it was used somewhere else when I merged #14429. I'll fix it tomorrow.
