### ISSUE TITLE
build in ssh server ignore restricting macs settings

### ISSUE THREAD

**Issue by morph027** [go-gitea/gitea#14518]
- Gitea version (or commit ref): 1.13.1
- Git version: 1:2.17.1-1ubuntu0.7
- Operating system:

```
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic
```
Package download from https://dl.gitea.io/gitea/ and running via systemd

- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite

## Description

Setting `SSH_SERVER_MACS` seems to be ignored.

app.ini contains `SSH_SERVER_MACS = hmac-sha2-256-etm@openssh.com, hmac-sha2-256` but `ssh -Q mac gitea@<gitea-host>` still lists all:

```
ssh -Q mac gitea@...
hmac-sha1
hmac-sha1-96
hmac-sha2-256
hmac-sha2-512
hmac-md5
hmac-md5-96
umac-64@openssh.com
umac-128@openssh.com
hmac-sha1-etm@openssh.com
hmac-sha1-96-etm@openssh.com
hmac-sha2-256-etm@openssh.com
hmac-sha2-512-etm@openssh.com
hmac-md5-etm@openssh.com
hmac-md5-96-etm@openssh.com
umac-64-etm@openssh.com
umac-128-etm@openssh.com
```

**Comment by lunny** [comment]
It only affects builtin SSH server.

**Comment by morph027** [comment]
Yes, sorry, forgot that.

**Comment by morph027** [comment]
Gnarf, some browser crossaccount foo....created this issue w/ my personal account, added the PR w/ my company account ...
