### ISSUE TITLE
HTML source reveals version

### ISSUE THREAD

**Issue by morph027** [go-gitea/gitea#14519]
- Gitea version (or commit ref): 1.13.1
- Git version: 1:2.17.1-1ubuntu0.7
- Operating system:

```
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic
```
Package download from https://dl.gitea.io/gitea/ and running via systemd

- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite

## Description

I already set `SHOW_FOOTER_VERSION` which does work for the footer, but inspecting the source code of the page still reveals the version.

## Screenshots

![Screenshot from 2021-01-29 13-24-36](https://user-images.githubusercontent.com/600106/106274927-58f25f80-6235-11eb-97dc-c13db4499e40.png)

**Comment by KN4CK3R** [comment]
`SHOW_FOOTER_VERSION` is not intended to keep the version secret. Should this be a feature request to keep the version number private?

**Comment by lunny** [comment]
The `AppVer` is used by service worker to cache something.

**Comment by morph027** [comment]
Okay, thanks for clarification!

**Comment by morph027** [comment]
Crawling trough the code, i see a lot of `{{MD5 AppVer}}` template variables. Can't we just use the md5 hash as the service worker `cacheKey` too?

**Comment by KN4CK3R** [comment]
If your concern is security, that won't help.

**Comment by morph027** [comment]
Argh, you're right :facepalm:
