### ISSUE TITLE
Create repository with an group owner but it can't pull from server

### ISSUE THREAD

**Issue by zhoufoxcn** [go-gitea/gitea#14517]
- Gitea version (or commit ref):1.13.1
- Git version:2.27.2
- Operating system:CentOS7.8
  
  
  
The package is downloaded from offical site and it version is  gitea-1.13.1.
The shell command is:
`/home/jerry/gitea-1.13.1/gitea-1.13.1 web --config /home/jerry/gitea-1.13.1/custom/conf/app.ini`
and app.ini as below:
`[repository]
ROOT = /home/jerry/gitea-repositories

[server]
SSH_DOMAIN       = localhost
DOMAIN           = localhost
HTTP_PORT        = 80
ROOT_URL         = http://192.168.0.6/
DISABLE_SSH      = false
SSH_PORT         = 22
LFS_START_SERVER = true
LFS_CONTENT_PATH = /home/jerry/gitea-1.13.1/data/lfs
LFS_JWT_SECRET   = aDVCeywlPGGz79m5k4ZGw9VWB9JHRgU1YGDM5w05BHg
OFFLINE_MODE     = false

[mailer]
ENABLED = false

[service]
REGISTER_EMAIL_CONFIRM            = false
ENABLE_NOTIFY_MAIL                = false
#DISABLE_REGISTRATION              = false
DISABLE_REGISTRATION              = true
ALLOW_ONLY_EXTERNAL_REGISTRATION  = false
ENABLE_CAPTCHA                    = false
REQUIRE_SIGNIN_VIEW               = false
DEFAULT_KEEP_EMAIL_PRIVATE        = false
#DEFAULT_ALLOW_CREATE_ORGANIZATION = true
DEFAULT_ALLOW_CREATE_ORGANIZATION = false
DEFAULT_ENABLE_TIMETRACKING       = true
NO_REPLY_ADDRESS                  = noreply.localhost

[picture]
DISABLE_GRAVATAR        = false
ENABLE_FEDERATED_AVATAR = true

[openid]
#ENABLE_OPENID_SIGNIN = true
ENABLE_OPENID_SIGNIN = false
#ENABLE_OPENID_SIGNUP = true
ENABLE_OPENID_SIGNUP = false

[session]
PROVIDER = file

[log]
MODE                 = console
LEVEL                = info
ROOT_PATH            = /home/jerry/gitea-1.13.1/log
REDIRECT_MACARON_LOG = true
MACARON              = console
ROUTER               = console`
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
- Log gist:

## Description
suppose the repository path is **/home/jerry/gitea-repositories**,and the server is 192.168.0.6.
step1>create userA.
step2>create groupB and assign userA to groupB.
step3>create repositoryC and set it's onwer as groupB,then the repository will be saved at **/home/jerry/gitea-repositories/groupB/repositoryC.git**,and in the web page will show the pull url is:http://192.168.0.6/groupB/repositoryC.git.
step4>at the client pull the repository with url http://192.168.0.6/groupB/repositoryC.git,it will find the find the repository at **/home/jerry/gitea-repositories/userA/repositoryC.git**,thus occur an error.The message is like as below:
2021/01/29 15:29:45 ...r/setting/profile.go:249:Repos() [E] filepath.Walk: lstat /home/jerry/gitea-repositories/userA: no such file or directory
2021/01/29 15:29:45 Completed GET /user/settings/repos 500 Internal Server Error in 6.338544ms

**Comment by denyskon** [comment]
Closing as stale and not able to reproduce.
