### ISSUE TITLE
Incomplete instructions for docker with ssh-container-passthrough (must use bash)

### ISSUE THREAD

**Issue by steven-omaha** [go-gitea/gitea#14510]
- Gitea version (or commit ref): 1.14.0+dev-627-g154b23da0
- Git version: not relevant
- Operating system: Host is Debian buster, gitea runs in docker
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
- Log gist: irrelevant

## Description
https://docs.gitea.io/en-us/install-with-docker/#ssh-container-passthrough mentions that a user with the name `git` and the same uid/gid as stated in the docker environment variable `USER_UID` and `USER_GID` must exist. I did this, but my setup did not work. This is because I previously used my git user somewhat differently, and had its shell set to `git-shell`. When I changed its shell to `bash`, it then worked.

So somewhere on the page it must be mentioned that the shell for `git` must be `bash`.

**Comment by techknowlogick** [comment]
ping @pat-s to keep you informed as I know you use the passthrough

**Comment by pat-s** [comment]
Might be worth checking if only `bash` is valid or if only `git-shell` is invalid.

**Comment by techknowlogick** [comment]
Mm yeah, a standard shell (bash, ah) would be suitable but git-shell limits what can be run (including Gitea itself)

**Comment by ThibaultNocchi** [comment]
I confirm that using /bin/sh also works, so you just gotta set a shell it seems
