### ISSUE TITLE
Add GITEA_CUSTOM in documentation

### ISSUE THREAD

**Issue by blankoworld** [go-gitea/gitea#1452]
Documentation lacks of explanation about GITEA_CUSTOM to set a specific directory to deal with custom files.

If would be better for package maintainer for an example.
And for user, instead of searching here: #831 or #1208.

This could be probably done here: https://docs.gitea.io/en-us/customizing-gitea/?

What do you think about?

**Comment by strk** [comment]
Please send a PR against https://github.com/go-gitea/docs

See https://github.com/go-gitea/docs/blob/master/content/doc/advanced/customizing-gitea.en-us.md
