### ISSUE TITLE
Feature suggestion for small language creators: keep .gitattributes linguist-language overrides with unknown name in languages bar

### ISSUE THREAD

**Issue by ell1e** [go-gitea/gitea#14528]
- Gitea version (or commit ref): 1.14.0+dev-546-gdc66e4740
- Git version: ???
- Operating system: docker
- Database (use `[x]`): should be irrelevant
- Can you reproduce the bug at https://try.gitea.io: did not try, since it's not a bug
- Log gist: not a bug

## Description

I have a feature suggestion for small language creators: keep .gitattributes linguist-language overrides with unknown name in languages bar. This has also been suggested for the original linguist and GitHub [here](https://github.com/github/linguist/issues/4435), but GitHub seems to query language names from a central database and isn't interested in adding extra code to allow repo-only entries indirectly created by `.gitattributes` entries.

Basically, when `.gitattributes` contains a line like this: `*.h64 linguist-language=Horse64`, and the language `Horse64` isn't known to gitea / go-enry, then it would be cool if it still showed up with the name "Horse64" and any random color choice in the languages bar. I checked this on my own gitea instance (running 1.14.0) and right now this isn't the case, same as on GitHub the unknown language classification is just plain ignored and omitted.

## Screenshots
Project with ``*.h64 linguist-language=Horse64`` line and some `.h64` files looks like this:
![Screenshot from 2021-01-30 17-30-04](https://user-images.githubusercontent.com/64124388/106362086-de027500-6318-11eb-89f4-12a23276c6bd.png)
Mockup how this could look like with this feature:
![Screenshot from 2021-01-30 17-30-04-2](https://user-images.githubusercontent.com/64124388/106362080-d4790d00-6318-11eb-94b5-d89d340c77ad.png)

**Comment by lafriks** [comment]
Currently Gitea does not support reading gitattributes file

**Comment by lunny** [comment]
And the language bar is not branch special.

**Comment by ell1e** [comment]
Ah interesting. I'm actually not sure if it changes on GitHub for each branch or even commit you're looking at, but so far I would have assumed it probably does...? I never really paid attention to this detail though. If  this was just based on the main branch I still think it'd work sufficiently well for most projects though.

**Comment by alexanderadam** [comment]
@ell1e maybe it would be easier to add this language to [go-enry](https://github.com/go-enry/go-enry)?

By the way, [this line](https://github.com/go-gitea/gitea/blob/511f6138d4b5b7a464a8fa3d7f8fc52bec3789a4/modules/git/repo_language_stats_nogogit.go#L57) implies that the `.gitattributes` feature is planned, though. :wink:

**Comment by ell1e** [comment]
@alexanderadam no, this is a general problem of [quirky side languages](https://fll.presidentbeef.com/), this just doesn't scale. So just "getting it added to {library that is meant for **serious** syntax highlighting/lang identification}" is usually not in anybody's interest. Nobody wants that filled up with small hobby languages that might be discontinued, yet these hobby languages have a real use in having their repos not completely wrongly annotated in statistics if they can help it via manual `.gitattributes` entries.

**Comment by spacekookie** [comment]
> Currently Gitea does not support reading gitattributes file

Is this on the roadmap to support some time? I couldn't find an issue about it.
I generally vendor a lot of code into a big mono-repo and the language bar is pretty useless to me (and I wish it wasn't!). Being able to ignore subtrees with regards to the language statistics would be very nice.

**Comment by Nakilon** [comment]
Bump. I made a language and I want stats of code written in it be shown in sidebar of its repository.

**Comment by 6543** [comment]
should be fixed by #16773 ?
