### ISSUE TITLE
[Feature] Partial clones (git clone --filter) support

### ISSUE THREAD

**Issue by bagasme** [go-gitea/gitea#14540]
## Description

Currently Gitea only supports regular (full) clone and shallow clone. Attempting to do partial clone (by issuing `git clone --filter=<args> <url>`) will cause ignoring the filter, like:

`warning: filtering not recognized by server, ignoring`

Partial clones (blobless and treeless) reduces data needed during clone. It's especially beneficial for large repos.

Reference docs:
  - [gitlab](https://docs.gitlab.com/ee/topics/git/partial_clone.html)
  - [github](https://github.blog/2020-12-21-get-up-to-speed-with-partial-clone-and-shallow-clone/)

**Comment by a1012112796** [comment]
sadly, not like github or gitlab, gitea directly use git commands ``git receive-pack`` and ``git upload-pack`` to provide git web services. So if git not support it in these commands, It's hard to do it by ourselves.

**Comment by a1012112796** [comment]
oh, sorry, After check git code, I found maybe you  can enable by setting this git config in server side : ``uploadpack.allowfilter = true``. will try it later.

**Comment by lunny** [comment]
This has been resolved by #12170

**Comment by a1012112796** [comment]
resolved, just need an git config. :) you can set it if you need. Thanks.

see https://github.com/go-gitea/gitea/issues/14540#issuecomment-770741890

example:

![test](https://user-images.githubusercontent.com/25342410/106477345-05a53900-64e3-11eb-9d03-777917222d82.gif)
