### ISSUE TITLE
Can`t delete Boards from Projects

### ISSUE THREAD

**Issue by BaxAndrei** [go-gitea/gitea#14546]
- Gitea version (or commit ref): 1.13.2
- Git version: 2.23.0
- Operating system: CentOS Linux release 7.7.1908
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
- Log gist:
![image](https://user-images.githubusercontent.com/12484505/106583063-56ea1280-654d-11eb-9898-610196bd5af7.png)

## Description
I can`t get any Board from any Project deleted, only solution is to remove entire project.
...

## Screenshots
![image](https://user-images.githubusercontent.com/12484505/106582898-2c985500-654d-11eb-92ad-9430a074a2ef.png)

**Comment by BaxAndrei** [comment]
UPDATE: Editing doesn't work either.

**Comment by 6543** [comment]
@BaxAndrei I can not reproduce this issue ... we need more logs

https://docs.gitea.io/en-us/logging-configuration/

**Comment by BaxAndrei** [comment]
After switching from linux to windows, the problem disappeared. Possibly the reason was the http proxy we were using. Thanks.
