### ISSUE TITLE
try.gitea.io almost completely unavailable

### ISSUE THREAD

**Issue by delvh** [go-gitea/gitea#14547]
- Gitea version (or commit ref): 1.14.0+dev-647-g6fc2d36fb
- Can you reproduce the bug at https://try.gitea.io:
  - Yes, otherwise this issue would not exist
- Log gist: Unfortunately, I have no access to the logs of try.gitea.io

## Description
Currently signing in to `try.gitea.io` is absolutely impossible:
No matter whether you check `Remember this device` or not, you simply get a `500 - internal server error` afterwards.

Even worse: Any link pointing to another page on `try.gitea.io` also currently returns a `500` response.
Oh, now even the sign in dialog does not get displayed anymore and throws a 500 instead.
The only links that currently seem to be working are `Register` and  `License`.

**Comment by lunny** [comment]
Disk is full. I have removed some files and now it's up.
