### ISSUE TITLE
Autofocus OTP input field on login screen

### ISSUE THREAD

**Issue by xoxys** [go-gitea/gitea#1455]
- Gitea version (or commit ref): 1.1.0
- Git version: Not relevant
- Operating system: Linux 
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
Another "small" bug. The input field for OTP has no focus after input username/password so you have to click inside before you can type in OTP. I think we should make this field autofocused.

**Comment by lunny** [comment]
resolved by #1460
