### ISSUE TITLE
Any way to insert image on issue page

### ISSUE THREAD

**Issue by iqiziqi** [go-gitea/gitea#14558]
- Gitea version (or commit ref): 1.13.2
- Git version: 2.30
- Operating system: OpenSUSE
  
  
  
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
- Log gist:

## Description

I can't find any way to insert image on issue page. I have to upload an attachment, then edit this comment. Is here any better way to insert images?

**Comment by lunny** [comment]
Can you try to paste image from clipboard on the issue input box?

**Comment by iqiziqi** [comment]
When i paste from clipboard on the issue input box, just show the path of image.

![图片](https://user-images.githubusercontent.com/8640316/106846783-81240780-66e8-11eb-8459-1c0a40881571.png)

**Comment by iqiziqi** [comment]
My operation system is OpenSUSE Tumbleweed, and I use KDE.
I think it just copy my file system path, when I copy file on Dolphin, because paste on text editor, just show the path of image too.

**Comment by noerw** [comment]
This is a limitation of browsers (it won't just load a file from a path that by chance was on clipboard). -> wontfix

I use nautilus on gnome, and also get a similar output when pasting
```
x-special/nautilus-clipboard
copy
file:///home/norwin/Pictures/Screenshot%20from%202021-03-21%2021-58-04.png
```

Opening the image, and then doing `ctrl+c`, and `ctrl+v` in gitea input works fine.
