### ISSUE TITLE
Gitea can't run due to GLIBC version incompatibility 

### ISSUE THREAD

**Issue by typeless** [go-gitea/gitea#14576]
- Gitea version (or commit ref):
```
go version go1.15.5 linux/amd64
```
- Git version:
2.26

- Operating system:
  Ubuntu 20.04.2 LTS

- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite

## Description
I built Gitea for my Synology NAS and it can't run.
```
/volume1/homes/git/gitea/gitea: /lib/libc.so.6: version `GLIBC_2.28' not found (required by /volume1/homes/git/gitea/gitea)
````
I suspect this would affect all users who run Gitea on older embedded devices (and unable to upgrade the system).

**Comment by typeless** [comment]
A quick fix is to use musl libc with the following build command:
```
CC=musl-gcc LDFLAGS='--linkmode external --extldflags "-static"' TAGS='bindata sqlite sqlite_unlock_notify' make build
```
I can send a patch for that. But I am not sure if I should integrate it into the default build target, or add the new make target.
Maybe leaving the issue open for others to consult is just good enough.

**Comment by lunny** [comment]
Is this a Golang related problem?

**Comment by typeless** [comment]
@lunny I don't think so. It's not strictly a Gitea problem either. But it does upset users when it happened to them (read: me) and the root cause is not obvious in the first place. All it shows is Gitea broken after an upgrade.

**Comment by zeripath** [comment]
You're actually missing a few other tags that should be added for completely static builds. `netgo` and `osusergo` jump to mind.

**Comment by typeless** [comment]
@zeripath Thanks for the information. I was not aware of those build tags.
