### ISSUE TITLE
LastCommit cache is broken by default on memcached

### ISSUE THREAD

**Issue by CirnoT** [go-gitea/gitea#14571]
- Gitea version (or commit ref): 1.14.0+dev-607-g012bf388a

## Description

Default TTL for LastCommit cache is 8760h or 365 days, however when supplying TTL in seconds to memcached, the maximum value is 2592000. Any value of seconds above that is treated as unix timestamp.

Due to this, LastCommit cache is always expired at the time of insertion (unix timestamp 31536000 is 1971-01-01T00:00:00+00:00)

**Comment by lunny** [comment]
Could you paste your configuration of these sections?

**Comment by CirnoT** [comment]
Broken:
```
[cache]
ENABLED  = true
ADAPTER  = memcache
HOST = gitea-mc:11211
```

Working:
```
[cache]
ENABLED  = true
ADAPTER  = memcache
ITEM_TTL = 36h
HOST = gitea-mc:11211
```

From https://github.com/go-gitea/gitea/blob/41c0776568b3fa1bf825439103085146260e16a8/modules/setting/cache.go#L46

**Comment by CirnoT** [comment]
Ref.:

https://github.com/memcached/memcached/blob/c472369fed5981ba8c004d426cee62d5165c47ca/memcached.h#L916

https://github.com/memcached/memcached/blob/c472369fed5981ba8c004d426cee62d5165c47ca/doc/protocol.txt#L132-L144
