### ISSUE TITLE
InitLocales() [F] Failed to set messages to en-US: Lang already exists

### ISSUE THREAD

**Issue by Kreyren** [go-gitea/gitea#14577]
- Gitea version (or commit ref): https://github.com/go-gitea/gitea/commit/014313134f72ebb2ca57eb2e5cd42726231f8fff, https://github.com/go-gitea/gitea/commit/4457d0e8d9b09e7577242a8bc005ef9d43be4e8c
- Git version: 2.29.2
- Operating system: Ubuntu in Gitpod
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [X] SQLite3
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Unable (present during a deployment)
- Log gist: https://gist.githubusercontent.com/Kreyren/e4dcd14f49c2b7f2cbfe3a196625371d/raw/a87e9d6326c0205c1b2c6df273d528522c9f96c2/gistfile1.txt

## Steps to reproduce
1. Clone gitea and change tag on version 2.13.2
2. `docker build -t kreyren -f Dockerfile.rootless .`
3. `docker run -it -p 3000:3000 kreyren`
4. Open `localhost:3000` and press `Install Gitea`
5. Expect mentioned failure

## Screenshots

![image](https://user-images.githubusercontent.com/11302521/107000293-eb3fb980-6787-11eb-809a-06a54fcb7f7f.png)

**Comment by lunny** [comment]
Looks like it's master branch but not v1.13.2

**Comment by Kreyren** [comment]
@lunny behavior observer on https://github.com/go-gitea/gitea/commit/014313134f72ebb2ca57eb2e5cd42726231f8fff as well (tag `v1.13.2`)
