### ISSUE TITLE
Several same PASSWD variable, imposible automate config!

### ISSUE THREAD

**Issue by minzak** [go-gitea/gitea#14585]
How to replace needed PASSWD variables, especially if we used ansible?

Because we have PASSWD in [database] section
https://github.com/go-gitea/gitea/blob/master/custom/conf/app.example.ini#L419

and in [mailer] section!
https://github.com/go-gitea/gitea/blob/master/custom/conf/app.example.ini#L739

Need to replace, extend Names.

**Comment by techknowlogick** [comment]
The way ini works is that they aren't the same variable as they are in different sections.

**Comment by minzak** [comment]
I would like to see your example in Ansible, for deployment, managing these variables)
In any way - good way in naming - make All names unique.
