### ISSUE TITLE
Users are missing from the webUI

### ISSUE THREAD

**Issue by bram-nijenkamp** [go-gitea/gitea#14584]
- Gitea version (or commit ref): 1.14.0+dev-635-gf761c82c9
- Git version: 2.30.0
- Operating system: Docker latest
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
 
## Description
Hello guys, I am currently having at least a user management problem. My main user is was once admin. Never having to look at it I just wanted to access the admin panel and nope, not admin anymore.

Thus I created a temporary admin account via the cli. The problem is that I don't see any users in the admin panel. When I list them in the cli they are thankfully still there. I can also still log into them. Does anybody know how to fix this?

I have also already tried to recreate all tables through the cli.

Updated:
I cheated my way with some url modification by changing the user_id. This way I was able to change the user to admin which I wanted. But now I only see the admin users incl. the new root user?
...

## Screenshots
<img width="1153" alt="Untitled 2" src="https://user-images.githubusercontent.com/14978036/107122898-d99b0680-689a-11eb-9711-e528c0aa6e45.png">

<img width="1176" alt="image" src="https://user-images.githubusercontent.com/14978036/107122748-d3f0f100-6899-11eb-8919-324e1c194226.png">
<img width="627" alt="Untitled" src="https://user-images.githubusercontent.com/14978036/107122878-b83a1a80-689a-11eb-977a-54a58fc45b53.png">

**Comment by zeripath** [comment]
agh... you were hit by the bug with #14387

**Comment by zeripath** [comment]
you're gonna need to look at a backup of your users table and restore it.

**Comment by 6543** [comment]
sorry...! @FrozenSource if you need help on fixing DB just ask on Discord ...

**Comment by FrozenSource** [comment]
> sorry...! @FrozenSource if you need help on fixing DB just ask on Discord ...

Ok will do that then! I’m using a 2 week parity backup and have a long term hard backup. Putting those back didn’t solve it so I take it I will need to do it by hand.

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
> > sorry...! @FrozenSource if you need help on fixing DB just ask on Discord ...
> 
> Ok will do that then! I’m using a 2 week parity backup and have a long term hard backup. Putting those back didn’t solve it so I take it I will need to do it by hand.

been there where you are, too.
unless your rollback method brings back the db in the exact state it was two weeks ago (if that's even desirable), you're left with missing data in the user table.. I had to manually put it back where it was, one by one (small instance so no worries). should you have a massive data set, it'd probably be worth it to write a little fix-up sql script to export only the missing data and have it automatically placed back where they belong.

as said above, pop a message in discord if you need help and glhf.

p.s. this was when I thanked myself for the backups :D

**Comment by techknowlogick** [comment]
Closing as this has been since handled in discord.
