### ISSUE TITLE
Discussion/mailinglist/forum?

### ISSUE THREAD

**Issue by monnier** [go-gitea/gitea#1458]
Like martinellison said in  #1426:

> (This is a support question; usually I ask support questions on a forum but gitea does not appear to have
> a forum; apologies then if this is the wrong place, but please advise the correct place and update the 
> documentation).

I do not see any indication in the documentation about where support questions should go nor where I can follow discussions about the development of Gitea.

**Comment by kolaente** [comment]
Probably on Gitter:
Join the chat: https://gitter.im/go-gitea/gitea

**Comment by andreynering** [comment]
- There's the GitHub issue, just the place we are.
- Most of the team is active on Gitter. [Room 1](https://gitter.im/go-gitea/gitea). [Room 2](https://gitter.im/go-gitea/develop).
- There's a [mailing list](https://groups.google.com/forum/#!forum/gitea), but nobody uses it.
- There's a #gitea channel on [Gopher's Slack](https://gophers.slack.com/), but also nobody uses it.

I'd like to have a user forum actually. Other popular Go projects have one (Gogs, Hugo, Caddy, others), but it should have enough users to be worth.

**Comment by techknowlogick** [comment]
Closing this as Gitea now links to discord as official chat (https://discord.gg/NsatcWJ), and forum (https://discourse.gitea.io/) on it's home page, docs, and blog (all in the theme, in the top nav bar)
