### ISSUE TITLE
Repository link on controller panel return 404 page

### ISSUE THREAD

**Issue by lwhile** [go-gitea/gitea#1459]
- Gitea version (or commit ref):1.1.0
- Git version:1.8.3.1
- Operating system:Ubuntu 14.04 LTS
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description

See screenshots

## Screenshots

![](http://on51si7u9.bkt.clouddn.com/2017-04-07%2013:00:05%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE.png)

clikc link "lwhile/monitorDoc" will return 404 page

![](http://on51si7u9.bkt.clouddn.com/2017-04-07%2013:03:00%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE.png)

the html code of the link:

    <a href="%5C%22/lwhile/monitorDoc%5C%22" rel="nofollow">lwhile/monitorDoc</a>

But I can access  the repository by other link.

**Comment by cez81** [comment]
Fixed in upcoming 1.1.1, see #1181
