### ISSUE TITLE
Visual glitch in contributor activity graphic

### ISSUE THREAD

**Issue by thomas-mc-work** [go-gitea/gitea#14605]
- Gitea version (or commit ref): 1.13.1
- Git version: 2.20.1
- Operating system: Debian 10.1, used gitea download from github releases
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
- Log gist:

## Description

The 'b' of 'Feb' is cropped slightly at the right side.

## Screenshots

![image](https://user-images.githubusercontent.com/6542498/107159372-d2a1f000-698f-11eb-95a4-21c38393a1f1.png)

**Comment by vnkmpf** [comment]
The glitch is present in 1.13.x, but as stated, cannot be reproduced at try.gitea.io.
Looks good on 1.14 branch - both user profile and dashboard.
![image](https://user-images.githubusercontent.com/30214167/107673100-f158fd00-6c95-11eb-93d3-9c1dcf87a0d4.png)

**Comment by thomas-mc-work** [comment]
Well, that'd be fine for me. Feel free to close the issue if you're satisfied with the solution.
