### ISSUE TITLE
SSH Sometimes Chooses Key With Weaker Permissions

### ISSUE THREAD

**Issue by mikeperalta1** [go-gitea/gitea#14617]
- Gitea version (or commit ref): 1.13.1
- Git version: 2.29.2
- Operating system: Fedora 33

  
Built from source using normal instructions.

  
Running the built binary as a systemd service.

  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X] No
- Log gist: I will include some SSH logs in the next comment.

## Description

Short idea:

Gitea seems to accept the first SSH key you offer, then use that to determine whether you have access to a repo or not. However, in some cases, the first key your client offers may have lesser privileges than a key that would be later offered. Thus, you may be denied access to a repo based on one of your keys, while you actually do have access with a different key.

Slightly longer version:

My old rsa key was lurking in an old repository as a deploy key. I then upgraded to a new ed25519 key, added it to my Gitea account, and attempted to fetch a different repo. Gitea accepted my old rsa key (because it was visible as a deploy key within an old repo before), and decided I had no permissions for the repo at hand. Yet, my newer ed25519 key had full account permissions.

I feel Gitea should check all SSH keys you're offering and choose the one with the most access. In my case, my old rsa key was only authorized to access one old repo, while my newer ed25519 key was authorized to access any repo under my account. If it is not possible/easy to tell openssh to try all keys in sequence until one has access, then there should probably be some sort of a log of recent authentications where you can see which keys were recently auth'ed and then denied access to a repo. Perhaps even, an admin area where recently denied keys (public sigs) can be listed, alongside the repos/accounts they appear, so a user like me could quickly debug the situation.

Of course, when I specified the newer ed25519 key:

```GIT_SSH_COMMAND='ssh -i /path/to/my/new/ed25519' git fetch```

Then everything worked.

Took me awhile to understand what was going wrong, as Gitea doesn't seem to currently have any sort of report to alert me to the fact my older key was accepted instead of my newer key. I had to trace with ssh verbosity, then manually troll through MariaDB tables.

My current solution will just be to remove the old rsa key from that repo. But I feel this issue could be very confusing for some people. I'm not a complete newbie and this cost me almost a half hour of scratching my head.

**Comment by mikeperalta1** [comment]
I don't know if this will be helpful, but here's a log of SSH client verbose output. You can see the rsa key was tried first, then once accepted, no other keys were tried. I feel it might be a good idea to try every key until one with the appropriate level of access is found.

(some values redacted)

```
me@bedroom:~/Desktop/my-repo$ GIT_SSH_COMMAND='ssh -v' git fetch
OpenSSH_8.3p1 Ubuntu-1, OpenSSL 1.1.1f  31 Mar 2020
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: Connecting to git.home [192.168.1.101] port 3222.
debug1: Connection established.
debug1: identity file /home/redacted/.ssh/id_rsa type 0
debug1: identity file /home/redacted/.ssh/id_rsa-cert type -1
debug1: identity file /home/redacted/.ssh/id_dsa type -1
debug1: identity file /home/redacted/.ssh/id_dsa-cert type -1
debug1: identity file /home/redacted/.ssh/id_ecdsa type -1
debug1: identity file /home/redacted/.ssh/id_ecdsa-cert type -1
debug1: identity file /home/redacted/.ssh/id_ecdsa_sk type -1
debug1: identity file /home/redacted/.ssh/id_ecdsa_sk-cert type -1
debug1: identity file /home/redacted/.ssh/id_ed25519 type 3
debug1: identity file /home/redacted/.ssh/id_ed25519-cert type -1
debug1: identity file /home/redacted/.ssh/id_ed25519_sk type -1
debug1: identity file /home/redacted/.ssh/id_ed25519_sk-cert type -1
debug1: identity file /home/redacted/.ssh/id_xmss type -1
debug1: identity file /home/redacted/.ssh/id_xmss-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_8.3p1 Ubuntu-1
debug1: Remote protocol version 2.0, remote software version Go
debug1: no match: Go
debug1: Authenticating to git.home:3222 as 'git'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256@libssh.org
debug1: kex: host key algorithm: ssh-rsa
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ssh-rsa SHA256:redacted
debug1: Host '[git.home]:3222' is known and matches the RSA host key.
debug1: Found key in /home/redacted/.ssh/known_hosts:7
debug1: rekey out after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey in after 134217728 blocks
debug1: Will attempt key: /home/redacted/.ssh/id_rsa RSA SHA256:redacted
debug1: Will attempt key: /home/redacted/.ssh/id_dsa 
debug1: Will attempt key: /home/redacted/.ssh/id_ecdsa 
debug1: Will attempt key: /home/redacted/.ssh/id_ecdsa_sk 
debug1: Will attempt key: /home/redacted/.ssh/id_ed25519 ED25519 SHA256:redacted
debug1: Will attempt key: /home/redacted/.ssh/id_ed25519_sk 
debug1: Will attempt key: /home/redacted/.ssh/id_xmss 
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey
debug1: Next authentication method: publickey
debug1: Offering public key: /home/redacted/.ssh/id_rsa RSA SHA256:redacted
debug1: Server accepts key: /home/redacted/.ssh/id_rsa RSA SHA256:redacted
debug1: Authentication succeeded (publickey).
Authenticated to git.home ([192.168.1.101]:3222).
debug1: channel 0: new [client-session]
debug1: Entering interactive session.
debug1: pledge: network
debug1: Sending environment.
debug1: Sending env LANG = en_US.UTF-8
debug1: Sending command: git-upload-pack '/org-name-redacted/repo-name-redacted.git'
Gitea: Unauthorized
Public (Deploy) Key: 20:me@bedroom.home is not authorized to read org-name-redacted/repo-name-redacted.
debug1: client_input_channel_req: channel 0 rtype exit-status reply 0
debug1: channel 0: free: client-session, nchannels 1
debug1: fd 0 clearing O_NONBLOCK
Transferred: sent 3628, received 2028 bytes, in 0.1 seconds
Bytes per second: sent 32887.1, received 18383.4
debug1: Exit status 1
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by lunny** [comment]
I think the process is under the control of OpenSSH and if there is no configuration exposed we can do nothing.

**Comment by zeripath** [comment]
@lunny is correct here.

We can do nothing to improve this situation.

If you want to use a specific key set your clients .ssh config appropriately, or use a specific environment variable trick to pass arguments.

At the end of the day as far as openssh is concerned it has offered a key and been authenticated successfully with it. That an authorization layer that it knows nothing about says that that key is not authorized is not its problem.

Things would be better if we could use the username but we can't.

Therefore I'm afraid we have to close this as invalid.

**Comment by mikeperalta1** [comment]
> @lunny is correct here.
> 
> We can do nothing to improve this situation.
> 
> If you want to use a specific key set your clients .ssh config appropriately, or use a specific environment variable trick to pass arguments.
> 
> At the end of the day as far as openssh is concerned it has offered a key and been authenticated successfully with it. That an authorization layer that it knows nothing about says that that key is not authorized is not its problem.
> 
> Things would be better if we could use the username but we can't.
> 
> Therefore I'm afraid we have to close this as invalid.

If you look at Gitea logs, it shows a database query to the public_key table. Therefore it seems Gitea is at least being given the chance to auth a public key or not.

Is Gitea also being given the path to the repository during the query? If not then I guess there's nothing that can be done. However, if Gitea is being given the path to the repository during the query (or the full command line, or whatever), then there's an opportunity for Gitea to validate permissions between validating the public_key and responding to the SSH connection request.

**Comment by mikeperalta1** [comment]
Should I open a new issue for the separate issue of an admin area that could report recently auth'ed keys, in order to help admins debug this sort of thing?

**Comment by zeripath** [comment]
By the time Gitea gets to check authorization open SSH has selected the key and has finished authentication. 

There is no opportunity to drop back a different key and OpenSSH doesn't get told the repository path so there's nothing that can be done. 

As far as gitea is concerned the other keys do not exist. Gitea gets the repository path that's how it can authorize. OpenSSH doesn't.

If we could SSH to multiple users - e.g. you ssh'd to owner/reponame@gitea then what you suggest could work - but we don't - we SSH as git@gitea and then use the path. The path is hidden from SSH's key exchange. 

The internal SSH built into gitea could be changed to allow the above option but - an OpenSSH system would not work.
