### ISSUE TITLE
API: Ability to create a commit including multiple files 

### ISSUE THREAD

**Issue by d-lunyov** [go-gitea/gitea#14619]
There are three endpoints to make a commit via API: [repoUpdateFile](https://try.gitea.io/api/swagger#/repository/repoUpdateFile), [repoCreateFile](https://try.gitea.io/api/swagger#/repository/repoCreateFile), [repoDeleteFile](https://try.gitea.io/api/swagger#/repository/repoDeleteFile). But there are no way to make a commit, that contains a multiple changes in multiple files.

**Comment by 6543** [comment]
What about a endpoint, that apply diff & patch files?

cc @zeripath

**Comment by zeripath** [comment]
Heheh

Ok I'll simplify and propose the patch endpoint pr. We'll get the rest of stuff sorted later.

**Comment by zeripath** [comment]
@d-lunyov why aren't you creating a temporary working branch to commit stuff to and the merge it in to your primary branch?

**Comment by d-lunyov** [comment]
> @d-lunyov why aren't you creating a temporary working branch to commit stuff to and the merge it in to your primary branch?

@zeripath This is exactly what I do. But I think this is a workaround. In addition, the number of requests to the server increases in proportion to the number of files.

Another git-providers offers:
**Github** rest api commit steps: 
1) [POST a new tree](https://docs.github.com/en/rest/reference/git#create-a-tree) 
2) [Create a new commit referred to the new tree SHA](https://docs.github.com/en/rest/reference/git#create-a-commit)
3) [Patch a reference to set a new commit SHA](https://docs.github.com/en/rest/reference/git#update-a-reference)

**Gitlab**: [create a commit with multiple files and actions endpoint](https://docs.gitlab.com/ee/api/commits.html#create-a-commit-with-multiple-files-and-actions)

**Bitbucket**:  [create new commits in the repository by uploading files](https://developer.atlassian.com/bitbucket/api/2/reference/resource/repositories/%7Bworkspace%7D/%7Brepo_slug%7D/src#post)

**Azure**: [Push changes to the repository with multiple actions](https://docs.microsoft.com/en-us/rest/api/azure/devops/git/pushes/create?view=azure-devops-rest-6.0)

**Bitbucket-server** also does not propose a simply-way to create a multiple files to commit, so I'm using a workaround with temporary branch.

**Comment by malarinv** [comment]
Is there any progress on this issue? currently I'm blocked by this on a pr I'm working on to enable support for Gitea on https://github.com/fluxcd/go-git-providers . It is used by https://github.com/fluxcd/flux2 to support git resource reconciliation logic.
. see similar api usage from other providers at 
* https://github.com/fluxcd/go-git-providers/blob/main/github/client_repository_commit.go#L72
* https://github.com/fluxcd/go-git-providers/blob/main/gitlab/client_repository_commit.go#L67

**Comment by lunny** [comment]
I think we need both patch upload endpoint and multiple files changed endpoint.

**Comment by denyskon** [comment]
Are there any updates on that? I created a gitea backend for [Static CMS](https://github.com/StaticJSCMS/static-cms), but without this feature I'm dependent on a hack which fails regularly....

**Comment by jimafisk** [comment]
We're trying to implement Gitea as a backend for [Plenti](https://plenti.co/) too, this unfortunately is a blocker for us. Per @d-lunyov's comment, the way GitLab uses actions works really well for our use-case.
