### ISSUE TITLE
Docs: docker tag 1.13.2-rootless is referred to, but does not exist.

### ISSUE THREAD

**Issue by flickerfly** [go-gitea/gitea#14614]
Documents suggest their should be a 1.13.2-rootless docker image: https://docs.gitea.io/en-us/install-with-docker-rootless/
This does not exist and #13914 suggests that this should be brought up in #10154 to be backported; however, comments there are closed to new contributors. Could this be backported to 1.13.2 to make the documents correct? 

- Gitea version (or commit ref): 1.13.2

Please excuse not filling out the irrelevant info requests.

**Comment by lafriks** [comment]
Rootless will be available only starting with 1.14
