### ISSUE TITLE
SIGSEGV when NO_REPLY_ADDRESS = noreply.%(DOMAIN)s

### ISSUE THREAD

**Issue by cdr8H** [go-gitea/gitea#14610]
- Gitea version (or commit ref): 1.6.4 built with: bindata, sqlite
- Git version:
- Operating system: https://dl.gitea.io/gitea/1.6.4/gitea-1.6.4-linux-amd64
  
  
  
- Database (use `[x]`):
  - [X ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ X] Not relevant
- Log gist:

## Description

When using the default:

**NO_REPLY_ADDRESS = noreply.%(DOMAIN)s**

gitea produces a SIGSEGV:

2021/02/08 05:28:25 AppPath: /var/lib/gitea/gitea
2021/02/08 05:28:25 AppWorkPath: /var/lib/gitea
2021/02/08 05:28:25 Custom path: /var/lib/gitea
2021/02/08 05:28:25 Log path: /var/lib/gitea/log
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x7f09a4]

goroutine 1 [running]:
code.gitea.io/gitea/vendor/gopkg.in/ini%2ev1.(*Key).transformValue(0xc0005725a0, 0xc00056c2a1, 0x12, 0x1581235, 0x10)
        /go/src/code.gitea.io/gitea/vendor/gopkg.in/ini.v1/key.go:123 +0xa4
code.gitea.io/gitea/vendor/gopkg.in/ini%2ev1.(*Key).String(0xc0005725a0, 0x0, 0x0)
        /go/src/code.gitea.io/gitea/vendor/gopkg.in/ini.v1/key.go:130 +0x3d
code.gitea.io/gitea/vendor/gopkg.in/ini%2ev1.(*Key).MustString(0xc0005725a0, 0x158943e, 0x13, 0xc0005725a0, 0x1)
        /go/src/code.gitea.io/gitea/vendor/gopkg.in/ini.v1/key.go:202 +0x2f
code.gitea.io/gitea/modules/setting.newService()
        /go/src/code.gitea.io/gitea/modules/setting/setting.go:1251 +0x6d6
code.gitea.io/gitea/modules/setting.NewServices()
        /go/src/code.gitea.io/gitea/modules/setting/setting.go:1601 +0x22
code.gitea.io/gitea/routers.NewServices()
        /go/src/code.gitea.io/gitea/routers/init.go:40 +0x22
code.gitea.io/gitea/routers.GlobalInit()
        /go/src/code.gitea.io/gitea/routers/init.go:53 +0x238
code.gitea.io/gitea/cmd.runWeb(0xc000338a00, 0x0, 0x0)
        /go/src/code.gitea.io/gitea/cmd/web.go:121 +0xaa
code.gitea.io/gitea/vendor/github.com/urfave/cli.HandleAction(0x13d7a40, 0x15dcf98, 0xc000338a00, 0xc00014ef00, 0x0)
        /go/src/code.gitea.io/gitea/vendor/github.com/urfave/cli/app.go:471 +0xad
code.gitea.io/gitea/vendor/github.com/urfave/cli.Command.Run(0x15687ed, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x158ea69, 0x16, 0x0, ...)
        /go/src/code.gitea.io/gitea/vendor/github.com/urfave/cli/command.go:191 +0x96d
code.gitea.io/gitea/vendor/github.com/urfave/cli.(*App).Run(0xc00016eea0, 0xc0000b0040, 0x4, 0x4, 0x0, 0x0)
        /go/src/code.gitea.io/gitea/vendor/github.com/urfave/cli/app.go:241 +0x5a2
main.main()
        /go/src/code.gitea.io/gitea/main.go:53 +0x3d1

Workaround: changing NO_REPLY_ADDRESS  to f.ex. '123@nowhere.com'  ...

**Comment by techknowlogick** [comment]
please upgrade to latest stable version, 1.6.4 is significantly out of date.

**Comment by cdr8H** [comment]
I stumbled into the bug, when upgrading an older Version (1.0 any) and using the instructions from here: [https://docs.gitea.io/en-us/upgrade-from-gogs/#upgrading-from-a-more-recent-version-of-gogs](url) 

<img width="495" alt="gitea" src="https://user-images.githubusercontent.com/6630333/107182602-59c98500-69dd-11eb-9b38-0724392c437f.png">

**Comment by zeripath** [comment]
When using the default:

    NO_REPLY_ADDRESS = noreply.%(DOMAIN)s

There is no such default. You have set this in your app.ini - clearly by copying the app.sample.ini / app.example.ini as your app.ini.

You are not supposed to do that, and in fact it is warned against.

Do not set settings in your app.ini that you do not understand.

Do not copy app.ini.sample or app.example.ini as your app.ini - just set the settings you require.
