### ISSUE TITLE
Star counter by repos with long names misaligned in dashboard

### ISSUE THREAD

**Issue by hexa29** [go-gitea/gitea#14613]
- Gitea version (or commit ref): `1.14.0+dev-676-gd96f13c41`
- Git version: `git version 2.30.0.666.g8944e3a3a1`
- Operating system: Arch Linux
  
  
  
- Database:
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] No

## Description

Repository star counter in dashboard is incorrectly offset in case of a long repo name. The name is correctly truncated but the counter gets pushed too far to the right.

## Screenshots
![grim-2021-02-08_20-11-00](https://user-images.githubusercontent.com/12410899/107269568-148f6c80-6a4a-11eb-827c-5c598d419c09.png)

**Comment by zeripath** [comment]
Looks like: 

https://github.com/go-gitea/gitea/blob/4cffc46f651205b9d7eb0b1df46dd6117c6d95e9/templates/user/dashboard/repolist.tmpl#L126

needs to have a style of `max-width: 90%` applied but that doesn't really make sense with flex box.

Oh how I hate CSS

**Comment by zeripath** [comment]
Fixed by #14767
