### ISSUE TITLE
Add support for path parameter to get a list of commits API

### ISSUE THREAD

**Issue by d-lunyov** [go-gitea/gitea#14618]
The current implementation of [repoGetAllCommits](https://try.gitea.io/api/swagger#/repository/repoGetAllCommits) API does not provide the ability to specify a `path` query parameter.

This limits the API functionality to retrieve the only full commits list, while it would be expected to be able to fetch only commits containing specified file path to be returned.

**Comment by denyskon** [comment]
Implemented by #17652
