### ISSUE TITLE
Cannot change max size of attachments via env variables on docker

### ISSUE THREAD

**Issue by AuspeXeu** [go-gitea/gitea#14628]
- Gitea version (or commit ref):
- Git version: 1.13.2
- Operating system: docker on centos
- Database (use `[x]`):
  - [x] MySQL

## Description
setting the env var `GITEA__ATTACHMENT__MAX_SIZE=40` in docker-compose is ignored and the limit is still 4MB

## Screenshots
![image](https://user-images.githubusercontent.com/2115696/107514391-e4f77600-6ba9-11eb-9971-c8caf56399cc.png)

**Comment by techknowlogick** [comment]
most of the env vars passed to docker are only used to cerate the app.ini if it doesn't yet exist. If app.ini already exists then you'll need to configure it there. You appear to be using the format for the contrib helper script https://github.com/go-gitea/gitea/tree/master/contrib/environment-to-ini however that is not built into the default docker image.

**Comment by AuspeXeu** [comment]
This would be a nice addition though, no ? :)
