### ISSUE TITLE
Background mirroring with progress/failure indication

### ISSUE THREAD

**Issue by lofidevops** [go-gitea/gitea#1463]
- Gitea version (or commit ref): 1.1.0
- Git version: 2.9.3
- Operating system: Ubuntu 16.10
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist: N/A

## User story

After initiating a mirror process, I want to be able to close the tab the mirror started in, so that I don't accidentally terminate the process. I also expect to be able to follow the process progress, so that I know how far along it is, and that it is still underway (it has not hung or failed).

## Proposals

* One solution might be a page with a progress bar (and error message, if applicable) for each mirroring process.
* Another solution would be the ability to initiate a mirror from the command line (and report progress/errors there).

**Comment by pgaskin** [comment]
A few things I want to say:

- You can close the tab and the mirror will still happen.
- You can see if the mirror is still happening on the monitoring page in the admin ui.

Overall, I think this would be a good idea.

**Comment by lofidevops** [comment]
This suggestion was prompted by a failed mirror attempt. It sounds like the existing functionality already addresses, and maybe this is just needs:

* an on-screen message telling you that you can navigate away, and where to follow mirror progress
* a note in the documentation about how it works

**Comment by lunny** [comment]
Now the mirroring is background but with no progress.
