### ISSUE TITLE
API: unable to post a first file to the empty repository

### ISSUE THREAD

**Issue by d-lunyov** [go-gitea/gitea#14633]
Repository was created with an API call [createCurrentUserRepo](http://localhost:3000/api/swagger#/repository/createCurrentUserRepo) and parameter "auto_init" set to false.

After that I want to create a first commit with README.md file, with the [repoCreateFile](http://localhost:3000/api/swagger#/repository/repoCreateFile) request:
`POST http://localhost:3000/api/v1/repos/lunik/apiRepoTest1/contents/README.md`
with the next body:
`{
  "content":"aGVsbG8==",
  "message": "initial"
}`

I've got the next response (also this is illegal JSON):

> {"message":"repo is empty","url":"http://localhost:3000/api/swagger"}
> {"message":"illegal base64 data at input byte 8","url":"http://localhost:3000/api/swagger"}

**Comment by delvh** [comment]
This is somewhat related to #6918, I'd say: The ability to create files on an empty repository (using the web interface).
There however, the API most likely did not get updated as well to allow for that. I'll ask there whether a) it has already been fixed b) that branch is the correct branch for that or whether c) a new branch should be opened for this.

**Comment by delvh** [comment]
Okay, as it seems, this issue will be blocked until #6918 has been merged.
Afterwards, it should be simple to fix.
