### ISSUE TITLE
[Thread] CSS Optimization and Testing Summary

### ISSUE THREAD

**Issue by kdumontnu** [go-gitea/gitea#14639]
I wanted to put together a list of proposals for CSS refactor and consolidation.

I've been working on some styling bugfixes lately and found the state of the CSS code to be quite frustrating. I wanted to discuss some options to improve performance, consistency, and reduce bugs. 

### UI Bugs
I'm fairly new to this project, but I've found quite a few UI bugs that really take away from the professional feel of Gitea. Many are reported in [open issues](https://github.com/go-gitea/gitea/issues?q=is%3Aopen+is%3Aissue+label%3Akind%2Fui), but most are not. 

Here are a couple I found just now clicking around:
![image](https://user-images.githubusercontent.com/12700993/107597488-02dbcf80-6bd8-11eb-9f6c-a8074e74ae61.png)
![image](https://user-images.githubusercontent.com/12700993/107597887-46830900-6bd9-11eb-8503-bed4fa5dd2f8.png)

### Consistency
There is a lot of inconsistency with how classes are defined and styled. There is some use of `semantic.css`, but also `helpers.less` (which is completely counter to Semantic UI ideology), and extreme usage of class overrides in `web_src/less`.
This makes it very difficult to develop, but also results in some visual discrepancies. For instance, see the badges being styled 3 different ways below:
![image](https://user-images.githubusercontent.com/12700993/107597275-67e2f580-6bd7-11eb-9203-89b93d49a45d.png)
![image](https://user-images.githubusercontent.com/12700993/107597344-906aef80-6bd7-11eb-88b8-3b16fc9912c5.png)

Further, we are effectively hard-forked from Fomantic source because of [changes](https://github.com/go-gitea/gitea/commits/master/web_src/fomantic/build) in `./web_src/fomantic/build/semantic.css`. I'm sure there were good reasons for these changes, but it will increasingly become impossible to update the dependency (btw, Semantic has support for [theming](https://semantic-ui.com/usage/theming.html), even demonstrating how to emulate [GitHub's old styling](https://semantic-org.github.io/example-github/)).

### Performance
index.css is flagged by Chrome dev tools as the highest network utilization when loading a page and a critical-path file, which takes 500ms + to load on my computer with a good internet connection (with caching disabled).
![image](https://user-images.githubusercontent.com/12700993/107595365-a83f7500-6bd1-11eb-8492-b6d36ed22184.png)

The is largely because of the general file size.
Priority: `Highest`
Encoded Data: `128 kB`
Decoded Body: `845 kB`

The utilization of CSS classes on a given page is extremely low. 96% of the css classes are unused on any given page:
![image](https://user-images.githubusercontent.com/12700993/107595586-5519f200-6bd2-11eb-857e-89ae058ae39e.png)

## Proposed Solutions
I'm not writing this for the purpose of putting the project or anyone down - there is incredible progress on the app! However, a lot of the focus is on adding new features without much consideration for the architecture. It's less glorious, but important stuff 😄 

I propose the following tentative solutions:
- [ ] Create a style guide for Gitea
- [ ] Review new PRs against the style guide
- [ ] Add a CI test for CSS - there are many options to choose from ([BackstopJS](https://github.com/garris/BackstopJS), Karma, etc.)
- [ ] Use webpack plugin to remove unused CSS ([PurifyCSS](https://chriscourses.com/blog/purifycss-and-webpack))
- [ ] Refactor to remove ALL files in `web_src/less` & use Semantic's supported `.variables` and `.overrides`, beginning with `helpers.less` and all `_*.less` files
- [ ] Revert all changes to `web_src/fomantic/build/semantic.css`

## Questions
**Am I missing anything else?**
**Is there significant desire to continue using Fomantic UI?** It would be very painful to move away, but something like Tailwind would solve half of the suggestions above (including the precompiler)

This is certainly a huge undertaking, but I wanted to test to see if others agree with this analysis or it's not of interest. I also don't want to bring up all of these issues without helping towards a solution, so I plan to contribute to some of these resolutions.

**Comment by techknowlogick** [comment]
Without getting into all the points above, technically we are using fomantic which is a fork of semantic for security & accessibility reasons.

**Comment by lunny** [comment]
@kdumontnu Thanks for your proposals and ideas about community contribution styles. I think we can start with some easier one, i.e. introducing PurifyCSS

**Comment by CL-Jeremy** [comment]
Sorry for not noticing this. I dropped a comment in your merged PR (traced from Git blame) and I apologize for that.

The Gitea project originated from Gogs, which is maintained more or less by a single person. As such the workflow with styling has not been particularly thoughtful, with class-based overriding being commonplace from the beginning. The fact that stale code went dead unnoticed and made through multiple releases is unfortunate, and suggests that this type of thread is exactly needed.

Regarding `semantic.css`, from what I can tell it's just normal usage with several custom parameters set in site variables. I don't consider that as a problem with how Semantic/Fomantic UI is used.

`helpers.less` started only recently as a result of having too many class names. Think of it as disintegrating semantic classes (which could have long names) into rank-marked features, which should be limited in usage (I apologize for not using them exactly responsibly, good those are not merged yet). I agree it's no good convention, that architectural changes to styling would become inevitable, but it did solve the problem @silverwind had, and to some extent pretty nicely.

The example of label padding is exactly something hard to customize with Semantic UI, and in their demo they were overriding them as well, but the classes are separated by element instead of by context. Factoring out those basic redefinitions from `_base.less` etc. is of course a means to help with the current situation. In fact it seems a redesign of color classes has been planned already, so that would also help.

**Comment by kdumontnu** [comment]
> Sorry for not noticing this. I dropped a comment in your merged PR (traced from Git blame) and I apologize for that.

No need to apologize - it was helpful to point out and a great example of the difficulty with styling ([PR](https://github.com/go-gitea/gitea/pull/14761) for reference).

Thanks for the background! Super helpful to understand. 

I would really like this to evolve into a more detailed roadmap for improving the CSS architecture, so it would be helpful to catalog ongoing efforts and settle on a trajectory. I attempted to put the suggested high-level items in order of priority. I really think having a style-guide that explains the Gitea ideology/methodology will be helpful.

It's interesting that `helpers.less` seems to follow the Tailwind [ideology](https://dev.to/fjkhan/what-is-tailwind-css-3153) that broad css classes are futile and you will always riddle them with overrides, which is the opposite of fomantic/semantic. In my opinion, we need to pick a direction, document it, and stick with it as best possible. Which leads me to my two main questions:

**Do we like Fomantic/Semantic generalized-styles or do we want to move to a "utility-first" style?**
It wouldn't be very difficult to *start* porting the app over to something like Tailwind (and support both in the interim), BUT unless there is 110% support it risks being aborted and adding yet another hybrid section to the styling.

**Is there any preference for Karma vs BackstopJS or any other UI regression testing?**
Having a CI utility to test rendered output for changes will have the biggest impact and imo a prerequisite to any larger rearchitectures. I've used Karma in the past, but backstop seems quite promising.

**Comment by CL-Jeremy** [comment]
One other thing with Semantic/Fomantic UI is the extensive use of em-values of fractions of 7, in order to recover 10-based pixel values (e.g. default line height: 14 px * 1.4285 em = 19.999 px), which has created noticeable glitches on high DPI devices or when zoomed in on desktop (I suppose pinch-zoom wouldn't count here). I imagine this could be solved using `calc()` if we employ some sort of post-processing step in a plug-in.

**Comment by CL-Jeremy** [comment]
In https://github.com/go-gitea/gitea/pull/14704/commits/090cfa34847d6bb968374ef80b65f4326a90fda5 and https://github.com/CL-Jeremy/gitea/pull/6/commits/6403812d0131d821bc468c19fd83ca653b321400#diff-5d1373f9290f762a4751c497b0e8be279eb04caa3a7cdc2fd3f42b9f505a83be, a general override for vanilla-sized rectangular labels has been added to match their original styling in Gogs. Since these will not be merged until v1.15.0, it might be nice to port these changes to master earlier.

**Comment by silverwind** [comment]
Also I think we should move to plain CSS over Less. No preprocessor means faster compilation and we barely use any Less features besides nesting (which I think is a bad practice in itself as it somewhat encourages nesting which leads to overly long CSS selectors).

**Comment by kdumontnu** [comment]
>  it may actually be nice to have screenshot diffs when reviewing PRs, but downside is the screenshots need to be checked in with the code.

Agreed. It would be really nice to set this up. I did some local testing with BackstopJS and it worked really well.

Committing the screenshots with the code might become unbearable, but it seems like this would be the perfect case for git LFS. At first I thought that might add too much complexity (as a dev dependency), but I think if we go the LFS route and people clone the repo without LFS installed git just won't resolve the screenshot files. So, we can add a note in the docs saying "if you want to run UI tests locally you'll need to install git LFS" otherwise we just handle it in CI.

Unless that rings any alarm bells I can try to work on a PR.

**Comment by silverwind** [comment]
AFAIK Github does not support LFS and I think the big benefit would be to have visual diffs in the PRs so I guess the files would have to live in the repo for GitHub to see them. Personally, I've strayed from using LFS so far and have not activated it on my Gitea instances because I prefer to not require git extensions on clone.

**Comment by kdumontnu** [comment]
> AFAIK Github does not support LFS

How so? I use git LFS with GitHub all the time. Here's a [demo I put together](https://github.com/AllSpiceIO/LFS_Demo/pull/1/files?short_path=1e324d0#diff-1e324d0ebf365fa3fff4d26528bb0e234fd9e59efee490efb903ad6a85f50db4)

LFS would only be required as a dev dependency for someone making changes that effect the UI, not to build or any backend changes. If you clone without LFS installed you just get pointer files for the screenshots. Alternatively we could let CI handle generating and committing the images on PRs, but then you will have to pull your branch any time you push on a PR with a UI change...

Unfortunately, I don't think this solution would be feasible without LFS (the repo would grow too large). I guess that's why tools like [Cypress](https://www.cypress.io/) exist to manage it externally from the git repo.

**Comment by silverwind** [comment]
TIL. Seems free accounts [do get 2 GB LFS quota](https://docs.github.com/en/github/managing-large-files/about-git-large-file-storage) which is probably plenty for a few screenshots.

**Comment by silverwind** [comment]
I guess a few size-optimized PNGs would not hurt to have in the repo and it will save us from future headaches with LFS quotas. It would probably boil down to around 40 PNGs to cover the most important pages in light and dark theme.

**Comment by kdumontnu** [comment]
A full page screenshot (note, you can also capture single elements or regions) at 768x1024 is about `65KB`. Doing some back-envelope math, if ~ 1 in 5 PRs changes the UI, we'll have about 1 updated image per day (using the past week as an example). So 65KB * 30 days = ~2MB/month added to repo size. That's not so bad...
![backstop_default_BackstopJS_Homepage_0_document_1_tablet](https://user-images.githubusercontent.com/12700993/111813317-a8045a80-889e-11eb-99c9-d60a1d747cbb.png)

**Comment by kdumontnu** [comment]
Netlify is going through a very similar process: https://www.netlify.com/blog/2021/03/23/from-semantic-css-to-tailwind-refactoring-the-netlify-ui-codebase/

They are using Percy storybook for regression testing.

**Comment by silverwind** [comment]
I would not consider bulma until they support css vars (stale PR https://github.com/jgthms/bulma/pull/2981).

I think generally we want to combine both helper-style classes (maybe tailwind, but I'm not convinced) and more general classes for often re-used classes like buttons. That way we are not dependant on any frameworks which may become bloated/outdated/unmaintained.

**Comment by silverwind** [comment]
As for unit-testing frontend code, I think we could use [jest](https://github.com/facebook/jest). Any objections?

My only one would be that it needs transpilation for ESM support, https://github.com/facebook/jest/issues/9430, but it's not a blocker imho.

**Comment by kdumontnu** [comment]
> As for unit-testing frontend code, I think we could use [jest](https://github.com/facebook/jest). Any objections?

I'm good with Jest, but it only tests javascript code, right? We would need something else for CSS/UI?

**Comment by silverwind** [comment]
Yes, for actual UI interaction tests, I would probably have a look at https://testing-library.com/ but given that such tools expect HTML to be rendered by a SPA, it might not be a good fit after all. I guess it will be kind of hard to integrate the backend rendering into frontend tests.

**Comment by kdumontnu** [comment]
> Yes, for actual UI interaction tests, I would probably have a look at https://testing-library.com/ but given that such tools expect the DOM to be rendered by JS, it might not be a good fit after all. I guess it will be kind of hard to integrate the backend rendering into frontend tests. I guess something based on a headless browser would still be needed for our case.

testing-library looks neat and it's one step in the right direction, but imo the biggest problem it doesn't solve is when a developer changes a CSS property or changes an HTML class and breaks another part of the app by unknowingly matching a selector. It would also take a lot of effort to test different screen sizes, etc as opposed to a screenshot based test.

**Comment by silverwind** [comment]
Yes, of course CSS regression can only be tested with screenshots, so:

- for unit tests, use jest
- for interaction tests, use something like puppeteer and maybe testing-library
- for css tests, use screenshots

**Comment by silverwind** [comment]
https://github.com/testing-library/pptr-testing-library looks like something that could work. You could probably also produce screenshots during these test runs.

**Comment by silverwind** [comment]
Initial jest integration in https://github.com/go-gitea/gitea/pull/15315.

**Comment by kdumontnu** [comment]
Closing this in favor of #18302
