### ISSUE TITLE
The dates on the contributor activity graph look wrong

### ISSUE THREAD

**Issue by vessd** [go-gitea/gitea#14632]
- Gitea version (or commit ref): v1.13.2
- Git version: v2.30.0.windows.2
- Operating system:
  - Windows 2012 R2
  - Download gitea-1.13.2-windows-4.0-amd64.exe from release page
  - Run as [service](https://docs.gitea.io/en-us/windows-service/)
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (https://try.gitea.io/vessd?tab=activity)
  - [ ] No
- Log gist:

## Description

I think contributor's activity graph should mark the date specified in the commits, not when they are uploaded to the server.
At least I expect this behavior.

**Comment by a1012112796** [comment]
duplicate with #8178
