### ISSUE TITLE
Difference between official api and self-hosted instance

### ISSUE THREAD

**Issue by AuspeXeu** [go-gitea/gitea#14643]
- Gitea version (or commit ref):
- Git version: 1.13.2
- Operating system: docker on centos
- Database (use `[x]`):
  - [x] MySQL

## Description
My api/swagger documentation is missing some endpoints in comparison to https://try.gitea.io/api/swagger#/
In particular the `/repos/{owner}/{repo}/releases/tags/{tag}` endpoint. Is this a configuration problem?

**Comment by techknowlogick** [comment]
try.gitea.io is updated to the latest commit in the master branch (currently 1.14-dev). for documentation about your specific instance please refer to the swagger that is built in.

**Comment by AuspeXeu** [comment]
Would be kinda nice if this was reflected by try.gitea.io :)

![image](https://user-images.githubusercontent.com/2115696/107650359-b1d2e680-6c7e-11eb-9b6a-51089a8daf86.png)
