### ISSUE TITLE
How to install on  SUSE LES and SQLite3 ? Documentation not clear

### ISSUE THREAD

**Issue by S-Koell** [go-gitea/gitea#14642]
- Gitea version (or commit ref):  gitea-1.9.5-1.2.x86_64.rpm from [Link in Docu](https://software.opensuse.org/download/package?package=gitea&project=devel%3Atools%3Ascm)
- Git version:  2.26.2
- Operating system:
  Distributor ID: SUSE
  Description:    SUSE Linux Enterprise Server 15 SP1
  Release:        15.1

 
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite

## Description

Disclaimer: I'm a complete rookie when it comes to work with Linux, especially with only having access via putty. So please bare with me.

What have I done so far:
- Went to [Docu "Installation from Package"](https://docs.gitea.io/en-us/install-from-package/)
- Downloaded the rpm from the linked page for SUSE [Link](https://software.opensuse.org/download/package?package=gitea&project=devel%3Atools%3Ascm)
- run `rpm -Uvh gitea-1.9.5-1.2.x86_64.rpm`
- created ` /etc/systemd/system/gitea.service` with contents I found at [Link](https://www.rosehosting.com/blog/how-to-install-gitea-on-debian-9/)
- ran `systemctl start gitea `
- and `systemctl enable gitea`
- `systemctl status gitea `gives me:
```
gitea.service - Gitea
   Loaded: loaded (/etc/systemd/system/gitea.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Thu 2021-02-11 10:19:50 CET; 577ms ago
  Process: 1944 ExecStart=/usr/local/bin/gitea web -c /etc/gitea/app.ini (code=exited, status=203/EXEC)
 Main PID: 1944 (code=exited, status=203/EXEC)

Feb 11 10:19:50 grwbghvgit01 systemd[1]: gitea.service: Unit entered failed state.
Feb 11 10:19:50 grwbghvgit01 systemd[1]: gitea.service: Failed with result 'exit-code'.
```

As you can see ... I probably forgot everything. I also needed external instructions to somehow continue.
But that is my point: I think the official documentation is lacking guidance.

My issues with the installation documentation:
- In what sequence should I do things? There is no "1. ... 2 ... 3..."
 ![image](https://user-images.githubusercontent.com/8007734/107620089-73c0cd00-6c54-11eb-9a54-0777e5705324.png)
- I guess I should start with "Database Preparation" despite it is the 3rd entry and not linked or referenced in other places..
- the database preparation has no guidance on SQLite even though it's supported. So I just did nothing ...
- So I continued with "installation from package" and scrolled to SUSE. The only information there is the Link to the download...
No information on what to do next ... just: Here is a link. So I just ran the rpm
- Now I **assume** that I should go to the "Linux Service" part... Which left me with the above output

I hope you can see my frustration.
None the less... I would be happy if someone could give me guidance on how to do it the right way :)

**Comment by techknowlogick** [comment]
SUSE is packaging a version of Gitea that is significantly out of date. I recommend using the https://docs.gitea.io/en-us/install-from-binary/ install from  binary instructions instead.

For more troubleshooting please join us in our chatroom https://discord.gg/Gitea
