### ISSUE TITLE
No notification when issue is closed via git commit

### ISSUE THREAD

**Issue by RichieB2B** [go-gitea/gitea#1464]
- Gitea version (or commit ref): 1.1.0
- Git version: 1.9.4
- Operating system: CentOS 6
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
When an issue is closed using a git commit ("fixes #n") no notification E-mail is sent.

**Comment by lunny** [comment]
@andreynering I confirm this is a bug. maybe you can help to find the reason.

**Comment by andreynering** [comment]
@lunny I think it's not a bug, just wasn't implemented yet.

Maybe we should integrate web and email notifications first.

**Comment by ghost** [comment]
Just to add that follow-up comments on **closed** issues, when still **subscribed**, is also failing to deliver email notifications (web notifications work), tested on Gitea 1.4.3.
Just saying that maybe it doesn't have to be a git commit, the issue just needs to be closed.

**Comment by RichieB2B** [comment]
Thanks stalebot for reminding us this issue has not been addressed in 2 years.

**Comment by zeripath** [comment]
@RichieB2B Are you still experiencing this bug on latest?

**Comment by RichieB2B** [comment]
Nope, I can't reproduce this issue in gitea 1.6.4, thanks!
