### ISSUE TITLE
Do not run CI on draft merge requests

### ISSUE THREAD

**Issue by Kreyren** [go-gitea/gitea#14656]
Recommending to configure DroneCI to not run on draft merge requests.

### Rationale
Draft merge requests doesn't need CI so this way we can preserve processing resources.

**Comment by a1012112796** [comment]
suggested solutions:
- add ``[SKIP CI]``on commit message
- add some logic on CI file to skip.

**Comment by techknowlogick** [comment]
We thankfully have generous sponsors who provide us with resources for our CI, and so running extra builds are fine. If the backlog of builds gets too backed up, we can manually cancel some as needed. 

I also sometimes use draft PRs so I don't blast everyone with emails and still utilize our CI, so suggestion that @a1012112796 would be best if you don't want specific commits to build. However, a manager needs to be careful when merging your PRs as those skips would be added into the squash'd commit message and would skip the merge commit.
