### ISSUE TITLE
[API] Add repoCreateTag function

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#14669]
`POST /repos/{owner}/{repo}/tags` to create a tag

**Comment by segfult** [comment]
Hey @6543, I'd like to look into this. As a newcomer few pointers would be helpful. :)

**Comment by 6543** [comment]
first start is to read the **CONTRIBUTING.md** especially the [API v1 section](https://github.com/go-gitea/gitea/blob/master/CONTRIBUTING.md#api-v1)

for this issue you can have a look how CreateRelease works
https://github.com/go-gitea/gitea/blob/24f7bd589945c8fc22c9cfc00bc21fca679da9d0/routers/api/v1/repo/release.go#L128-L211

just remove unnecessary options & tell releaseservice.CreateRelease to only create a tag but no release :)

**Comment by 6543** [comment]
@segfult if you have specific questions just PM me via Discord

**Comment by segfult** [comment]
> @segfult if you have specific questions just PM me via Discord

will do, thanks.
