### ISSUE TITLE
[FR] Implement Required Approvals similar to GitLab

### ISSUE THREAD

**Issue by Reinitialized** [go-gitea/gitea#14664]
Currently, the pull request approvals are lackluster in the sense of not enforcing reviewers to give consent before a request can be merged. GitLab has the ability to require approval from reviewers, and a lot of customization. Refer to the link for detailed explanation as I feel it is redundant to rewrite what's already written. 

https://docs.gitlab.com/ee/user/project/merge_requests/merge_request_approvals.html#required-approvals

**Comment by jolheiser** [comment]
You can set the number of required approvals, as well as a list of users/teams who count towards that number.

**Comment by Reinitialized** [comment]
> You can set the number of required approvals, as well as a list of users/teams who count towards that number.

I've been playing around with Pull Requests before making this while reading available documentation, and haven't seen it? When setting test accounts as Reviewers, I was still able to merge the request and could not find options to enforce their consent beforehand.

**Comment by jolheiser** [comment]
You have to set up branch protection.

`https://try.gitea.io/<user>/<repo>/settings/branches/master`

**Comment by Reinitialized** [comment]
Alright, good to know. I'll adapt this request then as this has to be implemented per branch, and it would be nice to have this automatically apply on each pull request vs manually configuring it.
