### ISSUE TITLE
Proposal: review the way the explore page works

### ISSUE THREAD

**Issue by yusefmaali** [go-gitea/gitea#1467]
This is a proposal about reviewing how the explore page works.

On the explore page there's three tabs on the left that allows me to access the repos, the users and the organizations pages.

How it works now:
---------------
- The repos page shows all my repos and all repos of the organizations I'm in.
- The users page shows all the users registered in gitea.
- The organizations page shows all the organizations registered in gitea, even those I'm not in. Accessing to the detail page of an organization I'm not in, results in the correct behavior of showing nothing.

How it _may_ be enhanced:
---------------
- The repos page should show all my repos and _only_ the repos of the organizations I have access to (just like the 'shared repos' box does in the activity page). If the organization has 10 repositories but I'm allowed to access only to 3 of them, I should not see the other 7.
I can have access to organization repositories through enabling me directly to the repo or adding me in a organization team. In the first case I have NO access (neither I can see a listing) to the organization's repos (and this is a correct behavior). In the second case, just adding me to an orga team, allows me to see all the orga repos (even if I don't have access to them).

- The users page is OK.

- The organizations page should show ONLY the orga I'm in as an orga team and eventually the orga I have some repos enabled (even as non orga team). Showing all of them is not a correct behavior. Moreover the datail page of the orga I'm not enabled, results "empty" and is really not useful at all.

As a base rule, I will suggest:

- if a repo is _private_ it should appear _only_ to user who have access.
- if a repo is _public_ it should appear everywhere to everyone.
- if an organization has no visible repos to me (on the two rules above), I should _not_ see it.

---------------

These improvement will be useful (required, I'd like to say) in a business environment.
Example:
- giving customers access to its code without allowing it to see all organizations in gitea (which may reveal "secret" informations)
- restricting team visibility to only the orga and repos they are enabled
- shutting down unwanted curiosity of curious users... 

Thanks!

**Comment by pgaskin** [comment]
IMHO, these changes would cause quite a bit of confusion for users. This could be useful, but not as a default. Personally, the existing method works fine for me.

---

> - if a repo is private it should appear only to user who have access.
> - if a repo is public it should appear everywhere to everyone.

What do you mean? It already works this way.

> The organizations page should show ONLY the orga I'm in as an orga team and eventually the orga I have some repos enabled (even as non orga team). Showing all of them is not a correct behavior. Moreover the datail page of the orga I'm not enabled, results "empty" and is really not useful at all.

I disagree. Sometimes, you need to be able to see empty orgs for organisational purposes. An org might be there as a placeholder, for example.

> giving customers access to its code without allowing it to see all organizations in gitea (which may reveal "secret" informations)

IMO, an internal instance of gitea shouldn't be publicly accessible. There are too many possible risks. Another instance of gitea should be set up for organisations for customer access. 

> shutting down unwanted curiosity of curious users...

What do you mean. You can just have a private repo and add read only collaborators.

---

Also btw, the tabs are now moved to the top instead of the left.

**Comment by yusefmaali** [comment]
> IMHO, these changes would cause quite a bit of confusion for users

why confusion?

> What do you mean? It already works this way.

Nope. A private repository is not _accessible_ but may be _visible_ through the explore/organizzations page.

> I disagree. Sometimes, you need to be able to see empty orgs for organisational purposes. An org might be there as a placeholder, for example.

Ok, this depends strictly on the workflow you need from gitea.
Just for curiosity, why do you need empty organizations as placeholder?

> IMO, an internal instance of gitea shouldn't be publicly accessible. There are too many possible risks. Another instance of gitea should be set up for organisations for customer access.

You are suggesting to have at least two instances of gitea live and running ? One for internal use and one for external use.
What about if you need your customer to interact with the repository? In some case you may want to give write access to the customer (ie. it may be a partner, that may push some code or some fix). I should setup a mirroring between the internal and external instances? It look to me a bit complicated.
Take into account I'm talking about customers, but it may be also external suppliers. Change the role, don't change the fact I want to restrict the visibility of private repos and "empty" organizations.

Moreover, I may wish to give access to more than one customer/supplier. In that case, do you suggest to have an instance running per customer? Don't seem to me a practical solution.

You wrote about "too many possible risks" in having only one public instance.
What kind of risk are you talking about? I suppose we can consider Gitea a safe and stable platform.

> Also btw, the tabs are now moved to the top instead of the left.

Ok, I use only stable released version. Current v.1.1.0 has them on the left (and some bugs).

**Comment by pgaskin** [comment]
> why confusion?

They create a new organization, tell someone else to find it, it isn't there.

> Nope. A private repository is not accessible but may be visible through the explore/organizzations page.

I just tried this in about 3 different ways, a private repo isn't visible anywhere for me

> Just for curiosity, why do you need empty organizations as placeholder?

Sometimes, I need to create empty orgs as a placeholder so other people do not create them, either by mistake (they thought an organization for their team wasn't there yet), or for a malicious purposes (to create the same org with the same name before I have a chance) (I know they can be moved, but it's still a hassle)

> You are suggesting to have at least two instances of gitea live and running

Yes, I do that with my own server and proxy them with caddy. It is quite simple actually.

> What kind of risk are you talking about? I suppose we can consider Gitea a safe and stable platform.

Let's say a XSS bug is found. Someone external could take advantage of it to add a ssh key or change the password of the admin, and mess with all the repos. There is also the problem of spam too.

> Ok, I use only stable released version. Current v.1.1.0 has them on the left (and some bugs).

OK. Try gitea on https://try.gitea.io

**Comment by yusefmaali** [comment]
> I just tried this in about 3 different ways, a private repo isn't visible anywhere for me

Assuming your user in try.gitea.io is "geek1011" I've created a couple of tests.
I have created an orga "YMA-test-organization" that has two private repos. I'm gonna adding you only to "private-repo-1".
I have created another orga "YMA-test-organization-2" that has two private repos. I'm gonna create a "dev" team for this orga, enable only one repo for the team and adding you to the team.

What I expect to happen:

1) in your activity page you should see under "Shared repository"
- "YMA-test-organization /  private-repo-1"
- "YMA-test-organization-2 /  private-repo-x"

this is correct

2)  still in activity page, under the organizzation tab:
- "YMA-test-organization-2"

this is correct

3) open the detail page for the organization:
- you should see only "private-repo-x"

this is correct

4) now, open explore / repository page:
I expect you to see:
- "YMA-test-organization-2 /  private-repo-x"
- "YMA-test-organization-2 /  private-repo-y"

this is NOT correct

private-repo-y is not shared with you in any way, it is private and owned by the organization you are part of through a team that is allowed to access only to "private-repo-x".

-----------

About the other replies, I use Gitea in a really different way as you.
I have disabled the registration feature, only administrators can activate new users.
Users won't create organizations, that are created by the admins.
Users will be added to repos or orga's team and have only the write permission.

In my case, users won't have so much freedom as in your case and, coming back to my initial post, I don't like them to see organization (and private repos!) they are not part of.

**Comment by pgaskin** [comment]
Yes, now I see what you mean about that point. This is certainly a bug. You might want to open another issue specifically about this problem about private org repos showing in the explore page. This is not meant to happen. Thanks for showing a demo, your original wording wasn't very clear.

**Comment by pgaskin** [comment]
@lunny, I think the part of this issue is a bug, not a proposal. It should be reported as a seperate issue because some of this is also a proposal. See my above comments for more details.

The bug is that private repos, in an org you are part of, will appear on the explore page, resulting in a 404 on an attempt to access them. This can confuse users and expose private information. The repos do not appear anywhere else, this bug only applies to the explore page. 

The rest of this issue is a proposal.

**Comment by yusefmaali** [comment]
Ok, I think we may going to close this issue.
I'm going to create the bug report and another proposal (restricted to hide organizations a user is not part of).
Thks

**Comment by pgaskin** [comment]
@usef ok, that sounds good

**Comment by yusefmaali** [comment]
ok, closing this. @geek1011  thanks for your time!
