### ISSUE TITLE
API repos doesn't return all repos

### ISSUE THREAD

**Issue by mixman68** [go-gitea/gitea#14698]
- Gitea version (or commit ref): 1.13.1
- Git version: 2.20.5
- Operating system: Debian Buster
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
No enouth data
- Log gist:

## Description
The GET /api/v1/users/{user}/repos return only 30 repos max, so with Gitea jenkins plugin, i cannot choose my repo because i have 71 repos on my user
...

**Comment by jpraet** [comment]
You could increase these properties in your app.ini:

```ini
[api]
; Max number of items in a page
MAX_RESPONSE_ITEMS = 50
; Default paging number of api
DEFAULT_PAGING_NUM = 30
```

But it would be best to report this issue on the Gitea jenkins plugin side as well, as they should make use of the pagination when fetching the repositories.

**Comment by jolheiser** [comment]
There is a PR over at https://github.com/jenkinsci/gitea-plugin/pull/25 to address this issue.
