### ISSUE TITLE
app.ini option to allow clone filters

### ISSUE THREAD

**Issue by bagasme** [go-gitea/gitea#14697]
## Description

Currently to allow clone filters (upload pack filters), one have to manually set the option via `git config`, as described on [the docs](https://docs.gitea.io/en-us/clone-filters/).

To be better, there should be option on `app.ini` named `ALLOW_CLONE_FILTERS` (or `ALLOW_UPLOAD_PACK_FILTERS`) which toggle git config `allowpack.togglefilter` globally, defaulted to false (which disallow filters). To allow filters, set the option to true. 

This option can be overridden on per-repo basis.

Note that clone filters requires Git version 2.22 or later. The option above must be hardcoded to false for instances running Git versions lower than the required.

**Comment by zeripath** [comment]
What's wrong with just setting it in .gitconfig for gitea user.

**Comment by bagasme** [comment]
@zeripath i think i propose this issue for convenience. It is more convenient to have `app.ini` option that abstracts actual `git config` than using `git config` directly
