### ISSUE TITLE
Can't clone project

### ISSUE THREAD

**Issue by camelator** [go-gitea/gitea#14691]
Hi,
firstty I would like to say many thanks for this project. I am using Gitea on my raspberry for my projects for years now.
I have no issue to clone a project on my computer when I created it with my username.
But today I would like to create a project within an organisation.
I've created an organisation, I am in the group 'owners'
Within this organisation, I created a project 'test'
Then I tried to clone the project on my computer with this command line:

git clone 'http address'/'organisation'/'project name'.git
I have the following error: Unable to read remote depot.

How to work wirth organisation ? Is it any documentation?

Many thanks for your help,

Christian

**Comment by camelator** [comment]
My gitea version is v1.13.2 built with GNU Make 4.3, go1.15.7 : bindata, sqlite, sqlite_unlock_notify

Unfortunately, some progress in my issue:
Everything appeared since I tried to create an organisation (but maybe it is not the root cause)
Now, if I want in the Gitea interface to create a new repo with my user account (and not the organisation), I have a page with an error 500

How to debug it ? What can I do ?

**Comment by jolheiser** [comment]
Please fill out the issue template. Until then, we are going to be shooting in the dark.

We need logs, among other things in the issue template.

**Comment by zeripath** [comment]
@camelator do not comment on closed issues - open a new issue and link to the closed issue.

We need logs for your problem, or come to Discord: https://discord.gg/Gitea and we can work through your issue.

**Comment by camelator** [comment]
[gitea.log.2021-02-16.001.txt](https://github.com/go-gitea/gitea/files/5988962/gitea.log.2021-02-16.001.txt)

With help of the log file I found rthe issue, it was a memory issue because my Raspberry has 1GB memory. So I extended the swap file and all working.

But:

Isn't it a memory leak issue?

After rebooting my RPI, launch docker free -m displays: 119MB as used memory
launched mariadb and other images : 199MB (so all images including mariadb take 80MB)
launched gitea : 275MB ( memory usage 76MB)
sign in to gitea : memory usage: 290MB
a push from my remote PC (studio code: memory usage on raspberry after the operation: 424MB)

5 minutes after the operations (Login+ push from another PC) free -m still displays 627 memory usage including 424MB from Gitea...

What do you think about it?

**Comment by zeripath** [comment]
We're aware of a number of memory issues in 1.13 one of the biggest was defaulting to argon2 for password hashing but there is also an issue with go git.

I personally have worked extremely hard to attempt to address these issues in our current master. 

I suggest you try running the latest master to see if that improves things.

You should also be aware that free is not the correct way to assess memory use for garbage collected languages like go.
