### ISSUE TITLE
[Feature Request] KanBan: allow to change the order of "boards" and other properties of "boards"

### ISSUE THREAD

**Issue by datenheim** [go-gitea/gitea#14709]
- Gitea version (or commit ref): 1.13.0

## Description
Give some sort of control over the order of so called "boards" (or panes).

Right now their order is bit out of control, and after renamed a board, the order has changed.
Could be drag and drop (#13805), or a numeric option or whatever.

If a numeric option, it could be placed in the dialogue currently allowing to rename the board.

Of course any board shoulb be renamable, also the default one, #14679

Also one might add an option to color the board, relates to #11160

And an option to input a description of the board, relates to #12513

**Comment by delvh** [comment]
> Give some sort of control over the order of so called "boards" (or panes).
Right now their order is bit out of control, and after renamed a board, the order has changed.
Could be drag and drop (#13805), or a numeric option or whatever.
If a numeric option, it could be placed in the dialogue currently allowing to rename the board.

Should already be a part of 1.14 (see #14533 and its merged PR #14634).

I agree however that the other mentioned points (board color, board renaming and maybe even board description (even if I personally don't think board description would be really useful)) are valid feature requests. Maybe delete the first paragraphs and rename the issue.

**Comment by lunny** [comment]
Duplicated with #13805.

**Comment by datenheim** [comment]
@lunny thanks for taking the points to the summary
