### ISSUE TITLE
Access repository: Error 500

### ISSUE THREAD

**Issue by elegraf007** [go-gitea/gitea#14708]
- Gitea version (or commit ref):
- Git version: 1.13.2 
- Operating system:
  
Windows 2019 Server
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ X ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ X ] No
- Log gist:

2021/02/17 11:16:28 ...les/context/panic.go:35:1() [E] PANIC:: runtime error: invalid memory address or nil pointer dereference
	/usr/local/go/src/runtime/panic.go:212 (0x4515b5)
	/usr/local/go/src/runtime/signal_windows.go:246 (0x45144d)
	/go/src/code.gitea.io/gitea/modules/git/blob.go:28 (0x20df648)
	/go/src/code.gitea.io/gitea/routers/repo/view.go:256 (0x20df63c)
	/go/src/code.gitea.io/gitea/routers/repo/view.go:657 (0x20e5004)
	/go/src/code.gitea.io/gitea/routers/repo/view.go:576 (0x20e43ed)
	/usr/local/go/src/reflect/value.go:476 (0x4a31e6)
	/usr/local/go/src/reflect/value.go:337 (0x4a2684)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:177 (0xd9a619)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:137 (0xd99fde)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:121 (0xd9bbc1)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:112 (0x169c224)
	/go/src/code.gitea.io/gitea/modules/context/repo.go:810 (0x169c209)
	/usr/local/go/src/reflect/value.go:476 (0x4a31e6)
	/usr/local/go/src/reflect/value.go:337 (0x4a2684)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:177 (0xd9a619)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:137 (0xd99fde)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:121 (0xd9bbc1)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:112 (0x169a8b3)
	/go/src/code.gitea.io/gitea/modules/context/repo.go:593 (0x169a89c)
	/usr/local/go/src/reflect/value.go:476 (0x4a31e6)
	/usr/local/go/src/reflect/value.go:337 (0x4a2684)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:177 (0xd9a619)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:137 (0xd99fde)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:121 (0xd9bbc1)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:112 (0x169807b)
	/go/src/code.gitea.io/gitea/modules/context/panic.go:39 (0x169806c)
	/usr/local/go/src/reflect/value.go:476 (0x4a31e6)
	/usr/local/go/src/reflect/value.go:337 (0x4a2684)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:177 (0xd9a619)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:137 (0xd99fde)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:121 (0xd9bbc1)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:112 (0x1643644)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/session/session.go:192 (0x164362d)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:79 (0xd9ba17)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:157 (0xd9a342)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:135 (0xd9a0cd)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:121 (0xd9bbc1)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:112 (0x220281d)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/gzip/gzip.go:140 (0x2202810)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:79 (0xd9ba17)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:157 (0xd9a342)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:135 (0xd9a0cd)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:121 (0xd9bbc1)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:112 (0xdadbcc)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/recovery.go:161 (0xdadbbf)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/logger.go:40 (0xd9f85a)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:157 (0xd9a342)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:135 (0xd9a0cd)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:121 (0xd9bbc1)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:112 (0xdacebc)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/logger.go:52 (0xdacea7)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/logger.go:40 (0xd9f85a)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:157 (0xd9a342)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:135 (0xd9a0cd)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:121 (0xd9bbc1)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/router.go:187 (0xdaee7c)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/router.go:303 (0xda852c)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/macaron.go:218 (0xda0c35)
	/go/src/code.gitea.io/gitea/vendor/github.com/gorilla/context/context.go:141 (0x12b60fa)
	/usr/local/go/src/net/http/server.go:2042 (0x77bb0a)
	/usr/local/go/src/net/http/server.go:2843 (0x77f1a9)
	/usr/local/go/src/net/http/server.go:1925 (0x77a8cc)
	/usr/local/go/src/runtime/asm_amd64.s:1374 (0x473620)

## Description

...
On accessing a repository via web interface owned by a group or accessing as administrator
an error of 500 occurs.
The logfile is attached.
The repo is accessible via git client (clone, pull, push) without problem.
On the server itself a git fsck is doable without problem
I did try to re-read all repos meta data via web interface.
Repo does only contain a huge amount of text files with a cloned size of about 15MB

## Screenshots

![Unbenannt](https://user-images.githubusercontent.com/63120626/108196711-b9c8d580-7119-11eb-9382-adb6d11636f2.PNG)

**Comment by lunny** [comment]
Hi, could you try v1.13 branch release ?

**Comment by elegraf007** [comment]
Hi, thank you for your fast reply! 
I tried https://dl.gitea.io/gitea/1.13 with build date of 02/15/2021 12:32:22 AM +00:00
unfortunately the error persist. Here started with debug logging enabled 




2021/02/17 14:10:35 routers/repo/view.go:181:renderDirectory() [D] README.md
2021/02/17 14:10:35 routers/repo/view.go:192:renderDirectory() [D] false
2021/02/17 14:10:35 ...les/context/panic.go:35:1() [E] PANIC:: runtime error: invalid memory address or nil pointer dereference
	/usr/local/go/src/runtime/panic.go:212 (0x451615)
	/usr/local/go/src/runtime/signal_windows.go:246 (0x4514ad)
	/go/src/code.gitea.io/gitea/modules/git/blob.go:28 (0x20e7688)
	/go/src/code.gitea.io/gitea/routers/repo/view.go:256 (0x20e767c)
	/go/src/code.gitea.io/gitea/routers/repo/view.go:657 (0x20ed044)
	/go/src/code.gitea.io/gitea/routers/repo/view.go:576 (0x20ec42d)
	/usr/local/go/src/reflect/value.go:476 (0x4a4966)
	/usr/local/go/src/reflect/value.go:337 (0x4a3e04)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:177 (0xda1ed9)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:137 (0xda189e)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:121 (0xda3481)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:112 (0x16a0684)
	/go/src/code.gitea.io/gitea/modules/context/repo.go:810 (0x16a0669)
	/usr/local/go/src/reflect/value.go:476 (0x4a4966)
	/usr/local/go/src/reflect/value.go:337 (0x4a3e04)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:177 (0xda1ed9)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:137 (0xda189e)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:121 (0xda3481)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:112 (0x169ed13)
	/go/src/code.gitea.io/gitea/modules/context/repo.go:593 (0x169ecfc)
	/usr/local/go/src/reflect/value.go:476 (0x4a4966)
	/usr/local/go/src/reflect/value.go:337 (0x4a3e04)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:177 (0xda1ed9)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:137 (0xda189e)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:121 (0xda3481)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:112 (0x169c4db)
	/go/src/code.gitea.io/gitea/modules/context/panic.go:39 (0x169c4cc)
	/usr/local/go/src/reflect/value.go:476 (0x4a4966)
	/usr/local/go/src/reflect/value.go:337 (0x4a3e04)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:177 (0xda1ed9)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:137 (0xda189e)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:121 (0xda3481)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:112 (0x1646fc4)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/session/session.go:192 (0x1646fad)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:79 (0xda32d7)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:157 (0xda1c02)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:135 (0xda198d)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:121 (0xda3481)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:112 (0x220acbd)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/gzip/gzip.go:140 (0x220acb0)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:79 (0xda32d7)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:157 (0xda1c02)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:135 (0xda198d)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:121 (0xda3481)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:112 (0xdb548c)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/recovery.go:161 (0xdb547f)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/logger.go:40 (0xda711a)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:157 (0xda1c02)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:135 (0xda198d)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:121 (0xda3481)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:112 (0xdb477c)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/logger.go:52 (0xdb4767)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/logger.go:40 (0xda711a)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:157 (0xda1c02)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:135 (0xda198d)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:121 (0xda3481)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/router.go:187 (0xdb673c)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/router.go:303 (0xdafdec)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/macaron.go:218 (0xda84f5)
	/go/src/code.gitea.io/gitea/vendor/github.com/gorilla/context/context.go:141 (0x12bde7a)
	/usr/local/go/src/net/http/server.go:2042 (0x77db4a)
	/usr/local/go/src/net/http/server.go:2843 (0x7811e9)
	/usr/local/go/src/net/http/server.go:1925 (0x77c90c)
	/usr/local/go/src/runtime/asm_amd64.s:1374 (0x4737a0)
	
2021/02/17 14:10:35 ...s/context/context.go:139:HTML() [D] Template: status/500

**Comment by lunny** [comment]
Is this repository a public one? Could you share it on https://try.gitea.io ?

**Comment by zeripath** [comment]
You need to run gc on this repository

**Comment by elegraf007** [comment]
Hi, thank your for your fast answers.
As this is nighttime in Germany sorry for being not as fast as you!

My problem is solved by  git gc --aggressive directly in the repository.
Beforehand I tried to fire the "garbage collection on all repositories" button via the web interface which did not solve the problem.

My suggestion would be to fire up git gc --aggressive when pressing the button.

**Comment by zeripath** [comment]
Ah, looking into this a bit more the reason aggressive worked is that it does a repack.

We might want to have aggressive and repack as actions but - to be honest these are quite deep git maintenance tasks and I'm not certain if we should put them in the UI.

It would be good to know how your pack went missing. Do your repos have gc.auto set to false?

**Comment by elegraf007** [comment]
@zeripath : the gc.auto setting is unset so I assume it to be the default value of 6700. 
So bringing this back to the initial problem:
When displaying a repo with presumably many loose objects in it

a. what is the reason that gitea fails on doing something like git ls-files 
b. how should users with similar problems react on an error like this

I completely agree that more maintenance tasks are not a good solution(btw they cause programming affords). Question would be: how to avoid the problem?  Sorry for only  being able to ask the question not having the answer since I'm not into the code

**Comment by zeripath** [comment]
I don't understand what is causing this issue and if it simply a bug in go-git. I think we'll have to see if this occurs on 1.14 where we have migrated back to git command based variants instead.

However I think we can close this - if it comes back or you manage to work out what caused the issue in the first place please reopen.
