### ISSUE TITLE
Hooks partly don't work after gitea update

### ISSUE THREAD

**Issue by lakostin** [go-gitea/gitea#14712]
- Gitea version (or commit ref):
1.14.0+dev-707-g66a148e39
- Git version:
2.30.1
- Operating system:
docker Alpine Linux v3.13
- Database (use `[x]`):
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
- Log gist:

## Description
After gitea update pipelines for multiple branches/commits don't work at all (hooks are being sent though): commit doent't start new pipeline, new branches do not appear in jenkins automatically.
For some branches hooks still work.
Looks like gitea has limits for branches, for which hooks work.
We downgraded gitea to version 1.14.0+dev-514-gd2ee1221c and hooks work well again.
...

## Screenshots

![Screenshot from 2021-02-17 18-53-56](https://user-images.githubusercontent.com/29179059/108230212-8efa7380-7151-11eb-99bc-33b09132075c.png)

**Comment by techknowlogick** [comment]
We need logs to be able to help you, what do the webhook logs say, what do the standard logs say?

**Comment by lakostin** [comment]
Actually there is nothing interesting in gitea logs, though trace log level is being used.
In project settings i can see that hook was successfully sent and 200 code was returned.
No pipeline started though when i push new branch. But when i create new pull request from this branch, jenkins job starts successfully.
I know it looks like its not a gitea bug but with previous gitea version everything worked well: both branch and pull request hooks started a new job. And we didn't update anything else except gitea. In jenkins logs there are also no errors.

**Comment by techknowlogick** [comment]
I recommend opening up a ticket with the jenkins plugin then. As such I will close this ticket.

**Comment by lakostin** [comment]
> I recommend opening up a ticket with the jenkins plugin then. As such I will close this ticket.

Do you know how to do it? It's not possible to create an issue without logging in and its not possible to sign up there cause i always get an error))

**Comment by techknowlogick** [comment]
I'm afraid I've never filed a ticket with them, perhaps there is a public email address you can email?
