### ISSUE TITLE
Create issue within Project view

### ISSUE THREAD

**Issue by Reinitialized** [go-gitea/gitea#14714]
# Feature Request

## What is your feature?

Allow for creating issues within the projects page.

Example of GitLab having a + icon on the top right of the Open board:
![image](https://user-images.githubusercontent.com/20674500/118875384-9dbc0800-b8b1-11eb-9775-3917ce2ff044.png)

## How would implementing this feature improve your experience?

Quality of life

## Do you plan on submitting a pull request?

- [ ] Yes, I intend on submitting a pull request
- [X] No, I will not submit a pull request

**Comment by denyskon** [comment]
This feature is already present

![Screenshot_20230701-063307~2.png](https://github.com/go-gitea/gitea/assets/47871822/7a4a90dc-cb56-4d47-9c0b-3ef471156289)
