### ISSUE TITLE
[FEATURE] Create branch along with Pull Request without requiring existing changes

### ISSUE THREAD

**Issue by Reinitialized** [go-gitea/gitea#14715]
~~With the current UX flow when you attempt to create a Pull Request, a branch must already exist and contain changes, requiring additional steps to be made to create said pull request. It would be a nice to have to be able to create a new branch within the current UI instead of having to push a new branch with a single change to do so.~~

~~Although #11888 is similar, this request is different as the referenced issue is asking to create Pull Requests in issues, while I'm requesting the ability to create one without having an issue tied.~~

![Screenshot from 2021-02-17 14-51-48](https://user-images.githubusercontent.com/20674500/108267000-68781080-7130-11eb-962b-b7bde8281a61.png)

# Closing issue because ...
Upon further use of Gitea and learning Git practices, #11888 should be sufficient enough

**Comment by jolheiser** [comment]
You can create a branch from the UI, however it still won't let you open a PR if there would be no differences.


![branch](https://user-images.githubusercontent.com/42128690/108267918-70848000-7131-11eb-98e3-005f844b37e1.png)

**Comment by Reinitialized** [comment]
> You can create a branch from the UI, however it still won't let you open a PR if there would be no differences.
> 
> ![branch](https://user-images.githubusercontent.com/42128690/108267918-70848000-7131-11eb-98e3-005f844b37e1.png)

It would seem there may be a bug relating to this, as I was not prompted with UX informing me to "Create branch ... from '...'". However, although a separate potential bug, this request should still stand as you are unable to create a Pull Request with the above statement.
