### ISSUE TITLE
PL/SQL double dash comments in diff

### ISSUE THREAD

**Issue by bartkaptur** [go-gitea/gitea#14711]
Hi.
I use Gitea 1.13.2 on top of PostgreSQL.
A comment on a pull request including an Oracle pl/sql file with "--" comments results in something like this in DB in comment.patch:

```
diff --git a/sql/FUND/PACKAGES/CORRECTIONS.pkb b/sql/FUND/PACKAGES/CORRECTIONS.pkb
--- a/sql/FUND/PACKAGES/CORRECTIONS.pkb
+++ b/sql/FUND/PACKAGES/CORRECTIONS.pkb
---  some comment
---  some other comment
@@ -2061,839 +2119,733 @@
     END LOOP;
 
     IF gv_test_type THEN
-      Dr.begin ('Debit correction summary');
+      dr.begin ('Debit correction summary');
@@ -2703,0 +2522,4 @@
+                            l_register,
+                            v_hssr,
+                            vt_events (i_zd).oper_type,
+                            correction_cost.GC_ALG_PERC_SUM_BR_M, -- TODO
```

What happens next is that presumably the pulls panel treats the two "some comment" lines like the file locations above it and tries to link to them. The effect:

`template: repo/issue/view_content/comments:470:20: executing "repo/issue/view_content/comments" at <CommentMustAsDiff (index $comms 0)>: error calling CommentMustAsDiff: runtime error: invalid memory address or nil pointer dereference`

Manual removal of the two lines results in the pull request displayed properly.
Please check.

**Comment by lunny** [comment]
The patch on master(fe628d8406632e6f5b3969ac86d817a035d4bae9) may resolve the problem.

```diff
diff --git a/services/gitdiff/gitdiff.go b/services/gitdiff/gitdiff.go
index d5c392351..caba8365b 100644
--- a/services/gitdiff/gitdiff.go
+++ b/services/gitdiff/gitdiff.go
@@ -802,9 +802,9 @@ parsingLoop:
                                curFile.Type = DiffFileRename
                        case strings.HasPrefix(line, "Binary"):
                                curFile.IsBin = true
-                       case strings.HasPrefix(line, "--- "):
+                       case strings.HasPrefix(line, "--- a/"+curFile.OldName):
                                // Do nothing with this line
-                       case strings.HasPrefix(line, "+++ "):
+                       case strings.HasPrefix(line, "+++ b/"+curFile.Name):
                                // Do nothing with this line
                                lineBytes, isFragment, err := parseHunks(curFile, maxLines, maxLineCharacters, input)
                                diff.TotalAddition += curFile.Addition
```

**Comment by zeripath** [comment]
Please can you try to replicate on try.gitea.io. I do not believe that master should be affected by this problem.

**Comment by bartkaptur** [comment]
Seems to work fine on try.gitea.io. No error. Thank you.
There is, hovewer, another problem. When I go to the "Files changed" tab and add a single comment on a deleted -- comment in a commited file, I see the -- comment twice in the Conversation tab, like this:
![screenshot_gitea](https://user-images.githubusercontent.com/56125997/108315630-f6e5a400-71bb-11eb-93cd-d78c5caa595c.png)

**Comment by zeripath** [comment]
Can you make arandomer@mailinator.com a collaborator on that repo so I can test.

**Comment by bartkaptur** [comment]
Done. bkaptur/test_oracle
