### ISSUE TITLE
How to set gpg key to a repository?

### ISSUE THREAD

**Issue by tomaswarynyca** [go-gitea/gitea#14722]
Hello, can you explain me how to put a gpg key to a repository?

**Comment by lunny** [comment]
What did you mean and what do you want to do?

**Comment by delvh** [comment]
If my guess of what you want is correct, then you can't add a GPG key to a single repository.
GPG keys have to be globally declared in your account settings.
I also don't see too much value behind adding the capability to add GPG keys limited to a single repository, that only leads to cluttered states where no one wants to clean up their repositories because every single repository can behave differently, and at best you don't even know if the commit signature you entered will be valid because you can't be sure whether you entered that certain key for your repository.

**Comment by tomaswarynyca** [comment]
So I am misinterpreting the note this documentation
https://docs.gitea.io/en-us/signing/#signing_key

**Comment by delvh** [comment]
No, if I understand you correctly: You don't have to put inside the app.ini (the **global gitea config for all users**).
Instead, inside your account settings (click on your profile picture displayed in the upper right corner > settings), there is a tab `SSH / GPG keys`. There you can add your GPG key according to the linked guide.
But yes, the key has to be generated on your local machine first.

**Comment by tomaswarynyca** [comment]
I should have sent this photo earlier
SSH / GPG keys for my account are set up

![image](https://user-images.githubusercontent.com/41587659/108353730-3a91db00-71c7-11eb-9107-daeeb72b75c0.png)

**Comment by delvh** [comment]
Sorry, I misunderstood you there. I thought you wanted to set your own GPG key, not the key Gitea uses for all commits generated by Gitea.
I have no idea how to set the default Gitea key, so we'll have to wait if someone else can answer this.

**Comment by lunny** [comment]
> So I am misinterpreting the note in this documentation
> https://docs.gitea.io/en-us/signing/#signing_key
> 
> So to put I have to generate it on my machine and put the data in app.ini?

Yes, you are right. The commit you push to the branch is signed well with your gpg key. But when merge a PR into the master, Gitea don't know your private gpg key. So you have to generate a server gpg key to sign all PR merged commit and it will be recognized as the committer on Gitea.

**Comment by tomaswarynyca** [comment]
I understand, now another question the id name and email has to be from a registered user right?
In this case, if I put my gpg id, name and email as I have it configured in my gitea account, it will sign the commit as if it were me?

**Comment by lunny** [comment]
The signing name and email could not be a registered user. It will display the key's name and email but not the committer's. This is different from Github's implementation.

**Comment by tomaswarynyca** [comment]
Great, everything is clear, thank you @lunny 
It seems to me that it should be as implemented by github, process to close the issues and we continue in #14735
