### ISSUE TITLE
No notification of label assignment and reassignment of the last event

### ISSUE THREAD

**Issue by tomaswarynyca** [go-gitea/gitea#14733]
- Git version: 1.14.0+dev-714-g7ab6c77b4
- Operating system: Linux
- Database (use `[x]`):
  - [x] MySQL
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes

## Description

As you can see in the video, when a new label is put before 1m after an event, the last event is set again. 

## Screenshots

https://user-images.githubusercontent.com/41587659/108373426-a59adc00-71de-11eb-83e5-01e608124e88.mp4

**Comment by lunny** [comment]
duplicated with #13923

**Comment by zeripath** [comment]
Closed as is a duplicate
