### ISSUE TITLE
Proposal: hide organizations for users are not part of

### ISSUE THREAD

**Issue by yusefmaali** [go-gitea/gitea#1474]
In my typical scenario, will be extremely useful if a user is not allowed to see all the organizations through the explore page, but only those he is part of.

May be needed, for example, add a "private" flag to the organization, just like repos already have.

Thank you!

**Comment by DblK** [comment]
Seems to be a duplicate of #714

**Comment by lunny** [comment]
@DblK yes. Let's continue there. @usef
