### ISSUE TITLE
Can't enter gopher hole in profile

### ISSUE THREAD

**Issue by 4y8** [go-gitea/gitea#14748]
I would like to put a link to my gopher hole in the website section of my profile. However, when I enter its URL, it tells me that it's not a valid URL because is starts with `gopher://`.

**Comment by jolheiser** [comment]
Here is the relevant code based on our form binding.
https://github.com/go-gitea/gitea/blob/afbddf1f0e93cf8b38a7244dfd434b448c81037d/modules/validation/helpers.go#L45-L53

**Comment by 6543** [comment]
@yul3n if you like, you could file a pull for it ;) :point_up:

**Comment by yul3n** [comment]
Here is the link to the pull request I made to add support fix it:
https://github.com/go-gitea/gitea/pull/14749

**Comment by yul3n** [comment]
Thanks for your support!

**Comment by sikmir** [comment]
The same issue for `gemini://` URL.
