### ISSUE TITLE
Allow gitea dump with readonly sqlite database

### ISSUE THREAD

**Issue by nickbabcock** [go-gitea/gitea#14740]
- Gitea version (or commit ref): 1.13.2
- Database:
  - [x] SQLite

## Description

Given that the following works:

```bash
docker run --rm -ti -w /tmp --user git -v "${PWD}:/tmp" --volume gitea_gitea:/data gitea/gitea:1 gitea dump
```

Mounting the volume as readonly will not work:

```bash
docker run --rm -ti -w /tmp --user git -v "${PWD}:/tmp" --volume gitea_gitea:/data:ro gitea/gitea:1 gitea dump
```

The `gitea dump` will error with:

```
Failed to dump database: attempt to write a readonly database
```

[As it appears the dump command tries to write to the database](https://github.com/go-gitea/gitea/blob/014313134f72ebb2ca57eb2e5cd42726231f8fff/models/models.go#L320)

It seems preferential to allows users to backup data without needing write access. Though I do not know what the solution would be that wouldn't regress on https://github.com/go-gitea/gitea/issues/14069 . Looking at the code and issues, it sounds like this problem will be resolved with 1.14 so feel free to close this issue if backporting a fix is not worth it.

**Comment by wxiaoguang** [comment]
If you do not lock the database, you get an inconsistent backup.
