### ISSUE TITLE
Proposal: hide explore menu

### ISSUE THREAD

**Issue by yusefmaali** [go-gitea/gitea#1475]
In some situations, the explore page may not be needed.

It should be very useful to have a config settings to hide at all the explore menu entry.
Something very similar to (for example) "DISABLE_REGISTRATION", we may have a "DISABLE_EXPLORE_MENU".

Thank you!

**Comment by strk** [comment]
Are you aware of the custom templates feature ?
With that you could easily hide the menu (but the page would still
be available by having a direct URL).

**Comment by yusefmaali** [comment]
This sounds pretty interesting.
Can you give some hints to look for more details?

**Comment by strk** [comment]
On Mon, Apr 10, 2017 at 02:09:00AM -0700, Yusef Maali wrote:
> This sounds pretty interesting.
> Can you give some hints where to looks for more details?

Uhm, I see the documentation is scarce:
https://docs.gitea.io/en-us/customizing-gitea/

It would be great if you could help improving it:
https://github.com/go-gitea/docs/blob/master/content/doc/advanced/customizing-gitea.en-us.md

Basically you copy any template from the `templates/` directory
into the `custom/templates/` directory, and modify as you see fit.
For your case it'd be the `templates/base/head.tmpl` to be copied
and modified.

Looking forward for your contribution to add a template section to
the documentation ! :)

**Comment by yusefmaali** [comment]
sure!

I need to pass through a Golang tutorial, then I will contribute for sure!

**Comment by strk** [comment]
I surely think it's worth passing the Golang tutorial, but will
note you don't need Golang expertise to provide *documentation*
patches (it's just text, markdown if you wish)

**Comment by yusefmaali** [comment]
Of course, you're right. I thought I needed to run gitea from its sources. I'm seeing the compiled version is enough.

**Comment by Spenhouet** [comment]
This would be a needed feature. User case: Non admin users should not be able to see other users and other repositories. Not sure, but hiding the explore page (also sub pages) could solve that.

**Comment by lafriks** [comment]
@Spenhouet just hiding menu won't solve that. Access should be controlled also when opening repository page and for that there is private repository setting. If it is set other users won't be able to see that repository

**Comment by lesderid** [comment]
Was this added? Seems like a sensible feature to have.
