### ISSUE TITLE
hCaptcha failed to initialize on link registration page

### ISSUE THREAD

**Issue by qwertfisch** [go-gitea/gitea#14766]
- Gitea version (or commit ref): 1.13.1
- Git version: irrelevant
- Operating system: Linux
  
  
  
- Database:
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No, because hCaptcha is not used in that Gitea instance

## Description

Using hCaptcha as captcha type, for all new users to register an inline hCaptcha element is displayed and needs to be solved by the user. This works well on the standard register page (`/user/sign_up`).

When using a __linked login__, e.g. login through Github and then trying to link the Github account with a new Gitea user to be registered, the hCaptcha element is not loaded because it cannot be initialized. Trying to complete the registration therefore fails because of not solved captcha.

### Login via external method

Before registration on Gitea, first login via Github. Then select __Register new account__ on the resulting page to link a new Gitea account with Github (`/user/link_account`). The inline hCaptcha element cannot initialize:
![registration1](https://user-images.githubusercontent.com/4212687/108640628-22f27500-749b-11eb-97a8-c65ac822311f.png)

### Registration fails
Just trying to complete the registration of course fails:
![registration2](https://user-images.githubusercontent.com/4212687/108640635-2a198300-749b-11eb-8c5b-a8a3ee728263.png)

## Expectation
I expect the hCaptcha element to load on both pages, `/user/sign_up` and `/user/link_account`. The latter is a specific case to register just using an external login and create a linked Gitea account without password. Nonetheless it should also work with hCaptcha and use the same hCaptcha credentials / keys as on the standard registration page.

**Comment by zeripath** [comment]
It would be helpful to tell us what the developer tools console says...
