### ISSUE TITLE
Replace `com.Expand`

### ISSUE THREAD

**Issue by jolheiser** [go-gitea/gitea#14760]
[Here is a search](https://github.com/go-gitea/gitea/search?q=com.Expand) (on GH) of our usage of [`com.Expand`](https://github.com/go-gitea/gitea/blob/f3e64f677fd242850beafb1767504722f2dc2703/vendor/github.com/unknwon/com/string.go#L89-L115).

We should think about replacing it with either template execution or [`os.Expand`](https://golang.org/pkg/os/#Expand).

There isn't anything necessarily wrong with `com.Expand`, but an stdlib implementation would be nice, and it would be manageable to refactor now.

**Comment by wxiaoguang** [comment]
Finally, it's done in 
* https://github.com/go-gitea/gitea/pull/19284

**Comment by lunny** [comment]
A little problem is the syntax between `vars/expand` and `os/expand` is not the same. So that `readme` init placeholder syntax is not the same as template repository.
