### ISSUE TITLE
External Authorization

### ISSUE THREAD

**Issue by willstott101** [go-gitea/gitea#14770]
Would you be interested in accepting a PR for external authorisation, where (for instance) a downstream service can be used to authorise requests rather than a database?

**Comment by lunny** [comment]
We have already support Oauth2/LDAP/Smtp and more.

**Comment by willstott101** [comment]
My understanding is that these can be used to authenticate, but then authorisation and repo-ownership is defined in the gitea-managed database, is that not correct?

**Comment by lunny** [comment]
Hm, yes. What's the benefit to store them to an external system?

**Comment by techknowlogick** [comment]
Closing as this would be suitable for a plugin system.

**Comment by willstott101** [comment]
Sorry, do you mean this is possible for a plugin already, or there should be a ticket covering an expansion of the plugin framework?

**Comment by techknowlogick** [comment]
We don't have a plugin system yet, however this would be a good candidate for when one is implemented.
