### ISSUE TITLE
why topics color are not green

### ISSUE THREAD

**Issue by synhi** [go-gitea/gitea#14787]
- Gitea version (or commit ref): 1.13.2
- Git version: 2.30.1
- Operating system: windows 10

- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
- Log gist:

## Description

i like the green topics, how can i get its?

## Screenshots

![image](https://user-images.githubusercontent.com/12025422/109040215-a4027400-7708-11eb-8212-10c6aec5f847.png)

![image](https://user-images.githubusercontent.com/12025422/109040398-d1e7b880-7708-11eb-81b4-f0b0d160c43b.png)

**Comment by techknowlogick** [comment]
You can customize the CSS of your instance using these instructions: https://docs.gitea.io/en-us/customizing-gitea/
