### ISSUE TITLE
when i try to merge two branch with above 12k of code changes then it will prompt 500 error how to resolve this?

### ISSUE THREAD

**Issue by akshathaphalady** [go-gitea/gitea#14788]
- Gitea version (or commit ref):
- Git version:
- Operating system:
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
- Log gist:

## Description

...

**Comment by techknowlogick** [comment]
Please fill in the template, as otherwise we can't help you with 0 information.
