### ISSUE TITLE
Run gitea in rootless mode as a specific uid

### ISSUE THREAD

**Issue by martencassel** [go-gitea/gitea#14780]
Would like to run gitea as a specific UID so it can access its files from a NFS share through Kerberos using the helm chart.
I don't know if the rootless work supports setting the uid ? 

This scenario works for docker images such as postgres or minio. They will create the wanted user during startup.

https://github.com/minio/minio/blob/2a79ea033206acfa74323e1719a869f8f6a69f1c/dockerscripts/docker-entrypoint.sh#L100
https://github.com/docker-library/postgres/blob/14f13e4b399ed1848fa24c2c1f5bd40c25732bdd/docker-entrypoint.sh#L67

**Comment by martencassel** [comment]
It this supported in https://github.com/go-gitea/gitea/pull/14626 @Kreyren  ?

**Comment by Kreyren** [comment]
> It this supported in https://github.com/go-gitea/gitea/pull/14626 @Kreyren  ? 

Partially implemented, is expected to change the UID, GID names and other configuration through environment variable configuration

**Comment by Kreyren** [comment]
Also just to clarify: You seem to want to run the rootless gitea docker as specific user.. That should be already possible (e.g. `su USER -c "docker-command-here"` or optimization of service on sysadmin side)

The https://github.com/go-gitea/gitea/pull/14626 implement this handling inside of the docker container used for debugging purposes.

**Comment by Kreyren** [comment]
EDIT: Also possible inside of the docker-compose using the `user` property documented in https://docs.gitea.io/en-us/install-with-docker-rootless/#custom-user

Consider joining the discord server on discord.gg/gitea is you need a guidance with it.
