### ISSUE TITLE
Replying discussion comments redirects to mail pull request page

### ISSUE THREAD

**Issue by lyz-code** [go-gitea/gitea#14797]
- Gitea version (or commit ref): 1.13.0
- Git version:
- Operating system: Ubuntu 20.04
  
  
  
Running from the binary downloaded from github.

- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
- Log gist:

## Description

While reviewing the discussions of a pull request under the "Files Changed" tab, when you reply to a comment, you get redirected to the "Overview"  page of the pull request. This hinders the process of reviewing as you need to go back to "Files changed" and then scroll down to find wherever you were. Directly answering in the Overview is not always possible as you need to review more code than its shown there.

**Comment by jpraet** [comment]
In 1.14 there is no redirect anymore. The reply comments are now submitted without refreshing the page: #13877
