### ISSUE TITLE
swastika avatars

### ISSUE THREAD

**Issue by davidak** [go-gitea/gitea#14799]
- Gitea version (or commit ref):
- Git version:
- Operating system:
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [X ] Yes https://try.gitea.io/339349330
  - [ ] No
- Log gist:

## Description
The swastica was used by the german fascist movement. Later, it was the sign of the right-wing german party NSDAP and the third reich. Now it's legally forbidden to use this sign in germany ([Strafgesetzbuch § 86a](https://en.wikipedia.org/wiki/Strafgesetzbuch_section_86a#Crossed-out_swastika)). It's also called „Hakenkreuz“ in germany.

Even this anti-fascist sign was long forbidden until a court decided that it is legal.

<img src="https://user-images.githubusercontent.com/91113/109158669-f7f67280-7773-11eb-8ec4-d0ad70d59600.png" width="50">

https://de.wikipedia.org/wiki/Swastika#/media/Datei:Anti-Nazi-Symbol.svg

The gitea avatar algorithm sometimes creates geometric shapes that could get recognised as swasticas. Therefore gitea could be considered illegal in germany.

That might sound a bit crazy and you could argue that it's just random geometric shapes, but it's a highly sensitive topic in germany and probably someone will show up and call you a fascist if you try to argue about it. I find it kind of ironic, because probably no one getting this random avatar is actually a fascist, but other people might be more sensitive.

So you might consider using a different algorithm for the avatar creation.

Related issue:

- https://codeberg.org/Codeberg/avatars/issues/1
- https://codeberg.org/Codeberg/Documentation/issues/55
- https://codeberg.org/Codeberg/Community/issues/394

It was also noticed in social media: https://social.tchncs.de/@cark/105651953031693352

## Screenshots

![4b49d4114ff3cb83475e5db5164494e6](https://user-images.githubusercontent.com/91113/109159298-c0d49100-7774-11eb-9f4f-4e7fd0fbfb7c.png) ![b3ed110ab76b8cfd207377b5f07405cf](https://user-images.githubusercontent.com/91113/109159552-07c28680-7775-11eb-9b14-a50082c93d76.png) ![18fbbeaff4f0b7fa5d43cb0f8327372c](https://user-images.githubusercontent.com/91113/109159300-c16d2780-7774-11eb-9d85-85fc2fd0aef5.png) ![38eb51f7be21116d19acbc5a95f1bf4b](https://user-images.githubusercontent.com/91113/109159303-c16d2780-7774-11eb-9317-e2140028b516.png) ![42e65d0b91208734ffa8a292479c0bc0](https://user-images.githubusercontent.com/91113/109159305-c16d2780-7774-11eb-970f-fd3aa94f2ebe.png) ![92ae996e87b6998b63bbc9092ec00b2a](https://user-images.githubusercontent.com/91113/109159306-c205be00-7774-11eb-90fc-ce924766d625.png) ![857c04e3f1b9474742353a6420523ebf](https://user-images.githubusercontent.com/91113/109159307-c205be00-7774-11eb-8eb8-e8701853b7fb.png) ![951b52225ed1cbc595bd385c34f86578](https://user-images.githubusercontent.com/91113/109159308-c205be00-7774-11eb-8c5d-25ae6a40307f.png) ![3374c6f251ca3cfc9bd62a3f5b691e0b](https://user-images.githubusercontent.com/91113/109159499-faa59780-7774-11eb-8aa0-89d37430ec16.png) ![5297b7c29a26c21151865e9539955e43](https://user-images.githubusercontent.com/91113/109159502-fc6f5b00-7774-11eb-8c0b-b4eb7a9300ee.png) ![95440b7510aec8cf685ae7511b070d26](https://user-images.githubusercontent.com/91113/109159531-02fdd280-7775-11eb-93b0-daba69040160.png) ![3689970e59c0c837adb50d6f39c11114](https://user-images.githubusercontent.com/91113/109159535-042eff80-7775-11eb-8c14-27bf11ee0b11.png) ![624453464ba38ab46180567a1f4bdc93](https://user-images.githubusercontent.com/91113/109159538-04c79600-7775-11eb-8902-979e39361320.png) ![d99585829753c5d8ce95639a79b823aa](https://user-images.githubusercontent.com/91113/109159577-0d1fd100-7775-11eb-8058-30691008d3fb.png) ![c73b6bd648d00da1ebfd61753672d0e0](https://user-images.githubusercontent.com/91113/109159564-0b560d80-7775-11eb-988d-922d78014b03.png) 

![6489c9467cc0ef15273aadd9784243ff](https://user-images.githubusercontent.com/91113/109159509-fe391e80-7774-11eb-87cc-5be7068a8434.png) ![6489c9467cc0ef15273aadd9784243ff-2](https://user-images.githubusercontent.com/91113/109159514-ff6a4b80-7774-11eb-9bc9-1fa23d475b37.png) ![41105](https://user-images.githubusercontent.com/91113/109159520-009b7880-7775-11eb-9a50-2e7982d6e6d2.png) ![41145](https://user-images.githubusercontent.com/91113/109159526-01cca580-7775-11eb-94ac-44da0d8c2ca5.png) ![c96c86ae2b934966fa0b070d75121b64](https://user-images.githubusercontent.com/91113/109159572-0beea400-7775-11eb-9c8d-6fc7fd99743c.png) ![a3d8d438cbc331492c311c24326d2ba5](https://user-images.githubusercontent.com/91113/109159542-05f8c300-7775-11eb-8958-ee6562d5dc10.png) ![ad864034c5e750fccda5cadc1b69a701](https://user-images.githubusercontent.com/91113/109159547-0729f000-7775-11eb-9e75-cc35318af671.png)

**Comment by noerw** [comment]
Legally this is not an issue I believe, as only the specific original symbol is banned afaik, not approximations thereof.
Socially I agree, I felt uneasy looking at some generated avatars in the past.

Pointing to https://codeberg.org/codeberg/avatars, which should be possible to integrate into mainline gitea

**Comment by 6543** [comment]
related: https://codeberg.org/Codeberg/Community/issues/394

**Comment by 6543** [comment]
if using codeberg/avatars ... `github.com/ajstarks/svgo` can be used to convert svg to an image witch is needed ...

**Comment by arogge** [comment]
I just stumbled across this issue.
Being a German myself, I can tell you that I had not recognized any of the above screenshots to contain a swastika if nobody had told me what to see. I'm completely sure none of the images presented is a legal issue in Germany.

In fact only two of the images contain a structure that looks at least remotely like a swastika to me. However, I'm sure there are people that are probably a lot of people who are much more sensitive than me, when it comes to this.
To overexaggerate this: displaying random images to a user is a Rorschach_test. If you show a lot of random images to a lot of people, somebody will recognize something they don't like.

As you will probably always run into some kind of issue with randomly generated images, the only real solution is probably to either provide a button to re-generate the avatar with another random seed if desired or to not to random-generate them, but to use a set of pre-generated and handpicked avatar images.

Just to add a bit more (completely biased) personal opinion: I like the idea of random avatar images. It is a lot better to have distinguishable random avatars instead of a single default avatar.

**Comment by arogge** [comment]
I just took a look at the DiceBear avatars. While I personally think they look great, I believe they have a lot more trigger-potential than the currently implmented random generation.

**Comment by jolheiser** [comment]
I would like to copy a comment from @techknowlogick in [CodeBerg/Community#394](https://codeberg.org/Codeberg/Community/issues/394#issuecomment-173985).

> I've ported several avatar generating libraries to golang. Once we get 1.14.0-rc1 out I will start on a PR that'll allow swapping out of the default avatar generation library.
> 
> src.techknowlogick.com/monster-id
src.techknowlogick.com/wavatars
src.techknowlogick.com/retricon

I think allowing the avatar generator to be chosen on install (and/or changed in config) would be sufficient for a host to choose whatever suits their use-case.

**Comment by zeripath** [comment]
This argument essentially boils down to any object with rotational symmetry order 4 and without mirror symmetry is a swastika. 

---

The avatars are generated using: 

https://github.com/issue9/identicon

Looking at the code this appears to build its avatars with deliberate 4th order rotational symmetry

It would not be hard to change:

https://github.com/issue9/identicon/blob/99644285dc221b04fde804663f754891d8759b46/identicon.go#L116-L144

```go
func drawBlocks(p *image.Paletted, size int, c, b1, b2 blockFunc, angle int) {
	// 每个格子的长宽。先转换成 float，再计算！
	blockSize := float64(size) / 3
	twoBlockSize := 2 * blockSize

	incr := func() { // 增加 angle 的值，但不会大于 3
		angle++
		if angle > 3 {
			angle = 0
		}
	}

	c(p, blockSize, blockSize, blockSize, 0)

	b1(p, 0, 0, blockSize, angle)
	b2(p, blockSize, 0, blockSize, angle)

	incr()
	b1(p, twoBlockSize, 0, blockSize, angle)
	b2(p, twoBlockSize, blockSize, blockSize, angle)

	incr()
	b1(p, twoBlockSize, twoBlockSize, blockSize, angle)
	b2(p, blockSize, twoBlockSize, blockSize, angle)

	incr()
	b1(p, 0, twoBlockSize, blockSize, angle)
	b2(p, 0, blockSize, blockSize, angle)
}
```

To break this symmetry by changing the angle placed in each corner from 0,1,2,3 to 0,1,3,2 instead.

---

Now my initial review of the code of this library is not entirely favourable - however, this is a question of developer effort and time spent looking for a new avatar library.

**Comment by CoderBuddhist** [comment]
@davidak can you please stop insult my religion?

> Just like the Hindus, the Buddhists also used the swastika to mark the beginning of Buddhist texts as they consider it a symbol of universal harmony, prosperity, plurality, good luck, abundance, dharma, fertility, long life, and eternity. In different parts of the world, the swastika is given a different meaning by the Buddhist. For instance, In Tibet, the swastika was a graphical representation of eternity. There are 65 auspicious symbols on the footprint of the Buddha and the swastika is considered as the first one. You can also find the swastika symbol imprinted on the body, palms, chest, or feet of Buddha. It is used to mark the beginning of sacred texts or as a clothing decoration. The Buddhists in India, consider swastika as “The Seal on Buddha’s Heart.”
> From ancient times, Swastika is considered noble, which is prominent in most cultures throughout history. It is also the most liked symbol of Aryans.

**Comment by jolheiser** [comment]
I'm going to go ahead and lock this discussion.

Further discussion can perhaps be moved to issues regarding new avatar generation libraries to add, or changing the parameters we use for identicon.

I think adding options would be a nice idea regardless the motivation, and I think that should also cover the use-cases presented.

**Comment by lafriks** [comment]
This could be replacement option: https://github.com/o1egl/govatar

**Comment by wxiaoguang** [comment]
Please have a look at:

* https://github.com/go-gitea/gitea/pull/17707
