### ISSUE TITLE
add daily specific Contribution Activity

### ISSUE THREAD

**Issue by JHenneberg** [go-gitea/gitea#14796]
Similar to GitHub it would be a neat feature when clicking on a specific day in your contribution calender your `Contribution Feed` would be updated accordingly.

![image](https://user-images.githubusercontent.com/6606609/109118942-4c81f980-7744-11eb-8a44-d911fce5c87e.png)

**Comment by noerw** [comment]
duplicate of #10843, will be fixed by #13935
