### ISSUE TITLE
With DigitalOcean One Click apps which uses Snap, gitea is not able to access the block storage

### ISSUE THREAD

**Issue by manikk** [go-gitea/gitea#14800]
With DigitalOcean One Click apps which uses Snap, gitea is not able to access the block storage.

**Comment by noerw** [comment]
see also #14126

**Comment by zeripath** [comment]
Do we even have control of the packaging of this package?

**Comment by lunny** [comment]
> Do we even have control of the packaging of this package?

Yes.

**Comment by techknowlogick** [comment]
This was recently resolved using the removable-media snap directive.
