### ISSUE TITLE
In version 1.13.2, when the default port was changed, push was abnormal and push failed

### ISSUE THREAD

**Issue by leehuajun** [go-gitea/gitea#14805]
- Gitea version (or commit ref):
- Git version: 1.13.2
- Operating system: CentOS7
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x ] No
- Log gist:

## Description

In version 1.13.2, when the default port 3000 was changed, push was abnormal and push failed

**Comment by techknowlogick** [comment]
please resync your git hooks. you can do this via the admin dashboard.
