### ISSUE TITLE
Grammatical mistake in Russian language

### ISSUE THREAD

**Issue by inzanty** [go-gitea/gitea#14809]
Gitea version (or commit ref): 1.13.2
Operating system: Ubuntu 18.04
Database: MySQL
Can you reproduce the bug at https://try.gitea.io: yes

![Screenshot_6](https://user-images.githubusercontent.com/53940590/109279224-2894e580-7822-11eb-808a-1fecea717df3.png)

So it's better to change this word to "Приватная команда" because "Приватизировать" 
conveys a different meaning.

**Comment by zeripath** [comment]
Translations are managed on https://crowdin.com/translate/gitea/all/enus-ru?filter=basic&value=0

Pop in your suggested translations on there and for more missing translations then pop to https://discord.gg/Gitea #translations and #russian to alert us of your changes and someone will go through approving them.

**Comment by zeripath** [comment]
And anyone else watching please do the same for the languages you speak too!
