### ISSUE TITLE
Stable image :1-rootless mentioned in install documentation is not available on docker hub

### ISSUE THREAD

**Issue by x-qq** [go-gitea/gitea#14819]
The page https://docs.gitea.io/en-us/install-with-docker-rootless/ under "Basics" mentions `:1-rootless` image, however it is not present currently on https://hub.docker.com/r/gitea/gitea/tags?page=1&ordering=last_updated

**Comment by techknowlogick** [comment]
rootless image hasn't been released as stable. If you'd like to use it then `:latest-rootless` is available.

**Comment by x-qq** [comment]
This was not a question, and the issue is not resolved.

The documentation clearly mentions a non-existing image.

**Comment by zeripath** [comment]
@x-qq if you would like to help progress the project to the point that we can release 1.14 we would appreciate testers and help. 

This kind of comment is not helpful.

We will get the rootless version released as soon as possible until then I'm sorry that the documentation isn't quite correct - but it will be soon.
