### ISSUE TITLE
Provide a front page for `/compare`

### ISSUE THREAD

**Issue by exap** [go-gitea/gitea#1481]
At the moment there are pages like
`/user/repo/compare/branch-a...branch-b`
but the page
`/user/repo/compare`
doesn't exist.

Github [supports this front page](https://help.github.com/articles/comparing-commits-across-time/). It'd be nice if Gitea would support this also.

I use Gitea 1.1.0

**Comment by gsantner** [comment]
Having an additonal "Compare" button (or/and a "changes since this commit") while viewing a commit would also be great

**Comment by lunny** [comment]
I think this is duplicated with #1352. Let's discuss continue there.
