### ISSUE TITLE
Localize Email Templates

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#14822]
at the moment email templates are not really localized, change this!

*Gitea version 1.14.0+dev-880-gb3056a026*

**Comment by zeripath** [comment]
https://github.com/go-gitea/gitea/blob/3d8b5ad5f37f495e50d83bbad214f8061f8a5ac4/services/mailer/mail.go#L227-L232

**Comment by 6543** [comment]
`pass users into func -> group them by lang -> render for each lang -> send chuncks independent ...`

**Comment by 6543** [comment]
Current state: all done beside replace strings in themplate with one in locale files by using Tr help function
