### ISSUE TITLE
[Feature Request] Add to whitelist domains without redeploying

### ISSUE THREAD

**Issue by kdumontnu** [go-gitea/gitea#14828]
The option to [whitelist email](https://docs.gitea.io/en-us/config-cheat-sheet/#service-service) domains is a great feature in Gitea. However, updating the whitelist requires changing the config and restarting gitea. 

Ideally, the web admin could view and update the whitelist in either `User Accounts`, `User Emails`, or `Configuration` 
AND through an API or endpoint. 
This will probably also require changing the config setting from `EMAIL_DOMAIN_WHITELIST` to something like `DEFAULT_EMAIL_DOMAIN_WHITELIST` or `INITIAL_EMAIL_DOMAIN_WHITELIST`.

The specific use-case is a company hosting Gitea as a service & adding a new customer domain.

If this functionality already exists please let me know and I'll gladly close this ticket.

**Comment by lafriks** [comment]
We should really start moving configuration to database imho

**Comment by techknowlogick** [comment]
Closing as dupe as there is more generic ticket of updating config without restart
