### ISSUE TITLE
Repo Transfer: If the sql transaction fails we will be left repository in the wrong place

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#14821]
If the transaction fails we will be left repository in the wrong place

_Originally posted by @zeripath in https://github.com/go-gitea/gitea/pull/14792#discussion_r584185299_

**Comment by noerw** [comment]
@6543 is this fixed? Not sure how the linked PR is related

**Comment by 6543** [comment]
Not jet ... related code was moved in that pull
