### ISSUE TITLE
feat: Fork page not allowing same owner even if the repo name is different

### ISSUE THREAD

**Issue by malikbenkirane** [go-gitea/gitea#14838]
- Gitea version (or commit ref): 1.12.6 
- Git version: not relevant
- Operating system: container image pulled from docker hub (tag 1.12.6), runtime: cri-o 1.18.x

- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (https://try.gitea.io/repo/fork/23472, https://try.gitea.io/testd711b1d40320fb4a12487f42/forktest)
  - [ ] No
- Log gist: not relevant here

## Description

Fork page currently disable forking a repo on the same organization. There is actually a workaround which is to transfer the ownership of the repo after fork has been prepared. I wonder what are the implications of that workaround and if there is deeper reasons not to allow that behavior.

Expected behavior: If the name of the repo is different that the original repo, allow the owner of the repo to be the same as the original owner.

## Screenshots

How to reproduce:
1. create an organization
2. create a repo for that organization and push anything there
3. fork the repo

At the fork page, you'll not be able to select that organization you just created even if you are able to change the repo name.

**Comment by lafriks** [comment]
It is intentional as it breaks other functionality if I remember correctly. Also what is use case to create multiple copies (forks) of same repository in one user/org?

**Comment by malikbenkirane** [comment]
We were thinking of creating a fork in one org to maintain two different versions of the same repo in that same org.

**Comment by zeripath** [comment]
Well I think the pr code might just be clever enough to cope without being forks - but you'd have to explicitly magic up the URL yourself because without them one being a fork of the other - or sibling forks - there's no way for the UI to know.

The head branch name should be owner/repo:branch iirc

**Comment by malikbenkirane** [comment]
Ok! @zeripath  Thank you for the details !
