### ISSUE TITLE
odd markdown behaviour with code blocks in lists

### ISSUE THREAD

**Issue by fnetX** [go-gitea/gitea#14835]
- Gitea version (or commit ref): 1.13 (Codeberg) + 1.14 (try.gitea.io)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes https://try.gitea.io/fnetx/markdown-issues/issues/1

## Description
A user on Codeberg.org pointed out, that the behaviour of Gitea's markdown rendering in ordered lists is somewhat odd when using code blocks.
Especially code blocks don't work in ordered lists as the counting is restarted afterwards.
Markdown code blocks are also unsupported when using an HTML list.

Please also refer to this very detailed comment in the original issue thread: https://codeberg.org/Codeberg/Community/issues/67

Oh and please note, that **Gitea actually has the same behaviour as GitHub shows**, but it seems to be technically violating the GFM specs.

## Screenshots

<details><summary>Code blocks in markdown lists</summary>
<pre>
1. item one
1. item two
1. item three with code
1. item four has a code block
```
code line one
code line two
```
1. item five
</pre>

is shown in Gitea (and actually GitHub) as 
![Screenshot](https://user-images.githubusercontent.com/19634137/109430425-bd096e80-7a01-11eb-9870-2afefbb51635.png)
There was already a debate whether this is actually violating the GFM specs.
</details>

<details><summary>Code fence within an HTML list</summary>
This

    <ol><li>yada yada<li>
    ```
    block of code
    ```
    <li>last item</ol>

is shown in Gitea and GitHub as
![Screenshot](https://user-images.githubusercontent.com/19634137/109430813-7157c480-7a03-11eb-8d2a-7d945d0723ef.png)
</details>

**Comment by zeripath** [comment]
So what you're saying is that we render exactly the same as Github? I'm afraid then we have to mark this as not-a-bug.

However, in your second case if you change it to:

    <ol><li>yada yada<li>
   
    ```
    block of code
    ```
    
    <li>last item</ol>

Note the empty lines it renders:

<ol><li>yada yada<li>

```
block of code
```

<li>last item</ol>

See https://try.gitea.io/arandomer/pathological/src/branch/master/issue-14835.md
