### ISSUE TITLE
bug: Excluding more than two labels does not work

### ISSUE THREAD

**Issue by MGChecker** [go-gitea/gitea#14840]
- Gitea version (or commit ref): 1.13.2
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL) https://try.gitea.io/MGChecker/DokuForge2/pulls?q=&type=all&sort=&state=open&labels=-12523%2c-12525&milestone=0&assignee=0
  - [ ] No

## Description

If you try to exclude labels by using Alt+Click, after doing this with the third one the exclusion of the first one you selected is removed.

**Comment by jaqra** [comment]
The problem is here:

https://github.com/go-gitea/gitea/blob/master/web_src/js/index.js#L3761-L3767

We should change regex like:

```js
// TODO: Remove `href` and `newStr` constants;

window.location = href.replace(new RegExp("labels=(-?\\d+)(%2c-?\\d+)*&"), function (match) {
    return match.replace(new RegExp(`(=|c)(${id})(%|&)`), "$1-$2$3");
});
```

@6543 Can you test and send pr for this please :)

**Comment by 6543** [comment]
@jaqra didn't helped :/
