### ISSUE TITLE
Missing SSH public keys from LDAP

### ISSUE THREAD

**Issue by strk** [go-gitea/gitea#14849]
I'm still having trouble with public ssh keys synchronization from LDAP.
I have added 4 sshPublicKey in LDAP but only see 2 in Gitea.

One thing I noticed is that 3 of those 4 keys I have in LDAP all start with the same list of characters, and the portion of the key shown by Gitea is the start of such "common substring". Maybe Gitea is just assuming the keys are EQUAL due to this shared initial string ? The keys are of ecdsa-sha2-nistp521 type and the first character outside the substring shown by Gitea is a `b` (not found before).

It would help if Gitea showed the whole key somehow, or at least the key comment at the end, to know what it's taking in consideration.

 Gitea Version: 1.12.3

**Comment by strk** [comment]
Sorry, I was misleaded by the need to logout/login again to see changes done in LDAP.
Now that I did I realize that with the given version of Gitea, only a SINGLE key is retrieved from LDAP when there are multiple ones.

Sounds like a revival of  #13984 but I cannot find traces of the fix for that one in the CHANGELOG.md file. @zeripath any idea bout that ? Could you figure that out and add to CHANGELOG in the appropriate section ?

**Comment by strk** [comment]
Logs from Gitea, about the "common substring":
> 2021/03/02 01:54:15 models/user.go:1746:addLdapSSHPublicKeys() [E] addLdapSSHPublicKeys[OSGeo LDAP]: Error adding LDAP Public SSH Key for user strk: public key already exists [owner_id: 2, name: OSGeo LDAP-ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTIt]

**Comment by strk** [comment]
Another problem (needs another ticket?) is that even if I enter a _single_ key, `ecdsa-sha2-nistp521` typed ssh key seems not supported (`rsa` works)

**Comment by zeripath** [comment]
Gitea Version: 1.12.3 <- do you mean 1.13.2 or 1.12.3?
