### ISSUE TITLE
[Bug] Deleting wiki page returns 404

### ISSUE THREAD

**Issue by delvh** [go-gitea/gitea#14844]
- Gitea version (or commit ref): 1.14.0+dev-786-gf0e15250b

## Description
When deleting a wiki page, the user gets redirected to
`{repo}/wiki/`
which appears to be outdated as the new value seems to be
`{repo}/wiki/_pages`.
Hence a 404 error gets returned, which is a bit annoying: It implies the task failed successfully.

**Comment by a1012112796** [comment]
releated to https://github.com/go-chi/chi/issues/594

**Comment by delvh** [comment]
Let's hope it will be fixed.
How often does try.gitea.io get updated, or better: When will it get updated for that specific commit to test?

**Comment by 6543** [comment]
@delvh try should be ready to test ...

> How often does try.gitea.io get updated

each merge into master

**Comment by delvh** [comment]
is currently still at commit def964e which is the one before the merged PR…

**Comment by 6543** [comment]
-> if https://drone.gitea.io/go-gitea/gitea/36548 passes it will update ...

**Comment by delvh** [comment]
Okay, that makes more sense. Thanks!

**Comment by delvh** [comment]
Works. Even better, if I manually delete the `_pages` part, I always get redirected to `{repo}/wiki/_pages` automatically.
