### ISSUE TITLE
gitea-1.13.2-linux-mipsle: Illegal instruction

### ISSUE THREAD

**Issue by zhaojh329** [go-gitea/gitea#14857]
Downloaed from https://github.com/go-gitea/gitea/releases/download/v1.13.2/gitea-1.13.2-linux-mipsle

**Comment by techknowlogick** [comment]
closing as dupe of https://github.com/go-gitea/gitea/issues/14857

**Comment by delvh** [comment]
Wait a second…
Did you just close #14857 with the reason being that it is a duplicate of #14857?

**Comment by jolheiser** [comment]
He may have meant #14034, as he commented on it shortly after this one. 🙂
