### ISSUE TITLE
repository can not be push, and there is a 401 report in log

### ISSUE THREAD

**Issue by YeChuanShun** [go-gitea/gitea#14858]
- Gitea version (or commit ref): 1.12.4
- Git version:  1.8.3.1
- Operating system: Centos 7
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
- Log gist:

## Description

...
I can not push all repository ,and there is a 401 report in log,

## Screenshots

![image](https://user-images.githubusercontent.com/44352976/109755695-6da18900-7c21-11eb-8144-0f012df59798.png)
![image](https://user-images.githubusercontent.com/44352976/109756424-e5bc7e80-7c22-11eb-8bf6-338cf880944a.png)

![image](https://user-images.githubusercontent.com/44352976/109755908-d5f06a80-7c21-11eb-8580-72674c231ab9.png)

**Comment by techknowlogick** [comment]
Please try "resynch-ing hooks" via the admin dashboard, however you are several versions behind please update to the latest stable version 1.13.2 as well. If you have questions about this please open a post in the [forum](https://discourse.gitea.io/) or join us in chat at https://discord.gg/gitea if this is still an issue.
