### ISSUE TITLE
Deploying gitea on Qovery platform

### ISSUE THREAD

**Issue by hbk-ronak** [go-gitea/gitea#14859]
- Gitea version (or commit ref):
- Git version: 1.13
- Operating system: Trying to Deploy on Qovery platform
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
- Log gist:

## Description

Unable to deploy on qovery. Deployment is successful but the app throws the following log:

```
Connection closed by 10.244.35.163 port 59598
Could not load host certificate "/data/ssh/ssh_host_ed25519_cert": No such file or directory
Could not load host certificate "/data/ssh/ssh_host_rsa_cert": No such file or directory
Could not load host certificate "/data/ssh/ssh_host_ecdsa_cert": No such file or directory
Could not load host certificate "/data/ssh/ssh_host_dsa_cert": No such file or directory
kex_exchange_identification: Connection closed by remote host
```
...

**Comment by techknowlogick** [comment]
Those are warnings and don't prevent gitea from operating.
