### ISSUE TITLE
Gitea Issues link are formated using localhost:3000 and not the actual name of the site used from the internet.

### ISSUE THREAD

**Issue by gissehel** [go-gitea/gitea#14851]
- Gitea version (or commit ref): **1.14.0+dev-782-gfaf775c55**
- Git version: 
- Operating system: 
  - docker based using official (docker.io/)gitea/gitea(:latest) image (more exactly the image **sha256:831a7ce1c8566419b53f7a8044aac4c24cd4a70937fc73cf60c74efba6e0bfef**).
  - The image is hosted on a **amd64**/**x86_64** server.
  - The server is accessed threw a nginx frontend generating https using a certificated delivered by letsencrypt.
  - The screen capture are from a clean install of gitea after discovering the problem on a real life installation.
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
 
## Description

I have tryed without a proxy as the problem is interaction with the proxy, but doesn't seems to be a configuration problem of the proxy.

This was reprocduced from scratch after:
- Creating a new instance of gitea (hosted on for example **https://gitea-test.example.com/**)
- Creating a admin account
- Creating a user account
- Creating a repo with the user account

Steps to reproduce:
- Create an issue
- Go to the issue tabs

Expected result:
- The link to the issue goes to something like **https://gitea-test.example.com/test-user/barfoo/issues/1**

Actual result:
- The link to the issue goes to something like **http://localhost:3000/test-user/barfoo/issues/1**

## Screenshots

![20210302-121625-gitea-bug](https://user-images.githubusercontent.com/199364/109643129-1b466680-7b54-11eb-8bd1-f9cb3acef7e4.jpg)

While hovering the link:

![20210302-121659-gitea-hover](https://user-images.githubusercontent.com/199364/109643585-b5a6aa00-7b54-11eb-9615-a286f2d2fd7a.jpg)

## Notes

- I haven't yet tryed to update to the latest image, but the image should date back from last saturday. I'll try and post a follow up
- I haven't been able to find a similar issue here
- The problem exists at least in both issues page a projects as in global issues, but you can access the issues correctly threw the dashboard.

**Comment by gissehel** [comment]
The issue issue is still present with latest version of the docker image:
- gitea/gitea:latest : sha256:1aa3a172b0fe66ab5e0e3fa5ca8ce548251b45023451507984ea09031a34ed9b
- gitea version : **1.14.0+dev-786-gf0e15250b**

**Comment by noerw** [comment]
You need to set `ROOT_URL` in app.ini, see https://docs.gitea.io/en-us/config-cheat-sheet/#server-server

If the problem persists, feel free to reopen
