### ISSUE TITLE
Make go packages from subdirectories on gitea instances installable with "go get"

### ISSUE THREAD

**Issue by jcgruenhage** [go-gitea/gitea#1485]
Currently, you can't fetch go projects from gitea, without the .git extension. This causes the binaries to have this ugly .git extension too and prevents people from fetching projects from subdirectories.

Documentation of meta-tags: https://golang.org/cmd/go/#hdr-Remote_import_paths
The PR and commit that fixed this in gitlab: https://github.com/gitlabhq/gitlabhq/pull/7693 https://github.com/gitlabhq/gitlabhq/commit/e23d6ada1c234acd45b676a34a2997aeae94d087

**Comment by jcgruenhage** [comment]
Since this affects me more than I thought, I've decided to start looking into it. I've found that the header file in the base template folder already contains a meta tag for that, but that doesn't work, because somehow {{.GoGetImport}} doesn't start with the domain, but with localhost instead.

**Comment by lunny** [comment]
@jcgruenhage any news?

**Comment by lunny** [comment]
I test `go get git.lunny.info/lunny/tango`. There is no problem. I found that you have to add `DOMAIN = <your domain>` on your custom/conf/app.ini before `SSH_DOMAIN` to let it work.

**Comment by jcgruenhage** [comment]
I've changed the title. If the root directory is the go project you want to get, there is no problem, but if you want to get something in a subdirectory, that does not work, since the 404 page does not contain the appropriate meta tags.

**Comment by jcgruenhage** [comment]
## Works: 
```go get git.host.tld/user/repo```

## Doesn't work:
```go get git.host.tld/user/repo/subdir```

### Workaround:
Clone the repo into ```$GOPATH/src/git.host.tld/user/repo``` first.

**Comment by lunny** [comment]
#1518 should fix `go get git.host.tld/user/repo/subdir` have you tried that?

**Comment by jcgruenhage** [comment]
I am not sure why, but it seems to work.. I didn't think that that HTTP func was actually called when serving a 404..
