### ISSUE TITLE
[BUG] [DOCS] example of using env vars in docker is broken

### ISSUE THREAD

**Issue by vvvrrooomm** [go-gitea/gitea#14853]
- Gitea version (or commit ref): master

- Log gist:
" ORM engine initialization attempt #3/10 failed. Error: Failed to connect to database: Unknown database type:"

## Description
in [1] it says """
Environment variables
You can configure some of Gitea’s settings via environment variables:
"""
this is misleading. gitea never consumes any environment variables. 
environment variables are consumed by helpers like `envsubst` or `environment-to-ini` 
PR#14762 added its specific syntax to the documentation in a later paragraph, which is good.

[1] https://docs.gitea.io/en-us/install-with-docker/#managing-deployments-with-environment-variables

Please make clear that gitea does not consume env variables and that the provided docker image contains extra logic, e.g.:
"""
Environment variables
Gitea cannot be configured using environment variables! To work around that the provided docker image contains helpers `envsubst` and `environment-to-ini` which consume a template app.ini file to create a app.ini which contains certain envrionment variables. this requires write access to the storage location of app.ini 
"""

**Comment by techknowlogick** [comment]
Here is the list of environment variables that Gitea accepts directly: https://docs.gitea.io/en-us/environment-variables/

The documentation you are looking at is specifically for the docker container as mentioned on that page.
