### ISSUE TITLE
[FR] add API to get available reviewers & assignees

### ISSUE THREAD

**Issue by noerw** [go-gitea/gitea#14856]
expose `repo.GetReviewers()` as `GET /api/v1/repos/<owner>/<repo>/reviewers`
expose `repo.GetAssignees()` as `GET /api/v1/repos/<owner>/<repo>/assignees`

https://github.com/go-gitea/gitea/blob/a4148c0f12fe5a93d2c9a40f24d4813bcfef4ff8/models/repo.go#L617-L624

This would be helpful for `tea issue create`

**Comment by 6543** [comment]
blocking
 * https://codeberg.org/gitnex/GitNex/issues/200
 * https://gitea.com/noerw/tea/src/branch/issue-create-opts/modules/interact/issue_create.go#L118
