### ISSUE TITLE
Repo size on web isn't updated after Auto GC

### ISSUE THREAD

**Issue by bagasme** [go-gitea/gitea#14862]
- Gitea version (or commit ref): master (commit b2986ab8b2671c2779aa4a8b72cb7947c62402a4)
- Git version: 2.30.1
- Operating system: Debian 10
  
  
  
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No (not relevant)
- Log gist: (not relevant)

## Description

When auto gc occurs, the actual repo size is shrinked, but the repo size on web interface isn't updated accordingly.

For example, today I pushed recent commits on `git.git` (Git SCM repo) to my local Gitea instance, then auto gc was invoked. 
After auto gc, the repo size was about 132 MiB, but on the web interface the size was still 211 MiB (before gc)

## Screenshots

![on web interface](https://user-images.githubusercontent.com/40219486/109787680-0f849e00-7c41-11eb-835d-c9149c05b453.png)
*on web interface, repo size: 211 MiB*
![git count-objects -v on the instance](https://user-images.githubusercontent.com/40219486/109787940-57a3c080-7c41-11eb-9dff-cf876d817ec8.png)
*git count-objects -v when accessing the interface, repo size: 132 MiB*

**Comment by zeripath** [comment]
UpdateSize is only called during PushUpdates - I guess the auto gc happened after PushUpdates was called. 

I'm not really sure what we can do - updating size is an expensive function. The only thing I can imagine is a cron task that can be called to update things.

**Comment by 6543** [comment]
add it to the cron task that gc repos?

**Comment by bagasme** [comment]
@6543 seems ok
