### ISSUE TITLE
db password contains special character will not read correctly

### ISSUE THREAD

**Issue by scofieldpeng** [go-gitea/gitea#14868]
- Gitea version (or commit ref):
- Git version: 1.13.2
- Operating system:
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
- Log gist:

## Description

When the db password contains special characters like @,$,# etc, gitea can't read it from app.ini file correctly and gitea can't run.

**Comment by jolheiser** [comment]
https://docs.gitea.io/en-us/config-cheat-sheet/#database-database

> Use \`your password\` or """your password"" for quoting if you use special characters in the password.
