### ISSUE TITLE
[wishlist] Server-side reflog

### ISSUE THREAD

**Issue by mateusza** [go-gitea/gitea#14865]
There should be an option to enable server-side reflog for all or specific repositories. This is very helpful when somebody accidentally `push -f`

https://stackoverflow.com/questions/48769443/git-reflog-in-bare-repository-with-core-logallrefupdates-set-true-returns-nothin

**Comment by zeripath** [comment]
why not just set this value in the gitea user's .gitconfig?

**Comment by mateusza** [comment]
> why not just set this value in the gitea user's .gitconfig?

Why not just user bare repositories, command line git and regular SSH access instead of this Gitea thing? :-)

Of course you can set this value per repository, as long as you are the server administrator.

It would be nice to let repository owners set this with Gitea web interface; also possibly make it default per server, per user, per organization etc.

**Comment by philip-peterson** [comment]
This has been implemented now via config option. Issue can likely be closed.
