### ISSUE TITLE
in Swagger UI repo.projects is missing in model of /orgs/{org}/teams

### ISSUE THREAD

**Issue by netcicd** [go-gitea/gitea#14875]
It looks like the projects toggle in https://try.gitea.io/api/swagger#/organization/orgCreateTeam is missing (bold in the list below). 

Adding it manually in the call does work properly though.

tooling_team_write_payload='{ 
    "can_create_org_repo": true, 
    "description": "The tooling team - can write", 
    "includes_all_repositories": false, 
    "name": "gitea-tooling-write", 
    "permission": "write", 
    "units": [
        "repo.code",
        "repo.issues",
        "repo.ext_issues",
        "repo.wiki",
        "repo.pulls",
        "repo.releases",
        **"repo.projects",**
        "repo.ext_wiki"
        ]
    }'
tooling_team_write_data=`curl -s --user $user:$pwd -X POST "http://gitea:3000/api/v1/orgs/infraautomator/teams" -H "accept: application/json" -H "Content-Type: application/json" -d "${tooling_team_write_payload}"`

**Comment by zeripath** [comment]
That's an example - it not supposed to list all of the possible values.

**Comment by jolheiser** [comment]
> That's an example - it not supposed to list all of the possible values.

In the context of Swagger UI I think it should show all possible values, though. Otherwise there's really no way for a user to discover the possible values, is there?

**Comment by noerw** [comment]
Is there a way to make the UI show the model (wihch includes all fields) by default, instead of the example?

**Comment by zeripath** [comment]
The swagger ui is a rendering from a fixed file. You'd need to add something to /api/v1/settings/repository to get it to return the default units I think.
