### ISSUE TITLE
[Bug] SSH key verification fails in rootless contaner image

### ISSUE THREAD

**Issue by Starefossen** [go-gitea/gitea#14889]
- Gitea version (or commit ref):  Gitea version 1.14.0+dev-795-ga5279b74b built with GNU Make 4.3, go1.16 : bindata, timetzdata, sqlite, sqlite_unlock_notify
- Git version: git version 2.24.3 (Apple Git-128)
- Operating system: gitea/gitea:latest-rootless
  
  
  
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
- Log gist:

```
Can not verify your SSH key: SSHKeyGenParsePublicKey: fail to parse public key: exec: "ssh-keygen": executable file not found in $PATH -
```

## Description

When running the `-rootless` Gitea container image you are unable to add SSH keys due to `ssh-keygen` not being installed.

## Screenshots

![Screenshot 2021-03-05 at 01 04 23](https://user-images.githubusercontent.com/968267/110047763-c0c52a00-7d4e-11eb-8733-a9e015c05a43.png)

**Comment by techknowlogick** [comment]
@Starefossen thanks for report. Are you able to see if #14891 resolves the issue?

**Comment by zeripath** [comment]
Hmm we shouldn't need ssh-keygen if we're using the internal SSH server

**Comment by zeripath** [comment]
Yes I'm right here. The only place that SSHKeyGenParsePublicKey is called is here:

https://github.com/go-gitea/gitea/blob/9db590f2ee198fa260c16387a8baa73f107db533/models/ssh_key.go#L345-L351

Which requires `DISABLE_SSH = false` and `START_SSH_SERVER = false` which does not make sense for the rootless docker as there is no other SSH server in that docker.

Therefore - @Starefossen how exactly are you intending SSH to be provided on the rootless docker without there being an SSH server on it?

**Comment by Starefossen** [comment]
Good point @zeripath. I hadn't come that far. From a security point of view I want to run Gitea without root. I guess that shouldn't be a problem for SSH - the unprivileged port 2222 is referenced in the docs so I guessed it was supported.

**Comment by techknowlogick** [comment]
Gitea has an ssh server built-into its binary, so like @zeripath said I recommend looking into the `START_SSH_SERVER` variable to use that SSH server (rather than the opensshd server that is used in the rootful container).

**Comment by Starefossen** [comment]
Setting `START_SSH_SERVER` to `True` solved the problem. I have added that as default value for the Helm Chart when using the `rootless` image. Thanks for helping 😄  https://gitea.com/gitea/helm-chart/pulls/129

**Comment by zeripath** [comment]
no problem
