### ISSUE TITLE
commit graph rendering issues

### ISSUE THREAD

**Issue by Spongman** [go-gitea/gitea#14887]
- Gitea version (or commit ref): 1.13.2
- Git version: 2.18.4
- Operating system: centos7 systemd Go1.15.7
- Database (use `[x]`):
  - [x] MySQL
- Can you reproduce the bug at https://try.gitea.io:
  - [x] No
- Log gist:

## Screenshots

![image](https://user-images.githubusercontent.com/1088194/110017083-a6e9ff80-7cda-11eb-85a9-67d05ad87846.png)

not sure if this is git's fault or not but:
1. there's a dark purple horizontal line that seems out of place
2. right above that the olive-colored branch starts from thin air
3. (minor) couldn't the splits be simplified, like this?

![image](https://user-images.githubusercontent.com/1088194/110020009-ebc36580-7cdd-11eb-9ce8-4ce6455a1d2c.png)

**Comment by zeripath** [comment]
Can you replicate on try so I can fix the algorithm for 1&2

Point 3 is feature of the way we read and convert from git's output so wouldn't be possible to fix easily. 

However replicate on try and then we can see.

**Comment by zeripath** [comment]
Output is parsed here:

https://github.com/go-gitea/gitea/blob/11229ca53990fcb163b35295a2300daaf3ba7f47/modules/gitgraph/graph.go#L20

But most of the work is in here:

https://github.com/go-gitea/gitea/blob/11229ca53990fcb163b35295a2300daaf3ba7f47/modules/gitgraph/parser.go#L47

**Comment by zeripath** [comment]
an alternative to replicating the issue on try would be to give me the dump of the following:

```
git log --graph --date-order --decorate=full -C -M --date=iso --pretty="format:DATA:||||"
```

**Comment by zeripath** [comment]
I'm going to assume that this is fixed. Please reopen with a replicable example if not.
