### ISSUE TITLE
Gitea over internet - Reverse proxy with Apache not working - https

### ISSUE THREAD

**Issue by njarun** [go-gitea/gitea#14882]
- Gitea version (or commit ref): gitea-1.13.2-linux-arm-6 (on Raspberry pi, ubuntu server 20.04.2 LTS)
- Git version: 2.25.1
- Operating system: Ubuntu Server 20.04.2 LTS x64 - for rpi 4

- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
  
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] N. A

## Description

Tried setting up https access to my gitea repo. But no chance it setting it up with Apache reverse proxy.  Below is the config files we used for to set it up. But never worked, tried combinations of local host and local ip for HTTP_ADDR in the app.ini file. Nothing worked. Please let us know, if its the config issue or not the way to do it!

Apache .conf file

```
<VirtualHost *:80>

  ServerAdmin ubuntu@localhost
  ServerName www.mysite.duckdns.org
  ServerAlias mysite.duckdns.org

  RewriteEngine on
  RewriteCond %{HTTPS} !=on
  RewriteRule .* https://%{SERVER_NAME}%{REQUEST_URI} [NE,R,L]

</VirtualHost>

<VirtualHost *:443>

    ServerAdmin ubuntu@localhost
    ServerName www.mysite.duckdns.org
    ServerAlias mysite.duckdns.org

    ProxyPreserveHost On
    ProxyRequests off
    AllowEncodedSlashes NoDecode
    ProxyPass / http://localhost:3006 nocanon
    ProxyPassReverse / http://localhost:3006

    <IfModule mod_headers.c>
       Header always set Strict-Transport-Security "max-age=15552000; includeSubDomains"
    </IfModule>

    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined

    SSLEngine on
    SSLCertificateFile /etc/letsencrypt/live/mysite.duckdns.org/cert.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/mysite.duckdns.org/privkey.pem
    SSLCACertificateFile /etc/letsencrypt/live/mysite.duckdns.org/chain.pem

</VirtualHost>
```

Gitea config file - /etc/gitea/app.ini 

```
APP_NAME = Gitea: Private code dump
RUN_USER = git
RUN_MODE = prod

[server]
PROTOCOL         = http
HTTP_PORT        = 3006
SSH_DOMAIN       = localhost
DOMAIN           = localhost
ROOT_URL         = https://mysite.duckdns.org/
HTTP_ADDR        = 
DISABLE_SSH      = false
SSH_PORT         = 22
LFS_START_SERVER = true
LFS_CONTENT_PATH = /path/to/gitea/data_dir/data/lfs
LFS_JWT_SECRET   = *******
OFFLINE_MODE     = false
```

## Screenshots
  - [x] N. A

**Comment by njarun** [comment]
Any help appreciated!! Is this the right settings?

**Comment by techknowlogick** [comment]
@njarun we are all volunteers here, so if we can't always respond to tickets as quickly as 12hours opening them up. I'm going to close this however as it is better suited for our chatroom/forum: https://docs.gitea.io/en-us/seek-help/
