### ISSUE TITLE
Problem with migrating repositories containing LFS objects

### ISSUE THREAD

**Issue by morpheus-87** [go-gitea/gitea#14896]
- Gitea version (or commit ref): 1.13.1
- Git version: 2.20.1
- Operating system: Raspbian 10 (Buster)
  
I'm using the binary from https://dl.gitea.io/gitea.
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
- Log gist:

## Description

I have some problems while migrating an existing Gitea instance to a new hardware, especially with repositories containg LFS objects. On the old system, I could see the images in the UI - after the migration, I only see this:
```
version https://git-lfs.github.com/spec/v1
oid sha256:be0a076d8463d95cca1c57863af10d813cf44a8f63d9de20256227010c06c587
size 608901
```
What can I do?

**Comment by zeripath** [comment]
We cannot currently migrate the lfs assets for you automatically - you will have to do a git lfs fetch --all on a local checkout and then git lfs push --all back up to the gitea server.

There is a WIP PR looking at attempting to get automatic LFS migration in to gitea but it is not an easy feat.

**Comment by zeripath** [comment]
Duplicated with #9939
