### ISSUE TITLE
gitea.io infinite redirect loop

### ISSUE THREAD

**Issue by plessbd** [go-gitea/gitea#1490]
It seems gitea.io is in an infinite redirect loop.

Seems like https was enabled using cloudflare and the page now always get redirected to https://gitea.io:443/

We also should update the repo description to have https instead of http (saves a redirect...)

**Comment by sapk** [comment]
This would be related to traefik front-end and a fix is ready to be apply in go-gitea/infrastructure#15

**Comment by plessbd** [comment]
this has been resolved
