### ISSUE TITLE
A new doctor check should be added that an issue should not be added a label belong to another repository.

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#14908]
Just found some the problem on gitea.com

**Comment by zeripath** [comment]
Sounds like this is a consistency check

**Comment by zeripath** [comment]
I assume that the autofix solution is that the comment is removed

**Comment by zeripath** [comment]
This is a considerably more involved issue than it at first appears.

**Comment by zeripath** [comment]
Do we know how these labels even end up happening?

**Comment by lunny** [comment]
I guess it's related with restore-repo command because I ever execute that command on gitea.com to test migrating gitea itself.
