### ISSUE TITLE
Cannot push to repository.

### ISSUE THREAD

**Issue by raghavken** [go-gitea/gitea#14934]
- Gitea version (or commit ref): 1.13.2
- Git version:  2.25.1
- Operating system: Ubuntu 20.04 LTS

Running gitea from docker.
- Database (use `[x]`):
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X] No
- App.ini
```ini
[server]
APP_DATA_PATH    = /data/gitea
DOMAIN           = 10.0.0.146
SSH_DOMAIN       = 10.0.0.146
HTTP_PORT        = 8080
ROOT_URL         = http://10.0.0.146:8080/
DISABLE_SSH      = false
SSH_PORT         = 2221
SSH_LISTEN_PORT  = 22
LFS_START_SERVER = true
LFS_CONTENT_PATH = /data/git/lfs
LFS_JWT_SECRET   = _fnDUuWNFFz_AI6z6j5PsmIgxzpvaRvJWRxnNOhmZz0
OFFLINE_MODE     = false
```
When I push it looks like it's making a request to localhost but I never set the domain or root URL to localhost as you can see in my app.ini.

## Screenshots
![image](https://user-images.githubusercontent.com/33642056/110493416-40892680-80b8-11eb-9598-724726beb854.png)

**Comment by jolheiser** [comment]
Take a look at the config [server section](https://docs.gitea.io/en-us/config-cheat-sheet/#server-server), `LOCAL_ROOT_URL`.

That is what Gitea uses when calling its hooks. Alternatively, you could also set `HTTP_ADDR`, as that defaults to `0.0.0.0` and `LOCAL_ROOT_URL` is then set as `localhost` on startup.
