### ISSUE TITLE
Official builds for Apple M1

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#14945]
## Description
From my local testing Gitea builds and runs fine using Go 1.16 on an M1 machine. Can official builds be provided for this system type?

**Comment by lunny** [comment]
Could xgo support that?

**Comment by jolheiser** [comment]
I believe it is supported. 

ref: https://github.com/techknowlogick/xgo/issues/89#issuecomment-781613725

**Comment by techknowlogick** [comment]
Indeed it is supported by xgo. I've submitted a PR to gitea to support it.
