### ISSUE TITLE
anchor links in gitea rendered md file don't work 

### ISSUE THREAD

**Issue by Bubu** [go-gitea/gitea#14968]
- Gitea version (or commit ref): 1.13.4+15-g7aaa02e22 (codeberg.org)
- Git version: ?
- Operating system: Archlinux

- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes
  - [ ] No

## Description

This link which you get by clicking on the anchor icon in the markdown heading in this file doesn't jump to the right section when loading the page again:

https://try.gitea.io/Bubu/TEST/src/branch/main/FAQ_de.md#warum-ben%C3%B6tigt-die-app-zugriff-auf-meinen-standort

## Screenshots

![image](https://user-images.githubusercontent.com/105185/110944525-de8d2300-833c-11eb-963e-575481e6734f.png)

**Comment by fnetX** [comment]
Probably related to the Umlauts in the text. Works when adding the user-content-Prefix: https://try.gitea.io/Bubu/TEST/src/branch/main/FAQ_de.md#user-content-warum-ben%C3%B6tigt-die-app-zugriff-auf-meinen-standort
