### ISSUE TITLE
Fail to pull  LFS objects but can be downloaded via web interface. "batch response: Repository or object not found: [Repo Name].git/objects/batch/"

### ISSUE THREAD

**Issue by mrbbbaixue** [go-gitea/gitea#14966]
- Gitea version (or commit ref): Gitea v1.13.2 built with GNU Make 4.1, go1.15.7 : bindata, sqlite, sqlite_unlock_notify
- Git version: Git Version: 2.30.0, Wire Protocol Version 2 Enabled
- Operating system: Windows Server Datacenter 2019
Run Gitea using commandline.
- Database:
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
- Log gist:
    See the attachment below.

## Description
Our team used to host our Repo on Gitlab CE, then we moved it to gitea with lfs. (change origin and git push --all)
Some LFS objects can't be downloaded via Git Commandline.
But I can download it on the Server website. (see the picture below)

[log-on-my -pc.txt](https://github.com/go-gitea/gitea/files/6129318/log-on-my.-pc.txt)

[log-on-server.txt](https://github.com/go-gitea/gitea/files/6129320/log-on-server.txt)

Sorry for my poor english, just let me know if you need further information.

## Screenshots

![Sourcetree on my PC](https://i.loli.net/2021/03/12/OUkuPptoly3Fvng.png)

![Server log](https://i.loli.net/2021/03/12/yE3Wwv9Mjghi8lx.jpg)

![Web Interface](https://i.loli.net/2021/03/12/QqN2d3WYcmTAwej.jpg)

![App.ini](https://i.loli.net/2021/03/12/d5DHIumLgFEMfX8.jpg)

**Comment by zeripath** [comment]
the url should be /owner/repo/info/lfs/objects/batch

**Comment by zeripath** [comment]
If I had to guess this will be because your lfs configuration on your local clone is incorrect and presumably matches what gitlab ce uses

**Comment by MrBBBaiXue** [comment]
> the url should be /owner/repo/info/lfs/objects/batch

OK, i will try to tweak the configuration and try it again. Thanks!

**Comment by zeripath** [comment]
with the `.git` but it shouldn't matter IIRC

**Comment by MrBBBaiXue** [comment]
OK, solve it!
