### ISSUE TITLE
Trouble understanding cron configuration

### ISSUE THREAD

**Issue by lx30011** [go-gitea/gitea#14967]
I'm setting up the cron feature for automatically updating my mirrored repos, but I don't quite understand how the config works.

```ini
[cron.update_mirrors]
SCHEDULE = @every 10m

[mirror]
DEFAULT_INTERVAL = 8h
```

Which one of these determines how often the repos get mirrored? To me, they seem like they do the same thing.

Thanks!

**Comment by zeripath** [comment]
The `cron.update_mirrors` task runs through the repositories at `SCHEDULE` time to check whether any of the need an update as per each individual repositories `Interval`. When creating a mirror, the repository's mirroring `Interval` will be set to the `DEFAULT_INTERVAL` unless the user creating the repository changes it.

The only one of these values that you should really be adjusting is the DEFAULT_INTERVAL if at all.

Please note:
DO NOT COPY app.example.ini AS YOUR app.ini. 

That is not what that file is for and it contains some documentary sections that are not designed to be placed in live configuration files.

If you do not know what a setting is you should NOT be putting it in your app.ini.
