### ISSUE TITLE
Migrate from another gitea fails with error "the  host resolve to a private ip address"

### ISSUE THREAD

**Issue by lakostin** [go-gitea/gitea#14974]
- Gitea version (or commit ref):
1.14.0+dev-707-g66a148e39
- Git version:
2.26.2
- Operating system:
docker Alpine Linux v3.12
- Database (use `[x]`):
  - [X PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
- Log gist:
modules/task/task.go:51:handle() [E] Run task failed: migrate from 'gitea' is not allowed: the 
host resolve to a private ip address '10.100.1.101'

## Description
Migrating from gitea failed.

migrate from gitea is not allowed: the host resolve to a private ip address '10.100.1.101'

...

**Comment by jolheiser** [comment]
https://docs.gitea.io/en-us/config-cheat-sheet/#migrations-migrations
`ALLOW_LOCALNETWORKS`

**Comment by lakostin** [comment]
> https://docs.gitea.io/en-us/config-cheat-sheet/#migrations-migrations
> `ALLOW_LOCALNETWORKS`

missed that option. thank you!
