### ISSUE TITLE
[Feature Request] Allow dragging images into textareas

### ISSUE THREAD

**Issue by delvh** [go-gitea/gitea#14982]
- Gitea version (or commit ref): 1.14.0+dev-841-g3c7582061

## Description
GitHub allows to drag images from the dragboard directly into any text area instead of dragging it to an upload section below which seems more intuitive to understand and with less code necessary.

## What to implement
Also give the textarea the ability to accept dragged images, and insert them not as an attachment, but as part of the message (meaning basically the same behavior as when "Ctrl + V" was pressed with an image in the clipboard).

GitHub even went so far as to completely integrate the "upload section" of a textarea into the textarea itself, resulting in a smaller webpage being displayed.
This could also be considered (maybe later on), as the only purpose of the upload section, once this gets implemented, is to open the file system dialog, and nothing else.

## Screenshots
Current appearance:
![image](https://user-images.githubusercontent.com/51889757/111022748-03cd7000-83d5-11eb-9110-7e430b8532f7.png)

Appearance when using manual attachments versus `![image]` (at the top):
![image](https://user-images.githubusercontent.com/51889757/111022984-94588000-83d6-11eb-8c37-a16d78ff9c39.png)

**Comment by a1012112796** [comment]
I'm sorry, But in my opinion. ``pasting images into textareas`` has  been implement in gitea. example:

![tmp](https://user-images.githubusercontent.com/25342410/111252234-a2630680-864b-11eb-8a1a-6abc5eec2de0.gif)

Aren't it?

**Comment by delvh** [comment]
Okay, yes, I can verify that it is partially possible using "Ctrl + V":
It will work if the image was directly added to the clipboard.
However, if the image was simply added as a file link, nothing spectacular will happen, except that the link will be copied as plain text (this however is not necessarily a bug as GitHub has the same behavior when encountering a pasted file).
But, what is not possible is dragging images into a text area.
Although it will appear as if it could be dragged, nothing happens once the dragging gets released.
I'll change the title of the issue accordingly.

**Comment by tyroneyeh** [comment]
This #20263 edit should fix the issue
Demo

https://user-images.githubusercontent.com/1255041/176474223-e4ad12fb-3bfb-4811-a0b2-12555965655b.mov
