### ISSUE TITLE
Error on the comparison table

### ISSUE THREAD

**Issue by tuxmaster5000** [go-gitea/gitea#14987]
I found some statement on the table https://docs.gitea.io/en-us/comparison/ for 
BitBucket which must be corrected I think.

- Only the cloud version has in integrated wiki,
- Repository tokens with write rights are available. Also tokens with admin rights, for example for using with the api
- Reject unsigned commits are possible
- The Issue tracker are only working in the cloud version or with an extra jira set up

**Comment by techknowlogick** [comment]
Would you be open to creating a PR to update this page?

**Comment by tuxmaster5000** [comment]
Yes of course, exits an repo for the site?

**Comment by lafriks** [comment]
Yes, here it is: https://github.com/go-gitea/gitea/blob/master/docs/content/doc/features/comparison.en-us.md
