### ISSUE TITLE
missing git-hook configuration in UI

### ISSUE THREAD

**Issue by homburgs** [go-gitea/gitea#14989]
- Gitea version (or commit ref): 1.13.4
- Git version: 2.21.0
- Operating system: Debian Buster
- Database :
  - [ x ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite

## Screenshots
from release 1.11.1
![image](https://user-images.githubusercontent.com/2833290/111042920-f26d7d80-843f-11eb-8798-19cbacd8f9a7.png)

from latest release
![image](https://user-images.githubusercontent.com/2833290/111042948-116c0f80-8440-11eb-9970-1b7bd303c034.png)

**Comment by jolheiser** [comment]
As of 1.13 git hooks default to off.
Checking the blog I notice we have the PR in the security changes, but no note in the blog with the other big changes. I'll PR a notice for the blog.

https://docs.gitea.io/en-us/config-cheat-sheet/#security-security
`DISABLE_GIT_HOOKS`
