### ISSUE TITLE
Error on cloning via SSH: invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by retifrav** [go-gitea/gitea#14988]
- Gitea version: 1.13.4 (*binary downloaded from https://dl.gitea.io/gitea/1.13.4*)
- Git version: 2.25.1
- Operating system: Ubuntu 20.04.2 LTS
  - Gitea is running via [systemd service](https://docs.gitea.io/en-us/linux-service/)

- Database:
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
- Log gist:
```
2021/03/13 17:40:00 ...m.io/xorm/core/db.go:286:afterProcess() [I] [SQL] SELECT user_id, count(*) AS count FROM notification WHERE user_id IN (SELECT user_id FROM notification WHERE updated_unix >= ? AND updated_unix < ?) AND status = ? GROUP BY user_id [1615653588 1615653598 1] - 255.362µs
2021/03/13 17:40:09 ...s/context/context.go:332:func1() [D] Session ID: e7f885888901857b
2021/03/13 17:40:09 ...s/context/context.go:333:func1() [D] CSRF Token: HERE-GOES-TOKEN
2021/03/13 17:40:09 ...m.io/xorm/core/db.go:286:afterProcess() [I] [SQL] SELECT `id`, `lower_name`, `name`, `full_name`, `email`, `keep_email_private`, `email_notifications_preference`, `passwd`, `passwd_hash_algo`, `must_change_password`, `login_type`, `login_source`, `login_name`, `type`, `location`, `website`, `rands`, `salt`, `language`, `description`, `created_unix`, `updated_unix`, `last_login_unix`, `last_repo_visibility`, `max_repo_creation`, `is_active`, `is_admin`, `is_restricted`, `allow_git_hook`, `allow_import_local`, `allow_create_organization`, `prohibit_login`, `avatar`, `avatar_email`, `use_custom_avatar`, `num_followers`, `num_following`, `num_stars`, `num_repos`, `num_teams`, `num_members`, `visibility`, `repo_admin_change_team_access`, `diff_view_style`, `theme`, `keep_activity_private` FROM `user` WHERE `lower_name`=? LIMIT 1 [gitapi] - 121.202µs
2021/03/13 17:40:09 routers/repo/http.go:105:HTTP() [E] GetUserByName: user does not exist [uid: 0, name: gitapi, keyid: 0]
2021/03/13 17:40:09 ...s/context/context.go:139:HTML() [D] Template: status/404
2021/03/13 17:40:10 ...m.io/xorm/core/db.go:286:afterProcess() [I] [SQL] SELECT user_id, count(*) AS count FROM notification WHERE user_id IN (SELECT user_id FROM notification WHERE updated_unix >= ? AND updated_unix < ?) AND status = ? GROUP BY user_id [1615653598 1615653608 1] - 251.954µs
```

- `/etc/gitea/app.ini`:
```
# ...

RUN_USER = git
RUN_MODE = prod

# ...

[server]
LOCAL_ROOT_URL   = http://localhost:8001/git # behind NGINX at /git route
SSH_DOMAIN       = 192.168.1.32
DOMAIN           = 192.168.1.32
HTTP_ADDR        = localhost
HTTP_PORT        = 8001
ROOT_URL         = http://192.168.1.32/git
DISABLE_SSH      = false
SSH_PORT         = 22
LFS_START_SERVER = true
LFS_CONTENT_PATH = /var/lib/gitea/data/lfs
LFS_JWT_SECRET   = HERE-GOES-SECRET
OFFLINE_MODE     = false

# ...

[repository]
ROOT = /home/git/gitea-repositories

# ...
```

## Description

I have a local Gitea instance installed on a server in my local network. No domain, just direct IP address.

When I try to clone a repository to my machine via SSH, I get this error:

```
$ git clone git@192.168.1.32:retif/some.git
Cloning into 'some'...
Gitea: Internal Server Error
invalid character '<' looking for beginning of value
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

My local `~/.ssh/config`:

```
Host 192.168.1.32
HostName 192.168.1.32
IdentityFile ~/.ssh/gitea
```

The contents of `/home/git/.ssh/authorized_keys` on server are set by Gitea (*I added my SSH key via Gitea web-interface*):

```
# gitea public key
command="/usr/local/bin/gitea --config=/etc/gitea/app.ini serv key-4",no-port-forwarding,no-X11-forwarding,no-agent-forwarding,no-pty ssh-rsa HERE-GOES-MY-PUBLIC-SSH==
```

Just in case I also ran these two admin tasks:

- `Update the '.ssh/authorized_keys' file with Gitea SSH keys`
- `Resynchronize pre-receive, update and post-receive hooks of all repositories`

but that did not help, unfortunately.

**Comment by zeripath** [comment]
```
Gitea: Internal Server Error
invalid character '<' looking for beginning of value
```

implies that the hooks or serv cannot contact the running gitea server.

**Comment by zeripath** [comment]
Your LOCAL_ROOT_URL is very likely to be incorrect. You should have left it alone and not put it in.

Remove it or set it to:

```
LOCAL_ROOT_URL   = http://localhost:8001/
```

---

If that doesn't work you can get more information by:

1. try adjusting the authorized_keys line to include ` --debug ` after the `gitea serv`
2. without using git try plainly sshing to git@192.168.1.32

We would also need to know how you are running Gitea. Is it by systemd etc.

**Comment by retifrav** [comment]
> We would also need to know how you are running Gitea. Is it by systemd etc.

It's a systemd service, I mentioned this in the description.

> your LOCAL_ROOT_URL is very likely to be incorrect

You are absolutely right! Somehow I've totally missed that, for local route this `/git` isn't needed, it only makes sense in `ROOT_URL`. Setting `LOCAL_ROOT_URL` to `http://localhost:8001/` (*trailing `/` turned out to be important too*) resolved the issues, I can now successfully clone and push.

Thank you!
