### ISSUE TITLE
Support S3 non-pathstyle (V2)

### ISSUE THREAD

**Issue by OrvilleQ** [go-gitea/gitea#14991]
Currently Gitea's S3 support only support path style which MinIO could handle with. But a lot of S3 provider out there do not support path style like AWS S3.

> Amazon S3 currently supports two request URI styles in all regions: path-style (also known as V1) that includes bucket name in the path of the URI (example: //s3.amazonaws.com/<bucketname>/key), and virtual-hosted style (also known as V2) which uses the bucket name as part of the domain name (example: //<bucketname>.s3.amazonaws.com/key).
> Customers should update their applications to use the virtual-hosted style request format when making S3 API requests before September 30th, 2020 to avoid any service disruptions. Customers using the AWS SDK can upgrade to the most recent version of the SDK to ensure their applications are using the virtual-hosted style request format.

So please support non-pathtyle.

**Comment by OrwillT** [comment]
And also, S3 is a Object Storage standard created by Amazon and been widely used any support by other storage providers. I don't think named gitea's S3 storage support to MINIO, one of countless programs that support this standard, is a good move. It might be confusing, in especially if someone add other network storage solution to gitea like Swift or B2.

**Comment by lunny** [comment]
According `minio` golang sdk, https://docs.min.io/docs/golang-client-quickstart-guide.html

> The MinIO Go Client SDK provides simple APIs to access any Amazon S3 compatible object storage.

And more `Storage` implementation PRs are welcome. See https://github.com/go-gitea/gitea/blob/master/modules/storage/storage.go#L66
