### ISSUE TITLE
Unablte to use svg files als repo/organisation icon.

### ISSUE THREAD

**Issue by tuxmaster5000** [go-gitea/gitea#14990]
- Gitea version (or commit ref):  1.13.4
- Git version:    2.18.4
- Operating system: CentOS7
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ X] Yes (provide example URL)
  - [ ] No

When I try to use an svg file, only the error message:
`UploadAvatar: DecodeConfig: image: unknown format`
will shown.

**Comment by altinnadmin** [comment]
Seems like a duplicate of #8707 ?

**Comment by tuxmaster5000** [comment]
It looks  some think it, but another error code on an different function.
For me it looks like an general svg problem on gitea.
