### ISSUE TITLE
Pushes by registered user but with different email address treated as different author

### ISSUE THREAD

**Issue by Halfwalker** [go-gitea/gitea#15003]
- Gitea version: 1.14.0+dev-692-ga3cc842e1 built with GNU Make 4.3, go1.15.8 : bindata, timetzdata, sqlite, sqlite_unlock_notify
- Git version: 2.17.1
- Operating system: Ubuntu 18.04.5
- gitea running from docker
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes https://try.gitea.io/Halfwalker/multiple-authors
  - [ ] No

If the email address used in _~/.gitconfig_ is different from the address on file for the gitea user, then any pushes are treated as a different author.

#### In gitea
- Define a user **joe** in gitea with email address **joe@example.com**
- Add an ssh key to the profile, and a custom avatar image
- Create a repo _multiple_authors_ in gitea - initialize with README etc.

Verify that the repo shows the initial commit with the new user avatar, and that the user is a link to the actual user in gitea

#### On local machine
- Ensure _~/.gitconfig_ has the user defined with email address **joe@random.org** - _different_ from gitea email
- Clone the repo _multiple_authors_
- Make changes, commit and push

View commit list and see that two different authors are listed, with the newest having no link.  They both have the same username though.  View the Activity for the repo and see that TWO authors are listed.

## Screenshots
![image](https://user-images.githubusercontent.com/1365031/111192315-4c308d80-858f-11eb-8e8e-ffe14d38eba2.png)

![image](https://user-images.githubusercontent.com/1365031/111192490-7e41ef80-858f-11eb-95e3-e95a0da9688d.png)

**Comment by Halfwalker** [comment]
NOTE: Adding the 2nd email address to the gitea user brings them together as one user.  BUT, gitea still sees them as two authors.  This image is from a personal gitea instance

![image](https://user-images.githubusercontent.com/1365031/111193560-a8e07800-8590-11eb-858c-903ca44939d0.png)

**Comment by techknowlogick** [comment]
This is how git works, it is recommended that you use gpg signed commits to prevent spoofing.

Calling @jolheiser who has an example repo of this on github creating commits that show as being done by me.

**Comment by jolheiser** [comment]
I dunno, the commit specifically says it [wasn't me](https://github.com/jolheiser/Test/commit/027e0bdda19d3fe6e526194251fe94d51479c92a). 😉

**Comment by techknowlogick** [comment]
No, because pusher does not always mean author. I apply patches from others onto local repos, but it wouldn't be right to claim those commits as my own, and so the behaviour from Gitea (and Github) correctly attributes the authorship to the author.

**Comment by Halfwalker** [comment]
OK I see that.  In a non-signed environment, what defines the "author" ?  In the case above, it looks like two authors, even though the user is the same, and the email addresses match up.  That is, the gitea user has both email addresses associated, and the commits each used one of those emails.

What's the missing factor that differentiates the two authors ?  Is there any way to collapse them into one entity ?  (sorry, I know it's closed, learning here ...)

**Comment by jolheiser** [comment]
> What's the missing factor that differentiates the two authors ?

The email. Gitea has a concept of users, but git doesn't care. git is only concerned with username/email.

**Comment by Halfwalker** [comment]
OK, so every user/email is considered a unique author no matter what.  Gitea might assign the two _joe/email1_ and _joe/email2_ commits to the same **user** but still sees them as authored by different git-users ...

I think I got it :)  Thanks.

**Comment by a1012112796** [comment]
just wonder if the [``gitmailmap``](https://git-scm.com/docs/gitmailmap) feature in git is usefull or not in gh and gitea ?
