### ISSUE TITLE
error :  failed: Malformed IDX file 

### ISSUE THREAD

**Issue by lds-lds** [go-gitea/gitea#15000]
- Gitea version 1.13.4 
- Git version: 2.7.4 ( built gitea myself)
- Operating system: ubuntu/xenial
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x ] No
- Log gist: ~/gitea/log/gitea.log

## Description
I have this error when I start gitea:
  
```
2021/03/15 09:05:58 ...dexer/stats/queue.go:24:handle() [E] stats queue indexer.Index(409) failed: no such file or directory
2021/03/15 09:05:59 ...dexer/stats/queue.go:24:handle() [E] stats queue indexer.Index(11) failed: Malformed IDX file
```

Here is my systemd launcher

```
[Unit]
Description=Gitea (Git with a cup of tea)
After=syslog.target
After=network.target
#After=mysqld.service
#After=postgresql.service
#After=memcached.service
#After=redis.service

[Service]
# Modify these two values and uncomment them if you have
# repos with lots of files and get an HTTP error 500 because
# of that
###
LimitMEMLOCK=infinity
LimitNOFILE=65535
RestartSec=2s
Type=simple
User=git
Group=git
WorkingDirectory=/home/git/gitea
ExecStart=/home/git/gitea/gitea web
Restart=always
Environment=USER=git HOME=/home/git

[Install]
WantedBy=multi-user.target
```

**Comment by techknowlogick** [comment]
This happens due to Gitea not being stopped cleanly. You can remedy this by removing the queue files, or by switching to a different non-file based queue. Please hop into our chat and we'd be happy to guide you through that process :)

**Comment by zeripath** [comment]
So actually this problem is a different problem.

The error is coming from go-git trying to open the repository and it is reporting a malformed IDX file - I'm not entirely certain why this is the case - but it shouldn't be a problem on 1.14 as we don't use go-git by default there anymore. 

Likely the issue is that the repository doesn't exist but I'm not certain.
