### ISSUE TITLE
Downgrading database issue.

### ISSUE THREAD

**Issue by mage1k99** [go-gitea/gitea#15017]
was updating gitea and this error was thrown

Downgrading database version from '165' to '156' is not supported

```sh
/home/gittea/bins/gitea -p 5050 --config /home/gittea/config/app.ini
2021/03/17 03:27:49 cmd/web.go:108:runWeb() [I] Starting Gitea on PID: 30549
2021/03/17 03:27:49 ...dules/setting/git.go:91:newGit() [I] Git Version: 2.20.1, Wire Protocol Version 2 Enabled
2021/03/17 03:27:49 routers/init.go:132:GlobalInit() [T] AppPath: /home/gittea/bins/gitea
2021/03/17 03:27:49 routers/init.go:133:GlobalInit() [T] AppWorkPath: /home/gittea/bins
2021/03/17 03:27:49 routers/init.go:134:GlobalInit() [T] Custom path: /home/gittea/bins/custom
2021/03/17 03:27:49 routers/init.go:135:GlobalInit() [T] Log path: /home/gittea/gitea/log
2021/03/17 03:27:49 routers/init.go:56:checkRunMode() [I] Run Mode: Production
Downgrading database version from '165' to # '156' is not supported and may result in loss of data integrity.
If you really know what you're doing, execute UPDATE version SET version=156 WHERE id=1;
```

**Comment by jolheiser** [comment]
You had a DB version of `165` and are now trying to run a binary using DB version `156`

We need more information, like what version you were using and what you are trying to use now.

**Comment by mage1k99** [comment]
sure thing @jolheiser

**Comment by mrcodekiddie** [comment]
was trying to upgrade gitea from a older version (mostly 2 months old) to the latest [release](https://github.com/go-gitea/gitea/releases/tag/v1.13.4)

the checksum also matched. @jolheiser



![image](https://user-images.githubusercontent.com/24442168/111387584-f4e80580-86d3-11eb-8774-81ab597dccf6.png)

**Comment by techknowlogick** [comment]
Sounds like you were using a development version, then switched to a lesser version (1.13.4). We don't support downgrades, however you are in luck that we will be releasing 1.14.0-rc1 soon(tm), and so you can move to that instead.
