### ISSUE TITLE
Cannot delete user account created with external authenticator

### ISSUE THREAD

**Issue by kdumontnu** [go-gitea/gitea#15012]
- Gitea version (or commit ref): master, 1.14.0+dev-861-gd2dc182dc
- Operating system: 
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes, create a user with GitHub and try to go to Settings -> Account -> Delete
  - [ ] No
- Log gist:
No additional info found in logs, even using `debug`

## Description
If a user is created with an external authenticator they don't have a password for Gitea. However, a password is required for a user to delete their account. 

## Screenshots

![image](https://user-images.githubusercontent.com/12700993/111353007-7430f700-864a-11eb-91e1-e660899a8c77.png)

**Comment by lafriks** [comment]
Diplicate of #3521
