### ISSUE TITLE
Link to repo broken on Notifications page under Port 3000

### ISSUE THREAD

**Issue by midzer** [go-gitea/gitea#15019]
- Gitea version (or commit ref): 1.13.4
- Git version: 2.30.2
- Operating system: Debian Buster
  
Used package from https://packaging.gitlab.io/gitea
  
Running as user gitea via service
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
- Log gist:

## Description

In our gitea installation, running in a VM under standard port 3000, links to repos on Notfications page are broken: the link is without port.

On the other hand, on the dashboard those repo links are fine.

**Comment by lafriks** [comment]
Check that you have correct `ROOT_URL` set in app.ini file: https://docs.gitea.io/en-us/config-cheat-sheet/#server-server

**Comment by midzer** [comment]
@lafriks Thanks, manually inserting `HTTP_PORT` in `ROOT_URL` fixed the issue.

I am unsure whether you can set `ROOT_URL` on initial config page though, maybe I've missed setting port there.
