### ISSUE TITLE
Delete Tag by name

### ISSUE THREAD

**Issue by renemoc** [go-gitea/gitea#15027]
- Gitea version (or commit ref): 1.13.3
- Git version: 2.25.1
- Operating system: Ubuntu
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X] No
- Log gist:

## Description
I use the Gitea API for automatic release management. Releases are created and deleted via the API. If a new tag was created by a release, it should be removed again if the release was also deleted. However, when trying to delete the tag via the name, the error "Not Found" is returned.

Try to delete the tag with curl

curl -X DELETE "http://192.168.2.177:3000/api/v1/repos/ESG/IRISSYS/tags/test" -H "accept: application/json" -H "authorization: Basic dGVzdFVzZXJGYWxrOnRlc3QxMjM0NTY3OA==" -H "Authorization: token 3c311305732546427419e2419f70031cec310c94"

Response
{"documentation_url":"http://192.168.2.177:3000/api/swagger","errors":null,"message":"Not Found"}

## Screenshots
![grafik](https://user-images.githubusercontent.com/68544627/111641729-b51d3d00-87fd-11eb-8225-e280aaa64952.png)
![grafik](https://user-images.githubusercontent.com/68544627/111641844-d4b46580-87fd-11eb-9f96-ddddafb492ff.png)

**Comment by jolheiser** [comment]
Tag deletion API is only available in 1.14+

Implemented in https://github.com/go-gitea/gitea/pull/13358 and then changed/corrected in https://github.com/go-gitea/gitea/pull/14563.
