### ISSUE TITLE
Gitea dump error "Failed to include data directory: open /data/ssh: permission denied"

### ISSUE THREAD

**Issue by senthilrch** [go-gitea/gitea#15024]
- Gitea version (or commit ref): Gitea version 1.13.2 built with GNU Make 4.3, go1.15.7 : bindata, timetzdata, sqlite, sqlite_unlock_notify
- Git version: git version 2.26.2
- Operating system: Alpine 3.12.3
  
  
  
- Gitea running in Kubernetes cluster
- Gitea installed using helm chart from https://gitea.com/gitea/helm-chart/
- Database (use `[x]`):
  - [X ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
- Log gist: https://gist.github.com/senthilrch/30c2e949e998f909fdeefd5a0bd42455#file-gitea-dump-log

## Description

I am running Gitea in a Kubernetes cluster. Installed it via helm chart from https://gitea.com/gitea/helm-chart/. I am following the document in https://docs.gitea.io/en-us/backup-and-restore/ to take a backup of gitea using "gitea dump" command. Steps I followed:-
- kubectl exec -it <gitea pod name> -- bash
- su git
- cd /tmp
- gitea dump -c /data/gitea/conf/app.ini

Receiving following error (complete log in https://gist.github.com/senthilrch/30c2e949e998f909fdeefd5a0bd42455#file-gitea-dump-log):-
```
...
...
...
2021/03/18 09:18:18 ...m.io/xorm/core/db.go:286:afterProcess() [I] [SQL] SELECT "id", "issue_id", "project_id", "project_board_id" FROM "project_issue" [] - 663.219µs
2021/03/18 09:18:18 ...m.io/xorm/core/db.go:286:afterProcess() [I] [SQL] SELECT "id", "name", "repo_count", "created_unix", "updated_unix" FROM "topic" [] - 603.999µs
2021/03/18 09:18:18 ...m.io/xorm/core/db.go:286:afterProcess() [I] [SQL] SELECT "repo_id", "topic_id" FROM "repo_topic" [] - 390.503µs
2021/03/18 09:18:18 ...m.io/xorm/core/db.go:286:afterProcess() [I] [SQL] SELECT "id", "version" FROM "version" [] - 339.919µs
2021/03/18 09:18:18 cmd/dump.go:290:runDump() [I] Adding custom configuration file from /data/gitea/conf/app.ini
2021/03/18 09:18:18 cmd/dump.go:303:runDump() [I] Custom dir /data/gitea is inside data dir /data, skipped
2021/03/18 09:18:18 cmd/dump.go:310:runDump() [I] Packing data directory.../data
Failed to include data directory: open /data/ssh: permission denied
2021/03/18 09:18:18 cmd/dump.go:171:fatal() [F] Failed to include data directory: open /data/ssh: permission denied
bash-5.0$ ls -l /data/ssh
ls: can't open '/data/ssh': Permission denied
total 0
bash-5.0$ exit
exit
bash-5.0# ls -l /data/ssh
total 32
-rw-------    1 root     root          1381 Mar 16 12:38 ssh_host_dsa_key
-rw-------    1 root     root           602 Mar 16 12:38 ssh_host_dsa_key.pub
-rw-------    1 root     root           505 Mar 16 12:38 ssh_host_ecdsa_key
-rw-------    1 root     root           174 Mar 16 12:38 ssh_host_ecdsa_key.pub
-rw-------    1 root     root           399 Mar 16 12:38 ssh_host_ed25519_key
-rw-------    1 root     root            94 Mar 16 12:38 ssh_host_ed25519_key.pub
-rw-------    1 root     root          1823 Mar 16 12:38 ssh_host_rsa_key
-rw-------    1 root     root           394 Mar 16 12:38 ssh_host_rsa_key.pub
```

**Comment by noerw** [comment]
This is related to the helm-chart configuration, in the future please post there.
Tracking this now at https://github.com/go-gitea/gitea/issues/15024
