### ISSUE TITLE
Gitea 1.13.4 - very high RAM usage during mirroring process

### ISSUE THREAD

**Issue by somera** [go-gitea/gitea#15035]
- Gitea version (or commit ref): 1.13.4
- Git version:
- Operating system: Ubuntu 20.04.2
  
  
  
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite

## Description

When I try to mirror https://github.com/vim/vim than gitea RAM usage is growing to 13GB!!! Reproducible.

## Screenshots

![image](https://user-images.githubusercontent.com/8334250/111709011-2af9c680-8847-11eb-84db-ade1b411b733.png)

With only 8 GB RAM the server is swapping. And at the end Gite uses the allocated RAM.

**Comment by 6543** [comment]
should be a go-git bug ... fixed in gitea >= v1.14.0

**Comment by lunny** [comment]
Since this change is so big, we will not back port the change go-git -> git command line and keep v1.13.4 as it is.

What we can do is to release v1.14 ASAP.

**Comment by somera** [comment]
> Since this change is so big, we will not back port the change of go-git -> git command line and keep v1.13.4 as it is.

It's ok.

> What we can do is to release v1.14 ASAP.

Whas is ASAP? There are ~4 opened tickets for the 1.14 release.

**Comment by lunny** [comment]
> > Since this change is so big, we will not back port the change of go-git -> git command line and keep v1.13.4 as it is.
> 
> It's ok.
> 
> > What we can do is to release v1.14 ASAP.
> 
> Whas is ASAP? There are ~4 opened tickets for the 1.14 release.

In fact, it's only one issue and one pr to this issue and the changelog pr.

**Comment by somera** [comment]
Works very good! Thx!
