### ISSUE TITLE
Create the database if it does not already exist.

### ISSUE THREAD

**Issue by nektro** [go-gitea/gitea#15037]
- Gitea version (or commit ref): `gitea/gitea:latest`
- Git version: `git version 2.20.1`
- Operating system:
  - `Linux 4.19.0-14-amd64 #1 SMP Debian 4.19.171-2 (2021-01-30) x86_64 GNU/Linux`
  - `docker-compose version 1.28.5, build c4eb3a1f`
  - `Docker version 20.10.4, build d3cb89e`
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
- Log gist:

## Description
The following message is produced when using Postgres and the `DB_NAME` does not already exist. It would be nice to be able to have it connect to an already existing db server and create the database it needs if it detects it does not already exist.

> `The database settings are invalid: pq: database "gitea_codemirror" does not exist`

## Screenshots

![image](https://user-images.githubusercontent.com/5464072/111714235-76dc4980-880e-11eb-822d-65fd8a71a835.png)

**Comment by lunny** [comment]
The database username/password may have no permission to create a new database?

**Comment by nektro** [comment]
it does because <https://github.com/plausible/analytics> was able to create the database with no issue.

**Comment by lunny** [comment]
It seems you are out of topic. I mean someone may use a normal database user to manage gitea's databse. And the user may have no permission to create the database. So should we add the feature on installation? Maybe a checkbox and default not checked to let user decide that.
