### ISSUE TITLE
Add WYSIWYG editor on milestone form

### ISSUE THREAD

**Issue by Cypouz** [go-gitea/gitea#15045]
- Gitea version (or commit ref): 1.13.4
- Git version: 2.20.1
- Operating system: Debian 10, using binary package from Gitea, running with systemd.
- Database:
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (https://try.gitea.io/Cypouz/Test/milestone/1335)
  - [ ] No
- Log gist:

## Description

Milestone form doesn't propose a WYSIWYG form like the one proposed by Issue form.

## Screenshots

![Capture d’écran du 2021-03-19 16-42-09](https://user-images.githubusercontent.com/4980075/111806469-4d84f180-88d2-11eb-8e7a-e00f269d5db2.png)

**Comment by lunny** [comment]
Even github didn't do that. Is this necessary?

**Comment by silverwind** [comment]
I think it's fine for this to stay plaintext. ideally with a markdown preview tab, but that should be part of a future editor component, not added manually to this template.

**Comment by silverwind** [comment]
Since https://github.com/go-gitea/gitea/pull/23876 we default to plaintext editor, so this is not planned.

**Comment by wxiaoguang** [comment]
I guess we can keep this open , and introduce the new editor to the milestone page?

At the moment, there is only a simple textarea, no toolbar, no preview

**Comment by silverwind** [comment]
Yes, all places that allow Markdown and generally hold more than 1 line of content could use the new editor.

**Comment by wxiaoguang** [comment]
Agree, markdown editor could help with long text editing, like comment, release description, so milestone description is similar.

Org/user description is usually not that long, so a simple textarea is enough.

**Comment by wxiaoguang** [comment]
> @wxiaoguang v1.23.0 will support markdown editor like a comment?

Yes, I am working on it, there will be a PR

**Comment by wxiaoguang** [comment]
-> Refactor markdown editor and use it for milestone description editor #32688 

(actually, there is not real WYSIWYG editor in Gitea, but markdown editor)
