### ISSUE TITLE
Invalid directory issue with online editor

### ISSUE THREAD

**Issue by KN4CK3R** [go-gitea/gitea#15044]
- Gitea version (or commit ref): current master

## Description
When using the online editor an invalid directory name (because of a file with the same name exists) is detected and reported as an error. On the editor page the invalid directory is now embedded into the path and can't be changed anymore.

## Screenshots
![test](https://user-images.githubusercontent.com/1666336/111799900-ba48bd80-88cb-11eb-8209-76c29114205b.gif)

**Comment by silverwind** [comment]
Huh, I guess no on really thought about putting directories there. If we continue to allow it, we must sanitize input for any `..` segments for security.

**Comment by KN4CK3R** [comment]
It looks like there isn't an error. The info tooltip says to press backspace on the left of the input field. In this case the directory name gets pulled into the name field again.

`..` isn't a problem too:
![grafik](https://user-images.githubusercontent.com/1666336/111818863-f5ed8280-88df-11eb-88ff-54517ee8dbe9.png)

**Comment by zeripath** [comment]
Agh but you have found a bug - we really should not be displaying `/src/data/tmp/local-repo/...`
