### ISSUE TITLE
[UI] SHA links in timeline (sub)events may look better in monospace

### ISSUE THREAD

**Issue by CL-Jeremy** [go-gitea/gitea#15049]
- Gitea version (or commit ref): 1.14.0+dev-864-gdf891dc59
- Git version: -
- Operating system: -
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes https://gitea.com/gitea/go-sdk/pulls/485
  - [ ] No
- Log gist:

## Description

...

Somehow I stumbled on this while reworking on frontend. I compared the relevant snippets from [/repo/issue/view_content/comments.tmpl](https://github.com/go-gitea/gitea/blob/master/templates/repo/issue/view_content/comments.tmpl#L128-L130) and [pull.tmpl](https://github.com/go-gitea/gitea/blob/a5279b74b63248902a6572df5afa3745367e6cb9/templates/repo/issue/view_content/pull.tmpl#L133-L135) and see no real difference whatsoever. Any thoughts?

## Screenshots

![-3 - --gitignore- を更新 - Test - Gitea- Git with a cup of tea 3-19-2021 5-37-29 PM](https://user-images.githubusercontent.com/1714243/111815126-97bea080-88db-11eb-8b7a-006b0468f586.png)

**Comment by CL-Jeremy** [comment]
Bump this.

**Comment by lunny** [comment]
Is this related with the translation string which hasn't contain a link tag?

**Comment by CL-Jeremy** [comment]
> Is this related with the translation string which hasn't contain a link tag?

D'oh, lol. didn't see it's hard-coded.

Then it's just up to the design (not a bug). Whichever the community prefers, the code is inherently correct.
