### ISSUE TITLE
404 Error on view draft release

### ISSUE THREAD

**Issue by kdumontnu** [go-gitea/gitea#15058]
- Gitea version (or commit ref): master
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes: 
  - [ ] No
- Log gist:
From the logs:
```
2021/03/19 22:33:42 ...ules/context/repo.go:824:1() [E] RepoRef invalid repo: branch or tag not exist: 
2021/03/19 22:33:42 ...s/context/context.go:184:HTML() [D] Template: status/404
```
## Description
I had an issue running this locally (Windows, using `make watch`) & confirmed on `try.gitea`. 

To recreate:
- Create new release, add required tag + title
- Save as draft
- Click on Release -> 404 error

If I select "edit" instead it works.

## Screenshots

![image](https://user-images.githubusercontent.com/12700993/111859247-13811300-8905-11eb-8928-85d1f83faa59.png)

**Comment by lunny** [comment]
A draft release will not create tag, the tag will be created once it publish formally. So the link to the tag will return 404.

I think we have two choices. One is to create tag even if draft, another is disable the tag link if it's a draft release.

**Comment by richmahn** [comment]
I'm actually actually actively working with this in my fork of Gitea and noticed this bug too. It looks like Github does make the tag when it is a draft and just means you are working on the release notes and all that, but don't want anyone to see the release yet. If changes are made to the branch it was given at the time of making the draft and the tag, it does NOT include those changes when the draft status is removed. I guess this makes sense. 

We probably should do the same thing that Github does?

**Comment by richmahn** [comment]
It sounds like Pre-Release means it is a Release Candidate and thus make it clear to people as well as apps using the release API endpoint that it is experimental. Draft means you aren't ready for ANYONE or any APP to see it yet, still working on editing the release form and want to work on it again at a later time.

I also noticed on Github you don't have to give it a tag, but once you do, it is set in stone. I see we always require a tag (#7693). I vote we make it behave just like Github.

**Comment by kdumontnu** [comment]
@richmahn can you review the proposed PR #15137 and see if resolves as you're suggesting?

I've been meaning to review it.

**Comment by richmahn** [comment]
@kdomanski Yes, will review it today!
