### ISSUE TITLE
HTTP Port changed?

### ISSUE THREAD

**Issue by ulm0** [go-gitea/gitea#1505]
- Gitea version (or commit ref):
gitea-1.1.0+122-gc764a54
- Git version:
2.11.1
- Operating system:
  - Docker Image: Alpine 
  - Host: HypriotOS
- Database:
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant

## Description
Been using `gitea-1.1.0+75-g6a451a2` for a while and today upgraded to `gitea-1.1.0+122-gc764a54` from the [Gitea site](https://dl.gitea.io/gitea/master/), thing is when i want to reach the web UI, nginx shows a 502 error. Inspecting the `gitea-1.1.0+122-gc764a54` image i see the port 3000 is no longer present
```
bash-4.3# netstat -tulpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      14/sshd
tcp        0      0 127.0.0.11:39612        0.0.0.0:*               LISTEN      -
tcp        0      0 :::22                   :::*                    LISTEN      14/sshd
udp        0      0 127.0.0.11:46767        0.0.0.0:*                           -
```

this is the output in the `gitea-1.1.0+75-g6a451a2` image
```
bash-4.3# netstat -tulpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      14/sshd
tcp        0      0 :::22                   :::*                    LISTEN      14/sshd
tcp        0      0 :::3000                 :::*                    LISTEN      -
```

Is this intended?

One more thing with `gitea-1.1.0+122-gc764a54`, when using the `-h` flag (or any other argument) it panics
```
bash-4.3# /app/gitea/gitea -h
panic: Segmentation fault (core dumped)
```

**Comment by ulm0** [comment]
Apparently there's a problem with Postgres when trying to update, so that keeps the web service from being started. Just rolled back to `gitea-1.1.0+75-g6a451a2`

The DB container logs outputs this
PS: I run gitea on a RPi3
```
LOG:  database system was interrupted; last known up at 2017-04-17 18:38:44 UTC
LOG:  database system was not properly shut down; automatic recovery in progress
LOG:  invalid record length at 0/92F2A38: wanted 24, got 0
LOG:  redo is not required
LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
ERROR:  value "28800000000000" is out of range for type integer
STATEMENT:  UPDATE "mirror" SET "interval" = $1 WHERE "id"=$2
ERROR:  value "28800000000000" is out of range for type integer
STATEMENT:  UPDATE "mirror" SET "interval" = $1 WHERE "id"=$2
ERROR:  value "28800000000000" is out of range for type integer
STATEMENT:  UPDATE "mirror" SET "interval" = $1 WHERE "id"=$2
ERROR:  value "28800000000000" is out of range for type integer
STATEMENT:  UPDATE "mirror" SET "interval" = $1 WHERE "id"=$2
ERROR:  value "28800000000000" is out of range for type integer
STATEMENT:  UPDATE "mirror" SET "interval" = $1 WHERE "id"=$2
```

**Comment by cez81** [comment]
Same problem as #1496. Try altering the interval column type in the mirror table from int to bigint.

**Comment by ulm0** [comment]
@cez81 thank you! that did the trick. just had to type `ALTER TABLE mirror ALTER COLUMN interval SET DATA TYPE bigint;` in postgres and voilà!
