### ISSUE TITLE
REGISTER_MANUAL_CONFIRM not working

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#15053]
- Gitea version (or commit ref): 1.13.2, 1.13.3, 1.13.4 (all binary installs)
- Git version: 2.25.1
- Operating system: ubuntu 20.04.01 (5.8.8-44-generic x86_64)
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No (Did not try since this is a configuration issue which requires admin privilege)

## Description

First time using Gitea, it looks really amazing and was easy to install! Everything seems to work fine.
I am just trying out all the settings and possibilities and got most of my info from here: https://docs.gitea.io/en-us/config-cheat-sheet/

### The issue
With the following settings in `/etc/gitea/app.ini`, it still allows new users to register and be activated immediately.
```
REGISTER_EMAIL_CONFIRM = false
REGISTER_MANUAL_CONFIRM = true
```

I also tried to set `ENABLE_CAPTCHA=true` to see if my changed settings were taking effect at all. The CAPTCHA worked just fine.

For sure I am missing something.

Thanks in advance!

**Comment by noerw** [comment]
Hi, thanks for the report! This is fixed in the upcoming release 1.14 (#14455)
If needed, we can backport it to 1.13.5

**Comment by yevsev** [comment]
Hi noerw,
Thanks for the quick reply!

I can wait for the new release, no need to hurry.

**Comment by 6543** [comment]
this option is a **new** enhancement/feature of v1.14.0
