### ISSUE TITLE
Avatar bug again -> when renaming organization

### ISSUE THREAD

**Issue by somera** [go-gitea/gitea#15050]
- Gitea version (or commit ref): 1.13.4
- Git version:
- Operating system: Ubuntu 20.04.2
  
  
  
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite

## Description

How to reproduce:

- create new organization - test
- rename test to testOld
- create test again -> same avatar like firt test organization
- delete testOld
- the test organization hasn't avatar

**Comment by CL-Jeremy** [comment]
Hmm, can't seem to reproduce on latest master... could be fixed already?

**Comment by somera** [comment]
Yes, is fixed. I can't reproduce it in 1.13.6.
