### ISSUE TITLE
Mirror project: wrong path to images

### ISSUE THREAD

**Issue by somera** [go-gitea/gitea#15075]
- Gitea version (or commit ref): 1.13.4
- Git version:
- Operating system:
  
  
  
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite

## Description

When I migrate https://github.com/cassiomolin/log-aggregation-spring-boot-elastic-stack then I get in browser

![image](https://user-images.githubusercontent.com/8334250/111885267-06c4f380-89c7-11eb-902c-eeb9444cfa4f.png)

The problem is the brocken url path to the image:

![image](https://user-images.githubusercontent.com/8334250/111885290-29efa300-89c7-11eb-842e-2d0e9e6d6cf1.png)

**Comment by zeripath** [comment]
You need to tell us what the file actually links to in the markdown, what it was rendered to, what you expected, what your appurl URL and give us some indication as to how you expect us to be able to guess that this is what it should be.

We could potentially change the base URL for the render but I think we may be screwed at making this work.

**Comment by somera** [comment]
Sorry. My gitea config

```
[server]
SSH_DOMAIN       = nuc-mini-celeron
DOMAIN           = nuc-mini-celeron
HTTP_PORT        = 3000
ROOT_URL         = http://nuc-mini-celeron:3000/

```
The URL on the GitHub page looks so:

`https://github.com/cassiomolin/log-aggregation-spring-boot-elastic-stack/blob/master/misc/img/diagrams/elastic-stack.png`


The link in my local Gitea is

`http://nuc-mini-celeron:3000/misc/img/diagrams/logstash-pipeline.png`

It's not bad, that the image isn't shown. But the basic authentication "sucks".

**Comment by lunny** [comment]
markdown rendering related

**Comment by silverwind** [comment]
Auth popup is a separate issue where the browser hits the HTTPS endpoint meant for the git client which should never happen. If there are steps to reproduce this popup, please open a separate issue with them.

**Comment by zeripath** [comment]
OK so the actual markdown that is being misrendered is:

```
![Elastic Stack][img.elastic-stack]
```

**Comment by zeripath** [comment]
So it's the linked reference paths aren't being handled properly

**Comment by zeripath** [comment]
OK it's actually not that it's with or without preceding slash that makes the difference.

**Comment by somera** [comment]
Should this work in 1.14.0?

**Comment by 6543** [comment]
1.15.0

**Comment by somera** [comment]
> 1.15.0

Thx. Cause I saw

![image](https://user-images.githubusercontent.com/8334250/114316436-e4288500-9b03-11eb-8120-73f71fb1c154.png)

But 1.15.0 is good!
