### ISSUE TITLE
Publisher of release v1.13.5 is 6543 instead of gitea-bot

### ISSUE THREAD

**Issue by ErickStaal** [go-gitea/gitea#15087]
- Gitea version (or commit ref): v1.13.5
- Git version: not relevant
- Operating system: not relevant

Question: given that the release v1.13.5 is released by user 6543: is this a valid release? Since normally releases are published by gitea-bot.

**Comment by zeripath** [comment]
Yes it is - I think we're waiting for the CI to catch up.

**Comment by 6543** [comment]
CI will add assets witch are signed by gitea-bot
