### ISSUE TITLE
Please email new release after they're built and ready to download

### ISSUE THREAD

**Issue by laoshaw** [go-gitea/gitea#15089]
In the past it worked well, now when I saw a new release email, I could not find it other than the source code, so I tell myself let's wait and revisit it later, and each time I then forgot.

can you delay the email until the release is fully built? After all most if not all the users need the binary release.

Thanks!

**Comment by noerw** [comment]
The way to do this in Gitea is to mark the release as draft first, and disable draft status when the release is finalized.
This could also be integrated into CI, for example using the `tea` CLI: `tea release edit --draft=false v1.0.0`
