### ISSUE TITLE
German translation incomplete

### ISSUE THREAD

**Issue by tuxmaster5000** [go-gitea/gitea#15080]
- Gitea version (or commit ref): 1.13.4
- Can you reproduce the bug at https://try.gitea.io:
  - [x ] Yes 
  - [ ] No

## Description
At Crowdin the German translation is marked as 100%, but the contributions graph is always English.

## Screenshots
I have marked the affected section red.:
![demo](https://user-images.githubusercontent.com/837503/111901887-e9ca0800-8a3a-11eb-908b-9b89d65080aa.png)
![orginal](https://user-images.githubusercontent.com/837503/111901889-eb93cb80-8a3a-11eb-845a-5df28306b308.png)

**Comment by 6543** [comment]
locales are not backported ... if you need them you can manualy backport them ...

**Comment by 6543** [comment]
@tuxmaster5000 If you have qestion how to do so, just ask via Discord ... (can ping me there too)
