### ISSUE TITLE
2FA + Github login = Unable to login to existing account

### ISSUE THREAD

**Issue by ulm0** [go-gitea/gitea#1509]
- Gitea version (or commit ref):
1.1.0+115-g54f0293 and later
- Git version:
2.11.1
- Operating System:
Docker image: alpine
Host: HypriotOS
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes
  - [ ] No
  - [ ] Not relevant
## Description
Added Github login for my existing account on a Gitea instance i have, this has 2FA previously configured, when trying to login, it reaches the 2FA UI, once the passcode is given, it shows a 500 page, the only way to login succesfully is to enter the scratch code, which has to be regenerated for future logins.

## Screenshots
![screenshot from 2017-04-18 15-00-22](https://cloud.githubusercontent.com/assets/13160093/25145505/c470bc78-2447-11e7-846c-f5c4fe46572d.png)

**Comment by strk** [comment]
Was your account initially created with a GitHub login or was the GitHub login added to a pre-existing account ? Could you try both cases and report if there's a difference in handling them ?

Basically I'm concerned about the problem #1143 is aiming to fix...

**Comment by ulm0** [comment]
@strk added to a pre-existing account. Sure i can try the other case, doing so as soon as i get home.

**Comment by klud1** [comment]
@strk tested it with the current build 1.0+123-g941281a in the gitea site and it seems to be fixed.

**Comment by strk** [comment]
Tried with both scenarios (first creation and subsequent connection) ?

**Comment by ulm0** [comment]
@strk created an account with Github and added 2FA no problems, though is it normal the Github not to show on external accounts?
![screenshot from 2017-04-19 12-14-41](https://cloud.githubusercontent.com/assets/13160093/25187568/c87d6782-24f9-11e7-90f7-f62127a8d617.png)

**Comment by strk** [comment]
To me it is not, thus #1143, but others think it is. Let's continue the discussion there, if you want to partecipate, while this issue can be closed if you confirm it's fixed.

**Comment by techknowlogick** [comment]
Closing this, please re-open if needed.
