### ISSUE TITLE
Gogs: internal error Failed to get user by key ID(1): needs a pointer to a slice or a map

### ISSUE THREAD

**Issue by gencer** [go-gitea/gitea#151]
I get following error;

`Gogs: internal error
Failed to get user by key ID(1): needs a pointer to a slice or a map
fatal: Could not read from remote repository.
`

..when I try to push newly created repository.

SSH key is added to user's account.

PostgreSQL 9.6 used for data backend.

I use current **master** branch.

serv.log contains:
`
2016/11/11 17:16:19 [...o/gitea/cmd/serve.go:241 runServ()] [F] Failed to get user by key ID(1): needs a pointer to a slice or a map`

**Comment by strk** [comment]
@gencer could you please check if this is fixed now that #153 was merged ?

**Comment by gencer** [comment]
@strk I have successfully managed to push BUT almost. I get lot of hook rejected errors.

```
! [remote rejected] v1.16.10583-alpha -> v1.16.10583-alpha (hook declined)
remote: 2016/11/12 10:27:43 <nil>
remote: error: hook declined to update refs/tags/v4.23.304872-beta
remote: 2016/11/12 10:27:43 <nil>
remote: error: hook declined to update refs/tags/v4.233.304871-beta
remote: 2016/11/12 10:27:43 <nil>
remote: error: hook declined to update refs/tags/v5.0.330151-beta
remote: 2016/11/12 10:27:43 <nil>
remote: error: hook declined to update refs/tags/v6.0.0

...

 ! [remote rejected] master -> master (hook declined)
 ! [remote rejected] v1.16.10583-alpha -> v1.16.10583-alpha (hook declined)
 ! [remote rejected] v1.16.10584-alpha -> v1.16.10584-alpha (hook declined)
 ! [remote rejected] v1.17.10585-alpha -> v1.17.10585-alpha (hook declined)
 ! [remote rejected] v1.18.10586-alpha -> v1.18.10586-alpha (hook declined)
 ! [remote rejected] v1.18.10587-alpha -> v1.18.10587-alpha (hook declined)
 ! [remote rejected] v1.19.10588-alpha -> v1.19.10588-alpha (hook declined)
 ! [remote rejected] v2.20.10589-alpha -> v2.20.10589-alpha (hook declined)
 ! [remote rejected] v2.21.10590-alpha -> v2.21.10590-alpha (hook declined)
 ! [remote rejected] v2.21.10591-alpha -> v2.21.10591-alpha (hook declined)
 ! [remote rejected] v3.109.20389-alpha -> v3.109.20389-alpha (hook declined)
 ! [remote rejected] v4.23.304872-beta -> v4.23.304872-beta (hook declined)
 ! [remote rejected] v4.233.304871-beta -> v4.233.304871-beta (hook declined)
 ! [remote rejected] v5.0.330151-beta -> v5.0.330151-beta (hook declined)
 ! [remote rejected] v6.0.0 -> v6.0.0 (hook declined)


```

Aditional note: repo page shows **500** error.

Gogs has no this issue at all.

**Comment by gencer** [comment]
@strk this message is for notification only. (email)

Also fresh installation of database and repo dir has same issue. hooks are rejected.

`git push -u origin master --tags`

**Comment by gencer** [comment]
@lunny @strk issue has been fixed.  Thanks!

I made a github theme patch. If anyone interested. It is still in development and file size is bigger. It will be smaller in the future.

https://github.com/gencer/gitea-gihubify

**Comment by lunny** [comment]
Great theme! We will support theme feature later. Now I will close this issue. Please feel free if you have any further question.
