### ISSUE TITLE
expand contributors guideline on README

### ISSUE THREAD

**Issue by mohae** [go-gitea/gitea#1510]
This is a result of talking with @strk on #go-nuts and the result of a pull request I saw that had no tests associated with it.

I think the contributors section should be expanded to include:
* use `gofmt`
* use `govet`
* add test cases that show that the code does what it is supposed to do and handles failures properly, where appriopriate.

There may be additional things, like use `golint`, make sure errors are not ignored, etc. 

I just wanted to start the ball rolling by opening this issue so that there can be additional discussion with the goal of reaching a consensus as to what the **Contributors** section should include.

Also, should there be more information to help people new to Go, Github, or contributing to Open Source to make it easier for them to get going with regards to contributing to gitea?

Once a consensus is reached, I'd be happy to make a pull request with changes that are consistent with what has been agreed to.

Regards,

Joel

**Comment by strk** [comment]
For `gofmt` I filed #1366 some time ago, which would make the `Drone` build service fail if `gofmt` wasn't run. Unfortunately it turned out that `gofmt` can behave differently based on the architecture it is run on. 

The `vet` and `lint` steps are already checked by Drone (see `.drone.yml`).

**Comment by mohae** [comment]
For the gofmt, govet, and golint suggestions, it's more so that new contributers know to use those tools, and hopefully encourage them to use them; also so that there's some documentation piece to point back to.

My main concern is tests and being able to consistently have tests be part of the pull request, esp. on bug fixes. The fix should be provable, imo.

**Comment by lunny** [comment]
I also agree with document them what we have implemented in `make`.

**Comment by sapk** [comment]
All theses commands/tests are in drone and it is explained how to run them locally.
https://github.com/go-gitea/gitea/blob/master/CONTRIBUTING.md#testing-redux

Feel free to re-open if need.
