### ISSUE TITLE
How to migrate from sqlite3 to mysql？

### ISSUE THREAD

**Issue by li-xunhuan** [go-gitea/gitea#15101]
- Gitea version (or commit ref):
`1.12.5`
- Git version:
- Operating system:
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
- Log gist:

## Description

I want to upgrade from 1.12.5 to 1.13.x, but after updating the binary file, the CPU occupies 100% and cannot be used. I want to migrate to MySQL, but the database table fields seem to be different

**Comment by somera** [comment]
Manually or jou can use the rest api with own script.

**Comment by somera** [comment]
https://gitlab.com/markuman/gitea-mariadb-migration/

**Comment by somera** [comment]
https://github.com/go-gitea/gitea/issues/12909
