### ISSUE TITLE
[1.13.5] Updating to this version I get an issue with failed execution(permission denied)

### ISSUE THREAD

**Issue by thepra** [go-gitea/gitea#15122]
- Gitea version (or commit ref): 1.13.5
- Git version: 2.25.1
- Operating system: Ubuntu 20.04 LTS
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
- Log gist:

> mar 23 10:48:25 v01d systemd[1612776]: gitea.service: Failed to execute command: Permission denied
> mar 23 10:48:25 v01d systemd[1612776]: gitea.service: Failed at step EXEC spawning /usr/local/bin/gitea: Permission denied
> -- Subject: Process /usr/local/bin/gitea could not be executed

## Description
I'm trying to update from `1.13.4` to `1.13.5` without success(as you can see from the logs above), despite stopping the service, replacing the binary and setting it up as executable and giving the right `user:group`(`gitea:gitea` in my case) the binary have issues at execution that the `1.13.4` doesn't have if I go back to that binary. 
Is there any change that I should apply to the `.service` or `app.ini` file given this new version?
What can I do to further get a more precise error?

**Comment by lunny** [comment]
`chmod +x /usr/local/bin/gitea`

**Comment by thepra** [comment]
Now there is this:

> mar 23 12:16:25 v01d systemd[1623904]: gitea.service: Failed to execute command: Exec format error
> mar 23 12:16:25 v01d systemd[1623904]: gitea.service: Failed at step EXEC spawning /usr/local/bin/gitea: Exec format error

**Comment by lunny** [comment]
You downloaded wrong Gitea binary file for this OS.

**Comment by thepra** [comment]
Holy sh1t, damn arm64 vs amd64 -_-
Thanks.
