### ISSUE TITLE
Wrong user returned in API: GET /repos/{owner}/{repo}/pulls/{index}/reviews/{id}/comments

### ISSUE THREAD

**Issue by sotho** [go-gitea/gitea#15127]
- Gitea version (or commit ref): v1.13.5
- Git version: 2.29.2
- Operating system: Debian/buster
- Release from https://dl.gitea.io/gitea/1.13.5/gitea-1.13.5-linux-amd64
- Also tried self-built v1.13.5
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite

## Description

I use the API to download the comments of a review.
In the returned json all comments have the the same user, although the comments were done by different users (as can be seen in the web frontend).

In modules/convert/pull_review.go ToPullReviewCommentList uses the reviewer, but I think it should use the poster of the comment. This fixes it for me:

    --- a/modules/convert/pull_review.go
    +++ b/modules/convert/pull_review.go
    @@ -94,7 +94,7 @@ func ToPullReviewCommentList(review *models.Review, doer *models.User) ([]*api.P
                    apiComment := &api.PullReviewComment{
                        ID:           comment.ID,
                        Body:         comment.Content,
    -                   Reviewer:     ToUser(review.Reviewer, doer != nil, auth),
    +                   Reviewer:     ToUser(comment.Poster, doer != nil, auth),
                        ReviewID:     review.ID,
                        Created:      comment.CreatedUnix.AsTime(),
                        Updated:      comment.UpdatedUnix.AsTime(),

**Comment by a1012112796** [comment]
@sotho Hello, Thanks for your response, would you please send a pull request to fix it?Thanks.

**Comment by sotho** [comment]
Pull request #15139 opened
