### ISSUE TITLE
Deprecated nodejs packages used

### ISSUE THREAD

**Issue by ecsgh** [go-gitea/gitea#15138]
- Gitea version (or commit ref): 1.13.6
- Git version: 2.26.2
- Operating system: openSUSE Leap 15.2
- Source from gitea
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x ] Yes (provide example URL)
  - [ ] No
- Log gist:
npm WARN deprecated babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
npm WARN deprecated core-js@2.6.12: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade he actual version of core-js@3.
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
npm WARN deprecated core-js@1.2.7: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated

## Description
When i use npm install on source it rise up above deprecated warnings.
So my question. Why use gitea deprecated packages?
Wouldn't it be better to update that? 
Also with regard to security problems?

**Comment by silverwind** [comment]
Most if not all of these are coming from indirect dependencies and it's kind of unavoidable to have some deprecations because the ecosystem is often slow to update. They are not really something to worry about.
