### ISSUE TITLE
Broken links in "Search repository" result

### ISSUE THREAD

**Issue by Beh01der** [go-gitea/gitea#15135]
There's a regression here.
https://github.com/go-gitea/gitea/blob/0fe32826eda43d95c457ace2863f159aa67c40f5/routers/repo/search.go#L43

This causes search result links to be relative to the repository page.
For example, I am getting
`http://git.chronos/andrey/memz-service/andrey/memz-service/src/commit/cc5f663c1a4aa05b60c0060f99869c90bf9a493d/web/dev/tinymce/plugins/example/dialog.html`
instead of
`http://git.chronos/andrey/memz-service/src/commit/cc5f663c1a4aa05b60c0060f99869c90bf9a493d/web/dev/tinymce/plugins/example/dialog.html`

Older version
`	ctx.Data["SourcePath"] = setting.AppSubURL + "/" +
		path.Join(ctx.Repo.Repository.Owner.Name, ctx.Repo.Repository.Name)`
works fine

**Comment by noerw** [comment]
This is a regression of #12999, very similar to #15021 
There may be more such regressions, this should be properly checked

**Comment by wxiaoguang** [comment]
It should have been fixed.
