### ISSUE TITLE
SHA1 in /users/<user>/token response empty; unclear if bug or feature

### ISSUE THREAD

**Issue by ianw** [go-gitea/gitea#15149]
- Gitea version (or commit ref): 1.13.1

## Description

Creating a token works and returns all expected info

```
$ curl -XPOST -H "Content-Type: application/json"  -k -d '{"name":"test"}' -u root:password https://localhost:3000/api/v1/users/root/tokens
{"id":3,"name":"test","sha1":"9fcb1158165773dd010fca5f0cf7174316c3e37d","token_last_eight":"16c3e37d"}
````

However, querying that token does not show the SHA1 again

```
$ curl -k -u root:password https://localhost:3000/api/v1/users/root/tokens
[{"id":3,"name":"test","sha1":"","token_last_eight":"16c3e37d"}, ...
```

It's unclear if the ```sha1``` is deliberately empty as a security measure (or requirement) or if this is a bug?  The API documentation (https://docs.gitea.io/en-us/api-usage/) doesn't specify either way; I'm happy to update when it is determined what it should say. 

This interests me from an automation stand-point; we want a token created in production and I'm wondering if I need to persist it separately after creation, or can look it up using the root password.

**Comment by techknowlogick** [comment]
Tokens aren't stored as plaintext for security reasons (as they are essentially passwords), this is the same behaviour as the Github API.
