### ISSUE TITLE
Problem with health check repository - invalid author/committer line - missing space before email

### ISSUE THREAD

**Issue by somera** [go-gitea/gitea#15146]
- Gitea version (or commit ref): 1.13.6
- Git version:
- Operating system:
  
  
  
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
- Log gist:

## Description

I have an old mirror on my Gitea instance. This mirror was converted to local repo. But after update to Gitea 1.13.6 (???) I get this error messages

```
Failed to health check repository (cache/libmemcached-old): exit status 4 - error in commit aaa58bfca87a6e47d11c4efbc5f0c0637091c5bb: missingNameBeforeEmail: invalid author/committer line - missing space before email
error in commit 237c14119ce4a784a0cbeba4cf674c4af8aa314d: missingNameBeforeEmail: invalid author/committer line - missing space before email
error in commit 3f2aab5c24ea76d37d4c1ef59f2277d1ea2d265e: missingNameBeforeEmail: invalid author/committer line - missing space before email
error in commit c41e93402bbafd6a9393c0589b8b01650049749f: missingNameBeforeEmail: invalid author/committer line - missing space before email
error in commit 4aac578b259d8ce082a9de428636799da1add598: missingNameBeforeEmail: invalid author/committer line - missing space before email
error in commit 5fc74e1abc81b936f089556ba8edd686846173f9: missingNameBeforeEmail: invalid author/committer line - missing space before email
error in commit 7df00ced05e7e4b447009c77704acbe9bda24a98: missingNameBeforeEmail: invalid author/committer line - missing space before email
error in commit c6f7a55231552beca528c83d0999988bceaa70c1: missingNameBeforeEmail: invalid author/committer line - missing space before email
```

## Screenshots

![image](https://user-images.githubusercontent.com/8334250/112385358-d1cede80-8cef-11eb-8a35-b352a2630985.png)

**Comment by lunny** [comment]
What's the log from? It seems it's not Gitea's log.

**Comment by somera** [comment]
I see this in Gitea

**Comment by zeripath** [comment]
`grep -R missingNameBeforeEmail /home/andrew/src/go/gitea`

returns nothing.

Gitea is not doing this.

**Comment by zeripath** [comment]
This is from Git. There is an invalid commit in this repository. Gitea will not have made this commit.

**Comment by somera** [comment]
@zeripath as I wrote I get this since  Gitea 1.13.5/6. It's old mirror.

This issue can stay closed.
