### ISSUE TITLE
`brew install gitea` fails for M1 ARM because download URL does not exist

### ISSUE THREAD

**Issue by websocket98765** [go-gitea/gitea#15145]
Running `brew install gitea` fails because the URL doesn't exist. 

```
❯ brew install gitea
==> Installing gitea from gitea/tap
==> Downloading https://dl.gitea.io/gitea/1.13.6/gitea-1.13.6-darwin-10.12-arm64
#=#=-#  #
curl: (22) The requested URL returned error: 404
Error: Failed to download resource "gitea"
Download failed: https://dl.gitea.io/gitea/1.13.6/gitea-1.13.6-darwin-10.12-arm64
```

If you visit this URL in a browser, you get: "NoSuchKey The specified key does not exist."

Mac: 11.2.2 (M1 ARM)
Homebrew: 3.0.9

**Comment by jolheiser** [comment]
This will begin to work when `1.14.0` lands as a stable release. `1.13.x` does not have arm64 for Darwin.
