### ISSUE TITLE
is it problem?

### ISSUE THREAD

**Issue by igor9292** [go-gitea/gitea#15142]
- Gitea version (or commit ref):1.11.6 and 1.13.5
- Git version: 2.22
- Operating system:
  RHEL, start systemd
- Database (use `[x]`):
  - [x ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
- Log gist:
in log only one select... 

what changed? I upgraded from version 1.11.6 to 1.13.5, and I cannot copy the public repository from the server (git archive). 
Gitea: Unauthorized
Your account is disabled.
fatal: The remote end hung up unexpectedly

on version 1.11.6 - all good

**Comment by techknowlogick** [comment]
Please fill out the standard issue form as that information is being requested so we can help you. Logging which is also requested via the standard issue form is necessary for us to provide any assistance: https://docs.gitea.io/en-us/logging-configuration/#debugging-problems

**Comment by igor9292** [comment]
The problem turned out to be the following: if the key is loaded, and the user is no longer active, you cannot re-upload the key to gitea. Is this a bug or a feature? Maybe deactivate the keys of inactive users?

**Comment by igor9292** [comment]
In general, it would not be bad for the administrator to do something like administering ssh keys so that he can delete, add, modify for each user

**Comment by zeripath** [comment]
There's another issue suggesting this. So I think we can close this.
