### ISSUE TITLE
False conflict in Pull Request if docx file is changed

### ISSUE THREAD

**Issue by tbino5981** [go-gitea/gitea#15152]
- Gitea version (or commit ref): 1.13.6
- Git version: git version 2.31.0.windows.1
- Operating system: Microsoft Windows Server Version 1607
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No

## Description
We tried to merge a Pull-Request in our local Gitea-Instance. This failed with the message about a conflict even though there are no conflicting commits, or even any new commits in the target branch at all. The merge could be resolved with a fast-forward.

I could reproduce the problem with a newly started Gitea-Instance with default configs:
- clone https://github.com/weezlemsneezle/Gitea-Bug-Sample
- change the remote to a newly created repository in Gitea
- `git push -u origin master`
- `git checkout pr`
- `git push -u origin pr`
- create a Pull Request from `pr` into `master`

**Comment by kevinlin18** [comment]
- Gitea version (or commit ref): 1.13.6
- Git version: git version 2.31.0
- Operating system: Windows 10

Another example for this issue
https://try.gitea.io/kevinlin18/binarytest
PR on try.gitea.io works fine, but Gitea on Windows got conflicts

>  This pull request has changes conflicting with the target branch.
> File.docx
> File.ods
> File.odt
> File.pdf

**Comment by noerw** [comment]
This seems to be the same problem as https://github.com/go-gitea/gitea/issues/10913 (there [is a workaround](https://github.com/go-gitea/gitea/issues/10913#issuecomment-726879161)), please continue discussion there if needed
