### ISSUE TITLE
Need workaround to allow migration/import involving gitlab source resolving to 127.0.0.1

### ISSUE THREAD

**Issue by bodhi-one** [go-gitea/gitea#15161]
- Gitea version (or commit ref): 1.13
- Git version:
- Gitlab verison: 13.6.7
- Operating system: OSX Big Sur
- Using docker image gitea/gitea:13.6.7
- Database (use `[x]`):
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite

## Description

Everything installed for gitea with no issues.  I have a python script reading the gitlab projects and I am trying to migrate these into gitea.

Because of how our security is setup I have to tunnel out to our gitlab instance via 127.0.0.1 through a bastion server, etc.

I get an error when I attempt to import each of the projects into gitea:

422 {"message":"migrate from 'gitlab.someserver' is not allowed: the host resolve to a private ip address '127.0.0.1'","url":"http://redactedLocalMachine:3000/api/swagger"} {"repo_name": "redactedprojectName", "description": "", "clone_addr": "http://gitlab.someserver/somegroup/someproject.git", "mirror": true, "private": false, "uid": 2}

I did go into gitea conf/app.ini and update from localhost to the redactedLocalMachine and the error still occurs.

This is when I realize the issue must be related to the source and not the destination.

I did find on an Internet search some go sources for gitea like this:

case "migrate from 'localhost:3000' is not allowed: the host resolve to a private ip address '::1'",
--
  |   |   | "migrate from 'localhost:3000' is not allowed: the host resolve to a private ip address '127.0.0.1'":
  |   |   | assert.EqualValues(t, "local-ip", testCase.repoName)

What I need is a work around to whitelist or ignore this condition as, due to security configuration, there is not an IP that I can get to without going through our network security and resolving to localHost (127.0.0.1) with port forwarding/tunneling.  I need to either have a resolution match of 127.0.0.1 bypassed OR an ability to set a configuration variable to ignore this check OR an ability to white-list/override the default blocking logic.

## Screenshots

N/A

**Comment by jolheiser** [comment]
https://docs.gitea.io/en-us/config-cheat-sheet/#migrations-migrations
`ALLOW_LOCAL_NETWORKS`

**Comment by bodhi-one** [comment]
Terrific, thank you
