### ISSUE TITLE
When selecting a license you can't write in any field

### ISSUE THREAD

**Issue by tomaswarynyca** [go-gitea/gitea#15172]
When you try to create a repository and select a license you cannot continue working in the other fields.
I checked the bug in try.gitea.io v1.15.0+dev-27-gdc56fb7c8

**Comment by noerw** [comment]
Can't reproduce. Which browser are you using? Did you try clearing the browser cache? Are there errors in JS concole?

**Comment by tomaswarynyca** [comment]
Curious it happens to me in Edge, Chrome and Opera, I just installed Opera to test it

**Comment by noerw** [comment]
Indeed, looks like only FF is unaffected.

**Comment by noerw** [comment]
https://github.com/go-gitea/gitea/commit/1a03fa7a4f353eb2f965cdcac39f630c281eca1e is the bad commit.
@silverwind any idea what's causing this?

**Comment by silverwind** [comment]
Hmm I think the only related upgrade there is jQuery which did some changes with focus events which may trigger this bug in Fomantic's form handling. Should try if reverting jQuery to 3.5.1 fixes this.

https://blog.jquery.com/2021/03/02/jquery-3-6-0-released/

**Comment by tomaswarynyca** [comment]
Dependabot made a [PR](https://github.com/fomantic/Fomantic-UI/pull/1905) to upgrade to jquery v3.6 but they haven't approved it yet 
It is set for v2.9 of fomantic, currently they are on v2.8.7.

We should go back to jquery v3.5.1 and the problem should be fixed.

**Comment by silverwind** [comment]
Also one needs to consider our [hard-fork version](https://github.com/go-gitea/gitea/blob/master/web_src/js/vendor/semanticdropdown.js) of semantic's dropdown module which could also be the source of the error. I guess it's time to finally drop it if it's indicated as the source of the error.

**Comment by silverwind** [comment]
So it seems both downgrading jQuery and removing the hard-fork seem to resolve the issue. I'll go with the latter as it also removes 150kB frontend and it's something I've been meaning to do for a while now. It does mean dropdowns will be slightly less accessible but I think such changes are better done upstream anyways.

**Comment by lubber-de** [comment]
I tried with a simple form containing a dropdown using jquery 3.6.0 and latest fomantic 2.8.8-beta
I cannor reproduce what you are describing. Could you please adjust my jsfiddle (if possible) to be able to reproduce the situation in gitea? I am otherwise about to merge the jquery 3.6.0 dependency into fomantic

**Comment by silverwind** [comment]
I think there is indeed no issue with jQuery 3.6.0 with the latest `dropdown.js` version, the bug we were seeing showed only with that older dropdown.js version we had loaded in combination with jQuery 3.6.0.
