### ISSUE TITLE
Webhook table is not update correctly

### ISSUE THREAD

**Issue by loynoir** [go-gitea/gitea#15189]
- Gitea version (or commit ref): docker gitea latest
- Git version:
- Operating system: 
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
- Log gist:

### Reproduce
1. Login
2. Jump to `<repo>/user/settings/applications`.
3. Edit existing "OAuth2 Applications"
4. Change `Redirect URI` from port A to port B.
5. Save
6. Refresh webpage.

### Expect:
Webhook redirect to port B without restart docker.

### Current:
1. Docker logging complain on port A, "connect: connection refused"
2. Besides, webhook which worked at port A, not working at port B.

### Slightly debug:
database "gitea/gitea.db" 
table "webhook"
field "url" is still port A.

**Comment by techknowlogick** [comment]
Oauth settings don't change webhook settings, if you want to update webhooks you'll need to do that in webhook settings.
