### ISSUE TITLE
authentication not available on login

### ISSUE THREAD

**Issue by dvgoyeneche** [go-gitea/gitea#15206]
I have configured ldap bindDN authentication but in the login page I cant see the select option
![image](https://user-images.githubusercontent.com/49909762/113009215-0b806900-9178-11eb-8fcb-8fa805dcb135.png)

![image](https://user-images.githubusercontent.com/49909762/113009290-1a671b80-9178-11eb-8c2e-bcc77b9f31fc.png)

**Comment by noerw** [comment]
Check the logs for LDAP related errors.
I suspect that the server may not be reachable, and the auth method thus gets disabled.

**Comment by lafriks** [comment]
There won't be special select option just enter ldap username and password in appropriate fields
