### ISSUE TITLE
REQUIRE_SIGNIN_VIEW when true migrate fails with  403

### ISSUE THREAD

**Issue by basaran** [go-gitea/gitea#15207]
- Gitea version (or commit ref):
Gitea version 1.13.6 built with GNU Make 4.1, go1.15.10 : bindata, sqlite, sqlite_unlock_notify

- Database (use `[x]`):
  - [X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X] No
- Log gist:

2021/03/30 12:31:54 Started GET / for 127.0.0.1
2021/03/30 12:31:54 Completed GET / 200 OK in 180.201023ms
2021/03/30 12:31:58 Started GET /api/v1/version for 127.0.0.1
2021/03/30 12:31:58 Completed GET /api/v1/version 403 Forbidden in 966.575µs
2021/03/30 12:32:03 Started GET /api/v1/version for 127.0.0.1
2021/03/30 12:32:03 Completed GET /api/v1/version 403 Forbidden in 820.394µs

## Description

When REQUIRE_SIGNIN_VIEW is enabled to `true`, migration from another gitea source fails with 403 forbidden.

## Screenshots

![image](https://user-images.githubusercontent.com/30809170/113023862-19bc8e00-9154-11eb-9523-3f558f2e7164.png)

![image](https://user-images.githubusercontent.com/30809170/113023986-3b1d7a00-9154-11eb-95b0-1b7a780126aa.png)

**Comment by noerw** [comment]
I can't reproduce, the problem must be elsewhere.
The log you provided is unrelated.

**Comment by basaran** [comment]
REQUIRE_SIGNIN_VIEW was the only parameter I changed to get the gitea to gitea migration working. I tested on different repositories too. When it is set to `true`, it will return 403. But I will setup two new test instances this weekend and report back.

**Comment by lunny** [comment]
Which side did you changed the config? Send side Gitea or receive side Gitea?

**Comment by basaran** [comment]
REQUIRE_SIGNIN_VIEW was set to true on the gitea where repository was cloned from (acting as source server). I haven't had the time last week, but I will do two clean installs this weekend to replicate the issue.

**Comment by zeripath** [comment]
Were you able to reproduce?

**Comment by basaran** [comment]
Hi, I completely forgot about this. Sorry about that. I will setup the test vms this weekend, and let you know.
