### ISSUE TITLE
attachments not found but it exists

### ISSUE THREAD

**Issue by nkbai** [go-gitea/gitea#15202]
- Gitea version (or commit ref):
Gitea version 1.14.0+dev-876-gc0c052bdb built with GNU Make 4.3, go1.16.2 : bindata, timetzdata, sqlite, sqlite_unlock_notify
- Git version:
- git version 2.30.2
- Operating system:
Linux a71339d37cce 3.16.0-6-amd64 #1 SMP Debian 3.16.56-1+deb8u1 (2018-05-08) x86_64 Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x ] No

running gitea use docker:
```
docker run -d --name=cy_gitea -p 3001:22 -p 3000:3000 -v /var/lib/gitea:/data gitea/gitea:latest
```

```
root@gitea:/var/lib/gitea/gitea/attachments/0/f# ls
0fb968ae-c40c-4478-b6d0-d71281513f4b
root@gitea:/var/lib/gitea/gitea/attachments/0/f# pwd
/var/lib/gitea/gitea/attachments/0/f
root@gitea:/var/lib/gitea/gitea/attachments/0/f#
```

but  when I visit `http://xxxx/attachments/0fb968ae-c40c-4478-b6d0-d71281513f4b` , gitea reports not found.

```
root@gitea:/var/lib/gitea/gitea/attachments/d/1# ls
d1abdd19-3083-44c6-a862-df22db86ee4a
root@gitea:/var/lib/gitea/gitea/attachments/d/1# pwd
/var/lib/gitea/gitea/attachments/d/1
```

when I visit `http://xxxx/attachments/d1abdd19-3083-44c6-a862-df22db86ee4a`,gitea works.

**Comment by lunny** [comment]
Please confirm you have the permission to visit `0fb968ae-c40c-4478-b6d0-d71281513f4b`.

**Comment by nkbai** [comment]
```
root@gitea:/var/lib/gitea/gitea/attachments/0/f# ls -lh
total 100K
-rw-r--r-- 1 gitea gitea 97K Mar 29 16:20 0fb968ae-c40c-4478-b6d0-d71281513f4b
root@gitea:/var/lib/gitea/gitea/attachments/0/f# cd ..
root@gitea:/var/lib/gitea/gitea/attachments/0# ls -l
drwxr-xr-x 2 gitea gitea 4096 Mar 29 19:47 f
root@gitea:/var/lib/gitea/gitea/attachments/0# cd ..
root@gitea:/var/lib/gitea/gitea/attachments# ls -l
total 68
drwxr-xr-x 10 gitea gitea 4096 Mar 29 19:23 0
drwxr-xr-x  7 gitea gitea 4096 Mar 29 21:09 d




root@gitea:/var/lib/gitea/gitea/attachments/d/1# ls -l
total 64
-rw-r--r-- 1 gitea gitea 64342 Mar  3 21:28 d1abdd19-3083-44c6-a862-df22db86ee4a
root@gitea:/var/lib/gitea/gitea/attachments/d/1# cd ../
root@gitea:/var/lib/gitea/gitea/attachments/d# ls -l
total 20
drwxr-xr-x 2 gitea gitea 4096 Mar  3 21:28 1
root@gitea:/var/lib/gitea/gitea/attachments/d# cd ../
root@gitea:/var/lib/gitea/gitea/attachments# ls -l
total 68
drwxr-xr-x 10 gitea gitea 4096 Mar 29 19:23 0
drwxr-xr-x  7 gitea gitea 4096 Mar 29 21:09 d
```

these two files have the same permissions. 

@lunny lunny

**Comment by lunny** [comment]
@nkbai I mean the permissions of the Gitea user you are login. But not file system.

**Comment by nkbai** [comment]
these two files have the same permission, but the first cannot found and the second is ok.

I'm running gitea use docker.


```
bash-5.1# ps ax
PID   USER     TIME  COMMAND
    1 root      0:00 /bin/s6-svscan /etc/s6
   16 root      0:00 s6-supervise gitea
   17 root      0:00 s6-supervise openssh
   18 git       3:57 /app/gitea/gitea web
   20 root      0:00 sshd: /usr/sbin/sshd -D -e [listener] 0 of 10-100 startups
 3082 root      0:00 bash
 3104 root      0:00 ps ax
bash-5.1# ls -l
total 100
-rw-r--r--    1 git      git          98615 Mar 30 02:20 0fb968ae-c40c-4478-b6d0-d71281513f4b
```

**Comment by lunny** [comment]
Both two attachments belong to the same repository? You login user have read permission to those repositories?

**Comment by nkbai** [comment]
yes, one is ok and another is not available.

**Comment by wxiaoguang** [comment]
Feel free to reopen with more details.

It seems a underlying problem (eg: file system, permission, etc)

About `another is not available`: how about remove the `not available` one and copy the `ok` one to the `not available` one?
