### ISSUE TITLE
[Proposal] Create Postgres schema on initial config if set

### ISSUE THREAD

**Issue by kasbah** [go-gitea/gitea#15216]
Currently initial config on a fresh database fails when you set a schema. 

![image](https://user-images.githubusercontent.com/206854/113067075-992d7a00-91b3-11eb-8391-a8673183e872.png)

It's especially problematic if you use docker and set `GITEA__DATABASE__SCHEMA` and `SECRET_KEY` as it will skip this setup page and have an error on console

```
ORM engine initialization attempt #6/10 failed. Error: migrate: sync: pq: schema "gitea" does not exist
```

We should make initial config create the schema if it doesn't exist.

**Comment by lunny** [comment]
You should create the database and schema before the installation page.

**Comment by lunny** [comment]
For a security consideration, the Gitea database user should have lower permission of that database. I don't think it's a good idea.

**Comment by kasbah** [comment]
Yeah, I think you are right. Just seemed inconvenient when I ran into it.
