### ISSUE TITLE
Merge did not really merge in git tree line

### ISSUE THREAD

**Issue by FFFFDDDD25** [go-gitea/gitea#15220]
- Gitea version (or commit ref): 1.13.0+dev-500-g3270e7a44
- Git version: not sure what version is used in remote server

I'm using Gitea web button to operate, when I merge DEV into STAGE, the STAGE code did changed, but in the git tree line the two branches didn't merge into one single node, instead, the STAGE had grow a new node, is this a bug? thanks

**Comment by lunny** [comment]
That's a feature of Git not a bug.

**Comment by a1012112796** [comment]
Gitea has many merge stlyes like github. Only ``Merge pull request`` will merge head branch (refs/pull/**/head) into base branch with a new merge commit.

Can see https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-request-merges in github.

Thanks.
