### ISSUE TITLE
Footer broken on org dashboard

### ISSUE THREAD

**Issue by tomaswarynyca** [go-gitea/gitea#15224]
- Git version: **1.14.0+rc2**
- Operating system: **Linux**
- Database: **SQLite**
- Can you reproduce the bug at https://try.gitea.io: **No**

When trying to view the organization's dashboard the footer breaks the web site.

![image](https://user-images.githubusercontent.com/41587659/113154608-8f853000-920e-11eb-8645-217689fcdb6b.png)

**Comment by jpraet** [comment]
Has already been fixed in  #15174

**Comment by tomaswarynyca** [comment]
I think it's about time to release v1.14.0-rc3

**Comment by tomaswarynyca** [comment]
> Has already been fixed in #15174

Ohh great! I think it's time to release v1.14.0-rc3
