### ISSUE TITLE
[Proposal] Ability to create automatic releases by closing a milestone/ project

### ISSUE THREAD

**Issue by delvh** [go-gitea/gitea#15222]
- Gitea version (or commit ref): 1.15.0+dev-44-g1b762fc5d

## Description
If you could opt-in to automatically create a release by closing a milestone/ project, lots of time could be saved creating a release.
In many projects, one project/ milestone equals one release, so there this feature could shine.
By using some automated parsing, you can even classify issues, i.e. as `bug`, `feature`, `enhancement`, `breaking`, `docs`, `miscellaneous` or `security`.
This parsing (performed only when the milestone/ project has been closed and automated releases has been enabled) can be done either by looking at the labels (look if the issue/ PR has one of these labels - order by priority, i.e. `security` →  `breaking` → `bug` → `feature` →  `enhancement` → `docs` → `miscellaneous`), or if the issue title displays the type (i.e. ~~[~~`Proposal`~~]~~) in this case here.
After parsing, all merged PRs attributed to that milestone/ project should be collected into one release description text (for now can be a hardcoded format), resulting in something like:
```md
- %PR_TITLE (%PR_ID)
```
```md
## Security
- Change default password hashing algorithm (#ABC)

## Bugs
- Fixed Bug #ABD (#BCD)
- Fixed Bug #ADE (#BDE)

## Features
- Add option to create automatic releases (#CDE)
- Remove option to do nothing (#CEF)

## Docs
- Add documentation for /api/test (#DEF)

### Contributors
…
```
The title of the release could for now simply be the milestone/ project title.
The release should be created as draft to allow for manual confirmation.

## Open Question
Should this be a per milestone/ project setting, or a repo wide setting?

## Later on (once the basic functionality has been implemented)
- Add ability to display a custom format for the output of any issue/ pull request (combi) shown in the generated release (so that something like
`[%ISSUE_TYPE] (%PR_ID, from issue %ISSUE_ID) %PR_TITLE - %ISSUE_TITLE` could be used as release text, leading to i.e.
`[Feature] (#XYZ, from issue #ABC) Add example option - Ability to add example option` displayed in the release page) 
- How to handle creating the release note if an issue in linked to more than one merged pull request? (My idea: Use the PR that actually closed the issue)
- Customize automated parsing process
- Customize generated release description
- Customize generated release title

**Comment by a1012112796** [comment]
I think it's better to do it by a ci bot.

**Comment by techknowlogick** [comment]
Yes, better from CI.
