### ISSUE TITLE
LFS file no commits found

### ISSUE THREAD

**Issue by rwalravens** [go-gitea/gitea#15236]
- Gitea version (or commit ref): 1.14.0+rc2
- Git version: 2.30.2
- Operating system: using docker
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No (**LFS not supported**)

## Description
Repo settings > LFS > "Find Commits" (of any listed file)

For the same repository:
* in 1.13.2 the commit is found
* in 1.14.0+rc2 no commit is found

URI: {repo}/settings/lfs/find

## Screenshots

1.13.2
![image](https://user-images.githubusercontent.com/36928442/113284271-b1071a00-92e9-11eb-9367-61f7b50f6491.png)

1.14.0+rc2
![image](https://user-images.githubusercontent.com/36928442/113284465-f62b4c00-92e9-11eb-9579-f2eef1e0f6cd.png)

**Comment by lunny** [comment]
Related with `ParseTreeLine`
