### ISSUE TITLE
Mirroring cron operations - spread out timings - Improvement

### ISSUE THREAD

**Issue by bodhi-one** [go-gitea/gitea#15239]
Current Situation:

Currently in the gitea configuration section for cron mirroring there is a setting for schedule (@every 3hr, etc).
This tends to create clumps of significant CPU utilization around that timing.

Proposed Change:

Please consider adding the ability to specify a mirror task separation/idle time (likely expressed as seconds) to be used between checking each repository for mirroring updates.
This would allow gitea to yield CPU to other processes.

There may be another way to space-out/randomize gitea mirror actions that is better but achieves similar goals.

**Comment by techknowlogick** [comment]
FWIW you can control the number of workers for specific queues if there are too many workers working on a specific type of task at certain times.

**Comment by bodhi-one** [comment]
Thank you, minimizing max workers to 2 did the trick.
