### ISSUE TITLE
Issue render failed.

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#1523]
visit https://try.gitea.io/trygitea123/BigRed/issues/1

**Comment by strk** [comment]
Anything in the server logs ?

**Comment by cez81** [comment]
Looks ok when signed in. Same as #1539?

**Comment by lunny** [comment]
@cez81 seems a duplicted issue.

**Comment by geek1O11** [comment]
Bad idea

**Comment by bkcsoft** [comment]
Closing as duplicate of #1539
