### ISSUE TITLE
Docker image should have environment variables to configure basic startup settings like database password and default admin password

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#1525]
- Gitea version (or commit ref): as in "latest" docker image from 2017-04-20
- Git version: as in "latest" docker image from 2017-04-20
- Operating system: as in "latest" docker image from 2017-04-20
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

The docker image should have environment variables to configure basic startup settings like database password and default admin password instead of just a graphical wizard. While a wizard is completely fine for a manual install, docker containers are usually launched automatically and most of the popular well-written ones can be booted in a working state immediately without much manual intervention.

For a comparable startup script, check the gitlab omnibus container: apart from arbitrary config values (which wouldn't be necessarily needed for gitea but nice to have), it allows specifying the admin login password and the database access password so that on first launch, it starts immediately ready to use without any additional configuration needed. The postgresql container you recommend for use in the gitea docker tutorial is also a good example, it allows setting a password, a user and even automatically creating a database by name on first launch purely with environment variables specified on container creation.

Adding this would allow a more automated setup of gitea instances with docker.

**Comment by bkcsoft** [comment]
The only thing we'd need is a startup-script that populates `custom/conf.ini` based on environment variables. So this is `kind/deployment`, not `kind/feature` 🙂

**Comment by techknowlogick** [comment]
These variables now exist, check out gitea's docker docs for instructions.
