### ISSUE TITLE
Compiling  Gitea with gccgo

### ISSUE THREAD

**Issue by Maniues** [go-gitea/gitea#15254]
Is it possible to compile gitea with gccgo?
I was building gitea with gccgo, no gc and it asked to install gc. Is it possible to compile Gitea with gccgo? If so, how can I do it?

**Comment by lunny** [comment]
We haven't support that officially.

**Comment by Maniues** [comment]
> We haven't support that officially.

How to do it unofficially?

**Comment by techknowlogick** [comment]
leave out the sqlite build tags, and then compile it with gccgo how you would another go program.
