### ISSUE TITLE
[E] stats queue indexer.Index(145) failed: object does not exist [id: refs/heads/master, rel_path: ]

### ISSUE THREAD

**Issue by xoxys** [go-gitea/gitea#15257]
- Gitea version (or commit ref): 1.13.6
- Git version: 2.24.4
- Operating system: CentOS 7

- Database (use `[x]`):
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X] No
- Log gist:
```
2021/04/02 17:22:33 ...eful/manager_unix.go:127:handleSignals() [W] PID 9116. Received SIGTERM. Shutting down...
2021/04/02 17:22:33 .../graceful/manager.go:217:doHammerTime() [W] Setting Hammer condition
2021/04/02 17:22:34 .../graceful/manager.go:231:doTerminate() [W] Terminating
2021/04/02 17:22:35 ...rm/session_schema.go:360:Sync2() [W] Table user Column max_repo_creation db default is '-1', struct default is -1
2021/04/02 17:22:36 ...dexer/stats/queue.go:24:handle() [E] stats queue indexer.Index(145) failed: object does not exist [id: refs/heads/master, rel_path: ]
```

## Description

I got the mentioned indexer error in the gitea log.

**Comment by milanaleksic** [comment]
I had the same issue I think. This happened because this particular repository didn't have `master` branch. After I have pushed a master branch and restarted gitea it didn't throw this error any more
