### ISSUE TITLE
How can I use a pfx certificate in gitea?

### ISSUE THREAD

**Issue by dvgoyeneche** [go-gitea/gitea#15265]
How can I get the key and pem certificate from a pfx certificate for using it in gitea?

**Comment by techknowlogick** [comment]
I recommend using openssl for this: https://stackoverflow.com/questions/15413646/converting-pfx-to-pem-using-openssl

**Comment by dvgoyeneche** [comment]
after configured it using a non self signate certificate, I get this error on git console (pull action)

SSL certificate problem: unable to get local issuer certificate
