### ISSUE TITLE
PDF preview shows the wrong version of the document

### ISSUE THREAD

**Issue by christiankral** [go-gitea/gitea#15269]
- Gitea version (or commit ref): 1.15.0+dev-21-gf4e677edb @ [gitea.com](https://gitea.com)
- Git version: 2.31.0
- Operating system: Linux Manjaro (5.11.6-1-MANJARO)

## Description

I committed different versions of a LyX and PDF file on the public repository [gitea.com/christiankral/Ipe_Anleitung](https://gitea.com/christiankral/Ipe_Anleitung)

If I click on the PDF document `Ipe_Anleitung.pdf`

![image](https://user-images.githubusercontent.com/4184218/113489795-7dcdb200-94c6-11eb-8dd2-c13e24276335.png)

the URL becomes https://gitea.com/christiankral/Ipe_Anleitung/src/branch/master/Ipe_Anleitung.pdf and old document version is previewed, which consists of only two pages:

![image](https://user-images.githubusercontent.com/4184218/113489835-cc7b4c00-94c6-11eb-9ad1-2984432dac1b.png)

However, the PDF file in the repository holds the actual version of the document, consisting of five pages. One can double check this by cloning the repository by `git clone https://gitea.com/christiankral/Ipe_Anleitung.git`.

Additionally, when changing the URL to https://gitea.com/christiankral/Ipe_Anleitung/raw/branch/master/Ipe_Anleitung.pdf (change `src` to `raw`), the previewed document is the correct version, consisting of five pages.

**Note.** Possibly this issue is related with #10913

**Comment by lunny** [comment]
It should be a browser cache problem. Both urls returned 5 pages from me.

**Comment by christiankral** [comment]
Good point. After clearing the cache, it loads five pages. I guess this issue can be closed then.
