### ISSUE TITLE
Allow GPG key for noreply email address

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#15263]
if you generate a a gpg key for your noreplay email address you can not add, it will fail with `This GPG key is not usable with any email address associated with your account.`

proposal: allow noreplay add as valid gpg email

source: https://codeberg.org/Codeberg/Community/issues/335#issuecomment-184108
gitea version: v1.13.6

**Comment by zeripath** [comment]
Can you give me an example on try.gitea.io?

If you add the noreply address to the gpg key does that validate it?

Would #14054 fix the issue?

**Comment by Rijul-A** [comment]
I can confirm that #14054 fixes this issue.
