### ISSUE TITLE
[Docs] Config Options Should Add Versions

### ISSUE THREAD

**Issue by kdumontnu** [go-gitea/gitea#15279]
https://docs.gitea.io/en-us/config-cheat-sheet/

We get a lot of questions in discord about debugging different config options only to find out users are using an unsupported version. They should not be expected to read all release notes/PRs to know if a setting is supported.

Each config option (and maybe other settings in the docs) should include the supported version. I'm not sure if there's an automated way of doing this with Hugo, but simply adding `1.14.0+` etc tag for each setting would be a good start.

Maintainers should also reject documentation PRs without version information.

**Comment by kdumontnu** [comment]
Looks like some sites will retain docs for each version (ex. [demo](https://docs.camunda.org/manual/7.4/introduction/), [Vue](https://vuejs.org/v2/guide/single-file-components.html#Example-Sandbox))

Seems nice if someone wants to take that on, but will increase the effort required for releasing new versions.

**Comment by lunny** [comment]
Yes, so we can publish all docs according the release branches or master branch. Since docs will not distribute with binary. It will only affect the docs.gitea.io site.

**Comment by kdumontnu** [comment]
Duplicate (or subset) of https://github.com/go-gitea/gitea/issues/5588
