### ISSUE TITLE
DISABLE_MIGRATIONS

### ISSUE THREAD

**Issue by dvgoyeneche** [go-gitea/gitea#15288]
Altough I have configured DISABLE_MIGRATIONS=true in the app.ini file, users still can see the link for create a new migration

![image](https://user-images.githubusercontent.com/49909762/113553966-d604d100-95f8-11eb-8ca4-c3fce091b149.png)

**Comment by a1012112796** [comment]
@dvgoyeneche which version?

**Comment by dvgoyeneche** [comment]
Last version

El 5 abr. 2021 17:12, a1012112796 ***@***.***> escribió:

⚠ This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.

@dvgoyeneche<https://github.com/dvgoyeneche> which version?

**Comment by dvgoyeneche** [comment]
Solved in prerelease 1.14
