### ISSUE TITLE
Markdown preview blocked by REQUIRE_SIGNIN_VIEW

### ISSUE THREAD

**Issue by protozis** [go-gitea/gitea#15284]
- Gitea version (or commit ref): 1.13.6
- Git version: 2.31.1
- Operating system: Archlinux
- Installed with Pacman package: gitea
- Run on systemd
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
- Log gist: https://gist.github.com/vegaServer/c555fd0cc1a45701f03479b71006dacb

## Description

...
Cannot preview markdown documents even I was login at that moment.
POST response:  `message | "Only signed in user is allowed to call APIs."`
The preview works fine if I set `REQUIRE_SIGNIN_VIEW` to false.

## Screenshots
![Screenshot_2021-04-05 LBM](https://user-images.githubusercontent.com/67610433/113529243-8cff4d80-95f5-11eb-8c17-fe55a8c9f4af.png)

**Comment by lunny** [comment]
We should not use APIs from the UI because they should have different authentication methods.

**Comment by zeripath** [comment]
Then you're going to cause us to have to rewrite and recopy whole sections of code. 

We use the API in multiple places and I would argue we should use more API and do less rendering in the main template sections.

Instead we should just make this work again - it previously worked.

**Comment by lunny** [comment]
I mean we should have two different APIs routers. They could have different router paths and authentication's method but the handler functions could be shared but no copy.

i.e. `/api/v1` will only support tokens authentication and `/api/ui` will support sessions but not tokens.

**Comment by richmahn** [comment]
Very valid point and good idea. We always know the UI uses the latest version of the API, as it is our "own" app. Yet apps that use the API, if there were more than one version, would need to use a version number and different authentication.

**Comment by lunny** [comment]
@vegaServer But I cannot reproduce this.

**Comment by vegaServer** [comment]
@lunny I will see what I can do about this...

**Comment by 6543** [comment]
cant reproduce ... any status update?

**Comment by vegaServer** [comment]
Sorry for the late update...
I have tried a fresh new installation and it works just fine, I guess it was just me messed up some steps in the building and I should go back and review my configuration. Sorry for boarding you guys, very appreciate for all the help!!
