### ISSUE TITLE
[UI] Bug on Fille List / View if commit message is to long

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#15283]
Gitea Version: 1.15.0+dev-67-g48ef04ee5

![2021-04-05 02-22-42](https://user-images.githubusercontent.com/24977596/113525692-ab922400-95b6-11eb-9621-828dd37e1b36.png)

**Comment by CL-Jeremy** [comment]
Will be solved by merging #15005 (see https://github.com/go-gitea/gitea/pull/15005#issuecomment-800207086).

**Comment by wxiaoguang** [comment]
It has been resolved by a recent PR separately.

![image](https://user-images.githubusercontent.com/2114189/167238032-aebaf23a-ae6d-4ab7-9199-34e601a5c482.png)
