### ISSUE TITLE
Heatmap loaded for user "undefined" on Dashboard page

### ISSUE THREAD

**Issue by mwllgr** [go-gitea/gitea#15295]
- Gitea version: 1.13.6 (binary file)
- Git version: 2.25.1
- Operating system: Ubuntu 20.04
- Database:
  - [ ] PostgreSQL
  - [x] MySQL (MariaDB)
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes
  - [x] No (Heatmap not visible with newly registered user?)

## Description
When navigating to the dashboard, a heatmap for my user's commits should appear. Instead, a loading circle is visible for around half a second which simply disappears then.

When checking out the HTTP requests, I found out that Gitea requests the heatmap for a user with the name _undefined_ instead of my real username. The request works when I manually set the URL to my own username.

## Screenshots

![image](https://user-images.githubusercontent.com/25794895/113632665-dee2ba80-966b-11eb-8daf-59aa91d569a4.png)

**Comment by Tobstr02** [comment]
+1 Same issue here

**Comment by silverwind** [comment]
Not sure what's the issue but this will be fixed in 1.14 where this api call was removed for the heatmap rendering.

**Comment by mwllgr** [comment]
Yes, indeed, it's fixed now. Thanks!
