### ISSUE TITLE
Something is causing a lock on some records on "repositories" table

### ISSUE THREAD

**Issue by andreynering** [go-gitea/gitea#1529]
- Gitea version (or commit ref): Current master (4bea2191286dd5a9c89696d3e8cd506caf997c7e)
- Git version: `git version 2.10.2.windows.1`
- Operating system:
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist: none

## Description

I think it might be PostgreSQL specific, since I tried on `try.gitea.io`, which uses MariaDB, but couldn't reproduce.

In different installations I saw this issue where it isn't possible to update any information of a repository (e.g. change its name or if it's private or public) or even delete the repo. When you click the Update or Delete button, the request takes forever and nothing happens.

Doing some investigation I found that it's a lock issue in the DB. If I try to update or delete the record in my SQL editor it takes forever and never completes. But if I stop Gitea and try again than it works. If I start Gitea again the lock happens again.

I think it may be an issue with an migration or other startup action (probably a mising commit or rollback), but could not fint it yet. I'm posting here to know it anyone has any idea.

**Comment by lunny** [comment]
Then have you tested before  4bea219's version ?

**Comment by lunny** [comment]
I think this should be caused by #1332 which we just merged.

**Comment by bkcsoft** [comment]
@andreynering Could you verify using this? https://wiki.postgresql.org/wiki/Lock_Monitoring

And get the last N lines from `xorm.log` :)

**Comment by bkcsoft** [comment]
@lunny Status-API isn't used by anything, and has no Foreign Keys to Repository either (that should probably be fixed though...). So I don't see how it could affect the DB at all 😕

**Comment by andreynering** [comment]
I noticed this issue during this week, but it may exist even longer. So has nothing to do with the status API just merged.

**Comment by bkcsoft** [comment]
Well, we found other issues in the Status-API PR anyhow so 💯 https://github.com/go-gitea/gitea/pull/1332#pullrequestreview-34055076 (Double Transactions ❤️ )

**Comment by andreynering** [comment]
After updating with current master, this was somehow fixed, but I have no idea how. 😱

**Comment by lunny** [comment]
Since no PR to fix this, I moved it from 1.2.0
