### ISSUE TITLE
"commit.GetBranchName: signal: segmentation fault" when opening older commit message

### ISSUE THREAD

**Issue by eveslage** [go-gitea/gitea#15307]
- Gitea version (or commit ref): 1.13.4
- Git version: 2.20.1
- Operating system:
  Debian 4.19.171-2
  gitea running as systemd
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
- Log gist:

2021/04/06 14:55:54 ...uters/repo/commit.go:318:Diff() [E] commit.GetBranchName: signal: segmentation fault
2021/04/06 14:55:54 ...s/context/context.go:139:HTML() [D] Template: status/500

## Description

when I open a commit message of file changed a while ago (> 6 month), I get a 500 error message. more recent changed files, work as expected.

Any chance to debug the error further?

**Comment by zeripath** [comment]
Please could you try on the latest version of Gitea, it would also be useful to do a git gc on the related repository.

**Comment by eveslage** [comment]
exactly the same error message (using gitea 1.13.6)

2021/04/06 16:06:31 ...uters/repo/commit.go:318:Diff() [E] commit.GetBranchName: signal: segmentation fault
2021/04/06 16:06:31 ...s/context/context.go:139:HTML() [D] Template: status/500

did a git gc:

$ git gc
Enumerating objects: 1499651, done.
Counting objects: 100% (1499651/1499651), done.
Delta compression using up to 16 threads
Compressing objects: 100% (337081/337081), done.
Writing objects: 100% (1499651/1499651), done.
Total 1499651 (delta 1065496), reused 1482042 (delta 1053844)
Checking connectivity: 1499651, done.
Computing commit graph generation numbers: 100% (186352/186352), done.

sadly nothing changed

**Comment by eveslage** [comment]
is there any chance to find out, which git command created the segmentation fault? neither log level debug, trace oder the dev run mode provided any more details

**Comment by zeripath** [comment]
The err is coming from:

https://github.com/go-gitea/gitea/blob/223dddb29e7559896a49b4e3fc89472b4444abf6/modules/git/commit.go#L482-L509

So it will be a call to:

`git name-rev --name-only --no-undefined <SHA>` (with or without `--exclude refs/tags/*` depending on your version of git.)

This absolutely should never segfault - and the only way it can happen is if there is a problem with your git repo. Please tell me you ran the gc on the gitea-repository not your local checkout. `git fsck` may also help.

**Comment by eveslage** [comment]
I did run `git gc` on the gitea repository

`git fsck` returned fine
`$ git fsck
Checking object directories: 100% (256/256), done.
Checking objects: 100% (1499651/1499651), done.
Checking connectivity: 1501004, done.
Verifying commits in commit graph: 100% (186352/186352), done.`

I could reproduce the issue on the command line

`
$git name-rev --name-only --no-undefined 8d0608be97eb07f5e8a7b624462181af55069b5a
tags/chart/XXXXXX_versionXXXXX~38
$ git name-rev --name-only --no-undefined fe325dc9c4349cc7453ee70b59baa9ab6413799c
Segmentation fault
`

that's bad, right?

**Comment by zeripath** [comment]
yeah it really shouldn't be possible to cause a segfault on name-rev

**Comment by zeripath** [comment]
I wonder if repacking may actually solve the issue.

**Comment by eveslage** [comment]
Thanks for your assistance. After cloning the affected repository, the error was gone. We will investigate the issue further, but its not a gitea issue.
