### ISSUE TITLE
the /repos/{owner}/{repo}/commits interface. if  sha use branch as parameter value can bring about commit count is incorrect

### ISSUE THREAD

**Issue by QuietClickCode** [go-gitea/gitea#15320]
- Gitea version (or commit ref): 1.11.0+dev-371-gd9c67a8c9
- Git version: 1.11.0+dev-371-gd9c67a8c9
- Operating system:win 10.0.18362
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
- Log gist:

## Description

...
the /repos/{owner}/{repo}/commits interface. if  sha use branch as parameter value can bring about commit count is incorrect

## Screenshots

![微信图片_20210407153000](https://user-images.githubusercontent.com/33307916/113828120-9f74b500-97b6-11eb-8ee7-d78c14d4c7d3.png)
![1](https://user-images.githubusercontent.com/33307916/113828438-f5495d00-97b6-11eb-8b00-21c5b4800b50.png)
![2](https://user-images.githubusercontent.com/33307916/113828443-f7abb700-97b6-11eb-958e-b138a3be7c28.png)

**Comment by zeripath** [comment]
1.11 is extremely old. It's possible we have already fixed this on master. Can you replicate the problem on try?
