### ISSUE TITLE
Restored from backup and now dashboard does not update with existing repos activities.

### ISSUE THREAD

**Issue by iarp** [go-gitea/gitea#15326]
- Gitea version (or commit ref): 1.15.0+dev-65-g0bb8bd819
- Operating system: gitea/gitea docker
- Database: PostgreSQL
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
- Log gist: [gitea.log](https://github.com/go-gitea/gitea/files/6271982/gitea.log)

## Description

Gitea runs as a docker on unraid. For backup purposes I run tar the repos and data directories every night. About 1.5 months ago I had dual hard drive failure and had to restore data from backups. Since restoring, gitea's dashboard no longer shows activities for repos that existed before the restore point. 

If I add a new repo now and do commits, it all shows up in the dashboard. However preexisting stuff does not. I can still push and pull all repos without an issue. I've logged into that docker console to also recursively restore permissions on all repo folders to git:git.

How can I get my dashboard back?

The only difference I can currently see is the ownership on the repo folders/files were not correct. To figure out what the permissions should've been I created a new repo and saw that everything was written as git:git so I can `chown -R git:git ` on the repos in hopes it would bring back the dashboard.

**Comment by wxiaoguang** [comment]
IIRC this bug could have been fixed, please try latest release.

It's caused by out-synced git hooks.
