### ISSUE TITLE
PUT on `/notifications` endpoint with invalid date causes internal server error

### ISSUE THREAD

**Issue by matusf** [go-gitea/gitea#15346]
- Gitea version (or commit ref): Gitea version 1.13.7 built with GNU Make 4.1, go1.15.11 : bindata, sqlite, sqlite_unlock_notify
- Git version: git version 2.17.
- Operating system: Ubuntu 18.04
- Downloaded gitea from downloads page
- Running as a command-line program
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes (provide example URL)
  - [ ] No
- Log gist:
```
2021/04/08 18:14:24 Completed PUT /api/v1/notifications?last_read_at=xxx 500 Internal Server Error in 35.807758ms
```

## Description
Make PUT request on `/notifications` endpoint with supplied authorization token and invalid date in query parameters. Then 500 response is returned with following response body:
```
curl -X PUT 'http://localhost:3000/api/v1/notifications?last_read_at=xxx' -H "Authorization: token $TOKEN"
{"message":"","url":"http://localhost:3000/api/swagger"}
```

**Comment by 6543** [comment]
I think we should return a 422 with an error description

**Comment by zeripath** [comment]
I mean a 500 here is not entirely inappropriate, from MDN:

```
500 Internal Server Error
The server has encountered a situation it doesn't know how to handle.
```

I think 422 is really supposed to be emitted by WebDAV servers - I'm not sure how many other services use it.

400: Bad Request is probably the better supported option.

**Comment by 6543** [comment]
shuld be solve by #16177
