### ISSUE TITLE
Question mark in URL renders as broken link in Markdown

### ISSUE THREAD

**Issue by fnetX** [go-gitea/gitea#15349]
- Gitea version (or commit ref): 1.13 - 1.15-dev
- Database (use `[x]`):
  - [x] MySQL
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes https://try.gitea.io/fnetx/everything/issues/1

## Description
As a user on Codeberg pointed out a while ago, adding a question mark in a URL makes Gitea add a `=` sign at the end whcih breaks the url, see https://codeberg.org/Codeberg/Community/issues/292 (and originally https://codeberg.org/Codeberg/Community/issues/249#issuecomment-79991)
I didn't find this reported anywhere (although I found it's somehow hard to search for this if no one spelled out `question mark` and or `equals sign`), and it's still reproducible.

**Comment by silverwind** [comment]
Should rename the issue that this relates to the Markdown renderer. It was not immediately clear to me.

**Comment by zeripath** [comment]
OK it appears that the `=` is being added by the bluemonday Sanitizer.

**Comment by zeripath** [comment]
Likely at: 

https://github.com/go-gitea/gitea/blob/477c4530e48c072aa3d02c9e62c8428768c443e6/vendor/github.com/microcosm-cc/bluemonday/sanitize.go#L168-L179

Bluemonday has made the common but actually non-compliant assumption that the query component must contain key=value pairs.

**Comment by silverwind** [comment]
> Bluemonday has made the common but actually non-compliant assumption that the query component must contain key=value pairs.

Ugh, yeah that is a very bad assumption.

**Comment by zeripath** [comment]
Now the following patch will handle that assumption:

```patch
diff --git a/vendor/github.com/microcosm-cc/bluemonday/sanitize.go b/vendor/github.com/microcosm-cc/bluemonday/sanitize.go
index 99559bbab..f4ec4126e 100644
--- a/vendor/github.com/microcosm-cc/bluemonday/sanitize.go
+++ b/vendor/github.com/microcosm-cc/bluemonday/sanitize.go
@@ -124,8 +124,9 @@ func escapeUrlComponent(val string) string {
 
 // Query represents a query
 type Query struct {
-	Key   string
-	Value string
+	Key      string
+	Value    string
+	HasValue bool
 }
 
 func parseQuery(query string) (values []Query, err error) {
@@ -139,9 +140,11 @@ func parseQuery(query string) (values []Query, err error) {
 		if key == "" {
 			continue
 		}
+		hasValue := false
 		value := ""
 		if i := strings.Index(key, "="); i >= 0 {
 			key, value = key[:i], key[i+1:]
+			hasValue = true
 		}
 		key, err1 := url.QueryUnescape(key)
 		if err1 != nil {
@@ -158,8 +161,9 @@ func parseQuery(query string) (values []Query, err error) {
 			continue
 		}
 		values = append(values, Query{
-			Key:   key,
-			Value: value,
+			Key:      key,
+			Value:    value,
+			HasValue: hasValue,
 		})
 	}
 	return values, err
@@ -169,8 +173,10 @@ func encodeQueries(queries []Query) string {
 	var b strings.Builder
 	for i, query := range queries {
 		b.WriteString(url.QueryEscape(query.Key))
-		b.WriteString("=")
-		b.WriteString(url.QueryEscape(query.Value))
+		if query.HasValue {
+			b.WriteString("=")
+			b.WriteString(url.QueryEscape(query.Value))
+		}
 		if i < len(queries)-1 {
 			b.WriteString("&")
 		}
@@ -965,7 +971,6 @@ func (p *Policy) matchRegex(elementName string) (map[string]attrPolicy, bool) {
 	return aps, matched
 }
 
-
 // normaliseElementName takes a HTML element like <script> which is user input
 // and returns a lower case version of it that is immune to UTF-8 to ASCII
 // conversion tricks (like the use of upper case cyrillic i scrİpt which a
```

This will make the url: `https://htmlpreview.codeberg.eu/?https%3A%2F%2Fcodeberg.org%2Fivan-paleo%2FinitiationR%2Fsrc%2Fbranch%2Fmaster%2FinitiationR.html` 

Presumably this is correct enough? Technically AFAIU the `/` in the query component do not need to be escaped - nor potentially the `:`
