### ISSUE TITLE
[query] Where can I put a .gitconfig for just Gitea?

### ISSUE THREAD

**Issue by lofidevops** [go-gitea/gitea#1536]
- Gitea version (or commit ref): 1.1.0
- Git version: 2.11.0
- Operating system: Ubuntu 17.04
- Database (use `[x]`):
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Not relevant
- Log gist: N/A

## Description

1. Start Gitea web server
2. Gitea creates ~/.gitconfig and populates it with user.name "Gitea" and user.email "gitea@fake.local"

I don't normally use a global `~/.gitconfig` so this autocreation creates issues for other tools I use. Is there another location I can create a `.gitconfig` file for Gitea to use? For example, `gitea/custom/conf/` or `gitea/repositories/`.

**Comment by lofidevops** [comment]
~~Workaround: create `~/.gitconfig` as an empty file, make it owned by root, and make it read-only. Gitea will use the "gitea@fake.local" identity and won't make changes to the file.~~

This doesn't work. Gitea recreates `~/.gitconfig` as a file owned by the user.

**Comment by lunny** [comment]
create a Gitea only-use user for example git Or maybe you can use docker to do that.

**Comment by lofidevops** [comment]
I created a user for the Gitea process and modified `~/.gitconfig` for that user. Thanks!
