### ISSUE TITLE
failed connection to postgres due to null bytes

### ISSUE THREAD

**Issue by butlerx** [go-gitea/gitea#1537]
- Gitea version (or commit ref): docker latest
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist: https://gist.github.com/butlerx/391f096cd83ad37655069ef8a1350587

## Description
server fails to respond. 
postgres complains about different null bytes
...

**Comment by lafriks** [comment]
What is database encoding?

**Comment by butlerx** [comment]
error from tcp dial appeared to be an internal dns, that's since been fixed and null byte seems to be unrelated but has not occurred again
