### ISSUE TITLE
Issuelist icon too high

### ISSUE THREAD

**Issue by zeripath** [go-gitea/gitea#15386]
- Gitea version (or commit ref): 1.15.0+dev-108-g84f5a0bc6
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes (provide example URL): https://try.gitea.io/issues
  - [ ] No

## Description

The issue list icon is now too high

## Screenshots

![Screenshot from 2021-04-10 12-36-02](https://user-images.githubusercontent.com/1824502/114268499-53fe1900-99f9-11eb-8d12-3c8c4770d5db.png)

**Comment by zeripath** [comment]
Could fix this by sticking an ac in the class here:

https://github.com/go-gitea/gitea/blob/84f5a0bc62568b6d0a67969e460f4d41339a07d6/templates/shared/issuelist.tmpl#L5

which would make this:

![Screenshot from 2021-04-10 12-51-31](https://user-images.githubusercontent.com/1824502/114268897-7e50d600-99fb-11eb-9d8c-3c8d66d5eff6.png)

**Comment by silverwind** [comment]
The top edge of the icon should align with the top edge of the first text line.

**Comment by silverwind** [comment]
I can not reproduce the original screenshot on latest Chrome. Can you try updating?

https://github.com/go-gitea/gitea/pull/15391#issuecomment-817647436

**Comment by zeripath** [comment]
it persists.

**Comment by zeripath** [comment]
the issue may be related to segoe ui on linux

**Comment by silverwind** [comment]
Yeah must be something like that. It's kind of hard to align this properly. I guess I'd need to boot up a Linux VM to verify.

**Comment by zeripath** [comment]
I think it's just Segoe UI - its baseline sits 2.5px below the svg height. 

https://core.trac.wordpress.org/ticket/48423

I'm not certain how we can handle it except by abandoning segoe-ui. I might just remove it from my fonts as I only occasionally need it.

**Comment by zeripath** [comment]
Do we know if Windows has the same problem?

**Comment by zeripath** [comment]
The NotoSans looks like the baseline is perhaps 1px below the svg.
