### ISSUE TITLE
[Feature] /metrics in json format -> /metrics?format=json

### ISSUE THREAD

**Issue by somera** [go-gitea/gitea#15395]
- Gitea version (or commit ref): 1.13.7
- Git version:
- Operating system: Ubuntu 20.04.2
  
  
  
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite

I will store the metrics informations in InfluxDB. It would be easier if the data were already in json format.

**Comment by johanvdw** [comment]
InfluxDB has native support for reading openmetrics (prometheus data format) that gitea exposes.

**Comment by somera** [comment]
> InfluxDB has native support for reading openmetrics (prometheus data format) that gitea exposes.

Yes, that's correct
