### ISSUE TITLE
[BUG] PDF File View broken if CDN subdomain used + private repo

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#15390]
Gitea Version: 1.15.0+dev-21-gf4e677edb

test: `https://gitea.com/TestOrg/Test/raw/branch/master/pdf-test.pdf`

since pdf viewer try to load `https://s.gitea.com/TestOrg/Test/raw/branch/master/pdf-test.pdf` (CDN url) it wont show it

error message:
```
PDF.js Version 2.1.266 (build: 81f5835c)
Nachricht: Missing PDF "https://s.gitea.com/TestOrg/Test/raw/branch/master/pdf-test.pdf".
```

**Comment by wxiaoguang** [comment]
The PDF viewer has been replaced by a more native one. Maybe no problem now?
