### ISSUE TITLE
Problem running 1.14.0 on Slackware64-current

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#15406]
- Gitea version (or commit ref): 1.14.0
- Git version: 2.31.1
- Operating system: Slackware64-current
  
Gitea is being built from source (1.13.7 and 1.14.0) Build compiles fine but instant HTTP 500 error when accessing the web i nterface . 

Running from command line under gitea user ... ./gitea web

- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X] No

Builld log: https://www.wilhall.net/build.log

Using Nginx as a reverse proxy, but this is not the issue cos prebuilt binaries work fine with the same setup.

2021/04/11 19:09:54 cmd/web.go:82:runWeb() [I] Starting Gitea on PID: 14109
2021/04/11 19:09:54 ...dules/setting/git.go:101:newGit() [I] Git Version: 2.31.1, Wire Protocol Version 2 Enabled
2021/04/11 19:09:54 routers/init.go:93:PreInstallInit() [T] AppPath: /home/nginx/gitea
2021/04/11 19:09:54 routers/init.go:94:PreInstallInit() [T] AppWorkPath: /home/nginx
2021/04/11 19:09:54 routers/init.go:95:PreInstallInit() [T] Custom path: /home/nginx/custom
2021/04/11 19:09:54 routers/init.go:96:PreInstallInit() [T] Log path: /home/nginx/log
2021/04/11 19:09:54 routers/init.go:97:PreInstallInit() [T] Preparing to run install page
2021/04/11 19:09:54 cmd/web.go:189:listen() [I] Listen: http://0.0.0.0:3000
2021/04/11 19:09:54 ...s/graceful/server.go:55:NewServer() [I] Starting new Web server: tcp:0.0.0.0:3000 on PID: 14109
2021/04/11 19:09:54 ...s/graceful/server.go:66:func1() [D] Starting server on tcp:0.0.0.0:3000 (PID: 14109)

As soon as i hit the web interface the following errors appear in the console:

2021/04/11 19:19:16 ...uters/routes/base.go:36:1() [I] Started GET / for 127.0.0.1:36938
2021/04/11 19:19:16 ...s/context/context.go:184:HTML() [D] Template: install
2021/04/11 19:19:16 ...s/context/context.go:194:HTML() [E] Render failed: html/template: "install" is undefined
2021/04/11 19:19:16 ...s/context/context.go:184:HTML() [D] Template: status/500
2021/04/11 19:19:16 ...uters/routes/base.go:45:1() [I] Completed GET / 500 Internal Server Error in 418.278µs
2021/04/11 19:19:17 ...uters/routes/base.go:36:1() [I] Started GET /serviceworker.js for 127.0.0.1:36942
2021/04/11 19:19:17 ...uters/routes/base.go:45:1() [I] Completed GET /serviceworker.js 404 Not Found in 55.33µs

Relevant build flags: 
make clean
TAGS="bindata sqlite sqlite_unlock_notify pam"
make generate build

Any idea's on what is going on here and now i can fix this ? If i have missed any useful information please let me know and i will provide the information

**Comment by 6543** [comment]
Look like bindata did not embed some templatefiles

**Comment by lunny** [comment]
```
CGO_CFLAGS="-g -O2 -DSQLITE_MAX_VARIABLE_NUMBER=32766" go build -mod=vendor -v  -tags '' -ldflags '-s -w  -X "main.MakeVersion=GNU Make 4.3" -X "main.Version=1.14.0" -X "main.Tags="' -o gitea
```
-tags is empty, bindata is necessary and if you want to support sqlite, sqlite is also needed.

**Comment by R3belWithoutAPause** [comment]
> ```
> CGO_CFLAGS="-g -O2 -DSQLITE_MAX_VARIABLE_NUMBER=32766" go build -mod=vendor -v  -tags '' -ldflags '-s -w  -X "main.MakeVersion=GNU Make 4.3" -X "main.Version=1.14.0" -X "main.Tags="' -o gitea
> ```
> 
> -tags is empty, bindata is necessary and if you want to support sqlite, sqlite is also needed.

In my build script i have set TAGS="bindata sqlite sqlite_unlock_notify pam" as said above and as per the instructions for building from source. If these flags are not being picked up by the build process, what am i doing wrong and how should i pass these flags ?

**Comment by 6543** [comment]
are the build scripts in a public repo?

**Comment by R3belWithoutAPause** [comment]
https://git.wilhall.net/Slackbuilds/Gitea/src/branch/master/gitea.SlackBuild

**Comment by 6543** [comment]
@R3belWithoutAPause you have to export enviroment vairalbes or set them in exec call:
```
export TAGS="a b c"
make build -j1
```
or
```
TAGS="a b c" make build -j1
```
