### ISSUE TITLE
[Improve] Two-step verification code is automatically filled out

### ISSUE THREAD

**Issue by Hill-98** [go-gitea/gitea#15403]
- Gitea version (or commit ref): v1.14.0

## Description

1Password does not currently support two-step verification code that automatically fills in Gitea, I suggest that you can improve this experience.

Maybe you can modify the `id` and `name` of the input to `twofactor_tokeen` (I found that CloudFlare is so)

**Comment by Jonher937** [comment]
Do you have any documentation showing what 1Password (and possibly other Password managers) are looking for?

I made a small modification on the input of the 2FA page to make the experience a bit better on mobile (showing only numeric keyboard and on Android it suggest pasting the OTP code).

```
diff --git a/templates/user/auth/twofa.tmpl b/templates/user/auth/twofa.tmpl
index 68b474c86..a9ed66c43 100644
--- a/templates/user/auth/twofa.tmpl
+++ b/templates/user/auth/twofa.tmpl
@@ -11,7 +11,7 @@
                                        {{template "base/alert" .}}
                                        <div class="required inline field">
                                                <label for="passcode">{{.i18n.Tr "passcode"}}</label>
-                                               <input id="passcode" name="passcode" type="number" autocomplete="off" autofocus required>
+                                               <input id="passcode" name="passcode" type="text" autocomplete="one-time-code" inputmode="numeric" pattern="[0-9]*" autofocus required>
                                        </div>
 
                                        <div class="inline field">
```

Can you try if that makes it better for 1Password too?
Although I believe 1Password does not have support for pasting directly to OTP fields, but does offer an automatic copy of the OTP code on autofill so you have the OTP code in copy-paste

**Comment by Hill-98** [comment]
I tested this patch, although 1Password does not automatically populate it, but will display a list of fills. When I click on the list item, the 2fa code will appear in the input box.

This is a nice improvement.

**Comment by zeripath** [comment]
@Jonher937 would you like to send a PR with that?
