### ISSUE TITLE
Open Pull-Requests view with > 500 organizations need more than 1 minute

### ISSUE THREAD

**Issue by somera** [go-gitea/gitea#15412]
- Gitea version (or commit ref): 1.14.0
- Git version:
- Operating system: 20.04.2
  
  
  
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
- Log gist:

## Description

This with 1 minute is on my internal mini-server configuration.

I try to analyze what are you doing after I open the Pull-Requests link.

![image](https://user-images.githubusercontent.com/8334250/114322947-45138580-9b23-11eb-9292-c7d6710f2265.png)

What I see.

First this PostgreSQL query:

`explain analyze SELECT "repository"."id" FROM "repository" INNER JOIN "team_user" ON repository.owner_id = team_user.org_id INNER JOIN "team_repo" ON ('true' != 'false' and repository.is_private != 't') OR (team_user.team_id = team_repo.team_id AND repository.id = team_repo.repo_id) WHERE (team_user.uid = '1') GROUP BY repository.id`

![image](https://user-images.githubusercontent.com/8334250/114322958-4fce1a80-9b23-11eb-913f-cda537b9bf40.png)

Which needs ~7 seconds on my NUC (https://ark.intel.com/content/www/us/en/ark/products/126137/intel-nuc-kit-nuc7pjyh.html -> I'm running here Gitea 1.14.0, PostgreSQL 13, Nginx, InfluxDB, Grafana), And after the first query I see a lot small PostgreSQL queries. I think one for every organization.

And when I choose other organization from the long list

![image](https://user-images.githubusercontent.com/8334250/114323012-958ae300-9b23-11eb-8158-4c5b28993099.png)

I see > 500 http requests to the Gitea server

![image](https://user-images.githubusercontent.com/8334250/114323083-cff48000-9b23-11eb-9b05-452d888809a8.png)

Looks like the process is "complicated" and not scalable for a lot of organizations and repos. Cause I have no pull requests on my Gitea instance

![image](https://user-images.githubusercontent.com/8334250/114323309-d8998600-9b24-11eb-8c7f-da1f065950aa.png)

I think you should return back only all organizations which has pull requests. In my case: no one. Just the info: you dind't have any pull requests.

But this "problem" has only user with a lot of organizations and repos.

Am I right?

**Comment by nsmith5** [comment]
This looks like the offending call stack for anyone interested:

- https://github.com/go-gitea/gitea/blob/66f0fd0959b293c01a7685e9d7858db1da4416da/routers/user/home.go#L340
- https://github.com/go-gitea/gitea/blob/66f0fd0959b293c01a7685e9d7858db1da4416da/routers/user/home.go#L425
- https://github.com/go-gitea/gitea/blob/66f0fd0959b293c01a7685e9d7858db1da4416da/routers/user/home.go#L751
- https://github.com/go-gitea/gitea/blob/66f0fd0959b293c01a7685e9d7858db1da4416da/models/user.go#L588
- https://github.com/go-gitea/gitea/blob/66f0fd0959b293c01a7685e9d7858db1da4416da/models/user.go#L547-L565

Since this code path only appears to be used in this pull request page it might be worth making a more specific functions for this query?

**Comment by somera** [comment]
@nsmith5 the first question is, how the "show pulls" process should be changed?

I see two ways:

1. First fast fix: get only repos with opened or closed pull requests back -> use the current view
2. Rebuild the whole process

> Imagine the user has 1000 or 2000 repos? -> The speed of this view will be slower.
> 
> Collecting all the informations is not the best solution. Show only list with opened pull requests. Than add an option for showing the closed pull requests. And get the information for the selected option after users action. As user is my goal to see first and fast opened pull requests. Cause I will approve or deny them.

**Comment by lunny** [comment]
It depends on the machine I think. I tested my local instance with postgres 9.6 (Macbook pro 13 2020), I created 600 orgs, and it spend 1229ms on first org pull requests page and 494ms on second org pull requests page.

**Comment by somera** [comment]
> It depends on the machine I think. I tested my local instance ([ec69f34](https://github.com/go-gitea/gitea/commit/ec69f347264962448e619f3722788e07a11c36d2)) with postgres 9.6 (Macbook pro 13 2020), I created `600` orgs, and it took `1229ms` on first org pull requests page and `494ms` on second org pull requests page.
> 
> @somera Could you try v1.14.1 ?

Have you created empty orgs?

![image](https://user-images.githubusercontent.com/8334250/115965524-fce46200-a529-11eb-9b2c-3dc453f9e351.png)

Yes, it will be fastes with better hardware. But I would say, that the current flow is not scalable.

At the moment I have:

- 550 organisations
- 5461 repos

**Comment by somera** [comment]
First call

![image](https://user-images.githubusercontent.com/8334250/116006092-1a88f880-a60a-11eb-826e-9eb00184444d.png)

Second call

![image](https://user-images.githubusercontent.com/8334250/116006126-355b6d00-a60a-11eb-8a53-e70348ec93cf.png)

Third call

![image](https://user-images.githubusercontent.com/8334250/116006199-68056580-a60a-11eb-92c6-1b4032fe7e62.png)

And I'm using PostgreSQL 13 and Memcached.

**Comment by lunny** [comment]
@somera Could you test if #16099 could help you?

**Comment by somera** [comment]
> @somera Could you test if #16099 could help you?

I can't test an unreleased Gitea version.

**Comment by somera** [comment]
@lunny tested now with official 1.14.3

![image](https://user-images.githubusercontent.com/8334250/122601122-1e1c8700-d071-11eb-8861-40ab194dec07.png)

**Comment by zeripath** [comment]
It's not backported to 1.14.3

**Comment by somera** [comment]
@zeripath as I saw should it work fasten in 1.15.0. Today updated. And ...

Pull-Requests:
![image](https://user-images.githubusercontent.com/8334250/130350450-f1d66903-5eb9-45be-97a4-664228f9f46c.png)

Issues:
![image](https://user-images.githubusercontent.com/8334250/130350461-039e04c8-6fb6-4fd5-ad34-b99ee420d894.png)

The "fix" is not working.

**Comment by zeripath** [comment]
Can you give us some updated logs?

**Comment by somera** [comment]
> Can you give us some updated logs?

Take a look from this timestamp

```
2021/08/24 22:38:38 ...s/context/context.go:740:1() [D] Session ID: 49a88c0a05f4fe4b
2021/08/24 22:38:38 ...s/context/context.go:741:1() [D] CSRF Token: 4963LSms59-jIJIQYyeyCv4Rs9Y6MTYyOTgzNzQ5MzQ2NTQ0MjcxNQ
2021/08/24 22:39:48 ...s/context/context.go:185:HTML() [D] Template: user/dashboard/issues
```

See attachment. There are no more logs.

Gitea makes for every repo 2 or 3 queries. I have 5997 repos. ;) Sorry.
[xorm.zip](https://github.com/go-gitea/gitea/files/7042028/xorm.zip)

**Comment by somera** [comment]
To reproduce it just import ~100 mirrors or create repos. Without this you can't analyze it.

**Comment by lunny** [comment]
Could you change your configuration file to change log stack level to error? And give a new log file include http and xorm

**Comment by somera** [comment]
> Could you change your configuration file to change log stack level to error? And give a new log file include http and xorm

This is now my configuration:

```
[log]
MODE             = file,file-servicesmirror
MAX_DAYS         = 15
; LEVEL            = Debug
LEVEL            = Error
ROOT_PATH        = /var/lib/gitea/log
ROUTER           = file
; ROUTER_LOG_LEVEL = Debug
ROUTER_LOG_LEVEL = Error
STACKTRACE_LEVEL = Error
XORM             = file

[log.file.xorm]
FILE_NAME        = xorm.log
; STACKTRACE_LEVEL = Debug
STACKTRACE_LEVEL = Error

[log.file-servicesmirror]
MODE       = file
FILE_NAME  = servicesmirror-trace.log
; LEVEL      = Debug
LEVEL      = Error
EXPRESSION = services/mirror
```

But there will be nothing logged and the runtime chanched to:

Issues: Powered by Gitea Version: 1.15.0 **Seite: 23249ms** Template: 34ms

Pulls: Powered by Gitea Version: 1.15.0 **Seite: 23240ms** Template: 33ms

**Comment by lunny** [comment]
You have to change `[database] LOG_SQL=true`

**Comment by somera** [comment]
> You have to change `[database] LOG_SQL=true`

Yes. This looks so:

```
[database]
DB_TYPE  = postgres
CHARSET  = utf8
LOG_SQL  = true

[log]
MODE             = file,file-servicesmirror
MAX_DAYS         = 15
LEVEL            = Error
ROOT_PATH        = /var/lib/gitea/log
ROUTER           = file
ROUTER_LOG_LEVEL = Error
STACKTRACE_LEVEL = Error
XORM             = file

[log.file.xorm]
FILE_NAME        = xorm.log
STACKTRACE_LEVEL = Error

[log.file-servicesmirror]
MODE       = file
FILE_NAME  = servicesmirror-trace.log
LEVEL      = Error
EXPRESSION = services/mirror
```
But sql queries will be not logged.

**Comment by somera** [comment]
> @somera Could you help to try #16839 ?

I try to setup a new test system for this. I can't test it on my 24/7 system.

**Comment by somera** [comment]
Looks in 1.16.0 good now

![image](https://user-images.githubusercontent.com/8334250/151882193-ca5d4e80-d123-46f7-86bc-88996e74b428.png)

Thx!
