### ISSUE TITLE
TOC generating in VSCode with Markdown All in One : not compatible with Gitea

### ISSUE THREAD

**Issue by MilesTEG1** [go-gitea/gitea#15410]
- Gitea version (or commit ref): 1.14
- Git version:
- Operating system: Docker on Synology DS290+ , installed with `image: gitea/gitea:1`
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes ( https://try.gitea.io/mil/test/src/branch/master/README.md#user-content-222-changer-le-th%C3%A8me )
  - [ ] No
- Log gist: N/R

## Description

There is a difference between Gitea and GitHub markdown in the bookmark created when using # or ##, etc to make a paragrah title.
For my shared project, I use VSCode to code my file, and I create a TOC with [Markdown All in One](https://github.com/yzhang-gh/vscode-markdown). On GitHub there is no problem, it works perfectly, but not in Gitea (mine or your test server).

Why is there those differences between the bookmark for paragrah title between Gitea and GitHub ?
Would you consider making the same as GitHub ?
Thanks in advance.
...

## Screenshots

![image](https://user-images.githubusercontent.com/29298312/114321534-899b2300-9b1b-11eb-9b25-4ad4c8febbe3.png)

TOC working in Gitea, but not working on GitHub :  it has been modified by hand to have it working
![image](https://user-images.githubusercontent.com/29298312/114321241-088f5c00-9b1a-11eb-9abf-9541a287385b.png)

TOC working in GitHub but not in Gitea : generated by the VSCode Extension Markdown All in One
![image](https://user-images.githubusercontent.com/29298312/114321028-1690ad00-9b19-11eb-8e9a-241cec099fc8.png)

**Comment by silverwind** [comment]
Can you please paste the two variants in text format instead of screenshots?

**Comment by MilesTEG1** [comment]
The code is accessible here : https://try.gitea.io/mil/test/raw/branch/master/README.md

**Comment by zeripath** [comment]
The problem appears to be that on Gitea if we see:

```markdown
# 1.1. Header
``` 

We will set the id to `1-1-Header` whereas github will set it to `11-Header`. Of course if you then change that to 1. 1. Header Github and Gitea will then agree.

TBH Github is wrong - Their method is just going to make everything that much likely to conflict and less easy to understand. 

However, we need to handle it I guess?

**Comment by MilesTEG1** [comment]
Ok, I investigate further, and I sax that setting :
![image](https://user-images.githubusercontent.com/29298312/114464246-c9c6d800-9be5-11eb-89b2-f5fa482e5586.png)
Selecting Gitea made the TOC like Gitea's so I think this is it !
I have to investigate how to set automaticaly this setting on Gitea for my Gitea's repository, and set back to GitHub for the Github's one.
If you have any idea about this, I would be grateful :) 

So, I'm not sure you need to handle this.
But if you want, give a option to switch between Gitea's markdown, or GitHub's.

Thanks for your help 😃

**Comment by silverwind** [comment]
It depends whether GitHub's parser is open source and could be contributed to. It seems they use https://github.com/gjtorikian/commonmarker but I'm not sure if TOC parsing is part of that parser.

**Comment by MilesTEG1** [comment]
For now, I found a solution.
Add this `"markdown.extension.toc.slugifyMode": "gitea"`  into a `workspace.code-workspace` file to set the type of TOC.
![image](https://user-images.githubusercontent.com/29298312/114678227-58814500-9d0b-11eb-9564-c87498066362.png)
I may be done too by setting the same line into a .json file inside .vscode folder in each repositorie...

**Comment by wxiaoguang** [comment]
Markdown is not a strict standard, there is no definition for "anchor/TOC" generation.

So there is no right or wrong for this problem IMO.

I guess the issue has been resolved by `"markdown.extension.toc.slugifyMode": "gitea"` ?
