### ISSUE TITLE
doc errata

### ISSUE THREAD

**Issue by Hokwang** [go-gitea/gitea#15419]
Hi,

I think I find some problem in your web-site.

1. please look at https://docs.gitea.io/en-us/config-cheat-sheet/#oauth2-oauth2/
there's
```
oauth2:
  ENABLE: true
```
but, I think ENABLED (add D) may be right. please make consistency with other's.

2. please look at https://docs.gitea.io/en-us/config-cheat-sheet/#openid-openid
I think
`ENABLE_OPENID_SIGNUP: ! DISABLE_REGISTRATION: Allow registering via OpenID.`
has problem.

**Comment by lunny** [comment]
@Hokwang Could you send a PR?

**Comment by noerw** [comment]
Ad 1: the docs are correct, the setting is named `ENABLE`. This is inconsistent with other `ENABLED` settings, but due to already high complexity in settings parsing, this is most likely a wontfix

Ad 2: this is also correct, although ENABLE_OPENID_SIGNIN obviously needs to be true too.
