### ISSUE TITLE
Fix checkbox rendering in issues

### ISSUE THREAD

**Issue by mirhec** [go-gitea/gitea#1541]
- Gitea version (or commit ref): master
- Git version: the version on try.gitea.io
- Operating system: Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL): https://try.gitea.io/mirhec/test/issues/1
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

You can create checkboxes via the `[ ]` brackets, but there always is a line break after the checkbox. The following issue-content

```
## Checkbox

- [ ] Test 1
- [x] Test 2
- [ ] Test 1
```

renders to

![image](https://cloud.githubusercontent.com/assets/5173805/25386065/526304cc-29c6-11e7-9a94-8720a07f38c2.png)

**Comment by silverwind** [comment]
They are wrapped by a bare `<div>`, which should probably just be removed.

Also, it'd be great if they were checkable and that these state changes would edit the underlying markdown (if the user has edit permission), but that's probably more complicated to realize.

**Comment by geek1O11** [comment]
Bad idea

**Comment by pree** [comment]
This has probably something to do with #186

**Comment by kenogo** [comment]
Is there a reason to keep the bullets next to the checkboxes? It seems like quite an unusual way to handle it. At least GitHub and GitLab both don't do it.

**Comment by lunny** [comment]
@kenogo please fire another issue to discuss that.
