### ISSUE TITLE
1.14.0: git clone of the wiki broken?

### ISSUE THREAD

**Issue by cthu1hoo** [go-gitea/gitea#15420]
URL that was previously leading to the git repository of the wiki (i.e. https://git.tt-rss.org/git/tt-rss.wiki.git/) now returns source code for the main repository. I've been using this URL to generate static wiki pages which is now seemingly impossible.

Wiki editor also shows URL of project source repo now instead of a separate wiki repo which, I think, was shown here before:

![image](https://user-images.githubusercontent.com/47687909/114340122-81fd6d80-9b5f-11eb-8442-34af649f05f3.png)

Running 1.14.0 in a stock docker setup. I have multiple instances of Gitea running and it seems to be broken on all of them.

**Comment by silverwind** [comment]
What is the correct URL for wiki repos? I think this might have broken during one of the refactors of these headers.

**Comment by cthu1hoo** [comment]
I don't mind the URL not being visible but I would prefer it to be clone-able. :)

```
* remote origin
  Fetch URL: https://git.tt-rss.org/git/tt-rss.wiki.git/
  Push  URL: https://git.tt-rss.org/git/tt-rss.wiki.git/
```

**Comment by silverwind** [comment]
Will be fixed with https://github.com/go-gitea/gitea/pull/15430.
