### ISSUE TITLE
Mark file as reviewed

### ISSUE THREAD

**Issue by ptman** [go-gitea/gitea#15422]
- Gitea version (or commit ref): 1.14.0

## Description

GitHub now has a nice feature during review that allows you to mark files as reviewed. This helps with large PRs that you review in multiple parts.
![review](https://user-images.githubusercontent.com/24669/114370136-cb61b300-9b87-11eb-8d69-302401e2d753.png)

**Comment by 6543** [comment]
duplicate to #11730
