### ISSUE TITLE
 /api/v1/repos/search -> sending too much informations back

### ISSUE THREAD

**Issue by somera** [go-gitea/gitea#15437]
- Gitea version (or commit ref): 1.14.0
- Git version:
- Operating system:
  
  
  
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
- Log gist:

## Description

I analyzed which api calls are you doing for this view.

![image](https://user-images.githubusercontent.com/8334250/114470608-76f21e00-9bef-11eb-8b43-0cf1ba0cefaf.png)

Cause when I search for some repos and when I click << < x > >> than I see this steps:

- 176 is changing to 0
- sending /api/v1/repos/search with parameters
- show next founded repos
- 0 is changig to 176

I was wondering why the switch 176 <-> 0?

This is the response from /api/v1/repos/search api call:

![image](https://user-images.githubusercontent.com/8334250/114471110-59718400-9bf0-11eb-8b13-b45d6a20cf5e.png)

And if you take deep look on the data you see

![image](https://user-images.githubusercontent.com/8334250/114471173-76a65280-9bf0-11eb-9b57-26b4ac7181b5.png)

I would say, that you don't need 95% of the informations for this view.

**Comment by techknowlogick** [comment]
There's always someones usecase that potentially uses these fields, so if someone is looking into making a PR for this perhaps a field filter?

(relevant xkcd: https://xkcd.com/1172/)

**Comment by lunny** [comment]
We could introduce a new route `/api/ui/repos/search` to only provide necessary fields.

**Comment by zeripath** [comment]
I seriously doubt this is a major performance issue. Yes it's wasteful but we have much bigger fish to fry.

**Comment by somera** [comment]
> I seriously doubt this is a major performance issue. Yes it's wasteful but we have much bigger fish to fry.

I like fish! ;)

With the new `/api/ui/repos/search` route it will be better. But you are showing informations for others which shouldn't be shown for people, who has no admin access to the projects. Just show informations which are needed for this view.
