### ISSUE TITLE
LDAP account lockout

### ISSUE THREAD

**Issue by LukeMauldin** [go-gitea/gitea#15467]
- Gitea version (or commit ref): 1.13.1
- Git version: 2.30
- Operating system: rhel 8
- Database (use `[x]`):
  - [x ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x ] No

I have an LDAP provider setup for Gitea authentication using BindDN. The issue is that if I enter my password incorrectly on login, it appears that Gitea makes multiple ldap requests with the incorrect password and triggers the account lockout policy on the LDAP server. Is there an option to make Gitea only try one request?

**Comment by zeripath** [comment]
It would be helpful to get an idea what is causing the bind.  Now you could add some logging:
```ini
[log]
MODE = ...,bindtraceconsole
...

[log.bindtraceconsole]
MODE=console
LEVEL=trace
EXPRESSION=Binding with userDN:
STACKTRACE_LEVEL=trace
```

This would then cause logging to the console with stacktraces everytime `bindUser` is called.

We will then be able to work out what is causing the multiple binds.

**Comment by zeripath** [comment]
Without the logging requested we can't proceed further with helping you. Please reopen when you can provide the requested information.
