### ISSUE TITLE
Weird layout on a small (i.e. mobile) device

### ISSUE THREAD

**Issue by cthu1hoo** [go-gitea/gitea#15468]
The "repositories / users / organizations" bar seems to have a weird layout on small devices (phone, portrait):

![image](https://user-images.githubusercontent.com/47687909/114709129-e291d380-9d34-11eb-8448-88229a230815.png)

- indenting looks wrong
- there's a singular fade out after "users"

Maybe it should collapse into a dropdown or something? 

I'm running 1.14.0, stock docker setup.

**Comment by silverwind** [comment]
This was improved substantially lately.
