### ISSUE TITLE
Gitea 1.14.0 - Configuration page - SSH Configuration - Use Built-In Server value is reversed

### ISSUE THREAD

**Issue by GeyserLaPunk** [go-gitea/gitea#15461]
- Gitea version (or commit ref): 1.14.0
- Git version: 2.14.0
- Operating system: Windows 10
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
- Log gist:

## Description

...
Configuration page SSH Configuration Use Built-In Server check mark is reversed.
I have START_SSH_SERVER = true in app.ini but on the page I'm getting an "X".
If I change it to false and restart, I then get a check mark.

It was working correctly in 1.13.7 and 1.13.6.

**Comment by techknowlogick** [comment]
For anyone looking at a PR for this, I suspect the change required would need to be here: https://github.com/go-gitea/gitea/blob/master/templates/admin/config.tmpl#L64-L97
