### ISSUE TITLE
PHP Syntax Highlighing with inline HTML

### ISSUE THREAD

**Issue by JamesColeman-AH** [go-gitea/gitea#15497]
- Gitea version (or commit ref): 1.13.7
- Git version: 2.26.3
- Operating system: Linux/Docker
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes (provide example URL) https://try.gitea.io/JamesColeman-AH/Test/src/branch/master/example.php
  - [ ] No

## Description
Syntax highlighting of PHP with inline HTML seems to end the highlighting after the first PHP section, and does not highlight additional PHP/HTML. I tried looking to see where the highlighting was done to see if I could poke at it, and also reviewed previous issues posted. I found that CodeMirror is used for the editor, so I reviewed that and it is highlighting correctly.

## Screenshots

![Screen Shot 2021-04-15 at 10 47 24 AM](https://user-images.githubusercontent.com/55253252/114898903-24278a80-9dd8-11eb-96a3-fdb4a707f110.png)
![Screen Shot 2021-04-15 at 10 47 30 AM](https://user-images.githubusercontent.com/55253252/114898904-24c02100-9dd8-11eb-87f9-a42298457656.png)

**Comment by silverwind** [comment]
Highlighting in recent versions is done by chroma (rendering) and monaco (editor). I can reproduce the issue on https://swapoff.org/chroma/playground/ so it needs to be raised/fixed in chroma, https://github.com/alecthomas/chroma.

**Comment by JamesColeman-AH** [comment]
Actually, they have a syntax highlighter that works: https://github.com/alecthomas/chroma/blob/master/lexers/circular/phtml.go

https://github.com/alecthomas/chroma/issues/440

So maybe, is this an issue for Gitea or go-enry?

**Comment by silverwind** [comment]
I guess such a workaround would have to be in gitea. We could hardcode `.php` to PHTML syntax if that syntax works on both regular PHP sources and mixed HTML. Could you check on https://swapoff.org/chroma/playground/ if that is the case?

**Comment by JamesColeman-AH** [comment]
I tested random PHP files from WordPress/Joomla and Drupal as commonly used PHP programs with the phtml language, both template and non template PHP code and it handles PHP standalone code and code mixed with HTML without issues.

**Comment by silverwind** [comment]
I think there's still a possibility of fixing it in Chroma if they add the common php file extensions [here](https://github.com/alecthomas/chroma/blob/c44c690de223c9cb8fcd2eb28625edbc012bc2b8/lexers/circular/phtml.go#L16). We do use those file extensions during `lexers.Match`:

https://github.com/go-gitea/gitea/blob/9c4601bdf8369ed72944085e3952111cf4aeea11/modules/highlight/highlight.go#L74

**Comment by JamesColeman-AH** [comment]
Should I open an issue with chroma referencing this issue and suggest that we move the file name/mime types from their PHP lexer to their PHTML lexer?

**Comment by silverwind** [comment]
Please do. I'm no expert on PHP but [this comment](https://github.com/alecthomas/chroma/issues/210#issuecomment-651044801) suggests modern PHP could would generally not be mixed with HTML so that is why they went with two lexers. So I think either Chroma could provide a single "convenience" lexer we could use or one has to live with the `.phtml` extension. It should also be possible to override highlighting in your `app.ini`.

**Comment by JamesColeman-AH** [comment]
Oh, so that is an argument on syntax highlighting within a markdown parser. So to fix that, they basically made the lexer not care if a PHP tag is present or not, so it highlights PHP code without it. However, in our case, we are doing syntax highlighting of PHP files which are parsed by the PHP parser either via PHP-FPM, PHP-CGI, or another interface. The PHP parser itself will not recognize PHP code unless there is a PHP open tag.

For an example, the PHP code below will not execute if you just put that in a file and call it with the command line interface.

```php
echo "Hello ".$argv[1]."!\n";
```

Running just the above code with command line:

```
# php test.php Name
echo "Hello ".$argv[1]."!\n";
```

However, if you add the PHP open tag, it will work:

```php
<?php
echo "Hello ".$argv[1]."!\n";
```

Running code with the above in a file:

```
# php test.php Name
Hello Name!
```

With all of that in mind, the issue should be that the PHP lexer is not designed to parse files, but code snippets. And when parsing files, the PHTML lexer should be used instead.

I'll go ahead and open a issue with chroma referencing this issue.

**Comment by silverwind** [comment]
We could distinguish snippets in markdown from files. Reading up on the `.phtml` extension, it seems to have been of use in the PHP 2 era, with some transitions later to `.php4` and `.php5` and finally to just `.php`. It seems it's not that commonplace nowadays. If the issue can be resolved via detection of a `<?php` opening tag, that may be solveable in Chroma.

**Comment by JamesColeman-AH** [comment]
Created a pull request (https://github.com/alecthomas/chroma/pull/477) with chroma and tested the changes within chroma itself, I'm not entirely sure on how to verify if the changes will fix gitea.

**Comment by JamesColeman-AH** [comment]
Pull request is merged.

**Comment by Evzin** [comment]
Hello, im still having this issue with mixed php + html files on Gitea v1.18. Is there a way maybe to set phtml lexer for php files on setting level?

**Comment by silverwind** [comment]
> Hello, im still having this issue with mixed php + html files on Gitea v1.18. Is there a way maybe to set phtml lexer for php files on setting level?

Try `*.tmpl linguist-language=PHTML` in `.gitattributes`.

Original issue was fixed, so closing.
