### ISSUE TITLE
It is impossible to clone wiki repo

### ISSUE THREAD

**Issue by pvnhome** [go-gitea/gitea#15494]
- Gitea version: 1.14.0
- Git version: 2.30.0
- Operating system: Ubuntu 18.04.3 LTS
- Database:
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes
  - [ ] No

## Description

It is impossible to clone wiki repo any more. 

".wiki.git" suffix is not working.

For example try to clone https://try.gitea.io/pvnhome/test.wiki.git (user: pvnhome, pwd: qwerty):

```
git clone https://try.gitea.io/pvnhome/test.wiki.git
```

**Comment by techknowlogick** [comment]
Attempted to replicate using try and I was able to clone the wiki
![Screen Shot 2021-04-15 at 9 34 01 AM](https://user-images.githubusercontent.com/164197/114877929-c0985f80-9dcd-11eb-8966-757cb53d3686.png)

**Comment by pvnhome** [comment]
Yes, repo was cloned. But it is not wiki. It is main repo :-(
