### ISSUE TITLE
git push fails after upgrade to 1.14.1-gogit

### ISSUE THREAD

**Issue by tautf** [go-gitea/gitea#15507]
- Gitea version (or commit ref): 1.14.1 gogit
- Operating system: Windows server 2019
  
  
  
- Database (use `[x]`):
  - [x] PostgreSQL
- Log gist:

```
2021/04/16 10:24:43 routers/repo/http.go:556:serviceRPC() [E] Fail to serve RPC(receive-pack) in D:\Gitea\Repositories\supplier-platform\spwatchguard.git: read tcp 192.168.3.63:3000->192.168.3.117:57179: wsarecv: An existing connection was forcibly closed by the remote host. - 
2021/04/16 10:24:43 routers/repo/http.go:510:func1() [E] serviceRPC: Close: read tcp 192.168.3.63:3000->192.168.3.117:57179: wsarecv: An existing connection was forcibly closed by the remote host.
```
## Description

After update to 1.14.1 with gogit on windows server, git push doenst work anymore.
The logs are written above.

Following is outputted on the client:
```> git push origin master:master
error: RPC failed; curl 56 Recv failure: Operation timed out
fatal: the remote end hung up unexpectedly
fatal: the remote end hung up unexpectedly
Everything up-to-date
```

Do i have to run any tasks to gitea after the update?
Worked with 1.14.0 and previous 1.13.x versions

I already ran task: `Resynchronize pre-receive, update and post-receive hooks of all repositories.`

**Comment by TautFlorian** [comment]
After 20 minutes of retrying it then worked ?!?!
