### ISSUE TITLE
No way to use non-svg logo

### ISSUE THREAD

**Issue by andreymal** [go-gitea/gitea#15510]
Since 1.14 using `logo.svg` is hardcoded in all the templates, but my logo is not a svg, so it looks like a regression for my specific use case. Maybe it would be better to store a custom url for the logo in the configuration file?

**Comment by silverwind** [comment]
I think it's possible to embed bitmap images in SVG. If that is the case, we should probably add some hints in the documentation on how to do so.

**Comment by andreymal** [comment]
I should have left a note that I don't want to use such ugly workarounds...

**Comment by silverwind** [comment]
I think it's a proper solution. SVG is the most flexible format as it can display vector and raster images. One such convertion tool I found is https://www.aconvert.com/image/png-to-svg/.

**Comment by andreymal** [comment]
A custom url in the configuration file is even more flexible ;)

**Comment by andreymal** [comment]
Not every bitmap can be converted to a proper vector. I'm not sure if moving towards SVG is a good thing, and embedding bitmaps in SVG is still an ugly workaround :(

**Comment by silverwind** [comment]
JPG and PNG should work according to [this](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/image), which should cover all use cases. Not totally opposed to a PR that makes logo URL configurable thought.
