### ISSUE TITLE
Display SVG respecting viewbox

### ISSUE THREAD

**Issue by camlafit** [go-gitea/gitea#15515]
- Gitea version (or commit ref): 1.4.0

## Description

#14101 it's a very nice feature. But it's display on full webpage. Could be possible to display them respecting their viewbox ?

## Sample

https://git.spip.net/spip/spip/src/commit/195ea6651e848bd36b6823e6419d20869e391b13/prive/themes/spip/images/article-new-16.svg is displayed on full screen but it's an icon and should be proposed on 64x64 size.

Thanks

**Comment by lunny** [comment]
Or we can have zoom in/zoom out

**Comment by camlafit** [comment]
yes could be nice to zoom in/out from viewport as default size

**Comment by silverwind** [comment]
`viewbox`is not for dimensions. Try adding `width` and `height` to the `<svg>` tag and I imagine it would display in the proper size.

**Comment by silverwind** [comment]
Some [research](https://github.com/silverwind/symlink-test/tree/master/images) on the GH renderer:

- SVG without `width/height` always render at 300px width/height (letterboxed I assume).
- SVG with `width/height` render at those dimensions but capped at 600px width/height.

**Comment by camlafit** [comment]
\o/
