### ISSUE TITLE
When viewing a PDF file in a repository via browser, it appears to be cached and cannot be downloaded properly.

### ISSUE THREAD

**Issue by tcpluess** [go-gitea/gitea#15518]
- Gitea version (or commit ref): 1.14.0
- Git version: git version 2.30.2
- Operating system: alpine-release  3.13.5
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (example URL: https://try.gitea.io/tester125/giteatest2)
  - [ ] No

## Description

Steps to reproduce:
1. add the first PDF file from the attachments to a repository, and name the file e.g. `test.pdf`.
2. commit & push.
3. in the web UI, navigate to the repository and display the PDF file in the repository. The PDF is nicely displayed.
4. simulate some changes in the PDF by replacing the existing PDF with the second ond from the attachment. Git marks the PDF file as changed, because there are differences.
5. commit & push.
6. in the web UI, navigate to the repository and display the PDF. Expected behaviour: the replaced PDF should be shown (with the changes). Actual behaviour: the browser still loads the *old* version of the PDF, without the changes.
7. in the web UI, navigate to the PDF, and select the `Raw` download. The browser downloads the wrong PDF file with the old contents.
8. in the web UI, choose "Download Repository". In the downloaded ZIP or TAR file, the correct PDF is included.

Obviously, Gitea (or the web browser) performs some internal caching which leads to the fact that PDF files are not properly updated when they have been changed. Even refreshing the page in the browser does not solve the issue. It can only resolved by using a browser on a different computer, using an "incognito" tab or completely clearing the browser cache. While it is not strictly necessary to have PDF files in Git, it still indicates some problems with caching and the question arises: could this behaviour also affect other files, e.g. plain text files, or source code files or images?

[test.pdf](https://github.com/go-gitea/gitea/files/6326442/test1.pdf)
[test.pdf](https://github.com/go-gitea/gitea/files/6326443/test2.pdf)

**Comment by KN4CK3R** [comment]
That should be fixed with #15370.

**Comment by dfujim** [comment]
I have this same issue with firefox but not chrome. If I navigate to view the file via the exact commit, then the pdf renders properly, if not then I see the "cached" version. 

Mozilla Firefox 98.0.1
Google Chrome 99.0.4844.82
git version 2.25.1
os CentOS Linux 7
gitea version 1.16.2
         database SQLite3
         
For some reason this does not reproduce in the example above, but when I produce my own version the cached issue persists.

[Version 1](https://try.gitea.io/tester126/test/src/commit/2579186df6655f47f71c416ca238514853fd1410/test.pdf)
[Version 2](https://try.gitea.io/tester126/test/src/commit/8f6eb9226ba91ad41e31e540ff2ef9ded3615186/test.pdf)

[File link](https://try.gitea.io/tester126/test/src/branch/master/test.pdf), should show version 2, but shows version 1. 

PDFs produced with latex, if that makes a difference

**Comment by wxiaoguang** [comment]
> That should be fixed with #15370.

Close this one.
