### ISSUE TITLE
When the issues index is configured as a public path, multiple nodes cannot start normally

### ISSUE THREAD

**Issue by xingzhaowu** [go-gitea/gitea#15512]
It is normal to start the first node, but the error message when the second node starts is as follows:
Issue Indexer Initialization timed-out after:30s
My app.ini configuration information is as follows (the three nodes have the same configuration):
```
[indexer]
ISSUE_INDEXER_PATH=/public/indexers/issues.bleve
ISSUE_INDEXER_QUEUE_DIR=/public/indexers/issues.queue 
```

**Comment by lunny** [comment]
Multiple nodes should not use bleve as indexer type, you can use `db` or `elasticsearch` for issues indexer, `elasticsearch` for code indexer. And also there are many other thing need to be changed.

**Comment by xingzhaowu** [comment]
> Multiple nodes should not use bleve as indexer type, you can use `db` or `elasticsearch` for issues indexer, `elasticsearch` for code indexer. And also there are many other thing need to be changed.

Ok i see, thank you very much.
