### ISSUE TITLE
Create git-daemon-export-ok file when creating public repositories

### ISSUE THREAD

**Issue by holtrop** [go-gitea/gitea#15521]
- Gitea version (or commit ref): 1.14.1 (downloaded from web site, running via systemd service)
- Git version: 2.25.1
- Operating system: Ubuntu 20.04.2 LTS
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] N/A - try.gitea.io appears to not have the git-daemon port open and I cannot tell if it created the git-daemon-export-ok file without that

## Description

gitea appears to have support to create the git-daemon-export-ok file when the repository is changed from private to public (done in the updateRepository() function). However, gitea does not create this file when creating a repository (either via New or Migrate options).

I can get gitea to create the git-daemon-export-ok file as I desire after creating a new repository by changing it from public to private, saving the settings, and then changing it from private back to public.

gitea should create the git-daemon-export-ok file when creating a repository if it is set to public visibility to match what is done when changing from private to public.

**Comment by zeripath** [comment]
So there are a number of issues here - for a start we need to only create these files only when the repository is actually publicly viewable so the current code is likely incorrect too.
