### ISSUE TITLE
Issue upgrading from 1.13.1 to 1.14.1

### ISSUE THREAD

**Issue by jswolf19** [go-gitea/gitea#15525]
- Gitea version (or commit ref): 1.13.1 to 1.14.1
- Git version: 2.29.2 to 2.31.1
- Operating system: OpenSuse Leap 15.2
- using package from https://build.opensuse.org/package/show/devel:tools:scm/gitea
- using docker (self-made Dockerfile, can provide if necessary)
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
- Log gist:

## Description

String localization and interpolation does not seem to work correctly on upgrade to 1.14.1 from 1.13.1.
(Only the latest package is available at the repo, it seems, so I haven't been able to try upgrading to 1.13.7 first. Still working on that.)
The pages normally display in Japanese in my environment

I have reverted back to 1.13.1 for now, but I needed to update the version in the DB to be 156, so I don't know how long-term that solution is.

## Screenshots
![gitea 1 14 1](https://user-images.githubusercontent.com/519875/115099787-23772b80-9f73-11eb-8e1f-256e6524b206.png)

**Comment by jswolf19** [comment]
I executed the statements below to revert the DB schema to the previous values. The only data that seemed to be modified by the upgrade is the `comment` table, where non-sha data was moved from `commit_sha` to `old_ref`, but I'm leaving this as is for now.
```mysql
alter table `comment` drop column time_id;

alter table hook_task
      drop column typ
    , modify type int after uuid;

alter table oauth2_grant
      drop column `scope`
    , drop column nonce;

alter table project_board drop column sorting;

alter table protected_branch drop column block_on_official_review_requests;

alter table reaction
      modify created_unix bigint after user_id
    , drop key IDX_tmp_recreate__reaction_type
    , add key  IDX_reaction_type (`type`)
    , drop key IDX_tmp_recreate__reaction_issue_id
    , add key  IDX_reaction_issue_id (issue_id)
    , drop key IDX_tmp_recreate__reaction_comment_id
    , add key  IDX_reaction_comment_id (comment_id)
    , drop key IDX_tmp_recreate__reaction_user_id
    , add key  IDX_reaction_user_id (user_id)
    , drop key IDX_tmp_recreate__reaction_original_author_id
    , add key  IDX_reaction_original_author_id (original_author_id)
    , drop key IDX_tmp_recreate__reaction_created_unix
    , add key  IDX_reaction_created_unix (created_unix)
    , ROW_FORMAT = DEFAULT
;

drop table repo_transfer;

alter table review drop column dismissed;

drop table `session`;

alter table topic modify name varchar(25);

drop table user_redirect;

alter table webhook
      drop column `type`
    , modify hook_task_type int after is_active
;
```

**Comment by jswolf19** [comment]
I have also noticed that log files are no longer created where they used to be.
I'm guessing the layout on the filesystem has changed, either here or in the package I am using.

**Comment by jswolf19** [comment]
I had been moving a folder in my docker file which no longer needed moving. Sorry for any trouble.

**Comment by ecsgh** [comment]
One more remark as the maintainer of the package at openSUSE.
The package specified here is not used by docker in any way. It is a pure rpm package. And I have absolutely nothing to do with the docker container for opensuse. The issue is all completely wrong and irrelevant.
Since I have been using the specified package myself for years, I can say that it works without any errors.
