### ISSUE TITLE
The content wrapping problem in WIKI 

### ISSUE THREAD

**Issue by pjntt2020** [go-gitea/gitea#15531]
- Gitea version (or commit ref):
  Gitea version 1.14.1 built with GNU Make 4.1, go1.16.3 : bindata, sqlite, sqlite_unlock_notify

- Git version:
git version 2.1.4

- Operating system:
 
Linux raspberrypi 4.9.35-v7+ #1014 SMP Fri Jun 30 14:47:43 BST 2017 armv7l GNU/Linux

PRETTY_NAME="Raspbian GNU/Linux 8 (jessie)"
NAME="Raspbian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ x] Yes (provide example URL)
https://try.gitea.io/pjntt/qktest/wiki/%E6%B5%8B%E8%AF%95%E5%86%85%E5%AE%B9

  - [ ] No
- Log gist:

## Description
Some content added line breaks when editing, but the line breaks were lost when displayed.
Is this a problem with my operation? 

## Screenshots
When editing:

![微信截图_20210418125926](https://user-images.githubusercontent.com/68732405/115134821-2000a480-a046-11eb-9523-d033de0760d4.png)

When displayed 

![微信截图_20210418125950](https://user-images.githubusercontent.com/68732405/115134827-2e4ec080-a046-11eb-80f5-743953323fb7.png)

**Comment by noerw** [comment]
By default markdown renders linebreaks only when there is a blank line in between. This behaviour can be toggled by configuration:
https://docs.gitea.io/en-us/config-cheat-sheet/#markdown-markdown
