### ISSUE TITLE
gitea for Synology SSH not connected

### ISSUE THREAD

**Issue by iamkevinf** [go-gitea/gitea#15539]
- Gitea version (or commit ref):
- Git version: 1.15.0
- Operating system: Synology
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
- Log gist:

## Description

I deployed Gitea through a longshoreman on Synology. The HTTP method is normal, but the SSH method fails to connect. I was prompted to input the password, and my key has been added to the setting.
The SSH port for Synology is 11022
The port in Docker is set to local port 11023 container port 11022

## Screenshots

![image](https://user-images.githubusercontent.com/6906178/115207418-29fdd280-a12e-11eb-8ca4-3a982aa9db32.png)
![image](https://user-images.githubusercontent.com/6906178/115207447-31bd7700-a12e-11eb-806a-8fcd9cc6d5cc.png)
![image](https://user-images.githubusercontent.com/6906178/115207662-60d3e880-a12e-11eb-8a3f-82d3ff8bf2fb.png)
![image](https://user-images.githubusercontent.com/6906178/115207760-75b07c00-a12e-11eb-9a9e-113e1771b973.png)

**Comment by lunny** [comment]
Please try to change `SSH_PORT` to 11023

**Comment by iamkevinf** [comment]
> Please try to change `SSH_PORT` to 11023

![image](https://user-images.githubusercontent.com/6906178/115229357-88827b00-a145-11eb-8f7d-992728555e70.png)
my nas ssh port is 11022,
if you change port to 11023, the above error will be reported

**Comment by lunny** [comment]
but
> The port in Docker is set to local port 11023 container port 11022

**Comment by iamkevinf** [comment]
> but
> 
> > The port in Docker is set to local port 11023 container port 11022

英文不好还是说中文吧抱歉，，，，我nas的`ssh端口`是11022，docker中设置的`本地端口`是11023（这里不能是11022，提示端口占用），`容器端口`是11022,配置文件中`SSH_PORT`应该对应的是docker的本地端口还是容器端口呢？这部分一直没搞明白，谢谢回复。。。

**Comment by iamkevinf** [comment]
Problem solved
Synology does not open port `11023`, restart the service and modify the port is solved
