### ISSUE TITLE
Feature Request: Protect tags

### ISSUE THREAD

**Issue by eNBeWe** [go-gitea/gitea#15545]
- Gitea version (or commit ref): Any
- Git version: Any
- Operating system: Any
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No

## Description
We are currently migrating towards using Gitea as our company Git server. In the process we stumbled upon the fact that tags are not protectable in Gitea. We would like to have some way to restrict write access to tags through the UI.
At the moment we might be able to help us with re-enabling Git-Hooks, but this doesn't give us control over permissions etc.

**Comment by SuperOok** [comment]
As there were clarification questions, this requests wants the following:

- add a configuring option in the UI
- make it possible to configure specific tags
- you can add restrictions on users who can create, update, delete the named tags

Such a feature exists already for branch protection, but in gitea not for tag protection.
It exists in gitlab: https://docs.gitlab.com/ee/user/project/protected_tags.html
There wildcards can be used to specified tags or tag-families which should be configured with permissions.

Example usage: A release tag like release_1.0.05 is set by a specific role or person and is only allowed to be updated or deleted by that role or person.

**Comment by KN4CK3R** [comment]
I added this with #15629.
