### ISSUE TITLE
Edit Issue Title / Close issue button click events not working in Firefox

### ISSUE THREAD

**Issue by skaldesh** [go-gitea/gitea#15554]
- Gitea version (or commit ref): 1.14.1 built with GNU Make 4.3, go1.16.3 : bindata, timetzdata, sqlite, sqlite_unlock_notify
- Git version: 2.30.2
- Operating system: Arch Linux
- Run from docker via systemd (image: gitea/gitea:v1.14.1)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
- Firefox version: Mozilla Firefox for Arch Linux (archlinux - 1.0), 87.0 (64-bit)
## Description
When trying to edit the title of an existing issue, clicking on the "Edit" button does nothing in my firefox browser. Chromium works.
The "Close" button next to Comment has the same behaviour!

**Comment by skaldesh** [comment]
It happened to us after upgrading from 1.13 to 1.14. Before that, it worked fine

**Comment by silverwind** [comment]
Try clearing browser cache, it might be the (known) issue of stale resources shortly after an update.

**Comment by skaldesh** [comment]
You are absolutely right! Thank you
