### ISSUE TITLE
[Feature Request]: Show project of issue in list overview

### ISSUE THREAD

**Issue by skaldesh** [go-gitea/gitea#15553]
Use case: We created a single repo for tracking issues for the whole organization. For each repo, we created a project and we assign each issue to one project.  
In the issue list, the projects are not displayed, however. We are forced to open the project itself and use the kanboard view (which we do not like that much).  

It would be awesome, if we could show the associated project of an issue already in the list overview and make it also a filterable property (like assignee, label, milestone, etc.)  

![Image showing feature with exceptional drawing skills](https://user-images.githubusercontent.com/12274166/115380289-b4980d80-a1d2-11eb-9c47-2bdf43fc4005.png)

**Comment by wolftune** [comment]
I was searching for "filter" by project when checking if someone already opened this request. So, I hope this reply will make this issue show when searching for "filter". I strongly support this request, thanks!

**Comment by lunny** [comment]
I think this has been resolved.
