### ISSUE TITLE
Allow arbitrary path for landing pages

### ISSUE THREAD

**Issue by fwdekker** [go-gitea/gitea#15556]
- Gitea version: 1.14.0 (installed using `pkg`)
- Git version: 2.31.1
- Operating system: FreeBSD 12.2
- Database:
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL: N/A, not a bug)

## Description
In `nginx.conf`, I'm restricted to setting the `LANDING_PAGE` to one of `[home, explore, organizations, login]`. However, I actually want to get an anonymous dashboard as is proposed in #3263 (but the issue is stale and I cannot reopen it). Assuming that #3263 is not solved, a workaround for me would be to set the landing page to `FWDekker?tab=activity` because I'm the only one who uses the Gitea instance, so it's a close enough approximation. However, as far as I know, this custom value is not currently possible.

Allowing arbitrary (local) paths for the `LANDING_PAGE` option would also
* fix #14209 by allowing `explore/repos?sort=moststars`,
* allow a repo to be set as landing page, for Giteas on which that's probably what people are looking for anyway, and
* allow organisations, specific issues or pull requests, and so on to be set as landing page.

Allowing this probably doesn't have any security implications (as long as the path is sanitised), and at worst decreases usability because of a stupid configuration (e.g. paths to non-existing resources, paths to restricted resources, etc.), while it increases flexibility for users who want something like I described above.

Suggestion for backwards compatibility: If it starts without a `/`, it's one of the original four values, and if it starts with a `/ `the path is used as is.

**Comment by cnyballk** [comment]
I'm restricted to setting the <code>LANDING_PAGE</code> to login. but, i can open  organisations, specific issues or pull requests when i don't login.   not as login page

**Comment by wxiaoguang** [comment]
It has been implemented.

**Comment by FWDekker** [comment]
Awesome! :-)
