### ISSUE TITLE
Repository mirror failed due to rate-limit - duplicate key value violates unique constraint "topic_pkey

### ISSUE THREAD

**Issue by anders-larsson** [go-gitea/gitea#15564]
- Gitea version (or commit ref): 1.14.1. Using docker container gitea/gitea.
- Git version: 
- Operating system: Alpine 3.10
  
  
  

- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
- Log gist:

```
2021/04/20 14:49:12 modules/task/task.go:51:handle() [E] Run task failed: GET https://api.github.com/repos/puppetlabs/puppetlabs-augeas_core: 403 API rate limit of 60 still exceeded until 2021-04-20 15:02:13 +0200 CEST, not making remote
 request. [rate reset in 13m01s]
2021/04/20 14:58:19 ...s/context/context.go:308:HandleText() [E] Repository not found
2021/04/20 15:02:38 ...ules/task/migrate.go:67:func1() [E] DeleteRepository: repository does not exist [id: 137, uid: 11, owner_name: , name: ]
2021/04/20 15:02:38 modules/task/task.go:51:handle() [E] Run task failed: pq: duplicate key value violates unique constraint "topic_pkey"
2021/04/20 15:07:10 ...ules/task/migrate.go:67:func1() [E] DeleteRepository: repository does not exist [id: 138, uid: 11, owner_name: , name: ]
2021/04/20 15:07:10 modules/task/task.go:51:handle() [E] Run task failed: pq: duplicate key value violates unique constraint "topic_pkey"
```
I don't think `[E] Repository not found` line is relevant because it has been occurring before this happened.

## Description

Initiated a repository mirror request for a repository on github.com. However the request failed due to rate-limit implemented by Github. However after the mirror request failed it's no longer possible to attempt to do another mirror attempt because everything was not removed after the failed attempt.

Tried to run `Health check all repositories`, `Delete all repositories missing their Git files`, and `Reinitialize all missing Git repositories for which records exist` but neither seems to help. I suspect to fix this I would need to remove the record manually from the database? Maybe there is a bug in Gitea where not everything is cleaned up?

Had a look around and I'm not sure how to go about to resolve this issue. Not sure where this key is.
...

**Comment by zeripath** [comment]
I'm not certain that this is actually related to migration and may be more of a problem with your `topic` table.

it would be helpful if you could check what the value of the `topic_id_seq` and compare that to what is already within the topic table.

It may be that you need to recreate the topic table but first we need to check what the status of the sequences and the topic table are.

**Comment by lunny** [comment]
I think you are running migrate but not mirror.

**Comment by anders-larsson** [comment]
> 
> 
> I'm not certain that this is actually related to migration and may be more of a problem with your `topic` table.
> 
> it would be helpful if you could check what the value of the `topic_id_seq` and compare that to what is already within the topic table.
> 
> It may be that you need to recreate the topic table but first we need to check what the status of the sequences and the topic table are.

`last_value` in topic_id_seq1 is `6`. There are `7` rows in topic table. The entry with id `7` has created_unix 1615906280 which seems to be Tue 16 Mar 15:51:20 CET 2021 which is quite a while ago.

As far as I know topics is nothing we have messed around with manually. Seems like it automatically populated or maybe inherited from the repository mirror?

>
> I think you are running migrate but not mirror.
>

In  1.14.1 it seems mirror has been merged into the migrate. It's now a checkbox when doing a migrate to mirror the repository.

**Comment by anders-larsson** [comment]
Would `select setval('topic_id_seq1', 6);` as describe here[1] solve this issue? Sorry for stupid question but that would make last_value match the most recent id in topic.

[1] https://stackoverflow.com/questions/14646085/changing-the-value-of-a-id-seq-table-in-postgresql/14646121#14646121

**Comment by anders-larsson** [comment]
I followed the instructions on https://stackoverflow.com/a/21639138 and it seemed to fix it
