### ISSUE TITLE
pr initiator merge after reviewed.

### ISSUE THREAD

**Issue by dongshimou** [go-gitea/gitea#15567]
- Gitea version (or commit ref): 1.14.1 built with GNU Make 4.2.1, go1.16.3 : bindata, sqlite, sqlite_unlock_notify

can pr initiator merge after reviewed?

our app ci will run after merge. I hope the initiator controls the timing of the merger.

**Comment by noerw** [comment]
Your question is hard to follow, you can try asking with more details on our discord :)
