### ISSUE TITLE
Gitea allows to create duplicate issues

### ISSUE THREAD

**Issue by joseluisq** [go-gitea/gitea#15569]
- Gitea version (or commit ref): 1.13.7
- Git version: 
- Operating system: Linux amd64
  
  
  
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes, please see an example at https://try.gitea.io/joseluisq/duplicated-issues/issues
  - [ ] No
- Log gist:

## Description

To reproduce the issue, navigate to `/project/repo/issues/new` page for a Gitea repository and just press many times as you want on `Create Issue` button. Then you will see many `issues` created.

## Screenshots

Those screenshots show the same issue created twice because I have pressed two times the `Create Issue` button unintentionally.

**Screenshot of Issue 1 (using the same date time)**

<img width="300" alt="Screenshot 2021-04-21 at 15 29 38" src="https://user-images.githubusercontent.com/1700322/115563298-acfe6480-a2b7-11eb-8a4d-114dc757cbb8.png">

**Screenshot of Issue 2 (using the same date time)**

<img width="300" alt="Screenshot 2021-04-21 at 15 29 12" src="https://user-images.githubusercontent.com/1700322/115563308-aec82800-a2b7-11eb-9cbd-7d16c1b8a68e.png">

**Comment by wxiaoguang** [comment]
More details in
* https://github.com/go-gitea/gitea/issues/17111
