### ISSUE TITLE
Respository's home page show like empty after subgit transfer.

### ISSUE THREAD

**Issue by lightjiao** [go-gitea/gitea#15563]
- Gitea version (or commit ref): 1.14.1
- Git version:
- Operating system: Ubuntu 20
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
- Log gist:
No error log

## Description

My company use SVN for version control, but I would like use git. 
So I find a lightweight git server ( gitea ) deploy on virtual machine and use subgit to mirror SVN repo and git repo.

After subgit transfer：
- ✔I can see right git log on the server's repo ( xxx/data/gitea-repositories/xxx/xxx.git ) which means subgit transfer success.
- ✔I can clone the repo to my work machine with `git clone xxx@192.168.109.128:xxx/xxx.git`, and see right git commit which mirrored from SVN.
- ❌ BUT, the repo home page looks like it's a empty repo

...

## Screenshots
![](https://ftp.bmp.ovh/imgs/2021/04/520f1d8d12552a6c.png)

**Comment by lunny** [comment]
Please run `Resynchronize pre-receive, update and post-receive hooks of all repositories.` on your admin panel.

**Comment by lightjiao** [comment]
It doesn't work.
I click the `Resynchronize pre-receive, update and post-receive hooks of all repositories.` several times, I can see the task has finished on System Notices panel.

and this is the log:
```
2021/04/21 06:11:39 Started POST /admin for 192.168.109.1:8117
2021/04/21 06:11:39 ...odules/cron/tasks.go:113:GetTask() [I] Getting resync_all_hooks in &{{0 0} resync_all_hooks 0xc0013bf560 0x1fd3520 11}
2021/04/21 06:11:39 Completed POST /admin 302 Found in 3.339787ms
2021/04/21 06:11:39 Started GET /admin for 192.168.109.1:8117
2021/04/21 06:11:39 Completed GET /admin 200 OK in 5.296437ms
2021/04/21 06:11:39 Started GET /avatar/09eb38435a67112073d696bff1ad81ef for 192.168.109.1:8117
2021/04/21 06:11:39 Completed GET /avatar/09eb38435a67112073d696bff1ad81ef 302 Found in 852.835µs
```

**Comment by lunny** [comment]
If you are using ssh, please also run `Update the '.ssh/authorized_keys' file with Gitea SSH keys. (Not needed for the built-in SSH server.)`

**Comment by lightjiao** [comment]
@lunny 
I have run all of the Maintenance Operations on the admin panel yesterday, it still doesn't work. 😔

**Comment by lightjiao** [comment]
I found an error log on System Notices panel:
```
Failed to health check repository (xxx/xxx): context deadline exceeded
```

**Comment by lunny** [comment]
After you run that operations, you should push again to test.

**Comment by lightjiao** [comment]
@lunny 
I pushed one commit to `master` branch which subgit mirrored, 
- ✔The commit transfer to SVN repo successfully
- ✔I can see the push activity on Dashboard panel 
- ❌Click the commit id shows on Dashboard panel but return 404
- ❌the repo home page are still empty  

it still doesn't work : (

**Comment by zeripath** [comment]
This is a common problem with the root cause being that the hooks are not running for whatever reason.

One of the most common reasons is the use of noexec on the partition containing the repositories - this will not work.

Another one is too restrictive a set of permissions and privileges.

Another is the incorrect settings for the hooks or making them nonexec.

A final issue is the use of a non gitea controlled key.

If you are still having trouble search through the many similar closed issues and or reopen this one.
