### ISSUE TITLE
Error when trying to create Deploy Key on Codeberg.org (public Gitea instance)

### ISSUE THREAD

**Issue by Technisha** [go-gitea/gitea#15574]
- Gitea version (or commit ref): 1.15.0+dev-168-g2255afffa
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No

## Description
When trying to create a deploy key, i get this error: `Can not verify your SSH key: extractTypeFromBase64Key: invalid key format: illegal base64 data at input byte 0`, i don't have any idea why and it happens on both Codeberg and try.gitea

## Screenshots
![Screenshot_20210421_190522](https://user-images.githubusercontent.com/55587033/115600375-8a2e7900-a2d4-11eb-9d74-517e9069fcd6.png)
![Screenshot_20210421_190539](https://user-images.githubusercontent.com/55587033/115600397-9286b400-a2d4-11eb-9a53-aea74b16e8f5.png)

**Comment by zeripath** [comment]
The content of a deploy key needs to be the SSH key. It should begin with 'ssh-ed25519', 'ssh-rsa', 'ecdsa-sha2-nistp256', 'ecdsa-sha2-nistp384', 'ecdsa-sha2-nistp521', 'sk-ecdsa-sha2-nistp256@openssh.com', or 'sk-ssh-ed25519@openssh.com'.
