### ISSUE TITLE
Repo migration is not working in the new version 1.14.1

### ISSUE THREAD

**Issue by angelsanchez** [go-gitea/gitea#15570]
- Gitea version (or commit ref): 1.14.1
- Git version: 2.30.2
- Operating system: GNU/Linux Alpine 3.13.5
We are using the official docker image in k8s:
```  
image:
    repository: gitea/gitea
    tag: 1.14.1
```

- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
- Log gist:

The gitea container is logging this:
```
 2021/04/21 14:39:54 Started POST /api/v1/repos/migrate for 172.17.0.8:32768                                                                                                                           
 2021/04/21 14:39:54 Completed POST /api/v1/repos/migrate 409 Conflict in 37.199026ms
```

## Description

1. We are creating a new migration from a public github.com repository using the API `/api/v1/repos/migrate`

The API is returning the following error:

```
422 Unprocessable Entity

Migration failed: Clone: exit status 128 - fatal: unable to access 'https://github.com/go-gitea/gitea.git/': Could not resolve host: github.com
```

If we try to connect with github from the gitea instance, it fails:
```
# curl -vv https://github.com
* Could not resolve host: github.com
* Closing connection 0
curl: (6) Could not resolve host: github.com
```

The OS that is using the gitea docker image is:
```
# cat /etc/alpine-release 
3.13.5
```

Could be it related to https://github.com/gliderlabs/docker-alpine/issues/539?

**Comment by zeripath** [comment]
Is this still a problem?

**Comment by angelsanchez** [comment]
I have tested the new version `1.14.2` and the problem persists:

```
Could not resolve host: github.com
```
