### ISSUE TITLE
PR Error 500 with branch and tag sharing the same name

### ISSUE THREAD

**Issue by Berjou** [go-gitea/gitea#15592]
- Gitea version (or commit ref): 1.14.1
- Git version: 2.30.2
- Operating system: docker image gitea/gitea:1

- Database:
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite

- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes: https://try.gitea.io/berjou/same-tag-and-branch-name-test/pulls
![1619107644](https://user-images.githubusercontent.com/10575885/115747495-9cbcb700-a395-11eb-8ad1-cb27dee50b54.png)
  - [ ] No
  
- Log gist:
Sorry, tinkering a lot with my setup right now, the log are no longer present on my machine, and since the issue is easily reproductible, it should not be a problem. However, I'm happy to provide you specific logs if needed.

## Description
- `git checkout -b same-tag-and-branch-name-test`
- Create a commit and `git push origin same-tag-and-branch-name-test`
- `git tag same-tag-and-branch-name-test`
- `git push origin tag same-tag-and-branch-name-test`
- Create a pull request to merge `same-tag-and-branch-name-test` into `master`
- Now `https://gitea-instance/user/repo/pulls` return an error 500
- Note that we can see the pull request by accessing `https://gitea-instance/user/repo/1`

Notes:
After deleting the branch and tag, pushing my commit to a new brarnch with a different name, and opening a new pull request, the error 500 on `https://gitea-instance/user/repo/pulls` is gone. However, after merging the merge request, and now that there is no more opened PR, the error 500 came back.

Hope this issue can be fixed, and that someone could help me to fix my broken repository.

**Comment by Viktor-Yakovchuk** [comment]
I have reproduced similar problem on Gitea Version: 1.15.0+dev-252-ga69fb523a
But I have 500 error on the compare page: `http://localhost:3000/viktor/test/compare/master...test500`

I have a plan to fix it soon.
