### ISSUE TITLE
STATIC_URL_PREFIX configuration error

### ISSUE THREAD

**Issue by blakejia** [go-gitea/gitea#15607]
- Gitea version (or commit ref): 1.14.1
- Git version: 2.30.2
- Operating system: docker
  
  
  
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
- Log gist:

## Description

When I use this field STATIC_URL_PREFIX in app.ini, the following log appears in the browser.

```
construct 'SharedWorker': Script at '[STATIC_URL_PREFIX]/js/eventsource.sharedworker.js' cannot be accessed from origin '[ROOT_URL]'.
```

## Screenshots

![image](https://user-images.githubusercontent.com/9416560/115962389-b9035400-a54d-11eb-9f82-15582360805b.png)

**Comment by noerw** [comment]
This should be fixed by #15834
