### ISSUE TITLE
Repo paging in dashboard shows too many pages with 30 repos

### ISSUE THREAD

**Issue by fnetX** [go-gitea/gitea#15601]
- Gitea version (or commit ref): 1.13 (Codeberg), 1.15 (try.gitea.io)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io: 
  - [x] Yes https://try.gitea.io/30repos (feel free to join this org as admin)

## Description
The paging of repos is broken in the user dashboard with (n)*15 repos, n >= 2.
So with 15 repos, there is no paging yet, but with exactly 30 repos, you can click to the second page, and it also offers you to navigate to the third page (repos 31 - 45) - but it is just empty because there are no more repos to show.
I assume that this also happens with 45, 60, 75, 90 repos etc.

Feel free to join the 30repos org on try.gitea.io, I assume the maintainers have admin accounts on the instance.

## Screenshots
![screenshot, second page still offers a button to the right](https://user-images.githubusercontent.com/19634137/115876884-22e50600-a447-11eb-8521-9451307155ed.png)

**Comment by fnetX** [comment]
Since this is just a minor thing, it's probably a good first issue? Won't find the time to look at the code the coming weeks though ...

**Comment by jannaahs** [comment]
Hi, I would like to work on it. Is it ok?
