### ISSUE TITLE
Plain text README displayed partially

### ISSUE THREAD

**Issue by bagasme** [go-gitea/gitea#15615]
- Gitea version (or commit ref): master (commit 6ea6e2b4eb339f58f805783532f1b481fec67375, built with Go 1.16.1, Node 14.15.4).
- Git version: 2.31.1
- Operating system: Debian 10
  
  
  
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No (not relevant)
- Log gist: (not relevant)

## Description

I have a copy of [git.git](https://github.com/git/git) repository on my Gitea instance. When I navigate to `t/` directory, the displayed `README` was only partial (not fully displayed). I have to click `Raw` to see the full contents.

This issue first occurred from commit a week ago (I forgot where it is first happened).

This issue does not occur in README files with file extension (such as `README.md`).

## Screenshots

![displayed README](https://user-images.githubusercontent.com/40219486/115991474-c292c780-a5f2-11eb-9440-23e2d04e04a4.png)
In the screenshot above, the `README` is displayed up until `Since the tes`.

**Comment by POPSuL** [comment]
It's caused by this if-else branch https://github.com/go-gitea/gitea/blob/master/routers/repo/view.go#L514

Here only 1024 bytes passed to view (from https://github.com/go-gitea/gitea/blob/master/routers/repo/view.go#L404)
