### ISSUE TITLE
UI language setting problems

### ISSUE THREAD

**Issue by X-Lucifer** [go-gitea/gitea#15612]
- Gitea version (or commit ref): 1.14.1
- Git version: 2.31.1
- Operating system: Windows 10
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
- Log gist:

## Description

I used the Microsoft Edge browser and set the UI language to English, but after logging in again, it changed to Chinese by default.

## Screenshots

![屏幕截图 2021-04-25 111115](https://user-images.githubusercontent.com/11420730/115979173-fb14b000-a5b6-11eb-92a3-b08d5702cbf5.png)

**Comment by r10r** [comment]
Hi there, 

I can confirm this issue in the following clients:

* Safari on macOS 11.6 
* Edge on Windows 10

**Steps to Reproduce**

1. Set a language different from the browser language in `Settings->Profile->Language` and save the changes. The UI language is changed.
2. Logout from gitea
3. Login to gitea
4. The UI uses browser language which is different from  the `Settings->Profile->Language`.

**Comment by wxiaoguang** [comment]
Oh yes, I also meet the similar problem. The UI language sometimes differs from the language setting.

**Comment by zeripath** [comment]
I think this: 

```patch
diff --git a/modules/context/api.go b/modules/context/api.go
index c978835af..e25318940 100644
--- a/modules/context/api.go
+++ b/modules/context/api.go
@@ -245,6 +245,9 @@ func APIAuth(authMethod auth.Method) func(*APIContext) {
 		// Get user from session if logged in.
 		ctx.User = authMethod.Verify(ctx.Req, ctx.Resp, ctx, ctx.Session)
 		if ctx.User != nil {
+			if ctx.Locale.Language() != ctx.User.Language {
+				ctx.Locale = middleware.Locale(ctx.Resp, ctx.Req)
+			}
 			ctx.IsBasicAuth = ctx.Data["AuthedMethod"].(string) == new(auth.Basic).Name()
 			ctx.IsSigned = true
 			ctx.Data["IsSigned"] = ctx.IsSigned
diff --git a/modules/context/context.go b/modules/context/context.go
index 8adf1f306..a405f93d1 100644
--- a/modules/context/context.go
+++ b/modules/context/context.go
@@ -614,6 +614,9 @@ func Auth(authMethod auth.Method) func(*Context) {
 	return func(ctx *Context) {
 		ctx.User = authMethod.Verify(ctx.Req, ctx.Resp, ctx, ctx.Session)
 		if ctx.User != nil {
+			if ctx.Locale.Language() != ctx.User.Language {
+				ctx.Locale = middleware.Locale(ctx.Resp, ctx.Req)
+			}
 			ctx.IsBasicAuth = ctx.Data["AuthedMethod"].(string) == new(auth.Basic).Name()
 			ctx.IsSigned = true
 			ctx.Data["IsSigned"] = ctx.IsSigned
diff --git a/routers/web/user/auth.go b/routers/web/user/auth.go
index ba37c8e3e..1b1c70c8f 100644
--- a/routers/web/user/auth.go
+++ b/routers/web/user/auth.go
@@ -572,6 +572,10 @@ func handleSignInFull(ctx *context.Context, u *models.User, remember bool, obeyR
 
 	middleware.SetLocaleCookie(ctx.Resp, u.Language, 0)
 
+	if ctx.Locale.Language() != u.Language {
+		ctx.Locale = middleware.Locale(ctx.Resp, ctx.Req)
+	}
+
 	// Clear whatever CSRF has right now, force to generate a new one
 	middleware.DeleteCSRFCookie(ctx.Resp)
 
```

would solve the issue.

It would be useful if you could test this patch.

**Comment by r10r** [comment]
I'll try to test it on top of 1.15.6

**Comment by r10r** [comment]
Works! Thanks @zeripath!

Tested with 
* Safari on macOS 11.6
* Firefox on Windows 10

Will this be added to the 1.15.7 ?
