### ISSUE TITLE
JS error thrown in console on all pages: TypeError: setting getter-only property "name"

### ISSUE THREAD

**Issue by wolfbeast** [go-gitea/gitea#15617]
- Gitea version (or commit ref): 1.15.0+dev-184-g6ea6e2b4e
- Git version: unknown, the one on try.gitea.io
- Operating system: try.gitea.io
- Database (use `[x]`): try.gitea.io instance
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL) https://try.gitea.io/wolfbeast/pale-moon-localization/issues
  - [ ] No
- Log gist:

## Description
Browser: Pale Moon 29.1.1 x64
Error thrown in console: 
```
16:15:37.848 error { target: SharedWorker, isTrusted: true, message: "TypeError: setting getter-only property "name"", filename: "https://try.gitea.io/js/eventsource.sharedworker.js", lineno: 1, colno: 35, srcElement: SharedWorker, currentTarget: SharedWorker, eventPhase: 2, bubbles: false, cancelable: true } 1 index.js:150:2396
	Jh/</< https://try.gitea.io/js/index.js:150:2396
```
The code in question is:
```
self.name="eventsource.sharedworker.js";
```
I'm not sure what `self` in this context is, but it obviously doesn't seem to have a setter defined.

Note: it doesn't seem to affect functionality in a major way that I know of; it is also present on our production system running 1.12.6

**Comment by silverwind** [comment]
It should be https://developer.mozilla.org/en-US/docs/Web/API/SharedWorkerGlobalScope/name which is indeed read-only. I'm not sure what the purpose of the assignment exactly is.

**Comment by wolfbeast** [comment]
I'm assuming it would cause loss of functionality if a `TypeError` is thrown there, even if not critical. It'd abort the script.

**Comment by zeripath** [comment]
I'm not sure why I put it in - I'm sure I was copying from some other code that did set it - but clearly it's incorrect so let's just remove it.

**Comment by silverwind** [comment]
FWIW, we already give that worker a name via initialization, so there's certainly no reason to override it.

````js
new SharedWorker(`${__webpack_public_path__}js/eventsource.sharedworker.js`, 'notification-worker')
````
