### ISSUE TITLE
Feature request: Add CI/CD indicator on main home screen for each repo

### ISSUE THREAD

**Issue by Halfwalker** [go-gitea/gitea#15620]
Right now when viewing a repo, The main line shows the Author, commit hash and commit msg.  If CI/CD is configured (Drone in this case) then a green checkmark (hopefully) is also shown.
![image](https://user-images.githubusercontent.com/1365031/116012760-7d729380-a5fa-11eb-9236-f25f0b805145.png)

This is great - shows at a glance that the CI/CD pipeline(s) passed and all is well.

It would be really nice to ALSO see that green checkmark (or whatever status) on the main home screen next to each repo as well.  Would give an overall-status-at-a-glance
![image](https://user-images.githubusercontent.com/1365031/116012824-ece88300-a5fa-11eb-8855-68e0114a7364.png)

If it was live, as it is in the repo view, even better.  You glance at the home screen, see a problem, click, click and you're right in the CI/CD to see where the problem is.

Perhaps put it just to the left of the repo name, left of the small icon already there.

**Comment by Halfwalker** [comment]
Is there any chance of this happening ?  I just bumped into a situation where it would have been **great** ...  Found a repo that had been failing CI/CD just by chance when I clicked into it.  Had the Green Check or Red X been on the home screen it would have been obvious.

Wish I knew Go :(

**Comment by silverwind** [comment]
Open for implementation I'd say. We recently removed the star icon so there is certainly space there.

**Comment by yardenshoham** [comment]
How would one be able to get the latest commit status of the default branch of a repo? The search endpoint doesn't make it accessible
https://github.com/go-gitea/gitea/blob/4f1065030fb43f72478b068d08ad747b00300168/routers/web/repo/repo.go#L490
