### ISSUE TITLE
Renaming of the default branch to `main`

### ISSUE THREAD

**Issue by pat-s** [go-gitea/gitea#15623]
Given the well-known reasons for getting rid of the term `master` for branches in programming, I would like to push the idea of doing so in this repository.

GitHub default branch renaming is quite sophisticated and I'd expect little interruption for users.

Maintainers would need to make adjustments to CI runners eventually.

**Comment by techknowlogick** [comment]
As discussed in chat, this is what we'd like to do. A note for when the branch is changed is that when it is run a bunch of CI runs will happen at once so a bunch of jobs will need to be cancelled, also that branch protection would need to be updated.

Two things that need to happen prior to making the change, 1. the drone yaml (as mentioned above), and 2. a redirect for dl.gitea.io for where the bleeding edge binaries are stored. 

I'm happy with this change as I updated a bunch of my local tooling to adapt to many other forges/repos making this change and I have my gitea stuff pinned to an older version of my scripts so updating this repo would mean I could update those too.

**Comment by a1012112796** [comment]
so maybe we need a vote to decide whether we need rename ``master`` branch to ``main``.

**Comment by silverwind** [comment]
I would stick to [git's default](https://git-scm.com/docs/git-init#Documentation/git-init.txt---initial-branchltbranch-namegt) which is still `master`.

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
> I would stick to [git's default](https://git-scm.com/docs/git-init#Documentation/git-init.txt---initial-branchltbranch-namegt) which is still `master`.

yes, it *still is*, for now anyway.
![image](https://user-images.githubusercontent.com/61180606/116377177-35798980-a811-11eb-996c-2f1daa76aff2.png)

For my personal stuff I usually now just go with `main` but for bigger projects I'd probably just wait until git changes the default, I don't know...

Ultimately it's not too much work to change it right away, the branch changes in `.drone.yml` could even be prepared in advance, accepting both {main,master} fir the moment and pushed (merged) with `[skip ci]` until the thing is ready in other places, then clean up `.drone.yml` back to a single branch and links in Docs and other places or what have you.

**Comment by pat-s** [comment]
The work that needs to be done won't change. I do not see how `git init` calls are related to the default branch of **this** repo.

I would like to emphasise the [motivations for this change](https://www.theserverside.com/feature/Why-GitHub-renamed-its-master-branch-to-main) again which boils down to values.

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
> I do not see how `git init` calls are related to the default branch of **this** repo.

yeah, no worries...a demonstration of git's default branch warning/info message?
it was a reaction to silverwind mentioning what even for git currently stays as a default, although - per their words - subject to change.

the point being  along the lines of "they are also considering a change, why not wait until it's the default".

it's only related to the default branch of **this** repo in that the versioning tool's default is something and we're talking something else.

of course the decision to change *this project's* default branch has little to do with whatever the current versioning tool's default value is.

**Comment by pat-s** [comment]
Maybe this is a misunderstanding for some here - the default branch for new gitea repos is already `main`.

This is about the default branch of **this GitHub repo** :)

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
oh no, I get it perfectly.
main as the default branch in Gitea is for new installations perhaps, AFAIK it's set in the config.

I don't know why I have the weird thing in my head that says let's wait for git to change the default so that it really is a new standard default branch name (FWIW they could absolutely settle on a different default than main and now the whole world is stuck with it), but it's absolutely any project's decision to use anything as their default branch.

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
what would this do in terms of backward compatibility, though?
