### ISSUE TITLE
Stuck: "Your old project requires credentials for read-only access."  When importing into GitHub?

### ISSUE THREAD

**Issue by jscottelblein** [go-gitea/gitea#15636]
First time I'm trying to do this and am stuck in a loop trying to import a repo I have on my self-hosted Gitea.

I'm passing the repo  URL like this:

  `https://my.gitea.repo/gitea/Scott/Dark-Nord-Material-Theme-for-WallaBag.git`

I then enter my Gitea credentials, and it just loops right back to the same screen, as seen below:

![image](https://user-images.githubusercontent.com/1524526/116231800-f539de80-a71e-11eb-87a6-3b3a1fab924f.png)

I thought perhaps I was entering the wrong creds, and it wanted my GH creds instead, so I entered those: same result.

What am I doing wrong?

Currently using the latest Gitea as of this post, on Docker.

**Comment by KN4CK3R** [comment]
Your gitea instance is reachable from the internet?

**Comment by STaRDoGG** [comment]
> Your gitea instance is reachable from the internet?

Yep

**Comment by STaRDoGG** [comment]
Turns out I needed to set:

`REQUIRE_SIGNIN_VIEW = false` in my `app.ini`.

Think it has to do with my having 2FA enabled (not sure, but whatever).

**Comment by 6543** [comment]
@STaRDoGG it is, if you have 2FA enabled basicAuth do not work for git-clone/api

the way to go would be to create a **token** witch can be created specific for one purpose if done right
