### ISSUE TITLE
linux服务器编译报错recipe for target "public/fomantic/semantic.min.js"failed

### ISSUE THREAD

**Issue by LIUMING32** [go-gitea/gitea#15633]
代码是ssh拉取到linux服务器（无外网），执行编译报错recipe for target "public/fomantic/semantic.min.js"failed，请问大佬有没有建议？

**Comment by a1012112796** [comment]
Translation:

question:
when build gitea on a linux server without internet connection, It will failed with error ``recipe for target "public/fomantic/semantic.min.js"failed``. so how to build gitea on on a linux server without internet connection?
Thanks.

/cc @silverwind

**Comment by silverwind** [comment]
Not sure what's going on but if this is 1.13, try a `touch public/fomantic/semantic.min.js`. It should certainly not be an issue in 1.14 or higher.

**Comment by lunny** [comment]
@LIUMING32 @a1012112796 we need more details. OS, gitea version and etc.

**Comment by zeripath** [comment]
Without the requested information we cannot help you. If this is still an issue please reopen with the requested information.
