### ISSUE TITLE
Integration with Cockpit

### ISSUE THREAD

**Issue by hwpplayer1** [go-gitea/gitea#15632]
I would like to serve an integration with Cockpit source code, like graphical monitoring on Monitoring Section Gitea Site Administration

Also do you mind to open Discussions section for topics like i point to ? 

And please create templates for any need 

See you there

**Comment by 6543** [comment]
@hwpplayer1 do you mean https://cockpit-project.org/ ?

**Comment by techknowlogick** [comment]
How do you see "integration" with cockpit looking like? If you want shared users, Gitea already supports things like PAM,LDAP, and even more that Cockpit also uses. If you mean providing the monitoring that Cockpit uses in Gitea, their codebase is mostly C(?) which means that we couldn't just import it.

**Comment by hwpplayer1** [comment]
If we or I can not import, I can write better and better
