### ISSUE TITLE
Feature request: Go to file

### ISSUE THREAD

**Issue by BLumia** [go-gitea/gitea#15639]
## Description

GitHub has a decent feature named "Go to file" which can be handy when using the web UI to quickly searching and browsing a file. It's very useful if the project has a very deep hierarchy of files and you need to find one of them to browse the content. It could be great to have this feature built-in in Gitea.

## Screenshots

![GitHub's Go to file button](https://user-images.githubusercontent.com/10095765/116261163-f49a5a00-a7a9-11eb-9945-185f9cdd8770.png)

![GitHub's Go to file page while searching a file](https://user-images.githubusercontent.com/10095765/116261098-e8160180-a7a9-11eb-9cd0-8fdb54775713.png)

**Comment by lunny** [comment]
duplicated with #12638
