### ISSUE TITLE
Due Date Format for Milesones

### ISSUE THREAD

**Issue by tcpluess** [go-gitea/gitea#15635]
The date formats for milestones are inconsistent.
For the due date, the mm/dd/yyyy format is used, whereas the normal yyyy-mm-dd is used in the milestones overview.
There should be an option to change the date format.

- Gitea version (or commit ref): 1.14.1
- Git version: 2.30.2
- Operating system: Linux
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (any repo)
  - [ ] No
- Log gist:

## Description

...

![image](https://user-images.githubusercontent.com/16662475/116228614-cc810b80-a755-11eb-9174-4f1c5ad46ba0.png)

![image](https://user-images.githubusercontent.com/16662475/116228663-e02c7200-a755-11eb-9b9e-09f0f7dcc119.png)

**Comment by silverwind** [comment]
The date input is locale-aware but our date/time rendering is not. This will require a big overhaul of our timestamp rendeirng and would likely require it to be done in JavaScript, like Github already does.

**Comment by tcpluess** [comment]
OK I can understand that this change will not happen in the near future. However on the other hand we could argue that there is an actual ISO standard about how dates should be written:

https://en.wikipedia.org/wiki/ISO_8601

in that case it would not be necessary to use locale-aware date/time format, one could just stick to the ISO standard.

**Comment by silverwind** [comment]
I think generally we want to render timestamps in relative format (which should be locale-independent strings) with absolute date in a tooltip (which can be locale-dependant).

**Comment by yardenshoham** [comment]
Fixed in #23988?

**Comment by silverwind** [comment]
I'd say so as we now render in the user's OS preference.

**Comment by delvh** [comment]
Isn't this issue actually talking about #24055 which was never merged and should thus be reopened?

**Comment by lunny** [comment]
It's another date format used for due dates.

**Comment by yardenshoham** [comment]
#24055 was replaced by https://github.com/go-gitea/gitea/pull/24275 so I think we can close it
