### ISSUE TITLE
User name reserved

### ISSUE THREAD

**Issue by jscolaire** [go-gitea/gitea#15647]
- Gitea version (or commit ref): docker image gitea/gitea:1.14.1 but fails in some versions (1.11.0+dev-11-g1e9b33052 1.12.6 )
- Git version: 
- Operating system: linux
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
- Log gist:

2021/04/28 09:23:18 ...dels/login_source.go:717:UserSignIn() [W] Failed to login 'js' via 'ipa': name is reserved [name: js]

## Description

User name *js* is reserved. It's indifferent if authetication source is LDAP or local. I have an user with js as user name.
...

## Screenshots

![2021-04-28_12-16](https://user-images.githubusercontent.com/1184251/116389229-023cf780-a81d-11eb-842b-9c89ab2dfa0d.png)

**Comment by a1012112796** [comment]
waiting https://github.com/go-gitea/gitea/pull/15219

**Comment by richmahn** [comment]
Fixed via #15219

**Comment by jscolaire** [comment]
I don't understand, I'm sorry. In #15219 I don't read about reserved user names, only about root or admin.

In this case I'm speaking about an user name called *js*. Why is it reserved word?.

Thanks
