### ISSUE TITLE
Closing issue with a commit on changed default branch.

### ISSUE THREAD

**Issue by terokorp** [go-gitea/gitea#15648]
- Gitea version (or commit ref): 1.14.1 / Docker image gitea/gitea:1, 95c811f7bc1e
- Git version: 
- Operating system: Debian 10.8, Docker version 20.10.5, build 55c4c88
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes https://try.gitea.io/thasan/bugtest/branches
  - [ ] No
- Log gist:
I will provide logs later when I and our gitea server have time to do so.

## Description
Closing issue with a commit doesn't work when default branch is changed. although on my local install I was able to close issue merging closing commit to master at some point (develop was set to default branch) but didn't get event that work on try.gitea.io
https://try.gitea.io/thasan/bugtest/branches

...

## Screenshots

![firefox_iUol73baf5](https://user-images.githubusercontent.com/1323257/116390567-dc1c5500-a826-11eb-9606-b2181c035dda.png)
Issue 40, with 2 attempt to close it with a commit. Branch is set to develop

![firefox_W8s46HqZeY](https://user-images.githubusercontent.com/1323257/116390887-2b628580-a827-11eb-8c50-b57662bedee1.png)
Default branch is develop

![firefox_FyK6MVrVPr](https://user-images.githubusercontent.com/1323257/116391475-e2f79780-a827-11eb-837b-8d3ea21ef7ab.png)
"closes" keyword has underline (not so visible on ss, sorry about theme) so it is detected and issue number link works.
before "closes" keyword has a space, but its not here on commit graph

**Comment by noerw** [comment]
I can't follow, please describe step-by-step how to reproduce this issue

**Comment by zeripath** [comment]
Without the requested information we cannot help you. If this remains an issue please answer @noerw and reopen this issue.
