### ISSUE TITLE
Settings section oauth2_client is not working

### ISSUE THREAD

**Issue by kzinas-adv** [go-gitea/gitea#15660]
- Gitea version (or commit ref): v1.14.1
- Git version: 2.30.2
- Operating system: Centos 8.3;  Binary from releases 
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x ] No
- Log gist:

## Description

It looks file  modules/setting/oauth2_client.go is missing in  release v1.14.1
Settings section oauth2_client is not working.

## Screenshots

[domas@x1 gitea]$ git log --name-status HEAD^..HEAD
commit 918d3d96ff30670f0b63d99698d76dab434ba833 (HEAD, tag: v1.14.1)
Author: 6543 <6543@obermui.de>
Date:   Fri Apr 16 04:19:09 2021 +0200

    Changelog v1.14.1 (#15498)
    
    * RAW Changelog v1.14.1
    
    * wordings
    
    * Apply suggestions from code review
    
    Co-authored-by: techknowlogick <matti@mdranta.net>
    
    * Update CHANGELOG.md
    
    Co-authored-by: 6543 <6543@obermui.de>
    
    * Update CHANGELOG.md
    
    Co-authored-by: 6543 <6543@obermui.de>
    
    Co-authored-by: techknowlogick <matti@mdranta.net>
    Co-authored-by: Lunny Xiao <xiaolunwen@gmail.com>
    Co-authored-by: techknowlogick <techknowlogick@gitea.io>

        M       CHANGELOG.md

     [domas@x1 gitea]$  git diff-tree --no-commit-id --name-only -r 55eb1745bd5427c6f84f77703a580d580ac379b3
     custom/conf/app.example.ini
     docs/content/doc/advanced/config-cheat-sheet.en-us.md
     models/migrations/migrations.go
     models/migrations/v179.go
     modules/auth/oauth2/oauth2.go
     modules/setting/oauth2_client.go
     modules/setting/setting.go
     routers/user/auth.go
     routers/user/auth_openid.go
     [domas@x1 gitea]$ ls -ltr modules/setting/oauth2_client.go
     ls: cannot access 'modules/setting/oauth2_client.go': No such file or directory
     [domas@x1 gitea]$ 

###############################################################################

     [domas@x1 gitea_lastest]$  git log --name-status HEAD^..HEAD
     commit d7dbe4feebac7805a4ca184f0989f58de8063d96 (HEAD -> master, origin/master, origin/HEAD)
     Author: Lunny Xiao <xiaolunwen@gmail.com>
     Date:   Thu Apr 29 04:22:54 2021 +0800
          
         Fix readme render bug (#15649)
     
          M       routers/repo/view.go
     [domas@x1 gitea_lastest]$  git diff-tree --no-commit-id --name-only -r 55eb1745bd5427c6f84f77703a580d580ac379b3
     custom/conf/app.example.ini
     docs/content/doc/advanced/config-cheat-sheet.en-us.md
     models/migrations/migrations.go
     models/migrations/v179.go
     modules/auth/oauth2/oauth2.go
     modules/setting/oauth2_client.go
     modules/setting/setting.go
     routers/user/auth.go
     routers/user/auth_openid.go
     [domas@x1 gitea_lastest]$ ls -ltr modules/setting/oauth2_client.go
     -rw-rw-r--. 1 domas domas 3355 Apr 29 13:13 modules/setting/oauth2_client.go
     [domas@x1 gitea_lastest]$

**Comment by zeripath** [comment]
Sorry I think this was missed. I don't think the oauth2_client was included in 1.14.1 but in any case the 1.15.6 has already been released so I'm going to close this as out-of-date.
