### ISSUE TITLE
[Bug] [Doctor] db consistency fix function not working

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#15668]
doctor **check-db-consistency** task use `models.DeleteOrphanedObjects()` witch does not work

ref: https://github.com/go-gitea/gitea/pull/15658#issuecomment-829474478

tested with `mariadb Ver 15.1`

gitea v1.13.7, v1.14.1 & master have same issue:

v13: `Error: Unsupported type`
v14&master: ` - [C] Error: %!v(MISSING) whilst deleting orphaned objects`

**Comment by KN4CK3R** [comment]
`%!v(MISSING)` should be fixed by #15658 and the underlaying bug in `models.DeleteOrphanedObjects()` gets fixed with #15657.
