### ISSUE TITLE
[FEATURE] Filedrop Directory Should Zip

### ISSUE THREAD

**Issue by kdumontnu** [go-gitea/gitea#15665]
## Description
When dragging a directory into attachments we currently upload all files individually. 

Instead, I believe gitea should zip the files if a directory is selected.

**Comment by lunny** [comment]
Or we can prompt user to chose one.

**Comment by jackghg** [comment]
why zip ?

**Comment by kdumontnu** [comment]
I'm closing this because I'm not sure there is general interest.
