### ISSUE TITLE
[BUG] Error Tooltip Blocks Remove File

### ISSUE THREAD

**Issue by kdumontnu** [go-gitea/gitea#15662]
- Gitea version (or commit ref): master (1.15.0+dev-192-gd7dbe4fee)
- Operating system: Windows, Chrome, Firefox
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes: https://try.gitea.io/kdumontnu/test/releases/edit/test (drag more than 5 files in dropzone)
  - [ ] No

## Description
If more than 5 files (and possibly with other errors), the tooltip drops down and blocks "Remove File", so user is stuck refreshing the page to continue.

## Screenshots
![blocked_remove](https://user-images.githubusercontent.com/12700993/116577286-923a7a00-a8cd-11eb-8ce3-4374c2960449.gif)

Essentially, we built this 😄:
![CluelessEssentialAplomadofalcon-size_restricted](https://user-images.githubusercontent.com/12700993/116577847-155bd000-a8ce-11eb-8684-fd3963b01425.gif)

**Comment by silverwind** [comment]
I think those tooltips are positioned by Dropzone itself so might be a bug there.

**Comment by kdumontnu** [comment]
> I think those tooltips are positioned by Dropzone itself so might be a bug there.

We apply our own styling in https://github.com/go-gitea/gitea/blob/master/web_src/less/features/dropzone.less

I need to check if deleting these overrides would fix it. Otherwise, yeah it might be an upstream issue.

**Comment by silverwind** [comment]
Try removing this one. I'm not sure of its purpose but we probably should not mess with it.

```css
.dropzone .dz-error-message {
  top: 120px !important;
}
```

**Comment by kdumontnu** [comment]
> Try removing this one. I'm not sure of its purpose but we probably should not mess with it.
> 
> ```css
> .dropzone .dz-error-message {
>   top: 120px !important;
> }
> ```

I just deleted everything and it's still pretty bad (though you can actually click the url between the dialog now):

![image](https://user-images.githubusercontent.com/12700993/116620504-28d35f00-a8ff-11eb-8db1-4109580080bd.png)

**Comment by silverwind** [comment]
Seems like a good enough solution. I recently refactored this and it might be that change have moved the tooltip.
