### ISSUE TITLE
404 on logout when LANDING_PAGE=login

### ISSUE THREAD

**Issue by yanlusu** [go-gitea/gitea#15673]
- Gitea version (or commit ref): 1.14.1
- Git version: 2.20.1
- Operating system: Linux raspberrypi 5.10.17-v7l+ #1403 SMP Mon Feb 22 11:33:35 GMT 2021 armv7l GNU/Linux
- Install binary Link: https://github.com/go-gitea/gitea/releases/download/v1.14.1/gitea-1.14.1-linux-arm-6
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x]  No
- Log gist:
  I canot change try.gitea.io configuration to using login as homepage.
## Description
1. using login as homepage;
   ```bash
   # ${gitea_home}/custom/conf
   [server]
   LANDING_PAGE     = login
   ```

2. start gitea;
3. visit homepage, and login;
4. click some repository;
5. click right upper account icon, select "logout" from dropdown menu;
6. 404 return;
...

## Screenshots
this issue can be reproduced.

**Comment by qwerty287** [comment]
Maybe the repository is private? Then you can't access it after logging out.

**Comment by zeripath** [comment]
Although I think I now understand how to replicate this issue - it really would have been much more helpful if you could have provided logs.

**Comment by yanlusu** [comment]
> Although I think I now understand how to replicate this issue - it really would have been much more helpful if you could have provided logs.

Tonight, I want to reproduce this issue, but using other computer in my home(last time using the one in the office), but annoying, I changed log level to debug and restart server, it cannot be reproduced. 
So, I think maybe the reason is browser cache?
I will temporary close this issue, and remaining log level to debug; when it occured again, I will issue log with it.

**Comment by yanlusu** [comment]
> Maybe the repository is private? Then you can't access it after logging out.

Yes, it's private repository, but it just only for me, and I can access it, promise :)
