### ISSUE TITLE
Graph results in 500 error after upgrade

### ISSUE THREAD

**Issue by hauke68** [go-gitea/gitea#15692]
- Gitea version (or commit ref): 1.14.1
- Git version: 2.1.4
- Operating system: Debian, gitea runs as downloaded binary, started by SysV
  
  
  
- Database (use `[x]`):
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL): 
  - [X] No
- Log gist: https://gist.github.com/hauke68/bab3c33fba4f81d5dff295357cdb0e28

## Description

I upgraded gitea from 1.13.0 via 1.13.7 to 1.14.1 and after that, calling the graph results in a 500 error. See https://opengit.hauke-zuehl.de/hauke/Skripte/graph for an example.

Never had problems before.

**Comment by zeripath** [comment]
Already fixed and backported. See #15517 & #15530 should be v1.14.2
