### ISSUE TITLE
Github owns NPM now with future integrations to come - what would Gitea NPM (PHP/Python/etc) support look like?

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#15706]
This is more of a discussion than a feature request.

In terms of supporting NPM repos, it looks like Github and NPM could potentially merge.  Github has announced better integrations between their platform and NPM.

For me it's a no brainer and could allow Gitea to support other repository types (python, go, PHP, node) if it was provided as a plugin or architecture which allows it.  They are all similar in terms of what they do - build, tag, host, publishing.

Do we want Gitea to have this?

To support an NPM (or other repository types)  what would be needed?

**Comment by lafriks** [comment]
There is already work in this direction #14919
