### ISSUE TITLE
Branch Protection Impossible For New Repositories

### ISSUE THREAD

**Issue by muellert** [go-gitea/gitea#15705]
- Gitea version (or commit ref): 1.14.1
- Git version: n/a
- Operating system: n/a
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)  any, really
  - [ ] No
- Log gist:

## Description

If I create a new repository, it is initially empty. In this case, I cannot set up branch protection, at least not via the UI.

Maybe templating could work around this?

...

## Screenshots

![20210503-gitea-repo-in-use](https://user-images.githubusercontent.com/1183079/116870044-afdb4c80-ac09-11eb-9788-46b0e5fc2730.png)
![20210503-gitea-new-repo](https://user-images.githubusercontent.com/1183079/116870050-b36ed380-ac09-11eb-88ec-b43585c69e89.png)

**Comment by KN4CK3R** [comment]
I noticed that too while implementing #15629 but did not add that restriction there. At the moment you must select an existing branch to enable branch protection. As an empty repository does not have branches that tab is stripped. #2529 might want this too.

**Comment by lunny** [comment]
Fixed by #20825
