### ISSUE TITLE
[Feature Request] option to disable animations

### ISSUE THREAD

**Issue by qwerty287** [go-gitea/gitea#15709]
Hello,
Gitea has almost everywhere animations: the "Create" menu, the issue preview...
The problem is, I don't like these animations, I think they're a bit disturbing. So, I think it would be nice if there's an option in the settings to disable these animations.
Thanks!

Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes
  - [ ] No

**Comment by silverwind** [comment]
I generally find the animations obnoxious too. Here is a very crude method of doing it, certainly not something we should commit like that:

```css
* { 
  animation-duration: 0ms !important;
}
```

**Comment by jtran** [comment]
I, personally, like animations.  But perhaps support could be added for the OS preference, which browsers expose in CSS as [prefers-reduced-motion](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion).  It can also be accessed in JS.

**Comment by yukijoou** [comment]
Seems like this is controlled by the package 'fomatic-ui' used by gitea. I have [reported the issue upstream](https://github.com/fomantic/Fomantic-UI/issues/2872)
