### ISSUE TITLE
Docs: Potential color theme tweaks

### ISSUE THREAD

**Issue by pat-s** [go-gitea/gitea#15711]
In my opinion the red-coloured code text is quite dominant and a bit too large.

I've taken a stab and aligned the text theming to GitHub ones. 

Please 👍/👎 if you would like to see a change.

## Changes

- Reduced font size from `0.875em` to `0.85em`
- Added `border-radius: 6px;`
- Changed padding from `0.25em 0.5em 0.25em;` to `.2em .4em;`
- Set font color to `#24292e;`

## Current

![image](https://user-images.githubusercontent.com/8430564/116919918-4895ba80-ac52-11eb-9e0c-92993b2bf714.png)

## New

Navbar background: `#f4f4f4`
![image](https://user-images.githubusercontent.com/8430564/117252589-7b080900-ae46-11eb-97e5-8c8762d968de.png)

# Link color

Another change, which could maybe be discussed separately, is the link color.
Here I also think that (#528321`) is actually more pleasant to the eyes than the current one.

Here's a preview of the proposed change:

![image](https://user-images.githubusercontent.com/8430564/117253122-26b15900-ae47-11eb-95dd-c89c18b5a0fd.png)

----

pull: https://gitea.com/gitea/theme/pulls/95

**Comment by zeripath** [comment]
Whilst I agree that the red colour at present is a bit glaring I think your change is too dark. Have you tried a dark burgundy?

**Comment by silverwind** [comment]
Looking good. As for green, I suggest `#609926` which is also used in the gitea logo.

**Comment by silverwind** [comment]
`#609926` on `#ffffff` is 3.45:1
`#2ea44f` on `#ffffff` is 3.21:1

Both colors fail the [WCAG AAA requirement](https://webaim.org/resources/contrastchecker/) of contrast ratio of 7 thought.

**Comment by pat-s** [comment]
Ok, here's the next try

```css
code {
    background-color: #ecf0f1;
    color: black;
    font-size: 0.85em;
    font-weight: normal;
    padding: .2em .4em;
    border-radius: 6px;
}
```

Also the body font is `black` here and the background `#ecf0f1`.

The green tone is `#528321`.

![image](https://user-images.githubusercontent.com/8430564/117013095-d70c4980-acef-11eb-919a-cc3211eb970b.png)

**Comment by silverwind** [comment]
I like it except the blueish header which seems a bit out of place but I see that color is also used on the frontpage, so it's a more involved change. Also, I would not use `black` body text because it seems to harsh of a color against white, maybe `#333` instead.

**Comment by pat-s** [comment]
I also do not like the blue. I could think of a general recoloring using a greyish tone and `#528321` (maybe the green tone of the gitea logo to stay consistent).

## Main page

Navbar background: `#f4f4f4`

![image](https://user-images.githubusercontent.com/8430564/117252589-7b080900-ae46-11eb-97e5-8c8762d968de.png)


## Docs

With `#333` as the body font and `#f8f8f8` as the navbar background.

![image](https://user-images.githubusercontent.com/8430564/117253122-26b15900-ae47-11eb-95dd-c89c18b5a0fd.png)

**Comment by silverwind** [comment]
Looks great imho :)

**Comment by 6543** [comment]
did you update the issue description screenshots with the current look @pat-s ?

**Comment by pat-s** [comment]
No, the current looks can be seen in the last comment which contains screenshots. Otherwise some comments would not make sense anymore which refer to the first proposals.

**Comment by 6543** [comment]
will update it then :)

**Comment by 6543** [comment]
@silverwind will need review at https://gitea.com/gitea/theme/pulls/95 :)

**Comment by silverwind** [comment]
PR is merged, but it does not seem to be live yet.

**Comment by techknowlogick** [comment]
@silverwind that's my bad, I hadn't updated CI secrets so it didn't publish. I've resolved that and next PR merged to this repo will update theme.

**Comment by pat-s** [comment]
Thanks!

I was expecting the theme change to apply to all sites, albeit only the docs were updated. Might need to look again.

**Comment by techknowlogick** [comment]
@pat-s Docs are our only site that gets update frequently, although I had run the website CI too https://gitea.io/en-us/ I'll rebuild blogs as well.
