### ISSUE TITLE
Avatars missing after recent upgrade (47fd15693)

### ISSUE THREAD

**Issue by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [go-gitea/gitea#15727]
- Gitea version (or commit ref): `1.15.0+dev-223-g47fd15693`
- Git version: built from `next`, not pertaining to this issue
- Operating system: Arch Linux
- Database:
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] haven't tried

## Description
After upgrading to a commit merged by #15301 user-supplied user avatars won't load and org avatars won't load at all.
org avatars that should load from gravatar are looked for locally and end up 404ing

## Screenshots
users:
![image](https://user-images.githubusercontent.com/61180606/117079822-dbab1f00-ad3c-11eb-833b-3163f9b9fd6a.png)

orgs:
![image](https://user-images.githubusercontent.com/61180606/117079740-abfc1700-ad3c-11eb-8eae-2ae27402c6a4.png)

**Comment by zeripath** [comment]
Sorry I think I must have missed pushing a commit up. PR up.
