### ISSUE TITLE
Upgrade Failure from v1.13.6 to v1.14.1

### ISSUE THREAD

**Issue by 2ral** [go-gitea/gitea#15726]
- Gitea version (or commit ref): 1.14.1
- Git version: 1.8.3.1
- Operating system: Centos 7.0. Using the pre-built gitea binary from releases. Gitea running under systemd.
- Database:
  - [ ] PostgreSQL
  - [x] MySQL   5.5.68-MariaDB
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No

Hello I am suffering from update failure after replacing the gitea binary v1.13.6 with v1.14.1.
Seems like the new binary had messed up with database somehow.

2021/05/04 21:44:08 ...dules/setting/log.go:333:newLogService() [I] Gitea Log Mode: File(File:info)
2021/05/04 21:44:08 ...dules/setting/log.go:250:generateNamedLogger() [I] Router Log: Console(console:info)
2021/05/04 21:44:08 ...les/setting/cache.go:73:newCacheService() [I] Cache Service Enabled
2021/05/04 21:44:08 ...les/setting/cache.go:88:newCacheService() [I] Last Commit Cache Service Enabled
2021/05/04 21:44:08 ...s/setting/session.go:77:newSessionService() [I] Session Service Enabled
2021/05/04 21:44:08 ...s/storage/storage.go:158:initAttachments() [I] Initialising Attachment storage with type:
2021/05/04 21:44:08 ...les/storage/local.go:47:NewLocalStorage() [I] Creating new Local Storage at /var/lib/l2gitea/data/attachments
2021/05/04 21:44:08 ...s/storage/storage.go:152:initAvatars() [I] Initialising Avatar storage with type:
2021/05/04 21:44:08 ...les/storage/local.go:47:NewLocalStorage() [I] Creating new Local Storage at /var/lib/l2gitea/data/avatars
2021/05/04 21:44:08 ...s/storage/storage.go:170:initRepoAvatars() [I] Initialising Repository Avatar storage with type:
2021/05/04 21:44:08 ...les/storage/local.go:47:NewLocalStorage() [I] Creating new Local Storage at /var/lib/l2gitea/data/repo-avatars
2021/05/04 21:44:08 ...s/storage/storage.go:164:initLFS() [I] Initialising LFS storage with type:
2021/05/04 21:44:08 ...les/storage/local.go:47:NewLocalStorage() [I] Creating new Local Storage at /var/lib/l2gitea/data/lfs
2021/05/04 21:44:08 routers/init.go:150:GlobalInit() [I] SQLite3 Supported
2021/05/04 21:44:08 routers/init.go:68:initDBEngine() [I] Beginning ORM engine initialization.
2021/05/04 21:44:08 routers/init.go:75:initDBEngine() [I] ORM engine initialization attempt #1/10...
2021/05/04 21:44:08 ...om/urfave/cli/app.go:524:HandleAction() [I] PING DATABASE mysql
2021/05/04 21:44:08 ...ations/migrations.go:357:Migrate() [I] [SQL] SELECT `TABLE_NAME` from `INFORMATION_SCHEMA`.`TABLES` WHERE `TABLE_SCHEMA`=? and `TABLE_NAME`=? [l2gitea version] - 4.010939ms
2021/05/04 21:44:08 models/models.go:220:NewEngine() [I] [SQL] SELECT `COLUMN_NAME` FROM `INFORMATION_SCHEMA`.`COLUMNS` WHERE `TABLE_SCHEMA` = ? AND `TABLE_NAME` = ? AND `COLUMN_NAME` = ? [l2gitea version id] - 3.18519ms
2021/05/04 21:44:08 models/models.go:220:NewEngine() [I] [SQL] SELECT `COLUMN_NAME` FROM `INFORMATION_SCHEMA`.`COLUMNS` WHERE `TABLE_SCHEMA` = ? AND `TABLE_NAME` = ? AND `COLUMN_NAME` = ? [l2gitea version version] - 4.638688ms
2021/05/04 21:44:08 ...rm.io/xorm/engine.go:1130:Get() [I] [SQL] SELECT `id`, `version` FROM `version` WHERE `id`=? LIMIT 1 [1] - 767.624µs
2021/05/04 21:44:08 ...ations/migrations.go:394:Migrate() [I] Migration[159]: update reactions constraint
2021/05/04 21:44:08 models/models.go:220:NewEngine() [I] [SQL] BEGIN TRANSACTION [] - 250.468µs
2021/05/04 21:44:08 ...s/migrations/v159.go:33:updateReactionConstraint() [I] [SQL] CREATE TABLE IF NOT EXISTS `tmp_recreate__reaction` (`id` BIGINT(20) PRIMARY KEY AUTO_INCREMENT NOT NULL, `type` VARCHAR(255) NOT NULL, `issue_id` BIGINT(20) NOT NULL, `comment_id` BIGINT(20) NULL, `user_id` BIGINT(20) NOT NULL, `original_author_id` BIGINT(20) DEFAULT 0 NOT NULL, `original_author` VARCHAR(255) NULL, `created_unix` BIGINT(20) NULL) DEFAULT CHARSET utf8mb4 ROW_FORMAT=DYNAMIC [] - 2.971163ms
2021/05/04 21:44:08 ...s/migrations/v159.go:33:updateReactionConstraint() [I] [SQL] CREATE UNIQUE INDEX `UQE_tmp_recreate__reaction_s` ON `tmp_recreate__reaction` (`type`,`issue_id`,`comment_id`,`user_id`,`original_author_id`,`original_author`) [] - 249.455µs
2021/05/04 21:44:08 ...ations/migrations.go:447:recreateTable() [E] Unable to create uniques for table tmp_recreate__reaction. Error: Error 1071: Specified key was too long; max key length is 767 bytes
2021/05/04 21:44:08 ...ations/migrations.go:397:Migrate() [I] [SQL] ROLLBACK [] - 170.11µs
2021/05/04 21:44:08 routers/init.go:81:initDBEngine() [E] ORM engine initialization attempt #1/10 failed. Error: migrate: do migrate: Error 1071: Specified key was too long; max key length is 767 bytes
2021/05/04 21:44:08 routers/init.go:82:initDBEngine() [I] Backing off for 3 seconds
2021/05/04 21:44:11 ...eful/manager_unix.go:127:handleSignals() [W] PID 13686. Received SIGTERM. Shutting down...
2021/05/04 21:44:11 .../graceful/manager.go:217:doHammerTime() [W] Setting Hammer condition
2021/05/04 21:44:11 routers/init.go:157:GlobalInit() [F] ORM engine initialization failed: Aborted due to shutdown:
        in retry ORM engine initialization
2021/05/04 21:45:27 ...dules/setting/log.go:333:newLogService() [I] Gitea Log Mode: File(File:info)
2021/05/04 21:45:27 ...dules/setting/log.go:250:generateNamedLogger() [I] Router Log: Console(console:info)
2021/05/04 21:45:27 ...les/setting/cache.go:73:newCacheService() [I] Cache Service Enabled
2021/05/04 21:45:27 ...les/setting/cache.go:88:newCacheService() [I] Last Commit Cache Service Enabled
2021/05/04 21:45:27 ...s/setting/session.go:77:newSessionService() [I] Session Service Enabled
2021/05/04 21:45:27 ...s/storage/storage.go:158:initAttachments() [I] Initialising Attachment storage with type:
2021/05/04 21:45:27 ...les/storage/local.go:47:NewLocalStorage() [I] Creating new Local Storage at /var/lib/l2gitea/data/attachments
2021/05/04 21:45:27 ...s/storage/storage.go:152:initAvatars() [I] Initialising Avatar storage with type:
2021/05/04 21:45:27 ...les/storage/local.go:47:NewLocalStorage() [I] Creating new Local Storage at /var/lib/l2gitea/data/avatars
2021/05/04 21:45:27 ...s/storage/storage.go:170:initRepoAvatars() [I] Initialising Repository Avatar storage with type:
2021/05/04 21:45:27 ...les/storage/local.go:47:NewLocalStorage() [I] Creating new Local Storage at /var/lib/l2gitea/data/repo-avatars
2021/05/04 21:45:27 ...s/storage/storage.go:164:initLFS() [I] Initialising LFS storage with type:
2021/05/04 21:45:27 ...les/storage/local.go:47:NewLocalStorage() [I] Creating new Local Storage at /var/lib/l2gitea/data/lfs
2021/05/04 21:45:28 routers/init.go:150:GlobalInit() [I] SQLite3 Supported
2021/05/04 21:45:28 routers/init.go:68:initDBEngine() [I] Beginning ORM engine initialization.
2021/05/04 21:45:28 routers/init.go:75:initDBEngine() [I] ORM engine initialization attempt #1/10...
2021/05/04 21:45:28 ...om/urfave/cli/app.go:524:HandleAction() [I] PING DATABASE mysql
2021/05/04 21:45:28 ...ations/migrations.go:357:Migrate() [I] [SQL] SELECT `TABLE_NAME` from `INFORMATION_SCHEMA`.`TABLES` WHERE `TABLE_SCHEMA`=? and `TABLE_NAME`=? [l2gitea version] - 90.338347ms
2021/05/04 21:45:28 models/models.go:220:NewEngine() [I] [SQL] SELECT `COLUMN_NAME` FROM `INFORMATION_SCHEMA`.`COLUMNS` WHERE `TABLE_SCHEMA` = ? AND `TABLE_NAME` = ? AND `COLUMN_NAME` = ? [l2gitea version id] - 7.089183ms
2021/05/04 21:45:28 models/models.go:220:NewEngine() [I] [SQL] SELECT `COLUMN_NAME` FROM `INFORMATION_SCHEMA`.`COLUMNS` WHERE `TABLE_SCHEMA` = ? AND `TABLE_NAME` = ? AND `COLUMN_NAME` = ? [l2gitea version version] - 2.741804ms
2021/05/04 21:45:28 ...rm.io/xorm/engine.go:1130:Get() [I] [SQL] SELECT `id`, `version` FROM `version` WHERE `id`=? LIMIT 1 [1] - 9.82632ms
2021/05/04 21:45:28 ...ations/migrations.go:394:Migrate() [I] Migration[159]: update reactions constraint
2021/05/04 21:45:28 models/models.go:220:NewEngine() [I] [SQL] BEGIN TRANSACTION [] - 1.793286ms
2021/05/04 21:45:28 ...s/migrations/v159.go:33:updateReactionConstraint() [I] [SQL] CREATE TABLE IF NOT EXISTS `tmp_recreate__reaction` (`id` BIGINT(20) PRIMARY KEY AUTO_INCREMENT NOT NULL, `type` VARCHAR(255) NOT NULL, `issue_id` BIGINT(20) NOT NULL, `comment_id` BIGINT(20) NULL, `user_id` BIGINT(20) NOT NULL, `original_author_id` BIGINT(20) DEFAULT 0 NOT NULL, `original_author` VARCHAR(255) NULL, `created_unix` BIGINT(20) NULL) DEFAULT CHARSET utf8mb4 ROW_FORMAT=DYNAMIC [] - 13.994248ms
2021/05/04 21:45:28 ...s/migrations/v159.go:33:updateReactionConstraint() [I] [SQL] CREATE UNIQUE INDEX `UQE_tmp_recreate__reaction_s` ON `tmp_recreate__reaction` (`type`,`issue_id`,`comment_id`,`user_id`,`original_author_id`,`original_author`) [] - 1.744552ms
2021/05/04 21:45:28 ...ations/migrations.go:447:recreateTable() [E] Unable to create uniques for table tmp_recreate__reaction. Error: Error 1071: Specified key was too long; max key length is 767 bytes
2021/05/04 21:45:28 ...ations/migrations.go:397:Migrate() [I] [SQL] ROLLBACK [] - 162.766µs
2021/05/04 21:45:28 routers/init.go:81:initDBEngine() [E] ORM engine initialization attempt #1/10 failed. Error: migrate: do migrate: Error 1071: Specified key was too long; max key length is 767 bytes
2021/05/04 21:45:28 routers/init.go:82:initDBEngine() [I] Backing off for 3 seconds
2021/05/04 21:45:31 routers/init.go:75:initDBEngine() [I] ORM engine initialization attempt #2/10...

Then the log is repeated. Any advices how to fix it? Sadly I have no backup of gitea instance so installing from scratch is not an option for me :(

**Comment by zeripath** [comment]
Error 1071: Specified key was too long; max key length is 767 bytes

**Comment by zeripath** [comment]
https://docs.gitea.io/en-us/faq/#upgrade-errors-with-mysql

**Comment by zeripath** [comment]
https://github.com/go-gitea/gitea/issues/15540#issuecomment-822761650

**Comment by 2ral** [comment]
Where I try to convert the database using gitea convert I still face-up with similar error

2021/05/04 22:33:54 cmd/convert.go:42:runConvert() [F] Failed to convert database from utf8 to utf8mb4: Error 1071: Specified key was too long; max key length is 767 b
