### ISSUE TITLE
[FEATURE] User watch notification settings

### ISSUE THREAD

**Issue by kdumontnu** [go-gitea/gitea#15743]
This is a superset of #15742.

In GitHub a user can configure the extent they would like to be notified in watched repos. Gitea should add the option at least for "Participating and @mentions", "All Activity", and "Ignore".
![image](https://user-images.githubusercontent.com/12700993/117222440-a3512280-adc8-11eb-840d-14bb9fb53139.png)

The default setting should be configurable as a user setting, repo setting, org setting, and/or config setting.

**Comment by a1012112796** [comment]
Maybe duplicate with https://github.com/go-gitea/gitea/issues/11120.
