### ISSUE TITLE
Can not override default logo and favicon.

### ISSUE THREAD

**Issue by Aleksei-Badyaev** [go-gitea/gitea#15752]
- Gitea version (or commit ref): 1.15.0+dev-221-g21465a2ce built with GNU Make 4.3, go1.16.3 : bindata, timetzdata, sqlite, sqlite_unlock_notify
- Git version: 2.30.2
- Operating system: use docker image gitea/gitea:latest-rootless
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
- Log gist:
[gitea.log](https://github.com/go-gitea/gitea/files/6436939/gitea.log)

## Description
I can serve aditional content, but cannot override Gitea content (favicon or default logo for example).

**Comment by a1012112796** [comment]
see https://docs.gitea.io/en-us/customizing-gitea/#changing-the-logo

**Comment by Aleksei-Badyaev** [comment]
I followed the instructions exactly. I looked at the project code and it looks like there is a bug. Can I also fix the bug and create a pull-request?

**Comment by a1012112796** [comment]
> I followed the instructions exactly. I looked at the project code and it looks like there is a bug. Can I also fix the bug and create a pull-request?

Welcome

**Comment by Aleksei-Badyaev** [comment]
In fact, there is no bug in the code (well, except a bit inefficient - each static file is processed twice if it is not in custom). The documentation, however, incorrectly describes the process of customizing the logo and favicon.
