### ISSUE TITLE
Repositories w/ capital letters in their names show up as unadopted

### ISSUE THREAD

**Issue by emichael** [go-gitea/gitea#15755]
- Gitea version (or commit ref): 1.14.1 (Docker)
- Git version: N/A
- Operating system: N/A
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  I don't have admin access on that instance.
- Log gist: Nothing in logs

## Description

1. Create a repository through the web interface with capital letters in its name.
2. Go to the admin interface, Repositories, Unadopted Repositories, Search
3. That repository will show up in the list, even though it's already imported into Gitea.

## Screenshots

![image](https://user-images.githubusercontent.com/1312141/117368455-69d7f000-ae78-11eb-8e9e-a89208ec28c5.png)
![image](https://user-images.githubusercontent.com/1312141/117368560-8b38dc00-ae78-11eb-8d64-5394d7c3a898.png)

**Comment by zeripath** [comment]
Gitea does not create repositories with capital names, non bare or repositories without the terminal .git. It can only adopt repositories that look like they were made by it.

If we adopted repositories that did not meet those requirements there would be multiple issues.

The rules for adoption are strict and necessarily so.

**Comment by zeripath** [comment]
Oh sorry I got the wrong end of the stick here!

**Comment by emichael** [comment]
It's very likely just a missing `toLower()` or some such function when matching existing repo names in Gitea against filesystem names. Probably a one line fix.

**Comment by zeripath** [comment]
https://github.com/go-gitea/gitea/blob/ab77a24f18ae45248bd6c71778fe3bfacacf864f/modules/repository/adopt.go#L231

**Comment by zeripath** [comment]
Feel free to put up a PR. The rest of the code is doing the correct thing - that one sneaked through by accident.
