### ISSUE TITLE
completely delete a issue

### ISSUE THREAD

**Issue by samuelortion** [go-gitea/gitea#15763]
Is there a way to completely delete a closed issue on web interface, or tea command line ?
We faced a set of spam issues and wanted to not only close them but also delete them completely from the repository.
Thank you in advance for your help.

**Comment by 6543** [comment]
@OrnithOrtion not posible yes via WEB or API, you have to delete it via SQL commands manualy :/

best practise for now is: to rename title & body if it is due to spam or something similar ...

**Comment by 6543** [comment]
depends on #15599

**Comment by 6543** [comment]
duplicate to #923
