### ISSUE TITLE
CSS bug with too long file path in the pull requests

### ISSUE THREAD

**Issue by ndaidong** [go-gitea/gitea#15760]
This is just a small CSS bug, happens with chromium based browsers.

When the file path is too long,  it will show as below (tested on Chrome, Vivaldi, Opera):

![Screenshot from 2021-05-07 10-34-35](https://user-images.githubusercontent.com/1809619/117395428-17530e00-af22-11eb-95d8-cbbf5f0f3832.png)

Firefox pushes remaining text to the second line:

![Screenshot from 2021-05-07 10-29-28](https://user-images.githubusercontent.com/1809619/117395647-87fa2a80-af22-11eb-9c86-009147945676.png)

**Comment by zeripath** [comment]
So this may be ok on 1.15:

https://try.gitea.io/arandomer/pathological/pulls/25#issuecomment-84723

Although it's not perfect:

https://try.gitea.io/arandomer/pathological/pulls/25/files#issuecomment-84723
