### ISSUE TITLE
[Feature Request] Translate keywords like 'close'

### ISSUE THREAD

**Issue by qwerty287** [go-gitea/gitea#15771]
Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No

## Description
Hello, 
it would be nice if keywords like 'close' that can be used to close issues with a comment on a PR/Commit could be translated. Even it most projects are in English language and you can write 'close' in every language, it would be a nice addition. Thanks!

**Comment by techknowlogick** [comment]
It is possible that the translations haven't been provided here: https://crowdin.com/project/gitea and a fallback is used.

**Comment by zeripath** [comment]
@techknowlogick I think they meant `CLOSE_KEYWORDS`

@qwerty287  see:

https://docs.gitea.io/en-us/config-cheat-sheet/#repository---pull-request-repositorypull-request

We don't translate by default as it would be a very long keyword list and likely cause significant numbers of false positives.
