### ISSUE TITLE
confusing simplified Chinese translation for "Set Email Preference"

### ISSUE THREAD

**Issue by BruceKangCN** [go-gitea/gitea#15786]
- Gitea version (or commit ref): 1.14.1
- Git version: 2.25.1
- Operating system: Ubuntu 20.04
  
  
  
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL) https://try.gitea.io/user/settings/account
  - [ ] No
- Log gist:

## Description

The simplified Chinese Translation of "Set Email Preference" is confusing.
I sugguest changing it to "更新邮件偏好" or "更新邮件通知设置".

## Screenshots

![QQ截图20210508162435](https://user-images.githubusercontent.com/43891241/117533129-9f6a0e00-b01d-11eb-9828-7d876efbbec9.jpg)
![QQ截图20210508162457](https://user-images.githubusercontent.com/43891241/117533133-a7c24900-b01d-11eb-8679-c309f8daf79b.jpg)

**Comment by lunny** [comment]
Please go to https://crowdin.com/translate/gitea/68/enus-zhcn?filter=basic&value=0 to change it.
