### ISSUE TITLE
Implement OAuth2 PROVIDER

### ISSUE THREAD

**Issue by tboerger** [go-gitea/gitea#158]
We need to implement an OAuth2 provider, not the consumer we already have for some platforms, with that third party tools like Drone can use the repositories quite easy. This works even for multiple repos at once without the need to provide deploy keys. Here you can see an explanation of Github how they did it: https://github.com/blog/1270-easier-builds-and-deployments-using-git-over-https-and-oauth

The library https://github.com/RangelReale/osin looks pretty promising for providing this functionality, we "just" need some models and a management UI for that :)

**Comment by techzilla** [comment]
With http://openid.net/connect/ identity layer?  does osin support the new standards?

**Comment by tboerger** [comment]
Project is dead, close.
