### ISSUE TITLE
Edit a file directly?

### ISSUE THREAD

**Issue by jscottelblein** [go-gitea/gitea#15814]
I'm using the  current   latest version  within docker.

Is there a way to edit a file right  form the web ui (as there is in GH) and I'm just missing it?

If there isn't, can it be added? Sometimes it's just a lot more convenient to do it that way.

Here's GH's for example, when viewing a .css file in a repo (the pencil icon).
![image](https://user-images.githubusercontent.com/1524526/117602904-60b87e80-b117-11eb-9500-f64f9bcbdd5b.png)

**Comment by jolheiser** [comment]
It's in pretty much the same spot, with the same icon, assuming you have write access to that repo.

![Screenshot from 2021-05-09 22-51-24](https://user-images.githubusercontent.com/42128690/117603600-2819a480-b119-11eb-9a28-283d932ad71a.png)

**Comment by STaRDoGG** [comment]
@jolheiser ok, I see what the problem was. That particular repo is a mirror of a gh repo, so it doesn't offer the edit directly button. My bad.
