### ISSUE TITLE
Upgraded from 1.12.6 => 1.14.2 now getting 500 error - pq: could not read block 0 in file "base/16384/16409": read only 0 of 8192 bytes

### ISSUE THREAD

**Issue by nodesocket** [go-gitea/gitea#15810]
- Gitea version (or commit ref): `1.14.2`
- Operating system: `Kubernetes / Docker`
  
I am running Gitea in Kubernetes so the following Docker image https://hub.docker.com/layers/gitea/gitea/1.14/images/sha256-91f81ed3bbd607a4f3ad71f84e6a8c82b3987d08a7b9bdaeab341c010cdea303?context=explore. Installed via the [Helm chart](https://gitea.com/gitea/helm-chart/) and using the default PostgreSQL backend.

I just upgraded from version `1.12.6`, but now after logging in I see a 500 error and:

```
An error has occurred:

pq: could not read block 0 in file "base/16384/16409": read only 0 of 8192 bytes
Gitea Version: 1.14.2
```

Any ideas or troubleshooting I can perform?

**Comment by nodesocket** [comment]
**Update:** Just looked at the log files for Gitea and see:

```
2021/05/09 23:36:15 ...ules/auth/sso/sso.go:89:SessionUser() [E] GetUserById: pq: column "keep_activity_private" does not exist
```

Maybe I am missing a database migration?

**Comment by lunny** [comment]
For your second comment, I think you missed v141 migration which will add a column named `keep_activity_private`
