### ISSUE TITLE
[Bug] Deleting text disables recommendations

### ISSUE THREAD

**Issue by delvh** [go-gitea/gitea#15837]
- Gitea version (or commit ref): 1.15.0+dev-274-g143071ee4 and every single one below
- Can you reproduce the bug at https://try.gitea.io: Yes 

## Description
When a user enters text that requests recommendations (either the emoji `:`, the user mentioning `@` or maybe later on the issue linking `#` syntax), recommendations will not get updated after text has been deleted from the input (i.e. removing the `e` from `:smile` ). This means the recommendations popup will be frozen in place, not changing for any input.
There are currently two ways to force the menu to close:
A) The textarea loses focus
B) Every part of the recommendation requesting input gets deleted (i.e. even the `:` of `:smile`)

It would be nice if the recommendations would also get updated when text is deleted and afterwards.

## Screenshots

![Screenshot_20210511_235746](https://user-images.githubusercontent.com/51889757/117890058-c8580080-b2b4-11eb-95b1-6dc1b05903aa.png)
In this screenshot, I entered `:smile`, then replaced it with `:build`. As you can see, the menu did not get updated and is now frozen.

**Comment by wxiaoguang** [comment]
Resolved by https://github.com/go-gitea/gitea/pull/23985  ?

**Comment by delvh** [comment]
Yup.
Finally. I had a feeling when reviewing that PR that I missed an issue that is fixed by it :smiley:
