### ISSUE TITLE
[mirror] option protect mirror from commit removals (like branchprotection deny force push)

### ISSUE THREAD

**Issue by UmutAlihan** [go-gitea/gitea#15843]
There was a case when an RPA tool is sold to another company and they revert to closed sourced licensing model while they are fully open and free. In this context they removed every single source code and commit history from their repositories and only left a readme file.  ([repo link](https://github.com/automagica/automagica))

Most of RPA developers using automagica as their base tool have lost reach to source code and commit history in related repo. Some had the chance of having a local offline copy of the codebase and saved their robots in action. 

However, What happens if I had a Gitea mirror repo to this remote and they would remove all commit history and source code. Do we lose all the codebase once the cronjob is triggered to sync mirror repositories?  Is there anything to avoid that? Is having a regular repository only option to avoid this risk of losing codebase caused by closing remote repo?

Cheers

**Comment by 6543** [comment]
short: yes in default mirror config

long: you can tell gitea to not remove old refs if they got deleted from source. This should safe souch thungs. But i didnt test it ...

**Comment by UmutAlihan** [comment]
Many thanks for your answer and beautifying my issue!

**Comment by 6543** [comment]
@UmutAlihan you can just disable mirror sync cron tab and do it manualy ...but i think it's not optimal

**Comment by UmutAlihan** [comment]
could you please provide an example app.ini line to only disable cron mirror sync w/out messing other regular cronjobs? It would really be very kind p2p act :)

(fyi I used docker-compose to spin up my gitea server)

**Comment by 6543** [comment]
@UmutAlihan -> https://docs.gitea.io/en-us/config-cheat-sheet/#cron---update-mirrors-cronupdate_mirrors 
`ENABLED = false`

**Comment by yoyoyonas** [comment]
I'd suggest to close this duplicate in favor of #14076.
