### ISSUE TITLE
Some users report broken font starting with Gitea 1.14

### ISSUE THREAD

**Issue by fnetX** [go-gitea/gitea#15844]
- Gitea version (or commit ref): starting with 1.14
- Operating system: different
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes, already at https://try.gitea.io/JonasFranzDEV/drone-gitea-release/issues/2

## Description
Forwarded from Codeberg https://codeberg.org/Codeberg/Community/issues/444 :
Multiple users reported issues with fonts in different browsers where some versions work, some don't. Especially affected are Emojis, two users (one in the issue, another one via Mastodon) reported that numbers were missing in the fonts. Please find the original report at the URL above, additionally I'll copy some relevant information here.

> | ***browser*** | Gitea 1.13.6 | Gitea 1.14.1 |
> |---|---|---|
> | Firefox | works | works |
> | Tor Browser (not ver 10.0.16) | works | broken |
> | Ungoogled Chromium | works | broken |
> 
> ---
> 
> However I noticed that noticed on Tor Browser that numbers don't render. var(--fonts-emoji) as a font on the root element seems to be the culprit.
> 
> ---
> 
> Tor Browser 10.0.16 works but I heard someone else using TB complain that the symbols were boxes.

If you can, please join the discussion over at Codeberg, since some users don't want to use Microsoft GitHub. Otherwise, I can forward the discussion, but please expect high delay.

Thank you for investigating this.

## Screenshots

![Screenshot, emojis are only rendered as rectangular boxes](https://codeberg.org/attachments/79697d32-49b4-4c0b-aae3-685394a6aa9e)
> This is what it looks like in Ungoogled Chromium 72.0.3626:

![Numbers missing](https://codeberg.org/attachments/58af1b40-6aee-4774-b2f2-0b6dbf184e0c)
> However I noticed that noticed on Tor Browser that numbers don't render. var(--fonts-emoji) as a font on the root element seems to be the culprit.

**Comment by zeripath** [comment]
I suspect the issue is that the user does not have an emoji font installed. We previously would provide it as a webfont but it was thought that this was unnecessary.

In most cases downloading and install noto color emoji fonts would fix the problem.

**Comment by fnetX** [comment]
Downstream closed as invalid ... Can you still have a look at https://codeberg.org/Codeberg/Community/issues/445 (the missing numbers issue)? Was reported twice and seems much more relevant than missing emoji.

**Comment by zeripath** [comment]
This just doesn't make any sense - why would non emoji numbers be affected?

I think we need to see a screenshot of an actual issue that is occuring.

---

If it's just the font rendering issue because the emoji font isn't being provided, well one option for codeberg is to just edit the `custom/header.tmpl` to include a `<style>` that adds (I think this is correct - adjust as necessary): (for 1.14.x)

```html
<style>
    @font-face {
     font-family: 'Noto Color Emoji';
     src: url('/NotoColorEmoji.eot'); /* IE9 Compat Modes */
     src: url('/NotoColorEmoji.eot?#iefix') format('embedded-opentype'), /* IE6-IE8 */
       url('/NotoColorEmoji.woff2') format('woff2'), /* Super Modern Browsers */
       url('/NotoColorEmoji.woff') format('woff'), /* Pretty Modern Browsers */
       url('/NotoColorEmoji.ttf')  format('truetype'), /* Chrome, Safari, Android, iOS */
       url('/NotoColorEmoji.svg#svgFontName') format('svg'); /* Legacy iOS */
    }
</style>
```

and then add the font files to the `public/` directory. (for 1.15.x the urls should be `/assets/NotoColorEmoji.*` - again I think this is correct.)

**Comment by n194** [comment]
> > This is what it looks like in Ungoogled Chromium 72.0.3626:

The screenshot is actually from Tor Browser 10.0.16 (based on Mozilla Firefox 78.10.0esr)

**Comment by fnetX** [comment]
I put the quotes below the screenshot, sorry for the confusion.
And thank you, @zeripath for stepping in.

**Comment by fnetX** [comment]
The mentioned pull fixes the most pressing issue with a still supported browser. The other issue is free for further investigation, but only seems to affect outdated Ungoogled Chromium on oldoldstable Debian and only Emoji instead of more-relevant numbers.
