### ISSUE TITLE
Display problem in blame

### ISSUE THREAD

**Issue by mlpo** [go-gitea/gitea#15858]
- Gitea version (or commit ref): 1.15.0+dev-265-ge5723d655
- Git version: N/A
- Operating system: N/A
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes (see screenshot)
  - [ ] No
- Log gist: N/A

## Description

There is a shift (which intensifies when the file grows) between the code and authors in blame page.

## Screenshot

Taken from https://gitea.com/gitea/git/blame/commit/e03eb393a2224110a4e3fde279bf67ae1ecd3b34/MAINTAINERS:
![blame_gitea](https://user-images.githubusercontent.com/1258839/118148649-108c3580-b411-11eb-91a5-3233a1b4d1af.PNG)

**Comment by silverwind** [comment]
Can someone check if 1.14 is affected?

**Comment by mlpo** [comment]
@silverwind it is. My personnal instance is 1.14 and is affected.

**Comment by zeripath** [comment]
yup can confirm.
