### ISSUE TITLE
[Bug] Delete Repo Fails On Windows

### ISSUE THREAD

**Issue by kdumontnu** [go-gitea/gitea#15864]
- Gitea version (or commit ref): 1.15.0+dev-285-g6a8e5f69c
- Git version:
- Operating system: Windows
  
  
  
- Database (use `[x]`):
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X] No
- Log gist:
```
2021/05/13 13:45:45 models/admin.go:87:removeAllWithNotice() [W] Delete repository files [C:\Users\<user>\Documents\5 - Software Development\gitea\data\gitea-repositories\test\lfs_demo.git]: remove C:\Users\<user>\Documents\5 - Software Development\gitea\data\gitea-repositories\test\lfs_demo.git: The process cannot access the file because it is being used by another process.
2021/05/13 13:45:45 ...s/context/context.go:692:1() [D] Session ID: 7b2e3c9790a33b69
```

## Description

Gitea cannot seem to delete a repo on Windows. The contents of the directory are removed, but the .git repo directory root is left behind. This results in a collision if you try to create another repo with the same name.

Appears to work fine on v1.14.

## Screenshots

Says the repository was successfully deleted.
![image](https://user-images.githubusercontent.com/12700993/118185031-4d4c3280-b3f9-11eb-9b55-401f9a4f8d45.png)

Collision when creating a repo with the same name
![image](https://user-images.githubusercontent.com/12700993/118185124-6654e380-b3f9-11eb-8a69-32da4f2f41b2.png)

**Comment by zeripath** [comment]
it'll be due to the open git repo.
