### ISSUE TITLE
Unable to create internal queue for push_update Error (Docker Swarm)

### ISSUE THREAD

**Issue by TheSilkky** [go-gitea/gitea#15879]
- Gitea version (or commit ref):  1.15.0+dev-303-gb6b8b194c
- Git version: 2.30.2
- Operating system: docker-swarm mode (Docker version 20.10.6)
  
  
  
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
- Log gist:
  ```
  2021/05/15 08:09:49 ...ueue_disk_channel.go:144:Run() [F] Unable to create internal queue for push_update Error: Unable to create queue level for push_update with cfg queue.LevelQueueConfiguration{ByteFIFOQueueConfiguration:queue.ByteFIFOQueueConfiguration{WorkerPoolConfiguration:queue.WorkerPoolConfiguration{QueueLength:20, BatchLength:20, BlockTimeout:1000000000, BoostTimeout:300000000000, BoostWorkers:1, MaxWorkers:5}, Workers:0, Name:"push_update-level"}, DataDir:"/data/gitea/queues/push_update", ConnectionString:"", QueueName:""} by max attempts: error: resource temporarily unavailable
  ```
[Full server logs](https://bin.snopyta.org/?792d861770a7deda#CvT9C5sM98BnzTRtJR8DAfsQgZBSEtw5UPdYMUxTw6qr)
[app.ini](https://bin.snopyta.org/?e27dc2b9e3a047e1#2S6Xvt1wK9PvhNAtMq73kAM2WtYTfTSuBFBijE6mP5eC)

## Description

[docker-compose](https://bin.snopyta.org/?ab5e575306c3f2f8#FaceKvrqX37m9Y5KRK7dsSHgRkFdKr5oBnYnYQr6PiS7)
Gitea is accessible from the web-ui and everything appears to work fine, but regularly a "bad gateway" error appears, after looking in the logs you can see ```Unable to create internal queue for push_update Error: Unable to create queue level for push_update with cfg``` and shortly after ```Received signal 15; terminating```. The container crashes.

Extra details:
- Postgres is running on only 1 node. The others communicate with it over an overlay network.
- I'm using GlusterFS to store the persistent Gitea data.

## Screenshots
![Cluster diagram](https://i.postimg.cc/HkHkKrZ8/cluster.png)

**Comment by zeripath** [comment]
```
 resource temporarily unavailable
```

implies that the directory `/data/gitea/queues/push_update` cannot be accessed.

**Comment by TheSilkky** [comment]
> ```
>  resource temporarily unavailable
> ```
> 
> implies that the directory `/data/gitea/queues/push_update` cannot be accessed.

Might be a permissions problems with the mounted data directory. Ill have a look when I have time, thanks

**Comment by techknowlogick** [comment]
You have multiple processes accessing the queue simultaneously, please consider using redis as a queue manager. Currently HA/multi-home is not thoroughly documented and so please refer to the HA ticket for more details.
