### ISSUE TITLE
Not enough space in the Start Timer button for certain translations

### ISSUE THREAD

**Issue by emansije** [go-gitea/gitea#15896]
- Gitea version (or commit ref): 1.14.2 (although other versions might be affected as well)
- Git version: 2.27.0
- Operating system: Kubuntu 20.10
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (https://try.gitea.io/emansije/teste/issues/3 when language is set to European Portuguese (*Português de Portugal*))
  - [ ] No
- Log gist:

## Description

The "Start Timer" button of the Time Tracker in the editing issue page doesn't have enough space for the European Portuguese translation for the word "Timer" (*"cronómetro"*), but I've noticed that other languages have the same issue, like German, Spanish and Turkish.

The left and right padding of the button text is 1.5em. Perhaps making it 1.2em would solve the issue.

## Screenshots

As it is now:

![Screenshot_20210516_134806](https://user-images.githubusercontent.com/602233/118398202-7e25a500-b64f-11eb-9299-1655aa3b9265.png)

After making the left and right padding 1.2em:

![Screenshot_20210516_135015](https://user-images.githubusercontent.com/602233/118398203-7ebe3b80-b64f-11eb-8aa5-cc206b268c58.png)

**Comment by silverwind** [comment]
There is just not enough space for two side-by-side buttons, let's make it 2 rows:

<img width="222" alt="image" src="https://user-images.githubusercontent.com/115237/118400154-b84b7280-b660-11eb-840f-c8d1ef5a5e86.png">
