### ISSUE TITLE
Allow to serve (repo-)avatars statically

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#15898]
- Gitea version (or commit ref): 1.13.7
- Git version: 2.31.1
- Operating system: Arch Linux
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
  - [x] Irrelevant
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Irrelevant
- Log gist: Irrelevant

## Description

Currently, there are issues with `data/avatars` and `data/repo-avatars` folders and their files (`user:group` is set to `gitea:gitea`, for repo-avatars files, umask is set to restrictive 077), so it is impossible to serve images using caching web server (unless running everything from root user).

## Screenshots

Irrelevant

**Comment by silverwind** [comment]
Avatars should already be cached well using `STATIC_CACHE_TIME`, why do you want to serve them separately?

**Comment by intereal** [comment]
> Avatars should already be cached well using `STATIC_CACHE_TIME`, why do you want to serve them separately?

I mean sending files from server, not client side caching. Calling gitea embedded webserver for static files is less efficient comparing to sending via nginx.

**Comment by silverwind** [comment]
Hmm indeed, I think avatars have to come from the gitea webserver currently, so that is a valid concern.

**Comment by intereal** [comment]
> I think avatars have to come from the gitea webserver currently

Why? Avatars are just files, and if they are stored locally, I see no issues with offloading static requests to caching web server. Similar option is already available for static resources like scripts, styles, fonts etc.

**Comment by silverwind** [comment]
IDK, but I guess we could make them world-readable to allow such configurations.

**Comment by techknowlogick** [comment]
This is possible currently by using the CDN setting of gitea and pointing it at a host that fetches the files from disk which nginx could do.
