### ISSUE TITLE
Create OSS Crowdin project

### ISSUE THREAD

**Issue by tboerger** [go-gitea/gitea#159]
@lunny please register a free opensource Crowdin project to get better support for updating the i18n files for our needs.

**Comment by tboerger** [comment]
I already crreated one but it needs to be transfered to an OSS plan: https://crowdin.com/project/gitea

**Comment by lunny** [comment]
I think we could resolve translation question when #51 has been resolved. And before that, since gogs has a crowdin, maybe gitea doesn't need one.

**Comment by tboerger** [comment]
IMHO it still makes sense to use crowdin as well as we will reach much more translators

**Comment by lunny** [comment]
OKay.

**Comment by lunny** [comment]
Just use https://crowdin.com/project/gitea?

**Comment by tboerger** [comment]
Yes, i want to use that, but it's currently not registered as an OSS project and have to be payed after one month. We need to register it as an opensource project to get this service for free.

**Comment by tboerger** [comment]
Project is dead, close.
