### ISSUE TITLE
Customization files should not require /assets path segment

### ISSUE THREAD

**Issue by silverwind** [go-gitea/gitea#15906]
Since https://github.com/go-gitea/gitea/pull/15219, previous customization files like `$GITEA_CUSTOM/public/img/logo.svg` are not loaded any more and require `$GITEA_CUSTOM/public/assets/img/logo.svg` to be loaded again, we should fix this because the `assets` segment should only be relevant on HTTP, not in the file system.

**Comment by silverwind** [comment]
@a1012112796 fyi.

**Comment by lunny** [comment]
I think this has been resolved by #15961 .

**Comment by silverwind** [comment]
Yeah, just rebuilt with that, seems to have been resolved.
