### ISSUE TITLE
Issues with the comment section in Windows Server

### ISSUE THREAD

**Issue by Sabdix** [go-gitea/gitea#15917]
Hi.
## Description
In the comment section for releases and pull request, it shows a line full of xxxxxxxxx nad doesn't show the style like it did before. In Addittion to that the cursor is always above the text i'm writing, so it's impossible to know where you are in the text.
Plus when the text its to large, it overflows the limits of the comment section looking like this:

## Screenshots
![image](https://user-images.githubusercontent.com/32939564/118665557-02933780-b7b8-11eb-80b9-c089f4516e87.png)

- Gitea version (or commit ref):
- Git version: 1.14.2
- Operating system:
  Windows Server 2012
  Running as a service
- Database
  -MySQL
- Can you reproduce the bug?
  - [ X] No

**Comment by silverwind** [comment]
Is that using IE? If so, you need to install another browsers, we don't support IE any more.

**Comment by Sabdix** [comment]
It is with Microsoft Edge

**Comment by Sabdix** [comment]
And Chrome

**Comment by Sabdix** [comment]
> Is that using IE? If so, you need to install another browsers, we don't support IE any more.

It is with edge and chrome

**Comment by Sabdix** [comment]
This is the version 1.14.1.
I installed the 1.14.2 version in my local computer and the issue persists
![image](https://user-images.githubusercontent.com/32939564/119991884-9078da80-bf8f-11eb-9a24-72df740cc906.png)

**Comment by Sabdix** [comment]
Here is another example

![image](https://user-images.githubusercontent.com/32939564/119992047-be5e1f00-bf8f-11eb-9489-d1d6a8c8b620.png)

**Comment by Sabdix** [comment]
Here is from the configuration site
![image](https://user-images.githubusercontent.com/32939564/120389526-25623780-c2f2-11eb-954b-53f795513484.png)

**Comment by silverwind** [comment]
Rebuild your frontend files, e.g. `rm -rf public/js && make frontend`, 1.14 does not have a simplemde.min.js, only easymde.js:

https://github.com/go-gitea/gitea/blob/release/v1.14/webpack.config.js#L59-L62

**Comment by Sabdix** [comment]
Thnks that solves it!!!!
