### ISSUE TITLE
Add possibility to make new branches in web interface

### ISSUE THREAD

**Issue by Viktor-Yakovchuk** [go-gitea/gitea#15911]
- Gitea version (or commit ref): commit c3aaf5eafd91b881ca67ab51e0cc2fd17a5b7921
- Database (use [x]):
    - [ ] PostgreSQL
    - [ ] MySQL
    - [ ] MSSQL
    - [X] SQLite

Description:
---
There is the possibility to make a commit with some changes but there are no the possibility to make a new branch. The equivalent to
`git checkout -b new_branch_name`
Adding this feature will case changes only it templates and adding new js handler because all we need at backend is in the code now.

This is new look of branch in branches page:
![image](https://user-images.githubusercontent.com/20933795/118400276-94d8f580-b669-11eb-9b2c-a6525130b9df.png)

This is new form for setting name of new branch:
![image](https://user-images.githubusercontent.com/20933795/118408896-5f93ce00-b690-11eb-94b5-889b0d364684.png)

**Comment by jolheiser** [comment]
You can create a branch from the UI, however there is no button on the branches page.

Are you intending for this issue to be a feature request for the latter?

![branching](https://user-images.githubusercontent.com/42128690/118539865-919b4380-b715-11eb-9c24-17e3a92589ce.png)

**Comment by Viktor-Yakovchuk** [comment]
I can send pull request with a code I recently have written.
