### ISSUE TITLE
Personal Access Tokens no longer work with https when 2fa is turned on.

### ISSUE THREAD

**Issue by musicislife08** [go-gitea/gitea#15919]
- Gitea version (or commit ref): 1.15.0+dev-322-g3e068fcdc built with GNU Make 4.3, go1.16.4 : bindata, timetzdata, sqlite, sqlite_unlock_notify
- Git version: 2.27.0 and 2.31.1
- Operating system: Official Docker Image
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
- Log gist:
https://gist.github.com/musicislife08/1dfa6cc8975edfd80a01023162aca415

## Description
I am not sure what changed however after a recent update I can no longer use my Personal Access Token to pull from my repo while 2fa is turned on like all of the documentation says I should be able to do however it always returns the following even with a brand new token.

using ~git clone https://username:token@repo.domain/org/repo.git` or any other command no longer works as it used to.
This does the same on the try.gitea.io site after turning on 2fa.  This feature used to work however im not sure why its not allowing the use of the pat anymore.

```bash
git pull
remote: Users with two-factor authentication enabled cannot perform HTTP/HTTPS operations via plain username and password. Please create and use a personal access token on the user settings page
fatal: Authentication failed for 'repourlhere'
```

The above gist includes the debug logs from both the git file and from the docker container logs.

**Comment by Projekt95** [comment]
This was a Bug in #15303 and got fixed with #15915.
Try to update your Gitea. The new Docker Image including the Fix has also been rolled out.
I tested the Token Auth successfully again in 1.15.0+dev-325-g370cfde35
