### ISSUE TITLE
FR: Creating a repo from a template repo via API

### ISSUE THREAD

**Issue by pat-s** [go-gitea/gitea#15934]
As title.

Needed to implement a CLI command (`tea repo create --template`) as in https://gitea.com/gitea/tea/issues/362.

**Comment by jolheiser** [comment]
> @pat-s maybe #12942 is what you need.

No, he's referring to using the API to create a repo _from_ an existing template afaik.

**Comment by a1012112796** [comment]
okay, I see. ref https://docs.github.com/en/rest/reference/repos#create-a-repository-using-a-template
I think this is a ``good first issue``.
