### ISSUE TITLE
nginx reverse proxy with subpath documentation not valid nginx syntax

### ISSUE THREAD

**Issue by gabevenberg** [go-gitea/gitea#15931]
This is what works for me for `http://domain.com/git/` (running nginx/1.16.1 and Gitea version 1.8.3+2-g11f6ed4f8 built with go1.12.6 : bindata, sqlite, sqlite_unlock_notify):

```
server {
    listen 80;
    server_name domain.com ;

location /git/ {
    proxy_pass http://localhost:3000/;
    }
}
```

Without the trailing slash on proxy_pass everything was 404.

_Originally posted by @defulmere in https://github.com/go-gitea/gitea/issues/8635#issuecomment-625485258_

when using the above in an nginx config, nginx gives me the following error:
nginx: [emerg] "proxy_pass" cannot have URI part in location given by regular expression, or inside named location, or inside "if" statement, or inside "limit_except" block in /etc/nginx/locations/venberg.xyz_sites/gitea:2
using @donpdonp 's inital solution worked perfectly.

only issue now is that mydomain.xyz/git/ works, but mydomain.xyz/git (without trailing space) gives a 404 error.

**Comment by pat-s** [comment]
The [docs as of today](https://docs.gitea.io/en-us/reverse-proxies/#nginx-with-a-sub-path) already have this trailing slash added.
Did not check when it was added.

**Comment by zeripath** [comment]
sounds like this fixed then.
