### ISSUE TITLE
git clone over ssh, gitea log says user does not exist.

### ISSUE THREAD

**Issue by gabevenberg** [go-gitea/gitea#15944]
- Gitea version (or commit ref):
- Git version:
- Operating system:
  
  
  
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
- Log gist:

on server side (journalctl /usr/bin/local/gitea)
```
May 21 19:53:00 gittea gitea[6005]: 2021/05/21 19:53:00 Started GET /api/internal/serv/command/1/git:gabe/resume?mode=1&verb=git-upload-pack for [::1]:47464
May 21 19:53:00 gittea gitea[6005]: 2021/05/21 19:53:00 ...ters/private/serv.go:108:ServCommand() [E] Unable to get repository owner: git:gabe/resume Error: user does not exist [uid: 0, name
May 21 19:53:00 gittea gitea[6005]: 2021/05/21 19:53:00 Completed GET /api/internal/serv/command/1/git:gabe/resume?mode=1&verb=git-upload-pack 500 Internal Server Error in 1.815752ms
```
client side (git clone ssh://git@venberg.xyz/git:Gabe/lidarutils.git)
```
Cloning into 'lidarutils'...
Gitea: Internal Server Error
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
## Description

...

**Comment by lunny** [comment]
Your git clone format is wrong. it should be `ssh://git@venberg.xyz/Gabe/lidarutils.git` or `git@venberg.xyz:Gabe/lidarutils.git`

**Comment by Gabe-Venberg** [comment]
Ahh, I see it. just a PEBKAC issue. (Problem Exists Between Keyboard And Chair)
