### ISSUE TITLE
once again custome logo/settings

### ISSUE THREAD

**Issue by badsmoke** [go-gitea/gitea#15953]
- Gitea version (or commit ref): latest docker
- Git version:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x ] Yes (provide example URL)
  - [ ] No

## Description

the questions came up already the one and other time, but no answer could help me.

I would like to customize my gitea docker installation, specifically the log and the default page.

as custom path is set /data/gitea/

i tried to create a folder custom, public, img and others in any order. but nothing helped.

**Comment by techknowlogick** [comment]
The custom path is /data/gitea/ you don't need to create a specific custom folder. So if you want to create a folder for templates it'd be /data/gitea/template etc...

More info here: https://docs.gitea.io/en-us/install-with-docker/#customization https://docs.gitea.io/en-us/customizing-gitea/
