### ISSUE TITLE
Q: How to recover Pull Requests in a restored repository?

### ISSUE THREAD

**Issue by brettwooldridge** [go-gitea/gitea#15969]
- Gitea version: 1.14.2
- Git version: Whatever is built into the docker image
- Operating system: Running from a docker under Ubuntu
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite

## Description
We experienced disk corruption in our main git repository due to a hard reset of the system. We had an up-to-date clone on a developer machine, so we created a bare clone and uploaded it to the gitea server, in place of the corrupted one.

After bringing gitea back up, at first everything seemed intact. However, looking at pull requests, we can tell that something is broken. "This pull request is broken due to missing fork information."  See the screen shot below.

All repositories, i.e. the one that the pull request is *from*, as well as the one that it is *to* (the formerly corrupt one), reside in the same gitea instance. We have 25 open Pull Requests currently, so deleting and submitting them all, from different developers, would be quite tedious.

Is there any way to rebuild/relink the pull request information so that the main repository is whole again?

## Screenshots
<img width="512" alt="Screen Shot 2021-05-25 at 1 05 23" src="https://user-images.githubusercontent.com/1538661/119375477-d0249580-bcf5-11eb-875c-743d0d26d6f0.png">

**Comment by noerw** [comment]
What's missing very likely is the git refs to the PR branches. They should reside in the repo's tree at `refs/pull/<idx>/head`.
Not sure if there's a built in way to recover them, re-opening the PRs seems easier than manually merging them into the bare repo..
Also you need to re-sync the git hooks (admin dashboard -> "Resynchronize pre-receive, update and post-receive hooks of all repositories.")

**Comment by brettwooldridge** [comment]
@noerw Thanks, I did run the resynchronize task.  One of the things that gave me pause before deleting the PRs was [this comment](https://github.com/go-gitea/gitea/issues/13321#issuecomment-717391982), where upon deleting the PR and trying to re-open they reported: "This pull request cannot be reopened because the branch was deleted." (of course the branch is not deleted)

Thanks again.
