### ISSUE TITLE
gitea lfs not Enabled

### ISSUE THREAD

**Issue by ebenmo** [go-gitea/gitea#15966]
- Gitea version (or commit ref): 1.14.2
- Git version: 1.8.3.1
- Operating system: centos 7.7
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
- Log gist:

## Description

LFS Configuration is disabled, new repo can't upload lfs file.
However, when i open web first time, i have filled lfs path, but it did not work.
And I have check app.ini, LFS_START_SERVER is true.

## Screenshots

![Dingtalk_20210524192529](https://user-images.githubusercontent.com/7875807/119340987-d6028280-bcc5-11eb-8aee-4545df540569.jpg)
![Dingtalk_20210524192703](https://user-images.githubusercontent.com/7875807/119341176-0ba76b80-bcc6-11eb-8390-89714bce16f6.jpg)

**Comment by a1012112796** [comment]
hello, your git version is too low to support lfs

**Comment by ebenmo** [comment]
@a1012112796 thanks a lot, I can't find lfs setup requirements in gitea docs, but when I updated git version to 2.3 and now lfs is working.
