### ISSUE TITLE
[Bug] Deleted commits are visible and inaccessible, if they are referenced in an issue

### ISSUE THREAD

**Issue by ExceptionGit** [go-gitea/gitea#15974]
- Gitea version (or commit ref): 1.14.2
- Git version: 2.30.2
- Operating system: docker gitea/gitea:1.14.2
  
  
  
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not tried

## Description

After #13674 and `git gc --prune=now` in container: deleted commits still visible in the issue where they are referenced, but inaccessible "Page Not Found 404".

- `WEB UI -> Garbage collect all repositories` - has finished without fix
- `gitea doctor --run check-db-consistency --fix` - showed ok without fix

**Comment by noerw** [comment]
related: #13694

**Comment by ExceptionGit** [comment]
I think this is a bug, issue/pull/dashboard history stay in inconsistent state after `gc`.

**Comment by colejohnson66** [comment]
Still a bug on 1.20.2.

**Comment by lunny** [comment]
Maybe this commit should become disabled state.

**Comment by lunny** [comment]
I think this has been resolved in #16101.
