### ISSUE TITLE
Repo MAX_CREATION_LIMIT=0 restriction cannot be overridden with user or organisations

### ISSUE THREAD

**Issue by spirritus** [go-gitea/gitea#15979]
Hi there, 

if you set a global repo creation restricion via app.ini (MAX_CREATION_LIMIT=0) you cannot override it with user or organization settings. I think this is a bug.

Best regards

downloaded 
gitea-1.14.0
linux (debian 10)
PostgreSQL

**Comment by noerw** [comment]
I can't reproduce this. Maybe you mean #16575?
