### ISSUE TITLE
Allow administrators to create tokens for other users

### ISSUE THREAD

**Issue by djcaesar9114** [go-gitea/gitea#15975]
### It's more a feature request than a bug report

- Gitea version (or commit ref): 1.15.0+dev-344-g5285a3e70 built with GNU Make 4.3, go1.16.4 : bindata, timetzdata, sqlite, sqlite_unlock_notify
- Git version: 2.25.1
- Operating system: Ubuntu 20.04

Gitea on docker
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X] No
- Log gist: useless

## Description

I'm using a SSO to handle connections on my apps. I don't have the hand on this SSO so I can't integrate my Gitea instance in this SSO. What I would like is to allow the users of my app to post issues on the gitea with their userID.

I started to develop this mechanism:
- check if the username exists: GET /users/\<username\>
- if it doesn't exist, create it: POST /admin/users
- get the tokens of the user: GET /users/\<username\>/tokens
- if in the list of tokens I don't have a "myapp" token, I create it: POST /users/\<username\>/tokens
- with the token, I create the issue

The problem is that I can't create a token for another user, it has to be the user connected who creates his own token. I could create the same password for all my users, but it's not secure at all and I'd like my users to be able to connect to Gitea with their own password.

Would it be possible to allow administrators to create tokens for other users?

## Screenshots

Useless

**Comment by lunny** [comment]
We have su feature, so this is unnecessary.

**Comment by techknowlogick** [comment]
Closing, as you can use the `sudo` header per https://docs.gitea.io/en-us/api-usage/#sudo to impersonate other users.

**Comment by djcaesar9114** [comment]
OK but an explanation in the documention on how sudo works with Gitea API wouldn't be useless...
