### ISSUE TITLE
[Feature] Team permissions for users

### ISSUE THREAD

**Issue by bestlinuxgamers** [go-gitea/gitea#15983]
Currently, there is no possibility for user repos to set permissions on code, issues, PRs, etc. individually. Even in organizations this is currently only possible for teams. It would be a possibility to add these settings in the collaborators tab of all repos for all users or with #14717 also for all teams. These permissions could even be enhanced with #1228 .

**Comment by bendem** [comment]
This seems to boil down to the same as #22074, which came later but has a larger discussion.

**Comment by lunny** [comment]
Let's move to #22074
