### ISSUE TITLE
[Proposal] Add Copy Button to Text styled in a specific language

### ISSUE THREAD

**Issue by delvh** [go-gitea/gitea#15982]
- Gitea version (or commit ref): 1.15.0+dev-347-gc1a80b7d6 and below
- Can you reproduce the bug at https://try.gitea.io:
  - Yes, i.e. https://try.gitea.io/delvh/kanban-test/pulls/10

## Description
GitHub has added the feature to copy text styled in a specific language using
```
    ```<language>
    Some text
    ```
```
by clicking on a button that on the right-upper corner of the generated area that appears only when the user hovers over that area (see above on the right).
I find that useful as often times the reason why something has been styled in that specific language is to allow for copy and pasting code.

**Comment by silverwind** [comment]
I plan to follow up with a few copy-related features after https://github.com/go-gitea/gitea/pull/15899.

As for this button, I think I'd prefer if it would copy plain text without fences but I see there may be a necessity to have both options. Same goes for the copy feature on lines when viewing a file.

**Comment by delvh** [comment]
Wait… When is there a necessity to copy text as markdown?

**Comment by silverwind** [comment]
Ah, no there actually is no copying as markdown, I was just confused by copying above block because it in itself is markdown. We should always copy plain.

**Comment by yardenshoham** [comment]
I think this has been implemented and can be closed.

**Comment by delvh** [comment]
Yep, I think I remember that as well.
