### ISSUE TITLE
[Bug] Do not reload page after resolving a conversation

### ISSUE THREAD

**Issue by delvh** [go-gitea/gitea#15981]
- Gitea version (or commit ref): 1.15.0+dev-344-g5285a3e70
- Can you reproduce the bug at https://try.gitea.io:
  - Yes: Feel free to experiment [here](https://try.gitea.io/delvh/kanban-test/pulls/10) yourself

## Description
Currently, when resolving a conversation in a PR inside the `Conversation` tab, the page automatically gets reloaded.
Surprisingly, when resolving a conversation there inside the `Files Changed` tab, then it does not get reloaded.
This is interesting as I would have expected both to use the same exact code, given that both should do exactly the same.
Would it be possible to not have to endure a reload every time a conversation is resolved in the `Conversation` tab, simply by replacing the currently present code with the one used in the `Files changed` tab?

**Comment by thigg** [comment]
very annoying if you got a long code review, because the page jumps to the top everytime you resolve a conversation
