### ISSUE TITLE
[Bug] Active Pull Requests Should Not Have Option For "New Pull Request"

### ISSUE THREAD

**Issue by kdumontnu** [go-gitea/gitea#15996]
## Description
Pull requests should not have the option to create a "New Pull Request". I believe this is an artifact from using the same template for "compare" as used for PRs.

## Screenshots

![image](https://user-images.githubusercontent.com/12700993/119861750-fa807980-bed4-11eb-94dc-b4863999e5df.png)

**Comment by zeripath** [comment]
I'm not sure about this. What's the problem with the button being there? I can imagine it being helpful if you have a series of PRs to open up.

**Comment by kdumontnu** [comment]
It removes confusion for new users and removes clutter in a crowded interface. 

The simple process to create a New PR is `Pull Requests` -> `New Pull Request`. 

The scenario you mention of creating repeated PRs is pretty rare and not really intuitive (I should go to an existing PR to open a new PR?). Question: have you used this feature before?

This feedback actually came from our user-base - it's a change I made in our fork and one I think gitea could benefit from.

**Comment by techknowlogick** [comment]
I think it's there to be similar to how issues have the "New Issue" button (screenshot taken from github) ![Screen Shot 2021-05-27 at 3 36 29 PM](https://user-images.githubusercontent.com/164197/119886796-5d880580-bf01-11eb-9300-7f247e97944d.png)

Although GH doesn't have it on PRs, so I'm fine w/ it being removed on the page
![Screen Shot 2021-05-27 at 3 38 24 PM](https://user-images.githubusercontent.com/164197/119887004-988a3900-bf01-11eb-9245-fb879a6c9cbe.png) as it already is on the PR list page.

I don't really have any strong feelings either way, but if some users run into some confusion about it then I'm fine with change.
