### ISSUE TITLE
changes of existing comment will lost when updating due date of a issue

### ISSUE THREAD

**Issue by leeveney** [go-gitea/gitea#15992]
- Gitea version (or commit ref):1.14.2
- Git version:
- Operating system:windows server 2012 r2
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL) https://try.gitea.io/leeveney/Test/issues/1
  - [ ] No
- Log gist:

## Description

...
1. open an existing issue with due date set
2. editing an comment, make some changes
3. update the due date
4. changes made in the comment will lost caused by page refresh without any prompt

please see the gif

## Screenshots
![changesLostWhenUpdatingDueDate](https://user-images.githubusercontent.com/11975191/119792121-06d1fa00-bf08-11eb-8909-f896296fdde9.gif)

**Comment by silverwind** [comment]
Multiple features on the issue page reload the page which leads to lost unsaved state on other features. We need to eliminate those page reloads and implement the features in JS. Semi-Related: https://github.com/go-gitea/gitea/issues/12783.
