### ISSUE TITLE
Restore Travis CI 

### ISSUE THREAD

**Issue by sapk** [go-gitea/gitea#16]
A Travis CI instance should be create.

**Comment by tboerger** [comment]
@lunny I wanted to enable this, but somebody with admin rights have to do that. Please enable it at https://travis-ci.org/profile/go-gitea, than we can close this issue.

**Comment by lunny** [comment]
I have enabled it. When some push on master. The icons will be changed.

**Comment by tboerger** [comment]
So let's close this issue as it's enabled now.
