### ISSUE TITLE
[Bug] Checkbox Overrides Edit

### ISSUE THREAD

**Issue by kdumontnu** [go-gitea/gitea#16000]
- Gitea version (or commit ref): `main` `(1.15.0+dev-353-g6d6a65cf5)`
- Operating system: Windows
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes
  - [ ] No

## Description
Checking a box after making a comment edit will revert the change in the edit.
To recreate: create comment with checkboxes -> edit comment -> save -> toggle box -> reload page

## Screenshots
![checkbox](https://user-images.githubusercontent.com/12700993/119887750-c5365480-bef1-11eb-9363-c64ef69e53f8.gif)

FYI @KN4CK3R @silverwind

**Comment by a1012112796** [comment]
That's becaue the ``oldContent`` is get from ``.raw-content``, it's not update ontime when save new content.
![imege](https://user-images.githubusercontent.com/25342410/120076640-2f5d1e00-c0d9-11eb-90a8-bc025b661a88.png)
