### ISSUE TITLE
Failure mirroring a repository from Github

### ISSUE THREAD

**Issue by rburchell** [go-gitea/gitea#16016]
- Gitea version (or commit ref): 1.14.2
- Git version: 2.25.1
- Operating system: Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Unsure (requires MySQL setup and I'm not sure try is using MySQL)
- Log gist:

## Description
I attempted to set up a mirror of a repository (https://github.com/rburchell/koel) using the API. Many other repositories that I have set up in this way have worked, but this particular one fails. The logs (see below) show an INSERT failing which subsequently breaks the transaction.

My guess is that the problem is caused by the emoji in the description, but I guess that emoji should be supported? :)

## Log
```
May 29 12:00:55 2021/05/29 10:00:55 ...repository/create.go:58:func1() [I] [SQL] INSERT INTO `repository` (`owner_id`,`owner_name`,`lower_name`,`name`,`description`,`website`,`original_service_type`,`original_url`,`default_branch`,`num_watches`,`num_stars`,`num_forks`,`num_issues`,`num_closed_issues`,`num_pulls`,`num_closed_pulls`,`num_milestones`,`num_closed_milestones`,`num_projects`,`num_closed_projects`,`is_private`,`is_empty`,`is_archived`,`is_mirror`,`status`,`is_fork`,`fork_id`,`is_template`,`template_id`,`size`,`is_fsck_enabled`,`close_issues_via_commit_in_any_branch`,`topics`,`trust_model`,`avatar`,`created_unix`,`updated_unix`) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) [21 rburchell-github-mirror koel koel 🐦 A personal music streaming server that works. 2 https://github.com/rburchell/koel 0 0 0 0 0 0 0 0 0 0 0 true true false false 1 false 0 false 0 0 false false null default 1622282455 1622282455] - 572.343µs
May 29 12:00:55 2021/05/29 10:00:55 ...i/v1/repo/migrate.go:168:Migrate() [I] [SQL] ROLLBACK [] - 173.218µs
May 29 12:00:55 2021/05/29 10:00:55 ...i/v1/repo/migrate.go:244:handleMigrateError() [E] MigrateRepository: Error 3988: Conversion from collation utf8mb4_0900_ai_ci into utf8_general_ci impossible for parameter
May 29 12:00:55 2021/05/29 10:00:55 Completed POST /api/v1/repos/migrate?access_token=693cff921463ee83a559440efc3bbf383ee7a942 500 Internal Server Error in 76.38096ms
```

**Comment by KN4CK3R** [comment]
Should be the same as https://github.com/go-gitea/gitea/issues/15922#issuecomment-843896007

**Comment by rburchell** [comment]
That looks relevant, thanks. I'll close this, assuming it'll work out.
