### ISSUE TITLE
[Proposal] add option to update pull request by ``rebase``

### ISSUE THREAD

**Issue by a1012112796** [go-gitea/gitea#16019]
As we all know, do ``git rebase main(base_branch)`` and then force push to the head branch also can set the base of head branch update to the base branch, So I think maybe we can also add it as 
a optional way on ui. Thanks

**Comment by lunny** [comment]
Didn't we have implemented that? You can find a button named `Update` when the pull request base head branch moved.

**Comment by nils91** [comment]
That button does a `git merge base_branch` to update the PR, not a rebase.

**Comment by a1012112796** [comment]
@lunny I know it, It use ``git merge base_branch``, but as we all know, ``git rebase base_branch`` can do same thing. So like we provide more than one way to merge a pull request. I think we can also provide more than one way to ``update pull request`` also, Thanks.
