### ISSUE TITLE
Issues: can not attach 'unsupported' files

### ISSUE THREAD

**Issue by fhuberts** [go-gitea/gitea#16028]
- Gitea version (or commit ref): 1.14.2+29-g3a79f1190 (self-packaged, private server)
- Git version: 2.31.1
- Operating system: Fedora 34 x64, running from systemd
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io: not relevant
  - [ ] Yes (provide example URL)
  - [ ] No
- Log gist: not relevant

## Description
Not being able to attach random 'unsupported' files is a drag.
Especially since for me the 'supported' files cover at most 5% of the files I attach to issues.

Why are attachments limited to 'supported' files?

Any 'unsupported' file should be able to be attached. Just treat them as binary files...

**Comment by noerw** [comment]
You can configure the supported mime-types via `ALLOWED_TYPES`, [see docs](https://docs.gitea.io/en-us/config-cheat-sheet/#issue-and-pull-request-attachments-attachment)

**Comment by fhuberts** [comment]
ah, thanks!
sorry for missing that in the docs!
