### ISSUE TITLE
[Bug] Can't Select Checkbox After Edit

### ISSUE THREAD

**Issue by kdumontnu** [go-gitea/gitea#16056]
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes: https://try.gitea.io/kdumontnu/testRepo/issues/1#issuecomment-87858
  - [ ] No

## Description
Since closing #16000 it appears that checkboxes are no longer selectable after the comment is edited (until page is refreshed).
For some reason the title comments appear to work fine. It is only in subsequent comments.

## Screenshots

![checkbox_edit](https://user-images.githubusercontent.com/12700993/120530318-ffe13680-c3a2-11eb-9de9-f5d6d74ceb09.gif)

@a1012112796

**Comment by a1012112796** [comment]
hasn't found this issue at the last commit of master branch
![Peek 2021-06-04 18-14](https://user-images.githubusercontent.com/25342410/120786712-20ef8600-c561-11eb-968f-b2d2a45e4c52.gif)

``1.15.0+dev-382-ga38f62ad0``

**Comment by kdumontnu** [comment]
> hasn't found this issue at the last commit of master branch
> ![Peek 2021-06-04 18-14](https://user-images.githubusercontent.com/25342410/120786712-20ef8600-c561-11eb-968f-b2d2a45e4c52.gif)
> 
> `1.15.0+dev-382-ga38f62ad0`

Is that the parent comment? Try to create another comment below that and do the same thing. For some reason they behave differently.

**Comment by a1012112796** [comment]
hmm, looks the ``for..of`` not work fine in my chorme web browser it only catch two items, while there are more than two items in the list. I try change it to ``forEach``, example change:
```DIFF
diff --git a/web_src/js/markup/tasklist.js b/web_src/js/markup/tasklist.js
index 5a7291b4d..ef6cc1a2e 100644
--- a/web_src/js/markup/tasklist.js
+++ b/web_src/js/markup/tasklist.js
@@ -9,7 +9,12 @@
 const preventListener = (e) => e.preventDefault();
 
 export function initMarkupTasklist() {
-  for (const el of document.querySelectorAll(`.markup[data-can-edit=true]`) || []) {
+  const allComments = document.querySelectorAll(`.markup[data-can-edit=true]`);
+  if (allComments.length === 0) {
+    return;
+  }
+
+  allComments.forEach((el) => {
     const container = el.parentNode;
     const checkboxes = el.querySelectorAll(`.task-list-item input[type=checkbox]`);
 
@@ -58,5 +63,5 @@ export function initMarkupTasklist() {
     for (const checkbox of checkboxes) {
       checkbox.disabled = false;
     }
-  }
+  });
 }
```

Then it work again. But I wonder why?

@kdumontnu which web browser you are using? Thanks.

/cc @silverwind

**Comment by kdumontnu** [comment]
Good find. I only tried it on Chrome

**Comment by silverwind** [comment]
``for..of` can't be the culprit I think, it's basically made for iterating DOM collections.

**Comment by lunny** [comment]
I think this has been resolved.
