### ISSUE TITLE
Pull request view take long time to load 

### ISSUE THREAD

**Issue by zuhairamahdi** [go-gitea/gitea#16054]
- Gitea version (or commit ref): 1.14.2
- Git version:
- Operating system: Windows
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
- Log gist:

## Description
we are starting to notice that the pull request pages (especially if it is a big one 'many commits') take a long time to load. and the files changed section even take longer.

note that due to the long time it takes to open the 'Files Changed' I was not able to take screenshot (we are talking about minutes not seconds)

## Screenshots

![image](https://user-images.githubusercontent.com/6876269/120512341-f15f4300-c3d3-11eb-8e77-8607fd15afbb.png)
![image](https://user-images.githubusercontent.com/6876269/120512583-2cfa0d00-c3d4-11eb-9ed9-421ba6e6eaaf.png)

**Comment by zuhairamahdi** [comment]
this is how much it take to load 'Files Changed' for me:
![image](https://user-images.githubusercontent.com/6876269/120513292-ca554100-c3d4-11eb-8ae3-e483a6c8a657.png)

**Comment by zuhairamahdi** [comment]
even when viewing a single commit changes it is taking a long time:
![image](https://user-images.githubusercontent.com/6876269/120515167-bb6f8e00-c3d6-11eb-9378-30db9580731c.png)
this specific commit had only 2 lines changed

**Comment by lunny** [comment]
Have you tested gogit version?

**Comment by zuhairamahdi** [comment]
@lunny how can I test that?

**Comment by zuhairamahdi** [comment]
Hi @lunny we use the executable for windows and I'm not sure how to test the version of gogit. this is giving us a very hard time to do code reviews and merge pull requests.

**Comment by lunny** [comment]
@zuhairamahdi You can find the download link from https://dl.gitea.io/gitea/1.14.2/gitea-1.14.2-gogit-windows-4.0-amd64.exe , for windows and v1.14.2, we generated two versions release.

**Comment by zuhairamahdi** [comment]
Hi @lunny once we changed to the gogit version there was a considerable performance boost:
- Pull request page: 
![image](https://user-images.githubusercontent.com/6876269/120660519-12856980-c490-11eb-8af0-b458d75d4572.png)
- Files changed views: 
![image](https://user-images.githubusercontent.com/6876269/120660631-32b52880-c490-11eb-8408-cd9833b8df8e.png)

**Comment by lunny** [comment]
So this is a known issue that we are trying to resolve, the problem of gogit version is that may spend more time than git version.

**Comment by wxiaoguang** [comment]
Caused by Git for Windows
