### ISSUE TITLE
auto move task in kanban

### ISSUE THREAD

**Issue by zuhairamahdi** [go-gitea/gitea#16053]
- Gitea version (or commit ref): 1.14.2
- Git version:
- Operating system:
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
- Log gist:

## Description
is there a way to auto move to different columns? for example when we create a new issue it goes directly to 'Uncategorized' and we have to manually move it to 'To Do' or 'In Progress' and once the issue closed we need to move it manually to the 'Done' section as well.

**Comment by delvh** [comment]
Currently not.
See my issue, #14359.
