### ISSUE TITLE
Email notifications for comments on subscribed Issues not working

### ISSUE THREAD

**Issue by HammyHavoc** [go-gitea/gitea#16058]
- Gitea version (or commit ref): 1.15.0+dev-378-g9fdda9008
- Git version: Whatever is the latest on https://registry.hub.docker.com/r/gitea/gitea/
- Operating system: Docker container running on Unraid: https://registry.hub.docker.com/r/gitea/gitea/
  
  
  
- Database (use `[x]`):
MariaDB according to https://registry.hub.docker.com/r/gitea/gitea/
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X] No
- Log gist:

https://gist.github.com/HammyHavoc/9c45b33ba696d5a33d23facea6775c5d

## Description

As per https://twitter.com/hammyhavoc/status/1399490410066677760:

On GitHub I receive notifications for comments on Issues that I've created or been assigned. However, on Gitea, I'm not receiving email notifications for comments on Issues, despite being subscribed to them.

Otherwise, email notifications definitely work for Gitea.

**Comment by lunny** [comment]
Please confirm that your personal setting -> `Account` -> `Your primary email address will be used for notifications and other operations. ` is `Enable Email Notifications`.

**Comment by HammyHavoc** [comment]
Yep, email notifications are enabled for it, set as primary, and activated.

**Comment by HammyHavoc** [comment]
Addendum: I opened an Issue and assigned it to a colleague who didn't receive an email notification for it, despite their settings being identical to my own in regards to email notifications, primary and activated.

However, I just did the 'Send Testing Email' in admin/config and it arrives just fine, yet still no emails for Issues.

**Comment by bauermarkus** [comment]
Have you activated eMail sending in the config?

**Comment by HammyHavoc** [comment]
Wow, that seems so obvious in retrospect. I assumed they'd be enabled by default if the Mailer was configured and setup. Thanks so much! :- ) Stay well!
