### ISSUE TITLE
Using arrow keys to navigate emoji recommendations moves caret

### ISSUE THREAD

**Issue by delvh** [go-gitea/gitea#16061]
- Gitea version (or commit ref): 1.15.0+dev-379-gc1ff59c1c
- Can you reproduce the bug at https://try.gitea.io:
  - Yes

## Description
When there is a line above or below the line requesting emojis, the caret will be moved as well when the arrow keys are used to navigate the emoji recommendation. As a result of this, most likely some internal check fails as the caret is not aligned where it is expected to be, and hence no recommendation insertion occurs.

To fix this problem, `↑` `↓` key input should not be forwarded to the caret while the recommendation popup is present.

## Screenshots
![image](https://user-images.githubusercontent.com/51889757/120622574-3a100e00-c45f-11eb-9238-3ae59fa05aef.png)
Shows that the caret has been moved up after clicking `↑`. If enter is pressed now, nothing happens except that the menu disappears. Same is true if there is a line below and `↓` is pressed.

**Comment by wxiaoguang** [comment]
It has been refactored. 

Is there still a problem?

**Comment by wxiaoguang** [comment]
I think it has been fixed.
