### ISSUE TITLE
How to display characters :1: in Markdown documents

### ISSUE THREAD

**Issue by a96219** [go-gitea/gitea#16060]
- Gitea version (or commit ref): 1.15.0+dev-365-g36dce0e45 (docker)

In Markdown, the following characters
```markdown
这是字符:1:
```
Show as follows:
![image](https://user-images.githubusercontent.com/38235993/120618384-9c800300-c48d-11eb-9d71-df7bdd31a362.png)

How do I display `这是字符:1:` correctly

**Comment by silverwind** [comment]
This is a bug in the markdown processor. It should only replace text with images for the know emoji sequences.

**Comment by zeripath** [comment]
The failure is here:

https://github.com/go-gitea/gitea/blob/f424862cbb4e681a8df08debc51863d0e9005268/modules/markup/html.go#L951-L952

The use of strings.Contains(...) to check if the alias is known is incorrect.

```
			s := " " + strings.Join(setting.UI.Reactions, " ") + "gitea "
			if strings.Contains(s, " " + alias + " ") {
```

would fix this particular issue

**Comment by 6543** [comment]
@zeripath #16004 does fix it too :D
