### ISSUE TITLE
Unable to log-in after dump and restore

### ISSUE THREAD

**Issue by ejthesnaar** [go-gitea/gitea#16093]
- Gitea version (or commit ref): Going from <unknown, didn't check> to v1.14.1 on TrueNAS
- Git version: 2.31.1
- Operating system: TrueNAS Community Plugin on TrueNAS 12.0 U4
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
- Log gist:

## Description
Hi Gitea team.  

I was running the Gitea Community plugin within TrueNAS.  I didn't check versions prior to reinstall.  I used the dump command, as per https://docs.gitea.io/en-us/backup-and-restore/, to create a backup of the installation.  

I installed a clean TrueNAS-12.0-U4, and installed a clean Gitea plugin.  I tried multiple methods, from first configuring Gitea and then restoring, to after install stopping the service and immediately restoring. I had significant problems restoring the dump.  With the PostgreSQL restore flooding the terminal, it was hard to see any errors.  Even setting ON_ERROR_STOP, didn't show errors.  After everything (app.ini, Data, Logs, Repos and Database) was moved to correct locations, I could not log in.

Inspecting the DB didn't show any users.  I opened the SQL backup and tried to manually run the INSERT to add the user.  This failed with:

ERROR: null value in column "keep_activity_private" violates not-null constraint

Query with details removed:
INSERT INTO "user" ("id", "lower_name", "name", "full_name", "email", "keep_email_private", "email_notifications_preference", "passwd", "passwd_hash_algo", "must_change_password", "login_type", "login_source", "login_name", "type", "location", "website", "rands", "salt", "language", "description", "created_unix", "updated_unix", "last_login_unix", "last_repo_visibility", "max_repo_creation", "is_active", "is_admin", "is_restricted", "allow_git_hook", "allow_import_local", "allow_create_organization", "prohibit_login", "avatar", "avatar_email", "use_custom_avatar", "num_followers", "num_following", "num_stars", "num_repos", "num_teams", "num_members", "visibility", "repo_admin_change_team_access", "diff_view_style", "theme", "keep_activity_private") VALUES (5,'test','test','','',false,'','','',false,0,0,'',1,'','','jmE8n9yvnY','BHCtCK1XQc','','',1602655076,1614569971,0,false,-1,true,false,false,false,false,false,false,'3','',true,0,0,0,17,1,1,0,true,'','',NULL);

Changing the final NULL value to false succeeded the insert.

I believe there is therefor an issue with the DUMP command, and the specific 'user' table and 'keep_activity_private' column. Either the schema changed somewhere along the line, and the NULL values was inserted when the column was inserted, or the dump function is incorrectly storing the value.

**Comment by ejthesnaar** [comment]
Following the restore, and fixing the SQL script, the stored SSH key didn't work.  Removing the key from the Web UI and re-adding it, fixed it.

**Comment by lunny** [comment]
After restored, you should run both `Resynchronize pre-receive, update and post-receive hooks of all repositories.` and `Regenerate ssh keys` if you are using openssh. Because the location is changed.

**Comment by ejthesnaar** [comment]
Regarding the SSH keys.  Sure.

Regarding hooks.  I did run the following sequence:

su git
gitea admin regenerate hook --c /usr/local/etc/gitea/conf/app.ini.  

It ran successfully, but I was still unable to log on.  I had to specify the config path, as it looks like the plugin uses non default paths.  The problem is that the users, inserted by the first segment of the SQL database script, are not in the DB, resulting in failing login attempts.

**Comment by ejthesnaar** [comment]
For reference, Gitea was both prior to the TrueNAS install and afterwards, installed using the community plugin.  All, even my mounted data directories had exactly the same structure.

**Comment by ejthesnaar** [comment]
On the new installation, I made another dump.  This time, the entries did contain false/true values instead of null.  Might I suggest looking at the SQL database deployment script, and adding a default value of false to the column?

**Comment by zeripath** [comment]
Dumps prior to 1.14 don't include a copy of the version table. So on startup migrations are not run.

We need to know what version you originally dumped from in order to tell you what that version table should be so that prior to running gitea you can set it properly and get the dB migrations to run.

**Comment by ejthesnaar** [comment]
Like I stated in the original post, I didn't check the version prior to migrating, as didn't expect an issue will arise.  I am unable to check the previous version, as the machine is completely wiped.  As the version is not in the dumps, it is now lost.

The best I can do is narrow it down to: the installation of the Gitea server was less than a year old.

You can close this issue if you feel this is not going anywhere.

I managed to recover the DB by changing the NULL values in the SQL script inside of the dump to FALSE and all is working fine now.

My suspicion is that at some point, "keep_activity_private" was added as an additional column in the database (Postgres in this instance) during a version upgrade of Gitea, but without a default value in the SQL upgrade script, NULL values gets populated, instead of a TRUE/FALSE.  From the version history of the SQL deployment script, you should be able to see when the column was introduced, whether it has a default value for upgrades and whether it now has a default value.

**Comment by zeripath** [comment]
It is probably possible to work out what version of Gitea it was from the schema. Especially if you can give us some sort of date of when it was installed. Almost all gitea versions have some sort of change of the schema so by looking at what the changes were between versions you should be able to work it out.
