### ISSUE TITLE
Postprocess performance profile

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#16092]
Postprocess is very slow when render a 900 line csv file. This is the cpu profile graph.

<img width="685" alt="图片" src="https://user-images.githubusercontent.com/81045/120931449-234e0d80-c724-11eb-8da6-747c5101dcef.png">

**Comment by zeripath** [comment]
yup the sha1ccommand processer thing is kinda silly - should be able to pass these to the batch-check
