### ISSUE TITLE
Better avatar positioning in mobile view.

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#16108]
## Description

The profile avatar looks stretched and gets cut off on smaller and mobile layouts.  

## Screenshots
![mobile](https://user-images.githubusercontent.com/51394064/121200476-7c887f00-c893-11eb-914a-7c9dcabf6dbe.png)
![stretched](https://user-images.githubusercontent.com/51394064/121202442-038a2700-c895-11eb-8832-1b519b219065.png)

**Comment by silverwind** [comment]
Think this was fixed, if not, report back.
