### ISSUE TITLE
Subscription based model feature for Gitea

### ISSUE THREAD

**Issue by yogeshbeniwal** [go-gitea/gitea#16105]
Looking at how subscription based model is getting popular, it will be nice to have this feature considered for development future release. Talking about on a high level how it should work
- Various subscription based signups (Monthly/Yearly)
- Using Stripe as payment gateway
- Configuration to provide access to clone functionality according to subscription (Free/Members only/Paid Members)

**Comment by hypervtechnics** [comment]
I think that this isn't a good idea. If you plan on providing a hosted gitea server where users pay for the usage (reasons why they would do so regarding all the alternatives: I don't know...) try to build something next to it. Maybe another service using the Gitea API as an administrator to manage users. You can then handle you payment stuff there and not in Gitea. That's not where it belongs!

**Comment by jolheiser** [comment]
I am going to close this issue under the belief that Gitea should remain free of pay-to-use functionality at its core.  

Anyone looking for hosted Gitea instances, take a look at the list on [awesome-gitea](https://gitea.com/gitea/awesome-gitea#organizations). :slightly_smiling_face:
