### ISSUE TITLE
Move InitDBEngine from routers to better place

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#16116]
https://github.com/go-gitea/gitea/blob/1bfb0a24d843e10d6d95c4319a84980485e584ed/routers/common/db.go#L19-L39

"...I think this might be better in modules/database. 

If you think about what else is in here they're all handlers/middleware of some sort - this is very definitely not and therefore should not be here. ..."

_Originally posted by @zeripath in https://github.com/go-gitea/gitea/pull/15800#discussion_r646930456_

**Comment by wxiaoguang** [comment]
It should have been done.
