### ISSUE TITLE
[Feature request] list all subscriptions/watched repositories

### ISSUE THREAD

**Issue by qwerty287** [go-gitea/gitea#16111]
### Description

It would be very nice if there would be an option to see all subscribed issues/pull requests and all repos you watch. GitHub uses https://github.com/watching and https://github.com/notifications/subscriptions to access these lists. Thanks!

**Comment by jhult** [comment]
Related: #5917

**Comment by qwerty287** [comment]
Hi!
I'd like to work on the first part of this issue (the lists for the subscriptions), but I found a problem where I'd need some help: the `issue_watch` table doesn't include issues if you wrote a comment on them or created them (i.e. never used the subscribe/unsubscribe button on the issue page). Since I would add this as a filter option on `/issues`, I'd like to know how this could implemented using the conditions of xorm.Session (like [here](https://github.com/go-gitea/gitea/blob/main/models/issue.go#L1297-L1301)).
Thanks for your help!
