### ISSUE TITLE
gitea dashboard show empty repositories

### ISSUE THREAD

**Issue by SealinGp** [go-gitea/gitea#16127]
- Gitea version (or commit ref): 1.14.2
- Git version: git version 2.27.0
- Operating system: CentOS Linux release 8.3.2011
  
  
  
- Database (use `[x]`): 
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
- Log gist:

## Description

...

operation
1. create empty repositories  in dashboard
2. push project to repositories main branch through ssh
3. dashboard show that repositories code emtpy
4. confirm repositories actually is not emtpy in server(i can still clone through ssh)

## Screenshots

dashbord warehouse web page show empty
![image](https://user-images.githubusercontent.com/32982627/121467901-8d003d00-c9ec-11eb-8a5f-69ae982b6d04.png)

i can still actually clone through ssh
![image](https://user-images.githubusercontent.com/32982627/121467946-9b4e5900-c9ec-11eb-82c2-77ea6694f096.png)

**Comment by zeripath** [comment]
Gitea's hook must not be running.

The usual reason for this is that you have your repositories on a noexec partition. That will not work.

The second most common reason is that you are pushing not using a gitea controlled SSH key. If you SSH to your gitea box using the key and username that you push with - you must not be able to get a shell. If you can you are not pushing with a gitea controlled key.

The third most common reason is that your hooks are out of date or can't communicate to gitea. There is an admin task to resynchronize hooks and you could show your app.ini here and full debug logs around the time of pushing.

---

This is an extremely common issue please review old closed issues regarding this.

**Comment by SealinGp** [comment]
i found it , it's because my app.ini file wrong config

**Comment by SealinGp** [comment]
i found it , it's because my app.ini file wrong config
