### ISSUE TITLE
Performance regression in Gitea 1.14 for large diffs

### ISSUE THREAD

**Issue by jpraet** [go-gitea/gitea#16130]
- Gitea version (or commit ref): 1.14.2
- Operating system: docker on RHEL 7.7

Due to #13949 when you want to create a PR for backporting a change to a release branch, gitea first calculates the diff against the master branch. If the branches have diverged a lot this diff can be quite large, and the processing and rendering can take a very long time. This was already quite slow on Gitea 1.13, but on Gitea 1.14 it got significantly slower.

Gitea 1.14.2:
2021/06/09 16:28:03 Completed GET /CBSS/cics/compare/master...release/10.2 200 OK in 2m15.325931649s

Same with Gitea 1.13.4:
2021-06-09 16:04:19: Completed GET /CBSS/cics/compare/master...release/10.2 200 OK in 46.343604847s

It looks like the performance has already improved again on the latest 1.15 dev version:
2021/06/10 16:00:08 Completed GET /CBSS/cics/compare/master...release/10.2 200 OK in 34.828378582s

This diff is pretty large: 375 changed files with 22643 additions and 25134 deletions.

I noticed there are other tickets about performance issues with 1.14, but they seem to be related to Windows, or to repo browsing.

**Comment by jpraet** [comment]
I will try to identify the commit that improved the performance on 1.15.

**Comment by jpraet** [comment]
It's #15667. Could it be backported to 1.14?

**Comment by wxiaoguang** [comment]
Outdated
