### ISSUE TITLE
net::ERR_INCOMPLETE_CHUNKED_ENCODING 200 (OK)

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#16149]
When review a big pull request files, it returned the error on browser console.

GET https://gitea.com/xorm/reverse/pulls/28/files net::ERR_INCOMPLETE_CHUNKED_ENCODING 200 (OK)

**Comment by wxiaoguang** [comment]
I believe it's a network (nginx cache, proxy, etc) problem, not Gitea's problem.
