### ISSUE TITLE
Bug online edit file

### ISSUE THREAD

**Issue by jiatao99** [go-gitea/gitea#16153]
After upgrade to the 1.14.2, the GUI hangs when trying to edit an existing file using Chrome. It hangs (see screenshot below). 

![image](https://user-images.githubusercontent.com/5280694/121942020-01551c00-cd1e-11eb-8473-f722d3920b48.png)

1. Click the preview button, it will display properly. 
2. Use Safari works perfectly fine.
3. Docker image: gitea/gitea:1.14.2

**Comment by techknowlogick** [comment]
Have you attempted to clear your cache? If yes, then what does your console say?

**Comment by jiatao99** [comment]
Clear cache does solve the problem. Thanks.
