### ISSUE TITLE
Repo Indexer Type Bleve does not work with new migrated repositories.

### ISSUE THREAD

**Issue by safag05** [go-gitea/gitea#16152]
- Gitea version (or commit ref): 1.14.2
- Git version: 2.26.3
- Operating system: Custom Gitea Image, deployed via helm charts on Kubernetes.
- Database (use `[x]`):
  - [ x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x ] No

...

Hello, 

After enabling `REPO_INDEXER_ENABLED = true` I have migrated a repository from Github and tried using Code Search feature on the UI to find a line from that repository however it did not return any output. After following the instructions from the [Gitea discussions](https://discourse.gitea.io/t/cant-search-issues-after-gogs-migration/168) Code Search worked on the migrated repository. I looked through the issues on Github regarding this but did not find much about it. Is this something that can be worked on to automate the process so that we do not have to go inside the Kubernetes pod (in my case) and delete the "indexers" folder and reboot the pod in order for the changes to apply to the new migrated repositories after each migration?

My app.ini file
`[indexer]`
`REPO_INDEXER_ENABLED = true`

Thanks!

**Comment by lunny** [comment]
Maybe we should have a new event, repository migrated.

**Comment by safag05** [comment]
@lunny Not sure what that means.  Is this something that can be fixed easily?

**Comment by safag05** [comment]
@lunny It seems that this was an issue before as well. Closed issue [#9190](https://github.com/go-gitea/gitea/issues/9190#issue-529723263). @MFYDev had the same issue with code search not working after migration. This issue was closed after some other fix related to code search but those fixes did not fix the original issue what @MFYDev described. I thought maybe this issue might help.

**Comment by lunny** [comment]
@safag05 Could you help to confirm that #16991 fix this?
