### ISSUE TITLE
Prefer implicit TLS instead of STARTTLS.

### ISSUE THREAD

**Issue by MrSorcus** [go-gitea/gitea#16160]
https://github.com/go-gitea/gitea/blob/864f0c044704a0151948b09be5d1f3c448df8584/custom/conf/app.example.ini#L1390
RFC 8314 (https://datatracker.ietf.org/doc/html/rfc8314) updates RFC 6409 with using `implicit TLS`, not a `STARTTLS`.

**Comment by zeripath** [comment]
I think this is just a language issue. If you put in port 465 - implicit TLS will be used.

Use whatever works for your server.

**Comment by MrSorcus** [comment]
@techknowlogick it's not a `question`.
I think that config shouldn't recommend `STARTTLS on port 587`, because it's obsoleted via RFC 8314.
