### ISSUE TITLE
Add a warning log when gitea is using a deprecated setting item.

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#16181]
We can add some warning logs when gitea start up if it's using a deprecated setting item. The docs is also important but I think that's not enough.

**Comment by wxiaoguang** [comment]
Now there is a deprecatedSetting function:

![image](https://user-images.githubusercontent.com/2114189/165458140-8ab5cb1f-869e-43af-9ebe-015e6ae35425.png)
