### ISSUE TITLE
A large white box obstructs the file editor on iOS

### ISSUE THREAD

**Issue by jacopo-j** [go-gitea/gitea#16188]
- Gitea version (or commit ref): 1.14.2, from your releases
- Git version: 2.30.1
- Operating system: macOS 11.3, running from launchd
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes (any file editing page)
  - [ ] No
- Log gist:

Shouldn't be relevant (it's a UI problem)

## Description

Title and screenshots are pretty self-explanatory. They were taken on an iPhone and on an iPad both running iOS 14.6 and using Safari. The problem doesn't occur on Safari on macOS.

## Screenshots

![IMG_2126](https://user-images.githubusercontent.com/9914547/122463866-704ca200-cfb6-11eb-948b-69c8d1c522da.PNG)
![IMG_0270](https://user-images.githubusercontent.com/9914547/122463882-73479280-cfb6-11eb-9326-e336a2432176.PNG)

**Comment by silverwind** [comment]
Can you check if that box is also there on https://microsoft.github.io/monaco-editor/playground.html?

**Comment by jacopo-j** [comment]
Doesn't seem so:
![IMG_0271](https://user-images.githubusercontent.com/9914547/122550344-d62b3f00-d033-11eb-8295-4ffe258fa516.jpeg)

**Comment by thoppa** [comment]
Same issue- prevents editing of last 10ish lines of code. I have been adding 10 ish blank lines.

**Comment by silverwind** [comment]
Still present in latest Safari?

**Comment by jacopo-j** [comment]
Yes

**Comment by silverwind** [comment]
Please hook up [web inspector](https://www.browserstack.com/guide/how-to-debug-on-iphone) to the phone, inspect the element and show the HTML.

**Comment by jacopo-j** [comment]
Looks like element `<textarea class="iPadShowKeyboard">` is the culprit

<img width="889" alt="Screenshot 2023-04-22 alle 18 32 47" src="https://user-images.githubusercontent.com/9914547/233796093-e5d9719c-9351-417a-a4ce-7dabb006e5dc.png">

**Comment by silverwind** [comment]
Interesting, this seems like something that Safari itself adds to the page, or maybe an extension? Do you run any Safari extensions?

**Comment by silverwind** [comment]
Actually no, it's VSCode adding it:

https://github.com/microsoft/vscode/search?q=iPadShowKeyboard

**Comment by silverwind** [comment]
The monaco issue tracker does not yield any results for this issue, so I assume it must be our CSS interfering with this feature of VSCode/Monaco.

@jacopo-j one last question: if you add `display: none !important` to the element's CSS in the inspector, does the editor work normally, or do you see reduced functionality?

**Comment by jacopo-j** [comment]
It does seem to work normally.

**Comment by silverwind** [comment]
Okay I guess I will add that as a workaround then, but leaving this open for the future for a proper fix.

**Comment by silverwind** [comment]
I think I found out what this textarea may supposed to be. See bottom-right:

<img width="317" alt="image" src="https://user-images.githubusercontent.com/115237/233796755-f7b09b93-8bcd-449f-a628-500ed387d540.png">

So it seems to be some kind of accessiblity helper that should bring up the native browser textarea, but I suppose this is mostly unnecessary.

**Comment by silverwind** [comment]
Will check if i can debug this in XCode's IOS simulator.
