### ISSUE TITLE
?redirect_to= is dropped after failed login attempt

### ISSUE THREAD

**Issue by noerw** [go-gitea/gitea#16194]
- Gitea version (or commit ref): 1.14.2
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes: https://try.gitea.io/user/login?redirect_to=%2fnoerw%2ftest%2f

## Description
When visiting an URL like https://try.gitea.io/user/login?redirect_to=%2fnoerw%2ftest%2f and failing the first login attempt, the redirect is stripped on the new login page.
This is bad UX.

**Comment by zeripath** [comment]
so the redirect is stored and isn't lost - it's just that it disappears from the query.

It wouldn't be too hard to not do that but I'm not sure what the problem is.

**Comment by noerw** [comment]
Oh you're right, looks like it's just a cosmetic issue, the redirect is still applied via the cookie.
In the past the redirect would actually be stripped, seems like this is fixed already
