### ISSUE TITLE
Internal Server Error on endpoint ​/orgs​/{org}​/teams - List an organization's teams

### ISSUE THREAD

**Issue by anders-larsson** [go-gitea/gitea#16192]
- Gitea version (or commit ref): 1.14.2
- Git version: Not applicable
- Operating system: Official Gitea docker container
  
  
  
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes - https://gitea.com/api/v1/orgs/gitea/teams
  - [ ] No
- Log gist: https://gist.github.com/anders-larsson/730d73cdc825061a3b5bfe3904cfdadb

## Description

Using the List an organization's teams endpoint gives Internal Server Error and prints the error in the included Gist.

**Comment by anders-larsson** [comment]
Just to add. On the private gitea instance token authentication was used when this error was thrown.

**Comment by zeripath** [comment]
OK looking at your gist it appears that the issue was that the ctx.User was nil. Which would fit with your token being incorrect.

I'll pop up a PR to prevent the NPE though.
