### ISSUE TITLE
Can't save Release draft as draft

### ISSUE THREAD

**Issue by thibaultmeyer** [go-gitea/gitea#162]
- Gitea version (or commit ref): 0.9.99.0915
- Git version: 2.10
- Operating system: CentOS 64bit
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Log gist:

## Description

Can't save a Release draft modification as draft.

## How to reproduce

1. Go to release tab
2. Create a new draft and click on "Save Draft"
3. On release tab, click on "Edit" button for the newly created draft
4. The "Save Draft" button not appearing

**Comment by strk** [comment]
Does this also happen on Gogs or is it a new bug in gitea ?

**Comment by lunny** [comment]
Yes. Maybe it's a bug. When you edit a draft, you cannot save it. Only publish it or delete it or Cancel.

**Comment by strk** [comment]
Just tried on try.gogs.io and I confirm you can only delete the release, save it as an actual release or cancel the operation, so no further saving as draft after the first one. Will try to fix.

**Comment by strk** [comment]
So, what do we want here ? 
At the moment upon "editing" a draft release you have "Edit" and "Delete" options, whereas "Edit" _also_ publishes the release (changing its "draft" state).

It sounds like you'd want "Edit" to keep the "Draft" or "Published" state while adding a "Publish" button to change the state ?

**Comment by strk** [comment]
Can you test https://github.com/go-gitea/gitea/pull/169 @0xbaadf00d ?

**Comment by thibaultmeyer** [comment]
Excellent, it working very well @strk.
