### ISSUE TITLE
How the project will evolve because that  Gogs  has become alive?

### ISSUE THREAD

**Issue by melote** [go-gitea/gitea#162]

**Comment by tboerger** [comment]
As the plans are getting in different directions it looks like it's getting difficult. We try to sync where it is possible and reasonable.

**Comment by lunny** [comment]
But there is no wiki and pull-request features on gogs and gitea will have.

**Comment by MorphBonehunter** [comment]
So i think this https://github.com/gogits/gogs/issues/1304 explains it fully.
As @Unknwon explains this in the closing message of this thread, both projects are not merged.
So as @tboerger sad (and look at the PR's he made) some of the fixes of gogs will go into gitea.

I would link the https://github.com/gogits/gogs/issues/1304 to any thread which asks about the actual behavior as it explains (and concludes) the situation very well :)

**Comment by tboerger** [comment]
So let's close this issue.
