### ISSUE TITLE
How to store/create/access global pre-receive hooks? 

### ISSUE THREAD

**Issue by Chewibub** [go-gitea/gitea#16204]
Tried adding a hooks folder in the gitea-repositories folder (separate to the one within repos), and using:
`git config --global core.hooksPath <path/to/hooks>`
but that didn't work. Tested adding server side hooks to the hook folder within the repo and those work, but I'm looking for a solution to have the hook be present in all repo within the gitea server.

Also, is there an easy way to push hooks to the gitea server from within a local repo? Have the server hosted within kubernetes, making it pretty difficult.

Thanks!

**Comment by zeripath** [comment]
You can set the DISABLE_GIT_HOOKS option to false and then the admin will get a nice UI to add hooks.

Regarding core.hooksPath we want to use that in future to take complete control of hooks within gitea, so you would likely have found that breaking at some point.
