### ISSUE TITLE
Request an API for creating tags without creating releases

### ISSUE THREAD

**Issue by lchrennew** [go-gitea/gitea#16207]
- Gitea version (or commit ref): 1.14.2
- Git version:
- Operating system:
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [*] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
- Log gist:

## Description

it seems the only approach is using the API for creating releases.
as mentioned in the title, I need an API to create tags instead of creating releases with tags.

**Comment by 6543** [comment]
Got merged last days ...
