### ISSUE TITLE
Request the creating branch API support commitish

### ISSUE THREAD

**Issue by lchrennew** [go-gitea/gitea#16208]
- Gitea version (or commit ref): 1.14.2
- Git version:
- Operating system:
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [*] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
- Log gist:

## Description

Current API `POST /repos​/{owner}​/{repo}​/branches` (Create a branch) only support create a branch from another branch.

I need this API supports more:
- Create a branch based on a tag.
- Create a branch based on a commit.

**Comment by richmahn** [comment]
This is covered in the request for the git/refs create reference endpoint as mentioned here: https://github.com/go-gitea/gitea/issues/11835
