### ISSUE TITLE
Removing yourself from an organization should require a confirmation dialog

### ISSUE THREAD

**Issue by fnetX** [go-gitea/gitea#16215]
- Gitea version (or commit ref): 1.14.3 + 1.15-dev
- Database (use `[x]`):
  - [x] MySQL
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes, https://try.gitea.io/org/will-leave-owners/teams/owners = no longer accessible for me
  - [ ] No

## Description
A user on [Codeberg](https://codeberg.org/Codeberg/Community/issues/475) reported perse accidentally left the "Owners" team of an organization, as this requires no confirmation, and thus the whole organization with no chance, to regain access after a single mistaken click.

As many other things do require confirmation, and these buttons are quite easy to hit ("Leave", or removing the wrong member), this should have a confirmation dialog IMHO, too.

Thank you for considering a fix. :v:

**Comment by thegeorgeous** [comment]
@techknowlogick @6543 
I would like to work on this? Can I pick it up?
