### ISSUE TITLE
Migration from 1.13.7 to 1.14.x failing with: no such file or directory

### ISSUE THREAD

**Issue by raucao** [go-gitea/gitea#16210]
I'd like to re-open #15505, but I don't have permissions for doing so. I'd appreciate if a collaborator could do it.

---

The migration from 1.13.7 to 1.14.x is still broken for us. I just tried it again, and it's failing migration transactions with the following output (still the same problem as OP reported in #15505):

```
models/models.go:220:NewEngine() [I] [SQL] BEGIN TRANSACTION [] - 757.98µs
...s/migrations/v156.go:74:fixPublisherIDforTagReleases() [I] [SQL] SELECT "id", "repo_id", "sha1", "tag_name", "publisher_id" FROM "release" WHERE (publisher_id = 0 OR publisher_id is null) AND (is_tag=$1) ORDER BY "repo_id" ASC, "id" ASC LIMIT 100 [true] - 2.108098ms
...s/migrations/v156.go:89:fixPublisherIDforTagReleases() [I] [SQL] SELECT "id", "owner_id", "owner_name", "name" FROM "repository" WHERE "id"=$1 LIMIT 1 [7] - 1.802507ms
...s/migrations/v156.go:114:fixPublisherIDforTagReleases() [E] Error whilst opening git repo for [7]kosmos/mastodon. Error: no such file or directory
...ations/migrations.go:397:Migrate() [I] [SQL] ROLLBACK [] - 585.276µs
routers/init.go:81:initDBEngine() [E] ORM engine initialization attempt #8/10 failed. Error: migrate: do migrate: no such file or directory
```

**Comment by zeripath** [comment]
The repository for kosmos/mastodon is missing.  

This is a fatal problem.

Are you sure that $GITEA_REPOSITORIES/kosmos/mastodon.git exists, is readable and owned by the gitea user and is a git repository.

**Comment by raucao** [comment]
The repository is clearly there, yes.

**Comment by zeripath** [comment]
What is your `[repository]` `ROOT` value in your app.ini?

There was a breaking change in 1.14:

https://blog.gitea.io/2021/04/gitea-1.14.0-is-released/#breaking-changes-or-potentially-breaking :

❗ The default location for repository data ([repository] ROOT) will now be in a subdirectory of the APP_DATA_PATH path. (#13991)

**Comment by zeripath** [comment]
https://github.com/go-gitea/gitea/issues/16217#issuecomment-864970210

appears to have the same issue.

**Comment by jakubgs** [comment]
Here is my full log: https://gist.github.com/jakubgs/752203b20581700c288fa856bc7d48a6

And here's a section of my config:
```yaml
[repository]
ROOT = /data/git/repositories

[repository.local]
LOCAL_COPY_PATH = /data/gitea/tmp/local-repo

[repository.upload]
TEMP_PATH = /data/gitea/uploads

[server]
APP_DATA_PATH = /data/gitea
````

**Comment by zeripath** [comment]
This doesn't make any sense.

The error is coming from:

**Comment by jakubgs** [comment]
I'm trying to strace the process to see what paths it actually tries to open:
```
/ # ps faux
PID   USER     TIME  COMMAND
    1 root      0:00 /bin/s6-svscan /etc/s6
   15 root      0:00 s6-supervise openssh
   16 root      0:00 s6-supervise gitea
   17 git       0:15 /app/gitea/gitea web
   18 root      0:00 sshd: /usr/sbin/sshd -D -e [listener] 0 of 10-100 startups
 1620 root      0:00 sh
18994 root      0:00 ps faux
18995 git       0:00 /usr/bin/git -c credential.helper= -c protocol.version=2 show-ref --verify --hash refs/tags/v0.1.1
/ # sudo strace -e trace=%file -f -p 17
strace: attach: ptrace(PTRACE_SEIZE, 17): Operation not permitted
```
But I'm having issues with the container. I'll report back when i get it working.

**Comment by jakubgs** [comment]
Actually, the path looks correct:
```
[pid 2679313] stat("/data/git/repositories/status-im/keycard-cli.git/.git", 0x7ffea19d7ec0) = -1 ENOENT (No such file or directory)
```
But it seems to not be expecting bare repositories:
```
/ # ls -l /data/git/repositories/status-im/keycard-cli.git/.git
ls: /data/git/repositories/status-im/keycard-cli.git/.git: No such file or directory
/ # ls -l /data/git/repositories/status-im/keycard-cli.git/
total 40
-rw-r--r--    1 git      nobody        4096 Jun 21 06:55 FETCH_HEAD
-rw-r--r--    1 git      nobody          24 Feb 23 12:05 HEAD
drwxr-xr-x    2 git      nobody        4096 Feb 23 12:05 branches
-rw-r--r--    1 git      nobody         175 Feb 23 12:05 config
-rw-r--r--    1 git      nobody          73 Feb 23 12:05 description
drwxr-xr-x    2 git      nobody        4096 Feb 23 12:05 hooks
drwxr-xr-x    2 git      nobody        4096 Feb 23 12:05 info
drwxr-xr-x    4 git      nobody        4096 Feb 23 12:05 objects
-rw-r--r--    1 git      nobody        2130 Feb 23 12:05 packed-refs
drwxr-xr-x    4 git      nobody        4096 Feb 23 12:05 refs
```

**Comment by jakubgs** [comment]
Here's a full list of `ENOENT` errors I see for a single repo:
```
[pid 2651945] newfstatat(AT_FDCWD, "/data/git/repositories/embarklabs/grunt-embark.git/refs/tags/0.5.1", 0xc00415e5e8, AT_SYMLINK_NOFOLLOW) = -1 ENOENT (No such file or directory)
[pid 2690828] stat("/data/git/repositories/embarklabs/grunt-embark.git/.git", 0x7fff47c258a0) = -1 ENOENT (No such file or directory)
[pid 2690828] lstat("/data/git/repositories/embarklabs/grunt-embark.git/.git/HEAD", 0x7fff47c25750) = -1 ENOENT (No such file or directory)
[pid 2690828] lstat("/data/git/repositories/embarklabs/grunt-embark.git/commondir", 0x7fff47c25820) = -1 ENOENT (No such file or directory)
[pid 2690829] stat("/data/git/repositories/embarklabs/grunt-embark.git/.git", 0x7ffcf77a5c90) = -1 ENOENT (No such file or directory)
[pid 2690829] lstat("/data/git/repositories/embarklabs/grunt-embark.git/.git/HEAD", 0x7ffcf77a5b40) = -1 ENOENT (No such file or directory)
[pid 2690829] lstat("/data/git/repositories/embarklabs/grunt-embark.git/commondir", 0x7ffcf77a5c10) = -1 ENOENT (No such file or directory)
[pid 2690830] stat("/data/git/repositories/embarklabs/grunt-embark.git/.git", 0x7ffdfed14570) = -1 ENOENT (No such file or directory)
[pid 2690830] lstat("/data/git/repositories/embarklabs/grunt-embark.git/.git/HEAD", 0x7ffdfed14420) = -1 ENOENT (No such file or directory)
[pid 2690830] lstat("/data/git/repositories/embarklabs/grunt-embark.git/commondir", 0x7ffdfed144f0) = -1 ENOENT (No such file or directory)
```
It repeats those for each repo several times.

**Comment by zeripath** [comment]
git will generally try the .git directly first so those are unlikely to be your problem. 

We need the results related to status-im/fastlane-plugin-diawi.git.

--- 

Now I think there may well be an issue with the migrate command in that I don't think it's setting up the repository root but that shouldn't be included here and it appears that the path above is correct.

**Comment by jakubgs** [comment]
Yes, the path does indeed look correct. Let me try go get the `strace` output for that repo.

**Comment by jakubgs** [comment]
Oh, I see, the repo folder doesn't actually exist:
```
[pid 2749577] newfstatat(AT_FDCWD, "/data/git/repositories/status-im/fastlane-plugin-diawi.git", 0xc00412e448, 0) = -1 ENOENT (No such file or directory)
```
And I can see it on the site when using `1.13.7`:
![image](https://user-images.githubusercontent.com/2212681/122766917-5d7dea00-d2a2-11eb-9a89-6a673dea48d4.png)

But the folder does indeed not exist:
```
/ # ls -l /data/git/repositories/status-im/fastlane-plugin-diawi.git
ls: /data/git/repositories/status-im/fastlane-plugin-diawi.git: No such file or directory
```
So I guess the issue is that it exists in the DB, but doesn't on the filesystem, and that breaks the migration:
```
gitea=# SELECT id,owner_name,lower_name,description FROM repository WHERE lower_name = 'fastlane-plugin-diawi';
 id  | owner_name |      lower_name       |                   description                   
-----+------------+-----------------------+-------------------------------------------------
 477 | status-im  | fastlane-plugin-diawi | https://rubygems.org/gems/fastlane-plugin-diawi
(1 row)
```
Would the correct fix be to just `DELETE` it from the `repository` table, or is there anything else I need to do in the DB?

**Comment by jakubgs** [comment]
Yep, that was it, just dropping that row fixed it. Thanks for helping me figure this out. I guess it's not exactly a bug.

Although a graceful handling of lack of repositories would be a nice feature. Not sure what's the correct behavior here, not start Gitea if a repo folder is missing? Currently it starts fine and just returns 500 for the repo site that is missing, which is probably a pretty sane behavior.

**Comment by zeripath** [comment]
I don't think you can have a graceful handling of a migration that fails because it can't find the repository.

This migration is specifically looking for the repo files and needs to see them. As I've stated above there are many reasons for that to happen - the simplest is that the repo isn't there but - the repo root path could be incorrect in which case the migration is going to be completely incorrect.

The error says it can't find this particular repository - apart from emitting the path directly saying look at that path I'm not sure what else it can do.

For this particular migration - it is a fatal error not to be able to find the repo and no graceful handling is possible.

**Comment by jakubgs** [comment]
Yeah, makes sense. Thank you.

**Comment by raucao** [comment]
I hadn't seen the breaking config change, and I that was indeed the problem. Thanks!
