### ISSUE TITLE
[Bug] - mkdir jwt - permission denied

### ISSUE THREAD

**Issue by jhult** [go-gitea/gitea#16218]
- Gitea version (or commit ref): `1.15.0+dev-453-g4fcae3d06` via Docker image `gitea/gitea:latest-rootless`
  
- Database:
  - [x] SQLite
## Description

```
...th2/jwtsigningkey.go:360:loadOrCreateAsymmetricKey() [F] Error generating private key: mkdir /var/lib/gitea/custom/jwt: permission denied
```

This causes the Docker container to continually restart.

Related issue: https://github.com/go-gitea/gitea/issues/15912
Related pull request: #16010

**Comment by yfreund** [comment]
I also encountered this issue - this is caused by the application setting permissions on `/var/lib/gitea/custom` to `600` prior to creating `/var/lib/gitea/custom/jwt`. I had to manually create the latter as a workaround (`sudo mkdir custom/jwt && sudo chown gitea:gitea custom/jwt`).

**Comment by zeripath** [comment]
You can set:

`[oauth]` `JWT_SIGNING_PRIVATE_KEY_FILE` to an absolute path or just create the KeyFile as necessary.

**Comment by yfreund** [comment]
Thanks for the additional feedback @zeripath - I still believe the folder permissions should be altered, or changed after the subfolder is created. This should be a fairly trivial alteration to `docker/rootless/usr/local/bin/docker-setup.sh`:
```
# Prepare custom folder
mkdir -p ${GITEA_CUSTOM} && chmod 0500 ${GITEA_CUSTOM}
```

I Would be happy to submit a merge request, but I have no further information as to why these permissions are set to `0500`, so I'm not sure which approach would be better - setting the permissions to `0700` or moving the second command further down the file (unfortunately this hasn't been documented [here](https://github.com/go-gitea/gitea/pull/10154/commits/039e3fbe332bb5720e076ef4631e3eb0e8609fd1#diff-92dee4294e3809d6d1f4dd70cf3beb1102bba99245362be61418bdb3f0733d13R8)).

**Comment by zeripath** [comment]
Yeah it appears to be a breaking change by default - I'm gonna mark it as breaking and we're gonna need to think about what we do by default here.

**Comment by 6543** [comment]
Well two options:
A. switch back old default
B. Make somehow sure it dont break

**Comment by zeripath** [comment]
thanks @6543 - I would guess we should have the default be a fallback to the old case when it can't create - with a log Error.

**Comment by 6543** [comment]
good idear :) cc @KN4CK3R
