### ISSUE TITLE
Missing Documentation for Docker Restore Process

### ISSUE THREAD

**Issue by gcstang** [go-gitea/gitea#16228]
First and foremost thank you for a great product!
I'm trying to setup a set of instructions to properly perform this task but there is nothing official.

- Gitea version (or commit ref):
- Git version: 1.14.x
- Operating system: Linux/Mac
- Docker Image pulled from hub.docker.com
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] NA

There is docker information on how to perform the backup i.e. 'dump' however there are no instructions on how to properly perform a Docker restore from that dump.

Please add documentation on how to properly accomplish this task or is Docker not recommended?

**Comment by wxiaoguang** [comment]
Now there it is https://docs.gitea.io/en-us/backup-and-restore/
