### ISSUE TITLE
oauth applications show up as failed logins when using ldap

### ISSUE THREAD

**Issue by johanvdw** [go-gitea/gitea#16235]
We have a lot of logs like this:
```
2021/06/23 17:40:52 ...dels/login_source.go:844:UserSignIn() [W] Failed to login '3b5ade80-xxx' via 'ldaphost': user does not exist [uid: 0, name: 3b5ade80-xxx', keyid: 0]
```
Where the key 3b5ade80-xxx is actually an oauth key (used by droneci). 

It is a bit inconvenient, because the large volume hides real issues. It would be better to show this warning only if the login is not found as a token either.

**Comment by zeripath** [comment]
What version of gitea are you using?

**Comment by zeripath** [comment]
But in any case I see the issue. 

https://github.com/go-gitea/gitea/blob/b223d361955f8b722f7dd0b358b2e57e6f359edf/models/login_source.go#L859

should be debug unless the error is not a UserNotExist error.

**Comment by zeripath** [comment]
Now interestingly if this user had properly authenticated these shouldn't have ever got to the UserSignin stage so I'm not sure what's going on - likely this is related to the other oauth2 error people have been experiencing.
