### ISSUE TITLE
Markdown references should be fetched asynchronously or be limited in count

### ISSUE THREAD

**Issue by noerw** [go-gitea/gitea#16257]
- Gitea version (or commit ref): 1.15.0+dev-499-gca18c4d44
- Git version:
- Operating system: linux
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
- Log gist:

## Description
When a markdown file or a comment contains lots of references (looking at you, CHANGELOG.md), they are all resolved, inducing very high server load: loading the view page of gitea's CHANGELOG.md takes ~15secs!

I'm not sure if it's sensible to just limit the number of references that are preloaded, as that change has quite a impact on functionality.
Loading those issue cards on demand (on hover?) might be a better approach, though inducing latency.
Maybe a hybrid approach is best: load max 5 references on page render, and resolve the rest on hover via ajax

**Comment by zeripath** [comment]
This should be substantially better since #16251.

**Comment by noerw** [comment]
@zeripath Yeah the example above ran with that commit, while certainly better, it's still very high load :/

**Comment by zeripath** [comment]
Your sha ref isn't a published version of Gitea btw.

1.15.0+dev-488-g622f1e764 is current main

---

Yeah I'm not surprised that there's still high load - I suspect you're right that issue cards are potentially the next hot spot. 

The specific way in which #16251 came to light wouldn't have hit those.

Tbh our main render needs to do less overall.

(Although if we can get a safe(r) cache #16226 we could cache more things I think)
