### ISSUE TITLE
gitea.service not starting on boot

### ISSUE THREAD

**Issue by RolfNoot** [go-gitea/gitea#16253]
- Gitea version (or commit ref): 1.14.3
- Git version: 2.17.1
- Operating system: Ubuntu 18.04.4 LTS
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Log gist:

## Description

The gitea service doesn't start on boot, it fails with "Found ordering cycle" on boot (see log below). When I start manually after boot, the service starts well.

## LOG

systemd[1]: sockets.target: Found ordering cycle on gitea.service/start
systemd[1]: sockets.target: Job gitea.service/start deleted to break ordering cycle starting with sockets.target/start

**Comment by zeripath** [comment]
We would need to see your service file.

**Comment by zeripath** [comment]
It's worth noting that this isn't a bug with gitea but a problem with your systemd configuration.

**Comment by RolfNoot** [comment]
Yes, I get that it's a configuration problem. I took the gitea.service as provided by the documentation and changed it accordingly. I can see that systemd tried to start the service and that it failed.

[Unit]
Description=Gitea (Git with a cup of tea)
After=syslog.target
After=network.target
###
# Don't forget to add the database service dependencies
###
#
Wants=mysql.service
After=mysql.service
#
#Wants=mariadb.service
#After=mariadb.service
#
#Wants=postgresql.service
#After=postgresql.service
#
#Wants=memcached.service
#After=memcached.service
#
#Wants=redis.service
#After=redis.service
#
###
# If using socket activation for main http/s
###
#
#After=gitea.main.socket
#Requires=gitea.main.socket
#
###
# (You can also provide gitea an http fallback and/or ssh socket too)
#
# An example of /etc/systemd/system/gitea.main.socket
###
##
## [Unit]
## Description=Gitea Web Socket
## PartOf=gitea.service
##
## [Socket]
## Service=gitea.service
## ListenStream=8084
## NoDelay=true
##
## [Install]
## WantedBy=sockets.target

###

[Service]
# Modify these two values and uncomment them if you have
# repos with lots of files and get an HTTP error 500 because
# of that
###
#LimitMEMLOCK=infinity
#LimitNOFILE=65535
RestartSec=2s
Type=simple
User=git
Group=git
WorkingDirectory=/var/lib/gitea/
# If using Unix socket: tells systemd to create the /run/gitea folder, which will contain the gitea.sock file
# (manually creating /run/gitea doesn't work, because it would not persist across reboots)
#RuntimeDirectory=gitea
ExecStart=/usr/local/bin/gitea web --config /etc/gitea/app.ini
Restart=always
Environment=USER=git HOME=/home/git GITEA_WORK_DIR=/var/lib/gitea
# If you install Git to directory prefix other than default PATH (which happens
# for example if you install other versions of Git side-to-side with
# distribution version), uncomment below line and add that prefix to PATH
# Don't forget to place git-lfs binary on the PATH below if you want to enable
# Git LFS support
#Environment=PATH=/path/to/git/bin:/bin:/sbin:/usr/bin:/usr/sbin
# If you want to bind Gitea to a port below 1024, uncomment
# the two values below, or use socket activation to pass Gitea its ports as above
###
SystemCallErrorNumber=EPERM
#CapabilityBoundingSet=CAP_NET_BIND_SERVICE
#AmbientCapabilities=CAP_NET_BIND_SERVICE
###

[Install]
WantedBy=multi-user.target

**Comment by zeripath** [comment]
Have you changed other systemd configuration?

Do you have a mysql.service?

Have you created a socket activation?

**Comment by RolfNoot** [comment]
1. It runs on a system which runs other services as well. Some other services have been installed before.
2. There's no mysql service. 
3. Maybe another service uses socket activation, I don't know the details of what's installed previously.

Let me note that when starting the service after boot, it succeeds.

**Comment by zeripath** [comment]
> 2 .There's no mysql service.

Well that's your problem

**Comment by RolfNoot** [comment]
Sorry, I didn't see the service listed at `/etc/systemd/system/` However if I do `service --status-all`, this is my output:

```
 [ - ]  acpid
 [ + ]  apparmor
 [ + ]  apport
 [ + ]  atd
 [ - ]  console-setup.sh
 [ + ]  cron
 [ - ]  cryptdisks
 [ - ]  cryptdisks-early
 [ + ]  dbus
 [ + ]  ebtables
 [ + ]  grub-common
 [ - ]  hwclock.sh
 [ - ]  irqbalance
 [ + ]  iscsid
 [ - ]  keyboard-setup.sh
 [ + ]  kmod
 [ - ]  lvm2
 [ + ]  lvm2-lvmetad
 [ + ]  lvm2-lvmpolld
 [ + ]  lxcfs
 [ - ]  lxd
 [ - ]  mdadm
 [ - ]  mdadm-waitidle
 [ + ]  mosquitto
 [ + ]  mysql
 [ + ]  netfilter-persistent
 [ + ]  nginx
 [ - ]  open-iscsi
 [ - ]  open-vm-tools
 [ - ]  plymouth
 [ - ]  plymouth-log
 [ + ]  postgresql
 [ + ]  procps
 [ + ]  redis-server
 [ - ]  rsync
 [ + ]  rsyslog
 [ - ]  screen-cleanup
 [ + ]  ssh
 [ + ]  sysstat
 [ + ]  udev
 [ + ]  ufw
 [ + ]  unattended-upgrades
 [ - ]  uuidd
```

**Comment by RolfNoot** [comment]
Sorry for bothering, I finally find out that after a `systemctl daemon-reload` everything works well!

Thanks!
