### ISSUE TITLE
Missing translation for gpg in crowdin

### ISSUE THREAD

**Issue by pree** [go-gitea/gitea#1625]
## Description

The GPG-strings are missing in crowdin and thus they cannot be translated there.
Also `ssh_keys` has changed to `ssh_gpg_keys` in #1293 

I just translated the GPG-strings in a fork to german: https://github.com/pree/gitea/commit/f3ff7d098226858ce18b9d511b87de288cbd5e4c

**Comment by lunny** [comment]
Yes. We have to upload the ini file to crowdin.

**Comment by techknowlogick** [comment]
Can this be closed?
