### ISSUE TITLE
keep installed packages when updating to newer versions

### ISSUE THREAD

**Issue by daviddoji** [go-gitea/gitea#16265]
- Gitea version (or commit ref): 1.14.3
- Git version: 2.30.2
- Operating system: Ubuntu Server 20.04.2
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
  - [X] MariaDB
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
- Log gist:

## Description

Last couple of times I updated the image (from 1.14.1 to 1.14.2 and now to 1.14.3), the rendering of jupyter notebooks was lost.
However, the "app.ini" file was still modified with the instructions from the official documentation but, as the dependencies were wiped out when pulling the new image, I could not make the render. The solution was to reinstall the packages.

I do my updates by simply modifying a docker-compose file and bringing it up with ```docker-compose up -d```.

Is there a way to keep those installed packages (for the rendering) amongst updates?

If not, is there any alternative to make the automatized the installation of the needed package?

Cheers,
David

P.S.: Thanks for making gitea :D
...

**Comment by noerw** [comment]
Docker images are immutable at runtime, so that's expected.
The way to go is to use the official gitea docker image as a base image, where you add your custom dependencies during build time.
