### ISSUE TITLE
User avatar in profile page changed from s=290 to s=580 while rendered at s=128 anyway

### ISSUE THREAD

**Issue by strk** [go-gitea/gitea#16287]
Gitea 1.14.3 is requesting Libravatar avatar images with size 580 in profile page while rendering them at 128x128.
Older versino 1.12.3 was requesting a size of 290 instead.

I think it would make sense to request s=128 instead, to reduce the download time

**Comment by zeripath** [comment]
See https://github.com/go-gitea/gitea/issues/15453

**Comment by strk** [comment]
That ticket shows that passing a size is what changed, but doesn't explain why we're passing a size of 580 when rendering the image at 128, is that an UI issue which went unnoticed before ?

**Comment by strk** [comment]
290 constant is still present in `modules/avatar/avatar.go`:
```
// AvatarSize returns avatar's size
const AvatarSize = 290
```

What was the AvatarRenderedSizeFactor introduced for ?

It looks like be745be0a4f3feab01f896f1c0f17164bb30234b doubled it from a factor of 2 to a factor of 4 to get better avatars for Hi-DPI displays but, shouldn't all of this be decided by the frontend code and based on actual displays ?

\cc @techknowlogick @zeripath ref #15941

**Comment by strk** [comment]
Unfortunately the default size factor of 3 still breaks my avatar: https://try.gitea.io/strk (is requested at 870x870
I still think this should be based on actual user monitor rather than expecting a "one size fits all" as it is now.
