### ISSUE TITLE
Serving custom public files = stop working

### ISSUE THREAD

**Issue by mariuszmaximus** [go-gitea/gitea#16292]
- Gitea version (or commit ref): 1.15.0+dev-509-g2f3d3ac20
- Git version:   Git Version: 2.30.2, Wire Protocol Version 2 Enabled
- Operating system: docker on ubuntu 19.10
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [X] SQLite 
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X] No
- Log gist:

## Description

...
In my opinion stop working "Serving custom public files"  in "Customizing Gitea" https://docs.gitea.io/en-us/customizing-gitea/
I used gitea over "docker pull gitea/gitea"
a month ago it was working 
when I put file to "$GITEA_CUSTOM/public/test.jpg" I can open it in http://my-gitea.com/test.jpg
a few days ago I updated and it stopped working 

My current gitea 
Using default tag: latest
latest: Pulling from gitea/gitea
Digest: sha256:b3011b077d5d2e8ce504755e2f373c86e784e30ce1068436a74f561de3f82a89
Status: Image is up to date for gitea/gitea:latest
docker.io/gitea/gitea:latest
0ab3ec073bb1d14b00779b0bfe2e0e287c504555323fa30a16b448a7d7e4d01f

**Comment by noerw** [comment]
It might be a file permission issue, if you're sure it's about the custom files in `custom/public/`.
We need [gitea logs](https://docs.gitea.io/en-us/logging-configuration/#debugging-problems) to get to the cause of this.

**Comment by zeripath** [comment]
I think this is related to the assets root pr

Try http://my-gitea.com/assets/test.jpg

**Comment by lunny** [comment]
PR #15219 move all assets under `/assets`

**Comment by mariuszmaximus** [comment]
I confirm 
$GITEA_CUSTOM/public/test.jpg is on  http://my-gitea.com/assets/test.jpg

Please update [Serving custom public files](https://docs.gitea.io/en-us/customizing-gitea/#serving-custom-public-files)
> For example, a file image.png stored in $GITEA_CUSTOM/public/, can be accessed with the url http://gitea.domain.tld/image.png

`to:`
> For example, a file image.png stored in $GITEA_CUSTOM/public/, can be accessed with the url http://gitea.domain.tld/assets/image.png
