### ISSUE TITLE
How to login without password?

### ISSUE THREAD

**Issue by khs4640** [go-gitea/gitea#16293]
- Gitea version (or commit ref): 1.14
- Git version: 2.17.1
- Operating system: download using snap command on Ubuntu 18.04
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
- Log gist:

## Description

I installed gitea using snap on Ubuntu server.
I'm trying coding in python to interworking mail system and gitea.
My source for logging in to gitea is
```
self._s.post(url + '/user/login', data={ 'user_name' : userid, 'password' : password})
```
But, I want login without password.
Is there a way?

**Comment by adyanth** [comment]
Create an access token and use that.
![image](https://user-images.githubusercontent.com/33192449/123789623-ff34b500-d8fa-11eb-94d4-9623bf93851c.png)

**Comment by khs4640** [comment]
Thanks for your comment :)
but... What I want is to be able to login for all users on my gitea server.
So I want a way to set the same password(or token) for all users.
Is it possible with that..?

**Comment by adyanth** [comment]
If you need to get the access of the user, then you need to build an OAuth application where the user can authorize your application.

Having a global API key would be a bad security decision? You can still probably use the key from the super admin to do most of it, but won't be able to spoof users.

I'll leave it to others to comment if there is some other way.

**Comment by techknowlogick** [comment]
You could use ldap, pam, smtp to share passwords between different systems, but if you want passwordless (at least from gitea side) you could connect to an IDP that provides oauth.

The global admin does have "sudo" permissions, in that with the api you can impersonate other users as needed.
