### ISSUE TITLE
Mismatched instructions for SSH/HTTPs

### ISSUE THREAD

**Issue by adyanth** [go-gitea/gitea#16295]
- Gitea version (or commit ref): 1.15.0+dev-494-g35f37a362 built with GNU Make 4.3, go1.16.5 : bindata, timetzdata, sqlite, sqlite_unlock_notify
- Git version: 2.30.2
- Operating system: Ubuntu-20.04 Docker install
  
  
  
- Database (use `[x]`):
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes (provide example URL): https://try.gitea.io/adyanth/test
  - [ ] No
- Log gist:

## Description

See below. The instructions don't match the protocol selected after creating a repo, and on every reload.

## Screenshots

After creating a repo
![image](https://user-images.githubusercontent.com/33192449/123790753-5424fb00-d8fc-11eb-992a-ae6d9e11b7a5.png)

2nd repo
![image](https://user-images.githubusercontent.com/33192449/123790835-6868f800-d8fc-11eb-910a-822cf5d1244b.png)

Switch to SSH
![image](https://user-images.githubusercontent.com/33192449/123790882-73238d00-d8fc-11eb-9fce-4665ed10422e.png)

Switch back to HTTPS
![image](https://user-images.githubusercontent.com/33192449/123790939-82a2d600-d8fc-11eb-8eed-5ae611cb235b.png)

Reload page
![image](https://user-images.githubusercontent.com/33192449/123791186-c39aea80-d8fc-11eb-939f-dc929b4793bc.png)

This is inconsistent behavior as one would expect the instructions to align with the selected scheme.

**Comment by 6543** [comment]
note: if you klick to ssh and back to https, it get changed to a valid https commands ...

**Comment by adyanth** [comment]
Yes, also provided screenshots for the same.
Meaning it can show https commands, but won't do by default.
