### ISSUE TITLE
Characters like "&" in Organization Full Name are converted/displayed as html

### ISSUE THREAD

**Issue by dalito** [go-gitea/gitea#1629]
- Can you reproduce the bug at https://try.gitea.io: (ver. 1.1.0+143-g6853bf32)
  - [X] Yes https://try.gitea.io/ampersand
- To reproduce
  - give "a & b" as full name to an organization.
  - resulting name will be `a &amp; b`.

Description
- Ampersand and other characters are converted to raw html when entered in "Organization Full Name"

**Comment by cez81** [comment]
https://github.com/go-gitea/gitea/pull/1360

**Comment by wyattoday** [comment]
The same thing for a username's full name (for example, I have an apostrophe in my last name, rather than being displayed as "`Wyatt O'Day`" it's displayed as "`Wyatt O&#39;Day`")
