### ISSUE TITLE
RESTful URLs?

### ISSUE THREAD

**Issue by tboerger** [go-gitea/gitea#163]
I would like to update the routes definition to really follow RESTful rules instead of the current semi-RESTful routs. That makes the interaction with the API much cleaner, especially for all kinds of client implementations and singlepage application web UIs. Maybe this is something I can realise before 0.7 to have some stable API that won't change on the next version again.

**Comment by lunny** [comment]
RESTful or not, it's a question.

**Comment by fuxiaohei** [comment]
just make api routes resutful, not page routes

**Comment by lunny** [comment]
A good idea. @fuxiaohei

**Comment by tboerger** [comment]
Project is dead, close.
