### ISSUE TITLE
Feature Request: issue forms

### ISSUE THREAD

**Issue by mscdex** [go-gitea/gitea#16301]
- Gitea version (or commit ref): master/main
- Git version: n/a
- Operating system:
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
- Log gist:

## Description
It would be nice to have something like [GitHub's issue forms](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms) to make it easier/more straightforward to add issue details when submitting a new issue.

**Comment by jpraet** [comment]
Duplicated by #16353, which elaborates a bit more in detail on the issue.
