### ISSUE TITLE
Relative Image Links Are Broken In READMEs

### ISSUE THREAD

**Issue by TheBrokenRail** [go-gitea/gitea#16308]
- Gitea version (or commit ref): Both v1.14.3 (Self-Hosted) And v1.15.0+dev-516-ge8c6cead0 (https://try.gitea.io)
- Database:
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes: https://try.gitea.io/TheBrokenRail/image-test
- Log gist: https://gist.github.com/TheBrokenRail/02f26f44cd4ed89aed8f519891a63ed6

## Description
Images specified with relative links in markdown files don't load.

## Screenshots
![Screenshot from 2021-06-29 23-28-00](https://user-images.githubusercontent.com/17478432/123897597-ab918e00-d931-11eb-8793-cf2330c2f750.png)

![Screenshot from 2021-06-29 23-27-49](https://user-images.githubusercontent.com/17478432/123897604-adf3e800-d931-11eb-99b0-813d437f5c9f.png)

**Comment by zeripath** [comment]
This should be linking to

https://try.gitea.io/TheBrokenRail/image-test/media/branch/master/images/base-1024.png

But is linking to:

https://try.gitea.io/TheBrokenRail/images/base-1024.png

**Comment by zeripath** [comment]
I'm not sure how this has broken it's probably something to do with the changes to html.go or render ctx

**Comment by zeripath** [comment]
Basically I bet the prefix URL is incorrect

**Comment by zeripath** [comment]
This is really weird because this is working for me...
