### ISSUE TITLE
Get a single commit from a repository API return change files is null

### ISSUE THREAD

**Issue by xmwilldo** [go-gitea/gitea#16307]
- Gitea version (or commit ref):
1.14.1
- Git version:
git version 2.20.1
- Operating system:
Debian 10, run in docker
  
  
  
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
- Log gist:

## Description

When I call the api `GetSingleCommit` which is like `Merge branch 'release/v1.0.9'`. The return data files is null. Is that normal？

## Screenshots
![image](https://user-images.githubusercontent.com/16560252/123894803-64d38080-d991-11eb-8f2f-221cfe6ac62d.png)
![image](https://user-images.githubusercontent.com/16560252/123895000-b5e37480-d991-11eb-9b9f-3421d8ecb5a2.png)

**Comment by KN4CK3R** [comment]
Works for me: https://try.gitea.io/api/v1/repos/TheBrokenRail/image-test/git/commits/4900c79098
May got fixed since 1.14.1.

**Comment by 6543** [comment]
@xmwilldo can you upgrate to 1.14.3 ?

it works on it, example: https://codeberg.org/api/v1/repos/Codeberg/Community/git/commits/5d80a97f1989f856428faa8ad8ea03aa6a36920a

**Comment by xmwilldo** [comment]
Actually, This is for this situation. The commit is like this
![image](https://user-images.githubusercontent.com/16560252/124049650-8f820f80-da4b-11eb-9ca2-546fcfe2a0dc.png)
and it has tow parent commits, like this
![image](https://user-images.githubusercontent.com/16560252/124049727-af193800-da4b-11eb-81b3-844293cfebb9.png)
In this situation, the file belonging to this commit `36b02272a3` is empty.

**Comment by 6543** [comment]
it it's a merge commit, the commit itselve does not change files

**Comment by xmwilldo** [comment]
so, it's normal. ok, thanks.
