### ISSUE TITLE
Provide a Jenkins plugin for gitea

### ISSUE THREAD

**Issue by martinellison** [go-gitea/gitea#1631]
Please provide a Jenkins plugin for gitea so that we can automate builds.

Note: there is a gogs plugin for Jenkins (does this work with gitea?).

**Comment by lunny** [comment]
@martinellison It should be work since Gitea is forked from Gogs.

**Comment by strk** [comment]
See https://github.com/jenkinsci/gogs-webhook-plugin/issues/6

**Comment by stephenc** [comment]
Actually see https://github.com/jenkinsci/gitea-plugin

**Comment by vynshin** [comment]
I had tried installing the gitea-plugin a couple times on a the latest jenkins build 2.107.3 but it doesn't seem to work.

**Comment by jalcine** [comment]
Echoing what @gchung01 mentioned; the documentation on both the plugin page and the README of the plugin doesn't give much information on how to use it.

**Comment by bkahlerventer** [comment]
Tried to use the plugin on gitea 1.5.1  It always gives Could not communicate with server: HTTP 403/Forbidden.  Tried using gitea token.  The plugin appears abandoned, last updates are 6 months ago, there is no way to contact the owner.

**Comment by stephenc** [comment]
Token does not work at present *by design* as the Jenkins git plugin doesn’t support redaction of the token from the logs. Just use user/pass

**Comment by stephenc** [comment]
(I am waiting on gitea to expose tag details via rest api before I allocate my next time budget to this plugin... been waiting a while now and no progress yet https://github.com/go-gitea/gitea/issues/2738 if you have any influence)

**Comment by lafriks** [comment]
@stephenc we are already feature freeze but I will implement it in next version

**Comment by stephenc** [comment]
@lafriks totally fine... just ping me when #2738 is implements (or you have an easy to try prototype) and I'll schedule a slot to put some work in the plugin to consume the new api)

**Comment by bkahlerventer** [comment]
> Token does not work at present _by design_ as the Jenkins git plugin doesn’t support redaction of the token from the logs. Just use user/pass

@stephenc if I understand you correctly I should encode the user name and password with the URL in Jenkins config?  I tried that but I still get "Could not communicate with server: HTTP 403/Forbidden".  

Whether I turn on manage hooks and select a credential user with full admin rights on gitea, or supply userid:password or both, the gitea plugin always give me a 403/Forbidden message.  I am running gitea on my local laptop and access it via http://localhost:3000

Update: Event tried ip address, http://127.0.0.1:3000 - no go.

**Comment by stephenc** [comment]
You can... that's at the job configure page

**Comment by stephenc** [comment]
I'm uploading a video to youtube to show a quick walk through of set-up from scratch... give it a few minutes to encode

**Comment by stephenc** [comment]
Uploading is slow too... not just encoding!

**Comment by bkahlerventer** [comment]
no problem... :-)

**Comment by stephenc** [comment]
At approx 9:06 in the video you will see the credentials drop down in an org folder. There are equivalent drop-downs in the other job types. There should be an `Add` button beside, but even if there isn't you can use the Jenkins credentials management screen to add the credential and it should show in the drop down.

<img width="1214" alt="screenshot 2018-12-05 at 11 04 35" src="https://user-images.githubusercontent.com/209336/49509615-ca187100-f87d-11e8-8b42-c45a34d3edfd.png">

**Comment by stephenc** [comment]
https://youtu.be/B4boQozMaRA is claimed to be the video URL (now youtube is processing it)

**Comment by stephenc** [comment]
ok video is live. there is no audio!

**Comment by jalcine** [comment]
I appreciate you clarifying that @stephenc!
