### ISSUE TITLE
Let Previous/ Next Button Cycle When There is no Previous/ Next Comment

### ISSUE THREAD

**Issue by delvh** [go-gitea/gitea#16317]
- Gitea version (or commit ref): 1.15.0+dev-521-g365c4e931
- Can you reproduce the bug at https://try.gitea.io:
  - Yes [here](https://try.gitea.io/delvh/kanban-test/pulls/10/files)
## Description
Currently, the next/ previous button for the next or previous PR comment will be shown regardless whether there actually is a next or previous PR comment. Clicking them in this state simply does nothing.
~~It would be more intuitive if either these buttons would be disabled or completely removed when no such comment exists.~~

Another approach would be to circularly link to the next comment, meaning that clicking on `previous` on the first comment would link to the last comment, and vice versa. This could even be better than disabling them, especially when they are still opened.

## Screenshots

![image](https://user-images.githubusercontent.com/51889757/124025094-5799ae80-d9f0-11eb-9f21-8e06c838dada.png)
Currently, the previous button gets displayed even for the first PR comment

**Comment by jpraet** [comment]
Making it wrap around circularly between first and last comment would be easiest.

Review comments can be added and deleted dynamically without a page refresh, so what is at one point the first comment, could become the second comment later on, if you add a new comment above it in the diff. Dynamically toggling the visibility of these buttons could be challenging.

**Comment by delvh** [comment]
Then I would suggest the circular approach instead of the disabling approach. Also, I can see this to be much easier to implement. In parts, it should even be more user friendly, as it allows to switch in the best case from top to bottom or vice versa instantly, which is definitely needed from time to time.
