### ISSUE TITLE
Change default theme to arc-green

### ISSUE THREAD

**Issue by delvh** [go-gitea/gitea#16315]
- Gitea version (or commit ref): 1.15.0+dev-519-g7d70a6eff
- Can you reproduce the bug at https://try.gitea.io:
  - Yes, simply log out
## Description
Gitea is shown in the light theme by default for anyone not logged in.
Judging by my personal experience, it would be better if the default webpage would be shown by using the `arc-green` theme, since that is much more lenient on the eyes, especially around nighttime.
So, it would be great, if the default site appearance could be changed to dark.
Normally, it simply is much less painful to switch voluntarily from dark to light  than it is to switch from light to dark as the damage is then already done.

Or, alternatively, a configuration could be added that sets the default theme used for this server, until the visitor logs in and gets his requested theme.

## Screenshots
![image](https://user-images.githubusercontent.com/51889757/124020266-59f90a00-d9ea-11eb-88e4-b2b84e9bea4c.png)
Default display shown for not logged in users

**Comment by jolheiser** [comment]
You can change the [default theme](https://docs.gitea.io/en-us/config-cheat-sheet/#ui-ui) already.

**Comment by delvh** [comment]
my bad
