### ISSUE TITLE
"Clone repository" page of newly generated project shows wrong information

### ISSUE THREAD

**Issue by penpendede** [go-gitea/gitea#16328]
- Gitea version (or commit ref): 1.14.3
- Git version: 2.29.0
- Operating system: Ubuntu 18.04.5 LTS
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
- Log gist:

## Description

Searching the issues I couldn't find that this already has been reported: As the screenshot illustrates, even though HTTP is selected, the information shown is for SSH. Moreover the address shows localhost while a FQDN is configured and displays for existing projects' clone URLs. I just switched to 1.4.3 as the issue showed up after switching to 1.4.2; prior to that I have been using 1.3.5 where the issue was abesent .

## Screenshots

![clone_repo_broken](https://user-images.githubusercontent.com/9119675/124292391-ce9c8780-db55-11eb-981e-ed91d0ace8ed.png)

**Comment by a1012112796** [comment]
@penpendede The gitea version (1.4.3) is too old, suggest upgrade at first, Thanks.

**Comment by jpraet** [comment]
I think this is fixed by #16302

**Comment by penpendede** [comment]
Seems somewhere along the line a digit was lost, the version is 1.**14**.3 (i.e. the latest), not 1.**4**.3.

**Comment by zeripath** [comment]
Already fixed by #16302
