### ISSUE TITLE
The mirror settings in repo settings > Repo tab are not displayed

### ISSUE THREAD

**Issue by Clemorange22** [go-gitea/gitea#16322]
- Gitea version (or commit ref): 1.14.3 release ( installed from yunohost)
- Git version: 2.20.1
- Operating system: Debian 10

  
I'm running gitea from systemd
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X] No , It works

## Description

First, thanks for this awesome project !
My problem is really dumb.
When I go in the settings of my repo, I don't see the mirrors settings.
It is implemented in 1.14.3 ?
If yes, how can I enable it ?

## Screenshots

![image](https://user-images.githubusercontent.com/62897760/124117025-eb5e8f80-da6f-11eb-9cc7-28f6e031e4c6.png)

**Comment by haiderim** [comment]
Same issue on 1.14.4, Ubuntu 20.04.

**Comment by techknowlogick** [comment]
This is a 1.15 feature
