### ISSUE TITLE
no webhook triggers when click the start review button

### ISSUE THREAD

**Issue by lchrennew** [go-gitea/gitea#16333]
- Gitea version (or commit ref): 1.14.3
- Git version:
- Operating system:
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
- Log gist:

## Description

...

## Screenshots
![image](https://user-images.githubusercontent.com/1522365/124361375-794d9c80-dc61-11eb-90c0-0e5a849975ea.png)

**Comment by jpraet** [comment]
Should it trigger a webhook? It is a "pending" review. The comments are only visible to you until you submit the review.

**Comment by lchrennew** [comment]
> Should it trigger a webhook? It is a "pending" review. The comments are only visible to you until you submit the review.

I see, if there's any API can fetch these comments and their positions, this webhook is unneccesary. Is there?

**Comment by jpraet** [comment]
Yes there is. You can find the id of the pending review with https://try.gitea.io/api/swagger#/repository/repoListPullReviews.
Then, you can access the comments with https://try.gitea.io/api/swagger#/repository/repoGetPullReviewComments.

**Comment by lchrennew** [comment]
> Yes there is. You can find the id of the pending review with https://try.gitea.io/api/swagger#/repository/repoListPullReviews.
> Then, you can access the comments with https://try.gitea.io/api/swagger#/repository/repoGetPullReviewComments.

That's great! Thank you very much!
