### ISSUE TITLE
Relative paths in Markdown <img> tags not working

### ISSUE THREAD

**Issue by moqmar** [go-gitea/gitea#16336]
- Gitea version (or commit ref): ac84bb7183a58a60c056f4fa5f6059392339b41b
- Git version: N/A
- Operating system: Docker, using the provided Dockerfile
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes: https://try.gitea.io/momar/test
  - [ ] No
- Log gist: N/A

## Description
`<img src="test.jpg>` in Markdown files now refers to the relative path as the browser would see it, while `![](test.jpg)` refers to the relative path in the repository - before, both would work as a relative path. This was discovered in https://codeberg.org/Codeberg/Community/issues/478 and is explained there in more detail; also see the example repository (the uppermost two images were rendering before the commit referenced above and now aren't anymore).

Seems like this is a regression to #8830, which was solved by #10515. The problematic PR is #16098

## Screenshots

![grafik](https://user-images.githubusercontent.com/5559994/124376804-023bf680-dca9-11eb-9c71-321bce5432fc.png)

**Comment by moqmar** [comment]
Aaah, I think I found the issue! `node.Attr[idx].Val` is not the same reference as `attr.Val`.

**Comment by 6543** [comment]
#16334
