### ISSUE TITLE
gitea executable printing spurious line starting with `frequencies():` early in startup

### ISSUE THREAD

**Issue by bjj** [go-gitea/gitea#16345]
- Gitea version (or commit ref): Gitea version 1.15.0+dev-541-g5bb97a12d built with GNU Make 4.3, go1.16.5 : bindata, timetzdata, sqlite, sqlite_unlock_notify
- Git version:
- Operating system: Linux 4.4.59+ #25426 SMP PREEMPT Wed Jul 8 03:21:29 CST 2020 x86_64 GNU/Linux synology_apollolake_718+

This is gitea/gitea:latest 1c8c5cb40181

## Description
The `gitea` executable is printing a spurious line to stdout, breaking `ssh`:

```
# docker exec -it gitea /bin/bash
bash-5.1# gitea
frequencies():  19200000 234 3 -> 1497600000
2021/07/05 15:27:16 cmd/web.go:97:runWeb() [I] Starting Gitea on PID: 2526
2021/07/05 15:27:16 ...s/setting/setting.go:911:NewContext() [F] Expect user 'git' but current user is: root
```

The `frequencies():  19200000 234 3 -> 1497600000` comes out very early. I can't figure out what is printing it. From `strace` it is right after something tries to open `"/proc/self/cpuset"`.

This breaks `ssh` access because it comes out there too:

```
3# ssh git@localhost -p 222
PTY allocation request failed on channel 0
frequencies():  19200000 234 3 -> 1497600000
Hi there, bjj! You've successfully authenticated with the key named Orion Root, but Gitea does not provide shell access.
If this is unexpected, please log in with password and setup Gitea under another user.
Connection to localhost closed.
```

**Comment by bjj** [comment]
Forgot to mention what the actual error from `git` looks like because it is unobvious: `fatal: protocol error: bad line length character: freq`. This is a terrible error message which just means it didn't see the git protocol on connection (instead, it saw that `frequencies...` output and interpreted the first 4 bytes as something it expected)

**Comment by lunarys** [comment]
Same for me.

**Comment by bjj** [comment]
Looks like some progress on this in #16358

**Comment by techknowlogick** [comment]
Even though this one was opened sooner, I will close it in preference of #16358 as it has some progress in it.
