### ISSUE TITLE
/api/swagger is public visible if  REQUIRE_SIGNIN_VIEW is true

### ISSUE THREAD

**Issue by r10r** [go-gitea/gitea#16360]
- Gitea version (or commit ref):1.14.2

Hi there,

I'm a new, and very impressed, gitea user.

I've installed gitea for internal and external use  and want to show the swagger ui '/api/swagger' 
only for authenticated users. 

I did set `REQUIRE_SIGNIN_VIEW: true`. The `Explore` now shows the sign-in view but the swagger view is still visible for unauthenticated users.

> REQUIRE_SIGNIN_VIEW: false: Enable this to force users to log in to view any page or to use API.

Is that intended behaviour or a bug ?

Regards,
Ruben

**Comment by lunny** [comment]
I think that's by designer. i.e. Even Github enterprise's API docs are also open.

**Comment by r10r** [comment]
Ok, then maybe the documentation for `REQUIRE_SIGNIN_VIEW` should be changed from

> REQUIRE_SIGNIN_VIEW: false: Enable this to force users to log in to view any page or to use API.

into something like

>REQUIRE_SIGNIN_VIEW: false: Enable this to force users to log in to view any page except the API pages.

**Comment by techknowlogick** [comment]
The API is still blocked from being accessed, it's only the swagger documentation that is available.

**Comment by r10r** [comment]
Ok I see. For a new user like me the wording `view any page` may include the swagger API pages, but since swagger can be disabled separately I simply got it wrong. Thanks for clarification!

> The API is still blocked from being accessed.

Does that mean that there are API calls that can be made without an access token otherwise ?

**Comment by techknowlogick** [comment]
> Does that mean that there are API calls that can be made without an access token otherwise ?

API would need access token. For example going to example.com/api/v1/version would return an error saying auth is needed.

**Comment by KN4CK3R** [comment]
That's not correct. Most read-apis do not require auth. Your example für example: https://try.gitea.io/api/v1/version

**Comment by techknowlogick** [comment]
@KN4CK3R specifically if the `REQUIRE_SIGNIN_VIEW` is set to true, then those endpoints won't be accessible.

**Comment by KN4CK3R** [comment]
Ah, I thought you talked about general access.

**Comment by r10r** [comment]
What about adding another config option to disable the swagger UI for non-authorized users ? E.g :

`api. SWAGGER_REQUIRE_SIGNIN_VIEW`

**Comment by wxiaoguang** [comment]
If you don't need it , you can set `ENABLE_SWAGGER=true`
