### ISSUE TITLE
Command that moves to a repository

### ISSUE THREAD

**Issue by vuvgaG** [go-gitea/gitea#16363]
- Gitea version (or commit ref): n/a 0.7.0

## Description

Adding a command that opens the repository.

```
$ tea move user/repo1
```

The current shells working directory would be changed to that of the root of a local repository copy.

This could be done by using a shell wrapper (function for a bashrc) that listens for move commands and interprets the output into a `cd` command within the users current shell.

Shipping a bash file that can be sourced by users will enable the move command. (something like)

```bash
function teacmd()
{
  # capture the input args
  # if is a call to the move command
  # pass output to the users cd command
}
```

I'm not sure what you think about that or the idea of storing state client side?

Happy to make the PR.

**Comment by techknowlogick** [comment]
Thanks for opening this issue, the tea cli is managed here: https://gitea.com/gitea/tea/ please send all feature/bug reports there :)
