### ISSUE TITLE
oAuth / openID with skip-tls-verify

### ISSUE THREAD

**Issue by inthuriel** [go-gitea/gitea#16376]
Is it possibe to use `oauth` with `openidConnect` provider alongside with `skip-tls-verify` option?
We have `openID` provider with self-signed `SSL` and `gitea` isn't able to connect to it 
  
```bash
2021/07/08 13:22:02 main.go:117:main() [F] Failed to run app with [gitea admin auth update-oauth --id 1 --auto-discover-url [url] --key [app] --name oAuth --provider openidConnect --secret [secret]]: models.SetEngine: Failed to connect to database: Unknown database type: 
```

**Comment by noerw** [comment]
That's currently not supported as far as I can tell.
I'm also not sure skipping TLS verification is a good idea for an auth provider.
You could instead try to add your local CA used to create the self signed cert to the trust store on the system gitea is running on.

**Comment by zeripath** [comment]
Add your certificate to a copy of the root certs file and set `SSL_CERT_FILE` to the new file.

**Comment by zeripath** [comment]
If we were to provide an option to set the trusted CAs users would have to provide a file containing all root CAs.
