### ISSUE TITLE
Cannot use branch name to get CI status

### ISSUE THREAD

**Issue by pauloo27** [go-gitea/gitea#16384]
- Gitea version (or commit ref): 1.15 (probably any version tho) 
- Git version: 
- Operating system:
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No (I couldn't find a repo with CI to test it)
- Log gist:

## Description

Running `curl 'https://gitea.com/api/v1/repos/gitea/tea/commits/0f4f669cf00bb0bbf13707a5bc36aae4708d80dc/status'` returns the CI status, but `curl https://gitea.com/api/v1/repos/gitea/tea/commits/master/status` return just empty values.

## Screenshots
![image](https://user-images.githubusercontent.com/23013073/125022880-09218b00-e054-11eb-83f2-14fb5c0fed3b.png)
![image](https://user-images.githubusercontent.com/23013073/125023043-6ddce580-e054-11eb-842d-a5958c55ad24.png)

**Comment by techknowlogick** [comment]
I don't know that this is a bug, as branch names are refs, but this is looking for commit hashes. So instead of returning blank values it should be returning an error (especially as statuses are attached to commits rather than refs)

**Comment by Pauloo27** [comment]
I send as a bug, since "branch" is listed as a valid input in the docs.

![image](https://user-images.githubusercontent.com/23013073/125107920-bda0c880-e0b7-11eb-91b8-f76651f7d3b7.png)
