### ISSUE TITLE
File corrupted on https://dl.gitea.io/gitea/1.14.4/gitea-1.14.4-linux-amd64.xz

### ISSUE THREAD

**Issue by christaus** [go-gitea/gitea#16389]
https://dl.gitea.io/gitea/1.14.4/gitea-1.14.4-linux-amd64.xz

No sha256 match (twice)
The file cannot be extracted
This is not directly for github but I didn't know where to put the issue

**Comment by techknowlogick** [comment]
❯ sha256sum -c gitea-1.14.4-linux-amd64.xz.sha256
gitea-1.14.4-linux-amd64.xz: OK

returns as ok.

What is the sha of the binary you downloaded, and what is the content of the sum file?

**Comment by cGIfl300** [comment]
gitea-1.14.4-linux-amd64.xz
I have deleted both the file and the checksum but they didn't matched, if that's ok now, I guess the problem were perhaps on my side.
