### ISSUE TITLE
[Bug] - unable to find group 1000 # git: no matching entries in group file

### ISSUE THREAD

**Issue by jhult** [go-gitea/gitea#16387]
Rootless container is broken on Docker (due to #16361 I believe)

```
Error response from daemon: unable to find group 1000 # git: no matching entries in group file
```

Gitea version (or commit ref): https://hub.docker.com/layers/gitea/gitea/latest-rootless/images/sha256-b86c5ffeaf0d592e87e89b84f72ecf652fa1977248b8f6668a4590c9f9cfd765?context=explore

**Comment by jhult** [comment]
I think this is due to the attempt to put a comment at the end of the line ([which Docker does not allow](https://stackoverflow.com/a/42123446/423351)).

**Comment by 6543** [comment]
Damed ci should verify souch! :/

**Comment by 6543** [comment]
Ok lets just remove comment @jhult wana send a pull?

**Comment by jhult** [comment]
Whoops. @6543, I submitted a PR before I saw your comment.

I just moved the comment on top of the USER instruction (instead of removing it).
