### ISSUE TITLE
Support unprotected file patterns

### ISSUE THREAD

**Issue by jpraet** [go-gitea/gitea#16381]
Currently, in the branch protection settings, "Protected file patterns" can be configured:

![image](https://user-images.githubusercontent.com/2212615/124988438-45e28780-e03e-11eb-82ef-31407677f8da.png)

I propose to add support for configuring the counterpart of this: "Unprotected file patterns".

Users with write access to the repo should be able to push commits that only touch unprotected files directly to the otherwise protected branch.

**Comment by lafriks** [comment]
It could probably be added as selection on what behavior is expected for patterns matching

**Comment by jpraet** [comment]
> It could probably be added as selection on what behavior is expected for patterns matching

What if we want to configure both protected file patterns AND unprotected file patterns though?

**Comment by lafriks** [comment]
They would be conflicting imho, how that would work?

**Comment by jpraet** [comment]
I think they are complementary. For example:
* protected_file_patterns: `/LICENSE.md`
* unprotected_file_patterns: `/docs/**`

And protected_file_patterns takes precedence: when a changed path matches both protected_file_patterns and unprotected_file_patterns, it will be treated as protected.

**Comment by lafriks** [comment]
But if I understand correctly that if I have write to the repo and there is unprotected_file_patterns set like in your example I would not be able to modify `/LICENSE.md` anyway even with no `protected_file_patterns` set as I can only modify files in `/docs/` directory.

**Comment by jpraet** [comment]
With unprotected_file_patterns, people with write access to the repo can modify those files even if they are not allowed to push directly to the branch. It is to allow to bypass the PR workflow.
