### ISSUE TITLE
Upgrade from 1.8.3 to 1.14.4 :  Table project column board_type db type is INT(10) UNSIGNED, struct type is INT UNSIGNED

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#16393]
- Gitea version (or commit ref):1.14.4
- Git version:2.17.1
- Operating system:Ubuntu 18.04.5 LTS
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No

## Description
After converting 1.8.3 to 1.14.4, i have succeeded to fix almost problems with : 
SET GLOBAL innodb_file_format=Barracuda;
SET GLOBAL innodb_file_per_table=ON;
SET GLOBAL innodb_large_prefix=1;

I do not use docker. 
Install and upgrade from binaries gitea (gitea-1.14.4-linux-amd64). 

But i always have those two error while trying to run gitea : 
2021/07/10 13:03:21 ...rfave/cli/command.go:173:Run() [W] Table project column board_type db type is INT(10) UNSIGNED, struct type is INT UNSIGNED
2021/07/10 13:03:21 ...rfave/cli/command.go:173:Run() [W] Table project column type db type is INT(10) UNSIGNED, struct type is INT UNSIGNED

I tried also a doctor recreate-table everything is fined except for : 

2021/07/10 13:14:32 ...rfave/cli/command.go:372:startApp() [W] Table project column board_type db type is INT(10) UNSIGNED, struct type is INT UNSIGNED
2021/07/10 13:14:32 ...rfave/cli/command.go:372:startApp() [W] Table project column type db type is INT(10) UNSIGNED, struct type is INT UNSIGNED

Any help ? 

Thanks, 
Patrice

**Comment by pat75007** [comment]
Precision : I am using MariaDB Server : 10.1.48-MariaDB-0ubuntu0.18.04.1 - Ubuntu 18.04
Default table type : InnoDB
Default charset : utf8mb4

**Comment by zeripath** [comment]
These warning can be ignored but if you really want them to disappear, `gitea doctor recreate-table project` should fix it.
