### ISSUE TITLE
Plantuml still not working :(

### ISSUE THREAD

**Issue by Sepphod** [go-gitea/gitea#16397]
I would like to reopen #14219 as plantuml code in comments is still not working.

**Comment by techknowlogick** [comment]
Please fill in the issue template when opening issues, the PR that closed the linked issue is merged for 1.15 which has yet to be released.

**Comment by Sepphod** [comment]
sry my mistake I didn't see that info - thx anyway

**Comment by lunny** [comment]
Which version are you using?
