### ISSUE TITLE
Can I add the feature to allow query params for new file name and contents?

### ISSUE THREAD

**Issue by coolaj86** [go-gitea/gitea#16398]
Gitea lets you open a URL to create a new file at a given path, like this:

```
https://git.example.com/example/project/_new/master/path/to
```

Github allows you to also specify the [name of the file, and some contents](https://github.com/isaacs/github/issues/1527#issuecomment-617466083), like this:

```
https://github.com/example/project/new/master
        ?filename=path/to/hello.md
        &value=Hello+World!
```

I would like to add this feature to gitea.

- [x] Would this be acceptable?
- [x] How can I find the JavaScript file I would need to edit to add this?
- [x] Where should I add documentation for a feature like this?

**Comment by noerw** [comment]
Hi!

1. :+1:  I'm confident this will be accepted
2. You could populate the field with javascript, or handle this in the serverside templating (we use mostly use the latter option, though I can see that this is not needed in this case). Add [here](https://github.com/go-gitea/gitea/blob/522b72095493a72796a3b2e6caaac757c527f979/web_src/js/index.js#L111) if you do it in JS, add [here](https://github.com/go-gitea/gitea/blob/522b72095493a72796a3b2e6caaac757c527f979/routers/web/repo/editor.go#L139) and potentially [here](https://github.com/go-gitea/gitea/blob/522b72095493a72796a3b2e6caaac757c527f979/templates/repo/editor/edit.tmpl#L19) for the templating approach.
3. As this feature probably targets devs that want to integrate with Gitea mostly, the [developers section](https://github.com/go-gitea/gitea/tree/main/docs/content/doc/developers) of our docs would be good

**Comment by coolaj86** [comment]
Thanks. I've got this in my queue of side projects. I hope to work on this within the next two weeks.

**Comment by coolaj86** [comment]
The blog project I've been working on that depends on this change is now at a stage where it will be immediately useful:

https://bliss.coolaj86.com/

To demonstrate:
1. Enter some content
2. Enter a title
3. Select `Blog: Eon`, `Git: Gitea`
4. Paste the repo url in the Repo section
5. Click "Create on Gitea"

<img width="800" alt="Screen Shot 2021-07-26 at 3 17 25 AM" src="https://user-images.githubusercontent.com/122831/126965218-fb3f4bbd-4b19-47a7-98ed-7a27782f4a0c.png">

**Comment by coolaj86** [comment]
Done. Merged. Awesome!
