### ISSUE TITLE
505 error

### ISSUE THREAD

**Issue by Nirmalashaanmugasundaram** [go-gitea/gitea#16403]
- Gitea version (or commit ref):
- Git version:
- Operating system:
  
  
  
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
- Log gist:

## Description

...

**Comment by Nirmalashaanmugasundaram** [comment]
505 error

**Comment by noerw** [comment]
?
