### ISSUE TITLE
[LFS] video player cannot be controlled 

### ISSUE THREAD

**Issue by marxangels** [go-gitea/gitea#16414]
The progress bar of the HTML `video` player cannot be dragged, in other words, the player cannot be controlled to play on the specified position. 

To fix this we need support for the `Accept-Ranges: bytes` HTTP header.

**Comment by wxiaoguang** [comment]
Related to 
* #18448

**Comment by wxiaoguang** [comment]
Will be fixed by  Make repository response support HTTP range request #24592
