### ISSUE TITLE
User name with spaces

### ISSUE THREAD

**Issue by RickZeeland** [go-gitea/gitea#1641]
- Gitea version (or commit ref): gitea-1.1-windows-4.0-amd64.exe
- Git version: 2.12.2
- Operating system: Windows 10
- Database (use `[x]`):
  - [x ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x ] Not relevant
- Log gist:

## Description
When adding users in Gitea, the name can not contain spaces.
This is a bit awkward as we have all names configured with spaces, and this works without problems in GIT and TeamCity.

**Comment by bkcsoft** [comment]
There's a difference between username and fullname, one can't create a username with space on GitHub or other sites either. You can however set the fullname to whatever you want :)

**Comment by RickZeeland** [comment]
Then I find the help on [https://help.github.com/articles/setting-your-username-in-git/](url) very confusing, in the example "Mona Lisa" is used as a user name.

**Comment by cez81** [comment]
username != user name. username is name to sign in to system whilst user name is the name of the user. The setting configured in the example is the user name.
