### ISSUE TITLE
bugfix: concurrent save getIssueFullPattern

### ISSUE THREAD

**Issue by Dexus** [go-gitea/gitea#16415]
- Gitea version (or commit ref):  https://github.com/go-gitea/gitea/commit/5ff807acdebdd75960418060f465bb8ba79e96a6

Make sure the function in modules/makeup/html.go getIssueFullPattern() is concurrent save.

**Comment by 6543** [comment]
function `Init()` in modules/markup/renderer.go will initialize it so there should not be a race ... but I did a code cleanup with #16417

**Comment by 6543** [comment]
roadmap:
 * remove call in `Init()` at modules/markup/renderer.go
 * add an sync.Once lock next to `issueFullPattern` ... call it **issueFullPatternInitOnce** or so?
 * add an issueFullPatternInitOnce.Once(func() { init regex ... } ) to getIssueFullPattern()

@Dexus
