### ISSUE TITLE
Plan of Gitea v1.16

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#16429]
Hi all Gitea contributors,

Gitea 1.15rc1 will be out sooner (🎉!) and after that we will create a new branch for 1.16 development. As mentioned in our [CONTRIBUTION](https://github.com/go-gitea/gitea/blob/main/CONTRIBUTING.md#releasing-gitea), it will spend three or four months before feature freeze.

I'm aware now is the time for the regular planning thread. Please use it to discuss your own plans for the 1.16 development cycle.

(Reminder, this thread is for things you *PLAN TO DO YOURSELF*, not things you want other people to do.)

Thanks,
Lunny

**Comment by lunny** [comment]
I plan to finish some of my previous PRs at first, #16083, #16052, #15398 and #6918 . And I also want to resolve the problems when migrating Gitea from Github to gitea.com .

If I have more time, I would like to try to support Github actions on Gitea.

**Comment by zeripath** [comment]
## Authentication/Authorization refactors

models/login_source needs to be simplified and we need to make authentication and authorization a bit clearer.

* #16199 is the beginning of this and following on from this I intend to look at Oauth providers a bit to make adding additional ones a lot simpler. I suspect we can prevent the creation of these goth users etc.
* Following on from #16199 I think we should be able to make it possible to create and use OAuth tokens with restricted permissions. This would require a clearer idea of context and permissions but it's something we need to do.

This is likely to represent a large refactoring series with multiple PRs and will probably represent the bulk of the things.

(It's worth noting that although this may appear orthogonal to things like federation - this is will be key to making federation possible.)

## Rendering repositories

Now we pass a context in to get last commit we can give the last commit generator a deadline and make it return what it has found within that deadline. A simple solution would then refresh the page to find the missing entries but if we paged the repository viewer we could actually make things a lot quicker there too. 

## Diff generation

It's way past time we move this out of the main thread. 

My work on 1.15 was massively derailed by the git and go-git problems so this might actually finally pop to the top of the list again.

## Caching

Now we have a memory cache implementation (twoqueue) that is not unbounded in the number of objects it will and can store we can consider caching more things. A good candidate could be commit verification as the cache invalidation is predictable.

It's likely that the simplistic solution within twoqueue may need further optimization as people try it - but hopefully we'll be able to consider it ready to make it the default for 1.16. Another thing is that it may be helpful to consider having a two level cache.

## Queues

We still need to merge/consider the Pause Queues PR. This is likely to be very important for users of things like elasticsearch which may stop or start.

**Comment by jolheiser** [comment]
## Existing PRs
- [ ] #14686 
- [ ] #14538 
   - Another PR after this that uses bundles instead of bare repos in archives
- [ ] #14334 

## Other plans
- [ ] #14693
- [ ] Continue working on OpenGraph image implementation
- [ ] Possibly #12233

**Comment by lafriks** [comment]
## Automatically pause queues if Elastic becomes available and viceversa
- [ ] #15066 (based on @zeripath pausable queues)

## Secrets storage
- [ ] #14483

## Advanced labels with priority
- [ ] #11669

## CI integration into Gitea UI
- [ ] Woodpecker runner
- [ ] GitLab runner

**Comment by a1012112796** [comment]
## Existing PRs

- [ ] #14295 
- [ ] #16125 
- [ ] #15870
- [ ] #13585

**Comment by kolaente** [comment]
I hope to finally find the time to work on https://github.com/go-gitea/gitea/pull/9307 and maybe https://github.com/go-gitea/gitea/pull/14003.

**Comment by chrvip** [comment]
I hope to can paste picture from cutboard when I create an issue.

**Comment by richmahn** [comment]
Having got into CSV/TSV for my company and how they render, I noticed a lot of bugs, which I created issues for last week. Will at least be fixing those, and back porting to v1.15.X if needed.

**Comment by vwbusguy** [comment]
These are some low hanging fruit that have been asked for over several releases that I'd love to see picked up:

- https://github.com/go-gitea/gitea/pull/7225
- https://github.com/go-gitea/gitea/pull/7182
- https://github.com/go-gitea/gitea/issues/822

**Comment by techknowlogick** [comment]
Now that the RC is coming soon(tm) I will close this, and when 1.17-dev is here we can open a new one for that.
