### ISSUE TITLE
Webhook for Telegram doesn`t work

### ISSUE THREAD

**Issue by sergey-perepelkin** [go-gitea/gitea#16436]
Hi,

I can`t configure Telegram Webhook.

My steps:

Create Bot via botfather, got botID on email

Got chat ID via special bots.

Go to http://localhost:3000/admin/hooks create Telegram WebHook:
Set up bot token:
123456:XXXXXX
Chat ID:
-123456
Events:
All Events

4. Test: Created Task, Edited task, commited in master - no messages
Also "recent Deliveries" are empty

But it is working via this response in browser.
https://api.telegram.org/bot123456:XXXXXXXXXXXXXXX/sendMessage?chat_id=-123456&text=test

Thanks.
Sergey.

- Gitea version (or commit ref): Gitea 1.14.3, built from source (also tried binary, 1.14.2, 1.14.4)
- Git version: 2.20.1
- Operating system: Debian 10, 4.19.0-17-amd64, systemd 241
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X] No

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
I think I followed the same steps to create a bot and the rest
However, if the webhook works from web (as you said) and `curl` (I'd try that from the host where Gitea is running), I'd like to postulate it might be a matter of either not having webhooks enabled in Gitea's config (the `app.ini` file) or perhaps even sth to do with running Gitea locally without a domain and a public IP.
More probably the former.
