### ISSUE TITLE
GC and Health checks fail, maybe caused by bug in git migration?

### ISSUE THREAD

**Issue by R3dByt3** [go-gitea/gitea#16441]
- Gitea version (or commit ref): 1.14.3
- Git version: 2.20.1 (server sided)
- Operating system: Debian 10.10
  "Your gitea build"
 systemd
  Linux version 4.19.0-17-amd64
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Cannot (Admin required)
- Log gist:
2021/07/15 17:49:02 .../repository/check.go:39:func1() [W] Failed to health check repository (&{8812 320 ORG <nil> name DESC  1 MIGRATED_FROM_LINK develop 2 0 0 1 0 1 0 0 0 0 0 0 0 0 0 true false false false <nil> 0 map[] map[] [] <nil> false 0 <nil> false 0 <nil> 1966289376 <nil> <nil> true false [] default 8812-099d026b04c807c40b9c6236915c97e5 1626267202 1626346148}): context deadline exceeded
2021/07/15 17:49:02 models/admin.go:53:createNotice() [I] [SQL] INSERT INTO `notice` (`type`,`description`,`created_unix`) VALUES (?,?,?) [1 Failed to health check repository (ORG/REPO): context deadline exceeded 1626364142] - 1.809991ms
2021/07/15 17:49:02 .../repository/check.go:39:func1() [W] Failed to health check repository (&{8813 320 ORG <nil> repo REPO DESC  0  master 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 true false false false <nil> 0 map[] map[] [] <nil> false 0 <nil> false 0 <nil> 19661807907 <nil> <nil> true false [] default  1626276924 1626361222}): context deadline exceeded
2021/07/15 17:49:02 models/admin.go:53:createNotice() [I] [SQL] INSERT INTO `notice` (`type`,`description`,`created_unix`) VALUES (?,?,?) [1 Failed to health check repository (ORG/REPO): context deadline exceeded 1626364142] - 1.297265ms
2021/07/15 17:49:02 models/admin.go:53:createNotice() [I] [SQL] INSERT INTO `notice` (`type`,`description`,`created_unix`) VALUES (?,?,?) [2 Task: Health check all repositories started by gerdel has finished 1626364142] - 1.38977ms

.ini:
[migrations]
ALLOW_LOCALNETWORKS = true

[git.timeout]
MIGRATE = 1800
GC = 1800

[cron.git_gc_repos]
ENABLED = true
RUN_AT_START = true
TIMEOUT = 1800

[cron.repo_health_check]
TIMEOUT = 1800

## Description
After setting up a fresh gitea server, I migrated several hundred repos into it. Afterwards I took one of these repos and migrated it to LFS, via git lfs migrate and pushed it into a newly created repo of the gitea server.

After starting a health check, the health check fails within a few seconds for >1000 repos with the following message: "context deadline exceeded"

After starting a garbage collection, the garbage fails and stops with the first repo, also with the following message: "context deadline exceeded"

After investigating the logfile, I saw that every error included the repo url from the migration source.

May this be caused by the migration process or are my repos corrupted?

**Comment by zeripath** [comment]
`context deadline exceeded` - means that `git fsck` etc took too long.

Change these settings:

https://docs.gitea.io/en-us/config-cheat-sheet/#git---timeout-settings-gittimeout

**Comment by R3dByt3** [comment]
Do you mean this part? ;;(For GC)
[git.timeout]
GC = 1800

[cron.repo_health_check] ;;(For fsck)
TIMEOUT = 1800

These were the only options I could find.

If yes these are included already, also it seems the default timeout is less than 1 second (because it fails directly), what seems weird to me.

**Comment by zeripath** [comment]
```
[cron.repo_health_check] ;;(For fsck)
TIMEOUT = 1800s
```

**Comment by R3dByt3** [comment]
Ahh well I didn't saw the 's'..

Sorry about that.

I will try it out by tomorrow, give you feedback and close the issue if it's resolved.

Thank you for your time in advance.

**Comment by zeripath** [comment]
> Ahh well I didn't saw the 's'..

There's an inconsistency in the `git.timeout` configuration vs. the `cron` configuration. It's hard to fix though because the `git.timeout` although the configuration options should be using the duration notation changing it would be a seriously breaking configuration change.

**Comment by R3dByt3** [comment]
Just my own 2 cents:

What about the idea of killing the process if the config has not parsable content;
This way the user is directly informed about his mistake, because there is no gitea and the log / console's last line would be like:
"Invalid value found for XXX" (Did you forget the unit of time?) For example?

**Comment by zeripath** [comment]
it is parsable. 

Just that the 1800 was interpreted as 1800 ms not seconds
