### ISSUE TITLE
[question] Docker latest image - Gitea version - Hash no longer in info?

### ISSUE THREAD

**Issue by bkraul** [go-gitea/gitea#16459]
- Gitea version (or commit ref):  1.15.0+rc1
- Git version:
- Operating system: Ubuntu 20.04 (docker)
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
- Log gist:

## Description
The `latest` docker tag for the gitea image is showing the following version information:
```Gitea version 1.15.0+rc1 built with GNU Make 4.3, go1.16.6 : bindata, timetzdata, sqlite, sqlite_unlock_notify```

However, the current try.gitea.io version shows this:
```Powered by Gitea Version: 1.16.0+dev-9-g95f40047e```

I use the latter string in order to track git hash information for my dev tags archive but I find that the latest docker tag breaks this pattern. Is this going to be the case going forward? I notice there is now a `dev` tag in the list of tags at gitea's hub page. Just want to make sure I avoid regressions here.

...

**Comment by techknowlogick** [comment]
This is expected, with the release of the RC we are moving `:latest` to be the latest stable tag and `:dev` will track the latest development version.
