### ISSUE TITLE
Cannot rename non-empty repositories

### ISSUE THREAD

**Issue by arcvetkovic** [go-gitea/gitea#16475]
- Gitea version (or commit ref): 1.14.4
- Git version: 2.31.1
- Operating system: Windows Server 2019. Using an official download, installed in `C:\gitea`, run from command prompt (either as an admin or a regular user).
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
- Log gist:

## Description

I'm able to rename empty repositories. However, I get the following error when I try to rename repositories that contain commits:

```
2021/07/18 11:32:00 ...ters/repo/setting.go:102:SettingsPost() [E] ChangeRepositoryName: rename repository directory: rename D:\gitea\data\gitea-repositories\arcvetkovic\test.git D:\gitea\data\gitea-repositories\arcvetkovic\test1.git: The process cannot access the file because it is being used by another process.
```

What I've tried so far:

- I wasn't able to identify any processes using the file(s) (e.g., by using Process Explorer or similar solutions).
- After rebooting the server, the error is still there.
- Also checked that my user has modify/write permission (I'm able to rename directories by hand).
- Tried moving Gitea data from `D:` disk to `C:` as well.
- Finally, did a clean install, not only on the server but on a laptop with Windows 10 -- getting the same behavior.

**Comment by zeripath** [comment]
Can you compile Gitea or try the build mentioned here:

https://github.com/go-gitea/gitea/pull/16439#issuecomment-881457812

This should be fixed by https://github.com/go-gitea/gitea/pull/16463

**Comment by arcvetkovic** [comment]
I tried https://www.eldritchkitty.com/~andrew/gitea-1.14.5-16463-windows-4.0-amd64.exe, but didn't work (same error message).

**Comment by zeripath** [comment]
Please try:

https://www.eldritchkitty.com/~andrew/gitea-1.14.5-16481-windows-4.0-amd64.zip 

which contains a build of 1.14 with #16481 and it's gpg signature.

**Comment by arcvetkovic** [comment]
Unfortunately, didn't work.

**Comment by zeripath** [comment]
OK let's try:

https://www.eldritchkitty.com/~andrew/gitea-1.14.5-16481-attempt2-windows-4.0-amd64.zip

This just attempts to wait again.

**Comment by zeripath** [comment]
@arcvetkovic

**Comment by arcvetkovic** [comment]
Apologies, stuck at work.

With https://www.eldritchkitty.com/~andrew/gitea-1.14.5-16481-attempt2-windows-4.0-amd64.zip renaming works.

**Comment by zeripath** [comment]
Cool. OK I'll add the necessary bits up.
