### ISSUE TITLE
Failed to create '.ssh': mkdir .ssh: permission denied

### ISSUE THREAD

**Issue by vincentDcmps** [go-gitea/gitea#16476]
- Gitea version (or commit ref): 1.13.7
- Git version: 2.32
- Operating system: Arch linux
 --> install via pacman
 --> launch with systemd
- Database (use `[x]`):
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X] No

## Description
I try to rebuild my gitea instance in case of disaster
but when I try to regenerate authorization_keys with  
`sudo -u gitea gitea admin -c /etc/gitea/app.ini regenerate hooks`
I get error bellow:
``` 2021/07/18 12:45:43 ...s/setting/setting.go:688:NewContext() [F] Failed to create '.ssh': mkdir .ssh: permission denied```
rigth on work dir seem OK
```[root@VMAS-HML ~]# ls -la /var/lib/gitea
total 44
drwxr-xr-x 10 gitea gitea 4096 18 juil. 12:31  .
drwxr-xr-x 26 root  root  4096 18 juil. 12:12  ..
drwxr-xr-x  2 gitea gitea 4096 18 juil. 12:07 'addrs=127.0.0.1:6379 db=0'
drwxr-x---  2 gitea gitea 4096 18 juil. 12:07  attachments
drwxr-xr-x  3 root  root  4096 18 juil. 12:24  custom
drwxr-x---  9 gitea gitea 4096 18 juil. 12:34  data
-rw-r--r--  1 gitea gitea  162 18 juil. 12:07  .gitconfig
drwxr-x---  3 gitea gitea 4096 18 juil. 12:07  indexers
drwxr-x---  2 gitea gitea 4096 18 juil. 12:07  repos
drwx------  2 gitea gitea 4096 18 juil. 12:31  .ssh
drwxr-x---  2 gitea gitea 4096 18 juil. 12:07  tmp
```
and I get same issue when doing other admin command:

```
[root@VMAS-HML ~]# sudo -u gitea gitea admin -c /etc/gitea/app.ini auth list
2021/07/18 12:48:07 ...s/setting/setting.go:688:NewContext() [F] Failed to create '.ssh': mkdir .ssh: permission denied
```

note that when I start an interactive gitea session I launch directly gitea binaries

```
[root@VMAS-HML ~]# sudo -i gitea
2021/07/18 12:49:02 cmd/web.go:108:runWeb() [I] Starting Gitea on PID: 39117
```

I have reproduce this issue on my main gitea server

**Comment by techknowlogick** [comment]
This is happening because h the ere is a conflict between the workdir that systemd uses, and the one you have via cli. I believe the quick and dirty fix for this for your situation would be to either change your workdir to the same one as systemd or utilize the -w argument (undocumented and not really recommend).

That being said, I highly recommend you updated to the latest stable version of Gitea (1.14.5 at the time of writing), as it contains many bug fixes and a few security ones too.

**Comment by vincentDcmps** [comment]
for information command work when I change current dir to gitea workdir
