### ISSUE TITLE
Dark theme (arc-green) needs more contrast

### ISSUE THREAD

**Issue by Barugon** [go-gitea/gitea#16489]
- Gitea version (or commit ref): 1.13.7
- Git version: NA
- Operating system: Manjaro ARM

## Description
The dark theme, arc-green, is too flat. Please consider making the background grays darker to improve readability and lower eye strain. Also, maybe consider making the grays a bit more neutral.

## Screenshots
Here's how it currently looks:
![default](https://user-images.githubusercontent.com/16503728/126215820-77fe7749-35b2-4c8f-9b02-86d71128db33.png)

Here it is with a contrast boost:
![contrast](https://user-images.githubusercontent.com/16503728/126215921-b9fdb873-7fcc-40a5-896e-15dda0235a9d.png)

**Comment by delvh** [comment]
As far as I know, there is the option to (build and) install a custom theme that does that for you, as long as you have administrator rights (or access to the server).

I for example have no problem with the current theme and would like it to stay the way it currently is.

**Comment by pat-s** [comment]
We could add another dark theme with more contrast.

**Comment by pat-s** [comment]
[Here](https://github.com/pat-s/gitea-github-theme) is a GitHub-based dark-theme.

**Comment by Jieiku** [comment]
I made a theme because I actually had trouble reading the text with the current contrast, so additional dark themes would  be good, here is one I made yesterday, I may make small tweaks here and there as I notice other contrast issues.

https://github.com/Jieiku/theme-dark-gitea
