### ISSUE TITLE
log level should be case insensitive

### ISSUE THREAD

**Issue by r10r** [go-gitea/gitea#16485]
gitea version: 1.14.5

Hi there,

I did set the log level to `info`, but gitea still logged at trace level.
After consulting the documenation i realized that the level value is case-sensitive and I had to set the log level to `Info` instead. This was a kinda surprising to me.

What about making the log level string case insensitive instead?

**Comment by zeripath** [comment]
The log level has been case insensitive for the past 2 years.

Whatever was happening was not due to the capitalisation or not of the level.

**Comment by r10r** [comment]
Hmm, maybe an issue with the helm deployment - i'll try to reproduce it
