### ISSUE TITLE
Automatically delete head branches

### ISSUE THREAD

**Issue by pat-s** [go-gitea/gitea#16493]
Similar to the repo setting available in GitHub.

![image](https://user-images.githubusercontent.com/8430564/126279810-d1cab0ab-ee5b-4981-8f5e-c613e34b2dce.png)

I could not find a similar discussion yet browsing the issues - feel free to link/close if its a duplicate :)

**Comment by lafriks** [comment]
Duplicate of #13568 and already implemented will be available in version 1.15.0
