### ISSUE TITLE
Organization custom avatar only gets updated on browser cache reset

### ISSUE THREAD

**Issue by gencer** [go-gitea/gitea#165]
When a new organization avatar get uploaded you get a message says:

`Organization avatar setting has been updated successfully.`

File is uploaded to `data/avatars/{orgId}` but it does not show up on frontend.

Until you Ctrl+ F5 or reset browser cache. It should reflect change immediately.

**Comment by thibaultmeyer** [comment]
Maybe you have cache. Try to call directly `/avatars/{id}` (use force refresh: CTRL-SHIFT-R on Chrome) and refresh organisation page.

**Comment by gencer** [comment]
Indeed I had a cache.

**Comment by tboerger** [comment]
So let's refine the cache headers for the avatars.

**Comment by lunny** [comment]
Really? But which PR fixed this?

**Comment by Bwko** [comment]
@lunny Nvm somehow disable cache was checked >_<

**Comment by lunny** [comment]
Then, just close this one? @gencer could you confirm this is resolved?

**Comment by Bwko** [comment]
@lunny No, my browser did not cache any images so it looked like it was fixed.
I've create a [branch](https://github.com/Bwko/macaron/tree/etag) to add ETag headers to macaron and fixing this issue.
Maybe we should fork macaron to add things like this?

**Comment by lunny** [comment]
fork macaron and send PR to the original? Maybe we will change macaron to other framework some time.

**Comment by Bwko** [comment]
@lunny Done, now I hope that Unknwon merges this PR in the next couple of days.
