### ISSUE TITLE
Make Mermaid JS character limit configurable

### ISSUE THREAD

**Issue by moiflo033** [go-gitea/gitea#16513]
- Gitea version (or commit ref): 1.14.4
- Git version: 2.30.2
- Operating system: docker
  
  
  
- Log gist:

## Description

Currently the character limit is 5000 chars. This isn't enough for more complex diagrams. I understand the concern that mermaid.js might take to long with larger diagramms, hence why i'm suggesting to make it configurable.

**Comment by silverwind** [comment]
Agree, the 5000 limit was ported from GitLab's implementation, we should add a config option for it.
