### ISSUE TITLE
gitea over docker. localhost:300 error

### ISSUE THREAD

**Issue by kryukov54** [go-gitea/gitea#16516]
- Gitea version (or commit ref): Version: 1.15.0+rc1
- Git version: git version 2.25.1
- Operating system: linuxmint 20.2
- download by docker image from github
- docker-compose up -d
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X ] No
- Log gist:

## Description
There are some laces where the references to localhost:3000 exist. For example:
repo->issues->test-issue

The apache config is
1) example.conf
<VirtualHost *:80> 
  ServerName www.example.com
  RedirectMatch 301 /(.*) https:// www.example.com/$1
</VirtualHost>

2)example-ssl.conf
<VirtualHost *:443> 
  ProxyPreserveHost On
  ProxyRequests Off
  ServerName www.example.com
  ProxyPass / http://localhost:8080/
  ProxyPassReverse / http://localhost:8080/
</VirtualHost> 

3) docker-compose.yml
version: "3"

networks:
  gitea:
    external: false

volumes:
  gitea:
    driver: local

services:
  server:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    networks:
      - gitea
    volumes:
      - gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8080:3000"
      - "8022:22"

...

## Screenshots
The 

![Screenshot from 2021-07-22 18-36-09](https://user-images.githubusercontent.com/3815343/126667098-eb22a42e-ed01-4148-99e1-4f33f507365b.png)

test-issue refer to http://localhost:3000/... instead of www.example.com

**Comment by techknowlogick** [comment]
You'll need to set the ROOT_URL in your configuration (app.ini) to the domain/URL you want

**Comment by kryukov54** [comment]
Thank you! It works.

**Comment by kryukov54** [comment]
Unfortunately, this did not help everywhere. The link for cloning the repository by ssh remained the same (see screen shot).
![Screenshot from 2021-07-23 15-45-33](https://user-images.githubusercontent.com/3815343/126783448-e524968c-b880-4dd8-a0aa-554e64890f17.png)

**Comment by zeripath** [comment]
See:

https://docs.gitea.io/en-us/config-cheat-sheet/#server-server

* `SSH_DOMAIN`: **%(DOMAIN)s**: Domain name of this server, used for displayed clone URL.

**Comment by techknowlogick** [comment]
@jeff-hykin please don't post in closed issues. Your report will get lost. As this is not a bug I recommend hopping into our chat where someone can help you set your configuration.

**Comment by zeripath** [comment]
Please do not half comment on old closed issues without providing full information. You should open another issue or likely just go to our discord and ask for help there as it would be quicker.

From the very little you have given us you I would guess that your LOCAL_ROOT_URL is completely incorrect and it should hav been left at http://localhost:3000
