### ISSUE TITLE
Repository Topics are lowercased

### ISSUE THREAD

**Issue by kyland-holmes** [go-gitea/gitea#16525]
- Gitea version (or commit ref): 1.14.2, 1.14.3, 1.14.5
- Git version:  2.30.2
- Operating system: Linux version 5.10.25-linuxkit (root@cef9c358b34d) (gcc (Alpine 9.2.0) 9.2.0, GNU ld (GNU Binutils) 2.33.1) #1 SMP Tue Mar 23 09:27:39 UTC 2021

This is being observed via running gitea in the publicly provided docker images at [docker hub](https://hub.docker.com/r/gitea/gitea)

- Database (use `[x]`):
  - [ X] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ X] Yes : https://try.gitea.io/kylandholmes/test
  - [ ] No
- Log gist:
https://gist.github.com/KyKoPho/345d3a3e3df8a4ebfe43dae93ae4acf9

## Description

I found that when creating a new topic for a repo, gitea will save uppercase letters in the topic as lower cased.  Screen shots below.

## Screenshots

<img width="1300" alt="image" src="https://user-images.githubusercontent.com/7452787/126851927-42bcab65-50cd-467b-b950-68527ae2e3fb.png">
<img width="1348" alt="image" src="https://user-images.githubusercontent.com/7452787/126851933-e794ae95-3d14-4296-b76c-55b7278eba87.png">
<img width="560" alt="image" src="https://user-images.githubusercontent.com/7452787/126851948-405e239d-7fb6-493e-8139-1cc8a910229e.png">

**Comment by delvh** [comment]
To be fair, that could also be intended, because when you only allow lowercase names, then users have it way easier not to accidentally misspell the topic:
Think for example about a repo with the topic `test-Test-tEst`. Should it then not be found when you enter `test-test-test`? I would say that this eases finding repositories with that tag a lot.

**Comment by zeripath** [comment]
This is in keeping with Github where repository topics are always lower-case.

**Comment by KyKoPho** [comment]
@zeripath  sorry, pretty new to this project. Didn't know there was a general desire to follow GitHub style(s).

**Comment by zeripath** [comment]
no worries - I think gitlab also lower-cases the topics too.
