### ISSUE TITLE
Limit git diff details in create pull request page

### ISSUE THREAD

**Issue by wcb33** [go-gitea/gitea#16521]
When create pull request, it will show all the differences. This can take a long time when the number of differences is high.

It is recommended to limit the number of detailed differences to be displayed and to configure a slightly smaller value as a default, and to hide them when they are exceeded.

Or you can split the commits and diff details into tab pages and display the commits by default, which can also greatly improve performance. Refer to gitlab

**Comment by zeripath** [comment]
This is a known issue and there are multiple requests on our issues for this. Please don't open duplicate requests.
