### ISSUE TITLE
Tags list returns 404, releases tab missing entirely

### ISSUE THREAD

**Issue by sbrl** [go-gitea/gitea#16526]
- Gitea version (or commit ref): 1.14.5
- Git version: 2.25.1
- Operating system: Ubuntu Server 20.04, all patches installed
- Installed via a binary downloaded & verified from the GitHub releases page
- Running via a manually created systemd service file on bare metal.
- Running behind a *non caching* Nginx reverse-proxy providing HTTPS termination.
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
- Log gist:

```
Jul 24 02:29:32 starbeamrainbowlabs gitea[407265]: 2021/07/24 02:29:32 Completed GET /user/events 200 OK in 44.538203814s
Jul 24 02:29:32 starbeamrainbowlabs gitea[407265]: 2021/07/24 02:29:32 Started GET /sbrl/MusicBoxConverter/releases for CLIENT_IP:0
Jul 24 02:29:32 starbeamrainbowlabs gitea[407265]: 2021/07/24 02:29:32 Completed GET /sbrl/MusicBoxConverter/releases 404 Not Found in 63.973903ms
Jul 24 02:29:32 starbeamrainbowlabs gitea[407265]: 2021/07/24 02:29:32 Started GET /js/index.js?v=bc281f6cb46e7a516fedc56eecf3c820 for CLIENT_IP:0
Jul 24 02:29:32 starbeamrainbowlabs gitea[407265]: 2021/07/24 02:29:32 Completed GET /js/index.js?v=bc281f6cb46e7a516fedc56eecf3c820 304 Not Modified in 3.660387ms
Jul 24 02:29:32 starbeamrainbowlabs gitea[407265]: 2021/07/24 02:29:32 Started GET /img/logo.svg for CLIENT_IP:0
Jul 24 02:29:32 starbeamrainbowlabs gitea[407265]: 2021/07/24 02:29:32 Started GET /img/404.png for CLIENT_IP:0
Jul 24 02:29:32 starbeamrainbowlabs gitea[407265]: 2021/07/24 02:29:32 Started GET /avatars/7e96ec7a3ce16012aebb6129ba0d25ee?size=48 for CLIENT_IP:0
Jul 24 02:29:32 starbeamrainbowlabs gitea[407265]: 2021/07/24 02:29:32 Completed GET /img/logo.svg 304 Not Modified in 5.748606ms
Jul 24 02:29:32 starbeamrainbowlabs gitea[407265]: 2021/07/24 02:29:32 Completed GET /img/404.png 304 Not Modified in 7.223472ms
Jul 24 02:29:32 starbeamrainbowlabs gitea[407265]: 2021/07/24 02:29:32 Completed GET /avatars/7e96ec7a3ce16012aebb6129ba0d25ee?size=48 304 Not Modified in 10.280223ms
Jul 24 02:29:32 starbeamrainbowlabs gitea[407265]: 2021/07/24 02:29:32 Started GET /user/events for CLIENT_IP:0
```

## Description
Both the releases page (`https://git.example.com/user/repo/releases`) and the tags page (`https://git.example.com/user/repo/tags`) result in a 404 page not found. This is regardless of whether tags already exist in the repository or not.

1. Navigate to a repository's home page
2. Observe that the Releases tab is missing
3. Try clicking `X tags` in the bar just above the prrogramming language bar
4. See 404

Adding `DEFAULT_REPO_UNITS = repo.code,repo.releases,repo.issues,repo.pulls` to the `repository` section of my `app.ini` (in `custom/conf/`) has no effect.

## Screenshots
The top of the main page of a repository. Note that the releases tab is missing:

![image](https://user-images.githubusercontent.com/9929737/126853859-e3771dff-27af-46aa-9b28-18481068c1fa.png)

When one clicks on the text `1 Tag`, one gets this:

![Selection_2021-07-24_02:35:27_001_e45c0b5](https://user-images.githubusercontent.com/9929737/126853848-7a2e9c12-03cf-430b-b4ea-880df991ad77.png)

**Comment by zeripath** [comment]
Is it true that you cannot reproduce this on try.gitea.io? 

If so would it be possible to upgrade to 1.15-RC2 to try to see if this is still present in 1.15 - if not then we can consider it fixed.

**Comment by lunny** [comment]
It seems you have no permission to visit release or your database lost release unit because of some reason.

**Comment by sbrl** [comment]
I'll test it on 1.15 when it comes out. If it is still a problem, I'll comment here again.

> or your database lost release unit because of some reason.

Is there any way I can check that my "release unit" has been lost? If it has been lost, how can I get it back?

**Comment by bovender** [comment]
I have the same problem and upgrading my docker image from 1.14.6 to 1.15.0-rc3 did not solve it.

**Comment by zeripath** [comment]
@bovender please can you try to reproduce on try.gitea.io or give us some logs at DEBUG level.

**Comment by bovender** [comment]
@zeripath thanks for looking into this. I have created a gist that contains the log output: https://gist.github.com/bovender/2e71dd522ce34d56d9f125aa9ea39179

The log was produced by changing the log level to "Debug" and the log folder to `log2` in `app.ini`, then hitting <kbd>ENTER</kbd> in the browser's address bar with `https://MY.DOMAIN/MY_ORG/MY_REPO/tags`.

I should add that this behavior (the 404 error on the tags page) occurs with at least several repositories (did not try all of them), and other users of my Gitea instance (we're a small NGO) reported the same. The setup is a dockerized Gitea with a Postgres database. Has been running fine for a few of years now.

By the way I am unable to log into try.gitea.io using Github authentication because a 500 error occurs (repeatedly):

![image](https://user-images.githubusercontent.com/1484759/129143752-bcd50854-3a65-439b-8240-97d879fe434f.png)
