### ISSUE TITLE
why timeout connect to ssh?

### ISSUE THREAD

**Issue by guojie** [go-gitea/gitea#16531]
PS D:\workspace\front\wiki> git push origin master
Enumerating objects: 383, done.
Counting objects: 100% (383/383), done.
Delta compression using up to 8 threads
Compressing objects: 100% (178/178), done.
Writing objects: 100% (242/242), 842.44 KiB | 1.81 MiB/s, done.
Total 242 (delta 107), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (107/107), completed with 57 local objects.
remote: Gitea: Internal Server Error
remote: Unable to contact gitea: Post "http://localhost:3000/api/internal/hook/pre-receive/front/wiki": read tcp [::1]:58256->[::1]:3000: i/o timeout
To ssh://git.guoj.top:2222/front/wiki.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'ssh://*****:2222/front/wiki.git'

Ubuntu 20.04.2 LTS (GNU/Linux 5.4.0-70-generic x86_64)
reboot is ok.  After a few days, it looks like this.

**Comment by zeripath** [comment]
There is an issue proforma for a reason.

Without that information we cannot help you. 

Please reopen with the issue proforma completed.
