### ISSUE TITLE
OpenID broken in 1.15.0-rc2

### ISSUE THREAD

**Issue by BastienVigneron** [go-gitea/gitea#16548]
- Gitea version (or commit ref):
- Git version: 1.15.0-rc2
- Operating system: Linux / Docker
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
- Log gist:

```
2021/07/25 18:25:13 Started GET /user/login?redirect_to=%2f for 10.16.0.10:56370
2021/07/25 18:25:13 Completed GET /user/login?redirect_to=%2f 200 OK in 16.048122ms
2021/07/25 18:25:14 Started GET /user/oauth2/solutions2 for 10.16.0.10:56370
2021/07/25 18:25:14 Completed GET /user/oauth2/solutions2 307 Temporary Redirect in 16.845337ms
```

## Description
After upgrade from 1.14.5 to 1.15.0-rc2 the OpenID login seems broken.
The initial redirection to OpenID login page is ok, but after authentication, the user is endless redirected to the same login page.

**Comment by techknowlogick** [comment]
OpenID != Oauth2. From your logs it looks like you are using Oauth2, which oauth2 provider are you using?

**Comment by 6543** [comment]
@bastien-solutions wee need more detail about your configuration

**Comment by bastien-solutions** [comment]
> OpenID != Oauth2. From your logs it looks like you are using Oauth2, which oauth2 provider are you using?

Keycloak, I've found no way to declare a real OpenID provider in gitea, then I've declared an OAuth2 with OpenID connect provider : 

![Capture d’écran 2021-07-27 à 09 47 33](https://user-images.githubusercontent.com/66112470/127116688-de7ada91-ac9d-4bb6-948c-efbc01651dae.png)

This have been worked like a charm up to 1.15.0

**Comment by zeripath** [comment]
I am betting that you have been hit by the breaking change within https://github.com/go-gitea/gitea/pull/16010

**Comment by zeripath** [comment]
Please see https://gitea.com/gitea/blog/wiki/v1.15.0 for a WIP blog post regarding the breaking changes for 1.15

**Comment by bastien-solutions** [comment]
Even with RS256 signature activation (see below), the OAuth / OpenID seems still unusable  : 

<img width="778" alt="Capture d’écran 2021-07-27 à 14 46 36" src="https://user-images.githubusercontent.com/66112470/127156007-61173c57-f55a-4e31-82b6-a5b754e8dfc1.png">

**Comment by zeripath** [comment]
Have you updated the client secret?

**Comment by bastien-solutions** [comment]
No, the documentation is not really clear, do we must generate a public key from the private one stored in `jwt` directory ?

**Comment by techknowlogick** [comment]
@zeripath it looks like @bastien-solutions is going in the other direction, of logging into Gitea using keycloak so our OIDC changes wrt RS256 wouldn't have an effect on that.

**Comment by zeripath** [comment]
@techknowlogick I was wondering if keycloak had the client secret tied to the JWT key in some way.

---

OK @bastien-solutions we need some browser logs I think.

Looking your provided logs it doesn't appear that Gitea is ever receiving the `/user/oauth2/solutions2/callback` but yet Gitea is sending the redirect to the keycloak server: (`Temporary Redirect`). So the question is why? 

Is keycloak redirecting back to the right place and Gitea is then doing some weird loop? Or is keycloak redirecting back to the wrong place?

--- 

Another option is are able to rebuild gitea with some patches to try to get some more information as to what is happening?

**Comment by bastien-solutions** [comment]
After reseting all options in keycloak to default values, I finally success to get the following log in gitea : 
```
2021/07/27 15:28:11 Completed GET /user/oauth2/solutionsId/callback?state=6e2aafb2-f5fc-44ee-a52d-16fccb842c4b&session_state=ade03674-5e18-4d34-8aaa-3c55b2133fe0&code=a519fd10-5494-40e8-8fc4-8056ed9a73ce.ade03674-5e18-4d34-8aaa-3c55b2133fe0.4f9764fa-8cac-4e91-ae0b-02c04789ffea 500 Internal Server Error in 54.804993m
```

Same error in browser console logs.

**Comment by bastien-solutions** [comment]
....and finally after reverting client authenticator to cliend id and secret rather than signed JWT as indicated in the documentation, everything seems now ok.
I really don't understand whats happened.

**Comment by bastien-solutions** [comment]
anyway thank you guys for helping.
