### ISSUE TITLE
Cannot delete user with LDAP auth (500 - Internal Server Error)

### ISSUE THREAD

**Issue by viktike** [go-gitea/gitea#1655]
- Gitea version (or commit ref):
66c803f
- Git version:
git version 2.7.4
- Operating system:
Ubuntu 16.04.2 server LTS x86_64 (ni LXC)
- Database (use `[x]`):
  - [x] PostgreSQL 9.4
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
PostgreSQL complains:
```
2017-05-01 11:36:05.080 CEST [9585] xxx@gitea STATEMENT:  DELETE FROM "external_login_user" WHERE "user_id"=$1
2017-05-01 11:40:28.643 CEST [9585] xxx@gitea ERROR:  Cannot run UPDATE or DELETE on table external_login_user because it does not have a PRIMARY KEY.
```
And very well there is no index on that table:
```
gitea=# select * from pg_indexes where tablename = 'external_login_user';
 schemaname | tablename | indexname | tablespace | indexdef
------------+-----------+-----------+------------+----------
(0 rows)
```

**Comment by lafriks** [comment]
LDAP source should not have record in this table for users, except only if user has added oauth linked account.
As for table there seems to be bug, table needs composite primary key.

**Comment by viktike** [comment]
There is no record in this table (at all actually), but Gitea executes that DELETE statement.
So should I go on, and add a PKEY for all columns or just wait for a further version which does this as a migration?

**Comment by lafriks** [comment]
Are you using PostgreSQL replication? I can not reproduce this issue on standard PostgreSQL configuration.

**Comment by viktike** [comment]
Yes, I have write ahead log (wal) level set to the _logical_ value for the multi-master setup (2ndQuadrant BiDirectional Replication).
