### ISSUE TITLE
CSV module includes encoding/csv twice

### ISSUE THREAD

**Issue by richmahn** [go-gitea/gitea#16557]
- Gitea version (or commit ref): 4b6370c46d8d75a163e271b3636e48791d4cc641 (main)

## Description

No need to import `encoding/csv` twice:

https://github.com/go-gitea/gitea/blob/4b6370c46d8d75a163e271b3636e48791d4cc641/modules/csv/csv.go#L9

Use stdcsv here and below:

https://github.com/go-gitea/gitea/blob/4b6370c46d8d75a163e271b3636e48791d4cc641/modules/csv/csv.go#L100

**Comment by lunny** [comment]
Good catch
