### ISSUE TITLE
Feature: Block commits that reveal email

### ISSUE THREAD

**Issue by ImDaBigBoss** [go-gitea/gitea#16578]
### Description
I would like to see a feature a bit like on GitHub, where you can block commits that reveal an email. On GitHub it's called "Block command line pushes that expose my email" under email settings.
Maybe there could be a toggle button to chose if the selected email should be always used as a commit email.

### Example
A user has no gitconfig or it specifies a private email, therefore, when that commit is pushed, it should be blocked to keep the user's name/domain name/private email safe.

**Comment by jolheiser** [comment]
https://github.com/go-gitea/gitea/pull/14686

**Comment by ImDaBigBoss** [comment]
Oh ok. Thank you jolheiser.
