### ISSUE TITLE
Feature request: Trigger push mirroring on change to source branch

### ISSUE THREAD

**Issue by jotoho** [go-gitea/gitea#16579]
- Gitea version (or commit ref): 1.15.0+rc2 (docker image gitea/gitea:69d52290d01b)
- Git version: 2.30.2
- Operating system: Official docker image on 64-bit Raspberry Pi OS
- Database: SQLite

## Description

I would like to have the option for push mirroring to trigger on changes to the source branch instead of only happening on a fixed timer.

If a user, for example, prefers Gitea as a platform but mirrors their repository to another platform, like GitLab or GitHub, for running CI, then it wouldn't do them any good to have to wait potentially hours before getting their CI results from the secondary repository. 

Changing the mirroring frequency to something like 10 minutes still wouldn't be ideal though and would place unnecessary load on Gitea and the mirror remote. (No need to synchronize changes every 10 minutes when the only user last touched the repo half a week ago)

I think that this use-case would best be addressed by adding the option for mirroring to trigger whenever the source branch on Gitea is changed instead of a timed trigger, maybe with a rate-limiting setting (i.e. pushing at most 5x an hour - if source branch is changed a sixth time in that hour, schedule a push for the start of the next hour) to slow down mirroring during particularly active periods.

**Comment by N-R-K** [comment]
+1
Also I think it's sensible to wait 30~40sec to check if there's more changes before triggering a push.

**Comment by tgruenert** [comment]
We are in exactly same situation as @jotoho described before. 
+1

**Comment by jotoho** [comment]
Closing as it seems work has begun on issue #18220, which is a duplicate of this one.
