### ISSUE TITLE
Repository size reduced, UI still shows original value

### ISSUE THREAD

**Issue by GAS85** [go-gitea/gitea#16573]
- Gitea version (or commit ref): 1.14.5
- Git version: 2.25.1
- Operating system: Ubuntu 20.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL/MariaDB
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
- Log gist: Nothing related

## Description

One of Repositories being used for automation and it's size grows (up to 1.3 Gb) with 100+ commits, in order to reduce size and commits aomount `git rebase` was used, but Repository size in UI was not changed.
Repository size in FS being reduced:

```
du -sh
78M
```

## Screenshots

![grafik](https://user-images.githubusercontent.com/6813635/127485274-def780d2-6db9-417b-9a2c-e38d74837151.png)

**Comment by lunny** [comment]
After confirm that no ref to old commits, then run GC will resolve the problem. The default GC cron task is every 3 days?

**Comment by GAS85** [comment]
I pushed Garbage Collector job to execute, it is correct shown 11 commits, but size is not. On Server FS it is smaller:

```bash
$ sudo du -sh /var/git/gitea-repositories/USER/REPO.git/
78M	/var/git/gitea-repositories/USER/REPO.git/
```
and even all Repos together are smaller:
```bash
$ sudo du -sh /var/git/gitea-repositories/
332M	/var/git/gitea-repositories/
```
Grapg is quite straightforward
![изображение](https://user-images.githubusercontent.com/6813635/127542986-a6e8d022-0867-42bb-a6b1-c02f12d04cbf.png)

But after new push size was dropped to real one:
```
$ sudo du -sh /var/git/gitea-repositories/USER/REPO.git/
103M	/var/git/gitea-repositories/USER/REPO.git/
```
Screenshot:
![изображение](https://user-images.githubusercontent.com/6813635/127543629-61b26b95-230e-4cba-aa19-3d90a65170c2.png)
