### ISSUE TITLE
Add Wiki Page Error - exit status 128

### ISSUE THREAD

**Issue by zzudongxiang** [go-gitea/gitea#16584]
- Gitea version (or commit ref):1.15.0+rc2 built with GNU Make 4.3, go1.16.6 : bindata, timetzdata, sqlite, sqlite_unlock_notify 
- Git version:2.30.2
- Operating system:Synolgy 7.0-4189 + Docker
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (https://try.gitea.io/zzudongxiang/test/wiki/_new)
  - [ ] No
- Log gist:

## Description
An error occurred while creating a new wiki

## Screenshots
![image](https://user-images.githubusercontent.com/33760061/127731100-e4c99737-22c5-421e-8100-7a3dd23c51d6.png)
![image](https://user-images.githubusercontent.com/33760061/127731107-daafb9ec-9351-48c9-82fa-c790f8703584.png)

**Comment by zeripath** [comment]
We need more logs at DEBUG level.

Please read https://docs.gitea.io/en-us/logging-configuration/#debugging-problems

Your problem also relates to git commands so please also set `RUN_MODE=dev` at the top of app.ini.

**Comment by zzudongxiang** [comment]
[gitea.log](https://github.com/go-gitea/gitea/files/6911157/gitea.log)
Line: 124 && Line: 181

**Comment by zeripath** [comment]
PR up. 

Sorry about this.
