### ISSUE TITLE
Rename empty organization error!

### ISSUE THREAD

**Issue by jearton** [go-gitea/gitea#16589]
- Gitea version (or commit ref): gitea/gitea:1.14.5 docker image
- Git version: 2.30.2 (in docker container)
- Operating system:
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
- Log gist:

## Description

First, rename empty organization:

![image](https://user-images.githubusercontent.com/10370433/127758336-bdd395ce-bc6f-45f5-ba78-38fce4e5b2ee.png)

Then, error page appears:

![image](https://user-images.githubusercontent.com/10370433/127758360-981a4c65-bcfe-4de2-b0a2-5c46f3087b08.png)

## Screenshots

![image](https://user-images.githubusercontent.com/10370433/127758518-d729c2bb-67e2-4fab-96cd-b9af08bbd714.png)

![image](https://user-images.githubusercontent.com/10370433/127758277-87d0de26-a039-4d73-9fa2-4778f8185ca9.png)

**Comment by zeripath** [comment]
Apologies for this bug it's already fixed by #16463 which will be in v1.14.6.

**Comment by jearton** [comment]
> Apologies for this bug it's already fixed by #16463 which will be in v1.14.6.
@zeripath When will v1.14.6 be released?
