### ISSUE TITLE
OAUTH2 login via Keycloak (OpenID connect) does not work after 1.14.2?

### ISSUE THREAD

**Issue by asifbacchus** [go-gitea/gitea#16593]
- Gitea version (or commit ref): 1.14.2
- Operating system:
  - Running docker container 1.14.2 on Debian Buster host
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Haven't tried
- Log gist:
  - don't know what logs to provide, need guidance

I've been using Keycloak via OAUTH2 as an option to log into Gitea for a long time and never had problems. No changes to made to *anything* except that I updated to the latest release version container (1.14.5). Keycloak configuration is *unchanged* (I have a client set-up and using a custom scope, but it provides everything Gitea needs).

If I try logging in via OAUTH2 (using OpenID Connect as provider), Keycloak issues the token with no problems. However, Gitea bounces me back to the homepage as though nothing happened. So, I tried logging in using my username and password (which always works) and then un-linked my account. Then tried logging in via OAUTH2 again expecting to get the link-account confirmation.  Instead I got an error 500 and mentions in the log of:
 `routers/user/auth.go:765:LinkAccount() [E] UserSignIn: not in LinkAccount session`.
`...ters/user/profile.go:29:GetUserByName() [E] GetUserByName: user redirect does not exist [name: robots.txt]`

I tried shutting down and restarting the Gitea container, clearing the session directory, tried version 1.14.3, 1.14.4 also. As soon as I rolled back to 1.14.2 everything worked perfectly again.

For reference, here are the relevant parts of my config:

```ini
[service]
DISABLE_REGISTRATION = true
REQUIRE_SIGNIN_VIEW = false
REGISTER_EMAIL_CONFIRM = true
ENABLE_NOTIFY_MAIL = true
EMAIL_DOMAIN_WHITELIST = asifbacchus.dev asifbacchus.app bacchus.cloud bacchus.me
ALLOW_ONLY_EXTERNAL_REGISTRATION = false
ENABLE_CAPTCHA = false
DEFAULT_KEEP_EMAIL_PRIVATE = false
DEFAULT_ALLOW_CREATE_ORGANIZATION = true
DEFAULT_ENABLE_TIMETRACKING = true
NO_REPLY_ADDRESS = noreply.asifbacchus.dev

[oauth2]
ENABLE = false

[openid]
ENABLE_OPENID_SIGNIN = true
ENABLE_OPENID_SIGNUP = false
WHITELISTED_URIS = ^https://auth.bacchus.cloud/.*

[oauth2_client]
ENABLE_AUTO_REGISTRATION = false
OPENID_CONNECT_SCOPES = gitea openid
USERNAME = userid
ACCOUNT_LINKING = login
UPDATE_AVATAR = false
```

I am running behind an NGINX reverse proxy but that configuration has been the same for years and it's nothing special, just a straight proxy and I've never had problems before. I also tried everything in multiple browsers both in normal and private windows and also on 3 different machines.

I am thinking, since nothing else other than the Gitea version has changed, this is not on my end. Has there been a change in how OAUTH2 is handled since 1.14.2? Token format changed or something like that?

Any help appreciated, thank you very much in advance. If you need *any* further information, please let me know.

**Comment by tacerus** [comment]
I would too recommend to disabling and re-enabling it (possibly also generating a new secret in Keycloak). It works great for me, but took two attempts.

**Comment by asifbacchus** [comment]
I have some time this weekend and will try again. However, yes, I did try disabling and re-enabling OAUTH2 as well as destroying and recreating the client in Keycloak. Maybe the slightly newer incremental version will work better for me.

**Comment by asifbacchus** [comment]
This is still happening with version 1.15.6... no idea what could be wrong. The `not in LinkAccount session` seems to be the recurring issue though. Any ideas what I could try? Staying on 1.14.2 doesn't seem like the best idea, getting a little old now.

**Comment by zeripath** [comment]
@asifbacchus did you do a `gitea dump` from version 1.14.2-1.14.6 or 1.15.0 and restore from that dump?

If so your login_sources are likely broken.

Create a new one - with the same config that you had before and then copy over `cfg` field on to the login_source in the db. 

Although I was able to write a fixer for the repo_units I was not able to write a fixer for the login_source because it's so varied..

If it's not that you'll have to give us some logs.

**Comment by asifbacchus** [comment]
Thanks for the reply. I just tried it on a completely clean fresh installation with an empty sqlite database created by the installer. Same issue, error 500 on the callback.  Could it be some combination of my registration settings, perhaps? I want to keep the same registration settings I've had for the last few years, if possible: admin creates users, no users can sign-up, users can login using their username & password and/or OAUTH2 via Keycloak.  Here's the app.ini I'm using:

```ini
APP_NAME = AB-Git running Gitea
RUN_USER = git
RUN_MODE = prod

[repository]
ROOT            = /var/lib/gitea/git/repositories
DEFAULT_PRIVATE = private
DEFAULT_BRANCH  = main

[repository.local]
LOCAL_COPY_PATH = /tmp/gitea/local-repo

[repository.upload]
TEMP_PATH = /tmp/gitea/uploads

[server]
APP_DATA_PATH           = /var/lib/gitea/gitea
SSH_DOMAIN              = git.asifbacchus.dev
HTTP_PORT               = 3000
ROOT_URL                = https://git.asifbacchus.dev/
DISABLE_SSH             = false
; In rootless gitea container only internal ssh server is supported
START_SSH_SERVER        = true
SSH_PORT                = 2222
SSH_LISTEN_PORT         = 2222
BUILTIN_SSH_SERVER_USER = git
LFS_START_SERVER        = true
LFS_CONTENT_PATH        = /var/lib/gitea/git/lfs
DOMAIN                  = git.asifbacchus.dev
LFS_JWT_SECRET          = <withheld>
OFFLINE_MODE            = false
LFS_MAX_FILE_SIZE       = 524288000

[database]
PATH     = /var/lib/gitea/gitea/gitea.db
DB_TYPE  = sqlite3
HOST     = localhost:3306
NAME     = gitea
USER     = root
PASSWD   = 
SSL_MODE = disable
CHARSET  = utf8
LOG_SQL  = false
SCHEMA   = 

[session]
PROVIDER_CONFIG   = /var/lib/gitea/gitea/sessions
SESSION_LIFE_TIME = 259200
SAME_SITE         = strict
PROVIDER          = file
GC_INTERVAL_TIME  = 259200

[picture]
AVATAR_UPLOAD_PATH            = /var/lib/gitea/gitea/avatars
REPOSITORY_AVATAR_UPLOAD_PATH = /var/lib/gitea/gitea/repo-avatars
ENABLE_FEDERATED_AVATAR       = true
DISABLE_GRAVATAR              = false
GRAVATAR_SOURCE               = gravatar

[attachment]
PATH = /var/lib/gitea/gitea/attachments

[log]
ROOT_PATH         = /var/lib/gitea/gitea/log
ENABLE_ACCESS_LOG = false
MODE              = console
ENABLE_XORM_LOG   = true
LEVEL             = info
ENABLE_SSH_LOG    = false
ROUTER            = console

[security]
SECRET_KEY                    = <withheld>
REVERSE_PROXY_LIMIT           = 1
REVERSE_PROXY_TRUSTED_PROXIES = 172.31.1.1
COOKIE_USERNAME               = ab_git_user
COOKIE_REMEMBER_NAME          = ab_git_remember
LOGIN_REMEMEBER_DAYS          = 5
DISABLE_WEB_HOOKS             = false
DISABLE_GIT_HOOKS             = true
INTERNAL_TOKEN                = <withheld>
PASSWORD_HASH_ALGO            = pbkdf2
INSTALL_LOCK                  = true

[service]
DISABLE_REGISTRATION                = true
REQUIRE_SIGNIN_VIEW                 = false
ENABLE_CAPTCHA                      = false
ENABLE_REVERSE_PROXY_AUTHENTICATION = false
REGISTER_EMAIL_CONFIRM              = true
NO_REPLY_ADDRESS                    = noreply.asifbacchus.dev
DEFAULT_KEEP_EMAIL_PRIVATE          = true
ALLOW_ONLY_EXTERNAL_REGISTRATION    = false
ENABLE_NOTIFY_MAIL                  = true
EMAIL_DOMAIN_WHITELIST              = asifbacchus.dev asifbacchus.app bacchus.cloud bacchus.me
DEFAULT_ALLOW_CREATE_ORGANIZATION   = true
DEFAULT_ENABLE_TIMETRACKING         = true
DEFAULT_ORG_VISIBILITY              = private
DEFAULT_USER_VISIBILITY             = private

[oauth2_client]
ENABLE_AUTO_REGISTRATION = true
ACCOUNT_LINKING          = login
USERNAME                 = userid
UPDATE_AVATAR            = true
REGISTER_EMAIL_CONFIRM   = false
OPENID_CONNECT_SCOPES    = gitea openid

[default]
RUN_MODE = prod
APP_NAME = AB-Git running Gitea
RUN_USER = git

[mailer]
PASSWD          = <withheld>
ENABLED         = true
FROM            = git.admin@asifbacchus.dev
USER            = <withheld>
HOST            = <withheld>
IS_TLS_DISABLED = false

[openid]
ENABLE_OPENID_SIGNIN = true
ENABLE_OPENID_SIGNUP = true
WHITELISTED_URIS     = ^https://auth.bacchus.cloud/.*

[indexer]
ISSUE_INDEXER_PATH = /var/lib/gitea/gitea/indexers/issues.bleve

[lfs]
PATH = /var/lib/gitea/git/lfs

[cron.git_gc_repos]
SCHEDULE = @every 168h
ENABLED  = true

[ui]
DEFAULT_THEME   = arc-green
SHOW_USER_EMAIL = false

[ui.meta]
KEYWORDS    = git,gitea,ab-group,AB-GROUP,AB-Group,'Asif Bacchus'
DESCRIPTION = Private git server for AB-Group projects
AUTHOR      = Asif Bacchus

[other]
SHOW_FOOTER_BRANDING           = false
SHOW_FOOTER_TEMPLATE_LOAD_TIME = false
SHOW_FOOTER_VERSION            = false

[admin]
DISABLE_REGULAR_ORG_CREATION = false
DEFAULT_ADMIN_NOTIFICATIONS  = enabled

[oauth2]
ENABLED = false

[time]
DEFAULT_UI_LOCATION = America/Edmonton
```

Again, very grateful of any insights. Otherwise I'm gonna have to rollback to 1.14.2 and feel super primitive 😝

**Comment by asifbacchus** [comment]
I figure I should probably post my docker-compose and nginx configurations too, just in case things have changed and I'm doing it wrong now

```yml
#
# gitea containerized
#

version: "3.5"

services:
    gitea:
        image: gitea/gitea:1.15-rootless
        container_name: gitea
        restart: unless-stopped
        volumes:
          - type: bind
            source: /etc/localtime
            target: /etc/localtime
            read_only: true
          - type: bind
            source: /etc/timezone
            target: /etc/timezone
            read_only: true
          - type: bind
            source: /var/gitea/data
            target: /var/lib/gitea
          - type: bind
            source: /var/gitea/config
            target: /etc/gitea
        networks:
          - svc_network
        ports:
          - "127.0.0.1:3333:3000"
          - "0.0.0.0:2222:2222"
        environment:
          - USER_UID=2001
          - USER_GID=2001
        user: "2001:2001"

networks:
  svc_network:
    external: true

#EOF
```

```ini
#
# reverse proxy for gitea
#

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    # specify server name
    server_name git.asifbacchus.dev;

    # SSL certificates for this server
    include /etc/nginx/snippets/ssl/ssl_certs_devops.conf;

    # server specific overrides
    client_max_body_size 1024m;
    chunked_transfer_encoding off;

    # add headers
    include /etc/nginx/snippets/securityHeaders.conf;
    
    # proxy options
    proxy_http_version 1.1;

    # proxy headers
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $remote_addr;

    # set upstream locations
    set $upstream_gitea http://127.0.0.1:3333;


    # location blocks
    location / {
        # check if webroot/503_backup.gitea exists, generate 503
        if (-f /usr/share/nginx/html/503_backup.gitea) {
            return 503;
        }
        proxy_pass $upstream_gitea;
    }


    # error pages
    include /etc/nginx/snippets/errorpages.conf;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    # specify server name
    server_name git.asifbacchus.app;

    # SSL certificates for this server
    include /etc/nginx/snippets/ssl/ssl_certs_devops.conf;

    # redirect to asifbacchus.dev
    return 302 https://git.asifbacchus.dev$request_uri;
}
```

**Comment by zeripath** [comment]
> Same issue, error 500 on the callback. 

We need the logs

Read https://docs.gitea.io/en-us/logging-configuration/#debugging-problems

**Comment by asifbacchus** [comment]
Alright, I set up my logging according to the linked document. Notably, the router log is suggested to be console, so the log file does not reflect the callback which is what appears to be throwing the 500. I set the router log to debug and attached that too. They are from 2 separate attempts but it's the same information being logged.

Background:
1) Clean install, same set-up as above configuration files
2) Administrator creates oauth2 authentication backend
3) Administrator creates user 'asif'
4) 'asif' logs in locally once to ensure the account is working ok
5) Attempt to log-in via oauth2 using keycloak
6) 500 error encountered in gitea

Let me know if you need any other logs or want to to try anything else in particular. Thank you very much!
[router.log](https://github.com/go-gitea/gitea/files/7448277/router.log)
[gitea.log](https://github.com/go-gitea/gitea/files/7448278/gitea.log)

**Comment by zeripath** [comment]
Your gitea.log does not cover the same time as the router.log. This is why https://docs.gitea.io/en-us/logging-configuration/#debugging-problems asks you to use the console logger for everything and redirect from there.

I'm guessing however that:

```
2021/10/31 00:59:05 ...s/context/context.go:751:1() [D] Session ID: c08562e8bfbabe8d
2021/10/31 00:59:05 ...s/context/context.go:752:1() [D] CSRF Token: DXhQsdaiaPj8vKJw3xCQrz1lB1Y6MTYzNTY2MzU0NTk3MzM5OTc0Mw
2021/10/31 00:59:05 ...ers/web/user/auth.go:615:SignInOAuthCallback() [E] UserSignIn: could not find a matching session for this request
2021/10/31 00:59:05 ...s/context/context.go:185:HTML() [D] Template: status/500
```

corresponds with: 

```
2021/10/31 01:05:47 Started GET /user/link_account for 50.66.148.168:0
2021/10/31 01:05:47 Completed GET /user/link_account 500 Internal Server Error in 1.497364ms
```

This isn't particularly instructive but it does tell us where to look next.

**Comment by zeripath** [comment]
Hmm... I note your use of `SAME_SITE         = strict`

Are you sure that this is correct and that it shouldn't be `lax`?

**Comment by zeripath** [comment]
OK, this is coming from deep within goth and the associated xormstore.

There's some old stuff in there that I am concerned doesn't really work in modern go, but I don't understand why this should suddenly be causing issues on 1.15 vs 1.14. The only thing I can think of is to do with the cookie above - as we now properly pay attention to the SAME_SITE in 1.15+ - hence my suggestion that trying this as lax may solve things.

I'm gonna take another look at the xormstore stuff - we should probably just use gitea's own session store.

**Comment by asifbacchus** [comment]
You are correct that the two logs are not at the same time, as I mentioned in my comment. However, your interpretation of them is still also correct. How do I redirect docker console logs to file? If you need sync'd logs, I can always run another test and just dump everything to a file since I know how to do that now.

Regarding your other question: It has always worked for me with `SAME_SITE = strict`. Has that changed in the 1.15.x branch? Is that what you'd suggest changing as a next step?

**Comment by asifbacchus** [comment]
@zeripath I really appreciate all your help with this. I'll try to spin up a set of test containers over the next few hours and try changing that _same_site_ setting. I'll let you know how it works out.

**Comment by zeripath** [comment]
Please try switching the SAME_SITE to lax in case that is the problem.

**Comment by asifbacchus** [comment]
@zeripath You are a wonderful person! That was the issue -- thank you very very very much!!!
