### ISSUE TITLE
Install with PostgreSQL not working

### ISSUE THREAD

**Issue by manfer** [go-gitea/gitea#166]
I'm trying to install from source in a PostgreSQL database but when I submit the install form I get an error:
```
Database setting is not correct.pq:syntax error near "NOT"
```
I'm not sure if the issue is on gitea not calling xorm correctly or on xorm itself. But for sure the error comes from some code in xorm.

Don't know if it has something to do with it but just in case I see in dialect.go when creating a table it uses the following SQL:
```
CREATE TABLE IF NOT EXISTS 
```
Don't know if that will be used on any database but just in case it is, I would like to point out that `IF NOT EXISTS` was [introduced on PostgresSQL in version 9.1](http://www.postgresql.org/docs/9.1/interactive/sql-createtable.html) so that will not work on previous versions.

I'm testing in a PostgreSQL 8.20 so that SQL query will not work.

**Comment by manfer** [comment]
Yes, indeed that's the problem. I removed `IF NOT EXISTS` rebuilded xorm and rebuilded gitea and the install process worked.

I don't know what is the solution. More than sure removing that code is not. Just worked as a temporary solution to test.

**Comment by manfer** [comment]
By the way, the dialect.go file I refer to is from `go-xorm/core` and curiously inspecting that file it already has a `CreateTableIfNotExists` function but commented out. I suppose because it is deprecated as it is now the default behaviour on `CreateTableSql` function.

**Comment by lunny** [comment]
I think we have resolved this issue. Now I will close it and please reopen it if you have more problem.

**Comment by manfer** [comment]
Tested and works
