### ISSUE TITLE
Username not logged for logged in users in access log

### ISSUE THREAD

**Issue by svh1985** [go-gitea/gitea#16600]
- Gitea version (or commit ref): 1.15.0+rc2
- Operating system: Host: Ubuntu 20.04.02 running Gitea docker container
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X] No
- Access log entry of logged in user:
192.168.1.154:0 - - [02/Aug/2021:13:15:29 &#43;0000] "GET /api/v1/user/stopwatches HTTP/1.1" 200 3 "\" \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.2 Safari/605.1.15"

Config:
```
[log]
MODE      = file
LEVEL     = info
ROUTER    = console
ROOT_PATH = /data/gitea/log
ENABLE_ACCESS_LOG = true
ENABLE_SSH_LOG = true
LOG_ROTATE = true
DAILY_ROTATE = true
MAX_DAYS = 90
```

**Comment by zeripath** [comment]
oh yes I see... that's both interesting, annoying and I don't quite know what's happened there..

**Comment by zeripath** [comment]
Hmm... fixing this is a bit more involved that I would have hoped.
