### ISSUE TITLE
How to update version to 1.14 from 1.11.0+dev

### ISSUE THREAD

**Issue by colben** [go-gitea/gitea#16609]
# Environment
- CentOS 8
- 1.11.0+dev-252-g21ae9838e built with GNU Make 4.1, go1.13.4
- mariadb 10.4.12

# ISSUE
- Is there any way to update gitea to a newer version(like 1.14)?

**Comment by zeripath** [comment]
Don't update to 1.14.0 - update to 1.14.5 (or whatever is the latest released sub-version at the time.) Always go to the latest minor version.

Read the breaking changes for 1.12, 1.13 and 1.14 - the most likely breaking change to affect you would be that you will need to ensure that `[repository]` `ROOT` is set in your app.ini.

Backup your db.

Replace the binary and restart Gitea.

**Comment by colben** [comment]
> Don't update to 1.14.0 - update to 1.14.5 (or whatever is the latest released sub-version at the time.) Always go to the latest minor version.
> 
> Read the breaking changes for 1.12, 1.13 and 1.14 - the most likely breaking change to affect you would be that you will need to ensure that `[repository]` `ROOT` is set in your app.ini.
> 
> Backup your db.
> 
> Replace the binary and restart Gitea.

Thanks a lot!
