### ISSUE TITLE
Draft markdown isn't redered on release list

### ISSUE THREAD

**Issue by viceice** [go-gitea/gitea#16610]
- Gitea version (or commit ref): 1.14.5
- Git version: official docker image
- Operating system: official docker image (linux)
  
  
  
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io: https://try.gitea.io/viceice/test/releases
  - [ ] Yes (provide example URL)
  - [x] No
- Log gist:

## Description

The markdown code in a draft release isn't properly rendered at the releaes list.

On https://try.gitea.io/viceice/test/releases i get a 500 when try to view the draft release page

## Screenshots

![image](https://user-images.githubusercontent.com/1798109/128008879-5386ba11-173d-4d57-a852-80ff15536ef2.png)
![image](https://user-images.githubusercontent.com/1798109/128008937-e7626122-3735-4ae0-8f76-df06306e6dd4.png)

**Comment by zeripath** [comment]
I have a feeling that this has already been fixed by #15175 in 1.15+. Please try on 1.15.0-rc2 (or 1.15.0-rc3 as soon as that's out.)

The 500 is of more interest to me - Could you explain exactly how you get this? Please could you duplicate on 1.15 and give us some logs?

**Comment by viceice** [comment]
The 500 is happening on your try gitea page linked above.

Yes i think this is already fixed in v1.15 because I can't reproduce on try gitea.

**Comment by zeripath** [comment]
Ah found it.

**Comment by zeripath** [comment]
I think there's another bug with the compare but I need to do more testing to check it.
