### ISSUE TITLE
Remove commit hash from repository table

### ISSUE THREAD

**Issue by lafriks** [go-gitea/gitea#1661]
I would like to propose to remove commit hash from repository table list and make commit message as link to commit like it is in GitHub and GitLab. It makes UI a lot cleaner.

### Before
![repo-table-before](https://cloud.githubusercontent.com/assets/165205/25669507/65c7f7ee-3032-11e7-9c59-4dbff4f47683.png)

### After
![repo-table-after](https://cloud.githubusercontent.com/assets/165205/25669531/72ba2b70-3032-11e7-8bb3-b7701161f0df.png)

**Comment by sapk** [comment]
If someone do that, He could you add the GPG check of the last commit like https://github.com/go-gitea/gitea/blob/master/templates/repo/commits_table.tmpl#L49. I was fearing that it will add some overload here, when doing PR, but with one commit to check this could be safe..
