### ISSUE TITLE
Text keep reappearing

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#16620]
- Gitea version (or commit ref):
- Git version:
- Operating system: Android  8, Firefox, SwiftKey 
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
- Log gist:

## Description

When editing a post and going to start, new lines, start again, type some sentance, new lines, delete lines, start typing again. 
The deleted text keep reaparing and the curskr jumps to end. 

## Screenshots

https://user-images.githubusercontent.com/48178307/128238091-2a359d43-3500-4bec-a2a7-8a21bcf64e08.mp4

**Comment by jolheiser** [comment]
This is the same vein of issue as #12146 and should (hopefully) be fixed once #10729 is resolved. (There are other issues linked to #10729 as well)

The current solution is to click that very last icon on the toolbar to revert to a normal textarea.
