### ISSUE TITLE
[Feature Request] Commit highlighting in code review

### ISSUE THREAD

**Issue by toxyl** [go-gitea/gitea#16630]
Regularly I come upon this situation: an author requests a PR, I do the code review and afterwards the author makes multiple commits. Next time I review the PR I have to check each new commit if I don't want to read the whole code again. However, sometimes stuff is added in one commit and removed in a later commit (e.g. debug logging). If possible it would be really nice if I could do the normal code review flow (via the "files" tab) and highlight changes that belong to one or more specific commits, so I can quickly see what was added/removed/changed in regards to the last time I reviewed the code.

**Comment by shollander** [comment]
I would also add that the "Changed since your last review" label should have a way to show the user *only* the part that changed since last review. This would save reviewers a lot of time.

**Comment by delvh** [comment]
@shollander please upgrade to 1.21.0.
This has been implemented.
