### ISSUE TITLE
PAM Authentication not configurable

### ISSUE THREAD

**Issue by truzzon** [go-gitea/gitea#16639]
- Gitea version (or commit ref): 1.14.6 (Noticed it on earlier versions as well!)
- Git version: 2.20.1
- Operating system: Debian 10
  
  
  
- Database (use `[x]`): (irrelevant, saw it on different setups)
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes
  - [x] No - Can't login to try.gitea.io via GitHub OAuth, will attach screenshot.
- Log gist:

## Description

The documentation ([link](https://docs.gitea.io/en-us/authentication/#pam-pluggable-authentication-module)) mentions, that is is possible to use PAM as an authentication provider. It is not possible to select PAM as a Provider in the Web GUI.
Furthermore there is no sign in the app.ini that I can configure it there.

If the feature was planned and scrapped halfway through, this part should be removed from the docs. I'd love to use this feature, so if it would be implemented at a later point in time I'd appreciate it.

If this feature is available, the documentation should be updated as well to further describe, how to correctly configure it. 

In the mean time I'll update my instance to the latest release and update the issue accordingly.

## Screenshots

![gitea_auth_providers](https://user-images.githubusercontent.com/14220695/128503352-13548952-4f17-4c46-bcd5-f2e0e8ede326.png)

**Comment by truzzon** [comment]
Updated my instance.
Problem still persists.

**Comment by zeripath** [comment]
AFIAU PAM cannot be built statically therefore we do not provide it within the binaries you can download.

You need to build gitea yourself with the `pam` tag in addition to your normal build tags.

See https://docs.gitea.io/en-us/install-from-source/#build

**Comment by truzzon** [comment]
Hello @zeripath,

thanks for your response.

This should definitely be made more clear in the documentation article ([link](https://docs.gitea.io/en-us/authentication/#pam-pluggable-authentication-module)). If someone is not installing it from source like me, he won't come across this step and wonders, why it is not working. 

 Is it possible to put it on the agenda?

Kind Regards

truzzon

**Comment by zeripath** [comment]
Please feel free to send a PR improve the documentation on this.
