### ISSUE TITLE
v1.15.0-rc3 is not marked as pre-release on GitHub Releases

### ISSUE THREAD

**Issue by Jackenmen** [go-gitea/gitea#16644]
## Description
[v1.15.0-rc3](https://github.com/go-gitea/gitea/releases/tag/v1.15.0-rc3) is not marked as a pre-release.
This is a bit problematic when using GitHub API (`https://api.github.com/repos/go-gitea/gitea/releases/latest`) in automation scripts when updating Gitea. The previous releases (i.e. [v1.15.0-rc2](https://github.com/go-gitea/gitea/releases/tag/v1.15.0-rc2)) had this set correctly so I assume it is unintentional.

**Comment by techknowlogick** [comment]
Updated, our CI doesn't do this automatically and is a manual process.
