### ISSUE TITLE
Date time format

### ISSUE THREAD

**Issue by lifebarier** [go-gitea/gitea#16642]
- Gitea version (or commit ref): 1.14.5

I have set 
[time]
FORMAT = RFC3339
in app.ini
yet I still see wrongly formatted dates : 
"Joined on Aug 04, 2021" on my profile
"Updated 2 days ago" next to repo (why is this useless format so popular? I understand for simple people on twitter or other low attention span places, but default on dev tool?)
"Aug 06, 2021" in System notices
etc

How do I change all of those. Also is there a way to format dates more specifically other than limited RFC3339, RFC1123, etc ?

**Comment by jpraet** [comment]
When you hover the "2 days ago" text, you can see the date and time:

![image](https://user-images.githubusercontent.com/2212615/128937750-09a6bafc-6298-46f2-839b-0e59dcae325d.png)

which is formatted according to the configured FORMAT in app.ini.

**Comment by lifebarier** [comment]
@jpraet , is there a way to make it default so I don't need to hover mouse over things?

also, I take it "FORMAT" will understand yyyy-mm-dd HH:mm format not only "RFC3339, RFC1123,"?
