### ISSUE TITLE
tag contain character ) will http 500 on release page

### ISSUE THREAD

**Issue by ncwgf** [go-gitea/gitea#1664]
- Gitea version (or commit ref): 59f5bba
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes https://try.gitea.io/ncwgf/demo-release-error
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

Create a tag/release contain a character )   e.g. : v1.0 (2)
go to release page, return http error 500
error link https://try.gitea.io/ncwgf/demo-release-error/releases

**Comment by appleboy** [comment]
Already fix in https://github.com/go-gitea/git/issues/49. I will update vendor if https://github.com/go-gitea/git/issues/49 has been merged.
