### ISSUE TITLE
The number of Repository for Organization is incorrectly displayed on dashboard page

### ISSUE THREAD

**Issue by zzudongxiang** [go-gitea/gitea#16648]
- Gitea version (or commit ref):1.15.0+rc2
- Git version:2.30.2
- Operating system:Synology + Docker
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No

## Description
The number of Repository for Organization is incorrectly displayed on dashboard page

## Screenshots
![image](https://user-images.githubusercontent.com/33760061/128603670-18a2d3ce-5951-4035-9230-a59356fe88ec.png)

**Comment by fnetX** [comment]
The English title is "My organizations" and it correctly displays the number of organizations next to it. You have six organizations in your screenshot, so the number next to it matches. Or do I miss something?

It's not supposed to show you the number of repositories in your organizations. If the description is misleading, this might be a translation problem ...

**Comment by zzudongxiang** [comment]
I mean, the number of repositories for my organizations should not be 0

![Snipaste_2021-08-09_20-57-17](https://user-images.githubusercontent.com/33760061/128709746-98402ab9-db83-40dd-8c30-a2bd74aea066.png)

**Comment by zeripath** [comment]
This is what I was worried about when the old org user was removed.

**Comment by zeripath** [comment]
I think this is a regression due to #14032 and #13994 and we should use getOrgsByUserID
