### ISSUE TITLE
Init Repo: HTTPS/SSH-selection does not match button

### ISSUE THREAD

**Issue by TheKruspe** [go-gitea/gitea#16646]
- Gitea version (or commit ref): 1.14.3
- Git version: -
- Operating system: Windows Server 2019, amd64-installer
  
  

- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Registration with E-Mail does not work

## Description
When creating a new repo and go the the init page, you get code blocks with instructions to either create a new repo or push an existing one. The content of these code blocks changes, depending on the active protocol selection : HTTPS/SSH. By default, HTTPS is enabled. This is indicated by the blue HTTPS button. However, inside the code blocks, the connection URL for SSH is shown.

**Comment by delvh** [comment]
I think this is a duplicate of #16295 and has been fixed in #16302 for 1.15.

**Comment by TheKruspe** [comment]
@delvh Yes, indeed, you are right.
