### ISSUE TITLE
When i create PR with many changes i see freeze gitea, because she return full compare

### ISSUE THREAD

**Issue by visteras** [go-gitea/gitea#16652]
- Gitea version (or commit ref): 1.14.5
- Git version: 2.30.2
- Operating system: docker

- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite

Just subj. I can disable full compare for "create PR" ?
P.S.: 453 changed files :123758 add and 7694 remove
P.P.S. Why i can see changes for create PR? I known my changes, changes need for reviewer(after create PR), not for creator...

**Comment by visteras** [comment]
Alternatively, we can create exclusion templates for files (* .xml or vendor / *) so that we don't see this when creating a PR.

**Comment by lafriks** [comment]
This will be fixed by #16250

**Comment by lunny** [comment]
Duplicate of #31600
