### ISSUE TITLE
Edit wiki sidebar via UI

### ISSUE THREAD

**Issue by fnetX** [go-gitea/gitea#16655]
- Gitea version (or commit ref): 1.16.0+dev-88-geaa791bed
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes at https://try.gitea.io/fnetx/wikistuff/wiki/Home

## Description
Editing the wiki is possible via the web. There is the _Sidebar.md file that is rendered as a sidebar (although I can't find it documented after all). We are looking into documenting this to the Codeberg Docs and noticed that it wasn't possible to edit it afterwards via the Web UI (https://codeberg.org/Codeberg/Documentation/issues/160#issuecomment-246327)

Please either allow to edit this special page, or add an "Edit Sidebar" button. Maybe also a "Create Sidebar" button to make people aware of this opportunity.

## Screenshots

![Screenshot of a Gitea wiki index, there is a rendered sidebar, an edit button for the current page and a site navigation that does not show the special Sidebar page](https://user-images.githubusercontent.com/19634137/128687400-880202f7-09e6-4437-b77b-099a0973ae37.png)

**Comment by n194** [comment]
To clarify, it is possible to edit it by changing the URL to _Sidebar or _Footer, but it's not made obvious to the user.

For reference, here's GitHub's UI for editing:
![wiki-edit-sidebar-footer](https://user-images.githubusercontent.com/67550725/128692514-fc5e7e4c-9584-48fb-a9c0-9950e2209aa0.png)

and here's the UI suggesting to add a sidebar or footer.

![wiki-add-sidebar-footer](https://user-images.githubusercontent.com/67550725/128692524-21bc61ec-4f1b-4a20-8972-b792f779160a.png)

**Comment by Tanami** [comment]
This would be really great. The dropdown menu is a keyhole nuisance which adds extra clicking/scrolling time to navigate.

**Comment by silverwind** [comment]
Yeah some UI to create sidebar/footer would be very nice, it's a pretty much undiscoverable feature.

**Comment by n194** [comment]
Is there any URL scheme to create a new Wiki page with a given title?
