### ISSUE TITLE
The gogit implementation of git notes differs from the nogogit implementation

### ISSUE THREAD

**Issue by nitul1991** [go-gitea/gitea#16657]
- Gitea version (or commit ref): 1dc41c47b960a4f364228d267ec16e2835b15191
- Git version: 2.32.0
- Operating system: macOS Catalina version 10.15.6
- I built gitea from source and ran the tests via the command-line.
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
- Log gist:

## Description

Whilst working on the issue #15373, I discovered that the implementation of the gogit version of git notes differs from the no-gogit version when a non existent commit ID is passed to the function GitNote.
I brought this up on Discord and @zeripath suggested that I provide a fix for this issue in a separate PR so that it can be backported to version 1.15.

**Comment by zheangrybear** [comment]
id
