### ISSUE TITLE
Feature: Upload Files in Wiki Pages

### ISSUE THREAD

**Issue by HerrHase** [go-gitea/gitea#1666]
- Gitea version (or commit ref):
- Git version: 1.1.0
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] MSSQL
  - [x ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

Hello,
uploading Files in Pages of the Wiki, that would be really helpful. I use Wiki also for Planing and Brainstorming and sometimes it would be easier to upload scribbles or wireframes direkt to a page.

Thanks! :)

**Comment by lunny** [comment]
duplicated with #574
