### ISSUE TITLE
Placeholder for Outcome of Accessibility Audit

### ISSUE THREAD

**Issue by techknowlogick** [go-gitea/gitea#16660]
The Gitea project is currently reaching out to professionals who would be able to perform an accessibility audit (and be paid of course).

This issue is currently a placeholder for when we receive the report so we can coordinate remediation of issues identified.

If you are, or know, someone who can perform a professional accessibility audit of Gitea please reach out to the project team at maintainers@gitea.io (or any of the project owners per their email in CONTRIBUTING.md).

I'm going to lock this issue now as we don't yet have a report, and will reopen it once we have something to act upon.

I want to say a general thanks to everyone who has helped us so far in this matter.

Related issue:
* #7057
* #8638
* #10672
* #16581

**Comment by techknowlogick** [comment]
Some very good news, as part of our NLnet funding they provide us with access to accessibility experts, and while the amount of time we receive is likely not to be enough for a full audit there would still be that relationship established and we could ask if we could pay them directly for additional work.

**Comment by lunny** [comment]
Looks like all these issues are resolved.

**Comment by wxiaoguang** [comment]
Inactive for long time and these issues have been resolved.
