### ISSUE TITLE
U2F/FIDO does not work with Vivaldi browser

### ISSUE THREAD

**Issue by beedaddy** [go-gitea/gitea#16666]
- Gitea version (or commit ref): 1.14.5
- Git version: 2.20.1
- Operating system: Debian 10 (using gitea download with systemd)
  
  
  
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X ] No (didn't receive any account activation mail)
- Log gist:
  - There's nothing u2f-related in the debug-log.

## Description

Using u2f with Firefox browser on my gitea instance works very well. u2f with Vivaldi on other sites also works. But using Vivaldi on my gitea instance doesn't work at all. I tried to de-register and re-register my U2F device (Nitrokey FIDO2) but registering the device is not possible. Gitea tells me that my browser doesn't support U2F (which is not true).

## Screenshots

![Bildschirmfoto von 2021-08-11 13-02-07](https://user-images.githubusercontent.com/3264939/129021467-5f02198e-e945-4872-a12a-538084d8ca5f.png)

**Comment by lafriks** [comment]
Can you check in Vivaldi browser in JavaScript console what does this return:
```js
window.u2f
```

and

```js
window.u2f.sign
```

**Comment by beedaddy** [comment]
I hope I did this right. Here are the results:

> window.u2f

`undefined`

> window.u2f.sign
```
Uncaught TypeError: Cannot read property 'sign' of undefined
    at <anonymous>:1:12
```

> navigator.userAgent

`"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.134 Safari/537.36"`

**Comment by 6543** [comment]
#17957
