### ISSUE TITLE
Repository garbage collection:  context deadline exceeded

### ISSUE THREAD

**Issue by somera** [go-gitea/gitea#16671]
- Gitea version (or commit ref):
- Git version: 1.14.6
- Operating system: Ubuntu 20.04
  
  
  
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
- Log gist:

## Description

I can't run GC on all my repos (~5900).

After I start it it stops

```
2021/08/11 22:37:57 .../repository/check.go:87:func1() [E] Repository garbage collection failed for &{6061 77 apache <nil> hadoop hadoop   2 https://github.com/apache/hadoop.git trunk 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 false false false true <nil> 0 map[] map[] [] <nil> false 0 <nil> false 0 <nil> 718441243 <nil> <nil> false false [hadoop] default  1620514328 1628612608}. Stdout:
        Error: context deadline exceeded
        /source/modules/repository/check.go:87 (0x15f1bf3)
        /source/vendor/xorm.io/xorm/session_iterate.go:88 (0xc42f3b)
        /source/vendor/xorm.io/xorm/session_iterate.go:35 (0xc42949)
        /source/models/context.go:67 (0x141c084)
        /source/modules/repository/check.go:60 (0x15db893)
        /source/modules/cron/tasks_extended.go:56 (0x1fdf4b2)
        /source/modules/cron/tasks.go:88 (0x1fde6e1)
        /source/modules/graceful/manager.go:135 (0xc64437)
        /source/modules/cron/tasks.go:82 (0x1fdc744)
        /usr/local/go/src/runtime/asm_amd64.s:1371 (0x47a4a0)
```

My GC timeout is set to 3000 seconds.

```
; Operation timeout in seconds
[git.timeout]
#DEFAULT = 360
#MIGRATE = 600
#MIRROR = 1200
#CLONE = 1200
#PULL = 300
#GC = 240
DEFAULT = 360
MIGRATE = 6000
MIRROR = 3000
CLONE = 3000
PULL = 3000
GC = 3000
```
Is the value of 3000 seconds for every repo or whole run?

## Screenshots

![image](https://user-images.githubusercontent.com/8334250/129100789-a9018e1b-fc06-42c5-acee-26b61b2bf316.png)

**Comment by lunny** [comment]
Have you tried run `git gc` in this repository on server and how much time it will spend?

**Comment by somera** [comment]
> Have you tried run `git gc` in this repository on server and how much time it will spend?

I didn't try this. I can do this.

But there is a bug in Gitea. In my configuration is GC timeout set to 3000 seconds. Is this 3000 seconds for every repo or all repos?

Cause:

If for one repo, than it runs not longer than 3000 seconds.

But when I check my monitoring, than I would say, that the 3000 seconds are for all repos. Is this correct?

**Comment by somera** [comment]
@lunny I found the problem.

The timeout configuration

GC = 3000

means, that the GC task runs only 3000s (50 minutes). And this is not good. All other timeout settings 

```
; Operation timeout in seconds
[git.timeout]
DEFAULT = 360
MIGRATE = 6000
MIRROR = 3000
CLONE = 3000
PULL = 3000
```

are for each repo.

Not I set my GC timeout to 2h (7200 seconds).

**Comment by zeripath** [comment]
@somera Check that you haven't set `[cron.git_gc_repos]` `TIMEOUT` too as that will override the `[git]` `GC` setting.

To be honest the `[git]` `GC` setting should be considered legacy and removed.

**Comment by 99rgosse** [comment]
Hello,
Same issue here, but what is strange it's that the GC fails before reaching the 3000 sec

Gitea version (or commit ref):
Git version: 1.14.6
Operating system: Ubuntu 18.04
Database (use [x]):
- [X]  PostgreSQL
- [ ]  MySQL
- [ ]  MSSQL
- [ ]  SQLite

Can you reproduce the bug at https://try.gitea.io:
 No => I can't import this confidential data

Logs :
> 2021/08/12 08:26:31 Completed GET /admin/notices 200 OK in 138.746099ms
> 2021/08/12 08:29:16 .../repository/check.go:39:func1() [W] Failed to health check repository (&{260 43857 "GreatRepo" <nil> "GreatRepo" "GreatRepo"  1 https://"GreatRepo.com/GreatRepo".git master 4 0 0 0 0 0 0 0 0 0 0 0 0 0 0 false false false false <nil> 0 map[] map[] [] <nil> false 0 <nil> false 0 <nil> 792781717 <nil> <nil> true false [] default  1622560424 1622560466}): context deadline exceeded

The repository is about 756Mb with more than 10k commits, and is a migrated from self hosted Gitlab => I think that generates lots of errors, as there are branches and heads missing ( see #15155 )

Here is the log a little while later for another repo :

> 2021/08/12 08:37:41 .../repository/check.go:87:func1() [E] Repository garbage collection failed for &{365 4 "OTHER REPO" <nil> "OTHER REPO" "OTHER REPO" 4 https://"OTHER REPO".com/"OTHER REPO".git main/master 69 0 0 0 0 0 1945 1929 16 0 0 0 0 0 0 false false false false <nil> 0 map[] map[] [] <nil> false 0 <nil> false 0 <nil> 215460551 <nil> <nil> true false [] default  1627052947 1627053864}. Stdout: 
>         Error: exit status 128 - error: refs/pull/1/head does not point to a valid object!


The app.ini configuration is fairly stock, apart an LDAP and migrate from self hosted gitlab parameter.

**Comment by somera** [comment]
> @somera Check that you haven't set `[cron.git_gc_repos]` `TIMEOUT` too as that will override the `[git]` `GC` setting.

It was set to 60 seconds. I increased it now.

> To be honest the `[git]` `GC` setting should be considered legacy and removed.

ok. thx.

Now it's clear for me.

**Comment by 99rgosse** [comment]
> @99rgosse this
> 
> ```
> ; Garbage collect all repositories

Thank you ! I'll take a look at this part, I was searching for it in the cheat sheet :)

**Comment by somera** [comment]
> > @99rgosse this
> > ```
> > ; Garbage collect all repositories
> > ```
> 
> Thank you ! I'll take a look at this part, I was searching for it in the cheat sheet :)

https://docs.gitea.io/en-us/config-cheat-sheet/
