### ISSUE TITLE
Inconsitency between Swgger spec and Code

### ISSUE THREAD

**Issue by nektro** [go-gitea/gitea#16675]
- Gitea version (or commit ref): v1.14.6
- Git version: 2.30.2
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No

## Description
For the `Repository` type (there's bound to be others but I did not check everything) there is an inconsistency between the OpenAPI spec generated by Swagger and actual backing Go code.

https://try.gitea.io/api/swagger#model-Repository

https://pkg.go.dev/code.gitea.io/gitea@v1.14.6/modules/structs#Repository

As you will see, there are a number of fields which have their json tag paired with `omitempty`. However, these fields are not marked as optional in the swagger docs and so attempting to generate Gitea client bindings for another language based on these docs becomes problematic.

Swagger [actually expects a required list](https://swagger.io/docs/specification/data-models/data-types/#required) and says that all fields are optional by default. So by Gitea not having a `required` list it is not accurately Modelling its models.

**Comment by nektro** [comment]
It appears some definitions do actually have this property. Searching for `"required": [` in the raw json yields 26 results. However, given that there are 142 definitions as of this writing, I believe this issue still stands.

**Comment by nektro** [comment]
?

**Comment by nektro** [comment]
?

**Comment by lunny** [comment]
As mentioned above, you need to compare the same version. I will close this one, please reopen it if you have further quesiton.
