### ISSUE TITLE
User inactivated, auth 403 error.

### ISSUE THREAD

**Issue by TxcA** [go-gitea/gitea#16686]
- Gitea version (or commit ref):1.14.6
- Git version:2.28.0

## Description
After canceling the user activation, the warehouse created by the user, the collaborator push will cause 403 error.
`fatal: unable to access 'http://.../': The requested URL returned error: 403`

## Screenshots
![](https://files.catbox.moe/u8dmqp.png)

**Comment by techknowlogick** [comment]
This is how that option works.
