### ISSUE TITLE
Proposal: Remove the Dashboard/Home button from the navigation bar

### ISSUE THREAD

**Issue by n194** [go-gitea/gitea#16699]
I am proposing to remove the Dashboard/Home button to reduce the amount of items in the navbar and have a simpler experience for users. The Gitea icon already points to the same location, and for accessibility, an aria-label with `Dashboard` or `Home` can be added to the link. Users will also be familiar with this navigation style as it used on other software forges.

**Comment by lunny** [comment]
Then a hover action on the logo is better.
