### ISSUE TITLE
Add #issuecomment to E-Mail notification

### ISSUE THREAD

**Issue by jonasfranz** [go-gitea/gitea#1669]
Please add an #issuecomment-XXXXXX to a comment notification E-Mail.
The link to a comment look actually like this:

> https://the.gitea.url/ORG/REPO/issues/20#issuecomment-87

This is the E-Mail notification:

> ...
> 
> ---
> View it on Gitea ( https://the.gitea.url/ORG/REPO/issues/20 ) .

**Comment by jonasfranz** [comment]
OFFTOPIC: Do I need to assign this issue to me if I want to fix it via pull-request?

**Comment by lunny** [comment]
Yes. Please assign to yourself.

**Comment by lunny** [comment]
fixed by #1674
