### ISSUE TITLE
Not all Git tags are listed in Tags sub-tab of Releases Tab

### ISSUE THREAD

**Issue by pankajazad** [go-gitea/gitea#16702]
- Gitea version (or commit ref): 1.15.0-rc3
- Git version:2.32.0
- Operating system: Windows 10
  
Downloaded the built binary executable from github
  
Running as windows service 
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
- Log gist:

## Description

There are multiple tags in my repository, all of which are visible in commit graph view. But due to some reason only a screen full are visible in the Tags sub-tab of the Releases tab of the repository. May be multiple page view needs to be added/enabled for tags sub-tab. Tags belong to different branches. Few tags are visible for each branch... not all.

**Comment by noerw** [comment]
- You are talking about the page at `/<user>/<repo>/tags`, right?
- How many tags should there be, how many are displayed?
- You don't see any pagination bar at the bottom of the page? Because for me it does ([example](https://gitea.com/postgis/postgis/tags?page=2))

**Comment by pankajazad** [comment]
> referring to /<organization>/<repo>/tags

> there should be 13 tags, only 11 are displayed

> No pagination bar is visible for me. Maybe because of v 1.15.0-rc3.  The example page shows 1.16

> My tags are form Version1.0/draft-1.1, Version-1.0/draft-1.2, Release/1.0 and so on.

**Comment by pankajazad** [comment]
facing the same issue with release 1.15
