### ISSUE TITLE
PGP-Key: Problem with leading zero

### ISSUE THREAD

**Issue by Snck3rs** [go-gitea/gitea#16701]
Hello Guys,

i ran into a problem with PGP-Keys. After i've added my Key to Gitea and made my first signed commit it says that theres no matching key. I compared the key showed in the commit with my configured key and found out, that the leading zero of my key is missing in the commit-view.

Maybe there's a bug related to leading zeros in PGP-Keys?

_Account -> PGP-Keys_

![2021-08-16_10-00](https://user-images.githubusercontent.com/67102783/129531054-c8ce7ef8-bee3-4a8a-84ab-bb0f8b203665.png)

_Commit_ 

![2021-08-16_09-59](https://user-images.githubusercontent.com/67102783/129531057-da0e15ec-4bc5-4eb8-8a14-98450392d1f7.png)

**Installation Data**

- Gitea version: 1.14.4 and 1.15.0+RC3

- Database:
  - [x] MySQL

**Comment by zeripath** [comment]
On 1.15.0-rc3 the key tells you which identities it matches - that is the email addresses that were activated when the key was installed - does the commit you are trying to verify have match one of those identities?

On 1.15.0-rc3 you can verify the key to match any of your user's activated email addresses. Have you verified the key?

**Comment by zeripath** [comment]
Also, have you tried re-adding the key? If the key was added a long time ago - it's possible that it was affected by a previous bug that has been fixed.

If this genuinely is a bug it would be helpful to see an example of a commit on try.gitea.io with the key. If you'd prefer to not to make that public contact me on discord directly with details so that I can replicate.

**Comment by Snck3rs** [comment]
@zeripath thank you so much!

> On 1.15.0-rc3 the key tells you which identities it matches - that is the email addresses that were activated when the key was installed - does the commit you are trying to verify have match one of those identities?

the keys mail adresses where already activated before adding the key. so i've thought it would be enough just to add the key.

> 
> On 1.15.0-rc3 you can verify the key to match any of your user's activated email addresses. Have you verified the key?

That's it! After verifying the key everythink works like expected. Is this a new feature or have i just been blind in 1.14.4?

**Comment by Snck3rs** [comment]
> Also, have you tried re-adding the key? If the key was added a long time ago - it's possible that it was affected by a previous bug that has been fixed.

It was a new key added in 1.14.4, but i remembered the bugfix for this old problem so i've guessed it could be the same reason in my case too.

> 
> If this genuinely is a bug it would be helpful to see an example of a commit on try.gitea.io with the key. If you'd prefer to not to make that public contact me on discord directly with details so that I can replicate.

**Comment by Snck3rs** [comment]
b.t.w. i've created a small script for download and updating gitea a long time ago. Maybe it could be usefull for lazy bones like me ;-)

https://entwicklung.hq.tosit.de/Snck3rs/Gitea-Updater

**Comment by zeripath** [comment]
> @zeripath thank you so much!
> 
> > On 1.15.0-rc3 the key tells you which identities it matches - that is the email addresses that were activated when the key was installed - does the commit you are trying to verify have match one of those identities?
> 
> the keys mail adresses where already activated before adding the key. so i've thought it would be enough just to add the key.

It should be - I guess the key has to have the email address in it too.
 
> > On 1.15.0-rc3 you can verify the key to match any of your user's activated email addresses. Have you verified the key?
> 
> That's it! After verifying the key everythink works like expected. Is this a new feature or have i just been blind in 1.14.4?

Yes - new feature in 1.15 - see #14054

**Comment by Snck3rs** [comment]
> > @zeripath thank you so much!
> > > On 1.15.0-rc3 the key tells you which identities it matches - that is the email addresses that were activated when the key was installed - does the commit you are trying to verify have match one of those identities?
> > 
> > 
> > the keys mail adresses where already activated before adding the key. so i've thought it would be enough just to add the key.
> 
> It should be - I guess the key has to have the email address in it too.

that's strange. my key should have the mail address in it. plus a second identity with another email address. Both mail addresses have been configured in my gitea account before adding the key itself. if you want to dig deeper into that case i could provide you the informations you need.
> 
> > > On 1.15.0-rc3 you can verify the key to match any of your user's activated email addresses. Have you verified the key?
> > 
> > 
> > That's it! After verifying the key everythink works like expected. Is this a new feature or have i just been blind in 1.14.4?
> 
> Yes - new feature in 1.15 - see #14054

**Comment by zeripath** [comment]
I think it would be useful to see an example commit that isn't verifying on try or elsewhere.
