### ISSUE TITLE
Read-only config mode

### ISSUE THREAD

**Issue by clarfonthey** [go-gitea/gitea#16726]
## Description

Right now, gitea will always attempt to open app.ini and other config files (like `INTERNAL_TOKEN_URI`) in read-write mode. This causes the process to fail when these files are marked as read-only.

It seems desirable to be able to open these files when they are not writable by gitea, falling back to errors when they would otherwise need to be written.

Side note, I've been experimenting with watching for config changes for various services I use, and auto-restarting the services when they change. For gitea this is infeasible due to it opening all its files as writeable, since it will get caught in a restart-loop.

**Comment by lunny** [comment]
I think maybe it should be related with `INSTALL_LOCK`. If it's true, then it could be read-only. Otherwise, Gitea could change it.

**Comment by noerw** [comment]
see also #7263

**Comment by wxiaoguang** [comment]
Dup with
* https://github.com/go-gitea/gitea/issues/7263
