### ISSUE TITLE
Matrix URIs aren't rendered as links

### ISSUE THREAD

**Issue by Mikaela** [go-gitea/gitea#16721]
- Gitea version (or commit ref): 1.15.0-rc3
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes: https://try.gitea.io/Mikaela/gist-manual/src/branch/master/matrix/spaces.md

## Description

Linking to a Matrix URI such as: `[Mikaela.info](matrix:roomid/psumPMeAfzgAeQpXMG:feneas.org?action=join&via=feneas.org&via=sorunome.de&via=the-apothecary.club&via=pirateriot.net&via=matrix.org)` renders as text instead of a clickable link.

<s>Matrix URI scheme is proposed in https://github.com/matrix-org/matrix-doc/blob/master/proposals/2312-matrix-uri.md and is being proposed in https://github.com/matrix-org/matrix-doc/pull/3168.</s>

Update: [Matrix URI scheme is specified in Matrix 1.2](https://spec.matrix.org/latest/appendices/#matrix-uri-scheme) and [recognised by IANA](https://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml).

## Screenshots

* https://gitea.blesmrt.net/mikaela/gist/src/branch/master/matrix/spaces.md
  * ![image](https://user-images.githubusercontent.com/831184/129938516-fa48f31f-c3b7-4e8e-8847-b7f64420f26c.png)
  * ![image](https://user-images.githubusercontent.com/831184/129938656-31009449-4ec6-4ed7-ab61-3b59fceb6afc.png)

**Comment by ShadowJonathan** [comment]
FWIW, `matrix:` is a properly recognised URI at the moment; https://www.iana.org/assignments/uri-schemes/prov/matrix

The URI is already proposed and has passed a "final comment period" in https://github.com/matrix-org/matrix-doc/pull/2312, and https://github.com/matrix-org/matrix-doc/pull/3168 is only to formalise the wording into the specification.

**Comment by Mikaela** [comment]
I updated the original comment a bit on that Matrix URI scheme became part of Matrix Specification in version 1.2 and included the IANA bit.

* https://spec.matrix.org/latest/appendices/#matrix-uri-scheme
