### ISSUE TITLE
Ability to remove issues

### ISSUE THREAD

**Issue by Kreyren** [go-gitea/gitea#16722]
Add ability to remove issues, see https://git.dotya.ml/RiXotStudio/RiXotStudio/issues/1

- Gitea version (or commit ref): 1.16.0+dev-115-g37d0d9484 
- Git version: Unknown
- Operating system: Unknown (arch?)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
  - [x] Unknown
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes (provide example URL)
  - [ ] No
- Log gist: Not relevant

**Comment by Kreyren** [comment]
@techknowlogick Link the duplicate i wasn't able to find the relevant issue

**Comment by techknowlogick** [comment]
https://github.com/go-gitea/gitea/issues/923
