### ISSUE TITLE
Project Webhook fails on Gitea1.11.4

### ISSUE THREAD

**Issue by danshufenxiang** [go-gitea/gitea#16730]
- Gitea version (or commit ref):1.11.4
- Git version:2.24.1
- Drone version:1.6
- Operating system:Debian 4.19.98-1
- Log gist:
docker logs drone --tail=20
`"error":"client is not authorized","event":"push","level":"warning","msg":"trigger: cannot find yaml","ref":"refs/heads/master",
`
## Description
Today I don’t know why one of the project push changes did not trigger the deployment.

## Screenshots
<img width="1139" alt="iShot2021-08-18 17 06 46" src="https://user-images.githubusercontent.com/45238979/130021207-c7fbd982-be62-4eec-a855-2e6a302399b9.png">
<img width="1142" alt="iShot2021-08-18 17 06 32" src="https://user-images.githubusercontent.com/45238979/130021244-9632a458-563a-4202-be29-f66fd4baec68.png">

**Comment by danshufenxiang** [comment]
用管理员账号在drone对应的项目settings里面关闭然后重启项目，对应的gitea仓库里面的web钩子就更新了~目前只找到这个方法~

**Comment by KN4CK3R** [comment]
There will be no fix for Gitea 1.11.x even if there is an error. You may update your installation.
