### ISSUE TITLE
Missing argument in doc for Docker SSH passthrough

### ISSUE THREAD

**Issue by ThibaultNocchi** [go-gitea/gitea#16748]
- Gitea version (or commit ref):
- Git version: 1.14.6
- Operating system: Host Arch, Gitea in Docker
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite

## Description
I reinstalled Gitea on a new Arch host in a Docker. I also transferred my Docker volume to the new container.
I followed the instructions here https://docs.gitea.io/en-us/install-with-docker/#ssh-container-passthrough to set the SSH passthrough, and I think the shell script that goes in `/app/gitea/gitea` on the host is missing something.

If I used `ssh -p 2222 -o StrictHostKeyChecking=no git@127.0.0.1 "SSH_ORIGINAL_COMMAND=\"$SSH_ORIGINAL_COMMAND\" $0 $@"` as advised, I was getting errors like this:

```
ssh: connect to host MY_HOST port 2222: Connection refused
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists
```

I fetched back my previous config and it add a `-i /home/git/.ssh/id_rsa` argument added: ` ssh -i /home/git/.ssh/id_rsa -p 2222 -o StrictHostKeyChecking=no git@127.0.0.1 "SSH_ORIGINAL_COMMAND=\"$SSH_ORIGINAL_COMMAND\" $0 $@"`

Is it normal? If yes, I should maybe do a simple PR to fix the doc? Thanks!

**Comment by wxiaoguang** [comment]
The doc has been updated recently

**Comment by ThibaultNocchi** [comment]
Thank you, have a nice day!
