### ISSUE TITLE
deleting wrong image attachments from issue comments

### ISSUE THREAD

**Issue by noerw** [go-gitea/gitea#16749]
- Gitea version (or commit ref): 1.16.0+dev-125-g03937891e, also current codeberg
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes: https://try.gitea.io/noerw/hochwasser/issues/3#issuecomment-88871

## Description
1. create an issue(comment) and paste multiple images via ctrl+v (resulting in an image upload + markdown img tag)
2. edit the comment, and delete the second file
3. the wrong image is deleted (in my case the 3rd image, not the 2nd)

It seems that initially adding images via dropzone does not cause this issue.

## Screenshots
better look at the try.gitea.io link above

**Comment by KN4CK3R** [comment]
I can reproduce it. Should be fixed before 1.15 release.

**Comment by zeripath** [comment]
I'm struggling to reproduce this.

**Comment by KN4CK3R** [comment]
Still works for me on try.gitea.io
I deleted the "H2" image but afterwards the "H3" image is missing:

![grafik](https://user-images.githubusercontent.com/1666336/131666678-18ce418b-f402-4a0b-bc3a-6f13be460ae2.png)

**Comment by wxiaoguang** [comment]
Look at this  https://github.com/go-gitea/gitea/pull/16915  😂

**Comment by zeripath** [comment]
ah I suspected it was going to be a same name thing - but the bug report does not state that.

**Comment by noerw** [comment]
@wxiaoguang thank you!
