### ISSUE TITLE
Feature Request: Implement Nodeinfo endpoints for federation discovery

### ISSUE THREAD

**Issue by techknowlogick** [go-gitea/gitea#16758]
Nodeinfo is a way to expose certain metadata about a server for use of discovery regarding functionality of its federation capabilities.

Two endpoints are required:
1. `/.well-known/nodeinfo` which informs client where it can find the location of the location of its metadata (including which version of the schema is used)
2. the endpoint which exposes the metadata in json format according to schema.

Notes:
* `openRegistrations` is a required field, but I propose to set to false as default in case someone writes a crawler to discover "open" gitea instances
* to limit data leakage I also propose to not include the `usage` field (note it is required so it should be included, but left as empty).

More info:
https://github.com/jhass/nodeinfo
https://github.com/jhass/nodeinfo/tree/main/schemas/2.1
http://nodeinfo.diaspora.software/protocol.html

cc: @pilou-

**Comment by techknowlogick** [comment]
I claim 2,500€ from the fedeproxy Gitea federation grant for the work I did to create this issue and implement the associated pull request, where 25% will be split among the reviewers, and 25% will go to the project (via opencollective).

@lunny / @lafriks do you approve this? (more info linked here: https://forum.fedeproxy.eu/t/howto-5-000-grant-earmarked-for-gitea-federation/330/17)

**Comment by lafriks** [comment]
I approve
