### ISSUE TITLE
No syntax highlighting on .tmpl files

### ISSUE THREAD

**Issue by n194** [go-gitea/gitea#16761]
- Gitea version (or commit ref): 1.16.0+dev-130-g0bd58d61e
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes: 
  - [ ] No

## Description
Gitea doesn't show any syntax highlighting on .tmpl files in the Web UI

See example: https://try.gitea.io/n/gitea/src/branch/main/templates/home.tmpl

**Comment by clarfonthey** [comment]
The reason for this is that you can't guarantee the type of template from the file alone. I don't think there's a standard file extension for go templates, but if there were, then we could go based off of that.

**Comment by zeripath** [comment]
I think it's actually supposed to be .go.tmpl 

Realistically any heuristic measure is going to get things wrong from time to time so we should have a way to select the language and we should use git attributes for hints too.
