### ISSUE TITLE
gitea-src-1.15.0.tar.gz is missing node_modules

### ISSUE THREAD

**Issue by ecsgh** [go-gitea/gitea#16769]
Since several versions the corresponding source.tar.gz file contains the necessary node_modules.
Unfortunately, these are completely missing in gitea-src-1.15.0.tar.gz.
Can someone please add this again and post a new source.tar.gz?

**Comment by noerw** [comment]
This was a deliberate change in #16769
To make any broken setups work again, just run `make build` (or equivalent commands) (+ make sure you have nodejs 16 installed)

**Comment by ecsgh** [comment]
I don't quite agree with the close.
I had already written this several times, that a build system does not come to the Internet to download additional sources.
By removing the nodejs module it is no longer possible to package gitea in a build system.

So. again the question.
How do I get the node_molules to package gitea in a build system that can't access the internet?

**Comment by zeripath** [comment]
node_modules is not architecture independent anymore.

> prebuilt UI files are shipped in the public directory.

Do you have to re-build the UI?

**Comment by ecsgh** [comment]
No I haven't for versions.
And no problems at all.
Before that I built the packages with npx and less.
At some point it was said but you do not need it anymore.

**Comment by zeripath** [comment]
`make backend` will build the binary without reattempting to build the frontend.

As the linked PR states node_modules is now architecture dependent so can't really be distributed.
