### ISSUE TITLE
Unify migration descriptions

### ISSUE THREAD

**Issue by delvh** [go-gitea/gitea#16777]
- Gitea version (or commit ref): 1.16.0+dev-138-gdb1e3d02a

## Description
Currently, there does not seem to exist a standard for the migration descriptions.
I, and most likely everyone else as well would prefer it, if these descriptions would be unified.
What do I mean by that?
1. I would replace `Migrating data …` with its more precise version `Migrate data …` as currently no action is already being performed
2. Some URLs are started with a capital letter, and some are not (example: `Github.com`, `notabug.org`). Either all URLs should start with their first letter capitalized, or none at all. In the first case: How do you handle urls with subdomains (especially `code.onedev.io`)? Do you capitalize all domain starting letters, or only the first?
3. Unify the overall descriptions: Currently, the unique descriptions each differ slightly enough to be noticeable. I think it would be better to use a unified approach for everything such as `Migrate data from <Provider.URL> or other <Provider> instances.`
4. Cut the `or Mirroring` from `Migrating or Mirroring git data from Git services` in `migrate.git.description`. All other migration descriptions also enable this and don't publicly announce it.

## Screenshots
![image](https://user-images.githubusercontent.com/51889757/130405249-c4663be1-d2ed-4b6a-a2a6-145e632527a6.png)
Current appearance (in 1.15, not current dev 1.16)
![image](https://user-images.githubusercontent.com/51889757/130405785-8b7000d7-7e44-4805-8b51-4d62ae88166a.png)
Expected result afterwards

**Comment by zeripath** [comment]
I think it's probably best just to send a PR updating locale-en_US (with screenshots - although I know that's going to be annoying to do.)
