### ISSUE TITLE
HTML/View Template is rendered twice

### ISSUE THREAD

**Issue by PhoenixPeca** [go-gitea/gitea#16771]
- Gitea version (or commit ref): v1.15.0
- Git version: not relevant
- Operating system: Ubuntu (Gitee docker via mailcow setup)
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No -- the gitea server did not send me the activation link.
- Log gist: not relevant

## Description

I'm not sure if this issue has been reported already, but after researching the existing issues in this repo, seems like this is a new one.

Anyways... here's a bug that I found:

 I'm using the latest release of Gitea (v1.15.0) and created a new empty repository. I opened the repository Settings and clicked on the "Add Push Mirror" button without any change to the other fields and somehow the webpage just reloads and renders two copies of the same template. Attached is the fullpage screenshot.

## Screenshots

Fullpage PDF Screenshot: [screencapture-mail-aspac-io-gitea-phoenix-testing-settings-2021-08-22-23_09_30.pdf](https://github.com/go-gitea/gitea/files/7027598/screencapture-mail-aspac-io-gitea-phoenix-testing-settings-2021-08-22-23_09_30.pdf)

Fullpage PNG Screenshot![image](https://user-images.githubusercontent.com/9730242/130357853-0be27fb6-1283-4315-b8a4-0e500146777c.png)
[screencapture-mail-aspac-io-gitea-phoenix-testing-settings-2021-08-22-23_09_30.pdf](https://github.com/go-gitea/gitea/files/7027604/screencapture-mail-aspac-io-gitea-phoenix-testing-settings-2021-08-22-23_09_30.pdf)

**Comment by delvh** [comment]
I would like to mention that these are not two exactly equal copies:
Copy one has as error message
`You are not allowed to import local repositories`, and copy two has
`the provided url is invalid. You must escape all components of the URL correctly. `
So, could it be that the copy behavior is triggered by two different error messages being present at once, and for each error message the site is created again?
