### ISSUE TITLE
Installing package via brew tap gives error

### ISSUE THREAD

**Issue by MarcelXia** [go-gitea/gitea#16778]
Gitea version (or commit ref): the one that I will get when trying to get it via brew

git version 2.33.0

Operating system: Mac Big Sur 11.5.2

This is the output with the error I see in the terminal:
```
brew tap gitea/tap https://gitea.com/gitea/homebrew-gitea
==> Tapping gitea/tap
Cloning into '/opt/homebrew/Library/Taps/gitea/homebrew-tap'...
remote: Enumerating objects: 417, done.
remote: Counting objects: 100% (417/417), done.
remote: Compressing objects: 100% (291/291), done.
remote: Total 417 (delta 252), reused 224 (delta 125), pack-reused 0
Receiving objects: 100% (417/417), 80.98 KiB | 241.00 KiB/s, done.
Resolving deltas: 100% (252/252), done.
Error: Invalid formula: /opt/homebrew/Library/Taps/gitea/homebrew-tap/tea.rb
tea: Unsupported system darwin-arm64
Error: Cannot tap gitea/tap: invalid syntax in tap!
```

**Comment by noerw** [comment]
Thanks for reporting. We already track this on the tap repo https://gitea.com/gitea/homebrew-gitea/issues/141
Could you run `export HOMEBREW_VERBOSE=1` prior to running brew tap for more debug info?

**Comment by wxiaoguang** [comment]
It has been closed https://gitea.com/gitea/homebrew-gitea/issues/141
