### ISSUE TITLE
Upgrade to Gitea 1.15.0 - service doesn't start WinSrv 2008R2

### ISSUE THREAD

**Issue by sasa00** [go-gitea/gitea#16784]
- Gitea version (or commit ref): 1.15.0
- Git version:  version 2.25.1.windows.1
- Operating system: WinSrv 2008 R2 with ready built gitea-1.15.0-windows-4.0-amd64.exe
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ x] No
- Log gist:
[log.txt](https://github.com/go-gitea/gitea/files/7031028/log.txt)

Hi,

I tried updating from v1.14.6 to 1.15.0. After restarting the service I get an error 1067 from Services:
![image](https://user-images.githubusercontent.com/5843305/130430178-53f93d97-dc58-4173-87a4-ac1314536fea.png)

In the log files I could not see any error. Last entry finishes with:
`[2 Cron: Check all repository statistics has finished 1629713364] - 1ms`

I already switched log to "DEBUG". 

KR,
Sascha

**Comment by noerw** [comment]
Did you follow the migration notes described in https://blog.gitea.io/2021/08/gitea-1.15.0-is-released?

..this looks quite similar to #16779, as the log does not contain any errors and fails to start after the update.

**Comment by zeripath** [comment]
Can you try just starting gitea from a command line and seeing if something is emitted there.

**Comment by sasa00** [comment]
Hello,

in the meantime I figured out what was wrong. I had a "install-service"- script with "\\" as folder dividers for the app.ini. This does not seem to work anymore. I changed my add service script 
from:
`sc.exe create gitea start= auto binpath= "\"c:\gitea\gitea.exe\" web --config \"c:\gitea\custom\conf\app.ini\""`
to:
`sc.exe create gitea start= auto binpath= "\"c:\gitea\gitea.exe\" web --config \"c:/gitea/custom/conf/app.ini/""`

and re-installed the service (remove & add again). This made my gitea server start again. Additionally I had an error in an template where I exchanged the gitea logo with our company logo and the new version did not find the "{{StaticUrlPrefix}}" variable anymore. I just deleted the template and now gitea seems to work again.

Nevertheless, thanks you for the fast response;

Sascha

**Comment by zeripath** [comment]
> Additionally I had an error in an template where I exchanged the gitea logo with our company logo and the new version did not find the "{{StaticUrlPrefix}}" variable anymore. I just deleted the template and now gitea seems to work again.

this is probably the root cause for the death. It causes an unguarded panic in a goroutine when the templates get compiled and kills the server.

The panic would only get emitted on the console as it's completely unguarded and so its logging is made by the go runtime as it kills program - not our logging suite.
