### ISSUE TITLE
Drone CI cannot authorize since update to 1.15.0

### ISSUE THREAD

**Issue by SuNNjek** [go-gitea/gitea#16787]
- Gitea version (or commit ref): 1.15.0
- Git version: -
- Operating system: Raspian Buster 64bit (running on Docker)
  
  
  
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
  - [ ] MSSQL
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
- Log gist:

```
gitea_1  | 2021/08/23 17:20:02 Started GET /Sunner/repo/settings/hooks/7 for 172.19.0.1:52506
gitea_1  | 2021/08/23 17:20:02 Completed GET /Sunner/repo/settings/hooks/7 200 OK in 77.765394ms
gitea_1  | 2021/08/23 17:20:03 Started GET /avatar/1afa6262175f1751761e57c71d890c6e?size=96 for 172.19.0.1:52510
gitea_1  | 2021/08/23 17:20:03 Completed GET /avatar/1afa6262175f1751761e57c71d890c6e?size=96 302 Found in 5.426332ms
gitea_1  | 2021/08/23 17:20:06 Started POST /Sunner/repo/settings/hooks/7/test for 172.19.0.1:52514
gitea_1  | 2021/08/23 17:20:06 Completed POST /Sunner/repo/settings/hooks/7/test 200 OK in 47.667596ms
gitea_1  | 2021/08/23 17:20:07 Started POST /login/oauth/access_token for 172.19.0.1:52526
gitea_1  | 2021/08/23 17:20:07 Completed POST /login/oauth/access_token 400 Bad Request in 1.278394ms
```

## Description

After updating to 1.15.0 my Drone CI webhooks stopped working. They were working fine before. All requests just return "client not authorized" and the Gitea logs say that the OAuth request is invalid. I have already tried revoking the OAuth token and refreshed the secret but to no avail.

## Screenshots
![grafik](https://user-images.githubusercontent.com/20151081/130479584-b54593d0-4453-4d4e-a567-d303683a3a92.png)

**Comment by jolheiser** [comment]
I believe this is because of https://github.com/go-gitea/gitea/pull/16010

Please refer to the breaking changes on the blog or referenced PR for steps to fix.

**Comment by jolheiser** [comment]
I'll re-open, though I'm still thinking it's a result of the JWT PR. I will look into it further later unless someone else gets to it first.

cc @KN4CK3R @zeripath thoughts?

**Comment by SuNNjek** [comment]
Ok, after changing the column types in the Drone database (as suggested in the linked PR, must've missed that the first time, sorry :cold_sweat:) it's working now.
