### ISSUE TITLE
OSX m1 build

### ISSUE THREAD

**Issue by hirako2000** [go-gitea/gitea#16809]
- Any version of Gitea
- Operating system:
   OSX Big Sur, m1 Apple Silicon

## Description
Finding binaries for M1 OSX is a desperate hunt. Two issues were raised and closed with vague answers.
Please keep an issue open until a solution is provided, or at least a decent work around proposed.

M1 models have been rolled out nearly a year ago, and compilers support the arm64 platform. Please provide a suggestion for M1 systems, that being compiling from source until binaries are made available. Currently neither the github release repo nor brew repos provide binaries for arm64 OSX systems which are now used by millions.

thanks.

**Comment by techknowlogick** [comment]
We've been compiling for m1 for a while now and the latest release has arm binaries specifically built for the m1 https://github.com/go-gitea/gitea/releases/download/v1.15.0/gitea-1.15.0-darwin-10.12-arm64

**Comment by hirako2000** [comment]
Thanks. Things are not clear whatsoever. I will look into providing dmg and see what brew team is up to.

Sorry for the false claim no binary was present anywhere. It's a clarity issue that's all.

**Comment by hirako2000** [comment]
That's not the kind of display that promotes adoption. I know the blame should rather be put on Apple, but hey.

<img width="246" alt="Monosnap 2021-08-25 05-33-22" src="https://user-images.githubusercontent.com/1500712/130698877-d5455241-18c3-42b4-af64-043249824c25.png">

**Comment by techknowlogick** [comment]
Indeed, that error is definitely concerning. We have instructions for those on macOS who wish to install Gitea https://docs.gitea.io/en-us/install-from-package/#macos where that error won't show. brew is also the recommended install process of Gitea on macOS

That error only happens when you download the binary via the web browser, but if the binary is fetched via wget/curl then macOS doesn't show the warning.

While I have a personal apple developer subscription which can notarize binaries, the project itself doesn't (nor can it as apple doesn't accept our organization type). We also lack appropriate CI resources (aka a mac buildbox) to be able to notarize the binaries.

**Comment by hirako2000** [comment]
```some@hosr-MacBook-big-sur dev % brew tap gitea/tap https://gitea.com/gitea/homebrew-gitea
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 3 taps (homebrew/core, homebrew/cask and homebrew/bundle).
==> Updated Formulae
Updated 23 formulae.
==> Updated Casks
Updated 13 casks.

==> Tapping gitea/tap
Cloning into '/opt/homebrew/Library/Taps/gitea/homebrew-tap'...
remote: Enumerating objects: 420, done.
remote: Counting objects: 100% (420/420), done.
remote: Compressing objects: 100% (294/294), done.
remote: Total 420 (delta 254), reused 224 (delta 125), pack-reused 0
Receiving objects: 100% (420/420), 82.09 KiB | 840.00 KiB/s, done.
Resolving deltas: 100% (254/254), done.
Error: Invalid formula: /opt/homebrew/Library/Taps/gitea/homebrew-tap/tea.rb
tea: Unsupported system darwin-arm64
Error: Cannot tap gitea/tap: invalid syntax in tap!
```

Please let's make this a real issue, since neither the bin can run, nor the first recommendation to execute it work either.
REOPEN. the issue, first.

Then. Let's a agree the problem is serious. since we can't install with the official package osx workflow, nor with brew, nor trying to execute the exec via the command line. This problem is wider than those operating with Linux think.

For the wider adoption of OSX, this software should run under m1 64arm, and under 64/32 bits of the OSX versions without unjustified invasions that make users think the software should simply not run under their system, or even worse, isn't even runnable under their system for the layman.

So, we got to provide a dmg packaged binary. Which is the still standard install format for any software under OSX.
This dmg shall be notarised, and sadly built with an OSX running machine. And signed for publication. If you can't publish via the Apple streams, at least notaries and provide .dmg (or pkg if that works) formats. If this is trouble I will provide assistance to my capacity.

Here again, million of people are on M1 at this point, and more to come. Decentralised git software deserve to be conveniently installed for spread across systems. If this fails, then that's allowing a serious wall between communities..
 
Here again.

1/ Re-open the issue.
2 Wait until community approves the fix/solution
3/ Seek help if you don't know how to expedite a fix
4/ Think twice, don't ignore. I understand thousands of issues is hard. but this one is a serious adoption one.
5/ Keep cool. You guys are awesome. You did great in the past, and I trust you will do greater things going forward.

**Comment by zeripath** [comment]
The problem with Tap is already reported elsewhere but is best looked at on https://gitea.com/gitea/homebrew-gitea/issues/141 If you can help resolve that that would be helpful.
