### ISSUE TITLE
Number of commits from push listed on the start page is wrong

### ISSUE THREAD

**Issue by whannes** [go-gitea/gitea#16804]
The number of commits from a push listed on the start page refers to the number of items in the list rather than the actual number of commits:
![grafik](https://user-images.githubusercontent.com/41183585/130639194-aa33d3ef-791a-4549-bf05-c85f49485e38.png)
![grafik](https://user-images.githubusercontent.com/41183585/130639526-df232bd5-103b-40b5-9278-6cce5a148830.png)

- Gitea version:  1.15.0 (https://github.com/go-gitea/gitea/releases/download/v1.15.0/gitea-1.15.0-linux-amd64)
- Git version:     2.20.0
- Operating system: CentOS 7 with PostgreSQL

**Comment by lunny** [comment]
I also found the bug. Even if you push one commit, but it will always display recent 5 commits.

**Comment by zeripath** [comment]
OK This is a regression from #9370

This will need a migration and/or a doctor script to fix.

**Comment by zeripath** [comment]
Unfortunately I think the correct length for these actions is unrecoverable. :frowning_face:
