### ISSUE TITLE
Add UI hints to create a Wiki sidebar and footer

### ISSUE THREAD

**Issue by n194** [go-gitea/gitea#16800]
## Description
Mentioned in #16719 and lost in #16655, this issue is about adding UI hints on the Wiki from which a user with edit access can quickly create a sidebar or footer.

## Screenshot from GitHub
![wiki-add-sidebar-footer](https://user-images.githubusercontent.com/67550725/128692524-21bc61ec-4f1b-4a20-8972-b792f779160a.png)

**Comment by zeripath** [comment]
This would be a simple change to `templates/repo/wiki/view.tmpl` around line 63 + change to `options/locale/locale_en-US.ini` for localisation.

**Comment by n194** [comment]
@zeripath how do you open the Wiki editor with a pre-defined page name?

**Comment by zeripath** [comment]
ah you want to add that... 

that would need a change to routers/web/repo/wiki.go:NewWiki() 

Probably as simple as adding:

```go
if ctx.Form("title") != "" {
  ctx.Data["title"] = ctx.Form("title")
}
```

then you'd need to add `?title=...` to the url
