### ISSUE TITLE
Request: Citation File Format

### ISSUE THREAD

**Issue by SommerEngineering** [go-gitea/gitea#16825]
It would be good if Gitea offered support for the new citation file format, cf. https://citation-file-format.github.io/ and https://blog.front-matter.io/mfenner/step-forward-for-software-citation

This is intended to allow scientists to cite software repositories. I can imagine an implementation similar to Github: Similar to the buttons for forks and downloads of repositories, there may be a new button. This will only be shown if the `CITATION.cff` file exists. With one click the user can copy the citation as e.g. BibTeX to the clipboard.

**Comment by gouravmohanty7070** [comment]
Can I work on this? It would be great if you brief me a bit about the issue!

**Comment by solarchemist** [comment]
Was just thinking about opening an issue on [Codeberg](https://codeberg.org/) asking for this integration. Glad to see Gitea is already on it :-)

I really agree, it would be great if Gitea (and by extension, Codeberg) offered support for this.
The links provided by @SommerEngineering offer a very good summary on CFF. I have nothing to add, really, except for a big thumbs up!
