### ISSUE TITLE
dump and manual restore causes broken external auth sources.

### ISSUE THREAD

**Issue by TwoTwenty** [go-gitea/gitea#16831]
- Gitea version (or commit ref): 1.14.6
- Git version:
- Operating system: ubuntu 2004
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x ] No

...

using gitea dump to backup my system then restored it I realized that all the external authentication is broken.

During the restore process I deleted the old DB and restored it the with the command provided in the docs. 
```mysql --default-character-set=utf8mb4 -u$USER -p$PASS $DATABASE <gitea-db.sql```

now when users from external auth try to login they get error 500 and also when trying to edit the sources from my local admin account they also error 500. 

This is reproducible with my setup but I have not tried to setup external auth with a vanilla install. please let me know if more details are needed.

**Comment by lunny** [comment]
Maybe we should publish v1.15.1 or v1.14.7 ASAP

**Comment by zeripath** [comment]
Yup I think so

**Comment by zeripath** [comment]
The underlying bug also means that the `config` field in the `repo_unit` table has also been corrupted.
