### ISSUE TITLE
Unable to apply settings in Gitea ARM

### ISSUE THREAD

**Issue by ulm0** [go-gitea/gitea#1683]
- Gitea version (or commit ref):
a503947
- Git version:
2.11.1
- Operating system:
Alpine
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
## Description
I'm facing a problem with Gitea in ARM, when trying to apply settings to a (any) project (e.g. change project privacy o convert a mirror project into a normal one) it hangs until it's unavailable to access.

I think it has to do with the Go version it is built on (though i can't confirm), i say this because i try to do the same in https://try.gitea.io and it works, but not on my instance of Gitea.
at the time of this writing i'm using the same commit as in https://try.gitea.io but they're built on different go versions.

### try.gitea.io

![screenshot from 2017-05-05 01-10-23](https://cloud.githubusercontent.com/assets/13160093/25733480/d56ca786-312f-11e7-84e4-76bd329f9e24.png)

#### My Gitea instance
![screenshot from 2017-05-05 01-10-36](https://cloud.githubusercontent.com/assets/13160093/25733489/ed4bde4e-312f-11e7-842e-d7a183245bc2.png)

**Comment by zeripath** [comment]
Hi do you still experience this problem on v1.8.2 on the arm6 build?

**Comment by ulm0** [comment]
Sadly, i'm not using Gitea anymore.
