### ISSUE TITLE
500 on CSV diff: runtime error: index out of range

### ISSUE THREAD

**Issue by silverwind** [go-gitea/gitea#16837]
- Gitea version (or commit ref): latest 1.15, https://github.com/go-gitea/gitea/commit/0c7927fe48b29769dd5da2d585ecde54dcbb4f4d
- Git version: 2.33.0
- Operating system: Ubuntu 20.04

When viewing a certain CSV diff, I see a 500 and this error in the log:

````
2021/08/27 13:14:14 ...s/context/context.go:195:HTML() [E] Render failed: template: repo/diff/csv_diff:3:15: executing "repo/diff/csv_diff" at <call .root.CreateCsvDiff .file .root.BaseCommit .root.HeadCommit>: error calling call: runtime error: index out of range [-1]
````

I can't share the particular CSV content but will try to fabricate a file that reproduces that error.

**Comment by zeripath** [comment]
It would be helpful if you could upload an example CSV to try.gitea.io.

I think:

```patch
diff --git a/templates/repo/diff/csv_diff.tmpl b/templates/repo/diff/csv_diff.tmpl
index b86e9d2a7..b037e29b8 100644
--- a/templates/repo/diff/csv_diff.tmpl
+++ b/templates/repo/diff/csv_diff.tmpl
@@ -12,7 +12,9 @@
 						{{if and (eq $i 0) (eq $j 0)}}
 							<th class="line-num">{{.RowIdx}}</th>
 							{{range $j, $cell := $row.Cells}}
-								{{if eq $cell.Type 2}}
+								{{if not $cell}}
+									<th></th>
+								{{else if eq $cell.Type 2}}
 									<th class="modified"><span class="removed-code">{{.LeftCell}}</span> <span class="added-code">{{.RightCell}}</span></th>
 								{{else if eq $cell.Type 3}}
 									<th class="added"><span class="added-code">{{.LeftCell}}</span></th>
@@ -25,7 +27,9 @@
 						{{else}}
 							<td class="line-num">{{if .RowIdx}}{{.RowIdx}}{{end}}</td>
 							{{range $j, $cell := $row.Cells}}
-								{{if eq $cell.Type 2}}
+								{{if not $cell}}
+									<td></td>
+								{{else if eq $cell.Type 2}}
 									<td class="modified"><span class="removed-code">{{.LeftCell}}</span> <span class="added-code">{{.RightCell}}</span></td>
 								{{else if eq $cell.Type 3}}
 									<td class="added"><span class="added-code">{{.LeftCell}}</span></td>
```

Would stop the panic but I'm not sure if there is a deeper bug here.

**Comment by silverwind** [comment]
Here you go:

https://try.gitea.io/silverwind/symlink-test/commit/46c2ca254f58499afea56cbd16912c3523cc8f00

Essentially, it is a CSV where column names and content have changed, initially it was:

```csv
a,b,c
1,2,3
```

Then it was update to:

```csv
d,e,f
4,5,6
```

**Comment by richmahn** [comment]
Is anyone working on this one? Having got quite familiar with the CSV module I'll look.

**Comment by richmahn** [comment]
Maybe what @zeripath wrote above will make it work, but the error one gets from switching the column name is:

An error has occurred:

```
template: repo/diff/csv_diff:15:21: executing "repo/diff/csv_diff" at <$cell.Type>: nil pointer evaluating *gitdiff.TableDiffCell.Type
```

So maybe needs to bve hadnled in this call to csv_diff in the template

**Comment by richmahn** [comment]
Yes, what @zeripath wrote above removes the error, but then you don't see what it was changed FROM....I assume we need to show two header rows or something to see the change.

**Comment by zeripath** [comment]
I suspect the diff may need a close looking at.

**Comment by silverwind** [comment]
Just did a test with the patch above, did not help, still failing with the same error.

**Comment by zeripath** [comment]
@silverwind can you chat to me on discord - it might be easiest to just give me a copy of the problematic CSVs in question privately so we can just get this sorted.

@KN4CK3R do you have any ideas?

**Comment by silverwind** [comment]
@zeripath did you see https://github.com/go-gitea/gitea/issues/16837#issuecomment-913399495?

File is also on try: https://try.gitea.io/silverwind/symlink-test/src/branch/master/test.csv.

**Comment by richmahn** [comment]
Found the bug:

https://github.com/go-gitea/gitea/blob/0c6137617fbf41ee6cb315f96a2acc2dd91203e8/services/gitdiff/csv.go#L184
https://github.com/go-gitea/gitea/blob/0c6137617fbf41ee6cb315f96a2acc2dd91203e8/services/gitdiff/csv.go#L219

Going through the unmapped b row (the new content) clobbers the old contents cell items. The cells should be shifted right and then this unmapped b cell can be inserted. Making fix.

**Comment by richmahn** [comment]
@zeripath @silverwind and anyone else: for review ^^^ #17018
