### ISSUE TITLE
Changing labels/milestones during editing issue resets text

### ISSUE THREAD

**Issue by MGChecker** [go-gitea/gitea#16846]
I understand why this happens, but if one does this accidentally after writing a lot of text, it can be quite frustrating.

- Gitea version (or commit ref): 1.14.5
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No

**Comment by silverwind** [comment]
Comment text should be preserved in localStorage during page reloads. It could probably be keyed off the URL.

**Comment by jolheiser** [comment]
Duplicate of #8342
