### ISSUE TITLE
Gitea does not implement proper OIDC

### ISSUE THREAD

**Issue by Reinitialized** [go-gitea/gitea#16852]
- Gitea version (or commit ref): 1.15.0

## Description
Based on what I've recently learned about OIDC, I do not believe Gitea implements this protocol correctly, specifically when it comes to linking an non-existent Gitea user. Gitea allows the end user to change a variety of identity related options, violating the intent of SSO, such as:

- Upon registration of a Gitea account, allowing the end user to change their username and email
- Within Account Settings, allowing the user to change their email and password
- Allowing end users to log in locally instead of through the OIDC provider

Gitea is an amazing product which I enjoy using, but as I grow my infrastructure and eventually business/community, the ability to manage these settings in a centralized system without having to implement workarounds such as LDAP is a crucial component to using this product. I hope this can be addressed within a timely manner.
## Screenshots

Example of being able to change password/email on "non-local" account
![image](https://user-images.githubusercontent.com/20674500/131195190-47902c35-cab1-4b3b-a2ce-afbc0b1f5ff1.png)
![image](https://user-images.githubusercontent.com/20674500/131195232-2cc593ba-808a-432f-96bc-2d66eb99da73.png)

**Comment by sanderfoobar** [comment]
> Upon registration of a Gitea account, allowing the end user to change their username and email

Set this to `true` and it will auto register

```text
[oauth2_client]
ENABLE_AUTO_REGISTRATION = true
```

> Allowing end users to log in locally instead of through the OIDC provider

Set this to `false` if you want to only include users from the OIDC to register 

```text
[service]
DISABLE_REGISTRATION              = false
```

> Within Account Settings, allowing the user to change their email and password

Yep, this is weird in the context of OIDC

**Comment by zeripath** [comment]
Disabling the changing of username has another issue request.

**Comment by Reinitialized** [comment]
> Set this to `true` and it will auto register after redirecting from OIDC provider

Don't know how I missed this, but it solves one of the problems. Thanks!

> Disabling the changing of username has another issue request.

Looking into account settings, I don't see an option to change username, and with the above change Usernames are no longer an issue it seems. Email and passwords are still a problem, however. I know for LDAP passwords cannot be changed, but emails still can.

**Comment by fuomag9** [comment]
> > Set this to `true` and it will auto register after redirecting from OIDC provider
> 
> Don't know how I missed this, but it solves one of the problems. Thanks!
> 
> > Disabling the changing of username has another issue request.
> 
> Looking into account settings, I don't see an option to change username, and with the above change Usernames are no longer an issue it seems. Email and passwords are still a problem, however. I know for LDAP passwords cannot be changed, but emails still can.

the `ENABLE_AUTO_REGISTRATION` variable was missing from the default config as of today! I'd not have found it if it weren't for this issue

**Comment by lunny** [comment]
> 

It's in the documentation and the example ini file. The default config is a minimum configuration file.

**Comment by kdumontnu** [comment]
I believe these issues are now all closed with https://github.com/go-gitea/gitea/pull/31535 and also superseded by this tracking issue https://github.com/go-gitea/gitea/issues/23794

OIDC was not necessarily implemented incorrectly, but it was configured as an "external auth provider" (eg. an alternative login) instead of Single Sign-On (SSO) / Single Identity Provider. These options should now be supported in config settings.

**Comment by Reinitialized** [comment]
Sweet! Love seeing how far Gitea has come since I've opened the few issues I have. Thanks for everything you guys do!
