### ISSUE TITLE
Receive emails for own posts

### ISSUE THREAD

**Issue by confusedsushi** [go-gitea/gitea#16855]
It would be great to have the possibility to configure reception of emails of my own posts. Ideally it is configurable on a per user basis.

Background: When someone is keeping track of an issue in his emails, it is very helpful to have his own posts among these emails.

**Comment by lunny** [comment]
This has been removed at some PR. But as a per user configuration is reasonable.

**Comment by tyroneyeh** [comment]
Maybe #20179 solved this issue, but waiting for review
