### ISSUE TITLE
Theme proposal: GitHub

### ISSUE THREAD

**Issue by pat-s** [go-gitea/gitea#16867]
I would like to propose the inclusion of a **third built-in** theme "GitHub" which aims to mimic the appearance of the GitHub.

I've created this [theme](https://github.com/pat-s/gitea-github-theme) recently for my own purposes (happy to take update recommendations) but could image that it could fit into the current built-in theme line-up quite nicely.

## Preview

To preview the theme you can either follow the [instructions for custom themes](https://docs.gitea.io/en-us/customizing-gitea/#customizing-the-look-of-gitea) (updated today) or use the Chrome extension ["Stylus"](https://chrome.google.com/webstore/detail/stylus/clngdbkpkpeebahjckkjfobafhncgmne/related).

The latter is quicker and the only way if you do not have admin access to your own Gitea instance.
1. Create a stylus theme for a Gitea site (e.g. gitea.com)
2. Copy the contents of https://github.com/pat-s/gitea-github-theme/blob/main/theme-github.css and you should be able to toggle the theme on/off

## Screenshots

|                           |                           |
| :-----------------------: | :-----------------------: |
| ![screenshot1](https://user-images.githubusercontent.com/8430564/131262792-028aa289-0978-4c16-8ebc-a1b2e6077ce4.png)| ![screenshot2](https://user-images.githubusercontent.com/8430564/131262798-8233ba1f-ab7b-4e28-9d1c-88bf90ddea46.png)

**Comment by lunny** [comment]
I think we should keep less themes with Gitea and build a theme site to allow user install themes.
