### ISSUE TITLE
Add OAuth2 Sign out URL 

### ISSUE THREAD

**Issue by yoyoyonas** [go-gitea/gitea#16869]
- Gitea version (or commit ref): 1.15.0
- Git version: 2.25.1
- Operating system: Ubuntu 20.04
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No

## Description

When Gitea is used as an OAuth2 client, the "Sign out" button in Gitea signs out only from Gitea, not from the authentification provider. However, the user may expect to be logged out also from the OpenID Connect provider, which creates a small security flaw.  
I propose to add the option to set a sign out URL parameter for every OAuth2 provider.

When using e.g. [Keycloak](https://github.com/keycloak/keycloak/) as a provider, this typically would be something like `https://sso.example.com/auth/realms/master/protocol/openid-connect/logout?redirect_uri=https%3A%2F%2Fgit.example.com%2F`.

(Other OpenID Connect clients provide such options, see e.g. [Nextcloud](https://github.com/pulsejet/nextcloud-oidc-login#usage-with-keycloak) with `oidc_login_logout_url`.)

**Comment by lunny** [comment]
And we also needs an option with `logout the provider when logout Gitea as well`.

**Comment by yoyoyonas** [comment]
I realized I created a duplicate of #14270 :/
