### ISSUE TITLE
How do I close the annoying pop-up window?

### ISSUE THREAD

**Issue by aszswaz** [go-gitea/gitea#16861]
![gitea](https://user-images.githubusercontent.com/57160610/131248306-6e229553-0470-4c6d-a67c-88e697acc8c9.png)

The content of this pop-up window is:
Leave this site?
The system may not save your changes.

This pop-up window appears when operating the warehouse settings.
As long as I access via https, this pop-up window will appear, but http does not.

My browser is chromium, and this pop-up window will appear in the settings of the operating warehouse. But there is no such pop-up window in Firefox.

How can I prevent pop-ups from appearing?

**Comment by lunny** [comment]
Are you editing something when you want to leave the page?

**Comment by zeripath** [comment]
It is probably related to autofill of fields. We may need to change their names to discourage chrome etc from guessing that what they should hold

**Comment by aszswaz** [comment]
> 当您想离开页面时，您是否正在编辑某些内容？

I did not edit any content. And I hope that no matter whether I have edit settings or not, I don’t want this pop-up window to appear.
 Because even the currently edited settings are not saved, it does not matter if they are lost. 
I plan to use gitea to build a public and private website. This pop-up will frequently disturb users.

**Comment by aszswaz** [comment]
> 当您想离开页面时，您是否正在编辑部分内容？

I did not edit any content. And I hope that no matter whether I have edit settings or not, I don’t want this pop-up window to appear.
The currently edited settings are not saved, and it does not matter if they are lost.
I plan to use gitea to build a public personal website. This pop-up window may frequently disturb users.

**Comment by aszswaz** [comment]
> It is probably related to autofill of fields. We may need to change their names to discourage chrome etc from guessing that what they should hold

In other words, is it currently unable to be resolved by configuring the app.ini file?
I have been using it privately before, only using the HTTP protocol to interact with gitea, and this pop-up window has never appeared.
Migrating to the server and using the HTTPS protocol to interact with gitea, this pop-up window appeared.
I thought that gitea's javascript has special actions for access via domain names and HTTPS.

**Comment by zeripath** [comment]
Just press the leave button each time.

As I say it's not coming from gitea directly but from Chrome.

Chrome is guessing that you want these values filled and is then detecting a changed form. 

There will be a way of telling Chrome that the name field here is not supposed to be your name but off the top of my head I don't know how.

**Comment by aszswaz** [comment]
> 每次只需按一下离开按钮。
> 
> 正如我所说，它不是直接来自 gitea，而是来自 Chrome。
> 
> Chrome 正在猜测您希望填充这些值，然后检测到更改的表单。
> 
> 有一种方法可以告诉 Chrome，这里的名称字段不应该是你的名字，但我不知道该怎么做。

I want to replace the code of the gitea page without moving the restful api of the gitea server. What do I need to do?

**Comment by aszswaz** [comment]
> 每次点击一下鼠标。
> 
> 正如我所说，它不是直接来自 gitea，而是来自 Chrome。
> 
> Chrome 正在浏览您希望更新这些值，然后检测到更改的表单。
> 
> 有一种方法可以告诉 Chrome，这里的名称字段不应该是你的名字，但我不知道自己做。

I want to replace the code of the gitea page without changing the restful api of the gitea server. What do I need to do?

**Comment by aszswaz** [comment]
> Just press the leave button each time.
> 
> As I say it's not coming from gitea directly but from Chrome.
> 
> Chrome is guessing that you want these values filled and is then detecting a changed form.
> 
> There will be a way of telling Chrome that the name field here is not supposed to be your name but off the top of my head I don't know how.

I am not familiar with GO. I want to replace the code of the gitea page without changing the restful api of the gitea server. What do I need to do?

**Comment by aszswaz** [comment]
> > Just press the leave button each time.
> > As I say it's not coming from gitea directly but from Chrome.
> > Chrome is guessing that you want these values filled and is then detecting a changed form.
> > There will be a way of telling Chrome that the name field here is not supposed to be your name but off the top of my head I don't know how.
> 
> I am not familiar with GO. I want to replace the code of the gitea page without changing the restful api of the gitea server. What do I need to do?

**Comment by aszswaz** [comment]
> Just press the leave button each time.
> 
> As I say it's not coming from gitea directly but from Chrome.
> 
> Chrome is guessing that you want these values filled and is then detecting a changed form.
> 
> There will be a way of telling Chrome that the name field here is not supposed to be your name but off the top of my head I don't know how.

Instead of using the form, changing to javascript to listen to the click event of the button should be able to avoid this problem.
I am not familiar with GO. I want to replace the code of the gitea page without changing the restful api of the gitea server. What do I need to do?

**Comment by zeripath** [comment]
Let me attempt to be a little clearer.

This is coming directly from your browser. Your browser is telling you that the form is being left unsubmitted whilst there are changes - changes it itself made without being asked to do so, because it has matched the form fields with data it wants to change.

Javascript will not solve or improve this.

The solution is to stop the browser from auto-filling the fields by changing the form field names, roles or otherwise.

**Comment by wxiaoguang** [comment]
I meet this problem too.  @zeripath is right. 

The key point is that gitea has the prompt if a user try to leave a page but some form inputs was changed. Chrom auto-fills many input fields.

I think we can have a quick fix to keep things clear and  satisfy users:

Let gitea only detect form changes after 5 seconds. Chrome will auto-fill inputs in short time. After that time, the changes should belong to users.

If you feel OK, I can propose a PR.

**Comment by zeripath** [comment]
I've done two things:

1. Mark the password field ignore-dirty on the user setting pages.
2. Mark the mirror address field autocomplete=off on the repository setting pages.

**Comment by aszswaz** [comment]
> Let me attempt to be a little clearer.
> 
> This is coming directly from your browser. Your browser is telling you that the form is being left unsubmitted whilst there are changes - changes it itself made without being asked to do so, because it has matched the form fields with data it wants to change.
> 
> Javascript will not solve or improve this.
> 
> The solution is to stop the browser from auto-filling the fields by changing the form field names, roles or otherwise.

Well, what I want to say is not js to operate the form, but to implement the form-like function through js, such as this:

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Hello World</title>
</head>
<body>
<div class="input" contenteditable="true">please input.</div>

<script type="text/javascript">
    function inputDemo() {
        let inputDiv = document.getElementsByClassName("input")[0]
        alert(inputDiv.innerHTML)
    }
</script>

<button onclick="inputDemo()">send</button>
</body>
</html>
```

Will this method be detected by chrome?

**Comment by wxiaoguang** [comment]
I can get your point, but I think it's not reasonable to introduce the complex mechanism.

You see, if we draw a snake and find what we draw has some flaws, adding feet to the snake doesn't make it more like a snake. Instead we should perfect the picture we drawn.

**Comment by zeripath** [comment]
The associated pr should solve the issue.

**Comment by wxiaoguang** [comment]
It seems that `autocomplete="off"` doesn't help ...... Maybe my propose works.

> Let gitea only detect form changes after 5 (or 10) seconds. Chrome will auto-fill inputs in short time. After that time, the changes should belong to users.

# Login source

![image](https://user-images.githubusercontent.com/2114189/134796054-a419e62a-5d25-43c5-9145-e0778c776d19.png)

# Repo setting

![image](https://user-images.githubusercontent.com/2114189/134796024-01d66db4-e5df-44a5-aa54-082b553bbbcd.png)

**Comment by wxiaoguang** [comment]
Another trial: https://github.com/go-gitea/gitea/pull/17291
