### ISSUE TITLE
Missing links in PR after comments

### ISSUE THREAD

**Issue by melmus** [go-gitea/gitea#16877]
- Gitea version (or commit ref): v1.15.0
- Git version: 2.30.2
- Operating system: Ubuntu 18.04.4 LTS
   Gitea running in docker
  
  
  
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
- Log gist:

## Description

After i create PR and our team comments or review PR, message "user commented on this pull request" comes to email, but i do not see link to PR in message. On the screenshots you can see an example of this problem.

## Screenshots
![recieve_message_from_pr](https://user-images.githubusercontent.com/15018126/131347043-4ce201d4-df02-4c34-ae4c-3cc05948f689.png)

![receive_email2](https://user-images.githubusercontent.com/15018126/131349251-0d455251-fa03-47db-a74c-31a792cc4c01.png)

**Comment by prasadkatti** [comment]
Hi. I would like to work on fixing this issue. I have already done some triaging. The issue occurs because the template rendering fails with this error - 

> ...vices/mailer/mail.go:301:composeIssueCommentMessages() [E] ExecuteTemplate [issue/default/body]: template: issue/default:65:10: executing "issue/default" at <.i18n.Tr>: can't evaluate field i18n in type *models.Comment

**Comment by zeripath** [comment]
change line 65 in templates/mail/issue/default.tmpl from:

https://github.com/go-gitea/gitea/blob/5a73153493332a110fb9c3ac3f716972f6a2390c/templates/mail/issue/default.tmpl#L65

to:
```handlebars
			{{$.i18n.Tr "mail.issue.in_tree_path" .TreePath}}
```

This bug is therefore a regression of #16200

**Comment by prasadkatti** [comment]
@zeripath - Yes, thanks. The `i18n` variable is defined in the outer scope and needs to be referenced using `$`.

**Comment by 6543** [comment]
sorry missed that - thanks for the fix
