### ISSUE TITLE
Ability to edit user profile picture from Site Admin section

### ISSUE THREAD

**Issue by SonGokussj4** [go-gitea/gitea#16876]
- Gitea version (or commit ref): 1.15.0
- Operating system: Docker
  
  
  

## Description

...

I didn't find this issue so I'm opening one. 

At our company users are logging in through LDAP. But there is no picture loaded and I, as root/admin, can't edit profile picture of those people which refuse to upload it themselves. Or upload something improper...

As I can edit their names, mail, etc... I would like to edit their profile picture.

Edit: Found a gogs issue: https://github.com/gogs/gogs/issues/3324

**Comment by kemzeb** [comment]
Closing as this feature has been implemented in #17661 and from manually testing on my latest main branch (840ad7eefe2b49ab453b9a89b153a264a8c9f8a2) I am able change user avatars as an admin.
