### ISSUE TITLE
Special characters in Git (Project) Wiki Title

### ISSUE THREAD

**Issue by wxrl** [go-gitea/gitea#16873]
Hello, I accidentally used some special characters (`/  \  '`) in the title of a newly generated wiki page and saved it. After saving, it immediately displayed "404 page not found", which is fine (I can start a new page without these special characters). 

**But** the page with the special characters in its title is still listed in the "Pages" (./wiki/_pages) list as well as in the Drop-Down List which is shown in every page under this Wiki, with the special characters in the page title. (But if I click it, it shows "404 page not found" of course)

**Any idea that I can delete the page with the special characters in its title completely?**

Also would like to request add the blocker functionality to stop saving when there's any reason that would affect the access of the page after saving (special character in the title apparently is one of these reasons.)
 
My Config: **Gitea 1.15.0 Binary with NGINX 1.18, and MariaDB 10.5** on Debian 11 x64

**Comment by zeripath** [comment]
The wiki is a git repo so you should be able to just clone and push it back it up after having changed the name of the file.

**Comment by wxrl** [comment]
> 
> 
> The wiki is a git repo so you should be able to just clone and push it back it up after having changed the name of the file.

Thanks. Done. Closing.
