### ISSUE TITLE
how restore my gitea repositories

### ISSUE THREAD

**Issue by ssmns** [go-gitea/gitea#16875]
My MySQL database was corrupted. I haven't any backup, so in this situation how can restore my repositories? I have all my directories and configurations.

**Comment by lunny** [comment]
You can use adopt feature on admin panel. Only git data will be taken back. But your issues and PRs and other things stored on database will not be taken back.

**Comment by wxiaoguang** [comment]
@ssmns 

To be honest, in most cases, a corrupted MySQL database can be mostly recovered.

As lunny said, without database recovery, you only have your git repository data. So if the database wasn't deleted and just corrupted, it's better to ask help from a DBA.
