### ISSUE TITLE
Intermittent wrong comment count on PRs

### ISSUE THREAD

**Issue by noerw** [go-gitea/gitea#16901]
- Gitea version (or commit ref): 1.16.0+dev-109-gd17f555fe
- Git version: ?
- Operating system: linux
  
  
  
- Database (use `[x]`):

  - [x] MySQL
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL): https://gitea.com/gitea/tea/pulls/391, https://gitea.com/gitea/tea/pulls
- Log gist:

## Description
A PR is listed as having comments, while none show up in the PR detail view (see gitea.com example above.)

This may be about approving reviews, and is probably caused by a fairly recent change, as [an older PR](https://gitea.com/gitea/tea/pulls/388) has an approval too, but does not list additional comments that are not visible on the PR detail page.

The API also returns a higher comment count, while not returning any comments

## Screenshots
![Screenshot_20210831_094952](https://user-images.githubusercontent.com/7880552/131464189-dd79b707-e266-4aa8-b5e2-46f6d0f15ee4.png)
![Screenshot_20210831_095048](https://user-images.githubusercontent.com/7880552/131464282-bcaa402c-08ca-4c37-80be-62645e789a29.png)

**Comment by delvh** [comment]
Could it be that `approval` counts as a comment, even if it does not have any comment associated?

**Comment by noerw** [comment]
hmm, now the comment count on that specific issue is correct.. 🤔

**Comment by noerw** [comment]
This is a regression of #16075:
It adds reviews to the comment counter on a PR, but
- this does not check if the review has a comment body
- this deviates from the logic of [CheckRepoStats()](https://github.com/go-gitea/gitea/blob/7bcbdd07072d375eb9f24a64a047879ae2aa7aed/models/repo.go#L1917-L1921), which runs via cronjob and corrects the counter again

**Comment by noerw** [comment]
github does the following:
- in the UI, they count any comment (including code comments) that has a body.
- the `/pulls/{index}/comments` API endpoint only returns non-review comments
- the `/pulls/{index}` endpoint returns two separate counters `comments` + `review_comments`
this feels like a reasonable solution, that could even be backported

**Comment by lunny** [comment]
It seems now it's correct. I think maybe we could close this one and remove it from v1.15.7 .

**Comment by noerw** [comment]
No this bug is not fixed yet, just reproduced on 1.15.6 and gitea.com.
I'm currently short on time, but I'll try to come up with a fix in the coming days

**Comment by lunny** [comment]
If we follow Github's method, we need a new number column but I think it's difficult to add a new column in a stable version. Maybe we can do it in v1.16 if possible. I'll move this to v1.15.8

**Comment by lunny** [comment]
> * https://gitea.com/gitea/tea/pulls

Could you have time to confirm if it's gone?

**Comment by noerw** [comment]
fyi: bug is still present.
@lunny I'll submit a bugfix for 1.15.10 that reverts [this two line change of #16075](https://github.com/go-gitea/gitea/pull/16075/files#diff-78c2c18ca14c9554e7f5a73716a4c65b659d751ea76dfbc57d87c68d91a0f37fR765-R766) so we at least have consistent state back.

In a followup for 1.16 or 1.17 we can aim at implementing PR comment counts similar to github with separate counters.
