### ISSUE TITLE
Labels gone in v1.15.0 (upgraded from v1.14.x)

### ISSUE THREAD

**Issue by prologic** [go-gitea/gitea#16908]
- Gitea version (or commit ref): 1.15.0
- Git version: 2.30.1
- Operating system: macOS

Using upstream Docker image: `gitea/gitea:1.15.0`

I am running it like so:

```#!sh
docker stack deploy -c gitea.yml gitea
```'

Where `gitea.yml` is:

```#!yaml
---
version: "3.8"

services:
  server:
    image: gitea/gitea:1.15.0
    environment:
      - USER_UID=1000
      - USER_GID=1000
    ports:
      - "<redacted>:22/tcp"
    volumes:
      - gitea:/data
    networks:
      - mail
      - traefik
    deploy:
      placement:
        constraints:
          - "node.hostname == <redacted>"
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik"
        - "traefik.http.services.gitea.loadbalancer.server.port=<redacted>"
        - "traefik.http.routers.gitea.rule=Host(`<redacted>`)"
        - "traefik.http.routers.gitea.priority=2"
      restart_policy:
        condition: on-failure
      replicas: 1

networks:
  mail:
    external: true
  traefik:
    external: true

volumes:
  gitea:
    driver: local
```

On a Docker Swarm cluster.

- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] N/A (_I would have to reproduce a v1.14.x -> v1.15.0 upgrade_)
- Log gist: I _think_ this _might_ be a data migration bug in the database. What logs do you need? They are likely too old, I didn't notice until weeks later :/

## Description

As per the title. Labels on new projects seem to be gone.
I'm not sure how to re-create them either.

## Screenshots

<img width="1281" alt="Screen Shot 2021-09-01 at 13 41 37" src="https://user-images.githubusercontent.com/1290234/131608142-23a72e56-f326-44d0-a800-f98d22b7c826.png">

**Comment by prologic** [comment]
Although now that I said I wasn't sure how to recreate labels for my project, I poked around and I can see how to do it now :)

<img width="1282" alt="Screen Shot 2021-09-01 at 13 42 10" src="https://user-images.githubusercontent.com/1290234/131608207-a0fdf818-b800-42ea-ae88-0a338c49c5cf.png">

However I _still_ this this is valid as I don't recall in v1.14.x that new projects has no label sets by default. Did this behaviour change or is this a bug?

**Comment by jolheiser** [comment]
New projects don't have label sets unless you choose to initialize the project with a label set.

![Screenshot from 2021-08-31 22-49-06](https://user-images.githubusercontent.com/42128690/131608720-9ac33970-9125-4ae0-ba3a-056104d2aa5f.png)

**Comment by prologic** [comment]
> New projects don't have label sets unless you choose to initialize the project with a label set.

Did this change form v1.14.x -> v1.15.x? Or am I dreaming? 😀

**Comment by zeripath** [comment]
don't think so.
