### ISSUE TITLE
Create repo page automatically scrolls down

### ISSUE THREAD

**Issue by axifive** [go-gitea/gitea#16937]
- Gitea version (or commit ref): 1.16.0+dev-195-gb6c752e91
- Git version: -
- Operating system: -
- Browser: Desktop Opera/Chrome, Chrome Mobile
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes https://try.gitea.io/repo/create
  - [ ] No
- Log gist:

## Description
Noticed that when opening the repo create page it quickly shows breaking layout and then automatically scrolls down.

## Screenshots

![Untitled_screenvideo (1)](https://user-images.githubusercontent.com/844963/131940730-14cac978-e948-4322-942b-c5346b4d2867.gif)

**Comment by wxiaoguang** [comment]
The bug is more obvious in Chrome.

Some guess:

The page layout may be wrong (eg: tag mismatching), or the HTML output is not smooth.

So the rendered page may appear in some intermediate state (see the screen shot), then page height is very large.

Then when the page is completely rendered, Chrome tries to adjust the scrolling position by percentage. Then what you see.



![image](https://user-images.githubusercontent.com/2114189/131942816-f0ed4d82-5f88-4064-823c-c492c0a3056d.png)

**Comment by silverwind** [comment]
Is there some reliable way to get the partial rendered state? I tried with DevTools network throttling but it switches to regular layout too fast for me to pause the page.

**Comment by axifive** [comment]
@silverwind Try disable
```css.ui.grid>.column:only-child, .ui.grid>.row>.column:only-child {
    /* width: 100%; */
}```

**Comment by wxiaoguang** [comment]
Agree axifive.

The problem is caused by mis-used fomatic layout.

Old code:

```
<div class="ui middle very relaxed page grid">
   <div class="column">
```

The inner `column` has a `width: 6.25%` by `.ui.grid>.column:not(.row),.ui.grid>.row>.column {`

I think the correct layout should be something like:

```
<div class="ui middle very relaxed page one column grid">
   <div class="column">
```

With `one column`, the inside `column` has width 100%.

**Comment by silverwind** [comment]
Fomantic's grid system is incredibly hacky (negative margins everywhere and the width issue above during page load), I hope we can get rid of it eventually, but I'd be okay with doing a short-term fix now.

**Comment by wxiaoguang** [comment]
Yes, I am the same feeling. Fomantic was born very early, so what it did was already the best it could do.

Other pages may not be affected because only this page has a very long list.
