### ISSUE TITLE
Docker image `gitea/gitea:1` regressed from 1.15.0 to 1.14.7

### ISSUE THREAD

**Issue by frebib** [go-gitea/gitea#16931]
https://hub.docker.com/layers/gitea/gitea/1/images/sha256-f8b9adeb25bfec817008d07b0eb7b92740a48e2b51834fc8c6ff86a0943afc95?context=explore

Todays release caused gitea to fail to start and spin 
```
Downgrading database version from '189' to '178' is not supported and may result in loss of data integrity.
If you really know what you're doing, execute `UPDATE version SET version=178 WHERE id=1;`
Received signal 15; terminating.
```

I would assume that the `1` tag is only "latest stable" releases, with monotonic versioning, and any additional LTS releases don't get pushed to that tag. Doing that doesn't break the assumption that pulling every `1` tagged image should work. I assume that the same release procedure is used for both "stable" and "lts" releases, hence the overwriting of the `1` tag.
If there are no worries, can I ask that the `1` tag is restored to 1.15.0 please?

**Comment by razinj** [comment]
Can confirm the issue, not sure what to do about this.

Any help/guidance from maintainers would be awesome.

Thanks.

**Comment by techknowlogick** [comment]
It's due to how CI tags images. 1.15.1 was just tagged/pushed, and will write the expected version to :1

If you wait 30 minutes the CI will put the expected image in place. We very rarely tag a version below current stable, and when we do we tag a newer one so that the CI will resolve the issue.
