### ISSUE TITLE
404 when accessing files from a commit

### ISSUE THREAD

**Issue by ramasoft-dv** [go-gitea/gitea#16946]
- Gitea version (or commit ref): 1.15.1
- Git version: 2.30.0
- Operating system: Windows 10
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [X] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X] No

## Description
When trying to access to a file from a commit (and actually all files), I have a 404:
"404 - File or directory not found.
The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable."
As an exemple, in try.gitea.io, if you access to the following file, it's ok:
https://try.gitea.io/xueyoo/operator/src/commit/b39de50c592ee57b2b0aaf5e4c927063af02315c/docs/crd.adoc
But, in our server it would return a 404.

We are able to see folders, so if I take the same exemple, this works:
https://try.gitea.io/xueyoo/operator/src/commit/b39de50c592ee57b2b0aaf5e4c927063af02315c/docs/

We have moved the files/folders. Before the gitea service and data were stored on G:\, now they are at F:\.
We've changed in the app.settings the [repository].[ROOT] path and actually all occurences of G:\ in the settings file.
Everything seems to work (push, pulls, ..) except the issue described.

Which logs do you need ?
I tried Trace levels to find some useful info, but actually couldn't find anything interesting in the logs.

Thank you for your help.

**Comment by ramasoft-dv** [comment]
It seems that it's related to the url rewrite, because locally in the server it's ok:
server:port/src/commit/guid/file.txt
but, with url rewrite and https on:
https://git.ourdomain.com/src/commit/guid/file.txt
, it's not ok.

**Comment by ramasoft-dv** [comment]
Nothing is wrong with the url rewrite.
It seems that accessing a file from a commit when an url rewrite is done, is not accepted. But I don't have a clue why.

**Comment by zeripath** [comment]
remember 404s can be due to permissions failures - (we have to do it that way to avoid revealing leaking information about whether a repo or particular file exists).

Is it possible that your rewrite is not passing the correct session information?

**Comment by zeripath** [comment]
Could you try with an absolutely public path?

**Comment by ramasoft-dv** [comment]
> remember 404s can be due to permissions failures - (we have to do it that way to avoid revealing leaking information about whether a repo or particular file exists).
> 
> Is it possible that your rewrite is not passing the correct session information?

That would be strange, we would have more issues. So I don't think.

**Comment by ramasoft-dv** [comment]
> Could you try with an absolutely public path?

Can you provide me an exemple based on try.gitea.io ?
Do you mean:
ourGiteaServerDomain.com/Orga/Repository/src/branch/develop/OneFileInRootDir.txt
If yes, then it's working.
The issue happen only when consulting files from commits.
So, an exemple:
ourGiteaServerDomain.com/Orga/Repository/src/commit/6f231b87aba3c2678ce3bf28636e5e48302004cc/OneFileInRootDir.txt

**Comment by ramasoft-dv** [comment]
Any help would be great.
Is there a way for me to debug and see where it goes wrong ?

**Comment by ramasoft-dv** [comment]
I found the reason.
We use IIS to tunnel gitea server. And the web instance had some file extension filters, which denied the access to those file.
Locally, we were contacting directly the gitea server, so no problem. But throught internet, it uses our iis server and then we had 404.
