### ISSUE TITLE
Drone webhooks broken after uprading to 1.1.1

### ISSUE THREAD

**Issue by jhasse** [go-gitea/gitea#1695]
- Gitea version (or commit ref): 1.1.1
- Git version: 2.7.4
- Operating system: Linux 4.4.0-71-generic
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist: Don't know what logs could be relevant.

## Description

After upgrading from 1.0.2 to 1.1.1, all my Drone webhooks no longer work. I can manually trigger them, which works, but push events fail and the time shows as `1970-01-01 01:00:00 CET`.

## Screenshots

![webhook](https://cloud.githubusercontent.com/assets/80071/25808189/95d91820-3409-11e7-8413-4aa6bf6cefd9.png)

**Comment by jhasse** [comment]
Maybe related: https://github.com/gogits/gogs/issues/4467

Note that after clicking "Test Delivery" the correct date is shown.

**Comment by lunny** [comment]
Could you test v1.1.4 fix that? I cannot reproduce this on my v1.1.4 instance.

**Comment by jhasse** [comment]
Yes, still happens with v1.1.4.

I'm using nginx for both Gitea and Drone btw.

**Comment by olymk2** [comment]
Probably related to this bug ? #2480

**Comment by jcgruenhage** [comment]
@olymk2 I doubt it, since #2480 is not present on 1.1.4 and before.

**Comment by jhasse** [comment]
I've updated to 1.2.3 and this seems to be fixed. No idea what was the cause though.
