### ISSUE TITLE
json.Unmarshal errors in gitea log

### ISSUE THREAD

**Issue by echodreamz** [go-gitea/gitea#16959]
- Gitea version (or commit ref): 1.15.0
- Git version: 2.33.0
- Operating system: Ubuntu 20.0.4 - Gitea running as a systemd service, downloaded directly from the releases page
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x ] No
- Log gist:
`2021/09/05 08:36:38 .../templates/helper.go:849:ActionContent2Commits() [E] json.Unmarshal:
	{"Commits":[{"Sha1":"d5d05abd8ada7e8c3318433288915ff7a6acbee3","Message":"Updates
	
	- Fixed flag offsets on fuzzy checks to make sure each fuzzy check had a unique `flag`
	- Metadata exporter adjusted to also report trusted messages
	","AuthorEmail":"REMOVED@REMOVED","AuthorName":"REMOVED","CommitterEmail":"REMOVED@REMOVED","CommitterName":"REMOVED","Timestamp":"2021-08-25T02:57:47-05:00"}],"HeadCommit":{"Sha1":"d5d05abd8ada7e8c3318433288915ff7a6acbee3","Message":"Updates
	
	- Fixed flag offsets on fuzzy checks to make sure each fuzzy check had a unique flag
	- Metadata exporter adjusted to also report trusted messages
	","AuthorEmail":"REMOVED@REMOVED.com","AuthorName":"REMOVED","CommitterEmail":"REMOVED@REMOVED.com","CommitterName":"REMOVED","Timestamp":"2021-08-25T02:57:47-05:00"},"CompareURL":"rspamd-config/compare/e040728619554f1e3cbcd6fbeedd9de8d8399af8...d5d05abd8ada7e8c3318433288915ff7a6acbee3"}
	ERROR: repository.PushCommits.Commits: []*repository.PushCommit: repository.PushCommit.Message: ReadString: invalid control character found: 10, error found in #10 byte of ...|Message":"Updates
	
	-|..., bigger context ...|05abd8ada7e8c3318433288915ff7a6acbee3","Message":"Updates
`

## Description
The above errors started in our logs after the v1.15.0 update

**Comment by echodreamz** [comment]
Was a DB issue, fixed up.

**Comment by zeripath** [comment]
There's an apparent issue with the dumping of this field with poor escaping of strings.

This makes me highly concerned that the dump is no longer handling cross db dumping correctly despite it working on 1.14.0-1.14.2.

**Comment by wxiaoguang** [comment]
Since 1.16 is coming, maybe we can close this one to see if there is new problem of database dumping.

Feel free to provide new clues to reopen this issue.

**Comment by zeripath** [comment]
No it's still broken.

Cross DB Dump is broken since 1.14.3 as it appears that the fixes I put in xorm to make it work were reverted.

We need to put some proper tests for dump into Gitea and we need to re-fix xorm.

**Comment by wxiaoguang** [comment]
@lunny how do you think?

**Comment by lunny** [comment]
> No it's still broken.
> 
> Cross DB Dump is broken since 1.14.3 as it appears that the fixes I put in xorm to make it work were reverted.
> 
> We need to put some proper tests for dump into Gitea and we need to re-fix xorm.

I don't know if the dump in recent xorm is right. But the tests in xorm PASS.
