### ISSUE TITLE
[Feature Request] can organization have a README.md instead of plain text description?

### ISSUE THREAD

**Issue by wameup** [go-gitea/gitea#16965]
This is a feature suggestion. Sometimes organizations need more expressive description instead of plain text. 

For example, 
- There could be hierarchical organizations such as 'company', 'company-admin', 'company-admin-personnel', or 'top-project', 'sub-project1', 'sub-project2'. ==> It's nice to have some hyperlinks in each organization's description, such that I can navigate between the hierarchy. 
- I want to copy a list of all repository names in an organization, so that I can clone them all in one command.
- It's nice for organizations to have a 'homepage', just like README.md file in repositories. 

Anyway, if organizations have README.md files just like repositories do, it could be much more expressive and useful.

**Comment by wameup** [comment]
great!

**Comment by delvh** [comment]
(However, the mentioned PR only implements this for users, not for orgs which this issue seems to be concerned with)

**Comment by LAX18** [comment]
I did no testing on organizational profiles. I'll start looking into this
