### ISSUE TITLE
Mail service should keep email on cache if mail service is temporarily down and sent again when mail service is up. And once failed, could retry serval times

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#16968]

**Comment by silverwind** [comment]
Queuing like that could be done by mailer daemons like postfix, I don't think every application needs to re-implement it, or at least, it should probably be disabled by default.

**Comment by echodreamz** [comment]
> Queuing like that could be done by mailer daemons like postfix, I don't think every application needs to re-implement it, or at least, it should probably be disabled by default.

Yes, this could be done by writing emails to the postfix pickup/maildrop directory and then letting postfix handle sending them.

**Comment by wxiaoguang** [comment]
I also gree that it is MTA's task, not Gitea's.
