### ISSUE TITLE
Collapse all diffs in a pull request at once

### ISSUE THREAD

**Issue by Hekewa** [go-gitea/gitea#16979]
On github when you collapse any file in PR while holding `alt` it will collapse all the files in PR files review page (https://github.blog/changelog/2018-08-17-collapse-all-diffs-in-a-pull-request-at-once/).

**Comment by wxiaoguang** [comment]
There it is:

![image](https://user-images.githubusercontent.com/2114189/234667441-98903195-f6b3-47c2-bf7f-cbd683d766f4.png)
