### ISSUE TITLE
Feature request- Repository tags/keywords

### ISSUE THREAD

**Issue by dan508** [go-gitea/gitea#16981]
- Gitea version (or commit ref): V1.14.6
- Operating system: Ubuntu 20.04

- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x ] No

One feature that I think would make Gitea great is the ability to add keywords/tags to repositories. for Instance, we have a number of repos that are for a CRM system. As the only way to find repos is to search for the name, this can take a while to do. An alternative way would be to add the ability to add keywords/tags to the repo so that instead of looking through all the repos for the one I want, I could search keywords linked to the repos such as 'CRM' or 'Sales' etc.

**Comment by techknowlogick** [comment]
This currently exists

**Comment by hwcltjn** [comment]
> This currently exists

I can't seem to find where this feature is in the UI?
