### ISSUE TITLE
Added URL mapping for Release attachments like on github.com

### ISSUE THREAD

**Issue by al-sabr** [go-gitea/gitea#1699]
## Description
Implement a Git Hub style URL mapping for the attachment files in Release.
...

## Screenshots

![image](https://cloud.githubusercontent.com/assets/26530975/25880055/6628ae2e-3535-11e7-994e-332d82d034e5.png)

**If this issue involves the Web Interface, please include a screenshot**

**Comment by cez81** [comment]
PR https://github.com/go-gitea/gitea/pull/1707 ~~https://github.com/go-gitea/gitea/pull/1700~~

**Comment by techknowlogick** [comment]
closing as linked PR has been merged.
