### ISSUE TITLE
Unable to post text to /api/v1/reponame/reponame/issues

### ISSUE THREAD

**Issue by 39charlong** [go-gitea/gitea#16999]
- Gitea version (or commit ref): 1.15.2
- Git version: 1.15.2
- Operating system: nix
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
- Log gist:

## Description

This is happening way frequent rendering gitea unuseable.
`Short texts` are okay, `a little bit long text` are not.

1. POST long text(example below) to /api/v1/reponame/reponame/issues ; [body=textdatahere]
2. Gitea will return `{api swagger}` thing and nothing else.

**Comment by noerw** [comment]
Please refer to the API docs: you can't just put the issue body text in the request body. Also `/reponame/reponame` is likely to be the wrong URL prefix.
https://try.gitea.io/api/swagger#/issue/issueCreateIssue

If you still think this is a bug, please provide a proper way to reproduce, eg a curl command.
