### ISSUE TITLE
Error message , error saving to custom config: open /etc/gitea/app.ini: permission denied

### ISSUE THREAD

**Issue by StefanSa** [go-gitea/gitea#17002]
- Gitea version (or commit ref): 1.15.2
- Git version: 2.31.1
- Operating system: openLeap 15.3
  
  
  
- Database (use `[x]`):
  - [x] PostgreSQL
- Can you reproduce the bug at https://try.gitea.io:
  - [x] No
- Log gist:

## Description

...

Hi there,
have a little strange behavior.
If the symlink to app.ini is missing in /etc/gitea, i get this error message when i push.
```
setting/setting.go:1168:CreateOrAppendToCustomConf() [F] error saving to custom config: open /etc/gitea/app.ini: permission denied
```
Gitea is started via systemd with these parameters:
```
[Unit]
Description=Gitea (Git with a cup of tea)
After=syslog.target
After=network.target
Requires=postgresql.service
[Service]
Type=simple
User=gitea
Group=gitea
WorkingDirectory=/var/lib/gitea/
RuntimeDirectory=gitea
ExecStart=/usr/local/bin/gitea web -c /etc/gitea/conf/app.ini
Restart=always
Environment=USER=gitea HOME=/home/gitea GITEA_WORK_DIR=/var/lib/gitea GITEA_CUSTOM=/etc/gitea
[Install]
WantedBy=multi-user.target
```
Why does this symlink have to be available so that you can push, a bug?
thanks for any help here.
Stefan

**Comment by delvh** [comment]
`Permission denied` tells you the most likely the cause for this error:
You have insufficient permissions to edit this file.
Can you please check using `ls -alhq /etc/gitea | grep ` what the current permissions for this file are and who owns it?
There are two plausible errors according to this error statement:
1) There is a permission problem so that your gitea user cannot write to that file. Something like `sudo chmod 606 /etc/gitea/app.ini` most likely resolves this problem. 
2) Somewhat related: the gitea user is not the owner of the file as you most likely used `sudo touch /etc/gitea/app.ini` or something similar. If that is the case, a `sudo chown gitea:gitea /etc/gitea/app.ini` should resolve the problem.

I do have to admit, however, that I do not know why exactly Gitea would change the config file when a simple push is made.

**Comment by techknowlogick** [comment]
> why exactly Gitea would change the config file when a simple push is made

assuming various internal secrets are not set, then Gitea will attempt to set them.

**Comment by StefanSa** [comment]
The question is, why despite "web -c /etc/gitea/conf/app.ini" and "GITEA_CUSTOM=/etc/gitea" there has to be an app.ini in "/etc/gitea at all, if it already exists in /etc/gitea/conf/ ?

**Comment by StefanSa** [comment]
This is a bug in my eyes.
With this permission, i  get the said error message.
```
git-03:/etc # ls -alhq /etc/gitea
insgesamt 4,0K
drwxr-x--- 1 root  gitea   66 10. Sep 08:56 .
drwxr-xr-x 1 root  root  4,5K  9. Sep 17:35 ..
drwxrwxr-x 1 root  gitea   14  9. Sep 12:35 conf
drwxr-xr-x 1 root  root    66  9. Sep 17:19 options
drwxr-xr-x 1 root  root    18  9. Sep 17:19 public
drwxr-xr-x 1 root  root   188  9. Sep 17:19 templates
```
and with this permission gitea creates the file in `/etc/ gitea` even though it already exists in `/etc/gitea/conf`, but there is now a new error message.
```
git-03:/etc/gitea # ls -alhq /etc/gitea
insgesamt 4,0K
drwxrwx--- 1 root  gitea   66 10. Sep 08:56 .
drwxr-xr-x 1 root  root  4,5K  9. Sep 17:35 ..
-rw------- 1 gitea gitea  135 10. Sep 08:56 app.ini
drwxrwxr-x 1 root  gitea   14  9. Sep 12:35 conf
drwxr-xr-x 1 root  root    66  9. Sep 17:19 options
drwxr-xr-x 1 root  root    18  9. Sep 17:19 public
drwxr-xr-x 1 root  root   188  9. Sep 17:19 templates
```
```
remote: Gitea: Internal Server Error  
```
There really has to be a `symlink` in`\etc\gitea` for gitea to work correctly at the moment.

**Comment by delvh** [comment]
> > why exactly Gitea would change the config file when a simple push is made
> 
> assuming various internal secrets are not set, then Gitea will attempt to set them.

Why exactly would that be necessary? Wouldn't it suffice to simply do that at application startup?

**Comment by delvh** [comment]
> and with this permission, gitea creates the file in `/etc/ gitea` even though it already exists in `/etc/gitea/conf`, but there is now a new error message.

I think I can partially understand why it needs this extra file: It doesn't want to overwrite the original config, and hence it needs a new file. And I guess, in that case, it did not have enough permission to write to this file. That's my guess at what happened. If that is really the case, we should perhaps update the docs to say that the `/etc/gitea` or whatever directory needs the right permissions to work correctly.

But it is interesting that you encounter a new error now.
Would you mind pasting the logs for that error here as well?
"Internal Server Error" is not concise enough to track down the problem.

**Comment by StefanSa** [comment]
Despite loglevel debug, you don't really see much in the log file.
```
2021/09/10 09:29:20 ...s/context/context.go:700:1() [D] Session ID: 2a06ea5ceade4a3c
2021/09/10 09:29:20 ...s/context/context.go:701:1() [D] CSRF Token: AX0SDsPlM1V8Kz-Ldg-NbJNNdRI6MTYzMTI1ODk2MDYyMDEyODMzNw
2021/09/10 09:29:21 ...s/context/context.go:700:1() [D] Session ID: 608b995912f7d345
2021/09/10 09:29:21 ...s/context/context.go:701:1() [D] CSRF Token: o3QeCaoZa_U2upmI8-QIBcj1Lzo6MTYzMTI1ODk2MTQ3MzkyNDY3MQ
2021/09/10 09:29:21 ...dules/git/command.go:143:RunWithContext() [D] /var/lib/gitea/data/gitea-repositories/felten-group-it/gitea-installation.git: /usr/bin/git -c credential.helper= -c proto
col.version=2 -c filter.lfs.required= -c filter.lfs.smudge= -c filter.lfs.clean= receive-pack --stateless-rpc --advertise-refs .
2021/09/10 09:29:21 ...s/context/context.go:700:1() [D] Session ID: 9a1aec8aca3a7fdf
2021/09/10 09:29:21 ...s/context/context.go:701:1() [D] CSRF Token: P4zhGAhlqro6KoWNBI5OQYgz0Tw6MTYzMTI1ODk2MTU1Nzc0OTY5MA
```

**Comment by zeripath** [comment]
Hmm...

The apparent issue here is that the `-c` option for passing in a specified config file is not working on your setup. Now that's interesting because others do not appear to be having this problem.

* If instead of using `-c` you put `--config` does that work?
* How are you starting `gitea` are you sure that the above service file is the one that is running?
   * What does `ps auxwww | grep gitea` show? Is the `-c` even being passed to Gitea?
* The first four lines emitted by Gitea to stdout - which will be usually be journalctl on systemd - tell us about how Gitea is being configured. What are they?

---

When you see `remote: Gitea: Internal Server Error` you should look at your gitea server logs for more information - but you need to read: https://docs.gitea.io/en-us/logging-configuration/#debugging-problems

---

However, this is jumping ahead because at present your systemd unit is not working the way it should - so all bets are off about the configuration of Gitea.

**Comment by delvh** [comment]
Don't share your server secrets on a public issue!

**Comment by StefanSa** [comment]
`--config` is not the trick either, same behavior.
```
git-03:/etc/systemd/system # ps auxwww | grep gitea
root      2678  0.0  0.1  85496  4544 pts/0    S    Sep09   0:00 su gitea
gitea     2679  0.0  0.2  20932  8964 pts/0    S+   Sep09   0:00 bash
gitea    19906 27.1  5.3 1665228 213756 ?      Ssl  09:41   0:00 /usr/local/bin/gitea web --config /etc/gitea/conf/app.ini
postgres 19927  0.0  0.4 253400 18008 ?        Ss   09:41   0:00 postgres: gitea gitea 127.0.0.1(53990) idle
postgres 19928  0.0  0.3 252620 15728 ?        Ss   09:41   0:00 postgres: gitea gitea 127.0.0.1(53992) idle
root     19933  0.0  0.0  10128   728 pts/1    R+   09:41   0:00 grep --color=auto gitea
```

**Comment by StefanSa** [comment]
OK more debug Infos here ...
```
2021/09/10 10:06:55 Started GET /IT/gitea-Installation.git/info/refs?service=git-receive-pack for 127.0.0.1:0
2021/09/10 10:06:55 Completed GET /IT/gitea-Installation.git/info/refs?service=git-receive-pack 401 Unauthorized in 4.788087ms
2021/09/10 10:06:56 Started GET /IT/gitea-Installation.git/info/refs?service=git-receive-pack for 127.0.0.1:0
2021/09/10 10:06:56 Completed GET /IT/gitea-Installation.git/info/refs?service=git-receive-pack 200 OK in 35.516881ms
2021/09/10 10:06:56 Started POST /IT/gitea-Installation.git/git-receive-pack for 127.0.0.1:0
2021/09/10 10:06:56 Completed POST /IT/gitea-Installation.git/git-receive-pack 200 OK in 124.475656ms
```
It is important to know that i started gitea in the shell of `gitea`. So here the `unit` has no influence on this error. That is a general problem.
```
/usr/local/bin/gitea web --config /etc/gitea/conf/app.ini
```

**Comment by StefanSa** [comment]
@zeripath , sehr mysteriös
I have done the following to understand where the permission problems may reside.
I created a backup of everything and then completely deleted everything that has to do with the gitea installation, including the user...
After that i installed gitea via the openLeap repo, restored the data and copied the appropriate binary instead of the repo.
You have to know that the binary of the repo of openLeap is located in `usr/bin/gitea` and not in `usr/local/bin/gitea` as in the previous installation.
With this gitea installation, i now get this error message when committing.
```
remote: ./hooks/pre-receive.d/gitea: Zeile 2: /usr/local/bin/gitea: Datei oder Verzeichnis nicht gefunden
```
If i copy the binary to the old location as before, i also get this permission problem with the repo of openLeap. 
At the moment i am a bit perplexed why there are these problems here.

**Comment by StefanSa** [comment]
I think i have found the error, but i don't really understand it.
i copied the binary to `/usr/bin/`, then makes a `Resync pre-receive, update and post-receive hooks of all repositories.`
Now i do not know what the cause was / is, wrong location of the binary or had the `post-receive hooks` helped ?

**Comment by zeripath** [comment]
synchronizing the hooks is always necessary if you move the gitea binary - it's likely that was the cause of the problem.

I think we can close this now.
