### ISSUE TITLE
404 Repo Inaccessible for Users in Team w/ All Repo Access

### ISSUE THREAD

**Issue by SoulSeekkor** [go-gitea/gitea#17003]
- Gitea version (or commit ref): 1.15.2 built with GNU Make 4.1, go1.16.7 : bindata, sqlite, sqlite_unlock_notify
- Git version: 2.33.0.2
- Operating system: Windows Server 2012 R2
  Running using your pre-built Win x64 binary.  This is being started/stopped using a Windows service created per your installation instructions running as a local user with 'full control' of relevant folders.
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [X] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No (Couldn't register or email was taking a super long time to come. May have to try this later.)

## Description
1) Create new organization as admin user and make it private.
2) Create a new empty repo named 'test'.
2) Create new team named 'read-only' with all repo access, read, with everything toggled OFF except code.
3) Add a regular (and restricted) test user to the read-only team.
4) Attempt for that user to access the repo they should have access to will fail with a 404.

Note that creating the team and THEN creating the repo works fine, just not in reverse.  The retroactively applied permissions for a team created after the repo was created is botched.

**Comment by zeripath** [comment]
We need logs.

**Comment by SoulSeekkor** [comment]
Relevant access.log entry:
x.x.x.x:64329 - testuser [15/Sep/2021:14:33:06 -0500] "GET /GiteaTest/test HTTP/2.0" 404 18396 "\" \"Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36 Edg/93.0.961.47"

Entries from the gitea.log:
2021/09/15 14:33:04 ...ices/auth/session.go:73:SessionUser() [T] Session Authorization: Logged in user 9:testuser
2021/09/15 14:33:04 models/repo.go:349:getUnits() [T] repo.Units: [0xc0093e98c0 0xc0093e9920 0xc0093e9980 0xc0093e99e0 0xc0093e9a40 0xc0093e9aa0]
2021/09/15 14:33:04 models/repo.go:349:getUnits() [T] repo.Units: [0xc009682c90 0xc009682cf0 0xc009682d50 0xc009682db0 0xc009682e10 0xc009682e70]
2021/09/15 14:33:04 ...s/repo_permission.go:154:func1() [T] Permission Loaded for 9:testuser in 106:GiteaTest/test:
	Permissions: AccessMode: 0:none, 1 Units, 1 UnitsMode(s): [ 
	Units[0]: ID: 772 RepoID: 106 Type: 1:UnitTypeCode Config: {}
	UnitMode[1:UnitTypeCode]: 1:read ]
2021/09/15 14:33:04 ...s/repo_permission.go:154:func1() [T] Permission Loaded for 9:testuser in 106:GiteaTest/test:
	Permissions: AccessMode: 0:none, 1 Units, 1 UnitsMode(s): [ 
	Units[0]: ID: 772 RepoID: 106 Type: 1:UnitTypeCode Config: {}
	UnitMode[1:UnitTypeCode]: 1:read ]
2021/09/15 14:33:04 ...s/context/context.go:740:1() [D] Session ID: f5d659a998deecb9
2021/09/15 14:33:04 ...s/context/context.go:741:1() [D] CSRF Token: 1997u8NBnd-DzYyjfxV0DVPlXyk6MTYzMTczMjg5OTMzODU1NjAwMA
2021/09/15 14:33:04 ...ices/auth/session.go:57:SessionUser() [T] Session Authorization: Found user[9]
2021/09/15 14:33:04 ...ices/auth/session.go:73:SessionUser() [T] Session Authorization: Logged in user 9:testuser
2021/09/15 14:33:06 ...s/context/context.go:740:1() [D] Session ID: f5d659a998deecb9
2021/09/15 14:33:06 ...s/context/context.go:741:1() [D] CSRF Token: 1997u8NBnd-DzYyjfxV0DVPlXyk6MTYzMTczMjg5OTMzODU1NjAwMA
2021/09/15 14:33:06 ...ices/auth/session.go:57:SessionUser() [T] Session Authorization: Found user[9]
2021/09/15 14:33:06 ...ices/auth/session.go:73:SessionUser() [T] Session Authorization: Logged in user 9:testuser
2021/09/15 14:33:06 models/repo.go:349:getUnits() [T] repo.Units: [0xc00924eb10 0xc00924eb70 0xc00924ebd0 0xc00924ec30 0xc00924ec90 0xc00924ecf0]
2021/09/15 14:33:06 ...s/repo_permission.go:154:func1() [T] Permission Loaded for 9:testuser in 106:GiteaTest/test:
	Permissions: AccessMode: 0:none, 1 Units, 1 UnitsMode(s): [ 
	Units[0]: ID: 772 RepoID: 106 Type: 1:UnitTypeCode Config: {}
	UnitMode[1:UnitTypeCode]: 1:read ]
2021/09/15 14:33:06 ...s/context/context.go:185:HTML() [D] Template: status/404

**Comment by zeripath** [comment]
OK it looks like this works on 1.16/main right now.

![Screenshot from 2021-09-15 21-33-26](https://user-images.githubusercontent.com/1824502/133505453-87b9d349-24f4-4a12-8d2f-65792c5ee597.png)

**Comment by zeripath** [comment]
Just pulled docker 1.15.2 as above:

![Screenshot from 2021-09-15 21-37-09](https://user-images.githubusercontent.com/1824502/133505974-05d542e5-a0c7-44d4-8d0d-76e9b235bd06.png)

But was not able to reproduce the problem.

**Comment by SoulSeekkor** [comment]
Hmm odd, I was able to reliably perform this again to cause the problem.  Just to confirm you created the repo first in the private org, created the team (with all repo access for read, code only), added the regular and restricted user to the team and were able to access the repo successfully?

**Comment by zeripath** [comment]
I didn't test the restricted user yet. But the regular one works.

**Comment by SoulSeekkor** [comment]
Okay, on Monday I'll test it with a regular user to see if that one works to confirm if it's specific to the restricted user or not.

**Comment by noerw** [comment]
Can confirm with 1.15.3 + restricted user added *after* a repo is added.
The user can access the repo, once I toggle the private flag for a repo once (independent from the initial private state)
