### ISSUE TITLE
always running processes from 1.14.5=>1.15.2

### ISSUE THREAD

**Issue by dannyzcy** [go-gitea/gitea#17007]
- Gitea version (or commit ref): 1.15.2
- Git version:  2.33.0.windows.2
- Operating system:
  windowns
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No

## Description
always running processes from 1.14.5=>1.15.0=>1.15.1=>1.15.2

the bug from 1.15.x

not appear in 1.14.5

## Screenshots
![未命名](https://user-images.githubusercontent.com/89442035/132778725-4dc798c3-804e-4b92-b07e-c322c936c239.png)

**Comment by zeripath** [comment]
Is there actually a process associated with this on your system?

**Comment by zeripath** [comment]
Apologies there appears to be a missing Close if the external context is cancelled and the defer wasn't firing due to a slight gotcha.
