### ISSUE TITLE
Pijul VCS support

### ISSUE THREAD

**Issue by notramo** [go-gitea/gitea#17019]
[Pijul](https://pijul.org/) is a distributed version control system based on a theory of patches.
It's dimilar to Darcs, but is solves some merging problems that Darcs has.
It's easier to use than Git, and has better conflict resolution.

Since Gitea is a quite big platform (Issues, PRs, code highlighter, etc.), from which only a small part is Git-related, I think, most of the code should not need to be changed.

**Comment by lunny** [comment]
I don't think supporting more version control systems is a good idea. And since it's `Git`ea, we should still stick in Git.

**Comment by notramo** [comment]
Why isn't it a good idea?

**Comment by mohe2015** [comment]
Probably because this project is already super wide in scope and there's lots of work to do. Also as Pijul has other approaches this would probably need lots of redesigning / duplication.

**Comment by mohe2015** [comment]
Still if you have the time to implement this a fork could still be a good idea to not have to duplicate that much work.

**Comment by zeripath** [comment]
Git is tightly tied into the way Gitea works. It would be an immense amount of work to even basically support other VCSs.

Supporting a pijul emulation layer or bridge may be possible in the future if one was written but we could consider that at that point. 

A PR & issue could be opened at that point but until then I think this out of scope.
