### ISSUE TITLE
click into pull_request failed (error : 500)

### ISSUE THREAD

**Issue by yuyuanshifu** [go-gitea/gitea#17010]
we create a pull request, and we can see it in the pull request list, but can not click into the pull request(error:500)

**Comment by a1012112796** [comment]
@yuyuanshifu which version?

**Comment by zeripath** [comment]
Your screenshot has also cut off most of the error. What was the rest of the error report in the logs.

**Comment by yuyuanshifu** [comment]
Sorry to reply so late.
I reproduce the problem again:
1、Create two branches: test1 and test2
2、Create pr1 from test1 to master
3、Create pr2 from test2 to test1.
4、Create a tag with the same name as test1
5、Update the base branch in PR2
6、Click to approve pr2, error 500 will be reported
7、Click to enter PR1 details, error 500 will be reported

**Comment by zeripath** [comment]
Let me be clearer.

WE NEED COMPLETE LOGS.

Not just a half cut off error - not a screenshot.

**Comment by yuyuanshifu** [comment]
> @yuyuanshifu which version?

v1.12.3

**Comment by yuyuanshifu** [comment]
> Let me be clearer.
> 
> WE NEED COMPLETE LOGS.
> 
> Not just a half cut off error - not a screenshot.

sorry, I wrote the reproduce step above。

**Comment by zeripath** [comment]
OK Version 1.12.3 of Gitea is way out of date and we cannot provide support for this version. For reference there are 2460 commits between it and 1.15.2 and 7806 files changed, 1159111 insertions & 361623 deletions.

Update your version of Gitea to 1.15.2 and open a new issue if the problem occurs again.

In future:

* DO NOT just delete the issue proforma - fill it in and complete it as much as possible.
* Give us logs as per the instructions linked to in the proforma: https://docs.gitea.io/en-us/logging-configuration/#debugging-problems

I appreciate that coming across problems and not being sure how to fix things is frustrating however, we provide support and help for free - we simply ask that you provide us with the minimum of information to help you.

It is not acceptable or fair to not even give us that.

**Comment by yuyuanshifu** [comment]
> OK Version 1.12.3 of Gitea is way out of date and we cannot provide support for this version. For reference there are 2460 commits between it and 1.15.2 with 7806 files changed, 1159111 insertions & 361623 deletions.
> 
> Update your version of Gitea to 1.15.2 and open a new issue if the problem occurs again.
> 
> In future:
> 
> * DO NOT just delete the issue proforma - fill it in and complete it as much as possible.
> * Give us logs as per the instructions linked to in the proforma: https://docs.gitea.io/en-us/logging-configuration/#debugging-problems
> 
> I appreciate that coming across problems and not being sure how to fix things is frustrating however, we provide support and help for free - we simply ask that you provide us with the minimum of information to help you.
> 
> It is not acceptable or fair to not even give us that.

Sorry , I am not meaning to hide some info to you.
Today I realized that I provided error info last week, so I reproduce the steps and delete the error info.
Thx anyway.
