### ISSUE TITLE
Webhook Improvement

### ISSUE THREAD

**Issue by DblK** [go-gitea/gitea#1702]
When I used the actual webhook, I saw that there is still some "Gogs" implementation, so first we should modify it.

I would also suggest to modify the webhook implementation by dividing it into two sort of webhook.
One for incoming and another for outgoing (as it is right now).

If we implement incoming webhook, it can be a nice implementation for CI result of commit or PR (see #996).

For the implementation on the UI, I would suggest either add another button for "Incoming Webhook" and rename "Add Webhook" to "Outgoing Webhook" or use icons in the list like the following ones:
![image](https://cloud.githubusercontent.com/assets/832617/25891333/f9f24670-3570-11e7-8eb9-b5984481d331.png)

What do you think about those improvements?

**Comment by lunny** [comment]
what's the different between incoming webhooks and outgoing webhoks ?

**Comment by DblK** [comment]
For Outgoing webhook, it's only when Gitea will POST to another url like Rocket.Chat, Mattermost,...

The Incoming webhooks is when another application POST to Gitea that will handle the post to do something.
I can see a use of incoming webhook to drone for example POST a result and Gitea will handle it to update a table with the build status.

I am clear enough?

**Comment by DblK** [comment]
After digging to the code and on github api, I found this (https://developer.github.com/v3/repos/statuses/).
My proposal for incoming webhook does not have to exist because of the API that I forgot :p.

So the only thing I think we should do is to remove the "GOGS" information in all webhook.
See, [there](https://github.com/go-gitea/gitea/blob/a85c5ab9ff60dab58b2bf713479460caac8e9567/models/webhook.go#L539) for example.

I can make a PR very quickly ;)

**Comment by DblK** [comment]
I made a PR for adding Gitea Webhook #1755.
However the status are already inside the code, so nothing to do with this issue anymore.
