### ISSUE TITLE
Relax email validation

### ISSUE THREAD

**Issue by metov** [go-gitea/gitea#17029]
When adding emails for a user under `Settings -> Account -> Manage Email Addresses`, Gitea 1.12.1 applies an email validation. If the address given doesn't satisfy gitea, it issues https://github.com/go-gitea/gitea/blob/3d6cb25e315c0d4249c5c749a2eb8c64ec463aad/options/locale/locale_en-US.ini#L417.

It seems like part of the validation is to require a `.` in the domain, so for example `johndoe@homepc` will be considered "invalid" while `johndoe@homepc.local` will be accepted.

I don't think it makes sense for gitea to validate emails at this point. AFAIK these emails serve two purposes:

1. Send email notifications
2. Associate the user with the emails in git histories

Git 2.33.0 considers `johndoe@homepc` a valid email and does not complain if commits are signed with it. When such commits are pushed to gitea, gitea then displays the author as `johndoe` with no way of associating the actual gitea user with this. Since a git host like gitea should fully support all repositories produced by git, this seems to me like a bug with respect to point 2.

If we allow "invalid" emails to be added to the profile, then occasionally this might break point 1. There is anyhow no way to guarantee that sending emails won't occasionally fail, so letting users enter "invalid" emails does not actually introduce any new corner cases. Users can already enter invalid emails if they really want, the validation just requires the email to be invalid while conforming to a regex, so no problem is being solved here while the user is inconvenienced. That said, if validation is seen as necessary, perhaps emails could be validated not when they are being added, but when notifications are enabled for them.

**Comment by zeripath** [comment]
You should propose a PR to  https://gitea.com/go-chi/binding:

To change this line https://gitea.com/go-chi/binding/src/branch/master/binding.go#L236:

```go
	EmailPattern        = regexp.MustCompile("[\\w!#$%&'*+/=?^_`{|}~-]+(?:\\.[\\w!#$%&'*+/=?^_`{|}~-]+)*@(?:[\\w](?:[\\w-]*[\\w])?\\.)+[a-zA-Z0-9](?:[\\w-]*[\\w])?")
```

to:

```go
	EmailPattern        = regexp.MustCompile("[\\w!#$%&'*+/=?^_`{|}~-]+(?:\\.[\\w!#$%&'*+/=?^_`{|}~-]+)*@(?:[\\w](?:[\\w-]*[\\w])?\\.)*[a-zA-Z0-9](?:[\\w-]*[\\w])?")
```

That would solve this issue.

**Comment by axifive** [comment]
@zeripath How about make EmailPattern changeable from admin settings page?

**Comment by metov** [comment]
>You should propose a PR to https://gitea.com/go-chi/binding:
Well, that would solve the specific issue I'm having. But it seems like it would get a bit tedious to amend that pattern every time someone discovers a new email pattern (and there is [quite a few](https://stackoverflow.com/q/201323)). Besides, I don't think git itself validates emails at all, so technically the email from git history can be any string.

@axifive Maybe not changing the pattern itself, but simply add a flag to admin settings about whether that pattern will be applied or not?

**Comment by metov** [comment]
Also, if anyone else is having a similar problem, my workaround is:

* Add email with some placeholder TLD
* Navigate to the data directory containing gitea.db
* Open DB session: `sqlite3 gitea.db`
* See all emails: `select email from email_address;`
* Edit the one you want: `update email_address set email = 'johndoe@homepc' where email = 'johndoe@homepc.local;`

And then gitea will correctly associate the email with the commit.

**Comment by zeripath** [comment]
@metov Our emails have to be mailable.
