### ISSUE TITLE
Default branch can be missing on releases tab

### ISSUE THREAD

**Issue by delvh** [go-gitea/gitea#17037]
- Gitea version (or commit ref): 1.16.0+dev-209-g9fa6bdb64
- Can you reproduce the bug at https://try.gitea.io: not sure, was noticed on https://gitea.com/xorm/xorm/releases

## Description
Apparently, the default branch can be missing on the release page of projects.
This seems to be a backend issue because the generated link is `https://gitea.com/xorm/xorm/compare/v1.2.2...` as well and hence missing the branch to compare with.
When I disable JavaScript, the result is still the same.

## Screenshots
![image](https://user-images.githubusercontent.com/51889757/133160612-7de738d9-752d-4e48-938a-023d017d275d.png)

**Comment by a1012112796** [comment]
maybe `Target` of these `Release` is missing in db. But don't know why.
hasen't found this bug on the latest commit (`1.16.0+dev-239-g04b233e94`)

**Comment by wxiaoguang** [comment]
Related to  #24470 and  #24148 

I think this issue has been fixed.
