### ISSUE TITLE
Create webhook through api returns 422

### ISSUE THREAD

**Issue by jessielaf** [go-gitea/gitea#17038]
- Gitea version (or commit ref): 1.13.7 
- Git version: 2.33.1
- Operating system:
Gitea is downloaded from the release-page on github.
It runs through systemd

- OS: Ubuntu 20.04

- Database (use `[x]`):
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X] No
 I cannot create a account at try.gitea.io because I do not receive the email to enter my password. So I can not test it.
- Log gist:

## Description
I am trying to make a call to gitea to create webhooks programmatically. 

Request url: `'https://gitea.example.com/api/v1/repos/software/release-notes/hooks'`

Request body:
```json
{
   "active":true,
   "branch_filter":"*",
   "config":{
      "content_type":"application/json",
      "url":"http://example.com/commits/",
      "http_method":"post"
   },
   "events":[
      "push"
   ],
   "type":"gitea"
}
```
Request headers:
```json
{
   "User-Agent":"python-requests/2.26.0",
   "Accept-Encoding":"gzip, deflate",
   "Accept":"*/*",
   "Connection":"keep-alive",
   "Content-Type":"application/json",
   "Content-Length":"186",
   "Authorization":"Basic {{ basic auth }}"
}
```

Response status code: 422
Response:
```json
{
   "message":"Invalid content type",
   "url":"https://gitea.example.com/api/swagger"
}
```

I tried to send the request through postman and with the python requests library both came back with the same result.

**Comment by ash-r1** [comment]
By using `json` instead of `application/json` for `body.config.content_type`-ish request body, it works.

Although, I agree with the idea that this is a bug.

refs #13907

**Comment by wxiaoguang** [comment]
`body.config.content_type` is not HTTP header's content type
