### ISSUE TITLE
Empty loading issue context popup for external issue tracker

### ISSUE THREAD

**Issue by jpraet** [go-gitea/gitea#17047]
- Gitea version (or commit ref): 1.15.2
- Can you reproduce the bug at https://try.gitea.io:
  - Yes: https://try.gitea.io/jpraet/review-test/pulls/1

## Description

I'm seeing an empty issue context popup that remains loading, when an external issue tracker is configured.
This is since upgrading from 1.14 to 1.15.

## Screenshots

![image](https://user-images.githubusercontent.com/2212615/133307899-8996b9b4-e7ff-4406-805a-ad0a32a9381c.png)

**Comment by zeripath** [comment]
would it be possible to check the web console - there is likely to be an error in there/#.

**Comment by zeripath** [comment]
OK it's likely something to do with:

https://github.com/go-gitea/gitea/blob/e2f0ab3343cd4ed710221d96c253566c20cfab04/web_src/js/features/contextpopup.js#L5-L12

this shouldn't be firing for external issues - so probably these need to have a different class instead of `ref-issues`
