### ISSUE TITLE
Support pikchr in Markdown renderer

### ISSUE THREAD

**Issue by melak** [go-gitea/gitea#17048]
"[Pikchr](https://pikchr.org/) (pronounced "picture") is a PIC-like markup language for diagrams in technical documentation.", from the same bloke who let SQLite and Fossil loose on the unsuspecting word.

Please consider adding pikchr support to the Markdown renderer. There seems to be a [Go binding](https://github.com/gebv/pikchr) available (can't say anything about its suitability though).

**Comment by KN4CK3R** [comment]
Alternative usage could be like https://docs.gitea.io/en-us/customizing-gitea/#example-plantuml
