### ISSUE TITLE
Markdown checkbox missing check mark

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#17042]
- Gitea version (or commit ref): 1.16.0
- Git version:
- Operating system: Windows
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (https://try.gitea.io/ZukenHammer/markdown-checkbox-print/src/branch/master/README.md)
  - [ ] No

## Description
When trying to print a markdown with checkboxes in a list from Gitea the check mark is missing in the printing.
Tried browsers: 
* Chrome 93
* Firefox 90
* Edge 93

## Screenshots
Webpage:
![image](https://user-images.githubusercontent.com/62339082/133265878-b0bb1cbe-671c-46cf-927e-10c3409d61cf.png)

Printing preview:
![image](https://user-images.githubusercontent.com/62339082/133265732-e06d997e-ac33-40f0-920a-ab708973c06b.png)

**Comment by wxiaoguang** [comment]
Remove some css styles, then the check mark appears again.

```
.markup input[type=checkbox] {
    /* -webkit-appearance: none; */
    /* -moz-appearance: none; */
    /* appearance: none; */
}
.markup input[type=checkbox]:after {
    /* background: var(--color-text); */
}
```

And it's very strange that this bug is not related to media(print), if the media(print) is activated manually in Chrome's Developer Tools console, the rendered page in browser is still correct while the print preview is wrong.

**Comment by sebastian-sauer** [comment]
When enabling "Background graphics" in Print Dialog (expand More Settings) the Checkbox will be rendered correctly.

**Comment by sebastian-sauer** [comment]
Looks like a "-webkit-print-color-adjust: exact;" for the checkbox:after will solve this issue.
I'll create a PR for this.

**Comment by sebastian-sauer** [comment]
In Firefox the problem is solved by adding the color-adjust. Looks like chrome doesn't apply the mask-image when printing:

![checkbox](https://user-images.githubusercontent.com/1135157/134061095-f998743a-9eb6-4140-917e-086f2aece4c6.png)
