### ISSUE TITLE
git tree corruption

### ISSUE THREAD

**Issue by cookiengineer** [go-gitea/gitea#1704]
- Gitea version (or commit ref): 1.0.1
- Git version: 2.12.2
- Operating system: Arch Linux
- Database (use `[x]`):
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] No

## Description

My gitea installation on my Raspberry Pi worked fine for around half a year. Now, all of a sudden, the installation is broken and I cannot push to the repositories.

```bash
Counting objects: 77, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (73/73), done.
Writing objects: 100% (77/77), 9.43 KiB | 0 bytes/s, done.
Total 77 (delta 47), reused 1 (delta 0)
remote: error: object file /opt/gitea/gitea-repositories/artificial-engineering/lycheejs.git/./objects/incoming-skZwQJ/52/f4a1425dc36727aecbb6daef4f378a9095682f is empty
remote: fatal: loose object 52f4a1425dc36727aecbb6daef4f378a9095682f (stored in /opt/gitea/gitea-repositories/artificial-engineering/lycheejs.git/./objects/incoming-skZwQJ/52/f4a1425dc36727aecbb6daef4f378a9095682f) is corrupt
error: remote unpack failed: unpack-objects abnormal exit
To git-mirror:Artificial-Engineering/lycheejs.git
 ! [remote rejected] feature/studio -> feature/studio (unpacker error)
error: failed to push some refs to 'git@git-mirror:Artificial-Engineering/lycheejs.git'
```

- How did the corruption happen?
- How can I fix it? Do I need to reinstall gitea? (Hopefully not :'( )

I was trying to follow the suggestions on SO and basically scp'ed some corrupted files from the git folder to the gitea instance. However, this didn't help much and after ~10-15 files I gave up.

Both logs (`gogs.log` and `gogs.log.<today's date>`) show up nothing.

**Comment by typeless** [comment]
[This](https://confluence.atlassian.com/bitbucketserverkb/recommended-action-plan-if-a-repository-becomes-corrupted-on-a-bitbucket-server-779171653.html) might help for you.
