### ISSUE TITLE
Link to attachment via copy & paste not correct

### ISSUE THREAD

**Issue by nsolthe** [go-gitea/gitea#17057]
- Gitea version (or commit ref): 1.15.2
- Git version: 2.17.1
- Operating system: Linux
  - Downloaded gitea from binary (`https://dl.gitea.io/gitea/1.15.2/gitea-1.15.2-linux-amd64.xz`)
  - Running as `systemd` service
  - Distro: Ubuntu Server 18.04.5 LTS
- Database:
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] No
- Log gist:
  - see attachement
[gitea.log](https://github.com/go-gitea/gitea/files/7169502/gitea.log)

## Description

I'm working on a Windows PC.
While creating an issue or creating/editing a comment I like to add screenshots. I copy the image file by selecting it in the file explorer, press "Ctrl + c" on keyboard, change to Windows Edge where I am creating the comment, press "Ctrl + v" after the cursor is in the location where I want the image.

The image gets added as and the link is added after file upload completes. When selecting preview the image does not get displayed but I see a "broken image link" pictogram.

I have noticed that I need to edit the automatically generated link from `/gitea/attachments/<image_id>` to `/attachments/<image_id>` and then I get the image preview.

Images added in older comments/issues are currently displayed with the "broken image link" pictogram.
It seems that there have been some changes to how the links are being created.

### Hosting environment

We are using an apache as reverse proxy for http to https redirect.

The gitea base-URL is configured as: `https://<hostname>/gitea/`

## Screenshots

![image](https://user-images.githubusercontent.com/44598007/133423238-4ad86119-fbf3-4828-8b68-858c01512f70.png)

![image](https://user-images.githubusercontent.com/44598007/133423261-5765ecb7-6b10-44b7-b64f-a2a6005476cd.png)

**Comment by zeripath** [comment]
What is your `[server]` `ROOT_URL`?

Are you running gitea behind a reverse proxy with some url-rewriting?

**Comment by nsolthe** [comment]
> What is your `[server]` `ROOT_URL`?

Yes. It is:
```
[server]
ROOT_URL = https://<HOST>.<DOMAIN>/gitea/
```

> Are you running gitea behind a reverse proxy with some url-rewriting?

Yes. The apache config looks like:
 ```Redirect permanent "/gitea" "/gitea/"
<FilesMatch "\.(cgi|shtml|phtml|php)$">
SSLOptions +StdEnvVars
</FilesMatch>
<Directory /usr/lib/cgi-bin>
SSLOptions +StdEnvVars
</Directory>

<Proxy *>
Order allow,denyAllow from all
</Proxy>

ProxyPass /gitea/ http://localhost:3000/ nocanon
ProxyPassReverse /gitea/ http://localhost:3000/
AllowEncodedSlashes NoDecode```

**Comment by Sol7469** [comment]
I am a coworker of @nsolthe and I have copied the gitea instance with this problem to another Linux machine to investigate, if our reverse proxy is causing this. For this copy I used a dump and the original config file with just minor changes and of course no reverse proxy. Here is the output from a diff of both used config files:

```[server]                                                           [server]
SSH_DOMAIN       = <simple host name for testing>               |  SSH_DOMAIN       = <original hostname>
ROOT_URL         = /                                            |  ROOT_URL         = https://<=valid FQDN=>/gitea/
DISABLE_SSH      = true                                         |  DISABLE_SSH      = false

[mailer]                                                           [mailer]
ENABLED = false                                                 |  ENABLED = true
```

For me, only ROOT_URL seems to be of interest here.

Without a reverse proxy that adds `/gitea/` at the end of the URL, attachments can be pasted into comments and can be displayed without any problems. Maybe there is a little mistake in generating links in comments for pasted attachments. For me, it looks like protocol and hostname from ROOT_URL are stripped and a remaining string is put in front of a URL of an attachment. But if you are at a page of an issue, there already is a `/gitea/` at the beginning of this URL path followed by organisation name and repository name. So an additional `/gitea/` is wrong here.

Hope that helps to find this little problem.

**Comment by ryshi** [comment]
I met this problem on v1.15.6. I just copied a image and pasted into the issue editor, but image url was broken.
* attachement url by upload : `<host>/gitea/attachments/434cc057-5783-43d6-aaf1-3a743d4a9425`
* attachement url showed in editor : `<host>/gitea/ryan/test/gitea/attachments/d0836971-a3d2-48cf-97dd-82e8f938e746`

![image](https://user-images.githubusercontent.com/1818419/139770630-ea47d16e-b981-448e-a837-2cb285e9ebf4.png)

**Comment by lunny** [comment]
> I met this problem on v1.15.6. I just copied a image and pasted into the issue editor, but image url was broken.
> 
> * attachement url by upload : `<host>/gitea/attachments/434cc057-5783-43d6-aaf1-3a743d4a9425`
> * attachement url showed in editor : `<host>/gitea/ryan/test/gitea/attachments/434cc057-5783-43d6-aaf1-3a743d4a9425`
> * correct url should be : `<host>/gitea/ryan/test/attachments/434cc057-5783-43d6-aaf1-3a743d4a9425`
> 
> ![image](https://user-images.githubusercontent.com/1818419/139770630-ea47d16e-b981-448e-a837-2cb285e9ebf4.png)

Could you reproduce it on https://try.gitea.io ?

**Comment by zeripath** [comment]
Sorry this is due to us changing the base url for absolute path links from within repositories. Previously these would be relative to the host but now they're relative to the repository. Thus the appsuburl is no longer needed and is in fact incorrect.
