### ISSUE TITLE
Support dependabot

### ISSUE THREAD

**Issue by rawvoid** [go-gitea/gitea#17056]
dependabot can help developers better maintain their projects. Does the gitea project team consider adding this feature?

**Comment by techknowlogick** [comment]
This functionality can already be integrated into Gitea.

cc @kolaente

**Comment by aomsweet** [comment]
Hi, @techknowlogick  thanks for your reply. 

I'm looking forward to Gitea integrating this feature.

**Comment by kolaente** [comment]
I'm using renovate with Gitea, that works really great.

**Comment by kimpenhaus** [comment]
@techknowlogick @kolaente is there any documentation or samples on how to integrate dependabot? as for someone fairly new to that it's quite hard 😁 thanks!
