### ISSUE TITLE
Gitea 1.15 does not work on postgres <9.5: Submitting a new issue gives 500 error

### ISSUE THREAD

**Issue by artu72** [go-gitea/gitea#17067]
### Gitea Version

1.15.2

### Git Version

2.16.5

### Operating System

Linux RHEL 7.6

### How are you running Gitea?

Downloaded the 64bit version binary Linux executable, and running it as a service.

### Database

PostgreSQL

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

2021/09/16 10:00:32 models/issue.go:1012:NewIssue() [I] [SQL] ROLLBACK [] - 40.9
49µs
2021/09/16 10:00:32 ...rs/web/repo/issue.go:980:NewIssuePost() [E] NewIssue: gen
erate issue index failed: pq: syntax error at or near "ON"

### Description

Updated from gitea 1.14.6 to 1.15.2. Now, creating a new issue in every repository gives a 500 error.

**Comment by zeripath** [comment]
what version of Postgres are you running?

**Comment by zeripath** [comment]
The SQL this is failing on is: ```
INSERT INTO issue_index (group_id, max_index) "+
			"VALUES (?,1) ON CONFLICT (group_id) DO UPDATE SET max_index = issue_index.max_index+1
```

which implies you have a version of postgres that does not support ON CONFLICT

This has been present in Postgres since ve

**Comment by artu72** [comment]
> what version of Postgres are you running?

9.2

**Comment by zeripath** [comment]
I don't think we state anywhere what the minimal supported version of postgres is but I think it's entirely reasonable to set that at at least 9.5.

I guess we need to detect the version of postgres at time of startup and warn users and update the documentation.

**Comment by zeripath** [comment]
I've retitled the bug - so a PR doing the above could reference this issue and close it.

**Comment by artu72** [comment]
> I've retitled the bug - so a PR doing the above could reference this issue and close it.

Ok, thank you for the effort. Ii is fine to specify minimum requirements of the database from now on.

**Comment by zeripath** [comment]
Yeah unfortunately we absolutely have to have postgres >= 9.5.

I've added a docs PR so I will close this now.

**Comment by artu72** [comment]
I onfirm that upgrading posgres to 9.6 solved the problem.
