### ISSUE TITLE
Get tag creation timestamp from API

### ISSUE THREAD

**Issue by DrissiReda** [go-gitea/gitea#17069]
### Feature Description

Currently the api call to `repos/{owner}/{repo}/tags/{tag}` returns only the reference to the commit, and some other metadata. I would like for it to also give me the tag creation timestamp.

On the other hand the commits do give creation timestamps.

My use case : 

I need a script that tells me whether the repository has been updated (commits/tags) within the last X minutes. I know there is the webhook feature in gitea but it allows for a communication from gitea to my server. In my case that won't be possible, so I need a call from my server to gitea.

**Comment by axifive** [comment]
It's already returns tag created datetime, seems need to change the description in the swagger
https://github.com/go-gitea/gitea/blob/59c58553baa5597f5c2156b47fd2e47e46aa58ac/modules/convert/git_commit.go#L33

```
{
  "commit": {
    "created": "2021-09-25T03:34:16.599Z",
    "sha": "string",
    "url": "string"
  },
  "id": "string",
  "message": "string",
  "name": "string",
  "tarball_url": "string",
  "zipball_url": "string"
}
```

**Comment by DrissiReda** [comment]
That's not tag creation time, it's the commit creation time, so if you push the commit on 25th september, but create the tag on the 30th of september, `commit.created` will show the 25th of september.

**Comment by DrissiReda** [comment]
@axifive any idea on how to achieve that ? I still am unable to get anything besides the commit's timestamp.

**Comment by DrissiReda** [comment]
@justusbunsi I'm referring to plain tags, when I use the webhook functionality I receive the event with its timestamp, but when I use the API I can't see any timestamps. How can I create annotated tags from the UI?

**Comment by justusbunsi** [comment]
> How can I create annotated tags from the UI?

If you visit the "New release" page of your repository, you can fill the form with your desired tag name and title and at the bottom you have the checkbox to "Use the title and content of release as tag message". If you enable this checkbox and hit the button "Create Tag Only" this will create an annotated tag with it's own creation date.

![image](https://user-images.githubusercontent.com/61625851/136657921-cb57f00d-9808-4471-83b6-deb31097ab59.png)

If you want to create such tag from the command line you could use `git tag -m "<your title>" <your-tag>`.

---

As @axifive already mentioned, both api endpoints `<owner>/<repo>/tags` and `<owner>/<repo>/tags/<tagname>` already include the creation date for either _plain tags_ (which is the commit create date) or the tag creation date for _annotated tags_.
