### ISSUE TITLE
Template: status/500 - repo/branch_dropdown:12:82

### ISSUE THREAD

**Issue by rgarofalo** [go-gitea/gitea#17062]
- Gitea version (or commit ref): 1.15.2 built with GNU Make 4.3, go1.16.7 : bindata, timetzdata, sqlite, sqlite_unlock_notify
- Git version: 2.30.2
- Operating system: docker
 
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x ] No
- Log gist:

```
2021/09/15 18:24:29 ...s/context/context.go:195:HTML() [E] Render failed: template: repo/branch_dropdown:12:82: executing "repo/branch_dropdown" at <.root.BranchName>: invalid value; expected string
2021/09/15 18:24:29 ...s/context/context.go:185:HTML() [D] Template: status/500
```

## Description

I did an update of gitea to the latest version and every time I try to open a repo it gives me error 500

**Comment by lafriks** [comment]
Are you using custom templates?

**Comment by rgarofalo** [comment]
No

Il mer 15 set 2021, 18:58 Lauris BH ***@***.***> ha scritto:

**Comment by zeripath** [comment]
What version did you update from?

**Comment by rgarofalo** [comment]
> What version did you update from?
1.12

> Does your app.ini set [repository] ROOT?
yes

however I solved it by recreating the container, thanks for the quick support
