### ISSUE TITLE
[Feature Request]: Decentralize, one gitea account, involve in the activities amoung the gitea instance all over the world.

### ISSUE THREAD

**Issue by evan0greenup** [go-gitea/gitea#17087]
### Feature Description

Just inspired by Matrix Protocol, https://matrix.org/

Each server hold a bunch of accounts, but the accounts in different server can also interact each other.

Currently, Github is the center of git-based open source development. But itself is not open source at all. Github might be influenced by politics or other non-tech related issue.

Gitea is completely open source, and the gitea instance is distributed all over the world.

It might be a large list about what exactly the feature in details include.

But it would be nice to make exist gitea instance form a large network. And make users of those instance feel that they are in a gap-less Gitea decentralized network.

All the activities in a single server can be done between servers.

For example, user A `@A@gitea.hello.world` might clone a project `gitea.nice.peace:/B/project_sample` from `@B@gitea.nice.peace`. A's fork will display the original repo position, and he can easily submit new merge request back.

If a user on `gitea.nice.peace` [at] A, the server `gitea.nice.peace` will send a request to server `gitea.hello.world`, and A will receive the notification. While this is just an example, more inter-server communication should be included.

**Comment by evan0greenup** [comment]
With the power of decentralization, it have potential to become the large ecosystem just as Github has done.

**Comment by evan0greenup** [comment]
@lunny @zeripath what is your opinion?

**Comment by evan0greenup** [comment]
By the way, the feature of real-time cross-server mirroring could be added.

This is not just git-mirroring, but include all the activities, issues, merge request, milestone, and wiki. It is not sync at specific time,

When ever new activities take place, the mirroring server will sync each other, and make all the nodes always up to date.

The open source development won't be affected if one of those server down.

It can make open source software development always available to every one in the world without affected by politics and situation.

**Comment by mscherer** [comment]
You might be interested in the work around [FedeProxy](https://fedeproxy.eu/) and [forgefed](https://forgefed.peers.community/), as well as all tickets tagged [federation](https://github.com/go-gitea/gitea/issues?q=is%3Aopen+is%3Aissue+label%3Atheme%2Ffederation).

**Comment by delvh** [comment]
Please have a look at https://github.com/go-gitea/gitea/issues?q=is%3Aopen+is%3Aissue+label%3Atheme%2Ffederation.
I think your proposal is already known.
If I understood the conversation correctly, one of the main features for Gitea 1.16 or 1.17 that are currently in development is exactly enabling federation between different (Gitea) instances.
Especially interesting for that might be #16827.

**Comment by lunny** [comment]
Please go to known issues to discuss further.
