### ISSUE TITLE
Gitea UI trimming white space

### ISSUE THREAD

**Issue by Jameshudson** [go-gitea/gitea#17099]
### Gitea Version

1.15.2

### Operating System

Ubuntu 20.04

### Browser Version

Chrome 93.0.4577.63

### Can you reproduce the bug on the Gitea demo site?

No

### Description

I'm not entirely sure what the issue is or if it is an interface bug. But all the repositories on my self hosted Gitea are missing spaces. I've attached a screenshot of the issue.

### Screenshots

Here's a screenshot from the Gitea UI

![Screenshot 2021-09-20 at 08 41 45](https://user-images.githubusercontent.com/2446151/133970045-2b4a32f6-4376-47f6-96af-a9ef88299c62.png)

and here is a screenshot from my IDE. Looks like Gitea has trimmed the whitespace for some reason

<img width="857" alt="Screenshot 2021-09-20 at 8 44 08 am" src="https://user-images.githubusercontent.com/2446151/133970361-8a19c43f-c14a-4113-8f8e-b3a243e64311.png">

**Comment by zeripath** [comment]
It's not Gitea.

It's Cloudfare.

You're using Cloudfare and you've got whitespace minimization on.

**Comment by Jameshudson** [comment]
> It's not Gitea.
> 
> It's Cloudfare.
> 
> You're using Cloudfare and you've got whitespace minimization on.

Thanks for getting back to me so quickly. This was the issue. I would have never thought of it
