### ISSUE TITLE
error 500 when creating new PR: git read-tree Develop: exit status 128 - error: invalid path

### ISSUE THREAD

**Issue by zuhairamahdi** [go-gitea/gitea#17092]
### Gitea Version

1.15.2

### Operating System

Windows

### How are you running Gitea?

In windows Server as windows process

### Database

MSSQL

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

2021/09/19 14:41:51 ...ers/web/repo/pull.go:1113:CompareAndPullRequestPost() [E] NewPullRequest: git read-tree Develop: exit status 128 - error: invalid path 'UCFS TAS'HEEL/Support Files/Assets.xcassets/Icon_NewWordAr.imageset/#New# Icon\Gold\new icons\new arabichdpi.png'

### Description

for some projects that have weird path 'created on linux and/or macOS' we keep getting error 500

**Comment by wxiaoguang** [comment]
It seems that the some filenames contain characters which make Windows filesystem unhappy.

Maybe you can try this first:

https://stackoverflow.com/questions/63727594/github-git-checkout-returns-error-invalid-path-on-windows

And it's highly recommended to use "valid" filenames in all platforms. Or you can run gitea in Linux, whose filesystem can contain almost every character.

**Comment by delvh** [comment]
> And it's highly recommended to use "valid" filenames for files in git on all platforms. Or you can run gitea in Linux, whose filesystem can allow almost every character in the filename.

Rule of thumb:
Use only limited ASCII for filenames (`0-9` `A-Z` `a-z` and `-._` as special signs). And **especially no spaces**, as those can lead to a myriad of other problems.
That prevents exactly those kinds of problems.

**Comment by wxiaoguang** [comment]
> Use only limited ASCII for filenames (`0-9` `A-Z` `a-z` and `-._` as special signs). And **especially no spaces**, as those can lead to a myriad of other problems.

Spaces are OK in modern days. If you have developed some macOS or iOS application, you will find that Apple recommends to use spaces in filenames.

**Comment by zuhairamahdi** [comment]
the issue is that I can see old pull requests worked just fine but once we upgraded to 1.15 we are getting this issue.

**Comment by zeripath** [comment]
it's interesting because I can't think of any changes to this area in 1.15.

**Comment by zeripath** [comment]
and the read-tree should not be looking at the filesystem at all.

**Comment by zeripath** [comment]
We could specifically add a `-i` to the command-line but there shouldn't be a working tree at all.

**Comment by zuhairamahdi** [comment]
> it's interesting because I can't think of any changes to this area in 1.15.
> 
> (In particular this call to read-tree has been present since #9302 in 1.11)

I think this might explain it. we upgraded from 1.10 to 1.14 and now to 1.15 where all the pull requests we made when we were using 1.10

**Comment by zeripath** [comment]
If you could would it be possible change this line:

https://github.com/go-gitea/gitea/blob/d4bb8e0ae7aa9bdd769a935770dfe7046d519313/services/pull/patch.go#L140

to:

```go
	_, err = git.NewCommand("read-tree", "-i", "base").RunInDir(tmpBasePath)
```

**Comment by zeripath** [comment]
@zuhairamahdi it really would be helpful if you could try the backport of #17102 to see if that fixes your problem. If you cannot build this yourself - please contact me.

**Comment by zuhairamahdi** [comment]
@zacheryph is this specific to gogit version? if we used the default package you think it might help?

**Comment by zeripath** [comment]
nope. It shouldn't be related to gogit.

I don't understand why the paths are being checked here. 

What version of git are you using?

**Comment by zuhairamahdi** [comment]
@zeripath 
git version 2.31.1.windows.1

I think you were able to replicate this issue earlier when you added "-i". I doubt its the git version that's causing this issue.

**Comment by zeripath** [comment]
It is related to the git version. (Well partially)

The issue is that you have core.protectNTFS on by default in these later versions, and is not allowing bad names to be even in the index. Setting:

```
git config core.protectNTFS false
```

Will stop the problem - but I am not certain how things would respond if a merge was required with this bad file as I know we may attempt to sparse check these out to do merges.

**Comment by zuhairamahdi** [comment]
@zeripath this still did not fix it. I run:
```sh
git config --global core.protectNTFS false
```
in the server but it is still no use.

**Comment by zeripath** [comment]
I suspect you've not got the right config file and so this setting is not taking effect.

**Comment by wxiaoguang** [comment]
The git config keys seems case-insensitive : https://git-scm.com/docs/git-config/2.14.6#_configuration_file

```
The variables are divided into sections ... The variable names are case-insensitive, ...
```

I also suspect the config are not set correctly on target git repository 😊

**Comment by zuhairamahdi** [comment]
@zeripath @wxiaoguang I tried to change the config file for the targeted repo and it still not having any impact, this is the config file:

```sh
[core]
	repositoryformatversion = 0
	filemode = false
	bare = true
	symlinks = false
	ignorecase = true
	protectNTFS = false

```

**Comment by zuhairamahdi** [comment]
@zeripath it is working now.
