### ISSUE TITLE
Webhooks are not delivered until gitea is restarted

### ISSUE THREAD

**Issue by xPaw** [go-gitea/gitea#171]
Log looks like this:
```
[Macaron] Started HEAD /xxx/xxx/hooks/trigger for xxx
[Macaron] Completed /xxx/xxx/hooks/trigger 302 Found in 133.298us
[Macaron] Started HEAD /user/login for xxx
[Macaron] Completed /user/login 404 Not Found in 744.64us
[Macaron] Started HEAD /xxx/xxx/hooks/trigger for xxx
[Macaron] Completed /xxx/xxx/hooks/trigger 302 Found in 126.234us
[Macaron] Started HEAD /user/login for xxx
[Macaron] Completed /user/login 404 Not Found in 463.373us
```

Then after restarting gitea:
```
2015/08/01 19:24:29 [T] Hook delivered(3d51aa67-2292-4733-a2b5-21a5abf3c34c): xxx
```

**Comment by vtolstov** [comment]
why i don't see this (i'm useing gitea master with drone master) and all hooks delivered fine.

**Comment by tboerger** [comment]
Need to dive into that, currently idk

**Comment by xPaw** [comment]
I am on `dev` branch. I just recompiled with latest commit, and it still doesn't deliver hooks.

**Comment by Unknwon** [comment]
gitea does not have real time webhook, so if you shutdown within 1min you trigger the hook, this could happen.

**Comment by vtolstov** [comment]
@Unknwon as i know gitea already pull this from gogs

**Comment by xPaw** [comment]
I've had gitea running for a couple of weeks and the hooks were never delivered.

**Comment by Unknwon** [comment]
@vtolstov no, it does not, at least not entirely as I can tell.

**Comment by tboerger** [comment]
@Unknwon i thought I have added all parts. Do you know what I'm missing? Got to review your changes one more time...

**Comment by Unknwon** [comment]
@tboerger https://github.com/go-gitea/gitea/blob/master/cmd/serve.go#L196 here should be a request to hook trigger

**Comment by tboerger** [comment]
@Unknwon thanks!
