### ISSUE TITLE
API returns strange things when getting `api/v1/repos/{owner}/{repo}/pulls/{index}.{any extensions except diff or patch}`

### ISSUE THREAD

**Issue by qwerty287** [go-gitea/gitea#17105]
### Gitea Version

1.16.0+dev-267-g5ac857f4d

### How are you running Gitea?

Built from source code

### Can you reproduce the bug on the Gitea demo site?

Yes

### Description

If I enter an URL like https://codeberg.org/api/v1/repos/gitnex/Gitnex/pulls/975.test, it returns a strange result, the PR with the number 139. It should return a 404 error.

**Comment by 6543** [comment]
looks like chi router do some unexpected magic ...

**Comment by lunny** [comment]
This is upstream related I think.

**Comment by a1012112796** [comment]
> https://codeberg.org/api/v1/repos/gitnex/Gitnex/pulls/975.test

The reason is that  `GET /repos/{owner}/{repo}/pulls/{index}` matched this link,
that's right. isn't it? but the indx is `975.test` which isn't a number. so `ctx.ParseInt64(":index")` will return 0.

But I wonder why can get value from database by `indx = 0` (`GetPullRequestByIndex()`) ?
/cc @lunny
