### ISSUE TITLE
milestone listing miss PRs 

### ISSUE THREAD

**Issue by fiurthorn** [go-gitea/gitea#1711]
- Gitea version (or commit ref): 1.1.1
- Git version: git version 2.13.0.windows.1
- Operating system: windows
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL) https://try.gitea.io/fiurthorn/fiurthorn/issues?state=open&milestone=51
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

Listing open task for a milstone only lists isses, the PRs are missing.
Found no Way to list all open task for a milestone.

## Screenshots

![image](https://cloud.githubusercontent.com/assets/13510039/25992751/ddfdfca0-3707-11e7-8d1c-124c3be7dfcf.png)

![image](https://cloud.githubusercontent.com/assets/13510039/25992762/e88436bc-3707-11e7-912d-40000b072eb1.png)

**Comment by appIeboy** [comment]
<p align=right><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup>#1798 @lunny @tboerger @sapk @cez81 @geek1011 @lafriks @ethantkoenig @andreynering @DblK </sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></p>
