### ISSUE TITLE
Click buttons quickly in some forms will submit repeated/duplicated requests

### ISSUE THREAD

**Issue by wxiaoguang** [go-gitea/gitea#17111]
### Description

All Gitea versions. Click buttons quickly in Issue form will submit repeated requests.

* https://try.gitea.io/wxiaoguang/test/issues/1#issuecomment-91921 
* And there are so many related issues ...

About UI/UX: because there is no UI feedback to users and the buttons are still clickable, when there is a laggy network, user may click buttons multiple times, then there will be many duplicated comments.

Related PRs (but it still needs more work)

* https://github.com/go-gitea/gitea/pull/16157 , it prevents the `create issue/pr` and `create comment` button  from double-clicked.
* https://github.com/go-gitea/gitea/pull/10459  , partially replaced by #16157

Remaining works:

* check and prevent repeated requests for other forms
* prevent repeated requests for AJAX requests

### Screenshots

<details>

![image](https://user-images.githubusercontent.com/2114189/145171000-0f31fa57-d4c9-4017-9691-0edb53a410b4.png)

</details>

NOTICE: This issue is not completely fixed. Some buttons have been fixed by https://github.com/go-gitea/gitea/pull/16157, but this issue is out-dated, so close it.

**Comment by delvh** [comment]
I would say that is the same error as #6859 on another form.
This seems to be a general submission problem.

**Comment by wxiaoguang** [comment]
If you like my idea about frontend refactor (https://github.com/go-gitea/gitea/pull/16770#discussion_r702322766 , introduce a general method to pass template variables, not relay one html `data` tag, split index.js into separated js files, etc), I can take this one.

**Comment by delvh** [comment]
Not a Gitea member (yet), but I do approve of it. I completely agree that things should be fixed once, not `n` times.

**Comment by lunny** [comment]
Spliting `index.js` is always welcome! And about the general method to pass template variables, any idea?

**Comment by silverwind** [comment]
I think a proper solution would be to interject all form submissions via JS, stop them and re-execute them via `fetch`. This can be used to prevent duplicate submission and more importantly enables to show a potential error message/toast without a page reload.

**Comment by wxiaoguang** [comment]
Some buttons have been fixed by #16157, this issue is out-dated, so close it.
