### ISSUE TITLE
cmd/web.go:91:func1() [F] PANIC: template: repo/header:48: function "MirrorAddress" not defined

### ISSUE THREAD

**Issue by XutaxKamay** [go-gitea/gitea#17114]
### Gitea Version

7ce938b

### Git Version

v1.15.3

### Operating System

Raspbian GNU/Linux 10 (buster)

### How are you running Gitea?

I'm running the release from github, gitea-linux-arm-6 with a systemd service.

### Database

MySQL

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/XutaxKamay/7cba85f8ecdab8bb6fb1ad42e563ca85

### Description

This is weird because I wasn't mirroring anything, it searches for a function called MirrorAddress but I feel like MirrorAddress is a variable/string?

This happened after an update of gitea, v1.4.x to v1.5.x, I even tried to delete my whole database and started from fresh, just to see if there was any possible conflicts and it does not seem to resolve the issue even by deleting the whole database. (I get the same panic message)

**Comment by lunny** [comment]
Have you use a custom template?

**Comment by zeripath** [comment]
There is no `MirrorAddress` function or call in the default templates provided with v1.15.3.

You appear to still have the template for 1.14.x.

You need to update your templates.

**Comment by XutaxKamay** [comment]
> Have you use a custom template?


> There is no `MirrorAddress` function or call in the default templates provided with v1.15.3.
> 
> You appear to still have the template for 1.14.x.
> 
> You need to update your templates.

Sorry for the late reply, yeah it was templates, I just didn't remember using custom templates.

Thank you.
