### ISSUE TITLE
Failed to initialize ORM engine: migrate: do migrate: pq: syntax error at or near "-"

### ISSUE THREAD

**Issue by Iced-Sun** [go-gitea/gitea#17120]
### Gitea Version

1.15.2

### How are you running Gitea?

[gitea helm-chart](https://gitea.com/gitea/helm-chart)-4.1.0

### Database

PostgreSQL

### Can you reproduce the bug on the Gitea demo site?

No

### Description

upgrade chart-4.0.3 to chart-4.1.0, the init pod raises with
```
gitea-0:configure-gitea 2021/09/22 13:01:54 ...s/migrations/v179.go:19:convertAvatarURLToText() [I] [SQL] alter table gitea-fbacaae.external_login_user ALTER COLUMN avatar_url TYPE TEXT [[] - 529.538µs
gitea-0:configure-gitea 2021/09/22 13:01:54 cmd/migrate.go:38:runMigrate() [F] Failed to initialize ORM engine: migrate: do migrate: pq: syntax error at or near "-"
```

Seems that orm doesn't quote the schema name of `gitea-fbacaae`.

**Comment by lunny** [comment]
This is an upstream related bug. Could you paste it to https://gitea.com/xorm/xorm/issues/new ?
