### ISSUE TITLE
How set upload file size for releases? 

### ISSUE THREAD

**Issue by typefile** [go-gitea/gitea#17127]
### Feature Description

# Do this:
file: `custom/conf/app.ini`
```
[repository.upload]
FILE_MAX_SIZE = 4096
MAX_FILES = 10
```
It was successful.
But, it's `Code` upload file size.

I want set `Release` upload file size, it limited to 4MB.

-----------------------------------------
Windows server
gitea 1.15.3
MS Sql Server

**Comment by wxiaoguang** [comment]
![image](https://user-images.githubusercontent.com/2114189/134452718-b8c4708a-edac-4c27-8328-1e03afda302d.png)

Maybe here?

```

[attachment]
;; Max size of each file. Defaults to 4MB
;MAX_SIZE = 4

```

**Comment by typefile** [comment]
> ![图片](https://user-images.githubusercontent.com/2114189/134452718-b8c4708a-edac-4c27-8328-1e03afda302d.png)
> 
> 也许在这里？
> 
> ```
> 
> [attachment]
> ;; Max size of each file. Defaults to 4MB
> ;MAX_SIZE = 4
> ```



Very thankful !
```
[attachment]
MAX_SIZE = 1024
```
