### ISSUE TITLE
Setting default branch is missing in API 

### ISSUE THREAD

**Issue by Salvador1994** [go-gitea/gitea#17128]
### Feature Description

Gitea Version: 1.15.3

I can't find the API that allows me to set the default branch, so what do I need to know if this feature has already been developed.

I await response, thank you!

**Comment by Joannazyx** [comment]
you can set the default branch when creating a new repo and init it
API path
/api/v1/admin/users/${owner}/repos
json body
{
  "auto_init": true,
  "default_branch": "master",
  "name": "${repo}"
}

**Comment by Salvador1994** [comment]
@Joannazyx 

We are developing a SaaS infrastructure and we don't do repository creation, we use the fork to register repositories

**Comment by aliencrash** [comment]
@noerw thanks that is helpful.

**Comment by Salvador1994** [comment]
@Joannazyx @noerw  thanks that your help, I solved the problem.
