### ISSUE TITLE
org snippet caused 500 internal server error

### ISSUE THREAD

**Issue by Iced-Sun** [go-gitea/gitea#17139]
### Gitea Version

1.15.2

### How are you running Gitea?

Helm chart.

### Can you reproduce the bug on the Gitea demo site?

Yes

### Description

A source block with `http` language modifier in org-mode file causes render failure with 500 internal server error for gitea-1.15.2. A demo is located at https://try.gitea.io/Iced-Sun/org/src/branch/master/test.org.

```
#+begin_src http
POST https://httpbin.org/post
Content-Type: application/json

{
  "foo": "bar"
}
#+end_src
```

It used to work on gitea-1.14.6 and before.

**Comment by zeripath** [comment]
Thank you for providing a test case, however the logs would have been helpful too.

**Comment by Iced-Sun** [comment]
Here is the relevant log:

```
2021/09/24 06:55:23 ...ers/web/repo/view.go:522:renderFile() [E] Render: orgmode.Render failed: could not write output: runtime error: index out of range [0] with length 0
```

**Comment by zeripath** [comment]
OK looks like there is a panic:

```go
			if _, err := w.WriteString(highlight.Code(lexer.Config().Filenames[0], source)); err != nil {
				return ""
			}
```

likely the `lexer.Config().Filenames` is empty.
