### ISSUE TITLE
Add option to delete repo if it is broken

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#17132]
If a repo is broken somehow. you will just see a 500 page without the option to delete it.

you can manually add `/settings` to go to repo settlings page to delete it, but most people don't know.

So I propose a button to directly delete it.

**Comment by delvh** [comment]
How do you break a repo in the first place?
I support your request, but I definitely wonder what you have to do to achieve that…

**Comment by 6543** [comment]
https://fosstodon.org/@5am/106979181347005295

It should not hapen ... but there is real world

**Comment by wxiaoguang** [comment]
Where should the link be put to, is there any recommended page/location?

**Comment by lunny** [comment]
You can delete it from admin panel currently.

**Comment by delvh** [comment]
Closed in #17747.
