### ISSUE TITLE
PR diff doesn't show removal correctly

### ISSUE THREAD

**Issue by toxyl** [go-gitea/gitea#17144]
### Gitea Version

1.14.2

### Git Version

2.17.1

### Operating System

Ubuntu 18.04.5 LTS (GNU/Linux 5.4.140-1-pve x86_64)

### How are you running Gitea?

Selfhosted using one of your downloads AFAIK (I'm not the sysadmin responsible). 

### Database

MySQL

### Can you reproduce the bug on the Gitea demo site?

No

### Description

When making a PR I noticed that the diff shown by Gitea does not match the reality. On the screenshot you can see that Gitea marked one value of the list as being removed, but in reality two values ("device_in_flow" and "device_drop_flow") were removed.

Please note that I haven't tested this on the demo site as I don't feel comfortable allowing access to my Github. 

### Screenshots

![Screenshot at 2021-09-24 16-29-30](https://user-images.githubusercontent.com/11501185/134695538-7dc0c2b8-c2df-4ba0-a8f8-7c719292aea4.png)

**Comment by techknowlogick** [comment]
The version of Gitea you are using is several versions out of date, please update to the latest stable and try again (1.15.3)

I will close this now, but if it is still the case please re-open.
