### ISSUE TITLE
Secret lost from push action webhook

### ISSUE THREAD

**Issue by PutinVladimir** [go-gitea/gitea#17147]
### Gitea Version

1.15.3

### Operating System

linux

### How are you running Gitea?

systemd

### Database

SQLite

### Can you reproduce the bug on the Gitea demo site?

No

### Description

v. 1.13.5 webhook post
```
{
  "secret": "somemysecret",
  "ref": "refs/heads/dev",
  "before": "2cc31c104faf46190774011c3d8ad169edf6ed0d",
  "after": "eb5237114f854320d3b545e4ab70c794f319cf21",
  "compare_url": "https://url/2cc31c104faf46190774011c3d8ad169edf6ed0d...eb5237114f854320d3b545e4ab70c794f319cf21",
  "commits": [
...
```

Now v. 1.15.3 webhook post
```
{
  "ref": "refs/heads/dev",
  "before": "868287009bb32192cef6ca2b0e69f6867104ca9e",
  "after": "7c3546dc92e724015d04c552deea9313798013d9",
  "compare_url": "https://url/868287009bb32192cef6ca2b0e69f6867104ca9e...7c3546dc92e724015d04c552deea9313798013d9",
  "commits": [
...
```

**Comment by zeripath** [comment]
https://blog.gitea.io/2021/08/gitea-1.15.0-is-released/#-webhook-refactors-16176httpsgithubcomgo-giteagiteapull16176

https://github.com/go-gitea/gitea/pull/16176

**Comment by zeripath** [comment]
It should not have been being sent in the first place - it's supposed to be secret.
