### ISSUE TITLE
Add deploy key should scroll down to the form

### ISSUE THREAD

**Issue by GhaziTriki** [go-gitea/gitea#17142]
### Gitea Version

1.15.0

### Operating System

Windows 10 Pro

### Browser Version

Firefox 92.0

### Can you reproduce the bug on the Gitea demo site?

Yes

### Description

When clicking on "Add Deploy Key" you have a long list of keys, the form is displayed at the most bottom and we have to manually scroll. The button should show the form and scroll to it without any additional efforts.

### Screenshots

![image](https://user-images.githubusercontent.com/4991088/134663579-ea66d993-20cd-46d1-8728-ad315b10ef1c.png)

**Comment by delvh** [comment]
I think a better approach would be to move the form before the list of already present keys.
That would solve this problem just as well as scrolling down automatically and can be implemented easier and less error-prone than the automatic scroll.
