### ISSUE TITLE
I can't change my email address, so I can't activate my account.

### ISSUE THREAD

**Issue by Neko7sora** [go-gitea/gitea#17148]
### Gitea Version

1.16.0+dev-248-g45ebcb0d1

### How are you running Gitea?

https://gitea.com/

The reason is that the Internet Service Provider used for the gitea.com server is blocking the Google domain. The Gmail domain that I use does not allow me to receive emails.

In the "Activate Your Account" state, my email cannot be changed and I cannot activate it.

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![image](https://user-images.githubusercontent.com/75793267/134754530-d36ead59-d676-4276-9618-29ef106dea80.png)

**Comment by techknowlogick** [comment]
@Neko7sora I just sent you an email to the email registered for that address. Please respond to it and I can activate your account.
