### ISSUE TITLE
%!s() instead of repo name in email

### ISSUE THREAD

**Issue by lakostin** [go-gitea/gitea#17160]
### Gitea Version

1.15.0

### Git Version

2.30.2

### Operating System

docker Alpine Linux v3.13

### How are you running Gitea?

docker

### Database

PostgreSQL

### Can you reproduce the bug on the Gitea demo site?

Yes

### Description

@denis.patrakeev assigned you to the pull request #106 in repository %!s().

---
View it on Gitea: Git with a cup of tea.

### Screenshots

![image](https://user-images.githubusercontent.com/29179059/134818137-a7961c1d-e13d-43ae-852a-3f233ad47339.png)

**Comment by axifive** [comment]
Don't you have [custom templates](https://docs.gitea.io/en-us/mail-templates/) in your `$GITEA_CUSTOM/templates/mail` directory?
https://docs.gitea.io/en-us/customizing-gitea/#customizing-gitea-mails

**Comment by lakostin** [comment]
> Don't you have [custom templates](https://docs.gitea.io/en-us/mail-templates/) in your `$GITEA_CUSTOM/templates/mail` directory?
> https://docs.gitea.io/en-us/customizing-gitea/#customizing-gitea-mails

no

**Comment by zeripath** [comment]
Is this in the English emails or a different language?

Looking at some of our translations I can see that the related string is incorrect in a number of them.

The related string is: `mail.issue_assigned.pull`

https://github.com/go-gitea/gitea/blob/122917f4d54f47c11f1453115aed7558637095ae/options/locale/locale_en-US.ini#L348

The related template is `mail/issue/assigned.tmpl`.

https://github.com/go-gitea/gitea/blob/122917f4d54f47c11f1453115aed7558637095ae/templates/mail/issue/assigned.tmpl#L11-L16

Both the template and locale string appear correct for English in 1.15.

**Comment by silverwind** [comment]
Noticed the same problem on issue as well:

````
@username assigned you to the issue #1 in repository %!s().
```
