### ISSUE TITLE
Setting to disable/enable autofocus of search fields

### ISSUE THREAD

**Issue by rebeka-catalina** [go-gitea/gitea#17162]
### Feature Description

I think it would be great if gitea had a setting to provide control over autofocus of search fields on server level and user level. There are quite a few search fields - for example on `explore/users/` and I personnally don't like it if these are focused automatically. Each time I visit a page that contains a search field I have to press `esc` first before I can go on.
To avoid this I just grep-ed the templates for autofocus, copied each to `custom/` and removed the autofocus attribute. Of course this works and I have a gitea instance with only few users, but this way I would have to keep an eye on the templates always because if changes happen (updated versions of templates provided by the gitea devs) then I have to change them and remove the autofocus again from each.
And the other point is that I think that it would be nice if users could choose a behavior for this in their own settings, because... well, I think there are for sure people who have exactly opposite feelings and find it annoying if they always have to click there manually.

I think it would be nice to have an ability to control this in the settings and would be very happy if there would be a way to implement it :-)

**Comment by wxiaoguang** [comment]
> "Each time I visit a page that contains a search field I have to press esc first before I can go on."

Can you explain why you need to press ESC?

And for your customization, you can just write a JavaScript file and inject to the base template, then you can control everything you like, eg: auto remove focus when page is loaded. And you do not to update all templates again and again.

**Comment by rebeka-catalina** [comment]
On 2021.09.26, wxiaoguang wrote:
> > "Each time I visit a page that contains a search field I have to press esc first before I can go on."
> 
> Can you explain why you need to press ESC?

Sure:
I control my browser with keyboard and vim-like bindings and if the search field
is focused then instead of controlling my browser letters get inserted into the
search field, so I have to hit `esc` first to be able to control my browser
again. Each time I visit a page with a search field with autofocus.

> And for your customization, you can just write a JavaScript file and inject to the base template, then you can control everything you like, eg: auto remove focus when page is loaded. And you do not to update all templates again and again.

I don't know how JavaScript works and how I could write such a script :-/

**Comment by wxiaoguang** [comment]
The JavaScript looks like this:

```js
$(function() {
    if ($('[autofocus]').length) {
        document.activeElement.blur();
    }
});
```

I think we can close this issue because it's difficult to satisfy everyone's need and it's not worthy to introduce more settings.

**Comment by rebeka-catalina** [comment]
> The JavaScript looks like this:
> 
> ```js
> $(function() {
>     if ($('[autofocus]').length) {
>         document.activeElement.blur();
>     }
> });
> ```
> 
> I think we can close this issue because it's difficult to satisfy everyone's need and it's not worthy to introduce more settings.

Thank you. I think so, too - yes. Can't currently test if it works, because for
some reason gitea crashes if I put the footer.tmpl into custom/base/ - even the
original one makes it crash... I don't know why - but that's a differnt thing.

Thanks for the script! :-)
