### ISSUE TITLE
key exhange negotiation failed though client and server share some protocols

### ISSUE THREAD

**Issue by rockmenjack** [go-gitea/gitea#17175]
### Gitea Version

1.15.3

### Git Version

2.33.0

### Operating System

CentOS 7

### How are you running Gitea?

After a openssh client upgrade, push to gitea

### Database

SQLite

### Can you reproduce the bug on the Gitea demo site?

No

### Description

using built-in SSH server with below config:
```ini
[server]
SSH_SERVER_CIPHERS      = aes128-ctr aes192-ctr aes256-ctr aes128-gcm@openssh.com arcfour256 arcfour128
SSH_SERVER_KEY_EXCHANGES = curve25519-sha256 diffie-hellman-group1-sha1 diffie-hellman-group14-sha1 ecdh-sha2-nistp256 ecdh-sha2-nistp384 ecdh-sha2-nistp521 curve25519-sha256@libssh.org ssh-rsa
```

both client and server have common algorithm, but report `no common algorithm for key exchange`
```txt
2021/09/29 10:46:19 modules/ssh/ssh.go:259:sshConnectionFailed() [W] Failed connection from 10.118.13.125:50358 with error: ssh: no common algorithm for key exchange; 
client offered: [curve25519-sha256 curve25519-sha256@libssh.org ecdh-sha2-nistp256 ecdh-sha2-nistp384 ecdh-sha2-nistp521 diffie-hellman-group-exchange-sha256 diffie-hellman-group16-sha512 diffie-hellman-group18-sha512 diffie-hellman-group14-sha256 ext-info-c], 
server offered: [curve25519-sha256 diffie-hellman-group1-sha1 diffie-hellman-group14-sha1 ecdh-sha2-nistp256 ecdh-sha2-nistp384 ecdh-sha2-nistp521 curve25519-sha256@libssh.org]
```

**Comment by 6543** [comment]
@rockmenjack `1.5.3` is quite old - we can not hunt down the issue on this version - its ancient

please upgrade to latest stable 1.**1**5.3

**Comment by rockmenjack** [comment]
> @rockmenjack `1.5.3` is quite old - we can not hunt down the issue on this version - its ancient
> 
> please upgrade to latest stable 1.**1**5.3

Oh, that was a typo, I was supposed to mean **1.15.3**

**Comment by synaptiko** [comment]
I'm not sure if it's related but after the upgrade I started getting:
```
Unable to negotiate with XYZ port 22: no matching host key type found. Their offer: ssh-rsa
fatal: Could not read from remote repository.
```

I'm also using built-in SSH server and I didn't configure neither `SSH_SERVER_KEY_EXCHANGES` nor `SSH_SERVER_CIPHERS` previously, so I suppose it uses defaults.

**Comment by neonmoe** [comment]
I'm having the same issue as @synaptiko above. Adding `HostkeyAlgorithms ssh-rsa` to my `~/.ssh/config` for the host fixed the host key type problem, but my keys don't work. Seems like the internal ssh server just isn't working as it used to.

**Comment by idanoo** [comment]
Looks like the same issue as here

https://github.com/gogs/gogs/issues/6623

**Comment by simonvik** [comment]
Probably https://github.com/golang/go/issues/37278

**Comment by nougad** [comment]
Workaround is to specify SSH parameter in `~/.ssh/config`:

```
Host mygiteahost.com
	Port 2222
	HostKeyAlgorithms +ssh-rsa
	PubkeyAcceptedAlgorithms +ssh-rsa
	User gitea
```

**Comment by dogtopus** [comment]
Apparently `ssh-rsa` host key algorithm (and apparently also the signature algorithm) was [declared deprecation](https://levelup.gitconnected.com/demystifying-ssh-rsa-in-openssh-deprecation-notice-22feb1b52acd) a year ago and it finally has an effect.

**Comment by zeripath** [comment]
Oh damn - this is going to be annoying and difficult to fix.

Fundamentally there is a problem in the way that Go's x/crypto/ssh library does the handshake.

**Comment by zeripath** [comment]
@Poyoman39 the attached PR will solve the issue.

**Comment by kaedr** [comment]
For people looking for a workaround way to fix this on their server without people having to make changes to `~/.ssh/config` on the client end:
If you manually generate and ED25519 keypair `ssh-keygen -t ed25519` and  reference them with the `SSH_SERVER_HOST_KEYS` setting in `app.ini` it will force a better signature algorithm based on said key type.

IMO, it's worth looking at moving to ED25519 or another elliptic curve algorithm as the default for Gitea, as RSA is getting closer to being totally broken all the time.

**Comment by G2G2G2G** [comment]
My company's entire ed25519 keys stopped working lmao

**Comment by dogtopus** [comment]
> The easiest solution is just generating an ed25519 and pointing to it, takes <10 seconds

Yes but if you got a bunch of different clients connected to the server it would be a PITA to update them all to use the new public key. Although adding back RSA SHA1 on every machine is not ideal either.

**Comment by G2G2G2G** [comment]
Yep, ed25519 is something that should have been defaulted ~10 years ago. My entire office has to delete their known_hosts line now and accept the new key. Not really that big of a deal.

**Comment by grisu48** [comment]
For anyone who ends up here, here is how you can easily switch over to ed25519.

## Use ed25519 on the gitea side

Add `SSH_SERVER_HOST_KEYS = ssh/gitea.ed25519` to your `app.ini`:

    SSH_SERVER_HOST_KEYS     = ssh/gitea.ed25519

Don't bother setting `SSH_SERVER_CIPHERS`, `SSH_SERVER_KEY_EXCHANGES` and `SSH_SERVER_MACS`, that is not necessary. However, in case you find it necessary to do so, please consult `man sshd_config` and `ssh -Q cipher|key|key-sig`.

In case the keys don't get generated automatically, move to the `ssh` directory in your gitea data dir and generate the keys manually:

    cd /var/gitea/ssh             # Change to your needs
    ssh-keygen -t ed25519 -f gitea.ed25519

Then restart gitea, and look for the following entry in the log

    2021/10/19 07:11:14 modules/ssh/ssh.go:312:Listen() [I] Adding SSH host key: /data/gitea/ssh/gitea.ed25519

Perhaps the [gitea config cheat sheet](https://docs.gitea.io/en-us/config-cheat-sheet/) is useful, if the above stated suggestions don't work for you and you need to dive deeper into the configuration options.

## Force ssh to use ed25519 for your gitea server

In my case the above stated steps were enough to fix the issue. If for some reason, you ssh needs to be forced to use ed25519, then see the following template for your `~/.ssh/config` file

    HOST gitea.local gitea
        HOSTNAME gitea.local
        PreferredAuthentications publickey
        IdentityFile ~/.ssh/id_ed25519
        IdentitiesOnly yes
