### ISSUE TITLE
It is  possible to reopen merged PRs via API

### ISSUE THREAD

**Issue by qwerty287** [go-gitea/gitea#17180]
### Gitea Version

(almost) latest main

### How are you running Gitea?

Built from source, from cli

### Can you reproduce the bug on the Gitea demo site?

Yes

### Description

It is possible to reopen merged prs via the api endpoint. This should be impossible

**Comment by delvh** [comment]
Could you please clarify which endpoint you mean?
Because I just had a quick glance at https://try.gitea.io/api/swagger, and I have no idea which endpoint might be responsible for this.

**Comment by 6543** [comment]
yes it is - if it's not working we need more infos&logs:
1. what specific endpoints do you rever to?
2. what gitea do print out in debug mode
3. what response the api return (body & header & status)

**Comment by noerw** [comment]
I get the urge for detailed bug reports, but in this case it's just needless bureaucracy.. I was easily able to spot the problem here right away 🤔

**Comment by qwerty287** [comment]
> it's this request https://try.gitea.io/api/swagger#/repository/repoEditPullRequest

Yes, it is, and it is probably the same (not tested) here: https://try.gitea.io/api/swagger#/issue/issueEditIssue

**Comment by qwerty287** [comment]
@6543 it's the same if I reopen a closed issue or PR - status code is 201, and the answer is the pull request.
