### ISSUE TITLE
Render scoped labels

### ISSUE THREAD

**Issue by anbraten** [go-gitea/gitea#17189]
### Feature Description

Show scoped labels by using some kind of separator like: `/` or `::` and show them as the following example of Gitlab:

### Screenshots

Gitea uses some kind of scoped labels on Github:
![Screenshot from 2021-09-30 08-12-20](https://user-images.githubusercontent.com/6918444/135397237-0c82f13d-246e-4b64-a852-dab4af14f803.png)

Gitlab supports scoped labels by writing: `scope::label name`:
![Screenshot from 2021-09-30 08-14-15](https://user-images.githubusercontent.com/6918444/135397495-2884ffe8-23de-4d38-bf73-8b0847a28cb3.png)

**Comment by delvh** [comment]
While I can absolutely understand this request, I don't know how well that would integrate into the existing theme mechanism…
I mean: Should themes be able to customize the appearance of such a scoped label?
If it should: How are themes supposed to know which color to convert to automatically?
If it shouldn't: Well, some labels might then be almost invisible in in some themes…

**Comment by anbraten** [comment]
I suggest the yellow color in this example could be the current label color and the body bg-color (`white`) and text-color (`black`) could be defined by the theme. Having some sort of support for dark-mode colors for labels seems to be a different issue to me: #16728

**Comment by techknowlogick** [comment]
on github our labels are literally `something/something` which can be used already in gitea.

**Comment by anbraten** [comment]
@techknowlogick Doesn't seem to work for me on `1.15.3`. Could you link a PR?

![Screenshot from 2021-10-02 08-02-20](https://user-images.githubusercontent.com/6918444/135705543-08bac27e-4a59-4f11-927e-af3df4a65e9e.png)

**Comment by delvh** [comment]
@techknowlogick if I see that correctly, there is a misunderstanding between you two:
@techknowlogick, I think you mean that **Gitea does not disallow a `/` inside labels**, which is indeed correct.
A label `test/label` can be used in Gitea.
@anbraten, however, most likely wants a visual difference for the main part, so that `test` and `label` will be displayed with a separate UI styling, Gitlab-like.

**Comment by sebastian-sauer** [comment]
Here's a link to gitlabs docs: 

https://docs.gitlab.com/ee/user/project/labels.html#scoped-labels

**Comment by delvh** [comment]
There are three things I would like to clarify after reading the GitLab docs:
If I see that correctly, you only want to display those labels differently, right?
a) That means you (for now) don't want a check to ensure that at most one scoped label with the same scope is present for one issue, right?
b) How are multi-scope labels rendered? The GitLab documentation mentions them but does not show them. And (how) should Gitea support multi-scope labels?
c) Which separator? `::` to conform with Gitlab, or the style used inside this project (`/`)?

**Comment by anbraten** [comment]
a) for now I am only interested in the UI enhancement. Any additional logic could be nice but would need some additional proposal
b) I would ignore them for now. So the first separator would be used to split the label name and all following ones would be ignored. Just tired Gitlab and it seems they only use the last separator and ignore previous ones.
b) I first thought it would be nice to just use `/` as Gitea does it already, but I think a single char like `/` should not be used as it is not very special and could potentially cause bad UX. There are probably users using `/` with its `or` meaning and `//` could be part of a url, so I think `::` would fit best.

**Comment by bryanpedini** [comment]
Thank you @wxiaoguang for pointing out this to me.

I would like to reply to @delvh c) point too: I would prefer `::` since it's the same as GitLab and already existing bots and scripts would be able to switch easily between the two platforms.

**Comment by lunny** [comment]
duplicated with #13117.
