### ISSUE TITLE
[API] `/repos/{owner}/{repo}/pulls/{index}` returns `false` for all permissions of the base/head branch repo

### ISSUE THREAD

**Issue by qwerty287** [go-gitea/gitea#17181]
### Gitea Version

(almost) latest main

### How are you running Gitea?

Built from source, from cli

### Can you reproduce the bug on the Gitea demo site?

Yes

### Description

If I get a PR via the API, it returns the pull's head/base branch. The repos that are included in these information also return the permissions, but all values of these permissions (`admin`, `push`, `pull`) are `false`.

**Comment by noerw** [comment]
can confirm with 1.14.7 and current main
