### ISSUE TITLE
Add GITEA_REPO_MEMBERS_EMAILS env key for hooks

### ISSUE THREAD

**Issue by ivptr** [go-gitea/gitea#17199]
### Feature Description

It would be nice to add GITEA_REPO_MEMBERS_EMAILS environment key, containing emails of all users having access to repository (collaborators, owners and its team members).

That way it would be possible to send email notifications about commits to all involved parties, as mentioned in #1457.

**Comment by zeripath** [comment]
Which kind of hook do you mean here? a githook?

**Comment by wxiaoguang** [comment]
Another question, what is the purpose of "sending email notifications about commits"? In old days people liked to know the committing actions, but as today, the code repository becomes larger and larger, most people do not care about every trivial commit anymore.

I also do not think passing emails via environment is a good idea. Think about you have a large org contains more than a thousand users, the environment will be filled by a lot of emails which are not very useful.

**Comment by ivptr** [comment]
This feature request is in line with explanation for `post-receive` Git hook:
https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks
"The post-receive hook runs after the entire process is completed and can be used to update other services or **notify users**":

I just want to notify all users having access to repository (collaborators, owners and its team members).

Is there another way to fetch such emails if GITEA_REPO_MEMBERS_EMAILS environment key is a no go? Maybe calling `/usr/local/bin/gitea` using some param?

**Comment by wxiaoguang** [comment]
Gitea has API: https://try.gitea.io/api/swagger#/repository/repoListCollaborators

**Comment by ivptr** [comment]
API seems to be overkill for this, it needs ENABLE_SWAGGER enabled and authorization.

Is it possible to get such data using Gitea command line, similar to `/usr/local/bin/gitea -c /etc/gitea/app.ini admin user list`
