### ISSUE TITLE
Webhooks only work for branch filter "*" or "master" in private repositories

### ISSUE THREAD

**Issue by argentini** [go-gitea/gitea#17200]
### Gitea Version

1.15.3, 1.16.0

### Git Version

2.33.0

### Operating System

Windows Server 2016

### How are you running Gitea?

Service

### Database

MSSQL

### Can you reproduce the bug on the Gitea demo site?

Yes

### Description

Create a private repository, add a branch other than master, make a Gitea "push" webhook and filter it on the new branch. When you test the webhook nothing appears in the history and it won't get triggered by a push. Then change the branch filter to "*" or "master" and it will work.

**Comment by kanocz** [comment]
+1 webhooks works only for master branch :(

**Comment by kanocz** [comment]
downgrade to 1.5.0-rc1 (where everything worked before) doesn't help :(

**Comment by kanocz** [comment]
fresh install just fixed everything for me :thinking:

**Comment by jbaez** [comment]
Same issue here after a version update. Currently on docker image `gitea/gitea:1.15.3`
Trigger on `Push events` and  filter set for `dev` branch.
Submitting a "Test Delivery"
Logs:
```
2021/10/04 09:22:56 Started POST /[RepoOwner]/[Repo]/settings/hooks/7/test for 10.10.11.67:64257
2021/10/04 09:22:56 ...s/webhook/webhook.go:147:prepareWebhook() [I] Branch "[default-branch]" doesn't match branch filter "dev", skipping
```

Additionally, after the update this same filter is not filtering out tags push events. This is the content from the "Recent deliveries" for this webhook:
`X-Gitea-Event: push`
```
{
  "ref": "refs/tags/[some-tag]",
  "before": "0000000000000000000000000000000000000000",
  "after": "asdfas934297f1c8e7dd88acec022773f7ba2f43",
  "compare_url": "https://git.repo-owner-com/",
  "commits": [],
  "head_commit": null,
 ...
}
```

**Comment by zx9597446** [comment]
same issue here
version: 1.16.2

2022/03/03 12:41:21 ...s/webhook/webhook.go:154:prepareWebhook() [I] Branch "master" doesn't match branch filter "develop", skipping
2022/03/03 12:42:08 ...s/webhook/webhook.go:154:prepareWebhook() [I] Branch "master" doesn't match branch filter "*/develop", skipping
2022/03/03 12:43:15 ...s/webhook/webhook.go:154:prepareWebhook() [I] Branch "master" doesn't match branch filter "develop", skipping
2022/03/03 12:46:54 ...s/webhook/webhook.go:154:prepareWebhook() [I] Branch "master" doesn't match branch filter "*develop*", skipping
2022/03/03 12:47:59 ...s/webhook/deliver.go:55:Deliver() [I] HTTP Method for webhook 86 empty, setting to POST as default
2022/03/03 12:48:51 ...s/webhook/webhook.go:154:prepareWebhook() [I] Branch "master" doesn't match branch filter "{develop}", skipping
2022/03/03 12:52:32 ...s/webhook/webhook.go:154:prepareWebhook() [I] Branch "master" doesn't match branch filter "dev*", skipping

**Comment by foto-andreas** [comment]
Is there any workaround or fix?

**Comment by lunny** [comment]
I couldn't reproduce this problem.

**Comment by foto-andreas** [comment]
I could reproduce the problem with the gitea jenkins plugin. But the situation showed up as follows: Gitea sends the hook when I use ```{master,branchname}``` but not when using the advanced RE syntax ```(master|branchname)```. But the jenkins gitea plugin ignored everything which was not pushed to master. Maybe this was a configuration error in Jenkins. Now I am using the "General-Webhooks Plugin" in Jenkins und everything seems to work. Public or private setting of repo is not relevant here.

**Comment by lunny** [comment]
> I could reproduce the problem with the gitea jenkins plugin. But the situation showed up as follows: Gitea sends the hook when I use `{master,branchname}` but not when using the advanced RE syntax `(master|branchname)`. But the jenkins gitea plugin ignored everything which was not pushed to master. Maybe this was a configuration error in Jenkins. Now I am using the "General-Webhooks Plugin" in Jenkins und everything seems to work. Public or private setting of repo is not relevant here.

But it only supports glob match not RE.

**Comment by foto-andreas** [comment]
Ah ok, I thought the link to the glob syntax documentation implied that gitea also supports the advanced syntax documented there.

Thank you
Andreas

**Comment by lunny** [comment]
Please feel free to reopen it if you can have reproducible steps.
