### ISSUE TITLE
Message-ID header missing in follow-up email notifications

### ISSUE THREAD

**Issue by mxmehl** [go-gitea/gitea#17203]
### Gitea Version

1.15.3

### Git Version

2.30.2

### Operating System

Debian 10

### How are you running Gitea?

Binary packages running via systemd

### Database

MySQL

### Can you reproduce the bug on the Gitea demo site?

Yes

### Description

The first notification mail of an issue or pull request contains a valid `Message-ID` header, e.g. `Message-ID: <fsfe-system-hackers/baseline/issues/10@git.fsfe.org>`.

However, all following mails do not carry this header for some reason. This is bad because it does not conform with RFC 5322, and spam filters often downrate it or even not not let it pass (in RSPAMD: `MISSING_MID(2.5)`).

Not sure whether it relates to #13065.

**Comment by KN4CK3R** [comment]
> However, all following mails do not carry this header for some reason.

The reason is the comment
`// Set Message-ID on first message so replies know what to reference`
but that's wrong. Will be fixed with #17206.
