### ISSUE TITLE
Gitea API /admin/orgs return only public organizations

### ISSUE THREAD

**Issue by bawk3** [go-gitea/gitea#17215]
### Gitea Version

1.15.0-rc2

### How are you running Gitea?

Self-hosted Gitea, running from binary downloaded from https://github.com/go-gitea/gitea/releases as system service.

### Database

PostgreSQL

### Can you reproduce the bug on the Gitea demo site?

No

### Description

Gitea API started to return only public organizations.
API token belongs to Admin privileged user. Tried out on different users with admin privileges.

Here is the response of gitea API /admin/orgs
```
[
  {
    "id": 1161,
    "username": ***,
    "full_name": "",
    "avatar_url": ***,
    "description": "",
    "website": "",
    "location": "",
    "visibility": "public",
    "repo_admin_change_team_access": true
  },
  {
    "id": 2317,
    "username": ***,
    "full_name": "",
    "avatar_url": ***,
    "description": "",
    "website": "",
    "location": "",
    "visibility": "public",
    "repo_admin_change_team_access": false
  },
  {
    "id": 2319,
    "username": ***,
    "full_name": "",
    "avatar_url": "***,
    "description": "",
    "website": "",
    "location": "",
    "visibility": "public",
    "repo_admin_change_team_access": false
  }
]
```

### Screenshots

![orgs_gui](https://user-images.githubusercontent.com/43581101/135831385-80241e21-213a-4f42-bde4-3214be6eb7c5.png)

**Comment by techknowlogick** [comment]
Please report issues using the latest stable version (1.15.3), as issues may be fixed otherwise. As you have reported unable to repeat with try.gitea.io the issue may have indeed been completed. Please re-open issue once updating if you are able to repeat.
