### ISSUE TITLE
Validate commiter e-mail

### ISSUE THREAD

**Issue by laurivosandi** [go-gitea/gitea#17217]
### Feature Description

Not sure if this is doable with reasonable effort, but it would be nice if Gitea could reject commits pushed with unknown e-mail alias. This would force the user to run `git config` or add the e-mail alias under their account

**Comment by techknowlogick** [comment]
We recommend requiring signed commits instead. Rejecting comments pushed with an unknown alias wouldn't work directly because you my push commits authored by someone else, and this would reject that even if they are "valid" emails.
