### ISSUE TITLE
Wrong avatar in history/commit line

### ISSUE THREAD

**Issue by artemanufrij** [go-gitea/gitea#17230]
### Gitea Version

1.15.3

### Operating System

Docker-Image (last)

### How are you running Gitea?

Run it in a docker container on an archlinux server

### Database

MySQL

### Can you reproduce the bug on the Gitea demo site?

Yes

### Description

I set a custom image for my profile. Now gitea shows wrong image on commit/history page (see screenshot)

### Screenshots

![image](https://user-images.githubusercontent.com/16517095/136079652-d823f1db-d3e5-4aaa-b2fa-24c26e0dd98a.png)

**Comment by jpraet** [comment]
Does the user.email in your git config match the email adress of your gitea account?

**Comment by artemanufrij** [comment]
> Does the user.email in your git config match the email adress of your gitea account?

No, i use github gitlab and gitea on same machine with different emails-accounts. Is it possible to configure an email explicite for gitea?

**Comment by artemanufrij** [comment]
If I use email-account instead of username, then it works as expected.
