### ISSUE TITLE
docker compose file to install gitea with mysql?

### ISSUE THREAD

**Issue by yigalirani** [go-gitea/gitea#17259]
### Feature Description

i see something similar at 
https://docs.gitea.io/en-us/install-with-docker/

but it have these green plus sign that i would have to remove myself
sorry for bravity

### Screenshots

![green_signs](https://user-images.githubusercontent.com/1817381/136444546-5ecdfc6f-bfc9-413a-b66b-2e13a4c5efe2.png)

**Comment by techknowlogick** [comment]
The + are from using the diff format showing what you would add to a docker compose file. You can find exactly what you'd like on the exact same page you found the above: https://docs.gitea.io/en-us/install-with-docker/#mysql-database

In the future please don't use feature requests for support requests. This is what chat and the forum are for.
