### ISSUE TITLE
UserSignIn: Non-200 response from UserInfo: 401, WWW-Authenticate=Bearer error="invalid_token"

### ISSUE THREAD

**Issue by TobiasS1402** [go-gitea/gitea#17268]
### Gitea Version

1.15.3

### Git Version

2.32.0

### Operating System

Gitea 12.2-RELEASE-p6 FreeBSD 12.2-RELEASE-p6 df578562304(HEAD) TRUENAS  amd64

### How are you running Gitea?

Running Gitea via the TrueNAS community plugin in the IOcage jails.

### Database

PostgreSQL

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/TobiasS1402/18f2b47430c3bc1254319bc3ec09dab7

### Description

I have set up ADFS via OpenID but i get an error 500 when trying to authorize.
Followed this guide for setting op OpenID with ADFS: https://wiki.resolution.de/doc/openid-oauth-authentication/latest/setup-guides/adfs-setup-guide.

**Claims**
- Name ID
- email
- preferred_username
- name

**Callback URL**
- https://git.intranet.xxxx.xxxx/user/oauth2/ADFS/callback

### Screenshots

![Gitea_ADFS](https://user-images.githubusercontent.com/46230851/136547701-c288089c-3845-4850-bf86-1ae4014efb6c.png)
![ADFS_server-application](https://user-images.githubusercontent.com/46230851/136547945-c943f7d1-6d07-494a-afc7-bd8f758591fa.png)
![ADFS_web-api](https://user-images.githubusercontent.com/46230851/136548069-3695a94f-a392-4938-b561-cd1953eb2546.png)
![claim_rules](https://user-images.githubusercontent.com/46230851/136548271-9e14f1a8-3d28-49f4-a801-bb0d263476cb.PNG)

**Comment by zeripath** [comment]
**Please do not routinely set STACKTRACE_LEVEL it is generally unhelpful and obscures issues. Go is not Java the errors returned are not exceptions - they do not come with embedded stacktraces.**

---

I suspect that your secret/clientID pair is incorrect. The rest of your error tells you more:

 UserSignIn: Non-200 response from UserInfo: 401, WWW-Authenticate=Bearer error="invalid_token", error_description="MSIS9921: Received invalid UserInfo request. Audience 'microsoft:identityserver:907cc825-492c-40cc-8c9e-8316954b5f07' in the access token is not same as the identifier of the UserInfo relying party trust 'urn:microsoft:userinfo'."

**Comment by TobiasS1402** [comment]
@zeripath 
I thought that i had tried tried renewing the secret, so i re-created the ADFS Application and rolled-over the secret and client id. This worked.

Thank you.
