### ISSUE TITLE
How do reference the image files generated by external renders?

### ISSUE THREAD

**Issue by lihanglin** [go-gitea/gitea#17276]
### Gitea Version

1.14.5

### Git Version

2.17.0

### Operating System

CentOS Linux release 7.9.2009

### How are you running Gitea?

Use the official release

### Database

SQLite

### Can you reproduce the bug on the Gitea demo site?

No

### Description

I did not find any tips in FAQ or documents.
Please allow me to post this question here.

I enabled the external render "asciidoctor" in Gitea to support to display *.adoc file in WEB directly.
Everything is fine but the image file.
There are wavedrom diagrams in some *.adoc files and asciidoctor would convert and generate the *.svg files when you browsed the *.adoc file each time.

The svg files cannot be referenced or fond in WEB page.
The HTML in my Gitea page is like as below to show 404 error (image not found)

```html
<div>
<img src="/$USER/$REPO/media/branch/master/dir/diag-892f37f776e5e3e93dd838003910a66a.svg" alt="Diagram" width="819" height="520"/>
</div>
``` 

There are no "/$USER/$REPO/media/branch/master/" directory path in my server.

The generated image file is put at $AppPath where gitea binary located.
How do I set up the Gitea to reference the files generated by asciidoctor?

Thanks.

**Comment by zeripath** [comment]
What is your `[markup]` config?

**Comment by lihanglin** [comment]
Hi @zeripath 

My markup config as below

```ini
[markup.sanitizer.1]

; The following keys can appear once to define a sanitation policy rule.
; This section can appear multiple times by adding a unique alphanumeric suffix to define multiple rules.
; e.g., [markup.sanitizer.1] -> [markup.sanitizer.2] -> [markup.sanitizer.TeX]
; ELEMENT = span
; ALLOW_ATTR = class
; REGEXP = ^(info|warning|error)$

[markup.asciidoc]
ENABLED         = true
; List of file extensions that should be rendered by an external command
FILE_EXTENSIONS = .adoc,.asciidoc
; External command to render all matching extensions
RENDER_COMMAND = "/srv/gitea/custom/renders/asciidoctor"
; Don't pass the file on STDIN, pass the filename as argument instead.
IS_INPUT_FILE   = false
```

I have a wrapper for asciidoctor to preset some attribute
/srv/gitea/custom/renders/asciidoctor
```bash
/usr/local/bin/asciidoctor -s -r asciidoctor-diagram -a showtitle -a allow-uri-read -a wavedrom-format=svg -a diagram-svg-type=inline --out-file=- -
```

**Comment by lihanglin** [comment]
Hi @zeripath 

It's much clear to me about the failure I hit.
Thanks.
