### ISSUE TITLE
Can't add new WeChatWork webhook into Organization

### ISSUE THREAD

**Issue by zhu0629** [go-gitea/gitea#17279]
### Gitea Version

1.16.0+dev-339-gee73d8409 

### How are you running Gitea?

docker

### Database

SQLite

### Can you reproduce the bug on the Gitea demo site?

No

### Description

http://host/org/ORGNAME/settings/hooks/wechatwork/new

**Comment by wxiaoguang** [comment]
I have tried the page (/org/repo/settings/hooks/wechatwork/new), it can add a wechat work webhook into the repository.

You need to describe your problem more clearly. What errors do you meet? How to reproduce it?

**Comment by zeripath** [comment]
You must provide us with logs or else we cannot help you.

We will close this issue in 14 days if you do not provide us with logs and some way to replicate your issue.

**Comment by zhu0629** [comment]
HERE IS THE REQUEST

curl 'http://MYHOST/org/MYORG/settings/hooks/wechatwork/new' \
  -H 'Connection: keep-alive' \
  -H 'Cache-Control: max-age=0' \
  -H 'Upgrade-Insecure-Requests: 1' \
  -H 'Origin: null' \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4621.0 Safari/537.36' \
  -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9' \
  -H 'Accept-Language: zh-CN,zh;q=0.9,en;q=0.8' \
  -H 'Cookie: gitea_awesome=MYUSERNAME; gitea_incredible=a10d652b5c90bbb2319987e9a75d1e5a3c3593b342bec046a9b1c883923976ff; i_like_gitea=ce721507c1b8beb0; _csrf=Cy0StSbRBmtcLdE-kwhJSkuU_Bs6MTYzNzEzNDcxMzk2MTI4NTY3Ng' \
  --data-raw '_csrf=Cy0StSbRBmtcLdE-kwhJSkuU_Bs6MTYzNzEzNDcxMzk2MTI4NTY3Ng&payload_url=https%3A%2F%2Fqyapi.weixin.qq.com%2Fcgi-bin%2Fwebhook%2Fsend%3Fkey%3DMYROBOTID&events=push_only&branch_filter=*&active=on' \
  --compressed \
  --insecure


RESPONSE:
404

**Comment by wxiaoguang** [comment]
Sorry, the problem indeed exists, will be fixed in https://github.com/go-gitea/gitea/pull/17810
