### ISSUE TITLE
Web UI does not allow empty wiki pages, but does not notify about that

### ISSUE THREAD

**Issue by delvh** [go-gitea/gitea#17280]
### Gitea Version

1.16.0+dev-339-gee73d8409

### Operating System

Linux

### Browser Version

Firefox 93

### Can you reproduce the bug on the Gitea demo site?

Yes

### Description

There seems to be a silent failure when attempting to publish a wiki page without content:
The `save page` button on the `new page` editor will simply act as if it was never pressed.
I think it would be better to notify the user that the content cannot be empty, just as the `edit page` editor does - yes, there is different behavior between the two.

### Screenshots

No response

**Comment by delvh** [comment]
Since when do we have a `theme/wiki` label? In a quick search prior today it was not present…

**Comment by zeripath** [comment]
Since I added it for this one :mage:
