### ISSUE TITLE
[UI] Add download button to file view

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#17286]
Add a download button on file view to make it easy to download files for people not familiar with  gitea/github/...

ref: https://youtu.be/mvk5tVMZQ_U?t=3198

**Comment by georgioupanayiotis** [comment]
Hello @6543 can I take this issue?

**Comment by 6543** [comment]
instead of a "Download" button what about a icon: 
![Bildschirmfoto zu 2021-10-14 18-15-08](https://user-images.githubusercontent.com/24977596/137356723-2b2bdcdd-9bda-4193-b1de-56d81c3a7e6b.png)
?
