### ISSUE TITLE
Gitea can't authenticate against Postgres 13

### ISSUE THREAD

**Issue by stop5** [go-gitea/gitea#17285]
### Gitea Version

1.17.2

### Git Version

2.30.2

### Operating System

Debian GNU/Linux Bullseye (11)

### How are you running Gitea?

currently with sudo manually.
but it is indipendent from the running method.

### Database

PostgreSQL

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/stop5/ccfbc4eed19bfa4dfc3754c234a55cac

### Description

I have set up gitea and the database as the description.
But the Authentication fails every time.
The authentication with the postgres client runs without problems. The authentication that i recorded using tcpdump also looks ok.

**Comment by zeripath** [comment]
Are there any special characters in your password?

**Comment by stop5** [comment]
no, it has only caracters from A-Z, a-z and 0-9.

**Comment by zeripath** [comment]
Does postgres give us any more information as to why it is rejecting gitea's connection?

**Comment by zeripath** [comment]
Actually it does:

**Comment by zeripath** [comment]
`scram-sha-256`

I am willing to bet is not supported by the `pq` driver. 

Switch that to md5

**Comment by stop5** [comment]
I set it up like the docs said: https://docs.gitea.io/en-us/database-prep/#postgresql
They say that it must be scram-sha-256.

**Comment by stop5** [comment]
i tested it and nothing has changed

**Comment by theAkito** [comment]
Same problem with Gitea `1.15.10` with a legacy PostgreSQL 11 database.

I am in the process of migrating from a generic local installation to a Kubernetes installation of Gitea and I want to keep my old database.

I experience the same problems, as described here. I can connect perfectly fine on the CLI with `psql`, etc. I can do everything. However, when the Gitea configuration container tries to authenticate with PostgreSQL 11, it fails with an authentication failure regarding the password.

I excluded common errors and human mistakes by repeating the restoration process in different ways and I was really careful to make it as working as possible. Still, to no avail.

I might try a different Gitea version, to see if it continues to happen then. My legacy Gitea installation is based on a development release of `1.13`.

**Comment by lunny** [comment]
Looks like https://github.com/lib/pq/pull/833 has been merged and this is not a problem anymore?
