### ISSUE TITLE
500 error on organization page: error calling DescriptionHTML

### ISSUE THREAD

**Issue by aanderse** [go-gitea/gitea#17297]
### Gitea Version

1.15.3

### Operating System

Linux (NixOS)

### Browser Version

Firefox 92.0

### Can you reproduce the bug on the Gitea demo site?

No

### Description

A user on my `gitea` instance reported that whenever they hit the "org" page for one organization they get a 500 error. I'm able to reproduce this. The error only occurs on 1 organization - all other organizations are viewable without any errors.

I imagine a `select` statement in one of the tables in the associated database could provide more relevant information, but I'm not sure which table(s) to `select` from.

Any help would be greatly appreciated.

Thank you.

### Screenshots

![Screenshot_20211012_224441](https://user-images.githubusercontent.com/7755101/137058224-6e3339df-1dff-42c0-abf1-8027f1630c24.png)
![Screenshot_20211012_224409](https://user-images.githubusercontent.com/7755101/137058088-76142cfb-388d-4331-b5c1-64747a323d5a.png)

**Comment by techknowlogick** [comment]
Which database are you using?

**Comment by techknowlogick** [comment]
Panic looks like it is coming from `JSONUnmarshalHandleDoubleEncode` in login_source.go. Although I'll poke at it once I get to a desktop where I can actually read the above logs on a larger screen than my phone.

**Comment by zeripath** [comment]
Have you restored from a dump made by 1.14.3-1.14.6?

**Comment by zeripath** [comment]
Please upgrade to 1.15.4 - there is a fix to prevent an NPE at that line introduced in #17137 but you will need to reapply the patch I've provided if you still get problems so we can get more logging.

**Comment by aanderse** [comment]
Upgrading fixes the issue. Thanks to all for your help!
