### ISSUE TITLE
Sort tag listing by alphanumeric values

### ISSUE THREAD

**Issue by camlafit** [go-gitea/gitea#17316]
### Gitea Version

1.14.1

### Operating System

linux

### Browser Version

not relevant

### Can you reproduce the bug on the Gitea demo site?

Yes

### Description

For example on https://try.gitea.io/camlafit/ps_checkout# if we list tags on interface, listing doesn't follow semver list.
2.15.x  is after 2.1.x but before 2.2.x but 15 > 2.

Thanks a lot

### Screenshots

![Capture d’écran de 2021-10-15 16-44-37](https://user-images.githubusercontent.com/209915/137507253-58118c06-f1e5-41fb-b513-ff78dd8fb6fc.png)

**Comment by silverwind** [comment]
Yeah, I meant our code could probably do the same, at least in the git binary code path.
