### ISSUE TITLE
500 error when accessing repo on web (context deadline exceed, LastCommitCache related)

### ISSUE THREAD

**Issue by bagasme** [go-gitea/gitea#17314]
### Gitea Version

commit d47798ccc72236fa239834583ae8367a16ab3fbe

### Git Version

2.33.0

### Operating System

Debian 11

### How are you running Gitea?

built from source with Go 1.17.2, Node 14.17.6 (npm 6.14.15) on Ubuntu 20.04. Running as systemd service on production mode. Connected to a PostgreSQL 14 instance on separate server.

### Database

PostgreSQL

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/bagasme/5c5dc41a48d8cea354b0f68fc6d2f6bd

### Description

I'm trying to access one of my repo (a local copy of `git.git`) on the web interface (at `https://gitnode.io/bagas/git`). It returns 500 error instead of showing the repo contents. Going through log, the error occurs at `renderDirectoryFiles()`, but before it logs `LastCommitCache` stuff.

### Screenshots

(not relevant, since the 500 error page is generic).

**Comment by zeripath** [comment]
This is going to be related to #16467 - something will have changed that that PR relied on and now instead of the error being ignored/expected it's being propagated up.

I'll take a look.

**Comment by zeripath** [comment]
Well given a feature I made caused it...

Repo view should now be a lot more snappy for big repos.

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
> Well given a feature I made caused it...

right.. still thanks.
 
> Repo view should now be a lot more snappy for big repos.

it does feel that way. btw I was only getting 500s on larger™ repos and now I'm not so that's great. 🚀
