### ISSUE TITLE
stat /data/ssh/gitea.rsa: permission denied

### ISSUE THREAD

**Issue by izouxv** [go-gitea/gitea#17312]
### Gitea Version

1.15.3

### How are you running Gitea?

helm install gitea gitea-charts/gitea  --namespace gitea --create-namespace --version 4.1.1 \ 
       --set gitea.config.server.START_SSH_SERVER=true 

### Database

PostgreSQL

### Can you reproduce the bug on the Gitea demo site?

Yes

### Description

[F] Unable to check if [/data/ssh/gitea.rsa /data/ssh/gogs.rsa] exists. Error: stat /data/ssh/gitea.rsa: permission denied

### Screenshots

[F] Unable to check if [/data/ssh/gitea.rsa /data/ssh/gogs.rsa] exists. Error: stat /data/ssh/gitea.rsa: permission denied

**Comment by zeripath** [comment]
And you should be using 1.15.4 not 1.15.3
