### ISSUE TITLE
Can't use Apache HTTPd as a reverse proxy - missing content-type header

### ISSUE THREAD

**Issue by rubys** [go-gitea/gitea#17310]
### Gitea Version

Gitea version 1.15.4 built with GNU Make 4.1, go1.16.9 : bindata, sqlite, sqlite_unlock_notify

### Git Version

git version 2.25.1

### Operating System

Ubuntu 20.04

### How are you running Gitea?

Downloaded from https://dl.gitea.io/gitea/1.15.4/gitea-1.15.4-linux-amd64

### Database

MySQL

### Can you reproduce the bug on the Gitea demo site?

Yes

### Description

I'm trying to use Apache HTTPd as a reverse proxy, per https://docs.gitea.io/en-us/reverse-proxies/#apache-httpd-with-a-sub-path

Unfortunately, mod proxy html requires a valid content type header, per https://httpd.apache.org/docs/2.4/mod/mod_proxy_html.html#proxyhtmlenable

No such header is provided by gitea's main page:

```
$ curl --head https://try.gitea.io/
HTTP/2 200 
date: Thu, 14 Oct 2021 20:25:39 GMT
set-cookie: i_like_gitea=526e7410161b0b16; Path=/; HttpOnly; SameSite=Lax
```

P.S.  I believe that the instructions are missing a `ProxyHtmlEnable on`.

**Comment by rubys** [comment]
That's odd; I'm still seeing a 200 response:

```
$ curl --head https://try.gitea.io/
HTTP/2 200
date: Fri, 15 Oct 2021 05:05:52 GMT
set-cookie: i_like_gitea=9058c2ceaf5cc63d; Path=/; HttpOnly; SameSite=Lax
```

**Comment by rubys** [comment]
OK.

I have a server.  It runs Ubuntu 20.04 with Apache httpd.  It serves various content, a few CGIs, and reverse proxy to [openvpn](https://openvpn.net/), [radicale](https://radicale.org/3.0.html), and a personal node.js application.

I tried adding gitea.  The configuration is done in `/etc/apache2/conf-enabled/gitea.conf`:

```
AllowEncodedSlashes NoDecode

# Note: no trailing slash after either /git or port
ProxyPass /git http://localhost:3000 nocanon
ProxyPassReverse /git http://localhost:3000
```

What I find it the HTML returned is not adjusted, for example:

```
$curl -s http://localhost/git | tail -5
        <script src="/assets/js/index.js?v=a493805f36551bca156f633fe0e30c1c"></script>

</body>
</html>
```

When I run with a browser, I get a 404 when trying to fetch `http://localhost/assets/js/index.js`.  And another 404 trying to fetch `http://localhost/assets/css/index.css`.

**Comment by wxiaoguang** [comment]
You should use `ROOT_URL` in `app.ini`: https://github.com/go-gitea/gitea/blob/main/custom/conf/app.example.ini

Do not use ProxyPassReverse. If you see it, then the document should be updated.
