### ISSUE TITLE
Migration failed by "error in table task after rename: duplicate column name: message"

### ISSUE THREAD

**Issue by wxiaoguang** [go-gitea/gitea#17328]
### Gitea Version

1.15.4

### Description

Many users report that the migration fails:

```
2021/10/16 08:45:14 ...ations/migrations.go:422:Migrate() [I] [SQL] ALTER TABLE `task` RENAME COLUMN errors TO message [] - 6.592953ms
2021/10/16 08:45:14 ...ations/migrations.go:422:Migrate() [I] [SQL] ROLLBACK [] - 113.064µs
2021/10/16 08:45:14 routers/common/db.go:33:InitDBEngine() [E] ORM engine initialization attempt #1/10 failed. Error: migrate: do migrate: error in table task after rename: duplicate column name: message
2021/10/16 08:45:14 routers/common/db.go:34:InitDBEngine() [I] Backing off for 3 seconds
2021/10/16 08:45:17 routers/common/db.go:27:InitDBEngine() [I] ORM engine initialization attempt #2/10...
```

`Removing the message field in task table` resolves this problem and can complete the migration.

The problem seems to be caused by Gitea accessed the `task` ORM too early (before migration), so the `task` table was changed (`message` was added while `error` also exists) before the migration and then the conflict occurs.

**Comment by zeripath** [comment]
I don't understand where this could be happening - we'd need to be calling `Sync2()` before the Migrate function runs but I can't find any example of this. 

The interesting thing is that not every user reports this - which suggests that whatever is going on is either some kind of race or it's related to something else.

**Comment by wxiaoguang** [comment]
Yep, I cannot reproduce this bug either. One user was using pgsql while another was using sqlite3. My only guess is whether there is some code triggering `task` early before a long running migration finishes.

**Comment by wxiaoguang** [comment]
Just to record here: we have an issue tracking this problem

* https://github.com/go-gitea/gitea/issues/17531
