### ISSUE TITLE
ArchLinux upgrade to 1.15.4

### ISSUE THREAD

**Issue by smallint** [go-gitea/gitea#17336]
### Gitea Version

1.15.4

### Git Version

2.33.1

### Operating System

ArchLinux

### How are you running Gitea?

Installed via pacman

### Database

PostgreSQL

### Can you reproduce the bug on the Gitea demo site?

No

### Description

After upgrading to 1.15.4 I can't navigate to any repository anymore. The frontend shows error 500 and the backend logs:

```
2021/10/17 10:56:39 ...ules/context/repo.go:343:repoAssignment() [E] GetUserRepoPermission: skipObjectDecoder: expect object or null, error found in #0 byte of ...|&\003d{\003d}\003d|..., bigger context ...|&\003d{\003d}\003d|...
```

**Comment by zeripath** [comment]
In future read the blog entry for the version: https://blog.gitea.io/2021/10/gitea-1.15.4-is-released/

❗ We remind users that a bug was discovered with gitea dump in 1.14.3–1.14.6 and 1.15.0. Database dumps from these versions cause broken fields in the repo_unit and login_source tables causing the issue identified in #16961. Users on 1.14.x must upgrade to 1.14.7 before running gitea dump. If this is not possible and you are affected #17137 provides a new gitea doctor command to fix the repo_unit issue:

```
gitea doctor --fix --run fix-broken-repo-units
```
