### ISSUE TITLE
Cannot change themes (changing settings in [ui] does nothing)

### ISSUE THREAD

**Issue by MatCat** [go-gitea/gitea#17331]
### Gitea Version

 1.15.4 built with GNU Make 4.1, go1.16.9 : bindata, sqlite, sqlite_unlock_notify

### Git Version

2.20.1

### Operating System

Debian 10

### How are you running Gitea?

Running the amd64 binary

### Database

MySQL

### Can you reproduce the bug on the Gitea demo site?

No

### Description

I added:

```
[ui]
DEFAULT_THEME = arc-green

```
to my app.ini, however the theme does not change.  No idea what I am doing wrong for it to not work.  

I have GITEA_CUSTOM="/home/mygit/custom/"

app.ini is in /home/mygit/custom/conf/app.ini

**Comment by delvh** [comment]
Could you please rebuild Gitea again? I have a slight suspicion that the cause is a cached app.ini.
To me it seems as if `bindata` caches the state of files. They will be rebuilt only if they have changed.
If I'm correct, this should fix the problem.
