### ISSUE TITLE
COOKIE_SECURE doesn't flag _csrf cookie as 'Secure'

### ISSUE THREAD

**Issue by eripa** [go-gitea/gitea#1734]
- Gitea version (or commit ref): 1.1.1
- Git version: 2.1.4
- Operating system: Debian GNU/Linux 8.8 (jessie) x86_4
- Database:
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description

I was under the impression that setting COOKIE_SECURE to true will make all cookies have the 'Secure' flag set. However it only seem to apply to the i_like_gitea cookie.

https://try.gitea.io doesn't seem to be configured with COOKIE_SECURE.

**Comment by appIeboy** [comment]
<p align=right><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup>#1798 @lunny @tboerger @sapk @cez81 @geek1011 @lafriks @ethantkoenig @andreynering @DblK </sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></p>
