### ISSUE TITLE
404 when @ in folder name

### ISSUE THREAD

**Issue by somera** [go-gitea/gitea#17344]
### Gitea Version

1.15.4

### Git Version

2.25.1

### Operating System

Ubuntu 20.04.3

### How are you running Gitea?

Downloaded compiled version for Linux.

### Database

PostgreSQL

### Can you reproduce the bug on the Gitea demo site?

Yes

### Description

When I mirror https://github.com/boostorg/boost than there is an folder with @ in name.

![image](https://user-images.githubusercontent.com/8334250/137647956-cb6670b1-9de6-4be0-b30b-fb597dadda87.png)

or is this something special?

Take a look here: https://try.gitea.io/somera/boost

**Comment by jolheiser** [comment]
It sends me to a 404 on github as well.

**Comment by somera** [comment]
> It sends me to a 404 on github as well.

Cause Gitea hat a bug.

Here is the original GitHub link: https://github.com/boostorg/boost

**Comment by jolheiser** [comment]
> > It sends me to a 404 on github as well.
> 
> Cause Gitea hat a bug.
> 
> Here is the original GitHub link: https://github.com/boostorg/boost

Yes, on the original github link I'm also sent to 404 when clicking the submodule

**Comment by somera** [comment]
> > > It sends me to a 404 on github as well.
> > 
> > 
> > Cause Gitea hat a bug.
> > Here is the original GitHub link: https://github.com/boostorg/boost
> 
> Yes, on the original github link I'm also sent to 404 when clicking the submodule

hm ... for me works. With Chrome and FF.
