### ISSUE TITLE
Apostrophe shows as HTML entity when adding user to organization

### ISSUE THREAD

**Issue by jhult** [go-gitea/gitea#17362]
### Gitea Version

1.15.3

### Git Version

2.30.2

### Operating System

alpine

### How are you running Gitea?

Docker via `gitea/gitea:latest-rootless`

### Database

SQLite

### Can you reproduce the bug on the Gitea demo site?

No

### Description

Create a user with an apostrophe in their name. Add them to an organization. Notice that the apostrophe is shown as the HTML entity (`&#39;`).

Cannot test on try.gitea.io since I need permissions (which I don't have) to add the user to an organization.

User is coming from an OpenID registry.

**Comment by zeripath** [comment]
@jhult are the two places I've demonstrated the only places where it happens? I.e. it's just in the drop-downs?
