### ISSUE TITLE
Put Vue into production-mode

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#1736]
- Gitea version (or commit ref):     9e627af built with: bindata, sqlite
- Git version:     2.11.2
- Operating system: Ubuntu 17.04
- Database (use `[x]`):
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes - directly on start site
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
Gitea seems to ship with Vue in development mode:

"You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html"

Since Vue suggests this by itself, maybe it should be changed to production mode?

## Screenshots

**If this issue involves the Web Interface, please include a screenshot**

**Comment by lunny** [comment]
@andreynering

**Comment by andreynering** [comment]
Hmm... I think this issue will only be resolved when we migrate to something like Webpack for front-end build.

We could change it to prod version now, but then we lose the warnings while in development.

**Comment by bkcsoft** [comment]
@andreynering Actually just using `vue.min.js` instead put's it into prod-mode 🙄 

Have it include different files depending on `setting.RUN_MODE` 😉

**Comment by appIeboy** [comment]
<p align=right><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup>#1798 @lunny @tboerger @sapk @cez81 @geek1011 @lafriks @ethantkoenig @andreynering @DblK </sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></p>
