### ISSUE TITLE
 Failed to initialize ORM engine: dial tcp <public_ip>:5432: connect: connection timed out       

### ISSUE THREAD

**Issue by WillNilges** [go-gitea/gitea#17379]
### Gitea Version

4.0.3

### Git Version

¯\\\_(ツ)_/¯

### Operating System

CoreOS 34

### How are you running Gitea?

Running the Gitea Helm Chart on OKD 4.7

### Database

PostgreSQL

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/WillNilges/029f65fbf6b3d36e0fe294958bb752a1

### Description

Trying to run Gitea on OKD 4.7 using the Kubernetes instructions, which pointed me to the Helm chart. I actually got it working for a month or two (after messing with the permissions; See this blog post (https://nilges.me#gitea_on_okd4_post) about my experience doing that). For some reason, sometime in the last week, I've started getting errors involving something about the postgres database.  I _think_ it's something to do with my cluster's routing, but this is the first time I've ever seen an issue like this on any cluster _ever._ Also, I'm pretty damn sure that it _can_ communicate with the postgres pod because it resolves the IP and actually gets as far as it does in the first place.

Apologies about the ¯\_(ツ)_/¯ but I have literally no idea.

Here's where I've been:
- https://github.com/go-gitea/gitea/issues/2979
- https://github.com/go-gitea/gitea/issues/4904
- https://gitea.com/gitea/helm-chart/issues/159
- https://github.com/go-gitea/gitea/issues/1362

I'm also going to open a sister issue here: https://gitea.com/gitea/helm-chart/issues

Thoughts? Questions? Concerns?

**Comment by WillNilges** [comment]
Helm issue: https://gitea.com/gitea/helm-chart/issues/232

**Comment by WillNilges** [comment]
I think I found the issue: My `gitea` and `memcached` pods were running under **worker01** and my `postgres` pod was running under **worker02**. For context, my cluster is laid out like so (Sorry, I'm a poor college student)

celestial (Proxmox host)
- okd4-master01
- okd4-master02
- okd4-master03

rihuud (Proxmox host)
- okd4-worker01
- okd4-worker02

What I did was use a nodeselector to specify that all pods in my `gitea` namespace are to run on `master03`. That worked. My Gitea instance is back up.

I added the worker nodes _after_ I set up Gitea. **I'm wondering if it's _Gitea_ that doesn't like running on multiple nodes, or if it's something weird with my network.** This hasn't happened with any other service I have tried to deploy. I need to do some testing, I guess. I'm theorizing that I'll be fine to run Gitea on a worker node, on rihuud, as long as I run all pods on the same node. I hope that's the case, anyway.

I think this needs some investigation, because this is sus.

**Comment by lunny** [comment]
You should have some settings if you have many Gitea Nodes.

**Comment by WillNilges** [comment]
Sorry, can you elaborate? What do you mean by that? Also, I only have one pod running Gitea.

**Comment by wxiaoguang** [comment]
It's configuration problem, the database connection setting must be correct.
