### ISSUE TITLE
Check if cache works correctly during init

### ISSUE THREAD

**Issue by wxiaoguang** [go-gitea/gitea#17380]
Users may meet problem if the cache doesn't work. If we can check the cache during init, we can report this failure to users as early as possible.

```
2021/10/21 03:44:46 Started GET /repo/demo for x.x.x.x:yyyy
...
2021/10/21 03:44:46 ...ules/context/repo.go:849:func1() [E] GetCommitsCount: memcache: connect timeout to z.z.z.z:1234
...
2021/10/21 03:44:46 Completed GET /repo/demo 500 Internal Server Error in 255.614891ms
```

_Originally posted by @tardich in https://github.com/go-gitea/gitea/issues/17369#issuecomment-948232414_

**Comment by lunny** [comment]
But even if the cache(redis, memcache) is available at the start of Gitea, it may also gone any time.

**Comment by wxiaoguang** [comment]
At least this check can help users to find the mistakes during setup. Just like the issue.
