### ISSUE TITLE
Issue comment URLs parsed / emitted incorrectly

### ISSUE THREAD

**Issue by noerw** [go-gitea/gitea#17394]
### Gitea Version

a115309f4 (current 1.16), but I observed this since early in the 1.16 dev cycle

### How are you running Gitea?

try.gitea.io

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

https://try.gitea.io/noerw/hochwasser/issues/5

### Description

Issue comment references don't get parsed correctly, when it isn't the last thing on the line.
Looks like the HTML emitted is wrong, the word following the link is missing. The href is empty.
See try.gitea.io link above.

**Comment by wxiaoguang** [comment]
Somehow related to https://github.com/go-gitea/gitea/pull/17398 , maybe the code can be improved more.
