### ISSUE TITLE
Issue comment edit-diff is wrong

### ISSUE THREAD

**Issue by noerw** [go-gitea/gitea#17393]
### Gitea Version

58cd55d35

### Git Version

? idk, saw it on gitea.com

### Operating System

linux

### How are you running Gitea?

gitea.com

### Database

MySQL

### Can you reproduce the bug on the Gitea demo site?

Yes

### Description

Edits of more complex comments get quite strange diffs. [I got diffs that didn't touch the single line that was edited, but show two other lines as changed](https://try.gitea.io/noerw/hochwasser/issues/4) (I'll try to come up with a more minimal reproducer later)
An edit like the following worked fine though. 
```diff
foo
-baz
+bar
bar
```
It seems this feature needs more testing with longer comments / more complex edits.

### Screenshots

I don't know what the actual edit was, but certainly not this:
![image](https://user-images.githubusercontent.com/7880552/138348990-de05b831-c3ba-42b4-b967-76c7e081deb5.png)

**Comment by wxiaoguang** [comment]
You just triggered an unrelated bug which prevent the JS executing 😂 

I fixed that bug and I think we should apply the patch first to continue. https://github.com/go-gitea/gitea/pull/17398

**Comment by wxiaoguang** [comment]
Just a guess, have you edited the issue more than 20 times? If yes, it is a feature (required by some reviewers) that we only keep 20 history revisions at most, the shortest interval history revision are deleted if the count is greater than 20.
