### ISSUE TITLE
eslint-module-utils from npm is to new

### ISSUE THREAD

**Issue by ecsgh** [go-gitea/gitea#17402]
### Gitea Version

1.15.5 (also 1.15.4 ...)

### Operating System

linux

### How are you running Gitea?

not relevant for this bug.

### Can you reproduce the bug on the Gitea demo site?

No

### Description

No build with current nodejs packages.

Since about 1 week version 2.7.x of eslint-module-utils is available.
If you install the nodejs packages with npm install you can't build gitea afterwards.

It comes the error message:
error exported declaration 'default' not used within other modules import/no-unused-modules

With the last version 2.6.2 of eslint-module-utils this error does not occur.

**Comment by wxiaoguang** [comment]
Oudated
