### ISSUE TITLE
Respositories are not shown for an Organization

### ISSUE THREAD

**Issue by Avalancs** [go-gitea/gitea#1742]
- Gitea version (or commit ref): 03d6bab
- Git version: git 2.12.2.windows.2
- Operating system: Windows 10
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
## Description
Using said version will not show the repositories inside the dashboard when switching to an Organization, but works for my user. As a workaround I stopped the service, switched out the exe to the 1.1.1 version, and I can see the repositories there, so I think this is a regression issue.

## Screenshots
I have an organization open where I should be able to see all repositories. There are 4 private and 1 public repository I should see. I am the owner of the organization, but still nothing shows up under the "Repositories" section.
![org_dashboard](https://cloud.githubusercontent.com/assets/18668703/26163889/4de5d246-3b2b-11e7-91ba-aec267ecc572.jpg)

**Comment by andreynering** [comment]
This is due recent change of this panel to VueJS and the API.

**Comment by andreynering** [comment]
This should be fixed by https://github.com/go-gitea/gitea/pull/1750
