### ISSUE TITLE
The font color is broken

### ISSUE THREAD

**Issue by Brandonbr1** [go-gitea/gitea#17424]
### Gitea Version

v1.15.5

### Operating System

Windows 10

### Browser Version

Edge 84.0.522.52 (Official build) (64-bit)

### Can you reproduce the bug on the Gitea demo site?

No

### Description

The font is white and it makes it hard to see GO and MIT

### Screenshots

![Capture](https://user-images.githubusercontent.com/74426342/138621116-1463759d-4a29-47fc-8c15-efe670c160a2.PNG)

**Comment by wxiaoguang** [comment]
This issue has been fixed by https://gitea.com/gitea/theme/issues/102
