### ISSUE TITLE
Add SSH signing

### ISSUE THREAD

**Issue by ptman** [go-gitea/gitea#17449]
### Feature Description

Like GPG signing, but with SSH keys

https://github.com/git/git/pull/1041

**Comment by unbeatable-101** [comment]
Git v2.34.0 is out now with support for this.

**Comment by melvincarvalho** [comment]
Yes, I'm using it.  It's great.  Here's what it looks like currently on github:

![image](https://user-images.githubusercontent.com/65864/142010765-5f464982-d829-4873-81d7-0aae95f5ad5c.png)

https://github.com/melvincarvalho/melvincarvalho.com/commits/gh-pages

git verify-commit also works

I've mailed github support about changing that from unverified -> verified ... hopefully soon!

**Comment by unbeatable-101** [comment]
If you click on the `unverified` you can see it is recognized as signed, just GitHub doesn't know how to read it. 

>  GitHub supports GPG and S/MIME signatures. We don’t know what type of signature this is.

**Comment by 42wim** [comment]
I'm going to try and implement this.
Already created a library to create/verify those armored ssh signatures (https://github.com/42wim/sshsig)
