### ISSUE TITLE
How to change the default homepage from Dashboard to an Organization

### ISSUE THREAD

**Issue by gayprogrammer** [go-gitea/gitea#1745]
- Gitea version (or commit ref): 1.1.1+2-g2854c8a
- Git version: 2.12.2
- Operating system: Windows Server 2012
- Database (use `[x]`):
  - [x] MSSQL
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Not relevant
- Log gist: Not relevant

## Description
I would like to change the default homepage that all users are directed to. We have one organization with a few repos, so I would like all users to log in and land on the organization's page. The Dashboard page is not useful to us (neither is Issues, Pull Requests, and Explore pages).

What is the best way to change the default homepage? Would it be to inject a JavaScript redirect in the "home" template?

**Comment by psxde** [comment]
In general it would be great to set the default homepage per user and/or a global variable to something other than the current homepage, e.g. an organization dashboard or the user profile page which is more usable to welcome new users than a nearly blank page.

**Comment by naim42** [comment]
Yes, this would be nice.

**Comment by RichardCraven** [comment]
...no response?

**Comment by guillep2k** [comment]
I thik there are several ways to do this but, one of them could be the use of custom templates.

**Comment by shannon-fluellen-aurea** [comment]
For a work account, I think it would be much better to have the option to set an organization as the default dashboard page

**Comment by carlosrziegler** [comment]
some updates ?

**Comment by lunny** [comment]
I think one workaround is to customize dashboard page like @guillep2k said. For Gitea itself, it's difficult to merge this into the main base code.
