### ISSUE TITLE
Issue with repo-archive storage in gitea 

### ISSUE THREAD

**Issue by platof** [go-gitea/gitea#17450]
I have been trying to configure gitea for  repository archive storage following this url [https://docs.gitea.io/en-us/config-cheat-sheet/#repository-archive-storage-storagerepo-archive](https://docs.gitea.io/en-us/config-cheat-sheet/#repository-archive-storage-storagerepo-archive). This is my configuration in app.ini 
![image](https://user-images.githubusercontent.com/35527059/139047363-c7b373e3-dc3f-4af8-b484-28cbfd3c181f.png). when I go into the repo to archive it. it is meant to refelect in the s3 bucket but nothing shows. I also configured lfs, attachments avatars. those show up in s3. except for repo-archive. I configured gitea using docker-compose. these are my logs too 
![image](https://user-images.githubusercontent.com/35527059/139048897-fa422e02-7eb7-4e33-b737-76bcfdf2b8c9.png)
 I am open to sharing more information if needed. Thanks

**Comment by wxiaoguang** [comment]
Stale for no feedback. Feel free to reopen if there is still a problem.
