### ISSUE TITLE
Do we have some documents do describe our permission system? I have questions about the real meaning about "prohibited", "active", "restricted" and how they work and how they affect the permission checks.

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#17467]
Do we have some documents do describe our permission system? I have questions about the real meaning about "prohibited", "active", "restricted" and how they work and how they affect the permission checks.

_Originally posted by @wxiaoguang in https://github.com/go-gitea/gitea/issues/17464#issuecomment-953470628_

**Comment by lafriks** [comment]
* prohibited - user is not allowed to log in in UI
* active - standart user
* restricted - user is allowed to see only organizations/repositories that he has explicit rights specified (ex. in private Gitea instances user won't be allowed to see even organizations/repositories that are set as public)
