### ISSUE TITLE
Batch calling of `updateIssuesMeta` causes database deadlock

### ISSUE THREAD

**Issue by wxiaoguang** [go-gitea/gitea#17469]
### Gitea Version

dev(main)

### Description

Bug:

https://github.com/go-gitea/gitea/blob/141d1a2aa5ff31267661c1985f52e6c02eafea11/web_src/js/features/repo-legacy.js#L87-L91

It causes database deadlock and results in error response (some data can not be updated correctly, and the page can not be reloaded)

```
2021/10/28 17:51:22 .../repo/issue_label.go:209:UpdateIssueLabel() [E] RemoveLabel: Error 1213: Deadlock found when trying to get lock; try restarting transaction
2021/10/28 17:51:23 Completed POST /root/test/issues/labels 500 Internal Server Error in 421.528354ms
```

**Comment by lunny** [comment]
Is this resolved?

**Comment by wxiaoguang** [comment]
Not yet, I haven't got time for this. (If someone can help that's also very welcome)

**Comment by wxiaoguang** [comment]
I proposed a simple fix, please review.
