### ISSUE TITLE
Single user mode: Or, set a user's profile page as LANDING_PAGE

### ISSUE THREAD

**Issue by trwnh** [go-gitea/gitea#17478]
### Feature Description

Similarly to how LANDING_PAGE today can be used to default users to seeing the Explore view, I think it would be very useful to implement functionality to have the landing page be a single user's profile.

Rationale: I self-host Gitea (as I'm sure many do), and I am the only user of my instance. Having visitors land on the default home page is near-useless. Having visitors land on the Explore page is more useful. But the most useful thing would be to have visitors land on my profile. This is functionally the same as the Explore view, but with a better layout and a more personal focus (since it shows an avatar and join date, at least).

**Comment by trwnh** [comment]
That did not work.

**Comment by trwnh** [comment]
OK, I think I got *something* to work, but I think it would still be much cleaner to have this handled by app.ini instead of by custom templates.

To refine the idea of a "single user mode", I think it should include the following changes:
- Redirect the home page to the single user's profile
- Disable and/or hide the following/follower tabs
- Disable and/or hide the registration button
- Disable and/or hide the explore page/tab
- Disable and/or hide the help tab

**Comment by wxiaoguang** [comment]
Duplicated of https://github.com/go-gitea/gitea/issues/11028 ,  and the original one has been closed also.

Gitea focuses more on teams. Users can customize Gitea to implement different single-user features.
