### ISSUE TITLE
footer.tmpl won't be added to the HTML anymore

### ISSUE THREAD

**Issue by Sepphod** [go-gitea/gitea#17489]
### Gitea Version

1.15.6

### Operating System

raspbian

### How are you running Gitea?

docker on a raspi

### Database

PostgreSQL

### Can you reproduce the bug on the Gitea demo site?

No

### Description

footer.tmpl won't be added to the HTML anymore =>

**Comment by techknowlogick** [comment]
In fact it does, and we are modifying the footer on Gitea.com using this method.

Could you confirm it is just this one template or all of them? Are you using the appropriate "custom" dir per the docker docs?

**Comment by Sepphod** [comment]
this snippet here
<footer>
	<div class="ui container">
		<div class="ui left">
			Powered by Gitea Version: 1.16.0&#43;dev-360-g58cd55d35 Seite: <strong>0ms</strong> Template: <strong>0ms</strong>
		</div>
		<div class="ui right lin
		..
is the footer.tmpl? I see the same on my gitea.

I can't see neither the footer.tmpl nor the header.tmpl (which is a copy of the footer for testing) in the html of the server.
both are located in
/data/gitea/templates/custom

**Comment by techknowlogick** [comment]
The location that you've added the templates is in a different location to where they should be, the template overrides need to be in the same folder hierarchy as it is in code, so footer.tmpl would not be under templates/custom

**Comment by Sepphod** [comment]
according to https://docs.gitea.io/en-us/customizing-gitea/ the templates should be under templates/custom.  But honestly I don't understand your comment. Where should be the templates be located?

**Comment by techknowlogick** [comment]
That is specific to adding content to the footer, but the snippet you posted above said you wanted to replace content in the footer ("powered by" etc..), which means you'll want to edit the following template https://github.com/go-gitea/gitea/blob/main/templates/base/footer.tmpl and place it in templates/base (note: I linked to the template in the `main` branch, but as you are using `1.15.6` you will likely need to pull the template from the `release/v1.15` branch)

**Comment by Sepphod** [comment]
I think we misunderstood. I wanted to test if the plantuml feature is working again. When I follow the guide here https://docs.gitea.io/en-us/customizing-gitea/#other-additions-to-the-page than i should add the javascript files and the customized footer. But it is not working. I am not able to see my footer.tmpl in the rendered html page. is the how-to still correct?

**Comment by wxiaoguang** [comment]
The custom template mechanism always works correctly, as long as you put your file in the correct place.

Feel free to report bugs if there is one.
