### ISSUE TITLE
Error: pq: syntax error at or near "." whilst counting Collaborations without existing user

### ISSUE THREAD

**Issue by frnmst** [go-gitea/gitea#17485]
### Gitea Version

1.15.6

### Git Version

git version 2.20.1

### Operating System

Debian 10

### How are you running Gitea?

using `deb [arch=amd64] https://packaging.gitlab.io/gitea buster stable` as APT source

### Database

PostgreSQL

### Can you reproduce the bug on the Gitea demo site?

No

### Description

I migrated from Gitea 1.15.2 directly to 1.15.6. If I run the following I get the error.

`HOME=/var/lib/gitea GITEA_WORK_DIR=/var/lib/gitea /usr/bin/gitea -c /etc/gitea/app.ini doctor --all --fix`

```
[1] Check paths and basic configuration
 - [I] Configuration File Path:    "/etc/gitea/app.ini"
 - [I] Repository Root Path:       "/var/lib/gitea/repos"
 - [I] Data Root Path:             "data"
 - [I] Custom File Root Path:      "/var/lib/gitea/custom"
 - [I] Work directory:             "/var/lib/gitea"
 - [I] Log Root Path:              "/var/log/gitea"
OK
[2] Check if there is garbage storage files
OK
[3] Check Database Version
OK
[4] Check consistency of database
 - [C] Error: pq: syntax error at or near "." whilst counting Collaborations without existing user
ERROR
[5] Check if user with wrong type exist
OK
[6] Check if OpenSSH authorized_keys file is up-to-date
OK

[... continues normally ...]
```

Anyway, everthing seems to be working fine. The `collaboration` table in the database is empty.

**Comment by clarfonthey** [comment]
Are you sure that this is fixed? I'm still getting the error even though I'm running 1.15.7, which supposedly has the fix.

**Comment by zeripath** [comment]
Is it still the same warning exactly?

**Comment by zeripath** [comment]
https://github.com/go-gitea/gitea/blob/a9ed1c5c7c6c85ae280e6a13ca0d4e665945efb4/modules/doctor/dbconsistency.go#L170

 user needs to be backticked here as well...

**Comment by clarfonthey** [comment]
Yeah, unfortunately there's no specific clarification on the error that lets you see what the specific syntax error is, and it shows up as the same. Maybe worth fixing that as well as the underlying issue.

**Comment by zeripath** [comment]
Could you apply the following patch and attempt again to see if it solves the problem?

```patch
diff --git a/modules/doctor/dbconsistency.go b/modules/doctor/dbconsistency.go
index e5f0c5678..cd34994e1 100644
--- a/modules/doctor/dbconsistency.go
+++ b/modules/doctor/dbconsistency.go
@@ -167,13 +167,13 @@ func checkDBConsistency(logger log.Logger, autofix bool) error {
 			"lfs_lock", "repository", "lfs_lock.repo_id=repository.id"),
 		// find collaborations without users
 		genericOrphanCheck("Collaborations without existing user",
-			"collaboration", "user", "collaboration.user_id=user.id"),
+			"collaboration", "user", "collaboration.user_id=`user`.id"),
 		// find collaborations without repository
 		genericOrphanCheck("Collaborations without existing repository",
 			"collaboration", "repository", "collaboration.repo_id=repository.id"),
 		// find access without users
 		genericOrphanCheck("Access entries without existing user",
-			"access", "user", "access.user_id=user.id"),
+			"access", "user", "access.user_id=`user`.id"),
 		// find access without repository
 		genericOrphanCheck("Access entries without existing repository",
 			"access", "repository", "access.repo_id=repository.id"),
```
