### ISSUE TITLE
Invalid session expiration time

### ISSUE THREAD

**Issue by xingzhaowu** [go-gitea/gitea#17493]
### Gitea Version

release/v1.12

### Git Version

2.31.0.windows.1

### Operating System

windows

### How are you running Gitea?

I built gitea on windows,it is runing from a command-line

### Database

MySQL

### Can you reproduce the bug on the Gitea demo site?

No

### Description

my app.ini config:
[session]
PROVIDER = file
SESSION_LIFE_TIME = 30
When I log in to gitea and wait for 30 seconds, the session should have expired, but when I visit again, and there is no prompt to log in. 
But when PROVIDER is set to memory, the login operation will be prompted.

**Comment by wxiaoguang** [comment]
`release/v1.12` is toooo old.

This bug should have been fixed in the latest release.

If you meet problem with the latest release, feel free to reopen the issue.

**Comment by xingzhaowu** [comment]
release/v1.15 also has this problem.
When PROVIDER is set to file, the login status is always valid and has nothing to do with the SESSION_LIFE_TIME configuration item

**Comment by zeripath** [comment]
I cannot replicate this.

Please ensure that you've closed all the browser pages to ensure that the `/user/events` event stream is closed.

**Comment by xingzhaowu** [comment]
> I cannot replicate this.
> 
> Please ensure that you've closed all the browser pages to ensure that the `/user/events` event stream is closed.

Yes, if the session is saved in a file, I need to log in again only after closing the browser.
If the session is stored in the memory, I don't need to close the browser, I have to log in again as soon as the session expires. 
So when the session is saved in a file, the session expiration time seems meaningless.

**Comment by zeripath** [comment]
I didn't say close the browser. I said close the browser pages to ensure that the /user/events eventstream is closed.

you can happily keep the browser open just not a gitea webpage.

**Comment by xingzhaowu** [comment]
我明白了，谢谢。
