### ISSUE TITLE
[API] notifcations API returns 500 if comment was deleted

### ISSUE THREAD

**Issue by qwerty287** [go-gitea/gitea#17499]
### Gitea Version

1.16.0

### How are you running Gitea?

built from source, from cli

### Can you reproduce the bug on the Gitea demo site?

Yes

### Description

The notifications API (`api/v1/notifications`) returns a 500 internal server error if any notification addresses a comment that was deleted.
`...pi/v1/notify/user.go:85:ListNotifications() [E] InternalServerError: GetCommentByID [193] for issue ID [53]: comment does not exist [id: 193, issue_id: 0]`

**Comment by zeripath** [comment]
OK so the problem here is that `NotificationList.LoadAttributes()` is not fault tolerant and will return whenever there is an error.
