### ISSUE TITLE
Bad HTML encoding in blames

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#17492]
### Gitea Version

1.15.6

### Git Version

2.33.1

### Operating System

Arch Linux

### How are you running Gitea?

Using gitea official builds from dl.gitea.io/gitea. It's the  gitea-1.15.6-linux-amd64 executable.

### Database

SQLite

### Can you reproduce the bug on the Gitea demo site?

Yes, here : https://try.gitea.io/issuereporter287/repo

### Description

Reproduction :
- create a new repo in the web interface
- commit a new file in this repo and put special characters in the commit like `<`, `>` or `'`
- push the commit in gitea
- look at the new file blame in the web interface

Result : the special characters of the commit text are badly encoded on the blame page.

I tested by commiting `<yes> l'apo`. It is displayed as `&lt;yes&gt; l&#39;apo` on the web page.

### Screenshots

![image](https://user-images.githubusercontent.com/91130460/139533838-cb0aabd6-9a09-4bb6-8b8f-ccdad88acad8.png)

**Comment by sibzou** [comment]
The `<a>` tag contains `&amp;lt;yes&amp;gt; l&amp;#39;apo`. It should contain `&lt;yes&gt; l&#39;apo`. It's the same thing for the `title` attribute of `<a>`.

**Comment by wxiaoguang** [comment]
I think it is a double-encoding bug.

Can you share the existing reproducible URL on try.gitea.io? Then developers can view the bug at first glance.

**Comment by sibzou** [comment]
Yes it is here https://try.gitea.io/issuereporter287/repo.
