### ISSUE TITLE
WebUI shows incorrect number of tags after migration (mirror) of git-lfs

### ISSUE THREAD

**Issue by plaimbock** [go-gitea/gitea#17509]
### Gitea Version

release/v1.15 git rev 9340269

### Git Version

2.33.1

### Operating System

AlmaLinux 8.4 x86_64

### How are you running Gitea?

Gitea release/v1.15 git rev 9340269d8433277807e98059bfb91daa8bc544b4 was built on AlmaLinux 84 x86_64 with Go 1.17 and NodeJS 14. It was deployed on the same box.

Steps to reproduce:
Migrate (mirror) git-lfs from github. The webUI then shows '1 Tag'  while there are actually 93.

### Database

MySQL

### Can you reproduce the bug on the Gitea demo site?

Yes

### Description

Reproduced on try.gitea.io: https://try.gitea.io/patrick42/git-lfs

### Screenshots

![Gitea - incorrect number of tags after mirror of git-lfs](https://user-images.githubusercontent.com/5047637/139598061-b9889f56-86c7-421e-bdca-0f86bb4e221d.png)

**Comment by plaimbock** [comment]
Screenshot of reproduced isse on try.gitea.io:

![Screenshot](https://user-images.githubusercontent.com/5047637/139598669-9505fc08-7e69-4204-9f66-cabafd7e415a.png)

**Comment by plaimbock** [comment]
This is still an issue with 1.16.4 and also on try.gitea.io
https://try.gitea.io/patrick42/git-lfs

Related? issue #19038

**Comment by lunny** [comment]
I believe this has been resolved. https://demo.gitea.com/lunny/git-lfs/tags and Looks like there should be 103 tags at this time but Github said it's 104. I have counted it page by page, it's 103.
