### ISSUE TITLE
Improve admin dashboard summary display to prevent timeout

### ISSUE THREAD

**Issue by wxiaoguang** [go-gitea/gitea#17506]
### Description

The Admin -> Dashboard -> Summary shows many counting numbers. Some of them aren't useful to admins. Even worse, some counting operations on the large tables like `action` will make the page timeout. For example:

* https://github.com/go-gitea/gitea/issues/17504  ,  "Action table contains 8539538 rows", it takes several minutes to count.

I suggest to improve the summary information, we shouldn't count so many models. Each number displayed here should be useful to admins.

**Comment by zeripath** [comment]
Instead of these `COUNT(*)` calls I think we need to use something like:

```sql
SELECT table_rows FROM information_schema.tables WHERE tables.table_name = ? AND tables.table_schema = ?;
```

with the first parameter as the table name and the second param is the db name.

**Comment by zeripath** [comment]
I have to say I suspect that getting the count for the Action table might be a false report - the real problems are if you have:

```ini
[metrics]
ENABLED_ISSUE_BY_LABEL=true 
ENABLED_ISSUE_BY_REPOSITORY=true
```

Then all of that work occurs every time you look at the statistics page.

**Comment by wxiaoguang** [comment]
For the user, it's not a false report, after the user truncated their `action` table, then their system functions correctly.

For me, it's not a false report. Now what I am doing is truncating my `action` table regularly. (I know how to tune MySQL to bypass the problem, but the truncating just reminds me that there is still a problem).
