### ISSUE TITLE
Public folder and templates not found.

### ISSUE THREAD

**Issue by vuhuythanh1995** [go-gitea/gitea#17502]
### Feature Description

I use docker-compose to create a gitea with Postgres, I want to Customize the homepage but can't find the public and templates folder, did I miss something, or it really doesn't exist in the gitea container.

**Comment by vuhuythanh1995** [comment]
__

**Comment by zeripath** [comment]
> I use docker-compose to create a gitea with Postgres, I want to Customize the homepage but can't find the public and templates folder, did I miss something, or it really doesn't exist in the gitea container.

Please read https://docs.gitea.io/en-us/install-with-docker/#customization & https://docs.gitea.io/en-us/customizing-gitea/

The default templates are all embedded in the gitea binary and can be extracted from the binary for editing using `gitea embedded` see https://docs.gitea.io/en-us/cmd-embedded/ 

You may want to seek further advice on our #docker channel on our discord.

**Comment by vuhuythanh1995** [comment]
> > I use docker-compose to create a gitea with Postgres, I want to Customize the homepage but can't find the public and templates folder, did I miss something, or it really doesn't exist in the gitea container.
> 
> Please read https://docs.gitea.io/en-us/install-with-docker/#customization & https://docs.gitea.io/en-us/customizing-gitea/
> 
> The default templates are all embedded in the gitea binary and can be extracted from the binary for editing using `gitea embedded` see https://docs.gitea.io/en-us/cmd-embedded/
> 
> You may want to seek further advice on our #docker channel on our discord.

Thank you for your reply, this means a lot to me.
