### ISSUE TITLE
Changing email account doesn't release that email

### ISSUE THREAD

**Issue by isyq** [go-gitea/gitea#17519]
I set the admin account to xxx@mail.com, after built everything up, I change it to yyy@mail.com.
Now I try to set a new user with that email(xxx@mail.com), it always alerts the email is already existed.

**Comment by lunny** [comment]
What's the version of you Gitea instance?

**Comment by isyq** [comment]
"gitea.exe --version" shows: Gitea version 1.15.6 built with GNU Make 4.1, go1.16.9 : bindata, sqlite, sqlite_unlock_notify.

**Comment by lunny** [comment]
How did you change the old user's email to yyy@mail.com?

**Comment by isyq** [comment]
Login admin's home page -> 'Site administration' page -> User accounts -> Change itself email address.
