### ISSUE TITLE
Pull request #947 breaks HTTPS push/pull to "master" when logged in as Admin

### ISSUE THREAD

**Issue by wyattoday** [go-gitea/gitea#1751]
- Gitea version (or commit ref): https://github.com/go-gitea/gitea/commit/fd6034aaf23af1ce03bcba0babcbe7675ce093ee
- Git version: 2.13
- Operating system: Ubuntu 16.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:

## Description

This commit break pushing and pulling on "master" branch when using HTTPS and logged in as an "admin" account: https://github.com/go-gitea/gitea/commit/fd6034aaf23af1ce03bcba0babcbe7675ce093ee

Here's the pull request in question: https://github.com/go-gitea/gitea/pull/947

Rolling back to the prior commit of gittea fixes the problem.

There's likely a logic error where Admin / creator accounts aren't being read in correctly (or their permissions aren't being read in correctly).

## Screenshots

**If this issue involves the Web Interface, please include a screenshot**

**Comment by lunny** [comment]
Hi, It seems only system admin has the permission problem?

**Comment by lunny** [comment]
@wyattoday please help to confirm #1753 resolve this issue.

**Comment by wyattoday** [comment]
I'll try with a regular user account tomorrow morning (Eastern Time) and report back.

**Comment by wyattoday** [comment]
The proposed fix still breaks things (or leaves things broken). For example, as an admin user, when cloning an existing repository, I get an empty directory:


```
git.exe clone --progress -v "https://example.com/git/repository_name.git" "C:\Users\USERNAME\Documents\repository_name"

Cloning into 'C:\Users\USERNAME\Documents\repository_name'...
warning: You appear to have cloned an empty repository.

Success (641 ms @ 5/19/2017 8:08:51 AM)
```

Other things are broken as well (pulling still broken, haven't tried pushing yet).


Rolling back to before https://github.com/go-gitea/gitea/commit/fd6034aaf23af1ce03bcba0babcbe7675ce093ee fixes things for me.
