### ISSUE TITLE
Migrate through API gives ``

### ISSUE THREAD

**Issue by kad-beumer** [go-gitea/gitea#17527]
### Gitea Version

latest Docker image

### Git Version

latest Docker image

### Operating System

latest Docker image

### How are you running Gitea?

latest Docker image

### Database

PostgreSQL

### Can you reproduce the bug on the Gitea demo site?

Yes

### Description

When migrating a repository from Github with `"pull_request": true`. I get an error saying: `MigrateRepository: 'PullRequests' not supported`. When running the migration throug the UI everything goes as expected.

Data:
```
{
  "auth_password": "*********************",
  "auth_username": "username",
  "clone_addr": "https://github.com/my-org/my-repo",
  "private": true,
  "pull_requests": true,
  "releases": true,
  "repo_name": "my-repo",
  "repo_owner": "richard",
  "service": "git",
  "wiki": true
}

```

Logs:
```
2021/11/02 17:27:01 Started POST /api/v1/repos/migrate?token=******** for 172.22.0.1:37090
2021/11/02 17:27:18 ...i/v1/repo/migrate.go:242:handleMigrateError() [E] MigrateRepository: 'PullRequests' not supported
2021/11/02 17:27:18 ...i/v1/repo/migrate.go:197:func1() [E] DeleteRepository: repository does not exist [id: 190, uid: 14, owner_name: , name: ]
2021/11/02 17:27:18 Completed POST /api/v1/repos/migrate?token=********  500 Internal Server Error in 17.6840749s
```

What is going wrong?

**Comment by lunny** [comment]
{
"service": "github"
}

**Comment by kad-beumer** [comment]
That made do 1 step forward. Thanks.

But it now gives the error: 
`{"message":"GET https://api.github.com/repos/my-org/my-reop: 404 Not Found []","url":"http://localhost:3000/api/swagger"}`

Its a private repo but my PAT has access to it.
Any advise?

**Comment by kad-beumer** [comment]
No difference if I change from `auth_password` to `auth_token`. The `404` error remains

**Comment by kad-beumer** [comment]
Thanks. That fixed it.
