### ISSUE TITLE
Delete button for branches in confusing

### ISSUE THREAD

**Issue by gdstewart** [go-gitea/gitea#17535]
Presently, the "Delete" button for branches is a trash bin icon: 
![image](https://user-images.githubusercontent.com/23243532/140058371-23a59436-96a6-4ffc-8b69-fd813fa1887d.png)
This is unambiguous and provides satisfactory warning that what you're going to do is pretty severe. 

However, on the page to confirm the deletion, the "No" button is ALSO a trash bin icon:
![image](https://user-images.githubusercontent.com/23243532/140058670-423eb471-5bd3-45e2-893d-00741c7130c8.png)

To me, this is confusing. I simply do not want to click on the "No" button even though I know it is innocuous because it uses the same icon. With the trash bin icon being used for "No" the logic seems to be that you are going to "trash" or delete your request to delete the branch. 

I think an X icon might be preferred in this case, while the "Yes" button could be the trash bin icon. In any case this gave me pause and I wanted to see if anyone else had similar thoughts on this.

**Comment by delvh** [comment]
Just confirmed it on try.gitea.io and a custom 1.15.6 server. That problem is present in both servers.
I agree that this is confusing, and a potential solution should be backported to both 1.14 and 1.15. (Although I don't know whether 1.14 has the same problem but I would guess so.)

**Comment by delvh** [comment]
Made a fix.
Using the trash icon on the yes button would have been far more complicated, so I opted for the simple solution.
