### ISSUE TITLE
Where is the /assets/img/ directory in the container?

### ISSUE THREAD

**Issue by vuhuythanh1995** [go-gitea/gitea#17542]
### Gitea Version

1.15.5

### Git Version

2.30.2

### Operating System

Container.

### How are you running Gitea?

docker-compose.

### Database

PostgreSQL

### Can you reproduce the bug on the Gitea demo site?

No

### Description

After running docker-compose including Gitea 1.15.5 and Postgres 10, I got into the container and did the data extraction.
After I run the command:
$ gitea -c /etc/gitea/app.ini embedded  list
I see the directories are: options/ public/ templates/ 
I know those are customizable folders and i want to change the logo of my gitea homepage.
after i do put the image in public/img folder and change the image path in template/ nothing happens on my gitea homepage.
I have checked the link of the logo on the website, after opening the image in a new tab I see the current image path is:
http://***.***.*.**:3333/assets/img/logo.svg
How can i extract assets/ folder.

**Comment by wxiaoguang** [comment]
https://docs.gitea.io/en-us/customizing-gitea/#serving-custom-public-files

`For example, a file image.png stored in $GITEA_CUSTOM/public/, can be accessed with the url http://gitea.domain.tld/assets/image.png.`

Please read the document carefully.
