### ISSUE TITLE
Global configuration to prevent users from deleting their own account

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#1756]
- Gitea version (or commit ref):25d6e2a
- Git version:2.11.2
- Operating system:ubuntu/docker
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
There should be a default admin level configuration to prevent users from deleting their own account.

This has currently led to an issue on our installation, wherein, we use only the SMTP login source.
A user logs in once, admin sets their repo limit to 0.
The user deletes their account and signs back in, this is making the repo setting go back to -1 (unlimited)

This is just one problem.
We do not want any of the users of our ORG to have the ability to delete their own accounts for multiple other reasons as well.

**Comment by DblK** [comment]
I will try to work on it.
But first, I have some questions:
1) Should it be linked to the authentification Source (Ex with LDAP EDIT)

![image](https://cloud.githubusercontent.com/assets/832617/26243188/41e857fa-3c8b-11e7-9bf3-9f39adaa9830.png)

2) Or more simply add to the user modification page (in admin mode) with default value to prevent deletion

![image](https://cloud.githubusercontent.com/assets/832617/26243169/320ecb84-3c8b-11e7-97da-a43df2b53c97.png)

3) Somewhere else?

**Comment by ghost** [comment]
My vote is for Approach 1

I would also like to suggest Approach 3, have a global variable in app.ini, so that it would apply to every source and prevent account deletion altogether.

Also, IMO, the administrator should have absolute authority over this and hence we should avoid placing any UI configurable element.

**Comment by DblK** [comment]
I will wait for comments from other members to see which implementation should be done.
The approach 3 sounds good too.

**Comment by lunny** [comment]
Maybe a global option to disable_user_suicide

**Comment by DblK** [comment]
When you said global option, you mean inside conf.ini?

**Comment by ghost** [comment]
I'm currently using the app.ini file to define gobal configuration variables.

**Comment by lunny** [comment]
@DblK yes

**Comment by lunny** [comment]
should be resolved by #20549

**Comment by lunny** [comment]
Fixed by #29275
