### ISSUE TITLE
Migrated milestone may be duplicated.

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#17567]
![image](https://user-images.githubusercontent.com/81045/140611033-c36b7fdc-5719-4cfb-9c59-a6c08594dc5a.png)

**Comment by yp05327** [comment]
It seems that this issue can be reproduced stably
![image](https://github.com/go-gitea/gitea/assets/18380374/5631363d-09e5-473b-ada5-796aa3c30437)
