### ISSUE TITLE
Failed mirror will be not deleted

### ISSUE THREAD

**Issue by somera** [go-gitea/gitea#17571]
### Gitea Version

1.15.6

### Git Version

2.25.1

### Operating System

Ubuntu 20.04.3

### How are you running Gitea?

Self hostet

### Database

PostgreSQL

### Can you reproduce the bug on the Gitea demo site?

Yes

### Description

Just try to mirror an not existing project. Gitea (can be resproduce on Gitea demo site with 1.60.x too) creates a new project. Afte the error will be shown, the created project will be not remowed. If you open it in Giteate (https://try.gitea.io/somera/nethogss) than you see HTTP ERROR 500. The project could be deleted only in the admin repo view.

This bug exists (I think) since Gitea 1.15.4 or 1.15.5.

**Comment by zeripath** [comment]
Does https://try.gitea.io/somera/nethogss/settings work?

**Comment by somera** [comment]
Yes, this works in gitea 1.15.6. I didn't try this before.

But you changed behavior in the latest versions. Was there a reason for this?

**Comment by zeripath** [comment]
When you say mirror, exactly what do you mean? A repository migration from git, github, gitea or other? 

Do you have any logs from when the mirror failed?

**Comment by somera** [comment]
> When you say mirror, exactly what do you mean? A repository migration from git, github, gitea or other?

Yes, just start new mirror.

> Do you have any logs from when the mirror failed?

Nope. I can't see any error. Cause I disabled logging. You can reproduce it on your local instance too.

Try with this: https://github.com/screeps/driverr.git (right URL is https://github.com/screeps/driver.git). With the wrong URL (or if there are some problems cause GitHub is temporary blocking you) Gitea creates an corrupted repo. In the earlier Gitea versions this repo was automatically deleted.

**Comment by zeripath** [comment]
> > When you say mirror, exactly what do you mean? A repository migration from git, github, gitea or other?
> 
> Yes, just start new mirror.

This is not enough information.  Using the Git migration does not reproduce the bug - it appears I need to use the Github migration to reproduce this.

> > Do you have any logs from when the mirror failed?
> 
> Nope. I can't see any error. Cause I disabled logging. You can reproduce it on your local instance too.

!!

Please help us to help you. Give us logs in future. 

None of us are paid to work on Gitea it's not fair to make us run around reproducing things.

> Try with this: https://github.com/screeps/driverr.git (right URL is https://github.com/screeps/driver.git). With the wrong URL (or if there are some problems cause GitHub is temporary blocking you) Gitea creates an corrupted repo. In the earlier Gitea versions this repo was automatically deleted.

Thanks! This is the information I needed to reproduce. 

---

```
2021/11/06 22:48:14 ...ers/web/repo/view.go:585:checkHomeCodeViewable() [E] models.GetMigratingTask: task is not exist [id: 0, repo_id: 166, type: 0]
2021/11/06 22:48:14 ...s/context/context.go:185:HTML() [D] Template: status/500
```

This is the Error.

To reproduce:

* Create a new migration from Github using a non-existent repository: e.g.  https://github.com/screeps/driverr.git

**Comment by somera** [comment]
> > > When you say mirror, exactly what do you mean? A repository migration from git, github, gitea or other?
> > 
> > 
> > Yes, just start new mirror.
> 
> This is not enough information. Using the Git migration does not reproduce the bug - it appears I need to use the Github migration to reproduce this.
> 
> > > Do you have any logs from when the mirror failed?
> > 
> > 
> > Nope. I can't see any error. Cause I disabled logging. You can reproduce it on your local instance too.
> 
> !!
> 
> Please help us to help you. Give us logs in future.

I run my gitea instance with logging. But this slows it down. And I follow you words about logging (#15412)

- Please, just set STACKTRACE_LEVEL = none it's not helpful except in very very rare levels.
- Please, if it is at all possible, when sending us logs, send all of your logs to the console as it is the simplest way to get them all together and nicely interleaved.
- Setting the LEVEL=error for everything including the xorm logger is the reason you're not seeing any SQL logs.
- In this case SQL logs will be helpful

and I had no logg error message in my logs. I can't every time edid the config and restart my Gitea instance. In this case I reproduced the problem on the Gitea try instance. And I was sure, you can check the logs there.

> None of us are paid to work on Gitea it's not fair to make us run around reproducing things.

This is right. but at the end you have to reproduce the problem. This is the development way. If it'S easy to reproduce. Or not.

> > Try with this: https://github.com/screeps/driverr.git (right URL is https://github.com/screeps/driver.git). With the wrong URL (or if there are some problems cause GitHub is temporary blocking you) Gitea creates an corrupted repo. In the earlier Gitea versions this repo was automatically deleted.
> 
> Thanks! This is the information I needed to reproduce.
> 
> ```
> 2021/11/06 22:48:14 ...ers/web/repo/view.go:585:checkHomeCodeViewable() [E] models.GetMigratingTask: task is not exist [id: 0, repo_id: 166, type: 0]
> 2021/11/06 22:48:14 ...s/context/context.go:185:HTML() [D] Template: status/500
> ```
> 
> This is the Error.

I don't see this errro on my instance. And my logging is set to error.

I see this error (I added stacktraces):

```
==> gitea.log <==
2021/11/07 00:12:36 modules/task/task.go:54:handle() [E] Run task failed: GET https://api.github.com/repos/screeps/driverr: 404 Not Found []
        /source/modules/task/task.go:54 (0x202e232)
        /source/modules/queue/workerpool.go:408 (0x1e59e68)
        /source/modules/queue/workerpool.go:261 (0x1e5c824)
        /usr/local/go/src/runtime/asm_amd64.s:1371 (0x47aa80)
```

> To reproduce:
> 
> * Create a new migration from Github using a non-existent repository: e.g.  https://github.com/screeps/driverr.git

Or If you will be blocked by too many requests (HTTP ERROR 429) Gitea is creating an corrupted repo since 1.15.5. Before this version the mirror was deleted.

**Comment by somera** [comment]
The other error message was:

`2021/10/23 13:15:38 modules/task/task.go:54:handle() [E] Run task failed: GET https://api.github.com/repos/jcuda/jcuda: 403 API rate limit of 60 still exceeded until 2021-10-23 13:23:45 +0200 CEST, not making remote request. [rate reset in 8m07s]`
