### ISSUE TITLE
Only admin should have right to edit any comment

### ISSUE THREAD

**Issue by camlafit** [go-gitea/gitea#17585]
### Gitea Version

1.14.1

**edited by team members to hide irrelevant information**

### Description

On organization we have create a team with write permission on repository. Any user in this team can edit any issue comment .

Edition should be move to "administrator access" to prevent any security issue

![Capture d’écran de 2021-11-08 10-10-17](https://user-images.githubusercontent.com/209915/140714632-f4c0b2cd-6672-409c-9ae1-69072c9b973b.png)

![Capture d’écran de 2021-11-08 10-09-10](https://user-images.githubusercontent.com/209915/140714637-1a1bd10f-d8c2-4021-a2b1-46b741f21927.png)

**Comment by wxiaoguang** [comment]
Is the behavior the same as GitHub? For example, as a team member, I can edit your comment (I added `**edited by team members to hide irrelevant information**`)

**Comment by JLuc** [comment]
I dont see your `**edited by team members to hide irrelevant information**` edit anywhere except in your own post. Did you edited https://github.com/go-gitea/gitea/issues/17585#issue-1047206951 ?

**Comment by wxiaoguang** [comment]
![image](https://user-images.githubusercontent.com/2114189/140724940-485e7c39-ccd5-4bea-bcb9-1d3a61f4097f.png)

**Comment by JLuc** [comment]
yep.

**Comment by lunny** [comment]
On a team, if you remove the write permission to issue/pullrequest unit, the team members will not have the permission to edit the comments.

**Comment by camlafit** [comment]
Hello

Indeed if we disable issues/Pull request right we lost comment edit option. But we lost also some other behavior as manage tag, milestone, ....

If user as write permission looks logic to also edit tag, milestone to qualify code contribution. But edit comment from other contributors looks a bit different.

Should be better to move this behavior "edit comment"  if use has admin permission.

**Comment by zeripath** [comment]
As a non-admin but maintainer of this project - I frequently use my comment editing power to fix up rendering problems in other people's comments, rename issues and pulls, and to make the pull request initial comments closer to what was pulled.

It may seem like putting words into other people's mouths but I think this kind of editing functionality is important. The comments on an issue or PR are not an audit of what was said - they're a form of documentation.

**Comment by camlafit** [comment]
Hello

Yes I see this use case. In our use case we have a different logic. We want allow default contribution on some organization and we allow write permission. 
But editing comment looks a bit too important, with as you said " putting words into other people's mouths" and we want preserve this.

Looks possible in this case to propose a sub option to allow/restrict message edition ? Then we will manage these two use case ?

**Comment by lunny** [comment]
`Issue` unit permission is not the same as `Code`. With read permission of unit `Issue`/`PullRequest`, team members could post issue and post comment but cannot edit comment. With write permission of unit `Issue`/`PullRequest`, team members could edit issues/comments. I want to know why you want to give all members of org write permission of unit `issue`/`pullrequest`.

**Comment by camlafit** [comment]
Hello

We have a collaborative forge where peer can approve PR/MR/commit on same repository. Then we have open enable write contribution but we don't want user rewrite collaborator content as issue.

For example at https://git.spip.net/spip-contrib-extensions all account are set to contrib team. Then all could be contribute as peer but should not be admin (as in this case edit other comment )

**Comment by fnordsh** [comment]
One way to mitigate this issue would be an edit history like GitHub has. I would be okay with other people editing my comments if these edits are documented and attributable.

**Comment by fnordsh** [comment]
> `Issue` unit permission is not the same as `Code`. With read permission of unit `Issue`/`PullRequest`, team members could post issue and post comment but cannot edit comment. With write permission of unit `Issue`/`PullRequest`, team members could edit issues/comments. I want to know why you want to give all members of org write permission of unit `issue`/`pullrequest`.

Could you explain how I can allow a group of people to push code, but only post/read issues?

**Comment by fnordsh** [comment]
@zeripath 
> As a non-admin but maintainer of this project - I frequently use my comment editing power to fix up rendering problems in other people's comments, rename issues and pulls, and to make the pull request initial comments closer to what was pulled.
> 
> It may seem like putting words into other people's mouths but I think this kind of editing functionality is important. The comments on an issue or PR are not an audit of what was said - they're a form of documentation.

Maybe a moderator role would be the right thing for this use case. (But even if editing is restricted to moderators and admins, I still think there should be an indicator that the comment has been edited, and by whom.)

**Comment by lunny** [comment]
It seems one team cannot implement it. You have to have two teams. One team for people who could push code, another for post/read issues.

**Comment by fnordsh** [comment]
Thank you! For my current use case this is a feasible workaround, although I don't think this would scale well.
TBH, I find Giteas permission model a bit weird - giving a team the same permissions to every repository it is assigned to seems counter-intuitive to me. Maybe I should read up on the reasoning behind this.

**Comment by lunny** [comment]
This could be resolved by #16859

**Comment by camlafit** [comment]
Hello

Yes could be optimized by this issue. :+1:  But looks as a big job on long time.

Waiting this evolve is it possible to provide any work around ?

**Comment by gmingen** [comment]
@camlafit See the [@lunny's comment](https://github.com/go-gitea/gitea/issues/17585#issuecomment-966263814) above. It's not pretty, but it does work for me.

**Comment by lunny** [comment]
@camlafit @gmingen I sent a PR #17811 and I think it could be merged into v1.16.
