### ISSUE TITLE
GlobalInit() [F] SQLite3 is set in settings but NOT Supported

### ISSUE THREAD

**Issue by MarcelXia** [go-gitea/gitea#17600]
### Gitea Version

Gitea v1.16.0+dev-481-gaa4355ba1 built with GNU Make 3.81, go1.17.3

### Git Version

Git Version: 2.33.0, Wire Protocol Version 2 Enabled

### Operating System

Mac Monterey

### How are you running Gitea?

Downloaded (pulled) latest version and build it with make
```
./gitea web -C ~/stack/Gitea -c custom/conf/app.ini
```

### Database

SQLite

### Can you reproduce the bug on the Gitea demo site?

No

### Description

When I start it, I see
```
021/11/09 17:06:35 ...s/setting/setting.go:541:SetCustomPathAndConf() [W] Using 'custom' directory as relative origin for configuration file: '/Users/marcelloh/stack/Gitea/custom/conf/app.ini'
```
lots of logging and it ends with this:
```
2021/11/09 17:06:35 ...s/storage/storage.go:189:initRepoArchives() [I] Initialising Repository Archive storage with type: 
2021/11/09 17:06:35 ...les/storage/local.go:46:NewLocalStorage() [I] Creating new Local Storage at /Users/marcelloh/data/go-tools/Gitea/data/repo-archive
2021/11/09 17:06:35 routers/init.go:133:GlobalInit() [F] SQLite3 is set in settings but NOT Supported
```

**Comment by MarcelXia** [comment]
That should have been the message instead of the "SQLite3 is set in settings but NOT Supported"
something like : "SQLite3 is set in settings but Gitea wasn't build with that option. See : https://docs.gitea.io/en-us/install-from-source/#build"
Would have saved a lot of time :-) Thanks for the answer.

**Comment by wxiaoguang** [comment]
Thank you for the suggestion, the text is improved in the latest Gitea code:

```
SQLite3 support is disabled, but it is used for database setting. Please get or build a Gitea release with SQLite3 support.
```
