### ISSUE TITLE
Support edit online like vscode.dev

### ISSUE THREAD

**Issue by winxxp** [go-gitea/gitea#17604]
### Feature Description

Support edit online like vscode.dev, or like github.com  press key to '.' entry in to vscode

**Comment by lunny** [comment]
Could vscode.dev be self hosted?

**Comment by wxiaoguang** [comment]
Something like https://github.com/cdr/code-server . Maybe the author prefers something like https://github.dev/go-gitea/gitea

However, being a full function IDE seems not the goal of Gitea in recent future. Users can setup their own online vscode IDE. Integrating an full IDE inside Gitea is really a huge project.

**Comment by lunny** [comment]
Yes, I mean Gitea can open some files in external self-hosted online editor if there some protocol.

**Comment by silverwind** [comment]
> if there some protocol

That protocol can just be git via https, [JS can do it](https://github.com/isomorphic-git/isomorphic-git).

**Comment by techknowlogick** [comment]
Closing as other solutions are probably a better fit for this, such as gitpod, coder (as mentioned above), and many others.
