### ISSUE TITLE
Pull request #947 / #1753 (still) breaks HTTPS clone/push/pull to/from "master" when logged in as Admin 

### ISSUE THREAD

**Issue by wyattoday** [go-gitea/gitea#1761]
- Gitea version (or commit ref): https://github.com/go-gitea/gitea/commit/281a0389c10b95a48045ebb161ad5492226bad78 or https://github.com/go-gitea/gitea/pull/1753
- Git version: 2.13
- Operating system: Ubuntu 16.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

This is a followup to the issue that was closed (but not fixed): https://github.com/go-gitea/gitea/issues/1751

The proposed fix still breaks things (or leaves things broken). For example, as an admin user, when cloning an existing repository, I get an empty directory:

```
git.exe clone --progress -v "https://example.com/git/repository_name.git" "C:\Users\USERNAME\Documents\repository_name"

Cloning into 'C:\Users\USERNAME\Documents\repository_name'...
warning: You appear to have cloned an empty repository.

Success (641 ms @ 5/19/2017 8:08:51 AM)
```

Other things are broken as well (pulling still broken, haven't tried pushing yet).

Rolling back to before https://github.com/go-gitea/gitea/commit/fd6034aaf23af1ce03bcba0babcbe7675ce093ee fixes things for me.

## Screenshots

**If this issue involves the Web Interface, please include a screenshot**

**Comment by sapk** [comment]
cc @lunny maybe we should add integration test to validate action as an admin in a other PR.

**Comment by lunny** [comment]
@sapk you are right! I remember I have sent a PR to add clone test, but not merged?

**Comment by sapk** [comment]
Thx I will have a look at #1682
