### ISSUE TITLE
Edit history for Issue and PR comments

### ISSUE THREAD

**Issue by fnordsh** [go-gitea/gitea#17617]
### Feature Description

It would be very helpful if issue and pr comments had an edit history, like github has.

Every comment that has been edited should have a message informing the user about when and by whom the comment was last edited. Ideally, it should also have a way to view older versions and/or diffs.

Currently, there is no such indication, so people could, for example, make a popular comment and after getting approval from others change the content of the original comment to create a false impression for anyone coming late to the discussion.

This is made worse by the fact that by default, every user with write permissions can change every other user's comments **without any indication that this has happened** - see #17585.

### Screenshots

![image](https://user-images.githubusercontent.com/13398150/141315148-97dd7386-0324-4577-a5d1-eaccb163bda9.png)

**Comment by wxiaoguang** [comment]
We already have it (in 1.16, I submitted the PR)

* https://github.com/go-gitea/gitea/pull/16909

Try it on try.gitea.io
