### ISSUE TITLE
Allow modification of migration items after initial migration

### ISSUE THREAD

**Issue by MPeti1** [go-gitea/gitea#17628]
### Feature Description

I think it would be great if it would be possible to change what is to be migrated after the initial migration, in case of a migrated repository that has mirroring enabled.
Specifically, what I was thinking about is enabling migration of certain kinds of data that wasn't enabled before. I see that this might be problematic with data that has a counted id, like issues and PRs, but this could be useful at least for Wikis, and maybe other things too with appropriate restrictions.

### Screenshots

The migration items I was speaking about: 
![image](https://user-images.githubusercontent.com/9215491/141516715-d51aa5be-387e-48ee-b59d-4126cb4114a3.png)

**Comment by lunny** [comment]
OK. Migrating Wiki should not require token.

**Comment by MPeti1** [comment]
Thank you, that was a problem too that I had.
Is it possible to enable/disable migration of the Wiki after the fact, though?
