### ISSUE TITLE
Table project warnings after upgrade from 1.13 to 1.15

### ISSUE THREAD

**Issue by pboguslawski** [go-gitea/gitea#17629]
### Gitea Version

1cec7f5ab5e4a02b68a4223f1ad0166118a6e953

### Git Version

2.30.2

### Operating System

Debian 11

### How are you running Gitea?

Build from github sources.

### Database

MySQL

### Can you reproduce the bug on the Gitea demo site?

No

### Description

After upgrading from 1.13 to 1.15 warnings are thrown on gitea startup:

```
2021/11/12 21:37:00 ...om/urfave/cli/app.go:524:HandleAction() [W] Table email_address Column lower_email db nullable is true, struct nullable is false
2021/11/12 21:37:00 ...om/urfave/cli/app.go:524:HandleAction() [W] Table external_login_user column avatar_url db type is TEXT, struct type is VARCHAR(255)
2021/11/12 21:37:00 ...om/urfave/cli/app.go:524:HandleAction() [W] Table project column board_type db type is INT(11), struct type is INT UNSIGNED
2021/11/12 21:37:00 ...om/urfave/cli/app.go:524:HandleAction() [W] Table project column type db type is INT(11), struct type is INT UNSIGNED
```

Accroding to https://github.com/go-gitea/gitea/issues/16393 executing `
gitea doctor recreate-table email_address external_login_user project` should resolve issue but only email_address and external_login_user warnings disappear but project table warnings still exist. Repeating only for project table...

```
$ gitea doctor recreate-table project
2021/11/12 21:51:21 ...s/setting/setting.go:902:NewContext() [I] Default UI Location is Europe/Warsaw
2021/11/12 21:51:21 ...om/urfave/cli/app.go:405:RunAsSubcommand() [I] PING DATABASE mysql
2021/11/12 21:51:21 ...ations/migrations.go:444:func1() [I] Recreating Table: project for Bean: Project
2021/11/12 21:51:22 ...om/urfave/cli/app.go:405:RunAsSubcommand() [W] Table project column board_type db type is INT(10) UNSIGNED, struct type is INT UNSIGNED
2021/11/12 21:51:22 ...om/urfave/cli/app.go:405:RunAsSubcommand() [W] Table project column type db type is INT(10) UNSIGNED, struct type is INT UNSIGNED
```
...does not help:

```
2021/11/12 22:02:52 ...om/urfave/cli/app.go:524:HandleAction() [W] Table project column board_type db type is INT(10) UNSIGNED, struct type is INT UNSIGNED
2021/11/12 22:02:52 ...om/urfave/cli/app.go:524:HandleAction() [W] Table project column type db type is INT(10) UNSIGNED, struct type is INT UNSIGNED
```

Warnings in logs should not be ignored. How to fix it?

**Comment by pboguslawski** [comment]
Same problem after upgrade from 1.13 to 1.16.

**Comment by zeripath** [comment]
These can be ignored. They are a bug with xorm's matching of the inferred schema with that of the struct.

Please raise a bug at https://gitea.com/xorm/xorm

**Comment by pboguslawski** [comment]
> These can be ignored. 

Ignoring errors/warnings in logs is bad habit and should be avoided. 

> Please raise a bug at https://gitea.com/xorm/xorm

Raised:
https://gitea.com/xorm/xorm/issues/2110
