### ISSUE TITLE
Discussion tab for project

### ISSUE THREAD

**Issue by trymeouteh** [go-gitea/gitea#17637]
### Feature Description

I would like to suggest allowing projects to have a discussion tab just like some projects offer on Github such as this one in the link below.

Discussions is essentially a forum within the project and it is a good place to discuss and ask questions instead of creating issues for a discussion or question on a project.

https://github.com/loki-47-6F-64/sunshine/discussions

**Comment by techknowlogick** [comment]
closing as dupe of https://github.com/go-gitea/gitea/issues/14562
