### ISSUE TITLE
Ambiguous "Remove Linked Account" dialog

### ISSUE THREAD

**Issue by MmAaXx500** [go-gitea/gitea#17634]
### Gitea Version

1.15.6

### Operating System

Windows 10 21H1

### Browser Version

Firefox 94.0.1

### Can you reproduce the bug on the Gitea demo site?

Yes

### Description

(I choose Yes above because I have to chose one, but I did not test because I cannot link an account)
When I try to unlink a linked account, the "Remove Linked Account" is ambiguous.
The dialog shows a big trash can at the top center, and we have two buttons to choose from: a red "No" with a trash can and a green "Yes" with a check mark.
It took me a few seconds to figure out that the green "Yes" with the check mark is the delete button and the red "No" with the trash can is the cancel button.

### Screenshots

![image](https://user-images.githubusercontent.com/36025825/141655755-eeea428d-dbc7-4041-952d-5c4d2259dca7.png)

**Comment by delvh** [comment]
I already fixed that in #17537.
1.15.7 won't have this issue anymore.
