### ISSUE TITLE
Federation

### ISSUE THREAD

**Issue by trymeouteh** [go-gitea/gitea#17636]
### Feature Description

I would like to suggest allowing gitea instances to be able to connect to other instances and be federated. Simular to how federated platforms work such as Mastodon, Plemora and Peertube where you can have an account on gitea.com and use that account to work in repositories and projects on other instances like mygitea.net.

And to have the ability for those who host a gitea instance on weather to federate or limitations on federation.

**Comment by techknowlogick** [comment]
Closing as dupe as federation has been requested previously, and we have applied for a grant to work on this. please see: https://github.com/go-gitea/gitea/issues/16827
