### ISSUE TITLE
Support clone filter

### ISSUE THREAD

**Issue by LukeMauldin** [go-gitea/gitea#17656]
### Feature Description

When trying to execute following command receive error:
`git clone --filter=blob:none --no-checkout https://XXXXX`
Error: `filtering not recognized by server, ignoring`

Running Gitea 1.15.6
Git: 2.33.1

**Comment by a1012112796** [comment]
you can enable this git feature by run ``git config --global uploadpack.allowFilter true`` on the server.

**Comment by LukeMauldin** [comment]
That worked, thank you
