### ISSUE TITLE
Add additional Prometheus metrics

### ISSUE THREAD

**Issue by laurivosandi** [go-gitea/gitea#17653]
### Feature Description

It's great that people are aware of Prometheus, but what is the usefulness of metrics added in #678 ? 
Realistically these can't be used for alerting.

How about we add some actually useful metrics:
- Successful/failed SSH login attempts
- Successful/failed login attempts via web
- Currently open TCP connections (recently our Gitea gets hammered by DDoS attacks)
- HTTP response latency histogram
- Errors encountered while interacting with Git repos
- Failed/successful webhook calls

These were just few to mention. Some of these can be handled by haproxy that sits in front of Gitea which is the case for us of course...

**Comment by laurivosandi** [comment]
If I am reading right Gitea uses Chi framework so enabling some of those metrics is trivial simply by adding, just make sure no high entropy labels are included: https://pkg.go.dev/github.com/m8as/go-chi-metrics

**Comment by lunny** [comment]
Merged into #14724
