### ISSUE TITLE
Redirect Repo URLs on User/Org rename

### ISSUE THREAD

**Issue by silverwind** [go-gitea/gitea#17655]
### Feature Description

If a repo is renamed, the old repo URL will redirect to the new one. This feature is not present when a user or org is being renamed, while it would definitely be nice to have to allow an easy transition to the new URL.

Edit: Did some testing: Redirects on the user/org pages are already present, they are just missing for the repos.

**Comment by lunny** [comment]
The feature is similar as `UserRedirect` but could be named `RepoRedirect`.
- when rename a repo, add a new record into table `repo_redirect`
- when visit a repo, if repo is not exist, then try to get the new location from `repo_redirect`
- when creating a new repository, the same repo path must be removed from table `repo_redirect`
- when delete a repository, the records on `repo_redirect` should be deleted

**Comment by silverwind** [comment]
Would it interfere with the existing repo redirect mechanism that triggers on repo rename? I did not check the code, but maybe we could re-use part of that system, but also trigger it on user/org rename.

**Comment by lunny** [comment]
Yes, the userredirect should be also considered. I have updated my above comment.
