### ISSUE TITLE
FreeBSD binary release

### ISSUE THREAD

**Issue by LukeMauldin** [go-gitea/gitea#17651]
### Feature Description

Would it be possible for you to add FreeBSD pre-compiled binaries to your binary releases page?

**Comment by schrodyn** [comment]
Would be great to see this project support FreeBSD. While I can build it myself it would be handy to just grab the release as needed. FreeBSD is just as important an OS as Linux, Darwin and Windows.

**Comment by hbokh** [comment]
Any update on this request?
According to Santa, we're not on the naughty list! 🎅🏼

**Comment by lafriks** [comment]
I think problem mostly is cross compiling to freebsd version that that requires CGO using drone CI (sqlite, pam etc)

**Comment by 6543** [comment]
https://github.com/techknowlogick/xgo/issues

I guess an upstream issue would make more sense ...

**Comment by lafriks** [comment]
> https://github.com/techknowlogick/xgo/issues
> 
> I guess an upstream issue would make more sense ...

xgo can not be used in this case as you need freebsd host (drone runner on freebsd host) to do this

**Comment by techknowlogick** [comment]
closed by https://github.com/go-gitea/gitea/pull/22397
