### ISSUE TITLE
Upgrading from 1.14.3 to 1.15.6 fails

### ISSUE THREAD

**Issue by RobinBeismann** [go-gitea/gitea#17669]
### Gitea Version

1.14.3

### Operating System

Windows Server 2019

### How are you running Gitea?

- Binary downloaded from Gitea Artifacts
- Service running as Windows Service with MSSQL as Backend

### Database

MSSQL

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/RobinBeismann/7103d48f9f7e1849bbf215fafab65976

### Description

I tried upgrading from 1.14.3 to 1.15.6 fails by replacing the binary as I'm used to, however this time the instance didn't start up as it tries to insert into a table where 'id' can't be null but it is not specified in the SQL Statement that the upgrade wizard is running.
To me, it looks like this should have been set to autoincrement there but it wasn't by the already applied SQL DDL Upgrades.

**Comment by lunny** [comment]
Why mssql wants to insert a NULL into the table?

**Comment by RobinBeismann** [comment]
The first column in that table is "id" and it is not specified in the INSERT query, since the table has no default, it throws that error.

**Comment by wxiaoguang** [comment]
I think that table lost the `auto increment` of column `id`.

Can you try to make the `email_address.id` auto increment?

**Comment by RobinBeismann** [comment]
That did the trick, thanks. I'm wondering how this happened through, those columns are fine on the prod instance.

**Comment by wxiaoguang** [comment]
Maybe the problem is caused by some old bugs in the migration code. IIRC the migration of EmailAddress table got some bug fixes recently.
