### ISSUE TITLE
Repository Mirror storage space doubling

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#17678]
### Gitea Version

1.15.6

### Operating System

Ubuntu 20.04.3

### How are you running Gitea?

Run on k8s.

### Can you reproduce the bug on the Gitea demo site?

No

### Description

I pulled some repository mirror. When these repository are updated, the storage space of these repository mirror will continue to increase.

### Screenshots

<img width="1196" alt="iShot2021-11-17 09 45 08" src="https://user-images.githubusercontent.com/24501922/142094948-58165dd4-5f06-4c6f-bfa3-1f45820f7c43.png">
<img width="1351" alt="iShot2021-11-17 09 55 02" src="https://user-images.githubusercontent.com/24501922/142094990-5d3ba500-921f-4c0b-9a5e-6c4b7dae8f87.png">
<img width="1214" alt="iShot2021-11-17 09 45 28" src="https://user-images.githubusercontent.com/24501922/142095024-57e99abb-3159-49e8-a6c0-50e736006158.png">
<img width="1329" alt="iShot2021-11-17 09 45 53" src="https://user-images.githubusercontent.com/24501922/142095043-2ffa542c-241d-4e6c-86b2-e4bf80b2f78e.png">

**Comment by techknowlogick** [comment]
Are you using the Gitea helm chart?

**Comment by fanxin92** [comment]
> Are you using the Gitea helm chart?

I use docker.

**Comment by wxiaoguang** [comment]
1.15 is out-dated.

And you need to look into your local git repository to see how the size comes.

If no more clues, it's difficult for contributors to to provide helps.

Feel free to re-open if you have more clues or solutions.
