### ISSUE TITLE
Changing email addresses in 'user accounts' page doesn't synchronize to 'user emails' page

### ISSUE THREAD

**Issue by LYCN** [go-gitea/gitea#17681]
### Gitea Version

1.15.6

### Git Version

2.34.0

### Operating System

Windows Server 2019

### How are you running Gitea?

I downloaded 'gitea-1.15.6-gogit-windows-4.0-amd64.exe' from github release page, and  registered gitea as a windows service using:
`sc.exe create gitea start= auto binPath= "\"C:\gitea\gitea.exe\" web --config \"C:\gitea\custom\conf\app.ini\""`
Then gitea was configured following install page.

### Database

SQLite

### Can you reproduce the bug on the Gitea demo site?

No

### Description

When I try to change email addresses in 'Site Administration' -> 'User Accounts' page, it did successfully change the email in 'User Accounts' page. But the email addresses in 'Site Administration' -> 'User Emails' page remained the old ones, and didn’t synchronize with the configuration in 'User Accounts' page.

I'm not sure whether it is caused by the same problem mentioned in: https://github.com/go-gitea/gitea/issues/17519 

### Screenshots

![1](https://user-images.githubusercontent.com/17449127/142168833-74c7ed90-a7a9-40c1-ac9e-3ae83dec268b.PNG)
![2](https://user-images.githubusercontent.com/17449127/142168884-a260870f-f1fc-4c32-a28d-3bcd7408574c.PNG)

**Comment by lunny** [comment]
Could you confirm that #17549 also fix this issue?

**Comment by LYCN** [comment]
> 
> 
> Could you confirm that #17549 also fix this issue?



> 
> 
> Could you confirm that #17549 also fix this issue?

**Comment by LYCN** [comment]
> 
> 
> Could you confirm that #17549 also fix this issue?

I'm not sure about whether #17549 could fix this issue. I'm not familiar with Go language.

Besides, I just made a maloperation to close this issue. I have reopened this issue. Sorry for the inconvenience.

**Comment by lunny** [comment]
This should also be fixed by #17840
