### ISSUE TITLE
branch tab is invisible.

### ISSUE THREAD

**Issue by SJ2050cn** [go-gitea/gitea#17685]
### Gitea Version

1.15.6

### Operating System

centos7.9 docker20.10.10

### Browser Version

Microsoft Edge Version 95.0.1020.53 (Official build) (64-bit)

### Can you reproduce the bug on the Gitea demo site?

No

### Description

When I open my gitea website and enter one repository, **I can't find branch tab**. It seems ok in this morning, but I don't change any setting after than. 

### Screenshots

![error](https://user-images.githubusercontent.com/48412174/142178889-2e966978-350b-4882-9d6d-89ec84f4123e.png)

**Comment by lunny** [comment]
I think it's a deployment problem.

**Comment by wxiaoguang** [comment]
It's said that the problem is caused by incorrect nginx config. fixed from nginx config.
