### ISSUE TITLE
Internal Server Error when attempting to download archive via API

### ISSUE THREAD

**Issue by jotoho** [go-gitea/gitea#17689]
### Gitea Version

1.15.6

### Git Version

2.30.2

### Operating System

Raspberry Pi OS + Docker

### How are you running Gitea?

Running official docker image (tag: `1.15-linux-arm64`, id: `d7e5e9d96a5d269120a579a887efeae1589afb8d92ba4c03fe61264548e9af7f`) on an up-to-date version of Raspberry Pi OS (based on Debian bullseye).

TLS is handled by a Caddy reverse-proxy.

### Database

MySQL

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

https://gist.github.com/jotoho/e4813169969a9d0a669cd86169de14e8

### Description

I was attempting to learn how to use the API to download the files in a private repository and attempted using it with a public repo first to avoid needing to provide a token.

Unfortunately when I tried to access the archive for `master` via `/api/swagger` or curl, my server threw back a "500 Internal Server Error" message.

* Original repository: https://gitea.jotoho.de/jotoho/waituntil
* Reproduction repository (mirror): https://try.gitea.io/jotoho/waituntil

**Comment by jotoho** [comment]
Also, disregard that the post above says "MySQL" - it's actually MariaDB 10.5.13 running in another docker container.

**Comment by lunny** [comment]
You should use .../archive/master.zip if you want zip file

**Comment by jotoho** [comment]
> You should use .../archive/master.zip if you want zip file

Can you download the file from private repository non-interactively (using a script) by doing that? I presumed the API option is there to get the file without needing to access the website from a logged in browser.

**Comment by jotoho** [comment]
Oh, you probably meant adding `.zip` or something to the URL in the API! I thought you meant the URL normally used to download archives from the browser.

**Comment by lunny** [comment]
Yes, add the extension name `.zip`, `.tar.gz` or `.bundle`.

**Comment by jotoho** [comment]
@lunny Thanks for the advice and quick bugfix!
