### ISSUE TITLE
Restrict creating organisations by user

### ISSUE THREAD

**Issue by Schwobaland** [go-gitea/gitea#177]
Currently it's not possible to restrict, wether an user is allowed to create organisations. Would be very useful in enterprise context to control the repository.

**Comment by strk** [comment]
Agreed, are you up to provide a pull request ?

**Comment by Schwobaland** [comment]
yes - it's already working on local machine. Will provide pull request soon.

**Comment by thibaultmeyer** [comment]
Nice idea
