### ISSUE TITLE
CI fails with unknown permission problems

### ISSUE THREAD

**Issue by wxiaoguang** [go-gitea/gitea#17710]
These errors occur many times:

```
+ make backend
mkdir: cannot create directory '.make_evidence': Permission denied
make: *** [Makefile:251: .make_evidence/tags] Error 1
```

```
+ make unit-test-coverage test-check
Running unit-test-coverage -race -tags 'sqlite sqlite_unlock_notify'...
open /drone/src/coverage.out: permission denied
make: *** [Makefile:395: unit-test-coverage] Error 1
```

**Comment by silverwind** [comment]
Both seem like infrastructure issues to me.

**Comment by zeripath** [comment]
Is it possible that make is being called before the volumes are up?

**Comment by wxiaoguang** [comment]
A guess:

Maybe the problem is caused by that the gitea uid doesn't match on docker hosts.

For example, in `.drone.yml`, we use `user: gitea`, in `https://gitea.com/gitea/test-env/src/branch/master/Dockerfile`, we use `adduser gitea uid=1000`.

Is it possible that on some hosts, the uid of `gitea` is not 1000?


@lunny @techknowlogick

**Comment by wxiaoguang** [comment]
Another possibility, the drone dependency is incorrect. I just rewrite them in the PR.
