### ISSUE TITLE
u2f-api script should be moved to npm/webpack

### ISSUE THREAD

**Issue by silverwind** [go-gitea/gitea#17712]
### Feature Description

There is a [unversioned copy](https://github.com/go-gitea/gitea/blob/main/public/vendor/plugins/u2f/index.js) of what I think is a minified version of [`u2f-api`](https://github.com/grantila/u2f-api) that came in https://github.com/go-gitea/gitea/pull/3971. It should be moved to npm/webpack to become maintainable.

Maybe @jonasfranz can point out the source/version of this script.

**Comment by wxiaoguang** [comment]
I believe the code comes from https://github.com/github/u2f-api/blob/master/u2f-api-polyfill.js

Some fingerprints:

```
"U2F isn't supported over http, only https"
"U2F not supported"
ensureSupport
isSupported
formatRegisterRequest_
```

And most u2f-api we can find in npm they are all copied and modified from that one, they share same API interfaces, like:

* https://www.npmjs.com/package/u2f
* https://www.npmjs.com/package/u2f-api

**Comment by wxiaoguang** [comment]
As reported in 

* https://github.com/go-gitea/gitea/issues/17754

Maybe we should refactor this module too.

**Comment by silverwind** [comment]
I think it needs to be changed to use webauthn, see https://github.com/go-gitea/gitea/issues/6892.

**Comment by lunny** [comment]
@silverwind So maybe we could close this one and just continue in #6892, we could remove u2f-api and introduce webauthn in the same PR.

**Comment by silverwind** [comment]
Yes, u2f removal can come with the webauthn addition.
