### ISSUE TITLE
Gitea Maintenance Question

### ISSUE THREAD

**Issue by davydov-vyacheslav** [go-gitea/gitea#1772]
Hi,

I have a question about maintenance part of gitea.

As admin / owner of gitea instance I'd like:
- during upgrading get information about status of migration . If migration is not completed yet, the server returns 503 error per each request . It is a bit confused because I don't know, whether migration fails / service is not up during any reasons or just migration is still in progress
- My database locates at different host, and each time when for some reasons database connection lists, I'm receiving 503 error per each request. Again, when I have access only for UI part (from mobile device) it is hard to get insight the reason of this behavior. 

Is it possible to get some king of maintenance page to get status of each page connection and e.g. for database connection get ability to try to restore connection? Is it possible there get server.log content to identify possible reasons of 503 error myself without direct access to host?

P.S.
In my environment it is installed as daemon / service (Raspberry PI).

Thanks in advance,
Slava

**Comment by lunny** [comment]
I think 503 is returned from your reverse proxy since Gitea upgrade failed (i.e. nginx).

**Comment by davydov-vyacheslav** [comment]
The main problem (from my point of view) is that 503 error returns not because of failed migration but because migration is still in progress , and the situation is ambiguous to determine the actual root of 503 error

**Comment by lunny** [comment]
Yes. The Gitea web service will be started after migration completed.

**Comment by davydov-vyacheslav** [comment]
Is there a way to make some kind diagnostic page to determine the reason of site being down (actually up, but with errors or migration in progress) ?

**Comment by appIeboy** [comment]
<p align=right><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup>#1798 @lunny @tboerger @sapk @cez81 @geek1011 @lafriks @ethantkoenig @andreynering @DblK </sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></p>

**Comment by appIeboy** [comment]
<p align=right><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup>#1798 @lunny @tboerger @sapk @cez81 @geek1011 @lafriks @ethantkoenig @andreynering @DblK </sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></p>

**Comment by appIeboy** [comment]
<p align=right><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup>#1798 @lunny @tboerger @sapk @cez81 @geek1011 @lafriks @ethantkoenig @andreynering @DblK </sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></p>

**Comment by kolaente** [comment]
If you're using a reverse proxy, you could set up a 503-Errorpage with that
