### ISSUE TITLE
Forked repo: ability to update branch on PR level by maintainers

### ISSUE THREAD

**Issue by StanislavKharchenko** [go-gitea/gitea#17728]
### Feature Description

If branch was outdated then author of PR could click "Update branch" so it will be syncronized with upstream.
This option will be also very useful for reviewers/approvers.
When reviewer approving PR, the branch could become outdated. The approver should ask author to click to "Update branch".
Found merged PR, but I'm not sure that it about what we need:
https://github.com/go-gitea/gitea/pull/16125

So, steps are following:

1. Branch has restriction to merge in case if it outdated;
2. User#1 created a PR and assigned to reviewer;
3. Reviewer (maintainer of upstream repo) make approval; at this time base branch (upstream) got changes so PR became outdated;
4. Reviewer can't merge and should ask author to perform "Update branch". In this step we need to grant access to reviewers to make update PR branch by himself.

This should be similar to "Allow edits from maintainers" option on GitHub

**Comment by Gusted** [comment]
Just to get it clear:

In other words, if the creator of the PR(maybe anyone who can assign a reviewer) assigns a reviewer. That reviewer should have the permission to perform the "Update Branch" action. But that reviewer doesn't have write permissions in that repo where the PR is made?

**Comment by qwerty287** [comment]
As far as I understand this, it seems to be something like the "Allow edits from maintainers" option on GitHub. On GH, this means that everyone that has write access to the base repo can edit, push and update to the head branch (but only the head branch, the other branches are still read-only as long as they are not added as collaborators). You can select this if you create a new PR on GitHub from a forked repo. 

Step 7 on this site: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

**Comment by StanislavKharchenko** [comment]
Yes,
it should be like "Allow edits from maintainers" from GH.
