### ISSUE TITLE
Gitea does not start with docker installation on gitea:latest

### ISSUE THREAD

**Issue by Y0ngg4n** [go-gitea/gitea#17720]
### Gitea Version

Docker gitea:latest

### Git Version

Docker gitea:latest

### Operating System

Debian Bullseye

### How are you running Gitea?

I am running Gitea with Docker from Dockerhub with a Postgresql Database Docker Container

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/Y0ngg4n/8c18ea26a877590ffb32c72be62d0d7b

### Description

I can´t start the Docker container.

**Comment by techknowlogick** [comment]
Can you provide any logs?

**Comment by zeripath** [comment]
From your gist:

```
2021/11/18 22:18:23 models/models.go:233:NewEngine() [I] [SQL] CREATE UNIQUE INDEX "UQE_email_hash_email" ON "email_hash" ("email") [] - 1.136167ms
2021/11/18 22:18:23 routers/common/db.go:33:InitDBEngine() [E] ORM engine initialization attempt #7/10 failed. Error: sync database struct error: pq: could not create unique index "UQE_email_hash_email
```

This suggests that your email_hash table contains duplicate email entries.

Now iirc you should be able to just delete the contents of that table and it will be recreated as needed.

**Comment by lunny** [comment]
That means there are duplicated content on email_hash table and `email` column is not unique index before, but now it is.

**Comment by Y0ngg4n** [comment]
Ok i have deleted the duplicated hash. works again now :)
