### ISSUE TITLE
Allow on-demand loading of too large file diffs

### ISSUE THREAD

**Issue by jpraet** [go-gitea/gitea#17738]
### Feature Description

On gitea, file diffs are suppressed if they are too large
(app.ini MAX_GIT_DIFF_LINES)
![image](https://user-images.githubusercontent.com/2212615/142729164-6e454e6b-fdc1-4806-9aba-31799a5eb3fe.png)
or contain lines that are too long
(app.ini MAX_GIT_DIFF_LINE_CHARACTERS)
![image](https://user-images.githubusercontent.com/2212615/142729138-61fdd445-35ad-4726-a652-c44fb93ee3b1.png).

It would be nice if these could be explicitly loaded on-demand anyway. Like is now supported for "Show More" if the diff contains too many files.

### Screenshots

GitHub supports this:
![image](https://user-images.githubusercontent.com/2212615/142729241-d8abbce3-41a4-49b4-a8dc-4a7a2c85b5f6.png)

**Comment by zeripath** [comment]
I was already working on this... 

This may not be the correct thing as we should probably really only produce a diff of a certain size.

**Comment by zeripath** [comment]
#17739 fixes the issue with files that have too many lines - by allowing you to specifically suffer the delayed load times yourself. 

Lines which are too long are a more difficult issue as they could crash the browser or even OOM gitea itself.

**Comment by silverwind** [comment]
Browsers should have no issues with long wrapped lines in general.

I think we could combine the two limits (line length and line count) to just a byte count, which I think is a more neutral measure of size.

**Comment by zeripath** [comment]
> Browsers should have no issues with long wrapped lines in general.

Its not the length of the lines its the number of elements in that line.

> I think we could combine the two limits (line length and line count, which are just one-dimensional limits) to just a byte count, which is a more neutral measure of size. It should apply to both diff and file view.

It's not as simple as that. We tokenize and diff whole lines. That's why the line length matters. 

Now for very long lines we can abandon syntax highlighting these lines which will drop the tokenizing problem. Intra line diffing could still be done but it's still different so these lines would need some kind of marking.

**Comment by silverwind** [comment]
> Now for very long lines we can abandon syntax highlighting these lines which will drop the tokenizing problem

IIRC, this is what GitHub does. On file with like 20k+ lines, syntax highlighting is no longer applied for performance reasons.
