### ISSUE TITLE
SSH does not work on kubernetes cluster

### ISSUE THREAD

**Issue by DavidvtWout** [go-gitea/gitea#17730]
### Gitea Version

1.15.6

### Operating System

k3s cluster

### How are you running Gitea?

Docker container in k3s cluster

### Database

SQLite

### Can you reproduce the bug on the Gitea demo site?

No

### Description

/etc/ssh/sshd_config is incorrectly generated from the template. 
Instead of the expected line `Port 22` it contains `Port tcp://10.43.225.190:22`

The ssh server can't parse this line according to the log and doesn't start;
`/etc/ssh/sshd_config line 1: Badly formatted port number.`

**Comment by techknowlogick** [comment]
It is recommended that you use the helm chart for kubernetes, and if you are already using it and are facing a bug with it please report this bug directly to that repo.
