### ISSUE TITLE
Feature request: download git log in CSV to local disc from UI

### ISSUE THREAD

**Issue by osevoso** [go-gitea/gitea#1773]
Hello! 

Now, I'm collect log commits info with shell script by explore disk's folders, оne by one, while Gitea already knows about organisation and their repos... I think, It could provide a little bit UI option for selecting repos, authors, period and separator for the report.  

Is the feature (subj) possible to do this or is there a plan?
I mean it would be very useful.

**Comment by appIeboy** [comment]
<p align=right><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup>#1798</sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></p>

**Comment by appIeboy** [comment]
<p align=right><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup>#1798 @lunny @tboerger @sapk @cez81 @geek1011 @lafriks @ethantkoenig @andreynering @DblK </sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></p>
