### ISSUE TITLE
Cannot add code comment on file loaded with "Show More"

### ISSUE THREAD

**Issue by jpraet** [go-gitea/gitea#17736]
### Gitea Version

1.16.0+dev-564-gf380bc8a5

### Git Version

2.34.0

### Operating System

Windows

### How are you running Gitea?

Built myself

### Can you reproduce the bug on the Gitea demo site?

No

### Description

Adding code comments to files loaded with "Show More" does not seem to be working.
Clicking the "+"  button does nothing. There are no errors in the browser console or gitea logs.

Cannot reproduce on try.gitea.io yet, because "Show More" doesn't work there (#17731).

### Screenshots

![image](https://user-images.githubusercontent.com/2212615/142723321-1896da90-54e8-4df9-b807-4c77aea990a4.png)

**Comment by silverwind** [comment]
Sounds like it needs a delegate event listener on a  common parent node.

**Comment by zeripath** [comment]
This was working previously - I suspect this is regression from the changes to the javascript.
