### ISSUE TITLE
Load markdown from logical link if inside repo

### ISSUE THREAD

**Issue by gsantner** [go-gitea/gitea#1774]
- Gitea version:1.1.0+dev
- Git version: 2.13.0
- Operating system: Debian
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
In an example repo I added the docs to e.g. `docs/index.md` and made an logical link to it:

    cd repo
    ln -s docs/index.md README.md

The markdown renderer now just shows the path of the logical link, instead of displaying it's contents as seen in screenshots. It should display the contents instead. It is important to check if the path is inside the repo (otherwise it would be a security risk).

## Screenshots
![unbenannt](https://cloud.githubusercontent.com/assets/6735650/26310260/7d9d1b7e-3f00-11e7-908c-21ed42674a22.png)

**Comment by sondr3** [comment]
But why? This is pretty much something that no other code hosting services does nor is it something that I think makes sense, the README is different from the documentation, it's an introduction to your project/repository.

**Comment by gsantner** [comment]
>  This is pretty much something that no other code hosting services does

Is having features that others don't have bad? Don't think so

> nor is it something that I think makes sense, the README is different from the documentation, it's an introduction to your project/repository.

README was just an example. This is about the possibilty of rendering any markdown that is symlinked in the repo.

**Comment by appIeboy** [comment]
<p align=right><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup>#1798 @lunny @tboerger @sapk @cez81 @geek1011 @lafriks @ethantkoenig @andreynering @DblK </sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></p>
