### ISSUE TITLE
Set default merge strategy for pull requests

### ISSUE THREAD

**Issue by MahdiGhiasi** [go-gitea/gitea#17741]
### Feature Description

Currently Gitea shows a green "Merge" button, and one can change the merge strategy by clicking the arrow next to it.

It would be nice to be able to change the default, in our case making "Squash and Merge" the default merge option, to avoid mistakenly pressing the default merge button (we usually squash, unless there's a reason not to).

**Comment by jpraet** [comment]
This is already configurable in the repository settings:

![image](https://user-images.githubusercontent.com/2212615/142775768-97a8368f-531e-4b71-9ef6-39c56147f9f9.png)

**Comment by MahdiGhiasi** [comment]
Thanks!

**Comment by suntsu42** [comment]
Is it possible to configure this as default for all new repositories?

**Comment by Gusted** [comment]
> Is it possible to configure this as default for all new repositories?

There currently don't seem to be a option to do this. You can open up a issue about it to request it as a feature.
