### ISSUE TITLE
Users and Organizations gone

### ISSUE THREAD

**Issue by MrCoala** [go-gitea/gitea#17748]
Hello,

all my users seem to be gone but they can still login. Same applies to organizations. I created two new admin users via the command line and these are the only two users that show up in the admin area:

![image](https://user-images.githubusercontent.com/18616998/142778371-eb5f9f9c-89ab-49b0-b1f2-5b9450fafbe6.png)

The users that dont show up any longer are still able to login though. Also if i login with such a broken user i am still able to see the organizations. The both new users cant see the old users nor do they show up in the admin interface (same applies to organizations)

I used the doctor to recreate the user table and made him perform all checks but the problem still persists.

Any idea on how i could solve that?

**Comment by techknowlogick** [comment]
There is a form that requests specific information that you have bypassed. We request this information because it helps us help you otherwise we would be completely guessing. Please provide this information.

**Comment by MrCoala** [comment]
Sorry,

here is the requested information:

gitea version:
1.15.6

databse: sqlite

running as docker (latest) and i keep automatically update the container once a week. 

The difference between the users within the database for the users that show up / i created with the command line tool:

not defined fields: full_name, keep_email_private, login_type, login_name, type, location, all num_* fields except num_following, use_custom_avatar, allow_* fields

**Comment by wxiaoguang** [comment]
The number comes from `SELECT COUNT(*) FROM user WHERE type=0`

Did you do some operation to you SQLite database? Restored?

**Comment by wxiaoguang** [comment]
stale
