### ISSUE TITLE
Chrome - U2F API invalid after 02.2022, use Web Authentication AP

### ISSUE THREAD

**Issue by uli-heller** [go-gitea/gitea#17754]
### Gitea Version

1.15.6

### Operating System

Ubuntu-20.04

### Browser Version

Chrome-96

### Can you reproduce the bug on the Gitea demo site?

No

### Description

I'm using a FIDO device to authenticate against gitea. Probably since upgrading to chrome 96, a warning like this shows up:

![image1](https://user-images.githubusercontent.com/1677414/142838274-6adafda6-9c46-4111-a4a3-1516140482b6.jpeg)

It is German and it says that the U2F API will not be available after February 2022.
Here is a similar tochet for another project: https://github.com/authelia/authelia/issues/2615

There it says:

> We're working on adding the Web Authentication API.
>
> Chrome is the only browser deprecating support at the moment. It was deprecated since version 95, will be disabled by default in February 2022 (version 98), and finally removed in March 2022 (version 100).

So maybe we need something similar for gitea?

### Screenshots

![image1](https://user-images.githubusercontent.com/1677414/142838467-6f01b755-57a6-4866-87ff-7bdab6ab80cb.jpeg)

**Comment by wxiaoguang** [comment]
Oh, maybe this problem can be considered together with

* https://github.com/go-gitea/gitea/issues/17712

**Comment by silverwind** [comment]
Related: https://github.com/go-gitea/gitea/issues/6892.

**Comment by lunny** [comment]
Let's continue in #6892
