### ISSUE TITLE
Review comment cannot be edited

### ISSUE THREAD

**Issue by jpraet** [go-gitea/gitea#17768]
### Gitea Version

1.16.0+dev-581-gbaed01f24

### How are you running Gitea?

try.gitea.io

### Can you reproduce the bug on the Gitea demo site?

Yes

### Description

It does not currently seem possible to edit the main comment you can add when submitting a PR review.
Such a comment also does not have the labels (like Poster / Owner), reactions and other actions.

https://try.gitea.io/jpraet-org/test-repo/pulls/2

### Screenshots

ok (a regular comment on a PR):
![image](https://user-images.githubusercontent.com/2212615/142920601-62365d20-2ed2-43ec-82d8-8984a6957835.png)

not ok (a comment from submitted review cannot be edited):
![image](https://user-images.githubusercontent.com/2212615/142920719-443d8291-b05d-4699-9a2c-54949a33ae20.png)

not ok (a comment from submitted review cannot be edited, whereas the individual code comment can be edited):
![image](https://user-images.githubusercontent.com/2212615/142920835-71050ce1-23fc-4d19-87e7-a0f86ce16218.png)

**Comment by wxiaoguang** [comment]
Is it a regression or an existing problem?

**Comment by jpraet** [comment]
Looks like an existing problem / oversight. 1.15.6 also doesn't support it.

**Comment by wxiaoguang** [comment]
Fixed in #18323
