### ISSUE TITLE
Feature Request: offer .tar.zst repo downloads

### ISSUE THREAD

**Issue by proailurus** [go-gitea/gitea#17766]
### Feature Description

Repo archives for downloading could be created much quicker using Zstandard instead of gzip, especially when multithreaded.

**Comment by zeripath** [comment]
The archives are created using `git archive`. I have git version 2.34.0 and if I run `git archive -l` to list the possible formats I get:

```
tar
tgz
tar.gz
zip
```

Thus it does not appear that Zstd is supported. 

I think this means that we would need to completely reimplement archive ourselves if we wanted to do this.

**Comment by clavinet** [comment]
It seems that additional compression programs can be added in the git repo config:

https://git-scm.com/docs/git-archive#_configuration
and example config command here:
https://git-scm.com/docs/git-archive#Documentation/git-archive.txt-codegitconfigtartarxzcommandxz-ccode

https://public-inbox.org/git/38ba34f9-47e5-8059-7c16-6cf159c849ad@gmail.com/

**Comment by zeripath** [comment]
That means that we'd then have to make the options configurable.

**Comment by lunny** [comment]
I think we have to reject the proposal.
