### ISSUE TITLE
Code comment history not shown on lazily loaded diffs

### ISSUE THREAD

**Issue by jpraet** [go-gitea/gitea#17767]
### Gitea Version

1.16.0+dev-581-gbaed01f24

### How are you running Gitea?

try.gitea.io

### Can you reproduce the bug on the Gitea demo site?

Yes

### Description

The comment edit history dropdowns are only initialized once when the page loads.
If additional diffs are loaded afterwards (via "Show More" or "Load Diff"), their code comments don't have the edit history. 

Example:
* https://try.gitea.io/jpraet-org/test-repo/pulls/1/files -> "Show More" -> you'll see the edited comment on file 99 has the edit history dropdown, while the edited comment on file 105 does not
* https://try.gitea.io/jpraet-org/test-repo/pulls/2/files -> "Load Diff" -> the edited comment does not have the dropdown

### Screenshots

ok:
![image](https://user-images.githubusercontent.com/2212615/142918989-f5d2fd6c-e909-4c66-8b2b-5630e81ee581.png)

not ok:
![image](https://user-images.githubusercontent.com/2212615/142919034-c31809cb-f373-4693-b0fc-97f5a819ebc6.png)

**Comment by Gusted** [comment]
@silverwind What if we add a call to `initRepoIssueContentHistory` on these lines:
https://github.com/go-gitea/gitea/blob/3d996c85a5a56a0c680c80653813ba361c21cc4a/web_src/js/features/repo-diff.js#L101-L103

**Comment by zeripath** [comment]
@gusted I think that would work.
