### ISSUE TITLE
Release retention periods / temporary releases

### ISSUE THREAD

**Issue by 0x1a8510f2** [go-gitea/gitea#17770]
### Feature Description

I use Drone CI with Gitea and would like to store build artefacts from CI jobs as Gitea releases. The problem is that builds happen on every commit and that would end up using a lot of storage. To avoid this, I was looking for a way to configure retention periods for releases such that they would be automatically cleaned up after some time. Unfortunately, this does not seem to be an option currently and hence my feature request.

Implementation-wise, either a repository-wide option or an additional parameter when creating a release would work well in my opinion, with the latter being a bit more flexible.

**Comment by fnetX** [comment]
Please also see #16585

**Comment by jolheiser** [comment]
As per above comment, closing as duplicate. 🙂
Please continue discussion in #16585 as needed.
