### ISSUE TITLE
Organization avatar is not displayed in headers

### ISSUE THREAD

**Issue by proton-ab** [go-gitea/gitea#17778]
### Gitea Version

1.16.0+dev-572-g7743f13be

### Browser Version

Any

### Can you reproduce the bug on the Gitea demo site?

Yes

### Description

Organization custom avatars are no longer displayed on header. Can be reproduced on try.gitea.io when browsing any organization with avatar set. The avatar is still displayed in few places, most notably on explore page.

The issue occurred between 1.16.0+dev-496-g47448083a and 1.16.0+dev-572-g7743f13be

### Screenshots

![firefox_2021-11-23_12-30-51](https://user-images.githubusercontent.com/25139420/143017045-1ebd7b15-ab08-42c9-adcd-e83881885c38.png)

---

![firefox_2021-11-23_12-30-58](https://user-images.githubusercontent.com/25139420/143017044-715bba76-a5b9-4ee5-a48a-6491d50c53c4.png)

![firefox_2021-11-23_12-31-04](https://user-images.githubusercontent.com/25139420/143017041-b00d1081-2adf-4e8f-967c-dcc6731d9c5e.png)

---

![firefox_2021-11-23_12-31-11](https://user-images.githubusercontent.com/25139420/143017035-6e89cf00-7d2e-4234-8065-3595a1451344.png)

**Comment by qwerty287** [comment]
I have this issue too...
