### ISSUE TITLE
Wrong user on Issue title change for Matrix webhook

### ISSUE THREAD

**Issue by f0086** [go-gitea/gitea#17788]
### Gitea Version

1.15.6

### Git Version

2.27.0

### Operating System

CentOS 8

### How are you running Gitea?

Official Docker image

### Database

PostgreSQL

### Can you reproduce the bug on the Gitea demo site?

No

### Description

We use the Matrix Webhook to push notifications on Issue changes.
When changing the title of an Issue, the wrong user will be shown in the notification (the person who created the issue [mezzo on the screenshot]). In the UI, the correct user (the user who changed the title [f on the screenshot]) will be shown.

### Screenshots

![image](https://user-images.githubusercontent.com/121972/143107817-e271bdd5-06fb-4839-a5d3-4577dc01b253.png)
![image](https://user-images.githubusercontent.com/121972/143107991-49a9f222-de40-48aa-832a-1fe2b1a88a2f.png)

**Comment by mscherer** [comment]
Seems the problem is here: https://github.com/go-gitea/gitea/blob/main/modules/notification/webhook/webhook.go#L217
