### ISSUE TITLE
Emoji heavy_check_mark: shown as pink instead of green

### ISSUE THREAD

**Issue by suchAdemon** [go-gitea/gitea#17795]
### Gitea Version

1.15.6

### Operating System

Debian 10

### Browser Version

Chrome 96.0.4664.45

### Can you reproduce the bug on the Gitea demo site?

Yes

### Description

I have seen that if I add `:heavy_check_mark:` to comments or something like that, it gets displayed in a different way based on the theme got selected, which leads to a miss understanding of it.

As you can see in the attached screenshots, it is green if the gitea theme is selected, but if you select the arc-green theme, it gets pink which leeds to a miss understanding of if

tested there as well: https://try.gitea.io/suchAdemon/test_sad

### Screenshots

![image](https://user-images.githubusercontent.com/6714555/143220642-3ecfb4a3-a535-496b-8a01-5e8488ca1ea0.png)
![image](https://user-images.githubusercontent.com/6714555/143220751-42866196-8dc7-4fbe-98dc-27f00f407cc3.png)

**Comment by silverwind** [comment]
Some emoji fonts like Apple's render this emoji in monochrome black, this is why we had it inverted using a CSS filter for better contrast. See https://emojipedia.org/check-mark/ for example renderings. I think it should be possible to change the inversion to preserve color, e.g. `filter: invert(100%) hue-rotate(180deg)` to fix this.
