### ISSUE TITLE
RSA public keys cannot authenticate against internal SSH if the client has a recent ssh version (which disables ssh-rsa algorithm)

### ISSUE THREAD

**Issue by zeripath** [go-gitea/gitea#17798]
### Gitea Version

1.15.x/1.16.x till the latest

### Operating System

- Any SSH client with ssh-rsa algorithm disabled (ex: OpenSSH >= 8.8)

### How are you running Gitea?

Builtin/Internal SSH (ex: docker-rootless or START_SSH_SERVER=true in app.ini)

### Can you reproduce the bug on the Gitea demo site?

Yes

### Description

The `ssh-rsa` key signing algorithm is disabled on recent ssh versions. Although #17281 means that Gitea will offer `rsa-sha2-256` and `rsa-sha2-512` for the host key verification - it does not fix the issue of advertising and handling the public key signing algorithm. 

This failure then results in ssh authentication failing.

## How to reproduce

Use a newer version of SSH where this is disabled and attempt to authenticate using an RSA key.

On older versions of SSH:

```
ssh -o PubkeyAcceptedKeyTypes=-ssh-rsa,+rsa-sha2-256 ...
```

Unfortunately OpenSSH have changed the name of this option across versions and in newer versions, including the affected version, this option is called: `PubkeyAcceptedAlgorithms`

So if the above fails with an error try:

```
ssh -o PubkeyAcceptedAlgorithms=-ssh-rsa ...
```

## Workaround

* On affected clients, add `-o PubkeyAcceptedAlgorithms=+ssh-rsa` to the ssh command line (In the unlikely event you have an older version which has deliberately disabled the ssh-rsa algorithm you will need to add 
`-o PubkeyAcceptedKeyTypes=+ssh-rsa`)
* Use other supported SSH key formats
* Use OpenSSH server instead of builtin SSH server (ex: use Docker instead of Docker-rootless)

## History of this issue

For speed I'm going to collect things here:

* #17175 reported that there was a key negotiation failure with newer versions of SSH and Gitea.
* Through investigation this was revealed to be a HostKey algorithm failure due to the key type being used to determine the signing algorithms available for the key. 
* Fortunately the HostSigners are exposed on the underlying ssh server so although there is a fundamental flaw in the way signers (their type is not reportable separate from the key) #17281 was able to work around this by wrapping those keys around something to pretend to be signers.
* This then fixes the hostkey issue - however, I was unaware of the next issue...
* @andypost then commented on https://github.com/go-gitea/gitea/issues/9691#issuecomment-955776326 (Which is unfortunately an unrelated feature request issue relating to HTTPS not SSH.)
* My comment here https://github.com/go-gitea/gitea/issues/9691#issuecomment-956753681 describes that the issue is actually relating to the next step of authentication - the pubkeyalgorithm 
* I then discovered that the problem is relating to the pubkey signing algorithms offered to the client https://github.com/go-gitea/gitea/issues/9691#issuecomment-962434683
* There is an upstream issue: https://github.com/golang/go/issues/49269 relating to supporting the required extension.
* And there is a PR here: https://github.com/golang/crypto/pull/197 that implements this but I'm not completely convinced its totally correct.
* In the meantime go have merged: https://github.com/golang/crypto/commit/b4de73f9ece8163b492578e101e4ef8923ac2c5c
* This does a similar bodge to the one I did in #17281, however, whereas #17281 leaves the possibility of disabling certain host key signing algorithms in the future, if we support ssh-rsa we have to support rsa-sha2-256 and rsa-sha2-512, and no way is provided to support only  rsa-sha2-256 and rsa-sha2-512. (The above commit does provide certificate support which is something that #17281 missed.)
* Now alpine linux are having to build gitea with a patch that adds the above workaround to fix issues with testing and #17786 proposes upstreaming that patch - but our testing version of OpenSSH is not affected by this problem as it is too old and this PR fails because it uses the new option which our version does not (!).

## What is actually needed

The fundamental issue is not resolvable within Gitea without forking and otherwise reimplementing the ssh server. We will need to address this problem upstream.

There are two major structural issues:

* Signers need to be separately configurable and advertisable apart from the key types that they sign. The commit mentioned above may have degraded the ability of users of the upstream ssh package to disable the `ssh-rsa` signing algorithm in future and this needs to be addressed.
* The Handshake needs to support extension negotiation https://datatracker.ietf.org/doc/html/rfc8308 and in particular the SSH_MSG_EXT_INFO extension described therein.

**Comment by suchAdemon** [comment]
Another workaround, very ugly, is to modify ssh key files which are used by gitea it self.
By replacing the file content with e.g. ed25519 keys, just make sure that the file name stay the same (gitea.rsa.pub and gitea.rsa), gitea will accept the files and offer the new keys to the clients (but all clients have then to accept the new ones which can be a pain, depending on the amount of users)
Still looking forward to the patch

**Comment by zeripath** [comment]
@suchAdemon I think you're talking about the HostKey signing algorithm - not the client public key. Host Keys have been fixed by #17281 and its backport #17376 which is in 1.15.5. 

This issue is specifically talking about the client's public key and the signing algorithm chosen during its authentication.

**Comment by 0xc0000007b** [comment]
Belive I just hit this issue on gitea.com just now. Ended up switching to ed25519 from RSA and the issue was resolved.

With RSA what I saw trying to clone via SSH:

```
git@gitea.com: Permission denied (publickey).
fatal: Could not read from remote repository.
```

Debugged with:

```
ssh -vT git@gitea.com
```

Everything looked fine. But then I remembered ed25519 was an option looking at the SSH key input placeholder text in the Gitea key input field, switched as I prefer it anyway, and was able to use SSH again.

**Comment by trading-peter** [comment]
A easy and transparent workaround:

Set "HostkeyAlgorithms" and "PubkeyAcceptedKeyTypes" in ~/.config/ssh

```
Host <Your Git Name>
  HostkeyAlgorithms +ssh-rsa
  PubkeyAcceptedKeyTypes +ssh-rsa
```

**Comment by wxiaoguang** [comment]
FYI, some recent progress from go/x/crypto: https://cs.opensource.google/go/x/crypto/+/3147a52a75dda54ac3a611ef8978640d85188a2a

<details>

![image](https://user-images.githubusercontent.com/2114189/166093984-b39ec3ed-12df-4d2a-86ce-bdb1b1e3f24c.png)

</details>

**Comment by bopoh13** [comment]
And the reverse situation. If the following message is displayed [testing](https://github.com/go-gitea/gitea/issues/17798#issuecomment-1003576352) operation of the key:
```
Unable to negotiate with 192.168.254.254 port 22: no matching host key type found.
Their offer: rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ssh-ed25519
```

Remove lines 3 and 4 from the **`config`** file (if the text from the example was used):
```nix
Host *
  AddKeysToAgent yes
  IdentityFile ~/.ssh/id_rsa
  HostKeyAlgorithms ssh-rsa
  ForwardAgent yes
```

**Comment by ChrisWitt** [comment]
God overview and transparent problem handling. This encourages trust in your project. I am a happy user :) 
Of course also because of the great service gitea provides!

**Comment by dreirund** [comment]
> A easy and transparent workaround:
> 
> Set "HostkeyAlgorithms" and "PubkeyAcceptedKeyTypes" in ~/.ssh/config

That should not be considered valid, since the algorithm behind it is known as weak.

Please support up-to-date crypto algorithms. Forcing users to use weak algorithms is not acceptable.

Reason to not re-install gitea after a just-done server upgrade.

**Comment by MartinX3** [comment]
> A easy and transparent workaround:
> 
> Set "HostkeyAlgorithms" and "PubkeyAcceptedKeyTypes" in ~/.ssh/config
> 
> ```
> Host <Your Git Name>
>   HostkeyAlgorithms +ssh-rsa
>   PubkeyAcceptedKeyTypes +ssh-rsa
> ```

That's like advising schools to wear weapons against people using weapons instead of forbid weapons by law.

SSH-RSA IS OFFICIALLY BROKEN SINCE 2020 AND DISABLED BY DEFAULT SINCE 2021!
https://lists.mindrot.org/pipermail/openssh-unix-announce/2020-February/000138.html

**Comment by PKizzle** [comment]
An alternative workaround that might be more secure (I only quickly checked the source code) is to temporarily replace `golang.org/x/crypto` with a patched version for RFC8308

```
replace golang.org/x/crypto => github.com/rmohr/crypto v0.0.0-20211203105847-e4ed9664ac54
```

Additionally you will need to adjust `SSH_SERVER_KEY_EXCHANGES` to replace `curve25519-sha256` with `curve25519-sha256@libssh.org`
