### ISSUE TITLE
Draft a vendor update policy

### ISSUE THREAD

**Issue by strk** [go-gitea/gitea#178]
We need to define a policy for updating the vendor/ directory.
I propose it's written in a vendor/README.md file.
My proposal for a policy is:
 - vendor/ is only updated when needed to fix a bug or to implement a feature.
 - when bugfix or feature *also* require changes to the gitea/ codebase, the updating PR should include both vendor/ and local file changes
 - when bugfix only requires upgrading of the vendor, the PR should only include the vendor update
 - reviewer should check to make sure the updates under vendor/ really match an upstream commit before approving the changes

**Comment by metalmatze** [comment]
We could also update minor versions of our dependencies.
I think it's the responsibility of the merger to make sure that updated dependencies don't break anything. Additionally PR creator can help with that by providing more info about why the dependency was updated.

**Comment by strk** [comment]
I agree about the possibility to update minor versions, but it still needs a justification to update (so yes, would need to be written in the PR).

And yes, merger should also check the update doesn't break anything, but the important point to me is that the matching with upstream version is checked, to avoid having local-only changes (as it happened when lint errors were fixed). Do you agree on that part ? (ie: no local-only modifications)

**Comment by stevenroose** [comment]
Doesnt a `VENDORING.md` file in the main folder make more sense, since people tend to ignore the `vendor/` directory? ([cfr docker](https://github.com/docker/docker/blob/master/VENDORING.md))

**Comment by strk** [comment]
Good idea, +1 for VENDORING.md

**Comment by metalmatze** [comment]
We already have a lot of files in the root. Let's just add a section to the `README.md` that tells which vendoring tool gitea uses. I don't see the need for a extra file.

**Comment by strk** [comment]
Le'ts move this to #187, where I added a vendoring section to the CONTRIBUTING.md file (which is linked from the PR template)
