### ISSUE TITLE
Unable to restore a database

### ISSUE THREAD

**Issue by rpelissi** [go-gitea/gitea#17805]
Hi,
I am using latest 1.15.6 with mariadb database and I wanted to move from an lxc container to a vm. The OS is centos 7.9.
I have done a database backup as indicated in the documentation but when I want to restore on the new database, I got this:

```
[root@pdrgitea01 restore]# mysql --default-character-set=utf8mb4 -uroot -pxxxx gitea < gitea-db.sql
ERROR 1048 (23000) at line 4: Column 'keep_activity_private' cannot be null
```

Any help will be very appreciated.
Thanks!

**Comment by wxiaoguang** [comment]
I am not sure whether a bug of the Gitea dump command.

I think it can be bypassed by:

1. alter keep_activity_private to allow null
2. complete the database restore
3. update set keep_activity_private=false where keep_activity_private is null, and alter keep_activity_private to non-null

**Comment by rpelissi** [comment]
Hello,
So I have modify my dump file forthe user table creation like this:
`CREATE TABLE IF NOT EXISTS `user` (`id` BIGINT(20) PRIMARY KEY AUTO_INCREMENT NOT NULL , `lower_name` VARCHAR(255) NOT NULL , `name` VARCHAR(255) NOT NULL , `full_name` VARCHAR(255) NULL , `email` VARCHAR(255) NOT NULL , `keep_email_private` TINYINT(1) NULL , `email_notifications_preference` VARCHAR(20) DEFAULT 'enabled' NOT NULL , `passwd` VARCHAR(255) NOT NULL , `passwd_hash_algo` VARCHAR(255) DEFAULT 'argon2' NOT NULL , `must_change_password` TINYINT(1) DEFAULT false NOT NULL , `login_type` INT NULL , `login_source` BIGINT(20) DEFAULT 0 NOT NULL , `login_name` VARCHAR(255) NULL , `type` INT NULL , `location` VARCHAR(255) NULL , `website` VARCHAR(255) NULL , `rands` VARCHAR(10) NULL , `salt` VARCHAR(10) NULL , `language` VARCHAR(5) NULL , `description` VARCHAR(255) NULL , `created_unix` BIGINT(20) NULL , `updated_unix` BIGINT(20) NULL , `last_login_unix` BIGINT(20) NULL , `last_repo_visibility` TINYINT(1) NULL , `max_repo_creation` INT DEFAULT -1 NOT NULL , `is_active` TINYINT(1) NULL , `is_admin` TINYINT(1) NULL , `is_restricted` TINYINT(1) DEFAULT false NOT NULL , `allow_git_hook` TINYINT(1) NULL , `allow_import_local` TINYINT(1) NULL , `allow_create_organization` TINYINT(1) DEFAULT true NULL , `prohibit_login` TINYINT(1) DEFAULT false NOT NULL , `avatar` VARCHAR(2048) NOT NULL , `avatar_email` VARCHAR(255) NOT NULL , `use_custom_avatar` TINYINT(1) NULL , `num_followers` INT NULL , `num_following` INT DEFAULT 0 NOT NULL , `num_stars` INT NULL , `num_repos` INT NULL , `num_teams` INT NULL , `num_members` INT NULL , `visibility` INT DEFAULT 0 NOT NULL , `repo_admin_change_team_access` TINYINT(1) DEFAULT false NOT NULL , `diff_view_style` VARCHAR(255) DEFAULT '' NOT NULL , `theme` VARCHAR(255) DEFAULT '' NOT NULL , `keep_activity_private` TINYINT(1) DEFAULT false NULL ) DEFAULT CHARSET utf8mb4 ROW_FORMAT=DYNAMIC;`

And changeg the value for keep_activity_private to NULL.
Then, I was able to restore my dump!

Just after, change back the setting:

```
MariaDB [(none)]> use gitea;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
MariaDB [gitea]> SHOW COLUMNS FROM user;
+--------------------------------+---------------+------+-----+---------+----------------+
| Field                          | Type          | Null | Key | Default | Extra          |
+--------------------------------+---------------+------+-----+---------+----------------+
| id                             | bigint(20)    | NO   | PRI | NULL    | auto_increment |
| lower_name                     | varchar(255)  | NO   | UNI | NULL    |                |
| name                           | varchar(255)  | NO   | UNI | NULL    |                |
| full_name                      | varchar(255)  | YES  |     | NULL    |                |
| email                          | varchar(255)  | NO   |     | NULL    |                |
| keep_email_private             | tinyint(1)    | YES  |     | NULL    |                |
| email_notifications_preference | varchar(20)   | NO   |     | enabled |                |
| passwd                         | varchar(255)  | NO   |     | NULL    |                |
| passwd_hash_algo               | varchar(255)  | NO   |     | argon2  |                |
| must_change_password           | tinyint(1)    | NO   |     | 0       |                |
| login_type                     | int(11)       | YES  |     | NULL    |                |
| login_source                   | bigint(20)    | NO   |     | 0       |                |
| login_name                     | varchar(255)  | YES  |     | NULL    |                |
| type                           | int(11)       | YES  |     | NULL    |                |
| location                       | varchar(255)  | YES  |     | NULL    |                |
| website                        | varchar(255)  | YES  |     | NULL    |                |
| rands                          | varchar(10)   | YES  |     | NULL    |                |
| salt                           | varchar(10)   | YES  |     | NULL    |                |
| language                       | varchar(5)    | YES  |     | NULL    |                |
| description                    | varchar(255)  | YES  |     | NULL    |                |
| created_unix                   | bigint(20)    | YES  | MUL | NULL    |                |
| updated_unix                   | bigint(20)    | YES  | MUL | NULL    |                |
| last_login_unix                | bigint(20)    | YES  | MUL | NULL    |                |
| last_repo_visibility           | tinyint(1)    | YES  |     | NULL    |                |
| max_repo_creation              | int(11)       | NO   |     | -1      |                |
| is_active                      | tinyint(1)    | YES  | MUL | NULL    |                |
| is_admin                       | tinyint(1)    | YES  |     | NULL    |                |
| is_restricted                  | tinyint(1)    | NO   |     | 0       |                |
| allow_git_hook                 | tinyint(1)    | YES  |     | NULL    |                |
| allow_import_local             | tinyint(1)    | YES  |     | NULL    |                |
| allow_create_organization      | tinyint(1)    | YES  |     | 1       |                |
| prohibit_login                 | tinyint(1)    | NO   |     | 0       |                |
| avatar                         | varchar(2048) | NO   |     | NULL    |                |
| avatar_email                   | varchar(255)  | NO   |     | NULL    |                |
| use_custom_avatar              | tinyint(1)    | YES  |     | NULL    |                |
| num_followers                  | int(11)       | YES  |     | NULL    |                |
| num_following                  | int(11)       | NO   |     | 0       |                |
| num_stars                      | int(11)       | YES  |     | NULL    |                |
| num_repos                      | int(11)       | YES  |     | NULL    |                |
| num_teams                      | int(11)       | YES  |     | NULL    |                |
| num_members                    | int(11)       | YES  |     | NULL    |                |
| visibility                     | int(11)       | NO   |     | 0       |                |
| repo_admin_change_team_access  | tinyint(1)    | NO   |     | 0       |                |
| diff_view_style                | varchar(255)  | NO   |     |         |                |
| theme                          | varchar(255)  | NO   |     |         |                |
| keep_activity_private          | tinyint(1)    | YES  |     | 0       |                |
+--------------------------------+---------------+------+-----+---------+----------------+


MariaDB [gitea]> update user set keep_activity_private=0 WHERE keep_activity_private IS NULL;
Query OK, 4 rows affected (0.004 sec)
Rows matched: 4  Changed: 4  Warnings: 0

MariaDB [gitea]> alter table user modify keep_activity_private tinyint not null;
Query OK, 0 rows affected (0.025 sec)
Records: 0  Duplicates: 0  Warnings: 0

| keep_activity_private          | tinyint(4)    | NO   |     | NULL    |                |
```

Working fine :)
Let me know if all looks good for you so I can close the ticket.
Thanks!

**Comment by wxiaoguang** [comment]
I think you have done right.

But I am not sure how the bug was triggered. Maybe other developers can also have a look at this.

**Comment by wxiaoguang** [comment]
Another question, where does your backup come from? Is your backup dumped from the same Gitea(1.15.6) database?

**Comment by wxiaoguang** [comment]
stale

**Comment by mikeperalta1** [comment]
Would just like to chime in that I had the same issue trying to restore from an automated backup (dump). @rpelissi 's solution worked perfectly for me as well.

Perhaps this should continue to be investigated because I'm on 1.16.8. I can provide my dump command or other config is that is helpful (?).

**Comment by zeripath** [comment]
What version of gitea provided the dump? were you converting types of db? What db are you trying to import into? What is the error?

**Comment by mikeperalta1** [comment]
For me:
* Export from 1.16.8, import to 1.16.8 (simply moving servers)
* MariaDB: Ver 15.1 Distrib 10.3.32-MariaDB, for Linux (x86_64) using readline 5.1
* Same DB type and version on both servers
* Error and solution: Same as OP
