### ISSUE TITLE
Use xorm LRU cache

### ISSUE THREAD

**Issue by sapk** [go-gitea/gitea#1781]
Before making a PR what do you think of activating [xorm cache](http://gobook.io/read/github.com/go-xorm/manual-en-US/chapter-11/#) ?
I haven't tested (yet) and don't really know if we could have an improvement with it.

This issue is to have your feedback on that idea and if you have already used this functionality.

**Comment by lunny** [comment]
Maybe make it as an option

**Comment by appIeboy** [comment]
<p align=right><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup>#1798 @lunny @tboerger @sapk @cez81 @geek1011 @lafriks @ethantkoenig @andreynering @DblK </sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></p>

**Comment by bkcsoft** [comment]
Just make sure that the cache is cleaned in the right places 😉

**Comment by lunny** [comment]
I think this could be closed because we have ourselves' cache system.
