### ISSUE TITLE
key_exchange_identification

### ISSUE THREAD

**Issue by FlyingOnion** [go-gitea/gitea#17812]
### Gitea Version

1.15.4

### How are you running Gitea?

Helm chart

### Can you reproduce the bug on the Gitea demo site?

No

### Description

The log keeps appearing
```
kex_exchange_identification: client sent invalid protocol identifier "GET /metrics HTTP/1.1"^M
banner exchange: Connection from {ip-address} port {port}: invalid format
```
Any ideas?

**Comment by wxiaoguang** [comment]
Not a bug. You are trying to access "https://xxxx" but you are sending "http://xxxx" requests.

**Comment by wxiaoguang** [comment]
Maybe the health/metric metric of helm-chart should be improved. You may open an issue in the helm-chart repository. https://gitea.com/gitea/helm-chart/
