### ISSUE TITLE
Proposal: allow users on try.gitea.io to create organizations

### ISSUE THREAD

**Issue by wxiaoguang** [go-gitea/gitea#17814]
Now the users on try.gitea.io can not create organizations.

Many organization related bugs can not be test on try.gitea.io, eg:

* https://github.com/go-gitea/gitea/issues/17279
* https://github.com/go-gitea/gitea/pull/17807

**Comment by silverwind** [comment]
Might not affect all users, I can for example create orgs.

**Comment by techknowlogick** [comment]
It was disabled by default due to spammers using it rather than having to pass a captcha and email verification for each spam account they wished to create.

I can enable for your user if you wish.

**Comment by wxiaoguang** [comment]
Oh, if it is done by purpose, that's fine.
