### ISSUE TITLE
Session panic

### ISSUE THREAD

**Issue by winxxp** [go-gitea/gitea#17823]
### Gitea Version

1.15.6

### Git Version

git version 2.33.0.windows.2

### Operating System

Windows 11

### How are you running Gitea?

Download from github.com release page.

- run command-line： "d:\servers\gitea\gitea.exe" web --config "d:\servers\gitea\custom\conf\app.ini"

### Database

SQLite

### Can you reproduce the bug on the Gitea demo site?

No

### Description

```go
2021/11/25 17:26:52 ...common/middleware.go:64:1() [E] PANIC: session(start): EOF
	/source/vendor/gitea.com/go-chi/session/session.go:246 (0x1a876be)
	/usr/local/go/src/net/http/server.go:2049 (0xd2574a)
	/source/modules/public/public.go:42 (0x1bf97b0)
	/usr/local/go/src/net/http/server.go:2049 (0xd2574a)
	/source/vendor/github.com/go-chi/chi/mux.go:70 (0x1c847ea)
	/source/vendor/github.com/go-chi/chi/mux.go:311 (0x1c8ac9b)
	/usr/local/go/src/net/http/server.go:2049 (0xd2574a)
	/source/vendor/github.com/go-chi/chi/mux.go:436 (0x1c86cea)
	/usr/local/go/src/net/http/server.go:2049 (0xd2574a)
	/source/routers/common/middleware.go:72 (0x261d664)
	/usr/local/go/src/net/http/server.go:2049 (0xd2574a)
	/source/routers/common/logger.go:23 (0x261c888)
	/usr/local/go/src/net/http/server.go:2049 (0xd2574a)
	/source/vendor/github.com/go-chi/chi/middleware/strip.go:30 (0x2619487)
	/usr/local/go/src/net/http/server.go:2049 (0xd2574a)
	/source/vendor/github.com/chi-middleware/proxy/middleware.go:37 (0x26149b3)
	/usr/local/go/src/net/http/server.go:2049 (0xd2574a)
	/source/routers/common/middleware.go:25 (0x261d1a7)
	/usr/local/go/src/net/http/server.go:2049 (0xd2574a)
	/source/vendor/github.com/go-chi/chi/mux.go:87 (0x1c84570)
	/source/modules/web/route.go:318 (0x25f423a)
	/source/vendor/github.com/gorilla/context/context.go:141 (0x178edfa)
	/usr/local/go/src/net/http/server.go:2049 (0xd2574a)
	/usr/local/go/src/net/http/server.go:2867 (0xd28d89)
	/usr/local/go/src/net/http/server.go:1932 (0xd2420c)
	/usr/local/go/src/runtime/asm_amd64.s:1371 (0x9c65c0)```

Now fix by rename session folder.

### Screenshots

Just visit '/'

**Comment by wxiaoguang** [comment]
`Now fix by rename session folder.`, it seems that this problem is caused by broken session files.

Maybe it should be fix on `go-chi/session` side: https://gitea.com/go-chi/session/

**Comment by zeripath** [comment]
It would be useful to know what the contents of the `[session]` section of your app.ini is.

As @wxiaoguang says it's likely that something is corrupted within your session files and simply deleting them would fix this, but the error that we're getting from chi's session provider isn't particularly helpful. 

It's quite odd though that the error is an EOF because I'm not entirely sure where that could be coming from.

**Comment by winxxp** [comment]
> It would be useful to know what the contents of the `[session]` section of your app.ini is.
> 
> As @wxiaoguang says it's likely that something is corrupted within your session files and simply deleting them would fix this, but the error that we're getting from chi's session provider isn't particularly helpful.
> 
> It's quite odd though that the error is an EOF because I'm not entirely sure where that could be coming from.


[session]
PROVIDER = file

**Comment by donnyv** [comment]
I got this after our office went through a power outage. You might want to test by killing the power on a machine when a session is active.

**Comment by zeripath** [comment]
I guess we should just add a recover, or some error catch when creating the session to catch for an EOF and just delete the file.

@donnyv do you have an up-to-date set of logs and stack trace? The provided stack-trace is considerably old now and very much does not match the current state of the framework

**Comment by wxiaoguang** [comment]
The problem is:

* Corrupted file -> 
* file.Read gets corrupted data: https://gitea.com/go-chi/session/src/branch/master/file.go#L166 
* then DecodeGob returns EOF
* then Manager.Start returns EOF: https://gitea.com/go-chi/session/src/branch/master/session.go#L403-L406
* then Sessioner Handler panics: https://gitea.com/go-chi/session/src/branch/master/session.go#L247

**Comment by lunny** [comment]
> The problem is:
> 
> * Corrupted file ->
> * file.Read gets corrupted data: https://gitea.com/go-chi/session/src/branch/master/file.go#L166
> * then DecodeGob returns EOF
> * then Manager.Start returns EOF: https://gitea.com/go-chi/session/src/branch/master/session.go#L403-L406
> * then Sessioner Handler panics: https://gitea.com/go-chi/session/src/branch/master/session.go#L247
> 
> IMO file.Read or Manager.Start or Sessioner Handler should ignore the error, corrupted session data should be treated as empty session data.

I agree we can have a warning here if files corrupted since they are sessions, users will have to login again and maybe not lose something(if he is not editing something).

**Comment by zeripath** [comment]
https://gitea.com/go-chi/session/pulls/5 is one option where we simply swallow the EOF error.

**Comment by donnyv** [comment]
My version is a little old, its 1.15.10.
[gitea.log.2022-12-19.001.gz](https://github.com/go-gitea/gitea/files/10259598/gitea.log.2022-12-19.001.gz)

**Comment by donnyv** [comment]
@zeripath yeah until this error happened, I didn't realize how behind I was on updates
