### ISSUE TITLE
SSH push error on relative unix socket address

### ISSUE THREAD

**Issue by mamins1376** [go-gitea/gitea#17833]
### Gitea Version

Gitea version 1.15.6 built with GNU Make 4.1, go1.16.9 : bindata, sqlite, sqlite_unlock_notify

### Git Version

git version 2.20.1

### Operating System

Debian Buster

### How are you running Gitea?

I downloaded the binray from releases page and activated the systemd service.

### Database

SQLite

### Can you reproduce the bug on the Gitea demo site?

No

### Description

Using a relative address for `HTTP_ADDR` when `PROTOCOL` is `unix` would result in push failure:
```
remote: Resolving deltas: 100% (100/100), done.
remote:
remote: Gitea: Internal Server Error
remote: Unable to contact gitea: Post "http://unix/api/internal/hook/pre-receive/user/repo": dial unix socket: connect: no such file or directory
remote: Gitea: Internal Server Error
```

**Comment by zeripath** [comment]
What is your LOCAL_ROOT_URL

**Comment by zeripath** [comment]
You need to set PROTOCOL=unix

**Comment by mamins1376** [comment]
The point is they should be resolved the same way in any context, web or hooks.

It looks like currently they are resolved relative to current working directory which is different than server worker when `gitea` is invoked to receive a push.

Personally I'd prefer resolution to be relative to executable binary, but the alternatives are config file and server working directory.
