### ISSUE TITLE
Design discussion / remove redundancy of new organization menu

### ISSUE THREAD

**Issue by fnetX** [go-gitea/gitea#17847]
> [...] the redundancy of the peoples / teams parts (top menu and side menu, both include a link) looks a bit off at first glance. The details of the side-menu are handy, and the top menu a nice navigation feature, but still ... it feels a little weird to me.

_Originally posted by @fnetX in https://github.com/go-gitea/gitea/issues/17802#issuecomment-978027598_

Are you interested in discussing this design once more? If not, feel free to close immediately, but I'd suggest having a second thought at it.

**Comment by lunny** [comment]
Yes, of course it's interesting. And I think we may want to consider it on the whole system. Github has a dashboard concept for User/Org, you can put a Readme markdown in there and some pin repositories. And Github also has another page named repositories for User/Org. But currently, our home page for Org is also repositories page.

**Comment by wxiaoguang** [comment]
No more discussion, so it could be closed 

> feel free to close immediately
