### ISSUE TITLE
Slow CI builds

### ISSUE THREAD

**Issue by ethantkoenig** [go-gitea/gitea#1785]
Our CI builds are very slow (can take up to an hour). #1783 will help, but that will only reduce the durations of some CI builds (and those builds will still take >20 minutes).

`make release` usually takes about 20 minutes to complete in Drone. Is it absolutely necessary for us to compile to every supported architecture in every build? What is running `make release` supposed to ensure/accomplish?

**Comment by lunny** [comment]
for Pull Request, `make release` is no need I think.

**Comment by ethantkoenig** [comment]
Only for tag builds?

**Comment by lunny** [comment]
@ethantkoenig Not only tags. Also master and other branches since we provides these downloads on https://dl.gitea.io

**Comment by lunny** [comment]
@tboerger @bkcsoft @appleboy

**Comment by DblK** [comment]
Is this linked to #1783? If yes, maybe we can close it.

**Comment by appleboy** [comment]
@DblK @lunny I will make new PR to fix @tboerger comments https://github.com/go-gitea/gitea/pull/1783#issuecomment-304476001

**Comment by ethantkoenig** [comment]
Would it be possible to cache compiled `vendor/` packages that are generated in `make release`, and reuse them across different builds? The contents of `vendor/` rarely change, so it seems like a waste to repeatedly recompile them (multiple times, once for each supported architecture) every build.

**Comment by lunny** [comment]
This has been resolved.
