### ISSUE TITLE
Markdown editor supports tldraw

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#17851]

**Comment by yardenshoham** [comment]
What's your vision here?

**Comment by lunny** [comment]
Looks like it's difficult to support draw a graph with markdown syntax with https://github.com/tldraw/tldraw

**Comment by yardenshoham** [comment]
Is there an example for markdown with tldraw?

**Comment by yardenshoham** [comment]
#12334 probably provides a limited alternative. I think we can close this

**Comment by a1012112796** [comment]
> #12334 probably provides a limited alternative. I think we can close this

/cc @lunny
