### ISSUE TITLE
500 internal server error when renaming an organisation as reserved name 

### ISSUE THREAD

**Issue by cobber** [go-gitea/gitea#17876]
### Gitea Version

1.15.3

### How are you running Gitea?

standalone binary installation gitea-1.15.3-linux-arm-6 image installed under a dedicated "gitea" user

### Database

SQLite

### Can you reproduce the bug on the Gitea demo site?

No

### Description

When I tried to rename one of my organisations to "admin" (for my git repo's with administrative scripts etc) I got a nondescript "500" error (without "internal server error" or any other information).

Being my own gitea admin, I was able to find the log entry:
2021/12/01 21:04:40 ...s/web/org/setting.go:72:SettingsPost() [E] ChangeUserName: name is reserved [name: admin]

It would be much more user friendly if at least this error message was displayed in the UI.

As far as I can tell this is being triggered via CreateOrgnization() when it gets an error from user_model.IsUsableUsername()

Also, the list of reserved names in models/user/user.go (reservedUsernames var) would be useful information to help the user understand what went wrong.

**Comment by a1012112796** [comment]
Has you try the new version (**v1.15.6**) ?

**Comment by cobber** [comment]
Yep, 1.15.6 shows the same error, but I see you have added a patch.
I'll check it again when 1.15.7 is released.
Thanks.

**Comment by cobber** [comment]
just checked: 1.15.7 no longer crashes, just shows 'illegal_username' in a red dialog box.
Could be prettier, but is definitely a big improvement :-)

**Comment by Gusted** [comment]
> just shows 'illegal_username' in a red dialog box.
> Could be prettier, but is definitely a big improvement :-)

#18342
