### ISSUE TITLE
Voting for new owners between 2022/1/1 ~ 2022/12/31

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#17872]
With the end of the year coming soon and as the description on our CONTRIBUTING, the Gitea community has an election every year for owners. Only maintainers are eligible to vote or to be elected, and if somebody doesn't want to be elected please send comment in this thread. Every maintainer could send 3 or less than 3 votes to other maintainers on the following comments and cannot send the votes to themself. The voting is available from now to 2021/12/31.

If you are not a maintainer of gitea, please don't send any comment in this thread and if you do that the comment will be deleted. Speak to us on discord if you have any comments about the community election.

Please see: https://github.com/go-gitea/gitea/issues/13801 for an example of how voting has happened in past years.

ping @go-gitea/maintainers

**Comment by lafriks** [comment]
First of all would like to say that our maintainers team has grown and it gets harder to choose who to vote for as there are many maintainers who really deserve to be nominated. I just want to say big thank you for everyone for giving your free time to maintain and contribute to Gitea, you are all great!

My votes will go to @lunny @techknowlogick @zeripath

**Comment by delvh** [comment]
I vote for @lunny @techknowlogick @zeripath as well.

**Comment by justusbunsi** [comment]
Same here @lunny @techknowlogick @zeripath

**Comment by 6543** [comment]
@lunny @lafriks @zeripath

**Comment by khmarbaise** [comment]
I vote the same here...  @lunny @techknowlogick @zeripath

Also from my side many thanks for your constant work.

**Comment by pat-s** [comment]
This project can be proud to have so many humble and active maintainers!

Maybe the number of owners could even be increased to 5?

Vote: @lunny @techknowlogick @zeripath

**Comment by Gusted** [comment]
Almost seems like a conspiracy theory 😄 

My votes goes to  @lunny @techknowlogick @zeripath

**Comment by pgaskin** [comment]
@lunny @techknowlogick @zeripath

**Comment by zeripath** [comment]
Steady as she goes from me.

@lafriks @techknowlogick @lunny

**Comment by a1012112796** [comment]
Vote: @lunny @techknowlogick @lafriks

**Comment by typeless** [comment]
@lunny @techknowlogick @zeripath

**Comment by strk** [comment]
@lunny @techknowlogick @zeripath

**Comment by jolheiser** [comment]
@lunny @techknowlogick @zeripath 

Looking forward to another year of Git and Tea! 🍵

**Comment by jpraet** [comment]
Big thanks to all maintainers!
@lunny @techknowlogick @zeripath

**Comment by gary-kim** [comment]
@lunny @techknowlogick @zeripath

**Comment by sapk** [comment]
@lunny @techknowlogick @zeripath

**Comment by richmahn** [comment]
@lunny @techknowlogick @zeripath

**Comment by techknowlogick** [comment]
As I did last year, I will cast my votes for the managers, as thanks for their hard work this year (and as always).

@zeripath @6543 @jolheiser

**Comment by khmarbaise** [comment]
My vote goes to:

@lunny @techknowlogick @zeripath

And thanks for their hard work this year...

**Comment by appleboy** [comment]
@lunny @techknowlogick @zeripath Thanks all!

**Comment by noerw** [comment]
@lunny @techknowlogick @zeripath :100:

**Comment by wxiaoguang** [comment]
@lunny @techknowlogick @zeripath

**Comment by guillep2k** [comment]
@lunny @techknowlogick @zeripath Thank you guys!!

**Comment by KN4CK3R** [comment]
@zeripath @wxiaoguang @6543

**Comment by techknowlogick** [comment]
We have now hit the new year in all parts of the world, and with that our election is now over.

Thank you to everyone for voting, for another year of wonderful contributions, and wishing you all a happy new year 🥂 2021 has been a difficult year, but one thing is for certain we have worked together on something we all can be proud of.

The new owner group, with their vote counts are:
@lunny | 23
@zeripath | 23
@techknowlogick | 22

I want to take a moment and give a heartfelt thanks to @lafriks for his work on the project for these past many years, and he was one of the main people who encouraged me to become more involved in this project. I hope you continue to participate in this wonderful community, and look forward to working with you more.

Election verification here: `curl -H "Accept: application/vnd.github.v3+json" "https://api.github.com/repos/go-gitea/gitea/issues/17872/comments?per_page=100" | jq -r ".[].body"` <- is the command I can to get all the comments in this thread.

**Comment by zeripath** [comment]
I'm greatly honoured to have been elected an owner. As @techknowlogick says, I'd like to give a heartfelt thanks to @lafriks for all his work on the project for these past many years! I too hope you continue to participate in the project and look forward to working with you more!

**Comment by lunny** [comment]
Thanks for all the contributors especially our @go-gitea/maintainers in last year. I believe Gitea community will become more active than before in 2022. Happy New Year for everyone!!!

**Comment by lafriks** [comment]
> I'm greatly honoured to have been elected an owner. As @techknowlogick says, I'd like to give a heartfelt thanks to @lafriks for all his work on the project for these past many years! I too hope you continue to participate in the project and look forward to working with you more!

Thanks, I'm not going anywhere, was quite busy this year because of work this year but once things settle I will be more active again :)
