### ISSUE TITLE
pull requests: wrong line numbers in discussions 

### ISSUE THREAD

**Issue by rnwgnr** [go-gitea/gitea#17875]
### Gitea Version

1.16.0+dev-630-g042cac5fe

### How are you running Gitea?

tested on try.gitea.io with a migrated repo

### Can you reproduce the bug on the Gitea demo site?

Yes

### Description

demo: https://try.gitea.io/murks/Vereinsdokumente/pulls/7

I've created a comment for line 23 in a PR. While everything is fine in the "Files Changed" tab, the text block in the conversation view is off-by-one which brings the comments out of context.

### Screenshots

`Files Changed` tab:
![image](https://user-images.githubusercontent.com/10488791/144265668-ca1936b0-3e03-4ef0-8012-6d5e4493cfac.png)

`Conversation` tab with wrong text section:
![image](https://user-images.githubusercontent.com/10488791/144265090-3004e8eb-9261-4a51-b04d-c654e653dcf5.png)

**Comment by lunny** [comment]
So which line is the right one?

**Comment by guzzisti** [comment]
Sorry, i've forget to add that information:
The comment has been created for line 23.

If you look at the screen of the `Conversation` tab you'll notice that the line numbers are adjusted to line 23, but the text is off-by-one. `## §4 Umgang mit der SARS-Cov-2-Pandemie` should be line 21 (as shown in the `Files Changed` tab), but is shown as line 22 in the `Conversation` view.

**Comment by jpraet** [comment]
Possibly some corner case in CutDiffAroundLine (https://github.com/go-gitea/gitea/blob/main/modules/git/diff.go#L135)?
I suspect it may have something to do with the `\ No newline at end of file`.
https://try.gitea.io/murks/Vereinsdokumente/pulls/7.diff

/cc @zeripath
