### ISSUE TITLE
Cannot register oauth with 2fa enabled

### ISSUE THREAD

**Issue by pgaskin** [go-gitea/gitea#1787]
- Gitea version (or commit ref): Since a while ago, I just haven't had time to fully check and report this issue.
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not tried
- Log gist: Nothing interesting in any of the logs.

## Description

I get invalid username or password when I try to link the account. Accounts I have already linked before adding 2fa work fine. See the video: https://minio.geek1011.net/tmp/gitea2faoauthbug.mp4?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=TQ30G7PMPOCD1KCJ7H1J%2F20170524%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20170524T005530Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=09ff69ef7234768837c69235baf316e72698ceea6668da0b29ed1de1904300c2

**Comment by lunny** [comment]
It seems there is already an issue to report this.

**Comment by pgaskin** [comment]
@lunny Which one (I thought this was reported, but I could not find the issue)?

**Comment by appIeboy** [comment]
<p align=right><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup>#1798</sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></p>

**Comment by techknowlogick** [comment]
@geek1011 I think #1509 so I will close this, but please re-open if you think it is different.
