### ISSUE TITLE
Action (accept_transfer): The process cannot access the file because it is being used by another process.

### ISSUE THREAD

**Issue by doggy8088** [go-gitea/gitea#17885]
### Gitea Version

1.15.6

### Git Version

2.34.1

### Operating System

Windows Server 2019

### How are you running Gitea?

I'm running Gitea as a Windows Service on Windows Server 2019 using LocalSystem identity.

### Database

PostgreSQL

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/doggy8088/24746886bc6f55ff933dfef676b8c215

### Description

I want to transfer repo's ownership to another account in my On-Prem Gitea installation. After I applied transfer to another account, the account opened his own notification message. Then press the green Approved button. The screen shows 500. All the detailed error log has been attached on this issue.

I doubted it's a bug on Windows Gitea.

### Screenshots

N/A

**Comment by silverwind** [comment]
This is almost certainly a Windows-only issue where some other process might "lock" the file by keeping a handle open. You can try using https://docs.microsoft.com/en-us/sysinternals/downloads/handle to find out which process it is.

**Comment by doggy8088** [comment]
@silverwind 
It seems `gitea.exe` locked the repo folder/files by itself. After I press "Accept Transfer" button, I tried to run the following command. Nothing been locked.  Is it possible Gitea on Windows locked the repo folder before accept transfer due to some unknown reason?

```sh
handle D:\Gitea
```

![image](https://user-images.githubusercontent.com/88981/144811020-f7201360-a8fa-44c4-874a-d66b8abe4a00.png)

**Comment by zeripath** [comment]
Yup almost certainly we've locked the repo ourselves. Probably it's in ctx.Repo.GitRepo and we need to close that before we move the repo.
