### ISSUE TITLE
Incorrect merge message (wrong direction)

### ISSUE THREAD

**Issue by siruoren** [go-gitea/gitea#17893]
### Gitea Version

1.15.7

### Operating System

docker

### Browser Version

edge 94.0.992.50

### Can you reproduce the bug on the Gitea demo site?

No

### Description

合并请求发起后，更新分子，代码合并是反方向的

### Screenshots

![image](https://user-images.githubusercontent.com/28772488/144572616-b10567e5-ee4a-49a3-b847-60d07656d7f0.png)

**Comment by wxiaoguang** [comment]
没有反。下面的红框里是指用户自己做了一个从 master 合并进入 其他分支 的操作。

It is correct, the below red block shows that a user committed a merge from main to their branch.
