### ISSUE TITLE
Binaries missing from assets in latest release

### ISSUE THREAD

**Issue by vwbusguy** [go-gitea/gitea#17891]
### Gitea Version

1.15.7

### How are you running Gitea?

Running Gitea using the provided Linux amd64 binaries posted on GitHub for each release.

### Can you reproduce the bug on the Gitea demo site?

Yes

### Description

The binaries that are normally provided are missing from assets in the most recent 1.15.7 release.  This has sadly broken our deployment scripts for Gitea.

### Screenshots

![image](https://user-images.githubusercontent.com/5474941/144502647-fb911efb-9fa8-4f74-9e5a-d826555bfd26.png)

**Comment by vwbusguy** [comment]
They also appear to be missing from the downloads site: https://dl.gitea.io/gitea/1.15.7

**Comment by vmario89** [comment]
i figured this out too. Will add some file check in our script to avoid running into web server error 500

**Comment by zeripath** [comment]
Give it time. They're being built.

**Comment by vwbusguy** [comment]
@vmario89 - Yeah, our script is aware when it fails to download and reports that GitHub is probably down, lol.  I'll try again after a bit.

**Comment by 6543** [comment]
-> https://drone.gitea.io/go-gitea/gitea/47604

**Comment by vwbusguy** [comment]
Looks like they're live now!
