### ISSUE TITLE
null pointer deref on migrating from other gitea instance

### ISSUE THREAD

**Issue by plsnp** [go-gitea/gitea#17896]
### Gitea Version

Gitea version 1.14.6 built with go1.16.7

### Git Version

git version 2.31.1

### Operating System

SUSE Linux Enterprise Server 15 SP3

### How are you running Gitea?

https://software.opensuse.org/download/package?package=gitea&project=devel%3Atools%3Ascm

### Database

SQLite

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/plsnp/9bb32fe059bd78a9e6eae0da09571a7a

### Description

A memory error was triggered when trying to migrate a repository from another gitea server (see log file)

**Comment by lunny** [comment]
Could you upgrade to v1.15.7 to try again?

**Comment by wxiaoguang** [comment]
Outdated, please open a new issue if there is still any problem
