### ISSUE TITLE
An organization can be added as a member of itself

### ISSUE THREAD

**Issue by pgaskin** [go-gitea/gitea#1789]
- Gitea version (or commit ref): 7b907ed348595e45d2d69cdabf70bfbbbb41c3ee
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes (https://try.gitea.io/org-bug-1)
  - [ ] No
  - [ ] Not relevant

## Description
You can add the organization as a member of itself.

**Comment by pgaskin** [comment]
Just realized, you can also add another org as a member of it too, which makes everything even more confusing.

**Comment by appIeboy** [comment]
<p align=right><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup>#1798</sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></p>

**Comment by appIeboy** [comment]
<p align=right><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup>#1798 @lunny @tboerger @sapk @cez81 @geek1011 @lafriks @ethantkoenig @andreynering @DblK </sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></p>
