### ISSUE TITLE
Reorder side menu

### ISSUE THREAD

**Issue by tboerger** [go-gitea/gitea#179]
IMHO the menu on the right side needs some reordering.

<img width="243" alt="bildschirmfoto 2015-08-04 um 13 07 04 1" src="https://cloud.githubusercontent.com/assets/156964/9059392/d5caa6de-3aa9-11e5-845b-bbbd1f0bb063.png">

The correct ordering should be:

- Issues
- Pulls
- Releases
- Wiki

Separator

- Commits

Separator

- Settings

**Comment by lunny** [comment]
I think Wiki is more useful than Pulls on a company git service. So I would like it be:

* Issues
* Wiki
* Pulls
* Releases
Separator
* Commits
Separator
* Settings

**Comment by nounoursheureux** [comment]
I think that Issues and Pulls should definitely be adjacent because they are tightly related, and settings should be separated from the others options.

**Comment by lunny** [comment]
@tboerger @fuxiaohei. Please let us make a decision.

**Comment by tboerger** [comment]
Issues and pulls should be together. I have suggested Wiki at the bottom in front of the seperator because it's the only one without a counting badge :)

**Comment by lunny** [comment]
I'm thinking your first idea is good. Please pr to the develop branch. @tboerger

**Comment by tboerger** [comment]
Ok, I will create the PR soon.

**Comment by tboerger** [comment]
Fixed with #189
