### ISSUE TITLE
Can't remove non-exisiting favorites

### ISSUE THREAD

**Issue by jhasse** [go-gitea/gitea#1792]
- Gitea version (or commit ref): ff2464c
- Git version: what try.gitea.io is using
- Operating system: what try.gitea.io is using
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant

## Description

I have added https://try.gitea.io/gitea/gitea to my favorites, but that repository seems to be deleted / moved. When I'm visiting https://try.gitea.io/jhasse?tab=stars now, clicking on the repo will result in a 404 error and I have no way to remove it from my favorites.

**Comment by jhasse** [comment]
Oh. I've just noticed that I only get a 404 for https://try.gitea.io/gitea/gitea when I'm logged in. So I guess this a different issue?

Sorry for the confusion.

**Comment by andreynering** [comment]
@lunny @bkcsoft Seems that the repo was deleted?

**Comment by DblK** [comment]
Maybe similar to #1797. I think **Units** might be the issue.

**Comment by bkcsoft** [comment]
https://try.gitea.io/gitea/gitea Still exists for me :/

**Comment by lunny** [comment]
@jhasse since #1797 is closed by #1873, maybe you can confirm that this issue is also resolved.

**Comment by jhasse** [comment]
Yes, it's fixed :) Thanks!
