### ISSUE TITLE
Pushing to a ref directly causes an error message

### ISSUE THREAD

**Issue by evilstiefel** [go-gitea/gitea#1793]
- Gitea version (or commit ref): 1.1.1+2-g2854c8aa
- Git version: 2.8.5
- Operating system: Ubuntu
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant

## Description

When pushing a (new) ref directly (e.g. git push develop:refs/wip/develop), some hook in Gitea fails to process it properly (possibly because it's assumed to be a branch name directly). You get an error-message while pushing:
```
git push origin develop:refs/wip/develop
Total 0 (delta 0), reused 0 (delta 0)
remote: 2017/05/24 11:57:17 [...tea/models/update.go:147 PushUpdate()] [E] GetBranchCommitID[refs/wip/develop]: object does not exist [id: refs/heads/refs/wip/develop, rel_path: ]
To ssh://*snip*/*snip*/*snip*.git
 * [new branch]      develop -> refs/wip/develop
```

Git itself doesn't care and the push is successful, I am unsure about the side effects within Gitea's web-interface though.

**Comment by appIeboy** [comment]
<p align=right><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup>#1798</sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></p>

**Comment by lunny** [comment]
I tested currently master. Both https and ssh are OK. Closed now and feel free to reopen it.
