### ISSUE TITLE
WebGUI: Escape character in folder or file name prevents access

### ISSUE THREAD

**Issue by sebveit** [go-gitea/gitea#17938]
* Gitea version (or commit ref): 1.15.7 built with GNU Make 4.1, go1.16.10 : bindata, sqlite, sqlite_unlock_notify
* Git version: 2.30.2
* Operating system: Debian GNU/Linux 11 (bullseye)
* Database (use [x]):
   - [x]  PostgreSQL
   - [ ] MySQL
   - [ ] MSSQL
   - [ ] SQLite
* Can you reproduce the bug at https://try.gitea.io:
   - [x] Yes (provide example URL): https://try.gitea.io/sebveit/meta-openwrt
   - [ ] No

### Description
I've cloned a repository from GitHub that uses the percentage character (%) in file and folder names a lot. This %-char prevents the access, via the web GUI of Gitea, to the file or folder containing this char in its name.
It looks like Gitea is displaying the %-char correctly but fails to provide the correct URL when clicking on it.
When I modify the URL and try to access it, nginx answers with `400 Bad Request`.

### Example
Expected URL: https://try.gitea.io/sebveit/meta-openwrt/src/branch/master/recipes-tweaks/busybox/busybox_%.bbappend
Actual URL: https://try.gitea.io/sebveit/meta-openwrt/src/branch/master/recipes-tweaks/busybox/busybox_%25.bbappend

### Reverse Proxy
I'm using nginx (1.18) as a reverse proxy for Gitea. My config for nginx is the following:

```
server {
    listen 443 ssl;
    server_name gitea.somedomain.tld;
    ssl_certificate     /etc/nginx/ssl/gitea.somedomain.tld.crt;
    ssl_certificate_key /etc/nginx/ssl/gitea.somedomain.tld.key;

    location / {
        proxy_pass http://localhost:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        client_max_body_size 50M;
    }
}
```

I hope that helps pinpointing the bug. Let me know if you need additional information.
BTW, Gitea is really nice and slim compared to the bloated GitLab.

**Comment by wxiaoguang** [comment]
Maybe this is a bug for path processing. However Actual URL `busybox_%25.bbappend` is correct. Non-standard characters should be encoded due to RFC.

**Comment by zeripath** [comment]
OK so this used to work in 1.14.7

This is going to be related to the chi migration.

**Comment by zeripath** [comment]
This is interesting the ctx.Params("*") appears to be "" even though the requestURI is correct...

**Comment by zeripath** [comment]
Right the problem is:

https://github.com/go-gitea/gitea/blob/f58e687a83b18d58298097d485f4febf98062dd7/modules/context/context.go#L484

This is double unescaping the Params("*") value.

Now I need to double check that this is always the case.
