### ISSUE TITLE
Support Incremental Backups

### ISSUE THREAD

**Issue by robd003** [go-gitea/gitea#17931]
### Feature Description

It would be great if there was a way to support incremental backups so you aren't constantly uploading a giant zip to Amazon S3 every day.

Backing up only changes and then once a month doing a full backup would be ideal.

**Comment by lafriks** [comment]
Probably for some data incremental backup could be doable, for example backing up only changed repository git data. But for some data (like db and some other assets, not so easy)

**Comment by wxiaoguang** [comment]
A possible method: do regular backup and use rsnapshot to get incremental data and upload it to S3, then you can control the whole backup progress.

Incremental backup is too complex and I am afraid it's not suitable to be a built-in feature for Gitea (neither for most applications)

**Comment by techknowlogick** [comment]
Closing per @wxiaoguang comment. This is what I would suggest as well.
