### ISSUE TITLE
Unable to mirror/migrate from another Gitea server hosted on a public IP address (self signed certificates)

### ISSUE THREAD

**Issue by Indiana3714** [go-gitea/gitea#17949]
### Gitea Version

Gitea v1.15.6

### Git Version

Git Version 2.34.1.windows.1

### Operating System

Windows 10

### How are you running Gitea?
Installed via Chocolatey on Windows locally and run via Powershell with admin rights, remote Gitea server is hosted on Ubuntu 20.04

### Database

SQLite

### Can you reproduce the bug on the Gitea demo site?

No

### Description

I have another **working Gitea** server already that's hosted with self signed certificate on a public IP address (not a proper domain name). **Cloning from this test pc using "git clone" using HTTPS works just fine** as it will prompt me for my remote Gitea server's username and password (To test that the issue is unique to Gitea and not Git, I've used the generally unsafe method of: "git config --global http.sslVerify false" before performing the "git clone" command)

**Trying to migrate a repository from a Gitea installed on the same said test pc unfortunately will always fail in the console with** 
```
Failed to create NewGiteaDownloader for: https://XXX:3000. Error: Get "https://XXX:3000/api/v1/version": x509: certificate signed by unknown authority
```
I've tried this on my daily driver Windows PC as well as on a separate Windows VM to see if it might be a local env issue.

**Other stuff I have tried but DON'T work:** 
1) Configuring "app.ini" and adding "SKIP_TLS_VERIFY = true" under both the headings [webhook] and [migrations]
2) Editing my local windows account user's "/.ssh/config" file
3) Variations of changes to my git config with other keys, also done on a "system" level rather than "global"
4) Using my remote Gitea server's access token makes no difference (the one created under the remote Gitea server's Settings > Applications > Manage Access Tokens)

I hope the recommendation won't be to just get a domain name? Since I believe self-hosting mirrors should be an integral part of the system?

### Screenshots
![gitea error screenshot](https://user-images.githubusercontent.com/41246263/145569566-3d3681fc-0ad5-493f-9629-cd08a85a8440.png)

**Comment by lunny** [comment]
This has been resolved in coming release v1.16 with an configuration option 
```ini
[migrations]
SKIP_TLS_VERIFY = true
```
But unfortunately, this will not be resolved in v1.15 .
