### ISSUE TITLE
Syntax highlight of characters in scheme code is buggy

### ISSUE THREAD

**Issue by msklywenn** [go-gitea/gitea#17948]
### Gitea Version

1.15.7

### Git Version

2.30.2

### Operating System

Debian

### How are you running Gitea?

I download gitea from the github releases and just run it from a systemd service.

### Database

MySQL

### Can you reproduce the bug on the Gitea demo site?

Yes

### Description

Characters are not highlighted properly in scheme code.
![image](https://user-images.githubusercontent.com/1546678/145561609-dfe6d51f-e18d-4a83-b289-a199103d44cf.png)
As can be seen on this screenshot taken from gitea demo site, #\(, #\[, #\< and #\{ should be displayed as one color, not seemingly random colors.

**Comment by silverwind** [comment]
Needs to be fixed in https://github.com/alecthomas/chroma.

**Comment by msklywenn** [comment]
Thanks for the info. I created a PR on their repo : https://github.com/alecthomas/chroma/pull/582

**Comment by msklywenn** [comment]
This has been fixed when chroma v0.10.0 was integrated. Thank you :)
