### ISSUE TITLE
Warehouse download button disabled

### ISSUE THREAD

**Issue by zqxvip** [go-gitea/gitea#17946]
### Gitea Version

1.15.7

### Git Version

2.30.1

### Operating System

Mac and win11

### How are you running Gitea?

docker container

### Database

SQLite

### Can you reproduce the bug on the Gitea demo site?

Yes

### Description

![image](https://user-images.githubusercontent.com/7312051/145510099-aad9ca15-f1b1-4ccf-ae26-6107428b96c2.png)

**Comment by wxiaoguang** [comment]
I can not understand what you mean. Please clarify the problem. If `Can you reproduce the bug on the Gitea demo site? Yes`, please show how to reproduce it, including the URL.
