### ISSUE TITLE
oauth callback raise an error while use gitea with woodpecker

### ISSUE THREAD

**Issue by zxcvbnm3057** [go-gitea/gitea#17969]
### Gitea Version

1.15.7

### Operating System

offical docker image gitea/gitea:latest

### How are you running Gitea?

Just request an oauth permission form woodpecker after woodpecker first install. Then there is the bug.

both in docker
gitea/gitea:latest
woodpeckerci/woodpecker-server:v0.14.3

Log in gitea
```
2021/12/14 04:34:01 Started GET /login/oauth/access_token for *****
2021-12-13T20:34:01.159542506Z 2021/12/14 04:34:01 Completed GET /login/oauth/access_token 405 Method Not Allowed in 259.322µs
```

Log in woodpecker
```
time="2021-12-13T20:34:01Z" level=error msg="cannot authenticate user. oauth2: cannot fetch token: 405 Method Not Allowed\nResponse: "
```

### Can you reproduce the bug on the Gitea demo site?

No

**Comment by 6543** [comment]
Well gitea work as expected if it get's an `GET` request as it expect a `POST`

![.](https://user-images.githubusercontent.com/24977596/145899416-117eef03-6797-443e-b297-c794a15f94bd.png)

**Comment by 6543** [comment]
@zxcvbnm3057 can you paste your woodpecker server config?

**Comment by 6543** [comment]
closing this issue as it's more a configuration issue at woodpecker -> https://github.com/woodpecker-ci/woodpecker/issues/609#issuecomment-992979051

**Comment by zxcvbnm3057** [comment]
Sorry for duplicate issue because in fact I don't know who caused the problem in fact...
