### ISSUE TITLE
Use A CI/CL Tool With Gitea

### ISSUE THREAD

**Issue by zxcvbnm3057** [go-gitea/gitea#17964]
Is there any CI/CL tools which can work only in the changed subproject and work fine with gitea?

For example, a spring cloud multi-module project has been updated on gitea, so then Drone will be triggered by it and rebuild all the subproject in this repository.

**Comment by techknowlogick** [comment]
Drone has a "trigger downstream" plugin that would allow you to start builds for other projects in drone when a primary git repo is also triggered.

**Comment by zxcvbnm3057** [comment]
I had look at that plugin before. But it is not useful for my condition. The multi-module project is not split into different git repository but in one, the subproject is child folder of parent. So what I need actually is listening for child floder's code change and only triger in that folder.

**Comment by 6543** [comment]
@zxcvbnm3057 so you look for something like a path condition?
(https://woodpecker-ci.org/docs/usage/conditional-execution#path)

**Comment by zxcvbnm3057** [comment]
Yes, just like `only/changes` syntax in Gitlab

**Comment by zxcvbnm3057** [comment]
@6543 Thanks, this seem like what I need. Thank you for your help!

**Comment by 6543** [comment]
@zxcvbnm3057 tld: you can do that with drone too - there should be a plugin around in combination to write starlak ...

but if you still searching for a ci I would recommend woodpecker anyway - ironic: I have no idea why :D

**Comment by zxcvbnm3057** [comment]
@6543 The drone is very small and light, but its document and forum has too many things not introduced. I am worried that soon or later there are some other questions waiting for me.

**Comment by zxcvbnm3057** [comment]
So is there any blog or post mention this? I have search 3 days but still got nothing helpful. Most of drone plugin require a git-diff future which gitea didn't provide. So if anyone has soluted this please must tell me.
