### ISSUE TITLE
Ability to set default merge style for pull requests for repository in app.ini

### ISSUE THREAD

**Issue by mctaguma** [go-gitea/gitea#17974]
### Feature Description

It would be ideal to be able to set the default merge style for pull requests for new repositories in app.ini.

This would make it possible to have "Squash and Merge" as the default merge style for all new repositories, reducing the likelihood of many commits from dev branches being merged to master, rather than squashing and merging a "summary" of the changes from the dev branch.

**Comment by delanym** [comment]
Yes please!

**Comment by benbourner** [comment]
Would like to see the ability to set defaults per branch. We prefer to squash features but retain the feature history when merging to master.

**Comment by Mo0rBy** [comment]
+1 on this

**Comment by vettamatt** [comment]
Gitea maintainers have already implemented this, unsure when this occurred.
`https://docs.gitea.com/administration/config-cheat-sheet#repository---pull-request-repositorypull-request`

**Comment by techknowlogick** [comment]
closing per last comment, due to it being implemented.

**Comment by benbourner** [comment]
I guess my comment about different defaults per branch was ignored. Should
I open another ticket?
