### ISSUE TITLE
Ability to create a tag on any commit from the web UI

### ISSUE THREAD

**Issue by Danita** [go-gitea/gitea#17986]
### Feature Description

As of now, you can only create a tag from the "New release" page, but that tag ends up pointing to the last commit of the selected branch. It would be good to be able to tag any commit from that UI or even from a contextual button on the commit view.

This would be useful for example managing tags by people organizing releases on multiple huge repos, for whom there's no other use to have a full clone locally.

### Screenshots

An implementation proposal:

![proposal](https://user-images.githubusercontent.com/754783/146080944-413a16ad-36ee-462b-a3e7-b266f3063e76.PNG)

**Comment by lunny** [comment]
We could put two dropdown buttons here, one is for creating a new tag, another is for creating a new branch.

**Comment by silverwind** [comment]
Dropdown is planned to be added in https://github.com/go-gitea/gitea/pull/17902.
