### ISSUE TITLE
Cant create a user. Error 1033 in file deploy_key.frm

### ISSUE THREAD

**Issue by PoncelasIvan** [go-gitea/gitea#17988]
### Gitea Version

gitea-1.15.7-linux-arm-6

### Git Version

2.20.1

### Operating System

Raspbian Buster

### How are you running Gitea?

As a systemd service or executing in bash as git user (./gitea web)

### Database

MySQL

### Can you reproduce the bug on the Gitea demo site?

No

### Description

 installed gitea on my newly configured raspberry pi 3b+.
When the web configuration panel finished the installation, the connection was redirected against  /user/login as usuall, but then the server stopped responding on port 3000, so I couldn't create a new user (I think that's the problem).

The gitea service runs correctly, but there is no server up on port 3000, I have tried to modify the app.ini file without success.

The error message I get from the logs is the following:

`
2021/12/14 23:28:23 routers/common/db.go:34:InitDBEngine() [I] Backing off for 3 seconds
2021/12/14 23:28:26 routers/common/db.go:27:InitDBEngine() [I] ORM engine initialization attempt #2/10...
2021/12/14 23:28:26 ...om/urfave/cli/app.go:524:HandleAction() [I] PING DATABASE mysql
2021/12/14 23:28:26 routers/common/db.go:33:InitDBEngine() [E] ORM engine initialization attempt #2/10 failed. Error: sync database struct error: Error 1033: Incorrect information in file: './gitea/deploy_key.frm'
`

**Comment by techknowlogick** [comment]
This is specifically an issue with MySQL/mariadb. They are saying something is off with its underlying files. See https://bobcares.com/blog/mysqldump-got-error-1033-incorrect-information-in-file/ for more info
