### ISSUE TITLE
Reorder the process of repo rename.

### ISSUE THREAD

**Issue by FlyingOnion** [go-gitea/gitea#17990]
### Feature Description

I'm facing a small problem when I implement my own notifier. When I implement `NotifyRenameRepository` function, I could not find the new repo name (the name in arg `repo *models.Repository` is the old name). After I check the code I found that `repo.Name = newRepoName` is called after function `repo_service.ChangeRepositoryName`.

There are two places:
https://github.com/go-gitea/gitea/blob/f58e687a83b18d58298097d485f4febf98062dd7/routers/web/repo/setting.go#L103

https://github.com/go-gitea/gitea/blob/f58e687a83b18d58298097d485f4febf98062dd7/routers/api/v1/repo/repo.go#L651

Wait for your opinion.

**Comment by lunny** [comment]
I think you can find the old and new name. `NotifyRenameRepository(doer *user_model.User, repo *repo_model.Repository, oldRepoName string)`.

**Comment by FlyingOnion** [comment]
In `NotifyRenameRepository(doer *user_model.User, repo *repo_model.Repository, oldRepoName string)`, `repo.Name` returns old name. `repo.Name` is updated after `func repo_service.ChangeRepositoryName(doer *models.User, repo *models.Repository, newRepoName string) error` function returns.

This is a brief order in `routers/api/v1/repo/repo.go` function `updateBasicProperties`, so as in `routers/web/repo/setting.go` function `SettingsPost`.
```
func updateBasicProperties(ctx *context.APIContext, opts api.EditRepoOption) error {
  repo := ctx.Repo.Repository
  repo_service.ChangeRepositoryName(ctx.User, repo, newRepoName) {
    notification.NotifyRenameRepository(doer, repo, oldRepoName)
  }
  repo.Name = newName
}
```
