### ISSUE TITLE
Gitea x keycloak with self sign cert dont work.

### ISSUE THREAD

**Issue by wagfeliz** [go-gitea/gitea#17996]
### Gitea Version

last

### Operating System

kubernetes 1.22

### How are you running Gitea?

Gitea and keycloak are running in an kubernetess cluseter with cert-manager self-sign certificates.
The hosts are set in /etc/hosts.

### Can you reproduce the bug on the Gitea demo site?

No

### Description

I setup an env on kubernetes with gitea and keycloak with valid self-sign certificate and after I configure openId connect : 

Failed to initialize OpenID Connect Provider with name 'Keycloak' with url 'https://keycloak.wade.com.br/auth/realms/master/.well-known/openid-configuration': Get "http://keycloak.wade.com.br/auth/realms/master/.well-known/openid-configuration": dial tcp: lookup keycloak.wade.com.br on 10.96.0.10:53: no such host

The address https://keycloak.wade.com.br is valid and with valid certificate both on kubernates and linux machine ( not in the nodes )

In the logs : 
[Macaron] 2021-12-15 17:34:45: Started GET /user/oauth2/Keycloak for 10.40.0.0
[Macaron] 2021-12-15 17:34:45: Completed GET /user/oauth2/Keycloak 500 Internal Server Error in 1.777143ms

I also tried with the http://keycloak.wade.com.br , get the same error.

Do gitea works with openId with self sign certificate ? Several people told me it should work, but so far I got no luck making this to work.

Any tips ?

**Comment by techknowlogick** [comment]
This isn't an issue related to self-signed certs. The DNS is unable to resolve the host of your keycloak server. `dial tcp: lookup keycloak.wade.com.br on 10.96.0.10:53: no such host`. You'll need to debug the DNS of your kubernetes cluster to resolve.
