### ISSUE TITLE
session expired everyday

### ISSUE THREAD

**Issue by fizzse** [go-gitea/gitea#18009]
### Gitea Version

1.15.7

### Operating System

docker

### How are you running Gitea?

docker image: gitea/gitea:1.15.7

### Database

MySQL

### Can you reproduce the bug on the Gitea demo site?

No

### Description

settings:

[session]
PROVIDER_CONFIG   = *******@tcp(db:3306)/gitea
PROVIDER          = mysql
GC_INTERVAL_TIME  = 864000
SESSION_LIFE_TIME = 864000 

question：
the session life I set is 10 days, but I need to log in again every day

**Comment by techknowlogick** [comment]
There is a ton of information missing from this report. As such I will close it. If you'd like to reopen it please provide at least the base information requested from the report form. Please also include relevant information from your config such as your session expiry time and browser, also are you using a revert proxy?
