### ISSUE TITLE
Customizing the logo with WebUI

### ISSUE THREAD

**Issue by snaildos** [go-gitea/gitea#18010]
### Feature Description

I think it would be great if Gitea had a webui to change the logo. Instead of changing the source, it's easier to just go to the WebUI and change the logo, just like bitbucket has. :)
Regards,
SnailDOS

**Comment by lunny** [comment]
you can do that already, see https://docs.gitea.io/en-us/customizing-gitea/#changing-the-logo and I think it's unnecessary to have a webui to do that.

**Comment by snaildos** [comment]
Yeah, Understandable. It's just a pain to that in docker. You'd need to rebuild your own image and stuff.
Oh well.
Thanks.

**Comment by wxiaoguang** [comment]
It seems that you did wrong to docker usage.

Why do you need to rebuild the image ...  You can just mount the volume.
