### ISSUE TITLE
Confirmation prompts: usability, accessibility, and clarity

### ISSUE THREAD

**Issue by fwdekker** [go-gitea/gitea#18014]
### Feature Description

<img src="https://user-images.githubusercontent.com/13442533/146550638-159d7b34-a1a6-403e-97a8-5ff52367fb03.png" width="50%" alt="Confirmation dialog on Gitea." align="right" /> Some actions in Gitea require the user to confirm the action in a prompt, for example when removing an email address or deleting an account. Currently, these confirmation prompts are formatted as _"Are you sure you want to delete this account?"_ or _"Are you sure you want to delete this repository?"_.

While certainly better than a vague _"Are you sure about this?"_, this still leaves room for error. Imagine a user removing one of multiple email addresses, but the user is unaware that they clicked the delete button next to the wrong email address. The user sees _"Are you sure you want to remove this email address?"_, wrongly interpreting what "this" refers to, confirm the action, and accidentally remove the wrong email address.

<img src="https://user-images.githubusercontent.com/13442533/146550700-3a9f99d8-10d5-4731-8a14-990740916477.png" width="50%" alt="Confirmation dialog on GitHub, where user has to type target before being able to confirm the action." align="right" /> I think the prompt text should be even clearer about what the user is about to do: _"Are you sure you want to delete the account **Frankie**?"_ and _"Are you sure you want to delete the repository **Frankie/MyFirstRepo**?"_. GitHub goes one step further when it comes to removing accounts/repos, and asks the user to write the name of the target in an input box. This would be great, but is, in my opinion, not required. (On the other hand, GitHub also does not mention the exact email address when removing an email address.)

---

Now that I look at Gitea's confirmation dialog, I think there's a few other important improvements to be made:
* [x] The user should be able to close the dialog very easily, in case they panic. Pressing `Esc` should close the dialog. Clicking in the grey area around the dialog should also close the dialog. Basically, doing anything other than clicking "Yes" should close the dialog.
* [x] The "No" button has a trash can icon. While probably intended to signify "Throw away this action", it can be misunderstood to mean "Throw away the email address". This is confusing. Perhaps the symbols should be removed from the buttons.
* [x] The buttons should be given colours: "Yes" should be red (i.e. danger), and "No" should remain transparent (i.e. neutral).
* [x] The text should be given a non-transparent background to make it easier to read; currently I experience minor accessibility issues while trying to read the text.

<img src="https://user-images.githubusercontent.com/13442533/146551946-397df487-8af9-40fc-a426-dfb2e7c58e24.png" width="50%" alt="Mockup confirmation dialog on Gitea that includes my suggestions." align="right" />

**Comment by delvh** [comment]
> The "No" button has a trash icon.

Already implemented in #17537.

**Comment by Ryuno-Ki** [comment]
Partly addressed in #19894

**Comment by FWDekker** [comment]
Not sure since when exactly, but at least as of v1.20.4 all of my points have been addressed :smile:
