### ISSUE TITLE
Incorrect issue href link from all issue list to the issue if unstandart http port

### ISSUE THREAD

**Issue by alexei-31** [go-gitea/gitea#18012]
### Gitea Version

1.15.7

### Operating System

Windows 64-bit

### Browser Version

Google Chrome 96.0.4664.110 64-bit

### Can you reproduce the bug on the Gitea demo site?

No

### Description

Incorrect issue href link to 80 port happend in browser from web page with all issue list to the issue, if user unstandart (not 80) http port configured for gitea server. Web page with all issue list has custom http port in address line in browser and in gitea configuration, but jump to the issue page by left mouse click was wrong 80 port.

### Screenshots

![gitea bug nonstandart port](https://user-images.githubusercontent.com/15984032/146509815-9e29ca08-ecc8-4f67-93d0-4e581727b36e.png)

**Comment by wxiaoguang** [comment]
Your ROOT_URL in `app.ini` is incorrect.

**Comment by silverwind** [comment]
Seems like a configuration issue.
