### ISSUE TITLE
Support pagination of commit and expand the limit of files in commit

### ISSUE THREAD

**Issue by laozhoubuluo** [go-gitea/gitea#18019]
### Feature Description

I migrated from GitLab to Gitea some time ago, and found that Gitea only prompts when there are more than 100 single commit files (large commits are caused by historical reasons), I only get a “Some files cannot be displayed due to too many files.” tips and can't see subsequent changes.

I personally hope that Gitea can consider supporting the pagination function for long commits and expanding the current length limit. GitLab supports a single commit to display 1000 files and this limit can be extended such as 2000 files or more.

Regardless of whether you can accept this demand, I would like to thank the Gitea development team for providing a good, high-performance Git platform solution for the industry.

### Screenshots

The following screenshots are from the GitLab.

![header](https://user-images.githubusercontent.com/31075951/146644341-66e76eb8-2ca3-4406-afc0-3ca5ef9e4546.png)

![footer](https://user-images.githubusercontent.com/31075951/146644352-d3c3f2e9-a95c-4f0f-9f3f-e3f57f7f97bb.png)

**Comment by jpraet** [comment]
The upcoming 1.16 release will have a "Show More" button to fetch the next page of affected files: #16829
Note that the limit of 100 is configurable with [MAX_GIT_DIFF_FILES](https://docs.gitea.io/en-us/config-cheat-sheet/#git-git) in `app.ini`.

**Comment by zeripath** [comment]
Yup I've recently implemented show more in #16829 & #16775. There are already several options for limiting inital diff generation. 

It would be helpful if you could try main and see if that implements your suggestion.

**Comment by wxiaoguang** [comment]
Outdated, please open a new issue if there is still any problem
