### ISSUE TITLE
"PASSWORD_COMPLEXITY" DO NOT work with update password when first login

### ISSUE THREAD

**Issue by FourLeafTec** [go-gitea/gitea#18036]
### Gitea Version

1.15.7

### How are you running Gitea?

Docker

### Database

SQLite

### Can you reproduce the bug on the Gitea demo site?

No

### Description

I set `PASSWORD_COMPLEXITY = lower,upper,digit,spec`.
Then I use admin to create account. Check "Require user to change password (recommended)".
The new user can set his password to "123456" when first login.

**Comment by jolheiser** [comment]
Did you restart gitea after making the config change?

**Comment by zeripath** [comment]
Duplicate of #17977

Already fixed by #18005 and its backport #18015
