### ISSUE TITLE
[UI] Buttons on "Submit review" popover out of viewport => review is not possible on mobile 

### ISSUE THREAD

**Issue by dpschen** [go-gitea/gitea#18055]
### Gitea Version

1.15.7

### Description

I am not able to review / approve even simple pull requests on mobile. 

Since the "Submit review" popover (with class `.diff-detail-box`) is positioned via `position: sticky` I am not able to approve pull requests on mobile anymore because the button is outside (below) the viewport).

I am not able to scroll down because the popover is emerging from the review-button.

### Screenshots

[This attached](https://user-images.githubusercontent.com/6173598/146917360-b894f43c-51ce-4dc7-bef5-a1613af59518.mp4) screen recording shows the issue:

- it shows a pull request page with the `files` tab selected
- before the recording I clicked the review button so the "Submit review" popover is already opened.
- the video shows me scrolling down and up with the intend to scroll to the approve button but unable to do so.

The resolution of the viewport in the screencast is from an iPhone 5 via Brave Desktop, but I got the same issue on a real iPhone 8 with Safari.

Note:
- I did not try to reproduce on https://try.gitea.io. If really necessary I can add that later.

**Comment by silverwind** [comment]
This was fixed, the reviewbox now stays in viewport.
