### ISSUE TITLE
Add Hungarian to translations in Crowdin

### ISSUE THREAD

**Issue by Avalancs** [go-gitea/gitea#1805]
I would like to translate Gitea on Crowdin, but do not see the Hungarian language there. Can it be added?

**Comment by lunny** [comment]
done. Please go to crowdin to translate.

**Comment by viktike** [comment]
Translated half of the strings.

**Comment by viktike** [comment]
@lunny translation is at 100%. What's the next step?

**Comment by lunny** [comment]
And all the translation approved? So just wait until v1.2 release. This new translation will be included in the new release.

**Comment by viktike** [comment]
They are not. Hope someone will do that. It doesn't make sense for me to approve my own work. Will wait for 1.2, thanks.

**Comment by Avalancs** [comment]
I will have a look at it this weekend, had little to no time recently, sorry :( (If I have permission anyways, I'm new to Crowdin)

**Comment by lunny** [comment]
@Avalancs I have gave you the permission. :)

**Comment by Avalancs** [comment]
@lunny the translations are going well. Can you also give @viktike approve rights? We have a nice consensus on the Hungarian translations.

**Comment by lunny** [comment]
done.

**Comment by viktike** [comment]
I'm done with my part of the approval process. Just to explain: we agreed to use formal translation instead of informal. In English, there is no much difference, but in Hungarian, there is.
