### ISSUE TITLE
404 error for repo link in repository code search results when language is zh-CN or zh-TW

### ISSUE THREAD

**Issue by Joannazyx** [go-gitea/gitea#18051]
### Gitea Version

1.15.5

### Git Version

git version 2.34.1

### Operating System

k8s

### How are you running Gitea?

running 1.15.5 in docker

### Database

MySQL

### Can you reproduce the bug on the Gitea demo site?

No

### Description

When language is set to zh-CN(简体中文) or zh-TW（繁体中文（台湾））, and start a code search in a repository, the repo link in results is a long path, and redirects to a 404 page.

![image](https://user-images.githubusercontent.com/4640297/146861082-40d03ac6-6c69-4a7a-9ac2-97cde9094e38.png)

In other languages, results of repository code search will only show repo name and the link is correct.
![image](https://user-images.githubusercontent.com/4640297/146862230-43ed3782-6b91-4d80-8ef7-7a726d3cba91.png)

The reason seems obvious. The order of string fields in search.results is different in English and Chinese, but they use the same template.
code in templates\repo\search.tmpl, require order of string fields to be Keyword, RepoLink, RepoName.
`		{{if .Keyword}}
			<h3>
				{{.i18n.Tr "repo.search.results" (.Keyword|Escape) .RepoLink .RepoName | Str2html }}
			</h3>`
code in options\locale\locale_en-US.ini
`search.results = Search results for "%s" in <a href="%s">%s</a>`

code in options\locale\  zh-CN and zh-TW
`search.results=在 <a href="%s"> %s </a> 中搜索 "%s" 的结果`

**Comment by lunny** [comment]
Hm, we should update crowdin and update directly in v1.15. It should be v1.15.9 because v1.15.8 just tagged.
