### ISSUE TITLE
[Feature Request] Allow deleting issues

### ISSUE THREAD

**Issue by MightyPork** [go-gitea/gitea#18056]
### Feature Description

I would like to be able to completely delete issues (other than through postgres). It can be limited to admin users.

This can be done on gitlab.

Example: spam posted as an issue report. I deleted the links and changed title, but it still stays in the repo.

![Screenshot_20211221_121105](https://user-images.githubusercontent.com/2041118/146920853-d0fa36b5-f659-4cab-aa0a-4e30a8e4490e.png)

**Comment by lunny** [comment]
related #923
