### ISSUE TITLE
Can not migrate repositories from private IPs

### ISSUE THREAD

**Issue by oper1000** [go-gitea/gitea#18065]
### Gitea Version

1.15.8

### Operating System

Client:Windows 10    Server:Debian 10.9

### How are you running Gitea?

use docker:  gitea/gitea:1.15.8 + mysql:8  image
Install with Docker Compose

use yml file get from https://docs.gitea.io/zh-cn/install-with-docker/

### Database

MySQL

### Can you reproduce the bug on the Gitea demo site?

Yes

### Description

Why i can not Can not migrate repositories from private IPs

there's two server all in LAN (private net)

i want Migrate from other server that already have git datas.
but Gitea tell me can not do like this , why ?

help me ,thanks a lot .

### Screenshots

![企业微信截图_20211222145303](https://user-images.githubusercontent.com/993995/147048733-70a12805-2417-4eaf-b077-dff128c1c177.png)

**Comment by qwerty287** [comment]
You can set `ALLOW_LOCALNETWORKS` under the [`migration` category](https://docs.gitea.io/en-us/config-cheat-sheet/#migrations-migrations) to `true` in your `app.ini` file.

**Comment by wxiaoguang** [comment]
That's why I changed the i18n text to below in 1.16:

```
migrate.permission_denied_blocked = You can not import from disallowed hosts, please ask the admin to check ALLOWED_DOMAINS/ALLOW_LOCALNETWORKS/BLOCKED_DOMAINS settings.
```
