### ISSUE TITLE
Add version string to metrics

### ISSUE THREAD

**Issue by steled** [go-gitea/gitea#18061]
### Feature Description

Hi,

I'm monitoring my Gitea instance via Prometheus and Grafana.
It would be great to have a string for the current Gitea version and the new one in the metrics to set an Grafana alert for possible new version on it.

**Comment by Flygrounder** [comment]
Sounds like a useful feature. But Prometheus does not support string metrics and adding version string as a label does not sound like a good idea.

Maybe we should convert semver to an integer e.g.  1.15.9 = 1 * 100^2 + 15 * 100 + 9 = 11509

**Comment by techknowlogick** [comment]
@Flygrounder that's a good suggestion, although I'm not sure it'd work in all cases, as there are occasions when the version wouldn't always be in a format that could be converted so cleanly, ex `v1.16.0-dev-796-gd228d346c`

**Comment by Flygrounder** [comment]
But this is only the case with dev versions, for which you probably do not want to get alerts because they are constantly updated. Perhaps in that case reporting `11600` would be fine.

**Comment by wxiaoguang** [comment]
I think we had better keep the original version format, and just use a new field like `updateAvailable` to indicate that there is a new update. Converting a version string to an (big) integer may introduce new problems.

**Comment by Flygrounder** [comment]
What is the current format for version ? It seems like currently there is no version metric for Prometheus. 

Additional benefit of having version metric in contrast to `updateAvailable` is that you can correlate other metrics to the specific Gitea version and see how well each version performs.

**Comment by jonpalmisc** [comment]
If you've just gotten a notification about this PR, I regret to inform you that I am being forced to make this PR as part of an academic assignment. I will be closing it after the assignment has been submitted, unless for some reason this is deemed an acceptable fix.

**Comment by 6543** [comment]
https://github.com/go-gitea/gitea/pull/18454#pullrequestreview-867011850

**Comment by mwasilew2** [comment]
I think that what you use for "semi-automated" upgrades or upgrade notifications varies from environment to environment and it would be hard to provide a unified approach. This is not to say that Gitea shouldn't include an approach for that (e.g. a notification in the admin panel or an email sent to the Gitea admins saying that a new version is available).

I'm not sure what would be the best approach to populating a Prometheus metric with the latest available version of Gitea.

Some ideas for how to approach the problem of picking up new versions automatically:
- https://github.com/containrrr/watchtower
- https://github.com/renovatebot/renovate

Regardless of the mechanism used for updating, I think it's still useful to expose build info, so I opened: https://github.com/go-gitea/gitea/pull/22819

**Comment by delvh** [comment]
> This is not to say that Gitea shouldn't include an approach for that (e.g. a notification in the admin panel or an email sent to the Gitea admins saying that a new version is available).

FYI: That exists already. https://docs.gitea.io/en-us/config-cheat-sheet/#cron----check-for-new-gitea-versions-cronupdate_checker

**Comment by lunny** [comment]
resolved by #22819
