### ISSUE TITLE
Dark Theme: Syntax Highlighting Colors is very Bland

### ISSUE THREAD

**Issue by hhhapz** [go-gitea/gitea#18071]
### Gitea Version

1.15.3 (and also 1.16.0+dev-589-g2dae5b715)

### Operating System

(Not Relevant)

### Browser Version

(Not Relevant)

### Can you reproduce the bug on the Gitea demo site?

Yes

### Description

Many of the syntax highlighting keywords from chroma are the same color as the default text, which yields a poor user experience for reading and reviewing code on the platform. As compared to the light mode theme, many of the css classes (e.g `.chroma .kd`) have the same color.

cc: @jolheiser 

### Screenshots

Light Mode:
![image](https://user-images.githubusercontent.com/29532600/147113952-53afbcab-d93f-4172-b4d7-a50a32f2f001.png)

Dark Mode:
![image](https://user-images.githubusercontent.com/29532600/147113969-f60bd767-0cf0-494d-91a7-31ecec12d5df.png)

Light Mode CSS Rule Example:
![image](https://user-images.githubusercontent.com/29532600/147114064-76f5d152-c7ea-4d2a-8d62-0efbd9353104.png)

Dark Mode CSS Rule:
![image](https://user-images.githubusercontent.com/29532600/147113992-80fcda24-0945-419f-93fa-e666244c6adb.png)

**Comment by silverwind** [comment]
Agree, we should improve this so that each detected syntax token has a distinct color.

**Comment by Fogapod** [comment]
python `from` imports:

![image](https://user-images.githubusercontent.com/22667809/175893811-06216a6f-291a-4c29-989d-0d510f75f869.png)
![image](https://user-images.githubusercontent.com/22667809/175893937-01b349f9-5fe3-4888-8d22-c87fde9d4404.png)

everything else looks fine so far

**Comment by wxiaoguang** [comment]
It should have been fixed by a recent PR.
