### ISSUE TITLE
Login topbar is aligned left not center

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#1807]
![untitled](https://cloud.githubusercontent.com/assets/81045/26434068/039ef096-4139-11e7-9f15-3660204973bd.png)

**Comment by lunny** [comment]
This is not fixed.

**Comment by lunny** [comment]
@ethantkoenig

**Comment by ethantkoenig** [comment]
@lunny ? https://try.gitea.io/user/login?redirect_to= looks aligned to me

![image](https://user-images.githubusercontent.com/8990880/27003820-f1bb8f84-4dcb-11e7-8b9f-91e1d8c40555.png)

**Comment by lunny** [comment]
@ethantkoenig I tested locally and there is only `User/Password`, it's not fixed.

**Comment by ethantkoenig** [comment]
@lunny Could you take a screenshot?

**Comment by lunny** [comment]
![untitled](https://user-images.githubusercontent.com/81045/27007349-0d1e360c-4e83-11e7-85f4-b8d4dde43d4a.png)

**Comment by lunny** [comment]
Chrome on macOS

**Comment by bkcsoft** [comment]
@lunny Which version is this? When you don't have OpenID/OAuth enabled you should not get the tabs at all...

**Comment by bkcsoft** [comment]
since this isn't critical I'm moving this to v1.x

**Comment by cez81** [comment]
Looks OK nowadays. Chrome 64 on macOS

![image](https://user-images.githubusercontent.com/9416498/36064273-c897ff7e-0e88-11e8-892b-029c09c5d2db.png)
