### ISSUE TITLE
Unable to scroll to see all content in Blame window

### ISSUE THREAD

**Issue by richmahn** [go-gitea/gitea#18074]
### Gitea Version

v1.16-dev

### Git Version

v2.30.1

### Operating System

MacOS ARM1

### How are you running Gitea?

Local build from main

### Database

MySQL

### Can you reproduce the bug on the Gitea demo site?

Yes

### Description

When viewing a large file in Blame, you can't scroll to the right.

Happening for me in Chrome, but not in Safari. Can scroll in Safari.

**Comment by richmahn** [comment]
Note, if I inspect source and set the CSS for the container to be overflow: scroll, I can scroll to the right.

![image](https://user-images.githubusercontent.com/2839925/147126586-95cd5d72-fe41-4874-8810-34477b1aba40.png)

**Comment by silverwind** [comment]
IIRC long lines should always wrap the text, are they not wrapping for you?
