### ISSUE TITLE
[Question] How to get information in post-receive git hook

### ISSUE THREAD

**Issue by UziTech** [go-gitea/gitea#1808]
How can I get the information provided to stdin in the git post-receive hook?

I've tried

```sh
read var
echo $var
```

and it returns nothing

**Comment by bkcsoft** [comment]
`post-receive` hook doesn't get anything from stdin. See git documentation on how to use it: https://git-scm.com/docs/githooks

**Comment by UziTech** [comment]
> **post-receive**
>
>This hook is invoked by git-receive-pack on the remote repository, which happens when a git push is done on a local repository. It executes on the remote repository once after all the refs have been updated.
>
> This hook executes once for the receive operation. It takes no arguments, but **_gets the same information as the pre-receive hook does on its standard input_**.

**Comment by UziTech** [comment]
> **pre-receive**
> 
> This hook executes once for the receive operation. It takes no arguments, but for each ref to be updated it receives on standard input a line of the format:
> 
> `<old-value> SP <new-value> SP <ref-name> LF`
