### ISSUE TITLE
[API] Subscribing user to issue produces nil in API reponse

### ISSUE THREAD

**Issue by realaravinth** [go-gitea/gitea#18090]
### Gitea Version

743-g7cc44491f

### How are you running Gitea?

Tested on https://try.gitea.io

### Can you reproduce the bug on the Gitea demo site?

Yes

### Description

When subscribing a user through the API to an issue, it returns the following error when the operation is forbidden:

```json
{
  "message": "%!s(<nil>)",
  "url": "https://try.gitea.io/api/swagger"
}
```
This is probably harmless but can be fixed to return an appropriate error message like so:

```json
{
 "message": "Only admin and user for itself can change subscription",
"url": "https://try.gitea.io/api/swagger"
}
```
The problem seems to be in this line:
https://github.com/go-gitea/gitea/blob/7cc44491fae1e5f00616a5b8d8da2934a8a619f8/routers/api/v1/repo/issue_subscription.go#L131

I'll be happy to submit a patch to this effect!

### Screenshots

![image](https://user-images.githubusercontent.com/33521410/147348285-461efe74-0fac-4b6e-9090-fea898c7a604.png)

**Comment by zeripath** [comment]
This can only occur if you're trying to subscribe a user that isn't the logged in user or you're not the admin.

It will be coming from 

```go
	//only admin and user for itself can change subscription
	if user.ID != ctx.User.ID && !ctx.User.IsAdmin {
		ctx.Error(http.StatusForbidden, "User", nil)
		return
	}
```

**Comment by realaravinth** [comment]
The error(403 forbidden) is alright and is working according to spec but I was referring to the message. It's a minor thing but a descriptive error message might come in handy while debugging
