### ISSUE TITLE
Commit username section cannot display commit's owner.

### ISSUE THREAD

**Issue by umut-akkaya** [go-gitea/gitea#18106]
### Gitea Version

1.15.7

### How are you running Gitea?

Running on linux server as a systemd service.

### Database

PostgreSQL

### Can you reproduce the bug on the Gitea demo site?

No

### Description

My gitea doesnt show username's of commits. It only show "Your Name".

### Screenshots

![Screenshot from 2021-12-25 22-41-41](https://user-images.githubusercontent.com/17011399/147392425-152ea9b1-3dfd-460a-acf9-1b5c1d34c950.png)

**Comment by wxiaoguang** [comment]
Does the git email match your Gitea account?

**Comment by theumut57** [comment]
> Does the git email match your Gitea account?

My email domain does not exist. I am going to set up an email server but it is not completed. How can chech it ?

**Comment by zeripath** [comment]
Git commits are mapped to Gitea users by matching the email address of the commit author with a Gitea user with that email address. 

How else would you expect Gitea to match commits with users?

**Comment by theumut57** [comment]
> Git commits are mapped to Gitea users by matching the email address of the commit author with a Gitea user with that email address.
> 
> How else would you expect Gitea to match commits with users?

So how can i make it match ?

**Comment by theumut57** [comment]
@zeripath @wxiaoguang  Thank you for all. I have solved the problem by configing git user.name user.email. I thought setting username and pass on android studio fix the problem but it did'nt. Is it because android studio only deal with auth not config ?
