### ISSUE TITLE
Can't delete account when logged in through OAuth

### ISSUE THREAD

**Issue by catdevnull** [go-gitea/gitea#18105]
### Gitea Version

1.15.6

### How are you running Gitea?

Void Linux package

### Database

SQLite

### Can you reproduce the bug on the Gitea demo site?

Yes

### Description

It is not possible to delete an account when logged in through OAuth as the form for doing it asks for a password.

### Screenshots

![image](https://user-images.githubusercontent.com/86896666/147392224-10e32eb6-8efa-4741-96e4-c53d77ccf215.png)

**Comment by wxiaoguang** [comment]
More details in
* https://github.com/go-gitea/gitea/issues/18329
