### ISSUE TITLE
Allow non logged in users to view releases

### ISSUE THREAD

**Issue by Jragon** [go-gitea/gitea#1810]
- Gitea version (or commit ref): 1.1.0
- Operating system: Ubuntu
- Database (use `[x]`):
  - [x] MySQL

## Description

I'd like to allow non logged in users to view our releases and download the executables. I really like the release page at the moment, but a lot of the people who want to download the release files don't want to have to create an account.

Thanks!

**Comment by bkcsoft** [comment]
This is actually a bug introduced with Units.

**Comment by ethantkoenig** [comment]
Fixed by #1999
