### ISSUE TITLE
After migrating the Gitea application as a whole, the old repository doesn't display commits count and public activity properly

### ISSUE THREAD

**Issue by suiyueou** [go-gitea/gitea#18108]
### Gitea Version

1.15.7 built with GNU Make 4.1, go1.16.10 : bindata, sqlite,

### Git Version

git version 2.34.1

### Operating System

Ubuntu 20.04.1

### How are you running Gitea?

GitHub Repository Release Page Download.

Using systemd.

### Database

SQLite

### Can you reproduce the bug on the Gitea demo site?

No

### Description

**The following content is from deepl translator:**

After migrating the Gitea application as a whole, the old repository doesn't display commits count and public activity properly:

* The submitted quantity is not displayed properly：

For example, before the migration, there were 53 commits in the gitea repository, and after the migration, the number of commits visible on the gitea page was also 53. However, if I commit a new commit in my local git repository and push it to gitea, no matter how much I refresh the page, the number of commits visible on the gitea page will be 53 and will not show the latest 54.

![image](https://user-images.githubusercontent.com/48700331/147399849-63ec4141-3a1f-45f3-b95d-17200c20d30d.png)

If I restart gitea and refresh the page again I can see that the commit count is updated to 54, but if I continue to upload new commits from local, it will still repeat the above description unless I restart again.

* Public Activity cannot be displayed properly：

In addition to the previous issue, the new commit activity is not displayed in the Public Activity, I submitted 3 commits to test if they are valid, but the latest commit activity is not displayed:

![image](https://user-images.githubusercontent.com/48700331/147399858-6eddcd0b-92c3-4ad8-ac51-9934603e4590.png)

And, both of these issues are only with the old repository before the migration, the new repository created after the migration everything is fine.

**Comment by zeripath** [comment]
As an admin user on the administration dashboard settings page click the resynchronize hooks page

**Comment by cainb** [comment]
> As an admin user on the administration dashboard settings page click the resynchronize hooks page

Solved! Thank you so much!

**Comment by wxiaoguang** [comment]
Since 1.16, this problem won't occur again, 1.16 will auto re-sync the hooks if the Gitea app path changes. So the issue can be closed.
