### ISSUE TITLE
range over the pointer of a slice

### ISSUE THREAD

**Issue by azhai** [go-gitea/gitea#18118]
### Gitea Version

e4e3df6c66dbeac6ac5bceff8ac4f05dbea30d70

### Git Version

2.34

### Operating System

CentOS 7

### How are you running Gitea?

In go 1.18 beta1:
TAGS="bindata" make build

### Database

MySQL

### Can you reproduce the bug on the Gitea demo site?

No

### Description

`modules/indexer/code/bleve.go:427:23: cannot range over languagesFacet.Terms (variable of type *search.TermFacets)`

A similar bug in StackOverflow
[golang-cannot-range-over-pointer-to-slice](https://stackoverflow.com/questions/21278023/golang-cannot-range-over-pointer-to-slice)

### Screenshots

![image](https://user-images.githubusercontent.com/47268/147620240-20b9473c-f019-4193-a638-0b4c848b1a56.png)

**Comment by azhai** [comment]
github.com/blevesearch/bleve/v2 v2.3.0

**Comment by Gusted** [comment]
> In go 1.18 beta1:
> TAGS="bindata" make build

The golang version is still in beta. Does this error also popup on go 1.17.x?

I'm quite confused by the fact that golang could error at that point of the code.

https://github.com/go-gitea/gitea/blob/e4e3df6c66dbeac6ac5bceff8ac4f05dbea30d70/modules/indexer/code/bleve.go#L427

Is totally correct code, as it will be looping over the type of `Terms`, which is `TermFacets`, which is a type alias for ` []*TermFacet`, which is not the same type. It's currently `search.TermFacets`, but as shown in the screenshot it somehow managed itself to be a pointer type.

**Comment by azhai** [comment]
Change languagesFacet.Terms to languagesFacet.Terms.Terms()
```go
#modules/indexer/code/bleve.go line 425
languagesFacet := result.Facets["languages"]
for _, term := range languagesFacet.Terms.Terms() {
}
```

**Comment by Gusted** [comment]
https://github.com/blevesearch/bleve/pull/1404/files Ah well bleve broke it. I'm not sure about how golang handles it, but gitea's bleve version is currently `v2.0.6` and it's vendored as well. so I'm not sure if this is a bug. Given that we aren't supporting(unless bleve is upgraded within gitea) this version yet.
