### ISSUE TITLE
Conflict detection broken for PRs that have been updated via merge to resolve conflicts

### ISSUE THREAD

**Issue by CirnoT** [go-gitea/gitea#18130]
### Gitea Version

1.16.0+dev-759-g8ce1b539b

### How are you running Gitea?

Docker (:dev-rootless) or https://try.gitea.io

### Can you reproduce the bug on the Gitea demo site?

Yes

### Description

Exists since #18004 was merged (so since f1e85622da0492fa01d8449eb938197cd4fa65bf; last working is 9296baf65a73ccdda329b45770d22390ead7905f).

Simplest example can be seen on https://try.gitea.io/Yumaa/kanna/pulls/1

**Comment by lunny** [comment]
Maybe @zeripath can help.
