### ISSUE TITLE
Allow Collaborators with read-only-access to be set as Pull Request and Issue assignees

### ISSUE THREAD

**Issue by der-jannik** [go-gitea/gitea#18144]
### Feature Description

I think it would be great if Gitea had the ability to assign Collaborators with read-only repository access. 

The usecase would be to use a fork-driven contributor model, so that not every team member has to get write access to an repository with complicated branch protection rules for every single branch.

**Comment by Gusted** [comment]
> I think it would be great if Gitea had the ability to assign Collaborators with read-only repository access.

Do you mean:
![image](https://user-images.githubusercontent.com/25481501/147862226-92eda4ed-be32-4a36-bad0-8a29b4c8e4d7.png)
