### ISSUE TITLE
Repository size and languages percentage doesn't update when repo updated manually

### ISSUE THREAD

**Issue by dehghani-mehdi** [go-gitea/gitea#18154]
### Gitea Version

latest

### Git Version

2.27.0

### Operating System

Windows 10

### How are you running Gitea?

By running `Gitea` via command-line

### Database

SQLite

### Can you reproduce the bug on the Gitea demo site?

No

### Description

When I push offline/manually repository size and languages percentage doesn't update, by offline I mean copy bare repository from somewhere else and paste to repo location, not by pushing to `http://localhost:....`

**Comment by Gusted** [comment]
I think this is working as intended from my perspective. As I'm pretty sure that Gitea doesn't allow nor support that users are messing around with the repo's that Gitea is hosting. As a lot of functionality(like language and size) isn't generated on-demand, but they are generated when their are new commits on the main branch.

**Comment by dehghani-mehdi** [comment]
Gitea shows all commits and files correctly, even tho I manually update the repo.

**Comment by Gusted** [comment]
> Gitea shows all commits and files correctly, even tho I manually update the repo.

Well, that doesn't imply that it's allowed or supported. I'm against it, as allowing this can cause for a lot of undefined behavior. Maybe some other maintainer want's to shed some light 🤷🏽

**Comment by dehghani-mehdi** [comment]
Other maintainer can set the remote url to `file://path/to/repository.git`, as I do, in fact we currently working this way without any problem.

I can make a fake commit and push via `http://localhost:....`, so Gitea update repo info (e.g languages and size), but I'm not happy with it. that's why I filed this issue.

**Comment by Gusted** [comment]
> so Gitea update repo info (e.g languages and size), but I'm not happy with it. that's why I filed this issue.

Well you could manually update it by going to the settings page of the repo and then click on the `Add to the Re-Index queue`

![image](https://user-images.githubusercontent.com/25481501/147882474-d5cab459-c5fd-46c0-b1ed-9c45c034f30d.png)

**Comment by dehghani-mehdi** [comment]
I can not see `Code Statistics Indexer` section. all I have is this:

![image](https://user-images.githubusercontent.com/9152330/147882561-a1ce6c33-fd5d-4074-a937-74e4e0ce1d6a.png)

**Comment by Gusted** [comment]
https://github.com/go-gitea/gitea/pull/17494 It will be added in the next release.

**Comment by dehghani-mehdi** [comment]
By doing that, the language and size info will be updated correctly?

**Comment by Gusted** [comment]
Yap. It then takes the latest commit(doesn't mater if it was pushed online or offline).

**Comment by a1012112796** [comment]
Maybe that's not usefull for repository size ...

**Comment by Gusted** [comment]
> Maybe that's not usefull for repository size ...

🤷🏽 I'm pretty sure that gitea doesn't support nor handle that users are messing around with the repo's under the data folder. So it's just own-risk and what works, that works.
