### ISSUE TITLE
Dependency `github.com/hashicorp/go-version v1.3.1`  doesn't exist

### ISSUE THREAD

**Issue by iazkaban** [go-gitea/gitea#18150]
### Gitea Version

v1.15.9 

### How are you running Gitea?

我在直接go get 引入gitea的时候，发现gitea引用了

github.com/hashicorp/go-version v1.3.1

这个包，但是看起来可能是包作者把这个tag删掉了，目前最新的版本是v1.3.0所以导致了引入gitea时报错，不知道gitea会不会考虑修复引用的问题

### Can you reproduce the bug on the Gitea demo site?

No

### Description

我在直接go get 引入gitea的时候，发现gitea引用了

github.com/hashicorp/go-version v1.3.1

这个包，但是看起来可能是包作者把这个tag删掉了，目前最新的版本是v1.3.0所以导致了引入gitea时报错，不知道gitea会不会考虑修复引用的问题

**Comment by 6543** [comment]
https://github.com/go-gitea/gitea/blob/main/go.mod#L141

https://go.dev/doc/modules/gomod-ref

we use a fork to allow parsing versions not compatible to semversion compliant ...
used by the git project etc ...

**Comment by wxiaoguang** [comment]
Please report in English.

And as 6543 said, Gitea uses an aliased package, not the official hashicorp/go-version.

**Comment by iazkaban** [comment]
found the problem:

until golang 1.17.5

if you import a project and it import a package by using "replace" in go.mod

go get will not find the right package whitch behind '=>'

maybe you can add the same replace message in your own go.mod???
i don't known if it's a right way,but it works

**Comment by wxiaoguang** [comment]
So what you mean is: you are working on a new project, which imports `gitea`, then the imported `gitea` package can not use the aliased `go-version` package, right?
