### ISSUE TITLE
Unable to build Gitea 1.15.9 for ARMv7

### ISSUE THREAD

**Issue by MPeti1** [go-gitea/gitea#18167]
### Gitea Version

1.15.5

### Operating System

Debian

### How are you running Gitea?

I'm building Gitea for myself, to be able to run it on ARMv7.
For that I use `docker buildx build --platform linux/arm/v7 ...`

### Database

MySQL

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/MPeti1/4d89749defbddf51bb5b621ef804881f

### Description

I have problems with building Gitea 1.15.9 for ARMv7 architecture.
The included "Log Gist" includes the build error as output by docker buildx.

The problem was probably introduced with #18048. The problem itself is that the new base image for the build environment is not being built for ARMv7, and so the docker build system cannot build Gitea solely based on the instructions of `Dockerfile.rootless`.

I think a workaround might be to _also_ build that new base image locally for the required architecture, but I cannot find the sources of that image, as it is not linked to from the Docker Hub page of the image.

**Comment by MPeti1** [comment]
I think this might also mean that Gitea currently cannot be totally self-built, because the build-env's base image cannot be built in lack of sources.

**Comment by lunny** [comment]
Maybe @techknowlogick can help.

**Comment by techknowlogick** [comment]
Can you try now? I just published an arm/v7 variant of the upstream image. https://hub.docker.com/layers/techknowlogick/go/1.16-alpine3.13/images/sha256-2b3903ccd375a8ed7d5661dd644aaa17a57981f8fd6452e89ccff639f8e36261?context=explore

**Comment by MPeti1** [comment]
It now did not error out early so I think it will be ok now, thank you.
Though it still would be nice to have the sources available. Would you consider publishing it, please?

**Comment by techknowlogick** [comment]
The source is https://github.com/docker-library/golang/ but I'm building for alpine 1.13 instead 1.15, and from the link in my last comment you can see the source of each layer in the image.
