### ISSUE TITLE
Allow movie as attachements

### ISSUE THREAD

**Issue by Glandos** [go-gitea/gitea#18169]
### Feature Description

Currently, there is a hardcoded list of allowed MIME types: https://github.com/go-gitea/gitea/blob/ab77a24f18ae45248bd6c71778fe3bfacacf864f/modules/setting/attachment.go#L19

However, it should be great to be able to upload webm/mp4 short movies, that are really more efficient for small dynamic screen reports.

**Comment by Gusted** [comment]
> Currently, there is a hardcoded list of allowed MIME types:

It's not hardcoded, and that's not the actual value when used in production(it's specified a few lines below at line 32). I think adding a common video format makes sense, e.g. when a user wants to demonstrate a bug or something within a issue.
