### ISSUE TITLE
404 appears when editing the file

### ISSUE THREAD

**Issue by 0INVEST1** [go-gitea/gitea#18178]
### Gitea Version

1.15.6

### Git Version

2.33.1

### Operating System

windows11

### How are you running Gitea?

1. git clone https://try.gitea.io/hang/tom.git
2. Copy .configure in the folder
3. Push code with git command
4. Files can be seen on the web
5. When editing the  " - 副本 (6).configure" file, an error was reported

### Database

MySQL

### Can you reproduce the bug on the Gitea demo site?

Yes

### Description

1. git clone https://try.gitea.io/hang/tom.git
2. Copy .configure in the folder
![image](https://user-images.githubusercontent.com/44969381/148038322-52039746-227f-4ddc-9f8f-ce4c4bb411f4.png)
3. Push code with git command
4. Files can be seen on the web
![image](https://user-images.githubusercontent.com/44969381/148039184-657b910f-06c0-4c5d-bf4f-9e4b4a8fd498.png)
5. When editing the  " - 副本 (6).configure" file, an error was reported

I think it is because there is a blank number in front of the file

**Comment by lunny** [comment]
duplicated with #18176
