### ISSUE TITLE
Review form overflows in height

### ISSUE THREAD

**Issue by Gusted** [go-gitea/gitea#18183]
### Gitea Version

https://github.com/go-gitea/gitea/commit/d228d346c4d719cc0c0725ff1409eb97f0ac3109

### Operating System

Arch Linux

### Browser Version

Firefox 97.0a1 

### Can you reproduce the bug on the Gitea demo site?

Yes

### Description

See: https://try.gitea.io/Gusted/Test-repo/pulls/1/files -> Click on Review button.

I'm not comfortable enough with CSS to fix this one myself, nor sure how it should be "wrapped". 

### Screenshots

![image](https://user-images.githubusercontent.com/25481501/148110686-416cbf04-69a4-4d14-be6e-af3acb56bee8.png)

**Comment by zeripath** [comment]
I think the review box is too big and there's probably too much space in the dropzone.

**Comment by wxiaoguang** [comment]
The EasyMDE has a property `minHeight`: Sets the minimum height for the composition area, before it starts auto-growing. Should be a string containing a valid CSS value like "500px". Defaults to "300px".

I will try to set it to 150px to see if it works.
