### ISSUE TITLE
Dashboard shows no repository overview due to API query returning 403 Forbidden

### ISSUE THREAD

**Issue by aeveris** [go-gitea/gitea#18181]
### Gitea Version

1.15.8

### Git Version

2.34.1

### Operating System

Arch Linux

### How are you running Gitea?

Installed via the [community gitea package](https://archlinux.org/packages/community/x86_64/gitea/) and run using systemd.

### Database

MySQL

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/aeveris/315ab6efd8441b7992fce87dd295b526

### Description

Since the update to 1.15.8 the repositories overview on the dashboard is empty as can be seen in the attached screenshot. Downgrading to 1.15.7 resolves the issue. The log shows that when accessing the API to query the repos, status code 403 is returned. Performing the query directly in the browser gives `{"message":"Only signed in user is allowed to call APIs."}` in addition to the 403.

### Screenshots

![Screenshot 2022-01-04 at 13-52-45 Gitea](https://user-images.githubusercontent.com/6649296/148066439-6684fcb9-90ef-4e6d-8323-e408d8c1788d.png)

**Comment by lunny** [comment]
Have you tried v1.15.9 ?

**Comment by aeveris** [comment]
Ah yes, should have tried that before. Using v1.15.9 solves this.
