### ISSUE TITLE
Tree view in Pull Requests, similar to GitLab/GitHub/Azure DevOps

### ISSUE THREAD

**Issue by nunoperalta** [go-gitea/gitea#18192]
### Feature Description

The current way Gitea shows the file changes on a Pull Request (whether in Preview/Simulation or when the PR is created), to me feels disorganized and hard to review, as it shows ALL files in the same page.
For big PRs, this gets really messy/hard.

I actually feel very comfortable reviewing PRs using Azure DevOps, as they show a tree of the files changed (organized by affected folders), so that we can review one by one, by clicking on the file we want to review, and it will show the whole file on the right side, with the changes.

https://docs.microsoft.com/en-us/azure/devops/repos/git/review-pull-requests?view=azure-devops&tabs=browser

### Screenshots

![image-12](https://user-images.githubusercontent.com/487079/148311105-55ed0cb2-b85d-4e1f-9e9d-ea4434386ed8.png)

![image-13](https://user-images.githubusercontent.com/487079/148311117-05e3ed95-b61b-427a-82fe-9c8d29884409.png)

--

![sshot-2022-01-06-00-46-37-1](https://user-images.githubusercontent.com/487079/148311075-2902e704-a341-4427-af5d-1b9080f2d54b.jpg)

![pull-request-all-changes-dropdown](https://user-images.githubusercontent.com/487079/148311161-01df2de7-602f-4d8d-940c-692cbf6cc9e3.png)

**Comment by lunny** [comment]
We have one, but in the top.

![image](https://user-images.githubusercontent.com/81045/148331504-e26397b6-72ea-4c03-acf4-9da75d79688e.png)

**Comment by 6543** [comment]
wasn't there a plugin out in the wild for github that also support gitea??

**Comment by wxiaoguang** [comment]
> We have one, but in the top.
> 

Does Gite has a tree view? I think the author means the left tree for file list, it's more friendly and easier to use.

**Comment by lunny** [comment]
> > We have one, but in the top.
> 
> Does Gite has a tree view? I think the author means the left tree for file list, it's more friendly and easier to use.

We have a file list on the top of the files view.

**Comment by nunoperalta** [comment]
> We have one, but in the top.
> 
> ![image](https://user-images.githubusercontent.com/81045/148331504-e26397b6-72ea-4c03-acf4-9da75d79688e.png)

Hey
Thanks for the reply.

I'm not sure I understand what you mean (or what your screenshot is showing).

There just seems to be plain text with the stats, and each box below has the name of the file.
But I don't find anywhere an organized Tree of files, which I can click to see that file individually.

Similar to using VS Code, opening a file from the File Explorer at the left side, and the contents appear on the right side.
But the Tree / File Explorer only contains the changed files,
and the left side would either contain a Split View or Unified View of differences.

**Comment by qm012** [comment]
expectation plus this need

**Comment by nunoperalta** [comment]
btw, GitHub is implementing that. It's available under "Feature preview", although I'm not seeing the new version yet (even if enabled).

But here's the image in the "Feature preview" area:

<img width="932" alt="152002241-026a1fb8-897c-4653-a64d-f4b328574ba0" src="https://user-images.githubusercontent.com/487079/156890028-a44fd92e-e787-429e-a84f-b450b83b735e.png">

**Comment by nunoperalta** [comment]
Ah -- it's appearing to me now!!

Here's an example for this PR: https://github.com/go-gitea/gitea/pull/19007/files

![sshot-2022-03-05-15-36-52-1](https://user-images.githubusercontent.com/487079/156890076-1ef767dc-00e4-453c-b4c8-71d59710753c.jpg)

![sshot-2022-03-05-15-37-29-1](https://user-images.githubusercontent.com/487079/156890086-b8216c15-5937-4030-9ea7-6a69fec5d967.jpg)

**Comment by lunny** [comment]
As a workaround, you can use some chrome extensions, i.e. git-master

**Comment by delvh** [comment]
I have a suggestion for the icons:
While I do find it useful to display icons showing whether the file was added, modified, or deleted; I do not like the wasted space by displaying the file icon.
The folder icon is alright, as you can then quickly skim through which tree items are folders.
However, while using this feature in GitHub already, I noticed that there is unused potential here:
Instead of knowing that it is a file, I would find it much more useful to display a read-only checkbox (so most likely two different checkbox icons, one checked and one unchecked) showing whether you have already viewed this file while reviewing.
Implementing this is of course only possible once you can actually mark files as viewed, so it would depend on #19007 to get merged.

But the base implementation does not depend on this suggestion.

**Comment by sebastiande** [comment]
> As a workaround, you can use some chrome extensions, i.e. git-master

I think git-master is always showing all files and not only the changed files of a pull request, so it does not help.

**Comment by denwwer** [comment]
Hi, is any updates about that?

**Comment by happyxhw** [comment]
+1

**Comment by sebastian-sauer** [comment]
I've tried to get a first file list on the left of the tree view.

fomantic will add support for a tree (hopefully) with the next 2.9 release - so for now this is (at least for me) a good step to have a file list on the left to easy navigate in a pr.

![image](https://user-images.githubusercontent.com/1135157/187743873-69a6a392-a318-4c74-bc92-3636f137de30.png)

**Comment by sebastian-sauer** [comment]
Please see the PR for an updated screenshot with a first non collapsible tree view of files.

**Comment by sebastian-sauer** [comment]
Now the tree has collapsible directories and a github like show / hide mechanism. 

Please see updated screenshots in PR.
