### ISSUE TITLE
Use more friendly error message when a repository can not be accessed

### ISSUE THREAD

**Issue by wxiaoguang** [go-gitea/gitea#18225]
Now, if users access an invalid repository (non-existing, renamed, etc), they would see:

```
$ git fetch
Gitea: Internal Server Error
Gitea: Internal Server Error
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

The `Internal Server Error` is quite misleading and there is a error level message in Gitea log: 

```
...ters/private/serv.go:114:ServCommand() [E] Unable to get repository owner: org-name/repo-name Error: user does not exist [uid: 0, name: org-name, keyid: 0]
```

Since such case is not an serious error, users should not see the `Internal Server Error` or the error level log messages.

**Comment by lunny** [comment]
We should say the repository is not exist or you have no access to this repository.
