### ISSUE TITLE
Error when navigating to an organisations Issue/Pull Request/Milestone page 

### ISSUE THREAD

**Issue by eeyrjmr** [go-gitea/gitea#18229]
### Gitea Version

1.16.0+dev-825-gaf9247392 

### Git Version

2.34

### Operating System

Windows

### How are you running Gitea?

Console/ service 

### Database

SQLite

### Can you reproduce the bug on the Gitea demo site?

No - only because unable to create organisations 

### Log Gist

https://gist.github.com/eeyrjmr/da0e4db660632599685d4019953ddb74

### Description

When you navigate to an organisations page and try to click on Issue/Pull Request/Milestone page you are presented with a 500 error

This does not happen with 1.15.x

steps to recreate

1) make an organization (eg test) 
2) navigate to the organization dashboard ( http://localhost:3000/org/test/dashboard)
3) click on issues ( http://localhost:3000/org/test/issues ) 

### Screenshots

![Annotation 2022-01-10 190315](https://user-images.githubusercontent.com/4564448/148823950-66bf18a2-e995-4618-8ab1-683dab178a56.png)

**Comment by lunny** [comment]
Could you give some logs? Or you can change run_mode to dev and the error will be displayed in the 500 page.

**Comment by eeyrjmr** [comment]
here is a log
Steps
1) fresh "install" of gitea - ie delete all directories
2) configure gitea
3) stop gitea
4) edit app.ini 
RUN_MODE = dev
log.LEVEL = debug
log.MODE = file
5) restart gitea
6) sign in
7) create new ORG = test 
8) click on issue ( http://localhost:3000/org/test/issues)
9) click on pull request ( http://localhost:3000/org/test/pulls)
10) click on milestones ( http://localhost:3000/org/test/milestones) 

![Annotation 2022-01-12 224246](https://user-images.githubusercontent.com/4564448/149235014-e306acd2-ab8d-41d6-aea5-161f9e0f439a.png)

![Annotation 2022-01-12 224450](https://user-images.githubusercontent.com/4564448/149235242-56d44aeb-3ac2-4221-be78-511dcc877e08.png)

**Comment by wxiaoguang** [comment]
It looks like a regression bug of 
* #16839
