### ISSUE TITLE
Synchronize push mirror on push

### ISSUE THREAD

**Issue by culmat** [go-gitea/gitea#18220]
### Feature Description

Allow a [push mirror](https://docs.gitea.io/en-us/repo-mirror/#pushing-to-a-remote-repository) to synchronize on the _push event_ like a [web hook](https://docs.gitea.io/en-us/webhooks/). 
Make this the default behavior?

see also #18175
this would also provide a work around for  #13539,  as it would allow to trigger github actions on a mirror timely.

**Comment by zeripath** [comment]
I think you're really asking for an API that would cause a push mirror to sync.

Now the issue here is who that API should be available and how often it can be called.

**Comment by kodermho** [comment]
Seems similar to #16579

**Comment by guiohm** [comment]
I'm coming from Bitbucket and I was using this plugin: https://github.com/ef-labs/stash-hook-mirror/wiki
It pushes without any delay and is very convenient.

**Comment by harryzcy** [comment]
> I think you're really asking for an API that would cause a push mirror to sync.
> 
> Now the issue here is who that API should be available and how often it can be called.

I think this feature request means Gitea sync the repo with the "push mirror" every time new commits are pushed to Gitea, rather than syncing on scheduled intervals. So it's not a public API.

**Comment by jotoho** [comment]
> I think this feature request means Gitea sync the repo with the "push mirror" every time new commits are pushed to Gitea, rather than syncing on scheduled intervals. So it's not a public API.

If this interpretation is correct, I suspect that this issue is a duplicate of my issue #16579.

**Comment by harryzcy** [comment]
I believe this issue is resolved as #19411 has been merged
