### ISSUE TITLE
Closing an issue which has open dependencies does not show any error

### ISSUE THREAD

**Issue by fnetX** [go-gitea/gitea#18223]
### Gitea Version

1.16.0+dev-819-g3a0dee01e

### How are you running Gitea?

try.gitea.io + 1.15.9 on https://Codeberg.org

### Database

MySQL

### Can you reproduce the bug on the Gitea demo site?

Yes

### Description

https://try.gitea.io/fnetx/dependencytesting/issues/2

If an issue depends on another one which is not closed, trying to close the issue with dependencies fails but does not show any helpful error in the UI. This might be confusing to users, they might either miss the issue wasn't closed, or wonder why it cannot be closed when they don't notice the dependencies.

**Comment by zeripath** [comment]
This is a regression due to #17643 - we should be handling the dependency error in the callers.
