### ISSUE TITLE
Change the edit title button text to say "Change title" instead of "Edit"

### ISSUE THREAD

**Issue by ArthaTi** [go-gitea/gitea#18230]
### Feature Description

![image](https://user-images.githubusercontent.com/28842854/148833137-7f869953-81ef-46be-a699-65225b520acb.png)

A very minor issue, but the intention of the button is not very clear until you press it. What will it edit? Some issue settings? Ticket content? Status? It's slightly annoying, I never get to remember what the button is actually for.

I think it'd be a lot better to have it say "Change title" instead. I think it's descriptive enough.

**Comment by jolheiser** [comment]
This can also be used to change the base and HEAD of a PR, so `Change title` isn't entirely accurate.

**Comment by ArthaTi** [comment]
@jolheiser Hm, I didn't know! :thinking:

**Comment by ArthaTi** [comment]
> GitHub also call it `Edit`, it only edits the title.
> 
> <img alt="image" width="845" src="https://user-images.githubusercontent.com/2114189/148974378-218ae744-4dc8-4f14-ac7e-6f89e2424b62.png">

it annoyed me on github as well :sweat_smile: But I see it's not exactly as simple as I thought anyway. Heh
