### ISSUE TITLE
Transition steps from rootful to rootless image misses some changes

### ISSUE THREAD

**Issue by MPeti1** [go-gitea/gitea#18243]
### Gitea Version

v1.15.5

### Operating System

Raspbian Buster

### How are you running Gitea?

Self building from `Docker.rootless` for ARMv7

### Database

MySQL

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/MPeti1/8e27b3d8a3b402a3c85c27bc471c6f2c

### Description

Recenetly I migrated from the rootful Docker image to the rootless one, following the steps listed [here](https://docs.gitea.io/en-us/install-with-docker-rootless/#upgrading-from-standard-image) in the "Upgrading from standard image" section.

I also described my steps in an [other issue's comment](https://github.com/go-gitea/gitea/issues/16038#issuecomment-954920563).

Since the migration, I noticed that in repositories that were made before the migration, it's not possible to make new Wiki pages.
The logs reveal that this is because there are hook scripts in the Wiki repositories that would execute an other script in the "installation" directory, and I haven't edited these hook scripts to use the new, correct path for the scripts.

The contents of the hook file mentioned in the log:
```
#!/usr/bin/env bash
/app/gitea/gitea hook --config=/data/gitea/conf/app.ini pre-receive
```

The main part of this issue is about discussing a solution to this situation, and updating the documentation regarding the steps needed for transitioning between the 2 versions accordingly. There should be a new entry for editing files that contain old, broken paths.
I'm afraid I cannot implement a complete fix because I'm not familiar enough with the codebase (or with Go) to know which files might include such paths.

I also recommend considering to not use absolute paths for such script executions, but instead use an other way that is more resilient to path changes. One such way could be editing the PATH environment variable to include the directories that contain such scripts. There might be better options, though, and also this might cause problems for the users/admins who do not run Gitea from a container environment or a dedicated system.

**Comment by MPeti1** [comment]
Repositories that were made after the transition have this content in their `gitea` named `pre-receive` hook script.
```
#!/usr/bin/env bash
/usr/local/bin/gitea hook --config=/etc/gitea/app.ini pre-receive
```

It would probably be enough if I was going through all the old repositories and changing the `gitea` command's path in their hook scripts, but it would be good to know if there are any more files that should receive this treatment.

Also, this might be suitable as a new `gitea doctor` script.

**Comment by zeripath** [comment]
> Since the migration, I noticed that in repositories that were made before the migration, it's not possible to make new Wiki pages. The logs reveal that this is because there are hook scripts in the Wiki repositories that would execute an other script in the "installation" directory, and I haven't edited these hook scripts to use the new, correct path for the scripts.

These paths will be autoupdated on startup in 1.16.0 but in 1.15.x you can simply click the button labelled:

```
Resynchronize pre-receive, update and post-receive hooks of all repositories.
```

on the administration dashboard.

> I also recommend considering to not use absolute paths for such script executions, but instead use an other way that is more resilient to path changes. One such way could be editing the PATH environment variable to include the directories that contain such scripts. There might be better options, though, and also this might cause problems for the users/admins who do not run Gitea from a container environment or a dedicated system.

The paths have to be absolute.

**Comment by MPeti1** [comment]
Oh there is such a function already!

> The paths have to be absolute.

If you have planned with this happening then it's probably ok.

**Comment by MPeti1** [comment]
Problem fixed by mentioned maintenance function.
