### ISSUE TITLE
Could not remove config section

### ISSUE THREAD

**Issue by yuyuanshifu** [go-gitea/gitea#18246]
### Gitea Version

v1.11.4 

### How are you running Gitea?

built gitea by myself, and running gitea from systemd.

### Database

PostgreSQL

### Can you reproduce the bug on the Gitea demo site?

No

### Description

I found some error log shown below.
And in some repos I found many remote info in the config file("config") and many empty file in "refs/remotes".
And it takes long time to open these repos html in the web, I think it's related with too many remote files in "refs/remotes".
I want to know why this happened.

### Screenshots

error log:
![image](https://user-images.githubusercontent.com/7686122/149085441-d0be4708-c10f-4a18-b76d-1f3998e38cff.png)
code:
![image](https://user-images.githubusercontent.com/7686122/149085727-03b474b1-346e-45e1-8bfb-de4dfbcd913e.png)

**Comment by wxiaoguang** [comment]
I have some guess about this problem.

Git needs to lock the file `config` when updating remote config.

If the file is locked by other Git processes when `RemoveRemote`, the removal will fail.

If it is the case, it could be fixed by: 

1. Generate our internal remote name like `_tmp_{timestamp}`
2. When `defer`, remove all  `_tmp_{timestamp}` remotes. Even if some removals fail, then there will be a new removal to clean the temp remotes.

**Comment by yuyuanshifu** [comment]
> I have some guess about this problem.
> 
> Git needs to lock the file `config` when updating remote config.
> 
> If the file is locked by other Git processes when `RemoveRemote`, the removal will fail.
> 
> If it is the case, it could be fixed by:
> 
> 1. Generate our internal remote name like `_tmp_{timestamp}`
> 2. When `defer`, remove all  `_tmp_{timestamp}` remotes. Even if some removals fail, then there will be a new removal to clean the temp remotes.

Maybe it is this case, but I can not reproduce this problem.
I found something different: the right of config file. Is it the reason?
![image](https://user-images.githubusercontent.com/7686122/149090362-f0f9374a-4380-4537-bd5a-f50f421f8c89.png)

**Comment by zeripath** [comment]
@wxiaoguang removing all tmp remotes at the time of defer would break any remotes that were in use. 

We can't even use a timestamp to say that we think we should be removing all older remotes as we cannot guarantee that any of those are finished.

For races like this we probably have to wait to try again. Either that or push them on to some stack so that they can be removed later.

It's for this reason that I generally tended to create temporary repos even for simple pushing etc. We don't really want to be adding any temporary remotes to the main repository.

So I guess the question is: Is this really still happening on 1.15.x? 1.11.x is quite old now.

**Comment by wxiaoguang** [comment]
> removing all tmp remotes at the time of defer would break any remotes that were in use.

Hmm, I was thinking that there is a timestamp, `_tmp_{timestamp}`, we can just remove some very old remotes, eg: 1 hour before (nothing should run that long)

**Comment by yuyuanshifu** [comment]
> @wxiaoguang removing all tmp remotes at the time of defer would break any remotes that were in use.
> 
> We can't even use a timestamp to say that we think we should be removing all older remotes as we cannot guarantee that any of those are finished.
> 
> For races like this we probably have to wait to try again. Either that or push them on to some stack so that they can be removed later.
> 
> It's for this reason that I generally tended to create temporary repos even for simple pushing etc. We don't really want to be adding any temporary remotes to the main repository.
> 
> So I guess the question is: Is this really still happening on 1.15.x? 1.11.x is quite old now.

>We modified many code on 1.11.4, so we can not upgrade the version right now.

**Comment by wxiaoguang** [comment]
> We modified many code on 1.11.4, so we can not upgrade the version right now.

I see, then you could try to patch to remove the out-dated dangling remotes.

**Comment by yuyuanshifu** [comment]
> > We modified many code on 1.11.4, so we can not upgrade the version right now.
> 
> I see, then you could try to patch to remove the out-dated dangling remotes.

OK. But the remote file is increasing. I want to change the right of config now.

**Comment by zeripath** [comment]
Please could you check and ensure that there isn't a dangling lockfile for that config file?

I think it's .config.lock but it might simply be config.lock.

>We modified many code on 1.11.4, so we can not upgrade the version right now.

Then your only answer is to add a loop to the above code:

```go
		defer func() {
			for i := 0; i < 5; i++ {
				if err := repo.RemoveRemote(tmpRemote); err != nil {
					logger.Error("GetPullRequestInfo: RemoveRemote: %v", err)
					time.Sleep(1 * time.Second)
				} else {
					return
				}
			}
		}()
```

Something like that and reformatted to be more idiomatic.

**Comment by wxiaoguang** [comment]
(ps: if there is a dangling config.lock, the `AddRemote` should fail first, indeed I have no idea about this problem 😂)

**Comment by yuyuanshifu** [comment]
> ## As this is a problem that relates to git it would also be extremely helpful to know your git version.
> But otherwise, please could you ensure that there isn't a dangling lockfile for that config file?
> 
> I think it's .config.lock but it might simply be config.lock.
> 
> If there is one then that's the real cause of this problem and nothing else will fix this.
> 
> > We modified many code on 1.11.4, so we can not upgrade the version right now.
> 
> Then your only answer is to add a loop to the above code:
> 
> ```go
> 		defer func() {
> 			for i := 0; i < 5; i++ {
> 				if err := repo.RemoveRemote(tmpRemote); err != nil {
> 					logger.Error("GetPullRequestInfo: RemoveRemote: %v", err)
> 					time.Sleep(1 * time.Second)
> 				} else {
> 					return
> 				}
> 			}
> 		}()
> ```
> 
> Something like that and reformatted to be more idiomatic.
> 
> I'll try to push up a PR to Gitea main that does the same - although it would be better if we could completely avoid doing this kind of remote creation rubbish completely.

There is no .config.lock or config.lock. I will try the method you provided, thx.
Would gitea clean the remote file automatically?

**Comment by zeripath** [comment]
> Would gitea clean the remote file automatically?

That is precisely what the defer is trying to do but is failing.

The code I've suggested above suggests changing the defer to retry cleaning the remote a number of times - delaying further and further each time. It's not ideal by any means - realistically we should async further deletions with a goroutine and try to avoid adding remotes to the gitea repository directly.

What version of git are you using?

**Comment by yuyuanshifu** [comment]
> > Would gitea clean the remote file automatically?
> 
> That is precisely what the defer is trying to do but is failing.
> 
> The code I've suggested above suggests changing the defer to retry cleaning the remote a number of times - delaying further and further each time. It's not ideal by any means - realistically we should async further deletions with a goroutine and try to avoid adding remotes to the gitea repository directly.
> 
> What version of git are you using?

The git version is 2.7.4, it is too old. I will upgrade it.

**Comment by yuyuanshifu** [comment]
> > > Would gitea clean the remote file automatically?
> > 
> > 
> > That is precisely what the defer is trying to do but is failing.
> > The code I've suggested above suggests changing the defer to retry cleaning the remote a number of times - delaying further and further each time. It's not ideal by any means - realistically we should async further deletions with a goroutine and try to avoid adding remotes to the gitea repository directly.
> > What version of git are you using?
> 
> The git version is 2.7.4, it is too old. I will upgrade it.

After upgrading my git version to 2.34.1, I hadn't found the error any more.
