### ISSUE TITLE
Check file integrity on git lfs push/pull

### ISSUE THREAD

**Issue by amichuda** [go-gitea/gitea#18258]
### Feature Description

Sorry if this is already possible, but I couldnt find anything in the issues. Is there some way (or a tutorial?) on how to check for the integrity of a file that is pushed or pulled through LFS?

I ask because I have my instance running on a raspberry pi and it would be nice to know that the data doesn't get corrupted along the way.

**Comment by zeripath** [comment]
Lfs should be doing that automatically.
