### ISSUE TITLE
500 error when default banch doesn't exist on owner/repo/branches page

### ISSUE THREAD

**Issue by wxiaoguang** [go-gitea/gitea#18265]
Gitea version: 1.15.9

```
Jan 13 05:25:12 my-host gitea[10979]: 2022/01/13 05:25:12 Started GET /testuser/pandas/branches for 127.0.0.1:48032
Jan 13 05:25:12 my-host gitea[10979]: 2022/01/13 05:25:12 ...s/web/repo/branch.go:168:loadBranches() [E] loadBranches: get default branch: branch does not exist [name: master]
Jan 13 05:25:12 my-host gitea[10979]: 2022/01/13 05:25:12 ...s/web/repo/branch.go:169:loadBranches() [E] GetDefaultBranch: branch does not exist [name: master]
Jan 13 05:25:12 my-host gitea[10979]: 2022/01/13 05:25:12 Completed GET /testuser/pandas/branches 500 Internal Server Error in 110.488967ms
Jan 13 05:25:12 my-host gitea[10979]: 2022/01/13 05:25:12 Started GET /assets/img/500.png for 127.0.0.1:48034
```

**Comment by lunny** [comment]
Is there any branch in this repository?

**Comment by tim-kong** [comment]
> 

Yes, but the original repository does not contain a 'master' branch ( e.g., https://github.com/pandas-dev/pandas )

**Comment by zeripath** [comment]
this is I presume related to an adopted repository?

**Comment by wxiaoguang** [comment]
@tim-kong Can you help to confirm the problem? How the `/testuser/pandas` comes, was it adopted (imported from Gitea repository directory directly) before?

**Comment by tim-kong** [comment]
> 

OK. Login as _testuser_ , and just mirror the Pandas repository ('https://github.com/pandas-dev/pandas') using Gitea web page (http://example.com/repo/migrate). Don't need to do anything. And when accessing http://example.com/testuser/pandas/branches you well see 500 error.

Thanks.

**Comment by somera** [comment]
> > 
> 
> OK. Login as _testuser_ , and just mirror the Pandas repository ('https://github.com/pandas-dev/pandas') using Gitea web page (http://example.com/repo/migrate). Don't need to do anything. And when accessing http://example.com/testuser/pandas/branches you well see 500 error.
> 
> Thanks.

Works for me in Gitea 1.15.10. It need some seconds, but it works.

My URL: http://nuc-mini-celeron:3000/pandas-dev/pandas/branches

`Powered by Gitea Version: 1.15.10 Seite: 4904ms Template: 26ms`

**Comment by zeripath** [comment]
I can't reproduce this on main/1.16.0

**Comment by zeripath** [comment]
Can anyone reproduce this on 1.16?

**Comment by wxiaoguang** [comment]
I can trigger the bug manually in 1.16:

1. Prepare a normal git repository
2. Go to database, change the `repository`.`default_branch` to a non-existing one
3. Visit `/owner/repo/branches`
4. Then we get the 500 error

I can imagine a real case: if a user force-pushes a git repository with a different default branch name, they would also trigger this bug.

Maybe the better behavior is getting rid of the 500 page (internal error should be something serious, but not this case)

**Comment by tim-kong** [comment]
I update my gitea version to 1.15.10, and cannot trigger the bug.

**Comment by wxiaoguang** [comment]
> I update my gitea version to 1.15.10, and cannot trigger the bug.

Actually, 1.15.10 only contains some small fixes, and should not be related to this bug. I suspect you did something or Gitea did something, then the `default_branch` gets a correct value.

**Comment by zeripath** [comment]
> I can trigger the bug manually in 1.16:
> 
> 1. Prepare a normal git repository
> 2. Go to database, change the `repository`.`default_branch` to a non-existing one
> 3. Visit `/owner/repo/branches`
> 4. Then we get the 500 error
> 
> I can imagine a real case: if a user changes a git repository with a different default branch name (eg: changes the git repository on the server), they would also trigger this bug. I am not sure whether force-push would also trigger such bug.
> 
> Maybe the better behavior is getting rid of the 500 page (internal error should be something serious, but not this case)

Weirdly I wasn't able to do this on pandas.

**Comment by tim-kong** [comment]
https://github.com/pandas-dev/pandas/commit/50ac4981e0b2dca5fc0c353ddcf3b900925bce9b

It is probably the root cause.... Pandas has recently replace 'master' with 'main', just several days ago.

**Comment by zeripath** [comment]
I've put a PR in to handle this but we might not necessarily backport it.
