### ISSUE TITLE
add option to deactivate `Update branch` button

### ISSUE THREAD

**Issue by JHenneberg** [go-gitea/gitea#18268]
### Feature Description

Because it is not possible by now to set the update strategy for the `update branch` button it would be quite usefull to be able to deactivate it completly to avoid using it with a not intended strategy.

Of course the best solution would be too define the update strategy.

**Comment by Ulrik-dk** [comment]
`update branch` is very ambiguous until you try, and then find out that you are merging master into your feature branch.

Would be nice to be able to rebase on master.

**Comment by 6543** [comment]
You can rebase if you want too

**Comment by 6543** [comment]
What version do you use?!?

**Comment by 6543** [comment]
... Of course the best solution would be too define the update strategy. ...

Can be done closing

**Comment by Ulrik-dk** [comment]
@6543 I can see that I am using 1.15.10, and that the latest is 1.17.2. That would explain it.

**Comment by 6543** [comment]
@Ulrik-dk keep in mind of breaking changes, they are written in changelogs for v1.16.0 and v1.17.0 ... please upgrade asap as there are known sec-issues
