### ISSUE TITLE
Wrapping long lines in code views

### ISSUE THREAD

**Issue by silverwind** [go-gitea/gitea#1827]
Currently, Gitea does not wrap long lines of code, making it harder to look at code and diffs that contains lines that extend beyond the screen width.

Is there a general interest in having long lines automatically wrapped? It's a simple CSS tweak (similar to what I've done [here](https://github.com/StylishThemes/GitHub-code-wrap/blob/master/github-code-wrap.css) for GitHub):

Before:

<img width="1154" src="https://cloud.githubusercontent.com/assets/115237/26529488/dda99758-43c0-11e7-96d4-2142d6dca7c1.png">

After:

<img width="1152" src="https://cloud.githubusercontent.com/assets/115237/26529491/f0d8229a-43c0-11e7-86ff-decec95fec61.png">

This might not work too well on small screens, where I think it might be better to not wrap those lines (horizontal scrolling is easier on touch).

**Comment by lunny** [comment]
@silverwind please send a PR.

**Comment by appleboy** [comment]
fixed by https://github.com/go-gitea/gitea/pull/1845

**Comment by silverwind** [comment]
Actually, this one isn't fixed yet. Can you reopen please?

**Comment by mlthlschr** [comment]
would be great if this could be enabled in normal code views as well (maybe via toggle or config setting). currently working with `.Rmd` files which contain quite long lines sometimes.
