### ISSUE TITLE
False-formatted login form

### ISSUE THREAD

**Issue by iusgit** [go-gitea/gitea#18304]
### Gitea Version

1.15.10

### Operating System

Ubuntu 20.04

### How are you running Gitea?

Command-line

### Can you reproduce the bug on the Gitea demo site?

Yes

### Description

The login form has wrong alignments for username and password. See attachment from try.gitea

### Screenshots

<img width="1111" alt="Bildschirmfoto 2022-01-17 um 10 27 10" src="https://user-images.githubusercontent.com/91615683/149743405-910072a4-66d4-4584-93d1-ee97bf384099.png">

**Comment by wxiaoguang** [comment]
The translated text is very long. Maybe you can do a quick fix in crowdin https://crowdin.com/translate/gitea/ to use a shorter text.

**Comment by noerw** [comment]
@wxiaoguang this is not the issue, for me it renders fine on all resolutions.
@iusgit what is that icon next to the email textfield? if that's from an extension, does it render correctly when disabling that extension?

**Comment by wxiaoguang** [comment]
Oh yes, I can see the HTML layout is changed by a unknown element.

![image](https://user-images.githubusercontent.com/2114189/149750257-6cd11d97-8810-4467-98ec-adabc39bcb9c.png)

**Comment by iusgit** [comment]
Good catch!

That is the icon of the new Firefox Relay addon and disabling it solves the misformatting.

Haven't seen that behavior with other icons e.g. from Password Manager which are placed there aswell.

So from my side it is "solved".

Thak you!
