### ISSUE TITLE
'Commits since last release' label broken

### ISSUE THREAD

**Issue by OCram85** [go-gitea/gitea#18307]
### Gitea Version

1.5.10

### Git Version

2.30.2

### Operating System

SLES 15 SP2

### How are you running Gitea?

[2x haproxy / keepalived nodes] --- (ponting to  traefik reverse proxy) ---> [ multiple docker swarm manager] ---- running ---> [ Single gitea container ]

### Database

MySQL

### Can you reproduce the bug on the Gitea demo site?

No

### Description

The link label on the repo/release page seems to be broken The counter `0 commits `

Can't reproduce it 100% on https://gitea.com/xorm/xorm/releases because #18226 isn't fixed on this instance.

The commits were always done via the same gitea workflow -> [Gitea PR] -> [Review] -> [Squash Commit / Merge to master].

### Screenshots

![image](https://user-images.githubusercontent.com/13993700/149776576-a3cfe180-4e71-46e0-870c-96471bed1fc9.png)

![image](https://user-images.githubusercontent.com/13993700/149776753-5b0a5f89-f4e0-43d3-bf79-946c98fa628e.png)

**Comment by zeripath** [comment]
OK I think this is working on 1.16.0

![Screenshot from 2022-01-17 19-49-46](https://user-images.githubusercontent.com/1824502/149829672-d48b7a7d-41ad-4533-8c9e-7464ad5a8464.png)

But what's really interesting is that if you look at your first picture the 1.0.3 release looks correct - except the DefaultBranch is incorrect.

**Comment by RealStickman** [comment]
Broken again in 1.17.2. I've made 1 commit since this release.  
![grafik](https://user-images.githubusercontent.com/61015582/189915015-6503244e-be14-4982-abfa-304a9f3f3781.png)

Clicking the link does lead to the correct diff with 1 commit.  
![grafik](https://user-images.githubusercontent.com/61015582/189915463-b2525acd-f584-41be-9be4-d181109aae9d.png)

**Comment by wxiaoguang** [comment]
Come across this one.

Incorrect milestone, and .... whether it has been fixed?
