### ISSUE TITLE
Changing PR Comment Resolved State Disables Further Changes

### ISSUE THREAD

**Issue by delvh** [go-gitea/gitea#18315]
### Gitea Version

1.16.0+dev-863-g076cead40

### Operating System

Kubuntu 20.04

### Browser Version

Firefox 96.0

### Can you reproduce the bug on the Gitea demo site?

Yes

### Description

When I change a PR comment in terms of it being `resolved`, I cannot (un-)resolve it any further without reloading the page.
What I mean by that:
Resolve a comment, and then try to unresolve it. It won't work.
The same is true when unresolving a resolved comment and then trying to re-resolve it.

The corresponding button seems to now be nothing more than a glorified label, especially regarding that the button text will be selected when pressing it.

### Screenshots

Not possible as simply _nothing_ happens.

**Comment by wxiaoguang** [comment]
Good catch, I am working on it, it will be fixed soon.
