### ISSUE TITLE
Copy git clone address not working 

### ISSUE THREAD

**Issue by rcdevice** [go-gitea/gitea#18318]
I'm new guy ,only using Gitea for a week, Gitea is powerful  and easy ,but I have a trouble , That I can't COPY git clone links to  to the clipboard automatically  ,every time ,I must press CTRL + C to complete it(Press ⌘-C or Ctrl-C to copy.), Where did I go wrong?  need some one to help me! I use the same browser with Gogs, and copying works fine
![Snap1](https://user-images.githubusercontent.com/30013680/149865354-4a2b1f20-09c0-4315-bd80-043b22879b10.jpg)

**Comment by rcdevice** [comment]
OS: windows 10 home  ,Chinese 
browser：  Firefox  and Chrome  both not working

**Comment by lunny** [comment]
Which version did you use?

**Comment by rcdevice** [comment]
Gitea Version: 1.15.9

**Comment by wxiaoguang** [comment]
It doesn't work for "HTTP" site in 1.15

Please use 1.16 or use "HTTPS"

**Comment by rcdevice** [comment]
Thanks for faster reply， I will try it.  
Have nice day!
