### ISSUE TITLE
Display assigned user in Kanban board

### ISSUE THREAD

**Issue by bcallaghan-et** [go-gitea/gitea#18326]
### Feature Description

The Kanban boards within Gitea should display the assigned user on each card. If an issue is unassigned, then this spot should be left blank or perhaps have some indicator that the issue is unassigned. Currently, the card displays the author of the issue, but not the developer working on the issue. My team uses Kanban boards as a task tracker, so it is much more useful to know who is working on the task, not who asked for the task to be done. Trello supports this feature by displaying the avatar (or initials) of the assigned user in the bottom-right corner of the card.

**Comment by zeripath** [comment]
Hmm... I think it would be useful to see a mock-up of this.

---

```patch
diff --git a/templates/repo/projects/view.tmpl b/templates/repo/projects/view.tmpl
index 1db52a3d7..c53b03662 100644
--- a/templates/repo/projects/view.tmpl
+++ b/templates/repo/projects/view.tmpl
@@ -228,6 +228,18 @@
 								</a>
 							</div>
 							{{- end }}
+							{{- if .Assignees}}
+							<div class="meta my-2">
+								<div class="text light grey">{{$.i18n.Tr "repo.issues.new.assignees"}}
+								<ul>
+									{{- range .Assignees}}
+										<li><a class="ui assignee tooltip tdn" href="{{.HomeLink}}" data-content="{{.GetDisplayName}}" data-position="left center">
+											{{avatar .}} {{.GetDisplayName}}
+										</a></li>
+									{{- end}}
+								</ul></div>
+							</div>
+							{{- end}}
 						</div>
 						{{if .Labels}}
 							<div class="extra content labels-list p-0 pt-2">

```

![Screenshot from 2022-01-18 23-35-37](https://user-images.githubusercontent.com/1824502/150035846-bebb9b34-4758-421a-8c31-6d598ccd06c1.png)

which doesn't quite work I think.

**Comment by wxiaoguang** [comment]
IIRC there was an old PR for this.

**Comment by wxiaoguang** [comment]
This one: https://github.com/go-gitea/gitea/pull/15232

**Comment by bcallaghan-et** [comment]
That PR looks exactly like what I want. I'll close this issue as a duplicate of #15026
