### ISSUE TITLE
The messages for OAuth Authorize page are escaped incorrectly.

### ISSUE THREAD

**Issue by wxiaoguang** [go-gitea/gitea#18327]
Gitea: 1.16-dev

The messages for OAuth Authorize page are escaped incorrectly.

URL: https://the-gitea/login/oauth/authorize?....

![image](https://user-images.githubusercontent.com/2114189/150063584-ff89e15a-819b-4ba7-a1a1-43f1c0a7fccc.png)

**Comment by zeripath** [comment]
ugh these have been double escaped as a result of a mistake by me in #17551

PR incoming.

**Comment by wxiaoguang** [comment]
I have made a PR
