### ISSUE TITLE
Links in repo issues doesn't change automatically on web URL change.

### ISSUE THREAD

**Issue by CkovMk** [go-gitea/gitea#18322]
### Gitea Version

1.15.9

### How are you running Gitea?

Official docker image, arch=x86-64

### Database

MySQL

### Can you reproduce the bug on the Gitea demo site?

No

### Description

The Gitea instance is deployed in LAN and accessed via http://ip-address:port/ .
I Changed the host ip address from 192.168.8.21 to 10.25.5.21 (for instance), but links in repo issue page still remains the old address, which is apparently inaccessible. Change the ip address manually to new one results in a success though.

One more thing, I have some of the issues added to a project. Issue links in the project seems working normally.

**Comment by KN4CK3R** [comment]
Which "links in repo issue page" exactly?

**Comment by zeripath** [comment]
Have you changed your ROOT_URL setting?

**Comment by CkovMk** [comment]
An update: ROOT_URL setting has been updated and solved the problem. Thanks and sorry for the inconvenience.
ps: Need to update those values in docker ENV! urrrrrrrrrh.

**Comment by CkovMk** [comment]
An update: ROOT_URL setting has been updated and solved the problem. Thanks and sorry for the inconvenience.
ps: Need to update those values in docker ENV! urrrrrrrrrh.
