### ISSUE TITLE
Repository topics returning 403 on search and edit

### ISSUE THREAD

**Issue by almahmoud** [go-gitea/gitea#18337]
### Gitea Version

1.15.8

### Operating System

Kubernetes

### How are you running Gitea?

Used Gitea helm chart to deploy on a Kubernetes cluster

### Database

PostgreSQL

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

https://gist.github.com/almahmoud/e5068fbf41f2a3bea998234f8191140c

### Description

It seems that no user (even original admin) can list or add topics. I also was not able to add a repository topic on https://try.gitea.io/alexm-test/testtopics either. Gist above contains log from Gitea container and below is a screenshot of the errors in the browser console. Happy to help provide more info and/or test other things out as needed.

### Screenshots

Console log

![image](https://user-images.githubusercontent.com/14061824/150231972-c08b853e-15bd-4ab4-bd47-338d545c801b.png)

**Comment by zeripath** [comment]
Please read: https://docs.gitea.io/en-us/logging-configuration/#debugging-problems

The logs you have given us do not give us any information.

**Comment by almahmoud** [comment]
Thanks for the pointer, I'll change configuration and extract better logs. Sorry about not doing that from the beginning, I didn't pay much attention to the logs since it seemed reproducible on the public test instance, but I can definitely get better logs from our instance as well

**Comment by almahmoud** [comment]
Hopefully this will be more helpful: https://gist.github.com/almahmoud/e5068fbf41f2a3bea998234f8191140c ? Let me know if it isn't and/or if you'd want me to trace anything specific and/or get other logs

**Comment by zeripath** [comment]
Hmm not a particularly enlightening log. 

I guess it's going to be a case of walking through the code and replicating the issue.

**Comment by almahmoud** [comment]
Good news! I upgraded the version while changing the logging and it seems the issue is fixed in v 1.15.9. Sorry for the bother.
