### ISSUE TITLE
Hook still work after webhook is deactive

### ISSUE THREAD

**Issue by Zoranner** [go-gitea/gitea#18343]
### Gitea Version

1.15.9

### Git Version

2.34.1

### Operating System

centos

### How are you running Gitea?

Download from the github releases page and run through service deployment.

### Database

MySQL

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

![image](https://user-images.githubusercontent.com/20719726/150353076-0ccecdb9-bf24-49b1-b770-53b0987d5048.png)

**Comment by wxiaoguang** [comment]
It should have been fixed by
* https://github.com/go-gitea/gitea/pull/19234
