### ISSUE TITLE
webpack error related to uint8-to-base64 when building Gitea

### ISSUE THREAD

**Issue by bagasme** [go-gitea/gitea#18349]
### Gitea Version

commit 6c7084cbee1334c0e21118b5dbbd7368aff27ee8

### Git Version

2.34.1

### Operating System

OpenSUSE Tumbleweed

### How are you running Gitea?

Build from source on Ubuntu 20.04 (go 1.17.2, node v16.13.2 via nvm)

### Database

PostgreSQL

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/bagasme/def6f32065d04580802d79a0e1785c04

### Description

On my Ubuntu computer I tried to build Gitea from source. I expected that the build success. But it returned error in `webpack`, saying:

```
ERROR in ./web_src/js/features/user-auth-webauthn.js 1:0-49
Module not found: Error: Can't resolve 'uint8-to-base64' in '/home/bagas/repo/git/gitea/web_src/js/features'
resolve 'uint8-to-base64' in '/home/bagas/repo/git/gitea/web_src/js/features'
  Parsed request is a module
  using description file: /home/bagas/repo/git/gitea/package.json (relative path: ./web_src/js/features)
    Field 'browser' doesn't contain a valid alias configuration
...<snipped>
```

The last commit successfully built and deployed was commit 69a28299e.

### Screenshots

<not relevant>

**Comment by silverwind** [comment]
Does `node -p 'require("uint8-to-base64")'` work?

```
$ node -p 'require("uint8-to-base64")'
{ encode: [Function: encode], decode: [Function: decode] }

**Comment by bagasme** [comment]
> Does `node -p 'require("uint8-to-base64")'` work?
> 
> ```
> $ node -p 'require("uint8-to-base64")'
> { encode: [Function: encode], decode: [Function: decode] }
> ```
> 
> If not, does `node_modules/uint8-to-base64` exist?
@silverwind no, it returned `MODULE_NOT_FOUND` error:

```
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'uint8-to-base64'
Require stack:
- /home/bagas/repo/git/gitea/[eval]
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at [eval]:1:1
    at Script.runInThisContext (node:vm:129:12)
    at Object.runInThisContext (node:vm:305:38)
    at node:internal/process/execution:75:19
    at [eval]-wrapper:6:22
    at evalScript (node:internal/process/execution:74:60) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/bagas/repo/git/gitea/[eval]' ]
}
```

**Comment by silverwind** [comment]
Your `node_modules` folder is out of date but the mechanisms in the Makefile should lead to execution of `npm install --no-save` which apparently never happends. Does `make node_modules` fix it? Otherwise, you can just delete it which should reinstall them.
