### ISSUE TITLE
Plan of Gitea v1.17

### ISSUE THREAD

**Issue by zeripath** [go-gitea/gitea#18345]
Hi all Gitea contributors,

Gitea v1.16rc1 is now out! We have created the `release/v1.16` branch and tagged `v1.17.0-dev` opening up `main` for 1.17 development. As mentioned in our CONTRIBUTION, it will spend three or four months before feature freeze.

I'm aware now is the time for the regular planning thread. Please use it to discuss your own plans for the 1.17 development cycle.

**(Reminder, this thread is for things you PLAN TO DO YOURSELF, not things you want other people to do.)**

Thanks,
zeripath

**Comment by zeripath** [comment]
Previous planning threads:

* #16429
* #14477

**Comment by zeripath** [comment]
I guess I'll start with some of things I'd like to do:

## Context Propagation + "Process" management

This is a series of refactors that will cause the request context to be passed down in called functions. Doing this allows newly created child contexts to be scoped to the request context - enabling process hierarchies to work, better logging, easier db functions, easier permissions checking and scoping. The first steps of this process was in #17125 and the DBContext work.

* #17868 - means that all git contexts will now be scoped to the request context.
* [ ] - Do the same for the DB functions
* [ ] - pass context into log calls to allow these to print the process ID (or even get the logger from the ctx...)
* [ ] - add `gitea manager process` or create admin API for process management
* [ ] - Once we have context propagation complete we can actually consider dropping the global dependence on setting.AppURL and setting.AppSubURL and make Gitea be possible to be hydra-headed.

## Authentication/Authorization

We still need to continue work on the DB password authentication.

* [ ] - The DB password authentication things really need to be moved out user 
* [ ] - I'd like to make it possible to enforce 2fa
* [ ] - I want to consider if users want to use their sec key as their method of login without a password

Then there are OAuth scoping and tokens:

* [ ] - OAuth Tokens scopable to github like permissions
  * With the context propagation above permissions checks could actually be performed a bit more clearly.
* [ ] - Deprecate the old Token scheme

We also need to make it possible to force logout of sessions for the current user - useful additionally for admin.

* [ ] - Refactor sessions infrastructure to account for this.

## Dump/Restore

I think we should stop dumping to "SQL" - and instead dump to a SQLite db file. We should then be able to restore from this a lot easier!

## Federation

This work stream will be discussed elsewhere

## Misc
* #18064 - this allows admins to purge a user and all of their repositories
* #17902 
  * I think this work also shows the basics of how to approach resolve conflicts - but I'm not sure if I will get to this.
* #18335
* [ ] -  I think the notifications UI could do with some work. It currently just shows all of the notifications but I think we should really be able to make it searchable etc. The problem is when I will be able to get to this.

## Work with others
*  #18341 - Adds more deprecation notices to the settings
*  #17308 - Contains a significant refactor for Wrap that means instead of performing reflection at routing time these are precalculated

That's probably enough to be getting on with however, I'd like to list some potential refactors that I'd like to consider:

### Potential Refactors

* As mentioned above, context passing means we can consider "hydra" heading dropping the dependence on the global AppURL and instead get this set at the server level.
   - This would allow users to more easily mount gitea in two places and also reduce the problems from the ROOT_URL setting.
* Once we stop having global dependence on setting.AppURL we'll likely find that a lot of packages really only look at particular settings. If we implement configurable we can actually consider having packages do this themselves.
* I think we need to use more generation especially in the routers.
* I think we should either consider using the go-sdk in the (especially the API) integration tests or get swagger to generate an API.

**Comment by techknowlogick** [comment]
Placeholder for my plan, will edit this post as I have things to add.

Currently just maintenance tasks are on top of my head:

* Due to crowdin API deprecation, the cron task needs to be updated.
* With upcoming release of golang 1.18, we will need to build with that (update drone, docker, & xgo)

refactor:
* move some user columns to use user_settings table instead

features:
* labels for milestones

As mentioned above, federation tasks will be discussed elsewhere.

Also, general upkeep of our infra & coordination with sponsors

**Comment by silverwind** [comment]
- Start refactoring out jQuery with the help of https://github.com/dgraham/eslint-plugin-jquery

**Comment by lafriks** [comment]
* Finally finish priority labels
* Secret storage

**Comment by vwbusguy** [comment]
I would love to see these make the cut.  This is some low hanging fruit that's been around for a while that would be  a great quality of life improvement: https://github.com/go-gitea/gitea/issues/16429#issuecomment-919345943

Ref. 
WIP: wiki - page toc and directory support #7225
WIP: wiki - add toc to wiki pages and rendered md files #7182
TOC for Wiki Pages #822

**Comment by techknowlogick** [comment]
@vwbusguy please see note in original post:

> (Reminder, this thread is for things you PLAN TO DO YOURSELF, not things you want other people to do.)

**Comment by lunny** [comment]
- [ ] Finish #18165 and finally move the Gitea repository itself to https://gitea.com/gitea/gitea.git
- [ ] More refactors backend code (models, modules, services)
- [ ] #18147 
- [ ] #18177 
- [ ] #16052 
- [ ] Internal CI/CD which is similar as Github Actions

**Comment by KN4CK3R** [comment]
- [ ] Finish #16510
- [ ] Once the package registry is ready, finish the docker/container registry
- Work towards federation

**Comment by Gusted** [comment]
Bit late to the party.

- [ ] Get https://github.com/go-gitea/gitea/pull/17711 merged
- [ ] Do some more security stuff (~~un~~intentionally vague)
- [ ] Improve QoL of Gitea, with little quirks that other Git services have.

**Comment by richmahn** [comment]
Still in great need of a UI for conflict resolving #9014. I said last summer I would work on this...still seeking to find the time, hopefully for 1.17.

**Comment by delvh** [comment]
I'm currently working on #11730, should be ready for review in a few days.

**Comment by more-pepsi** [comment]
> * [ ]  Start refactoring out jQuery with the help of https://github.com/dgraham/eslint-plugin-jquery
> * [ ]  Finish removal of icon fonts
> * [ ]  Finish removal of all color values in CSS in favor of variables

I'm looking for some starter tasks if you want to pas some tasks on. I"m a JavaScript expert, but a little rusty with frameworks, its been years. So i'll just follow your lead.

**Comment by wxiaoguang** [comment]
There are some work for refactoring:
1. replace all `.data('xxx')` by `.attr('data-xxx')` for static HTML data attributes `data-xxx="..."`, it makes the developers easier to find the `data-xxx` usages. Dynamic `.data('yyy', val)` might be kept at the moment.
2. clean legacy / incorrect CSS styles. eg, the polluted `.ui .left`
