### ISSUE TITLE
[release signing] replace gitea signing key: impending key expiry on 2022-06-24

### ISSUE THREAD

**Issue by noerw** [go-gitea/gitea#18353]
The GPG key Gitea (as well as `tea`?) releases are signed with has limited lifetime:

```
pub   rsa4096 2018-06-24 [SC] [expires: 2022-06-24]
      7C9E68152594688862D62AF62D9AE806EC1592E2
uid           [ unknown] Teabot <teabot@gitea.io>
sub   rsa4096 2018-06-24 [E] [expires: 2022-06-24]
sub   rsa4096 2018-06-24 [S] [expires: 2022-06-24]
```

It probably makes sense to swap the signing key on a major release, being kind of a breaking change for users of the signed binaries.
I'm uncertain that 1.17 will be released by then, so we should probably do this right before releasing 1.16.
@go-gitea/owners if you don't agree, feel free to remove from 1.16 milestone :)

To my (limited) knowledge it's best practice to have a non-expiring key for signing binaries to avoid issues like this for consumers of the signatures. This non-expiring key may have sub-keys handed to individuals & CI with a (short-ish) expiration date.

**Comment by lunny** [comment]
I don't think a never expired GPG key is the best practice whatever it will be used in.

**Comment by zeripath** [comment]
It's fine to just update the expiry date and repush up the key

**Comment by noerw** [comment]
> A sub key with expiration date is not very different from the pub key with expiration?

The difference is that the key ID used by others does not need to be changed, when a subkey is changed.

> It's fine to just update the expiry date and republish the public key.

I just noticed that too, probably the best option

**Comment by Gusted** [comment]
> It's fine to just update the expiry date and republish the public key.

This, I think I might've set the wrong foot with noerw on the update.sh PR. It will become a problem with a new key will generated instead of the same key(with same key ID), as that will make it impossible to verify earlier builds as well to verify that the new key that was generated is trust worthy(people can be paranoid sometimes). Not sure if there is a secret internal owners document, otherwise it might be nice to mention that ;)

**Comment by zeripath** [comment]
Updating the expiry for a key does not change its ID.

**Comment by Gusted** [comment]
> Updating the expiry for a key does not change its ID.

Bad wording from me, I've updated my comment.

**Comment by zeripath** [comment]
I'm still confused by your comment. 

My GPG key 3CDE74631F13A748 originally was due to expire in 2018 - it has had its expiry updated twice since it was created. Each time I've updated its expiry I've pushed it to Github, keys.openpgp.net and Gitea.

**Comment by Gusted** [comment]
So:

1. If the case was that gitea was generating a whole new key and use that one for signing, it would be bad.
2. If the case was that gitea is updating the expiry and then push it to the key-servers, it's a ll fine.

**Comment by lunny** [comment]
The signing key has been updated twice since 2016. The ID will not be changed.

**Comment by Gusted** [comment]
I think in that case it can be closed, as I'm pretty sure the only main concern here was that the key ID shouldn't change between new key uploads.
