### ISSUE TITLE
Adding group claim name for admin and required does not show in gui

### ISSUE THREAD

**Issue by netcicd** [go-gitea/gitea#18388]
### Gitea Version

1.16.0-rc1

### Operating System

docker: gitea/gitea:1.16.0-rc1

### How are you running Gitea?

docker container as part of https://github.com/Devoteam/CICD-toolbox 

### Database

PostgreSQL

### Can you reproduce the bug on the Gitea demo site?

No

### Description

when running 
gitea admin auth update-oauth --id 1 --required-claim-name gitea-admin --admin-group gitea-admin
in the container, this does not show in the gui. Adding these fields in the gui gives 200 in the log, but no entry in the gui

### Screenshots

![Screenshot from 2022-01-24 16-04-53](https://user-images.githubusercontent.com/46484069/150808324-4d5520a3-c11a-47fe-a14a-2d248fe945b8.png)
secret in picture is randomly generated

**Comment by netcicd** [comment]
When set in the GUI, Additional scopes and Group claim name for administrators show up in the database. Required shows up when entered on CLI, not in GUI

**Comment by zeripath** [comment]
The rendering in your screenshots appears to be a little odd.  

Do you have old custom templates?

**Comment by netcicd** [comment]
> The rendering in your screenshots appears to be a little odd.
> 
> Do you have old custom templates?
Hi Zeripath,
No custom templates, just the container I downloaded from docker hub. I selected the relevant portions of the screens. Nothing
What I'll do is purge my docker images and rebuild.

**Comment by netcicd** [comment]
Hi Zeripath,
No custom templates, just the container I downloaded from docker hub. I selected the relevant portions of the screens. Nothing
What I'll do is purge my docker images and rebuild.
Nothing changed after rebuild in the images...

**Comment by zeripath** [comment]
OK the edit page template looks to have suffered a conflict merge at some point and it got broke. 

```patch
diff --git a/templates/admin/auth/edit.tmpl b/templates/admin/auth/edit.tmpl
index a9942354c..efa440ff3 100644
--- a/templates/admin/auth/edit.tmpl
+++ b/templates/admin/auth/edit.tmpl
@@ -286,6 +286,10 @@
 							<input id="skip_local_two_fa" name="skip_local_two_fa" type="checkbox" {{if $cfg.SkipLocalTwoFA}}checked{{end}}>
 							<p class="help">{{.i18n.Tr "admin.auths.skip_local_two_fa_helper"}}</p>
 						</div>
+					</div>
+					<div class="oauth2_use_custom_url inline field">
+						<div class="ui checkbox">
+							<label><strong>{{.i18n.Tr "admin.auths.oauth2_use_custom_url"}}</strong></label>
 							<input id="oauth2_use_custom_url" name="oauth2_use_custom_url" type="checkbox" {{if $cfg.CustomURLMapping}}checked{{end}}>
 						</div>
 					</div>

```

would fix the template.
