### ISSUE TITLE
mermaid markdown can not render after upgrading gitea from 1.14.x to 1.15.10

### ISSUE THREAD

**Issue by zhengmz** [go-gitea/gitea#18381]
### Gitea Version

docker images: gitea/gitea:1.15.10

### Operating System

CentOS7 for host os

### How are you running Gitea?

docker-compose

### Database

PostgreSQL

### Can you reproduce the bug on the Gitea demo site?

No

### Description

When a mermaid markdown is added to issue or README.md, it does not render as expected.
It can render normal in try.gitea.io.

BTW:  my gitea server upgraded from 1.4.x step by step.

### Screenshots

write in issue or README.md

![image](https://user-images.githubusercontent.com/3997518/150730322-ff1af855-6f3f-42e3-83c8-7e01ee546b07.png)

but cannot render

![image](https://user-images.githubusercontent.com/3997518/150730511-cdf0e4d1-d9e5-42ac-ba0d-46d22496a2c3.png)

**Comment by wxiaoguang** [comment]
Please provide logs, eg: is there any network failure? is there any JS error?

**Comment by zhengmz** [comment]
Web browser (Edge) console have:

![image](https://user-images.githubusercontent.com/3997518/150733399-93bfd6b9-854f-480c-98a2-cdef575054e8.png)

**Comment by wxiaoguang** [comment]
Could you try:

1. Use Private Windows or clean your browser cache (Ctrl+F5 for Windows browsers)?  (to make sure all files are correct)
2. Use 1.16? (if step 1 doesn't help, make sure whether the problem also happens in 1.16)

**Comment by zhengmz** [comment]
> Could you try:
> 
> 1. Use Private Window or clean your browser cache (Ctrl+F5 for Windows browsers)?  (to make sure all files are correct)
does not work.

> 2. Use 1.16? (if step 1 doesn't help, make sure whether the problem also happens in 1.16)
My current server is for product. I will try in a new docker container.

> 
> I just tried it on try.gitea.io (the frontend code is the same as 1.16): https://try.gitea.io/wxiaoguang/test/issues/1 , it works.

thank you.

**Comment by wxiaoguang** [comment]
I just tried 1.15.10 and can confirm this is a bug in 1.15.10 😭

**Comment by wxiaoguang** [comment]
Related to
* https://github.com/go-gitea/gitea/pull/18206

**Comment by zhengmz** [comment]
> I just tried 1.15.10 and can confirm this is a bug in 1.15.10 😭
> 
> There isn't important change in 1.15.10 (see the changelog), so you might use 1.15.9 instead, and then 1.16

thank, 1.15.9 work well.

**Comment by silverwind** [comment]
Will be fixed next release.
