### ISSUE TITLE
Cannot debug gitea in vscodium + default vscode-go 0.30.0 config

### ISSUE THREAD

**Issue by pboguslawski** [go-gitea/gitea#18394]
### Gitea Version

1.16

### How are you running Gitea?

Compilation from source.

### Can you reproduce the bug on the Gitea demo site?

No

### Description

When you try to compile gitea in vscodium with current vscode-go extension version 0.30.0 using instructions from

https://github.com/go-gitea/gitea/blob/main/contrib/ide/README.md

debug binary will be build in /tmp not in ${workspaceRoot} and page http://127.0.0.1:3000/ will display only

`Unable to find status/500 template`

and debug console will contain errors like

```
2022/01/24 19:02:18 ...ers/common/logger.go:21:1() [I] Started GET / for 127.0.0.1:34106
2022/01/24 19:02:18 ...s/context/context.go:206:HTML() [E] Render failed: html/template: "install" is undefined
2022/01/24 19:02:18 ...s/context/context.go:290:PlainTextBytes() [E] PlainTextBytes: Unable to find status/500 template
2022/01/24 19:02:18 ...ers/common/logger.go:30:1() [I] Completed GET / 500 Internal Server Error in 469.837µs
```
Problem is caused probably by new debugger mode used in vscode-go extension (dlv-dap).

Workaround that seems to work is to turn on legacy mode by adding

```
    "go.delveConfig": {
        "debugAdapter": "legacy",
    }
```

to settings.json.

**Comment by Gusted** [comment]
This seems to be a issue with the stable version of vscode-go, I don't encounter such issue with the preview version of vscode-go, Could you try [go nightly](https://marketplace.visualstudio.com/items?itemName=golang.go-nightly)?

**Comment by zeripath** [comment]
I suspect that the new configuration does not set the correct working directory. 

I think this might be indicating a bug though - I suspect that:

https://github.com/go-gitea/gitea/blob/main/modules/templates/base.go#L87

Should actually be:

```go
		Directory:                 path.Join(setting.AppWorkPath, "/templates"),
```

**Comment by Gusted** [comment]
@zeripath Applied the patch - same error.

**Comment by zeripath** [comment]
add `"-w=${workspaceRoot}"` to the args

**Comment by zeripath** [comment]
and the patch

**Comment by Gusted** [comment]
Same error, different values:

```
2022/01/24 22:43:23 ...s/context/context.go:207:HTML() [E] Render failed: html/template: "user/dashboard/dashboard" is undefined
2022/01/24 22:43:23 ...s/context/context.go:291:PlainTextBytes() [E] PlainTextBytes: Unable to find status/500 template
2022/01/24 22:43:23 router: completed GET / for 127.0.0.1:34588, 500 Internal Server Error in 7.6ms @ web/home.go:26(web.Home)
2022/01/24 22:43:23 router: completed GET /favicon.ico for 127.0.0.1:34588, 200 OK in 0.9ms @ user/profile.go:51(user.Profile)
```

**Comment by lafriks** [comment]
this works for me:
```json
    {
      "name": "Launch",
      "type": "go",
      "request": "launch",
      "mode": "debug",
      "buildFlags": "",
      "program": "${workspaceRoot}/main.go",
      "env": {
        "GITEA_WORK_DIR": "${workspaceRoot}",
      },
      "args": ["web"],
      "cwd": "${workspaceRoot}",
      "showLog": true
    },
 ```

**Comment by zeripath** [comment]
I think the `cwd` is what is fixing this.

**Comment by lafriks** [comment]
`cwd` is not really fixing imho, just left it just in case (I think it's even defaults to this value already). Problem is that appdir and workdir from us is historically directory where binary is located

**Comment by zeripath** [comment]
so:

```json
        {
            "name": "Launch",
            "type": "go",
            "request": "launch",
            "mode": "debug",
            "buildFlags": "-tags='sqlite sqlite_unlock_notify'",
            "program": "${workspaceRoot}/main.go",
            "env": {
              "GITEA_WORK_DIR": "${workspaceRoot}",
            },
            "args": ["web"],
            "cwd": "${workspaceRoot}",
            "showLog": true
        },
```

is now working for me.

**Comment by zeripath** [comment]
interesting - now why doesn't -w do the same thing
