### ISSUE TITLE
Better repository header

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#184]
I proposa a new repository header. There are three lines for every repository page:

1. [Logo]   Dashboard    Explore    Help              username    +     admin      settings      signout

2. [public or private icon]    [repo name]                                    watch    star    fork      download

3. [repo description]                                                                      ssh | https [git url] copy button

@makhov @fuxiaohei @tboerger

**Comment by fuxiaohei** [comment]
I'm worry about the buttons in the second line. There are four buttons on the right. a little crowd.

**Comment by lunny** [comment]
So lets merge watch button & star button as one button?

**Comment by fuxiaohei** [comment]
good idea

**Comment by tboerger** [comment]
Closing as it is done.

**Comment by Arkanosis** [comment]
> I'm not sure if @Arkanosis comment would also apply to Diaspora

@KingDuckZ: I wish! The last time I checked, Diaspora wasn't implementing ActivityPub, though. I'd really like it to do so to federate with other networks (especially with Mastodon). That would, as an added benefit, make it much easier to federate Diaspora and whatever comes out of this proposal (GitPub or anything else).

Sure, it'd be possible to federate directly with Diaspora using the diaspora federation protocol (webfingers + microformats + others), but this protocol does not seem to get as much traction as ActivityStreams / ActivityPub.

**Comment by vanitasvitae** [comment]
Niiiice!

**Comment by techknowlogick** [comment]
I've locked this issue as it is being currently discussed in the forgefed mailing list please redirect all conversation there.

More info: https://github.com/forgefed/forgefed
