### ISSUE TITLE
Diff view doesn't detect doc-style comment in Scala code

### ISSUE THREAD

**Issue by mal-tee** [go-gitea/gitea#18406]
### Gitea Version

1.17.0+dev-37-g93250bfe2 and 1.15.6 

### Operating System

Ubuntu 21.10

### Browser Version

Firefox 96 

### Can you reproduce the bug on the Gitea demo site?

Yes

### Description

The syntax highlighting doesn't pick up this comment in the diff view:

https://try.gitea.io/mal-tee/test/commit/9e168abc6591937b6f644f3bc2691612e7d97f2b

![image](https://user-images.githubusercontent.com/45886910/151013399-945dcd6f-0e05-405f-8adc-f3df71124e13.png)

the regular view is ok:

![image](https://user-images.githubusercontent.com/45886910/151013480-b2f9fc82-1f41-4245-98e5-c5ed5adaabc4.png)

### Screenshots

see above

**Comment by silverwind** [comment]
IIRC, this is because diff content is fed to `chroma` line-per-line, so multi-line things like these doc blocks can not correctly highlight.

**Comment by lunny** [comment]
duplicated #23176
