### ISSUE TITLE
WebHook to internal Drone CI not allowed

### ISSUE THREAD

**Issue by zimbres** [go-gitea/gitea#18402]
### Gitea Version

1.16.0+rc1

### Git Version

2.30.2

### Operating System

Docker

### How are you running Gitea?

Docker "latest"

### Database

SQLite

### Can you reproduce the bug on the Gitea demo site?

No

### Description

Im getting the messege when try to webhook to Drone CI running internally. Where I can set the host/subnet list to allow it on Docker Container?

webhook can only call allowed HTTP servers (check your webhook.ALLOWED_HOST_LIST setting)

**Comment by wxiaoguang** [comment]
`webhook can only call allowed HTTP servers (check your webhook.ALLOWED_HOST_LIST setting)`

The message is CLEAR

**Comment by sahil87** [comment]
@zimbres did this solve your problem?
For me Drone doesn't trigger builds even after this setting contains *.

![image](https://user-images.githubusercontent.com/9037064/154891875-6858edba-97b1-48a5-ba83-ec432b567b8c.png)

**Comment by zimbres** [comment]
Yes, in facto you should use:

ALLOWED_HOST_LIST = *

or

ALLOWED_HOST_LIST = private

**Comment by wxiaoguang** [comment]
> @zimbres did this solve your problem? For me Drone doesn't trigger builds even after this setting contains *.
> 
> ![image](https://user-images.githubusercontent.com/9037064/154891875-6858edba-97b1-48a5-ba83-ec432b567b8c.png)

`ALLOWED_HOST_LIST` is a Gitea setting (in `app.ini`), but your screenshot was showing a non-Gitea YAML config .... I highly suspect you didn't set the settings correctly.

**Comment by sahil87** [comment]
Thank you! @zimbres , @wxiaoguang 

Your comments helped me zero down on the problem. My gitea runs in a docker through a docker compose. The above screenshot was an environment variable defined there. The format was wrong.

The following works:
![image](https://user-images.githubusercontent.com/9037064/154895071-84686bd9-d11d-4f72-9039-584a5975353f.png)
