### ISSUE TITLE
500 when changing repo owner from an org to another one

### ISSUE THREAD

**Issue by olivier-mauras** [go-gitea/gitea#1841]
- Gitea version (or commit ref): v1.1.1
- Git version: 2.11.2
- Operating system: Alpine Linux 3.5
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:
```
[...ters/repo/setting.go:289 SettingsPost()] [E] TransferOwnership: removeOrgRepo: database table is locked
[D] Template: status/500
```
## Description
When changing ownership of a repo from an organisation to another it fails with a 500 error

**Comment by ethantkoenig** [comment]
@coredumb Can you confirm that #1842 fixes the problem?

**Comment by olivier-mauras** [comment]
@ethantkoenig compiled and tested, I confirm this fixes the problem!
Thanks for the quick action.
