### ISSUE TITLE
goland debug page 500

### ISSUE THREAD

**Issue by wangjiao123456789** [go-gitea/gitea#18445]
goland  after  debug or run 
Unable to find status/500 template

2022/01/24 19:02:18 ...ers/common/logger.go:21:1() [I] Started GET / for 127.0.0.1:34106
2022/01/24 19:02:18 ...s/context/context.go:206:HTML() [E] Render failed: html/template: "install" is undefined
2022/01/24 19:02:18 ...s/context/context.go:290:PlainTextBytes() [E] PlainTextBytes: Unable to find status/500 template
2022/01/24 19:02:18 ...ers/common/logger.go:30:1() [I] Completed GET / 500 Internal Server Error in 469.837µs

**Comment by wxiaoguang** [comment]
https://docs.gitea.io/en-us/hacking-on-gitea/
