### ISSUE TITLE
[Feature Request] Download Realeases via Torrent

### ISSUE THREAD

**Issue by schorsch13** [go-gitea/gitea#18463]
# Introduction

Releases are currently available as direct download in a `.zip` or `.tar.gz` file. To weaken the effect of censorship (think of the youtube-dl case), releases could also be made available via BitTorrent, so that a lot of alternative sources are available as long as one has the magnet link or the torrent file for the release. It would also help with reducing bandwidth after the release files have been distributed wide enough.

# Proposal

Add a download link to the release page after the `.tar.gz` link

![image](https://user-images.githubusercontent.com/97637661/151698655-87e6cc8e-720e-4b14-a6cd-dc8bb72df612.png)

*Source: [dnkl/foot](https://codeberg.org/dnkl/foot/releases)*

# Technical implementation

After creating the `.zip` and `.tar.gz` file, a `.torrent` file would have to be created in the same directory. That could be achieved by using a Go library or by using a program like [mktorrent](https://github.com/pobrn/mktorrent). The `.zip` and `.tar.gz` files need to be added to the `.torrent` file and the download link for it has to be visible on the releases page. For adding a webseed to the torrent (for initial seeding), the URL https://gitea-instance.example///archive/ has to be set as webseed in the torrent file.

In case no BitTorrent library is available for Go, it would be necessary to implement [Bencode](https://en.wikipedia.org/wiki/Bencode) in Go. After that, the Bencoded torrent file has to be written using a specific structure: https://en.wikipedia.org/wiki/Torrent_file

Bencode seems to be trivial to implement. [ncc1988](https://codeberg.org/ncc1988) did it once in Python in one of his projects. See the bencode function at the top of [this file](https://codeberg.org/ncc1988/cctorrent/src/branch/master/extensions/Torrent.py#L216).

# Credits

The idea, description and technical implementation of this feature comes from a codeberg user called [ncc1988](https://codeberg.org/ncc1988).

See: his feature request on [codeberg](https://codeberg.org/Codeberg/Community/issues/388).

**Comment by lafriks** [comment]
It's not really possible to accomplish as zip/targz are created only on first download

**Comment by 6543** [comment]
closing ... this should be done via external service

you can for example use CI to create a torrent download and push it to a webseed & release torrent file as release attachment ...
