### ISSUE TITLE
Users with first-time PAM authentications cannot access profile page (HTTP 500)

### ISSUE THREAD

**Issue by ichrispa** [go-gitea/gitea#1846]
- Gitea version (or commit ref):
- Git version: bfb44f885468839259bc2ead999953cdd85654e1 (master)
- Operating system: Linux Debian 8
- Database:
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description

Hi everyone,

I have an issue of late when users who have never logged into gitea before authenticate over PAM. The users are authenticated correctly and can access repos (explore) or create their own repos. They are shown in the admin "users" tab.  

If these users try to access their dashboard, profile page or private repos page, they are confronted with an empty page and the server returns a statuscode 500 (without showing the usual error page). Any reference to the users profile - including avatars shown in "explore" - return a broken image link. The same applies if any other user attempts to access these users profiles/repos.

There are no error messages, neither in the logs (gitea.log, xorm.log or http.log). The page loaded is simply empty (no source). The HTTP 500 error code only becomes visible when debugging using firefoxes developer mode.

If the same users are created by an admin first, they can login and everything works as expected...

gitea uses HTTPS and was built with the tags "pam certs bindata".

Any advice on how to further debug this issue?

Best regards,

ichrispa

**Comment by ichrispa** [comment]
On a side note: I do not remember this error occuring when using the sqlite backend. I recently switched to MySQL (fresh install, the sqlite contents where not ported).

**Comment by lunny** [comment]
Maybe you can find the error information on console or file that will be helpful.

**Comment by ichrispa** [comment]
Retested after Upgrade to 1.4.1; issue appears to have been resolved. 

@lunny: Sorry for the long lingering issue and thank you for your assistance.
