### ISSUE TITLE
Files for 1.15.11 and 1.16.0 are incomplete on dl.gitea.io

### ISSUE THREAD

**Issue by fnordsh** [go-gitea/gitea#18474]
### Gitea Version

1.15.11, 1.16.0

### Operating System

Linux-amd64

### How are you running Gitea?

linux-amd64 binary with systemd

### Can you reproduce the bug on the Gitea demo site?

No

### Description

1.16.0 is missing more files than 1.15.11, but in both cases the linux-amd64 binary is absent.
First I thought that the upload might not be finished because it had just been released, but that was hours ago, so apparently something went wrong.

### Screenshots

![image](https://user-images.githubusercontent.com/13398150/151717104-31c5da8f-8ab2-443f-8e69-e0868f9b45cd.png)

**Comment by zeripath** [comment]
Unfortunately we're having some trouble uploading the assets to dl.gitea.io

**Comment by ExplodingDragon** [comment]
您好, 请问当前有可用的版本是多少？我是
OS: Linux
Arch: amd64
May I ask what version is currently available?

**Comment by lenny87** [comment]
It is possible to also upload binaries to github releases?
https://github.com/go-gitea/gitea/releases/tag/v1.16.0 contains only source code tarballs.

**Comment by s-hamann** [comment]
Meanwhile, `linux-amd64` is there, but the signature does not verify:
```
$ gpgv gitea-1.16.0-linux-amd64.asc gitea-1.16.0-linux-amd64
gpgv: Signature made Sun 30 Jan 2022 19:58:00 CET
gpgv:                using RSA key CC64B1DB67ABBEECAB24B6455FC346329753F4B0
gpgv: BAD signature from "Teabot <teabot@gitea.io>"
```
Is that expected/related?

**Comment by bertptrs** [comment]
> Meanwhile, `linux-amd64` is there, but the signature does not verify:

It's not; only the signatures are there.

**Comment by s-hamann** [comment]
> > Meanwhile, `linux-amd64` is there, but the signature does not verify:
> 
> It's not; only the signatures are there.

Funny. It's there for me. Uploaded 01/31/2022 02:27:45 AM +00:00, SHA1 `a200cb8f6daa3e0a44a28a46d80ac89d56f2cb60`.

**Comment by gmingen** [comment]
I see it too. Maybe he meant 1.15.11.

**Comment by somera** [comment]
I'm missing:

`gitea-1.15.11-linux-amd64`

**Comment by ekortright** [comment]
I can confirm that 1.16.0 is there for Linux 64-bit, but the signature verification fails.
Also tried downloading 1.15.11 for Linux 64-bit, but the binary file is not there, so I'm trying 1.15.10 instead.
Downloading seems to take forever: 1.16.0 took about 16.5 minutes, and 1.15.10 took almost 18 minutes.

**Comment by tacerus** [comment]
Where is the public GPG key to verify the signatures with ?

**Comment by techknowlogick** [comment]
1.16.0 is there fully now. Note, some checksums may have changed due to timestamps on files in bindata, and I'm working on 1.15.11 now, if anyone wants to follow along here: https://drone.gitea.io/go-gitea/gitea/50157

**Comment by techknowlogick** [comment]
the 1.15.11 files are uploading now. apologies for delay. please direct all the blame at the infrastructure team (spider man meme of @techknowlogick pointing at another @techknowlogick)
