### ISSUE TITLE
Cannot pull git repo on Gitea 1.16.0 (docker)

### ISSUE THREAD

**Issue by MahdiGhiasi** [go-gitea/gitea#18479]
### Gitea Version

1.16.0 docker

### Operating System

Ubuntu 20.04

### How are you running Gitea?

We've updated our docker-compose Gitea instance to 1.16.0, and since then pulling any repo fails with this error:

```
sh: 1: /usr/local/bin/gitea: not found
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

I've checked inside the gitea server docker image and `/usr/local/bin/gitea` is present in the container, so I'm not sure why we're getting this error.

![image](https://user-images.githubusercontent.com/1775637/151775947-8912402a-3495-46f2-b7f8-24497f8b9246.png)

### Database

PostgreSQL

### Can you reproduce the bug on the Gitea demo site?

No

**Comment by MahdiGhiasi** [comment]
Update: I've tried downgrading Gitea to latest 1.15.x docker image and manually ran `UPDATE version SET version=189 WHERE id=1;` as well on postgres database, but the issue still persists even on the older version.

**Comment by wxiaoguang** [comment]
1. You should never do `UPDATE version SET version=189 WHERE id=1`, you will end up in breaking something. https://docs.gitea.io/en-us/upgrade-from-gitea/
2. You should fix (update) your docker pass-through https://docs.gitea.io/en-us/install-with-docker/#ssh-container-passthrough

**Comment by MahdiGhiasi** [comment]
Thanks for the docker pass-through fix. It solved the issue.

It might also be a good idea to add this to the BREAKING section of the 1.16 release notes on GitHub, so others can know that pass-through needs to be updated when updating to 1.16.

**Comment by zeripath** [comment]
The relevant PR is https://github.com/go-gitea/gitea/pull/17846

We've already marked it BREAKING and updated the PR comment. Unfortunately that BREAKING notice didn't make it in to CHANGELOG.md but we'll try to remember to mention in the blog post.

We've already updated the online documentation.
