### ISSUE TITLE
Firefox: Unable to drag and drop issue cards from Kanban project 

### ISSUE THREAD

**Issue by floviolleau** [go-gitea/gitea#18476]
### Gitea Version

1.16.0

### Git Version

2.20.1

### Operating System

Raspbian buster

### How are you running Gitea?

Downloaded artifact from https://dl.gitea.io/gitea/1.16.0/gitea-1.16.0-linux-arm-6
Run from systemd the cli

### Database

PostgreSQL

### Can you reproduce the bug on the Gitea demo site?

No. Demo is in 1.17.0+dev-66-g72256c16a

### Description

Hi,

Thanks for this amazing app you made!

I just upgraded from 1.15.3 to 1.16.0 and now on my Firefox, I'm unable to drag and drop issue cards on Kanban project view despite I can do it on Chromium.

I was able to do it before the migration.

Thanks for your help.

**Comment by floviolleau** [comment]
Sorry problem what a  cache issue.

**Comment by wxiaoguang** [comment]
@go-gitea/maintainers please consider #18348 seriously (and specially @go-gitea/owners and @silverwind).
* https://github.com/go-gitea/gitea/pull/18348

But I have no interest to push it again because I can not get enough support.
