### ISSUE TITLE
Team Permission Table Bug

### ISSUE THREAD

**Issue by AaronS8** [go-gitea/gitea#18483]
### Gitea Version

1.16.0 && 1.17.0+dev-32-gab7f70167 

### Git Version

2.33

### Operating System

Windows 10

### How are you running Gitea?

I'am running Gitea as a service

### Database

PostgreSQL

### Can you reproduce the bug on the Gitea demo site?

No

### Description
Team Permmission Table bugs

### Bugs

1. if I give a team admin rights I can't change it back to general access
2. if I give a team general access and give all read permission but one permission to write access, the team have readonly access
3. and team members won't be able to assigned a project even if they have write access on **code**, issue which means they aren't recoginzed as collabrators 
### Tested Databases

- MSSQLServer
- MySql
- Sqlite

### Links

https://gitea.com/org/BugTester/teams/collabrotors/edit

### Screenshots

![bug1](https://user-images.githubusercontent.com/98172519/151801859-7d1806a7-9718-44ac-8e1a-e85c415779bc.jpg)
![bug2](https://user-images.githubusercontent.com/98172519/151802137-d15baf2e-72e2-4372-9e90-b55ff0eef380.jpg)

**Comment by Gusted** [comment]
I was able to reproduce the first and third bug. The first bug was a regression and is fixed by #18496, the third bug is another issue which was is currently the behavior(so it should be a new issue as enhancement). The second bug is too vague to understand/reproduce.

**Comment by lunny** [comment]
The first bug is when check `admin access` and then check `general access`, the access table will not be shown again.

**Comment by AaronS8** [comment]
@lunny  This setting the general access and admin is fixed but the team mebers can't be assigned an issue even if they have write permmision in the code and read on the issue.

**Comment by zeripath** [comment]
1. ~~if I give a team admin rights I can't change it back to general access~~ I think this is fixed by #18496 
2. if I give a team general access and give all read permission but one permission to write access, the team have readonly access
3. team members won't be able to assigned a project even if they have write access on code, issue which means they aren't recoginzed as collabrators

**Comment by zeripath** [comment]
As @Gusted said above we're a little confused by number 2 here. Would it be possible for you to create an org with teams on try.gitea.io that replicates the issue. Use temporary users that you can share the passwords of here.

**Comment by AaronS8** [comment]
Sorry I couldn't create temporary users in try.gitea.io since I have slow internet, but I think  number 2 is fixed after I upgraded my gitea to v1.17.0+dev-75-g7f2530e00.
