### ISSUE TITLE
Checked checkboxes rendered as unchecked

### ISSUE THREAD

**Issue by D0ctorWh0** [go-gitea/gitea#18480]
### Gitea Version

1.16.0

### Git Version

2.34.1.windows.1

### Operating System

Windows 10 x64

### How are you running Gitea?

I downloaded gitea .exe file from gitea website. Running it in console window. 

### Database

MSSQL

### Can you reproduce the bug on the Gitea demo site?

No

### Description

After upgrading from gitea 1.15.10 to 1.16.0 cheched checkboxes in issues rendered as unchecked

**Comment by D0ctorWh0** [comment]
It seems to happen only in MS Edge

**Comment by D0ctorWh0** [comment]
Ufter updating to latest version of edge problem has gone

**Comment by delvh** [comment]
So this issue can be considered fixed?

**Comment by D0ctorWh0** [comment]
If the glitch in Edge 82 is not important, then yes
