### ISSUE TITLE
Timezone problem - wrong time in kubernetes without tzdata

### ISSUE THREAD

**Issue by andybe** [go-gitea/gitea#18493]
### Gitea Version

docker gitea:latest (1.16)

### Operating System

Linux arch

### How are you running Gitea?

I'm running gitea in a k3s kubernetes. 

### Database

SQLite

### Can you reproduce the bug on the Gitea demo site?

No

### Description

The Problem without tzdata is a known issue by alpine.

I mount localtime into the container.  (file not link)

Jump into the container. app add tzdata:

Before: Mon Jan 31 18:01:02 UTC 2022

 apk add tzdata
 
After: Mon Jan 31 19:01:13 CET 2022

**Comment by wxiaoguang** [comment]
The timezone problem has been hinted in doc:

https://docs.gitea.io/en-us/install-with-docker/#basics

Users should choose the tzdata they need.
