### ISSUE TITLE
Question: two running tasks in 1.16.0

### ISSUE THREAD

**Issue by somera** [go-gitea/gitea#18507]
### Gitea Version

1.16.0

### Git Version

2.25.1

### Operating System

Ubuntu 20.04.3

### How are you running Gitea?

Download pre compiled gitea-1.16.0-linux-amd64.

### Database

PostgreSQL

### Can you reproduce the bug on the Gitea demo site?

No

### Description

After I updated to Gitea 1.16.0 I see two running tasks. Is this normal?

### Screenshots

![image](https://user-images.githubusercontent.com/8334250/151882472-d9b00127-682f-47fb-87e9-cdc894e6a407.png)

**Comment by lunny** [comment]
It's by designed.
