### ISSUE TITLE
pull requests taking to much time to load, sometimes it crashed the browser

### ISSUE THREAD

**Issue by jimankit2708** [go-gitea/gitea#18513]
### Gitea Version

1.16.0

### Git Version

1.16.0

### Operating System

Ubuntu 20.04 LTS

### How are you running Gitea?

We are running gitea in ubuntu 20.04 over the aws ec2. we are using the binary file for Gitea.

Command to start - service gitea start

### Database

MySQL

### Can you reproduce the bug on the Gitea demo site?

No

### Description

Hi Team,

We are getting some issues with the pull requests, we were using gitea version 1.15.9 and we did the update to the latest version 1.16.0. But we are getting the same issue in the latest version as well.
Here are some helpful details/

Total Commit - 14728
Repo size - 40MB
Branches - we had 77 branches in the repo, we have deleted some of the repos. Now we have 40 branches. 

Things we did already -
- Run garbage collector
- CPU and memory check
- OS security updates.
Mostly we are getting issues with the hotfix branches. 

Can anyone tell me if there is any solution for this?

**Comment by lunny** [comment]
Duplicated of #31600
