### ISSUE TITLE
Missing "New Repo" + "New Mirror" actions in organisation

### ISSUE THREAD

**Issue by somera** [go-gitea/gitea#18523]
### Gitea Version

1.16.0

### Git Version

2.25.1

### Operating System

Ubuntu 20.04.3

### How are you running Gitea?

Downloaded gitea-1.16.0-linux-amd64

### Database

PostgreSQL

### Can you reproduce the bug on the Gitea demo site?

Yes

### Description

In #13091 you added "new mirror" action.

But in 1.16.0 I missing this.

![image](https://user-images.githubusercontent.com/8334250/151961264-d306d470-4b74-4f7c-bce9-1250d8bcf590.png)

**Comment by lunny** [comment]
I couldn't find a suitable place to put the buttons.

**Comment by somera** [comment]
> I couldn't find a suitable place to put the buttons.

On the right side in a new "Actions" Box. Above Persons?

**Comment by silverwind** [comment]
I would do left of "settings", possibly not big green buttons, but subtle ones like the settings button itself.

**Comment by rcdevice** [comment]
![Snap11](https://user-images.githubusercontent.com/30013680/154786475-c7e62e54-2507-4bf7-abe2-235ff5890469.jpg)

**Comment by rcdevice** [comment]
![Snap11](https://user-images.githubusercontent.com/30013680/154786543-d0abca02-f85c-4733-84c5-2bf2f05be42d.jpg)
