### ISSUE TITLE
Can't create repository under organization

### ISSUE THREAD

**Issue by vyacheslav-l** [go-gitea/gitea#18525]
In case if user reached repository creation limit he don't have option to create repository under organization.
Workaround to edit HTML next to "Create Repository" button.

User setup:
Maximum Number of Repositories = 0

Organization setup:
Maximum Number of Repositories = -1

https://discourse.gitea.io/t/creating-repository-bug/4498

**Comment by zeripath** [comment]
We have an issue template for a reason.

Please tell us the version of Gitea you are using etc.

**Comment by vyacheslav-l** [comment]
Gitea Installed Version
1.16.0 

Gitea Versino with same issue
1.15.x, not sure about 1.14.x and before

Operating System
Ubuntu 20.04.2 LTS

**Comment by vyacheslav-l** [comment]
@zeripath any news?

**Comment by vyacheslav-l** [comment]
@zeripath, please provide status update.

**Comment by wxiaoguang** [comment]
Related to ?
* https://github.com/go-gitea/gitea/issues/15504
* https://github.com/go-gitea/gitea/pull/15924

??

**Comment by techknowlogick** [comment]
> @zeripath, please provide status update.

We are all volunteers here working on our free time, please be be patient.

**Comment by vyacheslav-l** [comment]
> Related to ?
> 
> * [User in Organisation has no repo limit but the user itself has a limit of 0: Cannot create repo in organisation #15504](https://github.com/go-gitea/gitea/issues/15504)
> * [fix ui bug when user can't create repo but org can #15924](https://github.com/go-gitea/gitea/pull/15924)
> 
> ??

Yes, issues are related

**Comment by wxiaoguang** [comment]
Duplicate, so close this one.
