### ISSUE TITLE
web interface - spellchecker of the browser not available

### ISSUE THREAD

**Issue by flobee** [go-gitea/gitea#18532]
### Feature Description

The default behavior for spell checking of the browser does not work in forms. e.g when editing a README.md and want to use spell checks

### Screenshots

not possible within a right mouse click

**Comment by silverwind** [comment]
There is `spellcheck="false"` set on the underlying texarea which was probably to work around some issue. We can remove it but I'm not sure whether spell checking can even work with CodeMirror, those might require a standard `<textarea>`.

**Comment by flobee** [comment]
Well. Never refactor/reset standard browser functionality. Removing default user control is a completetly NOGO since ages >25Y i experience. Make all default browser standards available/possible as good you can.

**Comment by wxiaoguang** [comment]
There is an option for EasyMDE/CodeMirror.

```
spellChecker: If set to false, disable the spell checker. Defaults to true. Optionally pass a CodeMirrorSpellChecker-compliant function.
```

However it was set to `false` in history in Gitea code. I do not think it's correct. The wrong code was just Copied&Pasted from https://github.com/go-gitea/gitea/commit/2b10fdc4 .

A simple PR can fix this problem

**Comment by wxiaoguang** [comment]
Please test #19776
* https://github.com/go-gitea/gitea/pull/19776
