### ISSUE TITLE
Make backup more incremental or restic friendly

### ISSUE THREAD

**Issue by GAS85** [go-gitea/gitea#18556]
### Feature Description

Currently I'm using [restic](https://restic.readthedocs.io/en/stable/040_backup.html) to perform backups. It will bother about duplicates, changes, increments and snapshots. But `ZIP` file is not suitable for this purpose and will always be taken as a new file that drives to wasting of space. I need to unzip file twice, first initial zip that I have after `dump` command and then `gitea-repo.zip`.

Please add option to perform backup in one folder without archiving it.

**Comment by mscherer** [comment]
You can use `gitea dump --type tar` to not compress anything, wouldn't it solve the issue of being more friendly to restic ?

**Comment by techknowlogick** [comment]
If you are using restic for your backups, you'd be better off pointing it at the data directories directly instead of at the zip/tar output of dump (note, you'll probably need to add in a mysqldump or the equivalent for your DB still)

**Comment by GAS85** [comment]
> You can use gitea dump --type tar to not compress anything
This will be still 1 file that will taken by restic as a new and I need to extract it.

> pointing it at the data directories directly
That what I suppose to do, but expect that SQL dump is also there, and I do not need to relay on any other tool / commands to do it before backup.

Add something like `--type raw` to not zip/tar directory will be really nice.
