### ISSUE TITLE
replace all git.Command.RunInPipeline... with RunWithContext

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#18553]
- [x]  Change git.cmd to RunWithContext (#18693)
        cmd.RunInDirTimeoutPipeline,
        cmd.RunInDirTimeoutEnvFullPipeline,
        cmd.RunInDirFullPipeline,
        ...
- [x] Delete cmd.RunInDir... func()

**Comment by lunny** [comment]
If all has been replaced, then we can rename `cmd.RunWithContext` to `cmd.Run`

**Comment by martinscholz83** [comment]
Can I take this up? I searched with a regex `.*cmd\..*Pipeline` for all places. I think that should find all.

**Comment by 6543** [comment]
@martinscholz83 yes would be awesome :)

**Comment by 6543** [comment]
PS: if you look closely all the RunInPipeline... func do already use RunWithContext ... so the code cleanup should be easy todo - if you have issues just tell us here :)

**Comment by martinscholz83** [comment]
I changed all the calls to `RunWithContext` so that I can now remove the `RunInPipeline` func. Shall I open a new PR?

**Comment by 6543** [comment]
@martinscholz83 yes sure go on :)

as always if you need help we are a `@`ping away ;)
