### ISSUE TITLE
[Feature Request] Configureable wiki branch

### ISSUE THREAD

**Issue by renaissance14** [go-gitea/gitea#18568]
# Introduction

Currently the wiki has only one branch where everything happens and its name is `master`. There is no option to view the wiki from a different branch

# Proposal

- Change the default branch name from `master` to `main` ([IETF recommended terminology](https://datatracker.ietf.org/doc/html/draft-knodel-terminology-07))
- Add a drop-down menu where you can switch the branch of the wiki in the web-ui

# Credits

The main idea of this feature request comes from the codeberg user [ECP5-PCIe](https://codeberg.org/ECP5-PCIe). Have a look at the issue on [codeberg](https://codeberg.org/Codeberg/Community/issues/555)

**Comment by zander** [comment]
Can you explain how you would use this to make this useful?

Sounds like it would be extremely confusing and making something that is simple and elegant overly complex, I'd like to know what usecase this solves.

**Comment by aschrijver** [comment]
(The first bullet point at least would be for sake of consistency. Creating a new repo will create a `main` branch, not `master` which is the old way. Second bullet would be optional, and not a need I have personally)

**Comment by ECP5-PCIe** [comment]
Yes, changing the default branch to main for consistency would be good and was my main issue with it, though having it configurable might be good for people who use other branch names, like having a wiki branch.
One use-case for a user-selectable branch might be if you have different wikis, for example one for using the program and another for developing it.

**Comment by wxiaoguang** [comment]
->  Make wiki default branch name changable #29603
