### ISSUE TITLE
Resolving Merge Conflicts On Gitea

### ISSUE THREAD

**Issue by AaronS8** [go-gitea/gitea#18570]
### Feature Description

I think it would be great if gitea could have merge conflict editor like visual studio

### Screenshots

![manual Merge](https://user-images.githubusercontent.com/98172519/152312301-f8b7f681-143f-4116-8f89-5001129d8014.jpg)
![wecandothisto](https://user-images.githubusercontent.com/98172519/152312365-6a705b68-49cc-454b-bbf2-3b06f17104e7.jpg)

**Comment by AaronS8** [comment]
### visual studio behaviour
1. after you try merging and conflict occures
2. it lists the files with merging errors under the **_Unmerged Changes_**
3. Then when you select the one file it opens the merge conflict editor
4. it lets you select wich difference your going to take you can even select both of them which it assumes the first selected comes first and puts it on top 
5. it have check box like that shows 
   - Show Conflicts Only
   - Take Incoming 
   - Take Current
   - Indivisually line by line using check box to let the merge editor you will take that change

**Comment by AaronS8** [comment]
### GitHub Merge Conflict Editor
![Githubmergeconflict](https://user-images.githubusercontent.com/98172519/152333521-11bafce3-77ef-4bf4-9069-c1b5662f110f.jpg)

**Comment by richmahn** [comment]
Don't see the original issue. It's #9014
