### ISSUE TITLE
problems with copying CRLF files in the browser

### ISSUE THREAD

**Issue by mrexodia** [go-gitea/gitea#1857]
- Gitea version (or commit ref): 62f600c
- Git version: ?
- Operating system: Windows 8.1 x64
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant

When copying a file with CRLF line endings (https://try.gitea.io/mrexodia/testcopy/src/master/crlf.txt) there will be additional lines inserted when pasting in notepad:

![](https://i.imgur.com/mJ4zqU9.png)

**Comment by silverwind** [comment]
This is because of empty text nodes inside the code `<pre>`:

````html
<ol class="linenums"><li class="L1" rel="L1">Lorem ipsum dolor sit amet
</li>
<li class="L2" rel="L2">Nam condimentum, odio a egestas dapibus
</li>
<li class="L3" rel="L3">Nulla egestas velit nec elit dapibus aliquet.
</li>
<li class="L4" rel="L4">Nulla facilisi. Praesent vel sem sit amet
</li>
<li class="L5" rel="L5">Fusce tincidunt laoreet laoreet.</li>
</ol>
````

Fix would be to render `</li><li` (e.g. no newline between)

**Comment by mrexodia** [comment]
The same issue was fixed in gogs by simply trimming `\r` from the end of every line: https://github.com/gogits/gogs/commit/91f65cedc88729b5504d72647185d685083df773

**Comment by appleboy** [comment]
@mrexodia fixed in https://github.com/go-gitea/gitea/pull/1931

**Comment by mrexodia** [comment]
Yeah, but that's not merged 😄

**Comment by silverwind** [comment]
Soon. I'd say my approach is the better one, it preserves the original line endings and does not introduce a extra `\n` at the end of the copied text.

**Comment by mrexodia** [comment]
From what I can tell no new lines were introduced if I copy from here: https://try.gogs.io/mrexodia/testcopy/src/master/crlf.txt

I'm still looking at switching to gitea, but I couldn't really find a list of benefits or a clear update path from gogs so I'm postponing it...

**Comment by silverwind** [comment]
Might be your editor trimming it, but I certainly get a newline pasted after the text:

<img width="495" src="https://user-images.githubusercontent.com/115237/27006490-1b26b600-4e35-11e7-99ac-b6c88ef2162a.png">

**Comment by lafriks** [comment]
@mrexodia Upgrade instructions are here - https://docs.gitea.io/en-us/upgrade-from-gogs/
