### ISSUE TITLE
email activation is disabled but still showing the message

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#18574]
### Gitea Version

1.16

### Operating System

Linux

### Browser Version

Chrome Latest

### Can you reproduce the bug on the Gitea demo site?

No

### Description

I have set REGISTER_EMAIL_CONFIRM to false, REGISTER_MANUAL_CONFIRM to true in app.ini file.
When someone sign up, It still says "A new confirmation email has been sent to . Please check your inbox within the next 3 hours to complete the registration process.
It's confusing so please change this message 

### Screenshots

![image](https://user-images.githubusercontent.com/93811078/152359300-25afd57f-383a-49b2-b450-4d5bf03f81b1.png)

**Comment by poka-IT** [comment]
This is not just a message bug, but the user still receive email confirmation even REGISTER_EMAIL_CONFIRM is set to false and REGISTER_MANUAL_CONFIRM to true.

https://github.com/go-gitea/gitea/issues/17263

**Comment by kusattapangod** [comment]
hmm

**Comment by wxiaoguang** [comment]
It should have been fixed by
*  #19119
