### ISSUE TITLE
[Bug Report] Wiki as submodule

### ISSUE THREAD

**Issue by renaissance14** [go-gitea/gitea#18590]
# Introduction

When adding the wiki of a repo to the repo itself as a submodule, you will get a 404 error in the web UI when clicking on the submodule. This occurs due to the fact that the wiki is no real repo.

# Example

Here are two example repositories. One on codeberg and one on try.gitea

- https://try.gitea.io/schorsch/test-wiki-submodule
- https://codeberg.org/moenavigator/moenavigatorengine (the `./doc` folder)

# Proposal

The wiki has the exact same name as the original repo but with the suffix `.wiki`. When accessing `https://gitea-instace.example/user/repo.wiki` just redirect to `https://gitea-instance.example/user/repo/wiki`

# Credits

The bug was discovered by the codeberg user [ncc1988](https://codeberg.org/ncc1988). They also suggested the workaround. For further information have a look at the issue on codeberg: https://codeberg.org/Codeberg/Community/issues/217

**Comment by lunny** [comment]
But this maybe a break for those repositories have suffix `.wiki` but in fact it's not a wiki of some repositories.

**Comment by a1012112796** [comment]
> But this maybe a break for those repositories have suffix `.wiki` but in fact it's not a wiki of some repositories.

@lunny `.wiki` has been reserved. https://github.com/go-gitea/gitea/blob/2b5e0134307a45581860029de99449e8be8f807e/models/repo/repo.go#L30
