### ISSUE TITLE
Issue Not Found

### ISSUE THREAD

**Issue by AaronS8** [go-gitea/gitea#18597]
### Gitea Version

1.15 ,1.16 && 1.17.0+dev-75-g7f2530e00

### Git Version

2.33

### Operating System

Windows 10

### How are you running Gitea?

Used One of your downloads

### Database

MSSQL

### Can you reproduce the bug on the Gitea demo site?

No

### Bug

After trying to open issue, Got 404 Page ("You're not authorized or you don't ve permmssion but I've the admin account).
Deleted the index folder from gitea directory still the problems still perssisted, at last I noticed on the 404 page there was login button, I loged in then I was able to access the issue freely, I tried to recreate the bug but I didn't found it yet.

**Comment by wxiaoguang** [comment]
Check the `ROOT_URL` in your `app.ini` first.

**Comment by AaronS8** [comment]
@wxiaoguang  checked it,  ROOT_URL         = http://localhost:3000/ 
It's not just issues but repositories have similar problem.

Uploading GiteaBugReport.mp4…

**Comment by wxiaoguang** [comment]
It's wrong. Please read the document about how to set ROOT_URL

**Comment by AaronS8** [comment]
@wxiaoguang  I don't understand what is wrong, I've read the Gitea documentation on configuration, I don't see anything wrong.
### Clarification
1.I'm using it on my local computer if it about the localhost, and the the application does that on the actual gitea instance
2. where the root url set the actual ipaddress of the server.
 am I still wrong?

**Comment by AaronS8** [comment]
I understand my mistake now, thanks!!!
