### ISSUE TITLE
[Bug Report] Mentioning a deleted user ghost results into 404

### ISSUE THREAD

**Issue by renaissance14** [go-gitea/gitea#18602]
# Introduction

If you mention a deleted user @ghost who is actually proposed if a ghost user is in your current issue conversation, it creates a link to that non-existent user resulting in a 404 error page. 

The name `Ghost` is also pretty confusing and could be renamed to `Deleted User` or something.

# Proposal

This issue can be resolved either by checking if a mentioned user (even if a username) (still) exists and only link to that profile if it does or by displaying an information like "This user has been deleted" in case of a ghost user. 

# Credits

This bug was discovered my the codeberg user [fnetX](https://codeberg.org/fnetX). For further information have a look at the issue on codeberg: https://codeberg.org/Codeberg/Community/issues/361

**Comment by fnetX** [comment]
I assigned myself to the downstream issue as I planned to add a "This user is a ghost" page to Gitea, it's about position 4 on my backlog :)

If someone decides to rather implement the user checking to avoid links to /ghost, I'm happy about that, too, but I won't find time for that solution.

**Comment by yardenshoham** [comment]
Fixed by #21554?
