### ISSUE TITLE
WorkerPool warnings after upgrade from 1.13 to 1.16-rc1

### ISSUE THREAD

**Issue by pboguslawski** [go-gitea/gitea#18617]
### Gitea Version

1.16-rc1

### How are you running Gitea?

Compiled from source.

### Can you reproduce the bug on the Gitea demo site?

No

### Description

After upgrade from 1.13 to 1.16-rc1 gitea send to its stderr messages like

```
2022/02/05 04:56:21 .../queue/workerpool.go:93:zeroBoost() [W] WorkerPool: 17 (for mirror-channel) has zero workers - adding 1 temporary workers for 5m0s
2022/02/05 04:56:28 .../queue/workerpool.go:93:zeroBoost() [W] WorkerPool: 14 (for repo_stats_update-channel) has zero workers - adding 1 temporary workers for 5m0s
2022/02/05 11:23:46 .../queue/workerpool.go:93:zeroBoost() [W] WorkerPool: 13 (for issue_indexer) has zero workers - adding 1 temporary workers for 5m0s
```

No such messages in gitea 1.13 on same data so looks like a bug in new gitea version.

**Comment by lunny** [comment]
It's just a warn and it should have no effect for usage. 

But I think maybe it could be a `trace` or  a `info`. @zeripath

**Comment by pboguslawski** [comment]
> It's just a warn and it should have no effect for usage.

Error/warnings should not be ignored by admins. Gitea should not produce messages that have no effect for usage.

**Comment by zeripath** [comment]
These are all already debug on 1.17. I'll add it to #18620

**Comment by zeripath** [comment]
I would note that this has been there since 1.15 when we moved to the zero initial worker mode and was there to ensure things were working correctly.
