### ISSUE TITLE
Uncaught TypeError: Aa is undefined

### ISSUE THREAD

**Issue by tacohitbox** [go-gitea/gitea#18611]
### Gitea Version

1.15.10

### Git Version

2.25.1

### Operating System

Ubuntu 20

### How are you running Gitea?

I'm running Gitea from one of the downloads, if I recall correctly.
It's ran through systemd on an Ubuntu VPS.

### Database

PostgreSQL

### Can you reproduce the bug on the Gitea demo site?

No

### Description

Mirror log calls and certain sidebar links have `/undefined/` in their URL.

Mirrors seem to fail at first but it's just the logs being called incorrectly.

Not sure if it's related, although it probably is, there's an error in the console reading `Uncaught TypeError: Aa is undefined`

Full error:
```
Uncaught TypeError: Aa is undefined
    km [redacted]/assets/js/index.js?v=9a0f63666f00393444485fcd82e8ace3:29
    da [redacted]/assets/js/index.js?v=9a0f63666f00393444485fcd82e8ace3:29
    da [redacted]/assets/js/index.js?v=9a0f63666f00393444485fcd82e8ace3:29
    km [redacted]/assets/js/index.js?v=9a0f63666f00393444485fcd82e8ace3:29
    js [redacted]/assets/js/index.js?v=9a0f63666f00393444485fcd82e8ace3:62
    ir [redacted]assets/js/index.js?v=9a0f63666f00393444485fcd82e8ace3:29
    ir [redacted]/assets/js/index.js?v=9a0f63666f00393444485fcd82e8ace3:29
    js [redacted]/assets/js/index.js?v=9a0f63666f00393444485fcd82e8ace3:62
    Lt [redacted]/assets/js/index.js?v=9a0f63666f00393444485fcd82e8ace3:62
    Di [redacted]/assets/js/index.js?v=9a0f63666f00393444485fcd82e8ace3:62
```

### Screenshots

![image](https://user-images.githubusercontent.com/87399016/152631250-700efe51-781e-40ea-a0cc-6fdf211e828b.png)

**Comment by lunny** [comment]
Could you clear the cache and visit again?

**Comment by tacohitbox** [comment]
This issue was on a fresh browser, but I will try again.

**Comment by tacohitbox** [comment]
Any updates?

**Comment by zeripath** [comment]
All I can say is that no one can reproduce but I would note that 1.15.10 isn't even the latest 1.15 version,  and 1.16.1 is out.

Upgrade and see if the problem persists

**Comment by tacohitbox** [comment]
Yeah, updating fixed my issue. Thanks and sorry for not trying that first.
