### ISSUE TITLE
Unable to create backup

### ISSUE THREAD

**Issue by skibbipl** [go-gitea/gitea#18627]
### Gitea Version

1.16.0

### Git Version

2.34.1

### Operating System

Debian bookworm

### How are you running Gitea?

Manually installed binary files

### Database

PostgreSQL

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/skibbipl/eab96d7606022e9837c2abdba4d0c964

### Description

I have no idea why gitea complains about permissions. `/tmp/data` is r/w for git user.
```
ls -la /tmp/data
total 24
drwxr-xr-x  6 git  git  4096 Feb  5 20:11 .
drwxrwxrwt 21 root root 4096 Feb  5 20:11 ..
drwxr-xr-x  2 git  git  4096 Feb  5 20:11 attachments
drwxr-xr-x  2 git  git  4096 Feb  5 20:11 avatars
drwxr-xr-x  2 git  git  4096 Feb  5 20:11 repo-archive
drwxr-xr-x  2 git  git  4096 Feb  5 20:11 repo-avatars
```

**Comment by lunny** [comment]
filesytem permission problem.

**Comment by skibbipl** [comment]
I had to reboot server to fix the problem. Permissions were OK. Strange.
