### ISSUE TITLE
[Feature Request] Add `Approve` button to the main PR page

### ISSUE THREAD

**Issue by renaissance14** [go-gitea/gitea#18623]
# Introduction

Currently when you want to approve a PR you have to navigate to `PR > Files Changed > Review > Approve`. It is not only confusing for beginners but also a unnecessary handicap. Of course you should review the changes before approving but still a unnecessary amount of "work"

# Proposal

Add a `Approve` button right next to the `Merge` button

**Comment by lunny** [comment]
Why you want to approve before you have reviewed the code?

**Comment by schorsch13** [comment]
> Why you want to approve before you have reviewed the code?

I did not say that I want to approve before reviewing

> Of course you should review the changes before approving

**Comment by lunny** [comment]
> > Why you want to approve before you have reviewed the code?
> 
> I did not say that I want to approve before reviewing
> 
> > Of course you should review the changes before approving

So I think it's suitable only put the button on review page but not conversation page.

**Comment by yardenshoham** [comment]
I agree, it doesn't make sense to have the approval button outside the Files Changed tab
