### ISSUE TITLE
Release page don't paginate

### ISSUE THREAD

**Issue by sapk** [go-gitea/gitea#1863]
## Env

- Gitea version (or commit ref): 009a0739906566abd511d17d53b8282696e9e99e
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes (https://try.gitea.io/sapk/test-release/releases && https://try.gitea.io/sapk/test-release/releases?page=2)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

The page list is not shown at bottom of page

## Screenshots

![image](https://cloud.githubusercontent.com/assets/4052400/26754793/6c11368a-4881-11e7-80df-fd278c25a08b.png)

**Comment by lunny** [comment]
should be fixed by #1866

**Comment by sapk** [comment]
No this is the fact that we don't have page list at bottom of release page.

**Comment by lunny** [comment]
So if there is no PR for this, move this to v1.3 is a good chosen.

**Comment by sapk** [comment]
This is a bad bug but not blocking for the use of gitea. (we just don't have button to go to next page)
I don't have time to investigate futhermore in the next days so we could move to v1.3 if no one can fix it before.

**Comment by lafriks** [comment]
Reopening as #2080 fixes this
