### ISSUE TITLE
user restricted flag is reset on login

### ISSUE THREAD

**Issue by netcicd** [go-gitea/gitea#18643]
### Gitea Version

1.17.0+dev-86-g92e81e97e

### Operating System

docker

### How are you running Gitea?

running as a container

### Database

PostgreSQL

### Can you reproduce the bug on the Gitea demo site?

No

### Description

configured gitea with 

`gitea admin auth update-oauth --id 1 --required-claim-name giteaGroups --admin-group giteaAdmin --group-claim-name giteaGroups --restricted-group infraautomator,gitea-netcicd-read,gitea-netcicd-write,gitea-netcicd-admin,gitea-cicdtoolbox-read,gitea-cicdtoolbox-write,gitea-cicdtoolbox-admin --skip-local-2fa`

when I log in using oauth and user has 
```
"giteaGroups": [
    "gitea-netcicd-read",
    "gitea-cicdtoolbox-admin"
  ],
```
in the token, the restricted flag set at the user gets reset.

**Comment by zeripath** [comment]
--restricted-group is meant to be one group and one group only.
