### ISSUE TITLE
incorrect password while delete organisation still continues to next page

### ISSUE THREAD

**Issue by tskamath** [go-gitea/gitea#1865]
- Gitea version (or commit ref): 2ec5dc1
- Git version: 2.11.2
- Operating system: Synology NAS DSM: Docker
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [√ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [√ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
even if incorrect password is entered while delete organisation. "incorrect password" is not shown immediately but proceed to next page, the returned page displays "Please ensure the that password you entered is correct.".

maybe a bug..? shouldnt the password be check before providing the next page for confirmation..?

## Screenshots
<img width="894" alt="screen shot 2017-06-03 at 10 27 58 pm" src="https://cloud.githubusercontent.com/assets/3492767/26755524/847a9e34-48ac-11e7-8e83-af33911ad1ad.png">
<img width="828" alt="screen shot 2017-06-03 at 10 27 47 pm" src="https://cloud.githubusercontent.com/assets/3492767/26755527/8c318192-48ac-11e7-8f1d-8afce3d85df2.png">

regard
Srikanth Kamath

**Comment by lunny** [comment]
The password will be check on the server side after form is submitted. It's not checked via AJAX.
