### ISSUE TITLE
docs / comparison: mention GPG Signed Commits?

### ISSUE THREAD

**Issue by Mikaela** [go-gitea/gitea#18662]
I noticed that https://docs.gitea.io/en-us/comparison/ under code management ( https://github.com/go-gitea/gitea/blob/main/docs/content/doc/features/comparison.en-us.md#code-management ) mentions GPG Signed Commits.

I don't think anything else than Gitea supports SSH Signed Commits yet (at least not [GitHub](https://github.com/github/feedback/discussions/7744) or [GitLab](https://gitlab.com/gitlab-org/gitlab/-/issues/343879)) being so recent feature, I think it could be nice to mention.

**Comment by lunny** [comment]
@Mikaela Would you like to send a PR to add that?

**Comment by lunny** [comment]
> @Mikaela Would you like to send a PR to add that?

I did it. :)
