### ISSUE TITLE
gomail library unmaintained

### ISSUE THREAD

**Issue by fnetX** [go-gitea/gitea#18664]
The gomail library used by Gitea is out of date. Transfer from me from the channel ([Matrix](https://matrix.to/#/%23gitea%3Amatrix.org/%24Kh1hQlkz2u0spp6ihaF_SCgScOBdJ-iPtbx-FwhHUac?via=matrix.org&via=libera.chat&via=maclemon.at))

> Gitea seems to use https://github.com/go-gomail/gomail which is unmaintained since 2016, and the "actively maintained" fork appears unmaintained, too: https://github.com/go-mail/mail/
> Do you consider this an issue for you? I looked at some Gitea issues, and some cases like different timeouts / retries is also a feature request to both frameworks, but apparently never implemented. Does a switch make sense, or is the current state perfectly fine?

---

Discussion already started here:

> FYI
> 
> * https://github.com/go-gomail/gomail/issues/163
> * https://github.com/go-gomail/gomail/issues/150
> 
> Maybe we should maintain gomail by ourselves, or switch to another one. Then we may not need hacky code.
> 
> 
> Some active forks:
> 
> * https://github.com/Shopify/gomail (Shopify is a big company)
> * https://github.com/DeedleFake/gomail (new)

_Originally posted by @wxiaoguang in https://github.com/go-gitea/gitea/issues/18075#issuecomment-1000053400_

**Comment by wxiaoguang** [comment]
FYI, there were more comments. 
1. These active forks seem not ideal. 
2. IIRC many contributors accepted to maintain the gomail by ourselves since it's not complex.

**Comment by lunny** [comment]
How about convert to https://github.com/xhit/go-simple-mail .

**Comment by sh7dm** [comment]
> How about convert to https://github.com/xhit/go-simple-mail .

+1, it appears to be quite active and featured, I'm going to try myself at integrating it

**Comment by fredmenez** [comment]
FYI the maintainer of go-gomail/gomail has left this world, details in https://github.com/go-gomail/gomail/issues/182.

**Comment by techknowlogick** [comment]
@fredmenez thank you for sharing this news with us ❤️ 🕯️

**Comment by Neustradamus** [comment]
Dear all, it is possible to change your code?
Change from here:
- https://github.com/go-gomail/gomail
- https://github.com/go-gomail/gomail/issues/188
- https://github.com/go-mail/mail
- https://github.com/Shopify/gomail
- https://github.com/Shopify/gomail/issues/59
- https://github.com/ory/mail

It has been unmaintained and maybe one or more vulnerabilities :/

There are:
- https://github.com/xhit/go-simple-mail from @xhit
- https://github.com/wneessen/go-mail from @wneessen

Linked to:
- https://github.com/go-gomail/gomail/issues/182
- https://github.com/go-gomail/gomail/issues/163
- https://github.com/go-gomail/gomail/issues/142
- https://github.com/go-gomail/gomail/issues/108
- https://github.com/go-gomail/gomail/issues/104
- https://github.com/go-gomail/gomail/issues/105
- https://github.com/go-gomail/gomail/issues/94
- https://github.com/go-mail/mail/issues/78
- https://github.com/go-mail/mail/issues/73
- https://github.com/go-mail/mail/issues/61

**Comment by lunny** [comment]
Maybe https://github.com/wneessen/go-mail is a better choice.

**Comment by Neustradamus** [comment]
@lunny: Thanks for your reactivity!
Yes totally! :)

**Comment by lunny** [comment]
First step #32618 to move to the new package.

**Comment by Neustradamus** [comment]
@lunny: Thanks for your quick PR!

**Comment by Neustradamus** [comment]
Thanks to @lunny for this work to solve this important ticket:

Linked to:
- https://github.com/go-gitea/gitea/issues/18664
- first PR: https://github.com/go-gitea/gitea/pull/32618
- Second PR: https://github.com/go-gitea/gitea/pull/32682

**Comment by Neustradamus** [comment]
@lunny: Good job, thanks!
