### ISSUE TITLE
Main ('stable'?) instance HTTP status code 500 + no push ability

### ISSUE THREAD

**Issue by Nomagno** [go-gitea/gitea#18663]
### Gitea Version

gitea.com

### Operating System

gitea.com

### Browser Version

All available browsers and networks (WebKit, Firefox, Chromium, IPv4, IPv6)

### Can you reproduce the bug on the Gitea demo site?

No

### Description

The main instance (https://gitea.com) seems to return HTTP status code 500 on every request, after redirecting to /user/login. The demo instance isn't affected. Additionally, trying to push to the main instance produces the following error:
```
error: remote unpack failed: unable to create temporary object directory
To https://gitea.com/Nomagno/ANY-REPO
! [remote rejected] master -> master (unpacker error)
```

### Screenshots

https://0x0.st/oXB-.png

**Comment by zeripath** [comment]
Please use the #gitea.com channel on discord.
