### ISSUE TITLE
Slovak translation

### ISSUE THREAD

**Issue by brango67** [go-gitea/gitea#18674]
Hi!

I'd like to help with the the Slovak translation of Gitea.

Cheers!
Branislav

**Comment by techknowlogick** [comment]
Hey @brango67 what is your username on crowdin.com? I can activate this language to accept translations:)

**Comment by lunny** [comment]
@brango67 language Slovak has been created and you have bee set as proofreader. Note: Only those languages translated over 20% will be included in release version.
