### ISSUE TITLE
Gitea: Rejecting changes as Gitea environment not set.

### ISSUE THREAD

**Issue by nishit93-hub** [go-gitea/gitea#18681]
### Gitea Version

gitea/gitea:latest

### Git Version

gitea/gitea:latest

### How are you running Gitea?

Hi there,

I have setup Gitea  on kubernetes.
When i do git clone and push changes back to git repo from locally, its working fine.

Now same thing i am trying to do inside the gitea kubernetes pod.
There i cloned the bare repository to new directory and pushed the changes backup to repo. However i am getting the below errors.

```
bash-5.1# git push origin master
Enumerating objects: 4, done.
Counting objects: 100% (4/4), done.
Delta compression using up to 48 threads
Compressing objects: 100% (2/2), done.
Writing objects: 100% (3/3), 304 bytes | 304.00 KiB/s, done.
Total 3 (delta 0), reused 0 (delta 0), pack-reused 0
remote: 2022/02/09 08:29:22 ...s/setting/setting.go:952:loadFromConf() [F] Expect user 'git' but current user is: root
To /data/wordpress/nishit/wordpress-main.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to '/data/wordpress/nishit/wordpress-main.git'
```

### Can you reproduce the bug on the Gitea demo site?

No

**Comment by zeripath** [comment]
Pushes to Gitea's repositories must go through Gitea. That is through http(s) or ssh and not to the repositories themselves.

That you have ever seen "Rejecting changes as Gitea environment not set" implies that you're not doing this. If you have set `ONLY_ALLOW_PUSH_IF_GITEA_ENVIRONMENT_SET=true` to counter that warning - you are in an unsupported configuration.

If you cannot figure out the environment necessary to make this work yourself you should not be doing it. If you are insistent that you absolutely must be able to push to Gitea's repos directly you may discuss with me directly on discord or matrix but this is not supported by Gitea.

**Comment by nishit93-hub** [comment]
@zeripath Ok. Actually, I am using one script for installing Gitea on the Kubernetes cluster. After it gets installed, the script would also mirror the external repository somewhere on GitHub or GitLab into repo on Gitea.

For that, I am not using HTTP or ssh Gitea protocol. what my script would do is

1) It login to the pod using kubectl and clone the external repo as a bare repo.
2) From there it would mirror the cloned repo by pushing on the Gitea repo.

If it is not supported by Gitea then I need to find another way.

**Comment by techknowlogick** [comment]
That seems unnecessarily complicated, as Gitea has mirroring built in.

**Comment by nishit93-hub** [comment]
@techknowlogick Agree with you that Gitea has mirroring built-in. But that would be a manual task.
 I want to install Gitea on k8s, then create a repo, and then mirror the existing repo into the Gitea repo using a single script.

Same thing I have tested using my own GitSCM server by creating a bare repo, there for GIt scm I am getting any UI, that's I am doing R&D on Gitea.

Moreover same thing I can do with Gogs.

**Comment by lunny** [comment]
@nishit93-hub You are discourage to do that because then you may lost some update action and some data may be inconsistent. You can change the remote to the https protocol to do the same thing I think. Another method is that you can create mirror via API `POST /migrate`.
