### ISSUE TITLE
Error 500 on admin users dashboard when there is a new version

### ISSUE THREAD

**Issue by exbob** [go-gitea/gitea#18698]
### Gitea Version

itea version 1.16.0+rc1 built with GNU Make 4.3, go1.17.6 : bindata, timetzdata, sqlite, sqlite_unlock_notify

### Git Version

git version 2.30.2

### Operating System

Docker（QNAP Container Station）

### How are you running Gitea?

 User Docker（QNAP Container Station）。Reference https://www.anchorpoint.app/blog/setting-up-a-self-hosted-git-server

### Database

PostgreSQL

### Can you reproduce the bug on the Gitea demo site?

No

### Description

I've been using it without problems until today。
When I access the **site administration** page, I get a 500 error 。

log：
```
2022/02/10 10:32:20 Completed GET /user/events 200 OK in 14m13.091847516s
2022/02/10 10:32:20 ...s/context/context.go:206:HTML() [E] Render failed: template: admin/dashboard:8:90: executing "admin/dashboard" at <Str2html>: invalid value; expected string
2022/02/10 10:32:20 Completed GET /admin 500 Internal Server Error in 42.299935ms
2022/02/10 10:32:21 Started GET /user/events for 192.168.5.51:55427
```

### Screenshots

![image](https://user-images.githubusercontent.com/2002202/153326611-ce4feb0c-1461-4347-9883-ea098d52a082.png)

**Comment by wxiaoguang** [comment]
Please upgrade to 1.16.1, and feel free to reopen if there is still an issue.

**Comment by wxiaoguang** [comment]
Hmm, I found that there is a bug:

Introduced by:
* #17212

Need to improve:

1. Incorrect leading `"`
2. No i18n
3. `<a>` should have `target=_blank`
4. `{{.AppVer ...` is incorrect, "AppVer" is a function, so it should be `{{AppVer ...}}`

```
				<p>"Gitea {{.RemoteVersion | Str2html}} is now available, you are running {{.AppVer | Str2html}}. Check the <a href="https://blog.gitea.io">blog</a> for more details.</p>
```
