### ISSUE TITLE
Gitpod support

### ISSUE THREAD

**Issue by ghuntley** [go-gitea/gitea#18695]
### Feature Description

:wave: Geoff here from Gitpod. 

Keen to have discussions about financially supporting Gitea going forward and getting Gitea x Gitpod well integrated.

https://github.com/gitpod-io/gitpod/issues/80#issuecomment-1033266756

> Would Gitpod be amenable to sponsoring a Gitea maintainer to submit a PR to Gitpod to support Gitea integration? 
> (I am one of the project leads of Gitea and am able to facilitate coordination with Gitea maintainers if the answer to above is yes)

Happy to raise the amount of ongoing sponsorship to Gitea from Gitpod @techknowlogick once the integration is in place as part of our open-source sustainability fund as Gitea once integrated would officially be in Gitpod's bill of materials.

<img width="1285" alt="2022-02-09_12-38-55" src="https://user-images.githubusercontent.com/127353/153108420-6abd9899-8053-4ad0-8a99-41117b93a05e.png">

Here's how Gitpod approaches supporting software that makes Gitpod possible...

https://www.gitpod.io/blog/gitpod-open-source-sustainability-fund

<img width="862" alt="2022-02-09_12-41-49" src="https://user-images.githubusercontent.com/127353/153108667-6d7ce96c-e71a-4189-a307-4f233e5880b1.png">

In addition to this can upgrade the accounts of Gitea maintainers to complementary accounts 🚀

https://github.com/gitpod-io/gitpod/issues/80#issuecomment-1033266756

**Comment by yardenshoham** [comment]
related: https://github.com/go-gitea/gitea/pull/20995

**Comment by techknowlogick** [comment]
closing now, but if any changes to Gitea are needed we can re-open and track that.
