### ISSUE TITLE
Template Rendering Error When Viewing Pull-Requests

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#18706]
### Gitea Version

1.16.1

### Operating System

Linux Debian 11

### How are you running Gitea?

We're using the Gitea binary `gitea-1.16.1-linux-amd64` from the "Releases" page.
An Nginx reverse proxy communicates with Gitea via `http+unix` (HTTP over Unix sockets).

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/rtpt-jonaslieb/23ad0a6d873ade04aac7e2ad55f0dfd2

### Description

Gitea displays a 500 server error upon viewing an unmerged pull request. The corresponding log is attached to this issue.
It does not happen with pull requests that have been merged or closed. 

The underlying issue appears to be that `PullRequestWorkInProgressPrefixes` is undefined in `sidebar.tmpl`.
The corresponding render-call is here: https://github.com/go-gitea/gitea/blob/bb77e6c12dd0c261e56d15ee0d6db7cae4d3d6f7/routers/web/repo/issue.go#L1657 
in function `ViewIssue`: https://github.com/go-gitea/gitea/blob/bb77e6c12dd0c261e56d15ee0d6db7cae4d3d6f7/routers/web/repo/issue.go#L1083

The error occurs even if `WORK_IN_PROGRESS_PREFIXES = WIP:,[WIP]` is explicitly included in the `app.ini` section `repository.pull-request`.

I'm not quite sure why the issue cannot be reproduced on the Gitea demo instance.

**Comment by rtpt-jonaslieb** [comment]
This appears to happen only if the PR refers to a broken Git state. In our case, this happened by creating a PR via the API.

**Comment by wxiaoguang** [comment]
Wait for backport

**Comment by weezlemsneezle** [comment]
Is there a workaround for this issue? After the weekend all of our Pull-Requests suddenly show this error. All Pull-Request were created through the web-interface.
We would like to continue working with Pull-Requests as soon as possible and not wait for this bugfix to be released

**Comment by wxiaoguang** [comment]
If you are affected by this bug, you can try to download the latest 1.16-dev from https://dl.gitea.io/gitea/1.16/ , it includes this fix. 

If the releases in https://dl.gitea.io/gitea/1.16/  doesn't help, then the bug you meet could be a new one.

**Comment by weezlemsneezle** [comment]
Thanks for the quick reply, I tried the dev-build and it indeed fixes the 500 HTTP-Error.
But, as predicted, the Pull-Request just says `This pull request is broken due to missing fork information.` 
I think I should open a new Issue for this but I don't even know what to title it, I can clone the Project without issues, fsck doesn't say anything and the gitea log file also has nothing special even on `debug`, only the Pull-Requests seem broken
