### ISSUE TITLE
Mail templating error when assigning PR

### ISSUE THREAD

**Issue by flozzone** [go-gitea/gitea#18704]
### Gitea Version

1.16.1

### How are you running Gitea?

Plain docker container

### Database

PostgreSQL

### Can you reproduce the bug on the Gitea demo site?

No

### Description

When a PR gets assigned to a user (`Enable notifications`), the HTML fails to be generated:

```
2022/02/10 13:44:03 ...vices/mailer/mail.go:297:composeIssueCommentMessages() [E] ExecuteTemplate [issue/assigned/body]: template: issue/assigned:12:70: executing "issue/assigned" at <.Issue.Index>: wrong type for value; expected string; got int64
```

https://github.com/go-gitea/gitea/blob/main/templates/mail/issue/assigned.tmpl#L12

The following is the source of the mail which is received:
```
<!DOCTYPE html><html><head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"><style>
		.footer { font-size:small; color:#666;}
	</style>
	
	<title>Re: [ORG/repo] [Test] test PR. (#94)</title>
</head>
```

so it seems to break exactly after the `</head>`.

Is there a way to convert the type or should `<.Issue.Index>` return strings?

**Comment by wxiaoguang** [comment]
Bug confirmed. There should be no `Escape` for IssueIndex
