### ISSUE TITLE
Wiki Sites naming in file system

### ISSUE THREAD

**Issue by mibuthu** [go-gitea/gitea#1871]
- Gitea version (or commit ref): 1.1.1 and master
- Git version: 2.7.4
- Operating system: Ubuntu Server 16.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (https://try.gitea.io/mibuthu/wiki-test/wiki/Test2%20Test)
  - [ ] No
  - [ ] Not relevant

## Description

There was a change in the way how the wiki sites with special character in the site name (e.g. spaces) are saved in the wiki git repository between 1.0 and 1.1. I know that 1.1 had some additional issues with that which were fixed in 1.1.1, but it is still not completely solved in 1.1.1 and also not in the actual master:

An example wiki entry with the site name "Test Test" was saved as "Test Test.md" in 1.0 and is saved as "Test-Test.md" since 1.1. But already existing entries from 1.0 are kept with the old name format also after the update. This makes troubles when I want to edit an old entry, I get a 500 error when I want to save the changes with the following message in the logfile:
`routers/repo/wiki.go:500 EditWikiPost()] [E] EditWikiPage: Failed to remove data/tmp/local-wiki/2/Test-Test.md: remove data/tmp/local-wiki/2/Test-Test.md: no such file or directory`
Additionally the url is not encoded correctly.

To reproduce this on try.gitea.io i created a new entry via the filesystem of the cloned wiki repository in the old style format with spaces, and this issue is reproducible with this. This is also another issue with the new format if someone creates a new wiki entry in this way.

You can find these examples in https://try.gitea.io/mibuthu/wiki-test/wiki.

In my opinion the old style format in the filesystem was better, but I can also go with the new one, but then at least some additional checks/changes are required and a migration for old and in-filesystem-created entries should be included.

What are your thoughts about this?

**Comment by chesedo** [comment]
I just had the same problem. Trying to just rename the files to have a hyphen instead of the space also ended up in two entries being created for each wiki item (with the update not being recognized). Had to clear the wiki in the end - in project settings - and start over again.

**Comment by agaida** [comment]
same here - it works sometimes for unknown reasons, if i touch the wiki next time i get a 500

**Comment by moritzheiber** [comment]
Is there a way to mitigate this issue except completely removing the wiki and re-creating it? Will this happen again with the newly created wiki?

**Comment by zeripath** [comment]
Is this still an issue

I think it affects only very early versions of Gitea.

**Comment by 6543** [comment]
@zeripath what do you mean ?

close this or not?

**Comment by lunny** [comment]
Let's close this now and please feel free to reopen it.
