### ISSUE TITLE
Tags and Releases missing after fork

### ISSUE THREAD

**Issue by noetzold** [go-gitea/gitea#18715]
### Gitea Version

1.17.0+dev-145-g165ab17a0 

### How are you running Gitea?

Verified with gitea 1.16.1 running as docker and with try.gitea.io

### Can you reproduce the bug on the Gitea demo site?

Yes

### Description

When forking a repository with Tags and Releases they are not shown under Tags or Releases. But at least the Tags can be selected in the code view. See Screenshot. Can be seen here: https://try.gitea.io/Monty/testing-fork/tags

When mirroring the same repository it is working: https://try.gitea.io/Monty/testing-mirror/tags

### Screenshots

![image](https://user-images.githubusercontent.com/36108512/153511784-c48802d1-e4b9-48c7-946d-4d083b91d770.png)

**Comment by lunny** [comment]
The tags and branches should be copied from original repository when it's forking.
