### ISSUE TITLE
Option to disable update branch by rebase

### ISSUE THREAD

**Issue by jpraet** [go-gitea/gitea#18710]
### Feature Description

In Gitea 1.16 we can update a PR branch using rebase instead of merge. (#16125)

I would like to be able to disable this option through some configuration option.
I think it's often not a good idea to rebase as it is a destructive operation:
* it causes issues when the person/people working on the PR have local changes that have not been pushed yet
* it marks review comments as outdated (#12956)

So, for the workflow in my team I would like to discourage rebasing by not showing the option in the UI.

### Screenshots

![image](https://user-images.githubusercontent.com/2212615/153483677-7f63959e-26fd-4e65-bd3e-6104d30aa3ff.png)

**Comment by jpraet** [comment]
Can it be added to the [PullRequestsConfig](https://github.com/go-gitea/gitea/blob/e0688995efdeaf5da2997779e369cc27a5ce6a5e/models/repo/repo_unit.go#L110) (AllowRebaseUpdate)?
Should it default to true or to false?

**Comment by lunny** [comment]
> Can it be added to the [PullRequestsConfig](https://github.com/go-gitea/gitea/blob/e0688995efdeaf5da2997779e369cc27a5ce6a5e/models/repo/repo_unit.go#L110) (AllowRebaseUpdate)? Should it default to true or to false?

I think yes, it could be in that struct. To keep compatible as old version, it should be `true`.
