### ISSUE TITLE
Migration from 1.15 to 1.16 fails on webauthn table

### ISSUE THREAD

**Issue by ashimokawa** [go-gitea/gitea#18727]
### Gitea Version

1.16.1

### Git Version

 2.30.2

### Operating System

Debian 11

### How are you running Gitea?

Self-compiled from https://codeberg.org/Codeberg/gitea/src/branch/codeberg-1.16

### Database

MySQL

### Can you reproduce the bug on the Gitea demo site?

No

### Description

When doing a test migration for coderberg.org to 1.16 in an isolated vm, the migration fails with

```
022/02/11 13:34:47 ...ations/migrations.go:465:Migrate() [I] Migration[207]: Add webauthn table and migrate u2f data to webauthn
2022/02/11 13:34:47 routers/common/db.go:33:InitDBEngine() [E] ORM engine initialization attempt #1/10 failed. Error: migrate: migration[207]: Add webauthn table and migrate u2f data to webauthn failed: Error 1406: Data too long for column 'credential_id' at row 1
```
The credential_id is a varchar(255) column.
Relaxing the sql mode would probably work but truncate the data, probably leading to u2f failing for affected users

(Might be related to #18477)

**Comment by zeripath** [comment]
Duplicate #18477

**Comment by ashimokawa** [comment]
@zeripath 

How is this a duplicate? This is a bug report about a failed database migration.

**Comment by zeripath** [comment]
Sorry I apologise I misread your message.

What db are you using?

**Comment by ashimokawa** [comment]
@zeripath 

mariadb 10.5 is the database.
The column credential_id in the newly created webauthn table is created as a varchar(255) column which is obviously too small for what is being migrated from the u2f table, so the migration fails.

The migration would probably "work" if chosing another sql_mode which allows just overflowing columns to be truncated - which then would break webauthn for affected users. That's why I pointed to the other issue which might be related - a seemingly okay migration with truncation.

**Comment by christiaangoossens** [comment]
After this update, I can no longer login and I get a 500 error, with the log message: `ers/web/auth/auth.go:218:SignInPost() [E] UserSignIn: auth source is not actived`

**Comment by christiaangoossens** [comment]
@fnetX My issue seemed to be related due to the very similar scenario and that I saw that same migration error happen, but as it's solved and probably had more to do with my outdated config, I have removed the comment. Thanks for your comment!
