### ISSUE TITLE
Empty repository show error 500

### ISSUE THREAD

**Issue by TOMeeeek** [go-gitea/gitea#18722]
### Gitea Version

1.16.1

### Git Version

2.13.6

### Operating System

Ubuntu server 20.04

### How are you running Gitea?

Installed from binary

### Database

MySQL

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/TOMeeeek/554a4d6ed4a6336683904887c086f0e4

```
2022/02/11 12:53:54 ...ers/web/repo/view.go:860:renderCode() [E] GitRepo.IsEmpty: check empty: exit status 129 - usage: git rev-list [OPTION] <commit-id>... [ -->
          limiting output:
            --max-count=<n>
            --max-age=<epoch>
            --min-age=<epoch>
            --sparse
            --no-merges
            --min-parents=<n>
            --no-min-parents
            --max-parents=<n>
            --no-max-parents
            --remove-empty
            --all
            --branches
            --tags
            --remotes
            --stdin
            --quiet
          ordering output:
            --topo-order
            --date-order
            --reverse
          formatting output:
            --parents
            --children
            --objects | --objects-edge
            --unpacked
            --header | --pretty
            --abbrev=<n> | --no-abbrev
            --abbrev-commit
            --left-right
            --count
          special purpose:
            --bisect
            --bisect-vars
            --bisect-all
```

### Description

After upgrading from Gitea 1.15.9 to 1.16.1, a 500 error is reported when entering an empty repository. When downgrading to 1.15.9 again everything is without problems.

**Comment by wxiaoguang** [comment]
Confirmed, it is the case. But git document never mentioned that.

If we run `git --all` on an empty git, old git would report errors.

**Comment by lunny** [comment]
> Confirmed, it is the case. But git document never mentioned that.
> 
> If we run `git rev-list --all` on an empty git, old git would report errors.

What's the old git version?

**Comment by zeripath** [comment]
Can we use:

```
git show-ref HEAD
```

Instead.

Btw @lunny I missed your reply on my comment:

```
git rev-list --all 
```

Still just uses the HEAD branch. If we wanted to check if a repo had any branches or tags we'd need to use for-each-ref or the like.

**Comment by wxiaoguang** [comment]
> What's the old git version?

Author reported `2.13.6`, I tried `2.11.x`, they all have this bug. It seems that `2.3x` doesn't have the bug, but I do not know which version fixed it.

**Comment by lunny** [comment]
> git show-ref HEAD

`git show-ref HEAD` is not work from me.
