### ISSUE TITLE
[Bug Report]  Issue and Pull Request Duplications

### ISSUE THREAD

**Issue by AaronS8** [go-gitea/gitea#18724]
### Gitea Version

1.171

### Git Version

2.33

### Operating System

Windows 10

### How are you running Gitea?

using from gitea downloads

### Database

MSSQL

### Can you reproduce the bug on the Gitea demo site?

Yes

### Details
  Got Duplicated Pull request upon further testing found out if I double clicked when I'm creating a pull request, the pull request got duplicated, I found the same on issues too.

### LIng to try.gitea

https://try.gitea.io/arons8/ComTest/pulls

**Comment by wxiaoguang** [comment]
It's a well-known problem:

* https://github.com/go-gitea/gitea/issues/17111

**Comment by AaronS8** [comment]
Sorry Didn't see that.
