### ISSUE TITLE
Links under repository sidebar stay "localhost:3000"

### ISSUE THREAD

**Issue by poVoq** [go-gitea/gitea#18757]
### Gitea Version

0.16.1

### Git Version

latest debian bullseye

### Operating System

debian bullseye

### How are you running Gitea?

Official binary release behnd Nginx reverse-proxy

### Database

MySQL

### Can you reproduce the bug on the Gitea demo site?

No

### Description

When logged in on the right-side link list to the repositories does not properly replace "localhost:3000" with the actual domain name.

Everywhere else it seems to work as intended.

### Screenshots

![giteabug](https://user-images.githubusercontent.com/940360/153778192-c57a7073-036a-4605-aade-fd9419d19fd4.png)

**Comment by techknowlogick** [comment]
Please set the ROOT_URL to the expected result
