### ISSUE TITLE
Migration[209]: Increase WebAuthentication CredentialID size to 410

### ISSUE THREAD

**Issue by azhai** [go-gitea/gitea#18759]
### Gitea Version

1.17-dev-157

### Git Version

2.34.1

### Operating System

CentOS 7

### How are you running Gitea?

```gitea web```

### Database

MySQL

### Can you reproduce the bug on the Gitea demo site?

Yes

### Description

2022/02/14 10:30:51 routers/common/db.go:34:InitDBEngine() [I] Backing off for 3 seconds
2022/02/14 10:30:54 routers/common/db.go:27:InitDBEngine() [I] ORM engine initialization attempt #3/10...
2022/02/14 10:30:54 cmd/web.go:152:runWeb() [I] PING DATABASE mysql
2022/02/14 10:30:54 ...ations/migrations.go:467:Migrate() [I] Migration[209]: Increase WebAuthentication CredentialID size to 410
2022/02/14 10:30:54 routers/common/db.go:33:InitDBEngine() [E] ORM engine initialization attempt #3/10 failed. Error: migrate: migration[209]: Increase WebAuthentication CredentialID size to 410 failed: Error 1146: Table 'db_gitea.u2f_registration' doesn't exist

**Comment by lunny** [comment]
I think we haven't drop the table. Why it's missed in your instance?

**Comment by azhai** [comment]
```git reset --hard 1b1658d8875e42f0c5130ddfe9c7339e10bf5c20```
Then rebuild the project, the bug disapper.

**Comment by azhai** [comment]
> I think we haven't drop the table. Why it's missed in your instance? Oh, right. It's possible.

Because I installed the gitea in v1.16-dev some monthes ago.
