### ISSUE TITLE
Error "TreePath cannot be empty" when creating a new file and using autocomplete 

### ISSUE THREAD

**Issue by AntoineFr** [go-gitea/gitea#18751]
### Gitea Version

1.17.0+dev-159-ga39287cd4

### Operating System

Windows 11

### Browser Version

Firefox 97.0

### Can you reproduce the bug on the Gitea demo site?

Yes

### Description

When you create a New file using Gitea's UI and you select an old file name in the autocomplete dropdown instead of writing it to the field, and you commit the changes, the following error is shown : `TreePath cannot be empty.`.

### Screenshots

![image](https://user-images.githubusercontent.com/4655583/153762604-90d05b95-fb70-4e44-b0ec-790e96754b7a.png)

**Comment by AntoineFr** [comment]
Still reproducible on the Gitea demo site with version 1.17.0+dev-429-g695c4b4b0

**Comment by lunny** [comment]
I cannot reproduce it in my local instance now. I think it has been resolved.

**Comment by AntoineFr** [comment]
> I cannot reproduce it in my local instance now. I think it has been resolved.

I can't reproduce it on the Gitea demo website so it should be fixed!
