### ISSUE TITLE
GitRepo.IsEmpty: check empty: exit status 129 - usage: git rev-list [OPTION] <commit-id>... [ -- paths... ]

### ISSUE THREAD

**Issue by zdwork** [go-gitea/gitea#18768]
### Gitea Version

1.16.1

### Git Version

git version 1.8.3.1

### Operating System

centos

### How are you running Gitea?

make all

./gitea web

### Database

MySQL

### Can you reproduce the bug on the Gitea demo site?

Yes

**Comment by lunny** [comment]
duplicated with #18722
