### ISSUE TITLE
Editing Repositories via API ignores default_merge_style

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#18773]
### Gitea Version

1.16.1

### How are you running Gitea?

Using the Linux x64 binaries from the releases page.

### Can you reproduce the bug on the Gitea demo site?

Yes

### Description

When editing repos via the API, the value of `default_merge_style` is ignored.

Querying the API with curl/jq before the change:
```
$ export GITEA_ACCESS_TOKEN=[...]
$ curl -s -H "Authorization: token $GITEA_ACCESS_TOKEN" https://try.gitea.io/api/v1/repos/7CLfteiIYWtD/test | jq .default_merge_style
"merge"
```

Trying to change the setting via the API:
```
$ curl -s -H "Authorization: token $GITEA_ACCESS_TOKEN" -X PATCH -H 'Content-Type: application/json' -d '{"default_merge_style": "rebase"}' https://try.gitea.io/api/v1/repos/7CLfteiIYWtD/test | jq .default_merge_style
"merge"
```
This **should** have returned `"rebase"`.

After changing the default merge style through the UI:
```
$ curl -s -H "Authorization: token $GITEA_ACCESS_TOKEN" https://try.gitea.io/api/v1/repos/7CLfteiIYWtD/test | jq .default_merge_style
"rebase"
```

**Comment by noerw** [comment]
I'm pretty sure has the same cause as described in https://github.com/go-gitea/gitea/issues/19069#issuecomment-1075517026

**Comment by jolheiser** [comment]
Parent issue #13622
