### ISSUE TITLE
Upgrade from 1.15 to 1.16.1 fails, webauthn err

### ISSUE THREAD

**Issue by bourbonspecial** [go-gitea/gitea#18778]
### Gitea Version

1.16.1

### Operating System

Windows

### How are you running Gitea?

Pre-built binaries on windows 7. Run from cmd.

### Database

SQLite

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/bourbonspecial/7794da6c8dbc39fe958973f8f570e33c

### Description

Im trying to upgrade from 1.15.11 to 1.16.1 but getting some errors which seem to be related to the introduction of webauthn in 1.16 (see linked log).

I'd previously tried to upgrade to upgrade to 1.16 RC1 but that failed (I can't remember why unfortunately) so I rolled back by changing the version number in the db. I guess this could be the issue as the previous upgrade attempt and my ham-fisted roll back could have left the db in a bad state?

**Comment by zeripath** [comment]
yeah I think that's a possible unfortunately. You'll need to drop the webauthn_credential table before reattempting

Now... there's a bug in v208.go migration so we have merged a fix which will be in 1.16.2 - but you should be able to jump to the latest build of 1.16 which will become 1.16.2 v. soon at https://dl.gitea.io/gitea/1.16 (or use the docker tag 1.16-dev)

**Comment by bourbonspecial** [comment]
I dropped the webauthn_credential table and the migration mostly worked, though previously installed keys weren't working. Removing then re-adding my key worked so I'll just get my users to do that.

Thanks for your help, and for your work getting webauthn ready for 1.16 :)

**Comment by zeripath** [comment]
Did you use: https://dl.gitea.io/gitea/1.16

**Comment by bourbonspecial** [comment]
I used https://dl.gitea.io/gitea/1.16.1/gitea-1.16.1-windows-4.0-amd64.exe

**Comment by zeripath** [comment]
could you try https://dl.gitea.io/gitea/1.16/gitea-1.16-windows-4.0-amd64.exe ?

**Comment by bourbonspecial** [comment]
Sorry for being slow to get back, Im on holiday for a couple of weeks so will try it out when Im back.

**Comment by wxiaoguang** [comment]
Outdated
