### ISSUE TITLE
When merging a PR and deleting the branch the info box text is not correct.

### ISSUE THREAD

**Issue by noetzold** [go-gitea/gitea#18785]
### Gitea Version

1.17.0+dev-172-g616146f90

### How are you running Gitea?

https://try.gitea.io/

### Can you reproduce the bug on the Gitea demo site?

Yes

### Description

Kind of a cometic Issue
The text in the green info box is not correct when deleting a branch while merge a PR. See the Screenshot. 

Only the organization is mentioned but not the repository:
"Branch 'Monty/test2' has been deleted."
 It should be:
"Branch 'Monty/testing-Notifications test2' has been deleted."

Reproduce:
-Create a PR
-Create a merge commit and check "Delete Branch"
-See the green Box

### Screenshots

![image](https://user-images.githubusercontent.com/36108512/154285858-dc0a25b0-d525-48ba-8e4b-d90bb8d10882.png)

**Comment by fnetX** [comment]
I think it's supposed to refer to which repo the branch was from, like you would do locally with multiple remotes. It's obvious the branch belongs to this kind of repo, but it might have been from a fork (and then say "user-with-fork/branch" has been deleted)

**Comment by noetzold** [comment]
OK, might be a matter of taste. It is just that Gitea identifiers a repro usually as organization/repro. I just came across this because I had a repro with the same name as the branch and thought for a second the branch has been deleted.

When the message is as indented, please close this Issue

**Comment by JVimes** [comment]
Glad this was confirmed as a bug. Thanks.
