### ISSUE TITLE
Internal Server Error when listing locks or accessing locked files in web view

### ISSUE THREAD

**Issue by eNBeWe** [go-gitea/gitea#18782]
### Gitea Version

1.16.1

### Git Version

2.25.1

### Operating System

Linux (Ubuntu Server 20.04.3)

### How are you running Gitea?

Binary installation very similar to instructions from the docs.
Service is run through systemd.

### Database

SQLite

### Can you reproduce the bug on the Gitea demo site?

No (since LFS is not available there)

### Description

I have a repository with a few locked files (xlsx).
As soon as I try to access the file through the web interface, I receive a HTTP 500 Internal Server Error. I can download the the file when I use the "/raw"-Url.
When I try to show the locked files in the repository from the settings, I also get a HTTP 500.

I tried to reproduce the issue on another server running Gitea 1.15.6 and the issue didn't occur. I will try to update the server and see if it breaks.

**Comment by lunny** [comment]
What's locked files? Did you mean git LFS Lock?

**Comment by eNBeWe** [comment]
Yes, sort of. The files are marked as lockable by GIT LFS, but the actual files are not tracked by LFS.
So the entry in the .gitattributes is just 
`*.data lockable`

**Comment by parnic-sks** [comment]
We are seeing this part of the reported issue:

> As soon as I try to access the file through the web interface, I receive a HTTP 500 Internal Server Error.

fixed in 1.16.2. However, this part:

> When I try to show the locked files in the repository from the settings, I also get a HTTP 500.

is still a problem.
