### ISSUE TITLE
invalid character '\x00' looking for beginning of object key string

### ISSUE THREAD

**Issue by miketgv** [go-gitea/gitea#18792]
### Gitea Version

1.16.1

### How are you running Gitea?

gitea is runing from systemd on ubuntu 18

### Database

MySQL

### Can you reproduce the bug on the Gitea demo site?

No

### Description

Not sure after what update happened but my old repositories that I wanted to access fails with 500 Internal server error.
This error can be found in the log file:
2022/02/17 09:59:24 ...ules/context/repo.go:351:repoAssignment() [E] GetUserRepoPermission: invalid character '\x00' looking for beginning of object key string

**Comment by lunny** [comment]
https://blog.gitea.io/2021/12/gitea-1.15.8-is-released/, see the break part.

**Comment by miketgv** [comment]
fixed, thanks
