### ISSUE TITLE
Merge deploy keys from gogs

### ISSUE THREAD

**Issue by tboerger** [go-gitea/gitea#188]
Maybe somebody wants to jump in and integrate https://github.com/gogits/gogs/commit/39a3b768bc8b0288cb4aa91d27485f46cfbfeb29 for adding deployment keys?

**Comment by lunny** [comment]
Yes. @tboerger

**Comment by vtolstov** [comment]
I'm try

**Comment by tboerger** [comment]
Awesome!

**Comment by tboerger** [comment]
Project is dead, close.
