### ISSUE TITLE
golangci-lint should ignore node_modules

### ISSUE THREAD

**Issue by silverwind** [go-gitea/gitea#18803]
CI failure seen on https://drone.gitea.io/go-gitea/gitea/51286/1/6

It seems golangi-lint tries to access files in `node_modules` which is completely unnecessary and likely a reason for its long runtime. It might be possible to pass a list of files to it via https://github.com/golangci/golangci-lint/issues/301#issuecomment-441311986, thought I'm not sure whether that usage actually works (https://github.com/golangci/golangci-lint/issues/2568).

I recently added the `skip-dirs` option at https://github.com/go-gitea/gitea/blob/1ab88da0e460a076a95dcd2cad812e707da3acc9/.golangci.yml#L27-L30 but it does not seem to help because not all of their "linters" seem to honour the option (https://github.com/golangci/golangci-lint/issues/913).

**Comment by lunny** [comment]
So maybe we could run backend lint before frontend lint in CI to avoid that?

**Comment by silverwind** [comment]
That sounds like a workaround that will only work on CI. It needs to work locally too.

**Comment by lunny** [comment]
I think this has been resolved. If it's not, please feel free to reopen it.

**Comment by zeripath** [comment]
Fixed by #18708

**Comment by silverwind** [comment]
Not really fixed with that, `skip-dirs` only has effect on some linters, and those rare CI failures should still be able to happen currently.

**Comment by taagomag** [comment]
So is there any solution to skip node_modules? It seems that this issue is turning in circles since 2 years...

**Comment by silverwind** [comment]
No, it needs to happen in golang first: https://github.com/golang/go/issues/42965.
