### ISSUE TITLE
status/500 template seems can not loads

### ISSUE THREAD

**Issue by almas** [go-gitea/gitea#18819]
### Gitea Version

1.16.1

### Git Version

2.25.1

### Operating System

Ubuntu 20.04 server

### How are you running Gitea?

With systemd with RUN_MODE=prod configuration with 64 bit binary for linux.

### Database

MySQL

### Can you reproduce the bug on the Gitea demo site?

No

### Description

Message: "Unable to find status/500 template"

When I create a custom template with error. Then text above shown without any style.

It might not bug. But just to be sure I reporting this.

**Comment by trepmag** [comment]
In my case I was overriding the `head_navbar.tmpl` which was throwing a `Render failed: template: base/head_navbar...` under 1.16...

Check you `gitea.log`...

**Comment by qduff** [comment]
I seem to have the same issue here. I first created and modified head_navbar.tmpl, and it worked perfectly, however when I create footer_content.tmpl and paste in the contents of the footer_content.tmpl that is in this repo, I receive a `Unable to find status/500 template` error. 

I am interested to know if anyone also has this issue.

**Comment by lunny** [comment]
Please check your custom templates are correct.
