### ISSUE TITLE
[Translation] Mongolian Cyrillic language translation

### ISSUE THREAD

**Issue by almas** [go-gitea/gitea#18818]
Please add a Mongolian Cyrillic language translation to Crowdin.

Locale: mn_MN

**Comment by lunny** [comment]
I can only find `Mongolian`, but no `Mongolian Cyrillic` in the crowdin language list. And there is no customized language name option. Should I add `Mongolian`?

**Comment by almas** [comment]
Yes please. I just wanted to give an information that language is Cyrillic. 😅

**Comment by lunny** [comment]
Could you tell me your name in crowdin so that I can add you as proofreader .

**Comment by almas** [comment]
My name on Crowdin is "Almas". Thanks.
https://crowdin.com/profile/almas

**Comment by lunny** [comment]
@almas done.
