### ISSUE TITLE
Gitea panics on title page(public)

### ISSUE THREAD

**Issue by BRNSystems** [go-gitea/gitea#18829]
### Gitea Version

https://github.com/go-gitea/gitea/commit/83c9035971e4b594686391a7ff052a7d1fe13771

### Git Version

2.32.0

### Operating System

Ubuntu 21.10(server)

### How are you running Gitea?

Firstly used main developement build from dl.gitea.io then build own with no change

### Database

MySQL

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/BRNSystems/0c2efb2cd808a4f9b93fdf7d9476a8ff

### Description

Was trying to access gitea and found blank page, then checked logs and filed this issue.

**Comment by lunny** [comment]
Looks like actions' repository missed for some reason. When deleting a repository, related actions should be deleted as well.

**Comment by BRNSystems** [comment]
Oh, I see. I accidentally created a repo while migrating and deleted the folder. Then I deleted one entry in mysql. What other entries should I delete?

**Comment by BRNSystems** [comment]
Ok, I deleted all entries where repo ID was 27.
Thanks
