### ISSUE TITLE
Notification emails display text lists incorrectly

### ISSUE THREAD

**Issue by gayprogrammer** [go-gitea/gitea#1883]
- Gitea version (or commit ref): 1.1.1+2-g2854c8a
- Git version: 2.12.2
- Operating system: Windows Server 2012
- Database (use `[x]`):
  - [x] MSSQL
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Not relevant
- Log gist: Not relevant

Notification emails display text lists incorrectly. Emails display lists with an asterisk ('*') instead of a dash ('-'). I am using plain text emails. 

It makes sense that lists should be sent in their original form. Since I type markdown lists with the dash, I think that emails should at least reflect the plain text markdown version.

**Comment by lunny** [comment]
I think this has been fixed. Please feel free to reopen it.
