### ISSUE TITLE
BOMs are treated as illegal escape sequences in at least the diff view /commit/*

### ISSUE THREAD

**Issue by ReeceSX** [go-gitea/gitea#18837]
### Gitea Version

v1.16.1

### Description

The 4th file down within [this](https://gitea.reece.sx/AuroraSupport/HelloAurora/commit/52338d1e3f5460dacdbc6a871925fdbc631a730c) commit presents the illegal characters escaped warning icon in the line column; and renders `[+FEFF]` which isn't even the complete BOM sequence. The relevant BOM is nothing more than a UTF-8 hint, `EF BB BF`, truncated to 0xFEFF in the editor 

### Expected behavior 

None.
The BOM sequence should be respected in the lexer and _possibly_ used as a conversion hint to translate the doucment to the html charset, other than that, the BOM should be dropped. Given the translation from the UTF-8 BOM to the generic BOM codepoint, it should be safe to assume the document was safely translated, and this warning is spurious. 

### Screenshots

![image](https://user-images.githubusercontent.com/97978250/154853696-64aa27aa-601a-4ddc-9cf9-d5330ddde687.png)

**Comment by zeripath** [comment]
Please provide testcase on try.gitea.io.
