### ISSUE TITLE
Nickname for repo

### ISSUE THREAD

**Issue by bigsk05** [go-gitea/gitea#18832]
### Feature Description

I think using the repo path as the repo name is not free enough and not easy to understand. We can create a nickname function, and enter the name with special symbols such as spaces as the name of the repo display, like gitlab.
我觉得使用仓库路径作为仓库名不够自由，不便于展示。可以推出一个昵称功能，输入可以带空格等特殊符号的名字作为仓库展示的名字，像GitLab一样

**Comment by newhinton** [comment]
@techknowlogick Has this been implemented? If so, is it in gitea 1.19, or does it need to be enabled? Thanks!

**Comment by jolheiser** [comment]
I believe this was closed in a bulk-change last year during a cleanup process, it is not currently implemented. 

However, it appears #9032 is asking for the same thing, so we can keep this closed and follow that issue instead.
