### ISSUE TITLE
Clarification: simple Merge Request with the API?

### ISSUE THREAD

**Issue by ekianjo** [go-gitea/gitea#18842]
Hi, I am finding the API very useful to execute a bunch of actions, however I can't figure out how to use the pull request/merge part of the API - the Swagger documentation for that one is far from being very explicit. 
Could you provide an example?

**Comment by ekianjo** [comment]
Thanks let me check this out! @eladyn

**Comment by ekianjo** [comment]
Hi @eladyn I tried your suggestion but I seem to be getting a 422 error with the following message:

$message
[1] "[Head]: Required"

Even though I entered the branch name in the head variable as "head":"username:branch_name" - any idea why I might be getting this error?

**Comment by eladyn** [comment]
@ekianjo Could you post the full request / payload, you tried this with (ofc with private information stripped, if any)? It seems there is something it doesn't like about your JSON.

**Comment by 6543** [comment]
just play around with https://try.gitea.io/api/swagger#/repository/repoMergePullRequest ...
