### ISSUE TITLE
Assign multiple people to an issue

### ISSUE THREAD

**Issue by gayprogrammer** [go-gitea/gitea#1884]
- Gitea version (or commit ref): 1.1.1+2-g2854c8a
- Git version: 2.12.2
- Operating system: Windows Server 2012
- Database (use `[x]`):
  - [x] MSSQL
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Not relevant
- Log gist: Not relevant

I would like the ability to assign multiple people to an issue. This is possible on GitHub by default, so I think it is a reasonable feature to add. 

Is there a technical reason we can not add this?

**Comment by bkcsoft** [comment]
No technical reason no. New table `Assignees` that links `Issue => User`. And a migration to move all the current Assignees

**Comment by lcges** [comment]
Will be implemented in version 1.3?

**Comment by lunny** [comment]
No people working on this.

**Comment by kolaente** [comment]
I'll start working on this.

**Comment by kolaente** [comment]
It's implemented with #3705!!

**Comment by mckaygerhard** [comment]
can be this backported to 1.4 branch?

**Comment by mckaygerhard** [comment]
ah i answered by myselft by see the #3705 and teh covereage impact.

**Comment by ptman** [comment]
Is it possible to limit this? I fear that having multiple assignees will make people think "oh, someone else is also assigned, so I can focus on other stuff".

**Comment by bkcsoft** [comment]
@ptman That sounds like a communication issue, not a code issue :slightly_smiling_face:

**Comment by mckaygerhard** [comment]
also limit this will cause code complication, due wil/must be a per repository attribute/feature

**Comment by techknowlogick** [comment]
Now that #3705 has been merged, can this issue be closed?
