### ISSUE TITLE
Warning on upgrade from 1.15.11 to 1.16.0

### ISSUE THREAD

**Issue by lds-lds** [go-gitea/gitea#18843]
### Gitea Version

1.15.11

### Git Version

2.7.4

### Operating System

ubuntu/xenial

### How are you running Gitea?

i run gitea by systemd /etc/systemd/system/gitea.service

```
[Unit]
Description=Gitea (Git with a cup of tea)
After=syslog.target
After=network.target
After=mysqld.service


[Service]

LimitMEMLOCK=infinity
LimitNOFILE=65535
RestartSec=2s
Type=simple
User=git
Group=git
WorkingDirectory=/home/git/gitea
ExecStart=/home/git/gitea/gitea web
Restart=always
Environment=USER=git HOME=/home/git

[Install]
WantedBy=multi-user.target


```

### Database

MySQL

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/lds-lds/f0bc87b04d5153bf72020c8715b5b5a7

### Description

Hello
I just updated gitea from 1.15.11 to 1.16.0 and I get many warnings (in log gist)
Is this normal or do i need to correct something in the database?
note that I have access to gitea without any error

**Comment by lunny** [comment]
It's normal. You upgraded successfully.

**Comment by lds-lds** [comment]
Ok Thanks :)
