### ISSUE TITLE
Notification emails for comments not working

### ISSUE THREAD

**Issue by gayprogrammer** [go-gitea/gitea#1885]
- Gitea version (or commit ref): 1.1.1+2-g2854c8a
- Git version: 2.12.2
- Operating system: Windows Server 2012
- Database (use `[x]`):
  - [x] MSSQL
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Not relevant
- Log gist: Not relevant

Notification emails for comments not working. I expect that emails should be sent to the issue creator and assignee for comments on that issue. 

Is this a feature that has not been implemented? Will there be a notification email settings menu to select which notifications are sent? Will there be a 'Subscribe' button added to issues?

**Comment by lunny** [comment]
I think this is a not implementation feature. @andreynering

**Comment by gayprogrammer** [comment]
I think this is related to issue #145 .

**Comment by lunny** [comment]
@razzintown yes, you are right.
