### ISSUE TITLE
How to rebuild the repository code index 

### ISSUE THREAD

**Issue by TanxiangCode** [go-gitea/gitea#18853]
### Gitea Version

1.16.1

### Git Version

2.32.0.2

### Operating System

Windows Server 2019 Datacenter

### How are you running Gitea?

Run gitea-1.16.1-windows-4.0-amd64.exe using Windows Service

### Can you reproduce the bug on the Gitea demo site?

No

### Description

Now, when I search for the code, most of them cannot be searched. I need to rebuild the es index or what should I do. 

### Screenshots

![image](https://user-images.githubusercontent.com/42427662/155048642-74fa3d73-9095-46a5-8b5b-38cb421c7a40.png)

**Comment by lunny** [comment]
You can just delete the index files and restart Gitea

**Comment by lunny** [comment]
There is a button on repository setting to reindex the code index.
