### ISSUE TITLE
Issues sort by Type menu does not work

### ISSUE THREAD

**Issue by gayprogrammer** [go-gitea/gitea#1886]
- Gitea version (or commit ref): 1.1.1+2-g2854c8a
- Git version: 2.12.2
- Operating system: Windows Server 2012
- Database (use `[x]`):
  - [x] MSSQL
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes
- Log gist: Not relevant

In the issues list, the 'Type' sorting menu is broken. None of the options affect the sorting or searching of the issues.

**Comment by ghost** [comment]
Not sure if I should create a new issue but, sorting by **Recently updated/Least recently updated**, seems to have the same effect as sorting **Newest/Oldest**.

GitHub shows `updated 3 hours ago` next to `opened 7 months ago by someuser` when sorting by last update, so I wonder if this is actually implemented in Gitea.

**Comment by gayprogrammer** [comment]
@megadr01d It sounds like a new issue would be good since there is now a PR (#1914) that would close this issue.

**Comment by ghost** [comment]
@razzintown Okay, thanks, I will. And sorry for the noise, you can close this when ready.
