### ISSUE TITLE
Templates disappeared on latest reinstall and is not working

### ISSUE THREAD

**Issue by gayprogrammer** [go-gitea/gitea#1887]
- Gitea version (or commit ref): 1.1.1+2-g2854c8a
- Git version: 2.12.2
- Operating system: Windows Server 2012
- Database (use `[x]`):
  - [x] MSSQL
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Not relevant
- Log gist: Not relevant

The folder for Templates disappeared when I started with a fresh install from the last version. I re-added the Templates folder to the gitea custom directory, but it caused gitea to not start. I currently use a custom Templates folder with only a 'public' folder inside, and that works as expected.

Is the Templates feature working? How do I get my installation to generate a new Templates folder?

**Comment by lunny** [comment]
The custom templates should work. Could you show some start error log?

**Comment by gayprogrammer** [comment]
I do not have any errors in my log. What log level setting should I set in my config?

I do not have a templates folder in my install directory to properly test. Is there a way I can generate one?

I copied in an old copy of `custom/templates/base/head.tmpl` and in the web browser, I got this message:
`html/template:base/head:77:12: no such template "inject/head"`

**Comment by lunny** [comment]
@razzintown It seems this is a Gogs' template. Since Gitea has forked half an year, many things are different.

**Comment by gayprogrammer** [comment]
> The custom templates should work. 

@lunny Thank you for your help. Where is Gitea template? My folder has no template.

**Comment by bkcsoft** [comment]
@razzintown The binary that we ship has all templates built into the binary (`make bindata && TAGS="bindata" make build`). The templates are in this repo ( https://github.com/go-gitea/gitea/tree/master/templates )
