### ISSUE TITLE
Default gitea custom_config in docker rootless images broken

### ISSUE THREAD

**Issue by OCram85** [go-gitea/gitea#18877]
### Gitea Version

1.16.1

### Git Version

2.30.2

### Operating System

Ubuntu 20.04 LTS

### How are you running Gitea?

Running gitea with docker-rootless image `gitea/gitea:1.16.1-rootless`

### Database

SQLite

### Can you reproduce the bug on the Gitea demo site?

No

### Description

Just started a new gitea instance like described to investigate the restore process for docker rootless instances.
Like described in the 1.16.1 release article I tried to run the dump command without the `-c` parameter.

It seems like the default values are fine  but not recognized by gitea. If you are running:

- `/app/gitea/gitea dump` ,  `/app/gitea/gitea --help` 
- `/usr/local/bin/gitea dump` / `/usr/local/bin/gitea --help` 
- `gitea dump` / `gitea --help` 

You get different config outputs which could contain strange custom_conf:

```
CustomConf:  /var/lib/gitea/custom/"/etc/gitea/app.ini"
```

So you still need to provide a valid `-c` argument on each 3 cases.

### Screenshots

![image](https://user-images.githubusercontent.com/13993700/155521426-1dafb199-3e03-49b4-81a6-7b0d65b8d4a4.png)

![image](https://user-images.githubusercontent.com/13993700/155522177-fb5e3e05-1e6e-43ba-835b-136d297d1490.png)

![image](https://user-images.githubusercontent.com/13993700/155523347-115a5f82-82b5-4ab2-9468-5acdef49b1c4.png)

**Comment by zeripath** [comment]
This is a duplicate and has already been fixed and will be out in 1.16.2 

In the meantime consider using the 1.16-dev-rootless tag.
