### ISSUE TITLE
From Gogs, migration v189 failed v15 -> v16.2 "UQE_login_source_login_source_name_key" does not exist

### ISSUE THREAD

**Issue by mrkeuz** [go-gitea/gitea#18882]
### Gitea Version

v1.16.2

### Git Version

2.30.2

### Operating System

Linux (Docker)

### How are you running Gitea?

Running in docker

### Database

PostgreSQL

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://github.com/go-gitea/gitea/files/8136587/migration_v189_error.log

### Description

After upgrade from `v15` → `v16.2` faced with migration error with:
```shell
...
 2022/02/25 00:13:00 routers/common/db.go:33:InitDBEngine() [E] ORM engine initialization attempt #2/10 failed. Error: migrate: migration[189]: Unwrap ldap.Sources failed: pq: index "UQE_login_source_login_source_name_key" does not exist
...
```
Full log in attach: [migration_v189_error.log](https://github.com/go-gitea/gitea/files/8136587/migration_v189_error.log)

My table structure was (recently version ago migrated from gogs): 

  <details>
    <summary>Spoiler</summary>

```sql
create table login_source
(
  id              int8 default nextval('login_source_id_seq'::regclass) not null
    constraint login_source_pkey
      primary key,
  type            int8,
  name            text
    constraint login_source_name_key
      unique,
  is_actived      bool                                                  not null,
  is_default      bool,
  cfg             text,
  created_unix    int8,
  updated_unix    int8,
  is_sync_enabled bool default false                                    not null,
  is_active       bool default false                                    not null
);

create index "IDX_login_source_is_actived"
  on login_source (is_actived);

create index idx_login_source_uqe_login_source_login_source_name_key
  on login_source (name);

create index uqe_login_source_login_source_name_key
  on login_source (name);
```
  
  </details>

Can provide some additional info.

WORKAROUND:
I had empty `login_source` table. So be CAREFUL with data! 

- Leave only columns in `login_source`
  ```sql
  login_source.id
  login_source.type
  login_source.cfg
  login_source.is_active -- as i understand should renamed from is_actived
  login_source.name
  ```

- Skip v189 migration via update table `version.version = 190`

**Comment by 0mhu** [comment]
Hello,
are there any solutions to this? I'm experiencing the same problem.

**Comment by 0mhu** [comment]
I folled the steps you mentioned as a workaround.
However, I now get 

`. Error: sync database struct error: pq: index "IDX_login_source_uqe_login_source_login_source_name_key" does not exist`

I'm not too much into databases, but as far as I see, there is an index with that name. So I don't really understand the error.

Btw, I also upgraded from gogs a few months ago.

**Comment by wxiaoguang** [comment]
Do you have content in the `login_source` table? If not, you can safely drop this table, and Gitea will re-create a new (correct) table.

**Comment by 0mhu** [comment]
Yes. My `login_source` table is empty. I deleted it, as you've suggested. v1.16.5 does now start and seems to work.
