### ISSUE TITLE
CI Integration

### ISSUE THREAD

**Issue by hughesjs** [go-gitea/gitea#1889]
I know this would be very difficult to implement and is by no means a small request, but might it be possible to integrate Continuous Integration within Gitea itself such that any unit tests in a project get run every time something is comitted?

**Comment by strk** [comment]
James this is already working with drone (github.com/drone/drone)
The only part missing is automatically reporting build status near
the commits view and the PR view. But Drone can run on every commit
in all branches and pull requests

**Comment by lafriks** [comment]
@strk it does show status in commits view but not in PR view currently

**Comment by strk** [comment]
it could be useful to setup a fake service to showcase on try.gitea.io - ideas about doing that ?

**Comment by lunny** [comment]
Maybe we can run a test drone service and all try.gitea.io project could visit it.

**Comment by strk** [comment]
That would be great !

**Comment by bkcsoft** [comment]
Duplicate of https://github.com/go-gitea/gitea/issues/996
