### ISSUE TITLE
cron.update_mirrors updates only 51 mirrors in one run

### ISSUE THREAD

**Issue by somera** [go-gitea/gitea#18895]
### Gitea Version

1.16.2

### Git Version

2.25.1

### Operating System

Ubuntu 20.04.4

### How are you running Gitea?

Precompiled [gitea-1.16.2-linux-amd64](https://github.com/go-gitea/gitea/releases/download/v1.16.2/gitea-1.16.2-linux-amd64)

### Database

PostgreSQL

### Can you reproduce the bug on the Gitea demo site?

No

### Description

In #18607 I reported problem with the ron.update_mirrors. Now it's wioking, but the cron is updating only 51 mirrors.

Status after Gitea update

![image](https://user-images.githubusercontent.com/8334250/155601563-caf1de4f-034a-4e2a-9bc9-7b385a62f075.png)

Status after the first run Gitea updates 51 mirrors.

![image](https://user-images.githubusercontent.com/8334250/155601647-be7afc27-ed0f-4049-89a9-df0f2a22fdde.png)

why only 51?

Status after the second run Gitea updates 51 mirrors.

![image](https://user-images.githubusercontent.com/8334250/155601695-6839d25d-93b6-4445-9343-f62f7c4979e5.png)

why only 51?

51 is same like some days ago: https://github.com/go-gitea/gitea/issues/18607#issuecomment-1044120194

This

```
[mirror]
; Default interval as a duration between each check
DEFAULT_INTERVAL = 8h
; Min interval as a duration must be > 1m
MIN_INTERVAL = 10m
LENGTH = 20000
TYPE = level

[queue.mirror]
LENGTH = 20000
WORKERS = 1

[cron.update_mirrors]
; Every hour
SCHEDULE = 0 0 * * * *
PULL_LIMITS = 1000
PUSH_LIMITS = 1000
```

is my current configuration.

With

`PULL_LIMITS = 1000`

gitea should update 1000 mirrors in one run. Right?

After 4th run I did this:

- flush-queues
- stop gitea
- remove ./../data/queues/common folder
- start gitea

And the 5th run updated again only 51 mirrors.

How can I update in Gitea 1.16.x 1000, 2000 or more mirrors in one row? And not only 51.

My current "solution" is: run the cron every hour and update the 51 mirror on every run. In my case it needs 179 runs.

**Comment by zeripath** [comment]
@somera Please read the configuration cheat sheet.

https://docs.gitea.io/en-us/config-cheat-sheet/#cron---update-mirrors-cronupdate_mirrors

```
[cron.update_mirrors]
PULL_LIMIT = 1000
PUSH_LIMIT = 1000
```

**Comment by somera** [comment]
> @somera Please read the configuration cheat sheet.
> 
> https://docs.gitea.io/en-us/config-cheat-sheet/#cron---update-mirrors-cronupdate_mirrors
> 
> ```
> [cron.update_mirrors]
> PULL_LIMIT = 1000
> PUSH_LIMIT = 1000
> ```

My mistake. I need glasses.
