### ISSUE TITLE
Bulk migration of repositories

### ISSUE THREAD

**Issue by HenriDellal** [go-gitea/gitea#18899]
### Feature Description

I'd like to propose a feature which would allow to migrate/import multiple repositories at once. It should work as following: The user gives authorization to Gitea application in Github/Gitlab/other service. After that the user sees the UI which lists all available repositories in that profile and is able to unmark the unwanted repositories from the list and set values for options of each repository import.

**Comment by lunny** [comment]
duplicated with #2569 ?

**Comment by HenriDellal** [comment]
Yes, I used issue search before publishing and couldn't find it, sorry.
