### ISSUE TITLE
Gitea DroneCI auth fail

### ISSUE THREAD

**Issue by adyanth** [go-gitea/gitea#18894]
### Gitea Version

1.16.2

### Git Version

N/A

### Operating System

k3s

### How are you running Gitea?

Kubernetes

### Database

PostgreSQL

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/adyanth/79ff84d4557e0d825660277d78ff2f69

### Description

I am seeing the exact same issue as #16838. But the [linked fix](https://blog.gitea.io/2021/08/gitea-1.15.0-is-released/#-asymmetric-jwt-signing-key-16010httpsgithubcomgo-giteagiteapull16010) points to increasing the field size for user_oauth_token but my drone instance is a new one. It is also using sqlite and TEXT type for the column, which has unlimited size.

### Screenshots

![image](https://user-images.githubusercontent.com/33192449/155715372-e9924d32-d151-43e5-bd5d-90a33aeadc9b.png)

**Comment by lunny** [comment]
Could you restart drone and try again.

**Comment by adyanth** [comment]
I recreated the containers and tried too. It was a working one, and i deleted the drone DB and tried also. That did not work either.

**Comment by adyanth** [comment]
I try again today (no restart/recreate) and it decides to work again. Not sure what went wrong. Will close this for now and reopen if I face the same issue when I migrate it over to k8s. Thanks!
