### ISSUE TITLE
APNG avatar loses animation information on upload

### ISSUE THREAD

**Issue by silverwind** [go-gitea/gitea#18907]
### Gitea Version

https://github.com/go-gitea/gitea/commit/fd273b05b9513e4ac1b0d7b743acc3c3d36c905c

### Can you reproduce the bug on the Gitea demo site?

Yes

### Description

APNG files lose animation information on upload. For example when uploading [this APNG](https://apng.onevcat.com/assets/elephant.png) as an avatar, postprocessing squares it and the [resulting file](https://try.gitea.io/avatars/9ebf623334446078a8b464a18fd37106) no longer animates.

**Comment by Gusted** [comment]
`image/png` doesn't support APNG, we would need to detect this kind of PNG and use a appropriate encoder like: https://github.com/kettek/apng

**Comment by silverwind** [comment]
Possibly way of detection: https://stackoverflow.com/a/4525194

**Comment by silverwind** [comment]
Let's continue in https://github.com/go-gitea/gitea/issues/24263.
