### ISSUE TITLE
gitea is not sending emails on creating issues

### ISSUE THREAD

**Issue by o3o** [go-gitea/gitea#1890]
- Gitea version 1.1.1
- Git version:
- Operating system: CentOS Linux 6.8
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant

## Description
I've tried using the "Send test email" feature and I've received correct email
But, when I open an issue, or I create a pull request etc, I haven't received any email

Is it a my mistake?

Thank you...

**Comment by strk** [comment]
Are you "Watch"ing the repository ?

**Comment by o3o** [comment]
Yes...

**Comment by gayprogrammer** [comment]
If you are both the user who is watching and the user who creates an issue, then you will not receive a mail notification for the issue you created, correct?

Have you received email notifications for issues created by other users?

**Comment by o3o** [comment]
@razzintown you're right! 
If user A is watching and user B creates an issue, A receive mail notification.
It is reasonable...
