### ISSUE TITLE
Gitea crash loop every 2 minutes

### ISSUE THREAD

**Issue by adyanth** [go-gitea/gitea#18917]
### Gitea Version

1.16.2

### Git Version

2.30.2

### Operating System

k3s

### How are you running Gitea?

Running on Kubernetes v1.22.6+k3s1 with the `docker.io/gitea/gitea:1.16.2` image

### Database

PostgreSQL

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

REMOVED

### Description

Gitea crashes every 1-2 minutes. All crashes end with `[F] Unable to create internal queue for XXX Error: Unable to create queue level for XXX with cfg ...` in the logs

**Comment by adyanth** [comment]
I don't have any section called queue. I can see configs for it here, am I supposed to set anything? https://docs.gitea.io/en-us/config-cheat-sheet/#queue-queue-and-queue

**Comment by zeripath** [comment]
Could you paste the rest of your app.ini?

**Comment by adyanth** [comment]
Let me give that a try. It is via a PVC to an NFS share which I recently enabled with no_root_squash, so I will check

**Comment by adyanth** [comment]
It can, but the user might be different now (I had removed runas git to troubleshoot). Should I run as git again?

```
❯ k -n gitea exec gitea-0 -it -- sh
Defaulted container "gitea" out of: gitea, init-directories (init), init-app-ini (init), configure-gitea (init)
/ # cd /data/queues/common/
/data/queues/common # ls
000002.ldb       CURRENT          LOCK             MANIFEST-000014
000013.log       CURRENT.bak      LOG
/data/queues/common # touch test
/data/queues/common # ls -alh
total 20K    
drwxr-xr-x    1 git      git          128 Feb 26 17:07 .
drwxr-xr-x    1 git      git           12 Feb 25 10:24 ..
-rw-r--r--    1 git      git          167 Feb 25 10:27 000002.ldb
-rw-r--r--    1 git      git            0 Feb 25 11:49 000013.log
-rw-r--r--    1 git      git           16 Feb 25 11:49 CURRENT
-rw-r--r--    1 git      git           16 Feb 25 11:49 CURRENT.bak
-rw-r--r--    1 git      git            0 Feb 25 10:24 LOCK
-rw-r--r--    1 git      git         3.4K Feb 25 11:50 LOG
-rw-r--r--    1 git      git           71 Feb 25 11:50 MANIFEST-000014
-rw-rw-rw-    1 root     root           0 Feb 26 17:07 test
/data/queues/common # 
```

**Comment by zeripath** [comment]
Are you trying to have multiple giteas run at the same time?

**Comment by zeripath** [comment]
If so you need to use redis for your queues

**Comment by adyanth** [comment]
Nope, just one. When I had this issue, I started removing stuff to isolate. I disabled memcache and run as git.

**Comment by zeripath** [comment]
Killall Giteas and tell me if the LOCK file goes away

**Comment by adyanth** [comment]
Will give that a try. I do not scale to more than 1, and don't plan to. But will keep redis in mind.

**Comment by zeripath** [comment]
Cool. I think we can close this. Sorry it took me so long to get involved. 

The logs were saying that the issue was the level db was temporarily unavailable - which is code for it can't get a LOCK on the db - and it was pointing to the directory but I guess that this isn't completely clear. I guess the question is whether can do more to make things clearer. 

There are a couple of reasons why a lock can't be taken - but I guess we could just detect this error and try to suggest a few things.

I'll close this issue though.
