### ISSUE TITLE
Issue API POST/PATCH update comment with certain Chinese characters cause encoding error.���

### ISSUE THREAD

**Issue by derekhu** [go-gitea/gitea#18925]
### Gitea Version

1.16.1

### Git Version

git version 2.35.1.windows.2

### Operating System

WindowsServer 2019

### How are you running Gitea?

windows system servcie

### Database

MySQL

### Can you reproduce the bug on the Gitea demo site?

No

### Description

Using API to update comments like:

 `PATCH /repos/{owner}/{repo}/issues/comments/{id}`

with body example:
(content from : https://docs.gitea.io/zh-cn/ )

```
- 功能特性
- 支持活动时间线
- 支持 SSH 以及 HTTP/HTTPS 协议
- 支持 SMTP、LDAP 和反向代理的用户认证
- 支持反向代理子路径
- 支持用户、组织和仓库管理系统
- 支持添加和删除仓库协作者
- 支持仓库和组织级别 Web 钩子（包括 Slack 集成）
- 支持仓库 Git 钩子和部署密钥
- 支持仓库工单（Issue）、合并请求（Pull Request）以及 Wiki
- 支持迁移和镜像仓库以及它的 Wiki
- 支持在线编辑仓库文件和 Wiki
- 支持自定义源的 Gravatar 和 Federated Avatar
- 支持邮件服务
- 支持后台管理面板
- 支持 MySQL、PostgreSQL、SQLite3、MSSQL 和 TiDB(MySQL) 数据库
- 支持多语言本地化（21 种语言）
```

Will get response with error encode characters: ���
![image](https://user-images.githubusercontent.com/1978211/155873544-961435d0-eda3-405a-a3e1-db23f274a2e6.png)

If change content a litter bit, the error may not occured.

MySQL encoding is : utf8mb4  

This error occured after migrate localhost Gitea from 1.15.6 to  1.16.1. And it was ok in 1.15.x

#### Screenshot 
API call request:   
![image](https://user-images.githubusercontent.com/1978211/155873925-1cb0bc0a-22ca-412f-8348-340b92fcf3a8.png)

response:
![image](https://user-images.githubusercontent.com/1978211/155873983-54b70af8-e376-4eba-952d-0c0acb2fc4c6.png)

**Comment by lunny** [comment]
So maybe it's a problem of encoding detection? Could you find the response encoding in the head?

**Comment by derekhu** [comment]
> So maybe it's a problem of encoding detection? Could you find the response encoding in the head?

Yeah, response head contained `Content-Type: application/json;charset=utf-8`

![image](https://user-images.githubusercontent.com/1978211/159386581-dc337754-ff3f-480c-844c-5f0166dd52be.png)

**Comment by wxiaoguang** [comment]
If you can not reproduce it on gitea.com or try.gitea.io, it's highly likely your environment's problem.

Feel free to reopen if you get new clues.

**Comment by derekhu** [comment]
This issue can not reproduce on gitea.com just becuase gitea.com SHUT DOWN CORS 

But the issue does exist.

**Comment by wxiaoguang** [comment]
What do you mean by `SHUT DOWN CORS`? Isn't it just an API, how is it related to CORS?

And what about try.gitea.io?

**Comment by derekhu** [comment]
> What do you mean by `SHUT DOWN CORS`? Isn't it just an API, how is it related to CORS?
> 
> And what about try.gitea.io?

Test API on gitea.com ?

**Comment by wxiaoguang** [comment]
Indeed, either you find a reproducible method to show how the problem occurs, or you can try to debug it and find the root problem and describe it. Otherwise maintainers can not reproduce the problem and can not help.
