### ISSUE TITLE
Gitea creates invalid links

### ISSUE THREAD

**Issue by orangebokov** [go-gitea/gitea#18934]
**Gitea Version**
1.16.1

**Git Version**
2.20.1

**Operating System**
Mac OS Mojave 10.14.6

**How are you running Gitea?**
Via terminal command `gitea`

**Database**
MySQL

**Description**
An invalid link is being created at this location.
https://github.com/go-gitea/gitea/blob/f56bba1a7823168f038cc4bd847c51771ca73bc9/templates/shared/issuelist.tmpl#L34

I mean they are absolute.
![Снимок экрана 2022-02-27 в 19 54 57](https://user-images.githubusercontent.com/39646729/155891768-9685030e-0b87-4636-ad93-09f19deb17d0.png)

Maybe they should be relative as well as on the whole site?
![Снимок экрана 2022-02-27 в 19 54 39](https://user-images.githubusercontent.com/39646729/155891746-1f7cba0b-c495-4d80-b5ae-38cd63905eb3.png)

I will explain

The site works in reverse proxy format. In nginx, relative links are replaced with the correct url: localhost:8082
![Снимок экрана 2022-02-27 в 20 11 49](https://user-images.githubusercontent.com/39646729/155892267-f4335f5e-ab11-49ab-b29e-74269cabedbc.png)

Absolute links refer to localhost:3000 directly.

It seems to me that there should be relative links here, as well as throughout the site.

Thanks.

**Comment by techknowlogick** [comment]
Those are built upon the ROOT_URL in your app.ini. You'd need to configure it to be the URL you'd expect

**Comment by orangebokov** [comment]
You are right, everything worked.
I've been poking around for a few hours.
The answer was so close.
Thank you very much.
Gradually understand.
Gitea is the best.
