### ISSUE TITLE
'Issues' not supported with API migration

### ISSUE THREAD

**Issue by slavb18** [go-gitea/gitea#18948]
### Gitea Version

1.16.2

### Git Version

2.34.1

### Operating System

Linux

### How are you running Gitea?

opensuse package

### Database

MySQL

### Can you reproduce the bug on the Gitea demo site?

No

### Description

Cannot migrate repo using API
Request (migration.json):
```json
{
"auth_token": "ghp_XZ...U",
"clone_addr": "https://github.com/org/repo",
"issues": true,
"private": true,
"repo_name": "repo",
"repo_owner": "owner"
}
```

Comman line:
```bash
curl -k -X POST "https://gitea.host/api/v1/repos/migrate" \
    -H "accept: application/json" \
    -H "Authorization: token e....d" \
    -H "Content-Type: application/json" -d @migration.json -i
```

Result: `{"message":"'Issues' not supported","url":"https://gitea.host/api/swagger"}`

**Comment by lunny** [comment]
You should indicate `service_type`.

**Comment by noerw** [comment]
`"service_type": "git"` does not support issues, other providers do.
