### ISSUE TITLE
When you change email, it is not replaced everywhere

### ISSUE THREAD

**Issue by orangebokov** [go-gitea/gitea#18958]
### Gitea Version

1.16.1

### Git Version

2.20.1

### Operating System

Mac OS Mojave 10.14.6

### How are you running Gitea?

terminal

### Database

MySQL

### Can you reproduce the bug on the Gitea demo site?

No

### Description

If I make an api request to change email, it is replaced in the database table `user`.
Which is to be expected.
But it should also be removed from the `email_address` table.
Because another user cannot register with this email.

![Снимок экрана 2022-03-01 в 20 24 12](https://user-images.githubusercontent.com/39646729/156217708-5d69a23c-4d5a-402b-991b-c1cfb505bc2d.png)

**Comment by Gusted** [comment]
What kind of API call did you make to change your user's email? Did you mean to add a new email? A user can have multiple emails(see `email_adresses` table in database). From what I see and tested it's working correctly.

**Comment by orangebokov** [comment]
Reproduce the situation:

Registering a user
![Снимок экрана 2022-03-02 в 18 25 06](https://user-images.githubusercontent.com/39646729/156392723-2c300d70-1407-471f-b16e-e8826eb8c7d6.png)
![Снимок экрана 2022-03-02 в 18 16 54](https://user-images.githubusercontent.com/39646729/156392897-a3f52178-cd3d-45bf-854c-1f6b593a8841.png)
mysql.user
![Снимок экрана 2022-03-02 в 18 17 12](https://user-images.githubusercontent.com/39646729/156392979-7b15902f-94b1-43e2-8cb8-61a06304b65a.png)
mysql.email_address
![Снимок экрана 2022-03-02 в 18 17 29](https://user-images.githubusercontent.com/39646729/156393047-1f4f082e-d6de-427d-8749-593732424808.png)

Update email
![Снимок экрана 2022-03-02 в 18 25 27](https://user-images.githubusercontent.com/39646729/156394010-362d30bb-335d-439c-8396-705b38d39967.png)
![Снимок экрана 2022-03-02 в 18 22 05](https://user-images.githubusercontent.com/39646729/156394104-2aa05b2c-6b77-4bc8-b74c-c24c9b05a562.png)
mysql.user
![Снимок экрана 2022-03-02 в 18 22 29](https://user-images.githubusercontent.com/39646729/156394200-ef06c74c-1c23-4815-8e4d-5e092c592100.png)
mysql.email_address
![Снимок экрана 2022-03-02 в 18 22 40](https://user-images.githubusercontent.com/39646729/156394239-1bb5931c-c61e-426a-88cf-c395da61c626.png)

We are trying to create a new user with an email that does not currently belong to anyone
![Снимок экрана 2022-03-02 в 18 24 48](https://user-images.githubusercontent.com/39646729/156394741-c2768597-aad3-41c9-8efb-454d00cfcb75.png)
![Снимок экрана 2022-03-02 в 18 24 18](https://user-images.githubusercontent.com/39646729/156394804-69b51bd6-2b9b-462f-a837-169a9913ea92.png)

This is because the email has not been removed from the table mysql.email_address
![Снимок экрана 2022-03-02 в 18 39 15](https://user-images.githubusercontent.com/39646729/156395059-40ff8dfd-7a93-4726-9a58-33d512cf5926.png)

Let me explain.
I am registering users programmatically.
They have a template email.
Then I replace the template email with the desired one.

This has to be done, because when creating a user, email cannot be set immediately, because it may contain non-Latin characters. But then you can replace it with the desired one.

**Comment by orangebokov** [comment]
If this is intended, then I get around this by removing the email from the email_address table manually.

**Comment by orangebokov** [comment]
I understand that email addresses are added, not replaced. Is it possible to somehow remove the address using api? Or only by directly accessing the database?

**Comment by orangebokov** [comment]
Thank you for your attention. Essentially, I got around this situation. Direct communication with the database is not so scary. I hope the api will diversify over time with many functions. I could add them myself, but I did not really understand the source code. Sorry.
