### ISSUE TITLE
mail notifications for releases are send for user with deactivated e-mail

### ISSUE THREAD

**Issue by r10r** [go-gitea/gitea#18950]
### Gitea Version

1.16.1

### How are you running Gitea?

Gitea helm chart

### Database

PostgreSQL

### Can you reproduce the bug on the Gitea demo site?

No

### Description

I have created a (bot) user with a fake e-mail adress but deactivated the e-mail address in the administration settings.
But when I create a release of a project a e-mail notification is send to this user.
Since the user doesn't have a valid mailbox a bounce message is generated
and sent to the mail system administrator.

How can I disable all e-mail notifications for a bot user ?

### Screenshots

<img width="1191" alt="Screenshot 2022-03-01 at 09 27 05" src="https://user-images.githubusercontent.com/309304/156133329-eea0c64f-591d-46bf-9750-cf93e71fada7.png">

**Comment by Gusted** [comment]
It seems like that none of the sending mail functions is taking into account if a email address might be de-activated... Marking as bug.

**Comment by r10r** [comment]
@Gusted Can you please give ma link to the relevant code section ? 
I look forward to get this fixed - maybe I can send a pull request.

**Comment by Gusted** [comment]
There too many code paths that eventually lead to sending a mail and many more functions, which uses those function and can access the user/database and can see if a email is inactive. If it was a general function it would be easier, but the code is quite cluttered.
