### ISSUE TITLE
Unable to connect when accessing repos from repositories list

### ISSUE THREAD

**Issue by daviddoji** [go-gitea/gitea#18956]
### Gitea Version

1.16.1

### Operating System

Ubuntu server 20.04

### Browser Version

Firefox 97.0.1

### Can you reproduce the bug on the Gitea demo site?

No

### Description

I'm running Gitea using Docker from Ubuntu Server. I'm very happy so far with it.

Recently, I've noticed that if I try to access any repository from the repository list (see screenshot attached), I'm getting redirected to "git.mydomain.com:XXXX/username/myrepo" and I'm getting an error from the browser saying "Unable to connect. Firefox can’t establish a connection to the server at git.mydomain.com/XXXX"

On the other hand, I can access any repository if I go instead to "https://git.mydomain.com/username/myrepo.git"

What do I have to change in my configuration? 

### Screenshots

![image](https://user-images.githubusercontent.com/4411314/156210253-62a432bd-ab96-4601-8f30-aab0c2c7225b.png)

**Comment by Gusted** [comment]
Do you have `ROOT_URL` correctly set in your config.ini file?

**Comment by daviddoji** [comment]
Thx for the tip! Pointing to the proper URL (https without port number) made the trick :D
