### ISSUE TITLE
Email login produce white page for non-admin user

### ISSUE THREAD

**Issue by dharmann** [go-gitea/gitea#18970]
### Gitea Version

1.16.2

### Git Version

2.25.1

### Operating System

Ubuntu 20.04 Linux

### How are you running Gitea?

systemd service using the binary downloaded from https://dl.gitea.io/gitea/1.16.2/gitea-1.16.2-linux-amd64
In addition I have Apache as proxy to expose gitea on port 80 of virtualhost

### Database

MySQL

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/dharmann/897e099d6ba1aa85b54ef9f800d73c90

### Description

After upgrade from v1.15.2 to v1.16.2 a non-admin user trying to login with email address can't go on. The browser stop itself into a blank page. Apparently without network or javascript error. The login with username works normally. Apparently a login with an admin user seems working well with both username and email

### Screenshots

![Screenshot_20220302_114228](https://user-images.githubusercontent.com/6182373/156346816-fce3eb37-f436-4d79-9aca-810165827cec.png)

**Comment by lunny** [comment]
This should be resolved by v1.16.3
