### ISSUE TITLE
Cannot upgrade to 1.16.0+ : Heatmap loads forever + No Repository list

### ISSUE THREAD

**Issue by JeanFrancoeur** [go-gitea/gitea#18991]
### Gitea Version

1.15.11

### Git Version

2.17.1

### Operating System

Ubuntu 18.04.4

### How are you running Gitea?

Within docker v19.03.8

### Database

PostgreSQL

### Can you reproduce the bug on the Gitea demo site?

No

### Description

Similar to this issue: https://github.com/go-gitea/gitea/issues/10441

### But another error in web console:
_index.js?v=bc863f21533a71adeb12f9c4b9854556:31 Uncaught TypeError: Cannot destructure property 'copy_success' of 'window.config.i18n' as it is undefined.
    at Object../web_src/js/index.js (index.js?v=bc863f21533a71adeb12f9c4b9854556:31:823)
    at Yt (index.js?v=bc863f21533a71adeb12f9c4b9854556:92:866)
    at index.js?v=bc863f21533a71adeb12f9c4b9854556:94:521
    at index.js?v=bc863f21533a71adeb12f9c4b9854556:94:713_

**Also note that the Profile & Settings Dropdown won't open on click (the new context dropdown too)**
Each upgrade from 1.15.3 to 1.15.11 works, but any 1.16.x doesn't.

**Found this error in gitea db log:**
_ERROR:  missing chunk number 0 for toast value 56934 in pg_toast_16749
CONTEXT:  automatic analyze of table "gitea.public.hook_task"_

**Here's the last lines of Gitea server:**
_2022/03/03 18:24:26 models/repo.go:1012:repoStatsCheck() [T] Updating repository count 'num_closed_pulls': 68
2022/03/03 18:24:27 cmd/web.go:208:listen() [I] Listen: https://0.0.0.0:3000
2022/03/03 18:24:27 cmd/web.go:212:listen() [I] AppURL(ROOT_URL): https://x.x.x.x:9043/
2022/03/03 18:24:27 cmd/web.go:215:listen() [I] LFS server enabled
2022/03/03 18:24:27 cmd/web.go:64:runHTTPRedirector() [I] Redirecting: 0.0.0.0:3080 to https://x.x.x.x:9043
2022/03/03 18:24:27 ...s/graceful/server.go:61:NewServer() [I] Starting new Web server: tcp:0.0.0.0:3000 on PID: 16
2022/03/03 18:24:27 ...s/graceful/server.go:61:NewServer() [I] Starting new HTTP Redirector server: tcp:0.0.0.0:3080 on PID: 16
2022/03/03 18:24:27 ...s/graceful/server.go:74:func1() [D] Starting server on tcp:0.0.0.0:3000 (PID: 16)
2022/03/03 18:24:27 ...s/graceful/server.go:74:func1() [D] Starting server on tcp:0.0.0.0:3080 (PID: 16)
2022/03/03 18:24:36 ...ource/manager_run.go:40:Run() [T] Event source has no listeners
2022/03/03 18:24:36 ...ource/manager_run.go:50:Run() [T] Pausing the eventsource_

### Screenshots

![GiteaUpgradeError](https://user-images.githubusercontent.com/3595476/156630571-a58ccda8-c098-434e-9d3e-6e55b7fec818.png)

**Comment by Gusted** [comment]
Try clearing the cache, it could be that a older version of the scripts is loaded.

**Comment by JeanFrancoeur** [comment]
Thanks for your suggestion, but clearing cache and trying another fresh browser, login and same behavior.
Note I'm able to reach Profile and Settings url directly.
What changed between 1.15.x and 1.16.x?

**Comment by Gusted** [comment]
> What changed between 1.15.x and 1.16.x?

It's a major version update, so quite a lot. But are you by any chances using custom templates?

**Comment by JeanFrancoeur** [comment]
That was the case.  I've found some template files and renamed them.
Thank you so much @Gusted, everything is back on track

**Comment by joseluisq** [comment]
To mention also that a restart is necessary.
