### ISSUE TITLE
Allow using Ctrl+Enter to submit issue/comment

### ISSUE THREAD

**Issue by unfa** [go-gitea/gitea#19005]
### Feature Description

Ctrl+Enter it's a common keyboarad combo used to send messages, comments, posts etc in various online services.

I am missing that one greatly in Gitea. being able to submit your issue or comment using Ctrl+Enter rather than switching back to mouse and clicking a button in the UI is a very nice usability feature that I am really missing in Gitea.

Github has this feature and I got used to it.

**Comment by NPatch** [comment]
https://github.com/go-gitea/gitea/issues/14843

**Comment by wxiaoguang** [comment]
Close due to duplicate
