### ISSUE TITLE
请问一下，gogit版本和不带gogit版本什么区别？win10应该下载哪个版本？

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#19019]

**Comment by saber-project** [comment]
应该是指是否集成由go来原生实现的git
Integrate git natively implemented by go
--------------------------------------------------------
[https://github.com/go-git](url)
[https://pkg.go.dev/gopkg.in/src-d/go-git.v4?utm_source=godoc](url)
[https://git-scm.com/book/en/v2/Appendix-B:-Embedding-Git-in-your-Applications-go-git](url)

**Comment by airxy** [comment]
> 应该是指是否集成由go来原生实现的git
> 
> Integrate git natively implemented by go
> 
> --------------------------------------------------------
> 
> [https://github.com/go-git](url)
> 
> [https://pkg.go.dev/gopkg.in/src-d/go-git.v4?utm_source=godoc](url)
> 
> [https://git-scm.com/book/en/v2/Appendix-B:-Embedding-Git-in-your-Applications-go-git](url)

非常感谢🙏，总算是有了一个方向，当时啥都没看懂
