### ISSUE TITLE
Double attachments and lfs-files in backup

### ISSUE THREAD

**Issue by boboloris** [go-gitea/gitea#19016]
### Gitea Version

1.16.3

### Git Version

git version 2.28.0.windows.1

### Operating System

Windows Server 2019

### How are you running Gitea?

We are running a build from the gitea page as a windows service.

### Database

PostgreSQL

### Can you reproduce the bug on the Gitea demo site?

No

### Description

After updating from version 1.15.11 to 1.16.3 we encountered a strange behaviour concerning the backups using the gitea dump command. The backups have incresed in size of several GBs without any changes to the repos, lfs etc. Further investigation yields that all attachments and lfs files are backuped twice (see screenshot for example).

### Screenshots

![image](https://user-images.githubusercontent.com/33197833/157018200-b9c19ec7-aef8-4c73-98f3-35bb70ba2793.png)
Example from a file in lfs in a backup.

**Comment by zeripath** [comment]
Presumably these files are at different paths - would you be able to tell us what paths they are at?

It would be helpful to see your app.ini, in particular any storage settings you have.

Could you test adding `--skip-attachment-data` to your dump command to see if that stops the doubled lfs dumping.

**Comment by lunny** [comment]
For all the storages, Gitea didn't implement deduplicate for files. It should be done by the file system. i.e. minio could deduplicate files in the architecture.

**Comment by boboloris** [comment]
No, both files are in the same location in the zip file  (see the screenshot below).
![image](https://user-images.githubusercontent.com/33197833/157177589-bc93494f-4fb6-480b-8557-b49055520e7e.png)

I have no special settings in the app.ini concerning storage options.
Using `--skip-attachment-data` helps, all files in the attachment folder in the backup are now single. But files in the lfs folder are still doubled.

**Comment by zeripath** [comment]
OK it looks likes the recursive exclusion of storage directories isn't working.

It would be useful to see your app.ini and to see the results of dump --verbose.

**Comment by zeripath** [comment]
I suspect the problem is that the paths here:

```go
		excludes = append(excludes, setting.RepoRootPath)
		excludes = append(excludes, setting.LFS.Path)
		excludes = append(excludes, setting.Attachment.Path)
		excludes = append(excludes, setting.LogRootPath)
```

are not absolute and they need to be.

**Comment by boboloris** [comment]
Gist [app.ini](https://gist.github.com/boboloris/10ad46f3b57d715d5a79518cbf95d4b5)
Gist [gitea dump --verbose](https://gist.github.com/boboloris/9ffe9134ad2a930e21d7fe1c2b0cfe6f) (I have removed the logs concerning the git repos themself due to data proctection)
