### ISSUE TITLE
Copy button

### ISSUE THREAD

**Issue by buzzard10** [go-gitea/gitea#19011]
### Feature Description

It would be great if you could add copy button like there is in gitlab for example. It would help me very much. 
I think it's small thing but it would help.

### Screenshots

![image](https://user-images.githubusercontent.com/17282191/156897243-f33db2f7-2334-4f5f-9b79-712e909d93f8.png)

**Comment by lunny** [comment]
But then so much buttons there.

**Comment by b1f17773** [comment]
@lunny i want only one button - for copying. If that's a problem, then they can also add this as option, so user could decide in his preferences does he want this additional button, or not.

**Comment by lunny** [comment]
Just found Github also has that button.

**Comment by b1f17773** [comment]
> Just found Github also has that button.

So you're also down for this feature?

**Comment by lunny** [comment]
> > Just found Github also has that button.
> 
> So you're also down for this feature?

Yes, I think we can follow that if no better idea.

**Comment by r4tze** [comment]
I'm missing such a "Copy Content" Button as well. This would be a nice feature.

**Comment by yardenshoham** [comment]
Does #21629 close this?

**Comment by buzzard10** [comment]
It's work in the same way as button on github? If so, then yes :)

**Comment by yardenshoham** [comment]
It's not exactly the same, in #21629 you can only copy the text if a file is displayed in `source` mode. The maintainers preferred to avoid an HTTP call to get raw contents on click. If you want to try it out,

https://try.gitea.io/alchemist/stem-ui/src/branch/main/README.md (disabled as it's not raw text)
https://try.gitea.io/alchemist/stem-ui/src/branch/main/README.md?display=source (enabled)
https://try.gitea.io/alchemist/stem-ui/src/branch/main/sass/main.sass (enabled)

**Comment by buzzard10** [comment]
Can you make it work for all views? Not only raw content?

**Comment by yardenshoham** [comment]
If you'd like the extended functionality to copy files while in rendered view please open a new issue

**Comment by silverwind** [comment]
Where does GitHub have this button?

We can extend later to allow image copy which is a bit tricky but possible. What other file types do you want to copy?

**Comment by silverwind** [comment]
Apparently GitHub hides the button depending on User-Agent. Firefox UA will not show it. Switching Firefox to Chrome UA shows it and it also works. Way to go to discriminate browsers...
