### ISSUE TITLE
cli `--must-change-password` not working

### ISSUE THREAD

**Issue by loynoir** [go-gitea/gitea#19026]
### Gitea Version

[Docker] Gitea version 1.16.3 built with GNU Make 4.3, go1.17.6 : bindata, timetzdata, sqlite, sqlite_unlock_notif

### How are you running Gitea?

cli `--must-change-password` not working
```sh
$ docker run -p 3000:3000 -it gitea/gitea
$ docker exec -it $(docker ps|grep gitea|awk '{print $1}') bash
```
Visit Initial Configuration at http://localhost:3000/

```sh
# su git
$ gitea admin user create  --username foo  --password foo  --email foo@localhost  --must-change-password false
```
Still need to change password when first login

But using library generated by `https://github.com/OpenAPITools/openapi-generator`, `--must-change-password false` works fine.

### Can you reproduce the bug on the Gitea demo site?

No

**Comment by zeripath** [comment]
`gitea admin user create  --username foo  --password foo  --email foo@localhost  --must-change-password=false`

**Comment by zeripath** [comment]
Note the `=`

**Comment by noerw** [comment]
Looks like only bool flags require a `=` separator, afaik this is fixed in `urfave/cli/v2`.
But that version has [quite stupid issues with flag / argument order when using global flags](https://github.com/urfave/cli/issues/1113), that might be a blocker for switching to v2.

**Comment by loynoir** [comment]
> `gitea admin user create --username foo --password foo --email foo@localhost --must-change-password=false`

Yes, confirmed working with `=` way

**Comment by zeripath** [comment]
I think the BoolTFlag may have a slightly nicer behaviour.

**Comment by techknowlogick** [comment]
@noerw you'll find v1 has same global ordering pattern, which we've worked around.

Gonna close this now though.

**Comment by decentral1se** [comment]
> @noerw you'll find v1 has same global ordering pattern, which we've worked around.

@techknowlogick oh! would you mind sharing that work-around? i'm struggling with cli ordering with urfave also...

**Comment by zeripath** [comment]
https://github.com/go-gitea/gitea/blob/fda5b9fc3e6dd831987979f37fe39f08963b875d/main.go#L109-L127

Look at the `setFlagsAndBeforeOnSubcommands`
