### ISSUE TITLE
swagger operationId Suggestion: change `renderMarkdownRaw` to `renderRawMarkdown`

### ISSUE THREAD

**Issue by loynoir** [go-gitea/gitea#19025]
### Feature Description

https://try.gitea.io/swagger.v1.json

change from
```txt
"operationId": "renderMarkdownRaw",
```
to
```txt
"operationId": "renderRawMarkdown",
```

method pattern `xxxRaw` maybe conflict, when using code generator to create gitea api client 

https://github.com/OpenAPITools/openapi-generator/issues/11827

**Comment by yardenshoham** [comment]
This is a bug in openapi-generator and should be addressed there
