### ISSUE TITLE
No users show in assignment list

### ISSUE THREAD

**Issue by jcluna** [go-gitea/gitea#19024]
### Gitea Version

1.16.3

### Git Version

2.35.1.windows.2

### Operating System

Windows Server 2019 Standard

### How are you running Gitea?

I'm using gitea binary v1.16.3 from https://dl.gitea.io/gitea/1.16.3/gitea-1.16.3-windows-4.0-amd64.exe

### Database

SQLite

### Can you reproduce the bug on the Gitea demo site?

No

### Description

When registering an issue, I want to assign users but the users associated with the repository do not appear in the list of assignments. Only the user with which the repository was created appears. I hope you guys can fix it soon.

### Screenshots

This are my users
![image](https://user-images.githubusercontent.com/8999438/157131723-a6d181d3-eb8f-441f-b926-45394db55499.png)

But they aren't listed in the assignment list
![image](https://user-images.githubusercontent.com/8999438/157131743-ffeac42b-c2f1-45c7-920d-61420541f92a.png)

**Comment by Gusted** [comment]
This will be fixed in the next Gitea release: #18992
