### ISSUE TITLE
Failed to synchronize tags to release in SyncMirror with error: "pushUpdateAddTag: GetTag: Length must be 40:"

### ISSUE THREAD

**Issue by somera** [go-gitea/gitea#19038]
### Feature Description

In gitea.log I see sometimes:

```
==> gitea.log <==
2022/03/09 12:06:37 ...irror/mirror_pull.go:261:runSync() [E] Failed to synchronize tags to releases for repository: pushUpdateAddTag: GetTag: Length must be 40:
        /source/services/mirror/mirror_pull.go:261 (0x1cdf3b8)
        /source/services/mirror/mirror_pull.go:376 (0x1ce10b8)
        /source/services/mirror/mirror.go:42 (0x1cdb344)
        /source/services/mirror/mirror.go:144 (0x1cdbe31)
        /source/modules/queue/unique_queue_channel.go:76 (0x14954b6)
        /source/modules/queue/workerpool.go:437 (0x149e1c5)
        /source/modules/queue/workerpool.go:280 (0x149d096)
        /usr/local/go/src/runtime/asm_amd64.s:1581 (0x471520)
```

But you can't see:

- which project
- which tag?
- how long is it?

**Comment by zeripath** [comment]
You have to tell us what version of Gitea you're reporting from.

Assuming you're using 1.16 - you can add a trace logger for the services/mirror as I have previously explained which will add significant amounts of tracing. 

<details><summary>How to add trace logging for services/mirror</summary>

You can adjust your ini like this:

```ini
[log]
MODE=console, traceconsole
...

[log.traceconsole]
MODE=console
LEVEL=trace
EXPRESSION=services/mirror
```

Or you can run `gitea manager logging add console -n traceconsole -l trace -e "services/mirror"`

You can use a file logger too. Look at `gitea manager logging add --help` `gitea manager logging add file --help`

</details>

This is an interesting case. The error is coming from within:

https://github.com/go-gitea/gitea/blob/2448c5ad8b82eb06ec63bcc9c696d380b35ea97c/modules/repository/repo.go#L293-L295

The error string indicates that the ID it is trying to look for is actually an empty string but that doesn't make any sense at all.

I've created another PR to further improve the logging here, but if you add the tracelogger as above we can find out what is special about the repo that is causing this.

**Comment by somera** [comment]
I'm using 1.16.3.

**Comment by somera** [comment]
@zeripath some log examples

Repo-URL: https://github.com/ballerina-platform/module-ballerina-cache
```
2022/03/10 08:50:08 ...irror/mirror_pull.go:356:SyncPullMirror() [T] SyncMirrors [repo_id: 6354]
2022/03/10 08:50:08 ...irror/mirror_pull.go:375:SyncPullMirror() [T] SyncMirrors [repo: 6354:ballerina-platform/module-ballerina-cache]: Running Sync
2022/03/10 08:50:08 ...irror/mirror_pull.go:190:runSync() [T] SyncMirrors [repo: 6354:ballerina-platform/module-ballerina-cache]: running git remote update...

==> gitea.log <==
2022/03/10 08:50:09 ...age_stats_nogogit.go:86:func2() [E] Unable to open checker for 11d0f5d34c7e8287afa5724c0e4b907a00ebe573. Error: failed to run attr-check. Error: context canceled
        Stderr:
        /source/modules/git/repo_language_stats_nogogit.go:86 (0xaeef8f)
        /usr/local/go/src/runtime/asm_amd64.s:1581 (0x471520)
```


Repo-URL:  https://github.com/hendisantika/spring-boot-paypal
```
2022/03/10 08:49:53 ...irror/mirror_pull.go:356:SyncPullMirror() [T] SyncMirrors [repo_id: 6417]
2022/03/10 08:49:53 ...irror/mirror_pull.go:375:SyncPullMirror() [T] SyncMirrors [repo: 6417:hendisantika/spring-boot-paypal]: Running Sync
2022/03/10 08:49:53 ...irror/mirror_pull.go:190:runSync() [T] SyncMirrors [repo: 6417:hendisantika/spring-boot-paypal]: running git remote update...

==> gitea.log <==
2022/03/10 08:49:53 ...age_stats_nogogit.go:86:func2() [E] Unable to open checker for cf898a8c2e397c699e5e65b8ffa060883532eb1a. Error: failed to run attr-check. Error: context canceled
        Stderr:
        /source/modules/git/repo_language_stats_nogogit.go:86 (0xaeef8f)
        /usr/local/go/src/runtime/asm_amd64.s:1581 (0x471520)
```

Repo-URL: https://github.com/ballerina-platform/ballerina-standard-library
```
2022/03/10 08:49:53 ...irror/mirror_pull.go:356:SyncPullMirror() [T] SyncMirrors [repo_id: 6330]
2022/03/10 08:49:53 ...irror/mirror_pull.go:375:SyncPullMirror() [T] SyncMirrors [repo: 6330:ballerina-platform/ballerina-standard-library]: Running Sync
2022/03/10 08:49:53 ...irror/mirror_pull.go:190:runSync() [T] SyncMirrors [repo: 6330:ballerina-platform/ballerina-standard-library]: running git remote update...

==> gitea.log <==
2022/03/10 08:49:53 ...age_stats_nogogit.go:86:func2() [E] Unable to open checker for a5f1ab1c2af1bb0866438c793c390062bf0e39ec. Error: failed to run attr-check. Error: context canceled
        Stderr:
        /source/modules/git/repo_language_stats_nogogit.go:86 (0xaeef8f)
        /usr/local/go/src/runtime/asm_amd64.s:1581 (0x471520)
```

**Comment by zeripath** [comment]
```
Unable to open checker for a5f1ab1c2af1bb0866438c793c390062bf0e39ec. Error: failed to run attr-check. Error: context canceled
```

Ignore these. They are nothing to do with your initial report. They are incorrectly being reported as an error when they're normal.

**Comment by somera** [comment]
> ```
> Unable to open checker for a5f1ab1c2af1bb0866438c793c390062bf0e39ec. Error: failed to run attr-check. Error: context canceled
> ```
> 
> Ignore these. They are nothing to do with your initial report. They are incorrectly being reported as an error when they're normal. PRs to fix them have already been merged and I recently closed a duplicate issue you opened about these.

Sorry. Wrong post.

**Comment by somera** [comment]
I got this error on run "Garbage-Collection" cron. I will start it again.

**Comment by somera** [comment]
@zeripath I got this

```
2022/03/24 02:07:27 ...irror/mirror_pull.go:261:runSync() [E] SyncMirrors [repo: 225:games/triplea]: failed to synchronize tags to releases: unable to PushUpdateAddTag: "2.0.17694" to Repo[225:games/triplea]: unable to GetTag: Length must be 40:
        /source/services/mirror/mirror_pull.go:261 (0x1d49ddc)
        /source/services/mirror/mirror_pull.go:376 (0x1d4bc4d)
        /source/services/mirror/mirror.go:46 (0x1d45cb5)
        /source/services/mirror/mirror.go:148 (0x1d467d1)
        /source/modules/queue/unique_queue_channel.go:76 (0x14ffd76)
        /source/modules/queue/workerpool.go:406 (0x150863a)
        /source/modules/queue/workerpool.go:280 (0x1507956)
        /usr/local/go/src/runtime/asm_amd64.s:1581 (0x471520)
```

repo: https://github.com/triplea-game/triplea

**Comment by zeripath** [comment]
Sorry I missed your response.

Let's break down the log message

```
2022/03/24 02:07:27 ...irror/mirror_pull.go:261:runSync() [E] SyncMirrors [repo: 225:games/triplea]: failed to synchronize tags to releases: unable to PushUpdateAddTag: "2.0.17694" to Repo[225:games/triplea]: unable to GetTag: Length must be 40:
 ```

In repo with ID: `225` which has the path `games/triplea` and would therefore be `GITEA_REPOSITORY_ROOT/games/triplea.git` whilst PushUpdateAddTag was trying to work it tried to push the tag `2.0.17694` but the tag was not found.

So...

Does that tag exist in that repository?

**Comment by somera** [comment]
@zeripath I don't know. But the error happens during mirror update cron.

My local mirror:

![image](https://user-images.githubusercontent.com/8334250/160295776-3ad797e6-d160-42e6-8864-4b794dce557b.png)

GutHub repo:

https://github.com/triplea-game/triplea/tags?after=2.0.17751

**Comment by zeripath** [comment]
What are the results of:

```bash
git show-ref --tags | grep 2.0.17694
```


```bash
git show-ref --tags -- 2.0.17694 
```

**Comment by somera** [comment]
```
$ git show-ref --tags | grep 2.0.17694
ef59fccf7e34a7f036829d2fdc4f5e09006ddb78 refs/tags/2.0.17694

$ git show-ref --tags -- 2.0.17694
ef59fccf7e34a7f036829d2fdc4f5e09006ddb78 refs/tags/2.0.17694
```

**Comment by zeripath** [comment]
This is on the gitea repository on the server right?

**Comment by somera** [comment]
I started new mirror and got this:

```
==> gitea.log <==
2022/03/27 21:37:54 ...s/repository/repo.go:146:MigrateRepositoryGitData() [E] Failed to synchronize tags to releases for repository: unable to PushUpdateAddTag: "1.9.0.0.9102" to Repo[10988:gitea_admin/triplea]: unable to GetTag: Length must be 40:
        /source/modules/repository/repo.go:146 (0x14fea5f)
        /source/services/migrations/gitea_uploader.go:116 (0x1dcb0b5)
        /source/services/migrations/migrate.go:201 (0x1de2f6c)
        /source/services/migrations/migrate.go:129 (0x1de2579)
        /source/services/task/migrate.go:112 (0x1e898f5)
        /source/services/task/task.go:33 (0x1e8a7a4)
        /source/services/task/task.go:55 (0x1e8aa6f)
        /source/modules/queue/workerpool.go:445 (0x1607ade)
        /source/modules/queue/workerpool.go:280 (0x1606c16)
        /usr/local/go/src/runtime/asm_amd64.s:1571 (0x46ffe0)
```

**Comment by somera** [comment]
> This is on the gitea repository on the server right?

```
[So Mär 27][21:39:55][git]@[nuc-mini-celeron]:[~/data/repositories/games/triplea.git]$ git show-ref --tags | grep 2.0.17694
ef59fccf7e34a7f036829d2fdc4f5e09006ddb78 refs/tags/2.0.17694
[So Mär 27][21:40:19][git]@[nuc-mini-celeron]:[~/data/repositories/games/triplea.git]$ git show-ref --tags | grep 2.0.17694
ef59fccf7e34a7f036829d2fdc4f5e09006ddb78 refs/tags/2.0.17694

```

**Comment by zeripath** [comment]
Pull and build #19236 and see if the problem still happens.

**Comment by zeripath** [comment]
The second line there is not right they are not supposed to be the same it should be `git show-ref --tags -- 2.0.17694` .

---

However, I don't understand what is happening here.

The ref is being listed by `git show-ref --tags` but then when we try to use `git show-ref --tags -- TAG_NAME` it doesn't work. 

I dunno.

I've got a patch that tries to avoid the second show-ref so I guess we try that?

**Comment by somera** [comment]
> Pull and build #19236 and see if the problem still happens.

I can't do this on my gite instance.

Can you check this on https://try.gitea.io/ ?

**Comment by somera** [comment]
> The second line there is not right they are not supposed to be the same it should be `git show-ref --tags -- 2.0.17694` .

wrong copy & paste

```
So Mär 27][22:05:49][git]@[nuc-mini-celeron]:[~/data/repositories/games/triplea.git]$ git show-ref --tags -- 2.0.17694
ef59fccf7e34a7f036829d2fdc4f5e09006ddb78 refs/tags/2.0.17694
```

**Comment by zeripath** [comment]
> > Pull and build #19236 and see if the problem still happens.
> 
> I can't do this on my gite instance.
> 
> Can you check this on https://try.gitea.io/ ?

If I could replicate your issue I would have done so myself and I wouldn't have asked.

"I can't do this on my gitea instance" does not make sense. You have already determined that this is a bug of significant importance to you and your workflow. Running a small patch temporarily in order to test if a bug fix works, resolves or helps to explain your problem further cannot therefore break your instance further. 

Honestly it's like working blindfolded in the dark and it's deeply infuriating - it unnecessarily delays the resolution of your issues and leads to these months long issue threads where I or others attempt to fix the problems that affect you - often unsuccessfully and if the issue is ever fixed it is because someone else has finally managed to replicate or reported the problem in a different way and has tested a bug fix.

Having just managed to successfully migrate https://github.com/triplea-game/triplea locally - I can see a number of potential issues with the code - not least that it is repeatedly calling git commands instead of reusing the open cat-files. This may be a cause of fd exhaustion so I guess I will take a look at reducing that and will continue to work on #19236 as an efficiency improvement.

However, if you are unwilling to try patches - I am afraid I don't know what to do.

PushAddUpdateTag only runs on tags which have been emitted by `git show-ref --tags` first. The error you receive indicates that a subsequent `git show-ref --tags -- TAGNAME` is then returning no id. How this could happen I don't know and it doesn't make sense to me. I guess all I can say is I will have a think and will comment again if again comes to me.

**Comment by somera** [comment]
@zeripath I don't want test unofficial release on my private prod instance. This is the main relason.

> However, if you are unwilling to try patches - I am afraid I don't know what to do.

Hm ... you are developing software or fixes without testing them? In this case you have to add new mirror and check the log.

But it's ok. I will check it on other computer. But not today.

I need some infos:

- should I compile the 1.16 branch? If not, which commit is it?
- how to compile it for PostgreSQL? I'm not working with go.
- which go version I need?

**Comment by zeripath** [comment]
> > However, if you are unwilling to try patches - I am afraid I don't know what to do.
> 
> Hm ... you are developing software or fixes without testing them? In this case you have to add new mirror and check the log.

As I said - I am unable to replicate your problem on my testing machine. 

I do not know why but the code works for me.

> I need some infos:
> 
> * should I compile the 1.16 branch? If not, which commit is it?

#19236 is the attempted fix PR backported to v1.16. Its branch name is `backport-19235-v1.16` on my fork `zeripath/gitea.git`

The github ssh url is therefore `git@github.com:zeripath/gitea` 

If you have the `gh` github cli tool:

```bash
gh pr checkout 19235
```

if you have a clone of the gitea repo you can either add my fork as a remote or use fetch to get the branch.

```bash
git fetch git@github.com:zeripath/gitea.git backport-19236-v1.16:backport-19236-v1.16
git checkout backport-19236-v1.16
make vendor
```

> * how to compile it for PostgreSQL? I'm not working with go.

```bash
TAGS="bindata sqlite sqlite_unlock_notify" make
```

You will need also need [Node.js LTS](https://nodejs.org/en/download/)

> * which go version I need?

It is probably best to just get 1.18

**Comment by somera** [comment]
hm ... I try this. My system is optimized for Java development.

It's possible to compile the code with go in docker?

`docker run --rm -i -t -v $PWD:/v -w /v golang:1.18 make`

Or you can attach an gitea-1.16.x-linux-amd64 to the ticket?

**Comment by somera** [comment]
My instance for testing hat at the moment problem with

```
2022/03/28 21:56:04 ...ervices/task/task.go:56:handle() [E] Run task failed: pq: doppelter Schlüsselwert verletzt Unique-Constraint »topic_pkey«
        /source/services/task/task.go:56 (0x1e8aa75)
        /source/modules/queue/workerpool.go:445 (0x1607ade)
        /source/modules/queue/workerpool.go:280 (0x1606c16)
        /usr/local/go/src/runtime/asm_amd64.s:1571 (0x46ffe0)
```

I updated this

- from gitea-1.14.5-linux-amd64
- to gitea-1.15.11-linux-amd64
- to gitea-1.16.5-linux-amd64

**Comment by zeripath** [comment]
`gitea doctor recreate-table topic`

**Comment by zeripath** [comment]
I've managed to hopefully create a docker image at https://eldritchkitty.com/~andrew/backport-19235-v1.16.tar.gz

**Comment by somera** [comment]
I can't reproduce the problem on my 2nd gitea 1.16.5 instance. Strange.

> I've managed to hopefully create a docker image at https://eldritchkitty.com/~andrew/backport-19235-v1.16.tar.gz

thx.
