### ISSUE TITLE
Re-editing issue should open "Write", not "Preview"

### ISSUE THREAD

**Issue by fwdekker** [go-gitea/gitea#19031]
### Gitea Version

1.15.9

### Operating System

FreeBSD 13

### Browser Version

Firefox 96.0.3

### Can you reproduce the bug on the Gitea demo site?

No
(I was unable to create an account at try.gitea.io.)

### Description

If a user edits an issue, then previews, then saves/cancels, and then edits again, the editor will start at "Preview" instead of "Write".

I think it would make more sense to forcefully jump to the "Write" tab when a user edits the contents of an issue.

### Screenshots

Not applicable.

**Comment by wxiaoguang** [comment]
->  Switch to "edit" tab when edit comment again #31445
