### ISSUE TITLE
Admin Authentication Sources pages show 500 error in some causes

### ISSUE THREAD

**Issue by wxiaoguang** [go-gitea/gitea#19036]
If there is an error occurs during `add(new)` (eg: duplicated name), then 500 error occurs during template rendering:

```
* template: admin/auth/new:17:68: executing "admin/auth/new" at <.type.Int>: can't evaluate field Int in type interface {}
* template: admin/auth/source/oauth:5:93: executing "admin/auth/source/oauth" at <.oauth2_provider.Name>: can't evaluate field Name in type interface {}
```

If the admin uses a duplicated name on the edit page, there is another 500:

```
* Error 1062: Duplicate entry 'aa' for key 'login_source.UQE_login_source_name'
```

In a word, the login source page is too complex and there are many bugs for edge cases.

**Comment by Javonne-do** [comment]
I also reported an error of 500. How is this problem solved?

**Comment by zeripath** [comment]
@Javonne-do please provide the issue number of that.
