### ISSUE TITLE
500 error while entering admin panel

### ISSUE THREAD

**Issue by musialny** [go-gitea/gitea#19057]
### Gitea Version

1.16.1

### Git Version

2.25.1

### Operating System

Ubuntu 20.04

### How are you running Gitea?

Official docker image

### Database

MySQL

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/musialny/1fe70fc57bf47e366a3052c63c6ee5c8

### Description

When I'm entering the admin panel gitea returns error 500.

**Comment by techknowlogick** [comment]
> 1.17.6

that is not a valid version. I suspect you ran into the translation bug that has been fixed in a stable version, please update to 1.16.3

**Comment by musialny** [comment]
I accidentally read Go version, after update everything works well
