### ISSUE TITLE
Documentation for SSH is not correct for Alpine linux (fixes in the description)

### ISSUE THREAD

**Issue by williamdes** [go-gitea/gitea#19065]
### Gitea Version

1.16.x

### How are you running Gitea?

Using docker compose

### Database

MySQL

### Can you reproduce the bug on the Gitea demo site?

No

### Description

I have the following error message in my logs by sshd: `fatal: reprocess config line 122: AuthorizedKeysCommand must be an absolute path`

After applying https://docs.gitea.io/en-us/install-with-docker/#ssh-shell-with-authorizedkeyscommand

What was needed on my Alpine 3.14 was this diff:
```diff
- AuthorizedKeysCommand ssh -p 2222 -o StrictHostKeyChecking=no git@127.0.0.1 /usr/local/bin/gitea keys -c /data/gitea/conf/app.ini -e git -u %u -t %t -k %k
+ AuthorizedKeysCommand /usr/bin/ssh -p 2222 -o StrictHostKeyChecking=no git@127.0.0.1 /usr/local/bin/gitea keys -c /data/gitea/conf/app.ini -e git -u %u -t %t -k %k
```
And after the forwarding worked fine after another tweak

I had this error in my logs and git clone failed fetch commands `..s/setting/setting.go:952:loadFromConf() [F] Expect user 'git' but current user is: root`
Solved by adding `-u git` in the step https://docs.gitea.io/en-us/install-with-docker/#docker-shell-with-authorizedkeyscommand
Please note on the step above the `-u git` is here, maybe this is also a mistake. See: https://docs.gitea.io/en-us/install-with-docker/#docker-shell-with-authorized_keys

**Comment by mscherer** [comment]
Given openssh man pages, this doesn't seems to be a Alpine specific issue, so I fixed the 1st issue in the doc.

**Comment by williamdes** [comment]
> Given openssh man pages, this doesn't seems to be a Alpine specific issue, so I fixed the 1st issue in the doc.

Thank you so much !

What about the `-u git` one ?

**Comment by mscherer** [comment]
For the 2nd part, I am not sure to really understand where the problem come from. Is the issue in the docker-shell wrapper, as there is already a -u on the AuthorizedKeysCommand.

If you could make a PR, it would be clearer to me

**Comment by williamdes** [comment]
> For the 2nd part, I am not sure to really understand where the problem come from. Is the issue in the docker-shell wrapper, as there is already a -u on the AuthorizedKeysCommand.
> 
> If you could make a PR, it would be clearer to me

There is no `-u git` in the shell wrapper of https://docs.gitea.io/en-us/install-with-docker/#docker-shell-with-authorizedkeyscommand
But there is one in the wrapper of https://docs.gitea.io/en-us/install-with-docker/#docker-shell-with-authorized_keys

![image](https://user-images.githubusercontent.com/7784660/158062110-db453edf-fa95-4574-ad37-0ec3c21d210c.png)
![image](https://user-images.githubusercontent.com/7784660/158062126-b52982ac-c5e4-4afb-ac23-5d024b5fe970.png)


Does it make more sense ?

**Comment by mscherer** [comment]
Seems the bug was closed by error (or rather closed automatically), I can't reopen myself it seems.

And yes, the wrapper is not the same but I wonder if it should be fixed on the Dockerfile side to force the container to run as the user git, as it would make the doc simpler.

**Comment by williamdes** [comment]
> Seems the bug was closed by error (or rather closed automatically), I can't reopen myself it seems.
> 
> And yes, the wrapper is not the same but I wonder if it should be fixed on the Dockerfile side to force the container to run as the user git, as it would make the doc simpler.

Well I tried running the container as git user and that was not the right fix for this issue, I lost quite a lot of time trying this solution.
Finally the `-u git` worked like a charm and did not destroy my setup
Would you mind making a PR for that ? (I could make one too but I am not setup for gitea dev)
