### ISSUE TITLE
Day ago count is wrong in issue comments

### ISSUE THREAD

**Issue by gayprogrammer** [go-gitea/gitea#1906]
- Gitea version (or commit ref): 1.1.1+2-g2854c8a
- Git version: 2.12.2
- Operating system: Windows Server 2012
- Database (use `[x]`):
  - [x] MSSQL
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes: https://try.gitea.io/gitpitch/code-presenting/issues/1
- Log gist: Not relevant

Today is `Wednesday June 7 (19:21:25 UTC)`. The test issue in the above linked issue was created on `Monday June 5` and was closed on `Tuesday June 6`. Here is what is displayed:
```
razzintown commented 1 day ago (Mon, 05 Jun 2017 23:52:30 UTC)
gitpitch closed 1 day ago (Tue, 06 Jun 2017 03:26:36 UTC)
```

Since `7 - 5 = 2` It should read `2 days ago` for the number of days ago it was created.

I also suggest that `1 day ago` should actually read `yesterday`.

**Comment by sondr3** [comment]
You could also use a JS library to automatically and dynamically change the time, e.g. [timeago.js](https://github.com/hustcc/timeago.js). The aforementioned library also includes translations if that's something.

This is just throwing it out there, I see that you do this when pages are requested in Gitea. GitHub uses JS as well to automatically change `datetime` elements to their correct date. I also disagree with `1 day ago` becoming `yesterday`, I'd much rather it becomes `a day ago` instead.

**Comment by gayprogrammer** [comment]
Note that at this moment, the test issue linked above is showing the days ago correctly. There may be only a short span of time where this bug shows itself, or a certain time of day. 
UPDATE: Yes, the bug in the test issue linked above appears every day.

@sondr3 I agree that using a JS library might be a better solution than having it done on the server. I am also perfectly fine with the phrase `a day ago`.

**Comment by lunny** [comment]
`yesterday` means we need a new translation item. :)

**Comment by gayprogrammer** [comment]
@lunny This is a bug. (See https://try.gitea.io/gitpitch/code-presenting/issues/1)
````
razzintown commented 1 day ago (Mon, 05 Jun 2017 23:52:30 UTC)
gitpitch closed 1 day ago (Tue, 06 Jun 2017 03:26:36 UTC)
````
Monday and Tuesday are not both `1 day ago `.

**Comment by bkcsoft** [comment]
No it's not a bug...
```
now       (07 Jun 2017 19:21:25 UTC)
1 day ago (05 Jun 2017 23:52:30 UTC)
1 day ago (06 Jun 2017 03:26:36 UTC)
```
6th 03:26 => 7th 19:21 == 1 day, 15h 55m
5th 23:52 => 7th 19:21 == 1 day, 19h 29m

So `1 day` is technically more correct than `2 days` :)

**Comment by bkcsoft** [comment]
It would however be an enhancement. But it would be very hard to do correctly... Don't want 5 minutes to show up as "1 day" (`5th 23:58 => 6th 00:03`)

**Comment by leitzler** [comment]
Wouldn't it be good start with:
< 1 minute gives "x seconds ago"
< 1 hour gives "x minutes ago"
< 24 hours "x hours ago"
And leave the rest as is, or change them to calculate number of midnights passed in browser timezone.

**Comment by sondr3** [comment]
Which is more or less what the JS libraries do.

**Comment by bkcsoft** [comment]
I agree that we should use an existing JS-lib for this. Just keep the license in mind 😉
