### ISSUE TITLE
Tarbomb in release src tarball file

### ISSUE THREAD

**Issue by eleksir** [go-gitea/gitea#19066]
### Gitea Version

1.16.3

### Git Version

N/A

### Operating System

N/A

### How are you running Gitea?

tar xf gitea-src-1.16.3.tar.gz

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

N/A

### Description

Gitea official src, gitea-src-1.16.3.tar.gz, (from releases page at [github](https://github.com/go-gitea/gitea/releases), particulary at [release of 1.16.3](https://github.com/go-gitea/gitea/releases/tag/v1.16.3)) contains [tarbomb](https://en.wikipedia.org/wiki/Tar_(computing)#Tarbomb). Such behavior is considered bad etiquette on the part of the archive's creator.

Expected behavior is (after untarring) to find this pile of files in subdir named gitea-src-1.16.3 or even better in subdir named gitea-1.16.3.

### Screenshots

N/A

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
fair point, IMO, this shouldn't be hard to fix.
what I usually tend to do anyway is automaticaly create a folder for pretty much any archive I am untarring, then use tar with `-C newfolder`. those times I forget to prepare a folder hurt, though.

**Comment by lunny** [comment]
That's generated by Github I think, maybe you should submit an issue to them?

**Comment by eleksir** [comment]
https://github.com/twpayne/chezmoi/issues/1576

absolutely same thing but it was resolved without Github intervention.

**Comment by techknowlogick** [comment]
`gitea-src-1.16.3.tar.gz` (and similar) is a custom tar that we create in the make-release step of CI, so it would need to be updated in our CI.

**Comment by zeripath** [comment]
We'd need to use `--transform` or `--xform` option in the `tar` within the `release-sources` target in the `Makefile` here:

https://github.com/go-gitea/gitea/blob/ed1d95c55dfa91d1c9a486bfb8e00375d4038e29/Makefile#L648

@eleksir would you like to test and propose a PR?
