### ISSUE TITLE
Editor won't load on PaleMoon

### ISSUE THREAD

**Issue by hiiamboris** [go-gitea/gitea#19063]
### Gitea Version

1.16.3

### Operating System

W10

### Browser Version

Pale Moon 29.4.4 x32
Pale Moon 30.0.0 x32

### Can you reproduce the bug on the Gitea demo site?

No

### Description

Editor widget won't load at all, just shows a rolling circle.

To reproduce:
1. Install PaleMoon x32
2. Try web editor on any markdown file

`try.gitea.io` only shows error 500 for me, so I cannot test there
Tested on Codeberg and on a local 1.16.3 fresh setup

This is similar to https://github.com/go-gitea/gitea/issues/13799 but this is not a cache issue AFAICT: fresh browser or private browsing mode does not fix it.

### Screenshots

![](https://i.gyazo.com/25c6ee4473e43d24385b3264e6d67351.png)

Errors on localhost:
![](https://i.gyazo.com/eb64340bff76dc2057d16d6e9f7ae862.png)
Errors on Codeberg:
![](https://i.gyazo.com/42539bf25a2418eb220eb231f149567e.png)

**Comment by wxiaoguang** [comment]
The screenshots are unrelated to Gitea.

The first screenshot shows that the ROOT_URL is incorrect.

The second screenshot shows that Codeberg's stlview doesn't work, it's not part of Gitea.

Please show the real and related logs for Gitea.

**Comment by hiiamboris** [comment]
latest version is very slow but it works

**Comment by lunny** [comment]
For the first time, it will download the editor. It's a bit big. But after cached by web browser, it will be fast next time.
