### ISSUE TITLE
default_delete_branch_after_merge doesn't work

### ISSUE THREAD

**Issue by sprnza** [go-gitea/gitea#19069]
### Gitea Version

1.16.0

### Git Version

2.30.2

### Operating System

Debian 10

### How are you running Gitea?

Gitea is running from docker container

### Database

PostgreSQL

### Can you reproduce the bug on the Gitea demo site?

Yes

### Description

I've set `default_delete_branch_after_merge` to True using this:
```
http --auth user:pass PATCH https://try.gitea.io/api/v1/repos/user/TestRepo default_delete_branch_after_merge:=true
```
got this reply:
```
HTTP/1.1 200 OK
```
But when I create a PR a get checkbox "Delete branch 'test-branch' unchecked in UI and after merge the branch is not being deleted (so it's not just an UI issue).

**Comment by noerw** [comment]
Looking at the code, I think you also need to set `"has_pull_requests": true` for changes to PR settings to have an effect:

https://github.com/go-gitea/gitea/blob/80c59672335f00283d9edd51b3490787eb28755a/routers/api/v1/repo/repo.go#L842


This doesn't seem like correct behavior to me, though changing this may be a breaking change to some.

**Comment by jolheiser** [comment]
Parent issue #13622
