### ISSUE TITLE
POPULATE_SQUASH_COMMENT_WITH_COMMIT_MESSAGES doesn't work as expected

### ISSUE THREAD

**Issue by sprnza** [go-gitea/gitea#19068]
### Gitea Version

1.16.0

### Git Version

2.30.2

### Operating System

Docker container on Debian 10

### How are you running Gitea?

Gitea is running from docker.

### Database

PostgreSQL

### Can you reproduce the bug on the Gitea demo site?

No

### Description

I added this env variable for the container:
```
      GITEA__reposiroty.pull-request__POPULATE_SQUASH_COMMENT_WITH_COMMIT_MESSAGES: "true"
```
and expect commit messages to be populated in a PR message when I click "Create Merge Commit" but currently only url to the pullrequest is being added:
```
Reviewed-on: https://gitea.host/Org/Repo/pulls/7
```

**Comment by noerw** [comment]
you have a typo in your env variable

```diff
-      GITEA__reposiroty.pull-request__POPULATE_SQUASH_COMMENT_WITH_COMMIT_MESSAGES: "true"
+      GITEA__repository.pull-request__POPULATE_SQUASH_COMMENT_WITH_COMMIT_MESSAGES: "true"
```

**Comment by sprnza** [comment]
Yeah, thanks. I've fixed it but squash comment is still not being populated for some reason.

**Comment by techknowlogick** [comment]
The env var shouldn't have an `.` in it, per https://github.com/go-gitea/gitea/tree/main/contrib/environment-to-ini it should be escaped as `0x2E`. However, even after changing that I recommend you look at your app.ini to confirm the config is as expected.

**Comment by wxiaoguang** [comment]
Please check if the config is really written into the file, refer to https://github.com/go-gitea/gitea/blob/main/contrib/environment-to-ini/README
