### ISSUE TITLE
error 500 when accessing admin dashboard after upgrade

### ISSUE THREAD

**Issue by Shea690901** [go-gitea/gitea#19074]
### Gitea Version

1.16.1

### Git Version

2.35.1

### Operating System

Gentoo Linux (kernel 5.16.10-gentoo)

### How are you running Gitea?

self build with go1.17.2
started via systemd
on Gentoo Linux

### Database

SQLite

### Can you reproduce the bug on the Gitea demo site?

Can't login

### Log Gist

https://gist.github.com/96c1dd0bf2b1908b0c0df3d50b1baa48

### Description

Since upgrading to version 1.16.1 I can't access the admin dashboard any longer.
Instead I get an error 500.
The relevant line is marked by an empty line before and after the entry.

I'm no go-programmer so I'm no real help on this front....

**Comment by lunny** [comment]
Please upgrade to v1.16.3

**Comment by Shea690901** [comment]
worked like a charm :ok_hand: 
The 1.16.1 was the newest in the package db from my distro :wink:
