### ISSUE TITLE
Gitea OIDC doesn't send bearer token 

### ISSUE THREAD

**Issue by lvelvee** [go-gitea/gitea#19073]
### Gitea Version

1.16.3

### Operating System

docker

### How are you running Gitea?

gitea v1.16.3 running in docker 

I got a 500 error when I use Open ID Connect.

In the OAuth2 server-side, I found token not presented.

Use another gitea instance as oauth server, but it's OK.

I'm not familiar with golang yet, so I have no idea debug with gitea.

the token response as follows

```json
 {
  "access_token": "...",
  "token_type": "bearer",
  "expires_in": 3600,
  "refresh_token": "",
  "id_token": ""
}
```

my oauth provider

```json
 {
  "access_token": "...",
  "expires_in": 36000,
  "token_type": "Bearer",
  "scope": "openid",
  "refresh_token": "...",
  "id_token": "..."
}
```

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

<img width="1638" alt="iShot2022-03-14 11 25 19" src="https://user-images.githubusercontent.com/25785753/158100946-aab023b5-f0ec-4c8e-8224-553f4d6c4978.png">
<img width="1656" alt="iShot2022-03-14 11 22 00" src="https://user-images.githubusercontent.com/25785753/158100955-aa81b88b-f34c-4499-bba3-147d190913eb.png">

**Comment by lvelvee** [comment]
After debugging it, I found out that it was my URL was https, but it was http in issuer.

Anyway, since I'm not familiar with golang and didn't find the specific code, it should have had a friendly hint.

**Comment by zeripath** [comment]
> Anyway, since I'm not familiar with golang and didn't find the specific code, it should have had a friendly hint.

What would be that hint? Where would you suggest it be? Any hint needs to cover a common problem - do you think your problem is that common?  From your comments I can't actually tell what the problem was...

**Comment by lvelvee** [comment]
Actually my OAuth URL is https protocol, but the URL in `.well_known/openid-configuration` is `http` protocol due to a configuration error (it's my own application, and Gitea has nothing wrong), so **no bearer token is sent to userinfo endpoint**, that's all I know...
