### ISSUE TITLE
When generating repo from template, default_branch returns as blank string

### ISSUE THREAD

**Issue by truesteps** [go-gitea/gitea#19082]
### Gitea Version

1.16.3

### Git Version

2.25.1

### Operating System

Ubuntu 20.04.3 LTS (Focal Fossa)

### How are you running Gitea?

I'm running gitea from the binary, through systemctl. I installed it from a tutorial I found online, recently updating it to the latest version, so I can use the generate repo endpoint.

### Database

MySQL

### Can you reproduce the bug on the Gitea demo site?

Yes

### Description

Whenever I create a new repo from a template repo, I get back the repository detail as the request response, but the `default_branch` property is returned as an empty string. I think It should be the default branch, since when I fetch the detail of it in the next request, it's there, therefore I concluded this is a bug.

Allow me to send a gist with the entire response from the API [https://gist.github.com/truesteps/43b4b13ac3619c92cbdc70c5622c6e02](https://gist.github.com/truesteps/43b4b13ac3619c92cbdc70c5622c6e02)

### Screenshots

![Screenshot 2022-03-14 at 16 08 41](https://user-images.githubusercontent.com/12614944/158201589-15bc3280-689e-424b-8ed7-aeeccf92acad.png)

**Comment by ADawesomeguy** [comment]
https://github.com/go-gitea/gitea/blob/60fbaa90683add2a8af891fc2ca8448b9b75c92e/routers/api/v1/repo/repo.go#L425 not sure, but I think the issue stems from here where the created `repo` object does not have that value and is created by https://github.com/go-gitea/gitea/blob/60fbaa90683add2a8af891fc2ca8448b9b75c92e/modules/repository/generate.go#L244-L257

**Comment by truesteps** [comment]
@ADawesomeguy I think it would make perfect sense to include the default_branch... Maybe even an option to define default_branch? 👼

**Comment by ADawesomeguy** [comment]
I just had the generated repo define its default branch using the template repo's default branch, so hopefully that should work @truesteps.

**Comment by truesteps** [comment]
@ADawesomeguy I have an app where I use the api to generate new repos from templates or as blank repos, and you can select the default branch of the generated repo, and because it defaults to template default branch, I need to create new branch, change it to default, remove master basically :). It's a workable workaround It just feels like too many extra steps where it could fail for a basic operation.

Thanks for the tip tho!

**Comment by ADawesomeguy** [comment]
@truesteps wait sorry could you explain that again? I'm a bit confused as to what you want but I'd be happy to give implementing the ideal situation a shot even though I'm a bit lacking in experience.

**Comment by truesteps** [comment]
Basically I would love to be able to pass a default_branch argument to the generate function, so the generated repo has a specific default branch, if left empty, defaults to default branch in template as the current behaviour dictates.

**Comment by ADawesomeguy** [comment]
Awesome, I'll see if I can add that to my PR.

**Comment by truesteps** [comment]
@ADawesomeguy thanks dude :) 👍
