### ISSUE TITLE
 Feed Support for Releases / Tags

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#19091]
as title

basic support for feeds was added at  #569, to get backend information, just look at the 3 related pulls

**Comment by oGi4i** [comment]
The current implementation of the repo feed actually already has events about tags and releases based on actions:
- ActionPushTag
- ActionDeleteTag
- ActionPublishRelease

**Comment by KevinSJ** [comment]
hello, @oGi4i is correct in that the current repo feed already include the tags and releases based on acations. Is this issue about a separate feed for the release and tag only? I can give it a go, if we have a conclusion on this.

**Comment by 6543** [comment]
:point_up: yes it is ... the main difference will be that you should use model.release and tag info directly ...
since actions can be purged and so are not that accurate long term

**Comment by reopt999** [comment]
Hi, I would like to work on this issue

**Comment by ilf** [comment]
It would be great to have (RSS|Atom)-Feeds for Releases (and other events). It's really helpful to subscribe to https://github.com/go-gitea/gitea/releases.atom

Actually it's kind of surprising this doesn't exist yet. So thanks for working on this!
