### ISSUE TITLE
Features of gitea

### ISSUE THREAD

**Issue by sakshi1225** [go-gitea/gitea#1909]
Hi Team,

I would like to know if below features are available in gitea : 

Git Repo hosting
Web based SCM hosting software
Local Repo Administration
Support for Microsoft Active Directory
User Roles
Merge Request Reviewer
Protect direct push on master
Leaving comments on Merge Request
Merge Request Diffs
Cherry pick changes from UI
Revert patch/merge request/pull Changes From UI
Integration with other build server
Support for Private Repositories
Notifications-Issue/Merge request events
Backup and DR

**Comment by bkcsoft** [comment]
- [x] Git Repo hosting
- [x] Web based SCM hosting software
- [ ] (UNSURE) Local Repo Administration
- [x] Support for Microsoft Active Directory
- [x] User Roles
- [ ] Merge Request Reviewer
- [x] Protect direct push on master
- [ ] Leaving comments on Merge Request
- [x] Merge Request Diffs
- [ ] (UNSURE) Cherry pick changes from UI
- [ ] (UNSURE) Revert patch/merge request/pull Changes From UI
- [x] Integration with other build server
- [x] Support for Private Repositories
- [x] Notifications-Issue/Merge request events
- [ ] Backup and DR

**Comment by soyuka** [comment]
Hi! Do you guys now if someone is working on "Leaving comments on Merge Request"? IMO this would be a really big step forward to give ppl a fully-featured tool to replace gitlab/github :).

**Comment by lunny** [comment]
@soyuka as I know, nobody currently are working on that.

**Comment by bkcsoft** [comment]
@soyuka There is a big conversation on how to implement code comments in #189 . I think there's also an open pull-request for it, but it seems stalled.

**Comment by techknowlogick** [comment]
Can this ticket be closed?

**Comment by alexanderadam** [comment]
I just stumbled over this and

> Cherry pick changes from UI

is also handled in #3880

**Comment by lafriks** [comment]
https://docs.gitea.io/en-us/comparison/
