### ISSUE TITLE
500 Error on Admin 

### ISSUE THREAD

**Issue by tixlegeek** [go-gitea/gitea#19095]
### Gitea Version

1.16.1

### Operating System

Debian 11

### Browser Version

Firefox 91.7.0esr (64 bits)

### Can you reproduce the bug on the Gitea demo site?

No

### Description

Suddenly, i can't access administration page on a self hosted gitea. The rest of the app seems ok. Here is what the log says:
```
2022/03/15 17:22:32 cmd/web.go:208:listen() [I] Listen: http://0.0.0.0:3000
2022/03/15 17:22:32 cmd/web.go:212:listen() [I] AppURL(ROOT_URL): http://git.XXXXXXXX.local/
2022/03/15 17:22:32 ...s/graceful/server.go:61:NewServer() [I] Starting new Web server: tcp:0.0.0.0:3000 on PID: 69726
2022/03/15 17:22:36 ...s/context/context.go:206:HTML() [E] Render failed: template: admin/dashboard:8:90: executing "admin/dashboard" at <Str2html>: invalid value; expected string
```

This happened without any major action 

thanks!

### Screenshots

![500](https://user-images.githubusercontent.com/5763595/158426256-8f4ab90f-bbd3-4117-9ab6-d70ac024b752.png)

**Comment by techknowlogick** [comment]
Please update to latest version (1.16.4), this has been resolved.
