### ISSUE TITLE
access log configuration not as expected - Unable to stop unwanted Started GET / Completed GET lines

### ISSUE THREAD

**Issue by mjevans** [go-gitea/gitea#19105]
### Gitea Version

1.15.11 built with GNU Make 4.3, go1.17.6 : bindata, sqlite, sqlite_unlock_notify, pam

### Git Version

2.35.1

### Operating System

Arch Linux

### How are you running Gitea?

An Archlinux Linux provided systemd service which launches gitea as:

/usr/bin/gitea web -c /etc/gitea/app.ini

### Database

SQLite

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/mjevans/cee0ec30575b53e77668ba9fc1cf1be2

### Description

I've skimmed https://docs.gitea.io/en-us/logging-configuration/ for any keywords that seem remotely relevant and tried every sort of logging configuration I can think of.  Even when everything is set to Critical only the logs still needlessly record every get and put, twice.

I'd still like to capture any output that indicates a problem might exist, but to help me see if a problem exists I want the haystack to be smaller.  The Started GET Completed GET status lines are surely supposed to be INFO level right?  Or maybe there's some specific logging facility that isn't obvious?

**Comment by techknowlogick** [comment]
You are using an out of date version of Gitea, please update to latest stable (1.16.4) and then reopen if you still experience the above

**Comment by mjevans** [comment]
The Archlinux package was already marked stale, and while I updated the git sha hash to checkout in the build script it doesn't produce a working package; probably missing or incorrect build dependencies.

So I grabbed a binary from the site and dropped it over the broken gitea that had been installed.

A new comment has been added to the old gist; the problem persists.

https://gist.github.com/mjevans/cee0ec30575b53e77668ba9fc1cf1be2

Mar 16 08:48:11 gitea gitea[39656]: 2022/03/16 08:48:11 ...dules/setting/log.go:283:newLogService() [I] Gitea v1.16.4 built with GNU Make 4.1, go1.17.8 : bindata, sqlite, sqlite_unlock_notify

It's also unclear _what_ log facility is generating any of these lines.  They're prefixed go logging timestamps, the pid, an additional timestamp, and then the message.  No indication of the facility or log level like traditional syslog entries.
