### ISSUE TITLE
Repository stars and watchers routes are allowed to access for all users even with no access to repository

### ISSUE THREAD

**Issue by lafriks** [go-gitea/gitea#1911]
Repository stars and watchers routes are allowed to access for all users even with no any unit rights to repository where all other repository URL's would return 404

**Comment by lunny** [comment]
There is no unit to include this two routes.

**Comment by lafriks** [comment]
Yes, but at least it should be checked just like home handler on len repository units > 0

**Comment by lunny** [comment]
Should be fixed by #5314, close now and please feel free to reopen it.
