### ISSUE TITLE
Plantuml not rendering in Readme only in Issues and Wiki 

### ISSUE THREAD

**Issue by lukaskwkw** [go-gitea/gitea#19110]
### Gitea Version

1.16.4

### Git Version

2.30.2

### Operating System

Windows 11

### How are you running Gitea?

Docker image

### Database

PostgreSQL

### Can you reproduce the bug on the Gitea demo site?

No

### Description

PlantUML rendering is only working in Issues & Wiki. Not in README.md files.  

I.e. using  code in README.md

` ```plantuml`
`@startuml`
`Bob -> Alice : hello`
`@enduml`
` ``` ` 

will generate `<code>` block with ` language-plantuml` class but won't render any content in if body
```go
{{if .RequireHighlightJS}}
nothing here
{{end}}
```

I was able to workaround this by adding `PageIsViewCode ` condition into if statement from docs example:
 https://docs.gitea.io/en-us/customizing-gitea/#example-plantuml

```go
{{if or .PageIsViewCode .RequireHighlightJS}}
```

It might be similar to https://github.com/go-gitea/gitea/issues/12307

### Screenshots
with single `RequireHighlightJS` condition
![obraz](https://user-images.githubusercontent.com/12010980/158662468-fc9a2039-9427-4808-9d3a-7345f6936b7b.png)
with addtional `PageIsViewCode ` condition
![obraz](https://user-images.githubusercontent.com/12010980/158662784-cc3752ff-15b0-4e4c-a41a-2bd1958ac57c.png)

**Comment by silverwind** [comment]
We should probably remove `RequireHighlightJS` and instead suggest to always just call `parsePlantumlCodeBlocks`. We're not even using higlight.js anymore.

**Comment by zeripath** [comment]
> We should probably remove `RequireHighlightJS` and instead suggest to always just call `parsePlantumlCodeBlocks`. We're not even using higlight.js anymore.

Yeah I suspect we should just drop the RequireHighlightJS things from our templates.

@lukaskwkw you should be fine to just remove the requirement on the RequireHighlightJS from your pages - an alternative option might be to also detect IsMarkup in addition to RequireHightlightJs and perhaps we should migrate all places that use RequireHighlightJS to IsMarkup instead.

**Comment by lunny** [comment]
Looks like `RequireHighlightJS` could be removed, no standard template use that now.

**Comment by lunny** [comment]
`IsMarkup` is still not accurate. We need to detect all markdown sections which has `plantuml` code blocks.

**Comment by silverwind** [comment]
I think JS should just execute `document.querySelector('language-plantuml')` only, no need to hand-hold it via template variables.

**Comment by zeripath** [comment]
@silverwind do you want to propose a documentation update PR?

**Comment by silverwind** [comment]
Yes, once I figure out something that works.

**Comment by wxiaoguang** [comment]
@lukaskwkw try this one (the example works for 1.16.x)
* #19615

And please help to report or fix potential problems in it.

**Comment by lunny** [comment]
Since it's a break change, maybe we don't need to back port to v1.16
