### ISSUE TITLE
Allow Gitea to use local folders that already exist

### ISSUE THREAD

**Issue by DUOLabs333** [go-gitea/gitea#19114]
### Feature Description

I self-host Gitea on the same computer where my repos are stored. This causes unnecessary duplication of space, as the repos are clone from my "Repos" folder to the gitea folder. Is there a way for gitea to just use my "Repos" folder instead?

**Comment by lafriks** [comment]
No it's not possible because gitea stores repositories in bare format that is different as cloned/checked out format
