### ISSUE TITLE
Updated text lost on Save when editing existing issue

### ISSUE THREAD

**Issue by aschrijver** [go-gitea/gitea#19126]
### Gitea Version

1.16.4+35-gafe98af

### How are you running Gitea?

This issue refers to Gitea as run on [Codeberg](https://codeberg.org) where I am user 'circlebuilder'.

### Can you reproduce the bug on the Gitea demo site?

No

### Description

**Occurrence**: The issue I am reporting I have now experienced a total of about 4 times, but I cannot reproduce it unfortunately. Always takes me off guard.

**Background**: In various repo's on Codeberg I regularly update existing issues by adding additional information to them by clicking 'Edit'. They contain nothing special, just markdown and regular English text. I feel the bug occurs when on issues that already contain longer text amount (say ~2 full pages of printed text), and likely also when adding more than just a single bullet point to a list.

**Bug**: I click edit and at the bottom of the text add a bunch of additions. Often bullet-formatted. Between editing I switch browser tabs (Firefox 96.0 on Ubuntu) and copy/paste plain text. When done I click 'Save' and ... the issue is in its old state before I started editing. The text is lost, and no error message is shown.

Until now every time I was aghast and pushed the browser's Back button in hopes it would bring back the issue form in edit mode (as what Github does), but Gitea doesn't support that and leads back to the issue list. So I have to type anew (though now I've come to conclusion that I should really use different tools than Gitea as the current work method is too unreliable).

Issue happened just now, but in a private repo, so I cannot include the URL. Note that other times I experienced this it was on older version than current 1.16 release.

**Comment by aschrijver** [comment]
@fnetX on [the related Codeberg issue](https://codeberg.org/Codeberg/Community/issues/600) pointed out that this is likely the CSRF token that expires, as reported in #17850

I don't know the expiration timeout, but I was indeed having the issue in Edit-mode for more than just a couple of secs. Maybe half an hour.

**Comment by wxiaoguang** [comment]
More details:
* https://github.com/go-gitea/gitea/issues/17850
