### ISSUE TITLE
Push activity doesn't show up in overview page on try.gitea.io

### ISSUE THREAD

**Issue by nidico** [go-gitea/gitea#19143]
### Gitea Version

1.17.0+dev-298-g7fc5fd641

### How are you running Gitea?

Using try.gitea.io

### Can you reproduce the bug on the Gitea demo site?

Yes

### Description

Commiting to the (public) repo https://try.gitea.io/nidi/gitea-issue-reproduction/ to any branch doesn't lead to those commits showing up in the activity overview or contributions heatmap of [my user](https://try.gitea.io/nidi?tab=activity) or on the overview page (https://try.gitea.io).

This doesn't happen on a gitea installation (version 1.16.4) though.

I just accidently figured that out when trying to reproduce another issue, which occured on the 1.16.4 installation, on try.gitea.io.

### Screenshots

![gitea-missing-git-push-activity](https://user-images.githubusercontent.com/457147/159126165-7c1c10d0-384a-4d89-a909-ef3e76eed072.png)

**Comment by zeripath** [comment]
OK - so I can't replicate this locally so I think this must be something to do with the current set-up of try itself. 

I'll investigate further.

**Comment by zeripath** [comment]
This was a docker version issue.
