### ISSUE TITLE
Remove read permission from private repositories

### ISSUE THREAD

**Issue by dexgs** [go-gitea/gitea#19148]
### Feature Description

Currently, when a repository is marked private, its permissions on the host filesystem are still drwxr-xr-x. It would be nice if this were not the case and the read permission for other users was removed as it would allow the privacy of repositories to be maintained when displaying the git repositories with an alternative front-end such as cgit.

**Comment by techknowlogick** [comment]
Thanks for the suggestion, the storage of the git repos are treated as internal to git and not meant to be used by any other tool. There is also a potential plan to eventually shard the directories so it wouldn't be in the user/repo format anymore.
