### ISSUE TITLE
[Feature Request] Push notifications by administrator/console

### ISSUE THREAD

**Issue by Glavo** [go-gitea/gitea#19157]
### Feature Description

Currently, the Notifications feature of Gitea only supports automatic notifications and cannot be sent manually by the administrator. I wish Gitea would support the ability to send notifications manually, and supports preset notification templates to send specific notifications for each newly registered user.

**Comment by wxiaoguang** [comment]
Dup:
* https://github.com/go-gitea/gitea/issues/2345
