### ISSUE TITLE
Unable to clone repo via SSH [Podman pod, rootless container]

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#19150]
### Gitea Version

1.16.4

### Git Version

2.30.2

### Operating System

Podman rootless container on openSUSE MicroOS host

### How are you running Gitea?

I am running my self-hosted Gitea instance on home server. I create simple script to run Podman's [pod](https://developers.redhat.com/blog/2019/01/15/podman-managing-containers-pods#) with Postgre and Gitea-rootless container behind Caddy reverse proxy

``` bash
#!/usr/bin/env bash
set -e
podman pod create --infra -n gitea -p 3000:3000 -p 2222:2222

podman run --pod gitea --name db \
       -e POSTGRES_USER=db \
       -e POSTGRES_PASSWORD=somePassword \
       -e POSTGRES_DB=giteadb \
       -e PGDATA=/var/lib/postgresql/data/pgdata \
       -v db-data:/var/lib/postgresql/data \
       -d docker.io/library/postgres

podman run --pod gitea --name app \
       -e DB_TYPE=postgres \
       -e DB_HOST=localhost:5432 \
       -e DB_NAME=giteadb \
       -e DB_USER=db \
       -e DB_PASSWD=somePassword \
       -v gitea-data:/var/lib/gitea \
       -v gitea-config:/etc/gitea \
       -d docker.io/gitea/gitea:latest-rootless
```

Caddyfile
```
my.gitea.instance:443 {
	reverse_proxy HOST_IP:3000
}
```

I use built-it SSH server so in installation wizard on browser I put port 2222 in config and my domain name
``` ini
[server]
...
SSH_DOMAIN              = my.gitea.instance
HTTP_PORT               = 3000
ROOT_URL                = https://my.gitea.instance/
DISABLE_SSH             = false
...
START_SSH_SERVER        = true
SSH_PORT                = 2222
SSH_LISTEN_PORT         = 2222
BUILTIN_SSH_SERVER_USER = git
...
DOMAIN                  = my.gitea.instance
```

### Database

PostgreSQL

### Can you reproduce the bug on the Gitea demo site?

No

### Description

I've setup added server, user and port in my `sshd_config`, added my public key to my user account, created repo and during clone I received an error:
``` bash
> git clone ssh://git@my.gitea.instance:2222/asterops/test.git
Cloning into 'test'...
git@my.gitea.instance: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
On the Gitea's log I see only these two lines (I've increased log level to debug):
``` bash
2022/03/20 11:23:56 modules/ssh/ssh.go:260:sshConnectionFailed() [W] Failed connection from 10.0.2.100:36362 with error: [ssh: no auth passed yet]
2022/03/20 11:23:56 modules/ssh/ssh.go:262:sshConnectionFailed() [W] Failed authentication attempt from 10.0.2.100:36362
```
I also manually run `Update the '.ssh/authorized_keys' file with Gitea SSH keys.` cron task from UI but it didn't change anything. What else can I check?

**Comment by v4dkou** [comment]
Similar issue on `gitea/gitea:1.16.5-rootless` with Docker

Whenever I run the `Update the '.ssh/authorized_keys' file with Gitea SSH keys.` task, I see an error that reads
`2022/03/27 13:14:14 ...rvices/cron/tasks.go:114:GetTask() [I] Getting resync_all_sshkeys in &{{0 0} resync_all_sshkeys 0xc0054dea20 0x1e5ef60 0}`

I've checked the file and it's not being updated.
I am mounting the /data/git/.ssh/ folder as per the official tutorial, so 
`docker exec gitea cat /data/git/.ssh/authorized_keys` is the same as `cat /home/git/.ssh/authorized_keys`

**Comment by techknowlogick** [comment]
> I also manually run Update the '.ssh/authorized_keys' file with Gitea SSH keys. cron task from UI but it didn't change anything. What else can I check?

Rootless doesn't use the authorized_key file as it runs an SSH server internal to the golang binary and fetches keys directly from the database.

You mention changing ssh**d**_config, can you provide more details on that, as above opensshd is not used. Do you mean your `~/.ssh/config`?

Are you able to attempt connecting using ssh directly (`ssh -vvv -p 2222 git@example.com`)? This will give more details on if the expected key is being sent.

**Comment by polyurethanegoose** [comment]
@AsterOps Please verify that this is not connected to issue #17175 I've got the same problem with same message in logs with rootless Podman container and found out that i had to add `-o PubkeyAcceptedKeyTypes=+ssh-rsa -o PubkeyAcceptedAlgorithms=+ssh-rsa` to my clone commands.

**Comment by fengjiongmax** [comment]
I have a similar issue but I'm not sure if I have the same environment( search keyword `no auth passed yet` brought me here).

my environment is with truenas scale box and gitea installed via [truenas charts](https://truecharts.org/apps/stable/gitea/).

After a fresh install, I add the ssh pub key from gitea web UI, and `ssh [git@gitea] -T` failed.

[ssh log with ssh info defined in .ssh/config](https://gist.github.com/fengjiongmax/ae81f2ae2f18016178ba224d5d4a3ac0#file-ssh-vvv)
[ssh log file with bare ssh command](https://gist.github.com/fengjiongmax/ae81f2ae2f18016178ba224d5d4a3ac0#file-ssh-vvv-with-ip)

gitea log shows the same warning as OP.

I tried to verify the private key in the web UI and failed.

is there anything I can do to provide more information?

**Comment by wxiaoguang** [comment]
About the problem for rootless container:
* https://github.com/go-gitea/gitea/issues/17798

This issue is inactive for long time and Gitea 1.16.x is out-dated. Feel free to re-open or open a new issue if there is any other problem.
