### ISSUE TITLE
Documentation should be more explicit, that things like LOCAL_ROOT_URL require a trailing slash

### ISSUE THREAD

**Issue by p-kraszewski** [go-gitea/gitea#19166]
### Feature Description

Hey y'all!

Thank you for an excellent project!

However, I've spent most of the today chasing, why any access via `ssh://` ended with uninformative "_Internal error_". Only after enabling `dev` mode and `trace` logging level it appeared `gitea serv` connected back to the daemon with wrong path.

DOC/FAQ should be **much** more explicit, that `LOCAL_ROOT_URL` should be a path to `gitea` web interface reachable from localhost and **must** have a trailing slash (this may be the case of you concatenating path elements manually instead of using `path.Join(...)`)

**Comment by silverwind** [comment]
I think we better just append that slash to the parsed variable if it's really crucial.

**Comment by p-kraszewski** [comment]
That's one way. 

```go
if !strings.HasSuffix(setting.LocalURL,`/`){
   setting.LocalURL=setting.LocalURL+`/`
}
```

Another way is to avoid things like
```go
reqURL := setting.LocalURL + "api/internal/mail/send"
```

and replace it with
```go
// I'm not sure of the performance impact
reqURL := path.Join(setting.LocalURL,"api/internal/mail/send")
```
or
```go
// Double slash would do no harm and relative paths aren't valid here.
reqURL := setting.LocalURL + "/api/internal/mail/send"
```

**Comment by p-kraszewski** [comment]
Wow, that escalated quickly...
