### ISSUE TITLE
Allow users to choose issue template from Project view, when clicks New Issue button

### ISSUE THREAD

**Issue by donkeylobster** [go-gitea/gitea#19170]
### Problem

_New Issue_ button in project view dose not let you select issue template. 

Now Gitea doesn't support to choose issue template in the Project UI. A button pointing to the `/org/repo/issues/new/choose` should be put there to allow users to create issues from templates.

### Example
- Open a project (eg. https://try.gitea.io/thomas/test3/projects/1872 )
- Press _New Issue_
- New default issue is created (no way to choose the issue template)

### Expected

Template selection, like when pressing _New Issue_ on Issues page (eg. https://try.gitea.io/thomas/test3/issues )

### Can you reproduce the bug on the Gitea demo site?

Yes

**Comment by wxiaoguang** [comment]
> Can you reproduce the bug on the Gitea demo site?
> Yes ..........

HOWEVER, you didn't follow the Gitea document: https://docs.gitea.io/en-us/issue-pull-request-templates/


![image](https://user-images.githubusercontent.com/2114189/159498575-eb0139e3-0755-4223-b38d-a9f6c69e2f2b.png)

**Comment by wxiaoguang** [comment]
Well, it's about sub-directory, not sure whether it is really a bug for the latest development branch .... 😂

**Comment by donkeylobster** [comment]
I noted 1.18 as that is current version at https://try.gitea.io/
Same problem is in 1.17.8 at my local installation.

**Comment by wxiaoguang** [comment]
I believe it's not a bug but a unimplemented feature (enhancement)

The story is: now Gitea doesn't support to choose issue teamplate in the Project UI. So, a button pointing to the `/org/repo/issues/new/choose`  should be put there.

**Comment by zeripath** [comment]
> I believe it's not a bug but a unimplemented feature (enhancement)
> 
> The story is: now Gitea doesn't support to choose issue teamplate in the Project UI. So, a button pointing to the `/org/repo/issues/new/choose` should be put there.

We'd need to pass the project id along in choose.
