### ISSUE TITLE
Repository can not be cloned

### ISSUE THREAD

**Issue by JHenneberg** [go-gitea/gitea#19198]
### Description

Cloning a repository which is bigger then 1Gb results in the following error, all other repositories can be cloned:

```
remote: Enumerating objects: 34305, done.
remote: Counting objects: 100% (34305/34305), done.
remote: aborting due to possible repository corruption on the remote side.

fatal: early EOF
fatal: fetch-pack: invalid index-pack output
```

Fetchging to an already existing same repository is working flawlessley. It does not matter if the connections is established in the internal or outside network.

According to the following link:
https://confluence.atlassian.com/bitbucketserverkb/git-clone-fails-fatal-the-remote-end-hung-up-unexpectedly-fatal-early-eof-fatal-index-pack-failed-779171803.html
it can be a nginx server configuration limiting to 1Gb, 

### Gitea Version

1.16.5

### Can you reproduce the bug on the Gitea demo site?

Yes 
https://try.gitea.io/JHenneberg/repo_bigger_then_1gb.git

### How are you running Gitea?

Running in Docker

**Comment by techknowlogick** [comment]
<img width="683" alt="image" src="https://user-images.githubusercontent.com/164197/163050990-0aa3520c-5502-41a1-9cd8-2ab62909a1bc.png">

It may be related to your network connection, as I was able to clone from try.gitea.io without issue.

**Comment by JHenneberg** [comment]
Yeah seems to be a network issue as I am able to pull this repo from a different location.

**Comment by theoryshaw** [comment]
Curious too.  Having the same problem.

**Comment by JHenneberg** [comment]
For me it was the VPN connection to our internal network where gitea is hosted.
