### ISSUE TITLE
Reference pull request in merge commits

### ISSUE THREAD

**Issue by tobias--** [go-gitea/gitea#1919]
- Gitea version (or commit ref): 1.1.1
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

It would be great if merge commits would reference the ID of the pull request and/or the title of a pull request. 

GitHub uses a pattern similar to this:
```
Merge pull request #{PR_ID} from {branch}

{PR_title}
```

**Comment by bkcsoft** [comment]
IMO we should just make templates for this. So they could be localized as well 😉

**Comment by 6543** [comment]
feature is in master
