### ISSUE TITLE
Please issue docker images before releasing security patches

### ISSUE THREAD

**Issue by erikh** [go-gitea/gitea#19193]
### Feature Description

Currently, there have been multiple instances where gitea releases have been cut and I have been notified of their release, with full security details, and no docker image to pull. The latest example is today, but I suspect this is just a timing issue of CI or what-have-you. I'm not really upset about this other than it really makes it hard to track releases in a security-minded manner for services that are exposed to the internet.

Thank you for considering my griping; I don't have anything else to add here.

**Comment by techknowlogick** [comment]
This was previously the case where the release email went out after CI, however github changed their behaviour where they send an email on tag, instead of release. As long as we use GitHub we are beholden to their changes. However the migration to gitea.com is very much in progress.

**Comment by erikh** [comment]
gotcha; thanks for the response!
