### ISSUE TITLE
系统正在运行的时候 是不是不可以备份 ？

### ISSUE THREAD

**Issue by jiaomy2016** [go-gitea/gitea#19199]
### Description

如图，
如果不关掉服务一直有这个错误

[https://aws1.discourse-cdn.com/standard10/uploads/gitea/original/2X/8/8fd5a8851676f201f043b056d991a1974899fdd3.png](https://aws1.discourse-cdn.com/standard10/uploads/gitea/original/2X/8/8fd5a8851676f201f043b056d991a1974899fdd3.png
)

[https://discourse.gitea.io/t/topic/4878/5](https://discourse.gitea.io/t/topic/4878/5)

### Gitea Version

1.16.4

### Can you reproduce the bug on the Gitea demo site?

Yes

### Git Version

Git-2.32.0-64-bit

### Operating System

windows

### How are you running Gitea?

使用的是咱们官网上的安装包

gitea-1.16.4-windows-4.0-amd64.exe

**Comment by wxiaoguang** [comment]
是
