### ISSUE TITLE
Switch to bootstrap CSS

### ISSUE THREAD

**Issue by tboerger** [go-gitea/gitea#192]
As discussed on Gitter we would like to switch entirely to bootstrap and use [this](http://scottdorman.github.io/bootstrap-flat/theme/) custom theme to keep it as a flat UI.

**Comment by nounoursheureux** [comment]
I like this theme :+1:

**Comment by lunny** [comment]
Or could we let user change their theme on the admin panel?

**Comment by lunny** [comment]
Looks awesome.

**Comment by tboerger** [comment]
Yeah, if this is manageable we can add a theme selection later on.

**Comment by tboerger** [comment]
Project is dead, close.
