### ISSUE TITLE
Terraform Provider

### ISSUE THREAD

**Issue by malarinv** [go-gitea/gitea#19204]
### Feature Description

I am looking for a terraform provider similar to [terraform-provider-github](https://github.com/integrations/terraform-provider-github) for provisioning _git resources_ from gitea. I discovered [terraform-provider-gitea](https://gitea.com/gitea/terraform-provider-gitea), but it seems inactive(or maybe the author has writer's block? :stuck_out_tongue: ) If it exists, I might work on building a [crossplane](https://crossplane.io/) [terrajet](https://github.com/crossplane/terrajet) provider for gitea. (un)likes of [crossplane provider-github](https://github.com/crossplane-contrib/provider-github)

**Comment by noerw** [comment]
@techknowlogick do you have a status update on that project?

**Comment by techknowlogick** [comment]
Yup, I had done some work, but didn't end up pushing it up. Ive just pushed what I had, and updated it to use latest SDK, may not be in the best place right now, but am very happy to accept PRs for additional data sources/resources/etc.. and also CI tests to verify functionality.

Closing this, as now any tickets in regards to terraform can be opened in the linked repo above.
