### ISSUE TITLE
Gitignore, README.md, label templates

### ISSUE THREAD

**Issue by viktike** [go-gitea/gitea#1920]
- Gitea version (or commit ref): 4a3f404
- Git version: 2.7.4
- Operating system: Ubuntu 16.04 LTS
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

Please provide instructions how to use templates for issue label sets, gitignores and readmes.
I tried to place them into relevant subdirectories under custom/conf/, later just conf/, but they don't show up on the webui either way. This was the place where I used them with Gogs.

I think the issue label sets must be working, since it has a list on the webui with just one (Default) option.

I also think, that I'm doing nothing wrong here, and this is actually a bug, and not the lack of instructions.

Thanks.

**Comment by cez81** [comment]
Place in folders under custom/options/ eg. labels in custom/options/label/

**Comment by viktike** [comment]
Very well, it works. I had no idea about the /options/ part, and didn't find it anywhere.

**Comment by HarvsG** [comment]
Is there a way to make a default for each of these that is automatically selected and make the:
- [ ] Initialize Repository (Adds .gitignore, License and README)

checked by default?

**Comment by nguyenxndaidev** [comment]
> Is there a way to make a default for each of these that is automatically selected and make the:
> 
> * [ ]  Initialize Repository (Adds .gitignore, License and README)
> 
> checked by default?

This would be an extremely useful feature!

Otherwise, I guess user must manually modify the default template https://github.com/go-gitea/gitea/blob/master/templates/repo/create.tmpl and add it to custom/templates directory :-(

**Comment by zeripath** [comment]
@nguyenxndaidev editing the template is probably the correct thing to do.
