### ISSUE TITLE
xorm/router logs will be not rotated

### ISSUE THREAD

**Issue by somera** [go-gitea/gitea#19200]
### Description

This

```
[log]
MODE             = file,file-servicesmirror
MAX_DAYS         = 15
LEVEL            = Error
ROOT_PATH        = /var/lib/gitea/log
ROUTER           = file
STACKTRACE_LEVEL = Error
XORM             = file

[log.file.xorm]
FILE_NAME        = xorm.log
STACKTRACE_LEVEL = Error

[log.file-servicesmirror]
MODE       = file
FILE_NAME  = servicesmirror-trace.log
LEVEL      = Error
EXPRESSION = services/mirror
```

is my log configuration. The xorm/router logs were created on 27.02.2022 and are not rotated. But this works for the other logs.

### Gitea Version

1.16.4

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![image](https://user-images.githubusercontent.com/8334250/159926603-4989b6a2-675a-4702-92a3-309f4c40ea59.png)

### Git Version

2.25.1

### Operating System

Ubuntu 20.04.4

### How are you running Gitea?

Self hosted 

### Database

PostgreSQL

**Comment by zeripath** [comment]
Did you try adding the `MAX_DAYS` to the `log.file.xorm` ini section?

```ini
...

[log.file.xorm]
FILE_NAME        = xorm.log
STACKTRACE_LEVEL = Error
MAX_DAYS         = 15
```

**Comment by somera** [comment]
> Did you try adding the `MAX_DAYS` to the `log.file.xorm` ini section?
> 
> ```ini
> ...
> 
> [log.file.xorm]
> FILE_NAME        = xorm.log
> STACKTRACE_LEVEL = Error
> MAX_DAYS         = 15
> ```

No, cause this is defined in

```
[log]
MAX_DAYS         = 15
```

like here https://docs.gitea.io/en-us/logging-configuration/#file-mode and this will be used by [log.file-servicesmirror]. Can you see in the screenshot.

But now I added it and I will see what would happen.

And what should I add for router.log? This is defined in [log] and should be rotated every 15 days too.

**Comment by somera** [comment]
With the "new" config parameter it works.
