### ISSUE TITLE
Hooks UI is broken Chrome on macOS

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#1921]
https://try.gitea.io/org/gitea/settings/hooks

**Comment by mjwwit** [comment]
Is this still an issue? I just checked on https://try.gitea.io and it looks just fine using Chrome on macOS... If it's still an issue, could you make a screenshot?

**Comment by lunny** [comment]
![untitled](https://user-images.githubusercontent.com/81045/27063371-e7c91e60-5023-11e7-8bbb-7cf7317139c5.png)

The org hooks setting page, not repository hooks setting page.
