### ISSUE TITLE
[Telegram] Webhook "Active" flag ignored

### ISSUE THREAD

**Issue by bryanpedini** [go-gitea/gitea#19220]
### Description

I noticed that after configuring a Telegram webhook, new repos in a private org trigger the webhook too, even private repos themselves (but this is a separate issue).

I then disabled the webhook by unflagging the "Active" section in the webhook settings, tho it still sends out Telegram messages via the bot.

In the logs I flag the webhook enabled, save the webhook configuration, disable it again and save it again, create a test repository, and finally delete it.

### Gitea Version

1.16.5

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/bryanpedini/3f191cf3b8ae706541f511e809961282

### Screenshots

N/A

### Git Version

2.20.1

### Operating System

Debian 10 + official Docker image

### How are you running Gitea?

Docker Compose stack: [deployments/gitea](https://git.bjphoster.com/deployments/gitea.git)

### Database

MySQL

**Comment by zeripath** [comment]
Is this a system webhook or a repository webhook?

**Comment by zeripath** [comment]
I've noticed a few bugs - which assuming that these represent your problems then should they should fix the problem.

**Comment by bryanpedini** [comment]
> I've noticed a few bugs - which assuming that these represent your problems then should they should fix the problem.

Thank you a lot Zeripath!!

> Is this a system webhook or a repository webhook?

Sorry for the missing information, it was a system-wide wehbook that sent a Telegram notification whenever action X happened on the Gitea server.

Would it be possible to take a look at why it sends webooks even for private repos too? Or is it "normal" behavior?

**Comment by zeripath** [comment]
A system webhook runs on every webhook - that is why it is a system webhook.
