### ISSUE TITLE
Versioned Documentation

### ISSUE THREAD

**Issue by adamu** [go-gitea/gitea#19238]
### Feature Description

The documentation on https://docs.gitea.io/ follows the `main` branch (I think?) and does not correspond with the latest release (1.16).

I spent time time debugging why the documented `ENABLE_ACME` setting was being ignored, before realising that in the latest version, the value is `ENABLE_LETSENCRYPT`, and has been changed to `ENABLE_ACME` on `main`. I only discovered this by reading the source code and comparing branches. There are probably many other examples.

**Comment by jolheiser** [comment]
Duplicate of #5588
Related to #17905
