### ISSUE TITLE
Some buttons doesn't work on issues screen

### ISSUE THREAD

**Issue by maherma-adg** [go-gitea/gitea#19245]
### Description

After update from 1.15.9 to 1.16.1 the close issue button stop working, when you hit the button nothing happens.
Checking screen I detect some buttons stop working too:
- Add time
- Start timer
- Edit issue title

Other buttons still works:
- New Issue
- Comment
- Tags
- Milestone

I update gitea to 1.17.0+dev-351-g54961f3ac but get the same result.

### Gitea Version

1.16.1 and up

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

2.25.1

### Operating System

linux 

### How are you running Gitea?

Gitea server is downloaded from gitea repo. 
Gitea is running as systemd service.
server is ubuntu 20.20.4

### Database

SQLite

**Comment by maherma-adg** [comment]
More info: Tested on Firefox and Chrome do the same result.

**Comment by silverwind** [comment]
Any JS errors visible in the browser console/devtools?

**Comment by maherma-adg** [comment]
Browsers show this message when reload page:

jQuery.Deferred exception: Cannot read properties of undefined (reading 'adminUserListSearchForm') TypeError: Cannot read properties of undefined (reading 'adminUserListSearchForm')

but no reactions when click on buttons

**Comment by wxiaoguang** [comment]
Remove your customized templates.

**Comment by maherma-adg** [comment]
Solved. Now I'll try to restore mermaid and katex render to pages.
Thanks for the solution.

**Comment by wxiaoguang** [comment]
@silverwind how about show JS errors to end users, like this one https://github.com/go-gitea/gitea/pull/18971

There should be no JS error during normal usage. If there is an error, it must be reported and fixed.

**Comment by silverwind** [comment]
Yeah, sounds like a good idea.
