### ISSUE TITLE
Error message when compiling with a too-old version of Go requests the wrong version

### ISSUE THREAD

**Issue by Carnildo** [go-gitea/gitea#19253]
### Description

When compiling Gitea 1.16.5 with Go 1.16.7, it fails with the error message

> Gitea requires Go 1.16 or greater to build.

When looking at the makefile, the actual check is for Go version 1.17 or newer.

### Gitea Version

1.16.5

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

Gentoo

### How are you running Gitea?

N/A

**Comment by wxiaoguang** [comment]
Will be fixed by backport
* https://github.com/go-gitea/gitea/pull/19254
