### ISSUE TITLE
Commits picker in PR change files view

### ISSUE THREAD

**Issue by luwol03** [go-gitea/gitea#19263]
### Feature Description

I think it would be great, if gitea also has a commits picker while browsing through the changed files of a pull request like github have it. When #19007 is implemented, this could also cover `since your last review`.

### Screenshots

![image](https://user-images.githubusercontent.com/60048565/160710197-4cf9fb58-26d1-46ff-9504-7f93d5ffc140.png)

**Comment by sebastian-sauer** [comment]
https://github.com/go-gitea/gitea/pull/25528 adds a commit picker to files tab in PRs.
