### ISSUE TITLE
Pull Request File Tree

### ISSUE THREAD

**Issue by luwol03** [go-gitea/gitea#19262]
### Feature Description

I think it would be great, if gitea also has a pull request file tree. This feature is currently in beta for github and very useful to navigate between *hundreds* of changed files and keep a overview. (On GitHub its the left file tree panel in the screenshot)

### Screenshots

![image](https://user-images.githubusercontent.com/60048565/160709511-0adc4500-6c49-4627-a5d9-a8db56438b9c.png)

**Comment by wxiaoguang** [comment]
* https://github.com/go-gitea/gitea/issues/18192

**Comment by luwol03** [comment]
Oh, you're right. Didn't found that issue. So I'll close that one.
