### ISSUE TITLE
Docs: Add OpenID COnnect to Authentication options

### ISSUE THREAD

**Issue by xeruf** [go-gitea/gitea#19269]
I don't know if I got something wrong here, but the docs (https://docs.gitea.io/en-us/authentication/) only explicitly list Gitea as [OAuth2 *Provider*](https://docs.gitea.io/en-us/oauth2-provider/), while it can definitely also be a client to another provider: https://github.com/go-gitea/gitea/pull/1010

This initially confused me when I tried to check this capability.
And it is actually listed on the Comparison page: https://docs.gitea.io/en-us/comparison/#3rd-party-integrations

**Comment by dkowis** [comment]
Yes please. I'm trying to understand how scopes work, and I can't figure it out :(

**Comment by lunny** [comment]
Moved to https://gitea.com/gitea/docs/issues/106
