### ISSUE TITLE
Push mirror from gitea to bitbucket fails

### ISSUE THREAD

**Issue by lg-elit** [go-gitea/gitea#19285]
### Description

Hi,

so I'm trying to setup a push mirror from Gitea to Bitbucket, Im following this guide:
[https://docs.gitea.io/en-us/repo-mirror/#setting-up-a-push-mirror-from-gitea-to-bitbucket](https://docs.gitea.io/en-us/repo-mirror/#setting-up-a-push-mirror-from-gitea-to-bitbucket).

I get the following error:

> remote: Bitbucket Cloud recently stopped supporting account passwords for Git authentication.
remote: See our community post for more details: https://atlassian.community/t5/x/x/ba-p/1948231
remote: App passwords are recommended for most use cases and can be created in your Personal settings:
remote: https://bitbucket.org/account/settings/app-passwords/
fatal: Authentication failed for 'https://sanitized-credential@bitbucket.org/name/repo.git/'

I've tried with multiple App passwords and repos and so far I haven't been able to make it work. In the blog post from the Bitbucket error message they mention that some changes have taken place on March 1 and maybe this is the cause of this? or maybe I've missed some setting somewhere.

Anyways thanks for the awesomeness that is Gitea.

### Gitea Version

1.16.5

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

2.17.1

### Operating System

Ubuntu 18.04.6 LTS

### How are you running Gitea?

We're running the latest official build from https://dl.gitea.io/gitea for linux-amd64 using systemd.

### Database

SQLite

**Comment by techknowlogick** [comment]
Could you try with the username be set to the user who created the app token, and the password being the app token? This is what works for my push mirroring.

**Comment by lg-elit** [comment]
Thank you, that worked.
