### ISSUE TITLE
Use `Cache-Control: no-transform` to disable Cloudflare auto minify

### ISSUE THREAD

**Issue by wxiaoguang** [go-gitea/gitea#19309]
Many users report that all the tab/space in code disappear. The code indent/indentation become messy.

The reason is that they put Gitea behind Cloudflare, and they enabled the `auto minify` feature on Cloudflare.

The **workaround** is to disable the `auto minify` feature on Cloudflare.

Also, Cloudflare has an option to disable the auto minify: `Cache-Control: no-transform`

Issues:
* https://github.com/go-gitea/gitea/issues/14062
and more

Ref:

* https://community.cloudflare.com/t/disable-minification-with-header/15294
* https://support.cloudflare.com/hc/en-us/articles/200168396-What-will-Cloudflare-compress-

**Comment by tankerkiller125** [comment]
Reading through the docs this will also disable gzip/brotli compression, which I don't think is necessarily what you would want to do?

**Comment by silverwind** [comment]
Whitespace in HTML is often times significant, I think it's a bug on CF if they remove significant whitespace and break sites that way.

Anyways, I would not be opposed to adding `no-transform` to `text/html` responses only.

**Comment by wxiaoguang** [comment]
> Reading through the docs this will also disable gzip/brotli compression, which I don't think is necessarily what you would want to do?

It won't be a problem. Gitea has builtin `ENABLE_GZIP` support.

**Comment by zeripath** [comment]
Is it possible that if we use `<pre>` instead of just relying on CSS `pre` cloudfare would just do the correct thing?

**Comment by wxiaoguang** [comment]
I have no idea about whether Cloudflare affects the content inside `<pre>` or `<textarea>`. I didn't find related documents about this topic.

**Comment by silverwind** [comment]
> Is it possible that if we use <pre> instead of just relying on CSS pre cloudfare would just do the correct thing?

Depends on which HTML minfier they are using, but I suspect it might help, but I'm not sure if the introduction of `<pre>` will break other things. I think we could do a common `<pre>` ancestor to code view, similar to how GitLab does it. GitHub itself has no `<pre>` ancestor to their code views so should be affected by this "bug" too.
