### ISSUE TITLE
Redirect to /robots.txt after login

### ISSUE THREAD

**Issue by keval6b** [go-gitea/gitea#19314]
### Description

Whenever I click login, I get redirected to `/robots.txt` (e.g. `https://git.example.com/robots.txt`). I do get successfully logged in though.

- My setup is `Internet -> Traefik -> Gitea`
- Issue occurs with any method of authentication

### Gitea Version

1.16.5

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/thechubbypanda/258aaeacde287648489603e39ff935d9

### Git Version

2.30.2

### Operating System

ArchLinux

### How are you running Gitea?

Docker image: `gitea/gitea:latest`

### Database

PostgreSQL

**Comment by zeripath** [comment]
Delete your `redirect_to` cookie. 

I suspect you have an old cookie that has not been deleted.

**Comment by wxiaoguang** [comment]
There is no such redirection inside Gitea.  Please check your environment config.

Feel free to reopen if you get new clues.

**Comment by thechubbypanda** [comment]
Found the issue, my browser did have some remaining data but it was for the root domain `example.com` as opposed to `git.example.com`.
