### ISSUE TITLE
Can't view created repositories. (Error 500, Snap, Pi)

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#19313]
### Description

I just installed Gitea via Snap on my Raspberry Pi 2 with Raspberry Pi OS Lite (Debian Bullseye).
Everything works great and was easy to setup. I also can create a new repo. But when I click on that repo, I get just an 500 error. 

Sorry, the log folder is empty. Either please tell me with colored hand puppets how to view the log (casual linux user) or just try to reproduce it as following:

1. Install Gitea via Snap. (see commands below)
2. Open website for simple initial setup.
3. Create user.
4. Create repo.
5. Try to view your repo. 
6. Get error 500.

<details>
  <summary>Configuration - Click to expand!</summary>
  
![setup](https://user-images.githubusercontent.com/53160891/161388160-5eb1be99-3a38-4aa5-9385-4d07cb79b537.jpg)

</details>

### Gitea Version

1.16.5 built with GNU Make 4.1, go1.17.8 : bindata, sqlite, sqlite_unlock_notify, pam, cert

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

Log is empty.

### Screenshots

![image](https://user-images.githubusercontent.com/53160891/161385886-270244e1-27de-4900-adf9-a9527cdc7ca4.png)

### Git Version

2.30.2

### Operating System

Raspberry Pi OS Lite (32-bit) 2022-01-28

### How are you running Gitea?

```
sudo apt update
sudo apt upgrade
sudo apt install sqlite3 -y
sudo apt install git -y

sudo apt install snapd
sudo reboot

sudo snap install core
sudo snap install gitea
```

### Database

SQLite

**Comment by lunny** [comment]
Could you change the `RUN_MODE` to `dev` in `app.ini` and take a look at that page again?

**Comment by twoco** [comment]
Thanks for the hint. Here's the message on the 500 page when accessing a repo:

> An error occurred:
> exit status 1 - ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.

**Comment by wxiaoguang** [comment]
please search `libarmmem` in the issue list

**Comment by zeripath** [comment]
Duplicate see #17462

**Comment by twoco** [comment]
OK thanks. I just commented out the line in `/etc/ld.so.preload`. But not sure what that file is.

**Comment by wxiaoguang** [comment]
Nobody knows how and why at the moment. I am not a Raspberry/Snap user, either.

If anyone knows how to explain and fix the problem, a PR is welcome ........
