### ISSUE TITLE
matrix webhook dial tcp: i/o timeout (Client.Timeout exceeded while awaiting headers)

### ISSUE THREAD

**Issue by G2G2G2G** [go-gitea/gitea#19325]
### Description

I only use matrix webhook, but this might apply to all the webhooks. 
The [matrix] webhook times out. I have a 20 person business that uses the matrix server with lots of automation, there are no issues with our server nor our gitea server. I think the Go function is just set with a much too low timeout seconds so it triggers before there is a response or something?

In the screenshot you can see it just randomly works sometimes and sometimes it doesn't. Nothing has changed as I said I think it's only having a 2-3 second wait until it "times out" but maybe the matrix synapse server is taking 5 seconds or something (for example)

I think adding a input field for a longer timeout could resolve the issue, so users can set their timeout?
For example I know the http client in Go is something like:
```Go
&http.Client{Timeout: 45 * time.Second}
```

Thanks

### Gitea Version

1.14 - 1.16.5

### Can you reproduce the bug on the Gitea demo site?

Have not tried, idk if you can setup webhook there but I wouldn't put my matrix token in it either way

### Screenshots

![1](https://user-images.githubusercontent.com/50514477/161658455-bb836bfc-0889-47bc-a32b-86af4115c130.jpg)

### Operating System

Debian

### How are you running Gitea?

Just get the executable from the releases and run it via systemd daemon

### Database

PostgreSQL

**Comment by lunny** [comment]
You could try to change the timeout in app.ini, it's default 5 seconds.
```ini
;[webhook]
;;
;; Deliver timeout in seconds
;DELIVER_TIMEOUT = 5
```

**Comment by G2G2G2G** [comment]
Oh ok, I didn't even have a webhook section in my ini.. Is it default or my app.ini is just too old to have had it.

I'll close this as I assume that'll probably fix my issue, I'll post back if it happens still. Thanks!
