### ISSUE TITLE
Spearate forks from repo tab

### ISSUE THREAD

**Issue by luwol03** [go-gitea/gitea#19327]
### Feature Description

I like the idea from tastytea,

> Maybe a compromise could be to list forks in a different category (with an option to ”promote” them when the fork becomes a project on its own) [...]
[Source](https://github.com/go-gitea/gitea/issues/19322#issuecomment-1087694671) in #19322 

Maybe there could be a new tab next to the repos where all forks are listed. And in the repos tab only normal repos are listed. Then there could be a little checkbox in the settings to promote a fork as a normal repo (still keep the fork label), so that the repo is now shown in the repos instead of forks tab.

While making a little sketched thing, I noticed that the repos doesn't have a counter like users have. This needs also to be improved.

### Screenshots

![image](https://user-images.githubusercontent.com/60048565/161737738-395be71e-20d5-4f84-a471-42519aa736b6.png)

**Comment by techknowlogick** [comment]
<img width="916" alt="image" src="https://user-images.githubusercontent.com/164197/161784440-dc844126-c484-4c01-b7ee-a9a7a3981f61.png">
Rather than a new tab, because there are many types (archived, forks, templates, etc..), we could instead have a filter on the standard repo listing?

**Comment by lunny** [comment]
You can click the fork button to go to the fork list page. So I don't think we need another entry in the tab list.
