### ISSUE TITLE
Is there a configurational way to replace the user table to another table in another database?

### ISSUE THREAD

**Issue by GitHubGov** [go-gitea/gitea#19326]
### Feature Description

Is there a configurational way to replace the user table to another table in another database?
(provided that all the data can be adjusted)

Thanks in advance.

**Comment by lunny** [comment]
I don't think this is a good idea.

**Comment by lunny** [comment]
I don't think this is a good idea.

**Comment by lunny** [comment]
I don't think this is a good idea.

**Comment by wxiaoguang** [comment]
There is no benefit to do so at the moment. If you need such feature, you can just rewrite the user module for your usage.
