### ISSUE TITLE
Scan commits for secrets and prevent push

### ISSUE THREAD

**Issue by luwol03** [go-gitea/gitea#19343]
### Feature Description

I think it would be a cool integration to prevent pushing commits which contain secrets. [Github](https://www.bleepingcomputer.com/news/security/github-can-now-auto-block-commits-containing-api-keys-auth-tokens/) now announced, that they now prevent such pushes. Of course this feature should be possible to opt-out.

I randomly found the following [go tool](https://github.com/trufflesecurity/trufflehog) on my discover page that can scan repositories and files even directly via a remote url from git. Maybe it’s somehow possible to use that for scanning the files.

**Comment by silverwind** [comment]
I'd say this should definitely be an opt-in feature.

**Comment by techknowlogick** [comment]
closing as dupe of https://github.com/go-gitea/gitea/issues/5656

**Comment by luwol03** [comment]
Oh ok. Never found that issue. Thank you.
