### ISSUE TITLE
Cannot login to WebUI

### ISSUE THREAD

**Issue by cmonty14** [go-gitea/gitea#19347]
### Description

Hello,
for unknown reason I cannot login to WebUI of my gitea server.
After clicking "Sign in" button in login screen I'm redirected to Gitea Welcome Screen.

Using the gitea CLI I can fetch information of user accounts correctly:
```
gitea --config /etc/gitea/app.ini admin user list
ID   Username       Email                 IsActive IsAdmin
1    d038783        user@example.com true     true
3    t-user_d038783 user@example.com       true     false
4    d057862        user2@example.com        true     true

```

I could change the password of the relevant user ID 1, however login in WebUI is still not working.

Can you please advise how to trouble-shoot this issue?

THX

### Screenshots

![2022-04-08_11-37-44](https://user-images.githubusercontent.com/12523591/162414149-e1af8789-4c2d-4d0f-ad99-c95c891b0a27.png)

### Gitea Version

Gitea version 1.16.5 built with GNU Make 4.1, go1.18 : bindata, sqlite, sqlite_unlock_notify

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

Ubuntu 20.04.4 LTS

### Browser Version

Chrome Version 99.0.4844.74 (Official Build) (64-bit)

**Comment by lunny** [comment]
We need logs and if you have chrome dev network request records, it's better.

**Comment by cmonty14** [comment]
Can you please specify the logs that are required?
I could share logs in /var/log/nginx/.

I have created a file that capture the network traffic and attached it here.
[vlcspgit.devsys.net.sap.zip](https://github.com/go-gitea/gitea/files/8456683/vlcspgit.devsys.net.sap.zip)
.

**Comment by wxiaoguang** [comment]
There must be something wrong in your `app.ini`, eg: incorrect ROOT_URL, incorrect DOMAIN, etc.

**Comment by cmonty14** [comment]
I have never used `https` before, therefore I wonder what could have changed.

**Comment by wxiaoguang** [comment]
Please READ the document


![image](https://user-images.githubusercontent.com/2114189/166193324-4326092c-6cd6-4702-86e3-0bcf9893e5a9.png)

**Comment by TobiasDeBruijn** [comment]
I'm also having this same issue. POST login request is fine, but still get redirected to the home page.
On login, the server responds with
```
Set-Cookie: macaron_flash=; Path=/; Max-Age=0; HttpOnly; SameSite=Lax
```
