### ISSUE TITLE
Dissimilar URLs

### ISSUE THREAD

**Issue by cschuber** [go-gitea/gitea#19340]
When tunneling gitea:3000 through SSH port forwarding, some URLs will contain the ROOT_URL. For example, to "bypass" a firewall I ssh to the gitea server itself (ssh port is open but all other ports are blocked).  I add the following to my .ssh/config:

    LocalForward 3000 127.0.0.1:3000

This works for most links presented by gitea but some, such as Issues and Pull Requests, the link contains the ROOT_URL as its base. This results in the browser hanging until timeout, after which I replace the FQDN with localhost, press enter, and continue.

As to asking the firewall group to open port 3000, the answer was no.

Can this be addressed in a future version of gitea?

I did notice this at home when I changed ROOT_URL to a FQDN. Using the short name (as permitted by search in resolv.conf) also exhibited this same problem.

Would you recommend using gitea behind a nginx reverse proxy instead?

**Comment by wxiaoguang** [comment]
It's impossible. See
* https://github.com/go-gitea/gitea/pull/18971

**Comment by wxiaoguang** [comment]
I opened a new issue for the root problem.
* https://github.com/go-gitea/gitea/issues/19345
