### ISSUE TITLE
Can not drag issue in project board

### ISSUE THREAD

**Issue by u1465** [go-gitea/gitea#19341]
### Description

1. User A login
2. shut down gitea 1.15.4
3. upgrade gitea to 1.16.4
4. restart gitea
5. Go Project Board and can not drag issue anymore.

NOTE: if user A logout first, everything is fine.

### Gitea Version

1.16.5

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

2.34.1.windows.1

### Operating System

Win10

### How are you running Gitea?

start with windows service

### Database

SQLite

**Comment by wxiaoguang** [comment]
Clear your browser cache and try again, or use browser private window to try

**Comment by u1465** [comment]
@wxiaoguang thanks for your help.

Related to #18476?

**Comment by wxiaoguang** [comment]
> @wxiaoguang thanks for your help.
> 
> Related to #18476?

Maybe, has your issue been resolved?

**Comment by u1465** [comment]
@wxiaoguang I am trying now. Will feedback soon if it is resolved. :)

**Comment by u1465** [comment]
@wxiaoguang OK. It is resolved. Thanks for you help again.

**Comment by wxiaoguang** [comment]
@go-gitea/maintainers and @go-gitea/owners

It's worth to mention this long standing cache problem again, which still has no progress. There are not only just a few issues from the beginning.

**Comment by silverwind** [comment]
Browser cache issues are to my knowledge always because of the Service Worker, which will be disabled by default in coming 1.17 with https://github.com/go-gitea/gitea/pull/18914.

**Comment by wxiaoguang** [comment]
How about do a backport to 1.16?

**Comment by silverwind** [comment]
Guess I wouldn't be opposed to it, for the sake of getting rid of cache errors. We probably should remove the serviceworker entirely in 1.17 or later.

**Comment by silverwind** [comment]
https://github.com/go-gitea/gitea/pull/19342
