### ISSUE TITLE
Set default branch name to "main" instead of "master".

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#19351]
### Feature Description

When creating new repos, we should no longer use the word "master" for the branch. Just like GitHub and GitLab now use "main" instead of "master" as the default initial branch name.

https://sfconservancy.org/news/2020/jun/23/gitbranchname/

### Screenshots

![image](https://user-images.githubusercontent.com/53160891/162537721-ee42802e-5d2f-4196-85da-bbc498ad493d.png)
![image](https://user-images.githubusercontent.com/53160891/162537751-c18c838d-acc6-4007-b6de-083cb32ce1f5.png)

**Comment by jolheiser** [comment]
This is already configurable via [`DEFAULT_BRANCH`](https://docs.gitea.io/en-us/config-cheat-sheet/#repository-repository).

**Comment by twoco** [comment]
But set to "master" per default, isnt it?
