### ISSUE TITLE
How to enable container registry ? 

### ISSUE THREAD

**Issue by znoxx** [go-gitea/gitea#19366]
### Description

I'm trying to use package registry functionality, described here: https://docs.gitea.io/en-us/packages/overview/
Instance is running via docker image gitea/gitea:1.16.5 and docker-compose described in configuration.

I've enabled packages in app.ini:
```
[packages]
ENABLED = true
```
Then restarted docker container. 
After this I'm trying to login to registry like described here:
https://docs.gitea.io/en-us/packages/container/

```
docker login localhost:3000
```
And getting 404 error:
```
Error response from daemon: login attempt to http://localhost:3000/v2/ failed with status: 404 Not Found
```
What I'm doing wrong ? How to enable package functionality (at least docker images) ?

### Gitea Version

1.16.5

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

Linux

### How are you running Gitea?

Via docker-compose like described in documentation with ports
* 3000 (web)
* 2222 (ssh)

published

### Database

SQLite

**Comment by luwol03** [comment]
The package feature is not available in v1.16. The docs at https://docs.gitea.io are currently out of sync. You need to wait for v1.17 or use the dev (main branch) version (not recommended in production).

**Comment by W-A-S-A-Y** [comment]
I've tried using it with gitea 1.17 and it doesn't resolve the issue. which is something I need help with. kindly correct me or explain what could possibly be going wrong? 

What I've done is used the app.ini file and added the 
[package]
ENABLED = true.

if this is not the way kindly let me know

**Comment by delvh** [comment]
[package**s**]
ENABLED = true

https://docs.gitea.io/en-us/config-cheat-sheet/#packages-packages
