### ISSUE TITLE
Gitea: Sign In - Page Blank 

### ISSUE THREAD

**Issue by zedkazi** [go-gitea/gitea#19373]
### Description

Self Hosted Gitea on 
Server: Ubuntu Server 20.04
Gitea version 1.16.3 built with GNU Make 4.1, go1.17.7 : bindata, sqlite, sqlite_unlock_notify
Git: 2.25.1

Gitea Web is running as I can see the home page.
But when I click sign in - _It shows a blank page_
See Screenshot 1

Please see the config 
see Screenshot 2

P.S. Did not receive anything in /var/snap/gitea/common/log

### Gitea Version

1.16.3

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

Screenshot 1:
![image](https://user-images.githubusercontent.com/2480772/162727336-ac92cf7e-fcdd-4b21-8618-b5edc2af762c.png)

Screenshot 2:
![image](https://user-images.githubusercontent.com/2480772/162736931-b1576be6-1702-42b9-80ba-8376ca430398.png)

### Git Version

2.25.1

### Operating System

Ubuntu Server 20.04

### How are you running Gitea?

Using Gitea Web from work station using local network 
Browsers: Firefox, Chrome

### Database

MySQL

**Comment by wxiaoguang** [comment]
1. What have you done recently? What has been changed?
2. Is the ROOT_URL correct? Is the URL of correct home page the same (the same host) with the incorrect blank page?
3. What does the browser say about the blank page? Any errors in the browser console?
4. How do you run Gitea? snap? Any change recently?
5. Are you using customized templates? If yes, are the templates correct?
6. There must be some logs somewhere, if the problem still exists, try to find them.

**Comment by zedkazi** [comment]
1. Tried self signing ssl 
2. Yes, its same
3. Nothing. If it helps please visit 123.253.15.219:3000
4. no change in gitea. 
5. not using customized templates
6. If you can share me a command using which i can get please do. I tried each log directory set in app.ini

P.S. also a noob inserver management.

**Comment by wxiaoguang** [comment]
Not an issue on Gitea side, question could be asked in discord.
