### ISSUE TITLE
Gitea - Sign In : shows Blank Page

### ISSUE THREAD

**Issue by zedkazi** [go-gitea/gitea#19372]
Cannot sign in anymore, because I see a blank page instead of a sign in form.

**Comment by techknowlogick** [comment]
When opening an issue please provide the information that is requested as otherwise we can't help you.

**Comment by zedkazi** [comment]
Self hosted Gitea on Ubuntu 20.04 and only 3 users have been created inclusive of admin.
Has been working great for the week but today could not login
![image](https://user-images.githubusercontent.com/2480772/162710917-988c2d1c-02ea-45e6-9440-81829f4e7bb0.png)


Kindly let me know what information you may need to resolve this.
