### ISSUE TITLE
Unzip on Docker Gitea 1.16.5 amd64 seems to be failing

### ISSUE THREAD

**Issue by 99rgosse** [go-gitea/gitea#19381]
### Description

Steps :
- 1 Download docker gitea 1.16.5-amd64
- 2 copy some previous gitea dump backup inside
- 3 unzip leads to error : 

> root@ubuntu-bionic:~# docker exec -it gitea /bin/bash
> bash-5.1# cd backup/
> bash-5.1# ls
> gitea-dump-1649701143.zip  gnupg.tar
> bash-5.1# unzip gitea-dump-1649701143.zip 
> Archive:  gitea-dump-1649701143.zip
> unzip: short read

Now if you do inside the container 
`apk upgrade && apk add zip`

then you can deflate correctly the gitea dump.

### Gitea Version

1.16.5

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

> 2.27

### Operating System

Linux

### How are you running Gitea?

Inside a vagrant machine and with docker

### Database

PostgreSQL

**Comment by 99rgosse** [comment]
Do you think it is better to modify the Dockerfile to add the commands, or should I file an issue to alpine / busybox ?

**Comment by techknowlogick** [comment]
Please open an issue with alpine, as we try to modify as little with the base image as we can manage.
