### ISSUE TITLE
Missing backtick in locale_ru-RU

### ISSUE THREAD

**Issue by bvp** [go-gitea/gitea#19383]
### Screenshots

![изображение](https://user-images.githubusercontent.com/284156/163025679-01ca051f-ecf0-4ff2-bb18-134978642526.png)

### Gitea Version

1.16.5

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

Linux

### Browser Version

Firefox 99.0

**Comment by techknowlogick** [comment]
Thanks for pointing this out, are you able to send a PR to the release/1.16 branch?

**Comment by bvp** [comment]
> Thanks for pointing this out, are you able to send a PR to the release/1.16 branch?

Sure
