### ISSUE TITLE
Building gitea with golang1.18 binary fails

### ISSUE THREAD

**Issue by gesangtome** [go-gitea/gitea#19385]
I tried to build gitea with the latest binary package of golang, and exported the environment variable $GOROOT, it looked fine at first, but when running go generate, I got this error:

Running go generate...
make[1]: *** No rule to make target 'modules/public/bindata.go', needed by 'gitea'.  Stop.
make[1]: Leaving directory '/home/gesangtome/rpm-packages/gitea/BUILD/gitea-1.16.5'

what happened?

**Comment by techknowlogick** [comment]
FWIW, gitea's 1.16.x branch is being built with golang 1.18 but it looks like that is somehow related to make instead of go itself.

To confirm an assumption made, is the binary you are using for go have the name `go` or is it `go1.18` or something similar?

**Comment by 42wim** [comment]
Can you also paste the output of `go env` ?

**Comment by gesangtome** [comment]
@techknowlogick https://golang.google.cn/dl/go1.18.1.linux-amd64.tar.gz

**Comment by gesangtome** [comment]
@42wim
➜  GOROOT=/home/gesangtome/golang; export GOROOT
➜  PATH=$GOROOT/bin:$PATH; export PATH
➜  go version
go version go1.18.1 linux/amd64
➜ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/***/.cache/go-build"
GOENV="/home/***/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/***/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/***/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/home/***/golang"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/***/golang/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18.1"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/***/gitea-1.16.5/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2105614396=/tmp/go-build -gno-record-gcc-switches"

**Comment by techknowlogick** [comment]
To confirm, this works when you use golang 1.17?

**Comment by techknowlogick** [comment]
The 1.16.5 tag hasn't changed, so it must be something locally had changed. I suspect it could be related to go generate not making the bindata files initially and so then make couldn't file them. 
I'm going to close this as it is now working, but if you have issues later on please open a thread in our forum: https://discourse.gitea.io/

**Comment by gesangtome** [comment]
@techknowlogick thank
