### ISSUE TITLE
Sorting by Recently updated/Least recently updated not working

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#1938]
- Gitea version (or commit ref): 1.1.1
- Git version: Not sure (3rd party service - Teknik.io)
- Operating system: Windows Server 2016 Datacenter
- Database:
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No but I can at [Teknik.io](https://git.teknik.io/Teknikode/Teknik/issues?q=&type=all&sort=recentupdate&state=closed&labels=0&milestone=0&assignee=0)
  - [ ] Not relevant
- Log gist: N/A

## Description

Sorting by **Recently updated/Least recently updated**, seems to have no effect.
In the test link above, the post **Keep 3rd party services up to date** or **Suggestions for future services** have been updated 1 day ago.

GitHub shows `updated 3 hours ago` next to `opened 7 months ago by someuser` when sorting by last update, so I wonder if this is actually implemented in Gitea.

## Screenshots

![screencap-1497187960331](https://user-images.githubusercontent.com/9649385/27011398-e5d3850e-4eb2-11e7-8830-78aa67617934.png)

**Comment by bkcsoft** [comment]
Since this is most likely a regression I'm adding the backport-label
