### ISSUE TITLE
Authentication failed: Push mirror from Gitea to GitHub

### ISSUE THREAD

**Issue by 735trv** [go-gitea/gitea#19389]
### Description

The authentication failed when trying to set up a push mirror to GitHub:

> remote: Support for password authentication was removed on August 13, 2021. Please use a personal access token instead.
> remote: Please see https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/ for more information.
> fatal: Authentication failed for 'https://github.com/USER/REPOSITORY.git/'

I created a GitHub personal access token and chose `[X] repo Full control of private repositories` (Contains `repo:status`, `repo_deployment`, `public_repo`, `repo:invite` and `security_events`)

You can reproduce this with your test instance https://try.gitea.io

### Gitea Version

1.16.5

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

Different and depends on the customer

**Comment by noerw** [comment]
Can confirm, it still worked a couple of days ago. Error message:
```
PushRejected Error: exit status 1: warning: redirecting to https://github.com/noerw/nextcloud-exporter/
To https://github.com/noerw/nextcloud-exporter
 ! [remote rejected] err-ratelimit -> err-ratelimit (refusing to allow a Personal Access Token to create or update workflow `.github/workflows/pull-request.yml` without `workflow` scope)
 ! [remote rejected] expose-active-users -> expose-active-users (refusing to allow a Personal Access Token to create or update workflow `.github/workflows/pull-request.yml` without `workflow` scope)
error: failed to push some refs to 'https://sanitized-credential@github.com/noerw/nextcloud-exporter'
```

Looks like GH added a new required scope for pushing to repos that have a `.github/workflows` dir.
The files in that dir didn't change afaik though, so this scope seems kind of unnecessary

**Comment by ddddavid-he** [comment]
Same problem .
Push mirror for GitHub is not available.

**Comment by Disane87** [comment]
Same problem here

**Comment by zeripath** [comment]
have you tried creating an access token with the appropriate scope `workflow` and then setting the access token as the password?

**Comment by Disane87** [comment]
Yeah sure
![image](https://user-images.githubusercontent.com/956158/205462233-f58e7468-8ccf-4db4-81ff-462027a4580d.png)

Error persists:
![image](https://user-images.githubusercontent.com/956158/205462291-cc0e4e30-0f34-4005-b781-31b4da4a50a7.png)

**Comment by zeripath** [comment]
Have you put the access token as the password?

**Comment by Disane87** [comment]
> Have you put the access token as the password?

Yes

**Comment by zeripath** [comment]
This is odd because if you read the referenced document that is precisely what it says to do

**Comment by Disane87** [comment]
Yeah that's pretty weird 🫤

**Comment by Disane87** [comment]
Tried that new with a new token but within .git in the url and now it works.

**Comment by devfaz** [comment]
Hint: had the same issue. It seems there is a " " (space) char in front of the token if you copy&paste it.

**Comment by wxiaoguang** [comment]
This issue is very old.

Gitea could support GitHub's token. 

But GitHub's page has a very annoying behavior: the copied content has leading and trailing spaces ....
