### ISSUE TITLE
Would love a way to 100% disable organizations

### ISSUE THREAD

**Issue by Jieiku** [go-gitea/gitea#19391]
### Feature Description

Would love a way to 100% disable organizations

I have locked it down as far as I think possible in app.ini:

```ini
[service]
DEFAULT_ALLOW_CREATE_ORGANIZATION = false
DEFAULT_ORG_VISIBILITY            = private
DEFAULT_ORG_MEMBER_VISIBLE        = false

[admin]
DISABLE_REGULAR_ORG_CREATION = true
```

### Screenshots

I want to COMPLETELY disable organizations, so that this box goes away completely:

![2022-04-12_23-13-13](https://user-images.githubusercontent.com/106644/163112002-a16d970f-734b-43f8-a015-aa599ab78fa5.png)

**Comment by wxiaoguang** [comment]
You can disable it by a customized css:

```
#dashboard-repo-list .menu .item:nth-child(2) {
  display: none;
}
```

**Comment by Jieiku** [comment]
@wxiaoguang that did not work the top box is still there, also the Sources menu item is now missing between All and Forks:

![2022-04-12_23-35-00](https://user-images.githubusercontent.com/106644/163114836-9d4959ba-d2f5-479f-b553-bf4818f06e51.png)

however after a few minutes I think I figured it out, hopefully no other side effects:

```css
#dashboard-repo-list > div > div:first-child {
  display: none !important;
}
```
