### ISSUE TITLE
Issue badge color

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#1939]
- Gitea version (or commit ref): 1.1.1
- Git version: Not sure (3rd party service - Teknik.io)
- Operating system: Windows Server 2016 Datacenter
- Database:
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No but I can at [Teknik.io](https://git.teknik.io/Teknikode/Teknik/issues)
  - [ ] Not relevant
- Log gist: N/A

## Description

When the user is not logged in, all issues are marked with a default black badge. When the user logs in, issues created by him should be marked with the different color (green in this case) to differentiate from all issues, but the logic seems inverted.

What happens is that after log in, all issues suddenly assume the green badge and the user issues (**Rainloop Piwik Analytics** post, in the second screenshot) get the black badge.

## Screenshots

Logged out

![screencap-1497188158734](https://user-images.githubusercontent.com/9649385/27011485-6c286e16-4eb4-11e7-93a5-45096872af8c.png)

Logged in

![screencap-1497188206896](https://user-images.githubusercontent.com/9649385/27011487-7139a1e0-4eb4-11e7-92f5-b360e6bd1f48.png)

**Comment by bkcsoft** [comment]
I read somewhere that the bagde color is actually unread issues. Could you verify this?

**Comment by ghost** [comment]
I can not. On the Teknik test link above, there are 3 pages of issues and, after logged in, the black ones were started by me and the green ones were not. They remain the same color (green or black) whether they're read or not.

Update: Exhibits the same behavior on both **Open** and **Closed** issue tabs.

**Comment by techknowlogick** [comment]
Closing. Please re-open if needed.

**Comment by ghost** [comment]
@techknowlogick Can you explain the badge colors, based on my original description?

**Comment by lafriks** [comment]
Green is for unread issues

**Comment by ghost** [comment]
> Green is for unread issues

No. But thanks anyway. I guess my description wasn't clear enough or something. BTW, I just tested it on https://try.gitea.io and, yeah, issues are always green. Even after I read them. Which would make them read, not unread. Like I said 2 posts above. Maybe I'm seeing things. Apologies.

**Comment by lafriks** [comment]
From issue list template:
```
<div class="ui {{if .IsRead}}black{{else}}green{{end}} label">#{{.Index}}</div>
```

Maybe you didn't refresh page and after pressing back in browser it did show cached page?
