### ISSUE TITLE
API documentation for endpoint

### ISSUE THREAD

**Issue by joubertredrat** [go-gitea/gitea#194]
Hi guys,

I think that a important thing on Gitea is have a API endpoint documentation on application or on site documentation like [Swagger](http://petstore.swagger.io/) or [Apidoc](http://apidocjs.com/example/).
With this will be more easy to see all methods (or operations) and all information about each one of them.

Today on Gogs, this documentation is on github wiki and isn't easy to learn and work with this.

**Comment by tboerger** [comment]
I also dislike the Wiki approach, the docs have to be bundled with the code and also exported automatically to the docs website.

**Comment by bkcsoft** [comment]
I started to play around with swagger[1] today, IMO it would be the best solution (even though I personally prefer ApiDoc...). I'm just not entirely sure how/where we should present it, @tboerger had the idea of integrating the docs in Gitea itself (e.g. `try.gitea.io/docs/api` ) though I'm not sure that is a good idea

[1] https://github.com/yvasiyarov/swagger

**Comment by tboerger** [comment]
We can enable or disable that via config flag. Additionally to that we can extract this documentation from every branch and provide all of this within our docs or at a separate page.

**Comment by joubertredrat** [comment]
For first I think that is good idea to documentation manually on https://api.gitea.io/ as example because today doesn't exists anything about API documentation

After this we can view automated tools like Swagger

**Comment by tboerger** [comment]
Nobody wants to do it twice, so we should directly provide something generated out of swagger annotations

**Comment by lunny** [comment]
Yes, we need an API document ASAP.

**Comment by sapk** [comment]
We could use : https://goswagger.io/generate/spec.html ?

**Comment by ralphtheninja** [comment]
Until there is a proper API documentation available. Where can I dig around to find out how to call the api?

**Comment by sapk** [comment]
You could find all api url in code here : https://github.com/go-gitea/gitea/blob/master/routers/api/v1/api.go#L230

You could copy-paste : https://github.com/sapk-fork/gitea/blob/generate-swagger/public/swagger.v1.json in http://editor.swagger.io for viewing incoming documentation.

You could also look at https://github.com/go-gitea/go-sdk that is a go package to access the api (all url are not implemented)

**Comment by SeanFarrow** [comment]
Hi,
Is there a swagger document available as of now? I need to generate a client in c#.

**Comment by lafriks** [comment]
@SeanFarrow it is still WIP - https://try.gitea.io/swagger

**Comment by SeanFarrow** [comment]
Hi,

Thanks, is there a test gitea server anywaere?

**Comment by SeanFarrow** [comment]
Thanks, Do you know whether there are any test servers available, or alternatively a vagrant/packer base box. I'm tryingot write integration tests against the API.

**Comment by lafriks** [comment]
There is https://try.gitea.io but integration tests for api are run localy from development environment (see https://github.com/go-gitea/gitea/tree/master/integrations)

**Comment by SeanFarrow** [comment]
How are the integration environments spun up?

**Comment by lafriks** [comment]
On linux you need to run `make test-pgsql` or `make test-mysql` but you need postgresql or mysql set up correctly

**Comment by SeanFarrow** [comment]
Ok, it would be nice if there were boxes so that this could be run from a windows box for testing—maybe a separate issue!

**Comment by SeanFarrow** [comment]
Hi,

Assuming I have a url for a server, what is the uri for the api?
I've had a look at api.go and only see gitea.io url's.
Help appreciated.
Kind regards
Sean.

**Comment by sapk** [comment]
You could try to go to `/swagger` on your instance to view documentation and you could use integration test has an example for url, like : https://github.com/go-gitea/gitea/blob/f1adaef45849fc260b07be39a39b9c1ee5146923/integrations/api_issue_test.go#L25

**Comment by SeanFarrow** [comment]
Strange, the swagger url doesn’t seem present on that server.
Cheers
Sean.
Kino r

**Comment by SeanFarrow** [comment]
Hi,

I’m trying to go to url:
http://server:port/api/v1/orgs/MeasurementSystems
it can’t seem to find the page, as I keep getting an http404, what would be the correct uri to look an organizations repos?
This is for gitea v1.1.0.
Kind regards
Sean.

**Comment by SeanFarrow** [comment]
Hi all,

What is the minimum version of Gitea that the api works with, with v1.1.0, the API doesn't seem to exist, I'm only getting 404's and no swagger document exists at /swagger as noted above.
Any help appreciated.
Cheers
Sean.

**Comment by lunny** [comment]
@SeanFarrow /swagger is the document which is on v1.2. But the APIs works well on v1.1.0

**Comment by SeanFarrow** [comment]
Ok, can you give me a sample uri please, I can’t seem to get this to work what ever uri I use!
Do I need to enable the api?

**Comment by cez81** [comment]
@SeanFarrow If you haven't got this to work yet, here's an example https://try.gitea.io/api/v1/repos/search?q=gitea

**Comment by sapk** [comment]
This one could be close

**Comment by lunny** [comment]
@sapk I think yes.

**Comment by marbetschar** [comment]
@sapk https://try.gitea.io/ seems to be down

**Comment by lunny** [comment]
@marbetschar yes, we are changing to a new plan for bigger disk space.

**Comment by marbetschar** [comment]
@lunny meanwhile, is there any documentation for the api available? We are working on a Gitea integration, but its not so easy getting things right by solely read the code in the repo.

**Comment by sapk** [comment]
@marbetschar I just uploaded at https://app.swaggerhub.com/apis/gitea/gitea-api/1.1.1 you can see it there for the moment. I will need to auto-update that if we keep it.

You can always copy https://raw.githubusercontent.com/go-gitea/gitea/master/public/swagger.v1.json to https://editor.swagger.io/ (File -> Import URL)

**Comment by marbetschar** [comment]
@sapk thanks for this! I can see a bunch of errors there (screenshot attached), but I guess I can ignore them for now?

<img width="1280" alt="bildschirmfoto 2018-03-15 um 11 53 13" src="https://user-images.githubusercontent.com/392542/37459167-8f4c8932-2847-11e8-8fb3-37af0eb64047.png">

**Comment by sapk** [comment]
@marbetschar yes, we need to fill security schema and maybe other spec to be fully compliant with swagger and the editor seems to be more exigent than the swagger-ui we use in gitea. But with all the definitions allready done you should get enough information to get started with api. You can dismiss error and hide them even.
