### ISSUE TITLE
Open the management background and report an error

### ISSUE THREAD

**Issue by huangjunfa1** [go-gitea/gitea#19402]
### Description

Error log：
[E] Render failed: template: admin/dashboard:8:90: executing "admin/dashboard" at <Str2html>: invalid value; expected string

### Gitea Version

1.16.1

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![image](https://user-images.githubusercontent.com/30465052/163337439-81b2b1fd-dc73-495d-a090-60e88a9f1cd5.png)
![image](https://user-images.githubusercontent.com/30465052/163337478-5122cd8c-78da-477d-9492-8427053d1262.png)
![image](https://user-images.githubusercontent.com/30465052/163337526-05ccb2b1-1c54-4701-9d42-e08be1f5d082.png)

### Git Version

1.16.1

### Operating System

centos-release-7-9

### How are you running Gitea?

docker，Tag：latest

### Database

MySQL

**Comment by lunny** [comment]
Please upgrde to v1.16.5
