### ISSUE TITLE
How to handle incorrect ROOT_URL for gitea.com

### ISSUE THREAD

**Issue by wxiaoguang** [go-gitea/gitea#19407]
After the PR (background https://github.com/go-gitea/gitea/issues/19345)
* https://github.com/go-gitea/gitea/pull/18971 

Now if users visit `www.gitea.com`, they will see the prompt.

I think the prompt is correct at the moment.

A real case: if users log into `www.gitea.com`, then many URLs are pointing to `gitea.com`, then if they try to visit it, they are still not logged-in on `gitea.com` because the cookie is not shared between these two domains.

This problem becomes more serious because some forms and ajax requests are using absolute URL to `gitea.com`, users may lose their work if they try to submit request to `gitea.com` from `www.gitea.com`.

And that's one of the reasons why some users complain that their work are lost, see screenshot 2, the URL in form is absolute.

Then the question is: how to continue? IMO the proper way is to make `www.gitea.com` redirect users to `gitea.com` at the moment.

### Screenshot 1, incorrect ROOT_URL

<details>

![image](https://user-images.githubusercontent.com/2114189/163562138-1d40cc87-493e-49c5-bb95-6a9523cbba33.png)

</details>

### Screenshot 2, the absolute URL in form

<details>

![image](https://user-images.githubusercontent.com/2114189/163563574-ddc04b2d-0843-4567-bda7-a3e003109e7b.png)

</details>

**Comment by lunny** [comment]
We always need to redirect www.gitea.com to gitea.com
