### ISSUE TITLE
[Feature Request] Shields.IO Endpoint API

### ISSUE THREAD

**Issue by OdinVex** [go-gitea/gitea#19418]
Shields.IO supports custom endpoints to return information for badges. It'd be pretty neat for Gitea to have an endpoint to query various info to support it.

**Comment by techknowlogick** [comment]
Could you provide some links for documentation on what would be needed?

**Comment by OdinVex** [comment]
> Could you provide some links for documentation on what would be needed?

https://shields.io/endpoint

**Comment by techknowlogick** [comment]
Thanks for providing that information. I think this would be better suited for a 3rd party middleware, or 1st party support within shields, as otherwise we'd be duplicating all our endpoints to provide information in a specific format.

**Comment by 6543** [comment]
-> https://github.com/badges/shields/issues/4040 etc...

**Comment by OdinVex** [comment]
Some things can't necessarily be queried by Shields.io, I'd also prefer an air-gapped situation. I disagree, but your project.

**Comment by 6543** [comment]
they have fully github support, and githup does not implement there api either - so they muse be a way to do so

PS: they can reuse most of the github code anyway as gitea mimic most endpoints

**Comment by OdinVex** [comment]
> they have fully github support, and githup does not implement there api either - so they muse be a way to do so
> 
> PS: they can reuse most of the github code anyway as gitea mimic most endpoints

Implementing an endpoint can save a lot of bandwidth instead of requiring them to download entire pages to parse. I get the impression you might not know what endpoint I was talking about...a queryable API specifically for Shields.io...?
