### ISSUE TITLE
1.14 sqlite3 migrate to 1.15 problem

### ISSUE THREAD

**Issue by march1993** [go-gitea/gitea#19417]
### Description

It seems there are some column structure problem. Take `email_hash` table for example. The table fresh created has the following structure by running command `SELECT sql FROM sqlite_master WHERE name='email_hash';`,

```sql
CREATE TABLE `email_hash` (`hash` TEXT PRIMARY KEY NOT NULL , `email` TEXT NOT NULL )
```

but by using a gui tool like db browser the structure becomes,

```sql
CREATE TABLE "email_hash" (
	"hash"	TEXT NOT NULL,
	"email"	TEXT NOT NULL,
	PRIMARY KEY("hash")
)
```

There's a slight difference between two table. I don't know why xorm complains about the second one generated by 3rd tools.
A workaround is available: drop the table, run exactly the same sql from fresh created one including tables and indicies. 

### Gitea Version

1.14.x

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

binary self host

**Comment by lunny** [comment]
Which 1.15 version did you upgrade?

**Comment by march1993** [comment]
@lunny from v178 to v187. Migration process complains about webhook table at very beginning. Then I tried to alter the table columns manually.

**Comment by lunny** [comment]
Please give the Gitea version but not database version.

**Comment by techknowlogick** [comment]
> I don't know why xorm complains about the second one 

How does it complain? We need logs. Please also instead go to latest stable (1.16.5) as 1.15.x is no longer supported.

**Comment by march1993** [comment]
Here is partial of the log. 
```
2022/04/18 10:16:31 cmd/migrate.go:40:runMigrate() [W] Table hook_task has column id but struct has not related field
2022/04/18 10:16:31 cmd/migrate.go:40:runMigrate() [W] Table hook_task has column repo_id but struct has not related field
2022/04/18 10:16:31 cmd/migrate.go:40:runMigrate() [W] Table hook_task has column hook_id but struct has not related field
2022/04/18 10:16:31 cmd/migrate.go:40:runMigrate() [W] Table hook_task has column uuid but struct has not related field
2022/04/18 10:16:31 cmd/migrate.go:40:runMigrate() [W] Table hook_task has column NULL but struct has not related field
2022/04/18 10:16:31 cmd/migrate.go:40:runMigrate() [W] Table hook_task has column NULL but struct has not related field
2022/04/18 10:16:31 cmd/migrate.go:40:runMigrate() [W] Table hook_task has column payload_content but struct has not related field
2022/04/18 10:16:31 cmd/migrate.go:40:runMigrate() [W] Table hook_task has column NULL but struct has not related field
2022/04/18 10:16:31 cmd/migrate.go:40:runMigrate() [W] Table hook_task has column event_type but struct has not related field
2022/04/18 10:16:31 cmd/migrate.go:40:runMigrate() [W] Table hook_task has column NULL but struct has not related field
2022/04/18 10:16:31 cmd/migrate.go:40:runMigrate() [W] Table hook_task has column is_delivered but struct has not related field
2022/04/18 10:16:31 cmd/migrate.go:40:runMigrate() [W] Table hook_task has column delivered but struct has not related field
2022/04/18 10:16:31 cmd/migrate.go:40:runMigrate() [W] Table hook_task has column is_succeed but struct has not related field
2022/04/18 10:16:31 cmd/migrate.go:40:runMigrate() [W] Table hook_task has column request_content but struct has not related field
2022/04/18 10:16:31 cmd/migrate.go:40:runMigrate() [W] Table hook_task has column response_content but struct has not related field
2022/04/18 10:16:31 cmd/migrate.go:41:runMigrate() [F] Failed to initialize ORM engine: migrate: migration[187]: Drop unneeded webhook related columns failed: near ")": syntax error
```

**Comment by march1993** [comment]
I've desensitized the `gitea.db` and uploaded it here for who is interested in the sqlite db file.
[gitea.zip](https://github.com/go-gitea/gitea/files/8503120/gitea.zip)

**Comment by lunny** [comment]
Which 1.15.x version did you upgrade?

**Comment by march1993** [comment]
@lunny  I tried 1.15.0 and 1.15.11. You may consider 1.15.0 only.

**Comment by lunny** [comment]
You should upgrade to the last minor version of 1.15.x, it should be 1.15.11.

**Comment by march1993** [comment]
> You should upgrade to the last minor version of 1.15.x, it should be 1.15.11.

I made duplications of `gitea.db` and tried several versions even 1.16.x.

**Comment by singuliere** [comment]
@march1993 it looks like a simple mistake rather than a bug. Did you solve the problem?

**Comment by march1993** [comment]
@singuliere  Thank you for your investigation. Would you try the following one please?

> I've desensitized the `gitea.db` and uploaded it here for who is interested in the sqlite db file. [gitea.zip](https://github.com/go-gitea/gitea/files/8503120/gitea.zip)

**Comment by singuliere** [comment]
@march1993 the message above is an investigation based on this file.

**Comment by march1993** [comment]
Aha. No wonder the error output differs. I can mail you the original database. Is `sxxxxxxxx@autxxxxxx.oxx` your mail address?

**Comment by singuliere** [comment]
I won't have time to do this myself but you can ask [in the forum](https://forum.hostea.org/t/gitea-upgrade-from-1-14-to-1-16-5-column-id-but-struct-has-not-related-field/48/2), I'm sure there will be an interest to solve this mystery.

**Comment by singuliere** [comment]
@march1993 did you figure it out? I'm eager to know how.
