### ISSUE TITLE
JS error in imagediff.js

### ISSUE THREAD

**Issue by wxiaoguang** [go-gitea/gitea#19414]
caught by https://github.com/go-gitea/gitea/pull/18971 (Show JS errors) , reported by a user.

caused by imagediff.js

```js
function getDefaultSvgBoundsIfUndefined(svgXml, src) {
  const DefaultSize = 300;
  const MaxSize = 99999;

  const svg = svgXml.rootElement; // BUG, here svg might be null, then the following `svg.width` triggers JS error

  const width = svg.width.baseVal;
  const height = svg.height.baseVal;
  if (width.unitType === SVGLength.SVG_LENGTHTYPE_PERCENTAGE || height.unitType === SVGLength.SVG_LENGTHTYPE_PERCENTAGE) {

```

![image](https://user-images.githubusercontent.com/2114189/163661672-01389a4a-e38e-4d34-a7f9-0a99ad04b1d0.png)

Compiled JS, the `index.js:37:1821` is at `c=o.width`
```
o=e.rootElement,c=o.width.baseVal,y=o.height.baseVal;if(c.unitType===SVGLength.SVG_LENGTHTYPE_PERCENTAG
```

**Comment by KN4CK3R** [comment]
Do you have an example svg?

**Comment by wxiaoguang** [comment]
No, I have asked but the reporter can not provide more information.

**Comment by wxiaoguang** [comment]
I managed to reproduce it. See https://try.gitea.io/wxiaoguang/test/pulls/6/files

**Comment by wxiaoguang** [comment]
I proposed a fix https://github.com/go-gitea/gitea/pull/19494
