### ISSUE TITLE
Adding more checkboxes deletes content on mobile

### ISSUE THREAD

**Issue by Giszmo** [go-gitea/gitea#19412]
### Description

Adding checkboxes in the markdown editor deletes the last word of the prior line on mobile.

To reproduce:

1. Open try.gitea on Android Firefox
2. Create issue
3. Type "some sentence"
4. Click the "checkbox" button

## Result

```
some
- [ ]
```
## Expected (and result on Firefox desktop)

```
some sentence
- [ ]
```

### Gitea Version

1.17.0+dev-428-gdeffe9e52

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

I noticed the issue on an install from snap but it's reproducible on try.gitea, too.

**Comment by wxiaoguang** [comment]
This issue could be resolve by 
* https://github.com/go-gitea/gitea/pull/23876

**Comment by delvh** [comment]
Yes, please try the latest state i.e. on https://try.gitea.io, and reopen this issue if it is still present.
