### ISSUE TITLE
"Create Pull Request" button is not disabled after first click

### ISSUE THREAD

**Issue by lehag92** [go-gitea/gitea#19410]
### Description

I my project when a developer clicks several times "Create Pull Request" because of server load, 2 requests where sent to server, and 2 PRs created.
Same behaviour I can reproduce on [try,gitea](https://try.gitea.io)https://try.gitea.io/
example:
<img width="702" alt="Screenshot 2022-04-15 at 20 41 05" src="https://user-images.githubusercontent.com/26865927/163603446-63181de0-da91-43ca-9725-6ead3d7ae7bc.png">

https://try.gitea.io/1234iiiii/test-PR/pulls

At least button can be disabled after first click. Or additional check on API that this PR already exists/

### Gitea Version

1.16.5

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

EC2 server hosted with packet through systemd

**Comment by wxiaoguang** [comment]
A longstanding problem with no progress yet.

* https://github.com/go-gitea/gitea/issues/17111
