### ISSUE TITLE
how to enable push-to-create option?

### ISSUE THREAD

**Issue by shikihane** [go-gitea/gitea#19420]
### Feature Description

I want create new repo when push a local repo   .
I find below option in the manual  :
**DEFAULT_PUSH_CREATE_PRIVATE: true:** 
But I can't find the **PUSH_CREATE** option.
how to enable **push-to-create** option ? 
how to use push-to-create option ?

**Comment by a1012112796** [comment]
https://docs.gitea.io/en-us/config-cheat-sheet/#repository-repository

![image](https://user-images.githubusercontent.com/25342410/163777905-2f159ae9-5342-4348-a4ea-d9699ea440ef.png)

usage: push to a not exist repo addr.

**Comment by shikihane** [comment]
> https://docs.gitea.io/en-us/config-cheat-sheet/#repository-repository
> 
> ![image](https://user-images.githubusercontent.com/25342410/163777905-2f159ae9-5342-4348-a4ea-d9699ea440ef.png)
> 
> usage: push to a not exist repo addr. example:
> 
> ```shell
> git remote add origin https://try.gitea.io/{user name}/{new repo name}.git
> git push -u origin main
> ```
> 
> then a new repo will be auto created.

Thanks, now there is new progress.
I add option on app.ini, as follow:
![O O YG3XKT3A%AAA0WX 56X](https://user-images.githubusercontent.com/48197860/163783744-c3ce5f7f-176c-40ad-b795-44d278b290a0.png)
Then i restarted the service.
But it is still not success, as follow:
![image](https://user-images.githubusercontent.com/48197860/163784496-dd27d8a3-b79c-4e3b-9cb4-dbeadd12a572.png)

**Comment by a1012112796** [comment]
@shikihane git version?

**Comment by shikihane** [comment]
> @shikihane git version?
@a1012112796 
git version 2.29.2.windows.3

**Comment by a1012112796** [comment]
have you try whether it's ok to push to an already exist repository in same website?

**Comment by shikihane** [comment]
![image](https://user-images.githubusercontent.com/48197860/163792391-afa924b1-a48f-4b24-b98c-f4d024599b44.png)
 Yes, it's successful for other already exist of repository

**Comment by shikihane** [comment]
> In your push-create examples you are trying to use https, but the "working" example uses http.

Thanks, Such is the case. Now it's successful.
