### ISSUE TITLE
Failed on release migration

### ISSUE THREAD

**Issue by mopinon** [go-gitea/gitea#19425]
### Description

I use last version gitea v1.16.5 via PostgreSQL 14.2
When migrating repositories from the github, I encountered a problem: `pq: value does not fit into character type varying(40)`

```
2022/04/19 11:42:20 [625e75ec] router: completed GET /user/task/5?_csrf=6mkrOo9wzGEBk-_Z6kUI6Sx2DOY6MTY1MDM1NzYyNDMwOTM1OTMwMA for [::1]:55411, 200 OK in 2.4ms @ user/task.go:17(user.TaskStatus)
5[REALEASE migrate.go] COMMIT SIZE 45 a-string-that-is-longer-than-forty-characters
2022/04/19 11:42:22 ...ervices/task/task.go:56:handle() [E] Run task failed: pq: value does not fit into character type varying(40)
        C:/Projects/gitea/services/task/task.go:56 (0x1f64005)
        C:/Projects/gitea/modules/queue/queue_disk_channel.go:60 (0x166f721)
        C:/Projects/gitea/modules/queue/queue_channel.go:65 (0x166d41d)
        C:/Projects/gitea/modules/queue/workerpool.go:561 (0x1680a0e)
        C:/Projects/gitea/modules/queue/workerpool.go:309 (0x167f2a4)
        C:/Program Files/Go/src/runtime/asm_amd64.s:1571 (0x46cc20)
```

The error occurred only when the Releases checkbox was checked

In the "Releases" table, only the Sha1 field has the data type charaсter varying(40)

I was surprised that sha1 has more than 40 characters and made logs
https://github.com/go-gitea/gitea/blob/b74322dfce8d15e9204900913bb815a7b0ba073f/models/migrate.go#L158-L183
I inserted the following code between lines 166 and 167 in the above file

`fmt.Println("5[REALEASE migrate.go] COMMIT SIZE", len(rel.Sha1), rel.Sha1)`

I saw the following in the logs: `5[REALEASE migrate.go] COMMIT SIZE 45 a-string-that-is-longer-than-forty-characters`
`a-string-that-is-longer-than-forty-characters` - the name of the branch from which the release was made

IIf you change the type of field in the database to text, the error disappears
It's strange, but the database eventually writes hashes of commits

I create [repo](https://github.com/mopinon/gitea-import-release) for reproduce this bug

 

### Gitea Version

v1.16.5

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![image](https://user-images.githubusercontent.com/58467666/163984724-95bf9c45-5e42-462b-a5b9-9d613b66c9a7.png)
![image](https://user-images.githubusercontent.com/58467666/163984744-10053e52-df54-47a7-910d-67038aaa7d2e.png)
![image](https://user-images.githubusercontent.com/58467666/163985002-d6f1b6a9-6fdd-42f8-ab07-96ff1005793b.png)

### Git Version

git version 2.35.1.windows.2

### Operating System

Windows 10

### How are you running Gitea?

use [gitea-1.16.5-windows-4.0-amd64.exe](https://github.com/go-gitea/gitea/releases/download/v1.16.5/gitea-1.16.5-windows-4.0-amd64.exe)
For the logs I made a build for win10 according to the instructions from README.MD

### Database

PostgreSQL

**Comment by lunny** [comment]
Look at the result of https://api.github.com/repos/mopinon/gitea-import-release/releases , github didn't return a commit hash but a branch name. But gitea expects a commit hash.

**Comment by mopinon** [comment]
> It's strange, but the database eventually writes hashes of commits

if gitea expects a commit hash, then how sha1 gets into the database? github returns the branch name.

The [github documentation](https://docs.github.com/en/rest/releases/releases#:~:text=MDc6UmVsZWFzZTE%3D%22%2C%0A%20%20%20%20%22tag_name%22%3A%20%22v1.0.0%22%2C-,%22target_commitish%22%3A%20%22master%22%2C,-%22name%22%3A%20%22v1.0.0%22%2C%0A%20%20%20%20%22body) states that `target_commitish` is the branch name

commit-ish is not necessarily a commit hash https://stackoverflow.com/questions/23303549/what-are-commit-ish-and-tree-ish-in-git

**Comment by lunny** [comment]
OK. I think the bug is we need to get tag commit hash but not from `target_commitish`
