### ISSUE TITLE
how to  create a file to wiki repos via api 

### ISSUE THREAD

**Issue by wupei1024** [go-gitea/gitea#19459]
### Feature Description

how to  create a file to wiki repos via api ,
the wiki repository 's name is "xxxx.wiki‘ when use api to create a file returns 404.

**Comment by Gusted** [comment]
You can create a wiki page via the API: https://try.gitea.io/api/swagger#/repository/repoCreateWikiPage Please check if the input's are correct, 404 means it didn't found the repository you did specify.

**Comment by wupei1024** [comment]
not a page , i want to commit an image to wiki repository 。like create a file to normal repository.

**Comment by Gusted** [comment]
Please better specify your question next time, but you cannot upload a file to a wiki. The wiki doesn't behave as a git repo. If you want to upload a file, use the repository, using a picture in a wiki page, you will have to use markdown for that `
![A picture](link_to_picture)`

**Comment by wupei1024** [comment]
> Please better specify your question next time, but you cannot upload a file to a wiki. The wiki doesn't behave as a git repo. If you want to upload a file, use the repository, using a picture in a wiki page, you will have to use markdown for that ` ![A picture](link_to_picture)`

yes, but i want to use an tool upload the attachment(image) to the wiki repository when i editing the wiki page.
use git to commit an image every time is troublesome..

**Comment by Gusted** [comment]
Watch the corresponding issue for that: https://github.com/go-gitea/gitea/issues/17231
