### ISSUE TITLE
admin page return 500 error

### ISSUE THREAD

**Issue by ycyxuehan** [go-gitea/gitea#19465]
log like this:
2022/04/22 10:50:06 ...s/context/context.go:206:HTML() [E] Render failed: template: admin/dashboard:8:90: executing "admin/dashboard" at <Str2html>: invalid value; expected string
2022/04/22 10:50:06 Completed GET /admin 500 Internal Server Error in 14.543567ms

**Comment by lunny** [comment]
What's your Gitea version?

**Comment by ycyxuehan** [comment]
> What's your Gitea version?

1.16.0, deploy by docker

**Comment by lunny** [comment]
This has been fixed, please upgrade to v1.16.6
