### ISSUE TITLE
Add s390x architecture support 

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#19473]
### Feature Description

I think Gitea supports that architecture, it’s good

**Comment by Gusted** [comment]
What's the exact request/feature here? Are there any errors when you try to build/running Gitea for s390x architecture? [Go](https://go.dev/) has support for the s390x on Linux operating systems.

**Comment by misakano7545** [comment]
> What's the exact request/feature here? Are there any errors when you try to build/running Gitea for s390x architecture? [Go](https://go.dev/) has support for the s390x on Linux operating systems.

But why don't add to release

**Comment by istiak101** [comment]
> But why don't add to release

I think that's a overhead to add a release type for arch that many people don't use. That's why they didn't add it.

**Comment by 6543** [comment]
@misakano7545 if you need it: https://pkgs.alpinelinux.org/packages?name=gitea&branch=edge&arch=s390x

add it to the normal build pipeline in here would require a lot more work ...
