### ISSUE TITLE
[API] Payloads too large for the database schema cause errors 500

### ISSUE THREAD

**Issue by cghislai** [go-gitea/gitea#19471]
### Description

While setuping a renovate bot to include release notes in its pull requests, i noticed that the gitea api was sometimes returning errors 500, causing the renovate job to fail.
The cause was a pull requests comment too large for the database schema, from what i get in the logs:

```
Mon, Apr 18 2022 2:04:24 pm | 2022/04/18 12:04:24 modules/web/route.go:70:func1() [I] [SQL] ROLLBACK [] - 224.592µs
Mon, Apr 18 2022 2:04:24 pm | 2022/04/18 12:04:24 .../api/v1/repo/pull.go:599:EditPullRequest() [E] UpdateIssueByAPI: Error 1406: Data too long for column 'content' at row 1
Mon, Apr 18 2022 2:04:24 pm | 2022/04/18 12:04:24 Completed PATCH /api/v1/repos/Valuya/embedded-webview/pulls/6 500 Internal Server Error in 40.601052ms
```

I think gitea should return a client error in the 4xx range in such cases, probably with a dedicated message.
That would be easier to handle by api consumers.

See also https://github.com/go-gitea/gitea/issues/18783 dealing with user input size limit in the UI
See also https://github.com/renovatebot/renovate/issues/15162 for the related renovate issue

### Gitea Version

1.15.10 

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

Using the helm chart deployed on a kubernetes cluster

### Database

PostgreSQL

**Comment by wxiaoguang** [comment]
Please use latest release, the field size of `context` has been fixed to correct value.

**Comment by cghislai** [comment]
thx, sorry i hadn't checked that :/

**Comment by wxiaoguang** [comment]
Feel free to re-open if there is still a problem
