### ISSUE TITLE
[Feature Request] Do not fail if wiki.git doesn't exist

### ISSUE THREAD

**Issue by istiak101** [go-gitea/gitea#19481]
### Feature Description

I do many local mirrors and I have to do migrations from Github. Usually I check all the options (mirror, lfs, wiki).

Most of the case I have to also check if there is actually any wiki(after few failed migrations I realized that checking those repo manually). Also in many cases wiki page for that repo was enabled but actually blank.

Is it possible to show a exact error message that wiki.git doesn't exist for that repo or not failing the migration and show there was no wiki.git?

Also is this possible to implement a retry button for migrations which would perform the same request again? Currently failed migrations only deletes the record and you have to fill all the details again. I have attached a screenshot for this request.

### Screenshots

![Screenshot from 2022-04-25 11-26-49](https://user-images.githubusercontent.com/30789544/165025899-89893b7b-b7a8-4e5b-8f04-19508a1e58df.png)

**Comment by zeripath** [comment]
Fixed by #19563
