### ISSUE TITLE
API endpoint for user activity

### ISSUE THREAD

**Issue by tianalemesle** [go-gitea/gitea#19488]
### Feature Description

Hello,

It would be nice to have an API endpoint for `/{username}?tab=activity` that could be queried with self/admin authentication to get items related to private repos.

Thanks

**Comment by KaKi87** [comment]
I have no idea.
I precisely specified which page I'd like to have an API for.
The mentioned issue might as well be related to the homepage.

**Comment by lunny** [comment]
> 

Yes. Let's continue there.

**Comment by ryanbsdeveloper** [comment]
Still without this endpoint?
