### ISSUE TITLE
Organization and repository not displaying on Dashboard

### ISSUE THREAD

**Issue by Dennis-Evans** [go-gitea/gitea#19491]
Version 1.15.8, MS SQL Server, running as a windows service

I have an organization with five repositories, the organization and the repositories do not display on the dashboard. 

the repositories display when the Explore option is used.   I am able to navigate to four of the five repositories, the remaining one, when selected displays the 500 error page.   The repository is present and can be used normally from a Git client.

The is archived flag in the database is set to false.

**Comment by lunny** [comment]
Please upgrade to latest stable version.
