### ISSUE TITLE
Login redirect lost url fragment

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#19498]
When you view a file like https://gitea.com/gitea/go-sdk/src/commit/603e4358f80d195dfe4d1c677716096df95656ce/gitea/repo_file.go#L126-L129 and when session is expired and you login you will be redirected to https://gitea.com/gitea/go-sdk/src/commit/603e4358f80d195dfe4d1c677716096df95656ce/gitea/repo_file.go.

**Comment by wxiaoguang** [comment]
That's how HTTP works. Fragment is not part of HTTP request if user is redirected by backend code. Unless the redirection occurs from frontend.

![image](https://user-images.githubusercontent.com/2114189/165227228-c927d9a8-2584-4806-a29e-39d50c4bac84.png)

**Comment by wxiaoguang** [comment]
Is it really a bug?

**Comment by zeripath** [comment]
yeah unfortunately we don't get the fragment as far as I understand.
