### ISSUE TITLE
Better build documentation

### ISSUE THREAD

**Issue by ogarcia** [go-gitea/gitea#195]
Add in README or in wiki a better documentation of build using tagged source from github. Something like this.

```
git clone https://github.com/go-gitea/gitea.git
cd gitea
git checkout latest_tag
etc...
```

**Comment by lunny** [comment]
In fact, `go get code.gitea.io/gitea` just OK for source installation. You can find this on `README.md` Installation section.

**Comment by ogarcia** [comment]
Yes, but is for master not for a tagged version :disappointed:

**Comment by lunny** [comment]
OK.

**Comment by bkcsoft** [comment]
@ogarcia tagged version should be downloaded as binaries IMO, otherwise you might as well run `master`.  
In other cases you can follow the instructions from `development` (but add the `git checkout $tag` yourself :)

**Comment by ogarcia** [comment]
@bkcsoft Yes. But, Where is `development` docs? I think that may be a link to docs into README.md.

And now `https://docs.gitea.io/ == Blank page` :disappointed:

In Arch Linux and Gentoo prefer make builds from tagged sources than use binaries :wink:

**Comment by bkcsoft** [comment]
> In Arch Linux and Gentoo prefer make builds from tagged sources than use binaries

And those who create the `PKGBUILD`/`ebuild`-files already knows how to do that 😉 (I'm an Arch-user myself)

**Comment by tboerger** [comment]
A proper documentation page is planned, we need to copy or create a Hugo theme, and than we need to migrate the Gogs docs.

**Comment by bkcsoft** [comment]
@tboerger "migrate"... under which license are the docs for Gogs? worst-case we have to re-write the docs...

**Comment by tboerger** [comment]
I have taken the same license as the Gogs docs to avoid that. First I wanted to do it with a creative commons license, but now it's also apache 2.0.

**Comment by tboerger** [comment]
https://github.com/go-gitea/docs/commit/cdfe6a8faffd0c6a2e4ecd279a14978afc965147

**Comment by lunny** [comment]
So, there are enough documents to resolve this issue?

**Comment by tboerger** [comment]
The biggest document is https://docs.gitea.io/en-us/hacking-on-gitea/ but we will also write https://docs.gitea.io/en-us/installation-from-source/ with more details.

**Comment by tboerger** [comment]
Solved via https://github.com/go-gitea/docs/pull/19
