### ISSUE TITLE
Negative open Pull request count persists

### ISSUE THREAD

**Issue by kricka91** [go-gitea/gitea#19505]
### Description

I have somehow been able to close a pull request twice, which results in an incorrect (negative) count of open pull request. This issue has supposedly been fixed in the code (https://github.com/go-gitea/gitea/pull/7518), but after I upgraded to Gitea 1.16.5 and migrated the data, the incorrect negative count still shows. The duplicate PR close probably happened a while ago using Gitea v1.10.1.

Will this be automatically corrected after opening or closing a new pull request, or should it have been corrected when migrating the database data? Or what do I need to do in order to correct this? I guess I could try something, but it would be good to get confirmation from someone who knows so that others with the same problem can see.

### Gitea Version

1.16.5

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

In Kubernetes with existing helm charts.

### Database

PostgreSQL

**Comment by wxiaoguang** [comment]
Longstanding problem related to
* https://github.com/go-gitea/gitea/issues/17111
* https://github.com/go-gitea/gitea/issues/18330

**Comment by kricka91** [comment]
Well, I guess one problem is the duplicate comments/closes, and another problem is the negative pull request count, which is caused by the former. I could live with the duplicate closes still being shown in the UI, but I would really like the pull request count to be accurate. Is it correct that the fix I linked to (#7518) is supposed to address this? And if so, when is the code in the fix executed?

**Comment by kricka91** [comment]
Nothing is updated automatically at midnight, unless of course it continues to compute it incorrectly.

I cannot find any feature like this in the Gitea GUI. Is it a setting on an organization level? Repo level? Global level?

**Comment by wxiaoguang** [comment]
> Nothing is updated automatically at midnight, unless of course it continues to compute it incorrectly.
> 
> I cannot find any feature like this in the Gitea GUI. Is it a setting on an organization level? Repo level? Global level?

`the feature is on admin -> monitoring -> Check all repository statistics`, if it doesn't help, then they are not related either.

**Comment by kricka91** [comment]
Ok, I found it. I had to be logged in as **gitea_admin** and go to **Site Administration** to find it. However, running it didn't help, and it also shows that the task has been executed last midnight, even though I didn't see any results of that. Probably something else, then.

**Comment by PotatoesFall** [comment]
I reported this same issue a while ago in #19349, good to see it is now being tackled!

**Comment by lunny** [comment]
duplicated with #19349
