### ISSUE TITLE
local git

### ISSUE THREAD

**Issue by xyz5s** [go-gitea/gitea#1950]
hello
i got to have no access to clone local repo when i make a mirrors from github or other platfrom
how can i setting it

**Comment by cez81** [comment]
Sorry I don't understand what you're trying to say...

**Comment by lunny** [comment]
I think @shiwen5 means He cannot import local git repo. @shiwen5 You should change the ini file before do that.

**Comment by cez81** [comment]
```
[security]
; True when users are allowed to import local server paths
IMPORT_LOCAL_PATHS = true
```

**Comment by bkcsoft** [comment]
You also have to allow the user to do this in the admin-panel
