### ISSUE TITLE
Permalink Files In PR Diff

### ISSUE THREAD

**Issue by kdumontnu** [go-gitea/gitea#19525]
### Feature Description

GitHub allows users to click a file in a PR diff and copy a permalink to that file, which makes it easy to share a specific file in a PR and/or decorate a PR description.

GitHub appears to create some kind of hash for each file. For example: `https://github.com/go-gitea/gitea/pull/17145/files#diff-23ceed4d2a9f0e4f08ead9fd5b74b481e40e029fd83cd0453f9c0a2edfd53577`

This can be extended to adding a permalink to specific lines in the diff, but probably warrants a separate issue.

### Screenshots

<img width="1090" alt="image" src="https://user-images.githubusercontent.com/12700993/165434235-e9adf770-ea8e-4d83-a904-809256da2e1b.png">

**Comment by KN4CK3R** [comment]
The GitHub hash is btw the sha256 of the filename.
