### ISSUE TITLE
Metadata inheritance from issue to pull request

### ISSUE THREAD

**Issue by tdido** [go-gitea/gitea#19529]
### Feature Description

In GitLab, if when working on an issue you name your branch starting with the issue number (e.g. "123-doing-something"), when creating a merge request from that branch the request inherits the issue's metadata (labels, milestone, etc.), and gets the `Closes #123` comment to auto-close the issue added to it.

I find it extremely helpful for my workflow and I thought others may as well.

**Comment by lunny** [comment]
Maybe duplicate of #20226
