### ISSUE TITLE
CompareAndPullRequestPost() causes internal server error

### ISSUE THREAD

**Issue by skaldesh** [go-gitea/gitea#19527]
### Description

I have a repository with a *vendor* folder in the master branch. In separate feature branch, I deleted this folder and replaced it with a git submodule. I then tried to create a Pull Request in the gitea UI, which causes a 500 Internal Server Error:

Error in the logs:  
```
2022/04/26 16:20:39 ...ers/web/repo/pull.go:1164:CompareAndPullRequestPost() [E] NewPullRequest: exit status 128 - vendor: unmerged (b9193c1afe1d0bd874d6f995bcbf1fc98d249588)
	fatal: git-write-tree: error building trees
```

### Gitea Version

     1.16.6 built with GNU Make 4.3, go1.18.1 : bindata, timetzdata, sqlite, sqlite_unlock_notify

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

     2.30.3

### Operating System

Official Gitea Docker image

### How are you running Gitea?

Via docker-compose

### Database

SQLite

**Comment by phostann** [comment]
The same error, wait for an answer.

**Comment by Fogapod** [comment]
Error persists on `1.17.0+rc1`. Replaced git submodule with normal folder (just copied submodule contents in instead of using submodule) in feature branch and I cannot make a PR from that branch to main that has it

**Comment by LJFan** [comment]
When I new pull request (pull from branch A and merge into master), a similar error will appear.
But when I pull from master and merge into branch A, it succeeds.
It's weird.
```
2022/07/01 16:24:16 ...dules/git/command.go:146:RunWithContext() [D] D:/gitea/data/tmp/local-repo\pull.git1357600457: C:\Program Files\Git\cmd\git.exe -c credential.helper= -c protocol.version=2 -c uploadpack.allowfilter=true -c uploadpack.allowAnySHA1InWant=true -c filter.lfs.required= -c filter.lfs.smudge= -c filter.lfs.clean= apply --check --cached --3way C:\WINDOWS\TEMP\patch1298657802
2022/07/01 16:24:16 ...ers/web/repo/pull.go:1164:CompareAndPullRequestPost() [E] NewPullRequest: git apply --check: exit status 1
2022/07/01 16:24:16 ...s/context/context.go:214:HTML() [D] Template: status/500
```

**Comment by SteadEXE** [comment]
When I try to merge master into my branch B, I have the same issue error 500.

**Comment by LJFan** [comment]
I have fixed it by using the `git merge` command to merge branch A into master locally.
Then I can new pull request (pull from branch A and merge into master).

**Comment by SteadEXE** [comment]
I did the same, I was stuck with the GUI

**Comment by zeripath** [comment]
It would be very helpful if you could create a simple test case to replicate this issue.

The likely problem is in TestPatch and is related to the three-way merge here. 

The error will most likely be originating here:

https://github.com/go-gitea/gitea/blob/713bc6c8dca072c3946e5ff1ab6b1c58748f1a1a/services/pull/patch.go#L266

**Comment by zeripath** [comment]
Now the issue is how is one supposed to handle merging when a submodule is turned into a directory or vice versa?

**Comment by zeripath** [comment]
I have attempted to replicate this locally and on try.gitea.io and am unable to replicate on main.

https://try.gitea.io/arandomer/module-test/pulls/1

**Comment by parnic** [comment]
@zeripath and others - I _am_ able to reproduce this on try.gitea.io (after running into it on our production server). Here's what I did:
1. Create a repo with a file that will eventually be added as a submodule elsewhere: https://try.gitea.io/parnic/temp-repo
2. Create a repo that will eventually hold the submodule: https://try.gitea.io/parnic/submodule-replace-test
3. Add a directory that will be swapped out with the submodule afterward.
4. Create a branch that swaps out the directory with a submodule in the same place: https://try.gitea.io/parnic/submodule-replace-test/commits/branch/submodule-replace
5. Attempt to open a PR for that branch: https://try.gitea.io/parnic/submodule-replace-test/compare/main...submodule-replace
6. Click New Pull Request then Create Pull Request results.
7. Get a 500 error (and, I assume, the same error on the server as is reported in this chain).

Is that enough to go off of? I can provide exact git commands if needed, but hopefully they're obvious from the above links.

**Comment by zeripath** [comment]
OK adding some logging here, the problem appears to be that:

```
	160000 8d33ac46845bd6695b643385280e2d6fc2f945a6 3	temp
```

is left unmerged.

AHA I've found the bug

**Comment by zeripath** [comment]
This was resolved thanks to @parnic for providing the clear testcase and instructions for reproducing the issue.

Once I was able to reproduce the issue using the provided try.gitea.io example I was able to work through the issue in little time.

This really highlights the importance of giving us simple reproducing testcases.

Thanks once again to @parnic for providing the testcase.
