### ISSUE TITLE
Migrating repo from GitLab fails if Wiki is checked

### ISSUE THREAD

**Issue by fnetX** [go-gitea/gitea#19545]
### Description

Migrating repos from GitLab fails if the user ticks the "wiki" option in Gitea, tested from https://gitlab.com/interpeer/caprock which was reported on https://Codeberg.org

It works fine if the "wiki" checkbox is left unticked. Probably a check is missing that the wiki exists // what is the branch.

log excerpt (seems relevant):
~~~
2022/04/28 22:06:21 ...s/repository/repo.go:102:MigrateRepositoryGitData() [W] Clone wiki: exit status 128 - fatal: Remote branch master not found in upstream origin
	
2022/04/28 22:06:23 ...ervices/task/task.go:56:handle() [E] Run task failed: unable to write commit-graph for '/data/git/gitea-repositories/interpeer/liberate.wiki.git' : chdir /data/git/gitea-repositories/interpeer/liberate.wiki.git: no such file or directory
~~~

### Gitea Version

1.17.0+dev-491-g8eb1cd926

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

Codeberg deployment + try.gitea.io

**Comment by 6543** [comment]
`Migrate repository from https://gitlab.com/interpeer/caprock failed: unable to write commit-graph for '/data/git/gitea-repositories/6543/caprock2.wiki.git' : chdir /data/git/gitea-repositories/6543/caprock2.wiki.git: no such file or directory`

-> this is is happening because the "wiki" is activated in gitlab but it's an empty git issue if you like to clone it

**Comment by fnetX** [comment]
https://gitlab.com/interpeer/caprock/-/wikis/home it still looks empty, so probably can be checked via API? I'm just wondering if another error could occur on cloning an existing wiki and would not be detected with your change.

**Comment by 6543** [comment]
@fnetX blame gitlab, yes you can check via API - **but** it wont tell you anything about the state (if initialized or empty)

**Comment by 6543** [comment]
my pull https://github.com/go-gitea/gitea/pull/19563 does fix by the way ...
