### ISSUE TITLE
Package Docs should include info about required gitea version

### ISSUE THREAD

**Issue by Topograph** [go-gitea/gitea#19549]
I think the package registry features are available from gitea version 1.17.0 it caused me some headaches trying to follow the documentation at [https://docs.gitea.io/en-us/packages/overview/](https://docs.gitea.io/en-us/packages/overview/) and searching why "packages" tab wouldn't show up on my 1.16.0 gitea instance until i figured out that that feature is yet to be released.

Maybe there should be a "Requirements"-Section in the docs explaining from which version on the feature is available.

**Comment by wxiaoguang** [comment]
* https://github.com/go-gitea/gitea/issues/5588
* https://github.com/go-gitea/gitea/pull/17905
