### ISSUE TITLE
[Proposal] Drop git 1.x support, or fix the IsEmpty bug

### ISSUE THREAD

**Issue by wxiaoguang** [go-gitea/gitea#19554]
There is an obvious bug in Gitea that `IsEmpty` check always fails in git 1.x (git 1.x reports an error for that command), it makes many users only see empty repositories after they have pushed content in.

* https://github.com/go-gitea/gitea/issues/19086 
(and more)

The only reason to support git 1.x IIRC is for CentOS 7.x users.

However, CentOS 7.x is quite old, and the users could always have other solutions: upgrade git (ius/wandisco/endpoint), or use docker to run Gitea.

Since Gitea is reaching 1.17, it's time to make the decision.

* 👍 Drop git 1.x support
* 🎉 [or] Fix the `IsEmpty` bug

I prefer to drop git 1.x support.

**Comment by lafriks** [comment]
I would also vote for dropping git 1.x support

**Comment by silverwind** [comment]
We should probably define a minimum git version visibly in the docs and maybe emit a startup warning if it's too old. A good starter might be git 2.17 which is the latest upstream-supported version.

**Comment by wxiaoguang** [comment]
@go-gitea/maintainers 

It seems that this proposal gets votes for `drop git 1.x support`.

Any objection? If no objection, then we can move on.

**Comment by lunny** [comment]
> @go-gitea/maintainers
> 
> It seems that this proposal gets votes for `drop git 1.x support`.
> 
> Any objection? If no objection, then we can move on.

I update the issue content to add two emoji to make vote easier. :)

**Comment by wxiaoguang** [comment]
Since there is no objection (yet), so the PR comes, a very simple PR:
* #19577

**Comment by silverwind** [comment]
> Do you have some references about this information? I can not find the earliest supported git version.

I was going off [Wikipedia](https://en.wikipedia.org/wiki/Git#Releases), not sure how accurate that info is, but the release dates seem to confirm it.

**Comment by wxiaoguang** [comment]
Interesting .... I prefer maybe we do not need to hard-code these minor versions into code, without these detailed version, it reduces the maintenance workload, and gitea still works correctly. And there are a lot of git version check inside gitea, maybe they should be upgraded together in future.

**Comment by eeyrjmr** [comment]
One consideration for the minimum is any associated security issues
https://www.cvedetails.com/vulnerability-list/vendor_id-15815/product_id-33590/Git-scm-GIT.html
