### ISSUE TITLE
GroupClaimName not used to map user to team

### ISSUE THREAD

**Issue by Morriz** [go-gitea/gitea#19555]
### Description

Hi, I consider this a bug, but you decide:

According to this merged PR https://github.com/go-gitea/gitea/pull/16766/files#diff-190f875ffe99e881bafbd2fae54d5099c9d52bf13bd7c9a3ba434323e82078af it would now be possible to map content of OIDC claim name to teams, so that setting `GroupClaimName` to "groups", and seeing a JWT with "groups" claim containing ["bla"], would try to add the user to team bla if it exists.

The `adminGroup` is correctly identified, so the parts are already working I think.

### Gitea Version

1.16.6

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

helm chart with image running version mentioned above.

### Database

PostgreSQL

**Comment by Morriz** [comment]
reference post from @zeripath: https://github.com/go-gitea/gitea/issues/10016#issuecomment-903123957

**Comment by zeripath** [comment]
It never promised to do this.

**Comment by Morriz** [comment]
Ah, to me it gave that impression when I saw those options. Would it be hard to map the groups claim to teams? Should I make a separate issue for that?

**Comment by KN4CK3R** [comment]
Implemented this in #21441, please test it.
