### ISSUE TITLE
rootless image migration plans

### ISSUE THREAD

**Issue by dkanada** [go-gitea/gitea#19564]
### Feature Description

Just curious if there were still plans to use the rootless image by default at some point as mentioned in #10154 last year. Seems like a year might be good enough to make the switch, but if that idea was dropped then feel free to disregard this suggestion.

**Comment by wxiaoguang** [comment]
I would suggest not use rootless at the moment, due to the builtin ssh server key exchange bug (from upstream).
* https://github.com/go-gitea/gitea/issues/17910
* https://github.com/go-gitea/gitea/issues/17798

**Comment by techknowlogick** [comment]
Closing as the rootful image is still rather popular and the user support load from switching to rootless would be rather significant.
