### ISSUE TITLE
Dashboard shows deleted comments

### ISSUE THREAD

**Issue by gayprogrammer** [go-gitea/gitea#1956]
- Gitea version (or commit ref): 1.1.1+2-g2854c8a
- Git version: 2.12.2
- Operating system: Windows Server 2012
- Database (use `[x]`):
  - [x] MSSQL
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes [gitpitch/code-presenting/issues/1](https://try.gitea.io/gitpitch/code-presenting/issues/1) (dashboard screenshot attached)
- Log gist: Not relevant

The Dashboard page shows activity for a deleted comment. I think this should not be shown because the comment is no longer visible on the issue. 

![image](https://user-images.githubusercontent.com/1140256/27052981-8636a3a6-4f70-11e7-8afd-6c18e6f60423.png)

**Comment by jonasfranz** [comment]
Could somebody assign this issue to me? I have insufficient permissions.

**Comment by lunny** [comment]
@JonasFranzDEV It seems it cannot be assigned to you on Github. But I think you can go ahead. I marked this for you.
