### ISSUE TITLE
Resend webhook payloads from everywhere the result is displayed

### ISSUE THREAD

**Issue by McNetic** [go-gitea/gitea#19573]
### Feature Description

While it is possible to resend webhooks from the webhook configuration page, it is not very convenient. If a build fails for technical reasons (timeout, build server problems, dependency problems or whatever that has not to be fixed by fixing the code itself, it would be very helpful if it could be triggered again from where the result is display (be it the commit history or pull request). Especially, since the build may have failed while the webhook itself is succesful, so it is very complicated to find the correct one from the recent deliveries.

**Comment by techknowlogick** [comment]
Webhooks != Statuses on commits. You can set statuses on commits without even needing a webhook active on a repo.

**Comment by McNetic** [comment]
> Webhooks != Statuses on commits. You can set statuses on commits without even needing a webhook active on a repo.

I don't see how answer relates to the feature request. Everywhere the webhook result is displayed, there is also a link to the "Details". I don't see why it should not be possible to add a replay button. Could you please elaborate and/or reopen the issue?

**Comment by McNetic** [comment]
It would be very nice if you could explain why this is not a valid feature request.

**Comment by lunny** [comment]
Because you don't know the commit statuses come from which webhook or a cron task. At least you cannot track that both in Github and Gitea.
