### ISSUE TITLE
Modern browsers block 10080 port with error: ERR_UNSAFE_PORT

### ISSUE THREAD

**Issue by 2375399351** [go-gitea/gitea#19571]
### Description

The url automatically jumps to about:blank
DOMAIN = 192.168.2.240
SSH_DOMAIN = 192.168.2.240
HTTP_PORT = 3000
ROOT_URL = http://192.168.2.240:10080/
Only iOS had the problem
![09EEC9A8-39DD-4743-9E38-7DB68F637DB7](https://user-images.githubusercontent.com/34334506/166126982-24b8f6d4-aac0-40db-b109-f5c3310b4757.gif)

### Gitea Version

1.16.5

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

docker

**Comment by 2375399351** [comment]
I try to turn off the content blocker and request desktop access, both get the same error

**Comment by wxiaoguang** [comment]
```
Can you reproduce the bug on the Gitea demo site?

Yes
```

If you are correct, please provide more clues. At least you should clarify why the desktop browser doesn't work.

**Comment by wxiaoguang** [comment]
If you need help other than bug report, please see refer to : https://docs.gitea.io/en-us/seek-help/

You may need `Support for the Chinese language is provided ....  QQ Group 328432459 `

**Comment by 2375399351** [comment]
> ```
> Can you reproduce the bug on the Gitea demo site?
> 
> Yes
> ```
> 
> If you are correct, please provide more clues from `try.gitea.io`. I have tested on iOS, `try.gitea.io` works correctly with iOS Safari.
> 
> At least you should clarify why the browser doesn't work. It's very likely your configuration or network problem.

I found the reason.
app.ini:
APP_DATA_PATH    = /data/gitea
DOMAIN           = 192.168.2.240
SSH_DOMAIN       = 192.168.2.240
HTTP_PORT        = 3000
ROOT_URL         = http://192.168.2.240:3000/
docker network:host
All my devices can be accessed through IP: 3000

app.ini:
APP_DATA_PATH    = /data/gitea
DOMAIN           = 192.168.2.240
SSH_DOMAIN       = 192.168.2.240
HTTP_PORT        = 3000
ROOT_URL         = http://192.168.2.240:10080/
docker network:bridge
web_port 10080:3000
Only PC can access through IP: 10080
Mobile Access tips：net::ERR_UNSAFE_PORT

NAS IP:192.168.2.240
But I don't know the reason for this problem

> ```
> Can you reproduce the bug on the Gitea demo site?
> 
> Yes
> ```
> 
> If you are correct, please provide more clues from `try.gitea.io`. I have tested on iOS, `try.gitea.io` works correctly with iOS Safari.
> 
> At least you should clarify why the browser doesn't work. It's very likely your configuration or network problem.

I found the reason.
app.ini:
APP_DATA_PATH    = /data/gitea
DOMAIN           = 192.168.2.240
SSH_DOMAIN       = 192.168.2.240
HTTP_PORT        = 3000
ROOT_URL         = http://192.168.2.240:3000/
docker network:host
All my devices can be accessed through IP: 3000

app.ini:
APP_DATA_PATH    = /data/gitea
DOMAIN           = 192.168.2.240
SSH_DOMAIN       = 192.168.2.240
HTTP_PORT        = 3000
ROOT_URL         = http://192.168.2.240:10080/
docker network:bridge
web_port 10080:3000
Only PC can access through IP: 10080
Mobile Access tips：net::ERR_UNSAFE_PORT

NAS IP:192.168.2.240
But I don't know the reason for this problem

**Comment by 2375399351** [comment]
> > ```
> > Can you reproduce the bug on the Gitea demo site?
> > 
> > Yes
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > If you are correct, please provide more clues from `try.gitea.io`. I have tested on iOS, `try.gitea.io` works correctly with iOS Safari.
> > At least you should clarify why the browser doesn't work. It's very likely your configuration or network problem.
> 
> I found the reason. app.ini: APP_DATA_PATH = /data/gitea DOMAIN = 192.168.2.240 SSH_DOMAIN = 192.168.2.240 HTTP_PORT = 3000 ROOT_URL = http://192.168.2.240:3000/ docker network:host All my devices can be accessed through IP: 3000
> 
> app.ini: APP_DATA_PATH = /data/gitea DOMAIN = 192.168.2.240 SSH_DOMAIN = 192.168.2.240 HTTP_PORT = 3000 ROOT_URL = http://192.168.2.240:10080/ docker network:bridge web_port 10080:3000 Only PC can access through IP: 10080 Mobile Access tips：net::ERR_UNSAFE_PORT
> 
> NAS IP:192.168.2.240 But I don't know the reason for this problem
> 
> > ```
> > Can you reproduce the bug on the Gitea demo site?
> > 
> > Yes
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > If you are correct, please provide more clues from `try.gitea.io`. I have tested on iOS, `try.gitea.io` works correctly with iOS Safari.
> > At least you should clarify why the browser doesn't work. It's very likely your configuration or network problem.
> 
> I found the reason. app.ini: APP_DATA_PATH = /data/gitea DOMAIN = 192.168.2.240 SSH_DOMAIN = 192.168.2.240 HTTP_PORT = 3000 ROOT_URL = http://192.168.2.240:3000/ docker network:host All my devices can be accessed through IP: 3000
> 
> app.ini: APP_DATA_PATH = /data/gitea DOMAIN = 192.168.2.240 SSH_DOMAIN = 192.168.2.240 HTTP_PORT = 3000 ROOT_URL = http://192.168.2.240:10080/ docker network:bridge web_port 10080:3000 Only PC can access through IP: 10080 Mobile Access tips：net::ERR_UNSAFE_PORT
> 
> NAS IP:192.168.2.240 But I don't know the reason for this problem

I know the reason. Port 10080 is not secure and is shielded by default
