### ISSUE TITLE
Popup window should be displayed in the front of editor form

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#19580]
### Description

The popup window should be displayed in the front of editor form.

### Gitea Version

1f0541780

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

![image](https://user-images.githubusercontent.com/81045/166203758-b52261c3-d1ec-4c66-8270-64fb57146494.png)

### How are you running Gitea?

https://gitea.com

**Comment by silverwind** [comment]
Link to page with issue? It's very likely a problem with CSS stacking contexts that can only be fixed via "portalling" the popup.

**Comment by lunny** [comment]
Visit https://gitea.com/gitea/go-sdk/issues/558 and move the mouse over `#543`

**Comment by silverwind** [comment]
Hmm, that popup stays loading for me forever with a JS error:

```
TypeError: can't access property "full_name", e.issue.repository is undefined
```

**Comment by wxiaoguang** [comment]
Fixed by 
* https://github.com/go-gitea/gitea/pull/20393
