### ISSUE TITLE
Complete installation without user interaction

### ISSUE THREAD

**Issue by osresearch** [go-gitea/gitea#19616]
### Feature Description

For building automated deployments it would be helpful if the installation could be completed without requiring any user interaction on the website. My scripts pre-provision all of the database, hostnames, etc information via the environment, but the scripts can't setup extra features like single-sign-on OIDC login until the database has been initialized by someone loading the install page and clicking "`Install Gitea`" at the bottom.

This could be done either via an environment var that says "everything is configured" or if there was an `gitea admin` command that would finalize the install and build the database.

**Comment by osresearch** [comment]
I've tried using `curl` to `POST` the form data to the web site, but it looks like there might be some cookie management that needs to be done to get `gitea` to accept it.

**Comment by wxiaoguang** [comment]
Set `INSTALL_LOCK=true` means the instance has been installed, then no installation page.

And you can refer to the helmchart config.

Feel free to reopen if you meet other problems.
