### ISSUE TITLE
SSH server can be disabled if not used.

### ISSUE THREAD

**Issue by AnkitShankdhar** [go-gitea/gitea#19619]
### Feature Description

Description: Nessus failed to successfully authenticate directly to the remote target on an available authentication protocol. Nessus was able to connect to the remote port and identify that the service running on the port supports an authentication protocol, but Nessus failed to authenticate to the remote service using the provided credentials.

There may have been a failure in protocol negotiation or communication that prevented authentication from being attempted or all of the provided credentials for the authentication protocol may have been invalid. A protocol failure may indicate a compatibility issue with the protocol configuration. A protocol failure due to an environmental issue such as resource or congestion issues may also prevent valid credentials from being identified. See plugin output for error details.

This plugin reports per protocol, so it is possible for valid credentials to be provided for one protocol and not another. For example, authentication may succeed via SSH but fail via SMB, while no credentials were provided for an available SNMP service.
Providing valid credentials for all available authentication protocols may improve scan coverage, but the value of successful authentication for a given protocol may vary from target to target depending upon what data (if any) is gathered from the target via that protocol. For example, successful authentication via SSH is more valuable for Linux targets than for Windows targets, and likewise successful authentication via SMB is more valuable for Windows targets than for Linux targets.
Solution: Address the reported problem(s) so that credentialed checks can be executed.

Once Tenable detects an SSH service, it should be able to login and execute local checks (create software inventory, check OS/patch level, etc).

In case the SSH server of Gitea is not used , then it should be disabled so that any scanner won't get port 22 in open state.

**Comment by wxiaoguang** [comment]
I think you can always disable the SSH server, can't you?

**Comment by AnkitShankdhar** [comment]
The SSH Service is disabled , but the SVC shows the port 22. The port 22 is been scanned by the scanner and report the issue.

gitea-ssh                      ClusterIP   None             <none>        22/TCP

**Comment by wxiaoguang** [comment]
It's not related to Gitea itself, but docker-compose/helmchart or other methods you used to deploy Gitea.

For helmchart, see: https://gitea.com/gitea/helm-chart/src/branch/master/templates/gitea/ssh-svc.yaml

You could propose PRs on the helmchar repository.
