### ISSUE TITLE
Tags not showing up on try.gitea.io web interface

### ISSUE THREAD

**Issue by parnic-sks** [go-gitea/gitea#19622]
### Description

While trying to report another bug, I pushed a repo with tags to https://try.gitea.io/parnic-sks/tag-release-test, and noticed that the Tags section is empty.

```
git ls-remote --tags
```

shows that the tags are there, and if I delete the tags from the remote and re-push them, they still don't show up.

I realize this is a demo site, but I wanted to report it in case this is a bug that could make its way into the 1.17 release. Our 1.16.7 installation locally is not having this issue; tags show up just fine there.

### Screenshots

Bug:
<img width="600" alt="image" src="https://user-images.githubusercontent.com/62021255/167004088-d076d674-6033-4c8d-8480-08465d486931.png">

Despite:
<img width="355" alt="image" src="https://user-images.githubusercontent.com/62021255/167004137-b09d0434-a31c-4df6-9b19-90756e74220e.png">

Expected:
<img width="595" alt="image" src="https://user-images.githubusercontent.com/62021255/167004179-bb3b987e-4d8e-46fb-9eff-41d2d5101543.png">

### Gitea Version

Current try.gitea.io: 1.17.0+dev-532-gb536b6518

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

Windows 11

### Browser Version

Chrome Version 100.0.4896.127 (Official Build) (64-bit)

**Comment by Gusted** [comment]
Hmm weird, locally everything seems fine.

CC @go-gitea/owners could you have a look?

**Comment by lunny** [comment]
It maybe a bug. On the dropdown menu, tags could be listed, but not in the tags tab

![image](https://user-images.githubusercontent.com/81045/167050254-b6c06e00-f01d-48d1-9c2f-411405f26ec7.png)

**Comment by Gusted** [comment]
Those tags are loaded directly from git repo. The tags in the header are loaded from the database(which should be updated on a push with tags). Does try.gitea.io have too many pushes in it's queue? From my perspective it doesn't seems like a bug because I cannot reproduce it locally.

**Comment by Ryuno-Ki** [comment]
> Does try.gitea.io have too many pushes in it's queue?

Unlikely. One month later and the tags still do not appear at https://try.gitea.io/parnic-sks/tag-release-test

**Comment by techknowlogick** [comment]
Due to seccomp change git hooks weren't being run on try, this has been resolved.
