### ISSUE TITLE
Using the New Release link on a tag does not set up the release correctly

### ISSUE THREAD

**Issue by parnic-sks** [go-gitea/gitea#19623]
### Description

When pressing New Release on a tag, the Release page doesn't set the Target combo box correctly, so the user must manually change the branch in order to successfully create the release.

### Screenshots

From the Tags page:
<img width="413" alt="image" src="https://user-images.githubusercontent.com/62021255/167005119-a39fd8d0-ba03-4ae5-9a8c-09f286f07625.png">

When pressing New Release:
<img width="613" alt="image" src="https://user-images.githubusercontent.com/62021255/167004609-770984bd-7263-49b7-9b65-3c5a2ec3149c.png">

But if I fill in a Title and try to click Publish, I get:
<img width="584" alt="image" src="https://user-images.githubusercontent.com/62021255/167004663-0a207a21-64c5-4966-94bc-a739b57ec933.png">

The fix is to open the Target drop-down box and change the target to the actual branch:
<img width="408" alt="image" src="https://user-images.githubusercontent.com/62021255/167004762-056de591-38c1-412f-b0fa-c036bf1bde25.png">

Doing so removes the original "Target : [branchname]" option entirely:
<img width="458" alt="image" src="https://user-images.githubusercontent.com/62021255/167004864-d3f2db13-ec79-4826-92b7-abaf29d02d0a.png">

### Gitea Version

1.16.7

### Can you reproduce the bug on the Gitea demo site?

No, but the only reason is because tags currently don't show up at all (see issue #19622)

### Operating System

Windows 11

### Browser Version

Chrome Version 100.0.4896.127 (Official Build) (64-bit)

**Comment by agsiegel** [comment]
I have experienced this bug as well in 1.16.7
