### ISSUE TITLE
replace sync module

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#19620]
replace "code.gitea.io/gitea/modules/sync" with a cluster aware one ( #13791)

ref https://github.com/go-gitea/gitea/pull/19520/files#r859289575

https://github.com/go-gitea/gitea/blob/7b089c465d9f851454be91ca209ab26782648a45/services/pull/pull.go#L32-L33
https://github.com/go-gitea/gitea/blob/7b089c465d9f851454be91ca209ab26782648a45/services/repository/transfer.go#L21-L23
https://github.com/go-gitea/gitea/blob/7b089c465d9f851454be91ca209ab26782648a45/services/wiki/wiki.go#L30-L31

**Comment by lunny** [comment]
The first one could be replaced by a unique queue at the moment to prevent there are two tasks for one pull request.
