### ISSUE TITLE
No way to re-select a generated avatar if a custom avatar has been selected

### ISSUE THREAD

**Issue by typeless** [go-gitea/gitea#1962]
- Gitea version (or commit ref):
Gitea Version: 1.1.0+307-gad70af1

- Git version:
2.7.4

- Operating system:
Ubuntu 16.04

- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite

- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant

## Description
If the user has selected a custom avatar, he can not 'opt-out' to use a generated avatar anymore.
...

**Comment by daviian** [comment]
@typeless @lunny Fixed with PR https://github.com/go-gitea/gitea/pull/3988
