### ISSUE TITLE
Team repository view also shows archived repo's

### ISSUE THREAD

**Issue by jpraet** [go-gitea/gitea#19639]
### Description

The repository count:

![image](https://user-images.githubusercontent.com/2212615/167155787-70675609-5a31-4e83-94d8-cf8e5d0ab949.png)

and the list of repositories assigned to the team:

![image](https://user-images.githubusercontent.com/2212615/167156106-fb615a13-f279-4355-bf04-34d413509091.png)

... also include the archived repositories. I'm not sure but I don't think they should?

### Gitea Version

1.16.7

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

docker

**Comment by lafriks** [comment]
why not, archived does not mean that users should not be able to access them. Archived repository could be private and it would still be need for users to access it, at least as readonly

**Comment by jpraet** [comment]
The repositories view on the dashboard does not include archived repo's though.

![image](https://user-images.githubusercontent.com/2212615/167161862-60c05990-412b-4b48-a7c7-4971923c25cd.png)

(well, actually the total repositories count does include it, but the "All" tab does not show the archived repo).

**Comment by lunny** [comment]
Maybe we need to change dashboard.

**Comment by lafriks** [comment]
> Maybe we need to change dashboard.

I don't think it's needed, dashboard is for quick access and archived repositories is usually not needed daily :)

This was changed to hide archived here to remove list growing too big in this PR #11440

Archived repositories is still listed in owner repository list

**Comment by lafriks** [comment]
They can still be accessible using dashboard:
![attels](https://user-images.githubusercontent.com/165205/167173460-b81f222a-1ac7-4ca0-88d7-15b1fca18fc6.png)

**Comment by jpraet** [comment]
I see. OK, I think the only change needed then is to label the repo as "archived" on the team repositories view.

**Comment by lafriks** [comment]
I don't think marking it as archived in team settings repository list gives much context, it's more administrative interface.. but if anyone submits PR I would not be blocking it 😄
