### ISSUE TITLE
[Question] Does gitea dump protect against data corruption when backing up live repos?

### ISSUE THREAD

**Issue by annanyearian** [go-gitea/gitea#19640]
### Feature Description

I have been reading about how to backup git repositories and there is some concern from 9 years ago that copying a repository mid-operation would lead to inconsistent data - [difficulties in backing up live git repositories](https://joeyh.name/blog/entry/difficulties_in_backing_up_live_git_repositories/). I can't find any information about if this was changed, but I imagine not.

Does the `gitea dump` command protect against this type of issue when it copies repositories, or do I need to make sure users are not doing anything? (~shutting down gitea service while backing up)

**Comment by wxiaoguang** [comment]
The answer is in code https://github.com/go-gitea/gitea/blob/main/cmd/dump.go

`gitea dump` just writes all the files under `repos` directory into the archiver, one by one. Shutting down gitea is the most safe way to do dump.

Personally I always use low-level methods to do backup & restore (eg: zfs snapshot), no stop time anymore.
