### ISSUE TITLE
manually merge PR by fast-forward crashes gitea

### ISSUE THREAD

**Issue by grissiom** [go-gitea/gitea#1964]
- Gitea version (or commit ref): 1.1.2
- Git version: 2.11
- Operating system: Windows
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:
Sorry that the log is on the working machine which could not access the Internet easily,

## Description

https://github.com/go-gitea/gitea/blob/v1.1.2/models/pull.go#L520 assume the `mergeCommit` is not empty. But if the PR is merged manually by fast-forward, `git rev-list --ancestry-path --merges ...` will give empty output. So `mergeCommit[:40]` will crash the program by index out of range error.

I hope I've provided enough information. If you need the full log etc., please tell me and I will try to get more.

**Comment by ethantkoenig** [comment]
The out-of-index error seems to have been fixed since v1.1.2 (#1420)

**Comment by grissiom** [comment]
That commit treat the empty `mergeCommit` as errors. So how do you deal with fast-forward "merge"?

**Comment by ethantkoenig** [comment]
This issue should be closed, it was fixed by #1989.

**Comment by lunny** [comment]
@grissiom please feel free to reopen it.

**Comment by grissiom** [comment]
Yes, I found it was fixed. Thanks for you all!
