### ISSUE TITLE
500 from "Too many open files" (pipes)

### ISSUE THREAD

**Issue by coomdev** [go-gitea/gitea#19658]
### Description

Regularly, the file descriptor table for the gitea process fills up with anonymous pipes, reaching soft limits resulting in 500 errors when opening a repo's page.

### Gitea Version

1.16.6

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/coomdev/acea5b993a347a6395f9afb92de2fc0e

### Git Version

2.36.0

### Operating System

Archlinux (kernel 5.17.5)

### How are you running Gitea?

Running from the default package manager install from pacman (Pacman v6.0.1), as a systemd service (250.5).

### Database

MySQL

**Comment by lunny** [comment]
Could you upgrade to v1.16.7 and try again?

**Comment by coomdev** [comment]
Ah yes, I forgot to resync my repos when checking if 1.16.7 was available.
I will reopen it this occurs again (this usually takes a few days)
