### ISSUE TITLE
project title can be named the same 

### ISSUE THREAD

**Issue by eeyrjmr** [go-gitea/gitea#19664]
### Description

when creating an issue project, there is nothing to restrict the name of the board and thus the same name can be used multiple times

https://try.gitea.io/eeyrjmr/test_issues/projects

### Gitea Version

1.17.0+dev-558-g3da9dafc6 

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

![2022-05-09_22-05-1652131090](https://user-images.githubusercontent.com/4564448/167500214-f7096a06-fae2-45ee-98d0-f709b8b0fd38.jpg)

### Git Version

N/A

### Operating System

N/A

### How are you running Gitea?

Try.gitea.com

**Comment by 6543** [comment]
this is a classic question: feature or bug? - we need to decide

**Comment by lunny** [comment]
It's not name, it's a title at least Gitea think so. So I don't think it's a bug.
