### ISSUE TITLE
Internal Server Error 500

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#1966]
- Gitea version (or commit ref): d3efca3
- Git version: 2.1.4
- Operating system: Debian Jessie 8.8 x64
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:
Not sure how to get this.

## Description
Folder is unavailable and throws an internal server error, however files within the folder can be accessed if appended manually in url. Only folder that is affected.
...

## Screenshots

![screenshot at 2017-06-13 19-30-53](https://user-images.githubusercontent.com/7034850/27109156-1159b8f2-506f-11e7-809b-c3a852a839d8.png)
![screenshot at 2017-06-13 19-23-12](https://user-images.githubusercontent.com/7034850/27109155-11598df0-506f-11e7-8bbc-c6c6c61ae127.png)

**Comment by lunny** [comment]
any detail on console or log?

**Comment by ghost** [comment]
> 2017/06/13 21:06:24 [...routers/repo/view.go:53 renderDirectory()] [E] GetCommitsInfo: object does not exist [id: , rel_path: .gitmodules]

That looks like the only error I can see.
Sorry, I forgot gitea had dedicated logs, and took me awhile to find them. I am new to this.

Edit: I realize the replication error is for try.gitea.io and I am self-hosting this. I will edit main post.

**Comment by cez81** [comment]
Any submodules in that directory?

**Comment by ghost** [comment]
Ah that's it.

There's not any submodule in that parent directory, but a subdirectory within it has a .git folder, and that's the only subdirectory that won't manually load by editing the url. I removed the .git folder in that directory and pushed a commit and the error occurs, though, it doesn't say it modified the folder with the new commit, and I can't access it to make sure it removed the .git folder.

**Comment by andreynering** [comment]
I think this may be related to https://github.com/go-gitea/gitea/issues/1933

**Comment by bkcsoft** [comment]
Is there anyway you can replicate this on try.gitea.io with a repo that you don't mind sharing? Otherwise it might be hard to debug :(

**Comment by ghost** [comment]
What I can do is clone my repo and omit the private parts, leaving the public code, and the submodule causing the error is in the public part to begin with. I'll post back when I have it setup with a link.

**Comment by ghost** [comment]
Here you go, with the same error:
https://try.gitea.io/notstevek/suptv-public
page with error:
https://try.gitea.io/notstevek/suptv-public/src/master/js/chat

everything in /js/chat/:
At.js-master
bootstrap
Caret.js-master
client-pedro.js
client.js
jquery.form
wdt-emoji-bundle
bgrins-spectrum-98454b5
bootstrap-filestyle
jquery-3.1.1     
Remodal-1.1.0

folder that has the .git folder:
https://try.gitea.io/notstevek/suptv-public/src/master/js/chat/wdt-emoji-bundle
