### ISSUE TITLE
Azure AD v2 OAUTH2 with Git

### ISSUE THREAD

**Issue by Rainson12** [go-gitea/gitea#19671]
### Description

When enabling azure ad OAUTH2, the user will be allowed to authenticate against the azure ad and login to the web ui. However when submitting code via git cli like using "git clone [URL]" the user will never be able to authenticate since the user is always prompted for username & password which seem to be authenticated against the gitea internal user directory but not the SSO. I would expect to be prompted with the azure ad authentication dialog which credentials are then used to authenticate against gitea.

### Gitea Version

1.16.6

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

git version 2.36.1.windows.1

### How are you running Gitea?

we are running gitea inside docker

### Database

PostgreSQL

**Comment by lafriks** [comment]
That is not technically possible as git client supports only username/password authentication flow. If Azure AD supports LDAP protocol that could theoretically be configured in gitea under authentication sources

**Comment by wxiaoguang** [comment]
@lafriks 

There are more similar issues:
* https://github.com/go-gitea/gitea/issues/19336
* https://github.com/go-gitea/gitea/issues/17350

**Comment by lafriks** [comment]
@wxiaoguang these are different issues, git client does not support oauth2 authorization workflow

**Comment by wxiaoguang** [comment]
Oh yeah, not exactly the same.

I was thinking about the problem that Gitaa's git auth only use internal database. This one has another problem that git client doesn't support OAuth2.
