### ISSUE TITLE
Emails are not sent from gitea

### ISSUE THREAD

**Issue by zuhairamahdi** [go-gitea/gitea#19686]
### Description

after upgrading to gitea 1.16.5 gitea stopped sending emails and we are getting the following log:

`StartTLS: tls: server selected unsupported protocol version 301`

### Gitea Version

1.16.5

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

in Windows with Windows SQL

### Database

MSSQL

**Comment by techknowlogick** [comment]
This is sadly due to golang dropping support for tls 1.1 and below. If you are able to set env vars you can set `GODEBUG=tls10default=1` (note, this will be removed with golang 1.19)
