### ISSUE TITLE
Can the repository name support UTF-8 names? i.e. Chinese

### ISSUE THREAD

**Issue by dxf1122** [go-gitea/gitea#19699]
Can the project name support Chinese?

Many projects are difficult to translate into English, and many people around us are not very good at English. I hope the project name can support Chinese or UTF-8

**Comment by dxf1122** [comment]
Can the project name support Chinese?



Many projects are difficult to translate into English, and many people around us are not very good at English. I hope the project name can support Chinese or UTF-8

**Comment by lunny** [comment]
I have to say there is some technical problem need to be resolved. First, the repository store struct. Now we use repository name as a directory name, a UTF-8 name may cause some problems on different OS.

If you cannot read English document, it's amazing you could work as a programmer nowadays. So I think it's not reasonable. And you can also use many translation sites to do that.

**Comment by wxiaoguang** [comment]
Duplicate: #13295, which was marked as `wontfix`

* https://github.com/go-gitea/gitea/issues/13295
