### ISSUE TITLE
Duplicate entry when high concurrency request to add a team member

### ISSUE THREAD

**Issue by zuzuviewer** [go-gitea/gitea#19697]
### Description

when a user is not team member,high concurrency request to add this user to the team,it will response 204 to one,and other resposne is Duplicate entry error.

### Gitea Version

1.16.7

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![lQLPDhtrTTeAfkHNAgTNB1awhzdcwrTBLMMCgHnmhIA9AA_1878_516](https://user-images.githubusercontent.com/19585711/168231360-08b3004d-ebb0-4850-81e0-8147d74f3d02.png)

### Git Version

1.8.3.1

### Operating System

centos7.8

### How are you running Gitea?

docker

### Database

MySQL

**Comment by lunny** [comment]
Fixed by #19702
