### ISSUE TITLE
Stop depending on magic numbers in database

### ISSUE THREAD

**Issue by bkcsoft** [go-gitea/gitea#1969]
Sparking from https://github.com/go-gitea/gitea/issues/1937

The reason we have `repository.num_issues` isn't to know how many issues there are, but to know what issue-number to assign next. It should _not_ be used in the UI to list number of issues 🙄

**Comment by uncled1023** [comment]
Is this still an issue?

**Comment by lafriks** [comment]
For count we should probably could use cache  like I changed it in commit count

**Comment by uncled1023** [comment]
In kind of a related note, is there a method to 'reset' the issue counts?  ie: num_issues

**Comment by bkcsoft** [comment]
@uncled1023 As far as I know, no. The only way is to open up the database and run a query. Do note that `count(...)` will break things, as `num_issues` is used to select the number for the next opened issue or pull-request 😒 (That also needs to be fixed 😉 )

**Comment by sapk** [comment]
I don't think this is still the case but I will have to re-check

**Comment by guillep2k** [comment]
> 
> 
> I don't think this is still the case but I will have to re-check

@sapk I can confirm it's not the case.

**Comment by guillep2k** [comment]
Here's the code used to assign the issue number (index) nowadays:

https://github.com/go-gitea/gitea/blob/cc2916dc5acea2c32372082986f8c2e2c43e55fe/models/issue.go#L901-L905

Not to say it can't be improved. 😄

**Comment by sapk** [comment]
Thanks to confirm that. I will close this issue so.
