### ISSUE TITLE
Internal Server Error while using `Content-Type=multipart/form-data; boundary=cats` on `/v1/user/keys`

### ISSUE THREAD

**Issue by ludovicianul** [go-gitea/gitea#19698]
### Description

While doing some fuzzing using https://github.com/Endava/cats I discovered an issue for the `/v1/user/keys"` endpoint. Doing a POST with `multipart/form-data; boundary=cats` `Content-Type` results in a 500, rather that something more meaningful.

You can reproduce the issue using (just replace $token with your own token):

`cats replay Test1246.json`

[Test1246.json.zip](https://github.com/go-gitea/gitea/files/8686686/Test1246.json.zip)

### Gitea Version

1.17.0+dev-573-ge45738e3c

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

[Online](https://try.gitea.io)https://try.gitea.io/

**Comment by zeripath** [comment]
Would it be possible to see some logs for this?

**Comment by wxiaoguang** [comment]
It could be reproduced by:

```
curl -v -XPOST -H "Authorization: token $token" -H "Content-Type: multipart/form-data; boundary=cats" "https://try.gitea.io/api/v1/user/keys"
```

**Comment by wxiaoguang** [comment]
panic here:

![image](https://user-images.githubusercontent.com/2114189/194555519-82494aac-6b48-40fa-bec4-155e052f5830.png)

**Comment by zeripath** [comment]
https://gitea.com/go-chi/binding/pulls/13
