### ISSUE TITLE
Authorized Push

### ISSUE THREAD

**Issue by SoniEx2** [go-gitea/gitea#19691]
### Feature Description

When attempting to push to a repo over SSH, if the key is unknown and Authorized Push is enabled, the repo owner is asked to allow the push.

Authorized Push is enabled by opening the repo on a logged-in device (in the web interface), and navigating to Authorized Push. Push requests then show up in the Authorized Push screen, and the public key is displayed to the user, who may then allow or reject the push. If the Authorized Push screen is closed, any pending push requests are automatically rejected.

**Comment by techknowlogick** [comment]
Closing as key is checked by opensshd prior to knowing anything about repo, and so would mean all keys would need to be accepted by opensshd, and then checked by gitea.

**Comment by SoniEx2** [comment]
this can be done with a pam module.
