### ISSUE TITLE
 Wrong suggested changes url in dashboard

### ISSUE THREAD

**Issue by NepPure** [go-gitea/gitea#19696]
### Description

Can be reproduce in https://try.gitea.io/

See Screenshot below. Language must select Chinese, no problem with English version.

### Gitea Version

1.17.0+dev-573-ge45738e3c

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

<img width="1727" alt="image" src="https://user-images.githubusercontent.com/12379907/168207736-4249624b-6878-4ba6-b363-640711be4cec.png">

### How are you running Gitea?

no need.

**Comment by NepPure** [comment]
https://crowdin.com/translate/gitea/68/enus-zhcn?filter=basic&value=0#q=reject_pull_request

**Comment by wxiaoguang** [comment]
Translation has been merged by:
* https://github.com/go-gitea/gitea/commit/6d54799bbcce3ccaa27e3660b4a47f1bee039601

Thank you for your contribution ~~
