### ISSUE TITLE
Better error handling for adding Auth Sources

### ISSUE THREAD

**Issue by ibigbug** [go-gitea/gitea#19705]
### Description

this line could get an internal error: https://github.com/go-gitea/gitea/blob/54e9ee37a7a301dbe74d46fd3c87712e6120e9bf/routers/web/admin/auths.go#L295

if for example, adding a new OpenID config and the openid auto discovery URL returns unexpected response.

Maybe inspect error and improve the UI form error render to avoid confusion.

### Screenshots

I already fixed the URL and didn't capture a screenshot but it's basically the 500 error page.

### Gitea Version

1.16.7

### Can you reproduce the bug on the Gitea demo site?

Yes

### Browser Version

Latest Chrome.

**Comment by zeripath** [comment]
It really is much much much much better to give us logs.

**Comment by ibigbug** [comment]
sorry I lost the logs inside the container, thought it was a general error checking. but anyways it's now working, thanks!

**Comment by lunny** [comment]
Closed as outdated.
