### ISSUE TITLE
Email test timeout

### ISSUE THREAD

**Issue by f0x52** [go-gitea/gitea#19714]
### Description

With a (possibly) wrong email config, using the SMTP mailer test form results in a (gateway) timeout. With loglevel Debug, there's no further info about the (failed) mailing attempt at all, other than `Started POST /admin/config/test_mail for `

### Gitea Version

1.16.7

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

NixOS Module

### Database

PostgreSQL

**Comment by owenfiscus** [comment]
I have the same issue running in Docker.

**Comment by aphex3k** [comment]
+1

**Comment by lolcatw** [comment]
Got the same issue here using sendmail:

```
[mailer]
ENABLED = true
FROM = no-reply@lolcat.ca
PROTOCOL = sendmail
SENDMAIL_PATH = /usr/sbin/sendmail
SENDMAIL_ARGS = "--" ; most "sendmail" programs take options, "--" will prevent an email address being interpreted as an option.
```

**Comment by lunny** [comment]
Looks like @f0x52 is SMTP but yours is sendmail.

**Comment by lolcatw** [comment]
I used Luke Smith's emailwiz script, and I believe that my AAAA ipv6 records did not propagate when I did the setup of my mail server which lead to deliverability problems to local accounts somehow. I reinstalled everything and the issue sorted itself out. Thanks.

**Comment by lunny** [comment]
I think this could be closed and please feel free to reopen if there is further information.
