### ISSUE TITLE
Gitea still doxes unwilling users e-mail addresses [Not a question / bug / potentially violating GDPR Article 5]

### ISSUE THREAD

**Issue by ReeceSX** [go-gitea/gitea#19716]
Closely resembles https://github.com/go-gitea/gitea/issues/4502 fixed in 1.6

The endpoint `/api/v1/users` contains an email json field that doesn't respect user authentication. Any user with a standard web browser binary and incognito mode is theoretically capable of doxing any user on the gitea. Worse still, users synchronizing against an LDAP server backed by, say, an organization's entire user directory, risks exposing non-git internal and external emails of staff and external agents who may have never used the service. This could also be a GDPR liability. 

Confirmed in: {"version":"1.16.1"}

**Comment by lunny** [comment]
```ini
[service]
DEFAULT_KEEP_EMAIL_PRIVATE=true
```

**Comment by ReeceSX** [comment]
No, it's not a question nor does this solve the problem. There's a difference between doxing git emails and doxing registered default emails of non-site users by default.

**Comment by wxiaoguang** [comment]
@ReeceSX please clarify your problem first.

Some background for you:

Exposing user's email address or not, is controlled by users themselves.

For example, now I set my "Hide Email Address" on my account, I think you can not get my real E-mail address by the API:

https://try.gitea.io/api/v1/users/wxiaoguang  (it's a fake one)

If you set DEFAULT_KEEP_EMAIL_PRIVATE, then your newly created account will be set "Hide Email Address" automatically, then their emails will not be exposed.

So, I would change the title back to a concise one to reduce misleading.

If you are sure there is something incorrect, please provide detailed steps (and reproducible demo on try.gitea.io if possible). Only after you teach others to reproduce your problem, then others have a chance to confirm whether is a bug.

**Comment by Gusted** [comment]
> The endpoint `/api/v1/users` contains an email json field that doesn't respect user authentication.

This is a feature request. Gitea never claimed to do this. 

> Any user with a standard web browser binary and incognito mode is theoretically capable of doxing any user on the gitea.

Why is this specific use-case used? I also could be a logged in user, or simply using the api or any other way of requesting such infromation.

> Worse still, users synchronizing against an LDAP server backed by, say, an organization's entire user directory, risks exposing non-git internal and external emails of staff and external agents who may have never used the service.

Could you please state the relevance of this to the other part of the issue? If this is a issue it should be a issue on it's own.

> This could also be a GDPR liability.

Users who host a gitea instance are responsible to ensure that it's complying with their local law. Gitea can only assist with this, but not our job to enforce nor our responsibility.

**Comment by ReeceSX** [comment]
> @ReeceSX please clarify your problem first.
> 
> Some background for you:
> 
> Exposing user's email address or not, is controlled by users themselves.
> 
> For example, now I set my "Hide Email Address" on my account, I think you can not get my real E-mail address by the API:
> 
> https://try.gitea.io/api/v1/users/wxiaoguang (it's a fake one)
> 
> If you set DEFAULT_KEEP_EMAIL_PRIVATE, then your newly created account will be set "Hide Email Address" automatically, then their emails will not be exposed.
> 
> So, I would change the title back to a concise one to reduce misleading.
> 
> If you are sure there is something incorrect, please provide detailed steps (and reproducible demo on try.gitea.io if possible). Only after you teach others to reproduce your problem, then others have a chance to confirm whether is a bug.

RTFM -> https://docs.gitea.io/en-us/authentication/#ldap-lightweight-directory-access-protocol



> Could you please state the relevance of this to the other part of the issue? If this is a issue it should be a issue on it's own.

Not only are unsuspecting users doxing their __registered email addresses__ by default, you are also doxing everyone within an LDAP organization.

**Comment by 6543** [comment]
please dont keep this issue overloaded!!!
1. `Gitea can only assist with this, but not our job to enforce nor our responsibility.` - so please dont argue with some law
2. if a user did hit "keep email private" this is a bug and should be solved, however your issue is just crowded with unrelated suff I cant read where exactly it's leaked - sorry!!!

**Comment by ReeceSX** [comment]
> 1. so please dont argue with some law

Try harder. I added this comment to the title after the issue was immediately dismissed with a worthless config suggestion. Otherwise, this was nothing more than a three-letter sentence.  It really takes some rationalizing to believe im trying to hold gitea legally accountable. 


> 2\. if a user did hit **"keep email private"** this **is a bug** and should be solved, **however** your issue is just crowded with unrelated suff I cant read where exactly it's leaked - sorry!!!

....including unregistered users?

**Comment by wxiaoguang** [comment]
I think you should be polite first instead of saying something ..... `RTFM`  .... the `F`, how does it help about the problem? Most maintainers are more familiar with the Gitea code base.

And I can not understand `you are also doxing everyone within an LDAP organization.` , you could use docker-compose or something similar to provide a demo to show how  doxing  everyone within an LDAP organization. I really have difficulty to understand.

You are more than welcome to provide a real sample (say, reproducible, it is important) about the problem if the problem really exists.

**Comment by 6543** [comment]
> I added this comment to the title after the issue was immediately dismissed with a worthless config suggestion. 

1. well then you might have not described the issue well enouth to got our attention - we have 1.6k open issues - and if it looks like a nowbrainer aka question, we just answer and move forward

**YOU WASTE OUR TIME** - this sounds **harsch** BUT:
 - we are mostly voluntary
 - if you like to chat we have other channels
 - your formulation sounds harsh to us

**Comment by 6543** [comment]
tld: pay us or help us pro-active and nicle not just shout at us
