### ISSUE TITLE
Issues are not mirrored

### ISSUE THREAD

**Issue by WaromiV** [go-gitea/gitea#19710]
### Description

migrating repository to try.gitea.io:
![image](https://user-images.githubusercontent.com/59875489/168468482-13d01ddd-135e-4484-88e4-22a3244a0613.png)
original repository has issues, but new one doesn't:
https://try.gitea.io/HIMINTOMA/github-maven-example/issues
same situation with self-hosted

### Gitea Version

gitea-1.16.7-linux-amd64

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

ubuntu, running through ./gitea https://dl.gitea.io/gitea/1.16.7/gitea-1.16.7-linux-amd64

### Database

SQLite

**Comment by lunny** [comment]
The feature is not implemented.
