### ISSUE TITLE
Can't view PR file comments

### ISSUE THREAD

**Issue by stuzer05** [go-gitea/gitea#19734]
### Description

Other users can't see my PR comments (and me theirs). I even added a user as collaborator. I expect anyone t sse anyone's comments.

https://try.gitea.io/stuzer05/test-preview/pulls/1/files

### Gitea Version

1.17.0

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

My comment
![image](https://user-images.githubusercontent.com/23124682/168756604-8bc4a078-10b4-4246-89cd-5919ebe64f57.png)

When reviewer sees (no comment):
![image](https://user-images.githubusercontent.com/23124682/168756720-d2d9ebc3-8932-48d3-bc1c-4379a6a6db3b.png)

Second user is collaborator:
![image](https://user-images.githubusercontent.com/23124682/168756808-bdf77c51-207a-440d-8c6b-d401f54e59ae.png)

### How are you running Gitea?

Docker

**Comment by wxiaoguang** [comment]
![image](https://user-images.githubusercontent.com/2114189/168764290-172744e9-4132-4f2f-bf28-a81a1a1dfde1.png)


They are pending, you should submit a final review
