### ISSUE TITLE
Some files are recognized as SVG incorrectly, make the diff UI unable to work.

### ISSUE THREAD

**Issue by stuzer05** [go-gitea/gitea#19733]
### Description

When certain conditions are met gitea can't display the `blade.php` file diff when viewing the commit. It only works when I click "View source button". Second link is taken from network, it is causing the crash.

https://try.gitea.io/stuzer05/test-preview/commit/f97b3784f8c8efc222128f6dffd4e5abb5fda462
https://try.gitea.io/stuzer05/test-preview/raw/commit/e2f752e123151fea55959571d56d57462025f0f6/test.blade.php

![image](https://user-images.githubusercontent.com/23124682/168754789-1967dae8-908e-488c-86cd-dbb63ce5f867.png)

### Gitea Version

1.17.0

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

Docker

**Comment by wxiaoguang** [comment]
The file was recognized as SVG incorrectly.

`https://try.gitea.io/stuzer05/test-preview/raw/commit/e2f752e123151fea55959571d56d57462025f0f6/test.blade.php`

Response header:

`content-type | image/svg+xml`

**Comment by lunny** [comment]
By the extension name, it's not a svg file.
