### ISSUE TITLE
[API] incorrect permission values of repos if using notifications endpoints

### ISSUE THREAD

**Issue by qwerty287** [go-gitea/gitea#19759]
### Description

Requesting a notification endpoint returns wrong values of the permission object. 
It always looks like:
```json
{
    "admin": false,
    "push": false,
    "pull": true
}
```
even if I own the repo where it should be
```json
{
    "admin": true,
    "push": true,
    "pull": true
}
```

### Gitea Version

1.17.0 (also on try.gitea.io)

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

build from source, from CLI

**Comment by zeripath** [comment]
I think reporting the permission here is a mistake and we should not report it.
