### ISSUE TITLE
Gitea shows extra line at the end of file, again

### ISSUE THREAD

**Issue by jinm** [go-gitea/gitea#19766]
### Description

The web UI of Gitea 1.15.6 always shows an extra line at the end of a file. This was previously reported in https://github.com/go-gitea/gitea/issues/4050.

This can be reproduced on gitea demo site. I randomly picked a file here: https://try.gitea.io/asahiocean/leetcode/src/branch/main/.gitignore

### Gitea Version

1.15.6

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

![image](https://user-images.githubusercontent.com/4997609/169554363-f2e7bd6a-396b-47ed-9d2a-1039817a62cd.png)
![image](https://user-images.githubusercontent.com/4997609/169554409-0cfc4eef-284d-4d14-a9d7-dc44bfdf6123.png)

### How are you running Gitea?

Self-hosted

### Database

PostgreSQL

**Comment by silverwind** [comment]
See discussion in https://github.com/go-gitea/gitea/pull/18076

**Comment by jinm** [comment]
Thanks for sharing the information. I will close this issue and watch the other one.
