### ISSUE TITLE
404 on an organization's repo

### ISSUE THREAD

**Issue by mxmehl** [go-gitea/gitea#1977]
- Gitea version (or commit ref): 033aaf4 (latest master)
- Git version: 2.1.4
- Operating system: Debian 8
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL): https://try.gitea.io/test123123123/test (not my org/repo)
  - [ ] No
  - [ ] Not relevant
- Log gist: https://gist.github.com/mxmehl/d73cff00f556f034bb87d95ef9e8ea6c

## Description

As a normal user, I receive an 404 every time I open an organization's repository. The repository is public, and when logged out I can visit it without any errors.

Log is attached. It seems to be an auth issue to me at some point. Thanks for looking into it!

**Comment by mxmehl** [comment]
Additional information: On the server the error occurs, it doesn't matter whether this normal user uses local authentication or LDAP (both are enabled). It also doesn't matter whether I just browse the repo's root or e.g. its issues.

When browsing /org/repo/src/master/README.md, I see a different error in the log:

```
2017/06/16 12:53:46 [...ules/context/repo.go:529 func1()] [E] CheckUnit: You are not allowed to visit this repository unit: 1
```

As admin, I can always see the repositories.

**Comment by lunny** [comment]
@mxmehl please confirm #1984 fix this.
