### ISSUE TITLE
branch filtering inconsistency

### ISSUE THREAD

**Issue by acopxl** [go-gitea/gitea#19778]
### Description

Branch filtering works differently on different screens. It seems to be working fine on the "Code" page. On "New Pull Request" show branches that seem not to match the string we enter

### Screenshots

![Screenshot from 2022-05-21 21-26-56](https://user-images.githubusercontent.com/16439545/169666625-c2d76bf8-cc66-491d-9e61-9473748e7b25.png)
![Screenshot from 2022-05-21 21-27-11](https://user-images.githubusercontent.com/16439545/169666627-2cb2bbb1-b646-476f-be87-2417dcb1503d.png)

### Gitea Version

1.16.7

### Can you reproduce the bug on the Gitea demo site?

Yes

### Browser Version

Chrome

**Comment by zeripath** [comment]
Yup exact would stop this fuzzy searching behaviour

**Comment by lunny** [comment]
> It's caused by Dropdown's full-search behavior.
> 
> [fomantic/Fomantic-UI#1737](https://github.com/fomantic/Fomantic-UI/discussions/1737)
> 
> https://github.com/go-gitea/gitea/blob/e31c6166ee92c378c84570b2959f2fdb040d438a/web_src/js/features/repo-common.js#L110-L115
> 
> Maybe it can be fixed by the suggestion of the discussion : `fullTextSearch: 'exact'`

Do you have plan to send a PR?

**Comment by wxiaoguang** [comment]
Use exact search instead of fuzzy search for branch filter dropdown #19885
