### ISSUE TITLE
add the intermediate certificates

### ISSUE THREAD

**Issue by dvgoyeneche** [go-gitea/gitea#19789]
Problem renewing ssl certificate (sectigo certificate)

**Comment by dvgoyeneche** [comment]
after renewing the certificate I get this error:
SSL certificate problem: unable to get local issuer 

A year ago I solved it by adding the intermediate certificates but I dont remember the steps

**Comment by Gusted** [comment]
Please use the bug report template, as we need all information in order to actually have an actionable issue. 

https://github.com/go-gitea/gitea/issues/new?assignees=&labels=kind%2Fbug&template=bug-report.yaml
