### ISSUE TITLE
Release/Tag comparing, not all tags listed

### ISSUE THREAD

**Issue by tautf** [go-gitea/gitea#19795]
### Description

When comparing releases, it's only possible to select tags as comparison partner, which have a release behind.
Tags that where created without release are not visible in the comparison list.

Would be good to be able to compare all tags with each other without having them to be a release. Or give the comparing feature in tags page as well.

Regards.

### Gitea Version

1.16.5

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

![Bildschirmfoto 2022-05-24 um 14 57 48 PM](https://user-images.githubusercontent.com/18403881/170040656-3a188b3f-f1e2-47fc-b5e4-72f1e74af73e.png)
![Bildschirmfoto 2022-05-24 um 14 57 54 PM](https://user-images.githubusercontent.com/18403881/170040662-c985b110-a1d2-43fd-a96a-5470c2c98227.png)
.

### Git Version

none, integrated

### Operating System

Windows Server 2019

### How are you running Gitea?

Basic executable from github releases. gogit amd64

### Database

PostgreSQL

**Comment by TautFlorian** [comment]
Seems to be resolved?
