### ISSUE TITLE
can not read the full title of issues in dependency list of an issue

### ISSUE THREAD

**Issue by flobee** [go-gitea/gitea#19806]
### Description

See the list on dependencys/ blocks of issues https://try.gitea.io/company/testsB/issues/1

A fix: Each link need a title attribute containing the `<a ..title="MISSING" ...>` node value. thats all. Hover over the link displays the complete title. its hidden by css 

### Screenshots

![2022-05-25](https://user-images.githubusercontent.com/1349520/170351642-5c40e4ce-b402-4779-8fc2-cb4a2c6900be.png)

### Gitea Version

1.6.8

### Can you reproduce the bug on the Gitea demo site?

Yes

### Browser Version

FF 91.9.1esr (64-Bit)

**Comment by zeripath** [comment]
I have a feeling that this would solve the issue:

```patch
diff --git a/templates/repo/issue/view_content/sidebar.tmpl b/templates/repo/issue/view_content/sidebar.tmpl
index ffc46bfed..309b9c890 100644
--- a/templates/repo/issue/view_content/sidebar.tmpl
+++ b/templates/repo/issue/view_content/sidebar.tmpl
@@ -468,7 +468,7 @@
 						{{range .BlockingDependencies}}
 							<div class="item dependency{{if .Issue.IsClosed}} is-closed{{end}} df ac sb">
 								<div class="item-left df jc fc f1">
-									<a class="title" href="{{.Issue.Link}}">
+									<a class="title" href="{{.Issue.Link}}" title="#{{.Issue.Index}} {{.Issue.Title | RenderEmoji}}">
 										#{{.Issue.Index}} {{.Issue.Title | RenderEmoji}}
 									</a>
 									<div class="text small">
```

**Comment by flobee** [comment]
lovly :+1:  at try.gitea.io
