### ISSUE TITLE
Status code 404 when logging out and the current page was not public

### ISSUE THREAD

**Issue by indigoxela** [go-gitea/gitea#19804]
### Description

First of all, I really :heart: Gitea, many thanks for this cool software.

One thing's a bit odd.

Steps to reproduce:

1. Log in
2. Go to a non-public page you have access to, for instance in a limited organization, or your own non-public profile page
3. Log out via the dropdown user-menu (top right), with "Sign out"

Result:
404 The page you are trying to reach either does not exist or you are not authorized to view it.

That's not really bad and the text explains what happens, but wouldn't it be cleaner to redirect to the home page in that case?
Some other pages seem to redirect to the login form after logging out, for instance the issues overview page.

Maybe that's actually some fancy feature, and I just don't get the logic behind it, but it seems inconsistent. :wink:

### Gitea Version

1.16.8

### Can you reproduce the bug on the Gitea demo site?

Yes

### Git Version

2.30.2

### Operating System

Debian bullseye

### How are you running Gitea?

- Installed via binary file
- Start/stop via systemd (gitea.service)
- Apache as proxy
- DEFAULT_USER_VISIBILITY = private
- DEFAULT_ORG_VISIBILITY = limited

### Database

MySQL

**Comment by lunny** [comment]
Maybe sign out should not redirect to any page but just go to default page.

**Comment by indigoxela** [comment]
I did a quick check with REQUIRE_SIGNIN_VIEW set to true. In that case logging out redirects to the login form (consistently).

**Comment by lunny** [comment]
I think this has been resolved on main branch.
