### ISSUE TITLE
Unable to find git note corresponding to the commit errors in log

### ISSUE THREAD

**Issue by pboguslawski** [go-gitea/gitea#19819]
### Description

Noticed errors like

```
2022/05/27 15:55:56 ...git/notes_nogogit.go:50:GetNote() [E] Unable to find git note corresponding to the commit "***". Error: object does not exist [id: , rel_path: 58]
```

in gitea 1.16.3 (built from sources) log.

Fix from similar issue https://github.com/go-gitea/gitea/issues/18616 is already applied in 1.16.3.

### Gitea Version

1.16.3

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

Build from sources.

### Database

MySQL

**Comment by lunny** [comment]
So you mean #18616 has been fixed?

**Comment by pboguslawski** [comment]
https://github.com/go-gitea/gitea/blame/v1.16.3/modules/git/notes_nogogit.go#L24

**Comment by zeripath** [comment]
This is just a spurious logging line and can be safely ignored. #19884 will finally stop it.
