### ISSUE TITLE
Feature request: public wiki on private repository

### ISSUE THREAD

**Issue by davydov-vyacheslav** [go-gitea/gitea#1982]
Hi,

I have private repository with a wiki. 
I'd like to allow anonymous/unauthorized for project users to access wiki pages. As the project is private, they can't do that for now.

BTW, yes, I know that the workaround is to set external wiki url, but this is not acceptable for me

P.S.  Gitea Version: 1.1.0

Thanks,
Slava

**Comment by lunny** [comment]
see #639
