### ISSUE TITLE
I think some javascript issue?

### ISSUE THREAD

**Issue by Zoe8338** [go-gitea/gitea#19823]
### Description

Uncaught SyntaxError: Invalid or unexpected token  index.js:6
I get this error in the console. I found it because neither the heatmap loads nor things like the "Remember me on this device" box or the user menu on the top right of the site shows.

### Gitea Version

1.16.8

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

There is nothing on the log folder.

### Screenshots

![image](https://user-images.githubusercontent.com/76208326/170821641-a255270d-3623-47c8-a9ed-261ec42d8e9c.png)

### Operating System

Ubuntu 20.04

### How are you running Gitea?

Docker

### Database

MySQL

**Comment by delvh** [comment]
Can't reproduce it on https://try.gitea.io.
I guess you have some sort of cache or build issues, or something similar.
It does not appear to be a Gitea issue, however.
With the amount of information you gave, I can't say anything else.
