### ISSUE TITLE
Editing file on a branch via web UI causes "PR broken due to missing fork information"

### ISSUE THREAD

**Issue by stu1811** [go-gitea/gitea#19847]
### Description

 If I a edit a file from the gitea website, create a PR, and then make another edit to the same file on the branch, I get "This pull request is broken due to missing fork information." I reproduced it on the demo site. https://try.gitea.io/developers/foobar/pulls/6

### Gitea Version

1.16.8

### Can you reproduce the bug on the Gitea demo site?

Yes

### Git Version

2.24.1

### Operating System

RHEL 7

### How are you running Gitea?

Download the amd64 linux binary from the releases page and run via systemd

### Database

MySQL

**Comment by zeripath** [comment]
The bug on try was due to hooks not running from a issue with docker versions and alpine 3.14+. 

Please try again.

**Comment by zeripath** [comment]
It would be helpful to check https://<gitea>/<owner>/<reponame>/graph .

Look at the branch that has is the head of the PR and check its past for where the `#PR` label is. If it is not concurrent with the top of the PR then your hooks are not running properly.

That could be because your gitea repositories are not mounted on an executable drive, it could be some permissions thing or it could even be that they're not communicating with Gitea properly.

**Comment by wxiaoguang** [comment]
Copy some information here:

https://try.gitea.io/developers/foobar/pulls/6

`This pull request is broken due to missing fork information. `

The graph:

![image](https://user-images.githubusercontent.com/2114189/194461308-d1d3b506-f97d-4f50-a79e-d3f6bd288987.png)

**Comment by wxiaoguang** [comment]
@stu1811

I tried some operations on try.gitea.io, can not reproduce your problem.

* Test 1: edit README on main -> create a new branch patch-xx -> create a PR from branch patch-xx -> edit README on branch patch-xx -> the PR still works well.

* Test 2: based on test1, edit edit README on main again -> commit on main -> the PR from branch patch-xx still works well.


Please help to provide reproducible steps.

**Comment by wxiaoguang** [comment]
Maybe it's related to 
* https://github.com/go-gitea/gitea/issues/18802#issuecomment-1290792260

Since this issue has been inactive for more than 2 weeks, I will close it (as dup), feel free to re-open it with reproducible steps.

**Comment by zeripath** [comment]
> Copy some information here:
> 
> https://try.gitea.io/developers/foobar/pulls/6
> 
> `This pull request is broken due to missing fork information. `

As we can see there the `#6` head is behind the branch head... that explains the "pull request is broken" thing but it's weird and I don't quite understand how that has happened.

**Comment by zeripath** [comment]
If this was only reproducible on try.gitea.io only then the issue was simply that the hooks weren't working on try for a while due to the docker bug and this bug is yet another duplicate of that.

**Comment by zeripath** [comment]
Another duplicate of: https://github.com/go-gitea/gitea/issues/16428, https://github.com/go-gitea/gitea/pull/16451, https://github.com/go-gitea/gitea/pull/16170, https://github.com/go-gitea/gitea/issues/16464, https://github.com/go-gitea/gitea/issues/16484

See https://github.com/go-gitea/gitea/pull/18050

We put a huge warning in to tell people to upgrade their dockers for 1.17.
