### ISSUE TITLE
Push to a branch under PR makes the PR broken

### ISSUE THREAD

**Issue by FrankCui-FengqiaoCui** [go-gitea/gitea#19848]
### Description

1. create a repo, update some readme
2. created a branch, modify the readme and push to a branch
3. created PR from the branch to main
4. modify readme again on the branch, then push to main
5. the PR shows  This pull request is broken due to missing fork information.

### Gitea Version

1.17.0+dev-633-gfdc784dbf

### Can you reproduce the bug on the Gitea demo site?

Yes

### Git Version

git version 2.36.1.windows.1

### Operating System

windows

### How are you running Gitea?

explored on try.gitea.io

**Comment by wxiaoguang** [comment]
It sounds like the same problem of #19847 ?
* #19847

**Comment by FrankCui-FengqiaoCui** [comment]
> It sounds like the same problem of #19847 ?
> 
> * [Append to PR Through Gitea UI #19847](https://github.com/go-gitea/gitea/issues/19847)

Yes. I think it's the same problem.

**Comment by zeripath** [comment]
@FrankCui-FengqiaoCui what version of docker are you running?

See #18050

---

Upgrade Alpine from 3.13 to 3.15

## :warning: BREAKING :warning: 

Users with docker version < 20.10.6 have to upgrade their docker.

See: https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.14.0 & https://about.gitlab.com/blog/2021/08/26/its-time-to-upgrade-docker-engine/

The upgrade to alpine 3.14+ causes everyone using gitea with docker less than version 20.10.6 to break. (https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.14.0)

We upgraded to alpine 3.14 and had multiple bug reports like:

 #16428, #16451, #16170, #16464, #16484
