### ISSUE TITLE
Repo Migraiton (mirror) fails with wiki

### ISSUE THREAD

**Issue by Jeansen** [go-gitea/gitea#19844]
### Description

Cloning https://github.com/lensapp/lens.git fails (as mirror) when also ticking the checkbox for 'wiki'. This repo has no wiki.

I'd expect it to not fail, but either issue a warning or ignore the option.

Here's the relevant log line:

```
2022/05/30 22:00:55 ...ervices/task/task.go:56:handle() [E] Run task failed: unable to write commit-graph for '/media/ocdata/gitea/marcel/lens.wiki.git' : chdir /media/ocdata/gitea/marcel/lens.wiki.git: no such file or directory
```

If I disable the checkbox on the migration page, it works fine.

### Gitea Version

1.16

### Can you reproduce the bug on the Gitea demo site?

Yes

### Git Version

2.30.2

### Operating System

Debian 11

### How are you running Gitea?

Binary distribution, on a rapsberry pi 4, via systemd service.

### Database

PostgreSQL

**Comment by wxiaoguang** [comment]
Is it similar as  #19481 ?
* #19481

**Comment by Jeansen** [comment]
@wxiaoguang Yes, seems like a similar issue.

**Comment by zeripath** [comment]
I cannot reproduce on main.

**Comment by Jeansen** [comment]
@zeripath Oh great, thanks. Will this be in the next 1.16.x version?

**Comment by zeripath** [comment]
yes

**Comment by zeripath** [comment]
It was backported to 1.16.7 by https://github.com/go-gitea/gitea/pull/19568
