### ISSUE TITLE
Support plain CGI

### ISSUE THREAD

**Issue by cweagans** [go-gitea/gitea#19854]
### Feature Description

It would be awesome if Gitea supported plain CGI (as opposed to fcgi). It's certainly not the _best_ way to run Gitea, but it would allow users of cheap, shared hosting services (e.g. Dreamhost) to easily run Gitea.

There are some potential complications with doing this:

* There is never a persistent Gitea process, so things like e.g. queue processing, session storage, etc. would need a way to run via a CLI (so that a user can configure them in a crontab or something outside of Gitea)
* Things like database migration on startup would probably need to be automatically disabled in CGI mode (since a separate instance of Gitea would be started on _every_ HTTP request). In general, CGI is pretty sensitive to startup time.
* Probably sevearl other things, but I'm not familiar enough with the Gitea codebase to know about them offhand.

**Comment by kousu** [comment]
Interesting, but would Dreamhost allow this? Cheap hosting services usually have TOSes that are pretty strict about the kinds of code they allow to run. They optimize their servers for PHP; they probably have `noexec` marked on the client-accessible mountpoints.

**Comment by cweagans** [comment]
I'm reasonably sure that dreamhost explicitly allows any kind of CGI application. They don't like long-running processes very much though.

**Comment by cweagans** [comment]
Also: it's interesting to think about CGI support in that it also gets Gitea closer to running on something like Lambda. I know the protocol isn't even close, but the constraints are similar (long running process isn't necessarily a given, separating queue processing into separate explicit actions is helpful, etc)

**Comment by wxiaoguang** [comment]
That's nearly impossible. The startup is slow, you won't benefit anything from CGI mode, CGI won't help about "cheap" hosting services.

**Comment by lafriks** [comment]
As CGI requires starting process for each request and gitea requires running all the time in background this would make it impractical to implement
