### ISSUE TITLE
git error: gnutls_handshake() failed on push

### ISSUE THREAD

**Issue by dvgoyeneche** [go-gitea/gitea#19880]
### Gitea Version

1.16.8

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

on premise gitea server, when cloning a repository, error
:gnutls_handshake() failed: Error 
gnutls_handshake() failed on push

### Database

MySQL

**Comment by zeripath** [comment]
I suspect this is relating to your local git client and is not related to Gitea.

https://stackoverflow.com/questions/15665444/git-error-gnutls-handshake-failed-on-push
