### ISSUE TITLE
Migrate frontend framework from Vue2 to Vue3

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#19902]
### Feature Description

As vue3 becomes more and more fluent, we have to consider to migrate current Vue2 to Vue3 to avoid mantaince problem.
I think there are many works to do to address that.

And this will also resolve below issues:

- [x] #10669

**Comment by silverwind** [comment]
Can vue3 import vue2-based dependencies or do they all have to upgrade? https://github.com/lafriks/vue-bar-graph/issues/9 is related.

**Comment by Ryuno-Ki** [comment]
There is a migration build that runs Vue3 but emulates the API of Vue2 (up to a certain degree).
It comes with a performance penalty, though.

**Comment by lafriks** [comment]
> Can vue3 import vue2-based dependencies or do they all have to upgrade? [lafriks/vue-bar-graph#9](https://github.com/lafriks/vue-bar-graph/issues/9) is related.

I have released vue-bar-graph vue3 version

**Comment by wxiaoguang** [comment]
@lafriks 

The vue3-bar-graph's layout is different from the vue2 version.

By default, it looks like this:

![image](https://user-images.githubusercontent.com/2114189/193418028-f2f2c183-d15b-478d-9cc6-06239aacb793.png)


On try.gitea.io, I applied a simple style patch:

![image](https://user-images.githubusercontent.com/2114189/193418056-66333cbb-cc88-452d-8cb1-3fe8b98b0c78.png)


Before, it looks like this (Vue2 version):

![image](https://user-images.githubusercontent.com/2114189/193418082-c054595f-9d50-4342-b714-f0c32eea3632.png)


Will you update the vue-bar-graph styles? Or the style will be justed patched on Gitea side?
