### ISSUE TITLE
gitea.web snap service unable to access /etc/gitconfig

### ISSUE THREAD

**Issue by DrPyser** [go-gitea/gitea#19911]
### Description

This is the same as #12620 . The issue was closed by author since removing /etc/gitconfig "solves" the issue. However, it seems to me that shouldn't be required. gitea should be able to work with existing system git config.

From some quick research, a solution path is to update the snap configuration to request access to the file using system-files interface. https://forum.snapcraft.io/t/the-system-files-interface/9358

### Gitea Version

Gitea version 1.16.8 built with GNU Make 4.1, go1.18.2 : bindata, sqlite, sqlite_unlock_notify, pam, cert

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/DrPyser/5f27106f7e5ddea27cdabdf9a50fbfb8

### Git Version

2.25.1

### Operating System

Ubuntu 20.04

### How are you running Gitea?

Installed via snapd. Running gitea web service using snapd service management: `snap start gitea`.

### Database

SQLite

**Comment by wxiaoguang** [comment]
I have a feeling that it could be fixed by:
* https://github.com/go-gitea/gitea/pull/19732
