### ISSUE TITLE
Gitea does not work to run otherwise than from the root

### ISSUE THREAD

**Issue by DimS1872** [go-gitea/gitea#19915]
### Description

At the first launch of Gitea, the launch from the git user was configured. But after a reboot, Gitea does not start. The startup log and the beginning of the app.ini file are shown in the screenshots.

### Gitea Version

Gitea version 1.16.8 built with GNU Make 4.1, go1.18.2 : bindata, sqlite, sqlite_unlock_notify, pam, cert

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

Ubuntu 20.04.4 LTS

### How are you running Gitea?

Installed by the _snap install gitea_ command.
Configuration via the web interface to use the sqlite3 database and run from the _git_ user. After the reboot, the startup failed. Screenshot with an error in the attachment. The startup is performed using _systemd_.

/etc/systemd/system/snap.gitea.web.service :
```
[Unit]
# Auto-generated, DO NOT EDIT
Description=Service for snap application gitea.web
Requires=snap-gitea-6042.mount
Wants=network.target
After=snap-gitea-6042.mount network.target snapd.apparmor.service
X-Snappy=yes

[Service]
EnvironmentFile=-/etc/environment
ExecStart=/usr/bin/snap run gitea.web
SyslogIdentifier=gitea.web
Restart=on-failure
WorkingDirectory=/var/snap/gitea/6042
TimeoutStopSec=30
Type=simple

[Install]
WantedBy=multi-user.target
```

![2022-06-07_21-49](https://user-images.githubusercontent.com/73383273/172459571-8ea74068-2283-403a-bc3a-d43baac8f4db.jpg)

![2022-06-07_21-56](https://user-images.githubusercontent.com/73383273/172461184-c0fe74ef-4486-4778-a7be-b7403aea034b.jpg)

### Database

SQLite

**Comment by techknowlogick** [comment]
snap runs gitea as root (albeit sandboxed), so you'll need to change the RUN_USER to root

For those that come later, this is only for snap, as running as root is something that should never be done.
