### ISSUE TITLE
Cannot enable CORS on snap-installed gitea

### ISSUE THREAD

**Issue by DrPyser** [go-gitea/gitea#19914]
### Description

I'm trying to setup a local instance of gitea with CORS enabled to allow integration with tools that expect CORS-enabled APIs.
Despite editing the configuration with this snippet, there's no indication that the instance is correctly cors-enabled(e.g. no indication in configuration section of site administration view in UI) and the tool I'm trying to integrate is still complaining about invalid CORS responses.
```ini
[cors]
ENABLED = true
ALLOW_DOMAIN = *
SCHEME = http
ALLOW_CREDENTIALS = true
```

I installed through snap, so maybe the issue is related but I don't see how. 

### Gitea Version

Gitea version 1.16.8 built with GNU Make 4.1, go1.18.2 : bindata, sqlite, sqlite_unlock_notify, pam, cert

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

Ubuntu 20.04

### How are you running Gitea?

running gitea web service as snap service.

### Database

SQLite

**Comment by DrPyser** [comment]
For the records, I switched to using the docker image with a Caddy proxy to handle CORS instead.

**Comment by wxiaoguang** [comment]
IIRC, `[cors]` only works for API and a few web endpoints.
