### ISSUE TITLE
Topics Save Button uses href with javascript protocol

### ISSUE THREAD

**Issue by Ryuno-Ki** [go-gitea/gitea#19912]
### Description

I noticed this while working on #19900.

In general, `href="javascript:;"` is an anti-pattern (see http://www.jibbering.com/faq/#javascriptURI for the original intent).
As a rule of thumb, links go somewhere and buttons are used to resolve actions.

https://github.com/go-gitea/gitea/blob/d9b50e4fd126e60fe0735bafbcb12d0e8f6dd0c2/templates/repo/home.tmpl#L48-L49

is the only occurence I could find so far. Since it is controlled by JavaScript alone, a fix would require the `<a>` to become `<button type="button">` (or perhaps a submit button if there would be a `<form>` and Go-side logic to update the saved topics).
Plus some style changes to make it look like before.

### Gitea Version

1.17.0+dev-675-g81cf00686

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

try.gitea.io

**Comment by wxiaoguang** [comment]
There could be a lot of bad smells in a large project which is many years old ..... so, large projects always need maintaining and refactoring.

And I think the AJAX was used there to avoid page reload/refresh, just like what GitHub does, it seems no benefit to replace it with a form.

**Comment by silverwind** [comment]
Proper solution is probably `<a role="button">`.
