### ISSUE TITLE
Deleting pull request result in 500

### ISSUE THREAD

**Issue by HarounGY** [go-gitea/gitea#19924]
### Description

Create a pull request and then deleting it, return a 500 page

### Gitea Version

d087554d81e56bff6bde9c68bf610daae15b011e 

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

![image](https://user-images.githubusercontent.com/17424154/172782094-7ce1ce9f-6b3c-4b8c-bac0-c31bc49fcdfd.png)

### Git Version

git version 2.29.1.windows.1

### Operating System

win10

### How are you running Gitea?

Build Gitea myself in Windows with no change.

### Database

SQLite

**Comment by lafriks** [comment]
Please report issues in English

**Comment by lunny** [comment]
> Please report issues in English

I helped the translation.

**Comment by delvh** [comment]
I would like to point out the error in the log:
> DeleteIssueByID: exit status 1 - error: cannot lock ref `refs/pull/7`: ...

**Comment by wxiaoguang** [comment]
It's likely caused by the unexpected git refs in your repository. You may try to remove the `pull/7/head` ref from your repository. Feel free to re-open if there are other problems.
