### ISSUE TITLE
Unable to create new issues

### ISSUE THREAD

**Issue by Muirrum** [go-gitea/gitea#19927]
### Description

When trying to create a new issue, Gitea throws a 500 because of what I assume to be badly formatted SQL (`NewIssue: generate issue index failed: pq: syntax error...`).

My PostgreSQL version is 14.3.

### Gitea Version

1.16.8

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/Muirrum/a8215137e3daceab45bf617a89012821

### Git Version

2.36.1

### Operating System

Alpine

### How are you running Gitea?

Using the alpine linux APK via OpenRC and nginx.

### Database

PostgreSQL

**Comment by techknowlogick** [comment]
first, I just want to say a big thank you for including logs you have already as that's incredibly helpful. This is one of the cases where we'd ask you to enable SQL logging (per https://docs.gitea.io/en-us/logging-configuration/#debugging-problems) could you enable SQL logs so we could see the exact SQL statement that is being made?

**Comment by zeripath** [comment]
> BTW: I think XORM should log all SQL errors by default, it would make the debugging easier.

I could agree with these being at Log.DEBUG level but not all Errors in SQL are actually going to be errors.

**Comment by lunny** [comment]
Cannot reproduce that in Postgres 13.4.

**Comment by zeripath** [comment]
> My PostgreSQL version is 14.3.

Are you sure that you're connecting to the right Postgres DB?

> 2022/06/09 14:12:59 models/db/index.go:64:GetNextResourceIndex() [I] [SQL] INSERT INTO issue_index (group_id, max_index) VALUES ($1,1) ON CONFLICT (group_id) DO UPDATE SET max_index = issue_index.max_index+1 [10] - 281.628µs

Maps to:

```sql
INSERT INTO issue_index (group_id, max_index) VALUES (10,1) ON CONFLICT (group_id) DO UPDATE SET max_index = issue_index.max_index+1
```

> 2022/06/09 14:12:59 ...rs/web/repo/issue.go:1015:NewIssuePost() [E] NewIssue: generate issue index failed: pq: syntax error at or near "ON"

implies that the `ON CONFLICT` is not supported... The last version of Postgres that does not support ON CONFLICT is Postgres version 9.4...
