### ISSUE TITLE
Composer package contains `.git` directory from packagist

### ISSUE THREAD

**Issue by S1SYPHOS** [go-gitea/gitea#19929]
### Description

Whenever I release [my package](https://codeberg.org/Fundevogel/kirby3-charts) and install it via Composer (for its Packagist page, see [here](https://packagist.org/packages/fundevogel/kirby3-charts)), the installed version includes `.git` directory and - please correct me if I'm taking a too big leap here - I guess it could be a miscommunication / cloning issue between Packagist and Gitea. When the same package was hosted on GitHub, in a past "far far away", this was never an issue, so migrating to Gitea "is my only hope" (= clue) what could be causing this behaviour.

It's a long shot, but maybe others had this issue as well. Thanks for this great project,
cheers

S1SYPHOS

### Gitea Version

1.16

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

I'm using https://codeberg.org

**Comment by KN4CK3R** [comment]
I think we can close this

https://github.com/composer/packagist/issues/1009#issuecomment-1152900400

> Well, there is no composer driver for gitea yet. So composer is not able to know that gitea provides archives for specific commits in the repository (and I don't even know whether gitea has such feature). As such, there is no dist to use and composer will then install from source (that's why the option is named `prefer-dist` and not `use-dist`, as there is no guarantee that a dist will always be used due to not having dists at all). The support for generic git servers only has source install (by doing a git clone).

**Comment by S1SYPHOS** [comment]
As much as I would love to see webhook support AND package support for packagist (= 1st class), I know that for now, this may be closed.

Thanks for letting me know, anyway!

**Comment by KN4CK3R** [comment]
If I understand it correct there is nothing Gitea could do.
> Well, there is no composer driver for gitea yet.
