### ISSUE TITLE
[Proposal] Remove most `class="hidden"` for Fomantic checkbox/radiobox

### ISSUE THREAD

**Issue by wxiaoguang** [go-gitea/gitea#19926]
According to https://fomantic-ui.com/modules/checkbox.html#/usage

The `<input class="hidden" type="(checkbox|radio)" tabindex="0" ...>` could be simplified to `<input type="(checkbox|radio)"  ...>`

The "hidden" CSS class here is very ambiguous and seems not help about UI/UX in most cases. The comment for it is: 

```
/* Initialized checkbox moves input below element to prevent manually triggering */
.ui.checkbox input.hidden {
  z-index: -1;
}
```

**Comment by silverwind** [comment]
The hidden class seems to for the purpose of allowing a click on the label to toggle the checkbox which is not possible with their suggested HTML.

It's possible to make checkboxes toggleable through label by putting them inside it, for example https://jsfiddle.net/silverwind/seb670f3/, so something like that should be preferrable.

Generally like to remove the fomantic checkbox/radio module and implement these ourselves.

**Comment by wxiaoguang** [comment]
To be more aggressive, I prefer to use native checkbox/radio/select as much as possible instead of these Fomantic UI checkbox/radio/dropdown. GitHub is using native HTML input elements as much as possible. And these native elements are more friendly for all browsers and a11y.

**Comment by Ryuno-Ki** [comment]
Can we label this `kind/ui`?

Instead of nesting `<input type="checkbox" />` (or `radio`) inside a `<label>`, they can be associated with `id` and `for`.

I agree with getting rid of `::before`.
(`:before` is valid, too. But `:` is usually preferred for pseudo-classes, whereas `::` is used for pseudo-elements).

**Comment by Ryuno-Ki** [comment]
> It's feasible. But Fomantic UI checkbox has some features which is not simple.

Which would that be? Looking through their documentation I couldn't spot anything, that couldn't be done with a few lines of HTML and JS.

**Comment by wxiaoguang** [comment]
> > It's feasible. But Fomantic UI checkbox has some features which is not simple.
> 
> Which would that be? Looking through their documentation I couldn't spot anything, that couldn't be done with a few lines of HTML and JS.

I mean the API for the Fomantic checkbox. I did a grep by `.checkbox` in the `web_src/js` directory. All these code should rewritten.

**Comment by jn64** [comment]
Fomantic checkbox fails if user blocks remote fonts e.g. `gfx.downloadable_fonts.enabled=false` in Firefox, or popular browser extensions like uBlock

Example from [gitea demo](https://try.gitea.io/user/login):
![Screenshot of checkbox on Gitea with remote fonts disabled](https://user-images.githubusercontent.com/23169302/178101998-96fcd1d7-0665-46a0-8bdf-c2f69ef02895.png)

**Comment by silverwind** [comment]
Indeed, that's another argument for native checkboxes with SVG overlay, like we already do for Markdown checkboxes.

**Comment by wxiaoguang** [comment]
Close this one. Wait for the rewriting the checkbox code using the native element.
