### ISSUE TITLE
Can not verify your SSH key: SSHKeyGenParsePublicKey failed: exit status 255 No user exists for uid 997

### ISSUE THREAD

**Issue by wxiaoguang** [go-gitea/gitea#19920]
Some docker users are affected by this bug (not only one) when they try to add public keys.

```
Can not verify your SSH key: SSHKeyGenParsePublicKey: fail to parse public key: exec(629f88e0-5:SSHKeyGenParsePublicKey) failed: exit status 255() stdout: stderr: No user exists for uid 997 - No user exists for uid 997
```

It's likely cased by the error reported by the `ssh-keygen` command executed by Gitea, which meets the non-existing UID 997.

I don't know how it happens at the moment. For Gitea Docker, the UID should have been default to 1000, maybe user's setup steps/configs/operations could provide some clues.

**Comment by zeripath** [comment]
As far as I can see our entrypoint (for the docker with root) would ensure that the USER_UID is in the /etc/passwd file.

Therefore I think this can only happen on the root docker if they're not using our entrypoint - I don't think we can be expected to correctly configure things if they're not using our entrypoint.

On the rootless - do we really use ssh-keygen there?

**Comment by wxiaoguang** [comment]
I have checked the entrypoint logic and tried to play a while, but I have difficulty to reproduce the problem (I do not know what the users have done on their side .....)

Another thing that I do not understand is whose UID is 997. In most Linux distro, the 997 doesn't seem to be a common UID, and it doesn't seem to be easily used by a user by mistake.

**Comment by kubo6472** [comment]
> I have checked the entrypoint logic and tried to play a while, but I have difficulty to reproduce the problem (I do not know what the users have done on their side .....)
> 
> Another thing that I do not understand is whose UID is 997. In most Linux distro, the 997 doesn't seem to be a common UID, and it doesn't seem to be easily used by a user by mistake.

988 for me. Experiencing basically the same thing.

**Comment by wxiaoguang** [comment]
Could you provide your setup details? A reproducible example would help the debug.

**Comment by kubo6472** [comment]
Nevermind, it was my configuration mistake

**Comment by wxiaoguang** [comment]
Could you share your experiences? It will help other users. Thank you.

**Comment by kubo6472** [comment]
It's very specific, but sure:
![image](https://user-images.githubusercontent.com/26146502/190874686-8fa12112-8b09-40d7-994b-abd63a1fec05.png)
I clicked this button, it made that error happen. It was downloaded from here: https://github.com/parkervcp/eggs/tree/master/software/gitea and it runs on Pterodactyl Panel

**Comment by wxiaoguang** [comment]
No more feedbacks

**Comment by MvBonin** [comment]
> 

I use pterodactyl too and with this set to false, the error is still there.

**Comment by wxiaoguang** [comment]
Can you help to provide more clues? Or could you help to provide a minimal reproduce setup instruction?
