### ISSUE TITLE
Server restarts after power failure and the project file is damaged

### ISSUE THREAD

**Issue by xd1810232299** [go-gitea/gitea#19933]
### Description

The server restarts after power failure ,and the project file is damaged when submitting the code. Gitea background cannot view the project,displayed 500

### Gitea Version

1.14.7

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![image](https://user-images.githubusercontent.com/46117049/173033696-86461247-d731-46e1-827a-d3a8f7358976.png)

### Git Version

2.30.1

### Operating System

CentOS7.6

### How are you running Gitea?

command

### Database

SQLite

**Comment by delvh** [comment]
I don't know what you want us to do.
This sounds like due to the power failure, your filesystem got corrupted.
Without further information, there is nothing that can be done from our side.

**Comment by wxiaoguang** [comment]
Agree with delvh

If you are sure there is something wrong with Gitea, please provide logs. Otherwise if your filesystem corrupts, please try to recover it or use backups.

**Comment by xd1810232299** [comment]
I can't see the logs for this wrong.When I submit the code,the server restarts,and I sumbit again.In the directory/gitea - repositories/XXX/projectname git/objects/34 damage of the file.I don't konw the reason.

**Comment by lunny** [comment]
Please paste the error logs.
