### ISSUE TITLE
Compare Releases 10 tags only

### ISSUE THREAD

**Issue by danielezelante** [go-gitea/gitea#19936]
### Description

Pressing Compare button in Releases page, the 10 oldest releases only are shown to select for comparison.

### Gitea Version

1.16.8 ... main

**Comment by lunny** [comment]
regression from #16897

**Comment by 6543** [comment]
does this also happen with 1.17.0-rc1 ?

**Comment by lunny** [comment]
Maybe RC2. Need a Ajax branches search.

**Comment by lunny** [comment]
And it should be fixed in 1.16, it's serious.
