### ISSUE TITLE
mirroring progress screen always results in 500 after failed mirror

### ISSUE THREAD

**Issue by Fogapod** [go-gitea/gitea#19947]
### Description

I tried mirroring torvalds/linux but my server couldn't handle it (git process OOMd). Seems like this event broke mirroring progress for all other repos.
When I try mirroring anything, I get 500 error. Git process is started though and successfully completed. Repository gets mirrored.
Logs:
```
...s/context/context.go:231:HTML() [E] [62a61ab0-3] Render failed: template: repo/header:41:51: executing "repo/header" at <$.Mirror.GetRemoteName>: invalid value; expected string
[62a61ab0-3] router: completed GET /eugene/linux for [xxxx]:0, 500 Internal Server Error in 21.9ms @ repo/view.go:727(repo.Home)
```
I tried deleting repositories using admin ui; clicking garbage collection, `Delete all repositories missing their Git files` and other buttons in admin ui but it didnt help. Restarting gitea also didn't do anything

### Gitea Version

1.17.0+dev-700-gedf14202f

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

2.34.1

### Operating System

Ubuntu 22.04 LTS

### How are you running Gitea?

Locally compiled binary via systemd

### Database

PostgreSQL

**Comment by moyilong** [comment]
+1

**Comment by moyilong** [comment]
I have tested the latest image, and it is no problem. Thank you @Fogapod
