### ISSUE TITLE
Custom redirect for LANDING_PAGE is ignored

### ISSUE THREAD

**Issue by uriesk** [go-gitea/gitea#19942]
### Description

If i set an URL as LANDING_PAGE (according to PR #19324) — doesn't matter if relative `/org/something` or absolute `https://something.com` — it ignores the option and still shows the the default landing page.
Setting LANDING_PAGE to explore or organization does work.

### Gitea Version

1.16.8

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

Binary from
https://dl.gitea.io/gitea/1.16.8/gitea-1.16.8-linux-amd64
on Ubuntu 20.04.4 LTS
run by systemd service according to docs.gitea.io

### Database

MySQL

**Comment by lunny** [comment]
This feature is in coming v1.17
