### ISSUE TITLE
Ask for Changing alt Property of Logo img Element

### ISSUE THREAD

**Issue by Orange23333** [go-gitea/gitea#19950]
### Feature Description

A little suggestion:

Change from
`<img class="ui mini image" width="30" height="30" src="/assets/img/logo.svg" alt="Logo">`
to
`<img class="ui mini image" width="30" height="30" src="/assets/img/logo.svg" alt="Home Page">`
is more pretty nice for understanding, including but not limited to blind.

By the way, If you use SVG format, could consult GitHub code. They use `aria-label` property:
```html
<a href="https://github.com/" aria-label="Homepage "><svg></svg></a>
```
And GitLab use `aria-label` and a tooltip with text `GitLab home page`:
```html
<a href="/" data-nav="logo" aria-label="Home" class="slp-btn slp-mr-8 slp-btn-icon" ><svg xmlns="http://www.w3.org/2000/svg" role="img" aria-labelledby="tanukiHomeDesktop"><title id="tanukiHomeDesktop">GitLab home page</title></svg></a>
```
But for lightness, `aria-label` property is great and enough.

Thanks a lot!

**Comment by wxiaoguang** [comment]
Try this
* https://github.com/go-gitea/gitea/pull/19955

**Comment by Orange23333** [comment]
Nice!

**Comment by wxiaoguang** [comment]
ps: it's still being reviewed. Wait for some time for its merge.
