### ISSUE TITLE
URL of any link in section "Repository" includes port 3030

### ISSUE THREAD

**Issue by cmonty14** [go-gitea/gitea#19963]
### Description

Hello,
when I click a link in section "Repository" the URL includes port 3030.
This URL will result in a 404.

If I use the link in section "main screen" the URL is correct.

I have attached screenshots that document

- link in section "Repository"
- link in section "main screen"
- WebUI showing 404 error

Can you advise how to fix the links in section "Repository"?

THX

### Screenshots

![2022-06-13_17-41-37](https://user-images.githubusercontent.com/12523591/173392164-a7705372-94ab-435b-b67e-7cd79df6e528.png)
![2022-06-13_17-38-11](https://user-images.githubusercontent.com/12523591/173392197-d1706b6a-7bd0-4d71-b4e6-a618cfdc24b0.png)
![2022-06-13_17-38-54](https://user-images.githubusercontent.com/12523591/173392265-69c18b67-b0db-4128-b272-3f14679a875a.png)

### Gitea Version

Gitea version 1.16.8 built with GNU Make 4.1, go1.18.2 : bindata, sqlite, sqlite_unlock_notify

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

Ubuntu 20.04.4 LTS

### Browser Version

Chrome Version 102.0.5005.63

**Comment by wxiaoguang** [comment]
Maybe related to this one
* https://github.com/go-gitea/gitea/issues/19345

Correct your ROOT_URL related settings in your app.ini
