### ISSUE TITLE
why I can edit my team member's issue

### ISSUE THREAD

**Issue by jianjianxu** [go-gitea/gitea#19960]
### Feature Description

We are in the same team, we can edit each other's issue now.
Sometimes, he just edited my issue's reply.
I think this is not right. He should reply my issue to correct my problem, but not just edit my reply.

How can I disable this feature?

**Comment by lunny** [comment]
If you have no write permission of issues in those repositories, that will works like you want.

**Comment by jianjianxu** [comment]
Thank you.
If I close this, can I edit the reply I wrote by myself?

**Comment by wxiaoguang** [comment]
The answer should be yes. This issue can be closed, feel free to re-open if there is a bug.
