### ISSUE TITLE
AuthorizedKeysCommand failed, status 1 with rootless container

### ISSUE THREAD

**Issue by gregflynn** [go-gitea/gitea#19974]
### Description

I followed the rootless docker install method described here mostly: https://docs.gitea.io/en-us/install-with-docker-rootless/
Deviations:
- using single docker run inside a systemd unit file instead of docker compose
- database is located on the host so 172.yada instead
- my git user is UID/GID 998, it's a carry over from my old gogs installation im migrating from (note im not doing any of the migration guides, starting fresh except for the host system user)

I'm currently stuck trying to get the git user's ssh passthrough authentication working so that the host's sshd can be the only ssh server. https://docs.gitea.io/en-us/install-with-docker-rootless/#ssh-container-passthrough

When I have the sshd_config set as described in the documentation, I see in journalctl for `ssh` an error executing the command:
``` 
Jun 15 07:58:11 HOSTNAME-REDACTED sshd[10553]: AuthorizedKeysCommand /usr/bin/docker exec -i gitea /usr/local/bin/gitea keys -e git -u git -t ssh-rsa -k AAAAPUBLICKEY-REDACTED failed, status 1
Jun 15 07:58:11 HOSTNAME-REDACTED sshd[10553]: Connection closed by authenticating user git 192.168.1.1 port 58756 [preauth]
```

So I start debugging:
- Copy and pasted the command and am able to run it manually and successfully as both my personal user and as `sudo su git`, so gitea itself is working, awesome
- Trying some other commands to see which executable in the command chain SSH doesn't like:
  - `AuthorizedKeysCommand /usr/bin/docker exec -i gitea /bin/bash -c "echo hai" failed, status 1`
  - `/usr/bin/docker --help` didn't produce an error in the log, so it seems to have at least been able to execute and get output
  - made sure user `git` is in the docker group
  - checked permissions on /usr/bin/docker and it looks good and based on `docker --help` not reporting status 1 in ssh logs i think the host docker executable is fine probably

### Gitea Version

1.16.8-rootless

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

docker rootless on a debian buster (10)

### How are you running Gitea?

here's my unit file and all it's dirty hacks

```
[Unit]
Description=Gitea Server Docker Container
After=docker.service
Requires=docker.service

[Service]
User=git
Group=git
TimeoutStartSec=0
ExecStartPre=-/usr/bin/docker kill gitea
ExecStartPre=-/usr/bin/docker rm gitea
#ExecStartPre=/usr/bin/docker pull gitea/gitea:1.16.8-rootless
ExecStart=/usr/bin/docker run --name gitea \
    --user 998 \
    -e "USER_UID=998" \
    -e "USER_GID=998" \
    -e "GITEA__database__DB_TYPE=postgres" \
    -e "GITEA__database__HOST=172.17.0.1:5432" \
    -e "GITEA__database__NAME=giteadb" \
    -e "GITEA__database__USER=REDACTED" \
    -e "GITEA__database__PASSWD=REDACTED" \
    -v "/tank/git/gitea/data:/var/lib/gitea" \
    -v "/tank/git/gitea/conf:/etc/gitea" \
    -v "/etc/timezone:/etc/timezone:ro" \
    -v "/etc/localtime:/etc/localtime:ro" \
    -p 3002:3000 \
    gitea/gitea:1.16.8-rootless
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
```

### Database

PostgreSQL

**Comment by gregflynn** [comment]
Poking around at this some more, I figured a fun test would be since i can manually run `gitea keys` and get good output, i'll write that to a file and tell ssh to cat that file as `AuthorizedKeysCommand`. Well that worked to verify that the rest of the flow is working, all that's broken is getting `sshd` to run docker and barf out those keys

![image](https://user-images.githubusercontent.com/295898/173970672-f1ec104e-ab98-4695-a118-16b8ec40482d.png)

**Comment by 42wim** [comment]
Can you add extra sshd loglevel ? Add `LogLevel DEBUG3` in /etc/ssh/sshd_config and restart sshd
Retry and see if it gives a bit more output regarding the `status 1`

**Comment by gregflynn** [comment]
> Can you add extra sshd loglevel ? Add `LogLevel DEBUG3` in /etc/ssh/sshd_config and restart sshd Retry and see if it gives a bit more output regarding the `status 1`

Ah yes log level! Unfortunately I didn't spot anything that stuck out on debug 3, i've copied a snippet here starting at sshd finding the match for `git` and through failing publickey auth

```

Jun 18 17:28:25 REDACT-HOSTNAME sshd[14932]: debug1: user git matched 'User git' at line 125
Jun 18 17:28:25 REDACT-HOSTNAME sshd[14932]: debug3: match found
Jun 18 17:28:25 REDACT-HOSTNAME sshd[14932]: debug3: reprocess config:126 setting AuthorizedKeysCommandUser git
Jun 18 17:28:25 REDACT-HOSTNAME sshd[14932]: debug3: reprocess config:129 setting AuthorizedKeysCommand /usr/bin/docker exec -i gitea /usr/local/bin/gitea keys -e git -u %u -t %t -k %k
Jun 18 17:28:25 REDACT-HOSTNAME sshd[14932]: debug3: mm_answer_pwnamallow: sending MONITOR_ANS_PWNAM: 1
Jun 18 17:28:25 REDACT-HOSTNAME sshd[14932]: debug3: mm_request_send entering: type 9
Jun 18 17:28:25 REDACT-HOSTNAME sshd[14932]: debug2: monitor_read: 8 used once, disabling now
Jun 18 17:28:25 REDACT-HOSTNAME sshd[14932]: debug2: input_userauth_request: setting up authctxt for git [preauth]
Jun 18 17:28:25 REDACT-HOSTNAME sshd[14932]: debug3: mm_start_pam entering [preauth]
Jun 18 17:28:25 REDACT-HOSTNAME sshd[14932]: debug3: mm_request_send entering: type 100 [preauth]
Jun 18 17:28:25 REDACT-HOSTNAME sshd[14932]: debug3: mm_inform_authserv entering [preauth]
Jun 18 17:28:25 REDACT-HOSTNAME sshd[14932]: debug3: mm_request_send entering: type 4 [preauth]
Jun 18 17:28:25 REDACT-HOSTNAME sshd[14932]: debug2: input_userauth_request: try method none [preauth]
Jun 18 17:28:25 REDACT-HOSTNAME sshd[14932]: debug3: user_specific_delay: user specific delay 0.000ms [preauth]
Jun 18 17:28:25 REDACT-HOSTNAME sshd[14932]: debug3: ensure_minimum_time_since: elapsed 1.582ms, delaying 7.087ms (requested 8.669ms) [preauth]
Jun 18 17:28:25 REDACT-HOSTNAME sshd[14932]: debug3: mm_request_receive entering
Jun 18 17:28:25 REDACT-HOSTNAME sshd[14932]: debug3: monitor_read: checking request 100
Jun 18 17:28:25 REDACT-HOSTNAME sshd[14932]: debug1: PAM: initializing for "git"
Jun 18 17:28:25 REDACT-HOSTNAME sshd[14932]: debug1: PAM: setting PAM_RHOST to "192.168.1.1"
Jun 18 17:28:25 REDACT-HOSTNAME sshd[14932]: debug1: PAM: setting PAM_TTY to "ssh"
Jun 18 17:28:25 REDACT-HOSTNAME sshd[14932]: debug2: monitor_read: 100 used once, disabling now
Jun 18 17:28:25 REDACT-HOSTNAME sshd[14932]: debug3: mm_request_receive entering
Jun 18 17:28:25 REDACT-HOSTNAME sshd[14932]: debug3: monitor_read: checking request 4
Jun 18 17:28:25 REDACT-HOSTNAME sshd[14932]: debug3: mm_answer_authserv: service=ssh-connection, style=, role=
Jun 18 17:28:25 REDACT-HOSTNAME sshd[14932]: debug2: monitor_read: 4 used once, disabling now
Jun 18 17:28:25 REDACT-HOSTNAME sshd[14932]: debug3: userauth_finish: failure partial=0 next methods="publickey" [preauth]
Jun 18 17:28:25 REDACT-HOSTNAME sshd[14932]: debug3: send packet: type 51 [preauth]
Jun 18 17:28:25 REDACT-HOSTNAME sshd[14932]: debug3: receive packet: type 50 [preauth]
Jun 18 17:28:25 REDACT-HOSTNAME sshd[14932]: debug1: userauth-request for user git service ssh-connection method publickey [preauth]
Jun 18 17:28:25 REDACT-HOSTNAME sshd[14932]: debug1: attempt 1 failures 0 [preauth]
Jun 18 17:28:25 REDACT-HOSTNAME sshd[14932]: debug2: input_userauth_request: try method publickey [preauth]
Jun 18 17:28:25 REDACT-HOSTNAME sshd[14932]: debug1: userauth_pubkey: test pkalg rsa-sha2-512 pkblob RSA SHA256:LALALA-REDACT [preauth]
Jun 18 17:28:25 REDACT-HOSTNAME sshd[14932]: debug3: mm_key_allowed entering [preauth]
Jun 18 17:28:25 REDACT-HOSTNAME sshd[14932]: debug3: mm_request_send entering: type 22 [preauth]
Jun 18 17:28:25 REDACT-HOSTNAME sshd[14932]: debug3: mm_key_allowed: waiting for MONITOR_ANS_KEYALLOWED [preauth]
Jun 18 17:28:25 REDACT-HOSTNAME sshd[14932]: debug3: mm_request_receive_expect entering: type 23 [preauth]
Jun 18 17:28:25 REDACT-HOSTNAME sshd[14932]: debug3: mm_request_receive entering [preauth]
Jun 18 17:28:25 REDACT-HOSTNAME sshd[14932]: debug3: mm_request_receive entering
Jun 18 17:28:25 REDACT-HOSTNAME sshd[14932]: debug3: monitor_read: checking request 22
Jun 18 17:28:25 REDACT-HOSTNAME sshd[14932]: debug3: mm_answer_keyallowed entering
Jun 18 17:28:25 REDACT-HOSTNAME sshd[14932]: debug3: mm_answer_keyallowed: key_from_blob: 0x55cda5b4ee20
Jun 18 17:28:25 REDACT-HOSTNAME sshd[14932]: debug3: subprocess: AuthorizedKeysCommand command "/usr/bin/docker exec -i gitea /usr/local/bin/gitea keys -e git -u git -t ssh-rsa -k AAAAREDACTEDTINFOILHAT
Jun 18 17:28:25 REDACT-HOSTNAME sshd[14932]: debug1: temporarily_use_uid: 998/998 (e=0/0)
Jun 18 17:28:25 REDACT-HOSTNAME sshd[14932]: debug1: restore_uid: 0/0
Jun 18 17:28:25 REDACT-HOSTNAME sshd[14932]: debug3: subprocess: AuthorizedKeysCommand pid 14934
Jun 18 17:28:25 REDACT-HOSTNAME sshd[14932]: debug1: temporarily_use_uid: 998/998 (e=0/0)
Jun 18 17:28:25 REDACT-HOSTNAME sshd[14932]: AuthorizedKeysCommand /usr/bin/docker exec -i gitea /usr/local/bin/gitea keys -e git -u git -t ssh-rsa -k AAAAAAAAREDACTEDTINFOILHAT failed, status 1
Jun 18 17:28:25 REDACT-HOSTNAME sshd[14932]: debug1: restore_uid: 0/0
Jun 18 17:28:25 REDACT-HOSTNAME sshd[14932]: debug1: temporarily_use_uid: 998/998 (e=0/0)
Jun 18 17:28:25 REDACT-HOSTNAME sshd[14932]: debug1: trying public key file /tank/git/.ssh/authorized_keys
Jun 18 17:28:25 REDACT-HOSTNAME sshd[14932]: debug1: Could not open authorized keys '/tank/git/.ssh/authorized_keys': No such file or directory
Jun 18 17:28:25 REDACT-HOSTNAME sshd[14932]: debug1: restore_uid: 0/0
Jun 18 17:28:25 REDACT-HOSTNAME sshd[14932]: debug1: temporarily_use_uid: 998/998 (e=0/0)
Jun 18 17:28:25 REDACT-HOSTNAME sshd[14932]: debug1: trying public key file /tank/git/.ssh/authorized_keys2
Jun 18 17:28:25 REDACT-HOSTNAME sshd[14932]: debug1: Could not open authorized keys '/tank/git/.ssh/authorized_keys2': No such file or directory
Jun 18 17:28:25 REDACT-HOSTNAME sshd[14932]: debug1: restore_uid: 0/0
Jun 18 17:28:25 REDACT-HOSTNAME sshd[14932]: debug3: mm_answer_keyallowed: publickey authentication test: RSA key is not allowed
Jun 18 17:28:25 REDACT-HOSTNAME sshd[14932]: Failed publickey for git from 192.168.1.1 port 52740 ssh2: RSA SHA256:LALALAREDACTED
```

**Comment by 42wim** [comment]
Ok that's not to useful, up next is strace if you're up for it :)
run `strace -yy -s1000 -f -o outputfile -p <sshdpid>` and try again
This will create a lot of output, and hopefully shows what causing it, knowing openssh, probably a permission issue :)

**Comment by gregflynn** [comment]
> Ok that's not to useful, up next is strace if you're up for it :) run `strace -yy -s1000 -f -o outputfile -p <sshdpid>` and try again This will create a lot of output, and hopefully shows what causing it, knowing openssh, probably a permission issue :)

Absolutely, so in strace output I did find an interesting nugget, but of course can post more output:
```
19892 futex(0xc000094840, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
19885 write(2</dev/null<char 1:3>>, "Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.39/containers/gitea/json: dial unix /var/run/docker.sock: connect: permission denied\n", 232) = 232
19885 exit_group(1 <unfinished ...>
19888 <... futex resumed> )             = ? <unavailable>
```

This is just above the strace line indicating the write of the "AuthrizedKeysCommand failed" line in sshd and this seems to imply that the user is lacking the `docker` group but:
```
$ sudo su git -s /bin/bash
$ groups
git docker
```

There's a user entry for `sshd` in `/etc/passwd`, does `sshd` need docker permissions? Feels dirty

**Comment by 42wim** [comment]
No, it uses the `AuthorizedKeysCommandUser` to exec the `AuthorizedKeysCommand`
You should be able to see in the strace output above that permission denied the uid/gid it's using to execute the command.
What is the output of `ls -al /var/run/docker.sock` ?

**Comment by gregflynn** [comment]
> No, it uses the `AuthorizedKeysCommandUser` to exec the `AuthorizedKeysCommand` You should be able to see in the strace output above that permission denied the uid/gid it's using to execute the command. What is the output of `ls -al /var/run/docker.sock` ?

```
 ls -al /var/run/docker.sock
srw-rw---- 1 root docker 0 Mar  9 14:58 /var/run/docker.sock
```

Yea you're right, I see a number of calls to setting uid/gid 998 as expected

**Comment by 42wim** [comment]
What is the output of `id git`

**Comment by gregflynn** [comment]
> What is the output of `id git`

```
 id git
uid=998(git) gid=998(git) groups=998(git),105(docker)
```

**Comment by 42wim** [comment]
Sorry  no idea then, looks like it should work

**Comment by gregflynn** [comment]
> Sorry no idea then, looks like it should work

Haha, I appreciate the ideas to further debugging, I have a few more crazy ideas to try. My suspicion is something about maybe debian's sshd here or its age since debian likes that stability. I'm tempted to make a new user just for this handoff and see if there's some crazy restriction about sub-1000 uid/gid users.

**Comment by zeripath** [comment]
It's likely that you will need to set the correct user for the docker exec command.

e.g.

```
  AuthorizedKeysCommand /usr/bin/docker exec ---user 998 -e "USER_UID=998" -e "USER_GID=998"  -i gitea /usr/local/bin/gitea keys -c /etc/gitea/app.ini -e git -u %u -t %t -k %k
```

**Comment by gregflynn** [comment]
> It's likely that you will need to set the correct user for the docker exec command.
> 
> e.g.
> 
> ```
>   AuthorizedKeysCommand /usr/bin/docker exec ---user 998 -e "USER_UID=998" -e "USER_GID=998"  -i gitea /usr/local/bin/gitea keys -c /etc/gitea/app.ini -e git -u %u -t %t -k %k
> ```

So that change looked like we got further as the sshd log no longer says `status 1` but still permission denied. Hopped back into strace and spotted an unfortunately familiar error though:
```
23554 futex(0x55b6c4f84ea0, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
23566 write(2</dev/null<char 1:3>>, "Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.39/containers/gitea/json: dial unix /var/run/docker.sock: connect: permission denied\n", 232) = 232
23566 exit_group(1)                     = ?
23565 <... futex resumed>)              = ?
23564 <... futex resumed>)              = ?
23563 <... futex resumed>)              = ?
23561 <... futex resumed>)              = ?
23560 <... futex resumed>)              = ?
23564 +++ exited with 1 +++
23566 +++ exited with 1 +++
23565 +++ exited with 1 +++
23563 +++ exited with 1 +++
23561 +++ exited with 1 +++
23560 +++ exited with 1 +++
23559 <... futex resumed>)              = ?
23558 <... futex resumed>)              = ?
23557 <... futex resumed>)              = ?
23559 +++ exited with 1 +++
23556 <... futex resumed>)              = ?
23558 +++ exited with 1 +++
23557 +++ exited with 1 +++
23555 <... nanosleep resumed> <unfinished ...>) = ?
23556 +++ exited with 1 +++
23554 <... futex resumed>)              = ?
23562 <... futex resumed>)              = ?
23555 +++ exited with 1 +++
23562 +++ exited with 1 +++
23552 <... read resumed> "", 4096)      = 0
23554 +++ exited with 1 +++
23552 --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=23554, si_uid=998, si_status=1, si_utime=3, si_stime=2} ---
23552 close(4<pipe:[272535367]>)        = 0
23552 wait4(23554, [{WIFEXITED(s) && WEXITSTATUS(s) == 1}], 0, NULL) = 23554
23552 getpid()                          = 23552
23552 socket(AF_UNIX, SOCK_DGRAM|SOCK_CLOEXEC, 0) = 4<UNIX:[272535371]>
23552 connect(4<UNIX:[272535371]>, {sa_family=AF_UNIX, sun_path="/dev/log"}, 110) = 0
23552 sendto(4<UNIX:[272535371->13991]>, "<38>Jun 19 10:44:47 sshd[23552]: AuthorizedKeysCommand /usr/bin/docker exec --user 998 -e USER_UID=998 -e USER_GID=998 -i gitea /usr/local/bin/gitea keys -e git -u git -t ssh-rsa -k AAAA/REDACT", 533, MSG_NOSIGNAL, NULL, 0) = 533
23552 close(4<UNIX:[272535371->13991]>) = 0
23552 rt_sigaction(SIGCHLD, NULL, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
23552 getpid()                          = 23552
23552 socket(AF_UNIX, SOCK_DGRAM|SOCK_CLOEXEC, 0) = 4<UNIX:[272535372]>
23552 connect(4<UNIX:[272535372]>, {sa_family=AF_UNIX, sun_path="/dev/log"}, 110) = 0
23552 sendto(4<UNIX:[272535372->13991]>, "<39>Jun 19 10:44:47 sshd[23552]: debug1: restore_uid: 0/0", 57, MSG_NOSIGNAL, NULL, 0) = 57
23552 close(4<UNIX:[272535372->13991]>) = 0
```

Not sure why we went from signal 1 to no signal 🤷🏻 

Still running that command manually as `git` works and produces output that if I pipe to a file and read that file in AuthorizeKeysCommand

**Comment by zeripath** [comment]
> Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.39/containers/gitea/json: dial unix /var/run/docker.sock: connect: permission denied)

The user running this AuthorizedKeysCommand is not allowed to connect to the docker container.

> Docker shell passthrough using AuthorizedKeysCommand will work only if
>
> * The host git user is allowed to run the docker exec command.

**Comment by gregflynn** [comment]
> > Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.39/containers/gitea/json: dial unix /var/run/docker.sock: connect: permission denied)
> 
> The user running this AuthorizedKeysCommand is not allowed to connect to the docker container.
> 
> > Docker shell passthrough using AuthorizedKeysCommand will work only if
> > 
> > * The host git user is allowed to run the docker exec command.

Yup but the strange part is that if I `sudo su git -s /bin/bash` I can run the docker exec command no sweat. And right now I'm actually using the output of that command from the git user just saved to a file and `cat`'d out to workaround the issue ([comment](https://github.com/go-gitea/gitea/issues/19974#issuecomment-1157127681)).

And [this comment](https://github.com/go-gitea/gitea/issues/19974#issuecomment-1159591416) should demonstrate that the `git` user has the docker group and should thus have the proper permissions. (theoretically assuming no bugs!)

```
 sudo su git -s /bin/bash
[sudo] password for foo:
git@hostname:/home/foo$ /usr/bin/docker exec --user 998 -e USER_UID=998 -e USER_GID=998 -i gitea /usr/local/bin/gitea keys -c /etc/gitea/app.ini -e git -u git -t ssh-rsa -k AAAASNIP
# gitea public key
command="/usr/local/bin/gitea --config=/etc/gitea/app.ini serv key-1",no-port-forwarding,no-X11-forwarding,no-agent-forwarding,no-pty,no-user-rc,restrict ssh-rsa AAAASNIP foo@gmail.com
git@hostname:/home/foo$
```

```
# /etc/ssh/sshd_config
Match User git
  AuthorizedKeysCommandUser git
  #AuthorizedKeysCommand /bin/cat /tank/git/keys.txt
  #AuthorizedKeysCommand /usr/bin/gitea-keys %u %t "%k"
  AuthorizedKeysCommand /usr/bin/docker exec --user 998 -e "USER_UID=998" -e "USER_GID=998" -i gitea /usr/local/bin/gitea keys -c /etc/gitea/app.ini -e git -u %u -t %t -k %k
  #AuthorizedKeysCommand /usr/local/bin/gitea keys -e git -u %u -t %t -k %k
  #AuthorizedKeysCommand /usr/bin/docker exec -i gitea /bin/bash -c "echo %u"
```
The above you can see some of the other ideas I've been poking at to debug.

I appreciate your time and any further ideas to debug!

**Comment by DrasLorus** [comment]
I may have found the problem... I am running Debian 11 Bullseye. It uses OpenSSH_8.4p1.
Quoting [OpenSSH release notes](https://www.openssh.com/releasenotes.html):

> Security
> ========
> 
> [sshd(8)](https://man.openbsd.org/sshd.8) from OpenSSH 6.2 through 8.7 failed to correctly initialise
> supplemental groups when executing an AuthorizedKeysCommand or
> AuthorizedPrincipalsCommand, where a AuthorizedKeysCommandUser or
> AuthorizedPrincipalsCommandUser directive has been set to run the
> command as a different user. Instead these commands would inherit
> the groups that [sshd(8)](https://man.openbsd.org/sshd.8) was started with.

Thus, the git user cannot inherit the docker group, thus can't run docker. I have tried to use sudo, but it is cumbersome and ultimately failed. I have set the AuthorizedKeysCommandUser to root, and it works. You may also add `root` to the docker group, but any AuthorizedKeysCommandUser would gain the permission to run docker.

Not a Gitea bug, nor a docker related one. OpenSSH in Debian is just too old I guess :/

**Comment by gregflynn** [comment]
> I may have found the problem... I am running Debian 11 Bullseye. It uses OpenSSH_8.4p1. Quoting [OpenSSH release notes](https://www.openssh.com/releasenotes.html):
> 
> > # Security
> > [sshd(8)](https://man.openbsd.org/sshd.8) from OpenSSH 6.2 through 8.7 failed to correctly initialise
> > supplemental groups when executing an AuthorizedKeysCommand or
> > AuthorizedPrincipalsCommand, where a AuthorizedKeysCommandUser or
> > AuthorizedPrincipalsCommandUser directive has been set to run the
> > command as a different user. Instead these commands would inherit
> > the groups that [sshd(8)](https://man.openbsd.org/sshd.8) was started with.
> 
> Thus, the git user cannot inherit the docker group, thus can't run docker. I have tried to use sudo, but it is cumbersome and ultimately failed. I have set the AuthorizedKeysCommandUser to root, and it works. You may also add `root` to the docker group, but any AuthorizedKeysCommandUser would gain the permission to run docker.
> 
> Not a Gitea bug, nor a docker related one. OpenSSH in Debian is just too old I guess :/

Oh man I love me a debian bug, good eye! I agree with your assessment that this isn't a gitea bug and given how niche the issue is and the fact that it's fixed in newer releases, this doesn't even warrant a callout in the documentation in my opinion. I appreciate you coming back and solving this mystery!
