### ISSUE TITLE
Duplicate "update by merge" button

### ISSUE THREAD

**Issue by Fogapod** [go-gitea/gitea#19987]
### Description

I have duplicate button each time i create PR from outdated branch

### Screenshots

![image](https://user-images.githubusercontent.com/22667809/174118801-38c90e4a-200d-48a8-aac5-af0ed3893076.png)
![image](https://user-images.githubusercontent.com/22667809/174118833-caf8ca69-0182-4d87-b448-d2073009ef9b.png)

### Gitea Version

1.17.0+dev-719-gf0ce5470e

### Can you reproduce the bug on the Gitea demo site?

No

### Browser Version

Chromium based 100+

**Comment by lunny** [comment]
Do you have a customize template file?

**Comment by Fogapod** [comment]
I haven't done any customization. Just built gitea from source. I only ever changed config file
