### ISSUE TITLE
Don't use third party CDNs

### ISSUE THREAD

**Issue by xPaw** [go-gitea/gitea#20]
Some javascript files can be served from a third party CDN if offline mode is turned off. However turning on offline mode will also disable gravatar, which might not be desirable.

**Comment by linquize** [comment]
I suggest to add one more setting to separate between these 2 settingss.

**Comment by tboerger** [comment]
:+1: for the idea to habe two seperate flags for enable/disable CDN and enable/disable gravatar.

**Comment by makhov** [comment]
Done.
