### ISSUE TITLE
Right menu

### ISSUE THREAD

**Issue by ponzipo** [go-gitea/gitea#200]
I find [this menu](https://lut.im/hJoXbcWA/jPg5FDiZ) very confusing... I think it would be better to have only the blue menu on the right (wiki, releases, etc) and move these things in a horizontal menu (like gogs)

**Comment by tboerger** [comment]
What is confusing with that?

**Comment by ponzipo** [comment]
@tboerger there's too much stuff stacked together. The blue menu is for things related to the repo development, whereas the gray buttons are for "social" stuff.... My opinion is that they they belong better to a horizontal menu on top (like github and and also like gogs)

**Comment by tboerger** [comment]
@lunny decided against putting it at the top because gitea got the focus on cloningnthe repo and not the big focus (visible on every repo page) on the social parts like forking and so on. But the design is not the best yet...

**Comment by lunny** [comment]
Hi, my opinion is two lines header, one line is left repo name and right stars, watchs, and etc. buttons. Another is left repo description and right clone bar.

**Comment by tboerger** [comment]
Fixed with the repo header redesign.
