### ISSUE TITLE
gitea dump error (related to #19930)

### ISSUE THREAD

**Issue by spirkaa** [go-gitea/gitea#20014]
### Description

Dump not working after changes intruduced in #19930 when gpg signing configured  == `.gnupg` dir present

> bash-5.1$ gitea dump -d postgres -c /data/gitea/conf/app.ini
2022/06/18 12:45:04 ...dules/setting/log.go:288:newLogService() [I] Gitea v1.17.0+dev-745-gdd1ed35f7 built with GNU Make 4.3, go1.18.3 : bindata, timetzdata, sqlite, sqlite_unlock_notify
2022/06/18 12:45:04 ...dules/setting/log.go:335:newLogService() [I] Gitea Log Mode: Console(Console:info)
2022/06/18 12:45:04 ...les/setting/cache.go:76:newCacheService() [I] Cache Service Enabled
2022/06/18 12:45:04 ...les/setting/cache.go:91:newCacheService() [I] Last Commit Cache Service Enabled
2022/06/18 12:45:04 ...s/setting/session.go:73:newSessionService() [I] Session Service Enabled
2022/06/18 12:45:04 ...es/setting/mailer.go:127:newMailService() [I] Mail Service Enabled
2022/06/18 12:45:04 ...es/setting/mailer.go:149:newNotifyMailService() [I] Notify Mail Service Enabled
2022/06/18 12:45:04 ...s/storage/storage.go:176:initAttachments() [I] Initialising Attachment storage with type: 
2022/06/18 12:45:04 ...les/storage/local.go:46:NewLocalStorage() [I] Creating new Local Storage at /data/gitea/attachments
2022/06/18 12:45:04 ...s/storage/storage.go:170:initAvatars() [I] Initialising Avatar storage with type: 
2022/06/18 12:45:04 ...les/storage/local.go:46:NewLocalStorage() [I] Creating new Local Storage at /data/gitea/avatars
2022/06/18 12:45:04 ...s/storage/storage.go:188:initRepoAvatars() [I] Initialising Repository Avatar storage with type: 
2022/06/18 12:45:04 ...les/storage/local.go:46:NewLocalStorage() [I] Creating new Local Storage at /data/gitea/repo-avatars
2022/06/18 12:45:04 ...s/storage/storage.go:182:initLFS() [I] Initialising LFS storage with type: 
2022/06/18 12:45:04 ...les/storage/local.go:46:NewLocalStorage() [I] Creating new Local Storage at /data/gitea/lfs
2022/06/18 12:45:04 ...s/storage/storage.go:194:initRepoArchives() [I] Initialising Repository Archive storage with type: 
2022/06/18 12:45:04 ...les/storage/local.go:46:NewLocalStorage() [I] Creating new Local Storage at /data/gitea/repo-archive
2022/06/18 12:45:04 ...s/storage/storage.go:200:initPackages() [I] Initialising Packages storage with type: 
2022/06/18 12:45:04 ...les/storage/local.go:46:NewLocalStorage() [I] Creating new Local Storage at /data/gitea/packages
2022/06/18 12:45:04 cmd/dump.go:241:runDump() [I] Dumping local repositories... /data/gitea/repositories
Failed to include repositories: open /data/gitea/repositories/.gnupg/S.gpg-agent.ssh: no such device or address
2022/06/18 12:45:05 cmd/dump.go:159:fatal() [F] Failed to include repositories: open /data/gitea/repositories/.gnupg/S.gpg-agent.ssh: no such device or address

### Gitea Version

1.17.0+dev-745-gdd1ed35f7

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

Docker image gitea/gitea:dev

### Database

PostgreSQL

**Comment by lunny** [comment]
Please check your filesystem permission

**Comment by wxiaoguang** [comment]
I think this problem is caused by that the `S.gpg-agent.ssh` is not a normal file, it is a unix socket file.

Gitea's dump should only process normal files, skip other types like socket/block/char/pipe

**Comment by wxiaoguang** [comment]
PR #20015 will try to fix this issue.
* #20015
