### ISSUE TITLE
Plans for Gitea v1.18

### ISSUE THREAD

**Issue by delvh** [go-gitea/gitea#20022]
Hi all,

`Gitea v1.17.0-rc1` will be released in the next few hours.
We have created the `release/v1.17` branch accompanied by the `v1.18.0-dev` tag and are now using `main` for `1.18` development.

Please comment here your own plans for the next release.

## Important
This summary is for things you **PLAN TO DO YOURSELF**, not things you want other people to do.
Other comments will be hidden.

## Schedule
`Gitea 1.18-rc1` is currently set to be released on `2022-09-15`, so in the middle of september.
All new features for 1.18 should be merged until `2022-08-21` to be included in the next release.

## Previous Plans
- #18345
- #16429
- #14477

**Comment by delvh** [comment]
My plans are
1) Reviewing  **a lot** of PRs (as always :smiley:  )
1) a Plugin system so that we can finally offload all the optional customizations there without bloating the main binary too much. (At least if I find the time for it, I know already that my free time will be scarce until the next release)

**Comment by Gusted** [comment]
To keep this thread going, my optimistic plans for this release:

- Continue improving mobile experience for Gitea.
- Continue with QoL improvements.
- Fix-up my open [private issues](https://github.com/go-gitea/gitea/pull/17711) PR to be more secure-by-design and hopefully get it merged this release or early next one.
- Help moving forward with [federation](https://github.com/go-gitea/gitea/issues/18240).

**Comment by silentcodeg** [comment]
* Help moving forward with [federation](https://github.com/go-gitea/gitea/issues/18240)
* PR to use the [Friendly Forge Format](https://lab.forgefriends.org/friendlyforgeformat) for mirroring issues, pull requests, comments, etc.

**Comment by 6543** [comment]
* help @Gusted with private issues ...
* help with federation - mostly reviews I guess
* refactoring stuff ...
* help long open pulls
* better integration of external CIs (define api etc ... cc @lunny )

**Comment by harryzcy** [comment]
- help to finish off #19411

**Comment by Ta180m** [comment]
Various federation features:
- Implement [ForgeFed](https://forgefed.org/) vocabulary
- Federated following
- Federated starring
- Federated issues
- Federated comments
- Federated forking
- Federated pull requests
- Cross-instance user migrations
- UI for federated features (Remote interactions pop-up and `authorize_interaction?uri=` page, similar to Mastodon)

**Comment by pat-s** [comment]
Enhanced 2FA support and disabling simple user/pass login in favor of SSO are two long standing feature wishes which would be great to have :)

- https://github.com/go-gitea/gitea/issues/880
- https://github.com/go-gitea/gitea/issues/13606

**Comment by CodeDoctorDE** [comment]
I'm currently not an expert but I want to add the move issue functionality to gitea: https://github.com/go-gitea/gitea/issues/20788

**Comment by 6543** [comment]
@CodeDoctorDE https://github.com/go-gitea/gitea/issues/453#issuecomment-861599858 would be the original ;)

**Comment by earl-warren** [comment]
* Help move forward with https://github.com/go-gitea/gitea/issues/18240
* Add support for the [Friendly Forge Format (F3)](https://forum.forgefriends.org/t/about-the-friendly-forge-format-f3/681) (continuation of https://github.com/go-gitea/gitea/pull/20122)

**Comment by Rainson12** [comment]
is there any plan on the release date? Im following the features included in this release and it the second time 1.18 is past due

**Comment by f403** [comment]
I would also like to have already merged functions sooner. 
Maybe moving work-in-progress to the next release, and releasing 1.18 with current features?

**Comment by delvh** [comment]
Yes, we are now officially in feature freeze.
We discussed the release cycle internally and came to the conclusion that it would make sense to release `rc0` once we enter feature freeze.
This means, `1.18.0-rc0` can be expected in the next few days.
