### ISSUE TITLE
Bleve indexer stuck on large repo

### ISSUE THREAD

**Issue by Fogapod** [go-gitea/gitea#20020]
### Description

I'm running gitea on weak hardware with just 1 cpu. I got linux kernel mirror to work but code indexing is in a weird state.
Here is what admin ui shows: 
![image](https://user-images.githubusercontent.com/22667809/174448040-050bacca-d2f5-40aa-8519-31dac38ba064.png)
All other repos have commit shown so indexer works otherwise.

When i add reindexing to queue, multiple processes appear in system and run for a couple minutes, then they disappear. There are no dmesg OOM messages, there are no gitea logs about it. Gitea admin ui still shows them as running: 
![image](https://user-images.githubusercontent.com/22667809/174448167-cc56902d-31a1-42f6-916e-958fc5f3f283.png)

Code search works, at least partially:
![image](https://user-images.githubusercontent.com/22667809/174448174-98e99a49-7cb6-495d-87ca-b1b308f63690.png)

I have nothing interesting in config:
```ini
[indexer]
REPO_INDEXER_ENABLED = true
```
~~gitea.com has linux source. I wonder what is the state of indexer there? https://gitea.com/marktsai0316/linux~~
gitea.com has indexer disabled

### Gitea Version

1.17.0+dev-751-g433443ffa built with GNU Make 4.3, go1.18.1 : bindata

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

2.34.1

### Operating System

Ubuntu 22.04 LTS

### How are you running Gitea?

Locally compiled binary

### Database

PostgreSQL

**Comment by Fogapod** [comment]
Clicking trash icon does nothing:
```
Jun 18 17:04:15 localhost gitea[62335]: 2022/06/18 17:04:15 [62ae058f] router: completed POST /admin/monitor/cancel/62adf91d-2 for [::]:0, 200 OK in 3.9ms @ admin/admin.go:358(admin.MonitorCancel)
Jun 18 17:04:15 localhost gitea[62335]: 2022/06/18 17:04:15 [62ae056b] router: completed GET /user/events for [::]:0, 200 OK in 36032.1ms @ events/events.go:19(events.Events)
Jun 18 17:04:15 localhost gitea[62335]: 2022/06/18 17:04:15 [62ae058f-2] router: completed GET /admin/monitor for [::]:0, 200 OK in 25.1ms @ admin/admin.go:326(admin.Monitor)
Jun 18 17:04:19 localhost gitea[62335]: 2022/06/18 17:04:19 [62adf4fd] router: polling   GET /user/events for [::]:0, elapsed 3439.0ms @ events/events.go:19(events.Events)
```

**Comment by wxiaoguang** [comment]
It's highly likely related to this problem, but there is no clue about how to fix it.

https://github.com/go-gitea/gitea/blob/c090f87a8db5b51e0aa9c7278b38ddc862c048ac/modules/indexer/code/indexer.go#L146-L163

**Comment by wxiaoguang** [comment]
It should have been fixed.
