### ISSUE TITLE
Switch Dashboard Context dropdown not opening on mobile web ui

### ISSUE THREAD

**Issue by Fogapod** [go-gitea/gitea#20039]
### Description

Title. Tested on gitea.com

### Screenshots

Mobile version:
![Screenshot_20220619-162217_Brave](https://user-images.githubusercontent.com/22667809/174483218-462ca85f-7c37-4c02-bbc3-9962017718b8.png)

Desktop website version:
![Screenshot_20220619-161735_Brave](https://user-images.githubusercontent.com/22667809/174483093-fc616ee3-d791-4b3a-b511-4a803121013c.png)

### Gitea Version

1.17.0+dev-711-g1fef9a2d6

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

Android

### Browser Version

Chromium 102 based

**Comment by Fogapod** [comment]
can still reproduce on gitea.com `1.18.0+dev-125-g6247a1dd5`

**Comment by wxiaoguang** [comment]
I think it could work now? The dropdown code has been improved a lot.

Feel free to reopen if there is still a problem.
