### ISSUE TITLE
Question about upgrading Gitea with minor versions

### ISSUE THREAD

**Issue by Avalancs** [go-gitea/gitea#2004]
I noticed that versions get backport fixes, and I would like to upgrade from 1.1.1 version (from 1 month before) inside the company to 1.1 which contains some fixes to issues I raised. But I did not find anything on minor version upgrades, even though I tried searching the Gitea docs, and "migration", "upgrade" keywords on GitHub.

My main concern is changes in the database schema, such as in the commit  506c98df5bd7d795491906645d8f9befbf91e91a . Is there any general guide/advice on upgrading? Of course I can export database schema from 1.1.1 and 1.1 then compare, but if there is a better way I would like to know.

We are very satisfied with Gitea in general, thanks for this awesome software!

**Comment by cez81** [comment]
1.1 is a not a release, it's the development branch for 1.1.x track. If you mean you want to upgrade to 1.1.2 from 1.1.1, that's fine. Migration scripts deals with db changes. To be safe, do a backup first, then just replace the binary.

**Comment by Avalancs** [comment]
Ahh okay, thank you!
