### ISSUE TITLE
Access Token in Mirror settings

### ISSUE THREAD

**Issue by laikee99** [go-gitea/gitea#20042]
### Feature Description

I would like to set a github mirror in gitea, but the project is private, and I want to use access token to sync it.
As is known to all, github already abandoned method of `username` and `password`, so I think it would be nicer if we can set a token in the mirror settings just like we need to use the token to sync issues.

### Screenshots

![image](https://user-images.githubusercontent.com/28212423/174495648-a2d0d444-8398-4aec-bc97-7bee2d7a8c81.png)

**Comment by jolheiser** [comment]
You should be able to use an access token in place of the password.

**Comment by zeripath** [comment]
As per @jolheiser - just set the access token as the password.
