### ISSUE TITLE
Migrating from https://github.com/ImageMagick/ImageMagick failed

### ISSUE THREAD

**Issue by wcb33** [go-gitea/gitea#20051]
### Description

Only ImageMagick fialed. 
The log 
```
Migrate repository from https://github.com/ImageMagick/ImageMagick failed: updateRepository: update: Error 1366: Incorrect string value: '\xF0\x9F\xA7\x99\xE2\x80...' for column `gitea`.`repository`.`description` at row 1
```

### Gitea Version

1.16.8

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

Debian

### How are you running Gitea?

docker

### Database

MySQL

**Comment by lunny** [comment]
confirm you are using MySQL with utf8mb4

**Comment by Chuanbin-Wang** [comment]
It need edit by self?
![图片](https://user-images.githubusercontent.com/76732400/174543473-870f3e7c-03e6-4094-a088-d22deee0a8a6.png)

**Comment by Chuanbin-Wang** [comment]
add this command for mysql , it's OK.
```
command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
```
Thins.
