### ISSUE TITLE
Pending Tooltip Doesn't Show For New Code Comments

### ISSUE THREAD

**Issue by kdumontnu** [go-gitea/gitea#20068]
### Description

The "Pending" tooltip for PR review comments doesn't show on new comments until the page is reloaded.

To recreate:
 - Go to an open PR.
 - Add comment on line of code
 - "Add to Review" (or "Start Review")
 - Hover cursor on "Pending"
 - Refresh page
 - Hover again

### Gitea Version

1.18.0+dev-14-g1e2c2edab

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

See demo:
![Pending-Tooltip](https://user-images.githubusercontent.com/12700993/174826255-4391639a-154f-4c68-af35-71fb83c6296d.gif)

### How are you running Gitea?

https://gitea.com/Kyle/Tester/pulls/1/files

**Comment by 6543** [comment]
introduced at #19662 ...

**Comment by silverwind** [comment]
Fomantic tooltips need [to be initialized](https://github.com/go-gitea/gitea/blob/main/web_src/js/features/common-global.js#L124-L131) after they are added in the DOM. I think solution should be to extract that initialization into a function and call it after DOM has been modified with content that includes tooltips.

**Comment by wxiaoguang** [comment]
Maybe it's time to drop the Fomantic popup, and use a global mouseenter event handler to popup the attached `data-content`.
