### ISSUE TITLE
general security question

### ISSUE THREAD

**Issue by laoshaw** [go-gitea/gitea#2006]
How safe is it to run gitea on a public IP? comparing to gitlab, redmine etc? https will be used, but how secure is it overall?

I use it locally and really like its simplicity and light-weight-ness, but do not know how many are using it in a public IP these days.

**Comment by lafriks** [comment]
I think it should be quite safe, I have been running it on public IP for quite some time

**Comment by lunny** [comment]
I have two instances on public IP. I think it's safe enough!

**Comment by bkcsoft** [comment]
Apart from `try.gitea.io`, I host 3 ipublic nstances personally, and have 3 other friends that have public instances as well. I'd deem it "safe enough" 🙂

**Comment by ulm0** [comment]
I've been using it for a while now on public ip, 0 problems.

**Comment by sapk** [comment]
Same here, running it on public IP no problem. It would be good to have a security audit in the future. We could also require some version of tools (or display warning) used by gitea like openssh based on CVE.

**Comment by pgaskin** [comment]
4 public, 1 private, running for a while, no problems.

**Comment by techknowlogick** [comment]
Can this issue be closed?
