### ISSUE TITLE
Gitea unable to remember or use ssh keys.

### ISSUE THREAD

**Issue by dogunbound** [go-gitea/gitea#20078]
### Description

After setting up gitea with postgres on my home server, I decided setup my ssh key. I put what was in my id_rsa.pub into the ssh key and tried git push. It asked me to put in a password. 

I check my verify my ssh key and get this: `The provided SSH key, signature or token do not match or token is out-of-date.`

It's not saving the SSH key I put in.

### Gitea Version

1.16.8

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

https://youtu.be/IM73R5ZkjSY 

### Git Version

git version 2.36.1

### Operating System

Fedora NetInstall Linux

### How are you running Gitea?

Docker.

This connects to my Postgres server running on the same machine.

### Database

PostgreSQL

**Comment by mthie** [comment]
Why are you pasting the public key instead of the signature? Please read the line over the signature textarea and paste the result of the command.

**Comment by dogunbound** [comment]
> Why are you pasting the public key again instead of the signature? Please read the line over the signature textarea and paste the result of the command.

I'll be honest. I don't know what the signature is. I tried googling what the signature of a public ssh key, and still unsure as to what it is. https://www.google.com/search?client=firefox-b-1-d&q=signature+textarea+of+ssh+key

**Comment by dogunbound** [comment]
@mthie Same error

**Comment by techknowlogick** [comment]
the instructions have been corrected to reference the priv key in the command that gets run. Please try again.

**Comment by bodzio4749** [comment]
OK... ONE THING to remember: You will have a problem verifying the key if you use THE SAME comment in the public key file.  This is what I did, and I was not happy, sending a lot of "unkind" remarks about the Gitea projects. I was wrong obviously. I finally decided to grep for the string on ALL *.PUB files in the .ssh directory and the mystery was solved for me.  It did force me to evaluate my ssh key management, which should love these confusions in the future. 
Big thanks to the developers.

**Comment by RitchieFlick** [comment]
In case someone else stumbles upon this with the `The provided SSH key, signature or token do not match or token is out-of-date.` error on **Windows**.
I also was unable to verify my keys on **Windows** but executing the same command on **WSL** worked for me, so I guess that there might be a problem with the **Windows** implementation of SSH.

**Comment by masiton** [comment]
> In case someone else stumbles upon this with the `The provided SSH key, signature or token do not match or token is out-of-date.` error on **Windows**. I also was unable to verify my keys on **Windows** but executing the same command on **WSL** worked for me, so I guess that there might be a problem with the **Windows** implementation of SSH.

Can confirm, I had to generate the keypair on Ubuntu for the signed token to be accepted. However, now I can't use Git Extensions, because Putty doesn't support Linux keypairs ("format too new.", even if saved as ver2).
