### ISSUE TITLE
Branch protection user/team dropdowns do not list everyone

### ISSUE THREAD

**Issue by Fogapod** [go-gitea/gitea#20083]
### Description

I tried setting up whitelists for branch protection but dropdowns only list 4 out of 9 org members. Text search only searches among these 4.
![image](https://user-images.githubusercontent.com/22667809/174999524-51a32f7c-a963-4551-9af0-97b327e751dc.png)

![image](https://user-images.githubusercontent.com/22667809/174999546-2ffb3ef8-955b-4ad6-a5a4-3d1c55eeb9f6.png)

Similar thing happened to teams - one of the teams wasnt showing. It worked after team recreation.

I noticed that each of these 4 members is on top of user list of some team. Membership from top to bottom for 1st screenshot:
- none, is website admin
- CI
- devs-back (bottom); lead-devs (top)
- devs-back (top)

### Gitea Version

1.17.0+rc1

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

Locally compiled binary

### Database

PostgreSQL

**Comment by lunny** [comment]
Could you confirm all of the 9 members have read permissions to that repository?

**Comment by Fogapod** [comment]
> Could you confirm all of the 9 members have read permissions to that repository?

Yes.

So here is a `devs-back` team: 
![image](https://user-images.githubusercontent.com/22667809/175066666-074d9fb9-ef42-48a1-8245-8bf2d054290e.png)
It has access to all currently exising repositories (as seen in ui). Look at 3 top members. Red avatar is listed in dropdown while 2 other people are not. All these 3 people only have a single role. 4th member is also a member of other team.

Team permissions:
![image](https://user-images.githubusercontent.com/22667809/175067329-105c200f-ba88-4286-97c6-c321dbb444e0.png)

**Comment by Fogapod** [comment]
![image](https://user-images.githubusercontent.com/22667809/176933962-4832287a-ac2b-4a50-8b79-148e9685d667.png)
This might be related: trying to add team to repository collaborators, search does not work at all, request logs say it always 404s. Even if i type in team name exactly search shows 404 even though pressing button successfully adds that team

**Comment by Gusted** [comment]
I've looked into the issue and the code for this is correct and straightforward. But it's likely that you didn't add the teams to the repository(otherwise other issues would arise if this is already the case). Also for the 404's it's not reproducible for me.

**Comment by Fogapod** [comment]
it has access to that repository:
![image](https://user-images.githubusercontent.com/22667809/177271242-1f0cab71-8024-483b-9af8-2b655e9ba183.png)

today i've got 4 different users shown in that list. still not everyone:
![image](https://user-images.githubusercontent.com/22667809/177271623-8df973ca-070e-42a8-b067-c1370b5db9b7.png)

**Comment by Gusted** [comment]
Is the list scrollable?

**Comment by Gusted** [comment]
So it seems like the code was correct, however the code to store the access information into the database wasn't. Fixed by #20275
