### ISSUE TITLE
Dashboard feed no longer respects FEED_PAGING_NUM setting

### ISSUE THREAD

**Issue by jpraet** [go-gitea/gitea#20080]
### Description

The feed in the dashboard view no longer respects the [ui] FEED_PAGING_NUM setting.
Instead, it looks like the [api] DEFAULT_PAGING_NUM setting is now used.

Reproducable on https://try.gitea.io/ where it shows 30 items instead of 20.

### Gitea Version

1.17.0-rc1

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

docker

**Comment by lunny** [comment]
Are you sure it was setting.UI.FeedPagingNum and the default value is 20?
