### ISSUE TITLE
Open/closed issue/pull count always 0

### ISSUE THREAD

**Issue by jpraet** [go-gitea/gitea#20081]
### Gitea Version

1.17.0-rc1

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

![image](https://user-images.githubusercontent.com/2212615/174993149-7dd2642a-d688-43b2-b5cf-60a0e49069a2.png)

### How are you running Gitea?

docker

**Comment by lunny** [comment]
regression from https://github.com/go-gitea/gitea/commit/796c4eca0bacf67c186768de66fcfee21867045f#r76720279
