### ISSUE TITLE
New organization members automatically watch ALL public repositories

### ISSUE THREAD

**Issue by Fogapod** [go-gitea/gitea#20082]
### Description

In the process of moving to gitea I noticed that every new member of organization automatically starts watching ALL public repositories and all new public repositories are watched by ALL org members.

This is weird and should be turned off by default or made configurable

### Gitea Version

1.17.0+rc1

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![image](https://user-images.githubusercontent.com/22667809/174999026-a9381f48-f6d2-4a64-be53-bc9696c185bf.png)

### How are you running Gitea?

Locally compiled binary

### Database

PostgreSQL

**Comment by jpraet** [comment]
This is already configurable:
https://docs.gitea.io/en-us/config-cheat-sheet/#service-service
AUTO_WATCH_NEW_REPOS: true: Enable this to let all organisation users watch new repos when they are created

**Comment by Fogapod** [comment]
Thanks
