### ISSUE TITLE
Create a test for the 'database is locked' and 'database table is locked' error

### ISSUE THREAD

**Issue by typeless** [go-gitea/gitea#2009]
I tried to re-use the 'NewIssue' integration test for the purpose, creating a test with two goroutines each looping the test 100 times. But it takes quite long time to run and not that reliable given the number of iterations are not that high.

Any thoughts?

**Comment by bkcsoft** [comment]
This is easy actually, just make all tests run in parallel ;)

**Comment by typeless** [comment]
@bkcsoft Would it not affect the CI running time? I suppose the Drone CI server doesn't provide too many cores for free instances.

Anyway I will still submit the PR for troubleshooting the database locking issue. And we can discuss whether to add it to the 'official' test suite later.

**Comment by bkcsoft** [comment]
Running the test in parallel would make it run faster, if we allow to run multiple processes 😉

**Comment by lunny** [comment]
testing for #2040
