### ISSUE TITLE
Manifest: property 'start_url' ignored, should be same origin as document.

### ISSUE THREAD

**Issue by turtlebasket** [go-gitea/gitea#20091]
### Description

The specific place where I'm noticing this issue is in the following homescreen widget:

<img width="422" alt="Screen Shot 2022-06-22 at 1 02 27 PM" src="https://user-images.githubusercontent.com/32886427/175125889-5c27dcb6-c573-4146-8cf0-8986fcae11cf.png">

I have my gitea instance running behind a nginx reverse proxy under a subdomain of my personal web domain, and am noticing that the repo links on the homepage are redirecting me to localhost:3000/\<user\>/\<repo_name\> instead of the \<gitea instance UR>/\<user\>/\<repo_name\>.

`Manifest: property 'start_url' ignored, should be same origin as document` shows up in the JS console on the homescreen, and I think it's probably related.

<img width="523" alt="Screen Shot 2022-06-22 at 1 01 49 PM" src="https://user-images.githubusercontent.com/32886427/175125789-fd2140f3-86f5-4dcd-9bde-0bc8b3b98504.png">

### Gitea Version

1.16.8

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

https://user-images.githubusercontent.com/32886427/175126526-b318083c-91bb-4b11-943b-498f357bc68a.mp4

### Operating System

Ubuntu Server 20.04 LTS

### How are you running Gitea?

- Gitea Snap on Ubuntu Server 20.04 LTS
- Behind nginx reverse proxy under subdomain, using Cloudflare DNS

### Database

SQLite

**Comment by wxiaoguang** [comment]
* https://github.com/go-gitea/gitea/issues/19345

**Comment by turtlebasket** [comment]
Ah, I see this bug has been filed before. Will set the ROOT_URL field in my server config and close this issue. ;)
