### ISSUE TITLE
"New Release" results in 500

### ISSUE THREAD

**Issue by ponzipo** [go-gitea/gitea#201]
I've installed gitea, fresh. I've created a repo, then forked it. When I create a new release for my fork, it results in a 500 page...

**Comment by tboerger** [comment]
Do you have some log output related to that?

**Comment by ponzipo** [comment]
Where should I look for the logs?

**Comment by tboerger** [comment]
It depends how you started it. If you just executed ./gitea web it should be printed out to the terminal.

**Comment by lunny** [comment]
You can find logs in gitea home dir's sub dir `logs`. @ponzipo

**Comment by tboerger** [comment]
I can not reproduce that. Feel free to reopen the issue if it is still present for you and you have some Trace log level output.
