### ISSUE TITLE
[1.17.0-rc1] Missing Tabs on organisation/package-View

### ISSUE THREAD

**Issue by LukasKlepper** [go-gitea/gitea#20106]
### Description

If I select packages on the organisation view then teams and people tab disappear.

I have no access to the tabs on gitea demo.

### Screenshots

![image](https://user-images.githubusercontent.com/69464569/175314200-b9fd8995-6070-42dc-928e-7f496fc3d1b5.png)
![image](https://user-images.githubusercontent.com/69464569/175314289-8f12eae5-afb3-4016-9e1c-817a366bfd84.png)
![image](https://user-images.githubusercontent.com/69464569/175314325-cd0b0da6-db6e-4a95-a698-814c45bae8e0.png)
![image](https://user-images.githubusercontent.com/69464569/175314360-500e7a75-365a-48f6-b4ed-67d2fb80d31a.png)

### Gitea Version

[1.17.0-rc1]

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

Docker on Linux

### Browser Version

Edge, 102.0.1245.44 64bit

**Comment by lhsazevedo** [comment]
Note that, at the moment, the header in organization packages view and the one in #20107 (user packages) share the same template: [templates/user/overview/header.tmpl](https://github.com/go-gitea/gitea/blob/ce8e06f9f30f0ff3800d0d8da3c7d3044c71c64a/templates/user/overview/header.tmpl)
