### ISSUE TITLE
[1.17.0-rc1] Portainer can't connect to Gitea Container registry

### ISSUE THREAD

**Issue by helmut72** [go-gitea/gitea#20111]
### Description

Portainer shows following message when adding a Gitea Container registry:

```
Portainer was not able to use this registry management features. You might need to update the configuration used by Portainer to access this registry.

Note: Portainer registry management features are only supported with registries exposing the [v2 registry API](https://docs.docker.com/registry/spec/api/).
```

### Gitea Version

1.17-rc1

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

Gitea from Docker

**Comment by lunny** [comment]
What's the registry url?

**Comment by helmut72** [comment]
Using the same url like on my own Docker registry `registry.example.com` and in your docs: `gitea.example.com`.

Both with authentication. Then I wanted to select browse in Portainer and the message appears on `gitea.example.com`.

**Comment by KN4CK3R** [comment]
`/v2/_catalog` is not implemented if that endpoint is needed. Is there a way to test your bug with Portainer CE or only with the business version?

**Comment by helmut72** [comment]
Browsing is only supported with business version. Using that because it's free for 5 nodes and it comes with good a good registry browser. I'm limited on time for debugging, will try to do it next days.

**Comment by helmut72** [comment]
Back to an SSH for an hour. I've enabled access log in Gitea, but just got this log entry when I want to start browsing with Portainer when the error appears:
```
"OPTIONS /v2/ HTTP/1.1" 405 0
```

**Comment by Fogapod** [comment]
> ```
> "OPTIONS /v2/ HTTP/1.1" 405 0
> ```

Do you have CORS enabled in gitea config?

**Comment by helmut72** [comment]
I don't have CORS enabled, then it should be disabled.

**Comment by KN4CK3R** [comment]
I added support for `/v2/_catalog` and got some problems which prevent a PR but in general it works.
Github/Gitlab may got the same problems which may be the reason they don't provide this endpoint.

![grafik](https://user-images.githubusercontent.com/1666336/175827985-ee3d64d9-cf00-492f-bf10-b218cf88c8ef.png)
![grafik](https://user-images.githubusercontent.com/1666336/175827996-14ad26c8-6963-4fa3-817a-0667c4b04833.png)

**Comment by helmut72** [comment]
Wow! But it's up to you. I never used Github/Gitlab registry, just the one from Docker and I'm used to browse the registry.

**Comment by KN4CK3R** [comment]
I have added #20469 but this does not work with Portainer. The `_catalog` endpoint returns a list like `['owner/image']`. Portainer uses this name and requests data from the registry with a call to `registry/v2/owner%2Fimage`. As you can see Portainer escapes the slash, so that does not work at the moment. Since other tools like `docker-ls` use the name as is, I would say this a bug in Portainer.

**Comment by helmut72** [comment]
Wow, thanks! I will create an issue to Portainers repo once your pull request it is included in Gitea.

**Comment by helmut72** [comment]
This can be closed as it looks like a problem with Portainer. If Portainer doesn't fix it or won't support Gitea in the future like others, it doesn't matter, because the registry browser in Gitea is an alternative.
