### ISSUE TITLE
Option to add legal notice/privacy policy page

### ISSUE THREAD

**Issue by xoxys** [go-gitea/gitea#2012]
Hi,
would it be possible to add an option so that an administrator can create individual legal notice and privacy policy pages? For some gitea instances which are used in a public environment it would be very helpful (in some countries it is even necessary). Also it is a nice feature for all users of a web service to provide informations about the carrier and the current privacy policy.

**Comment by i5heu** [comment]
Is there at least a config parameter to add links to an legal page?
I don't want to edit files in the Docker container.

**Comment by i5heu** [comment]
Its currently possible to add an link at the footer and an public lagel notice html

Its not pretty but gets the job done

https://docs.gitea.io/en-us/customizing-gitea/

**Comment by xoxys** [comment]
Works for me. Thanks
