### ISSUE TITLE
Why is logging in to the try.gitea.io homepage very slow

### ISSUE THREAD

**Issue by tyroneyeh** [go-gitea/gitea#20129]
### Description

as title

### Gitea Version

1.18.0+dev-33-g97bfabc74

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

<img width="521" alt="image" src="https://user-images.githubusercontent.com/1255041/175764043-4382c770-cac0-4a8f-9826-7a9466f72bc4.png">

### How are you running Gitea?

In try.gitea.io

**Comment by wenmingtang** [comment]
yes, very low.

**Comment by tyroneyeh** [comment]
Strange, the home page will get stuck after logging in. If I log in to explore, it's fine, but I can't go to the home page.

**Comment by zeripath** [comment]
Unfortunately it appears that the new indexes on the action table are bad for big SQLite DBs. 

I've been able to correctly ascertain what they should be and will make a PR as soon as I have checked them on MySQL and other dbs.
