### ISSUE TITLE
Copy and paste the images has list legend

### ISSUE THREAD

**Issue by tyroneyeh** [go-gitea/gitea#20130]
### Feature Description

At the moment, the pasted image in the issue content doesn't appear in the file list below (dropzone).

It's better to make the pasted image added into the file list legend below as the general upload file.

### Screenshots

<img width="852" alt="image" src="https://user-images.githubusercontent.com/1255041/175764559-b70895b0-8422-487b-ab63-344b86e28432.png">

**Comment by wxiaoguang** [comment]
Instead of mention someone, I think it's better to make an issue more open, there may be more people interested  in it.

**Comment by tyroneyeh** [comment]
Sorry :(

**Comment by wxiaoguang** [comment]
nvm, I will update the comment to make it more open, and hide some unrelated comments 😊
