### ISSUE TITLE
Don't show mail-notification settings when ENABLE_NOTIFY_MAIL is false

### ISSUE THREAD

**Issue by uriesk** [go-gitea/gitea#20131]
### Description

I wasted time playing with mail-notification settings in the profile and adding / removing mail addresses.
Till i realized that there is a ENABLE_NOTIFY_MAIL setting, which is false per default.

I think the mail notification setting in the profile should not be available (grayed out), or there should be some
`"Mail notifications are disabled by the Administration"` or any other hint making it obvious that it is not available.

### Screenshots

<img width="871" alt="Screenshot_20220625_111716" src="https://user-images.githubusercontent.com/13338250/175767852-c3cc1619-077d-4733-a2ea-2b64b646d3b0.png">

### Gitea Version

1.17.0-rc1

### Can you reproduce the bug on the Gitea demo site?

Yes

### Browser Version

Brave 1.40.105 Chromium: 103.0.5060.53

**Comment by Francewhoa** [comment]
This is another example of a user struggling with notification at https://discourse.gitea.io/u/JVC-MSF

I believe that @uriesk's suggestions above would resolve this challenge
