### ISSUE TITLE
Unnecessary horizontal scrollbar arrows on Firefox

### ISSUE THREAD

**Issue by jpraet** [go-gitea/gitea#20139]
### Description

On Firefox, some pages show unnecessary horizontal scrollbar arrows. This does not happen on Chrome.

### Screenshots

**Firefox:**

![image](https://user-images.githubusercontent.com/2212615/175814100-70c36970-d2bb-4b66-827c-3d2b8cbfd8e2.png)

![image](https://user-images.githubusercontent.com/2212615/175814229-01f98743-80b5-4311-84d5-598a6b5612d0.png)

**Chrome:**

![image](https://user-images.githubusercontent.com/2212615/175814130-06b035e1-b970-4847-a196-20a0a90bb08f.png)

![image](https://user-images.githubusercontent.com/2212615/175814282-ac08f662-5f53-402e-b888-b7eabdeb06d1.png)

### Gitea Version

1.18.0+dev-37-g711cbcce8

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

Windows 10 21H2

### Browser Version

101.0.1

**Comment by wxiaoguang** [comment]
I also use Firefox a lot , can not reproduce it at the moment .... do you have any clue?

<img width="1414" alt="image" src="https://user-images.githubusercontent.com/2114189/175816905-1df022f9-ef8e-43c1-bd79-34e79d20c5d3.png">

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/2114189/175816942-9f43cf37-b8bf-4948-8637-bb199bc07781.png">

**Comment by jpraet** [comment]
Etzelia also reported it on discord #general some time ago. Maybe different Firefox version, or OS?

**Comment by KN4CK3R** [comment]
I noticed that problem too. Firefox 101.0.1 on Windows

**Comment by KN4CK3R** [comment]
Looked into it and it's caused by `overflow-x: scroll;` from #19945 @Gusted

**Comment by Gusted** [comment]
I'm on Linux, no issue. It could be on windows that when `overflow-x: scroll` is specified it will unconditionally show a scrollbar? But that's quite stupid. Could you try adjusting it to `overflow-x: auto;`? That might help, as that should be more "dynamic".

**Comment by KN4CK3R** [comment]
Yep, works with `auto`.

**Comment by delvh** [comment]
There is a display difference between Firefox on Linux and Windows?
That would at least explain why both @Gusted and me did not notice any problem with it...

**Comment by Gusted** [comment]
> There is a display difference between Firefox on Linux and Windows?

Yeah browsers tend to do that(historical reasons). Ah well, luckily that doesn't beat me and `auto` works. I will get up a patch.

**Comment by Gusted** [comment]
https://github.com/go-gitea/gitea/pull/20142 and backport lives at #20143
