### ISSUE TITLE
Wiki overview of pages is loading slowly

### ISSUE THREAD

**Issue by luwol03** [go-gitea/gitea#20156]
### Description

Yesterday I searched for a example `_Sidebar.md` for the wiki pages, especially how to link to other pages. While doing so I thought Gitea.com may has some wikis with a sidebar and I discovered the following repo: https://gitea.com/henri/wiki/wiki/?action=_pages , but this page is loading very slowly, page: ~11s, template: ~5ms.

### Gitea Version

1.18.0+dev-14-g1e2c2edab

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

![image](https://user-images.githubusercontent.com/60048565/176012859-cdab0ffa-c6a0-408d-b976-3b9e17f6ae35.png)

### How are you running Gitea?

I discovered the bug on https://gitea.com. I guess it's using MySQL as discussed on discord.

### Database

MySQL

**Comment by lunny** [comment]
Obviously for every page in the list, it will invoke a git command below. There are over 100 pages in this list. That's why it's slow.
```
wiki-perf.wiki.git: /usr/local/bin/git -c protocol.version=2 -c uploadpack.allowfilter=true -c uploadpack.allowAnySHA1InWant=true -c credential.helper= -c filter.lfs.required= -c filter.lfs.smudge= -c filter.lfs.clean= log -1 --pretty=format:%H -- Antisemitismus.md
```
