### ISSUE TITLE
Kanban board is not in sync with issues

### ISSUE THREAD

**Issue by ivanvlaho** [go-gitea/gitea#20154]
### Description

Hi,

I installed latest version of Gitea and I tried using kanban board for project. I created default kanban board and opened issue. 

When I created issue it appeared at Uncategorised board. But when I closed issue it didn't automatically moved to done board. Another problem is that issue has only opened and closed status and it is not in sync with kanban board.

I don't know if this is intended behaviour or it is not supported yet. 

Please help!  

### Gitea Version

1.16.8 

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

I installed Gitea following https://docs.gitea.io/en-us/install-with-docker-rootless/

### Database

PostgreSQL

**Comment by noerw** [comment]
This is not implemented, see https://github.com/go-gitea/gitea/issues/14359 for a proposal
