### ISSUE TITLE
git push error

### ISSUE THREAD

**Issue by jiantaozi** [go-gitea/gitea#20160]
### Description

Gitea: Internal error when pushing

### Gitea Version

remotes/origin/release/v1.16

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

none

### Git Version

2.34.1

### Operating System

centos7

### How are you running Gitea?

[git@centos7 t2]$ touch README.md
[git@centos7 t2]$ git init
已初始化空的 Git 仓库于 /home/git/temp/t2/.git/
[git@centos7 t2]$ 
[git@centos7 t2]$ git add README.md
[git@centos7 t2]$ git commit -m "first commit"
[main（根提交） 95def5a] first commit
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 README.md
[git@centos7 t2]$ git remote add origin git@192.168.56.104:gitea/test2.git
[git@centos7 t2]$ git push -u origin master
error: 源引用规格 master 没有匹配
error: 推送一些引用到 '192.168.56.104:gitea/test2.git' 失败
[git@centos7 t2]$ git push -u origin main
Gitea: Internal error
fatal: 无法读取远程仓库。

请确认您有正确的访问权限并且仓库存在。
[git@centos7 t2]$ ssh git@192.168.56.104
PTY allocation request failed on channel 0
Hi there, gitea! You've successfully authenticated with the key named git@centos7, but Gitea does not provide shell access.
If this is unexpected, please log in with password and setup Gitea under another user.
Connection to 192.168.56.104 closed.

### Database

mysql

**Comment by wxiaoguang** [comment]
A similar answer from discord (thanks to justusbunsi):

> Wild guess: either remote config for local clone is incorrect (which doesn't explain working pull) or maybe read-only permissions on Gitea side for this repo.

I also think it's the similar reason. Check you repo's permission in Gitea. Or provide more logs.
