### ISSUE TITLE
Question: Is it possible to sponsor specific features?

### ISSUE THREAD

**Issue by bjadamson** [go-gitea/gitea#20168]
### Feature Description

Hi, I just want to start out by saying we love gitea! We started using it a few months ago and it is amazing software. Since we started using it more, we found a few small features/qol improvements that we'd like to see implemented. Do you have a history of allowing people to sponsor specific features / bug fixes? I read through the contributions page and didn't see this explicitly mentioned either way. 

Thanks!

**Comment by lunny** [comment]
You can also sponsor some issues via bountysource

**Comment by jolheiser** [comment]
Closing this per above answers.
