### ISSUE TITLE
Highlight/mark tags and branches in commit view

### ISSUE THREAD

**Issue by warped-rudi** [go-gitea/gitea#20167]
### Feature Description

When showing the list of commits, it would be nice to have a sign/mark indicating when a given commit matches a tag or branch. I have not seen this in any git GUI, however newer command line version do this.

### Screenshots

![view-tags](https://user-images.githubusercontent.com/912371/176182994-427bba0b-638d-47e2-b931-5dc9f09456d2.PNG)

**Comment by lunny** [comment]
Since Gitea commits has a different UI, I couldn't find a suitable place to put the tag name in #24283

**Comment by KazzmanK** [comment]
Just a reminder for nice feature

**Comment by lunny** [comment]
I think since now all tags have been stored in database `release` table. It can be query and store to cache and display in the UI.

**Comment by lunny** [comment]
Duplicated of #10036 and should be fixed by #31082
