### ISSUE TITLE
setting ALLOWED_HOST_LIST for containerized Gitea app

### ISSUE THREAD

**Issue by sw-alpha-romeo** [go-gitea/gitea#20163]
### Description

Hi,
  I deployed and running Gitea as docker container. From web console I configured webhook (**webhook link is an api endpoint running on same host as Gitea docker container**) and on testing the webhook using "Test Delivery" option I get below in response. 
  "http://localhost:8079/webhook/automation/push": dial tcp 127.0.0.1:8079: webhook can only call allowed HTTP servers (check your webhook.ALLOWED_HOST_LIST setting), deny 'localhost(127.0.0.1:8079)'
  
  Where can I find how to set the value of `ALLOWED_HOST_LIST` for containerized Gitea app.

Thanks in advance

### Gitea Version

latest

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

Gitea docker image using docker compose

### Database

SQLite

**Comment by wxiaoguang** [comment]
In documents

Or in google "gitea webhook.ALLOWED_HOST_LIST"

**Comment by wxiaoguang** [comment]
And : https://docs.gitea.io/en-us/install-with-docker/#customization

**Comment by landashu** [comment]
I am not a docker installation, but the webhook test prompts me to check your ` webhook ALLOWED_ HOST_ List setting `, I should be in the app Which location of ini is configured? In [server]? Or in [service]?

**Comment by landashu** [comment]
I know, I need my own home in app Add the following to the INI file:
`
[webhook]
ALLOWED_HOST_List=private,*
`
