### ISSUE TITLE
docker rootless homedir not writeable

### ISSUE THREAD

**Issue by FredFoo** [go-gitea/gitea#20162]
### Description

When I try to run docker rootless I get this:
```
user@machine-a1$ docker run --rm --name gitea-t1 --hostname gitea-t1 -v git-data:/var/lib/gitea -v git-etc:/etc/gitea gitea/gitea:latest-rootless
/var/lib/gitea/git is not writable
docker setup failed
```
If I do it manually, I can do this:
```
user@machine-a1$ docker run -it --rm --name gitea-t1 --hostname gitea-t1 --entrypoint /bin/bash -v git-data:/var/lib/gitea -v git-etc:/etc/gitea gitea/gitea:latest-rootless
bash-5.1$ ls -l /var/lib/gitea
total 0
drwx------    1 git      git             34 Jun 28 08:31 git
bash-5.1$ echo $HOME
/var/lib/gitea/git
bash-5.1$ if [ ! -w ${HOME} ]; then echo "${HOME} is not writable";fi
/var/lib/gitea/git is not writable
bash-5.1$ touch $HOME/test
bash-5.1$ ls -l $HOME
total 0
-rw-r--r--    1 git      git              0 Jun 28 08:31 test
```
Seems to me that ! -w $HOME always returns true and the setup script exits in line 5. If I manually create a file it seems to me quite writeable indeed.

And why is gitea:latest-rootless an rc1? Should latest not be the latest stable release?

### Gitea Version

Gitea version 1.17.0+rc1 built with GNU Make 4.3, go1.18.3 : bindata, timetzdata, sqlite, sqlite_unlock_notify

**Comment by FredFoo** [comment]
Just tried gitea:1.16-rootless and it works fine!
```
bash-5.1$ if [ ! -w ${HOME} ]; then echo "${HOME} is not writable";fi
bash-5.1$
```

**Comment by FredFoo** [comment]
Docker on prod is indeed 19.10, which I cannot touch. Tested with 20.10.17 and it works. Good guess :) 

I will stick with 1.16 anyways and revisit when 1.17 is released.

**Comment by alorence** [comment]
I fight against this particular issue for hours now, while my Docker version is already up-to-date (20.10.17).
Updating the CentOS system with `yum update` shown the following issue:
```
Warning: RPMDB altered outside of yum.
** Found 1 pre-existing rpmdb problem(s), 'yum check' output follows:
3:docker-ce-20.10.17-3.el7.x86_64 has missing requires of containerd.io >= ('0', '1.4.1', None)
```

The command updated package `containerd.io` from 1.3.9 to 1.6.7, which solved the issue.

Thanks for the tip !
