### ISSUE TITLE
For containerised Gitea, ALLOWED_HOST_LIST value is not working as expected

### ISSUE THREAD

**Issue by sw-alpha-romeo** [go-gitea/gitea#20164]
### Description

Hi,
   I am havinga VM, on this VM I deployed containerized Gitea app and a standalone API service . I set the value of **ALLOWED_HOST_LIST** as **private** (_also tried by setting *_). Then I configured web hook for my repository, the web hook uri is the end point of standalone API service which is running in same VM. Then i tried to test the web hook by clicking "Test Delivery" option, it resulted into failed action. The response of "Test Delivery" was as below
   
_Delivery: Post "http://10.0.0.24:8079/webhook/automation/push": dial tcp 10.0.0.24:8079: webhook can only call allowed HTTP servers (check your webhook.ALLOWED_HOST_LIST setting), deny '10.0.0.24(10.0.0.24:8079)'_

_I did tested the connectivity from Gitea app container to API service end point by running curl -v telnet://10.0.0.24:8079/ from inside the Gitea container, telnet got connected._

Note :- 10.0.0.24 IP is the Virtual Machine IP on which the Gitea container and standalone API service is running.

app.ini for Gitea Container at /data/gitea/conf/app.ini, has the value of ALLOWED_HOST_LIST as below
ALLOWED_HOST_LIST             = private

### Gitea Version

latest

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

latest

### Operating System

linux

### How are you running Gitea?

Gitea as containerized app

### Database

SQLite

**Comment by wxiaoguang** [comment]
Make sure you have put the options in correct sections. Or please paste the full app.ini to check.
