### ISSUE TITLE
Webhook creation using gitea api not resulting in proper setup of webhook

### ISSUE THREAD

**Issue by k-p-ani** [go-gitea/gitea#20178]
### Description

Hi,
   I am trying to setup webhook using gitea api. below is the sample curl. I set that, this webhook must be triggered only for PUSH EVENTS (by setting **events** of type **push_only**). After execution of curl, when I check webhook tab in settings, I can see that webhook does gets created but, the event selected is as **custom** (not push )and under custom no event type is selected.

curl --location --request POST 'http://host/api/v1/repos<MY-USER>/<MY_REPO>/hooks' \
--header 'Content-Type: application/json' \
--user '<MY-USER>:<MY-PASSWORD>' \
--header 'Content-Type: application/json' \
--data-raw '{
  "active": true,
  "branch_filter": "*",
  "config": {
    "content_type": "json",
    "url": "http://repositories/2222",
    "http_method": "post"
  },
  "**events**": [
    "**push_only**"
  ],
  "type": "gitea"
}'

Thanks 

### Gitea Version

latest

### Can you reproduce the bug on the Gitea demo site?

Yes

### Git Version

latest

### Operating System

ubuntu

### How are you running Gitea?

containerised Gitea app

**Comment by jolheiser** [comment]
It appears the webhook API always chooses custom events, and the correct hook event is just `push`.
I'm going to close this, as they should be functionally the same.
