### ISSUE TITLE
Issue List Page Size

### ISSUE THREAD

**Issue by thigg** [go-gitea/gitea#20184]
### Feature Description

It would be nice if the list under Repo->Issues would either load dynamically more pages when scrolling down, or the default page size would be a bit higher or configurable. 

10 is quite annoying if you search for something, especially as search only matches full words.

**Comment by wxiaoguang** [comment]
https://github.com/go-gitea/gitea/blob/main/custom/conf/app.example.ini

```
;; Number of issues that are displayed on one page
;ISSUE_PAGING_NUM = 10
```

while I think the default value should be larger. 10 is too small indeed.
