### ISSUE TITLE
`dump-repo` command is somewhat dangerous: removing the data directory if failed.

### ISSUE THREAD

**Issue by wxiaoguang** [go-gitea/gitea#20191]
DumpRepository -> migrateRepository -> uploader.Rollback -> os.RemoveAll(g.baseDir)

If migrateRepository returns error, then the data directory is removed completely.

I have run `gitea dump-repo` in the gitea directory, then the Gitea's data directory (including sqlite database, repositories) is removed, all lost (luckily not on production).

**Comment by a1012112796** [comment]
looks it's beter make sure the `repo_dir` is empty before `dump-repo`
