### ISSUE TITLE
Allowing only single fork per user/organization

### ISSUE THREAD

**Issue by lafriks** [go-gitea/gitea#2019]
I think we should allow only single fork for every user/organization from single repository. At least I don't see point of having multiple forks for each user and PR anyway does not work with multiple forks for one user because of url limitation. It could be also source of bad practice that users are creating new forks just for PR instead of normal workflow with new branches.

GitHub also does allow only single fork, just as GitLab.  

If that's seem ok, I could create PR for this.

**Comment by lunny** [comment]
@lafriks please do it.

**Comment by lunny** [comment]
Let's move this to v1.3 at first

**Comment by lafriks** [comment]
Yes

**Comment by lunny** [comment]
resolved by #2193

**Comment by bard** [comment]
Does this also make it impossible for an individual user to fork a project to multiple organizations?

I described a scenario where that is needed at https://github.com/gogits/gogs/issues/1791#issuecomment-278899979, switched to Gitea because it implemented the feature as noted by @lunny at https://github.com/gogits/gogs/issues/1791#issuecomment-278905982, and am currently using it.

**Comment by lunny** [comment]
Yes, I think @bard is right. @lafriks, user cannot fork him repo to an organization now.

**Comment by bard** [comment]
Any chance of the fork-to-organization capability staying? I'm using this workflow, if future releases containing #2193 aren't allowing it I should start figuring out a migration path...

**Comment by lunny** [comment]
I think we will fix this at some time.

**Comment by rossberg** [comment]
Is there any chance that this change can be reverted? It is breaking the proposal workflow we have defined for WebAssembly, where the org creates and iterates on each proposal by creating a fork of the spec repo (the advantage over a branch being that github.io can easily host a modified version of the spec documents per proposal, and that the main repo isn't spammed with commit notifications).

Currently we need to manually copy repos and merge proposals, which seems silly and unnecessary.
