### ISSUE TITLE
gitea branch button disappears and is missing

### ISSUE THREAD

**Issue by oDinZu** [go-gitea/gitea#20204]
### Description

I was browsing another Gitea and seen they had the branches drop-down button. 

I don't remember if I ever had this button; I thought it was a Gitea UI difference from GitHub.

On refresh, I see the button load in, but it disappears.

### Screenshots

![image](https://user-images.githubusercontent.com/18726788/176982248-5fe8afc5-4d19-44e2-b53b-686de94a3281.png)

### Gitea Version

     1.16.6 built with GNU Make 4.1, go1.18.1 : bindata, sqlite, sqlite_unlock_notify

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

Ubuntu 21.04

### Browser Version

FF 101.0.1 (64-bit)

**Comment by wxiaoguang** [comment]
If JS doesn't execute correctly, the button might disappear.

A similar issue:
* https://github.com/go-gitea/gitea/issues/19851

**Comment by wxiaoguang** [comment]
Feel free to reopen or report new issues.
