### ISSUE TITLE
Can't assign users to issues

### ISSUE THREAD

**Issue by schmittlauch** [go-gitea/gitea#2021]
- Gitea version (or commit ref): 1.1.2
- Git version: 2.12.3
- Operating system: openSUSE (Linux)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes https://try.gitea.io/schmittlauch/foobar2342/issues/1
  - [ ] No
  - [ ] Not relevant
- Log gist: https://gist.github.com/schmittlauch/38db2a9440306334d17e03d965d7fcbc

## Description

It's not possible to assign users to issues (both other users and one self) on my gitea instance. When clicking on a user to assign, the page just reloads but afterwards still no one is assigned.
I also was able to reproduce this issue on try.gitea.io so it's probably not only my instance.

In my logs the only SQL `UPDATE` statement is setting `issue_user.is_read` to true. All other SQL statements are just SELECT statements. So it looks like the assignment is never saved.

**If this issue involves the Web Interface, please include a screenshot**

**Comment by schmittlauch** [comment]
Uuhh... It works with a fresh firefox profile. Probably my Firefox profile is the issue. Closing this until I find out more.

**Comment by schmittlauch** [comment]
Seems to be caused by the Firefox add-ons "Privacy Badger" and "Foxy Proxy Standard edition". if only one of these add-ons are active, the issue appears.

**Comment by schmittlauch** [comment]
How is the assigning feature implemented? Because all the Firefox addons *Disconnect*, *PrivacyBadger*, and *FoxyProxy Standard Edition* are breaking it.

Either all these add-ons are doing something wrong or gitea is using code here seen as problematic by anti-tracking add-ons.

**Comment by sondr3** [comment]
This is a duplicate of #1271.
