### ISSUE TITLE
Wrong PR URL shown for complex repo structure when branch is pushed

### ISSUE THREAD

**Issue by flozzone** [go-gitea/gitea#20228]
### Description

We have a quite complex repository structure for a open-source project specialization, which allows downstream merges and contributions by a private company with separation of users and privileges. 

This works very well in sense of code and user organization, but is not fully supported by Gitea. I've already submitted a issue regarding this structure, but for another bug (see issue #14921). 

The following bug was identified already quite some time ago, but I didn't manage it to report it here.

# The bug

## Organization and repository structure

* Private mirror repository of a public open-source project https://github.com/DSpace/DSpace under a 4Science organization -> 4science/DSpace
* Private fork repository of 4science/DSpace in our organization -> OurOrg/DSpace
* Private fork of our repository from OurOrg/DSpace for special implementations for the 4Science team -> 4science/OurOrgDSpace
** For this fork to work I had to first create the fork under my private user and then changing owner to 4science (created separate issue for this #20229)

## Steps to reproduce

* Create a repository structure like described above
* Create a feature branch and push it to OurOrg/DSpace

## Actual result

While pushing the console shows the URL for the PR to create, but it targets the mirrored repository 4science/DSpace

https://git.our.org/4science/DSpace/compare/dspace-5_x_x-cris...OurOrg:feature-branch

## Expected result

The PR URL should open the PR creation page and target the default branch (next) in OurOrg/DSpace repository, like:

https://git.our.org/OurOrg/DSpace/compare/next...feature-branch

# Reproduce on Gitea demo site

I've prepared this repository structure on your Gitea demo site:

* Mirrored repository is https://github.com/rtyley/small-test-repo, just to keep the example small
* Mirrored repository https://try.gitea.io/4science/DSpace
* Own specialization https://try.gitea.io/OurOrg/DSpace
* Specialization fork for the creator for custom payed features https://try.gitea.io/4science/OurOrgDSpace

## Steps to reproduce

```shell
➜  /tmp git clone git@try.gitea.io:OurOrg/DSpace.git                                                                                                                                                                              
Cloning into 'DSpace'...
remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 6 (delta 0), reused 6 (delta 0), pack-reused 0
Receiving objects: 100% (6/6), done.
➜  DSpace git:(master) git checkout -b feature origin/master                                                                                                                                                                      
Branch 'feature' set up to track remote branch 'master' from 'origin'.
Switched to a new branch 'feature'
➜  DSpace git:(feature) echo feature > feature                                                                                                                                                                                    
➜  DSpace git:(feature) ✗ git add feature                                                                                                                                                                                         
➜  DSpace git:(feature) ✗ git commit -m feature                                                                                                                                                                                   
[feature 321e9fe] feature
 1 file changed, 1 insertion(+)
 create mode 100644 feature
➜  DSpace git:(feature) git push origin feature                                                                                                                                                                                   
Enumerating objects: 4, done.
Counting objects: 100% (4/4), done.
Delta compression using up to 8 threads
Compressing objects: 100% (2/2), done.
Writing objects: 100% (3/3), 285 bytes | 285.00 KiB/s, done.
Total 3 (delta 0), reused 0 (delta 0), pack-reused 0
remote: 
remote: Create a new pull request for 'OurOrg:feature':
remote:   https://try.gitea.io/4science/DSpace/compare/master...OurOrg:feature
remote: 
remote: . Processing 1 references
remote: Processed 1 references in total
To try.gitea.io:OurOrg/DSpace.git
 * [new branch]      feature -> feature
➜  DSpace git:(feature)
```

Result: https://try.gitea.io/4science/DSpace/compare/master...OurOrg:feature is shown, where it should actually show https://try.gitea.io/OurOrg/DSpace/compare/master...feature

### Gitea Version

1.16.8

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

Centos 7

### How are you running Gitea?

Official docker container extended with custom config as plain docker with apache reverse proxy for SSL termination.

### Database

PostgreSQL

**Comment by Gusted** [comment]
I had a close look into the code and the thought behind it, but the code and message is correct here. Pushing to a forked repository is in Gitea's eyes a way to make contributions to the original repository, so therefor it helps by displaying the URL to make the PR on the original repository.

**Comment by lunny** [comment]
Or we can put two URLs there, one is to original repository and another is to parent fork repository if they are not the same.

**Comment by flozzone** [comment]
@Gusted ok sounds reasonable, @lunny would be a great idea to provide a solution for different use cases.

The think is that the shown link https://try.gitea.io/4science/DSpace/compare/master...OurOrg:feature targets the PR to the mirrored repository, which in fact is a repository where no commits should be merged, because its just a mirror. For me this means that the shown link makes no sense at all. But this is true just for this specific use case.

If I think further, then in this case it would be enough if we would check if the original repository of a forked one is a mirror. If its a mirror show the link to the forked repository and if its normal repository then show the PR link to the normal original repository.

Nevertheless I will check GitHubs behavior for these cases and report here.

**Comment by flozzone** [comment]
So I imported https://stash.kopano.io/scm/~bhuisman/kopano-webapp.git to a new test organization https://github.com/github-org-test-for-gitea-20228/github-mirror-test and forked it to my personal account https://github.com/flozzone/github-mirror-test-fork and pushed a feature branch to it.

```shell
➜  /tmp git clone git@github.com:flozzone/github-mirror-test-fork.git
Cloning into 'github-mirror-test-fork'...
remote: Enumerating objects: 41256, done.
remote: Total 41256 (delta 0), reused 0 (delta 0), pack-reused 41256
Receiving objects: 100% (41256/41256), 47.65 MiB | 8.14 MiB/s, done.
Resolving deltas: 100% (24099/24099), done.
➜  cd github-mirror-test-fork
➜  github-mirror-test-fork git:(master) git checkout -b feature origin/master
Branch 'feature' set up to track remote branch 'master' from 'origin'.
Switched to a new branch 'feature'
➜  github-mirror-test-fork git:(feature) echo "feature" > feature
➜  github-mirror-test-fork git:(feature) ✗ git add feature
➜  github-mirror-test-fork git:(feature) ✗ git commit -m "this is a feature"
[feature 11e331d9] this is a feature
 1 file changed, 1 insertion(+)
 create mode 100644 feature
➜  github-mirror-test-fork git:(feature) git push origin feature
Enumerating objects: 4, done.
Counting objects: 100% (4/4), done.
Delta compression using up to 8 threads
Compressing objects: 100% (2/2), done.
Writing objects: 100% (3/3), 288 bytes | 288.00 KiB/s, done.
Total 3 (delta 1), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (1/1), completed with 1 local object.
remote: 
remote: Create a pull request for 'feature' on GitHub by visiting:
remote:      https://github.com/flozzone/github-mirror-test-fork/pull/new/feature
remote: 
To github.com:flozzone/github-mirror-test-fork.git
 * [new branch]        feature -> feature
 ```
 
This proves that GitHub shows the link to my forked repository https://github.com/flozzone/github-mirror-test-fork/pull/new/feature instead to the mirror and since I am pretty sure it would otherwise show the original repositories PR URL it seems that Githubs behavior in this case is reflecting the idea I described above.

**Comment by Gusted** [comment]
> This proves that GitHub shows the link to my forked repository https://github.com/flozzone/github-mirror-test-fork/pull/new/feature instead to the mirror and since I am pretty sure it would otherwise show the original repositories PR URL it seems that Githubs behavior in this case is reflecting the idea I described above.

Github isn't. If you follow the link, you will be redirected to:

https://github.com/github-org-test-for-gitea-20228/github-mirror-test/compare/master...flozzone:github-mirror-test-fork:feature?expand=1

Which is the same behavior as Gitea currently has, just with extra steps. Having a fork and pushing to that is in 99% of the cases meaning that you want to contribute to the original repository and not having it act as it's own repository.

**Comment by Gusted** [comment]
So the issue is, you're expecting that Gitea assume a forked repository has no relation to the original repository, while we actually are. In these kind of cases I would say "Oh let's make a option for this" but this is such a small edge case that there isn't _really_ a benefit in my opinion. The best way to fix this is to not use the fork functionality and instead create the organization's repo as its own.

**Comment by flozzone** [comment]
I see the point and I just didn't test this on GitHub before and haven't thought it would be possible to create a PR against a mirror. Therefore I wouldn't be disappointed if you close this one.
