### ISSUE TITLE
Invalid syntax error when pushing

### ISSUE THREAD

**Issue by mangkang** [go-gitea/gitea#2022]
- Gitea version (or commit ref): 1.1.2
- Git version: 2.11.0
- Operating system: OS X Client / Ubuntu 64 Server
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ X] Not relevant
- Log gist:

Hi, I am experiencing an unexpected error when pushing to Gitea from local to remote. 
This seems to be related to a commit comment. There is no other error in the server log files.

The client side error in red is:

remote: 2017/06/20 21:58:55 [...tea/models/update.go:147 PushUpdate()] [E] updateIssuesCommit: strconv.ParseInt: parsing "ITOM-9100": invalid syntax

$ git push
Counting objects: 469427, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (123252/123252), done.
Writing objects: 100% (469427/469427), 120.48 MiB | 556.00 KiB/s, done.
Total 469427 (delta 299793), reused 441750 (delta 272388)
remote: 2017/06/20 21:58:55 [...tea/models/update.go:147 PushUpdate()] [E] updateIssuesCommit: strconv.ParseInt: parsing "ITOM-9100": invalid syntax
To https://172.30.47.164:3000/abc/repo1
 * [new branch]            master -> master

Thanks,

MK

**Comment by lafriks** [comment]
can you give exact commit message?

**Comment by mangkang** [comment]
Here are the two commit messages with that string pattern:

1)
#ITOM-9100 i.e To reflect availability changes done to fix status Report\n\ngit-svn-id: https://svn501.myhost.com/svn/itom/trunk@42563 86a4919b-b3e0-4e62-bec7-4511e7be0dea\n

2)
#[JIRA] (ITOM-9100) Enhanced the availability discrepancy utility to the the new availability changes
git-svn-id: https://svn501.myhost.com/svn/itom/trunk@41971 86a4919b-b3e0-4e62-bec7-4511e7be0dea
