### ISSUE TITLE
[Summary] Go to file (Find files in repo) optimization

### ISSUE THREAD

**Issue by wxiaoguang** [go-gitea/gitea#20231]
Follow:

* https://github.com/go-gitea/gitea/pull/15028

TODO:

* [x] Optimize the performance. should have been improved by #21368
* [x] ~~Use a config option to disable this feature if some users do not like it.~~ not needed anymore.
* [x] Use weighted algorithm for string matching. https://github.com/go-gitea/gitea/pull/21370
    * When a user searches `word`, they may want to see `/{word}.txt` before `/{w}e-g{o}t-{r}esult.{d}at`

**Comment by lunny** [comment]
For the find files, we have two ways to optimize. One is cache all the file paths, another is to use a backend search rather than frontend search or both.

**Comment by lunny** [comment]
Both are not easy, so for 1.17, a configuration to allow users disable it is a quick patch.

**Comment by wxiaoguang** [comment]
This feature is not the slowest one, and not the most urgent one to be optimized.

There are already a lot of slow handlers in Gitea.

For example, for the same repo:

```
$ time curl https://gitea.com/.../.../commits/branch/master/..../.... > /dev/null
curl 0.02s user 0.03s system 0% cpu 56.408 total

$ time curl https://gitea.com/.../.../tree-list/branch/master > /dev/null
curl  0.05s user 0.02s system 0% cpu 19.313 total
```

Fixing a not-slowest handler won't really help the situation.

**Comment by wxiaoguang** [comment]
--> Refactor parseTreeEntries, speed up tree list #21368

**Comment by wxiaoguang** [comment]
-->  Use weighted algorithm for string matching when finding files in repo #21370 

Then this issue could be closed as completed.

**Comment by wxiaoguang** [comment]
All done
