### ISSUE TITLE
translation error

### ISSUE THREAD

**Issue by zxyao145** [go-gitea/gitea#20248]
### Description

~~请看截图，这里是否应该使用“保存“比较好？~~

edit: by google translate: Please look at the screenshot, should it be better to use "Save" here?

### Gitea Version

1.16.8

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![image](https://user-images.githubusercontent.com/24973084/177321043-0f817b09-52be-4f91-9639-b3b9f23c856a.png)

### Git Version

2.8

### Operating System

docker

### How are you running Gitea?

docker

### Database

PostgreSQL

**Comment by zxyao145** [comment]
> 1. I don't understand what you want to say as I can't speak Chinese.
> 2. If my guess of the content of your issue is correct, you want to say "The translation is incorrect", right?
> 3. Our translations are managed by [Crowdin](https://crowdin.com/project/gitea) and are updated from there automatically.
>    You can create an account there, and update the corresponding text yourself.
>    You should be able to find it by searching for the current text.

Yes, I think the translation is unreasonable and not well understood in Chinese.

 I'll go to crowdIn, thank you!

**Comment by wxiaoguang** [comment]
For more inforamtion: "保护" is correct here. It comes from "protect branch"

**Comment by zxyao145** [comment]
> For more inforamtion: "保护" is correct here. It comes from "protect branch"

It's hard for me to understand why it's "Protect Tag", not "Save Tag".


![image](https://user-images.githubusercontent.com/24973084/177324036-d6e4da3f-8c32-4c27-8ef1-35a5855c00df.png)

**Comment by wxiaoguang** [comment]
Hmm ... maybe for most people, "Protect something" seems more intuitive, the text means the action. "Save" is too general, and no tag is saved indeed.

I still prefer to keep the word "Protect", and I think many people also prefer it (since the text and translations are there for many years).

**Comment by zxyao145** [comment]
> Hmm ... maybe for most people, "Protect something" seems more intuitive, the text means the action. "Save" is too general, and no tag is saved indeed.
> 
> I still prefer to keep the word "Protect", and I think many people also prefer it (since the text and translations are there for many years).

Maybe I misunderstood. Here is the Git tag, not the label of issue
