### ISSUE TITLE
fix for mobile view messed up non-mobile view

### ISSUE THREAD

**Issue by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [go-gitea/gitea#20245]
the fix of https://github.com/go-gitea/gitea/pull/20236 does indeed hide the "non-mobile" bell in the mobile view (as it's supposed to), however, the bell in my "non-mobile" toolbar got a little messed up as a result.

you can see in the picture that it's positioned a little above the toolbar centerline, compared to surrounding elements.

pic:
![image](https://user-images.githubusercontent.com/61180606/177309132-0ff27b07-348d-4cb1-9894-5228c4b04617.png)

_Originally posted by @wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf in https://github.com/go-gitea/gitea/pull/20236#pullrequestreview-1028415075_

**Comment by tyroneyeh** [comment]
Can in try.gitea.io duplication it?

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
> Can in try.gitea.io duplication it?

just tried, I cannot reproduce there. are you sure it isn't returning a cached version of the toolbar?

**Comment by zeripath** [comment]
I'm not able to reproduce this on firefox or on chrome on try or on a dev main build.

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
> I'm not able to reproduce this on firefox or on chrome on try or on a dev main build.

must be an issue with my tmpl (I have integrated latest changes but perhaps left something there when I shouldn't have), let me check.

**Comment by zeripath** [comment]
> I'm not able to reproduce this on firefox or on chrome on try or on a dev main build.

I should note I have been able to reproduce it - but it's more subtle on my default font than it is for @wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf
