### ISSUE TITLE
Gitea does not pick custom themes

### ISSUE THREAD

**Issue by akr2002** [go-gitea/gitea#20259]
### Description

I am placing them in `custom/public/assets/css`. Selecting custom theme just uses the default gitea light theme

### Gitea Version

1.16.3

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![image](https://user-images.githubusercontent.com/21287366/177398339-4d2a229f-01c9-4ba6-a66a-cfe1abdbecd6.png)
Clearly, it uses the default light theme

### Operating System

Debian GNU/Linux 11 (bullseye)

### How are you running Gitea?

Installed by following https://docs.gitea.io/en-us/install-from-binary/
Running Gitea natively (no docker). 
This is how systemd starts gitea: `ExecStart=/usr/local/bin/gitea web --custom-path /var/lib/gitea/custom --config /etc/gitea/app.ini`

### Database

PostgreSQL

**Comment by techknowlogick** [comment]
Have you added the theme to the list of possible themes to choose from in config: https://docs.gitea.io/en-us/config-cheat-sheet/#ui-ui ?

I will close this ticket but please hop into chat or our forum to discuss if that doesn't indeed work.

**Comment by GNUxeava** [comment]
no thanks, you can mark as 'wontfix'

i'll update gitea. If it still doesn't work, I'll switch to Codeberg
