### ISSUE TITLE
WebHooks: branch filter for push/pull request notifications

### ISSUE THREAD

**Issue by Avalancs** [go-gitea/gitea#2025]
I would like to notify Jenkins when there is a new push, or accepted pull request to the master branch, so it can be built and deployed for testing.
I could trigger the build without the use of the [Gogs webhook plugin](https://wiki.jenkins-ci.org/display/JENKINS/Gogs+Webhook+Plugin ) but the webhook is triggered for any pushes to the repository, not just the master branch.
So I would like to request the ability to create a filter for which branches a webhook should activate.

**Comment by kmadel** [comment]
Perhaps a Gitea Pipeline Multi-branch plugin for Jenkins. So filter from the Jenkins side, rather than the Gitea side. Although that is an interesting concept and one I don't believe GitHub supports.

**Comment by lafriks** [comment]
I think it should be done on gitea side as I would also like to get slack/mattermost notifications only for specific branches

**Comment by lafriks** [comment]
I think it should be done on gitea side as I would also like to get slack/mattermost notifications only for specific branches
