### ISSUE TITLE
Create Tag from Gitea Gui

### ISSUE THREAD

**Issue by christf** [go-gitea/gitea#20265]
### Feature Description

It would be great if it was possible to create git tags from the gui of gitea. Some workflows need this tagging be done after merging a PR. For these, currently users have to drop to cli, git pull, create tag, git push.
Being able to create a tag (similar to bitbucket or github) via gui would simplify this workflow.

**Comment by 42wim** [comment]
@christf like https://github.com/go-gitea/gitea/pull/19362 ?

**Comment by lunny** [comment]
You could do that when you reviewing a commit. You can find some menus there include 
<img width="110" alt="image" src="https://user-images.githubusercontent.com/81045/177679654-fe10b725-0140-4060-b759-feee6d00409a.png">

**Comment by a1012112796** [comment]
see https://github.com/go-gitea/gitea/pull/13467

**Comment by christf** [comment]
thank you for showing me.

Using a UI element meant to switch tags/branches to create new tags does not fee intuitive for me. So much, that I could not find the functionality even after looking for it.
When searching for it, I looked for a button when viewing a specific commit that needed to be tagged.
