### ISSUE TITLE
Webhooks are not triggered in repositories cloned via ssh

### ISSUE THREAD

**Issue by blacklight** [go-gitea/gitea#20284]
### Description

I have a repository with a webhook configured on push events.

The hook is correctly triggered if I click "Test Delivery", and also when the repository is cloned over HTTPS. If I perform code changes from the web view the webhook is also correctly triggered.

However, if I cloned the repo over `git@git.example.com:user/repo.git` and I push some commits, the hook is not triggered at all. No log traces on the target webapp, no log traces on gitea, no log traces on the nginx proxy.

Am I missing some obvious configuration? Are webhooks actually supported when the events are triggered from an ssh-cloned repo, or do I have to use git hooks for this purpose? If so, is there an easy way to map git hooks to web hooks?

### Gitea Version

1.16.8

### Can you reproduce the bug on the Gitea demo site?

N/A

### Git Version

2.37.0

### Operating System

Arch Linux

### How are you running Gitea?

Self-hosted on an Arch Linux server, installed via Arch package.

### Database

PostgreSQL

**Comment by oliverpool** [comment]
What happens when you try to directly open a ssh session?

```
ssh git@git.example.com
```

Do you have access to a shell ? (means that you are not connecting via gitea)
Or do you see the following:
> Hi there! You've successfully authenticated with the key named ..., but Gitea does not provide shell access.

(if it is the former, it means that gitea is not handling the ssh connection, which means that the config must be changed)

**Comment by BlackLight** [comment]
Thanks for the reply @oliverpool:

```
> ssh git@git.platypush.tech
Last login: Tue Jul  5 19:31:08 2022 from 213.93.230.45
fatal: Interactive git shell is not enabled.
hint: ~/git-shell-commands should exist and have read and execute access.
Connection to git.platypush.tech closed.
```

Which should be expected, because I have configured the git user on the system like this:

```
git:x:105:105::/var/lib/gitea/data/gitea-repositories:/usr/bin/git-shell
```

I'm using the `git-shell`, so the user doesn't have a proper shell.

So things should work if I configure bash or another proper shell for the user? Isn't that a security concern though, since it would allow any user with an authorized SSH key to log into the system?

**Comment by oliverpool** [comment]
I think this is not correct. The ssh connection should be handled by gitea (which is not the case here).
https://docs.gitea.io/en-us/faq/#ssh-issues

> If you do not get the above message but still connect, it means your SSH key is not being managed by Gitea. This means hooks won’t run, among other potential problems.

**Comment by BlackLight** [comment]
@oliverpool so what would be the solution? Btw clone/pull/push operations don't seem to be affected. I have also tried to change the git user's shell to /bin/bash. When I do I can login, but hooks still won't run.

**Comment by BlackLight** [comment]
@oliverpool yes I've tried it already. This is my server's configuration:

```ini
APP_NAME = My Git
RUN_USER = git
RUN_MODE = prod

[server]
PROTOCOL         = http
DOMAIN           = git.example.com
HTTP_ADDR        = 127.0.0.1
HTTP_PORT        = 18888
SSH_ROOT_PATH    = /var/lib/gitea/.ssh
LANDING_PAGE     = explore
LFS_JWT_SECRET   = *********
SSH_DOMAIN       = git.example.com
ROOT_URL         = https://git.example.com/
DISABLE_SSH      = false
SSH_PORT         = 22
LFS_START_SERVER = true
LFS_CONTENT_PATH = /var/lib/gitea/data/lfs
OFFLINE_MODE     = false

[database]
DB_TYPE  = postgres
HOST     = 127.0.0.1:5432
NAME     = gitea
USER     = gitea
PASSWD   = ********
LOG_SQL  = false
SCHEMA   =
SSL_MODE = disable
CHARSET  = utf8
PATH     = /var/lib/gitea/data/gitea.db

[security]
INSTALL_LOCK       = true
SECRET_KEY         =
INTERNAL_TOKEN     = *********
PASSWORD_HASH_ALGO = pbkdf2
DISABLE_GIT_HOOKS = false
DISABLE_WEBHOOKS = false
ONLY_ALLOW_PUSH_IF_GITEA_ENVIRONMENT_SET = false

[oauth2]
ENABLE = true

[U2F]
APP_ID =

[log]
MODE      = console
LEVEL     = info
ROUTER    = console
ROOT_PATH = /var/lib/gitea/log

[git]
PATH =

[service]
REGISTER_EMAIL_CONFIRM            = true
ENABLE_NOTIFY_MAIL                = true
DISABLE_REGISTRATION              = false
ALLOW_ONLY_EXTERNAL_REGISTRATION  = false
ENABLE_CAPTCHA                    = true
CAPTCHA_TYPE                      = image
REQUIRE_SIGNIN_VIEW               = false
DEFAULT_KEEP_EMAIL_PRIVATE        = false
DEFAULT_ALLOW_CREATE_ORGANIZATION = true
DEFAULT_ENABLE_TIMETRACKING       = true
NO_REPLY_ADDRESS                  = noreply.localhost

[repository]
ROOT =
DEFAULT_BRANCH = main
ROOT           = /var/lib/gitea/data/gitea-repositories

[indexer]
ISSUE_INDEXER_TYPE     = elastic
ISSUE_INDEXER_CONN_STR = http://127.0.0.1:9200
ISSUE_INDEXER_NAME     = gitea_issues

[queue.issue_indexer]
TYPE        = redis
SET_NAME    = issue_indexer
QUEUE_NAME  = gitea_issue_indexer
CONN_STR    = addrs=127.0.0.1:6379 db=0
WORKERS     = 3
MAX_WORKERS = 5

[webhook]
QUEUE_LENGTH = 10000
DELIVER_TIMEOUT = 10
ALLOWED_HOST_LIST = loopback

[cache]
ENABLED = true
ADAPTER = redis
HOST    = network=tcp,addr=:6379,db=0,pool_size=100,idle_timeout=180

[cache.last_commit]
ENABLED = true

[session]
PROVIDER        = file
PROVIDER_CONFIG = network=tcp,addr=:6379,db=0,pool_size=100,idle_timeout=180

[mirror]
ENABLED = true

[openid]
ENABLE_OPENID_SIGNIN = true
ENABLE_OPENID_SIGNUP = true
```

`sshd_config` contains `UsePAM yes` and no `AllowUsers` filtering is enabled.

**Comment by oliverpool** [comment]
Can you try changing the `gitea` shell using `chsh`: https://github.com/go-gitea/gitea/issues/1454#issuecomment-396881115

```
sudo chsh -s /bin/bash gitea
```

**Comment by oliverpool** [comment]
You can check it beforehand: `getent passwd gitea | cut -d: -f7` https://docs.gitea.io/en-us/faq/#ssh-common-errors

**Comment by BlackLight** [comment]
If I change the user's shell to /bin/bash (the user is `git` in my case, not `gitea`) then I'm able to login to the system over SSH (which is definitely not something I would like):

```
> ssh git@git.platypush.tech
Last login: Fri Jul  8 09:57:14 2022 from xxx.xxx.xxx.xxx
[git@gitter ~]$
```

But hooks don't get triggered yet upon push over SSH.

**Comment by oliverpool** [comment]
https://github.com/go-gitea/gitea/issues/9481#issuecomment-568683443

**Comment by BlackLight** [comment]
Yes that seems to be correct:

```
[git@gitter gitea]$ cat ~/.ssh/authorized_keys
# gitea public key
command="/usr/bin/gitea --config=/etc/gitea/app.ini serv key-1",no-port-forwarding,no-X11-forwarding,no-agent-forwarding,no-pty,no-user-rc,restrict ssh-rsa ......
```

**Comment by oliverpool** [comment]
Then something is wrong with the ssh server, since it doesn't seem to execute the `command` when you login via ssh (otherwise you wouldn't have an unrestricted shell access).

**Comment by BlackLight** [comment]
Hmm what could be wrong with it? If `UsePAM` is enabled then the `command` should be executed right?

**Comment by oliverpool** [comment]
I don't know.

What ssh server are you using ?
Did you restart it after changing the configuration?

If the `command` is not executed, this is likely not a gitea issue. I am not sure I can help you further.
You have to somehow find out, why your `authorized_keys` is not interpreted correctly.

**Comment by BlackLight** [comment]
I may have found the culprit buried deep in my `sshd_config`:

```
Match User git
    PermitEmptyPasswords yes
```

It seems that in one of my previous attempts to get SSH access to work for git I added that line to the configuration. My guess is that it bypassed the PAM authentication when no password was provided, so the `command` was never actually called.

After removing that configuration and resetting the git shell to /bin/bash things seem to work as expected:

```
> ssh git@git.example.com
PTY allocation request failed on channel 0
Hi there, user! You've successfully authenticated with the key named *****, but Gitea does not provide shell access.
If this is unexpected, please log in with password and setup Gitea under another user.
Connection to git.example.com closed.
```
