### ISSUE TITLE
Markdown may eat code blocks following a list

### ISSUE THREAD

**Issue by HermannDppes** [go-gitea/gitea#20324]
### Description

When having a fenced code block in a Markdown file after an empty list item, the entire code block or parts of it may be ignored in the rendered Markdown view of Gitea as if the lines were not present within the Markdown file.

#### Completely vanishing code block

If no lines which are indented at least two spaces are present in the code block, it gets ignored in its entirety. As an example where you'll have to ignore the backslashes I inserted because I'm unable to stack Markdown properly, a file containing
```markdown
*
\```
some code goes here
\```
```
would be rendered identically (as far as my eyes may discern) to a file having
```markdown
*
```
as its only content.

#### Partially vanishing code block

If at least one line is indented at least two spaces, everything up to but not including the first of these lines is ignored. So the file with
```markdown
*
\```
unindented code
 single space indented code
  double space indented code
unindented code
   triple space indented code
\```
```
renders just like
```markdown
*
  double space indented code
unindented code
   triple space indented code
\```
```
would have rendered.

#### Tabs

I have not yet tested tabs because I noticed the issue just today and quickly went to the online editor to produce MWEs where tabs were not available to me. For all I know, a tab indentation may behave similarly to space indentation or completely differently.

### Gitea Version

1.16.8

### Can you reproduce the bug on the Gitea demo site?

No, since it wanted me to jump through some hoops to make an account there and I was in no mood to jump through any more hoops today. *Maybe* tomorrow.

### Screenshots

![grafik](https://user-images.githubusercontent.com/11999912/178361658-a85382a8-6233-48c7-a2fa-15d57cefe406.png)
![grafik](https://user-images.githubusercontent.com/11999912/178361703-f42da0c3-2e58-4854-bd1a-b9705a2b8b65.png)
![grafik](https://user-images.githubusercontent.com/11999912/178361738-e0ba31ec-b9b2-4e6d-94da-b270cb8b86cc.png)
![grafik](https://user-images.githubusercontent.com/11999912/178361763-9e78561f-fc44-49c7-a2e2-974c6c2ea38e.png)
![grafik](https://user-images.githubusercontent.com/11999912/178361860-ce61f394-c77c-44af-b162-2d59e532152b.png)
![grafik](https://user-images.githubusercontent.com/11999912/178361873-be67583f-7432-4d1b-b150-8ab64be8f702.png)
![grafik](https://user-images.githubusercontent.com/11999912/178361881-fdd6572b-138d-4ff5-99c2-3ed1144b49b3.png)
![grafik](https://user-images.githubusercontent.com/11999912/178361905-4165d570-7b12-484a-9099-2942521f81aa.png)

### Operating System

Debian 10 (Buster)

### How are you running Gitea?

From a downloaded binary via systemd and behind a reverse proxy with Nginx.

### Database

MySQL

**Comment by Gusted** [comment]
Fixed in next release by, https://github.com/go-gitea/gitea/pull/20300
