### ISSUE TITLE
Context deadline exceeded

### ISSUE THREAD

**Issue by Prox501** [go-gitea/gitea#20329]
### Description

One of the mirrored project, [LLVM/LLVM-project](https://github.com/llvm/llvm-project) seems to have a problem that anytime I try to open it in gitea server, a 500 error is return with context deadline exceeded which seems to suggest that I am hitting a Time to Live timer limit when attempting to open the page for LLVM mirrored project. I've tried asking about it on matrix chat, checked FAQ, and other google search for this but I was not able to find a solution for this yet.

The local gitea server is running on Proxmox server with about 8 cores, 32 gb of RAM, and 1 TB of storage in LVM Ext4 file system. I also can't reproduce this on https://try.gitea.io since I am unable to get an activation email to try replicating the issue.

### Gitea Version

1.17.0-rc1

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/CLanguagePurist/66337b4af241f89f7f40a5dcc4d40946

### Screenshots

![giteaerror](https://user-images.githubusercontent.com/107034654/178466891-2b2176ea-4b61-4bc1-b082-8ddbc347be22.png)

### Git Version

2.25.1

### Operating System

Ubuntu 20.04.4 LTS

### How are you running Gitea?

Using executable download for Linux from tagged release for 1.17.0-rc1, gitea-1.17.0-rc1-linux-amd64 from [this page](https://github.com/go-gitea/gitea/releases/tag/v1.17.0-rc1) and have done SHA256 checksum comparison and they matched with gitea-1.17.0-rc1-linux-amd64.sha256. I have granted this executable privilege to operates on port 80 and 443 and this server is **NOT** visible to the public internet and required firewall whitelisted address on the LAN to access the server IE my development machine which also runs Linux.

### Database

PostgreSQL

**Comment by vwbusguy** [comment]
Any clue from system logs?  Usually when I get 500 errors like this, it's because of a systems issue, like the database is down or a dependent filesystem isn't mounted.

**Comment by CLanguagePurist** [comment]
> Any clue from system logs? Usually when I get 500 errors like this, it's because of a systems issue, like the database is down or a dependent filesystem isn't mounted or I haven't set the SELinux right labels for it yet.

The system is pretty nominal overall, I can access LLVM-Project repo from within repository folder, so the files are ok as far as access goes. I haven't activated SELinux/Apparmor for this server since the server is not visible to public internet, require public key authentication for SSH, and only allow connections from my devices via IP address that is reserved via static IP.

PostgreSQL Database seems to have no log that would indicates an error or issue. I am able to access the gitea database without any problem.

**Comment by CLanguagePurist** [comment]
Confirming that this is fixed in [Release Candidate 2](https://github.com/go-gitea/gitea/releases/tag/v1.17.0-rc2)
