### ISSUE TITLE
New commit status API doesn't check permissions properly

### ISSUE THREAD

**Issue by leytilera** [go-gitea/gitea#20331]
## Description
Using the Gitea API it is currrently possible with the new commit status endpoint to add a commit status to a repository, even if you don't have write access to that repository. [This function](https://github.com/go-gitea/gitea/blob/main/routers/api/v1/repo/status.go#L21) does not check, if the user has access to the repository.

## Gitea Version
from 1.16.8 to 1.18.0+dev-90-gc8e0fd0bc

##  Can you reproduce the bug on the Gitea demo site?
Yes

**Comment by 6543** [comment]
@leytilera **PLEASE follow [SECURITY.md](https://github.com/go-gitea/gitea/blob/main/SECURITY.md) next time

& thanks for reporting

**Comment by 6543** [comment]
also would you like to be mentioned in the https://blog.gitea.io ?
