### ISSUE TITLE
Option for "Leave site?" warning

### ISSUE THREAD

**Issue by Ryan-pelo** [go-gitea/gitea#20347]
### Feature Description

A few times I have been typing a long comment or post and accidently clicked a link or refreshed the page. Then all my work is gone and non-recoverable. I would appreciate having a "Leave Site?" dialogue box if I have unsaved content in a text box. 

### Screenshots

![Screenshot 2022-07-12 140337](https://user-images.githubusercontent.com/16597255/178594936-34fcb17b-54ce-496f-8a5a-66b4f3c9c42a.png)

**Comment by wxiaoguang** [comment]
Related:
* https://github.com/go-gitea/gitea/issues/17705

**Comment by silverwind** [comment]
There is already a warning via `jquery.are-you-sure`, but I'm not sure whether it will catch all changes, I think it only looks at stuff inside `<form>`.

**Comment by wxiaoguang** [comment]
Some details & background:

Before SimpleMDE/EasyMDE, there is a global `$.areYourSure` confirm (using onbeforeunload) for comment textarea. Everything was just "fine".

However, after introducing SimpleMDE/EasyMDE, `$.areYourSure` doesn't work well with SimpleMDE/EasyMDE editor, so the situation became what you see now.

**Comment by silverwind** [comment]
Another reason to add to the list of like 30+ other issues on why we should remove EasyMDE :)

**Comment by wxiaoguang** [comment]
Then let's do it?

**Comment by silverwind** [comment]
Yes, I think the approach in https://github.com/go-gitea/gitea/pull/15394 with the github toolbar is still ideal. If you have the capacity to do it, please go ahead, I'm happy to review.

**Comment by lunny** [comment]
Should be fixed by #23895

**Comment by silverwind** [comment]
Works now with #23895

<img width="821" alt="Screenshot 2023-04-03 at 22 34 48" src="https://user-images.githubusercontent.com/115237/229621684-071fc0f3-58d3-4dac-8b7f-0f8bdf666477.png">
