### ISSUE TITLE
Release 1.16.9 missing binaries

### ISSUE THREAD

**Issue by vwbusguy** [go-gitea/gitea#20345]
### Description

Release 1.16.9 is missing binaries and the drone CI operation failed before they were published: https://drone.gitea.io/go-gitea/gitea/57431/2/15

### Gitea Version

1.16.9

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![image](https://user-images.githubusercontent.com/5474941/178583520-ace54962-603e-4beb-96c2-58324c159a02.png)
![image](https://user-images.githubusercontent.com/5474941/178583595-5cd2736b-7bf0-4277-8b12-7cf99ed66b81.png)

### Operating System

CentOS Stream 8

### How are you running Gitea?

CentOS Stream 8 with binaries published on GitHub release page with mariadb-server-10.3.28.

### Database

MySQL

**Comment by vwbusguy** [comment]
Looks like the team is already on it and there's another run in the works: https://drone.gitea.io/go-gitea/gitea/57441

**Comment by 6543** [comment]
other ci jobs did consume to mouch resources so it timed out ... next run should not have this problem as all pipelines have been killed until release happened

**Comment by vwbusguy** [comment]
Only breadcrumb I see now is that https://dl.gitea.io/gitea/version.json still points to 1.16.8.
