### ISSUE TITLE
Deactivate account

### ISSUE THREAD

**Issue by lcges** [go-gitea/gitea#2034]
- Gitea version (or commit ref): 1.1.0
- Git version: last version
- Operating system: FreeBSD 11
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant

There is a bug when I deactivate account emails with all work progress are sending still to email from deactivated account. When account is deactivated it must be deactivated totally, all functions of account should be deactivated when account will be deactivated. 

...

![2017-06-22t12 02 59 02 00-831x39](https://user-images.githubusercontent.com/19255071/27428672-17902fd2-5743-11e7-95d6-88d1f22c291f.png)

**If this issue involves the Web Interface, please include a screenshot**

**Comment by daviian** [comment]
@lunny You can assign me to this issue

**Comment by lafriks** [comment]
@daviian only members can be assigned to issue but work freely on it

**Comment by daviian** [comment]
Currently there are two flags describing the active state of a user.
The `is_active` and `prohibited_login` flags. Imo a user is **inactive** if one of both is set.
Please correct me if I am wrong.

**Comment by lunny** [comment]
Just found some different between the two flags.
`is_active` is false, you and your public repos will not be visited by others.
`prohibited_login` is false, you and your public repos will still be visited by others

**Comment by lafriks** [comment]
But user should not get notifications in both cases I think

**Comment by lunny** [comment]
@lafriks I agree with that.

**Comment by lunny** [comment]
resolved by #2384
