### ISSUE TITLE
After renaming CI pipeline file, old pipeline remains as pending in the commit status popup

### ISSUE THREAD

**Issue by vanous** [go-gitea/gitea#20397]
### Description

Thank you for all the hard work, much appreciated.

After renaming the pipeline yml config file in `./woodpecker` directory , the previous pipeline name still remains in Gitea's commit-statuses popup with a correct status (e.g. "Pipeline was successful").  The new pipeline is there too, with  "Pipeline is pending" status text.

I am presuming that this is a Gitea issue, rather then Woodpecker but please let me know if i should report to Woodpecker instead.

Can be observed here: https://codeberg.org/Freeyourgadget/Gadgetbridge

Gitea version: i presume it is 1.16

Thank you!

### Gitea Version

2ddc552777

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![image](https://user-images.githubusercontent.com/3680926/179462087-58a50563-0587-4a09-adc4-30590f8ad43f.png)

### Git Version

i have no access to that info

### Operating System

linux

### How are you running Gitea?

Deployed at Codeberg

EDIT: correct wording

**Comment by wxiaoguang** [comment]
If I understand correctly, the list in the popup is reported by woodpecker. Maybe @6543 can help to do a confirmation.

**Comment by 6543** [comment]
this was gitea v1.16.x - I did not saw this again and could not reproduce it ...
