### ISSUE TITLE
mail notifications for releases are send for user with deactivated e-mail

### ISSUE THREAD

**Issue by r10r** [go-gitea/gitea#20392]
### Description

I've just upated to gitea 1.16.8 and noticed that we're still getting bounce messages for users with deactivated e-mail address. We have several bot users that we don't want to receive mail for.

@Gusted I couldn't comment on #18950, so I've created a new issue intead.
It seems that you've fixed mail notifications for **inactive** users but not for **active users with disabled mail notification** 

### Gitea Version

1.16.8

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

Gitea helm chart  **gitea-5.0.9**

**Comment by r10r** [comment]
A sample bot user with disabled email notifications:

<img width="751" alt="Screenshot 2022-07-17 at 14 18 26" src="https://user-images.githubusercontent.com/309304/179397920-9108d2bb-eea0-4aea-b703-5d2c8e7a0026.png">

**Comment by Gusted** [comment]
I wasn't the one who fixed this, please see #19131. Kindly ping @zeripath

----

> A sample bot user with disabled email notifications:

But that user isn't active, right? So the mentioned PR would have effect.

**Comment by r10r** [comment]
You're right - I must have looked at the wrong commits.
But the fix was scheduled for 1.16.5 - so should be included in v1.16.8 ?
I've **received a bounce message** right now  for goproxy@intern.drachenfels.de
because **someone created a new release**.
Maybe there is still a check missing.

**Comment by Gusted** [comment]
> But the fix was scheduled for 1.16.5 - so should be included in v1.16.8 ?

Yup.

> I've **received a bounce message** right now for [goproxy@intern.drachenfels.de](mailto:goproxy@intern.drachenfels.de)
> because **someone created a new release**.
> Maybe there is still a check missing.

I don't see any check missing. Looking at the code, the [`MailNewRelease`](https://github.com/go-gitea/gitea/blob/main/services/mailer/mail_release.go#L28) function will make sure all UserIDs are mailable via [`GetMaileableUsersByIDs`](https://github.com/go-gitea/gitea/blob/main/models/user/user.go#L1037), which [has](https://github.com/go-gitea/gitea/blob/main/models/user/user.go#L1047) [checks](https://github.com/go-gitea/gitea/blob/main/models/user/user.go#L1055) to only include active users.

**Comment by Gusted** [comment]
> So as an admin I have to login as the (bot) user to disable the users email notifications in Settings -> Account -> Manage Email Addresses - right ?

Yes.
