### ISSUE TITLE
Wiki: only one page

### ISSUE THREAD

**Issue by ponzipo** [go-gitea/gitea#204]
It's possible to create only one wiki page , called "Home". 
How do I create more pages?

**Comment by tboerger** [comment]
Last time I checked that there was a button to create a new page. Got to check that.

**Comment by ponzipo** [comment]
Yes there is a button, but it always create the same page called "Home"... I suppose it should be possible to change the page name?

**Comment by lunny** [comment]
Let me check it.

**Comment by makhov** [comment]
@ponzipo You *must* create page, which called «Home» at first. After that you can create other page with arbitrary name.

**Comment by tboerger** [comment]
After creation of the home page you can create as many pages as you want. Feel free to reopen this issue for further discussion.
