### ISSUE TITLE
random database lock when sqlite database

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#2040]
This is a summary issue since there are so many issues to report the database lock when using sqlite. I will close all other issues and please continue in this issue.

**Comment by lunny** [comment]
And maybe we should pause `make test-sqlite` util this issue is resolved.

**Comment by typeless** [comment]
Reference: https://sqlite.org/unlock_notify.html

**Comment by bkcsoft** [comment]
@typeless Unless that is available in https://github.com/mattn/go-sqlite3 _and_ https://github.com/go-xorm/xorm/ we can't use it 😞

**Comment by typeless** [comment]
@bkcsoft Agreed. This would probably need to be fixed upstream.

**Comment by andreynering** [comment]
I hope #2116 fixes the issue

**Comment by andreynering** [comment]
Reopening, since it seems it not really fixed.

**Comment by PaulBINK** [comment]
We are getting this problem frequently when working with issues: add label, comment, close issue, reopen. Sooner or later it will 500 on us. According to the logs it happens when calling GetNotificationCount.

**Comment by jonasfranz** [comment]
Enabling WAL mode worked for me. https://www.sqlite.org/wal.html

**Comment by hoxnox** [comment]
Same for me.
```
Caused by: hudson.plugins.git.GitException: Command "/usr/local/git/bin/git fetch --tags --progress ssh://sources.acme.com/repo.git +refs/heads/*:refs/remotes/origin/*" returned status code 128:
stdout: 
stderr: Gitea: Internal error
Failed to get repository: database is locked
```

**Comment by typeless** [comment]
Potential alternatives that could fix this:

https://github.com/bvinc/go-sqlite-lite
https://github.com/crawshaw/sqlite

**Comment by bvinc** [comment]
Author of `go-sqlite-lite` here.  My driver, and also crawshaw's driver, don't provide a `database/sql` interface, so they would be extremely inconvenient to use.  But for a few reasons, it would probably help with locking errors.  My driver gives complete control over connections, which means you'll only get locking errors if you're doing something directly to cause them.  The crawshaw driver defaults to using shared cache mode and WAL mode, and uses the unlock_notify API to prevent locking issues with shared cache mode.

I think the current mattn driver is the best one to use if you require a `database/sql` driver.  Their FAQ mentions setting the the maximum number of open connections to 1.  Have you tried that?

https://github.com/mattn/go-sqlite3#faq

**Comment by lunny** [comment]
@bvinc thanks for your reply, It's a good idea to send a PR to set open connections to 1 when using mattn/go-sqlite3

**Comment by hoxnox** [comment]
What is the best way to migrate from sqlite to postgresql?

**Comment by typeless** [comment]
Now that https://github.com/mattn/go-sqlite3/pull/439 is merged, we can either use the tip right away or wait for the new release of `go-sqlite3` to fix the issue. Note that to enable this functionality, we have to add a new build tag `sqlite_unlock_notify.`

Edit: I hope the users don't have to specify `-tags sqlite sqlite_unlock_notify` besides just `-tags sqlite` in that it would be better to not expose the nuances of a dependent package. I don't know how it should be done though. 

Edit2: I changed my mind. If one wants to build Gitea from source, he should be capable of handling the additional flag. We should update the documentation accordingly though.

**Comment by lunny** [comment]
at first, we need a PR to update go-sqlite3 library.

**Comment by lunny** [comment]
Even #5144 resolved single process issue. There is some issues when pushing via SSH. This should be closed by #4886.

**Comment by sapk** [comment]
@typeless go-sqlite3 library with sqlite_unlock_notify tag seems to not build on win 32bit https://drone.gitea.io/go-gitea/gitea/3536/18

**Comment by typeless** [comment]
@sapk Similar to https://github.com/mattn/go-sqlite3/issues/238. Will submit a fix soon.

**Comment by sapk** [comment]
@typeless exactly what I was searching but I use the terms `uint too large` and I found nothing ...

**Comment by typeless** [comment]
I have submitted https://github.com/mattn/go-sqlite3/pull/654.
However, I cannot find a computer with Windows/386 to test. 😨

**Comment by typeless** [comment]
@sapk I just installed it. But after typing `gox -osarch="windows/linux" -tags sqlite_unlock_notify`
, it only prints `Number of parallel builds: 31`. I've not figured out how to use it to run `go test` either. 

Edit: fixed at https://github.com/mattn/go-sqlite3/pull/655

**Comment by lunny** [comment]
Just type `make release-windows` on gitea?

**Comment by typeless** [comment]
@lunny  Is this good?

```
Checking for required docker image karalabe/xgo-latest... not found!
Pulling karalabe/xgo-latest from docker registry...
Using default tag: latest
latest: Pulling from karalabe/xgo-latest
d54efb8db41d: Pull complete
f8b845f45a87: Pull complete
e8db7bf7c39f: Pull complete
9654c40e9079: Pull complete
6d9ef359eaaa: Pull complete
930ad870b3ed: Pull complete
6c2305eeb102: Pull complete
8f5fb6ea515f: Pull complete
a7ed6daacbb2: Pull complete
59648a31bc06: Pull complete
e4950c92f0e1: Pull complete
39c73abb482c: Pull complete
18cc24c098e1: Pull complete
7393446f141f: Pull complete
7a27a63b85c8: Pull complete
712004ba29fc: Pull complete
2b0e6816a036: Pull complete
6bd81709671f: Pull complete
fb892dd34b01: Pull complete
896e316a2862: Pull complete
4a16bec3fec4: Pull complete
0e67b70fabab: Pull complete
308e2b79d14a: Pull complete
8a358963fd91: Pull complete
ea4e4d30f472: Pull complete
541072adfec2: Pull complete
Digest: sha256:7dc73d08ee39b1be23af76089797549fd9838edfd86ffe8cfbe124dd57bf95af
Status: Downloaded newer image for karalabe/xgo-latest:latest
Cross compiling code.gitea.io/gitea...
Building locally code.gitea.io/gitea...
Compiling for windows-4.0/amd64...
# code.gitea.io/gitea
loadinternal: cannot find runtime/cgo
Compiling for windows-4.0/386...
# code.gitea.io/gitea
loadinternal: cannot find runtime/cgo
Cleaning up build environment...
```

**Comment by typeless** [comment]
https://github.com/go-gitea/gitea/pull/5162 fixes the CI failure and `TAGS='bindata sqlite sqlite_unlock_notify' make release-windows` passes.

**Comment by lunny** [comment]
Closed this since it's not a system problem any more. If there is any issue please fire another issue.
