### ISSUE TITLE
"Manage account links" and "The default branch" do not has Chinese supports

### ISSUE THREAD

**Issue by zileyuan** [go-gitea/gitea#2042]
- Gitea version (or commit ref): 1.1.2
- Git version: 1.8.3.1
- Operating system: Centos7
- Database (use `[x]`): 
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite

**Comment by lunny** [comment]
Please go to crowdin.com to help translate. I think that could be in v1.2

**Comment by lafriks** [comment]
If you meant translation than it has to be translated here: https://crowdin.com/project/gitea
