### ISSUE TITLE
Question: Show rendered file in plain mode

### ISSUE THREAD

**Issue by r10r** [go-gitea/gitea#20437]
### Description

How can I show a rendered file (e.g markdown) in plain mode ?

I need this to jump from an external search server *zoekt* to the line of a file which is rendered by default (e.g markdown files) or by an external renderer. 

The answer should be added to https://docs.gitea.io/en-us/external-renderers/.

E.g gitub allows to disable rendering and shows the source blob when the
URL attribute **plain=1** is append.

https://github.com/sourcegraph/zoekt/blob/master/doc/indexing.md?plain=1

<img width="1254" alt="Screenshot 2022-07-21 at 17 48 10" src="https://user-images.githubusercontent.com/309304/180257641-86e0a298-00d3-435e-9a5d-f5a926b8e598.png">

### Gitea Version

1.16.8

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

helm chart

**Comment by silverwind** [comment]
There might be an already open issue for this feature somewhere, but I can't find it.

**Comment by silverwind** [comment]
Actually, this is already implemented via adding [`?display=source`](https://try.gitea.io/silverwind/symlink-test/src/branch/master/images/both-1024.svg?display=source).

**Comment by r10r** [comment]
Nice! It's working in the testing instance, but not in my installation **1.16.8**. 
I looked at the changelog and diff from 1.16.8 to 1.16.9 and haven't noticed a relevant change.
Is there any additional setting required or do I have to upgrade to **1.16.9**  ?
Thanks!

**Comment by zeripath** [comment]
You would need to try 1.17-rc2

**Comment by r10r** [comment]
Cool. I'll wait for 1.17 then. Thanks for the hint!

**Comment by zeripath** [comment]
Honestly consider trying 1.17-rc2 or even just run off the 1.17 release branch (1.17-dev in docker speak) - if no one tries it we'll never find the bugs.

**Comment by wxiaoguang** [comment]
The feature is in 1.17
* https://github.com/go-gitea/gitea/pull/19356

And 1.17-rc2 is very stable now, I highly recommend you to use it.

**Comment by r10r** [comment]
> if no one tries it we'll never find the bugs.

You're right. I'm using the helm chart for deployment.
Can I simply update the image tag in the helm chart values then?
