### ISSUE TITLE
Css/Less not rebuilding

### ISSUE THREAD

**Issue by bl00mber** [go-gitea/gitea#20439]
### Description

How to rebuild css/less files?
After each of following commands "gitea web" was runned:
TAGS="bindata" make build - not reloads less/css (changes not rendered in browser window)
make frontend - not reloads less/css
make webpack - not reloads less/css
make clean / make clean-all - does not have effect, when used before commands listed above.
No changes made in less/[filename].less are rendered on app page.
When inspecting app in browser looking for source of rendered css styles, it shows that /assets/css/index.css is used as css file. No such file exists in project directory, or created during running of commands.

### Gitea Version

c7fa5cc0175935579091daaa70a24a6442c4ee01

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

TAGS="bindata" make build

**Comment by silverwind** [comment]
Pretty much all commands above should rebuild the files in `public/css`, which is mapped to `assets/css` on the web. Also check config, if `STATIC_ROOT_PATH` is modified these files will take precedence of built-in ones via bindata.

**Comment by bl00mber** [comment]
@silverwind it was Firefox caching... spent 6 hours finding.
