### ISSUE TITLE
Webauthn Credential ID length too short

### ISSUE THREAD

**Issue by spotlightishere** [go-gitea/gitea#20457]
### Description

Hi all :wave: I recently received a new FIDO2 security key, a SoloKey v2. 

Upon registering it to my Gitea instance, a server error was encountered:
> WebauthnRegisterPost() [E] [62db09ae] CreateCredential: pq: value too long for type character varying(410)

While debugging this, I noticed that a 270 byte credential ID was generated for my instance. It seems that the current maximum credential ID length is 255 bytes:
https://github.com/go-gitea/gitea/blob/886b1de94914186a502ed68a6a281a15f1d8d9a3/models/migrations/v210.go#L28

After some tentative searching through the linked WebAuthn specification, I noticed the following:
> **[Credential ID](https://w3c.github.io/webauthn/#credential-id)**
>
> A probabilistically-unique byte sequence identifying a public key credential source and its authentication assertions. At most 1023 bytes long.

I think this issue could be resolved by changing the maximum credential ID length to 1023 bytes raw, or 1640 bytes base32-encoded (per `head -c 1023 /dev/random | base32 --wrap=0 | wc -c`).

### Gitea Version

1.17.0-rc2

### Can you reproduce the bug on the Gitea demo site?

No - its credential ID was exactly 255 bytes, which probably shouldn't be relied on

### Log Gist

https://gist.github.com/spotlightishere/8bcfd9591ca7ec421873091c77644e91

### Operating System

Debian 11

### How are you running Gitea?

Downloaded from https://dl.gitea.io/, running underneath systemd

### Database

PostgreSQL

**Comment by Gusted** [comment]
CC @zeripath migration v4? Didn't expect another issue to pop up after you fiddling with this for so long with this.

For context: https://github.com/go-gitea/gitea/pull/18770 this isn't the first time issues with this length has popped up.

**Comment by zeripath** [comment]
ffs.

They changed the spec.

THIS WAS THE SPEC https://www.w3.org/TR/2021/REC-webauthn-2-20210408/#credential-id

**Comment by Gusted** [comment]
https://github.com/w3c/webauthn/pull/1664 changed the spec

**Comment by zeripath** [comment]
anyway we'll need yet another migration and we'll need to backport the other migration changes. 

I don't know what we can do for 1.16 - a doctor command perhaps.

**Comment by Gusted** [comment]
1.17 should be around the corner. There aren't any other commit pending for a 1.16.10 release. "Just upgrade" advice?

**Comment by zeripath** [comment]
As an aside:

This is literally unbelievable they changed the spec 2 days ago and we're already getting behaviour that demands the new spec?!

It's just unreasonable
