### ISSUE TITLE
Repo links on dashboard wrong when using a proxy frontend

### ISSUE THREAD

**Issue by doodyd** [go-gitea/gitea#20450]
### Description

The repository links on the dashboard repository widget are incorrect when gitea is behind a proxy (HAProxy in my case).  All other links so far encountered are correct.

Example:

Repository link on dashboard (repo widget, pictured below):

   http://gitea.example.com:3000/org/repo-name

All other repo links (all other links so far):

   https://proxy-name.example.com/org/repo-name

### Gitea Version

1.16.7

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

n/a

### Screenshots

![image](https://user-images.githubusercontent.com/29137584/180369588-da9883e8-b0de-4f40-842c-dbb0a37f6144.png)

### Git Version

2.35.2

### Operating System

TrueNAS-13.0-U1 Core (jail)

### How are you running Gitea?

Installed in jail from default package manager

### Database

MySQL

**Comment by silverwind** [comment]
Generally this can be solved via configuration by setting `ROOT_URL` accordingly, but I'll take this up as a bug as we should not render absolute URLs where relative ones (without origin) are sufficient.

**Comment by wxiaoguang** [comment]
This one #19345

* https://github.com/go-gitea/gitea/issues/19345

**Comment by silverwind** [comment]
Okay, it's a duplicate then.

**Comment by doodyd** [comment]
Thanks for the feedback and the tip. I searched the issues for a similar problem but it can be difficult to know what terms to use. Changing the ROOT_URL has resolved the issue.

**Comment by LaserLV52** [comment]
Hi, i have installed the gitea in Truenas Scale (not core). Now, i have the ROOT_URL error  too. But, when i modify the ROOT_URL in app.ini and reboot the gitea, the ROOT_URL didn't work, it still convert back into the default ROOT_URL in app.ini. Do you have any idea? thanks!
