### ISSUE TITLE
Issue Template Uses Incorrect Path For Ref (Commit Instead Of Branch)

### ISSUE THREAD

**Issue by Deadmano** [go-gitea/gitea#20456]
### Description

When adding an issue from a template, the icon that links to the ref incorrectly wants to reference a commit instead of the branch, despite the branch existing with that same name. See the attached screenshot.

The template.md file contains:

```MD
---

name: "New Bug"
about: "Log a new bug!"
title: "Bug: "
ref: "main"
labels:

- bug

---
```

Expected path: `/user/repo/src/branch/main`
Actual path: `/user/repo/src/commit/main`

The actual path, which points to `commit` does not exist and thus results in a 404.

My understanding is that the link as per the screenshot will take you to the branch/tag as if you manually selected it when creating an issue and picking a branch/tag and the "ref" portion of the template would do exactly that. The documentation on issue templates was vague and doesn't mention what "ref" actually refers to.

### Screenshots

![Repo_Issue_5](https://user-images.githubusercontent.com/7104251/180529423-eb3d30d6-0f45-4c3f-9528-1a3782fa800b.PNG)

### Gitea Version

1.17.0-rc2

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

Windows 10

### Browser Version

Firefox 102

**Comment by Deadmano** [comment]
@6543 & @lunny tagging you both as I believe I saw some things related to changes made in the latest RC that may be relevant? I could have sworn it was working prior to updating to `v1.17.0-rc2`, link pointing to the actual _branch_. I went back to `1.17.0+rc1-34-g4c1f4ee84` and the issue now still persists. Any feedback would be greatly appreciated!

**Comment by zeripath** [comment]
Have you tried?

```yaml
---

name: "New Bug"
about: "Log a new bug!"
title: "Bug: "
ref: "refs/heads/main"
labels:

- bug

---
```

**Comment by zeripath** [comment]
If this represents a change in behaviour from 1.16 I think we should change:

https://github.com/go-gitea/gitea/blob/599ae09a94e40f9ef567aa2ec7486f68a64a3384/modules/context/repo.go#L1081-L1088

to prepend the `refs/heads/` to the `Ref` if it does not match a SHA or does not already start with `refs/`

**Comment by Deadmano** [comment]
@zeripath that did it; you are a wonderful soul! Now what I'd love to know is why it was working prior, and updating to the latest RC seemingly broke it? I tried multiple repos, initialised both via CLI, GUI, and via the Web Interface, and it made no change to the template issue.

Perhaps the [documentation](https://docs.gitea.io/en-us/issue-pull-request-templates/#issue-template-directory) can be updated to explain how Ref works? I had no idea it takes a literal Git ref since the wording in the example makes it seem as if it'd point to a default `main` branch.

Would it then be `refs/tags/{version}` for tags?

**Comment by zeripath** [comment]
Was it definitely doing this other behaviour in 1.16? If so that is likely to mean that it's an unintended change of behaviour and we should implement the changes I've suggested above

**Comment by Deadmano** [comment]
It was definitely doing it in `1.17.0+rc1-34-g4c1f4ee84` from the binary [gitea-1.17-windows-4.0-amd64.exe](https://dl.gitea.io/gitea/1.17/gitea-1.17-windows-4.0-amd64.exe) under the [1.17 downloads page](https://dl.gitea.io/gitea/1.17).

I tried upgrading to [v1.17.0-rc2](https://github.com/go-gitea/gitea/releases/tag/v1.17.0-rc2) from GitHub directly which is when I noticed this starting to happen with my templates.

**Comment by Deadmano** [comment]
Also I noticed some strange behaviour with the pathing in the URLs.

Take for example these two paths:
```
/user/repo/src/brach/
/user/repo/src/commit/

```
If you were to enter them as per above they get malformed into:
```
/user/repo/src/branch/branch/main/branch
/user/repo/src/commit/branch/main/commit
```
Is this behaviour intended and/or related?

**Comment by zeripath** [comment]
>Take for example these two paths:

What do you mean "path"? Do you mean "URL" as in:

    http://gitea/user/repo/src/<some-path-that-is-not-a-branch> 

is transformed to:

    http://gitea/user/repo/src/branch/master/<some-path-that-is-not-a-branch> 

If so then this is very much longstanding behaviour which has been present since before I have been submitting PRs to gitea and likely dates back to Gogs and relates to a legacy way of pointing to src files.

(Likely this should have been removed at least 3 years ago as it was legacy at that point.)

**Comment by zeripath** [comment]
OK Issue templates was in 1.16.0 so there has been an unintended change here and we should change the code above to prepend the `refs/heads/` if it doesn't start with `refs/`. 

An alternative option is to try to detect which ref this could be referring to as I suspect that people might actually want tags etc to be detected nicely.

I'm not certain.
