### ISSUE TITLE
[Proposal] Future improvments for code hightlight diff

### ISSUE THREAD

**Issue by wxiaoguang** [go-gitea/gitea#20467]
Follows

* https://github.com/go-gitea/gitea/pull/19958

# Background

Gitea's code diff is based on highlighted code at the moment. #19958 only does some improvements, there are still some bad cases for rendering if the diff breaks in a highlighted span. See the screenshot, the diff result is inconsistent.

![image](https://user-images.githubusercontent.com/2114189/180629848-22a2778c-b7b5-41a1-96d2-286a9278ebe1.png)

![image](https://user-images.githubusercontent.com/2114189/180629874-29b2f0de-a7c1-41ff-bdf9-450632b19f46.png)

(more hints, in the second screenshot, the color of `bbbb` is different, it's also caused by that the diff breaks in the span)

# Possible solutions

## Use "semantic change expanding" algorithm

Expand the spans with semantics to other diff sections?

## Use a general token parser

More aggressively, use placeholders for all tokens (make `aaaabbbb` a token), then there will be no break in tokens?

## Some other diff algorithms

(TODO)

## Some references

* https://github.com/dandavison/delta
* Git's `[diff].algorithm = patience`

**Comment by silverwind** [comment]
Regarding diff algorithms, there's also `histogram` which is an improvement over `patience`. [This article](https://luppeng.wordpress.com/2020/10/10/when-to-use-each-of-the-git-diff-algorithms/) gives a  good summary. I think we may opt to use these newer diff algorithms by default in the future.

**Comment by wxiaoguang** [comment]
I am not working on this, so close it. Feel free to take it.
