### ISSUE TITLE
Uploaded Package does not show in Webgui

### ISSUE THREAD

**Issue by quotengrote** [go-gitea/gitea#20483]
### Description

Hi,

i want to Upload a Package to the new Package Registry.

`curl --user mg:NE[..]iTTQdC --upload-file ./output/bash-helper-scripts-latest.deb https://<domain>/api/packages/mg/generic/bash-helper-scripts/1.1.1/bash-helper-scripts-latest.deb`.

The package is usccessfully uploaded:

```
ul 25 17:04:09 gitea gitea[2053835]: 2022/07/25 17:04:09 [62deb0e9] router: completed PUT /api/packages/mg/generic/bash-helper-scripts/1.1.2/bash-helper-scripts-latest.deb for 192.168.2.50:41852, 201 Created in 23.3ms @ generic/generic.go:68(generic.UploadPackage)
```

and

After a new try with the same Version Number:
```
Package version already exists
```

But after that the Package is never shown:
![2022-07-25 17_05_03-Packages - bash-helper-scripts-mgrote - Gitea - Vivaldi](https://user-images.githubusercontent.com/38253905/180810703-62b4704e-260f-44eb-8bae-b66911d4ca07.png)

### Gitea Version

1.17.0-rc2

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

20.04.4 LTS (Focal Fossa)

### How are you running Gitea?

Gitea ist installed with ansible:

https://git.mgrote.net/mg/ansible/src/branch/master/roles/tmaurice.gitea

All Vars:

https://git.mgrote.net/mg/ansible/src/branch/master/group_vars/gitea.yml

### Database

SQLite

**Comment by noerw** [comment]
Did you [link the package to the repository](https://docs.gitea.io/en-us/packages/overview/#repository-packages)?

**Comment by quotengrote** [comment]
Sry to ask, but...

"To link an (already uploaded) package to a repository, open the settings page on that package and choose a repository to link this package to."

But the Repository-Settings dont have such a setting.
![2022-07-26 15_10_04-Settings - bash-helper-scripts-mgrote - Gitea - Vivaldi](https://user-images.githubusercontent.com/38253905/181013876-7192784f-57ce-432b-a812-1b6b13cdd9e8.png)
![2022-07-26 15_10_10-Settings - bash-helper-scripts-mgrote - Gitea - Vivaldi](https://user-images.githubusercontent.com/38253905/181013881-716a5fc2-3c6a-4f82-815d-c03628f738ef.png)

And i did not find a API-Endpoint for this.

**Comment by noerw** [comment]
Not the repository settings, but the package settings (`<package-url>/settings`).
Yes, looks like the API is missing for this, feel free to change the issue title as a feature request for that API.

**Comment by quotengrote** [comment]
If i go to:

`https://git.mgrote.net/api/packages/mg/generic/bash-helper-scripts/1.1.33/bash-helper-scripts-latest.deb/settings` i get a 404.

But without `/settings` i can download the Package.

**Comment by noerw** [comment]
I'm talking about the web UI, not the API — as mentioned, there currently is no API for this.
https://git.mgrote.net/mg/-/packages/generic/bash-helper-scripts-mgrote/1.1.33/settings

**Comment by quotengrote** [comment]
Ah, i got it now.

And it worked!

thx
Maybe i/we could improve the docs with a Screenshot where to find that Settings Page?
