### ISSUE TITLE
`/api/v1/packages/<user>` returns internal/temporary `_upload` tag

### ISSUE THREAD

**Issue by noerw** [go-gitea/gitea#20491]
### Description

In addition to the tags published with `docker push <image:tag>` as they are displayed in the UI, an additional package with version `_upload` is returned.

I'm not sure if its a docker registry internal thing to keep this version around, but I'd argue the API should return the same items as the web UI.

`/api/v1/packages/<user>/container/<foo>/_upload` returns a 404.

Maybe @KN4CK3R can comment if this is intentional behaviour

### Gitea Version

1.18.0+dev-154-g3704be854

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

built from source on localhost:3000

### Database

SQLite

**Comment by KN4CK3R** [comment]
Thanks for tagging. Where exactly do you see the `_upload` version? You are right, this is an internal detail which should not be visible. UI and API should not display this version.
