### ISSUE TITLE
Preserve systemd provided socket after shutdown

### ISSUE THREAD

**Issue by frankli0324** [go-gitea/gitea#20490]
### Description

I struggle to understand why gitea unlinks the socket file on shutdown (L171):
https://github.com/go-gitea/gitea/blob/a701fd35cf6efdecf8047cb1ee9eb683d95b1db5/modules/graceful/net_unix.go#L166-L174
I believe this is unwanted behavior since it breaks `systemctl restart gitea` when using socket activation.

### Gitea Version

a701fd3

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

```systemd.service
# gitea.service
[Unit]
Description=Gitea (Git with a cup of tea)
After=syslog.target
After=network.target

Wants=postgresql.service
After=postgresql.service

After=gitea.socket
Requires=gitea.socket

[Service]
RestartSec=2s
Type=simple
User=git
Group=git
WorkingDirectory=/var/lib/gitea/
ExecStart=/usr/local/bin/gitea --config /etc/gitea/app.ini --custom-path /pool/git/custom --work-path /var/lib/gitea/ web
Restart=always
Environment=USER=git

[Install]
WantedBy=multi-user.target
```

```systemd.service
# gitea.socket
[Unit]
Description=Gitea Web Socket

[Socket]
ListenStream=/run/gitea/gitea.sock
SocketMode=0666
SocketUser=git
SocketGroup=git

[Install]
WantedBy=sockets.target
```

### Database

PostgreSQL

**Comment by zeripath** [comment]
Have you tried using kill -1 to restart gitea?

**Comment by frankli0324** [comment]
> Have you tried using kill -1 to restart gitea?

I could, but why?

**Comment by frankli0324** [comment]
from what I learned, `SetUnlinkOnClose` was designed exactly for **preserving** the socket file created by systemd by the golang team.

https://groups.google.com/g/golang-nuts/c/UtBR4IfgaEw

**Comment by silverwind** [comment]
Isn't it normal to unlink a inactive socket, indicating it is not available? What other options are there? Set `chmod 000`?

**Comment by frankli0324** [comment]
https://www.freedesktop.org/software/systemd/man/systemd.socket.html

**Comment by silverwind** [comment]
Interesting, yeah they mention it multiple times on that link:

> A daemon listening on an AF_UNIX socket may, but does not need to, call [close(2)](http://man7.org/linux/man-pages/man2/close.2.html) on the received socket before exiting. However, it must not unlink the socket from a file system.

**Comment by frankli0324** [comment]
further explanation on how it breaks "systemctl restart":

* gitea.socket activates, systemd creates ipc file
* gitea.service activates, listens on the ipc file sysd just created
* invoke systemctl restart
* gitea.service deactivates, deleting the ipc file
* gitea.service activates, failing to find the appropriate ipc file to listen on

under such circumstances, users would have to first restart gitea.socket, then gitea.service.

**Comment by frankli0324** [comment]
> Interesting, yeah they mention it multiple times on that link:
> 
> > A daemon listening on an AF_UNIX socket may, but does not need to, call [close(2)](http://man7.org/linux/man-pages/man2/close.2.html) on the received socket before exiting. However, it must not unlink the socket from a file system.
> 
> Unrelated to gitea, but normally, what I do in my apps is unlink,create and chmod 666 a socket on start, and do nothing with it on shutdown.

no, this is not about using ipc file, this is about using systemd.socket. it's two things to consider.

**Comment by frankli0324** [comment]
any thoughts?
