### ISSUE TITLE
Wikis: why not "Docs"

### ISSUE THREAD

**Issue by ponzipo** [go-gitea/gitea#205]
GIven that the purpose of "Wikis" is to write and collaborate on documentation, and also given that in this context "Wikis" aren't really mediawiki instances, but just repositories with Markdown files inside, wouldn't they better be renamed "Docs" or "Documentation"? "Wiki" doesn't really make any sense except that github/gitlab use it...

**Comment by tboerger** [comment]
Because documentation is something different than a collection of pages that can include whatever the author wants. It's not just used by gitea/gitlab/github. And i think the naming is fine as it just provides wiki-like functionality. Wikimedia != Wiki

**Comment by ponzipo** [comment]
What's the difference between "documentation" and "a collection of pages that can include whatever the author wants"? Aren't Wikis supposed to be used for extended documentation (to supplement the README)?

**Comment by tboerger** [comment]
it totally depends on the repo owner what get's written to the wiki. But nearly anybody who has worked with gitlab or github knows what this wiki means... So IMHO the naming should stay as it is.

**Comment by lunny** [comment]
Wiki provides a chance to seperate the codes and documents. So codes and documents have different commits records.

**Comment by lunny** [comment]
And for wiki we can write articles online with others.

**Comment by tboerger** [comment]
Let's close that for now, I think there are multiple people that want to stick with Wiki
