### ISSUE TITLE
Automated deletion for images in the container registry

### ISSUE THREAD

**Issue by loadi-dev** [go-gitea/gitea#20514]
### Feature Description

I'm heavily using the package registry introduced with Gitea 1.17 (using 1.17.0+rc2 at the moment). I'm especially generating docker images quite frequently. This starts to consume lots of space on my hard disk.

It would be nice, if Gitea would have the possibility to automatically delete packages (especially container images) after a configurable time. The configuration could come from the linked repository.

Gitlab has a similar feature allowing to configure a time to keep images (e.g. at least 2 weeks) and the amount of images to keep (e.g. keep the last 5 images).  So only if both conditions were exceeded it would delete the images.

Alternatively it would already be helpful to allow bulk deletion using a checkbox in the packages list. Right now I need a lot of clicks to delete old packages (6 per container image starting on the packages overview list). And every time I delete one old image I'm back on the packages overview site.

**Comment by KN4CK3R** [comment]
related #20766

**Comment by KN4CK3R** [comment]
Implemented this in #21658.
