### ISSUE TITLE
Gitea api not updating

### ISSUE THREAD

**Issue by mootfrost** [go-gitea/gitea#20533]
### Description

I have 30 repos in gitea. My side loads all repos from: https://git.mootfrost.ru/api/v1/users/Mootfrost777/repos.
New public repos aren't visible in api response.

### Gitea Version

1.16.5

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

Ubuntu 22.04

### How are you running Gitea?

Docker

**Comment by noerw** [comment]
This API is paginated and defaults to 30 items per page. use `?page=` and the `X-Total-Count` header
