### ISSUE TITLE
basics operations without javascript

### ISSUE THREAD

**Issue by imxade** [go-gitea/gitea#20553]
### Feature Description

It would be great if we could do some basic operations like

* selecting bubbles

![bubble](https://user-images.githubusercontent.com/56511165/181914383-0be30ee0-43b4-4b5a-b03f-4e71e3c9413d.png)

* deleting stuff

![delete1](https://user-images.githubusercontent.com/56511165/181914253-9a11e8d9-4809-44f4-9584-53f97e72d198.png)

![basic](https://user-images.githubusercontent.com/56511165/181914279-26659998-71ae-4a1b-9290-d45ff1d82076.png)

without **javascript**

**Comment by delvh** [comment]
I can see selecting radio boxes, but deleting won't be possible without JS.
Otherwise, you couldn't show the alert to ask the user for confirmation whether he really wants to delete what he is currently trying to delete.

**Comment by nvidiaLinuxUser** [comment]
I use the Internet without JavaScript, like many other people, it would be nice to implement this.

**Comment by wxiaoguang** [comment]
Nowadays, it's impossible to get rid of JavaScript.

There were already a lot of functions powered by JavaScript in Gitea.

Without JavaScript, the Gitea Web UI almost doesn't work (only some static links work ....)

So I proposed  Clarify that Gitea requires JavaScript #23677  to clarify the problem.

So sorry that it doesn't match your expectation.
