### ISSUE TITLE
Gitea 1.17.0 ignores "Default merge style for pull requests"

### ISSUE THREAD

**Issue by achikhv** [go-gitea/gitea#20562]
### Description

Gitea 1.17.0 ignores "Default merge style for pull requests:" for repository and always shows "Create merge commit". My repositories are configured to squash-merge by default, and after update from 1.16.9 to 1.17.0 default button is again merge commit.

URL of Gitea demo: https://try.gitea.io/achi/test/pulls/1
It shows "Create merge commit", but repository's setting is "Create squash commit".

### Gitea Version

1.17.0

### Can you reproduce the bug on the Gitea demo site?

Yes

### Git Version

Not relevant

### Operating System

Windows

### How are you running Gitea?

Used "https://dl.gitea.io/gitea/1.17.0/gitea-1.17.0-windows-4.0-amd64.exe"

### Database

MSSQL

**Comment by wxiaoguang** [comment]
Sorry, I forgot to choose the default merge style.

Will be fixed by #20564

**Comment by viceice** [comment]
@wxiaoguang When do you think this fix will be released in `v1.17.1`?

**Comment by wxiaoguang** [comment]
I am not sure. It depends when the owners/maintainers decide to make a new release. Maybe (usually) a week later?

I think you can use the latest 1.17 binary (https://dl.gitea.io/gitea/1.17) or latest 1.17 docker image (1.17-dev) to get this fix. They are as stable as 1.17 and contain all bug fixes for next unreleased 1.17.x
