### ISSUE TITLE
SCRIPT_TYPE "bash" is not on the current PATH

### ISSUE THREAD

**Issue by jarvis0325** [go-gitea/gitea#20580]
### Description

v1.16.7  > v1.17.0

2022/08/01 10:35:05 ...etting/repository.go:289:newRepository() [W] SCRIPT_TYPE "bash" is not on the current PATH. Are you sure that this is the correct SCRIPT_TYPE?

How to fix this warring ?

### Gitea Version

v1.17.0

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

![img](https://user-images.githubusercontent.com/8055266/182061899-9ac78987-1c91-4fbb-b970-1dfe3b11c9c8.jpg)

### Git Version

git version 2.34.1.windows.1

### Operating System

windows

### How are you running Gitea?

exe gitea.exe

### Database

PostgreSQL

**Comment by jarvis0325** [comment]
Repository >

**Comment by eeyrjmr** [comment]
Running doctor shows:


[7] Check if SCRIPT_TYPE is available
 - [C] ScriptType ""bash"" is not on the current PATH. Error: exec: "bash": executable file not found in %PATH%
ERROR


So I think this is the issue
