### ISSUE TITLE
PR failure while using NFS or JuiceFS

### ISSUE THREAD

**Issue by Bruc3Stark** [go-gitea/gitea#20587]
### Description

I'm using docker to run gitea, using volumes: /data:/data to mount space from container to local.
At first, I'm using juicefs as file system, and when i tried to pull request in a large repo, the gitea website will stuck and then break down on code 504. The docker logs showed as below: Unable to run ls-files -u -z! Error: git ls-files -u -z: context deadline exceeded
![image](https://user-images.githubusercontent.com/33786770/182151527-a2f8325d-9101-469a-95ef-9e7d0368e12a.png)
Then I thought it was the juicefs problem, so I tried nfs instead, but the performance is the same.
At last, I used ubuntu local file system, there was no problem any more, and the speed of PR or push was very quick.
So, can gitea use a network-file-system or cloud-file-system as storage rather than local fs? And what might be the reason of this situation?
Thanks.

### Gitea Version

1.16.8

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![image](https://user-images.githubusercontent.com/33786770/182151527-a2f8325d-9101-469a-95ef-9e7d0368e12a.png)

### Git Version

2.25.1

### Operating System

ubuntu

### How are you running Gitea?

Docker

### Database

MySQL

**Comment by 6543** [comment]
I would say your git on NFS is just slow ... so increase timeouts?
-> https://docs.gitea.io/en-us/config-cheat-sheet/#git---timeout-settings-gittimeout

**Comment by Bruc3Stark** [comment]
> I would say your git on NFS is just slow ... so increase timeouts? -> https://docs.gitea.io/en-us/config-cheat-sheet/#git---timeout-settings-gittimeout

Thanks a lot, but I wonder why it is slow for git on NFS? Could you please outline the reason if possible? Thanks again.

**Comment by 6543** [comment]
if you have high ping in the line ... and git does some sequential work ... it could handle throu thousands of files that depend on each other, so if NFS is not async ... you wait thousand*ping time + the computation work

**Comment by wxiaoguang** [comment]
Inactive for a long time. Feel free to re-open if there are new problems.
