### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'call') [v1.17.0]

### ISSUE THREAD

**Issue by viceice** [go-gitea/gitea#20582]
### Description

The following error occurs in browser console after upgrade from `v1.16.9` on PR and issue details pages

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'call')
    at jt (index.js?v=95cfeb8746010d271b9adf778c18dbad:7:127920)
    at ./node_modules/easymde/src/js/easymde.js (easymde.js:9:43063)
    at jt (index.js?v=95cfeb8746010d271b9adf778c18dbad:7:127920)
    at jt.t (index.js?v=95cfeb8746010d271b9adf778c18dbad:7:128283)
```

### Gitea Version

1.17.0

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![image](https://user-images.githubusercontent.com/1798109/182081713-9c15c821-72c2-4644-a919-968c8a20cbbd.png)

### Git Version

2.36.2

### Operating System

Linux

### How are you running Gitea?

offical docker image

### Database

PostgreSQL

**Comment by viceice** [comment]
![image](https://user-images.githubusercontent.com/1798109/182082222-5f5fce3e-db95-49e6-97a4-667962a43a28.png)
Happens when clicking on edit button 😕

**Comment by viceice** [comment]
OK. seems to be browser cache related 😞 

Leaving open if anybody else stumbles on it

**Comment by wxiaoguang** [comment]
That's a long standing problem but no progress yet.

* https://github.com/go-gitea/gitea/pull/18348
* https://github.com/go-gitea/gitea/pull/18632
