### ISSUE TITLE
[v1.17.0] API cannot use _csrf token get information

### ISSUE THREAD

**Issue by tyroneyeh** [go-gitea/gitea#20585]
### Description

Show `The target couldn't be found.` or `token is required`
How use _csrf token to API get data?

API URL: /api/v1/repos/{username}/{reponame}/issues this API in mustEnableIssuesOrPulls function show `The target couldn't be found.`

API URL: /api/v1/notifications this API show `token is required`

### Gitea Version

1.17.0

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

systemd

### Database

PostgreSQL

**Comment by lunny** [comment]
From v1.17, web requests are splitter from API/v1. API will not need csrf token. You could just use access token to do that.

**Comment by tyroneyeh** [comment]
Is it possible to use the session that the original browser is logged in to access the API data?, using AJAX
