### ISSUE TITLE
500 error, "No branches in non-empty repository" after upgrade to v1.17.0

### ISSUE THREAD

**Issue by saosangmo** [go-gitea/gitea#20591]
### Description

After I upgrade to V1.17.0, I get the 500 error when access any empty repositories. In my gitea, I create 3 empty repositories to manage our issues.

When I enable dev mode `RUN_MODE = dev` , the Web interface report the below message:
```
No branches in non-empty repository /var/lib/gitea/data/gitea-repositories/osdvn/digicart.git
```

### Screenshots

<img width="1159" alt="Screen Shot 2022-08-01 at 21 22 21" src="https://user-images.githubusercontent.com/4606931/182203712-28ff6539-2d8b-4cfd-aa99-981362acfed2.png">

### Gitea Version

1.17.0

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

MacOS X, Windows 10

### Browser Version

Chrome

**Comment by Gusted** [comment]
Do you have steps how you created these repositories? If you create a via the webUI, the repository will be marked as empty. Via any other way it should always have a branch or something similar. To work around it, you could push a branch to the repository so it won't error anymore.

**Comment by saosangmo** [comment]
Thank @Gusted so much. I follow your guide and it works normally. Hope this bug will be fixed in the next version.
