### ISSUE TITLE
Container package registry login does not respect 2fa

### ISSUE THREAD

**Issue by TymanWasTaken** [go-gitea/gitea#20598]
### Description

In my gitea instance, I have configured 2fa on my account and it works fine, but I noticed when I tried to use the docker package registry, it only asked for my username and password, nothing else. I would expect 2fa to apply everywhere, however it doesn't look like the package registry (at least the container part, I haven't checked others) respects 2fa settings.

### Gitea Version

1.17.0

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

![image](https://user-images.githubusercontent.com/32660892/182188349-533dd147-7a30-4ca8-91b7-2055577868dc.png)
As shown above (this is on try.gitea.io), I enabled 2fa on my account, however when logging in with docker all I had to enter was a simple username and password.

### How are you running Gitea?

My own instance is hosted via docker, but I could also reproduce on https://try.gitea.io

### Database

SQLite

**Comment by BaseCrusher** [comment]
#20573
if you try to push an image you'll see that it won't work

**Comment by TymanWasTaken** [comment]
I just tested it once again on `try.gitea.io`:
1. Make [an account](https://try.gitea.io/tyman)
2. Enable 2fa
3. Login via docker with username and password (no 2fa or access token)
4. Pushed [an image](https://try.gitea.io/tyman/-/packages/container/pufferfish-server/1.19-24) under my account

So this doesn't appear to be the same issue
