### ISSUE TITLE
Repository setting page push mirror address backend get errorAddress cause display error

### ISSUE THREAD

**Issue by xpy865934** [go-gitea/gitea#20592]
### Description

I used the function of migrating external repository to import an external repository. I tried it from both gitlab and gitea. After the import was successful, set the image setting of the repository. After the setting was completed, in the column of image setting - image library, the image library I set is not displayed, but the link of the external repository i migrated is displayed, but the image library I set is used during synchronization. It should be displayed incorrectly

1. git clone external repository
2. set repository push mirror address
3. setting push mirror address list display external repository url

### Gitea Version

main

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

1. 
![image](https://user-images.githubusercontent.com/26896223/182174631-d9f69840-b975-443e-92d9-bf9103630413.png)
2. 
![image](https://user-images.githubusercontent.com/26896223/182174968-5a183ea8-225b-4db8-8e5a-d9a812609fc9.png)
3.
![image](https://user-images.githubusercontent.com/26896223/182175340-306b51fb-d150-489e-9d62-061ef144b05e.png)
4.
![image](https://user-images.githubusercontent.com/26896223/182175487-f1adcc56-cf90-46cb-a43e-89a7c18777d9.png)

### How are you running Gitea?

using https://try.gitea.io/

### Database

MySQL

**Comment by lunny** [comment]
Should be fixed by #20593
