### ISSUE TITLE
Firefox and V1.17.0 Edit Forms (Issues) and Save Button does not work

### ISSUE THREAD

**Issue by flobee** [go-gitea/gitea#20590]
### Description

Firefox and V1.17.0 Edit Forms (Issues) and Save Button does not work

Edit and issue (click several times on "Edit' to get the form), then saving a change: No http request made. 

HINT:
A js error is reported in error console of the browser. Chrome Browser or latest gitea version on try.gitea.io works with firefox. So this is a tmp problem but the release is buggy.

### Gitea Version

1.17.0

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

debian 11

### How are you running Gitea?

binary build gitea-1.17.0-linux-amd64

### Database

SQLite

**Comment by silverwind** [comment]
Might just be a browser cache issue, try a hard refresh (ctrl+shift+r).

**Comment by flobee** [comment]
Jepp! Kind of... next day it works. wondering... anyway: CLOSE, NOT A BUG
