### ISSUE TITLE
500 error when trying to use non-semver packages

### ISSUE THREAD

**Issue by dorianim** [go-gitea/gitea#20603]
### Description

After creating a non-semver package, the page `https://gitea.domain/user/-/packages` returns an error 500.

Gitea logs `.../web/user/package.go:58:ListPackages() [E] [62e82d7a] GetPackageDescriptors: Malformed version: preview-be4d4b6e7849557ce7ba7bfee4b66c47c27f986a`

### Gitea Version

1.17.0

### Can you reproduce the bug on the Gitea demo site?

No, maybe because it is on `1.18.0+dev-198-g4f14c6de1`?

### Screenshots

![image](https://user-images.githubusercontent.com/30153207/182234899-a33d47e0-397e-476d-b984-0d3385acda94.png)

### How are you running Gitea?

I am using the `gitea/gitea` docker image on the `latest` tag

### Database

PostgreSQL

**Comment by dorianim** [comment]
Another thing I just discovered:
The `https://itsblue.dev/admin/packages`-Page now also returns 500

**Comment by lunny** [comment]
What's the error logs?

**Comment by dorianim** [comment]
I think, these are the relevant lines:
```
gitea-gitea-1  | 2022/08/08 10:11:59 ...eb/admin/packages.go:49:Packages() [E] [62f0c54f] GetPackageDescriptors: Malformed version: preview-be4d4b6e7849557ce7ba7bfee4b66c47c27f986a
gitea-gitea-1  | 2022/08/08 10:11:59 [62f0c54f] router: completed GET /admin/packages for 46.114.92.187:0, 500 Internal Server Error in 181.1ms @ admin/packages.go:24(admin.Packages)
```

**Comment by DerGoogler** [comment]
Oh, seems that this not so old

**Comment by dorianim** [comment]
No, definitely not. I think, it has been introduced in https://github.com/go-gitea/gitea/pull/20531

**Comment by dorianim** [comment]
Any idea on how to resolve this? I currently cannot use my packages because of this...
Is there some way to delete the faulty packages from the database?

**Comment by wxiaoguang** [comment]
Could you try to do `update package set semver_compatible=0` ? 

(suggest to backup your table first)

**Comment by dorianim** [comment]
It worked! Thank you so much :)
I'm gonna close this issue for now, let's see, if the problem reappears

**Comment by wxiaoguang** [comment]
I am curious whether this bug exists in 1.17.2 or 1.17-dev/1.18-dev. If yes, it should be fixed. Feel free to open an issue if there is still a problem.

**Comment by KN4CK3R** [comment]
Looks like we need a migration to fix this for existing packages.
