### ISSUE TITLE
update.sh fails for v1.17.0

### ISSUE THREAD

**Issue by germgerm** [go-gitea/gitea#20601]
### Description

$ gitea-update -v 1.17.0
Checking currently installed version...
Make sure to read the changelog first: https://github.com/go-gitea/gitea/blob/main/CHANGELOG.md
Are you ready to update Gitea from 1.16.7 to 1.17.0? (y/N)
y
Upgrading gitea from 1.16.7 to 1.17.0 ...
Downloading https://dl.gitea.io/gitea/1.17.0/gitea-1.17.0-linux-amd64.xz...
curl: (23) Failed writing body (0 != 632)
curl: (23) Failed writing body (0 != 94)
curl: (23) Failed writing body (0 != 641)

### Gitea Version

1.17.0

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

ubuntu 16.04

### How are you running Gitea?

downloaded binary

### Database

MySQL

**Comment by wxiaoguang** [comment]
It seems that the `curl` can not write the downloaded content into the file on disk.

Try to do `curl ... -O ..." on your side to see if there is a problem.

**Comment by germgerm** [comment]
I modified the script and saw that it was a permissions issue - so I assume that sudo is required - haven't tried as I had already updated manually ---- On Mon, 01 Aug 2022 23:25:31 -0400  ***@***.***  wrote ----
It seems that the curl can not write the downloaded content into the file on disk.
Try to do `curl ... -O ..." on your side to see if there is a problem.
