### ISSUE TITLE
Could not mention user is comments with space in username

### ISSUE THREAD

**Issue by jonasfranz** [go-gitea/gitea#2061]
- Gitea version (or commit ref): b93568c
- Operating system: Debian 8 64bit
- Database (use `[x]`):
  - [x] MySQL
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (https://try.gitea.io/Max%20Mustermann/Demonstration/issues/1#issuecomment-624)

## Description

It is not possible to mention users with a space in their username like "Max Mustermann". Perhaps a solution with quotation marks would be good. (Example: @"Max Mustermann")

**Comment by lunny** [comment]
That should be login name, I think a login name with space is not allowed?

**Comment by lafriks** [comment]
I think it should not be allowed. What login source is used for that user?

**Comment by jonasfranz** [comment]
@lafriks @lunny I registered the User with an email address. At the signup I choose a allowed username. Then I renamed the Account into "Max Mustermann".

**Comment by lunny** [comment]
The username should not be with space and other special characters. This is a bug on #2066. It's not a markdown rendering issue.
