### ISSUE TITLE
Default merge message changed in 1.17.0

### ISSUE THREAD

**Issue by parnic** [go-gitea/gitea#20634]
### Description

Prior to 1.17.0, clicking the merge button on a PR would pop up a box that either contained the PR description (the default behavior) or a combination of all commit messages (if `POPULATE_SQUASH_COMMENT_WITH_COMMIT_MESSAGES` is set in the INI). In 1.17.0, the commit message only contains the contents of the default merge template and nothing else.

Prior to 1.17.0: `pull.GetSquashMergeCommitMessages()` was used to populate the box (even when it wasn't a squash merge). This is set to `ctx.Data["GetCommitMessages"]` in `repo.PrepareViewPullInfo()`.
After 1.17.0: `defaultMergeMessage` in pull.tmpl is set to a specific Reviewed-on string that doesn't include the PR description or commit messages or anything.

If this new behavior is the intended method, it would be nice to config-ify it, but it feels more like a bug than anything.

### Gitea Version

1.17.0, 1.18.0+dev-203-ge43bb2b0b

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

<img width="666" alt="image" src="https://user-images.githubusercontent.com/888126/182414326-b8ea121c-e36d-4b00-b2a4-600fdd2a1135.png">

<img width="655" alt="image" src="https://user-images.githubusercontent.com/888126/182414377-23efa8f1-643d-49b3-8e28-131585e6286e.png">

### Git Version

2.37.1

### Operating System

Ubuntu 20.04

### How are you running Gitea?

Downloaded from Github releases page.

### Database

PostgreSQL

**Comment by wxiaoguang** [comment]
Will it fixed by #20618 ?
* https://github.com/go-gitea/gitea/pull/20618

**Comment by parnic** [comment]
> Will it fixed by #20618 ?
> 
> * [Add Commit message to PR #20618](https://github.com/go-gitea/gitea/pull/20618)

Yes! That's exactly the change I was making locally to fix this, haha. Great! 😄
