### ISSUE TITLE
nuget package push returns 400 if already exists - should be 409

### ISSUE THREAD

**Issue by germgerm** [go-gitea/gitea#20644]
### Description

as per subject , nuget push of existing package should return 409 Conflict - but is returning 400 Bad request

### Gitea Version

1.17.0

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

2.7.4

### Operating System

ubuntu 16.04

### How are you running Gitea?

downloaded binary

### Database

MySQL

**Comment by wxiaoguang** [comment]
Wait for backport
