### ISSUE TITLE
[v1.17.0]  Automerge / Admin merge sometimes doesn't work

### ISSUE THREAD

**Issue by viceice** [go-gitea/gitea#20646]
### Description

I've two issues[^1] which are closely related with latest gitea v1.17.0

1. I can't see the automerge feature, but normally i can force merge as admin.

2. Today i couldn't merge PR's because they where blocked because they are outdated

[^1]: https://discourse.gitea.io/t/gitea-automerge-when-succeed-v1-17/5620

### Gitea Version

1.17.0

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![](https://user-images.githubusercontent.com/1798109/182147212-2be87e30-7797-4fec-94c2-a774ed0c4595.png)

![image](https://user-images.githubusercontent.com/1798109/182529667-48fd29b9-d6f4-4575-9179-dac741c4b788.png)

### Git Version

offical docker image

### Operating System

offical docker image

### How are you running Gitea?

2 node HA from official gitea chart with redis / nfs

### Database

PostgreSQL

**Comment by viceice** [comment]
After updating the protection rule i could merge ad admin again.

**Comment by viceice** [comment]
I also saw PR's stuck in merge conflict check
![image](https://user-images.githubusercontent.com/1798109/182536027-602a3949-8494-4b54-93fe-effd298b62a4.png)

**Comment by viceice** [comment]
sometimes i also see broken fork information after using the merge update button

![image](https://user-images.githubusercontent.com/1798109/182536428-dabb7bfa-3d04-4be7-b464-bf1523188286.png)

**Comment by viceice** [comment]
Ok, i need to enable at least two merge methods to get the dropdown for automerge

**Comment by lunny** [comment]
I think this is the same as #24445 and should be fixed by #30780
