### ISSUE TITLE
Repo generated from template fails when template has no webhooks

### ISSUE THREAD

**Issue by gabriel-vasile** [go-gitea/gitea#20641]
### Description

To reproduce in web UI:
1. create a repo and check "Mark repository as template"
2. create another repo using the template in step 1. In "Template Items", check "Webhooks" checkmark. 

What I expected: step 2 creates a new, empty repo
What happened: `web/repo/repo.go:195:handleCreateError() [E] CreatePost: no element on slice when insert`. Pretty cryptic error I would say. grepping project returns no result.

### Gitea Version

head main

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

./gitea web

### Database

SQLite

**Comment by wxiaoguang** [comment]
Wait for backport

**Comment by zeripath** [comment]
Fixed by #20768
