### ISSUE TITLE
Document Manager role & the gpg keys since they can tag and release

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#20653]
we have written down [maintainers](https://github.com/go-gitea/gitea/blob/main/CONTRIBUTING.md#maintainers) and [owners](https://github.com/go-gitea/gitea/blob/main/CONTRIBUTING.md#owners).

but since then there where a new role added to move some load of of owners. they do have rights to:
- ban users in gitea related chats
- push tags (and so release versions) ...
- Can merge PRs on github/gitea.com

Packagers did want something like https://github.com/nodejs/node/#release-keys to ensure only trusted people did do a release

**Comment by 6543** [comment]
We are di-/assigned by the owners rather than an election process. The only explicit criteria for assignment is, having to be a maintainer first.

**Comment by 6543** [comment]
" ... Can moderate various platforms, such as open/close/lock issues/PRs on github, moderation of Discord/Matrix (delete messages, kick/ban users)
Privy to security related issues (some maintainers are as well, so this may need other clarification) ..."

**Comment by lunny** [comment]
This should be resolved by #24492

**Comment by lunny** [comment]
Since #24492 merged, I think we can close this one and further information could be sent to another PR.
