### ISSUE TITLE
Generic package multiple assets

### ISSUE THREAD

**Issue by pchampio** [go-gitea/gitea#20651]
### Feature Description

Gitea generic package only supports adding a single asset for a given tag version. https://github.com/go-gitea/gitea/blob/86e5268c396bd89716b2617a4949837982c1b0c3/routers/api/packages/generic/generic.go#L92-L112

I think having the possibility to add multiple assets (for example Windows, MacOS, Linux executable) to a single version is very common.

Ping @KN4CK3R :wink:

**Comment by KN4CK3R** [comment]
Sure, may be a bad decission to allow only one file per version. I did it because I don't know how to count the downloads of a version with multiple assests. Should every download of single file increase the version download counter?

**Comment by KN4CK3R** [comment]
Added this in #20661 and increases the download counter for every file.

**Comment by pchampio** [comment]
> Should every download of single file increase the version download counter?

Definitely!
