### ISSUE TITLE
Saving files in web editor sometimes fails to do a `git reset --hard`

### ISSUE THREAD

**Issue by richmahn** [go-gitea/gitea#2065]
- Gitea version (or commit ref):
- Git version: 1.1.2
- Operating system: Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No - just seems to happen sometimes, maybe when multiple people are editing
  - [ ] Not relevant

## Description

Sometimes when saving a change to a file through the Gitea web editor, it can fail to do a reset --hard.

Looks like multiple people editing the repo is causing the way Gitea works with a checked out copy to fail. This may be because before I came along to make the web editor for Gitea, it wasn't anticipated to make changes through Gitea. Before we had the edit/delete/add files pages, it just checked out repos to read them, not change them in a temp dir. Now that we change them the same way it checks them out to read the repo, we could be getting collisions (when I experienced this issue, as shown in screen shot below, I saw multiple files deleted but it never successfully committed so it was still in a commit/merge phrase of some sort).

We probably need to make a change to actually do a clean checkout, make changes, commit, and delete the checked out repo? Yet that could cause it to slow down if the repo has lots of files or big files. Right now it keeps trying to work with the same checked out repo in the temp directory for multiple reads, writes, deletes, etc. Probably the reason for this issue.

Keeping just one checked out of the repo would be faster, as then doesn't have to check out big repos, but when you get to people working on different branches and some editing online while some pushing from their local git, things could get out of sync.

Need to find the best solution for this. Below is a screen shot of such a failure. For some reason it wants to reset to a commit that doesn't exist.

...

## Screenshots

![failed_git_reset](https://user-images.githubusercontent.com/2839925/27552654-6ea1fb50-5a65-11e7-85b8-cee48fba3091.png)

**Comment by richmahn** [comment]
When I did a `git log` I didn't see the commit hash given in the failure message.

**Comment by bkcsoft** [comment]
it's not a commit sha, it's a tree object. `git cat-file tree d579e505a72` should do the trick

**Comment by bkcsoft** [comment]
(which is binary, so I'd suggest piping it through ` | hexdump -C`)

**Comment by richmahn** [comment]
@bkcsoft Right, should I have said tree object as the error even says. Still, it seems that the way Gitea works with ONE local clone of the repo for all edit/add/delete requests seems to not be fail safe, as multiple times I have had to clear out my temp directory for the repos.  I assume your commands are what I could do to fix that repo, but it is just as easy to remove the whole directory and then save the file again from the edit page. Yet many of our users can't do that, having to wait until someone with server access can clear the temp directory.

**Comment by bkcsoft** [comment]
that command just verifies that the tree exists, nothing else

**Comment by lafriks** [comment]
Please reopen if problem still exists
