### ISSUE TITLE
Unable to generate repo if template has no Issue Labels

### ISSUE THREAD

**Issue by gabriel-vasile** [go-gitea/gitea#20654]
### Description

To reproduce in web UI:
1. create a repo and check "Mark repository as template"
2. create another repo using the template in step 1. In "Template Items", check "Issue Labels" checkmark. 

What I expected: step 2 creates a new, empty repo
What happened: status code 500, `web/repo/repo.go:195:handleCreateError() [E] CreatePost: no element on slice when insert`. 

### Gitea Version

     1.18.0+dev-209-g7a31292c2 built with GNU Make 4.3, go1.18 : bindata, sqlite, sqlite_unlock_notify

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

./gitea web

**Comment by wxiaoguang** [comment]
Wait for backport
