### ISSUE TITLE
Gitea 1.17 does not set PR description in commit detail when squash merging

### ISSUE THREAD

**Issue by achikhv** [go-gitea/gitea#20662]
### Description

This issue somehow relates to [20562](https://github.com/go-gitea/gitea/issues/20562#issue-1323434770).

Prior to 1.17 button "Create squash commit" opened a form with PR's description used as commit details. It was a handy little feature, and in 1.17 it has gone. Now commit details contains only "reviewed -on" field, and I must copy PR description and paste it to this field.

Is it possible to return this function? 

Here is my test PR in try.gitea.io
https://try.gitea.io/achi/test/pulls/1

Thanks in advance.

### Gitea Version

1.17.0+6-gbd2218e14

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

Windows

### How are you running Gitea?

Downloaded binaries here:
https://dl.gitea.io/gitea/1.17

### Database

MSSQL

**Comment by wxiaoguang** [comment]
It should have been fixed by 
* https://github.com/go-gitea/gitea/pull/20645
for 1.17

**Comment by achikhv** [comment]
Thanks! Will check it out after build completes.
