### ISSUE TITLE
Reserved user name check missing from binary

### ISSUE THREAD

**Issue by rmbleeker** [go-gitea/gitea#20669]
### Description

The binary downloaded from https://dl.gitea.io/gitea/1.17.0/gitea-1.17.0-linux-amd64 is missing the `check-user-name` command from the **Gitea doctor** that is mentioned in the [release notes](https://blog.gitea.io/2022/07/gitea-1.17.0-is-released/#-reserved-usernames-updated-18438httpsgithubcomgo-giteagiteapull18438).

### Gitea Version

1.17.0

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![Screenshot from 2022-08-04 17-07-49](https://user-images.githubusercontent.com/4312801/182882403-fb892fd6-dc1f-400e-ac0c-501c540e87d2.png)

### Git Version

2.27.0

### Operating System

Red Hat Enterprise Linux 7.9

### How are you running Gitea?

Download from https://dl.gitea.io/gitea/

### Database

SQLite

**Comment by jolheiser** [comment]
Thanks for the report! This was indeed an error, we will get the check backported for our 1.17.1 release
