### ISSUE TITLE
Gitea 1.17.0 mirror update cron error

### ISSUE THREAD

**Issue by vcsmartdata** [go-gitea/gitea#20667]
### Description

"Update mirrors" cron does not finish due to a SQL query error as reported in system notices and in logs:

<img width="1376" alt="Screen Shot 2022-08-04 at 15 40 32" src="https://user-images.githubusercontent.com/75434253/182849359-779702b9-b7f3-447a-9508-1e9018b3b131.png">

```
Aug  4 15:36:59 git gitea[980518]: 2022/08/04 15:36:59 ...s/repo/pushmirror.go:103:PushMirrorsIterate() [I] [62ebbd6b] [SQL] SELECT `id`, `repo_id`, `remote_name`, `interval`, `created_unix`, `last_update`, `last_error` FROM `push_mirror` WHERE (last_update + (`interval` / ?) <= ?) AND (`interval` != 0) ORDER BY last_update ASC LIMIT -1 [1s 1659616619] - 1.073849ms
Aug  4 15:36:59 git gitea[980518]: 2022/08/04 15:36:59 ...ces/mirror/mirror.go:135:Update() [E] [62ebbd6b] PushMirrorsIterate: Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-1' at line 1
```

### Gitea Version

1.17.0

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

2.25.1

### Operating System

Ubuntu 20.04.4

### How are you running Gitea?

Running a Gitea binary downloaded from https://gitea.io/ as a systemd service on Ubuntu 20.04.

MySQL version is: 8.0.30

### Database

MySQL

**Comment by zeripath** [comment]
What version of MySQL are you running?

**Comment by zeripath** [comment]
Aha I see the issue.

Workaround for the moment is to remove your settings on `[cron.update_mirrors]`

https://docs.gitea.io/en-us/config-cheat-sheet/#cron---update-mirrors-cronupdate_mirrors

I would strongly recommend that you re-review your settings related to this - the cron code has changed to make the queue limits work much better.

**Comment by vcsmartdata** [comment]
yeah I figured it out too a couple of days ago, just had no time to update the issue here
I had a custom configuration for cron, after changing cron.update_mirrors SCHEDULE to @every 2m it started to work again

thank you for the update
