### ISSUE TITLE
meilisearch search engine support

### ISSUE THREAD

**Issue by morph027** [go-gitea/gitea#20665]
### Feature Description

Similar to https://github.com/go-gitea/gitea/issues/6648, having the ability to use a better (faster, more efficient, ...) search index would be nice. We recently discovered https://github.com/meilisearch/meilisearch which behaves quite nice according to our devs. And in terms of footprint, it's much more lightweight that Elasticsearch.

**Comment by techknowlogick** [comment]
go SDK can be found here: https://github.com/meilisearch/meilisearch-go
