### ISSUE TITLE
Internal server error after unpublishing an npm package

### ISSUE THREAD

**Issue by AuspeXeu** [go-gitea/gitea#20670]
### Description

1. `npm publish` a package to an organisation
2. `npm unpublish` the package
3. the package is still listed under the organisation
4. click the package -> 500
5. try to publish the same package + version -> `400 Bad Request - PUT https://[...] - Package version already exists`

### Gitea Version

1.17.0

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![Uploading image.png…]()

### How are you running Gitea?

docker

### Database

PostgreSQL

**Comment by KN4CK3R** [comment]
`npm unpublish` is not supported. If you want to, you can create a new "feature request" issue.

For the 500 error I have published a fix in #20675.
