### ISSUE TITLE
Push event log missing in main page

### ISSUE THREAD

**Issue by maoxuner** [go-gitea/gitea#20678]
### Description

After I had upgraded gitea version from `1.16.9` to `1.17.0`, push event activities never shown in dashboard recent logs.

There must be something wrong with push event. And may be it is related to this issue #20482 .

### Gitea Version

1.17.0

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

<img width="565" alt="2" src="https://user-images.githubusercontent.com/104855611/182990929-90dbbba2-6385-4e3e-a058-e996a140692b.png">

As is shown in the snapshot. I upgraded gitea version 5 days ago in repo `greendata/devops-server`. Then I pulled the repo and upgraded my server. After that, serveral pushes pushed, but none was shown in recent activities list.

### Git Version

 2.36.2, Wire Protocol Version 2 Enabled

### Operating System

CentOS 7 with DockerCE 18.09.7

### How are you running Gitea?

Docker image from official registry `gitea/gitea:1.17.0`

### Database

MySQL

**Comment by wxiaoguang** [comment]
https://blog.gitea.io/2022/07/gitea-1.17.0-is-released/

![image](https://user-images.githubusercontent.com/2114189/182997065-2bd3fe41-8c9e-4cd8-bf5d-283a98f6cde8.png)

**Comment by pawmaster** [comment]
Thank you very much.
I have checked upgrade document [Upgrade from an old Gitea](https://docs.gitea.io/en-us/upgrade-from-gitea/), but nothing mentioned here. I think there should be some work of the docs.

**Comment by wxiaoguang** [comment]
Thank you for your suggestion (I thought there were some documents, but there aren't 😂)

I propose a PR for the document.

* #20682
