### ISSUE TITLE
set DISABLE_DOWNLOAD_SOURCE_ARCHIVES to true, but still can download from UI

### ISSUE THREAD

**Issue by rz2014** [go-gitea/gitea#20685]
### Description

There is a download icon in repo as following:

![image](https://user-images.githubusercontent.com/10285656/183047877-5ff65b3b-1a63-42cc-b944-6fb9f8a271d6.png)

After set `DISABLE_DOWNLOAD_SOURCE_ARCHIVES = true` in `app.ini` file， and restart gitea. But it's still there! as shown above.

### Gitea Version

1.17

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![image](https://user-images.githubusercontent.com/10285656/183048794-19a1473d-7b47-4e95-87a1-8b083123226d.png)

### Git Version

2.36.2

### Operating System

docker

### How are you running Gitea?

Deploy gitea by docker.  the docker image is from hub.docker.com

### Database

PostgreSQL

**Comment by schmurtzm** [comment]
Still not working on 1.18.3
