### ISSUE TITLE
Reviewing a lot of files resets the counter when loading more

### ISSUE THREAD

**Issue by kolaente** [go-gitea/gitea#20681]
### Description

**Steps to reproduce:**

1. Create a repo
2. Create a PR with a lot of changed files (in my case 193)
3. Start reviewing the PR, marking each reviewed file as "viewed" with the checkbox
4. Once the first 100 files are marked as viewed, click the "load more" button at the end of the page to load the rest of the files
5. Mark the 101st file as viewed

**Expected behavior:**

101 files are marked as viewed

**Actual behavior:**

99 files are marked as viewed

The very first file is un-marked as viewed when marking the 101st file as viewed. When I mark it as viewed again, 100 files are marked as viewed again. When I then try to mark another of the newly loaded files as viewed, it unmarks the first file again, resulting in 99 files are marked as viewed.

### Gitea Version

1.17.0

### Can you reproduce the bug on the Gitea demo site?

Probably (on the go right now, will try to reproduce it later)

### How are you running Gitea?

Official docker image.

### Database

MySQL

**Comment by delvh** [comment]
Hmm.
I have absolutely no idea what could cause this.
I'm fairly certain I've tested the behavior on #19007, and there it worked correctly.
To be fair, I only tested by marking **some** and not all PRs as viewed before loading files dynamically, but still?
I don't see anything in the code (**I wrote**) (`web_src/js/features/pull-view-file.js`) that would cause this, unless `this.checked` (where `this` is a checkbox) was inverted for some reason?

**Comment by delvh** [comment]
Yep, just confirmed it on try.gitea.io.
I had even stranger behavior: For me, the counter was reset to `0`, meaning that when I clicked on the `101`st checkbox, the `1`st checkbox was acted upon, and as that was already selected, it was de-selected, thus bringing the counter down to `-1`.

So, to me, the first issue appears to be an index issue where if `x` files are loaded initially, all subsequent ones use `index - x` for the viewed checkbox JS.
The second issue is that the counter was reset to `0`, which it shouldn't.
