### ISSUE TITLE
Markdown rendering of links with titles

### ISSUE THREAD

**Issue by IzzySoft** [go-gitea/gitea#2068]
- Gitea version (or commit ref): 1.1.2
- Git version: 2.1.4
- Operating system: Bananian (Debian Jessie, ARM)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
  - [x] could not try, server timed out
- Log gist:

## Description
Markdown rendering of links with titles is incomplete and sometimes even fails, which I just noticed in the `README.md` file of one of my repos (a mirror of [Adebar](https://github.com/IzzySoft/Adebar)):

* `[Adb](http://en.wikipedia.org/wiki/Android_Debug_Bridge "Wikipedia: Android Debug Bridge")`: Title is missing (usually shown on mouse-over):  

        <a href="http://en.wikipedia.org/wiki/Android_Debug_Bridge" rel="nofollow">Adb</a>

* `[Bash](http://en.wikipedia.org/wiki/Bash_%28Unix_shell%29 "Wikipedia: Bash (Unix shell)")`: fails and renders as `Bash")`:

        It is mainly based on Bash")

So the `title` attribute is at best omitted or, if containing parenthesis, the entire link breaks.

## Screenshots

[![Screenshot](https://i.imgur.com/XdQYiWsm.png)](https://i.imgur.com/XdQYiWs.png)  
<sup>Screenshot (click for larger image)</sup>

**Comment by bkcsoft** [comment]
Added `kind/testing` since we also not testing for this

**Comment by IzzySoft** [comment]
This one was somehow forgotten it seems. I'll have to check if the problem itself was solved and just this issue forgotten to close (cannot access my Gitea instance from where I currently am).

**Comment by IzzySoft** [comment]
Issue still exists with Gitea 1.7. Any chance to see it fixed before its 2nd birthday? :smiley:

**Comment by lafriks** [comment]
Nobody is working on this so any help would be greatly appreciated

**Comment by techknowlogick** [comment]
I think this issue may be caused by the upstream markdown library and would need to be fixed there.

**Comment by IzzySoft** [comment]
I'd help out if I could – but I'm completely lost with Go, sorry…

**Comment by IzzySoft** [comment]
Thanks, @lunny – I just checked, the issue still exists with v1.7.5 (the latest release with binaries attached).

**Comment by 6543** [comment]
@IzzySoft can you check again?

the markdown rendering lib has changed

**Comment by zeripath** [comment]
This is also fixed.

See https://try.gitea.io/arandomer/Adebar

**Comment by IzzySoft** [comment]
I can confirm what @zeripath mentioned on try.gitea for the original place at Codeberg: https://codeberg.org/izzy/Adebar/ – so thanks, this indeed seems to be fixed!
