### ISSUE TITLE
Problems with packages publishing.

### ISSUE THREAD

**Issue by BlueBerrySans365** [go-gitea/gitea#20706]
### Description

Problems with publishing packages. Tried with Twine and Curl.
1. Twine situation:
> Publishing `.tar.gz` file with `twine upload --repository gitea ./dist/PythonPack-3.2.0.tar.gz` ends with :
```
INFO     Response from https://kepar.ml/api/packages/Nmwin_D/pypi/:                                                                                           
         500 Internal Server Error
```
Upd: For some reason i got ``INFO     Error 1366: Incorrect string value: '\xF0\x9F\x92\xA4  ...' for column `gitea`.`package_version`.`metadata_json` at row 1`` last time
2. Curl situation
> Publishing random file with :
```
curl --user Nmwin_D:password \
     --upload-file sometextfile.txt \
     https://kepar.ml/api/packages/Nmwin_D/generic/test/1.0.0/sometextfile.txt
```
> ends with: `reqPackageAccess`

### Gitea Version

1.17.0+rc2-18-gfc7b5afd9

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

2.25.1

### Operating System

Ubuntu

### How are you running Gitea?

Gitea running from systemd

**Comment by KN4CK3R** [comment]
Problem 1:
Could you upload the `PythonPack-3.2.0.tar.gz` file somewhere so I can test it?

Problem 2:
Works without problems for me. I created a user with your name and the password `password` and executed your curl request:

`curl --user Nmwin_D:password --upload-file Makefile http://localhost:3000/api/packages/Nmwin_D/generic/test/1.0.0/sometextfile.txt`

![grafik](https://user-images.githubusercontent.com/1666336/183357958-1e1798cc-d128-4264-a77b-1582de05fbdb.png)

**Comment by wxiaoguang** [comment]
I guess the user is using MySQL/MariaDB with utf8mb3 but not utf8mb4

Then there are some emoji chars in the `metadata_json`, the `'\xF0\x9F\x92\xA4` is emoji 💤

I would suggest the author to alter all tables to utf8mb4

**Comment by BlueBerrySans365** [comment]
@KN4CK3R, here is PythonPack: https://nmsmp.ml/files/hmtai-builds/hmtai-modified-3.2.0.tar.gz
@wxiaoguang, i'll try this

**Comment by wxiaoguang** [comment]
Your PKG-INFO

![image](https://user-images.githubusercontent.com/2114189/183400530-af940aff-b218-46f6-8fb2-46415eb51306.png)

**Comment by KN4CK3R** [comment]
Thank you, must be a problem at your end. Works for me:
![grafik](https://user-images.githubusercontent.com/1666336/183400524-d1da4002-a09e-47f8-99d4-ede3a6f05b11.png)

**Comment by BlueBerrySans365** [comment]
I'll try to alter all tables in MariaDB to utf8mb4

**Comment by BlueBerrySans365** [comment]
Fixed with `utf8mb4`, thank you)
