### ISSUE TITLE
Both Repository and System webhooks not firing on deletion of a repository

### ISSUE THREAD

**Issue by kevinwyso** [go-gitea/gitea#20705]
### Description

Repository creation webhooks are fired, but the complimentary deletion webhooks aren't firing upon deleting the repository. Tested a system wide webhook as well and the same result, no webhook is fired.

### Gitea Version

1.17

### Can you reproduce the bug on the Gitea demo site?

(In Progress)

### Git Version

N/A

### Operating System

Ubuntu 20.04 

### How are you running Gitea?

Docker container using the gitea/gitea:latest image as of 07/30

### Database

MySQL

**Comment by KN4CK3R** [comment]
May be related to https://github.com/go-gitea/gitea/pull/17940#discussion_r766447055

**Comment by AdamMajer** [comment]
This one seems to be fixed. In 1.22 the deleted webhook is fired when a repository (fork) is removed from an organization.
