### ISSUE TITLE
Add issues at organization level

### ISSUE THREAD

**Issue by MarcelCoding** [go-gitea/gitea#20715]
### Feature Description

Add issues at an organization level to be able to do a issue hierarchies in projects that span over multiple repos (e.g. microservices)

E.g. A feature needs stuff done in the frontend and the backend, therefore a top-level issue would be nice.

**Comment by PaulBol** [comment]
Replaced by #23827?

**Comment by lunny** [comment]
Let's go #23827 to continue discuss.
