### ISSUE TITLE
Inlucde activity from mirrored repos into activity graph

### ISSUE THREAD

**Issue by MarcelCoding** [go-gitea/gitea#20714]
### Feature Description

I don't quite know the actual behavior.

I think only the activity that actually happens over Gitea is included. It would be nice if also the activity from mirrors/migrations would be included. I don't know if the activity is included if someone different pushed on behalf of you (e.g. interactive rebase, ...), if not this would also be nice.

(low priority)

**Comment by lafriks** [comment]
it's not really possible as activity is in commits and parsing all commits that have been changed between sync would be quite slow. Also if user registers later on or changes email that historical commit had would still not show up in activity so it would always be inaccurate anyway

**Comment by MarcelCoding** [comment]
The email change thing is a point. But wouldn't it be possible to check this on every push - there is no other location where commit could be changed other than pushes.

**Comment by lafriks** [comment]
yes but commit count can be large (for example initial migration of linux kernel), branches can also be deleted etc. What if user registers in this gitea instance after repository was initially mirrored already?

**Comment by lafriks** [comment]
That is also reason why we do not count also in regular repository commit history. If you would push 100 commits that you have been working on for year, you would still have single activity event in your activity graph.

**Comment by MarcelCoding** [comment]
So only pushing is an activity event and not commiting?

**Comment by lafriks** [comment]
> So only pushing is an activity event and not commiting? Anyways thanks for your time and clarification.

yes
