### ISSUE TITLE
[1.17.0] Search label and assignee fields pressing enter has no effect

### ISSUE THREAD

**Issue by tyroneyeh** [go-gitea/gitea#20727]
### Description

Clicking a label in an existing issue or typing a keyword in the assignee field and pressing Enter does not select search results

### Gitea Version

1.17.0

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

systemd

### Database

PostgreSQL

**Comment by wxiaoguang** [comment]
I think it will be fixed by  Make issue label dropdown support Enter #23014
