### ISSUE TITLE
docker registry delete download counts on push

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#20722]
if you push a docker image to same existing tag, download counts are erased.

to reproduce:
1. push a docker image with tag `:latest`
2. delete image local and download image -> download count shows 1
3. push a new image with tag `:latest`
4. download count is 0 again

gitea version: v1.17.0 - main

**Comment by 6543** [comment]
@KN4CK3R is this intended?

**Comment by KN4CK3R** [comment]
No, fixed in #20728
