### ISSUE TITLE
Push Mirror show wrong (and always same) remot url

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#20732]
gitea version: v1.17.0 <-> main

go to any repo and add two push mirrors with different urls e.g. (`https://github.com/hahahah.git` & `https://codeberg.com/2.git`)

reproducable on codeberg and try: https://try.gitea.io/ngc6543/PartyGames/settings
![image](https://user-images.githubusercontent.com/24977596/183651763-62d10746-a8a9-4f3f-82d9-97c10d66dfb6.png)

**Comment by noerw** [comment]
Is this fixed by https://github.com/go-gitea/gitea/pull/20593?
