### ISSUE TITLE
Error while extracting downloaded file

### ISSUE THREAD

**Issue by nesc1** [go-gitea/gitea#20731]
### Description

Using gitea as a conan package remote server I'm having some problem with some packages after building them on the local machine upload the package id to the gitea server (conan upload) and then after i remove everything on local machine when trying to download the same package with the same settings for example for boost and icu I'm getting always the following problems:

```
icu/71.1: Retrieving package 09db9ef54d82f0b6035e5bb063b220fd3ba58442 from remote 'gitea'
Downloading conanmanifest.txt completed [12.58k]
Downloading conaninfo.txt completed [0.71k]
Downloading conan_package.tgz completed [0.00k]
Decompressing conan_package.tgz: 0.00B [00:00, ?B/s]icu/71.1: ERROR: Exception while getting package: 09db9ef54d82f0b6035e5bb063b220fd3ba58442
icu/71.1: ERROR: Exception: <class 'conans.errors.ConanException'> Error while extracting downloaded file '/home/nuno/.conan/data/icu/71.1/_/_/dl/pkg/09db9ef54d82f0b6035e5bb063b220fd3ba58442/conan_package.tgz' to /home/nuno/.conan/data/icu/71.1/_/_/package/09db9ef54d82f0b6035e5bb063b220fd3ba58442
file could not be opened successfully

ERROR: Error while extracting downloaded file '/home/nuno/.conan/data/icu/71.1/_/_/dl/pkg/09db9ef54d82f0b6035e5bb063b220fd3ba58442/conan_package.tgz' to /home/nuno/.conan/data/icu/71.1/_/_/package/09db9ef54d82f0b6035e5bb063b220fd3ba58442
file could not be opened successfully
```

(side note file is empty)
```
❯ ls -al /home/nuno/.conan/data/icu/71.1/_/_/dl/pkg/09db9ef54d82f0b6035e5bb063b220fd3ba58442/
total 28
drwxr-xr-x 2 nuno nuno  4096 Aug  9 13:31 .
drwxr-xr-x 3 nuno nuno  4096 Aug  9 13:31 ..
-rw-r--r-- 1 nuno nuno   726 Aug  9 13:31 conaninfo.txt
-rw-r--r-- 1 nuno nuno 12878 Aug  9 13:31 conanmanifest.txt
-rw-r--r-- 1 nuno nuno     0 Aug  9 13:31 conan_package.tgz
```

boost/1.79.0 has the same problem...

can you help figure out what is the problem?

### Gitea Version

1.17.0

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

as a service on a raspberry pi 4

### Database

MySQL

**Comment by nesc1** [comment]
ok thank you for your fast reply... I will wait for the next release since the latest version download from here: https://dl.gitea.io/gitea 
is the latest one that I'm using

**Comment by wxiaoguang** [comment]
You can safely use the binaries from https://dl.gitea.io/gitea/1.17 , they are 1.17.1-pre-release (with many bug fixes) at the moment 😁
