### ISSUE TITLE
Edit form doesn't display when editing issue/comment 

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#20747]
### Description

When editing an issue or a comment, the edit form will not be display, and the content of issue/comment also disappeared. It's a regression from #20428 .

### Screenshots

<img width="876" alt="image" src="https://user-images.githubusercontent.com/81045/183877305-6aeedc5c-3639-45cb-996b-2a1c4a315362.png">

### Gitea Version

1b2cd4c4e19c78390be329b4a3ad50ff8857ca8d

### Can you reproduce the bug on the Gitea demo site?

Yes

### Browser Version

Chrome

**Comment by wxiaoguang** [comment]
Caused by:

* https://github.com/go-gitea/gitea/pull/20428/files#r942314751
