### ISSUE TITLE
No way to unfocus comment field without the mouse

### ISSUE THREAD

**Issue by technomancy** [go-gitea/gitea#20752]
### Description

After typing a comment, normally you want to submit it. However, pressing tab (which should move the browser focus on to the next page element) just inserts a literal tab character, which is not useful in the context of the comment entry box. Pressing escape (which is supposed to unfocus the textarea) has no effect. Thus it is necessary to use the mouse to submit a comment, which is an unfortunate accessibility bug.

Repro URL: https://try.gitea.io/technomancy/pengbot/issues/new

I have reproduced in both Firefox and Chromium.

### Gitea Version

1.17.0+52-g7b04535

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

I first noticed this on codeberg.org but made sure it was also reproducible on try.gitea.io.

**Comment by wxiaoguang** [comment]
Ctrl + Enter

* https://github.com/go-gitea/gitea/pull/19729

**Comment by technomancy** [comment]
Thanks for the workaround. That will be useful to me while I wait for this to be fixed and deployed. =)

However, this is still an important bug to fix, because you don't always want to submit the issue; sometimes you want to interact with some other elements on the page first.

**Comment by wxiaoguang** [comment]
I agree that the a11y should be improved. At the moment Gitea doesn't have good a11y support (search the issues with "accessibility"), some UI elements just do not work with keyboard. So, improving Gitea's a11y is a big topic.

**Comment by silverwind** [comment]
This is codemirror behaviour. It being a code editor, tab inserts literal tab, so it doesn't act like a regular textarea would be expected. Workaround it to use the textarea button for now, we should make this experience better eventually.

**Comment by KiaraGrouwstra** [comment]
actually, as per the demos for [5](https://codemirror.net/5/) and [6](https://codemirror.net/) this behavior appears amended in 6.
perhaps we could just upgrade it?
i don't actually see where we've defined this dependency tho...

**Comment by KiaraGrouwstra** [comment]
looks like i got thrown off by codemirror being an implicit dependency thru EasyMDE now.
that means this now seems to depend on https://github.com/Ionaru/easy-markdown-editor/issues/505.

**Comment by KiaraGrouwstra** [comment]
potentially addressed by #10729

**Comment by silverwind** [comment]
Fixed with https://github.com/go-gitea/gitea/pull/23876, tab now works.
