### ISSUE TITLE
[UI] Pull request page doesn't contain repo name

### ISSUE THREAD

**Issue by schmittlauch** [go-gitea/gitea#2075]
- Gitea version (or commit ref): 1.1.2
- Git version: 2.12.3
- Operating system: openSUSE (Linux)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant

## Description

The text about which branch should be merged into which other branch doesn't contain the name of the repository. In the screenshot below, it has the form `organisation/branch`
In my opinion the current behaviour is not really intuitive, it should either have the form `org or user/repo:branch` or just `repo:branch`.

## Screenshots

![screenshot_20170628_114846](https://user-images.githubusercontent.com/1479555/27635580-df3df5e6-5c07-11e7-8ca7-847f061951d2.png)

**Comment by bkcsoft** [comment]
if it's changed go for `owner/repo:branch`. Since if you go for `repo:branch` you don't know which fork it's coming from :)

**Comment by lafriks** [comment]
I think best would be something like that: `... from fork_owner/repo:branch into devel`
