### ISSUE TITLE
Edit issue is not working in 1.17.0

### ISSUE THREAD

**Issue by timbze** [go-gitea/gitea#20767]
### Description

I just updated Gitea from 1.16.9 to 1.17.0 and now I can no longer edit my issues.

The first time I click "Edit", nothing happens. The second time it changes to text box so I can edit, but clicking Cancel or Save does nothing.

I don't know if this can be reproduced on the demo site because I'm not getting an email to finish signing up.

### Gitea Version

1.17.0

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/timbze/0966c073b6c9b6951abd3243c449664d

### Git Version

Whatever is in docker image gitea/gitea:1.17.0

### Operating System

Docker on Ubuntu 22.04

### How are you running Gitea?

Docker image: gitea/gitea:1.17.0
Together with postres:14

### Database

PostgreSQL

**Comment by wxiaoguang** [comment]
Maybe you are affected by the cache problem.

* https://github.com/go-gitea/gitea/pull/18348
* https://github.com/go-gitea/gitea/pull/18632

Please clear your browser cache and retry.
