### ISSUE TITLE
Missing commit notifications on the dashboard view from team repositories

### ISSUE THREAD

**Issue by rk-mlu** [go-gitea/gitea#20763]
### Description

This bug is a bit mysterious: In two instances, I noticed that there are commit notifications missing on my dashboard. I first noticed this problem this week after updating to version 1.17.0. Until last week, we ran version 1.16.6. 

To be more precise:
- The repository belongs to an organization. I am the owner of the organization, and I am in the list of watchers.
- The users are **not** in the list of watchers themselves (but that should not affect the content of my dashboard...)
- The users whose commits do not show on my dashboard have both been added as external collaborators to the repo.
- When entering the repository itself, the commits are displayed as expected.
- The repository is also placed at the top in the overview panel of all repositories on the right-hand side of the dashboard, as it should after recent activities.
- When toggling the dashboard view from my user view to the organization view, the commits are still not shown.
- I have not been able to reproduce this behavior when creating a new dummy repo with a new dummy user account. 
- I would rather not like to bother my external collaborators with helping to narrow down the bug.

The notifications have been missing on two different days from two different users. Commit notifications from regular members of the organization always show up, so far.

### Gitea Version

1.17.0

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

2.30.2

### Operating System

Debian 11

### How are you running Gitea?

Our server runs with one of the binaries offered here on GitHub.

### Database

SQLite

**Comment by jclinton-ibboost** [comment]
I've just updated a Gitea instance to 1.17.0 and we are having similar strange behaviour. 

We are no longer seeing any updates on any dashboards from post-update and webhooks no longer trigger after a commit. I've checked the webhooks by triggering them manually and they work so the connection is fine.

Viewing the repositories shows the commits and coming through and the Activity page on the repos is updating as expected.

I also noticed almost all of our repos which were previously private are now public.

**Comment by lunny** [comment]
Please check your docker version if you are using docker. There is a docker version requirement in 1.17.0 release notes.

**Comment by hpodhaisky** [comment]
No, we don't use docker at all.

**Comment by Gusted** [comment]
> * I have not been able to reproduce this behavior when creating a new dummy repo with a new dummy user account.

This likely means there's a missing factor that is causing this, please check if you add a dummy account as external collaborator if the problem happens or if the problem is just limited to the two external collaborators.

I'm also not able to reproduce it, as commits from external collaborators are showing up fine.

**Comment by beamsi** [comment]
We have the same problem since upgrading to 1.17. Commits from personal repositories appear in the newsfeed but not from organization repositories or shared repos. If it helps:, we run the binary and our users are LDAP-Users from an Active Directory.

**Comment by hpodhaisky** [comment]
Our users are also all from an AD. Unfortunately, we still haven't found the missing factor.

**Comment by hpodhaisky** [comment]
LDAP -> Confirmed.

Setup: 

I pushed to a repository with a local user. Two other users were watching: (A) local and (B) LDAP. 

Result: 

Only (A) had the push in his dashboard.

**Comment by beamsi** [comment]
I am not sure anymore that it is purely related to LDAP. Beside my own commit messages I can see comits from 2 other persons from my organization. They both are LDAP users.

**Comment by hpodhaisky** [comment]
Upgrade to 1.17.1 hasn't resolved this issue for us.

**Comment by zeripath** [comment]
If commits are not showing up this is because the hooks are not running.

That could be due to:

1. The hooks are out-of-date - you need to `Resynchronize pre-receive, update and post-receive hooks of all repositories.` from the dashboard
2. You are pushing directly to the repo using an ssh account not controlled by Gitea or your pushing to the repository on the file system.
3. The hooks are not executable because they don't the executable bit set or the unix permissions are incorect.
4. (SystemD) The hooks are not executable because some SystemD permission is not set up properly.
5. (Docker) The hooks are not executable because your version of docker is way out of date and you have been hit by the alpine 3.14 issue that our BREAKING NOTICE expressly warns about.

**Comment by hpodhaisky** [comment]
Thank you. Perhaps your first item may lead the way to find the full explanation. 

Our user hooks are working as before (post-update), but maintenance hooks seem not to be running at all. 

We don't see any new "System Notices". When we manually start a new action (such as "Check for Update") nothing new shows up in  "System Notices". The logs don't give an immediate hint (for me).  Possibly, our app.ini needs to be changed for the new version. We will try a fresh installation (with the shipped app.ini) and then migrate our settings incrementally to the new instance. Hopefully, our problem will become clear or will disappear.

Any clue on how we should proceed is appreciated. 

By if it has to do with the cron jobs, why do we see many pushes in the user's dashboards but not all?

**Comment by romain-marie** [comment]
Hi, it seems to work again after users check, save, and then uncheck and save 'Hide the activity from the profile page' on their preferences.

**Comment by rk-mlu** [comment]
> Hi, it seems to work again after users check, save, and then uncheck and save 'Hide the activity from the profile page' on their preferences.

Thanks, we will try. But on our Gitea instance, we currently have 200+ users. It would be very inconvenient to ask every single user to do this. An admin level workaround would be very welcome.

**Comment by rk-mlu** [comment]
This is how our system notices look like. If I remember correctly, August 8th was the day we upgrade to version 1.17.0.
![Screenshot System Notices](https://user-images.githubusercontent.com/65403623/188923705-8f34003c-8b33-43b7-903e-ec705dfa48bf.png)

**Comment by hpodhaisky** [comment]
I tried running gitea from scratch with all options left as default (1.17.2 amd64, Debian + sqlite3).

I can run monitoring jobs (and the execution counter is increased):

![Screenshot from 2022-09-08 09-21-55](https://user-images.githubusercontent.com/13908728/189060477-cdae4512-0e72-47cf-b2ef-6af030760dec.png)

but nothing shows up in "In System Notices":
![Screenshot from 2022-09-08 09-22-17](https://user-images.githubusercontent.com/13908728/189060487-82b7276f-08f0-4f82-9175-069f26842702.png)

However, with 1.16.9 "System Notices" is populated as expected.

**Comment by lassebm** [comment]
After upgrading from 15.x to 17.x, we experience an issue like this. All commits pushed by an _organization_ using deploy keys with write access are not shown in the dashboard of owner or member users of the org/repo receiving the push. The commits _are_ shown on the dashboard of admin users. We've tried the "Resynchronize pre-receive, update and post-receive hooks of all repositories." as mentioned without luck. Let me know if you need a seperate issue for this or need any additional information.

**Comment by wxiaoguang** [comment]
This issue has got a lot of voices, I am not sure whether all problems have been resolved here, so I think it time to close this one in a few days, and feel free to open new issues for the still existing problems (to keep the discussion more focused).

Please refer to this comment for more details, it also explains how the git push hook works.
* https://github.com/go-gitea/gitea/issues/21129#issuecomment-1260802986

If you think you encounter a bug, it needs more information to debug. It would be very helpful to provide a reproducible setup (ex: docker-compose config and steps).

**Comment by hpodhaisky** [comment]
Unfortunately, the our problem initially reported has not been resolved (1.17.2 -- no docker).  The nature of this bug makes it hard to specify exactly when it occurs.

**Comment by wxiaoguang** [comment]
If I understand correctly, the key conclusion at the moment is:

* "I have not been able to reproduce this behavior when creating a new dummy repo with a new dummy user account."
* "I pushed to a repository with a local user (U). Two other users were watching: (A) local user, (B) LDAP user.": only the local user A can see the push activity of user U.

Right?

**Comment by hpodhaisky** [comment]
Thanks for taking this forward. The conclusion (for us, at the moment) is:

- When LDAP users pushed to a joint repository other LDAP users don't see it in their notification board _occasionally_
- We don't observe this for none-LDAP users -- but we don't have many, thus it might be a random coincidence
- If it is related to hooks, we observe that the with >1.17.0 the "System notices" is almost empty, this is reproducible with an empty, dummy setup, see https://github.com/go-gitea/gitea/issues/20763#issuecomment-1240333858

**Comment by wxiaoguang** [comment]
For  "When LDAP users pushed to a joint repository other LDAP users don't see it in their notification board occasionally" and "We don't observe this for none-LDAP users -- but we don't have many, thus it might be a random coincidence":

* Then the problem is not related to the git hook problem. Without more related logs/clues or reproducible steps, I can not think about a debug plan for it.


For "If it is related to hooks, we observe that the with >1.17.0 the "System notices" is almost empty, this is reproducible with an empty, dummy setup, see ...": 
* it's not related, see: https://github.com/go-gitea/gitea/pull/19221

**Comment by hpodhaisky** [comment]
Many thanks for the explanations.

Please let me know what log/debug information would help resolve this issue.

**Comment by wxiaoguang** [comment]
At least:
* The trace logs when the result is correct
* The trace logs when the result is incorrect.

**Comment by wxiaoguang** [comment]
ps: I would suggest you to create a new Gitea instance (use the same LDAP source) to reproduce the problem. Then the logs will be very clear, and you may find differences (between instances) by yourselves. If everything works fine on your new instance and no obvious error logs, then it won't (99%...) be a Gitea problem.

**Comment by hpodhaisky** [comment]
Many thanks, I will try. But I'am not too optimistic to find something very soon as I don't have access to other LDAP accounts. Also note that the trouble started immediately after upgrading to 1.17.0.

**Comment by hpodhaisky** [comment]
We have finally found a workaround / the solution:

As gitea administrator do for every user the following:

Site Administration -> Edit User Account -> Update User Account 

Don't change any user setting, just press the green button once. After this, all commits from this user are become visible on the relevant dashboards again. We are very happy  -- it was really annoying not to see all the changes.

Thus the issue must have been related the migration of the database format (sqlite for us) when upgrading from 1.16.9 to 1.17.0.

Thanks for all the help and advice given here.

**For us this issue is now solved satisfactorily, it can be closed.**

**Comment by beamsi** [comment]
> We have finally found a workaround / the solution:
> 
> As gitea administrator do for every user the following:
> 
> Site Administration -> Edit User Account -> Update User Account
> 
> Don't change any user setting, just press the green button once. After this, all commits from this user are become visible on the relevant dashboards again. We are very happy -- it was really annoying not to see all the changes.


Thanks a lot. That solved it!!!

**Comment by rk-mlu** [comment]
After applying the workaround, we noticed no further problems related to this issue for the last two months. Thus, I guess, it is time to close the issue.

Many thanks to everyone for supporting us!

**Comment by esbennn** [comment]
I'm currently experiencing this issue after upgrading from 1.14.x to 1.17.3 a few weeks ago.

We're a small team of developers using just one organization, which is the owner of most repositories. 
The solution posted by @hpodhaisky does not seem to work for me.
Heatmap for the last couple of weeks only shows activities such as issues and newly created repositories. 

I'm running the Gitea binary on debian with MariaDB.
I'm not sure how to investigate.

**Comment by esbennn** [comment]
Okay, so mine was not actually a gitea related issue.
When upgrading, I also upgraded from a Pi3 to a Pi4 and to a new external ssd for repositories. 
This new ssd was apparently mounted without exec permissions, so the post push hooks for any repository failed to run. 
Changing the settings in fstab and rebooting solved the issue for me.
