### ISSUE TITLE
Data retention settings for package registry

### ISSUE THREAD

**Issue by fuero** [go-gitea/gitea#20766]
### Feature Description

The package registry feature should offer settings for data retention for package versions:

- How long versions are kept,
- how many versions are kept,
- globally, per organization, per repo.

The goal is to allow to conserve space without having to manually delete packages.

If that's already possible, I've missed it in the docs - so please point it out to me :-)

**Comment by hypervtechnics** [comment]
And there should be an option using e.g. Regex or a semver parser to semantically select version to retain e.g. only last 5 prereleases

**Comment by KN4CK3R** [comment]
related #20514

**Comment by KN4CK3R** [comment]
Implemented this in #21658.
