### ISSUE TITLE
Close Milestone from Milestone view

### ISSUE THREAD

**Issue by martyfuhry** [go-gitea/gitea#20773]
### Feature Description

When I am in the Milestone detail view, I would like to be able to close the Milestone. Currently, the only way to close a milestone is to navigate to the milestone list and select close.

### Screenshots

![image](https://user-images.githubusercontent.com/100457/184404221-2bd0cfe8-38d5-4a60-b8a4-e10768e7d10f.png)
![image](https://user-images.githubusercontent.com/100457/184404324-af190b28-56cb-4781-a280-af1d3027b45c.png)

**Comment by BElluu** [comment]
Duplicate #19083 

Implement in #23877
