### ISSUE TITLE
RFE Add 'move issue'

### ISSUE THREAD

**Issue by fhuberts** [go-gitea/gitea#20788]
### Feature Description

I would like to propose a 'move issue' function that can move an issue, from repo into another repo.

**Comment by 6543** [comment]
Note: this should be a duplicate if you can find the original

**Comment by 6543** [comment]
Note2: on move create a redirect ... so kinda add issue type redirect and let rest stay as is. create new issue in new repo and Copy issue. second change direct referenced content (comments...)

**Comment by 6543** [comment]
#453

duplicate
