### ISSUE TITLE
Some buttons not working in iPad OS with Magic Keyboard

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#20790]
### Description

For example, When I'm using trackpad on Magic Keyboard in safari to access my Gitea server. Move the cursor to “add a repository” button, but it’s not work, I need using my finger to touch this button to make it works.

### Screenshots

![3CD62159-C53B-45A6-B11F-7EC7F2515D43](https://user-images.githubusercontent.com/106723472/184546116-7ac38fb0-9422-4ca4-b41a-d30361253a01.png)

### Gitea Version

1.17.0

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

Server:Linux,Client:iPad OS 16 bate

### Browser Version

Safari on IPad

**Comment by yp05327** [comment]
Auto popup the list? Is it really needed....

**Comment by wxiaoguang** [comment]
> `Move the cursor to “add a repository” button, but it’s not work`

I guess `Move the cursor` means "hover", it shouldn't auto popup every dropdown list when it is being hovered, otherwise it would be too annoying. So you need to "focus" or "click" the dropdown to show the list.
