### ISSUE TITLE
Unable to delete project board

### ISSUE THREAD

**Issue by UltraBlackLinux** [go-gitea/gitea#20801]
### Description

The delete button on project boards does nothing.

Notice: I couldn't try this on the public instance since I can't log in. I am assuming YES

### Gitea Version

Gitea version 1.17.0 built with GNU Make 4.1, go1.18.4 : bindata, sqlite, sqlite_unlock_notify

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

Could not for the life of me get gitea to output logs even though I am basically on the stock config

### Git Version

git version 2.34.1

### Operating System

Linux selfhosted 5.15.0-1013-raspi #15-Ubuntu SMP PREEMPT Mon Aug 8 06:33:06 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux

### How are you running Gitea?

Service from the deb file.

### Database

MySQL

**Comment by silverwind** [comment]
Does work for me on https://try.gitea.io when I create a empty project and then delete it afterwards. Maybe there's more conditions? There should be an error in the server log or possibly in the browser console, try to check those.

**Comment by UltraBlackLinux** [comment]
> Does work for me on https://try.gitea.io when I create a empty project and then delete it afterwards. Maybe there's more conditions for the problem to appear? There should be an error in the server log or possibly in the browser console, try to check those.

As I said, I couldn't get gitea to actually start logging anything and the server console didn't show any errors either.

**Comment by silverwind** [comment]
Does it work when you create a empty project and then immediately delete it?

**Comment by UltraBlackLinux** [comment]
> Does it work when you create a empty project and then immediately delete it?

It doesn't no. I can't delete any boards.

**Comment by wxiaoguang** [comment]
I think what silverwind meant is to also check whether there are error logs in your browser's console.

There could be some different issues behind the problem:
1. The frontend resources are out-of-sync. Upgrade to 1.17.2 will 99.9% resolve the problem.
2. The are some out-of-sync customized templates or customized static CDN.
3. There are some permission problem (bug), try with admin account.
4. If there are other issues, then it needs more logs to continue, see https://docs.gitea.io/en-us/seek-help/

**Comment by UltraBlackLinux** [comment]
I have already checked the browser console, but it didn't contain any errors
1. I sure hope that this is the fix
2. no clue what you are talking about, so probably not. I am pretty much using stock gitea with nginx
3. Well I only have one account on my gitea instance, so I assume that my account is the admin account
4. logging for some reason didn't work and the service logs didn't contain any errors

**Comment by wxiaoguang** [comment]
> logging for some reason didn't work

That's impossible. Follow the document https://docs.gitea.io/en-us/seek-help/, the logging should always work.

And, "check what HTTP requests are sent to backend when clicking Delete Board", what do you see?

**Comment by UltraBlackLinux** [comment]
> > logging for some reason didn't work
> 
> That's impossible. Follow the document https://docs.gitea.io/en-us/seek-help/, the logging should always work.
> 
> And, "check what HTTP requests are sent to backend when clicking Delete Board", what do you see?

Just checked, a DELETE request gets sent (0b tho? Is that correct?)

**Comment by wxiaoguang** [comment]
Can you show details? For example, what's the response of the `0b DELETE`? Do you see the `{"ok":true}` response?

Even if you thought "Logging yielded no results at all. Just debug prints", it will also help, do you see the DELETE request on the backend? If no, are you using a reverse-proxy? Is it blocking some request? etc.

Please provide enough clues and logs. If you can not follow https://docs.gitea.io/en-us/seek-help/ to provide enough information, it will waste a lot of time on asking and answering.

**Comment by UltraBlackLinux** [comment]
> Can you show details? For example, what's the response of the `0b DELETE`? Do you see the `{"ok":true}` response?
> 
> Even if you thought "Logging yielded no results at all. Just debug prints", it will also help, do you see the DELETE request on the backend? If no, are you using a reverse-proxy? Is it blocking some request? etc.
> 
> Please provide enough clues and logs. If you can not follow https://docs.gitea.io/en-us/seek-help/ to provide enough information, it will waste a lot of time on asking and answering.

I am using nginx. The debug prints that did exist never mentioned "DELETE". It is not blocking other stuff in gitea. I did not see an OK response.

Here are the logs, but as I said, I didn't see anything: 
[xorm.log](https://github.com/go-gitea/gitea/files/9556772/xorm.log)
[router.log](https://github.com/go-gitea/gitea/files/9556773/router.log)
[gitea.log](https://github.com/go-gitea/gitea/files/9556774/gitea.log)

**Comment by UltraBlackLinux** [comment]
certbot apparently added a check which I didn't know about. It filtered some request types like delete
