### ISSUE TITLE
Clicking on an organization dashboard during a warehouse migration will report a 500 error

### ISSUE THREAD

**Issue by suiyueou** [go-gitea/gitea#20804]
### Description

When an organization is performing a repository migration task in the background, if you switch to the corresponding organization's dashboard in a new tab at this time, a 500 error is reported

In testing, I found that only the organization's dashboard had this problem, everything was fine for the user

### Gitea Version

1.17.0

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![image](https://user-images.githubusercontent.com/48700331/184783694-8e7a71dd-6004-44b7-a66f-27a37fde5d84.png)

### Git Version

2.36.2

### Operating System

Ubuntu 22.04 LTS

### How are you running Gitea?

Docker Deploy

### Database

SQLite

**Comment by lunny** [comment]
When migrating a mirror, the mirror record hasn't been inserted into database at the beginning.

**Comment by cainb** [comment]
> When migrating a mirror, the mirror record hasn't been inserted into database at the beginning.

It is when the organization is executing the repository migration task in the background, at this time the user accesses the link `/org/orgName/dashboard/` will report 500 error, this error I also tested on the old version (1.16.3), and there is no, should be the new version introduced.

For example, a `mirror` organization is migrating a `gitea` repository in the background, and during the migration, when I visit the `/org/mirror/dashboard` page, I get a 500 error.

This error is only triggered when the organization is performing a migration task, and when the migration task is complete, the error disappears and access returns to normal

**Comment by zeripath** [comment]
I've put up a PR to prevent the panic in this code but I think we need to look again at this code and consider whether it's even necessary to call it as I'm not sure that the value of .Mirrors is ever used...
