### ISSUE TITLE
text-align:right in pages: New Repository/Migration/Organization

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#20808]
### Description

It seems that after 1.17.0,  #20458  introduced this issue

https://github.com/go-gitea/gitea/pull/20458/commits/f4e417b2ff32f199b4ae2a47330cc9aca64eb012#diff-cc9e4ee9acba1c5f41b0d09f882b0013b81bbdd34b20c8ab5779f34a48aba8efR160

### Screenshots

https://user-images.githubusercontent.com/76462613/184831791-6db92135-e603-4614-bc35-f55c26ec9fb3.mp4

![image](https://user-images.githubusercontent.com/76462613/184832358-839c4cb8-2273-4814-8756-df22cb4cfc00.png)

### Gitea Version

main

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

Windows 10

### Browser Version

Edge/104

**Comment by Gusted** [comment]
Oops already noticed this a few days ago, forgot to push my stashed changes. https://github.com/go-gitea/gitea/pull/20810
