### ISSUE TITLE
UI mis-align for PR commit history

### ISSUE THREAD

**Issue by wxiaoguang** [go-gitea/gitea#20818]
Gitea  1.18.0+dev-283-gefaa9958b

https://gitea.com/gitea/helm-chart/pulls/343

![image](https://user-images.githubusercontent.com/2114189/185013571-1945f2cc-a9b2-45c7-915c-43a44e4e32c4.png)

**Comment by silverwind** [comment]
Should use flexbox to solve. Commit title will need a ellipsis overflow.

**Comment by Gusted** [comment]
I don't see this bug:

![image](https://user-images.githubusercontent.com/25481501/185285818-93b2e59c-01a1-4c4a-991c-37b34d2c4013.png)

**Comment by wxiaoguang** [comment]
Reproducible:
macOS Chrome Version 104.0.5112.79 (Official Build) (x86_64)
macOS Chrome Version 104.0.5112.101 (Official Build) (x86_64)
macOS Firefox 103.0.2 (64-bit)
Windows Edge Version 104.0.1293.54 (Official Build) (64 bit)

Non-reproducible:
macOS Safari Version 15.6 (17613.3.9.1.5)

**Comment by Gusted** [comment]
Non-reproducible:

Linux Firefox 105.0a1
Linux Chromium 104.0.5112.79 (Official Build) Arch Linux (64-bit)

Ugh another platform+browser dependent bug.

**Comment by silverwind** [comment]
Might be font-related, but doesn't really matter for fixing the issue.
