### ISSUE TITLE
Arm compability: Why in helm chart used bitnami images? I've tried official images and make pods work

### ISSUE THREAD

**Issue by ilya1st** [go-gitea/gitea#20816]
### Feature Description

There is a problem with bitnami inages used in HELM chart(yes they're still not supported on arm64)
I just changed locally images to official in my deployments and gitea in my local kubernetes 1.24(arm64, debian 11)  started to work.

Images used: gitea/gitea:1.16.8,  docker.io/memcached:latest, docker.io/postgres:12.12-bullseye

<img width="999" alt="image" src="https://user-images.githubusercontent.com/9489084/185002773-e7d7780c-c5a3-4595-a30f-37fca773d21c.png">

<img width="501" alt="image" src="https://user-images.githubusercontent.com/9489084/185002982-48b328ca-f660-4cc8-9e6f-cd26712e7a27.png">
<img width="250" alt="image" src="https://user-images.githubusercontent.com/9489084/185003175-5f43e5f9-1320-4264-92b8-2cd5ecc51468.png">

So, why in helm chart are used binami images which are x86_64 only?

**Comment by lunny** [comment]
Please post this on https://gitea.com/gitea/helm-chart
