### ISSUE TITLE
migration from gitolite via https not working

### ISSUE THREAD

**Issue by chiemseesurfer** [go-gitea/gitea#20811]
### Description

I want to setup gitea as a replacement of our beloved gitolite. I want to have migrated all repsitories to gitea and set up as a mirror.

I tried the api and the webinterface:
new migration -> Git -> enter everything needed

gitolite url to clone from is: git.internal.company.com
gitea url to access web ui is gitea.internal.company.com

Every migrate request ends up in `You can not import from disallowed hosts, please ask the admin to check ALLOWED_DOMAINS/ALLOW_LOCALNETWORKS/BLOCKED_DOMAINS settings.`

My config section for migrations:
```
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;[migrations]
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;
;MAX_ATTEMPTS = 3
;RETRY_BACKOFF = 3
ALLOWED_DOMAINS = "*.internal.company.com,git.internal.company.com"
;BLOCKED_DOMAINS =
ALLOW_LOCALNETWORKS = true
SKIP_TLS_VERIFY = true
```

git.internal and gitea.internal are located on the same host (192.168.112.50).

```
 gitea@githost:~$ git config --global -l
http.sslverify=false
```

gitea is running behind an apache proxy which does the ssl offloading.

### Gitea Version

1.17.0

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

2.20.1

### Operating System

Debian buster (10)

### How are you running Gitea?

Using downloaded golang binary.

### Database

MySQL

**Comment by wxiaoguang** [comment]
Your config file is incorrect. Change the `;[migrations]` to `[migrations]` to make a correct section

**Comment by chiemseesurfer** [comment]
thx, I was blind. I didn't see that.
