### ISSUE TITLE
Javascript error after updating to 1.17.0

### ISSUE THREAD

**Issue by wolfbeast** [go-gitea/gitea#20824]
### Description

I'm in the process of updating out Gitea instance to 1.17.0 from 1.12.6, and ran into it throwing a JS error after upgrading and migrating successfully.

```
09:54:40.024 error { target: SharedWorker, isTrusted: true, message: "ReferenceError: EventSource is not defined", filename: "https://repo.palemoon.org/assets/js/eventsource.sharedworker.js", lineno: 1, colno: 85, srcElement: SharedWorker, currentTarget: SharedWorker, eventPhase: 2, bubbles: false, cancelable: true } 1 index.js:37:15714
	Gg/< https://repo.palemoon.org/assets/js/index.js:37:15714
```

This is on the Pale Moon web browser (we use Gitea for Pale Moon development).
Of note, Pale Moon does not support the ambiguous global `window.event` MSIE quirk (deprecated on mainstream browsers also) which _may_ be the issue here?

### Screenshots

![gitea1](https://user-images.githubusercontent.com/3359132/185066233-df5744b4-3bfe-4cb4-ae15-40a207362fc1.png)

### Gitea Version

1.17.0

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

Windows 10

### Browser Version

Pale Moon 31.2.0.1

**Comment by lunny** [comment]
Should be fixed by #20663

**Comment by wolfbeast** [comment]
Thanks!
I did some digging myself and found it seems to be because while we do support EventSource (and have since forever) and SharedWorkers, we currently don't support EventSource _in_ workers. I opened an issue on our end to fix that, as well.

of note attempting to disable EvenSource use through `EVENT_SOURCE_UPDATE_TIME = -1` doesn't actually help here.

**Comment by silverwind** [comment]
BTW, does PaleMoon support Websocket inside SharedWorker?

**Comment by wolfbeast** [comment]
> BTW, does PaleMoon support Websocket inside SharedWorker?

Yes, websockets are available in workers.

**Comment by eeyrjmr** [comment]
Is this related to or a duplicate of : https://github.com/go-gitea/gitea/issues/20572

**Comment by wolfbeast** [comment]
@eeyrjmr Yes it seems to be a duplicate. I'll just wait for it to make it to the release train.
