### ISSUE TITLE
Global / default labels

### ISSUE THREAD

**Issue by olymk2** [go-gitea/gitea#2082]
- Gitea version (or commit ref):
- Git version: master
- Operating system: linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ x ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ x ] Not relevant
- Log gist:

## Description

Be nice to have the ability to configure labels at organisation level, this way we can create them and have them available to all repositories.

Currently on each new repository you have to recreate your labels, its nice to have per project labels but would be good if you can share common ones across repositories.

**Comment by cez81** [comment]
You can add your own label templates, https://docs.gitea.io/en-us/customizing-gitea/

**Comment by olymk2** [comment]
Great, but if nothing else that page could do with an update, so i created custom/options/labels then what ?

label per line or should these files already exist, I am using containers so perhaps they are not exposed to the host.

Good to know there is a mechanism anyway once I figure it out :)

**Comment by cez81** [comment]
Use same format as default in
https://github.com/go-gitea/gitea/blob/master/options/label/Default
One file per set of labels. Make sure to create the subfolders. 
Not sure how it works when using container. Think you set your custom
folder in config.

Agree documentation needs more information. Feel free to help with PR :)

**Comment by olymk2** [comment]
Cool interesting i don't get those defaults, labels are completely blank I wonder if the mapping from the host to the container is replacing that folder structure.

Thanks for clarifying @cez81 I will close this as its not actually an issue and just lack of knowledge :)
