### ISSUE TITLE
Generic package size limited to 32MiB

### ISSUE THREAD

**Issue by wtodd1** [go-gitea/gitea#20830]
### Description

If you try to upload a package that is larger than 32MiB to the generic package registry, the upload appears to succeed, and the package can be seen in the web ui, but downloading the package later gives a 0 byte file.

I suspect this is due to the hard-coded buffer size on [this line](https://github.com/go-gitea/gitea/blob/7503cd35c285741c6d9caf9797a5c953ae9dccf6/routers/api/packages/generic/generic.go#L85).

Looking at references to CreateHashedBufferFromReader, the 32MiB limit also seems to apply to the other package registries as well.

### Gitea Version

1.17.0

### Can you reproduce the bug on the Gitea demo site?

I did not receive the confirmation email after registering, so I was unable to attempt it.

### How are you running Gitea?

Reproduced on docker and Windows 10.

### Database

SQLite

**Comment by lunny** [comment]
This has been fixed by #20635
