### ISSUE TITLE
[1.17.1] Reaction icon problem

### ISSUE THREAD

**Issue by tyroneyeh** [go-gitea/gitea#20860]
### Description

1. Click +1 reaction in comment
2. Click +1 on the first content to respond invalid
3. Deselect +1 reaction in comments
4. On the first content click +1 response is working
5. Hit +1 reactions in comments
6. In the first content deselect +1 reaction, comment reactions are also deselected

https://user-images.githubusercontent.com/1255041/185575871-acd2543d-dcc5-4ecb-814a-bf7cc787383e.mp4

### Gitea Version

1.17.1

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

Gentoo

### How are you running Gitea?

systemd

### Database

PostgreSQL

**Comment by earl-warren** [comment]
I confirm experiencing the same bug as described.
