### ISSUE TITLE
500 in template when showing repository of deleted user

### ISSUE THREAD

**Issue by lephe** [go-gitea/gitea#20865]
### Description

On [this instance](https://gitea.planet-casio.com/) we have a repository `mistercyb/chip8_emulator` that somehow still exists despite their user being deleted. Anytime this repo comes up in the Explore tab or in search we get a 500; for instance [here in search](https://gitea.planet-casio.com/explore/repos?sort=recentupdate&language=&q=chip8_emulator).

I'm pretty sure this is the same issue as [this Discourse thread](https://discourse.gitea.io/t/internal-server-error-500-on-site-administration-page/5347).

The log suggests an access to the nonexisting user, with

```
2022/08/19 16:48:39 ...s/context/context.go:232:HTML() [E] [62ffa2c7] Render failed: template: explore/repo_list:29:19: executing "explore/repo_list" at <.Owner.Visibility.IsPrivate>: nil pointer evaluating *user.User.Visibility
```

(Sorry I can't get debug logs just yet -- I might try later)

Something of note is that the repo folder not only had `mistercyb/chip8_emulator.git` but also a rogue `chip8_emulator.git` outside of any user/org folder with no objects or refs. (I deleted it thinking it was the cause of the issue.)

It seems something went wrong as soon as the repo remained when the user was deleted. Currently it's not possible to remove the repository from the web UI because of the error. Any instructions for how to remove it from the command-line would be helpful.

### Gitea Version

1.17.0

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

2.37.2

### Operating System

Arch Linux

### How are you running Gitea?

Installed from the official Arch Linux repository.

### Database

SQLite

**Comment by lunny** [comment]
The repositories should be deleted before user deleted according the logic in the current codebase.

**Comment by lephe** [comment]
That seems reasonable. Setting aside the question of whether/how to fix it for now, is there a documented way for me to properly get rid of the rogue repository to unblock the instance without using the web UI?

**Comment by lunny** [comment]
I think you have to manually delete the repository from database and disk. 
I'm going to close this one as it's impossible to address that situation according normal operations.

**Comment by lephe** [comment]
That's fine with me, but do you have a pointer on how to do that? I'm not exactly familiar with the way Gitea stores repositories on the disk, or the database format.

**Comment by lunny** [comment]
Maybe it's easier for you to change the repository's owner and then delete the repository from UI.

```SQL
Select id from repository where owner_name = '<owner_name>' and name = '<repo_name>';
```
```SQL
Update repository set owner_id = <new_id>, owner_name = '<new_owner_name>' where id = <above_id>;
```

**Comment by lephe** [comment]
Excellent. The owner field was weirdly blanked out (neither an empty string nor null as far as I can tell, which should explain why I had a repo folder outside of any owner folder in the storage) but the ownership change still worked fine. Fortunately the UI allows deleting the repo even when the files are gone, so that's solved. Thank you!
