### ISSUE TITLE
Code highlighting in issue titles - `example`

### ISSUE THREAD

**Issue by pat-s** [go-gitea/gitea#20887]
### Feature Description

It would be great if Gitea would support code highlighting in issue titles (as GH does, see title).

Screenshot from 1.18.0+dev-289 below.

### Screenshots

![image](https://user-images.githubusercontent.com/8430564/185785011-80fcd4af-ac2d-4038-9ea9-5be8dc5776af.png)

**Comment by yardenshoham** [comment]
I'll take this
