### ISSUE TITLE
Is go-gitea dead?

### ISSUE THREAD

**Issue by FSMaxB** [go-gitea/gitea#209]
I've followed the discussions in https://github.com/gogits/gogs/issues/1304 and to me it seams like gogs is back in the game.

I find this situation rather unpleasant because I'm confused whether I should go with gogs or go-gitea on my server. After watching the development of both gogs and go-gitea over the past weeks, to me it looks like nothing is really happening in go-gitea whereas the gogs people get actual work done.

Is it safe to say that go-gitea is dead?

**Comment by tboerger** [comment]
Gitea is not dead for sure, but you forget that it's summer time. so many people are out on vacation and things like that.

**Comment by lunny** [comment]
I think it's not. Since gogs comes back. It's a good result for gitea's beginning.

**Comment by tboerger** [comment]
Let's close that for now, it's not an issue
