### ISSUE TITLE
Git-Hook for update does not get the refname, oldrev, newrev as parameter

### ISSUE THREAD

**Issue by TomFreudenberg** [go-gitea/gitea#2090]
- Gitea version (or commit ref): v1.1
- Git version: 2.10.1 (Apple Git-78)
- Operating system: OSX/Ubuntu
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

Hi, I have tested some simple scripts from here:

> https://git-scm.com/book/uz/v2/Customizing-Git-An-Example-Git-Enforced-Policy 

and put that as update-hook via Git-Hooks->update

```ruby
#!/usr/bin/env ruby

$refname = ARGV[0]
$oldrev  = ARGV[1]
$newrev  = ARGV[2]
$user    = ENV['USER']

puts "Enforcing Policies..."
puts "(#{$refname}) (#{$oldrev[0,6]}) (#{$newrev[0,6]})"
```

But it seems that the ARGV is empty.

Also a very simple

```bash
#!/bin/bash
echo "$1 $2 $3"
```

doesn't print out anything.

From where in the "hook call" of gitea I will be able to read the refs?

**Comment by TomFreudenberg** [comment]
Hint from @lunny

maybe this PR will fix that? @TomFreudenberg #1975

**Comment by TomFreudenberg** [comment]
Hi @lunny thanks for guiding me to that PR. It might resolve my issue too, but I can't test it. The patch cannot be cherry-picked to release/v1.1 branch in case of missing `integrations/gitea-integration-meta/gitea-repositories/...`

I will check if the master branch is working for me with that applied.

-----

Update:

Still no success, the arguments $1, $2, $3 should have been available but they are not.
Seems to me that this might be a bug?

**Comment by TomFreudenberg** [comment]
Ok, I did a default git test

```bash
git create --bare hooks.git
```

and then put that above `ruby` example into `hooks.git/hooks/update` and run a test push.

That works like expected:

```bash
git push
```

<pre>
Counting objects: 3, done.
Writing objects: 100% (3/3), 304 bytes | 0 bytes/s, done.
Total 3 (delta 0), reused 0 (delta 0)

remote: Enforcing Policies...
remote: (refs/heads/master) (5317c5) (c59a55)

To /tmp/hooks.git
   5317c5f..c59a55c  master -> master
</pre>

When I put the same hook script into a gitea repository, I get an error, because arguments `$1`, `$2`and `$3` are empty / not set.

**Comment by TomFreudenberg** [comment]
@lunny @lafriks 

I still can't reproduce the output from Lauris without doing a patch.

The post-receive and pre-receive hooks are working but not the update hook. I tried this for branch release/v1.1 as well as for master branch.

I have created new repositories all the time via gitea web interface. After that the update hook script of the new repos looks like:

```bash
#!/usr/bin/env bash
data=$(cat)
exitcodes=""
hookname=$(basename $0)
GIT_DIR=${GIT_DIR:-$(dirname $0)}

for hook in ${GIT_DIR}/hooks/${hookname}.d/*; do
test -x "${hook}" || continue
echo "${data}" | "${hook}"
exitcodes="${exitcodes} $?"
done

for i in ${exitcodes}; do
[ ${i} -eq 0 ] || exit ${i}
done
```

But as you can see from your integration meta sources at: https://github.com/go-gitea/gitea/blob/master/integrations/gitea-integration-meta/gitea-repositories/user2/repo1.git/hooks/update#L6

the update hook should have forwarded the params 1 to 3, like

```bash
echo "${data}" | "${hook}" $1 $2 $3
```

If I change the update hook script, then I can reproduce the output from Lauris as well.

Thanks for feedback

**Comment by lafriks** [comment]
Did you try running update hooks from administration interface?

**Comment by TomFreudenberg** [comment]
Hi @lafriks, what does that mean? 

> try running update hooks from administration interface?

I do the following:

1. Connect Web Browser to gitea web
2. Login as user with rights to manage githooks
3. Create a new repository through Button "Create -> New Repository" and create a README.md by default
4. Go to settings for the new repo and entering the update hook script
5. Copy/Paste your code and save
6. See "green" info about active hook
7. Change to a terminal
8. Clone ssh://localhost/my-new-repo
9. cd cloned-path
10. Change content of README.md and commit
11. Push to origin and check the console output

**Comment by lafriks** [comment]
@TomFreudenberg, I'm sorry I was testing with code I did some fixes :laughing:. On master it does not work, I'll create PR that does fix this problem

**Comment by lafriks** [comment]
@TomFreudenberg can you please check with code from #2095 to see if that fixes your issue?

**Comment by TomFreudenberg** [comment]
Hi @lafriks @lunny 

I can confirm that this fix works now!

Thanks a lot Lauris for doing that fast work.

**Comment by TomFreudenberg** [comment]
Just as an info I post the three hooks working with Ruby Lang as well

**post-receive:**

```ruby
#!/usr/bin/env ruby

oldrev, newrev, refname = gets.chomp.split(" ")

puts "(post-receive) Old revision: #{oldrev}"
puts "(post-receive) New revision: #{newrev}"
puts "(post-receive) Reference name: #{refname}"
```

**pre-receive:**

```ruby
#!/usr/bin/env ruby

oldrev, newrev, refname = gets.chomp.split(" ")

puts "(pre-receive) Old revision: #{oldrev}"
puts "(pre-receive) New revision: #{newrev}"
puts "(pre-receive) Reference name: #{refname}"
```

**update:**

```ruby
#!/usr/bin/env ruby

refname = ARGV[0]
oldrev  = ARGV[1]
newrev  = ARGV[2]

puts "(update) Old revision: #{oldrev}"
puts "(update) New revision: #{newrev}"
puts "(update) Reference name: #{refname}"
```

**Comment by TomFreudenberg** [comment]
@lunny, @lafriks  - off-topic question - do you have an approx date for 1.2.0 to be available as branch release/v1.2?

We will create a new service based on gitea (really great project) and I would like to do it with the next stable release and the fixes from above.

Thanks in advance, if you have an idea.
Tom

**Comment by lafriks** [comment]
There are no exact date but after few remaining issues are resolved I think it will be released. It could be in a week or two if no critical issues or upgrade migration issues found that can't be resolved in this time-frame.

**Comment by TomFreudenberg** [comment]
Great Lauris, thats what I thought when reading the open issues on the milestone path.

**Comment by TomFreudenberg** [comment]
Offtopic:

Hi @lafriks Lauris, sorry for disturbing you again. Do you have some update about 1.2 release date. Thanks for some information. Tom

**Comment by lafriks** [comment]
@TomFreudenberg we are still working on fixing final bugs to release as stable version as possible it is very close but I can't give you exact date

**Comment by TomFreudenberg** [comment]
@lafriks Thanks for your update - thats fine for me

**Comment by TomFreudenberg** [comment]
Offtopic:

@lafriks Lauris, If we would like to start with working on our servers, what would you prefer? Start with 1.1.3 or use master until 1.2 is ready. Thanks for your suggestion. Tom

**Comment by lafriks** [comment]
@TomFreudenberg 1.2 is close enough to be safe on using master, if you have tried it out and have not encountered any issues that are not critical for you
