### ISSUE TITLE
Missing info about docker image size

### ISSUE THREAD

**Issue by t347s** [go-gitea/gitea#20909]
### Description

Hi,
Will be nice to have a information about the size of a docker image package. This info is present on "General package" but not for docker images.

Also, a info about repo with packages is usefull, right now i cannot determine if a repo has packages, maybe a pictogram, an icon, or something like that can be implemented.

Thank you!

### Screenshots

![Screenshot 2022-08-22 113956](https://user-images.githubusercontent.com/31503790/185878556-1ff1666f-812f-44e2-b0a1-f37a11dbd258.png)

### Gitea Version

1.17.1

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

Windows 10

### Browser Version

Firefox 103

**Comment by KN4CK3R** [comment]
Added in https://github.com/go-gitea/gitea/pull/20927
