### ISSUE TITLE
Logout doesn't redirect to home in Firefox

### ISSUE THREAD

**Issue by garymoon** [go-gitea/gitea#20914]
### Description

When using Firefox the logout flow does not redirect the user to the home page as it does with other browsers, so users are presented with a 404 if they were on any page that requires an active session.

### Screenshots

Not a visual issue.
![image](https://user-images.githubusercontent.com/4531887/185982612-7105d63f-fece-4668-830b-e7a0b2671b56.png)

### Gitea Version

Noticed on 1.16.9 but still happens on current.

### Can you reproduce the bug on the Gitea demo site?

Yes

### Browser Version

Firefox 103.0.2

**Comment by the-pulli** [comment]
same here with Firefox 104.0.2

**Comment by lunny** [comment]
Can not reproduce this on my Firefox.

**Comment by lunny** [comment]
Since recent changes about logout, I think this has been resolved.
