### ISSUE TITLE
Emoji in code shown with “hidden unicode characters” warning

### ISSUE THREAD

**Issue by aral** [go-gitea/gitea#20924]
## Reproduction

See https://codeberg.org/kitten/app/src/commit/9e0b13def3409bfb66e256941fcf8aeafead6844/examples/kitten-count/index.page#L6

## What should happen

The emoji should display without any warnings.

## What actually happens

A “hidden unicode characters” warning is shown.

The warning is shown for unicode character [U+FE0F](https://unicode-table.com/en/FE0F/) (variation selector).

### Gitea Version

1.16

### How are you running Gitea?

Codeberg.

**Comment by silverwind** [comment]
I think https://github.com/go-gitea/gitea/pull/19990 fixed this, but it's only in 1.18 currently.

**Comment by wxiaoguang** [comment]
It has been fixed.
