### ISSUE TITLE
Distorted PR changes UI with german localization

### ISSUE THREAD

**Issue by otbutz** [go-gitea/gitea#20922]
### Description

After an update from 1.16.x to 1.17.1, the menu of the PR changes page is distorted with German localization. Hitting Ctrl+F5 doesn't change anything. The UI looks normal if i switch to English.

### Gitea Version

1.17.1

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

German:

![image](https://user-images.githubusercontent.com/22315436/186108380-db8cc3b9-101c-42e1-bfdf-44daf09e8f36.png)

English:

![image](https://user-images.githubusercontent.com/22315436/186112468-b675e492-de76-4f54-afce-5ed45a740351.png)

### How are you running Gitea?

Downloaded from the release page, running as a service via systemd

### Database

PostgreSQL

**Comment by silverwind** [comment]
Probably need to make more space by changing buttons to icon-only to make space for longer translation.

**Comment by otbutz** [comment]
Maybe related to the changes introduced in #19546 ?

**Comment by silverwind** [comment]
Not sure, but https://github.com/go-gitea/gitea/pull/20934 will fix it.
