### ISSUE TITLE
Ignore certain directory or file in Language Status Bar

### ISSUE THREAD

**Issue by ddddavid-he** [go-gitea/gitea#20929]
### Feature Description

![2022-08-23](https://user-images.githubusercontent.com/58453183/186186608-cdb5363f-8db5-4a6d-ae23-d26468ee24df.png)

When I have some repos of LaTeX project with a lot of `.eps` figures or something like that inside, the Language Status Bar will be occupied by the language PostScript (as is shown above), which is quite misleading. 

I wounder if it is possible to have some options to ignore certain directories or language 
 in language detection process in the future versions.

**Comment by delvh** [comment]
I think something like this should already be possible by supplying your own `.gitattributes`.
But don't ask me _how_.

**Comment by ddddavid-he** [comment]
It's exactly what I want. Thanks for your tips. 
Adding `**/figures/*    linguist-vendored` in `.gitattributes` do prevent language detection.

**Comment by raforg** [comment]
Does gitea support linguist-detectable=false as well? It doesn't seem so. Putting this in .gitattributes affects github's display of the main language, but it doesn't affect codeberg.
