### ISSUE TITLE
Kanban cards are losing their sort/priority order in 1.17

### ISSUE THREAD

**Issue by Akaitatsu** [go-gitea/gitea#20920]
### Description

In 1.16.1, we could prioritize cards within a column on the Kanban board and the new order would be saved. When I upgraded from 1.16.1 to 1.17.0, the cards stopped retaining the order and started sorting newest to oldest; upgrading to 1.17.1 didn't help. I reproduced this in the demo site as well; here is the link and repro steps:

https://try.gitea.io/eleven11/KanbanTest/projects/2282

1. Note that the cards in the _In Progress_ column are displayed in reverse of the order they were created (D, C, B, A).
2. Rearrange the cards in any other order
3. Click the browser refresh button
4. Note that the cards are back in the same order when you started

I ran SQL Server Profiler and queried the database and Gitea does appear to be updating the _sorting_ column in the _project_issue_ table. However, when the page is reloaded it's ignoring the sorting and appears to sort by issue_id.

There are no errors in the Gitea log.

### Screenshots

Before
![image](https://user-images.githubusercontent.com/20346471/186036170-396ea411-32f6-485c-b5c2-8395f985815a.png)
Changed the order
![image](https://user-images.githubusercontent.com/20346471/186036246-38cdd17a-12cc-43e4-bd2e-4c47a93db56f.png)
Refreshed the page
![image](https://user-images.githubusercontent.com/20346471/186036457-bd3a65f6-e1a5-457a-b98b-24ddfcf58451.png)

### Gitea Version

1.17.1

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

Windows Server 2019

### Browser Version

Firefox 103.0.2

**Comment by anbraten** [comment]
I can confirm this. 

Was it possible to sort columns of a board before as well (I think so) as that is not working for me as well.

**Comment by Akaitatsu** [comment]
> Was it possible to sort columns of a board before as well (I think so) as that is not working for me as well.

Yes. I used the sorting extensively in **1.16.1**.

**Comment by wxiaoguang** [comment]
It's a regression of "Move project files into models/project sub package (#17704)"

The `SortType` was lost in `LoadIssuesFromBoard`.

I was keeping telling people:

1. Do not rebase / force-push during refactoring
2. Make all refactoring works complete as soon as possible (do not last longer than 1 week)

But people do not want to listen (I have to complain!), that's why I do not want to spend time for arguments on Gitea.

**Comment by Akaitatsu** [comment]
Many thanks! It's working great since I upgraded to 1.17.2.
