### ISSUE TITLE
In Admin UI Required Claim Name/Value appear blank for any OpenID Connect Authentication Source

### ISSUE THREAD

**Issue by soumyadey** [go-gitea/gitea#20945]
### Description

In Gitea Admin UI, values for the following two fields do not show up even if set.

1. Required Claim Name
2. Required Claim Value

<img width="1653" alt="gitea-ui-bug" src="https://user-images.githubusercontent.com/24243812/186451613-8a3195ae-1f6b-4c01-aa87-c199e7e45c27.png">

**Steps to reproduce:**
1. Create an Authentication Source with `Authentication Type: OAuth2` and `OAuth2 Provider: OpenID Connect`
2. Enter values for `Required Claim Name` and `Required Claim Value`
3. Later view or edit the Authentication Source
4. Above two fields are empty

### Gitea Version

1.17.1

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

On Kubernetes using Helm as instructed [here](https://docs.gitea.io/en-us/install-on-kubernetes/).

### Database

PostgreSQL

**Comment by wxiaoguang** [comment]
It has got backport in 1.17.2
* #21001
