### ISSUE TITLE
Language stats not available without JavaScript

### ISSUE THREAD

**Issue by vollkorntomate** [go-gitea/gitea#20947]
### Description

The language stats inside a repository are not available if JavaScript is disabled.

Clicking the colored bars doesn't bring up the language names and shares, since it relies on a JavaScript function.

### Screenshots

![ezgif-3-47c8df9635](https://user-images.githubusercontent.com/38211057/186500594-4b979173-3d73-4b23-9a2e-19ce2a06d093.gif)

### Gitea Version

1.17

### Can you reproduce the bug on the Gitea demo site?

Yes

### Browser Version

all

**Comment by zeripath** [comment]
This was always intended to require js. You are welcome to provide a PR that would make this work without JS.

if you disable JS many things in Gitea will not work.
