### ISSUE TITLE
A push mirror that pushes to remote immediately?

### ISSUE THREAD

**Issue by shouya** [go-gitea/gitea#20942]
### Feature Description

I use the [repository mirror](https://docs.gitea.io/en-us/repo-mirror/#pushing-to-a-remote-repository) feature to mirror some of my projects to GitHub from my Gitea instance, and I usually use Gitea as my main git upstream for local development. However, the push mirror only syncs on a fixed interval. Thus there is always a long delay between the moment I push to when it shows up on GitHub. To overcome the delay, I usually employ one of these two approaches:

- click 'synchronize now' on webui
- add github as a second remote and push both it and gitea

Neither is quite ideal to me. I wish there could be a push mirror mode that pushes to the mirror repo immediately as it receives a push from the user. Is this functionality currently achieveable with the current version of gitea? If not, is it possible to get it included in as a planned feature? Thanks!

**Comment by delvh** [comment]
this feature is already implemented on main, wait for Gitea 1.18.
