### ISSUE TITLE
Should we say the repository’s default branch is usually main?

### ISSUE THREAD

**Issue by wolfogre** [go-gitea/gitea#20963]
### Feature Description

Gitea tends to use main as the default branch now according to #19354, shall we update the API doc or wait until main is more popular?

https://github.com/go-gitea/gitea/blob/6c4688e1b1ddb68de192af7f83b06de27baae85e/templates/swagger/v1_json.tmpl#L3455

**Comment by delvh** [comment]
The problem is far worse than what you expected:
I just did a search where _master_ is still used (`ag 'master' | wc -l`), and there are **555** instances where we still use _master_.
The worst thing: There is even a bug I found in `cmd/hook.go` where we still default to _master_ instead of _main_!

**Comment by wxiaoguang** [comment]
> I just did a search where master is still used (ag 'master' | wc -l), and there are 555 instances where we still use master (some are false positives, however).

There are some cases for the master still being used:
* test code (most cases)
* wiki (wiki code hard-coded the master branch name)
* mirror/pull/push (master and main are processed together)
* the post-receive hook (below)

>  The worst thing: There is even a bug I found in cmd/hook.go where we still default to master instead of main!

The logic is `if wasEmpty && masterPushed: then set default branch to master`, it looks safe and I think it could be consider as a fallback for users who still uses "master" branch name.

----

I did some tests about creating an empty repo with master as the default branch and push the a git repo with main branch into it, I think in most cases it works fine. If we still need the logic like `if wasEmpty && masterPushed`, the related code could also be improved to cover the `main` branch name.
