### ISSUE TITLE
WebUI System Notices does not show timestamp

### ISSUE THREAD

**Issue by nem8** [go-gitea/gitea#20966]
### Feature Description

First off, im not sure if this is a feature request or a bug.
Searched to see if this was reported/requests, but did not find any existing posts.

The "System Notices" section in the "Site Administration" section of the webGUI does not show timestamp, only date.
I think it would be helpfull to also show the time of the error occuring.

### Screenshots

![CDViewer_HL6aWS9hFo](https://user-images.githubusercontent.com/495296/186896448-440f8fc8-60a0-49a6-b7ca-0c198ff158e1.png)
![CDViewer_hxXi8jhfjN](https://user-images.githubusercontent.com/495296/186896843-a6a04a47-45ad-474b-8acf-4235c2384157.png)

**Comment by yardenshoham** [comment]
It now shows the full timestamp on click
![image](https://github.com/go-gitea/gitea/assets/20454870/9a11610a-7d76-4d6a-97c3-0d601764328f)

Is that enough or would you like the full timestamp as part of the table?

**Comment by delvh** [comment]
The full timestamp is even shown on hover over the created date.
So, I think this can be closed.
Please wait for the release of 1.20.
