### ISSUE TITLE
[Proposal] Remove the Gitea site URL from `Reviewed-on: ...` in the commit message or make it optional

### ISSUE THREAD

**Issue by wxiaoguang** [go-gitea/gitea#20964]
The `Reviewed-on: ...`  was introduced by #9623 .

It's a full URL like `Reivewed-on: https://my-gitea-instance.com/org/repo/pulls/3`

It causes some problems:

* If a private Gitea instance hosts the repository and sync it to public domain, the private domains will be exposed (security and privacy problem)
* If a Gitea instance's domain expired and hijacked, the URLs in the commit message may cause phishing (security problem)
* If a Gitea instance's domain changed then the links becomes invalid (a flaw)

**Comment by lunny** [comment]
But when you view the commit in client, it will allow you to click and jump to the repository
