### ISSUE TITLE
500 Internal Server Error context/repo.go:863(context.RepoRefByType)

### ISSUE THREAD

**Issue by prologic** [go-gitea/gitea#20973]
### Description

Seeing a lot of these types of 5xx errors in my instance of late:

```
500 Internal Server Error in 10.4ms @ context/repo.go:863(context.RepoRefByType)
```

### Gitea Version

1.17.0

### Can you reproduce the bug on the Gitea demo site?

Yes

### Git Version

N/A

### Operating System

N/A

### How are you running Gitea?

Docker container

### Database

SQLite

**Comment by lunny** [comment]
We need more logs context.

**Comment by prologic** [comment]
> We need more logs context.

Like more logs surrounding this one? 🤔

**Comment by lunny** [comment]
> > We need more logs context.
> 
> Like more logs surrounding this one? 🤔

Yes

**Comment by lunny** [comment]
Closed as no more context.
