### ISSUE TITLE
Display changes in PR since last review / since specified commit

### ISSUE THREAD

**Issue by Artalus** [go-gitea/gitea#20989]
### Feature Description

GitHub and GitLab have this great feature which allows you to see exactly what have changed in the PR since the last time you've looked at it. In Gitea it seems that the only option currently is to view commits one be one.

A tiny step in that directions was made in PR #19007 though it only labels the files as "changed since" instead of providing the diff. Also there are issues #12800 and #19862 , which are more "generalized" versions of this feature request.

### Screenshots

- Github:
![image](https://user-images.githubusercontent.com/10381253/187165511-1caab027-f32f-44ee-b58f-d95c4b5d2357.png)
- Gitlab:
![image](https://user-images.githubusercontent.com/10381253/187169164-5bd63488-9b9f-4411-9014-9c24f3082ac9.png)

**Comment by thammaknot** [comment]
This feature would be awesome. I miss it moving from gitlab/github as well.
Thank you for proposing.

**Comment by cy18** [comment]
I'm missing this feature too. After migrating from gitlab to gitea for about one year, this is the only defect of gitea.

**Comment by lunny** [comment]
Maybe #13313 could fix this one?

**Comment by cy18** [comment]
> /compare/commitA...commitB

The `/compare/commitA...commitB` does not eliminate identical changes of the two commits.

**Comment by sebastian-sauer** [comment]
https://github.com/go-gitea/gitea/pull/25528 implements a first version of this commit selector

changes since last review could be a next PR

**Comment by sebastian-sauer** [comment]
Update: the display changes since last review is now implemented, too ;-)
