### ISSUE TITLE
Error After Click New Pull Request

### ISSUE THREAD

**Issue by MhSaleemAlZayat** [go-gitea/gitea#20982]
### Description

After upgrading to 1.17.1 from 1.16.x when Click New pull request to merge new branch to main branch, js error appears:

**JavaScript error: TypeError: o is undefined (http://10.150.100.47:3000/assets/js/index.js?v=7ea14c4ca3b4ece8917e08968da69260 @ 108:5841). Open browser console to see more details.**

 

### Gitea Version

1.17.1

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![New Pull Request Error 001](https://user-images.githubusercontent.com/26679085/187078953-d89bd376-1db8-4e4e-8fb0-341b9147e0c7.png)
![New Pull Request Error 002](https://user-images.githubusercontent.com/26679085/187078955-9c4c9d01-4161-4f41-9ebb-766ba77d7b74.png)

![New Pull Request Error 003](https://user-images.githubusercontent.com/26679085/187079724-64180c28-52f6-4600-88a8-d5152b7c0ae6.png)

### Git Version

1.17.1

### Operating System

Windows Server

### How are you running Gitea?

Running gitea-1.17.1-windows-4.0-amd64.exe

### Database

MSSQL

**Comment by delvh** [comment]
Did you try to clear the browser cache and then reloading the page?

**Comment by MhSaleemAlZayat** [comment]
No i didn't ... i try it it works now thank you 👍
