### ISSUE TITLE
Support Casbin as the authorization module

### ISSUE THREAD

**Issue by hsluoyz** [go-gitea/gitea#2099]
Hi, [Casbin](https://github.com/casbin/casbin) is an authorization library that supports models like ACL, RBAC, ABAC.

Related to RBAC, Casbin has several advantages:
1. roles can be cascaded, aka roles can have roles.
2. support resource roles, so users have their roles and resource have their roles too. role = group here.
3. the permission assignments (or policy in Casbin's language) can be persisted in files or database (MySQL and Cassandra).

And you can even customize your own access control model, for example, mix RBAC and ABAC together by using roles and attributes at the same time. It's very flexible.

Casbin can provide more flexibility and security than the current authorization in models/access.go. I can make PR if needed. Let me know if there's any question:) Thanks.

**Comment by lunny** [comment]
@hsluoyz please feel free to send a PR and notice the data migration.

**Comment by hsluoyz** [comment]
@lunny ,

I'd like to make such a function: ``hasAccess(user, repo, action)``. Then all access in gitea will call this function for mediation. Casbin will store the collaborator mapping, repo owner mapping, user-organ mapping, organ-team mapping, team-repo mapping, and will use the mappings to calculate whether allow the access.

The mappings stored by Casbin are parallel with what gitea currently stores. Because those mappings are also used for other components like UI.

The Casbin policy rules will be stored into MySQL DB. With Casbin, gitea can also develop a UI to modify Casbin policy, so that the users/admins can also use Casbin to define more flexible policy rules.

Please advise.

**Comment by lunny** [comment]
@hsluoyz And we have added a new concept `Unit`. `hasAccess(user, repo, action)` has no consideration of that. If casbin stored the access data and you have to notice the synchronism and compitable.
