### ISSUE TITLE
Questions about how I best procede, ran into  some errors from dep versions 

### ISSUE THREAD

**Issue by techzilla** [go-gitea/gitea#210]
I had a travisci building, and the godep workspace, and was working on an rpmspec.
The plan did work though, making an rpmspec did become possible.

However, after installing the test rpm, i realized we have a problem.
Our code has errors due to upstream changes. How should I procede?

Are we gonna assume dev has the newest upstream deps, and fix the errors?

**Comment by tboerger** [comment]
I close it as we are using the go 1.5 vendoring now. Feel free to reopen for further discussion.
