### ISSUE TITLE
Redirect stdout and stderr to logfile

### ISSUE THREAD

**Issue by strk** [go-gitea/gitea#210]
This is to have panic messages logged, mostly.
See https://github.com/gogits/gogs/issues/3893

**Comment by tboerger** [comment]
And for docker I would expect the opposite, drop the log files and print everything to stdout and stderr.

**Comment by lunny** [comment]
Anyone work on this?

**Comment by tboerger** [comment]
Nobody claimed it, but as said above I wish we can get rid of all log files for the docker container

**Comment by strk** [comment]
@lunny please go ahead, for 1.0.0 I'd like to have a working setup outside of docker, further tweaks (like an option to only log to stdout) would be nice for 1.1.x

**Comment by lunny** [comment]
Maybe we could resolve all log issues in 1.1

**Comment by lunny** [comment]
I put this to v1.2 since nobody could send a PR to resolve this.
