### ISSUE TITLE
First user created with "gitea admin user create" is not required to change password on first login

### ISSUE THREAD

**Issue by Sirtea** [go-gitea/gitea#21002]
### Description

I'm installing gitea with an automated script, mostly following "installation from binary".

To avoid setup step, a stock app.ini is left on place (with `service` / `DISABLE_REGISTRATION` at "true"). This leaves the installation running, but with no users. This is ok, as the last step is to use `gitea admin user create` for some users, like that:

```
# Here I have the service running but nobody can login, as there are no users
sudo -u git GITEA_WORK_DIR=/var/lib/gitea gitea -c /etc/gitea/app.ini admin user create --username u1 --email u1@example.com --random-password --admin
sudo -u git GITEA_WORK_DIR=/var/lib/gitea gitea -c /etc/gitea/app.ini admin user create --username u2 --email u2@example.com --random-password --admin
sudo -u git GITEA_WORK_DIR=/var/lib/gitea gitea -c /etc/gitea/app.ini admin user create --username u3 --email u3@example.com --random-password
```

Honoring the flag `--must-change-password` from `gitea admin user create`, users are required to change their passwords on first login, **all but the first on the list** (u1 in this example). It's irrelevant if it's admin or not, it's always the first one that is not required to change his password on first login.

As this is not documented, I believe that could be an issue/bug

Regards

### Gitea Version

gitea-1.17.1-linux-amd64

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

```
+ systemctl daemon-reload
+ systemctl enable gitea --now
Created symlink /etc/systemd/system/multi-user.target.wants/gitea.service → /etc/systemd/system/gitea.service.
+ sleep 10
+ sudo -u git GITEA_WORK_DIR=/var/lib/gitea gitea -c /etc/gitea/app.ini admin user create --username u1 --email u1@example.com --random-password --admin
generated random password is '************'
New user 'u1' has been successfully created!
+ sudo -u git GITEA_WORK_DIR=/var/lib/gitea gitea -c /etc/gitea/app.ini admin user create --username u2 --email u2@example.com --random-password --admin
generated random password is '************'
New user 'u2' has been successfully created!
+ sudo -u git GITEA_WORK_DIR=/var/lib/gitea gitea -c /etc/gitea/app.ini admin user create --username u3 --email u3@example.com --random-password
generated random password is '************'
New user 'u3' has been successfully created!
```

### Git Version

git version 2.30.2 (debian bullseye stable repo)

### Operating System

debian bullseye

### How are you running Gitea?

Gitea binary from downloads -> https://dl.gitea.io/gitea/1.17.1/gitea-1.17.1-linux-amd64
Running "from binary" -> following the procedure https://docs.gitea.io/en-us/install-from-binary/, except that app.ini is copied on place (vanilla file as it's generated when does not exist, but disabled registration). I follow the `systemd` part for managing the service
Distribution -> debian bullseye (netinstall, ssh, git and gitea; nothing else)

### Database

SQLite

**Comment by jolheiser** [comment]
https://github.com/go-gitea/gitea/blob/754861a020b4160140d6fb1e4351018fb9ae9374/cmd/admin.go#L558-L569

If you deliberately set `--must-change-password` it should work as expected.

**Comment by Sirtea** [comment]
Good point! Source code is always the response...

So, in short, if there are no users on the database, the default must-change-password is False.
This should be somewhere on the documentation or on the `gitea admin user create --help`.

```
gerard@gitea:~$ gitea admin user create --help | grep must
   --must-change-password          Set this option to false to prevent forcing the user to change their password after initial login, (Default: true)
gerard@gitea:~$
```

Thank you
