### ISSUE TITLE
Gitea freezes while merging a PR

### ISSUE THREAD

**Issue by gmendesM** [go-gitea/gitea#21000]
### Description

PRs get stuck on "Merge conflict checking is in progress. Try again in few moments.". UI sometimes hangs even dozens of minutes or days with this.

### Gitea Version

1.17.1

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

We run Gitea from the command-line.

**Comment by lunny** [comment]
duplicated with #21087
