### ISSUE TITLE
initial username and passwd does not work

### ISSUE THREAD

**Issue by NikolayUvarov** [go-gitea/gitea#21008]
### Description

Setting username gitea, pass gittea. It is saved to ini file as plaintext, but when logging in got wron password error.

### Gitea Version

1.17.1

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

commandline centos7

**Comment by NikolayUvarov** [comment]
I leave admin section unfilled so mixed up pass of db with user pass. When you fill in admin section all work ok.

**Comment by lunny** [comment]
The admin name and password will never save into app.ini.
