### ISSUE TITLE
Describe agit flow in docs

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#21018]
see https://github.com/go-gitea/gitea/pull/14295 & https://git-repo.info/en/2020/03/agit-flow-and-git-repo/

**Comment by CypherpunkSamurai** [comment]
Hello Sir, I'm new to open-source and would like to contribute to the issue. 

I've read the issue description and the linked issue, and I feel like I can help contribute to this.

I've 1 question. Are we supposed to add the markdown file for agit feature [under the content/doc/usage directory?](https://github.com/go-gitea/gitea/tree/main/docs/content/doc/usage)?

**Comment by 6543** [comment]
yes I would add it into this directory as new md file ...

**Comment by 6543** [comment]
... and thanks, docs are important :heart:

**Comment by CypherpunkSamurai** [comment]
Hello Sir,

I've created a draft commit https://github.com/CypherpunkSamurai/gitea/commit/7da176c0181f8cd68c5b75fe8cd7ffc5d2f8702d

Please review changes :)

**Comment by 6543** [comment]
yes just draft a pull against default branch :rocket:

**Comment by CypherpunkSamurai** [comment]
Sure Sir.
