### ISSUE TITLE
OpenID login direct to 404 registration page

### ISSUE THREAD

**Issue by strk** [go-gitea/gitea#2101]
I've logged in on try.gitea.io using livejournal.com and was redirected to https://try.gitea.io/user/openid/register which gave me a 404

**Comment by lunny** [comment]
It's a config problem? Or a bug?

**Comment by cweiske** [comment]
Same problem here, with my own OpenID server.

Gitea sends the following return URL to my OpenID server: `https://try.gitea.io/user/login/openid`.
That page redirects to Location `/user/openid/register`, which 404s.

**Comment by strk** [comment]
@bkcsoft so this was the regression, while #2100 was not :) - please accept #2160 which fixes this regression
