### ISSUE TITLE
[BUG] Due date showing placeholders when modified

### ISSUE THREAD

**Issue by mmarif4u** [go-gitea/gitea#21040]
### Description

If you add a due date to an issue or pr and then modify it. It will show you the placeholders instead.

### Screenshots

![Screenshot_20220903_191410](https://user-images.githubusercontent.com/1280585/188274421-48735be9-0d48-41b6-b3a1-a5273e66279d.png)

### Gitea Version

1.17.1

### Can you reproduce the bug on the Gitea demo site?

Yes

### Browser Version

FF 103

**Comment by jolheiser** [comment]
This was fixed by #20388 and subsequent backport #21032
