### ISSUE TITLE
Avoid GitHub

### ISSUE THREAD

**Issue by Kobaxidze256** [go-gitea/gitea#21047]
### Feature Description

Why does a GitHub alternative use GitHub for hosting code. If you need it so much, why not maintain a private core repo to which GitHub doesn't have write access. I don't see a link to anything similar.

**Comment by delvh** [comment]
See https://github.com/go-gitea/gitea/issues/1029 and the current blocker https://github.com/go-gitea/gitea/pull/18165.
We have planned to do this for a **very** long time now.
