### ISSUE TITLE
Omit database dump when doing gitea-dump

### ISSUE THREAD

**Issue by snakers4** [go-gitea/gitea#21056]
### Feature Description

Gitea dump docs say the [following](https://docs.gitea.io/en-us/backup-and-restore/#backup-command-dump):

> Inside the gitea-dump-1482906742.zip file, will be the following:
> ...
> gitea-db.sql - SQL dump of database
> gitea-repo.zip - Complete copy of the repository directory.

I use a slightly modified gitea Dockerfile with a local folder as an attached volume and an external database:

```
        volumes:
            - /home/snakers4/gitea:/data
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
```

So, I have a question / feature proposal:

- Can database dump be omitted during `gitea-dump`?
- Can gitea be backed by just stopping it and backing up the database and the `/data` folder separately?

**Comment by JulienPalard** [comment]
Looks like a duplicate of: https://github.com/go-gitea/gitea/issues/28720 which has been resolved by @kemzeb adding a `--skip-db` argument.

But I'm also interested by the idea of "just stopping it and backing up the database and the /data folder separately" answer.

**Comment by lunny** [comment]
> Can database dump be omitted during gitea-dump?
#28720 did that like @JulienPalard said.

> Can gitea be backed by just stopping it and backing up the database and the /data folder separately?
Yes for the standard installation from docker.

I think this issue could be closed. Please feel free to reopen it if you have any further problem.
