### ISSUE TITLE
Gitea freezes while merging a PR

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#21087]
### Description

We use Gitea 1.17.1 which should have fixed [PRs stuck on "Merge conflict checking is in progress. Try again in few moments." · Issue #17204 · go-gitea/gitea](https://github.com/go-gitea/gitea/issues/17204) . However, the bug is still there. UI sometimes hangs even dozens of minutes with "Merge conflict checking is in progress. Try again in few moments." This really slows down the development process (we merge 10 PRs every day) and causes a lot of frustration among the developers.

### Gitea Version

1.17.1

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

We run it on command-line.

**Comment by nazario29** [comment]
I can replicate the same issue with gitea 1.17.2 and let me add more detail:
1. First of all I can only see this problem happening when we have a big chunk of changes, in branches with 3 or 4 file changes I see no problem.
1. I open the Pull Request via gitea UI and immediately we see memory from the client's PC raising nonstop until it hits 4 or 5 GB memory and then it throws a browser message about "Out of memory"

**Comment by CypherpunkSamurai** [comment]
Hello Mr. @nazario29, 

Is it possible to enable logging on the instance? It would really help the issue. Thank you :)

**Comment by zeripath** [comment]
Without logs we have no hope of being able to debug this.

**Comment by zeripath** [comment]
I think it would also be helpful to review your app.ini too.
