### ISSUE TITLE
Crash Gitea After Update

### ISSUE THREAD

**Issue by tahaghafuri** [go-gitea/gitea#21099]
### Description

I Updated Gitea v 1.17.1 To 1.17.2,After Update,Gitea Crashed And Don't Run.
I checked All Configs,Cannot Find Error.
(app.ini fixed,firewall,service,. . . )

Please Help Me.

### Gitea Version

1.17.2

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

(https://gist.github.com/tahaghafuri/3c9602594f70e24ef834472be0868f1f)

### Git Version

latest

### Operating System

ubuntu

### How are you running Gitea?

systemd

### Database

MySQL

**Comment by techknowlogick** [comment]
Hi, Please see the link in the form you submitted for the logs we need. What was submitted doesn't tell us anything.

I will close this now, but please re-open if you are able to submit detailed logs.

**Comment by dvgoyeneche** [comment]
Same problem, in ubuntu 20.04.1 LTS

Loaded: loaded (/etc/systemd/system/gitea.service; enabled; vendor preset: enabled)
Active: activating (auto-restart) (Result: exit-code) since Wed 2022-09-07 08:31:57 +0430; 1s ago
Process: 5262 ExecStart=/usr/local/bin/gitea web --config /etc/gitea/app.ini (code=exited, status=1/FAILURE)
Main PID: 5262 (code=exited, status=1/FAILURE)

**Comment by techknowlogick** [comment]
Again, we need detailed logs. All that we've been provided is systemd saying that the process failed but not why.

**Comment by wxiaoguang** [comment]
Use journalctl to collect systemd logs.

**Comment by dvgoyeneche** [comment]
sep 07 08:44:51 GITserver gitea[2767]: 2022/09/07 08:44:51 cmd/web.go:95:func1() [F] PANIC: template: base/footer:15: function "MD5" not defined
sep 07 08:44:51 GITserver gitea[2767]:         /usr/local/go/src/html/template/template.go:374 (0x15cdbd5)
sep 07 08:44:51 GITserver gitea[2767]:         /go/pkg/mod/github.com/unrolled/render@v1.4.1/render.go:322 (0x15cdae9)
sep 07 08:44:51 GITserver gitea[2767]:         /go/pkg/mod/github.com/unrolled/render@v1.4.1/render.go:202 (0x15ccc86)
sep 07 08:44:51 GITserver gitea[2767]:         /go/pkg/mod/github.com/unrolled/render@v1.4.1/render.go:146 (0x15cc7c4)
sep 07 08:44:51 GITserver gitea[2767]:         /source/modules/templates/base.go:86 (0x167eeb5)
sep 07 08:44:51 GITserver gitea[2767]:         /source/routers/web/base.go:127 (0x218c758)
sep 07 08:44:51 GITserver gitea[2767]:         /source/routers/web/web.go:123 (0x218f41e)
sep 07 08:44:51 GITserver gitea[2767]:         /source/routers/init.go:174 (0x21ac784)
sep 07 08:44:51 GITserver gitea[2767]:         /source/cmd/web.go:177 (0x228fd4d)
sep 07 08:44:51 GITserver gitea[2767]:         /go/pkg/mod/github.com/urfave/cli@v1.22.9/app.go:524 (0x1be3ce7)
sep 07 08:44:51 GITserver gitea[2767]:         /go/pkg/mod/github.com/urfave/cli@v1.22.9/command.go:173 (0x1be4ad1)
sep 07 08:44:51 GITserver gitea[2767]:         /go/pkg/mod/github.com/urfave/cli@v1.22.9/app.go:277 (0x1be1346)
sep 07 08:44:51 GITserver gitea[2767]:         /source/main.go:116 (0x22cc598)
sep 07 08:44:51 GITserver gitea[2767]:         /usr/local/go/src/runtime/proc.go:250 (0x43f2d1)
sep 07 08:44:51 GITserver gitea[2767]:         /usr/local/go/src/runtime/asm_amd64.s:1571 (0x4700c0)

**Comment by techknowlogick** [comment]
[F] PANIC: template: base/footer:15: function "MD5" not defined

Please review your custom templates

**Comment by tahaghafuri** [comment]
Log:
[F] Gitea is not supposed to be run as root. Sorry. If you need to use privileged TCP ports please instead use setcap and the `cap_net_bind_service` permission

**Comment by tahaghafuri** [comment]
and i'm restart service,log:
root@plesk:~# systemctl status gitea
● gitea.service - Gitea (Git with a cup of tea)
     Loaded: loaded (/etc/systemd/system/gitea.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Wed 2022-09-07 13:14:05 +0430; 1s ago
    Process: 105160 ExecStart=/usr/local/bin/gitea web --config /etc/gitea/app.ini (code=exited, status=1/FAILURE)
   Main PID: 105160 (code=exited, status=1/FAILURE)

**Comment by wxiaoguang** [comment]
Use journalctl to collect systemd logs.

**Comment by s-s** [comment]
Experienced the same after updating to 1.17.2 with `function "MD5" not defined` error in logs. Problem was with my local outdated templates, fixed by replacing `{{MD5 AppVer}}` to `{{AssetVersion}}`

**Comment by wxiaoguang** [comment]
@s-s sorry for the inconvenience, it's not done by purpose 😭

**Comment by zeripath** [comment]
Yup we made an accidental breaking change when we removed this now unused function.

Update your templates now so you're not affected when 1.18 is released.
