### ISSUE TITLE
Gitea API can't handle slash on method https://git_url/api/v1/repos/repo_owner/repo_name/branch_protections

### ISSUE THREAD

**Issue by nazario29** [go-gitea/gitea#21093]
### Description

When using **Gitea API** method `https://git_url/api/v1/repos/repo_owner/repo_name/branch_protections` and in particular aiming to branches with a slash on the name the response is `404 page not found` instead of a treated message from the API itself, got me thinking that maybe this method is not ready to handle slashes on URL.

This is the request:
```
curl -X 'GET' \
  'https://git_url/api/v1/repos/repo_owner/repo_name/branch_protections/release%2F1' \
  -H 'accept: application/json'
```

But if I use other method for example:
```
curl -X 'GET' \
  'https://git_url/api/v1/repos/devops/sample-java-app/branches/release%2F1' \
  -H 'accept: application/json'
```

I got an expected response from the API:
```
{
  "errors": null,
  "message": "The target couldn't be found.",
  "url": "https://git_url/api/swagger"
}
```

### Gitea Version

1.17.1

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

2.37.2

### Operating System

CentOS 8

### How are you running Gitea?

Running gitea as a systemd service together with postgres DB on a CentOS 8

### Database

PostgreSQL

**Comment by nazario29** [comment]
I removed the Authorization header from this thread on purpose but I get expected responses from other methods.
Nothing relevant in the logs, just the trace of the request itself.

Also, something I forgot to mention is we have Nginx on top of Gitea.

I'm attaching prints from swagger to help explain it:

Failed request on branch_protection with just a 404:
![image](https://user-images.githubusercontent.com/69314381/188697833-2176d9e0-938e-4a46-a42f-a78963826222.png)
Request on branches method that we can see API accepts it and responds:
![image](https://user-images.githubusercontent.com/69314381/188698489-f079d29c-a428-4731-9a74-201d412190f3.png)

**Comment by jolheiser** [comment]
Can you try to reproduce on the demo?
As well, maybe try on your server directly using curl without hitting the proxy, just to check.

**Comment by nazario29** [comment]
Ok it worked on demo gitea, definitely something wrong on my end, will try to investigate it further.
Thank you @jolheiser

**Comment by wxiaoguang** [comment]
Check you nginx config (especially the ending slash for proxy_pass)

Some reverse proxy will decode the path from `release%2F1` to `release/1`, but Gitea expects to see `release%2F1`, you can check whether the URI is correct in Gitea's access log.

**Comment by nazario29** [comment]
After doing the mentioned change here https://github.com/go-gitea/gitea/issues/20890#issuecomment-1222347277 just fixed this issue,
thanks, everyone!
