### ISSUE TITLE
Docker Package Registry not working with sub directory?

### ISSUE THREAD

**Issue by Rincewind34** [go-gitea/gitea#21092]
### Description

According to this documentation: https://docs.gitea.io/en-us/packages/container/ I think it is not possible to use the package registry with docker, if GitEa is running in a sib directory as in "example.com/gitea". 

Is this something that one can bypass by altering the ```docker push``` command?

### Gitea Version

1.17.1

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

Hosted with Docker without subdomain but with sub directory under ```https://mydomain.com/gitea```

**Comment by mlarabi** [comment]
Use a reverse proxy (nginx for example) to rewrite the URL by removing the static part before passing it to your Gitea instance.

**Comment by KN4CK3R** [comment]
That's not a Gitea limitation. The docker api needs the `/v2/` endpoint.

**Comment by Rincewind34** [comment]
Thanks for the feedback! I'll be trying the proxy tomorrow with a colleague. But I did a little digging and it seems to me that this can (and should?) be configured on the server side using the prefix setting: https://docs.docker.com/registry/configuration/#http

**Comment by KN4CK3R** [comment]
The **registry** supports that but the/every **client** does not. See https://github.com/go-gitea/gitea/pull/18438#issuecomment-1024903419 and the following posts for more informations.

**Comment by jlw4049** [comment]
> Thanks guys! I'm no expert but I managed to get this working. Running gitea and nginx with docker compose -- add this to nginx:
> 
> ```
>     location /gitea/ { ## normal GitEA configuration
>         client_max_body_size 10G;
>         proxy_pass http://gitea:3000/;
>     }
> 
>     location /v2/ { ## NEW, necessary for docker registry.
>         client_max_body_size 10G;
>         proxy_pass http://gitea:3000/v2/;
>     }
> ```

This should be added to the gitea documentation for nginx for subfolders
