### ISSUE TITLE
Composer package registry: packages not deletable

### ISSUE THREAD

**Issue by ToSchQLB** [go-gitea/gitea#21104]
### Description

I created a composer package: [https://try.gitea.io/Toni.Schreiber/-/packages/composer/toschqlb%2Fyii2-filter-helper/0.1.7.2](https://try.gitea.io/Toni.Schreiber/-/packages/composer/toschqlb%2Fyii2-filter-helper/0.1.7.2)

But I can't delete it via API

```shell
curl -k --user toni.schreiber:TOKEN-X DELETE \
     https://try.gitea.io/api/packages/toni.schreiber/composer/toschqlb/yii2-filter-helper/0.1.7.2
```

But the result is 404 - page not found.

### Gitea Version

1.17.0

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

https://try.gitea.io/ and own docker-installation does not work

**Comment by wxiaoguang** [comment]
Check your nginx config (especially the ending slash for proxy_pass)

See this one:
* https://github.com/go-gitea/gitea/issues/20890#issuecomment-1222291868

**Comment by ToSchQLB** [comment]
Thank you for this tip but even, if I try it this way
```shell
curl -k --user toni.schreiber:TOKEN -X DELETE \
     https://try.gitea.io/api/packages/toni.schreiber/composer/toschqlb%2Fyii2-filter-helper/0.1.7.2
```
I got Error 404

**Comment by wxiaoguang** [comment]
https://try.gitea.io/api/swagger#/package/deletePackage

![image](https://user-images.githubusercontent.com/2114189/188882143-26eb826f-4e39-4683-b2a6-ab79d8ee9b6c.png)

**Comment by ToSchQLB** [comment]
This works, but here is the problem

I was able to create the package with this URL:
https://try.gitea.io/api/packages/toni.schreiber/composer

But I can't delete with this one:
https://try.gitea.io/api/packages/toni.schreiber/composer/toschqlb%2Fyii2-filter-helper/0.1.7.2

I have to use this one whit api/**v1**/packages:
https://try.gitea.io/api/v1/packages/toni.schreiber/composer/toschqlb%2Fyii2-filter-helper/0.1.7.2

**Comment by KN4CK3R** [comment]
The composer api simply does not offer an endpoint to delete a package. The `/api/v1/` endpoint is the Gitea api.

**Comment by KN4CK3R** [comment]
Can this be closed?
