### ISSUE TITLE
 hello,  I had problems installing Gitea. use these two tutorials in their respective order.

### ISSUE THREAD

**Issue by Wotan6891** [go-gitea/gitea#21115]
### Description

hello,

I had problems installing Gitea.
use these two tutorials in their respective order.

https://linux-packages.com/ubuntu-focal-fossa/package/golang-codegitea-git-dev

https://www.howtoforge.com/how-to-install-gitea-on-ubuntu-22-04/

I was never able to run localhost.

I would like to uninstall the Gitea software that I installed.

1. How do I uninstall Gitea?

Then I want to install Gitea using Snap.

https://snapcraft.io/gitea

Thank you very much for your help.

### Gitea Version

1.17.1

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

https://linux-packages.com/ubuntu-focal-fossa/package/golang-codegitea-git-dev

https://www.howtoforge.com/how-to-install-gitea-on-ubuntu-22-04/

**Comment by jolheiser** [comment]
Did you try the install method from our docs?
https://docs.gitea.io

**Comment by jolheiser** [comment]
In terms of uninstallation, I would just follow the tutorial in reverse.
You'll need to remove the data dir and the binary.

Feel free to drop by discord, matrix, etc if you need more help.
