### ISSUE TITLE
Disallow access to project archive in release unless authorized user has read access

### ISSUE THREAD

**Issue by cleandesign-contrib** [go-gitea/gitea#21110]
### Feature Description

The current [security model](https://docs.gitea.io/en-us/permissions/) of gitea has a certain bit of granularity that allows a user to be restricted from viewing the source code of a project, but allowed to access and download its releases.

This is great, because a CI bot can take the project and post a release, creating an effective security fire-gap.

However, every release comes with an automatically generated `master.zip` and `master.tar.gz` links, which effectively means that if one has access to the releases, then one has access to the entire contents of the project (minus `.git` history).

Would adding the following code [here](https://github.com/go-gitea/gitea/blob/4562d40fcead66e54525f710875377ebf7c4766e/routers/api/v1/repo/file.go#L314) possibly be a solution to this problem?

```go
if !canReadFiles(ctx.Repo) {
        ctx.Error(http.StatusForbidden, "Access Denied", repo_model.ErrUserDoesNotHaveAccessToRepo{
            UserID:   ctx.Doer.ID,
            RepoName: ctx.Repo.Repository.LowerName,
        })
        return
    }
```

**Comment by lunny** [comment]
If you have tried, I think we have done that. For release archives, you must have read permission to Code. This has been implemented but if it's not, it should be a bug.

**Comment by cleandesign-contrib** [comment]
Hi @lunny: then this is a bug. 

There's also an additional bug in that it appears `DISABLE_DOWNLOAD_SOURCE_ARCHIVES` has been orphaned as a configuration setting. Would you like me to split that out into a separate bug?

**Comment by noerw** [comment]
> There's also an additional bug in that it appears DISABLE_DOWNLOAD_SOURCE_ARCHIVES has been orphaned as a configuration setting. Would you like me to split that out into a separate bug?

This is not true, see https://github.com/go-gitea/gitea/blob/bb0ff77e461ae080b1722701aea74010ff71e0ae/routers/web/web.go#L293

**Comment by noerw** [comment]
> However, every release comes with an automatically generated master.zip and master.tar.gz links, which effectively means that if one has access to the releases, then one has access to the entire contents of the project (minus .git history).

@cleandesign-contrib I can't reproduce this in current `1.18.0+dev-402` (52c2ef790). What  gitea version are you referring to?

**Comment by cleandesign-contrib** [comment]
@noerw do you have access to the security email account for gitea? Because I have sent an email there which may or may not be related to this.
