### ISSUE TITLE
option to archive a repository and make it read-only

### ISSUE THREAD

**Issue by rdwz** [go-gitea/gitea#21116]
### Feature Description

I would like to have an option to "Archive a repository" like github has, the repository get's marked as archived and remains read-only.

### Screenshots

![Screenshot 2022-09-09 032024](https://user-images.githubusercontent.com/8125196/189252460-85b08be0-7522-40cb-8fda-11b4c0d7fddd.png)

**Comment by techknowlogick** [comment]
This exists already
