### ISSUE TITLE
`push` webhook doesn't fire when pull request is merged

### ISSUE THREAD

**Issue by berwyn** [go-gitea/gitea#21129]
### Description

I have a sever with Drone and Gitea setup where I want to run steps every time a PR is merged. Drone ignores the PR closed/merged action, so I thought to filter by pushes to `main`, however Gitea doesn't dispatch a `push` event when I merge my PRs (configured as rebase then fast-forward).

Since I cannot find any documentation that lays out what events are pushed and when, I have to assume it's a bug that no push webhook is fired when new commits are pushed to a ref using a PR.

### Gitea Version

1.17.2

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

`gitea/gitea:1.17-rootless` with docker-compose, `docker-ce 20.10.18` running on Ubuntu 22.04

### Database

PostgreSQL

**Comment by jerry3k** [comment]
I can confim we have the same issue: 
Drone Server: drone/drone:2.9.1
Gitea: 1.17.1

**Comment by RealStickman** [comment]
Push events never fire for me either. I tested creating commits directory to a monitored branch and merging a pull request.
Gitea 1.17.2
Woodpecker 0.15.4

In the Monitoring tab, the GET /user/events seems stuck  
![image](https://user-images.githubusercontent.com/61015582/189543636-3979ad73-0436-4c5d-a760-37274911e9a4.png)

**Comment by RealStickman** [comment]
Creating a tag doesn't fire events (Create in webhook) either, with /user/events being stuck.

**Comment by xtulnx** [comment]
@jerry3k @RealStickman Did you fix it please?

**Comment by jerry3k** [comment]
> 

@xtulnx no fix available as of yet.

**Comment by lunny** [comment]
`webhook` is unrelated with `/user/events` which is just related with notification UI. Could you find the webhook record in history?

**Comment by xtulnx** [comment]
@jerry3k @RealStickman hi, I temporarily solved the problem of service exception by downgrading.

1. Stop the service. **Back up your data if necessary**
1. Git Image tag use 1.16.9: `"gitea/gitea:1.16.9"`
1. Delete the record with type=9 in the `repo_unit` table (Database):

    ```sql
    delete from repo_unit where `type`=9;
    ```

3. Modify version=211 in the version table:

    ```sql
    update version set version=211 where version>211
    ```

Downgraded 1.17.2 and 1.18.0-dev successfully. 

Now my webhook and the latest activity in the homepage are back to normal

**Comment by jerry3k** [comment]
> @jerry3k @RealStickman hi, I temporarily solved the problem of service exception by downgrading.
> 
> 1. Stop the service. **Back up your data if necessary**
> 2. Git Image tag use 1.16.9: `"gitea/gitea:1.16.9"`
> 3. Delete the record with type=9 in the `repo_unit` table (Database):
>    ```sql
>    delete from repo_unit where `type`=9;
>    ```
> 4. Modify version=211 in the version table:
>    ```sql
>    update version set version=211 where version>211
>    ```
> 
> Downgraded 1.17.2 and 1.18.0-dev successfully.
> 
> Now my webhook and the latest activity in the homepage are back to normal

Please do NOT do this, as you will be UNABLE to upgrade it in future!

**Comment by wxiaoguang** [comment]
I just setup a Gitea 1.17.2 (docker) locally and did a full test, all work as expected. 

If there is a problem, there are only a few possibilities:

1. The docker version is too low: >=20.10.6
2. The git hooks are out of sync: "Resynchronize pre-receive, update and post-receive hooks of all repositories" on the site admin panel
3. The git repositories (and hooks) are stored on some filesystems(Windows/NAS) which doesn't support script execution, which is pretty a rare case.


If you think you encounter a bug, it needs more information to debug.

----

Test Result

<details>

![image](https://user-images.githubusercontent.com/2114189/192773583-1e314f3f-9805-446b-ba94-e3a7aca51fac.png)

</details>

**Comment by RealStickman** [comment]
@wxiaoguang Thanks for the detailed reply.  
I can confirm storing stuff on a samba share was the issue for me. Local storage works.  
Guess I'll have to use that going forward for gitea.

**Comment by kSandr-ki** [comment]
I still don't understand
how docker version affects this, is it possible to somehow fix this without touching docker?

**Comment by wxiaoguang** [comment]
Because it's a Docker's bug:

* https://github.com/go-gitea/gitea/issues/20103#issuecomment-1166268520

**Comment by kSandr-ki** [comment]
thanks
