### ISSUE TITLE
Support additional clone schemes

### ISSUE THREAD

**Issue by rdwz** [go-gitea/gitea#21121]
## Feature Description
the custom handler for VSCodium is
vscodium://vscode.git/clone?url=

## Screenshots
![](https://user-images.githubusercontent.com/8125196/189298307-818cff76-c45c-4898-b9d8-8525a8a58fc9.png)

**Comment by jolheiser** [comment]
This makes me think we should somehow make this configurable.

One option is to maintain a custom template, but understandably that's less than ideal for this.
Another option is to somehow make this a type of config setting that's dynamic.

Nothing against vscodium, if I'm honest I also (personal opinion) don't like that we've already added a vscode link to begin with.

Perhaps we should discuss how to make this generic before we end up with another "adding webhooks for every service" problem. 😅

**Comment by 6543** [comment]
User preverences ...

**Comment by silverwind** [comment]
Does VSCodium not support `vscode://` urls? I think it'd be better to start there.

**Comment by jolheiser** [comment]
I think we could 

1. Add another custom-only template like how we do for header links, etc. or;
2. Somehow make this a dynamic configuration option similar to external renderers

**Comment by silverwind** [comment]
No custom templates please, they suck 😉. Maybe with config:

```
repo.ADDITIONAL_CLONE_SCHEMES = vscodium://,sublime://
```

**Comment by jolheiser** [comment]
> Still, generall I think the issue is on the editors, not us.

Probably true, but I custom protocol probably lets them do other things that's specific to each editor (maybe?)
I think a config option would work fine with a little forethought

**Comment by silverwind** [comment]
Problem with the option approach is user can not set icon, but that may be acceptable.

**Comment by silverwind** [comment]
Well I suppose one could have a JSON value in the config option, but I don't think we do those yet.

```ini
repo.ADDITIONAL_CLONE_SCHEMES = '[{"scheme": "vscodium://", "icon": "<svg/>"}]'

**Comment by jolheiser** [comment]
Could have a config option for local image or web image. 
In terms of "security", since it would be config-level, it would be up to the admin?

**Comment by silverwind** [comment]
Would keep it simple, just SVG string support. Security should be fine as it's in the config, only admin-accessible.

**Comment by jolheiser** [comment]
> Would keep it simple, just SVG string support.

For a web image, technically Gitea could even host the image in its custom dir, which would still allow users to serve it themselves without relying on another service. 
And I think might be nicer than storing JSON in an ini config?

**Comment by CypherpunkSamurai** [comment]
I think adding more than editor svg could be confusing later on. We can simply skip it and use a standard icon for code editor urls, and just have the text beside it.

![image](https://user-images.githubusercontent.com/66906402/189500899-191088cd-acf9-4ac3-bcdb-1cdbd2cd367b.png)

**Comment by yashpalgoyal1304** [comment]
hey @author @redwerkz can u add a test link in the description (first comment) of this issue? e.g.:

"Repositories for trial on gitea are at: https://try.gitea.io/"

**Comment by lunny** [comment]
Please don't talk about your opinion of community governance in a special issue.
