### ISSUE TITLE
current default_delete_branch_after_merge value not returned by api

### ISSUE THREAD

**Issue by jsalatiel** [go-gitea/gitea#21138]
### Description

Any changes to the repo using api at  https://gitea.url/api/v1/repos/user/repo returns the current values for the repo, but it does not return the current value for default_delete_branch_after_merge. This way it is not possible to build idempotent ansible modules If one can not get the current value.

### Gitea Version

1.16.5

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

docker

### Database

PostgreSQL

**Comment by jolheiser** [comment]
It is returned.
![Screenshot_20220910_194024](https://user-images.githubusercontent.com/42128690/189506663-9a4dcb5a-624a-4a63-84bd-5f9d1ec9b966.jpg)

**Comment by jsalatiel** [comment]
That's odd. I do not have that in my output.
<img width="415" alt="image" src="https://user-images.githubusercontent.com/5522389/189506754-794f5829-5444-46ee-8f63-f1e97081b683.png">

**Comment by jolheiser** [comment]
It is unreleased in 1.18 currently.
