### ISSUE TITLE
RFE: Add more event types to get parity with GitHub event types

### ISSUE THREAD

**Issue by stephenc** [go-gitea/gitea#2113]
- Gitea version (or commit ref): N/A
- Git version: N/A
- Operating system: N/A
- Database (use `[x]`): N/A
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io: N/A
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

Please add more event types to bring closer parity to the GitHub event types:

<img width="677" alt="screen shot 2017-07-04 at 22 13 51" src="https://user-images.githubusercontent.com/209336/27842941-872a512a-6106-11e7-8c96-2fbc443ee977.png">

Specifically, first round targets:

- [x] Repository
- [x] Pull request review comment
- [x] Delete
- [x] Fork
- [x] Issues
- [x] Issue comment

The others are not really relevant for the current feature set

**Comment by ethantkoenig** [comment]
See #1663, which adds support for "repository" events

**Comment by lunny** [comment]
maybe a duplicated with https://github.com/go-gitea/gitea/issues/2418

**Comment by lunny** [comment]
Only `Pull request review comment` left here since #3929 merged.

**Comment by stephenc** [comment]
@lunny any eta on `Pull request review comment` ?

**Comment by lunny** [comment]
@stephenc I think that has been resolved.  Sorry to forget close this issue, see https://github.com/go-gitea/gitea/pull/5027.

**Comment by lunny** [comment]
All event types have been implemented on v1.7.x
