### ISSUE TITLE
All collaborative repositories disappeared from the dashboard

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#2114]
This bug should be caused by #1750.

**Comment by andreynering** [comment]
I'll take a look at this when have time.

This should be fixed at `/repo/search` API route. It's probably not returning collaborative repos.

**Comment by lunny** [comment]
This has been resolved by #2285

**Comment by lafriks** [comment]
@lunny are you sure this was fixed? As merged PR just changed UI not how searching was done
