### ISSUE TITLE
Alllow all schemes in markdown by default

### ISSUE THREAD

**Issue by tobiasBora** [go-gitea/gitea#21146]
### Description

Using the main intance https://gitea.com I am unable to insert non-http emails. In particular I am interested to add links to my emails (I use the tool only internally) provided by the [https://camiel.bouchier.be/en/cb_thunderlink](https://camiel.bouchier.be/en/cb_thunderlink) extension. Unfortunately links like `cbthunderlink://somebase64string` are not clickable, even if I explicitely use the longer url notation:

```
See you can't click me [cbthunderlink://somebase64string](cbthunderlink://somebase64string)
```

### Gitea Version

1.18.0+dev-333-g9e0c43777

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

![image](https://user-images.githubusercontent.com/2164118/189615669-c888115f-2e35-4a39-a288-d3d39ca23299.png)

![image](https://user-images.githubusercontent.com/2164118/189615452-32a6cf5f-c528-4046-ade1-6dc8246e12ee.png)

### How are you running Gitea?

Using the instance from https://gitea.com

**Comment by wxiaoguang** [comment]
There is an config option. markdown.CUSTOM_URL_SCHEMES

**Comment by tobiasBora** [comment]
Hum good to know… but I guess it will not work if I do not own the server (which is my case)… Is there any security reason for this limitation?

**Comment by wxiaoguang** [comment]
I believe security is the main concern (although it's not designed by me).

Some schemes/protocols could lead to security problem.

**Comment by wxiaoguang** [comment]
I would agree with you if there is no more security concern. The code is as old as year 2014 and 2016

https://github.com/go-gitea/gitea/commit/3a9fd81f5946cbd70390b9c061bdcd1842f29735
https://github.com/go-gitea/gitea/commit/a4cbe79567072befd96cf1b7eb319de1e2809ca3

**Comment by tobiasBora** [comment]
Ok perfect then!
