### ISSUE TITLE
Filter/sort issues in a board

### ISSUE THREAD

**Issue by tobiasBora** [go-gitea/gitea#21149]
### Feature Description

I found no way to filter and sort issues from a kanboard board (or project as they are called). For instance I may like to show only the issues that are still open (one could even imagine to provide an option to automatically hide the closed issues for a given board). And more advanced filtering could also be interesting, for instance to filter all issues that are assigned to myself etc…

**Comment by lunny** [comment]
Duplicate of #21846 ?

**Comment by tobiasBora** [comment]
Yes, funnily enough it got created only a few weeks after mine ^^ Will close in favor of it.
