### ISSUE TITLE
Mail Notification Not Sending When New commit

### ISSUE THREAD

**Issue by urunsal** [go-gitea/gitea#21143]
### Description

my installed version 1.17.2
app.ini file mail sending flag is active but mail sending not working.

### Gitea Version

1.17.2

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

windows

### How are you running Gitea?

windows service

### Database

PostgreSQL

**Comment by techknowlogick** [comment]
We need:
1. 🪵 LOGS 🪵
    See https://docs.gitea.io/en-us/logging-configuration/#debugging-problems for how to set up DEBUG logs.
    See https://docs.gitea.io/en-us/faq/#stdout-logging-on-systemd-and-docker for how to see stdout logging.
2. app.ini - please censor KEYs, passwords and other confidential information but it really helps to see the whole app.ini instead of segments.

**Comment by wxiaoguang** [comment]
I will close this issues. Feel free to re-open if you have more logs and clues.

For 1.18, there is a new feature, you can receive your own notifications.
