### ISSUE TITLE
Allow sharing one SSH key between multiple accounts

### ISSUE THREAD

**Issue by forestbeasts** [go-gitea/gitea#21141]
### Feature Description

So, we're plural (multiple people living in the same body). We've got multiple accounts on our own personal gitea server, one per person who's bothered to set one up.

This is great! ... except when we go to add SSH keys.

Gitea apparently rejects a SSH key if it's already been added to another account. This means that we have to use a separate key for each account, which wouldn't be that big of a deal except it means we need to configure SSH to _send_ a different key for each account. So we have to use things like "git@giteadomain-user:user/repo", and we end up with a SSH hosts file that has a bunch of "giteadomain-user" fake hosts in it.

Allowing one key on multiple accounts wouldn't be a security issue, I don't think: the accounts all belong to us anyway. So, how about letting us share a SSH key?

-- Frost

**Comment by forestbeasts** [comment]
... okay update: apparently SSH lets you put in multiple keys and it tries them all! That helps IMMENSELY, making this much less big of a deal.

(It'd still be nice not to have to make tons of keys though, of course.)

**Comment by lunny** [comment]
But how do you know which user should be login when push with that SSH public key?

**Comment by wxiaoguang** [comment]
A SSH key can be only used for one account. Otherwise if someone does "git push git@gitea.host", the Gitea server can not know what the user is for the key.
