### ISSUE TITLE
Custom Routing / new Pages?!

### ISSUE THREAD

**Issue by CMiksche** [go-gitea/gitea#2115]
- Gitea version (or commit ref): v1.1.2
- Git version: 2.11.0
- Operating system: Ubuntu 17.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist: None

## Description

Is there any way to create custom pages with the templating engine and custom routes?

Here in germany, we need at least two custom sites (imprint and privacy policy) and it would be great, if i could create this two sites in the custom directory.

The template files can already be created in _**custom/templates**_ but how do i define the routing?

It looks like the routing is made in go files in the _**routers**_ directory? That means i would have to edit the source files? (And updates would destroy my changes?)

## Screenshots

None

**Comment by lafriks** [comment]
Probably this could be created adding new reserved name `pages` and something like Gitea wiki but editable only by admins

**Comment by AlbertoGP** [comment]
After #3308 "Templates for extra links in top navbar and repo tool tabs." you can do this by placing your extra sites/pages under your "custom/public/" directory (for instance `custom/public/impressum.html`) and putting links to them in `custom/templates/custom/extra_links.tmpl`:
https://docs.gitea.io/en-us/customizing-gitea/#customizing-gitea-pages

To match the current style, the link should have class name "item":
`<a class="item" href="{{AppSubUrl}}/impressum.html">Impressum</a>`

**Comment by lafriks** [comment]
That should be added to docs

**Comment by AlbertoGP** [comment]
Hi, I've added that information to the docs and also listed all the other template hooks at the PR "Improve documentation about custom templates. #3345"

**Comment by CMiksche** [comment]
Sounds good. Im closing this issue now
