### ISSUE TITLE
Container registry show image hash

### ISSUE THREAD

**Issue by iplusplus42** [go-gitea/gitea#21160]
### Feature Description

Hello! I think it would be helpful to show the image hashes/digests for docker container images on the respective package page. I tend to reference them for verifying the build/push/pull process. I don't think Gitea currently has this, but if it does, I can't seem to find it. Thank you!

### Screenshots

<img width="1366" alt="Image" src="https://user-images.githubusercontent.com/5349957/189973389-c1a28115-7217-4df3-b5df-9b423efb4a2a.png">

**Comment by KN4CK3R** [comment]
Added in #21170

**Comment by iplusplus42** [comment]
Many thanks!
