### ISSUE TITLE
Multi select and delete issues

### ISSUE THREAD

**Issue by meaz** [go-gitea/gitea#21165]
### Feature Description

With v17, an admin can delete an issue.
It would be nice, in the issues list, to be able to multi select issues to delete them. At the moment we can just multi select and close them.

**Comment by lafriks** [comment]
Deleting issues should be last resort action when some sensitive info is posted etc that must be deleted and as it's unrevertable I don't think it's good idea to have multidelete from list

**Comment by lunny** [comment]
You can do that via API if you really want to do.

**Comment by meaz** [comment]
We have a bunch of spammers that create several issues, that is why that would be really useful to multi select / delete them...

**Comment by lafriks** [comment]
there is option in latest version to purge all user comments when deleting spammer users

**Comment by yp05327** [comment]
This is supported now.
