### ISSUE TITLE
FreeIPA: LDAP group sync does not work with several LDAP Group mapping

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#21163]
Having the same issue with FreeIPA. But this time, nothing works. Settings are as follows:
![Снимок экрана от 2022-09-13 18-45-01](https://user-images.githubusercontent.com/1463277/189955583-b1c7eb04-f981-4662-9e65-e74c6217666d.png)

**{"cn=developers,cn=groups,cn=accounts,dc=autogramma,dc=lan":{"Autogramma":["Developers"]},"cn=engineers,cn=groups,cn=accounts,dc=autogramma,dc=lan":{"Autogramma":["Engineers"]}}**

Any help?

_Originally posted by @drequivalent in https://github.com/go-gitea/gitea/issues/20954#issuecomment-1245653364_

**Comment by drequivalent** [comment]
I already created #21159 pls close
