### ISSUE TITLE
Layout issue on mobile with  code comment user avatar

### ISSUE THREAD

**Issue by noerw** [go-gitea/gitea#21173]
### Description

Happens on current  mobile firefox and chrome on android 10.

### Screenshots

![signal-2022-09-15-113557](https://user-images.githubusercontent.com/7880552/190436505-3b63f7ae-8fda-4fd7-9d49-ec8b9abb58ff.jpeg)

### Gitea Version

1.18.0+dev-421-geaa561145  (eaa561145)

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

android 10

### Browser Version

firefox 104.1.0

**Comment by silverwind** [comment]
IIRC, there is already an issue for this somewhere.

**Comment by noerw** [comment]
you're right, dupe of https://github.com/go-gitea/gitea/issues/20970
