### ISSUE TITLE
Do not show Add file button if user has no rights to add files to repo

### ISSUE THREAD

**Issue by lafriks** [go-gitea/gitea#21179]
### Description

Currently button with empty submenu is shown

### Gitea Version

1.17.2

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

Not relevant

**Comment by wolfogre** [comment]
I believe it has been fixed by #20718, and backport #20719 has been merged too.

I can't reproduce the error on v1.17.2, maybe this is a false positive?

**Comment by lunny** [comment]
I can confirm this has been fixed in branch v1.17.
