### ISSUE TITLE
Creating Token via API with Token authentication is not possible

### ISSUE THREAD

**Issue by davidhiendl** [go-gitea/gitea#21186]
### Description

In trying to write a Drone Secrets Extension to allow Drone pipelines to obtain a per-pipeline Gitea API Token automatically I ran into 2 problems:

1. Trying to create a token for a user does not work when using a token for authorization:
```bash
curl -X 'POST' \
  'https://gitea.test/api/v1/users/test123/tokens' \
  -H 'accept: application/json' \
  -H 'Authorization: token xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' \
  -H 'Content-Type: application/json' \
  -d '{
  "name": "drone_123123_2022-09-16-14-00"
}'
```
Response: `{"message":"auth required","url":"https://gitea.test/api/swagger"}` 
Note: The token was created for an admin user account.

**Edit**: Forgot to mention the same problem seems to be present for listing and deleting tokens as well.

2. ~~Trying to create API tokens for different users via the API is not possible. In the following example I'm trying to create a token for the user "test123" (the user has been created already). However the token is created for my primary user (the one specified via basic auth credentials).~~ This requires the `sudo` get param, the URL is however confusing because it also contains a `username` path param.

```bash
curl -X 'POST' \
  'https://gitea.test/api/v1/users/test123/tokens' \
  -H 'accept: application/json' \
  -u "admin:xxxxxxxx" \
  -H 'Content-Type: application/json' \
  -d '{
  "name": "drone_123123_2022-09-16-14-00"
}'
```

The reason appears to be that the controller uses the request context user instead of the one specified in the path parameter:
https://github.com/go-gitea/gitea/blob/548387b2beaaaeb6b1c32c3c6f226b8f53aafecb/routers/api/v1/user/app.go#L101

### Gitea Version

1.17.2

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

- official docker image 
- deployed via helm chart

### Database

PostgreSQL

**Comment by lunny** [comment]
You can use `?sudo=my_user` with an admin token.

**Comment by davidhiendl** [comment]
@lunny Thanks for the info. Adding GET parameter with the target username works. It is however confusing, that the URL has a `.../{username}/...` path param.
But the first problem remains: It appears those endpoints don't work with a token.

**Comment by abdennour** [comment]
actually i am using the admin user which is bootstrapped with helm..
```sh
base_url=http://$USERNAME:$PASSWORD@gitea:3000/apiv/v1
curl -u $USERNAME:$PASSWORD -X POST ${base_url}/users/$USERNAME/tokens 
```

tried many times, but always getting
```
{"message":"auth required","url":"http://gitea:3000"}
```

My requirements is to bootstrap many things (organizations, repos,...etc) just after having the Gitea up & running... while doing ZERO manual administration

**Comment by abdennour** [comment]
It's typo while copy paste here , not in the source code . Could you confirm if we remove that typo, everything else should work ? I am using the official helm chart to install it BTW

**Comment by davidhiendl** [comment]
@abdennour I'm using Golang to create users using the `api/v1/admin/users` endpoints and tokens using the `api/v1/users/{user}/tokens?sudo={user}`. Works fine.

**Comment by abdennour** [comment]
If you could share snippet of code, I would appreciate that. I am familiar with Go and I can proceed with that

**Comment by davidhiendl** [comment]
@abdennour I've tried to use the API with curl via Ansible for automation and it works just fine. If the following does not work I suspect there is something else wrong on your end.

```bash
curl -X 'POST' \
  'https://gitea.example.com/api/v1/admin/users' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -u "adminuser:adminpassword" \
  -d '{
  "email": "user@example.com",
  "full_name": "Example User",
  "login_name": "example",
  "must_change_password": true,
  "password": "example123",
  "restricted": true,
  "send_notify": true,
  "username": "example"
}'
```

**Comment by davidhiendl** [comment]
I updated the ticket name and description to better reflect the problem besides the `sudo` param.

**Comment by abdennour** [comment]
Thank you @davidhiendl ! Actually, I switched to the CLI and it works like a charm :

tea login add --name admin 
tea org list

**Comment by davidhiendl** [comment]
@abdennour Please read the issue again. The issue is not creating a token using basic auth on the API, but rather creating **additional** tokens using an already existing token.

**Comment by techknowlogick** [comment]
>  using an already existing token.

This is intentionally not possible, and related basic auth will be deprecated in the future (no date set yet). Creating app tokens with existing app tokens may be revisited when scoped tokens are introduced.
