### ISSUE TITLE
Missing docker images for release 1.16.10

### ISSUE THREAD

**Issue by emetrix** [go-gitea/gitea#21191]
### Feature Description

Can you please provide official images for Gitea release 1.16.10 at hub.docker.com ?

**Comment by zeripath** [comment]
Gitea 1.16 is now out of support and you should use 1.17.x

**Comment by emetrix** [comment]
Usually I always use the latest minor release versions like 1.15.11, 1.16.10, ... because 1.17.x seems to have
 some issues...

**Comment by wxiaoguang** [comment]
1.17.2 should be stable enough. What issues are in 1.17.x do you think?

**Comment by emetrix** [comment]
Thank you. I'll give 1.17.2 a try...
