### ISSUE TITLE
The js-clone-url-vsc element is located below the script

### ISSUE THREAD

**Issue by tyroneyeh** [go-gitea/gitea#21224]
### Description

So this part is useless

https://github.com/go-gitea/gitea/blob/main/templates/repo/clone_script.tmpl#L25
https://github.com/go-gitea/gitea/blob/main/templates/repo/home.tmpl#L129

### Gitea Version

1.17.2

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

gentoo

### How are you running Gitea?

systemd

### Database

PostgreSQL

**Comment by tyroneyeh** [comment]
v1.17.2 or later still one more issue

![image](https://user-images.githubusercontent.com/1255041/191631544-bf76dbee-2c89-4896-b9a3-5a7e1dd11158.png)

**Comment by wxiaoguang** [comment]
Hmm, that's strange. IIRC someone mentioned that the ``` `..//...` ``` can not be used. Maybe that's the root problem.

For 1.18-dev, it works fine https://try.gitea.io

**Comment by wxiaoguang** [comment]
It will fixed by https://github.com/go-gitea/gitea/pull/21226

ps: the bug doesn't exist in 1.17.2, but only in unrelease 1.17-dev

Thank you very mucy for testing it!
