### ISSUE TITLE
Clicking on "Viewed" on a PR after "Show more" doesn't work

### ISSUE THREAD

**Issue by Fifi31** [go-gitea/gitea#21228]
### Description

Hello, when reviewing a PR with a lot of files, only some files are displayed. After clicking on "Show more" at the bottom of the page, if you click on "Viewed" on the first of the newly displayed files, it is the first file of the page that has its "viewed checkbox" checked/unchecked. Same happens on the second newly displayed file, it is the second file of the page that is changed.
When clicking on the checkbox and not the label, it works though.

You can reproduce it here : https://try.gitea.io/vtaix/test/pulls/1/files

### Screenshots

![gitea](https://user-images.githubusercontent.com/42673300/191476913-276f4532-2665-4604-aa43-e53c75b446b8.png)

### Gitea Version

1.17.1

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

Ubuntu 20.04

### Browser Version

Firefox 104.0

**Comment by wxiaoguang** [comment]
Maybe related to this one:
* https://github.com/go-gitea/gitea/issues/20681
