### ISSUE TITLE
[gitea.io] Website is only displayed in Chinese.

### ISSUE THREAD

**Issue by infacto** [go-gitea/gitea#21231]
Visiting https://gitea.io/ directly or e.g. via Google always forward to https://gitea.io/zh-cn/. I see no language select. It should be english by default. (https://gitea.io/en-us/) Btw. when I enter: https://gitea.io/index.html it works. But https://gitea.io/ is always zh-cn. I would also suggest to avoid language in URL.

Tested in Firefox and Chrome 105 on Windows 10 (english is not set as main language, but also not chinese).

**Comment by lunny** [comment]
Please fire it in https://gitea.com/gitea/website/issues
