### ISSUE TITLE
heatmap does not reflect all contributions

### ISSUE THREAD

**Issue by daviddoji** [go-gitea/gitea#21235]
### Gitea Version

1.17.2

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

This is what I can see from the dashboard:
![image](https://user-images.githubusercontent.com/4411314/191685461-c2b962a4-3f91-48b1-8a6d-ff14826747bf.png)

But entering at that very same repo, I can see that more contributions have been made recently:
![image](https://user-images.githubusercontent.com/4411314/191686596-0c082712-232c-4b0f-b93b-1e33ac6570cd.png)

As it can be seen, the user is the same in both screenshots

### Operating System

Linux

### How are you running Gitea?

Self-hosted

### Database

MySQL

**Comment by necarnot** [comment]
Hello,

That may be related, but I'm witnessing the same kind of issue when just after logging in, and choosing the correct context, the displayed list is not showing anymore [1] the updated list of commits.
But when entering in each repo, the header line is showing the last commit action.

[1] This has worked for years, and stopped maybe around 1.17.something (let's say maybe 4 months ago)

**Comment by wxiaoguang** [comment]
It seems that your Git Hook doesn't work.

Could you try the FAQ first https://docs.gitea.io/en-us/faq/#push-hook--webhook-arent-running ?

**Comment by DocBrown101** [comment]
I just noticed that it has not worked for me for a few months. Is there a way to display the missing months?

**Comment by wxiaoguang** [comment]
https://docs.gitea.io/en-us/faq/#push-hook--webhook-arent-running
