### ISSUE TITLE
Online Security Policy breaks the interface

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#21238]
### Description

After employing Online Security Policy i.e. CSP gitea interface has some issues.

When applying the following rules: 

Content-Security-Policy
default-src 'self' *.x-files.dk *.cloudflare.com fonts.googleapis.com fonts.gstatic.com; frame-ancestors 'self' *.x-files.dk; object-src *.x-files.dk/; script-src *.x-files.dk/; style-src 'self'; font-src 'self' data:;

So for this to work I had to add the following which is below best practice for CSP

default-src 'self' *.x-files.dk *.cloudflare.com fonts.googleapis.com fonts.gstatic.com https://secure.gravatar.com; frame-ancestors 'self' *.x-files.dk; object-src *.x-files.dk/; script-src *.x-files.dk/ **'unsafe-inline'** **'unsafe-eval'**; style-src 'self' **'unsafe-inline'**; font-src 'self' data:;

No one absolutetly no one should ever use: **'unsafe-inline'** as well as **'unsafe-eval'** in their Content Security Policy. 

### Gitea Version

gitea-1.17.2-linux-amd64

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

N/A

### Screenshots

![gitea](https://user-images.githubusercontent.com/107126577/191732542-4841edc1-c892-4e60-bb36-208a8afa355b.png)

### Git Version

gitea-1.17.2-linux-amd64

### Operating System

Ubuntu 22.04

### How are you running Gitea?

Runs as a service on a stand alone server.

### Database

MySQL

**Comment by wxiaoguang** [comment]
Related to this one
* https://github.com/go-gitea/gitea/issues/19851

**Comment by silverwind** [comment]
Inline scripts are currently necessary for the clone script which we should remove.
Inline styles will be a massive refactor and probably be nigh impossible as jQuery show/hide and Fomantic-UI depend on them.

**Comment by xfilestogo** [comment]
> Inline scripts are currently necessary for the clone script which we should remove.
> Inline styles will be a massive refactor and probably be nigh impossible as jQuery show/hide and Fomantic-UI depend on them.

Right I know this is not easy and I could very well live with inline styles beeing needed for now if inline scripts would go. What botheres me the most is the “unsafe eval” any thoughts on this one ?

**Comment by silverwind** [comment]
I don't think there is any `eval` use in the codebase or the dependencies, but IIRC, browser count other things as `eval` as well, maybe you can get a list of problematic JS call sites.

**Comment by xfilestogo** [comment]
Indeed good idea I will, I’m at work right know but once I get home I’ll get them listed. Should I post them here ?

**Comment by xfilestogo** [comment]
> Related to this one
> 
> * [Branch selector disappear immediately (JS `eval` function is blocked by CSP) #19851](https://github.com/go-gitea/gitea/issues/19851)

Indeed it is thnx.
