### ISSUE TITLE
Mailgun setup fails certificate validation

### ISSUE THREAD

**Issue by miguelpeixe** [go-gitea/gitea#21241]
### Description

While setting up Mailgun with either:

```
HOST=smtp.mailgun.com:587
IS_TLS_ENABLED=true
```

or

```
HOST=smtp.mailgun.com:465
IS_TLS_ENABLED=false
```

Returns the following error while sending a test email:

```
gomail: could not send email 1: StartTLS: x509: certificate is valid for *.mailgun.org, mailgun.org, not smtp.mailgun.com
```

Seems like a bug in validation, since `*.mailgun.org` is a wildcard that covers `smtp.mailgun.com`

### Gitea Version

1.17.2

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

Latest stable image under docker

### Database

MySQL

**Comment by wxiaoguang** [comment]
```
gomail: could not send email 1: StartTLS: x509: certificate is valid for *.mailgun.org, mailgun.org, not smtp.mailgun.com
```

I think this message is clear, it said that you are connecting to `smtp.mailgun.com`, but `smtp.mailgun.com` claims that it uses certificates for `*.mailgun.org, mailgun.org`. It doesn't look like a Gitea problem.

**Comment by miguelpeixe** [comment]
How would a `*.mailgun.org` certificate not include `smtp.mailgun.com`?

**Comment by wxiaoguang** [comment]
The question could only be answered by mailgun

**Comment by miguelpeixe** [comment]
Huh, I just now saw the TLD 🤦

**Comment by miguelpeixe** [comment]
Yep! Thank you :)
