### ISSUE TITLE
Table UI is overflow when package label is too long

### ISSUE THREAD

**Issue by noahziheng** [go-gitea/gitea#21248]
### Description

Hi all, I found a UI problem when I try to publish the container image to Gitea Package by Paketo + Cloud Native Build Pack:
- Only divider in the "Layers" section if the layer name is empty
  - Maybe need a default shown value such as `(Empty)`
- The content is overflow in the "Labels" section if the label is too long
  - Maybe we can show the split content in the table, and provide a popover view to show the full content of the label.

### Screenshots

![image](https://user-images.githubusercontent.com/2758317/191968082-00dc103f-aba7-4772-b611-45905cd7a5fb.png)

### Gitea Version

1.17.2

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

Windows 11

### Browser Version

Microsoft Edge 105.0.1343.42

**Comment by KN4CK3R** [comment]
@silverwind Any idea about the table? With `ui very basic fixed compact table` the problem is gone but the auto width of the columns too. I don't know why the table can overflow the parent div.
