### ISSUE TITLE
Error 500 is reported when the repo belonging to the organization is released

### ISSUE THREAD

**Issue by suli3** [go-gitea/gitea#21240]
### Description

Error 500 is reported when the repo belonging to the organization is released

steps：
1. release with tag

![image](https://user-images.githubusercontent.com/1057425/191762660-4741418b-5768-43a1-8dc7-870b968b3ad3.png)

2. web ouput 500

![image](https://user-images.githubusercontent.com/1057425/191762904-f20acb96-d8d7-4270-ba9a-1a08396b41b0.png)

3. save as draft, the 500 error output still there.

### Gitea Version

1.17.2

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

docker

### Database

MySQL

**Comment by 42wim** [comment]
I can not reproduce this on main, 1.17.3 or on the demo site.
