### ISSUE TITLE
Extra blank line shown at end of files

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#21255]
### Description

Any file that ends in a single `\n` (so no visible trailing newline in text editors) seems to have an extra blank numbered line shown when viewing it from Gitea on web. I'm posting this as a new issue as #4050 is closed and locked but it appears to have regressed.

I can't seem to reproduce this on try.gitea.io so perhaps it's been fixed in dev already, but on a quick search I haven't found any recent commits or issues relating to this.

### Gitea Version

1.17.2

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

`No EOL`:
![Screenshot of No EOL](https://user-images.githubusercontent.com/482367/192094854-ac50d1ce-8ee6-4ff1-b21e-b1e959062724.png)

`Single EOL\n`:
![Screenshot of Single EOL](https://user-images.githubusercontent.com/482367/192094878-400d993d-8f1f-4bf5-963e-70152d0f2fee.png)

`Double EOL\n\n`:
![Screenshot of Double EOL](https://user-images.githubusercontent.com/482367/192094890-ce86150c-cdb0-47f7-9676-0d94fd684c96.png)

### Git Version

2.31.0

### Operating System

Debian 11

### How are you running Gitea?

Precompiled build, systemd service

### Database

MySQL

**Comment by wxiaoguang** [comment]
Can you try it with 1.18 (https://try.gitea.io)?

I think the problem has a clear solution now:

* https://github.com/go-gitea/gitea/pull/18076#issuecomment-1240149559
