### ISSUE TITLE
Error 500 if upload non SemVers Conan packages

### ISSUE THREAD

**Issue by Leopol123** [go-gitea/gitea#21250]
### Description

We are trying Gitea as repository.

We are experimenting the same issue that this case using Conan package:

https://github.com/go-gitea/gitea/issues/20603#issue-1324905900

[****](https://github.com/go-gitea/gitea/issues/20603#issuecomment-1247069270)

If we upload a conan package using nonSem version, we have error 500 on repo package pages.

To fix this issue, I update semver_compatible from true to false :

```
giteadb=# UPDATE package SET semver_compatible = 'f' WHERE id = 7;
UPDATE 1
giteadb=# UPDATE package SET semver_compatible = 'f' WHERE id = 9;
UPDATE 1
giteadb=# select * from package;
 id | owner_id | repo_id |  type   |     name     |  lower_name  | semver_compatible
----+----------+---------+---------+--------------+--------------+-------------------
  1 |        2 |       0 | generic | cirros       | cirros       | f
  2 |        4 |       0 | conan   | boost        | boost        | t
  4 |       12 |       0 | conan   | b2           | b2           | t
  5 |       12 |       0 | conan   | boost        | boost        | t
  6 |       12 |       0 | conan   | grpc         | grpc         | t
 10 |       12 |       0 | conan   | openssl      | openssl      | t
 11 |       12 |       0 | conan   | zlib         | zlib         | t
  7 |       12 |       0 | conan   | libbacktrace | libbacktrace | f
  9 |       12 |       0 | conan   | opengv       | opengv       | f
(9 rows)

giteadb=#
```

There is no command on conan upload cli to fix semvers to true or false.

Is this a bug in Gitea ?

Thanks,

### Gitea Version

1.18-dev

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

Ubuntu 22

### How are you running Gitea?

Install gitea on vmware virtual machine, ubuntu22 using the binary.

### Database

PostgreSQL

**Comment by KN4CK3R** [comment]
I expected conan to use SemVer but the upload did not enforce it. I don't use conan in production, are non-SemVer versions common and should the registry allow non-SemVer versions?

The docs are not clear about that:
https://docs.conan.io/en/latest/versioning/introduction.html

> It is also true that the semver definition that comes from other programming languages doesn’t fit that well to C and C++ packages, because of different reasons, because of open source libraries that don’t closely follow the semver specification, but also because of the ABI compatibility issues and compilation model that is so characteristic of C and C++ binaries.

**Comment by Leopol123** [comment]
I am more an ops than a dev. Our dev team uses non-SemVer versions on Conan packages but I don't know if it's a good practise.

Thanks for your interest on thi s issue.

**Comment by stefled** [comment]
For instance, [libbacktrace](https://conan.io/center/libbacktrace) recipe on Conan-center index doesn't use SemVer : version is cci.20210118  and we encounter the problem with this dependency.

not tested, but perhaps it's the same with :
- [android-ndk](https://conan.io/center/android-ndk)

More generally, we cannot either manage an intermediate version in dev : "latest" or other string version currently with Gitea.
