### ISSUE TITLE
Allow creation of empty pull requests

### ISSUE THREAD

**Issue by maximilize** [go-gitea/gitea#21258]
### Feature Description

Our development flow includes empty pull requests. Once one developer starts to work on some issues, he is creating a new PR, prefixed with `WIP: ` and is using time tracking there as well.

After the recent update, it's not possible to open empty PR's anymore. This is the message we get:
`These branches are equal. There is no need to create a pull request.`

Via the gitea cli, it's still possible. But that's not a convenient option for most use cases.

**Comment by MirisWisdom** [comment]
Similar situation here -- it would definitely be awesome to allow the creation of empty Pull Requests.

Asides from the Gitea CLI, there is another hacky way to create an empty PR, and that is to push an empty commit:

```sh
git checkout -b branch-for-pr
git commit --allow-empty --allow-empty-message
git push --set-upstream origin branch-for-pr

# 1. create pr in gitea
# 2. to delete the empty commit:
#    git reset --hard HEAD~1 && git push --force
```

**Comment by lunny** [comment]
Yes, I think this has been resolved.
