### ISSUE TITLE
Use username instead of displayname in GetListLockHandler

### ISSUE THREAD

**Issue by pezhovski** [go-gitea/gitea#21268]
### Feature Description

When listing lfs locks from command line, response contains display name in owner field
It could happen that the same display name may be used by several users and it becomes hard to distinguish owner of the lock without finding branch and file in web ui

This plugin relies on this field to determine if user can edit file and prevent conflicts later
https://github.com/ProjectBorealis/UEGitPlugin

**Comment by KN4CK3R** [comment]
The current implementation is following the example from the Git LFS docs.
https://github.com/git-lfs/git-lfs/blob/main/docs/api/locking.md#successful-response

Would `Fullname (Username)` help?

**Comment by CrazyTushkan** [comment]
Hello @KN4CK3R it would definitely help to distinguish users with same fullname, but in case of mentioned plugin it will require to place this combination in settings instead of just fullname, which, at least for me, seems more counter-intuitive.

**Comment by KN4CK3R** [comment]
Sure, but that's how the plugin works. What solution do you propose?

**Comment by CrazyTushkan** [comment]
Why don't just use username?
