### ISSUE TITLE
403 Forbidden /repo/create

### ISSUE THREAD

**Issue by enzofoucaud** [go-gitea/gitea#21266]
### Description

Hi,
since I upgraded to version 1.17.2, my users cannot create a repo while they are owner of the organization.
_Owners have full access to all repositories and have administrator access to the organization._

`2022/09/26 13:52:18 [63319271] router: completed POST /repo/create for 172.18.0.7:47200, 403 Forbidden in 3.9ms @ repo/repo.go:198(repo.CreatePost)`

### Gitea Version

1.17.2

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

gitea@latest docker

### Database

MySQL

**Comment by enzofoucaud** [comment]
Same problem here #20841

**Comment by eeyrjmr** [comment]
It's not automatically fixed so you need to "modify " the owner permissions and apply to force a permissions update.
