### ISSUE TITLE
Unable to change Clone From URL

### ISSUE THREAD

**Issue by julzt0244** [go-gitea/gitea#21279]
### Description

After successfully mirroring a remote Gitea repository, I changed the "Clone From URL" since I've changed the ownership of the remote repo being mirrored to a different organization.

Editing the "Clone From URL" gives a success message: "The repository settings have been updated." but the mirror settings remain unchanged when refreshing the page even

### Gitea Version

 1.17.1 built with GNU Make 4.3, go1.18.5

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

Docker on Windows Host

### How are you running Gitea?

Local Gitea instance running on Docker, that is mirroring a remote Gitea instance running on Ubuntu 20.04 LTS

**Comment by zeripath** [comment]
We need more logs.

**Comment by wxiaoguang** [comment]
I have tested on try.gitea.io and a local docker 1.17.2, I can not reproduce your problem.

First, I mirror https://try.gitea.io/wxiaoguang/test, then change the Clone URL to https://try.gitea.io/wxiaoguang/test1

The screenshot shows that the Clone URL is updated correctly.

Please provide enough clues how the bug happens, feel free to re-open.

<img width="815" alt="image" src="https://user-images.githubusercontent.com/2114189/194709261-f3dedb5c-53ff-4373-b9b2-bb41f9ba67a9.png">
