### ISSUE TITLE
n8n integration

### ISSUE THREAD

**Issue by xeruf** [go-gitea/gitea#21286]
### Feature Description

[n8n](https://n8n.io) is essentially a self-hostable IFTTT/Zapier alternative

See also https://kolaente.dev/vikunja/api/issues/1249#issuecomment-36094

n8n already has integrations for [discourse](https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.discourse/), zulip, invoiceninja, zammad and many more - by tapping into its ecosystem gitea can be integrated much more easily with other open-source tools (and even non-FOSS tools) for a coherent user experience.

Even imports from Github or other forges might be realised over that in the future, so that you don't need to keep creating specific connections but use their abstraction layer.

**Comment by Mondei1** [comment]
That would actually make sense to implement. I have no idea how complicated it could be, but if you run Gitea within a more complex organization, you could implement complex automation tasks with almost no effort on Gitea's end.

**Comment by techknowlogick** [comment]
Merging into: https://github.com/go-gitea/gitea/issues/1089

**Comment by xeruf** [comment]
not sure this is solved by that, as a proper n8n integration also adds some nodes on their side I think, but I have not gotten around to using it yet

**Comment by delvh** [comment]
Well, the primary problem I can see (which probably also confused @techknowlogick) :
From your description, I have absolutely no idea what would need to be done to integrate n8n.
I've even looked at their website and documentation for about 10 minutes, and I still have no idea.
I agree that it is (partially) related to #1089, but I don't know what else it entails…

**Comment by 6543** [comment]
I did had a quic look into there youtube channel, for my understanding it is https://github.com/go-gitea/gitea/issues/1089 on our side, the rest n8n has to program on there site (mostly to by using the existing rest api)

**Comment by delvh** [comment]
Well… The `automation` part confuses me:
That looks like a `push` instead of a `poll` mechanism to me.
So, there would be some work on our side.
