### ISSUE TITLE
Case insensetive file search

### ISSUE THREAD

**Issue by Strongleong** [go-gitea/gitea#21283]
### Feature Description

Title speaks for itself.

**Comment by wxiaoguang** [comment]
Which search? Do you mean https://github.com/go-gitea/gitea/pull/21269 ?

**Comment by Strongleong** [comment]
Yes, I mean this. 
Next time when I will want to make feature request will search not only issues but PR's to :sweat_smile: 

P.S. Sorry for bad English

**Comment by wxiaoguang** [comment]
Never mind, glad to help and glad that the issue as been resolved.
