### ISSUE TITLE
Support for Chocolatey/NuGet v2 in packages

### ISSUE THREAD

**Issue by Jamie96ITS** [go-gitea/gitea#21294]
### Feature Description

I'd like to suggest an addition to the Packages feature...[Chocolatey ](https://chocolatey.org/) packages. As an API reference, this would require NuGet v2 support(I understand there are some enhancements for a full-featured Chocolatey repo but NuGet v2 is the base). Additionally, this would change up the package view page with references to chocolatey commands, e.g. `choco push` and `choco install` instead of the `dotnet` NuGet commands. I personally would try to put [choco:// links](https://community.chocolatey.org/packages/choco-protocol-support) on the page but that protocol is unofficial. 

While Chocolatey will eventually upgrade to support NuGet V3, and technically you could use Gitea's NuGet API as a repo at that point, there is no set date on that upgrade and the pages would reference `dotnet` commands. 

Thoughts?

**Comment by Jamie96ITS** [comment]
> I did not test it but can't you just use the NuGet registry as a Chocolatey registry?

Unfortunately you cannot. While you can apparently still `Push` packages to the registry if you drop the index.json from the API, use of the API on the client side to query and pull packages does not work. I believe this is because Gitea only supports v3 of the NuGet API? Chocolatey does not support that yet™️. It is a major overhaul for Chocolatey that has been in the works for some time now and may be quite a while longer to be finished. I’m on mobile now and will edit this/respond later to reference the open issue there. 

So for Chocolatey, we would need the v2 version of the NuGet API, which I understand is quite old and deprecated on the NuGet side of things. Hence it would make sense to leave NuGet alone and consider it as a Chocolatey API, especially of it were ever to include any of their “enhancements”. Though I don't think those are strictly necessary, if someone were to figure them out they don't belong with vanilla NuGet.

**Comment by KN4CK3R** [comment]
Ah, missed that they only support v2, thanks. I will have a look at the v2 api spec.

**Comment by KN4CK3R** [comment]
I have added #21393. Could you test this PR?

**Comment by Jamie96ITS** [comment]
So far so good! It works for everything I use it for. I can push, list, info, and install without complaint.
