### ISSUE TITLE
Always show Organization Owners

### ISSUE THREAD

**Issue by Schalli1987** [go-gitea/gitea#21301]
### Feature Description

When a user navigates to an organization (public or also visible for logged in only), where the user is not a member of, there are no teams shown and only members that were explicitly marked as visible (if any).
On the other hand, if the user is a member, only the own team is shown.

This prevents the user from contacting the organization owners (if not marked as visible), e.g. to request any access rights or new repositories.

Could it be possible to at least always show the organization owners?

**Comment by techknowlogick** [comment]
Those users have explicitly chosen to set their status as private, and so they don't want their account to show up.

**Comment by Schalli1987** [comment]
@techknowlogick this is not true.

For example, I'm also owner of an organization and had the same Problem. Other users could not see any members of my organization, including me, but my profile is set to public.
I had to manually set myself as visible for my organization.
But this is not the point of my request.

I want the owners team and its members to be shown for everyone, or maybe only logged in users.
As an owner, one is a person of interest, that weights higher than privacy concerns if a member is part of an organization and its owner role state.

I mean I can see the public repositories and the commit histories and the users who committed, why should I not be able to see, who is responsible?
