### ISSUE TITLE
"Team.units_map" field is an object, not an string array!

### ISSUE THREAD

**Issue by ozgurceozturkce** [go-gitea/gitea#21307]
### Description

The problem experienced due to some uncertainties and deficiencies in the documentation is as follows.

The unit_map field in the Team model defined in Gitea is shown as an string, but the response returns as an object. There is also no model related to the units_map field. Also, as an example in the documentation description, text starts with a object sign '{' and ends with a array sign ']'.

Please see refer to the definition and example of the unit_map field in Team model introduction in documentation at <a href="https://try.gitea.io/api/swagger#/organization/orgGetTeam" target="_blank">this link</a>.

### Gitea Version

1.17.2 and (for doc try.gitea.io - 1.18.0+dev-478-g08609d439)

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![resim](https://user-images.githubusercontent.com/4337205/193370719-14474166-ec74-43b7-9927-6b6131e1052d.png)

### Git Version

2.37.1

### Operating System

Windows Server 2022

### How are you running Gitea?

Gitea version 1.17.2 executable on Windows Server 2022.

### Database

MySQL

**Comment by wxiaoguang** [comment]
What do you mean?

![image](https://user-images.githubusercontent.com/2114189/194096263-f6706ef6-03a6-4a86-8a2c-ae720bd37f4c.png)

**Comment by ozgurceozturkce** [comment]
![resim](https://user-images.githubusercontent.com/4337205/194106445-dda2acc7-5f2a-41d6-a34b-5f8ccb1f87a8.png)

As seen in the screenshot I attached, the sample json text starts with an object sign but ends with a string sign. It also comes as a model object, not a plain string, and I can get it with a Dictionary<TKey, TValue> but at first I perceived it as an object according to the information here.

**Comment by wxiaoguang** [comment]
> As seen in the screenshot I attached, the sample json text starts with an object sign but ends with a string sign.

It means that the values in the object are strings.

**Comment by wxiaoguang** [comment]
Thank you for your catch and suggestion. The `unit_map : {  <*>: string }` format is generated by Swagger automatically, IIRC it's widely used already for object map? I am not sure it's possible to change it or use other formats at the moment.

The PR #21347 will fix the comment.
