### ISSUE TITLE
Change storage location of Package-Registry items

### ISSUE THREAD

**Issue by arcastro** [go-gitea/gitea#21300]
### Feature Description

Seems package registry currently stores items in `/data/gitea/packages` (is this the correct location?)

Would be great if this location could be configured to a custom one. 
This would allow storing package data in mounted filesystems.

**Comment by techknowlogick** [comment]
This is configurable, please see the storage section of config documentation.

**Comment by arcastro** [comment]
Thank you @techknowlogick , are you referring to this document?

- https://docs.gitea.io/en-us/config-cheat-sheet/#storage-storage

Seems it allows configuration of [lfs] and [attachment] individually, but the [packages] configuration does not allow specifying location of uploaded packages (for things like docker image registry, or nuget package registry, etc).

Please let me know if I misinterpreted anything. If I understood things correctly, could this issue be re-opened?
