### ISSUE TITLE
Chrome offering to translate gitea even when already in user language

### ISSUE THREAD

**Issue by pgaskin** [go-gitea/gitea#2131]
On some pages, google chrome offers to translate gitea pages, even when they are already in the user language.

To fix this, the following meta tag can be added, but set to whatever language the user chose: 

    <meta http-equiv="content-language" content="en-US"/>

![](https://user-images.githubusercontent.com/13909717/27991143-77c5f422-643b-11e7-8e34-e3fb998d6596.png)
![](https://user-images.githubusercontent.com/13909717/27991142-77c3691e-643b-11e7-9cab-29850fd583ac.png)

**Comment by pgaskin** [comment]
@lunny This is a bug, not a proposal. Chrome should not be offering to translate english to english, which is what it was trying to do. It thought gitea was in afrikaans even though it was in english.

**Comment by strk** [comment]
Would be even better to send that information via HTTP header

**Comment by lunny** [comment]
@geek1011 could you send a PR to fix that?

**Comment by warnat** [comment]
is it solved with #2272 as well and can be closed ?

**Comment by zeripath** [comment]
I think I'll close and let the OP reopen if this is still happening.
