### ISSUE TITLE
Commits pushed with deploy keys not shown in owner/member dashboard

### ISSUE THREAD

**Issue by lassebm** [go-gitea/gitea#21324]
### Description

After upgrading from 1.15.x to 1.17.2, all commits pushed by an organization using deploy keys with write access are not shown in the dashboard of owner or member users of the org/repo receiving the push. The commits are shown on the dashboard of admin users. Tried "Resynchronize pre-receive, update and post-receive hooks of all repositories." without luck.

Reproducible on 1.17.2, not reproducible on 1.15.x and 1.16.x.

Steps to reproduce:

- Spin up Gitea instance as Docker container: docker run -p "3000:3000" -p "2222:22" gitea/gitea:1.17.2
- Walk through first time setup with defaults and 'testadmin' admin user
- Create 'testuser' normal user through site admin
- Create 'testorg' organization with private visibility
- Create 'testteam' team in 'testorg'
- Add 'testuser' to 'testteam'
- Create 'testrepo' repo in 'testorg' with private visibility
- Add 'testteam' as collaborator in 'testrepo'
- Generate SSH key and add it as deploy key with write access in 'testrepo'
- Checkout 'testrepo', make commit and push to server with deploy key
- Verify commit is visible in dashboard
- Login as 'testuser' and verify commit is visible in dashboard

### Gitea Version

1.17.2

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

Docker container on Docker Engine 20.10.17.

### Database

SQLite

**Comment by lassebm** [comment]
Still reproducible on 1.18.1.

**Comment by lassebm** [comment]
Still reproducible on 1.19.2.

**Comment by wxiaoguang** [comment]
Thank you for the detailed steps and sorry for the inconvenience.

I was going to take a look at it but recently I have some high priority PRs. Hopefully some people could help to look into this problem. 🙏
