### ISSUE TITLE
Inconsistent count of repositories

### ISSUE THREAD

**Issue by harryzcy** [go-gitea/gitea#21327]
### Description

The count badges for repositories are not consistent, as shown in the screenshot

### Gitea Version

1.17.2

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

<img width="423" alt="image" src="https://user-images.githubusercontent.com/37034805/193621721-4d545e0a-e552-4af0-9828-5a920be45dba.png">

### How are you running Gitea?

Running from docker

### Database

PostgreSQL

**Comment by yardenshoham** [comment]
I managed to reproduce

![image](https://user-images.githubusercontent.com/20454870/194721201-a6f15e31-ac8e-4003-9a01-a64154174da5.png)

The "Repositories `count`" badge includes archived repositories whereas the "All `count`" does not

Query for `Repositories`: `https://gitea.com/repo/search?count_only=1&uid=37147&team_id=0&q=&page=1&mode=`

Query for `All`: `https://gitea.com/repo/search?sort=updated&order=desc&uid=37147&team_id=0&q=&page=1&limit=15&mode=&archived=false`

**Comment by harryzcy** [comment]
Thank you @yardenshoham. Then it seems that's done on purpose. I'm closing this issue.
