### ISSUE TITLE
OAuth options should be included in "Register" page

### ISSUE THREAD

**Issue by SheetJSDev** [go-gitea/gitea#21339]
### Description

Since they do not have accounts, new users are more likely to click "Register" than "Sign In".

When OAuth is enabled, the register page (e.g. https://try.gitea.io/user/sign_up ) does not indicate that you can sign in with one of the providers.  Here's a screenshot from try.gitea.io (which has GitHub sign in enabled):

<img width="1035" alt="gitea-register" src="https://user-images.githubusercontent.com/6070939/193958507-2d0ff0d2-a36b-40d6-b216-2781b29caf8a.png">

Ideally the "Sign In With" OAuth box from the "Sign In" page would *also* be included in the "Register" page.

### Gitea Version

1.17.2

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

affects try.gitea.io

**Comment by wxiaoguang** [comment]
Related this one:
* https://github.com/go-gitea/gitea/issues/19809
