### ISSUE TITLE
Authorization to third-party applications

### ISSUE THREAD

**Issue by ryanbsdeveloper** [go-gitea/gitea#21349]
### Description

Using `/login/oauth/authorize` I get the `code`. And I put it on payload.

**_These data are from tests._**
![Screenshot from 2022-10-05 14-37-04](https://user-images.githubusercontent.com/94659270/194125423-a9ac27cc-d5f5-4ef0-9ea4-5a5ec4be59c0.png)

I get the access token, as desired!
However, this token will expire and the user who authenticates to my app will not see the 'to link' button in the future. And I need permanent access!

![Screenshot from 2022-10-05 14-43-30](https://user-images.githubusercontent.com/94659270/194126456-c7751262-d32d-45de-a10e-5e410510606e.png)
**I have permanent access with the above option.**

But I can't make a redirect button like in `/login/oauth/authorize` And that way it doesn't meet expectations, I want to make it as dynamic and easy as possible.

![Screenshot from 2022-10-05 14-47-17](https://user-images.githubusercontent.com/94659270/194127026-5e5d918c-4aea-4d20-8da6-47d65ceb7f3b.png)
**Redirect button which is in my app which I mentioned.**

### Gitea Version

1.16.7

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

2.34.1

### Operating System

Ubuntu 22.04

### How are you running Gitea?

Currently on localhost

### Database

MySQL

**Comment by lafriks** [comment]
You can use refresh_token to get new access token

**Comment by techknowlogick** [comment]
As @lafriks mentioned, this is standard oauth behaviour, and the refresh_token is to be used to do exactly that.

**Comment by ryanbsdeveloper** [comment]
I need the user to click this button only once. this refresh_token option is interesting! I can save this refresh token in the database and get a new access_token every time the token expires. Would that be the idea with the refresh_token? @techknowlogick  @lafriks

**Comment by ryanbsdeveloper** [comment]
do we have any API to receive a new token with refresh_token?

**Comment by wxiaoguang** [comment]
Please refer to OAuth2 spec, google: oauth2 refresh_token
