### ISSUE TITLE
Feature suggestion #14528 (language detection override for new unknown ones) doesn't seem to be working

### ISSUE THREAD

**Issue by ell1e** [go-gitea/gitea#21377]
### Description

I just tested with Gitea 1.17.2, and the feature suggestion #14528 doesn't seem to be working even though I think the comments on the issue suggest it *should* be.

Basically, make a new repo, add some non-empty test file that ends in a new unused file extension like `.bla`, then add a `.gitattributes` line:
```
*.bla linguist-language=BlaLanguage
```
The expected result is that the lines of your `.bla` file get counted and show up as a new entry on the language bar of the repository labelled `BlaLanguage`. This is however not the case, it just seems to be ignored.

### Gitea Version

1.17.2

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

See https://try.gitea.io/blablablablab/blatest

### How are you running Gitea?

It's someone else's instance

**Comment by Drugan-qc** [comment]
Same issue on my private instance with 1.16.9

**Comment by KN4CK3R** [comment]
It works until a certain point. The language gets detected
```
BlaLang: type unknown
Python: type programming
```
and sadly filtered out some lines later
https://github.com/go-gitea/gitea/blob/94037ada247e8b27c7b456e1eeb9461cdb433d66/modules/git/repo_language_stats_nogogit.go#L187-L195
