### ISSUE TITLE
Date range in activity page is not localized

### ISSUE THREAD

**Issue by emansije** [go-gitea/gitea#21380]
### Description

The date range on the top left of the activity board is not localized. It always shows up in English, independently of the chosen interface language. It affects every version that I've tested, including the development one:

<https://try.gitea.io/emansije/teste/activity/yearly>

Testing it is just a matter of selecting any localization while on the activity page.

### Screenshots

![activity](https://user-images.githubusercontent.com/602233/194727613-7b170d1d-5948-43c5-b917-d3cb802f0985.png)

### Gitea Version

1.17.2

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

Garuda Linux

### Browser Version

Firefox 105.0.3 (64-bit)

**Comment by yardenshoham** [comment]
I'll take this
