### ISSUE TITLE
Input field for new milestone is limited to 50 chars

### ISSUE THREAD

**Issue by RokkuCode** [go-gitea/gitea#21384]
### Description

The input field for a new milestone is limited to 50.

### Screenshots

![Screenshot_20221009_053244](https://user-images.githubusercontent.com/3813927/194736597-a4126d16-9748-4774-adbe-5b93fd0df877.png)
![Screenshot_20221009_053338](https://user-images.githubusercontent.com/3813927/194736599-307e9c1e-c348-4ec5-a49f-e0f80e380641.png)

### Gitea Version

1.16.9

### Can you reproduce the bug on the Gitea demo site?

Yes

### Browser Version

Firefox 105.0.3

**Comment by RokkuCode** [comment]
i will provide a patch in a few minutes.

**Comment by wxiaoguang** [comment]
What's the real use case for putting so long content in the title? The title will be rendered somewhere where the width is small.
