### ISSUE TITLE
Access Token authentication support for pushing Gitea repo to Github  

### ISSUE THREAD

**Issue by ddddavid-he** [go-gitea/gitea#21395]
### Feature Description

Github has removed password authentication since August 13, 2021. However, the push function in Gitea still only support password authentication. 

This problem was mentioned in #19389 [https://github.com/go-gitea/gitea/issues/19389](url), but it seems to draw little attention.

Is there any plans for further support for Access Token Authentication? It is really useful in managing Github mirrors.

**Comment by zeripath** [comment]
Have you tried setting the access token as the password?

**Comment by ddddavid-he** [comment]
Someone tried in this #19389 issue but failed

https://github.com/go-gitea/gitea/issues/19389#issuecomment-1336258981

**Comment by zeripath** [comment]
Have you tried it - because as far as github says this should work.

**Comment by ddddavid-he** [comment]
It do work magically 😅. 
Thanks!
