### ISSUE TITLE
Custom path doesn't follow config argument

### ISSUE THREAD

**Issue by camlafit** [go-gitea/gitea#2140]
On master (and at least 1.1) if we start with a specific config file, custom path doesn't follow this change.

`su -l git -s /bin/bash -c "/var/opt/gitea/gitea web --config /var/opt/gitea/project/custom/conf/app.ini" `
Custom path is `/var/opt/gitea/custom` should be more logical to get `var/opt/gitea/project/custom/`

Maybe should be better to set custom path as arg and not only config file

**Comment by camlafit** [comment]
To complete we can workaround with an `export GITEA_CUSTOM=/var/opt/gitea/project/custom`

Maybe should be better to provide an 'custom_path' argument and follow specification in this directory if we want use a specific app.ini , theme, ...

**Comment by lunny** [comment]
When you specify a config file on command line, the `GITEA_CUSTOM` will not be used for config file path.

**Comment by camlafit** [comment]
I don't understand. 

Without GITEA_CUSTOM, ( `su -l git -s /bin/bash -c "/var/opt/gitea/gitea web --config /var/opt/gitea/project/custom/conf/app.ini" ` ) I get : 
> [T] Custom path: /var/opt/gitea/custom
> [T] Log path: /var/opt/gitea/project/log

With `su -l git -s /bin/bash -c "export GITEA_CUSTOM=/var/opt/gitea/project/custom/ ;  /var/opt/gitea/gitea web --config /var/opt/gitea/project/custom/conf/app.ini" `
> [T] Custom path: /var/opt/gitea/project/custom/
> [T] Log path: /var/opt/gitea/project/log

To set a specific custom path (to personalize theme for example) to only `project` looks be required to set GITEA_CUSTOM and config arg.

Should be useful to have a relative path if `--config` is set or provide/replace a new argument to set `--custom_path`.
