### ISSUE TITLE
On the file page, the repository's description, website link, topics list, and statistics bar should be gone

### ISSUE THREAD

**Issue by ell1e** [go-gitea/gitea#21406]
### Description

On the file page, the repository's description, website link, topics list, and statistics bar should be gone to make space for the actual file. For example, this is what I expect when I'm linked a license file to read **(this was edited/not how it looks like)**:

![fileviewgiteaexpected](https://user-images.githubusercontent.com/64124388/195005063-eda2ae45-e19c-4000-81fa-0cb539784252.png)

Instead, my screen is mostly filled with generic info on the repository that I expect on its main page, not when I'm trying to look at a file of which I can just see a single line of its content:

![fileviewgiteaactual](https://user-images.githubusercontent.com/64124388/195005184-dde1f2df-141a-498b-b23d-b5f22b5e6c76.png)
Oh and I forgot to mention, GitHub does this too. So it's not just some weird idea I came up with myself.

### Gitea Version

 1.17.2+75-g67c091c 

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

I'm not, I tested this on others' instances

**Comment by neel1996** [comment]
Hi, The fix for this issue has been raised as #21420 

The repo description, topics and stats are conditionally hidden when the user is in file view or blame mode
