### ISSUE TITLE
More permissive conventions for dashboard activity

### ISSUE THREAD

**Issue by a-boyev** [go-gitea/gitea#21423]
### Current status
  - Dashboard view reflects only current user activities (commits, issues, PRs)
  - Activities of other users are visible to admin only
### Proposed
  - Include following contents to the dashboard of non-admin users:
      - Activities of users, to whom the user is subscribed
      - Activities of groups, to which the user belong
      - Activitites of projects, of which the user is co-owner
   - Similar to "Activity" tab in gitlab (https://gitlab.com/groups/GROUP_NAME/-/activity)
### Motivation
  - Dashboard summary can increase team awareness of the ongoing work, which is critical in collaborative environments

Once again, thanks for making gitea, it is awesome! Please keep it up!

**Comment by lafriks** [comment]
> Similar to "Activity" tab in gitlab (https://gitlab.com/groups/GROUP_NAME/-/activity)

There is already dashboard available for each organization ex. https://gitea.server/org/ORG_NAME/dashboard

**Comment by aboev** [comment]
> > Similar to "Activity" tab in gitlab (https://gitlab.com/groups/GROUP_NAME/-/activity)
> 
> There is already dashboard available for each organization ex. https://gitea.server/org/ORG_NAME/dashboard

It is empty as well. Below is the screenshot of organization dashboard, for which the user is a member.

![Снимок экрана 2022-10-12 в 20 35 42](https://user-images.githubusercontent.com/1049460/195410900-101120e4-1860-485d-9981-a3a50e9dc4e9.png)

Just in case if I do something wrong, here are steps to reproduce:
1. Create new organization `public`, create new repository `test` in organization (under admin account)
2. Create non-admin `user_b`, add the user to organization owners
3. Make commit to repository `test` (under admin account)
4. Go to organization dashboard under `user_b`
5. The dashboard is empty, dashboard of `user_b` is empty as well

**Comment by KN4CK3R** [comment]
That works for me, my user_b sees the admin actions.

**Comment by a-boyev** [comment]
> That works for me, my user_b sees the admin actions.

Then it looks more like a bug or misconfiguration on my side. Any suggestions what to check?
