### ISSUE TITLE
Web page becomes extremely slow when create a new PR 

### ISSUE THREAD

**Issue by Bruc3Stark** [go-gitea/gitea#21422]
### Description

After creating a new pull request, the website will become extremely slow when click button like "File Changed", etc, especially in some large repos. Sometimes, logging out and logging in again or changing a browser could probably help. Is their any way to accelerate the web page? Or what configuration might help to solve problem like this? Thanks a lot.

### Screenshots

![image](https://user-images.githubusercontent.com/33786770/195323343-c5439c70-6fa5-4135-b653-e7efddeb3268.png)

### Gitea Version

1.17.2

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

Ubuntu 20

### Browser Version

Chrome 105.0.5195.125

**Comment by lunny** [comment]
Is this still a problem since now there is a files pagination?

**Comment by wxiaoguang** [comment]
I am pretty sure there could be still some slow cases:

* Slow for the backend handler code (doing "git" operations)
* Slow for the network traffic, when the diff result is large
* Slow for the browser rendering, when the result generates a lot of HTML elements
* Slow for the browser JS (the DiffTree, etc)

Each case can be reproduced separately I guess.

But for this issue, it's not clear about which case it is for.

**Comment by lunny** [comment]
I think it's a duplicated of #14734
