### ISSUE TITLE
Gitea: InternalServerError when running `gitea manager flush-queues`

### ISSUE THREAD

**Issue by tdesveaux** [go-gitea/gitea#21438]
### Description

Hi,
We're seeing the same issue as mentioned in #17204 .

As mentioned in the issue, I tried running a `gitea manager flush-queues` which did not seem to resolve the PR issue.
I ran the command a first time, but it timed out (`flush timeout with non-empty queues: mail, mail-level, notification-service, notification-service-level, push_update, push_update-level`.).

I tried running again with `--debug --timeout 20m` and it ended with a
```
2022/10/13 13:56:35 ...dules/git/command.go:151:Run() [D] /usr/bin/git version

Gitea: InternalServerError
```
The `InternalServerError` happened roughly at the 20 minutes mark so could be related to the timeout but the default one didn't timeout.

I apologize for no logs directly here but there is some information we can't disclose publicly that might be contained in them.
I have a lightly stripped debug logs (removed nothing that could matter to this here) that I can send privately if needed.

One thing I saw is this kind of errors multiple times (but not sure it's relevant, this is from a live instance):
`2022/10/13 14:16:32 ...it/repo_attribute.go:416:func2() [E] [6348019f-91] Unable to open checker for {SHA1}. Error: failed to run attr-check. Error: exit status 128`

### Gitea Version

1.17.2

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

2.37.2

### Operating System

debian

### How are you running Gitea?

Self built binary from https://github.com/dontnod/fork-gitea/tree/dontnod-prod
(for simpler look into our changes, I rebased our branch on the 1.17.2 tag and pushed here https://github.com/dontnod/fork-gitea/tree/tds/rebase/v1.17.2).

### Database

PostgreSQL

**Comment by wxiaoguang** [comment]
The queue has been completely rewritten.

And `gitea manager flush-queues` wasn't designed to resolve "Merge conflict checking is in progress" problem.

Feel free to try the latest (main: 1.20) branch.
