### ISSUE TITLE
User activity endpoint

### ISSUE THREAD

**Issue by ryanbsdeveloper** [go-gitea/gitea#21439]
### Feature Description

Well, I'm doing a project where I'm using the gitea api to get the user data for my application. I would like to know if any endpoint exists or is in development that allows us to capture all user activity, eg commit, push, pull, as well as the image above.

**_I want to bring the data to do something very similar to the one below_**
![Screenshot from 2022-10-13 10-47-29](https://user-images.githubusercontent.com/94659270/195614981-eefdf9be-0faf-47c8-9f14-bcdedc176f74.png)

**Would have this api to bring all the commits of each user?**

**Comment by zeripath** [comment]
Could you use the user feed?

e.g. https://try.gitea.io/arandomer.rss

**Comment by ryanbsdeveloper** [comment]
Good idea @zeripath, thanks. but would it be the best way to get this data?

**Comment by zeripath** [comment]
https://APP_URL/username.rss or https://APP_URL/username.atom ?

**Comment by ryanbsdeveloper** [comment]
I managed to implement @zeripath , thanks. a question, this way it only brings us the activities of the public repositories, would it be possible to get the private ones too?
