### ISSUE TITLE
draft releases: update & delete events being sent while creation dont

### ISSUE THREAD

**Issue by Mai-Lapyst** [go-gitea/gitea#21448]
### Description

Pretty much what the title says: while creation events are not being sent when creating an release marked as draft, update and deletion events are, which seems counter intuitive; it should either be all sent or non of them for draft releases.

### Gitea Version

1.17.2

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

linux

### How are you running Gitea?

Official binary release

### Database

MySQL

**Comment by delvh** [comment]
Fix has been reverted for further discussion.

**Comment by lunny** [comment]
I lost the information about why the PR has been reverted.

**Comment by wxiaoguang** [comment]
Everything in #21451

**Comment by lunny** [comment]
I think this has been resolveded by #29008
