### ISSUE TITLE
post-receive not running after commit - docker

### ISSUE THREAD

**Issue by dan-willett** [go-gitea/gitea#21455]
### Description

When I push a commit to Gitea, the post-receive script is not running

/data/git/repositories/user/repo.git/hooks/post-receive

is not being executed  ( I added logging into the script so I could tell if it is being executed ... it is not getting executed )

### Gitea Version

:latest  (1.17.2)

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

latest official docker

**Comment by wxiaoguang** [comment]
See the FAQ

https://docs.gitea.io/en-us/faq/#push-hook--webhook-arent-running

**Comment by dan-willett** [comment]
> See the FAQ
> 
> https://docs.gitea.io/en-us/faq/#push-hook--webhook-arent-running

Docker = 20.10.14
I tried: 
1 The git hooks are out of sync: run “Resynchronize pre-receive, update and post-receive hooks of all repositories” on the site admin panel

Didn't change anything

The main script:
/data/git/repositories/user/repo.git/hooks/post-receive
is not getting run

**Comment by wxiaoguang** [comment]
I have tested 1.17.2 (docker) many times, can not reproduce the git hook problem.

It will be helpful if you can provide detailed reproducible steps, starting with a simplest setup to see whether the git hooks work, then step by step to reproduce the problem.

**Comment by dan-willett** [comment]
Ok, here is my setup:

Docker Server: Flatcar Linux
Docker image: gitea/gitea:latest
I currently have two repositories in Gitea on the server
I added the following line to post.receive  ( /data/git/repositories/user/repo.git/hooks/post.receive
date > /data/gitea/log/post.receive.log
I push a commit from my workstation to Gitea over https
Gitea shows the commit ... but the post.receive script does not run ( no log file ), and yes, the file is executable, there are no error message in the Gitea log

I see a lot of entries similar to this:

2022/10/14 18:18:44 ...dules/git/command.go:153:Run() [D] [6349a804] /data/git/repositories/user/repo.git: /usr/bin/git -c protocol.version=2 -c uploadpack.allowfilter=true -c uploadpack.allowAnySHA1InWant=true -c credential.helper= -c filter.lfs.required= -c filter.lfs.smudge= -c filter.lfs.clean= rev-parse
and
2022/10/14 18:33:27 ...dules/git/command.go:153:Run() [D] [6349ab77-9] /data/git/repositories/user/repo.git: /usr/bin/git -c protocol.version=2 -c uploadpack.allowfilter=true -c uploadpack.allowAnySHA1InWant=true -c credential.helper= -c filter.lfs.required= -c filter.lfs.smudge= -c filter.lfs.clean= rev-list ab61563bbe18d881e0dd24f5e0154b63b76ca6ed..aed53376fe78ee9315d45671113dbb9e85b44f8b

**Comment by dan-willett** [comment]
logging into the container I can execute the scripts just fine

i.e. 

docker exec -it gitea.docker bash

cd /data/git/repositories/user/repo.git/hooks

ls -l
-rwxr-xr-x    1 git      git            376 Oct 14 17:05 post-receive
drwxr-xr-x    2 git      git           4096 Oct 14 17:05 post-receive.d

./post-receive

-- This executes just fine

**Comment by dan-willett** [comment]
> `Flatcar Linux`, are the files mounted as noexec?

No, doesn't matter.  What matters is how they are accessible inside of the Gitea container

FYI: https://www.flatcar.org/ - Flatcar Container Linux

The server this is on is running Flatcar on bare metal -- it is a dedicated container server.

**Comment by wxiaoguang** [comment]
I tested it in my environment, the result is expected.


```
bash-5.1# cat /data/git/repositories/org/repo.git/hooks/post-receive
#!/usr/bin/env bash
# AUTO GENERATED BY GITEA, DO NOT MODIFY
data=$(cat)
exitcodes=""
hookname=$(basename $0)
GIT_DIR=${GIT_DIR:-$(dirname $0)/..}

date >> /data/gitea/log/post.receive.log

for hook in ${GIT_DIR}/hooks/${hookname}.d/*; do
  test -x "${hook}" && test -f "${hook}" || continue
  echo "${data}" | "${hook}"
  exitcodes="${exitcodes} $?"
done

for i in ${exitcodes}; do
  [ ${i} -eq 0 ] || exit ${i}
done
```

then git clone the repo via https, then git push via https

```
bash-5.1# cat /data/gitea/log/post.receive.log
Sun Oct 16 01:46:51 CST 2022
bash-5.1#
```

**Comment by zeripath** [comment]
To debug this further these are some of the questions you need to answer and work through:

1. Is git running the hook scripts? 
2. Are the hook scripts running correctly, i.e. is pre-receive calling pre-receive.d/Gitea
3. Is that hook script running?
4. Is that hook script running the gitea hook CMD? I.e. Does it have access to the gitea command in that environment?
5. Is that call of the Gitea subcommand correctly configured ? Can it see the correct app.ini file?
6. Is that subcommand able to open a connection to the gitea server? I.e. is the internal app URL correct? Is it being permitted to open a connection as such? Is it talking to the right server?

**Comment by wxiaoguang** [comment]
Inactive for more than 2 weeks.

If you can provide a reproducible setup, feel free to re-open and provide more clues.

Or maybe you could try other Linux distro? Could it be caused by Flatcar?
