### ISSUE TITLE
Regression for width on pull request

### ISSUE THREAD

**Issue by Gusted** [go-gitea/gitea#21460]
### Description

It seems like that there is a regression since #21012, which added `fluid padded` classes, regardless of split mode being enabled. This is causing the whole UI to take up all the available width, is this something we really want? In my eyes this seems like a regression/bug, it might make sense for the diff to be full-width(we are copying Github's behavior??) but not the other elements, which is currently happening.

CC @silverwind 

### Gitea Version

https://github.com/go-gitea/gitea/commit/94d6d93cc29dd8837d87e1aa58de8f52676d4963

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

![image](https://user-images.githubusercontent.com/25481501/195947813-232b002b-78a9-4115-8227-813061d7ed7b.png)
![image](https://user-images.githubusercontent.com/25481501/195948159-55814d9e-4fe1-4822-80a9-5cb164cfb97c.png)

### How are you running Gitea?

Not relevant

### Database

SQLite

**Comment by silverwind** [comment]
Yes I think we should restore old width again. Only split diffs need more width, but I think that was already handled previously.
