### ISSUE TITLE
Repository top bar is cut off at some page widths because horizontal scrollbar appears too late

### ISSUE THREAD

**Issue by ell1e** [go-gitea/gitea#21472]
### Description

When all functionality is enabled for a repository leading to the maximum amount of tabs, the "issues"/"pull requests"/etc top bar is cut off at some page widths because horizontal scrollbar appears too late. It's still usable because no button is fully cut off, but when this first happened to me I wasn't *sure* that no button *might* be fully cut off - basically, while it's not blocking off functionality it looks like it might be, which makes this not a good experience.

### Screenshots

[Screencast from 10-16-2022 08:21:08 AM.webm](https://user-images.githubusercontent.com/64124388/196021416-62b4657b-11af-400d-8300-f4356f22f62e.webm)

### Gitea Version

1.18.0+dev-569-g288adbdea

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

Linux

### Browser Version

Firefox 106

**Comment by ell1e** [comment]
I actually managed to get a button to be cut off now, making this possibly a more pressing issue:

[Screencast from 10-16-2022 12:05:17 PM.webm](https://user-images.githubusercontent.com/64124388/196029530-cf5b9fae-cb5e-4ea2-afb2-80193cab8a55.webm)

Ideally, the horizontal scrollbar would just appear the moment something is even slightly cut off (via `overflow-x: auto` or something) rather than what currently seems to be a hardcoded page width that may or may not fit all buttons.

**Comment by wxiaoguang** [comment]
I guess I have fixed it in " Start cleaning the messy ".ui.left / .ui.right", improve label list page, fix stackable menu #24393 ", by the way.

Feel free to reopen if there is still a problem.
