### ISSUE TITLE
Gmail SMTP

### ISSUE THREAD

**Issue by C-EO** [go-gitea/gitea#21488]
### Description

Every time I set my SMTP server and test it, Gmail blocks me.
When I check the account dashboard, Gmail says that access for less secure apps is disabled and I need an OAuth client to use the SMTP.
What's the way forward?

### Gitea Version

1.17.3

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![image](https://user-images.githubusercontent.com/85847352/196204849-c9e70e32-5d42-434e-89a3-40c5dda2601a.png)

### Git Version

2.17.1

### Operating System

Replit and Ubuntu

### How are you running Gitea?

I used one of your downloads and created a script to enable Gitea to run in a Repl.

### Database

SQLite

**Comment by wxiaoguang** [comment]
SMTP is never designed to be used for 3rd auth. Google does the right thing to protect your account's security.

The SMTP auth in Gitea was just there for historical reason, it should never be used in a modern system.
