### ISSUE TITLE
Discourse github login broken

### ISSUE THREAD

**Issue by pgaskin** [go-gitea/gitea#2148]
The redirect_uri is wrong, so it will not allow github login.

**Comment by pgaskin** [comment]
@go-gitea/owners

**Comment by lunny** [comment]
https://discourse.gitea.io not http://discourse.gitea.io

**Comment by appleboy** [comment]
Set redirect 80 to 443?

**Comment by lunny** [comment]
No permission to visit host only a WebUI for us from discourse.

**Comment by pgaskin** [comment]
Maybe ask them?

**Comment by lunny** [comment]
Yeah. I have wrote message to them and now it's resolved.
