### ISSUE TITLE
Attachments not in "Allowed Types" show an invalid "Remove File" link

### ISSUE THREAD

**Issue by reviewher** [go-gitea/gitea#21491]
### Description

When uploading an attachment in an unsupported format, there is an icon for the unsupported file.  At the bottom is a link to "Remove File".  Clicking the link performs a network request to the repo `/issues/attachments/remove` endpoint and returns HTTP 400.

If the attachment is known not to be in the allowed types list, there should be no icon in the first place.  Show a message that the attachment is not supported without generating the icon.

### Screenshots

<img width="135" alt="Remove File" src="https://user-images.githubusercontent.com/24845478/196253593-c442cf8c-b993-4752-9ec4-88ad4030abc3.png">

### Gitea Version

1.17.2

### Can you reproduce the bug on the Gitea demo site?

Yes

### Browser Version

Chrome 106

**Comment by lunny** [comment]
This has been resolved. Now there will be a pop up message like below.
<img width="1032" alt="image" src="https://github.com/go-gitea/gitea/assets/81045/ab65744a-c54d-4390-8fed-07593581aa99">
