### ISSUE TITLE
"Open in Gitpod" button thumbnail doesn't render in Hacking on Gitea page

### ISSUE THREAD

**Issue by yardenshoham** [go-gitea/gitea#21492]
### Description

see https://docs.gitea.io/en-us/hacking-on-gitea/

![image](https://user-images.githubusercontent.com/20454870/196267766-d8c26e15-ca1b-45d6-b07a-269df781c052.png)

Chrome devtools:
![image](https://user-images.githubusercontent.com/20454870/196267931-988dd043-93b8-4b05-98c0-05e241e87b7c.png)

### Gitea Version

/

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

/

**Comment by techknowlogick** [comment]
good catch, thanks :) I've created https://github.com/go-gitea/gitea/pull/21494 to resolve
