### ISSUE TITLE
nil pointer deference at install (db.DefaultContext is nil)

### ISSUE THREAD

**Issue by iTrooz** [go-gitea/gitea#21502]
### Description

Steps to reproduce :
- Clone the gitea repository
- run `TAGS="bindata sqlite sqlite_unlock_notify" make build && ./gitea web`
- connect to `http://localhost:3000`

Note : I tried to follow https://docs.gitea.io/en-us/logging-configuration/#debugging-problems but I don't think changing the configuration did anything, I even still had the colors. Writing random stuff in the configuration does make gitea crash though, so I think it reads it

### Gitea Version

20a545

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://pastebin.com/7ti4Vej6

### Screenshots

![image](https://user-images.githubusercontent.com/42669835/196491789-f56621b1-3819-454e-b8ce-074033b68c29.png)

### Git Version

2.38.0

### Operating System

ArchLinux

### How are you running Gitea?

I cloned the github repository and built using `TAGS="bindata sqlite sqlite_unlock_notify" make build` and then run with `./gitea web`

**Comment by lunny** [comment]
should be fixed by #21489

**Comment by iTrooz** [comment]
I confirm it's fixed :+1: Thanks !
