### ISSUE TITLE
File editor lost view after zooming the page

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#21508]
### Screenshots

![editor](https://user-images.githubusercontent.com/76462613/196617168-8ec69631-0886-42fe-946d-25ca6a7a86e2.gif)

### Gitea Version

1.18.0+dev-592-ge27d52b27

### Can you reproduce the bug on the Gitea demo site?

Yes

### Browser Version

Firefox and Edge

**Comment by silverwind** [comment]
May need to set `automaticLayout` for monaco so it can reflow itself.
