### ISSUE TITLE
APP_DATA_PATH and GITEA_WORK_DIR are not/badly documented

### ISSUE THREAD

**Issue by mqus** [go-gitea/gitea#21523]
### Feature Description

`GITEA_WORK_DIR` is referenced multiple times in the [config cheat sheet](https://docs.gitea.io/en-us/config-cheat-sheet/) and the [example config](https://github.com/go-gitea/gitea/blob/main/custom/conf/app.example.ini), but is itself not contained at all in those resources.

`APP_DATA_PATH` is contained in the linked documentation parts, but has so little text, it is almost useless. I am missing information such as: which application data is put there? (logs, repos, database, git stuff, ssh stuff, config, ..?) If this is relative (which seems to be the default), what path is it relative to?

Also, what is the difference/relation between `GITEA_WORK_DIR` and `APP_DATA_PATH`? They seem to be pretty crucial configuration options.

**Comment by gscsnm** [comment]
I have the same problm.
CustomPath  &  AppWorkPath & AppPath
what is the difference？

run gitea in docker.
