### ISSUE TITLE
Create mirror repository from API

### ISSUE THREAD

**Issue by fauzanelka** [go-gitea/gitea#21521]
### Feature Description

I recently saw that Gitea did not provide a way to create a mirror from API, the strange thing is that you can actually update the mirror interval from the endpoint `/repos/{owner}/{repo}`.

Do you guys open PR for this implementation? Is that possible?

**Comment by jolheiser** [comment]
This is indeed possible via the [migration API](https://try.gitea.io/api/swagger#/repository/repoMigrate) by supplying `mirror: true` and/or an optional interval.
