### ISSUE TITLE
MQTT webhook

### ISSUE THREAD

**Issue by gregfr** [go-gitea/gitea#21532]
### Feature Description

I think it would be great if Gitea had the possiblity to send a webhook-like message to an MQTT server.
It would allow system with no ingress access to receive events.

**Comment by KN4CK3R** [comment]
I think that's out of scope for Gitea. You can simply create an app which receives the HTTP event and translates it to MQTT.

**Comment by gregfr** [comment]
What about adding headers to http webhooks?

**Comment by KN4CK3R** [comment]
What do both things have to do with each other?

**Comment by 6543** [comment]
closing because one is out of scope and other unrelated

**Comment by gregfr** [comment]
Definitly related, mqtt can be seen as a kind of webhook, and adding headers would allow to send requests to API services.

I've open a new "feature request" ticket.

**Comment by 6543** [comment]
@gregfr thanks ... ps can you mention the index of the new issue (link stuff if related)
