### ISSUE TITLE
Avoid page refresh when submit a form

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#21539]
### Description

btw, gogs not refresh page frequently

### Screenshots

https://user-images.githubusercontent.com/76462613/197309656-4550db42-f1f2-4256-b35f-1232268c4542.mp4

### Gitea Version

1.18.0+dev-558-g94d6d93cc

### Can you reproduce the bug on the Gitea demo site?

Yes

### Browser Version

Firefox and Edge

**Comment by wxiaoguang** [comment]
* https://github.com/go-gitea/gitea/issues/17705

**Comment by wxiaoguang** [comment]
Close as duplicate
