### ISSUE TITLE
Releases didn't display

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#2154]
see https://try.gitea.io/lunny/core/releases for examples. This repo is migrated from https://github.com/go-xorm/core. The counter is 8, but nothing listed.

**Comment by ethantkoenig** [comment]
The problem is that the count is computed using `GitRepo.NumTags()`, whereas the list of releases is computed using the database. During the migration, the repo's tags are preserved, but no corresponding releases are added to the database.

We also don't generate/delete releases when tags are added/deleted. It seems there are two options
1. Enforce a one-to-one correspondence between releases and tags, by generating/deleting releases in the database when tags are added/deleted (including tags added during a migration)
2. Don't enforce such a one-to-one correspondence, and just compute the count using the DB. This seems like the easier option.

**Comment by lafriks** [comment]
I think the first option would be needed as otherwise mirrors will be missing releases

**Comment by lunny** [comment]
As @lafriks said, I like the first option

**Comment by lunny** [comment]
If we chose option 2, we need a new tab named tags. `Tags` is different with `Releases`, user could create `Releases` on `Tags`, user also could upload files to create `Releases`.

**Comment by lafriks** [comment]
@lunny I plan to work on first option

**Comment by sapk** [comment]
@lafriks any news ?
We could stick with option 1  we list tags and releases under release. Just if we found a release matching tag we display the attachements and formatted message in place of just the short message of tag. I think github does the same (even wrap successive tags without corresponding release).

**Comment by lafriks** [comment]
@sapk I'm working on it, hope to finish on weekend

**Comment by lunny** [comment]
@lafriks option 2 maybe an easier one. When importing, we can create release for every tags and inserted to databases. And on v1.3 we can add `tags` on `Source`, so that a release could be created from a tag. It's different from Github but more clear. And also it's easy to implement public release of private repo.

**Comment by lunny** [comment]
@lafriks since release/v1.2 created, please rebase and send PR to that branch.

**Comment by sapk** [comment]
@lunny I would say keep on master and backport.

**Comment by lafriks** [comment]
I will keep it to master and then backport

**Comment by lunny** [comment]
@sapk @lafriks yes, you are right!

**Comment by sapk** [comment]
@lafriks do have open a PR even with un-finished work but that we can pre-review ? Can we do anything to help you ?

**Comment by lafriks** [comment]
@sapk I will submit PR later today

**Comment by lcges** [comment]
Hi.
How does the issue look? The last on the list :)

**Comment by lunny** [comment]
@qdbdbp also #2370 which will be back ported to v1.2. I will release v1.2.0-rc1 at first at #2388 merged.

**Comment by lunny** [comment]
This isn't fixed yet.

**Comment by lafriks** [comment]
Yes only point 2 is implemented

**Comment by lunny** [comment]
@lafriks, So next, we only need copy tags to releases when migrating and add a button on tags to create a release.

**Comment by lafriks** [comment]
Not only but I'm working on that. Anyway I think it should not be 1.2.0 blocker. This can be later backported to 1.2.1

**Comment by bkcsoft** [comment]
@lunny is the counter still 8? or is it 0?

**Comment by lafriks** [comment]
@bkcsoft now counter is 0

**Comment by bkcsoft** [comment]
If so the bug would be fixed in my opinion. Gitea only imports the git repo, and Releases are metadata outside the repo.

**Comment by lunny** [comment]
~But how to create releases?~ Then we need a tags list on release create page?

**Comment by bkcsoft** [comment]
@lunny Yes, that would be the expected behaviour IMO

**Comment by strk** [comment]
Possibly related: #3247
