### ISSUE TITLE
RSS feed GUIDs are not unique enough

### ISSUE THREAD

**Issue by cthu1hoo** [go-gitea/gitea#21542]
### Description

Running Gitea 1.17.2, RSS feed entries have a GUID which is an integer, i.e.

```
<item>
....
<guid>8669</guid>
<pubDate>Sat, 15 Oct 2022 13:46:05 +0300</pubDate>
</item>
```

Article GUID is supposed to [globally identify](https://www.w3schools.com/xml/rss_tag_guid.asp) it between any amount of other RSS feeds. An integer value is not good enough here and may easily clash with other entries. Something like a tag: URI or a simple permalink would work a lot better. 

Even removing this field entirely would be better than current behavior. Please consider fixing this, thanks!

### Gitea Version

1.17.2

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

Running stock docker container.

### Database

PostgreSQL

**Comment by yardenshoham** [comment]
What do you think about the format `integer-link` for guid? Say someone comments and the activity link is `https://3000-yardenshoham-gitea-3pzuhkduf6t.ws-eu72.gitpod.io/abc/defg/issues/1#issuecomment-5` then it would be something like 
```xml
<guid>
8-https://3000-yardenshoham-gitea-3pzuhkduf6t.ws-eu72.gitpod.io/abc/defg/issues/1#issuecomment-5
<guid/>
```

**Comment by cthu1hoo** [comment]
Anything would work, as long as it is reasonably unique. I'm not aware of any other requirements for article GUIDs. 

There's a link element already which supposedly goes somewhere unique for each article (I haven't checked, just assuming) so you could just use it once more inside `<guid isPermaLink="true">....</guid>`. 

But really, anything unique would be good enough.

**Comment by yardenshoham** [comment]
I'm on it
