### ISSUE TITLE
New feature suggest: config can be reloaded by web, or changed  by web.

### ISSUE THREAD

**Issue by anotherGoogleFan** [go-gitea/gitea#2155]
It's my first time to use gitea.
I set config by web and when I want to change some setting, I cannot do it by web and must connect to server to do some change. This is very inconvenient. Why cannot I change it by web?
And, when I changed the config file, I have to restart gitea to let the change work. This is very inconvenient too. Can we just add a button in web such as a "reload config" button?

**Comment by kolaente** [comment]
This relates to #1714 and as stated there, there are some things which need a restart of gitea, so you need to edit it outside of gitea.

**Comment by bkcsoft** [comment]
I guess I've stated/asked it before but I'll do so again. What would happen if your config is broken when you press "reload config"?
