### ISSUE TITLE
web 500 error  database is locked

### ISSUE THREAD

**Issue by wangwj** [go-gitea/gitea#21571]
### Description

2022/10/24 05:03:40 ...ers/web/repo/view.go:705:checkHomeCodeViewable() [E] [63561cab] ReadBy: database is locked
2022/10/24 05:03:40 ...s/context/context.go:219:HTML() [D] [63561cab] Template: status/500

<img width="1414" alt="image" src="https://user-images.githubusercontent.com/4464162/197452099-c775629d-304d-4dcf-bf76-c67f933f46e8.png">

### Gitea Version

1.17.3

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

i use  docker  run gitea
docker run -d \
--restart=always \
--privileged \
--name gitea \
-v /gitea:/data -p 9000:3000 -m 500m \
gitea/gitea:1.17.3

### Database

SQLite

**Comment by KN4CK3R** [comment]
There must be another process which interacts with your database file. Check that, should not be a Gitea error.

**Comment by wangwj** [comment]
i not found other process database ,  show i use lsof result:
<img width="969" alt="image" src="https://user-images.githubusercontent.com/4464162/197657075-aaea16a2-97fd-4b51-82ce-99e05399f076.png">
<img width="904" alt="image" src="https://user-images.githubusercontent.com/4464162/197657105-0ce93366-01c4-4d08-881d-aa9de4a1d897.png">
<img width="973" alt="image" src="https://user-images.githubusercontent.com/4464162/197657172-ccdfdc11-f81c-4bc9-82cd-d823bfc1f7e2.png">
@KN4CK3R

**Comment by wxiaoguang** [comment]
> i found err reason: i use cifs mount file system ,default file lock ,need modify default mount param

Yup, it's filesystem related.
