### ISSUE TITLE
Please use SET GLOBAL host_cache_size=0 instead

### ISSUE THREAD

**Issue by ghnp5** [go-gitea/gitea#21576]
### Description

I use Docker Gitea, with a MySQL 8 instance next to it.

When looking at the logs of the MySQL instance, on restart I see this:

> 2022-10-24T10:19:24.316236Z 0 [Warning] [MY-011068] [Server] The syntax '--skip-host-cache' is deprecated and will be removed in a future release. Please use SET GLOBAL host_cache_size=0 instead.

I don't maintain the `my.cnf` file, so I assume it is Gitea that is putting this `--skip-host-cache` variable in.

### Gitea Version

1.17.3

### How are you running Gitea?

Docker with RUN_MODE=prod

### Database

MySQL

**Comment by KN4CK3R** [comment]
Gitea does not maintain the MySql configuration. Please contact the MySql maintainers about their Docker image.
