### ISSUE TITLE
Repository images cannot be displayed

### ISSUE THREAD

**Issue by wch66** [go-gitea/gitea#21587]
### Description

![image](https://user-images.githubusercontent.com/36251958/197669233-0c53adc5-5dec-4539-a44b-820a31008df5.png)

### Gitea Version

gitea-1.17.3-gogit-windows-4.0-amd64

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

windows server 2012R2

**Comment by techknowlogick** [comment]
Do you have gravatar enabled, and are you on a network that blocks gravatar?

**Comment by wch66** [comment]
> Do you have gravatar enabled, and are you on a network that blocks gravatar?

Can I show the profile picture of the repository creator? I set DISABLE_GRAVATAR = true, which shows the default gitea avatar

**Comment by wch66** [comment]
When I create a file, the avatar here is also not displayed 
![image](https://user-images.githubusercontent.com/36251958/197671260-c20faf61-762c-4fe6-9e3f-8ea613ed7a24.png)

**Comment by lunny** [comment]
Could you try to visit the link of the avatar in web browser directly?

**Comment by wch66** [comment]
Yes, direct access is no problem, I found that when the code is pushed, the avatar does not display, I reconfigured the avatar path, and opened the DISABLE_GRAVATAR

**Comment by lunny** [comment]
Don't know whether your problem has been resolved but we have no more similar reports.
