### ISSUE TITLE
Issue images can not be deleted

### ISSUE THREAD

**Issue by zjjhot** [go-gitea/gitea#21588]
### Description

clicking the Delete button does not respond, and the picture is not actually deleted.

![OP9ZQ3T3DO1F8YCNM`T 9WF](https://user-images.githubusercontent.com/79889452/197679277-b7ac184d-56db-42a5-890b-c8f86ee379a2.png)

![YXOZ4GHTX97%VW@}HPS_O`L](https://user-images.githubusercontent.com/79889452/197679244-f75a7e3c-089c-4f16-a3c3-c41e09631b12.png)

### Gitea Version

1.18.0~dev-865-g0c1b151c1

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

windows gitea.exe

**Comment by wxiaoguang** [comment]
Maybe I have fixed it in 
* https://github.com/go-gitea/gitea/pull/20147#issuecomment-1168151327
*  the removal seems not working for edit on existing comment

But it's discarded.

**Comment by eeyrjmr** [comment]
This appears to be working now or the triggers are more subtle  

https://gitea.io/  Version: 1.19.0+dev-159-g46485848f

![2022-12-04_11-12-1670155012](https://user-images.githubusercontent.com/4564448/205489041-3641d0f6-1113-4f2c-8385-f4595cec7404.jpg)

**Comment by zjjhot** [comment]
> Maybe I have fixed it in
> 
> * [Add thumbnail to dropzone when pasting images in to comments #20147 (comment)](https://github.com/go-gitea/gitea/pull/20147#issuecomment-1168151327)
> * the removal seems not working for edit on existing comment
> 
> But it's discarded (the new one for replacing is much more complex and I'm afraid it will be too difficult to maintain, and I haven't got time to test or optimize it)

That's OK.
