### ISSUE TITLE
As a windows service, Gitea will write in System32 for its session files

### ISSUE THREAD

**Issue by dubeg** [go-gitea/gitea#2159]
- Gitea version: 1.1.2
- Git version: 2.13.0
- Operating system:
- Database:
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
- I have a Windows Service running Gitea under _UserX_.
- It seems Windows services are started in the same directory as the Service Manager, which is `System32`.
- _UserX_ is a normal user (unprivileged), except that he has Full Control over `C:\gitea`.
- _UserX_ has in its env. variables, `GITEA_WORK_DIR=c:/gitea`.
- When running the service and navigating to Gitea's home URL, Gitea will return HTTP 500.
- There's no useful info about what's happening in the log file.
- With procmon, if I look at what's happening for Gitea.exe, I see that it's trying to write in `C:\Windows\System32\data\sessions`.

__gitea.log__
![logfile](https://user-images.githubusercontent.com/6020602/28184893-22f60e18-67e3-11e7-8ffd-c5dd6a0b4886.PNG)

__Procmon__
![logs](https://user-images.githubusercontent.com/6020602/28184891-211363fc-67e3-11e7-8757-5df159e512be.PNG)

## Notes
I've checked the source code, it doesn't seem like GITEA_WORK_DIR is affecting the session setting `PROVIDER_CONFIG` if it's not explicitly set in `app.ini`. This may be explain why it is trying to write in `C:\Windows\System32`?

**Comment by lafriks** [comment]
Fixed by #2192
