### ISSUE TITLE
error: Use Nginx to serve Gitea instance

### ISSUE THREAD

**Issue by dakango** [go-gitea/gitea#21613]
### Description

![image](https://user-images.githubusercontent.com/23118182/198168765-7bcca1bd-cac8-4ee5-b53d-f9fcd78343ca.png)

error: Use Nginx to serve Gitea instance

I have checked configuration file( app.ini ), ROOT_URL is correct.

nginx config:
```
server {
    server_name xxx.com;

    listen 80;
    listen [::]:80;

    location / {
        proxy_pass http://localhost:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
```

### Gitea Version

1.17.3

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

2.30.2

### Operating System

Alibaba cloud linux

### How are you running Gitea?

Gitea was downloaded from the website(https://dl.gitea.io/gitea/1.17.3)

run command: `nhup ./gitea web &`

### Database

SQLite

**Comment by techknowlogick** [comment]
What happens when you access that linked file directly?

**Comment by outer199** [comment]
> What happens when you access that linked file directly?

access by `IP:3000` directly is fine. but access by domain  nginx `server_name` configuration(xxx.com) is wrong.

**Comment by outer199** [comment]
> What happens when you access that linked file directly?

access http://xxx.com/asserts/js/index.js?v=1.17.3 directly is fine

**Comment by zhenzi0322** [comment]
> > What happens when you access that linked file directly?
> 
> access http://xxx.com/asserts/js/index.js?v=1.17.3 directly is fine

403 Forbidden appears
