### ISSUE TITLE
404 when creating pull request directly on organization repository

### ISSUE THREAD

**Issue by Weyzu** [go-gitea/gitea#2162]
- Gitea version (or commit ref): 6a3c03762a37f593ec8101c2005836ca44683e1d
- Git version: 2.13.1
- Operating system: Arch Linux
- Database:
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist: N/A

Site throws 404 for certain branches after an attempt to display a compare page within a repo. A repo of which you're not the owner but have the right to create pull requests. Steps to reproduce the error:

1. Create an organization with some repo to which you have write access.
2. Create a branch directly in the repository (not by fork) and make some changes.
3. Push the changes remote, so that it's available on gitea.
4. Click compare branches below the repo description to open the compare page.

After the 4th step, a 404 should be thrown. What frontend tries to do is to assume that we would always merge from a fork, not directly on the repo, so it provides wrong upstream path, e.g.
```
organization:master..username:branch
```
instead of just
```
organization:master..branch
```
What it should do is to check whether the currently viewed repo is a fork. If it is, pass the first option. If not, pass the second one.

I will drop a fix for that in a matter of minutes. ✌

**Comment by lunny** [comment]
resolved by #2163
