### ISSUE TITLE
SSH times out after three connection

### ISSUE THREAD

**Issue by Rincewind34** [go-gitea/gitea#21628]
### Description

After three established connections, the SSH connection time out before every new attempt. Reproducible with calling `ssh -T git@bbbbb.dyndns.org` three times and the fourth time will time out.

This is especially problematic when doing operations with `git submodule foreach` as after the fourth module will time out.

I tried disable SSH_PER_WRITE_TIMEOUT and SSH_PER_WRITE_PER_KB_TIMEOUT but the issue persists. 

### Gitea Version

1.17.3

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

With docker. The SSH connection does not pass the daemon on the root server, port 22 is directly forwarded into the container in the compose file: `0.0.0.0:22:22`. Also connecting over ssh to the root server does not show the same problem.

### Database

MySQL

**Comment by wxiaoguang** [comment]
1. Please try to ssh without the `dyndns` first.
2. If you are using OpenSSH:

https://stackoverflow.com/questions/31114690/difference-between-maxstartups-and-maxsessions-in-sshd-config

**Comment by Rincewind34** [comment]
`ssh -T git@77.1.9.5` creates the same issue. As I wrote above, connecting the SSH Daemon on the root server does not have this issue. 

Concerning if I'm using OpenSSH: I don't exactly know how GitEA is set up. I don't even know how I could change these settings in my GitEA installation.

My volume `/data/gitea_data/ssh/` only contains some RSA keys and in `/data/gitea_data/gitea/` I couldn't find anything that looks like a file I can edit aside from `conf/app.ini`. Also reading through the article, neither setting seems like it has something to do with my problem. I don't open any concurrent connections.

**Comment by ostylk** [comment]
I am having the same issue. Is there any info I can provide to help fix this issue?

**Comment by wxiaoguang** [comment]
If you can do `ssh` or `git clone` with Gitea's host in an internal network without timeout, then the timeout is caused by the external network or ISP, Gitea can't control that.

If the `ssh` or `git clone`  in an internal network also time, then it needs enough clues (your environment, logs, etc) to see what's the problem.
