### ISSUE TITLE
Cannot create mirror repository: sql syntax error

### ISSUE THREAD

**Issue by stephens2424** [go-gitea/gitea#21635]
### Description

I'm getting an error when I try to create a new migration repository (a mirror). The key error I see in the logs when I do it is:

```  ...ervices/task/task.go:56:handle() [E] Run task failed: pq: syntax error at or near "ON"```

The web UI still says "migrating git data" just before it switches to an error message.

### Gitea Version

1.17.3

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/stephens2424/b09a35df5ea748543ce629b76e59b06c

### Git Version

2.25.1

### Operating System

Ubuntu 20.04

### How are you running Gitea?

Using binary release with systemd, hosted on a digitalocean instance.

### Database

PostgreSQL

**Comment by wxiaoguang** [comment]
Your PgSQL version might be very old. Please use PgSQL >= 10 .

**Comment by wxiaoguang** [comment]
Maybe related to
* https://github.com/go-gitea/gitea/issues/19927#issuecomment-1151411574

**Comment by stephens2424** [comment]
You're right. I forgot that postgres runs multiple versions under the hood, I was only looking at the primary installed version (i.e. what apt shows as installed) at first, but that's misleading! The gitea database can be in a postgres "cluster" that's on an earlier version than that still.

Sorry for the noise, thanks for the help!
