### ISSUE TITLE
Bulk migrate of repositories

### ISSUE THREAD

**Issue by andreas-bulling** [go-gitea/gitea#21631]
### Feature Description

Hi,

The migrate functionality (in my case from GitLab to Gitea) works great but has a huge bottleneck: Each repository has to be migrated individually/separately.

It would save a lot of time and thus be fantastic if in the migrate dialog one could enter a group URL instead and the migrate screen would then show a list of available repositories in that groups together with a checkbox to select/deselect a particular repository for migration. Migration settings (what to import, whether mirror, LFS objects etc) could still be set like now globally for all repositories.

In a future version of this the script could directly check which repositories are already available in the target organization and grey those out.

**Comment by lunny** [comment]
duplicated with #2569
