### ISSUE TITLE
Gitea fails to start after rerunning docker-compose

### ISSUE THREAD

**Issue by terrifictable** [go-gitea/gitea#21634]
### Description

Gitea fails to start after stopping and rerunning docker-compose container (`docker-compose stop` and `docker-compose up`)
It just pings the mysql database gives a io timeout error and continues pinging database (which works fine) 

### Gitea Version

1.17.3

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/TerrificTable/854de511e3e6b304a45b8609efb7db30

### Git Version

2.24.1.windows.2

### Operating System

Windows 10

### How are you running Gitea?

I'm running Gitea using docker-compose on my Windows 10 maschine

### Database

MySQL

**Comment by TerrificTable** [comment]
fixed after seeing my misstake: ```
GITEA__database__HOST=db:3306
``` `db` does not exist tho since i renamed it to `database`
