### ISSUE TITLE
gitea version not easy to understand on web page

### ISSUE THREAD

**Issue by anotherGoogleFan** [go-gitea/gitea#2164]
I download gitea binary from https://dl.gitea.io/gitea/master/gitea-master-linux-amd64。
I run command ./gitea web and the version shows © Gitea 当前版本: dd758ad
For users it's hard to understand dd758ad.
So can we change it, for example, 1.2:dd758ad, so I can clearly know its version is 1.2.

**Comment by sapk** [comment]
If you run builds from tag like https://dl.gitea.io/gitea/1.1.2/ you should have the version displayed like `Version: 1.1.2`
