### ISSUE TITLE
Gitea fails to handle webhooks when an emoji is present in the commit name/description

### ISSUE THREAD

**Issue by HeySora** [go-gitea/gitea#21644]
### Description

Putting an emoji in a commit (either title or description) makes things go out of sync.

The personal homepage as well a person's "Public Activity" page on their profile won't ever show the push, even after running health checks, restarting the machine, or syncing git hooks.  
The commit list on the impacted Git repository is still up-to-date, though.

The repository which exhibited that issue only has a single Discord webhook link.

Shortest possible reproduction:

```bash
git commit --allow-empty -m "test 😅"
```

Relevant `gitea.log` portion:
```
2022/10/31 15:01:26 ...n/webhook/webhook.go:631:NotifyPushCommits() [E] [635fe346-11] PrepareWebhooks: CreateHookTask: Error 1366: Incorrect string value: '\xF0\x9F\x98\x85 -...' for column `gitea`.`hook_task`.`payload_content` at row 1
2022/10/31 15:01:26 ...ion/action/action.go:335:NotifyPushCommits() [E] notifyWatchers: insert new actioner: Error 1366: Incorrect string value: '\xF0\x9F\x98\x85\n...' for column `gitea`.`action`.`content` at row 1
```

### Gitea Version

1.18.0+rc0

### Git Version

2.30.2

### Operating System

Debian 11, Linux 5.10

### How are you running Gitea?

The issue happens both on [a prebuilt 1.18.0-rc0 binary](https://github.com/go-gitea/gitea/releases/tag/v1.18.0-rc0), or when building with `TAGS="bindata" make build`

Gitea is being run [using systemd (ver. 247)](https://docs.gitea.io/en-us/linux-service/).

### Database

MySQL

**Comment by KN4CK3R** [comment]
That's a problem with your setup. https://docs.gitea.io/en-us/faq/#why-are-emoji-broken-on-mysql
