### ISSUE TITLE
START_SSH_SERVER = true works only in rootless images

### ISSUE THREAD

**Issue by neszt** [go-gitea/gitea#21645]
### Description

Decided to switch to gitea builtin ssh server, so i changed config:
```
[server]
START_SSH_SERVER = true
```
But it seems that this config works only in rootless images (1.17.3-rootless in my case). With version 1.17.3, a separate ssh server is always started.

### Gitea Version

1.17.3

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

Debian 11.4

### How are you running Gitea?

With Docker compose.

```bash
# cat docker-compose.yml
version: "3.3"
services:
  server:
    restart: always
    image: gitea/gitea:${GITEA_VERSION}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
      - ${DATA}:/data
    ports:
      - "${HTTP_PORT}:3000"
      - "${SSH_PORT}:22"
```
```bash
# cat .env
GITEA_VERSION=1.17.3
HTTP_PORT=3000
SSH_PORT=2222
DATA=./data
```

**Comment by zeripath** [comment]
This is by design - although we could do the work to make the root docker start the openssh server as needed it's in a lot of ways unnecessary.

If you do not need to run openssh concurrently with the gitea server and are happy with using the builtin ssh server (or no ssh server) you should use the rootless docker build.

**Comment by neszt** [comment]
Thank you for your quick answer!

> This is by design - although we could do the work to make the root docker start the openssh server as needed it's in a lot of ways unnecessary.

I think this would be worth mentioning in the documentation.

> If you do not need to run openssh concurrently with the gitea server and are happy with using the builtin ssh server (or no ssh server) you should use the rootless docker build.

I tried, but: https://github.com/go-gitea/gitea/issues/21647

**Comment by wxiaoguang** [comment]
#21647 has been resolved.
