### ISSUE TITLE
gitea ignoring  config init.templateDir

### ISSUE THREAD

**Issue by Shakthijuego** [go-gitea/gitea#21643]
### Description

We have used git config `init.templateDir` to set up default hooks for gitea in the older versions (Unfortunately cannot recall the exact version - mostly gitea-1.15.x).
  The hooks specified in this folder  are used to automatically merge with .git/hooks/pre-receive.d/ 
Now it's not working. 
Please let me know if you have alternatives. 

### Gitea Version

gitea-1.17.3

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

2.34.1

### Operating System

ubuntu

### How are you running Gitea?

Running from systemd 

### Database

SQLite

**Comment by wxiaoguang** [comment]
https://blog.gitea.io/2022/07/gitea-1.17.0-is-released/#-internal-gitconfig-19732httpsgithubcomgo-giteagiteapull19732

❗ Internal Gitconfig ([#19732](https://github.com/go-gitea/gitea/pull/19732))

**Comment by Shakthijuego** [comment]
Got it. Thanks
