### ISSUE TITLE
Docker installation failing when using `INTERNAL_TOKEN_URI`

### ISSUE THREAD

**Issue by whois-marvin-42** [go-gitea/gitea#21666]
### Description

Docker install process generates an `INTERNAL_TOKEN` while variable `INTERNAL_TOKEN_URI` was set in `docker-compose.yml` ... which leaves us with an `app.ini` having both of them set ... terminating the container due to an invalid configuration ... and raising an error accordingly :

`(...) Cannot specify both INTERNAL_TOKEN_URI and INTERNAL_TOKEN`

### Gitea Version

1.18.0-rc0

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.githubusercontent.com/whois-marvin-42/7409ea57866a18b9695357457d02e221/raw/902e430a07f69e5d13a94897a802ae2ffa89004a/gistfile1.txt

### How are you running Gitea?

Using a pretty straightforward `docker-compose.yml` with your latest docker (`rootless`) image.
Trying to use Docker `secrets` feature when needed/possible for sensitive data = setting required variables (aka `INTERNAL_TOKEN_URI` being one of those) according to your [documentation](https://docs.gitea.io/en-us/config-cheat-sheet/#security-security)

### Database

SQLite

**Comment by wxiaoguang** [comment]
Caused by https://github.com/go-gitea/gitea/pull/19663

The `install.go` should not generate new token if the token  file exists.

**Comment by wxiaoguang** [comment]
The fix: #21669

Workaround:
* Remove the `INTERNAL_TOKEN` after installation.
* Or, prepare the whole app.ini with `INSTALL_LOCK=true` and skip the installation page.

**Comment by whois-marvin-42** [comment]
Hi. Thanks for your answer. Since I was testing your RC, I filled the issue hoping a fix could be part of the next milestone (or at least update / make a note on the documentation) making it easier for those who are using `secrets`. Now generating the configuration from our own template/process. Thanks again for this great product  :bowing_man:
