### ISSUE TITLE
Can't enable option "This account has permissions to import local repositories"

### ISSUE THREAD

**Issue by FranAguiar** [go-gitea/gitea#2166]
- Gitea version (or commit ref): 6a3c037
- Git version: 2.7.4
- Operating system: ubuntu 16:04
- Database (use `[x]`):
  - [x] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No (admin account required)
  - [ ] Not relevant

## Description

As an admin editing an user account, when mark the option "This account has permissions to import local repositories", update the account but the option didn't saved.

## Screenshots

![image](https://user-images.githubusercontent.com/18166018/28207357-542c891e-6881-11e7-8479-33c709af346f.png)

Edit: In DB is updated correctly, probably is a front-end issue

**Comment by lafriks** [comment]
To allow import local repositories (repositories stored on gitea server disk) you need to enable setting in app.ini file

**Comment by kwoot** [comment]
This will probably help the next one a great deal: https://github.com/go-gitea/gitea/blob/master/custom/conf/app.ini.sample 

; True when users are allowed to import local server paths
IMPORT_LOCAL_PATHS = false
