### ISSUE TITLE
Anchors break after clicked once

### ISSUE THREAD

**Issue by ell1e** [go-gitea/gitea#21680]
### Description

I noticed something which makes navigating documentation on gitea quite irritating: anchors break after clicked once. An anchor on every other page I've ever visited can be clicked multiple times in a row with scrolling in between, and every subsequent click will re-center the view to the anchor. Not when viewing a markdown file on Gitea however, only the **first** click works and then it just won't recenter anymore.

Try here by clicking the "Test anchor", then scrolling away with it still in view, then click it again (which should recenter the view once more and undo the scroll, but it doesn't): https://try.gitea.io/blablablablab/BlaTest/src/branch/main/README.md

### Gitea Version

1.19.0+dev-39-g2900dc90a

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

[Screencast from 11-04-2022 12:52:41 PM.webm](https://user-images.githubusercontent.com/64124388/199966708-be47c4aa-f464-4906-9cc2-9c781574d60f.webm)

### How are you running Gitea?

I'm not, but this reproduces on all instances run by others that i have tested

**Comment by silverwind** [comment]
Might be some JS interference, I'm not sure.

**Comment by apachejuice** [comment]
This happens on the central gitea instance for me (https://gitea.com) but interestingly not my own at https://git.apachejuice.dev (for example in [this page](https://git.apachejuice.dev/apachejuice/uwuno/src/branch/main/backend) the anchors seem to work fine. 
Specs of my gitea server:
![grafik](https://user-images.githubusercontent.com/88475516/199997965-be78d289-1b9d-47f1-84ce-f6e6822bcd9a.png)

**Comment by silverwind** [comment]
I can reproduce on your instance as well:

- Click anchor, page scrolls
- Change scroll offset
- Click same anchone again, page no longer scrolls

**Comment by apachejuice** [comment]
I did the exact same, although after reloading the page it appears too
