### ISSUE TITLE
Empty repositories Always Show Quick-Start Guide after PUSH 

### ISSUE THREAD

**Issue by mariuszmaximus** [go-gitea/gitea#21688]
### Gitea Version

1.18.0+rc0

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

The problem is still not solved!

https://github.com/go-gitea/gitea/issues/2898
https://github.com/go-gitea/gitea/issues/2665

Is there any solution?
Install GITLAB? 

### Database

SQLite

**Comment by techknowlogick** [comment]
Hi @mariuszmaximus, this is likely due to git hooks not firing. This can be caused by many reasons, some are documented here: https://docs.gitea.io/en-us/faq/#push-hook--webhook-arent-running

**Comment by mariuszmaximus** [comment]
You have right !  Thank you for the link !
I check my server and docker version 
I have ubuntu 19.xx and very old docker 

After update Ubuntu to 22.04  all works, many other issues have also been fixed

**Comment by techknowlogick** [comment]
Glad to hear :)
