### ISSUE TITLE
Incorrect latest commit message in UI when viewing tag

### ISSUE THREAD

**Issue by silverwind** [go-gitea/gitea#21687]
### Description

The latest commit is incorrectly rendered when viewing a tag, the first line (commit title) is absent. It's okay when viewing a branch.

Not OK (tag view) https://try.gitea.io/silverwind/remap-css/src/tag/5.0.4:

<img width="667" alt="image" src="https://user-images.githubusercontent.com/115237/200040454-56484d16-385f-414c-8d70-9340969d6b9d.png">

OK (branch view) https://try.gitea.io/silverwind/remap-css/src/branch/master:

<img width="370" alt="image" src="https://user-images.githubusercontent.com/115237/200040423-a84c83c2-8ca7-4b3d-a0c4-c8516f37dafd.png">

### Gitea Version

1.19

### Can you reproduce the bug on the Gitea demo site?

Yes

**Comment by KN4CK3R** [comment]
Added a patch in #21693.
