### ISSUE TITLE
login page misses all text

### ISSUE THREAD

**Issue by netcicd** [go-gitea/gitea#21682]
### Description

https://:<gitea>:3000/user/login?redirect_to=%2f does not contain any text

### Screenshots

![image](https://user-images.githubusercontent.com/46484069/200020039-d7882ae4-cd88-4fb9-b7fc-ad12cb39c835.png)

### Gitea Version

1.18.0+rc0

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

Docker

### Browser Version

both chrome and firefox

**Comment by silverwind** [comment]
Which OS? In case this is Linux, check browser/os font configuration.

**Comment by netcicd** [comment]
Ubuntu. But if I login knowing what should be there the page looks normal and has text

Verstuurd vanaf mijn iPhone.

**Comment by techknowlogick** [comment]
To confirm: Only the login form is missing its text, as the other pages have their text showing? It might be missing translations, to rule this out you could "view source" to see if the text is being sent, but then not being rendered.

**Comment by netcicd** [comment]
When logging in for the first time. You then get the password reset page which does show text

Verstuurd vanaf mijn iPhone.

**Comment by netcicd** [comment]
When I do an Inspect source, there is no test in the button or on the labels: 
'''
<div class="ui attached segment">
			<form class="ui form" action="/user/login" method="post">
			<input type="hidden" name="_csrf" value="pZaSqZkO2Hr414nlWJvz-Ju9Igc6MTY2NzU5NDA4MzE3NzkyMTQwMw">
			<div class="required inline field ">
				<label for="user_name"></label>
				<input id="user_name" type="text" name="user_name" value="" autofocus="" required="">
			</div>
			
			<div class="required inline field ">
				<label for="password"></label>
				<input id="password" name="password" type="password" value="" autocomplete="current-password" required="">
			</div>
			
			
			<div class="inline field">
				<label></label>
				<div class="ui checkbox">
					
					<input name="remember" type="checkbox" tabindex="0" class="hidden"><label></label>
				</div>
			</div>
			

			<div class="inline field">
				<label></label>
				<button class="ui green button">
					
						
					
				</button>
				<a href="/user/forgot_password"></a>
			</div>

			

			
			<div class="ui attached segment">
				<div class="oauth2 center">
					<div id="oauth2-login-loader" class="ui disabled centered loader"></div>
					<div>
						<div id="oauth2-login-navigator">
							<p></p>
							
								
								<a href="/user/oauth2/keycloak">
									<img alt="OpenID Connect (keycloak)" title="OpenID Connect (keycloak)" class="openidConnect oauth-login-image" src="/assets/img/auth/openid_connect.svg"></a>
							
						</div>
					</div>
				</div>
			</div>'''

**Comment by silverwind** [comment]
No text at all in the HTML seems very odd. I thought the could should fall back to either english or a placeholder translation token. Are you maybe overwriting the translation files using a custom config directory?

**Comment by netcicd** [comment]
Not that I am aware of. I now switched from :latest to :1 and the problem is gone.

Verstuurd vanaf mijn iPhone.

**Comment by techknowlogick** [comment]
I'll close this then. Thanks for the report and follow up information.
