### ISSUE TITLE
please make sure the asset files can be accessed and the ROOT_URL setting in app.ini is correct.

### ISSUE THREAD

**Issue by zhenzi0322** [go-gitea/gitea#21691]
### Description

Failed to load asset files from http://xxx.xxx.cn/assets/js/index.js?v=1.17.3, please make sure the asset files can be accessed and the ROOT_URL setting in app.ini is correct.

### Gitea Version

1.17.3

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

I use docker to run

### Database

PostgreSQL

**Comment by lunny** [comment]
Please set your `ROOT_URL` in your app.ini correctly.

**Comment by zhenzi0322** [comment]
> Please set your `ROOT_URL` in your app.ini correctly.

ok
