### ISSUE TITLE
Mailer not working

### ISSUE THREAD

**Issue by mootfrost** [go-gitea/gitea#21697]
### Description

I have created my own mail on my domain and I want to set up a mailer in getea. My configuration:

```
[mailer]
ENABLED        = true
SMTP_ADDR      = smtp.yandex.ru
SMTP_PORT      = 465
FROM           = xxx@xxx.ru
USER           = xxx@xxx.ru
PASSWD         = xxx
PROTOCOL       = smtps
HELO_HOSTNAME  = xxx.ru
```

When trying to send a test email, error 504. I also tried an example from the documentation for gmail, it doesn’t work. What am I doing wrong?

### Gitea Version

1.18.0+rc0 

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

2022/11/06 10:57:57 [63676807] router: slow      POST /admin/config/test_mail for 79.139.191.112:0, elapsed 3082.2ms @ admin/config.go:31(admin.SendTestMail)

### Operating System

Ubuntu 20.04

### How are you running Gitea?

Docker compose gitea/gitea:latest

### Database

SQLite

**Comment by Mootfrost777** [comment]
@xin-u, I made a password for the app, but still nothing happens:(

**Comment by Mootfrost777** [comment]
Both Yandex and Google mail does not work, I'm beginning to suspect that I'm doing something wrong, but I don't know what

**Comment by Mootfrost777** [comment]
@xin-u. LMFAO, there was port simply blocked by host provider
