### ISSUE TITLE
Show dates for tags

### ISSUE THREAD

**Issue by WhyNotHugo** [go-gitea/gitea#21699]
### Feature Description

When looking at tags, only their name and commit sha are shown, but not their date.

Showing the dates for tags would be super useful to understand their age, or history of a project at a glance.

### Screenshots

![image](https://user-images.githubusercontent.com/730811/200177200-fd95f40a-252f-4d20-a7f3-a0a8ba7273c1.png)

![image](https://user-images.githubusercontent.com/730811/200177228-7760c603-ab5c-4477-9f47-1f9c9ec3bdb1.png)

**Comment by silverwind** [comment]
Also, we are missing the tag message in this list (indicated by `...` on the GitHub UI).
