### ISSUE TITLE
Upgrade from UI

### ISSUE THREAD

**Issue by nacho-domatix** [go-gitea/gitea#21694]
### Feature Description

Although is really simple and easy to upgrade Gitea, I think won't be really difficult to make it work from the UI. It could be manually (as other Go apps like AdGuard do) or even automatic (that could be dangerous tho, and should require a "way back" from cli?).

Anyway, just throwing suggestions.

**Comment by lunny** [comment]
We need to consider more things about the proposal. At least, Gitea don't know how it's running, via systemd or container or others. And second, there are also some work to download the suitable binary, and you don't know whether the version is a special version that users compile it themselves which may contains incompatible things.

**Comment by nacho-domatix** [comment]
Agree, some checks should be done before showing even the option, and if the update is easy as stop the service, download the binary, replace it and start the service provide the functionality.

**Comment by lafriks** [comment]
Problem is that gitea would run as non-privileged user so it can not really update itself. To be able to do that there must be running other service as root to do that

**Comment by nacho-domatix** [comment]
I see. I guess it could ask for "root" password or so. Would be a great feature if can be done.

**Comment by nacho-domatix** [comment]
> what crazy privilege escalation!

Excuse my lack of knowledge (I'm not a developer neither sysadmin), but wIth cli this is quite normal. Anyway I'm just trying to help throwing ideas (even crazy ones) to make this feature happen! :)

**Comment by silverwind** [comment]
I don't think this is feasible. The only way I see is self-update via `fork` syscall through a separate updater process but that could only work in simple standalone non-container deployments and it would probably be only work on Linux, if at all.

Given that the majority of deployments nowadays are in containers, there's not much value to it and self-update inside a container is impossible by design.
