### ISSUE TITLE
Schedule issue creation for recurrent issues: automatically create an issue every X days

### ISSUE THREAD

**Issue by tobiasBora** [go-gitea/gitea#21706]
### Feature Description

We are using gitea's issue tracker to also track some tasks that are recurrent (e.g.: renew a DNS domain every X year, prepare/schedule a weekly meeting, monthly review code, pay a bill every month, fill some administrative documents every week…).

Github [recommends](https://docs.github.com/en/actions/managing-issues-and-pull-requests/scheduling-issue-creation) to use a github action [issue-bot-action](https://github.com/marketplace/actions/issue-bot-action) to create these issues, and it can automatically assign the appropriate users to the newly created repository… Unfortunately gitea [does not want](https://github.com/go-gitea/gitea/issues/12673) to provide a github-action-like functionality and recommends to setup an external CI/CD tool like drone… which is a bit overwhelming for such a simple task. Another option would be to write a bot or to use an external service for this task (IFTTT/zappier/n8n should work, for instance I was able to use IFTTT  (date & time trigger + webhook applet on `https://gitea.com/api/v1/repos/YOURNAME/YOURPROJECT?access_token=TOKEN_IN_SETTINGS_APPLICATIONS_GENERATE_TOKEN`, with type `application/json` and content like `{ "body": "...", "title": "..." }`), but it is not as user friendly (having configuration spread over multiple website is not great) and you may need to pay or self host it.

**Comment by techknowlogick** [comment]
You'll be interested by https://github.com/go-gitea/gitea/issues/13539

**Comment by tobiasBora** [comment]
Oh that looks great! But as I understand the user will still need to add agents to the CI, and therefore self-host a server (unless gitea.com provides an agent for everybody… which seems quite unlikely as it would certainly be quite costly. But I may be wrong, maybe it could be free for small scripts and non-free for longer computations like Github is doing, which could be a business model for gitea). Do you have more informations? If not the current issue may still make sense.
