### ISSUE TITLE
gitea merge request conflict handling online

### ISSUE THREAD

**Issue by Clownsw** [go-gitea/gitea#21719]
### Feature Description

I found that gitea seems to be unable to handle merges after creating merge request conflicts, I wonder if gitea can have the same merge processing capabilities as github

**Comment by kdumontnu** [comment]
Duplicate of https://github.com/go-gitea/gitea/issues/9014

Please let me know if this is closed in error and we can reopen. Otherwise, feel free to add your support to the ongoing efforts towards implementing this feature.
