### ISSUE TITLE
413 when uploading large files using lfs in gitea

### ISSUE THREAD

**Issue by zhenzi0322** [go-gitea/gitea#21717]
### Feature Description

LFS: Client error: http://xxx.xx.cn/xxx/test.git/info/lfs/objects/d3808b9be5f1cdcbd0cdb296eed501f4a43f6e9cde9ec298a982ccf0b312f2de/232468447 from HTTP 413
error: failed to push some refs to 'xxx.xx.cn:xxx/test.git'

**Comment by lunny** [comment]
Please check your reverseproxy configuration.

**Comment by zhenzi0322** [comment]
> Please check your reverseproxy configuration.

ok
