### ISSUE TITLE
Default branch name option in settings

### ISSUE THREAD

**Issue by jtbx** [go-gitea/gitea#21714]
### Feature Description

When creating a new repository, it uses the instance's default branch name. I think there should be an option in the settings menu to choose the default branch name that gets used each and every time you create a repository, similar to how it works in GitHub.

### Screenshots

![Default branch name setting in GitHub](https://i.ibb.co/FkrRNkW/Screenshot-20221108-111015.png)

**Comment by lunny** [comment]
You can do it in repository settings, branches
