### ISSUE TITLE
Uncaught Error: Language id "vs.editor.nullLanguage" is not configured nor known

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#21733]
### Description

related:
- https://github.com/go-gitea/gitea/issues/21427
- https://github.com/microsoft/monaco-editor/issues/2962

### Screenshots

https://user-images.githubusercontent.com/76462613/200743314-8ded50af-7bcd-4b0a-9913-b050a2bad797.mp4

### Gitea Version

 1.19.0+dev

### Can you reproduce the bug on the Gitea demo site?

Yes

### Browser Version

edge

**Comment by lunny** [comment]
If v1.17/v1.18 is also affected.
