### ISSUE TITLE
Import from GitHub failed

### ISSUE THREAD

**Issue by xet7** [go-gitea/gitea#21745]
### Description

Trying to migrate from GitHub https://github.com/wekan/wekan to locally installed Gitea that uses SQLite, with all issues, wiki, etc, using my GitHub API key. It did work some months ago, but not anymore.

I can not test this on try.gitea.io because it works too too slowly, try.gitea.io does not load in browser, and I would prefer not to add my GitHub API key there.

Error:
```
Migrating from https://github.com/wekan/wekan failed.

NzgxNzU4ODk1OA for 127.0.0.1:60492, 200 OK in 0.7ms @ user/task.go:17(user.TaskStatus)
2022/11/09 21:43:48 ...ervices/task/task.go:56:handle() [E] Run task failed: GetTagCommit[v6.48]: context deadline exceeded
2022/11/09 21:43:49 [636c02f5] router: completed GET /user/task/1?_csrf=9VnsDWeT-qdHbn5J_SQHDqeTxoM6MTY2ODAyMjU3NzgxNzU4ODk1OA for 127.0.0.1:60492, 404 Not Found in 0.7ms @ user/task.go:17(user.TaskStatus)
```

### Gitea Version

1.17.3

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![gitea-wekan-failed](https://user-images.githubusercontent.com/15545/200930297-715991a6-e53c-417a-8b68-169024e3953a.png)

### Git Version

2.37.2

### Operating System

Ubuntu 22.10

### How are you running Gitea?

- Downloaded release for amd64

```
mkdir gitea
cd gitea
./gitea web
```

### Database

SQLite

**Comment by KN4CK3R** [comment]
You can change the default timeouts here but I'm not really sure if that's the problem here:
https://github.com/go-gitea/gitea/blob/5a6cba4cf43f9e5be3ca4a3ffd8bfa351c92acbd/custom/conf/app.example.ini#L2130-L2138

Just a note: Looks like you are migrating all releases of that repo. The last releases all contains 500mb files and there are ~40 of them... That's a lot of storage and traffic...

**Comment by xet7** [comment]
@KN4CK3R 

Thanks! It seems that when I unchecked migrating releases, it is continuing migrating issues, PRs etc fine.
