### ISSUE TITLE
Proposal: Pin Issues

### ISSUE THREAD

**Issue by kolaente** [go-gitea/gitea#2175]
I don't know if this is overkill or if there is a better solution, but i'd like to have the abililty to pin issues to have them sticking at the top of the issues page.

This could be useful for general information you don't want to put in the readme or issues everyone in the team should comment.

More Context:
I'm currently working on a project with a bunch of other people. We don't know each other, so someone opened an "introduce yourself"-issue. But now we have so many issues that this one is already on the second page, so noone recognizes it anymore and until now, only two people introduced themselves.

**Comment by sapk** [comment]
This could be implemented by a default label like `pinned` or `on top`. This would not change a lot of code and let people remove the default tag if they want. And without a sort applyed they should be display on top.

**Comment by bkcsoft** [comment]
Adding Issue Priority and being able to sort on that would make more sense to me. Anyone else?

**Comment by lunny** [comment]
@bkcsoft Yes, a priority in database column, but we could also has a button to pin it.

**Comment by daviian** [comment]
@bkcsoft @lunny The pin button has the advantage that the issues are still sorted by date and pinned issues only appear above.

**Comment by lunny** [comment]
@daviian Yes. I mean, we only need to add one column `priority` to implement it. We can add an order SQL before all other order
```SQL
order by `priority` desc,  ...
```
When you `pin` an issue, we will set the issue's `priority` as max `priority` + 10 , and when you unpin it, we could set priority = 0

**Comment by kolaente** [comment]
@lunny i like the idea. Also priority would be a cool feature :grinning: (but wouldn't this be a seperate issue?)

**Comment by BetaCat0** [comment]
I've been working on it :)

**Comment by 6543** [comment]
update?

**Comment by TautFlorian** [comment]
Anything new here? Would be very nice to have.

**Comment by ivancxj** [comment]
need this feature

**Comment by mpeter50** [comment]
> When you pin an issue, we will set the issue's priority as max priority + 10 , and when you unpin it, we could set priority = 0

Implementing these 2 features with a single additional column is more optimal, but this way on unpinning the priority cannot be restored to its old value.

**Comment by stuzer05** [comment]
> More Context: I'm currently working on a project with a bunch of other people. We don't know each other, so someone opened an "introduce yourself"-issue. But now we have so many issues that this one is already on the second page, so noone recognizes it anymore and until now, only two people introduced themselves.

Why not use wiki for that?
