### ISSUE TITLE
LDAP users cannot edit profile anymore: "Name cannot be empty"

### ISSUE THREAD

**Issue by mxmehl** [go-gitea/gitea#2176]
- Gitea version (or commit ref): f33e6ae
- Git version: 2.1.4
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist: no log messages

## Description

Non-local users (LDAP in my case) cannot change their profiles anymore (this worked in an earlier version). The error message `Name cannot be empty.` appears if they modify something, e.g. their location, and press the "Update Profile" button.

## Screenshots

![20170718_auswahl_01](https://user-images.githubusercontent.com/6170081/28292168-2a22b754-6b4e-11e7-8375-829ae169624b.png)

**Comment by lafriks** [comment]
I can confirm this bug
