### ISSUE TITLE
404 Error When Opening .cs Files

### ISSUE THREAD

**Issue by tahaghafuri** [go-gitea/gitea#21774]
### Description

I don't Use CDN OR Proxy,
When Opening https://giteahub.ir/tahaghafuri/Linq/src/branch/master/Linq_Console/Program.cs,Gitea Return 404.

### Gitea Version

1.18-rc0

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

https://giteahub.ir/tahaghafuri/Linq/src/branch/master/Linq_Console/Program.cs

### Screenshots

Available IN:https://giteahub.ir/tahaghafuri/Linq/src/branch/master/Linq_Console/Program.cs

### Git Version

latest

### Operating System

ubuntu 20.04.5

### How are you running Gitea?

I installed it directly on the server.
Runing With gitea.service In Systemd.

### Database

MySQL

**Comment by tahaghafuri** [comment]
https://giteahub.ir/tahaghafuri/ConsoleApplication3/src/branch/main/ConsoleApplication3/Program.cs
https://giteahub.ir/tahaghafuri/Linq2/src/branch/master/Linq_2/PersonCar.cs

All .cs Files return 404.

**Comment by tahaghafuri** [comment]
.cs files directory:
https://giteahub.ir/tahaghafuri/Linq2/src/branch/master/Linq_2

**Comment by lunny** [comment]
Looks like all files view are 404, do you have any special changes?

**Comment by tahaghafuri** [comment]
no

**Comment by tahaghafuri** [comment]
But this is not a problem for https://giteahub.ir/lyntax/lyntax/src/branch/main/LICENSE

**Comment by lunny** [comment]
> https://giteahub.ir/lyntax/pre-test

In the first repository, `.json` file also return 404.

**Comment by lunny** [comment]
Do you have customized renderer?

**Comment by tahaghafuri** [comment]
no

**Comment by tahaghafuri** [comment]
Please Help

**Comment by lunny** [comment]
Could you also check your files permissions? And I think you need to post some logs when viewing these files.

**Comment by tahaghafuri** [comment]
Nov 13 15:02:32 gitea[49891]: 2022/11/13 15:02:32 [6370d5d0] router: completed GET /tahaghafuri/Linq2/src/branch/master/Linq_2 for 185.141.107.75:45610, 200 OK in 69.8ms @ repo/view.go:772(repo.Home)
Nov 13 15:02:33 gitea[49891]: 2022/11/13 15:02:33 [6370d5d1] router: completed GET /error_docs/forbidden.html for 185.141.107.75:41598, 404 Not Found in 8.5ms @ context/repo.go:429(context.RepoAssignment)

**Comment by tahaghafuri** [comment]
I Proxied Gitea ON Plesk(Nginx)
404 With Nginx
<Proxy *>
	Order allow,deny
	Allow from all
</Proxy>
AllowEncodedSlashes NoDecode
ServerName giteahub.ir
ProxyPreserveHost On
ProxyRequests off

# Note: no trailing slash after either /git or port

ProxyPass / http://giteahub.ir:3000/ nocanon
ProxyPassReverse / http://giteahub.ir:3000/

Without nginx no error
