### ISSUE TITLE
[remote rejected] branch-> branch(pre-receive hook declined) 

### ISSUE THREAD

**Issue by jackzhum** [go-gitea/gitea#21782]
### Description
I try to forward port 80 to port 3000 through iis url rewrite，The website can be accessed normally, but an error occurs in push:

config:
[server]
PROTOCOL         = http
SSH_DOMAIN       = git.xxxx.com
DOMAIN           = git.xxxx.com
HTTP_PORT        = 3000
ROOT_URL         = http://git.xxxx.com/
DISABLE_SSH      = true
SSH_PORT         = 22

logs: 
git.exe push --set-upstream --progress "origin" test
Enumerating objects: 5, done.
Counting objects: 100% (5/5), done.
Delta compression using up to 12 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 282 bytes | 282.00 KiB/s, done.
Total 3 (delta 2), reused 0 (delta 0), pack-reused 0
remote:
remote: Gitea: Internal Server Error
remote: Unable to contact gitea: Post "http://localhost:3000/api/internal/hook/pre-receive/User/Project": dial tcp: lookup localhost on 114.114.114.114:53: no such host
To http://git.xxxx.com/User/Project.git
! [remote rejected]   test -> test (pre-receive hook declined)
error: failed to push some refs to 'http://git.xxxx.com/User/Project.git'

IIS web.config:
```
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <system.webServer>
        <rewrite>
            <rules>
                <rule name="gitea">
                    <match url="(.*)" />
                    <conditions>
                        <add input="{HTTP_HOST}" pattern="^git.xxxx.com$" />
                    </conditions>
                    <action type="Rewrite" url="http://git.xxxx.com:3000/{R:1}" />
                </rule>
            </rules>
        </rewrite>
    </system.webServer>
</configuration>
```

### Gitea Version

1.18.0

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

2.25

### Operating System

Windows Server 2012R2

### Database

MSSQL

**Comment by jackzhum** [comment]
I did not find any content of **localhost** in the app.ini

**Comment by lunny** [comment]
dns problem

**Comment by jackzhum** [comment]
The problem is solved after setting the LOCAL_ROOT_URL。
