### ISSUE TITLE
[template] Move all js on head part

### ISSUE THREAD

**Issue by camlafit** [go-gitea/gitea#2179]
Hi

Template system have move some js call on footer page (I presume to performance issue). But I'm not sure is nice to use it in default template : 
* Defer attribute is now correctly supported (http://caniuse.com/#feat=script-defer) 
* is harder to configure a proxy cache/concatenation
* override template is not intuitive (two template files to change/check head and footer)
* jquery dependencies

**Comment by techknowlogick** [comment]
We've now mostly moved to using webpack, and so we pack all JS into one file (kinda, webpack has a webloader that'll load the relevant bits needed).
