### ISSUE TITLE
The commit record operation is not displayed

### ISSUE THREAD

**Issue by JaneYork** [go-gitea/gitea#21797]
### Description

1. re list information is not displayed, and submission and operation information is not displayed. For example, the calendar heat map on the home page, or the organization list page。And I often try to solve this problem, but it doesn't work。 https://docs.gitea.io/zh-cn/faq/#push-hook--webhook-arent-running

2. Sometimes, after successful login, it will jump to the robots.txt page, showing 404. At this point your browser's address is http://domain.com/robots.txt.

### Screenshots

<img width="1673" alt="image" src="https://user-images.githubusercontent.com/29787967/201504102-ea18e4e5-29e0-4397-a790-1ff2ef17943f.png">
<img width="1582" alt="image" src="https://user-images.githubusercontent.com/29787967/201504142-e8d868f4-7cb0-4b86-9783-770b9e758a36.png">

### Gitea Version

1.17.0 Binary installation

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

centos7.9 Aliyun

### Browser Version

Chrome last version

**Comment by lunny** [comment]
Please upgrade to latest stable version and try again.

**Comment by wxiaoguang** [comment]
1. list information is not displayed, and submission and operation information is not displayed.

What have you done?

2. Sometimes, after successful login, it will jump to the robots.txt page,

It seems your browser's or your reverse-proxy's problem.
