### ISSUE TITLE
Add option to ignore whitespace in diffs 

### ISSUE THREAD

**Issue by tobias--** [go-gitea/gitea#2180]
- Gitea version (or commit ref): 1.1.2

## Description

It would be great to have the ability to ignore whitespace in diffs on demand. For example, Github allows you to do this by adding '?w=1' to the URL. See https://github.com/blog/967-github-secrets

**Comment by tonivj5** [comment]
woow, that trick is awesome! Thanks 😄

**Comment by tobias--** [comment]
I just noticed: This issue duplicates #716.

**Comment by andreynering** [comment]
@tobias-- In this case let's close this in favor of #716
