### ISSUE TITLE
High used of cpu when i run gitea one or two day.

### ISSUE THREAD

**Issue by Codefans-fan** [go-gitea/gitea#21816]
### Description

![image](https://user-images.githubusercontent.com/5079520/201804318-464ce84f-e572-4e1a-b7f3-4c5a811f0c6c.png)

I need  restart to fix it.

### Gitea Version

1.17.3

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![image](https://user-images.githubusercontent.com/5079520/201805013-08095b2e-1041-4ea2-8c04-c63232d1ae6b.png)

### Operating System

Mac mini M1

### How are you running Gitea?

gitea & 

### Database

PostgreSQL

**Comment by Codefans-fan** [comment]
https://github.com/go-gitea/gitea/issues/10661 
issue come again ?

**Comment by zeripath** [comment]
The most likely cause of this is the cron task: repo_health_check which runs at midnight

This runs git fsck on your repositories. I suspect you have a repo that needs to be fsck'd and looked at

**Comment by Codefans-fan** [comment]
> Are you able to enable pprof and get a stack trace?
> 
> You'll need to enable pprof in app.ini and restart Gitea
> 
> ```
>     [server]
>     ENABLE_PPROF = true
> ```
> 
> Then when Gitea gets stuck, use curl or browser to visit: http://127.0.0.1:6060/debug/pprof/goroutine?debug=1 (IP must be 127.0.0.1 and port must be 6060).
> 
> Report the output back here.

OK.  I will try

**Comment by Codefans-fan** [comment]
> 

Sometime i also get in day time.  
That's see after i active the pprof.

**Comment by Codefans-fan** [comment]
> The most likely cause of this is the cron task: repo_health_check which runs at midnight
> 
> This runs git fsck on your repositories. I suspect you have a repo that needs to be fsck'd and looked at

Sometime i also get in day time.
That's see after i active the pprof.

**Comment by Codefans-fan** [comment]
when i push new data,   gitea create new thread and it take 100 % .  i restart the gitea this thread still exist.  need kill  the pid manually

**Comment by Codefans-fan** [comment]
> Do you build Gitea yourself or where did you download it?
Install using following command: 
```
brew tap gitea/tap https://gitea.com/gitea/homebrew-gitea
brew install gitea
```

**Comment by wxiaoguang** [comment]
After #24636 (1.20 nightly at the moment)

You can download the CPU profile from you admin page. Then we can know what happens.


![image](https://github.com/go-gitea/gitea/assets/2114189/c5c46fae-9dc0-44ca-8cd3-57beedc5035e)

**Comment by wxiaoguang** [comment]
Feel free to re-open if there are new clues.
