### ISSUE TITLE
Gitea file view seems to show an invalid empty line at the end for Unix line breaks

### ISSUE THREAD

**Issue by ell1e** [go-gitea/gitea#21821]
### Description

Gitea's file view seems to show an invalid empty line at the end for Unix line break files. On Windows, which can be verified with the built-in `Notepad.exe`, a file with DOS style line breaks (`\r\n`) will count every line break as start of a new separate line, for example `a\r\nb` (`a` followed by DOS line break followed by `b`) shows as two lines, and `a\r\nb\r\n` would show as three lines. However, on e.g. Linux, which can be verified e.g. with `vim`, a file with Unix style line breaks (`\n`) will be expected and be saved with each line to end with a `\n`, such that `a\nb\n` would show as **two** lines and not three.

Gitea seems to always apply the Windows interpretation of line break characters, but it should only do so if the file uses `\r\n` line breaks and otherwise apply the Unix logic. As a result, Gitea shows an unexpected additional empty line for Unix line break text files, since the trailing `\n` terminating the last line appears to be interpreted as starting a new line when with Unix line breaks it's not meant to.

(It likely reproduces on the Gitea demo site as well but I didn't try, since it can't be done via just the web UI since that won't show me what line breaks it saved and whether it saved a trailing `\n` or not.)

### Gitea Version

 1.17.3+97-ge7abdb2 

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

I tested this on someone else's instance

**Comment by wxiaoguang** [comment]
The new line logic has been totally rewritten in 1.18 or try.gitea.io.

Please provide some demo files on try.gitea.io
