### ISSUE TITLE
API update for adding GPG key on behalf of user

### ISSUE THREAD

**Issue by timaw7** [go-gitea/gitea#21838]
### Feature Description

Our use case is that we are attempting to fully manage keys through an admin account. We've locked down the user profile to not display the "SSH/GPG keys" tab and instead have an admin manage and add keys on behalf of a user through scripts utilizing the API.  

The API /admin/users/{username}/keys allows us to add SSH keys.  It does not appear that there is an option for an admin to add GPG keys for a user.  Adding this option for an admin would round out the ability for managing keys strictly through an admin account.

**Comment by techknowlogick** [comment]
As you are operating as an admin user, you could use the "sudo" capability of the API and use the standard gpg endpoint: https://docs.gitea.io/en-us/api-usage/#sudo
