### ISSUE TITLE
No Pascal code highlighting

### ISSUE THREAD

**Issue by Sniperq2** [go-gitea/gitea#21837]
### Description

When I add Pascal project to my gitea server I saw no any code highlighing for pascal files. See screenshot.

### Gitea Version

1.17.3

### Can you reproduce the bug on the Gitea demo site?

Did no try.

### Screenshots

![gitea-pascal](https://user-images.githubusercontent.com/1060059/202267298-39a99846-2f2b-4162-9978-e5b3b2fb9757.png)

### Operating System

Windows 10

### How are you running Gitea?

Windows exe file

### Database

MySQL

**Comment by techknowlogick** [comment]
Thanks for reporting this, we use https://github.com/alecthomas/chroma as our syntax highlighter.

**Comment by silverwind** [comment]
Follow https://github.com/alecthomas/chroma/issues/288, or better yet, contribute it there.

**Comment by silverwind** [comment]
Might want to keep this open just for visibilty.

**Comment by codiacdev** [comment]
I created a pull request (https://github.com/alecthomas/chroma/pull/883) and it was accepted, so there is hope...

**Comment by regs01** [comment]
> I created a pull request ([alecthomas/chroma#883](https://github.com/alecthomas/chroma/pull/883)) and it was accepted, so there is hope...

And it's working in Chroma 2.12. Any chance of update for Gitea 1.22?
<img width="574" src="https://github.com/go-gitea/gitea/assets/10468217/0c0c5c4a-e176-4d74-a2b4-6dde85b85d09">

**Comment by wxiaoguang** [comment]
> And it's working in Chroma 2.12. Any chance of update for Gitea 1.22?

Gitea 1.22 is using 	`github.com/alecthomas/chroma/v2 v2.12.0`

https://github.com/go-gitea/gitea/blob/a1dfffd723c434966152ee521c99e966a3aee065/go.mod#L20C1-L20C41

**Comment by wxiaoguang** [comment]
https://try.gitea.io/wxiaoguang/test/src/branch/master/test.pas

![image](https://github.com/go-gitea/gitea/assets/2114189/5c862f3c-4a84-4476-b94f-043aee0d34b1)
