### ISSUE TITLE
markdown: wrong indentation of list

### ISSUE THREAD

**Issue by andreynering** [go-gitea/gitea#2186]
Giving the following input:

```md
* Level 1
  * Level 2
    * Level 3
      * Level 4
        * Level 5
          * Level 6
```

This is rendered by Gitea:

![gitea](https://user-images.githubusercontent.com/7011819/28430066-8152c74a-6d55-11e7-86fc-7eee13b431f5.png)

As a test case, GitHub correctly renders it, as below:

* Level 1
  * Level 2
    * Level 3
      * Level 4
        * Level 5
          * Level 6

Reproduce on try.gitea.io: https://try.gitea.io/andreynering/issue-test/issues/2

**Comment by ethantkoenig** [comment]
See https://github.com/russross/blackfriday/issues/329

**Comment by 6543** [comment]
@andreynering  can you check again?

the markdown rendering lib has changed in v1.12.0

**Comment by zeripath** [comment]
https://try.gitea.io/arandomer/pathological/issues/3

it's fixed.
