### ISSUE TITLE
Apply 2FA challenge together with username/password

### ISSUE THREAD

**Issue by markovendelin** [go-gitea/gitea#21870]
### Feature Description

Right now, if we configure 2FA with OTA, OTA PIN is requested only after username and passwords have passed the checks. Which, in principle, allows attacker to scan usernames/passwords and later focus on OTA. Or use the obtained username/password combination for some users on other services. 

Such issue could be solved if 2FA challenge would be asked always together with username/password. So, check would be done on full set. For users without 2FA, the corresponding field would be let empty.

**Comment by lafriks** [comment]
2FA can be can be multiple types including hardware keys, so this is not really option that's why all services use it after first step (username/password) are done
