### ISSUE TITLE
Gitea SAAS

### ISSUE THREAD

**Issue by tahaghafuri** [go-gitea/gitea#21871]
### Feature Description

Hi,
SAAS Feature For Gitea,

Examples:
https://www.google.com/search?q=gitlab+saas
https://docs.gitlab.com/ee/subscriptions/gitlab_com/

**Comment by techknowlogick** [comment]
There are many providers who can provide gitea hosting for you, one of our sponsors https://hostea.org, https://docs.gitea.io/en-us/install-on-cloud-provider/, and [https://www.google.com/search?q=gitea+hosting](https://www.google.com/search?q=gitea+hosting)
