### ISSUE TITLE
[BUG] wrong migration in v1.17.3

### ISSUE THREAD

**Issue by wolflu05** [go-gitea/gitea#21880]
### Description

after upgrading from v1.16.7 to v1.17.3 Gitea logs these warnings.

```
gitea    | 2022/11/20 16:29:55 routers/init.go:135:GlobalInitInstalled() [W] Table push_mirror has column sync_on_commit but struct has not related field
gitea    | 2022/11/20 16:29:56 routers/init.go:135:GlobalInitInstalled() [W] Table gpg_key column content db type is TEXT(65535), struct type is MEDIUMTEXT
gitea    | 2022/11/20 16:29:56 routers/init.go:135:GlobalInitInstalled() [W] Table public_key column content db type is TEXT(65535), struct type is MEDIUMTEXT
```

These fields are added through a wrongly back ported migration, see [migrations.go](https://github.com/go-gitea/gitea/blob/f48fda8eefa4d47e335f01ac92366b9373950e0e/models/migrations/migrations.go#L400) .

Discussion started on [discord](https://discord.com/channels/322538954119184384/322538954119184384/1043926537356976188)

### Gitea Version

v1.17.3

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

docker via `gitea/gitea:1.17.3`

### Database

MySQL

**Comment by zeripath** [comment]
I'm not sure they're wrong exactly - the empty values shouldn't cause any problem as far as I can see. 

Potentially we should backport a "fix" that adds the empty fields to the schemas.

**Comment by zeripath** [comment]
Xorm is right to moan here the structs aren't matching what the migration has done, we should probably update the structs to match the migration

**Comment by lunny** [comment]
`sync_on_commit` is added in v1.18, so I think maybe you ever downgrade from 1.18, so there is a `[W] Table push_mirror has column sync_on_commit but struct has not related field` there.

**Comment by lunny** [comment]
> I'm getting the same warning messages and found that this is also preventing me from adding any commits in the web editor because I have `CRUD_ACTIONS` set to always sign, which is probably to be expected.
> 
> ```
> [repository.signing]
> SIGNING_KEY = XXXXXXXXXXXXXXX
> SIGNING_NAME = Some Key Name
> SIGNING_EMAIL = user@example.com
> INITIAL_COMMIT = pubkey
> CRUD_ACTIONS = always
> ```
> 
> gitea.log:
> 
> ```
> 2022/11/30 19:31:26 ...y/files/temp_repo.go:300:CommitTreeWithDate() [E] [638803ee] Unable to commit-tree in temporary repo: user/repo (/home/git/gitea/data/tmp/local-repo/upload.git429096436) Error: exit status 1
> 	Stdout: 
> 	Stderr: error: gpg failed to sign the data
> 	
> 2022/11/30 19:31:26 .../api/v1/repo/file.go:601:handleCreateOrUpdateFileError() [E] [638803ee] UpdateFile: Unable to commit-tree in temporary repo: user/repo Error: exit status 1
> 	Stdout: 
> 	Stderr: error: gpg failed to sign the data
> 	
> 2022/11/30 19:31:39 ...y/files/temp_repo.go:300:CommitTreeWithDate() [E] [638803fb-2] Unable to commit-tree in temporary repo: user/repo (/home/git/gitea/data/tmp/local-repo/upload.git4244920609) Error: exit status 1
> 	Stdout: 
> 	Stderr: error: gpg failed to sign the data
> 	
> 2022/11/30 19:31:39 .../api/v1/repo/file.go:601:handleCreateOrUpdateFileError() [E] [638803fb-2] UpdateFile: Unable to commit-tree in temporary repo: user/repo Error: exit status 1
> 	Stdout: 
> 	Stderr: error: gpg failed to sign the data
> 	
> 2022/11/30 20:02:11 ...y/files/temp_repo.go:300:CommitTreeWithDate() [E] [63880b23] Unable to commit-tree in temporary repo: user/repo (/home/git/gitea/data/tmp/local-repo/upload.git3654155080) Error: exit status 1
> 	Stdout: 
> 	Stderr: error: gpg failed to sign the data
> ```

This is a different issue.

**Comment by lunny** [comment]
Another two fields are `TEXT` before v1.17 but `MEDIUMTEXT` from v1.17. And the migration has been added in v1.18 from #20896
