### ISSUE TITLE
Docker Hub latest Tag points to release candidate?

### ISSUE THREAD

**Issue by notDavid** [go-gitea/gitea#21889]
### Description

Hi there,

i have pointed my docker compose container to pull the image `gitea/gitea:latest`, however i am running version `1.18.0+rc0`.

- Should the `latest` tag not point to the latest **stable** version?
- Could someone confirm whether this is some mistake, or a configuration error on my side?

Thank you.

https://hub.docker.com/r/gitea/gitea/tags

### Gitea Version

1.18.0+rc0

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

Docker compose

```
services:
  server:
    image: gitea/gitea:latest
```

### Database

SQLite

**Comment by lunny** [comment]
duplicated with #21615
