### ISSUE TITLE
Show required commit status which haven’t been done yet

### ISSUE THREAD

**Issue by markusamshove** [go-gitea/gitea#21892]
### Feature Description

If a base branch has a protection requiring a check, but the check hasn’t been started for a commit yet, then there is no indication in the pull which checks are missing. 

aside from pending, failed, succeeded etc checks, the pull page could also render missing checks (required checks that haven’t reported any status for the commit yet)

**Comment by lunny** [comment]
I think this has been implemented, you can find it in the branch protection page.

**Comment by MarkusAmshove** [comment]
I can't find a setting in the branch protection, might be a 1.18 feature (currently running 1.17.3)

**Comment by MarkusAmshove** [comment]
This still seems to be missing, unless I'm missing an option.

If you have a required check called "A" and open a PR for the protected branch, but the commit doesn't have any status from the check "A", then the PR page just says that there are missing checks, but not which checks are missing.

**Comment by lafriks** [comment]
It not only does not show required checks in PR view, it also allows merging PR while CI has not reported any status for required checks that are set in branch protection rules

**Comment by MarkusAmshove** [comment]
> It not only does not show required checks in PR view, it also allows merging PR while CI has not reported any status for required checks that are set in branch protection rules

This one already bit us 4-5 times since 1.20 and the introduction of patterns for status checks :)

**Comment by MarkusAmshove** [comment]
> It not only does not show required checks in PR view, it also allows merging PR while CI has not reported any status for required checks that are set in branch protection rules

Is there a way to set required checks as pending on the side of Gitea?
I can try to add them for PR updates via a 3rd party app with webhooks, but I think it could happen that I overwrite a commit status that was notified in the meantime

**Comment by MarkusAmshove** [comment]
I gave it a shot to fix the problem with the linked PR
