### ISSUE TITLE
Repository topic/labeling globally and within an organisation

### ISSUE THREAD

**Issue by typeless** [go-gitea/gitea#219]
When the number of repositories of an organisation grows to an extent, it's going to be difficult to keep the repos well-organised and easy to find. In directory-oriented VCS like Subversion, that can be intuitively handled by directory hierarchy. Something like labels for Git repository would help improving the user experience.

Ideas?

**Comment by tboerger** [comment]
This needs to be optional for sure, Bitbucket is an example, they are providing some kind of folders now, but IMHO it's not done really good.

**Comment by typeless** [comment]
@tboerger What are the disadvantages of Bitbucket's approach? I have never used the feature at Bitbucket.

**Comment by lunny** [comment]
This is like github topic.

**Comment by typeless** [comment]
A tree-like directory view of repositories would still be useful than the Github topic (or they serve different purposes). For instance, we currently have dozens of small shared libraries which share a common umbrella to expose a set of APIs. It's similar to Qt and its subordinate modules. In order to avoid messing the libraries with other unrelated repos belonging to the same team, we could use sub-modules to emulate the tree view. But it would still require annoying linear-search from page to page to locate the meta repo if it's not on the first few pages. It's less optimal than what CVS/subversion can do when it comes to organize hierarchical relationships of projects.

**Comment by marbetschar** [comment]
Would really love to see GitHub like topics in Gitea! This would enable a bunch of possibilities. Was there already any progress in implementing this?

![topics](https://user-images.githubusercontent.com/392542/37148180-c8318604-22c9-11e8-91ea-734f62e492ec.JPG)
