### ISSUE TITLE
How/where to set/select Package Type fоr Repository

### ISSUE THREAD

**Issue by 4meck** [go-gitea/gitea#21916]
### Description

"Enable Repository Packages Registry" is checked. How/where to set/select Package Type fоr Repository. Please share screenshot (link docs, config example..) or this feature is still not implemented, despite its presence in the documentation?

app.ini:
RUN_MODE = dev or RUN_MODE = prod 
[packages]
ENABLED = true

https://try.gitea.io/4meck/test1

### Gitea Version

1.17.3

### Can you reproduce the bug on the Gitea demo site?

Yes

### Git Version

2.31.1

### Operating System

Linux 5.14.0-197.el9.x86_64

### How are you running Gitea?

 docker.io/gitea/gitea:1.17.3 (Podman container)

### Database

SQLite

**Comment by KN4CK3R** [comment]
I don't understand your question. If you upload a package to an owner (user or organization), you can open the package settings and link the package to a repository there. Then the package will be displayed in the repository.

**Comment by 4meck** [comment]
I'm sorry, but i can not find in UI "package settings and link the package to a repository there" 
 - https://try.gitea.io/4meck/test1/settings
 - There are no packages yet.	https://try.gitea.io/4meck/test1/packages
 - There are no packages yet.	https://try.gitea.io/4meck/-/packages

Browser Version 1.45.127 Chromium: 107.0.5304.110 (Official Build) (64-bit)

**Comment by 4meck** [comment]
My demo repo https://try.gitea.io/4meck/test1 is not empty. (!)
 
Please tell me, how many files and in what format I need to upload to the repository in order to set the "Package Type" I need and the repository was available via gitea api.

**Comment by KN4CK3R** [comment]
I don't understand your problem. The package registry has nothing to do with the git files in your repository.

**Comment by 4meck** [comment]
The package registry is a list of git repositories by type of package manager and owner (company | user).
Depending on the repository type, the Gitea repository indexer creates an index file (repository list: owner, type, name...)
When calling the /packages/{owner}/{type} API, this file is passed to the client in a generic format, such as composer.json.
Do I understand the mechanism/algorithm/functionality of the package registry correctly?

**Comment by KN4CK3R** [comment]
No, everything is mixed in your explanation. Have a look at the [documentation](https://docs.gitea.io/en-us/packages/overview/) for the specific package type to learn how to use the package registry.
