### ISSUE TITLE
Ability to disable default issue template

### ISSUE THREAD

**Issue by C-EO** [go-gitea/gitea#21914]
### Feature Description

It would be great if one could disable Gitea's default issue template.
This could be done through a `config.yml` file like Github's system does.

### Screenshots

![image](https://user-images.githubusercontent.com/85847352/203545895-de730842-cef5-4a72-a187-564b821f71ad.png)

---

![image](https://user-images.githubusercontent.com/85847352/203546154-9c110604-1e2a-4dd3-be40-332773581136.png)

**Comment by jolheiser** [comment]
Ref #20955 #20956
