### ISSUE TITLE
Change webhook format for Discord compatibility

### ISSUE THREAD

**Issue by hauau** [go-gitea/gitea#2191]
- Gitea version (or commit ref):
1.1.2
- Can you reproduce the bug at https://try.gitea.io:
  - [x] No (It's currently down)

## Description

Currently webhook uses the format `repo:[branch]`
This format parsed incorrectly in Discord but if it were to be changed from `[ ]` to `( )` then this would be fixed. 

This is already fixed in gogs ([gogits/gogs/issues/4088](https://github.com/gogits/gogs/issues/4088)). I hope it can be done in gitea. 

## Screenshots

![screenshot 134](https://user-images.githubusercontent.com/8182054/28467766-1d383694-6e5b-11e7-9396-7ba5d35f90c8.png)

**Comment by lunny** [comment]
@appleboy it seems someone cherry picked Gogs discord webhook commit?

**Comment by appleboy** [comment]
I think nobody cherry picked Gogs discord webhook commit.

**Comment by bkcsoft** [comment]
It's using the slack webhook... And the "fix" is not exactly nice. I'd prefer to just add a Discord hook TBH...
https://github.com/gogits/gogs/commit/127005d733458d9a5e82f611fbb35ec70f3ff9c8

To be perfectly honest, I'd prefer to have all webhooks be templates that we render 🙄 

EDIT: it's not nice, but it works :trollface: https://play.golang.org/p/UZJbTEMkW7
