### ISSUE TITLE
Scale of avatar for user in Issue history is larger than it should be

### ISSUE THREAD

**Issue by wxiaoguang** [go-gitea/gitea#21924]
main branch, https://try.gitea.io , any issue with edit history, eg: https://try.gitea.io/wxiaoguang/test/issues/1

The avatar is broken, it's shown as the original size.

![image](https://user-images.githubusercontent.com/2114189/203785183-d109175f-fd04-4e57-a4a0-9d145218410b.png)

**Comment by silverwind** [comment]
Vertical centering also needs to be fixed.
