### ISSUE TITLE
Wrong documentation for windows service 

### ISSUE THREAD

**Issue by boyfromgermany** [go-gitea/gitea#21923]
### Description

I used windows Service doc 
https://docs.gitea.io/en-us/windows-service/

but it is wrong 

OS: windows Server 2019

the documentation says

`sc.exe create gitea start= auto binPath= "\"C:\gitea\gitea.exe\" web --config \"C:\gitea\custom\conf\app.ini\""`

but it only worngs with the following command
`sc.exe create Gitea start= auto binPath= ""C:\gitea\gitea.exe" web --config "C:\gitea\custom\conf\app.ini""`

### Gitea Version

1.18

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![image](https://user-images.githubusercontent.com/36824290/203733311-7d928a3d-098f-4e9b-a05d-1e6a98797c55.png)

### Operating System

Windows Server 2019

### How are you running Gitea?

Download from releases page

**Comment by lafriks** [comment]
Could it be difference on how postscript interprets escaping vs cmd?

**Comment by lunny** [comment]
I think the documentation has said `open a command prompt (cmd) as an Administrator`.
