### ISSUE TITLE
Adding permissions control for source code attachments

### ISSUE THREAD

**Issue by 4EarHeart1** [go-gitea/gitea#21933]
## My requirement
I want to implement closed-source hosting of a repository in gitea.

## Description
Right now gitea can control the visibility of code modules and release-modules for teams in the organization, but I would like to open up the access to my release attachments, but unfortunately I find that gitea cannot do that at the moment. The first reason is that the release automatically packages the source code program as a release attachment, and the second reason is that access to tags cannot be controlled separately.

## My expectations
1、Add the option of whether to include source code attachments when releasing a version.
2、Add access rights control of tags, or control whether tags show source code.

### Screenshots

![image](https://user-images.githubusercontent.com/64122863/203932858-f965347a-f02c-4c73-84b3-28722aba5d56.png)
![image](https://user-images.githubusercontent.com/64122863/203932880-4f441f13-7d50-4711-aae7-d6a68ffc31c4.png)
![image](https://user-images.githubusercontent.com/64122863/203932908-f711a923-093f-4ae5-bead-81db41409c82.png)

**Comment by lunny** [comment]
If one can't view `Code` tab, then he cannot visit that. This has been implemented.

**Comment by 4EarHeart1** [comment]
I'm sorry, I thought I could only control the display of the module, but I tried it now. Thank you very much.

**Comment by 4EarHeart1** [comment]
#21773   Please follow up, thank you!

**Comment by lunny** [comment]
I think this has already been implemented. If code is disabled or unreachable, these archives will not be displayed in releases.
