### ISSUE TITLE
[Feature] run git_gc_repos and deleted_branches_cleanup on specific repo

### ISSUE THREAD

**Issue by somera** [go-gitea/gitea#21938]
It's possible to run git_gc_repos and deleted_branches_cleanup on specific repo?

**Comment by a1012112796** [comment]
wonder whether it's necessary... for the repo owner, they wll't care about how much disk space wa used unless they need pay for it (but limit repo size feature is not exist now). then for the owner of server, they
can do it while ssh client quickly ...
