### ISSUE TITLE
Gitea can not display the sql file exported from navicat

### ISSUE THREAD

**Issue by sancome** [go-gitea/gitea#21949]
### Description

i pushed a sql file to gitea, but it could not be displayed, i got the error "ERR_CONNECTION_RESET".

### Gitea Version

1.17.3

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

Ubuntu 20.4

### How are you running Gitea?

wget -O gitea https://dl.gitea.io/gitea/1.17.3/gitea-1.17.3-linux-amd64
chmod +x gitea
./gitea web

### Database

SQLite

**Comment by wxiaoguang** [comment]
ERR_CONNECTION_RESET is 99.9% unrelated.

Please provide detailed reproducible steps if there is really a bug.

**Comment by wxiaoguang** [comment]
No more feedback, I think this issue can be closed, feel free to reopen if there are more clues.
