### ISSUE TITLE
Add well-known security.txt

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#21942]
the [security.txt](https://securitytxt.org/) described in  [RFC 9116](https://www.rfc-editor.org/rfc/rfc9116) should be signed by giteas bot key and should be able to be overwritten ... like other custom templates.

**Comment by 6543** [comment]
easyest way would be to just write a template and add this route ...
... more advanced way would be to write a lib that can generate, parse and validate according, and use the instance gpg key for signing if changes where made ... else use the gpg key of gitea-bot to sign

**Comment by caesar** [comment]
Will it be possible for the insurance admin to opt into also receiving reports, or only by replacing the whole file via the templates mechanism?

**Comment by silverwind** [comment]
> easyest way would be to just write a template

I'd just expose the individual values as config options. Easier to use than custom templates.

**Comment by alex19srv** [comment]
Hello.
I want to implement this feature. My vision: add `app.ini`-> `security` section `SECURITY_TXT_FILE` optional key with path to `security.txt` file. If key defined and file does not exist - report failure. If not defined/empty - use hardcoded `security.txt` value.

The reason for such architecture - `.ini` files do not support multiline values (and if do support security.txt content need to be written in single line - this is inconvenient). Also separate file allow easy support for signed `security.txt` file content. In such situation I do not see how "individual values as config options" will work better then bulk hardcoded `security.txt` + custom file.

**Comment by wxiaoguang** [comment]
My suggestion is not adding a new config key.

But make Gitea can read serve files in "CustomPath/web-well-known" as its "http://gitea/.well-known" directory. Then users could add anything they like, not only the "security.txt"
