### ISSUE TITLE
Hide fork repo in explore page

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#21961]
### Feature Description

If the fork repo can be hidden, the search results will be clearer

- https://gitea.com/explore/repos?q=gitea
- https://github.com/search?q=gitea

**Comment by delvh** [comment]
Implemented by #19361 already?

**Comment by delvh** [comment]
You just made me write a PR to remove this option as it is useless.
Will create it once I've been able to test that it still works as expected :)

**Comment by delvh** [comment]
See #21962.
