### ISSUE TITLE
What about going Jamstack?

### ISSUE THREAD

**Issue by pboguslawski** [go-gitea/gitea#21977]
### Feature Description

https://github.com/go-gitea/gitea/pull/16052 shows us two separate set of handlers for maintenance: one for web UI and one for "API clients". Two different sets of authentications for both (i.e. auth cookies and CSRF in web UI only). Current way (splitting routes, fixing on token auth for API) sounds not very flexible for future.

Idea to consider for Gitea's future: treating web UI as any other API client (and wiriting it as static SPA, Jamstack way) and making go backend API server only, one for all Gitea's clients (web ui, mobile, etc.). Maybe it's possible to smooth migrate using new API v2 and switch web UI elements to it when ready and supporting API v1 till the and of API v2 implementation?

I can see Github UI works like SPA today so probably Gitea can go SPA way too; single API maintenance, frontend UI separation from backend (easier replacing with new techologies like svelte/wasm/... in the future if required) is worth cosideration IHMO.

Seems CSRF protection may be based on Origin header only today (supporting only up to date, compatible web browsers) and throw away CSRF tokens?

- https://www.mixmax.com/engineering/modern-csrf
- https://github.com/sveltejs/kit/issues/72
- https://github.com/sveltejs/kit/pull/6510/files

**Comment by pboguslawski** [comment]
> Do you see what I mean, when I say it's unlikely to be implemented completely?

Yes I'm aware of complexity of such changes for existing projects; consider evolution (implementing changes according to ordered direction) not revolution. Your stat shows many technologies (not all probably - many different UI frameworks used?) which looks hard to manitain and probably will be harder to maintain/modernize in the future if changes will be required (i.e. drop outdated frontend frameworks).

**Comment by lunny** [comment]
I think the API should be a standalone service which main aim is to be invoked by external tools like sdks, CI/CD, mobile etc. which need a stable output. But for UI, the requirement is to provide data according the UI need, it means they should be changed when UI changed as well. So I don't think they should be shared otherwise it will bondage UI's development, you need to consider more when you want to change some routes.

For the SPA idea, for a very big project, a single page SPA will slow down the loading speed in an internet environment. Since Gitea wants to support both internet instances and intranet instances, at least we need a multiple page SPA. Go templates required some skills for frontend developers but an advantage of that is SEO, that is important for public Gitea instances.

**Comment by techknowlogick** [comment]
You may be interested in the following: https://github.com/unfoldingWord/gitea-react-toolkit

**Comment by kousu** [comment]
I would not like Gitea to be an SPA. I like that it renders, tight, low-resource HTML and is usable without JavaScript.

Making an SPA would mean adding way more network traffic to compute basic facts; like, how would you implement this typesniffer in an SPA?

https://github.com/go-gitea/gitea/blob/b2c4870481329889a76ea2421152647d36dd8374/routers/web/repo/view.go#L385-L388

https://github.com/go-gitea/gitea/blob/b2c4870481329889a76ea2421152647d36dd8374/routers/web/repo/view.go#L608-L616

https://github.com/go-gitea/gitea/blob/b2c4870481329889a76ea2421152647d36dd8374/templates/repo/view_file.tmpl#L63-L84

You'd have to download and parse the files in JavaScript, or fallback on trusting their file extensions, or add "/type-sniff/" route.

So, sorry, and I'm not on the team so my vote doesn't count for much, but :-1:

**Comment by pboguslawski** [comment]
> which need a stable output

Yes API should be stable but can be extended in backward compatible way. Breaking changes should increment API major version similar to how go modules versioning works.

> But for UI, the requirement is to provide data according the UI need,

Web UI should be treated as any other client and Web UI specific processing should be moved to Web UI if possible not to API. API should be kept as minimal, common base required for any type of client to be able to function.

> otherwise it will bondage UI's development,

Adding features should be analyzed in both sides: API and client; if its possible to implement feature easily on client side only - API should not be extended (to keep is as simple and secure as possible). Also [bloatware](https://en.wikipedia.org/wiki/Software_bloat#Examples) direction should be avoided.

> For the SPA idea, for a very big project, a single page SPA will slow down the loading speed in an internet environment. 

>  at least we need a multiple page SPA

> but an advantage of that is SEO, that is important for public Gitea instances.

This is challenge I agree. Github.com direction worth studying here maybe; mutliple SPAs will be better than server side rendering IHMO. Client/API separation would help in experiments with different client technologies and even provide seaparate clients for different areas (i.e. dummy front for search engines that won't read SPA, light HTML front for people afraid of JS, main modern UI with JS/wasm for general use, etc.).

> how would you implement this typesniffer in an SPA

Don't know this function but well designed API should not trust any client, even its own web UI and verify incoming every data on backed before storing/applying it to system. Verification on client side may be helpful also to avoid long uploads just to be blocked by server.

**Comment by gnat** [comment]
> This is challenge I agree. Github.com direction worth studying here maybe; mutliple SPAs will be better than server side rendering IHMO.

Um, not to make this a red herring, but Github's SPA implementation is notoriously slow compared to accessing Github URL's directly. It's likely Github will eventually move to Hotwire with their Ruby on Rails 7 transition, which is similar to htmx but for Rails 7. I doubt their existing implementation will stick around on the main website.

**Comment by silverwind** [comment]
I don't think it's realistic to rewrite Gitea UI to an SPA. Far too much code and far too much work for questionable benefit. Parts of the UI are SPA-fashion components that could also rely on API only, but not everything.
