### ISSUE TITLE
Document Makefile dependencies

### ISSUE THREAD

**Issue by silverwind** [go-gitea/gitea#2198]
## Description

The `Makefile` has various dependencies on command line tools which should be documented as a requirement for developing Gitea. I'm thinking this should be in a file in the repository itself and not on the website, maybe in `CONTRIBUTING.md` or `README.md`.

**Comment by lafriks** [comment]
I think `CONTRIBUTING.md` would be best place for this

**Comment by bkcsoft** [comment]
@silverwind Do you have a list of those? If you're referring to various `go get` then those should be fetched automagically if they don't exist

**Comment by sapk** [comment]
Looking quickly at makefile most (every ?) of deps are go project that are `go get`. (gocovmerge is used but not go get, we should fix this). But we could still list them in `CONTRIBUTING.md` at least to give credits and explain for what we use them.

**Comment by sapk** [comment]
And looking at #2194 ref. I think this PR is mostly for inkscape/convert/... new deps.

**Comment by lafriks** [comment]
@sapk not only, for development there is also make and golang dependency ;)

**Comment by silverwind** [comment]
I think these are all that are not pulled via `go get`:

git, gocovmerge, lessc, inkscape, ImageMagick, zopflipng

Can gocovmerge be installed via `go get`, by the way?

**Comment by sapk** [comment]
I have done a PR to fix gocovmerge. Lessc is based on a go version that is go get.
