### ISSUE TITLE
Incorrect path to issue template file on windows

### ISSUE THREAD

**Issue by crackedmind** [go-gitea/gitea#21987]
### Description

after choosing template from the list issue body is empty, because template query parameter is wrong

`?template=.gitea%5cISSUE_TEMPLATE%5cbug.md` instead of `?template=.gitea%2fISSUE_TEMPLATE%2fbug.md`

Manual fixing %5c to %2f in url helps

### Gitea Version

1.18-rc1

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

Windows

### How are you running Gitea?

From official gitea-1.18.0-rc1-windows-4.0-amd64.exe

### Database

SQLite

**Comment by KazzmanK** [comment]
Looks similar to [21632](https://github.com/go-gitea/gitea/issues/21632)

**Comment by zeripath** [comment]
Likely regression of #21639.

Paths in Git are always '/' separated.
