### ISSUE TITLE
The sidebar tag list is out of sync with the top Git tag data

### ISSUE THREAD

**Issue by rumosky** [go-gitea/gitea#21995]
### Description

I use `git clone --bare` and `git push --mirror` to migrate repo. I found data in the sidebar tag list, but no data at the top Git tag.
And I just create a tag named test, and push it to the Gitea. Then I delete the test tag. Here are the logs.

[xorm.log](https://github.com/go-gitea/gitea/files/10128967/xorm.log)
[gitea.log](https://github.com/go-gitea/gitea/files/10128965/gitea.log)
[router.log](https://github.com/go-gitea/gitea/files/10128966/router.log)

### Gitea Version

1.17.3

Docker  Server Version: 20.10.17

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

https://github.com/go-gitea/gitea/files/10128966/router.log
https://github.com/go-gitea/gitea/files/10128965/gitea.log
https://github.com/go-gitea/gitea/files/10128967/xorm.log

### Screenshots

![image](https://user-images.githubusercontent.com/41993388/204945982-b1f3ab3f-66dc-48db-aadb-8a644820d309.png)
![QQ截图20221201105309](https://user-images.githubusercontent.com/41993388/204957886-19b9da25-32ef-44b1-b6cd-7aac7609f3d9.png)

### Git Version

2.36.2

### Operating System

CentOS 7.9

### How are you running Gitea?

Docker

### Database

MySQL

**Comment by rumosky** [comment]
I used docker to install the latest version of Gitea, built a new warehouse and pushed the code. I still have the above BUG. Here is the log for this time.


Gitea version: 1.18.0+rc1

**Comment by lunny** [comment]
Is this still a problem?

**Comment by rumosky** [comment]
> Is this still a problem?

no, It's already resolved
