### ISSUE TITLE
Build packages on OBS

### ISSUE THREAD

**Issue by tboerger** [go-gitea/gitea#22]
In order to make it quite easy to install gitea I would suggest to start a project on http://build.opensuse.org, that way we are able to build packages for all major distributions inlcuding an update channel. Currently it supports these distributions:

* SUSE
* ~~Arch Linux~~
* Debian
* Redhat
* Mandriva
* Ubuntu

We just need to build proper ```.spec``` and ```control``` files, the build service will do the rest.

**Comment by lunny** [comment]
Sounds like a good idea.

**Comment by tboerger** [comment]
We can skip Arch Linux on this list as it is already or will be directly maintained on AUR.

**Comment by HLFH** [comment]
@tboerger Why skip ArchLinux? The [AUR link is Gogs](https://aur.archlinux.org/packages/gogs/) and there is no AUR package for gitea. I remind that gitea has wiki support https://github.com/go-gitea/gitea/pull/81 and not gogs. We need an AUR package for gitea, so we could easily migrate from gogs to gitea.

**Comment by tboerger** [comment]
@HLFH because arch will be done directly within AUR, no need for the open buildservice. Directly after the release of gitea @fanningert will create gitea packages within AUR for sure.

**Comment by lunny** [comment]
Does this feature should be completed in v0.7? @tboerger

**Comment by tboerger** [comment]
I would stick with packager until ich can fix some things on OBS. So let's close that for now.

**Comment by fanningert** [comment]
@HLFH and everyone else.
Don't forget that ArchLinux changed the repository of AUR package to GIT. I will update the documentation for gogs when I have time. I reserved the package names for gitea in the meantime.

**gogs**
https://aur4.archlinux.org/packages/gogs/
https://aur4.archlinux.org/packages/gogs-git/
https://aur4.archlinux.org/packages/gogs-git-dev/

**gitea**
https://aur4.archlinux.org/packages/gitea/
https://aur4.archlinux.org/packages/gitea-git/
https://aur4.archlinux.org/packages/gitea-git-dev/

**Comment by tboerger** [comment]
@fanningert AWESOME!
