### ISSUE TITLE
Configurable minimum password length requirement

### ISSUE THREAD

**Issue by jhasse** [go-gitea/gitea#220]
In order to discourage the use of insecure passwords, I would like to set a minimum password length requirement.

Original Gogs issue: https://github.com/gogits/gogs/issues/3135

**Comment by denji** [comment]
realistic password strength estimation: https://github.com/dropbox/zxcvbn
* https://blogs.dropbox.com/tech/2012/04/zxcvbn-realistic-password-strength-estimation/

**Comment by bkcsoft** [comment]
@denji not exacly relevant. Also given Dropbox [track record](https://www.troyhunt.com/the-dropbox-hack-is-real/) their advice is the _last_ I'd listen too 😆

**Comment by Bwko** [comment]
This got fixed by #223
