### ISSUE TITLE
Convert the multiple docker pipelines to one that uses buildx

### ISSUE THREAD

**Issue by techknowlogick** [go-gitea/gitea#22009]
### Feature Description

The current state of the pipelines that run docker, are that there are two. One that runs on amd64, and another that runs on aarch64. This requires us to ensure we have hardware available for both arches.

This ticket is to swap the multiple pipelines to use one that builds for multiple arches using https://github.com/thegeeklab/drone-docker-buildx (note: @techknowlogick will need to add this docker image to the privileged list in drone). This would allow us to reduce the need for specialized hardware for build alternative arches for docker images (perhaps we could finally add armv6 as a target arch for our images)

Expected result: PRs would continue having a dryrun for both docker images (root and rootless) built for aarch64, tags would build/publish for both arches with the expected docker image tags (the ones that are autogenerated right now from the plugins/docker drone plugin), and main/release branches would continue to build/publish for their expected `xyz-dev` docker images. The MVP for published images would be to continue the aarch64/amd64 arch, and we can add more later.

**Comment by KN4CK3R** [comment]
I would like to see an official armv6 docker image then to support all 32bit raspberry pi devices.
