### ISSUE TITLE
Update cron.update_mirrors doesn't work

### ISSUE THREAD

**Issue by oDinZu** [go-gitea/gitea#22005]
### Description

In my `app.ini` I change from `@daily 10m` to `@weekly 0 0 0 * * 0` and restart Gitea, but the cron schedule on the user interface doesn't update and stays at 10m time intervals. This creates bandwidth issues and hogs CPU resources. 

I tested `@weekly 0 0 0 * * 0`,`0 0 0 * * 0`, `@midnight`, ... but everything I change doesn't update anything. 

is `[cron.update_mirrors]` correct? 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Update mirrors
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
[cron.update_mirrors]
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
SCHEDULE = 0 0 0 * * 0
;; Enable running Update mirrors task periodically.
;ENABLED = true
;; Run Update mirrors task when Gitea starts.
;RUN_AT_START = false
;; Notice if not success
;NOTICE_ON_SUCCESS = false
;; Limit the number of mirrors added to the queue to this number
;; (negative values mean no limit, 0 will result in no result in no mirrors being queued effectively disabling pull mirror updating.)
PULL_LIMIT=75
;; Limit the number of mirrors added to the queue to this number
;; (negative values mean no limit, 0 will result in no mirrors being queued effectively disabling push mirror updating)
PUSH_LIMIT=75

### Gitea Version

1.16.6

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

I compiled it myself.

### Database

None

**Comment by zeripath** [comment]
Gitea 1.16 is very old - upgrade to at least 1.17.

**Comment by csharpee** [comment]
1.16.6 isn't that old.

**Comment by lunny** [comment]
> ### Description
> In my `app.ini` I change from `@daily 10m` to `@weekly 0 0 0 * * 0` and restart Gitea, but the cron schedule on the user interface doesn't update and stays at 10m time intervals. This creates bandwidth issues and hogs CPU resources.
> 
> I tested `@weekly 0 0 0 * * 0`,`0 0 0 * * 0`, `@midnight`, ... but everything I change doesn't update anything.
> 
> is `[cron.update_mirrors]` correct? ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;; ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;; ;; Update mirrors ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;; [cron.update_mirrors] ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;; ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;; SCHEDULE = 0 0 0 * * 0 ;; Enable running Update mirrors task periodically. ;ENABLED = true ;; Run Update mirrors task when Gitea starts. ;RUN_AT_START = false ;; Notice if not success ;NOTICE_ON_SUCCESS = false ;; Limit the number of mirrors added to the queue to this number ;; (negative values mean no limit, 0 will result in no result in no mirrors being queued effectively disabling pull mirror updating.) PULL_LIMIT=75 ;; Limit the number of mirrors added to the queue to this number ;; (negative values mean no limit, 0 will result in no mirrors being queued effectively disabling push mirror updating) PUSH_LIMIT=75
> 
> ### Gitea Version
> 1.16
> 
> ### Can you reproduce the bug on the Gitea demo site?
> No
> 
> ### Log Gist
> _No response_
> 
> ### Screenshots
> _No response_
> 
> ### Git Version
> _No response_
> 
> ### Operating System
> _No response_
> 
> ### How are you running Gitea?
> I compiled it myself.
> 
> ### Database
> None

Please ensure Gitea read the correct app.ini (you changed).

**Comment by csharpee** [comment]
This was the issue @lunny; I found another config in */etc/gitea/app.ini*. 

Whoops, I should of looked at my Gitea configuration file first. I don't know why I didn't look at this to begin with.. :smiling_face_with_tear: 

Thank you Lunny :heart:
