### ISSUE TITLE
Language statistics percentages don't add up to 100%

### ISSUE THREAD

**Issue by hr-98** [go-gitea/gitea#22023]
### Description

This is probably just a rounding bug, but it is still a little bit frustrating when you notice it.
As you can see from the screenshot, the percentages are
COBOL 45.7%
Assembly 43.2%
Shell 5.9%
Ruby 5.3%
which is 100.1% in total.

I've made a copy of my repo here:
https://try.gitea.io/hr98/aoc22-copy-percentage-bug

### Gitea Version

Gitea version 1.17.3 built with GNU Make 4.1, go1.18.7 : bindata, sqlite, sqlite_unlock_notify

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

![image](https://user-images.githubusercontent.com/119700815/205487775-cbe9a345-8824-4245-b035-c676252547c9.png)

### Git Version

git version 2.31.1

### Operating System

Linux

### How are you running Gitea?

Downloaded the binary and running as systemd service on Alma Linux 9.

### Database

SQLite

**Comment by eeyrjmr** [comment]
This is more than likely due to rounding to 1decimal place. 
changing it to 2dp would slightly improve it but I doubt this will truly ever be solved due to how floats work and all you need is the perfect combination of odd-count languages detected and odd-count files counted for it to manifest itself at some decimal position

**Comment by hr-98** [comment]
There are different things you can do to avoid such problems, like the largest remainder methods.
I might try implementing it to where ever it generates the stats later, I've just never used go before.

**Comment by delvh** [comment]
Then please have a look at `models/repo/language_stats.go#44-67`.
