### ISSUE TITLE
Dead websites

### ISSUE THREAD

**Issue by gagath** [go-gitea/gitea#2202]
- Gitea version (or commit ref): N/A
- Git version: N/A
- Operating system: N/A
- Database (use `[x]`): N/A
- Can you reproduce the bug at https://try.gitea.io: N/A
- Log gist: N/A

## Description

A lot of Gitea-related websites are down:

- ~https://drone.gitea.io/go-gitea/gitea (No response)~
- https://try.gitea.io/ (No response)
- ~https://gitea.io/ (Cloudflare Always Online response)~

**Comment by geek1011** [comment]
I have put a copy of the docs on my server for now: https://docs.gitea.io.geek1011.net if anyone wants them. Also, for people who want to build gitea, clone the github repository into $GOPATH/code.gitea.io/gitea

**Comment by jonasfranz** [comment]
> I have put a copy of the docs on my server for now: https://docs.gitea.io.geek1011.net if anyone wants them.

@geek1011 Your link returns `404 page not found`

**Comment by pgaskin** [comment]
oops. I will need to fix that, it was working fine yesterday.

**Comment by pgaskin** [comment]
## I have set up a clone of the whole site here: https://gitea.tk

**Comment by jonasfranz** [comment]
@geek1011 gitea.tk seems down for me.

**Comment by pgaskin** [comment]
@JonasFranzDEV Not anymore, I was just doing maintenance.

**Comment by pgaskin** [comment]
## [docs.gitea.io](https://docs.gitea.io) and [blog.gitea.io](https://docs.gitea.io) are now up again

**Comment by lunny** [comment]
We are working on this.

**Comment by pgaskin** [comment]
## [code.gitea.io](https://code.gitea.io) and [gitea.io](https://gitea.io) are now up again

**Comment by bkcsoft** [comment]
## [lgtm](https://lgtm.gitea.io) up again

**Comment by bkcsoft** [comment]
## [drone](https://drone.gitea.io/go-gitea/gitea) is temporarily up, need to check server-loads

**Comment by jonasfranz** [comment]
coverage.gitea.io is offline so ervy buiild will fail.

**Comment by sentabi** [comment]
dl.gitea.io still down

**Comment by lunny** [comment]
Now all the services up!

**Comment by IzzySoft** [comment]
First: Glad to read all is up again! Is it permitted to ask what had brought things down?

**Comment by lunny** [comment]
We have been sponsored by Digital Ocean but it's not any more. We have a new sponsor now.

**Comment by IzzySoft** [comment]
Thanks for the prompt reply – and glad to read you've got a (new) sponsor (and are not "left in the dark"). :+1: – and keep up the good work – while we keep spreading the word :stuck_out_tongue_winking_eye:

**Comment by vintprox** [comment]
I noticed dl.gitea.io, discourse.gitea.io, drone.gitea.io can be reached anyway. But looks like gitea.io, docs.gitea.io and try.gitea.io frequently disappear. Assuming possible cause is blocking in Russia where I live.
