### ISSUE TITLE
Firefox hangs when loading page while login has expired

### ISSUE THREAD

**Issue by fhuberts** [go-gitea/gitea#22036]
### Description

I resumed my Fedora 37  x64 laptop this morning after a weekend, reloaded the Gitea 1.17 page and Firefox 107 hung.
It appeared that my login had expired.
I had to kill Firefox and restart it to see that.

### Gitea Version

1.17 (Git 56716f583)

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

git-2.38.1-1.fc37.x86_64

### Operating System

Fedora Linux x64

### How are you running Gitea?

Packaged it myself
https://gitlab.com/fhuberts/rpmsUpstream/-/tree/master/fedora/gitea

### Database

PostgreSQL

**Comment by wxiaoguang** [comment]
A browser should never hang/die, whatever the page does. So it could be a firefox bug.

**Comment by silverwind** [comment]
Check the console for any errors. If Firefox hangs, it usually offers a option to kill the JS thread, maybe then, an error is visible in the console.

**Comment by wxiaoguang** [comment]
No more clues, and according to "A browser should never hang/die, whatever the page does.", I think we can close this issue.

If there is a Gitea bug, feel free to reopen or open a new issue.
