### ISSUE TITLE
Import from Confluence

### ISSUE THREAD

**Issue by ivptr** [go-gitea/gitea#22038]
### Feature Description

It would be nice to be able to import content from Confluence to Gitea Wiki.

**Comment by lafriks** [comment]
This should definitely be done using external tool. Our wiki uses markdown while confluence uses html with special tags for components

**Comment by silverwind** [comment]
AFAIK, Confluence does support Markdown input but still converts everything to incompatible HTML when saving, so it's definitely not going to be easy to parse that.

**Comment by lafriks** [comment]
I will close this as this should be done outside gitea and if there is no already available Golang library to convert confluence html to markdown I don't see this implemented

**Comment by ivptr** [comment]
Found PHP script to convert Confluence to Markdown and it seems to be working nice:
https://gist.github.com/grugnog/2e6ee420707a8196951956cf4dbf6e91

It creates Git repo having .md files in root directory and "files" directory containing images.

Those could be committed directly to repo.wiki.git.

Just need to be able to [add images to Wiki](https://github.com/go-gitea/gitea/issues/17231) first.
