### ISSUE TITLE
Running `docker` commands against Gitea registry results in a call against `ROOT_URL`

### ISSUE THREAD

**Issue by scubbo** [go-gitea/gitea#22033]
### Description

See [this repo](https://github.com/scubbo/possible-gitea-bug) - when running `docker` commands (`docker login`, `docker pull`, etc.) against a registry, a call is made against the server's `ROOT_URL`. If there is no server available at the `ROOT_URL`, this will result in an error. This can result in issues when the `ROOT_URL` refers to the public domain name of the Gitea service, but an image provided by the registry that is a prerequisite for setting up the public domain name is referenced by an internal domain name.

### Gitea Version

Gitea version 1.18.0+rc1 built with GNU Make 4.3, go1.19.3

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

Kubernetes in the original situation; docker-compose in the minimal reproduction.

### Database

None

**Comment by KN4CK3R** [comment]
You set ROOT_URL to something non-existing. Why should that work?

**Comment by scubbo** [comment]
> You set ROOT_URL to something non-existing. Why should that work?

Naïvely, for operations that do not require Gitea knowing it's own URL (like generating a `git clone` link), there's no reason to think that it _wouldn't_. Sure, a non-existent `ROOT_URL` is clearly not *correct* - but it's surprising that it results in breakages of APIs that appear to have nothing to do with the `ROOT_URL` itself.

That said, your explanation of the authentication mechanism makes it clear why this behaviour happens, and why addressing it would not be desirable. Thanks for the explanation!

**Comment by scubbo** [comment]
Basically I was looking for [Multi-domain support](https://github.com/go-gitea/gitea/issues/19345).
