### ISSUE TITLE
gitea on MacOS X (homebrew build) unable to resolve tailscale *.ts.net names

### ISSUE THREAD

**Issue by jum** [go-gitea/gitea#22035]
### Description

My Gitea instance on MacOS X (homebrew build) is unable to resolve tailscale *.ts.net names. I wanted to make internal hooks all reachable via the tailscale private net only, and allthough  I am able to curl the hook URL successfully on the same host, the gitea binary build is not able to resolve that address.

### Gitea Version

1.17.3

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

Delivery: Post "https://myhost.tailXXXXX.ts.net/giteahook": dial tcp: lookup myhost.tailXXXXX.ts.net on 192.168.178.1:53: no such host

### Screenshots

Delivery: Post "https://myhost.tailXXXXX.ts.net/giteahook": dial tcp: lookup myhost.tailXXXXX.ts.net on 192.168.178.1:53: no such host

The IP number is the IP number of my DSL router, but I have also tailscale with magic DNS running, and all other services appear to pick name resolution via the OS X native DNS resolver to map the tailscale network.

### Git Version

2.24.3 (Apple Git-128)

### Operating System

MacOS X Catalina

### How are you running Gitea?

I am running the homebrew build of gitea as a server via a launchd plist file.

### Database

PostgreSQL

**Comment by silverwind** [comment]
Check if other golang applications can resolve, I imagine this is not an issue related to gite application code.

**Comment by techknowlogick** [comment]
> So my question here: would it be possible to make the build homebrew uses cgo or do I have to build it myself?

The build homebrew uses is built with CGO so that sqlite works, although netdns is overridden the tag `netgo` is set.

Not that it likely matters, but for debugging sake are you using an M1/2 device or an amd64 mac?

**Comment by techknowlogick** [comment]
Good news, I reached out to tailscale and they provided some insight. This is due to an interaction between go and macOS, but will be fixed in go 1.20. Depending on your timelines you may need to build Gitea with the alternate options until that version of go is released. I'll close this ticket now as there is nothing we can do except wait for the new go version to release.

Source: https://twitter.com/bradfitz/status/1600364606022889473
