### ISSUE TITLE
Ticking a big file as viewed in review make page scroll too far

### ISSUE THREAD

**Issue by kenji21** [go-gitea/gitea#22047]
### Description

Ticking a big file as viewed in review make page scroll too far

### Screenshots

A video is better to explain this issue (the next file to review disappear when ticking current one) :

https://user-images.githubusercontent.com/1105089/205871381-1ad81449-ba5e-4914-a779-052570d82aae.mov

Before ticking fixture_generation.go from  https://try.gitea.io/kenji21/test/pulls/1/files:
<img width="1160" alt="Screenshot 1" src="https://user-images.githubusercontent.com/1105089/205873382-263a0b15-5bc3-4015-962f-0afbc9f21931.png">

Then I expect to see the start of fixture_test.go, but I got the last lines of this file:

<img width="1170" alt="Screenshot 2" src="https://user-images.githubusercontent.com/1105089/205873370-24fab131-496e-49c9-a28c-d5822f6f8eb7.png">

### Gitea Version

1.17.3

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

macOS

### Browser Version

Safari 16

**Comment by wxiaoguang** [comment]
Is there still  a problem on try.gitea.io ? The code has been improved a lot.

**Comment by delvh** [comment]
I think yes, I distantly remember encountering it myself on gitea.com

**Comment by wxiaoguang** [comment]
I can't reproduce it on https://try.gitea.io/kenji21/test/pulls/1/files at the moment.

The scrollbar doesn't scroll that far 🤔

**Comment by wxiaoguang** [comment]
@delvh do you mean that there is still a bug? I do not know how to reproduce it on try.gitea.io
