### ISSUE TITLE
Test email failing with could not send email 1: missing port in address

### ISSUE THREAD

**Issue by EmilyNerdGirl** [go-gitea/gitea#22040]
### Description

Trying to send a test mail with the following configuration using my Google apps hosted domain and the Test email option, and keep getting `Failed to send a testing email to 'REMOVED: gomail: could not send email 1: missing port in address`

Here's the app.ini config:
```
[mailer]
IS_TLS_ENABLED = true
USER           = git@MYGOOGLEAPPSDOMAIN
ENABLED        = true
PASSWD         = xxx
SMTP_ADDR      = smtp.gmail.com
MAILER_TYPE    = smtp
SMTP_PORT      = 465
FROM           = git@MYGOOGLEAPPSDOMAIN
HELO_HOSTNAME  = MYGOOGLEAPPSDOMAIN
PROTOCOL       = smtps
```

Thanks!

### Gitea Version

1.17.3

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

Running inside Kubernetes in a K3s instance deployed with the official Helm chart

### Database

MySQL

**Comment by tahaghafuri** [comment]
You Can User SMTP(Port:25) Without SSL/TLS,I'm Don't Problem To Send Mails.

**Comment by quinndiggity** [comment]
https://docs.gitea.io/en-us/config-cheat-sheet/#mailer-mailer

```
⚠️ This section is for Gitea 1.18 and later. If you are using Gitea 1.17 or older, please refer to [Gitea 1.17 app.ini example](https://github.com/go-gitea/gitea/blob/release/v1.17/custom/conf/app.example.ini) and [Gitea 1.17 configuration document](https://github.com/go-gitea/gitea/blob/release/v1.17/docs/content/doc/advanced/config-cheat-sheet.en-us.md)
```

```
SMTP_ADDR: <empty>: Mail server address. e.g. smtp.gmail.com. For smtp+unix, this should be a path to a unix socket instead. Before 1.18, this was combined with SMTP_PORT under the name HOST.
```

```
SMTP_PORT: <empty>: Mail server port. If no protocol is specified, it will be inferred by this setting. Common ports are listed below. Before 1.18, this was combined with SMTP_ADDR under the name HOST.

    25: insecure SMTP
    465: SMTP Secure
    587: StartTLS
```

since you are on `1.17.3`, try explicitly setting `HOST` instead:
```
;; Mail server
;; Gmail: smtp.gmail.com:587
;; QQ: smtp.qq.com:465
;; As per RFC 8314 using Implicit TLS/SMTPS on port 465 (if supported) is recommended,
;; otherwise STARTTLS on port 587 should be used.
;HOST =
```

`HOST = smtp.gmail.com:465`

**Comment by quinndiggity** [comment]
> You Can Use SMTP(Port:25) Without SSL/TLS,I'm Don't Problem To Send Mails.

@tahaghafuri , one could also not send mail at all, but that doesn't solve anything - recommending that someone disable encryption, particularly with use of a remote server, is the equivalent of telling someone that they should cut off their legs to resolve a hangnail. Terrible advice to give - fix the problem; don't disable, or recommend that someone disable, necessary security-related settings.

**Comment by eloebl** [comment]
> `HOST = smtp.gmail.com:465`

Thank you! I swore I checked the notes first, but missed it was `HOST` when I added the port in one of my tests.
