### ISSUE TITLE
500 error in web ui when trying to view commit with ~1600 deleted files

### ISSUE THREAD

**Issue by DjKlazaplaza** [go-gitea/gitea#22057]
### Description

Have a large commit with minor changes to some files and around 1600 files deleted. This does not render in the web ui, I get a 500 error. Debug logs says the following:

2022/12/07 09:34:47 ...s/context/context.go:232:HTML() [E] [63905e37] Render failed: template: repo/diff/section_split:62:30: executing "repo/diff/section_split" at <$section.GetComputedInlineDiffFor>: error calling GetComputedInlineDiffFor: runtime error: slice bounds out of range [:-1]
2022/12/07 09:34:47 ...s/context/context.go:219:HTML() [D] [63905e37] Template: status/500

### Gitea Version

1.17.1

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

2.34.1

### Operating System

Ubuntu 22.04.1 LTS

### How are you running Gitea?

Downloaded binary and running as a service. Based on this guide: https://linuxize.com/post/how-to-install-gitea-on-ubuntu-20-04/

### Database

SQLite

**Comment by HackerDaGreat57** [comment]
Make a backup of **everything** and then try running it with the [latest version](https://dl.gitea.io/gitea/1.18.0).

**Comment by wxiaoguang** [comment]
The diff code has been rewritten by #19958, I think the "slice bounds out of range [:-1]" panic should have been fixed.

If there is still any problem, feel free to reopen.
