### ISSUE TITLE
duo-labs/webauthn Deprecated

### ISSUE THREAD

**Issue by kdumontnu** [go-gitea/gitea#22052]
### Description

https://github.com/duo-labs/webauthn#this-library-is-deprecated

For future support looks like we should migrate to https://github.com/go-webauthn/webauthn

There's a [migration guide here](https://github.com/go-webauthn/webauthn/blob/master/MIGRATION.md).

### Gitea Version

main

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

N/A

### Database

None

**Comment by Saklad5** [comment]
Keep this in mind if you're migrating WebAuthn: https://github.com/go-gitea/gitea/issues/22015
