### ISSUE TITLE
Migrations bug

### ISSUE THREAD

**Issue by Bwko** [go-gitea/gitea#2206]
When migrating from gogs db version 16 the following happens:

Migrate [v37.go](https://github.com/go-gitea/gitea/blob/master/models/migrations/v37.go#L19) uses the latest `models.User`. Some of the `models.User` columns do not exists, like `keep_email_private`. Resulting in the following error: `ERROR:  column "keep_email_private" does not exist`. 

After all migrations are done xorm "magically" creates the missing columns. 

**Solutions:** 

1. Let xorm create all of the missing columns before the migrations. 
2. Only select the columns you need, in this case `id & full_name` 
3. Always add migrations for new columns

**Comment by lafriks** [comment]
I think 3 is must and if does not have migration, this should be fixed

**Comment by lunny** [comment]
@andreynering has contributed `https://github.com/go-xorm/xorm/tree/master/migrate`. Maybe we can change the migrations method to that?

**Comment by Bwko** [comment]
I'd like option 1.
Xorm automatically  creates all the columns and I don't see any reason why xorm can't create the columns before migrating.

**Comment by bkcsoft** [comment]
@lunny If we switch to that we'll loose all hopes of migrating from Gogs to Gitea in the future

**Comment by lafriks** [comment]
@Bwko that can make problems if you are upgrading from version where later column has been added to structure and in later removed and there is migration that converts it data to either other column or table for example

**Comment by lunny** [comment]
@lafriks yes, but that's a bug.

**Comment by andreynering** [comment]
If we use the Xorm migrate package, even them we would have to keep existing migrations for a while. Also, this don't solve the migration from Gogs problem.

Also keep in mind it is not as stable as [the Gorm version](https://github.com/go-gormigrate/gormigrate) since it don't have recent fixes, etc.

There's no easy solution for this.

**Comment by Bwko** [comment]
@lafriks  You're right, then we need to go for solution 3

**Comment by sondr3** [comment]
I was just bit by this issue, and can't upgrade one of my older Gogs instances to the new Gitea 1.2-rc1.

**Comment by strk** [comment]
@lunny if this bug prevents upgrading from Gogs it should be considered of upmost importance, why postponing fix to 1.3.0 ? Maybe I misunderstood the severity and db 16 is not a supported Gogs version ?

**Comment by sondr3** [comment]
I was upgrading from `Gogs version 0.9.48.0722`, but I can't tell from the Upgrading from Gogs info on the docs whether it's supported or not. It's not a major hassle for me, it was literally hosting a single repo but wanted to let you know.

**Comment by strk** [comment]
From docs:

> Gogs versions up to 0.9.146 (db schema version 15) can be smoothly upgraded to Gitea.

So yes, it should be supported
