### ISSUE TITLE
Public Repo, Private Code

### ISSUE THREAD

**Issue by FrostKiwi** [go-gitea/gitea#22074]
### Feature Description

I would like to set every aspect of a Repo Public, except the code and the ability to git clone it.
Use-case:
Being at an international company, code is under export restriction and cannot be published without prior green lighting. So it must remain private. But I still want international colleagues to be able to send in issues, collab on their resolution and have the Wiki public to any guest.
I can of course create two separate repos, once for private code and one for public issues and the Wiki. But I am not aware of Gitea being able to set this up in a single Repo.

Thus this is my feature request:
One Repo, Private Code Tab, Public Issue tracker + Wiki.

**Comment by techknowlogick** [comment]
Closing as dupe of https://github.com/go-gitea/gitea/issues/3217

**Comment by techknowlogick** [comment]
@FrostKiwi i may have been thinking of those other tickets. Sorry for prematurely closing this ticket, I've reopened it.

**Comment by lafriks** [comment]
Would be nice to have ability to be set parts of repo public (also packages for example)

**Comment by lightr4in** [comment]
For instance, Gitlab offers an options section to set the permissions for each unit separately:

![part of Gitlab's permissionspage](https://user-images.githubusercontent.com/120530289/207471740-e78c932f-6b95-40f1-9b3c-914b5724eb4e.png) 

But this might be something for an extra issue.

**Comment by FrostKiwi** [comment]
> Should the title be changed as private repo, public code? What's the different between them?

My use case within an international is the exact opposite. I want everything public for easiest collaboration, except code due to export border regulations.

Of course if a name change is desired, then I guess we could go along the lines of @lightr4in suggestion https://github.com/go-gitea/gitea/issues/22074#issuecomment-1350145371 and rename the issue to a variant of "More in-depth privacy controls" or something along those lines...

**Comment by bendem** [comment]
Gitea already has everything for this, it would "just" work (tm) if public access was evaluated as another "team".
![image](https://user-images.githubusercontent.com/2681677/217470179-f68e19a8-c016-4304-ae38-2db2a0e34370.png)

**Comment by FrostKiwi** [comment]
@delvh Is it within the realm of possibility, that this gets into [v1.20](https://github.com/go-gitea/gitea/issues/23072)?

**Comment by delvh** [comment]
If I'm not mistaken, the corresponding PR by @lunny has already been merged to disable the code tab while enabling the issue tracker.
It doesn't mean that you can make only parts of a repo public, but you can have a repo where users cannot see the code.
At least for the short and medium term, this seems like the best and easiest solution to me.

**Comment by lunny** [comment]
What's `Public` and `Private`? I think both concepts are for the anonymous users in a login-free Gitea instance or non-owners/non-members/non-collaborators of the repository in a login-required Gitea instance. So maybe we need one or two default roles for them.

**Comment by FrostKiwi** [comment]
> If I'm not mistaken, the corresponding PR by @lunny has already been merged to disable the code tab while enabling the issue tracker. It doesn't mean that you can make only parts of a repo public, but you can have a repo where users cannot see the code at all. At least for the short and medium term, this seems like the best and easiest solution to me.

Are you referring to this checkbox?
![image](https://github.com/go-gitea/gitea/assets/60887273/b5f1104e-88fa-44e1-904a-370d385bfc86)

Does this mean I can finally set the code to be invisible to all, except those chosen as Collaborators?

**Comment by a1012112796** [comment]
I think we can define a special user named as `@anyone` (or other name), all users and unlogin users will have all permssions that you permit `@anyone`.

**Comment by lunny** [comment]
No, it means nobody could visit code

**Comment by FrostKiwi** [comment]
> No, it means nobody could visit code

Ohh, that's not what I need for my use-case of allowing colleagues to comment on issues and allow them them to read the wiki, without violating export restrictions. I still need a separate "Repo for Collaboration", where I copy paste everything to and from.

Maybe a bit of a pipe dream to expect Gitea to handle it all, Gitea has already the ability to use external issue trackers and wiki, so maybe it's high time I stop depending on Gitea and use third party packages for those...

**Comment by moritz-h** [comment]
> ~Closing as dupe of #3217~
> 
> Edit: Wrong issue, one moment while I find the correct issue.

Duplicate of #639?

**Comment by FrostKiwi** [comment]
> > ~Closing as dupe of #3217~
> > Edit: Wrong issue, one moment while I find the correct issue.
> 
> Duplicate of #639?

Indeed, that is the same issue. Failed to find it when opening up this one...

**Comment by FrostKiwi** [comment]
Closed in favor of https://github.com/go-gitea/gitea/issues/639#issuecomment-1628261632 , since that discussion predates this one.
