### ISSUE TITLE
Gitea Pages

### ISSUE THREAD

**Issue by ShalokShalom** [go-gitea/gitea#2208]
You can provide Gitea pages, together with Caddy, a Go alternative to Apache and Nginx.

https://caddyserver.com/docs/http.git
https://caddyserver.com/

**Comment by bkcsoft** [comment]
Duplicate of https://github.com/go-gitea/gitea/issues/302

**Comment by bkcsoft** [comment]
And if not of that, then https://github.com/go-gitea/gitea/issues/1721
