### ISSUE TITLE
Stop using .io Domain

### ISSUE THREAD

**Issue by flynnnnnnnnnn** [go-gitea/gitea#22086]
### Feature Description

.io domains are used by colonial Britan to steal money rightfully owed to the islanders that were forcibly exiled. Please redirect all your traffic from the .io domain to a different domain to not support the exiling of these peoples. If you don't care about the ongoing plight of the exiled islanders there is a performance and search engine problem of using the .io domain.

https://en.wikipedia.org/wiki/.io#Controversy
https://old.gigaom.com/2014/06/30/the-dark-side-of-io-how-the-u-k-is-making-web-domain-profits-from-a-shady-cold-war-land-deal/
https://web.archive.org/web/20171113150544/https://getstream.io/blog/stop-using-io-domain-names-for-production-traffic/

**Comment by eeyrjmr** [comment]
https://www.gov.uk/government/publications/foi-release-administration-of-io-domain

`FOI ref 0347-15 explains that there is no agreement between the UK government and Internet Computer Bureau (ICB) regarding the administration of the .io domain and that neither the UK government nor the BIOT administration receives revenue from the sale of .io domains, which are administered independently by the ICB.`
