### ISSUE TITLE
CreatePost: initRepository: updateRepository: update: pq: duplicate key value violates unique constraint "UQE_repository_s"

### ISSUE THREAD

**Issue by cosoc** [go-gitea/gitea#22085]
### Description

When creating a warehouse and setting the warehouse description, 

### Gitea Version

gitea-1.17.3-linux-amd64

### Log Gist

```
...ers/web/repo/repo.go:194:handleCreateError() [E] CreatePost: initRepository: updateRepository: update: pq: duplicate key value violates unique constraint "UQE_repository_s"
```

### How are you running Gitea?

shell run

```
./gitea
```

### Database

PostgreSQL

**Comment by wxiaoguang** [comment]
The bug:
* Repo exists in database but doesn't exist on filesystem, then creating with the existing repo name (in database) will lead to this error.

Workaround: 
* Delete the repo manually first
