### ISSUE TITLE
Can't transfer repository owned by organization

### ISSUE THREAD

**Issue by lfkeitel** [go-gitea/gitea#2209]
- Gitea version (or commit ref): 1.1.2
- Git version: 2.7.4
- Operating system: Ubuntu 14.04.5 LTS
- Database:
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X] No
  - [ ] Not relevant
- Log gist:

2017/07/24 15:31:03 [...ters/repo/setting.go:277 SettingsPost()] [E] TransferOwnership: removeOrgRepo: database table is locked
2017/07/24 15:31:03 [D] Template: status/500

## Description

Repositories can't be transferred out of an organization. I can transfer from my individual account into an org, but I can't transfer it back. I also can't transfer org to org. The error is happening [here](https://github.com/go-gitea/gitea/blob/v1.1.2/models/repo.go#L1304). I have another instance of Gitea where the same thing happens. I attempted to reproduce it on the try.gitea.io but couldn't get it to happen.

One instance was running Gitea 1.1.0 and I upgraded to 1.1.2 to see if it fixed it, but it didn't. The other instance was already at 1.1.2 before I tried.

**Comment by lafriks** [comment]
I think it should be fixed in master

**Comment by lfkeitel** [comment]
You are correct. I built from master and the problem is fixed. I'll go ahead an close this. We'll just use our built version until an official release is made. I should've looked harder through the commits. Thank you.
