### ISSUE TITLE
Can't create a repo with readme

### ISSUE THREAD

**Issue by mentalfl0w** [go-gitea/gitea#22097]
### Description

When I create a new repository, this error is reported as soon as I choose to create files such as readme and gitignore, but in fact signing on the server is fine and has not been a problem in previous versions.
Errors:
<img width="1251" alt="image" src="https://user-images.githubusercontent.com/30333935/206889179-a68eb1d1-1272-44e5-9fff-6be6176df291.png">
Signing in server:
<img width="825" alt="image" src="https://user-images.githubusercontent.com/30333935/206889245-0defcc0f-ff60-4849-98e1-8961ca70718c.png">

### Gitea Version

1.17.3

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

Raspberry Pi OS

### How are you running Gitea?

used the latest downloads, run from systemd.
distribution are:
```
[Unit]
Description=Gitea (Git with a cup of tea)
After=syslog.target
After=network.target
[Service]
RestartSec=2s
Type=simple
User=git
Group=git
WorkingDirectory=/home/git/
ExecStart=/home/git/gitea web --config /home/git/custom/conf/app.ini
Restart=always
Environment=USER=git HOME=/home/git GITEA_WORK_DIR=/home/git/

[Install]
WantedBy=multi-user.target
```

### Database

MySQL

**Comment by restray** [comment]
It would be great to have logs as text (in Gist)! And commands as text too! It makes debug shorter :D

**Comment by lunny** [comment]
Gitea has a separate git configuration default in `data/home/.gitconfig`.

**Comment by mentalfl0w** [comment]
> It would be great to have logs as text (in Gist)! And commands as text too! It makes debug shorter :D
> 
> I'm not able to reproduce this bug.
> 
> With or without GPG key registered. With or without a fresh repo. It seems to be a GPG issue on Raspberry, can't troubleshoot this

Thanks for reply!

**Comment by mentalfl0w** [comment]
> Gitea has a separate git configuration default in `data/home/.gitconfig`.

Thank you! Your answer helped me solve my problem! I copied the public key pair to the directory and it worked! 😊
