### ISSUE TITLE
UI: button to download code lacks tooltip

### ISSUE THREAD

**Issue by pmattern** [go-gitea/gitea#221]
- Gitea version (or commit ref): cb16028
- Git version: 2.10.2
- Operating system: Arch Linux
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite

Within those fields displaying a repository's URL which can e. g. be seen at URLs like `gitea.example.org/Someorganization/Somerepo` the button to copy comes with a tooltip while the button to download at its right doesn't.
![gitea_repo-url-missing-tooltip](https://cloud.githubusercontent.com/assets/9860801/20544552/d72abbe4-b10a-11e6-9244-e89d73ad3745.png)
Maybe this is a bit of bikeshedding but I figure the UX would be a bit more smooth if the button to download had a tooltip as well.

**Comment by strk** [comment]
Sounds like an easy change. Are you up for a PR @pmattern ?

**Comment by gencer** [comment]
@pmattern try github theme for a while. I fixed these things. Hope to see theme feature on gitea in the future. https://github.com/gencer/gitea-gihubify

![Image](https://raw.githubusercontent.com/gencer/gitea-gihubify/master/ss/13.png)

**Comment by tboerger** [comment]
> @pmattern try github theme for a while. I fixed these things. Hope to see theme feature on gitea in the future. https://github.com/gencer/gitea-gihubify

Cool, we will provide better theming support for sure, but we will never get a GitHub clone theme into the core itself, we don't want to end like https://gitbucket.github.io/gitbucket-news/gitbucket/2016/03/20/change-user-interface.html ;)

**Comment by pmattern** [comment]
@gencer 
After applying gencer/gitea-gihubify@8b80e49 upon 574e49c the problem addressed in this issue is persisting here.
Btw. files `patch{,-ext}.css` have to go to `public/*css*/`, not? Also, I wonder whether directory `ss` really isn't needed at all and whether it's unavoidable that `patch.css` is basically a single line comprising 300k characters.

@strk 
> Sounds like an easy change. Are you up for a PR @pmattern ?

Unfortunately I'm lacking both time and skills right now.

**Comment by lunny** [comment]
@pmattern, please confirm this have been resolved.

**Comment by pmattern** [comment]
Running 39d0db5 the problem is basically solved but there are two things worth having another look at, IMO:

The tooltip to copy is above that line comprising URL etc. as shown [above](https://github.com/go-gitea/gitea/issues/221#issue-191141502) while the tooltip to download is placed left of the button which is a bit inconsistent and covering parts of the URL.
![gitea_tooltip-download_left-of-button](https://cloud.githubusercontent.com/assets/9860801/20975400/b1daabd8-bc9f-11e6-9de0-adc5472a46c4.png)

More importantly string "download_archive" doesn't seem like a really good choice.

**Comment by lunny** [comment]
@hhenkel

**Comment by tboerger** [comment]
Looks like the bindata have not been updated.

And the tooltip is automatically placed like that.

**Comment by pmattern** [comment]
> And the tooltip is automatically placed like that.

Indeed the alignment seems to be independent from the current commits. Increasing the width of the browser window yields
![gitea_tooltip-download_top-of-button](https://cloud.githubusercontent.com/assets/9860801/20979061/87614874-bcab-11e6-861f-f91a796a02e5.png)
Not sure whether the underlying algorithms should be adjusted, though. When the tooltip was displayed left of the button plenty of space would have been available to have it placed top / right of that line displaying URL and so on.

**Comment by hhenkel** [comment]
![image](https://cloud.githubusercontent.com/assets/2813782/20980059/5c5e3c32-bcaf-11e6-9edb-0d06b7124e83.png)
I'm currently testing - with the position "top right" it looks like shown on my screen.

**Comment by hhenkel** [comment]
@pmattern I submitted #364 to fix this, can you test it?

**Comment by pmattern** [comment]
@hhenkel 
Running bab737b from current master the tooltip states "Download this repository" and the placement is reasonable, IMO.

Would it make sense to have the other tooltip state something like "Copy *URL*" or so, hence some kind of description like the one provided by "Download *this repository*" right now? Just wondering.

**Comment by lunny** [comment]
@pmattern, please fire another issue for `Copy URL` and I think this issue could be closed.

**Comment by tboerger** [comment]
Fixed
