### ISSUE TITLE
Ability to have vigilance mode like on GitHub

### ISSUE THREAD

**Issue by Bobby99as** [go-gitea/gitea#22134]
### Feature Description

I think it would be best if gitea had vigilance mode so contributions not pushed with a PGP key could be marked as unverified or potentially dangerous because currently it doesn't say unverified or potentially dangerous when you have a PGP key set and you don't sign your push to the repo

### Screenshots

![Screenshot (256)](https://user-images.githubusercontent.com/71202582/207647294-3b288aad-944b-4c34-93b0-c3f3c1011442.png)

**Comment by KN4CK3R** [comment]
Duplicate of #17237
