### ISSUE TITLE
clone option to directly clone into Jetbrains IDEs

### ISSUE THREAD

**Issue by dozro** [go-gitea/gitea#22149]
### Feature Description

It would be nice to have a button like the "clone to VS Code" button for the IDEs made by JetBrains. GitLab already has a feature to clone a project to IntelliJ, so it is possible, furthermore I have already made a JavaScript to add these buttons in the browser (*as seen in the screenshots section*) and they work. Nonetheless, I think this (properly implemented) would be a useful feature for many.

Why?
It would make it much easier to clone them, you basically just have to enter the directory you want to clone it to in the presenting dialogue.

Best Regards.

### Screenshots

<img width="222" alt="image" src="https://user-images.githubusercontent.com/117523783/208177628-4749d553-f962-426b-8f32-ddc3b58a034a.png">

**Comment by silverwind** [comment]
See https://github.com/go-gitea/gitea/pull/21123 for similar request. If these are additional URL protocols, they could be supported via either server- or per-user configuration, I suppose. But we can't really add every editor in existance to that dropdown.

**Comment by jolheiser** [comment]
I think a config approach would be ideal because, even to note from your screenshot, JetBrains has _way_ more IDEs than that. 😅

**Comment by silverwind** [comment]
Yeah I could see a user config section like "My Editors" where users could define URL protocol and a name for each of their editors.

**Comment by jolheiser** [comment]
Ah, I was thinking instance config, but user config could also be interesting. It would mean users could have whatever they want. 
Maybe a combination of both, even?
I think we can come up with a proper template system so people can define something like `vscode://${repo}/${file}` or something and then Gitea just fills them in accordingly (I don't know what the existing schemes look like, but just an example)

**Comment by silverwind** [comment]
Per-server would of course be easier to implement and likely sufficient initially. But ultimately it is a user preference, I think. Server-side config has the benefit that it will work for logged-out users as well.

**Comment by lafriks** [comment]
just for reference: `jetbrains://idea/checkout/git?idea.required.plugins.id=Git4Idea&checkout.repo=<repo-url>`

**Comment by dozjul** [comment]
> just for reference: `jetbrains://idea/checkout/git?idea.required.plugins.id=Git4Idea&checkout.repo=<repo-url>`

Reference for cloning to JetBrains IntelliJ (aka Idea)

**Comment by redwerkz** [comment]
This one is used for Visual Studio!? check button right here on gh 😉

git-client://clone?repo=

**Comment by silverwind** [comment]
Let's combine this into https://github.com/go-gitea/gitea/issues/21121 so we have only 1 issue for the same topic.
