### ISSUE TITLE
SSH Clone not working . gitead built-in ssh via START_SSH_SERVER = true , using snap based install.

### ISSUE THREAD

**Issue by v3ss0n** [go-gitea/gitea#22151]
### Description

- installed via snap
- enabled ssh
- add pub key
- verified pub key 
- clone via ssh

error : 

```Permission denied (publickey)```

### Gitea Version
Gitea version 1.17.3 built with GNU Make 4.1, go1.18.5 : bindata, sqlite, sqlite_unlock_notify, pam, cert

### How are you running Gitea?

Installed via Snap and enabeld ssh via

```
START_SSH_SERVER = true
SSH_DOMAIN       = git.domain.tech
DISABLE_SSH      = false
SSH_PORT         = 3322
```

### Database

None

**Comment by KazzmanK** [comment]
What kind of key are you using? How you say you have verified your key?
About month ago, I was trying to setup ssh connection and also failed until I reissued new key ssh-ed25519 instead of old RSA key. 
With new key everything worked.

**Comment by v3ss0n** [comment]
i am using RSA

**Comment by delvh** [comment]
Then both of you have probably been hit by #17798.
See there for a workaround.
