### ISSUE TITLE
Gitea grants 0750 rights to uploaded avatars

### ISSUE THREAD

**Issue by Izorkin** [go-gitea/gitea#22161]
### Description

Gitea grants 0750 rights to uploaded avatars
```
ls -lah /var/lib/gitea/data/avatars
```
```
total 316K
drwxr-xr-x  3 gitea gitea 4.0K Dec 18 13:33 .
drwxr-xr-x 13 gitea gitea 4.0K Dec 18 13:05 ..
-rwxr-x---  1 gitea gitea 301K Dec 18 13:33 11be58ba3ef76ecc7ff4664e077d5c62
drwxr-xr-x  2 gitea gitea 4.0K Dec 18 13:33 tmp
```

Required grants - ~~0650~~ 0640.

### Gitea Version

1.18-dev

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

NixOS

### How are you running Gitea?

Using gitea module in OS NixOS.

### Database

None

**Comment by zeripath** [comment]
🤦

**Comment by Izorkin** [comment]
@zeripath thanks. fixed.

**Comment by zeripath** [comment]
@Izorkin do you mean the pr fixes the problem?

It's probably better to comment on the PR directly to indicate that you think it's correct.

**Comment by Izorkin** [comment]
> @Izorkin do you mean the pr fixes the problem?

Yes, fixed my problem.
