### ISSUE TITLE
Only allowing signup via OpenID does not work

### ISSUE THREAD

**Issue by xeruf** [go-gitea/gitea#22168]
### Description

See also https://github.com/go-gitea/gitea/issues/22164

I have the following in app.ini:
```ini
[service]
DISABLE_REGISTRATION        = true

[openid]
ENABLE_OPENID_SIGNUP = true
```
Expecting that username/password signup is prohibited while OpenID is allowed.

But I get this message upon OpenID signup:

> Registration is disabled. Please contact your site administrator.

### Gitea Version

1.16.8

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

Helm Chart

### Database

PostgreSQL

**Comment by strk** [comment]
I'm pretty sure this used to work but registration needs be open as first openid-based login MUST result in a local registration, basically. I can't remember by which switch but it should be possible to forbid local-only registration and enable the openid one. There might be an openid specific ALLOW_REGISTRATION variable (or there was)

**Comment by strk** [comment]
Must be `ENABLE_OPENID_SIGNUP = true`, is that set to true as well ?

**Comment by wfjake** [comment]
I think you are thinking of `ALLOW_ONLY_EXTERNAL_REGISTRATION`. What happens if you use these settings instead?
```
[service]
ALLOW_ONLY_EXTERNAL_REGISTRATION=true

[openid]
ENABLE_OPENID_SIGNUP=true
```
