### ISSUE TITLE
Disabling basic auth does not remove login form

### ISSUE THREAD

**Issue by xeruf** [go-gitea/gitea#22164]
### Description

I have the following in my config, so people can only login via the configured OpenID-provider:
```yaml
service:                                                                                                        
  ENABLE_BASIC_AUTHENTICATION: false                                                                           
```
according to https://docs.gitea.io/en-us/config-cheat-sheet/#service-service

### Screenshots

Nonetheless, there is a username-password prompt:
<img width="613" alt="image" src="https://user-images.githubusercontent.com/13354331/208311660-ad7e2aa6-cf79-4745-b435-3095ad0c61b1.png">

### Gitea Version

Powered by Gitea Version: 1.16.8

### Can you reproduce the bug on the Gitea demo site?

No

### Browser Version

Firefox

**Comment by xeruf** [comment]
It is configured from kubernetes via the helm chart, even these lines in the app.ini change nothing:
```ini
[service]
DISABLE_REGISTRATION        = true
ENABLE_BASIC_AUTHENTICATION = false

[openid]
ENABLE_OPENID_SIGNUP = true
```

**Comment by techknowlogick** [comment]
Basic Authentication means Disable HTTP BASIC Authentication, and specifically for the API.

**Comment by xeruf** [comment]
so how do I remove email-password-signin?
