### ISSUE TITLE
Open new tab when clicking on external wiki

### ISSUE THREAD

**Issue by mxmehl** [go-gitea/gitea#2217]
When setting an external wiki in a repository, the link of the `Wiki` button should open a new tab/window instead of being opened in the same tab. 

It is common behaviour of many websites that links to external sites are either marked as such or open in a separate tab.

**Comment by cez81** [comment]
Any thoughts on whether this should be default or as a setting?

**Comment by lafriks** [comment]
I think it should be default as it opens completely site
