### ISSUE TITLE
The latest label of the gitea docker warehouse is not the latest release

### ISSUE THREAD

**Issue by lostmaniac** [go-gitea/gitea#22179]
### Description

I started using the 1.17.3 version of the image, and today I changed the latest label, but the prompt:
The database version is 183

### Gitea Version

1.17.3

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

docker

### Database

SQLite

**Comment by wxiaoguang** [comment]
Your docker registry mirror doesn't work correctly, it cached a very old image and never updated it.
