### ISSUE TITLE
Topic selection very slow when there are many topics

### ISSUE THREAD

**Issue by AnselmF** [go-gitea/gitea#22188]
### Description

This is a forward of forgejo bug 132, https://codeberg.org/forgejo/forgejo/issues/132. In short, on sites like codeberg with ~1e4 topics, on several web browsers (we have reports for luakit (webkit-based) and firefox), topic selection becomes impossibly slow as the pop-up box is populated with the 1e4 elements for the topics.

Arguably, this is also a UX issue; nobody would want to scroll through the 1e4 topics, in particular as the order is not (really) predictable for users and prone to change as the popularity of topics changes.  Hence: would it be possible to just limit the number of matches from topics/search?

### Screenshots

(sorry, this would be a video)

### Gitea Version

See https://codeberg.org/

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

Debian bullseye

### Browser Version

luakit 2.3.3

**Comment by lunny** [comment]
duplicated with #22238, although this is the first one, but that one has more comments. so close this one.
