### ISSUE TITLE
User secrets

### ISSUE THREAD

**Issue by delvh** [go-gitea/gitea#22183]
Currently, we have both org- and repo secrets.
Some users already reported that they would like to have secrets that are shared across their own repos as well.
The code base should already allow that already, the only thing that needs to be added is a settings page to configure the user secrets.

_Originally posted by @KN4CK3R in https://github.com/go-gitea/gitea/issues/22142#issuecomment-1352927219, but extracted into its own issue to get the PR merged_

**Comment by silverwind** [comment]
> Currently, we have both org- and repo secrets

Is that a toggle-able feature? I don't see any secrets tab on repo/org on 1.19.

**Comment by KN4CK3R** [comment]
The secrets are in the settings of the repo/org.

**Comment by silverwind** [comment]
Ah, I do see the tab on try, but not on my local instances, must be something in the config that's preventing the tabs from showing.

**Comment by delvh** [comment]
Are you sure you have that commit already on your instance?
Because it was only merged 36 hours ago, and I don't remember any config option in the PR…

**Comment by silverwind** [comment]
Ah, I was out of date. Did miss that PR apparently.
