### ISSUE TITLE
Want All Feature of GitHub Enterprise in Gitea

### ISSUE THREAD

**Issue by faizanqritrim** [go-gitea/gitea#22197]
### Feature Description

I think It would be great If you provide the features of GitHub Enterprise to gitea for Private repo. Actually My organization wanted to switch from GitHub to Gitea. So I need help from gitea for the migration process because all of our repo and configuration is in Azure, Jenkins Because I don't want to take the risk because If one of repo is going to disturb inappropriately so it will damages the software. So I want help from gitea for the migration process.

**Comment by lunny** [comment]
I don't think it's possible to copy all the Github Enterprise features to Gitea because when Gitea are developing, Github Enterprise are also developing. And please post an issue per one feature or one group features and close this one.

**Comment by faizanqritrim** [comment]
Hello,

Can gitea help me to migrate my github overall setup to gitea. Best practice and strategy to approach the migration process
________________________________

**Comment by lunny** [comment]
You can get help from our discord.
