### ISSUE TITLE
NPM Packages published to gitea npm registry which use a scope, can't be opened in the web interface 404

### ISSUE THREAD

**Issue by suricoon** [go-gitea/gitea#22202]
## Summary
NPM Packages published to gitea npm registry which use a scope, can't be opened in the web interface anymore.
The UI shows 404

## Steps to reproduce

- create any npm project using npm init
- name the npm project something like @myscope/my-fancy-lib 
- create a local .npmrc and put the registry info there including the scope
- npm publish the package
- navigate to the organization/user and open packages tab
- click on the newly published package
- you will get a 404

## .npmrc 
````
@myscope:registry=https://********/api/packages/myorg/npm/
//********/api/packages/myorg/npm/:_authToken=${NPM_TOKEN}
````

## package.json
````
{
    "name" : "@myscope/my-fancy-lib"
    ...
}
````

## The problem

![image](https://user-images.githubusercontent.com/49761117/208945265-4221222b-4cae-4388-8a44-37fa6b4ad846.png)
The @ of the package name does not seem to be URL encoded in the URL.
![image](https://user-images.githubusercontent.com/49761117/208946035-331a88eb-974d-4614-b133-33a67b59965c.png)
![image](https://user-images.githubusercontent.com/49761117/208945566-ebd850db-418b-4fd3-a177-aa86d48f696f.png)

### Gitea Version

1.17.2

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

see description above

### How are you running Gitea?

self hosted gite in a docker container behing reverse proxy nginx

### Database

None

**Comment by KN4CK3R** [comment]
Still works for me:
![](https://user-images.githubusercontent.com/1666336/209147727-aaf35632-e9f2-4559-96fd-2ff8f9136871.png)

**Comment by KN4CK3R** [comment]
Maybe same error as #20890?

**Comment by cedx** [comment]
Same issue here. Using Gitea 1.18.0 on Windows Server 2019.

**Comment by KN4CK3R** [comment]
Which reverse proxy do you use?

**Comment by cedx** [comment]
You've found the root cause: thank you! I've tried a direct access (i.e. without using the proxy), and it works!
I'm using Microsoft IIS with the Application Request Routing module.

**Comment by cedx** [comment]
With IIS, you can avoid this issue by disabling the `useOriginalURLEncoding` flag and using the `UNENCODED_URL` server variable: 

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
	<system.webServer>
		<httpErrors existingResponse="PassThrough"/>
		<rewrite>
			<rules useOriginalURLEncoding="false">
				<clear/>
				<rule name="Packages" patternSyntax="Wildcard" stopProcessing="true">
					<match url="*/-/packages/npm/*"/>
					<action type="Rewrite" url="http://127.0.0.1:9000{UNENCODED_URL}"/>
				</rule>
				<rule name="Proxy" patternSyntax="Wildcard" stopProcessing="true">
					<match url="*"/>
					<action type="Rewrite" url="http://127.0.0.1:9000/{R:1}"/>
				</rule>
			</rules>
		</rewrite>
	</system.webServer>
</configuration>
```
