### ISSUE TITLE
if i migration a git mirror repository from another gitea, i got a error

### ISSUE THREAD

**Issue by CocytusElias** [go-gitea/gitea#22207]
### Description

If I migrate a mirror repository from one gitea to another gitea, gitea will show that the migration failed.
![image](https://user-images.githubusercontent.com/79587688/209054086-3543c96a-efc4-4cec-ba47-d1ac7ea48ad6.png)

source service log:
![image](https://user-images.githubusercontent.com/79587688/209054308-979de44a-7157-4d11-9037-df78d20093f9.png)

target service log:
![image](https://user-images.githubusercontent.com/79587688/209054410-544452da-060e-46c6-a2b8-6af70c4924ce.png)

### Gitea Version

source: gitea/gitea:1.15.7 , target:gitea/gitea:1.17.3

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

use docker 

### Database

None

**Comment by lunny** [comment]
Please check your gitea server's network connection to target server.

**Comment by eliassama** [comment]
it's not network's problem. I can reproduce it. If the repository is a mirror, migration cannot be performed. only a non-mirrored warehouse can be migrated.

**Comment by eliassama** [comment]
I think the reason is that when gitea a went to mirror a warehouse, it didn't mirror all the data.

When the gitea b service migrates to the mirror repository of the a service, it finds that many things cannot be found, resulting in an error.

The specific steps are:
1. gitea a migrates a github or other repository and sets it as a mirror.
2. When gitea b migrates the mirror repository of gitea a, it does not set it as the mirror repository.


gitea a refers to source.
gitea b refers to target.

**Comment by eliassama** [comment]
I think mirroring means constantly synchronizing all data from another repository without 404 errors.

so this is a BUG, not needs-feedback.

**Comment by lunny** [comment]
So could you chose to only migrate git data/wiki data and if that will succeed?

**Comment by eliassama** [comment]
if source and target all mirror repository, it's can work.

if source is mirror repository, target not is mirror repository:
- not migrate git merge data, it's can work.
- migrate git merge data, it's cannot work.

**Comment by eliassama** [comment]
So the problem is with git merge data. corresponds pull request on github , or merge requests on gitlab .

**Comment by eliassama** [comment]
and i think, is it a design problem? because, i can't find "merge requests"(maybe call this name?), on my mirror repository.

**Comment by eliassama** [comment]
![image](https://user-images.githubusercontent.com/79587688/209067025-aebe66a4-d8e6-4645-9da4-c65af5123489.png)

**Comment by eliassama** [comment]
my current solution is to convert it to a regular warehouse and then migrate it.

**Comment by lunny** [comment]
This is by design. A mirror repository will not include pull request features.
