### ISSUE TITLE
Feature: Execute scripts on events

### ISSUE THREAD

**Issue by sinnlosername** [go-gitea/gitea#2221]
Could you add a feature to execute shell scripts on specific events. 

Examples what I mean with events:
- Something is pushed into a repo
- A pull request was accept
- An issue was created/closed
- ...

The feature would be helpful as users could add their own features like notifications, automated emails, etc....

**Comment by jonasfranz** [comment]
You could use Webhooks for this. You could write for example an easy PHP script which executes your custom features and which is called by the webhook.

**Comment by jonasfranz** [comment]
Or you could use git hooks (https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks) for some specific events.

**Comment by sinnlosername** [comment]
Yes, but I think it would be easier to do it with shell scripts, as most features require shell commands and you won't have problems with permissions. 

Git hooks are clientside, aren't they

**Comment by jonasfranz** [comment]
No, git hooks can be server side too. 

https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks#_server_side_hooks

You could find this in your repository settings under "Git-Hooks".

**Comment by sinnlosername** [comment]
Events on push work with it, but issue listener or something like that aren't possible, are they?

**Comment by lunny** [comment]
As @JonasFranzDEV said, you could use webhook do that or you can edit custom git hooks on repository settings. I think that's enough for most things.

**Comment by sinnlosername** [comment]
Why don't you just copy webhooks and execute a shell script with all of it?

**Comment by sapk** [comment]
This could be a good first example/implementation for #2222 with a plugin listening on event and executing a list of shell script.

**Comment by 3shirtlessmen** [comment]
I do exactly these things with server side githooks. I use a mix of shell / python scripts to accomplish what I want.
