### ISSUE TITLE
Some docker hub tags are not updated to 1.17.4

### ISSUE THREAD

**Issue by svengo** [go-gitea/gitea#22210]
### Description

Giteabot missed to update some docker hub tags:

- [gitea/gitea:latest](https://hub.docker.com/layers/gitea/gitea/latest/images/sha256-b6afc1fbb31d63e731e0eacf19647042e82b239dd4fc5e9ee675a1c03fc14b0d?context=explore) is pointing to [gitea/gitea:1.18.0-rc1](https://hub.docker.com/layers/gitea/gitea/1.18.0-rc1/images/sha256-b6afc1fbb31d63e731e0eacf19647042e82b239dd4fc5e9ee675a1c03fc14b0d?context=explore)
- [gitea/gitea:1.17](https://hub.docker.com/layers/gitea/gitea/1.17/images/sha256-395098e77ecc0a6052c3b0f46736b16e586982e545734d8421c1727d82992b22?context=explore) is pointing to [gitea/gitea:1.17.3](https://hub.docker.com/layers/gitea/gitea/1.17.3/images/sha256-395098e77ecc0a6052c3b0f46736b16e586982e545734d8421c1727d82992b22?context=explore)

I didn't look at the other tags, maybe they are also not up to date. 

This is especially annoying because [1.17.4](https://github.com/go-gitea/gitea/releases/tag/v1.17.4) is a security update.

### Gitea Version

1.17.4

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

Docker

### Database

None

**Comment by eeyrjmr** [comment]
Its an unfortunate bug captured here: https://github.com/go-gitea/gitea/issues/21615

**Comment by nemunaire** [comment]
There is also [gitea/gitea:1](https://hub.docker.com/layers/gitea/gitea/1/images/sha256-395098e77ecc0a6052c3b0f46736b16e586982e545734d8421c1727d82992b22?context=explore) still pointing to [gitea/gitea:1.17.3](https://hub.docker.com/layers/gitea/gitea/1.17.3/images/sha256-395098e77ecc0a6052c3b0f46736b16e586982e545734d8421c1727d82992b22?context=explore)

**Comment by lunny** [comment]
> There is also [gitea/gitea:1](https://hub.docker.com/layers/gitea/gitea/1/images/sha256-395098e77ecc0a6052c3b0f46736b16e586982e545734d8421c1727d82992b22?context=explore) still pointing to [gitea/gitea:1.17.3](https://hub.docker.com/layers/gitea/gitea/1.17.3/images/sha256-395098e77ecc0a6052c3b0f46736b16e586982e545734d8421c1727d82992b22?context=explore)

Hm, wired missing tags, will check that and maybe manually push them.

**Comment by lunny** [comment]
This has been resolved.
