### ISSUE TITLE
Add RSS support for commits (per branch / file)

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#22228]
option to follow commits on branches via rss

pull to get inspiration how to add rss: https://github.com/go-gitea/gitea/pull/21696

more info at #19071

**Comment by adamcstephens** [comment]
Do you expect that will support per-file feeds? GitHub supports this and I find it useful for some projects to watch the commits on an individual file.

**Comment by 6543** [comment]
@adamcstephens can you provide an example url?

**Comment by adamcstephens** [comment]
@6543 Yep, you can get one for any file. Browse to the file, then the commit history of that file, and add `.atom` to the end of the URL.

e.g. https://github.com/go-gitea/gitea/commits/main/README.md.atom
