### ISSUE TITLE
Topic selection slow on Codeberg and WebKit 

### ISSUE THREAD

**Issue by tallship** [go-gitea/gitea#22238]
### Description

On sites like codeberg with ~1e4 topics, on several web browsers (we have reports for luakit (webkit-based) and firefox), topic selection becomes impossibly slow as the pop-up box is populated with the 1e4 elements for the topics.

Arguably, this is also a UX issue; nobody would want to scroll through the 1e4 topics, in particular as the order is not (really) predictable for users and prone to change as the popularity of topics changes. Hence: would it be possible to just limit the number of matches from topics/search?

Browser version: luakit 2.3.3

### Gitea Version

See https://codeberg.org/

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

(sorry, this would be a video)

### Git Version

See https://codeberg.org/

### Operating System

Debian Bullseye

### How are you running Gitea?

See https://codeberg.org/

Firefox luakit 2.3.3

### Database

PostgreSQL

**Comment by fsologureng** [comment]
Hi, I can confirm this. The ajax request just took ~350ms, so it is a problem in the response handler.

Additionally, maybe the call should be done just once the value in the input has a minimum length.

Originally reported in https://codeberg.org/forgejo/forgejo/issues/132

**Comment by jolheiser** [comment]
I think a minimal length might be good, a limit to returned topics, and certainly a debounce if there is none already.
