### ISSUE TITLE
Generated sitemaps aren't valid according to Google Search Console

### ISSUE THREAD

**Issue by TheBrokenRail** [go-gitea/gitea#22270]
### Description

As of v1.18, Gitea now generates sitemaps. So I updated my Gitea instance and loaded its sitemap into Google Search Console, and it threw a bunch of errors.

(I can't reproduce with https://try.gitea.io because Google Search Console only allows me to load sitemaps from domains I control, and I definitely don't control https://try.gitea.io.)

### Gitea Version

v1.18

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![Screenshot 2022-12-29 at 18-48-09 Sitemaps](https://user-images.githubusercontent.com/17478432/210021866-40e02d5e-c600-40f9-8907-96fdc1658142.png)

### Operating System

Linux

### How are you running Gitea?

Docker Compose

### Database

SQLite

**Comment by TheBrokenRail** [comment]
Any chance this fix will be backported to v1.18.1? Thanks!

**Comment by jolheiser** [comment]
> Any chance this fix will be backported to v1.18.1? Thanks!

Yep, this will be backported!
