### ISSUE TITLE
Delete multiple issues at once

### ISSUE THREAD

**Issue by TheBrokenRail** [go-gitea/gitea#22273]
### Feature Description

Right now you can select multiple issues from the issue tracker at once to open/close them, but you can only delete one issue at a time. I'd like a way to delete multiple issues at once.

### Screenshots

Someone put a bunch of spam on an issue tracker on my instance, and while I can open/close multiple issues at once, I can only delete issues one at a time, which is slightly annoying.

![Screenshot from 2022-12-29 23-23-32](https://user-images.githubusercontent.com/17478432/210034342-76c96a4b-2ebc-488f-9e75-4bf62dc28d18.png)

**Comment by CodeDoctorDE** [comment]
🥇 
I'm currently working on this. I will create a pull request after I'm finished!
