### ISSUE TITLE
Excessive queries to system_setting table causing slow load times

### ISSUE THREAD

**Issue by kimma** [go-gitea/gitea#22281]
### Description

Dashboard/home screen takes around 3-4 seconds to load.
Have turned on SQL logging, and it seems to be repeating two queries related to Avatars/System Settings for almost the full duration of the request, and then finally serving the page.

Seems related to this new feature listed for 1.18.0
`Add system setting table with cache and also add cache supports for user setting (https://github.com/go-gitea/gitea/pull/18058)`

It seems no Cache is utilized, since the query is repeated several times for each include of the avatar on the Dashboard/Home page.
Disabling Gravatar support does not affect load times, it simply does not load the Gravatar avatar but still queries the setting multiple times.

The attached log gist is an excerpt from the SQL logs showing all queries ran from hitting "refresh" on the Dashboard page and until NginX returns the result.

### Gitea Version

1.18.0

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/kimma/0ce826ed7f68353c4a22cf422d50cd4c

### Screenshots

Footer with load times:
<img width="487" alt="Screenshot 2022-12-30 at 11 47 38" src="https://user-images.githubusercontent.com/1186008/210065690-2fc98129-0658-49a7-b6af-ae7de8956244.png">

The dashboard in question:
<img width="802" alt="Screenshot 2022-12-30 at 12 32 57" src="https://user-images.githubusercontent.com/1186008/210065972-ff6ba41f-7041-4c7d-a37d-1404ffa20d1e.png">

### Operating System

Kubernetes

### How are you running Gitea?

Utilizing the Docker image from docker hub: `gitea/gitea:1.18.0`
Running in Kubernetes with Galera (mariadb) backend, Redis cache and Minio storage

### Database

None

**Comment by lunny** [comment]
Have you enabled cache? I think it could resolve the problem.

**Comment by kimma** [comment]
I’ve set the redis based caches:

https://docs.gitea.io/en-us/config-cheat-sheet/#cache-cache
https://docs.gitea.io/en-us/config-cheat-sheet/#cache---lastcommitcache-settings-cachelast_commit

**Comment by kimma** [comment]
Excerpt from config:
```
[cache]
ENABLED = true
ADAPTER = redis
HOST    = rediss+sentinel://<redacted>
[cache.last_commit]
ENABLED = true
```

Is there any Cache config that needs to be set manually?
I see the feature mentions caching but it does indeed not look like it is being utilized for this query.

**Comment by lunny** [comment]
Looks like `memory` cache fix the problem. I will take a look.

**Comment by somera** [comment]
Is the fix for memcache cache too?

```
[cache]
ENABLED = true
ADAPTER = memcache
INTERVAL = 240
HOST = 192.168.178.30:11211
ITEM_TTL = 16h
```

**Comment by lunny** [comment]
> Is the fix for memcache too?
> 
> ```
> [cache]
> ENABLED = true
> ADAPTER = memcache
> INTERVAL = 240
> HOST = 192.168.178.30:11211
> ITEM_TTL = 16h
> ```

Yes. It should be.
