### ISSUE TITLE
Unneccessary SMTP_ADDR lookup when using "PROTOCOL = sendmail"

### ISSUE THREAD

**Issue by markshep** [go-gitea/gitea#22287]
### Description

I've just upgraded to 1.18.0 and had to fix my [mailer] config to avoid #22274 (and also update my [log] config just to see the problem in the first place!).  Now that I can see warnings in the console I noticed this:

```
2022/12/30 21:49:49 ...es/setting/mailer.go:263:tryResolveAddr() [W] could not look up mailer.SMTP_ADDR: lookup : no such host
```

However it makes no sense for gitea to be attempting to resolve SMTP_ADDR as I'm using the "sendmail" PROTOCOL for my mailer:

```
[mailer]
ENABLED       = true
FROM          = Gitea <gitea@re.da.ct.ed>
PROTOCOL      = sendmail
SENDMAIL_PATH = /usr/sbin/sendmail
SENDMAIL_ARGS = --
```

### Gitea Version

1.18.0

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

Debian 11.6 (amd64)

### How are you running Gitea?

Downloaded from your GitHub release page.

### Database

None

**Comment by lunny** [comment]
22295 is a wrong ref.
