### ISSUE TITLE
Static configuration for root directory

### ISSUE THREAD

**Issue by MTecknology** [go-gitea/gitea#2229]
At the moment, it seems like gitea gets a little bit confused when trying to find configuration data. Sometimes it'll look for a file at ${binpath}/${foo} (/usr/bin/gitea/custom/...) and other times it'll try ${pwd}/${foo}.

It would be ideal if we could have a build-time (and run-time) argument to configure a base path. This variable would make it very easy to handle a wide variety of deployments and would provide a fair amount of consistency for locating files.

Something like this would probably make #2228 a moot (but still valid) issue.

**Comment by lafriks** [comment]
I think #2192 fixes this

**Comment by MTecknology** [comment]
If that fixes it, then documentation will definitely be needed.

**Comment by lafriks** [comment]
It fixes that all files are written to custom_directory etc it won't write to pwd if customdir is specified

**Comment by mckaygerhard** [comment]
curently changes get approved but now has conflicts and are not merged yet!

also this change the behaviour of the app.ini paths configs!

many documentations will be afected, also some preparation are need!

**Comment by MTecknology** [comment]
@lafriks Sorry, I haven't followed up on this. I'll close and re-open if needed.
