### ISSUE TITLE
Docker Registry Pull and Push Error since Version 1.18

### ISSUE THREAD

**Issue by NiclasPe** [go-gitea/gitea#22308]
### Description

Hello, 
at first i wanna thank all of you for this great pice of software!
Since I upgraded my Gitea - Docker Container to the latest version, there are problems with the Docker Registry.
I can neither push nor pull into the registry, as it keeps retrying until the process finally fails. Unfortunately, I don't know what could be causing this at the moment.
Is it possible to downgrade?

### Gitea Version

1.18.0

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

https://gist.github.com/NiclasPe/d0d7e4e45e9c28014150fdc37ff52ba3

### Screenshots

![Bildschirm­foto 2023-01-01 um 22 22 52](https://user-images.githubusercontent.com/52936786/210185088-3a11ce71-bf03-462f-92c4-8c4db5b302f3.png)
![Bildschirm­foto 2023-01-01 um 22 31 28](https://user-images.githubusercontent.com/52936786/210185115-6723b2ad-313f-4975-b288-6cfff3b4ade0.png)

### Git Version

 2.36.3, Wire Protocol Version 2 Enabled

### Operating System

ubuntu 22.04.01

### How are you running Gitea?

I run the offical Gitea - Container from DockerHub in an k3s Cluster with Traefik as an Reverse Proxy in front of it. The K3s Nodes all run on ubuntu 22.04.01 an the gitea Data is stored in PVC´s over NFS.

### Database

MySQL

**Comment by lunny** [comment]
Could you try `docker logout` and `docker login` again?

**Comment by KN4CK3R** [comment]
Where is the package data stored? Looks like there is a problem:
`Error whilst copying content to response: write tcp 10.42.2.18:3000->10.42.2.21:54118: write: connection reset by peer`
The push however looks more like a proxy not passing all the data.

**Comment by NiclasPe** [comment]
> Where is the package data stored? Looks like there is a problem:
> `Error whilst copying content to response: write tcp 10.42.2.18:3000->10.42.2.21:54118: write: connection reset by peer`
> The push however looks more like a proxy not passing all the data.

The Data is stored in on an NFS Share and will get to the container over an Kubernetes PVC (Persistent Volume Claim). 
Yesterday I’d tried it on my old Docker Swarm Cluster with Nginx as Reverse Proxy and ist work, but as I will go backwards to K3S the problem appears again. After that I tried the same Nginx Proxy with the same configuration from the Docker Swarm on Kubernetes, but no change. So I think it’s an problem with the cluster networking?!
I will try it on an Cluster created by DigitalOcean to check if it works there and report it here.

**Comment by NiclasPe** [comment]
> Could you try `docker logout` and `docker login` again?

My CI/CD Pipeline dose that on every push, but it failed as well.

**Comment by NiclasPe** [comment]
I tried it on digital Ocean, and it work, so i isn’t an gitea Issue. 
Sorry for the Trouble. 

I will close this Issue.
