### ISSUE TITLE
Document listening on a unix socket

### ISSUE THREAD

**Issue by MTecknology** [go-gitea/gitea#2230]
It seems that it's only possible to run gitea on a tcp socket. For some configuration deployments, it would be better if gitea could be configured to listen on a unix socket, ideally using something like the wsgi protocol.

**Comment by silverwind** [comment]
Why wgsi over a plain `http+unix` or `https+unix` socket? Any benefits?

**Comment by silverwind** [comment]
Also, I think this is already supported as of https://github.com/gogits/gogs/pull/2852 by setting `HTTP_ADDR` to a path and possibly adjusting `UNIX_SOCKET_PERMISSION`. Should be documented better.

**Comment by MTecknology** [comment]
If it already exists as http{,s}+unix, that sounds good to me. I didn't find it documented anywhere so I assumed it didn't exist.

**Comment by silverwind** [comment]
This works for me:

```
PROTOCOL = unix
HTTP_ADDR = /tmp/gitea
UNIX_SOCKET_PERMISSION = 666
```

Looks like it only supports http+unix, so I could see it  being improved to also support https+unix.

**Comment by MTecknology** [comment]
Awesome! Should I leave this open as a documentation request or should I go ahead and close this?

**Comment by silverwind** [comment]
I'd leave it open for documentation.

**Comment by silverwind** [comment]
Noteable issue with unix sockets: https://github.com/go-gitea/gitea/issues/2232
