### ISSUE TITLE
View as Role Button

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#22307]
### Feature Description

For administrators creating roles for their organization, I think a view as role button to see what that role actually does now as a user with that role would be useful. I have seen this idea before on discord, would it be possible to add here?

**Comment by KN4CK3R** [comment]
Related/duplicate #21599

**Comment by PrairieAstronomer** [comment]
Sorry, I tried to look for an already open issue for this, but evidently I wasn't searching the right search terms.
