### ISSUE TITLE
Migration from 1.17.4 to 1.18.0 fails due to permission problem

### ISSUE THREAD

**Issue by CKsTechnologyNews** [go-gitea/gitea#22314]
### Description

The manual upgrade from the binary installation from 1.17.4 to 1.18.0 fails due to permission issue. 

# My upgrade procedure from 1.17.4 to 1.18.0.

### Stop running Gitea Service
`sudo systemctl stop gitea`

### Download latest Gitea version
```
wget -O /tmp/gitea https://dl.gitea.io/gitea/1.18.0/gitea-1.18.0-linux-amd64
sudo mv /tmp/gitea /usr/local/bin
```

### Make the binary executable
`sudo chmod +x /usr/local/bin/gitea`

### Temporarily set with write permissions for user git
```
sudo chmod 750 /etc/gitea
sudo chmod 640 /etc/gitea/app.ini
```

### Reload just in case
`sudo systemctl daemon-reload`

### Ensure the Gitea Service starts at boot
`sudo systemctl enable --now gitea`

### Systemd restart Gitea
`sudo systemctl restart gitea`

### Gitea Version

1.18.0

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_See below_

### Screenshots

Not needed.

### Git Version

2.38.1

### Operating System

Ubuntu 22.10 Kinetic

### How are you running Gitea?

Gitea runs as binary installation.

The debug logs says that the permission is incorrect, I do not see why. Previous upgrades worked fine, I did not changed any permissions in the meantime between 1.17.4 and 1.18.0.

**Gitea version after downloading** 

```
gitea --version
Gitea version 1.18.0 built with GNU Make 4.1, go1.19.4 : bindata, sqlite, sqlite_unlock_notify
```

**journalctl -b 0 -u gitea**

```
gitea.service: Failed at step EXEC spawning /usr/local/bin/gitea: Permission denied
gitea.service: Main process exited, code=exited, status=203/EXEC
Failed with result 'exit-code'.
gitea.service: Scheduled restart job, restart counter is at 1.
Stopped Gitea (Git with a cup of tea).
Failed to execute /usr/local/bin/gitea: Permission denied
```

**log**

```
Stopping Gitea (Git with a cup of tea)...
2023/01/02 12:21:34 ...eful/manager_unix.go:150:handleSignals() [W] [63b1e68f] PID 938. Received SIGTERM. Shutting dow>
2023/01/02 12:21:34 ...eue/queue_channel.go:154:func1() [W] ChannelQueue: task-channel Terminated before completed flu>
2023/01/02 12:21:34 .../graceful/manager.go:205:doHammerTime() [W] Setting Hammer condition
2023/01/02 12:21:35 .../graceful/manager.go:224:doTerminate() [W] Terminating
```

**systemctl status gitea**

```
● gitea.service - Gitea (Git with a cup of tea)
     Loaded: loaded (/etc/systemd/system/gitea.service; enabled; preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Mon 2023-01-02 16:24:16 CET; 2s ago
    Process: 175943 ExecStart=/usr/local/bin/gitea web --config /etc/gitea/app.ini (code=exited, status=203/EXEC)
   Main PID: 175943 (code=exited, status=203/EXEC)
         IP: 0B in, 0B out
        CPU: 11ms
```

**LS**

```
ls -lah /usr/local/bin/gitea
-rwxr-x--- 1 root root 112M Jan  2 14:17 /usr/local/bin/gitea
```

**GITEA_WORK_DIR=/var/lib/gitea/ /usr/local/bin/gitea web -config /etc/gitea/app.ini**
```
cmd/web.go:106:runWeb() [I] Starting Gitea on PID: 176076
...s/setting/setting.go:1031:loadFromConf() [I] Default UI Location is Europe/Berlin
...s/setting/setting.go:1059:loadFromConf() [F] Gitea is not supposed to be run as root. Sorry. If you need to use privileged TCP ports please instead use setcap and the `cap_net_bind_service` permission
```
I tried to run `sudo setcap 'cap_net_bind_service=+ep' /usr/local/bin/gitea` without success.

**/etc/systemd/system/gitea.service**
```
[Unit]
Description=Gitea (Git with a cup of tea)
After=syslog.target
After=network.target
After=mysqld.service

[Service]
RestartSec=3s
Type=simple
User=git
Group=git
WorkingDirectory=/var/lib/gitea/
ExecStart=/usr/local/bin/gitea web --config /etc/gitea/app.ini
Restart=always
Environment=USER=git HOME=/home/git GITEA_WORK_DIR=/var/lib/gitea
CapabilityBoundingSet=CAP_NET_BIND_SERVICE
AmbientCapabilities=CAP_NET_BIND_SERVICE
ProtectSystem=full
PrivateUsers=false

[Install]
WantedBy=multi-user.target
```

I tried to downgrade but I get exactly the same permission denied error. If someone could point me in the direction, that would be nice.

### Database

[SQLite](https://www.sqlite.org/index.html).

**Comment by jolheiser** [comment]
You are running it as user `git`, but that user doesn't have executable access to `/usr/local/bin/gitea`

**Comment by CKsTechnologyNews** [comment]
No clue what to do here, git runs already as system.

```
adduser \
   --system \
   --shell /bin/bash \
   --gecos 'Git Version Control' \
   --group \
   --disabled-password \
   --home /home/git \
   git
```

**Comment by utking** [comment]
@CKsTechnologyNews ,
the fact that git user runs as system does not cancel that there are no (other bits) permissions for it on the binary. Either allow all to run the gitea binary or set a proper group (git) on it (since the group bits already allow to execute it)

**Comment by wfjake** [comment]
> --system

All this flag does it make the user and group ID of the newly created user below 1000, which just signifies to some programs that it is a system user. For example, Gnome Display Manager only shows users with UID 1000 and above on the login screen. It does nothing for Discretionary Access Control (file ownership + permissions).

Since `/usr/local/bin/gitea` is owned by `root:root` and the permissions are `-rwxr-x---`, only `root` or members of the `root` group can run Gitea as you have it configured. You need to do `chmod o+rx /usr/local/bin/gitea` so that **o**thers can run Gitea (others includes the `git` user).

**Comment by CKsTechnologyNews** [comment]
Thanks for the help, I will try the suggested solution provided by [wfjake](https://github.com/wfjake) and report back. 

If it fixes my issue then I close the ticket. 

Apparently I need to learn some things about git permissions, but I rather ask before I blow something up, apologies at this point, I do not want to abuse issue tickets for basic questions, but I saw others had similar issues and there is not really some useful feedback provided ](until now) on what to do without breaking something.
