### ISSUE TITLE
menu names missing migrating from v17 to v18

### ISSUE THREAD

**Issue by ware32** [go-gitea/gitea#22312]
### Description

migrating from latest release of v17 to v18, menu names doesnt appear in the menu bars

### Gitea Version

18

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

self hosted

### Database

None

**Comment by lunny** [comment]
It should be your custom templates' problem.

**Comment by ware32** [comment]
Yes, solved
