### ISSUE TITLE
(Javascript) Permission denied to access property "apply"

### ISSUE THREAD

**Issue by SoraBytes** [go-gitea/gitea#22329]
### Description

Trying to access the "edit file" in the WebUI results in:

`JavaScript error: Error: Permission denied to access property "apply" (https://{domain}/assets/js/index.js?v=1.18.0 @ 12:88482). Open browser console to see more details.`

Trying to use a Nginx Proxy, had no issues on previous versions. I've accessed the file location and it serves properly.
```
        location / {
                client_max_body_size 4096M;
                proxy_pass http://127.0.0.1:3000;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
        }
```

### Gitea Version

1.18.0

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/Sora012/b8a52d3d27238c99ba2fe30c9b1596c1

### Screenshots

![screenshot_2023-01-03_15:31:21](https://user-images.githubusercontent.com/18122133/210437581-ffd1894b-8786-4dcf-a1fa-2dc8cd137d5b.png)

### Git Version

2.38.1

### Operating System

Fedora 37

### How are you running Gitea?

Downloaded Gitea from https://dl.gitea.io/gitea/1.18.0/gitea-1.18.0-linux-amd64

Running via SystemD

```
[Unit]
Description=Gitea
After=network.target

[Service]
Type=simple

User=gitea
Group=gitea
WorkingDirectory=/home/gitea
ExecStart=/home/gitea/gitea-1.18.0-linux-amd64
Restart=on-failure

[Install]
WantedBy=multi-user.target
```

### Database

MySQL

**Comment by Sora012** [comment]
For "Can you reproduce the bug on the Gitea demo site?" I chose "no" because I didn't want to create an additional account and push a repo to test. If deemed necessary I will.

**Comment by eeyrjmr** [comment]
This might be firefox specific. Do you have another browser to test with?

eg: 
https://github.com/getsentry/sentry-javascript/pull/3377/files

**Comment by wfjake** [comment]
I'm running Gitea 1.18.0 with arc-green theme w/ Firefox 108.0.1. Cannot reproduce this issue when editing a README.md in one of my repos. 

What happens if you disable all your Firefox extensions? My guess is that an extension is messing with Gitea.

**Comment by Sora012** [comment]
So after checking chromium vs firefox as recommended, chromium didn't have the issue, I had previously "stopped" extensions but didn't fully disable them.

I've since tested with them fully disabled and the problem is in this plugin:
https://addons.mozilla.org/en-US/firefox/addon/persepolis-dlm-integration/
