### ISSUE TITLE
Add WeChatWork as Authentication

### ISSUE THREAD

**Issue by droplet-js** [go-gitea/gitea#22347]
### Feature Description

In China, many companies use enterprise WeChat to uniformly manage employee accounts.

> translate 在中国，许多公司使用企业微信统一管理员工账号。

**Comment by hetao29** [comment]
我们通过oauth2的配置，已经实现了企业微信的登录了
<img width="976" alt="image" src="https://github.com/user-attachments/assets/74aff691-203a-4803-9ad1-f65a01c0df85" />

**Comment by techknowlogick** [comment]
Closing as wechatwork supports OIDC. Might be worth documenting this.
