### ISSUE TITLE
Unable to create issues or pull requests

### ISSUE THREAD

**Issue by futurescenario9** [go-gitea/gitea#22352]
### Description

It is not possible to create issues or pull requests, trying to do so results in http status 500.
Here is what I think is the relevant log:
```
2023/01/03 16:30:50 ...rs/web/repo/issue.go:1086:NewIssuePost() [I] [63b44a2a] [SQL] BEGIN TRANSACTION [] - 222.3µs
2023/01/03 16:30:50 ...vices/issue/issue.go:26:NewIssue() [I] [63b44a2a] [SQL] UPDATE issue_index SET max_index=max_index+1   WHERE group_id=? [1]
2023/01/03 16:30:50 ...vices/issue/issue.go:26:NewIssue() [I] [63b44a2a] [SQL] INSERT INTO issue_index (group_id, max_index) VALUES (?, 0) [1] - 509.6µs
2023/01/03 16:30:50 ...vices/issue/issue.go:26:NewIssue() [I] [63b44a2a] [SQL] UPDATE issue_index SET max_index=max_index+1 WHERE group_id=? [1] - 179.5µs
2023/01/03 16:30:50 ...rs/web/repo/issue.go:1086:NewIssuePost() [I] [63b44a2a] [SQL] ROLLBACK []
2023/01/03 16:05:37 ...rs/web/repo/issue.go:1091:NewIssuePost() [E] [63b44441] NewIssue: generate issue index failed: impossible error when GetNextResourceIndex, insert and update both succeeded but no record is updated
```
If I run these querys myself through the console, they work as expected and also return the right amount of rows affected (1) but when run by gitea it seems to always return 0.
https://github.com/go-gitea/gitea/blob/f7ade6de7c1c4991c650d6b96e6407053e6bdae7/models/db/index.go#L98-L103

The MSSQL version is `15.0.2095.3`

### Gitea Version

1.18

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

Windows 10

### How are you running Gitea?

I'm using this binary: https://dl.gitea.io/gitea/1.18.0/gitea-1.18.0-windows-4.0-amd64.exe

### Database

MSSQL

**Comment by wxiaoguang** [comment]
Is it a one-time error, or it keeps reproducing?

**Comment by wxiaoguang** [comment]
I can not reproduce your problem with this setup. MSSQL 2019 is 15.x

```
version: '3'

services:
  gitea:
    image: gitea/gitea:1.18.0
    volumes:
      - ./gitea-1.18-mssql:/data
    ports:
      - 3000:3000
      - 2222:22
    #restart: never

  sql-server-db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "change_this_password"
      ACCEPT_EULA: "Y"
```

**Comment by futurescenario9** [comment]
I found the problem, it actually was a configuration issue.
I had to run this query, it disables a connection option called "no count"
```
EXEC sys.sp_configure N'user options', N'0'
GO
RECONFIGURE WITH OVERRIDE
GO
```

**Comment by jolheiser** [comment]
I wonder if this is worth having in the docs somewhere? In case someone else runs in to it.
I don't use MSSQL, so I'm not sure how common this connection option is or the usual defaults.

**Comment by wxiaoguang** [comment]
Luckily, it's a client option, and it's only used for batched statements or stored procedures, it should only be used explicitly by a client.

Just like MySQL can have startup statements with a lot of `SET xxx`, if some users write incorrect `SET xxx` options, MySQL would also behave strangely. So, just do not do that if you are not sure what they are for. I do not think it's worth to be noted in document.

**Comment by futurescenario9** [comment]
It's a bit annoying though because no matter what I set it breaks either application using that database.
It doesn't seem to be possible to just disable it for one user, it's enabled for all and I'd have to run `SET NOCOUNT OFF/ON` upon opening each connection.
