### ISSUE TITLE
I would like to support the ability to create branches by tag

### ISSUE THREAD

**Issue by inbjo** [go-gitea/gitea#22357]
### Feature Description

Hello,I need to create a branch from tag through the API interface. I have searched the documentation and did not find this interface, so if you can support it, thank you very much.

**Comment by leonheyna** [comment]
You want to create a branch based on a tagged commit via gitea api? Isn't that like the basic functionality of creating a remote branch in git?

**Comment by inbjo** [comment]
> You want to create a branch based on a tagged commit via gitea api? Isn't that like the basic functionality of creating a remote branch in git?

Yes, I need to operate multiple repositories through the API. But currently the interface for creating branches doesn't support creating from tag.
