### ISSUE TITLE
Most recent commit with long first line causes repo view to overflow

### ISSUE THREAD

**Issue by madeline-holland** [go-gitea/gitea#22360]
### Description

Hello. 

The changes in https://github.com/go-gitea/gitea/pull/21124, specifically [here](https://github.com/go-gitea/gitea/commit/52cbe2bdbce6cd5a4fc0738ab4a25fafe9aa6d48?diff=split#diff-109c70f0162741a5b3de595e88e23d39646b364750956dd6a99ab50b997869be) cause the repo file browser to overflow off the page when the most recent commit message has a long first line, which happens a lot when using the Gitea UI to merge two branches with median-length first lines, by default. 

By having `display: inline`, the `.commit-list .message-wrapper` in the repository file browser doesn't respect the `max-width` to prevent overflow. 

Changing `display: inline` to `display: inline-block` fixes the issue on the repository page, but breaks the changes in the above PR, otherwise I would have submitted a PR for it. 

I cannot reproduce on the Gitea demo site because it won't allow me to create an account (500 error).

### Screenshots

(Sorry for the obfuscation, I couldn't create an account on the demo site, otherwise I would have used that.)
![screenshot-1](https://user-images.githubusercontent.com/104645087/211127245-f40a5879-e390-4f64-956b-00078555a81f.png)
![screenshot-2](https://user-images.githubusercontent.com/104645087/211127249-37c13025-2503-45be-bef1-c2577dc1650d.png)

### Gitea Version

1.18.0

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

Linux

### Browser Version

Firefox 108.0, Google Chrome 108.0.5359.124

**Comment by madeline-holland** [comment]
I was able to fix it on my end without effecting the other page with a header template file containing:
```
<style>
#repo-files-table .commit-list .message-wrapper {
    display: inline-block;
}
</style>
```

**Comment by silverwind** [comment]
Fix suggestion in https://github.com/go-gitea/gitea/issues/22413#issuecomment-1381745041.
