### ISSUE TITLE
Show More button no longer works

### ISSUE THREAD

**Issue by gtema** [go-gitea/gitea#22380]
### Description

In the PRs with more changed files then the project limit a "Show More" button is no longer doing anything since the 1.18.0. In the 1.17.0 it was working.

There seem to be no JS errors on the page either, but clicking just on the button is just having no effect

### Screenshots

<img width="1152" alt="Screenshot 2023-01-09 at 13 44 07" src="https://user-images.githubusercontent.com/16461884/211310949-09a6bca2-4d6a-400e-ba49-dd744d5d12ee.png">

### Gitea Version

1.18.0

### Can you reproduce the bug on the Gitea demo site?

Yes

### Browser Version

Firefox 1.108 and Chrome 104.0

**Comment by gtema** [comment]
This is a very ugly workaround for people not so skilled and I made a mistake to deploy this prod already (what now affects many people).
Is there any possibility to downgrade DB so that it is possible to downgrade to 1.17.4 until this is solved?

**Comment by zeripath** [comment]
Are there any logs?

**Comment by zeripath** [comment]
I believe this is likely to be a regression from #17386

**Comment by gtema** [comment]
No logs make sense here, since UI doesn't trigger any action

**Comment by gtema** [comment]
is the fix going to be backported/released with 1.18.1?
