### ISSUE TITLE
Is it possible to not show all of the licenses ?

### ISSUE THREAD

**Issue by freedomtrain** [go-gitea/gitea#2239]
Is it possible to not show all of the licenses ?

Thanks

**Comment by lafriks** [comment]
I don't think so but you can set `PREFERRED_LICENSES` in app.ini that will be shown on top in select box

**Comment by freedomtrain** [comment]
Thanks !!!!
Are the licenses entries hard coded ?
I deleted all of the licenses files that we do not want to show as an option and they still are showing up

**Comment by lafriks** [comment]
They are compiled in binary. So to remove them you would have to recompile from source

**Comment by freedomtrain** [comment]
Ah ha ......
Thanks  !!!! Is there any documentation on how to recompile my current build from source ?

**Comment by sapk** [comment]
We have custom licenses, as stated in docs [here](https://github.com/go-gitea/docs/blob/master/content/doc/advanced/customizing-gitea.en-us.md#customizing-gitignores-labels-licenses-locales-and-readmes), but the behavior is to extend the default one not replace them. 

To compile the exact same build you need a golang env ready and follow https://docs.gitea.io/en-us/install-from-source/.
To know the commit/banch/version of binary use `./gitea -v` of your current version. It will also display TAGS used to build the binary like `sqlite `or `bindata`

**Comment by sapk** [comment]
And I forget, if you find any bottleneck following the documentation, feel free to contribute to https://github.com/go-gitea/docs and ask question on [Discord](https://discord.gg/NsatcWJ) or here. :wink:

**Comment by freedomtrain** [comment]
I have have followed the instructions here  https://docs.gitea.io/en-us/install-from-source/
The license that I have deleted are still showing up.

Are they in bindata ?

**Comment by sapk** [comment]
For context, bindata (more exacly go-bindata) is a program that convert file in go source code accessible like a filesystem.
Generated code should be under module/options. try to do a `make clean`, remove file under [options/license](https://github.com/go-gitea/gitea/tree/master/options/license) that you don't want, and do `make generate build` with your tags. 
You could also try without bindata tag but you will need to keep around static file like /templates or /public to work.

**Comment by lafriks** [comment]
As a feature this should be implemented in the future to be able manage licenses

**Comment by sapk** [comment]
One easy way could be to not use default licence if custom/licenses are used ? or add an option to not use default.

**Comment by BjoernAkAManf** [comment]
I was looking for something similar. How about a special file inside the license (or other overriding) folder like .INCLUDE or .EXCLUDE to specify included or exclude licenses respectively? It would be a shame to maintain a separate set of licenses just to remove some defaults.

**Comment by strk** [comment]
Pull request adding documentation for `PREFERRED_LICENSES`: https://github.com/go-gitea/gitea/pull/3230

**Comment by wolftune** [comment]
I think it would be preferable to indeed have a shorter list. At the least, showing all versions of licenses (such as even CC-BY 1.0 and 2.0 and 2.5 etc) is really noisy. If someone is actually going to use obscure or outdated licensing or is importing an old repo, they can do that without using the dropdown menu in creating new repos.

I would urge that a shorter list be used in general even for the relatively complete set. And it would be nicest to have a default of showing *only* the  `PREFERRED_LICENSES`

**Comment by lunny** [comment]
I think this could be closed and we can track #28661.
