### ISSUE TITLE
Discord hooks can't be delivered since today

### ISSUE THREAD

**Issue by crackedmind** [go-gitea/gitea#22391]
### Description

With empty  icon url discord answer this

`{"avatar_url": ["Scheme "" is not supported. Scheme must be one of ('http', 'https')."]}`

Maybe set this field to favicon if icon url is empty? Manual update all hooks it's not i want to do.

### Gitea Version

1.17.3

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

gitea.service 

### Database

SQLite

**Comment by jolheiser** [comment]
Interesting, not sure if this is new on the Discord API side or what. 
I will look at implementing a fix, considering we have that field marked as optional.

**Comment by jolheiser** [comment]
For reference, https://github.com/go-gitea/gitea/pull/22395 is the backport that will fix it in the `1.17.x` series.
We don't necessarily have a timeframe for `1.17.5`, but that's where it should land. Alternatively, it should also land in `1.18.1` which might be a better bet as it will also be an upgrade. 🙂
