### ISSUE TITLE
Update README.md with company info

### ISSUE THREAD

**Issue by buhtz** [go-gitea/gitea#22403]
### Description

Please update your README.md with informations about "Gitea Limited" and note that the project is now commercial drivin.

### Gitea Version

latest

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

I don't.

### Database

None

**Comment by jolheiser** [comment]
We are currently discussing/voting on governance amongst the maintainers, after which I'm sure there will be an update to `CONTRIBUTING.md`. 

In the meantime, I'm not entirely sure what would be changed in the README, do you have suggestions?
Just mentioning Gitea Ltd?

**Comment by buhtz** [comment]
Then maybe I misunderstood the organization.
I thought the maintainers/admins of this repo here at github do work for "Gitea Limited".

If they are not maybe you should write a small section about the "relation" between this repo and "Gitea Limited" and its current state.

Maybe it is not clear for all persons.

btw: Because of "Gitea Limited" there was a fork out of Gitea created named "Forgejo". So there happens a lot around and it is sometimes hard for coming-by-users to be aware of all details.

**Comment by jolheiser** [comment]
> I thought the maintainers/admins of this repo here at github do work for "Gitea Limited".

Currently (as far as I know) there are three maintainers who work for the company, and a few others who are being compensated on a part-time contract basis (paying open source developers 🥳)

> If they are not maybe you should write a small section about the "relation" between this repo and "Gitea Limited" and its current state.

I think this will likely happen once we have concluded the maintainer governance discussion, at least in some form. 🙂 

> Because of "Gitea Limited" there was a fork out of Gitea created named "Forgejo". So there happens a lot around and it is sometimes hard for coming-by-users to be aware of all details.

We are aware, and it has been an interesting time trying to keep all the details sorted. 😅

**Comment by wxiaoguang** [comment]
TBH, some people of the fork (Forgejo) are extremists, they refuse to listen to or talk with the community and lie about some facts.

**Comment by jolheiser** [comment]
I think we've gathered and responded to what will happen to clarify this issue, so I'm going to lock it as further discussion likely won't yield any further results. 

For any other concerns, I think there are other public spaces that could probably be used that are better than a GitHub issue.
