### ISSUE TITLE
Width issue with repo-files-table layout in Firefox

### ISSUE THREAD

**Issue by aschrijver** [go-gitea/gitea#22413]
### Description

When the message in the `commit-summary` element is too long then the table scales beyond the page width. See screenshot. This is independent of the theme chosen (tested with Forgejo and Codeberg theme).

Easily reproduced by doing "Inspect" in the browser and typing extra text in https://try.gitea.io
Firefox version 108.0.1 (64-bit) on Ubuntu 22.04.1 LTS (5.15.0-57-generic)

_(First reported downstream in [Forgejo/#235](https://codeberg.org/forgejo/forgejo/issues/235))_

### Gitea Version

1.18.0+50-g5a46a564 (codeberg)

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

![Screenshot of layout issue](https://user-images.githubusercontent.com/5111931/212051018-b1ac6a14-1487-48ed-a425-b6f5fc0c3dd7.png)

### How are you running Gitea?

This occurs in the current Codeberg installation.

### Database

None

**Comment by silverwind** [comment]
I think this can be solved elegantly by removing the header from the table and instead make it a separate flexbox with proper CSS truncation. Vertical centering will also be better than what is possible with current table layout.

**Comment by lunny** [comment]
duplicated with #22360

**Comment by silverwind** [comment]
Closing in favor of https://github.com/go-gitea/gitea/issues/22360.
