### ISSUE TITLE
Source code line's comments are not taken into account on Pull Requests page

### ISSUE THREAD

**Issue by kuraga** [go-gitea/gitea#22419]
### Description

On the Gitea demo site, source code line's comments are not taken into account on `Pull Requests` page. So, they are not added to the count of the MR's comments count.

### Gitea Version

1.19.0+dev-291

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

I visit it via a browser.

### Database

None

**Comment by lunny** [comment]
Should they be counted?

**Comment by kuraga** [comment]
Well I think 'there are no comments' if there is not a badge (on `Pull Requests` page). But they are.

**Comment by silverwind** [comment]
I agree, line comments should count towards the comment count. This is how it works on GitHub as well.

**Comment by kuraga** [comment]
#30556
