### ISSUE TITLE
On mobile, avatars are uncontrollable big at pull request's `Files` page

### ISSUE THREAD

**Issue by kuraga** [go-gitea/gitea#22418]
### Description

On Android Chrome, avatars are uncontrollable big at comments on pull request's `Files` page.

Example page: https://git.calculate-linux.org/calculate/calculate-overlay/pulls/22/files#issuecomment-361

### Gitea Version

1.16.9

### Can you reproduce the bug on the Gitea demo site?

No.

### Screenshots

![image](https://user-images.githubusercontent.com/1063219/212182284-516edb43-fd2a-4952-8e1a-a85833a451aa.png)

### How are you running Gitea?

I visit it via a browser.

### Database

None

**Comment by kuraga** [comment]
Well, can't reproduce on reproduce the bug on the Gitea demo site.

Maybe have been already fixed or is a theme issue.

Fill free to close after an analysis.

**Comment by wxiaoguang** [comment]
It has been fixed. Please upgrade to latest.
