### ISSUE TITLE
User's avatar not found after docker container migrate to 1.18

### ISSUE THREAD

**Issue by jiaming0708** [go-gitea/gitea#22424]
### Description

Use docker compose to host gitea service, volum gitea setting on server.
When I migrate service from 1.17 to 1.18, I can't see the user's avatar who does not upload own image (meaning use system default avatar)

in this picture, archie upload his image, tingyu doesn't
![image](https://user-images.githubusercontent.com/8855285/212244370-825d6606-3a57-4abc-b44e-5dacebcb20e7.png)

### Gitea Version

1.18

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

Docker compose

### Database

MSSQL

**Comment by lunny** [comment]
Are you running v1.18.0?

**Comment by jiaming0708** [comment]
yap, v1.18.0

**Comment by lunny** [comment]
There is a bug in v1.18.0 which will be fixed in v1.18.1. I think it could fix the problem.

**Comment by jiaming0708** [comment]
got it, do you have any plan to release v1.18.1?

**Comment by lunny** [comment]
> got it, do you have any plan to release v1.18.1?

Very soon.

**Comment by snoopydo** [comment]
I too am experiencing this issue of broken avatars for users.  Broke after upgrading to 1.18 and still broken after upgrading to 1.18.1 on windows.  
No users have custom avatars set, however if a user goes to their settings and selects delete current avatar, then the broken avatar is fixed for that one user.

**Comment by jiaming0708** [comment]
Migrate to v1.18.1, the issue is still there

**Comment by kekbaito** [comment]
Hello,
First of all, thanks to the gitea team for this awesome piece of software!

I encountered the same issue and recently found a solution. 

**My guess is that your avatars (maybe only some of them) were uploaded to gravatar.**
In the migration files for version 1.18, there is a file that moves the **DISABLE_GRAVATAR** setting to the database. However, it seems that the entry created in the database is set to "True" by default. 
You can refer to this link for more information: https://github.com/go-gitea/gitea/blob/e81ccc406bf723a5a58d685e7782f281736affd4/models/migrations/v1_18/v227.go#L53

To fix this, you can try going to the admin panel and setting it to "False". 

It's unclear whether this is a bug or not, but it's important for users to be aware of this.

**Comment by jiaming0708** [comment]
@kekbaito Thanks for your help!! After setting the value to false, the avatar is back!!
Find below block in the `Configuration` tab in `Site Adminstration`
![image](https://user-images.githubusercontent.com/8855285/214232984-394acc26-9a41-4805-8759-bfe1fcf3899e.png)
