### ISSUE TITLE
Show number of changed lines on pull request's page

### ISSUE THREAD

**Issue by kuraga** [go-gitea/gitea#22420]
### Feature Description

Good day!

(Strange but haven't found a feature request like this.)

Propose to show number of changed (added, removed) lines on pull request's page.

Thanks!

### Screenshots

![image](https://user-images.githubusercontent.com/1063219/212187755-78be8d9c-5f0a-4d8a-a332-ea11703e26c8.png)

**Comment by lunny** [comment]
Did you mean
<img width="541" alt="image" src="https://user-images.githubusercontent.com/81045/212220335-7a3bcf9e-7c3d-43f4-936e-4ff699350201.png">
? It has been implemented. You need to change to `File Changed` tab

**Comment by kuraga** [comment]
> You need to change to 

The idea is to let me don't:

> on pull request's page.

**Comment by denyskon** [comment]
Closing in favour of #25326, will be implemented by #25387
