### ISSUE TITLE
Consider support for reST (reStructuredText) preview

### ISSUE THREAD

**Issue by gagath** [go-gitea/gitea#2243]
- Gitea version (or commit ref): 1.1.2
- Git version: N/A
- Operating system: Debian Stretch
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist: N/A

## Description

I have a lot of README files formatted in [reStructuredText](https://en.wikipedia.org/wiki/ReStructuredText) but the README rendered can only render Markdown files. Please consider reStructuredText rendering for those of us who prefer reST rather than Markdown.

I do not know how this can be done however, maybe by calling external Python library if there is no reST library in Go.

## Screenshots

![screenshot](https://user-images.githubusercontent.com/989521/28866488-6ae1e126-7773-11e7-9938-69926f3c4997.png)

**Comment by lunny** [comment]
duplicated with #374

**Comment by lunny** [comment]
see https://github.com/go-gitea/gitea/pull/2564
