### ISSUE TITLE
Migration to 1.18: no analyzer with name or type 'keyword' registered

### ISSUE THREAD

**Issue by ebourg** [go-gitea/gitea#22430]
### Description

After upgrading from 1.17.3 to 1.18.0, Gitea fails to start.

	2023/01/13 08:17:55 [I] Log Mode: File(Debug)
	2023/01/13 08:17:55 [I] XORM Log Mode: File(Debug)
	2023/01/13 08:17:55 [I] Cache Service Enabled
	2023/01/13 08:17:55 [I] Session Service Enabled
	2023/01/13 08:17:55 [W] Notify Mail Service: Mail Service is not enabled
	2023/01/13 08:17:55 [I] Beginning ORM engine initialization.
	2023/01/13 08:17:55 [I] ORM engine initialization attempt #1/10...
	2023/01/13 08:17:55 [I] ORM engine initialization successful!
	2023/01/13 08:17:55 [I] Git Version: 2.30.2
	2023/01/13 08:17:55 [...ules/indexer/repo.go:81 InitRepoIndexer()] [E] InitRepoIndexer: no analyzer with name or type 'keyword' registered

If I disable the indexer in app.ini, it goes a little further but stops again:

	2023/01/13 08:07:31 [I] Log Mode: File(Debug)
	2023/01/13 08:07:31 [I] XORM Log Mode: File(Debug)
	2023/01/13 08:07:31 [I] Cache Service Enabled
	2023/01/13 08:07:31 [I] Session Service Enabled
	2023/01/13 08:07:31 [W] Notify Mail Service: Mail Service is not enabled
	2023/01/13 08:07:31 [I] Beginning ORM engine initialization.
	2023/01/13 08:07:31 [I] ORM engine initialization attempt #1/10...
	2023/01/13 08:07:31 [I] ORM engine initialization successful!
	2023/01/13 08:07:31 [I] Git Version: 2.30.2
	2023/01/13 08:07:31 [I] SQLite3 Supported
	2023/01/13 08:07:31 [I] Run Mode: Production
	2023/01/13 08:07:31 [I] SSH server started on :22. Cipher list ([aes128-ctr aes192-ctr aes256-ctr aes128-gcm@openssh.com arcfour256 arcfour128]), key exchange algorithms ([diffie-hellman-group1-sha1 diffie-hellman-group14-sha1 ecdh-sha2-nistp256 ecdh-sha2-nistp384 ecdh-sha2-nistp521 curve25519-sha256@libssh.org]), MACs ([hmac-sha2-256-etm@openssh.com hmac-sha2-256 hmac-sha1 hmac-sha1-96])
	2023/01/13 08:07:31 [I] Listen: https://0.0.0.0:443
	2023/01/13 08:07:31 [I] LFS server enabled
	2023/01/13 08:07:31 [.../cmd/web_graceful.go:37 runHTTPS()] [E] Failed to load https cert file 0.0.0.0:443: open : no such file or directory

### Gitea Version

1.18.0

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

Debian 11

### How are you running Gitea?

Gitea is launched by systemd in a Proxmox container

### Database

SQLite

**Comment by ebourg** [comment]
Removing `/var/lib/giteadata/indexers` solves the issue with the indexer.

**Comment by KN4CK3R** [comment]
Are you sure you are using 1.18? `modules/indexer/repo.go` does not exist.

The other error just tells you that a configured certificate was not found.

**Comment by KN4CK3R** [comment]
That file exists in Gitea 1.8 😉

**Comment by ebourg** [comment]
/facepalm

I shouldn't upgrade Gitea before the morning cofee, sorry for the noise
