### ISSUE TITLE
Documentation: CSS import code snippet for external renderers does not work

### ISSUE THREAD

**Issue by sbannier** [go-gitea/gitea#22434]
### Description

The documentation gives this code snippet (see https://github.com/go-gitea/gitea/blob/main/docs/content/doc/advanced/external-renderers.en-us.md?plain=1#L195)
`<link type="text/css" href="{{AppSubUrl}}/assets/css/my-style-XXXXX.css" />`

In Firefox and Chrome this did not work and the CSS was not applied to the rendered HTML page.

Adding `rel="stylesheet"` to the link tag solved the issue for both browsers:
`<link rel="stylesheet" type="text/css" href="{{AppSubUrl}}/assets/css/my-style-XXXXX.css" />`

I will also add a pull request including the changes.

### Gitea Version

1.16.4

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

Windows

### How are you running Gitea?

We are are using the prebuilt Gitea binaries on a Windows 2019 server.

### Database

None

**Comment by lunny** [comment]
closed by #22435
