### ISSUE TITLE
Gitea is GREAT !!!!

### ISSUE THREAD

**Issue by freedomtrain** [go-gitea/gitea#2244]
Gitea is Great !!!!
Cannot say enough about the help I received with my issues as well as the ease of use of Gitea !!!!

All thanks to you !!!

**Comment by lunny** [comment]
You are welcome, but I don't know how to handle this issue. :)

**Comment by bkcsoft** [comment]
You're very welcome 😄 

With that said, I know how to handle this issue :trollface:
