### ISSUE TITLE
Can't delete branch after Pull Request is granted

### ISSUE THREAD

**Issue by DerMolly** [go-gitea/gitea#2245]
- Gitea version (or commit ref): bbe6aa3
- Git version: 2.1.4
- Operating system: Debian 8.9
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

I'm using gitea at work and one colleague really want's to merge his own branches via PRs into master, which totally works until gitea suggests to delete the branch afterwards. That always fails.

When I tested it on try.gitea.io it worked. Is this a bug in the software which was fixed by a commit between bbe6aa3 and dde0052 or do I need to configure something differently?

**Comment by lafriks** [comment]
Does branch name contains `/`?

**Comment by DerMolly** [comment]
no but `-` and `_`

**Comment by DerMolly** [comment]
also tried a simple branch name `test`
same result

**Comment by philfry** [comment]
Had a similar problem with a centos7 default installation which shipped an older git version.

git 1.8.3.1 does not support force deleting branches. I suspect same goes for 2.1.4.
Gitea tries the following call when deleting a branch:
```
execve("/usr/bin/git", ["git", "branch", "-d", "-f", "mybranch"], [/* 7 vars */]) = 0
```
which results in logs like these:
```
[.../runtime/asm_amd64.s:514 call32()] [E] DeleteBranch: exit status 129 - usage: git branch [options] [-r | -a] [--merged | --no-merged]
```
Possible workaround: upgrade git. Anyways, please check your gitea logs for errors.

**Comment by lafriks** [comment]
@DerUser can you verify that git version is the problem?

**Comment by DerMolly** [comment]
Yes updating to git 2.11.0 via jessie-backports fixed the problem.
Thanks

**Comment by DerMolly** [comment]
@philfry btw. thanks for the tipp, but the gitea logs did not contain such an error. Which logging level do you use?

**Comment by philfry** [comment]
@DerUser "info", usually.
@lunny no, it would be easier to use `git branch -D` instead. `-D` is understood by older git versions and expands to `-d -f` in more recent versions.
git 1.8.3.1:
```
-D Delete a branch irrespective of its merged status.
```
git 2.13.4:
```
-D Shortcut for --delete --force.
-f, --force
           Reset <branchname> to <startpoint> if <branchname> exists already.
           Without -f git branch refuses to change an existing branch. In
           combination with -d (or --delete), allow deleting the branch
           irrespective of its merged status. In combination with -m (or
           --move), allow renaming the branch even if the new branch name
           already exists.
```

**Comment by lafriks** [comment]
I have created PR to support also older git versions

**Comment by lunny** [comment]
@lafriks You have to update the vendor
