### ISSUE TITLE
add new OpenID URI: EOF error

### ISSUE THREAD

**Issue by yuuuxt** [go-gitea/gitea#22461]
### Description

- I want to explore the feature of using external auth provider, so I tried providing  "Settings - Security - Manage OpenID Addresses" with `https://<auth.domain>/.well-known/openid-configuration` and click the add button below;
- an Error message `EOF` appears on top of current page.
Several combinations are tried:
- local docker gitea + local docker auth provider (`zitadel`) - `EOF`
- local docker gitea + `zitadel.cloud` - `EOF`; if adding `/` at the end - `LINK with rel=openid2.provider not found`
- local docker gitea + gitea's own discovery endpoint (i.e. use gitea domain instead of the auth provider) - `EOF`

on demo site it's the same.

looking at docker logs there seems no additional error msg:

```
2023-01-16 00:34:46 2023/01/16 00:34:46 [63c42b1e] router: completed GET /user/events for 172.28.0.1:33916, 200 OK in 7891.1ms @ events/events.go:19(events.Events)
2023-01-16 00:34:46 2023/01/16 00:34:46 [63c42b26] router: completed POST /user/settings/security/openid for 172.28.0.1:33996, 200 OK in 55.5ms @ security/openid.go:20(security.OpenIDPost)
2023-01-16 00:34:49 2023/01/16 00:34:49 [63c4176c-25] router: polling   GET /user/events for 172.28.0.1:33996, elapsed 3030.0ms @ events/events.go:19(events.Events)
```

### Gitea Version

1.18.0

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

![image](https://user-images.githubusercontent.com/3153534/212554437-bb574065-fbc1-4d07-ac66-dfd6cd4d52b8.png)

![image](https://user-images.githubusercontent.com/3153534/212554417-268ef85e-bf26-400c-9e3a-4cbf79650234.png)

### Git Version

NA

### Operating System

tried docker on linux & windows

### How are you running Gitea?

tried:
- docker-compose - behind traefik, postgres db;
- docker-compose - basics version on https://docs.gitea.io/en-us/install-with-docker/#installation (sqlite db)
- (and the demo site)

### Database

SQLite

**Comment by KN4CK3R** [comment]
Tested it with a local Zitadel instance and it works without problems.

**Comment by yuuuxt** [comment]
> Tested it with a local Zitadel instance and it works without problems.

Could you help provide more details about how you did it and what is the actual (and expected) result, so that I can learn and debug? I haven't found corresponding docs on gitea doc site.
