### ISSUE TITLE
Question about swagger.json file

### ISSUE THREAD

**Issue by sungam3r** [go-gitea/gitea#22488]
### Feature Description

Hi. I've read https://docs.gitea.io/en-us/faq/#what-is-swagger and I successfully can work with swagger UI on my running Gitea instance. I would like to ask how I can get swagger json file (Open API json document). I want to use NSwag to generate .NET REST client for Gitea. Example for Atlassian Bitbucket Server: https://developer.atlassian.com/server/bitbucket/8.6.swagger.v3.json

**Comment by jolheiser** [comment]
For example, this is try's: https://try.gitea.io/swagger.v1.json

**Comment by sungam3r** [comment]
Thanks, https://try.gitea.io/swagger.v1.json works. Just to clarify - I would like to get Open API document from exact the same instance that I use, not from somewhere else. The reasons are : 
1) Guaranteed adherence of received specification to the runnin instance.
2) Security considerations. Document should be taken from the internal network.

I tried to append swagger.v1.json to my host URL and it works. Thanks again.

**Comment by jolheiser** [comment]
That was why it was an example.  
I didn't mean to suggest you use try instead of your instance. 😅 

Glad you got it working! 👍
