### ISSUE TITLE
gitea upgrade from 1.8.1 to latest version

### ISSUE THREAD

**Issue by premryp** [go-gitea/gitea#22495]
### Description

Hello,

I am using the older version of Gitea 1.8.1 now I am planning to upgrade to the latest version.

Already I tried by installing the latest version and restore the data and mysql to newer version and got issue that seems there is a lot of changes in sql tables.

so please guide me on how to upgrade from 1.8.1 to 1.18.1

### Gitea Version

1.8.1

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

I am running Gitea from binary

### Database

None

**Comment by lunny** [comment]
ref https://docs.gitea.io/en-us/upgrade-from-gitea/

**Comment by premryp** [comment]
> ref https://docs.gitea.io/en-us/upgrade-from-gitea/

Thank you so much. So I need to upgrade one by one version https://dl.gitea.io/gitea
