### ISSUE TITLE
Docker container prompting to install after updating

### ISSUE THREAD

**Issue by koalaeagle** [go-gitea/gitea#2249]
- Gitea version (or commit ref): docker:latest
- Git version:
- Operating system: Arch Linux
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

After recently updating my gitea docker container, the container is now leading to /install like when it was first installed. I have run into this previously when moving the location of my docker data, however, after fixing the mistake the container started working. I have 2 containers in this case (gitea and db_gitea - which is a postgres container). I have destroyed these containers before and re-created them to test that the data is persistent across updates. No configuration has been changed. I have an ansible playbook that updates the containers and nothing has been changed in it recently so the setup should be identical. I tried removing the containers and re-creating them but the issue persists.

I checked the data of the postgres container and the gitea container and everything seems to be there. Is there a specific configuration file that is setup after the initial install that it is looking for and failing to find? If so I can check on that file or files.

## Screenshots

In this case I can only reach the generic install page so I am not sure a screenshot would help.

**Comment by sapk** [comment]
Could you provide us more niformation like what mount point you us (docker run cmd or docker-compose.yml file) and what version of gitea. If you can the startup log or any information that could be usefull. 

For the insigth, after install gitea write the configuation to a file `/data/gitea/conf/app.ini` that should among others set `INSTALL_LOCK   = true` (https://github.com/go-gitea/gitea/blob/master/conf/app.ini#L194). If still set to false at startup the install page is displayed.

Maybe not related but there is a current issue with saving app.ini changes inside docker: go-gitea/gitea/issues/2197

**Comment by koalaeagle** [comment]
I have an issue opened with zfsonlinux in regards to issues mounting zfs datasets. Since my gitea data is stored inside one of these datasets I am retracting this issue since I can't be sure gitea is to blame. I will re-open if needed.
