### ISSUE TITLE
viewing dates requires mouse hover

### ISSUE THREAD

**Issue by Spongman** [go-gitea/gitea#22493]
### Description

- the commits page shows all dates as "1 month ago"
![image](https://user-images.githubusercontent.com/1088194/213005842-5c000f83-5e3e-4c97-9aac-850a56e388f6.png)

- requiring mouse hover to see the actual dates is a severe usability issue:
   - it's impossible to scan the whole page of dates
   - it's impossible to select/copy a date from a tooltip
   - tooltips don't work on mobile
- there needs to be a configurable option to display full timestamps instead of these useless relative dates/tooltips.

### Gitea Version

1.17.1

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

systemd

### Database

MySQL

**Comment by bkraul** [comment]
Second this. Very critical for audits.

**Comment by Spongman** [comment]
also, why are some of the tooltips custom html:
![image](https://user-images.githubusercontent.com/1088194/225759290-c2f6e44d-25de-4ef6-9583-b18b88730e72.png)

and some of them just browser tooltips:
![image](https://user-images.githubusercontent.com/1088194/225759571-ab21076f-aca0-4f1c-ac98-a19577afe128.png)

**Comment by lunny** [comment]
Is there any better solution or suggestion?

**Comment by bkraul** [comment]
>there needs to be a configurable option to display full timestamps instead of these useless relative dates/tooltips.

That would probably be best...but in its absence, is there documentation we are missing that shows us how to properly template this in such a way that it does what we are asking?

**Comment by yp05327** [comment]
> tooltips don't work on mobile

If click it, tooltips will display on my phone

**Comment by wxiaoguang** [comment]
> > tooltips don't work on mobile
> 
> If click it, tooltips will display on my phone

Maybe because we have a general "tippy tooltip" now (before, the "title" didn't work)

**Comment by lunny** [comment]
How should this be resolved?

**Comment by bkraul** [comment]
Using full dates is far more functional than relative dates. But, a setting to alternate between the two would probably work best. The referenced PR (now closed) seemed like it would have addressed.
