### ISSUE TITLE
Change history

### ISSUE THREAD

**Issue by stevefan1999-personal** [go-gitea/gitea#22501]
### Feature Description

In Github we can edit our comments but still get the previous version for comparison. 
![image](https://user-images.githubusercontent.com/29133953/213112603-455e5081-16c0-4f90-bac1-d97f6bf89f6d.png)
This will make understanding the context easier. 
Also, this is useful for webhook because right now it will show the full latest version of text...for example, I don't want to show my team a full stream of text chat on the dedicated Slack channel just because I made a typo...
![image](https://user-images.githubusercontent.com/29133953/213113095-934e1522-12fd-42e3-82e7-8d5691352bc8.png)

**Comment by delvh** [comment]
That functionality exists already since https://github.com/go-gitea/gitea/pull/16909 and thus since `1.16`.
(Perhaps except for the `issue edited` webhook which sounds like a bug/intended behavior and worthy of its own issue).
Please upgrade your instance to something later than `1.16`.

**Comment by stevefan1999-personal** [comment]
@delvh Should that be a bug report or a feature request?

**Comment by delvh** [comment]
I haven't quite understood what you meant by it in the first place, so I don't know?
Please explain it a bit more.

**Comment by stevefan1999-personal** [comment]
@delvh I mean the webhook for the issue edited, should that contain the full text or the diff body I guess. I'm not sure if that's a bug or some feature I should ask for.

**Comment by delvh** [comment]
I think it is intended behavior that it contains **the current message**.
Everything else is probably not useful for a recipient. If they would want to only show the changes, they are responsible themselves to ensure they know the previous state.

---

To me, it sounds rather like you don't want to receive webhooks for editing a message.
Given that I often edit my own messages, I would be annoyed to receive a notification for every message edit.
Typically, this doesn't change anything major about the message. If you want to change something major about it, you should probably use a new comment for it.

**Comment by delvh** [comment]
Not to speak of that the recipient would need to parse it themselves again.
So, overall, I'm rather against it.
