### ISSUE TITLE
Broken long commit message wrapping

### ISSUE THREAD

**Issue by TitaniumHocker** [go-gitea/gitea#22505]
### Description

If commit message is long it breaks index repo page layout

### Gitea Version

1.18.1

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

![image](https://user-images.githubusercontent.com/37049574/213151199-abcbef6d-1234-478a-9e62-a23ef6b8116e.png)

### How are you running Gitea?

Downloaded from github releases page and reproduced on test public instance.

### Database

PostgreSQL

**Comment by lunny** [comment]
duplicated with #22360

**Comment by TitaniumHocker** [comment]
@lunny Fix for this is already planned? There is no milestone for #22360
