### ISSUE TITLE
Using port 22 that is not the default for ssh requires adding a prefix

### ISSUE THREAD

**Issue by lmlx66** [go-gitea/gitea#22508]
### Description

When I use port 222 as the ssh request port, the ssh link prompt given to me by gitea is as follows`git@wfggit.com/222:1938857445/wfg-admin-vue.git`

But I need to add the prefix ` ssh://git` to use it，for example：`ssh://git@wfggit.com:222/1938857445/wfg-admin-vue.git`

This may be just a small problem

### Screenshots

![Snipaste_2023-01-18_21-35-15](https://user-images.githubusercontent.com/65378985/213185295-7218c913-82df-45e6-8bf9-9507b2743833.png)

### Gitea Version

1.18.0

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

windows10

### Browser Version

edge

**Comment by zeripath** [comment]
This used to be correct

**Comment by zeripath** [comment]
and it works on main...

**Comment by zeripath** [comment]
and it works on 1.18.1 on docker...

**Comment by zeripath** [comment]
What is your app.ini configuration?

**Comment by lmlx66** [comment]
> 
Unfortunately, my server system is broken, and I am trying to use the host to reproduce the problem.

**Comment by lmlx66** [comment]
> What is your app.ini configuration?

Sorry to bother you, it's my configuration error
