### ISSUE TITLE
Azure Blob Storage Support

### ISSUE THREAD

**Issue by siegenthalerroger** [go-gitea/gitea#22527]
### Feature Description

As MinIO has deprecated support for proxying s3 api requests to different types of cloud object storage, a new solution is required to support object storage. Specifically Azure does not support s3 (for a diverse range of reasons) but has an object storage solution (azure blob storage) which has an s3-like API available.

Seeing gitea support azure blob storage natively would be amazing.

**Comment by yp05327** [comment]
Azure has go sdk for blob storage, it is possible to support it.
https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/storage/azblob

ps: does MinIO's api has compatibility with aws s3 or google cloud storage?

**Comment by lunny** [comment]
> Azure has go sdk for blob storage, it is possible to support it. https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/storage/azblob
> 
> ps: does MinIO's api has compatibility with aws s3 or google cloud storage?

It should support aws s3
