### ISSUE TITLE
Long commit message can break single line tables

### ISSUE THREAD

**Issue by zakjan** [go-gitea/gitea#22548]
### Description

After upgrading from 1.17.3 to 1.18.1, a long commit message can break single line tables, the text is not truncated.

Reproduced on the demo site with Chrome, Firefox and Safari.

https://try.gitea.io/teeeeeest/test

### Gitea Version

1.18.1

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

<img width="1920" alt="Screenshot 2023-01-20 at 09 16 51 (2)" src="https://user-images.githubusercontent.com/173585/213659642-75d9dc0a-c422-4581-a0d7-3d8eb55d96e9.png">

### Git Version

1.18.1

### How are you running Gitea?

Demo site

### Database

None

**Comment by silverwind** [comment]
Duplicate: https://github.com/go-gitea/gitea/issues/22360
