### ISSUE TITLE
Docker - Add gnulibiconv

### ISSUE THREAD

**Issue by c1rc0le** [go-gitea/gitea#22550]
### Feature Description

We are currently using gnu-libiconv (alpine) to ensure the encoding of our code.

We use Git hooks configured as below : 
![image](https://user-images.githubusercontent.com/33677334/213667560-aa74141f-a482-415a-a7bd-3530be3fb7ac.png)

Would it be possible to integrate in Gitea official Docker image the package gnu-libiconv?

Thanks,

**Comment by lunny** [comment]
You can build yourself docker based on Gitea's

**Comment by zeripath** [comment]
As Gitea does not use iconv itself and most users don't use it it would be inappropriate for Gitea to distribute it - I'm sure we're currently including more packages than we need within the Gitea dockers (e.g. we probably should not be leaving apk within the docker itself) but we should really avoid adding more.

As lunny says you should create your own dockerfile using the Gitea one as a base (likely something like this but I have not tried this):

```dockerfile
FROM gitea/gitea:latest

RUN apk --no-cache add gnu-libiconv
```
