### ISSUE TITLE
Example App config has incorrect example Redis strings

### ISSUE THREAD

**Issue by tiny-pangolin** [go-gitea/gitea#22571]
### Description

In the redis connection string for the queue, session, and task configuration the example config in `custom/conf/app.example.ini` suggests using a connection string formatted like `network=tcp,addr=:6379,password=macaron,db=0,pool_size=100,idle_timeout=180` but gitea expects a uri like connection string like this `reddis://127.0.0.1:6379/0?pool_size=100&idle_timeout=180s`. If you follow the example in `custom/conf/app.example.ini` it causes gitea to throw errors or fail to start and does not match the [config cheat sheet](https://docs.gitea.io/en-us/config-cheat-sheet/#cache-cache) in the documentation.

### Gitea Version

1.18.2

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

OCI Image on Fedora 37

### How are you running Gitea?

I am running gitea in via podman compose on fedora 37 behind a traefik reverse along side ansible-semaphore and woodpecker ci. 

### Database

MySQL

**Comment by tiny6996** [comment]
that merge only fixes one place I just added an MR for all three spots I noticed the issue. I didn't try adding a queue.
