### ISSUE TITLE
Writing tag and clicking enter not working

### ISSUE THREAD

**Issue by Ethan-Nox** [go-gitea/gitea#22607]
### Description

Hi, 
When i'm inside an issue and i want to modify a tag i have a bug when typing the tagname and clicking enter. 
It just do a reload and not apply my tag

### Gitea Version

1.18.0

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

https://user-images.githubusercontent.com/60541446/214807733-0289f189-c7d7-4f22-99b3-582342622543.mov

### How are you running Gitea?

Gitea is build and host on a local server

### Database

None

**Comment by sillyguodong** [comment]
I was trying to find the JavaScript code for the `keydown` event bound to the item in dropdown.
But in the end, i was not able to locate the relevant code. 😔

**Comment by sillyguodong** [comment]
> I was trying to find the JavaScript code for the `keydown` event bound to the item in dropdown. But in the end, i was not able to locate the relevant code. 😔

I am guessing the code is in the` semantic.js `.

**Comment by brechtvl** [comment]
I've looked into this a bit but did not find a good solution so far. This change makes it so that on click the label is applied, though the menu still closes immediately:
```
diff --git a/web_src/js/features/repo-legacy.js b/web_src/js/features/repo-legacy.js
index 61f82c8..4a824d7 100644
--- a/web_src/js/features/repo-legacy.js
+++ b/web_src/js/features/repo-legacy.js
@@ -85,6 +85,7 @@ export function initRepoCommentForm() {
     let hasUpdateAction = $listMenu.data('action') === 'update';
     const items = {};

+    $(`.${selector}`).dropdown({action: 'select'})
     $(`.${selector}`).dropdown('setting', 'onHide', () => {
       hasUpdateAction = $listMenu.data('action') === 'update'; // Update the var
       if (hasUpdateAction) {
```

However this breaks filtering. For example if I have a label name `color/blue` it no longer matches `blue` but does still match `color`. The relation is unclear to me.

Combined with the previous change, the menu can be made to not close on enter like this:
```
diff --git a/templates/repo/issue/view_content/sidebar.tmpl b/templates/repo/issue/view_content/sidebar.tmpl
index f27bbb0..f4b0093 100644
--- a/templates/repo/issue/view_content/sidebar.tmpl
+++ b/templates/repo/issue/view_content/sidebar.tmpl
@@ -106,7 +106,7 @@
                        <div class="ui divider"></div>
                {{end}}

-               <div class="ui {{if or (not .HasIssuesOrPullsWritePermission) .Repository.IsArchived}}disabled{{end}} floating jump select-label dropdown">
+               <div class="ui {{if or (not .HasIssuesOrPullsWritePermission) .Repository.IsArchived}}disabled{{end}} floating jump select-label dropdown multiple">
                        <a class="text df ac muted">
                                <strong>{{.locale.Tr "repo.issues.new.labels"}}</strong>
                                {{if and .HasIssuesOrPullsWritePermission (not .Repository.IsArchived)}}
```
However there is a delay in the event handling. Pressing enter the first time does nothing, and the second time it activates the label that was meant to be activated the first time.

**Comment by wxiaoguang** [comment]
Try this one Make issue label dropdown support Enter #23014
