### ISSUE TITLE
Comment text lost when changing issue label

### ISSUE THREAD

**Issue by brechtvl** [go-gitea/gitea#22603]
### Description

To reproduce:
* Type text in comment field on an existing issue
* Add a label to the issue
* Page reloads and comment field is cleared

If you've spent some time typing out a detailed comment, this is not ideal.

It was caused by #20432. Before that the comment was preserved.

Tested on Firefox 109, Ubuntu Linux 20.04.

### Gitea Version

e8ac6a9 (main)

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

Built Gitea myself, and confirmed on try.gitea.io.

### Database

None

**Comment by wxiaoguang** [comment]
It's actually caused by this:

* https://github.com/go-gitea/gitea/issues/17705
