### ISSUE TITLE
Organization pages have different color of private/limited tag

### ISSUE THREAD

**Issue by yp05327** [go-gitea/gitea#22601]
### Feature Description

At people and team page, we have red private tag or orange limited tag, but at repo page, it is gray (basic).
I think it is better to set them into same color (basic).

I have [worked on this](https://github.com/go-gitea/gitea/compare/main...yp05327:gitea:set-org-visibility-class-to-basic).
If it is ok, I can create a PR for this.

### Screenshots

![people](https://user-images.githubusercontent.com/18380374/214489862-5463854d-6fb8-45ce-bbd2-88878d7fcd40.PNG)
![team](https://user-images.githubusercontent.com/18380374/214489871-55e34168-45fc-411e-90fd-28500a73bc49.PNG)
![repo](https://user-images.githubusercontent.com/18380374/214489869-2869f9b3-41fd-4475-81e6-3a803943f0d1.PNG)

**Comment by yardenshoham** [comment]
I agree
