### ISSUE TITLE
Access rights for repository shown as 'Read' despite writing is possible

### ISSUE THREAD

**Issue by lynix** [go-gitea/gitea#22602]
### Description

On the _Settings_ -> _Collaborators_ page of a repository the access rights for the team owning the repository is shown as 'Read'.

Members of the team can nevertheless push code and team repository access is set to 'Write' so I think it's just a visualization issue.

(Note: I cannot reproduce the issue on the demo site as I've got no right to create or modify teams there.)

### Screenshots

Team access level shown as 'Read':
![screenshot](https://user-images.githubusercontent.com/129653/214496885-f867ccd0-2ef0-4b90-9ca1-6344dec1bf29.png)

Team access level set to 'Write':
![screenshot2](https://user-images.githubusercontent.com/129653/214496901-51ebcb20-f54d-47bb-bbf4-db9d4868d369.png)

### Gitea Version

1.18.3

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

Arch Linux

### Browser Version

Firefox 109.0

**Comment by mwb455** [comment]
I have the same issue.

**Gitea Version** 
1.17.2

**Can you reproduce the bug on the Gitea demo site?**
No

**Operating System**
FreeBSD 13.1

**Browser Version**
Brave 1.4.6.153, Firefox 108.0.2

**Comment by HesterG** [comment]
Hi @lynix , right now the rule to compute the Access Mode is designed as: Return the minimal permission greater than "No Access" from the permission unit map except that all are "No Access". 
In your case, i assumed that one or more of the permission selected from the unit map is selected to be "Read", and hence the Access Mode is computed as "Read". 
If all units are selected to be "Write", then the Access Mode will be computed as "Write".

**Comment by lynix** [comment]
Thanks for the explanation, changing the access level for 'Releases' to 'No Access' made the collaborators summary show 'Write'.

That being said I'd like to add that I find this hidden computation very misleading. I'd wish to see something indicating that it is really not just 'Read', e.g. 'Mixed' with a mouse-over showing the differing unit permissions. Or add something indicating that it's the _minimal_ access level being displayed.

Anyways, closing this as it turned out to be user confusion and not a bug.
