### ISSUE TITLE
Organization team access control dont work

### ISSUE THREAD

**Issue by yp05327** [go-gitea/gitea#22600]
### Description

1. You need to have two account. One is admin user1, the other one is normal user2.
2. Use the admin account to create an organization,  and create a new repo.
3. Add a new team, set `Repository access` to `All repositories` and all unit to `No Access` except `Issue` or any other, this is not important.
4. Add user2 to this team
5. Use user2 to access the repo, and all unit can be accessed.

If you check the settings of the repo, you will see this team only has `Read` permission of `Issues`.
But user2 can access all units.

#### create new team
![team settings](https://user-images.githubusercontent.com/18380374/214482052-9624a6b0-bdc8-4fdb-9615-c1d909baedff.PNG)

#### add user2 to this team
![team user of the org](https://user-images.githubusercontent.com/18380374/214482056-463d08ff-5939-450c-b845-5dda68c4b9ac.PNG)

#### user2 can access all unit
![user2 can see the code](https://user-images.githubusercontent.com/18380374/214482059-97b5b4d7-5f65-41b7-9c11-0d7f4eb95bde.PNG)

#### the settings of the repo shows the new added team only has `Read` permission of `Issues`.
![repo settings](https://user-images.githubusercontent.com/18380374/214482049-c31909e5-55dd-4cbb-a924-9d22b0ae7dc2.PNG)

Tips:
try.gitea.io can't create organization so i tested this at gitea.com. All screenshots are taken at gitea.com, not my local server.

### Gitea Version

1.18.3, 1.19.0+dev-334-g0c048e554

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

run gitea-1.18.3-windows-4.0-amd64.exe on win10
&
gitea.com

### Database

SQLite

**Comment by lunny** [comment]
Because the repository is a public one, you need to change it to private.

**Comment by yp05327** [comment]
Change to private is correct.
Thanks.

**Comment by yp05327** [comment]
@lunny 
I think we can add some explanations to avoid making the same mistake again?

eg:
``` text
Allow Access to Repositories Sections*
The following access control options have no effect on the public repositories in this organization.
```

**Comment by lunny** [comment]
Could you help to send a PR for that? Thanks in advance.
