### ISSUE TITLE
Search in filenames

### ISSUE THREAD

**Issue by michaelfresco** [go-gitea/gitea#22615]
### Feature Description

I think that it would be amazing if Gitea could search in filenames.
Right now we only match the content of the files, but not the filenames.

**Comment by delvh** [comment]
That has already been implemented, and is even part of 1.18:
![image](https://user-images.githubusercontent.com/51889757/215051463-26482a68-08fa-4ce3-8c25-c691cba0ac84.png)
Simply have an indexer configured, and click on `Go to file` on your repo main page.

**Comment by wxiaoguang** [comment]
Actually, this issue is related to (dup)
* https://github.com/go-gitea/gitea/issues/9005#issuecomment-1173540420

**Comment by delvh** [comment]
@wxiaoguang So, even one more issue to close? :grin: 
I've just seen that you referenced the implementing PR already there, so why is the other one still open?
The summary you posted there is also fully implemented, so I can close the other one too, right?

**Comment by wxiaoguang** [comment]
No, they are different.

1. `Go to files` feature 
2. Search filenames by a search engine (globally)

1 related issues can be closed.

2 related feature hasn't been implemented yet, see the comments in 9005
