### ISSUE TITLE
Autolinking problem

### ISSUE THREAD

**Issue by michaelkuhn** [go-gitea/gitea#2261]
- Gitea version (or commit ref): v1.1.0-467-g34df9def
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes: https://try.gitea.io/4kr_5fc85lzjshor/4kr_5fc85lzjshor/wiki/Autolink

## Description

When using a link that contains something that looks like an issue number, Gitea does not convert the link correctly.

For example, `https://pthree.org/2012/04/17/install-zfs-on-debian-gnulinux/` is turned into a link to "issue 17", followed by `/install-zfs-on-debian-gnulinux/` (see reproduce link above).

Edit: This is due to `IssueFullPattern` in `markdown.go`.

**Comment by andreynering** [comment]
Fixed by https://github.com/go-gitea/gitea/pull/2292
