### ISSUE TITLE
Unexpected rich-text copy-paste

### ISSUE THREAD

**Issue by KN4CK3R** [go-gitea/gitea#22622]
Copy-pasting file contents from the normal file view
![grafik](https://user-images.githubusercontent.com/1666336/215104388-91fca819-9d0a-4713-b20f-6b9dc853f747.png)
results in the full markup content
```
<html><body>
<!--StartFragment-->

module ROME
--


<code class="code-inner"><span class="n">require</span> <span class="n">github</span><span class="p">.</span><span class="n">com</span><span class="o">/</span><span class="mi">01</span><span class="o">-</span><span class="n">edu</span><span class="o">/</span><span class="n">z01</span> <span class="n">v0</span><span class="p">.</span><span class="mf">1.0</span> <span class="o">/</span><span class="o">/</span> <span class="n">indirect</span>
</code><!--EndFragment-->
</body>
</html>
```
if pasted into some input fields (like the Github comment fields). Copy-pasting from Github files works as intended.

**Comment by silverwind** [comment]
I don't think the source page can control what is being copied, so this behaviour to also copy rich must be some heuristics done by the browser based on the tags present (like `pre` plays a role).

**Comment by silverwind** [comment]
> a rich-text input field (like the Github comment fields)

GitHub comment field is not rich text, it's just a `<textarea>`. Are you using any browser extensions that transforms it?

**Comment by KN4CK3R** [comment]
No browser extension used. Wrong wording on my side. It's still unexpected if I paste the content here, it comes with the html tags.

**Comment by silverwind** [comment]
Yeah, I can reproduce. I think this is a bug in GitHub's `paste` event handling, it does not happen with a regular text area. GitHub seems to try something smart when pasting and it fails in many cases.

**Comment by KN4CK3R** [comment]
If you are sure it's not Giteas fault we can close this issue. Just noticed that behaviour yesterday.

**Comment by silverwind** [comment]
The bug is surely not ours, but lets keep this open for further investigation.

**Comment by silverwind** [comment]
Reported it in https://github.com/github/paste-markdown/issues/80.

**Comment by silverwind** [comment]
Closing, Github bug.
