### ISSUE TITLE
Contradictory messages when deleting branch

### ISSUE THREAD

**Issue by kernie** [go-gitea/gitea#22624]
### Description

When I delete a branch on the Code -> Branch tab, a message pops up that this delete is permanent and cannot be redone.

After confirming I see the image below where I can restore the branch...

<img width="988" alt="grafik" src="https://user-images.githubusercontent.com/23321751/215121792-620d47c1-b233-40b6-b4f8-42b0237f1fab.png">

Whether or not this might work it would be better to have a more consistent wording.

By the way thanks for this great software!

### Gitea Version

1.18.3

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

Ubuntu 18.04

### How are you running Gitea?

Manual server installation with systemd

### Database

MySQL

**Comment by lunny** [comment]
It can be reverted in a very short time.

**Comment by kernie** [comment]
According to discussion at Crowdin (in German) for `repo:branch.delete_desc` there is a proposal to change it into:

"Deleting a branch is permanent after 'git cleanup task' was run (by default once per day). It <strong>CANNOT</strong> be undone. Continue?"

Is `options/locale/locale_en-US.ini` the right place to create a pull request?

**Comment by wxiaoguang** [comment]
Per https://github.com/go-gitea/gitea/pull/22696#issuecomment-1521036199
