### ISSUE TITLE
404 Response after successfully applying patch from diff file

### ISSUE THREAD

**Issue by pahofmann** [go-gitea/gitea#22621]
### Description

When applying a patch (via code tab -> Add File -> Apply Patch) the patch is applied correctly, but the server responds with a 404. The after creating the patch commit the redirect that 404s is for USER/REPOSITORY/branch/main/diff.patch, which does not exist of course.

I could reproduce it here:
https://try.gitea.io/pahofmann/patch-404-test/
After I applied the patch I was redirected to https://try.gitea.io/pahofmann/patch-404-test/src/branch/main/diff.patch

### Gitea Version

1.18.1

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

https://gist.github.com/pahofmann/fb2c2e9daa8ff8d2c846b85e1eca3598

### How are you running Gitea?

Fresh setup in container.

### Database

SQLite

**Comment by yp05327** [comment]
I reproduced this bug and got incorrect num of commits in the last version.
![image](https://user-images.githubusercontent.com/18380374/220496311-0497325a-cf0a-4611-91a3-ac632e576947.png)

**Comment by yp05327** [comment]
And the default commit name in form is `Update ''`, but the real commit name will be `Apply Patch`
![image](https://user-images.githubusercontent.com/18380374/220496808-aab3e35c-083a-4102-aa92-1342d155bfa8.png)

**Comment by yp05327** [comment]
I don't think this issue can be closed, as the main fix PR is https://github.com/go-gitea/gitea/pull/23056 which is not closed.
