### ISSUE TITLE
not have any activity when git push with reverse proxy auth

### ISSUE THREAD

**Issue by ifooth** [go-gitea/gitea#22638]
### Description

not have any activity when git push with reverse proxy auth

### Gitea Version

1.18.3

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

docker

### Database

MySQL

**Comment by lunny** [comment]
Could you provide more details?

**Comment by ifooth** [comment]
## 背景
- 不好意思，信息不全。补充下信息

动态一直是空的
![image](https://user-images.githubusercontent.com/1853121/215314166-844a420b-c417-45d6-8811-0305968830e7.png)

一直有commit
![image](https://user-images.githubusercontent.com/1853121/215314155-2fd7ba10-7d4e-4e96-a8cd-2feca1806eee.png)

## 其他
- 使用 docker 部署，一直有跟版本，具体是哪个版本出现的，已经不好确定了
- 看日志文件，没有异常日志
- 其他副作用是使用drone ci也不能正常触发(单独在设置里面测试webhook正常)

**Comment by lunny** [comment]
Please speak English
Please resync your hooks in your instance's admin panel.

**Comment by lunny** [comment]
Closed as no response so I think maybe you have resolved the problem. I will close this one and please feel free to reopen it if you have further problems.
