### ISSUE TITLE
Hide by label

### ISSUE THREAD

**Issue by kolaente** [go-gitea/gitea#2265]
It'd be nice if you could hide issues with a given label. I know it's already possible to filter by lables, so this would basically be the inverted version of it. I know i could simply filter by all labels except the ones i want to hide, but if you have 50+ labels, this is not very practical.
I dont know if this is already possible, if it's the case, please point me to the solution.

**Comment by davydov-vyacheslav** [comment]
I’d like to bring this issue up

I also like the proposal and agree with cases

**Comment by tastytea** [comment]
It is possible to exclude labels with alt+click in Gitea 1.13.0. I think this issue can be closed?

![screenshot_2021-01-24T03:16:30](https://user-images.githubusercontent.com/3681516/105619394-9482c900-5df2-11eb-862a-b8c04d96072e.png)
