### ISSUE TITLE
Count on Projects tab (clarify or remove?)

### ISSUE THREAD

**Issue by JVimes** [go-gitea/gitea#22657]
### Feature Description

I'm not sure about this number:

![image](https://user-images.githubusercontent.com/6148201/215351697-994652aa-2bd6-48e5-9a40-32de6373bed6.png)

It looks like an unread/open count. It makes sense for things that need to be addressed, but I think projects live indefinitely.

**Comment by delvh** [comment]
It is intended as `number of open projects`.
I don't think it should be removed.

**Comment by JVimes** [comment]
Can you help me understand the value to the user?

**Comment by delvh** [comment]
- Consistency with the other tabs
- indicates whether the project uses projects and how they use it
(`0 → No projects`,`1 → One project for everything`, `2+ → custom project structure`)

would be my spontaneous guess?

**Comment by JVimes** [comment]
Okay. I think it's styled to draw attention like an unread count. It makes me feel like there's something outstanding I need to address. As an informational element I think it's got too prominent of a placement (right on the tab, always visible).

**Comment by fsiddi** [comment]
Suggesting #22687 to address this.

**Comment by JVimes** [comment]
Thanks @fsiddi , that would address my main concern.

**Comment by fsiddi** [comment]
This has been addressed, so I suggest to close the issue.
