### ISSUE TITLE
Your ROOT_URL in app.ini is http://localhost:3000/ but you are visiting https://git.mydomain.com/

### ISSUE THREAD

**Issue by kc9ryt** [go-gitea/gitea#22659]
### Description

Hello,
I recently updated my git install to ver18 and now i am getting this error message. I have gone in and changed the app.ini file to my domain and restarted the service/server but the error still claims that it is not set.

### Gitea Version

1.18.0 built with GNU Make 4.1, go1.19.4 : bindata, sqlite, sqlite_unlock_notify

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![Screenshot](https://user-images.githubusercontent.com/3506952/215360421-91752ff6-252a-4b09-894a-4bdaed1eee4d.jpg)

### How are you running Gitea?

systemd

### Database

None

**Comment by jolheiser** [comment]
It should be in the `[server]` section.
https://docs.gitea.io/en-us/config-cheat-sheet/#server-server
