### ISSUE TITLE
Docker: Your ROOT_URL in app.ini is http://XXX.XXX.X:3000/ but you are visiting http://XXX.XXX.XXX.X:3002/ You should set ROOT_URL correctly, otherwise the web may not work correctly.

### ISSUE THREAD

**Issue by Raptor05** [go-gitea/gitea#22655]
### Description

Hello,
I've updated my github container from 1.16 to latest (1.18.3). Now I see the following error at the website:
`Your ROOT_URL in app.ini is http://XXX.XXX.X:3000/ but you are visiting http://XXX.XXX.X:3002/
You should set ROOT_URL correctly, otherwise the web may not work correctly.`

But since the docker container is forwarding the container port to the external port, it's not possible to set the port in the app.ini correctly.

### Gitea Version

1.18.3

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

1.18.3

### Operating System

Synology NAS with Docker

### How are you running Gitea?

Docker container

### Database

SQLite

**Comment by jolheiser** [comment]
It's not asking you to change the port, but the `ROOT_URL` setting in https://docs.gitea.io/en-us/config-cheat-sheet/#server-server

**Comment by Raptor05** [comment]
> It's not asking you to change the port, but the `ROOT_URL` setting in https://docs.gitea.io/en-us/config-cheat-sheet/#server-server

Yes I know. But if I'm changing the `ROOT_URL` setting in the app ini, I will not be able to open the gitea website anymore. Because inside the docker container, the 3000 is correct, but from outside I'm calling the gitea website with the port 3002. 
And gitea is not fine with it, when my URL in the browser is different from the app.ini settings.

**Comment by jolheiser** [comment]
`ROOT_URL` AND `HTTP_PORT` are separate settings.
The former is used for links/clone urls etc.
