### ISSUE TITLE
Include Git LFS objects in archives

### ISSUE THREAD

**Issue by ziembek** [go-gitea/gitea#22665]
### Feature Description

Repository archive downloaded via http does not include LFS objects ( only links to objects ).

Example request for download archive:
curl --url https://${USER_NAME}:${USER_TOKEN}@${URL}/api/v1/repos/${ORG}/${REPO}/archive/${TAG}.tar.gz --output - | tar -xz

The feature to include LFS objects in archive is present in github.com.

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/managing-git-lfs-objects-in-archives-of-your-repository

**Comment by lunny** [comment]
duplicated with #4773
