### ISSUE TITLE
maximum file size changed but not work.

### ISSUE THREAD

**Issue by cloudcache** [go-gitea/gitea#22662]
### Description

app.ini config
[attachment]
ENABLED = true
TEMP_PATH = data/tmp/
ALLOWED_TYPES = .zip
STORAGE_TYPE = local
PATH = data/attachments
FILE_MAX_SIZE = 2048
MAX_FILES = 5
or 
[attachment]
ENABLED = true
TEMP_PATH = data/tmp/
ALLOWED_TYPES = .zip
STORAGE_TYPE = local
PATH = data/attachments
FILE_MAX_SIZE = 2048
MAX_FILES = 5
Gitea version:
Powered by Gitea 当前版本: 1.14.1

### Screenshots

error msg: 文件体积（15.56 MB）超过了最大允许体积（4 MB）
upload attachment while create new release.

### Gitea Version

1.14.1

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

centos7 64bit

### Browser Version

both chrome/edge

**Comment by lunny** [comment]
You should use 
```ini
[attachment]
MAX_SIZE = 4
```
