### ISSUE TITLE
Bleve index should have max 1 queue workers

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#22689]
Per https://github.com/blevesearch/bleve/blob/master/index.go#L28-L33
bleve is not thread safe, so only 1 workers should be running.

**Comment by zeripath** [comment]
It is thread safe to call `index.NewBatch()` . The comment states that the `bleve.Batch` structure itself is not threadsafe and should be used in a single-threaded way. The only use of a `bleve.Batch` is as a `FlushingBatch`:

https://github.com/go-gitea/gitea/blob/main/modules/indexer/bleve/batch.go

These are used in a single threaded way:

https://github.com/go-gitea/gitea/blob/e81ccc406bf723a5a58d685e7782f281736affd4/modules/indexer/code/bleve.go#L284-L311

I think we need to see logs for this concurrency/race. AFAICS the use of `bleve.Batch` within in direct gitea code is correct. (I'm not ruling out misbehaviour relating to use of `rupture` - there may well be issues there.)

---

As an aside, just to prove that Bleve itself believes that it is threadsafe, it starts for itself around 4 worker go-routines:

https://github.com/blevesearch/bleve_index_api/blob/615d85c70e101ee9492853f37d87e9dbb75f6125/analysis.go#L32-L41

which can be seen as unassociated go-routines in processes stacktraces.

I'm not certain which init() function causes this - I've not looked hard enough yet - but starting go-routines within init is a fairly unpleasant behaviour.

**Comment by wxiaoguang** [comment]
Each batch for each worker, it is thread-safe.
