### ISSUE TITLE
Adding a reply to an outdated review appears to not post (but still does)

### ISSUE THREAD

**Issue by Daeraxa** [go-gitea/gitea#22691]
### Description

This is kind of a weird issue and extremely specific but the replication steps are simple. Essentially if somebody creates a review comment on a particular line of code in a PR then somebody attempts to reply to that comment but whilst doing so the PR is updated to mark the review as outdated then the reply button appears to do nothing but does in fact post the reply. Pressing it multiple times will reply multiple times.

Steps:
- Bob creates a PR
- Sally creates an inline review on a line of the PR
- Sally presses `reply` and leaves the box open (assume also if the screen is just left without refreshing).
- Bob creates a new commit that alters that line, marking the original comment as outdated and so it no longer shows on the `files changed` tab.
- Sally attempts to create the reply by entering content to the box and pressing `reply
  - Sally will note that there is no visual feedback. The box does not close and remains editable with the reply button active
- Sally presses the reply button a few more times (as it appears the action did not register the first time)
- Both note that on the PR `Conversation` tab the reply has posted equal to the number of times the reply button was pressed.

Either there should be confirmation that the reply posted or an error should appear saying that the user should refresh the screen.

I wasn't able to replicate this for some reason on the try.gitea.io site, oddly enough it seems to work correctly there...

Log attached
[log3.txt](https://github.com/go-gitea/gitea/files/10548926/log3.txt)

### Gitea Version

gitea-1.18.3-linux-amd64

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![image](https://user-images.githubusercontent.com/58074586/215828038-9cb1fe61-0a91-4026-acbe-8f50f6daf4cd.png)

### Git Version

2.34.1

### Operating System

Linux Mint 21

### How are you running Gitea?

From the Gitea binary `gitea-1.18.3-linux-amd64`

### Database

SQLite

**Comment by Daeraxa** [comment]
It appears that https://github.com/go-gitea/gitea/pull/20821 actually fixes this issue, I guess this PR is present in `try.gitea.io` but not on the latest release.

**Comment by zeripath** [comment]
Ah so #20821 should be backported to 1.18

**Comment by Daeraxa** [comment]
If this is still an issue to track then I can reopen if you want? Feel free to close again or whatever.
