### ISSUE TITLE
Cannot right or middle click notification background to follow the link

### ISSUE THREAD

**Issue by Daeraxa** [go-gitea/gitea#22692]
### Description

The notification area has both a text link and a background "box" that, when **left clicked**, both take you to the same location.
However **right** or **middle** clicking this box does not open a new tab or give you a context menu to open in a new tab like you get if you were to right or middle click the text.

### Screenshots

Right clicking the text:
![image](https://user-images.githubusercontent.com/58074586/215839180-eed70017-235e-4a4d-be1b-3438d26c5313.png)

Right clicking the box:
![image](https://user-images.githubusercontent.com/58074586/215839247-cba0e1cb-9768-4935-a560-50fc16cc8b45.png)

### Gitea Version

1.18.3

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

Linux Mint 21

### Browser Version

Firefox 107.0.1

**Comment by Daeraxa** [comment]
Currently the entire box *is* a link but you can't right or middle click it as I stated in the issue detail so either way, it is wrong.
And I disagree, I think the row *should* be clickable but it should have the same options available to it as the text link, GitHub uses this style too and is a pretty standard UI thing.

**Comment by HesterG** [comment]
One possible solution is to make the `<a>` tag displayed as `block`. However, `<a>` tag might not be able to take up the whole height of `<td>`.
