### ISSUE TITLE
How far behind is gitea compared to gogs?

### ISSUE THREAD

**Issue by xPaw** [go-gitea/gitea#227]
It looks like gogs had a lot of activity in recent weeks, including tons of fixes, are these merged yet or will be in gitea?

**Comment by lunny** [comment]
These fixes will be merged to gitea but currently are not.

**Comment by vtolstov** [comment]
I think the main question is how long waiting? If gitea can't merge from
gogs fast, gogs is more preferred solution now. When author be lost
again,when fork again.
11 сент. 2015 г. 12:59 пользователь "Lunny Xiao" <notifications@github.com>
написал:

**Comment by xPaw** [comment]
Why not create patches for gogs with some of the new features added in gitea?

**Comment by tboerger** [comment]
@xPaw you are absolutely welcome to help us with that.

**Comment by vtolstov** [comment]
also if gogs accept patches from gitea, merging between two project is more simple

**Comment by vtolstov** [comment]
as i'm understand main difference - gitea supports wiki ?

**Comment by tboerger** [comment]
Since gogs released pull requests wikis are the main difference, right.

**Comment by xPaw** [comment]
Then I guess it's better to move back to gogs if I don't use wiki?

**Comment by tboerger** [comment]
It's your decision. I trust more in gitea because it's not all related to a single guy that even rejects some ideas i brought up to integrate into gogs.

**Comment by tboerger** [comment]
I will invest my time into gitea and not in gogs.

**Comment by MorphBonehunter** [comment]
it seems that nobody invest time in gitea at the moment...
is this this project dead before the first "official" release?
could someone please made an statement on the project future?
Thanks!

**Comment by tboerger** [comment]
There had already been a statement that the effort gets into Gogs as @Unknwon is back and working actively on Gogs. He's accepting contributions as well, I'm currently working on the CI to autobuild all binaries ;)

**Comment by tboerger** [comment]
As a side note: Gitea started just because Gogs have been dead for some time. But that's not the case anymore.

**Comment by MorphBonehunter** [comment]
Thanks @tboerger for the explanation!
The intention behind gitea was clear to me, but it seems that i missed the statement about the "effort gets into Gogs". That sounds great!
As contributions are accepted is there any chance that the wiki feature will go into gogs?

**Comment by makhov** [comment]
@DWE, I think about it. It's about 10000 strings of code.

If I will have enough time, I'll do it. But I don't know when.
25 нояб. 2015 г. 4:30 PM пользователь "DWE" <notifications@github.com>
написал:

**Comment by tboerger** [comment]
@Unknwon would accept a wiki feature, but he would expect better code :D

**Comment by MorphBonehunter** [comment]
thanks for your comments

**Comment by makhov** [comment]
> @Unknwon would accept a wiki feature, but he would expect better code :D
@tboerger, should i take offense? xD

**Comment by tboerger** [comment]
> @tboerger, should i take offense? xD

Feel free to improve the code and do a PR against Gogs ;)

**Comment by linquize** [comment]
Gogs is back.  Continue to develop gitea or not ?
Seems inactive for some time.

**Comment by lunny** [comment]
Since Gogs is active, gitea will become a backup project. If Gogs is inactive, we can restart this project. @Unknwon @tboerger @linquize @makhov @fuxiaohei

**Comment by carwyn** [comment]
It's really good to see Gogs very active again with lots of collaboration. Thank you guys for working on this.

Could someone update/change the http://gitea.io/ website to let people know what's going on? It's very confusing at the moment.

**Comment by lunny** [comment]
gitea.io has beend redirected to gogs.io. @carwyn
