### ISSUE TITLE
JS error on try.gitea.io `Error: Syntax error, unrecognized expression: input[type='range'`

### ISSUE THREAD

**Issue by wxiaoguang** [go-gitea/gitea#22702]
### Description

https://try.gitea.io/wxiaoguang/test/pulls/6/files

![image](https://user-images.githubusercontent.com/2114189/215943961-cac6918f-dd76-4baf-81be-e2b17a2713d5.png)

### Gitea Version

dev

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

try

### Database

None

**Comment by zeripath** [comment]
Can't reproduce this myself right now.

**Comment by wxiaoguang** [comment]
But, the JS code is wrong .... since 2021-02-28

The `]` is missing.


![image](https://user-images.githubusercontent.com/2114189/216012448-8645ea18-8ecf-4fac-9a01-e13c7f013743.png)

**Comment by zeripath** [comment]
Weird that my browser isn't barfing on it.

**Comment by zeripath** [comment]
https://github.com/go-gitea/gitea/blob/72a83dcc82add7537d2f661aa929dd073ced65f3/web_src/js/features/imagediff.js#L266

**Comment by zeripath** [comment]
PR up.

**Comment by lunny** [comment]
Js lint cannot detected that problem.

**Comment by wxiaoguang** [comment]
> Weird that my browser isn't barfing on it.

Maybe new Firefox is more strict. I don't see this error on my Chrome either.
