### ISSUE TITLE
Too many menus on settings page

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#2271]
![-1](https://user-images.githubusercontent.com/81045/29010884-4619b99e-7b61-11e7-9ef7-03691df5952e.png)

**Comment by bkcsoft** [comment]
OpenID/External seems like we could merge them. 2FA should go under Pasword. Avatar under Profile.

**Comment by lafriks** [comment]
We could also merge SSH / GPG Keys and Applications into "Keys / Tokens"

**Comment by pgaskin** [comment]
Merge Profile and Avatar into Profile

**Comment by lunny** [comment]
should be a part of #1346

**Comment by daviian** [comment]
Unfortunately I was to late to review #2695 
Would like to rename "Security" to "Account" and add "Delete Account" as well.

**Comment by lafriks** [comment]
@daviian Delete account could be moved into `Profile` tab

**Comment by daviian** [comment]
@lafriks Profile is more like the publicly visible part of your account. Whereas `Account` holds the technical parts of it.

**Comment by lunny** [comment]
Rename `Email Addresses` to `Emails` ?

**Comment by daviian** [comment]
@lunny I think this would be great to put under my proposed "Account" tab

**Comment by lunny** [comment]
@daviian Yes, your idea is better.

**Comment by renothing** [comment]
I think left sidebar is better as original. top menu is tooo crowded

**Comment by pgaskin** [comment]
@renothing left menu does not work well on narrow screens. Also, as this issue says, there are too many menus (many can be combined).

**Comment by renothing** [comment]
flexible.js maybe usefull
top menu also works worse on mobile screen

**Comment by daviian** [comment]
I'll give it a shot and prepare an alternative menu / subpage structure for the settings page before actually implementing it.

**Comment by daviian** [comment]
So I came up with following structure:

- Profile
  - Avatar
  - Public Profile
- Account
  - Email Addresses
  - Password
  - Delete Account
- Security
  - TOTP
  - OpenID
  - Access Tokens
  - Linked Accounts
- SSH / GPG Keys
- Organizations
- Repositories

First level represents the menu items. Second level refers to items that are moved onto that page.

![settings-menu](https://user-images.githubusercontent.com/5477981/39547718-af983c18-4e58-11e8-898f-48ce57a4b0a3.png)

**Comment by daviian** [comment]
Any objection against above proposed menu readjustments?
Otherwise I'd love to create a PR.

**Comment by lafriks** [comment]
LGTM :)

**Comment by TangentFoxy** [comment]
@daviian Why have SSH / GPG separate from Security settings?

**Comment by daviian** [comment]
@Guard13007 At first I thought I move SSH / GPG Keys to Security as well, but hesitated because of the GPG Keys part as they don't have something todo with Security/Authentication.
But furthermore they have something in common with SSH Keys.
So I decided to keep them as they are. But I am open for discussion ;-)

**Comment by renothing** [comment]
I don't think current layout good enough still. Do not change for change, submenu need two steps for users, and horizontal layout crowded. if next a new option added, so will you add new subgroup again ??why don't change it back to sidebar menu like github or gitlab? it's simple and rational more than current.

**Comment by daviian** [comment]
Oh I don't change for a change, I really think that some menu items should be bundled together no matter if the submenu is horizontal or vertical.
Also a vertical submenu doesn't minimize the steps for a user compared to the horizontal one.
For clarity, there won't be any dropdowns. Just that the sections move to that page.

**Comment by TangentFoxy** [comment]
@renothing Having a vertical menu is a big disadvantage for those who need to work with smaller screens.

**Comment by TangentFoxy** [comment]
So screw the minority because you don't like the look of something? The horizontal layout isn't that overcrowded, and the suggested re-arrangement would solve that problem easily without having to resort to sacrificing usability on smaller screens.

Also, I said nothing about mobile phones, I said smaller screens. That said, I do often need to check things on my phone as well, so yes, on a mobile phone is useful too.
