### ISSUE TITLE
Misleading LFS_JWT_SECRET description

### ISSUE THREAD

**Issue by pboguslawski** [go-gitea/gitea#22727]
### Description

According to https://docs.gitea.io/en-us/config-cheat-sheet/#server-server 
```
LFS_JWT_SECRET: <empty>: LFS authentication secret, change this a unique string.
```
which is not true because [gitea requires](https://github.com/go-gitea/gitea/blob/98770d3db8198714789c3182c14950d365ae4fb1/modules/setting/lfs.go#L54) such string to be unpadded urlsafe base64 encoded 32 bytes, i.e. generated with
```
dd if=/dev/urandom bs=1 count=32 status=none | base64 | tr '/+' '_-' | tr -d '='
```
If it's not - gitea generates own value on startup and logs
```
2023/02/01 22:26:08 ...s/setting/setting.go:1318:CreateOrAppendToCustomConf() [I] Settings for server.LFS_JWT_SECRET saved to: "[...]app.ini"
```
If LFS_JWT_SECRET is longer than 32 bytes i.e. generated with
```
dd if=/dev/urandom bs=1 count=33 status=none | base64 | tr '/+' '_-' | tr -d '='
```
gitea will panic on startup with
```
2023/02/02 10:29:24 cmd/web.go:95:func1() [F] PANIC: runtime error: index out of range [2] with length 2
```
which is caused by https://github.com/golang/go/issues/54532 probably.

Consider fixing manual and handling panic.

### Gitea Version

1.18.3

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

from git

### Database

None

**Comment by lunny** [comment]
This should be fixed by https://gitea.com/gitea/docs/pulls/46
