### ISSUE TITLE
Allow force pushing to protected branch

### ISSUE THREAD

**Issue by timbze** [go-gitea/gitea#22722]
### Feature Description

At this point you can only force push when a branch is not protected.

Once a branch is protected, it can be limited like this:
1. no pushes
2. all with write access can push
3. only white-listed users can push

Under option 3 (next to "Whitelist deploy keys..."), I would like an additional check box: "Allow force pushing by whitelisted users"

![image](https://user-images.githubusercontent.com/35117769/216176539-e967917b-fcab-4b9f-949f-c6ab28637e1a.png)

**Comment by henrygoodman** [comment]
Bump, I have a workflow where I revert a squash commit if some CI tests fail, and I am unable to push normally (because the tip is behind the remote counterpart), and cannot force push due to branch protection.

Add a checkbox to also allow force push

**Comment by henrygoodman** [comment]
TY @lunny, would also just suggest (the original proposal could seem a bit ambiguous) that whitelisted deploy keys should have access to force push, as well as whitelisted users (if this is a common workflow for CI, then it is likely people are using SSH/Deploy keys for their git creds).

**Comment by sebastian-sauer** [comment]
Setting in gh:

![image](https://github.com/go-gitea/gitea/assets/1135157/75472920-954b-49e8-b3c0-f022ff3ea2c4)

**Comment by sebastian-sauer** [comment]
I'd like to implement this feature. Will open a PR for this soon.

**Comment by henrygoodman** [comment]
@sebastian-sauer just wondering if you were still going with this? I might have a crack if stale

**Comment by henrygoodman** [comment]
How about something like this?

![image](https://github.com/go-gitea/gitea/assets/79623665/2a6127a0-ab16-4d96-9105-1c2bf2cf3eeb)

**Comment by henrygoodman** [comment]
I'm just going to start implementing above and make any changes based on PR feedback 👍

**Comment by SoulSeekkor** [comment]
Looking forward to this, I have to force push rarely but it's annoying to have to rename a rule to do it and rename it back after it's pushed every time.

**Comment by henrygoodman** [comment]
PR is raised now, note the UI isn't _precisely_ what I originally had in mind, due to how the template handles the logic, and it was a lot easier to implement in a similar fashion to the `Push` section. Regardless, it should still function as expected

**Comment by Urth** [comment]
The proposed change is the only way to have functional feature branches that enforce signed commits. I would love to see this fixed. (the signed commit requirement is exclusive to protected branches...)
