### ISSUE TITLE
Chrome Browser on MacOS detects wrong language

### ISSUE THREAD

**Issue by xoxys** [go-gitea/gitea#2272]
- Gitea version (or commit ref): 1.1.3
- Git version: not relevant
- Operating system: CentOS 6
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X] No
  - [ ] Not relevant
- Log gist:

## Description
Chrome seems to display selfhosted gitea in chinese language instead of german/english. Browser settings in chrome looks good. Preferred language is set to german, second is english (US). Language is correctly displayed if i use Safari. try.gitea.io is not affected. This side is correctly displayed in Chrome. Is this bug allready fixed in master branch or are there some configurations issues on my side?

**Comment by pgaskin** [comment]
~~Possible duplicate of #2131~~

**Comment by lunny** [comment]
seems not the same one?

**Comment by xoxys** [comment]
Not the same. The browser does not ask to translate. The site uses only wrong language (chinese/japanese) insteat of browser settings (german/english).

**Comment by xoxys** [comment]
Seems to be fixed somewhere
