### ISSUE TITLE
Remove deprecated settings in v1.19

### ISSUE THREAD

**Issue by yardenshoham** [go-gitea/gitea#22736]
We should remove the deprecated settings as planned:

- [ ] [v1.18](https://grep.app/search?q=//%20FIXME%3A%20DEPRECATED%20to%20be%20removed%20in%20v1.18.0&filter[repo][0]=go-gitea/gitea)
- [ ] [v1.19](https://grep.app/search?q=//%20FIXME%3A%20DEPRECATED%20to%20be%20removed%20in%20v1.19.0&filter[repo][0]=go-gitea/gitea)

**Comment by lunny** [comment]
I think we need to still have a warning log like `the configuration has bee removed, please take a look at xxxx` as well.
