### ISSUE TITLE
Incorrect version tag for release versions

### ISSUE THREAD

**Issue by tgurr** [go-gitea/gitea#2273]
Currently the version tag is hardcoded in main.go and doesn't get updated when you do proper releases.

```
// Version holds the current Gitea version
var Version = "1.1.0+dev"
```

For git head of the current development branch a 1.1.0+dev seems fine but for a proper release like e.g. 1.1.3 the version tag should get updated accordingly.

**Comment by lunny** [comment]
You should use `make` to do that. You can test https://dl.gitea.io/gitea/1.1.3, the tag is correct.
