### ISSUE TITLE
There is an error viewing the LFS file

### ISSUE THREAD

**Issue by hiifong** [go-gitea/gitea#22734]
### Gitea Version

1.18.0

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

https://user-images.githubusercontent.com/89133723/216563144-e5cb3ef9-35d9-45e0-8977-f6385fa6575e.mp4

### How are you running Gitea?

./gitea web

### Database

MySQL

**Comment by Zettat123** [comment]
I'm trying to fix this bug.

**Comment by hiifong** [comment]
> I'm trying to fix this bug.

thank you very much
