### ISSUE TITLE
links in search results are not escaped

### ISSUE THREAD

**Issue by AndreaBorgia-Abo** [go-gitea/gitea#22740]
### Description

New gitea installation: 
Gitea-Version                
1.18.2 built with GNU Make 4.3, go1.19.5 : bindata, timetzdata, sqlite, sqlite_unlock_notify 
Git-Version                2.36.4, Wire Protocol Version 2 Enabled

We're trying to use it together with [abapGit](https://github.com/abapGit/abapGit) for custom developments on an SAP system.

Because of the way abapGit and SAP work, the resulting filenames on the gitea server (or on any git server) would have slashes in them: for this reason, during serialization and push they’re replaced by hashmarks as follows:

Original SAP object: /SOFTW/ZTOPREP (that would be program ZTOPREP under the /SOFTW namespace)
Serialized content on the git server: /src/#softw#ztoprep.prog.abap

So far, so good: both abapGit and gitea seem to be fine with it; when browsing folders on gitea, that also works ok: the hashmarks are escaped, links are active and lead to the correct object. Notice the "%23" in the lower left corner:
![browse_top](https://user-images.githubusercontent.com/25269970/216621911-eeaae555-6e6e-4739-a5f2-fb2efb14c818.png)
![browse_sub](https://user-images.githubusercontent.com/25269970/216621954-d64aafc3-7dc1-4965-a8ac-9f5b5666de5b.png)

The problem comes up in search results: here hashmarks are NOT escaped, so they end up working as anchors and lead to the wrong object, typically the toplevel folder / package
![search_empty](https://user-images.githubusercontent.com/25269970/216622475-8bf3e9ec-071b-4e79-b908-a68f4e24332d.png)
![search_top](https://user-images.githubusercontent.com/25269970/216622499-402b0914-69bc-4898-a385-1e2639084351.png)
![search_sub](https://user-images.githubusercontent.com/25269970/216622523-144b401d-f32c-4642-a7b6-83476e5de9f3.png)

Is it something that can / should be configured in our installation or just a bug / missing feature?

### Gitea Version

1.18.2

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

2.36.4

### Operating System

Ubuntu 22.04.1 LTS

### How are you running Gitea?

Running gitea/gitea:latest ( sha256:86b1df821fa31475f7720f2e8b86b386fb48a1acf40e941cd8d077a9230d4578 ) on Docker 20.10.23 (API: 1.41), with Postgresql 14.6-1.pgdg110+1

### Database

PostgreSQL

**Comment by wxiaoguang** [comment]
That's a bug.

I think #22741 will fix it.

**Comment by zeripath** [comment]
🤦Fortunately despite this being yet another escaping bug I don't think this could result in a security issue.
