### ISSUE TITLE
using docusaurus to manage document

### ISSUE THREAD

**Issue by a1012112796** [go-gitea/gitea#22745]
### Feature Description

I think it's better to migrate to using docusaurus for document manage.   In my view, It have more features, and it looks at least can help us resolve these two problems:

- Versioning document: https://docusaurus.io/docs/versioning
   - that will have full documents for each version, but will be a little duplicate also ...
-  [manage translations by crowdin](https://docusaurus.io/docs/i18n/crowdin)
   - as we all know, gitea's document for other language has been stable in a long time, I think using crowdin will welcome more contributor to help us update them.

an example site:
https://wails.io/docs/next/introduction/

**Comment by jolheiser** [comment]
You're in luck! https://gitea.com/gitea/gitea-docusaurus
