### ISSUE TITLE
 go build -o gitea_no_gcc  # code.gitea.io/gitea/modules/setting  modules/setting/setting.go:470:27: undefined: exec.ErrDot  note: module requires Go 1.19

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#22746]
### Description

 go build -o gitea_no_gcc  # code.gitea.io/gitea/modules/setting  modules/setting/setting.go:470:27: undefined: exec.ErrDot  note: module requires Go 1.19

ref: https://drone.gitea.io/go-gitea/gitea/66732/1/12

### Gitea Version

main

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

CI

### Database

None

**Comment by jolheiser** [comment]
Odd...https://github.com/go-gitea/gitea/blob/c2774d9e80d9a436d9c2044960369c4db227e3a0/.drone.yml#L112

**Comment by jolheiser** [comment]
Worked after updating branch. 
https://drone.gitea.io/go-gitea/gitea/66737/1/12

Other CI failures were likely related to faulty merge resolution.
