### ISSUE TITLE
[Makefile:902: generate-images] Error 1

### ISSUE THREAD

**Issue by jelebruh** [go-gitea/gitea#22768]
### Description

I want to generate images. Type `make generate-images`.
I get 
```
npm ERR! code 1
npm ERR! path /home/gitea/test/gitea-1.18.3/node_modules/zopflipng-bin
npm ERR! command failed
npm ERR! command sh -c node lib/install.js
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/gitea/.npm/_logs/2023-02-05T17_42_34_758Z-debug-0.log
```
Full log below

npm 9.3.1
nodejs 18.14
go 1.19.5
### Gitea Version

1.19.0-dev, builded 4 feb., also tested 1.18.3 in releases

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://jelebruh.xyz/cfiles/gitealog.txt

### Operating System

Ubuntu 22.04

### How are you running Gitea?

Service with binary

### Database

PostgreSQL

**Comment by yardenshoham** [comment]
It works for me in (developing on Gitpod)

**Comment by techknowlogick** [comment]
What does the complete log in  /home/gitea/.npm/_logs/2023-02-05T17_42_34_758Z-debug-0.log say?

**Comment by KOT4N** [comment]
> What does the complete log in  /home/gitea/.npm/_logs/2023-02-05T17_42_34_758Z-debug-0.log say?

check log gist, this is it

**Comment by techknowlogick** [comment]
@KOT4N Ah, my apologies, I missed that.

**Comment by wxiaoguang** [comment]
It doesn't seem to be related to Gitea. But it's highly likely to be related to NPM or your SNAP or package zopflipng-bin

Use a native nodejs installation to have a try.

**Comment by KOT4N** [comment]
> Use a native nodejs installation to have a try.

Sorry, but idk how to do it.
I reinstall node and get
https://jelebruh.xyz/cfiles/gitealog2.txt

**Comment by wxiaoguang** [comment]
It seems that your local package cache might be broken. A fresh clone & make always succeed.

According your error message, there is no `canvas` package on your side. You may try to manually install it:

```
npm install --no-save --no-package-lock fabric@5 imagemin-zopfli@7 canvas@2
node build/generate-images.js
```

**Comment by KOT4N** [comment]
> ```
> npm install --no-save --no-package-lock fabric@5 imagemin-zopfli@7 canvas@2
> node build/generate-images.js
> ```

I clear `/home`, delete repo folder, reinstall node with purge all libs and get HTMLConvasElement again

**Comment by wxiaoguang** [comment]
No more idea from my side because I can not reproduce it.

ps: HTMLConvasElement is provided by the `canvas` package, it seems that you are near to succeed, but I do not know whether there are other factors affecting in your environment.

**Comment by KOT4N** [comment]
Maybe I help anyone with my solution
I scan logs and what understand:
Need gulp
Need canvas

I'm use `npm install canvas`, get HTML error. 
Install `gulp`, get errors. Then I google error, found solution. 
`npm install gulp@4.0.2 --force`
Then I type `npm install canvas`, get HTML error again.
Then I google `canvas`, founded method in wiki. 
`sudo apt-get update`
`sudo apt-get install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev`
Then `npm install canvas` and it works without error.

After this `make generate-images` worked normally.

**Comment by KOT4N** [comment]
Close as completed, thanks everyone for the tip and help.

**Comment by wxiaoguang** [comment]
I think I understand the problem now.

`canvas` package will download the binaries for supported OS/arch automatically. So in most cases, developers do not need to do anything manually. At the moment, only macOS/Linux/Windows on x64 are supported. https://github.com/Automattic/node-canvas/releases

However, if you are using an unsupported OS/arch (or build from source, or something else doesn't match the pre-built release), then you need to install the `lib*-dev` packages to make npm build the packages from source.
