### ISSUE TITLE
Total count of repos

### ISSUE THREAD

**Issue by Morlinest** [go-gitea/gitea#2277]
I need total count of repos to fix dashboard UI. Gitea returns (api/v1/repos/search) only array of repos but I do not know if there are more. I think we should add "Total" (or something like this) to api.SearchResults (code.gitea.io/sdk/gitea).

**Comment by Morlinest** [comment]
Another option is to set header like "X-Total-Count".

**Comment by sapk** [comment]
This would help if we paginate results later.

**Comment by Morlinest** [comment]
I've implemented it in header in my fix for now (very simple - `ctx.Header().Set("X-Total-Count", fmt.Sprintf("%d", count))`), but I want to resolve #2278 first.

**Comment by bkcsoft** [comment]
@Morlinest Please don't prefix with `X-` (rather use `Gitea-`) since that has been depricated from the HTTP specs: https://tools.ietf.org/html/rfc6648

**Comment by bkcsoft** [comment]
And actually, there's the `Link`-header for pagination, so please use that...
- https://developer.github.com/v3/guides/traversing-with-pagination/
- https://tools.ietf.org/html/rfc5988#section-5.5

**Comment by Morlinest** [comment]
@bkcsoft Thanks for your opinion. I can use `Gitea-Total-Count` too, real question is about right way to pass information from server to client (I know there is some deprecation, but it's often being ignored). I think, including `TotalCount` in response body is better way (also don't know, why gitea responds with `ok` field, response status code should be used instead). Example of response:
```
{
    data: [],
    total_count: 0
}
```

`Link` header is for pagination links, not for `total count`. It doesn't contain exact number, only pages. Also this header should be present there (it is in code), but right now it is not working.

**Comment by bkcsoft** [comment]
@Morlinest The API exposes this, but `code.gitea.io/sdk` does not unfortunately. I've yet to find a good way to support it either without breaking compatability 🙁

**Comment by lunny** [comment]
should be fixed by #2285
