### ISSUE TITLE
Global webhook

### ISSUE THREAD

**Issue by wenerme** [go-gitea/gitea#22788]
### Feature Description

I think it would be great if gitea has a global webhook, use cases

1. use gitea as a mirror to trigger webhook for any repo, due to github do not support external webhooks.
2. use gitea as corp private forge, a global webhook can used to trigger some automate functions.

org level webhook is not enough if

1. want to mirror github
2. don't limit user to one org

e.g.

I want to trigger webhook for grpc, frp, rclone etc.. to auto upgrade alpine aports, script is [here](https://github.com/wenerme/wode/blob/main/packages/alpine/src/aports/upgrade.ts) , use cron to pull every repo is too much.

**Comment by jolheiser** [comment]
Gitea already supports system-level webhooks. 
https://docs.gitea.io/en-us/webhooks/
You can find them on your instance (as an admin) via `<BASE_URL>/admin/hooks`

**Comment by delvh** [comment]
(Isn't that only from 1.19 on?
Or what was the PR about it that was merged recently?)

**Comment by jolheiser** [comment]
System-wide webhooks have been supported since [1.12](https://github.com/go-gitea/gitea/pull/10546)

I can't think of any specific PR, other than the ARIA changes that touched the webhook pages.

**Comment by delvh** [comment]
Ah, what I thought of was #14537.
