### ISSUE TITLE
Dashboard repo UI

### ISSUE THREAD

**Issue by Morlinest** [go-gitea/gitea#2278]
Hi, I have fix for dashboard (show only rendered UI, not vue templates). I've done some improvements, but need to discuss 2 options (or find another one).

Animated GIF of my first variant (I used throttling GPRS in chrome and refresh page few times):
![2017-08-08_10-27-17](https://user-images.githubusercontent.com/12720041/29070523-0bb2e318-7c40-11e7-8550-8462c4d5be1e.gif)

Second variant (logic is same, but render only 1 mixed list instead of 2):
![image](https://user-images.githubusercontent.com/12720041/29070484-e38d128c-7c3f-11e7-880b-5321f221f23f.png)

I do not like the mixed version with showed name ("My repositories") and repos count (it counts only my own repos, but showing all available). In this variant can be shown total repos found (after filter/search) or total count (when filter is empty). One of this method can be used also for showing "Show more repositories..." link.

What do you think?

Recap of questions:

1. Show 1 mixed list or 2 lists of repositories (my own and available)
2. If showing 1 mixed list:
     a. Naming - is "My Repositories" ok?
     b. Counter - show number of all repositories based on last search (= dynamic value) or show number of all available repositories (= static value, number can be saved from first/every empty search)
3. "Show more repositories..." link - show based on total count or filtered count

**Comment by lunny** [comment]
1 and 2:  Show 1 mixed list, but we can learn something from Github
![-1](https://user-images.githubusercontent.com/81045/29079656-4e80b0f8-7c90-11e7-96b5-12f0fb545591.png)

We can also add a submenu on `My Repositories` which have three menus, `All`, `Sources`, `Collbrative`

3: I think the number should be a static value of all repositories. We haven't a `My Repositories` page, so "Show more repositories..." is no need currently.

**Comment by Morlinest** [comment]
1: Github shows 2 lists, "Repositories you contribute to" and "Your repositories". Second one has few filters, that can be easily added later.
2: OK, static value.
3: That link is not new, it is in code (it's pointing to user page, with search box and sort options).

**Comment by lunny** [comment]
1. Yes, I mean the second one, "Repositories you contribute to" will not be implemented, we can ignore that currently.

**Comment by Morlinest** [comment]
@lunny OK

What type of filter is `Sources`?

**Comment by lunny** [comment]
`Sources` mean all the repositories in your name except mirrors, forks. It's the same concept as Github.

**Comment by Morlinest** [comment]
What do you think about this?

1.)
![image](https://user-images.githubusercontent.com/12720041/29121297-46390a8e-7d0e-11e7-97ab-e4a64eac55c3.png)

or 

![image](https://user-images.githubusercontent.com/12720041/29121508-109c3eea-7d0f-11e7-878f-1da530a45a09.png)

2.)
![image](https://user-images.githubusercontent.com/12720041/29121307-5099df4e-7d0e-11e7-8e97-e8232456ab6d.png)

First one is without any css modification (pure semantic ui classes), second one with 2 new classes (not expert in semantic ui, I could not find better solution = any help is welcome :)).

**Comment by lafriks** [comment]
I like second one better

**Comment by Morlinest** [comment]
@lunny If you like it, I can send PR with changes.

Animated gif (with throttling):
![2017-08-09_15-23-13](https://user-images.githubusercontent.com/12720041/29123807-429932ce-7d17-11e7-8f6f-f272a089684f.gif)

Animated gif (full speed):
![2017-08-09_15-26-24](https://user-images.githubusercontent.com/12720041/29123809-442826b8-7d17-11e7-8caf-a44df81956b5.gif)

**Comment by Morlinest** [comment]
Added `Forks` filter

![image](https://user-images.githubusercontent.com/12720041/29124731-00895e92-7d1a-11e7-93ba-32053e1efb66.png)

**Comment by lafriks** [comment]
Sure send PR and than we can probably help also with semantic ui css :)

**Comment by lunny** [comment]
@Morlinest Please do it. I wish it could be merged into v1.2 and then the PR will also fix #2114 and replace #2205

**Comment by lunny** [comment]
But maybe lack of some codes on search condition about collobratives on #2205.

**Comment by Morlinest** [comment]
@lunny I think #2205 can me merged too. There are some other improvements. I can rebase my PR.

**Comment by pgaskin** [comment]
I like the third one

**Comment by lunny** [comment]
closed by #2285
