### ISSUE TITLE
Migrated github issues incorrectly labeling all users as owner

### ISSUE THREAD

**Issue by tuxracer** [go-gitea/gitea#22797]
### Description

All users in all issues are incorrectly labeled as "owner" for a project migrated from github. For example, see:

migrated: [tuxracer/react-canvas#169](https://gitea.com/tuxracer/react-canvas/issues/169)

source: https://github.com/Flipboard/react-canvas/issues/169

### Gitea Version

1.19.0+dev-403-gb6b8feb3d

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

**Gitea:**

<img width="860" alt="Screenshot 2023-02-06 at 18 21 19" src="https://user-images.githubusercontent.com/788539/217131601-3d3049eb-5b17-4cea-89ad-4af5b09be672.png">

**Github:**

<img width="860" alt="Screenshot 2023-02-06 at 18 21 38" src="https://user-images.githubusercontent.com/788539/217131608-fff958ed-221f-420a-bf7c-642cd26371b3.png">

### How are you running Gitea?

gitea.com

### Database

None

**Comment by Zettat123** [comment]
I will try to fix this bug
