### ISSUE TITLE
The checkbox in repositories filter of dashboard will always be empty after click

### ISSUE THREAD

**Issue by yp05327** [go-gitea/gitea#22800]
### Description

the checkbox of `private` and `archived` will always be empty after click.
if you refresh the page, it will show rightly.

Im trying to fix this.

![image](https://user-images.githubusercontent.com/18380374/217165937-6943264b-8d7e-439a-9c92-40b1359e2ba4.png)

after click, `title` is same but the checkbox is empty
![image](https://user-images.githubusercontent.com/18380374/217165997-890c3f5e-f489-401d-8192-ea765eec3d53.png)

### Gitea Version

1.19.0+dev-442-g3ae78bc0a

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

try.gitea.io
gitea.com

### Database

None

**Comment by wxiaoguang** [comment]
The problem is mixing Vue and Fomantic UI together improperly.

In history, the code was not well but it just worked.

After upgrading to Vue3, the template is splitted into a `<template>` tag, then the Fomantic UI JS doesn't work on these checkbox elements correctly anymore.

**Comment by yp05327** [comment]
According to my test, these checkbox elements will be updated by Fomantic UI's Function correctly:
https://github.com/go-gitea/gitea/blob/d5fa2e7510844ad092804b7c11bf6847f7c4e45d/web_src/js/components/DashboardRepoList.js#L159-L190

But after get the response of searchRepo, they will be updated by something. Maybe by Vue?
Because `v-if` is used in template file to set the title:
https://github.com/go-gitea/gitea/blob/d5fa2e7510844ad092804b7c11bf6847f7c4e45d/templates/user/dashboard/repolist.tmpl#L49-L98

I tried to remove `v-if` so that the checkbox worked, but the title was missing.
Are there any other ways to fix this?

**Comment by wxiaoguang** [comment]
The only correct way:

Do not mix them together.
