### ISSUE TITLE
Error 500 can't open an issue or a pr

### ISSUE THREAD

**Issue by odybhoja** [go-gitea/gitea#22809]
### Description

The problem happen when opening a new issue i get the error 500 page. The same thing happen when i try to open a PR.
It's a brand new installation. 

### Gitea Version

1.18.3

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.githubusercontent.com/0xOdy/071bdd821fca7dfb6a75bc564e4ccc1f/raw/699fae4753f8be9b620df802c0d2dd62d10e64c2/gitea.log

### Screenshots

![Screenshot from 2023-02-07 14-32-21](https://user-images.githubusercontent.com/80256731/217274868-cafe83e4-cf2c-4573-bc3e-8c9deae97f01.png)

### Operating System

linux centos

### How are you running Gitea?

from a docker image ( gitea/gitea )

### Database

PostgreSQL

**Comment by jolheiser** [comment]
What version of postgres do you have? Also are there postgres logs?

**Comment by wxiaoguang** [comment]
The answer is clear: the postgresql verson is too old.

I have talked with @lunny  about this problem long ago, about adding database version checks

**Comment by 0xOdy** [comment]
Thanks you,
Will be upgrading postgresql

**Comment by lunny** [comment]
> The answer is clear: the postgresql verson is too old.
> 
> I have talked with @lunny about this problem long ago, about adding database version checks

XORM now supported returning the database version, but I think many users maybe use a customized database. So we cannot prevent users to use Gitea according to that versions.

**Comment by wxiaoguang** [comment]
> So we cannot prevent users to use Gitea according to that versions.

1. Then Gitea doesn't run well, how would the users think? It just hurts users.
2. Gitea itself already declared that "PostgreSQL (>=10)", https://docs.gitea.io/en-us/database-prep/

**Comment by 0xOdy** [comment]
Working great after installing postgresql-server-12 on my system.
THnaks a lot.

**Comment by zeripath** [comment]
Perhaps we can use `SHOW server_version;` and parse the output in someway in order to tell people they're running too old a version of Postgres?
