### ISSUE TITLE
Avatar and labels misalignment

### ISSUE THREAD

**Issue by fsiddi** [go-gitea/gitea#22818]
### Description

Up to Gitea 1.16, avatar and labels were aligned correctly. Since the refactoring of the Avatar component, styling breaks in element listings (e.g. users, organizations, etc). 

This issue is easily fixed by:

* replacing the `vm` class with `image` in the avatar component
* or adding `display: inline-block` to the `content` div next to the avatar

This breaks in other places, such the landing page of a repo.

## Gitea 1.16
<img width="1204" alt="image" src="https://user-images.githubusercontent.com/451841/217538053-9f648389-6f5d-417a-a6e3-42a190f8522d.png">

## Gitea 1.19
<img width="1183" alt="image" src="https://user-images.githubusercontent.com/451841/217537909-2b3535ba-53ff-4588-8f77-78664ad9195c.png">

### Gitea Version

1.19

### Can you reproduce the bug on the Gitea demo site?

Yes

### Browser Version

Chrome 109.0.5414.119

**Comment by wolfogre** [comment]
Related to #21145. I am not sure if we should add `image` back.

@silverwind Could you please take a look?

**Comment by wxiaoguang** [comment]
Another avatar misalignment is here:

![image](https://user-images.githubusercontent.com/2114189/218061841-742fa1de-6d17-4b85-b271-0def55c15b27.png)
