### ISSUE TITLE
Navbar is incorrect when select Projects or Code of an org

### ISSUE THREAD

**Issue by wolfogre** [go-gitea/gitea#22817]
### Description

![image](https://user-images.githubusercontent.com/9418365/217499620-4b8e8fbb-f2ef-48e6-a1aa-6ef0d1293d21.png)

### Gitea Version

1.19.0+dev-399-g72a83dcc8

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

./gitea web

### Database

SQLite

**Comment by yp05327** [comment]
Same as https://github.com/go-gitea/gitea/issues/22676
