### ISSUE TITLE
Merge message template and close issue references cause 500 error

### ISSUE THREAD

**Issue by brechtvl** [go-gitea/gitea#22821]
### Description

In a new repository 
* Create `.gitea/default_merge_message/SQUASH_TEMPLATE.md` with contents for example:
```
${PullRequestTitle}
```
* Create an issue
* Create a pull request with title `Fix #1`
* 500 error when going to the pull request page

It's crashing at `services/pull/merge.go:101` while constructing `$ClosingIssues` for the template.

Can be seen here:
https://try.gitea.io/brechtvl/test/pulls/2

### Gitea Version

5ae07d4 (main)

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

Both self built and try.gitea.io.

### Database

None

**Comment by wxiaoguang** [comment]
The fix seems to be adding a call to `ref.LoadIssue(ctx)` before `closeIssueIndexes = append(closeIssueIndexes, fmt.Sprintf("%s %s%d", closeWord, issueReference, ref.Issue.Index))`

```
						if err = ref.LoadIssue(ctx); err != nil { return .... err }
						closeIssueIndexes = append(closeIssueIndexes, fmt.Sprintf("%s %s%d", closeWord, issueReference, ref.Issue.Index))

```
