### ISSUE TITLE
1.2.0 release question

### ISSUE THREAD

**Issue by xoxys** [go-gitea/gitea#2283]
Hi guys,
first i want to say thank you for your great work. The second question is: When is 1.20 released? :D Please don't missunderstand me. I know its done when its done and this. But i look periodically at the milestone list and i was very happy as i see 99% completed for 1.2.0 :) but after a few weeks the status was dropped down to 89%, damn! I noticed this behavior over month till now. Is there a reason why you add more and more issues to current milestone? Are these all critical issues and have to be fixed absolutely before the release is ready? 

Remember, i dont want to stress you guys but i try to understand the doings behind the scenes :) There are nearly 600 fixed issues why not release a new version and give all these fixes to the users and work on next minor version? Or is this an issue of dependencies?

**Comment by lunny** [comment]
Bugs is always fixing. @xoxys maybe you are right. We should keep some minor bugs and release 1.2 ASAP.

**Comment by sapk** [comment]
The goal is to deliver 1.2.0 bug free (or with a minimum of it) some link to new feature introduced in this version. All non ready PR as been drop from milestone and there is only fews bugs to fix. It should be planned to be release before the end of August.

Milestone link : https://github.com/go-gitea/gitea/milestone/3

**Comment by xoxys** [comment]
@sapk I know the milestone list :) but from day to day new issues are added to the current milestone. Bug free is nice but there are 73 open issues labeled as "bug" and i think more bugs are found every day. So waiting for a "near bug free release" will be a never ending story ;) in my mind there must be a deadline for new issues for the current milestone after this deadline no issues will be added till release (excepted critical security issues) but this is still in my mind. But again i am not an software developer and the maintainer does a great job. Just trying to understand.

**Comment by sapk** [comment]
like @lunny said maybe we put to much pression on delivering with minimum bug.

**Comment by sondr3** [comment]
I think the way you're developing is fine, but the wait between releases is pretty long. Maybe consider doing smaller releases more often instead of a few big ones here and there? Focusing on delivering with as few bugs as possible is a very laudable goal, but with software you'll just keep finding more and more as the size of the project grows. It's a tough thing to balance, but I'd prefer smaller, more focused releases with one or two new features and a bunch of bug fixes that come somewhat frequently compared to the current pace. 😃

**Comment by lafriks** [comment]
@sondr3 there are currently known issues that will break upgrading from older versions leaving instance in unstartable state, so this is quite critical. For other issues I agree can be moved to later (1.2.1 etc)

**Comment by sondr3** [comment]
Yeah, I completely agree, I was just making a comment on the release schedule more so than the actual development -- which I think is completely fine as is, it's just the releases that are a bit slow in my opinion.

**Comment by xf-** [comment]
I think developer should create the best release possible. No frustration for new user or broken instances. Updates need time and testing. Rushing a software and update every few days with fixes will annoy sysadmins.

Massive changes in issue count often results out of 1 issue + 1 PR per FIX

PS: I also can't await 1.2 - but i tried the git version. Compile it yourself and help testing :)

**Comment by xoxys** [comment]
@xf- Not my opinion. Nobody talks about daily or monthly releases. But there are hundreds of fixed issues and bugs and i think sometime you must have a break an release a new version to bring these fixes to the users. Using the master branch is no option for production environments.

**Comment by techknowlogick** [comment]
Can this ticket be closed?
