### ISSUE TITLE
Create diff of single file between two freely choosable commits

### ISSUE THREAD

**Issue by mxmehl** [go-gitea/gitea#2284]
## Description

At the [FSFE](https://fsfe.org) we switched from trac/SVN to Gitea to maintain our website. With trac, our voluntary translators were able to see the diff of a file between two freely choosable commits. 

For example, with the file [work.en.xhtml](https://git.fsfe.org/FSFE/fsfe-website/commits/master/work.en.xhtml) we would like to see the difference between the current version/latest change (`4e89fd20cc`) and a freely choosable other date/commit (e.g. `d25c06af1e`).

[In trac, this diff](https://trac.fsfe.org/fsfe-web/changeset?new=32843%40trunk%2Fwork.en.xhtml&old=29198%40trunk%2Fwork.en.xhtml) is quite helpful for translators to know which bits have changed in a file over a certain span of time to update an outdated translated version.

This feature request is possibly related to #1481 and #1352.

Thanks <3

**Comment by lunny** [comment]
I think this is duplicated with #1352. Let's discuss continue there.
