### ISSUE TITLE
set DISABLE_DOWNLOAD_SOURCE_ARCHIVES to true, but still can download from UI

### ISSUE THREAD

**Issue by schmurtzm** [go-gitea/gitea#22849]
### Description

After set DISABLE_DOWNLOAD_SOURCE_ARCHIVES = true in app.ini file， and restart gitea. But it's still there.
Same issue : https://github.com/go-gitea/gitea/issues/20685 , I saw the fix https://github.com/go-gitea/gitea/pull/20701 but still the same problem on Gitea 1.8.3 (Windows 64 version :  `gitea-1.18.3-gogit-windows-4.0-amd64.exe` )

It's annoying because on big repo this functionality try to zip all the repo which can break server performances.

### Screenshots

![image](https://user-images.githubusercontent.com/7110113/218056795-40d12060-45d4-4f3e-8118-d1ee600da6f5.png)

### Gitea Version

1.8.3

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

Windows

### Browser Version

FF 109.0.1

**Comment by wolfogre** [comment]
However, if you click the button, you will see there's no download link:

<img width="336" alt="image" src="https://user-images.githubusercontent.com/9418365/218064706-93d5f10b-982d-4a0c-ae8a-72e64cc41714.png">

I know it's confusing, so in the next version (probably v1.19.0), it will look like:

<img width="224" alt="image" src="https://user-images.githubusercontent.com/9418365/218065514-c28ef18a-c5e5-4dc2-912b-fdc184d0d9dc.png">

**Comment by schmurtzm** [comment]
Oh indeed ! I was afraid to click on it because last time it has almost killed my instance during the zip process due to high demanding ressources.
Thank you.
