### ISSUE TITLE
Firefox "Reading mode" not working properly in Issues

### ISSUE THREAD

**Issue by ecke101** [go-gitea/gitea#22848]
### Description

I'm a user of Blender's new Gitea implementation and noticed the "Reader mode" works poorly in Issues.
It shows the list of branches instead of the issue description.
It looks like this is caused by that list being built up from divs instead of for example ul/li tags.
The Firefox code that converts the page to reader mode converts div tags without child tags into p-tags.
https://searchfox.org/mozilla-release/source/toolkit/components/reader/Readability.js#879

I think the file where this resides is templates/repo/issue/branch_selector_field.tmpl

If anyone is running Firefox, you can test reader mode (F9) on this link: https://projects.blender.org/blender/blender/issues/103248

### Gitea Version

a8c6cbf

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![bild](https://user-images.githubusercontent.com/249736/217999837-d32442b8-eaad-4251-9966-811c5b4157f0.png)

### How are you running Gitea?

Not my instance, it's run by the Blender Foundation.

### Database

None

**Comment by lunny** [comment]
Looks like this has been resolved. @ecke101 Could you help to confirm?

**Comment by lunny** [comment]
Closed and please feel free to reopen it if it's still a problem.
