### ISSUE TITLE
Create a new repo which is owned by user will be Internal sometimes

### ISSUE THREAD

**Issue by yp05327** [go-gitea/gitea#22859]
### Description

Create a new public repo which is owned by user will be Internal sometimes.
I have no idea about how to stability reproduce this bug.

![image](https://user-images.githubusercontent.com/18380374/218254638-999cb4b9-51df-4e4c-ab9a-f5750afa67f6.png)
![image](https://user-images.githubusercontent.com/18380374/218254646-55889db4-631f-48fb-abc7-6540ad6754bc.png)

### Gitea Version

fb1a2a13f05665764a6f91ed1a421b9e93c4e8c9

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

build

### Database

None

**Comment by delvh** [comment]
Could it be that you set `DEFAULT_USER_VISIBILITY = limited`?
To me, it looks like you can't have `public` repos, which would indicate that your user is `limited`.

**Comment by yp05327** [comment]
> Could it be that you set `DEFAULT_USER_VISIBILITY = limited`? To me, it looks like you can't have `public` repos, which would indicate that your user is `limited`.

DEFAULT_USER_VISIBILITY is not defined in my app.ini
Im using all default settings in app.ini
And `giteaadmin`'s user visibility is private.

I open this issue since I have encountered this bug twice.

I builded different versions with my own patches (no db changes) to fix bugs with the same db. 
Maybe something went wrong during the test. I will check it later.

**Comment by yp05327** [comment]
> And giteaadmin's user visibility is private.

Ah....
`private` user's 'public' repo will be Internal?

**Comment by delvh** [comment]
Probably.
I mean, it doesn't make sense to disclose a user if they intend to be `private`.
And by making the repo `public`, you automatically make the user `public` too.

**Comment by yp05327** [comment]
I usually use Japanese. And `Internal` is translated to `組織内` which means in an org or a group.

**Comment by delvh** [comment]
I mean… this translation is not totally wrong, but also not totally right.
In this case, it is rather meant as `only for registered users`.
You simply cannot see it without being logged in.
So, probably something like `内部` or `登録ユーザーのみ`/`登録者のみ` would be a better translation.
If you would like to propose a better translation, please propose it [here](https://crowdin.com/project/gitea/ja)
(Disclaimer: I got these translations from Google Translate, my current Japanese knowledge only tells me it _could be_ right, but I have no idea if it sounds natural)

**Comment by yp05327** [comment]
I can't find `Internal` (`desc.internal`) in crowdin. Did I do something wrong?
![image](https://user-images.githubusercontent.com/18380374/218267001-78e730b9-a8d5-46e9-bfd9-7330406b21b7.png)

![image](https://user-images.githubusercontent.com/18380374/218267047-bb5f2cd8-d7e7-4ef3-9d12-31d6bba0e414.png)

**Comment by wxiaoguang** [comment]
If I remember correctly, the crowdin sync has been down for a long long time.
