### ISSUE TITLE
Feat: API endpoint for creating users (`POST /users`)

### ISSUE THREAD

**Issue by hrueger** [go-gitea/gitea#22852]
### Feature Description

It would be great to have an api endpoint for registering new users via the API.
We're particularily interested in adding users from an external OIDC service programatically as we use gitea as an internal backend-like service and can't require users to click the "Complete Account" Button in the UI after logging in for the first time.

**Comment by wolfogre** [comment]
Maybe [POST /admin/users](https://gitea.com/api/swagger#/admin/adminCreateUser) can help?

**Comment by hrueger** [comment]
How come I did not see this endpoint? Never mind, that's what I was looking for!
Thanks!
