### ISSUE TITLE
NewPullRequest: newIssue: Error 3988: Conversion from collation utf8mb4_0900_ai_ci into utf8_general_ci impossible for parameter

### ISSUE THREAD

**Issue by ThraaxSession** [go-gitea/gitea#22858]
### Description

Renovate can creates a branch but not create a PR. It leads to a conversion error in the db. Gitea is migrate. I assume unicode can't be handled. See the question emoticon in "Screenshots".

### Gitea Version

1.18.3

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

       ---

        ❓ Got questions? Check out Renovate's [Docs](https://docs.renovatebot.com/), particularly the Getting Started section.
        If you need any further assistance then you can also [request help here](https://github.com/renovatebot/renovate/discussions).

        ---
This PR has been generated by [Renovate Bot](https://github.com/renovatebot/renovate).
         0 0 false true 0  0 1676108759 1676108759 0 false] - 769.507µs
2023/02/11 10:45:59 .../api/v1/repo/pull.go:420:CreatePullRequest() [I] [63e763d7] [SQL] ROLLBACK [] - 2.040923ms
**2023/02/11 10:45:59 .../api/v1/repo/pull.go:425:CreatePullRequest() [E] [63e763d7] NewPullRequest: newIssue: Error 3988: Conversion from collation utf8mb4_0900_ai_ci into utf8_general_ci impossible for parameter**
2023/02/11 10:45:59 [63e763d7] router: completed POST /api/v1/repos/SpaceUp/SWS/pulls for 162.55.152.199:0, 500 Internal Server Error in 282.1ms @ repo/pull.go:251(repo.CreatePullRequest)
2023/02/11 10:45:59 models/auth/token.go:160:GetAccessTokenBySHA() [I] [63e763d7-32] [SQL] SELECT `id`, `uid`, `name`, `token_hash`, `token_salt`, `token_last_eight`, `created_unix`, `updated_unix` FROM `access_token` WHERE (token_last_eight = ?) [c37d6d3b] - 824.249µs

### Git Version

2.30.2

### Operating System

Debian

### How are you running Gitea?

It's self-hosted and scheduled by supervisor.

### Database

MySQL

**Comment by lunny** [comment]
Please check all your database tables has the same collation.

**Comment by ThraaxSession** [comment]
Shouldn't `migrate` fix it? What should be the right one for all tables?

**Comment by zeripath** [comment]
Use `gitea convert`

**Comment by ThraaxSession** [comment]
Worked, thanks!
