### ISSUE TITLE
Long full name/username causes repo view to overflow

### ISSUE THREAD

**Issue by Maks1mS** [go-gitea/gitea#22866]
### Description

Similar as #22360, but with full name/username.

I can't reproduce on the Gitea demo site because it returns "Bad Gateway".

### Screenshots

![image](https://user-images.githubusercontent.com/36362599/218273284-746d3ec6-f956-4b45-b411-166a9dee32a9.png)

### Gitea Version

1.18.3

### Can you reproduce the bug on the Gitea demo site?

No

### Browser Version

Chrome 109.0.5414.119

**Comment by VladBrok** [comment]
I have this bug too

**Comment by wxiaoguang** [comment]
The same on try.gitea.io (main dev branch)

![image](https://user-images.githubusercontent.com/2114189/218289066-37a8b982-5954-4a31-a00c-308907f33458.png)

**Comment by jolheiser** [comment]
Should be fixed by #23030
