### ISSUE TITLE
Fork your own repository

### ISSUE THREAD

**Issue by mature-woman** [go-gitea/gitea#22882]
### Feature Description

hello

There are cases when it is necessary to make a copy of the project (creating a branch is not suitable). At the moment, you cannot make a fork to the same account. To do this, you have to do a fork on the organization and then take possession of that repository on the account.

If you change the ID manually in the html form to create a fork, you will get an error saying that the repository with that name already exists on the account even though you have changed the name of your fork.

I'll also add an error in Russian translation. The screenshot, as I understand it, should say that this repository is a fork. At the moment it is written as if it is a button which creates a new fork. Adapted to English, this could mean "Create a fork". We should change "Форкнуть" to "Форк".

offtop: don't scold me for the ugly color theme in the screenshot)))) I just recently started my site redesign

### Screenshots

![image](https://user-images.githubusercontent.com/21334019/218368285-df2f5d4e-cb94-4e87-922d-a0de54a18f64.png)

**Comment by lunny** [comment]
I think this has been mentioned many times and both github and gitlab don't support that.

**Comment by stuzer05** [comment]
> I think this has been mentioned many times and both github and gitlab don't support that.

This actually is a nice feature to have. At least, it should be disabled by default

**Comment by KazzmanK** [comment]
Fork to other account and than transfer ownership ?

**Comment by dloez** [comment]
> Fork to other account and than transfer ownership ?

Do not do this, we did it and it has caused us to have [misleading information about branches in PRs](https://github.com/go-gitea/gitea/issues/22311), it is not very bad, but it is not nice and in the future, we will probably end up with bigger issues.

I have asked/seen why this is not allowed, but every time the answer is "GitHub does it that way". I can understand that Gitea is basically a clone of the cloud-hosted alternatives, but I guess I was hoping that Gitea does not blindly follow every move they make when at least their users have said many times that a feature is actually nice and the feature itself does not seem to go against any patterns. I hope GitHub does not get crazy one day and removes, for example, forks as it seems like Gitea would blindly follow it.

**Comment by crabdancing** [comment]
Yeah, this is pretty dumb. I myself wanted to mirror external repos to my own, and then make my own forks of those repos, to get around my slow mountain broadband. But for some reason I can't, and now I have to move a bunch of mirrors to a different account or something... I don't know.

It's really annoying too, because I exclusively use SSH keys for access, and have a lot of automated systems that need to be able to access each repo. And, unfortunately SSH keys are per-account (because Github does it that way). So I'm stuck having two SSH keys, or having to juggle deployment keys that I have to set per-repository.

As it stands, Gitea does not scale very well the moment you're trying to do something complicated/unusual.

**Comment by stuzer05** [comment]
I want to fork my repos as well. My use case is I have main docker dev environment project and I fork it to make language-specific environment forks

**Comment by crabdancing** [comment]
@stuzer05 I found out that Forgejo _does_ let you fork your own repo! :) The migration process is a pain since they hard-forked from Gitea earlier this year, so I'm glad I'm getting it out of the way.

**Comment by wxiaoguang** [comment]
> @stuzer05 I found out that Forgejo _does_ let you fork your own repo! :) The migration process is a pain since they hard-forked from Gitea earlier this year, so I'm glad I'm getting it out of the way.

@crabdancing they do not. Since they have hard-forked for long time and many features are Gitea-only, such discussion is off-topic. I will hide these discussions as off-top.

![image](https://github.com/user-attachments/assets/654ad38b-5fee-488f-a553-626e3be25033)

**Comment by wxiaoguang** [comment]
Since there are many users liking this feature, let's try it:  Allow to fork repository into the same owner #32819 

Since there could be other complex logic I haven't fully figured out, this feature is experimental, not fully tested, and may be changed in the future.

At least, we could fork "own repository" now. 🎉

**Comment by lunny** [comment]
I'm not against this feature. But I think it will affect many logics, especially calculating `root repository` and `own fork repository`. Because those logics have assumed the root repository's owner will have no forked repository.

**Comment by wxiaoguang** [comment]
> I'm not against this feature. But I think it will affect many logics, especially calculating `root repository` and `own fork repository`. Because those logics have assumed the root repository's owner will have no forked repository.

There might be, might not. I have marked it as experimental. Why not try it? As long as it benefits end users.

**Comment by wxiaoguang** [comment]
Done and let's try it in 1.23 (will be released soon)

And it is also in "main-nightly" build.
