### ISSUE TITLE
Tracking issue for actions full-height CSS

### ISSUE THREAD

**Issue by jolheiser** [go-gitea/gitea#22883]
### Description

https://github.com/go-gitea/gitea/blob/be93e48ccb73acfaa372e56217105d3420e1a40e/web_src/less/_actions.less#L3-L6

### Screenshots

![image](https://user-images.githubusercontent.com/42128690/218373558-21ff8d68-e728-4d95-9c7f-474c590d6e91.png)

![image](https://user-images.githubusercontent.com/42128690/218373588-e94a3e69-ba46-42f4-9fc1-dbc18e91c991.png)

### Gitea Version

main

### Can you reproduce the bug on the Gitea demo site?

Yes

### Browser Version

Firefox

**Comment by wxiaoguang** [comment]
I do not know why it goes to the `_actions.less` and polluted the global styles.

**Comment by wxiaoguang** [comment]
OK, I think I know the problem, it's caused by this review:

* https://github.com/go-gitea/gitea/pull/21937#discussion_r1057311871


These CSS styles were put in `RepoActionView.vue` by design @delvh

**Comment by wxiaoguang** [comment]
Oh sorry that this problem isn't fixed yet.

I think I didn't make it clear enough at the beginning. I will take a look at the problem.
