### ISSUE TITLE
Cannot import large GPG key

### ISSUE THREAD

**Issue by fsologureng** [go-gitea/gitea#22896]
### Description

Hello,
This bug has been reported in @Codeberg-org and @Forgejo [here](https://codeberg.org/forgejo/forgejo/issues/359).

The problem is related with #20894.

The error log involved is
~~~
2023/02/12 15:37:27 ...user/setting/keys.go:117:KeysPost() [E] [63e907b5-20] AddPublicKey: Error 1406: Data too long for column 'content' at row 1
~~~
The table `gpg_key_import` should also be migrated to enlarge its `content` field size.

### Gitea Version

Codeberg

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

Forgejo latest build https://codeberg.org/forgejo/forgejo/commits/branch/v1.18/forgejo

### Database

MySQL

**Comment by zeripath** [comment]
We won't be able to backport this I'm afraid as there are quite a few migrations in 1.19 that are not in 1.18.

I think if you just run ``ALTER TABLE `gpg_import_key` CHANGE `content` `content` MEDIUMTEXT`` I'm fairly certain that Gitea should just work, and I think the migration should just no-op when time comes to upgrade to 1.19.

**Comment by fsologureng** [comment]
Thanks @zeripath

**Comment by zeripath** [comment]
I guess it's worth just double checking that `gpg_import_key` is the only thing that is left to do here and/or if you could provide a test case that fails then we could confirm for sure that this works.

**Comment by fsologureng** [comment]
> I guess it's worth just double checking that `gpg_import_key` is the only thing that is left to do here and/or if you could provide a test case that fails then we could confirm for sure that this works.

The test case is detailed in the linked bug report, with a link to a public gpg key grater than 64kb.

If your suggestion is implemented in Codeberg and works, I will report back here.

**Comment by zeripath** [comment]
Unfortunately I don't think that test case would be suitable to add to our test cases - as we'd probably need to add that person's email address in to our testcases! I guess what we need is to create a big keyring for one our test users e.g. `user2@example.com` - this is a bit involved for me to do right now.

**Comment by fsologureng** [comment]
Sorry, I misunderstood your request at first.
