### ISSUE TITLE
Formal review process by adding review's template

### ISSUE THREAD

**Issue by gd197** [go-gitea/gitea#22893]
### Feature Description

In a heavily constrained development process, a feature to standardize review would be an amazing must have.
The idea is to offer the option, like the existing pull request template, to configure template for reviewers.

E.g. file : .gitea/default_review_message/REVIEW_TEMPLATE.md

The result of such template could be a combination of texts and checkboxes with timestamps and reviewer name.

In addition, the content of those reviews from the pull request could be put in a variable.
Then, to be used in merge message, the same way the pull request description can be copied in merge message.

E.g. ${ListOfReviews}

With this feature, review's content can be standardized and committed to git with the content/code reviewed.
That way, we can demonstrate that the reviewer committed on a given list of tasks to perform at review stage.

**Comment by delvh** [comment]
If I understand your request correctly, isn't that effectively a concrete use of #22787?
If yes, let's close this issue in favor of the other.
Feel free to reopen if that is not the case.

**Comment by gd197** [comment]
I saw this feature request but does not seem to be the same for my point of view?
Imagine a repo for a project on which we have to provide the proof that a list of review tasks has been performed in the frame of a pull request.
Then we would ensure, by providing a template, that the text box for approval/rejection (submit a review) is used as a mean to let he reviewer commit on these tasks. This text would then be used in the frame of the merge commit message to store the proof.
Maybe this textbox (submit a review) is considered as "response" according to #22787 ? in that case yes it is a duplicate
![review](https://user-images.githubusercontent.com/25028540/218512047-bc6e22a4-3363-43da-bc0c-00065db6b02f.png)

**Comment by delvh** [comment]
I don't see why the "review textbox" shouldn't get the `saved replies`…
So yes, I guess this issue is then indeed a duplicate.
