### ISSUE TITLE
x-gitea-signature missing

### ISSUE THREAD

**Issue by chansdad** [go-gitea/gitea#22903]
### Description

Gitea Version
    1.5.1 built with: bindata, sqlite
when i create a webhook on push , and a payload is posted , i am not seeing the signature in the header.  All I am seeing are the following headers

Request method: POST
Content-Type: application/json
X-GitHub-Delivery: ffb80c47-1f7d-409f-99a1-3c50fa125918
X-GitHub-Event: push
X-Gitea-Delivery: ffb80c47-1f7d-409f-99a1-3c50fa125918
X-Gitea-Event: push
X-Gogs-Delivery: ffb80c47-1f7d-409f-99a1-3c50fa125918
X-Gogs-Event: push

### Gitea Version

1.5.1

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

1.5.1

### Operating System

Ubuntu

### How are you running Gitea?

on Ubuntu installed it following installation instructions

### Database

MySQL

**Comment by wolfogre** [comment]
v1.5.1 doesn't support `X-Gitea-Signature`, it first appeared in v1.9.0-rc1, see #6428

Please upgrade Gitea, it's worth it.
