### ISSUE TITLE
HolyC Syntax Highlighting?

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#22904]
### Feature Description

Would it be possible to get HolyC syntax highlighting for Gitea? I am working on a Git site dedicated around the language, but the fact that there is no syntax highlighting really takes away from the general aesthetic.

HolyC is really similar to C in terms of syntax except for really variables and function names. Below is a screenshot of said implementation on GitHub.

I understand this may be a very niche topic, and likely may not be added, however in that case, could I atleast be provided with documentation on writing the syntax highlighting manually? Thanks.

### Screenshots

![Screenshot_2023-02-14-04-34-09_1920x1080](https://user-images.githubusercontent.com/96399844/218648555-94a1cf29-5d9d-47ef-9194-b26538c4afce.png)

**Comment by JakobDev** [comment]
You might want to create a Issue for [Chroma](https://github.com/alecthomas/chroma), which is the Syntax Highlighter used by Gitea. If you want it to do yourself, you can find the Lexer for C [here](https://github.com/alecthomas/chroma/blob/1d0ed7f62a731c55beca0e609d4b0b28ad39e240/lexers/embedded/c.xml). If you have good knowledge of the Syntax, you can create a Lexer for HolyC based on this and make a PR.

**Comment by wxiaoguang** [comment]
Workaround: or use gitattributes to tell the highlighter that some files are C code. Like this one: 
* https://github.com/go-gitea/gitea/issues/21970#issuecomment-1424879041

**Comment by xzntrc** [comment]
> You might want to create a Issue for [Chroma](https://github.com/alecthomas/chroma), which is the Syntax Highlighter used by Gitea. If you want it to do yourself, you can find the Lexer for C [here](https://github.com/alecthomas/chroma/blob/1d0ed7f62a731c55beca0e609d4b0b28ad39e240/lexers/embedded/c.xml). If you have good knowledge of the Syntax, you can create a Lexer for HolyC based on this and make a PR.

Ah my nightmare, Regex. I knew I'd have to learn it eventually. Honestly though, thank you so much for this, I don't think HolyC will be that hard to manufacture using this. Appreciate it.

**Comment by silverwind** [comment]
If it works with `c` syntax, you could contribute the addition of the file extension (assuming it has a unique one) to chroma's [`c lexer`](https://github.com/alecthomas/chroma/blob/master/lexers/embedded/c.xml) and gitea will then automatically pick it up based on the file extension.

**Comment by silverwind** [comment]
As per https://github.com/github/linguist/pull/4512/files, Github does match it based on the `.hc` extension, so unless this extension is already in use at Chroma somewhere else, it should be possible to get it added.

**Comment by xzntrc** [comment]
Realistically, this looks like it should be a breeze to do considering it seems that the GitHub format is very similar to Chroma. From what @silverwind linked, I found this: [https://github.com/codingdandy/holyc.tmbundle]( https://github.com/codingdandy/holyc.tmbundle ) which should be sufficient.

**Comment by silverwind** [comment]
Yeah, so the job is to start with https://github.com/alecthomas/chroma/blob/master/lexers/embedded/c.xml and adapt the individual rules based on https://github.com/codingdandy/holyc.tmbundle/blob/master/Syntaxes/HolyC.tmLanguage to create the chroma lexer.

My earlier idea of just adding an alias to the C lexer is not right, the language is too different from C to be considered an alias.

**Comment by xzntrc** [comment]
> Yeah, so the job is to start with https://github.com/alecthomas/chroma/blob/master/lexers/embedded/c.xml and adapt the individual rules based on https://github.com/codingdandy/holyc.tmbundle/blob/master/Syntaxes/HolyC.tmLanguage to create the chroma lexer.
> 
> My earlier idea of just adding an alias to the C lexer is not right, the language is too different from C to be considered an alias.

Unfortunately I have no experience in Go. I figured it would be as simple as forking chroma, and then in Gitea's go.mod file replacing `github.com/alecthomas/chroma/v2 v2.4.0` with `github.com/xzntrc/chroma/v2 master` but that leaves me with a bunch of further errors like:
```
module declares its path as
... 
but was required as
```

**Comment by xzntrc** [comment]
I've gone ahead and made a pull request for this on Chroma: [https://github.com/alecthomas/chroma/pull/750](https://github.com/alecthomas/chroma/pull/750)

**Comment by silverwind** [comment]
Thanks, so we just need to wait until next chroma release and then update it.

**Comment by xzntrc** [comment]
Is that it @silverwind? I thought I had to edit "go-enry" or something

**Comment by silverwind** [comment]
For the syntax highlighting, chroma is enough.

https://github.com/go-enry/go-enry is used for the language stats bar, but it may be that they already support HolyC given that they source some data from linguist, but if you like, please double-check.

**Comment by xzntrc** [comment]
> For the syntax highlighting, chroma is enough.
> 
> https://github.com/go-enry/go-enry is used for the language stats bar, but it may be that they already support HolyC given that they source some data from linguist, but if you like, please double-check.

Alrighty, looks like HolyC is already there. Is there any way to force my gitea build to use the latest of Chroma, not the latest version since my PR wasn't packaged but instead the branch?

**Comment by silverwind** [comment]
Try:

```
go get -u github.com/alecthomas/chroma/v2@3ac94eea73f5de1bf6c864b9a7f4089514415090
```

**Comment by xzntrc** [comment]
That worked! Thanks all!
