### ISSUE TITLE
Pull Request: File-Tree sidebar is too small for long filenames

### ISSUE THREAD

**Issue by Hypersomniac** [go-gitea/gitea#22915]
### Feature Description

In the Pull Request  `Files Changed` view:
When dealing with files with names have the same long prefix, it is impossible to know the file's full name before clicking on them. Which is a bit cumbersome in some situations:

![Capture d’écran du 2023-02-15 00-34-13](https://user-images.githubusercontent.com/2557190/219011846-7d3c513d-cbaf-40cd-af8d-819fb7f570a7.png)

There is no possibility to either:
* Expand or resize the sidebar.
* Scroll the sidebar horizontally.
* Mouse over to see the full file name (using a simple html `title` would do the job).

It forces to click on the file, check the top of the page and read the full path name (which can even be broken into multiple lines).

This falls in between usability bug and feature request I guess.

Here is the issue in question https://projects.blender.org/blender/blender/pulls/104599/files#diff-a8030d774c658fc81d1e7a8b0a4aa3044e7b9723

**Comment by silverwind** [comment]
We should set a `tooltip` on these.

**Comment by wxiaoguang** [comment]
I guess `tooltip` doesn't work for Vue at the moment? So I think `title` wins.

**Comment by delvh** [comment]
I've tried it, the result is not too good: 
![image](https://user-images.githubusercontent.com/51889757/219045223-82ff4aa9-3b19-45bc-aef0-4ebcc637d13d.png)

**Comment by delvh** [comment]
Okay, yeah, `title` sounds reasonable.

**Comment by delvh** [comment]
Much better.
![image](https://user-images.githubusercontent.com/51889757/219046681-492154cb-8e73-49be-bced-7583837be9eb.png)

**Comment by silverwind** [comment]
Yeah, title is arguably better in this case.
