### ISSUE TITLE
The link of org people/member page

### ISSUE THREAD

**Issue by yp05327** [go-gitea/gitea#22931]
### Feature Description

Org people page's link is `domain/org/{OrgName}/members`.
Maybe `domain/org/{OrgName}/people` is better or just change the tab name from `People` to `Members`?

**Comment by wolfogre** [comment]
I prefer renaming `People` to `Memers`, it's always `Memers` in the code.

BTW, if somebody can help rename it, please change the icon too, it looks like buildings.

<img width="366" alt="image" src="https://user-images.githubusercontent.com/9418365/219285441-2be30f42-2a44-4d8e-8731-2890cb04ec3b.png">
