### ISSUE TITLE
Docs describe unreleased features

### ISSUE THREAD

**Issue by JakobDev** [go-gitea/gitea#22933]
### Description

The [official Gitea Docs](https://docs.gitea.io) describe features which are currently not in a release. e.g. the [Cargo package registry](https://docs.gitea.io/en-us/packages/cargo/), which was [merged only 2 weeks ago](https://github.com/go-gitea/gitea/pull/21888). This can [lead to some confusion](https://codeberg.org/Codeberg/Community/issues/941). I think the official docs site should show the Docs from the latest version instead of the current git or even better, add a Version Dropdown.

### Screenshots

![grafik](https://user-images.githubusercontent.com/15185051/219294987-4c68f4d6-1df0-476c-b63c-aa34df9b1115.png)

### Gitea Version

Happens on the official site, not on a Gitea instance

### Can you reproduce the bug on the Gitea demo site?

Yes

### Browser Version

Firefox 109

**Comment by wxiaoguang** [comment]
You are not the first one (also maybe not the last one)

* #17879
* #17905

**Comment by lunny** [comment]
Since versioned documentation site is up, this could be closed.
