### ISSUE TITLE
Add option to allow only gitea users to access public endpoints

### ISSUE THREAD

**Issue by unrealjo** [go-gitea/gitea#22941]
### Feature Description

- I want an option to restrict access to public endpoints like public repos and user profile .
- As I'm self hosting my gitea instance, I want only users with an account to access any page the gitea and avoid leaking some code which is supposed to be shared only with some specific users.

- Below in the screenshot below I able access any repos once I have the its url

### Screenshots

![2023-02-16_18-09](https://user-images.githubusercontent.com/63888397/219438829-028e820c-946e-40f5-93ec-72f92728c62c.png)

**Comment by unrealjo** [comment]
Yes exactly  😳,

**Comment by xgdgsc** [comment]
Why not make REQUIRE_SIGNIN_VIEW default to true?
