### ISSUE TITLE
Diff breaks if csv deleted from base and head

### ISSUE THREAD

**Issue by kdumontnu** [go-gitea/gitea#22946]
### Description

Deleting a .csv file from both the base and head branch in a compare will result in a 500 error.

https://try.gitea.io/kdumontnu/test/compare/main...delete-csv

### Gitea Version

d9c6cb71e

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

Seen on 1.17 initially. Reproduced on try.gitea.

### Database

None

**Comment by lunny** [comment]
```log
2023/02/17 02:58:03 ...s/context/context.go:231:HTML() [E] [63eeed3b-8] Render failed: template: repo/diff/csv_diff:3:15: executing "repo/diff/csv_diff" at <call .root.CreateCsvDiff .file .blobBase .blobHead>: error calling call: runtime error: invalid memory address or nil pointer dereference
```

**Comment by wxiaoguang** [comment]
Some contexts of this problem (just FYI):

* Issue #19530
* PR #19552
* PR #21189

**Comment by wxiaoguang** [comment]
OK, I fully understand the problem now. If a CSV file is deleted from both branch, then baseReader and headReader can both be nil.
