### ISSUE TITLE
incorrect 'header-wrapper' width in a repo's 404 page

### ISSUE THREAD

**Issue by yp05327** [go-gitea/gitea#22951]
### Description

A repo's 404 page will render repo/header.tmpl. But it has incorrect width in this page.
![image](https://user-images.githubusercontent.com/18380374/219561978-c40dcbbe-7a09-4535-92f5-e6aba17d044c.png)

### Gitea Version

latest

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

build

### Database

None

**Comment by yardenshoham** [comment]
How to reproduce?

**Comment by yp05327** [comment]
I'm sorry for my mistake.
After pulling the lastest version, I only rebuilded the backend. 
But something changed in the frontend, then I got this wrong ui.
