### ISSUE TITLE
Committing using web UI does not trigger webhook action "synchronized"

### ISSUE THREAD

**Issue by tobias--** [go-gitea/gitea#2295]
- Gitea version (or commit ref): be29d5f 
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant

## Description

The webhook action "synchronized" does not get triggered when changes to the PR-branch are made using the web UI.

Steps to reproduce:
1. Setup webhook to be triggered for every event on a repository
2. Fork this repository
3. Make changes to the fork and commit to a new branch using the web UI
4. Create a Pull Request in the original repository (webhook gets triggered correctly)
5. Make another change to the new branch in the forked repository **using the web UI**: **A webhook event "synchronized" is expected to be triggered but it is not triggered.**
6. Checkout the fork/pr-branch, make changes locally and push them back to origin: A webhook event "synchronized" is correctly being triggered

**Comment by ethantkoenig** [comment]
@tobias-- Could you confirm that #2302 fixes the problem?
