### ISSUE TITLE
Reopening a PR reopened another merged PR in the same reporitory

### ISSUE THREAD

**Issue by Greg-NetDuma** [go-gitea/gitea#22957]
### Description

I don't know how to reproduce this, I've only seen this happen this one time.

My guess is that reopening a PR (id - 198) somehow reopened another already merged in PR (id - 213) in the same repo along with the one it's supposed to, the timestamps in the activity log are the same.

I can't close (change the state of) the PR from the API because it says it has been merged in.

(non-debug) Logs:
```
2023/02/13 18:42:21 router: completed POST /NetDuma/api/issues/status for 172.25.0.1:54348, 200 OK in 233.8ms @ repo/issue.go:2554(repo.UpdateIssueStatus)
2023/02/13 18:42:21 [63ea848d-21] router: completed GET /NetDuma/api/pulls?q=&type=all&sort=&state=closed&labels=&milestone=0&assignee=0&poster=0 for 172.25.0.1:54354, 200 OK in 162.2ms @ repo/issue.go:408(repo.Issues)
2023/02/13 18:42:22 [63ea848e] router: completed GET /NetDuma/api/pulls?q=&type=all&sort=&state=open&labels=&milestone=0&assignee=0&poster=0 for 172.25.0.1:54428, 200 OK in 123.7ms @ repo/issue.go:408(repo.Issues)
```

### Gitea Version

1.18.3

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

PR log
![Screenshot from 2023-02-17 11-26-12](https://user-images.githubusercontent.com/69147407/219639280-6d1b7c02-73ac-41f7-8141-c57887be200b.png)

Activity log
![Screenshot from 2023-02-17 11-58-09](https://user-images.githubusercontent.com/69147407/219648173-118b1da6-1d8d-4f2d-8d98-d81800eaa80a.png)

### Git Version

The one provided in the docker image

### Operating System

Ubuntu 20.04

### How are you running Gitea?

Official docker image

### Database

MySQL

**Comment by lunny** [comment]
This should be resolved by #26108
