### ISSUE TITLE
Support long projects name in Issue sidebar

### ISSUE THREAD

**Issue by yp05327** [go-gitea/gitea#22953]
### Description

I didn't check the others in sidebar. It is necessary to check all of them.
![image](https://user-images.githubusercontent.com/18380374/219589124-0865fc87-1146-4fc8-85ae-f1124e28bdf1.png)

### Gitea Version

latest

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

build

### Database

None

**Comment by yardenshoham** [comment]
It looks like it only happens with `/`
![image](https://user-images.githubusercontent.com/20454870/219743660-22682ff4-f265-4df5-8d5e-e57f1a404a88.png)
![image](https://user-images.githubusercontent.com/20454870/219743857-7718f761-b6d2-448d-9d07-2758fc0a34a8.png)

**Comment by yp05327** [comment]
@yardenshoham 
![image](https://user-images.githubusercontent.com/18380374/219824901-9d41bb5c-1652-4c00-8ac1-5aba4e2aa518.png)
I'm not sure whether this string can be splitted.
It is tested in version https://github.com/go-gitea/gitea/commit/e7ef94e00f1319e5fb876f47fee28728bd671f07

**Comment by wxiaoguang** [comment]
word-break, or overflow hidden
