### ISSUE TITLE
cannot create a new branch on the mirror warehouse

### ISSUE THREAD

**Issue by frankelyns** [go-gitea/gitea#22972]
### Description

After setting the warehouse image, the branch cannot be created, and 403 will be prompted when pushing. What is the problem?

### Gitea Version

 1.17.2

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

It is run using docker.

### Database

PostgreSQL

**Comment by techknowlogick** [comment]
mirrors are read-only. If you'd like to modify you will need to make a fork and push to that, and merge from your mirror.
