### ISSUE TITLE
'make watch' dosen't work in wsl2 

### ISSUE THREAD

**Issue by yp05327** [go-gitea/gitea#22978]
### Description

It seems that `make watch` dosen't work in wsl2 (Ubuntu-22.04)
I installed a VM (Ubuntu-22.04) today, and it worked well.
Should I change some settings in wsl2 to make it work or this is just a bug?

### Gitea Version

latest

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

build

### Database

None

**Comment by KN4CK3R** [comment]
You may specify "doesn't work".

**Comment by yp05327** [comment]
@KN4CK3R 
`make watch` can build and run the server.
But when a file is changed and saved, it won't reflect the changes.
The source codes are all saved in ntfs (in the mnt path)

**Comment by KN4CK3R** [comment]
maybe related: https://github.com/cosmtrek/air/issues/274

I use docker inside the WSL2 environment and that works fine.

**Comment by yp05327** [comment]
I moved the source codes to `~/{your_path}` instead of `/mnt/{your_path_in_windows}` and it will reflect the changes now.

But all assets files were 404 when I added `bindata` Tag. Is it a bug, or just should not be added when we run `make watch`.
![image](https://user-images.githubusercontent.com/18380374/220013253-02fa015c-075f-40b0-8cc6-6db8a9d20dcb.png)

**Comment by lunny** [comment]
Don't use `bindata` when run `make watch`.
