### ISSUE TITLE
Admin Merge broken on 1.18.4

### ISSUE THREAD

**Issue by gempir** [go-gitea/gitea#23000]
### Description

I have a branch with a Branch Protection (at least 1 approval and a check that has to run)

![image](https://user-images.githubusercontent.com/9765622/220046419-f66ec033-5576-407c-ba73-90780f7195b0.png)

The UI tells me I still can merge it anyway since i'm Admin. But when I try to merge it 

The error message
> This pull request is not ready to be merged, check review status and status checks.
Appears 

Could also reproduce on try.gitea.io with `[Powered by Gitea](https://gitea.io/) Version: 1.19.0+dev-521-g2b3f12f6f Page: 99ms Template: 11ms`

Steps To Reproduce
- Be admin in repository
- Setup branch protection for any branch, require 1 approval
- Create a pull request pointing at the protected branch
- Try to merge without having 1 approval (with the red admin merge button)

### Gitea Version

1.18.4

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

![image](https://user-images.githubusercontent.com/9765622/220047032-96f41d82-0279-4778-bdf0-4659d84ad19a.png)

### How are you running Gitea?

Irrelevant

### Database

None

**Comment by kolaente** [comment]
Noticed that as well.

**Comment by lunny** [comment]
@kolaente Please confirm #23010 fix this problem.

**Comment by parnic-sks** [comment]
This same issue occurs when trying to schedule an auto-merge after checks succeeding, even as a non-admin.
