### ISSUE TITLE
Github API - space in version name

### ISSUE THREAD

**Issue by rpajik** [go-gitea/gitea#23033]
### Description

github api get version name with space on the start of string.

curl -s https://api.github.com/repos/go-gitea/gitea/releases/latest | jq .name
" v1.18.4"

I expect, this is wrong.

### Gitea Version

1.18.4

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

systemd, but not relevant

### Database

None

**Comment by wolfogre** [comment]
Sorry, I believe it was a misoperation and it has been fixed now.
