### ISSUE TITLE
Cannot log in on website, but pulling/pushing works

### ISSUE THREAD

**Issue by domsl** [go-gitea/gitea#23044]
### Description

I cannot login on the web ui with my account (which I was confused about, because it is in my password manager) on my selfhosted docker instance.

I used sudo docker attach gitea to see the following error:
`Failed authentication attempt for xxx from 100.84.234.122:51488: user does not exist [uid: 1, name: xxx, keyid: 0]`

but `gitea admin user list` shows me my user with ID 1 and everything.

I can still push/pull with git commandline / gitextensions normally

### Gitea Version

1.17.0+rc1

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

I use Gitea via Docker

### Database

None

**Comment by lunny** [comment]
Please confirm you are using correct password.

**Comment by domsl** [comment]
Hi, thank you for your response.

Would I get the error in the logs ` user does not exist` if it is the wrong password?

I can only check if it is the password I remember and it is also the password that I saved into my password manager. It could be that I misremember and also saved the wrong password, but I think it is the correct one.

Is there a way I can check hashes manually or something to see if it is correct?

**Comment by GatoMiopia** [comment]
I just got the same problem as you. I tried changing the password to what I had but it wouldn't work.
But for some reason, when I changed for another one testing it worked.
Then I logged in and changed it back and it seems to be working fine.

**Comment by domsl** [comment]
@GatoMiopia: 
Thank you for your answer.

Is there a way to just reset or change the password of user 1 from the shell inside the docker container?

**Comment by GatoMiopia** [comment]
@domsl Yes, that's how I was doing it.

You can see the commands under the Command Line section on the docs: https://docs.gitea.io/en-us/command-line/#admin
