### ISSUE TITLE
Add SSH key not working

### ISSUE THREAD

**Issue by brechtvl** [go-gitea/gitea#23040]
### Description

* Go to user/settings/keys
* Click Add Key

```
JavaScript error: TypeError: e.classList is undefined (http://localhost:3000/assets/js/index.js?v=1.19.0~dev-545-g7f790c7 @ 36:60982). Open browser console to see more details.
```

Caused by #22950

### Gitea Version

main (7f790c7)

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

Both own build and try.gitea.io

### Database

None

**Comment by brechtvl** [comment]
@wxiaoguang it's not immediately clear to me where the problem is, maybe you know.

**Comment by wxiaoguang** [comment]
Let me see

**Comment by wxiaoguang** [comment]
The fix:  Fix the show/hide methods for string selector #23042
