### ISSUE TITLE
Users with same email display diff name when the repo is cloned from another gitea site

### ISSUE THREAD

**Issue by yp05327** [go-gitea/gitea#23055]
### Description

Clone a repo from gitea site A, and push it to gitea site B, and the users with same email will display the user name in gitea site A.
Is it correct (by design) or not?

Link: https://try.gitea.io/yp05327/testrepo2/commits/branch/main

![image](https://user-images.githubusercontent.com/18380374/220495129-a702ee90-afaa-4363-8906-a8b020e76229.png)

### Gitea Version

1.19.0+dev-555-g4d2d3bd65

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

build
try.gitea.io

### Database

None

**Comment by jolheiser** [comment]
Commit authors are linked by email, so if a user on Gitea B has the same email as Gitea A, those commits will show as that user.

Assuming that's what you mean, it is not a bug.

Or did you mean something else?

**Comment by techknowlogick** [comment]
This is expected behaviour. The user "hello_miku" as you can see in the link, has the email "admin@example.com" which is why the commits are being attributed to them on try.gitea.io.

(aka: ☝️ what @jolheiser said).

Thanks for checking in with behaviour such as this.
