### ISSUE TITLE
Commit count num in cache data will not be refreshed

### ISSUE THREAD

**Issue by yp05327** [go-gitea/gitea#23060]
### Description

Relate to https://github.com/go-gitea/gitea/issues/22621#issuecomment-1439306976
It seems that commit count num in cache data will not be refreshed in the latest version.
But in try.gitea.io it works well. (Why? It seems that there are no changes related to this in recent)
Can anyone reproduce this too?

I added:
```
cache.Remove(repo.GetCommitsCountCacheKey(opts.NewBranch, true))
```
then the count nun will refresh after apping a partch.

Related functions maybe as following:
![image](https://user-images.githubusercontent.com/18380374/220522060-399ecd57-9686-465b-8a45-59d643138e6d.png)

### Gitea Version

latest

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

build

### Database

None

**Comment by lunny** [comment]
`try.gitea.io` will always follow the latest version automatically.

**Comment by yp05327** [comment]
I tested this issue on another pc again and it worked well. So I close this issue.
