### ISSUE TITLE
Can't create mirror

### ISSUE THREAD

**Issue by Morlinest** [go-gitea/gitea#2306]
- Gitea version (or commit ref): fc29a405e8c210fa62ad4cbe4250617e4b85d6c8 (+ my latest PR, but it is only UI change)
- Git version: 2.11.1
- Operating system: Win10
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:
2017/08/14 14:35:14 [...routers/repo/repo.go:107 handleCreateError()] [E] MigratePost: InsertOne: pq: value "28800000000000" is out of range for type integer

## Description
Error 500 when trying to create mirror (from localhost or github).

**Comment by Morlinest** [comment]
I found #1504, so it should be resolved, but I dont understand why my DB has version 39:
```
gitea=# select * from version;
 id | version
----+---------
  1 |      39
(1 row)
```

but `interval` column in "mirror" table was not changed and is still of type `integer`...
```
gitea=# \d+ mirror;
                                                  Table "public.mirror"
      Column      |  Type   |                      Modifiers                      | Storage | Stats target | Description
------------------+---------+-----------------------------------------------------+---------+--------------+-------------
 id               | bigint  | not null default nextval('mirror_id_seq'::regclass) | plain   |              |
 repo_id          | bigint  |                                                     | plain   |              |
 interval         | integer |                                                     | plain   |              |
 enable_prune     | boolean | not null default true                               | plain   |              |
 updated_unix     | bigint  |                                                     | plain   |              |
 next_update_unix | bigint  |                                                     | plain   |              |
```

**Comment by Morlinest** [comment]
Started sql by hand and it's working. I am closing issue, hoping this was just a crazy/weird bug on my testing db :).

**Comment by lunny** [comment]
It should be an incomplete upgrade problem.
