### ISSUE TITLE
Status checks don't show up in the pull request overview

### ISSUE THREAD

**Issue by dcermak** [go-gitea/gitea#23077]
### Description

I am adding status checks to a repository via the API and have managed for these status checks to show up in the commit overview as a green check mark or red cross. I then proceeded to enable branch protection on the repository with status checks being required. Then I opened a pull request against the protected branch, but the status checks don't show up like they for instance do on the [Gadgetbridge](https://codeberg.org/Freeyourgadget/Gadgetbridge/pulls) repository.

Repository without status checks showing up in the PR overview: https://gitea.opensuse.org/rpm/skopeo/pulls

### Screenshots

![image](https://user-images.githubusercontent.com/45594031/220662594-dd44a040-5f94-4604-95ee-e4ed5af134e2.png)

### Gitea Version

1.18.3

### Can you reproduce the bug on the Gitea demo site?

No

### Browser Version

Firefox 110, Chromium Version 110.0.5481.100

**Comment by oliverpool** [comment]
Looking at the commits of https://gitea.opensuse.org/rpm/skopeo/pulls/3/commits, they appear to have not status.

I think the PR page shows the status (if any) of the latest commit of the branch.

Can you try adding a commit status to the following commit https://gitea.opensuse.org/rpm/skopeo/commit/9baf12472696b216f41caf78f5e65851098ed721 ?

**Comment by dcermak** [comment]
I have added the statuses to the fork: https://gitea.opensuse.org/defolos/skopeo/commits/branch/factory. So they have to be explicitly added to the main repo?

**Comment by oliverpool** [comment]
Ah yes, the commit status must be added to the main repo (they are attached to a `commit hash`+`repo id`).

**Comment by dcermak** [comment]
Ah you're of course correct. Now it works, thanks a lot!

I think this would be worth documenting. Where could/should I submit a short guide about this? I could extend [api-usage.en-us.md](https://github.com/go-gitea/gitea/blob/d27d36f2f4dd389050e613967ad2a5d02d250acc/docs/content/doc/developers/api-usage.en-us.md) or create a new document in that folder?

**Comment by lunny** [comment]
> Ah you're of course correct. Now it works, thanks a lot!
> 
> I think this would be worth documenting. Where could/should I submit a short guide about this? I could extend [api-usage.en-us.md](https://github.com/go-gitea/gitea/blob/d27d36f2f4dd389050e613967ad2a5d02d250acc/docs/content/doc/developers/api-usage.en-us.md) or create a new document in that folder?

Please send a PR to improve the documentation. Sorry for late reply.

**Comment by dcermak** [comment]
Lunny Xiao ***@***.***> writes:

>> Ah you're of course correct. Now it works, thanks a lot!
>> 
>> I think this would be worth documenting. Where could/should I submit a short guide about this? I could extend [api-usage.en-us.md](https://github.com/go-gitea/gitea/blob/d27d36f2f4dd389050e613967ad2a5d02d250acc/docs/content/doc/developers/api-usage.en-us.md) or create a new document in that folder?
>
> Please send a PR to improve the documentation. Sorry for late reply.

The question was where to send it. I am unsure what the correct place is.

**Comment by lunny** [comment]
Maybe here https://github.com/go-gitea/gitea/blob/main/docs/content/doc/development/integrations.en-us.md

**Comment by lunny** [comment]
I think this has been resolved and please feel free to reopen it.
