### ISSUE TITLE
Issue popup preview doesn't get dismissed soon enough

### ISSUE THREAD

**Issue by dfelinto** [go-gitea/gitea#23073]
### Description

When we have multiple links to issues in a message and we mouse over one after the other the preview popups pile up.

### Screenshots

![image](https://user-images.githubusercontent.com/843498/220632946-fc537a6c-517e-4adf-8fa2-6d0e7fecc2a6.png)

### Gitea Version

1.19.0+dev-557-g90a7bba1f

### Can you reproduce the bug on the Gitea demo site?

Yes

### Browser Version

Google Chrome

**Comment by dfelinto** [comment]
To see this in the test instance of Gitea go to: https://try.gitea.io/dfelinto/blender/issues/14

**Comment by wxiaoguang** [comment]
It seems that the `tippy` popup must be hovered first, to make it could be hidden (mouseout) later .....

**Comment by wxiaoguang** [comment]
The answer seems to be this:

https://atomiks.github.io/tippyjs/v6/all-props/#interactiveborder

> Determines the size in pixels of the invisible border around a tippy which will prevent it from hiding if the cursor left it.


And Gitea set it to : `interactiveBorder: 30`
