### ISSUE TITLE
Whitespace trimming inside markdown inline tags inconsistent

### ISSUE THREAD

**Issue by silverwind** [go-gitea/gitea#23080]
### Description

Given mardown source

```md
x ` a` y
x `a ` y
x ` a ` y
```

Github renders:

<img width="89" alt="Screenshot 2023-02-22 at 17 33 32" src="https://user-images.githubusercontent.com/115237/220694364-f3e1dead-6fa7-4a1d-b6ff-4e52f04485db.png">

x ` a` y
x `a ` y
x ` a ` y

Gitea renders:

<img width="77" alt="image" src="https://user-images.githubusercontent.com/115237/220694624-1094a62c-344e-4a91-b731-39277831c27f.png">

- Line 1 should render the leading space inside the code element.
- Line 2 could do with some whitespace after the code element.
- It may be argued that whitespace should be visible within the code element on line 3.

### Gitea Version

latest

### Can you reproduce the bug on the Gitea demo site?

Yes

**Comment by HesterG** [comment]
Did an inspection on the less, looks like the difference between git and gitea is that gitea does not have this line:

`white-space: break-spaces;`

github:

<img width="1426" alt="截屏2023-02-23 15 22 22" src="https://user-images.githubusercontent.com/17645053/220843971-c8aceea7-76e3-4814-a22a-2ab15c3c8421.png">

gitea:

<img width="1422" alt="截屏2023-02-23 15 22 43" src="https://user-images.githubusercontent.com/17645053/220842610-124dfdd8-9356-43cf-915e-62825543cfc7.png">
