### ISSUE TITLE
Home page shows 688 No Reason Phrase

### ISSUE THREAD

**Issue by rugk** [go-gitea/gitea#2308]
- Gitea version (or commit ref): v1.1.3
- Operating system: Debian Jessie
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io: N/A
- Log gist: everything works

## Description
Accessing the home page shows "<a href="/subdir/explore">Found</a>." using the error "688 No Reason Phrase".

Gitea runs behind an nginx reverse proxy installed in a subdirector (`/subdir`), which is correctly set as `ROOT_URL` in the settings.

I think this issue was introduced in one of the latter gitea versions, as previous versions were executed correctly.

Accessing `/explore/repos` (manually by changing the URL), however, works.

Also, the login does not work. It seems to execute something, but then returns "700 No Reason Phrase".

My nginx config is basically a location block to catch all static assets, which uses  a `try_files` to redirect all other requests to a `@proxy`, which then does mostly this:
```
rewrite /subdir/(.*) /$1 break;
rewrite ^/subdir$ /subdir/ permanent;
proxy_buffering off;
# some proxy headers
proxy_pass […];
```

## Screenshots

![grafik](https://user-images.githubusercontent.com/11966684/29281999-6dda2250-8121-11e7-916b-972504334207.png)

**Comment by lunny** [comment]
Gitea has supported subdir. Maybe you should change your config to enable it.

**Comment by rugk** [comment]
It is configured in the `ROOT_URL`. That has worked since Gogs. Is there another option I should change/add?

**Comment by rugk** [comment]
Any news?

I also see errors when trying to push repos to gitea:
```shell
$ git push
fatal: unable to access 'https://example.com/subdir/orga/repo.git/': The requested URL returned error: 502
```

**Comment by rugk** [comment]
This could be an nginx error, I'll look into this soon…

**Comment by techknowlogick** [comment]
Can this ticket be closed?
