### ISSUE TITLE
PR information could be out of sync and stuck in a stale status

### ISSUE THREAD

**Issue by wxiaoguang** [go-gitea/gitea#23084]
### Description

Steps:

1. A PR from  `root-patch-5`  to `main`.
2. At the beginning, `root-patch-5` is behind `main`. 
3. Click `Update branch by merge`
4. Make Gitea exit immediately (for example, kill or panic) 
5. Then the commit shows that `main` has been merged into `root-patch-5`
6. But the PR's information is broken, there is still a `Update branch` button, do more clicks, nothing happens.

I haven't tried whether `doctor` could help. Suppose there is a busy instance, if this bug happens (when restart Gitea), that's unfriendly to users and site admins.

A workaround: if main branch is changed again, then clicking `Update branch by merge`  could work again.

----

![image](https://user-images.githubusercontent.com/2114189/220813567-733b5720-8ff6-41ab-99ba-424e5e0bf557.png)

----

![image](https://user-images.githubusercontent.com/2114189/220812798-5a6613b5-3884-429a-a9cd-d74770c70241.png)

**Comment by a1012112796** [comment]
maybe we can add a button to rerun `pull request check` .
