### ISSUE TITLE
README.md in npm package cause gitea to crash

### ISSUE THREAD

**Issue by nmqh** [go-gitea/gitea#23082]
### Description

After the attached file [README.md](https://github.com/go-gitea/gitea/files/10809506/README.md) is included in a npm package and published to GITea, and then when package details page is opened in GITea site for this package, GITea crashes (see attached error message) ![AppErrorAndCrash](https://user-images.githubusercontent.com/79547337/220799673-cf598b01-d3a3-4b62-b5fb-0e2747664288.jpg)

In the README.md if the following line is removed and published, the gitea app/service does not fail when viewing the package details in GITea.
`- The pacakge name @qccat-ui has been renamed to @qccat/core-ui.`

### Gitea Version

1.18.5

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

GITea is running in windows.

### Database

None

**Comment by Zettat123** [comment]
I think the reason of the panic is the `ctx.Ctx` is `nil`

https://github.com/go-gitea/gitea/blob/6c354546547cd3a9595a7db119a6480d9cd506a7/modules/markup/html.go#L615
