### ISSUE TITLE
Upload and play videos in issues - which is a very common need for mobile and frontend devs

### ISSUE THREAD

**Issue by fzyzcjy** [go-gitea/gitea#23094]
### Feature Description

Hi, thanks for the wonderful self-hosted git server! It would be great if we could upload videos and play them in the issues page. You know, GitHub does support this, and this is very valuable for mobile or frontend developers to discuss bugs. A live example may be https://github.com/flutter/flutter/issues/103847#issuecomment-1423082608 - we can see that, there are a ton of videos in the issue discussion. Without those videos, it is much harder to discuss.

---

EDIT: From https://discord.com/channels/322538954119184384/322538954119184384/1078266109976916058, related issue:

* https://github.com/go-gitea/gitea/pull/22892

**Comment by bauermarkus** [comment]
So I can upload videos without problems and my Android phone does play them very well in it's Chrome Browser?
So you just want to embed it?

**Comment by delvh** [comment]
That should be possible already with "workarounds":
You simply need to upload your video as a normal attachment file, and then write the corresponding `<video src="$ATTACHMENT_PATH">` as per that PR.
I don't know why that shouldn't work?

**Comment by fzyzcjy** [comment]
I guess yes! Looking forward to the next release :)
