### ISSUE TITLE
Characters automatically filled by browser are invisible in 1.18.5

### ISSUE THREAD

**Issue by yp05327** [go-gitea/gitea#23107]
### Description

The characters automatically filled by browser are white color in 1.18.5.
But in the latest version is black. 

Before input:
![image](https://user-images.githubusercontent.com/18380374/221100365-9c7ebecc-5c6d-43ae-9a5b-1bfdde74f454.png)

After:
![image](https://user-images.githubusercontent.com/18380374/221100337-f2e7b4b6-7401-40b2-a814-9d77eac03aa7.png)

In try.gitea.io:
![image](https://user-images.githubusercontent.com/18380374/221100441-6aac97ce-532f-4cb3-bc27-c4d474c00e8e.png)

### Gitea Version

1.18.5

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

helm version 7.0.4

### Database

None

**Comment by wxiaoguang** [comment]
I recalled that I have reviewed a related PR

* https://github.com/go-gitea/gitea/pull/22088

**Comment by yp05327** [comment]
So it is fixed, and just didn't backport into 1.18.
