### ISSUE TITLE
In users' dashboard, it's very slow to load action.

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#23101]
### Description

#19472 refined the indexes, now we have two indexes group. One is `repo_id`, `user_id`, `is_deleted`, another is "act_user_id", "repo_id", "created_unix", "user_id", "is_deleted". But the most frequent page is the dashboard, it will only be affected by `user_id` and `is_deleted`. So I think we should adjust the indexes again. We should add a new index  `user_id`, `is_deleted` for user's dashboard.

### Gitea Version

Latest

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![image](https://user-images.githubusercontent.com/81045/221067190-c24ca200-697c-4310-ae43-0b3066d685c5.png)

### How are you running Gitea?

self-hosted

### Database

None

**Comment by rsq424** [comment]
add new index 
`create index IDX_action_u_d_c
    on action (user_id asc, is_deleted asc, created_unix desc);
`

**Comment by lunny** [comment]
duplicated with #21611
