### ISSUE TITLE
Add number of repos for every filter type

### ISSUE THREAD

**Issue by Morlinest** [go-gitea/gitea#2312]
Hi, what do you think about little improvement of UI (introduced in #2285):
![image](https://user-images.githubusercontent.com/12720041/29363140-15610f5c-828f-11e7-86be-85f1c870c5f2.png)

or with grey color

![image](https://user-images.githubusercontent.com/12720041/29363196-54242e0e-828f-11e7-9c9b-1954cbfa3abc.png)

Any comment or idea is welcome.

**Comment by lafriks** [comment]
Grey looks better. Also I think numbers should be lower like it is in my repositories count above.

**Comment by Morlinest** [comment]
@lafriks Like this? Doesn't fit to screen well.

![image](https://user-images.githubusercontent.com/12720041/29382684-aea7fdfe-82cd-11e7-9a9b-ba66f8ffc5d9.png)

**Comment by Morlinest** [comment]
I was looking at github dashboard. They have filters too, but each filter do own search. Our filter only filters result of search "all" repositories. I can rework rest api and add type to query options.

**Comment by daviian** [comment]
In my opinion numbers are too much. Why not just greyish the filter which does not have any results, don't disable the button, only greyish to give a visual hint?

**Comment by lafriks** [comment]
I also does not like how it looks... Numbers makes interface with too much information. I agree that filters on each tab does need to perform it's own query as otherwise if you could get wrong information about your repositories if you are hitting page size limit

**Comment by Morlinest** [comment]
@daviian @lafriks I agree with you both. I'll try to change search of repositories first, each filter should do own search. Also I have some idea how to make it effective (and after testing on github I found that they had same idea :D)

Edit: Not exactly the same idea (also some bugs there).

**Comment by Morlinest** [comment]
I have some updates. First, with #2326 it's possible to do search for each filter, it can looks like this:

1. Without "counter" (same as now, but with custom search)
![2017-08-18_13-29-12](https://user-images.githubusercontent.com/12720041/29458187-2bff496e-841e-11e7-87d9-fa3f4cc3957a.gif)

2. Without "counter", with additional loader
![2017-08-18_13-26-39](https://user-images.githubusercontent.com/12720041/29458186-2bfe0644-841e-11e7-9dd7-a64c559b5557.gif)

3. Can be same as 2 or 3, but with `count` of repositories for actual filter and `searchQuery`
![image](https://user-images.githubusercontent.com/12720041/29458385-1f5a68aa-841f-11e7-885e-67e8a6f10fa3.png)
![image](https://user-images.githubusercontent.com/12720041/29458395-2c621ad4-841f-11e7-9d33-4f3b06f15675.png)
![image](https://user-images.githubusercontent.com/12720041/29458522-e501c3c8-841f-11e7-93e4-f3d417237492.png)

"Show more repositories" text is shown when actual search hits `limit`.

What do you think guys?

**Comment by lafriks** [comment]
that looks good :+1:

**Comment by Morlinest** [comment]
@lafriks Which one looks best? 

1. With or without additional loader?
2. With or without number of repositories?

**Comment by lafriks** [comment]
@Morlinest with loader & with total repository count

**Comment by daviian** [comment]
@Morlinest One small approvement would be to show a little spinner (or something else) while searching instead of a zero count ;-)

**Comment by lafriks** [comment]
No more spinners, two are already enough :) Just show count label only when data is loaded

**Comment by Morlinest** [comment]
Closed by #2343
