### ISSUE TITLE
template: explore/repo_list:5:200: executing "explore/repo_list" at <.Owner.Name>: can't evaluate field Name in type *models.User

### ISSUE THREAD

**Issue by strk** [go-gitea/gitea#2313]
- Gitea version (or commit ref): 722bcefbbf26f4bca74f160295611cc982b364dc

- Database (use `[x]`):
  - [x] PostgreSQL

## Description

Right after going to `/expore/repo` (there's no repository) results in an error printed in page:
```
template: explore/repo_list:5:200: executing "explore/repo_list" at <.Owner.Name>: can't evaluate field Name in type *models.User
```

**Comment by lunny** [comment]
@strk can you reproduce it on https://try.gitea.io ?

**Comment by strk** [comment]
On August 17, 2017 3:26:59 AM CEST, Lunny Xiao <notifications@github.com> wrote:
>@strk can you reproduce it on https://try.gitea.io ?

It takes a new install with no repositories so cannot be reproduced on try.gitea.io unless we reset to empty
--strk;

Sent from hand-held device, sorry for brevity
