### ISSUE TITLE
closing issues via commit on non-default branch

### ISSUE THREAD

**Issue by janstuemmel** [go-gitea/gitea#2314]
it's possible to close issues via commit message by pushing to a non-default branch, expected behavior should be that an issue only closes on commits on default branch (master). this is important for code reviewing workflows, where the code-reviewer megres/rebases a feature branch to master.

related: gogits/gogs#4699

**Comment by lunny** [comment]
@lafriks I think this is a feature not a bug.

**Comment by lafriks** [comment]
@lunny I would call it undesired behaviour :) so it is somewhere in between :)

**Comment by bkcsoft** [comment]
:trollface:

**Comment by janstuemmel** [comment]
would consider this as bug, closing issue via commit in a feature branch should not be possible
