### ISSUE TITLE
post-receive git hook fails because "test -x" returns incorrect exitcode

### ISSUE THREAD

**Issue by chylek** [go-gitea/gitea#23141]
### Description

Gitea's `post-receive` script (part of its git hook mechanism) is not executing scripts in `post-receive.d`.
Its `test -x` command to check for executable files in `post-receive.d` directory always exits with code `1`, even when testing a file that has executable flag set.

Running in Docker, gitea 1.18.5.

May be related to https://github.com/alpinelinux/docker-alpine/issues/156 and #21455.

### Gitea Version

1.18.5

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

Alpine in Docker 18.09.6

### How are you running Gitea?

Using docker-compose as instructed by https://docs.gitea.io/en-us/install-with-docker

### Database

MySQL

**Comment by wxiaoguang** [comment]
Your docker is too old. Please use docker server >=20.10.6

**Comment by chylek** [comment]
Thanks, updating Docker solved the issue.
