### ISSUE TITLE
Repository homepage readme cannot render images of the repository.

### ISSUE THREAD

**Issue by hiifong** [go-gitea/gitea#23151]
### Gitea Version

v1.19+

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

![image](https://user-images.githubusercontent.com/89133723/221368185-4860b1f4-297f-4cbf-a203-4d1c46758631.png)
![image](https://user-images.githubusercontent.com/89133723/221368236-ca83afb6-6129-46a4-aed1-9b9e1c3171fb.png)

### How are you running Gitea?

./gitea web

### Database

None

**Comment by yp05327** [comment]
Branch Name is missing in the link. 

The Wrong One:
https://gitea.com/hiifong/AuthenticatorPro/media/branch/doc/Rebranding/Wordmark.png
The Right One:
https://gitea.com/hiifong/AuthenticatorPro/media/branch/master/doc/Rebranding/Wordmark.png
