### ISSUE TITLE
Redirect failed after install gitea

### ISSUE THREAD

**Issue by yp05327** [go-gitea/gitea#23184]
### Description

After you install the gitea, it will redirect to user/login,
In 1.18 and 1.19, it works well but in the latest version,
you will get an error in console:
![image](https://user-images.githubusercontent.com/18380374/221735389-b56a8bbd-4f12-4f55-afdc-9c22b657b5ba.png)

### Gitea Version

latest

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

devcontainer

### Database

None

**Comment by wxiaoguang** [comment]
The install page does have some bugs 😂.

But about this issue .... what is `contents.js`? It doesn't look like a Gitae file.

**Comment by stuzer05** [comment]
> 

Try disabling browsser extensions. For example, firefox has troubleshoot mode (in the burger menu, help)

**Comment by wxiaoguang** [comment]
I think I know this problem now. I will propose a complete fix for all bugs of the install page.

**Comment by yp05327** [comment]
> I think I know this problem now. I will propose a complete fix for all bugs of the install page.

I can't reproduce this in my local pc. 
But as you can fix this, I will let this issue open.

**Comment by wxiaoguang** [comment]
See  Fix various bugs for "install" page #23194
