### ISSUE TITLE
GET data: net::ERR_INVALID_URL

### ISSUE THREAD

**Issue by yp05327** [go-gitea/gitea#23183]
### Description

Delete `data` and `app.ini`, run the server, access the install page, and you will get this error in console
![image](https://user-images.githubusercontent.com/18380374/221734743-26f8c106-4fd4-4e08-a41d-449e02601cbf.png)

~~This will not happen in 1.18.x~~

### Gitea Version

latest

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

localhost

### Database

None

**Comment by wxiaoguang** [comment]
IMO it's not a serious bug and it's not related to `data` directory.

I think it's caused by the incomplete `manifest` in HTML head.

![image](https://user-images.githubusercontent.com/2114189/221736396-f25cc620-d0ac-480a-8509-e1030156f995.png)

**Comment by yp05327** [comment]
> IMO it's not a serious bug and it's not related to `data` directory.
> 
> I think it's caused by the incomplete `manifest` in HTML head, I guess 1.18.x also has the same problem?
> 
> ![image](https://user-images.githubusercontent.com/2114189/221736396-f25cc620-d0ac-480a-8509-e1030156f995.png)

@wxiaoguang 
You are right.
1.18.x also has the same problem.
