### ISSUE TITLE
Clone Button Rearrangement

### ISSUE THREAD

**Issue by BlenderDefender** [go-gitea/gitea#23202]
### Feature Description

Currently, the Clone and Download Buttons use a lot of horizontal space and only the download/clone in editor buttons are "hidden" in a Dropdown-Menu. Being used to the GitHub UI, this UI feels a bit messy and unlogical. Why does the full clone section have to be visible all the time? Why are the download buttons hidden behind "..."?

Therefore, I'd suggest rearranging the clone/download section to look similar like on GitHub, see attached Screenshots.
This would have the following benefits:
- Unless needed, the Clone/Download UI is out of the way, creating more blank space.
- Inside the dropdown menu, there is more space for the Clone/Download UI, so buttons and links can be made larger

Also, inside the dropdown, a second tab can be added (similar to how GitHub does it, see screenshot) to simplify the UI even further, especially with more items added, like PR #22378
![grafik](https://user-images.githubusercontent.com/61777131/222010835-656160d4-6edf-46c5-bd09-284987b60cc5.png)

### Screenshots

Current Implementation:
![grafik](https://user-images.githubusercontent.com/61777131/222008109-1d513e49-e037-41f2-803f-104412e5df68.png)

Suggested Implementation (Mockup, details may change):
![grafik](https://user-images.githubusercontent.com/61777131/222009304-9dfce46b-98da-4a86-ae79-d714d4813bce.png)

**Comment by BlenderDefender** [comment]
Mockup for a two-tab layout:
![grafik](https://user-images.githubusercontent.com/61777131/222255092-78e5ba17-a0a7-4eac-bc37-b30625cca0c3.png)

**Comment by silverwind** [comment]
One thing I do not like about this is that it takes two clicks to copy a SSH URL in GitHub UI, while this can be done in one click in the Gitea UI.

Also, I'm not sure we are really starved for space like GitHub is with their very condensed layout. We do have more space available to show the URL.
