### ISSUE TITLE
Add searched repo type to api/repo/search

### ISSUE THREAD

**Issue by Morlinest** [go-gitea/gitea#2321]
I want to add an option to look for a specific type of repo (`fork`,` mirror`, `source`,` collaborative` or `all`). I think there are two options how to search repositories:

1. Search only 1 type - this means `SearchRepoOptions` will contain 1 attribute with one of possible values
2. Search any combination of types at once - this means `SearchRepoOptions` will contains every possible option and result will be their mix (OR), for example `mirror` OR ` fork` repositories

Any opinion? I've already done the first option, but second can be done very fast too.

**Comment by lunny** [comment]
I think one is enough.

**Comment by Morlinest** [comment]
On first option I don't like the code (can be just bad because of my skills in GO and understanding this project code). I need new type `RepoType`, const for each type (like `RepoTypeAll`,`RepoTypeFork`, ...) and then 'map[string]RepoType' in handler to map query to this types. In second option, I can add each type directly to `SearchRepoOptions` as bools and use `if`s in handler to set it. This is my "code" dilema :D

**Comment by lunny** [comment]
I like first option.

**Comment by Morlinest** [comment]
@lunny OK :) Will send PR soon, you can assign this issue to me.

**Comment by Morlinest** [comment]
Closed by #2756
