### ISSUE TITLE
Mac - Actions not show up (using brew)

### ISSUE THREAD

**Issue by ekoiav** [go-gitea/gitea#23223]
### Description

In Mac, I use brew to install Gitea, from this [docs](https://docs.gitea.io/en-us/install-from-package/#macos).
And I made changes in /usr/local/bin/custom/conf/app.ini to enable Actions. But nothing happened.  

Runner Management still not shown up.

Am I doing something wrong? Or this feature is not release yet for Mac?

Thank you

### Gitea Version

1.18.3

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

Mac

### How are you running Gitea?

I installed it using brew. And run it from terminal using _gitea_ command

### Database

MySQL

**Comment by jolheiser** [comment]
Actions are not in `1.18.x`. They are available for testing in 1.19, which only has an rc out currently.

You could theoretically use `gitea-head` from the brew tap, but that follows the main branch so be aware.

You could either grab a 1.19 binary manually, install the head tap, or wait until 1.19 is fully released.
