### ISSUE TITLE
releases/tag page looks broken when no release has been created

### ISSUE THREAD

**Issue by wiktor-k** [go-gitea/gitea#23221]
### Description

GitHub properly displays release/tag page for tags even if the release has not been created:

![2023-03-01-14-55-53](https://user-images.githubusercontent.com/1718963/222161414-efce548b-8796-4568-a09b-633e9e943f16.png)

Live URL: https://github.com/wiktor-k/pysequoia/releases/tag/v0.1.14

Compare that with the same view of the same object in Gitea:

![2023-03-01-14-56-09](https://user-images.githubusercontent.com/1718963/222161489-47bec14f-638e-47c8-9572-13b1f20a7423.png)

Live URL: https://try.gitea.io/wiktor/pysequoia/releases/tag/v0.1.14

The title and description are missing and there's a broken markup (`%!s(<nil>)`) which should default to repository's default branch.

I'd be happy to contribute a fix if this is considered a valid issue.

Thanks for your time!

### Gitea Version

1.20.0+dev-48-g04347eb81

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

Screenshots attached in the bug description.

### How are you running Gitea?

I'm using try.gitea.io

### Database

None

**Comment by silverwind** [comment]
> The title and description are missing and there's a broken markup (%!s(<nil>)) which should default to repository's default branch.

If by "title and description" you mean the tag message: Yes this would be a very welcome addition. I had requested in the past as well.

The `<nil>` is definitely a bug.

**Comment by wiktor-k** [comment]
:thinking: hmm even though the commit was merged into `main` it didn't close this issue for some reason. I'll close it manually (as from my PoV it has been completed).

Thank you all for help! I really appreciate it! :pray:

**Comment by silverwind** [comment]
> 🤔 hmm even though the commit was merged into `main` it didn't close this issue for some reason. I'll close it manually (as from my PoV it has been completed).
> 
> Thank you all for help! I really appreciate it! 🙏

GitHub's parser is not so smart and did not recognize your "This PR fixes several issues reported in https://github.com/go-gitea/gitea/issues/23221.". If you put a simple "Fixes: #12345" next time, it will automatically pick it up.
