### ISSUE TITLE
Incorrect alignment of "Viewed" checkbox for long (wrapped) file names

### ISSUE THREAD

**Issue by jpraet** [go-gitea/gitea#23248]
### Description

For files with long (line-wrapped) filenames, the "Viewed" checkbox is misaligned.

### Screenshots

![image](https://user-images.githubusercontent.com/2212615/222460308-4515a11c-30e2-4b79-897c-0c84050dfcb2.png)

reproduced on [try.gitea.io](https://try.gitea.io/jpraet-org/test_rep/pulls/1/files):

![image](https://user-images.githubusercontent.com/2212615/222462128-14acb5f0-6f32-43c8-a3a8-ff5d83ce75bc.png)

### Gitea Version

1.18.5

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

Windows

### Browser Version

Firefox 102.8.0.esr

**Comment by delvh** [comment]
Looks less like the `Viewed` checkbox is broken, and more like that whole group mysteriously gets shifted.
I think these buttons should always be at the same x position.

**Comment by silverwind** [comment]
Could probably be fixed by moving the `.diff-file-header-actions` into the same flexbox with the filename.

**Comment by HesterG** [comment]
Maybe it is better to add `text-overflow: ellipsis;` to the long text, so  the file name line won't be in two or more lines?

**Comment by jpraet** [comment]
Related, this "Changed since your last review" on 3 lines also looks kind of weird:

![image](https://user-images.githubusercontent.com/2212615/222673307-57f7146c-5f30-4c2d-8949-96fa9b6bf7a4.png)

**Comment by silverwind** [comment]
> Besides the misalignment, maybe it is better to add `text-overflow: ellipsis;` to the long text, so the file name line won't be in two or more lines?

I think two lines is still an okay display. There is [-webkit-line-clap](https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-line-clamp) which all major browsers support where we could limit the line number to two and in addition add the ellipsis so it will wrap to two lines and add ellipsis on the end of the second line.

**Comment by jpraet** [comment]
#22844 (Always go full width in PR view) would not fix this, but would reduce the likelihood of it happening.
Perhaps it can be backported to 1.18?

**Comment by silverwind** [comment]
I have no personal interest for backporting into 1.18 at this point as 1.19 isn't too far off.
