### ISSUE TITLE
Default to `histogram` diff algorithm

### ISSUE THREAD

**Issue by Maxattax97** [go-gitea/gitea#23255]
### Feature Description

Compelling research exists to suggest that the `histogram` diff algorithm is much superior to `myers`. This makes diffs smaller and easier to read in various edge cases. If `histogram` is not available, `patience` is close but less performant.

https://link.springer.com/article/10.1007/s10664-019-09772-z

If this request is denied, could you please advise how to alter a server setup to use this? i.e., which `.gitconfig` file should I change?

**Comment by silverwind** [comment]
This was discussed in the past in https://github.com/go-gitea/gitea/issues/20467 and I generally think it is a welcome change.

In which git version was `histogram` introduced?

Actual change can be done around here: https://github.com/go-gitea/gitea/blob/main/modules/git/git.go#L205.

**Comment by Maxattax97** [comment]
@silverwind :cake:  https://github.com/go-gitea/gitea/pull/23257
