### ISSUE TITLE
Create global teams which could be used by each organization

### ISSUE THREAD

**Issue by KroMignon** [go-gitea/gitea#23262]
### Feature Description

My original concern was to find a way to made all repository (even privates) listable for each registered user cf. feature request #23117  (as I could not reopen the FR, I create a new one).

@wolfogre suggests my to use teams for this, which is a good way to solve my issue but it is not very "comfortable" to use. Because those teams have to be created for each organization and when a new user have to be added, it must be done for each organization!

It is possible to create a kind of "default/global/template teams", which could be used by each organization?

For example, a Gitea admin user creates global teams with default allowed accesses.
Then for each organization, those "global teams" are visible and could be used as they are or with"adjusted" allowed accesses.

This will allow administrators to managed those global teams, and all changes will be applied to any organization which uses those teams.

Is this feasible or will it break Gitea?

**Comment by lunny** [comment]
Is this a duplication of #3642?

**Comment by KroMignon** [comment]
@lunny Yes! This is exactly what I need.
Sorry  for the noise, haven't see it.

Is this FR still "alive", is there a chance it could be implemented in a future release of Gitea?
