### ISSUE TITLE
Diff view of editor is broken

### ISSUE THREAD

**Issue by JakobDev** [go-gitea/gitea#23265]
### Description

The diff of the built-in Editor is completely broken. It doesn't show the Line numbers and also doesn't show, when another part of the file starts.

### Screenshots

The diff of the Editor:
![grafik](https://user-images.githubusercontent.com/15185051/222700247-ba4ab456-5b23-472f-8455-ed3a320eaa17.png)

The normal diff view after making the commit for comparison:
![grafik](https://user-images.githubusercontent.com/15185051/222700410-2ae7f5d0-ba65-4f5a-8847-040df8bc0e75.png)

### Gitea Version

1.18.3

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

Manjaro

### Browser Version

Firefox 110

**Comment by lunny** [comment]
Could you try 1.18.5?

**Comment by wxiaoguang** [comment]
On try.gitea.io, it's also broken.

<details>

![image](https://user-images.githubusercontent.com/2114189/222705678-959c923c-c2d8-426f-9159-035c14a8646d.png)

</details>

**Comment by silverwind** [comment]
"broken" does not accurately describe this issue.

**Comment by wxiaoguang** [comment]
It has been broken for long time, not only one regression I guess.

See  Fix broken code editor diff preview #23307
