### ISSUE TITLE
Migration from 1.16.9 to 1.18.3 or 1.16.9 to 1.17.3. Leads to an error 500 when we create a new pull request

### ISSUE THREAD

**Issue by cthed2** [go-gitea/gitea#23274]
### Description

Steps to reproduce in the instance that we have running.

- Start with version 1.16.9.
- Change docker-compose file to point to 1.18.3
- Start server (docker-compose up).
- Go to personal repo and fork.
- Change readme in the repo and commit on separate branch (patch-1)
- Request pull request.
- Error 500.

we saw the same issue earlier going from 1.16.9 to 1.17.3 and tried to figure out if it was someting in our configuration. But now we can repeat this consistently.

The error does not occur in the curren gitea demo instance.

### Gitea Version

1.18.3

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/cthed2/95e54a7d76721831838638de6131f747

### Screenshots

![image](https://user-images.githubusercontent.com/56838693/222829094-515b34a5-320b-4a8c-8ff3-c84b182085cf.png)

### Git Version

2.38.1

### Operating System

Ubuntu 22.04

### How are you running Gitea?

Running from docker

### Database

SQLite

**Comment by techknowlogick** [comment]
This may be fixed in 1.18.5, could you update to that?
The error in the logs is `server_1  | 2023/03/03 20:42:25 ...s/context/context.go:233:HTML() [E] [64025bb1-59] Render failed: template: repo/issue/view_content/pull:332:69: executing "repo/issue/view_content/pull" at <.Issue.PullRequest.GetDefaultMergeMessage>: can't evaluate field GetDefaultMergeMessage in type *issues.PullRequest`

**Comment by FvD** [comment]
Thank you @techknowlogick 

- We updated from the failing version 1.18.3 to 1.18.5. We can reproduce the same error.
- We then did the full update cycle from 1.16.9 to 1.18.5 (just to check if there is something int he database migration that has been fixed) --> same error.

Is there any additional information we can provide to help solve this issue?

**Comment by wxiaoguang** [comment]
You might be using custom templates? If yes, revert to the official one.
