### ISSUE TITLE
Add possibility to reuse internal git processes

### ISSUE THREAD

**Issue by PulsarFX** [go-gitea/gitea#23270]
### Feature Description

Currently gitea starts one or more new git.exe processes to handle incoming requests.
We have 300+ repos we need to push. This takes about 5-8minutes to finish (using c# gitea api).
I assume, that most of the time is lost inside gitea from starting and stopping git processes, like you can see in this process explorer screenshot:

![giteaPushLotsOfGitExe](https://user-images.githubusercontent.com/4960210/222752951-9e034b56-95a6-43b0-beef-4ed68c4ac081.png)

There should be a way to keep a bunch of git processes running to make gitea reuse them (like worker processes in apache or similar servers)
(or is it already possible?)

**Comment by wxiaoguang** [comment]
IMO it's not possible .... (maybe you could try the `gogit` version, but I guess it doesn't help too much)

If you have a heavy server, I think Gitea on Linux wins.

**Comment by zeripath** [comment]
I just don't think it's possible. We provide builds with gogit for those on Windows because of the issue of expensive processes.

**Comment by silverwind** [comment]
Unless git has a interface where you can pipe in multiple commands into a single process, I see no way.

**Comment by PulsarFX** [comment]
Thanks for all your feedback. I'll try with the gogit Version.

**Comment by stuzer05** [comment]
> Thanks for all your feedback. I'll try with the gogit Version.

gogit repository has been archived by the owner on Mar 25, 2022. It is now read-only.

**Comment by zeripath** [comment]
Which repository are you referring to? https://github.com/go-git/go-git is not archived

**Comment by stuzer05** [comment]
> Which repository are you referring to? https://github.com/go-git/go-git is not archived

Pardon me, might've seen the wrong one https://github.com/speedata/gogit

**Comment by PulsarFX** [comment]
I mean the gitea build with gogit

**Comment by PulsarFX** [comment]
Feedback on using  gitea-1.18.5-gogit-windows-4.0-amd64.exe : 
- Process Explorer looks about the same, 
- Test scenario takes about the same time
- but it has far less impact on the CPU

**Comment by wxiaoguang** [comment]
> maybe you can put a hint or a description to the main page on what gogit is or what it does different to the gitea-1.18.5-gogit-windows-4.0-amd64.exe

There was one: https://docs.gitea.io/en-us/install-from-binary/#choosing-the-right-file

Feel free to improve the documents ~~

**Comment by wxiaoguang** [comment]
> Test scenario takes about the same time

ps: I suspect there might be other bottlenecks, for example, disk io? network? And Gitea needs the real git.exe (not the gogit) to handle push/pull in many cases, so Linux wins 😂 Sever performance optimization is a big topic.
