### ISSUE TITLE
Gitea 1.2 when will it be finished?

### ISSUE THREAD

**Issue by lcges** [go-gitea/gitea#2328]
Listen, version 1.2 already has a lot of delay ...
From two months is 99% of the finished milestone (1.2).

It was 99% and 480 commits
Today 99% and 612 commits

This way you will never close the version.

**Comment by lunny** [comment]
I think maybe next week. Sorry for the delay.

**Comment by strk** [comment]
Please don't close 1.2 before having merged #2276
That PR is to complete the OpenID support, which is new in 1.2.0

**Comment by appleboy** [comment]
maybe we should create the release/v1.2 branch and release rc1 version. move the discussion to https://github.com/go-gitea/gitea/issues/2329

**Comment by xf-** [comment]
duplicate of #2283
