### ISSUE TITLE
JavaScript error: Uncaught TypeError: i.onChange is not a function

### ISSUE THREAD

**Issue by hiifong** [go-gitea/gitea#23295]
### Description

https://user-images.githubusercontent.com/89133723/222884909-b8111053-fc71-4ca0-8358-8c8959e9e03c.mp4

### Gitea Version

v1.20.0

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

![image](https://user-images.githubusercontent.com/89133723/222884952-f5e90b0e-4fe2-4c30-b2bf-3a2489c5d42d.png)
![image](https://user-images.githubusercontent.com/89133723/222884961-217570f9-cac6-445e-96c2-0ea5f586a040.png)

### How are you running Gitea?

use gitea.com

### Database

None

**Comment by wxiaoguang** [comment]
Try latest main branch, it should have been fixed

**Comment by hiifong** [comment]
> Try latest main branch, it should have been fixed (fixed by #23168 together)
> 
> Oh, just saw `gitea.com`, then site admin could do a upgrade.

It has been fixed
