### ISSUE TITLE
X-Gitea-Debug header being sent 3 times

### ISSUE THREAD

**Issue by stuzer05** [go-gitea/gitea#23308]
### Description

On view commit diff page, commit file request X-Gitea-Debug header is duplicated 3 times

### Gitea Version

latest master

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![image](https://user-images.githubusercontent.com/23124682/222958089-fea0032e-e22d-414d-bc6f-d2d1386f8ef9.png)

### How are you running Gitea?

Latest master, make watch-backend, make watch-frontend

### Database

None

**Comment by wxiaoguang** [comment]
It must be caused by repeated/duplicate calls to `httpcache.AddCacheControlToHeader`. That's not ideal, but luckily there is not side effect at the moment ....

**Comment by stuzer05** [comment]
Is there a reason to call `httpcache.AddCacheControlToHeader` 3 times? Looking on code, it seems it doesn't do anything different with each call

**Comment by wxiaoguang** [comment]
Of course no reason .... 😂 so that's not ideal.
