### ISSUE TITLE
Outdated detectable documentation translation

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#23316]
### Feature Description

Currently, when you view a non-English documentation, you don't know if it's outdated or not.

I propose adding new metadata key `version` to every documentation page like

```
---
date: "2016-12-01T16:00:00+02:00"
version: 1
---
```
And everytime a documentation update, we need to check whether we need to upgrade the version within the PR.
If it's an English documentation and extra content added, the version should be incremented 1.
If it's a non-English documentation and the change will make it keep consistent with related English version, then change the version to the same value which is in the English version documentation.

So, when we generated non-English version documentation, if version is not the same as related English version, it's outdated. Then we can add a top warning bar to display that this documentation is outdated.

**Comment by delvh** [comment]
Or we simply start adding our docs files to Crowdin/ Weblate/ …, and can simply use the latest version without a version requirement.

**Comment by lunny** [comment]
> Or we simply start adding our docs files to Crowdin/ Weblate/ …, and can simply use the latest version without a version requirement.

I don't whether it's suitable to translate the article in crowdin?

**Comment by a1012112796** [comment]
> > Or we simply start adding our docs files to Crowdin/ Weblate/ …, and can simply use the latest version without a version requirement.
> 
> I don't whether it's suitable to translate the article in crowdin?

looks the wails project has using crowdin for the documents translation, ref: https://crowdin.com/project/wails/zh-CN

**Comment by lunny** [comment]
Resolved by https://gitea.com/gitea/gitea-docusaurus/pulls/25
