### ISSUE TITLE
Failed to start gitea.service, but ok if run the command as git

### ISSUE THREAD

**Issue by qualing** [go-gitea/gitea#23329]
### Description

after installation, I tried to write a service file so that I can boot/manage gitea as a service. However, it says I don't have permission.
But it can run with command (even when I switched to user git, which is the user of the service environment).
Service file written as code below:

    [Unit]
    Description=Gitea (Git with a cup of tea)
    After=syslog.target
    After=network.target
    After=mariadb.service
    
    [Service]
    RestartSec=2s
    Type=simple
    User=git
    Group=git
    WorkingDirectory=/var/lib/gitea/
    ExecStart=/usr/local/bin/gitea web -c /etc/gitea/app.ini
    Restart=always
    Environment=USER=git HOME=/home/git GITEA_WORK_DIR=/var/lib/gitea
    
    [Install]
    WantedBy=multi-user.target

### Gitea Version

1.19

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![图片](https://user-images.githubusercontent.com/41828388/223053261-8e71c927-30e6-4520-8b0b-1ba43c564012.png)
![图片](https://user-images.githubusercontent.com/41828388/223054600-1e86d62b-6b8a-42ab-9c76-38b329eb47f5.png)

### Git Version

2.31.1

### Operating System

rockylinux9

### How are you running Gitea?

using official gitea distribution

### Database

MySQL

**Comment by wxiaoguang** [comment]
There is an error message , permission denied.


I would suggest to use docker. It's difficult to make gitea work well with manually binary installation

**Comment by qualing** [comment]
> There is an error message , permission denied.
> 
> I would suggest to use docker. It's difficult to make gitea work well with manually binary installation

That's a great piece of advice, but unfortunately I need to run the binary instead of docker image for some network reasons.

**Comment by wxiaoguang** [comment]
Then you could try to resolve the "permission denied." error.

**Comment by eeyrjmr** [comment]
Please post the output of 
`namei /usr/local/bin/gitea `

I suspect the user **git** doesn't have rx  permissions for the gitea binary OR does not have rx permissions for any of the parent directories 

ALSO please paste

`namei /var/lib/gitea `
The user git MUST own this directory and must have rx permissions for the parent directories

**Comment by qualing** [comment]
> 

I've already checked them before I posted this issue.
![图片](https://user-images.githubusercontent.com/41828388/223358289-14cb2948-42ae-43c0-9ad4-902eb983a5cd.png)

**Comment by qualing** [comment]
> Please post the output of `namei /usr/local/bin/gitea `
> 
> I suspect the user **git** doesn't have rx permissions for the gitea binary OR does not have rx permissions for any of the parent directories
> 
> ALSO please paste
> 
> `namei /var/lib/gitea ` The user git MUST own this directory and must have rx permissions for the parent directories

I've checked them before I posted this issue.
![图片](https://user-images.githubusercontent.com/41828388/223358415-b463a417-9860-441c-bf2d-07804bb23ec6.png)

**Comment by eeyrjmr** [comment]
sorry... forgot to request an argument

`namei -l /usr/local/bin/gitea `


I appreciate you have checked but there is clearly some access that is blocking it for user git, so this recursive method should highlight it

**Comment by qualing** [comment]
> sorry... forgot to request an argument
> 
> `namei -l /usr/local/bin/gitea `
> 
> I appreciate you have checked but there is clearly some access that is blocking it for user git, so this recursive method should highlight it

It's owned by root, but git should have read and execute permission.
![图片](https://user-images.githubusercontent.com/41828388/223543082-ca9aeb52-7c52-4a0f-b5bb-55c268e63f8f.png)

**Comment by eeyrjmr** [comment]
I agree with permissions like that, the user git can traverse to that directory and should be able to EXECUTE the executable ... without knowing your mount structure *IF* /usr/local/ was its on mount and the mount had noexec then well nothing would be able to exec :) 

the systemd logs are hiding some gitea specific information so it might be worth executing gitea manually as git to see what it outputs.
Could you please do theses steps
1. gain a root shell (su or other means)
2. change user to git 
3. launch gitea 

`$su
Password:
# su git 
sh-5.2$ /usr/local/bin/gitea web -c /etc/gitea/app.ini`

**Comment by qualing** [comment]
> I agree with permissions like that, the user git can traverse to that directory and should be able to EXECUTE the executable ... without knowing your mount structure _IF_ /usr/local/ was its on mount and the mount had noexec then well nothing would be able to exec :)
> 
> the systemd logs are hiding some gitea specific information so it might be worth executing gitea manually as git to see what it outputs. Could you please do theses steps
> 
>     1. gain a root shell (su or other means)
> 
>     2. change user to git
> 
>     3. launch gitea
> 
> 
> ```
> $su
> Password:
> # su git 
> sh-5.2$ /usr/local/bin/gitea web -c /etc/gitea/app.ini
> ```

Actually, you can see the outputs when I run the binary as git in the first screenshot. Could you be more specific?

**Comment by eeyrjmr** [comment]
Sorry, just read up. 
So this means the permissions and structure for gitea is valid and thus this is a systemd issue... 
are you 100% sure the service is enabled?

**systemctl status gitea**

**Comment by qualing** [comment]
> Sorry, just read up. So this means the permissions and structure for gitea is valid and thus this is a systemd issue... are you 100% sure the service is enabled?
> 
> **systemctl status gitea**

Yes, 100% sure.
![图片](https://user-images.githubusercontent.com/41828388/223552679-278d3711-da94-4bb7-920a-1fc29f27960a.png)

**Comment by eeyrjmr** [comment]
or you are on a SELinux system and it has flagged the gitea executable as sus.

# restorcon -rv /usr/local/bin/gitea

**Comment by qualing** [comment]
> 

Sorry, it's rocky linux, so I cannot use this command.

**Comment by eeyrjmr** [comment]
you should be able to?  rocky is a CentOS brought back into the community and since RH/Centos-Streams uses SELinux so does rocky. 

do you have a /var/log/audit/audit.log  file?   if you do, if you grep for gitea is it listed?

**grep gitea /var/log/audit/audit.log**

**Comment by qualing** [comment]
Oh you're right. I've got a typo. After running
`sudo restorecon -rv /usr/local/bin/gitea`
the service can now be booted. Thank you so much.
![图片](https://user-images.githubusercontent.com/41828388/223554852-eb724a72-c05f-46ae-9566-c9b7f4bc3596.png)
