### ISSUE TITLE
?go-get=1 not working if REQUIRE_SIGNIN_VIEW = true 

### ISSUE THREAD

**Issue by sulliwane** [go-gitea/gitea#2333]
- Gitea version (or commit ref): 1.1.3
- Operating system: Ubuntu server 16.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No, I can't change the app.ini settings
  - [ ] Not relevant

## Description
?go-get=1 not working on repo url, if ```REQUIRE_SIGNIN_VIEW = true``` in ```app.ini```, because redirected to login page

**Comment by strk** [comment]
What would you expect to happen ?
Doesn't the `?go-get=1` response count as `view` ?

**Comment by sulliwane** [comment]
I have my **login/password** stored in a ```~/.netrc```, which let me ```go get my.gitea.com/private/repo``` <- PRIVATE REPO.

The problem is that, if ```REQUIRE_SIGNIN_VIEW = true``` is enabled, the behavior described above doesn't work anymore.

I'm not 100% sure about the meaning of the ```REQUIRE_SIGNIN_VIEW``` option, but I think it should not make ```go get private/repo``` stop working...

Is it the same issue as this one : https://github.com/gogits/gogs/issues/1878  ?

**Comment by strk** [comment]
It looks like this was fixed in Gogs with this commit:
https://github.com/gogits/gogs/commit/e33c714073cc65f814bacf604a84cd2741951afa

Do you feel like opening a pull-requests porting it here ?
Best if it includes an automated test

**Comment by lafriks** [comment]
I think @bkcsoft fixed this in gitea master also

**Comment by lafriks** [comment]
I think this is fixed with #2010

**Comment by bkcsoft** [comment]
Yeah it's fixed in #2010, though hasn't been backported to 1.1.x

**Comment by lafriks** [comment]
I'm closing issue than. It will be fixed with 1.2.0 release
