### ISSUE TITLE
AssertExistsAndLoadBean not works well?

### ISSUE THREAD

**Issue by yp05327** [go-gitea/gitea#23348]
### Description

I don't know whether I have missed something, but it seems that AssertExistsAndLoadBean will return same result in sometimes?
![image](https://user-images.githubusercontent.com/18380374/223332448-2521fc06-4941-412d-8367-4a21f1a176e0.png)

### Gitea Version

latest

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

build

### Database

None

**Comment by wxiaoguang** [comment]
The dark side of Go and XORM

`Model { Field: 0 }` (any zero-value) won't be put in the `WHERE` clause. Unfortunately, `UserTypeIndividual` is 0

**Comment by lunny** [comment]
Yes, so you can use `unittest.AssertExistsAndLoadBean(t, &user_model.User{}, builder.Eq{"visibility":structs.VisibleTypePrivate, "type":user_model.UserTypeOrganization})` to avoid the zero problem.

**Comment by yp05327** [comment]
I saw there is a condition parameter, but I didn’t understand why we don’t use it.
So it is used to avoid the zero problem.
Thanks for the answers.
