### ISSUE TITLE
Internal server error toggling OpenID visibility

### ISSUE THREAD

**Issue by strk** [go-gitea/gitea#2338]
Current master version 1.1.0+491-g5707ad3b 
User settings, OpenID, Show in profile -> 500

user/settings/openid/toggle_visibility

**Comment by lafriks** [comment]
What error do you get in log?

**Comment by strk** [comment]
I just tried to reproduce locally but failed. The above was from http://gitea.debian.net so I don't have access to logs.

**Comment by strk** [comment]
Cannot reproduce on try.gitea.io (with 2c3a229) either.
@MTecknology I wonder if my latest commit (you are 2 commits behind) accidentally fixed this bug.
It will help to know more (logs, backend...)

**Comment by strk** [comment]
Cannot reproduce locally with 5707ad3bb72179e90adea16174102303564a22a9 either. That's supposedly the same version running on gitea.debian.net - I'm using a PostgreSQL backend here.

**Comment by MTecknology** [comment]
@strk It looks like it was probably some of the screwing around I was doing that was causing the 500's. It looks like you may have hit it when I was trying to add some caching to nginx.

**Comment by lafriks** [comment]
@strk @MTecknology can this be closed than?

**Comment by strk** [comment]
I'll close, OpenID is now disabled on there anyway.
