### ISSUE TITLE
[Proposal] Keep/add `xmlns` attribute for generated SVG images

### ISSUE THREAD

**Issue by wxiaoguang** [go-gitea/gitea#23409]
### Feature Description

Gitea's SVG files do not have the `xmlns` attribute. Without it, these SVG images couldn't be display correctly. 

*  Browsers (Safari/Chrome/Firefox) only display the XML content, but no the image
* VSCode shows 0 x 0 broken images
* macOS Finder show blank page

Then developers couldn't browse these images, they couldn't know what the images look like before rendering them as inline SVG in a page.

So it's better to keep/add the `xmlns` attribute for the generated SVG files.

https://stackoverflow.com/questions/18467982/are-svg-parameters-such-as-xmlns-and-version-needed

cc @silverwind 

### Screenshots

![image](https://user-images.githubusercontent.com/2114189/224314060-c2d19363-7557-4873-8515-dbb9d8b70be4.png)

![image](https://user-images.githubusercontent.com/2114189/224314438-f83794da-0b09-47e4-903a-9cb7e473dd61.png)

**Comment by silverwind** [comment]
Yes it would be welcome to add `xmlns` to SVGs before rendering. GitHub also recently did this change.

**Comment by silverwind** [comment]
Actually I misread. You are talking about SVG assets, I'm talking about SVG image rendering.

`xmlns` is not optional for SVG embedded inside HTML. It's only necessary when a SVG is rendered as it's own document, which we don't do.

**Comment by wxiaoguang** [comment]
Yup, for rendering, they do not need the xmlns.

We can remove the attribute before rendering, how do you think?

**Comment by wxiaoguang** [comment]
The PR:  Keep/add xmlns attribute for generated SVG images #23410 

The output is still clear, and developers could understand/choose SVG images quickly.
