### ISSUE TITLE
current page lost when deleting a branch from branch list

### ISSUE THREAD

**Issue by opengerp** [go-gitea/gitea#23411]
### Description

current page lost when deleting a branch from branch list

### Gitea Version

1.17.3 built with GNU Make 4.1, go1.18.7 : bindata, sqlite, sqlite_unlock_notify

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

On Rocky Linux Server

### Database

MySQL

**Comment by yardenshoham** [comment]
Please elaborate

**Comment by gerp-dev** [comment]
1. i click on Code
2. i click on Branches
3. i click on page 2  of branches list
4. i click on basket to delete a merged branch
5. i confirm
6. branch i deleted but i am back on page 1 

this is annoying because i must change page each time to remove old branches
thank you!

**Comment by yardenshoham** [comment]
Maybe you could automate what you are trying to do with a script that calls the API. The web UI isn't very suited for your use-case

**Comment by wxiaoguang** [comment]
Yup, some workarounds like API-call or git-client-deletion also work.

If you want to delete branches via UI ... indeed it's a UI bug, maybe it's not too difficult to fix but it needs some time for it 😂

**Comment by wxiaoguang** [comment]
See:  Make branches lit page operations remember current page #23420
