### ISSUE TITLE
VBA/VB6 code not detected in *.frm files (no syntax highlighting and not in language stats)

### ISSUE THREAD

**Issue by King555a** [go-gitea/gitea#23417]
### Description

When uploading a VB6 (Visual Basic 6.0) project to a repository in Gitea, *.frm files, which, among others like *.bas and *.cls, contain VB6 code, these are not affecting the language statistics bar and there is no syntax highlighting. I even tried `linguist-language=vb6` to override it, which changed nothing.

And I also think that the *.bas files, where syntax highlighting works, are not calculated into the statistics. I have *.bas files with many thousands of lines, but my repo is detected as 95% HTML. The HTML files have only a few hundred lines.

Sorry if this should be posted as an issue at the go-enry repo.

### Gitea Version

1.18.5

### Can you reproduce the bug on the Gitea demo site?

Yes

### Git Version

2.39.2

### Operating System

Ubuntu 18.04.6 LTS x64

### How are you running Gitea?

I installed it as a package (https://gitlab.com/packaging/gitea). I also tested it at https://try.gitea.io/

### Database

MySQL

**Comment by wxiaoguang** [comment]
Gitea uses https://github.com/alecthomas/chroma , it seems that Chroma doesn't support VB.

**Comment by wxiaoguang** [comment]
> I thought it's go-enry. So go-enry is just for language detection and chroma for syntax highlighting?

I think you are right 😁 


> At this point I'm unsure where to post this issue, whether it's chroma, go-enry, gitea, ...

A recent highlighting issue is this one, maybe it could help you.

* #22904

Gitea 100% depneds on Chroma to do highlighting. It's impossible to support new languages without upstream support.

And I have experiences with VB6 in old ages. IIRC, VB6 "frm" file is not pure code file, it also contains "form definition", so maybe it needs a new parser & syntax-highlighter (from upstream ....)

The problem is, TBH, VB6 is quite old (and almost dead ...), I am not sure whether upstream could support it easily.

**Comment by wxiaoguang** [comment]
Hmm sorry, I do not what your repository looks like so I guess I can't provide an accurate answer.

The calculation is done by:

```
// GetLanguageStats calculates language stats for git repository at specified commit
func (repo *Repository) GetLanguageStats(commitID string) (map[string]int64, error)
```

You can take a look if you have interests. And without a reproducible example (the real repository), I guess it's difficult to figure out what it should be.

**Comment by wxiaoguang** [comment]
The color is provided by 

```
// LoadAttributes loads attributes
func (stats LanguageStatList) LoadAttributes() {
	for i := range stats {
		stats[i].Color = enry.GetColor(stats[i].Language)
	}
}
```

If the language name is not recognized, then you see different colors.

**Comment by wxiaoguang** [comment]
Yup if it's related to upstream
