### ISSUE TITLE
Repo view, no commit refs shown - bug or normal?

### ISSUE THREAD

**Issue by chaosbunker** [go-gitea/gitea#2341]
- Gitea version (or commit ref): 27798c3
- Operating system: macOS (git 2.14.0)/Ubuntu (git 2.11)
- Database (use `[x]`):
  - [X ] MySQL

Is this what it's supposed to look like? Just links, no commit ref?
<img width="1139" alt="screen shot 2017-08-20 at 12 07 37" src="https://user-images.githubusercontent.com/16366980/29493920-4661ba7a-85a0-11e7-882b-929be8e4df30.png">

this is the view I'm used to from gogs
<img width="997" alt="screen shot 2017-08-20 at 12 06 34" src="https://user-images.githubusercontent.com/16366980/29493929-57b363be-85a0-11e7-95a5-2addfb66c6c3.png">

In the screenshots in the readme, it shows commit refs, that's why I am uncertain.

**Comment by daviian** [comment]
It is a desired behaviour, see https://github.com/go-gitea/gitea/issues/1661

**Comment by chaosbunker** [comment]
That's too bad, I think it was quite useful to have it visible .. please consider switching back! It wasn't really in the way and for something like this I think information is way more important than design

**Comment by daviian** [comment]
@lafriks What's your opinion on this?

**Comment by tonivj5** [comment]
I think it could be optional via a configuration

**Comment by lafriks** [comment]
There is not much use in it as you are not able to easy copy it anyway as it is link and it takes a lot space in file list. Also I don't think looking at hash really means anything to you at least in file list. If you need commits hash from file list you can still get it from commits message url and it will be much easier than copying from UI as it was previously. Other reason is that no other git web ui shows hashes in code file listing
