### ISSUE TITLE
this is more like a standard cookie that will be used for authenticated users question

### ISSUE THREAD

**Issue by kolinfluence** [go-gitea/gitea#23418]
### Feature Description

possible to put into faq the cookie used by logined user?

we have firewall that blocks everything until the cookie is detected.

can u pls give the cookie name that's only available for logined users?
what prefix does it begin with?

e.g. for wordpress it's wordpress_login_

**Comment by wxiaoguang** [comment]
Search "cookie" in example config:

https://github.com/go-gitea/gitea/blob/main/custom/conf/app.example.ini

You can fine-tune every name.

**Comment by ultperf** [comment]
ok thx
