### ISSUE TITLE
browser 'find in page' text search for the content textarea for editing wiki pages or issue comments

### ISSUE THREAD

**Issue by KiaraGrouwstra** [go-gitea/gitea#23413]
### Feature Description

editing a wiki page, it would be nice to have a convenient way to navigate to a particular section of my document.
i would be inclined to try my browser's search function for this, but this does not work.
on the likes of Github one would also instead need to rely on the search function offered by their web application, but in Gitea such a thing currently appears to be missing.
this makes editing longer wiki articles in Gitea less convenient right now.

**Comment by wxiaoguang** [comment]
Searching text in the editor (globally) works.


<img width="1026" alt="Screenshot 2023-03-11 at 17 52 21" src="https://user-images.githubusercontent.com/2114189/224477610-c7538dd0-aa0d-4bc5-afcc-d5be95acbd60.png">

**Comment by KiaraGrouwstra** [comment]
right, thank you for mentioning that.
to clarify, the browser search does indeed seem to work as intended while the text to be searched is within view in the editing box.
however, once you try to search for some text that is (further) out of view, it will no longer be found by browser search for me.

**Comment by wxiaoguang** [comment]
The editor problem will be resolved by #23290 fundementally

At the moment, as a workaround, you could try to click the toolbar button "Revert to simple textarea", then no EasyMDE/CodeMirror problem.

**Comment by delvh** [comment]
I'm not sure but given that #23876 is merged, can this issue be closed?
