### ISSUE TITLE
Disabled releases lead to 404 on tags page

### ISSUE THREAD

**Issue by stuzer05** [go-gitea/gitea#23427]
### Description

When releases are disabled in repo settings, "tags" button leads to 404.

Probably tags page should be still available, but when "releases" button is clicked is should say "Not available".

### Gitea Version

master

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots
![image](https://user-images.githubusercontent.com/23124682/224538787-eb735126-5f14-406f-b76f-3ed22ffcba14.png)

![image](https://user-images.githubusercontent.com/23124682/224538714-48a3d410-91d4-4a69-9a2c-beb9b9fa264b.png)

### How are you running Gitea?

https://try.gitea.io

### Database

None

**Comment by lunny** [comment]
Caused by #22671
