### ISSUE TITLE
Sync fork

### ISSUE THREAD

**Issue by hiifong** [go-gitea/gitea#23423]
### Feature Description

like github sync fork

### Screenshots

![image](https://user-images.githubusercontent.com/89133723/224487294-0d2c89e6-10ae-45f3-acf5-076f7035c38b.png)

**Comment by manuelkamp** [comment]
is there a manual way to sync a fork until this gets implemented?

**Comment by ykong1337** [comment]
> is there a manual way to sync a fork until this gets implemented?

(github docs)[https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork#syncing-a-fork-branch-from-the-command-line]

**Comment by jonathanspw** [comment]
+1

**Comment by wolftune** [comment]
this is a duplicate of https://github.com/go-gitea/gitea/issues/20880
