### ISSUE TITLE
Card preview mode cannot be selected in repo items

### ISSUE THREAD

**Issue by hiifong** [go-gitea/gitea#23422]
### Gitea Version

v1.20+

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

https://user-images.githubusercontent.com/89133723/224485846-9ae3617b-8321-4801-b54b-1c48fe5fbef7.mp4

### How are you running Gitea?

./gitea web

### Database

None

**Comment by yp05327** [comment]
https://github.com/go-gitea/gitea/issues/23318#issuecomment-1463104898
