### ISSUE TITLE
No option to delete a Project?

### ISSUE THREAD

**Issue by baughmann** [go-gitea/gitea#23447]
### Description

I am unable to recreate the issue in the demo instance because I do not have admin rights on it.

How is one supposed to delete a Project from an Organization? For example, at `http://localhost:8080/MyOrg/~/projects/1` I have a project called `MyProject`. There is no "Delete" option to remove this project, nor any option to rename it. There are no "Settings" for the Project on it's page, nor any "Projects" portion of the admin UI.

I cannot find this functionality in any documentation. Am I expected to delete the entire instance and re-initialize if I no longer wish for a Project to exist?

### Gitea Version

1.19

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

2.39.2.windows.1

### Operating System

Windows Server 2022 10.0.20348

### How are you running Gitea?

Windows executable (not Windows Service)

### Database

SQLite

**Comment by delvh** [comment]
Fixed by #23388.
