### ISSUE TITLE
Email notification for pushes to head branch of closed pull request

### ISSUE THREAD

**Issue by brechtvl** [go-gitea/gitea#23440]
### Description

* Enable Settings > Account > And Your Own Notifications (for easier testing with 1 account)
* Fork a repository
* Commit a change to the default branch in the base repository
* Make a pull request on the fork to merge the latest default branch into the fork
* Close pull request without merging
* Commit a change to the default branch in the base repository
* Get an email notification for the closed pull request
* Pull request itself shows no new commit

I'm guessing this started happening after #23189, since I only saw it after updating to a recent version of Gitea.

I think there are two problems:
* Email notifications should not be sent out for closed pull requests in this case. This can lead to potentially a lot emails depending if someone is using this workflow to update their fork.
* Closed pull requests get commit comments but they are hidden. The amount of additional comments can grow effectively quadratically, as more closed pull requests accumulate and more commits are made to the default branch.

### Gitea Version

43c1362 (main)

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

Both own build and try.gitea.io.

### Database

None

**Comment by brechtvl** [comment]
CC @sillyguodong

**Comment by sillyguodong** [comment]
> CC @sillyguodong

copy that, I will check it.

**Comment by sillyguodong** [comment]
> * Email notifications should not be sent out for closed pull requests in this case. This can lead to potentially a lot emails depending if someone is using this workflow to update their fork.

oh, I made a mistake and fix in #23462
