### ISSUE TITLE
PR comment link on viewed files not scrolling

### ISSUE THREAD

**Issue by gempir** [go-gitea/gitea#23466]
### Description

When reviewing a file it is very common for the reviewer to mark these files as "viewed" 
When you now get a link to a comment in a file you already viewed you can't properly open that link because the anchor tag is missing.

Steps to reproduce:
1. Make a PR
2. Add a comment
3. Copy link of the comment (via the 3 dots menu)
4. Mark the file as viewed
5. Open the link

You will land at the top of the PR instead of at the comment.

My example:

https://try.gitea.io/gempir/gempbot/pulls/1/files#issuecomment-163257

First time you will land on the comment 
> Some comment on a file that is already marked as "viewed" for the user opening the link Previous Next

When you now mark that file as viewed you will not land on that comment anymore when you are opening the link above.
(See first screenshot)

Also minor nitpick: The Anchor lands directly on the text of the comment, not a little above, so it's very "cramped". (See second screenshot)

### Gitea Version

1.20.0+dev-163-gd56bb7420

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

![image](https://user-images.githubusercontent.com/9765622/224946900-c22e3329-7562-47b6-9c44-404e41a77b65.png)

![image](https://user-images.githubusercontent.com/9765622/224944930-06e6e43c-e8d7-454f-a0cc-a68058e75aeb.png)

### How are you running Gitea?

https://try.gitea.io/

### Database

None

**Comment by yp05327** [comment]
It seems that the width of the window is related.

Browser: Chrome
- Open a new tab
- F12
- set the window width: 700
- access the example link
![image](https://user-images.githubusercontent.com/18380374/225205354-8c968516-f8d3-4a1c-b10b-bff561450172.png)

- Open a new tab
- F12
- set the window width: 950
- access the example link
![image](https://user-images.githubusercontent.com/18380374/225205619-34236dbd-04ce-42ed-8117-22dd008a5857.png)

- Open a new tab
- F12
- set the window width: 1050
- access the example link
![image](https://user-images.githubusercontent.com/18380374/225205783-9035a89d-9895-4125-a830-a0f4a7f279d5.png)

**Comment by gempir** [comment]
I don't see the file marked as viewed in your screenshots. Can you reproduce this bug even with a wider width?

**Comment by HesterG** [comment]
I think this can be improved to have the same behavior as github: scroll to the comment with the viewed content automatically expand when the hash from url hits the comment.

**Comment by yp05327** [comment]
> I don't see the file marked as viewed in your screenshots. Can you reproduce this bug even with a wider width?

I did't login. So there was no `viewed` button.

**Comment by gempir** [comment]
> > I don't see the file marked as viewed in your screenshots. Can you reproduce this bug even with a wider width?
> 
> I did't login. So there was no `viewed` button.

That's my point. This issue exists only for logged in users. I'm not sure what you meant with the window width because in all your Screenshots the comment is visible.
