### ISSUE TITLE
Scrambeled issues after upgrading Gitea from 1.12.3 to 1.18.5

### ISSUE THREAD

**Issue by KroMignon** [go-gitea/gitea#23467]
### Description

I have upgrade our Gitea Server from Gitea 1.12.3 to current release (1.18.5)

Displaimer: our Gitea server was installed from someone else, years before and this person has left the company months before I came.

To be able to upgrade Gitea, I had to install a patch for MS-SQL Server (KB3158271), to enable TLS 1.3 support.

Here are the steps I followed:
```
net stop gitea
.\gitea.exe doctor --config <path_to_app.ini>
.\gitea.exe migrate --config <path_to_app.ini>
net start gitea
```
All seams to work fine except 2 issues:
1. For some "organisations" (at least only one found at this time), there was not possible to create a new repository. Even with "Maximum Number of Repositories" set to "-1".
I found a simple workaround for this:
* open organization settings
* go to Teams 
*  select the "Owners" team
* click on "settings"
![image](https://user-images.githubusercontent.com/3978902/224960423-88ee9235-e0e0-445f-a598-d247089860c0.png)
* and the click on "Update Settings" (without changing anything)

After that, I was able to add new repository to this organization!

2. This is more complex, we don't have used the "Issues" feature for now with Gitea.
After upgrading Gitea, one of our developer decided to give it a try.
But after adding an issue entry to a repository, the issue got comments from another repository and organization!!
![image](https://user-images.githubusercontent.com/3978902/224962524-3824bd9d-b387-4594-bb33-6991c4fee0be.png)

It looks like the content of our DB is corrupt, at least the tables used for comments and issues.
What can I do?

### Gitea Version

1.18.5

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

2.17.0

### Operating System

Windows Server 2012

### How are you running Gitea?

Gitea is running as a local service (installed with sc.exe) on Windows 2012 Server instance.

### Database

MSSQL

**Comment by lunny** [comment]
I'm surprised `gitea.exe upgrade`. I can't remember if we have that subcommand.

I think maybe because some comments lost their issues. Is there any output when executing `gitea.exe doctor`?

**Comment by KroMignon** [comment]
> I'm surprised `gitea.exe upgrade`. I can't remember if we have that subcommand.

As far I as can remember, this was an output from `gitea doctor`, which want's `gitea upgrade` to upgrade DB schema


> I think maybe because some comments lost their issues. Is there any output when executing `gitea.exe doctor`?

Here the output, all seems OK, except temporary files which could not be removed!

```
> .\gitea.exe doctor --config "custom\conf\app.ini"
[1] Check paths and basic configuration
 - [I] Configuration File Path:    XXX
 - [I] Repository Root Path:       XXX
Warning: can't remove temporary file: 'xxx\doctors-order994423791'
 - [I] Data Root Path:             XXX
Warning: can't remove temporary file: 'xxx\doctors-order3907404991'
 - [I] Custom File Root Path:      XXXX
 - [I] Work directory:             XXXX
 - [I] Log Root Path:              XXXX
Warning: can't remove temporary file: 'XXX\doctors-order3962735954'
OK
[2] Check Database Version
OK
[3] Check if user with wrong type exist
OK
[4] Check if OpenSSH authorized_keys file is up-to-date
OK
[5] Synchronize repo HEADs
 - [I] All 408 repos have their HEADs in the correct state
OK
```

**Comment by lunny** [comment]
Looks like your database has broken. Some comments come from 4 years ago. Maybe you have to manually clean the database. 
`SELECT count(*) FROM comment where issue_id NOT IN (SELECT id FROM issue)` will help you summarize how many broken comments are in your databases.

And after back up your database, you can delete them.

**Comment by wxiaoguang** [comment]
>  But after adding an issue entry to a repository, the issue got comments from another repository and organization!!

I guess it should be fixed by re-sync the issue number counter. I will try to find out the SQL from Gitea issue list

**Comment by wxiaoguang** [comment]
For the second problem:

* backup your database
* empty/truncate the `issue_index` table
* use the sql to re-sync the issue_index: https://github.com/go-gitea/gitea/issues/17070#issuecomment-921034548
* `` replace into issue_index (group_id, max_index) select repo_id, max(`index`) from issue group by repo_id; ``
* (the SQL provided was written for MySQL, it won't differ much for MSSQL)

**Comment by KroMignon** [comment]
> ooks like your database has broken. Some comments come from 4 years ago. Maybe you have to manually clean the database.
> `SELECT count(*) FROM comment where issue_id NOT IN (SELECT id FROM issue)` will help you summarize how many broken comments are in your databases.

This returns 72, but the comment table had only 31 entries!

**Comment by KroMignon** [comment]
> For the second problem (update: maybe not related ....)
> 
>     * backup your database
> 
>     * empty/truncate the `issue_index` table
> 
>     * use the sql to re-sync the issue_index: [Error 500 on new issue (not for all repositories) #17070 (comment)](https://github.com/go-gitea/gitea/issues/17070#issuecomment-921034548)
> 
>     * `` replace into issue_index (group_id, max_index) select repo_id, max(`index`) from issue group by repo_id; ``
> 
>     * (the SQL provided was written for MySQL, it won't differ much for MSSQL)
> 
> 
> If this fix doesn't work (update: after more thoughts, I guess it's not related ...), then I guess maybe some table's auto-increment IDs were reset somehow. Like lunny said, that's a database data corruption ....

It do not look like to problem is in the `issue_index` table:
```
SELECT  *  FROM issue_index order by group_id;

+----------+-----------+
| group_id | max_index |
+----------+-----------+
| 36       | 1         |
| 46       | 1         |
| 132      | 1         |
| 520      | 5         |
| 528      | 1         |
+----------+-----------+
```
and 
```
select repo_id, max([index]) as max_index from issue group by repo_id order by repo_id;

+---------+-----------+
| repo_id | max_index |
+---------+-----------+
| 36      | 1         |
| 46      | 1         |
| 132     | 1         |
| 520     | 5         |
| 528     | 1         |
+---------+-----------+
```

**Comment by KroMignon** [comment]
> That's impossible. Maybe they are two different databases.

You are right, I don't know what I've done... Maybe I am too tired!

So, if I understand you right, there are 72 entries in "comment" table which do not have a valid issue_id?

But why they are shown in the issues view?
I don't have any "valid" comment anyway.
All those comments was tests done about 4 or 5 years ago, while testing Gitea.

How can I cleanup my DB, to remove all comments (for any organization/repository) but keep the issue entries?

This way, we could start with an almost clean DB...  I hope!

**Comment by KroMignon** [comment]
@lunny @wxiaoguang 

I am a little bit lost with the Gitea DB schema, there are several things I don't understand:
* is the `comment` table only used to store comments for issues?
* as far as I can see, same `issue_id` could be possible for any repository for any organization. So how are comments linked to the right issue/repository/organization?

**Comment by KroMignon** [comment]
>  as far as I can see, same `issue_id` could be possible for any repository for any organization. So how are comments linked to the right issue/repository/organization?

Ok, I think I catch this, the issue_id is a link to `id` in `issue` table. So it should be unique!

**Comment by KroMignon** [comment]
Ok, I solve this by deleting all entries in `comment` table:
`delete  FROM comment where issue_id > 0 and created_unix < 1672527600`

As I don't have any valid comment for any issue which is prior to this year.
