### ISSUE TITLE
Glitch on Migrate From GitHub  screen (mirroring the repo)

### ISSUE THREAD

**Issue by Areso** [go-gitea/gitea#23472]
### Description

1. My browser is 110.0.1 Firefox (64 bit)
2. Gitea version is Version: 1.20.0+dev-165-gc492e8631
3. Official try instance. Path https://try.gitea.io/repo/migrate?service_type=2&org=&mirror=
4. Access token is provided (entered into the Access Token field via copypasting)
5. Actual Result: Checkboxes for Labels, Issues, PRs, Releases, Miltesones are still disabled.
Expected Result: After changing Access Token field Gitea should enable these checkboxes, thus they're should be enabled.

### Gitea Version

Version: 1.20.0+dev-165-gc492e8631

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

![image](https://user-images.githubusercontent.com/4927300/225019638-a5722827-e396-4fde-ac06-570ef47584a1.png)

### Git Version

n/d

### Operating System

n/d

### How are you running Gitea?

I don't. I use Gitea Demo site

### Database

None

**Comment by techknowlogick** [comment]
This is on purpose as you have "mirror" selected. Issue/etc.. mirroring are not (yet) possible.
