### ISSUE TITLE
Support Reverse Proxy Email

### ISSUE THREAD

**Issue by MTecknology** [go-gitea/gitea#2347]
- Gitea version (or commit ref): master
- Git version: 2.11.0
- Operating system: Debian
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

The option `REVERSE_PROXY_AUTHENTICATION_USER` option allows users to be created, which is great, but I noticed the email address tends to look something like this, `c8147db3-4a42-a6b3-8642-d7c33fc55365@localhost`. I'm not sure where that value comes from, but I'm pretty confident it's relatively useless.

When the proxy is providing authentication information, I imagine the user's email address is readily available to the proxy. In this case, it would be helpful if the option `REVERSE_PROXY_AUTHENTICATION_EMAIL` could be added so that the value can be correctly filled out during registration.

It'd also be nice if there were an option to automatically update the address if it changes.

**Comment by lafriks** [comment]
Other option would be to define email domain and have emails generated in form username@domain

**Comment by MTecknology** [comment]
We already have two domains that might be used and potentially more.

**Comment by MTecknology** [comment]
@lunny I'm surprised you reacted with the hooray emote when #2241 is my biggest blocker...
