### ISSUE TITLE
How to hide the version number of the home page

### ISSUE THREAD

**Issue by iAsuma** [go-gitea/gitea#23485]
### Description

![image](https://user-images.githubusercontent.com/33219490/225192642-18d5be63-db74-46dd-94f6-1af6fc2493aa.png)

### Gitea Version

1.17.3

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

docker gitea run 

### Database

MySQL

**Comment by lunny** [comment]
Custom template. https://docs.gitea.io/en-us/customizing-gitea/

**Comment by jolheiser** [comment]
Actually you can use `SHOW_FOOTER_VERSION` https://docs.gitea.io/en-us/config-cheat-sheet/#other-other

**Comment by iAsuma** [comment]
> Actually you can use `SHOW_FOOTER_VERSION` https://docs.gitea.io/en-us/config-cheat-sheet/#other-other

thanks

**Comment by iAsuma** [comment]
> Custom template. https://docs.gitea.io/en-us/customizing-gitea/

thanks
