### ISSUE TITLE
Default Dashboard context option

### ISSUE THREAD

**Issue by MattSG** [go-gitea/gitea#23497]
### Feature Description

User may be part of several organisations

The option to toggle a default within the Switch default context menu would be rather useful or a checkbox beside each to show repositories from those selected for example

**Comment by lunny** [comment]
I think this has been implemented.
<img width="380" alt="image" src="https://user-images.githubusercontent.com/81045/225303223-76ef818d-3ab5-4431-a476-fdf43fbc2c1b.png">
