### ISSUE TITLE
Miscellaneous files appear after compiling the source code

### ISSUE THREAD

**Issue by zjjhot** [go-gitea/gitea#23514]
### Description

Miscellaneous files appear after compiling the source code.

This problem may be caused by changing less to css.

![QQ图片20230316122034](https://user-images.githubusercontent.com/79889452/225513484-0d3536b3-bfea-417e-901c-a93410dce5fd.png)

### Gitea Version

1.20.0+dev-506-gc340f5045

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

windows

### Database

None

**Comment by wxiaoguang** [comment]
Comfirmed

```
$ TAGS="bindata sqlite sqlite_unlock_notify" make build
...
  asset 8b43027f47b20503057d.eot?v=4.7.0 162 KiB [emitted] [immutable] [from: node_modules/font-awesome/fonts/fontawesome-webfont.eot?v=4.7.0] (auxiliary name: index)
  asset c1e38fd9e0e74ba58f7a.svg?v=4.7.0 434 KiB [emitted] [immutable] [from: node_modules/font-awesome/fonts/fontawesome-webfont.svg?v=4.7.0] (auxiliary name: index)
```

**Comment by silverwind** [comment]
I suspect there come from PostCSS which is removed again in https://github.com/go-gitea/gitea/pull/23520. Please try with that PR.

**Comment by silverwind** [comment]
Fixed with https://github.com/go-gitea/gitea/pull/23520, these assets are no longer built with it:

https://drone.gitea.io/go-gitea/gitea/69886/1/11
