### ISSUE TITLE
github style pages

### ISSUE THREAD

**Issue by kolinfluence** [go-gitea/gitea#23516]
### Feature Description

github style pages

**Comment by JakobDev** [comment]
It can take a look at [Codeberg Pages](https://codeberg.org/Codeberg/pages-server)

**Comment by wxiaoguang** [comment]
Yup, Codeberg Pages is a good (maybe the only one at the moment?) solution.

There are also other similar feature requests like:

* #21100

But I guess `#21100` was closed by mistake, because `#16670` is for gist, not for pages.

Maybe it's good to keep this issue open?

**Comment by hiqsociety** [comment]
i'm asking for this to be a gitea feature.
is codeberg gitea?

**Comment by wxiaoguang** [comment]
If you want to deploy your own git & pages site, you could deploy Gitea first, then deploy Codeberg Pages to make Codeberg Pages use Gitea to provide "pages service".

**Comment by hiqsociety** [comment]
cant i just use codeberg directly?

**Comment by jolheiser** [comment]
I was almost sure we had an open issue for pages. The one I close referenced above asked for both gifts and pages, so I must have overlooked. 

We can keep this issue open or open a new one.

**Comment by wxiaoguang** [comment]
> We can keep this issue open or open a new one.

I think it's better to have a new one with "summary" tag to record "pages" related details.

**Comment by hiqsociety** [comment]
can i have built in pages is what i mean.
@wxiaoguang possible for this pr to be accepted?

**Comment by wxiaoguang** [comment]
Sorry, I haven't got your point.

> can i have built in pages is what i mean.

At the moment there is no builtin pages server.

> possible for this pr to be accepted?

Which PR do you refer? ps: I just helped to summarize the issues, I am not working on this, nor I can make decision.

**Comment by lunny** [comment]
Except it can resolve the possible security problem if all the pages are on the same site. If there are serval domains, then looks like it's not a good idea to put all the things in the same web port.

**Comment by wxiaoguang** [comment]
> Except it can resolve the possible security problem if all the pages are on the same site. If there are serval domains, then looks like it's not a good idea to put all the things in the same web port.

That's nearly impossible. All "pages-server" (including GitLab, GitHub), they all run on different domain.

If Gitea wants to support pages-server, end users must have a separate domain for pages.

**Comment by silverwind** [comment]
Would call the feature "Webhosting"

**Comment by 6543** [comment]
my opinion is here: https://github.com/go-gitea/gitea/issues/23521#issuecomment-1472372649

and I'd like to klose this in fafour of #23521 ?
