### ISSUE TITLE
How to break a mirror in gitea?

### ISSUE THREAD

**Issue by zfLQ2qx2** [go-gitea/gitea#2351]
If I have a mirror repo set up in gitea, and I want to break the mirror so that it no longer updates from source, how do I do that? I've tried setting the interval to 0 in the gui and clearing the address field, but I either can't save or it reverts to the previous values when I try to save.

**Comment by MTecknology** [comment]
Under the repository settings, in the danger zone, there is an option to "Convert To Regular Repository." Is this what you're after? Are you looking to temporarily suspend the cron task that runs all imports? Temporarily exclude one repository from regular checks? Something else?

**Comment by lafriks** [comment]
I think question is answered so I'm closing issue

**Comment by zfLQ2qx2** [comment]
@lafriks @MTecknology Apologies for the delayed response but this was the solution exactly. Thank you very much for pointing me in the right direction!
