### ISSUE TITLE
The menu in review comment page has layout problem

### ISSUE THREAD

**Issue by yp05327** [go-gitea/gitea#23517]
### Description

![image](https://user-images.githubusercontent.com/18380374/225550234-4fb5c0dc-43bb-4373-b1a3-2d6853315efb.png)

### Gitea Version

latest

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

build

### Database

None

**Comment by silverwind** [comment]
Should probably converted to use tippy.js.

**Comment by wxiaoguang** [comment]
I do not think that menu could be easily replace by tippy.

I guess changing the `z-index: 7` of `.diff-file-header.sticky-2nd-row` to `z-index: 1` is enough.

**Comment by wxiaoguang** [comment]
> I guess changing the `z-index: 7` of `.diff-file-header.sticky-2nd-row` to `z-index: 1` is enough.

Sorry .... it seems not working, more complex than I thought ....

**Comment by silverwind** [comment]
> I do not think that menu could be easily replaced by tippy.

I think the same dropdown in issue comments was already using tippy, but apparently not. Maybe I'll check out later to convert both these menus. tippy is the ideal solution for such overflow issues :)

**Comment by wxiaoguang** [comment]
I guess we can have a quick fix at the moment:  Fix review comment context menu clipped bug #23523

**Comment by silverwind** [comment]
> https://github.com/go-gitea/gitea/pull/22959 wants to render a wide CSV table.

Don't see why a `max-width` and `overflow-x: auto` shouldn't work. Scrollbars only on-demand.
