### ISSUE TITLE
[discussion] Gitea pages server (GitHub pages, web hosting, serving git repository contents as a site)

### ISSUE THREAD

**Issue by wxiaoguang** [go-gitea/gitea#23521]
Like GitHub pages, there are many feature requests for Gitea builtin pages service.

The initial issue is #302 , at that time (2016~2019) , the conclusion was that it's not on the roadmap.

Today, more and more people are asking about "Pages" feature, so I'd like to summary them, and maybe it's time to discuss a new conclusion.

Relate issues:

* #302
* #2208
* #3834
* #6163
* #9811
* #19129
* #23516

If Gitea wants to put this feature on its roadmap, it's a big feature, and it needs to be designed first, especially for security.

If this feautre is not on Gitea's roadmap, then I think it's better to provide a clear document about how to setup a pages service with production-level servers, eg: [Codeberg pages-server](https://codeberg.org/Codeberg/pages-server) , it's already mentioned in many issues, and it works well for Gitea.

**Comment by lunny** [comment]
There is also an interesting closed PR #9811 .

**Comment by lunny** [comment]
OK. Maybe we can have an `HTML` Package concept. And if a special domain could be bind, it will serve as a static server. Looks like an interesting thing.

**Comment by wxiaoguang** [comment]
> let the chosen Server Software (e.g. ngnix) do the rest.

That's also a good idea (especially for personal or small team usage), if the reverse-proxy servers could proxy the requests to Gitea's `raw` handlers to fetch contents. (I haven't tried but I guess it might be feasible)

**Comment by KN4CK3R** [comment]
I talked with @lunny and the generic package type could store and save pre-compiled HTML output. It may be necessary to create a new package type for that job to tweak the current ui or hide it from users. An action could then create the files and store them as a package which a proxy could serve with a different domain.

**Comment by lunny** [comment]
A dynamic rule could be configured from action to implement dynamic sub domain.

**Comment by 6543** [comment]
**I** am against add a build in pages server ... as I generalize the [Pages-Server](https://codeberg.org/Codeberg/pages-server), so anybody should be capable to setup it. It's also a single binary with good default settings, and the only thing that is not generic are the error pages, that show the codeberg logo at the moment. witch https://codeberg.org/Codeberg/pages-server/issues/199 should solve.

Just blow up gitea for no good reason is **bad**

**Comment by 6543** [comment]
as it's requested a lot I would just add this project directly in the feature-comparsion-sheet and document it well.

If you are afraid/dont like that it's tied to much to CB I'm also happy to maintain a fork that just switches the default settings to gitea and its logo ...

**Comment by silverwind** [comment]
Would call the feature "Web hosting", [Wikipedia](https://en.wikipedia.org/wiki/Comparison_of_source-code-hosting_facilities#Features) also calls it that.

**Comment by wxiaoguang** [comment]
I'm not sure whether the "reverse-proxy"-kind approach works, if it does, then it seems an easy way for personal usage or small team usage. If they don't care about security, they could even use the same domain (that's user's choice 😂)


Actually I also feel it's better to use production-level Pages-Server to provide pages service, instead of blowing up Gitea. I just saw many new issues about this proposal, so I opened this discussion issue (to help users with such requirements). I guess a document with some samples would help future users who need this feature.

**Comment by lunny** [comment]
> **I** am **against** add a build in pages server ... as I generalize the [Pages-Server](https://codeberg.org/Codeberg/pages-server),
> 
> so anybody should be capable to setup it. It's also a single binary with good default settings,
> 
> and the only thing that is not generic are the error pages, that show the codeberg logo at the moment. witch https://codeberg.org/Codeberg/pages-server/issues/199 should solve.
> 
> Just blow up gitea for no good reason is **bad**

Of course, that's why we closed so many request issues. For now, the possible answers of the requirement I think are two.
1) Use https://codeberg.org/Codeberg/pages-server
2) Use a reverse proxy server that redirects to the package URL of Gitea.

**Comment by 6543** [comment]
I'll create a pull to the docu :)
