### ISSUE TITLE
Allow configuring Gitea to act as a proxy for libravatar requests

### ISSUE THREAD

**Issue by strk** [go-gitea/gitea#23525]
### Feature Description

Right now enabling Libravatar allows registered users (RU) to receive requests from the browsers of the forge's users (FU) when those users  (FU) visit pages with the registered user (RU) avatar for the first time.

This is because Gitea delegates to users's browsers (FU) the operation of fetching those avatars.

By implementing a proxy in the forge itself we'd instead "masquerade" the forge users (FU) so that their information is not leaked. This would be at the expense of more load on the forge, so should be a server configuration.

**Comment by strk** [comment]
The rationale for this would be to make it less of a privacy concern for system administrators to enable the federated avatar service, see https://codeberg.org/Codeberg/Community/issues/48

**Comment by strk** [comment]
The alternative at the moment is to install a separate service: https://wiki.libravatar.org/running_your_own/

**Comment by wxiaoguang** [comment]
I do not think it's worth to make Gitea act as a proxy for libravatar requests. The reasons are:

1. Setting up a libravatar is quite complex, it also needs DNS setup (according to https://wiki.libravatar.org/running_your_own/).
2. Most end users do not really use libravatar. Large instances like Codeberg could have their own infrastructure to complete the complex libravatar proxy setup.
3. The Codeberg owner has stated that they are quite happy with their own-maintained Gitea forks, so they could implement it to fully satisfy their requirement.

So, no need to bloat Gitea's codebase.

**Comment by wxiaoguang** [comment]
Inactive for 2 weeks. Feel free to reopen if there is a feasible plan.
