### ISSUE TITLE
Not invited to the Matrix Chat

### ISSUE THREAD

**Issue by pree** [go-gitea/gitea#2352]
I just tried joining the Matrix-Chatroom but either getting `Forbidden` or `You're not invited to this Chatroom`.
How can I join the Chatroom ?

**Comment by strk** [comment]
Did you try logging in ?

**Comment by pree** [comment]
Yes I am logged in, with my own Synapse instance.

**Comment by jcgruenhage** [comment]
For some reason, the room was set to invite only. Could you try again now? @pree

**Comment by strk** [comment]
could have been some emergency setting in a spam storm ? I surely hadn't set the invite-only bit myself

**Comment by jcgruenhage** [comment]
It could be that I did that back then, but I think I only disabled guest access, because we did not have problems with spammers on matrix itself (iirc)

**Comment by pree** [comment]
@jcgruenhage yes it's working now, thanks o/
