### ISSUE TITLE
Add word break to long repo name in fork page

### ISSUE THREAD

**Issue by yp05327** [go-gitea/gitea#23535]
### Feature Description

![image](https://user-images.githubusercontent.com/18380374/225815433-ca41150c-ae57-4127-b385-d7d26f0eecbf.png)

**Comment by HesterG** [comment]
Looks like long filename also have the work break issue
<img width="1296" alt="截屏2023-03-17 13 19 45" src="https://user-images.githubusercontent.com/17645053/225819159-452f73b4-8f97-4151-8a4d-2a66d0ea15f3.png">

**Comment by yp05327** [comment]
Do you mean long file `path`?
I think you can create a new issue for this.

**Comment by HesterG** [comment]
I was meant to create a PR to fix them both. But if you are working on the fork long name one, i can fix only the long file name one.
