### ISSUE TITLE
not really a feature request but sort of. i would like to make the screen attached section to be private. only logged in users can view.

### ISSUE THREAD

**Issue by kolinfluence** [go-gitea/gitea#23559]
### Feature Description

not really a feature request but sort of. i would like to make the screen attached section to be private. only logged in users can view.

so it will be like a webpage! i dont even need to do github pages setup etc.

basically just edit the readme.md file and that'll be the webpage. need this coz
1. it's git backed
2. everyone signed in can edit
3. i dont need to use wordpress which is annoying.

does anyone know how to make this section "private" for non-logged in users? where in the code should i add the "
```
if (user_logged_in) { 
    then only show the directories etc.
}else{
   //dont show them the part i highlighted
}
```
**pls mention where and how to add the if statement! thx!**

![screen52](https://user-images.githubusercontent.com/104323920/226102242-c3b6f8a4-90ba-4e5c-a4ec-2b97164efee6.png)

**Comment by wxiaoguang** [comment]
Hiding something without a global design would cause problems in the end. It will mislead users to make them think that "anonymous users won't be able to clone or access other resources", however it isn't, it just "hides".

For personal usage, you could fine tune everything (eg: by custom build, or custom templates), but I guess it couldn't be a general feature/proposal to be accepted for all users.

----

If you want to use "custom templates", you can take a look at "templates/repo/home.tmpl" and "templates/repo/view_list.tmpl", hide everything except `{{template "repo/view_file" .}}`.

**Comment by ultperf** [comment]
@wxiaoguang how to do if user logged in?
{{if User_Logined?? }}

**Comment by wxiaoguang** [comment]
`{{if .IsSigned}}`

**Comment by ultperf** [comment]
@silverwind do u know where? actually i tried wrapping If IsSigned, doesnt work in view.tmpl file

**Comment by silverwind** [comment]
This is not a support channel, ask in Discord.
