### ISSUE TITLE
404 when creating new repo

### ISSUE THREAD

**Issue by MaT1g3R** [go-gitea/gitea#2357]
- Gitea version (or commit ref): 7455604
- Git version: 2.11.0
- Operating system: Debian GNU/Linux 9.1 (stretch)
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at 'https://try.gitea.io/:
  - [ ] Yes (provide example URL) 
  - [ ] No
  - [x] Not relevant

## Description
A '>' character is inserted after the url when clicking on the create repo button on the web UI.

## Screenshots
![screenshot_20170822_195534](https://user-images.githubusercontent.com/15258494/29592739-fffaa4cc-8773-11e7-8b51-1f8c5f36ccc0.png)

![screenshot_20170822_194350](https://user-images.githubusercontent.com/15258494/29592498-7e96d17c-8772-11e7-905f-bc9421e8da57.png)

**Comment by lunny** [comment]
caused by https://github.com/go-gitea/gitea/pull/2317
