### ISSUE TITLE
[actions] Skipped jobs are displayed as failed

### ISSUE THREAD

**Issue by denyskon** [go-gitea/gitea#23599]
### Description

I have a workflow file with three different jobs. The workflow is triggered by `push` and `issue_comment` events, and an if statement in the job definition decides which of the jobs gets executed by the `github.event_name` variable.

In the actions list (`/actions?workflow=&state=closed`) the action run is being displayed as successful.

![grafik](https://user-images.githubusercontent.com/47871822/226448754-eb5d9410-8f4b-4bec-a80d-4e29466ec5cb.png)

When opening the log view, the skipped job is being displayed correctly, but the steps are being displayed as failed.

![grafik](https://user-images.githubusercontent.com/47871822/226448966-6403fc37-b563-4144-b32b-248c1ad62017.png)

In the code view, the action is being displayed as failed, and in the tooltip, the skipped job is being displayed as failed.

![grafik](https://user-images.githubusercontent.com/47871822/226449614-3d4d386f-c373-459e-9cdf-ffa65d381fec.png)

### Gitea Version

1.19.0

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

Using the official docker image

### Database

SQLite

**Comment by a1012112796** [comment]
that's because there are only three optional commit status now: `success`, `failure` and `pending`.

**Comment by yardenshoham** [comment]
I think GitHub keeps it on "pending" https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks

We could also add a new status? "skipped"

**Comment by a1012112796** [comment]
Hmm,  I think whether `skipped` means `failed` should be optional for each repo.

**Comment by denyskon** [comment]
GitHub also seems to have `neutral` for that, at least that's what I have seen a few times.....
