### ISSUE TITLE
Maxsize limitation setting for uploading file

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#236]
Sometimes, we have to limit the max file size to upload. Then we can set it on repo settings.

**Comment by jhasse** [comment]
Isn't this possible via the webserver, e.g. nginx, already?

**Comment by tboerger** [comment]
Various people aren't using a Web server like that

**Comment by bkcsoft** [comment]
If this is implemented, we should add a note near the setting (if running behind a proxy) that says 
```
You seem to be running behind a proxy.
Please keep in mind that you are still limited
by the settings of the proxy.

See links below for changing the appropriate settings in the proxy.
Nginx: <link>
Apache: <link>
[more proxies...]
```
Or something similar :)

**Comment by krombel** [comment]
Isn't that already implemented on [this place](https://github.com/go-gitea/gitea/blob/7781e8c/modules/setting/setting.go#L218)?
Or which are the places which need to be Limited?

**Comment by lunny** [comment]
@krombel I think you are right.
