### ISSUE TITLE
After display language change from English > Russian, could not change in back from Russian > English

### ISSUE THREAD

**Issue by sgabenov** [go-gitea/gitea#23610]
### Description

I have changed the display language in bottom of the page to Russian. After i tried to revert it back to English, but the display always stays the same on Russian. In preferencies > appearance it is set up to use English. The to change language in this menu also do nothing. I tried to delete cache and cookies from the Chrome data, still the same behavior. 
But when using Incognito mode this switching is working normally.

### Gitea Version

1.19.0

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

Docker container

### Database

None

**Comment by wxiaoguang** [comment]
If you can't reproduce the problem on try.gitea.io, I would guess there might be something wrong with your browser cookie "lang"?

**Comment by KazzmanK** [comment]
@sgabenov , check in Chrome network if "Set-Cookie lang" success or not. There may be a number of network specific issues like http-https priority.

**Comment by sgabenov** [comment]
The issue was Chrome related, full clear of all cookies and cache fixed the behavior after all
