### ISSUE TITLE
Add option to list public ssh keys

### ISSUE THREAD

**Issue by cupcakearmy** [go-gitea/gitea#23618]
### Feature Description

It would be cool to have an option to list ssh keys as unauthenticated user.

**Motivation**

This makes it very handy to setup servers / remote machines.
Github has an endpoint for that (`https://github.com/<username>.keys`, in my case: https://github.com/cupcakearmy.keys).
They also offer a json verion of it `https://api.github.com/users/cupcakearmy/keys`.

In ubuntu for example there is the command `ssh-import-id` that also installs `ssh-import-id-gh` to automatically add them to your `~/.ssh/authorized_keys`. 

Otherwise you can [manually](https://askubuntu.com/a/1145195):

```
wget -O - https://github.com/<username>.keys >> /home/myuser/.ssh/authorized_keys
```

**Current state in Gitea**

In Gitea there is such endpoint [`/users/{username}/keys`](https://try.gitea.io/api/swagger#/user/userListKeys), however it's behind authentication. In addition it returns a json object.

**Feature Request**

It would be nice to have an endpoint which you can publicly query and it returns your public keys in the same format required by `authorized_keys`.

Thanks for all the AMAZING work! If I can help let me know ❤️

**Comment by silverwind** [comment]
> https://github.com/<username>.keys

This is [already implemented](https://try.gitea.io/silverwind.keys).

**Comment by cupcakearmy** [comment]
I am stupid xD Thanks and sorry for wasting your time :)

**Comment by silverwind** [comment]
Also, API [seems there as well](https://try.gitea.io/api/swagger#/user/userListKeys).
