### ISSUE TITLE
Some problems of dropdown menus

### ISSUE THREAD

**Issue by yp05327** [go-gitea/gitea#23625]
### Description

Can't see `Newest` option: (windows height< 589px)
(gitea.com)
![image](https://user-images.githubusercontent.com/18380374/226785422-e100f2dd-9c07-4300-8ae5-b3dece7784ee.png)
(try.gitea.io)
![image](https://user-images.githubusercontent.com/18380374/226785581-7e5a5c1a-31c3-4344-9060-34b23924b722.png)

If project names are too long, smart phone user can not see all options clearly.
![image](https://user-images.githubusercontent.com/18380374/226786628-e9eebdc8-a327-45e5-aef2-16a7223bbc42.png)

### Gitea Version

1.20.0+dev-171-gb2c1c17f3

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

gitea.com

### Database

None

**Comment by wxiaoguang** [comment]
The first problem can be fixed by https://github.com/go-gitea/gitea/pull/23626/files#diff-5132704e0ee1cedcd269ea7d54a004cf2c98206e3354f60fe5be02527c0bc982R12-R15


The second problem is also relate to width&word-break .... it may need more fine tunes.

**Comment by HesterG** [comment]
For the second one, did some check and I found there is a div called `issue-item-icons-right`, which is empty and took up space. Not sure what this is originally for.
<img width="1126" alt="截屏2023-03-22 18 17 34" src="https://user-images.githubusercontent.com/17645053/226872892-4e691cae-64d9-4886-af5b-2cc215d05427.png">

**Comment by wxiaoguang** [comment]
I guess these two problems have been fixed?

**Comment by silverwind** [comment]
> For the second one, did some check and I found there is a div called `issue-item-icons-right` in the issue list, which is empty and took up space. Not sure what this is originally for. <img alt="截屏2023-03-22 18 17 34" width="1126" src="https://user-images.githubusercontent.com/17645053/226872892-4e691cae-64d9-4886-af5b-2cc215d05427.png">
> 
> Update: Find in [issuelist.tmpl](https://github.com/go-gitea/gitea/blob/1d35fa0e784dffcadacb2322a3d7ac3ec2ff89b2/templates/shared/issuelist.tmpl#L146-L167), might need to adjust the conditions' positions

It's reserved space for assignee, replies and i think project. But I could see us collapsing that space on mobile view (on desktop, it's better to visually reserve the space).

**Comment by wxiaoguang** [comment]
I guess  #23653 and #23857 could have fixed the problems?

**Comment by yp05327** [comment]
It seems that this issue has been fixed.
