### ISSUE TITLE
Add a few rows to Gitea feature comparison

### ISSUE THREAD

**Issue by Timmmm** [go-gitea/gitea#23637]
### Feature Description

[This page](https://docs.gitea.io/en-us/comparison/) is really great but it is missing a few rows that I would have found useful:

1. "Multiple reviewers" - can you set multiple reviewers for a MR/PR?
2. "Require review" - can you have MR/PRs *require* review?
3. "Merge queue" - (AKA "merge trains" in Gitlab).

All three features are not in Gitlab CE but they are in Gitlab Premium. I believe Github supports all three. Here is how I think it should be:

```
| Feature                                         | Gitea                                              | Gogs | GitHub EE | GitLab CE | GitLab EE | BitBucket | RhodeCode CE |
| ----------------------------------------------- | -------------------------------------------------- | ---- | --------- | --------- | --------- | --------- | ------------ |
| Pull/Merge require approval                     | ✘                                                  | ✘    | ✓         | ✘        | ✓         | ✓         | ✓            |
| Pull/Merge multiple reviewers                   | ✓                                                  | ✓    | ✓         | ✘        | ✓         | ✓         | ✓            |
| Merge queues                                    | ✘                                                  | ✘    | ✓         | ✘        | ✓         | ✘         | ✘            |
```

Not 100% sure about the RhodeCode one.

**Comment by jolheiser** [comment]
Feel free to open a PR if you're comfortable with it, the page in question is https://github.com/go-gitea/gitea/blob/main/docs/content/doc/features/comparison.en-us.md

One nit, you can require PR approval in Gitea via protected branches.
