### ISSUE TITLE
Gitea: Internal Server Error

### ISSUE THREAD

**Issue by hiifong** [go-gitea/gitea#23636]
### Description

After I start a gitea instance with systemd, and then another gitea instance with the ./gitea web -p 3333 command, Ctrl+C

### Gitea Version

v1.20+

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots
![image](https://user-images.githubusercontent.com/89133723/226920062-7059ae60-4a22-4338-8584-65d06a881dcc.png)
![image](https://user-images.githubusercontent.com/89133723/226916303-99eeeb4e-4a29-450d-9843-c4cef489ff97.png)
![image](https://user-images.githubusercontent.com/89133723/226916762-65546d57-7743-43c0-93b5-4a984a8e4b13.png)
![image](https://user-images.githubusercontent.com/89133723/226917038-df19f3e6-09f2-4d1c-b905-3628dc616ff5.png)

### How are you running Gitea?

./gitea web

### Database

None

**Comment by lunny** [comment]
We needs more logs

**Comment by hiifong** [comment]
> We needs more logs

Seems like there are no more error logs

**Comment by lunny** [comment]
Or you can change RUN_MODE to dev and try ssh -T again.

**Comment by hiifong** [comment]
> Or you can change RUN_MODE to dev and try ssh -T again.

![image](https://user-images.githubusercontent.com/89133723/227084481-0d362a46-5467-4828-8f4c-286d2af20357.png)

**Comment by hiifong** [comment]
I can't solve it by replacing the gitea binary file

**Comment by wxiaoguang** [comment]
> >  Or you can change RUN_MODE to dev and try ssh -T again.
>
>  not found any error log: `<html>...`

You are accessing wrong port. The port you are accessing is a HTTPS server, not SSH server.

**Comment by wxiaoguang** [comment]
> After I start a gitea instance with systemd, and then another gitea instance with the ./gitea web -p 3333 command, Ctrl+C

And I don't see why you should run two different Gitea instances at the same time with the same config.

**Comment by hiifong** [comment]
> > After I start a gitea instance with systemd, and then another gitea instance with the ./gitea web -p 3333 command, Ctrl+C
> 
> And I don't see why you should run two different Gitea instances at the same time with the same config.

it was purely a mistake

**Comment by wxiaoguang** [comment]
I can not understand your problem.

What's your problem?

* Start Gitea by systemd, then start another manually, then stop the manually started one, then the systemd one doesn't work with SSH clone?  
* Why are you testing the SSH on a HTTPS port?

**Comment by hiifong** [comment]
> I can not understand your problem.
> 
> What's your problem?
> 
> * Start Gitea by systemd, then start another manually, then stop the manually started one, then the systemd one doesn't work with SSH clone?
> * Why are you testing the SSH on a HTTPS port?

step 1：use systemd run a gitea instance
step 2: `./gitea web -p 3333`
step 3: Ctrl + C
step 4: can't push code to gitea and git clone

**Comment by wxiaoguang** [comment]
Restart the systemd service will resolve the problem.

**Comment by hiifong** [comment]
> Restart the systemd service will resolve the problem.

no

**Comment by hiifong** [comment]
![image](https://user-images.githubusercontent.com/89133723/227431856-90666437-9c7a-4c58-a50a-5174b0c6bc35.png)

**Comment by hiifong** [comment]
![image](https://user-images.githubusercontent.com/89133723/227432004-f70097c7-0452-4cf5-a879-b09039d37762.png)

**Comment by wxiaoguang** [comment]
Try to:

1. Re-sync the git hook on the admin page
2. Enable Dev mode ,and try to : `ssh git-user@your-server git-receive-pack your-org/your-repo.git` to see what's the output. Do not use it on the HTTPS port.

**Comment by hiifong** [comment]
> 

![image](https://user-images.githubusercontent.com/89133723/227433484-c48ce23a-707e-45e6-9f6a-61f0953414ec.png)

**Comment by wxiaoguang** [comment]
Isn't it clear enough .........

**Comment by hiifong** [comment]
> Isn't it clear enough .........
> 
> Your LOCAL_ROOT_URL is wrong.
> 
> Fix the port

thank you，delete `LOCAL_ROOT_URL` can resolve the problem.

**Comment by hiifong** [comment]
I remember that I did not configure `LOCAL_ROOT_URL`

**Comment by wxiaoguang** [comment]
If there is an issue, please describe all the details clearly and provide enough clues. And it's always better to share texts than images.

**Comment by hiifong** [comment]
> If there is an issue, please describe all the details clearly and provide enough clues. And it's always better to share console texts than images.

get it

**Comment by hiifong** [comment]
thank you very much
