### ISSUE TITLE
Provide a programmable way to register a new action runner

### ISSUE THREAD

**Issue by yardenshoham** [go-gitea/gitea#23643]
### Feature Description

I wish there was an API endpoint I could query to retrieve a token I could register a new runner with. Currently, the only way to do this is to go to the web UI and copy the token from the page.

**Comment by wolfogre** [comment]
I remember I have discussed it with Lunny privately before, and the consensus is providing reusable token to register multiple runners, or you still need an auth token to use API.

Reusable tokens are feasible both in design and technology, you can even do this by modifying the status of tokens in database manually.

**Comment by wolfogre** [comment]
To be clear, I have no objection to having API to manage runners like listing, registering and removing.
