### ISSUE TITLE
File tree in PR  shows only 1 file

### ISSUE THREAD

**Issue by MartenH** [go-gitea/gitea#23641]
### Description

The file tree in a PR only shows the first file, not the entire tree. like so:
![image](https://user-images.githubusercontent.com/1034863/227001516-cb96bdb0-c78a-4090-a799-ece43174ee24.png)

Url to try:
https://try.gitea.io/MartenH/Bar/pulls/1/files

I'm really suck at CSS but figured out if I add the the lines:

```
<style>
#diff-file-tree {
    height: unset;	
}
</style>
```

to:
$GITEA_CUSTOM/templates/custom/header.tmpl

it seems to work just fine. 

### Gitea Version

1.19.0

### Can you reproduce the bug on the Gitea demo site?

Yes

### Git Version

On try.gitea.io

### Operating System

On try.gitea.io

### How are you running Gitea?

On try.gitea.io

### Database

None

**Comment by wxiaoguang** [comment]
You can get 1.19 latest from https://dl.gitea.com/gitea/1.19/ , or docker gitea:1.19-dev

These contain the fix.
