### ISSUE TITLE
404 when browser tag tree

### ISSUE THREAD

**Issue by zhsj** [go-gitea/gitea#2364]
- Gitea version (or commit ref): 8aadf79
- Git version: 
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes https://try.gitea.io/zhsj-pkg/packer/src/upstream/1.0.2+dfsg
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

I can't browser the git tree, maybe caused by the tag contains slash?

**Comment by ethantkoenig** [comment]
I believe the problem is that this repo also has a branch named `upstream`. When the `RepoRef(..)` handler sees `src/upstream/1.0.2+dfsg`, it thinks you're asking for the `1.0.2+dfsg` tree-path in the `upstream` branch.

Working on a fix

**Comment by ethantkoenig** [comment]
I think we'll need to change our URL schemes, for the following reason:

Suppose I have a repo with a file `foo`, a branch `bar`, and a tag `bar/foo`. If I request `.../src/bar/foo` there is no way to tell whether I want to view the `foo` file on branch `bar`, or I if want to view the root directory for tag `bar/foo`.
