### ISSUE TITLE
JavaScript error: Uncaught TypeError: Cannot read properties of undefined (reading 'length') (https://xxx.xx/assets/js/index.js?v=1.20.0~dev-240-gd4f35bd681 @ 37:60918). Open browser console to see more details.

### ISSUE THREAD

**Issue by hiifong** [go-gitea/gitea#23657]
### Description

When i click on the authenticate ssh button, this js error is thrown

I can reproduce the bug on the gitea.com and try.gitea.io

### Gitea Version

v1.20+

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

![image](https://user-images.githubusercontent.com/89133723/227207949-9c0d4060-eccc-448c-a155-c4224df83437.png)
![image](https://user-images.githubusercontent.com/89133723/227210253-6f743391-01e1-4352-be4e-b373df0f88fd.png)

### How are you running Gitea?

./gitea web

### Database

None

**Comment by wxiaoguang** [comment]
Incorrect copy-paste code by #17743 , and it triggers a bug.

**Comment by wxiaoguang** [comment]
Will be fixed by #23660

**Comment by hiifong** [comment]
> Will be fixed by #23660

Thank you
