### ISSUE TITLE
PR File list visual bug

### ISSUE THREAD

**Issue by watsom27** [go-gitea/gitea#23667]
### Description

When viewing PRs, the list of files to the left is now very small and you have to scroll no matter how many files there are

![image](https://user-images.githubusercontent.com/68954833/227328884-133a75ca-8c40-4de2-8c0e-54107fed6022.png)

Example PR on demo site: https://try.gitea.io/wxiaoguang/test/pulls/27/files (Just one i found, it seems to be on every PR)

### Gitea Version

1.19.0

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

![image](https://user-images.githubusercontent.com/68954833/227328884-133a75ca-8c40-4de2-8c0e-54107fed6022.png)

### How are you running Gitea?

ECS Linux instance with RDS MySql database

### Database

MySQL

**Comment by jolheiser** [comment]
More specifically, the linked PR will fix it in `1.19.x`. This still appears on try because the fix isn't in `main` yet, but will be once https://github.com/go-gitea/gitea/pull/23553 is merged.

**Comment by watsom27** [comment]
Sweet, thanks. I spent ages looking for a duplicate but knew as soon as i opened an issue someone would know where it was :D 

Thanks
