### ISSUE TITLE
Closed button's title will cross over background in user dashboard when using some languages

### ISSUE THREAD

**Issue by yp05327** [go-gitea/gitea#23673]
### Description

In english, `closed` is correct
![image](https://user-images.githubusercontent.com/18380374/227398621-a5a3706f-331d-46d2-86b1-e00f6aa08e9d.png)
But in some languages, `closed` is incorrect(randomly tested some one, not all of them):
![image](https://user-images.githubusercontent.com/18380374/227398605-cbef2d83-068b-435c-b98e-4d180a7c3bfe.png)
![image](https://user-images.githubusercontent.com/18380374/227398695-13e83564-b7d0-4212-aabc-0bef6f96f82e.png)
![image](https://user-images.githubusercontent.com/18380374/227399064-b9e82d9f-78e3-4102-9fab-9b802de7c216.png)

ps: tested window width = 640px

### Gitea Version

latest

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

build

### Database

None

**Comment by yp05327** [comment]
It seems that in the last pic, the count numbers also have a problem.
Language: ![image](https://user-images.githubusercontent.com/18380374/227399728-579e3e6e-63ad-4586-85ac-c049fe477103.png)

**Comment by Zettat123** [comment]
> the count numbers also have a problem

I think it should be a correct number in Arabic. 😄 
<img src="https://user-images.githubusercontent.com/15528715/227444709-7c20d30c-cdc0-4e56-815c-b305d154b80b.png" width="480px" />
