### ISSUE TITLE
Add badge for Gitea Actions to display result in README.md

### ISSUE THREAD

**Issue by lolo32** [go-gitea/gitea#23688]
### Feature Description

Like it exists on GitHub or other CI, it could be interesting to add a SVG badge to integrate into markdown in example.

The documentation to use it on GitHub could be found https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/adding-a-workflow-status-badge

An URL like `https://<GITEA_INSTANCE>/<OWNER>/<REPOSITORY>/actions/workflows/<WORKFLOW_FILE>/badge.svg` with:
* `GITEA_INSTANCE` the domain/url of the Gate server
* `OWNER` the project owner/organisation
* `REPOSITORY` the repository name
* `WORLFLOW_FILE` the filename of the action that trigged the build, and so, the result of the build

**Comment by belliash** [comment]
Bump
