### ISSUE TITLE
Incorrect line number display of process logs in actions

### ISSUE THREAD

**Issue by yp05327** [go-gitea/gitea#23680]
### Description

https://gitea.com/yp05327/testrepo/actions/runs/14
![image](https://user-images.githubusercontent.com/18380374/227449052-d14bc14b-97e7-49c6-852f-629b1aa5e9dd.png)

### Gitea Version

1.20.0+dev-251-g9f39def99

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

gitea.com

### Database

None

**Comment by yp05327** [comment]
It seems that the process state icon's location is also strange.
![image](https://user-images.githubusercontent.com/18380374/227450917-b165d47d-5796-4f5a-a08f-1972a634b94d.png)

**Comment by wxiaoguang** [comment]
I guess #23820 could help (I haven't tried). Could you take a look? Thank you.

**Comment by silverwind** [comment]
> Gitea assembles the content, only renders the last "Reading...100%\n".

Also prefer this if line deletions can be reliably detected and removed.

**Comment by yp05327** [comment]
> I think https://github.com/go-gitea/gitea/pull/23789 has fixed that alignment.

Yes, it fixed in #23789

**Comment by wxiaoguang** [comment]
Wait, keep it open.

The key problem hasn't been fixed.  #23789 only improves some alignments.
