### ISSUE TITLE
Incorrect finish time in action

### ISSUE THREAD

**Issue by yp05327** [go-gitea/gitea#23681]
### Description

https://gitea.com/yp05327/testrepo/actions/runs/22
![image](https://user-images.githubusercontent.com/18380374/227451820-266bed23-31d8-4626-8c39-f83f3adc3a76.png)

### Gitea Version

1.20.0+dev-251-g9f39def99

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

gitea.com

### Database

None

**Comment by yp05327** [comment]
`step.stoped` is a negative number.
Im working on this issue.

**Comment by wolfogre** [comment]
It should be fixed by https://gitea.com/gitea/act_runner/pulls/41

Please upgrade your act runner.
