### ISSUE TITLE
Invalid char in SQL query

### ISSUE THREAD

**Issue by CommanderRoot** [go-gitea/gitea#2369]
https://github.com/go-gitea/gitea/blob/64b706884635bcac31710d878bbb5e1b2d96ac0c/models/repo_list.go#L158

`"access"` is not valid in a sql query, it should be  \`access\` instead. This error causes 500 Internal Server errors:

![grafik](https://user-images.githubusercontent.com/4395417/29620583-96502bc2-881e-11e7-925a-4bf2487700d7.png)

**Comment by lunny** [comment]
fixed by https://github.com/go-gitea/gitea/pull/2361

**Comment by daviian** [comment]
@lunny I don't think it is fixed. The file `models/repo_list.go` mentioned here is different then `models/action.go` from #2361 .

**Comment by lunny** [comment]
#2367 will fix this.
