### ISSUE TITLE
RSS feeds still active after setting ENABLE_FEED = false

### ISSUE THREAD

**Issue by belzecue** [go-gitea/gitea#23697]
### Description

Gitea cheat sheet says RSS feeds can be switched off in the [other] section:

> Other (other)
> ENABLE_FEED: true: Enable/Disable RSS/Atom feed.

However,  

I added this to my app.ini:

> [other]
> ENABLE_FEED = false

then restarted Gitea, and I can still access RSS feeds, e.g. at:

> https://myserver.com/myorg/myrepo.rss

I also tested in a Chrome private session, logging in anew, to ensure this wasn't a cache issue.

I can't find any documentation around ENABLE_FEED other than how to set it.  I would understand if "ENABLE_FEED = false" means RSS is disabled except for the user's own accessible repos, i.e. RSS is ALWAYS enabled for the user's artifacts.  But I see no indication of that.  The intention of ENABLE_FEED seems to be to enable/disable the RSS feature globally.

NOTE: "Can you repro on Gitea demo site" - N/A obviously, not having access to switch it off in app.ini, but here's an example of an RSS feed with ENABLE_FEED = true

> https://try.gitea.io/owo/vaultwarden.rss

No log attached, as this should be very simple to repro.  If setting "ENABLE_FEED = false" works for issue readers, please say so in comments.

Here is my full app.ini:

> APP_NAME = Gitea
> RUN_MODE = prod
> RUN_USER = git
> 
> [repository]
> ROOT = /data/git/repositories
> DEFAULT_PRIVATE = private
> DEFAULT_PUSH_CREATE_PRIVATE = true
> 
> [repository.local]
> LOCAL_COPY_PATH = /data/gitea/tmp/local-repo
> 
> [repository.upload]
> TEMP_PATH = /data/gitea/uploads
> 
> [server]
> PROTOCOL  = https
> HTTP_PORT = 3000
> CERT_FILE = /data/gitea/conf/cert.pem
> KEY_FILE  = /data/gitea/conf/privkey.pem
> ROOT_URL  = https://[redacted].cloudapp.azure.com/
> DISABLE_SSH = true
> 
> [database]
> PATH     = /data/gitea/gitea.db
> DB_TYPE  = sqlite3
> HOST     = localhost:3306
> NAME     = gitea
> USER     = root
> PASSWD   =
> LOG_SQL  = false
> SCHEMA   =
> SSL_MODE = disable
> CHARSET  = utf8
> 
> [indexer]
> ISSUE_INDEXER_PATH = /data/gitea/indexers/issues.bleve
> 
> [session]
> PROVIDER_CONFIG = /data/gitea/sessions
> PROVIDER        = file
> 
> [picture]
> AVATAR_UPLOAD_PATH            = /data/gitea/avatars
> REPOSITORY_AVATAR_UPLOAD_PATH = /data/gitea/repo-avatars
> 
> [attachment]
> PATH = /data/gitea/attachments
> 
> [log]
> MODE      = console
> LEVEL     = Error
> ROUTER    = console
> ROOT_PATH = /data/gitea/log
> 
> [security]
> INSTALL_LOCK                  = true
> SECRET_KEY                    =
> REVERSE_PROXY_LIMIT           = 1
> REVERSE_PROXY_TRUSTED_PROXIES = *
> INTERNAL_TOKEN                = [redacted]
> PASSWORD_HASH_ALGO            = pbkdf2$50000$50
> LOGIN_REMEMBER_DAYS           = 30
> 
> [service]
> DISABLE_REGISTRATION              = true
> REQUIRE_SIGNIN_VIEW               = false
> REGISTER_EMAIL_CONFIRM            = false
> ENABLE_NOTIFY_MAIL                = false
> ALLOW_ONLY_EXTERNAL_REGISTRATION  = false
> ENABLE_CAPTCHA                    = false
> DEFAULT_KEEP_EMAIL_PRIVATE        = false
> DEFAULT_ALLOW_CREATE_ORGANIZATION = true
> DEFAULT_ENABLE_TIMETRACKING       = true
> NO_REPLY_ADDRESS                  = noreply.localhost
> 
> [lfs]
> PATH = /data/git/lfs
> 
> [mailer]
> ENABLED = false
> 
> [openid]
> ENABLE_OPENID_SIGNIN = false
> ENABLE_OPENID_SIGNUP = false
> 
> [repository.pull-request]
> DEFAULT_MERGE_STYLE = merge
> 
> [repository.signing]
> DEFAULT_TRUST_MODEL = committer
> 
> [other]
> ENABLE_FEED = false

### Gitea Version

1.18.5 built with GNU Make 4.3, go1.19.6 : bindata, timetzdata, sqlite, sqlite_unlock_notify

### Can you reproduce the bug on the Gitea demo site?

Yes

### Git Version

2.36.5, Wire Protocol Version 2 Enabled

### Operating System

Ubuntu 22.04

### How are you running Gitea?

Docker.
sudo docker-compose up -d

### Database

SQLite

**Comment by wxiaoguang** [comment]
This feature is only in 1.19

* https://github.com/go-gitea/gitea/pull/21622


cc @lunny @techknowlogick , call for Versioned Document, one more case today.

**Comment by lunny** [comment]
> 

Why do you think it's only in 1.19? That PR merged into the `main` branch. So v1.20 will also include this feature.

**Comment by wxiaoguang** [comment]
> Why do you think it's only in 1.19? That PR merged into the `main` branch. So v1.20 will also include this feature.

Hmm, I mean "after". But the user is using 1.18
