### ISSUE TITLE
Push Docker image to Gitea Registry

### ISSUE THREAD

**Issue by ghnp5** [go-gitea/gitea#23708]
Hey

I'm really confused how to get my first Docker image pushed to the Gitea Registry.

I've logged in, and it logged in successfully.

My Gitea instance is on Docker, under a reverse proxy (nginx), under a subpath (e.g. "/gitea/").

In the `app.ini`,
```
SSH_DOMAIN       = gitea.mydomain.win
ROOT_URL         = https://gitea.mydomain.win/gitea/
DOMAIN           = gitea.mydomain.win
```

I've gone ahead anyway, and added a second `/v2/` location in Nginx:

```
	map $upstream_http_docker_distribution_api_version $docker_distribution_api_version {
		'' 'registry/2.0';
	}
...

		location /v2/ {
			client_max_body_size 0;
			chunked_transfer_encoding on;

			add_header 'Docker-Distribution-Api-Version' $docker_distribution_api_version always;

			proxy_pass                          http://127.0.0.1:9000/;
			proxy_set_header  Host              $http_host;
			proxy_set_header  X-Real-IP         $remote_addr;
			proxy_set_header  X-Forwarded-For   $proxy_add_x_forwarded_for;
			proxy_set_header  X-Forwarded-Proto $scheme;
			proxy_read_timeout                  900;

			proxy_buffers 4 128k;
		}
```

On my Gitea instance, I have an organization, where my user is an Owner.

The organization is called, e.g., "MyOrg".
It has a repo called, e.g., "actions".

So, I've tried:

```
docker tag actions-rsync-ssh gitea.mydomain.win/myorg/actions/rsync-ssh
docker push gitea.mydomain.win/myorg/actions/rsync-ssh:latest
```

("myorg" instead of "MyOrg", because Docker requires it to be lowercase, but I confirm Gitea URLs are case insensitive anyway, so that should be fine)

But I'm always getting this:

> error parsing HTTP 404 response body: invalid character 'N' looking for beginning of value: "Not found.\n"

Access logs show the following:

> "GET /v2/ HTTP/1.1" 200 13843 "-" "[user agent here]" "-"
> "POST /v2/myorg/actions/rsync-ssh/blobs/uploads/ HTTP/1.1" 404 11 "-" "[user agent here]" "-"
> "HEAD /v2/myorg/actions/rsync-ssh/blobs/sha256:[big-hash] HTTP/1.1" 404 0 "-" "[user agent here]" "-"
> "POST /v2/myorg/actions/rsync-ssh/blobs/uploads/ HTTP/1.1" 404 11 "-" "[user agent here]" "-"

Any ideas why?

Also, do packages need to be associated to a repository, e.g. do I need "actions/" in it, or could it just be, like, "myorg/rsync-ssh" ?

Thank you very much!

**Comment by ghnp5** [comment]
Alright... got it working!

		location /v2/ {
			rewrite "/(.*)" /gitea/$1 last;
		}

		location /gitea/v2/ {
			...
			proxy_pass                          http://127.0.0.1:1234/v2/;

**Comment by wxiaoguang** [comment]
That's a hard restriction of Docker, but not Gitea.

Docker requires that the "/v2/" path must be on the root of the site ....

**Comment by ghnp5** [comment]
That's ok, thank you. This issue can be closed, since I already found a workaround for it (as per my reply above).

The issue is that I use a sub-path for Gitea, and that complicates a lot of things! :)

**Comment by mmBesar** [comment]
@ghnp5 
Would you, please share your Full Nginx configs! It might help with my problem here: #24042.
Thanks.

**Comment by ghnp5** [comment]
@mmBesar - my nginx config fix above is mostly needed because I have Gitea under a subpath (/gitea/)

In your case, you're getting a "405 Not Allowed", which seems to be a different issue.


Maybe replace this:

`proxy_pass       $forward_scheme://$server:$port$request_uri;`

With the localhost IP and Port directly, e.g.:

`proxy_pass       http://127.0.0.1:9005/;`


with the slash at the end.

**Comment by mmBesar** [comment]
@ghnp5 
I did try it before, and now again, the same problem.
I think the problem is in the `nginx.conf`! This why I'm asking for your config.
