### ISSUE TITLE
Getting Internal Server Error 500 When Creating some PRs

### ISSUE THREAD

**Issue by Dan6erbond** [go-gitea/gitea#23727]
### Description

When I try to merge certain branches to our `dev` branch in a private repo, I get the 500 error with the following logs:

```console
2023/03/26 20:47:25 router: completed POST /Dikurium/consulting-tool-backend/compare/dev...user-story/732-submit-goal-categories for 10.42.0.61:46804, 500 Internal Server Error in 81.4ms @ repo/pull.go:1143(repo.CompareAndPullRequestPost)
```

### Gitea Version

1.18.5

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

Linux / Kubernetes (K3s)

### How are you running Gitea?

Gitea is running as a StatefulSet in K3s. The deployment is based on the provided Helm chart, which I rewrote to a Terraform module.

### Database

PostgreSQL

**Comment by lunny** [comment]
Are there any more detail logs?

**Comment by wxiaoguang** [comment]
No more feedback, I think this issue can be closed, feel free to reopen if there are more clues.

Gitea has new stale releases, please try the latest one.
