### ISSUE TITLE
Attachments are not deleted in Minio storage after removing them from a Release

### ISSUE THREAD

**Issue by belidzs** [go-gitea/gitea#23728]
### Description

I'm using B2 (their S3-compatible API) as my storage backend to store attachments, more specifically to store files attached to releases.

Uploading and downloading these attachments works as expected, however if I edit a release to remove an attachment, the file never gets deleted from the remote storage. It is removed from the database and from the UI as expected though.

## Steps

1. Set up an S3 compatible storage for attachments
2. Create a new release on a repo
3. Upload a file as an attachment
4. Save the release
5. Make note of the object name by hovering the mouse over it
6. Edit the release
7. Click on Remove next to the file
8. Click on Update Release
9. Verify that the object is still present in the object storage

### Gitea Version

1.19.0

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/belidzs/ab40b7e65f7a8cac9b2434754ad07fa8

### Git Version

2.38.4

### Operating System

Linux

### How are you running Gitea?

It's running in a kubernetes cluster. I've used https://gitea.com/gitea/helm-chart/ to deploy it

### Database

PostgreSQL

**Comment by lunny** [comment]
ref https://github.com/go-gitea/gitea/blob/main/services/release/release.go#LL230C36-L230C36
