### ISSUE TITLE
Bulk enable actions / enable actions by default

### ISSUE THREAD

**Issue by cthu1hoo** [go-gitea/gitea#23724]
### Feature Description

I need to enable actions for a large-ish amount of repositories. Is there a way to do that without clicking in the UI, e.g. through the API? I went through the demo API page but didn't find anything relevant.

Possibly related, it would also be great to have an organization setting to enable actions by default on any child repositories.

Thanks in advance for considering. Actions, even in the current somewhat unfinished state, are really great. I was waiting for native Gitea CI for a very long time. :)

**Comment by jaydouble** [comment]
For the time being a bash script with the use of sqlite:
```
export db=gitea/gitea/gitea.db 
sqlite3 $db "select id from repository;" | \
    while read repoid; \
    do \
        [ "$(sqlite3 $db "select * from repo_unit where repo_id=$repoid and type=10")" == "" ] && \
        sqlite3 $db "INSERT INTO repo_unit VALUES (null,$repoid,10,null,$(date +%s));"; \
    done
```

Review this script first if it fits your needs.
It will enable it on all repos without warnings.

It worked on my simple gitea server, but it maybe not working on yours. 

But it will maybe give an direction how to enable actions for your repos.

disclaimer: i'm not responsible for breaking your system.

**Comment by lunny** [comment]
The actions now was enabled by #27054 and you can update repository to enable actions via API. You can find it at https://docs.gitea.com/api/next/#tag/repository/operation/repoEdit and `has_actions`.
I think this could be closed now.
