### ISSUE TITLE
Configure a two-level nginx agent with a login prompt of 303 See Other

### ISSUE THREAD

**Issue by haowaiwai** [go-gitea/gitea#23735]
### Description

Configure a two-level nginx agent with a login prompt of 303 See Other

### Gitea Version

v.1.19.0

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

it is being run from docker

### Database

None

**Comment by lunny** [comment]
Sorry, I don't know what did you mean.

**Comment by haowaiwai** [comment]
chrome-->nginx-->nginx-->gitea

**Comment by wxiaoguang** [comment]
You can put any number of proxies between your browser and your Gitea (or any backend server), as long as you can make pass the requests correctly.

If something doesn't work, check the log in each step.

**Comment by wxiaoguang** [comment]
No more feedback, I think this issue can be closed, feel free to reopen if there are more clues.
