### ISSUE TITLE
Build failes since moving vendor dir files

### ISSUE THREAD

**Issue by daviian** [go-gitea/gitea#2373]
Regression from https://github.com/go-gitea/gitea/pull/2241

Integration test `TestLinksNoLogin` failes because of 404 from `librejs.html`

**Comment by strk** [comment]
\cc @MTecknology

**Comment by strk** [comment]
File moved to `vendor/librejs.html` (from `assets/librejs/librejs.html`)

**Comment by strk** [comment]
Hopefully fixed by https://github.com/go-gitea/gitea/pull/2374
