### ISSUE TITLE
Use Codecov App

### ISSUE THREAD

**Issue by JakobDev** [go-gitea/gitea#23746]
### Feature Description

This is just a short note for the Admins.  Every comment of the codecov bot on a PR in this Repo contains this text:

> 📣 This organization is not using Codecov’s [GitHub App Integration](https://github.com/apps/codecov). We recommend you install it so Codecov can continue to function properly for your repositories. [Learn more](https://about.codecov.io/blog/codecov-is-updating-its-github-integration/?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=go-gitea)

When following [the link](https://about.codecov.io/blog/codecov-is-updating-its-github-integration/), it says the following:

> The precise timeline for this migration has not been determined, but we’re encouraging GitHub users to adopt the App Integration before March of 2023 to prevent any potential future interruption in service.

You may already working on this, but I think it's better to open a Issue in case you don't look closer at the codecov report and missed it, before something breaks.

### Screenshots

![grafik](https://user-images.githubusercontent.com/15185051/227955289-24ff5ce2-878e-42d9-a424-5710efdf25e7.png)

**Comment by delvh** [comment]
My personal opinion:
:scream: what a pity if the absolutely useless tool that does nothing but clutter PRs doesn't work anymore…

**Comment by jolheiser** [comment]
fwiw I think code coverage _is_ a good metric to be aware of (albeit not one to die on a hill for)

I'm fine if it no longer runs on PRs, but I think at least some form of using it on the main branch would be good to continue.

In terms of the "GH app integration", I would prefer we continue to use it as-is or find another way that doesn't tie it to GH, as the goal is to eventually move to gitea.com anyways.

**Comment by silverwind** [comment]
Maybe instead of posting disruptive comments, the integration could append its result to the initial PR message. That way, no extra notifications are triggered like on a comment. I guess ultimately it is up to the forge software to provide a better interface for coverage stats, like a sidebar entry or such.

**Comment by lunny** [comment]
[covergate](https://github.com/covergates/covergates) is a possible service(self-hosted) but with less functionality.
