### ISSUE TITLE
Depenency updater

### ISSUE THREAD

**Issue by RealFascinated** [go-gitea/gitea#23760]
### Feature Description

Something similar to GitHubs dependabot would be super handy
I'm not sure if there are already ways to do this, if there is feel free to let me know (would like to use gitea actions if possible)

**Comment by jolheiser** [comment]
I believe many people have been using https://github.com/renovatebot/renovate with success. 🙂

**Comment by RealFascinated** [comment]
This would be fine, but I'm more looking for something to make a PR with the dependency update

**Comment by delvh** [comment]
https://github.com/renovatebot/renovate#why-use-renovate:
> Get automated Pull Requests to update your dependencies

?
