### ISSUE TITLE
Gitea cannot start

### ISSUE THREAD

**Issue by superflewis** [go-gitea/gitea#23775]
### Description

Mar 26 22:16:00 dub20 gitea[1913129]: 2023/03/26 22:16:00 ...y_authorized_keys.go:136:RewriteAllPublicKeys() [E] Unable to MkdirAll(/home/git/.ssh): mkdir /home/git: permission denied
Mar 26 22:16:00 dub20 gitea[1913129]: 2023/03/26 22:16:00 routers/init.go:61:mustInit() [F] code.gitea.io/gitea/models/asymkey.RewriteAllPublicKeys failed: mkdir /home/git: permission denied
Mar 26 22:16:00 dub20 systemd[1]: gitea.service: Main process exited, code=exited, status=1/FAILURE
Mar 26 22:16:00 dub20 systemd[1]: gitea.service: Failed with result 'exit-code'.

### Gitea Version

v1.19.0-rc0

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

2.30.2

### Operating System

Debian

### How are you running Gitea?

Binary install

### Database

MySQL

**Comment by eeyrjmr** [comment]
What user is gitea being run as and what user owns /home/git ?

**Comment by superflewis** [comment]
Well... there is no /home/git folder.  I caught the process:

git         1720       1  0 20:26 ?        00:00:00 /usr/local/bin/gitea web --config /etc/gitea/app.ini

**Comment by superflewis** [comment]
root@dub20:/home/williew# /usr/sbin/adduser \
   --system \
   --shell /bin/bash \
   --gecos 'Git Version Control' \
   --group \
   --disabled-password \
   --home /home/git \
   git
The system user `git' already exists. Exiting.
root@dub20:/home/williew# cd ..
root@dub20:/home# ls
lost+found  williew

**Comment by wxiaoguang** [comment]
Then you need to `mkdir /home/git` and make `git` user as its owner, because you declares that ` --home /home/git`

**Comment by superflewis** [comment]
Works finally! Thanks so much!
