### ISSUE TITLE
Reported container image size on UI seems incorrect

### ISSUE THREAD

**Issue by wxiaoguang** [go-gitea/gitea#23771]
### Description

A report from Discord channel, thanks to Fascinated.

> Container registry works perfectly fine but the size of the images always shows as 856 B
> Same size on 2 different packages

![image](https://user-images.githubusercontent.com/2114189/228293465-4bb3ad18-1cb1-4039-b500-2568d600eaa9.png)

### Gitea Version

1.19.0

**Comment by KN4CK3R** [comment]
The size is correct. The image is a manifest list ("there are architectures x and y, choose one") and this list is just a small json document. The real images use more size.
Docker Hub does not show the size of a manifest list ("latest" in this case) but shows the size for every architecture:
![grafik](https://user-images.githubusercontent.com/1666336/228574153-026ac38d-5b6a-46cb-bc69-9a84071d917d.png)

Gitea displays only the available architectures but without size.
![grafik](https://user-images.githubusercontent.com/1666336/228575201-503db6a1-ea90-4e9c-a3cd-ee28f0f2898b.png)

So a simple solution would be to hide the size if an image is a manifest list to not confuse a viewer.

**Comment by yp05327** [comment]
IMO the size in `Details` means the size of used local disk space.
Maybe we can add the size for each architecture in the list.

**Comment by Zettat123** [comment]
> Is it possible to show the real size of the real image?

I think yes. We can read the layers from the `manifest.json` of each architecture and then add up the size of each layer to get the real size of the image.

**Comment by KN4CK3R** [comment]
I have changed the display of architectures:
![grafik](https://user-images.githubusercontent.com/1666336/228781477-cc76c4d1-4728-434f-8a27-fc008790d924.png)
Will push the changes later.

**Comment by RealFascinated** [comment]
the hope was that the size in the details would be the total size of everything in the package

**Comment by KN4CK3R** [comment]
That would not be correct.

**Comment by RealFascinated** [comment]
awesome, thanks :)
