### ISSUE TITLE
"Bad Request: invalid CSRF token" when Updating branch by merge

### ISSUE THREAD

**Issue by eNBeWe** [go-gitea/gitea#23787]
### Description

When clicking the "Update branch by merge" button in a pull request, I get dropped back to the main gitea page with a "Bad Request: invalid CSRF token" error message.

### Gitea Version

1.19.0 as well as 1.19.0+28-g81a995cd8

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![grafik](https://user-images.githubusercontent.com/3796429/228487432-c4fc1f51-1293-4af9-b431-de7ce757c07b.png)
![grafik](https://user-images.githubusercontent.com/3796429/228487535-f053d5fc-806b-4f41-ac1c-5dbe96c72a2d.png)

### Git Version

2.25.1

### Operating System

Ubuntu Linux 20.04.6

### How are you running Gitea?

Installed from binaries with systemd service behind nginx reverse proxy.
Nginx-Config is the same as given in the docs.

### Database

PostgreSQL

**Comment by lunny** [comment]
Whether you stay the page for a long time and click the button directly when you back?

**Comment by eNBeWe** [comment]
Happens in either case

**Comment by wxiaoguang** [comment]
OK, I understand the problem now. A regression of #22683

**Comment by eNBeWe** [comment]
For completeness: Nothing in the site admin pages.
But I guess that is kind of moot now, since you found the issue. Good job

**Comment by wxiaoguang** [comment]
#23790 will fix the problem. Thank you for your report.
