### ISSUE TITLE
Provide Dynamic LibreJS

### ISSUE THREAD

**Issue by MTecknology** [go-gitea/gitea#2379]
The librejs.html being produced is now complete documentation of included javascript. Unfortunately, this file is not very maintainable and not easy to read.

I think we should try to find a tool to manage vendor'd dependencies that uses an easy to read (json?) file as input. We should be able to keep track of package name, license, license url, version in use, download location for that version <other stuff?>.

I like to work on adding a page that is able to read this file and generate a dynamic version of librejs.html, if someone is willing to figure out/implement the right tool for the job. :)

Instead of assuming users will hover over a download link to find the download location, I'd prefer append a second table to the page explicitly listing versions.

**Comment by kolaente** [comment]
Bower? Or one of its successors?

**Comment by 6543** [comment]
is generated automatically now: https://try.gitea.io/js/licenses.txt
