### ISSUE TITLE
When canceling edit of project inside organization sends to 404

### ISSUE THREAD

**Issue by laromicas** [go-gitea/gitea#23799]
### Description

Inside an organization create a project.
Edit it.
Cancel
It redirects to `/projects`
![image](https://user-images.githubusercontent.com/2052864/228607778-2fa12c06-8617-4f0c-a1eb-071d6619674a.png)
and sends to 404
![image](https://user-images.githubusercontent.com/2052864/228607950-8065a2b5-55f0-4bca-b2cc-5571be44b65f.png)

### Gitea Version

1.19

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![image](https://user-images.githubusercontent.com/2052864/228607377-257cfb85-f08f-4a00-bfe7-8dc28762d9b0.png)
![image](https://user-images.githubusercontent.com/2052864/228607564-93cf8780-eb0a-4aba-b793-06795b80a411.png)
![image](https://user-images.githubusercontent.com/2052864/228607778-2fa12c06-8617-4f0c-a1eb-071d6619674a.png)
![image](https://user-images.githubusercontent.com/2052864/228607950-8065a2b5-55f0-4bca-b2cc-5571be44b65f.png)

### Git Version

git version 2.38.4

### Operating System

UNRAID Version: 6.11.5

### How are you running Gitea?

Gitea used inside a docker container in unraid.
https://registry.hub.docker.com/r/gitea/gitea/
MariaDB 10.11.2-MariaDB-1:10.11.2+maria~ubu2204

### Database

MySQL

**Comment by Zettat123** [comment]
Looks like this bug has been fixed in #23655

**Comment by wxiaoguang** [comment]
> Looks like this bug has been fixed in #23655

Need to backport?

**Comment by Zettat123** [comment]
I think we backport to 1.19

**Comment by wxiaoguang** [comment]
This issue can be closed by 

* #23813 

It had been merged.

You can use the nightly build from https://dl.gitea.com/gitea/1.19/ or docker `gitea:1.19-dev`.

**Comment by Zettat123** [comment]
I'll close this issue since the backport PR #23655 has been merged. Please feel free to reopen if you need more help.
