### ISSUE TITLE
Create repo/org list is outside the browser

### ISSUE THREAD

**Issue by yp05327** [go-gitea/gitea#23803]
### Description

try.gitea.io: (1.20.0+dev-301-g3e8db31a5)
![image](https://user-images.githubusercontent.com/18380374/228706368-f354a8bc-bbdd-460e-9418-9899acbc3f3e.png)
gitea.com: (1.20.0+dev-265-gc5cfc0855)
![image](https://user-images.githubusercontent.com/18380374/228706432-1180edf3-f142-42ad-b73c-ca237577d802.png)

### Gitea Version

1.20.0+dev-301-g3e8db31a5

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

build

### Database

None

**Comment by wxiaoguang** [comment]
See:  Fix dropdown direction behavior #23806
