### ISSUE TITLE
Semicolons in locale_en-US.ini

### ISSUE THREAD

**Issue by kzmi** [go-gitea/gitea#23814]
### Description

There is an issue with the locale_en-US.ini file where the following four keys contain semicolons:

* settings.protect_protected_file_patterns
* settings.protect_protected_file_patterns_desc
* settings.protect_unprotected_file_patterns
* settings.protect_unprotected_file_patterns_desc

The semicolons are causing problems because Crowdin treats a semicolon as the beginning of a comment:

![image](https://user-images.githubusercontent.com/3753969/228761709-d5e02318-02c9-4b8a-9dee-26d7c5459024.png)

This leads to the following issues:
- The part of the text after the semicolon cannot be translated.
- Crowdin appends the original comment to the end of the translation. (see [locale_zh-CN.ini](https://github.com/go-gitea/gitea/blob/71afbcafa9f8200af3f2e4848fad605116159c7f/options/locale/locale_zh-CN.ini#L2138-L2141))

It may be possible to enclose the text in double quotes to prevent Crowdin from treating the semicolon as a comment.

### Gitea Version

265675a31c1939cb25ee659868559aec03fecb48

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

-

### Database

None

**Comment by lunny** [comment]
I think most of the translations have the same problems. Maybe we need some translations lint when pushing.

**Comment by wxiaoguang** [comment]
I have removed most semicolons in en-US.ini. Those are the last four.

This time I will do a quick patch , try to use `\;` as before.

Next time I will propose a complete PR.

**Comment by wxiaoguang** [comment]
See:  Clarify Gitea/Crowdin locale behaviors, improve LocaleStore and update-locales.sh #23819

**Comment by wxiaoguang** [comment]
A hint: I guess we couldn't do ```` settings.protect_protected_file_patterns=`"... '\;' ... " ;'):`` ````  (eg: [the last commit](https://github.com/go-gitea/gitea/commit/d5feb10aca0b309dce17a13255b4030f0a0cfe1b#diff-321f6ca4eae1096eba230e93c4740f9903708afe8d79cf2e57f4299786c4528bL2138) )


#23819 uses `key="x='y'; z"` , I guess it should work well for both Gitea and Crowdin.
