### ISSUE TITLE
Predictable URL for release downloads

### ISSUE THREAD

**Issue by mikhirev** [go-gitea/gitea#23817]
### Feature Description

It would be very helpful if released files had a predictable URL, so that it would be possible to download them without knowing a Gitea internal UUID. It is needed for automation scripts.

E. g. such URL could have a path `/<project_path>/releases/tag/<tag_name>/assets/<file_name>`.

**Comment by JakobDev** [comment]
This should be simple. I see, if I can can do it tomorrow.

**Comment by mikhirev** [comment]
Well, IIUC the original problem was that multiple releases could have files with the same name attached that lead to collisions. But what I propose is including release tag in path, so cross-release collisions are impossible. I can't imagine why should someone want to have files with identical names in the same release.
