### ISSUE TITLE
Font size of editor and preview should be the same

### ISSUE THREAD

**Issue by vorlif** [go-gitea/gitea#23816]
### Description

Hi guys, first of all thanks for your work!

This is not really a bug, but it's been bothering me for a while. I think in the editor the font size for headings is overly large. I think nowhere in the entire Gitea UI are fonts used that large, and it would be nice if the font size in the editor and preview were identical.  

### Screenshots

![image](https://user-images.githubusercontent.com/4333770/228795716-14bbc77e-6dd0-42bb-b0dc-bf05e9a17fa0.png)

The preview looks good, but uses completely different font sizes

![image](https://user-images.githubusercontent.com/4333770/228795883-6092fad0-2100-4e0e-a8d9-cb89a128102d.png)

### Gitea Version

1.18, 1.19

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

Arch Linux

### Browser Version

Firefox 111 / Chrome 111

**Comment by silverwind** [comment]
PR welcome to adjust those font sizes. Long-Term we well move away from the WYSIWYG editor to a plain textarea.

**Comment by silverwind** [comment]
Don't see this as blocking for 1.19.1.

**Comment by wxiaoguang** [comment]
I proposed 2 small PRs:

* For 1.20: #24151
* For 1.19: #24152 

You can get the latest nightly build from https://dl.gitea.com/gitea/1.19/ or https://dl.gitea.com/gitea/main/ (for 1.20), or use latest docker image `:1.19-dev` or `:dev` (for 1.20)
