### ISSUE TITLE
Packages cannot be displayed after a user is deleted

### ISSUE THREAD

**Issue by vorlif** [go-gitea/gitea#23818]
### Description

We have a user who has published packages. After the user is deleted, the packages page cannot be opened.

### Gitea Version

1.18.5

### Can you reproduce the bug on the Gitea demo site?

No / Not attempted, as relatively complex.

### Log Gist

```text
2023/03/30 12:21:07 .../web/user/package.go:60:ListPackages() [E] [64256293] GetPackageDescriptors: user does not exist [uid: 19, name: , keyid: 0]
```

### Screenshots

![image](https://user-images.githubusercontent.com/4333770/228809039-aa149528-e132-4cf3-b760-7ab1d79d6adb.png)

### Git Version

2.39.1

### Operating System

Debian 11.6

### How are you running Gitea?

* Binary source: download from the Gitea site
* Execution: Directly on the host system
* Started via: systemd

### Database

PostgreSQL

**Comment by lunny** [comment]
Is this still a problem of v1.19.0 ?
