### ISSUE TITLE
"Make Repository Private" option should be moved into the "Danger Zone" settings area

### ISSUE THREAD

**Issue by alystair** [go-gitea/gitea#23826]
### Feature Description

Changing the visibility of a repo is a non-trivial decision after creation as it can affect many users and has potential knock-on effects.

### Screenshots

Gitea
![Current Gitea implementation](https://user-images.githubusercontent.com/159109/228931179-9a12468b-11f7-4f87-a754-f58f04e48d1b.png)

GitHub
![GitHub](https://user-images.githubusercontent.com/159109/228931072-0254c57c-e51d-4fc5-8e40-1ea0df43d4ee.png)

**Comment by fabiobarkoski** [comment]
Can I work on this issue, or it was solved?

**Comment by lunny** [comment]
> Can I work on this issue, or it was solved?

Sure. And this has been resolved.

**Comment by fabiobarkoski** [comment]
Reading the code, it seems that a user can change repo visibility. If so, isn't it better that only admins can change the visibility?

**Comment by lunny** [comment]
> Reading the code, it seems that a user can change repo visibility. If so, isn't it better that only admins can change the visibility?

Yes, I think the permissions have been checked. We just need frontend changes.
