### ISSUE TITLE
Gitea broken in latest commit

### ISSUE THREAD

**Issue by JakobDev** [go-gitea/gitea#23838]
### Description

In the latest commit, Gitea is complete broken (see Screenshot).  It looks like the assets file serves no content.

### Gitea Version

288c2e8c48991e5e425fd5ffe1959f4b3d0b675a

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/JakobDev/f8438f293ae4ea7fba877896f572914e

### Screenshots

![grafik](https://user-images.githubusercontent.com/15185051/229052789-709ec5fe-21b3-4ecb-b5eb-e677e6245b38.png)

### Git Version

2.39.2

### Operating System

Manjaro

### How are you running Gitea?

Build with `TAGS="bindata sqlite sqlite_unlock_notify" make build`

### Database

None

**Comment by sclu1034** [comment]
I've been experiencing the same thing. Running without the `bindata` tag serves as a workaround for now.

**Comment by lunny** [comment]
I cannot reproduce this on my local machine.

**Comment by wolfogre** [comment]
I can reproduce, need move the binary out of the code repo and start it.

**Comment by lunny** [comment]
I can now reproduce it. It's only for the installation page. After installation is finished, it will become normal.

**Comment by lunny** [comment]
Caused by #23495, 1.19 branch is also affected. @wxiaoguang

**Comment by wxiaoguang** [comment]
See:  Fix incorrect CORS failure detection logic #23844 

1.19 is not affected.
