### ISSUE TITLE
Support MINIO_CHECKSUM_ALGORITHM on lfs

### ISSUE THREAD

**Issue by andersmmg** [go-gitea/gitea#23837]
### Feature Description

The option 'MINIO_CHECKSUM_ALGORITHM' can be used for attachments for compatibility with backblaze which doesn't support the 'x-amz-checksum-algorithm' header. Being able to use this on lfs as well would be awesome, as I currently can't upload some projects when it's set to use backblaze.

**Comment by wxiaoguang** [comment]
I guess the LFS package should also be covered by this option? I ever fixed a related bug in LFS package when introducing MINIO_CHECKSUM_ALGORITHM #23768 , the [lfs/content_store.go](https://github.com/go-gitea/gitea/pull/23768/files#diff-70aafb3b6abe29f1375730ba4e20de4dfad91c60b11c1fe704d9f55131b62528)

ps: I am not using backblaze so I can't tell more details. If you encounter problems, welcome to provide more clues & logs.

**Comment by andersmmg** [comment]
Here are the logs when I try to push to my server with lfs configured to use backblaze.
```
gitea  | 2023/03/31 05:05:00 ...lfs/content_store.go:59:Put() [E] [642669fc] Whilst putting LFS OID[59e4a6dd4a1c50839fff2b63ce9837bf9008c5d2ccd1c6596d2cbf1a295eba1e]: Failed to copy to tmpPath: 59/e4/a6dd4a1c50839fff2b63ce9837bf9008c5d2ccd1c6596d2cbf1a295eba1e Error: Backblaze does not support the 'x-amz-checksum-algorithm' header for this API call.
gitea  | 2023/03/31 05:05:00 ...rvices/lfs/server.go:323:func1() [E] [642669fc] Error putting LFS MetaObject [59e4a6dd4a1c50839fff2b63ce9837bf9008c5d2ccd1c6596d2cbf1a295eba1e] into content store. Error: Backblaze does not support the 'x-amz-checksum-algorithm' header for this API call.
```
I have 
```
MINIO_CHECKSUM_ALGORITHM = md5
```
Under both `[lfs]` and my storage config `[storage.my_minio]`

**Comment by wxiaoguang** [comment]
What's your Gitea version? That fix is only in nightly.

**Comment by andersmmg** [comment]
Running `1.19.0` with docker,  I can probably try nightly, would that fix be in the latest `1.19-dev` tag or `dev` tag on the docker image?

**Comment by wxiaoguang** [comment]
`1.19-dev` tag is better for you.

`dev` tag is for next  unreleased version, aka 1.20.

**Comment by andersmmg** [comment]
Ah that makes sense. Seems to have worked perfectly! No error on 1.19-dev!
