### ISSUE TITLE
CSRF token on login

### ISSUE THREAD

**Issue by daviian** [go-gitea/gitea#2385]
- Gitea version (or commit ref): f61a1d21
- Git version: 2.13.3
- Operating system: Mac OS X
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant

## Description

After discussion in https://github.com/go-gitea/gitea/pull/2363#pullrequestreview-58278319 I checked if login is validating CSRF token. And it does not.
As opinions differ I want to start a discussion about the necessity of a token validation for login request.

A research lead me to https://stackoverflow.com/questions/6412813/do-login-forms-need-tokens-against-csrf-attacks/15350123#15350123, the guy describes a scenario in which not validating the csrf token on login page is used for an attack on data privacy.

What's your opinion on this guys? IMO I would add token validation for login.

**Comment by daviian** [comment]
Anyone against a CSRF token on login?
If not I would create a PR for this,

**Comment by lunny** [comment]
@daviian maybe because drone depends on that?

**Comment by daviian** [comment]
@lunny Any reason why the drone should depend on that?

**Comment by lunny** [comment]
@daviian since Gitea didn't implement OAuth2 provider. But drone need login with gitea user & password.

**Comment by daviian** [comment]
@lunny When does the drone need direct login to gitea, except when running integration tests? And integration tests already send csrf token on login, although the token is not validated.

**Comment by 6543** [comment]
Gitea **has** implemented OAuth2 provider
