### ISSUE TITLE
Merging pull requests not working with tracked LFS files

### ISSUE THREAD

**Issue by Shakthijuego** [go-gitea/gitea#23860]
### Description

Branches can be merged by local clients(git cli/Github for Windows) with push but not with web interface.

gitea.log have errors like this:
Apr 01 05:01:02 ip-172-31-41-184 gitea[3613493]:         batch request: missing protocol: ""
Apr 01 05:01:02 ip-172-31-41-184 gitea[3613493]:         batch request: missing protocol: ""
Apr 01 05:01:02 ip-172-31-41-184 gitea[3613493]:         batch request: missing protocol: ""
Apr 01 05:01:02 ip-172-31-41-184 gitea[3613493]:         batch request: missing protocol: ""
Apr 01 05:01:02 ip-172-31-41-184 gitea[3613493]:         batch request: missing protocol: ""
Apr 01 05:01:02 ip-172-31-41-184 gitea[3613493]:         error: failed to push some refs to....
...
Somebody else too getting the error. Mentioned here. https://discourse.gitea.io/t/merging-pull-requests-not-working-with-tracked-lfs-files/435/1

### Gitea Version

gitea-1.19.0

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

<img width="842" alt="Screenshot 2023-04-01 at 10 53 55 AM" src="https://user-images.githubusercontent.com/25612450/229267221-f5a9fc56-3bad-47a5-8af8-0935dc1f2b62.png">

### Operating System

ubuntu

### How are you running Gitea?

Native build on ubuntu, running using systemctl

### Database

SQLite

**Comment by wxiaoguang** [comment]
I am using LFS too, haven't encounter the problem.

![image](https://user-images.githubusercontent.com/2114189/230044007-462c2877-b526-4d61-a059-5c275adb222d.png)


Could you help to provide more clues, or provide a minimal reproducible setup (eg: docker)?

**Comment by wxiaoguang** [comment]
Feel free to re-open if you can provide reproducible steps.
