### ISSUE TITLE
Editing tags - ERROR 404

### ISSUE THREAD

**Issue by BElluu** [go-gitea/gitea#23865]
### Description

If you try to edit the tag, you get a 404 error. The tag remains unchanged. I reproduce it on demo and my dev env.

### Gitea Version

1.20

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

https://gist.github.com/BElluu/cc571885fb7a232077f89760bbe60b6b

### Screenshots

![image](https://user-images.githubusercontent.com/11333925/229308359-ec8e57f9-f807-4727-9907-ed6419f7fab6.png)

### Git Version

development

### Operating System

Linux

### How are you running Gitea?

Using debuger or make command

### Database

MySQL

**Comment by lunny** [comment]
I couldn't reproduce it in your try url.

**Comment by BElluu** [comment]
@lunny I reproduce it all the time. I record screen video - look at this.

https://user-images.githubusercontent.com/11333925/229356526-013e3a0a-66e1-4b76-9ac6-3ec8a37e4190.mp4

**Comment by Zettat123** [comment]
related code

https://github.com/go-gitea/gitea/blob/c2ff2a472435c9735b8fef78c3797e54b99c73ad/routers/web/repo/release.go#L529-L532
