### ISSUE TITLE
Pull Requests > Files changed's sidebar

### ISSUE THREAD

**Issue by EndMove** [go-gitea/gitea#23870]
### Description

Hello, 

I noticed during my code review that the file tree was missing. Then I noticed a button I pressed on it, and it opened the tree but in very small. The "bug" is simply the fact that the right side bar (see in red on screenshot 01) is not specified to take all the available height, and where to put it in automatic.

Furthermore, just above the horizontal bar there is a small line with the name of the files etc. It makes no sense to have this here, and it is totally unreadable (see in purple on screenshot 01). 

### Screenshots

Screen 01
![image](https://user-images.githubusercontent.com/38650560/229348051-df90e2c7-9632-4569-953c-e2d857581211.png)

Screen 02 (sidebar fixed with "height: auto;" on the container div)
![image](https://user-images.githubusercontent.com/38650560/229348148-5e6e9a55-99bb-426e-ab6b-e54490c3d4c1.png)

### Gitea Version

1.19.0

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

docker

### Browser Version

not useful

**Comment by wxiaoguang** [comment]
Related: #23593

The fix for 1.19 (#23616) has been merged.

You can get 1.19 latest from https://dl.gitea.com/gitea/1.19/ , or `docker gitea:1.19-dev`

These contain the fix.

**Comment by EndMove** [comment]
> Related: #23593
> 
> The fix for 1.19 (#23616) has been merged.
> 
> You can get 1.19 latest from https://dl.gitea.com/gitea/1.19/ , or `docker gitea:1.19-dev`
> 
> These contain the fix.

Thanks for your feedback @wxiaoguang
