### ISSUE TITLE
500 Error after modifying ALLOWED_USER_VISIBILITY_MODES for some users

### ISSUE THREAD

**Issue by j0nxs** [go-gitea/gitea#23893]
### Description

In our team we noticed some 500 errors for some users. It was after I changed the value of ALLOWED_USER_VISIBILITY_MODES to 'limited,private'.
The users with the 500 gave following log message:
`.ers/web/auth/auth.go:338:handleSignInFull() [E] [642aa1ae] UpdateUserCols: visibility Mode not allowed: public`
So it seems that a migration is missing when a visibility mode is becoming unavailable - possible solution is a message with a select box for new mode or automatic change of the mode to the next best matching option.
public -> limited -> private

### Gitea Version

1.19

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

Linux (Kubernetes)

### How are you running Gitea?

Kubernetes Helm Chart

### Database

MySQL

**Comment by lunny** [comment]
duplicated with #23211
