### ISSUE TITLE
Action doesn't run on `pull_request` for subsequent commits

### ISSUE THREAD

**Issue by harryzcy** [go-gitea/gitea#23897]
### Description

The Gitea action is set to trigger `on: [pull_request]`, but only runs when PR is created, and not when subsequent commits are made.

### Gitea Version

1.19.0

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

<img width="815" alt="image" src="https://user-images.githubusercontent.com/37034805/229527303-e3e3b892-6b0d-47b8-8170-8cc979b28430.png">

### How are you running Gitea?

Self-hosted using official docker image

### Database

PostgreSQL

**Comment by Zettat123** [comment]
I think this bug should be fixed by #23683.
@sillyguodong  Could you please take a look?

**Comment by lunny** [comment]
And maybe also #23037

**Comment by sillyguodong** [comment]
Thank you for report, it will be fixed after the release of v1.19.1 by #23683

**Comment by wxiaoguang** [comment]
The backport had been merged.

You can use the nightly build from https://dl.gitea.com/gitea/1.19/ or docker `gitea:1.19-dev`.
