### ISSUE TITLE
JavaScript error: EvalError: call to Function() blocked by CSP

### ISSUE THREAD

**Issue by GhaziTriki** [go-gitea/gitea#23928]
### Description

I am running gitea behind nginx revers proxy. In the UI get the following JS error message that prevents me from doing some actions like switching to SSH.

JavaScript error: EvalError: call to Function() blocked by CSP (https://gitea.mycompany.net/assets/js/index.js?v=1.19.0 @ 19:71859). Open browser console to see more details.

In the console I have 'Content Security Policy: The page’s settings blocked the loading of a resource at eval (“default-src”).'

### Screenshots

![2023-04-04_20-51](https://user-images.githubusercontent.com/4991088/229904500-aa780c6b-0453-4166-9ad6-f9c41f91cbca.png)

### Gitea Version

1.19.0

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

Ubuntu 20.04 LTS

### Browser Version

Firefox 111.0.1 (64-bit)

**Comment by silverwind** [comment]
It's likely because of the Vue compiler which requires `unsafe-eval` CSP. See https://github.com/go-gitea/gitea/issues/19851 and linked discussions. We need to find out how to remove it from served JS.

**Comment by wxiaoguang** [comment]
I think it has been fixed in 1.20, there is no `EvalError` anymore.

Welcome try try.

**Comment by wxiaoguang** [comment]
Do you still have problem in 1.20?  (I guess there won't be problem, I had tested the CSP when I did the refactoring)

That was a big refactoring, so the changes were not backported to 1.19

**Comment by GhaziTriki** [comment]
Is it possible to get a nightly build for 1.20? I guess you not backported to 1.19.x  since the fix is not in 1.19.1?

**Comment by techknowlogick** [comment]
@GhaziTriki nightlies can be found in https://dl.gitea.com/gitea/main/

**Comment by GhaziTriki** [comment]
I confirm it works in 1.20 build from "main"

**Comment by techknowlogick** [comment]
@GhaziTriki fantastic! I'll close this ticket now :)
