### ISSUE TITLE
Git archive command error

### ISSUE THREAD

**Issue by axeloz** [go-gitea/gitea#2393]
- Gitea version (or commit ref): Gitea Version: 1.1.0+24-g8746fb3
- Git version: git version 1.9.1
- Operating system: Ubuntu 14.04 LTS
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant

## Description

I get an error when running the following `git archive` command which should get me an archive of the given repository at the given revision:

`git archive --remote=git@git.wcie.io:agence/deployer.git --format=tar -o /tmp/150366516285.tar 6d9cf8e`

The output is:

```
fatal: sent error to the client: git upload-archive: archiver died with error
remote: fatal: no such ref: 6d9cf8e
remote: git upload-archive: archiver died with error
Gitea: Internal error
Failed to execute git command: exit status 128
```

In the serv.log, I get:

`2017/08/25 14:50:34 [...io/gitea/cmd/serv.go:306 runServ()] [F] Failed to execute git command: exit status 128`

The full revision ID is `6d9cf8eb0f8e7f67bed1387f27a27347337e2366`. It does exist in Gitea, in this repository.

Thanks

**Comment by axeloz** [comment]
Hang on, that may be normal, I'm reading the Git documentation of `git-upload-archive`:

```
Clients may not use other sha1 expressions, even if the end result is reachable. E.g., neither a relative commit like master^ nor a literal sha1 like abcd1234 is allowed, even if the result is reachable from the refs.
```

https://git-scm.com/docs/git-upload-archive

**Comment by axeloz** [comment]
I'm not quite sure to understand why the use of sha1 is forbidden by the server. There seems to be an option to disable this behavior: 

```
If the config option uploadArchive.allowUnreachable is true, these rules are ignored, and clients may use arbitrary sha1 expressions. This is useful if you do not care about the privacy of unreachable objects, or if your object database is already publicly available for access via non-smart-http.
````

**Comment by ghost** [comment]
@axeloz any breakthroughs?

**Comment by axeloz** [comment]
@jhabdas sorry man, no. I decided to use a `git checkout` to the given revision if I remember right.

**Comment by rwese** [comment]
Sadly today I would need exactly this to export a repository for a image-build.

**Comment by lunny** [comment]
@rwese This is still a problem.

**Comment by lunny** [comment]
So maybe make `uploadArchive.allowUnreachable` as an option on gitea side will resolve this issue.

**Comment by rwese** [comment]
@lunny today I reviewed this again to make produce more details and figured out it is a user-error.

Not providing a remote path to the `git archive` command results in an internal error:

```
$ git archive --format=tar --remote=ssh://git@xxxxx:22132/wese/ansible.git

remote: usage: git archive [<options>] <tree-ish> [<path>...]
remote:    or: git archive --list
remote:    or: git archive --remote <repo> [--exec <cmd>] [<options>] <tree-ish> [<path>...]
remote:    or: git archive --remote <repo> [--exec <cmd>] --list
remote: 
remote:     --format <fmt>        archive format
remote:     --prefix <prefix>     prepend prefix to each pathname in the archive
remote:     -o, --output <file>   write the archive to this file
remote:     --worktree-attributes
remote:                           read .gitattributes in working directory
remote:     -v, --verbose         report archived files on stderr
remote:     -0                    store only
remote:     -1                    compress faster
remote:     -9                    compress better
remote: 
remote:     -l, --list            list supported archive formats
remote: 
remote:     --remote <repo>       retrieve the archive from remote repository <repo>
remote:     --exec <command>      path to the remote git-upload-archive command
remote: 
remote: git upload-archive: archiver died with error
fatal: sent error to the client: git upload-archive: archiver died with error
Gitea: Internal error
Failed to execute git command: exit status 128
```

Providing a `path` works fine e.g. **HEAD**:

```
git archive \
            --format=tar \
            --remote=ssh://git@xxxxxxxx:22132/wese/ansible.git \
            -o /tmp/test.tar \
            HEAD
```

So maybe it is possible to catch this and return a understandable message?

Anyways, I hope this helps someone, since it wasn't clear for me.

Cheers!

**Comment by lunny** [comment]
OK. Thanks @rwese
