### ISSUE TITLE
Upgrade script should inform users that gitea service has to be running in order to upgrade it

### ISSUE THREAD

**Issue by ijustlovemath** [go-gitea/gitea#23949]
### Description

I'm running a non-docker install on a Debian VPS, and was upgrading from 1.18.3 to 1.19.0, using the upgrade script found here: https://github.com/go-gitea/gitea/blob/main/contrib/upgrade.sh

Following the backup steps, I stopped the gitea service with `#systemctl stop gitea`, did the manual backups, and then ran the upgrade script `# ./upgrade.sh`.

This upgrade script expects the service to be running (since it runs the flush queues command before making a backup), so when it encounters an Internal Server Error, it should suggest you have the service running before executing the upgrade script.

### Gitea Version

1.18.3

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

Debian

### How are you running Gitea?

Using a prebuilt binary fetched with the Upgrade script. Original install came from Linode Marketplace (which had something like 1.16.x)

### Database

PostgreSQL

**Comment by wxiaoguang** [comment]
Closed by #23949

But, actually, the script should not require Gitea is running, it should just ignore the "flush queue" failure if there is no running instance.

**Comment by ijustlovemath** [comment]
You linked this issue and not the PR, btw!
