### ISSUE TITLE
Use of FQIN in Dockerfile FROM instructions.

### ISSUE THREAD

**Issue by gitouche-sur-osm** [go-gitea/gitea#23954]
### Feature Description

This is a request for the use of `Fully Qualified Image Names (FQIN)` in Dockerfile `FROM` instructions.
eg. `FROM alpine:3.17` -> `FROM docker.io/library/alpine:3.17`

The use of short names is ambiguous as the registry it pulls from might depend on docker (or alternative build system) configuration. This is better explained in [containers-registries.conf man page](https://github.com/containers/image/blob/main/docs/containers-registries.conf.5.md#note-risk-of-using-unqualified-image-names).

Docker uses hardcoded configuration in order to search for short names on docker.io registry :
```
echo $(docker info | grep -oP "(?<=Registry: ).*")
https://index.docker.io/v1/
```
But this behaviour might be different if `registry-mirrors` is set in docker `daemon.json`.

This would also improve support for docker alternatives as well (e.g. buildah, where the docker.io HUB might not be the default registry), while staying 100% docker compatible.

Lines that would need patching : 
https://github.com/go-gitea/gitea/blob/797babbfcbcf845fe12c8659fffa1693ec4708bb/Dockerfile#L2
https://github.com/go-gitea/gitea/blob/797babbfcbcf845fe12c8659fffa1693ec4708bb/Dockerfile#L26
https://github.com/go-gitea/gitea/blob/797babbfcbcf845fe12c8659fffa1693ec4708bb/Dockerfile.rootless#L2
https://github.com/go-gitea/gitea/blob/797babbfcbcf845fe12c8659fffa1693ec4708bb/Dockerfile.rootless#L26

Thank you for considering this request.

**Comment by techknowlogick** [comment]
@gitouche-sur-osm thanks for the suggestion. I've just created a PR for this: https://github.com/go-gitea/gitea/pull/23955
