### ISSUE TITLE
Improve action log display

### ISSUE THREAD

**Issue by yp05327** [go-gitea/gitea#23962]
### Description

https://gitea.com/gitea/act_runner/actions/runs/218
![image](https://user-images.githubusercontent.com/18380374/230524754-7c500e95-6cd3-4d1c-b9e5-06207ba399c5.png)
Does this log display correct? It seems that `\n` is not handled.

### Gitea Version

1.20.0+dev-349-g17f23182f

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

gitea.com

### Database

None

**Comment by wxiaoguang** [comment]
I guess the original out is two chars: one is `\` and other is `n`.

The action log system doesn't do any decoding (it shouldn't), it only processes the real LF (0x10)
