### ISSUE TITLE
Gitea act not able to run

### ISSUE THREAD

**Issue by rodude123** [go-gitea/gitea#23974]
### Description

When I try to run the act daemon, I get this error what do I do? There's not enough documentation on how to set this up yet, I think since it's way too new.

```
INFO[0000] Starting runner daemon                       
INFO[2023-04-07T10:23:06+01:00] gc: 2023-04-07 10:23:06.050623535 +0100 BST m=+0.018931049  module=cache_request
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xea021b]

goroutine 10 [running]:
gitea.com/gitea/act_runner/internal/app/poll.(*Poller).fetchTask(0xc000518ac0, {0x1238c98?, 0xc00045abc0?})
        gitea.com/gitea/act_runner/internal/app/poll/poller.go:78 +0x1db
gitea.com/gitea/act_runner/internal/app/poll.(*Poller).poll(0xc000518ac0, {0x1238c98, 0xc00045abc0}, 0x0?, 0x0?)
        gitea.com/gitea/act_runner/internal/app/poll/poller.go:55 +0xc6
created by gitea.com/gitea/act_runner/internal/app/poll.(*Poller).Poll
        gitea.com/gitea/act_runner/internal/app/poll/poller.go:41 +0x6c
```

### Gitea Version

Gitea version 1.19.0 built with GNU Make 4.1, go1.20.2 : bindata, sqlite, sqlite_unlock_notify, pam, cert

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

2.34.1

### Operating System

Ubuntu 22.04

### How are you running Gitea?

I'm running the base Linux binary through a systemd service under a specific user. I'm running Ubuntu 22.04

### Database

SQLite

**Comment by lunny** [comment]
Please upgrade to the latest version and please fire similiar issues in https://gitea.com/gitea/act_runner .
