### ISSUE TITLE
Team members count is wrong and prevent from removing someone

### ISSUE THREAD

**Issue by 3l0w** [go-gitea/gitea#23970]
### Description

I don't know why but the member count is falty so i can't remove anyone from owner so do the ldap.
Some people owner of that group can't login and get a 500 error because ldap try to remove it from that team.
I found a workaround is to untick `Remove users from synchronized teams if user does not belong to corresponding LDAP group` in the ldap auth source that i use.

### Gitea Version

1.19 and newer

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/3l0w/5ff078545a4074869f34c0838f9d79f8

### Screenshots

![image](https://user-images.githubusercontent.com/37798980/230564971-7f8203aa-de7e-4f1e-bd1f-e86ec01bc089.png)
![image](https://user-images.githubusercontent.com/37798980/230565129-7367cc32-e81b-450e-8799-fedac0719a44.png)

### Git Version

2.38.4, Wire Protocol Version 2 Enabled

### Operating System

Debian GNU/Linux 12 (bookworm)

### How are you running Gitea?

I am running gitea with a docker compose with the latest tag (i also try with the dev tag).
I use openldap as LDAP and traefik as reverse proxy

### Database

MySQL

**Comment by lunny** [comment]
Could you run `./gitea doctor`?

**Comment by yp05327** [comment]
One reason is that the number of owner members is not 1, but in DB `NumMembers = 1`.
When `NumMembers=1`, nonmatter how many members belong to this owner team, `LastOrgOwner` check will not pass.
So you can not remove any owner members.

**Comment by 3l0w** [comment]
I have done nothing except upgrading to dev few days ago and run `gitea doctor` and the issue seems to be fixed 
![image](https://user-images.githubusercontent.com/37798980/235871304-3091dd8e-8242-4afa-8c79-e233a07b5539.png)
