### ISSUE TITLE
WebGUI Wiki Editor does not show Text of wiki page. Pressing save deletes all.

### ISSUE THREAD

**Issue by Henri-Kassulis** [go-gitea/gitea#23979]
### Description

When i edit any existing wiki page, gitea will not show the wiki pages content in the editor view.
There is no content. If i press save on the empty page, all the previous content is gone.
This makes it impossible for to use the Web GUI editor.

I am using getea as it is hosted on gitea.com
https://gitea.com/henri/wiki/wiki/Testpage
was able to reproduce it on 
https://try.gitea.io/henri/wikitest-repo/wiki/Home

This issue started a few day ago after the editor was changed to not be WYSIWYG any more.
I have tested it with Firefox and Chrome. Both have the bug.

Sorry, if this is the wrong place to report this issue.

### Screenshots

![gite wiki bug 1](https://user-images.githubusercontent.com/48138256/230629890-2bbcf23e-b3db-4df0-84e4-5af2015b46ed.JPG)
![gitea wiki bug 2](https://user-images.githubusercontent.com/48138256/230629898-0cdfb8d2-2b49-4faa-a485-58f85584834a.JPG)

### Gitea Version

Version: 1.20.0+dev-349-g17f23182f

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

Windows 7

### Browser Version

Firefox 111.0.1 (64-bit)

**Comment by wxiaoguang** [comment]
I guess it's a regression bug caused by my PR, I will take a look soon.
