### ISSUE TITLE
Generated installation URL for PyPI repository packages has an escaping problem

### ISSUE THREAD

**Issue by Gunzinger** [go-gitea/gitea#23980]
### Description

Hi dear gitea maintainers!

First off: Thank you for the great software, I am enjoying it a lot and it saves a lot of resources on my VPS compared to GitLab which I was using previously!

Now to the bug:
There seems to be a problem in the URL escaping of the `gitea-origin-url` templates, in which the space is url-escaped to `%20` when it should remain a space.

Reproduction of the bug in the demo site: https://try.gitea.io/test-pypi-url-bug/-/packages/pypi/pypi-url-test/0.1.0

Might have been introduced in this commit: https://github.com/go-gitea/gitea/commit/e7ef94e00f1319e5fb876f47fee28728bd671f07

### Screenshots

![demo instance screenshot](https://user-images.githubusercontent.com/8051909/230634594-505ab363-b098-4aa8-a882-f21f84ed8188.png)

### Gitea Version

1.19.0 (official docker container)

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

Windows 10

### Browser Version

Firefox 111.0.1

**Comment by Gunzinger** [comment]
Working on a PR, I think this is an easy fix by adjusting the `pypi.tmpl` and allows for the addition of a trailing slash to the repository URL in accordance to PEP-503.

**Comment by silverwind** [comment]
Is this suffix supposed to be part of the URL? If yes, the escaping would be correct.

**Comment by Gunzinger** [comment]
For anybody stumbling upon this, the suffix in this case is the package name, and as such not part of the URL, thanks for the approve :)
