### ISSUE TITLE
Dashboard shows all organization repositories, not respecting access rights

### ISSUE THREAD

**Issue by Morlinest** [go-gitea/gitea#2399]
- Gitea version (or commit ref): f61a1d21
- Git version:
- Operating system:
- Database (use `[x]`):
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:

## Description

See title.

**Comment by lunny** [comment]
Any further information?

**Comment by Morlinest** [comment]
@lunny You can reproduce this by creating repositories in organization, one public and one private. Create user and assign him to organization (invite as collaborator or create team without rights for any repo). On dashboard you will see every repository of organization, but if you try to open the private one, you will end with `404` page.
