### ISSUE TITLE
Integrate Drone CI

### ISSUE THREAD

**Issue by tboerger** [go-gitea/gitea#24]
To keep the CI system as fast as possible we should replace TravisCI with Drone CI, we can use my hosted version or we can also run our own Drone CI instance, however we prefer.

**Comment by lunny** [comment]
So which work should we do?

**Comment by strk** [comment]
@tboerger how would drone make CI faster ? doesn't travis also support docker ?
That said, I'm ok with using Drone either in addition to or instead of Travis.

**Comment by tboerger** [comment]
@lunny the question is if we want to launch our own drone instance or if we should use mine or if we should ask @bradrydzewski for access to beta.drone.io

**Comment by tboerger** [comment]
> @tboerger how would drone make CI faster ? doesn't travis also support docker ?
> That said, I'm ok with using Drone either in addition to or instead of Travis.

Travis is always loaded and pretty slow, drone is not. Beside that is drone much more flexible.

**Comment by lunny** [comment]
At the beginning, we will use the public service of drone. I think. @tboerger

**Comment by strk** [comment]
@bradrydzewski access to beta.drone.io would be great. I guess actual speed would depend on availability of agents.

**Comment by makhov** [comment]
I know that @tboerger loves Drone and I guess it will be good idea to use it instead of Travis, but I'm sure that we should use public service.

**Comment by strk** [comment]
Anyone up to set beta.github.io ?

**Comment by xinity** [comment]
agree @makhov as we are an opensource project, why don't we use public service, i think that would help getting more people on board.
besides build speed is a real matter as the project grows we'll need more builds , more tests and thus more workers. 

IMHO we should find a balance between growing needs and public service to attract more people on board.

**Comment by tboerger** [comment]
beta.drone.io will be opened to everybody soon, it's the only public instance of the up2date drone version. Here it's pretty good that we can use whichever plugin we want and in worst case we can simply launch our own instance.

**Comment by lunny** [comment]
Is this work now?

**Comment by lunny** [comment]
Or we can put it on v1.1

**Comment by tboerger** [comment]
This is a requirement for the build and test pipeline.

**Comment by lunny** [comment]
But we can use travis-ci on v1.0 if beta.drone.io is not ready.

**Comment by strk** [comment]
Looks like this is addressed by https://github.com/go-gitea/gitea/pull/96

**Comment by strk** [comment]
Should this be assigned to @metalmatze as he has an open PR addressing this ?

**Comment by tboerger** [comment]
Resolved via #96
