### ISSUE TITLE
Unable to create  an repo where the name contains an utf-8 char.

### ISSUE THREAD

**Issue by tuxmaster5000** [go-gitea/gitea#24007]
### Description

When I try to create an repo which contains an utf8 char in its name, an error is shown:
"Repository name should contain only alphanumeric, dash ('-'), underscore ('_') and dot ('.') characters."
But an utf-8 character is an normal character.

### Gitea Version

1.19.0

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

Binary download from GH

### Database

MySQL

**Comment by KN4CK3R** [comment]
alphanumeric as `a-z0-9`

**Comment by delvh** [comment]
> Database:
MySQL

Please see https://docs.gitea.io/en-us/faq/#why-are-emoji-broken-on-mysql.
