### ISSUE TITLE
is it possible setup a whole site mirror for remote backup?

### ISSUE THREAD

**Issue by yurenchen000** [go-gitea/gitea#24000]
### Feature Description

gitea is lightful and effective,
May often run on some lightweight environments,  which even lacking storeage RAID.

I don't want Data reliability based on storage RAID.
If we can setup a remote server for whole site mirror (incremental backup/sync),
it'll safer.

<br>

some similar but not identical topics:
https://github.com/go-gitea/gitea/issues/2959
https://github.com/go-gitea/gitea/issues/22240

**Comment by wxiaoguang** [comment]
zfs and zrepl works really well for me.

You can mirror anything without downtime.

**Comment by yurenchen000** [comment]
I known I can daily backup / restore,
but that operation seems not lightweight and efficient.
https://docs.gitea.io/en-us/backup-and-restore/


is it possble some kind of stream sync (like binlog in database)

**Comment by wxiaoguang** [comment]
zfs and zrepl backup is very lightweight and efficient. They does incremental sync.

**Comment by yurenchen000** [comment]
> zfs and zrepl works really well for me.
> 
> You can mirror anything without downtime.

Thanks for such quick reply,
I will try it
