### ISSUE TITLE
all repository health checks are immediately failed

### ISSUE THREAD

**Issue by cr0c0dylus** [go-gitea/gitea#24001]
### Description

If I run "Monitoring" => "Health check all repositories" - health checks for all of my repositories are immediately failed with  "context deadline exceeded" error.

Gist contains the trace log (1 repo, the rest are the same).

If I run git fsck manually, it works without any errors:

$ cd /home/gitea/repositories/devops/zabbix.git
$ /usr/bin/git -c protocol.version=2 -c credential.helper= -c filter.lfs.required= -c filter.lfs.smudge= -c filter.lfs.clean= fsck
Checking object directories: 100% (256/256), done.
Checking objects: 100% (25/25), done.
Verifying commits in commit graph: 100% (7/7), done.

### Gitea Version

1.19.0

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/cr0c0dylus/41b0be92b35a9540985b67f6caeb9ddc

### Operating System

2.34.1

### How are you running Gitea?

Gitea is installed to /home/gitea:

# ls /home/gitea
app.ini  bin  custom  log  phpcsHooks  repositories  tmp  working

gitea.service:

WorkingDirectory=/home/gitea/working/
ExecStart=/home/gitea/bin/gitea web --config /home/gitea/app.ini --custom-path /home/gitea/custom
Environment=USER=gitea HOME=/home/gitea GITEA_WORK_DIR=/home/gitea/working

### Database

MySQL

**Comment by wxiaoguang** [comment]
What's your `[cron.*]` config in your app.ini? Especially the `TIMEOUT` keys?

**Comment by cr0c0dylus** [comment]
gitea "Configuration":
Migration Timeout 600 seconds
Mirror Update Timeout 300 seconds
Clone Operation Timeout 300 seconds
Pull Operation Timeout 300 seconds
GC Operation Timeout 7200 seconds

app.ini:
[cron.repo_health_check]
TIMEOUT = 600

[cron.git_gc_repos]
ENABLED = true

**Comment by wxiaoguang** [comment]
`TIMEOUT = 600s`

You need the suffix `s` to make is as `second`

**Comment by cr0c0dylus** [comment]
I've added 's' and it's working now! Thank you! :)
