### ISSUE TITLE
About actions act_runner installation

### ISSUE THREAD

**Issue by pencail** [go-gitea/gitea#24029]
### Description

I installed GiTea and act_runners implemented Gitea Actions
But，After running the ./act_runner daemon command，show

INFO[0000] Starting runner daemon                       
INFO[2023-04-10T15:11:14+08:00] gc: 2023-04-10 15:11:14.353469657 +0800 CST m=+0.026311088  module=cache_request
ERRO[2023-04-10T15:11:14+08:00] failed to fetch task              error="unknown: rpc error: code = Unauthenticated desc = unregistered runner"
ERRO[2023-04-10T15:11:16+08:00] failed to fetch task              error="unknown: rpc error: code = Unauthenticated desc = unregistered runner"
ERRO[2023-04-10T15:11:18+08:00] failed to fetch task              error="unknown: rpc error: code = Unauthenticated desc = unregistered runner"

How should this problem be solved？
Since you are not logged into the Gitea act_runner website, submit a LSSUES here

### Gitea Version

1.19.0

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![image](https://user-images.githubusercontent.com/21018076/230850513-a463b14e-8a7f-4df5-bac4-27da87f97bed.png)

### How are you running Gitea?

used one of your downloads，Managed by SystemCtl，Use the OpenEuler system，A system very similar to CentOS

### Database

None

**Comment by lunny** [comment]
You need to register runner first. `./act_runner register --instance http://192.168.8.8:3000 --token <my_runner_token> --no-interactive`
