### ISSUE TITLE
Confusing icon for skipped actions

### ISSUE THREAD

**Issue by bilogic** [go-gitea/gitea#24020]
### Description

If an action was skipped, it gets a green tick on the `Closed` page
![image](https://user-images.githubusercontent.com/946010/230773183-f42b5e37-6d86-4b2e-ab26-eb32ee12480a.png)
But on the code page, it gets a cross
![image](https://user-images.githubusercontent.com/946010/230773222-5dd44330-2085-4649-8670-65406fee6505.png)

Maybe a red bent arrow like a missed phone call will be better, see below?
![image](https://user-images.githubusercontent.com/946010/230773358-fb62629a-ab53-49af-ac21-c80503bb00cc.png)
![image](https://user-images.githubusercontent.com/946010/230773392-6b973d7e-cf23-4cb0-9633-5c564b060eb1.png)

### Gitea Version

1.19.0

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

Using docker

### Database

MySQL

**Comment by silverwind** [comment]
Does [octicons](https://primer.github.io/octicons/) have something suitable?

**Comment by bilogic** [comment]
@silverwind 

They use this to represent skip https://primer.github.io/octicons/skip-24

But I think the ones I googled convey meaning better.. I'm in a dilemma myself over the bent arrow or over the empty box

Anyway, the issue is the inconsistent icon, if it is easier to just use https://primer.github.io/octicons/skip-24, then it would also solve the problem.

**Comment by silverwind** [comment]
We use only 16px, so it'd be https://primer.github.io/octicons/skip-16

**Comment by wolfogre** [comment]
Related to #23599.

The point is that there is no `skipped` for commit status, and it has been treated as `success` in #23786

**Comment by silverwind** [comment]
Shouldn't we not use `octicon-skip`?

**Comment by bilogic** [comment]
@wolfogre 

Thanks, I understand gitea's approach of following github entirely, but also gave this some thought:

It's pretty confusing to:

1. Show the `commit status icon` + commit message on the actions page
2. But show `action status icon` + commit message on the code page
3. Since the intention on code page is to show the last commit, it should stay the same regardless whether actions are enabled or not
4. Instead, we could append the commit message with `action status icon` and job name, which is consistent on the `actions page`
![image](https://user-images.githubusercontent.com/946010/230847813-287aea2e-5979-4b85-bf87-d50bde07de73.png)

I can elaborate with more images if the above is not clear.

**Comment by wolfogre** [comment]
> Shouldn't we not use `octicon-skip`?

I have no objection to use a better icon replacing  
<img width="999" alt="image" src="https://user-images.githubusercontent.com/9418365/230882886-857a2606-9e1f-4bf5-8e2c-e60f8d2b62f1.png">

But I don't think it is the point.

**Comment by wolfogre** [comment]
@bilogic Sorry I'm confused.

> 1. Show the `commit status icon` + commit message on the actions page

I think it's `action status icon` + commit message on the actions page now

> 2. But show `action status icon` + commit message on the code page

I think it's `commit status icon` + commit message on the code page now

> 3. Since the intention on code page is to show the last commit, it should stay the same regardless whether actions are enabled or not

Sorry, what do you mean by "should stay the same"? The commit status could be used even without Actions.

> 4. Instead of prefixing the `action status icon` to the commit message, I feel it is better to append that icon to the commit message followed by the job name, which is consistent on the `actions page`
>    ![image](https://user-images.githubusercontent.com/946010/230847813-287aea2e-5979-4b85-bf87-d50bde07de73.png)

"prefixing the `action status icon` to the commit message", could you show me where?

**Comment by bilogic** [comment]
@wolfogre yes thanks, let me show you what i'm seeing here

## This is `code` page when actions are disabled (No icons)
![image](https://user-images.githubusercontent.com/946010/231039394-50612d03-bc74-46fe-9d3d-1358e6174bb4.png)

## When `actions` are enabled and have ran, `code` page inserts an icon (red) between the commit hash and message
![image](https://user-images.githubusercontent.com/946010/231039401-2e60fabd-aa47-4fb0-b0b4-74df13bca2d4.png)

## On `actions` page, we see a different icon (blue) together with a commit message
![image](https://user-images.githubusercontent.com/946010/231039412-8b3231d5-5a86-40e4-8689-ff289b9fafcf.png)

## Clicking into the commit message, we see a 3rd different icon (green) with the job name
![image](https://user-images.githubusercontent.com/946010/231039420-2e8fe4c0-58f6-4680-92a8-b70a7a31fd2f.png)

so what I'm trying to ask here is:

1. Can we make all 3 icons the same, based on the first step that failed, in this case `Run PHPUnit tests`?

2. I also wondered, how many statuses does a `git commit` have? For me, it is either a committed or could not commit, and if it could not be committed, there are actually no records of it in `git`. So why do we have commit statuses? Could the current `commit status` actually be something else?

3. Now, I must say, I'm very new to actions, I tried hard to see if I missed any scenarios, but could not come up with much.

Open to hearing if the current icons represents something I might have missed. Thank you!

**Comment by bilogic** [comment]
> any external CI system can create commit status via Gitea API

@wolfogre ok thanks, I have little to no understanding of the above. But since it is a thing, I'm sure you guys know better than me.
