### ISSUE TITLE
Missing "cancel" button when editing Wiki pages

### ISSUE THREAD

**Issue by khorben** [go-gitea/gitea#24036]
### Description

When editing or creating wiki pages, there is no "Cancel" button helping the user navigate back to the original wiki page, or to the list of wiki pages available, respectively. (See https://try.gitea.io/khorben/test-for-wiki/wiki?action=_new)

Alternatively, Gitea could navigate back into the user's history. On the positive side, nowadays most browsers recognise when information was input but not saved yet, and warn the user before possibly losing this information. However, this would require JavaScript (unless a fallback behaviour is implemented) and break PLA (Principle of Least Astonishment) since it would remove the page edition page from the history, without the user actually interacting with the history buttons ("Back" and "Forward").

Note that this improvement to the User Interface/User eXperience may also apply to new issues. (See https://try.gitea.io/khorben/test-for-wiki/issues/new)

### Screenshots

![image](https://user-images.githubusercontent.com/1081724/230980447-7e267c7d-34ad-4dfd-8b86-26c66e3427eb.png)

### Gitea Version

1.16.9

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

NetBSD 9.3_STABLE (GENERIC) pkgsrc-2022Q4 (from source, system service)

### Browser Version

Safari 16.3

**Comment by yardenshoham** [comment]
I don't see a reason for a "Cancel" button when you could just navigate away
References:
- https://github.com/go-gitea/gitea/pull/21381
- https://github.com/go-gitea/gitea/pull/21872

**Comment by yardenshoham** [comment]
Can you illustrate with a video/gif?

**Comment by wxiaoguang** [comment]
I agree with the author.

Think about the case:

1. Go to wiki list page
2. Edit a page
3. Change some thing
4. Now you want to navigate back to the preview page, if you click the "back" button on browser toolbar, you will see an annoying "leave confirm" dialog.


And the "cancel" button sometimes is more friendly and intuitive for such page.

**Comment by aschrijver** [comment]
Thanks for the heads-up to this issue @wxiaoguang .. I reported the same request in: https://codeberg.org/forgejo/forgejo/issues/705
