### ISSUE TITLE
URL Composition Problems with Alternative Port Configurations

### ISSUE THREAD

**Issue by smeddinck** [go-gitea/gitea#2403]
- Gitea version (or commit ref): 1.2
- Git version:
- Operating system: Debian 8
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [x] Not relevant
- Log gist:

## Description

I use an alternative port for gitea via ssl (on nginx). Many API related links (e.g. https://mysite.com/swagger.v1.json or slack integration backlinks) miss the port (since it should be https://mysite.com:4242/swagger.v1.json). Gitea 1.2 on Debian 8 with MySQL

**Comment by 0rzech** [comment]
It's the same for `https://mysite.com/mypath/swagger.v1.json`. It looks like [`ROOT_URL`](/go-gitea/gitea/blob/v1.2.3/conf/app.ini#L100) is not being prepended to Swagger's [`basePath`](/go-gitea/gitea/blob/v1.2.3/public/swagger.v1.json#L25). Unfortunately this makes Gitea's Swagger documentation unusable with custom root URLs.

**Comment by igsol** [comment]
I have a similar problem. My Gitea server runs behind SSL reverse  proxy which makes not default URL to Gitea service, e.g. https://example.com/**gitea**/.
But Swagger page continues to use https://example.com/api/v1/ with missed "gitea" part after hostname.

**Comment by 0rzech** [comment]
@igsol This should be fixed in #3572.

**Comment by 0rzech** [comment]
@lunny Mine and @igsol's case is solved, but I am not sure about @smeddinck's, as it seems to be a different kind of bug with different solution.

**Comment by igsol** [comment]
@0rzech Thanks! I am on v1.4.3 still. Waiting for next release :)

**Comment by 0rzech** [comment]
@igsol You're welcome. ;)

**Comment by lunny** [comment]
@smeddinck could you confirm #3572 resolved your issue?

**Comment by 0rzech** [comment]
@igsol I forgot to remind you the fix will be available in 1.6 version, not in 1.5.

**Comment by igsol** [comment]
@0rzech NP, it's not urgent. The bug actually is not so critical as for me, cause it makes Swagger UI usage a bit harder, but API itself works flawlessly :)

**Comment by 0rzech** [comment]
@igsol Sure thing! Just wanted to avoid potential confusion. ;)
