### ISSUE TITLE
Actions - Incorrect job status

### ISSUE THREAD

**Issue by Zettat123** [go-gitea/gitea#24039]
### Description

In my job, I use a custom action to do some work. When I run the job on an image without `node.js` installed, the job will fail in the `Set up job` step because the image doesn't have a `node.js` runtime to run that action. However, the status of the job is `Success`, see the screenshot:

![image](https://user-images.githubusercontent.com/15528715/231038361-4a1f6578-260d-43b0-aaf2-988adbc7877b.png)

### Gitea Version

v1.20.0+dev-426-gb7b887ba0

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

command

### Database

PostgreSQL

**Comment by harryzcy** [comment]
I encountered the same issue today with Gitea v1.19.1 and act_runner main branch.

**Comment by Zettat123** [comment]
Looks like this issue is related to `act_runner`, so I make a [PR](https://gitea.com/gitea/act/pulls/40) in `gitea/act` and close this issue.
