### ISSUE TITLE
Container Registry - HTTP 405 response body: invalid character '<' 

### ISSUE THREAD

**Issue by mmBesar** [go-gitea/gitea#24042]
### Description

Gitea behind nginx reverse proxy, every was working fine with Nginx Proxy Manager, but when moved to Nginx, I got the below errors

- pushing an image to the Container Registry:

```
error parsing HTTP 405 response body: invalid character '<' looking for beginning of value: "<html>\r\n<head><title>405 Not Allowed</title></head>\r\n<body>\r\n<center><h1>405 Not Allowed</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n"
```

pulling an image from the Container Registry:

```
Error response from daemon: error unmarshalling content: invalid character '<' looking for beginning of value
```

Nginx proxy config:

```
server {
    
    listen 80;
    
    set $forward_scheme http;
    set $server         "gitea"; # container name
    set $port           3000;
    server_name         gitea.hs.mm;

    location / {

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $http_connection;
        proxy_http_version 1.1;

        add_header       X-Served-By $host;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Scheme $scheme;
        proxy_set_header X-Forwarded-Proto  $scheme;
        proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP          $remote_addr;
        proxy_pass       $forward_scheme://$server:$port$request_uri;

    }


}

```

Everything else on Gitea is working fine, all my other services working fine with Nginx.
What is missing? How can I get the Registry working again!

NOTE: My Nginx is `lscr.io/linuxserver/nginx:latest`

### Gitea Version

1.19

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

Debian 11

### How are you running Gitea?

Self-hosted docker container.

### Database

None

**Comment by wxiaoguang** [comment]
It seems that the request is not allowed by nginx: `<center><h1>405 Not Allowed</h1></center>\r\n<hr><center>nginx</center>`

1. Do you have other rules on nginx side?
2. Does Gitea see the request (check Gitea logs)?

**Comment by mmBesar** [comment]
Thank you, for the quick reply.
1. I don't have any other rules.
2. This is the problem, no logs in Gitea or Nginx!
How to resolve this issue, I've tried many Nginx rules/options, Nothing seem to work!
What is interesting is with the same rules/options, Nginx Proxy Manager works fine, but NPM not reliable after the recent updates, and it's an over-kill for my use case.
Kindly advice, what is right proxy config for Container Registry to work?

**Comment by mmBesar** [comment]
Hopefully, I'll get an answer from the community here.
I'll update the issue if I got through.

**Comment by wxiaoguang** [comment]
Maybe you could share your full nginx config (by `nginx -T`)

**Comment by wxiaoguang** [comment]
Some hints:

1. How do you use the container registry? If you type "docker pull ....", IIRC it uses HTTPS by default, but you only have Gitea proxy on HTTP.
2. What do your access / error logs say? I can see there are some different log files, grep them and check them one by one to see where the request goes to?

**Comment by mmBesar** [comment]
1. I've allowed it as an `insecure-registries` in `/etc/docker/daemon.json`, it is working fine under NPM.
2. I'm not good with Nginx, but I'll do my best.

**Comment by mmBesar** [comment]
When I typed
```sh
docker push gitea.hs.mm/mbesar/nginx:latest
```
I got :
``` sh
The push refers to repository [gitea.hs.mm/mbesar/nginx]
f33a90137499: Layer already exists 
41ec0442b359: Layer already exists 
dddbf7bffd18: Layer already exists 
538f44c80ebb: Layer already exists 
d3d7516f442d: Layer already exists 
670b0bb39f97: Layer already exists 
e447796ac3e0: Layer already exists 
error parsing HTTP 405 response body: invalid character '<' looking for beginning of value: "<html>\r\n<head><title>405 Not Allowed</title></head>\r\n<body>\r\n<center><h1>405 Not Allowed</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n"
```
and on `access.log` :

```  ini
192.168.100.51 - - [11/Apr/2023:21:41:16 +0200] "GET /v2/ HTTP/1.1" 200 988 "-" "docker/23.0.3 go/go1.19.7 git-commit/59118bf kernel/5.10.0-21-amd64 os/linux arch/amd64 UpstreamClient(Docker-Client/23.0.3 \x5C(linux\x5C))"
192.168.100.51 - - [11/Apr/2023:21:41:16 +0200] "HEAD /v2/mbesar/nginx/blobs/sha256:b1a08d3d4d676e53f37784b69e659d309a86e9342ea3845595c7424b982cc77c HTTP/1.1" 200 0 "-" "docker/23.0.3 go/go1.19.7 git-commit/59118bf kernel/5.10.0-21-amd64 os/linux arch/amd64 UpstreamClient(Docker-Client/23.0.3 \x5C(linux\x5C))"
192.168.100.51 - - [11/Apr/2023:21:41:16 +0200] "HEAD /v2/mbesar/nginx/blobs/sha256:247d19ac067e07fa4fa848c0d58c71640c5bbe99d48027ba994ac9cc0e2fe279 HTTP/1.1" 200 0 "-" "docker/23.0.3 go/go1.19.7 git-commit/59118bf kernel/5.10.0-21-amd64 os/linux arch/amd64 UpstreamClient(Docker-Client/23.0.3 \x5C(linux\x5C))"
192.168.100.51 - - [11/Apr/2023:21:41:16 +0200] "HEAD /v2/mbesar/nginx/blobs/sha256:9d5244c898c055f9f6d9ad9a486f5fd76b21b162de5ede879050dec2863020d5 HTTP/1.1" 200 0 "-" "docker/23.0.3 go/go1.19.7 git-commit/59118bf kernel/5.10.0-21-amd64 os/linux arch/amd64 UpstreamClient(Docker-Client/23.0.3 \x5C(linux\x5C))"
192.168.100.51 - - [11/Apr/2023:21:41:16 +0200] "HEAD /v2/mbesar/nginx/blobs/sha256:513fff0d181b03f0d70ef63cf3872e4bd27d6f99fc934f99ab4cd8b662b8e7d9 HTTP/1.1" 200 0 "-" "docker/23.0.3 go/go1.19.7 git-commit/59118bf kernel/5.10.0-21-amd64 os/linux arch/amd64 UpstreamClient(Docker-Client/23.0.3 \x5C(linux\x5C))"
192.168.100.51 - - [11/Apr/2023:21:41:16 +0200] "HEAD /v2/mbesar/nginx/blobs/sha256:c91ac784c9eff9147894e8b7e2b00e4076a5bf250bcf1be813f0b8aabd8ff27b HTTP/1.1" 200 0 "-" "docker/23.0.3 go/go1.19.7 git-commit/59118bf kernel/5.10.0-21-amd64 os/linux arch/amd64 UpstreamClient(Docker-Client/23.0.3 \x5C(linux\x5C))"
192.168.100.51 - - [11/Apr/2023:21:41:16 +0200] "HEAD /v2/mbesar/nginx/blobs/sha256:d2e3055e06573ab92f13c5e10afa9c4160d94a4808ce1b670b090b9a0d4522fa HTTP/1.1" 200 0 "-" "docker/23.0.3 go/go1.19.7 git-commit/59118bf kernel/5.10.0-21-amd64 os/linux arch/amd64 UpstreamClient(Docker-Client/23.0.3 \x5C(linux\x5C))"
192.168.100.51 - - [11/Apr/2023:21:41:16 +0200] "HEAD /v2/mbesar/nginx/blobs/sha256:08dfcae80dd98ee60617c45f3ce7fd08cae0b7fa05b47086ff64c2c80ccb7e7b HTTP/1.1" 200 0 "-" "docker/23.0.3 go/go1.19.7 git-commit/59118bf kernel/5.10.0-21-amd64 os/linux arch/amd64 UpstreamClient(Docker-Client/23.0.3 \x5C(linux\x5C))"
192.168.100.51 - - [11/Apr/2023:21:41:16 +0200] "HEAD /v2/mbesar/nginx/blobs/sha256:687581dd42e57f75df00819389f8f685db1d388f597081b5e982fb897537831d HTTP/1.1" 200 0 "-" "docker/23.0.3 go/go1.19.7 git-commit/59118bf kernel/5.10.0-21-amd64 os/linux arch/amd64 UpstreamClient(Docker-Client/23.0.3 \x5C(linux\x5C))"
192.168.100.51 - - [11/Apr/2023:21:41:16 +0200] "PUT /v2/mbesar/nginx/manifests/latest HTTP/1.1" 405 150 "-" "docker/23.0.3 go/go1.19.7 git-commit/59118bf kernel/5.10.0-21-amd64 os/linux arch/amd64 UpstreamClient(Docker-Client/23.0.3 \x5C(linux\x5C))"
```

**Comment by mmBesar** [comment]
When using Nginx Proxy Manager

Typing:
```sh
docker push gitea.hs.mm/mbesar/nginx:latest
```

Got:
``` sh
The push refers to repository [gitea.hs.mm/mbesar/nginx]
f33a90137499: Pushed 
41ec0442b359: Pushed 
dddbf7bffd18: Pushed 
538f44c80ebb: Pushed 
d3d7516f442d: Pushed 
670b0bb39f97: Pushed 
e447796ac3e0: Pushed 
latest: digest: sha256:9994eb1e8c2f3293b503d8b50924af68471a1ccf352e793118e9241138705950 size: 1788
```

and [access.log](https://gist.github.com/mmBesar/7ef67108c8dd250888d64133ccf143c8)

**Comment by techknowlogick** [comment]
It looks like it is working with nginx pm, does that mean this can be closed?

**Comment by mmBesar** [comment]
NO! This is problem! It's working with NPM, but I've moved to Nginx.
I don't know what is the problem! Why It's not working!

**Comment by wxiaoguang** [comment]
Let's summarize the problem:

1. Use Nginx Proxy Manager, `docker pull` works
2. Use your own manually written Nginx config, use `docker pull`:
    * the related `GET` requests work, Gitea can see the requests and respond correctly
    * but the `PUT` request is denied by Nginx, Gitea doesn't see it.

Right?

If it is the case,  I think you need to check your nginx config, especially for the `method` / `deny` /` `allow` related settings.

**Comment by mmBesar** [comment]
> Ah ok, sorry about my misunderstanding.
> 
> In the original config you posted you have $request_uri in the proxy_pass directive. In our example we have `proxy_pass http://localhost:3000;` without any uri, could you try without?

No problem.
I did try with and without, the same problem!

**Comment by mmBesar** [comment]
> Let's summarize the problem:
> 
>     1. Use Nginx Proxy Manager, `docker pull` works
> 
>     2. Use your own manually written Nginx config, use `docker pull`:
>        
>        * the related `GET` requests work, Gitea can see the requests and respond correctly
>        * but the `PUT` request is denied by Nginx, Gitea doesn't see it.
> 
> 
> Right?
> 
> If it is the case, I think you need to check your nginx config, especially for the `method` / `deny` / `allow` related settings.

Yes, this it!
I don't know, what am I looking for!
I didn't find any of these words in the `nginx.conf`.

**Comment by ghnp5** [comment]
Maybe replace this:

`proxy_pass       $forward_scheme://$server:$port$request_uri;`

With the localhost IP and Port directly, e.g.:

`proxy_pass       http://127.0.0.1:9005/;`

with the slash at the end.


It could be that `/v2/***` isn't being passed into Gitea's container, and `PUT` isn't allowed on the root / of Gitea, or something like that.
The slash at the end should help with that.

**Comment by mmBesar** [comment]
> Maybe replace this:
> 
> `proxy_pass $forward_scheme://$server:$port$request_uri;`
> 
> With the localhost IP and Port directly, e.g.:
> 
> `proxy_pass http://127.0.0.1:9005/;`
> 
> with the slash at the end.

I did try it, got the same output!

> It could be that `/v2/***` isn't being passed into Gitea's container, and `PUT` isn't allowed on the root / of Gitea, or something like that.

I think this is the problem, but I have no Idea how to fix it!

I did try adding another `location`

``` ini
    location /v2/ {

        proxy_pass http://127.0..1:3000/v2/;

    }
```

**Comment by techknowlogick** [comment]
nginx pm generates an actual config. Could you exec into the container and see what the difference might be?

**Comment by mmBesar** [comment]
> nginx pm generates an actual config. Could you exec into the container and see what the difference might be?

It was my first step!
Here is NPM proxy config for [gitea](https://gist.github.com/mmBesar/8178048af30b28b68ce589f4c203e36c) and NPM [proxy.conf](https://gist.github.com/mmBesar/175b7785948c1fdfaeb5c04d5a129481).
These are working configs, which I have copied to my Nginx, but It didn't work!

**Comment by mmBesar** [comment]
Please, I need to know, did anyone use Nginx successfully with Gitea's docker registry!
I did follow the official documentation with no luck at all!
And why is this issue marked as `needs-feedback`? What else can share?

**Comment by wxiaoguang** [comment]
> Please, I need to know, did anyone use Nginx successfully with Gitea's docker registry!

Yes, nginx works with Gitea docker registry.

And you see Ngixn PM config also works, so that's your manually written config's problem.

>  I did follow the official documentation with no luck at all!

I don't see so, "Here is NPM proxy config for [gitea](https://gist.github.com/mmBesar/8178048af30b28b68ce589f4c203e36c)" : What's your included config? What's the full `nginx -T`? There must be something wrong.

>  And why is this issue marked as needs-feedback? What else can I share?

Because it's really not related to Gitea. At least, you can first copy your full Nginx PM , and remove unnecessary config line by line, until the remaining lines are all necessary.

**Comment by mmBesar** [comment]
> And you see Ngixn PM config also works, so that's your manually written config's problem.

All I did is add the proxy config, nothing special. And I did share it all!

> I don't see so, "Here is NPM proxy config for [gitea](https://gist.github.com/mmBesar/8178048af30b28b68ce589f4c203e36c)" : What's your included config? What's the full `nginx -T`? There must be something wrong.

This for a working NPM config! And I did share "NPM [proxy.conf](https://gist.github.com/mmBesar/175b7785948c1fdfaeb5c04d5a129481)." My problem is with Nginx which I've shared everything about it including the full `nginx -T`

> Because it's really not related to Gitea. At least, you can first copy your full Nginx PM , and remove unnecessary config line by line, until the remaining lines are all necessary.

I understand it's Nginx not Gitea, but I'm using pure Nginx from a well-known image "linuxserver/nginx", and I did follow the Gitea Guide! And shared everything asked. NPM should not be the standard, Pure Nginx should!

I'm trying to understand what is the problem, and I'll keep searching and share it all here.

I love Gitea as it's a great project, thank you.

**Comment by mmBesar** [comment]
@nephatrine Thank you for sharing, I will try your config, but what Nginx image are you using? If it's the official one, which tag?

**Comment by mmBesar** [comment]
Finally, solved!
All I've done is add `listen 443 ssl http2;` to Gitea proxy config! And it works just fine, even though I'm not using SSL!
Thank you all, Love this project.
