### ISSUE TITLE
gitea restore dump

### ISSUE THREAD

**Issue by MasterDimmy** [go-gitea/gitea#2405]
We need ability to do:
1. gitea restore dump
2. automatic updates via apt-get update \ upgrade

**Comment by lunny** [comment]
1. duplicated with #1292
2. this work is on progress from debian, see https://github.com/MTecknology/gitea-wip

**Comment by strk** [comment]
apt-get is being taken care of by @MTecknology, better keep
this ticket just for the `restore` command (if it's not
a duplicated already)

**Comment by strk** [comment]
Looks like ticket for restore already exists: #1637
Close as duplicated ?

**Comment by MasterDimmy** [comment]
>https://github.com/MTecknology/gitea-wip/blob/master/work_in_progress

didnt find any word about "apt-get update" or something.
Just dont forget about it.

**Comment by MTecknology** [comment]
@MasterDimmy That [WIP](https://github.com/MTecknology/gitea-wip/blob/master/work_in_progress) is for the relevant [Debian ITP](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=792101).

**Comment by MetaiR** [comment]
any progress?

**Comment by mrsdizzie** [comment]
Closing as restore command exists and we don't have the power to put Gitea into upstream Debian release (and there are many reasons listed on the linked report why it isn't easy/possible -- mainly that all of the proper dependencies will never be packaged/kept up to date in a way that works).

#31 includes discussion on making a .deb build and some people have linked to ones they have created/maintain

**Comment by 6543** [comment]
there are ways to install gitea via package mangager: https://docs.gitea.io/en-us/install-from-package/
