### ISSUE TITLE
error deprecat argment check

### ISSUE THREAD

**Issue by blue-bird1** [go-gitea/gitea#24057]
### Description

in [code](https://github.com/go-gitea/gitea/blob/25faee3c5f5be23c99b3b7e50418fc0dbad7a41b/routers/api/v1/repo/release.go#L154).
because convert.ToCorrectPageSize, listOptions.PageSize never is 0

### Gitea Version

aa4d1d94f79e8edd9fa9ff2813fea12b085b2cae

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

make && /gitea web

### Database

None

**Comment by blue-bird1** [comment]
It's a lucky bug. It found in my codeql query。 
It lost the size check, but never entered this branch

**Comment by lunny** [comment]
It's not a bug, it's a useless code.
