### ISSUE TITLE
Browser warnings related to `macaron_flash` cookie

### ISSUE THREAD

**Issue by silverwind** [go-gitea/gitea#24062]
### Description

I observe these during development in Firefox, I think we should somehow fix these:

<img width="1276" alt="image" src="https://user-images.githubusercontent.com/115237/231251051-fa8419d2-b8d8-4770-a26e-47e13cb45298.png">

### Gitea Version

main

### Can you reproduce the bug on the Gitea demo site?

Yes

**Comment by pierre-eliep-met** [comment]
I get the same warning, and additionnaly I can't create a Pull request on my project, don't know if it is related

**Comment by wxiaoguang** [comment]
The cookie problem: the `FlashMessage` code keeps sending "deleting cookie" header to browsers.

Eventually ....  Refactor cookie #24107   because the old cookie code doesn't look good to me and has bugs .....
