### ISSUE TITLE
 CORS policy：Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource

### ISSUE THREAD

**Issue by yyy19961027** [go-gitea/gitea#24067]
### Description

I set up a gitea environment in Docker, and there was a cross domain issue when Ajax requested the gitea interface in the browser. As shown in the figure below, how should I configure to solve cross domain problems.

![docker](https://user-images.githubusercontent.com/66300848/231336127-4829f37c-e703-4454-b1b5-22e3d429313b.png)
![config](https://user-images.githubusercontent.com/66300848/231336138-08e81656-4663-4b1d-b1fd-f87469b4382e.png)

### Screenshots

![error](https://user-images.githubusercontent.com/66300848/231337510-405e3f82-0fd2-49b5-adfe-e1e25cc6d7c0.png)

### Gitea Version

 1.20.0+

### Can you reproduce the bug on the Gitea demo site?

Yes

### Browser Version

chrome 111.0.5563.147（正式版本） （64 位）

**Comment by wxiaoguang** [comment]
https://github.com/go-gitea/gitea/blob/main/custom/conf/app.example.ini

![image](https://user-images.githubusercontent.com/2114189/231382393-4e6004f5-8021-4b58-a681-d6cf0cbd711d.png)

**Comment by wxiaoguang** [comment]
> I have configured this parameter

I didn't see so

<img width="459" alt="image" src="https://user-images.githubusercontent.com/2114189/231404383-1c2fd8c2-2c9a-4c09-aed6-add3ce37a73d.png">

**Comment by yyy19961027** [comment]
![cors_config](https://user-images.githubusercontent.com/66300848/232373234-e7d42dbe-ef15-466d-838a-5c903b2246a5.png)

**Comment by wxiaoguang** [comment]
I still didn't see so.

Where is your `D`?

![image](https://user-images.githubusercontent.com/2114189/232373625-ed91ee29-a218-41be-84a3-276e5323a3b1.png)

**Comment by yyy19961027** [comment]
I have configured it to false, but there is still a cross domain issue. Is there anything else that needs to be configured

![config_cors](https://user-images.githubusercontent.com/66300848/232406339-12bbbcfb-cb85-4a4d-b5cf-0c241486d4d6.png)

**Comment by wxiaoguang** [comment]
Are you serious?

I would strongly suggest you to read the materials carefully line by line, before asking ........

1. Do you want to enable CORS? Then why not set it to false?  You should set it to true
2. Why you wrote "ENABLE"? The document says "ENABLED", I have highlighted that line not only once.

**Comment by yyy19961027** [comment]
Sorry, I didn't see your description at the beginning. Now that I have configured the correct parameters as you mentioned, there is still a cross domain issue. May I ask if you are Chinese? If so, we will communicate in Chinese.
![config_cors](https://user-images.githubusercontent.com/66300848/232409131-b10a983a-8bee-423a-99a2-5a1b40104194.png)
