### ISSUE TITLE
Custom mail templates not working

### ISSUE THREAD

**Issue by dsvictory** [go-gitea/gitea#24075]
### Description

Hello, again! :)

All mail templates register after launching without any problems in logs but built-in templates are always used.

Can anyone just confirm, please, that mail templates work for him on Windows?

This will at least give information that I should try to pick this topic further. Maybe this functionality does not work on Windows? Or maybe this feature has not been working long time and nobody uses it?

This link to my previous issue.
https://github.com/go-gitea/gitea/issues/23873#issue-1650948574

### Gitea Version

1.19.0

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

2.24.1.windows.2

### Operating System

Windows Server 2016 (v. 1607 build 14393.5648)

### How are you running Gitea?

As Windows Service or just launching .exe itself. Result is the same.

### Database

MSSQL

**Comment by wxiaoguang** [comment]
It's a bug in 1.19. 1.20 has fixed it.

I will try to fix it in 1.19

**Comment by wxiaoguang** [comment]
The fix has been merged https://github.com/go-gitea/gitea/pull/24081

Could you try to get the latest build from https://dl.gitea.com/gitea/1.19/ to see whether the fix works for you?

If there is still any problem, I would need to get a Windows computer to continue debugging.

**Comment by dsvictory** [comment]
Mail templates work now. Thank you so much!!! Nice to work with you. :)
