### ISSUE TITLE
Make it more obvious what license a repo is using

### ISSUE THREAD

**Issue by RealFascinated** [go-gitea/gitea#24076]
### Feature Description

Adding a ui element to show what license the repo is using eg: MIT

**Comment by silverwind** [comment]
License detection is complicated, requires heuristics and because of this, it'll never deliver perfect results unless the programming community as a whole standardizes on a format, which also won't happen.

**Comment by jolheiser** [comment]
In case someone is interested at looking in to this:

https://licensee.github.io/licensee/#the-solution
(and for that last part, https://github.com/adrg/strutil#sorensen-dice)

**Comment by jellykells** [comment]
As I suggested in #12905, license detection doesn't need to be implemented for this feature, even though it would be nice to have

**Comment by delvh** [comment]
Ah, you mean that a repo can set itself what license it uses, i.e. in the settings?

**Comment by jellykells** [comment]
> Ah, you mean that a repo can set itself what license it uses, i.e. in the settings?

Yes exactly

**Comment by silverwind** [comment]
I don't see a manual license setting as a solution. Other forges do auto-detection, so we are kind of forced to do too. This also avoids a potential mismatch problem between a manually set license and a different one via `LICENSE` file (or other means like package.json).

**Comment by jellykells** [comment]
> I don't see a manual license setting as a solution. Other forges do auto-detection, so we are kind of forced to do too. This also avoids a potential mismatch problem between a manually set license and a different one via `LICENSE` file (or other means like package.json).

If auto-detection is ever enabled a manual override will almost certainly be necessary in cases of potential mismatch or misdetection anyway, so I think the manual selection might as well be implemented first since it does not rely any new dependencies.

Also as an aside, I don't think what other code forges do should force Gitea to do anything. Gitea should forge (pun intentional) its own path and cater to its own users.

**Comment by silverwind** [comment]
https://github.com/go-enry/go-license-detector looks like something that might work as a start.

**Comment by jellykells** [comment]
> Other forges are having automation so we have to have too. Imagine you have hundrets of repos to migrate between forges, you don't want to manually set their licenses on each of them. If such a topic is important to you, you might even end up not choosing gitea because of the lack of automatism.

Gitea has no license detection currently, meaning those users are out of luck anyway, but if adding a license detector is on someone's roadmap then great!

Another Github-specific option is to just use the existing API to retrieve the license for a repo during migration.

**Comment by andreashaerter** [comment]
> License detection is complicated, requires heuristics and because of this, it'll never deliver perfect results unless the programming community as a whole standardizes on a format, which also won't happen.

Just as a side-note: https://reuse.software/ by the FSFE is a cool project to fix this and >70% of e.g. the Linux kernel is already on boat.
