### ISSUE TITLE
`on_date` translation is problematic

### ISSUE THREAD

**Issue by silverwind** [go-gitea/gitea#24074]
### Description

As seen on [Crowdin](https://crowdin.com/translate/gitea/68/enus-de?filter=basic&value=0#99755), translators have a hard time translating the `on` alone in `on <date>` phrases because some languages don't have a concept of such a word. We should evaluate if there are alternatives and whether we can somehow translate the whole phrase.

**Comment by yardenshoham** [comment]
Blocked by https://github.com/go-gitea/gitea/issues/23863?

**Comment by lunny** [comment]
> Blocked by #23863?

I don't think so.

**Comment by silverwind** [comment]
I think the solution will be to never have the time element emit this "on", and instead render it into the translation string via a token. I also checked the [JS Intl API](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat), it seems it also can not emit a "on", it can emit a "at", thought.

**Comment by yardenshoham** [comment]
One way to avoid `on` is to use `tense=past` whenever possible. Ref #24106

**Comment by wxiaoguang** [comment]
I would suggest to remove the `on` prefix from `TimeSince`, if it is not necessary. 

Is there a strong reason to keep it?

**Comment by silverwind** [comment]
In some contexts the on makes sense to form sentences, but it needs to be removed from `TimeSince` (and in turn `<relative-time>`), and these sentences should be formed based on a translation string `on %s`. where `%s` than renders the `TimeSince`.

**Comment by yardenshoham** [comment]
about the last sentence. Not `TimeSince`, an absolute datetime is more like `template "shared/datetime/short"`

**Comment by silverwind** [comment]
Though, the challenge ist that `<relative-time>` may or may not output the `on`, depending on how far back the date is. So I guess the backend must know as well when the `on` is supposed to appear to emit the correct translation.

**Comment by yardenshoham** [comment]
Threshold is configurable

**Comment by wxiaoguang** [comment]
Quote my comment from #24106

In history , IIRC the `TimeSince` always used relative date, then `<relative-time>` changed the behavior.

Now, we just make `<relative-time>` always use `tense=past`, then it behaves like the old `TimeSince` , then everything should be fine, and just like before.

Then we do not need the `on` either.

Correct me if I am wrong.

**Comment by yardenshoham** [comment]
If you use `template "shared/datetime/short"` it will just output the day, no `on`

**Comment by wxiaoguang** [comment]
New code:

```
<td>{{template "shared/datetime/short" (dict "Datetime" .CreatedUnix.FormatLong "Fallback" .CreatedUnix.FormatShort)}}</td>
```


Old code:

```
<td><span class="notice-created-time" data-tooltip-content="{{.CreatedUnix.AsTime}}"><time data-format="short-date" datetime="{{.CreatedUnix.FormatLong}}">{{.CreatedUnix.FormatShort}}</time></span></td>
```


There is no `on` in old code either. Since this problem couldn't be resolved easily, I would suggest to use the old code's behavior.

**Comment by yardenshoham** [comment]
I'm fine with `tense=past` by default, just have to be careful with future dates. @silverwind the problem with this is it will show `4 years ago` instead of `on April 14, 2019` which you prefer

**Comment by silverwind** [comment]
> Threshold is configurable

Then I think it's clear what needs to be done: Make backend aware of the threshold, and make it output a `on %s` translation string before the threshold and `%s` when not.

**Comment by yardenshoham** [comment]
The first should use `TimeSince` (`relative-time` with `format="relative"`). The second and third should be inserted into a phrase and use a function (we currently have `template "shared/datetime/short"` which is `relative-time` with `format="datetime"`)
