### ISSUE TITLE
Bug: Users authenticated via proxy-auth can change username

### ISSUE THREAD

**Issue by MTecknology** [go-gitea/gitea#2407]
In the current version of gitea, it is possible for users authenticated via proxy-auth to edit their username. I'm not able to find a config option to disable this. In cases where proxy authentication is being used, this allows users to change their username and orphan their repositories because a new userid will be immediately created with their correct user.

**Comment by bkcsoft** [comment]
I think in the case of proxy auth (or oauth/openid) we should disallow username changes.

**Comment by lafriks** [comment]
Only local users are allowed to change username and I don't think that somehow affects linked openid etc authorization that is handled otherwise and just links to account and are not authorization source

**Comment by ptman** [comment]
Yes, this is a problem
