### ISSUE TITLE
always api "rate limit" problem

### ISSUE THREAD

**Issue by StefanSa** [go-gitea/gitea#24102]
### Description

Hi there,
We want to migrate a project from gitea to gitlab via api / token.
However, we always get this error message and the migration is canceled.
```
172.13.31.74:38254 - testuser [13/Apr/2023:10:44:58 +0200] "GET /api/v1/rate_limit HTTP/1.1" 404 19 "\" \"Octokit Ruby Gem 4.25.1"
```
We have also once increased all api settings, but without success.
```
[api]
MAX_RESPONSE_ITEMS=1000
DEFAULT_PAGING_NUM=1000
DEFAULT_GIT_TREES_PER_PAGE=5000
```
What do we have to do to increase the `rate limit` for api ?

thx
Stefan

### Gitea Version

1.20.0+dev-166-g8e4063479 built with GNU Make 4.2.1, go1.20.1 : bindata, sqlite, sqlite_unlock_notify

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

openleap 15.4

### How are you running Gitea?

we have build gitea ourselves and it runs with systemd.

### Database

PostgreSQL

**Comment by KazzmanK** [comment]
Look like Gitea does not implement /api/v1/rate_limit 
Gitlab is calling this rest ? May be there is an option not calling it ?

**Comment by StefanSa** [comment]
@KazzmanK 

```
71.14.34.64:38254 - testuser [13/Apr/2023:10:44:58 +0200] "GET /api/v1/rate_limit HTTP/1.1" 404 19 "\" \"Octokit Ruby Gem 4.25.1"
71.14.34.64:38256 - testuser [13/Apr/2023:10:44:58 +0200] "GET /api/v1/user/repos HTTP/1.1" 403 107 "\" \"Octokit Ruby Gem 4.25.1"
```
These are the only logs i have on this.
The interesting thing is that there is an extra option to import "Gitea" at gitlab.

**Comment by a1012112796** [comment]
> We want to migrate a project from gitea to gitlab via api / token.

which tool you are using to migrate ?

**Comment by lunny** [comment]
> @KazzmanK
> 
> ```
> 71.14.34.64:38254 - testuser [13/Apr/2023:10:44:58 +0200] "GET /api/v1/rate_limit HTTP/1.1" 404 19 "\" \"Octokit Ruby Gem 4.25.1"
> 71.14.34.64:38256 - testuser [13/Apr/2023:10:44:58 +0200] "GET /api/v1/user/repos HTTP/1.1" 403 107 "\" \"Octokit Ruby Gem 4.25.1"
> ```
> 
> These are the only logs i have on this. The interesting thing is that there is an extra option to import "Gitea" at gitlab.

If you are using a tool GitLab integrated, maybe you can find their documentations or get help from them. As @KazzmanK said, Gitea hasn't implemented an API rate limit.

**Comment by lunny** [comment]
per the discuss I think this could be closed.
