### ISSUE TITLE
Nested 500 page inside a page

### ISSUE THREAD

**Issue by HesterG** [go-gitea/gitea#24104]
### Description

The position of 500 error might be incorrect if an error occurs inside a nested template. In the example below, the error occurs in line 694 of [`comments.tmpl`](https://github.com/go-gitea/gitea/blob/2b749af50508a28c7088e7d76132c27f96a45789/templates/repo/issue/view_content/comments.tmpl#L694), and this 500 error page was nested around this place where the error occurs.

https://user-images.githubusercontent.com/17645053/231715112-e151b595-d5e2-4344-a059-64671e359d99.mov

Steps to reproduce:

1. Create a team under an organization with the following settings

<img width="1126" alt="截屏2023-04-13 17 27 11" src="https://user-images.githubusercontent.com/17645053/231716531-a31155d7-b55b-4ae8-a45d-a7cb71f6b892.png">

2. Open a pull request and assign the team as the reviewer.

<img width="313" alt="截屏2023-04-13 17 32 27" src="https://user-images.githubusercontent.com/17645053/231718166-4495b00a-d8ec-4973-9784-0cc5a8d1a4eb.png">

3. Delete this team.
4. Go back to the pull request where this team was formerly assigned.

And the following JS error occurs because when the 500 error page is nested, there will be two `head_script.tmpl` with `webcomponents.js` imported twice. This error will be fixed if 500 page is not nested. 

<img width="1218" alt="截屏2023-04-13 17 47 40" src="https://user-images.githubusercontent.com/17645053/231722468-2c9c9ca2-d27f-47d1-81be-fed74fa7f0d4.png">

### Gitea Version

latest

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

On macOS:
```
TAGS="bindata sqlite sqlite_unlock_notify" make build
./gitea
```

### Database

None

**Comment by HesterG** [comment]
Did some check, and I think the issue might come from [somewhere around here](https://github.com/go-gitea/gitea/blob/2b749af50508a28c7088e7d76132c27f96a45789/modules/templates/htmlrenderer.go#L48), but not very sure.

**Comment by sillyguodong** [comment]
Internal server error is related to https://github.com/go-gitea/gitea/issues/23738#issuecomment-1506627030

**Comment by sillyguodong** [comment]
> The duplicate `<head><script>` is caused by backend/template errors. As long as there is no backend error, then there won't be JS error.

got it, i will fix the backend error.
close this issue?

**Comment by wxiaoguang** [comment]
Show friendly 500 error page to users and developers #24110 

This PR will help you.
