### ISSUE TITLE
Possibility do disable commit message issue number referencing

### ISSUE THREAD

**Issue by Mosch0512** [go-gitea/gitea#24103]
### Feature Description

It would be nice to be able to disable commit message referencing for issue numbers.

The problem i have is that i got a very long refernece list in my issue comments due to frequent changes. I think thats is mostly caused by force push though.

What could be done is removing alld references that arent appropiate anymore and replace them with the new ones.
![grafik](https://user-images.githubusercontent.com/48485443/231716774-f3a933ab-d9c0-41d9-a9a3-adae087df67e.png)

**Comment by wxiaoguang** [comment]
Does this help?


![image](https://user-images.githubusercontent.com/2114189/231835287-39657c32-66cc-4dec-9ce7-461e154b42ac.png)

**Comment by Mosch0512** [comment]
In which version was that included? I can not see that. have to w8 for my superviser.

**Comment by wxiaoguang** [comment]
1.17

* https://github.com/go-gitea/gitea/pull/17414

**Comment by Mosch0512** [comment]
Thx @wxiaoguang
