### ISSUE TITLE
Disable password autofill entirely with configuration flag

### ISSUE THREAD

**Issue by brodeuralexis** [go-gitea/gitea#24112]
### Feature Description

Gitea should expose a configuration flag like `PASSWORD_AUTOFILL` in the *security* section to prevent autofilling of password fields throughout the application.  This means that every `input[type="password"]` element will receive or modify its `autocomplete` attribute to be `"off"`. 

While an extreme security measure and not an issue with Gitea itself, it is sometimes required by companies, as all passwords saved by the browser can be leaked if the computer is compromised, or if the computer is shared by multiple people.

**Comment by wxiaoguang** [comment]
It doesn't work .......... Chrome does bad on this problem.

There are a lot of comments here: https://github.com/go-gitea/gitea/blob/main/templates/base/disable_form_autofill.tmpl


If the  `autocomplete=off` works for you, welcome to share your experience.

**Comment by MikeyG731** [comment]
In a situation where this is being required by the company. Hopefully this gains some traction.

**Comment by techknowlogick** [comment]
Thanks for opening this ticket, as @wxiaoguang this isn't really achievable via front end. I suggest you look into group policies to disable. I'll close this now.
