### ISSUE TITLE
Gitea v1.2 on dl.gitea.io

### ISSUE THREAD

**Issue by sentabi** [go-gitea/gitea#2412]
I saw Gitea 1.2 already on https://dl.gitea.io/gitea/ but on release page https://github.com/go-gitea/gitea/releases there's only 1.2-rc1

It's a bug on build system ?

**Comment by lafriks** [comment]
folder `x.y` is for version of that release not counting minor version number. so in folder 1.1 will be same as 1.1.3 currently etc. It could probably be improved not to include rc versions there

**Comment by lunny** [comment]
Maybe this should be a question label not kind/enhancement.

**Comment by bkcsoft** [comment]
This is definitively a build bug. Since we have both `1.2/gitea-1.2-linux-amd64` and `1.2.0-rc1/gitea-1.2.0-rc1-linux-amd64` 🙄

**Comment by bkcsoft** [comment]
This is definitively a build bug. Since we have both `1.2/gitea-1.2-linux-amd64` and `1.2.0-rc1/gitea-1.2.0-rc1-linux-amd64` 🙄

**Comment by lafriks** [comment]
@bkcsoft it's not really bug it is latest version from 1.2 branch

**Comment by sentabi** [comment]
@lafriks we have https://dl.gitea.io/gitea/1.2/gitea-1.2-linux-amd64. 
It's the latest branch, but which one? The stable/RC or anything else, from the folder or file name itself it's not clear.

**Comment by lafriks** [comment]
It is the latest version of 1.2 branch and currently it is 1.2.0-rc1

**Comment by lunny** [comment]
maybe we should rename `1.2` to `release/v1.2` to match the branch name.

**Comment by lafriks** [comment]
I don't think it's needed

**Comment by techknowlogick** [comment]
Can this ticket be closed?
