### ISSUE TITLE
Raw ISO date time displayed instead of relative time

### ISSUE THREAD

**Issue by bagasme** [go-gitea/gitea#24122]
### Description

I built Gitea from source on Debian 11 using Go 1.20.3 and Node v18.13.0 (npm 8.19.3). Yesterday I built commit 4299c3b7db61f8741eca0ba3d663bb65745a4acc. Before building, I wiped out `node_modules` directory (as it contains node artifacts). Then I built as usual and deployed to my Gitea instance on LXD container. Previous commit deployed to the instance before the rebuild was commit 57aab79b0d. No `app.ini` changes between deployments.

The Gitea instance uses PostgreSQL 15.2 on another container.

When I logged in to the instance, I noticed that raw ISO 8601 date time format was displayed instead of usual relative time (e.g. `12 minutes ago`) when I browse my repos and also on the dashboard.

I have tried reproducing on try.gitea.io but the issue doesn't occur (as it was deployed from commit 334c899f7) so either I have issues on my `app.ini` or this issue had been fixed in more recent commits than I deployed.

Here are [gitea.log from my instance](https://gist.github.com/bagasme/e8fb7bfeeb695c7dcb886fd83bb0c2aa) and [sanitized config](https://gist.github.com/bagasme/7ff9eb712e0cdce344dd89a355975693).

### Screenshots

# On the production
![Recent Gitea repo push on the dashboard](https://user-images.githubusercontent.com/40219486/231931892-e32280ab-31fd-49d7-95b0-a3ae0985e2bd.png)
![Tree of internal site sources](https://user-images.githubusercontent.com/40219486/231932372-e752e34f-af32-4c11-86c5-f033cf71234c.png)

# On try.gitea.io
![Testing repo tree](https://user-images.githubusercontent.com/40219486/231932835-1dc16683-6e88-4878-b791-bed708c48ab9.png)
![Recent testing repo push on the dashboard](https://user-images.githubusercontent.com/40219486/231932948-fa1e7ab9-1b29-4d0a-bef9-e28bac99e9ca.png)

### Gitea Version

main (commit 4299c3b7db61f8741eca0ba3d663bb65745a4acc)

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

Ubuntu 22.04

### Browser Version

Firefox Developer Edition (113.0.b2)

**Comment by wxiaoguang** [comment]
The relative-time is related to #23988  (which still has some open issues/PRs)

For the file list, I guess it's related to #24106 @yardenshoham

**Comment by yardenshoham** [comment]
@bagasme does https://github.com/github/relative-time-element work in your browser? Does https://github.github.io/relative-time-element/examples/ render for you?

@wxiaoguang do we polyfill the JS.Intl APIs?

**Comment by yardenshoham** [comment]
I was able to reproduce:
![image](https://user-images.githubusercontent.com/20454870/232000272-7841eb57-e9dc-40f7-a517-87a0a536f941.png)

I did it by compiling webpack without `@github/relative-time-element`:
![image](https://user-images.githubusercontent.com/20454870/232000900-be8ea742-680e-4cd4-8fe9-35d0095d5ce9.png)


Please make sure you have that package in `node_modules`

**Comment by delvh** [comment]
Can this issue be closed then?

**Comment by yardenshoham** [comment]
Let's make sure @bagasme fixed their issue

**Comment by bagasme** [comment]
Issue fixed by checking `node_modules` to contain appropriate module as @yardenshoham said. Closing.
