### ISSUE TITLE
[FEAT] + View MarkMap [Solved]

### ISSUE THREAD

**Issue by editfund-founder** [go-gitea/gitea#24139]
### Needs and benefits
- mindmaps of My Stars
- mindmaps of Repos | ["My repositories" sorting](https://codeberg.org/gitnex/GitNex/issues/1266)
- mindmaps of Issues
- mindmaps of misc

### Feature Description
```diff
...
View Source
- View Rendered
+ View Rendered
+ View MarkMap
Raw
Permalink
...
```

### Screenshots

![Visualize your Markdown as mindmaps with Markmap](https://user-images.githubusercontent.com/61936162/232204477-d0ba3306-9d3f-46a0-a669-4c804eace03b.jpg)

### References & Solutions
- https://markmap.js.org/repl
- https://docs.gitea.com/administration/external-renderers
- https://discourse.gitea.io/t/how-to-render-jupyter-notebooks-on-gitea-blog/5134/2
- https://blog.gitea.io/2022/04/how-to-render-jupyter-notebooks-on-gitea/
- https://github.com/go-gitea/gitea/pull/19017
- 
view_file.tmpl
```diff
			{{if .HasSourceRenderedToggle}}
				<div class="ui compact icon buttons two-toggle-buttons">
					<a href="{{$.Link}}?display=source" class="ui mini basic button tooltip {{if .IsDisplayingSource}}active{{end}}" data-content="{{.locale.Tr "repo.file_view_source"}}" data-position="bottom center">{{svg "octicon-code" 15}}</a>
					<a href="{{$.Link}}" class="ui mini basic button tooltip {{if .IsDisplayingRendered}}active{{end}}" data-content="{{.locale.Tr "repo.file_view_rendered"}}" data-position="bottom center">{{svg "octicon-file" 15}}</a>
+					<a href='{{AppSubUrl}}/assets/API-Editor/index.html?{{AppSubUrl}}{{$.RawFileLink}}' class="ui mini basic button">{{svg "octicon-eye" 15}}</a>
				</div>
			{{end}}
			{{if not .ReadmeInList}}

```
![实现了外接“文件查看与编辑”](https://user-images.githubusercontent.com/61936162/232601063-8d99868b-95a6-4493-9cfb-9e59a013ba9f.jpg)

![跳转到了“第三方编辑器”](https://user-images.githubusercontent.com/61936162/232619724-129d0ff8-1eb6-41e7-acc7-1cc9cf4ca0a1.jpg)

**Comment by delvh** [comment]
I don't quite see the benefit of this proposal:
Why would I want a mindmap of my markdown?
To me, this simply seems like unnecessary bloat, unless you can give me **a really good reason** why it isn't…
