### ISSUE TITLE
exec: "git": executable file not found in %PATH%

### ISSUE THREAD

**Issue by toolgood** [go-gitea/gitea#24135]
### Gitea Version

1.19.1

### Can you reproduce the bug on the Gitea demo site?

Yes

### Git Version

Git-2.40.0-64-bit

### How are you running Gitea?

无法识别 'git' 命令：exec: "git": executable file not found in %PATH%

![图片](https://user-images.githubusercontent.com/17310407/232180038-78214402-3201-4217-8b28-3a35890879f8.png)

![图片](https://user-images.githubusercontent.com/17310407/232179987-a638ecb9-4645-480f-9c44-43e85e1e167e.png)

![图片](https://user-images.githubusercontent.com/17310407/232180000-2a4b9e71-94ad-49e3-949c-3511eb38da35.png)

### Database

SQLite

**Comment by wxiaoguang** [comment]
1. Can you run "git" in your "cmd" window?
2. Windows has two PATHs: one is user setting, one is system setting.
3. If you can't figure out the PATH environment, you can set the git path in `app.ini` manually.

https://github.com/go-gitea/gitea/blob/35e562d7bd5e984a5cb97f74f5753d2a9998c1d3/custom/conf/app.example.ini#L681-L686

**Comment by toolgood** [comment]
![图片](https://user-images.githubusercontent.com/17310407/232183239-56e9a013-e26b-4044-acaf-a2dfe5ffc7b4.png)

**Comment by eeyrjmr** [comment]
what user is gitea being executed as? does that used have git in its %PATH% variable

**Comment by toolgood** [comment]
Not resolved, but copied data from other computers to run.

**Comment by techknowlogick** [comment]
Could you try setting `[git] PATH=""` to the exact path to the git binary?
docs here: https://docs.gitea.io/en-us/config-cheat-sheet/#git-git`

**Comment by wxiaoguang** [comment]
I am pretty sure it's a config problem.

It depends how the author runs Gitea (as current user or as service), and Windows has 2 PATH settings: one for current user, one for global (all users).

I guess the author has succeeded running Gitea on another server, instead of changing the global PATH or changing the `[git].PATH` in app.ini.

**Comment by toolgood** [comment]
After the prompt, the 'custom/conf/app. ini' configuration file was not generated.

**Comment by wxiaoguang** [comment]
Yes, because there are errors. You need to write the config to your `app.ini` manually if your system default values do not work.

**Comment by toolgood** [comment]
It's a bit strange that I generate data on my own computer, copy it to the server, and it runs normally without having to set `[git]` in the `app.ini` file .

**Comment by toolgood** [comment]
No git path
