### ISSUE TITLE
app.ini configuration being overwritten in kubernetes with Persistent Volume

### ISSUE THREAD

**Issue by warent** [go-gitea/gitea#24146]
### Description

I'm running Gitea using a Kubernetes cluster setup with minikube. The cluster has a Persistent Volume defined with all of the Gitea data. Everything successfully persists between destruction and recreation of the containers, including repositories, configurations, etc.

Yet for some reason despite this, when the Gitea pod is being created, it ignores the existing app.ini file and overwrites it. All custom configuration is deleted. Nothing else seems to be overwritten or deleted.

### Gitea Version

1.17.4

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

Initialized using Gitea Helm on Minikube

### Database

PostgreSQL

**Comment by wxiaoguang** [comment]
1.17 is outdated, the latest stable is 1.19

I guess the problem is that your `app.ini` is not shared across different instances?

**Comment by warent** [comment]
They all mount a volume to the same filesystem with the same app.ini, and there is only one running Gitea instance at a time

**Comment by wxiaoguang** [comment]
If Gitea runs with an existing app.ini, it won't/shouldn't overwrite it.

Can you provide detailed steps / a reproduce setup?

**Comment by wxiaoguang** [comment]
1.20/1.21 has a big refactoring for the config system. Now, in most cases, the app.ini won't be written 

Feel free to provide reproducible steps if there is still a problem.
