### ISSUE TITLE
"Packages" do not inherit "storage" configuration 

### ISSUE THREAD

**Issue by pat-s** [go-gitea/gitea#24142]
### Description

`lfs`, `attachments` and `avatars` inherit the configuration from `storage` automatically. This is described in https://docs.gitea.io/en-us/config-cheat-sheet/#storage-storage.

It reads also as if `packages` would do so as the section ends with "[...] etc.". Yet `packages` doesn't and one needs to explicitly set

```
    "storage.packages":
      STORAGE_TYPE: minio
```

in `app.ini` to be able to store packages in `minio` or similar.

This has already been asked in https://github.com/go-gitea/gitea/issues/21300 but the point whether this is desired this way or a bug has not been addressed.
Hence I am not sure whether label this as a "bug" or a "feature request" but it looks to me as if `packages` should inherit from `storage` in the same way as `lfs`, `attachments` and `avatars` already do?

In addition, in the documentation at https://docs.gitea.io/en-us/config-cheat-sheet/#packages-packages `STORAGE_TYPE` is not even listed for `packages`, which is another reason to assume that it inherits from `storage`. 
Maybe it might also be worth adding `STORAGE_TYPE` to the `PACKAGES` section as a parameter to make it more clear?

### Gitea Version

1.19.1

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

Kubernetes

### Database

None

**Comment by lunny** [comment]
I think #23911 should also fix this problem.
