### ISSUE TITLE
try.gitea.io certificate expired

### ISSUE THREAD

**Issue by ianw** [go-gitea/gitea#24158]
### Description

Hello,

In trying to replicate something for another bug report, I found the certificate for try.gitea.io expired on Sun, 16 Apr 2023 09:23:44 GMT.  It's now 17 Apr 01:29 GMT so I'm guessing if there is an automatic renewal it might have gone wrong.

### Gitea Version

1.19.1

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

Upstream site

### Database

None

**Comment by techknowlogick** [comment]
Thanks, I've renewed it and we're now using caddy on that server so it doesn't happen again :)
