### ISSUE TITLE
Require Sign In View doesnt work

### ISSUE THREAD

**Issue by kifirkin** [go-gitea/gitea#2416]
- Gitea version (or commit ref):
  -  1.2.0+rc1-3-g1cbe502
- Git version:
  - 2.11.0
- Operating system:
  - Debian GNU/Linux 9 (stretch)
  - Linux 4.9.0-3-amd64
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
If I set up Require Sign In View to true, then I can still view public repos, orgs and users from incognito browser window

**Comment by lunny** [comment]
have you restart your gitea service?

**Comment by kifirkin** [comment]
No :sweat_smile:
Thaaanks @lunny, it works after restart! 

Could be this requirement documented?

**Comment by lunny** [comment]
Maybe we need to add some word on https://docs.gitea.io/en-us/config-cheat-sheet/
