### ISSUE TITLE
Add to this repo's topics: `git-server`

### ISSUE THREAD

**Issue by mrienstra** [go-gitea/gitea#24163]
Perhaps the topics for this repo ought to include [git-server](https://github.com/topics/git-server) (used by 53 repos). ([instructions](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics))

Some other topics that may fit:
- [gitserver](https://github.com/topics/gitserver) (used by 15 repos)
- [git-gui](https://github.com/topics/git-gui) (used by 25 repos)
- [git-ui](https://github.com/topics/git-ui) (used by 12 repos)
- [git-server-docker](https://github.com/topics/git-server-docker) (used by 7 repos)
- [git-collaboration](https://github.com/topics/git-collaboration) (used by 4 repos)

Dubious:
- [docker-git](https://github.com/topics/docker-git) (used by 3 repos)
- [git-frontend](https://github.com/topics/git-frontend) (used by 1 repos)
- [git-front-end](https://github.com/topics/git-front-end) (not in use)
- [git-collaboration](https://github.com/topics/git-collaboration) (used by 4 repos)
- [github-clone](https://github.com/topics/github-clone) (used by 27 repos)
- [github-frontend-clone](https://github.com/topics/github-frontend-clone) (used by 1 repos)
- [private-repository](https://github.com/topics/private-repository) (used by 88 repos)
- [git-manager](https://github.com/topics/git-manager) (used by 4 repos)
- [git-management](https://github.com/topics/git-management) (used by 8 repos)
- [git-remote](https://github.com/topics/git-remote) (used by 14 repos)
- [git-repo](https://github.com/topics/git-repo) (used by 27 repos)

---

For future reference, the topics currently associated with this repo are:
- [github](https://github.com/topics/github)
- [git](https://github.com/topics/git)
- [go](https://github.com/topics/go)
- [golang](https://github.com/topics/golang)
- [devops](https://github.com/topics/devops)
- [gitlab](https://github.com/topics/gitlab)
- [gogs](https://github.com/topics/gogs)
- [gitea](https://github.com/topics/gitea)
- [hacktoberfest](https://github.com/topics/hacktoberfest)

**Comment by delvh** [comment]
Looks like the only people who can change the topics are @go-gitea/technical-oversight-committee…

**Comment by lunny** [comment]
I added `git-server`, `git-gui`, `github-clone`.

**Comment by yardenshoham** [comment]
We have stuff GitHub doesn't but yeah

**Comment by lunny** [comment]
> We have stuff GitHub doesn't but yeah

I think it's just a marketing word, there is no too much meaning. :) Gitea have many features GitHub does not have and will have more in future.
