### ISSUE TITLE
404 error when Pull to repo with 'pull requests' disabled

### ISSUE THREAD

**Issue by barzog** [go-gitea/gitea#24165]
### Description

When we fork repo - forked repo is created with 'pull request' repo setting enabled. Old repo 'pull request' setting is left untouched. When we trying to create pull request from new repo to old repo we receive 404 'Not found' error if 'pull request' setting is disabled in old repo settings. More informative message is needed, or (more better) only repos with 'pull requests' enabled should shown in 'merge into' drop-down list.

### Gitea Version

1.19.1

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![image](https://user-images.githubusercontent.com/11497626/232467800-41aa1f93-8db6-44bd-a62d-2d7ead020de9.png)

### Operating System

Flatcar

### How are you running Gitea?

Kubernetes helm-chart on k3s running on flatcar linux.

### Database

PostgreSQL

**Comment by barzog** [comment]
This may be even better (but I think that fork button should be shown anyway, but either in 'grayed' state - to show end-user that functionality is there but disabled or in 'normal' state with warning that 'you should enable PR on this repo beforehand.

**Comment by silverwind** [comment]
> So should we allow repo to be forked if pull request siabled? 🤔

Absolutely not. Not all forks are for the purpose as a sourcs of pull requests, they might become separate projects etc.
