### ISSUE TITLE
Pull request approvals

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#2417]
A repository could set every pull request needs at least some approvals before it merged.

**Comment by mmarif4u** [comment]
A very useful feature if implemented.

**Comment by lunny** [comment]
duplicated with #2794

**Comment by AragurDEV** [comment]
@lunny I think this isn't a duplicate anymore.  
Because #2794 got resolved but a "required approvals"-system isn't implemented yet.

**Comment by lunny** [comment]
@AragurDEV right and we opened another one see https://github.com/go-gitea/gitea/issues/5251 and there is already a PR #5350 to fix that.
