### ISSUE TITLE
Add repository counter badge like GitHub

### ISSUE THREAD

**Issue by jakob30061** [go-gitea/gitea#24188]
### Feature Description

After searching for a similar issue, i only could find this one. https://github.com/go-gitea/gitea/issues/19327

I already added the necessary lines, but wasn't sure if a direct PR would be merged, because of this section in [CONTRIBUTING.md](https://github.com/go-gitea/gitea/blob/main/CONTRIBUTING.md#discuss-your-design)

Badge is only visible if a repo exists (like "Starred Repositories").
Badge for users and organizations (compare screenshots)

Can I add a PR?

### Screenshots

![image](https://user-images.githubusercontent.com/72307968/232821270-36eb6af9-eb1e-4804-8f80-7e02c174a73e.png)
![image](https://user-images.githubusercontent.com/72307968/232821325-857f5a3b-f9c5-4aa3-9e87-804aa52cd58e.png)

**Comment by yardenshoham** [comment]
open a PR

**Comment by yardenshoham** [comment]
make it gray like
![image](https://user-images.githubusercontent.com/20454870/232831265-48cceb91-f938-4d97-a53a-d1af6cf51258.png)

**Comment by jakob30061** [comment]
> make it gray like ![image](https://user-images.githubusercontent.com/20454870/232831265-48cceb91-f938-4d97-a53a-d1af6cf51258.png)

I'm going to change the color of "Starred Repositories" as well, the avoid ui inconsistency
![image](https://user-images.githubusercontent.com/72307968/233021056-27d2ed8a-f9f6-4611-9f12-ce3e931edc12.png)

**Comment by yardenshoham** [comment]
Yes, good idea

**Comment by jakob30061** [comment]
Thanks for the fast responses.

While testing my implementation, i found out that when switching tabs the badges (my new repo badge and the old starred repo badge as well) are shown for `/gitea_user?tab=stars`, `/gitea_user?tab=activity` and missing under `gitea_user/-/projects` and `gitea_user/-/packages`

The general layout changes a little bit, so maybe it was intentional. Should I include fixes for that as well in the PR?

![image](https://user-images.githubusercontent.com/72307968/233032282-f2e0cfd1-bc35-4c42-9e95-7db7993a6da3.png)

**Comment by yardenshoham** [comment]
I think you could do that in another PR. Keep PRs small

**Comment by jakob30061** [comment]
Thank you for your help @yardenshoham
