### ISSUE TITLE
Vertical overflow 

### ISSUE THREAD

**Issue by krzysztofjeziorny** [go-gitea/gitea#24182]
### Description

Setting css of a `.container` (in the site `footer`) and `.dashboard .dashboard-navbar` to `100vw` causes a vertical overflow in Firefox (v112). 

On Chrome(ium) it is mitigated with `overflow: overlay`, but it [isn't supported](https://caniuse.com/css-overflow-overlay) on Firefox yet.

On the demo site it is visible when creating a repo https://try.gitea.io/repo/create

Propsed change: removing the set width of 100vw on these classes eliminates the need of hacking the vertical overflow on the body (with `overflow-x: hidden;`).

### Screenshots

<img width="981" alt="Screenshot 2023-04-18 at 10 46 48" src="https://user-images.githubusercontent.com/872730/232730138-558af8a8-e966-4c2a-a01a-6bd36ac9af21.png">

### Gitea Version

1.19.1

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

MacOS 12.6.5

### Browser Version

112

**Comment by silverwind** [comment]
I do not see any scrollbars in https://try.gitea.io/repo/create with Firefox 112 on MacOS. What's your version/os?

**Comment by krzysztofjeziorny** [comment]
> ### Operating System
> 
> MacOS 12.6.5
> ### Browser Version
> 
> 112

Also in Firefox Developer Edition, 113.0b4, without extensions.

**Comment by krzysztofjeziorny** [comment]
Just had a thought: as it doesn't happen on my Debian/KDE Firefox installation, where the scrollbars are kind-of-nonexistent, I'll check that out:

<img width="408" alt="MacOS general settings - Show scroll bars" src="https://user-images.githubusercontent.com/872730/232754134-0993a9a9-e429-4309-8d48-81401918e66a.png">

And sure enough, when scrollbars are automatic, the layout is all right. When set to "Always", the overflow bug is now visible.

Should I create a PR with a layout fix?

**Comment by silverwind** [comment]
Ah, yes I see it as well with "always" scrollbars. Please open a PR so we can test/discuss further.

**Comment by krzysztofjeziorny** [comment]
@silverwind [Pushed](https://github.com/go-gitea/gitea/pull/24184). Thanks for taking a look at it!

**Comment by wxiaoguang** [comment]
Closed by  #24184
