### ISSUE TITLE
Attachments In Review Comment Break With Edit

### ISSUE THREAD

**Issue by kdumontnu** [go-gitea/gitea#24195]
### To Reproduce
- Submit a review on design review with image attachments (I've only verified paste from clipboard)
  - images will automatically be inlined in markdown
- Edit the comment and delete one of the images
- All of the image/attachment links break

It seems as if all of the attachments are deleted when the review is edited.

Related to: https://github.com/go-gitea/gitea/issues/23290 and https://github.com/go-gitea/gitea/issues/24196

### Gitea Version

1.18 and 1.20 (try.gitea)

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots
Paste some images (note: attachments aren't indicated)
<img width="778" alt="Screenshot 2023-04-18 at 2 42 28 PM" src="https://user-images.githubusercontent.com/12700993/232877241-074b1630-07cf-4f2d-acd2-442817272aef.png">
Edit the review comment
<img width="640" alt="Screenshot 2023-04-18 at 2 43 24 PM" src="https://user-images.githubusercontent.com/12700993/232877266-bb163429-d4af-4b78-85a9-a4e283e0d2d1.png">
<img width="636" alt="Screenshot 2023-04-18 at 2 43 39 PM" src="https://user-images.githubusercontent.com/12700993/232877276-c46e8656-7104-462c-bd16-8689304534a4.png">
<img width="645" alt="Screenshot 2023-04-18 at 2 43 52 PM" src="https://user-images.githubusercontent.com/12700993/232877292-13733f38-3ad1-49ef-8685-ea414b9e1dd0.png">
All attachments are broken
<img width="639" alt="Screenshot 2023-04-18 at 2 44 05 PM" src="https://user-images.githubusercontent.com/12700993/232877309-5d00d627-b90a-4851-b309-8c653beb9c53.png">

### How are you running Gitea?

https://try.gitea.io/kdumontnu/test/pulls/2

### Database

None

**Comment by jtran** [comment]
Until proper editing of attachments on reviews is implemented, would adding `ignore_attachments: true` to the request fix the issue?

**Comment by wxiaoguang** [comment]
Good catch, the "attachment removal" code was already quite buggy before (this bug is not the first time appearing....)

I guess we need to rewrite it.

I am working on it.

**Comment by wxiaoguang** [comment]
I guess this PR could fix the bug: Fix issue attachment handling #24202
