### ISSUE TITLE
Scroll bar bug on the list of modified PR files

### ISSUE THREAD

**Issue by MrVrops** [go-gitea/gitea#24201]
### Description

Hello,

I updated my Gitea server from 1.14 to 1.19, everything is fine except for the visualization of the modified files.

Indeed, I have a scrollbar but it only goes down a few CM instead of taking up the whole space (See screenshot).
It's quite constraining to view these files.

Do you know how to remedy this?

Thanks to everybody,

### Gitea Version

1.19

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

Windows 10

### Browser Version

Chrome 112.0.5615.121

**Comment by wxiaoguang** [comment]
It has been fixed in 1.19.1

**Comment by MrVrops** [comment]
Oh fine, thanks you
