### ISSUE TITLE
gitea-api http Error:  from origin 'null' has been blocked by CORS policy: 

### ISSUE THREAD

**Issue by yyy19961027** [go-gitea/gitea#24203]
### Description

custom/conf/app.ini  configuration:
![微信截图_20230419174213](https://user-images.githubusercontent.com/66300848/233035903-1611cb11-e6f2-4557-8ec5-4bfb1f65a0dd.png)

run code:
![微信截图_20230419174228](https://user-images.githubusercontent.com/66300848/233035960-71dbd5b7-8ca0-4f37-b67e-40d22e18733f.png)

reponse message:
![微信截图_20230419172949](https://user-images.githubusercontent.com/66300848/233036083-e3924e2a-5e3b-4b80-8805-ffe86bf3c193.png)

How can configure？
I According to the API configuration of custom/conf/app.ini - [cors], there is still a cross domain issue. 

### Gitea Version

 1.20.0+

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

running gitea env:

step1:    docker pull gitea/gitea

step2:   mkdir mygitea

step3：docker run -d --name gitea --restart=always  -p 9210:22 -p 9211:3000 -v /home/dockers/mygitea/:/data gitea/gitea

setp4: init config

### Database

Default

**Comment by wxiaoguang** [comment]
Have you ever read jQuery document? Does jQuery say that it supports `mode:'cors'` ?

**Comment by wxiaoguang** [comment]
And, you made another mistake. The document says: `[cors]` , NOT `[CORS]`, please please please read materials really really really carefully.


To show the API CORS  work, I wrote:

![image](https://user-images.githubusercontent.com/2114189/233050677-a053b5da-a0ac-497d-a979-5dfae2924bb3.png)


![image](https://user-images.githubusercontent.com/2114189/233050720-9690def0-e4af-4407-acbb-ceff2ef09254.png)


![image](https://user-images.githubusercontent.com/2114189/233050981-30ecd8b6-5f85-422b-83c1-b6a376f91245.png)
