### ISSUE TITLE
Closed PRs getting picked up by build servers monitoring Gitea repos with Gitea 1.19

### ISSUE THREAD

**Issue by parnic-sks** [go-gitea/gitea#24213]
### Description

We recently upgraded from Gitea 1.18.5 to Gitea 1.19.1, and our TeamCity server has started queuing builds for a number of closed PRs for no discernable reason. No changes are being pushed to these PRs, in fact some of the PRs's branches have been deleted.

I haven't been able to track down the specific details of what's going on, but I can see on the Gitea host filesystem that the directory under repositories/org/repo/refs/pull for the closed PR is getting re-created with the "head" file containing a commit hash that doesn't belong to that branch at all (it seems to always belong to our default 'main' branch instead).

Our only fix has been to constantly monitor TeamCity for queueing builds on closed PRs and canceling them, then fully Deleting the closed PR in Gitea. This is causing a significant problem for us at the moment, so if there's a commit I can cherry-pick to manually build and deploy a fix, we'd be very happy to do that.

This only applies to PRs that are closed, it is not happening with open or merged ones.

I found some issues/PRs that sound possibly related:
* #23707 
* #23189 

### Gitea Version

1.19.1

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

Hand-built 1.19.1 with one local modification, running on an arm64 AWS EC2 instance.

### Database

PostgreSQL

**Comment by wolfogre** [comment]
Could you please explain how your Gitea instance triggers builds in TeamCity? Is it via a webhook or by monitoring the repository refs files?

**Comment by parnic-sks** [comment]
> Could you please explain how your Gitea instance triggers builds in TeamCity? Is it via a webhook or by monitoring the repository refs files?

Yes, good question, I left that out of the initial report.

Our TeamCity is set up to monitor branches matching the specification:

```
+:refs/heads/*
+:refs/(pull/*)/head
```

This is in the "VCS root" section:
<img width="715" alt="image" src="https://user-images.githubusercontent.com/62021255/233248003-d4977eaf-39c6-48c5-ad7e-81fdf0d71a88.png">

Then the VCS Trigger is defined like so:
<img width="584" alt="image" src="https://user-images.githubusercontent.com/62021255/233248150-8caa0df6-c68a-4171-b43d-f1c05b621ba3.png">

**Comment by sillyguodong** [comment]
I have probably found out the cause of this problem, I will fix that this week.

**Comment by parnic-sks** [comment]
> I have probably found out the cause of this problem, I will fix that this week.

We've been running the change from #24231 on our server for the past couple of weeks and it has indeed fixed the issue.

Is this going to be merged in soon?
