### ISSUE TITLE
[Proposal] Use vertical style secondary navbar in all-level settings

### ISSUE THREAD

**Issue by HesterG** [go-gitea/gitea#24229]
### Feature Description

Right now the secondary nav bar on settings pages on user/admin/repo levels are horizontal. 

Example from admin:

<img width="1423" alt="Screen Shot 2023-04-20 at 16 05 39" src="https://user-images.githubusercontent.com/17645053/233301423-14631e1d-d547-4b7d-bfd4-0898727bda13.png">

While the nav bar on organization level is vertical:

<img width="1418" alt="Screen Shot 2023-04-20 at 16 06 45" src="https://user-images.githubusercontent.com/17645053/233301718-61981d1b-93f5-4cb6-9b74-3c2dab06b06e.png">

It is better to also use vertical style for user/admin/repo levels, because as more settings are added, a horizontal scrollbar occurs on the horizontal navbar, which is  not very friendly to use. Whereas the vertical navbar can be folded so it can hold more items. Like the one in github.

And for this to look better, also propose to change the overall width of `ui.container` first, on large device (laptops/desktops, between 992px and 1200px), the page with a vertical navbar looks fine (like the screenshot above). But on extra large device (large laptops and desktops, 1200px and up), `ui.container` is only `1127px` in total, so overall the navbar and the contents look crowded in the middle (Also in other pages): 

<img width="1912" alt="Screen Shot 2023-04-20 at 16 18 38" src="https://user-images.githubusercontent.com/17645053/233304515-0153e0f0-25ee-4dc0-b82e-60b1995bf076.png">
 

Some Step:

- [x] Change html only to change from horizontal to vertical navbar
- [x] Change css (like width) to make the contents less crowded
- [ ] Change some of the routers to make some settings submenus

**Comment by silverwind** [comment]
Agree, these scrollable vertical navbars are weird. Pages like Org settings already have vertical nav, so you can copy the HTML structure from there.
