### ISSUE TITLE
Push comments of pull request sometimes are missed.

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#24237]
Take a look at the PR https://gitea.com/gitea/blog/pulls/262 . There are 4 commits but no any commits comment on pull request conversation.

**Comment by wxiaoguang** [comment]
Have you checked the database? I guess the problem is that when a PR is open, the comments are displayed. But for closed PRs, the commits are not displayed?

**Comment by wxiaoguang** [comment]
A old PR https://gitea.com/gitea/blog/pulls/180 (2 years ago) doesn't show the commits either

**Comment by lunny** [comment]
Caused by #23189 @sillyguodong

**Comment by wxiaoguang** [comment]
Oh, I have proposed a fix

 Show commit history for closed/merged PRs #24238
