### ISSUE TITLE
Activity Heatmap: Count commits instead of pushes

### ISSUE THREAD

**Issue by evur** [go-gitea/gitea#24240]
### Feature Description

Currently when pushing after every commit, the dot is brighter than when pushing multiple commits at once.
It would be better if commits are counted instead of pushes.

**Comment by idbolshakov** [comment]
It is also very handy in our use-cases. In our flow there is a standalone system account that push real users commits from other system. 

So for now there is a lot of activity for system account (pushes) and zero activity for a real user (commits). 

It will be very handy if we could track real users activity. Gitea correctly map commit authors to gitea users, but activity heatmap is empty.

**Comment by leaveye** [comment]
Agreed. and duplicate of #8178. Issue is heatmap counts the pusher, not the author of a commit.

**Comment by lunny** [comment]
Let's move to #8178 and I have a comment https://github.com/go-gitea/gitea/issues/8178#issuecomment-2530497132
