### ISSUE TITLE
Footer dispaly issue

### ISSUE THREAD

**Issue by yp05327** [go-gitea/gitea#24249]
### Description

![image](https://user-images.githubusercontent.com/18380374/233573621-141e1686-8d09-407d-a847-9492158a3626.png)

It seems that footer has been changed. (In the middle of the footer, not left and right)

Then if we adjust the browser's width:
![image](https://user-images.githubusercontent.com/18380374/233572399-b3f5fc41-cb5e-40b5-8aa1-2a8311e773ae.png)
It seems that there's an issue.

### Gitea Version

1.20.0+dev-517-g948a9ee5e

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

build

### Database

None

**Comment by wxiaoguang** [comment]
Maybe I changed some code .....

I guess we could remove the `ui container` and fine-tune the footer left & right, it could be simpler

**Comment by wxiaoguang** [comment]
Does this look good to you?  Fix footer display #24251

**Comment by yp05327** [comment]
@wxiaoguang 
When I was checking the question you asked in https://github.com/go-gitea/gitea/issues/23625#issuecomment-1518999958, 
I found that https://github.com/go-gitea/gitea/issues/24182 happend again.

Maybe the fix of this issue is related?
![image](https://user-images.githubusercontent.com/18380374/233877789-d9f30cb1-a486-4cd5-b8b0-7077fbaeb1b7.png)
![image](https://user-images.githubusercontent.com/18380374/233877832-ffe808b8-f0d9-45e4-82ef-64523850d358.png)

And `private` tag, user name also seems strange? Maybe no word break is better(at least the `private` tag)?

ps: Should I create a new issue for this?

**Comment by yp05327** [comment]
It seems that it also happens on the old version:
(gitea.com)
![image](https://user-images.githubusercontent.com/18380374/233878205-3bcf4f65-65d0-4a8b-90c3-4ac6e5203356.png)

**Comment by wxiaoguang** [comment]
> Maybe the fix of this issue is related?

IMO it's not related. It seems that the "issue list" page width is larger than expected. So a new issue could be fine.

**Comment by silverwind** [comment]
Maybe it's time to find something better for dropdowns. Maybe https://github.com/github/details-menu-element.

**Comment by wxiaoguang** [comment]
It's not related to dropdown.

I think the page width problem is a regression of 

* https://github.com/go-gitea/gitea/pull/19468
* https://github.com/go-gitea/gitea/pull/19486

Which look like a dirty pollution to existing CSS styles.

**Comment by wxiaoguang** [comment]
Will be fixed by https://github.com/go-gitea/gitea/issues/24296 (together)

At that time, some people do not understand how to make styles work with Fomantic UI correctly.

**Comment by yp05327** [comment]
@silverwind 
https://try.gitea.io/yp05327/longnamelongnamelongnamelongnamelongnamelongnamelongnamelongname/issues
