### ISSUE TITLE
In the  PR revew process, improve the presentation when a file is marked as viewed.

### ISSUE THREAD

**Issue by JVC-MSF** [go-gitea/gitea#24250]
### Feature Description

When I'm reviewing a PR, in the moment i click on the viewed checkbox in a file with a lot changes, the file is hidden but then I'm way down in the page and I must scroll up to reach the next file.

Will be nice if the page is scrolled to the begining of the next file when I click on the viewed checkbox of the current file.

**Comment by lunny** [comment]
This should be fixed by #23702

**Comment by JVC-MSF** [comment]
Cool! I see it's already merged.

Thanks!!
