### ISSUE TITLE
Unable to upload tar.gz attachment

### ISSUE THREAD

**Issue by JKingweb** [go-gitea/gitea#2425]
- Gitea version (or commit ref): 1.2.0-rc1
- Git version: N/A
- Operating system: Ubuntu 16.04 (server), Windows 10 (client)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

The default configuration suggests one should be able to upload gzipped tarballs as attachments (application/gzip is in the allowed list), but it doesn't seem to work on any Windows browser I've tried (Vivaldi, Edge, Chrome, Firefox).

![image](https://user-images.githubusercontent.com/89590/29855259-84e80b26-8d18-11e7-9c24-90365cd3b49e.png)
![image](https://user-images.githubusercontent.com/89590/29855273-975c5668-8d18-11e7-8477-aefcd19d9198.png)

**Comment by lafriks** [comment]
You can set allowed that in app.ini file and restart gitea:
https://docs.gitea.io/en-us/config-cheat-sheet/ section Attachments

**Comment by JKingweb** [comment]
As stated in my description, application/gzip should be allowed by default. I also tried adding it explicitly. Neither worked. Finally I had to change the allowed list to */* to get it to work. Is there something else non-obvious that would work?

**Comment by lafriks** [comment]
By default only images are allowed. You have to set correct mime type as sent from browser (there are multiple for gz files)

**Comment by lafriks** [comment]
Sorry I thought it is issue attachment :)

**Comment by lafriks** [comment]
Try adding `application/x-gzip` to allowed_type

**Comment by JKingweb** [comment]
Thanks, application/x-gzip worked. It may be beneficial to have the message state the type which is being rejected, so that one doesn't have to go fumbling in the dark.
