### ISSUE TITLE
Unnecessary horizontal scrollbar in Firefox

### ISSUE THREAD

**Issue by King555a** [go-gitea/gitea#24273]
### Description

No matter how large or small my browser window is, I always have a horizontal scrollbar (blue) at the bottom, without any obvious reason. It also does not matter whether I'm logged in or not. It does not occur in Chrome. I do not use an ad-blocker.

### Screenshots

![scrollbar](https://user-images.githubusercontent.com/126968427/233785629-78d7d718-d88a-43f9-aefc-9816b39daff0.png)

### Gitea Version

1.19.1

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

Windows 10 22H2 x64

### Browser Version

Firefox 112.0.1 (x64)

**Comment by wxiaoguang** [comment]
Could you try a nightly build? I guess https://github.com/go-gitea/gitea/pull/24211 has fixed the problem.

https://dl.gitea.com/gitea/1.19/

**Comment by wxiaoguang** [comment]
What package? If you'd like to try , you could safely  download the latest binary and replace it, pretty  simple.

**Comment by silverwind** [comment]
Could also verify on https://try.gitea.io/ which runs 1.20, but also should have the fix and be somewhat close of a test.

**Comment by silverwind** [comment]
And yes, don't be afraid of nightlies, they are well tested and in fact I run them in production as well.

**Comment by silverwind** [comment]
Pretty positive this was fixed, closing.
