### ISSUE TITLE
user can clone & push private repo without authentication when use Apache2 reverse proxy

### ISSUE THREAD

**Issue by dreampet** [go-gitea/gitea#2427]
- Gitea version (or commit ref):
- Git version: 1.2.0-rc1
- Operating system: Ubuntu 16.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description

I just install gitea on Ubuntu 16.04 + Apache2 + MySQL, with the default config, do not change the /home/git/app.ini 
and i create a reverse proxy config like this:

```
<VirtualHost *:443>
  ServerName git.example.com

  SSLEngine On
  SSLCertificateFile*.crt
  SSLCertificateKeyFile *.key
 
 ProxyPreserveHost On
  ProxyRequests off
  ProxyPass / http://127.0.0.1:3000/
  ProxyPassReverse / http://127.0.0.1:3000/
</VirtualHost>
```
then i can login to the web with https://git.example.com and create a **private** repo normally.

but i found that i can clone and push without username and password authentication with https url:

```
 git clone https://git.example/test/test.git
Cloning into 'test'...
remote: 对象计数中: 138, 完成.
remote: 压缩对象中: 100% (104/104), 完成.
remote: Total 138 (delta 29), reused 138 (delta 29)
Receiving objects: 100% (138/138), 393.25 KiB | 0 bytes/s, done.
Resolving deltas: 100% (29/29), done.

```
and just only in the ip url request to enter username and password

```
git clone http://192.168.1.10:3000/test/test.git
Cloning into 'test'...
Username for 'http://192.168.1.10:3000': admin
Password for 'http://admin@192.168.1.10:3000':
remote: 对象计数中: 138, 完成.
remote: 压缩对象中: 100% (104/104), 完成.
remote: Total 138 (delta 29), reused 138 (delta 29)
Receiving objects: 100% (138/138), 393.25 KiB | 0 bytes/s, done.
Resolving deltas: 100% (29/29), done.

```

**Comment by ekozan** [comment]
Maybe not a bug :) check ```git help credential-cache```

you can try``` git config --global credential.helper 'cache --timeout 3600'``` for not stay login

**Comment by Zegorax** [comment]
I can confirm this. On my installation, I can clone a private repo behind a Reverse Proxy without authentification. This is a major security issue.
