### ISSUE TITLE
Modal dialog button colors?

### ISSUE THREAD

**Issue by wxiaoguang** [go-gitea/gitea#24285]
### Feature Description

Which style should be used?

## 1
![image](https://user-images.githubusercontent.com/2114189/233842683-f77de1a3-c8d1-42f7-b106-3cf8629ab2f1.png)

## 2
![image](https://user-images.githubusercontent.com/2114189/233842618-d002f88f-2a34-42ae-8eba-bac921d431f2.png)

## 3
![image](https://user-images.githubusercontent.com/2114189/233842637-07e106be-948c-4237-80df-93fdc8c8d7f0.png)

## 4
![image](https://user-images.githubusercontent.com/2114189/233842661-cab0fb20-29b9-4f94-aed9-a89ecb89f387.png)

## 5
![image](https://user-images.githubusercontent.com/2114189/233842806-4ad2ec2c-a130-4e57-aa28-e01ebe72bace.png)

(5: only text is different from 4)

**Comment by KN4CK3R** [comment]
2 or 4 for me.

**Comment by wxiaoguang** [comment]
> 2 or 4 for me.

Added 5 , at the moment, all default texts are Yes/No or Confirm/Cancel.

**Comment by wxiaoguang** [comment]
Maybe we can always use style 5 from now on. Actually it has already been used widely in Gitea's UI. At the moment, some old dialogs are style 1, which don't look good to me 😁 

I will come back to collect more opinions tomorrow.

**Comment by delvh** [comment]
I think I prefer 2, simply as it isn't as confusing.
With the current red-green coloring, I always have to remember whether I should assign `red` to `yes` (-> destructive action), or to `no` (-> canceling the action)…
The only question is how does it look on arc-green?

**Comment by wxiaoguang** [comment]
> The only question is how does it look on arc-green?

Good question, the "primary" button is green on arc-green .....

![image](https://user-images.githubusercontent.com/2114189/233844293-4e4063cb-fc2f-44e4-a76a-5bf7ee5b5d20.png)


![image](https://user-images.githubusercontent.com/2114189/233844278-89f354bc-e056-4471-b22e-09c6f07b6591.png)

**Comment by delvh** [comment]
Then it looks like I hoped for.
Then 2 is my final choice.

**Comment by wxiaoguang** [comment]
When rewriting the old code ( Improve some modal action buttons #24289 ), I also found that there are "yellow" buttons in code 🤣 

I guess it might be better than "blue" for "destructive action"

And I added a devtest page for the modal buttons, welcome to try ~~~

![image](https://user-images.githubusercontent.com/2114189/233847773-a6d6b29b-7b5c-490e-8425-40dfd0ad2529.png)

**Comment by panekj** [comment]
1 - No, colours make the buttons text a little bit unreadable in that contrast
2 - Out of all presented options, yes, but still having a "Default button colour" for destructive actions is not that great choice.
3 - Kind of yes, the red colour for "confirming" a destructive action fits here, the green one not so much. It also can confuse end user as to what they want to achieve `green` -> `yes`, `red` -> `no`.
4,5 - Like 3 but worse.

6(?) option
Don't introduce a UI where user can be mistake/accident perform the wrong action.
GitHub solves with presenting only a single button in modal and a clickable link to close the modal
![image](https://user-images.githubusercontent.com/50457605/233850802-e8f0c232-aa9b-49fd-b640-d25078184245.png)

**Comment by wxiaoguang** [comment]
> Don't introduce a UI where user can make mistake/accident to perform the wrong action.
> GitHub solves with presenting only a single button in modal and a clickable link to close the modal

Gitea also does so on critical operations, see below.

This issue/PR are mainly for "general" deletion confirmation.

![image](https://user-images.githubusercontent.com/2114189/233851015-6f6eb5de-e693-49e1-8eea-3b773859ce70.png)

**Comment by wxiaoguang** [comment]
I managed to add a GitHub-like "danger" button in #24289

I guess we can start using it in some cases.

![image](https://user-images.githubusercontent.com/2114189/233852791-ca2f0106-3346-429f-9377-7e35bcd6918a.png)

**Comment by silverwind** [comment]
I would follow these rules:

- Delete buttons always red indicating the danger
- Confirm button always primary indicating the primary action
- All other buttons just basic outlined buttons without color

**Comment by BySempron** [comment]
I like 1. Keep color based decision but less intrusive like 3, 4 or 5

**Comment by wxiaoguang** [comment]
Thank you all for the suggestions! #24289 summarized the suggestions, and the current approach is:

1. Always show "negative" button as secondary button (no color)
2. Developers could use green/blue/yellow for the positive button, for different cases.
3. Developers could also use a single red button for dangerous operations, just like GitHub.

I think this issue could be closed, let's do more improvements (new issue/PR) in the future.

**Comment by yp05327** [comment]
Maybe  #20212 is related to this discussion?

**Comment by wxiaoguang** [comment]
Yes, but some colors are still inconsistent at the moment.
