### ISSUE TITLE
The account registration is prohibited, but the account registration succeeds

### ISSUE THREAD

**Issue by FunkyGod** [go-gitea/gitea#24297]
### Description

service]
DISABLE_REGISTRATION              = true
step 1：
try registering this account ：test.
step 2:
Page error：Forbidden
![企业微信截图_16823008832970](https://user-images.githubusercontent.com/39259580/233882356-ff62d6a6-346b-4b27-9ca7-93d15653797d.png)
step 3：check account manager
find Registered successfully
![image](https://user-images.githubusercontent.com/39259580/233882510-e8c9c19d-7536-46b4-b0f5-14292fb51096.png)

### Gitea Version

1.19.1

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

1

### Screenshots

1

### Git Version

1

### Operating System

1

### How are you running Gitea?

1

### Database

PostgreSQL

**Comment by yp05327** [comment]
I can't reproduce this issue in 1.20.0+dev-554-ga0cfc1c95 and 1.19.1+15-g7d717e22a

My process:
- start server with service.DISABLE_REGISTRATION = false
- access `user/sign_up`
- stop the server, and convert service.DISABLE_REGISTRATION into true
- restart server
- fill in the register form and register `test` user
- get `Forbidden` page
- login by admin user, and check the user list
- no `test` user in the list

**Comment by wxiaoguang** [comment]
Thanks to yp05327's test!

@FunkyGod  if there is still a problem, please help to provide details reproducible steps.
