### ISSUE TITLE
Horizontal overflow

### ISSUE THREAD

**Issue by yp05327** [go-gitea/gitea#24296]
### Description

Described in https://github.com/go-gitea/gitea/issues/24249#issuecomment-1519234504 and https://github.com/go-gitea/gitea/issues/24249#issuecomment-1519235790

### Gitea Version

1.20.0+dev-553 and 513

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

try.gitea.io:
![image](https://user-images.githubusercontent.com/18380374/233877789-d9f30cb1-a486-4cd5-b8b0-7077fbaeb1b7.png)
![image](https://user-images.githubusercontent.com/18380374/233877832-ffe808b8-f0d9-45e4-82ef-64523850d358.png)
gitea.com:
![image](https://user-images.githubusercontent.com/18380374/233878205-3bcf4f65-65d0-4a8b-90c3-4ac6e5203356.png)

### How are you running Gitea?

gitea.com

### Database

None

**Comment by wxiaoguang** [comment]
It's related to :

* https://github.com/go-gitea/gitea/pull/19468
* https://github.com/go-gitea/gitea/pull/19486

**Comment by yp05327** [comment]
![image](https://user-images.githubusercontent.com/18380374/234192369-142c1516-13b5-4182-9125-436b6cb47db6.png)
Same issue in dashboard pages.
