### ISSUE TITLE
Bold text not rendering for some fonts at font-weight: 600 e.g. 'Segoe UI'

### ISSUE THREAD

**Issue by belzecue** [go-gitea/gitea#24305]
### Description

I noticed this in my hosted 1.18.5 instance: bold wiki text was not showing as bold in latest Chrome browser.  I went straight to try.gitea.io and reproduced the issue there on the current dev instance.  Curiously, this issue does not present with Firefox, which renders the bold as expected, so it seems Chrome is rendering the same CSS differently [EDIT: more likely different fonts, as the Chrome instance was on Linux and the Firefox test was on a windows 10 box].

Video showing my experience:

https://user-images.githubusercontent.com/1931303/234031441-3ae06ce1-cd63-4742-8cbf-24c7d0ec1f60.mp4

There seems to be two CSS definitions for STRONG that are related to this issue.  When I disable one of them, as shown in the video, bold returns.

### Gitea Version

try.gitea.io

### Can you reproduce the bug on the Gitea demo site?

Yes

### Git Version

1.20.0+dev-559-g75c62054a

### Operating System

Linux (Debian)

### How are you running Gitea?

try.gitea.io

### Database

None

**Comment by belzecue** [comment]
Doublechecking my Chrome bold display by testing at w3schools.com:

![image](https://user-images.githubusercontent.com/1931303/234036657-6e9d5f64-9453-4855-a631-69bf3a0aa285.png)

Can't repro missing bold on any other app or site, so far.

**Comment by wxiaoguang** [comment]
I guess it's related to `font-weight` value.

I can see that: `font-weight: bolder` works for you, but `600` not. 

So could you help to confirm whether other values work? `900`, `bold` (not bolder).

**Comment by wxiaoguang** [comment]
MDN has a page for bolding testing:

https://developer.mozilla.org/en-US/docs/Web/CSS/font-weight

**Comment by belzecue** [comment]
> What's the minimal value it could render as bold?

601 !! LOL.  Crazy.  That does not seem right.

> ps: do you know your font's name?

"Segoe UI" according to the CSS "computed" value in Chrome's inspector.

**Comment by wxiaoguang** [comment]
Well, maybe 601 is not wrong .... according to MDN

The "bold" starts from 700 ....

![image](https://user-images.githubusercontent.com/2114189/234039639-54f31ccc-98c9-4d8f-987e-7ccea0d5af02.png)

**Comment by wxiaoguang** [comment]
Maybe we need this PR:  Use font-weight: bold instead of 600 #24307

**Comment by belzecue** [comment]
OK, looks to be just this font.  For some reason it bucks the standards and only renders bold at 601 and higher.

I tested at https://developer.mozilla.org/en-US/docs/Web/CSS/font-family by modifying the last font to be 'segoe-ui' to display my font in the list, then I added 'font-weight:600' to all the displayed fonts, and only 'segoe-ui' failed to render in bold.

https://user-images.githubusercontent.com/1931303/234041447-9976be96-a21b-4b59-b2b2-4aec83cd8cbd.mp4

**Comment by silverwind** [comment]
`700` seems to excessivly bold to me when semi-bold can be rendered. Show a screenshot of this please:

https://codepen.io/silverwind/pen/jOeBmvj

Here is MacOS:

<img width="169" alt="Screenshot 2023-04-24 at 17 27 50" src="https://user-images.githubusercontent.com/115237/234043741-d3f106b7-aa5e-4ac3-9b00-68164f5f3b21.png">

**Comment by wxiaoguang** [comment]
Then font-weight: 610 seems a reasonable value for most users.

**Comment by silverwind** [comment]
@belzecue show screenshot of this one please: https://codepen.io/silverwind/pen/jOeBmvj

**Comment by belzecue** [comment]
Working.  Although on this device it renders a uniform weight from 601 all the way up.  No graduation.  Perhaps to do with the display manager/desktop manager on my Linux installation.

![image](https://user-images.githubusercontent.com/1931303/234049173-e6ffa315-19eb-4f36-861c-9784e700f92f.png)

**Comment by silverwind** [comment]
Yeah I guess your bold kicks in at > 600, we will use 610.

**Comment by belzecue** [comment]
Chrome/Chromium has had struggles with Segoe-UI before: https://bugs.chromium.org/p/chromium/issues/detail?id=791305&q=component%3ABlink%3EFonts%20bold&can=2

**Comment by silverwind** [comment]
I think what you are lacking is a font that supports more fine-grained, likely called [variable font](https://developer.mozilla.org/en-US/docs/Web/CSS/font-weight#variable_fonts). If there's a good one available, it could be considered for our font stack.
