### ISSUE TITLE
Dropdown don't cross over the navbar in dashboard page

### ISSUE THREAD

**Issue by yp05327** [go-gitea/gitea#24320]
### Description

![image](https://user-images.githubusercontent.com/18380374/234192609-f1c255ca-bed1-451f-9340-2c9a8c7def20.png)
![image](https://user-images.githubusercontent.com/18380374/234192651-5c51e173-f068-4fdb-ab67-90b1e326a419.png)

### Gitea Version

latest

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

build

### Database

None

**Comment by wxiaoguang** [comment]
What do you mean by "cross over"? full width?

**Comment by yp05327** [comment]
Correct:
![image](https://user-images.githubusercontent.com/18380374/234204943-ae27aa5d-b3ea-461e-94e1-d359c4a32c34.png)

Maybe "cover" is correct?

**Comment by wxiaoguang** [comment]
I think I get your point now. It's like caused by misuse of Fomantic UI layout.

**Comment by yp05327** [comment]
Fixed
