### ISSUE TITLE
The size of create action runner button is too big

### ISSUE THREAD

**Issue by yp05327** [go-gitea/gitea#24326]
### Description

Maybe it is too big
![image](https://user-images.githubusercontent.com/18380374/234212412-60e02251-eb70-420a-8ad2-acb1e03b2377.png)
Other buttons in website settings:
![image](https://user-images.githubusercontent.com/18380374/234212437-43a780cf-d3d1-44e0-b23f-ddbbad8fa6f1.png)
![image](https://user-images.githubusercontent.com/18380374/234212687-9aab69e4-a1f5-4449-b8bc-441dea6b6339.png)
![image](https://user-images.githubusercontent.com/18380374/234212714-b7f2c750-84f3-47bb-bc02-095a0e5e8a9b.png)

### Gitea Version

latest

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

build

### Database

None

**Comment by silverwind** [comment]
Yes, needs same size classes as other buttons to fit inside these headers.
