### ISSUE TITLE
Global issues search

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#2434]
Currently we have issues where you can find all your related issues. But when the issues are too much, maybe you want to search them.

**Comment by kolaente** [comment]
It probably is very inperformant, to go through every issue when you issue a search, so: should we cache? (And how?)

Caching would probably mean to put every issue in a redis/memstore with everything that belongs to it.

**Comment by stevegt** [comment]
Caching may be needed in some cases, but I wouldn't bother with it for a first implementation.  A gitea instance run by an individual or small organization may not have enough issues in their db to cause a problem.  If performance is still a concern, make global search an admin tool only, or add a config option to turn the global search feature off.

In my own case, global issue search is one of the first things I went looking for, which led me here.  Seems like a gitea admin would need at least a global view of issues, similar to the global view of repos in /admin. Among other things, this would allow them to see how well gitea is being adopted so they can help bring project teams up to speed.

**Comment by stevegt** [comment]
#3841 (possible dup) discusses how the web frontend for this might look.

**Comment by scullhead** [comment]
Here is my content from the issue #3841 

- Gitea version (or commit ref): 1.4.0+3-g641d481
- Git version: 2.7.4
- Operating system: Ubuntu 16.04.4 LTS
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant

## Description
When you are on the "issues" tab of a repository you have a search input field where it is possible to search for a text in all issues of this repo.

When you klick on "Issues" in the global navigation menu of gitea it shows a list of all issues from all repositories (if they are public). 
It would be very useful if there was also a search input field to search over all public issues.

![gitea_issues_global_search](https://user-images.githubusercontent.com/10958573/39132535-5bc215b6-4712-11e8-902d-a2a1d275caca.png)

**Comment by jag3773** [comment]
Signalling that this is a desired feature by many of our users.  We are working on several projects that make heavy use of issues and it would be really handy to be able to search across all of them.

**Comment by lunny** [comment]
Where is the best place to put the search box?

**Comment by guillep2k** [comment]
`/issues` sounds good.

**Comment by lunny** [comment]
@guillep2k That design is good but I don't think that's the best place. A search box on /issues will let you think that the search scope is all issues related you but not all the sites.

**Comment by guillep2k** [comment]
> 
> 
> @guillep2k That design is good but I don't think that's the best place. A search box on /issues will let you think that the search scope is all issues related you but not all the sites.

They _will be related_ to me because they will be the issues I can see. e.g. "Issues you have access to".

Check this picture; adding "All issues" can help convey the idea.

![image](https://user-images.githubusercontent.com/18600385/65244936-02fa9d00-dac2-11e9-9f86-ddb73a15f7fd.png)

**Comment by lunny** [comment]
Then the repositories on the left corner when you checked `all repository` maybe a large list.

**Comment by jag3773** [comment]
@lunny That's exactly why a global search is an essential feature!

**Comment by bhalbright** [comment]
I'm probably missing the whole picture, but in https://github.com/go-gitea/gitea/pull/7901 I am attempting to add an endpoint to search issues across repositories (i.e. the repositories the user has access to). Just wanted to comment because perhaps it could be of use here. However, I put the endpoint under repos like for example: /api/v1/repos/issues/search?q={query}

**Comment by guillep2k** [comment]
@bhalbright Perhaps it should not be under `/api/v1/repos` if it's not searching inside a particular repo? @lafriks ?

**Comment by bhalbright** [comment]
@guillep2k I think I did it because all the "issues" api endpoints seemed to already be under /repos but I can see where this one might be debatable. For example from the swagger doc (the first in the list is the one I added in the #7901 PR)

![image](https://user-images.githubusercontent.com/32200834/65477555-494a5600-de4c-11e9-9999-6ce0522189ce.png)

**Comment by bhalbright** [comment]
Just dropping a note that I'm going to work on an attempt at this based on the ui design by @scullhead 
 and @guillep2k and using the api endpoint I worked on in #7901

**Comment by lunny** [comment]
@bhalbright The permission check with pagnation is something we need pay attention to.

**Comment by 6543** [comment]
I think a global issue search should be here:
![Bildschirmfoto zu 2020-01-14 20-40-48](https://user-images.githubusercontent.com/24977596/72376498-572f2a00-370e-11ea-9736-2e3934d5e306.png)

**Comment by cbrake** [comment]
I really like projects as a way to organize issues from multiple repos. It would be really useful to be able to search/filter all cards/issues in a project.

Trello does filtering really well.

**Comment by lunny** [comment]
We already have one at /issues like below.

![图片](https://github.com/user-attachments/assets/bb48e50d-7fbb-48dd-8176-7afe7d102a9e)

**Comment by cbrake** [comment]
> We already have one at /issues like below.
> 
> ![图片](https://private-user-images.githubusercontent.com/81045/379420813-bb48e50d-7fbb-48dd-8176-7afe7d102a9e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3ODc0NTAsIm5iZiI6MTcyOTc4NzE1MCwicGF0aCI6Ii84MTA0NS8zNzk0MjA4MTMtYmI0OGU1MGQtN2ZiYi00OGRkLTgxNzYtN2FmZTdkMTAyYTllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI0VDE2MjU1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1MzZmYjE5NDdlZTU0ZmI1YzA0ZWJkYTdhNDg3OTNhYTI3NTJmODhiZWIxMjM1YTllZGE3Y2E4NDE1MDcwMGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1m68PoXH_qfDqsqktF_iMNyeiEP2u2SeKmiHjEdkATk)

Thanks @lunny -- that is useful, but I think it would also be useful to have something similar on a project board where you can filter on a search term and only the cards in the board that match are shown, and the rest are hidden.

**Comment by nodiscc** [comment]
Hi, I think the feature originally requested in this issue is now fully implemented (global issues search)

Maybe it would be better to open separate issues for improvements/related feature requests?
