### ISSUE TITLE
Linking Gitea with Liberapay

### ISSUE THREAD

**Issue by meyverick** [go-gitea/gitea#24355]
### Feature Description

Add the possiblity to link Gitea to Liberapay.

It looks like that it's not possible to add Gitea to Liberapay because of how Gitea manage Oauth.

https://github.com/liberapay/liberapay.com/issues/943

**Comment by lafriks** [comment]
I don't really see what can be done on gitea side for this, please update issue with exact information that need to be added in gitea side

**Comment by meyverick** [comment]
- https://github.com/liberapay/liberapay.com/issues/943#issuecomment-586933282
- https://github.com/liberapay/liberapay.com/issues/943#issuecomment-588296218

It seems that Liberapay need to be able to automatically create OAuth credentials for Liberapay and with the minimum scope (read-only to basic information).

The post issues is from early 2020, perhaps Gitea has fulfilled the requirements. Can you confirm?

Here a screenshot of the already supported projects: 
![Screenshot_2023-04-28-00-51-58-37_e4424258c8b8649f6e67d283a50a2cbc](https://user-images.githubusercontent.com/101877847/235008259-1aa54356-81c5-40f7-a755-d54ad7555b17.jpg)

**Comment by jolheiser** [comment]
fwiw I left a [comment](https://github.com/liberapay/liberapay.com/issues/943#issuecomment-1402381501) there when we merged the scoped tokens.

I don't know if there's anything left for us to do on our end, now it just needs to be implemented in that project.  
If there is anything else, though, please let us know! 🙂

**Comment by meyverick** [comment]
Thank you for your rapid answer. I hope it will be integrated to Liberapay 🤞
