### ISSUE TITLE
confusing indentation

### ISSUE THREAD

**Issue by binford2k** [go-gitea/gitea#2435]
When typing out an indented block of code, the first line is indented with a [tab] character and the rest are indented with spaces. That makes for some really weird looking code. (And totally invalid code, if you're writing Python.)

https://try.gitea.io/nope/foobar/src/master/test.pp

**Comment by bkcsoft** [comment]
Where are you typing this?

**Comment by binford2k** [comment]
https://try.gitea.io/nope/foobar/src/master/test.pp

Click the edit pencil.

**Comment by bkcsoft** [comment]
In the web-editor then. 

https://github.com/go-gitea/gitea/blob/fd85e25f5f48823c4e65f3bd23662fd26d1398b3/public/js/index.js#L964-L982

Looks like the editor config is only loaded when one edits the filename 🤔 And the order of setting it also  seems off...

**Comment by bkcsoft** [comment]
On a side-note I noticed that the CodeMirror version we ship is very old https://github.com/codemirror/CodeMirror/releases/tag/5.17.0 and we should probably upgrade it to the newest version https://github.com/codemirror/CodeMirror/releases/tag/5.29.0

**Comment by techknowlogick** [comment]
We could probably update to this version now: https://github.com/codemirror/CodeMirror/releases/tag/5.43.0

**Comment by lafriks** [comment]
Can you recheck on try.gitea.io if problem has been solved with codemirror update

**Comment by lafriks** [comment]
Closing as we have replaced CodeMirror with Monaco Editor
