### ISSUE TITLE
how to upgrade

### ISSUE THREAD

**Issue by MetaiR** [go-gitea/gitea#2437]
hello,
I saw your doc about upgrading from Gogs but I couldn't find any references for upgrading to new version of your wonderful program.

we are using it in our server and it has projects, web hooks and etc and I want to upgrade it without any trouble or crashes (specially about losing data)

so how should I upgrade it?

**Comment by lafriks** [comment]
I'm currently working on fix to make it possible

**Comment by MetaiR** [comment]
@lafriks 
it's very good to hear that.
you think when it will be available?

**Comment by kmare** [comment]
I didn't setup any webhooks etc, just the basics. I'm using gitea just for my personal git needs on a rpi3. The only thing I have to do to upgrade is replacing the current binary with the newest version. Of course before doing that, I always keep a backup just to be safe. When you first run the updated version (./gitea web), wait a little bit (just a few seconds just to upgrade whatever it needs to I guess ) and you're good to go.
I updated from 1.1.2 to 1.1.3 and now to 1.2.0 without any problems so far. Everything worked like a charm!

**Comment by lafriks** [comment]
Gogs -> 1.1 -> 1.2 does work but direct upgrade to 1.2 does not currently

**Comment by MetaiR** [comment]
so how should I upgrade? can the team create a doc at least?

**Comment by lafriks** [comment]
@MetaiR There already is documentation on how to do that - https://docs.gitea.io/en-us/upgrade-from-gogs/

but if you want to upgrade directly to 1.2 than please wait for #2460 to merged to 1.2 branch and rc2/final version of 1.2.0

**Comment by MetaiR** [comment]
@lafriks 
is there any difference between upgrading from `Gogs` or from `Gitea` itself?
 I mean, your doc is about upgrading from `Gogs` to `Gitea` but my case is upgrading from an old version of it to the new one, so is that be enough for my situation? (I mean the doc you mentioned)

**Comment by lunny** [comment]
Since Gitea developed based on Gogs, so old Gods like an old gitea version. The both process should be the same.
