### ISSUE TITLE
dump  bug in converstion of authentications

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#2438]
Gitea Version: 1.2.0+rc1 
- Database
was sqlite
dump and moved to mariadb

- Can you reproduce the bug:
  - [x ] Yes

./gitea dump -d mysql
-load the resulting sql file to mariadb 
-modify app.ini to use mysql 
-cannot login with external authentication any longer 
-login with local admin account and see problem 

original authentication before conversion 
(&(groupMembership=cn=it,ou=UserGroups,ou=Unix,ou=Groups,ou=a,ou=b,o=c)(cn=%s))
after conversion 
(u0026(groupMembership=cn=it,ou=UserGroups,ou=Unix,ou=Groups,ou=a,ou=b,o=c)(cn=%s))

the ampersand was changed to unicode.

**Comment by bkcsoft** [comment]
I'm not sure that Gitea supports migrations between different SQL dialects :/
