### ISSUE TITLE
Actions not executing: Incorrect string value

### ISSUE THREAD

**Issue by d0x7** [go-gitea/gitea#24390]
### Description

I enabled actions, added two Docker runners and got them registered and showing up. Did a commit but in the web ui it's stuck at 'Waiting to run'. Gitea's log is spammed with this error:

```
Apr 28 03:51:14 gitea gitea[100520]: 2023/04/28 03:51:14 ...ons/runner/runner.go:106:FetchTask() [E] [644b2692-2] pick task failed: CreateTaskForRunner: Error 1366 (22007): Incorrect string value: '\xF0\x9F\x8E\x89 T...' for column `gitea`.`action_task_step`.`name` at row 1
Apr 28 03:51:14 gitea gitea[100520]: 2023/04/28 03:51:14 [644b2692-2] router: completed POST /api/actions/runner.v1.RunnerService/FetchTask for 10.0.10.0:41642, 500 Internal Server Error in 32.1ms @ <autogenerated>:1(http.Handler.ServeHTTP-fm)
```

And the docker containers log of the runner with this error:
```
gitea_runner  | time="2023-04-28T01:43:06Z" level=error msg="failed to fetch task" error="unknown: rpc error: code = Internal desc = pick task: CreateTaskForRunner: Error 1366 (22007): Incorrect string value: '\\xF0\\x9F\\x8E\\x89 T...' for column `gitea`.`action_task_step`.`name` at row 1"
gitea_runner  | time="2023-04-28T01:43:08Z" level=error msg="failed to fetch task" error="unknown: rpc error: code = Internal desc = pick task: CreateTaskForRunner: Error 1366 (22007): Incorrect string value: '\\xF0\\x9F\\x8E\\x89 T...' for column `gitea`.`action_task_step`.`name` at row 1"
```

I have only today updated from Gitea 1.18.0 to 1.19.1,
As the error seems to be related to my SQL table, I thought that it may be related to version changes and the migration not running correctly? Is there something I can do on my side?

<details>
  <summary>Structure of SQL table in question</summary>
  
  ```SQL
CREATE TABLE `action_task_step` (
  `id` bigint(20) NOT NULL,
  `name` varchar(255) DEFAULT NULL,
  `task_id` bigint(20) DEFAULT NULL,
  `index` bigint(20) DEFAULT NULL,
  `repo_id` bigint(20) DEFAULT NULL,
  `status` int(11) DEFAULT NULL,
  `log_index` bigint(20) DEFAULT NULL,
  `log_length` bigint(20) DEFAULT NULL,
  `started` bigint(20) DEFAULT NULL,
  `stopped` bigint(20) DEFAULT NULL,
  `created` bigint(20) DEFAULT NULL,
  `updated` bigint(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;


ALTER TABLE `action_task_step`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `UQE_action_task_step_task_index` (`task_id`,`index`),
  ADD KEY `IDX_action_task_step_task_id` (`task_id`),
  ADD KEY `IDX_action_task_step_index` (`index`),
  ADD KEY `IDX_action_task_step_repo_id` (`repo_id`),
  ADD KEY `IDX_action_task_step_status` (`status`);


ALTER TABLE `action_task_step`
  MODIFY `id` bigint(20) NOT NULL AUTO_INCREMENT;
COMMIT;
  ```
  
</details>

I also got a different issue/complaint, but it's not really worth opening a issue: I enabled actions in a repo that has a GitHub action, including a use entry which referes to a repo on GitHub (specifically GoReleaser). I was wondering that nothing is happening, no error, no nothing. Only then I realized that that's probably due to Gitea not being able to parse that repo. Would be nice to have an error shown or a warning that this file contains invalid entries, because I was changing other files trying to make it start a build but nothing happend. And that's another feature request: A button to manually start/re-start builds, like GitHub has :) 

Tell me if you need something else, I've just down the runners because it's really spamming my database (the action table has 10k entries at about 10mb now) but I'll gladly provide any other needed information.

### Gitea Version

1.19.1 gitea / 0cf31b2d22 runner

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

2.30.2

### Operating System

Debian 10.2.1 LXC inside PVE 7.2.11

### How are you running Gitea?

Installed as a systemd service inside a LXC on Proxmox.

### Database

MySQL

**Comment by wxiaoguang** [comment]
You need to change your MySQL to use utf8mb4


@lunny do you still think we do not need to do database check?

**Comment by lunny** [comment]
The problem and resolution has been recorded and be put in blog. So I think this could be closed.

> You need to change your MySQL to use utf8mb4
> 
> @lunny do you still think we do not need to do database check?

I just said some users will use custom database version, but I never said we should not check whether the database's charactor.
This problem is related with charactor but MySQL version.

**Comment by lunny** [comment]
I think you should have received an error log on your Gitea side when you start/restart Gitea like the below:
```
Deprecated database mysql charset utf8 support, please use utf8mb4 or convert utf8 to utf8mb4.
```

**Comment by lunny** [comment]
Closed as no response.
