### ISSUE TITLE
Close issues as duplicates of other issues

### ISSUE THREAD

**Issue by dakira** [go-gitea/gitea#2440]
## Description

There should be a possibility to mark an issue as a duplicate of another issue (autoclosing it). The main issue should have a list of its duplicates, so that one can look through them when needed (an example of this can be seen on [Launchpad](https://bugs.launchpad.net/ubuntu/precise/+source/plasma-widget-networkmanagement/+bug/872824)).

Another option could be to merge issues, but that would IMO overcomplicate things (e.g. order of comments).

**Comment by lafriks** [comment]
Do you mean referencing issues like it is in github?

**Comment by dakira** [comment]
No. That reference just shows up in the comments of the referenced issues. You would have to look through all comments to find the duplicates of the issues you're currently viewing. I mean something like this:

![duplicates](https://user-images.githubusercontent.com/576555/29927431-a4e48356-8e66-11e7-9161-78b89ecd4de9.png)

The closed issues should show something like "This issue has been closed as a duplicate of #xyz" at the top.

**Comment by dakira** [comment]
Could be displayed like this. Not sure how the UI for actually marking an issue as a duplicate should look like, though.

![duplicates-list](https://user-images.githubusercontent.com/576555/29930303-5d990f96-8e6e-11e7-8a68-48c23c955860.png)
![duplicate](https://user-images.githubusercontent.com/576555/29930312-60f21994-8e6e-11e7-826f-de6e540a16f6.png)

**Comment by SlavekB** [comment]
Your proposal is absolutely perfect!
I would like to see this solution in Gitea.

**Comment by ghost** [comment]
Having a section showing a summary of referenced issues seems useful, though the introduction of issue "duplicates" is where engineers start splitting hairs. Once you flag one you need a convenient way to unflagged it is more investigation reveals it's not, in fact, a true duplicate. I believe what's really being sought after here would be better served by label sets for custom taxonomy. YMMV
