### ISSUE TITLE
Named translation tags

### ISSUE THREAD

**Issue by silverwind** [go-gitea/gitea#24401]
### Feature Description

Currently we have translation strings like

```
merged commit %[1]s into %[2]s %[3]s
```

This is impossible to understand for a translator without additional context. Better would be a syntax with named variables, like 

```
merged commit {hash} into {branch} {relative-date}
```

Can Crowdin to do something like this?

**Comment by wxiaoguang** [comment]
https://github.com/go-gitea/gitea/issues/23863

**Comment by silverwind** [comment]
Close this in favor of https://github.com/go-gitea/gitea/issues/23863? The request here is not specifically for ICU syntax `{count, plural}`, but also for simple tags like `{hash}`.

**Comment by wxiaoguang** [comment]
`the {var}` syntax is a subset of ICU message.

https://unicode-org.github.io/icu/userguide/format_parse/messages/mf2.html

**Comment by silverwind** [comment]
Okay, let's close then.
