### ISSUE TITLE
No Dropzone in Comment Reply or Code Comment

### ISSUE THREAD

**Issue by kdumontnu** [go-gitea/gitea#24411]
### Description

Reply to comment doesn't have dropzone enabled or support pasting an image from clipboard.

Issue/PR comment and code comment support dropzone.

### Gitea Version

try.gitea

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

![image](https://user-images.githubusercontent.com/12700993/235261137-7293e8a0-172d-4b09-b690-c26e3839fbcb.png)

### How are you running Gitea?

try.gitea

### Database

None

**Comment by wxiaoguang** [comment]
It's duplicate of #12183  , they are the same problem : no upload support.

**Comment by kdumontnu** [comment]
> It's duplicate of #12183 , they are the same problem : no upload support.

Yep, you're right - thanks.
