### ISSUE TITLE
[UI] User followers page

### ISSUE THREAD

**Issue by appleboy** [go-gitea/gitea#24418]
### Description

Find a bug. See the followers page: https://gitea.com/appleboy?tab=followers

Reference PR: https://github.com/go-gitea/gitea/pull/24315

### Gitea Version

1.20.0+dev-601-g50133b02b

### Can you reproduce the bug on the Gitea demo site?

Yes

## Before

![image](https://user-images.githubusercontent.com/21979/235285973-00ae60c2-4106-414c-9f55-da51de90817f.png)

## After

remove `max-width: calc(100vw - 64px);`

![image](https://user-images.githubusercontent.com/21979/235286095-4f096cf7-7696-457d-93f0-16661dfe1c59.png)

**Comment by wxiaoguang** [comment]
I think the root problem is that the old code was wrong.

`ui container user-cards` : it should use `ui container`
