### ISSUE TITLE
Default Sort in Explore Page

### ISSUE THREAD

**Issue by spaghetti2514** [go-gitea/gitea#2442]
Since commit fa3abc22c06843bb27089e8c0f7aebf0f5d83fcc, the default sort criterion on the Explore page has been created_unix instead of updated_unix. I really preferred the earlier behavior, so I just wanted to make sure that the change was intentional (the commit didn't seem to be explicitly for that purpose so it may have been an accidental byproduct), and if it was intentional, request that it be changed back or have a config setting exposed for it.

**Comment by lunny** [comment]
I think so. order by `updated_unix` desc better.
