### ISSUE TITLE
Comments of code

### ISSUE THREAD

**Issue by lcges** [go-gitea/gitea#2443]
One of the most important things missing in Gitea is commenting the code.
This greatly improves the quality of work and quality control.
Are you going to implement this functionality?

![screenshot capture - 2017-08-31 - 21-40-39](https://user-images.githubusercontent.com/19255071/29956997-401b3fc0-8eeb-11e7-9f82-450dd476ded8.png)
![screenshot capture - 2017-08-31 - 21-46-04](https://user-images.githubusercontent.com/19255071/29956998-401f8d0a-8eeb-11e7-94da-3e3ca349c60a.png)

**Comment by lunny** [comment]
see #124

**Comment by lcges** [comment]
cool.
Is it finished or production?

**Comment by lunny** [comment]
No. There is nobody work on it currently.

**Comment by lcges** [comment]
Ok... because it's a really useful feature.

**Comment by lunny** [comment]
Yes, I see. I have tried to send a PR but I'm not good at UI.

**Comment by lcges** [comment]
listen. Maybe I will try to draw it in Semantic-UI and you already plug it into your template?

**Comment by lunny** [comment]
@qdbdbp Yeah! good idea! I have a branch on my local and not finished on UI.

**Comment by bkcsoft** [comment]
Isn't this duplicate of #124 ?

**Comment by lunny** [comment]
@bkcsoft Yes. And I have set the duplicated label.
