### ISSUE TITLE
Automerge does not work 

### ISSUE THREAD

**Issue by EndrII** [go-gitea/gitea#24445]
### Description

I added next rules for merging PR
* All statuses of commit must be successful before merge
* PR must have one approve review 

### Gitea Version

1.19.2

### Can you reproduce the bug on the Gitea demo site?

I don't know (I can't check it)

### Screenshots

![image](https://user-images.githubusercontent.com/12465465/235366919-4530467b-7ae6-4caa-a417-8b99d495473b.png)
![image](https://user-images.githubusercontent.com/12465465/235366979-a87fe3ec-71e2-447c-b190-3b0b878f2971.png)

### Git Version

git version 2.25.1

### Operating System

ubuntu 20.04 (Linux beloved-pipefish 5.4.0-125-generic #141-Ubuntu SMP Wed Aug 10 13:42:03 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux)

### How are you running Gitea?

I run Gitea from prepared binary files 

### Database

SQLite

**Comment by nekrondev** [comment]
The auto-merge isn't even working on a much simpler workflow by only requesting approval.
I created a demo here https://try.gitea.io/merge_user1/automerge_problem/pulls/1.

`merge_user1`'s repository got branched by `merge_user2` (both are repository admins). Now `merge_user1` PRs his bugfix. The `main` branch is protected and needs one approval. `merge_user2` submitted his PR with `auto merge` enabled, i.e. after approval of `merge_user1` his change should be auto-merged into main.

Now `merge_user1` approved his PR but the commit is not auto-merged into `main` branch like requested by PR owner.

![image](https://github.com/go-gitea/gitea/assets/13854802/3ce6af1d-0ca5-4a83-9758-f7a0e99de2f2)


![image](https://github.com/go-gitea/gitea/assets/13854802/5a16e231-32c7-480d-8f4c-e1482923948e)

![image](https://github.com/go-gitea/gitea/assets/13854802/5daf9348-585d-4eb1-8cc5-25100ea24e7b)

**Comment by EndrII** [comment]
@nekrondev this is looks as a bug, because you can enable branch protection and block merge without any review. But any users can enable automerge and merge it after successful tests ...
So anyway, the automerge must work as in GitHub. But not like now

**Comment by nekrondev** [comment]
I did a quick test with 

- auto-merge enabled and 
- one approval missing 

If I send the API request to commit a successful check the auto-merge is not executed which is fine (the PR still needs to be reviewed).

However if I submit my PR review approval then without any additional calls to the API endpoint the change wouldn't be merged automatically. I think this is the same behavior for Gitea Actions that needs to call the proper automerge function internally after a successful check had been returned from the runner.

@lunny I guess that

https://github.com/go-gitea/gitea/blob/221b90d2891025b08cd083bb821d91a7f5722341/services/pull/review.go#L267
 
is missing a call to `MergeScheduledPullRequest()` function at module `automerge` when an approval had been granted and origin PR owner requested an automerge.

**Comment by JoaoVictorLouro** [comment]
Same issue on GitTea 1.21

Running on:
Gitea Version
1.21.0 built with GNU Make 4.4.1, go1.21.4 : bindata, timetzdata, sqlite, sqlite_unlock_notify
Database:
mysql (mariadb) 10.6.9
Act Runner:
0.2.6

All through docker (via docker-compose)

![image](https://github.com/go-gitea/gitea/assets/34715931/fe545aae-452e-44c5-bdc8-185e3aeef5b2)

Any chance we can fix this? Any ideas of where to start looking?

**Comment by henrygoodman** [comment]
I really hope re-invigorating the auto-merge will also allow us to expose some endpoint to check PR mergeability (from more than just a git perspective, considering reviews/checks/correct merge base etc).
