### ISSUE TITLE
Import existing repositories

### ISSUE THREAD

**Issue by replay111** [go-gitea/gitea#2445]
Hi,

is there any option to import my existing repositories? In gitlab there is an option like: gitlab:import:repos. Does gitea support similar feature?

**Comment by daviian** [comment]
Indeed, it's called migration.

**Comment by jlusiardi** [comment]
Hi,

after the github microsoft merger, are there any plans to integrate such a feature to gitea?

Regards
Joachim

**Comment by lunny** [comment]
I think this has been implemented. @jlusiardi

**Comment by jlusiardi** [comment]
@lunny : thanks, yes, you are correct. **It works for me with Version 1.4.2.**

Rerhaps this issue could be closed then?

**Comment by lds-sdl** [comment]
Hello 
how to work this migration please ?
I do not see it in version 1.4.2 
O-o

**Comment by jlusiardi** [comment]
Its under the + Sign. see the screen shot
![gitea_2445](https://user-images.githubusercontent.com/9431614/41541462-d4488e9e-7312-11e8-8411-e1a01534e10f.PNG)

**Comment by lunny** [comment]
@laurentducos You have to enable it on app.ini at first.

**Comment by lds-sdl** [comment]
Oh yes this migration work perfectly but that i want is batch processing -> https://discourse.gitea.io/t/massive-migration-from-disks/352

**Comment by lunny** [comment]
That's not supported now.

**Comment by lds-sdl** [comment]
would it be possible to implement this feature in gitea ?
