### ISSUE TITLE
Cannot change password "No help topic for 'change-password'"

### ISSUE THREAD

**Issue by domsl** [go-gitea/gitea#24450]
### Description

Hi,

I am trying to change my password for gitea running inside docker (via exec bash):

Tried to run `gitea` got a "expected user git" so I `su git` and run:

`gitea admin --config /data/gitea/conf/app.ini change-password --username myusername --password mynewpassrd`

I only get a response "No help topic for 'change-password'" and still cannot log in :/

Related to #23044 

### Gitea Version

Gitea version 1.17.0+rc1 built with GNU Make 4.3, go1.18.3 : bindata, timetzdata, sqlite, sqlite_unlock_notify

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

Docker via Docker compose

### Database

None

**Comment by eeyrjmr** [comment]
Try:

`gitea --config /data/gitea/conf/app.ini admin user change-password --username myusername --password mynewpassrd
`

**Comment by domsl** [comment]
Thanks!
