### ISSUE TITLE
Container registry Login always return Error Response from Daemon: get "https://111.222.234.50/v2/": EOF

### ISSUE THREAD

**Issue by jaelys** [go-gitea/gitea#24466]
### Description

Container registry Login always return Error Response from Daemon.

My conf/app.ini
```
[server]
APP_DATA_PATH    = /data/gitea
DOMAIN           = localhost
SSH_DOMAIN       = localhost
HTTP_PORT        = 3000
ROOT_URL         = http://111.222.234.50/

[packages]
ENABLED = true
```
Cmd
```
C:\>docker login 111.222.234.50
Username: user123
Password: 123456
Error response from daemon: Get "https://111.222.234.50/v2/": EOF
```
Do I have no correct understanding or setting?

### Gitea Version

1.19.2

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

ubuntu 22.04

### How are you running Gitea?

docker

### Database

SQLite

**Comment by wxiaoguang** [comment]
By default, docker requires HTTPS

**Comment by KN4CK3R** [comment]
And if you use port 3000 you need that too for docker login.
`docker login 111.222.234.50:3000`

**Comment by jaelys** [comment]
I use nginx proxy HTTPS to log in normally, but the push container image error occurs. I have checked the related issues of # 23708, # 24042, but referring to the solution is invalid for me

`error parsing HTTP 404 response body: invalid character 'N' looking for beginning of value: "Not found.\n"`

my app.ini
```
DOMAIN           = gitea.xxx.com
ROOT_URL         = https://gitea.xxx.com/
HTTP_PORT        = 3000
```
nginx.conf

```
server { 
     server_name gitea.poliz.cn;
     listen 80;      
     return 301 https://$host$request_uri; 
}

server {
     server_name gitea.xxx.com; 
     listen 443 ssl http2 ;
     include /etc/nginx/conf.d/_server_proxy.conf;
     proxy_cache off;		
		location / {
			proxy_pass http://111.222.234.50:3000/;			
		}
		
		location /v2/ {
			proxy_pass http://111.222.234.50:3000/v2/;
		    client_max_body_size 0;		    
		}
}
```
_server_proxy.conf

```
ssl_certificate     /etc/nginx/conf.d/certs/xxx.com_bundle.pem;
ssl_certificate_key /etc/nginx/conf.d/certs/xxx.com.key;
ssl_session_timeout 5m;
ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
ssl_ciphers ALL:!ADH:!EXPORT56:RC4+RSA:+HIGH:+MEDIUM:+LOW:+SSLv2:+EXP;
ssl_prefer_server_ciphers on;

proxy_set_header Host $host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-Host $host:$server_port;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Port $server_port;
proxy_set_header X-Forwarded-Proto $scheme;
```

**Comment by jaelys** [comment]
> 



> What command are you trying to execute? The log shows owner name or image name are missing. You must tag your image as `gitea.xxx.com/owner/image`

Thank you very much. I use vs2022 Push to the container registry. I need to fill in /user123 behind the original gitea.xxx.com to correct the OWNER path correctly

I have made mistakes that should not be made, thank you, thank you for the great project
