### ISSUE TITLE
User dropdown hidden on context row

### ISSUE THREAD

**Issue by silverwind** [go-gitea/gitea#24460]
### Description

There is a regression from https://github.com/go-gitea/gitea/pull/24393 with `g-menu-stackable-scrollable` which prevents the dropdown from showing on https://try.gitea.io/issues when clicking user button top-left:

<img width="232" alt="image" src="https://user-images.githubusercontent.com/115237/235431924-e8e42484-cce2-47b0-8095-af9f073e7b20.png">

I recommend removing such `overflow` hiding. It can not work with non-portalled dropdowns like fomantic's.

**Comment by wxiaoguang** [comment]
Well, it seems that it just unnecessary .... no idea why I wrote so ... will remove it

**Comment by silverwind** [comment]
I think I would just remove this `g-menu-stackable-scrollable`.

**Comment by wxiaoguang** [comment]
Remove unnecessary g-menu-stackable-scrollable #24462
