### ISSUE TITLE
Closing a PR fails (404 web page) if external issue tracker enabled, or no issue tracker enabled

### ISSUE THREAD

**Issue by smckown** [go-gitea/gitea#2447]
- Gitea version (or commit ref): 1.2.0-rc1 (binary install)
- Git version: 2.11.0
- Operating system: Ubuntu Linux 16.04 amd64
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

```
2017/09/01 11:47:16 [...ules/context/repo.go:527 func1()] [E] CheckUnit: You are not allowed to visit this repository unit: 2
```

## Description

* Start with a repository that is configured for no issue tracker, or an external issue tracker
* Create a PR
* Press the Close button on the PR page
* Result: 404 web page, and log message shown above
* PR is not removed

The problem does not appear if the builtin issue tracker is enabled.  In fact, to close the PR I can:

* Change to the builtin issue tracker
* Go close the PR
* Return to original issue settings (either no issue tracker, or external issue tracker)

Thanks!

**Comment by lunny** [comment]
A PR is also an issue. So if we closed the issues, then maybe all the PR related features should be hidden also.

**Comment by lafriks** [comment]
I don't think so. PR should still work even if issues is disabled

**Comment by lunny** [comment]
So we still have Issues tab and only list all the Pull Requests?

**Comment by lafriks** [comment]
No do not have issues tab, just PR tab but we have to function them properly

**Comment by smckown** [comment]
I suspect the following behavior is related to the same root cause.

With external issues enabled, and trying to create (or edit) a PR comment to add an issue reference of the form #NNNN, the Preview pane shows the comment as one might expect.  Yet on Save, gitea logs the message below and does not save the PR comment.

```
2017/09/04 07:20:31 [...ules/context/repo.go:527 func1()] [E] CheckUnit: You are not allowed to visit this repository unit: 2
```

If I enable builtin issues, add/edit a PR comment to include #NNNN, Save the comment, then re-enable external issues, then the PR comment displays correctly.

This behavior does not appear to apply to references of the form:

```
<org>/<repo>/#N
```

The above extended reference format seems to allow me to refer to one PR from another PR comment even when external issues are enabled.

**Comment by iamnumbersix** [comment]
Also a 404 on 1.2.0+rc2 if there is no issue tracker. Even without a PR. Might be related.
I can only access Repositories with issue trackers (internal) enabled.

`2017/09/06 20:50:41 [...routers/repo/view.go:274 Home()] [E] Home: Cannot find any unit on this repository which you are allowed to access`

**Comment by lunny** [comment]
@iamnumbersix your problem should be different from this one.

**Comment by webjoel** [comment]
Comment, start time tracker and add time tracker, error page 404 is returned too.

In my opinion, using external or internal issue tracker should not be related to the functionality of the pull request, the comment part is undisputed, in the case of the time tracker I may want to record activities in the pull request with no relation to an issue, just record of the work itself. However if this is not accepted, at least the time tracker options in the pull request should be hidden as well as enabled external tracker issue.
