### ISSUE TITLE
EasyMDE toolbar is broken

### ISSUE THREAD

**Issue by wxiaoguang** [go-gitea/gitea#24486]
Related to https://github.com/go-gitea/gitea/pull/24471

I think we should keep EasyMDE, or at least find an alternative. Because when writing Wiki page, it is useful.

![image](https://user-images.githubusercontent.com/2114189/235689373-470dc502-548b-41c4-9321-5baf01c89b31.png)

**Comment by silverwind** [comment]
An oversight, I thought https://github.com/go-gitea/gitea/pull/24448 had replaced all these toolbar icons, but apparently only some. I guess we should restore with Octicons.

**Comment by yardenshoham** [comment]
Shouldn't easymde ship its own font-awesome? Do we override its internal classes?

**Comment by wxiaoguang** [comment]
We can manually construct every toolbar button, to use other icon sets.

**Comment by silverwind** [comment]
Yes, my oversight there. If the restoration is too much work, we could drop it.

> Shouldn't easymde ship its own font-awesome? Do we override its internal classes?

No, it apparently has an option `autoDownloadFontAwesome` which downloads it from CDN, but of course we needed to disable that as we don't want such downloads to happen.
