### ISSUE TITLE
[Proposal] publish every PR linux binary to package registry / storage

### ISSUE THREAD

**Issue by wxiaoguang** [go-gitea/gitea#24484]
Benefits:

1. Eat our own dogfood for the package feature.
2. Maintainers could easily pull the binaries or images for the PRs to do quick tests.
3. Users could get the PR's dev build to test whether some bugs are fixed.

eg: `wget gitea.com/.../gitea-pr-12345`

eg: `docker pull official-gitea:latest` and replace the dev binary into the container to do quick (and safe) test

**Comment by lunny** [comment]
We need a PR to allow create packages even global package is disabled.

**Comment by lunny** [comment]
> Then publish to a S3 storage before gitea.com can be used?

I think it's OK for binaries. Maybe `https://dl.gitea.com/gitea/pr-12345/`. And when PR is closed, the binaries could be removed.
