### ISSUE TITLE
Failed authentication attempt is logged with text 'user does not exist' even when the user exists

### ISSUE THREAD

**Issue by MarekChr** [go-gitea/gitea#24498]
### Description

**Log entry:**
...ers/web/auth/auth.go:206:SignInPost() [I] [645256b1] Failed authentication attempt for **_user_** from **_ip_**: user does not exist [uid: 2, name: **_user_**, keyid: 0]

**Description**
I tried to fail authentication by using wrong password and I looked at the log file. There is failed authentication attempt information log with additional text: 'user does not exist', however user exists and I can login when provided good password.

**Expected Fix**
Log authentication attempt fail log without text 'user does not exist' when user exists

### Gitea Version

1.19.2

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

2.30.2

### Operating System

Debian

### How are you running Gitea?

Running binary gitea behind nginx proxy

### Database

PostgreSQL

**Comment by msalmanmasood** [comment]
Hitting the same on 1.20 running on RHEL8.4

~~~
ers/web/auth/auth.go:206:SignInPost() [I] Failed authentication attempt for skhan from 10.1x.6x.x:57086: user does not exist [uid: 0, name: xxxxx, keyid: 0]
~~~

**Comment by MarekChr** [comment]
> Hitting the same on 1.20 running on RHEL8.4 where
> 
> Gitea version 1.20.0+rc0-58-g28ed763f5 built with GNU Make 4.3, go1.20.5 : bindata, sqlite, sqlite_unlock_notify
> 
> ```
> ers/web/auth/auth.go:206:SignInPost() [I] Failed authentication attempt for skhan from 10.1x.6x.x:57086: user does not exist [uid: 0, name: xxxxx, keyid: 0]
> ```

I think `uid 0` means that the user really does not exist, but can not confirm that.
