### ISSUE TITLE
Documentation error: View .STL files

### ISSUE THREAD

**Issue by f-steff** [go-gitea/gitea#24502]
### Description

In the customization documentation, a solution to view .stl files is presented: [https://docs.gitea.io/en-us/administration/customizing-gitea/#example-stl-preview](https://docs.gitea.io/en-us/administration/customizing-gitea/#example-stl-preview)

When inserting the code in the footer, and attempting to view a .stl file, an `JavaScript error: Uncaught ReferenceError` error is shown.

Searching for a fix online, I found another gitea site that had .stl viewing working. I copied their javascript code to test and it worked right away.  It's basically the same code, but " are replaced with ', and some ; line endings are omitted.

I don't know why it's working, but I wanted to share my findings.

This is the code:

```
<script>
function lS(src){
  return new Promise(function(resolve, reject) {
    let s = document.createElement('script')
    s.src = src
    s.addEventListener('load', () => {
      resolve()
    })
    document.body.appendChild(s)
  });
}

if($('.view-raw>a[href$=".stl" i]').length){
  $('body').append(
    '<link href="/assets/Madeleine.js/src/css/Madeleine.css" rel="stylesheet">'
  );
  Promise.all([
    lS("/assets/Madeleine.js/src/lib/stats.js"),
	lS("/assets/Madeleine.js/src/lib/detector.js"), 
	lS("/assets/Madeleine.js/src/lib/three.min.js"), 
	lS("/assets/Madeleine.js/src/Madeleine.js")
  ]).then(function() {
    $('.view-raw')
	   .attr('id', 'view-raw')
	   .attr('style', 'padding: 0;margin-bottom: -10px;');
    new Madeleine({
      target: 'view-raw',
      data: $('.view-raw>a[href$=".stl" i]').attr('href'),
      path: '/assets/Madeleine.js/src'
    });
    $('.view-raw>a[href$=".stl"]').remove()
  });
}
</script>

```

### Gitea Version

1.19.2

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

Windows 11

### How are you running Gitea?

docker

### Database

PostgreSQL

**Comment by wxiaoguang** [comment]
You "new" code seems the same as the "old" one in document 

https://github.com/go-gitea/gitea/pull/24504#issuecomment-1533342836


And I have tested the code in official document from my side, there is no JS error.

So, you might introduce some mistakes when you were copying the code.
