### ISSUE TITLE
Wrong action method for mirror form

### ISSUE THREAD

**Issue by stevefan1999-personal** [go-gitea/gitea#24534]
### Description

There is no such method called "post gt-dib". This effectively defaulted to a GET request. Please fix this. 

### Screenshots

https://github.com/go-gitea/gitea/blob/78fdbaf186ce629ff9252dd457f00ae1e0d485cf/templates/repo/settings/options.tmpl#L94-L98

https://github.com/go-gitea/gitea/blob/78fdbaf186ce629ff9252dd457f00ae1e0d485cf/templates/repo/settings/options.tmpl#L172-L183

### Gitea Version

nightly

### Can you reproduce the bug on the Gitea demo site?

Yes

### Browser Version

Edge

**Comment by wxiaoguang** [comment]
Regression: Make Issue/PR/projects more compact, misc CSS tweaks (#24459)

**Comment by stevefan1999-personal** [comment]
@silverwind blame shows you are also in it too

**Comment by wxiaoguang** [comment]
No worry, I am writing a fix for it
