### ISSUE TITLE
Subgroups in Gitea

### ISSUE THREAD

**Issue by gruselglatz** [go-gitea/gitea#24542]
### Feature Description

Since 9.0 GitLab allows to create [subgroups for groups/organizations](https://about.gitlab.com/2017/03/22/gitlab-9-0-released/#subgroups-ce-ee), It would be great if we could do the same in Gitea.

    Subgroups Docs: https://docs.gitlab.com/ce/user/group/subgroups/

We would like to organize our Repos in Subgroups like in Gitlab but i think the old Issue is dead?
Could we reevaluate the feature pls, I think it would be a great addition to Gitea.
https://github.com/go-gitea/gitea/issues/1872

**Comment by KN4CK3R** [comment]
The other issue is not dead. Just nobody works on it.

> Let's stay to the topic, this is not place for discussion. If you have nothing to add that would contribute to implementing this feature in Gitea, just add reaction to issue. Otherwise if you want to see this issue fixed you will have to wait, implement yourself or pay someone to implement this for you.

https://github.com/go-gitea/gitea/issues/1872#issuecomment-1263720465

**Comment by gruselglatz** [comment]
@KN4CK3R The issue is/was basically dead. I couldn't Create a comment, or Upvote for it. The issue is linked on the official Website in the Feature list. So it seemed pretty important. And it seems strange to only give the normal "open-source" answer: Do it on your own or don't complain.

So thanks for Reopening the Issue and as i am no Go Programmer I have to apologize that I cant implement this feature on my own, which seems pretty important to a bunch of people.

**Comment by KN4CK3R** [comment]
I didn't know you can't vote in locked issues but besides that this issue does not add something of value I think. We are still aware of the other issue but noone is currently implementing or planning it.

**Comment by gruselglatz** [comment]
It added the value of reopening this other important issue. ;)

**Comment by lunny** [comment]
I have unlocked that issue #1872.
