### ISSUE TITLE
forbidden error

### ISSUE THREAD

**Issue by xfzhaoxd** [go-gitea/gitea#24560]
### Description

I use the administrator role to create an common user account and require the first login to change the password.

When I log in with a user account to change my password, access is denied, and the page prompts "Forbidden"。

### Gitea Version

1.19.0

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

Linux

### How are you running Gitea?

Docker Compose

### Database

MySQL

**Comment by lunny** [comment]
I cannot reproduce this. Can you tell me which username you created in try site?

**Comment by xfzhaoxd** [comment]
I created an account with the name 'user1', not an administrator.
I found that the URL that was redirected to after changing the password was incorrect, and the password modification was successful.

**Comment by lunny** [comment]
Yes, that redirection url maybe private for the common user. Let's close this one.
