### ISSUE TITLE
There are some difference between reviewed and unreviewed files on the left changed files tree.

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#24566]
When I want to have a glance for all unreviewed files, I want to take a look at the changed file tree. But there is no any difference between reviewed and unreviewed files on the left changed files tree.

**Comment by delvh** [comment]
I think I mentioned something similar once already:
I think it would be best to get rid of the "useless" `file` icon in the tree, and replace it with a readonly checkbox which file is already viewed.
We can even think about using `indeterminate` for files that have changed in the meantime.
That way, we don't need additional space and display additional information.
The only problem is keeping the checkboxes in sync with the actual files.

**Comment by lunny** [comment]
How about using different colors for viewed and unviewed files.
