### ISSUE TITLE
Populate users list in issues/comments via mentions

### ISSUE THREAD

**Issue by mmarif4u** [go-gitea/gitea#2456]
Gitea version : 04ec795

I am not sure if it is currently implemented and i have issues with it. But i cant find it working. 

What i mean is if i want to mention a user in issues or comments start @ and then username/login, it should populate a list matching that keywords. That way easy to select.

Off-topic: Is the teams mentions working in Gitea issues/comments?

**Comment by lafriks** [comment]
I think user autocomplete is not implemented yet

**Comment by bkcsoft** [comment]
I've suggested a lib for doing this over here https://github.com/gogits/gogs/issues/2957 namely https://github.com/spantaleev/suggestor.js/. Example 7 for usernames only, and 8 for usernames, teams, issues etc 🙂

**Comment by lunny** [comment]
resolved by https://github.com/go-gitea/gitea/pull/3136
