### ISSUE TITLE
Gitea Actions Log copies line numbers as well

### ISSUE THREAD

**Issue by uvulpos** [go-gitea/gitea#24578]
### Description

I tried to copy my gitea actions log into a messager service and discovered that my selection copied also the line numbers. So I had to remove them by hands. Would be nice, if they were not selectable

### Screenshots

<img width="820" alt="Screenshot 2023-05-07 at 20 36 32" src="https://user-images.githubusercontent.com/53957681/236696235-17ce934d-d9a3-4035-8188-e4d78474d068.png">

### Gitea Version

1.19.x

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

MacOS

### Browser Version

Waterfox G5.1.5

**Comment by wxiaoguang** [comment]
I guess adding a  `user-select: none` is good enough
