### ISSUE TITLE
Wrong avatars for authors in Commits tab

### ISSUE THREAD

**Issue by mmarif4u** [go-gitea/gitea#2457]
- Gitea version (or commit ref): 04ec795

Screenshots:

![selection_001](https://user-images.githubusercontent.com/1280585/30004551-4b804516-9104-11e7-8454-c0b5eaf2f9ac.png)

![selection_002](https://user-images.githubusercontent.com/1280585/30004557-637edcc2-9104-11e7-8f3c-118d7b24d6cb.png)

**Comment by mmarif4u** [comment]
Just to add:
- Clicking on individual commit hash under Commits tab also show the default site avatar.
![selection_003](https://user-images.githubusercontent.com/1280585/30004659-10f55466-9106-11e7-95c3-f2a25dd9d22e.png)
- Also shows the same avatar on dashboard page in front of commits. Not sure what icon should it show.
![selection_004](https://user-images.githubusercontent.com/1280585/30004667-3bb22fd0-9106-11e7-9190-7d2f6c338a0d.png)

**Comment by sapk** [comment]
Are you sure you commit with the good email ? You can see it executing `git log` in the repo.

**Comment by mmarif4u** [comment]
@sapk that would be the case for local pushes if email does not match. But all this is done on the web interface, no local system push/pull involved, which made me open this issue.

**Comment by ethantkoenig** [comment]
@mmarif4u A few questions to help us debug:
1. Have you set `DISABLE_GRAVATAR` to false in app.ini?
2. Do you see any error messages in the log (specifically [this message](https://github.com/go-gitea/gitea/blob/250f1236dc2455d5b5969f4bdc5ec0ab06ca81c0/models/action.go#L392))?
3. Can you provide steps to reproduce?

**Comment by mmarif4u** [comment]
@ethantkoenig 
1. It was set to true, even setting it to false has no effect.
2. Nope, nothing related to it in the log, gitea.log.
  ```
2017/09/11 22:04:22 [I] Log Mode: File(Trace)
2017/09/11 22:04:22 [I] XORM Log Mode: File(Trace)
2017/09/11 22:04:22 [I] Cache Service Enabled
2017/09/11 22:04:22 [I] Session Service Enabled
2017/09/11 22:04:22 [I] Git Version: 2.7.4
2017/09/11 22:04:22 [T] Doing: CheckRepoStats
2017/09/11 22:04:22 [T] Doing: ArchiveCleanup
2017/09/11 22:04:22 [I] SQLite3 Supported
2017/09/11 22:04:22 [I] Run Mode: Production
2017/09/11 22:04:22 [I] Listen: http://0.0.0.0:3000
2017/09/11 22:04:22 [I] LFS server enabled
2017/09/11 22:04:26 [D] Session ID: 66231c453f1c4f54
2017/09/11 22:04:26 [D] CSRF Token: 6kVLqX0k5x9oDlC7MoHMW4juvxs6MTUwNTEzNzU0MDU2Mjg3NDUwMQ==
2017/09/11 22:04:26 [D] Detected encoding: utf-8 (fast)
2017/09/11 22:04:26 [D] Template: repo/diff/page
2017/09/11 22:04:28 [D] Session ID: 66231c453f1c4f54
2017/09/11 22:04:28 [D] CSRF Token: 6kVLqX0k5x9oDlC7MoHMW4juvxs6MTUwNTEzNzU0MDU2Mjg3NDUwMQ==
2017/09/11 22:04:28 [D] Detected encoding: utf-8 (fast)
2017/09/11 22:04:28 [D] Template: repo/diff/page
2017/09/11 22:04:31 [D] Session ID: 66231c453f1c4f54
2017/09/11 22:04:31 [D] CSRF Token: 6kVLqX0k5x9oDlC7MoHMW4juvxs6MTUwNTEzNzU0MDU2Mjg3NDUwMQ==
2017/09/11 22:04:31 [D] Template: repo/commits
2017/09/11 22:04:36 [D] Session ID: 66231c453f1c4f54
2017/09/11 22:04:36 [D] CSRF Token: 6kVLqX0k5x9oDlC7MoHMW4juvxs6MTUwNTEzNzU0MDU2Mjg3NDUwMQ==
2017/09/11 22:04:36 [D] Template: repo/home
2017/09/11 22:04:42 [D] Session ID: 66231c453f1c4f54
2017/09/11 22:04:42 [D] CSRF Token: 6kVLqX0k5x9oDlC7MoHMW4juvxs6MTUwNTEzNzU0MDU2Mjg3NDUwMQ==
2017/09/11 22:04:42 [D] Template: repo/home
2017/09/11 22:04:46 [D] Session ID: 66231c453f1c4f54
2017/09/11 22:04:46 [D] CSRF Token: 6kVLqX0k5x9oDlC7MoHMW4juvxs6MTUwNTEzNzU0MDU2Mjg3NDUwMQ==
2017/09/11 22:04:46 [D] Detected encoding: utf-8 (fast)
2017/09/11 22:04:46 [D] Template: repo/diff/page
2017/09/11 22:04:48 [D] Session ID: 66231c453f1c4f54
2017/09/11 22:04:48 [D] CSRF Token: 6kVLqX0k5x9oDlC7MoHMW4juvxs6MTUwNTEzNzU0MDU2Mjg3NDUwMQ==
2017/09/11 22:04:48 [D] Template: user/dashboard/dashboard
2017/09/11 22:04:49 [D] Session ID: 66231c453f1c4f54
2017/09/11 22:04:49 [D] CSRF Token: 6kVLqX0k5x9oDlC7MoHMW4juvxs6MTUwNTEzNzU0MDU2Mjg3NDUwMQ==
2017/09/11 22:07:29 [D] Session ID: 44ff8a43d258c2e6
2017/09/11 22:07:29 [D] CSRF Token: 2pmgXuIn4T2-_CrPzNnbCfM-oac6MTUwNTEzNjkzMDkyNjQ5MTk3NQ==
2017/09/11 22:07:29 [D] Template: user/dashboard/dashboard
2017/09/11 22:07:29 [D] Session ID: 44ff8a43d258c2e6
2017/09/11 22:07:29 [D] CSRF Token: 2pmgXuIn4T2-_CrPzNnbCfM-oac6MTUwNTEzNjkzMDkyNjQ5MTk3NQ==
2017/09/11 22:07:32 [D] Session ID: 44ff8a43d258c2e6
2017/09/11 22:07:32 [D] CSRF Token: 2pmgXuIn4T2-_CrPzNnbCfM-oac6MTUwNTEzNjkzMDkyNjQ5MTk3NQ==
2017/09/11 22:07:32 [D] Template: repo/home
2017/09/11 22:07:35 [D] Session ID: 44ff8a43d258c2e6
2017/09/11 22:07:35 [D] CSRF Token: 2pmgXuIn4T2-_CrPzNnbCfM-oac6MTUwNTEzNjkzMDkyNjQ5MTk3NQ==
2017/09/11 22:07:35 [D] Detected encoding: utf-8 (fast)
2017/09/11 22:07:35 [D] Template: repo/home
2017/09/11 22:07:37 [D] Session ID: 44ff8a43d258c2e6
2017/09/11 22:07:37 [D] CSRF Token: 2pmgXuIn4T2-_CrPzNnbCfM-oac6MTUwNTEzNjkzMDkyNjQ5MTk3NQ==
2017/09/11 22:07:37 [D] Detected encoding: utf-8 (fast)
2017/09/11 22:07:37 [D] Template: repo/editor/edit
2017/09/11 22:07:37 [D] Session ID: 44ff8a43d258c2e6
2017/09/11 22:07:37 [D] CSRF Token: 2pmgXuIn4T2-_CrPzNnbCfM-oac6MTUwNTEzNjkzMDkyNjQ5MTk3NQ==
2017/09/11 22:08:03 [D] Session ID: 44ff8a43d258c2e6
2017/09/11 22:08:03 [D] CSRF Token: 2pmgXuIn4T2-_CrPzNnbCfM-oac6MTUwNTEzNjkzMDkyNjQ5MTk3NQ==
2017/09/11 22:08:03 [T] TriggerTask 'website-revamp/dev' by mian
2017/09/11 22:08:03 [T] DeliverHooks [repo_id: 1]
2017/09/11 22:08:03 [T] AddTestPullRequestTask [head_repo_id: 1, head_branch: dev]: finding pull requests
2017/09/11 22:08:03 [T] AddTestPullRequestTask [base_repo_id: 1, base_branch: dev]: finding pull requests
2017/09/11 22:08:03 [D] Session ID: 44ff8a43d258c2e6
2017/09/11 22:08:03 [D] CSRF Token: 2pmgXuIn4T2-_CrPzNnbCfM-oac6MTUwNTEzNjkzMDkyNjQ5MTk3NQ==
2017/09/11 22:08:03 [D] Detected encoding: utf-8 (fast)
2017/09/11 22:08:03 [D] Template: repo/home
2017/09/11 22:08:06 [D] Session ID: 44ff8a43d258c2e6
2017/09/11 22:08:06 [D] CSRF Token: 2pmgXuIn4T2-_CrPzNnbCfM-oac6MTUwNTEzNjkzMDkyNjQ5MTk3NQ==
2017/09/11 22:08:06 [D] Template: user/dashboard/dashboard
2017/09/11 22:08:06 [D] Session ID: 44ff8a43d258c2e6
2017/09/11 22:08:06 [D] CSRF Token: 2pmgXuIn4T2-_CrPzNnbCfM-oac6MTUwNTEzNjkzMDkyNjQ5MTk3NQ==
2017/09/11 22:08:13 [D] Session ID: 44ff8a43d258c2e6
2017/09/11 22:08:13 [D] CSRF Token: 2pmgXuIn4T2-_CrPzNnbCfM-oac6MTUwNTEzNjkzMDkyNjQ5MTk3NQ==
2017/09/11 22:08:13 [D] Detected encoding: utf-8 (fast)
2017/09/11 22:08:13 [D] Template: repo/diff/page
```
3. On the web interface, create a repo, create a file and commit it to the repo. Its the same for all users.

Its a local server on my machine.

**Comment by mmarif4u** [comment]
I have installed it on a VPS having https via nginx proxy, still the same issue.

**Comment by lafriks** [comment]
can you check in `user` table what is avatar guid for that user and check if file with such guid exists in avatar directory?

**Comment by mmarif4u** [comment]
Yes, the user table avatar field have the guid for the user which match the filename in `data/avatars`.

**Comment by mmarif4u** [comment]
Tested on another server and same problem.   
This is happening on web interface of Gitea. Screens below.

User avatar:
![selection_002](https://user-images.githubusercontent.com/1280585/34284877-195b48e4-e710-11e7-8852-1c37c2ddc9d1.png)

Repo:
![selection_001](https://user-images.githubusercontent.com/1280585/34284884-232193ec-e710-11e7-992e-a4ce35e8a3d7.png)

But if i push from my local machine with the same email, it shows the correct avatar.
![selection_003](https://user-images.githubusercontent.com/1280585/34284977-f5422c38-e710-11e7-8747-e73efb3c3377.png)

Which means that somehow email is missing or not passing when commit,merge happen on web.

**Comment by ntimo** [comment]
Is there any update on this? Would be awesome if the correct avatar would be shown, this always buggs me when I merge my branches via the webui.

**Comment by lunny** [comment]
@ntimo which version are you using?

**Comment by ntimo** [comment]
Also when changing code via the webui and committing it the wrong avatar is shown :(
Gitea version: 1.7.0

**Comment by sergey-dryabzhinsky** [comment]
Can you provide part of output of `git log` with these commits - local and web?
