### ISSUE TITLE
how to change the repository language?

### ISSUE THREAD

**Issue by myxland** [go-gitea/gitea#24581]
### Description

how to change the repository language like this?
<img width="899" alt="1123" src="https://user-images.githubusercontent.com/11535019/236718743-704374a0-4eb0-400a-ba0d-a34adda5063a.png">

### Gitea Version

1.19.3

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

docker

### Database

None

**Comment by yp05327** [comment]
It is automatically calculated by the highest percentage of each language's total size. 
For example, your repository have 10 html files with 5kb total size and 5 js files with 10kb total size.
Then the main language of this repository will be `JavaScript`(66.66%) not `HTML`(33.33%).
It can not be changed manually now.

**Comment by myxland** [comment]
tks~
but maybe manually is better
