### ISSUE TITLE
Some of the texts are missing in Firefox

### ISSUE THREAD

**Issue by mmarif4u** [go-gitea/gitea#2458]
- Gitea version (or commit ref): 04ec795

Firefox versions : 55, 57
OS : Ubuntu 16.04

![selection_001](https://user-images.githubusercontent.com/1280585/30005235-61348f3c-9110-11e7-99b9-eee3bddf25f2.png)

Is it only me?, while it works in Chromium/Chrome/Vivaldi etc.

**Comment by lafriks** [comment]
Can you reproduce that on try.gitea.io?

**Comment by jonasfranz** [comment]
Do you use a TLS (https://) connection?

**Comment by mmarif4u** [comment]
@JonasFranzDEV nope, its on my local machine.

@lafriks yes, here it is.
![selection_002](https://user-images.githubusercontent.com/1280585/30068781-5f15b460-9291-11e7-88d7-da4a5ed3478e.png)

But the interesting part is that i can reproduce it only this machine. I tested it on another machine with FF 55 and 57, it loads fine. Seems to me, my FF issue not Gitea i guess unless other people have it also.

**Comment by lafriks** [comment]
I think this can be closed than, most probably pc related issue, could be browser cache (font file broken or not loading)
