### ISSUE TITLE
Upstream branch missing in drop-down lists when creating pull request

### ISSUE THREAD

**Issue by rh101** [go-gitea/gitea#24585]
### Description

This issue occurred after the update of Gitea from v1.19.1 to v1.19.3.

A mirror of a github project was created in Gitea, as shown below:
![image](https://user-images.githubusercontent.com/8603230/236737429-df36f98d-d640-4e34-a74f-c29e463989a0.png)

A fork to an organization account was created from the "dev" branch of that mirrored repository, still under the same username:
![image](https://user-images.githubusercontent.com/8603230/236737698-811bf019-ea07-410a-a3eb-a7e8334936b6.png)

Now, if I am in the `TEST_ORG/axmol` fork, and I try to create a new pull request for the purpose of synchronising the fork with the latest changes from the upstream, I no longer see the upstream branch listed in the "merge into" and "pull from" drop-down lists:

![image](https://user-images.githubusercontent.com/8603230/236740829-9fc444a0-396e-4909-8976-6662a3f450d8.png)

In v1.19.1, it would have displayed the upstream "testuser/axmol:dev" as an option.  Once Gitea was updated to v1.19.3, it no longer shows the upstream link.

Is this a bug, or is there some setting that I need to change to get this working?

### Gitea Version

1.19.3

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

https://gist.github.com/rh101/8912193d230f8f89a9cc6437620f8795

### How are you running Gitea?

Running Gitea in Docker, from https://registry.hub.docker.com/r/gitea/gitea

### Database

PostgreSQL

**Comment by lunny** [comment]
Which repository did the last screenshot come from?

**Comment by rh101** [comment]
> Which repository did the last screenshot come from?

Mirrored repository is `testuser/axmol`

Fork of `testuser/axmol` is `TEST_ORG/axmol`.

The last screenshot is from a pull request being created in the fork.  In Gitea 1.19.1, that drop-down would display the origin repository branches, such as `testuser/axmol:dev` and `testuser/axmol:release`, but in 1.19.3, it does not display any of them.

**Comment by rh101** [comment]
If I type the following in the address bar, then suddenly all branches appear from both repositories in both the left and right drop-down lists:

`https://[gitea.server]/TEST_ORG/axmol/compare/dev...testuser/axmol:dev`

But, if I click on any item in either the "merge into" or "pull from" drop-downs, the contents of the drop-downs change to reflect only one of the repositories, being either `testuser/axmol` or `TEST_ORG/axmol`.

**Comment by Eddcapone** [comment]
We are also affected (tested on v1.20.2).
We created a mirror to a repository on bitbucket and forked that mirror.
Today I tried to update the master branch of my fork with the master branch from the mirror, but I only see the branches from my fork.

**Comment by rh101** [comment]
@Eddcapone For the time being, and to avoid messing with the URL etc, you can work-around the issue by doing everything via the CLI:

```
### After cloning the repo from your gitea server:
git remote add mirrored_repo https://MIRRORED_REPO_ADDRESS (in your case bitbucket repo address)
git checkout [YOUR_BRANCH]
git fetch mirrored_repo (or git fetch --all)
git merge mirrored_repo/[BRANCH_TO_MERGE]
git push
```

That will push the changes to your gitea repo.

**Comment by Eddcapone** [comment]
@rh101 Only our admin has access to the CLI, but thx.

**Comment by catfromplan9** [comment]
Is this ever getting fixed? Its been a month.

**Comment by catfromplan9** [comment]
> > Is this ever getting fixed? Its been months
> 
> ~It's not a bug, because it's a private repository and you don't have access to the repository, so you can't raise PRs. you need to grant access/add collaborators accordingly, and you'll be fine.~

not a private repo, its a public mirror i made using an organization i created. i find this the most convenient way to fork projects from github and have them on my gitea

**Comment by CaiCandong** [comment]
> not a private repo, its a public mirror i made using an organization i created. i find this the most convenient way to fork projects from github and have them on my gitea

Maybe it's been fixed and you can try it. https://github.com/go-gitea/gitea/pull/26785

**Comment by catfromplan9** [comment]
> > not a private repo, its a public mirror i made using an organization i created. i find this the most convenient way to fork projects from github and have them on my gitea
> 
> Maybe it's been fixed and you can try it. #26785

thank you very much, i'll wait for the release though. if you dont mind, tag me here when the release that includes your fix is out

**Comment by CaiCandong** [comment]
Already backported 
![image](https://github.com/go-gitea/gitea/assets/50507092/2ee4f09a-90ab-43f6-9544-ca936235f9d8)
