### ISSUE TITLE
`TestAPIRepoMigrate` fails when GitHub is down

### ISSUE THREAD

**Issue by silverwind** [go-gitea/gitea#24615]
https://github.com/go-gitea/gitea/actions/runs/4927752928/jobs/8805178261

```
    api_repo_test.go:360: 
        	Error Trace:	/home/runner/work/gitea/gitea/tests/integration/api_repo_test.go:360
        	Error:      	unexpected error '%v' on url '%s'
        	Test:       	TestAPIRepoMigrate
        	Messages:   	Migration failed: Clone: exit status 128 - fatal: unable to access 'https://github.com/go-gitea/test_repo.git/': The requested URL returned error: 503
        	            	.%!(EXTRA string=https://github.com/go-gitea/test_repo.git)

```

**Comment by wxiaoguang** [comment]
At that time, GitHub is down ..........

**Comment by silverwind** [comment]
Generally I think we should not have external dependencies in our tests so they work offline too.

Otherwise, adding some failed test retries in [gotestsum](https://github.com/go-gitea/gitea/pull/24528) may help.

**Comment by silverwind** [comment]
Right, so I guess to realistically test GH, it has to be GH. Might just go with the retry variant.

**Comment by silverwind** [comment]
Closing for now as it is rather unactionable.
