### ISSUE TITLE
Docs: Reverse Proxy Documentation should mention client_max_body_size for nginx

### ISSUE THREAD

**Issue by DanielGibson** [go-gitea/gitea#24612]
### Description

I had problems with Gitea behind an nginx reverse proxy when trying to push big git LFS files.
I configured nginx like described in https://docs.gitea.io/en-us/administration/reverse-proxies/#nginx

The problem apparently was that nginx has a default size limit for uploading via http (at least in the default configuration on Ubuntu?), which can be overriden with `client_max_body_size` (e.g. `client_max_body_size 0; for "no limit").
Example:
```
server {
    listen 80;
    server_name git.example.com;
    # DG: disable size checking for uploads to prevent LFS problems
    client_max_body_size 0;

    location / {
        proxy_pass http://127.0.0.1:3000;
        ...
```

### Gitea Version

any

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

behind a nginx reverse proxy

### Database

None

**Comment by wxiaoguang** [comment]
It's described in nginx doc:

http://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size

```
Context: http, server, location
```

It could be written in `http` or `server` or `location` , it depends on which scope you'd like to make it take affect.

**Comment by DanielGibson** [comment]
I think `server` is the right place for this purpose.

1MB obviously is much too low to be useful for LFS, so indeed it would be helpful if the gitea documentation mentioned that one most probably wants to increase that value (or set to 0 for "no limit"), especially when using LFS (but even if you just want to let people upload screenshots in the issue tracker those might be >1MB)

**Comment by DanielGibson** [comment]
oh sorry, must've missed that down there below all the other cases not relevant for me ;)

still: I think the posted config snippets should have this set (maybe with a short comment what it's for), so they work properly out of the box (instead of having to debug the problem later, maybe much later, at the first time someone tries to push a >1MB file)

**Comment by wxiaoguang** [comment]
Good point 👍  some documents structure is not that good .... 

And actually there are some bugs (eg: #23711 ), I think it's time to fine tune them.

**Comment by DanielGibson** [comment]
thanks a lot for making the change! :)
