### ISSUE TITLE
Unable to create Default Webhooks

### ISSUE THREAD

**Issue by kousu** [go-gitea/gitea#24624]
### Description

As of 9a0652f0b2e1d56e1187a9442e7f053dad453703, the current `main`, it is impossible to create Default Webhooks using `/admin/default-hooks/gitea/new`. They are instead added as system webhooks, producing these database rows; notice that `is_system_webhook = 1` in both:

```
sqlite> select * from webhook limit 3;
id|repo_id|owner_id|is_system_webhook|url|http_method|content_type|secret|events|is_active|type|meta|last_status|header_authorization_encrypted|created_unix|updated_unix
3|0|0|1|https://system-main|POST|1||{"push_only":true,"send_everything":false,"choose_events":false,"branch_filter":"*","events":{"create":false,"delete":false,"fork":false,"issues":false,"issue_assign":false,"issue_label":false,"issue_milestone":false,"issue_comment":false,"push":false,"pull_request":false,"pull_request_assign":false,"pull_request_label":false,"pull_request_milestone":false,"pull_request_comment":false,"pull_request_review":false,"pull_request_sync":false,"wiki":false,"repository":false,"release":false,"package":false}}|1|gitea||0||1683681122|1683681122
4|0|0|1|https://default-main|POST|1||{"push_only":true,"send_everything":false,"choose_events":false,"branch_filter":"*","events":{"create":false,"delete":false,"fork":false,"issues":false,"issue_assign":false,"issue_label":false,"issue_milestone":false,"issue_comment":false,"push":false,"pull_request":false,"pull_request_assign":false,"pull_request_label":false,"pull_request_milestone":false,"pull_request_comment":false,"pull_request_review":false,"pull_request_sync":false,"wiki":false,"repository":false,"release":false,"package":false}}|1|gitea||0||1683681147|1683681147
```

### Gitea Version

9a0652f0b2e1d56e1187a9442e7f053dad453703

### Can you reproduce the bug on the Gitea demo site?

No -- but only because I don't have admin rights there

### Log Gist

https://gist.github.com/kousu/8cf00c3a7a6a032679a76d1bc2fda47b

### Screenshots

"Add a new default webhook":

![Screenshot 2023-05-09 at 21-12-16 Gitea Git with a cup of tea](https://github.com/go-gitea/gitea/assets/987487/dc176472-f678-4e14-9c1a-912e32bf519f)

Adds it as a system webhook:

![Screenshot 2023-05-09 at 21-12-30 Gitea Git with a cup of tea](https://github.com/go-gitea/gitea/assets/987487/0408bbc8-9bec-4745-9073-ab0aa751c4ed)

### Git Version

2.34.1

### Operating System

Ubuntu 22.04

### How are you running Gitea?

Built from git, run with `./gitea`

### Database

SQLite

**Comment by kousu** [comment]
This seems similar to https://github.com/go-gitea/gitea/issues/23139, in that it regards instability in the `/admin/hooks` API.

**Comment by lunny** [comment]
@kousu would you like to send a PR to fix it?

**Comment by kousu** [comment]
I will if I figure out what's wrong!

**Comment by kousu** [comment]
This doesn't appear on 8ceb78caad6c06fe66b27ca7c9b4144b3602e896 = v1.19.3; with that, it works as expected:

![Screenshot 2023-05-09 at 21-08-08 Gitea Git with a cup of tea](https://github.com/go-gitea/gitea/assets/987487/c8cbe29f-171c-4cca-be05-b47e27741d1d)

```
sqlite> select * from webhook limit 3;
id|repo_id|owner_id|is_system_webhook|url|http_method|content_type|secret|events|is_active|type|meta|last_status|header_authorization_encrypted|created_unix|updated_unix
1|0|0|0|https://whatsup|POST|1|sdfsdfsd|{"push_only":true,"send_everything":false,"choose_events":false,"branch_filter":"*","events":{"create":false,"delete":false,"fork":false,"issues":false,"issue_assign":false,"issue_label":false,"issue_milestone":false,"issue_comment":false,"push":false,"pull_request":false,"pull_request_assign":false,"pull_request_label":false,"pull_request_milestone":false,"pull_request_comment":false,"pull_request_review":false,"pull_request_sync":false,"wiki":false,"repository":false,"release":false,"package":false}}|1|gitea||0||1683680855|1683680855
2|0|0|1|https://system|POST|1|asfsdfsdf|{"push_only":true,"send_everything":false,"choose_events":false,"branch_filter":"*","events":{"create":false,"delete":false,"fork":false,"issues":false,"issue_assign":false,"issue_label":false,"issue_milestone":false,"issue_comment":false,"push":false,"pull_request":false,"pull_request_assign":false,"pull_request_label":false,"pull_request_milestone":false,"pull_request_comment":false,"pull_request_review":false,"pull_request_sync":false,"wiki":false,"repository":false,"release":false,"package":false}}|1|gitea||0||1683680885|1683680885
```

**Comment by kousu** [comment]
http://localhost:3000/admin/default-hooks/gitea/new generates 

```
<form class="ui form dirty" action="/admin/system-hooks/gitea/new" method="post">	
```

So it's the rendering side of the GET request that's confused.

PR in https://github.com/go-gitea/gitea/pull/24626 :tada:
