### ISSUE TITLE
[Summary] Improvements on actions run/job detail page

### ISSUE THREAD

**Issue by HesterG** [go-gitea/gitea#24625]
### Feature Description

<img width="1426" alt="Screen Shot 2023-05-09 at 17 07 50" src="https://user-images.githubusercontent.com/17645053/237049458-3556001a-40ce-4e66-a110-b2630241ecdb.png">

For this page, some improvements on ui can be made:

1. For the left panel, it is better to show rerun icon only on hover, and add style when the job is selected

    https://github.com/go-gitea/gitea/assets/17645053/55a95aec-7964-41e9-84c3-4ee4e3f47c4f

2. Move the rerun workflow icon to a consistent position. Probably move it to top right corner as a button, or add a management section under left panel

    <img width="1420" alt="Screen Shot 2023-05-10 at 09 55 50" src="https://github.com/go-gitea/gitea/assets/17645053/6a1b56a5-ed47-49ad-8eaa-25a69b8917c0">

    Possible option 1: Top right corner
    <img width="1430" alt="Screen Shot 2023-05-09 at 17 25 53" src="https://user-images.githubusercontent.com/17645053/237054299-a103f95d-d226-4883-a993-bc3e8d7efe60.png">

    Possible option 2: Add management section on left panel
    <img width="1186" alt="Screen Shot 2023-05-10 at 12 01 53" src="https://github.com/go-gitea/gitea/assets/17645053/ead58648-e1f7-4bf6-8230-b5160169aca7">

3. Adjust fonts (maybe generally smaller and use some secondary colors so the page will look more spatial), and add on hover effects to the log lines. And add loading effect when exanpanding the log.

    On hover effect:

    <img width="1052" alt="Screen Shot 2023-05-09 at 17 35 49" src="https://user-images.githubusercontent.com/17645053/237056784-d4e9eeec-e4a5-4d80-be2c-e6bbe6aef9c8.png">

    Loading when expanding log lines:

    https://github.com/go-gitea/gitea/assets/17645053/10bb45b7-d2df-4157-b796-142215765366

4. Add some left/right padding to the `action-view-container`

5. Add `gt-ellipsis` to summary lines
    
    <img width="930" alt="Screen Shot 2023-05-11 at 16 30 56" src="https://github.com/go-gitea/gitea/assets/17645053/c2c24830-b23a-48de-b5af-7ad5fd3eafee">

**Comment by wolfogre** [comment]
Some work has been done at #24611

**Comment by wolfogre** [comment]
One more thing, when loading the page, you will see an instant failure icon.


https://github.com/go-gitea/gitea/assets/9418365/94015057-ceaa-4f1c-8d71-dec69c6542e0

**Comment by silverwind** [comment]
> One more thing, when loading the page, you will see an instant failure icon.

Backend should render this initially on page load if possible, JS can then afterwards take over for dynamically updating.

> Adjust fonts (maybe generally smaller and use some secondary colors so the page will look more spatial)

Maybe tone down the bold in the fonts and use a lighter shade. Generally for the actions box, I think we should consider not using the console colors like currently. I would also consider actually making the console window have a light background on light theme. This black window just looks out of place in a light theme.

**Comment by HesterG** [comment]
> > One more thing, when loading the page, you will see an instant failure icon.
> 
> Backend should render this initially on page load if possible, JS can then afterwards take over for dynamic updates.
> 
I think this is because `ActionRunStatus` renders failure icon by default, should adjust that condition to only accept explicit action status.

**Comment by HesterG** [comment]
> For the "console box": Maybe tone down the bold in the fonts and use a less contrasting text color. I think we should consider not using the super contrastful console colors. 

I will try to use secondary colors as they are grey and should make less contrast.

> I would also consider actually making the console window have a light background on light theme. This black box just looks out of place in a light theme to me.

I am pretty bad at managing color themes, might need some help with this..

**Comment by silverwind** [comment]
I can probably check out the console box colors later.

Do people generally agree that white background on light theme is fine?

**Comment by wolfogre** [comment]
> Do people generally agree that white background on light theme is fine?

I would say I would agree only if I see the demo and it looks good. Because the console box is always black on Drone CI or GitHub Actions even if the theme is light. That's not a strong reason, just a stereotype.

<details>
<summary>Details</summary>

<img width="1250" alt="image" src="https://github.com/go-gitea/gitea/assets/9418365/2638039c-933b-4972-8990-caaf0e6a73e0">

<img width="1191" alt="image" src="https://github.com/go-gitea/gitea/assets/9418365/8f98d0d8-3775-4c0d-8f46-8306b86ee2c3">


</details>

**Comment by silverwind** [comment]
I think it goes against the theme's design to put a box of the opposing color scheme into the interface. In the past, many terminals where black, but today it's very much possible to run a light terminal as well and many do.

**Comment by lunny** [comment]
I never used a white background terminal...
