### ISSUE TITLE
Proposal: gitea dump should try to detect type from filename, if possible

### ISSUE THREAD

**Issue by DanielGibson** [go-gitea/gitea#24622]
### Feature Description

If a filename is given for `gitea dump` (`-f` or `--file`) and it has a file ending that corresponds to a supported `--type` and `--type` is not set, the type that corresponds to the filename should be automatically used.

For example, `gitea dump -f /path/to/mydump.tar` should create a tar (currently it would create /path/to/mydump.zip)

Not strictly necessary bonus-feature: Support some common alternative file-endings (like tgz for .tar.gz or .tbz for .tar.bz2)

**Comment by wxiaoguang** [comment]
Done by #30240
