### ISSUE TITLE
New commits does not show up in Dashboard and User Page

### ISSUE THREAD

**Issue by phellarv** [go-gitea/gitea#24680]
### Description

Dashboard and Userpage just show initial and imported commits. I have made multiple commiits to most repos, but it does not show up, except if I go into the repo-page.

### Screenshots

![2023-05-12_11-33_1](https://github.com/go-gitea/gitea/assets/822762/56650d47-fb76-477f-939b-9a41e424c30f)
![2023-05-12_11-33](https://github.com/go-gitea/gitea/assets/822762/9f4b4ae6-71b6-4972-87d9-4635ed22cbcb)

### Gitea Version

Gitea version 1.19.3 built with GNU Make 4.1, go1.20.4 : bindata, sqlite, sqlite_unlock_notify

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

Ubuntu 22.04

### Browser Version

Google Chrome 113.0.5672.92 (Official Build) (64-bit)

**Comment by wxiaoguang** [comment]
https://docs.gitea.io/en-us/help/faq/#push-hook--webhook-arent-running

**Comment by lunny** [comment]
And you can swith your current role in the left top dropdown. Some information will be displayed under some orgnization but not your peronsal feed.

**Comment by phellarv** [comment]
I will try to provide more info about my system, but it's a pretty basic new setup. Single user, no organization.
Imported a couple of already existing git repos. I pretty much haven't changed anything in the setting.
It's running behind a nginx which is the SSL-terminator. 
If you could give some idea what you need to reproduce I would be very thankful. 
One thing; There is no logs in /var/lib/gitea/logs 
gitea is running as the git user, and /var/lib/gitea is owned by the git user.

**Comment by wxiaoguang** [comment]
>  If you could give some idea what you need to reproduce I would be very thankful.

For example, could you help to create a new and clean VM, and setup a instance, reproduce and tell us the details setup steps ?


> "Imported a couple of already existing git repos."

How did you do that? If you create a new repo (not imported), does the new commit for that repo show in Dashboard?

**Comment by cppmm** [comment]
I also have this issue.
Gitea installed into kvm virtual machine behind the nginx reverse-proxy. Original installation was made many years ago. About a two week ago I moved gitea into vm and now have this issue. Nothing interesting in the logs. If I can give some debug information, please say what needed.

**Comment by wxiaoguang** [comment]
Have you tried: https://docs.gitea.io/en-us/help/faq/#push-hook--webhook-arent-running  ? >90% similar issues are related to it.

**Comment by cppmm** [comment]
Yes. I tried this hook. It works without errors, but nothing changed.

**Comment by wxiaoguang** [comment]
It seems that your database structure is out-of-sync.

What's your old instance? Was it upgraded from Gogs or restored by something? Does `gitea doctor --fix` work for you?

If it's difficult to resolve, I guess you can try to setup a new instance and adapt your existing repositories.

**Comment by cppmm** [comment]
@wxiaoguang thanks a lot!
There was problem with database. During export&import DB there was not exported `AUTO_INCREMET` options for id fields in database. After reexporting database structure I can creating new projects. And now I see new changes on dashboard. Unfortunately on dashboard there are not changes that was made after moving and before fixing database. In my case this is not a problem.
