### ISSUE TITLE
[Solutions] Fix `Mermaid➝flowchart➝click` event

### ISSUE THREAD

**Issue by editfund-founder** [go-gitea/gitea#24704]
### Description

# Solutions
### mermaid.js:

```diff
-      securityLevel: 'strict',
+      securityLevel: 'loose',
```

```diff
-      iframe.sandbox = 'allow-scripts';
+      iframe.sandbox = 'allow-popups allow-popups-to-escape-sandbox';
```

`chrome://settings/clearBrowserData`
### References:
https://codeberg.org/forgejo/forgejo/issues/734
https://codeberg.org/forgejo/forgejo/pulls/735

### Gitea Version

1.19.3.0

### Can you reproduce the bug on the Gitea demo site?

Yes

**Comment by silverwind** [comment]
In 1.20, we no longer set `sandbox`, so that part should be unnecessary. Not sure about the ramifications of `loose` security level.

https://github.com/go-gitea/gitea/blob/main/web_src/js/markup/mermaid.js
