### ISSUE TITLE
Repository Groups

### ISSUE THREAD

**Issue by evur** [go-gitea/gitea#24713]
### Feature Description

My proposal is to add the possibility to visually group repositories in the organization view.

This could be implemented as named dropdowns containing the repositories.

There could also be an option to automatically generate groups containing repositories with a specific prefix (e. g. "app-").

### Screenshots

Mockup:
![image](https://github.com/go-gitea/gitea/assets/63237520/4b7a753b-776b-46a6-a49f-7708d821dd89)

**Comment by wfjake** [comment]
Possible duplicate of #3840
