### ISSUE TITLE
How to assign an issue  to a organization member

### ISSUE THREAD

**Issue by o3o** [go-gitea/gitea#2471]
- Gitea version (or commit ref): 1.1.3
- Git version: 2.14.1
- Operating system: Linux
- Database (use `[x]`):
  - [ x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
I have an organization ACME with two  users Alice and Bob (admin. 
Bob creates a new issues but can not assign it to Alice: only "Bob" appears in the assignee list.

Is it a bug? If no how assign a issue to a organization member?
Thank you

**Comment by sentabi** [comment]
1. Create new team and add user example "CoreDeveloper", or add user to existing one.
2. On these  "CoreDeveloper" team add your user 
3. Add repository to these "CoreDeveloper" team 

![screenshot_2017-09-07_16-58-53](https://user-images.githubusercontent.com/203196/30157964-e6ebd826-93ed-11e7-8924-16f4346486b0.png)

..

![finally assigned able user](https://user-images.githubusercontent.com/203196/30158176-943c23e6-93ee-11e7-8b63-49acbd361107.png)

**Comment by lunny** [comment]
I think this is not an issue any more.
