### ISSUE TITLE
Filter translation documentations by the completeness like UI translation did

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#24715]
### Feature Description

If the documentation of one language has translated less than 30%, then remove them from the deployment.

**Comment by silverwind** [comment]
I'd also generally question the state of our Crowdin. French, German, Italian have close to 100% submission, but are lacking approvers, so these translation currently never make it into the product. I'm happy to help with german approval, if someone can add me there.

Also, it does not help that we are adding duplicate translations, we need to be more strict about these during review. See https://github.com/go-gitea/gitea/issues/24488 about it.
