### ISSUE TITLE
SERVE_DIRECT not functional for container registry

### ISSUE THREAD

**Issue by NOBLES5E** [go-gitea/gitea#24723]
### Description

Configuration:

```ini
[storage.packages]
STORAGE_TYPE               = minio
SERVE_DIRECT               = true
MINIO_ENDPOINT             = [redacted]
MINIO_ACCESS_KEY_ID        = [redacted]
MINIO_SECRET_ACCESS_KEY    = [redacted]
MINIO_BUCKET               = [redacted]
MINIO_LOCATION             = [redacted]
MINIO_USE_SSL              = true
MINIO_INSECURE_SKIP_VERIFY = false
```

### Gitea Version

1.19.3

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

Running from docker

### Database

SQLite

**Comment by KN4CK3R** [comment]
The container spec does [not allow redirects in the response](https://github.com/opencontainers/distribution-spec/blob/main/spec.md#endpoints).
