### ISSUE TITLE
Merge conflicts block the 'Mark as Manually Merged' operation

### ISSUE THREAD

**Issue by drsybren** [go-gitea/gitea#24729]
### Description

When a PR shows this message at the bottom:

>  This pull request has changes conflicting with the target branch.

it is no longer possible to mark the PR as 'manually merged'. This is the same for when the conflict checking is in progress, in such cases it's also impossible to just mark things as merged. Since conflict checking can take a lot of time, this is often a blocking issue for [the Blender project](https://projects.blender.org/blender/blender/).

### Gitea Version

https://github.com/blender/gitea/tree/blender-merged tracking Gitea `main` at ce5d711

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

Running our own branch.

### Database

PostgreSQL

**Comment by silverwind** [comment]
> it is no longer possible to mark the PR as 'manually merged'.

You think it's an regression? We did alter the PR merge box recently, so I suspect it came from that work.

**Comment by drsybren** [comment]
I'm not sure whether it's a regression or not. In any case I feel that it would be prudent to always have the option to close a PR as 'manually merged', regardless of any background processing that might be going on.

**Comment by wxiaoguang** [comment]
I guess it is a regression, I have left comments there

![image](https://github.com/go-gitea/gitea/assets/2114189/8676ec13-7ee8-4b22-9b0a-a4d5fd36b060)

**Comment by wxiaoguang** [comment]
On my side, I can see the "manual merge" form.

Do you have a reproducible example?

![image](https://github.com/go-gitea/gitea/assets/2114189/804becde-3496-4b9f-95ed-f46345445e93)
