### ISSUE TITLE
Labels for issues cannot be patched when updating through API

### ISSUE THREAD

**Issue by helgur** [go-gitea/gitea#24735]
### Description

(If this is an oversight I figure it is a bug, if it is not, it should be filed as a 'feature request')

Looking at the API documentation for the API, I can't update an issues labels through the API. The field for labels is missing from the patch endpoint but present in the post (create) endpoint

https://try.gitea.io/api/swagger#/issue/issueEditIssue

### Gitea Version

1.20.0

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

Gitea ran and installed from Linux binary: https://dl.gitea.com/gitea/1.19.0/gitea-1.19.0-linux-amd64

### Database

MySQL

**Comment by Zettat123** [comment]
https://try.gitea.io/api/swagger#/issue/issueReplaceLabels
You could use this API to update an issue's labels.

**Comment by helgur** [comment]
Thanks! That works
