### ISSUE TITLE
Cannot assign issue to someone or change milestone

### ISSUE THREAD

**Issue by rems4e** [go-gitea/gitea#2474]
- Gitea version (or commit ref): 1.1.4
- Git version: 2.11.0
- Operating system: Debian 9.1
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:
Nothing relevant, even in Trace level.

## Description
I created some issues yesterday and assigned them to myself. Today I want to remove the assignment.

When I try to select another user as assignee or select "remove assignees", the correct assignee (the other person or nobody) briefly appears, but immediately after that there is a page reload which brings me to the same issue, but with the assignee same as before I tried to change it.

Exactly the same is happening with the milestone selection.

However, when I create a new issue, the assignee is correctly set, even if I can't change it afterwards.

When enabling queries logging in the DB, I don't see any UPDATE (I'm using MariaDB) request apart of the request setting the issue as 'seen' by me, so it explains why the items are not updated :)

**Comment by lafriks** [comment]
I think this was fixed in master and should be fixed in 1.2.0

**Comment by rems4e** [comment]
I have tested it and it works in 1.2.0, indeed. Thanks, closing.
