### ISSUE TITLE
Automated provisioning of Actions runners

### ISSUE THREAD

**Issue by garymoon** [go-gitea/gitea#24750]
### Feature Description

Currently Actions runner tokens are retrieved from the web UI and are one-time use. This makes it difficult to provision runners in an automated fashion for CI and such.

[Woodpecker](https://woodpecker-ci.org/docs/administration/setup) and [Drone](https://docs.drone.io/runner/docker/installation/linux/) accept a symmetic secret via environment variables for both the application and the runners, making automated provisioning zero-touch. Could such a flow be considered for Gitea please?

P.S. Since it's Gitea issuing and validating the tokens it seemed more appropriate to open this issue here, but I'm happy to move or open a companion issue on act_runner instead :+1:

**Comment by delvh** [comment]
Isn't that already implemented by #23762?
An alternative to it would be offering an API route that would need to ensure that the caller is an admin for the respective scope.

**Comment by garymoon** [comment]
https://github.com/go-gitea/gitea/pull/23762 goes some way to making automation easier, but would still require executing the CLI in an automated fashion, extracting the token from the output, and applying it to the runner config, repeated for each runner. This would be particularly messy in an integration test.

Since runner tokens are just fixed-length random strings, would it be acceptable to have admin-supplied tokens/scopes retrieved from the ini with the ability to be reused?

**Comment by techknowlogick** [comment]
perhaps me completing this PR https://github.com/go-gitea/gitea/pull/23761 would be helpful

**Comment by benyanke** [comment]
Duplicate of #23703

**Comment by garymoon** [comment]
So it is, bugger it. Thanks @benyanke :blue_heart:
