### ISSUE TITLE
Display tags in commit list

### ISSUE THREAD

**Issue by KazzmanK** [go-gitea/gitea#24755]
### Feature Description

Is it possible to display tags associated with commits in commit list page ?

![image](https://github.com/go-gitea/gitea/assets/13328513/3bd7390d-14ee-4556-bfc1-57bad1092caa)

I have a tagged commit, but tag is not shown here. In my desktop tool it is.

ver 1.19.3

**Comment by silverwind** [comment]
Duplicate of https://github.com/go-gitea/gitea/issues/20167.
