### ISSUE TITLE
Git LFS GC does not work

### ISSUE THREAD

**Issue by MGerdel** [go-gitea/gitea#24763]
### Description

Running the new cron job that was introduced here: https://github.com/go-gitea/gitea/pull/22385 results in failure (see attachment).

### Gitea Version

1.19.3

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![grafik](https://github.com/go-gitea/gitea/assets/102671409/bcdbfb5c-08ac-48b6-997d-8a1132858021)

### Git Version

2.30.2

### Operating System

Debian GNU/Linux 11 (bullseye)

### How are you running Gitea?

Selhosted via systemd using https://github.com/go-gitea/gitea/releases/download/v1.19.3/gitea-1.19.3-linux-amd64

### Database

MySQL

**Comment by lunny** [comment]
It should be fixed by 3364092013aa4d5d27ad02806b0f47967c04de18
