### ISSUE TITLE
TypeError: undefined is not an object (evaluating '_i18n.textEdited')

### ISSUE THREAD

**Issue by HernanLencinas** [go-gitea/gitea#24770]
### Description

Some users are reporting that in the Gitea console, they are being shown the following error message:

JavaScript error: TypeError: undefined is not an object (evaluating '_i18n.textEdited') (https://git.cloudvalley.telecom.com.ar/assets/js/index.js?v=1.19.3 @ 54:663).
Open browser console to see more details.

Screenshot attached.

This happens randomly and from what we've observed, it mainly occurs with users using the Safari browser. We have checked the server and Gitea logs but haven't found any relevant error messages.

Users experiencing this issue also report that their user session is being closed, preventing them from working normally.

### Gitea Version

1.19.3

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/12104700/be49ab1c-df34-4eea-b6d3-8c7c52d4df7d)
![image](https://github.com/go-gitea/gitea/assets/12104700/d6c97214-2266-45e0-a785-d8e58897f5a8)

### Git Version

2.31.1

### Operating System

Linux

### How are you running Gitea?

We are running Gitea from the binary available at https://dl.gitea.com/gitea/1.19.3/gitea-1.19.3-linux-amd64 on a virtual server.

### Database

MySQL

**Comment by wxiaoguang** [comment]
Do you mean that, if a user sees the error, then they refresh page, then the refreshed page doesn't have the error?

**Comment by wxiaoguang** [comment]
I think I know the problem now.

Will propose a fix later (at most 1 day).

**Comment by HernanLencinas** [comment]
When users encounter that error message, it closes their session, and they have to log in again. Then, while browsing the repositories, it may or may not appear. It seems to be quite random.

When the same user tries it with Chrome, it works without any issues.

**Comment by wxiaoguang** [comment]
Oh .... if the user gets kicked-out, then that's another problem.

I think it has been fixed by https://github.com/go-gitea/gitea/pull/24330 

The related issue is https://github.com/go-gitea/gitea/issues/24176 , there are more details.


The fix is only in 1.20 (you can try nightly), but it's not easy to backport ....

According to my test, disabling Safari's "prevent cross-site tracking" could help.

**Comment by HernanLencinas** [comment]
> Oh .... if the user gets kicked-out, then that's another problem.
> 
> I think it has been fixed by #24330
> 
> The related issue is #24176 , there are more details.
> 
> The fix is only in 1.20 (you can try nightly), ~but it's not easy to backport~ hmm, not difficult.
> 
> According to my test, disabling Safari's "prevent cross-site tracking" could help.
> 
> I can try to send a partial backport to 1.19

On our side, we can try upgrading to version 1.20 over the weekend, and once it's done, test again to see if the issue is solved.

**Comment by liyimeng** [comment]
Same problem here.

**Comment by wxiaoguang** [comment]
> Same problem here.

It could be another problem IMO. This issue about "user randomly gets logged out".

**Comment by wxiaoguang** [comment]
I think this issue could be close since  #24772   has been backported to 1.19 nightly.

Feel free to reopen if there is any other problem.

**Comment by liyimeng** [comment]
Is this fixed in 1.20.0. I upgrade this version, but still get the same errors

`JavaScript error: TypeError: undefined is not an object (evaluating 'p.i18n.textEdited') (https://git.tdology.com/assets/js/index.js?v=1.20.0 @ 50:663). Open browser console to see more details.`


I have  safari `Version 16.4 (18615.1.26.110.1)`

**Comment by lunny** [comment]
> Is this fixed in 1.20.0. I upgrade this version, but still get the same errors
> 
> `JavaScript error: TypeError: undefined is not an object (evaluating 'p.i18n.textEdited') (https://git.tdology.com/assets/js/index.js?v=1.20.0 @ 50:663). Open browser console to see more details.`
> 
> I have safari `Version 16.4 (18615.1.26.110.1)`
> 
> The same problem on my iPhone.

Could you try to clear your web browser cache?
