### ISSUE TITLE
[Actions] Globally resolvable action names

### ISSUE THREAD

**Issue by silverwind** [go-gitea/gitea#24789]
# Issue

Currently when using this on gitea.com:

```
- uses: actions/setup-python@v4
```

It will resolve to instance-specific URL `https://gitea.com/actions/setup-python` which I see very problematic because it makes action names ambigous across multiple gitea instances and github itself (where this will work).

# Proposal

If the action URL is not absolute, assume a hardcoded `https://github.com/` prefix, just like podman and docker assume a `docker.io/` prefix on images not having a fully qualified name. This will ensure that action names are unambigously resolvable globally.

**Comment by delvh** [comment]
https://docs.gitea.com/administration/config-cheat-sheet#actions-actions `DEFAULT_ACTIONS_URL`?

**Comment by silverwind** [comment]
The option is good but it must not be an option, it needs to be hardcoded to ensure it stays globally resolveable.

**Comment by delvh** [comment]
That is not a good idea.

**Comment by delvh** [comment]
> I actually wish that DEFAULT_ACTIONS_URL (app.ini) is an array instead of a string.
With default value APP_URL (host your own actions via relative syntax), (https://gitea.com,
The last time I checked it was a place with mostly outdated copies of github),https://github.com

okay, I can understand that.
Should we reopen this issue as that, or open a separate issue for it?

**Comment by silverwind** [comment]
Looking closer at podman, it actually has a config that seems to default to:

```
unqualified-search-registries = ["docker.io", "quay.io"]
```

From that, I take it should be possible to define multiple search prefixes and I would suggest a default of `["https://github.com", "https://currentinstance.com"]`, with those URLs checked in sequence.

**Comment by silverwind** [comment]
Yeah, I understand that it's `gitea.com` on all instances. Still this is something I would set to `github.com` in all my instances and I would strongly suggest the default to be adjusted to that. GitHub Actions [does not](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsuses) support this prefix syntax, so the only way for workflows to be portable in the github -> gitea direction is with the proposed default.

**Comment by lunny** [comment]
I don't think github.com is better than gitea.com. Because some actions may need to be changed which cannot be used directly by Gitea. i.e. All actions which depend on GitHub APIs which Gitea APIs doesn't compatible will be run failed. For those actions, we need to fork and adjust them.

Considering 3 different Gitea instances.

1 Public Gitea instances
2 Private network Gitea instances that could connect to Internet.
3 Private network Gitea instances that cannot connect to Internet.

To satisfy all three situations, a configurable item is necessary.
And of course, if we can support multiple sites(less than 3), maybe it's better.
For 1 and 2, it could use `localhost, gitea.com, github.com`
For 3, it could use `localhost`

**Comment by silverwind** [comment]
Maybe we can have a vote:

- 1. 🎉  Set default to `https://github.com`
- 2. 🚀 Support multiple prefixes, e.g. `["https://github.com", "https://gitea.com"]` and search in sequence
- 3. ❤️  Set default to `https://gitea.com`

My option preference is 1 > 2, while 3 is unacceptable to me.

**Comment by lunny** [comment]
> Maybe we can have a vote:
> 
>     * 1. 🎉 Set default to `https://github.com`
> 
>     * 2. 🚀 Multiple prefixes, `["https://github.com", "https://gitea.com"]`
> 
>     * 3. ❤️ Set default to `https://gitea.com`
> 
> 
> My option preference is 1 > 2, while 3 is unacceptable to me.

Please read my comment above.

**Comment by silverwind** [comment]
> Because some actions may need to be changed which cannot be used directly by Gitea. i.e. All actions which depend on GitHub APIs which Gitea APIs doesn't compatible will be run failed. For those actions, we need to fork and adjust them.

Yes, but fork them under a new name so that `actions/foo` unambiguosly refers to the action on github while `https://gitea.com/actions/foo` refers to the one one gitea. This is how it works in docker where image name`foo` essentially always refers to `docker.io/foo`, and not another registry.

If we could convince GitHub to suppport a prefix, those actions would be even runnable (if compatible) on github.com.

**Comment by silverwind** [comment]
> Private network Gitea instances that cannot connect to Internet.

This is a valid concern, and a `https://localhost` entry would be need to set there, but it should not be the default.

**Comment by lunny** [comment]
👍  Could I vote `["https://gitea.com", "https://github.com"]`? So that we can override some compatible actions in github.com. Users' workflows could run both successes without changes.

**Comment by silverwind** [comment]
While not ideal, `["https://gitea.com", "https://github.com"]` for the default seems acceptable to me.

**Comment by silverwind** [comment]
I think we could extend `DEFAULT_ACTIONS_URL` with a comma syntax as comma is unlikely to appear in an URL, e.g.

```
DEFAULT_ACTIONS_URL = https://gitea.com, https://github.com
```

Trailing slash should be stripped while parsing the setting.

**Comment by silverwind** [comment]
I think we should also put out a recommendation to always use FQANs (fully qualified action names), eliminiating any ambiguity on where the repo is hosted, e.g.

```
https://gitea.com/actions/setup-python@4
```
instead of the ambiguous
```
actions/setup-python@4
```

We should also push github to support the FQAN syntax, as currently it's not possible to use actions hosted anywhere else than github.

**Comment by silverwind** [comment]
Another idea that comes to mind: docker images names omit the `https://` prefix, and I think this is something worth considering too. I think it should be possible to enforce that all actions should be hosted on `https` only, e.g. no `http`. This benefits both security and is less to type.

**Comment by yardenshoham** [comment]
Yes, that also feels more like docker

**Comment by silverwind** [comment]
Should be easy to accept all three forms:

```bash
https://github.com/actions/setup-python@4 # take as-is
github.com/actions/setup-python@4 # add 'https://' prefix
actions/setup-python@4 # resolve via DEFAULT_ACTIONS_URL
```

**Comment by silverwind** [comment]
> github actions syntax, path can contain multiple / or omitted

Ah, didn't know that action can be in subdirectories of a repo, yes that makes it ambiguous to parse, so probably skip that variant.

**Comment by silverwind** [comment]
I was toying with the idea of making [updates](https://github.com/silverwind/updates) support updating actions to latest versions locally, but given that the `DEFAULT_ACTIONS_URL` mechanism makes action URLs ambigous depending on instance configuration, it'll break in cases when `DEFAULT_ACTIONS_URL` is not `https://github.com` because `DEFAULT_ACTIONS_URL` is only resolved at the Gitea server, not the user's machine.

So I still strongly recommend we:

- Set `DEFAULT_ACTIONS_URL` to `https://github.com` by default, or even better, eliminate it completely so instances can not be configured to resolve action names ambigously
- Convince GitHub to support FQANs, making it possible to import Gitea-hosted action on Github Actions

This will ensure that when/if Gitea actions becomes popular, action names will always be unambigous globally and Users can seamlessly share actions between GitHub and Gitea instances.

**Comment by silverwind** [comment]
So I would propose the following course of actions:

- Deprecate `DEFAULT_ACTIONS_URL` in the runner in the next version
- Remove `DEFAULT_ACTIONS_URL` in the runner in the following version

The minor inconvenience of adding `https:/gitea.com` to all action names is meager in comparison to breaking the nascent actions ecosystem as a whole.

**Comment by lunny** [comment]
I don't think runner support `DEFAULT_ACTIONS_URL`?

**Comment by wolfogre** [comment]
> * Set `DEFAULT_ACTIONS_URL` to `https://github.com` by default, or even better, eliminate the option it completely so instances can not be configured to resolve action names ambigously
> * Clearly document that non-GitHub-hosted actions need to be specified as FQAN
> * Convince GitHub to support FQANs, making it possible to use Gitea-hosted actions on Github Actions
> 
> This will ensure that when/if Gitea actions becomes popular, action names will always be unambigous globally and users can seamlessly share actions between GitHub and Gitea instances. It will require a bit more verbose syntax, but I think it's only for the better:
> 
> * Use `actions/checkout@v3` to refer to the github.com action
> * Use `https://gitea.com/actions/checkout@v3` to refer to the gitea.com action
> * Use `https://codeberg.org/actions/checkout@v3` to refer to the codeberg.org action

I agree with @silverwind. We had to use `DEFAULT_ACTIONS_URL` because the act runner did not support `uses: https://gitea.com/xxx` at first, but now, the confusion it brings is greater than the convenience it brings.

**Comment by techknowlogick** [comment]
This sounds like a reasonable approach to me too

**Comment by silverwind** [comment]
> I don't think runner support `DEFAULT_ACTIONS_URL`?

Is it a gitea-only setting and gitea communicates the full URL to the runner?

https://github.com/go-gitea/gitea/blob/da6df0d0636c9e7bb5481e41dcd7d8f9b46deed5/modules/setting/actions.go#L16

I think we should get `DEFAULT_ACTIONS_URL=https://github.com` into v1.21, and likely document for v1.20 that the default will change next version.

**Comment by wolfogre** [comment]
I find a very strong reason to do what silverwind said. It's about security so we will talk about it in private.

**Comment by silverwind** [comment]
Don't have time right now, but will check it later there.

**Comment by silverwind** [comment]
One niceity we can allow ommitting the protocol, so `github.com` prefix is equal to `https://github.com` etc. It saves a bit of typing and is still unambiguous. This is also how docker does it, but I'm of the opinion we should support both with and without protocol.

**Comment by wolfogre** [comment]
> One niceity we can allow ommitting the protocol, so `github.com` prefix is equal to `https://github.com` etc. It saves a bit of typing and is still unambiguous because after the URL origin, the `user/repo` format is always to strings separated by `/`. This is also how docker does it, but I'm of the opinion we should support both with and without protocol.

I understand, that's what I thought at the beginning, but unfortunately GitHub Actions already support `uses: x/y/z`, and `z` means sub folder, like `use: actions/cache/restore@v3`.

So it's tricky to distinguish `host/user/repo` and `user/repo/folder`.

**Comment by yardenshoham** [comment]
docker treats it as a host if it has `.` or `:`, otherwise it's a user

**Comment by wolfogre** [comment]
> docker treats it as a host if it has `.` or `:`, otherwise it's a user

Not ideal for this, what if `https://gitea.com/test.com/test`?

**Comment by yardenshoham** [comment]
It'll be the action `test.com/test` from the `https://gitea.com` instance

**Comment by silverwind** [comment]
Unfortunatly, gitea allows usernames with `.`, making it ambigous again with hostname. I think we should forbid `.` in at least new usernames.

**Comment by wolfogre** [comment]
`.` is not the point (although it is a "point" 😂). Even though GitHub/Gitea/GitLab/GitXX all forbid `.` in usernames, users can still use use custom git server which we never heard to host actions, right?

And it is also possible for hostname not to contain `.`, what if `localhost` or others hostnames definded in `/etc/hosts`? And the service names in `docker-compose.yaml` are available hostnames

**Comment by yardenshoham** [comment]
You'd do something like `localhost:80`

**Comment by wolfogre** [comment]
To be clear, I agree with any solution that can shorten the path of actions, as long as:

- `schema://host/user/name` still works, so that the user can still make it clear. And it is also possible to support more schemas, such as `file://`.
- No ambiguity, and no additional operations are required to disambiguate. For example, `host/user/name` means `default_schema://host/user/name` , but if the host does not contain `.`, you must add the port to the host.
- No guessing . For example, don't do something like pinging the hostname to check if it is a valid hostname.

Unfortunately, I cannot figure out a solution.

**Comment by ghnp5** [comment]
Hey!

I believe I understand why this change was made, and I'm happy to keep the default to "github".


However, I'd like to understand whether this means I should prefer the GitHub Actions instead of Gitea Actions, when referring to `uses:`.

For example, you mirrored a few actions, such as `checkout`.
Is it OK to use GitHub's version instead of Gitea's version?


Also, there are several actions in the marketplace that use the Octokit library, which I always believed I should avoid those, because they only work for GitHub and not Gitea, am I correct to say that?

I'm just wondering how "safe" it is to default to GitHub, hoping that I will never use an action from GitHub by accident, that could potentially damage my repos or Gitea instance, due to incompatibilities (when Gitea's mirror version would be more compatible).


Apologies if something of what I said above doesn't make sense :)

Thank you!

**Comment by wolfogre** [comment]
> For example, you mirrored a few actions, such as `checkout`. Is it OK to use GitHub's version instead of Gitea's version?

IIRC, yes, the mirror is just a mirror.

> Also, there are several actions in the marketplace that use the Octokit library, which I always believed I should avoid those, because they only work for GitHub and not Gitea, am I correct to say that?

Not really, of course the Octokit library is designed for GitHub not Gitea, however, Gitea has a certain degree of compatibility with GitHub, so I would say that most actions can be used on Gitea, even though they are developed based on Octokit. However, I cannot guarantee that all actions will be compatible. We are also working on identifying incompatible actions and making them compatible, but you know, it's a big task.

**Comment by ghnp5** [comment]
Thank you very much for your reply @wolfogre

That's really great to know that actions using Octokit are actually safe to use on Gitea!

I was trying to avoid any of those, so far :)

> but you know, it's a big task

Absolutely - I understand!

My question above was not at all intending to be a bad criticism - it was just asking for clarification.

The work you guys have done for Gitea Actions is outstanding. Well done, really!

I've just submitted another donation. I absolutely love what you do 🧡
