### ISSUE TITLE
500 Error When Creating New Repository

### ISSUE THREAD

**Issue by sdifru** [go-gitea/gitea#24785]
### Description

I run gitea on a local machine. Today I updated gitea to the latest version. When I created new repository, gitea return this page
![2023-05-18_10-05-1684379029](https://github.com/go-gitea/gitea/assets/123437835/e54c3446-dfab-4a3a-b20b-51c85f42bfdb)

### Gitea Version

Gitea version 1.19.3

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

arch linux

### How are you running Gitea?

I installed gitea with `sudo pacman -S gitea`. I run gitea with `systemctl`.

### Database

PostgreSQL

**Comment by wolfogre** [comment]
Could you please provide some logs?

**Comment by wxiaoguang** [comment]
https://docs.gitea.io/en-us/seek-help/

**Comment by sdifru** [comment]
I uninstalled and installed it again and it works now. It might be some configuration things.
