### ISSUE TITLE
Issues with ROOT_URL and Gitea base URL not updating in Synology Docker instance

### ISSUE THREAD

**Issue by tfraley** [go-gitea/gitea#24794]
### Description

Good day, 

I have a Docker instance running Gitea on a Synology device. I am encountering an issue where the ROOT_URL specified in app.ini is different from the URL being accessed, resulting in potential web functionality issues. Although the error message suggests editing app.ini, I am modifying var/packages/gitea/var/conf.ini instead. I am unsure if these files are equivalent. Additionally, the updated Gitea base URL is not reflected on the admin/config page, despite changes being visible in the conf.ini file. Is this a caching issue or a bug?

### Gitea Version

1.17.3

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

![CleanShot 2023-05-18 at 11 27 48@2x](https://github.com/go-gitea/gitea/assets/1166064/f216c767-b61b-4ad4-bfa6-70b13e7ada12)
![CleanShot 2023-05-18 at 10 02 40@2x](https://github.com/go-gitea/gitea/assets/1166064/92365e51-a3e5-498e-a19a-778f177a9cd8)

### How are you running Gitea?

Docker on synology

### Database

None

**Comment by techknowlogick** [comment]
Have you restarted the service after updating the config?

**Comment by tfraley** [comment]
> I think maybe you missed the `s`? It's `https://xxx` not `http://xxx`.

I added the S but didn't take

**Comment by tfraley** [comment]
> Have you restarted the service after updating the config?

I stoped and started both containers  and restarted docker it self

**Comment by yp05327** [comment]
Did you set the environment variable `GITEA__server__ROOT_URL`?

**Comment by tfraley** [comment]
Figured it out.. Feel free to close thank you
