### ISSUE TITLE
Login UX – SSO login options unclear to users

### ISSUE THREAD

**Issue by EternalDeiwos** [go-gitea/gitea#24808]
### Description

I get questions all the time from new users about how to login to Gitea using our SSO, and I've concluded that the login form is just not clear about the option to login from those options.

I would suggest we can:

1. ~~Place SSO options (if configured) at the top of the form~~
2. Make the SSO options look more like buttons
3. Create a better division between them
4. Clearly show that users can logon with SSO _OR_ they can use the username/password form

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/1040903/4b93ee8c-09c0-4089-893a-1afab76e1d5d)

<img width="1071" alt="image" src="https://github.com/go-gitea/gitea/assets/1040903/b8cab132-703b-453c-ba68-b5a9ae9fd5e7">

### Gitea Version

1.19.3

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

N/A

### Browser Version

N/A

**Comment by silverwind** [comment]
How do other sites do this? Any suggested mockup?

**Comment by HesterG** [comment]
I am trying to work on this one, and one small problem is that semantic has special background color and color for `.ui.facebook.button` class. So our `facebook.png` cannot be seen clearly. Should we change this png or overwrite  semantic colors here?

<img width="520" alt="Screen Shot 2023-05-31 at 15 02 15" src="https://github.com/go-gitea/gitea/assets/17645053/b229e6ee-bc4a-45ca-8216-f545e8766b64">

**Comment by silverwind** [comment]
Please convert all these icons to SVG. With SVG we have full control over the rendered color.
