### ISSUE TITLE
Garbage collect lfs meta objects task fails everytime

### ISSUE THREAD

**Issue by Shakthijuego** [go-gitea/gitea#24807]
### Description

When trying to run lfs garbage collector task. It failed every time with the following error. I am using sqlite

Task: Garbage collect LFS meta objects canceled: no such table: count_lfs_meta_object 

### Gitea Version

gitea-1.19.0

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

2.34.1

### Operating System

ubuntu

### How are you running Gitea?

From systemd

### Database

SQLite

**Comment by lunny** [comment]
duplicated with #24763
