### ISSUE TITLE
Files are viewed on too new commits

### ISSUE THREAD

**Issue by delvh** [go-gitea/gitea#24813]
### Description

Apparently, the `I've viewed this file` implementation is half broken now.
It's still working without complaint because it's "dangling on a single thread that hasn't been destroyed yet":
I've put in a safe-guard that apparently is the only reason it's still working: https://github.com/go-gitea/gitea/blob/f5ce2ed292a90041abd749a8db26671645648a43/routers/web/repo/pull_review.go#L277-L279
For some reason, the `head commit SHA` isn't set (anymore?), so reviews always get assigned to the newest commit which isn't necessarily the commit someone has reviewed (in case they had their tab open for long enough that other commits were pushed)
I've traced this bug back to https://github.com/go-gitea/gitea/blob/f5ce2ed292a90041abd749a8db26671645648a43/templates/repo/diff/box.tmpl#L142
as apparently `PullHeadCommitID` is empty/not present.
However, I have no idea why this would be the case or if it has always been that way, and simply no one noticed.
(I doubt it, I remember testing the whole functionality, and I would have probably noticed it if the head-commit was always empty)

### Gitea Version

1.20.0+dev-833-g040970c32

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

try.gitea.io/ gitea.com and from compiled from source

### Database

None

**Comment by sebastian-sauer** [comment]
I just checked this on my local machine and on gitea.com - for both 1.20 versions the headcommit is set.

![image](https://github.com/go-gitea/gitea/assets/1135157/9fcdd31b-9106-401a-a048-113e54bd49dd)

I've checked this PR: https://gitea.com/xorm/xorm/pulls/2241/files

**Comment by delvh** [comment]
Now I'm confused…
How can this happen?


---

For me, it isn't set for a private repo under my own user.
But yes, I can confirm that your link indeed displays the headcommit.

Could it be that (private?) user repos have this problem?
Or under what circumstances is the headcommit not set?

**Comment by lunny** [comment]
> Now I'm confused… How can this happen?
> 
> For me, it still isn't set for a private repo under my own user. But yes, I can confirm that your link indeed displays the headcommit.
> 
> Could it be that (private?) user repos have this problem? Or under what circumstances is the headcommit not set?

Which repositories could you paste here as an example?

**Comment by delvh** [comment]
Well… I've just published my previously private test repo on gitea.com where I can reproduce this issue:
https://gitea.com/delvh/test/pulls/1/files
![grafik](https://github.com/go-gitea/gitea/assets/51889757/e028e52d-e765-4465-b71b-d8afbad32a03)
I don't know, however, how long I'll leave it public.

**Comment by sebastian-sauer** [comment]
Steps to reproduce:

- Create a PR for a deleted file 
- Merge PR and delete the branch
- --> Now the headcommit of the deleted file will be empty.

**Comment by sebastian-sauer** [comment]
@delvh Looks like the context variable "PullHeadCommitID" is not set. 
When using "AfterCommitID" it looks like it's working - but i'm not sure if this covers all cases. Any opinions?

https://github.com/go-gitea/gitea/blob/main/templates/repo/diff/box.tmpl#L150
