### ISSUE TITLE
GPG:  Failed to extract signature

### ISSUE THREAD

**Issue by strk** [go-gitea/gitea#2481]
See https://try.gitea.io/strk/test/commit/bf48a08fdfa2bdfbede039a8fa9df10163307bca

Reproducing locally the error in the logs is:
```
 [E] SignatureRead err: Packet is not a signature
```

The commit was created with `git commit -S`

**Comment by strk** [comment]
\cc @sapk

**Comment by sapk** [comment]
@strk for information, the error should come directly for the lib the read the signature that we send to it. ~~~It maybe git output that has change with a updated version.~~~ I will have a look at it. 
~~~In the mean time could you give me your local git version ?~~~

**Comment by sapk** [comment]
<details>
      <summary>Debug information : </summary>

[git-module] Hit cache: b1914b4ea57cb895b132523411756ea757ef4959
[git-module] /home/sapk/gitea-repositories/sapk/test.git: git cat-file -p bf48a08fdfa2bdfbede039a8fa9df10163307bca
[git-module] stdout:
tree 489acf7437dc1358f89d1caf2a35bf811b8735b8
parent 7f841d9536824aca71d5e87b2134252d2b82da5c
author Sandro Santilli <strk@kbt.io> 1505039757 +0200
committer Sandro Santilli <strk@kbt.io> 1505039757 +0200
gpgsig -----BEGIN PGP SIGNATURE-----
 Version: GnuPG v1
 
 iD8DBQBZtRWO1sB9pKxWLa0RAiyqAJ9b2jhppgMPcQuBGFqJUcTrGqC03ACfc8k9
 6Sr9qaW035WmIgQ27rnY7tc=
 =Bha/
 -----END PGP SIGNATURE-----

removed line

[git-module] /home/sapk/gitea-repositories/sapk/test.git: git cat-file -p 7f841d9536824aca71d5e87b2134252d2b82da5c
[git-module] stdout:
tree e23e39c8831256eca3af1e27ce26709c94780b9d
parent 1137dc6c0440a026cd19243bd13932c347aa49e6
author strk <strk@kbt.io> 1485347664 +0000
committer strk <strk@kbt.io> 1485347664 +0000

Delete 'README.md'

[git-module] /home/sapk/gitea-repositories/sapk/test.git: git cat-file -p 1137dc6c0440a026cd19243bd13932c347aa49e6
[git-module] stdout:
tree ad2ac0650909f5bbf301809e7333ca91fd33395b
parent 6b3196faa95b59af6d60c5c9f454e25839adc114
author strk <strk@kbt.io> 1485347648 +0000
committer strk <strk@kbt.io> 1485347648 +0000

Add 'README.txt'

[git-module] /home/sapk/gitea-repositories/sapk/test.git: git cat-file -p 6b3196faa95b59af6d60c5c9f454e25839adc114
[git-module] stdout:
tree cbc8f992c75642f59ce9a92a91b5091a3f1d72df
author strk <strk@kbt.io> 1485347633 +0000
committer Gogs <gogs@fake.local> 1485347633 +0000

Initial commit

[{"id":26,"primary_key_id":"","key_id":"D6C07DA4AC562DAD","public_key":"xsDiBD+ntCQRBACEG9LH4KfeIkX9rA6QYBFOnJITj+qzOAqpLwMDic1tPvZw8yQ4QGJK3T45aPqHDfx7h2PhSn0qVQ7G8BuhRnIbtuIp4Ifft9dLhWO3t8snw1SYlAOS1m8PHsOIq2bp+rvoHLl8aBWXEOX7sUrxSxU+k097BVicOiF4Aag8wdHIBwCgn1Y/pt5n886NDaRTPDFJsG9CrfUD/0vqVcNLiJNX95OxHoa/Gz9v5anznDzyt6FzvUs2aet2z5XZSzRWSiULxuO1AHscz9b4P6R1MLqzdwqS7KJgOcjd1x2zan2jq3Z8IhiYgXcx8Jbejsmp/wkdI7wKbJI6c0XYE6A++n8QNWC/8f/6fpXnD/ZeVXuI7Atu99XK5zPABACCdxkCv3xbI/z73AtrZVkBRlY5RuItuk8Bm3kaRpN7+zm499kXve4PC8zeFxGWwQKUSnSdD8FBH8oLzWFRYo2BGQfaeGTFqYEYHZZZirNaLjW4DkCOXPjgj9gDln4m9QJCp++3jCPDfr0Ck2X0EkEV2l8O2W+q3MW1GGdmshRVNA==","emails":[{"email":"strk@kbt.io","verified":true}],"subkeys":[{"id":27,"primary_key_id":"D6C07DA4AC562DAD","key_id":"A1B822DE19ADCCA4","public_key":"zsBNBD+ntCUQBADN5obXyq8JZsFf1DpMEiKjk8muNaLePnF/fkbPYOTJ7M+T5XFR5giiVbeCjz6A0r737eZgrEPR9B+CRneOzmrX23b+s08FBrYCqz+H8itEWZcRDClK5iPiJI3Kol6rfYMsKOTJfYRc3nObcycEkufiFVP18u8OrF2RhnQFmJNXRwADBwP/ff/6OInxeMHL8T9Qwmis1hsMqZt90gRemIhzaviIuA0XJ+sR6hQ74bmEzYPfntMP9zwAjkZX7DUu0775Olr69nQifYZiPqGzwVDu7QYtL/4KcQ5J3bTcicjU3dZ55Dg0ABrGjCFY8geiG+yoxgVWsAyB0OOvD+WCWFHREzzY3mU=","emails":null,"subkeys":null,"can_sign":false,"can_encrypt_comms":true,"can_encrypt_storage":true,"can_certify":false,"created_at":"2003-11-04T14:13:57Z","expires_at":"0001-01-01T00:00:00Z"}],"can_sign":true,"can_encrypt_comms":false,"can_encrypt_storage":false,"can_certify":true,"created_at":"2003-11-04T14:13:56Z","expires_at":"0001-01-01T00:00:00Z"}]

</details>

**Comment by sapk** [comment]
I can reproduce localy and add a test. I will try to find what is wrong.

What I have found that it not the output of that has change. The sign is extract but the lib used for gpg doesn't validate the signature format ...

updating lib doesn't fix ...

**Comment by strk** [comment]
Local git version 2.1.4

**Comment by lunny** [comment]
Is this still a problem?

**Comment by techknowlogick** [comment]
Closing due to lack of feedback. Please re-open if needed 😄
