### ISSUE TITLE
LDAP group map multiline support

### ISSUE THREAD

**Issue by codefritzel** [go-gitea/gitea#24826]
### Feature Description

With more than one group mapping, the single-line text field can quickly become very confusing. How about replacing the input text field with a multiline textarea?

This would make it easier to deal with many LDAP groups.

### Screenshots

**text input (actual)**
![input_text](https://github.com/go-gitea/gitea/assets/118316875/5754b2f6-c820-4652-981b-7c36da2a509d)

**textarea (idea)**
![textarea](https://github.com/go-gitea/gitea/assets/118316875/ac637a1e-87d0-432a-94f1-b42adb33236f)

**Comment by wxiaoguang** [comment]
-> Minor UI improvements: logo alignment, auth map editor, auth name display #25043
