### ISSUE TITLE
Decoding failed when running gitea manager commands

### ISSUE THREAD

**Issue by brechtvl** [go-gitea/gitea#24836]
### Description

This command successfully restarts but prints an error message:
```
$ ./gitea manager restart
Internal Server Response Decoding Failed
unable to decode response "POST http://localhost:3000/api/internal/manager/restart": readObjectStart: expect { or n, but found s, error found in #1 byte of ...|success|..., bigger context ...|success|...
```

This command prints an error as well:
```
$ ./gitea manager processes
Internal Server Response Decoding Failed
unable to decode response "GET http://localhost:3000/api/internal/manager/processes?flat=false&no-system=false&stacktraces=false&json=false&cancel-pid=": func(*http.Response, *private.ResponseExtra) is unsupported type
```

I guess this was caused by #23687.

### Gitea Version

64f6a5d (main)

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

Own build, default configuration.

### Database

SQLite

**Comment by wxiaoguang** [comment]
Yes, it's a regression. Working on it.

**Comment by wxiaoguang** [comment]
Fix regression: access log template, gitea manager cli command #24838
