### ISSUE TITLE
Issue filter list looks not good on phone

### ISSUE THREAD

**Issue by yp05327** [go-gitea/gitea#24846]
### Description

![image](https://github.com/go-gitea/gitea/assets/18380374/d96c8f9a-7432-40f6-a2b1-6cdcdff0db5f)

https://try.gitea.io/yp05327/longnamelongnamelongnamelongnamelongnamelongnamelongnamelongname/issues

### Gitea Version

latest

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

try.gitea.io

### Database

None

**Comment by wxiaoguang** [comment]
IMO it's nearly unfixable at the moment, unless rewrite a lot of related code or use some hacky and fragile methods.

**Comment by puni9869** [comment]
I can take this up. Assign me.
