### ISSUE TITLE
How to find different versions of docs for Gitea

### ISSUE THREAD

**Issue by AlexCai26** [go-gitea/gitea#24862]
### Feature Description

Is there a way to find a specifc version of online document matching Gitea (Docker image, `1.19.3`)?
Checked on docs.gitea.io, failed to find a switch of versions or similar functions to switch between different versions of docs.

Was working on the upgrading of Gitea from '1.18.2' to '1.19.3'(latest stable, using docker image), and it ‘seems that the content on https://docs.gitea.io/en-us/ are being constantly updated. For instance, there are changes on key words on https://docs.gitea.io/en-us/administration/config-cheat-sheet/#log-log section today. For instance, the introduction of `ENABLE_SSH_LOG`.

For stability, the version of image is specified in the `docker-compose.yml`, e.g., `image: gitea/gitea:1.19.3`.
It seems the docs on the docs.gitea.io are not versionlized, then it is not convenient to check all the environment variables needed for the compose file for the version of gitea image.

**Comment by yardenshoham** [comment]
try https://docs.gitea.com/

**Comment by alex-ibb** [comment]
> try https://docs.gitea.com/

@yardenshoham Thank you~
