### ISSUE TITLE
User Profile Page  Tabs Have Inconsistent Layout and Style

### ISSUE THREAD

**Issue by yekanchi** [go-gitea/gitea#24871]
### Description

in the user profile page the `Packages` and `Projects` tab have small icons for user but other tabs have bigger profile picture with user info:

### **For Packages  And  Projects:**
![image](https://github.com/go-gitea/gitea/assets/25511175/2420d77b-ba25-4718-9ccb-c5d0d95e3079)
### **For Other Tabs:**
![image](https://github.com/go-gitea/gitea/assets/25511175/ce9636b3-fe11-4c46-a230-30d83eee5947)

### Gitea Version

1.19

### Can you reproduce the bug on the Gitea demo site?

Yes

### Browser Version

110

**Comment by lunny** [comment]
duplicated with #24848

**Comment by yekanchi** [comment]
this is not duplicate of #24848 
this issue is related to size of and position of user profile when switching between Tabs.

**Comment by yekanchi** [comment]
> duplicated with #24848

this is not duplicate of #24848 
this issue is related to size of and position of user profile when switching between Tabs.

**Comment by silverwind** [comment]
Yes, those pages should use all use the "big" style, and likely also leave less space between user box and page content.

**Comment by puni9869** [comment]
Please assign this to me

**Comment by puni9869** [comment]
This is the new UI.
![image](https://github.com/go-gitea/gitea/assets/80308335/be17dcd5-5884-4c7d-9f2e-fb63de121eb8)

Ui is distorted
![image](https://github.com/go-gitea/gitea/assets/80308335/0f571334-20fa-4c4e-97b7-3a0fc9230129)

Do I need to modify also 
tplProjects           base.TplName = "org/projects/list"
tplProjectsNew        base.TplName = "org/projects/new"

**Comment by silverwind** [comment]
Projects list renders in a few "full screen" places. It's likely that some CSS changes need to be done to it to make it behave in smaller spaces.

Take a look at `templates/shared/issuelist`, this is a template that is also rendered in many places, both big and small.

**Comment by yekanchi** [comment]
> This is the new UI. ![image](https://user-images.githubusercontent.com/80308335/242092522-be17dcd5-5884-4c7d-9f2e-fb63de121eb8.png)
> 
> Ui is distorted ![image](https://user-images.githubusercontent.com/80308335/242092659-0f571334-20fa-4c4e-97b7-3a0fc9230129.png)
> 
> Do I need to modify also tplProjects base.TplName = "org/projects/list" tplProjectsNew base.TplName = "org/projects/new"
> 
> @delvh
looks good.
the organizations page also have a similar problem. if you change the tabs you will notice the inconsistency.

**Comment by puni9869** [comment]
Fix :: https://github.com/go-gitea/gitea/pull/25029
