### ISSUE TITLE
No result in the Explorer page

### ISSUE THREAD

**Issue by axeloz** [go-gitea/gitea#2487]
- Gitea version (or commit ref): 1.2.0+rc1
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant

## Description

Hello, 

since version 1.2.0+rc1, one dev of my team can't get any search result from the explorer page (/explore/repos).

I have one organization (MyAgency) and two users: me (admin) and my dev (owner). All the repositories were added into this organization.
I can search anything in the Explore page and find all the repositories. But my dev can't, whatever he searches. This used to work before the upgrade.
 
FYI, the search works fine for my dev from the right block on the homepage. 

Thanks

Axel

**Comment by Morlinest** [comment]
@axeloz Can you try #2371?

**Comment by axeloz** [comment]
Hello @Morlinest 
I'm not sure what you want me to try. Do you want I apply the changes on the 14 modified files of the pull request ?

**Comment by Morlinest** [comment]
@axeloz Yes, I want you to try build gitea from that PR (apply changes or pull [branch](https://github.com/Morlinest/gitea/tree/fix/missing-collaborative-repositories)) and try if it solves your problem.

**Comment by axeloz** [comment]
@Morlinest I'm not sure I'm willing to do so as I use Gitea in production. 
I'll try to free some time to create a sandbox environment.

**Comment by Morlinest** [comment]
Sure, do it only if you can in safe env.

**Comment by lunny** [comment]
Which version of your browser? This cannot be reproduce in chrome on macOS.

**Comment by Morlinest** [comment]
@lunny I think this problem was solved.

@axeloz Can you confirm this?
