### ISSUE TITLE
Pull upstream/master into fork

### ISSUE THREAD

**Issue by carmenbianca** [go-gitea/gitea#2488]
- Gitea version (or commit ref): Unknown
- Git version: 2.14.1
- Operating system: openSUSE Tumbleweed
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

There is currently no way to pull changes made in upstream into your fork.  As a timeline:

- Fork third-party/project into you/project.

- third-party/project:master receives new commits.

- You want to update you/project:master to also contain those commits.

Ideally there would be a very simple button somewhere to achieve this. GitHub and GitLab currently solve this by creating a pull request against yourself, but that is rather clunky and fault-prone (you have to manually make sure to fast-forward). In Gitea I haven't yet found a way to create a pull request against yourself from the upstream repository, but even so it'd be nice just to have a simple button to achieve this task without a pull request.

**Comment by locness3** [comment]
I'd really like to have this; Even if it's creating a pull request like on github/lab.

**Comment by gfwing** [comment]
I found similar feature in 1.12.0-rc1 when I try the 1.12.0-rc1 yesterday.
![圖片](https://user-images.githubusercontent.com/45010883/82688706-e4b9f200-9c8b-11ea-8cc5-d9871f11e3d7.png)

**Comment by locness3** [comment]
Also, I had tried to manually put forkuser:branch in the compare url, but that didn't work. :/

**Comment by zeripath** [comment]
@locness3 The compare page fork options have been substantially improved on 1.12 - so that problem should disappear very soon.

**Comment by 6543** [comment]
It's posible
