### ISSUE TITLE
Unable to update language stats for ID and stats queue indexer.Index(1424) failed

### ISSUE THREAD

**Issue by hiifong** [go-gitea/gitea#24896]
### Description

I mirrored [the repository](https://github.com/itwanger/paicoding),Every time I restart gitea will report some error.

1. Unable to update language stats for ID
2. stats queue indexer.Index(1424) failed

![image](https://github.com/go-gitea/gitea/assets/89133723/ce92dc82-2398-47d8-bf59-395a3d51d34d)

### Gitea Version

v1.20+

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

Ubuntu

### How are you running Gitea?

./gitea web

### Database

MySQL

**Comment by wxiaoguang** [comment]
Unrelated problem: it seems that you use "conn" mode for your loggers , which is not correctly configured. I guess you could remove the "conn" mode for loggers.

For the duplicate key problem, is it possible to debug what the content of `stats`map  is in the `UpdateLanguageStats`, and what are the lagnuage_stat database records for the repo 1424  ?

**Comment by wxiaoguang** [comment]
OK, reproduced. The problem is this:

```
stats = {map[string]int64} 
 0 = Shell -> 5131
 1 = Java -> 961174
 2 = java -> 6992114
 3 = PHP -> 15460
 4 = SCSS -> 66518
 5 = PLpgSQL -> 266014
 6 = Groovy -> 2134
```

**Comment by hiifong** [comment]
What should I do for the second question?

**Comment by hiifong** [comment]
thank you
