### ISSUE TITLE
Add option to show outdated review comments

### ISSUE THREAD

**Issue by sebastian-sauer** [go-gitea/gitea#24913]
### Feature Description

Review comments get invalidated when for example the commit sha of the line they were created on changes. 
This may happen due to the code author adding some lines at the beginning of the file.

Now all invalidated / outdated code comments are not shown in "Files changed" tab.
In order to check those comments i'll have to switch between "Files changed" tab and the conversation tab.

A new option to show outdated comments in "Files changed" tab would allow me to at least view all comments for a file in "Files changed" tab.

Even better would be to try to find the new line number for a comment - but the option to show outdated comments would already improve reviewing code with gitea (at least in my opinion) a lot.

**Comment by lunny** [comment]
But some comments needs the context and the context may be changed.
Finding the new line number of course is a better solution if the comment line hasn't been changed.

**Comment by sebastian-sauer** [comment]
Upsource for example shows a warning on top of a comment like "Discussion is pointing to a modified code fragment" and a link to the original snippet. We could allow/add this (the old snippet is available).

**Comment by sebastian-sauer** [comment]
I've proposed a PR with screenshots of a possible solution - https://github.com/go-gitea/gitea/pull/24936

Happy to make changes based on your feedback.

**Comment by lunny** [comment]
At least, we need an option to disable it for those who don't want to see the outdated comment which will only make confusing.

**Comment by sebastian-sauer** [comment]
> At least, we need an option to disable it for those who don't want to see the outdated comment which will only make confusing.

The latest changes added an option to show outdated comments (will be stored in user settings if logged in) - so if you don't "enable" the feature by turning the option on, nothing should change and confuse.
