### ISSUE TITLE
500 Internal Server Error when using emoji in comments

### ISSUE THREAD

**Issue by smallw00d2211** [go-gitea/gitea#24929]
### Description

2023/05/25 11:41:04 ...rs/web/repo/issue.go:2797:NewComment() [E] [646f494f] CreateIssueComment: Error 1366 (HY000): Incorrect string value: '\xF0\x9F\x92\xAF ' for column 'content' at row 1

### Gitea Version

1.19.3

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

gitea docker image

### Database

MySQL

**Comment by lunny** [comment]
Please use utf8mb4
