### ISSUE TITLE
Indentation is displayed incorrectly

### ISSUE THREAD

**Issue by zhu-hongwei** [go-gitea/gitea#24939]
### Description

gitea web & vscode

<img width="1290" alt="image" src="https://github.com/go-gitea/gitea/assets/61079864/612a7ba2-d538-47cd-b2ef-ab2c0dfad44e">

---

github desktop

<img width="1317" alt="image" src="https://github.com/go-gitea/gitea/assets/61079864/78845c05-b43a-4348-acd3-89dc36f31b61">

### Gitea Version

1.18.3

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

1.18.3

### How are you running Gitea?

  it is being run from docke

### Database

None

**Comment by techknowlogick** [comment]
> Gitea Version
> 1.18.3

There have been many changes to the rendering since that version. Could you update to the latest stable version and try again?

**Comment by wxiaoguang** [comment]
No more feedback, I think this issue can be closed, feel free to reopen if there are more clues.
