### ISSUE TITLE
Cannot add attachment to issue without admin access

### ISSUE THREAD

**Issue by hakito** [go-gitea/gitea#24944]
### Description

I have an issue created by User A.

I try to add an attachment via API for user B. User B is in a Team with write permissions for issues (and everything else)

When I do an sudo upload for user B i get the error:

> user should have permission to write issue

But the user has the permission. When I login as user B and do it via the web interface everything works fine.

It only works via API when I give the team admin access.

### Gitea Version

1.20.0+dev-919-gf9cfd6ce5

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

docker

### Database

MySQL

**Comment by lunny** [comment]
Which endpoint are you using?

**Comment by lunny** [comment]
Maybe related #25019

**Comment by lunny** [comment]
> The endpoint is: POST `/repos/{owner}/{repo}/issues/{index}/assets`

Could you update the the latest version and try it again since #24767 merged.

**Comment by hakito** [comment]
No the error still occurs in Version: 1.20.0+dev-1002-g379ec1303
