### ISSUE TITLE
No option to delete attached file

### ISSUE THREAD

**Issue by KazzmanK** [go-gitea/gitea#24947]
### Description

Steps to reproduce
1. Create an issue
2. Add text, paste in an image
3. Image is saved as image.png
4. Save
5. Go edit last comment
6. Remove link to attached image from comment`s content
7. Paste image again
8. Save

Now you have two attachments image.png and only one of them can be deleted. After deleting one of them, the other remains and there is no controls to delete it.

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/13328513/13e9072d-7657-4d7c-a6b2-169f05f2e5f7)

### Gitea Version

1.19.3

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

win

### Browser Version

chrome 113

**Comment by puni9869** [comment]
This is working fine. If you see this error again please feel free to reopen again.
