### ISSUE TITLE
Mailer Configuration

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#24955]
### Description

Something went wrong.
When i try to send a Test Mail i get following Error-Message:
" Das Senden der Test-E-Mail an „***@***.com“ ist fehlgeschlagen: gomail: could not send email 1: exit status 78 "

Configuration in the app.ini is as following
[mailer]
ENABLED        = true
MAILER_TYPE    = sendmail
FROM           = ***@***.com
SENDMAIL_PATH  = /usr/bin/msmtp

curiously if i try on terminal ( echo "Test 1 from $(hostname -f)"| mail -s "Test 1 $(hostname -f)" ***@***.com )
 the mail will be send successfully. 
 
 Actually i cant find further information about the exit code 78

How can i fix this issue? Or is it possible to configure the connector with outlookmail on port 25? 

### Gitea Version

1.19.0

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

On Debian 11 provided on proxmox

### Database

MySQL

**Comment by alex-ibb** [comment]
Hi @ThSeyfarth
The Mailer function should be good to on ,at least on version 1.19.3.
It seems the format of the value of `FROM` is not expected. Directly change it to `YourName <my@domain.com>` and restart ?

A deeper inverstigation may be processed via:
1. configure the log mode to file, and restart the gitea, ref https://docs.gitea.com/next/help/support
2. try the `send testing email` function and check the latest content on the log file.

**Comment by ThSeyfarth** [comment]
Hey @alex-ibb 
tries to do so you recommend, but didn´t work.

app.ini
...
[mailer]
ENABLED        = true
#MAILER_TYPE    = sendmail
( changed because of log output:  Deprecated fallback `[mailer]` `MAILER_TYPE` present. Use `[mailer]` `PROTOCOL` instead. This fallback will be/has been removed in v1.19.0 ) 
PROTOCOL   = sendmail
FROM           = Admin <admin@tomstation.de>
SENDMAIL_PATH  = /usr/bin/msmtp
...
( for get logging )
[log]
LEVEL  = debug
MODE   = console,file
ROUTER = console,file
XORM   = console,file
ENABLE_XORM_LOG = true
FILE_NAME = gitea.log

[log.file.router]
FILE_NAME = router.log

[log.file.xorm]
FILE_NAME = xorm.log

Or did i missed something?

**Comment by alex-ibb** [comment]
the log says ?

**Comment by ThSeyfarth** [comment]
gitea.log


2023/05/28 13:34:35 ...dules/setting/log.go:331:initLogFrom() [I] Gitea Log Mode: File(File:debug)
2023/05/28 13:34:35 ...dules/setting/log.go:286:generateNamedLogger() [I] Router Log: Console(console:debug)
2023/05/28 13:34:35 ...dules/setting/log.go:286:generateNamedLogger() [I] Router Log: File(file:debug)
2023/05/28 13:34:35 ...dules/setting/log.go:286:generateNamedLogger() [I] Xorm Log: Console(console:debug)
2023/05/28 13:34:35 ...dules/setting/log.go:286:generateNamedLogger() [I] Xorm Log: File(file:debug)
2023/05/28 13:34:35 ...les/setting/cache.go:75:loadCacheFrom() [I] Cache Service Enabled
2023/05/28 13:34:35 ...les/setting/cache.go:90:loadCacheFrom() [I] Last Commit Cache Service Enabled
2023/05/28 13:34:35 ...s/setting/session.go:74:loadSessionFrom() [I] Session Service Enabled
2023/05/28 13:34:35 ...es/setting/mailer.go:236:loadMailerFrom() [I] Mail Service Enabled
2023/05/28 13:34:35 ...es/setting/mailer.go:247:loadRegisterMailFrom() [I] Register Mail Service Enabled
2023/05/28 13:34:35 ...es/setting/mailer.go:258:loadNotifyMailFrom() [I] Notify Mail Service Enabled
2023/05/28 13:34:35 ...s/storage/storage.go:175:initAttachments() [I] Initialising Attachment storage with type:
2023/05/28 13:34:35 ...les/storage/local.go:45:NewLocalStorage() [I] Creating new Local Storage at /var/lib/gitea/data/attachments
2023/05/28 13:34:35 ...s/storage/storage.go:165:initAvatars() [I] Initialising Avatar storage with type:
2023/05/28 13:34:35 ...les/storage/local.go:45:NewLocalStorage() [I] Creating new Local Storage at /var/lib/gitea/data/avatars
2023/05/28 13:34:35 ...s/storage/storage.go:191:initRepoAvatars() [I] Initialising Repository Avatar storage with type:
2023/05/28 13:34:35 ...les/storage/local.go:45:NewLocalStorage() [I] Creating new Local Storage at /var/lib/gitea/data/repo-avatars
2023/05/28 13:34:35 ...s/storage/storage.go:185:initLFS() [I] Initialising LFS storage with type:
2023/05/28 13:34:35 ...les/storage/local.go:45:NewLocalStorage() [I] Creating new Local Storage at /var/lib/gitea/data/lfs
2023/05/28 13:34:35 ...s/storage/storage.go:197:initRepoArchives() [I] Initialising Repository Archive storage with type:
2023/05/28 13:34:35 ...les/storage/local.go:45:NewLocalStorage() [I] Creating new Local Storage at /var/lib/gitea/data/repo-archive
2023/05/28 13:34:35 ...s/storage/storage.go:207:initPackages() [I] Initialising Packages storage with type:
2023/05/28 13:34:35 ...les/storage/local.go:45:NewLocalStorage() [I] Creating new Local Storage at /var/lib/gitea/data/packages
2023/05/28 13:34:35 ...ueue_disk_channel.go:159:Run() [D] [64733c4b-24] PersistableChannelQueue: mail Starting
2023/05/28 13:34:35 ...ueue_disk_channel.go:196:Run() [D] [64733c4b-24] PersistableChannelQueue: mail Skipping running the empty level queue
2023/05/28 13:34:35 ...ue/queue_bytefifo.go:334:Shutdown() [D] [64733c4b-24] level: mail-level Shutdown
2023/05/28 13:34:35 ...ueue_disk_channel.go:188:Run() [D] [64733c4b-28] PersistableChannelUniqueQueue: repo-archive Starting
2023/05/28 13:34:35 ...ueue_disk_channel.go:234:Run() [D] [64733c4b-28] PersistableChannelUniqueQueue: repo-archive Skipping running the empty level queue
2023/05/28 13:34:35 ...ue/queue_bytefifo.go:334:Shutdown() [D] [64733c4b-28] unique-level: repo-archive-level Shutdown
2023/05/28 13:34:35 ...ueue_disk_channel.go:159:Run() [D] [64733c4b-26] PersistableChannelQueue: notification-service Starting
2023/05/28 13:34:35 ...ueue_disk_channel.go:196:Run() [D] [64733c4b-26] PersistableChannelQueue: notification-service Skipping running the empty level queue
2023/05/28 13:34:35 ...ue/queue_bytefifo.go:334:Shutdown() [D] [64733c4b-26] level: notification-service-level Shutdown
2023/05/28 13:34:35 routers/init.go:143:GlobalInitInstalled() [I] SQLite3 support is enabled
2023/05/28 13:34:35 routers/common/db.go:21:InitDBEngine() [I] Beginning ORM engine initialization.
2023/05/28 13:34:35 routers/common/db.go:28:InitDBEngine() [I] ORM engine initialization attempt #1/10...
2023/05/28 13:34:36 routers/init.go:149:GlobalInitInstalled() [I] ORM engine initialization successful!
2023/05/28 13:34:36 ...ueue_disk_channel.go:159:Run() [D] [64733c4c] PersistableChannelQueue: push_update Starting
2023/05/28 13:34:36 ...ueue_disk_channel.go:196:Run() [D] [64733c4c] PersistableChannelQueue: push_update Skipping running the empty level queue
2023/05/28 13:34:36 ...ue/queue_bytefifo.go:334:Shutdown() [D] [64733c4c] level: push_update-level Shutdown
2023/05/28 13:34:36 ...er/issues/indexer.go:173:func2() [I] [64733c4c-3] PID 1605: Initializing Issue Indexer: bleve
2023/05/28 13:34:36 ...ueue_disk_channel.go:188:Run() [D] [64733c4c-5] PersistableChannelUniqueQueue: repo_stats_update Starting
2023/05/28 13:34:36 ...ueue_disk_channel.go:234:Run() [D] [64733c4c-5] PersistableChannelUniqueQueue: repo_stats_update Skipping running the empty level queue
2023/05/28 13:34:36 ...xer/stats/indexer.go:38:populateRepoIndexer() [I] Populating the repo stats indexer with existing repositories
2023/05/28 13:34:36 ...ue/queue_bytefifo.go:334:Shutdown() [D] [64733c4c-5] unique-level: repo_stats_update-level Shutdown
2023/05/28 13:34:36 ...ueue_disk_channel.go:188:Run() [D] [64733c4c-7] PersistableChannelUniqueQueue: mirror Starting
2023/05/28 13:34:36 ...ueue_disk_channel.go:188:Run() [D] [64733c4c-9] PersistableChannelUniqueQueue: webhook_sender Starting
2023/05/28 13:34:36 ...ueue_disk_channel.go:234:Run() [D] [64733c4c-7] PersistableChannelUniqueQueue: mirror Skipping running the empty level queue
2023/05/28 13:34:36 ...ueue_disk_channel.go:234:Run() [D] [64733c4c-9] PersistableChannelUniqueQueue: webhook_sender Skipping running the empty level queue
2023/05/28 13:34:36 ...ue/queue_bytefifo.go:334:Shutdown() [D] [64733c4c-9] unique-level: webhook_sender-level Shutdown
2023/05/28 13:34:36 ...ue/queue_bytefifo.go:334:Shutdown() [D] [64733c4c-7] unique-level: mirror-level Shutdown
2023/05/28 13:34:36 ...xer/stats/indexer.go:84:populateRepoIndexer() [I] Done (re)populating the repo stats indexer with existing repositories
2023/05/28 13:34:36 ...ueue_disk_channel.go:188:Run() [D] [64733c4c-12] PersistableChannelUniqueQueue: pr_patch_checker Starting
2023/05/28 13:34:36 ...ueue_disk_channel.go:234:Run() [D] [64733c4c-12] PersistableChannelUniqueQueue: pr_patch_checker Skipping running the empty level queue
2023/05/28 13:34:36 ...ue/queue_bytefifo.go:334:Shutdown() [D] [64733c4c-12] unique-level: pr_patch_checker-level Shutdown
2023/05/28 13:34:36 ...ueue_disk_channel.go:188:Run() [D] [64733c4c-14] PersistableChannelUniqueQueue: pr_auto_merge Starting
2023/05/28 13:34:36 ...ueue_disk_channel.go:234:Run() [D] [64733c4c-14] PersistableChannelUniqueQueue: pr_auto_merge Skipping running the empty level queue
2023/05/28 13:34:36 ...ue/queue_bytefifo.go:334:Shutdown() [D] [64733c4c-14] unique-level: pr_auto_merge-level Shutdown
2023/05/28 13:34:36 ...ueue_disk_channel.go:159:Run() [D] [64733c4c-16] PersistableChannelQueue: task Starting
2023/05/28 13:34:36 ...ueue_disk_channel.go:196:Run() [D] [64733c4c-16] PersistableChannelQueue: task Skipping running the empty level queue
2023/05/28 13:34:36 ...ue/queue_bytefifo.go:334:Shutdown() [D] [64733c4c-16] level: task-level Shutdown
2023/05/28 13:34:36 ...rvices/cron/tasks.go:147:RegisterTask() [D] [64733c4c-19] Registering task: update_mirrors
2023/05/28 13:34:36 ...rvices/cron/tasks.go:147:RegisterTask() [D] [64733c4c-19] Registering task: repo_health_check
2023/05/28 13:34:36 ...rvices/cron/tasks.go:147:RegisterTask() [D] [64733c4c-19] Registering task: check_repo_stats
2023/05/28 13:34:36 ...rvices/cron/tasks.go:147:RegisterTask() [D] [64733c4c-19] Registering task: archive_cleanup
2023/05/28 13:34:36 ...rvices/cron/tasks.go:147:RegisterTask() [D] [64733c4c-19] Registering task: sync_external_users
2023/05/28 13:34:36 ...rvices/cron/tasks.go:147:RegisterTask() [D] [64733c4c-19] Registering task: deleted_branches_cleanup
2023/05/28 13:34:36 ...rvices/cron/tasks.go:147:RegisterTask() [D] [64733c4c-19] Registering task: update_migration_poster_id
2023/05/28 13:34:36 ...rvices/cron/tasks.go:147:RegisterTask() [D] [64733c4c-19] Registering task: cleanup_hook_task_table
2023/05/28 13:34:36 ...rvices/cron/tasks.go:147:RegisterTask() [D] [64733c4c-19] Registering task: cleanup_packages
2023/05/28 13:34:36 ...rvices/cron/tasks.go:147:RegisterTask() [D] [64733c4c-19] Registering task: delete_inactive_accounts
2023/05/28 13:34:36 ...rvices/cron/tasks.go:147:RegisterTask() [D] [64733c4c-19] Registering task: delete_repo_archives
2023/05/28 13:34:36 ...rvices/cron/tasks.go:147:RegisterTask() [D] [64733c4c-19] Registering task: git_gc_repos
2023/05/28 13:34:36 ...rvices/cron/tasks.go:147:RegisterTask() [D] [64733c4c-19] Registering task: resync_all_sshkeys
2023/05/28 13:34:36 ...rvices/cron/tasks.go:147:RegisterTask() [D] [64733c4c-19] Registering task: resync_all_sshprincipals
2023/05/28 13:34:36 ...rvices/cron/tasks.go:147:RegisterTask() [D] [64733c4c-19] Registering task: resync_all_hooks
2023/05/28 13:34:36 ...rvices/cron/tasks.go:147:RegisterTask() [D] [64733c4c-19] Registering task: reinit_missing_repos
2023/05/28 13:34:36 ...rvices/cron/tasks.go:147:RegisterTask() [D] [64733c4c-19] Registering task: delete_missing_repos
2023/05/28 13:34:36 ...rvices/cron/tasks.go:147:RegisterTask() [D] [64733c4c-19] Registering task: delete_generated_repository_avatars
2023/05/28 13:34:36 ...rvices/cron/tasks.go:147:RegisterTask() [D] [64733c4c-19] Registering task: delete_old_actions
2023/05/28 13:34:36 ...rvices/cron/tasks.go:147:RegisterTask() [D] [64733c4c-19] Registering task: update_checker
2023/05/28 13:34:36 ...rvices/cron/tasks.go:147:RegisterTask() [D] [64733c4c-19] Registering task: delete_old_system_notices
2023/05/28 13:34:36 ...rvices/cron/tasks.go:147:RegisterTask() [D] [64733c4c-19] Registering task: gc_lfs
2023/05/28 13:34:36 routers/init.go:185:NormalRoutes() [D] Creating static HTML Renderer
2023/05/28 13:34:36 ...er/issues/indexer.go:203:func2() [D] [64733c4c-3] Created Bleve Indexer
2023/05/28 13:34:36 ...er/issues/indexer.go:269:func3() [I] [64733c4c-3] Issue Indexer Initialization took 90.35453ms
2023/05/28 13:34:36 ...ue/queue_bytefifo.go:158:Run() [D] [64733c4c-4] level: issue_indexer Starting
2023/05/28 13:34:36 cmd/web.go:220:listen() [I] [64733c4c-26] Listen: http://0.0.0.0:3000
2023/05/28 13:34:36 cmd/web.go:224:listen() [I] [64733c4c-26] AppURL(ROOT_URL): http://192.168.10.5:3000/
2023/05/28 13:34:36 cmd/web.go:227:listen() [I] [64733c4c-26] LFS server enabled
2023/05/28 13:34:36 ...s/graceful/server.go:62:NewServer() [I] [64733c4c-26] Starting new Web server: tcp:0.0.0.0:3000 on PID: 1605
2023/05/28 13:34:36 ...s/graceful/server.go:75:func1() [D] [64733c4c-26] Starting server on tcp:0.0.0.0:3000 (PID: 1605)
2023/05/28 13:35:27 ...s/context/context.go:218:HTML() [D] [64733c7f] Template: home
2023/05/28 13:35:29 ...s/context/context.go:218:HTML() [D] [64733c81] Template: user/auth/signin
2023/05/28 13:35:33 ...s/context/context.go:218:HTML() [D] [64733c85] Template: user/dashboard/dashboard
2023/05/28 13:35:40 ...s/context/context.go:218:HTML() [D] [64733c8c] Template: admin/dashboard
2023/05/28 13:35:42 ...s/context/context.go:218:HTML() [D] [64733c8e] Template: admin/config
2023/05/28 13:35:56 ...s/context/context.go:218:HTML() [D] [64733c9c-3] Template: admin/config

**Comment by ThSeyfarth** [comment]
router.log

2023/05/28 13:35:27 [64733c7f] router: completed GET / for 192.168.10.28:55358, 200 OK in 34.2ms @ web/home.go:32(web.Home)
2023/05/28 13:35:27 [64733c7f-2] router: completed GET /assets/css/index.css?v=1.19.0 for 192.168.10.28:55358, 200 OK in 36.1ms @ public/public.go:42(AssetsHandler)
2023/05/28 13:35:27 [64733c7f-3] router: completed GET /assets/js/webcomponents.js?v=1.19.0 for 192.168.10.28:55359, 200 OK in 0.2ms @ public/public.go:42(AssetsHandler)
2023/05/28 13:35:27 [64733c7f-4] router: completed GET /assets/css/theme-auto.css?v=1.19.0 for 192.168.10.28:55360, 200 OK in 0.2ms @ public/public.go:42(AssetsHandler)
2023/05/28 13:35:28 [64733c80] router: completed GET /assets/img/logo.svg for 192.168.10.28:55360, 200 OK in 0.1ms @ public/public.go:42(AssetsHandler)
2023/05/28 13:35:28 [64733c7f-5] router: completed GET /assets/js/index.js?v=1.19.0 for 192.168.10.28:55361, 200 OK in 205.9ms @ public/public.go:42(AssetsHandler)
2023/05/28 13:35:28 [64733c80-2] router: completed GET /assets/img/favicon.svg for 192.168.10.28:55361, 200 OK in 0.1ms @ public/public.go:42(AssetsHandler)
2023/05/28 13:35:29 [64733c81] router: completed GET /user/login?redirect_to=%2f for 192.168.10.28:55361, 200 OK in 21.4ms @ auth/auth.go:141(auth.SignIn)
2023/05/28 13:35:33 [64733c84] router: completed POST /user/login for 192.168.10.28:55361, 303 See Other in 128.1ms @ auth/auth.go:170(auth.SignInPost)
2023/05/28 13:35:33 [64733c85] router: completed GET / for 192.168.10.28:55361, 200 OK in 66.4ms @ web/home.go:32(web.Home)
2023/05/28 13:35:33 [64733c85-4] router: completed GET /avatars/32a6eaf17a984aa66fb3173d4fcef857?size=84 for 192.168.10.28:55359, 200 OK in 8.8ms @ web/base.go:29(avatars)
2023/05/28 13:35:33 [64733c85-2] router: completed GET /avatars/57cdfac687b6b7811b1617e34d784583?size=72 for 192.168.10.28:55358, 200 OK in 22.1ms @ web/base.go:29(avatars)
2023/05/28 13:35:33 [64733c85-5] router: completed GET /avatars/1897bbbf8eb7b7fe878117daa501e454?size=84 for 192.168.10.28:55363, 200 OK in 0.9ms @ web/base.go:29(avatars)
2023/05/28 13:35:33 [64733c85-7] router: completed GET /avatars/52cce83a61e10d204ac9f0aea00b7f72?size=84 for 192.168.10.28:55364, 200 OK in 88.4ms @ web/base.go:29(avatars)
2023/05/28 13:35:33 [64733c85-6] router: completed GET /avatar/6facc8622983e097839cea05fd365612?size=84 for 192.168.10.28:55361, 303 See Other in 118.2ms @ user/avatar.go:48(user.AvatarByEmailHash)
2023/05/28 13:35:33 [64733c85-8] router: completed GET /avatar/aeca44da2a5ba3d85bbd851fad4b3696?size=84 for 192.168.10.28:55363, 303 See Other in 96.4ms @ user/avatar.go:48(user.AvatarByEmailHash)
2023/05/28 13:35:33 [64733c85-9] router: completed GET /avatars/8ad3ab75eb2e7cd5548cac5d8fc78a1b?size=84 for 192.168.10.28:55359, 200 OK in 84.8ms @ web/base.go:29(avatars)
2023/05/28 13:35:33 [64733c85-3] router: completed GET /avatars/57cdfac687b6b7811b1617e34d784583?size=84 for 192.168.10.28:55360, 200 OK in 225.3ms @ web/base.go:29(avatars)
2023/05/28 13:35:33 [64733c85-10] router: completed GET /avatar/7bb61a5293a7f8ecfb4de61a8dd14436?size=84 for 192.168.10.28:55361, 303 See Other in 2.2ms @ user/avatar.go:48(user.AvatarByEmailHash)
2023/05/28 13:35:33 [64733c85-11] router: completed GET /repo/search?count_only=1&uid=1&team_id=0&q=&page=1&mode= for 192.168.10.28:55361, 0  in 26.6ms @ repo/repo.go:472(repo.SearchRepo)
2023/05/28 13:35:33 [64733c85-12] router: completed GET /assets/js/eventsource.sharedworker.js?v=1.19.0 for 192.168.10.28:55361, 200 OK in 0.1ms @ public/public.go:42(AssetsHandler)
2023/05/28 13:35:33 [64733c85-14] router: completed GET /repo/search?sort=updated&order=desc&uid=1&team_id=0&q=&page=1&limit=15&mode=&archived=false for 192.168.10.28:55358, 200 OK in 10.2ms @ repo/repo.go:472(repo.SearchRepo)
2023/05/28 13:35:37 [64733c4c-25] router: polling   GET /user/events for 192.168.10.28:55361, elapsed 3589.6ms @ events/events.go:18(events.Events)
2023/05/28 13:35:40 [64733c85-13] router: completed GET /user/events for 192.168.10.28:55361, 200 OK in 6217.8ms @ events/events.go:18(events.Events)
2023/05/28 13:35:40 [64733c8c] router: completed GET /admin for 192.168.10.28:55360, 200 OK in 22.5ms @ admin/admin.go:116(admin.Dashboard)
2023/05/28 13:35:42 [64733c8c-2] router: completed GET /user/events for 192.168.10.28:55358, 200 OK in 2355.5ms @ events/events.go:18(events.Events)
2023/05/28 13:35:42 [64733c8e] router: completed GET /admin/config for 192.168.10.28:55360, 200 OK in 9.9ms @ admin/config.go:101(admin.Config)
2023/05/28 13:35:46 [64733c4c-25] router: polling   GET /user/events for 192.168.10.28:55360, elapsed 3321.4ms @ events/events.go:18(events.Events)
2023/05/28 13:35:56 [64733c8f] router: completed GET /user/events for 192.168.10.28:55360, 200 OK in 13632.1ms @ events/events.go:18(events.Events)
2023/05/28 13:35:56 router: completed POST /admin/config/test_mail for 192.168.10.28:55359, 303 See Other in 156.3ms @ admin/config.go:31(admin.SendTestMail)
2023/05/28 13:35:56 [64733c9c-3] router: completed GET /admin/config for 192.168.10.28:55359, 200 OK in 8.1ms @ admin/config.go:101(admin.Config)
2023/05/28 13:36:00 [64733c4c-25] router: polling   GET /user/events for 192.168.10.28:55359, elapsed 3195.1ms @ events/events.go:18(events.Events)

**Comment by alex-ibb** [comment]
Hi Th,

Failed to find records on the execution of `send the test mail`.

How about :
1. Try change the `FROM = Admin admin@tomstation.de` to `FROM = Admin <admin@tomstation.de>` ?
2. For the `mailer` block in `app.ini`, for Gitea `v1.19.3`, mine is like:
```ini
[mailer]
ENABLED   = true
SMTP_ADDR = smtp.livegitea.com
SMTP_PORT = 465
FROM      = MyGitea <dev@livegitea.com>
USER      = admin@livegitea.com
PASSWD    = livegitealivegitealivegitea
```
Other key words are using default value, use it as a template first to check if works, then consider to add other key words like `SENDMAIL_PATH`?

**Comment by ThSeyfarth** [comment]
It works right now. Mailer configuration actually runs with outlook-mailer easily. So it wasnt a real bug but layer 8 problem like so often. 
Many thanks for your advice.
