### ISSUE TITLE
Doubled feed in the dashboard and activity

### ISSUE THREAD

**Issue by schast** [go-gitea/gitea#2495]
- Gitea version (or commit ref): 1.2.0
- Git version: 1.8.3.1
- Operating system: Red Hat Enterprise Linux Server release 7.3 (Maipo)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:
[xorm.log.txt](https://github.com/go-gitea/gitea/files/1298105/xorm.log.txt)

## Description
i still get double entries in the dashboard activity on some of my repos.
`INSERT INTO action` is made twice for the same `user_id`.
related: #2455
...

## Screenshots
![selection_006](https://user-images.githubusercontent.com/3838857/30359008-2cf324b0-9848-11e7-8fac-1b0ff3d99dfd.png)

**Comment by lafriks** [comment]
@schast can you provide steps to reproduce that? I can not seem to get such cases

**Comment by schast** [comment]
the duplicate entries only appear if the default git hook (post-receive) is set.

```
#!/usr/bin/env bash
"/opt/gitea/current/gitea" hook --config='/opt/gitea/current/custom/conf/app.ini' post-receive
```

**Comment by lafriks** [comment]
Can you do  rewrite hooks in admin panel to see if that helps

**Comment by schast** [comment]
No, rewriting hooks doesn't help.
it only helps if you remove the complete hook and leave it empty (disabled).

**Comment by lafriks** [comment]
how do you remove it? from gitea UI (in repository settings)?

**Comment by schast** [comment]
yes, under git-hooks in gitea ui repository settings.

**Comment by lafriks** [comment]
There should be only custom hooks you need not gitea hook. Just delete it and you should be fine
