### ISSUE TITLE
git client cluttered since update of container

### ISSUE THREAD

**Issue by yogo1212** [go-gitea/gitea#24951]
### Description

After a recent update, all ssh interactions with the server produces loads of lines like these:

```
$ git push origin :qwer
2023/05/26 21:54:52 start process 64712aac: LoggerManager (system)
remote: 2023/05/26 21:54:52 start process 64712aac: LoggerManager (system)
remote: 2023/05/26 21:54:53 start process 64712aad: LoggerManager (system)
remote: 2023/05/26 21:54:53 start process 64712aad: LoggerManager (system)
```

### Gitea Version

1.20.0+dev-923-gabccb86b3

### How are you running Gitea?

Podman image `nightly-rootless` (`29f8336a623e`)

### Database

PostgreSQL

**Comment by wxiaoguang** [comment]
Related to #24924 , will do more clean up

**Comment by wxiaoguang** [comment]
->  Do not output "Trace" level logs from process manager by default #24952

**Comment by yogo1212** [comment]
Thanks  for your work! :blush:

**Comment by wxiaoguang** [comment]
#24952 has been merged and the nightly build has been released. Please try the latest nightly. Sorry for the inconvenience

**Comment by yogo1212** [comment]
@wxiaoguang no inconvenience!
granted, my using nightly isn't entirely voluntary but finding bugs early is what nightly is about.
thanks for your work on gitea :heart:
