### ISSUE TITLE
GITEA CRASHES ON PULL REQUEST

### ISSUE THREAD

**Issue by Sabdix** [go-gitea/gitea#24950]
### Description

When creating a pull request, the service crashes and goes down.
Every time it does that.
I check the log and I found this:

2023/05/26 09:08:13 ...it/repo_attribute.go:306:func2() [E] [6470cb5c-2] Unable to open checker for a03997ba89f967c72e8f3981d9c8a9a529d0608a. Error: failed to run attr-check. Error: exit status 1
	Stderr: 
2023/05/26 09:08:41 ...les/cache/context.go:62:GetContextData() [W] [6470cb76-3] cannot get cache context when getting data: &{context.Background.WithCancel.WithCancel.WithValue(type pprof.labelContextKey, val {"graceful-lifecycle":"with-hammer"}).WithCancel.WithValue(type pprof.labelContextKey, val {"graceful-lifecycle":"with-hammer", "pid":"6470cb76-3", "ppid":"", "process-description":"NewPullRequest: CMV_Becarios/NivelesServicioFront:2", "process-type":"normal"}) 6470cb76-3}
2023/05/26 09:08:41 ...les/cache/context.go:71:SetContextData() [W] [6470cb76-3] cannot get cache context when setting data: &{context.Background.WithCancel.WithCancel.WithValue(type pprof.labelContextKey, val {"graceful-lifecycle":"with-hammer"}).WithCancel.WithValue(type pprof.labelContextKey, val {"graceful-lifecycle":"with-hammer", "pid":"6470cb76-3", "ppid":"", "process-description":"NewPullRequest: CMV_Becarios/NivelesServicioFront:2", "process-type":"normal"}) 6470cb76-3}
2023/05/26 09:08:41 ...les/cache/context.go:62:GetContextData() [W] [6470cb76-3] cannot get cache context when getting data: &{context.Background.WithCancel.WithCancel.WithValue(type pprof.labelContextKey, val {"graceful-lifecycle":"with-hammer"}).WithCancel.WithValue(type pprof.labelContextKey, val {"graceful-lifecycle":"with-hammer", "pid":"6470cb76-3", "ppid":"", "process-description":"NewPullRequest: CMV_Becarios/NivelesServicioFront:2", "process-type":"normal"}) 6470cb76-3}
2023/05/26 09:08:41 ...les/cache/context.go:71:SetContextData() [W] [6470cb76-3] cannot get cache context when setting data: &{context.Background.WithCancel.WithCancel.WithValue(type pprof.labelContextKey, val {"graceful-lifecycle":"with-hammer"}).WithCancel.WithValue(type pprof.labelContextKey, val {"graceful-lifecycle":"with-hammer", "pid":"6470cb76-3", "ppid":"", "process-description":"NewPullRequest: CMV_Becarios/NivelesServicioFront:2", "process-type":"normal"}) 6470cb76-3}
2023/05/26 09:08:41 ...les/cache/context.go:62:GetContextData() [W] [6470cb76-3] cannot get cache context when getting data: &{context.Background.WithCancel.WithCancel.WithValue(type pprof.labelContextKey, val {"graceful-lifecycle":"with-hammer"}).WithCancel.WithValue(type pprof.labelContextKey, val {"graceful-lifecycle":"with-hammer", "pid":"6470cb76-3", "ppid":"", "process-description":"NewPullRequest: CMV_Becarios/NivelesServicioFront:2", "process-type":"normal"}) 6470cb76-3}
2023/05/26 09:08:41 ...les/cache/context.go:71:SetContextData() [W] [6470cb76-3] cannot get cache context when setting data: &{context.Background.WithCancel.WithCancel.WithValue(type pprof.labelContextKey, val {"graceful-lifecycle":"with-hammer"}).WithCancel.WithValue(type pprof.labelContextKey, val {"graceful-lifecycle":"with-hammer", "pid":"6470cb76-3", "ppid":"", "process-description":"NewPullRequest: CMV_Becarios/NivelesServicioFront:2", "process-type":"normal"}) 6470cb76-3}
2023/05/26 09:08:41 ...les/cache/context.go:62:GetContextData() [W] [6470cb76-3] cannot get cache context when getting data: &{context.Background.WithCancel.WithCancel.WithValue(type pprof.labelContextKey, val {"graceful-lifecycle":"with-hammer"}).WithCancel.WithValue(type pprof.labelContextKey, val {"graceful-lifecycle":"with-hammer", "pid":"6470cb76-3", "ppid":"", "process-description":"NewPullRequest: CMV_Becarios/NivelesServicioFront:2", "process-type":"normal"}) 6470cb76-3}
2023/05/26 09:08:41 ...les/cache/context.go:71:SetContextData() [W] [6470cb76-3] cannot get cache context when setting data: &{context.Background.WithCancel.WithCancel.WithValue(type pprof.labelContextKey, val {"graceful-lifecycle":"with-hammer"}).WithCancel.WithValue(type pprof.labelContextKey, val {"graceful-lifecycle":"with-hammer", "pid":"6470cb76-3", "ppid":"", "process-description":"NewPullRequest: CMV_Becarios/NivelesServicioFront:2", "process-type":"normal"}) 6470cb76-3}
2023/05/26 09:08:41 ...les/cache/context.go:62:GetContextData() [W] [6470cb76-3] cannot get cache context when getting data: &{context.Background.WithCancel.WithCancel.WithValue(type pprof.labelContextKey, val {"graceful-lifecycle":"with-hammer"}).WithCancel.WithValue(type pprof.labelContextKey, val {"graceful-lifecycle":"with-hammer", "pid":"6470cb76-3", "ppid":"", "process-description":"NewPullRequest: CMV_Becarios/NivelesServicioFront:2", "process-type":"normal"}) 6470cb76-3}
2023/05/26 09:08:41 ...les/cache/context.go:71:SetContextData() [W] [6470cb76-3] cannot get cache context when setting data: &{context.Background.WithCancel.WithCancel.WithValue(type pprof.labelContextKey, val {"graceful-lifecycle":"with-hammer"}).WithCancel.WithValue(type pprof.labelContextKey, val {"graceful-lifecycle":"with-hammer", "pid":"6470cb76-3", "ppid":"", "process-description":"NewPullRequest: CMV_Becarios/NivelesServicioFront:2", "process-type":"normal"}) 6470cb76-3}
2023/05/26 09:08:41 ...les/cache/context.go:62:GetContextData() [W] [6470cb76-3] cannot get cache context when getting data: &{context.Background.WithCancel.WithCancel.WithValue(type pprof.labelContextKey, val {"graceful-lifecycle":"with-hammer"}).WithCancel.WithValue(type pprof.labelContextKey, val {"graceful-lifecycle":"with-hammer", "pid":"6470cb76-3", "ppid":"", "process-description":"NewPullRequest: CMV_Becarios/NivelesServicioFront:2", "process-type":"normal"}) 6470cb76-3}
2023/05/26 09:08:41 ...les/cache/context.go:71:SetContextData() [W] [6470cb76-3] cannot get cache context when setting data: &{context.Background.WithCancel.WithCancel.WithValue(type pprof.labelContextKey, val {"graceful-lifecycle":"with-hammer"}).WithCancel.WithValue(type pprof.labelContextKey, val {"graceful-lifecycle":"with-hammer", "pid":"6470cb76-3", "ppid":"", "process-description":"NewPullRequest: CMV_Becarios/NivelesServicioFront:2", "process-type":"normal"}) 6470cb76-3}
2023/05/26 09:08:41 ...les/cache/context.go:62:GetContextData() [W] [6470cb76-3] cannot get cache context when getting data: &{context.Background.WithCancel.WithCancel.WithValue(type pprof.labelContextKey, val {"graceful-lifecycle":"with-hammer"}).WithCancel.WithValue(type pprof.labelContextKey, val {"graceful-lifecycle":"with-hammer", "pid":"6470cb76-3", "ppid":"", "process-description":"NewPullRequest: CMV_Becarios/NivelesServicioFront:2", "process-type":"normal"}) 6470cb76-3}
2023/05/26 09:08:41 ...les/cache/context.go:71:SetContextData() [W] [6470cb76-3] cannot get cache context when setting data: &{context.Background.WithCancel.WithCancel.WithValue(type pprof.labelContextKey, val {"graceful-lifecycle":"with-hammer"}).WithCancel.WithValue(type pprof.labelContextKey, val {"graceful-lifecycle":"with-hammer", "pid":"6470cb76-3", "ppid":"", "process-description":"NewPullRequest: CMV_Becarios/NivelesServicioFront:2", "process-type":"normal"}) 6470cb76-3}

### Gitea Version

Gitea 1.19.3

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://cmv365-my.sharepoint.com/:u:/g/personal/sabdi_pantoja_cajamorelia_mx/EW6Pts0eEFxNnl5oI2M3MuoBl95YkhvSDkyEVJ5k0TmCGw?e=eddert

### Git Version

git version 2.37.1.windows.1

### Operating System

WINDOWS

### How are you running Gitea?

Gitea is running on a Windows Server 2016 with the Windows Services Manager.

We have been working great with the tool, and  every update I installed it following the next steps:
1. Dump of the Mysql Database for backup
2. Making a Backup of the gitea folder wich contains all the configuration, repositories, files, etc.
3. Downlaoding the latest version of gitea.
4. Executing manually the exe file on the same location of the older version. This is done so that the .exe file updates the database and the files needed for the new version. (This is explain on your documentation)
5. Then when executing ok, i make a change on the windows service configuration, so it can use the new .exe

### Database

Mysql

**Comment by wxiaoguang** [comment]
Thank you for your report with logs.

Gitea's logger system doesn't record "panic" logs, so if you experienced other errors, the log file might not contain related information.


Could you try to stop the service, and run Gitea manually from CMD / PowerShell terminal? Then if any panic occurs, you can see detailed logs.

**Comment by Sabdix** [comment]
Hi Again. I did what you said and this is what appears

panic: unaligned 64-bit atomic operation

goroutine 2745 [running]:
runtime/internal/atomic.panicUnaligned()
        /usr/local/go/src/runtime/internal/atomic/unaligned.go:8 +0x2d
runtime/internal/atomic.Xadd64(0x17af64bc, 0x1)
        /usr/local/go/src/runtime/internal/atomic/atomic_386.s:125 +0x11
github.com/blevesearch/zapx/v15.(*chunkedContentCoder).incrementBytesWritten(...)
        /go/pkg/mod/github.com/blevesearch/zapx/v15@v15.3.8/contentcoder.go:114
github.com/blevesearch/zapx/v15.(*chunkedContentCoder).flushContents(0x17af6480)
        /go/pkg/mod/github.com/blevesearch/zapx/v15@v15.3.8/contentcoder.go:143 +0x2fe
github.com/blevesearch/zapx/v15.(*chunkedContentCoder).Close(...)
        /go/pkg/mod/github.com/blevesearch/zapx/v15@v15.3.8/contentcoder.go:110
github.com/blevesearch/zapx/v15.(*interim).writeDicts(0x180554a0)
        /go/pkg/mod/github.com/blevesearch/zapx/v15@v15.3.8/new.go:803 +0x150f
github.com/blevesearch/zapx/v15.(*interim).convert(0x180554a0)
        /go/pkg/mod/github.com/blevesearch/zapx/v15@v15.3.8/new.go:277 +0x2ff
github.com/blevesearch/zapx/v15.(*ZapPlugin).newWithChunkMode(0x5af9cd4, {0x17adef70, 0x1, 0x1}, 0x402)
        /go/pkg/mod/github.com/blevesearch/zapx/v15@v15.3.8/new.go:72 +0x18b
github.com/blevesearch/zapx/v15.(*ZapPlugin).New(0x5af9cd4, {0x17adef70, 0x1, 0x1})
        /go/pkg/mod/github.com/blevesearch/zapx/v15@v15.3.8/new.go:47 +0x43
github.com/blevesearch/bleve/v2/index/scorch.(*Scorch).Batch(0x14e09000, 0x17c22450)
        /go/pkg/mod/github.com/blevesearch/bleve/v2@v2.3.6/index/scorch/scorch.go:412 +0x5fe
github.com/blevesearch/bleve/v2.(*indexImpl).Batch(0x15a68460, 0x17ab9ba0)
        /go/pkg/mod/github.com/blevesearch/bleve/v2@v2.3.6/index_impl.go:310 +0xa0
code.gitea.io/gitea/modules/indexer/bleve.(*FlushingBatch).Flush(0x17c67da4)
        /source/modules/indexer/bleve/batch.go:52 +0x32
code.gitea.io/gitea/modules/indexer/issues.(*BleveIndexer).Index(0x14aaa3b0, {0x17adeeb8, 0x1, 0x1})
        /source/modules/indexer/issues/bleve.go:226 +0x183
code.gitea.io/gitea/modules/indexer/issues.InitIssueIndexer.func1({0x17239040, 0x1, 0x14})
        /source/modules/indexer/issues/indexer.go:146 +0x597
code.gitea.io/gitea/modules/queue.NewByteFIFOQueue.func1({0x17239040, 0x1, 0x14})
        /source/modules/queue/queue_bytefifo.go:70 +0x3e
code.gitea.io/gitea/modules/queue.(*WorkerPool).doWork(0x13d4be60, {0x43e3f80, 0x1782cf00})
        /source/modules/queue/workerpool.go:605 +0x725
code.gitea.io/gitea/modules/queue.(*WorkerPool).addWorkers.func1()
        /source/modules/queue/workerpool.go:311 +0x5d
created by code.gitea.io/gitea/modules/queue.(*WorkerPool).addWorkers
        /source/modules/queue/workerpool.go:309 +0x25

**Comment by wxiaoguang** [comment]
That's a known bug. Could you try 1.20 nightly, or download a 64bit release if your Windows is 64bit?

**Comment by Sabdix** [comment]
Yes, is 64 Bit

**Comment by Sabdix** [comment]
Wich one is the 64 bit release version?
https://dl.gitea.com/gitea/1.19.3/

**Comment by Sabdix** [comment]
Done Thanks!!! it got fixed!
