### ISSUE TITLE
When there are '@' or '?' character in the Redis password, gitea cannot connect to Redis.

### ISSUE THREAD

**Issue by hiifong** [go-gitea/gitea#24967]
### Gitea Version

v1.20+

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

./gitea web

### Database

None

**Comment by techknowlogick** [comment]
Are you able to url escape these special characters?

**Comment by hiifong** [comment]
> Are you able to url escape these special characters?

I escaped these characters in the url and still can't connect to Redis.

**Comment by wxiaoguang** [comment]
Show your case, others do not have time to guess what you are doing .......

**Comment by hiifong** [comment]
> Show your case, others do not have time to guess what you are doing .......

![image](https://github.com/go-gitea/gitea/assets/89133723/f53dccf3-2edf-48cd-a3e2-48d6366ec0be)

**Comment by wxiaoguang** [comment]
I do not think it is "escaping". Google how to escape a URL

**Comment by hiifong** [comment]
Thank you for your answer

**Comment by wxiaoguang** [comment]
https://superuser.com/questions/273799/how-to-use-special-characters-in-username-password-for-http-proxy

https://stackoverflow.com/questions/22544219/how-do-i-use-special-characters-password-on-the-url-when-dealing-with-http-aut

**Comment by hiifong** [comment]
I copied from here
![image](https://github.com/go-gitea/gitea/assets/89133723/5dc3fc6f-03e5-4e1a-a479-be1afcabdfba)
,thank you
