### ISSUE TITLE
Feature request: support ntfy as a webhook type

### ISSUE THREAD

**Issue by ksurl** [go-gitea/gitea#24978]
### Feature Description

see [ntfy](docs.ntfy.sh), a push notification server (can be selfhosted). it would be great to have as a self hosted option for a webhook endpoint.

**Comment by Kafumio** [comment]
hi @lunny, I am interested in this issue and would like to try implementing this feature. Can you assign it to me?

**Comment by wxiaoguang** [comment]
It's blocked by "custom webhook" related issues/PRs:

* #19307
* #14693
* #1089
