### ISSUE TITLE
Migration: Fails to mirror repositories with no master branch

### ISSUE THREAD

**Issue by thomasthep** [go-gitea/gitea#2500]
- Gitea version (or commit ref): 1.2.0-rc2
- Git version: 2.11.3
- Operating system: Alpine 3.6
- Docker Image: gitea/gitea:1.2.0-rc2 (57e5be805ca4e2981e636abbd5f074607256ca16ce8852bfa692a880c7d5d574)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

Gitea does not allow migrating/mirroring repos with an empty master branch or no master branch.

Ideally the repo to be cloned should always be cloned as is. The default branch set for the repo must also be mirrored and be used by Gitea.

I tried cloning bcoin-org's lcoin repo from GitHub without success. https://github.com/bcoin-org/lcoin.git

## Screenshots

![screen shot 2017-09-13 at 20 30 59](https://user-images.githubusercontent.com/10499371/30394198-ab1fafaa-98c2-11e7-8c8c-c892f5f1ac28.png)

**Comment by cez81** [comment]
This no longer seems to be an issue on master. I mirrored the repo in OP successfully to https://try.gitea.io/cez81/lcoin

Only 1 branch, litecoin. No master branch.

**Comment by lunny** [comment]
Let's close this at first.

**Comment by telsch** [comment]
I try this local with v1.6.0-rc2 and also on https://try.gitea.io/repo/

![image](https://user-images.githubusercontent.com/45108518/48646190-6e7a6680-e9e8-11e8-8b78-38275958896b.png)

**Comment by telsch** [comment]
Seemed to be fixed at least in Gitea Version: 1.10.0+dev-188-g2d0b90c96

**Comment by lunny** [comment]
Please feel free to reopen it.
