### ISSUE TITLE
Bad UI rendering in commit detail

### ISSUE THREAD

**Issue by Morlinest** [go-gitea/gitea#2502]
- Gitea version (or commit ref): 633de01
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL) https://try.gitea.io/morli/public/commit/92ab217c67da62fca9caab096b05346a09ed2f02
- Browser: Chrome

## Screenshots
![image](https://user-images.githubusercontent.com/12720041/30400000-d2feec44-98d5-11e7-9fd8-eb583e7d33cb.png)

![image](https://user-images.githubusercontent.com/12720041/30399986-cb6a7444-98d5-11e7-9808-e4e5680e04c6.png)

**Comment by Morlinest** [comment]
Caused by #2477.

**Comment by lunny** [comment]
closed by #2503
