### ISSUE TITLE
Skip expression

### ISSUE THREAD

**Issue by kcodeHub15** [go-gitea/gitea#25031]
### Feature Description

Now we need to use a function called skip expressions in our process, which was updated in April this year. Yesterday, we re integrated a new process engine, but it still does not have that function

### Screenshots

[https://github.com/Asuxxjava/img/blob/master/lx0d819c2c21ecba73c156c735985b970.png](url)

**Comment by techknowlogick** [comment]
Hi, That screenshot does not look like Gitea. Could you provide more details?
