### ISSUE TITLE
OAuth should not require secret for public clients

### ISSUE THREAD

**Issue by hickford** [go-gitea/gitea#25047]
According to OAuth spec https://datatracker.ietf.org/doc/html/rfc8252#section-8.5

> it is NOT RECOMMENDED for authorization servers to require client authentication of public native apps clients using a shared secret

but Gitea requires client secret in both authorization code flow and refresh flow regardless of client type

https://github.com/go-gitea/gitea/blob/7a5873335afb00dda5fa123fb023c88278e79deb/routers/web/auth/oauth.go#L756

https://github.com/go-gitea/gitea/blob/7a5873335afb00dda5fa123fb023c88278e79deb/routers/web/auth/oauth.go#L698

Fix would be to validate secret if and only if app.ConfidentialClient

**Comment by denyskon** [comment]
See https://github.com/go-gitea/gitea/pull/25033
