### ISSUE TITLE
Docker container updates destroy git repos

### ISSUE THREAD

**Issue by mkrecek234** [go-gitea/gitea#25045]
### Description

I am using the official docker container for Gitea where I have configured an external data directory.

Whenever I update a Gitea container to the latest versions, it renders the Gits useless with this message:

„ Die Git-Daten, die diesem Repository zugrunde liegen, können nicht gelesen werden. Kontaktiere den Administrator deiner Instanz oder lösche dieses Repository.“

(Git data of the repo cannot be read)

### Gitea Version

Latest

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

Docker

### Database

SQLite

**Comment by lunny** [comment]
We need more information, I don't think there are any logic which will delete them.

**Comment by mkrecek234** [comment]
So the setup is as follows:
- I pull the official gitea docker repo
- I configure it as follows:
![image](https://github.com/go-gitea/gitea/assets/28671486/16f98a17-9c06-4717-a3e5-ad77110a3b68)
- So /data/gitea is stored outside the docker container.
- I now and then update the gitea docker pulling "latest" - it then always destroys the repos. So the git repo still is there, but you can no longer access it. This was the case for more than 2 years now, so I had to rebuild the git repos after every upgrade.

Let me know what else you need to investigate the issue, happy to help.

**Comment by wolfogre** [comment]
You should mount `/data`, not only `/data/gitea`. Gitea stores data into `/data/gitea`, `/data/git` and `/data/ssh`.

See https://docs.gitea.com/next/installation/install-with-docker

**Comment by mkrecek234** [comment]
@wolfogre Thanks a lot, not sure where I had found the wrong instruction. Will mount it and close the issue.
