### ISSUE TITLE
[Proposal] Add toggleable menu to settings navbars

### ISSUE THREAD

**Issue by HesterG** [go-gitea/gitea#25051]
### Feature Description

Fomantic does not have it, we could add a js feature to implement this. 

<img width="412" alt="Screen Shot 2023-06-02 at 17 06 00" src="https://github.com/go-gitea/gitea/assets/17645053/7572ef57-4c23-4e03-b547-c03fb331de2c">

<img width="375" alt="Screen Shot 2023-06-02 at 17 06 05" src="https://github.com/go-gitea/gitea/assets/17645053/270758f8-94e7-4575-b484-39d265ecb601">

**Comment by silverwind** [comment]
You don't need JS for this, just use `<details>` and `<summary>`.
