### ISSUE TITLE
Allow for multiple redirect URIs in OAuth application UI

### ISSUE THREAD

**Issue by denyskon** [go-gitea/gitea#25068]
### Feature Description

It is already possible to create an OAuth application with multiple redirect URIs over the API. It would be great if it also would be possible to do this through the UI.
I propose a comma-separated list, like ```https://uri1.org/admin/,https://cms.uri2.com,https://uri3.net/cms/```

**Comment by wxiaoguang** [comment]
* #19627

**Comment by denyskon** [comment]
> * #19627

I think you're mixing up things. The linked approach talks about unpredictable wildcard uris, but I mean a predictable set of URIs which is already partially supported. As far as I understand the code, we already save the URIs as a string list, and over API I'm already able to set multiple URIs.
Personally I would need it because I want my CMS to be accessible over different URLs and do not want to register multiple OAuth apps for it.

The way to support it would be just treating the input value of the field as a comma-separated list and splitting it afterwards.

**Comment by wxiaoguang** [comment]
You are right, RFC says "The authorization server MUST require public clients and SHOULD require confidential clients to register their redirection URIs.", so predictable pre-registered URLs are safe.
