### ISSUE TITLE
Deleting maven packages

### ISSUE THREAD

**Issue by lambdagg** [go-gitea/gitea#25064]
### Description

Just as the documentation suggests (https://docs.gitea.com/packages/usage/packages/maven), there is no way of programmatically deleting a Maven package. I do not think this is intended ; we can do it on GitHub and in development stages we could need to delete and recreate a package (because we cannot overwrite it - it will just add the files to the previous package) multiple times because changing the version on each commit when the project is not done yet is not ideal.
As every (almost?) any other package manager (https://docs.gitea.com/packages/usage/packages/npm#unpublish-a-package, https://docs.gitea.com/packages/usage/packages/generic...), could we get a way of deleting artifacts? At least an API endpoint?

### Gitea Version

1.19.3

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

Pre-built, docker

### Database

SQLite

**Comment by KN4CK3R** [comment]
How can you delete the Maven packages from Github? I think there is no build-in delete command in Maven.

You can programmatically delete a package via the Gitea api: https://try.gitea.io/api/swagger#/package/deletePackage

**Comment by lambdagg** [comment]
There is indeed no built-in delete command in Maven. However, the GitHub APIs permits the deleting of packages.
I've figured it out with the API (i forgot the versioning when requesting...).
Thank you for troubleshooting!
