### ISSUE TITLE
new branch button content isn't show if not focus on it

### ISSUE THREAD

**Issue by a1012112796** [go-gitea/gitea#25079]
### Description

as title, example:

![tmp](https://github.com/go-gitea/gitea/assets/25342410/aa736397-574d-4a2b-a15b-4a5b5d28b4bc)

looks related to https://github.com/go-gitea/gitea/pull/23421

/cc @wxiaoguang 

### Gitea Version

1.20.0+dev-766-g6c8b680f9

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

./gitea web

### Database

None

**Comment by wxiaoguang** [comment]
Nope, it's actually caused by : Improve RSS (#24335)

The `.menu .item a {` is too loose
