### ISSUE TITLE
no checkmark when fork repo

### ISSUE THREAD

**Issue by saegl5** [go-gitea/gitea#25076]
### Description

When I fork a repository and click on the checkbox for "Make Repository Private," no checkmark is displayed.
To see this, you may visit https://try.gitea.io/koofio/123123 and click on Fork.

### Screenshots

| new repo | new repo fork |
| - | - |
| ![new_repo](https://github.com/go-gitea/gitea/assets/63764270/50dd291b-4a2c-4798-94f9-20d89cd776d6) | ![new_fork](https://github.com/go-gitea/gitea/assets/63764270/bd7de67f-b859-46e0-a41e-76ea89cf722c)<br>hard to see, but I am clicking on the checkbox |

### Gitea Version

1.19.3

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

macOS 13.4 (22F66)

### Browser Version

Safari Version 16.5 (18615.2.9.11.4)

**Comment by wxiaoguang** [comment]
The UI is misleading. 

The real meaning of it is: the checkbox is read-only, you can not change it, you can not change the visiblity of a forked repo.

**Comment by saegl5** [comment]
Once one's fork is created, yes.

If you click private, your fork remains private. Otherwise, your fork remains public.

**Comment by saegl5** [comment]
@wxiaoguang thank you for your response

I also ran some more tests... \
if a repo *or* forked repo even is public, fork remains public (in fact, the box stays unchecked) \
if a repo *or* forked repo even is private, fork remains private (in fact, the box stays checked) \
so, yes, you are correct to a point 👍 

that point being: you cannot change the visibility of a ~~forked repo~~ *repo from which we fork* \
"forked repository" is past tense; the repo from which we fork may or may not be forked; and our fork is not created yet

I guess if the checkbox were removed and if "The visibility of a forked repository cannot be changed" were reworded, then users would have more clarity \

is there any legitimate reason for keeping the checkbox, if it can't be checked or unchecked? \
also, why describe the visibility of newly created fork, if we are really describing that of repo from which we fork?

**Comment by wxiaoguang** [comment]
IMO no particular reason for keeping the checkbox, the code was written as so from beginning, and nobody ever changed it (that's open source)

**Comment by techknowlogick** [comment]
Forks retain the visibility as otherwise the "create a PR" logic gets significantly complex. For example if you create a PR and make the repo private, then how can the original author see the code? This is just one of the many conditions that would need to be considered. GitHub behaves the same for the same reasons.

**Comment by saegl5** [comment]
@wxiaoguang and @techknowlogick I see, thanks \
gitea is a masterpiece to me, and I wouldn't want to cause a headache, but mind if I *take a stab at it* and create a pr to change the checkbox?

**Comment by wxiaoguang** [comment]
Feel free to do so. Thank you.

**Comment by saegl5** [comment]
Progress...

- [x] Built Gitea from source following the [build instructions](https://github.com/go-gitea/gitea#building)
- [ ] Modify the source code
- [ ] Submit PR
