### ISSUE TITLE
[UX] make more visible warning for setting repo to private

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#25085]
## Now

![image](https://user-images.githubusercontent.com/1810977/172717307-aeaf1e21-25dd-46eb-8ba9-510ee3bea53d.png)

_Originally posted by @42wim in https://github.com/go-gitea/gitea/issues/19904#issuecomment-1150417113_

**Comment by 6543** [comment]
I propose to move this checkbox to the dangeroups part and convert it into a button.
there we can also describe ireversible processes that will happen if clicked

**Comment by alystair** [comment]
Dupe of my request #23826
