### ISSUE TITLE
 Implement Debouncing for Approve Button Clicks in Gitea Pull Requests

### ISSUE THREAD

**Issue by liriansu-opus** [go-gitea/gitea#25096]
### Description

I have discovered that Gitea lacks debouncing functionality for the approve button, which can result in repeated approvals if users click quickly before the website responds. Additionally, this can lead to multiple webhook calls being triggered.

To solve this issue, I suggest implementing a debounce mechanism in Gitea. Debouncing would effectively merge and handle multiple rapid approve actions performed by a user during a single interaction.

Here is a screenshot illustrating the problem:

![image](https://github.com/go-gitea/gitea/assets/3286092/ab85fc3f-4a96-438d-a487-c5b84fbc5b35)

I kindly request the Gitea development team to consider adding this feature to enhance the user experience and prevent unintended repeated approvals.

Thank you for your attention to this matter, and I appreciate your efforts in continually improving Gitea.

### Gitea Version

1.19.3

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

Self-hosted in docker container

### Database

None

**Comment by HesterG** [comment]
I think to improve this, we should first change the form submit to submit by `fetch`, and then do debounce or add flag like `loading`, and if the flag is there, do not `post` until the `post` is done.

**Comment by wxiaoguang** [comment]
Many related issues like https://github.com/go-gitea/gitea/issues/20402

AJAX is the answer to the problem.

**Comment by LKI** [comment]
Thanks! @lunny
