### ISSUE TITLE
Broken layout for changed files tree on PR

### ISSUE THREAD

**Issue by sgabenov** [go-gitea/gitea#25095]
### Description

Broken layout for changed files tree on PR.
The tree of changed files is shown partly
<img width="820" alt="layout" src="https://github.com/go-gitea/gitea/assets/15741789/ded6fc80-9e69-4edb-a805-f1812f5287ec">

### Gitea Version

1.19.0

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

linux

### How are you running Gitea?

docker

### Database

PostgreSQL

**Comment by delvh** [comment]
Should be fixed already in newer 1.19.x versions.
Please update.
It is certainly fixed on `main`.
