### ISSUE TITLE
bug: default port conflict with existing software

### ISSUE THREAD

**Issue by mckaygerhard** [go-gitea/gitea#2509]
- Gitea version (or commit ref): any
- Git version: 1.8.4
- Operating system: Linux
- Database (use `[x]`):
  - [x] PostgreSQL
  - [x] MySQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

Gitea was after gogs, so the default port must be changed, gogs already setup already times ago in port 3000, 

so it's time gitea have their own port. not only a rename of any "gogs" word in the sources
.

**Comment by lafriks** [comment]
It can be changed and I don't think anyone would run Gogs and Gitea on same server

**Comment by mckaygerhard** [comment]
i run both in same server! also for packgin purposes its necesary and to take care of standars!

**Comment by lafriks** [comment]
Changing default port would break existing installations and for such rare cases as yours you can change port to other in your config file

**Comment by mckaygerhard** [comment]
but this way its no standar, i not see that newer software try to overlaping ports of another in "same" category

**Comment by lcges** [comment]
Run nginx and apache this "same" server... 
That's why you set your preferences in the configuration file.

**Comment by lunny** [comment]
Run both Gogs and Gitea on same machine is strange.

**Comment by bkcsoft** [comment]
Gogs (and subsequently Gitea) just uses the same port that most other services use (gitlab, node-express, python-flask, etc) so this is a non-issue, change the port for one of the services either by editing the config or by running `./gitea web --port 3001`

**Comment by mckaygerhard** [comment]
now i know why distributions package fisrt the gogs event gitea

Lenz McKAY Gerardo (PICCORO)
http://qgqlochekone.blogspot.com

2017-10-21 12:55 GMT-04:00 bkcsoft <notifications@github.com>:
