### ISSUE TITLE
git mirror: context deadline exceeded

### ISSUE THREAD

**Issue by muradm** [go-gitea/gitea#25092]
### Description

I'm trying to mirror [linux](https://github.com/torvalds/linux). 

I already found the timeout configuration problem reports. But with last attempt, I set `MIGRATE`, `MONITOR`, `CLONE`, `PULL` and `GC` to `10800`. Normally, on that specific host, `git gc` on `linux` repository takes about 2 hours, that is why I set it to 3 hours according to above.

However, the time difference between start and finish below, is always about 40-50 minutes, regardless of the `git.timeout` values.

First of all, for me really it is not very clear from documentation and numerous issue report which exact value is responsible for this case.

Then according to the observed behavior, I suppose that, this timeout should be somewhere else.

**Start**:
```
Jun  5 19:31:51 core002 gitea[14526]: ...eb/routing/logger.go:102:func1() [I] router: completed POST /repo/migrate for a.b.c.d:0, 303 See Other in 565.4ms @ repo/migrate.go:151(repo.MigratePost)
```
**Finish**:
```
Jun  5 20:17:59 core002 gitea[14526]: ...ices/task/migrate.go:60:func1() [E] runMigrateTask[7] by DoerID[1] to RepoID[48] for OwnerID[9] failed: unable to write commit-graph for '/var/lib/gitea/git/repositories/mirror/linux.git' : context deadline exceeded
Jun  5 20:17:59 core002 gitea[14526]: ...ervices/task/task.go:51:handler() [E] Run task failed: unable to write commit-graph for '/var/lib/gitea/git/repositories/mirror/linux.git' : context deadline exceeded
```

(Note: Didn't reproduce at `try.gitea.io` because inapplicable I suppose)

### Gitea Version

1.20.0+dev-997-gd302a5ee6

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![2023-06-06T00:00:10,722397130+03:00](https://github.com/go-gitea/gitea/assets/2050575/4ce22330-5dcf-46d7-8eb1-48ce4bda7a0d)

### How are you running Gitea?

Using out of the box Docker image.

### Database

MySQL

**Comment by wxiaoguang** [comment]
The "write commit-graph" doesn't respect the "migration timeout", but it uses default "git timeout"

Have you set `DEFAULT` in `[git.timeout]`?

**Comment by muradm** [comment]
No :) It was not very clear from docs, what is impact of it. I assumed that it is like fallback or else. So yeah, setting it `DEFAULT` in `[git.timeout]` resolved issue.

Moreover, it looks like initial mirroring happened faster, when `DEFAULT` is set. Weird

```
Jun  6 04:25:30 core001 gitea[16259]: ...eb/routing/logger.go:102:func1() [I] router: completed POST /repo/migrate for a.b.c.d:0, 303 See Other in 2903.7ms @ repo/migrate.go:151(repo.MigratePost)

Jun  6 05:06:06 core001 gitea[16259]: ...eb/routing/logger.go:102:func1() [I] router: completed GET /mirror/linux for a.b.c.d:0, 200 OK in 3298.2ms @ repo/view.go:710(repo.Home)
```
