### ISSUE TITLE
feat: build as cgi/fpm application so can httpd handle better

### ISSUE THREAD

**Issue by mckaygerhard** [go-gitea/gitea#2510]
- Gitea version (or commit ref):any
- Git version: 1.8.3
- Operating system: Linux
- Database (use `[x]`):
  - [x] PostgreSQL
  - [x] MySQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

Gitea today builds as a httpd web itself, 

would be great full if can also be act as cgi/fpm application so can httpd handle better
...

**Comment by lafriks** [comment]
Gitea already supports that. You can set `PROTOCOL = fcgi` in `[server]` section to do that

**Comment by lafriks** [comment]
I'm closing this issue, please reopen if there is anything missing

**Comment by mckaygerhard** [comment]
thanks for the info, the docs said that permission are on unix socket to 666 ? why so insecure permisive  and why i cannot see the path for that socket?

**Comment by mckaygerhard** [comment]
just for info, now i can see more info for the path of socket but there's no info about permissions neither where will be search the files if all are from the binary path! i continue that issue (due i cannot reopen) here: #5466
