### ISSUE TITLE
UpdatePublicKey: Multiple Assignment to "update_unix"

### ISSUE THREAD

**Issue by programmeroftheeve** [go-gitea/gitea#2511]
- Gitea version (or commit ref): 005900b
- Git version: builtin
- Operating system: docker
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

```
bash % git push test master
Gitea: Internal error
UpdatePublicKey: Failed to update public key: pq: multiple assignments to same column "updated_unix"
error: failed to push some refs to 'ssh://git@localhost:2222/tbradt/buildbot_travis.git'
```
## Description

Pushing with SSH with a postgres backend is causing an error. The code pushes just fine to the repo. I did a search to figure out which commit broke things, and it was 005900b.

**Comment by lafriks** [comment]
@lunny  can you please look at this?

**Comment by lunny** [comment]
@lafriks maybe we still need your help with the `vendor/vendor.json`
