### ISSUE TITLE
Fork using only a single branch or tag

### ISSUE THREAD

**Issue by sad75** [go-gitea/gitea#25117]
### Feature Description

Fork is an important operation in some development processes. It will be much more convenient if the resulting repository will contain only the useful references and not all the ones from the original repository.

As it is possible with [github ]( https://github.blog/changelog/2022-07-27-you-can-now-fork-a-repo-and-copy-only-the-default-branch/), it could be achieved by selecting a branch or **a tag** for the clone operation.

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/6814287/b2552a47-aef2-4cea-8a05-c7cb0dbb449d)

**Comment by sh7dm** [comment]
Implemented support to fork arbitrary branch, since some projects are developed not on the default branch

**Comment by sh7dm** [comment]
Extra idea: maybe we should support the same option for migrations? It's maybe even more useful in such case when people migrate (essentially fork a repo to their instance) for development purpose
