### ISSUE TITLE
After the name of the new kanban in the projects, press Enter will not create the kanban

### ISSUE THREAD

**Issue by tyroneyeh** [go-gitea/gitea#25116]
### Description

In a projects click new column button to input name, after press Enter key then new column is not created

### Gitea Version

1.20.0+dev-1003-g58536093b

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

command-line

### Database

None

**Comment by puni9869** [comment]
![Jun-10-2023 18-43-04](https://github.com/go-gitea/gitea/assets/80308335/4796c9be-d161-43a0-a3e3-d9cd6a19cda4)

**Comment by puni9869** [comment]
This is working for me 
Steps to reproduce

After the name of the new kanban in the projects, press Enter will not create the kanban.

Can any one confirm the same..


The pr listed is this issue fixes something else.

Sorry for the confusion.
