### ISSUE TITLE
Don't allow bot users to be assigned to issue/pull 

### ISSUE THREAD

**Issue by stuzer05** [go-gitea/gitea#25115]
### Feature Description

Bot users are hidden in gitea, so why would we see them in issues "assignees" filter and be able to assign issues to them?

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/23124682/e069bc50-57c8-47b6-a832-2e739655cbe0)

**Comment by silverwind** [comment]
I see nothing wrong with assigning a bot an issue, if for example the bot is a merger bot, this may be desirable to get the bot to merge it.

**Comment by delvh** [comment]
Furthermore, as @silverwind mentioned, there might be bots that explicitly listen for issues they are assigned for.
That is an absolutely permitted usecase.
So, this would even be breaking.

**Comment by stuzer05** [comment]
> > Bot users are hidden in gitea, so ...
> 
> wonder what's the meaning of `Bot users` ? ...

https://github.com/go-gitea/gitea/pull/24026

**Comment by stuzer05** [comment]
> Furthermore, as @silverwind mentioned, there might be bots that explicitly listen for issues they are assigned for. That is an absolutely permitted usecase. So, this would even be breaking.

I thought that'll be done using labels

**Comment by lunny** [comment]
Assign action could ask the bot user do something, why not?

**Comment by stuzer05** [comment]
> Assign action could ask the bot user do something, why not?

I thought assignee means human to resolve an issue (code something, etc.)

**Comment by delvh** [comment]
Yes, too.
But that's the funny thing about software:
You can only guide the user on how to use it, you cannot forbid unforeseen uses.
