### ISSUE TITLE
Add "copy branch name" (icon) on dropdown branch selector

### ISSUE THREAD

**Issue by sgabenov** [go-gitea/gitea#25120]
### Feature Description

I want to have ability to easy copy branch name with dropdown menu. Now i can only do this from URL link after selecting the necessary branch

I expect to add this copy button as on the attached mock.
Also, add a context menu "copy branch name" when you click on ... button (button not yet available/implemented)

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/15741789/ef4a927c-6bef-47ec-857a-a5d32c156ecd)

**Comment by sgabenov** [comment]
As well add it here
![image](https://github.com/go-gitea/gitea/assets/15741789/6b2eeb2f-b3d1-448e-b5a9-96989873d3cf)

**Comment by silverwind** [comment]
Yes, seems useful to have.

**Comment by lunny** [comment]
I don't think dropdown is a good place to do that but branches and tags should be better places.

**Comment by sgabenov** [comment]
> I don't think dropdown is a good place to do that but branches and tags should be better places.

This is the way it is done in Bitbucket and i can say it is much easier to do, then go into "brunch" menu

**Comment by puni9869** [comment]
I can take it forward. Assign me.

**Comment by puni9869** [comment]
There are some observation in different platforms like Github, Gitlab, Bitbucket  and bunch of more platform. 
I have observed they all have copy option for branch name. They don't have copy option for tags.

As a UX prespective for tags we don't need copy option. 

By above observation I am suggsting the following UI changes, I know they might not align with UX point of way.But they are simplest to make quick.

Here is my suggestions:
<img width="896" alt="image" src="https://github.com/go-gitea/gitea/assets/80308335/32e17c2e-3022-41dd-bf5b-4b39bc6a0a70">

When Hover on Copy
<img width="457" alt="image" src="https://github.com/go-gitea/gitea/assets/80308335/290b969d-11b7-455e-854b-92ecfd76f851">

When Clicked on Copy
<img width="897" alt="image" src="https://github.com/go-gitea/gitea/assets/80308335/296fd4d8-af7d-4891-9e89-af136c3a9c08">


Code changes in files:- 

```html
<button class="btn interact-bg gt-p-3" data-clipboard-text="{{.Name}}" data-tooltip-content="{{$.locale.Tr "repo.branch.copy_branch_name"}}">{{svg "octicon-copy"}}</button>
```
Translations:- 
en-US.ini
```ini
[repo]
branch.copy_branch_name = Copy Branch Name
```


@silverwind @lunny  @delvh 
I am open for any UI/UX suggestion which work the best.

**Comment by silverwind** [comment]
@puni9869 seems good there as we should have enough space, but please test with long branch names to be sure. Otherwise, I'm happy to accept a PR for that.

**Comment by puni9869** [comment]
Are you referring this use case.
This is the long text branch name. We are not showing branch name in Tippy popup.
![image](https://github.com/go-gitea/gitea/assets/80308335/0ab4eaab-c823-4a32-87ea-cbf9313d9e73)

**Comment by silverwind** [comment]
yes, looks good. There is plenty of space for more buttons with such ellipsis, so we can add it.

**Comment by puni9869** [comment]
I got it , that you are saying.
![Screenshot 2023-06-29 at 12 16 14 AM](https://github.com/go-gitea/gitea/assets/80308335/f3cdf655-863c-45f3-83d8-664c151efa8e)

Here you want to add the copy button, Near the branch name/

But, There is a problem with UI, We need to modify this tag with every screen set. That will be a tricky effort. I am not worry about the effort. But that will be unnecessary to do for such small thing.

![image](https://github.com/go-gitea/gitea/assets/80308335/f47d93f5-395a-428a-9a42-7eb3f7fbee9c)

**Comment by silverwind** [comment]
No, I did not mean that. Just go with your original suggestion. I was just worrying that the extra button may cause issues with the table layout, but it doesn't.

**Comment by puni9869** [comment]
Cool, Pr is coming ASAP. Thanks a ton for immediate support.
