### ISSUE TITLE
Dissmiss a review on a pull request and input the reason but the reason missed on the conversation.

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#25127]
<img width="1003" alt="图片" src="https://github.com/go-gitea/gitea/assets/81045/59b416a4-8220-41d0-896e-d148538fd02d">

**Comment by silverwind** [comment]
May be related to https://github.com/go-gitea/gitea/pull/24526, I'm not sure.

**Comment by silverwind** [comment]
At least the rendering has not changed, so it might be a problem when the dismissal request is sent.

https://github.com/go-gitea/gitea/blame/main/templates/repo/issue/view_content/comments.tmpl#L76

**Comment by silverwind** [comment]
The input form is pretty much pure copy-paste, so I think it's unlikely that that PR regressed it and this may be a older bug.

**Comment by wxiaoguang** [comment]
It seems the bug exists from the beginning of the "dismiss" feature.

-> Make "dismiss" content shown correctly #25461
