### ISSUE TITLE
Gitea doesn't send branch name to Drone via Webhook after merging Pull Request

### ISSUE THREAD

**Issue by mxmehl** [go-gitea/gitea#2513]
- Gitea version (or commit ref): 5f4210a
- Git version: 2.1.4
- Operating system: Debian 8
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant

## Description

I have Drone connected to Gitea for CIs. It works all fine except when I merge Pull Requests: Drone does build PRs but doesn't deploy them.

Example: [This](https://git.fsfe.org/pmpc/website/pulls/107) is a PR I worked with. With [this](https://git.fsfe.org/pmpc/website/commit/e0ae45ae1c341723f5764ecc25479a1b63913e00) commit I merged the PR with master. And [this](https://drone.fsfe.org/pmpc/website/1274) is the drone build which is just testing the PR before it has been accepted – it actually never deployed. The Drone file should be correct: [.drone.yml](https://git.fsfe.org/pmpc/website/src/master/.drone.yml)

A comment on [my SO question](https://stackoverflow.com/questions/46165230/build-doesnt-trigger-on-merged-pull-request) suggests that the Webhook Gitea sends lacks a branch name – it should be master to trigger the drone build. This is also visible in the [API output](https://drone.fsfe.org/api/repos/pmpc/website/builds/1274).

Can it be that Gitea has a bug here?

## Screenshot

My Gitea webhook setiing: https://i.imgur.com/sh8bwEv.jpg

**Comment by lunny** [comment]
What's your Drone version and is this still a problem?

**Comment by mxmehl** [comment]
Yes, it's still an issue.

Drone version is 0.8.2. I just tested it with [this PR](https://git.fsfe.org/pmpc/website/pulls/207). The following [Drone build](https://drone.fsfe.org/pmpc/website/3681) made syntax check etc (before the merge) but didn't deploy the updated master after the merge.

[.drone.yml](https://git.fsfe.org/pmpc/website/src/branch/master/.drone.yml) hasn't been changed and should catch updates to master.

**Comment by mjwwit** [comment]
I think I may have fixed this in drone/drone#2320

**Comment by mxmehl** [comment]
Short update: The PR in drone has been merged but I cannot test it yet because Drone hasn't had a release yet and we only use stable versions in our organisation

**Comment by lafriks** [comment]
Closing this issue as fixed in drone. If issue persists even after drone upgrade to latest (with that fix) version please reopen
