### ISSUE TITLE
[DOCKER] Installing with ":latest" tag will install a RC

### ISSUE THREAD

**Issue by realizelol** [go-gitea/gitea#25136]
### Description

I'm using `gitea/gitea:latest` which should install the latest stable version, as mentioned in the docs [Install-With-Docker](https://docs.gitea.com/next/installation/install-with-docker):

_For a stable release you can use **:latest**, **:1** or specify a certain release like **:main-nightly**, but if you'd like to use the latest development version of Gitea then you could use the **:dev** tag._

On Github it's marked as "pre-release": https://github.com/go-gitea/gitea/releases

Running it with **:1** tag will use the correct stable `1.19.3` but cannot really go back to it in case my database is updated.

### Gitea Version

1.20.0-rc0

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

git version 2.39.2

### Operating System

Docker

### How are you running Gitea?

Docker with "gitea/gitea:latest" tag.

### Database

MySQL

**Comment by wfjake** [comment]
Seems like #21615 wasn't truly fixed

**Comment by lunny** [comment]
There is a regression imo.

**Comment by delvh** [comment]
I know, I wasn't fast enough with cancelling the release pipeline for the `v1.21.0-dev` tag.
That's why a Docker image was pushed.

**Comment by lunny** [comment]
Since v1.20.1 is released, this has been corrected.
