### ISSUE TITLE
There is a problem with the navbar ui style

### ISSUE THREAD

**Issue by hiifong** [go-gitea/gitea#25145]
### Description

![image](https://github.com/go-gitea/gitea/assets/89133723/a16df9aa-07ff-40f9-89cf-c1bbe2078de7)

### Gitea Version

1.20.0+rc0-6-g679b1f7949 built with GNU Make 4.2.1, go1.20.2 : bindata

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

./gitea web

### Database

MySQL

**Comment by silverwind** [comment]
Can you reproduce on https://try.gitea.io/? If not, this may be because of a outdated customization template.

**Comment by hiifong** [comment]
> Can you reproduce on https://try.gitea.io/? If not, this may be because of a outdated customization template.

thank you
