### ISSUE TITLE
Mirror update interval corrupted - changed 8H -> 318538h39m30.304065536s

### ISSUE THREAD

**Issue by issmirnov** [go-gitea/gitea#2515]
- Gitea version (or commit ref): 1.2.0+rc2
- Git version: 2.7.4
- Operating system: Ubuntu 16.04 LTS
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
## Description

After upgrading to the latest gitea, none of my mirrors are working. 

Checking my`app.ini`, things look okay:

```
[cron]
ENABLED      = true
RUN_AT_START = true

; Update mirrors
[cron.update_mirrors]
SCHEDULE = @every 10m
``` 

But, when I open a repo, I see:

```
Mirror interval (valid time units are "h", "m", "s") = 318538h39m30.304065536s
```

I did not change this. It used to be 8h intervals. I think the latest version somehow corrupted this value.

## Screenshots

1. Mirror: http://cloud.ivansmirnov.name/2O3N2u0s3y2t

**Comment by cez81** [comment]
Do you remember what version you upgraded from?

**Comment by issmirnov** [comment]
Yes, [v1.1.4](https://github.com/go-gitea/gitea/releases/tag/v1.1.4)

Upgraded by downloading new binary, replacing the old one, and restarting tye systemd service.

**Comment by cez81** [comment]
I've tried reproducing this bug using 1.1.4 and upgrading to 1.2.1 without success. Migration code hasn't changed between 1.2.0-rc2 and 1.2.1. If you still happen to have the log from the upgrade that would be interesting to see.
The migration was broken at one point but that was fixed back in April.

**Comment by issmirnov** [comment]
This has come back. I upgraded from 1.2.1 to 1.2.2. Mirror interval set to 318538h39m30.304065536s again.

**Comment by lafriks** [comment]
There was no migrations at all between 1.2.1 and 1.2.2

**Comment by issmirnov** [comment]
Odd. I'll close for now, will reopen if the same repos get corrupted sync times again.
