### ISSUE TITLE
Mirror Synchronization status display

### ISSUE THREAD

**Issue by yaoyingkeji** [go-gitea/gitea#25168]
### Feature Description

Synchronization status display

### Screenshots

![截图_选择区域_20230609112620](https://github.com/go-gitea/gitea/assets/93997433/1dc3e9a3-41e3-4346-8cbc-5924ff76c6a2)
![截图_选择区域_20230609162654](https://github.com/go-gitea/gitea/assets/93997433/bba7d2eb-faa5-4a1f-9ed0-60db7047daa3)

**Comment by sh7dm** [comment]
Currently working on this
