### ISSUE TITLE
Protected branchs doesn't work 

### ISSUE THREAD

**Issue by LanaYuan** [go-gitea/gitea#2517]
- Gitea version (or commit ref): 1.2.0+rc1-4-g0c910af 
- Git version:  2.14.1
- Operating system: amd64
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant

## Description

I have tried protected branch, but it still push successfully.
When I tried via 1.1.3 again, it works fine.

**Comment by lafriks** [comment]
Fixed by #2556 and will be in 1.2.0-rc3
