### ISSUE TITLE
Rebase and Fast-forward for Pull-Request is not working properly

### ISSUE THREAD

**Issue by jim-kirisame** [go-gitea/gitea#25177]
### Description

Hi, I'm notice the "Rebase and Fast forward" mode for Pull Requst is not work properly in 1.20.0-rc0. It will modify the last commit of the PR and rewrite the message of commit to "Merge pull request 'xxx' ([#1](xxx)) from BRANCH into main" 

I have reproduce the bug in try.gitea.io. This is the link:
- [branch after merge with rebase mode](https://try.gitea.io/jim1399/test-pr-repo/commits/branch/main)
- [branch to be merge](https://try.gitea.io/jim1399/test-pr-repo/commits/branch/jim1399-patch-1)

The HEAD of PR branch is [30a8edb4](https://try.gitea.io/jim1399/test-pr-repo/commit/30a8edb4539e9d9b0f3d6436f62d37656a1330d9) but in main branch is [29420402](https://try.gitea.io/jim1399/test-pr-repo/commit/29420402d2a0bd8b83161c26426b22ebde3f878e), which is not correct in Rebase and Fast-forward mode.

### Gitea Version

1.20.0-rc0, or 1.20.0+rc0-17-g81211db07

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

https://try.gitea.io/

### Database

None

**Comment by eremenko789** [comment]
Still relevant for 1.20.0-rc2

**Comment by mmithril** [comment]
Possible workaround: use _Squash commit_ & edit the message manually.

Please fix as soon as possible anyway.

**Comment by wxiaoguang** [comment]
-> Avoid amending the Rebase and Fast-forward merge if there is no message template #25779
