### ISSUE TITLE
Pull request webhook didn't fired when push to an exist pull request branch

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#2518]
As title.

**Comment by daviian** [comment]
@lunny I am on it

**Comment by daviian** [comment]
@lunny Guess this should be done after your PR https://github.com/go-gitea/gitea/pull/2548 is merged?

**Comment by lunny** [comment]
@daviian No. #2548 will not fix this

**Comment by daviian** [comment]
@lunny Ok, will have a look at it before finishing #2548

**Comment by daviian** [comment]
@lunny Can't reproduce that on master. Do you?

**Comment by ethantkoenig** [comment]
I also cannot reproduce. @lunny, can/should we close this issue?

**Comment by lunny** [comment]
OK. Let's close this one.
