### ISSUE TITLE
Troubles with SQLiteDB

### ISSUE THREAD

**Issue by xavetar** [go-gitea/gitea#25183]
.

**Comment by xavetar** [comment]
Everything works great with Postgres. (At least I haven't noticed any problems yet.)

**Comment by lunny** [comment]
I cannot understand well about the bug. Could you reproduce it on https://try.gitea.io which is running based on sqlite?

**Comment by xavetar** [comment]
> I cannot understand well about the bug. Could you reproduce it on https://try.gitea.io which is running based on sqlite?

Without direct access to the file system, no.

Steps to repeat:
1. Project size >10GB
2. Don't finish uploading the project via: "git push" (it will eat up disk space even if it's not completely pushed - I think this is also a bug)
3. Go to directory: "ata/git/repositories/$REPO.git/"
4. Run command: "git prune"
5. Delete project via gitea interface (may have problems with infinite waiting)
6. Reload the container.
7. The project will disappear, but this junk data will remain in the SQLite database.

Trying to create a project with the same name will fail. Trying to manually delete through other tools for working with databases will not work (there will be no records in the database). I managed to detect this garbage only through a HEX editor.

**Comment by lunny** [comment]
> > I cannot understand well about the bug. Could you reproduce it on https://try.gitea.io which is running based on sqlite?
> 
> Without direct access to the file system, no.
> 
> Steps to repeat:
> 
>     1. Project size >10GB
> 
>     2. Don't finish uploading the project via: "git push" (it will eat up disk space even if it's not completely pushed - I think this is also a bug)
> 
>     3. Go to directory: "ata/git/repositories/$REPO.git/"
> 
>     4. Run command: "git prune"
> 
>     5. Delete project via gitea interface (may have problems with infinite waiting)
> 
>     6. Reload the container.
> 
>     7. The project will disappear, but this junk data will remain in the SQLite database.
> 
> 
> Trying to create a project with the same name will fail. Trying to manually delete through other tools for working with databases will not work (there will be no records in the database). I managed to detect this garbage only through a HEX editor.

I don't think it's a normal behaviour to manually operate gitea's repositories directly

**Comment by xavetar** [comment]
> I don't think it's a normal behaviour to manually operate gitea's repositories directly

I don't think this is normal behavior - leftover data in the database and not clearing the repository if the download is interrupted. So you can push a couple of times and there will be no disk space left. How you think?

In the first case, a bug in working with the database, which can lead to data loss or overwriting of some important information (the way out is not to use SQLite).

The second bug is implicitly present even with a different database and is not related to it in any way, what this may lead to is unknown, it may even damage the local archive of repository.
