### ISSUE TITLE
Preconfigure Git Credential Manager as instance-wide OAuth application

### ISSUE THREAD

**Issue by shyim** [go-gitea/gitea#25189]
### Feature Description

It would be really nice if there would be a instance-wide OAuth application only for the purpose of using it with the [Git Credential Manager](https://github.com/git-ecosystem/git-credential-manager) or [git-credential-oauth](https://github.com/hickford/git-credential-oauth). This would allow Git authentication *just work* without passwords, personal access tokens or SSH keys.

The OAuth client details for both helpers are redirect URI http://127.0.0.1/, only the client-id needs to be same between all instances.

There is also a similar request to Gitlab: https://gitlab.com/gitlab-org/gitlab/-/issues/374172

**Comment by denyskon** [comment]
@hickford You seem to be the author of git-credential-oauth. If we tried to integrate it into Gitea, would a pre-registered OAuth application be enough for it to work? Would we need to implement something else?

**Comment by hickford** [comment]
@denyskon Two changes are necessary:

1. In a migration ([pseudocode](https://gitlab.com/gitlab-org/gitlab/-/issues/413809#note_1451710379)), insert  OAuth2Application records for git-credential-oauth and Git Credential Manager 
2. Change the 401 Unauthorized http header from `Www-Authenticate: Basic realm="."` to `Www-Authenticate: Basic realm="Gitea"` so that git-credential-oauth can identify Gitea instances and select the OAuth configuration

**Comment by hickford** [comment]
@shyim @denyskon I sketched an implementation in #25653 but it has a problem: the OAuth2Application isn't created on first time install. If you have any ideas how to fix, please have a go.

**Comment by denyskon** [comment]
Thanks, I'll take a look tomorrow.

**Comment by hickford** [comment]
An alternative approach would be to hard code the application in without database records.

**Comment by hickford** [comment]
@shyim @denyskon https://github.com/go-gitea/gitea/pull/25653 working, ready for review

**Comment by hickford** [comment]
Security wise, it would be prudent to fix  https://github.com/go-gitea/gitea/issues/25061 and #25813 , because these would protect the OAuth client from client impersonation, and limit its scope.

**Comment by lunny** [comment]
This has been resolved by #26291

**Comment by hickford** [comment]
Released https://github.com/hickford/git-credential-oauth/releases/tag/v0.10.0 with universal Gitea support 

Tested with https://try.gitea.io/

Requires Gitea 1.21 or greater and Git 2.41 or greater.

**Comment by denyskon** [comment]
@hickford Thanks for that quick implementation! Is anything needed from Gitea's side to also make it happen for Git Credential Manager?

**Comment by hickford** [comment]
> Is anything needed from Gitea's side to also make it happen for [Git Credential Manager](https://github.com/git-ecosystem/git-credential-manager)?

@denyskon I don't think so. The implementation would be similar to https://github.com/hickford/git-credential-oauth/commit/79a00fb737159a6bbb245d0a42f94ce0c78d0957
