### ISSUE TITLE
latest tag being bind to the wrong Docker image

### ISSUE THREAD

**Issue by WarningImHack3r** [go-gitea/gitea#25193]
### Description

The `latest` tag of your [Docker image](https://hub.docker.com/r/gitea/gitea/tags) is often bind to the wrong Gitea version. I often notice that it's bind to some RC version, dev version, or currently to the `1.21.0-dev` version, which is definitely not good.

I notice it because I'm running Watchtower daily to always keep my containers up-to-date, and right now my Gitea container has been bumped to this dev version and is no longer working because of an undocumented breaking change.

I can also think about the people attempting to casually download and run Gitea for the first time with a simple `gitea/gitea` and won't understand why it's not working.

So can you please make sure the `:latest` tag **always** points to the latest **stable** version please?

### Gitea Version

1.21.0

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![latest](https://github.com/go-gitea/gitea/assets/43064022/58f4b385-f50c-41ea-948b-df6a0b8a6f4a)
---
![1 21 0](https://github.com/go-gitea/gitea/assets/43064022/83525154-bdda-41e8-8d9f-636d81d46716)

### Operating System

Raspberry Pi OS 64bit

### How are you running Gitea?

:latest Docker image

### Database

SQLite

**Comment by lakoliu** [comment]
I came hear wondering if anyone else's Gitea wasn't working. This must be the reason. My container seems to be continuously trying to restart right now.

**Comment by WarningImHack3r** [comment]
@lakoliu it's even more a pain that we not only have to manually downgrade but we also have to tweak/disable Watchtower temporarily because it's will bump Gitea again during its next run...

**Comment by delvh** [comment]
Yes, we know.
We've noticed this bug immediately when releasing 1.20.0-rc0 as the new container was pushed almost immediately from our CI.
However, we couldn't downgrade anymore without causing breakages.

**Comment by WarningImHack3r** [comment]
@delvh I see. I assume it could only be fixed releasing a new version (1.19.x/1.20) ? Or is it even worse: not being able to fix it until a stable 1.21.0 version?

Have you planned some changes to not make it happen again? It's not the first time `:latest` is bind to an non-stable version

**Comment by wxiaoguang** [comment]
> I came hear wondering if anyone else's Gitea wasn't working. This must be the reason. My container seems to be continuously trying to restart right now.

Are you using 1.20? 1.20 has some breaking changes, could you share your logs?

**Comment by delvh** [comment]
> I assume it could only be fixed releasing a new version (1.19.x/1.20)

No, as your db will be upgraded with new versions.
You mean a stable 1.20 version, `1.21.0-dev` simply means here stopped the development on 1.20 and started the development on 1.21.

**Comment by WarningImHack3r** [comment]
@delvh so if I get it correctly it won't be fixed until 1.20.0 stable is released?

**Comment by delvh** [comment]
Yep

**Comment by WarningImHack3r** [comment]
> Have you planned some changes to not make it happen again? It's not the first time `:latest` is bind to an non-stable version

Ok, and about that @delvh?

**Comment by delvh** [comment]
Well… We'll try to harden our CI not to set the `latest` tag anymore on `-dev` tags, but that is a trial and error process:
The only way to know it works is by releasing something, so we can only hope it won't occur next time again.

**Comment by WarningImHack3r** [comment]
Don't forget `-nightly`, `-rc*` and others! 😄 Thanks for your quick response
