### ISSUE TITLE
timetracking popover disappears on hover

### ISSUE THREAD

**Issue by denyskon** [go-gitea/gitea#25198]
### Description

[Bildschirmaufzeichnung vom 2023-06-11, 21-27-52.webm](https://github.com/go-gitea/gitea/assets/47871822/1d1da86f-3d63-4275-9a69-955095ee611e)

When opening the timetracking popover from navbar and trying to click the stop/delete button, the whole popover disappears when hovering.

### Gitea Version

1.20.0+rc0

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

Docker (Root)

### Database

None

**Comment by wxiaoguang** [comment]
It should have been fixed by #25134

* https://github.com/go-gitea/gitea/pull/25134#issuecomment-1582585081 (the change 5)
