### ISSUE TITLE
Add download links to commits_list

### ISSUE THREAD

**Issue by wolfpackmars2** [go-gitea/gitea#25216]
### Feature Description

This is a small change which adds links to download any commit from the commits list.  The change makes the "message" column slightly smaller and adds text "[.zip]|[.tar.gz]" in the sha1 column, with "[.zip]" being a link to download the .zip copy of the repo commit on the related row, and "[.tar.gz]" being the same in .tar.gz format.

An example can be seen live here:

[https://git.groesz.org/Groesz.org/bits/commits/branch/master](https://git.groesz.org/Groesz.org/bits/commits/branch/master).

I've found this to be very convenient when needing to download a specific commit of a repo with fewer clicks.

### Screenshots

![Screenshot from 2023-06-12 18-40-50](https://github.com/go-gitea/gitea/assets/1011130/73b85c41-f028-4afb-8d86-f269146bd410)

**Comment by delvh** [comment]
Hmm… I'm not sure if cluttering up the UI is a good idea here.
How often do you actually need to download a repo at a specific commit, and can't use `git clone` instead?
I've never needed it so far, and I use git(ea) for quite some time now.
So, to me, this seems a bit like an unnecessary feature that takes away space from the list that is already scarce (especially on smaller screens such as mobile).
The action is already possible with a few clicks more on a page that is more fitting for it…

**Comment by wolfpackmars2** [comment]
I work from multiple locations and from multiple client PCs where I don't always have access to git locally. In my case, a project I was working on for another engineering team required me to send links to a .zip copy of the repository where the client didn't want to hassle with git. When developing in my own controlled environment, it's not such a big deal.

Also, I had cloned the Nvidia Jetson kernel repo to make changes. The repo was huge, but I wanted to share my changes without requiring a download of the entire repo on the client side.

This adds convenience links which, in my opinion, are unobtrusive. The links themselves are kept small for this reason. One or the other link can also be removed.

To me it's a small change that adds convenience without affecting the layout too terribly much.

**Comment by wolfpackmars2** [comment]
An alternative which is less intrusive is to add a single line

`<a href="{{AppSubUrl}}/{{$.Username}}/{{$.Reponame}}/archive/{{.ID}}.zip" rel="nofollow" class="default-link">{{svg "octicon-file-zip" 16 "gt-mr-3"}}</a>`

which adds an icon with the link to the .zip download for the commit and doesn't modify the column spacing.

![Screenshot from 2023-06-12 19-24-51](https://github.com/go-gitea/gitea/assets/1011130/7caf5139-dc20-4f08-9b2d-50a8c04b6686)

**Comment by wolfogre** [comment]
I understand your requirement, but it is indeed not a common one. Since Gitea is customizable, maybe you can use a custom template for your instance? See [Customizing Gitea pages and resources](https://docs.gitea.com/next/administration/customizing-gitea#customizing-gitea-pages-and-resources).
