### ISSUE TITLE
Notification count color changed from red to blue

### ISSUE THREAD

**Issue by neszt** [go-gitea/gitea#25215]
### Description

It's probably a ridiculous little thing, but it's very disturbing that instead of the easily noticeable red color, the number of notifications in the upper right corner has become an almost barely noticeable blue color. 

![image](https://github.com/go-gitea/gitea/assets/5006287/9cfd6815-e241-4cdc-97b3-1a736c59c579)

### Gitea Version

1.19.3

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

Docker compose.

### Database

SQLite

**Comment by wolfogre** [comment]
Related to https://github.com/go-gitea/gitea/pull/22169#issuecomment-1361421902

**Comment by lunny** [comment]
Github also is using blue color.

**Comment by neszt** [comment]
> Github also is using blue color.

And Facebook uses red.

Notifications may contain important information. Specifically, in my work, almost every notification is important and necessary for me to notice immediately.

I have a problem not only with the color, but also with the fact that it is difficult to notice.

Maybe it should be made configurable? I do not know.

I do not agree with the argument that the color red indicates an error or covers a dangerous operation. Of course, the error should be marked as red, as well as dangerous operations, but I think everyone knows that clicking the notification icon does not destroy the system.

**Comment by silverwind** [comment]
It's not blue, it's primary color, which depending on theme will be different. I don't see us realistically change this color or style. We have been working on getting the UI into a consistent state where under regular operation, only primary colors are rendered.

I think if you must change this, change it via a custom template or user style.

**Comment by neszt** [comment]
The chrome browser has an extension: stylebot, with which I was able to restore the original color and size very easily, in 1 minute.
