### ISSUE TITLE
Navbar width horizontal overflow in 1.20rc

### ISSUE THREAD

**Issue by noahziheng** [go-gitea/gitea#25221]
### Description

Hi all,

I find Gitea UI showing horizontal scrollbar when the content is more than screen like screen shot case. Look like the navbar has overflow its container.

It can be found in try.gitea.io at: [https://try.gitea.io/explore/repos](https://try.gitea.io/explore/repos)

Actually I never found this issue under 1.20-rc.

Maybe the problem is similar with [this post](https://stackoverflow.com/questions/23367345/100vw-causing-horizontal-overflow-but-only-if-more-than-one), and we can add `max-width: 100%` or `overflow-x: hidden` to solve it.

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/2758317/70340bd9-5f8c-4625-aa12-ee4120bc757e)

![image](https://github.com/go-gitea/gitea/assets/2758317/59042c9f-230b-4ca3-990a-5c17719af216)

![image](https://github.com/go-gitea/gitea/assets/2758317/91c8e3e2-bc68-4e9b-bcb5-df2984ded957)

### Gitea Version

1.20.0+rc0-17-g3e9fc3672

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

MacOS Ventura & Windows 11

### Browser Version

Microsoft Edge 114.0.1823.37

**Comment by wxiaoguang** [comment]
It's not related to navbar.

IMO actually is a regression of #21850 

You can see I have remove the "navbar" and "footer", only "page-content" there:


![image](https://github.com/go-gitea/gitea/assets/2114189/fc708980-624d-4e38-ba7d-af501597d128)

**Comment by noahziheng** [comment]
@wxiaoguang Actually the scrollbar will invisble if I remove navbar element

![image](https://github.com/go-gitea/gitea/assets/2758317/4238a0d7-3f6b-4529-a220-f09dfbbfbc13)

**Comment by wxiaoguang** [comment]
> Actually the scrollbar will invisble if I remove navbar element

But it is there in my screenshot, have you tried different pages and different sizes? In some cases "removing navbar element" makes the scrollbar invisible, but in some cases the UI is still not right. That's why I do not think the navbar is the root problem, while there is something wrong behind it.

**Comment by wxiaoguang** [comment]
Can you try this one?  Revert overflow: overlay (revert `#21850`) #25231

**Comment by noahziheng** [comment]
> Can you try this one? Revert overflow: overlay (revert `#21850`) #25231

Looks effective! This revert may cover more case in the UI.

**Comment by noahziheng** [comment]
@wxiaoguang But this revert will just hide horizontal scrollbar(because it's not overlay yet). 
The navbar(and/or other element we have not find) 's width always exceed its container.

![image](https://github.com/go-gitea/gitea/assets/2758317/9f4cc348-daa0-4225-bdaa-d6dc3af973fc)
