### ISSUE TITLE
ed25519 SSH-Keys not working

### ISSUE THREAD

**Issue by xoxys** [go-gitea/gitea#2522]
- Gitea version (or commit ref): 1.1.3
- Git version: not relevant
- Operating system: CentOS 6.8
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
I can't add ed25519 SSH-Keys. Error is:
```
SSHKeyGenParsePublicKey: fail to parse public key: exec(4:SSHKeyGenParsePublicKey) failed: exit status 1 stdout: /tmp/gitea_keytest143073527 is not a public key file. stderr: line 1 too long
```

**Comment by xoxys** [comment]
Not a bug? There is an option in [app.ini](https://github.com/go-gitea/gitea/blob/release/v1.1/conf/app.ini) to set ssh.minimum_key_sizes also for ED25519. If ED25519 is not supported it's a confusing option in app.ini

**Comment by lafriks** [comment]
Hard to say, it has some support for it in code but have to check if this is bug or not fully supported

**Comment by silverwind** [comment]
Pretty sure this is because OpenSSH on CentOS 6 is too old to support ED25519 keys.

**Comment by lunny** [comment]
So this is not a gitea's problem.
