### ISSUE TITLE
Add filter\search bar for branches

### ISSUE THREAD

**Issue by sgabenov** [go-gitea/gitea#25233]
### Feature Description

I want to have additional search\filter bar on the "brances" page. So when you enter text, the filter will only show branches that contains such text in branch name.

the problem: i have 100+ branches in my repo. I did a PR long time ago and want to delete this PR and corresponding branch for it. If i go to PR page, i can see a linked branch for this PR and have a button to delete current PR. But on the branch page, that is opened from PR, i do not have a "delete" button, so i have to go to the "branches" page whare i can find and delete the corresponding branch after PR is deleted. But i need to click on multiple pages of existing branches to find the branch i want to delete. Feels like a lot of manual work to do.

### Screenshots

<img width="852" alt="search bar" src="https://github.com/go-gitea/gitea/assets/15741789/39d1b39f-6516-4be5-9d7e-70e61fc14cf0">

**Comment by silverwind** [comment]
Agree, we need a search box there.

**Comment by lunny** [comment]
I think this depends on #22743

**Comment by ruess** [comment]
Just realized there at least is a branch search by going to the general <>Code tab and then clicking the branch change dropdown. This will at least get me by until this feature is added, as I also have way to many branches right now :)

<img width="437" alt="Screenshot 2023-09-01 at 12 05 30 PM" src="https://github.com/go-gitea/gitea/assets/797367/1ac2dc0b-295d-4df7-8e6d-33ebb457d3a0">
