### ISSUE TITLE
Translation problem in PL, string placeholder missing

### ISSUE THREAD

**Issue by fnetX** [go-gitea/gitea#25238]
### Description

The polish translation results in broken template text.

Strings like 
~~~
activate_account.text_1=Cześć <b>%[1]s</b>, dziękujemy za rejestrację na %[2]!
~~~

are broken and result in emails like this user reported: https://mastodon.social/@djvdq/110538301215880465

`%[2]` needs to become `%[2]s`.

I'd fix this in the translation source, but it's another proprietary platform I do not want to use.

I propose to add some sort of QA to spot such mistakes. I'm only familiar with Weblate so far, and I think they detect if placeholders in the source string are not present in the translated version, but I'm not sure if it works for every format.

### Gitea Version

1.19

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

Not relevant

### Database

None

**Comment by delvh** [comment]
Have just fixed that string, is there any other string with broken placeholders?

**Comment by lunny** [comment]
I have fixed it on crowdin https://crowdin.com/translate/gitea/68/enus-pl?filter=basic&value=0#q=activate_account.text_1
