### ISSUE TITLE
Cannot login with github on try.gitea

### ISSUE THREAD

**Issue by stuzer05** [go-gitea/gitea#25248]
### Description

500 error after redirect on login

### Gitea Version

trunk

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/23124682/624f0032-f381-402d-9b6a-57100e1096f4)

### How are you running Gitea?

https://try.gitea.io

### Database

None

**Comment by lunny** [comment]
Fixed now.
