### ISSUE TITLE
AiScript language support

### ISSUE THREAD

**Issue by ThatOneCalculator** [go-gitea/gitea#25268]
### Feature Description

Support for the [AiScript](https://github.com/syuilo/aiscript/) programming/scripting language would be great for repositories like [this](https://codeberg.org/box464/calckey-plugins). It can use the same syntax highlighter as Javascript, as seen [here](https://github.com/syuilo/aiscript/blob/8ab9c279009fe8453c9a65cf3bb7b359d081bb56/playground/src/App.vue#LL123C40-L123C50).

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/44733677/e0b1abb5-3efc-4f19-82f3-22420cca6433)

![image](https://github.com/go-gitea/gitea/assets/44733677/96bb7b94-649a-47e8-b764-387271334fd2)

**Comment by silverwind** [comment]
For the syntax, you can contribute it likely as an alias to JavaScript here:

https://github.com/alecthomas/chroma

For language stats, it needs to be contributed here:

https://github.com/go-enry/go-enry

**Comment by ThatOneCalculator** [comment]
Thank you! I'll close this as invalid as it's out-of-scope for Gitea.
