### ISSUE TITLE
Some problem about commit status

### ISSUE THREAD

**Issue by yp05327** [go-gitea/gitea#25279]
### Description

- Some times it will be outside of the window
![image](https://github.com/go-gitea/gitea/assets/18380374/79aa21cd-7051-4c6c-ab06-69ce84436256)
- Do we need to show all of them?
![image](https://github.com/go-gitea/gitea/assets/18380374/b53b0eb6-45c4-450a-b99c-dc39e5c54176)

You can also check this in:
https://gitea.com/yp05327/testrepo

### Gitea Version

latest

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

build

### Database

None

**Comment by wxiaoguang** [comment]
Please approve this one 

https://github.com/go-gitea/gitea/pull/25254

**Comment by wxiaoguang** [comment]
> Some times it will be outside of the window

Maybe it can be fine tuned by the Popper options: https://atomiks.github.io/tippyjs/v6/all-props/#popperoptions

**Comment by yp05327** [comment]
Just a question, is it possible to use dropdown menu instead of tippy, if we want to make a GitHub like ui for this?

**Comment by yp05327** [comment]
I think this issue is fixed in #26284.
