### ISSUE TITLE
Update repository size when pushing failure

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#25272]
### Description

```
2023/06/13 01:27:08 ...s/repository/push.go:97:pushUpdates() [E] Failed to update size for repository: updateSize: lstat /home/git/gitea-repositories/xxx/xxxx.git/objects/51/f2b199428f70eb68a9490af46d203767ae71a4: structure needs cleaning
```

### Gitea Version

main

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

Windows

### How are you running Gitea?

download the official binary

### Database

None

**Comment by yp05327** [comment]
The file system is broken?

**Comment by lunny** [comment]
Looks like it's a file system level problem and unrelated with Gitea itself. Let's close this one.
