### ISSUE TITLE
Basic functionality needs JavaScript

### ISSUE THREAD

**Issue by rambo-wears-a-pinky-thong** [go-gitea/gitea#2527]
- Gitea version (or commit ref):  dev
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes
  - [ ] No
  - [ ] Not relevant

## Description

Gitea works more or less well without javascript, but there are some features that are not accessible because the top menu requires javascript. These are 

- create new organization
- create new mirror
- change user settings
- logout
- the list of repositories is not visible at all

could the menus on the top bar please  be replaced with CSS/HTML menus only?

**Comment by lunny** [comment]
I think #2538 is the real duplicated one. But since @rambo-wears-a-pinky-thong closed this. Let's keep #2538 open until #2541 merged.
