### ISSUE TITLE
Under the repo page, text and icon overlap of add file button

### ISSUE THREAD

**Issue by hiifong** [go-gitea/gitea#25282]
### Description

![image](https://github.com/go-gitea/gitea/assets/89133723/8f0c216b-6c2a-4e5e-ba07-46c6a0402b94)

### Gitea Version

1.20.0+rc0

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

./gitea web

### Database

None

**Comment by silverwind** [comment]
Noticed that too earlier. https://github.com/go-gitea/gitea/pull/25277 will fix it.
