### ISSUE TITLE
When deleting a repo, it is forbidden to use the mouse to select the repo name

### ISSUE THREAD

**Issue by hiifong** [go-gitea/gitea#25283]
### Feature Description

like github：
![image](https://github.com/go-gitea/gitea/assets/89133723/306f55e0-231b-436d-bf0e-e3444106c96c)

this is gitea：
![image](https://github.com/go-gitea/gitea/assets/89133723/cc91e66a-4168-4586-a5ca-262db86c7f06)

**Comment by stuzer05** [comment]
Why?

**Comment by silverwind** [comment]
I always just copy it from there, it's very useful. Forcing the user to type this is a dark pattern that we imho should do.

**Comment by wxiaoguang** [comment]
Agree, I also like copying it.
