### ISSUE TITLE
a problem with the documentation related to the  "packages"

### ISSUE THREAD

**Issue by ExplodingDragon** [go-gitea/gitea#25302]
### Screenshots

I also observed problems with the documentation related to the package.

![图片](https://github.com/go-gitea/gitea/assets/33776693/3b7216c3-f132-4512-a4b9-d0617a424fd9)

![图片](https://github.com/go-gitea/gitea/assets/33776693/183de4c6-6ef6-4cd6-a96d-8b598318e1db)

![图片](https://github.com/go-gitea/gitea/assets/33776693/f9a52ea5-d74f-4cc9-b71e-063840c23736)

### Gitea Version

1.20.0-rc0

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

rocky linux 9 amd64

### Browser Version

firefox-113.0.1 linux by arch linux

**Comment by KN4CK3R** [comment]
Thank you! Fixed with #25310.
