### ISSUE TITLE
Internal Server Connection Error

### ISSUE THREAD

**Issue by M-Arthur-A** [go-gitea/gitea#25325]
### Description

steps:
- fresh install from binary
- create test empty repository
- try to push through ssh
- try to push through https

results:
- from ssh method:
```
Gitea: Internal Server Connection Error
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
- from https method:
```
Enumerating objects: 3, done.
Counting objects: 100% (3/3), done.
Writing objects: 100% (3/3), 215 bytes | 215.00 KiB/s, done.
Total 3 (delta 0), reused 0 (delta 0), pack-reused 0
remote:
remote: Gitea: Internal Server Connection Error
To https://192.168.1.4:3000/home/test.git
! [remote rejected] dev -> dev (pre-receive hook declined)
error: failed to push some refs to 'https://192.168.1.4:3000/home/test.git'
```

attempts to fix:
- setting `LOCAL_ROOT_URL=http://127.0.0.1:3000/` in /etc/gitea/app.ini
- 'Reinitialize all missing Git repositories for which records exist' from 'Maintenance Operations' of 'Site administration' menu
- switching in different branches

### Gitea Version

1.20.0+rc0-28-g5191ab644

### Log Gist

https://gist.github.com/M-Arthur-A/7968b553373a5e67095f633fcbb31e0e

### Screenshots

![Screenshot_20230617_222433](https://github.com/go-gitea/gitea/assets/61663555/3cdd400f-2af9-47e7-8fb1-04d21b005c81)

### Git Version

2.34.1

### Operating System

Ubuntu 22.04.2

### How are you running Gitea?

systemd

### Database

SQLite

**Comment by eeyrjmr** [comment]
You have aspects set to port 1881 but are trying to push to port 3000 

LOCAL_ROOT_URL=http://127.0.0.1:1881/

**Comment by M-Arthur-A** [comment]
> You have aspects set to port 1881 but are trying to push to port 3000
> 
> LOCAL_ROOT_URL=http://127.0.0.1:1881/

I just copied from another topic literally. Corrected in the description

**Comment by eeyrjmr** [comment]
Can you post your app.ini and full debug logs

This feels like a port issue since you will have
1. Http
2. Https
3. SSH

**Comment by M-Arthur-A** [comment]
> Can you post your app.ini and full debug logs
> 
> This feels like a port issue since you will have
> 
>     1. Http
> 
>     2. Https
> 
>     3. SSH

app.ini: https://gist.github.com/M-Arthur-A/491a0247a8441da8919db866d5cc1c5e

debug log: https://gist.github.com/M-Arthur-A/1d1cd905568c181f8ea7dac06c44206c

**Comment by wxiaoguang** [comment]
It would be quite tricky if you mix `PROTOCOL= https` + `LOCAL_ROOT_URL=http://127.0.0.1:3000/`

I have no idea about how to make them work together.

Either:

```
PROTOCOL=https
LOCAL_ROOT_URL=https://domain-with-valid-cert:3000/
```

Or

```
PROTOCOL=http
LOCAL_ROOT_URL=http://your-host-or-ip:3000/
```

**Comment by M-Arthur-A** [comment]
> It would be quite tricky if you mix `PROTOCOL= https` + `LOCAL_ROOT_URL=http://127.0.0.1:3000/`
> 
> I have no idea about how to make them work together.
> 
> Either:
> 
> ```
> PROTOCOL=https
> LOCAL_ROOT_URL=https://domain-with-valid-cert:3000/
> ```
> 
> Or
> 
> ```
> PROTOCOL=http
> LOCAL_ROOT_URL=http://your-host-or-ip:3000/
> ```
```
PROTOCOL=https
LOCAL_ROOT_URL=https://domain-with-valid-cert:3000/
```
it helps! thank you!
