### ISSUE TITLE
Failing to redirect after creating an issue

### ISSUE THREAD

**Issue by stuzer05** [go-gitea/gitea#25321]
### Description

When you click on "create" in issues, gitea shows json with redirect urls

### Gitea Version

trunk

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/23124682/37fa53ca-0e6f-4670-b68a-379e51d0679a)

### How are you running Gitea?

docker

### Database

None

**Comment by wxiaoguang** [comment]
After Use fetch to send requests to create issues/comments #25258 , Gitea uses AJAX to submit issue/comment forms, so backend returns the JSON "redirect".


On try.gitea.io, I can't reproduce your problem.

**Comment by stuzer05** [comment]
I found out, that I've overritten issue templates in gitea's custom folder. Those were like 2 days old and already broke. I reverted the changes and now everything is okay
