### ISSUE TITLE
Diff stats in PR tab bar

### ISSUE THREAD

**Issue by silverwind** [go-gitea/gitea#25326]
### Feature Description

It would be nice if we could show a diff stat on the right side of the PR tab bar.

### Screenshots

<img width="1227" alt="image" src="https://github.com/go-gitea/gitea/assets/115237/a7e92e71-0b8e-4cd3-a5a5-521c7db812a2">

**Comment by hiifong** [comment]
How to calculate the number of squares is a problem?

**Comment by silverwind** [comment]
We don't have squares in the file header either, so a "fluid" bar like there will do.

<img width="260" alt="image" src="https://github.com/go-gitea/gitea/assets/115237/a34e7dc2-f131-481b-8d8e-80a2c8e4f6f8">

**Comment by hiifong** [comment]
Which method is called by default when the path `{user}/{repo}/pull/{index}` is requested,
![image](https://github.com/go-gitea/gitea/assets/89133723/c77ba4e4-4163-44f8-8633-1f2229839a8f)
![image](https://github.com/go-gitea/gitea/assets/89133723/5e4f4541-6577-4be6-9f14-6fc0d3b6ad21)

**Comment by silverwind** [comment]
Keep note that it should show an all tabs, e.g. the relevant context info needs to be added to GET `/files` and `/commits` as well.

**Comment by hiifong** [comment]
`a: added`, `b: deleted`, `x: block-added`, `y: block-deleted`, `z: block-neutral`
| a    | b    | x    | y    | z    |
| ---- | ---- | ---- | ---- | ---- |
| 5    | 4    | 2    | 2    | 1    |
| 8    | 8    | 2    | 2    | 1    |
| 83   | 30   | 3    | 1    | 1    |
| 652  | 1    | 4    | 0    | 1    |
| 220  | 196  | 2    | 2    | 1    |
| 174  | 134  | 2    | 2    | 1    |
| 1373 | 1425 | 2    | 2    | 1    |
| 99   | 6    | 4    | 0    | 1    |
| 36   | 2    | 4    | 0    | 1    |
| 24   | 4    | 4    | 0    | 1    |
| 158  | 15   | 4    | 0    | 1    |
| 22   | 4    | 4    | 0    | 1    |
| 120  | 0    | 5    | 0    | 0    |
| 83   | 22   | 3    | 1    | 1    |
| 340  | 0    | 5    | 0    | 0    |
| 416  | 151  | 3    | 1    | 1    |
| 384  | 14   | 4    | 0    | 1    |
| 8    | 11   | 2    | 2    | 1    |
| 25   | 50   | 1    | 3    | 1    |
| 4    | 0    | 4    | 0    | 1    |
| 44   | 46   | 2    | 2    | 1    |
| 104  | 47   | 3    | 1    | 1    |
| 7345 | 16   | 4    | 0    | 1    |
| 0    | 40   | 0    | 5    | 0    |
| 3    | 9    | 1    | 3    | 1    |
| 0    | 1    | 0    | 1    | 4    |
| 13   | 25   | 1    | 3    | 1    |
| 9    | 15   | 1    | 3    | 1    |
| 6    | 18   | 1    | 3    | 1    |
| 5    | 17   | 1    | 3    | 1    |
| 329  | 0    | 5    | 0    | 0    |
| 222  | 32   | 4    | 0    | 1    |
| 216  | 172  | 2    | 2    | 1    |
| 2    | 4    | 1    | 3    | 1    |

**Comment by hiifong** [comment]
![image](https://github.com/go-gitea/gitea/assets/89133723/94551d6d-8030-40ad-b83e-b4b2f12b0bee)
![image](https://github.com/go-gitea/gitea/assets/89133723/9c2943ef-ec66-45c3-8422-2ca955e56233)
![image](https://github.com/go-gitea/gitea/assets/89133723/7d5bf035-c120-494f-a1b7-902cc82d7d4c)
