### ISSUE TITLE
Restoring Branch cannot work

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#25348]
### Gitea Version

main(1d92d0cf0f1799d6d6b167f9b0b5e8140b5d43ea)

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

<img width="600" alt="图片" src="https://github.com/go-gitea/gitea/assets/81045/e600a5f2-8b93-482f-bc57-93defc5a0aee">

### How are you running Gitea?

Build Gitea development version

### Database

None

**Comment by wxiaoguang** [comment]
Fix incorrect link-action event target #25306
