### ISSUE TITLE
Set user avatar with CLI or API

### ISSUE THREAD

**Issue by lonix1** [go-gitea/gitea#25344]
### Feature Description

We use automation (ansible) to setup multiple servers, each has gitea and our ci/cd stuff. We create the same users each time for our team members.

One can create a user with the CLI: username, password, email, is_admin.

But it's not possible to specify the avatar. It would be nice to do that with the CLI (or some other method, maybe just put the images in a certain directory using a certain filename?).

**Comment by silverwind** [comment]
I guess it could be added, but 5 arguments on a CLI is already pushing the complexity. It may already be possible via API to set the avatar, and your use case does sound like it may be better done with an API client.

**Comment by silverwind** [comment]
Yeah, it seems we are lacking both a `POST /user` and a `PATCH /user`.

**Comment by JakobDev** [comment]
I will start working on this
