### ISSUE TITLE
Network Error when creating pull request

### ISSUE THREAD

**Issue by stuzer05** [go-gitea/gitea#25351]
### Description

Press this button to create pull request and see the error

POST request returns HTML instead of json

### Gitea Version

trunk

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/23124682/da952c1e-d9ad-4882-9fda-2a0599e84d84)

![image](https://github.com/go-gitea/gitea/assets/23124682/bb50caeb-572e-4e44-b353-6241aaf9a1cd)

![image](https://github.com/go-gitea/gitea/assets/23124682/0f466f0c-c7f3-4684-ae08-543bb6745729)

### How are you running Gitea?

https://try.gitea.io

### Database

None

**Comment by wxiaoguang** [comment]
Oops, sorry I missed that 

 Make backend code respond correct JSON when creating PR #25353
