### ISSUE TITLE
Version for dev builds is not showing anymore

### ISSUE THREAD

**Issue by stuzer05** [go-gitea/gitea#25350]
### Description

Empty version in the footer, before there was a git commit hash

### Gitea Version

trunk

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/23124682/640a08c1-c7da-4f93-9929-aa31de05132b)

### How are you running Gitea?

https://try.gitea.io/

### Database

None

**Comment by makkes** [comment]
This breaks the [official go-sdk](https://gitea.com/gitea/go-sdk/) as in `gitea.NewClient(host, gitea.SetToken("token"))` returns an error:

```
Malformed version: 
```

**Comment by noahziheng** [comment]
> This breaks the [official go-sdk](https://gitea.com/gitea/go-sdk/) as in `gitea.NewClient(host, gitea.SetToken("token"))` returns an error:
> 
> ```
> Malformed version: 
> ```

I meet this problem too.

**Comment by techknowlogick** [comment]
Reopening as my PR may not have actually fixed this

**Comment by noahziheng** [comment]
This problem may be fixed by #25381 .

Version is showing in latest nightly image

**Comment by stuzer05** [comment]
> This problem may be fixed by #25381 .
> 
> Version is showing in latest nightly image

I can confirm, version is showing in the latest nightly build
![image](https://github.com/go-gitea/gitea/assets/23124682/c891154a-8e0e-465f-ae9d-d9e6ce02470d)
