### ISSUE TITLE
Gitea keeps restarting after receiving SIGTERM

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#25366]
### Description

Gitea service keeps receiving a SIGTERM and restart automatically. This repeats about every 90 seconds.

### Gitea Version

1.19.3

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.githubusercontent.com/innostus/76c9de74d0a16d376b415607947ad1fe/raw/2385b231afc72dca2b456f6889fadb49429c1926/gitea.log

### Git Version

2.39.2

### Operating System

debian 12

### How are you running Gitea?

Used a binary download. Running by systemd.

### Database

MySQL

**Comment by lunny** [comment]
Could you paste your system service file?

**Comment by innostus** [comment]
https://gist.githubusercontent.com/innostus/89f33d572167aada54d4463add52fff1/raw/cfc62547fdeccd8c68068f6296aabdbc966339f1/gitea.service

**Comment by delvh** [comment]
`notify` means that Gitea notifies systemd if and when it is ready.
And as the support for this protocol has only been added in 1.20, Gitea 1.19 never reports anything which makes systemd think something is wrong with the application and restarts it.

**Comment by lunny** [comment]
As @delvh  said. And a recent change of docs site is the source ref link can be changed via your chosed version. i.e. The link of the service file on https://docs.gitea.com/1.20/installation/linux-service will point to the file in branch `release/v1.20`.
I think we can close this now and feel free to reopen if it's still an issue.
