### ISSUE TITLE
Error 500 when trying to webview a specific repository

### ISSUE THREAD

**Issue by netzwerkgoettin** [go-gitea/gitea#2537]
- Gitea version (or commit ref):
- Git version: 1.1.4
- Operating system: Debian 8
- Database:
  - [x] MySQL
- Can you reproduce the bug at https://try.gitea.io:
  - [x] No
- Log gist: in log/gitea.log:
```
[...routers/repo/view.go:52 renderDirectory()] [E] GetCommitsInfo: GetCommitByPath (/Iconr): Length must be 40:
```

## Description
I manage several repositories via Gitea, and they a working like a charm. But one specific throws an 500 server error when I try to open it in the browser. In the logs I can stat this message:
```
[...routers/repo/view.go:52 renderDirectory()] [E] GetCommitsInfo: GetCommitByPath (/Iconr): Length must be 40:
```

But I can clone and push without any problem. 

Where to start debugging?

Cheers,
  Marianne

## Screenshots
![screen shot 2017-09-18 at 10 09 50](https://user-images.githubusercontent.com/11242139/30533413-8ecb36b8-9c59-11e7-96c3-4e1df844ad38.jpg)

**Comment by lunny** [comment]
It seems there was already an issue to describe that.

**Comment by lafriks** [comment]
I think this was already fixed in 1.2

**Comment by lunny** [comment]
@sysadmama could you confirm that?

**Comment by netzwerkgoettin** [comment]
@lunny + @lafriks Nope; started 1.2.0+rc2 yesterday and still error 500 on this specific repository. gitea.log.

```
[...routers/repo/view.go:53 renderDirectory()] [E] GetCommitsInfo: GetCommitByPath (/Iconr): Length must be 40:
```

Cheers,
  Marianne

**Comment by lafriks** [comment]
@sysadmama is that repository public so we could reproduce that issue?

**Comment by netzwerkgoettin** [comment]
@lafriks No it's reachable via VPN only :( Are there any further logfiles I could consult? Even `strace` doesn't enlighten me.

**Comment by lunny** [comment]
@lafriks @sysadmama I remember I have tried to resolve this issue but I failed.

**Comment by Andlix** [comment]
Here is an example for an 500 with Version 1.2.0+rc3-6-g03ff7687: 
https://try.gitea.io/AndyTest/TestDev.git
But with try.gitea.io it hangs.

The strings (of the filenames) are not escaped. I could imagine, that this would be a security issue, too.

**Comment by netzwerkgoettin** [comment]
Tried it with my repository: I accidentally had an empty File called `Icon?`. I removed it completely, and after a `push` I can access my repo via web interface. So I also would assume it's the (wrong or non existent) escaping.

**Comment by lunny** [comment]
@sysadmama The filename contains a special character gitea didn't parse correctly.

**Comment by ethantkoenig** [comment]
@Andlix It seems that we fail with filenames containing newlines (i.e. `\n`). I believe that none of the other filenames in your test repo cause problems.

**Comment by jxsl13** [comment]
same issue: [linkt to try.gitea.io](https://try.gitea.io/jxsl13/Software-Engineering/src/branch/john) 
after merging my repo from github, the branches seem to be missing, causing the 500 error.

gitea.log:
```
2017/12/14 06:42:16 [...s/context/context.go:118 NotFoundOrServerError()] [E] GetRepositoryByOwnerAndName: repository does not exist [id: 0, uid: 0, owner_name: 2016, name: 09]
2017/12/14 12:53:23 [...routers/repo/view.go:54 renderDirectory()] [E] GetCommitsInfo: Length must be 40:
```

**Comment by dmarov** [comment]
same issue with file named ":w"

**Comment by zeripath** [comment]
This is both a duplicate and fixed likely by one of @mrsdizzie escaping patches.
