### ISSUE TITLE
Newly installed instance could use incorrect "utf8" charset for MySQL

### ISSUE THREAD

**Issue by wxiaoguang** [go-gitea/gitea#25378]
A default install could produce such app.ini:

```
APP_NAME=Gitea: Git with a cup of tea
RUN_USER=xiaoguang
RUN_MODE=prod

[database]
DB_TYPE=mysql
HOST=127.0.0.1:3306
NAME=gitea
USER=gitea
PASSWD=gitea
SCHEMA=
SSL_MODE=disable

CHARSET=utf8     !!!!!!!!!!!! wrong here

PATH=/Users/xiaoguang/work/gitea/data/gitea.db
LOG_SQL=false
```

"utf8mb4" is required for MySQL to work with emoji.

**Comment by wxiaoguang** [comment]
Keep it open for 1.20 .... it's a serious problem now ....

**Comment by lunny** [comment]
Could you backport #25413 ?

**Comment by wxiaoguang** [comment]
There is a separate PR #25432 for 1.20, while I do not understand why there was objection for backporting #25413 or what's the difference between them.

**Comment by lunny** [comment]
> There is a separate PR #25432 for 1.20, while I do not understand why there was objection for backporting #25413 or what's the difference between them.

Now I can understand backporting #25413 will not break too much.
