### ISSUE TITLE
Basic functionality needs JavaScript

### ISSUE THREAD

**Issue by jorgesumle** [go-gitea/gitea#2538]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [x] PostgreSQL
  - [x] MySQL
  - [x] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (https://try.gitea.io/ [logged in]) 
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

Gitea works more or less well without JavaScript, but there are some features that are not accessible because the top menu and other parts of the GUI require JavaScript. Also (a minor thing) the message 'Please enable JavaScript in your browser!' is not internationalized.
 
See also https://github.com/gogits/gogs/issues/4778 and https://github.com/gogits/gogs/pull/4780

**Comment by sapk** [comment]
Please submit your PR also to gitea. 
For i18n you need to add the phrase inside : `options/locale/locale_en-US.ini`. The others files, inside `options/locale/`, are generated from crowdin.

**Comment by jorgesumle** [comment]
Duplicated here: https://github.com/go-gitea/gitea/issues/2527

Sorry for that, I didn't notice.

**Comment by bkcsoft** [comment]
Closed by #2541 ?

**Comment by lunny** [comment]
@bkcsoft I think yes.
