### ISSUE TITLE
Router `/user/events` takes too long to respond

### ISSUE THREAD

**Issue by hiifong** [go-gitea/gitea#25394]
### Description

```log
2023/06/21 00:01:26 ...eb/routing/logger.go:102:func1() [I] router: completed GET /user/events for 127.0.0.1:38122, 200 OK in 1914521.9ms @ events/events.go:18(events.Events)
```

### Gitea Version

v1.20+

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

./gitea web

### Database

None

**Comment by KN4CK3R** [comment]
That endpoint is an event stream and the lifetime is no bug.

https://github.com/go-gitea/gitea/blob/feda5063217b44a0b66e25726e8975795c308a87/routers/web/events/events.go#L18
