### ISSUE TITLE
Consider snap/flatpak packaging for Gitea

### ISSUE THREAD

**Issue by lofidevops** [go-gitea/gitea#2539]
- Gitea version (or commit ref): N/A
- Git version: N/A
- Operating system: Any GNU/Linux
- Database (use `[x]`):
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Not relevant
- Log gist: N/A

**User story:** I am a regular user with no/minimal configuration needs. I just want to install Gitea and keep it up-to-date.

**Proposed solution:** Release a flatpak or snap package. Releasing in this format requires fewer procedural barriers and allows users to keep up-to-date even if their distro doesn't. (Although inclusion in, for example, Debian is still a worthy goal.) Both formats are well-supported across all distros.

There is an example of a Gogs snap package here: https://github.com/tbraeutigam/gogs-snap

**Comment by tbraeutigam** [comment]
Please see above -- a pull request for snap-packing gitea :+1:

**Comment by lofidevops** [comment]
Anything I can do to help get this merged?

@tbraeutigam How much maintenance do these additions require?

**Comment by sapk** [comment]
@kwill Even if you aren't a maintainer, I would gladly appreciate your review or at least any suggestion as they seems to haven't maintainers with experience with snap packing.

**Comment by lofidevops** [comment]
@sapk I'm afraid I'm not qualified to review snap packaging, but I'm happy to follow instructions to run tests (eg. build the snap locally and check that it installs as expected; I'm not sure about how to get it on snapcraft.io).

**Comment by tbraeutigam** [comment]
Maintenance is relatively low.

As I just added configuration integration between the snap system and the gitea `app.ini` file, this might need maintenance if there are changes to file locations/large renaming of the options, but that's the biggest part I can think of.

As long as there's no desire to keep track of new snap package features and integrating them, it'll be relatively easy.

To get it onto `build.snapcraft.io`, you just have to go to the site, create an account and log in, and it guides you on how to allow the site to set a trigger for building.

It will then automatically build on new commits and push it to the 'edge' track.
You can then promote specific snaps to the other channels (stable, candidate & beta) either via `https://dashboard.snapcraft.io/` (same username & pw) or via command line `snapcraft` command as seen here: https://docs.snapcraft.io/core/store

**Comment by lunny** [comment]
resolved by #2568
