### ISSUE TITLE
Incorrect DEFAULT_ACTIONS_URL in act_runner

### ISSUE THREAD

**Issue by ofnhkb1** [go-gitea/gitea#25404]
### Description

In gitea/act_runner:0.2.0, the DEFAULT_ACTIONS_URL configured in app.ini does not take effect

But it is right at gitea/act_runner:0.1.8

### Gitea Version

gitea/gitea:1.19.3

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

gitea/act_runner:0.2.0
![66KLU0S}5S6RQG G0FZLT98](https://github.com/go-gitea/gitea/assets/8349882/a4f1cef5-e35b-451c-8a5b-da6fa77d8fa8)

app.ini
![`YY}{IYX{PKWH)YTOV9O2EP_tmb](https://github.com/go-gitea/gitea/assets/8349882/afe1640f-281f-4298-9d08-b7755ce8cdaf)

gitea/act_runner:0.1.8
![SLBW{YNSGXEW{TX6Q6$HF04_tmb](https://github.com/go-gitea/gitea/assets/8349882/b3dae228-3a65-4eff-aff6-1c0f0a621101)

### How are you running Gitea?

kubernetes

### Database

None

**Comment by Zettat123** [comment]
Could you please download [the latest build](https://dl.gitea.com/act_runner/nightly/) and try again?
