### ISSUE TITLE
REGISTER_EMAIL_CONFIRM not correctly reflected on Web

### ISSUE THREAD

**Issue by wxrl** [go-gitea/gitea#25421]
### Description

No matter `REGISTER_EMAIL_CONFIRM=true` or `REGISTER_EMAIL_CONFIRM=false` is set in `app.ini`, the  **Require Email Confirmation to ...** is always × in web **Configuration** page. Restarting the `gitea.service` doesn't change the situation.

Also, the space (width) for configuration item names (left part) in the  **Configuration** page is not enough for displaying the full item name, which is really not good.

![Screenshot from 2023-06-21 16-04-34](https://github.com/go-gitea/gitea/assets/81678209/eb2be542-62c1-458c-99ed-bb6b4bdeb796)

### Gitea Version

1.20

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

Binary (Debian 12, Linux Service, MariaDB)

### Database

None

**Comment by techknowlogick** [comment]
Do you have a mailer service configured? As I haven't been able to confirm this otherwise.

**Comment by wxiaoguang** [comment]
You need a working mail config first to make REGISTER_EMAIL_CONFIRM could be true
