### ISSUE TITLE
PR files tab style problem

### ISSUE THREAD

**Issue by zhu-hongwei** [go-gitea/gitea#25424]
### Gitea Version

1.18.3

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

<img width="1440" alt="image" src="https://github.com/go-gitea/gitea/assets/61079864/e568744c-42fb-4f03-9803-1efc9b654521">

### Operating System

chrome 114.0.5735.133（正式版本） (x86_64).    macos 10.14.5 (18F132)

### How are you running Gitea?

...

### Database

PostgreSQL

**Comment by lunny** [comment]
Could you reproduce that on https://try.gitea.io ?

**Comment by wxiaoguang** [comment]
* #23248

**Comment by silverwind** [comment]
I think 1.18 is EOL, so please upgrade to 1.19 which has the fix.
