### ISSUE TITLE
Logging in when already logged in redirects to front page

### ISSUE THREAD

**Issue by drsybren** [go-gitea/gitea#25435]
### Description

When you log in on one browser tab, and then press the login button on another tab, it redirects to the front page.

- Open https://try.gitea.io/drSybren/skyfill in a browser tab.
- Open https://try.gitea.io/drSybren/skyfill in another browser tab.
- In the first tab, log in. This redirects you to the same URL you pressed the login button on.
- In the second tab, click the login button.
- You're now redirected to the front page, https://projects.blender.org/.

I would expect to end up on the same URL, just like the first login did.

Note that this behaviour is always seen, not just when using two the same URLs in those tabs. It just made testing easier.

### Screenshots

This is not a graphical glitch, so can't be caught in a screenshot.

### Gitea Version

1.20.0+dev-1026-ge29ab5442

### Can you reproduce the bug on the Gitea demo site?

Yes

### Browser Version

Brave 1.52.126

**Comment by yp05327** [comment]
Checked in latest version 1.22.0+dev-1113-g99d7ef509, it seems that this issue has been fixed.
Can you confirm it again? Thanks.

**Comment by wxiaoguang** [comment]
Oh yes, it should have been fixed by " Make "/user/login" page redirect if the current user has signed in #29583 " (and backported to 1.21)

Feel free to reopen if there is still any problem. Thank you!

**Comment by drsybren** [comment]
I can confirm this was fixed, thanks!
