### ISSUE TITLE
Pressing 'Enter' on repo settings modals hides the modal

### ISSUE THREAD

**Issue by denyskon** [go-gitea/gitea#25438]
### Description

When trying to delete/transfer/archive a repo from its settings, entering the name and pressing enter, the modal is simply being hidden instead of deleting the repo.

### Gitea Version

1.20-nightly

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

docker rootful

### Database

None

**Comment by silverwind** [comment]
This 'Enter not working' affects a number of modals, including the "create tag" from commits page "Operations" button:

<img width="787" alt="Screenshot 2023-06-22 at 14 21 33" src="https://github.com/go-gitea/gitea/assets/115237/c20e1202-a244-4508-a685-e0c4c579c82a">

**Comment by JakobDev** [comment]
Maybe we should ditch our custom solution and should use the [new dialog HTML Element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog). According to [Can I Use](https://caniuse.com/mdn-html_elements_dialog), it is already supported by 92.86% of the Web Users.

**Comment by silverwind** [comment]
Yes, that would be preferred as we can then get rid of the fomantic modal module.

**Comment by wxiaoguang** [comment]
It's caused by abuse of Fomantic Modal in old code.

I think the new "form-fetch-action" could help and could be a clear solution.

**Comment by wxiaoguang** [comment]
Will be fixed by  Make buttons in a modal form have proper type #25446 (for most)

**Comment by delvh** [comment]
Not fixed?

**Comment by denyskon** [comment]
The fix was reverted because it introduced even more problems :/

**Comment by wxiaoguang** [comment]
The complete fix:  Make "cancel" buttons have proper type in modal forms #25618
