### ISSUE TITLE
Navbar menu regression

### ISSUE THREAD

**Issue by wxiaoguang** [go-gitea/gitea#25444]
### Description

I guess it's related to "Navbar styling rework #25343" but I haven't confirmed.

![image](https://github.com/go-gitea/gitea/assets/2114189/356134cb-4d4f-41e0-9f89-8f837bd78d6d)

### Gitea Version

main

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

N/A

### Database

None

**Comment by silverwind** [comment]
Will be fixed by https://github.com/go-gitea/gitea/pull/25402.
