### ISSUE TITLE
retain content deleted upstream in a pull mirror

### ISSUE THREAD

**Issue by DyingStar314** [go-gitea/gitea#25472]
### Feature Description

Allow the mirror repository to remain if the source repository is completely deleted by the author

**Comment by delvh** [comment]
Wait, it is currently deleted?

**Comment by Dying-star** [comment]
Probably the translation tool is not very accurate. For example, I mirror a GitHub repository, but the author of the GitHub repository deletes everything, including historical commit records, etc., but the repository is still there. The image repository also synchronizes such deletions

**Comment by lunny** [comment]
> Probably the translation tool is not very accurate. For example, I mirror a GitHub repository, but the author of the GitHub repository deletes everything, including historical commit records, etc., but the repository is still there. The image repository also synchronizes such deletions

So you mean just sync `add`, `update` operations but not `delete` operations?

**Comment by KN4CK3R** [comment]
This is a duplicate. There was a similar request some months/years ago.
