### ISSUE TITLE
Can't delete repo

### ISSUE THREAD

**Issue by hiifong** [go-gitea/gitea#25482]
### Description

https://github.com/go-gitea/gitea/assets/89133723/9ce64041-dc7c-4818-8ffc-82fe40eccda7

### Gitea Version

v1.20+

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

./gitea web

### Database

None

**Comment by wxiaoguang** [comment]
* #25484
* #25485
