### ISSUE TITLE
"Comment and close" replaces first issue comment with last comment

### ISSUE THREAD

**Issue by mxmehl** [go-gitea/gitea#2551]
- Gitea version (or commit ref): d155d0e
- Git version: 2.1.4
- Operating system: Debian 8
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL): https://try.gitea.io/mxmehl/test1/issues/1
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

This is a very severe bug because is modifies issues and potentially important information!

In an open issue, when clicking "comment and close", the text of the closing comment replaces the text of the first comment in this issue (*fortunately* not those in between).

Examples: https://try.gitea.io/mxmehl/test1/issues/1 or https://git.fsfe.org/pmpc/website/issues/89

**Comment by lafriks** [comment]
Not present in 1.2.0-rc2 only on master branch

**Comment by mxmehl** [comment]
The bug also happens when reopening an issue with a comment.

Does anyone have an idea how this could have been caused in the latest commits?

**Comment by mxmehl** [comment]
Workaround: Comment on an issue, and close it in a second step. Then the first message isn't overwritten. But who does it this way if there's a shortcut?
