### ISSUE TITLE
webhooks supports custom type or target url

### ISSUE THREAD

**Issue by liyunde** [go-gitea/gitea#25513]
### Feature Description

how to supports custom webhooks type that not in defined;

example:
1.  I want  to push message to my service which type not in supported
2.  I have a self hosted packagist service, how to push message to my url, not official url https://packagist.org

Is there a plan or solution,
or some suggest;
thanks

**Comment by techknowlogick** [comment]
closing as duplicate of https://github.com/go-gitea/gitea/issues/1089
