### ISSUE TITLE
Unstyled Link on Admin Dashboard

### ISSUE THREAD

**Issue by C-EO** [go-gitea/gitea#25527]
### Description

I discovered an unstyled link on the Admin Dashboard of my Gitea instance.

It is found under the `Applications` tab, when you're editing an OAuth2 application.

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/85847352/77e845ab-7430-4286-b972-f0e17b231d91)

### Gitea Version

v1.20.0+rc0-154-gd44a415bf 

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

linux 5.19.0-1026-gcp

### Browser Version

Microsoft Edge v114.0.1823.51 (Official build) (64-bit)

**Comment by silverwind** [comment]
It's a button, but I do agree we need to highlight it better, likely with an actual border.
