### ISSUE TITLE
docker registry not support  multi-architecture images

### ISSUE THREAD

**Issue by ExplodingDragon** [go-gitea/gitea#25526]
### Description

I compiled and pushed images of both architectures (amd64, arm64) to gitea using Podman, but only the last pushed image was kept on the page, and I observed that multiple architectures seem to be part of the [specification](https://github.com/opencontainers/image-spec/blob/main/manifest.md).

Is there something wrong with the way I'm pushing?

Test at: https://packages.d7z.net/images/rockylinux/packages

### Gitea Version

1.20.0-RC2

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

systemd

### Database

None

**Comment by KN4CK3R** [comment]
I can't tell what's wrong without more information but multi-architecture images are supported:

![](https://user-images.githubusercontent.com/1666336/159169400-42cf5936-039b-4008-915f-f730bb62e72b.png)

**Comment by ExplodingDragon** [comment]
Sorry, it's my problem.
Previously I was using separate compilation and push.

```bash
echo FROM quay.io/rockylinux/rockylinux:9 > Dockerfile
podman build --arch amd64  -t packages.d7z.net/images/rockylinux/el9/test --network host  --no-cache .
podman run -it --rm packages.d7z.net/images/rockylinux/el9/test uname -m
podman push packages.d7z.net/images/rockylinux/el9/test
podman build --arch arm64 -t packages.d7z.net/images/rockylinux/el9/test --network host  --no-cache .
podman run -it --rm packages.d7z.net/images/rockylinux/el9/test uname -m
podman push packages.d7z.net/images/rockylinux/el9/test
```

This will reproduce the previous problem. 


Later I changed to use the following command which works fine.

```bash
podman build --platform linux/amd64 --platform linux/arm64 --manifest packages.d7z.net/images/rockylinux/el9/test --network host  --no-cache   .
podman manifest push packages.d7z.net/images/rockylinux/el9/test packages.d7z.net/images/rockylinux/el9/test
```

Perhaps support for automatic change from single-architecture mirroring to multi-architecture mirroring (based on the first push method)?

**Comment by KN4CK3R** [comment]
The first example simply overwrites the `latest` tag and that's how it should work.
The working example creates a manifest index which includes both archs.
