### ISSUE TITLE
An admin connot see his organisation's packages

### ISSUE THREAD

**Issue by EndMove** [go-gitea/gitea#25538]
### Description

I do the update to the rc 1.20.0

Une utilisateur dont le nom d'utilisateur est "IO-Projects" n'a plus access au package de sont organisation. Cela étant dit le package est public, et si aucun utilisateur n'est connecté celui-ci reste accessible comme voulu.

### Gitea Version

1.20.0+rc

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

under my user :
![image](https://github.com/go-gitea/gitea/assets/38650560/5abdb368-44cb-4afd-9242-58dcf7f0f394)

under the owner user :
![image](https://github.com/go-gitea/gitea/assets/38650560/9f81e965-cb31-416a-bbf5-e7cd50da4610)

without being connected :
![image](https://github.com/go-gitea/gitea/assets/38650560/aed09371-95c1-4cc7-bd14-51efb6e566c6)

### How are you running Gitea?

on docker

### Database

MySQL

**Comment by EndMove** [comment]
An additional problem is that the user who owns the package can no longer publish (it denies access with a 403), but other users who are members of the project can.

**Comment by kimdre** [comment]
I have the same issue. I cannot access my own packages and get 404 errors and get unauthorized errors in my docker pipelines.
When I remove my ownership and just give me normal access rights I can view, pull and push packages just fine.
