### ISSUE TITLE
Unable to delete milestones

### ISSUE THREAD

**Issue by Fratee** [go-gitea/gitea#25557]
### Description

Cannot delete milestone after creation, same happens if the milestone is closed beforehand.

Steps to reproduce:
1. Create a new repository
2. Create a new milestone
3. Close the milestone
4. Delete the milestone

Expected behaviour:
The milestone is deleted

Actual behaviour:
The milestone is still present when the page refreshes

### Gitea Version

1.20.0-rc0

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

Windows 10

### How are you running Gitea?

Self hosted on windows 10

### Database

SQLite

**Comment by lunny** [comment]
Which repository did you test in try site?
