### ISSUE TITLE
Log stop ssh repo

### ISSUE THREAD

**Issue by m2nlight** [go-gitea/gitea#25552]
### Description

I cannot clone a ssh address repo.
The binary name: gitea-1.20-Gogot-windows4.0-amd64

I found this: [W] ScriptType "bash" is not on the current PATH throgh ssh -vvv command. 
It is a log info.

Then, I add a git-bash path to environment variable PATH to solved logger output. (Ref: https://github.com/go-gitea/gitea/issues/20580)

### Gitea Version

1.20.0+rc2-12-g102dcfa3a

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

Gitea on windows

### Database

None

**Comment by wxiaoguang** [comment]
The log problem will be fixed by 

* #25537

(by a backport)

**Comment by m2nlight** [comment]
That's great!
