### ISSUE TITLE
Actions step re-run button style issue when time so long

### ISSUE THREAD

**Issue by seepine** [go-gitea/gitea#25550]
### Description

See Screenshots

### Gitea Version

1.20.0+rc2

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/93666053/0a500d34-13be-400b-896d-0599077ec9ac)
![image](https://github.com/go-gitea/gitea/assets/93666053/a3f1f789-7538-4cd2-9a5c-a0e5532018ae)

### How are you running Gitea?

docker

### Database

MySQL

**Comment by silverwind** [comment]
Was fixed in https://github.com/go-gitea/gitea/pull/25531.
