### ISSUE TITLE
Language Switch select style optimization of Icon and Text a align

### ISSUE THREAD

**Issue by seepine** [go-gitea/gitea#25551]
### Gitea Version

1.20.0+rc2

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/93666053/8614b940-6de7-4ccc-a0d5-0d5b80eb489f)
![image](https://github.com/go-gitea/gitea/assets/93666053/059dfb8e-3342-49c3-be8b-25e483105c53)

### How are you running Gitea?

docker

### Database

None

**Comment by wxiaoguang** [comment]
Can you reproduce it on try.gitea.io ?
