### ISSUE TITLE
Enhancement of  Issue Multi selecting Feature

### ISSUE THREAD

**Issue by hardiklakhalani** [go-gitea/gitea#25561]
### Feature Description

Selecting multiple issues could be improved by adding either one or all of the above:

- [ ] Hold `Shift` to Select Multiple, (Select one & Shift Select another to auto-select in-between)
- [ ] `Ctrl/Cmd + A` to Select All of the visible issues

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/82162165/5c79c395-1c79-4348-a070-29faa6fa3146)

**Comment by wxiaoguang** [comment]
![image](https://github.com/go-gitea/gitea/assets/2114189/1475238b-a99a-427b-880f-8276ea105f08)
