### ISSUE TITLE
Unnecessary horizontal scrolling of the label selection component

### ISSUE THREAD

**Issue by kerwin612** [go-gitea/gitea#25575]
### Description

Unnecessary horizontal scrolling of the label selection component

### Screenshots

![}6~YIRK}YUBFKG00U%K{L A](https://github.com/go-gitea/gitea/assets/3371163/9a34d213-d2fb-40c5-984e-68bfbec8147c)

### Gitea Version

1.19.3

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

WIN10

### Browser Version

Microsoft Edge 版本 114.0.1823.58 (正式版本) (64 位)

**Comment by wxiaoguang** [comment]
Can you reproduce on try.gitea.io ?

**Comment by wxiaoguang** [comment]
It should have been fixed by https://github.com/go-gitea/gitea/pull/23653/files#diff-82c82a7062b055595984c9b71f98aa55805547a8a1a90322f4db9b8a16942463R147 

In 1.20
