### ISSUE TITLE
Older Gitea binaries won't run on MacOS 13.4 amd64

### ISSUE THREAD

**Issue by cheezedoodle2** [go-gitea/gitea#25570]
### Description

I have an Intel Mac running MacOS 13.4 (Ventura).  I'm trying to use it to upgrade a GOGS database, because the installation is in an arm64 (Ampere) exclusive environment, and there are no 1.0.x binaries available for arm64.  Compiling from scratch doesn't work either, because the 1.0.2 tree depends on things in code.gitea.io which no longer exist.

However, the 1.0.x darwin-amd64 binaries on gl.gitea.com don't work either, possibly because the older golang runtime is doing things this more modern MacOS kernel doesn't like.  Running the binaries results in them getting SIGKILL, and the crash report has this:

```
cat ~/Library/Logs/DiagnosticReports/gitea-1.0.0-darwin-10.6-amd64-2023-06-28-134330.ips  | jq .exception
null
{
  "port": 3418,
  "signal": "SIGKILL",
  "guardId": 0,
  "codes": "0x0000000000000d5a, 0x0000000000000000",
  "violations": [
    "INVALID_OPTIONS"
  ],
  "message": "mach_msg_trap() called with msgh_id 3418. The trap is not allowed on this platform.",
  "subtype": "GUARD_TYPE_MACH_PORT",
  "type": "EXC_GUARD",
  "rawCodes": [
    3418,
    0
  ]
}
```

### Gitea Version

1.0.0, 1.0.1, 1.0.2

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

N/A

### Operating System

MacOS 13.4

### How are you running Gitea?

Downloaded amd64-darwin binaries from here: https://dl.gitea.com/gitea/1.0.2/

### Database

None

**Comment by silverwind** [comment]
> Compiling from scratch doesn't work either, because the 1.0.2 tree depends on things in code.gitea.io which no longer exist.

Compiling may be your best bet. Which stuff is not there anymore? Maybe it can be restored.

**Comment by wxiaoguang** [comment]
Is your old instance large? If no, you could adopt the repositories and start a fresh Gitea instance.

Or, maybe you can try to use a Linux VM to run old binaries.

**Comment by silverwind** [comment]
https://github.com/go-gitea/gitea/issues/25570#issuecomment-1612316871 is the solution, just need to compile inside GOPATH with the vendor directory present which these old go versions require. If that does not work, manually move the files in place into GOPATH.
