### ISSUE TITLE
Font baseline is misaligned on issues page

### ISSUE THREAD

**Issue by stuzer05** [go-gitea/gitea#25597]
### Description

https://try.gitea.io/issues

### Gitea Version

trunk

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/23124682/f548cf95-3b11-41c0-8351-0a7421ec557e)
![image](https://github.com/go-gitea/gitea/assets/23124682/5911ca49-42c9-4e8c-b3a9-32b128f7a0cd)

### How are you running Gitea?

try.gitea.io

### Database

None

**Comment by hiifong** [comment]
Maybe this question is the same as the https://github.com/go-gitea/gitea/pull/25334.and that problem is not really solved
