### ISSUE TITLE
500 error: HasUserStopwatch, invalid connection

### ISSUE THREAD

**Issue by heannycn** [go-gitea/gitea#25616]
### Description

![image](https://github.com/go-gitea/gitea/assets/29299431/7704ef7d-486e-409b-8763-5680be96bc15)
I deployed Gitea in Docker, and the database is MySQL in Docker. When I logged into Gitea, the page reported an error of 500. The following is the log during login：
![image](https://github.com/go-gitea/gitea/assets/29299431/e6dbc38c-4a99-4e63-8013-f087f18b5b6d)
There is nothing in the log file
![image](https://github.com/go-gitea/gitea/assets/29299431/6f989122-a34e-4e36-8171-041e450e3389)

Here is my app.ini info
![image](https://github.com/go-gitea/gitea/assets/29299431/0ee7fde5-0bb5-413b-a249-2edb081ac48c)

and how can I resolve it . thanks a lot.

### Gitea Version

1.20.0+rc0

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

debian docker

### How are you running Gitea?

 docker-compose.yml：
version: '3.4'
services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    restart: unless-stopped
    networks:
      mycloud:
        ipv4_address: 172.1.0.21
    ports:
      - 1022:22
      - 8300:3000

### Database

MySQL

**Comment by lunny** [comment]
It's a database connection problem. Your docker-compose file doesn't configure database.

**Comment by heannycn** [comment]
![image](https://github.com/go-gitea/gitea/assets/29299431/fc25c93a-46fe-4f05-ac39-207e208f07b8)
The database is in a normal and other docker containers are in normal use. 
and visit gitea this morning is inexplicably normal.
When I enter a non-existent account, what prompts me is not a 500 error, but an account or password issue.

> It's a database connection problem. Your docker-compose file doesn't configure database.

**Comment by heannycn** [comment]
![image](https://github.com/go-gitea/gitea/assets/29299431/60d10a19-e2bf-4bc7-827e-1f44406f8022)
This is the database configuration content for Gitea and has not been changed in a long time

> It's a database connection problem. Your docker-compose file doesn't configure database.

**Comment by wolfogre** [comment]
Does your mysql has the fixed IP `172.1.0.2`? Could you show us the docker-compose.yml for mysql?
