### ISSUE TITLE
Styling Issues (CSS)

### ISSUE THREAD

**Issue by C-EO** [go-gitea/gitea#25628]
### Description

Firstly, I discovered that there is no spacing between the components under this route: `{INSTANCE_URL}/user/settings/security`

Secondly, under this route: `{INSTANCE_URL}/user/settings/account`, the alignment of the `Enable Email Notifications` dropdown and the `Set Email Preference` button is uneven.

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/85847352/7bbf4754-5171-4cbb-a643-6f34a02837ac)

![image](https://github.com/go-gitea/gitea/assets/85847352/e978276e-ed70-43ba-9737-9d78a2652b64)

### Gitea Version

1.21.0+dev-195-gaab7cb675

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

linux 5.19.0-1026-gcp

### Browser Version

Microsoft Edge v114.0.1823.51 (Official build) (64-bit)

**Comment by wxiaoguang** [comment]
Fix UI misalignment on user setting page #25629
