### ISSUE TITLE
Notification page update wrong page

### ISSUE THREAD

**Issue by bauermarkus** [go-gitea/gitea#25627]
### Description

When you have multiple pages of notifications and you open a notification in a new tab with page greater 1, the auto update of the notification page will push you back to page 1, even the URL still tells you the original page (greater 1).

### Gitea Version

1.20.0-rc1

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

Docker

### Database

SQLite

**Comment by wxiaoguang** [comment]
There is a bug in `updateNotificationTable` .....
