### ISSUE TITLE
Private repository,  team members cannot access

### ISSUE THREAD

**Issue by ryanlid** [go-gitea/gitea#2562]
## Description

I have try <https://try.gitea.io/>,  it have same problem

I have sign up 2 account: on1, on3 ,and on2 is team;
create a private repository "on2/test1" by on1 ,but "on3" cant access 

## Screenshots

account: on1
![on1](https://user-images.githubusercontent.com/6867964/30657990-f14cb266-9dfe-11e7-841f-4af37212de12.gif)

account: on3
![no3](https://user-images.githubusercontent.com/6867964/30657992-f2e25cac-9dfe-11e7-8672-f2e1bafc5dc0.gif)

**Comment by Morlinest** [comment]
You need to add user to team with access rights to private repository (default is owner team) if you want to grant him access to private repositories of organization. Showing private repositories of organization you are only member is bug, already reported in #2399 (and trying to solve it in #2371).
