### ISSUE TITLE
Actions page displays errors on the phone

### ISSUE THREAD

**Issue by ExplodingDragon** [go-gitea/gitea#25622]
### Description

ref: https://packages.d7z.net/packages/gitea/actions/runs/16/jobs/3

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/33776693/4d606539-371b-4512-b261-55721543aa79)

![image](https://github.com/go-gitea/gitea/assets/33776693/8f7b0b48-5f86-47f5-a13e-122ff7cd767d)

### Gitea Version

main

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

linux (x11)

### Browser Version

firefox latest stable

**Comment by denyskon** [comment]
I'm working on it, will fix soon
