### ISSUE TITLE
Broken translations

### ISSUE THREAD

**Issue by wxiaoguang** [go-gitea/gitea#25638]
Caught by #25635

And there are others: #25291

Admin/owner could fix them manually on Crowdin side.

```
========
WARNING: found broken locale: options/locale/locale_si-LK.ini , [repo] issues.filter_label_exclude
	str: Labels` ඉවත් කිරීමට <code>alt</code> + <code>ක්ලික් කරන්න/ඇතුළු කරන්න</code>
```

----

These are wrong in 1.20, which needs to be fixed manually during backporting.

<details>

```
----
WARNING: skip broken locale: options/locale/locale_pt-PT.ini , [repo] editor.filename_is_a_directory
	old: Nome_do_ficheiro "
	new: O nome de ficheiro "%s" já está a ser usado como um nome de pasta neste repositório.
----
WARNING: skip broken locale: options/locale/locale_ja-JP.ini , [action] rename_repo
	old: がリポジトリ名を <code>%[1]s</code> から <a href="%[2]s">[3]s</a> へ変更しました
	new: がリポジトリ名を <code>%[1]s</code> から <a href="%[2]s">%[3]s</a> へ変更しました
```

</details>

**Comment by lunny** [comment]
Updated https://crowdin.com/translate/gitea/68/enus-silk?filter=basic&value=0#q=filter_label_exclude

**Comment by wxiaoguang** [comment]
I will fix others after " Backport locale for 1.20 #25635 " gets merged

**Comment by 6543** [comment]
@wxiaoguang merged ;)

**Comment by wxiaoguang** [comment]
Some changes on Crowdin will be in main branch next day, so I will continue when I wake up tomorrow 🤣

**Comment by wxiaoguang** [comment]
->  Manuall backport of locale for 1.20 (2nd) #25668

**Comment by lunny** [comment]
Is this resolved?

**Comment by wxiaoguang** [comment]
This one is resolved, but there are new problems.

For example: the "package guideline" is broken .......

**Comment by lunny** [comment]
> This one is resolved, but there are new problems.
> 
> For example: the "package guideline" is broken .......

Fixed all of them on crowdin.

**Comment by wxiaoguang** [comment]
Unfornately, not "all" ....

There are still a lot (for every package). eg:

```
 # en-US
conda.documentation = For more information on the Conda registry, see <a target="_blank" rel="noopener noreferrer" href="%s">the documentation</a>.

# fr-FR (and many lanauges)
conda.documentation=Pour plus d'informations sur le registre Conda, voir <a target="_blank" rel="noopener noreferrer" href="https://docs.gitea.io/fr-fr/packages/conda/">la documentation</a>.
```

**Comment by wxiaoguang** [comment]
Remove broken translations #25737
