### ISSUE TITLE
Error assigning Issue to project (after the issue has been created)

### ISSUE THREAD

**Issue by lucas-labs** [go-gitea/gitea#25649]
### Description

I'm getting an error when trying to assign issues to a project once the issue has already been created (it works if I assign the issue to the project while creating the issue).

That is, when trying to assign the issue to the project here:

![image](https://github.com/go-gitea/gitea/assets/12949236/cca6054b-2162-4e7d-b637-b593e84c95b9)

The issue is reproducible in the Gitea demo (obviously, I can't see if the logs are the same, but I can't assign issues to projects there either)

### Gitea Version

1.20.0+rc2-25-g1ddfe0313

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

https://gist.github.com/lucas-labs/9622960103e75e627439bbe2ffc83f47

### Git Version

git version 2.35.0.windows.1

### Operating System

Windows 11

### How are you running Gitea?

As a Windows Service from the `gitea-1.20-windows-4.0-amd64.exe` binary provided in the downlaods page.

### Database

SQLite

**Comment by Zettat123** [comment]
might be related to 
https://github.com/go-gitea/gitea/blob/0403bd989f60ab84497eb5e04366496b3c9d2534/routers/web/repo/projects.go#L388-L391
