### ISSUE TITLE
Drop MySQL 5.7 support

### ISSUE THREAD

**Issue by silverwind** [go-gitea/gitea#25657]
MySQL 5.7 will reach EOL in [4 months](https://endoflife.date/mysql). We should:

- Drop it from CI matrix and remove relevant Makefile targets
- Update docs that MySQL 8.0 or greater is required

**Comment by lunny** [comment]
We can do it step by step. Firstly prevent new installation to chose mysql 5.7 but that askes Gitea read versions from database.

**Comment by silverwind** [comment]
I'm primarily looking to remove it from CI. We don't need to deliberatily go out of the way to break it for users unless there are valid reasons to do so.

**Comment by lunny** [comment]
Maybe we can have an announcement for that first and maybe 1.22 is a better version to remove mysql5.7 CI and new installation?

**Comment by yakob-aleksandrovich** [comment]
Is there already a roadmap for when support for MySQL 5.7 will be fully dropped? Which branch would that be? 
This would help me and various others in planning for an upgrade of our infrastructure.

**Comment by delvh** [comment]
…

`main`, since the instant we forked the `release/v1.21` branch.


So far, we haven't dropped MySQL 5.7 support.
If it happens, it will probably happen around or after the release of 1.21.0, but not before.

**Comment by silverwind** [comment]
Will likely happen in 1.22.

**Comment by delvh** [comment]
Yes, but the question was `when exactly is 'in 1.22'`.
The range ranges from now to feature freeze in three months…

**Comment by silverwind** [comment]
It shouldn't really matter. It will be a sort of soft-deprecation of support anyways, e.g. in theory 5.7 will still work in 1.22, we just don't actively test it anymore, and will start testing 8.0 and likely 8.1 instead.
