### ISSUE TITLE
File tree wrong icon offset

### ISSUE THREAD

**Issue by KN4CK3R** [go-gitea/gitea#25650]
### Description

The icon offset is different for files in dirs.

![grafik](https://github.com/go-gitea/gitea/assets/1666336/09215b4d-671e-4508-ae53-983a876bfd93)

It only occurs when zooming in, 110% in my tests.
[Example](https://gitea.com/xorm/xorm/pulls/2275/files)

**Comment by wxiaoguang** [comment]
That's a longstanding problem. I have spent a little time on it.

It's related to the path level (but not related to zoom level).



![image](https://github.com/go-gitea/gitea/assets/2114189/e19aca4e-77cc-4047-a230-b31a558f0273)

**Comment by silverwind** [comment]
IDK about this `display: grid`, but this case could may as well use `display: flex` with the link between icons with `flex: 1`.

**Comment by KN4CK3R** [comment]
> It's related to the path level (but not related to zoom level).

On my end it's related to the zoom level:

100%
![grafik](https://github.com/go-gitea/gitea/assets/1666336/4f45e5f7-de14-4f29-8803-c2f200c92ff1)

110%
![grafik](https://github.com/go-gitea/gitea/assets/1666336/63f90b1d-7339-4391-9e73-1965159504c9)

**Comment by wxiaoguang** [comment]
> > It's related to the path level (but not related to zoom level).
> 
> On my end it's related to the zoom level:

You can try to make some "deep" paths

**Comment by wxiaoguang** [comment]
->  Rewrite the DiffFileTreeItem and fix misalignment #26565
