### ISSUE TITLE
Search on the profile repositories page go wrong

### ISSUE THREAD

**Issue by starnakin** [go-gitea/gitea#25659]
### Description

Since the addition of the profile overview, when you search for a repository by name, you will be redirected to the profile overview. I believe the bug is caused by the recent update to the profile overview, as the repositories page is no longer the default page.

The correct URL should be: /{profile name}?tab=repositories&q=query. 
However, the current URL is: /{profile name}?q=query.

It's evident that this bug only exists on profiles with a profile page.

### Gitea Version

latest docker image

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

Docker

### Database

None

**Comment by delvh** [comment]
I think this has been fixed already with #25455
