### ISSUE TITLE
Creating PR defaults to comparison between master and the user's forked master

### ISSUE THREAD

**Issue by tobias--** [go-gitea/gitea#2565]
- Gitea version (or commit ref): 1.2.0+rc2
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant

## Description

The PR-Button (on original repo and on the forked repo) defaults to comparing master with {username}:master if the user has forked the repository (URL: .../{orgname}/{reponame}/compare/master...{username}:master). The right dropdown only shows the fork's branches, not the original repo's branches. However, the user might want create a pull request for a branch inside the original repo. This is possible by modifying the URL to .../compare/master...master

See:
- PR-Button. Only lists fork's branches: https://try.gitea.io/mainorg/mainrepo/compare/master...tobias--:master
- Lists only branches of mainorg/mainrepo: https://try.gitea.io/mainorg/mainrepo/compare/master...master 

I think all branches should be shown.

**Comment by tobias--** [comment]
Also: The PR-Button on mainorg/mainrepo https://try.gitea.io/mainorg/mainrepo/src/feature/branch-with-slash points to https://try.gitea.io/mainorg/mainrepo/compare/master...tobias--:feature/branch-with-slash  which actually should be https://try.gitea.io/mainorg/mainrepo/compare/master...feature/branch-with-slash because the branch only exists on mainorg/mainrepo and not on tobias--/mainrepo

**Comment by tobias--** [comment]
This issue seems to be resolved. The PR-Button on the main repo now points to mainorg/mainrepo/compare/master...mainrepo:master and the PR-Button on the fork points to mainorg/mainrepo/compare/master...{forkrepo}:master which in my opinion is a plausible behavior.

**Comment by lunny** [comment]
Please feel free to reopen it.
