### ISSUE TITLE
Gitlab migration: Migration fails when there are both issues and MRs in the repo

### ISSUE THREAD

**Issue by luna-duclos** [go-gitea/gitea#25674]
### Description

When migrating a gitlab repo to gitea, the migration will almost always fail if both MRs and issues are being migrated.
This is because gitlab assigns a seperate number sequence for each of them, so there is an issue 1, an MR 1, issue 2, MR 2, etc.

This doesn't work with gitea, which has a single number sequence for both and doesn't want them to overlap.

I sadly trashed my logs so I do not have them, my apologies :(
I will reproduce it on a test instance if necessary and provide them, please let me know if wanted.

### Gitea Version

1.9.3

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

gitea was being ran using the gitea helm charts found at https://gitea.com/gitea/helm-chart/

### Database

PostgreSQL

**Comment by hramrach** [comment]
This is #13884
