### ISSUE TITLE
database issue after updating

### ISSUE THREAD

**Issue by AntouanK** [go-gitea/gitea#2567]
- Gitea version (or commit ref):
- Git version: 
- Operating system: Linux arch (using docker containers)
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

After updating the docker images, I get this in the docker-compose logs

```
gitea_1     | 2017/09/21 15:13:08 [T] Custom path: /data/gitea
gitea_1     | 2017/09/21 15:13:08 [T] Log path: /data/gitea/log
postgres_1  | ERROR:  column "can_push" of relation "protected_branch" does not exist at character 31
postgres_1  | STATEMENT:  UPDATE "protected_branch" SET "can_push" = $1, "updated_unix" = $2 
...
```
It keeps repeating those 4 lines, and the web interface won't load.
Any ideas what's wrong?

Thanks

**Comment by daviian** [comment]
Unfortunately introduced with https://github.com/go-gitea/gitea/pull/2560

@lafriks PR https://github.com/go-gitea/gitea/pull/2451 dropped column `can_push`

**Comment by lafriks** [comment]
Oh, I thought it did not drop column. I will fix my migration just then to add it back

**Comment by AntouanK** [comment]
So how can I fix it?

**Comment by daviian** [comment]
@AntouanK @lafriks said he will change his migration to fix this.

As you updated to current master, I guess it isn't a productive system?

**Comment by AntouanK** [comment]
It's a server at home for my personal projects. But it's blocking all my repos now!
Should I revert to an older docker image manually?

**Comment by ghost** [comment]
I don't think that reverting to an older docker image will fix your issue. The can_push column in the protected_branch table has been deleted. I recreated the column in the database and now I have gitea running again with the latest docker image.

**Comment by AntouanK** [comment]
I just pulled the latest, and I still get those lines. ( and the web interface is not working )
```
gitea_1     | 2017/09/22 08:26:21 [T] Custom path: /data/gitea
gitea_1     | 2017/09/22 08:26:21 [T] Log path: /data/gitea/log
postgres_1  | ERROR:  column "can_push" of relation "protected_branch" does not exist at character 31
postgres_1  | STATEMENT:  UPDATE "protected_branch" SET "can_push" = $1, "updated_unix" = $2 
```

**Comment by daviian** [comment]
Like @nellonican said you have to create the `can_push` column manually afterwards as a temporary fix

**Comment by ghost** [comment]
@AntouanK What I did was:

Log in to my postgres database and give the following commands:

```bash
gitea-# \c gitea
gitea-# alter table protected_branch add column "can_push" boolean;
gitea-# \q
```
After that i had to do a `docker-compose down` and `docker-compose up -d`

**Comment by daviian** [comment]
@nellonican @AntouanK You should set the column to `NOT NULL DEFAULT false` as well

**Comment by ghost** [comment]
@daviian Thx. Will do.

**Comment by AntouanK** [comment]
I never used postgres, can you tell me how to log in?
I guess I can do `docker exec` on the running postgres container somehow to run those commands?

**Comment by ghost** [comment]
@AntouanK 
```bash
docker run -it --rm --link gitea_db_1:postgres postgres:alpine psql -postgres -U postgres
```
The `gitea_db_1` part should be the name of your docker container.

**Comment by AntouanK** [comment]
That didn't work for me.
Here's how I did it.

`docker exec -it gitea_postgres_1 /bin/bash` to get access to the postgres container.
`psql --username="dbuser" -d "giteadb"` to open that interactive shell.
then run `\c giteadb` and `alter table protected_branch add column "can_push" boolean;`

seems to be working now, thanks.

**Comment by ghost** [comment]
@AntouanK, as @daviian mentioned you should also do:
```bash
alter table protected_branch alter column "can_push" set DEFAULT false;
alter table protected_branch alter column "can_push" set NOT NULL;
```

**Comment by ToeiRei** [comment]
Same problem with my environment here (official docker image on MySQL) - thanks for the hint

**Comment by lunny** [comment]
@lafriks I think this needs a PR to fix.

**Comment by mmarif4u** [comment]
I was getting the same.
```bash
[...itea/routers/init.go:55 GlobalInit()] [E] Failed to initialize ORM engine: migrate: do migrate: Error 1054: Unknown column 'can_push' in 'field list'
```
The table(MySQL) hack from @nellonican fixed one issue:
```bash
Alter table protected_branch add column can_push boolean NOT NULL DEFAULT false;
```
Then hit by this one:
```bash
 [...els/issue_indexer.go:21 InitIssueIndexer()] [E] Unable to open issues indexer (indexers/issues.bleve). If the error is due to incompatible versions, try deleting the indexer files; gitea will recreate them with the appropriate version the next time it runs. Deleting the indexer files will not result in loss of data.
```
Have to delete `issues.bleve` dir inside indexers. And it starts normally afterwards.

**Comment by lafriks** [comment]
@mmarif4u issue with bleve index is known issue and #2524 fixes it
