### ISSUE TITLE
Fork Update Button

### ISSUE THREAD

**Issue by C-EO** [go-gitea/gitea#25679]
### Feature Description

I would love for Gitea to have an `Update Fork` button just like GitHub. This would not only make Gitea easier to use, but also bring in more users. I hate the fact that every single time I want to update my fork, I have to wait for the system-wide cron-job or puah the update myself.

## Button Preview

![image](https://github.com/go-gitea/gitea/assets/85847352/2fc31e0d-9765-4b22-9907-0e2dab154cf3)

## No need to sync changes because the fork is up-to-date

![image](https://github.com/go-gitea/gitea/assets/85847352/9dc941f1-407e-451c-9be9-954dcbd7a458)

## Need to sync changes and update fork

![image](https://github.com/go-gitea/gitea/assets/85847352/0c4d0b23-4553-4fde-8caa-cb0db68e6d21)

**Comment by hiifong** [comment]
duplicated with #23423
