### ISSUE TITLE
Adding SSH key fails with 'no armored data found'

### ISSUE THREAD

**Issue by ezplanet** [go-gitea/gitea#25676]
### Description

I have added SSH keys previously with success, but the last time was with versions likely prior to 1.17.
I have now upgraded to gitea 1.20 and this function no longer works.

To reproduce:
- On your workstation: 
1. generate an ssh key using ssh-keygen (no secret) which is saved automatically in ~/.ssh/id.rsa.pub

- On gitea web UI:
2. pull the user drop down menu and select 'Settings'
3. Select SSH / GPG Keys on the left pane, then press the button 'Add Key'
4. Copy the key previously generated and saved in id.rsa.pub and paste it in the 'Content' pane, then press the green button 'Add Key'

An error is returned on the top of the page:
"Cannot verify your GPG key: failed to parse gpg key openpgp: invalid argument: no armored data found"

### Gitea Version

1.20

### Can you reproduce the bug on the Gitea demo site?

I cannot register to the demo site because your captcha verification fails every time. I am definitely human and I can recognize buildings and animals with spectacles :-)

### Git Version

2.34.1 

### Operating System

Ubuntu Server 22.04.2 LTS

### How are you running Gitea?

I am running the downloaded binary

### Database

MySQL

**Comment by wxiaoguang** [comment]
I guess you went to a wrong panel. The message says "Cannot verify your GPG key". You need to click the "Add key" in the "SSH" panel.

**Comment by ezplanet** [comment]
This is the panel, as you can see my other keys are loaded:
<img width="1237" alt="Screenshot 2023-07-07 at 23 36 27" src="https://github.com/go-gitea/gitea/assets/23197153/46e3acbc-fa40-4546-a782-9cd8207c9a53">

**Comment by ezplanet** [comment]
The page is correct, however I have just noticed that 'Add Key' button on the top of the page is for SSH keys, whilst 'Add Key' button at the bottom of the page is for GPG keys. The UI is confusing.
