### ISSUE TITLE
Action workflows navbar UI has two empty items

### ISSUE THREAD

**Issue by hiifong** [go-gitea/gitea#25671]
### Description

as title
![image](https://github.com/go-gitea/gitea/assets/89133723/4677cc25-48f0-479b-845f-185fe2f1f6d0)

### Gitea Version

v1.20+

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

./gitea web

### Database

None

**Comment by silverwind** [comment]
Will be fixed in https://github.com/go-gitea/gitea/pull/25601
