### ISSUE TITLE
Name change

### ISSUE THREAD

**Issue by C-EO** [go-gitea/gitea#25683]
### Description

I have tried to change the name of my repo under an organization and Gitea keeps telling me `The repository name is already used.` I have tried checking for an available repo using the URL, but it returns the 404 page.

Is it a problem with the DB I'm using or?
( I use MySQL from Planetscale)

### Gitea Version

1.21.0+dev-215-gff140d405

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/85847352/eb0d070b-0c56-4be1-ac5c-41a6eec7fc7a)

![image](https://github.com/go-gitea/gitea/assets/85847352/71a22447-8647-4f53-b500-0d4d1c0ebb30)

https://github.com/go-gitea/gitea/assets/85847352/83b9e971-6fe9-4fb8-ad8b-c8e7d7aaafe5

### Git Version

2.33.1, Wire Protocol Version 2 Enabled

### Operating System

linux 5.19.0-1026-gcp

### How are you running Gitea?

I'm using a binary download from [here](https://dl.gitea.com/gitea/main/gitea-main-nightly-linux-amd64). I' running Gitea from the command-line with a GUI.

### Database

MySQL

**Comment by silverwind** [comment]
Maybe this is because there was a previous repo with that name. I do recall we keep some info on renamed repos in the database to be able to redirect the name after a rename. If this blocks the creation, it's a bug.

**Comment by yp05327** [comment]
Maybe there's previous data in `data/gitea-reposiroties/imperialbot/musicbot.git`

**Comment by C-EO** [comment]
None exists there

**Comment by C-EO** [comment]
Found it. After reloading the system I found it.

But one question though, which cron-job is supposed to delete empty repos?

I ran all of them but it wasn't until I deleted the `musicbot.git` myself that I could get to rename.

**Comment by denyskon** [comment]
Is this issue solved?

**Comment by silverwind** [comment]
At least the original issue seems to have turned out invalid.
