### ISSUE TITLE
Show tasks even when actions are disabled

### ISSUE THREAD

**Issue by ExplodingDragon** [go-gitea/gitea#25728]
### Description

Show tasks even when actions are disabled

link: https://packages.d7z.net/git-mirrors/yq

### Gitea Version

main

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/33776693/9879f9d4-9e49-433f-93d7-2173afa34f35)

### How are you running Gitea?

systemd

### Database

None

**Comment by lunny** [comment]
This is not a bug. The commit status is a feature to integrate with internal and external CI/CD service not an actions internal feature.
