### ISSUE TITLE
Unable to upgrade to 1.19.4 as upgrade script still sees 1.19.3

### ISSUE THREAD

**Issue by brianread108** [go-gitea/gitea#25747]
### Description

Using the upgrade.sh script to upgrade to 1.19.4, but it tells me that the current version is 1.19.3!

`Gitea is running. Continuing with rest of script...
Latest available version is 1.19.3
Checking currently installed version...
1.19.3 is already installed, stopping.
`

### Gitea Version

1.19.3

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

2.30.2

### Operating System

Container under proxmox

### How are you running Gitea?

Turnkey gitea container.

### Database

MySQL

**Comment by silverwind** [comment]
Likely because https://dl.gitea.com/gitea/version.json was not updated.

**Comment by brianread108** [comment]
Specifiying the version "-v 1.91.4" works though.
