### ISSUE TITLE
Padding for Clone Options button

### ISSUE THREAD

**Issue by C-EO** [go-gitea/gitea#25758]
### Description

Described in heading.

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/85847352/3af92b78-36d9-433c-b915-2ce7185a9542)

### Gitea Version

1.21.0+dev-242-ga6a9389c7

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

linux 5.19.0-1026-gcp

### Browser Version

Microsoft Edge 114.0.1823.67 (Official build) (64-bit)

**Comment by delvh** [comment]
Responsible element/ CSS rule: 
![grafik](https://github.com/go-gitea/gitea/assets/51889757/205980fe-59f6-4760-86ea-305ffdb2b0eb)
Apparently, no one expected that there is a matching button without a triangle icon.

**Comment by wxiaoguang** [comment]
Oops, I didn't notice this issue in the firs time. Thank you for linking the PR with it.
