### ISSUE TITLE
Non-sense "You pushed on branch ...." notification

### ISSUE THREAD

**Issue by wxiaoguang** [go-gitea/gitea#25778]
### Description

Reproduce step:

1. Create a branch
2. Create a PR
3. Merge the PR
4. Go to the repo home

Now, these 2 notifications are non-sense.

* [x] For "main" branch: yes, it is changed.
* [ ] For "root-patch-1": it has been merged.
 
![image](https://github.com/go-gitea/gitea/assets/2114189/da3da3be-80b1-472c-bfa1-3be2dd265da5)

### Gitea Version

1.21

**Comment by silverwind** [comment]
Default branch should never notify imho.

**Comment by hiifong** [comment]
> Default branch should never notify imho.

agree

**Comment by sh7dm** [comment]
I want to work on this. If I won't submit a fix within a week, consider the task free again

**Comment by wxiaoguang** [comment]
Close because I am not tracking this problem, maybe some have been fixed.
