### ISSUE TITLE
Cannot edit in WebEditor, keeps showing loading

### ISSUE THREAD

**Issue by sinsky** [go-gitea/gitea#25770]
### Description

When I try to create a new file or edit a file in the web editor, the web editor screen remains loading.

Reference.
This is not happening with version 1.19.3 that I am self-hosting.

### Gitea Version

1.21.0+dev-254-g2ff0c12a9 

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

<img width="1484" alt="スクリーンショット 2023-07-08 23 11 58" src="https://github.com/go-gitea/gitea/assets/60662802/be9781e8-3cf4-40a3-bc55-d5feb61e369f">
<img width="1645" alt="スクリーンショット 2023-07-08 23 17 39" src="https://github.com/go-gitea/gitea/assets/60662802/6defb62f-72f1-4879-8999-bcb5d82654e7">

### How are you running Gitea?

use https://try.gitea.io

### Database

None

**Comment by puni9869** [comment]
It is working fine. https://try.git.io is a dev server with low configuration. You can try the prod server https://gitea.com/user/sign_up

**Comment by wxiaoguang** [comment]
It's a regression of  Minify CSS with Lightning CSS #25754 

Before: `--color-code-bg: #ffffff;`

After: `--color-code-bg: #fff;`, but the editor doesn't like `#fff` color.

**Comment by sinsky** [comment]
Thanks for the reply. I did confirm that it works fine on gitea.com.
But just to be sure, I tried it in my local environment and got the same phenomenon.

@wxiaoguang Thank you for finding out the cause of the problem!
I have confirmed that I can edit the theme in User settings if I manipulate it with arc-green!

**Comment by wxiaoguang** [comment]
If you need to follow the main branch, you can revert the #25754  in your build (it's quite small) and try.

**Comment by puni9869** [comment]
> If you need to follow the main branch, you can revert the #25754 in your build (it's quite small) and try.

Shall we also revert the #25754 from main branch

**Comment by wxiaoguang** [comment]
No hurry, if it is the case, I think there could still be some solutions:

1. revert
2. fine tune options to keep `#ffffff`
3. do some special fixes for the editor's `getProp`

**Comment by delvh** [comment]
@silverwind

**Comment by silverwind** [comment]
Need to check but I assume we could just the color to 6-digit format for Monaco if it only accepts that, there might be a function for it existing already.
