### ISSUE TITLE
PANIC whilst trying to do migrate task: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by scruel** [go-gitea/gitea#25793]
### Description

I want to migrate repositories with related info like issues, pull requests, etc.
Tried once with the following settings:
![image](https://github.com/go-gitea/gitea/assets/16933298/80174998-d6da-4d88-9f9c-4b2ba4a75537)
But what I got is:
![image](https://github.com/go-gitea/gitea/assets/16933298/9fc91081-3828-4fcf-bbff-ea4768c6e413)
For debug purpose, you can check:
![image](https://github.com/go-gitea/gitea/assets/16933298/13f878e5-fe83-474a-841c-8ca829456460)
![image](https://github.com/go-gitea/gitea/assets/16933298/18d5b7f8-c72b-4870-a5c0-a9e23849ac5c)

### Gitea Version

1.20.0+rc0 built with GNU Make 4.4.1, go1.20.5 : bindata, timetzdata, sqlite, sqlite_unlock_notify

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

Got another issue on your Gitea demo site:
![image](https://github.com/go-gitea/gitea/assets/16933298/fe6280d6-b390-4b53-8cef-9b020762587a)
![image](https://github.com/go-gitea/gitea/assets/16933298/d5f6e68c-e0a5-4f4d-8dbf-a79fecb6755c)

### Git Version

2.40.1

### Operating System

Synology DSM7.2

### How are you running Gitea?

From docker image

### Database

SQLite

**Comment by hiifong** [comment]
the repo is public, don't need a Access token

**Comment by scruel** [comment]
> the repo is public, don't need a Access token，please retry without Access token

What about the rate limit?

**Comment by hiifong** [comment]
> > the repo is public, don't need a Access token，please retry without Access token
> 
> What about the rate limit? Also, the access token is required for selecting "Migration Items" options:
> ![image](https://github.com/go-gitea/gitea/assets/16933298/f1710930-526f-4b3f-8b4d-cc22635ad416)
> 

And do you have the relevant permissions for this repository?

**Comment by scruel** [comment]
> And do you have the relevant permissions for this repository?

No, I just want to mirror the repo, with all related items also.

**Comment by hiifong** [comment]
QQ Group:328432459

**Comment by hiifong** [comment]
> > And do you have the relevant permissions for this repository?
> 
> No, I just want to mirror the repo, with all related items also.

Do not enter the Access token

**Comment by scruel** [comment]
> > > And do you have the relevant permissions for this repository?
> > 
> > 
> > No, I just want to mirror the repo, with all related items also.
> 
> Do not enter the Access token

Hmm, you just reset the conversation back to https://github.com/go-gitea/gitea/issues/25793#issuecomment-1628031754...

**Comment by hiifong** [comment]
sorry

**Comment by hiifong** [comment]
> > And do you have the relevant permissions for this repository?
> 
> No, I just want to mirror the repo, with all related items also.

Don't pick the issue
