### ISSUE TITLE
500 error while trying to access any repository.

### ISSUE THREAD

**Issue by rubenelshof** [go-gitea/gitea#25805]
### Description

In the web ui while logged in I get a 500 error when trying to access any repository.
```
GetRecentlyPushedBranches, Error 1267 (HY000): Illegal mix of collations (utf8mb4_general_ci,IMPLICIT) and (utf8mb4_unicode_ci,IMPLICIT) for operation '='
```

The repositories that are public are accessible while logged out.

### Gitea Version

1.21.0+dev-266-gfa0b5b14c

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/15641671/c2e431d2-1504-406b-96d3-a948cf2fc058)

### How are you running Gitea?

Docker

### Database

MySQL

**Comment by lunny** [comment]
Please ensure columns in your MySQL have the same collation, either `utf8mb4_general_ci` or `utf8mb4_unicode_ci`.

**Comment by rubenelshof** [comment]
> Please ensure columns in your MySQL have the same collation, either `utf8mb4_general_ci` or `utf8mb4_unicode_ci`.

Converting collation to `utf8mb4_unicode_ci` fixed the issue.
Thank you.
