### ISSUE TITLE
Gitea Actions environment variables: GITHUB_REF_NAME and GITHUB_REF_TYPE is wrong

### ISSUE THREAD

**Issue by noetzold** [go-gitea/gitea#25816]
### Description

GITHUB_REF is "refs/heads/master"
that is OK, but 
GITHUB_REF_NAME is "refs/heads/master" it
Should only be "master"

GITHUB_REF_TYPE should "branch" or "tag" but is "heads"
See: https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables

I’m using a PowerShell runner but should make no difference

```
      - name: test
        run: |
              Write-Output "GITHUB_REF_NAME $Env:GITHUB_REF_NAME"
              Write-Output "GITHUB_REF $Env:GITHUB_REF"
              Write-Output "GITHUB_REF_TYPE $Env:GITHUB_REF_TYPE"
```

![image](https://github.com/go-gitea/gitea/assets/36108512/b8b276a2-96ab-46a0-bd05-a559f4372e71)

### Gitea Version

1.20.0+rc0 

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

Runs from Docker

### Database

None

**Comment by lunny** [comment]
This has been fixed by #25367
