### ISSUE TITLE
Gitea database Environment Variable: 'GITEA__database__SSL_MODE' not reading from environment.

### ISSUE THREAD

**Issue by jordanrbaker** [go-gitea/gitea#25817]
### Description

I am currently writing out deployment code (Bicep) to push out a multi-tier Gitea install in Azure using a container instance for the webserver and a postgres flexi server for the database.

I've defined my environment variables, and after running my deployment everything works as expected other than the SSL_MODE variable, which does not apply (it stays as disabled).

Reproduction Steps:

Define Environment Variable in Bicep Code:

``` 
            {
              name: 'GITEA__database__SSL_MODE'
              value: 'require'
            } 
```
Referencing the cheat sheet here to pull the config value: https://docs.gitea.com/next/administration/config-cheat-sheet#database-database.

Check deployment to validate container deployed with variable successfully:

![image](https://github.com/go-gitea/gitea/assets/66644533/16c3b56f-49f4-49e9-ad7c-379135435f9f)

Navigate to web UI - SSL mode is not set to require:

![image](https://github.com/go-gitea/gitea/assets/66644533/bc16ca16-e4fe-4b7e-99d0-6fd1304460e6)

### Gitea Version

1.20.0+rc0

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

See descriptions.

### Operating System

Linux

### How are you running Gitea?

Pulling directly from dockerhub, gitea/gitea:latest.

### Database

PostgreSQL

**Comment by wxiaoguang** [comment]
Please use 1.20 nightly

**Comment by wxiaoguang** [comment]
-> Show correct SSL Mode on "install page" #25818
