### ISSUE TITLE
add/create a tag based on commit in Web UI. 

### ISSUE THREAD

**Issue by chenx319** [go-gitea/gitea#25815]
### Feature Description

I am using gitea 1.16 ,
I cannot add/create a tag based on a commit.

I only create a tag based create a release in Web UI 
or create a tag in local then push to remote.

Is it possible to create a tag based on commit in web UI directly?

**Comment by JakobDev** [comment]
The latest Version is 1.19. You should update before making a report.

**Comment by silverwind** [comment]
This is possible in 1.20 at least, I think also in 1.19.

<img width="247" alt="image" src="https://github.com/go-gitea/gitea/assets/115237/6cd1e1bb-1141-4e9d-b9bb-a9d852ba1898">
