### ISSUE TITLE
Issue dependencies without user rights

### ISSUE THREAD

**Issue by bauermarkus** [go-gitea/gitea#25837]
### Description

When I create more than one dependence, I am not allowed to view the issue through the other issue. 

Maybe this is an intended feature, but if, I don't understand this

Side note: I am using a German version, the pop up is using English

### Gitea Version

1.20.0-rc1

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/42841227/1fbdcf8e-c4d9-42ca-9e47-15a2336725b7)

### How are you running Gitea?

Docker

### Database

SQLite

**Comment by lunny** [comment]
The languages' switching because maybe the german hasn't translate this string.

**Comment by bauermarkus** [comment]
@lunny I guess so too, that's why it's just a side note

Is the rest a bug or intended behaviour?

**Comment by lunny** [comment]
I think it's not a bug but an edge problem and no ideal resolution to fix it currently. Assume you are a plain user of this repository and issue but this issue depends on another private repository's issue but you have no permission but some others have the permissions to that dependencies issues.

**Comment by Gr3q** [comment]
I have the same issue, it doesn't matter in which order only the first dependency is not locked, the rest are. I can access all dependencies just fine, they are in the same repo.

If I would add these dependencies in a different order and a different PR would end up in first place that would not be locked either.

Also ignoring the obvious css issue.

![image](https://github.com/go-gitea/gitea/assets/22377521/5ff696ed-554f-4979-98fe-5df5e7e8258e)

**Comment by Renari** [comment]
This is most certainly a bug, considering you can just go to the issues tab of the same repository and see the issues that are locked. Furthermore if you have multiple issues blocked by a single other issue it will only show a single entry of the list of issues blocking it.

**Comment by bauermarkus** [comment]
I would like to have it classified as a bug, as it is really annoying and brings the feature to almost uselessness
