### ISSUE TITLE
UI: programming language highlight wrong keyword

### ISSUE THREAD

**Issue by Bisstocuz** [go-gitea/gitea#25848]
### Description

I check some TypeScript code in code review page, some keywords in variable names like `module` or `var` will be highlight improperly.

### Gitea Version

1.19.4

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

![8531900266c388fd3fe81315844f88e2](https://github.com/go-gitea/gitea/assets/42398278/cfc5a283-4fa6-4a5e-8a17-52c2f6c6f920)

### How are you running Gitea?

docker-compose

### Database

MySQL

**Comment by wxiaoguang** [comment]
It's an upstream bug

https://swapoff.org/chroma/playground/

![image](https://github.com/go-gitea/gitea/assets/2114189/5e6210da-2593-47a0-9bcb-104c8f7a2a07)

**Comment by puni9869** [comment]
Bisstocuz thanks for opening a issue.

👀

**Comment by silverwind** [comment]
Don't think we need to keep every upstream issue open.
