### ISSUE TITLE
Deprecate Go module github.com/go-gitea/gitea

### ISSUE THREAD

**Issue by hickford** [go-gitea/gitea#25862]
### Feature Description

https://pkg.go.dev/github.com/go-gitea/gitea hosts a very old version of Gitea v1.8.3 published 2019 (tag https://github.com/go-gitea/gitea/tree/v1.8.3)

This is confusing. Best would be to deprecate this module and link to maintained module https://pkg.go.dev/code.gitea.io/gitea

instructions in https://go.dev/ref/mod though it assumes the module already has a go.mod file

example of deprecated module https://pkg.go.dev/github.com/golang/protobuf with helpful warning on top

**Comment by wolfogre** [comment]
It's not easy. Unlike `github.com/golang/protobuf` -> `google.golang.org/protobuf`(`github.com/protocolbuffers/protobuf-go`), Gitea didn't move to a new repository; it just renamed the module name.

That means if we want to get a deprecation warning on go.dev, we have to update the `go.mod` file on the `release/v1.8` branch and release `v1.8.4`. That's too weird for now. Unfortunately, there's no `go.mod` file on `release/v1.18`; it used dep with `Gopkg.toml`.

Actually, Gitea is designed as an application, not a package, it doesn't really matter what go.dev has done with it.
