### ISSUE TITLE
Wrong closer reference in issues

### ISSUE THREAD

**Issue by KazzmanK** [go-gitea/gitea#25869]
### Description
In Organization, 
I have an issue, closed by my colleague
![image](https://github.com/go-gitea/gitea/assets/13328513/54c75a64-24b3-42bf-84a0-bbd28c5f4140)
But in Issues list this issue marked as closed by ~~me~~ issue author, not ~~my colleague~~ user who actually closed issue.
![image](https://github.com/go-gitea/gitea/assets/13328513/aa147ee4-dcb8-49d0-bfbe-41ccac70fff0)

### Gitea Version

1.19.4

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

windows as servie

### Database

SQLite

**Comment by KazzmanK** [comment]
It looks like Author is mentioned as a person who closed issue instead of one who really closed it.

**Comment by KN4CK3R** [comment]
The issue list just shows who created the issue and that it is closed. It does not show the closer.

**Comment by KazzmanK** [comment]
Ok, I see. Sorry for misunderstanding.
We have a group of two - developer and tester.
Tester AND developer create issues, both tester AND developer able to close issues, but tester have to verify outcome.
Idea was to list issues by "closed by developer" and double check them.

What we supposed to do now?  Create a label "Completted by developer" and allow close issues by tester only?

**Comment by lunny** [comment]
I think you can do that. Add a `done` label for developers, and close button for testers when they confirmed.

**Comment by KazzmanK** [comment]
Teach me how to set permissions for Close Issue in case we use organization and teams approach.

**Comment by KazzmanK** [comment]
Should I close this issue and open a new one with request to make it possible to control who can close issues?

**Comment by KazzmanK** [comment]
Close this issue, another opened
https://github.com/go-gitea/gitea/issues/26014
