### ISSUE TITLE
Branch name escape problem

### ISSUE THREAD

**Issue by yp05327** [go-gitea/gitea#25865]
### Description

Related: #25830

- https://github.com/go-gitea/gitea/pull/25812#discussion_r1262140690
This is the right link:
https://try.gitea.io/yp05327/testrepo/src/branch/test%2311

- https://github.com/go-gitea/gitea/issues/25830#issuecomment-1634050628

### Gitea Version

latest

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

build

### Database

None

**Comment by puni9869** [comment]
Thanks for summarizing it in short.
You are correct about Github.

**Comment by silverwind** [comment]
I don't get it. What is wrong on https://try.gitea.io/yp05327/testrepo/src/branch/test%2311?

**Comment by puni9869** [comment]
Thats the correct url for `test#11` branch. Nothing wrong with it.

**Comment by yp05327** [comment]
> I don't get it. What is wrong on https://try.gitea.io/yp05327/testrepo/src/branch/test%2311?

After access this link, you can select this branch again in the selector.
Then the url will become https://try.gitea.io/yp05327/testrepo/src/branch/test#11
