### ISSUE TITLE
Create org permissions of user created via cli client

### ISSUE THREAD

**Issue by nbenn** [go-gitea/gitea#25898]
### Description

With (default) settings as

```
[admin]
DISABLE_REGULAR_ORG_CREATION = false

[service]
DEFAULT_ALLOW_CREATE_ORGANIZATION = true
```

a user created via `gitea admin user create` does not have "create org" permissions. If it is intentional that the CLI client does not respect the relevant settings, it might be helpful to add an option to the CLI client.

### Gitea Version

1.19.0

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/nbenn/f4cf2314da1cc32d8d5325b9a0e9cbe3

### How are you running Gitea?

Docker: gitea/gitea:1.19.0

### Database

SQLite

**Comment by cassiozareck** [comment]
Thanks for sharing this issue

**Comment by lunny** [comment]
Maybe caused by #25330

**Comment by wxiaoguang** [comment]
> Maybe caused by #25330

No, it's not related IMO.

Before  #25330, `func Init(opts *Options) {` also only called `loadCommonSettingsFrom`, the settings were never fully loaded.


After #25330, the `loadCommonSettingsFrom` is also called, so it's not related.

**Comment by stevapple** [comment]
I met the same problem with LDAP users.

**Comment by lunny** [comment]
I can see what happened. The `loadCommonSettingsFrom` will be loaded but `loadServiceFrom` will not be included. And `DEFAULT_ALLOW_CREATE_ORGANIZATION = true` hasn't been loaded.

<img width="496" alt="图片" src="https://github.com/user-attachments/assets/7a785c08-a0f4-4ded-8305-de7a260b1836" />
