### ISSUE TITLE
500 Internal server error on signin page. 

### ISSUE THREAD

**Issue by zillani** [go-gitea/gitea#25891]
### Description

When we click on sign-in in gitea, we receive 500 internal server error & below is the log. Gitea is set o run in dev mode with debug logs enabled. 

gitea is on 1.18.1 version.

```
Render failed: template: user/auth/signin_inner:64:26: executing "user/auth/signin_inner" at <$provider.DisplayName>: nil pointer evaluating oauth2.Provider.DisplayName
2023/07/14 07:22:31 [64b0f7b7] router: completed GET /user/login for [fd00:101::94d1]:36554, 500 Internal Server Error in 10.2ms
```

### Gitea Version

1.18.1

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

redhat 8

### How are you running Gitea?

installed as helm chart on kubernetes 1.25

### Database

PostgreSQL

**Comment by lunny** [comment]
Please upgrade your Gitea to v1.19.4 and try the page again.

**Comment by zillani** [comment]
> Please upgrade your Gitea to v1.19.4 and try the page again.

Thanks for quick reply, let me upgrade & check.

**Comment by wxiaoguang** [comment]
No more feedback, I think this issue can be closed, feel free to reopen if there are more clues.
