### ISSUE TITLE
Unable to migrate repos with duplicate case-different tags

### ISSUE THREAD

**Issue by silverwind** [go-gitea/gitea#25909]
### Description

1. Create new migration from https://github.com/pytorch/pytorch, does not matter whether mirror or not.

After some time, it will error:

```
2023/07/16 18:19:53 ...ices/task/migrate.go:60:func1() [E] runMigrateTask[6] by DoerID[1] to RepoID[47] for OwnerID[1] failed: SyncRepoBranchesWithRepo: Error 1062 (23000): Duplicate entry '47-update-test-distribute' for key 'UQE_branch_s'
2023/07/16 18:19:53 ...ervices/task/task.go:51:handler() [E] Run task failed: SyncRepoBranchesWithRepo: Error 1062 (23000): Duplicate entry '47-update-test-distribute' for key 'UQE_branch_s'
```

<img width="909" alt="image" src="https://github.com/go-gitea/gitea/assets/115237/c8245898-2970-4843-8022-2e1f5826cb36">

Likely regression from https://github.com/go-gitea/gitea/pull/22743

### Gitea Version

main

### Database

```
mysqld  Ver 11.0.2-MariaDB for osx10.18 on x86_64 (Homebrew)
```

**Comment by wxiaoguang** [comment]
This one, but stale:

 Convert branch table name column to a new collation for mysql/mssql to support case sensitive because branch names are case sensitive #25623

**Comment by silverwind** [comment]
Indeed, the repo has two branches with same name but different case:

<img width="375" alt="image" src="https://github.com/go-gitea/gitea/assets/115237/6142ba03-d880-43a2-8a69-ddf54738fc77">

**Comment by wxiaoguang** [comment]
There is a workaround in #28131
