### ISSUE TITLE
Add search to all the texts in the repository

### ISSUE THREAD

**Issue by laoshaw** [go-gitea/gitea#2591]
can I search code/markdown-text/wiki content globally , per organization, per repo? with more repos used in gitea this becomes essential to the work flow. this probably involves a cron-job at the backend to build the index for quick grep, probably ctags or some golang search project can be used for that?

**Comment by lafriks** [comment]
Such feature is already requested in #1102 and per repository code search already being worked on in PR #2582

**Comment by lunny** [comment]
Since #2582 merged, close this one.
