### ISSUE TITLE
Actions fail and nltimeout

### ISSUE THREAD

**Issue by wayneconnolly** [go-gitea/gitea#25916]
### Description

![Screenshot_20230717_142617_Brave](https://github.com/go-gitea/gitea/assets/4142087/dd168128-af3f-4cba-9511-cd0775b38d80)
My actions succeed as designed but the final complete step fails and I don't understand why.

No message appears to show why.

### Gitea Version

1.20.0+rc0

### Can you reproduce the bug on the Gitea demo site?

Yes

### Git Version

1.20.0+rc0

### Operating System

Linux

### How are you running Gitea?

Docker-compose 

### Database

SQLite

**Comment by techknowlogick** [comment]
> 1.20.0+rc0

Are you able to upgrade to the latest stable version (atm it's 1.20.0, it's just been released yesterday so no worries that you haven't upgraded to it yet).

As well, which version of act_runner are you using?

**Comment by wayneconnolly** [comment]
I can't upgrade as it gives the error

``` 
Received signal 15; terminating.
Server listening on :: port 22.
Server listening on 0.0.0.0 port 22.
2023/07/17 20:28:37 ...g/config_provider.go:327:deprecatedSettingFatal() [F] Deprecated fallback `[server]` 
```

As I've observed - once you move off a release you are forever stuck on candidates and there is no way to move towards stable. Maybe someone has a trick?

Act_runners: Latest.

**Comment by wayneconnolly** [comment]
Ok - i found the fix for that. I've upgrade.

**Comment by earl-warren** [comment]
> Ok - i found the fix for that. I've upgrade.

What fix did you find?

**Comment by wayneconnolly** [comment]
![image](https://github.com/go-gitea/gitea/assets/4142087/5fd56f40-9dae-44a3-a6e2-90607d96a3b7)
It's all working now -wonderful!!! 

> > Ok - i found the fix for that. I've upgrade.
> 
> What fix did you find?

Edit gitea/conf/app.ini

Delete from the server block
`LFS_CONTENT_PATH=/data/git/lfs`
and add 

```
[lfs]
PATH=/data/git/lfs
```

Then refresh the page- no server restart required.
