### ISSUE TITLE
New cron.* maintenance to cleanup action job/run/task tables

### ISSUE THREAD

**Issue by nicorac** [go-gitea/gitea#25923]
### Feature Description

I'm testing the new Gitea Actions feature (I know, it's still a preview, but it works great for me...) and I've filled up Actions log with hundreds of (now useless) test runs.
I see there's no way to cleanup them other than straight access to DB.

The existing `cron.delete_old_actions` only deletes repo user actions (like pushes, issue close, ...) but does not cleanup the CI/CD Actions log.

Should be great to have a new maintenance job to cleanup `actions_job`, `actions_run` and `action_task` tables as like as the existing `cron.delete_old_actions` maintenance task cleans up the `actions` table.

I think there's no need to keep that history forever, at least in small & personal Gitea instances.

An alternative could be to extend the existing `cron.delete_old_actions` task to cleanup those tables too, maybe with different run parameters.

**Comment by wolfogre** [comment]
I think it's duplicated with #24256.
