### ISSUE TITLE
Not readable style

### ISSUE THREAD

**Issue by somera** [go-gitea/gitea#25939]
### Description

The new style is so compact, that the table is not readable.

I would say, that the ID column is not needed.

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/8334250/ed55d949-c91a-4a47-93ee-26cc8c041c6d)

![image](https://github.com/go-gitea/gitea/assets/8334250/a9845b12-124d-419d-8f5d-a1f16e401eff)

### Gitea Version

1.20.0

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

Ubuntu 20.04.4

### Browser Version

Chrome

**Comment by somera** [comment]
This ist the old style.
![image](https://github.com/go-gitea/gitea/assets/8334250/b6ac8f50-f909-4763-9c3f-6243d4b4b18f)
You can read the content in the table better.

**Comment by KazzmanK** [comment]
For such a request it may be sufficient to make left pane be collapsible under hamburger menu.

**Comment by silverwind** [comment]
This was https://github.com/go-gitea/gitea/pull/25568. Could maybe increase horizontal padding by like 1-2px, but I wouldn't do more.

**Comment by KN4CK3R** [comment]
Maybe we could drop some columns like `Beobachtungen` as they are not really relevant in the admin context.

**Comment by somera** [comment]
@KN4CK3R I would say all 3 columns
![image](https://github.com/go-gitea/gitea/assets/8334250/811d9da1-3950-4db7-9975-70ba7da0172c)
are not so important in this view.

**Comment by denyskon** [comment]
Maybe we should make a separate page with iser details to move stuff out of the table

**Comment by lunny** [comment]
Group the numbers columns as 1 column if they are not sortable columns.

**Comment by somera** [comment]
I checked the whole new UI and I'm not so happy with mowing the navigation to the left size. When you will extend the table size to WQHD, than it will look better. But the compressend width is not good. Sorry, this was wrong UI change.

**Comment by denyskon** [comment]
Regardless of the navigation, I think we need to simplify these tables.

**Comment by somera** [comment]
But you have to fix all tables.

![image](https://github.com/go-gitea/gitea/assets/8334250/261850b1-1567-4502-ba6b-0e520391a985)

![image](https://github.com/go-gitea/gitea/assets/8334250/4a8e904d-75bd-476a-9ea3-5522b4320894)

![image](https://github.com/go-gitea/gitea/assets/8334250/8bb8ce75-7216-461a-ae6a-6bd73c9a2fef)

**Comment by lunny** [comment]
The width of admin page could be extended like code review pages.

**Comment by denyskon** [comment]
Also needed for at least repo list

**Comment by denyskon** [comment]
Reopening, because org and repo details can still be moved out to separate pages

**Comment by lunny** [comment]
I think the UI problem mentioned in this issue has been resolved. So I will move this issue to another milestone.

**Comment by somera** [comment]
> I think the UI problem mentioned in this issue has been resolved. So I will move this issue to another milestone.

There are a few small improvements. But it's not "perfect".

Sorted by size
![image](https://github.com/go-gitea/gitea/assets/8334250/d9c459e0-f0e5-42ac-8bf8-8a57c9b396b8)

Sorted by name
![image](https://github.com/go-gitea/gitea/assets/8334250/a4fecc8f-1a2d-460d-a550-764876ed3b5a)

Date should be in one line. And the repo size.

**Comment by lunny** [comment]
#29581 hasn't been backport to v1.21

**Comment by somera** [comment]
I checked it with 1.22.2 and it looks good.
