### ISSUE TITLE
gitea --help fails

### ISSUE THREAD

**Issue by remram44** [go-gitea/gitea#25938]
### Description

Running `gitea --help` will fail to show the help message if I don't have write permissions to the folder:

```
$ /opt/gitea --help
2023/07/17 14:00:02 ...s/setting/setting.go:109:LoadCommonSettings() [F] Unable to load settings from config: unable to create chunked upload directory: /opt/data/tmp/package-upload (mkdir /opt/data: permission denied)
```

### Gitea Version

1.20.0

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

2.25.1

### Operating System

Linux amd64 (Ubuntu 20.04)

### How are you running Gitea?

Downloaded the official binary

### Database

None

**Comment by remram44** [comment]
A workaround is to set `GITEA_WORK_DIR`, for example:

```
$ GITEA_WORK_DIR=/tmp/test-gitea /opt/gitea --help
```

This will work, but will also create the folders `/tmp/test-gitea/data/tmp/package-upload`, which seems wrong for just running `--help`...?

**Comment by wxiaoguang** [comment]
I also noticed that there is a `package-upload` in my work-path .... Will fix it
