### ISSUE TITLE
User can see repositories they don't have access to

### ISSUE THREAD

**Issue by kolaente** [go-gitea/gitea#2593]
- Gitea version (or commit ref): 1.2.0+rc1 (Official Docker Container)
- Git version: 2.11.3
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

I created a Team who's members only have access to issues and wiki. When I logged in with a member of this team, i could still see all private repositories of the organisation the user is part of (but not access them, got a 404)  in the repository list to the right on the startpage. Don'T know if this is intended, seems like a bug.

**Comment by daviian** [comment]
Related to #2562, #2399 and #1794
