### ISSUE TITLE
Menu bar background color not following themes

### ISSUE THREAD

**Issue by TheNonexistent** [go-gitea/gitea#25930]
### Description

The top menu bar does not follow the color scheme of the selected theme, the css variable `--color-nav-bg` is always provided by `index.css` and overrides any changes the theme makes.
 
Even when manually setting the `--color-nav-bg` variable inside the theme-<>.css, the variable is stripped from the final file served to the browser.

The default dark theme(arc-green) works as expected as it provides a `--color-nav-bg` variable.

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/12313295/145e36b5-86f8-4ceb-beb1-20c57ad7fe70)
![image](https://github.com/go-gitea/gitea/assets/12313295/53202aaf-15fa-4ea2-b4b4-e70e79c6c80b)

### Gitea Version

1.20.0  on docker

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

Debian Linux (Firefox and Chrome browsers)

### Browser Version

Firefox 115.0.2

**Comment by denyskon** [comment]
Some variables need to be updated in your theme to work, see https://github.com/go-gitea/gitea/pull/25111#pullrequestreview-1482757937
