### ISSUE TITLE
v1.20.0 does not start as a windows service

### ISSUE THREAD

**Issue by achikhv** [go-gitea/gitea#25941]
### Description

After upgrade from v1.19.4 to v1.20.0 gitea can not start as a windows service. It gives 1053 (Service didn’t respond in a timely fashion) almost immediately after start attempt. No records are written to log to help debug this issue. Service starts successfully after downgrading back to v1.19.4.

### Gitea Version

1.20.0

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

Windows Server 2019

### How are you running Gitea?

Self hosted as a windows service.

### Database

None

**Comment by lunny** [comment]
Please take a look at the error log. It's possbile your Gitea instance has some deprecated app.ini configurations.

**Comment by achikhv** [comment]
@lunny, thanks for hinting. As I said gitea did not create any log files. So I started is manually and fixed removed fallbacks found in console. After that service has started successfuly.
