### ISSUE TITLE
HTTP 500 while creating users

### ISSUE THREAD

**Issue by KazzmanK** [go-gitea/gitea#25951]
### Description
I tried to create a new user, user visibility was defaulted to private, but after clicking Create user - error 500.
Should it be a 500 error? May be a more user friendly message?
But I set user visibility to "Private", and Public users are indeed disallowed. And there was no "Public" item in visibility dropdown at all.

It looks like UI inconsistency between default dropdown selection and data passed to backend.
If I re-select Private in dropdown, user created without error.

![image](https://github.com/go-gitea/gitea/assets/13328513/46648d03-08c7-439c-8d3f-0bd74d3f1364)

### Gitea Version

1.20

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

win service

### Database

None

**Comment by KazzmanK** [comment]
But this is a new user creation, not updating existing one. Looks more like a UI issue, where wrong item from dropdown select is passed to back.

**Comment by stuzer05** [comment]
It's fixed

**Comment by ovisan** [comment]
I am facing the same issue. We have 2 gitea instances deployed (dev and prod) with the same settings in the helmrelease. In prod i can create a user when the visibility is set to private, but in dev i get 500.
