### ISSUE TITLE
Actions/Worflows missing in Gitea API

### ISSUE THREAD

**Issue by belliash** [go-gitea/gitea#25958]
### Feature Description

GitHub provides API to work with actions/workflows. Documentation can be found here: https://docs.github.com/en/rest/actions/workflows?apiVersion=2022-11-28

This functionality is missing in Gitea, actually it is impossible to get any information about actions via API. Would be nice to get similar functionality.

**Comment by wolfogre** [comment]
I think it's duplicated with #25572.
