### ISSUE TITLE
Errors in repository avatar rendering from 1.19.4 to 1.20.0

### ISSUE THREAD

**Issue by artu72** [go-gitea/gitea#25950]
### Description

Upgrading from 1.19.4 to 1.20.0 fails complaining error in rendering repository avatars. Here is the messages from logfile:

```
2023/07/18 09:52:17 routers/web/base.go:110:2() [E] [64b644b1-3] Error whilst rendering repo-avatars 5-8df08b7be0a47f48a5a31bec514c7cc1. Error:
write tcp 156.14.27.106:3000->172.16.10.21:59989: write: broken pipe
2023/07/18 09:52:17 routers/web/base.go:110:2() [E] [64b644b1-4] Error whilst rendering repo-avatars 14-14a21215b6a0716f80af584b3456c6a8. Error:
write tcp 156.14.27.106:3000->172.16.10.21:59991: write: broken pipe
2023/07/18 09:52:17 routers/web/base.go:110:2() [E] [64b644b1-5] Error whilst rendering repo-avatars 13-ea6ffdfad98d5ca7e7e670ffce7fae37. Error:
write tcp 156.14.27.106:3000->172.16.10.21:59992: write: broken pipe
```

### Gitea Version

1.20.0

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

2.25.1

### Operating System

Linux

### How are you running Gitea?

gitea binary downloaded from ypur site, started with systemd

### Database

PostgreSQL

**Comment by KazzmanK** [comment]
No issues in my case....

**Comment by silverwind** [comment]
Maybe the client closed the browser tab before avatar was finished transferring? I think it may be benign, but we shouldn't really log such errors either.

**Comment by lunny** [comment]
Whether all the repository avatars are broken or some of them?

**Comment by artu72** [comment]
UPDATE: errors were due to obsolete directives in app.ini file. I have updated them and now the service works regularly. The log outputs are however confusing, since they signaled me the error I have reported in the first post and I did not realize the true cause of he problem.
