### ISSUE TITLE
After upgrading, repositories without an issuetracker can not be accessed.

### ISSUE THREAD

**Issue by iamnumbersix** [go-gitea/gitea#2595]
- Gitea version (or commit ref): 1.2.0+rc3
- Git version: 2.11.0
- Operating system: Linux Debian 9.1 kernel 4.9.0-3-amd64
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:
routers/repo/view.go:274 Home()] [E] Home: Cannot find any unit on this repository which you are allowed to access
## Description
After upgrading from 1.1.4 to the release candidate (1.2.0+rc3), repositories without an issue tracker can not be accessed. You will get a 404 error, Page can not be found.

Switching back to 1.1.4 and enabling the internal issue tracker for that repository and switching again to 1.2.0+rc3 version, the repository is accessible again.

After disabling the issue tracker in 1.2.0+rc3 it is still accessible.
It stays accessible after switching back to 1.1.4 and 1.2.0+rc3 again.

This has been the case for rc1 and rc2 too.

**Comment by daviian** [comment]
@iamnumbersix Does this issue happen to all types of repositories (private, public, repositories from organizations)?

**Comment by lafriks** [comment]
I think it could be related to #1794

**Comment by daviian** [comment]
@iamnumbersix Can you please test my fix in PR #2600

**Comment by daviian** [comment]
@iamnumbersix Are you sure it is because of a disabled issue tracker? Could there be anything else they have in common?

**Comment by iamnumbersix** [comment]
> Can you please test my fix in PR #2600

I'm sorry, I don't have go installed, I only use the binaries

>Are you sure it is because of a disabled issue tracker? Could there be anything else they have in common?

maybe...
I'm the owner of the repositories and after I enable the issue tracker, it is available again.
The repositories are private and have been previously imported in gogs.
I've been running gitea from the first version.

**Comment by iamnumbersix** [comment]
I ran the sqlite commands in #1794
https://github.com/go-gitea/gitea/issues/1794#issuecomment-316824479

And that fixed it!
Hooray!

**Comment by daviian** [comment]
Did you upgrade from gogs?

**Comment by iamnumbersix** [comment]
Yes, I did upgrade from gogs

**Comment by daviian** [comment]
From which version of gogs to which version of gitea?

**Comment by iamnumbersix** [comment]
I think  from gogs_v0.9.97_linux_amd64 to gitea-1.1.0-linux-amd64
(those where still in my download folder) 
The date was about 30-april-2017.

But as I said, #1794 is likely the bug and the solution provided worked.

**Comment by daviian** [comment]
I needed verification to be sure ;-)

**Comment by iamnumbersix** [comment]
Thanks for all your help.

#1794 is likely describing the bug and the solution provided worked.
