### ISSUE TITLE
SSPI auth error after update to 1.20.0

### ISSUE THREAD

**Issue by AnDann** [go-gitea/gitea#25952]
### Description

After update from 1.19.4 to 1.20.0 the SSPI auth is not working anymore.
I also did a fresh install of 1.20.0 on another PC in the same domain and I get the same error message.
A fresh install of 1.19.4 doesn´t have the issue.

### Gitea Version

1.20.0

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/AnDann/8637f5e3a29719d34ded21dbd8c4adcc

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/5374645/eaa0ced2-7d06-4acb-8e0f-97a7808f5139)

### Git Version

2.40.1

### Operating System

Windows Server 2016

### How are you running Gitea?

gitea-1.20.0-gogit-windows-4.0-amd64 from https://dl.gitea.com/gitea/1.20.0/ running as a windows service under a domain user

### Database

MSSQL

**Comment by GhaziTriki** [comment]
Hello,

I also have a problem when I update to 1.20. I am using PostgreSQL. How can share the logs?

**Comment by wxiaoguang** [comment]
@AnDann 

Can you try this  Fix SSPI auth panic #25955  ?

TBH the SSPI auth module seems hasn't been maintained for long time, I do not have the experience of debugging the SSPI auth modules. If there are other more difficult problems .... maybe it needs some people who have related experience to help.

**Comment by AnDann** [comment]
I dont think the auth fails because with 1.19.4 it is working and also if auth fails it should not panic.

I will try your fix but need some time to compile it my self.

**Comment by AnDann** [comment]
@wxiaoguang With the fix in #25952 the auth is working again. I still get the same error in the logfile but in continues and finally it says Authenticated.
[Log](https://gist.github.com/AnDann/723ec6e629228e340b4bf2b2ea5efd44)

**Comment by wxiaoguang** [comment]
Since it works, I think it's safe to ignore the error log

In 1.19, there is also an error, but it's not logged as that way
