### ISSUE TITLE
[1.20.0] SQL warnings on start up

### ISSUE THREAD

**Issue by tuxmaster5000** [go-gitea/gitea#25966]
### Description

In the log the following warnings will logged on start up:

> Jul 18 17:39:54 gitea[553629]: 2023/07/18 17:39:54 cmd/web.go:175:serveInstalled() [I] PING DATABASE postgres
> Jul 18 17:39:54 gitea[553629]: 2023/07/18 17:39:54 cmd/web.go:175:serveInstalled() [W] Table system_setting Column version db default is , struct default is 1
> Jul 18 17:39:54 gitea[553629]: 2023/07/18 17:39:54 cmd/web.go:175:serveInstalled() [W] Table oauth2_application Column confidential_client db default is true, struct default is TRUE
> Jul 18 17:39:54 gitea[553629]: 2023/07/18 17:39:54 cmd/web.go:175:serveInstalled() [W] Table user Column max_repo_creation db default is '-1', struct default is -1

an **doctor --all --fix** call don't change anything.
The app looks working.

### Gitea Version

1.20.0

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

Rocky 9.2

### How are you running Gitea?

Binary from GH

### Database

PostgreSQL

**Comment by lunny** [comment]
duplicated with #22275
