### ISSUE TITLE
allow issue filtering in "global issue view"

### ISSUE THREAD

**Issue by KlavsKlavsen** [go-gitea/gitea#25979]
### Feature Description

I would REALLY like if the issue view for "global issues" ( /issues ) - would allow for filtering on f.ex. "assignee" - like the "issues" view per repository does.
This way we would actually have a way to list "all issues assigned to specific user" - which does not exist today

**Comment by KlavsKlavsen** [comment]
I am thinking it would be done easiest (and best) - by simply copying the "field headers" from "repo issue view" - which allows filtering on them ?

**Comment by ricardobranco777** [comment]
It would be nice for this to be fixed.

**Comment by wxiaoguang** [comment]
> I am thinking it would be done easiest (and best) - by simply copying the "field headers" from "repo issue view" - which allows filtering on them ?

Not that simple, will try to add the initial support (if we could catch 1.23 milestone)
