### ISSUE TITLE
Incorrect definition of table mysql.column_stats: expected column 'hist_type' ...

### ISSUE THREAD

**Issue by meonkeys** [go-gitea/gitea#25970]
### Description

My database container log grows by about 20 lines of errors with every web request. Many of these appear:

```
db_1   | 2023-07-18 18:13:11 48 [ERROR] Incorrect definition of table mysql.column_stats: expected column 'hist_type' at position 9 to have type enum('SINGLE_PREC_HB','DOUBLE_PREC_HB','JSON_HB'), found type enum('SINGLE_PREC_HB','DOUBLE_PREC_HB').
db_1   | 2023-07-18 18:13:11 48 [ERROR] Incorrect definition of table mysql.column_stats: expected column 'histogram' at position 10 to have type longblob, found type varbinary(255).
```

Seems similar to https://github.com/wallabag/wallabag/issues/6572

### Gitea Version

1.20.0

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

2.40.1

### Operating System

Docker container

### How are you running Gitea?

Docker container from `gitea/gitea:1` image. Host is 64-bit Ubuntu 22.04 LTS server. Docker version is 20.10.21.

Database is a `mariadb` 11.0.2 container from the official mariadb image.

### Database

MySQL

**Comment by KN4CK3R** [comment]
May not be related to Gitea. See https://community.home-assistant.io/t/mariadb-errors-after-update/424731

**Comment by meonkeys** [comment]
Indeed! Great find, thank you!

I found a fix/workaround: run database upgrades.

For Docker: set the `MARIADB_AUTO_UPGRADE` environment variable for the db container to any nonzero value.

* https://github.com/docker-library/docs/blob/master/mariadb/README.md#mariadb_auto_upgrade--mariadb_disable_upgrade_backup
* https://github.com/MariaDB/server/pull/2166
* https://github.com/MariaDB/mariadb-docker/issues/438
* https://jira.mariadb.org/browse/MDEV-28866
* https://github.com/docker-library/docs/issues/2164
