### ISSUE TITLE
502 error occurred while creating pull request

### ISSUE THREAD

**Issue by jackzhum** [go-gitea/gitea#25973]
### Description

**Logs:**

2023/07/19 10:29:00 ...es/pull/temp_repo.go:98:createTemporaryRepoForPR() [E] Unable to init tmpBasePath for <PullRequest [0]Jack/HBERP#0[dev...feature/rxorder]>: context canceled
2023/07/19 10:29:00 ...vices/pull/update.go:172:GetDiverging() [E] CreateTemporaryRepoForPR <PullRequest [0]Jack/HBERP#0[dev...feature/rxorder]>: context canceled
2023/07/19 10:29:00 ...ers/web/repo/pull.go:1297:CompareAndPullRequestPost() [E] NewPullRequest: context canceled
2023/07/19 10:33:10 ...es/pull/temp_repo.go:98:createTemporaryRepoForPR() [E] Unable to init tmpBasePath for <PullRequest [0]Jack/HBERP#0[dev...feature/rxorder]>: context canceled
2023/07/19 10:33:10 ...vices/pull/update.go:172:GetDiverging() [E] CreateTemporaryRepoForPR <PullRequest [0]Jack/HBERP#0[dev...feature/rxorder]>: context canceled
2023/07/19 10:33:10 ...ers/web/repo/pull.go:1297:CompareAndPullRequestPost() [E] NewPullRequest: context canceled

**After upgrading from version 1.19.3 to version 1.20, it still cannot be resolved**

### Gitea Version

1.20.0

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

2.39.0, Wire Protocol Version 2 Enabled

### Operating System

Windows Server 2012R2

### How are you running Gitea?

SYSTEM
Prod

windows service

### Database

MSSQL

**Comment by lunny** [comment]
Could you paste more logs before these logs line?

**Comment by jackzhum** [comment]
Sorry, Although I haven't found the reason, I have already solved this problem. 
I no longer tried to use pull request , but instead solved it with picking.
which may still be a branch issue because only this branch has this error.
