### ISSUE TITLE
Provide issue search via api

### ISSUE THREAD

**Issue by kolaente** [go-gitea/gitea#2597]
This is a reminder/follow-up for #2531.

For issue dependencies, we need an api-endpoint to search.
General idea: you pass a search string to the api endpoint, it searches by title and first comment/maybe even all comments and returns a json array of all found issues. Basically like Githubs issue search.

**Comment by Morlinest** [comment]
Actually there are already multiple issues about this (#2434, #1893).

**Comment by kolaente** [comment]
oookay... but none regarding the api?

**Comment by Morlinest** [comment]
@kolaente I think you can close this issue as there is basic Issue api that can be used for #2531 and we don't need to improve and add more features to it yet. Or is there any other reason to keep it open?

**Comment by kolaente** [comment]
Yes, there is an api that can be used for #2531, but there is no general endpoint to search for issues via api. There are other issues (as you said) for an issue search, but none for a search via api.
So I think we should leave it open.

**Comment by kolaente** [comment]
Fixed with #3612.
