### ISSUE TITLE
LDAP "Admin Filter" stopped working

### ISSUE THREAD

**Issue by palto42** [go-gitea/gitea#25985]
### Description

After upgrading to Gitea 1.20.0 the LDAP Admin Filter stopped working and removed all LDAP based admin permissions.

The admin filter used is:

```
(memberOf=cn=git-admin,ou=group,o=company,ou=customers,dc=company,dc=net)
```

It worked in all previous Gitea versions and there hasn't been any change on the LDAP server used.

### Gitea Version

1.20.0 - 1.20.4

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

nothing visible in the logs

### Git Version

2.40.1

### Operating System

RHEL 7.9

### How are you running Gitea?

Docker based Gitea.
Docker version 24.0.6

### Database

MariaDB
mariadb  Ver 15.1 Distrib 10.5.11-MariaDB,

**Comment by cschuber** [comment]
I'm seeing ssh keys stopped working. I'm not sure if the issue reported here is specifically LDAP or a larger issue.

**Comment by palto42** [comment]
I re-tested with latest 1.20.2, still the admin filter isn't working anymore.
Isn't there anyone else with this problem or can anyone confirm that it's working in 1.20.x ?

**Comment by arcoast** [comment]
> I re-tested with latest 1.20.2, still the admin filter isn't working anymore. Isn't there anyone else with this problem or can anyone confirm that it's working in 1.20.x ?

I've also lost admin access fwiw.

**Comment by CaiCandong** [comment]
> (memberOf=cn=git-admin,ou=group,o=company,ou=customers,dc=company,dc=net)

Although you said that your LDAP service has not been changed, I still want to confirm that your LDAP service starts the `member of` function.

**Comment by palto42** [comment]
> Although you said that your LDAP service has not been changed, I still want to confirm that your LDAP service starts the `member of` function.

@CaiCandong Not sure what you mean by "your LDAP service **starts** the `memberOf` function", but I can run this query on CLI using `ldapsearch` with the same search string.

**Comment by CaiCandong** [comment]
This is the user information I used for testing, and was able to successfully get administrator rights. Can you provide some data to help me replicate your test environment?


--- 
```
dn: uid=xiaomei,ou=north,dc=deldap,dc=com
cn: xiaomei
displayname: xiaomei
employeenumber: cn=git-admin,ou=north,dc=deldap,dc=com
givenname: xiaomei
mail: xiaomei@esgyn.local
objectclass: person
objectclass: organizationalPerson
objectclass: inetOrgPerson
objectclass: top
ou: north
sn:: 5bCP576O
uid: xiaomei
userpassword: 123456
```


 <img src="https://github.com/go-gitea/gitea/assets/50507092/6fe6b1ab-449f-44c4-8688-e873a4612aba" width = "300" height = "400" alt="图片名称" align=center />

**Comment by CaiCandong** [comment]
@palto42 Can you show us the LDAP configuration of your Gitea?

**Comment by palto42** [comment]
@CaiCandong Please find below the sanitized Gitea LDAP config we used:
![image](https://github.com/go-gitea/gitea/assets/12280188/f29deebd-6dde-4d4c-af57-5b359d8bebd7)

One difference I spotted in the user filter is that you used `%[1]s` while I have just `%s`. I tried with this change, but as expected it has no impact and the admin filer is still not working for me.

In my user record I have this entry which should be matched for the admin filter:

`memberOf: cn=git-admin,ou=group,o=company,ou=customers,dc=company,dc=net`

**Comment by palto42** [comment]
I tried with `(uid=palto42)` as admin filter and it also doesn't work.
As I tried some other group filter, I got one user as admin, but this use was not even a member of the specified group!
No idea what's going on here, in previous releases all worked fine and our LDAP server works fine with other systems.

**Comment by palto42** [comment]
@CaiCandong Can't create easily a new user (managed by different department with long approval process), I was testing the changes by running the "Synchronize external user data" from the dashboard. I have a non-LDAP admin account to ensure that I don't lose access.
Do you think there is any difference for a new user vs, running a sync? In the past it was always working with the sync if I had to change any LDAP settings.

**Comment by palto42** [comment]
> I found bug #27051 while checking the related code, but I'm unsure if this relates to your question.

Since I'm setting the user name as `uid`, I don't think that this bug applies.

![image](https://github.com/go-gitea/gitea/assets/12280188/16e9790b-ccc0-49b1-b0a7-448fb1196705)

**Comment by CaiCandong** [comment]
> Do you think there is any difference for a new user vs, running a sync? In the past it was always working with the sync if I had to change any LDAP settings.

Yes, I found that issue with one that has to do with user synchronization... wait, did you not set up a user name selection rule?
![image](https://github.com/go-gitea/gitea/assets/50507092/785a1b45-54fd-4db9-a56a-171b6b1ca197)

**Comment by palto42** [comment]
I have set "Username Attribute" as `uid`, but also tried w/o setting it - no success either way.

**Comment by gd197** [comment]
hello, same issue here after upgrading from 1.19.x to 1.20.4. Admins who were already identified did not lost their admin privilege, but new ones did not get them.
Username attribute is not set in our configuration due to another issue with LDAP ( #20422 )

**Comment by palto42** [comment]
still not working in release 1.21.0

**Comment by Josue-T** [comment]
Maybe https://github.com/go-gitea/gitea/pull/18452 will fix the issue in some cases. cf https://github.com/YunoHost-Apps/gitea_ynh/issues/76#issuecomment-1909077575

**Comment by ShayArtzi** [comment]
FWIW, I'm also seeing an issue with the LDAP admin filter (using gitea 1.21.11).

It seems that the filter is being checked only upon user creation (first login). Then if the user is added to the admin group, they won't be promoted to admin and vice versa (if the user was an admin on first logon and then removed from the LDAP admin group, the admin privilege won't be revoked)

**Comment by palto42** [comment]
I just upgraded to latest version 1.22.0 and the LDAP admin filter started working again :-)
Closing this issue as it is solved for me.
