### ISSUE TITLE
After update to version 1.20.0 Gitea refused to start 

### ISSUE THREAD

**Issue by veita** [go-gitea/gitea#25995]
### Description

* Update from Gitea 1.19.4 to 1.20.0
* Gitea deployed as a Systemd service on Debian 12

Start with `systemctl start gitea` fails.

The log configured in `app.ini` does not give any hint about the cause of the error (neither did `journalctl`).

Starting Gitea interactively from the terminal revealed the cause:

```
$ GITEA_WORK_DIR=/var/lib/gitea/ /usr/local/bin/gitea web -c /etc/gitea/app.ini
2023/07/19 19:48:36 ...g/config_provider.go:327:deprecatedSettingFatal() [F] Deprecated fallback `[server]` `LFS_CONTENT_PATH` present. Use `[lfs]` `PATH` instead. This fallback will be/has been removed in v1.19.0
```

This information should probably also be written to configured log file. Also "v1.19.0" in the error message does not seem to be correct. And it may be added to the list of breaking changes (https://github.com/go-gitea/gitea/releases/tag/v1.20.0).

### Gitea Version

1.20.0

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

Download from GitHub; run as a Systemd service.

### Database

PostgreSQL

**Comment by why0why0why** [comment]
Try to modify app.ini from
```
[server]
LFS_CONTENT_PATH=xxxxx
```
to
```
[lfs]
PATH=xxxxx
```

**Comment by veita** [comment]
@why0why0why See https://docs.gitea.com/administration/git-lfs-setup

**Comment by Johnson90512** [comment]
Can this also be added to the upgrade documentation? I just ran into this issue while upgrading and took a lot of searching to find this post.

**Comment by jme147** [comment]
I tried to create a pull request to update the installation/upgrade instructions, but couldn't create a request due to not being a collaborator. Can someone add the above file to a pull request?

**Comment by lunny** [comment]
> Can this also be added to the upgrade documentation? I just ran into this issue while upgrading and took a lot of searching to find this post.

Reasonable. I think we can add a step for upgrade which is check your admin panel top bar. Some deprecated configurations will be displayed there, if you couldn't resolve them, Gitea may cannot started after upgrade. I will create a PR for that.
