### ISSUE TITLE
Ability to disable repo archives (possible bug too?)

### ISSUE THREAD

**Issue by prurigro** [go-gitea/gitea#25992]
### Feature Description

I don't need repo archives at all- gitea basically is my archive for repos I have elsewhere.

After a recent upgrade, my server ran out of storage, so I looked for the cause and found that the repo-archive folder was taking up a couple of gigs (all remaining space). I deleted the archives, but ran out of space again the next day, so I deleted some of my larger repositories and now my repos collectively consume 300 megs in total with nearly 6 gigs free on my server. The next day my server ran out of space again, and the repo archives folder was nearly 6 gigs, so I deleted them, updated gitea and restarted it to make sure it wasn't archiving old stuff or something. The next day my server was full and the folder was nearly 6 gigs again. This time I configured gitea to delete repo clean up archives older than 4 hours daily and the next day my server was full again.

So I looked into how to disable repo archives altogether, but it seems like you can only point it at local or s3 storage. If there was a `STORAGE_TYPE = none` option under `[repo-archive]` that would be really helpful.

Thanks for your time and the great project!

**Comment by shrimpza** [comment]
I'm having this issue as well. I recently upgraded my instance and now daily I seem to have runaway disk usage I have to manually clear out.

It also seems unclear to me exactly what "Repository Archives" are, and what they're actually doing which is generating so much disk usage or why I need them.

As such I think I can live without them, and the new administration overhead they've introduced.

**Comment by lunny** [comment]
We can have a new configuration like
```ini
[repo-archive]
ENABLED = false
```
to enable/disable the repository archives. To keep compatible, the default value of enable is true.

**Comment by prurigro** [comment]
Thanks!
