### ISSUE TITLE
Show deprecated config settings in UI

### ISSUE THREAD

**Issue by jolheiser** [go-gitea/gitea#25994]
### Feature Description

https://github.com/go-gitea/gitea/blob/main/modules/setting/config_provider.go could be expanded to also collect deprecated settings and show them on the UI (perhaps in the Admin interface?).

I'm not sure whether a banner message or notification would serve better in this regard.

This may be easier than grepping logs for deprecated settings.

**Comment by wxiaoguang** [comment]
It needs a "self-check" page (ref :https://github.com/go-gitea/gitea/pull/24392#issuecomment-1527385786 )

> What about adding a "self check" page in site admin?
> It could do a full self check, including:
> 1. database versions (pgsql, mysql, etc)
> 2. database charsets (mysql), not only just checking default, but check all columns.
> 3. reverse proxy rewriting and sub path (eg: is `%2F` kept?)
> 4. system time (to resolve incorrect OTP problems)
> 5. system health like free disk, etc

And a lot of errors/warnings can be shown there (including "Add logs to tell users they should move some of their legacy custom public files" in #25974)


For the "config options", we also need our own INI package to see whether a config option is really read. If it's not used, it should also remind the users that "you have misconfiguration in your app.ini", it can avoid a lot of low-level mistakes.

**Comment by lunny** [comment]
Not only a self-check page, maybe it should also a self-fix page?

**Comment by wxiaoguang** [comment]
Only a few can be fixed by Gitea itself.

But Gitea can fix none of  "database version", "incorrect config", "proxy rewriting", "system time", "free disk" and even more.

**Comment by lunny** [comment]
We can also have a topbar warning like ROOT_URL.

**Comment by delvh** [comment]
Don't show the user things that are only intended for admins.

**Comment by lunny** [comment]
> Don't show the user things that are only intended for admins.

Of course it should not.

**Comment by wxiaoguang** [comment]
Now they are shown on the "Self Check" page.

Feel free to reopen if I missed anything.
