### ISSUE TITLE
Integrate an OAuth2 consumer

### ISSUE THREAD

**Issue by tboerger** [go-gitea/gitea#26]
To keep the barrier of Gitea as small as possible we should integrate an OAuth2 consumer. That way new users can register with just a few clicks and can reuse there already elsewhere existing accounts. A good library for that can be https://github.com/markbates/goth.

**Comment by bkcsoft** [comment]
oauth for searchabilty

( GitHub fix your search-engine FFS 😒 )

**Comment by willemvd** [comment]
This would mean some area in the admin panel/app.ini to setup OAuth2 client_id, client_secret and a provider based on the goth provider list

Do we want to support non-existing goth providers (like MS ADFS/Office365) and let users enter a custom token & authorize url which we then can use to either create a new goth provider (not sure how) or use the golang.org/x/oauth2 package?

**Comment by tboerger** [comment]
I think on the first step we will support the goth providers, but on another step we should also try to support more providers.

**Comment by lunny** [comment]
So this has been resolved by #679 ?

**Comment by willemvd** [comment]
it will be broken in to multiple PR's, first part is in #679 , but I don't think we need this as reference for the other PR's

**Comment by lunny** [comment]
So let's close this.

**Comment by Lichtjaeger** [comment]
Nice work. But I would like to use Gitea on our intranet with our own OAuth2 provider (self-made with NodeJS).

I hope, this is planned for the next releases.

**Comment by laf0rge** [comment]
I also have several use cases (even on the public inthernet) where I'd want to be able to provide my own OAuth provider.  Particularly privacy-sensitive users would not typically like to share too much data with the large Oauth "providers".  So I think it's quite desirable for every entity/organization to run their own OAuth provider and not just rely on the big OAuth providers.

**Comment by lunny** [comment]
I think you mean a customize OAuth2 config UI? @Lichtjaeger @lafOrge Maybe we could create another issue to discuss that.

**Comment by Bryanpedini** [comment]
> 
> 
> I think you mean a customize OAuth2 config UI? @Lichtjaeger @laforge Maybe we could create another issue to discuss that.

Just crossing around open / solved issues of Gitea to better understand the underlying golang structure...
Immediately noticed you menti@ned the wrong user, @lunny, that 'o' was a zero..

**Comment by lunny** [comment]
@Bryanpedini You are right. Sorry, @laf0rge

**Comment by Lichtjaeger** [comment]
@lunny @laf0rge 
This feature request has long been fulfilled. I'm using Gitea with our own auth server successfully for over a year now.
![grafik](https://user-images.githubusercontent.com/8598542/59580375-2d0e7e80-90d1-11e9-8371-691260bcc168.png)
![grafik](https://user-images.githubusercontent.com/8598542/59580429-5f1fe080-90d1-11e9-9204-ed2ae20368f3.png)
