### ISSUE TITLE
Repository Path Copy to Clipboard tooltip exits download modal

### ISSUE THREAD

**Issue by edm00se** [go-gitea/gitea#26]
When in a repository, hovering over the "download" button, there's the SSH/ HTTPS path at the top of the modal, next to it a button to "Copy" with a tool tip on hover, saying "Copy to clipboard". This tool tip, once hovered over, breaks the hover status over the "download" button, causing it to disappear as soon as  you exit the tool tip.

![gogsissue_copytoclipboardtooltiphover](https://cloud.githubusercontent.com/assets/622118/8013887/d482b894-0b91-11e5-80b9-618f4b88db08.png)

<br />
Gogs Version: 0.6.1.0325
running on Ubuntu 14.04.2 LTS 64-bit

**Comment by sapk** [comment]
It's cause by the tipsy module gaining focus (:hover) and so the :hover of the .drop is loose and the box (.drop-down) hide again. I don't know if it possible in full css because the .tipsy div is not near the .drop and using .tipsy:hover + .drop-down would make it relative to it.

**Comment by lunny** [comment]
@fuxiaohei, any idea?

**Comment by pbor** [comment]
May I ask to reconsider the whole design of the clone/download user interface?

*) a single icon only button is not easily discoverable, especially for something so important as clone
*) the automatic display-on-hover diff frustrating to use, for instance if  you want to switch between ssh and http you have to click on the buttons that are near the border and it is easy to make the popup disappear by mistake

**Comment by makhov** [comment]
I confirm annoying popup disappearance.
I think, we can design some variants of the feature and choose the best.
6 июня 2015 г. 11:43 AM пользователь "Paolo Borelli" <
notifications@github.com> написал:

**Comment by lunny** [comment]
@pbor, I agree with you. We can redesign this feature.

**Comment by makhov** [comment]
What do you think about it?
![clone ui]
(https://habrastorage.org/files/020/6db/ed7/0206dbed7966449683c6dffdd88b499a.png)

https://github.com/makhov/gitea/tree/improvement/clone-ui

**Comment by pbor** [comment]
looks quite good to me, though we need to put the tarball download somewhere.

If possible I'd also keep the "copy to clipboard" button maybe with a small icon instead of the text

**Comment by makhov** [comment]
Add «copy to clipboard»
![ui with copy to clipboard]
(https://habrastorage.org/files/e19/0da/a4c/e190daa4c97a4505bd427775b1d2e231.png)
But there is no good idea, where put download links. Maybe here?
![download links]
(https://habrastorage.org/files/25e/95f/784/25e95f7845ea4dfdbb94eda2f171208f.png)

**Comment by pbor** [comment]
It is a bit unfortunate that the download buttons and clone are so far apart since they are somehow related, but I do not have any better ideas...  would it fit in the same line of the clone with smaller  [ .zip | .tar.gz ] button instead of the green ones?


A small personal preference I think the black background clipboard icon is too evident, I'd try with black icon on gray backgrund

**Comment by xPaw** [comment]
Buttons in sidebar is a good idea, you can also put clone url there too, like it is on GitHub.

**Comment by makhov** [comment]
I'll try to design another variant soon.

**Comment by pbor** [comment]
@xPaw  to be honest I do not like github solution too much: the clone url is almost wider than the sidebar so it is always clipped

**Comment by lunny** [comment]
Good. @makhov

**Comment by makhov** [comment]
Another variant 
![with download btns]
(https://habrastorage.org/files/9da/50f/4e1/9da50f4e110d44ab9da2ea3ad4b2c75b.png)

What we choose?

**Comment by tboerger** [comment]
IMHO you can make a button group combining the download dropdown with the clone stuff. Should be interesting to see how it looks like on mobile.

**Comment by makhov** [comment]
Done #28

**Comment by makhov** [comment]
There is a problem when repo name is long.
What do think about the proposal?
![a]
(https://habrastorage.org/files/905/8eb/0f4/9058eb0f413540e5a1db91abdcf166ec.png)

**Comment by pbor** [comment]
I like it. Maybe "Download" should be a button as well: it would be consistent with the other actions (gray button, icon + text) and it would still be relatively near to the clone UI.

I also think there should be more vertical space between the buttons and "Issues"

**Comment by lunny** [comment]
The new design is great.

**Comment by nounoursheureux** [comment]
:+1: for the new design

**Comment by lunny** [comment]
But if you want to star or fork repository, you have to return back to home page to do that.

**Comment by makhov** [comment]
I'm not sure that it is a problem. Another proposal is to design it like on Github.
I can do it, but we should decide which proposal is better.

**Comment by tboerger** [comment]
I would prefer the Github proposal as well. Make just icon buttons at the side on code view or other pages that need much space and show text with it on the index project page.

**Comment by makhov** [comment]
We have to decide, what is more important for our users — the clone possibility or the fork one. 
At Github fork button is more important, because it is a Github main idea — all is around forks and pull request. 
Github has another point of view — clone is more important at self-hosted git services, because usually (in my practice) all team members has write-access to repo.

**Comment by lunny** [comment]
Yes. I agree with you. @makhov. Clone is more important at self-hosted git services.

**Comment by tboerger** [comment]
So I think we can take the way of putting the clone stuff at the top in a good size and the fork stuff at the side with small icons within views that need much space? :)

**Comment by makhov** [comment]
I'll try to do something fine  :)

2015-06-09 16:24 GMT+03:00, Thomas Boerger <notifications@github.com>:

**Comment by tboerger** [comment]
> I'll try to do something fine  :)

I trust you that you will figure out some awesome stuff :)

**Comment by tboerger** [comment]
As the "copy to clipboard" feature is not in an popup anymore we can close this issue.
