### ISSUE TITLE
DB warnings on start

### ISSUE THREAD

**Issue by somera** [go-gitea/gitea#26027]
### Description

After upgrade to 1.20.0 I see in gietea.log this:

2023/07/21 00:47:25 cmd/web.go:175:serveInstalled() [W] Table system_setting Column version db default is , struct default is 1
2023/07/21 00:47:25 cmd/web.go:175:serveInstalled() [W] Table oauth2_application Column confidential_client db default is true, struct default is TRUE
2023/07/21 00:47:25 cmd/web.go:175:serveInstalled() [W] Table session has column created_unix but struct has not related field
2023/07/21 00:47:25 cmd/web.go:175:serveInstalled() [W] Table email_address Column lower_email db nullable is true, struct nullable is false
2023/07/21 00:47:25 cmd/web.go:175:serveInstalled() [W] Table user Column max_repo_creation db default is '-1', struct default is -1
2023/07/21 00:47:26 cmd/web.go:175:serveInstalled() [W] Table project column board_type db type is INTEGER, struct type is BIGINT
2023/07/21 00:47:26 cmd/web.go:175:serveInstalled() [W] Table project column card_type db type is INTEGER, struct type is BIGINT
2023/07/21 00:47:26 cmd/web.go:175:serveInstalled() [W] Table project Column card_type db default is 0, struct default is
2023/07/21 00:47:26 cmd/web.go:175:serveInstalled() [W] Table project Column card_type db nullable is false, struct nullable is true
2023/07/21 00:47:26 cmd/web.go:175:serveInstalled() [W] Table project column type db type is INTEGER, struct type is BIGINT
2023/07/21 00:47:27 cmd/web.go:175:serveInstalled() [W] Table hook_task has column repo_id but struct has not related field

warnings.

### Gitea Version

1.20.0

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

2.41.0

### Operating System

Ubuntu 20.04.5

### How are you running Gitea?

Downloaded official gitea-1.20.0-linux-amd64 file.

### Database

PostgreSQL

**Comment by lunny** [comment]
duplicated with #22275
