### ISSUE TITLE
Searching in all repositories I can see

### ISSUE THREAD

**Issue by clrh** [go-gitea/gitea#26040]
### Feature Description

I am looking for a way to "search" in all repositories, not only the titles.  It could be a tab on the line "Repositories / Users / Organizations" called "Code". Something like /explore/code for example.

I read others issues about this topic. Does some people having a workaround to use it like this or another way in another place to do this?

Thanks a lot :)

### Screenshots

![Sélection_091](https://github.com/go-gitea/gitea/assets/471280/ea1dfd93-6acb-4618-b72c-6c4f33913c5f)

**Comment by JakobDev** [comment]
It is already [possible to search Code in Gitea](https://docs.gitea.com/administration/repo-indexer), but it must be enabled by the Admin.

**Comment by clrh** [comment]
Ok, thanks for quick answers :)
