### ISSUE TITLE
Gitea Actions - could not find runner by label

### ISSUE THREAD

**Issue by sgabenov** [go-gitea/gitea#26045]
### Description

Gitea - v 1.20.0
Runner - tested on 0.2.3 (linux) and nightly v0.2.3-10-g1a7ec5f
Runner - INFO Registering runner, arch=amd64, os=linux, version=v0.2.3-10-g1a7ec5f

I have configured Gitea Actions, added and registered runner, but all jobs are not executed. I can see on UI, that it could not find runner by label. But the label exists. See attached screenshots.

### Gitea Version

1.20.0

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

<img width="1800" alt="actions_0" src="https://github.com/go-gitea/gitea/assets/15741789/bc603557-93cc-498b-849f-27d7945967ad">
<img width="712" alt="actions_1" src="https://github.com/go-gitea/gitea/assets/15741789/f49c63bb-77ea-46c7-b8b8-0baa061bd29c">
<img width="725" alt="actions_2" src="https://github.com/go-gitea/gitea/assets/15741789/36ae868e-4ed0-4346-921d-40a4dc845712">
ubunt

### Operating System

ubuntu 22.10

### How are you running Gitea?

docker

### Database

PostgreSQL

**Comment by CaiCandong** [comment]
I can't reproduce the bug, are you able to provide more details?

**Comment by wolfogre** [comment]
Let me guess.

- According to the screenshot, the type of the runner is "Individual", so it means that you have registered a runner for your own account, not an organization or the entire instance.
- And you tried to test Actions on `sandbox/gitea-actions`, I am not sure, but `sandbox` doesn't sound like a username, maybe it's a organization?
- If I'm right, you should register a runner for `sandbox`, not your own account.

**Comment by sgabenov** [comment]
@wolfogre Thank you! Indeed, the runner was configured not for organization, but for individual.

@CaiCandong - There is a problem in documentation, actual links to configure actions are different, compared to this article:
https://docs.gitea.com/next/usage/actions/act-runner#obtain-a-registration-token

Actual links to Gitea 1.20 are:
Global: https://<gitea_url>/admin/actions/runners
Organization: https://<gitea_url>/org/<org>/settings/actions/runners
Individual: https://<gitea_url>/user/settings/actions/runners

Also i wold recommend to add information how to configure it from UI as well to this page (https://docs.gitea.com/next/usage/actions/quickstart)

Global: Site Administration > Actions > Runners
Organization: Explore > Organizations > <Org> > Settings > Actions > Runners
Individual: User > Settings > Actions > Runners

**Comment by CaiCandong** [comment]
@sgabenov Thank you a lot for your suggestion
