### ISSUE TITLE
[chore] Why use `GITHUB_READ_TOKEN` in workflows

### ISSUE THREAD

**Issue by harryzcy** [go-gitea/gitea#26054]
### Feature Description

Github automatically adds `GITHUB_TOKEN` to all actions. Is there a reason why we are using non-standard `GITHUB_READ_TOKEN` in some of the tests?

I searched around and I guess it's created when still using drone for CI. So we actually could update this?

**Comment by wolfogre** [comment]
IIRC, `GITHUB_TOKEN` is used to checkout the code of Gitea, while `GITHUB_READ_TOKEN` is used to test migration from GitHub, it has only read access to `go-gitea/test_repo`. I don't think they're the same thing.

https://github.com/go-gitea/gitea/blob/e81ccc406bf723a5a58d685e7782f281736affd4/services/migrations/github_test.go#L20-L24

**Comment by harryzcy** [comment]
Thanks, closing as it's intended
