### ISSUE TITLE
Integration tests os.RemoveAll directory not empty

### ISSUE THREAD

**Issue by daviian** [go-gitea/gitea#2605]
- Gitea version (or commit ref):
- Git version:
- Operating system: Windows 10
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:
```
[Macaron] 2017-09-25 20:05:38: Started GET /user2 for 
[Macaron] 2017-09-25 20:05:38: Completed /user2 200 OK in 7.9266ms
PASS
os.RemoveAll: remove integrations/indexers-pgsql/issues.bleve: directory not empty
make: *** [Makefile:190: test-pgsql] Error 1
```

## Description

Since merging of https://github.com/go-gitea/gitea/commit/b0f7457d9ef6e16d4a3197f7544035d5d387e201 I get this log when running integration tests in docker container.
I am using the `webhippie/golang:edge` image.

The full command I use is as follows:
`run -i --rm -v D:\Development\go\src\code.gitea.io\gitea:/srv/app/src/code.gitea.io/gitea -w /srv/app/src/code.gitea.io/gitea --link gitea-test-db:pgsql -e TAGS="bindata" webhippie/golang:edge make build test-pgsql`

**Comment by ethantkoenig** [comment]
That's strange, [os.RemoveAll](https://golang.org/pkg/os/#RemoveAll) isn't supposed to fail for non-empty directories.

**Comment by daviian** [comment]
I guess it is https://github.com/golang/go/issues/20841

**Comment by daviian** [comment]
And because it is an issue with WSL I will close this one.
