### ISSUE TITLE
[Docs] Missing 404 swagger response docs for /admin/users/{username}

### ISSUE THREAD

**Issue by lonix1** [go-gitea/gitea#26079]
### Description

The swagger [endpoint](https://try.gitea.io/api/swagger#/admin/adminDeleteUser) `/admin/users/{username}` is missing the response `404`.

When the account does not exist then the API returns 404 - but that is not shown in the swagger docs.

### Gitea Version

1.21.0+dev-354-g24c3bb95a

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

n/a

### Git Version

n/a

### Operating System

n/a

### How are you running Gitea?

n/a

### Database

None

**Comment by CaiCandong** [comment]
I was able to reproduce the problem, and I'm going to propose a PR to fix swagger's documentation
