### ISSUE TITLE
View repo failed

### ISSUE THREAD

**Issue by hiifong** [go-gitea/gitea#26070]
### Description

build from main branch,https://github.com/go-gitea/gitea/commit/a12a5f3652c339b17b187ff424a480631a3c1e1e

```
An error occurred:

GetRecentlyPushedBranches, Error 1267 (HY000): Illegal mix of collations (utf8mb4_0900_ai_ci,IMPLICIT) and (utf8mb4_general_ci,IMPLICIT) for operation '='
```
![image](https://github.com/go-gitea/gitea/assets/89133723/7c457f41-67cd-4d28-9c78-28711837999b)

### Gitea Version

1.20.0+rc0-353-ga12a5f365

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

./gitea web

### Database

MySQL

**Comment by delvh** [comment]
Oh, woohoo.
I start to hate MySQL.

**Comment by wxiaoguang** [comment]
It's not really related to MySQL, but it's Gitea's fatal.

In history, Gitea allows users to customize everything, including the MySQL's charset (but not other database's ....)

Then, incorrect charset causes this problem.

**Comment by hiifong** [comment]
temporary solution: run `./gitea convert`command

**Comment by lunny** [comment]
We need to have a fixed charset and collation for all supported databases.

**Comment by hiifong** [comment]
I think if we can automate the convert operation after the migration
