### ISSUE TITLE
Official arm/rpi docker image

### ISSUE THREAD

**Issue by schvabodka-man** [go-gitea/gitea#2607]
Hello, there are currently only gitea images for x86. Would be cool if someone would build one for arm platforms. Gogs, for example has seperate image for rpi

**Comment by lafriks** [comment]
There is already built binaries already for all platforms both on GitHub for releases and in https://dl.gitea.io/gitea/

**Comment by Kunde21** [comment]
It's not official, but [this container](https://hub.docker.com/r/kunde21/gitea-arm/) is built (with sqlite support) for arm and is running on my rpi3.

**Comment by funkyfuture** [comment]
a multi-arch manifest on the Hub would be a nice topping on this.

**Comment by sapk** [comment]
@funkyfuture I plan to do a multi-arch setup (allready had but I separated it to ease the review process). Now, I wait for #2927 to be merged to go to next phase multi-arch.

**Comment by techknowlogick** [comment]
This is a dupe of #531 

Can this issue be closed?
