### ISSUE TITLE
404 in 1.20.1 when branch name contains #

### ISSUE THREAD

**Issue by dusatvoj** [go-gitea/gitea#26088]
### Description

I did an upgrade to gitea 1.20.1 (from 1.19.x) and now I'm facing the issue with WebUI - it's returning 404 when branch name contains `#`.

Link contains unescaped `#` ( `...branch#130...` ) - it could cause the problem :thinking: 

It's pretty severe bug bcs we are using reference of issue in branch name, so almost every branch has `#` in it's name :see_no_evil: 

### Gitea Version

1.20.1

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

Debian 11

### How are you running Gitea?

Built from source, run by systemd, proxied by external nginx.

### Database

PostgreSQL

**Comment by stuzer05** [comment]
Same here, problem is still present on latest dev commit. 

![image](https://github.com/go-gitea/gitea/assets/23124682/c408133d-d813-414e-93f0-57389dbbf7c5)
![image](https://github.com/go-gitea/gitea/assets/23124682/1b82ec45-e5c5-4010-bdef-86e64edf7a7a)

**Comment by silverwind** [comment]
Should be fixed when https://github.com/go-gitea/gitea/pull/25875 is backported.

**Comment by lunny** [comment]
Closed as #26103 merged.
