### ISSUE TITLE
Git LFS - Garbage collect LFS meta objects error

### ISSUE THREAD

**Issue by Lifeismana** [go-gitea/gitea#26093]
### Description

The "Garbage collect LFS meta objects" cron jobs errors when i try to run it
`Task: Garbage collect LFS meta objects cancelled: pq: invalid input syntax for type bigint: "2023-07-17 11:42:52.475264931+02:00"`

relevant log:
> 2023/07/24 11:42:52 ...rvices/cron/tasks.go:140:GetTask() [I] Getting gc_lfs in &{{0 0} gc_lfs 0xc001c7a6c0 0x24d9680 error pq: invalid input syntax for type bigint: "2023-07-17 10:49:23.693085257+02:00" 

### Gitea Version

1.21.0+dev-354-g24c3bb95a

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

2.40.1

### Operating System

debian

### How are you running Gitea?

docker with postgresql 14.02 as a db in the same stack

### Database

PostgreSQL

**Comment by Zettat123** [comment]
related to
https://github.com/go-gitea/gitea/blob/5db640abcd8608b065a1b390404bba2233220c95/models/git/lfs.go#L396-L401
