### ISSUE TITLE
Release is not Updated when recreating Tag

### ISSUE THREAD

**Issue by JakobDev** [go-gitea/gitea#26090]
### Description

If you recreate a Tag on a new Commit, the Release will not be updated.

Steps to reproduce:
1. Create a new Repo
2. Create a new Release with a Tag called "Test"
3. Clone the Repo
4. Run these commands:
```bash
git tag -d Test
git commit --allow-empty -m "New Commit"
git tag Test
git push
git push -f --tags
```

If you visit the Release Page, it shows 

> 1 commits to main since this release

But this is not true. The Tag has now changed to the latest Commit.

I expect Gitea to do one of these 2 Options:
1. Just Update the Release
2. Do the same as if the Tag was deleted

### Gitea Version

1.20.1

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

Not relevant to reproduce

### Git Version

2.41.0

### Operating System

Manjaro

### How are you running Gitea?

Binary downloaded from GitHub

### Database

SQLite

**Comment by delvh** [comment]
I mean…
I have a fairly good guess of why  happens what

**Comment by CaiCandong** [comment]
I tried to reproduce the issue on top of `github`, and when I modify the tag to push it to github, I get the following error:
```
Unable to pull from remote repository due to conflicting tag(s): v0.01.
Would you like  to resolve the conflict by replacing the local tag(s)?
```
![image](https://github.com/go-gitea/gitea/assets/50507092/9ce99683-0794-4c74-abfe-25ed34d61d54)

I can only complete the push if I modify the local tag to match the remote repository.

**Comment by CaiCandong** [comment]
> I expect Gitea to do one of these 2 Options:
> 
> 1. Just Update the Release
> 2. Do the same as if the Tag was deleted

I reproduced the problem on top of Github
- When I remove this tag, the corresponding release becomes `Draft` state:
![image](https://github.com/go-gitea/gitea/assets/50507092/5812a1c7-b809-4102-823a-1c4e82894f8b)
- When I re-pushed the tag, `github` didn't automatically update the release, its status was still `Draft`, and its sha was based on the current tag location.
![image](https://github.com/go-gitea/gitea/assets/50507092/634a2c8b-8775-49c9-b3f7-50c0857ed613)

**Comment by CaiCandong** [comment]
I can't reproduce your problem on gitea, I'm getting everything fine, Release is being updated automatically.
https://gitea.com/caicandong/gitea-debug
![image](https://github.com/go-gitea/gitea/assets/50507092/504fe9b6-a4d3-4d7b-a42d-5ad0e4c40d55)
![image](https://github.com/go-gitea/gitea/assets/50507092/f5da566a-3562-4aec-8190-0195f5c7eb49)

**Comment by JakobDev** [comment]
What have you done? Delete Tag > Push > Recreate Tag > Push or Delete Tag > Recreate Tag > Push?

**Comment by CaiCandong** [comment]
> What have you done? Delete Tag > Push > Recreate Tag > Push or Delete Tag > Recreate Tag > Push?
Follow your reproduction steps

**Comment by CaiCandong** [comment]
@JakobDev I recorded a video that you can watch.

https://github.com/go-gitea/gitea/assets/50507092/998fa791-c813-4409-9139-69cb2362d772

**Comment by JakobDev** [comment]
Interesting. Did you try this on 1.20.1 or the latest commit?

**Comment by CaiCandong** [comment]
> Interesting. Did you try this on 1.20.1 or the latest commit?

My code is based on the latest commit

**Comment by Zettat123** [comment]
> @JakobDev I recorded a video that you can watch.
> 
>  default.mp4

That's weird. I followed the steps in this video and finally reproduced the bug

**Comment by wolfogre** [comment]
The point is that the tag `Test` has an uppercase letter, and the incorrect code attempted to find existing releases with a lower name but couldn't find it. Then, when it tried to create a new one, it failed due to a unique index constraint. Therefore, you should see this error log:

```text
2024/02/19 16:15:45 ...s/repository/push.go:41:handler() [E] pushUpdate[root/update_tag_release] failed: PushUpdateAddDeleteTags: Insert: pq: duplicate key value violates unique constraint "UQE_release_n"
```

And why can't CaiCandong reproduce, while Zettat123 can? I think CaiCandong is using a database that is case-insensitive, maybe MySQL with a case-insensitive collation.
