### ISSUE TITLE
500 error on pull request view page

### ISSUE THREAD

**Issue by stuzer05** [go-gitea/gitea#26118]
### Description

![image](https://github.com/go-gitea/gitea/assets/23124682/65a78ed7-5f9f-499d-b927-3c4e79162a3e)

### Gitea Version

trunk

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

docker

### Database

None

**Comment by CaiCandong** [comment]
I have located the bug and am trying to fix it
