### ISSUE TITLE
Git Hooks (pre-receive) with fail check drops Gitea to 502 Error

### ISSUE THREAD

**Issue by sgabenov** [go-gitea/gitea#26129]
### Description

I have faced a situation where Git Hook drops Gitea to 502 Error.
Git Hook checks commits for some naming templates and raise error if check is not completed. All commits/PRs are blocked if check is failing.

Issue:
Gitea executes Git Hook on PR with non 0 error code. After receiving exit code 1 it drops to 502 Error

Expected behavior:
Show page with git console and error code from git. Do not drop to 502. 

How to reproduce:
1. Enable git hooks on Gitea and Configure Git Hook (pre-recive) on server side with this code:
```
#!/bin/bash

# Error message for BRANCH POLICY
error_msg_branch=$(cat <<-END

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@                                                                               @   
@   !!! Push not allowed by BRANCH NAME policy !!!                              @
@                                                                               @  
@   You branch should be named with these templaes:                             @
@     - master                                                                  @
@     - develop                                                                 @
@     - release/RC_*                                                            @
@     - feature/JIRA_ID-000--*                                                  @
@     - bugfix/*                                                                @
@     - hotfix/*                                                                @
@                                                                               @
@   Example: feature/MEC-167--add_new_functionaliry                             @
@                                                                               @
@   Wiki: https://confluence.ncloudtech.ru/display/KDM/Git+branch+naming        @                                                                        @
@                                                                               @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
    
END
)

error_msg_commit=$(cat <<-END

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@                                                                                 @
@   !!! Your Commit does not have a referance to JIRA ticket !!!                  @
@                                                                                 @
@   Please correct your Git messages, and push again.                             @
@   Example: "[KDM-1234] This is a correct JIRA reference"                        @
@                                                                                 @
@   Wiki: https://confluence.ncloudtech.ru/pages/viewpage.action?pageId=201708163 @                                                                                @
@                                                                                 @
@   To FORCE push, use "bugfix" or "hotfix" in your commit message                @                                                                  @
@                                                                                 @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
    
END
)



while read oldrev newrev refname
do
  #
  # Step 0:
  # Get Git commit information
  #
  BRANCH_NAME_FULL=$refname
  BRANCH_NAME="$(echo $BRANCH_NAME_FULL | sed 's/refs\/heads\///g')"
  COMMIT_MESSAGE=$(git log --format=%B -n 1)
  echo "[INFO] BRANCH NAME: $BRANCH_NAME"

  #
  # Step 1:
  # Policy - Check that brunch name is enforced by branch name
  #

  echo "[INFO] Policy - Check that brunch name is enforced by branch name"
  # Regexp for allowed names of branches
  branch_name_format='^master|^main|^develop|^release\/RC_.*|^feature\/[a-zA-Z0-9,\.\_\-]+-[0-9]+.*|^hotfix\/.*|^bugfix\/.*'
  
  if [[ ! $BRANCH_NAME =~ $branch_name_format ]]; then
      echo "$error_msg_branch" >&2
      exit 1
  else
      echo "Push is successful"
  fi

  #
  # Step 2:
  # Policy - Check commit message for JIRA issue number
  #

  # Configuration
  echo "[INFO] Policy - Check commit message for JIRA issue number"
  jiraIdRegex="[a-zA-Z0-9,\.\_\-]+-[0-9]+"
  fixMsgRegex="bugfix|hotfix"
  info_msg="[INFO] The commit message looks good"
  error_msg="[POLICY] The commit doesn't reference a JIRA issue"

  # Get all commits from this push
  for sha1Commit in $(git rev-list $oldrev..$newrev);
  do
    # Receive git commits sha from git history in chronologic order
    echo "[INFO] Processing commit with sha: $sha1Commit";
    # Get commit message from commit
    commitMessage=$(git log --format=%B -n 1 $sha1Commit)
    # Check with RegEX if commit has JIRA reference
    jiraIds=$(echo $commitMessage | grep -Eo $jiraIdRegex)
    fixMsg=$(echo $commitMessage | grep -Eo $fixMsgRegex)
    # Check if this commit urgent e.g. hotfox or bugfix
    if [[ -n "${fixMsg}" ]]; then
      echo "[WARNING] Found "bugfix|hotfix" in msg. Force skipping check for JiraID"
      exit 0
    fi
    # Check for JiraIDs in commit message
    echo "[INFO] Found JIRA IDs in commit: $jiraIds"
    if [[ -z "${jiraIds}" ]]; then
      echo "$error_msg: $commitMessage" >&2
      echo "$error_msg_commit" >&2
      exit 1
    fi
  done
done

#
# Exit
#
exit 0
```
2. Create new branch `feature/jira-123_some_text` and push to gitea
3. Create PR from `feature/jira-123_some_text` --> master
4. Get Error 502 on Gitea. The reason of this error, bacause git hook check failes. It not allows refs with PRs and exit with error 1. 
I expect, that it will show `$error_msg_branch >&2` from bash script in hook redirected to git log (How it is done on client side, if hook failes), but not prop to 502 Error

If i change   `branch_name_format='^master|^main|^develop|^release\/RC_.*|^feature\/[a-zA-Z0-9,\.\_\-]+-[0-9]+.*|^hotfix\/.*|^bugfix\/.*'` to `  branch_name_format='pull|^master|^main|^develop|^release\/RC_.*|^feature\/[a-zA-Z0-9,\.\_\-]+-[0-9]+.*|^hotfix\/.*|^bugfix\/.*' the check will not fail and PR working
`

### Gitea Version

1.20.0

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

![Screenshot1](https://github.com/go-gitea/gitea/assets/15741789/8eb053ad-e7a4-4c63-ace5-953ff6fd9864)
![Screenshot2](https://github.com/go-gitea/gitea/assets/15741789/2ae1edbb-766a-4bdd-b8ab-bb7cb89bd56f)

### Operating System

linux

### How are you running Gitea?

docker

### Database

PostgreSQL

**Comment by KazzmanK** [comment]
Don't 502 error comes from nginx?
Try to reproduce the same without nginx in between, or check gitea logs for more info.

**Comment by sgabenov** [comment]
The same behaviour when connecting directly to Gitea

**Comment by CaiCandong** [comment]
Following the reproduction steps you gave , I can reproduce reproduce the problem, but the error code is 500, and because of the git hook, the PR is not actually created successfully, but it is recorded in the PR list.

- Log messages when PR creation fails
![image](https://github.com/go-gitea/gitea/assets/50507092/c7b7d89d-bccf-48b8-a25d-274bfe786f94)


- PR records
		![image](https://github.com/go-gitea/gitea/assets/50507092/0e1c03a9-edd9-4117-b4a2-56ef648b582f)

- PR not exists
		![image](https://github.com/go-gitea/gitea/assets/50507092/77102619-358c-4c7b-8a71-e02ec900580e)

**Comment by CaiCandong** [comment]
> The same behaviour when connecting directly to Gitea

Did you use gitea directly to get a result of 500? Something like this?

> * PR not exists
>   ![image](https://user-images.githubusercontent.com/50507092/257128903-77102619-358c-4c7b-8a71-e02ec900580e.png)

**Comment by sgabenov** [comment]
@CaiCandong Initially i used gitea with nginx reverse proxy, when 502 error happened. After that i used direct connection to host and got the same behaviour as you posted.

**Comment by sgabenov** [comment]
@CaiCandong on gitea 1.19 the same hook worked a bit different. Gitea did not show 500 error and show git remote message in log, instead gitea showed this git remote message on Gitea web-page before creating PR. And this was good solution, as i can see the reason of error and fix it.

**Comment by CaiCandong** [comment]
> @CaiCandong on gitea 1.19 the same hook worked a bit different. Gitea did not show 500 error and show git remote message in log, instead gitea showed this git remote message on Gitea web-page before creating PR. And this was good solution, as i can see the reason of error and fix it.

I've located the problem and will fix it soon
