### ISSUE TITLE
gitea and Netlify

### ISSUE THREAD

**Issue by freedomtrain** [go-gitea/gitea#2612]
Is it possible to use Netlify https://www.netlifycms.org/  with Gitea ?

Thanks for your wonderful Art !!!

**Comment by pgaskin** [comment]
Not at the moment. At the moment, there is no external OAuth client written for Gitea for NetlifyCMS. 

See https://www.netlifycms.org/docs/custom-authentication/#external-oauth-clients for details about external OAuth clients for NetlifyCMS.

This feature also depends on this issue: #27

**Comment by fazlerabbi37** [comment]
@geek1001 it seems issue #27 is closed.

**Comment by lunny** [comment]
Right, someone could send a PR to https://github.com/igk1972/netlify-cms-oauth-provider-go to add gitea support.

**Comment by techknowlogick** [comment]
Seems the linked repo uses Goth as an oauth interface, and as such I've submitted the following PR to Goth: https://github.com/markbates/goth/pull/276 which is a dependency to get the linked repo using Gitea OAuth. Getting my PR into Goth will also allow Gitea to use other Gitea installs as an auth provider, which is very exciting.

**Comment by 6543** [comment]
I think https://github.com/igk1972/netlify-cms-oauth-provider-go/pull/9 is closing this?

**Comment by techknowlogick** [comment]
Sadly that PR doesn't close this, we have that PR running at https://netlify-auth.gitea.io/ however Gitea would need to be added as a provider to netlify-cms itself.

**Comment by ShalokShalom** [comment]
And what does prevent this?

**Comment by 6543** [comment]
@ShalokShalom time to contribute

**Comment by ShalokShalom** [comment]
I mean, it seems to be particularly implemented, so I ask again: What is still missing?

**Comment by lafriks** [comment]
@ShalokShalom netlify needs to add Gitea support on their side

**Comment by ShalokShalom** [comment]
Oh. They actually wait for us to do [so](https://github.com/netlify/netlify-cms/issues/1109) 😄
