### ISSUE TITLE
"You pushed on branch" message shows branch from different repository

### ISSUE THREAD

**Issue by stuzer05** [go-gitea/gitea#26130]
### Description

When you push to gitea, "new pull request" message shows up on "code" tab in repository. But the branch it shows is from a different repository

### Gitea Version

master

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/23124682/3c74c813-6166-4e9e-860c-5691c0c2f391)
![image](https://github.com/go-gitea/gitea/assets/23124682/e2f11b8c-0c52-4307-9fb8-c37afc6597fa)

### Git Version

latest

### How are you running Gitea?

docker

### Database

None

**Comment by Zettat123** [comment]
I reproduced this bug. Maybe we should only show the message for the repository the newly pushed branch belongs to or the upstream repository of a forked repository.
