### ISSUE TITLE
Adopting a "packed-refs" repository with tags

### ISSUE THREAD

**Issue by KazzmanK** [go-gitea/gitea#26138]
### Feature Description

Lets say we have a repository (windows)
```
mkdir packed
cd packed
git init
echo test > test.txt
git status
git add test.txt
git commit
git tag tag1
git show tag1
git pack-refs
```

now we have a packed repository. lets convert it to bare

```
copy .git ../packed.git
cd ..
cd packed.git
git config --bool core.bare true
```

Now lets adopt this repository by Gitea

It is adopted, but I was unable to make Tags working. Tags remains 0, git push with force tags also says nothing to push. 
The only way - push this (non bare) repository to emptyv repo in Gitea with tags. Only this way it shows tags in UI and in repo itself.

Can anyone try to reproduce and verify if it is a bug.

**Comment by lunny** [comment]
This maybe a bug that when adopting, tags are not synced into database.
