### ISSUE TITLE
Support quickly create workflow file in web ui

### ISSUE THREAD

**Issue by yp05327** [go-gitea/gitea#26145]
### Feature Description

Add new option here, then can quickly create a workflow file by only one click:
![image](https://github.com/go-gitea/gitea/assets/18380374/c843aac0-61c1-4359-889b-2f1db5d168c8)

If we want to add a new workflow file in web ui, the step now is that we should input `.gitea/workflows` or `.github/workflows` after click `add file` -> `new file`.
As the folder path of workflows will not change, maybe we can add new options called `New Gitea Workflow` and `New GitHub Workflow`?

**Comment by wolfogre** [comment]
Not sure, not everyone use Actions.

And what if `New License`, `New README`, `New GitIgnore`, `New Issue Template`, `New ...`

**Comment by yp05327** [comment]
> Not sure, not everyone use Actions.

We can display this option only in repos with action unit enabled.

> And what if New License, New README, New GitIgnore, New Issue Template, New Makefile, New Dockerfile, New ...

Sounds good.
