### ISSUE TITLE
Add the ability to add estimated time to an issue

### ISSUE THREAD

**Issue by kolaente** [go-gitea/gitea#2615]
It would be cool if you could add estimated time to an issue to better plan the workflow.

@JonasFranzDEV this is probably relevant for you.

**Comment by lunny** [comment]
So let's close this one since duplicated with #3003

**Comment by gsantner** [comment]
@lunny 
I think this can be reopened as #3003 didn't handle `time estimation`. At least as in current commit 3fb038c theres no estimation feature.

**Comment by gsantner** [comment]
-

**Comment by jsanchezba** [comment]
Any news on this? I guess it's not a hard thing to do, i tried but don't event know from where to start. Don't know where the controllers are, and i never used Go before.

**Comment by Eistime** [comment]
this feature could make my life 100 times easier! hope you guys doing well! animo! :)

**Comment by ian-steffy** [comment]
While Github Projects now works on features like 'Super cool customization for workflow automation' they ignore extremely basic task management tool core functionality like time estimations and being able to add attachments or have discussions in GH Projects. 

It's 5 years later and they have still done nothing for this.

**Comment by MrHaroldA** [comment]
Any progress on this?

**Comment by ivancxj** [comment]
have plan?

**Comment by ZJM6658** [comment]
i love gitea very much, i use gitea every day, 
this feature could goes well with my work !
i hope you guys have a plan ~

**Comment by chriswnz** [comment]
Would use this feature, without firing up a project management system, it's a quick way to check how time spent is going.

Love Gitea thanks to everyone involved.

**Comment by delvh** [comment]
Hasn't this already been implemented already for a long time?
![image](https://user-images.githubusercontent.com/51889757/188305718-bdd3cb36-8839-453f-9e7c-02bdd28e836f.png)

**Comment by lafriks** [comment]
That's spent time - estimated time is for planning to set estimated time on how much time would be needed to fix/implement issue

**Comment by lunny** [comment]
> That's spent time - estimated time is for planning to set estimated time on how much time would be needed to fix/implement issue

We already have start date, maybe an end date could satisfy the requirement and that will be a base of gantte graph

**Comment by GeNTooFReaK** [comment]
> We already have start date, maybe an end date could satisfy the requirement and that will be a base of gantte graph

In this issue (feature request) it's wanted to set estimated time in the manner of "implementing this is estimated to take 8 hours" and later be able to compare it to the actual time spent. GitLab has this feature (estimated and spent time).

**Comment by chriswnz** [comment]
Unfortunately an end or due date doesn't really let me log what I estimated for time vs what I logged in the issue.
Even if I had the luxury of only working on  a single issue at a time to make that work, the granularity on due date is entire days where an issue may only be estimated at 3 hours. 
It would also help with selecting issues to work on by selecting issues that might have a lower priority but can be cleared in a short amount of time. Sometimes its nice just to clear a few.
Thanks.

**Comment by julienfastre** [comment]
I encounter the same requirements. I'm trying to add this feature on gitea. I am on early stage, visible there: https://github.com/go-gitea/gitea/compare/main...julienfastre:gitea:2615-add-estimated-time-to-issue (I am a newbie here, guidance and remarks are welcome!)

**Comment by denyskon** [comment]
This seems to be discussed actively/worked on in #23112. I think it is better to close this to prevent issue duplication (even though this issue is way older)
