### ISSUE TITLE
[Bug] Actions status on commits for a repo that disabled Actions (resulting in 404 page)

### ISSUE THREAD

**Issue by theoludwig** [go-gitea/gitea#26160]
### Description

When enabling Gitea actions on a repository, and then pushing a commit that trigger the actions to run, then disabling the Actions on a Gitea repository, the status of the commits stays.

![image](https://github.com/go-gitea/gitea/assets/25207499/0079e5a9-b19c-4ffe-8be6-a46fdc0491a6)

When clicking on details, it results in a 404 error page.
You can see the issue on my Gitea instance here: https://git.theoludwig.fr/theoludwig/eslint-config-conventions

To add more context, I mirrored this repository from GitHub on my Gitea instance, and forgot to disabled Gitea Actions, so the "Release" job fails, because it was not meant to run on my Gitea instance, so I disabled the actions, and still see the failing checks.

---

I would say that the expected behavior would be to not display the status of a commit if actions are disabled, if wanted I would gladly contribute and open a PR to fix this, and be my first Gitea contribution. :smile:

### Gitea Version

https://github.com/theoludwig/gitea/tree/production

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

2.41.0

### Operating System

Ubuntu Server 22.04.2 LTS

### How are you running Gitea?

I compiled Gitea myself, with a slightly modfied Gitea (to add material icons based on filenames), but this is not relevant to this issue, as it doesn't change Gitea Actions at all.
You can see the commit here: https://github.com/theoludwig/gitea/commit/f03e15601fb700d81aeb0d63c5a14540d9fe7dec

### Database

PostgreSQL

**Comment by lunny** [comment]
Commits status is not a part of Actions. All other CI/CD system could also push commit status to Gitea.

**Comment by theoludwig** [comment]
> Commits status is not a part of Actions. All other CI/CD system could also push commit status to Gitea.

Thanks for the fast reply, but the fact that it results in a 404 page, you don't consider this as a bug?
Also can you check that the commit status is from Gitea Actions specifically, and if so, disable the status?

**Comment by lunny** [comment]
> > Commits status is not a part of Actions. All other CI/CD system could also push commit status to Gitea.
> 
> 
> 
> Thanks for the fast reply, but the fact that it results in a 404 page, you don't consider this as a bug?
> 
> Also can you check that the commit status is from Gitea Actions specifically, and if so, disable the status?

It's also GH did. If drone CI server or jenkins is down, the links in GH is still unavailable. And for Gitea Actions we may do something but currently no column can indicate a commit status comes from.

**Comment by theoludwig** [comment]
Closing as this is not considered an issue.
