### ISSUE TITLE
Unable to add issues to user level project

### ISSUE THREAD

**Issue by balki** [go-gitea/gitea#26189]
### Description

I created a user project from `https://try.gitea.io/<username>/-/projects -> New Project`. However I don't see how to add issues to this project. Tried few things.

1. From projects page `https://try.gitea.io/<username>/-/projects/<project_id>`, don't see any option to add issue 
2. Created an issue in of the repository. Create page `https://try.gitea.io/<username>/<repo_name>/issues/new has a 'Projects' setting on the setting. But don't see the user project in this list. 
3. Project does not show up in issue listing page or the issue page
4. Tried assigning the project to the user and still don't see any option to add to a user project.

Is there any way other way to use the user project ?

Link: https://try.gitea.io/balki/-/projects/3724

### Gitea Version

1.21.0+dev-408-geaea530d6

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

https://try.gitea.io/

### Database

None

**Comment by CaiCandong** [comment]
1. It is not available to create an issue directly for user/organization level projects, but you can bind it to a project on the issue page. 
1. The bug that prevented the display of user-level items was fixed at https://github.com/go-gitea/gitea/pull/26198.
![gif](https://github.com/go-gitea/gitea/assets/50507092/90a98522-dc99-4752-8bc3-6588cc9b5fe3)

**Comment by balki** [comment]
Awesome! Thanks!

**Comment by balki** [comment]
> @[lunny](https://github.com/lunny) lunny added this to the [1.20.3](https://github.com/go-gitea/gitea/milestone/146) milestone [Jul 29, 2023](https://github.com/go-gitea/gitea/issues/26189#event-9953954541)

Looks like it didn't make it to the 1.20.3 release.
```
❯ git log --grep "26189" v1.20.3

```
