### ISSUE TITLE
Release attachments remain on disk after deleting the release

### ISSUE THREAD

**Issue by thmo** [go-gitea/gitea#2618]
- Gitea version (or commit ref): 1.2.0+rc3 
- Git version: 2.11.0
- Operating system: Debian GNU/Linux 9 (stretch)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite

## Description
When deleting a release, the files attached to this release are not deleted from the `data/attachments` folder of Gitea.

**Comment by adelowo** [comment]
___Unstale___

>  good bot

**Comment by rakshith-ravi** [comment]
Quick question: If I have deleted some releases with attachments earlier, how do I remove them from disk as of now? Is there any way to "clean" the attachments folder?

**Comment by lunny** [comment]
Currently no tool to do that and I think we need a tool to clean that on admin panel or command line.

**Comment by adelowo** [comment]
I should find time to complete https://github.com/go-gitea/gitea/pull/6068

**Comment by zhanhb** [comment]
IMO, when editing release draft, the uploaded attachment should be appeared in the list.
I want to know if I'm right if the api become stable?
