### ISSUE TITLE
[Documentations] Act Runner - Add systemd service example for daemon

### ISSUE THREAD

**Issue by sgabenov** [go-gitea/gitea#26205]
### Feature Description

Please, add to documentation part, how to run act runner as a linux service.

I assume this could be something like:

Create service file in `/lib/systemd/system/act_runner.service`
```
[Unit]
Description=Gitea act_runner daemon
After=network.target

[Service]
Environment=HOME=/root
WorkingDirectory=/root
Type=simple
ExecStart=/usr/bin/act_runner daemon

[Install]
WantedBy=multi-user.target
```
Run commands: 
`systemctl enable act_runner.service ; systemctl start act_runner.service`

**Comment by jasonestewart** [comment]
Just make sure that you set WorkingDirectory to the directory that you have put the .runner file

**Comment by nodiscc** [comment]
I think this is already fixed in https://github.com/go-gitea/gitea/pull/27844

https://docs.gitea.com/next/usage/actions/act-runner#systemd-service
