### ISSUE TITLE
[performance] Listing repositories is slow

### ISSUE THREAD

**Issue by KazzmanK** [go-gitea/gitea#26227]
### Description

Request to 
/repo/search?sort=updated&order=desc&uid=3&team_id=undefined&q=&page=1&limit=100&mode=&archived=false

on dashboard page (http://root_path), right pane, takes almost 5 seconds for 50 repositories exists

Database - sqlite

At the same time same repository list on http://root_path/organization appears instantly
### Screenshots

none

### Gitea Version

1.20.1

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

Windows server 10.0

### Browser Version

113

**Comment by KazzmanK** [comment]
Oh, looks like for every repo 3 git commands are executed. Looks like information from database is not sufficient to display repo list. But in Json returned by rest method seems does not contains any special  data.

**Comment by KazzmanK** [comment]
It is not clear, why here, in "https://root_path", after "SearchRepositoryByCondition" git commands are executed, but on "https://root_path/Organization" after the same "SearchRepositoryByCondition" - no git commands are executed and pageload is instant.

**Comment by lunny** [comment]
This issue comes from #24638 in v1.20 and should be resolved by #22743 in v1.21

**Comment by Sebazzz** [comment]
Yes, I also ran into this after upgrading v1.19 to v1.20.4. Glad a fix is inbound!

**Comment by lunny** [comment]
I think this has been resolved. Please feel free to reopen if it is still a problem.

**Comment by Sebazzz** [comment]
Yes, though also simply reorganizing indices in MSSQL also helped!
