### ISSUE TITLE
Some endpoints ignore specified account and use auth account instead

### ISSUE THREAD

**Issue by lonix1** [go-gitea/gitea#26234]
### Description

Reproduction:
- I created an access token at the `/api/v1/users/bob/tokens` endpoint, using basic auth with my `admin` account.
- I expected the access token to be created for `bob`, but it was actually created for `admin`.
- the same is true for other related endpoints

This was **very** surprising and took a while to debug. Is it a bug or by design?

If it's a bug (I think it is), then this issue will track it.

If it's by design:
- It's common to use an admin account to interact with an app, even when managing other users' accounts. So this behaviour is very surprising.
- I specified that I wanted to act on the `bob` account, not the `admin` account.
- If this cannot be fixed/changed, then at least those API endpoints should return errors. If it will ignore the account that I specified and use the authenticating account instead, it must return an error rather than perform an action I didn't request.
- The docs should reflect this weird behaviour (I looked but couldn't find anything).

Thanks!

### Gitea Version

1.20.2

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

n/a

### Screenshots

n/a

### Git Version

n/a

### Operating System

n/a

### How are you running Gitea?

docker

### Database

None

**Comment by CaiCandong** [comment]
I think the current api is ambiguous, it doesn't make sense for one user to manipulate another user's token (unless that user is an admin)
1. I think the current `/api/v1/users/{username}/tokens` should be changed to `/api/v1/user/tokens`.(Users manipulate their own tokens)
1.  And the admin manipulate `token`  should be placed in: `/api/v1/admin/users/{username}/{token}`.(Adm manipulate user's tokens)

**Comment by CaiCandong** [comment]
> * keep the old endpoints, for now, but mark them as deprecated.

We give a permission error if the `{username}` in `path` does not match the currently logged in user? Prompting the user that they should use `/api/v1/admin/users/{username}/tokens` to complete the action?

**Comment by CaiCandong** [comment]
> But what about the admin user? He should be able to operate on another user's account.

The admin user should use `/api/v1/admin/users/{username}/tokens` to accomplish this.  Manipulating other people's tokens should only be done by administrators. 
I see that `{username}` is not considered in the implementation of this endpoints , so perhaps it was misplaced to begin with, causing the current misunderstanding. This endpoints  is not meant to manipulate other user tokens.  We should dispel this misunderstanding, not go along with it and modify it.

**Comment by CaiCandong** [comment]
> (Just keep in mind it's a breaking change, both for those who were using the API correctly and for those who weren't.)

People who want to use this endpoints to enable `token` modification operations by admin will encounter the same confusion as you.  Those who use it correctly will not be affected by this modification.

**Comment by CaiCandong** [comment]
> The point is it will break existing integrations

The changes I've made are guaranteed compatibility  https://github.com/go-gitea/gitea/pull/26323

**Comment by techknowlogick** [comment]
The creation of tokens via API is purposefully limited to non-app tokens because otherwise if an app token is leaked then it could be used to have a chain attack and have new tokens created to maintain access from a malicious user.

**Comment by CaiCandong** [comment]
> The creation of tokens via API is purposefully limited to non-app tokens because otherwise if an app token is leaked then it could be used to have a chain attack and have new tokens created to maintain access from a malicious user.

Yes, I noticed that token manipulation can only be done using `basic Auth` authentication. I'm wondering if gitea's current design allows administrators to manipulate ordinary users' tokens via the API. It seems to me that there are security and privacy issues with this as well, but @lonix1's desire for such an interface seems a bit unreasonable to me right now.

**Comment by waTeim** [comment]
What's happening with this?  I'm experiencing the problem explained in this bug.  There was a PR to fix this apparently (#26323), but it was abandoned, why?

**Comment by CaiCandong** [comment]
> but it was abandoned, why?

No one Reviewed it for a long time, so I closed it. I'm turning it back on now.

**Comment by waTeim** [comment]
Well, I'm confused now.  From the title of the merged PR, it appears that a fix is to remove the ability to specify the user in the path because it gets ignored; so the fix is to make the path consistent with that notion.  My objective is to use the admin account to obtain a token to become a user for purposes of forking a repo.  Embedded in the discussion, there's some sort of `sudo` functionality on (some of) the paths?  Is that documented somewhere?

**Comment by CaiCandong** [comment]
@waTeim @lonix1 
Now the endpoints mean that the `doer` operates on the `contextUser`'s token.
- If the `doer` and the `contextUser` are the same user, the operation will succeed.
- If the `doer` is an administrator, the operation will work.
- But if the `doer` is an ordinary user, his operation on the other `contextUser` will be rejected.

**Comment by waTeim** [comment]
Got it, so in scenario 2, what is the mechanism for the admin (doer) to set the contextUser to some arbitrary other user?

**Comment by CaiCandong** [comment]
> Got it, so in scenario 2, what is the mechanism for the admin (doer) to set the contextUser to some arbitrary other user?

I'm sorry, I don't quite understand your question.

**Comment by CaiCandong** [comment]
> I think I opened a can of worms when I opened that issue, and the new code and discussions were so complicated that I couldn't understand / follow any longer.

The discussion clarifies whether it is necessary to split this endpoint into two parts: normal user operations and administrator operations.

**Comment by waTeim** [comment]
In other words, what forces ContetUser != Doer, what sort of difference in the REST endpoint call is needed?

**Comment by CaiCandong** [comment]
> In other words, what forces ContetUser != Doer, what sort of difference in the REST endpoint call is needed?

Doer represents the user who provided the account and password, which is the user in basicAuth.
ContextUser represents the path in the URL path.
Doer applies an action to ContextUser.

**Comment by waTeim** [comment]
Ok so if this change is to remove user from the path, will ContextUser ever be different from Doer?

**Comment by CaiCandong** [comment]
But the `contextUser` is not removed from the path.

**Comment by waTeim** [comment]
oh, my bad, I misinterpreted the discussion, then.  I thought you had opted to remove it.

**Comment by waTeim** [comment]
I think so?  I'll modify my code, remove the workaround, re-test, and report back. Is there already a container image that has the change, or do I need to compile, etc, I've just been using 1.20.4 (feel free to point me to docs).
