### ISSUE TITLE
New pushed branches show up after migration

### ISSUE THREAD

**Issue by yardenshoham** [go-gitea/gitea#26239]
### Description

![image](https://github.com/go-gitea/gitea/assets/20454870/806cdf43-6aea-45d8-98cd-121b2b407b24)

### Gitea Version

4244ce0 (current main)

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

Gitpod

### Database

SQLite

**Comment by lunny** [comment]
So, pull mirrors and migrated repositories should not prompt the branches pushed.

**Comment by lunny** [comment]
For migrated repositories, it's difficult to say the prompt is wrong.

**Comment by cassiozareck** [comment]
May the error lies in the fact unix times aren't being preserved at the database?

<img src="https://github.com/go-gitea/gitea/assets/121526696/29078fb8-2260-4c0c-ae53-527c1e1c9b9d" width="500">

This is the exact time the migration was made, not the original time the push was made at the original repo. So perhaps this is why `FindRecentlyPushedNewBranches` is considerating it

**Comment by Zettat123** [comment]
In my opinion,
- for mirror repos, we should not show the prompt 
- for the repos with pull request units disabled, we should not show the prompt 
- for migrated repositories, I think we can keep the prompt as it might be useful sometimes

**Comment by yardenshoham** [comment]
Agree with the first 2.

In migrated repositories, don't show it until the first commit after the migration

**Comment by lunny** [comment]
> > May the error lies in the fact unix times aren't being preserved at the database?
> > <img alt="" width="500" src="https://user-images.githubusercontent.com/121526696/257093566-29078fb8-2260-4c0c-ae53-527c1e1c9b9d.png">
> > This is the exact time the migration was made, not the original time the push was made at the original repo. So perhaps this is why `FindRecentlyPushedNewBranches` is considerating it
> 
> Yes, the `created_unix` is the time when create the record. Maybe we should check `commit_time` in `FindRecentlyPushedNewBranches`

Yes, we should use `commit_time` really.

**Comment by Zettat123** [comment]
> In my opinion,
> 
> * for mirror repos, we should not show the prompt
> * for the repos with pull request units disabled, we should not show the prompt
> * for migrated repositories, I think we can keep the prompt as it might be useful sometimes

By using `commit_time`, only prompts of newly pushed branches will be displayed for migrated repos. I think it could help solve this issue.
