### ISSUE TITLE
Wrong markdown spacing for sublists

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#2623]
- Git version: 1.2.0+rc3
- Operating system: Ubuntu 16.04
  - [x] MySQL

## Description
When inserting text into the wiki the bullet list adds a white a white line above a sub point and none below before the next parent point.

however subpoints of subpoints seem to behave as expected
```
- all our automations, configuration pushes and processes used here will be open, transparent and agreed upon

- automated ansible transaction logs from us will be on both department's endpoint and our anisible servers central log system
    - clients will be able to verify our actions

- auth intrusion detection compliance
    - immediately fail2ban and system login intrusion detection for login & sshd shell enabled accounts
    - cetral log system will be able to engage perimeter firewall rules
        - login banner for shell access enabled account warning for private property


- system login alogrythm compliance
    - require pam, sshd.conf, sshd.conf, sssd.conf/LDAP, faile2ban(conf.d), etc.
```

## Screenshots

![gitea_wiki_lists](https://user-images.githubusercontent.com/1158515/31000523-05d23664-a491-11e7-8741-452b622fa329.png)

**Comment by ghost** [comment]
is there a good document for the markdown that gitea's wiki uses?

**Comment by sondr3** [comment]
Are you sure this isn't just a CSS/HTML issue? If you have a working example on try.gitea.io I could take a look.

**Comment by krrutkow** [comment]
I came across this markdown problem today, so I created an example: 
https://try.gitea.io/krrutkow/markdown-list-rendering/wiki/raw/Home
which renders as:
https://try.gitea.io/krrutkow/markdown-list-rendering/wiki/Home

**Comment by thehowl** [comment]
Yes - it looks like in the first case the `<p>` is not generated and in the second case it is, probably because it detects a newline afterwards. Need to investigate if this is an error on our side or if we need to report this upstream to blackfriday.

![image](https://user-images.githubusercontent.com/4681308/35590306-b488988e-0606-11e8-89e7-87b4c87fafa3.png)

**Comment by wxiaoguang** [comment]
![image](https://user-images.githubusercontent.com/2114189/163102475-edd77ee9-d492-498c-8b24-37bee59074e5.png)

It seems fine now. There were some PRs about the markdown layout fixes.
