### ISSUE TITLE
Matrix icon is broken (HTTP 404) on Matrix webhook page

### ISSUE THREAD

**Issue by CodeShakingSheep** [go-gitea/gitea#26241]
### Description

When going to `/user/settings/hooks/matrix/new` to create a new webhook for Matrix the Matrix icon in the right top corner is broken. This is due to the matrix icon not being present under `/assets/img/matrix.svg`. I figured there is another matrix SVG file present here instead `/assets/img/svg/gitea-matrix.svg`. This could be referenced instead.

The issue is also reproducible on Gitea demo site. See here: https://try.gitea.io/user/settings/hooks/matrix/new 
- https://try.gitea.io/assets/img/matrix.svg returns HTTP 404
- https://try.gitea.io/assets/img/svg/gitea-matrix.svg returns HTTP 200

### Screenshots

Screenshot from my Gitea instance:
![image](https://github.com/go-gitea/gitea/assets/19874562/6881dcb1-84cc-440c-aaa7-ce454719f995)

Screenshot from browser console:
![image](https://github.com/go-gitea/gitea/assets/19874562/0102ef9f-10e6-4eeb-b175-b198f1725ef6)

### Gitea Version

1.20.1

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

Windows 10

### Browser Version

Brave 1.56.14 (Chromium 115.0.5790.114)

**Comment by silverwind** [comment]
https://github.com/go-gitea/gitea/pull/26242 will fix it and use a much-needed shared template.
