### ISSUE TITLE
How to use protected meilisearch instance?

### ISSUE THREAD

**Issue by erhaone** [go-gitea/gitea#26255]
### Description

ISSUE_INDEXER_CONN_STR = "http://xxxx.7700"

when my meilisearch is set master key, gitea can't startup successfully.I want to set api key in app.ini，but i don't know where should i set api key.

meilisearch doc suggest request with auth like this:
curl \
  -X GET 'http://localhost:7700/keys' \
  -H 'Authorization: Bearer MASTER_KEY'

Unable to issueIndexer.Init with connection http://172.29.158.11:7700 Error: unaccepted status code found: 401 expected: [202], MeilisearchApiError Message: The Authorization header is missing. It must use the bearer authorization method., Code: missing_authorization_header, Type: auth, Link: https://docs.meilisearch.com/errors#missing_authorization_header (path "POST /indexes" with method "CreateIndex")

### Gitea Version

1.20.2

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

run from docker

### Database

MySQL

**Comment by techknowlogick** [comment]
Under `ISSUE_INDEXER_CONN_STR`, you would have `http://:apikey@localhost:7700` as it works with HTTP basic auth (note the `:` right before the API key in the URL`

**Comment by simahao** [comment]
> Under `ISSUE_INDEXER_CONN_STR`, you would have `http://:apikey@localhost:7700` as it works with HTTP basic auth (note the `:` right before the API key in the URL`

Thinks.
