### ISSUE TITLE
External tracker url didn't work on main page

### ISSUE THREAD

**Issue by Borisskin** [go-gitea/gitea#26251]
### Description

External tracker url didn't work on main page (with changes in all repo). But the url is exist in commit .

### Gitea Version

1.20.2

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

https://try.gitea.io/borisskin/repo_bp

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/3109197/144f6543-77c4-42b5-9aa9-b668bf27949a)
![image](https://github.com/go-gitea/gitea/assets/3109197/a0f0c656-b345-45f0-af68-9d5c75a21683)

### Git Version

2.41.0.windows.3

### Operating System

Windows Server 2016 Datacenter

### How are you running Gitea?

windows service (self-hosted Git service)

### Database

MSSQL

**Comment by puni9869** [comment]
I got this via visiting this
![image](https://github.com/go-gitea/gitea/assets/80308335/a79d2088-1e12-4c5b-a834-04b4571344c2)

**Comment by Borisskin** [comment]
> I got this via visiting this 

It's internal service our tracker. This page is opened in the local network.
![image](https://github.com/go-gitea/gitea/assets/3109197/54bf9418-4eff-41b4-964d-616d9295a1bc)

**Comment by Borisskin** [comment]
> sorry for this iterative question, whats the url you are redirecting to, is it html encoded url.
> 
> PS: I just want to understand the problem

the settings of internal gitea service is same on try.gitea and presents on picture
![image](https://github.com/go-gitea/gitea/assets/3109197/64d968ef-2733-4b14-b53b-616aabd35905)

**Comment by puni9869** [comment]
@wxiaoguang need your feedback, I am unable to repro it.
👀

**Comment by wxiaoguang** [comment]
The commit message is not rendered that way in the home's activity list.

Even you try to mention internal issues (without external URL) like `#1` or `#2`, it doesn't render either.

**Comment by Borisskin** [comment]
Thanks for the help. So I was misled that this functionality was implemented in previous releases.

**Comment by Borisskin** [comment]
Not bug

**Comment by lunny** [comment]
Sorry, I think maybe the rendering in the main page is not that important?
