### ISSUE TITLE
Found a way to break all repositories inside a gitea instance

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#26264]
### Description

The task "Delete all repositories' archives (ZIP, TAR.GZ, etc..)" corrupts all git repositories.
One of the deleted files are the HEAD files at the root of one repository.
I send the screenshot of the error message of the ui

### Gitea Version

1.20.2

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/26299054/34e379f8-6163-42da-80b9-ce4feeb73831)

### How are you running Gitea?

It is running from the official docker image

### Database

MySQL

**Comment by CaiCandong** [comment]
Please tell me how to reproduce this problem, I tried "Delete all repositories' archives (ZIP, TAR.GZ, etc...)" . There is no problem as you said.
![image](https://github.com/go-gitea/gitea/assets/50507092/39b90f4f-7867-43c5-a20d-4d69f6254255)

**Comment by deimosOmegaChan** [comment]
I did exact the same step but I got the issue.
I don't know yet how to reproduce the problem.
There are no error messages in the logs.

**Comment by wxiaoguang** [comment]
What's your `app.ini`? Especially the storage path related options.

**Comment by deimosOmegaChan** [comment]
Here is all the parts of the app.ini file, which have a path.
```
WORK_PATH = /data/gitea
[repository]
ROOT = /data/git/repositories
[repository.local]
LOCAL_COPY_PATH = /data/gitea/tmp/local-repo

[repository.upload]
TEMP_PATH = /data/gitea/uploads

[server]
APP_DATA_PATH = /data/gitea

[storage]
STORAGE_TYPE = local
PATH = /data/git

[indexer]
ISSUE_INDEXER_PATH = /data/gitea/indexers/issues.bleve

[session]
PROVIDER_CONFIG = /data/gitea/sessions
PROVIDER = file

[picture]
AVATAR_UPLOAD_PATH = /data/gitea/avatars
REPOSITORY_AVATAR_UPLOAD_PATH = /data/gitea/repo-avatars

[attachment]
PATH = /data/gitea/attachments

[log]
ROOT_PATH = /data/gitea/log
MODE = file
```
Would that help?

**Comment by wxiaoguang** [comment]
The problem is 

```
[storage]
STORAGE_TYPE = local
PATH = /data/git
```

The INI package has a quirk behavior: the path is inherited, so `storage.repo-archive` also uses path `/data/git`

Then everything is removed under the `/data/git`

Related to : Fix all possible setting error related storages and added some tests (#23911)

@lunny
