### ISSUE TITLE
500 error, Unable to view organisation Dashboard when using MSSQL.

### ISSUE THREAD

**Issue by sgtwilko** [go-gitea/gitea#2626]
- Gitea version (or commit ref): `1.2.0+rc1-6-g002fa73 built with: bindata, sqlite`
- Git version: `2.14.1.windows.1`
- Operating system: `Windows Server 2008R2`
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant (I did try but couldn't replicate because try.gitea.io probably isn't using MSSQL for the database)

- Log gist:

`[...routers/user/home.go:137 Dashboard()] [E] env.MirrorRepos: MirrorRepoIDs: mssql: Column "repository.updated_unix" is invalid in the ORDER BY clause because it is not contained in either an aggregate function or the GROUP BY clause.`

## Description
When changing to view an organisation dashboard you receive a 500 error.

## Screenshots
![image](https://user-images.githubusercontent.com/658876/31009798-917833c0-a500-11e7-8fec-6b2b47aa6d05.png)

**Comment by ethantkoenig** [comment]
I believe this has already been fixed: https://github.com/go-gitea/gitea/pull/2504

**Comment by sgtwilko** [comment]
Sorry for reporting a duplicate, I did search the issues before posting, but not the pull requests.

I've just upgraded to 1.2.0+rc3-4-g5b36379 which still has this issue, any idea if this fix make it into the final 1.2.0?

**Comment by lafriks** [comment]
@sgtwilko yes this fix will be backported to 1.2 branch

**Comment by lafriks** [comment]
Backport submitted as PR #2662

**Comment by lafriks** [comment]
Fixed with #2662
