### ISSUE TITLE
Use join for the deleting issue actions query

### ISSUE THREAD

**Issue by otbutz** [go-gitea/gitea#26277]
### Description

Our current DELETE query for actions is rather inefficient on MariaDB:

```sql
DELETE FROM action WHERE comment_id IN (SELECT id FROM comment WHERE issue_id=?)
```

https://github.com/go-gitea/gitea/blob/ab388deb0e52c058a19dbd844bdd890f7cf84d51/models/activities/action.go#L688-L702

Caused by https://jira.mariadb.org/browse/MDEV-16289

see https://codeberg.org/forgejo/forgejo/issues/1161 and https://codeberg.org/forgejo/forgejo/pulls/1165

### Gitea Version

1.20.2

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

Binary started via systemd behind a caddy reverse proxy.

### Database

None

**Comment by wxiaoguang** [comment]
Thank you for the report.

The referred fix on codeberg seems not good enough (eg: the test doesn't cover other databases).

I proposed a new fix: Bypass MariaDB performance bug of the "IN" sub-query #26279

**Comment by lunny** [comment]
The main problem is `comment_id` in `action` table is not an index column.

**Comment by wxiaoguang** [comment]
![image](https://github.com/go-gitea/gitea/assets/2114189/125cd3ce-33f0-47ad-9332-bf3ca2f1d869)

**Comment by lunny** [comment]
OK. I see, it's MariaDB's problem.
