### ISSUE TITLE
Feature: Add Comments for Commit

### ISSUE THREAD

**Issue by LamGC** [go-gitea/gitea#26288]
### Feature Description

Add comments to the commit, allowing users and Bots (accessing as users as there are currently no Bot Accounts) to comment on the commit.

For users, it is possible to discuss or raise questions for Commit. For Bots, the execution results of the automated process of Commit can be published through Comments.

A good example is that Vercel will post a comment for a commit to inform whether it has been successfully deployed to Vercel and provide relevant information after successful deployment (such as preview URL, partial information during deployment, etc.)

### Screenshots

Example commit: https://github.com/LamGC/github-readme-stats_self-hosted/commit/6707f34134b9e10ce3782985c6c4786be9faf605

ScreenShot:  

![image](https://github.com/go-gitea/gitea/assets/16975255/26c3446c-d9e5-4193-84a3-6f21967dcfc6)

**Comment by lunny** [comment]
duplicated with #4898
