### ISSUE TITLE
1.20.2:  hang when branch protections enable "Dismiss stale approvals" 

### ISSUE THREAD

**Issue by msantos** [go-gitea/gitea#26280]
## Process
* upgrade to gitea 1.20.2
* enable branch protections and enable "Dismiss stale approvals"
* enable Actions
* open a PR
* have a reviewer approve the PR
* push a commit to the PR
* the gitea instance hangs when running the Actions

## Logs
```
2023/08/01 13:16:34 ...eb/routing/logger.go:102:func1() [I] router: completed POST /api/actions/runner.v1.RunnerService/UpdateLog for 1.2.3.4:56296, 200 OK in
 25.5ms @ <autogenerated>:1(http.Handler.ServeHTTP-fm)
2023/08/01 13:16:34 ...eb/routing/logger.go:102:func1() [I] router: completed POST /api/actions/runner.v1.RunnerService/UpdateTask for 1.2.3.4:56296, 200 OK i
n 33.0ms @ <autogenerated>:1(http.Handler.ServeHTTP-fm)
2023/08/01 13:16:39 ...eb/routing/logger.go:68:func1() [W] router: slow      POST /api/actions/runner.v1.RunnerService/FetchTask for 5.6.7.8:46342, elapsed 32
44.4ms @ <autogenerated>:1(http.Handler.ServeHTTP-fm)
2023/08/01 13:16:39 ...eb/routing/logger.go:68:func1() [W] router: slow      POST /api/actions/runner.v1.RunnerService/UpdateLog for 1.2.3.4:56296, elapsed 3133.4ms @ <autogenerated>:1(http.Handler.ServeHTTP-fm)
...
2023/08/01 13:17:47 ...queue/workergroup.go:290:func1() [E] Queue "pr_patch_checker" is shutting down, but workers are still running after timeout
2023/08/01 13:17:47 ...queue/workergroup.go:290:func1() [E] Queue "notification-service" is shutting down, but workers are still running after timeout
```

## Fix
Either:
* downgrade to gitea 1.20.1
* disable "Dismiss stale approvals" from branch protections

Possibly related to https://github.com/go-gitea/gitea/pull/25882

### Gitea Version

1.20.2

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

git version 2.25.1/git version 2.40.0

### Operating System

Tested on Linux and FreeBSD

### How are you running Gitea?

Dowloaded from github releases running using systemd.

### Database

SQLite

**Comment by lunny** [comment]
I cannot get any clue from your logs. Can you give more information?

**Comment by msantos** [comment]
@lunny demo in https://try.gitea.io/msantos/test/pulls/1

try.gitea.io is unresponsive at the moment. Pushing additional commits to the PR is hanging:

```
$ git remote get-url origin
https://try.gitea.io/msantos/test.git
$ git commit -a
[test cb6fe14] README: update
 1 file changed, 1 insertion(+)
$ git push origin test
<hangs>
```
