### ISSUE TITLE
Assign reviewers on pull request creation

### ISSUE THREAD

**Issue by splitt3r** [go-gitea/gitea#26289]
### Feature Description

The pull request creation dialog currently misses the reviewers slection. You can only select an assinngee while creating a pull request. After creating the pull request and opening it you can select the reviewer for it. GitHub allows you to assign the pull request diretly to a reviewer while creating it which is pretty neat. It makes the workflow of suggesting changes for a repo more convenient.

### Screenshots

GitHub:
![GitHub](https://github.com/go-gitea/gitea/assets/1869584/0ebf8542-4db1-4d15-bdb2-94a3dee4518d)

Gitea:
![Gitea](https://github.com/go-gitea/gitea/assets/1869584/73fd799a-c7d4-406a-9bcd-170454e2a6ad)

**Comment by lunny** [comment]
duplicated with #13905

**Comment by delvh** [comment]
Sure. All issues are open for PRs.

**Comment by lunny** [comment]
If the pull request creator indicated the reviewers, the codeowner reviewers should be ignored.

**Comment by CalK16** [comment]
Hi, I'd like to make my contribution to this issue. Is it still open to PRs?

**Comment by lunny** [comment]
> > Hi, I'd like to make my contribution to this issue. Is it still open to PRs?
> 
> Since my pr is abadoned and i don't have the time to work on it anymore it would be great if you could fix the issue.

It was almost completed for me when I last reviewed it.

![图片](https://github.com/user-attachments/assets/e168e75c-cdba-41b6-8a85-2a50cf01638e)
