### ISSUE TITLE
Can't delete refs/remote/origin/branch 

### ISSUE THREAD

**Issue by LanaYuan** [go-gitea/gitea#2629]
- Gitea version (or commit ref): 1.2.0+rc3
- Git version: 2.14.1 
- Operating system: amd64
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description
I think only the protected branch can't be deleted .
But I can't delete refs/remote/origin/branch, when the branch didn't be protected.
I tried at https://try.gitea.io, it can be deleted.
And I also tried at https://try.gitea.io , I protected the branch and then deleted   refs/remote/origin/branch, the result is I deleted it successfully and the branch manage page got HTTP ERROR 500.

## Screenshots
![default](https://user-images.githubusercontent.com/30920949/31044143-6e6209e0-a5fc-11e7-9c34-24bc8391a3c3.PNG)

**Comment by lafriks** [comment]
Should be fixed with #2630
