### ISSUE TITLE
Debian registry: Reading package lists... Error!

### ISSUE THREAD

**Issue by podsvirov** [go-gitea/gitea#26313]
### Description

I was create Debian packages as described [there](https://github.com/sewenew/redis-plus-plus#building-a-redis-plus-plus-debian-package-optional), and then upload it to registry at Gitea demo site [there](https://try.gitea.io/podsvirov/-/packages/debian/libredis++-dev/1.3.10). I also reproduse this error at my Gitea instanse version `1.20.2`.

But when I try to setup this registry from the command line, I get the error:

```shell
Reading package lists... Error!
E: Encountered a section with no Package: header
E: Problem with MergeList /var/lib/apt/lists/try.gitea.io_api_packages_podsvirov_debian_dists_ubuntu_jammy_binary-amd64_Packages.lz4
E: The package lists or status file could not be parsed or opened.
```

Looks like Gite generate extra empty line inside `Package` file inside `Package` description block.

I guess the source of the error in the code is [here](https://github.com/go-gitea/gitea/blob/d74c2228e3f93de502aa37095a00421ca67c4ca9/services/packages/debian/repository.go#L215).

### Gitea Version

1.20.2

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

The docker container from image gitea/gitea:1.20.2 on Ubuntu host via docker-compose.

### Database

SQLite

**Comment by KN4CK3R** [comment]
Thank you for the report. That's the first debian package I got which has a double newline character at the end of the control block. I will send a fix soon.

**Comment by podsvirov** [comment]
Thanks for quick fix! 🥳
