### ISSUE TITLE
Collaborator who is not member of private org cannot `docker push $image` to org registry

### ISSUE THREAD

**Issue by bf** [go-gitea/gitea#26311]
### Description

- create user A
- user A creates organization $org
- organization $org creates repository $repo
- user A adds user B as "callaborator" with "read/write" to repository $repo, but not to the org $org
- user B creates new token $token in /user/settings/applications with "read/write" permission for "packages"
- repository $foo has action that does `docker login --username "user B" --password $token` and `docker push --tag gitea-instance.com/$org/mycontainername`
- `docker login` works as "user B" but `docker push` gives "unauthorized: authentication required"

How can "User B" push a docker container to container registry at gitea-instance.com/$org/containername if "User B" is not member of $org but only read/write collaborator of $repo which is in $org?

### Gitea Version

1.21.0+dev-437-gb9baed2c74

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

arch

### How are you running Gitea?

natively via archlinux AUR package gitea-git

### Database

SQLite

**Comment by bf** [comment]
Part of the problem might be that "User B" collaborator to $repo in $org cannot access the "Packages" link on the top of the $repo website. The URL `gitea-instance.com/$org/-/packages/container/containername` gives '404 The page you are trying to reach either does not exist or you are not authorized to view it.' even though "User B" is collaborator of $repo AND $containername has been linked to $repo which is in $org..

**Comment by KN4CK3R** [comment]
Repositories are not relevant when resolving package permissions. If the user has no write permissions for the package owner, they can't push images.

**Comment by bf** [comment]
Ok found a workaround:

- add new "team" to org with `repository access: specific repositories` and permission `packages: write` and everything else on `deny`
- add "User B" to the new team
- add $repo to the new team

Then "User B" can push to org package repository as expected.

![Screenshot from 2023-08-03 21-17-40](https://github.com/go-gitea/gitea/assets/464537/ac813339-9272-40f8-bdfb-bfc21711906a)

Closing as workaround works for me.
