### ISSUE TITLE
css bug in /$org/-/packages/container/$foo/latest/settings

### ISSUE THREAD

**Issue by bf** [go-gitea/gitea#26310]
### Description

go to: /$org/-/packages/container/$foo/latest/settings to see that the css is broken

open your organization page -> packages -> select package -> click on settings in bottom right corner -> see broken red box

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/464537/2fc1bb4a-93e8-4e4b-8996-de85ade6a90e)

### Gitea Version

1.21.0+dev-437-gb9baed2c74

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

arch

### Browser Version

chrome

**Comment by KN4CK3R** [comment]
Must be a regression, was fine [a month ago](https://github.com/go-gitea/gitea/issues/25559#issuecomment-1613315628)

**Comment by bf** [comment]
Seems to me the `<div class='item'>` should be removed

![image](https://github.com/go-gitea/gitea/assets/464537/112a11b5-0860-4ac3-a21c-0cc800d71190)

**Comment by bf** [comment]
This line needs to be changed. Not sure if CSS class item is needed for the ui-right part:
https://github.com/go-gitea/gitea/blob/main/templates/package/settings.tmpl#L42C3-L42C22

**Comment by KN4CK3R** [comment]
It's a regression of #25790. I will send a fix PR.
