### ISSUE TITLE
detect force push failure on deletion of protected branches

### ISSUE THREAD

**Issue by daviian** [go-gitea/gitea#2631]
- Gitea version (or commit ref): 26e49b8 
- Git version: 2.7.4
- Operating system: Windows 10
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL) https://try.gitea.io/dschneiderbauer/awsiotgg (trying to delete `develop` branch)
  - [ ] No
  - [ ] Not relevant
- Log gist:
```
Username for 'https://try.gitea.io': dschneiderbauer
Password for 'https://dschneiderbauer@try.gitea.io':
remote: Gitea: Internal error
remote: Fail to detect force push: exit status 128 - fatal: bad object 0000000000000000000000000000000000000000
remote:
To https://try.gitea.io/dschneiderbauer/awsiotgg.git
 ! [remote rejected] develop (pre-receive hook declined)
error: Fehler beim Versenden einiger Referenzen nach 'https://try.gitea.io/dschneiderbauer/awsiotgg.git'
```

## Description

Trying to delete a protected branch leads to above error in console.

**Comment by lunny** [comment]
It seems this is solved?

**Comment by daviian** [comment]
@lunny No, I still receive the same error on try.gitea.io
