### ISSUE TITLE
Unable to log out normally

### ISSUE THREAD

**Issue by kerwin612** [go-gitea/gitea#26327]
### Description

After clicking the exit button on the page, the page will be automatically refreshed, and the page will still be in login status, and you cannot log out

### Gitea Version

https://github.com/go-gitea/gitea/commit/907bedaad0301730ee2fbab1f18b54b155dad088

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![111](https://github.com/go-gitea/gitea/assets/3371163/bda6ba04-88d7-4edd-8937-5f5e90a95841)

![image](https://github.com/go-gitea/gitea/assets/3371163/49b404b0-9496-4ad0-9247-fa456f8a9a88)

![image](https://github.com/go-gitea/gitea/assets/3371163/11e0d4c8-9d8d-4aff-8212-c0f88c2a9fe0)

### Git Version

2.25.1

### Operating System

Linux version 5.10.16.3-microsoft-standard-WSL2 (oe-user@oe-host) (x86_64-msft-linux-gcc (GCC) 9.3.0, GNU ld (GNU Binutils) 2.34.0.20200220) #1 SMP Fri Apr 2 22:23:49 UTC 2021

### How are you running Gitea?

From the github checkout main branch, compile(TAGS="bindata sqlite sqlite_unlock_notify" make build) and run(./gitea);

### Database

SQLite

**Comment by kerwin612** [comment]
> > Can you reproduce the bug on the Gitea demo site?
> > Yes
> 
> How to reproduce?

Sorry, I haven't found a 100% replication method yet. The problem is that it happened during my docking with OAuth. I'll look for the replication path again.

**Comment by wxiaoguang** [comment]
You could try to check your cookies.

The "Cookie" header in the request, and the "Set-Cookie" header in the response.

**Comment by liszca** [comment]
> Please open a new issue with reproducible steps.

somehow it solved itself, what I did, I just looked what are the settings needed for ldap, but I didn't save/change anything.
