### ISSUE TITLE
Swagger errors

### ISSUE THREAD

**Issue by ethantkoenig** [go-gitea/gitea#2635]
- Gitea version (or commit ref): 1ad902d5298202d5be14fd5a9c8ed6ce781a23c8
- Git version:
- Operating system:
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

There are errors in our swagger config, see https://online.swagger.io/validator/debug?url=https://try.gitea.io/swagger.v1.json

## Screenshots
![image](https://user-images.githubusercontent.com/8990880/31056478-0f553d60-a687-11e7-808a-ca78c8e6b604.png)

**Comment by sapk** [comment]
That possible ^^. I will try to have a look if no one haven't yet. It should not be blocking to use the interface at https://try.gitea.io/swagger. I should also add other APIs to it to fill empty some generic object definition.

**Comment by ethantkoenig** [comment]
Please reopen, until #2899 is merged
