### ISSUE TITLE
The repository name is incomplete in the Issues page

### ISSUE THREAD

**Issue by CaiCandong** [go-gitea/gitea#26355]
### Description

As title

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/50507092/332e48a2-4033-40c2-baef-e63610908921)
![image](https://github.com/go-gitea/gitea/assets/50507092/6ce67056-b011-44af-81e6-f9211ddf4667)

### Gitea Version

main

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

windows

### Browser Version

chrome

**Comment by CaiCandong** [comment]
fixed by #26354

**Comment by wxiaoguang** [comment]
Duplicate of  Font baseline is misaligned on issues page #25597
