### ISSUE TITLE
500 permission denied on stat of packages and sessions

### ISSUE THREAD

**Issue by vettamatt** [go-gitea/gitea#26359]
### Description

We're running Gitea on Docker, using an NFS mount for /data.
We were using 1.20.2, and we're now using nightly.

For some reason, we see permission denied errors for some files, which cause 500 errors in the web GUI and in response to Docker push.
The most obvious problems are during Docker push, and with user sessions.
If we restart the container, the problem intermittently goes away for hours or overnight, then occurs again.

The owner of /data and beyond is 1000:1000.

Further information: [https://gist.github.com/vettamatt/a6f40f55d2b907986ad5c1e7e96fee24](https://gist.github.com/vettamatt/a6f40f55d2b907986ad5c1e7e96fee24)

### Gitea Version

nightly (Docker Hub) - https://hub.docker.com/layers/gitea/gitea/nightly/images/sha256-ccb7e43c8ae498648582a05d6cde8c14599b573c2efdf8ae6c097039541bd758

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/vettamatt/a6f40f55d2b907986ad5c1e7e96fee24

### How are you running Gitea?

We're running Gitea on Docker, using an NFS mount for /data.
We were using 1.20.2, and we're now using nightly.

### Database

MySQL

**Comment by KN4CK3R** [comment]
I think NFS is the bad boy:
#24684
#22308
#22059

**Comment by emmorts** [comment]
Have you found any solution @vettamatt? I am currently experiencing the same problem on a K8s cluster.

**Comment by lunny** [comment]
The workaround is in #24684
