### ISSUE TITLE
Context deadline exceeded during repo-sync-releases operation

### ISSUE THREAD

**Issue by sad75** [go-gitea/gitea#26394]
### Description

I cannot sync my repositories, Some of them have several thousands of tags:

Error during SyncReleasesWithTags :
```
$ gitea -c /etc/gitea/app.ini admin repo-sync-releases
2023/08/08 10:23:59 cmd/admin.go:382:runRepoSyncReleases() [W]  SyncReleasesWithTags: unable to PushUpdateAddTag:  
... unable to GetTag:
```

I tried to increase timeout. But the issue persists.

```
[git.timeout]
DEFAULT = 36000
MIGRATE = 60000
MIRROR = 30000
CLONE = 30000
PULL = 30000
GC = 6000
```

### Gitea Version

1.20.2

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

git version 2.39.2

### Operating System

linux debian 11.7

### How are you running Gitea?

gitea is a standard downloaded build.

### Database

MySQL

**Comment by wxiaoguang** [comment]
It seems an old problem ... Call git.InitSimple for runRepoSyncReleases #26396

**Comment by sad75** [comment]
I agree that is a duplicate, but the original one is not so old ;-) !

**Comment by sad75** [comment]
Run perfectly
