### ISSUE TITLE
Inform the user about maximum profile picture size.

### ISSUE THREAD

**Issue by ironveil** [go-gitea/gitea#26390]
### Feature Description

I noticed that when you try and set a profile picture that is too big, it comes up with a warning about how it is too big. However, it doesn't actually say how big the maximum file size can be. Is there a way to add the maximum file size onto the prompt?

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/131584614/4bb396ce-62b9-4699-9355-23ac2553bc9e)

**Comment by lng2020** [comment]
Actually, you can config this one, see as https://github.com/go-gitea/gitea/blob/97aa749578a05b207d54dbbcd8580201b5eba359/docs/content/administration/config-cheat-sheet.en-us.md?plain=1#L798
an example here https://github.com/go-gitea/gitea/blob/97aa749578a05b207d54dbbcd8580201b5eba359/custom/conf/app.example.ini#L1784
