### ISSUE TITLE
current version: imagefailed+26-gb842d2a32

### ISSUE THREAD

**Issue by zjjhot** [go-gitea/gitea#26404]
### Description

TAGS=bindata mingw32-make build

When I compiled  gitea, this version number was displayed as  imagefailed+26-gb842d2a32

What is "imagefailed", something wrong with that,

"imagefailed" should be like "1.21.0-dev ....."

### Gitea Version

main branch

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

windows

### Database

None

**Comment by CaiCandong** [comment]
The version number of gitea is generated based on git tags, which you can check with the following command. This is not a problem with gitea:

`git describe --tags --always | sed 's/-/+/' | sed 's/^v//'`

**Comment by zjjhot** [comment]
> The version number of gitea is generated based on git tags, which you can check with the following command. This is not a problem with gitea:
> 
> `git describe --tags --always | sed 's/-/+/' | sed 's/^v//'`

Thank you very much. 
The version displayed correctly after remove my own tag.
