### ISSUE TITLE
OIDC group mappings don't apply at registration

### ISSUE THREAD

**Issue by garymoon** [go-gitea/gitea#26415]
### Description

When a new user signs in/registers via OIDC, team mappings as declared in the authentation source don't take effect on the initial login. They do apply from the second login onward.

I would speculate that it's not a race issue since I can also repro it with email validation enabled.

Using OKTA as the idp.

### Gitea Version

main branch

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

`make watch`

### Database

PostgreSQL

**Comment by kdumontnu** [comment]
Can you please include a brief overview of the steps to follow to reproduce this and include the gitea version number that includes the commit sha?

Also, for traceability, this functionality was first implemented in https://github.com/go-gitea/gitea/pull/21441

**Comment by KN4CK3R** [comment]
I can't reproduce the problem. I used a Keycloak test instance with an additional "groups" mapper. 

Keycloak:
![grafik](https://github.com/go-gitea/gitea/assets/1666336/dd6813e2-4782-44fd-adc3-1d32a78e92da)

![grafik](https://github.com/go-gitea/gitea/assets/1666336/33fcf848-729b-41cf-b25e-3db82c4b8e56)

Gitea:
![grafik](https://github.com/go-gitea/gitea/assets/1666336/d5c3c0b8-2437-4ef9-b3cc-21a755c64d98)

Then I opened `<gitea>/user/login` and used "Sign in with keycloak". This redirects to Keycloak. After the login Gitea presents the "this is your username and password" screen. After that I'm logged in into Gitea and the user has the group membership.


https://github.com/go-gitea/gitea/assets/1666336/ab71a20f-96e0-49f8-9d47-9710e8cc17cd

**Comment by garymoon** [comment]
My apologies, I am not able to reproduce this locally myself :(
