### ISSUE TITLE
Customize Gitea - Service Unavailable & Crashes

### ISSUE THREAD

**Issue by imeidopf** [go-gitea/gitea#26419]
### Description

I created gita/custom/templates/base/head.tmpl which contains the exact same code as the source file. After I restart Gitea, the service starts running but immediately crashes once I try to hit the webpage. This leads to a Service Unavailable page and I lose access to Gitea until I remove/rename the file or the folder.

I don't have any logs, even though it's configured to /home/git/gitea/log.

### Gitea Version

1.20.2

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/10743319/9e8bf954-696f-461b-8886-8e73a8c97d4a)

### Git Version

2.30.2

### Operating System

Raspberry Pi OS Lite (64-Bit)

### How are you running Gitea?

I ran through this tutorial: https://pimylifeup.com/raspberry-pi-gitea/

### Database

MySQL

**Comment by CaiCandong** [comment]
Can you give me a detail step to reproduce the bug ?

**Comment by imeidopf** [comment]
> Can you give me a detailed step to reproduce the bug? 

I'm not entirely certain what more information you need. I provided the link to the tutorial to get it installed on the raspberry pi, which I followed step by step. I said I used the exact same code as in the source file for head.tmpl, along with the path the file was placed.

What other information are you looking for?

**Comment by jolheiser** [comment]
Ensure you're using the template file in the version your release is from, e.g. https://github.com/go-gitea/gitea/blob/release/v1.20/templates/base/head.tmpl
