### ISSUE TITLE
Test failure: Race detected in `TestGit/SSH`

### ISSUE THREAD

**Issue by silverwind** [go-gitea/gitea#26411]
### Description

Seen this for the first time:

https://github.com/go-gitea/gitea/actions/runs/5808995595/job/15746928976?pr=26409

```
=== TestGit/SSH (tests/integration/git_test.go:95)
==================
WARNING: DATA RACE
Read at 0x00c00501a5b8 by goroutine 221160:
  github.com/gliderlabs/ssh.(*sshContext).Err()
      <autogenerated>:1 +0x31
  database/sql.(*Rows).awaitDone()
      /opt/hostedtoolcache/go/1.21.0/x64/src/database/sql/sql.go:2973 +0x2a8
  database/sql.(*Rows).initContextClose.func1()
      /opt/hostedtoolcache/go/1.21.0/x64/src/database/sql/sql.go:2949 +0x8f
```

### Gitea Version

main

**Comment by silverwind** [comment]
Related: https://github.com/gliderlabs/ssh/pull/211

**Comment by wxiaoguang** [comment]
OK, I will "bypass" the upstream in this PR

**Comment by silverwind** [comment]
Fixed in main branch, leaving it open until we have a real fix via https://github.com/gliderlabs/ssh/pull/211.

**Comment by wxiaoguang** [comment]
The upstream is dead. I think this issue could also be closed since our "workaround" works well.
