### ISSUE TITLE
Use ajax for `Reference in New Issue`

### ISSUE THREAD

**Issue by yp05327** [go-gitea/gitea#26427]
### Description

We are using form post when during the request of `Reference in New Issue`.
https://github.com/go-gitea/gitea/blob/a370efc13f0e1ea309e324639832832bc14cb6dc/templates/repo/issue/view_content/reference_issue_dialog.tmpl#L6

But since #25258, we are going to use json response in the backend. so frontend should also make some changes or you will get this:
![image](https://github.com/go-gitea/gitea/assets/18380374/5d0803b2-5ca4-48ac-9340-b720cb5686e6)

### Gitea Version

latest

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

build

### Database

None

**Comment by CaiCandong** [comment]
How to reproduce this problem? Can you give me detailed steps to reproduce it?

**Comment by CaiCandong** [comment]
![gitea](https://github.com/go-gitea/gitea/assets/50507092/85d93059-966c-4a8e-8ed4-9cd76c1f3004)
