### ISSUE TITLE
Add option for specifying the default highlighting language per project

### ISSUE THREAD

**Issue by schra** [go-gitea/gitea#2643]
I'd be nice if one could specifiy the default highlighting language of code that people post in issues, prs, and the wiki for each project.

At the moment the programming language is deduced from the code as long as one doesn't specify the language explicitly. But this doesn't work well for small code snippets.

This can be archived by calling `hljs.configure({'languages': ['XXXXX']});` before `hljs.initHighlightingOnLoad()` (which is in `public/js/index.js`). But I am not sure how to integrate the default language selection into the UI.

**Comment by lafriks** [comment]
That should probably be added in repository settings

**Comment by schra** [comment]
Any ideas under which tab and segment this could be added in the repository settings?

**Comment by lafriks** [comment]
I think it should be in options tab in advanced settings section as there is also where you enable/disable issues and wiki sections
