### ISSUE TITLE
create repo 500 error

### ISSUE THREAD

**Issue by checkmateTowindn** [go-gitea/gitea#26432]
### Description

![image](https://github.com/go-gitea/gitea/assets/26129032/b0daf9f4-0b59-41ea-ac46-78a7f641eee0)
![image](https://github.com/go-gitea/gitea/assets/26129032/c0b7e507-8a89-4427-8e1b-3233d46437af)
uoload file 
![image](https://github.com/go-gitea/gitea/assets/26129032/a23eb345-10a5-4b8a-8cf0-93a0dd6d9e2e)

### Gitea Version

1.20.2

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

gitea-1.20.2-gogit-windows-4.0-amd64

### Database

None

**Comment by CaiCandong** [comment]
I see git hook in the prompt message, did you set up a git hook?

**Comment by checkmateTowindn** [comment]
This is the first creation after deployment and nothing has been set up

**Comment by CaiCandong** [comment]
Can you post the contents of your `app.ini` file?

**Comment by checkmateTowindn** [comment]
Sorry, after reinstalling, it seems that this issue cannot be reproduced

**Comment by CaiCandong** [comment]
> Sorry, after reinstalling, it seems that this issue cannot be reproduced

This issue may be related to the `app.ini` configuration file, if you are able to use it properly now, you may consider close this isssue

**Comment by yp05327** [comment]
It looks like that there's a missing enter in app.ini
I guess your app.ini is something like this:

``` ini
WORK_PATH=D:RUN_MODE = prod
```
Becasue of this error info:
![image](https://github.com/go-gitea/gitea/assets/18380374/8b192ac6-9d7a-4d8f-bfe5-839ae751194c)

**Comment by lunny** [comment]
Closed as it should be a configuration problem.
