### ISSUE TITLE
Threaded email notifications by adding missing mail headers

### ISSUE THREAD

**Issue by mxmehl** [go-gitea/gitea#2645]
## Description

Currently, the email notifications lack some headers which would make them easier to read and follow in mail clients. Even in a modern MUA the notification mails aren't shown in a thread like with Github mails.

This is because following headers are missing (from a mail of a Github pull request):
- `Message-ID: <astroidmail/astroid/pull/412/push/2025975904@github.com>`
- `In-Reply-To: <astroidmail/astroid/pull/412@github.com>`
- `References: <astroidmail/astroid/pull/412@github.com>`

While the message-id isn't required to allow the threaded view it's part of a valid email layout.

**Comment by mxmehl** [comment]
Other interesting issues along the lines of improved email notifications:

https://github.com/go-gitea/gitea/issues/745, https://github.com/go-gitea/gitea/issues/2386, https://github.com/go-gitea/gitea/issues/2141, https://github.com/go-gitea/gitea/issues/1885, https://github.com/go-gitea/gitea/issues/1883, https://github.com/go-gitea/gitea/issues/1464, https://github.com/go-gitea/gitea/issues/145

**Comment by ptman** [comment]
can message IDs be anything or do they need to confirm to a specific format?

**Comment by mxmehl** [comment]
> can message IDs be anything or do they need to confirm to a specific format?

Basically this is quite free to define accoridng to [RFC 2392](https://tools.ietf.org/html/rfc2392) as long as every ID is globally unique. But in order to enable the tree structure, it should follow a certain form.

Github seems to do it as follows:

- First message: `Message-ID: <$UserOrOrg/$reponame/$type/$number@$domain>`, so e.g. `astroidmail/astroid/pull/570@github.com`
- Following replies:
  - `Message-ID: <astroidmail/astroid/pull/570/issue_event/2191656010@github.com>`, where the number is the comment ID
  - `In-Reply-To: <astroidmail/astroid/pull/570@github.com>`, so the Message-ID of the first post
  - `References: <astroidmail/astroid/pull/570@github.com>`, so the Message-ID of the first post

As you can see, no need to create new random strings, as the Gitea domain, the user/repo name, the pull/issue number, and the comment ID will make every Message-ID unique.

The missing Message-ID also causes Gitea's mails to be caught by more and more spam filters.

**Comment by mxmehl** [comment]
Closed by #7484 as it seems. Thanks @mrsdizzie !
