### ISSUE TITLE
Can add 'unassignee'  filter value to  issue list of the millstone?

### ISSUE THREAD

**Issue by mei-rune** [go-gitea/gitea#26474]
### Feature Description

There is an "unassigned" value in the drop-down box of "Assignee Filtering" in the issues list, which is useful, but it is not available in the Milestones view, can you add it？

在 issues list 中 ”指派人筛选“  的下拉框中有一个的 “未指派” 值， 它很有用， 但是在 里程碑  这个视图中没有它， 请问能不能加一下？

### Screenshots

issue list
![1691898492891](https://github.com/go-gitea/gitea/assets/1052632/f3bb2813-b9a2-4d97-9d9e-9def9e7a2794)

list in the millstone 
![1691898746680](https://github.com/go-gitea/gitea/assets/1052632/80472231-3285-4ba1-ad55-bd78386f0c36)

**Comment by CaiCandong** [comment]
In version 1.21 of gitea, the button is alreay exists. which version are you using ?
![image](https://github.com/go-gitea/gitea/assets/50507092/72b09180-3220-4438-a686-2ab4c6e910bb)

**Comment by mei-rune** [comment]
@CaiCandong  Gitea version 1.20.0 built with GNU Make 4.1, go1.20.6 : bindata, sqlite, sqlite_unlock_notify

**Comment by CaiCandong** [comment]
> 1.21 is unreleased?

 I use the latest main branch. maybe you can try it?

**Comment by mei-rune** [comment]
I wait v1.21 release!
