### ISSUE TITLE
accepting or rejecting transfer to organization is disabled even when the user is the owner of repo and organization

### ISSUE THREAD

**Issue by basilrabi** [go-gitea/gitea#26491]
### Description

I am the owner of a repository and at the same time, owner of an organization. When I transfer the ownership of the repository to the organization, the transfer is pending since it needs to be accepted first. However, the accept and reject buttons are greyed-out with a tool-tip showing  "You do not have permission to Accept/Reject".

When I try this at https://try.gitea.io/, there is no confirmation needed and the transfer is done instantly.

### Gitea Version

1.20.2

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![Screenshot from 2023-08-14 20-03-35](https://github.com/go-gitea/gitea/assets/29010952/49375790-3c33-4734-a22b-0504bd6be4f5)

### Git Version

2.41.0

### Operating System

Fedora 37

### How are you running Gitea?

I used the binary version in the git release.

### Database

PostgreSQL

**Comment by wxiaoguang** [comment]
Could you try to create and join a team with this permissions?

![image](https://github.com/go-gitea/gitea/assets/2114189/69e6a52f-4167-4ed5-9c1e-74c1dfcccd03)

**Comment by yp05327** [comment]
Did you update Gitea from the version before v1.11?

**Comment by basilrabi** [comment]
> Could you try to create and join a team with this permissions?
> 
> ![image](https://user-images.githubusercontent.com/2114189/260609843-69e6a52f-4167-4ed5-9c1e-74c1dfcccd03.png)

Creating another team with this permission works. Thank you.

**Comment by basilrabi** [comment]
> Did you update Gitea from the version before v1.11? And this org is created before you updated from 1.11.

I came from version 1.19 but maybe the team was created prior to 1.11 but still, I'm the owner of the team and the owner of the repository so for me, creating another team is not needed.  Anyway, the previous comment works.
