### ISSUE TITLE
verify 2FA and error with "not in 2FA session"

### ISSUE THREAD

**Issue by soxft** [go-gitea/gitea#26500]
### Description

<img width="1163" alt="image" src="https://github.com/go-gitea/gitea/assets/42080379/4d0baa01-d3f3-4b82-bba4-c1666e5751c6">

### Gitea Version

1.20.2

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

systemd

### Database

MySQL

**Comment by lunny** [comment]
So the user stays on the 2fa page too long.

**Comment by soxft** [comment]
I tried to refresh the page, clear the cache, but still got a 500 error.
When I tried to log in on another device, it worked fine.
It may be some problem with my browser

sorry for that
