### ISSUE TITLE
Migartion removing index column fails

### ISSUE THREAD

**Issue by daviian** [go-gitea/gitea#2650]
- Gitea version (or commit ref): 4b2c8ca 
- Git version: 2.7.4
- Operating system: Ubuntu 16.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:
```
2017/10/04 12:15:46 [I] Migration: remove index column from repo_unit table
2017/10/04 12:15:46 [...itea/routers/init.go:55 GlobalInit()] [E] Failed to initialize ORM engine: migrate: do migrate: DROP COLUMN index: Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'index' at line 1
```

## Description

Migration removing index column from repo_unit table fails with above error.

**Comment by lafriks** [comment]
Index is reserved keyword and has to be escaped
