### ISSUE TITLE
Teams filter has no effect in org level dashboard 

### ISSUE THREAD

**Issue by yp05327** [go-gitea/gitea#26512]
### Description

This filter should select the repos belongs to the selected team.
![image](https://github.com/go-gitea/gitea/assets/18380374/eeaadab8-cfc3-428d-b73d-852993b84f09)
But you can see that there's no repo belongs to this team, and all count numbers are `0`, but there are still some issues here.
![image](https://github.com/go-gitea/gitea/assets/18380374/4b94540f-d3d7-434b-a9d0-7b050e786995)

Maybe the problem is that we will search all repos when the repo list is empty in the background. 
So I think not only issues but also PR and milestone dashboard have the same problem.

### Gitea Version

latest

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

build

### Database

None

**Comment by CaiCandong** [comment]
I will fix it
