### ISSUE TITLE
"Could not read from remote repository" after update to 1.20.2

### ISSUE THREAD

**Issue by veita** [go-gitea/gitea#26516]
### Description

After update to 1.20.2 Git commands like `git clone` failed with message "could not read from remote repository".

Trying to connect with `ssh gitea@host.example.org` revealed the error behind the error:
```
PTY allocation request failed on channel 0
2023/08/15 10:35:41 ...s/setting/setting.go:109:LoadCommonSettings()
[F] Unable to load settings from config: unable to create chunked upload directory:
/usr/local/bin/data/tmp/package-upload (mkdir /usr/local/bin/data: permission denied)
Connection to host.example.org closed.
```
`/usr/local/bin/` is the location of the Gitea binary. It has permissions `drwxr-xr-x`.

The running Gitea instance reports
```
App Data Path          /var/lib/gitea/data
Repository Root Path   /repo/gitea
Custom File Root Path  /var/lib/gitea/custom
Log Path               /var/log/gitea
```
on its web GUI.

The working directory of the Gitea process is `/var/lib/gitea`.

`CHUNKED_UPLOAD_PATH` is not present in `app.ini`. `INSTALL_LOCK` is set to `true`.

### Gitea Version

1.20.2

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

git version 2.39.2

### Operating System

Debian 12 Bookworm

### How are you running Gitea?

Gitea binary downloaded from https://github.com/go-gitea/gitea/releases/download/ and run as a Systemd service as user `gitea`.

### Database

PostgreSQL

**Comment by veita** [comment]
A workaround for this bug is to explicitly set
```
[packages]
CHUNKED_UPLOAD_PATH = /var/lib/gitea/data/tmp/package-upload
```
in `app.ini`. This is the default value as an absolute path. Using `tmp/package-upload` instead does not work.

**Comment by wxiaoguang** [comment]
Check your startup message. You might need to set your WORK_PATH in your app.ini correctly.

**Comment by veita** [comment]
> You might need to set your WORK_PATH in your app.ini correctly.
`WORK_PATH` was not present in `app.ini`. Setting it also solves the problem.

Thank you very much!

**Comment by wxiaoguang** [comment]
> It seems that neither `WorkingDirectory` nor `GITEA_WORK_DIR` do have the expected effect in 1.20.2.

GITEA_WORK_DIR still have effects, but they do not have effect on "ssh" related commands.

The work-path problem is quite longstanding, it used to cause various unfixable bugs. 1.20.x has a complete fix for it:

* #25330

That PR has been marked as "breaking", while it should be pretty transparent to users whose Gitea instance could write its app.ini.
