### ISSUE TITLE
Unable to use Manually Configured OAuth with Git Credentials Manager

### ISSUE THREAD

**Issue by Sapein** [go-gitea/gitea#26526]
### Description

Whenever using generic oauth authentication with Gitea, git-credentials-manager can not actually use gitea's oauth implementation. This occurs because the git-credentials-manager appends a trailing backslash onto the URI causing gitea to give an `unauthorized_client: unexpected redirect URI` error. This completely stops me from being able to use GCM with Gitea with how I have it setup atm. 

Ideally, gitea should not care about trailing backslashes. 

### Gitea Version

1.20.2

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

Gitea provided windows release of 1.20.2 and on https://try.gitea.io

### Database

None

**Comment by wxiaoguang** [comment]
Oops, I thought it's about the "builtin"  Git Credentials Manager support.


> This occurs because the git-credentials-manager appends a trailing backslash onto the URI causing gitea to give an unauthorized_client: unexpected redirect URI error.

What's the URI?

**Comment by Sapein** [comment]
> Oops, I thought it's about the "builtin" Git Credentials Manager support, but it's not, reopen.
> 
> > This occurs because the git-credentials-manager appends a trailing backslash onto the URI causing gitea to give an unauthorized_client: unexpected redirect URI error.
> 
> What's the URI?

Thanks for reopening, my apologies as I probably could've been clearer.

As to the URI the redirect URI setup with Gitea is: `http://127.0.0.1`, the redirect URI that GCM is using in the request is `http://127.0.0.1/`. 

A example of the request (copied directly from an actual attempt to use GCM) is as follows:
`https://[GITEA URL]/login/oauth/authorize?response_type=code&client_id=[CLIENT ID]&state=ce09ece29d724dfdb547291cf865f017&code_challenge_method=S256&code_challenge=5hWMCvzIBIpjhS3MmFA4Jaq3letwAt7yTXqq6NVBrGg&redirect_uri=http%3a%2f%2f127.0.0.1%3a52405%2f&scope=repository%3awrite+read%3auser`

This fails. However the following works:
`https://[GITEA URL]/login/oauth/authorize?response_type=code&client_id=[CLIENT ID]&state=ce09ece29d724dfdb547291cf865f017&code_challenge_method=S256&code_challenge=5hWMCvzIBIpjhS3MmFA4Jaq3letwAt7yTXqq6NVBrGg&redirect_uri=http%3a%2f%2f127.0.0.1%3a52405&scope=repository%3awrite+read%3auser`

**Comment by wxiaoguang** [comment]
Ignore the trailing slashes when comparing oauth2 redirect_uri #26597
