### ISSUE TITLE
JavaScript error: RangeError: invalid value unit for option style

### ISSUE THREAD

**Issue by veita** [go-gitea/gitea#26525]
### Description

Visit https://gitea.example.org/admin. The following error is shown on a red bar on the webpage:

```
JavaScript error: RangeError: invalid value unit for option style
(https://git.nezwerg.de/assets/js/webcomponents.js?v=1.20.2 @ 1:21550).
```

### Gitea Version

1.20.2

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

git version 2.39.2

### Operating System

Debian 12 Bookworm

### How are you running Gitea?

Gitea binary downloaded from https://github.com/go-gitea/gitea/releases/download/ and run as a Systemd service.

Browser: Pale Moon 32.3.1.

### Database

PostgreSQL

**Comment by silverwind** [comment]
Can you show a screenshot of the surrounding JS code when you click the error line number in the browser console (F12)?

**Comment by wxiaoguang** [comment]
The exception is thrown here: 

https://github.com/github/relative-time-element/blob/d0da95b8c69bd22b76781d50d6143f7427844380/src/duration-format-ponyfill.ts#L113

What's your browser name/version and what's your locale (eg: run `window.document.documentElement.lang` in your browser console)?

And, are you using some browser plugins like translators? Does the error still exist in private window?

**Comment by wxiaoguang** [comment]
PaleMoon bug (incomplete `Intl.NumberFormat` support).

You could test it on this page https://github.github.io/relative-time-element/examples/ and fix the bug accordingly.


![image](https://github.com/go-gitea/gitea/assets/2114189/5fa5a3d5-4651-4117-9198-b1d40a1bd42f)

**Comment by veita** [comment]
https://repo.palemoon.org/MoonchildProductions/Pale-Moon/issues/1930

**Comment by wolfbeast** [comment]
It's not necessarily a "bug", it's just "yet another spec change" and "yet another tacked on API". We did lift our `Intl` support to the proper level recently, however we do not yet support the so-called `Unified NumberFormat API` which Gitea apparently now wants to use. i.e. not a bug, just another feature we'll have to implement.

Couldn't this have been implemented a bit more browser-agnostic in Gitea? I mean, not like "relative date formats" are a new thing, at all.

**Comment by wxiaoguang** [comment]
Before 1.20: the "relative date" is rendered by backend, it doesn't support i18n well.

1.20: by using GitHub's "relative-time" element (#23988) , most date/time/duration texts are rendered by browser.

* https://github.com/github/relative-time-element
* https://github.github.io/relative-time-element/examples/

**Comment by wolfbeast** [comment]
Would you consider keeping the backend implementation as a fallback, at least? I mean, just hard throwing an error is always worse than "not supporting i18n well".

**Comment by wxiaoguang** [comment]
I am neutral for it, but I am not familiar with the "relative-time" change. Maybe the original author @yardenshoham  could suggest.

**Comment by wxiaoguang** [comment]
Maybe they use some internal packages or they use some polyfill packages.

**Comment by yardenshoham** [comment]
Perhaps we could add some sort of polyfill for the missing NumberFormat API? I see a backend implementation as a step back in terms of evolution

**Comment by wxiaoguang** [comment]
Just get an (somewhat strange) idea, would PaleMoon to pack some polyfill packages by default? Then many browser features could be used out-of-box, instead of waiting a C++ native implemention. 😁

**Comment by wolfbeast** [comment]
> Just get an (somewhat strange) idea, would PaleMoon like to pack some polyfill packages by default?

That's rather complex and potentially dangerous as we can't just inject scripts into content willy-nilly, especially not if they are part of the browser's internal resources (it breaks the chrome/content boundary); on top, blanked polyfilling will conflict with other websites that may polyfill things themselves. In isolation it might be a good idea but not on the open web, unfortunately. We have an open issue to implement this API now, but no immediate timeline as to when we'll get to it.

**Comment by wxiaoguang** [comment]
Made some tests, the minimal polyfill is like this (without i18n support):

```
	(function() {
		const old = Intl.NumberFormat;
		Intl.NumberFormat = function(locales, options) {
			if (options.style === 'unit') {
				return {
					format: function(value) {
						return ` ${value} ${options.unit}`;
					}
				}
			}
			return old(locales, options);
		};
	})();
```

![image](https://github.com/go-gitea/gitea/assets/2114189/7cc4c2ef-2fec-4065-9174-e07c45825b13)

**Comment by wxiaoguang** [comment]
Add minimum polyfill to support "relative-time-element" in PaleMoon #26575 

Does it look good or could there be better solutions?

**Comment by yardenshoham** [comment]
How about https://formatjs.io/docs/polyfills/intl-numberformat/?
