### ISSUE TITLE
Cannot filter issue search results by label/milestone/project/assignee/type

### ISSUE THREAD

**Issue by CaiCandong** [go-gitea/gitea#26536]
### Description
as title
relate indexer
# ScreenShot
Only the label case is shown, the rest milestone/project/assignee/type cases as it too.
![before](https://github.com/go-gitea/gitea/assets/50507092/505edec6-ed22-4e35-9d3a-964933752e0f)

# try.gitea.io

~~https://try.gitea.io/CaiCandong/dotfiles/issues?q=DSCD&type=all&sort=&state=open&labels=24194&milestone=0&project=0&assignee=0&poster=0~~

- [try.gitea.io/CaiCandong/dotfiles/issues?q=DSCD](https://try.gitea.io/CaiCandong/dotfiles/issues?q=DSCD)
- [try.gitea.io/CaiCandong/dotfiles/issues?labels=24194](https://try.gitea.io/CaiCandong/dotfiles/issues?labels=24194)
- [try.gitea.io/CaiCandong/dotfiles/issues?q=DSCD&labels=24194](https://try.gitea.io/CaiCandong/dotfiles/issues?q=DSCD&labels=24194)

### Gitea Version

main

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

development

### Database

None

**Comment by yp05327** [comment]
It seems that combined filters not work well

And this one, only two labels selected:
https://try.gitea.io/CaiCandong/dotfiles/issues?q=&type=all&sort=&state=open&labels=24194%2c24195&milestone=0&project=0&assignee=0&poster=0

**Comment by CaiCandong** [comment]
> It seems that the logic is `and` not `or`.

That's not what was discussed.  Try the three links below:
- https://try.gitea.io/CaiCandong/dotfiles/issues?q=DSCD
- https://try.gitea.io/CaiCandong/dotfiles/issues?labels=24194
- https://try.gitea.io/CaiCandong/dotfiles/issues?q=DSCD&labels=24194
