### ISSUE TITLE
Strange green point in dashboard repo list

### ISSUE THREAD

**Issue by yp05327** [go-gitea/gitea#26537]
### Description

I think this comes from #26520
![image](https://github.com/go-gitea/gitea/assets/18380374/af6ac787-5c59-4cd3-bca9-01cac030b3d2)
(Using Chrome on Windows)
@silverwind 

### Gitea Version

latest

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

build

### Database

None

**Comment by yp05327** [comment]
![image](https://github.com/go-gitea/gitea/assets/18380374/008eb593-6693-4bc0-a029-3f54048d39d5)

**Comment by silverwind** [comment]
Seems to be some Chrome-only issue. Adding `overflow-y: clip` does seem to help.

**Comment by wxiaoguang** [comment]
JS Fiddle: https://jsfiddle.net/6Ltbd581/16/


![image](https://github.com/go-gitea/gitea/assets/2114189/3f305cf6-72a8-461a-a8dc-d1de02ae737c)

**Comment by silverwind** [comment]
`line-height: 1` is the root of the problem, I think at minimum `1.2` is recommended, but I would go for `1.4` to be safe as the right value depends on font in use and we get different fonts on different OSs.

**Comment by wxiaoguang** [comment]
The "more"root problem seems that Chrome doesn't consider "descent" into the line-height .... so characters like "g" / "y" causes layout problems .....

At the moment I have no idea about how to deal with the descent gracefully.

![image](https://github.com/go-gitea/gitea/assets/2114189/1b1cee58-4665-4d8d-a4fd-bcaa7f34b991)

**Comment by wxiaoguang** [comment]
->  Fix various line-height styles #26553

**Comment by yp05327** [comment]
It seems that this is not completely fixed, I can still see these green things.
![image](https://github.com/go-gitea/gitea/assets/18380374/2b67ea09-4787-4366-b1a8-870b0d2a1389)

**Comment by yp05327** [comment]
Ah, I see. this green thing is a scrollbar. 😄 

(removed overflow-x)
![image](https://github.com/go-gitea/gitea/assets/18380374/ca957030-9103-4015-b532-03f1876cc565)

**Comment by yp05327** [comment]
![image](https://github.com/go-gitea/gitea/assets/18380374/dd53091c-6a63-4b6c-9367-ddfbaf0c9980)
![image](https://github.com/go-gitea/gitea/assets/18380374/aa9b859e-7999-408e-b6e2-149ad810b8ce)

when --line-height-default is 1.20, it will disappear

**Comment by wxiaoguang** [comment]
Then the "modules/normalize.css" should also be changed accordingly

**Comment by silverwind** [comment]
BTW, there is also this useless style in effect on these strings, which results in the too-early truncation:

```
.dashboard.feeds .filter.menu .item .text.truncate, .dashboard.issues .filter.menu .item .text.truncate {
  width: 75%;
}
```

**Comment by yp05327** [comment]
Does --line-height related to screen resolution?
My display is 1920 x 1080.

**Comment by silverwind** [comment]
No, `line-height` only depends on the font's intrinsic height.
