### ISSUE TITLE
markdown image links are wrong if repo is called 'src'

### ISSUE THREAD

**Issue by rmie** [go-gitea/gitea#26548]
### Description

Ack, this is an edge case.

We have a repo called src, and amazingly all links to images in markdown are wrong (404).

for example:

document: https://host/org/src/src/commit/...
actual img src: https://host/org/media/src/commit/...
expected img src: https://host/org/src/media/commit/...

It looks like the the first, instead of the second. occurrence of "src" is replaced by "media".

[try.gitea.io](https://try.gitea.io/rmie/src/src/branch/main/README.md) 

[suspected location](https://github.com/go-gitea/gitea/blob/1432d4eab94814db267577ec911a3375a1269fc0/modules/markup/html.go#L412)

### Gitea Version

1.19.3

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

docker

### Database

None

**Comment by KN4CK3R** [comment]
Fixed with #26745
