### ISSUE TITLE
Strange repo activity count

### ISSUE THREAD

**Issue by yp05327** [go-gitea/gitea#26540]
### Description

https://try.gitea.io/CaiCandong/dotfiles/activity
Have two issues active? ( I think) But in activity page, it is 1.

![image](https://github.com/go-gitea/gitea/assets/18380374/e801428c-496d-45db-9935-08fd09b9ff5c)

### Gitea Version

latest

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

build

### Database

None

**Comment by yp05327** [comment]
https://try.gitea.io/CaiCandong/dotfiles/activity/monthly

It seems that `monthly` is correct? Not sure the definition of active issues and unresolved issues.

**Comment by CaiCandong** [comment]
Active Issue is the sum of the number of open and closed issues in a period of time, which is not the same as the number of issues that remain open.
