### ISSUE TITLE
Change default sorting of user/org search to alphabetical

### ISSUE THREAD

**Issue by daviian** [go-gitea/gitea#2656]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL) search on explore page for user/org
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

At the moment every page including a searchbox use the same searchbox template, thus every search uses the same default ordering.
IMO sorting users and organizations by `newest` doesn't make much sense.
It would be more natural to have it sorted alphabetically by default.

I think in order to achieve that, we have to change the searchbox template to allow a dynamic assignment of default ordering per page.

**Comment by sapk** [comment]
Order by last activity could be best.

**Comment by daviian** [comment]
@sapk Since #2647 has already been merged ticket should be closed by now. ;-)

**Comment by lafriks** [comment]
@sapk it is very hard to orientate in searchbox if users are not alphabetically
