### ISSUE TITLE
Cannot display branch/tags list 

### ISSUE THREAD

**Issue by CaiCandong** [go-gitea/gitea#26572]
### Description

This bug cannot be reproduced stably， I noticed that the branches/tags data was already fetched, rather confused why it wasn't rendered？

- https://gitea.com/gitea/act_runner

https://github.com/go-gitea/gitea/assets/50507092/e54aa421-d738-4145-a88c-9778f626cfc3

![image](https://github.com/go-gitea/gitea/assets/50507092/6e9f8805-ab75-4347-905a-ecd3228dbe64)

### Gitea Version

gitea.com

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

gitea.com

### Database

None

**Comment by yp05327** [comment]
Can you provide the elements info here?
![image](https://github.com/go-gitea/gitea/assets/18380374/04f38b12-11b6-497f-aadb-7185d9d71456)

**Comment by CaiCandong** [comment]
```
<div data-v-22e70c27="" class="scrolling menu"><svg data-v-22e70c27="" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" width="16" height="16" aria-hidden="true" class="svg octicon-rss gt-hidden svg-symbol-container"><symbol id="svg-symbol-octicon-rss" viewBox="0 0 16 16"><path d="M2.002 2.725a.75.75 0 0 1 .797-.699C8.79 2.42 13.58 7.21 13.974 13.201a.75.75 0 0 1-1.497.098 10.502 10.502 0 0 0-9.776-9.776.747.747 0 0 1-.7-.798ZM2.84 7.05h-.002a7.002 7.002 0 0 1 6.113 6.111.75.75 0 0 1-1.49.178 5.503 5.503 0 0 0-4.8-4.8.75.75 0 0 1 .179-1.489ZM2 13a1 1 0 1 1 2 0 1 1 0 0 1-2 0Z"></path></symbol></svg><!--v-if--><!--v-if--></div>
```

**Comment by yp05327** [comment]
![image](https://github.com/go-gitea/gitea/assets/18380374/6cce29e0-e86d-45cb-bc1d-e7f8d2db66d4)
It seems that there are some errors on this page.

**Comment by yp05327** [comment]
Maybe you can test again with no browser extensions?

**Comment by CaiCandong** [comment]
> Maybe you can test again with no browser extensions?

Thank you, I deleted the `zotero connector` extension and it works! @yp05327
