### ISSUE TITLE
Prompt ui messages don't display on push changes - docker container

### ISSUE THREAD

**Issue by raphaelSm** [go-gitea/gitea#26584]
### Description

I'm running Gitea through the latest docker image with MariaDB 10 and I faced such a problem: Ui messages like 
`"You pushed on branch feature/branch-name now [New Pull Request]"` doesn't show up on repository dashboard, after user push changes to branch. 

Changes pushed via ssh/https/http are available in the repository. Has anyone encountered such a problem ?

In the gist link to the logs, I included the app.ini file and docker logs for the case of pushing commit via ssh and https.

### Gitea Version

1.20.2

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/raphaelSm/7af961cb57d4266fb29b004cd3e49e41

#### There is no notification after pushing the changes
![obraz](https://github.com/go-gitea/gitea/assets/45426478/348373ad-4537-419b-9bf7-9d4d635bbbcf)

#### Changes via ssh or https are pushed correctly
![obraz](https://github.com/go-gitea/gitea/assets/45426478/cd8a2739-b96f-4f28-93b4-b5ebc8fd3ba8)

### Git Version

2.40.1

### Operating System

DSM - GNU/Linux distro

### How are you running Gitea?

Gitea is running by docker - 
### image: 
gitea/gitea:latest
### Docker version:  
20.10.23, build 876964a
### Database:
MariaDB 10  

### Database

MySQL

**Comment by techknowlogick** [comment]
Thanks for opening this ticket. This functionality is available in 1.21-dev, so you'll be getting it soon when the next version releases :)

**Comment by raphaelSm** [comment]
I'm grateful for express reply, on version 1.21-dev works perfectly. Sorry for the misunderstanding.

PS. Gitea is awesome 🎉, thanks for hard work 👏

![obraz](https://github.com/go-gitea/gitea/assets/45426478/94cfce3c-9958-49f8-a5a9-5f2764db9f74)
