### ISSUE TITLE
"releases" page does not display correctly in Japanese

### ISSUE THREAD

**Issue by shomaku** [go-gitea/gitea#2659]
- Gitea version (or commit ref): v1.2.0-rc3
- Git version: 2.4.12
- Operating system: Windows Server 2008
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (https://try.gitea.io/scmstom/Test/releases)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
The commits information does disaplay correctly in Japanese.
English:  1 day ago 0 commits to master since this release
Japanese:  1 日 前 このリリース以降 **%!s(int64=0)** へ **%!d(string=master)** コミット

## Screenshots

![image](https://user-images.githubusercontent.com/1892176/31211467-2da3f108-a9d4-11e7-89b7-6e4f1be1c220.png)

**Comment by lafriks** [comment]
Please fix that it gitea crowdin.com page

**Comment by shomaku** [comment]
@lafriks Thanks, I have fixed it on crowdin.com.
