### ISSUE TITLE
UI: settings page style error

### ISSUE THREAD

**Issue by ExplodingDragon** [go-gitea/gitea#26617]
### Screenshots

![图片](https://github.com/go-gitea/gitea/assets/33776693/9e329668-9ad3-4bd7-b766-792088a5b2f1)
![图片](https://github.com/go-gitea/gitea/assets/33776693/030409e7-c0d3-4d48-8709-c9e889559ade)

### Gitea Version

main  (3db3f5daaeea38a9a8d8ec1a05d864e288338f82)

### Can you reproduce the bug on the Gitea demo site?

Yes

### Browser Version

firefox last stable

**Comment by wxiaoguang** [comment]
It seems related to "Introduce flex-list & flex-item elements for Gitea UI #25790"

@denyskon do you have ideas about it?

**Comment by denyskon** [comment]
@wxiaoguang / @ExplodingDragon Can you explain? Is it about the Mandarin (?) characters which have to be horizontal?

**Comment by denyskon** [comment]
@wxiaoguang / @ExplodingDragon Can you explain? Is it about the Mandarin (?) characters which have to be horizontal?

**Comment by wxiaoguang** [comment]
Could you try this one? -> Improve some flex layouts #26649
