### ISSUE TITLE
Signing commits with different email capitalization

### ISSUE THREAD

**Issue by CaeruleusAqua** [go-gitea/gitea#2661]
Gitea seems to have problems signing commits if the capitalization of the email address of the git user and the key does not match! On my local machine with "git verify-commit" the signature is verified correctly.

git verify-commit dc5fb4a4e5cf839cd30d11e8077bee7e7eecdcc3
gpg: Signature made Wed 04 Oct 2017 06:59:48 PM CEST
gpg:                using RSA key 3FC8FB4B947F9057
gpg: Good signature from "Julian Scholle <julian.scholle -at- iff - fraunhofer - de>" [ultimate]

![image](https://user-images.githubusercontent.com/1830710/31218562-0487948c-a9bb-11e7-8bac-40f7544efec5.png)

![image](https://user-images.githubusercontent.com/1830710/31218612-2f9a4f66-a9bb-11e7-8736-a8d5f717c68b.png)

- Gitea version (or commit ref): 4325320

**Comment by sapk** [comment]
This should be easy to fix. 
I haven't time rigth now. Just for information the change need to be done here : https://github.com/go-gitea/gitea/blob/master/models/gpg_key.go#L405 and sorround everythings with `strings.ToLower(email)`
