### ISSUE TITLE
Gitea can't run with template errors: template error: custom:base/footer:31 : function "ctx" not defined

### ISSUE THREAD

**Issue by byjove01** [go-gitea/gitea#26623]
### Description

I want to customize a lot my Gitea. I couldn't do it first because my templates were outdated ; people made me notice that... but now I got error outputs telling me that context variables aren't declared. What the hell? Do that mean I'll have to rewrite all of my template files each time Gitea gets updated?

### Gitea Version

Gitea version 1.20.2 built with GNU Make 4.4.1, go1.21.0 : bindata, sqlite, sqlite_unlock_notify, pam

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://0x0.st/HLUI.log

### Git Version

2.41.0

### Operating System

Arch Linux with kernel 6.4.11-arch1-1 

### How are you running Gitea?

Arch Linux binary.

### Database

MySQL

**Comment by lunny** [comment]
`ctx` is a template function for v1.21 only. Maybe you used a wrong template.

**Comment by byjove01** [comment]
Ok, that was it. My bad, I thought the git command would take the 1.20 and not main branch.
