### ISSUE TITLE
Can delete repo from Site Admin page without typing the name

### ISSUE THREAD

**Issue by lonix1** [go-gitea/gitea#26633]
### Feature Description

To delete a repo:
- click settings
- scroll down to delete, click
- popup asks to type name of repo, click

But in the "Site Administration" > "Repositories" page:
- click repo's delete button
- popup asks to click on yes/no (and the yes is active/bold/green, so it's easy to click it by mistake)

It doesn't ask to type the name. Forcing the user to type the name is a good safety feature.

**Comment by wxiaoguang** [comment]
The list is for maintenance purpose, it won't be friendly to site admin if it keeps asking to re-type the repo name.

And even more, as a site admin, usually they could just ssh into the server and do `rm -rf /` without typing any repo name to destroy everything, so, to be a site admin, they should have been very careful already.

For the color problem, it could be changed to another color by modifying one line code if you like.
