### ISSUE TITLE
Can't publish new package versions anymore

### ISSUE THREAD

**Issue by trading-peter** [go-gitea/gitea#26646]
### Description

I was able to push packages without problem but since one of the last updates it stopped worked all the sudden.

My setup:
- I have a organisation called "tp-elements"
- I'm in the owner group of that organisation. Checked like 10 times at this point lol.
- There are 32 repos in the org, each one als gets published as a NPM package by me.
- I can pull packages using npm install without problems.
- All packages are scoped in a "@tp" namespace.
- NPM output is the following
![image](https://github.com/go-gitea/gitea/assets/11567985/1fdbbf16-b0eb-4990-9b52-c13422c37ae0)
- Gitea logs show this if I try to push.
![image](https://github.com/go-gitea/gitea/assets/11567985/1fdbf0e9-000e-4220-aca9-275e6588fcf1)

### Gitea Version

1.20.3

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

Running it self-hosted using docker-compose.

### Database

PostgreSQL

**Comment by techknowlogick** [comment]
Did you upgrade from 1.20.2 or some other version?

**Comment by trading-peter** [comment]
I think I upgraded from 1.20.1 if I recall correctly

**Comment by trading-peter** [comment]
I figured it out.
Seems like there was a new setting added, or it got reset or whatever. Once I enabled the package registry on the repo that wanted to push a new npm package version it worked again.
![image](https://github.com/go-gitea/gitea/assets/11567985/8cc28333-0bb5-44b4-b606-a656e685a881)
