### ISSUE TITLE
Unable to run docker build, getting Operation not permitted error

### ISSUE THREAD

**Issue by maordavidov** [go-gitea/gitea#26645]
### Description

When running `make docker` I'm receiving in step 11 out of 29 the following errors:
```
Step 11/29 : RUN if [ -n "${GITEA_VERSION}" ]; then git checkout "${GITEA_VERSION}"; fi  && make clean-all build
 ---> Running in 0bb81b586144
go clean -i ./...
make: /bin/sh: Operation not permitted
make: /bin/sh: Operation not permitted
make: /bin/sh: Operation not permitted
make: git: Operation not permitted
make: /bin/sh: Operation not permitted
make: /bin/sh: Operation not permitted
make: find: Operation not permitted
make: /bin/sh: Operation not permitted
make: /bin/sh: Operation not permitted
make: go: Operation not permitted
make: *** [Makefile:279: clean] Error 127
```

### Gitea Version

main

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/14234032/1643b4e1-d6dd-489a-9133-6dd96d3e7d43)

### How are you running Gitea?

I'm building Gitea from source code

### Database

None

**Comment by techknowlogick** [comment]
Are you running from a clone of the primary Gitea repo, a fork, or an extract of a zip repo?

Also, can you provide the output of "docker info"? As more recent versions of alpine require more recent versions of docker to build.

**Comment by maordavidov** [comment]
Thank you @techknowlogick , it looks like it was the Docker version.
