### ISSUE TITLE
Why does editing global CSS files breaks my design?

### ISSUE THREAD

**Issue by byjove01** [go-gitea/gitea#26647]
### Description

In a more precise way, why is the structure of my web pages broken whileas I did put "web_src/css" folder from the main repository in my "custom" directory, and despite the only thing I edited being the `body` background?
Is there something else I should put so the structure could work again?

### Screenshots

https://i.imgur.com/3L6R2F6.png

### Gitea Version

Gitea version 1.20.2 built with GNU Make 4.4.1, go1.21.0 : bindata, sqlite, sqlite_unlock_notify, pam

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

Arch Linux with kernel 6.4.11-arch1-1

### Browser Version

LibreWolf Firefox 115.0.2-2

**Comment by wxiaoguang** [comment]
1. You need to use the same release version
2. You might not really want to edit the generated CSS files, but you can add a new file and override the defaults, eg: `css/my-styles.css` and include it in the custom template.

**Comment by byjove01** [comment]
I use the same release version. And I did try to override instead of replace the default CSS files, but modifications don't longer get applied. I made a my-custom.css with this content:
```
body {
  color: var(--color-text);
  background-image: url("../img/background.png");
  tab-size: var(--tab-size);
  display: flex;
  flex-direction: column;
  overflow-wrap: break-word;
}
```
