### ISSUE TITLE
Incorrect selection behavior at repo list , on the left side of the issues page.

### ISSUE THREAD

**Issue by zjjhot** [go-gitea/gitea#26653]
### Description

this url : https://your-gitea-url/issues

When entering the issues page for the first time, the repo list on the left is all-selected state.
This resulted in a STRANGE behavior:
When I click on a repo name in the list, the actual result is that the issue title list on the right side excludes the repo I just clicked on.
The EXPECTED effect should be, which repo(s) did I choose and which repo(s) issue list should be displayed on the right side.

![image](https://github.com/go-gitea/gitea/assets/79889452/559f18b0-0bd4-4941-9136-967288207d0f)

### Gitea Version

main branch

### Can you reproduce the bug on the Gitea demo site?

Yes

### Git Version

1.21.0-dev

### Operating System

windows

### How are you running Gitea?

windows exe

### Database

MSSQL

**Comment by CaiCandong** [comment]
# Current selected all:
![image](https://github.com/go-gitea/gitea/assets/50507092/0ac0e286-c0fd-4553-98ac-9bc573286670)

# Correctly selected all：

![image](https://github.com/go-gitea/gitea/assets/50507092/13877358-1a6f-463e-b472-9509b1f97506)
