### ISSUE TITLE
Empty diff page

### ISSUE THREAD

**Issue by yp05327** [go-gitea/gitea#26659]
### Description

empty diff page:
![image](https://github.com/go-gitea/gitea/assets/18380374/f9295297-f9b0-47f6-8ed5-069cb0340e76)

`diff.Files` is empty but `diff.NumFiles` is 1
![image](https://github.com/go-gitea/gitea/assets/18380374/f5102d95-2c83-4913-9ebe-1b7c0a7d9b4b)
![image](https://github.com/go-gitea/gitea/assets/18380374/1b1955cf-e120-4ccd-8449-b9e3258d6d2c)

How to reproduce:
Not know what happened. Maybe this is a coincidence. Can't reproduce this now. 😕 

### Gitea Version

latest

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

build

### Database

None

**Comment by yp05327** [comment]
It seems that this is caused by `WhitespaceBehavior`

git command in Gitea:
![image](https://github.com/go-gitea/gitea/assets/18380374/abc9da42-af5a-442b-b95d-0fe703e5a5d6)

git command in local without `-b`
![image](https://github.com/go-gitea/gitea/assets/18380374/11b32acd-b6d5-4a50-afc2-814c7a0d072d)
git command in local with `-b`
![image](https://github.com/go-gitea/gitea/assets/18380374/2d6d234b-fac9-4565-9dd4-fcce93e9214f)

**Comment by yp05327** [comment]
It comes from user's setting? Where can I change this setting.
![image](https://github.com/go-gitea/gitea/assets/18380374/dd5e61e4-6510-4f3d-aadb-327af1703926)

**Comment by lunny** [comment]
There is an option on top right dropdowns.

**Comment by yp05327** [comment]
![image](https://github.com/go-gitea/gitea/assets/18380374/1ff719e4-adb0-4eee-95de-7168046c155b)
I see it.
