### ISSUE TITLE
Duplicate check and an auto disappear timer for toast

### ISSUE THREAD

**Issue by yp05327** [go-gitea/gitea#26651]
### Description

Thanks for @wxiaoguang's work in #26535
But we need do some more works for toast:
![image](https://github.com/go-gitea/gitea/assets/18380374/1b5a7762-933f-45b7-afcd-002a13cde641)

How to reproduce?
just click rerun job button crazily :)

### Gitea Version

latest

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

build

### Database

None

**Comment by yp05327** [comment]
https://github.com/go-gitea/gitea/blob/f65977df3a65e193995c0bdf7069553fd5867fe2/web_src/js/modules/toast.js#L11-L19
duration is `-1`, so it will not disappear until user close it \. 😕

**Comment by yp05327** [comment]
Is it possible to check the content of the warning message, and if they are same then add `(number)` at the behind of the existing one?

**Comment by lunny** [comment]
Fixed by #28873 ?

**Comment by yp05327** [comment]
> Fixed by https://github.com/go-gitea/gitea/pull/28873 ?

No, that fix JS error, this is triggered by http response.
ps: tested in the latest commit.
