### ISSUE TITLE
Green action checkmark while workflows are still running

### ISSUE THREAD

**Issue by Eldolfin** [go-gitea/gitea#26665]
### Description

The main icon next to the commit message is green when the first action successfully passed, instead of waiting for all of them to pass.
As you can see on the example below, only one action finished and the icon is already a green check mark.

### Gitea Version

1.20.2

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/90446228/a149cf3b-4d85-4b0e-9594-d25b6656ef3c)

### How are you running Gitea?

ubuntu snap on arm server

### Database

SQLite

**Comment by yp05327** [comment]
I think this has already been fixed in #26121 and this fix will be released in 1.21.0.

**Comment by Eldolfin** [comment]
Thanks, i'll close the issue then 😄
