### ISSUE TITLE
Context filter has no effect in dashboard

### ISSUE THREAD

**Issue by yp05327** [go-gitea/gitea#26686]
### Description

Follow #26512

![bug](https://github.com/go-gitea/gitea/assets/18380374/86b3ab35-253b-43cd-a883-0193293ef771)

### Gitea Version

latest

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

build

### Database

None

**Comment by silverwind** [comment]
Maybe we should remove this context row altogether? I find it distracting on the few pages where it's present  and as seen, it's a half-finished implementation.
