### ISSUE TITLE
User with no action unit access permission can also see the commit status

### ISSUE THREAD

**Issue by yp05327** [go-gitea/gitea#26685]
### Description

User's permission:
![image](https://github.com/go-gitea/gitea/assets/18380374/92cda064-bd77-4474-9765-5e94899912a7)

![image](https://github.com/go-gitea/gitea/assets/18380374/adb7f6f4-312f-48e4-b436-3df2e3bde769)

### Gitea Version

latest

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

build

### Database

None

**Comment by lunny** [comment]
It's commit status not actions' special feature.

**Comment by yp05327** [comment]
> It's commit status not actions' special feature.

Reasonable answer. But, if click details, you will get 404 page. 
![image](https://github.com/go-gitea/gitea/assets/18380374/c481e6ea-a470-46b4-9c36-4e834cd84a1a)
Should we hidden this when using Gitea action and user have no unit permission?

**Comment by lunny** [comment]
> > It's commit status not actions' special feature.
> 
> Reasonable answer. But, if click details, you will get 404 page. ![image](https://user-images.githubusercontent.com/18380374/262837534-c481e6ea-a470-46b4-9c36-4e834cd84a1a.png) Should we hidden this when using Gitea action and user have no unit permission?

Wow, I have no idea how to handle now.

**Comment by Zettat123** [comment]
I encountered a similar issue. If the repo's action unit is disabled, even though I'm an administrator, I'll still get a 404 page when clicking the "Details" link

**Comment by yp05327** [comment]
I think this should be hidden when user does not have permission or the unit is disabled.

**Comment by lunny** [comment]
But you don't know if the commit status comes from actions or external sites.

**Comment by yp05327** [comment]
Actually, I noticed another related issue.
If user has no access to code unit, but have access to action unit, 
you would see the workflow file name, branch name, commit id and so on.
And they also have links which will get 404.
