### ISSUE TITLE
Alpine Package Registry: Handling of 'noarch' packages

### ISSUE THREAD

**Issue by joniw** [go-gitea/gitea#26691]
### Description

Hello,

thank you for integrating the possibility to use gitea as an alpine package registry.

When adding a package with the architecture 'noarch' (like the [salt package](https://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/salt-3006.1-r0.apk)) it can not be installed via apk.

The reason is the architecture ist automatically detected from the package in the source-code and the uploaded package is then only available under the 'noarch' archtitecture and not under the other architectures like 'x86_64'.

A short test with the salt package from edge to my gitea instance:

```
root@alpine-dev ~/test # wget https://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/salt-3006.2-r0.apk
Connecting to dl-cdn.alpinelinux.org ([2a04:4e42:6f::644]:443)
saving to 'salt-3006.2-r0.apk'
salt-3006.2-r0.apk   100% |**************************************************************************************************************************| 5625k  0:00:00 ETA
'salt-3006.2-r0.apk' saved
root@alpine-dev ~/test # curl --user testuser:password --upload-file salt-3006.2-r0.apk https://[***REDACTED***]/api/packages/alpine-packages/alpine/edge/
root@alpine-dev ~/test # apk update
fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/community/x86_64/APKINDEX.tar.gz
fetch https://[***REDACTED***]/api/packages/alpine-packages/alpine/edge/salt/x86_64/APKINDEX.tar.gz
WARNING: updating and opening https://[***REDACTED***]/api/packages/alpine-packages/alpine/edge/salt: No such file or directory
v3.18.3-55-g2ee93b9273a [https://dl-cdn.alpinelinux.org/alpine/v3.18/main]
v3.18.3-63-g5d6ac0a2673 [https://dl-cdn.alpinelinux.org/alpine/v3.18/community]
2 unavailable, 0 stale; 20063 distinct packages available
root@alpine-dev ~/test # wget https://[***REDACTED***]/api/packages/alpine-packages/alpine/edge/salt/x86_64/APKINDEX.tar.gz
Connecting to [***REDACTED***] ([***REDACTED***]:443)
wget: server returned error: HTTP/1.1 404 Not Found
root@alpine-dev ~/test # wget https://[***REDACTED***]/api/packages/alpine-packages/alpine/edge/salt/noarch/APKINDEX.tar.gz
Connecting to [***REDACTED***] ([***REDACTED***]:443)
saving to 'APKINDEX.tar.gz'
APKINDEX.tar.gz      100% |**************************************************************************************************************************|  1170  0:00:00 ETA
'APKINDEX.tar.gz' saved
```

Possible solutions to this problem from my point of view are:
- add 'noarch' packages to all architectures
- allow to set the architecture on upload

With regards
Joniw

### Gitea Version

1.20.3

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

Test instance in Kubernetes

### Database

PostgreSQL

**Comment by serenevoid** [comment]
I have been looking into this for a few days now. I was initially thinking that it would be nice to implement a logic to copy and store all `noarch` packages into all the architectures supported by alpine. But that might cause data redundancy if I understood it correctly. So what if I try to make the Download function search the package in `noarch` once if the package is not found in the respective arch folder. Will that be a good solution?

**Comment by joniw** [comment]
This would solve the problem that the "noarch" packages are not visible, but will still serve the packages under the "noarch" architecture. 

An alpine repository in a directory would serve each noarch package as a distinguished one, perhabs it would be better to allow to set the target architecture on upload.

**Comment by joniw** [comment]
Just a small workaround for other people who have problems with this issue:

```
TARGET_ARCH=x86_64
for apk in $(find /path/to/apks -type f -name "*.apk"); do
    tmp=$(mktemp -dup /tmp);
    mkdir -p ${tmp}/apk && chmod -R 0755 ${tmp};
    tar -xzpf ${apk} -C ${tmp}/apk;
    rm ${tmp}/apk/.SIGN*.pub;
    mv ${tmp}/apk/.PKGINFO ${tmp};
    tar -C ${tmp}/apk/ --xattrs -f - -c $(ls -A1 ${tmp}/apk) | abuild-tar --hash | gzip -9 > ${tmp}/data.tar.gz;
    sha256=$(sha256sum ${tmp}/data.tar.gz | cut -d" " -f1);
    sed -i "\$d" ${tmp}/.PKGINFO;
    echo "datahash = ${sha256}" >> ${tmp}/.PKGINFO;
    echo "Rewriting architecture for $(basename ${apk}) to ${TARGET_ARCH}";
    sed -i "s/arch = noarch/arch = ${TARGET_ARCH}/g" ${tmp}/.PKGINFO;
    tar -C ${tmp} -f - -c .PKGINFO | abuild-tar --cut | gzip -9 > ${tmp}/control.tar.gz;
    abuild-sign ${tmp}/control.tar.gz;
    cat ${tmp}/control.tar.gz ${tmp}/data.tar.gz > ${apk};
    rm -rf ${tmp};
done
```

With this code every apk is unpacked and the architecture gets rewritten. 

As we can see [in the source](https://gitlab.alpinelinux.org/alpine/abuild/-/blob/3.12.0/abuild.in?ref_type=tags#L604) the packages with the following names are always build with noarch as architecture:

- *-doc 
- *-openrc 
- *-lang 
- \*-lang-\* 
- *sh-completion 
- *-pyc
