### ISSUE TITLE
Unit testing on macOS invokes keychain

### ISSUE THREAD

**Issue by harryzcy** [go-gitea/gitea#26717]
### Description

Running test-sqlite on macOS causes keychain prompt to show up.

<img width="537" alt="Screenshot 2023-08-24 at 4 07 48 PM" src="https://github.com/go-gitea/gitea/assets/37034805/40411a20-e4da-444e-be6a-a0d563905a7d">

### Gitea Version

main branch

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

`TAGS="sqlite sqlite_unlock_notify" make build test-sqlite`

### Database

None

**Comment by KN4CK3R** [comment]
Same on WSL because git uses the agent to request credentials.

**Comment by wolfogre** [comment]
I am also troubled by this issue, and I would appreciate it if someone could solve it.

**Comment by wxiaoguang** [comment]
Which test triggers it?

**Comment by william-allspice** [comment]
For anyone else following, you can get around this on a mac by running the tests with the GIT_CONFIG_NOSYSTEM=true flag.

ie. ```GIT_CONFIG_NOSYSTEM=true make test-sqlite```

Credit to @bohde for diagnosing it.

**Comment by bohde** [comment]
I think I saw this in `TestDumpRestore` and `TestGit`. Dismissing the notification appears to cause the fallback to be cached, which makes it difficult to catch every test that may cause this though.
