### ISSUE TITLE
proxy is not work

### ISSUE THREAD

**Issue by hametan** [go-gitea/gitea#26727]
### Description

proxy with clash not work 
container curl google.com success.
but gitea have no link to clash

### Gitea Version

1.20.3

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

docker 

### Database

None

**Comment by silverwind** [comment]
Ensure that both the docker daemon and the container itself have the env vars set (HTTPS_PROXY etc).

**Comment by silverwind** [comment]
No usable issue description or reproduction steps and this is more of a support type question, clonsing.
