### ISSUE TITLE
Can't alter org member's role

### ISSUE THREAD

**Issue by muellert** [go-gitea/gitea#2672]
- Gitea version (or commit ref): 1.2.0+rc3-4-g5b36379
- Git version: 1:2.11.0-3+deb9u2
- Operating system: Debian Stretch 9.2/amd64
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No (need second account)
  - [ ] Not relevant
- Log gist:

## Description

I created an organisation and added a co-worker to the organisation, and their role is now fixed as ‘Member’. I would like to grant them admin rights.

I also created a team, but got an error when I wanted to change ownership of the repo to the team.

## Screenshots

![selection_190](https://user-images.githubusercontent.com/1183079/31311768-f624d7f0-abaa-11e7-8f22-09a400bc2eb8.png)

**Comment by lafriks** [comment]
I think #2641 resolves this question

Adding user directly as organization member does not grant any rights for that user. You need to add that user to team to grant rights to repository.

You can not transfer repository to team. You can transfer it only to organization or other user

**Comment by muellert** [comment]
Ok. It's probably a UI problem.
