### ISSUE TITLE
Accessibility - Tab order is wrong on creating an issue (tabindex)

### ISSUE THREAD

**Issue by TDesjardins** [go-gitea/gitea#26731]
### Description

When navigating with keyboard when creating an issue the tab order isn't plausible. I expect after editing the title the next tab is the description text area or the tabpanel but it jumps to somewhere else and the next targets are the menu items.

Strange settings of `tabindex` attributes on different DOM elements are the cause. A best practice is to not set the `tabindex` > `0` and using the natural DOM order.

### Gitea Version

1.20.2

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

run from docker but doesn't matter

### Database

None

**Comment by wxiaoguang** [comment]
->  Fix incorrect "tabindex" attributes #26733
