### ISSUE TITLE
Review bar and "sticky" file header layout regression

### ISSUE THREAD

**Issue by wxiaoguang** [go-gitea/gitea#26730]
Due to #26711 (and other old PRs) , now the "sticky" file header doesn't work well with uncertain review bar height. 

Before, the sticky top was hard-coded to 2 magic numbers, but the "review bar" has been changed many times and it uses "flex" layout, the height is not predictable.

**Comment by silverwind** [comment]
Height needs to be predictable for sticky to work, unless there is another solution but I'm not aware of.

**Comment by wxiaoguang** [comment]
I am not working on it either, just open an issue for record.
