### ISSUE TITLE
Can't search for repos unless I'm admin

### ISSUE THREAD

**Issue by muellert** [go-gitea/gitea#2673]
- Gitea version (or commit ref): 1.2.0+rc3-5-g73ad7d2
- Git version: 1:2.11.0-3+deb9u2
- Operating system: Debian Stretch 9.2/amd64
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description

If I am trying to search a repo from the Explore page, or if I am trying to search it from my profile page, I usually get no results. I have not detected a pattern when I get and when I don't get any results. If I search it from the Dashboard on the right side, I always get the desired results. The repos are all mine, anyway - I created them, and I am the owner of all organisations that I created them under. If I am logged in as the admin user, I can search the repos from the Explore page with no problem. But I created them with different versions of gitea 1.2rc3 - not sure what the upgrade procedure would be, I just copied the binary over and restarted the service.

**Comment by Morlinest** [comment]
#2652 is telling about this behaviour, you can vote for solution (show/hide private repositories on explore page).

**Comment by techknowlogick** [comment]
Closing issue. Please re-open this ticket if this is still an issue.
