### ISSUE TITLE
Migrating Repository from GitHub Failed

### ISSUE THREAD

**Issue by yekanchi** [go-gitea/gitea#26740]
### Description

I'm trying to migrate a public repository from Github to local Gitea with its **issues** included. but this error happens.
I tried multiple times, and it keeps telling this error.

![image](https://github.com/go-gitea/gitea/assets/25511175/39d58f10-cafb-4005-ad71-72f210afa9ce)

### Gitea Version

1.21dev

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

self hosted on windows

### Database

None

**Comment by puni9869** [comment]
Can we have the full trace logs? whats going on.

**Comment by yekanchi** [comment]
updated Gitea to the latest dev build.
IDK how but this issue is fixed.
