### ISSUE TITLE
Error "failed to update size for mirror repository: updateSize: lstat [...] no such file or directory"

### ISSUE THREAD

**Issue by pboguslawski** [go-gitea/gitea#26765]
### Description

Errors like
```
2023/08/27 17:07:40 ...irror/mirror_pull.go:308:runSync() [E] [64eb66a8-2] SyncMirrors [repo: 2:someorg/somerepo]: failed to update size for mirror repository: updateSize: lstat /path/to/repo/someorg/somerepo.git/objects/05/tmp_obj_Y5itXx: no such file or directory
```
rarely occur in gitea 1.19 while syncing mirror. No such problem on next mirror sync.

### Gitea Version

1.19.3

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

Compiled from source.

### Database

MySQL

**Comment by CaiCandong** [comment]
Weird, the code already handles this situation 
https://github.com/go-gitea/gitea/blob/1e76a824bcd71acd59cdfb2c4547806bc34b3d86/modules/repository/create.go#L300-L304

**Comment by wxiaoguang** [comment]
Because, the fix is incomplete

![image](https://github.com/go-gitea/gitea/assets/2114189/d5eeb62b-cfca-4a9f-8015-157405ab982a)

**Comment by CaiCandong** [comment]
But the message he got is  the file doesn't exist

> lstat /path/to/repo/someorg/somerepo.git/objects/05/tmp_obj_Y5itXx: no such file or directory

**Comment by wxiaoguang** [comment]
Yes, `info.Info()` calls `lstat`
