### ISSUE TITLE
Workflow disabled, timed task still executing

### ISSUE THREAD

**Issue by haisto** [go-gitea/gitea#26782]
### Description

![动画](https://github.com/go-gitea/gitea/assets/28912248/78d2f381-6b53-49df-842e-58c4c8475dd0)

### Gitea Version

1.21.0+dev-651-g60ca3d04a

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

alpine 3.9

### Database

SQLite

**Comment by yp05327** [comment]
It seems that we need a general function like CanRunJob.
