### ISSUE TITLE
Manage Organizations in User settings will broken when org name is too long

### ISSUE THREAD

**Issue by yp05327** [go-gitea/gitea#26787]
### Description

![image](https://github.com/go-gitea/gitea/assets/18380374/5e5f4d96-0c91-450e-98bd-976dd4e93b34)

### Gitea Version

latest

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

build

### Database

None

**Comment by puni9869** [comment]
I wil take it forward.

**Comment by lng2020** [comment]
is it okay to close it? Now the max length of org name, full name, and description is 40, 100, and 255. There seems to be no problem here.

**Comment by puni9869** [comment]
Could you test it once again, At my end it was lil flaky.

**Comment by yp05327** [comment]
I created a new organization in the latest version and there are no changes:
![image](https://github.com/go-gitea/gitea/assets/18380374/6138d781-963a-435e-9787-f1cd8a500762)
![image](https://github.com/go-gitea/gitea/assets/18380374/b060b8eb-91bf-45b2-a76f-95a2ee7ae5a7)

**Comment by yp05327** [comment]
> is it okay to close it? Now the max length of org name, full name, and description is 40, 100, and 255. There seems to be no problem here.

I don't understand the relationship between max length of these settings and the broken UI here.

**Comment by lng2020** [comment]
Sorry for the misunderstanding, I thought it was link somehow broken. I can see the problem here: the text won't have a new line although the name is long

**Comment by yp05327** [comment]
This issue has been fixed, as web UI is redesigned.
