### ISSUE TITLE
Enable PAM on releases

### ISSUE THREAD

**Issue by r3pek** [go-gitea/gitea#2679]
- Gitea version (or commit ref): v1.2.0-rc3
- Git version: 1.8.3.1
- Operating system: CentOS 7
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:

## Description
Releases made available from GitHub are not compiled with the PAM module. Please enable it so it can be used. Since it's not enabled (but it still appears as and Auth provider in the Admin settings), i tried to set it up until I saw in the logs:
`2017/10/09 00:44:19 [W] Failed to login 'xxxxxxx' via 'PAM': PAM not supported`

Thanks!

**Comment by lunny** [comment]
Since PAM needs CGO, it's not the default compiled version currently. But I agree the PAM option UI should be hidden if PAM is not supported on the binary.

**Comment by r3pek** [comment]
What's CGO?

**Comment by bkcsoft** [comment]
CGO is a way to call C-functions from Go. https://golang.org/cmd/cgo/
