### ISSUE TITLE
branch protection

### ISSUE THREAD

**Issue by continue98** [go-gitea/gitea#26801]
### Description

Hi, for some reason my branch protection for the master is not working for me. I have a team created, this team has been added to the repository. 
![image](https://github.com/go-gitea/gitea/assets/12125634/c2bbc449-847c-496f-8413-e7a2a87b31c3)

I'm trying to do a direct push to master (w/o PR). And guess what? I can do it!

What could be the problem (I'm not sure if it's a bug, maybe a configuration issue)

### Gitea Version

1.20.3

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/12125634/6a99fa54-22e3-4a07-b64d-3db230e2b1ab)
![image](https://github.com/go-gitea/gitea/assets/12125634/ea2fb6cb-8d67-4f95-a469-43f9df8c3cd7)
![image](https://github.com/go-gitea/gitea/assets/12125634/c72c42b8-5cc0-4922-a304-8f19a6315386)
![image](https://github.com/go-gitea/gitea/assets/12125634/4b25a3df-7c30-409e-9958-b22f10cb4246)

### Operating System

Manjaro Linux

### How are you running Gitea?

in docker

### Database

PostgreSQL

**Comment by jolheiser** [comment]
I see you have `code-review` for the branch protection pattern rather than `master`, so this only protects a branch named `code-review`.

As well, you are allowing pushes (but not force pushes) for anyone with write access.

**Comment by continue98** [comment]
@jolheiser thk u....
