### ISSUE TITLE
Can't add issue label

### ISSUE THREAD

**Issue by IamRezaMousavi** [go-gitea/gitea#26817]
### Gitea Version

Gitea version 1.20.3 built with GNU Make 4.2.1, go1.20.7 : bindata, sqlite, sqlite_unlock_notify

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![Screenshot from 2023-08-30 13-24-58](https://github.com/go-gitea/gitea/assets/83984878/c95e8406-8035-4510-9172-8e6c99198017)

### How are you running Gitea?

command-line

### Database

None

**Comment by eeyrjmr** [comment]
Have you created any lables, either manually or from a preconfigured list?

This is done at org level and at repo level

**Comment by IamRezaMousavi** [comment]
> Have you created any lables, either manually or from a preconfigured list?
> 
> This is done at org level and at repo level

I want to choose from preconfigured list
How is it?

**Comment by IamRezaMousavi** [comment]
> So gitea comes with a simple preconfigured list (big, enhancement etc...)
> 
> This can be set via going to the ISSUE section of a repo and there is an option for label and milestone. From there you can choose the example labels
> 
> A similar thing can be done from the org config

Yes but I have no preconfigured label to choose
![Screenshot from 2023-08-30 14-05-09](https://github.com/go-gitea/gitea/assets/83984878/b714807d-4c02-43c5-b76c-7410cef1729a)

**Comment by eeyrjmr** [comment]
Not that screen, in the main issues screen where there is a list of issues 

![Screenshot_20230830-124441](https://github.com/go-gitea/gitea/assets/4564448/3c09f3f4-e4a4-4d83-8c61-9ba6b04f64f9)

You will have a drop down for DEFAULT and ADVANCED
![Screenshot_20230830-124603](https://github.com/go-gitea/gitea/assets/4564448/33866f14-8ea0-4d48-b977-32ca50c64065)


These are the two default lists provided by gitea. I would advise you to make your own list at a future point when you know what works best for you

https://docs.gitea.com/usage/labels

**Comment by IamRezaMousavi** [comment]
> Not that screen, in the main issues screen where there is a list of issues
> 
> ![Screenshot_20230830-124441](https://user-images.githubusercontent.com/4564448/264317655-3c09f3f4-e4a4-4d83-8c61-9ba6b04f64f9.png)
> 
> You will have a drop down for DEFAULT and ADVANCED ![Screenshot_20230830-124603](https://user-images.githubusercontent.com/4564448/264318031-33866f14-8ea0-4d48-b977-32ca50c64065.png)
> 
> These are the two default lists provided by gitea. I would advise you to make your own list at a future point when you know what works best for you
> 
> https://docs.gitea.com/usage/labels

Thank you :))
