### ISSUE TITLE
cron actions does not show current branch.

### ISSUE THREAD

**Issue by ExplodingDragon** [go-gitea/gitea#26815]
### Description

cron actions does not show the current branch,

### Screenshots

![图片](https://github.com/go-gitea/gitea/assets/33776693/765d5fc3-cf76-4833-8a6e-e15a05834b36)

![图片](https://github.com/go-gitea/gitea/assets/33776693/9a5ac8fb-89bd-4419-be4e-662ffef7e27c)

### Gitea Version

main (476b9d1589)

### Can you reproduce the bug on the Gitea demo site?

Yes

### Browser Version

firefox last stable

**Comment by lng2020** [comment]
It seems to work for me. What's the procedure to produce?
<img width="295" alt="image" src="https://github.com/go-gitea/gitea/assets/70063547/d39cdf10-af65-4964-bae0-7e270dd8e305">

**Comment by ExplodingDragon** [comment]
> It seems to work for me. What's the procedure to produce? <img alt="image" width="295" src="https://user-images.githubusercontent.com/70063547/265712716-d39cdf10-af65-4964-bae0-7e270dd8e305.png">

Sorry, I can't seem to reproduce it now.

**Comment by lunny** [comment]
Let's close now and reopen when somebody encounter it again.
