### ISSUE TITLE
Organization level counters

### ISSUE THREAD

**Issue by KazzmanK** [go-gitea/gitea#26826]
### Description

Inspired by https://github.com/go-gitea/gitea/issues/26456 I`ve created an org level project and suddenly realized that org level counters are missing.
Repository counter is in place, but Projects, Members and Teams are not.

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/13328513/23c9ecc2-1a4d-4153-8b12-acc729507b08)

### Gitea Version

1.20.3

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

win

### Browser Version

116

**Comment by silverwind** [comment]
IIRC, this was fixed in v1.21, please verify on https://try.gitea.io.

**Comment by KazzmanK** [comment]
I have tried, but found no way to create an organization, to see organization-level dashboard.

**Comment by KazzmanK** [comment]
It is not well-fixed as of Version:
[1.21.0+dev-678-gc35b16a9a]
projects counter missing
![image](https://github.com/go-gitea/gitea/assets/13328513/ecba7e5b-07ab-4de4-a048-eb0e045cd805)
Still missing projects counter
![image](https://github.com/go-gitea/gitea/assets/13328513/63b4a509-62dd-43fb-bea3-aac3e1295f26)

Repository counter missing AND THIS IS A REGRESSION
![image](https://github.com/go-gitea/gitea/assets/13328513/99f40214-4f94-4eb1-b123-a0d4eecdea38)

Repo and Project counters missing
![image](https://github.com/go-gitea/gitea/assets/13328513/51440933-dd11-446a-953a-57bba37b7728)

**Comment by JakobDev** [comment]
I have currently [a PR open for package counters](https://github.com/go-gitea/gitea/pull/26467). I will open another PR for the other ones after this is merged, as I don't want a merge conflict. I can also update the PR to include other counters as well.

**Comment by silverwind** [comment]
Ah yes, that was the PR, thought it had already merged. Will try to review it soon.

**Comment by lng2020** [comment]
Fixed by #26842 and #26942

**Comment by CaiCandong** [comment]
> Fixed by #26842 and #26942
