### ISSUE TITLE
Make "gitea dump" respect hardlinks for backup

### ISSUE THREAD

**Issue by mxmehl** [go-gitea/gitea#2682]
## Description

If I understand correctly, Gitea uses hard links for forked repositories which saves considerable amount of space. Unfortunately, `gitea dump` saves each file individually because `zip` cannot work with hard links and dereferences them. By that, large repositories which are forked multiple times take up a lot of space in the backup.

I propose to use `tar` instead which can cope with hard links. However, I'm not sure whether this is compatible with Gitea on other systems than GNU/Linux, or how hard links work on such operating systems.

**Comment by bkcsoft** [comment]
Gitea does no such thing. `git clone` however does that. And it's nothing Gitea can keep track of and is just "random git magic" that we can't handle efficently in `gitea dump`. And while it's not explicitly stated, `gitea dump` is sort-of depricated and unmaintained in favour of #1637

**Comment by mxmehl** [comment]
@bkcsoft Thanks for working on `backup`. However, I wonder why you cannot use tar instead of zip. This would preserve the magic git created while zip breaks these hard links AFAIK.

**Comment by bkcsoft** [comment]
Baiscally because Windows compatibility :/

**Comment by XANi** [comment]
what "windows compability" ? pretty much any popular archive manager supports .tar.gz
