### ISSUE TITLE
PR's status doesn't update automatically when I do a branch merge locally

### ISSUE THREAD

**Issue by CaiCandong** [go-gitea/gitea#26836]
### Description

Reproduction：
1. Initialize a repository locally and open two branches, `main` and `pr`
```
git init
git checkout -b main
touch README.md
git add README.md
git commit -m "first commit"
git remote add origin http://host/user/repo.git
echo abc >> readme.md && git commit -am "abc"
git checkout -b pr
echo efg >> readme.md && git commit -am "efg"
```
2. Push both `main` and `pr` to gitea.
```
git push origin --all
```
3. Create a PR on gitea
![image](https://github.com/go-gitea/gitea/assets/50507092/5e32c315-8a6a-4876-8bef-2274a9e01fa5)

4. Finish branch merge push to remote repository locally
```
git switch main 
git merge pr
git push origin main 
```
5. Result
![image](https://github.com/go-gitea/gitea/assets/50507092/8b0bc84d-2add-4fc5-8fcd-7b05e1894925)

### Gitea Version

try.gitea.io

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

try.gitea.io

### Database

None

**Comment by CaiCandong** [comment]
I found that the error had to do with this option, which is off by default, but when I made the error, gitea didn't give me any indication to turn it on, which is very impersonal.

![image](https://github.com/go-gitea/gitea/assets/50507092/6248d4c0-5a55-4fa0-b327-1dd11efb4fc6)

**Comment by yp05327** [comment]
> I found that the error had to do with this option, which is off by default, but when I made the error, gitea didn't give me any indication to turn it on, which is very impersonal.

So this is not a bug? As we have this option.
