### ISSUE TITLE
Guest / tester issue reporting

### ISSUE THREAD

**Issue by hubyhuby** [go-gitea/gitea#2684]
I am in a use case scenario, where I want the testers to test my software but not to download my code. Imagine a company making games, doesn t want its tester to download the source code.

In Gitlab I can set a guest user on a specific project. (maybe the equivalent of Collaborators.)
The Guest user has only the right to post Bugs and issues. But cannot see the files / code on the repository.

So I tried all kind of configuration, such as colaborator and team (in private projects).
But in the end I cannot get to have a user who can only post issues.

With this team configuration I thought it would work. If you can t see the code but write , then you should be able to post issues.right? ;) But it doesn t work. In this case there is no "New issue" button, and when I click on an issue I get a 404 error

![screenshot at 2017-10-10 15-59-23](https://user-images.githubusercontent.com/26340942/31390536-763339fc-add4-11e7-90b6-d969a26fb79f.png)

PS: tried with gogs no luck aswell (less functionalities aswell)

Gitea 1.2RC3

**Comment by hubyhuby** [comment]
Guest view in Gitlab for example:

![screenshot at 2017-10-10 18-43-59](https://user-images.githubusercontent.com/26340942/31399028-2e2a33e2-adeb-11e7-8fc8-6eb371ee3701.png)

**Comment by Morlinest** [comment]
~What version are you using?~ I've tried it on try.gitea.io just now. Public org, private repo, team only with issues and wiki enabled for read:
![image](https://user-images.githubusercontent.com/12720041/31431831-0ec4e094-ae75-11e7-92e3-afd9d213a871.png)

**Comment by Morlinest** [comment]
Also working with your setup (write access, everything except Code enabled)

![image](https://user-images.githubusercontent.com/12720041/31432056-d7118a98-ae75-11e7-97a9-6593c26ef9f2.png)

**Comment by hubyhuby** [comment]
Hi @Morlinest , thanks for your answer. That s exactly what I would like to get ;) Better looking than 404 :D   
What I basically do then is try to connect with a user of the team defined, but I only got 404. That s the reason I thought the feature didn t exist. Now I have hope !!! 
I am trying and trying again...but no sucess from that side of the internet...

What do you mean by "Public org," and "team only", where do you find those aprameters ?
I have a "customer team" with the previous parameters set, 

![bug](https://user-images.githubusercontent.com/26340942/31442745-aa1527c6-ae97-11e7-89ec-5400fc573aef.png)

Finally I cannot get in the admin of "try.gitea.io" to try it out....

**Comment by Morlinest** [comment]
@hubyhuby I see your problem from screenshot. You have to add repositories to your team. Now there is bug when you see every repository (in repository list, dashboard, ...) in organization even you shouldn't as you don't have rights to do anything with repo (mentioned in few issues, #2689 should fix it).

I was talking about my setup, nothing important now.

**Comment by jonasfranz** [comment]
Bes sure that you are using the latest release or the latest master build since there was a bug which enabled issues only useres to fork the repository and gain access to the code.

**Comment by hubyhuby** [comment]
Yeah ! got it to work. Thanks a lot
So now maybe one little comment:
- The way you display "0 repository" is a link, which is counter intuitive. Because the behavior of such link every where else is to bring you to another page... Which in this case means AWAY from the team configuration page. Samething for "1 users"
Therefore when you arrive on this page, you think there is only one parameter to a team, which is "members"'

![guiteam](https://user-images.githubusercontent.com/26340942/31451263-f6f4dd2a-aeab-11e7-9471-dfe1177b6211.png)
