### ISSUE TITLE
Cannot migrate repo owned by organization with API

### ISSUE THREAD

**Issue by nickmi** [go-gitea/gitea#26846]
### Description

When i try to use the API to migrate a repo from a github organization to gitea, it fails with the following error: 

Request:

```bash
curl -X POST "http://{{EXTERNAL_IP}}:{{GITEA_PORT}}/api/v1/repos/migrate" \
     -H "Content-Type: application/json" \
     -H "Authorization: token xxx" \
     -d '{
        "clone_addr": "https://github.com/organizationxxx/xxxz.git",
        "auth_token": "xxx",
        "description": "Migrate sample",
        "private": true,
        "repo_name": "xxx",
        "repo_owner": "xxx",
        "mirror": true
     }'
```

Response:

```json
{
   "message":"Given user is not an organization.",
   "url":"http://localhost:3000/api/swagger"
}
```

The same operation works fine from the web interface, without the need that the user is an organization.

### Gitea Version

1.20.1

### How are you running Gitea?

Docker

### Database

SQLite
###

**Comment by puni9869** [comment]
Please upgrade to the newer version 1.20.4. Might works.

**Comment by nickmi** [comment]
Thank you guys for your response, i cant reproduce the issue anymore. I suspect it had something to do with my access token. I am closing the issue.
