### ISSUE TITLE
As an owner of an organisation and I cant accept request for receive the repository transfer to that organisation

### ISSUE THREAD

**Issue by Shakthijuego** [go-gitea/gitea#26840]
### Description

We are checking the request to transfer ownership of a repository to another organization. I am the owner of the organization, however( I believe this is the precondition.) However, I am not getting the option to approve in the UI.

### Gitea Version

gitea-1.20.2

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

<img width="1286" alt="Screenshot 2023-08-31 at 12 19 56 PM" src="https://github.com/go-gitea/gitea/assets/25612450/0b29ae95-4435-4222-985d-6234a74e19a4">

### Operating System

ubuntu

### How are you running Gitea?

on nginx proxy

### Database

SQLite

**Comment by wxiaoguang** [comment]
The workaround: https://github.com/go-gitea/gitea/issues/26491#issuecomment-1678325433

The fix:  Add fix incorrect can_create_org_repo for org owner team #26683

**Comment by otbutz** [comment]
@wxiaoguang is this something that needs manual intervention?

**Comment by wxiaoguang** [comment]
Has it been resolved? 🙏

**Comment by wxiaoguang** [comment]
Close as completed, feel free to reopen if there is any problem. Thank you!
