### ISSUE TITLE
Queue unexpected type conversion

### ISSUE THREAD

**Issue by KN4CK3R** [go-gitea/gitea#26843]
### Description

```go
q := queue.CreateSimpleQueue(
	graceful.GetManager().ShutdownContext(),
	"interface",
	func(data ...any) []any {
		for _, d := range data {
			fmt.Printf("<- %#v (%T)\n", d, d)
		}
		return nil
	},
)

go graceful.GetManager().RunWithCancel(q)

push := func(val any) {
	fmt.Printf("-> %#v (%T)\n", val, val)
	q.Push(val)
}

push(int64(1))
push(1)
```

Expected:
```
-> 1 (int64)
<- 1 (int64)
-> 1 (int)
<- 1 (int)
```

Actual:
```
-> 1 (int64)
<- 1 (float64)
-> 1 (int)
<- 1 (float64)
```

Somewhere there is an unexpected type conversion in the code.

@wxiaoguang You touched the queues last, it's yours 😄

**Comment by wxiaoguang** [comment]
It's an old behavior inherited from the old system.

Because, the "queue" uses JSON to marshal the items.

**Comment by wxiaoguang** [comment]
Such behavior came from #9363

Would you like to change the behavior in the future, or keep it?

**Comment by KN4CK3R** [comment]
I thought so but only "expected" that behaviour when using external queues like redis. I found it yesterday when writing tests for my audit PR. The check `assert.Equal(t, case.Scope.PrimaryKey, expected.Scope.PrimaryKey)` failed because of the different types.
I think we should use a different marshal method like https://pkg.go.dev/encoding/gob 

Why do we need marshalling at all in the normal flow? I would expect that it is only used when writing the queue to disk or similar.

**Comment by wxiaoguang** [comment]
> The check assert.Equal(t, case.Scope.PrimaryKey, expected.Scope.PrimaryKey) failed because of the different types.

At the moment, it is not a serous problem, because you could use typed handler: `func(data ...int64) []int64 {`, then there won't be any problem (do not use `any`)

> Why do we need marshalling at all in the normal flow? I would expect that it is only used when writing the queue to disk or similar.

Yes, for persistence.

**Comment by wxiaoguang** [comment]
I guess you need to use `string`, or wrap your content into another encoding (eg: base64).

**Comment by KN4CK3R** [comment]
Tested that but it's not flexible enough because you need to register (some) custom types:
> Failed to unmarshal item from queue "interface": gob: local interface type *interface {} can only be decoded from remote interface type; received concrete type int

I stopped testing at that point but it may be a simple error.

**Comment by wxiaoguang** [comment]
Didn't see any problem, what's your code?

```go
package main

import (
	"bytes"
	"encoding/gob"
	"fmt"
	"log"
)

type Sub struct {
	V any
}

type Msg struct {
	V1, V2 any
}

func main() {
	gob.Register(Sub{})

	buf := new(bytes.Buffer)
	enc := gob.NewEncoder(buf)
	dec := gob.NewDecoder(buf)

	err := enc.Encode(Msg{1, Sub{2}})
	if err != nil {
		log.Fatal("encode error:", err)
	}

	var m Msg
	err = dec.Decode(&m)
	if err != nil {
		log.Fatal("decode error 1:", err)
	}
	fmt.Printf("%#v\n", m)
}
```

```
main.Msg{V1:1, V2:main.Sub{V:2}}
```

**Comment by wxiaoguang** [comment]
What's your queue item `T` ?

**Comment by KN4CK3R** [comment]
any

**Comment by wxiaoguang** [comment]
Is it still a problem? I can see your PR is using `*Event` for `T`

**Comment by KN4CK3R** [comment]
It's not a critical problem. The PR functionality is not really affected at the moment. I just noticed it in the tests: https://github.com/go-gitea/gitea/pull/24257/files#diff-4d7ef1c8a608b4af111d9e1cbf85a844314a9c198dec098dbec005904ba5c464R149
