### ISSUE TITLE
Branch Protection Unprotected file patterns not working

### ISSUE THREAD

**Issue by aHcVolle** [go-gitea/gitea#26845]
### Description

I was using the unprotected file patterns for branch protection earlier and everything was working as expected.
Since updating (sorry i have no idea from which version I did update) this seems to be not working anymore.
I cannot push to the protected branch even if the filename should match the filter.

Example:
Setup a repo with enabled branch protection for branch main with disabled push and unprotected file patterns for "test*".
Try to push a file "testfile.txt" -> "Not allowed to push to protected branch main"

This was working before but i'm note sure which version i updated from.

### Gitea Version

1.20.3

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

debian

### How are you running Gitea?

I'm running gitea in the latest docker container but this problem exists in try.gitea.io, too.

### Database

None

**Comment by lng2020** [comment]
I followed your instructions but the rule worked well. 
Is there another commit that includes a protected file? Can you please give more specificated information?

**Comment by aHcVolle** [comment]
OK, I just gave this another try but I still cannot push a file in my test repo on try.gitea.io.
Maybe I'm understanding it somehow wrong.
I've attached a screenshot which shows my repo settings and the error message. This is the only commit that is pending to be pushed...
![prot_test](https://github.com/go-gitea/gitea/assets/6406817/7c9f8f96-d19b-46c2-8857-531cb8d3c632)

**Comment by lng2020** [comment]
> OK, I just gave this another try but I still cannot push a file in my test repo on try.gitea.io. Maybe I'm understanding it somehow wrong. I've attached a screenshot which shows my repo settings and the error message. This is the only commit that is pending to be pushed... ![prot_test](https://user-images.githubusercontent.com/6406817/264961663-7c9f8f96-d19b-46c2-8857-531cb8d3c632.png)

thanks for your patience! I encounter the same issue now. I'm looking into it.

**Comment by lng2020** [comment]
We use `.` and `/` as separators. So in the matching pattern, the file extension should be specified. `prot_test*.*` or `prot_test**` will solve your problem.
