### ISSUE TITLE
Inaccurate display of "Viewed" count in file diff when expanding files

### ISSUE THREAD

**Issue by Menah3m** [go-gitea/gitea#26854]
### Description

I have observed a bug in Gitea's file diff feature regarding the display of "Viewed" count in the context of expanding files.

I have configured the "MAX_GIT_DIFF_LINES:200" and "MAX_GIT_DIFF_FILES:20" settings in  app.ini . However, when I expand files in the diff view, the "Viewed" count appears to be inaccurately tracked. Specifically, clicking "View More" seems to reset the viewed count and sometimes even results in a negative count when unchecking previously viewed files.

### Gitea Version

1.19.3

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

<img width="1610" alt="image" src="https://github.com/go-gitea/gitea/assets/24191438/9f1a61ad-36d5-4595-a8ab-b3892ef3c647">

### Git Version

1.8.3.1

### Operating System

centos 7

### How are you running Gitea?

it is being run from a helm chart.

### Database

PostgreSQL

**Comment by delvh** [comment]
I think that bug was already fixed, please update to 1.20.
