### ISSUE TITLE
How to auto release in act runner?

### ISSUE THREAD

**Issue by JohnnyZhang0628** [go-gitea/gitea#26855]
### Feature Description

I try to use `https://gitea.com/actions/release-action`,it depend on go env.
![image](https://github.com/go-gitea/gitea/assets/28375774/05d6a255-dea4-469d-ba84-d06576e135bc)
I'm from china,it spend too much time.
![image](https://github.com/go-gitea/gitea/assets/28375774/17102ce8-fd5d-439e-9c57-5275b8675d2d)

Do you have another plugin i can use

**Comment by lng2020** [comment]
![PBSK5Q``F9{UR} OSF ZTDE](https://github.com/go-gitea/gitea/assets/70063547/ddb6126f-830a-4f50-aae6-c032ec235342)
config env or fork your own version `Release` may solve your problem
