### ISSUE TITLE
configure-gitea init error panic

### ISSUE THREAD

**Issue by SchisandraX** [go-gitea/gitea#26857]
### Description

2023/09/01 05:53:10 .../cli@v1.22.13/app.go:410:RunAsSubcommand() [I] PING DATABASE postgres
2023/09/01 05:53:10 .../cli@v1.22.13/app.go:410:RunAsSubcommand() [W] Table system_setting Column version db default is , struct default is 1
2023/09/01 05:53:11 .../cli@v1.22.13/app.go:410:RunAsSubcommand() [W] Table oauth2_application Column confidential_client db default is true, struct default is TRUE
2023/09/01 05:53:11 .../cli@v1.22.13/app.go:410:RunAsSubcommand() [W] Table user Column max_repo_creation db default is '-1', struct default is -1
Wait for redis to become avialable...
wukong-redis-cluster-headless.wentest.svc.cluster.local (10.42.1.126:6379) open
Admin account 'xxxx' already exist. Running update to sync password...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x50fa3a]

goroutine 1 [running]:
fmt.Fprintf({0x0, 0x0}, {0x328870b, 0x12}, {0xc00337e780, 0x1, 0x1})
	/usr/local/go/src/fmt/print.go:225 +0x7a
code.gitea.io/gitea/cmd.RunMainApp(0xc0034ae1c0, {0xc000052080?, 0x4?, 0xc00337e978?})
	/go/src/code.gitea.io/gitea/cmd/main.go:23 +0xc7
main.main()
	/go/src/code.gitea.io/gitea/main.go:166 +0xc2

### Gitea Version

1.20.3

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

k8s 

### Database

PostgreSQL

**Comment by wenchao5211** [comment]
This error doesn't exist after gitea pod restarts automatically a few times, but I think it's a problem

**Comment by wxiaoguang** [comment]
It should have been fixed by "Set errwriter for urfave/cli v1 #26616"

You can use the nightly build.
