### ISSUE TITLE
Members of an organization cannot open a private repository (owned by the organization)

### ISSUE THREAD

**Issue by nardhar** [go-gitea/gitea#2686]
- Gitea version (or commit ref): 1.2.0
- Git version: 1.8.3.1
- Operating system: Centos 7
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description

1. Fresh installed Gitea
2. Created three users: **SampleOwner**, **SampleCollab**, **SampleExternal**
3. Logged as **SampleOwner**
4. Created an organization **SampleOrganization** and added **SampleCollab** as a member
5. Created a private repository and set **SampleOrganization** as owner
6. Logged as **SampleCollab** and can view the repo in the explore tab, but gets a 404 page when tries to open it

Apparently the problem is that it does not add the **SampleCollab** user as a collaborator since it is a member of the owner organization, I guess it should be allowed to be added nevertheless, I'll investigate more and post more details about this

Thks in advance

**Comment by daviian** [comment]
A member needs to be in a team to have sufficient access rights to repositories.
We have already discussed removing the `add member` option from UI as it causes confusion and troubles.

Duplicate from #2562, #2593, #1794 and closely related to #2399

**Comment by nardhar** [comment]
having a team as owner works perfectly, but I expected that an organization would work the same, guess I will take the team approach as suggested.

Thanks for the quick response
