### ISSUE TITLE
HTTP error 500 when parsing publication on large repository

### ISSUE THREAD

**Issue by lds-lds** [go-gitea/gitea#2688]
- Gitea version (or commit ref): 1.0.1
- Git version: 2.7.4
- Operating system: Ubuntu 16.04.3 LTS
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x ] No
- Log gist:
[Macaron] 2017-10-11 11:00:47: Started GET /test/my_koha/releases for 10.215.181.10
2017/10/11 11:00:47 [D] Session ID: a523cea541144fee
2017/10/11 11:00:47 [D] CSRF Token: cnccvN16834ZuPMJoE-bpzi86Q46MTUwNzcxMTk3MjU1OTI2MzQ1MQ==
[Macaron] PANIC: runtime error: index out of range
/usr/local/go/src/runtime/panic.go:458 (0x434203)
/usr/local/go/src/runtime/panic.go:27 (0x432add)
/srv/app/src/code.gitea.io/gitea/vendor/code.gitea.io/git/signature.go:35 (0x6825a4)
/srv/app/src/code.gitea.io/gitea/vendor/code.gitea.io/git/repo_commit.go:70 (0x67c7ce)
/srv/app/src/code.gitea.io/gitea/vendor/code.gitea.io/git/repo_commit.go:108 (0x67d14d)
/srv/app/src/code.gitea.io/gitea/vendor/code.gitea.io/git/repo_commit.go:133 (0x67d33e)
/srv/app/src/code.gitea.io/gitea/vendor/code.gitea.io/git/repo_commit.go:151 (0x67d5b4)
/srv/app/src/code.gitea.io/gitea/routers/repo/release.go:106 (0x944a66)
/usr/local/go/src/runtime/asm_amd64.s:479 (0x463ffc)
/usr/local/go/src/reflect/value.go:434 (0x9f7b78)
/usr/local/go/src/reflect/value.go:302 (0x9f7494)
/srv/app/src/code.gitea.io/gitea/vendor/github.com/go-macaron/inject/inject.go:177 (0xccb1b3)
/srv/app/src/code.gitea.io/gitea/vendor/github.com/go-macaron/inject/inject.go:137 (0xccab72)
/srv/app/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/context.go:113 (0x99cac2)
/srv/app/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/context.go:104 (0x99c9e6)
/srv/app/src/code.gitea.io/gitea/vendor/github.com/go-macaron/session/session.go:186 (0x994f65)
/usr/local/go/src/runtime/asm_amd64.s:479 (0x463ffc)
/usr/local/go/src/reflect/value.go:434 (0x9f7b78)
/usr/local/go/src/reflect/value.go:302 (0x9f7494)
/srv/app/src/code.gitea.io/gitea/vendor/github.com/go-macaron/inject/inject.go:177 (0xccb1b3)
/srv/app/src/code.gitea.io/gitea/vendor/github.com/go-macaron/inject/inject.go:137 (0xccab72)
/srv/app/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/context.go:113 (0x99cac2)
/srv/app/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/context.go:104 (0x99c9e6)
/srv/app/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/recovery.go:161 (0x9afadb)
/usr/local/go/src/runtime/asm_amd64.s:479 (0x463ffc)
/usr/local/go/src/reflect/value.go:434 (0x9f7b78)
/usr/local/go/src/reflect/value.go:302 (0x9f7494)
/srv/app/src/code.gitea.io/gitea/vendor/github.com/go-macaron/inject/inject.go:177 (0xccb1b3)
/srv/app/src/code.gitea.io/gitea/vendor/github.com/go-macaron/inject/inject.go:137 (0xccab72)
/srv/app/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/context.go:113 (0x99cac2)
/srv/app/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/context.go:104 (0x99c9e6)
/srv/app/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/logger.go:43 (0x9aecae)
/usr/local/go/src/runtime/asm_amd64.s:479 (0x463ffc)
/usr/local/go/src/reflect/value.go:434 (0x9f7b78)
/usr/local/go/src/reflect/value.go:302 (0x9f7494)
/srv/app/src/code.gitea.io/gitea/vendor/github.com/go-macaron/inject/inject.go:177 (0xccb1b3)
/srv/app/src/code.gitea.io/gitea/vendor/github.com/go-macaron/inject/inject.go:137 (0xccab72)
/srv/app/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/context.go:113 (0x99cac2)
/srv/app/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/router.go:184 (0x9b0e6c)
/srv/app/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/router.go:286 (0x9a903e)
/srv/app/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/macaron.go:177 (0x9a135b)
/usr/local/go/src/net/http/server.go:2202 (0x6de80d)
/usr/local/go/src/net/http/server.go:1579 (0x6db217)
/usr/local/go/src/runtime/asm_amd64.s:2086 (0x466b61)
[Macaron] 2017-10-11 11:00:47: Completed /test/my_koha/releases 500 Internal Server Error in 355.867178ms

## Description
HTTP error 500 when parsing publication
the error is systematic on very large git depots like koha
to reproduce the error you can create a new migration with this repository->  https://github.com/Koha-Community/Koha.git

il try to set max value on systemd launcher for gitea, but it does not correct the error
LimitMEMLOCK=infinity
LimitNOFILE=1024000

...

**Comment by jonasfranz** [comment]
Do you tried to upgrade to v1.1 or v1.2?

**Comment by lds-lds** [comment]
I just upgraded to 1.2 and thanks the error disappears, but how to see all tags like "git ls-remote --tags --refs" ?

**Comment by lafriks** [comment]
@ldsbiblibre what do you mean by that? Your command seems to work just fine:
```
C:\Temp> git clone https://try.gitea.io/lafriks/test.git
Cloning into 'test'...
remote: Counting objects: 51, done.
remote: Compressing objects: 100% (36/36), done.
remote: Total 51 (delta 16), reused 0 (delta 0)
Unpacking objects: 100% (51/51), done.
C:\Temp> cd .\test\
C:\Temp\test [master ≡]> git ls-remote --tags --refs
192888402d6aef6ae6041e10f3b4a4fa1ac5c193        refs/tags/v0.0.1
From https://try.gitea.io/lafriks/test.git
C:\Temp\test [master ≡]>
```

**Comment by lafriks** [comment]
Closing issue as original issue is fixed
