### ISSUE TITLE
Profile Gravatar image won't load

### ISSUE THREAD

**Issue by cairoapcampos** [go-gitea/gitea#26900]
### Description

When I access the Gitea profile, it takes a while to load the image. At the end of loading it shows the default image. Look:

![perfil](https://github.com/go-gitea/gitea/assets/21186839/bc82cc0e-ba96-4e4b-a2b2-35c19b67ef70)

I've already tried to access Gitea directly by IP to escape the Reverse Proxy. The problem continued.

**Settings:**

Environment variables in Docker:

```
...
GITIA__picture__DISABLE_GRAVATAR="false"
GITIA__picture__ENABLE_FEDERATED_AVATAR="true"
...
```

Gitea's app.ini (`/etc/gitea/app.ini`) file after creating the container:

```
...
[picture]                                        
AVATAR_UPLOAD_PATH = /var/lib/gitea/data/avatars
REPOSITORY_AVATAR_UPLOAD_PATH = /var/lib/gitea/data/gitea/repo-avatars
DISABLE_GRAVATAR = false  
...
```

### Gitea Version

 1.20.3

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

I use the official image for docker. Currently the image used is `1.20.3-rootless`.

### Database

MySQL/MariaDB

**Comment by lunny** [comment]
You enabled gravatar
```ini
DISABLE_GRAVATAR = false  
```
So maybe you can open you chrome dev console to investigate whether your network is slow to visit Gravatar.

**Comment by cairoapcampos** [comment]
See some of my profile settings:

![Perfil1](https://github.com/go-gitea/gitea/assets/21186839/27774a75-9df9-4b43-a0e1-7ee99198f6ed)

Note: I hid the real email address and put an example address.

![Perfil2](https://github.com/go-gitea/gitea/assets/21186839/a05fa5bc-5f0a-4734-8ae4-b8b15ea73a33)

**Profile image loading test using Reverse Proxy.**

![ComProxy](https://github.com/go-gitea/gitea/assets/21186839/574ee16d-6bc3-4cf2-a972-dcd4e2a931ed)

**Profile image loading test without using proxy.**

![SemProxy](https://github.com/go-gitea/gitea/assets/21186839/7e3a623d-a869-4763-b5f0-6d0ffcea139e)


Below I show more information about the test that did not use a proxy. Access is via IP and port. **Example:** http://IP:8084.

![tela1](https://github.com/go-gitea/gitea/assets/21186839/46c60256-214e-4e0b-b0fa-cfd19e11b3db)


![tela2](https://github.com/go-gitea/gitea/assets/21186839/ad244b4c-6c62-44b2-9ccb-2f04574f0941)

**Comment by wxiaoguang** [comment]
> When I access the Gitea profile, it takes a while to load the image. 

It means that `ENABLE_FEDERATED_AVATAR="true"` service fails.

I guess you don't need it.
