### ISSUE TITLE
Why does it wrap line when there is a `-`?

### ISSUE THREAD

**Issue by devnakx** [go-gitea/gitea#26928]
### Description

[reproduce on Gitea demo](https://try.gitea.io/warren830/incubator-devlake/commit/ef26f305206e2e132b025e9e5a4032c8505d06f3#diff-2757f787dd4f39994593b6c102f652cddc28b5c1)
![3](https://github.com/go-gitea/gitea/assets/38558065/fe5213f2-32af-4900-9ee0-79207b6bef98)

### Gitea Version

1.21.0+dev-734-g473a8ae23

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

![1](https://github.com/go-gitea/gitea/assets/38558065/cd9540c8-baae-4a65-a902-9741a7879aae)
![2](https://github.com/go-gitea/gitea/assets/38558065/f3149757-f87b-4ac9-8c7d-93ac88d077a9)

### How are you running Gitea?

running Gitea on Docker and it built by myself with up to date source code

### Database

MySQL/MariaDB

**Comment by lng2020** [comment]
![image](https://github.com/go-gitea/gitea/assets/70063547/ee4da6a6-dd13-4098-ae76-e6e5b9accc69)
looks normal in my web browser (chrome offical-build, version: 116.0.5845.110)

**Comment by wxiaoguang** [comment]
What's your OS and browser? Are you using browser plugins? Could you try to start a clear browser instance without any plugin?

**Comment by devioa** [comment]
> What's your OS and browser? Are you using browser plugins? Could you try to start a clear browser instance without any plugin?

```
Windows 11 Pro 22H2 22621.2215 with Feature Experience Pack 1000.22662.1000.0
Cent Browser 5.0.1002.354 64bit (Chromium 102.0.5005.167)
```
I have also tried to disable all extensions or plugins and still

**Comment by wxiaoguang** [comment]
Cent Browser?

Could you also try Edge/Chrome/Firefox?

**Comment by devioa** [comment]
> Cent Browser?
> 
> Could you also try Edge/Chrome/Firefox?

It is normal in Edge
but it's strange, because of my browser kernel?

**Comment by wxiaoguang** [comment]
It seems a Cent Browser's bug. You could report it to the browser team.
