### ISSUE TITLE
Path to receive content from a repository's default branch

### ISSUE THREAD

**Issue by Andre601** [go-gitea/gitea#26920]
### Feature Description

(This has been discussed a little on the discord server)

There can be situations where you want to obtain content of a repository, but don't know the name of its default branch.

As an example, if I want to display a user profile readme in an app would I first need to obtain the repository to then get the default branch from and finally the file. This can waste API calls which, especially when unauthorized, could be somewhat limited depending on what other API requests are peformed and how frequent.

Another example could be a repository where you update the default branch whenever a new major release of your project is released, which would cause old URLs to break (Should you not keep them) or link to possible outdated sources, requiring you to update them.
With this feature could you keep the same URL and it would automatically redirect to the right file on the default branch.

Regarding the "name" of the branch would I go with `~` as it works in browsers and can't be used in a branch name itself, making it a perfect candidate to have for this function, without overriding any existing branch names a user may have.

As an example, assume a repository having a branch labeled `main`. Using `{user}/{repo}/src/branch/~/README.md` would be equal to `{user}/{repo}/src/branch/main/README.md`.
If the repo now has its default renamed to `default` would `{user}/{repo}/src/branch/~/README.md` now be equal to `{user}/{repo}/src/branch/default/README.md`

**Comment by KN4CK3R** [comment]
Indirect solution is to query the repo info first. There is a `default_branch` property.

**Comment by silverwind** [comment]
We should accept `HEAD` in place of the branch name, like GitHub:

https://github.com/go-gitea/gitea/blob/HEAD/README.md

Trying the same on gitea results in 404.

**Comment by silverwind** [comment]
Further investigation shows Gitea has unnecessary URL parts `/branch` and `/commit`, unlike github which puts them together into a [commit-ish](https://stackoverflow.com/a/23303550/808699) on the `/blob` path. So I'd say it should be added on at least these two paths:

```
/src/branch/main/README.md
/src/commit/hash/README.md
```
