### ISSUE TITLE
Gitea service fails to start (timeout 30 sec) on windows restart

### ISSUE THREAD

**Issue by KazzmanK** [go-gitea/gitea#26934]
### Description

I need an assistance to triage system restart issue. On windows restart Gitea service fails to start.
```
A timeout was reached (30000 milliseconds) while waiting for the Gitea service to connect.
```
```
The Gitea service failed to start due to the following error: 
The service did not respond to the start or control request in a timely fashion.
```
All the other services start successfully, Gitea have no dependencies (sqlite).
After seen a service down, manually it starts instantly.

No records in logs 
```
2023/09/06 09:31:07 cmd/web.go:195:serveInstalled() [I] PID: 3324 Gitea Web Finished
2023/09/06 10:15:49 ...les/setting/cache.go:75:loadCacheFrom() [I] Cache Service Enabled
```
where service start fail timestamp is 9:32:12

### Gitea Version

1.20.3

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

windows service

### Database

SQLite

**Comment by KazzmanK** [comment]
Setting service startup type to `Automatic-Delayed` solved problem for couple of test reboots. Just `Automaic `startup type results in timeout. 
`sc config Gitea start= delayed-auto
`
Should we update [documentation](https://docs.gitea.com/installation/windows-service) to hint possible issues ?
May be there is something under the hood of Gitea itself ?

**Comment by lunny** [comment]
Please help to send a PR to update documentation.

**Comment by KazzmanK** [comment]
My first try here
