### ISSUE TITLE
The color of scoped labels broken

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#26931]
### Gitea Version

latest

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

<img width="181" alt="图片" src="https://github.com/go-gitea/gitea/assets/81045/2410aa95-9011-4214-a925-ab71fd711edd">

### How are you running Gitea?

visit https://gitea.com/xorm/xorm/labels

### Database

None

**Comment by wxiaoguang** [comment]
->  Fix scoped label layout #26932
