### ISSUE TITLE
Gitea OAuth2  based SSO implementation not working

### ISSUE THREAD

**Issue by Shakthijuego** [go-gitea/gitea#26945]
### Description

We using a gitea as  SSO for internal Jenkins installation. However in the recent version of Gitea.   Jenkins successfully redirected to the git login screen. However, when the user enters their credentials it won't redirect back to Jenkins. It stays on the same page. Interestingly if the user is already logged in to Gitea, SSO perfectly works. ie When user click login on Jenkins screen they are taken to gitea login and redirected back to Jenkins with successful logon.

### Gitea Version

gitea-1.20.3

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![31cbb487ee619bcf70fc336c9bac826b6ba90096_2_1380x352](https://github.com/go-gitea/gitea/assets/25612450/bd6c4005-8ca4-4508-b7d2-77346733533c)

### How are you running Gitea?

Behind ssl enabled nginx proxy. Possibly issue started after ssl enabled.

### Database

SQLite

**Comment by Shakthijuego** [comment]
One more update. Issues seems to solved if we urlencode the redirect_uri.  I am not sure if this is the bug from gitea side or jenkins side. Please advice.  Jenkins seems doesn't have a option to configure the redirect url.

**Comment by wxiaoguang** [comment]
I think it will be fixed by 

-> Use strict protocol check when redirect #29642

**Comment by lunny** [comment]
Closed by #29642

**Comment by wxiaoguang** [comment]
> One more update. Issues seems to solved if we urlencode the redirect_uri. I am not sure if this is the bug from gitea side or jenkins side. Please advice. Jenkins seems doesn't have a option to configure the redirect url.

Actually Jenkins should encode the URL parameter correctly (every URL parameter should be escaped correctly), but Gitea could still tolerate the incorrect URL parameters .... so #29642 could fix the problem. The fix will be backported to 1.21, when the 1.21 nightly build is ready, you could take a try.
