### ISSUE TITLE
OAuth2 Account Linking configuration not working in Gitea v1.20.2 

### ISSUE THREAD

**Issue by dianaStr7** [go-gitea/gitea#26940]
### Description

I am experiencing an issue with configuring automatic account linking in my Gitea(version 1.20.2) setup. Based on my configuration, I expected users to be automatically linked to their accounts when they log in using OAuth2 OpenID Connect authentication source (Keycloak in my case). However, despite attempting to set the ACCOUNT_LINKING = auto option in the [oauth2_client] section in app.ini file, the users still need to manually link accounts.

Steps to Reproduce:

    Set up Gitea and configure OAuth2 authentication sources in the Gitea UI using OpenID Connect.  
    Attempt to enable automatic account linking by adding ACCOUNT_LINKING = auto to the [oauth2_client] section of the app.ini configuration file.
    Restart the Gitea Docker container to apply the changes.
    Create user with the OAuth2 authentication Source.
    Log in to Gitea user account using an OAuth2 authentication source.
    Link account window is shown (**unexpected behavior**)

Expected Behavior:
I expected that upon logging in with the OAuth2 authentication source, Gitea would automatically link the user's account, eliminating the need for manual account linking.

Actual Behavior:
Despite making the configuration changes as mentioned above, users are still required to manually link their accounts when logging in with OpenID Connect OAuth2 source provider set up. 

Additional Context:
The problem of account linking wasn't present at all in Gitea (version 1.18.303). Before the update, users created with Keycloak Oauth2 provider were automatically linked without any configuration changes and were authentificated by keycloak from start.

### Gitea Version

v1.20.2

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

Linux

### How are you running Gitea?

I am running Gitea on a server using Docker containers within a Rancher environment. The Docker images I am using for Gitea are downloaded from the official Gitea Docker Hub repository at https://hub.docker.com/r/gitea/gitea.

This setup allows me to deploy and manage Gitea within isolated containers.

### Database

PostgreSQL

**Comment by lng2020** [comment]
It's a bug. Currently, you should set both `ENABLE_AUTO_REGISTRATION` and 
`ACCOUNT_LINKING`  to enable the auto account linking even the user with the same name or email already registered. 
```ini
[oauth2_client]
ENABLE_AUTO_REGISTRATION = true
ACCOUNT_LINKING = auto
```

Additionally, setting `ACCOUNT_LINKING = disabled` and then using an oauth2 provider to register will cause some unexpected internal server error instead of the error message. Will open an issue to address in detail later.

**Comment by Diasastr** [comment]
Thank you! Just found this out. Had 500 Error because of the email:  must be valid alpha or numeric or dash(-_) or dot characters, but with additional USERNAME = email works just fine. The config that has worked:
`
[oauth2_client]
ENABLE_AUTO_REGISTRATION = true
ACCOUNT_LINKING = auto
USERNAME = email
`

**Comment by mgx0** [comment]
> It's a bug. Currently, you should set both `ENABLE_AUTO_REGISTRATION` and `ACCOUNT_LINKING` to enable the auto account linking even the user with the same name or email already registered.
> 
> ```ini
> [oauth2_client]
> ENABLE_AUTO_REGISTRATION = true
> ACCOUNT_LINKING = auto
> ```
> 
> Additionally, setting `ACCOUNT_LINKING = disabled` and then using an oauth2 provider to register will cause some unexpected internal server error instead of the error message. Will open an issue to address in detail later.

@lng2020 could you please put here the issue link you mentioned? I have the same problem and the solution you described is working. But users can register themselves as they want and they consume a license automatically, when they register.

thanks a lot

**Comment by lng2020** [comment]
> @lng2020 could you please put here the issue link you mentioned? 

Sorry, I forgot to address this one. I think probably you should not set `ACCOUNT_LINKING` to auto if you worry about the spam.

**Comment by mgx0** [comment]
there's no other way to link Gitea account to Keycloak one via REST API. Below works, but also allows users to register themselved

[oauth2_client]
ENABLE_AUTO_REGISTRATION = true
ACCOUNT_LINKING = auto

**Comment by lng2020** [comment]
I said it's a bug because when people set `ACCOUNT_LINKING = auto`, they must set `ENABLE_AUTO_REGISTRATION = true` to get things to work. But these two configs are not so connected in docs or config examples. 
I don't know about how the older version works. But if you are using an external OAuth source, Gitea will inevitably create a user in a database that is connected with the external user. So I can't see why you want `ENABLE_AUTO_REGISTRATION=false`. Maybe you could open an issue and address your concern in detail?

**Comment by mgx0** [comment]
> I said it's a bug because when people set `ACCOUNT_LINKING = auto`, they must set `ENABLE_AUTO_REGISTRATION = true` to get things to work. But these two configs are not so connected in docs or config examples. I don't know about how the older version works. But if you are using an external OAuth source, Gitea will inevitably create a user in a database that is connected with the external user. So I can't see why you want `ENABLE_AUTO_REGISTRATION=false`. Maybe you could open an issue and address your concern in detail?

after I set ENABLE_AUTO_REGISTRATION=true, anyone is able to register. Gitea creates an account and such account consumes a license.

I don't want people to register themselves > i need to be able to only create Gitea user account via REST API and link it to Keycloak account. 

you know what I mean?

**Comment by lng2020** [comment]
I can see your point now. You didn't want the side effect caused by `ENABLE_AUTO_REGISRATION=true`. Maybe you can open an issue to address it. I'm not familiar with that part of the code and why behavior changes.

**Comment by mgx0** [comment]
https://github.com/go-gitea/gitea/issues/27709

**Comment by mgx0** [comment]
@lng2020 i only reacted on this because you mentioned "it's a bug" in https://github.com/go-gitea/gitea/issues/26940#issuecomment-1709897880 😀  that's why asked. Let's see how it goes
