### ISSUE TITLE
Can't use the upgrade.sh

### ISSUE THREAD

**Issue by LouShangxiaolong** [go-gitea/gitea#26957]
### Description

when i use the upgrade.sh 
`./upgrade.sh -v 1.20.3`
```
Gitea is running. Continuing with rest of script...
Checking currently installed version...
git is not in the sudoers file.  This incident will be reported.
```

### Gitea Version

1.20.2

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/64191057/6148f6a5-46e3-4c6d-ac99-ff4c24a0930f)
![image](https://github.com/go-gitea/gitea/assets/64191057/898191fc-5712-4ac6-bbc5-241b32bef3e9)

### Git Version

2.33.2

### Operating System

centos7

### How are you running Gitea?

I use the  `systemd` to running.
but i can't upgrade

### Database

MySQL/MariaDB

**Comment by KazzmanK** [comment]
As I understand your user is not eligible to run commands, because it is not configured in sudoers file. If you allow your user to do anything, or run git command, it may continue.

**Comment by LouShangxiaolong** [comment]
ok,thanks;
i used root is running good.

**Comment by LouShangxiaolong** [comment]
> ok,thanks;
> i used root is running good.

ok,thanks;
i used root is running good.
