### ISSUE TITLE
INI value with trailing slash causes bugs

### ISSUE THREAD

**Issue by wxiaoguang** [go-gitea/gitea#26977]
eg:

```
[foo]
key = C:\
xxx = yyy
```

The current code reads: `key = C:\xxx = yyy` and can't read `xxx`

**Comment by silverwind** [comment]
`\` at end of line is common on unix shells for line continuation. I'd argue we should encourage quoting all strings anyways.

**Comment by wxiaoguang** [comment]
The problem is , ini package doesn't encode the `\` when writing.

So, in code we `SetValue("E:\\")`, but we can not read the correct value next time. That's why it is a bug.
