### ISSUE TITLE
Cron action incorrectly updates commit status of last commit

### ISSUE THREAD

**Issue by silverwind** [go-gitea/gitea#26971]
### Description

Workflow: https://gitea.com/gitea/gitea-docusaurus/src/branch/main/.gitea/workflows/build-and-publish.yaml
Commit: https://gitea.com/gitea/gitea-docusaurus/commit/d3697c65d25e763ff9f36d1db1888610612ec0b5

Initially, the action ran as part of a push to the main branch and passed. Then the cron action ran on scheduled time, failed, but updated the commit status of the commit in the main branch which is incorrect. Cron actions should not update any commit status as they run disassociated from commits, so their results should only be visible in the actions log.

### Gitea Version

main

**Comment by lunny** [comment]
Maybe we should remove these lines. https://github.com/go-gitea/gitea/blob/main/services/actions/schedule_tasks.go#L136
