### ISSUE TITLE
Regression: no longer possible to fork own repo

### ISSUE THREAD

**Issue by bard** [go-gitea/gitea#2698]
(Taking the liberty to open a new issue since this was only discussed in closed issues and risks therefore to become invisible.)

- Gitea version (or commit ref): 1.2
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes https://try.gitea.io/bard/test (hovering on "Fork" says "You cannot fork a repository you already own")

## Description

I described the rationale for forking one's own repo back when I was using gogs in https://github.com/gogits/gogs/issues/1791#issuecomment-278899979. @lunny replied in https://github.com/gogits/gogs/issues/1791#issuecomment-278905982 that Gitea had [implemented it](https://github.com/go-gitea/gitea/pull/761) so I switched to Gitea, as it's a make-or-break feature in my case; several projects I'm working on are now arranged around this possibility. Unfortunately it was subsequently removed in https://github.com/go-gitea/gitea/issues/2019 to solve a separate issue.

I'd really like to stay on top of Gitea development, especially seeing all the goodies and fixes that went into 1.2, but for now I'm frozen at 1.1. Anything I can do to help? I'm glad to do testing; also willing to code, but since I never touched Go I'm not sure any code I'd produce would qualify as "help".

**Comment by daviian** [comment]
I think we should handle it like github and add a modal asking where to fork the repository.
Of course only if the user is member of at least one organization he has the permission to create a repository.
But we shouldn't allow multiple forks in one user / organization of the same repository as introduced in #2019
