### ISSUE TITLE
Q: Login with Microsoft 365 account

### ISSUE THREAD

**Issue by leonkosak** [go-gitea/gitea#26980]
### Feature Description

Is there a way to configure authentication for Microsoft 365 (formerly Office 365) online accounts?
I know about Active Directory (local) authentication - LDAP.
Thank you for clarifications.

**Comment by techknowlogick** [comment]
Yup, you can use OIDC for Azure: https://blog.anoff.io/2019-03-23-configure-azure-ad-for-gitea/
