### ISSUE TITLE
[Feature Request] Show PR changes since the last review

### ISSUE THREAD

**Issue by rideg** [go-gitea/gitea#26994]
### Feature Description

I have been using Gitea very actively in the last half a year. It is an amazing product and I really love it. So first of all I would like to thank the team for creating this fantastic software! Great job!

I do a lot of code reviews and it would be great to see what has changed since the last review round. Gitea shows that if a file has changed since the last review round but not the changes. Seeing the exact diff would greatly simplify the review process because I could easily see if the developer addressed my comments or not. This would be especially useful for files introduced by the PR.

**I imagine the feature as follows:**

There would be a new dropdown on the `Files changed` tab next to `diff options` drowpdown. In this dropdown we could have the following options:

* `All changes`: this would be the default
* `Changes since last review` 
* `Changes since review n-1`: we can assume there was n review already. Maybe the commit hash can be there instead
* `Changes since review n-2`
* `Changes since review 1`

If the user selects any of those the file view would show only changes that happened after that review round.

**Comment by delvh** [comment]
Already implemented in 1.21.
The only problem about this that is virtually impossible is the `changes since review n-x` part as Gitea only stores the latest review and discards all other reviews.
Furthermore, even if it were possible, it would make the current UI (even) more confusing as we would need to display even more options on the same already-limited space.

**Comment by delvh** [comment]
Ah wait, I think I misremembered how I implemented it.
We do not discard this information, so we could even display it theoretically.
Still, there is an unavoidable problem with this: We only store the most recent time the review was updated and have no other measure to know which review comes before another review.
So, assuming that you can update a review afterwards, we will get in a lot of basically impossible-to-solve trouble.
Even further, I have no idea how a UI for that would need to look like.
So for now, I'm slightly in favor of not implementing it, unless you happen to have a good idea what a UI for it should look like.
We can work around the logical problem by disabling reviewing files when not reviewing the full diff (which is what we are doing already).

**Comment by rideg** [comment]
I see. We're running 1.19 that is why I reported the issue. I quickly tried the nightly version out, and what you have there is perfect since you have the filtering by commit options too. Then it seems we only need to wait for the release and upgrade. Thank you so much! Great work!
