### ISSUE TITLE
PRs stuck on "Merge conflict checking is in progress. Try again in few moments."

### ISSUE THREAD

**Issue by MrVrops** [go-gitea/gitea#27006]
### Description

Hello everyone,

I've been having a problem with my Gitea instance for some time. From one day to the next and without any apparent change, I get the message: "Merge conflict checking is in progress. Try again in few moments."

I've tried updating to the latest version of GItea but nothing has changed. Have you ever seen a similar case? Don't hesitate to ask me for more information.

Thanks for any help.

Best regards,

### Gitea Version

1.20.4

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![MicrosoftTeams-image (2)](https://github.com/go-gitea/gitea/assets/25271722/3de4097a-6db1-4259-bc4d-9060a5f1c477)

### Git Version

2.11.0

### Operating System

Debian 9.13

### How are you running Gitea?

Installation from binary.

### Database

MySQL/MariaDB

**Comment by wxiaoguang** [comment]
Which version you were using when it had the bug?

And could you show your admin -> monitoring -> queue page?

**Comment by MrVrops** [comment]
Sure, I was on 1.19.1

And that's my queue page:
![Capture](https://github.com/go-gitea/gitea/assets/25271722/ec8588c9-8e7d-4665-a1e7-bc78dd30c04d)

**Comment by MrVrops** [comment]
Sure sorry haha

So:
![Capture](https://github.com/go-gitea/gitea/assets/25271722/c7177e9f-7f0e-4127-acd0-6875cb60d7b3)

**Comment by wxiaoguang** [comment]
I see, it seems an uncommon problem. Maybe more details would help:

1. Does this "PR stuck" problem only occurs for one/a few special repositories? Or does it occur for every repository?
2. Could you provide Gitea **server logs** between your PR push and after a while till you think it gets "stuck"?
    * https://docs.gitea.com/help/support : `Bug Report` section
    * It might contain sensitive information, if you care about it, you could edit the logs manually.
3. Could you provide the **diagnosis report** when you think it gets "stuck"?
    * "Site Admin" -> "Monitoring" -> "Stacktrace" -> "Download diagnosis report"
    * It doesn't contain sensitive information.

**Comment by MrVrops** [comment]
1. This problem appears on some repos ( I don't know if it's related) but they all use Git LFS at first sight.

2. I'll send you this as soon as the bug is reproduced because it's not all the time but most of the time.

3 Here's the diagnostic report.
[goroutine-after.txt](https://github.com/go-gitea/gitea/files/12574192/goroutine-after.txt)
[goroutine-before.txt](https://github.com/go-gitea/gitea/files/12574193/goroutine-before.txt)

**Comment by wxiaoguang** [comment]
> 2.  .... because it's not all the time but most of the time.

So I guess you mean: even for the same repository, sometimes the PR check gets stuck, while sometimes it works, the PR check passes without any problem?

**Comment by MrVrops** [comment]
Exactly, some depots are not affected by the problem at all.
On the depots where the problem is, the problem is not always here.

**Comment by wxiaoguang** [comment]
Hmm, then it seems to be highly related to the git repo operation. I think we need to find the related logs first. Or if there could be a reproducible public repository, then I might be able to reproduce it by myself.
