### ISSUE TITLE
replace `stale` bot with `actions/stale`

### ISSUE THREAD

**Issue by a1012112796** [go-gitea/gitea#27004]
looks the `stale` bot was deprecated  (https://github.com/probot/stale/pull/430). we can replace it with [`actions/stale`](https://github.com/actions/stale). I'd like lable this issue as `good first issue`, welcome new contributor :)

related: https://github.com/GiteaBot/gitea-backporter/pull/108

**Comment by SaumyaBhushan** [comment]
Hi @lunny  @a1012112796 I would like to work on this one . Please assign it to me

**Comment by KN4CK3R** [comment]
I really hope we don't get a flood of "this is old" messages then...

**Comment by blackshot** [comment]
does act_runner support cron jobs?

**Comment by techknowlogick** [comment]
@blackshot yup, it's in the development version right now.
@KN4CK3R with the "lockbot" we have, it ratelimits the number of issues it touches per run so hopefully the stalebot operates the same.

**Comment by WillOfHeaven** [comment]
Hi @a1012112796 @lunny I would like to work on this issue, can you please assign it to me !

**Comment by techknowlogick** [comment]
Hi @WillOfHeaven, thank you for your enthusiasm. There is currently already a PR for this, but if you are interested in another intro issue/PR, please have a look at the others here: https://github.com/go-gitea/gitea/labels/good%20first%20issue

Please feel free to hop into chat if you have any questions or need guidance.

**Comment by denyskon** [comment]
Closing as with corresponding PR: https://github.com/go-gitea/gitea/pull/27447
