### ISSUE TITLE
Wrong `default branch` while switching between branches via the web interface

### ISSUE THREAD

**Issue by nanguanlin6** [go-gitea/gitea#27008]
### Description

When switching between branches via the web interface, the default branch should remain unchanged.
![ksnip_20230911-153517](https://github.com/go-gitea/gitea/assets/70063547/f0274288-bc82-4439-9519-eee9c6a70aed)
e.g. The `default branch` should remain `main`

### Gitea Version

latest codebase

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

building Gitea from source code

### Database

None

**Comment by CaiCandong** [comment]
@yp05327

**Comment by lng2020** [comment]
caused by pr #26697

**Comment by yp05327** [comment]
![image](https://github.com/go-gitea/gitea/assets/18380374/c7ffe556-a8af-48f1-b1f7-41bd723181c2)
`$defaultBranch` is not the repo's default branch, the existing code is confusing.
