### ISSUE TITLE
Delete pull request popup missing margin

### ISSUE THREAD

**Issue by stuzer05** [go-gitea/gitea#27012]
### Gitea Version

trunk

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/23124682/b927c4cb-fdb4-49ca-a857-f3495ade27bf)

### How are you running Gitea?

docker

### Database

None

**Comment by wxiaoguang** [comment]
->  Fix "delete" modal dialog for issue/PR #27015
