### ISSUE TITLE
Already reviewed PRs are still listed on "Pull Requests" page

### ISSUE THREAD

**Issue by TitaniumHocker** [go-gitea/gitea#27019]
### Description

After reviewing PRs are still listed on "Pull Requests" -> "Review requested" page.
Before 1.20.4 only waiting to review PRs were listed on this page.

Reproduced on [try.gitea.io](https://try.gitea.io/TitaniumHocker/testshit/pulls/1)

### Gitea Version

1.20.4

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/37049574/9a50a256-71c3-41b7-a66f-b0b5c795e1a5)
![image](https://github.com/go-gitea/gitea/assets/37049574/84dd3953-e2fd-48fb-ab16-4fc4209bc1b7)
![image](https://github.com/go-gitea/gitea/assets/37049574/995c5ddc-a75f-4462-8b81-fe5039bdee5c)

### Operating System

Debian 11

### How are you running Gitea?

Selfhosted on Debian 11 + Gitea 1.20.4 + Nginx(for SSL) + PostgreSQL

### Database

PostgreSQL

**Comment by TitaniumHocker** [comment]
@lng2020 When this issue will be fixed? There is no milestone attached to this issue.

**Comment by lng2020** [comment]
> @lng2020 When this issue will be fixed? There is no milestone attached to this issue.

I've merged several PRs to refractor the unit test about issues recently in order to solve the continuous bugs in the issue overview page. I will make a PR to fix this one tomorrow. Sorry for the delay😢
