### ISSUE TITLE
README.txt vs. README.md

### ISSUE THREAD

**Issue by pmorjan** [go-gitea/gitea#2701]
Gitea 1.2.0

## Description
A plain text README.txt instead of a README.md file in the repository root directory is rendered as Markdown and displayed on the main repository web site. 
This can lead to a broken layout because multiple white space characters used for indentation or in ASCII art are replaced by single blancs. Also the font family for plain text should be monospace.

It would be nice if Gitea would render a plain text README.txt using a monospace font without any modifications.

**Comment by strk** [comment]
Sounds like a regression. I remember this coming up in the past.

**Comment by lunny** [comment]
@lafriks I think strk is right. I will check this and send a PR to fix that.

**Comment by pmorjan** [comment]
Thanks for the very quick response! 
However I think the PR doesn't fix the issue. At least not how I wanted it.
I created an example:
https://try.gitea.io/pmorjan/issue2701
I would prefer the rendering to be similar to the view in the editor:
https://try.gitea.io/pmorjan/issue2701/_edit/master/README.txt

**Comment by Morlinest** [comment]
@pmorjan Can't open your second link.

**Comment by pmorjan** [comment]
sorry, hop this renders correctly
```
     /\_____/\
     |  o o  |
    __\__^__/__
   (__/     \__)
    _|   .   |_
   (__\_____/__)

```

**Comment by Morlinest** [comment]
@pmorjan yes, I get it now.

**Comment by lafriks** [comment]
@pmorjan please open for that new issue as bug was fixed:
https://try.gitea.io/lafriks/issue2701

monospace font for text still needs to be implemented
