### ISSUE TITLE
Running make watch twice with no backend code changes will broke js?

### ISSUE THREAD

**Issue by yp05327** [go-gitea/gitea#27029]
### Description

Reproduce steps:
1. Run `TAGS="bindata sqlite sqlite_unlock_notify" make watch`.
2. Access the web site, and make sure it works with not errors.
3. Press `ctrl + c` to stop the process and run `TAGS="bindata sqlite sqlite_unlock_notify" make watch` again. Then access the web site, you will get this:
![image](https://github.com/go-gitea/gitea/assets/18380374/ce5d8dfd-a3e7-4cd4-814b-8ce9bcfd9644)
4. Do some changes to the backend go codes, for example add `fmt.println` in some places. After saving file, Gitea will rebuild automatically and the error in step 3 will not occur again.

### Gitea Version

latest

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

build

### Database

None

**Comment by lunny** [comment]
Just use `make watch` with not other tags.

**Comment by yp05327** [comment]
Forgot removing `bindata` tag when using make watch.
