### ISSUE TITLE
Update documentation to use Docker Compose V2

### ISSUE THREAD

**Issue by GammaGames** [go-gitea/gitea#27025]
### Description

The older `docker-compose` command has stopped receiving updates, it's now recommended to use the included `docker compose` commands instead:

> From July 2023 Compose V1 stopped receiving updates. It's also no longer available in new releases of Docker Desktop.
>
> Compose V2 is included with all currently supported versions of Docker Desktop. For more information, see [Migrate to Compose V2](https://docs.docker.com/compose/migrate).

There are some of changes to flags and stuff, but 99% of users won't have any trouble since they mostly want to `up`, `pull`, `logs`, etc. 

### Gitea Version

1.20.4

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/7832163/1a60cf07-9b1c-44de-a542-1806ff842ea3)

### How are you running Gitea?

Docker

### Database

None

**Comment by lunny** [comment]
Closed by https://gitea.com/gitea/docs/pulls/43
