### ISSUE TITLE
Empty mail notification for dismissed approvel

### ISSUE THREAD

**Issue by otbutz** [go-gitea/gitea#27035]
### Description

A mail notification triggered by an automatically dismissed review is empty:

![image](https://github.com/go-gitea/gitea/assets/22315436/8bfe710d-9b69-4300-8879-f41991459c22)

```
Content-Type: multipart/alternative;
 boundary=7fec98bb05da73e13565f1c35ed520324672de761f3eb354ca42c4298795

--7fec98bb05da73e13565f1c35ed520324672de761f3eb354ca42c4298795
Content-Transfer-Encoding: quoted-printable
Content-Type: text/plain; charset=UTF-8


--7fec98bb05da73e13565f1c35ed520324672de761f3eb354ca42c4298795
Content-Transfer-Encoding: quoted-printable
Content-Type: text/html; charset=UTF-8

<!DOCTYPE html>
<html>
<head>
	<meta http-equiv=3D"Content-Type" content=3D"text/html; charset=3Dutf-8">
	<title>Re: [Optitool/ot] #39395 Add freehand/lasso selection in map (#9234=
)</title>

	<style>
		blockquote { padding-left: 1em; margin: 1em 0; border-left: 1px solid gre=
y; color: #777}
		.footer { font-size:small; color:#666;}
	=09
	</style>

</head>

<body>
=09
=09
	<p>
	=09
		=09
--7fec98bb05da73e13565f1c35ed520324672de761f3eb354ca42c4298795--
```
(removed the mail headers which looked fine to me)

This renders as an empty page in my mail client.

### Gitea Version

1.20.2

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

Binary started via systemd behind a caddy reverse proxy.

### Database

None

**Comment by sebastian-sauer** [comment]
.Comment.Review.Reviewer.Name in default.tmpl is null in this case.

**Comment by sebastian-sauer** [comment]
i'll send a pr asap to load the reviewer before sending the notification
