### ISSUE TITLE
Error 500 -> GetUserHeatmapDataByUserTeam strconv.ParseInt invalid syntax

### ISSUE THREAD

**Issue by dexeotechnologie** [go-gitea/gitea#27041]
### Description

Hello,

I've recently installed Gitea 1.14.1 with Postgresql 14 and when i browse my gitea site on dashboard or on my profile page, i've an Internal Server Error 500.
In the log file, i've found this message : routers/user/home.go:110:Dashboard() [E] GetUserHeatmapDataByUserTeam: arg timestamp as int: strconv.ParseInt: parsing "1694390400.000000": invalid syntax 

### Gitea Version

1.14.1

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![Capture d’écran 2023-09-12 à 15 19 20](https://github.com/go-gitea/gitea/assets/33835283/76d0abca-5d86-4dd7-84b5-d2ef743528b6)
![Capture d’écran 2023-09-12 à 15 20 54](https://github.com/go-gitea/gitea/assets/33835283/46f6ea56-78a2-4127-b7fa-ec36138f52be)

### Git Version

2.34.1

### Operating System

ubuntu 22.04.3

### How are you running Gitea?

I've installed gitea from https://dl.gitea.com/gitea/1.14.1/

### Database

PostgreSQL

**Comment by wxiaoguang** [comment]
1.14.1 is too old, the current stable (and supported) version is 1.20

Please upgrade and retry.

**Comment by techknowlogick** [comment]
closing, but please re-open if you face the same issue after upgrading.
