### ISSUE TITLE
Old icons for apps

### ISSUE THREAD

**Issue by C-EO** [go-gitea/gitea#27057]
### Description

Discord has a new icon and logo. Why is the old one still in use?

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/85847352/a2047d1f-14d8-4b0a-a556-3e6bb2ea7dc8)

![image](https://github.com/go-gitea/gitea/assets/85847352/1eaf5d20-b4e9-4736-bb55-7f1da04bbde7)

### Gitea Version

1.21.0+dev-800-ga38eca3f5

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

linux 6.2.0-1013-gcp

### Browser Version

Microsoft Edge 116.0.1938.69 (Official build) (64-bit)

**Comment by KN4CK3R** [comment]
Because nobody changed it. Feel free to replace it.

**Comment by C-EO** [comment]
I will replace it when I get time. Shouldn't take longer than next week.
