### ISSUE TITLE
Installing package dependencies from RPM Package Repo fails

### ISSUE THREAD

**Issue by mehmax** [go-gitea/gitea#27056]
### Description

I have uploaded some rpm packages to my Gitea instance. Some of those packages have dependencies which are uploaded as well to the gitea package repo.

I have added my package repo to dnf.

```
# packages.rpm.distro.redhat
dnf config-manager --add-repo http://XXXX:3000/api/packages/cloned/rpm.repo
```
But have modified the `/etc/yum.repos.d/rpm.repo` and disabled gpgcheck
```
[gitea-cloned]
name=cloned - Gitea: Git with a cup of tea
baseurl=http://XXXX:3000/api/packages/cloned/rpm
enabled=1
gpgcheck=0
gpgkey=http://XXXX:3000/api/packages/cloned/rpm/repository.key
```

I have uploaded the required packages 

![image](https://github.com/go-gitea/gitea/assets/84371809/df1534ec-64fe-4265-8ddd-2c0f21ea5602)

Due to simplification I now use Package 1 and Package 2
Package 1 is dependend on Package 2.

When trying to install Package 1 with dnf it correctly resolves dependencies and the source repository, but install fails due to checksum mismatch.
![image](https://github.com/go-gitea/gitea/assets/84371809/336b9fec-f079-4131-be63-a8b3e3560c78)

I did a bit of further analysis and found out that the filename of the downloaded file might be the reason.
All packages that are / were downloaded have the same filename `x86_64`.

When trying to install just from cache I see this error.
![image](https://github.com/go-gitea/gitea/assets/84371809/8259d05a-a029-4f07-830f-ca3fc6dd3af0)

dnf is always refering to the same filename `x86_64` even if the package name is different.

Downloading the packages manually with `wget` also outputs filename (which is the last part of the URL)

`wget http://XXXX:3000/api/packages/cloned/rpm/package/package-1/1.0/x86_64`

![image](https://github.com/go-gitea/gitea/assets/84371809/27c15f5f-277a-4711-894c-e0b75ca1a6d1)

Now I dont know where the rootcause is. Is gitea outputting a "wrong" filename or is dnf 

A few more annotations:
- Installing each package without dependencies one by one is working fine
- using `yum` instead of `dnf` results in the same error behaviour
- using `yumdownloader --resolve package-1` also outputs a single file named `x86_64`

### Gitea Version

1.20.3

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

### How are you running Gitea?

On-Premise with executable (no docker)

```
dnf version 4.0.9
```

### Database

MySQL/MariaDB

**Comment by Leskodamus** [comment]
Having the same issue and hoping for a fix as it would be nice to auto install dependencies in production.

**Comment by ExplodingDragon** [comment]
Note: After upgrading to the latest version you need to upload a new RPM to refresh the index before it will work.
