### ISSUE TITLE
Personal setting menus incorrect alignment

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#2706]
See below image.
![image](https://user-images.githubusercontent.com/81045/31581105-b2e0d670-b194-11e7-8e3e-8300e5405ea1.png)

**Comment by lafriks** [comment]
They are centered for me in try.gitea.io...

![attels](https://user-images.githubusercontent.com/165205/31581159-62338eca-b16c-11e7-9994-0b6798091d4e.png)

**Comment by lunny** [comment]
Yes, me too. But not v1.2.0

**Comment by lunny** [comment]
Maybe some back ported

**Comment by lafriks** [comment]
Seems to be working for me also in 1.2.0

**Comment by lunny** [comment]
My env: Chrome 59.0.3071.115 on MacOS

**Comment by renothing** [comment]
maybe change the setting menus as left sidebar will be better, as same as github

**Comment by lunny** [comment]
@renothing we just changed from left sidebar on v1.2.

**Comment by daviian** [comment]
@lunny Works for me on MacOS with Chrome 61.0.3163.100

**Comment by lunny** [comment]
Sorry, I zoom out to 120%, when I zoom back. It works.
