### ISSUE TITLE
Can't use issue templates on 1.20.4

### ISSUE THREAD

**Issue by colejohnson66** [go-gitea/gitea#27060]
### Description

Issue templates do not work on 1.20.4. When creating a new issue, we're taken to the template picker. However, picking a template does not work; It puts the template path in the URL, but then reloads the template picker. We downgraded back to 1.20.3, and it started working again.

The end of the URL the button links to hasn't changed; Both versions link to `/<org>/<repo>/issues/new?template=<template-path>`. However, when attempting to request that URL, Gitea responds with a `303 See Other` to `/<org>/<repo>/issues/new/choose?template=<template-path>`.

### Gitea Version

1.20.4

### Can you reproduce the bug on the Gitea demo site?

Have not tried

### Git Version

2.41.0.windows-3

### Operating System

Windows Server 2022

### How are you running Gitea?

As a Windows service. To upgrade/downgrade, we stop the service, overwrite the executable, and restart it.

### Database

MySQL/MariaDB

**Comment by wxiaoguang** [comment]
Related to #26813 @JakobDev

I would prefer not to limit it so strictly, give end users the freedom, or at least give repo members the freedom.

**Comment by JakobDev** [comment]
Sorry I should really have tested this better

> I would prefer not to limit it so strictly, give end users the freedom, or at least give repo members the freedom.

Blank Issues are enabled by default. If the repo owner wants to disable it, it's their choice. For allowing it only for repo members, we need finer settings.
