### ISSUE TITLE
Replace all instances of `db.DefaultContext` with a custom context

### ISSUE THREAD

**Issue by delvh** [go-gitea/gitea#27065]
## Problem

Early on, people often used `db.DefaultContext` whenever they did not have access to to a `context.Context` (from the Go standard library).

Nowadays, we see the problems from this approach as it means that data is added to transactions it doesn't belong, or requests hang forever waiting for some condition to be met.

## Solution

As such, any database call should be started from a fitting context that is **not** `db.DefaultContext`.
The only places where `db.DefaultContext` is still allowed, is inside tests (files ending with `test.go`).
Any other occurrence should be replaced with an additional `ctx context.Context` function parameter (that should be the first function parameter).

## Where to get the `ctx` param?

If you don't know where to get it from, in the worst case, you need to pass the context down from the route handler (`routers/` package, i.e. `routers/web/web.go`) until you reach the respective function.

## How to find all occurrences in need of conversion?

On Posix systems (MacOS, Linux, BSD), simply execute the following in a shell in the root directory of the gitea source code: 
```sh
grep -irnH 'db\.DefaultContext' {routers,services,models,modules} | grep -v 'test.*\.go'
```
or if you have `ag` installed:
```sh
ag 'db\.DefaultContext' | grep -v 'test.*\.go' 
```
Alternatively, you can use whatever graphical tool you like. This works on all systems.

**Comment by JakobDev** [comment]
I will try to fix it at some places

**Comment by JakobDev** [comment]
i had opened a first PR. More will follow.

btw: If someone wants to use the GitHub search, [here's a Link](https://github.com/search?q=repo%3Ago-gitea%2Fgitea+db.DefaultContext+path%3A%2F%5Erouters%5C%2F%2F+OR+path%3A%2F%5Eservices%5C%2F%2F+OR+path%3A%2F%5Emodels%5C%2F%2F+OR+path%3A%2F%5Emodules%5C%2F%2F&type=code).

**Comment by JakobDev** [comment]
@delvh How should I deal with functions that are used by templates?

**Comment by delvh** [comment]
Yes, those are unfortunately impossible yet.
We are currently working towards implementing `ctxFunctions` in the templates that could be called similar to the already existing mechanism of `ctx.Locale.Tr`, but that process isn't finished yet.

**Comment by JakobDev** [comment]
This can be closed now

**Comment by delvh** [comment]
All remaining 47 instances are inherently unfixable?

**Comment by lunny** [comment]
I think left db.DefaultContext is not easy to change and we can close this issue.
