### ISSUE TITLE
500 Error when editing OAuth2 applications

### ISSUE THREAD

**Issue by Zettat123** [go-gitea/gitea#27072]
### Description

Steps to reproduce
1. Click Edit
<img width="640" src="https://github.com/go-gitea/gitea/assets/15528715/576e873b-88b1-40d4-912e-c4f8f6081f2f"/>

2. Get 500 Error
<img width="640" src="https://github.com/go-gitea/gitea/assets/15528715/44c616b6-feb3-4199-9736-f3f83131cf24"/>

### Gitea Version

main

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

command line

### Database

None

**Comment by lunny** [comment]
Could you post the error logs here?
