### ISSUE TITLE
UI Spacing Errors

### ISSUE THREAD

**Issue by C-EO** [go-gitea/gitea#27071]
### Description

Is this a different section or are they merged?

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/85847352/8ad80516-890c-44d8-9d35-2645167cfe62)

### Gitea Version

1.21.0+dev-803-ge116ad450

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

linux 6.2.0-1013-gcp

### Browser Version

Microsoft Edge 116.0.1938.69 (Official build) (64-bit)

**Comment by puni9869** [comment]
Can you open a Pr for this change?

**Comment by puni9869** [comment]
Could you share the full description like which page you are on, we are unable to repro this.

**Comment by C-EO** [comment]
@puni9869 It's on the repo settings page for Pull mirrors. You have to first migrate and mirror a repo onto the Gitea instance to be able to see it
