### ISSUE TITLE
Adjust database connection attempts

### ISSUE THREAD

**Issue by tacerus** [go-gitea/gitea#27079]
### Feature Description

Hi,

currently, if the database backend is unreachable for a longer period of time (for example during maintenance on the database server), Gitea will crash after ten connection attempts:

```
Sep 14 09:40:57 gitea01 gitea[1165]: 2023/09/14 09:40:57 routers/common/db.go:35:InitDBEngine() [I] Backing off for 3 seconds
Sep 14 09:41:00 gitea01 gitea[1165]: 2023/09/14 09:41:00 routers/common/db.go:28:InitDBEngine() [I] ORM engine initialization attempt #9/10...
Sep 14 09:41:00 gitea01 gitea[1165]: 2023/09/14 09:41:00 cmd/web.go:175:serveInstalled() [I] PING DATABASE mysql
Sep 14 09:41:03 gitea01 gitea[1165]: 2023/09/14 09:41:03 routers/common/db.go:34:InitDBEngine() [E] ORM engine initialization attempt #9/10 failed. Error: dial tcp [2a07:>
Sep 14 09:41:03 gitea01 gitea[1165]: 2023/09/14 09:41:03 routers/common/db.go:35:InitDBEngine() [I] Backing off for 3 seconds
Sep 14 09:41:06 gitea01 gitea[1165]: 2023/09/14 09:41:06 routers/common/db.go:28:InitDBEngine() [I] ORM engine initialization attempt #10/10...
Sep 14 09:41:06 gitea01 gitea[1165]: 2023/09/14 09:41:06 cmd/web.go:175:serveInstalled() [I] PING DATABASE mysql
Sep 14 09:41:06 gitea01 gitea[1165]: 2023/09/14 09:41:06 routers/init.go:69:mustInitCtx() [F] code.gitea.io/gitea/routers/common.InitDBEngine(ctx) failed: dial tcp [2a07:>
Sep 14 09:41:06 gitea01 systemd[1]: gitea.service: Main process exited, code=exited, status=1/FAILURE
Sep 14 09:41:06 gitea01 systemd[1]: gitea.service: Failed with result 'exit-code'.
```

It would be great if the delay between the attempts and the amount of attempts could be adjusted, to have Gitea come online again automatically after the backend is back.
A workaround is to have systemd restart the service on failure, but that is prone to cause issues if the failure is caused by something other than the database being offline.

**Comment by CaiCandong** [comment]
I think so. We may need a Back-off algorithm to determine the retry interval.
How about this ？https://github.com/sethgrid/pester

**Comment by tacerus** [comment]
Hi @CaiCandong, the project you linked seems to be about HTTP, not TCP or MySQL?

**Comment by wxiaoguang** [comment]
Backoff is quite simple

https://github.com/go-gitea/gitea/blob/main/modules/queue/backoff.go

**Comment by wxiaoguang** [comment]
And it is already adjustable.

https://github.com/go-gitea/gitea/blob/47b878858ada27fc4c74eeadcc1e467d2da90e04/custom/conf/app.example.ini#L398-L399

**Comment by wxiaoguang** [comment]
Close as completed because it is adjustable.

**Comment by tacerus** [comment]
Thank you, I missed this!
