### ISSUE TITLE
Support a new file type: justfile

### ISSUE THREAD

**Issue by SteveLauC** [go-gitea/gitea#27086]
### Feature Description

It would be great if Gitea would support [justfile](https://github.com/casey/just)

1. File type detection
2. Syntax highlight

### Screenshots

![Screenshot from 2023-09-15 10-58-39](https://github.com/go-gitea/gitea/assets/96880612/549155d7-815c-4968-95bb-219896f1b2ea)
![Screenshot from 2023-09-15 10-58-58](https://github.com/go-gitea/gitea/assets/96880612/99b47677-3ae4-4feb-af7f-313b652f4dad)

**Comment by techknowlogick** [comment]
We use go-enery https://github.com/go-enry/go-enry for language detection. You could request it be added there and then we can support it here.
We also use chroma for syntax highlighting https://github.com/alecthomas/chroma support may need to be added there.

**Comment by SteveLauC** [comment]
Get it, I will open issues to the upstream, thanks!

**Comment by SteveLauC** [comment]
Issues filed:)

**Comment by puni9869** [comment]
We are facing multiple issues with this Library. It is giving so much problem day by day, 
Previously filed issue was also not acknowledged and resolved by the upstream author.

//cc @silverwind  @lunny  @wxiaoguang

**Comment by techknowlogick** [comment]
@puni9869 Which library? I've found that both of them are pretty reliable, hence their use by us.

**Comment by puni9869** [comment]
> We are facing multiple issues with this Library. It is giving so much problem day by day, 
> 
> Previously filed issue was also not acknowledged and resolved by the upstream author.
> 
> 
> 
> //cc @silverwind  @lunny  @wxiaoguang 

chrome go lib syntax highlighter.

**Comment by silverwind** [comment]
I have no issues with chroma, author is responsive and while I wish there was more activity, it's still the best syntax highlighter for golang as far as I'm aware. If you want something done, start contributing.

**Comment by puni9869** [comment]
Okay I will explore more about chrome lib. No worries, I am glad to know we are sponsoring chrome lib. :)

**Comment by SteveLauC** [comment]
`go-enry` 2.8.5 ships linguist 7.24.0, which contains the [patch that adds the support for justfile](https://github.com/github-linguist/linguist/pull/6086), so the next release of Gitea will support justfile!

Thanks to the folks who made this possible.

Close this issue as complete.
