### ISSUE TITLE
conan package registry and header only packages

### ISSUE THREAD

**Issue by lukester1975** [go-gitea/gitea#27090]
### Description

Header only conan packages can generate an empty `conaninfo.txt`, due to

```py
def package_id(self):
    self.info.clear()
```

`gitea` is currently ignoring such files, which appears to be due to https://github.com/go-gitea/gitea/blob/e502be46f3ac5f1075abd96bd9b326a4c1f7e96f/routers/api/packages/conan/conan.go#L328-L332 which breaks the `conan` client when trying to consume such packages:

```
tuplet/2.1.1: ERROR: Exception while getting package: da39a3ee5e6b4b0d3255bfef95601890afd80709
tuplet/2.1.1: ERROR: Exception: <class 'conans.errors.ConanException'> Corrupted tuplet/2.1.1:da39a3ee5e6b4b0d3255bfef95601890afd80709 in 'external' remote: no conaninfo.txt
ERROR: Corrupted tuplet/2.1.1:da39a3ee5e6b4b0d3255bfef95601890afd80709 in 'external' remote: no conaninfo.txt
```

Removing the above block in `conan.go` allows the empty `conaninfo.txt` to be stored in the registry, and the `conan` client works successfully.

Whether there are any other side effects of removing the check I couldn't say... seems OK so far though.

Thanks

### Gitea Version

1.20.4

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

N/a

### Operating System

Linux

### How are you running Gitea?

N/a but Fedora 38, systemd, custom build.

### Database

MySQL/MariaDB

**Comment by KN4CK3R** [comment]
While implementing the Conan registry I noticed the conan client uploads empty files in a first request and with content in the second request. Therefore I ignored these requests. Will test it again, maybe this will work:
```go
	isConaninfoFile := filename == conaninfoFile

	if buf.Size() == 0 && !isConaninfoFile {
		// ignore empty uploads, second request contains content
		jsonResponse(ctx, http.StatusOK, nil)
		return
	}
```

**Comment by KN4CK3R** [comment]
Looks like the Conan CLI has changed since last year. My package creation instructions don't work anymore and the empty uploads don't occur anymore.
