### ISSUE TITLE
New dark theme and default theme rename

### ISSUE THREAD

**Issue by silverwind** [go-gitea/gitea#27097]
### Feature Description

I think generally we agree that `arc-green` is a rather unconventional color theme and I don't like it very much. The idea is to make a new default dark theme with light blue primary color and almost-greyscale blue overall color. So I propose:

- Rename `gitea` theme to `gitea-light` and migrate existing users
- Rename and update `arc-green` theme to `gitea-dark` and migrate existing users

The colors I'd be aiming for are greyscale with a very subtle blue tint. Very similar to [this blender theme](https://projects.blender.org/infrastructure/gitea-custom/src/branch/main/public/css/theme-bthree-dark.css) and to Discord's dark theme, but not as blue as GitHub's dark theme.

### Screenshots

<img width="1240" alt="image" src="https://github.com/go-gitea/gitea/assets/115237/937df4ef-11ea-4b27-9d5a-5c124831bc38">

**Comment by puni9869** [comment]
It will be included in which milestone 1.21 or .122? I think we should tag this.

**Comment by silverwind** [comment]
Too late for 1.21, I guess it will be 1.22.

**Comment by TheBrokenRail** [comment]
Wait, what's wrong with `arc-green`? I've always thought it looked nice.

**Comment by delvh** [comment]
As I've understood it:
`arc-green` is an unconventional dark theme as it is basically the only common dark theme with a large _green_ focus instead of a _blue_ focus.

Ultimately, I'm neutral about which design we choose as we will all be able to adapt to whatever is decided.

**Comment by silverwind** [comment]
There is at least these issue with current themes:

- light theme is blue primary, dark theme is green, introducing inconsistency in our default themes.
- blue primary is in widespread use, likely because in HTML links are blue and people just went with that.
- green primary is unconventional. Not saying it couldn't work, but I think we are better off with blue

**Comment by lunny** [comment]
We can move arcgreen to a standalone repository so it can be used as external theme

**Comment by JakobDev** [comment]
While I personally use a dark theme, I'm in favour of keeping the light theme as default. While currently many sites on the Internet offers a dark theme, the most most will use the light theme as default, so Gitea should also do that. But maybe there's a way to respect `prefers-color-scheme`, what would even be better.

**Comment by silverwind** [comment]
`DEFAULT_THEME = auto`, which is the one that switches with `prefers-color-scheme`, so that's already taken care of.

**Comment by silverwind** [comment]
Got a initial draft [here](https://github.com/silverwind/gitea/commit/e24a3d247ee573f6d4e2681c93f10c690645e003), but I don't like it yet as the secondary colors are too blue, the color shades are generated by this currently:

```js
const col = [0x13, 0x1d, 0x26];

for(let i = -3; i < 200; i += 1) {
  const r = col[0] + i;
  const g = col[1] + i + Math.floor(i / 32);
  const b = col[2] + i + Math.floor(i / 16);
  console.info(`#${r.toString(16)}${g.toString(16)}${b.toString(16)}`);
}
```

<img width="1266" alt="image" src="https://github.com/go-gitea/gitea/assets/115237/aac11ffc-ee0c-4244-8099-a878bdec7b4b">

**Comment by lunny** [comment]
another example theme https://code.plashenkov.com/plashenkov/gitea-theme-deep-dark

**Comment by silverwind** [comment]
Ideally I would like to use CSS color generation but the necessary CSS functionality is still too new to realistically use, maybe in a year or two:

https://caniuse.com/mdn-css_types_color_color-mix
https://caniuse.com/css-relative-colors

**Comment by Code-DJ** [comment]
https://gitea.catppuccin.com/catppuccin/vscode

**Comment by istiak101** [comment]
> another example theme https://code.plashenkov.com/plashenkov/gitea-theme-deep-dark

I would vote for this one.

> https://gitea.catppuccin.com/catppuccin/gitea

This is a bit difficult for the eye.

**Comment by Code-DJ** [comment]
> > another example theme [code.plashenkov.com/plashenkov/gitea-theme-deep-dark](https://code.plashenkov.com/plashenkov/gitea-theme-deep-dark)
> 
> I would vote for this one.
> 
> > [gitea.catppuccin.com/catppuccin/gitea](https://gitea.catppuccin.com/catppuccin/gitea)
> 
> This is a bit difficult for the eye.

👍 I put it more as a reference. It's all subjective - I think the background on plashenkov is too muted while the foreground on catppuccin is too bright. May be find a happy median.
