### ISSUE TITLE
Chinese docs file linting failure in local system.

### ISSUE THREAD

**Issue by puni9869** [go-gitea/gitea#27098]
### Description

In github action docs linter is fail on chinese docs md files
https://github.com/go-gitea/gitea/actions/runs/6207127102/job/16852056368?pr=27096#step:5:5

Getting error on the local.
```
make lint-md
npm install --no-save

added 7 packages, and changed 30 packages in 7s
npx markdownlint docs *.md
docs/content/administration/https-support.zh-cn.md:55:277 MD051/link-fragments Link fragments should be valid [Context: "[HTTP 重定向](http重定向)"]
docs/content/administration/https-support.zh-cn.md:97:244 MD051/link-fragments Link fragments should be valid [Context: "[启用内置服务器S 支持](#使用内置服务器)"]
docs/content/installation/from-source.zh-cn.md:38:67 MD051/link-fragments Link fragments should be valid [Context: "[构建](#构建)"]
docs/content/installation/from-source.zh-tw.md:31:59 MD051/link-fragments Link fragments should be valid [Context: "[編譯章節](#編譯)"]
docs/content/usage/actions/act-runner.zh-cn.md:244:78 MD051/link-fragments Link fragments should be valid [Context: "[配置教程](#配置)"]
make: *** [lint-md] Error 1

```
I can't fix this due to language barriers.

### Gitea Version

0818e9b10

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

Localhost

### Database

PostgreSQL

**Comment by puni9869** [comment]
@lunny FYI
https://github.com/go-gitea/gitea/actions/runs/6207127102/job/16852056368?pr=27096#step:5:5

**Comment by CaiCandong** [comment]
https://github.com/go-gitea/gitea/assets/50507092/040e5022-4945-4196-9ff4-4ef8815717ae

**Comment by puni9869** [comment]
@CaiCandong  could you take it forward this issue?

**Comment by silverwind** [comment]
Seems https://github.com/go-gitea/gitea/pull/27094 brought this up, I will do a tweak to actions config so all jobs run when when dependencies change.

**Comment by silverwind** [comment]
We could either downgrade `markdownlint-cli` or fix the links.

**Comment by CaiCandong** [comment]
There's nothing wrong with this Markdown , a quicker way is to switch its title to English.

**Comment by puni9869** [comment]
But this is Chinese language translation, Cannot afford to change the title.

**Comment by silverwind** [comment]
> There's nothing wrong with this Markdown , a quicker way is to switch its title to English.

Can you report it to https://github.com/DavidAnson/markdownlint?

**Comment by silverwind** [comment]
https://github.com/go-gitea/gitea/pull/27100 includes the downgrade of `markdownlint-cli` as a short-term fix.

**Comment by CaiCandong** [comment]
> Can you report it to [DavidAnson/markdownlint](https://github.com/DavidAnson/markdownlint)?

I'm sorry, I speak Chinese but unfamiliar with JS.

**Comment by silverwind** [comment]
Found the issue: https://github.com/DavidAnson/markdownlint/issues/954. So if we upgrade to v0.31.1, it might be fixed.
