### ISSUE TITLE
Deprecated config option `[log]` `ROUTER` present in /admin/config

### ISSUE THREAD

**Issue by stuzer05** [go-gitea/gitea#27108]
### Description

```
Deprecated config option `[log]` `ROUTER` present. Use `[log]` `logger.router.MODE` instead. This fallback will be/has been removed in 1.21 (and 1 more)
```

### Gitea Version

trunk

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/23124682/c14d46fd-7cf7-473b-a0ea-17c8d1d998c2)

### How are you running Gitea?

docker

### Database

None

**Comment by KN4CK3R** [comment]
If you fix your app.ini the message will disappear.

**Comment by delvh** [comment]
It's simply the same message that was previously only an error in the logs.
We've added these errors to the admin page as well so that admins notice them sooner.

**Comment by stuzer05** [comment]
> If you fix your app.ini the message will disappear.

How to, what could wrong?

**Comment by delvh** [comment]
> Deprecated config option `[log].ROUTER` present.

> Use `[log].logger.router.MODE` instead.

**Comment by stuzer05** [comment]
> [log].logger.router.MODE

Thank you, I removed the errors. However, ([log].**logger.router**.MODE), bold part here is confusing

**Comment by wxiaoguang** [comment]
> However, ([log].**logger.router**.MODE), bold part here is confusing

It's documented here https://docs.gitea.com/administration/logging-config

I also agree that such naming is somewhat confusing, but it is the only way to avoid introducing more unclear config options when refactoring the "logger system" (the background is quite complex ....)

**Comment by stuzer05** [comment]
> > However, ([log].**logger.router**.MODE), bold part here is confusing
> 
> It's documented here https://docs.gitea.com/administration/logging-config
> 
> I also agree that such naming is somewhat confusing, but it is the only way to avoid introducing more unclear config options when refactoring the "logger system" (the background is quite complex .... due to many legacy problems)

Oh I see
