### ISSUE TITLE
Import bitbucket to gitea

### ISSUE THREAD

**Issue by ware32** [go-gitea/gitea#27112]
### Feature Description

Is it possible to import a bitbucket repository to gitea? I cant find information about this.
Thanks in advance

**Comment by lunny** [comment]
For repositories, you can use git to import them.

**Comment by ware32** [comment]
Thanks, is there any example or similar?

**Comment by delvh** [comment]
![image](https://github.com/go-gitea/gitea/assets/51889757/1bc49842-84e5-48e2-b558-31a88d9def36)
![image](https://github.com/go-gitea/gitea/assets/51889757/fce69978-4ae7-4e8c-95dd-c69470a75c27)

**Comment by ware32** [comment]
I get "authentication failed: Clone: exit status 128 - remote: Invalid credentials fatal: Authentication failed"
And the credentials are OK

**Comment by delvh** [comment]
And the Git repo URL is correct?
The URL should end in `.git` (if bitbucket behaves like GitHub/GitLab/Gitea)

**Comment by ware32** [comment]
This would be correct? must it be the username in the url?
https://USERNAME@bitbucket.org/trotecuto/bodega.git

**Comment by ware32** [comment]
> And the Git repo URL is correct? The URL should end in `.git` (if bitbucket behaves like GitHub/GitLab/Gitea)

are you sure bitbucket allows this migration?

**Comment by andrewimeson** [comment]
The generic Git importer should work.

If you want to keep PR history and other non-git metadata, that isn't directly supported. I used an intermediary GitLab instance which does have a BitBucket importer and moved all the repositories to GitLab and then to Gitea to keep PR history. It doesn't work perfectly, the PR comments on lines of code don't have the context, but it was better than losing that history.

**Comment by ware32** [comment]
> The generic Git importer should work.
> 
> If you want to keep PR history and other non-git metadata, that isn't directly supported. I used an intermediary GitLab instance which does have a BitBucket importer and moved all the repositories to GitLab and then to Gitea to keep PR history. It doesn't work perfectly, the PR comments on lines of code don't have the context, but it was better than losing that history.

Using the generic git importer I always get the "invalid credentials error".
In bitbucket I login using my gmail account. In the git importer, wich username and password must I use?

thanks

**Comment by JakobDev** [comment]
>  In the git importer, wich username and password must I use?

The same you use wit `git clone`

**Comment by ware32** [comment]
> > In the git importer, wich username and password must I use?
> 
> The same you use wit `git clone`

It uses browser to authenticate, when invoking git clone it apperars a box to perform the browser authentication

**Comment by ware32** [comment]
Solved, without using user and password and using in the server name the token
Example:
https://x-token-auth:ATCTT3xFfGN09CvULWBdrereRuANdisvf6Z7kwLfWKZm-Tu22yr6-oYen5Z0RMn80ghqE_6AAlqdJuuNB-Lg0q1dNtumsZzncfbRSyaLGt7bF5HCKH77jqo7unmbQOS4dT929QjtCCZH-nwjXbazwHRYHd3Ao9TqXNKb7zzHk73URhEptc=6BD153EB@bitbucket.org/xxxx/ccccc.git
