### ISSUE TITLE
The License files for project generations contain UTF8 characters for dashes

### ISSUE THREAD

**Issue by alexlehm** [go-gitea/gitea#27123]
### Description

When creating a project and using a LICENSE file, e.g. CC-BY-NC-4.0-SA, the file contains UTF8 characters for dashes which leads to a warning in the web interface. It would be better if the files were using the plain ASCII characters instead

### Gitea Version

1.20.4

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/156144/af59dd15-9412-47e2-a772-39709dc2e6e0)

### Operating System

Ubuntu 22.04.2 LTS

### How are you running Gitea?

GITEA_WORK_DIR=$PWD/data/ ./gitea web -c $PWD/etc/app.ini -p 3003

### Database

None

**Comment by lng2020** [comment]
Since the license title "Creative Commons Attribution-NonCommercial 4.0 International" contains the non-ascii char '-', I don't think those chars can be replaced. If you want to disable the warning, you can refer to (https://forum.gitea.com/t/this-file-contains-ambiguous-unicode-characters/6834)

**Comment by alexlehm** [comment]
I figured it might be possible to convert the source file to plain USASCII format, maybe that is not a good idea
I noticed that the same does not happen on other files, e.g. MIT license.

I guess its a non-problem as it can be fixed by converting the file after checkout with recode or whatever

**Comment by alexlehm** [comment]
yes, please close it
