### ISSUE TITLE
CriticMarkup support

### ISSUE THREAD

**Issue by kuon** [go-gitea/gitea#27135]
### Feature Description

We use [CriticMarkup](https://github.com/CriticMarkup/CriticMarkup-toolkit) in our wiki but gitea doesn't support it. We mostly uses other tool to view the wiki, but it would be nice to be able to see the correct rendering within gitea.

**Comment by KN4CK3R** [comment]
You can use external rendering:
https://docs.gitea.com/administration/external-renderers

**Comment by kuon** [comment]
Yeah I saw this documentation. This means fully replacing the renderer which I thought to be impractical. But I understand that gitea do not want to support all markup.
