### ISSUE TITLE
French translations 

### ISSUE THREAD

**Issue by axeloz** [go-gitea/gitea#2713]
- Gitea version (or commit ref): 2.0.0

## Description

Hello, 

There are still quite a lot of untranslated strings in Gitea in French (probably in other languages too). However most of these strings were translated in Crowdin months ago. For example : 

`- You will lose access if the new owner is a individual user.`
was translated 3 months ago.

But in Gitea v2.0.0 the string remains untranslated. Is it before the string is still pending validation?

I have spent a lot of time translating hundreds of strings but it does not seem useful at this point. 
Thanks

## Screenshots

<img width="803" alt="capture d ecran 2017-10-16 a 10 53 32" src="https://user-images.githubusercontent.com/1597611/31603393-49bd1d62-b260-11e7-9eaf-be37bab77bfd.png">

**Comment by lafriks** [comment]
Thanks for your work. I have approved translations and they will be included in next version (1.3.0) that will be released at the end of this or beginning of next month. BTW There are still 4 untranslated strings left to have 100% ;)

**Comment by axeloz** [comment]
OK thanks, I just translated the last strings.

**Comment by lafriks** [comment]
I'm sorry to say but there is one more now :)

**Comment by axeloz** [comment]
I'm happy to say there is none now :-)

**Comment by lafriks** [comment]
Thank you, it's now also 100% approved :)

**Comment by Arvil** [comment]
Sorry to unearth the thread. I have updated the french translation last week - coverage was back to 40% somehow. It needs proofreading (@axeloz maybe ?) and eventually approval (@lafriks ? :)).
