### ISSUE TITLE
`browser_download_url` broken for private repositories

### ISSUE THREAD

**Issue by selukov** [go-gitea/gitea#27142]
### Description

After updating to version 1.20.4, I can't download a file from a private directory. I tested this on your try.gitea.io test server and got the same result. Specifically, when I check the 'visibility' checkbox and make the repository private, I can't download the file. 
I get a link to the file through the API /repos/{owner}/{repo}/releases/tags/{tag}.
[![Screenshot-from-2023-09-20-05-25-48.png](https://i.postimg.cc/28kZD0qz/Screenshot-from-2023-09-20-05-25-48.png)](https://postimg.cc/14dt0ccT)
The download commands are as follows:
```wget --header="Authorization: Bearer ${key}" -O ./LSPosed-v1.9.1-6990-zygisk-release.zip "https://try.gitea.io/selukov/testing/releases/download/0.0.2/LSPosed-v1.9.1-6990-zygisk-release.zip"```
```curl -H "Authorization: token ${key}" -o ./LSPosed.zip -L -O "https://try.gitea.io/selukov/testing/releases/download/0.0.2/LSPosed-v1.9.1-6990-zygisk-release.zip"```
Here is the result of the commands.
[![Screenshot-from-2023-09-20-05-43-10.png](https://i.postimg.cc/wjP2MCJ5/Screenshot-from-2023-09-20-05-43-10.png)](https://postimg.cc/xXvMFF6q)

When the 'visibility' checkbox is unchecked, meaning the repository is public, I can download files. Please refer to the picture below.
[![Screenshot-from-2023-09-20-05-25-01.png](https://i.postimg.cc/NF6G2v5K/Screenshot-from-2023-09-20-05-25-01.png)](https://postimg.cc/30wQz6jh)

### Gitea Version

1.20.4 

### Can you reproduce the bug on the Gitea demo site?

Yes

### Git Version

1.20.4 

### Operating System

docker

### How are you running Gitea?

I use try.gitea.io my test repositories https://try.gitea.io/selukov/testing/releases 

### Database

None

**Comment by JakobDev** [comment]
Will be fixed with #26430

**Comment by selukov** [comment]
The error has been fixed in version 1.20.5.
[![Screenshot-from-2023-10-10-18-05-45.png](https://i.postimg.cc/dQjDzcr8/Screenshot-from-2023-10-10-18-05-45.png)](https://postimg.cc/dDDqyXW1)
