### ISSUE TITLE
Integration tests for PR functionality when issues are disabled

### ISSUE THREAD

**Issue by lafriks** [go-gitea/gitea#2715]
Need integration tests for #2710

**Comment by jonasfranz** [comment]
I've created some tests. But I'am not sure if they work properly and if they test everything needed.

My branch: https://github.com/go-gitea/gitea/compare/master...JonasFranzDEV:integration-test-pr?expand=1

Is there a good way to test integration tests locally? drone cli does not work for some reason.

**Comment by Morlinest** [comment]
@JonasFranzDEV You can run it same as `make test` but you need database up and running. I use 2 docker containers (gitea and db) on same custom network.

**Comment by jonasfranz** [comment]
@Morlinest could you send me your docker commands or docker-compose file?

**Comment by Morlinest** [comment]
@JonasFranzDEV I am using my own image (#2377), but you can try something like this (I can't test it because I can't mount local volumes now):
```
docker network create gitea-test
docker run -d --rm --net gitea-test -e POSTGRES_DB=test --name pgsql postgres:9.5
docker run -i --rm --net gitea-test -v <MY-PROJECT-PATH>:/srv/app/src/code.gitea.io/gitea -w /srv/app/src/code.gitea.io/gitea --net gitea -e TAGS="bindata" webh
ippie/golang:edge make clean generate build test-pgsql
```

Change `<MY-PROJECT-PATH>` for your path to project.

**Comment by lafriks** [comment]
This issue is about that that when issues in repository is disabled in PR it was not possible (tests must test that is possible) to:
* Add/remove labels
* Set/remove milestone
* Set/remove assignee
* Add/change/delete comment
* Start/stop/add timetracking
* Close PR
* Multi-PR actions from PR list
