### ISSUE TITLE
When mirroring, an error returned.

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#27159]
### Description

```log
fatal: Unable to create 'lunny2/pytorch.git/./objects/info/commit-graphs/commit-graph-chain.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
```

### Gitea Version

2001ffee3fa7e100c0829660a505fcb6044296d0

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

local dev env

### Database

None

**Comment by wxiaoguang** [comment]
See https://github.com/go-gitea/gitea/issues/22578#issuecomment-1478838673 and more

**Comment by Cyberes** [comment]
I'm still getting this error when trying to mirror `https://github.com/go-gitea/gitea.git`. Seems like it's not fixed yet.

**Comment by lunny** [comment]
Duplicate of #22578
