### ISSUE TITLE
Support for GDScript syntax highlight in code editor 

### ISSUE THREAD

**Issue by damvcoool** [go-gitea/gitea#27160]
### Feature Description

As Godot grows in popularity I believe it would be great if gitea added some support for the most commonly used language in Godot projects which is GDScript.

**Comment by lng2020** [comment]
We use [go-enery](https://github.com/go-enry/go-enry) for language detection and [chroma](https://github.com/alecthomas/chroma) for syntax highlighting. You could request it be added there and then we can support it here.

**Comment by damvcoool** [comment]
Seems like both go-enry and chroma already have support for GDScript
