### ISSUE TITLE
CSS Errors

### ISSUE THREAD

**Issue by C-EO** [go-gitea/gitea#27166]
### Description

Is this supposed to be there?

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/85847352/24f3f73e-50a4-4165-915b-87626dec214d)

### Gitea Version

 1.22.0+dev-3-ge46274b5b

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

linux 6.2.0-1013-gcp

### Browser Version

Microsoft Edge 117.0.2045.31 (Official build) (64-bit)

**Comment by wxiaoguang** [comment]
->  Fix repo sub menu #27169
