### ISSUE TITLE
More UI Errors

### ISSUE THREAD

**Issue by C-EO** [go-gitea/gitea#27173]
### Description

Currently, I'm finding very many UI errors on Gitea. Most of them are padding. A few are with non-working buttons.

### Screenshots

Why are the arrows not in line with the words? It's weird to have them slightly above the words. ->
![image](https://github.com/go-gitea/gitea/assets/85847352/d7488ba0-f50b-4ace-aad5-e0af47a9aaf0)

![image](https://github.com/go-gitea/gitea/assets/85847352/2599856e-d679-4c66-9cf2-0584def31336)

Padding. ->
![image](https://github.com/go-gitea/gitea/assets/85847352/bfdbd762-1d7f-4998-89d4-31c4d6755051)

Wording needs more centering in some buttons. ->
![image](https://github.com/go-gitea/gitea/assets/85847352/c90d091e-8ed2-4b1b-967e-c9a5e5e9f853)

Non-working buttons. (For now only on 500 page) ->
![image](https://github.com/go-gitea/gitea/assets/85847352/551ef8f3-831c-43a1-8046-a3dceca421e7)

### Gitea Version

1.22.0+dev-3-ge46274b5b

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

linux 6.2.0-1013-gcp

### Browser Version

Microsoft Edge 117.0.2045.31 (Official build) (64-bit)

**Comment by silverwind** [comment]
> The 500 page doesn't have the ability render user-related menu. So that "icon" is just to make the UI look "balanced", it is a fake button.

We should adapt the styling of the button to be inline with the current button that has no border or background. Ideally I'd like this non-function button to be removed, though.

**Comment by wxiaoguang** [comment]
I am neutral for changing/keeping/removing the fake button, either is fine, since the 500 page is not a real user page and shouldn't appear in daily usage.
