### ISSUE TITLE
«Internal server error» on simple URL mangling

### ISSUE THREAD

**Issue by jn0** [go-gitea/gitea#27176]
### Description

I tried (occasionally) to get to URL like `https://example.com/gitea/issues?labels=!30` and got error 500.

System journal has few lines for it (for `gitea.service`):
```
Sep 21 18:17:58 blackbox gitea[2170]: 2023/09/21 18:17:58 ...ers/web/user/home.go:490:buildIssueOverview() [E] [650c5ea6] StringsToInt64s: strconv.ParseInt: parsing "!30": invalid syntax
Sep 21 18:17:58 blackbox gitea[2170]: 2023/09/21 18:17:58 [650c5ea6] router: completed GET /issues?labels=!30 for 192.168.1.1:0, 500 Internal Server Error in 16.0ms @ user/home.go:308(user.Issues)
```

### Gitea Version

Gitea version 1.19.3 built with GNU Make 4.1, go1.20.4 : bindata, sqlite, sqlite_unlock_notify

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

Ubuntu 22.04.1 LTS

### How are you running Gitea?

Gitea is ran on premise, at home.

Cannot verify try.gitiea.io -- registration pending.

### Database

SQLite

**Comment by jn0** [comment]
Just upgraded to the latest version, but the bug is still here:

![image](https://github.com/go-gitea/gitea/assets/407437/5d73c692-a4af-4947-b0bb-50079c2d3c7e)

**Comment by jn0** [comment]
@wxiaoguang yepp, it should not - it was my typo.

I don't insist that this behaviour is incorrect, but it's quite strange to get 500 on mere URL typo.

**Comment by wxiaoguang** [comment]
If you see it again, could you navigate your browser back and try to figure out where the URL comes from?

**Comment by jn0** [comment]
@wxiaoguang it was *literally* typo - it was me who have entered wrong URL.

In humble attempt to filter issues…

**Comment by jn0** [comment]
@wxiaoguang yes, it tald :)

But I'd prefer a bit less offensive way over "error 500" that made me jump and look at the box it's ran on.

At least in semantics of the HTTP codes, it should be 400 "Bad Request", and not 500.

**Comment by wxiaoguang** [comment]
That's a longstanding problem in Gitea: there are a lot of unnecessary 500 responses. I am afraid such behavior is nearly impossible to get a complete fix at the moment.

**Comment by wxiaoguang** [comment]
There is a "500" summary issue:  Improve troubleshooting for 500 and other server errors #8016 (really longstanding ....)

**Comment by yp05327** [comment]
@wxiaoguang 
Can this issue be closed? As it is just a typo.
ps: of cause, we need to consider the HTTP codes later.

**Comment by lunny** [comment]
Maybe a PR returned 400 is a better choice.

**Comment by wxiaoguang** [comment]
I would suggest to simply ignore such annoying error. Just like others:

![image](https://github.com/go-gitea/gitea/assets/2114189/74185261-d57b-4876-b27b-15d01d8ca5e9)

**Comment by wxiaoguang** [comment]
->  Refactor StringsToInt64s #29967
