### ISSUE TITLE
Change X-Frame-Options to "allow-from"

### ISSUE THREAD

**Issue by carolcoral** [go-gitea/gitea#27186]
### Description

i had install it in my server's as docker compose.
i used https://redirect.x.x:18092 as the Git website, and used http://gitea.x.x proxy this site.But i found it not work, because it's header `X-Frame-Options` value is `SAMEORIGIN` that why i can not use it by `<iframe></iframe>`.

Could you change the request header of `X-Frame-Options` value to `allow-from`? And i can change it in `app.ini`.

Demo site: [gitea](http://gitea.cnkj.site)

### Screenshots

<img width="1485" alt="image" src="https://github.com/go-gitea/gitea/assets/8952687/0a8e30f5-3254-48b5-a60c-dfe8b88c6db6">

### Gitea Version

1.20.4

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

MacOS

### Browser Version

Chrome 115.0.5790.170

**Comment by wxiaoguang** [comment]
https://github.com/go-gitea/gitea/blob/383edf2fd7d3cf952c491dd483ba68d7a8e4aaf2/custom/conf/app.example.ini#L1175-L1176
