### ISSUE TITLE
render plain text README.txt with monospace font

### ISSUE THREAD

**Issue by pmorjan** [go-gitea/gitea#2718]
- Gitea version:
1.2.1
- Example
https://try.gitea.io/pmorjan/issue2701
## Description
A plain text README.txt should be rendered on the repo home page with a
 monospace font to  preserve text formatting and indentations.

**Comment by jonasfranz** [comment]
It seams that *.txt files are rendered as HTML and **not** as text file.

**Comment by Morlinest** [comment]
@JonasFranzDEV You are right, adding `<pre></pre>` solves it

**Comment by lunny** [comment]
~@lafriks why close this one?~

**Comment by lafriks** [comment]
@lunny I just merged PR that fixed it :)
