### ISSUE TITLE
Invalid mailer.FROM causes the installation to fail.

### ISSUE THREAD

**Issue by dawnlyn** [go-gitea/gitea#27188]
### Description

Because I have not been able to complete the installation, and then looked at the running status of gitea and realized:
`Invalid mailer.FROM (Violet-VE): mail: missing '@' or angle-addr`

# But he didn't prompt me when I was filling out the form.

### Gitea Version

1.20.4

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

systemctl start gitea

### Database

MySQL/MariaDB

**Comment by carlosfelgueiras** [comment]
Just reproduced this. I will work on it.
