### ISSUE TITLE
Editing issues does not relink SHA hashes

### ISSUE THREAD

**Issue by colejohnson66** [go-gitea/gitea#27198]
### Description

When posting a new issue or comment, SHA hashes are auto-linked (and wrapped in `<code>`), but editing them does not relink them until a refresh. The previewer also shows them unwrapped.

### Gitea Version

1.20.3

### Can you reproduce the bug on the Gitea demo site?

Untested

### Screenshots

After editing (and editor preview):
![image](https://github.com/go-gitea/gitea/assets/11381599/d5c44318-740e-4ccf-b83a-2f9ffcb42bff)

After refresh:
![image](https://github.com/go-gitea/gitea/assets/11381599/9761186b-73a2-4351-881d-3dd0729ab97b)

### How are you running Gitea?

Windows Service

### Database

None

**Comment by metiftikci** [comment]
@colejohnson66 i can not reproduce this. can you?

@lunny ping

**Comment by colejohnson66** [comment]
Nope. No repro in 1.22.6. Must've been fixed in the meantime.
