### ISSUE TITLE
Auto creation of images

### ISSUE THREAD

**Issue by zacekjakub** [go-gitea/gitea#27197]
### Feature Description

Could Gitea get some mechanism to autocreate images from repos? Or is there any workaround? Thank you!

**Comment by zacekjakub** [comment]
Talking about creation of docker image from git branch. Gitea already has docker registry, so it would just on push to repo trigger docker build and the created image would be saved to the registry.

Does it make better sense now?

**Comment by yardenshoham** [comment]
I agree with @jolheiser. I think we should close this issue.

**Comment by zacekjakub** [comment]
Thank you, I didn't know about Gitea actions, it is disabled by default.

**Comment by jolheiser** [comment]
No problem, glad to help. :slightly_smiling_face: 
https://docs.gitea.com/usage/actions/overview
