### ISSUE TITLE
Dropdown doesn't work when clicking on an arrow

### ISSUE THREAD

**Issue by stuzer05** [go-gitea/gitea#27224]
### Description

![image](https://github.com/go-gitea/gitea/assets/23124682/68c65645-6f93-4428-9715-3744779f4161)

Doesn't open when ckicking in the arrow vicinity

### Gitea Version

trunk

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

docker

### Database

None

**Comment by wxiaoguang** [comment]
It's Fomantic UI's bug.

->  Fix Fomantic UI dropdown icon bug when there is a search input in menu #27225
