### ISSUE TITLE
Provide more detailed error information for 'Push to Create not enabled'.

### ISSUE THREAD

**Issue by LamGC** [go-gitea/gitea#27229]
### Feature Description

In version 1.20.4, if a user pushes a non-existent repository, Gitea will return the following error message:

![image](https://github.com/go-gitea/gitea/assets/16975255/5e7e29af-6771-45da-8343-8573df96f191)

This error message is a bit difficult to understand. After encountering this issue, I needed to consult the documentation to understand the Push to create function before understanding this error message.

I hope this error message not only reminds the user that the server has not enabled the Push to Create function, but also reminds the user maybe that the current remote address has invalidated, reducing the time required for troubleshooting errors.

**Comment by lunny** [comment]
So what's the real reason in your case?

**Comment by LamGC** [comment]
Just because the name of the repository was changed a long time ago without changing the remote address of the local repository.😂

________________________________

**Comment by lng2020** [comment]
The error message sounds reasonable to me. Note that `Please make sure you have the correct access rights and the repository exists`. In your case, it's the repository does not exist.

**Comment by LamGC** [comment]
> The error message sounds reasonable to me. Note that `Please make sure you have the correct access rights and the repository exists`. In your case, it's the repository does not exist.

Indeed, the information provided by Git at the bottom has already reminded me of this. 

I don't know why, I always think it's not a real reason, I only focus on the error message returned by the server.

(Perhaps I have encountered such a situation before? I have already forgotten)
