### ISSUE TITLE
Start built-in server

### ISSUE THREAD

**Issue by MetaiR** [go-gitea/gitea#2723]
hello,
please tell me what's this and how to make it enable,
I tried to put `START_SSH_SERVER` in `app.ini` in server section but then it wasn't started anymore.
 
![image](https://user-images.githubusercontent.com/7807264/31650571-c8f882fa-b324-11e7-9124-7004f97e1b3f.png)

**Comment by jonasfranz** [comment]
Could you please send the log and your config file?

**Comment by MetaiR** [comment]
I didn't know there is a log, so thanks a lot, it was about permission on port 22, I changed it to 3001 and all done.
just one more question
I'm using gitea as a service with a different user in my server, so I want to know does it safe to use ssh and allow its port in my firewall?

**Comment by jonasfranz** [comment]
Yes, because SSH is not used to gain access to your server because it is used to transfer files via Git. It is simply an alternative to HTTP(S).

**Comment by MetaiR** [comment]
thanks a lot
