### ISSUE TITLE
Also request entering the repository name when delete it in admin settings page?

### ISSUE THREAD

**Issue by yp05327** [go-gitea/gitea#27247]
### Feature Description

To avoid the risk of mistakenly delete repository, we need to enter the repository name when delete it in the settings page: 
![image](https://github.com/go-gitea/gitea/assets/18380374/2c5f4500-88f2-40cd-bab5-8029589b2004)

But in admin page, we don't have this input check. Admin user can easily delete the repository by only one click.
![image](https://github.com/go-gitea/gitea/assets/18380374/0fd696e4-4540-4523-bea4-45c1a7324365)
So I think this can be considered as a risk, and it is better to add a input check request here.

**Comment by wxiaoguang** [comment]
* https://github.com/go-gitea/gitea/issues/26633#issuecomment-1686405677
