### ISSUE TITLE
Git LFS File Locking API

### ISSUE THREAD

**Issue by flozz** [go-gitea/gitea#2725]
- Gitea version (or commit ref): 1.2.0
- Git version: 2.11.0
- Operating system: Debian 9
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist: -

## Description

Hi, 

The [Git LFS File Locking API](https://github.com/git-lfs/git-lfs/blob/master/docs/api/locking.md) is currently not implemented in Gitea:

```
$ git lfs lock foo.bin
Lock failed: Repository or object not found: http://git.example.com/test/test.git/info/lfs/locks
Check that it exists and that you have proper access to it
```

I wonder if there is a plan to support it or even if someone is interested by it?

**Comment by OmarAssadi** [comment]
>or even if someone is interested by it?

Useful feature, IMO! Added a tiny starting bounty to this one. 

[![current amount](https://api.bountysource.com/badge/issue?issue_id=50410108)](https://www.bountysource.com/issues/50410108-git-lfs-file-locking-api)

**Comment by sapk** [comment]
I could take that one if no one is on it. ^^

**Comment by lunny** [comment]
@sapk please do it.
