### ISSUE TITLE
Need the feature of Browse the repository at this point in the history

### ISSUE THREAD

**Issue by ffbh123456** [go-gitea/gitea#27255]
### Feature Description

It is on the GitHub commits page, not sure if Gitea has this feature though I can't find it on Gitea's commits page.
<img width="455" alt="Screenshot 2023-09-25 at 4 52 41 PM" src="https://github.com/go-gitea/gitea/assets/20750357/deffbf9b-aa7d-4dc5-8be4-7e8385754614">

**Comment by delvh** [comment]
Yes.
![grafik](https://github.com/go-gitea/gitea/assets/51889757/7351f3f3-eb64-42be-876c-ce97392a198b)

**Comment by delvh** [comment]
(But yes, you need an extra click at the moment as you must first select the respective commit, and then click on `Browse Source`)

**Comment by ffbh123456** [comment]
cool, that's it, thanks
