### ISSUE TITLE
Error while adding user with full name to team

### ISSUE THREAD

**Issue by webjoel** [go-gitea/gitea#2726]
- Gitea version (or commit ref): 9e865ce
- Git version: 2.7.4
- Operating system: Linux Ubuntu 16.04
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes ( https://try.gitea.io/org/webjoel_test_user/teams/team_test )
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

When adding a user with full name filled to a team occurs the error that the user does not exist, removing the full name of the user in his or her registry works perfectly.

## Screenshots

![captura de tela de 2017-10-17 13-08-36](https://user-images.githubusercontent.com/1946348/31672962-b328c738-b33c-11e7-9d94-53e03fde997f.png)

**Comment by pgaskin** [comment]
I'm quite sure this is expected behavior.

**Comment by webjoel** [comment]
I do not agree, I can not add users who filled out your full name? In my opinion when searching for a user up could come the full name, but at the moment of adding the validation has to be only by username and not together as full name.

**Comment by pgaskin** [comment]
@webjoel good point.

**Comment by webjoel** [comment]
this was eventually corrected with issue #2962. I to close.

**Comment by lunny** [comment]
That's a duplicated of this one in fact.
