### ISSUE TITLE
When I click the notice,come to 500

### ISSUE THREAD

**Issue by Shanyoufusu12** [go-gitea/gitea#27280]
### Description

![image](https://github.com/go-gitea/gitea/assets/60723145/7006bee3-d79d-430f-829e-d369b7160a30)
![image](https://github.com/go-gitea/gitea/assets/60723145/27bf6a17-6505-473c-9dc3-72030d4d8fa7)

### Gitea Version

1.16.9

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

Docker

### Database

PostgreSQL

**Comment by wxiaoguang** [comment]
This is an invalid report.

1. `1.16.9` is out-dated (has been out-dated for long time). Please use latest (1.20 or 1.21-rc)
2. `Can you reproduce the bug on the Gitea demo site? Yes`. I do not believe it.
