### ISSUE TITLE
Issue edit history sometimes doesn't show the "Delete from history" menu.

### ISSUE THREAD

**Issue by ell1e** [go-gitea/gitea#27313]
### Feature Description

A part of the appeal of editing comments is to edit out something you didn't mean to post and don't want to end up in search engine indexes forever on a public repo. (I get it might still be e-mailed and shown to some people but that's not the same at all like it lingering forever on the internet.) However, that only works when it's possible **to delete old revisions of your own edited comments, which I'm hereby proposing.** GitHub by the way has been offering this for quite a while already. Or alternatively, do it like GitLab and just don't show older versions or any comment history at all. This in between where all older versions of a comment are kept forever but there seems to be no obvious way to delete them seems like a very unfortunate in-between.

Interestingly, the UI to pick and show an old version in a popup where just a single button for deletion would need to be added, is already there. So UI-wise, this change seems really minor. I hope it can be added.

Sure, it's still possible to delete an entire comment instead to "solve" this, but that seems like quite the nuclear option. It would be better to do it like GitHub, where you can delete an old version of the comment but then it also still shows transparently if you check that the older version existed but that it was deleted. That seems like the best of all worlds.

**Comment by wxiaoguang** [comment]
I do not understand what do you mean.


![image](https://github.com/go-gitea/gitea/assets/2114189/c1fed4b3-4987-4ee3-a603-cf2b66f52a72)

**Comment by ell1e** [comment]
![Screenshot from 2023-09-28 03-24-24](https://github.com/go-gitea/gitea/assets/64124388/a9d3a502-8cc2-48be-b302-6ab744910f87)

**Comment by wxiaoguang** [comment]
I do not know what you are talking about.

![image](https://github.com/go-gitea/gitea/assets/2114189/e42362c8-34b7-43ca-bd89-25a3995bb31a)

**Comment by ell1e** [comment]
Ah, my deepest apologies! Was this a recent addition perhaps? It seems like Codeberg is still based on too old Gitea code to show this. In any case, seems like this ticket is invalid, I'm sorry about that.

**Comment by wxiaoguang** [comment]
Hmm .... good point. 

I guess there is a bug. In some cases, the "delete" menu doesn't show. I will look into it.

Thank you for your report!

**Comment by ell1e** [comment]
Oh, I'm surprised this isn't just me not checking the server version properly :sweat_smile: :joy:

**Comment by wxiaoguang** [comment]
The problem is in `canSoftDeleteContentHistory`, the `CanWrite` check was incorrect.

->  Improve issue history dialog and make poster can delete their own history #27323 

Thank you again.
