### ISSUE TITLE
Password complexity check with PASSWORD_COMPLEXITY  = ["lower", "upper", "digit", "spec"] accepts a password with no special character

### ISSUE THREAD

**Issue by kaidrumm** [go-gitea/gitea#27316]
### Description

I have Gitea on a LXC container (Turnkey Gitea).

Under [security] in app.ini, I have tried:
PASSWORD_COMPLEXITY     = ["lower", "upper", "digit", "spec"]
or 
PASSWORD_COMPLEXITY     = [lower, upper, digit, spec]

However, a password that has no special character succeeds. 
The tests in modules/auth/password/password_test.go do not include a test for all four character classes.

### Gitea Version

Gitea version 1.18.3 built with GNU Make 4.1, go1.19.5 : bindata, sqlite, sqlite_unlock_notify

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

I am running Turnkey Gitea in a LXC container.

### Database

MySQL/MariaDB

**Comment by wxiaoguang** [comment]
PASSWORD_COMPLEXITY=lower,upper,digit,spec
