### ISSUE TITLE
Failed to create queue "notification-service

### ISSUE THREAD

**Issue by 54huige** [go-gitea/gitea#27355]
### Description

ww/wwwroot/gitea.com/data/repo-archive
2023/09/30 02:40:30 ...s/storage/storage.go:208:initPackages() [I] Initialising Packages storage with type: local
2023/09/30 02:40:30 ...les/storage/local.go:33:NewLocalStorage() [I] Creating new Local Storage at /www/wwwroot/gitea.com/data/packages
2023/09/30 02:40:40 ...les/queue/manager.go:108:]() [E] Failed to create queue "notification-service": unable to open level db at /www/wwwroot/gitea.com/data/queues/common: open /www/wwwroot/gitea.com/data/queues/common/LOCK: permission denied
2023/09/30 02:40:40 ...otification/ui/ui.go:42:NewNotifier() [F] Unable to create notification-service queue

### Gitea Version

Gitea version 1.20.4 built with GNU Make 4.2.1, go1.20.8 : bindata, sqlite, sqlite_unlock_notify

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

The server crashed and could not be started again 'gitea'

### Database

SQLite

**Comment by wxiaoguang** [comment]
1. You are running two Gitea instances at the same time, do not do that.
2. Your NFS is broken. See the FAQ.
3. You have incorrect filesystem permission (usually unlikely)
