### ISSUE TITLE
Auto-closing of issues via PR doesn't work

### ISSUE THREAD

**Issue by SnowMB** [go-gitea/gitea#2735]
- Gitea version (or commit ref): 1.2.0+6-g46bb1cf
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
I've tried a few things to automatically close issues when a PR is merged. I haven't found a way to do it.
Neither a commit with the message containing `closes #xx` nor using `closes #xx` as title or pr message has any effect. 

This is problematic because gitea doesn't display references that are made to the pr / issue in the discussion tab like github does. So there is no indicator if the issue was discussed / handled in another issue / pr.

**Comment by lunny** [comment]
@lafriks this should be a bug, but not an enhancement.

**Comment by SnowMB** [comment]
@lunny It might be both. A bug for not recognizing the "closes #xx" in a commit message after the pr is merged.

Feature request for also supporting closing issues by title / description of the PR.

**Comment by krrutkow** [comment]
Any update on when this issue might be addressed?

**Comment by finalex** [comment]
Is there any plan for this issue?

**Comment by mrsdizzie** [comment]
Fixed since #8866
