### ISSUE TITLE
Personal dashboard error when including release

### ISSUE THREAD

**Issue by ExplodingDragon** [go-gitea/gitea#27369]
### Description

This issue occurs after pushing a new tag and manually creating a release.

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/33776693/4e2b8382-f2c6-4d31-aec6-3f3cc965f6d9)

### Gitea Version

main (83f571628d186d8b865707c3c7b22de8bd530c4c)

### Can you reproduce the bug on the Gitea demo site?

Yes

### Browser Version

firefox last stable

**Comment by CaiCandong** [comment]
Regression of #27265 @JakobDev
