### ISSUE TITLE
Gitea hosted Gitea interfered by Chinese GFW

### ISSUE THREAD

**Issue by duchenpaul** [go-gitea/gitea#27371]
### Description

This is a discussion for Chinese mainland users.
Recently I found difficulties connecting to gitea.com, my script often fails to send API to gitea.com.

so wonder if https://www.gitea.com/ is being intermittently blocked or jammed by GFW.

I am collecting feedback from Chinese mainland users.

### Gitea Version

Not related

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

Gitea hosted Gitea

### Database

None

**Comment by lunny** [comment]
We can't resolve this problem ourselves. gitea.com aims to provide service around the global.

**Comment by techknowlogick** [comment]
What is your username on Gitea.com, and what are you attempting to do with the API?

**Comment by duchenpaul** [comment]
> What is your username on Gitea.com, and what are you attempting to do with the API?

duchenpaul

Using API to update the content of a file.

**Comment by duchenpaul** [comment]
> What is your username on Gitea.com, and what are you attempting to do with the API?

duchenpaul

Using API to update the content of a file.
