### ISSUE TITLE
"An error occurred" when I want to access a new repo

### ISSUE THREAD

**Issue by MrVrops** [go-gitea/gitea#27389]
### Description

Hello everyone, 

The existing repos in my Gitea instance work well.

However, when I try to create a new repo, I can do it but when I try to access it I encounter the following error: 
An error occurred 
The Git data underlying this repository cannot be read. Contact the administrator of this instance or delete this repository.

When I go into my log file, I come across these lines when I refresh the page on this new repo:
`2023/10/02 09:17:05 ...ers/web/repo/view.go:890:renderCode() [E] GitRepo.IsEmpty: check empty: exit status 129 - usage: git rev-list [OPTION] <commit-id>... [ -- paths... ]
  limiting output:
    --max-count=<n>
    --max-age=<epoch>
    --min-age=<epoch>
    --sparse
    --no-merges
    --min-parents=<n>
    --no-min-parents
    --max-parents=<n>
    --no-max-parents
    --remove-empty
    --all
    --branches
    --tags
    --remotes
    --stdin
    --quiet
  ordering output:
    --topo-order
    --date-order
    --reverse
  formatting output:
    --parents
    --children
    --objects | --objects-edge
    --unpacked
    --header | --pretty
    --abbrev=<n> | --no-abbrev
    --abbrev-commit
    --left-right
    --count
  special purpose:
    --bisect
    --bisect-vars
    --bisect-all
2023/10/02 09:17:05 ...eb/routing/logger.go:102:func1() [I] router: completed GET /Cloud/Test for SECRET-IP:0, 200 OK in 31.1ms @ repo/view.go:711(repo.Home)`

Have you ever seen a similar case? If so, can you help me?

Thank you for your help.

### Gitea Version

1.20.4

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

![Capture](https://github.com/go-gitea/gitea/assets/25271722/6159fcae-7e7c-4cd0-aeaf-9c1322a84934)

### Git Version

2.11.0

### Operating System

Debian 9

### How are you running Gitea?

Installation from binary.

### Database

MySQL/MariaDB

**Comment by wxiaoguang** [comment]
Related to #26517

You can update your "git" package to a newer version.

**Comment by MrVrops** [comment]
Thank you for your reply

I'm stuck at git 2.11.0 with Debian 9, if I install git via source I won't encounter compatibility problems?

Thanks for all

**Comment by wxiaoguang** [comment]
Or you could try to downgrade Gitea to 1.20.2 which doesn't contain that fix.

It's safe to directly downgrade to 1.20.x

**Comment by wxiaoguang** [comment]
Or you could try to build your own binary by with "Fix git 2.11 error when checking IsEmpty #27393", or wait for its backport to 1.20.5
