### ISSUE TITLE
AutoLink Referencing issue in Referenced issue

### ISSUE THREAD

**Issue by palamccc** [go-gitea/gitea#2739]
- Gitea version (or commit ref): a4cd461
- Git version: 2.11

## Description
Github have nice way of showing referenced issues like
```
<user> referenced this issue in <repo>
```
Please add this feature to gitea roadmap.

## Screenshot from Github (not gitea)
![screenshot from 2017-10-19 10-23-28](https://user-images.githubusercontent.com/202276/31754794-bce53154-b4b7-11e7-9585-022bc48e31b8.png)

**Comment by krrutkow** [comment]
This feature should be added whenever #3695 is merged.

**Comment by JustAnotherArchivist** [comment]
It appears that this has been implemented with #8137 in 1.10.

**Comment by guillep2k** [comment]
> 
> 
> It appears that this has been implemented with #8137 in 1.10.

@JustAnotherArchivist That's correct. This issue can be closed.
