### ISSUE TITLE
Duplicated struct tag name in internal struct `migrations.rawRepository` 

### ISSUE THREAD

**Issue by chavacava** [go-gitea/gitea#27401]
### Description

In
https://github.com/go-gitea/gitea/blob/dfa4e5857fe9d8f113cf50d4c7fda094f0f30b74/services/migrations/codebase.go#L191-L209
the `xml` struct tag name `ticketing-milestone` is repeated.
It seems the first field (`XMLName`) should have a different tag name.

### Gitea Version

88f8351

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

I do not run gitea, 

### Database

None

**Comment by Zettat123** [comment]
The xml response is like
```
<ticketing-milestone type="array">
    <ticketing-milestone>
        <id type="integer">1</id>
        <identifier>xxxx</identifier>
        <name>name1</name>
        <start-at type="date">2023-10-01</start-at>
        <description>desc1</description>
        <estimated-time type="integer">0</estimated-time>
        <status>active</status>
    </ticketing-milestone>
    <ticketing-milestone>
        <id type="integer">2</id>
        <identifier>xxxx</identifier>
        <name>name2</name>
        <start-at type="date">2023-10-03</start-at>
        <description>desc2</description>
        <estimated-time type="integer">0</estimated-time>
        <status>active</status>
    </ticketing-milestone>
</ticketing-milestone>
```

so I think the two `ticketing-milestone` tags are correct.
