### ISSUE TITLE
gitea.service systemd script doesn't work on Ubuntu

### ISSUE THREAD

**Issue by TheFriendlyCoder** [go-gitea/gitea#27422]
### Description

According to [the docs](https://docs.gitea.com/installation/linux-service) one should be able to install Gitea on Ubuntu using `snap` and then launch the app via a systemd service using the sample service file found [here](https://github.com/go-gitea/gitea/blob/release/v1.20/contrib/systemd/gitea.service), however based on my recent test deployment on Ubuntu 22.04 this does not work.

After spending some time debugging the problem, it seems the issue comes down to the `Type=notify` setting in the [config file](https://github.com/go-gitea/gitea/blob/release/v1.20/contrib/systemd/gitea.service#L55). Based on what I'm seeing, this setting is expecting the Gitea app to send a signal to systemd to notify it when the service is running, but this never actually happens, so systemd assumes the service is hung and times out after a while. Except, after the `systemctl start gitea` operation fails, the service itself is actually running fine.

Further, in order to side-step this problem in my environment I've simply changes the Type property to `Type=simple`, which allows the application to launch in the background, so that systemd isn't left waiting for a response from gitea. This is less than ideal because errors in the gitea startup sequence can go unnoticed, but at least it allows the service to start in a best-case scenario.

### Gitea Version

Gitea version 1.20.5 built with GNU Make 4.3, go1.21.1 : bindata, sqlite, sqlite_unlock_notify, pam, cert

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

git version 2.34.1

### Operating System

Ubuntu 22.04.3 LTS

### How are you running Gitea?

As a systemd service.

### Database

SQLite

**Comment by lunny** [comment]
Maybe #21151 has some problems.

**Comment by TheFriendlyCoder** [comment]
Based on [this comment](https://github.com/go-gitea/gitea/pull/21151#issuecomment-1663069147) I believe you are correct.

**Comment by lng2020** [comment]
<img width="788" alt="image" src="https://github.com/go-gitea/gitea/assets/70063547/ce0ecd91-4e6d-4cca-9f95-b6cca0e7cd0e">
works for me in Gitea's latest codebase and Ubuntu22.04. Probably there are some configs in app.ini that should be synced. I just reused my own app.ini in `/home/username` and it works well.

**Comment by lng2020** [comment]
After switching to the latest/stable(1.21.5) snap package, the Gitea indeed kept rebooting. The `gitea.service` file
```conf
[Unit]
Description=Gitea (Git with a cup of tea)
After=syslog.target
After=network.target
[Service]
RestartSec=2s
Type=notify
WorkingDirectory=/var/snap/gitea/common
ExecStart=/snap/bin/gitea web --config /var/snap/gitea/common/conf/app.ini
Restart=always
Environment=GITEA_WORK_DIR=/var/snap/gitea/common
WatchdogSec=30s
[Install]
WantedBy=multi-user.target
```

**Comment by techknowlogick** [comment]
I believe snap has its own built-in service manager, `snap run gitea` or `snap start gitea` (can't remember which right now) will start the daemon.

**Comment by TheFriendlyCoder** [comment]
That being the case, perhaps this is as simple as updating the docs to reflect that.

NOTE: I have confirmed that if I install the latest Gitea binary directly without using snap, the service will run as expected. So it is either a bug with the 1.20.4 version or a limitation of the snap package.

**Comment by techknowlogick** [comment]
Thanks for the suggestion @TheFriendlyCoder. @lng2020 sent a PR to the docs to update them. I'll close this now :)
