### ISSUE TITLE
Gitea is not respecting the GITEA_WORK_DIR env var

### ISSUE THREAD

**Issue by TheFriendlyCoder** [go-gitea/gitea#27421]
### Description

According to [the docs](https://docs.gitea.com/installation/install-from-binary?_highlight=gitea_work#2-running-from-command-lineterminal), you should be able to overload the default work dir for Gitea on the command line using the environment variable GITEA_WORK_DIR. However, this is not working. For example, I have a fully working Gitea install and I try to customize the work dir by doing the following:

`su -c "GITEA_WORK_DIR=/data/gitea gitea web --port=3005" git`

which results in a startup log that begins with:

```
2023/10/03 23:57:26 cmd/web.go:223:runWeb() [I] Starting Gitea on PID: 2931955
2023/10/03 23:57:26 cmd/web.go:148:serveInstalled() [I] Gitea version: 1.20.5 built with GNU Make 4.3, go1.21.1 : bindata, sqlite, sqlite_unlock_notify, pam, cert
2023/10/03 23:57:26 cmd/web.go:149:serveInstalled() [I] App path: /snap/gitea/6593/gitea
2023/10/03 23:57:26 cmd/web.go:150:serveInstalled() [I] Work path: /var/snap/gitea/common
2023/10/03 23:57:26 cmd/web.go:151:serveInstalled() [I] Custom path: /var/snap/gitea/common
2023/10/03 23:57:26 cmd/web.go:152:serveInstalled() [I] Config file: /var/snap/gitea/common/conf/app.ini
2023/10/03 23:57:26 cmd/web.go:153:serveInstalled() [I] Run mode: prod
2023/10/03 23:57:26 cmd/web.go:154:serveInstalled() [I] Prepare to run web server
2023/10/03 23:57:26 routers/init.go:112:InitWebInstalled() [I] Git version: 2.34.1, Wire Protocol Version 2 Enabled (home: /var/snap/gitea/common/data/home)
```

As you can see from this output, the app is using the default work path which is defined in the app.ini file, `/var/snap/gitea/common`. 

### Gitea Version

Gitea version 1.20.5 built with GNU Make 4.3, go1.21.1 : bindata, sqlite, sqlite_unlock_notify, pam, cert

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

git version 2.34.1

### Operating System

Ubuntu 22.04.3 LTS

### How are you running Gitea?

From the command line as shown above.

### Database

SQLite

**Comment by techknowlogick** [comment]
That env var is set in the snapfile and takes precedence over any other setting.

I'm not sure snap allows you to override these variables.

You can still update where the config exists, and the data is stored, using a combination of cli flags and config.
