### ISSUE TITLE
Swagger should be reserved when creating users (or: move /swagger to a different path)

### ISSUE THREAD

**Issue by thehowl** [go-gitea/gitea#2745]
- Gitea version (or commit ref): master
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes: https://try.gitea.io/swagger/this-exists - https://try.gitea.io/swagger

## Description

At the moment, if you try to access /swagger, it will not show the organization I created, but the org does exist. In order to address this issue, we should either forbid users creating new orgs or users with the name `swagger` (adding it to the list of blacklisted usernames), or move /swagger somewhere else (but thus generating some linkrot on gitea instances - perhaps redirect to new URL if there is no org, and show the org if there is one)

**Comment by strk** [comment]
I'd prefer moving swagger to `/api/swagger` or even `/api/<version>/swagger` when it makes sense
