### ISSUE TITLE
Allow scanning for and reporting vulnerabilities.

### ISSUE THREAD

**Issue by KazzmanK** [go-gitea/gitea#27462]
### Feature Description

We can analyze project at developer level, by running build goal, we can do analysis on Jenkins during build pipeline and we did not come into conclusion where is the proper place to have analysis?
Is it possible to have something like this at Gitea level?

![image](https://github.com/go-gitea/gitea/assets/13328513/83153d9e-78b6-4ed0-ac4b-62ac6e32deea)

The problem is how to make vulnerabilities report always ready and always on table? I do not want to run maven-analyze all the time, I do not look into Jenkins build output more or less often (but OWASP Dependency-check output [is pretty](https://www.google.com/search?q=dependency+check+jenkin&tbm=isch)). 
But Gitea is an everyday tool, and having a report there seems good.

**Comment by wfjake** [comment]
There is no feature specifically for security reporting. It is possible to accomplish a equivalent method through automation (run scan in Gitea action, have script parse results, script post new issue in repo say with tag "Security", and assign random developer to review. Have that occur say every week or so).

Possible duplicate of #24930
