### ISSUE TITLE
Render failed, failed to render template: user/profile

### ISSUE THREAD

**Issue by HeikoDressler** [go-gitea/gitea#27473]
### Description

on click to my Profile i got the following error:

Ein Fehler ist aufgetreten:

Render failed, failed to render template: user/profile, error: template error: builtin(bindata):shared/user/profile_big_avatar:86:87 : executing "shared/user/profile_big_avatar" at <.HasMemberWithUserID>: wrong number of args for HasMemberWithUserID: want 1 got 2
----------------------------------------------------------------------
					{{if (or .Visibility.IsPublic (and ($.SignedUser) (or .Visibility.IsLimited (and (.HasMemberWithUserID ctx $.SignedUserID) .Visibility.IsPrivate) ($.IsAdmin))))}}
					                                                                                  ^
----------------------------------------------------------------------
![image](https://github.com/go-gitea/gitea/assets/36741467/beec487b-5013-40df-b484-e0dec7a061ea)

### Gitea Version

1.21.0+rc0-69-g44aca6a65

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/36741467/6fb98985-7499-4e73-86df-beaf275bf1a5)

### Git Version

2.37.1, Wire Protocol Version 2 Enabled

### Operating System

Windows Server 2022 Standard

### How are you running Gitea?

 self hosting

### Database

MSSQL

**Comment by silverwind** [comment]
https://github.com/go-gitea/gitea/pull/27417 is related, but maybe the fix there was wrong? @delvh

**Comment by silverwind** [comment]
The function takes 1 argument on 1.21 branch but two on 1.22, so the backport was incorrect:

https://github.com/go-gitea/gitea/blob/44aca6a65a7c1765a765560e57e77be49ebec548/models/organization/org.go#L150

**Comment by delvh** [comment]
Erm… Could it be that we didn't backport the refactoring PR before it and thus the backport was unnecessary?

**Comment by silverwind** [comment]
Yes, likely missed one backport with the function refactoring.

**Comment by delvh** [comment]
Hmm… Does `revert`ing work for someone else on https://github.com/go-gitea/gitea/pull/27426? I only get a `500` on that page…
