### ISSUE TITLE
Notifications: show age / timestamp / date

### ISSUE THREAD

**Issue by drsybren** [go-gitea/gitea#27475]
### Feature Description

It would be really nice if the notifications list would show the age of these notifications. I'm not always keeping up with them, and it would be great to see how long ago the notification was sent.

### Screenshots

Example of what it could look like:

![example](https://github.com/go-gitea/gitea/assets/122987084/402f8d4f-b3f9-4f40-b93e-7bf3fa7a3f1b)

**Comment by techknowlogick** [comment]
I have some good news! In 1.21 there has been some love given to the notification pages and you'll get exactly this :)

![CleanShot 2023-10-06 at 10 40 14@2x](https://github.com/go-gitea/gitea/assets/164197/ccdffbac-28a1-4f00-be74-3216cc7549f9)

**Comment by drsybren** [comment]
That's nice, thanks!

But where did the button go that marks a notification as 'read'?

**Comment by techknowlogick** [comment]
@drsybren on hover there is the "read" button, but also there is a "pinned" button now to pin certain notifications to the top of your list.
