### ISSUE TITLE
HA configuration?

### ISSUE THREAD

**Issue by zfLQ2qx2** [go-gitea/gitea#2747]
I realize that that gitea was probably not engineered for concurrent access by multiple frontends on different servers - however,
* if I had a common database backend
* and hosted the repos on a networked filesystem
* and could guarantee that no two frontends would update the same repo at the same time
then do you think it would be feasible to have multiple gitea instances running concurrently without corrupting?

**Comment by lunny** [comment]
Currently, Gitea cannot guarantee that. It's safety on a single machine.

**Comment by zfLQ2qx2** [comment]
@lunny Ok, thanks for letting me know for certain
