### ISSUE TITLE
Branch protection not working on Gitea 1.2.1

### ISSUE THREAD

**Issue by lklock** [go-gitea/gitea#2748]
Hello,

We face an issue with the branch protection which doesn't allow to protect any branch

- Gitea version (or commit ref): 1.2.1
- Git version: 2.14.2
- Operating system:  Ubuntu 16.04.3 LTS 
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x ] No
  - [ ] Not relevant
- Log gist:

## Description

Most of the branches of I select are not being protected after selecting them
It works for some of them but I could not figure out any pattern (based on branch name per instance)

Example on one of our projects:

default branch set to dev-master
I can protect branch "master" but not branch"XTI-730" or "R_9_3_patches"

Are there any conditions for a branch to be able to be protected ?

**Comment by lunny** [comment]
cannot reproduce this.

**Comment by lunny** [comment]
could you show your repo settings `branches` UI?

**Comment by lklock** [comment]
![image](https://user-images.githubusercontent.com/22026690/31932929-06d4072e-b8a8-11e7-9a73-281a029c232f.png)

**Comment by lklock** [comment]
![image](https://user-images.githubusercontent.com/22026690/31933057-50f5bd8e-b8a8-11e7-91f3-1a56c40e05de.png)

**Comment by lunny** [comment]
This is not v1.2.1 I think.

**Comment by lklock** [comment]
Hi,
I've double checked it and It is version 1.2.1

![image](https://user-images.githubusercontent.com/22026690/31945247-e133a624-b8ce-11e7-9587-c9ba9cd9a820.png)

![image](https://user-images.githubusercontent.com/22026690/31945269-f0b64516-b8ce-11e7-8ac8-a153b06c582f.png)

**Comment by lklock** [comment]
83b894e321343e253006e689fb5a4d6fee048cf0fa3a169cb54c4060788133df  gitea-1.2.1-linux-amd64

**Comment by lafriks** [comment]
Are there any error either in javascript or gitea.log?

**Comment by lklock** [comment]
No, there are no error messages neither in gitea.log or in Javascript

**Comment by lklock** [comment]
Same behavior in 1.2.2

**Comment by lafriks** [comment]
@lklock can you try to reproduce that on try.gitea.io?

**Comment by lklock** [comment]
Tried to reproduce it on try.gitea.io but it is working there with the new branch protection feature
(in my repository: BatchSystem)

**Comment by lklock** [comment]
Not so sure anymore...get lots of error 500 when I play with settings there (trying to add user to whitelist, etc...)...Don't know if it is related

**Comment by lafriks** [comment]
Can you give what errors do you get in gitea.log file

**Comment by lklock** [comment]
> No, there are no error messages neither in gitea.log or in Javascript

**Comment by lafriks** [comment]
Is there anything in logs from gitea output? (Systemd/docker)?

**Comment by lklock** [comment]
Nothing useful
When I look in syslog, everything seems fine:

Nov  3 14:42:49 xtnet-01 gitea[1286]: [Macaron] 2017-11-03 14:42:49: Started POST /XTNET/cxtserver/settings/branches?action=protected_branch for 10.20.0.134
Nov  3 14:42:49 xtnet-01 gitea[1286]: [Macaron] 2017-11-03 14:42:49: Completed /XTNET/cxtserver/settings/branches?action=protected_branch 200 OK in 345.985958ms
Nov  3 14:42:49 xtnet-01 gitea[1286]: [Macaron] 2017-11-03 14:42:49: Started GET /XTNET/cxtserver/settings/branches for 10.20.0.134
Nov  3 14:42:50 xtnet-01 gitea[1286]: [Macaron] 2017-11-03 14:42:50: Completed /XTNET/cxtserver/settings/branches 200 OK in 321.402728ms

**Comment by lklock** [comment]
What I noticed, is that it works for repositories created from scratch but doesn't seem to work for repositories which have been created by a migration from SVN

**Comment by lafriks** [comment]
That's something I can try to reproduce

**Comment by lklock** [comment]
Hi,
It seems my latest comment is not valid, I have the issue also on newly created repositories

**Comment by lunny** [comment]
@lklock did you run gitea on docker?

**Comment by lklock** [comment]
No, it is not running under docker

**Comment by lklock** [comment]
Upgraded to 1.3.0
Branch protection is working fine
