### ISSUE TITLE
Expand the character count limit for the title of PR

### ISSUE THREAD

**Issue by ffbh123456** [go-gitea/gitea#27494]
### Feature Description

Seems that the max character counts of PR's title is 255, but sometimes I want to write more messages on it, can we expand the limit to a more large value, such as 1024 or 512?

**Comment by delvh** [comment]
You are misusing the PR title as PR description.

**Comment by delvh** [comment]
The PR title should be short.

**Comment by ffbh123456** [comment]
Okay, understood
