### ISSUE TITLE
Dont count on magic value "master" for the git backend

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#27497]
There still exist a lot of string values in the codebase of `"master"`

we at least should use one single const.  
but it's better to respect repo specific settings if posible

we should try to determine what the default branch of a repo or at least of the system is

_Originally posted by @6543 in https://github.com/go-gitea/gitea/pull/23894#discussion_r1349498540_

**Comment by silverwind** [comment]
1. check per-repo setting
2. fall back to global default

Indeed we should have no hardcoded `master` strings in the code anywhere.

**Comment by wxiaoguang** [comment]
I think it isn't a problem now?

**Comment by 6543** [comment]
yes it was continiously worked on so I guess it is now fixed :)
