### ISSUE TITLE
Remove non-english docs?

### ISSUE THREAD

**Issue by silverwind** [go-gitea/gitea#27499]
Non-english docs are very incomplete/outdated in this repo, and I question whether it wouldn't be better to only offer english docs, because those are the only ones guaranteed to be accurate and complete. It is a hindrance for contribution if someone needs to update a doc in a language they don't speak.

```
$ find docs -iname '*.en-us.md' | wc -l
107
$ find docs -iname '*.zh-cn.md' | wc -l
101
$ find docs -iname '*.zh-tw.md' | wc -l
32
$ find docs -iname '*.fr-fr.md' | wc -l
12
$ find docs -iname '*.de-de.md' | wc -l
4
```

Certain languages like de-de can be machine-translated very well. I think if we want multi-language docs, this would be a better option.

**Comment by lunny** [comment]
I prefer to keep both EN and CN, because both finished about 90%.

**Comment by silverwind** [comment]
I would also remove zh-cn, I doubt it's really 90% complete and who knows how many updates are missing in it. Many PRs only update en-us, so with every one of these, it will get more inaccurate.

**Comment by denyskon** [comment]
I didn't even know that we have docs in other languages until a few weeks ago. I think we should keep pages like language- specific translation information, but it would be easier for everyone if we went English- only.

**Comment by lunny** [comment]
> I would also remove zh-cn, I doubt it's really 90% complete. Who knows how many updates are missing in it. Many PRs only update en-us, so with every one of these, it will get more inaccurate.

We have implemented outdated translations reminder, if one page is outdated, there is a hint on top the page to notice user this translated page is outdated and he can help to update it.

But I also agree we should focus on better documentations in English.

**Comment by delvh** [comment]
There are exactly two viable options here:
1. Have a translation system where we can translate `md` files too (i.e. weblate), so that they are simply part of the translation process
2. Remove all non-English documentation

I prefer 1.

**Comment by denyskon** [comment]
If we could achieve 1. it would be ideal, but that also would mean a change of our main translation system.

**Comment by lunny** [comment]
> There are exactly two viable options here:
> 
>     1. Have a translation system where we can translate `md` files too (i.e. weblate), so that they are simply part of the translation process
> 
>     2. Remove all non-English documentation
> 
> 
> I prefer 1.

Even Gitea at crowdin, only less languages have been translated completely before releases. So I don't think the tool improvement can help too much.

I will chose 2 if I have to chose one between the two.

**Comment by delvh** [comment]
I mean, weblate brings this functionality by default.
As you might know, I've already argued for adopting it for quite some time…
In the end, I don't think there is a way around switching our translation system.
I'd be willing to take care of setting weblate up initially, however, I lack the resources to do so.
All I know already is that if my first use test is correct, then weblate has the basic features we need from it to keep our translation system.

**Comment by lunny** [comment]
Since the docs repository moved as a standalone repository. I think this can be closed and new issue could be created there.

**Comment by denyskon** [comment]
This can de facto be marked as completed since https://github.com/go-gitea/gitea/pull/27530. zh-CN still exists but it also is in a reasonable state.
