### ISSUE TITLE
"PR closed" event uses "check-circle" icon rather than "git-pull-request-closed" icon for closed and unmerged PRs

### ISSUE THREAD

**Issue by Andre601** [go-gitea/gitea#27495]
### Description

When you close a PR without merging it, does the overview of the web-ui (The one displaying most recent activities related to you and your repositories) use the [`check-circle` icon](https://primer.style/design/foundations/icons/check-circle-24).

This is a rather bad choice as the icon in question implies this to be good (As in merged). Instead should the [`git-pull-request-closed` icon](https://primer.style/design/foundations/icons/git-pull-request-closed-24) be used, as it is by far the best fit.

Also, merging a PR does use the right icon ([`git-merge`](https://primer.style/design/foundations/icons/git-merge-24)).

### Screenshots

Dashboard from try.gitea.io. From bottom to top there is:

- PR 1 being opened
- PR 1 being closed without merge
- PR 2 being opened
- PR 2 being closed with merge
- Resulting commit of the merge

![grafik](https://github.com/go-gitea/gitea/assets/11576465/f2a19ded-6d80-4915-8ce9-f4edf2fba236)

### Gitea Version

1.22.0+dev-125-ge3229c8e9

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

Windows

### Browser Version

Firefox 118.0.1 (64-Bit)

**Comment by Andre601** [comment]
I also just now noticed this, but it seems like that the PR title on a merge message uses a slightly darker colour than the other notifs in the dashboard (See how "Add lorem.md (merge)" is darker for the "merged pull request" message than for "created pull request")

**Comment by silverwind** [comment]
Closed PR should be `octicon-git-pull-request-closed`
