### ISSUE TITLE
Error: pq: relation "branch" does not exist whilst counting Branches without existing repository

### ISSUE THREAD

**Issue by frnmst** [go-gitea/gitea#27508]
### Description

After migrating from 1.20.4 to 1.20.5, I get this from Gitea's doctor which I always run after upgrading:

```
[9] Check consistency of database
 - [E] Error: pq: relation "branch" does not exist whilst counting Branches without existing repository
ERROR
```

The command I use is this one. It's a long one because GIT LFS checks take too long so I excluded them.

```shell
HOME=... GITEA_WORK_DIR=... /usr/bin/gitea -c ... doctor --run paths --run storage-archives \
--run storage-attachments --run storage-avatars --run storage-lfs --run storage-packages \
--run storages --run check-db-version --run check-db-consistency --run check-user-type \
--run authorized-keys --run script-type --run hooks --run recalculate-stars-number \
--run check-old-archives --run enable-push-options --run fix-broken-repo-units \
--run recalculate-merge-bases --run synchronize-repo-heads --run check-git-daemon-export-ok \
--run check-commit-graphs --run check-user-email --run check-user-names --fix
```

### Gitea Version

 1.20.5

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

2.39.2

### Operating System

Debian 11

### How are you running Gitea?

Debian package, Systemd

```
gitea/gitea,now 1.20.5+1 amd64 [installed]
  A painless self-hosted Git service.
```

### Database

PostgreSQL

**Comment by lng2020** [comment]
Have you fixed this problem? That's a check for the orphan branch(a branch with no repo). But seems like your db has no `branch` table. That's pretty weird🤔
