### ISSUE TITLE
Metrics endpoint for prometheus

### ISSUE THREAD

**Issue by jpds** [go-gitea/gitea#2751]
- Gitea version (or commit ref): 1.2.0+1-g670562a
- Git version: 1.2.0+1-g670562a
- Operating system: Docker image
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant

## Description

I would like gitea to expose a `/metrics` endpoint (can be on a different port from main Gitea) which could be used in conjunction with Prometheus to get information about:

* Page load latencies
* Number of git repos in gitea
* Time taken to pull a mirror repository down
* Number of users in Gitea
* Number of users logged into Gitea
* Number of failed log in attempts
* Any other metric you folks can think of :)

Once this information is in Prometheus, I can then use Grafana to create a dashboard for Gitea metrics.

**Comment by cez81** [comment]
Some work has been done previously in https://github.com/go-gitea/gitea/pull/678.

**Comment by techknowlogick** [comment]
Closed as linked PR has been merged.
