### ISSUE TITLE
Failed to health check repository (xxxxxxxxxxxx): context deadline exceeded

### ISSUE THREAD

**Issue by mei-rune** [go-gitea/gitea#27559]
### Description

Failed to health check repository (xxxxxxxxxxxx): context deadline exceeded

![1696917488872](https://github.com/go-gitea/gitea/assets/1052632/f723d96f-f2bd-4571-adad-0c90435eb7f0)

A large number of errors, possibly thousands, may be due to the timeout being too small. Please add a configuration to address this issue.
大量的错误，有几千条， 可能是这个 timeout 太小了， 如果的话请加一个配置吧

![1696917583951](https://github.com/go-gitea/gitea/assets/1052632/e282a35b-abfb-4601-8e90-51c6a3d95002)

### Gitea Version

1.21.0+rc0-44-g7ea7f2b37 built with GNU Make 4.3, go1.21.1 : bindata, sqlite, sqlite_unlock_notify

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

2.30.0, Wire Protocol Version 2 Enabled

### Operating System

windows 2016

### How are you running Gitea?

run as  window service.

### Database

SQLite

**Comment by KN4CK3R** [comment]
You can already configure that timeout. What you are see in the code is just the default value.

```ini
;[cron.repo_health_check]
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;SCHEDULE = @midnight
;; Enable running Repository health check task periodically.
;ENABLED = true
;; Run Repository health check task when Gitea starts.
;RUN_AT_START = false
;; Notice if not success
;NOTICE_ON_SUCCESS = false
;TIMEOUT = 60s
```
