### ISSUE TITLE
The `Open` button in the PR list lacks some checks

### ISSUE THREAD

**Issue by nanguanlin6** [go-gitea/gitea#27553]
### Description

![ksnip_20231010-113026](https://github.com/go-gitea/gitea/assets/70063547/30b10fbb-9cae-4453-bb72-20dfd525274a)
Currently, the only check of this button is 
https://github.com/go-gitea/gitea/blob/3c131307ac44247e65516135c626e437f089ca9f/routers/web/repo/issue.go#L2882-L2884
This will cause some problems such as when the head branch is deleted or the fork repo changes the visibility.
<details>

![ksnip_20231008-161624](https://github.com/go-gitea/gitea/assets/70063547/78eade43-ddb6-4283-a1dd-b725a4a1bf51)

</details>
But I'm not really sure about the whole check condition. Are there any other cases that the PR should not be reopened?

### Gitea Version

latest codebase

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

built from source code

### Database

None

**Comment by yp05327** [comment]
same to #26106?

**Comment by lunny** [comment]
This issue is for the pull request list page but yours is for pull request detail page.

**Comment by yp05327** [comment]
I think this has been fixed by #32081
