### ISSUE TITLE
Migrating the repo as a mirror from gitea.com failed

### ISSUE THREAD

**Issue by nanguanlin6** [go-gitea/gitea#27561]
### Description

While migrating as a mirror from www.gitea.com to try.gitea.io, the website returns no such user.
![ksnip_20231010-183128](https://github.com/go-gitea/gitea/assets/70063547/173db45f-7832-4183-9a0f-44c8a9211e62)
But the repo and the user both exist.
![ksnip_20231010-183212](https://github.com/go-gitea/gitea/assets/70063547/ed02691f-332f-4087-8c34-609e9f321b81)

### Gitea Version

1.22.0+dev-153-g3c131307a

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

it's on try.gitea.io

### Database

None

**Comment by lng2020** [comment]
Migrating from www.gitea.com to localhost works just fine.
