### ISSUE TITLE
The repo items in `explore` page have duplicate icon

### ISSUE THREAD

**Issue by nanguanlin6** [go-gitea/gitea#27596]
### Description

As title.
The problem is 
https://github.com/go-gitea/gitea/blob/c37f95fc56fa3fc8f51610af6915ac39839d7d19/templates/explore/repo_list.tmpl#L13-L40 
and
https://github.com/go-gitea/gitea/blob/c37f95fc56fa3fc8f51610af6915ac39839d7d19/templates/repo/icon.tmpl#L1-L14
have duplicate (but not same) check.

### Screenshots

<img width="319" alt="image" src="https://github.com/go-gitea/gitea/assets/70063547/0c78eadf-6e00-4ebf-9d82-886b78124da9">

### Gitea Version

latest codebase

### Can you reproduce the bug on the Gitea demo site?

Yes

### Browser Version

none

**Comment by hiifong** [comment]
The same thing happens with other pages.
![image](https://github.com/go-gitea/gitea/assets/89133723/3e2352ef-2cdb-420a-8455-d162c229b5d5)
![image](https://github.com/go-gitea/gitea/assets/89133723/ebc8b7d9-0732-4e2c-a8b8-573523298d53)
