### ISSUE TITLE
Visual highlight glitch

### ISSUE THREAD

**Issue by KN4CK3R** [go-gitea/gitea#27604]
### Description

On the PR file page the file highlight border is not hidden.

### Screenshots

![grafik](https://github.com/go-gitea/gitea/assets/1666336/f16d7387-154e-43a2-a3fd-08c85e4aca8c)

![grafik](https://github.com/go-gitea/gitea/assets/1666336/cc732b81-8ed1-43b3-afb5-1d46d1a89464)
(on the right side of the button)

### Browser Version

Firefox 118

**Comment by silverwind** [comment]
You mean hide behind the sticky header? I imagine we could enlarge it to 100% width.

**Comment by KN4CK3R** [comment]
Yes, if you scroll down the border scrolls into the header. The top border is hidden.
