### ISSUE TITLE
Removing image from doker registry

### ISSUE THREAD

**Issue by planlos-xyz** [go-gitea/gitea#27603]
### Description

Hi.

I want to use gitea as docker registry, too. - But how i can delete pushed images again.

Thanks..

### Gitea Version

1.20.5

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

debian

### How are you running Gitea?

In a docker countainer

### Database

None

**Comment by lng2020** [comment]
![HI$Q@A(6`0E`{JHC(E~14~A](https://github.com/go-gitea/gitea/assets/70063547/9e8fce41-9bca-4c97-b828-80522815be38)

**Comment by nerdshit-to** [comment]
Hey.
Thank you.

Nice greetings <3 <3
