### ISSUE TITLE
An issue when creating a project issue

### ISSUE THREAD

**Issue by achristov** [go-gitea/gitea#27607]
### Description

![image](https://github.com/go-gitea/gitea/assets/3130592/1c0b87d9-a212-41d5-9b30-a38e66b8f470)

### Gitea Version

1.21.0+rc1-22-g63a321b83

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

Windows 11

### How are you running Gitea?

as a service

### Database

PostgreSQL

**Comment by achristov** [comment]
I see "git version"  above but I don't think git has anything to do with that. anyway, my git version is: git version 2.42.0.windows.2

**Comment by lng2020** [comment]
close by #27612
