### ISSUE TITLE
Math blocks can't be directly preceded or followed by alphanumeric character

### ISSUE THREAD

**Issue by nschloe** [go-gitea/gitea#27605]
MWE:

```markdown
a$x$ -$x$ 1$x$
```

Screenshot:
  
![screenshot_2023-10-13-160253](https://github.com/go-gitea/gitea/assets/181628/b771d375-3df8-4da9-a1d1-b6ecd3a4dadd)

```markdown
$a$1

$a$-

$a$x
```
  
![screenshot_2023-10-13-160658](https://github.com/go-gitea/gitea/assets/181628/f316fa37-4fb5-41ae-b89c-714acdad1487)

This also concerns the `\(...\)` and `\[...\]` syntax.

**Comment by jmlt2002** [comment]
I managed to reproduce this bug locally, could i be assigned to this issue?
