### ISSUE TITLE
Make language label to follow mouse on language stats bar

### ISSUE THREAD

**Issue by ramiuslr** [go-gitea/gitea#27600]
### Feature Description

Just a little improvement idea I had about the UI.

Is it possible to make the language label follow the mouse on the language stats bar ? So that it does not hide informations about branches, commits, etc.

See screenshots below:

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/90651639/e8d5bc20-ba59-4e5e-9151-3c148b126e48)

![image](https://github.com/go-gitea/gitea/assets/90651639/6598d70e-2a0a-4b5f-9837-144aae3d3ab2)

**Comment by silverwind** [comment]
Can likely be achieved with the `followCursor` option on tippy:

https://atomiks.github.io/tippyjs/v6/all-props/#followcursor
