### ISSUE TITLE
Error in the HTTP2 framing layer

### ISSUE THREAD

**Issue by somera** [go-gitea/gitea#27611]
### Description

Today I found this

```
==> servicesmirror-trace.log <==
2023/10/13 21:23:16 ...irror/mirror_pull.go:290:runSync() [E] SyncMirrors [repo: <Repository 17976:solidiquis/erdtree>]: failed to update mirror repository:
Stdout:
Stderr: fatal: unable to access 'https://github.com/solidiquis/erdtree.git/': Error in the HTTP2 framing layer

Err: exit status 128
        /source/services/mirror/mirror_pull.go:290 (0x246377e)
        /source/services/mirror/mirror_pull.go:432 (0x2466187)
        /source/services/mirror/mirror.go:28 (0x245e04e)
        /source/services/mirror/mirror.go:125 (0x245ea24)
        /source/modules/queue/workerqueue.go:246 (0x1c9ecbc)
        /source/modules/queue/workergroup.go:98 (0x1ca14ad)
        /source/modules/queue/workergroup.go:162 (0x1c9e6c8)
        /usr/local/go/src/runtime/asm_amd64.s:1598 (0x472700)
                goexit: BYTE    $0x90   // NOP
```

22 times in my gitea.log.

Any ide what can be the reason for this?

### Gitea Version

1.20.5

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

2.42.0

### Operating System

Ubuntu 20.04.6

### How are you running Gitea?

gitea-1.20.5-linux-amd64

### Database

PostgreSQL

**Comment by KN4CK3R** [comment]
I don't think this is a Gitea problem. Do you have a proxy or something infront of Gitea which could mess up the connection?

**Comment by somera** [comment]
There is no prxy. I see this since two days. But not for every mirrorr update. And this is random. And I don't have any connections issues. Or this is an gitHub problem. I try to analyze it.

**Comment by somera** [comment]
I can't reproduce it or GitHub fixed this.
