### ISSUE TITLE
math: eqnarray missing

### ISSUE THREAD

**Issue by nschloe** [go-gitea/gitea#27614]
### Feature Description

MWE:
```
$$
\begin{eqnarray}
a
\end{eqnarray}
$$
```

Screenshot:

![screenshot_2023-10-14-125656](https://github.com/go-gitea/gitea/assets/181628/e4181f8e-c668-442b-a2af-71f4c8f4d6d8)

**Comment by eeyrjmr** [comment]
Gitea uses katex as the backend renderer and latex doesn't support equarray.
It supports align. https://katex.org/docs/supported

Also it is not advised to use equarray
http://www.tug.org/pracjourn/2006-4/madsen/
http://texblog.net/latex-archive/maths/eqnarray-align-environment/
http://www.math.uiuc.edu/~hildebr/tex/displays.html

**Comment by nschloe** [comment]
Your right, this issue depends on https://github.com/KaTeX/KaTeX/issues/3643.

**Comment by nschloe** [comment]
Let's close this in favor of the KaTeX issue.
