### ISSUE TITLE
math: use in divs

### ISSUE THREAD

**Issue by nschloe** [go-gitea/gitea#27619]
### Feature Description

Gitea apparently disallows Markdown syntax without HTML tags. This

```markdown
<div align="center">
*a*
</div>
```

renders as

![screenshot_2023-10-14-144139](https://github.com/go-gitea/gitea/assets/181628/6198e4c1-ab06-4fc2-af00-7200f4b19bb6)

While it's easy to work around that with bold text -- simply use `<b>...</b>`, I haven't found a way to get math to work in div-aligned blocks.

```markdown
<div align="center">
Lorem \(a\) ipsum
</div>
```

![screenshot_2023-10-14-144242](https://github.com/go-gitea/gitea/assets/181628/5abc22ab-e4f1-4645-897f-fa3de25b36bd)

**Comment by KroMignon** [comment]
Mixing HTML tags and Markdown is always complicated, because the markdown interpreter has to find out where HTML tags ends and where the Markdown sequence starts.

Did you try to add empty lines between Tags and markdown text?
```
<div align="center">

Lorem \(a\) ipsum

</div>
```

**Comment by nschloe** [comment]
This does the trick, thanks!
