### ISSUE TITLE
math: `\$` in inline math

### ISSUE THREAD

**Issue by nschloe** [go-gitea/gitea#27618]
### Description

MWE:

```markdown
$x = \$$
```

Screenshot:

![screenshot_2023-10-13-160513](https://github.com/go-gitea/gitea/assets/181628/492ef1db-e205-482d-ac7f-43a0b380e460)

### Gitea Version

1.22.0+dev-181-g76a85a4ce

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

https://try.gitea.io/

### Database

None

**Comment by nschloe** [comment]
Note that this is not a KaTeX issue; it renders `x = \$`. The `type/report-upstream` label is probably misplaced.

**Comment by nschloe** [comment]
Still an issue on 1.23.0+dev-753-gc5422fae9a (Dec 2024)

**Comment by wxiaoguang** [comment]
I am refactoring the render module, I think it will be fixed in 1.23, soon

**Comment by wxiaoguang** [comment]
1.23 nightly is ready and I think it should have been fixed, feel free to take a try

![image](https://github.com/user-attachments/assets/998db8f4-983f-490c-9a4a-25dd609d0b8f)

**Comment by nschloe** [comment]
Confirmed fixed.
