### ISSUE TITLE
Command line git add not shown in web interface

### ISSUE THREAD

**Issue by freebrowser1** [go-gitea/gitea#27638]
### Description

I ran the example script with Readme.md which was shown in the user interface/
Then I added a file:
```
myuserpc:~/projecten/@Klanten % git add totaalplanning.php 
myuserpc:~/projecten/@Klanten % git commit -m test        
[main 5df94bf] test
 1 file changed, 935 insertions(+)
 create mode 100644 totaalplanning.php
myuserpc:~/projecten/@Klanten % 
```
But after refreshing the web interface, I cannot find the file 'totaalplanning.php'.

The answer on 'Can you reproduce the bug on the Gitea demo site?' is No because it requires another login, the Github login does not work, so I cannot test it.

### Screenshots

![Screenshot 2023-10-16 at 10 23 54](https://github.com/go-gitea/gitea/assets/26625141/2d3ead5f-913c-4003-ab5e-67121f57b14d)

### Gitea Version

Gitea version 1.20.5 built with GNU Make 4.2.1, go1.20.8 : bindata, sqlite, sqlite_unlock_notify

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

macOS Sonoma

### Browser Version

Firefox 118

**Comment by delvh** [comment]
You are missing the `git push`.
You have only made the changes on your local computer, the server doesn't know about them.

**Comment by freebrowser1** [comment]
Thanks, I did not notice that.
So ticket can be closed.
