### ISSUE TITLE
Same issue shows twice in project's column

### ISSUE THREAD

**Issue by stuzer05** [go-gitea/gitea#27639]
### Description

I added spent time and then closed an issue

### Gitea Version

trunk

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/23124682/e91d0be5-7611-4438-a0b3-49c9ee9c0178)

### Git Version

6c501b14

### How are you running Gitea?

binary

### Database

None

**Comment by edlerd** [comment]
I would like to work on this, can you assign me?

**Comment by stuzer05** [comment]
> I would like to work on this, can you assign me?

You can make a pr, I don't have rights to assign anyone

**Comment by edlerd** [comment]
> ### Can you reproduce the bug on the Gitea demo site?
> Yes

@stuzer05 can you please add detailed steps how to reproduce the issue on https://try.gitea.io/ ?
I am having trouble finding a way to reproduce it.

**Comment by stuzer05** [comment]
I honestly cannot reproduce it myself, it was just random. The problem was in the `project_issue` table thewe were 2 identical records. Maybe, if there was a constraint for unique column values there wouldn't be an issue

**Comment by techknowlogick** [comment]
@stuzer05 which database are you using?

**Comment by lunny** [comment]
I guess it's a database join or group problem.

**Comment by stuzer05** [comment]
> @stuzer05 which database are you using?

mariadb

**Comment by edlerd** [comment]
I think this is a bug in the `LoadIssuesFromBoard` function, will submit a PR with a suggestion to fix it.

**Comment by stuzer05** [comment]
You can verify your fix by duplicating the row in `project_issue` table like this
![image](https://github.com/go-gitea/gitea/assets/23124682/42c4d05c-46f2-4cd0-aeee-5f2c5859778b)

Also, I would add a unique constraint for (issue_id, project_id) cols so duplicate rows would never happen in the first place

**Comment by edlerd** [comment]
> You can verify your fix by duplicating the row in `project_issue` table like this

Is this from your gitea deployment? 
Are you using any plugins?

The only place that adds to this table that I found is in [project_issues.go](https://github.com/go-gitea/gitea/blob/main/models/issues/issue_project.go#L148) where any previous entries to the table are removed before adding a new entry.

**Comment by lng2020** [comment]
Not sure if it's connected with https://github.com/go-gitea/gitea/pull/27746
But it seems more like a front-end issue, like sending the request twice. IIRC, there is an issue about the project board frontend concurrency issue too.
