### ISSUE TITLE
Is there any way to do some batch operates?

### ISSUE THREAD

**Issue by ltbyun** [go-gitea/gitea#27636]
### Feature Description

I need to migrate from git in microsoft's tfs to gitea.
I need to create hundreds of users, and migrate thousands of repositories.
I can not find any way to do this in batch, the only way is to do one by one, it's a huge task.
why can not import users from excel or other file?
and why can not migrate thousands of repositories with a text of repositories's urls?

**Comment by delvh** [comment]
You can write an API script.

**Comment by bthulu** [comment]
@delvh yes, it works.
but after i imported 183 repos to admin user, i find it uses more the 2 seconds to open the user's home page.
i opened mysql log_output, and reexecute query sqls, but find none uses more then 10ms, so it maybe occurs in the data resolve logic.
![image](https://github.com/go-gitea/gitea/assets/38602293/32b6f0d7-3908-4ba5-9d0a-af3eedba34fd)
![image](https://github.com/go-gitea/gitea/assets/38602293/7f8e5562-4473-4185-80c0-d62b5f467a43)

**Comment by lng2020** [comment]
Gitea log shows every step's executive time. If you think it's a bug of Gitea's code logic, feel free to paste log and open another issue.
