### ISSUE TITLE
gitea checks email addresses that are revoked in gpg key

### ISSUE THREAD

**Issue by stikonas** [go-gitea/gitea#2764]
## Description

I tried adding my GPG public key to gitea. And it started asking me to register my old emails with gitea.
Those emails are revoked in my gpg key, so gitea shoudn't check them.

**Comment by lafriks** [comment]
What version gitea are you using? Gitea should ask only one email in GPG key to be verified to be able to add it to account

**Comment by stikonas** [comment]
The latest one, 1.2.1

**Comment by lafriks** [comment]
This will be fixed in 1.3.0 with #2266
