### ISSUE TITLE
Gitea and cockroachdb doesn't work.

### ISSUE THREAD

**Issue by delandtj** [go-gitea/gitea#27648]
### Description

Trying to run gitea against cockroachdb gives :

```
The database settings are invalid: migrate: sync: pq: multiple primary keys for table "version" are not allowed

```
in the `Initial Configuration` of gitea.

the only relevant log entry seems to be 
```
2023/10/15 10:47:46 ...s/install/install.go:229:checkDatabase() [I] Gitea will be installed in a database with: hasPostInstallationUser=false, dbMigrationVersion=260
```

### Gitea Version

Version: 1.20.4 

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/5995555/c5b72418-8e6c-41b3-ab2b-00205f9c94a9)

### Operating System

ubuntu 22.04 with docker-compose

### How are you running Gitea?

with docker-compose, starting cockroach first, then gitea (default configurations)

### Database

PostgreSQL

**Comment by techknowlogick** [comment]
merging into https://github.com/go-gitea/gitea/issues/3765
