### ISSUE TITLE
make clean downloads all dependencies

### ISSUE THREAD

**Issue by strk** [go-gitea/gitea#27653]
### Description

Running `make clean` downloads all dependencies. I don't think it should hit the net.

### Gitea Version

current main branch as of 6c501b149809a7015e58d9627e84bfd593702f95

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

not running it

### Database

None

**Comment by BaiZe1998** [comment]
can u replicate this and show us the logs

**Comment by lng2020** [comment]
That seems to be an upstream issue about `go clean`. Because here we simply use `go clean -i ./...`
some related discussion(https://github.com/golang/go/issues/32977)

**Comment by silverwind** [comment]
There is no clear definition on what a `clean` shall do, but we do have `clean` and `clean-all`, so could maybe move the network stuff to `clean-all`.

**Comment by delvh** [comment]
Why should `clean` do network stuff?
That's not its task.

**Comment by silverwind** [comment]
Do we actually need this `go clean`?

> Clean removes object files from package source directories.
The go command builds most objects in a temporary directory,
so go clean is mainly concerned with object files left by other
tools or by manual invocations of go build.

Maybe it's good for `go generate` bindata files? But I don't think there is anything else temporary inside the project source dirs and those bindata files could be deleted via `rm` as well.

**Comment by techknowlogick** [comment]
Thanks @silverwind, I've created a PR based on your research
