### ISSUE TITLE
postgres pull bug

### ISSUE THREAD

**Issue by 121132839** [go-gitea/gitea#27656]
### Description

2023/10/17 13:54:44 ...ers/web/repo/pull.go:1297:CompareAndPullRequestPost() [E]
 NewPullRequest: generate pull request index failed: pq: 语法错误 在 "ON" 或附近
的

### Gitea Version

1.20.5

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

cmd

### Database

postgres 9.2

**Comment by BaiZe1998** [comment]
what u want to do ? perhaps you could show your steps, or a more detailed log of your operations

**Comment by 121132839** [comment]
![image](https://github.com/go-gitea/gitea/assets/32965581/5057648b-64f8-4875-9e7c-83dacb208c8b)

**Comment by 121132839** [comment]
Happens when creating a pull request, using postgre sql.

**Comment by 121132839** [comment]
windows server

**Comment by lng2020** [comment]
> Notice that the ON CONFLICT clause is only available from PostgreSQL 9.5. If you are using an earlier version, you will need a workaround to have the upsert feature.

Probably it's about the Postgre version.

**Comment by 121132839** [comment]
> > Notice that the ON CONFLICT clause is only available from PostgreSQL 9.5. If you are using an earlier version, you will need a workaround to have the upsert feature.
> 
> Probably it's about the Postgre version.

thank you!
