### ISSUE TITLE
Docker/rootless: "ssh-keygen": executable file not found in $PATH

### ISSUE THREAD

**Issue by williamdes** [go-gitea/gitea#27658]
### Description

This is the same request as #23363
Looks like #23363 was not fixed or has some other bug.

I disabled the internal SSH server.

But this time, no fancy error, just an error 500

```
2023/10/16 12:18:55 ...eb/routing/logger.go:102:func1() [I] router: completed POST /api/internal/ssh/authorized_keys for 127.0.0.1:0, 500 Internal Server Error in 1.1ms @ private/key.go:50(private.AuthorizedPublicKeyByContent)

2023/10/16 12:18:55 ...eb/routing/logger.go:102:func1() [I] router: completed POST /api/internal/ssh/authorized_keys for 127.0.0.1:0, 500 Internal Server Error in 0.6ms @ private/key.go:50(private.AuthorizedPublicKeyByContent)
```

I had to run: `docker exec -u root -it gitea apk add openssh-client` to fix the error

### Gitea Version

1.21

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

Debian 12

### How are you running Gitea?

Docker rootless

### Database

MySQL/MariaDB

**Comment by wxiaoguang** [comment]
rootless must use builtin SSH server.

**Comment by williamdes** [comment]
> rootless must use builtin SSH server.

That does not make sense to require a ssh server to parse the keys

**Comment by wxiaoguang** [comment]
Yup, rootless image doesn't use "a ssh server to parse the keys".

But you said "I disabled the internal SSH server."

**Comment by wxiaoguang** [comment]
And one more thing, you log

```
2023/10/16 12:18:55 ...eb/routing/logger.go:102:func1() [I] router: completed POST /api/internal/ssh/authorized_keys for 127.0.0.1:0, 500 Internal Server Error in 1.1ms @ private/key.go:50(private.AuthorizedPublicKeyByContent)
```

doesn't seem related to the "ssh-keygen" problem. I have read the code again, `private.AuthorizedPublicKeyByContent` only does some database queries, no "ssh-keygen" call.

----


So, if there is still a problem, please provide more clues, and provide a reproducible example with detailed steps.

**Comment by williamdes** [comment]
Can you re open, I will have one more look to reproduce this bug

**Comment by wxiaoguang** [comment]
Inactive for more than 2 weeks, feel free to reopen "if there is still a problem, please provide more clues, and provide a reproducible example with detailed steps"
