### ISSUE TITLE
500 page appear while trying to view repository items

### ISSUE THREAD

**Issue by ade-adeoti** [go-gitea/gitea#27679]
### Description

I have Gitea install on debian vm, I have created an account and login. I created repository and push project item into it. I close the vm and shut down the host system. When I restart the host and the vm, and trying to check my repository, I saw 500 page
![Screenshot from 2023-10-18 08-57-32](https://github.com/go-gitea/gitea/assets/146231241/47e0668d-9014-46bb-ae8c-73a2ff8e6811)
 

### Gitea Version

1.20.5

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

debian

### How are you running Gitea?

I run the Gitea in K3S clauter

### Database

PostgreSQL

**Comment by lng2020** [comment]
Can u show us some logs?

**Comment by aceArt-GmbH** [comment]
Maybe this is the same issue, but after upgrading from 1.20.5 to 1.21.1 the repo page throws 500.

```
2023/11/29 09:11:10 .../context_response.go:68:HTML() [D] Template: status/500
2023/11/29 09:11:10 ...eb/routing/logger.go:102:func1() [I] router: completed GET /myOrg/my-repo.de for 192.168.2.2:56028, 500 Internal Server Error in 63.6ms @ repo/view.go:725(repo.Home)
```

**Comment by wxiaoguang** [comment]
No more feedback, I think this issue can be closed, feel free to reopen if there are more clues.
