### ISSUE TITLE
I'd like to help improve the web interface.

### ISSUE THREAD

**Issue by bencurio** [go-gitea/gitea#27677]
### Feature Description

Hello,

I have submitted this question primarily as a feature request, but I would like to make minor modifications and fixes to the HTML code of the web interface when my free time allows.

**Here's what I'm initially thinking:**

1. I would like to make class naming better to help template creators write more customized CSS. (e.g.: `<body class="[...] page--repository page--repository--issues">`)
2. I want to display data that's available but not currently shown on the web interface. For example, the project listing lacks the display of pull requests and issue counts, even though this data is available (see: https://github.com/go-gitea/gitea/commit/403e54d2311386c58d0e406f39396abf1917520c).

**Future ideas include:**

- Redesigning existing forms for better organization and readability.
- Potential UI/UX enhancements _(e.g. fluid design on actions tab)_
- ...

My question is whether there is interest in these changes and if I should proceed with creating pull requests for both minor and major changes.

I appreciate your feedback in advance.

Thank you.

### Screenshots

Here's a little examples. I have made some modifications on my local instance that I would be happy to share back. 

## Added borders

![image](https://github.com/go-gitea/gitea/assets/7604637/ae39a924-ef2a-46d9-933a-79955d1ab1b0)

## Added: pull requests and issue counts + Counters moved to bottom

![image](https://github.com/go-gitea/gitea/assets/7604637/54fb4781-5e15-4858-96c7-26500c4d34ca)

## Fluid header items + Bordered list view

![image](https://github.com/go-gitea/gitea/assets/7604637/2048300b-5a1f-49be-8450-77a0e25b081d)

## Bordered issue view

![image](https://github.com/go-gitea/gitea/assets/7604637/c3e81c79-f14b-4300-9ea7-7480ebccc1ea)

## Fluid actions view

![image](https://github.com/go-gitea/gitea/assets/7604637/01a40932-f21e-4d90-a1cb-9c044cd65637)

## Replaced fonts in console, making green tick grey

![image](https://github.com/go-gitea/gitea/assets/7604637/6fbeaa54-8386-41f0-b71f-868c91889a9c)

## Removed borders from right pane, improved comment submit form

![image](https://github.com/go-gitea/gitea/assets/7604637/6a313fc2-e7e1-4cd2-9cc8-43cd035ad3c6)

**Comment by bencurio** [comment]
The screenshot is just an example, as I quickly put it together for my own Forgejo instance using only CSS _(and little HTML structure changes in template)_. At this point, I had the idea of helping the project itself. So my plan is to start the implementation from scratch based on the Gitea template.

My question is, would you like to receive such PRs from me? For transparency, I would split them by topic and not send them in bulk.

**Comment by jolheiser** [comment]
I think direct PRs for UI details would be welcome, like the borders and similar. 
Things like class name changes, form reworks, etc should probably start as an issue to gather discussion.

**Comment by bencurio** [comment]
Of course! I want to make the classes more talkative, so I'm thinking of expanding them. When I had to create theme for Drupal site, I really like talkative CSS classes.

Here is a good example from Drupal docs:

```html
<div class="progress">
  <!-- 
    .label is a separate component, used for form labels, but can be applied
    to non-label tags, and can be extended with a modifier class.
    -->
  <label class="label">Installing Node Module</label>
  
  <!-- progress element (sub-object) -->
  <div class="progress__track">
    <!-- 
      Component sub-objects don’t need more than the component name
      as a prefix; progress__track__bar is verbose and unnecessary.
       
      Inline styles shown here would be applied by JavaScript using 
      the independent 'js-' class.
      -->
    <div class="progress__bar js-progress-percent" style="width: 63%"></div>
  </div>
  <div class="progress__description">
    <!--
      .layout-pull and .layout-push are LTR/RTL-agnostic utility classes for floating; 
      these should not appear in core default markup since they are not
      design-independent.
      -->
    <div class="layout-pull">Installed 15 of 24 modules</div>
    <strong class="layout-push">63%</strong>
  </div>
  
  <!-- 
    Note that appearance is not tied to the tag; the appearance of the 
    <button> element would be reset in the base layer and styled as 
    needed by applying classes.
      
    Since this element uses an icon, it could be refactored to use a generic 
    icon container component. 
    -->
  <button class="progress__cancel" href="#" title="cancel">cancel</button>
</div>


<!-- 
  Modifier classes create component variants; modifier classes must 
  be used with the original class in the markup
  -->
<div class="progress progress--small">
  <label class="label label--small">Uploading syndey-opera-house-sunset.jpg</label>
  <div class="progress__track">
    <div class="progress__bar js-progress-percent" style="width: 29%"></div>
  </div>
  <div class="progress__description">
    <div class="layout-pull">Uploaded 221 of 762KB</div>
    <strong class="layout-push">29%</strong>
  </div>
  <a class="progress__cancel" href="#" title="cancel"><span class="visually-hidden">cancel</span></a>
</div>
```

It may be overkill to add so many CSS classes, but as a starting point I think it might be good.

Full docs here: https://www.drupal.org/docs/develop/standards/css/css-architecture-for-drupal-9

**Comment by silverwind** [comment]
1. We prefer short descriptive lowercase class names with words separated by `-`.
2. We are (still) using Fomantic UI framework so in some cases need to use classes they provide.
3. New CSS uses mostly atomic selectors, no classes needed at all. See `helpers.css`.

Plan to introduce either tailwind.css or unocss soon and replace most of `helpers.css` with it, and I prefer if that it will become the dominant styling sytems. More complex cases can always introduce classes on their own, in the scheme above.

The changes look good, but please raise one PR at a time for them.

**Comment by bencurio** [comment]
Okydoky, I'll take a look at the Fomantic UI and Tailwind/UnoCSS framework specifications. Btw. Tailwind/UnoCSS is looks great.

I was actually thinking that we should create a PWA,  but I discarded the idea for now due to the API. Or shall we dare to dream big?

**Comment by bencurio** [comment]
I understand, there are many dependencies that can break, and a lot of adjustments needed in the API. However, if the API is suitable, we could run the Gitea instance in a headless mode and build any app on that (including PWA). Users can then decide what they want to use.  Another hybrid solution could be that certain elements use, for example, Vue, such as the file browser. I know this is a lot of work, so for now, it's just brainstorming. Previously, I built a PWA interface based on a very popular voice-based application, and it's not as terrible as it might seem at first.

**Comment by delvh** [comment]
> Another hybrid solution could be that certain elements use, for example, Vue, such as the file browser

Yes, that's what we are already doing and what I deem `necessary`.
I agree, in some parts we **should** rely more on JS than our current templates hack, but overall too much stuff breaks when you solely rely on JS.

**Comment by bencurio** [comment]
Alright, I'll be working with the current codebase and making minor improvements to enhance the UX. Should we keep this issuet as a discussion or use another channel? I don't want to SPAM anyone unnecessarily.

**Comment by lunny** [comment]
PWA has been implemented in Gitea but removed from 1.17(?). It won't help but make things complicated.

**Comment by ell1e** [comment]
For what it's worth, JavaScript can also be a big performance issue on a phone, both for CPU and network download size reasons. GitLab is almost unusable on my phone due to this since it's the most JavaScript heavy of all the project hosters. So I personally hope Gitea will stay light on JavaScript as it is.

**Comment by bencurio** [comment]
I understand the arguments against PWA, if it is badly structured and built it quickly becomes an unmanageable monster. However, if the application is structured properly and the coding is implemented using programming methods such as clean code or S.O.L.I.D., and if sufficient tests are written for it, then you can reap the benefits. However, my experience shows that you need to minimize external dependencies and unfortunately this is difficult to do in the JS world. The biggest problem is that even though it is considered a frontend (and technically it is), in reality it is code like in backend and you need to apply the right techniques to get usable results (e.g. TypeScript; Strict typing; etc...). But I don't think I need to talk about that here.

**Comment by bencurio** [comment]
Regarding performance, opinions are actually divided. If it's poorly written, then it really can be slow. I don't aim to convince anyone, but let's recognize that most applications using PWA (yes, and there are slow ones, very slow ones). I can tell you about interfaces that don't use JS and are still slow. The problem is usually in the implementation.

**Comment by bencurio** [comment]
I reassure everyone that I'm not going to open a big PWA PR, I'm just throwing it up as an idea, why not? My goal is minor UX improvements. 😇

**Comment by ell1e** [comment]
All I can say is that I haven't encountered a single JS-heavy web page that wasn't slow to load and sluggish to use on my phone.

**Comment by bencurio** [comment]
I mostly agree, the sad truth is that nobody pays attention to memory usage and optimization, and GPU usage. This all drains battery and results in a slow interface.

**Comment by silverwind** [comment]
PWA is a convoluted term. I prefer to think in what part does the HTML rendering. Currently most of it is done in Go templates and I think overall this will stay.

We can extract parts of the UI into JS rendering like Vue or (my preference still) or React, but those parts of the UI like the actions view all feel slow because JS takes like 50s until it renders. A solution like Next.js with render on server with JS hydration would be ideal, but I am not sure anything like that exists in the GO ecosyste.

**Comment by silverwind** [comment]
Think this issue has ran its course.
