### ISSUE TITLE
Repository specific pattern for branch names

### ISSUE THREAD

**Issue by sebastian-sauer** [go-gitea/gitea#27683]
### Feature Description

In some environments a branch name pattern is used (like feature/* for all feature branches and bugfix/* for all bugfix branches).
In order to ensure everybody uses the pattern it'd be great to have a setting to configure a branch name regex that must match when pushing a new branch. 

If the branch name doesn't match the regex, the push will be rejected.

This could be a configuration option per repository, with .* as default value.

I'd propose to add this to the Repo -> Settings -> Branches page - a mockup for this:

![image](https://github.com/go-gitea/gitea/assets/1135157/590e60cb-f22b-429d-9bd9-c1343aef4de5)

**Comment by sebastian-sauer** [comment]
If the proposal is accepted i'd be happy to create a PR for this.

**Comment by lunny** [comment]
Please have more discussion before sending PRs.

Maybe rules priority could resolve your problem. Let's say:

1 feature/** can be pushed by some people.
2 ** can not be pushed even if you have write permission.

**Comment by delvh** [comment]
Yes, that should already be possible with branch protection, although with a workaround as you need to invert the logic:
Add branch protection to allow pushes to branch names that match your wanted pattern.
Then, add a wildcard `**` that disallows pushes to everything else.

**Comment by sebastian-sauer** [comment]
Maybe this could be solved. One issue I currently see is that force push will not be allowed on feature branches (as branch protection doesn't allow force push). Or is there an option i currently can't see?
