### ISSUE TITLE
Improve Organizations

### ISSUE THREAD

**Issue by give-me-my-toblerone** [go-gitea/gitea#277]
Organizations are really confusing.

- "settings" are impossible to find
- managing users is really confusing, I keep jumping left and right without understanding where I'm going
- the creator and all members should be visible by default (and not hidden)

**Comment by rwese** [comment]
is this still an issue?

* Settings can be now found at the organisation page

![grafik](https://user-images.githubusercontent.com/7153716/47673352-a2662700-dbb4-11e8-9d80-987ee2587b8f.png)

* managing users

If you have very granular permissions in your organisation this can be tedious.

* "show all members"

This could easily  mess up the organizations page.
