### ISSUE TITLE
API Request: Re-request review post ("user")

### ISSUE THREAD

**Issue by Snappiestjack** [go-gitea/gitea#27707]
### Feature Description

When a pull request is reviewed as Changes Request our workflow is to then Re-request a review from the user who requested the changes, our push process uses a in-house script. It would be great if the API had a post that allowed a re-request for a given user to be done, eliminating the need for the UI interaction as a additional step for the dev.

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/6187142/7c7803f9-2432-47bb-8463-65b500a55ae9)

**Comment by lng2020** [comment]
Reasonable. I will handle this.

**Comment by lng2020** [comment]
endpoint `POST /api/v1/repos/{owner}/{repo}/pulls/{index}/requested_reviewers` just works for me. Is it suitable for your case?

**Comment by Snappiestjack** [comment]
> endpoint `POST /api/v1/repos/{owner}/{repo}/pulls/{index}/requested_reviewers` just works for me. Is it suitable for your case?

works for you as in just works already?

If true, then yes that's all she wrote. I did see that endpoint, but assumed that was adding a new reviewer, I did not try to see what would happen if the reviewer was already requested, guess I should have,

**Comment by lng2020** [comment]
The endpoint is to add a new review request. If you want to re-request a reviewer, just use the same reviewer's name.

**Comment by Snappiestjack** [comment]
I shall give that a go, thanks.

**Comment by Snappiestjack** [comment]
Can confirm this does work.
