### ISSUE TITLE
CSS class is not included in the dev mode

### ISSUE THREAD

**Issue by nanguanlin6** [go-gitea/gitea#27732]
### Description

![SP5ZXKD_L`D{ JSU$KSISLR](https://github.com/go-gitea/gitea/assets/70063547/cabc8593-194c-4810-bdb6-bdc284a6109d)

those items should have a class called `.repository .repository-summary .sub-menu .item` in `repo.css`, but this class is not included.

![WOBSRT70H5VH3E@R7$BH1 H](https://github.com/go-gitea/gitea/assets/70063547/2c59b2ab-bb06-4de0-b96e-2e2a5e107f5f)

Need a suggestion about how to find out why 😭 

### Gitea Version

latest codebase

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

run in dev mode

### Database

None

**Comment by lng2020** [comment]
Never mind. It's the IDE debug configuration. After building the frontend manually, everything works well.
