### ISSUE TITLE
Incorrect link for submodules that specify the remote port

### ISSUE THREAD

**Issue by Governa** [go-gitea/gitea#2775]
- Gitea version (or commit ref):
d4c9399 and any older one that I've tested
- Operating system: Ubuntu 16.04 (using the docker image)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
https://try.gitea.io/BugReproduction871239/test213
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

In the example URL, there is a submodule called test214 that uses the port (22) as user name in its link.
The submodule configuration is valid and works on the command line.

**Comment by Governa** [comment]
This one (superficially) seems to be pretty simple. If anyone can point me to the right direction I could solve it myself.

**Comment by thehowl** [comment]
The culprit should be this function here: https://github.com/go-gitea/git/blob/master/submodule.go#L32-L74 Have fun! If you need any help, come on #develop on the Discord server or #gitea-dev on Freenode :)

**Comment by Governa** [comment]
Hi,

Is this fix on the Docker image already? I've tested commit "da1edbf" here and it doesn't seems to solve the problem. Is there anything I should do to "update" the links?

**Comment by lunny** [comment]
This has been merged to latest Docker image I think.

**Comment by Governa** [comment]
The problem persists. The submodule link shows "http(s)://<url>/<port>/<repo>" instead of "http(s)://<url>:<port>/<repo>".

The workaround I'm using is to set a relative path on the submodule URL. Fortunately, the workaround is the correct way of doing things :+1:, but older revisions still have the wrong link.

**Comment by zeripath** [comment]
Hi Governa, could you upload another testcase to try, so I can check this out?

**Comment by zeripath** [comment]
@Governa is the link to the come_on submodule in https://try.gitea.io/arandomer/arepoopo an example of this?

https://try.gitea.io/22/arandomer/come_on which should be https://try.gitea.io/arandomer/come_on

generated from `git submodule add ssh://git@try.gitea.io:22/arandomer/come_on.git`

Now looking at:

https://github.com/go-gitea/gitea/blob/f6eedd4dc8fb10df869750c69e2bead0521ec0eb/modules/git/submodule.go#L32-L77

I'm not particularly fond of this code - Why aren't we using the default url parsing code built into go?

Strangely it seems like a similiar case is being tested for in:

https://github.com/go-gitea/gitea/blob/f6eedd4dc8fb10df869750c69e2bead0521ec0eb/modules/git/submodule_test.go#L23

**Comment by lunny** [comment]
I think `git@github.com:a/b.git` is not a standard URL.

**Comment by zeripath** [comment]
yep it isn't just tested it.

**Comment by Governa** [comment]
The one case I had bookmarked is now working, so *works for me* :+1:

**Comment by mrsdizzie** [comment]
This has since been fixed and included in testcases
