### ISSUE TITLE
Render markdown in project descriptions

### ISSUE THREAD

**Issue by rhdunn** [go-gitea/gitea#27759]
### Feature Description

Currently, project descriptions do not support markdown.

This can be useful for formatting the text, adding several paragraphs to the description, adding links, etc..

**Comment by JakobDev** [comment]
Markdown is already supported, but not mentioned. The Field also don't use the markdown editor. I will create a PR for this.

**Comment by Jaffex** [comment]
It currently seems that the project in the repository scope does render markdown while the project in the organisation scope does not.

**Comment by wxiaoguang** [comment]
The project description is rendered as markdown now:

![image](https://github.com/go-gitea/gitea/assets/2114189/9bacfe75-35db-45f7-a48d-ac6a9d6d623b)
