### ISSUE TITLE
Issues don't show up in project

### ISSUE THREAD

**Issue by treyerl** [go-gitea/gitea#27769]
### Description

I tried Gitea using www.gitea.com not try.gitea.com. I created a repo and a project and some issues but the issues don't show up: https://gitea.com/treyerl/Test-Repo/projects/1823

<img width="1125" alt="Bildschirmfoto 2023-10-24 um 12 37 38" src="https://github.com/go-gitea/gitea/assets/1533260/2193a45c-9fe4-4f46-8a99-eae5aa52ac42">

### Gitea Version

 1.22.0+dev-219-gb2f828db5 

### Can you reproduce the bug on the Gitea demo site?

Didn't try

### How are you running Gitea?

www.gitea.com

### Database

None

**Comment by lng2020** [comment]
https://github.com/go-gitea/gitea/pull/27720 need someone to approve

**Comment by lng2020** [comment]
closed with #27720

**Comment by lng2020** [comment]
closed with #27720

**Comment by lng2020** [comment]
closed with #27720
