### ISSUE TITLE
math: Two display-style equations in a quote env don't render

### ISSUE THREAD

**Issue by nschloe** [go-gitea/gitea#27777]
### Description

Another weird little math bug: This

```markdown
> \[
> a
> \]
> \[
> b
> \]
```

isn't shown as two subsequent equations, but as

![screenshot_2023-10-24-200720](https://github.com/go-gitea/gitea/assets/181628/7b5d9229-a139-4698-955e-7489e10d4ef6)

For comparison, this is what

````markdown
> ```math
> a
> ```
> ```math
> b
> ```
````

renders as on GitHub:

![screenshot_2023-10-24-200808](https://github.com/go-gitea/gitea/assets/181628/bd8a46dd-8576-49e1-b4b6-c6776d6d0f3c)

(`$$`-math in quotes in broken.)

### Gitea Version

1.22.0+dev-233-g796ff26e0

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

https://try.gitea.io/

### Database

None

**Comment by nschloe** [comment]
Still an issue on 1.23.0+dev-753-gc5422fae9a (Dec 2024).

**Comment by wxiaoguang** [comment]
Will fix it in 1.23

![image](https://github.com/user-attachments/assets/cd6d8b33-e382-4ee1-ae51-b89179abd84a)

**Comment by wxiaoguang** [comment]
1.23 nightly is ready and I think it should have been fixed, feel free to take a try

![image](https://github.com/user-attachments/assets/e5100f40-875b-4f6a-b934-f2d4c05d2d21)

**Comment by nschloe** [comment]
Confirmed working, thanks!
