### ISSUE TITLE
Database migration issue: 1.15.4 -> 1.21

### ISSUE THREAD

**Issue by mheden** [go-gitea/gitea#27771]
### Description

When trying to migrate from gitea 1.15.4 to 1.21 I get the following error when migrating the database (sqlite3):
```
2023/10/24 15:39:21 routers/common/db.go:36:InitDBEngine() [E] ORM engine initialization attempt #9/10 failed. Error: migrate: migration[218]: Improve Action table indices v2 failed: unable to open database file: The system cannot find the path specified.
```

When restoring the database file and try other gitea versions it starts to fail in with 1.17 which seems to be matching well with:
```
	// v218 -> v219
	NewMigration("Improve Action table indices v2", v1_17.ImproveActionTableIndices),
```

When looking at the database file, version has been increased from 189 to 218.

### Gitea Version

1.21

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/mheden/9aaaf9bfec0299e7a3e80ee2551113fd

### Operating System

Windows

### How are you running Gitea?

Starting `gitea-1.21-gogit-windows-4.0-amd64.exe` from a command (cmd.exe) window

### Database

SQLite

**Comment by lunny** [comment]
Looks like it's unrelated to Gitea. Maybe it's a permission problem.
