### ISSUE TITLE
Can't get old versions on Debian package registry with apt

### ISSUE THREAD

**Issue by WooDeNDark** [go-gitea/gitea#27783]
### Description

When I try to get an older version of a package I get an error. After checking all the packages in the repository, I noticed that only the latest packages of each package group are displayed.

### Gitea Version

1.20.5 built with GNU Make 4.4.1, go1.20.8 : bindata, timetzdata, sqlite, sqlite_unlock_notify

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/33422161/91d47d5e-7969-4ac8-9631-3828349a5faf)
![image](https://github.com/go-gitea/gitea/assets/33422161/68b7dfaf-a2d5-4220-9fd8-171e640f267d)
![image](https://github.com/go-gitea/gitea/assets/33422161/171e41bc-5b5c-49fa-ad22-c44f3e6a43f1)

### Git Version

2.40.1, Wire Protocol Version 2 Enabled

### Operating System

Ubuntu 20.04

### How are you running Gitea?

Docker version on Docker Hub with latest tag

### Database

PostgreSQL

**Comment by KN4CK3R** [comment]
That's by design at the moment. Usually the debian package index contains only the latest available version and only that version is installable with apt.

**Comment by WooDeNDark** [comment]
> That's by design at the moment. Usually the debian package index contains only the latest available version and only that version is installable with apt.

Is it currently necessary to create components for specific versions?

**Comment by KN4CK3R** [comment]
That would be a workaround. I just used the latest package version then because the "big" repositories do the same. But we can list all package versions.

**Comment by WooDeNDark** [comment]
> That would be a workaround. I just used the latest package version then because the "big" repositories do the same. But we can list all package versions.

Yes, I understand. It would be convenient for the component to select all versions or only the latest one. For example, for the "main" component have only the latest version, and for "dev" have all versions

**Comment by KN4CK3R** [comment]
I will change it to list all versions. The Docker repository for example does that too https://download.docker.com/linux/debian/dists/bookworm/stable/binary-amd64/Packages .

**Comment by WooDeNDark** [comment]
> I will change it to list all versions. The Docker repository for example does that too https://download.docker.com/linux/debian/dists/bookworm/stable/binary-amd64/Packages .

Thanks

**Comment by KN4CK3R** [comment]
Added in #27786
