### ISSUE TITLE
wrong i18n

### ISSUE THREAD

**Issue by cruvie** [go-gitea/gitea#27785]
### Description

in English mode
but 
<img width="567" alt="Xnip2023-10-25_22-29-02" src="https://github.com/go-gitea/gitea/assets/55651847/66815d10-2e77-4417-904b-a5b2398346fc">

### Gitea Version

1.20.5

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

docker

### Database

None

**Comment by JakobDev** [comment]
That button text comes from your browser, not Gitea
