### ISSUE TITLE
Can't change user visibility in gitea.com

### ISSUE THREAD

**Issue by yp05327** [go-gitea/gitea#27797]
### Description

@lunny 
I can not change my user visibility in gitea.com
![bug](https://github.com/go-gitea/gitea/assets/18380374/0b5176da-70e5-43b5-bb2a-1adf7d1ec380)

but I can do this in try.gitea.io
![bug](https://github.com/go-gitea/gitea/assets/18380374/8e7733fe-437f-4f5f-96b1-b31e559abdb7)

### Gitea Version

unknown

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

gitea.com

### Database

None

**Comment by lng2020** [comment]
I can change it on both website.

**Comment by techknowlogick** [comment]
There is a configuration item that is conflicting with changing some information about this account. @yp05327 if you reach out to me in discord I can update the visibility of your account.
