### ISSUE TITLE
Display a License tab

### ISSUE THREAD

**Issue by give-me-my-toblerone** [go-gitea/gitea#278]
Like GitHub does. It shows a tab with the project license, so it's immediate to see what it is

**Comment by tboerger** [comment]
I don't understand what you want to request, please explain it properly.

**Comment by thibaultmeyer** [comment]
Maybe he speak about this?

![image](https://cloud.githubusercontent.com/assets/1005086/20648488/e5980da2-b4a8-11e6-871f-015b409efde5.png)

**Comment by tboerger** [comment]
Ah, that makes more sense.

**Comment by lunny** [comment]
But for a self-hosted server, I seems there is no requirement.

**Comment by thibaultmeyer** [comment]
we are no forced to do something like github who scan repo to determine license. maybe just a selectbox field on repo settings page is enough ?

**Comment by tboerger** [comment]
This is something we can integrate at some point, so I moved it to a future milestone

**Comment by bkcsoft** [comment]
Using something like go-license[1] it'd be fairly simple to implement, just remember to _cache_ the result until the license-file changes (just add another column in the repo-table) 

[1] https://github.com/ryanuber/go-license

**Comment by thibaultmeyer** [comment]
yes we could add a new field on repo model and update it at each push / merge event.

**Comment by bkcsoft** [comment]
@0xbaadf00d preferably only update when `LICENSE*` have been updated ;)

**Comment by bamboleeeero-bamboleeeero** [comment]
@bkcsoft that may not be always he case... some projects use COPYING for instance

**Comment by bamboleeeero-bamboleeeero** [comment]
LICENSE files my also not necessarily contain a single license, but a list of licenses for various components

**Comment by bkcsoft** [comment]
@bamboleeeero-bamboleeeero
> some projects use COPYING for instance

How does GitHub handle this?

> but a list of licenses for various components

Same here. How does others handle that?

As I see it, it's a new feature, do the smallest amount of work first then extend on that in a later version :)

**Comment by nogweii** [comment]
Github handles this through the gem [licensee](https://github.com/benbalter/licensee).

> some projects use COPYING for instance

Github scans the root of a project, and matches the files in that directory against a series of regular expressions with scores. High enough and it's treated as a file that likely contains the license text.

> but a list of licenses for various components

The first license that Licensee detects and knows about is used. A better solution is being discussed at https://github.com/benbalter/licensee/issues/57

**Comment by gsantner** [comment]
I can agree to @bamboleeeero-bamboleeeero - the filename is not always LICENSE. E.g. LICENSE.txt, LICENSE.md, COPYING are often used too

**Comment by gsantner** [comment]
activity!

**Comment by lunny** [comment]
ref. https://github.com/src-d/go-license-detector

**Comment by hendrikbl** [comment]
@lunny Any plans to implement this? The library looks promising.

**Comment by lafriks** [comment]
Library moved to https://github.com/go-enry/go-license-detector

**Comment by BaxAndrei** [comment]
I would love to see this suggestion implemented. Even if it is a self-hosted version, I offered access to several people on it and it would be useful to have a license tab.

**Comment by mxmehl** [comment]
May I suggest to also support the more flexible [REUSE](https://reuse.software) standard when implementing this important feature?

License detection would become really easy, especially if multiple licenses are in use. All you have to do is fetching the file names from the `LICENSES` directory. For instance, [check this](https://github.com/fsfe/reuse-tool/tree/master/LICENSES).

The files names (without `.txt`) indicate the unique SPDX license identifiers, and save everyone from interpreting the often diverging text in files like `LICENSE` or `COPYING`.

**Comment by 6543** [comment]
google did start developing a licence detector: https://github.com/google/licensecheck

**Comment by quackerd** [comment]
Would be very helpful indeed to have a license tab
