### ISSUE TITLE
Register a new user with Oauth2 doesn't link account

### ISSUE THREAD

**Issue by nanguanlin6** [go-gitea/gitea#27808]
### Description

Reproduce procedure:
1. create an account with a username and email in the Oauth2 provider. The username and email should not exist in the Gitea instance.
2. On the register page, click `sign in` with your oauth2 provider. Then it will redirect to a page to confirm the creation of an account in Gitea, which is expected since the username and the email are not existed in Gitea.
3. Click confirm. Now a new Gitea account is created but in `settings/security`, you can't see the `Account Linking` information, which is unexpected.

### Gitea Version

latest codebase

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

built with source code

### Database

None

**Comment by lng2020** [comment]
duplicate with #7056
