### ISSUE TITLE
Show Database Schema Version in Admin Area

### ISSUE THREAD

**Issue by mikeperalta1** [go-gitea/gitea#27818]
### Feature Description

When switching from the master branch to a release tag, the database schema version often must be downgraded. It would be very useful to see the current database schema version from within the Admin control panel somewhere, so the server administrator can quickly understand what sort of downgrade will need to be performed (if any), without digging through the local source tree.

My Personal use case: I have an intranet-only server sitting on the master branch, and I would like to put it back on an official release tag. Right now, that involves opening a shell and checking the source for a new tag's schema version to see if I can effortlessly build from a tag without downgrading, before also looking through the tag's source. It would be more convenient if I could simply open the web UI to see my installation's current database schema version.

**Comment by wxiaoguang** [comment]
* If you are a developer, the RUN_MODE=dev will tell you the database version.
* If you are an end user, never downgrade by changing the database version, it would cause unfixable problems.

**Comment by mikeperalta1** [comment]
> * If you are a developer, the RUN_MODE=dev will tell you the database version.
> 
>     * If you are an end user, never downgrade by changing the database version, it would cause unfixable problems.

Yeah I'm an end user, basically waiting and watching for a tag to catch up with the schema version that my main branch build was on.

**Comment by wxiaoguang** [comment]
You should just follow Gitea's release version.

For example:

* There is no schema change between 1.20.0 / 1.20.1 / 1.20.2 / ...
* There are schema changes between 1.20.x / 1.21.x

And see this example: https://docs.gitea.com/installation/upgrade-from-gitea


Showing the "schema version" doesn't really bring benefit to end users, I suppose this issue could be closed.
