### ISSUE TITLE
Non admin can't search for repository in Team Repositories, but can add?

### ISSUE THREAD

**Issue by webjoel** [go-gitea/gitea#2781]
- Gitea version (or commit ref): 3af5b67
- Git version: 2.7.4
- Operating system: Linux ubuntu 64
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes ( https://try.gitea.io/org/webjoel_test_user/teams/team_test )
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

In team management, if the user is not the owner, he can not search for repositories in the "Search repository ..." field to add to the team, but if I type the full repository name and click "Add Team Repository" the repository is added.

If the search does not work because of owner permission, the addition should work the same way.

**Comment by lunny** [comment]
![image](https://user-images.githubusercontent.com/81045/33865212-aa1bdade-df2b-11e7-9578-26eb7bba4076.png)
Non-admin has no input box there? Or maybe some PR fixed this?

**Comment by webjoel** [comment]
It's true, now the problem not exist more. This issue can be closed. :)
