### ISSUE TITLE
When will formal version of gitea:1.21.0 to be released in docker hub?

### ISSUE THREAD

**Issue by caixiangibm** [go-gitea/gitea#27810]
### Description

Need to confirm with gitea team when will formal version of **gitea/gitea:1.21.0** to be released in docker hub? (https://hub.docker.com/r/gitea/gitea/tags)
I had raised the question in another issue and it was said to be maybe some day this week Of Oct 27, details please refer to - https://github.com/go-gitea/gitea/issues/27194#issuecomment-1767893046, while so far the formal release of gitea/gitea:1.21.0 not available in docker hub yet, and not found formal repo tag of "v1.21.0" in https://github.com/go-gitea/gitea/tags

Would you update me here when could we pull newer version of gitea/gitea:1.21.0 image from docker hub? Thanks in advance!

### Gitea Version

v1.21

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

linux/amd64

### How are you running Gitea?

run with gitea docker image

### Database

None

**Comment by lunny** [comment]
It will be late because we need to wait for some PRs.

**Comment by denyskon** [comment]
https://blog.gitea.com/release-of-1.21.0/
