### ISSUE TITLE
Disabling disable avatar breaks Gitea

### ISSUE THREAD

**Issue by batkuip** [go-gitea/gitea#27828]
### Description

Disabling Disable Gravatar in configuration broke Gitea for me.  All pages give me:

```
Render failed, failed to render template: user/dashboard/dashboard, error: template error: builtin(bindata):base/head_navbar:146:7 : executing "base/head_navbar" at <avatar $.Context .SignedUser 24 "gt-mr-2">: error calling avatar: runtime error: invalid memory address or nil pointer dereference
----------------------------------------------------------------------
					{{avatar $.Context .SignedUser 24 "gt-mr-2"}}
					  ^
----------------------------------------------------------------------
```

### Gitea Version

1.20.5

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/110234/b99f2126-c7aa-406b-a779-03ba6ed509e3)

### How are you running Gitea?

docker compose

### Database

MySQL/MariaDB

**Comment by lunny** [comment]
I can reproduce this only once but cannot repeat it never.

**Comment by wxiaoguang** [comment]
There are many new refacotrings for these code. So I guess there might be no problem in 1.21
