### ISSUE TITLE
No way to display full branch names when browsing them in drop downs

### ISSUE THREAD

**Issue by RustyRaptor** [go-gitea/gitea#27833]
### Description

We use particularly long branch names and it is difficult to see the branch names when browsing them in the UI. Specifically when there is a drop down menu such as on the home page of a repo or when making a pull request. On the repo home it isn't as bad but on the pull request its really bad if you have a long organization name because it appends all the names before the branch name. 

A couple solutions could be either to make the drop-down box resizable or to add a tooltip to each branch in the list that displays the full name. 

### Screenshots

![Screenshot_20231029_092745](https://github.com/go-gitea/gitea/assets/7911442/03f06afb-2bf0-4b7e-9eae-66b1c45f4d5d)
![Screenshot_20231029_092859](https://github.com/go-gitea/gitea/assets/7911442/3bb5a575-358b-411f-8c33-8b3d84799c26)

### Gitea Version

1.13.2 built with GNU Make 4.1, go1.15.7 : bindata, sqlite, sqlite_unlock_notify

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

Server: Turnkey Linux (debian), Client: Arch Linux

### Browser Version

Microsoft Edge Version 117.0.2045.55 (Official build) (64-bit)

**Comment by Kanav-Arora** [comment]
Hi @denyskon 
Can I work on this issue?

**Comment by yp05327** [comment]
This issue has been fixed.
