### ISSUE TITLE
How to limit actions to run for a specific gitea organization?

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#27830]
### Feature Description

As written on the docs as well https://docs.gitea.com/usage/actions/faq#how-to-avoid-being-hacked, to prevent malicious script being running, I would like to limit the organization which could run Github Actions.

**Comment by lunny** [comment]
You can just create a runner register token from the organization setting. All runners registered with this token will only work for the repositories under this organization.

**Comment by kaliubuntu0206** [comment]
@lunny Ah I see, seems like it should be documented, thank you!
