### ISSUE TITLE
math: indented display math doesn't render

### ISSUE THREAD

**Issue by nschloe** [go-gitea/gitea#27834]
### Description

Using display math in quote environment only works if indented by 0 or 1 spaces. For indentation with 2 spaces, a superfluous open square bracket `[` is created, and an error is produced for 3+ spaces indentation.

MWE:
````markdown
Indent 0:

\[
\alpha
\]

Indent 1:

 \[
 \alpha
 \]

Indent 2:

  \[
  \alpha
  \]

Indent 3:

   \[
   \alpha
   \]
````

Screenshot:

![screenshot_2023-11-17-082125](https://github.com/go-gitea/gitea/assets/181628/01b3a4a2-7567-484d-9c01-5d41c4638f6f)

### Gitea Version

1.22.0+dev-256-gb36e2ca41

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

https://try.gitea.io/

### Database

None

**Comment by nschloe** [comment]
@lunny Are you sure this is a `type/report-upstream` issue?

**Comment by nschloe** [comment]
Ping @lunny: Check `type/report-upstream` label.

**Comment by lunny** [comment]
Sorry if I made a mistake. I will check it again once I get my computer.

**Comment by delvh** [comment]
This issue is indeed a tough question.
I can imagine it to be caused both upstream and from us.

**Comment by nschloe** [comment]
Still an issue on 1.23.0+dev-753-gc5422fae9a (Dec 2024).

**Comment by wxiaoguang** [comment]
I am refactoring the render module, I think it will be fixed in 1.23, soon

**Comment by wxiaoguang** [comment]
1.23 nightly is ready and I think it should have been fixed, feel free to take a try

![image](https://github.com/user-attachments/assets/8ad2fcaa-521e-4a55-a5bd-7fd857ae5b01)

**Comment by nschloe** [comment]
Confirmed fixed.
