### ISSUE TITLE
 Hope to support multiple 'ROOT_URL'

### ISSUE THREAD

**Issue by itodouble** [go-gitea/gitea#27843]
### Feature Description

Hope to support multiple 'ROOT_URL'
I use FRP to access the internal network when I was outside
I hope to have faster access when using the internal network

**Comment by lunny** [comment]
As a workaround, you can switch the DNS ip when you visit from outside and internally.

**Comment by wxiaoguang** [comment]
That's impossible in many cases because the server doesn't know the "correct" root URL, for example: when sending webhook requests.
