### ISSUE TITLE
Runner registration doesn't work

### ISSUE THREAD

**Issue by Demmtop** [go-gitea/gitea#27871]
### Description

I have running a kubernetes gitea pod (1.20.5) and an act runner pod (gitea/act_runner:latest-dind-rootless).
Runner is activeted in the config file.
The runner token is saved as secret for the runner.
In the gitea log I see following
`2023/11/01 23:59:19 ...eb/routing/logger.go:102:func1() [I] router: completed POST /api/actions/ping.v1.PingService/Ping for 10.244.237.98:55484, 200 OK in 0.2ms @ <autogenerated>:1(http.Handler.ServeHTTP-fm)`
`2023/11/01 23:59:19 ...eb/routing/logger.go:102:func1() [I] router: completed POST /api/actions/runner.v1.RunnerService/Register for 10.244.237.98:55484, 500 Internal Server Error in 9.1ms @ <autogenerated>:1(http.Handler.ServeHTTP-fm)`

This is the log of act_runner
`level=info msg="Registering runner, arch=amd64, os=linux, version=v0.2.6."`
`level=warning msg="Runner in user-mode."`
`level=debug msg="Successfully pinged the Gitea instance server"`
`level=error msg="poller: cannot register new runner" error="unknown: runner token not found"`
`Error: Failed to register runner: unknown: runner token not found`
`Waiting to retry ...`

Why cannot registration the runner? The token exist.

### Gitea Version

1.20.5

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

As kubernetes pod.

### Database

MySQL/MariaDB

**Comment by lng2020** [comment]
Can u provide more info about your Gitea version and how you run it? 
As far as I know, the bug only occurred in 1.21 and is already fixed.

**Comment by Demmtop** [comment]
The problem is resovled. The registration with base64 encoded token in a secrect.yaml doesn't work. With uncoded token i the deployment.yaml works the registration.

**Comment by abdennour** [comment]
thanks for mentioning : gitea/act_runner:latest-dind-rootless
