### ISSUE TITLE
1.20 update --> Cannot be selected as a reviewer anymore

### ISSUE THREAD

**Issue by FrostKiwi** [go-gitea/gitea#27886]
### Description

Our Gitea deployment was recently updated from `1.19.X` to `1.20.4`. After the update, others cannot select me as a reviewer anymore, but everyone else can be selected.

My Account is the sole admin account and I am the repo owner. It only concerns one repo, our single longest running one with over a 1000 commits and many branches. There is a list of collaborators, which are allowed to create branches and commit. I am not on that list, as I'm the repo owner.

When new Pull Requests are created, I cannot be selected as the reviewer anymore, but every other accounts on the collaborators list can be selected. I cannot figure out what caused this change. It only concerns this one long-running repo.

How can I diagnose this?

### Gitea Version

1.20.4

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

Self-hosted ubuntu LTS server, downloaded linux-amd64 binary from the official website and made a systemd service out of that.

### Database

SQLite

**Comment by lng2020** [comment]
It requires a lot of work to find out the root reason. 
The routing function is 
https://github.com/go-gitea/gitea/blob/abd79ddebfa72e817d2eb3159e79b0d18b07263f/routers/web/repo/issue.go#L1344
It uses 
https://github.com/go-gitea/gitea/blob/abd79ddebfa72e817d2eb3159e79b0d18b07263f/routers/web/repo/issue.go#L631
to get the potential reviewer.
The DB query is 
https://github.com/go-gitea/gitea/blob/abd79ddebfa72e817d2eb3159e79b0d18b07263f/models/repo/user_repo.go#L112

You probably should set up a [debug configuration](https://docs.gitea.com/development/hacking-on-gitea#visual-studio-code) to find out why. Good luck with that!

**Comment by FrostKiwi** [comment]
Upgraded to `1.20.5`, same result.
Is there maybe a possibility to set the repo owner as a collaborator as well, considering collaborators can be selected?

For reference, I do show up as the review after review, but cannot be chosen for review. I wonder if it has something to do with my Admin account be created upon initial installation, not through the create user interface.
![image](https://github.com/go-gitea/gitea/assets/60887273/d3264ba0-45ea-4e67-98ba-d2597d55b13a)
![image](https://github.com/go-gitea/gitea/assets/60887273/a7e2282b-eacd-466d-a970-efa16776aa7f)


> You probably should set up a [debug configuration](https://docs.gitea.com/development/hacking-on-gitea#visual-studio-code) to find out why. Good luck with that!

So the procedure would look like: Copy Database from server to a local machine, setup the local test with the database from the server?

**Comment by FrostKiwi** [comment]
Solved itself with the update to `1.21.1`. I presume some kind of rebuild / database upgrade rechecked this aspect and I'm selectable again.
