### ISSUE TITLE
Code blocks still exist aftering deleting code review comments

### ISSUE THREAD

**Issue by nanguanlin6** [go-gitea/gitea#27904]
### Description

Seem like a frontend issue. After I refresh the web page, the code blocks disappear.

### Screenshots

<img width="508" alt="image" src="https://github.com/go-gitea/gitea/assets/70063547/a5e62768-efc4-4721-9b4d-994919a38431">

### Gitea Version

latest codebase

### Can you reproduce the bug on the Gitea demo site?

Yes

### Browser Version

none

**Comment by lng2020** [comment]
solved by #29951
