### ISSUE TITLE
Cannot click on action link if the commit message is empty

### ISSUE THREAD

**Issue by ldicarlo** [go-gitea/gitea#27901]
### Description

When I commit using ` git commit --allow-empty-message -m ""`
Then I cannot click on the link in the associated action.
The resulting `html` element is 
`<a class="index gt-no-underline title action-item-title" title="" href="/<AUTHOR>/<REPO>/actions/runs/1"></a>`

Maybe we should have a placeholder here in case of missing message? 

But this is really not a big problem, I just write it here so you know, but it is really minor.

### Gitea Version

1.20.5

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/15803534/546756b9-c940-4e78-b03e-16b52b6fe937)

### Operating System

NixOS

### How are you running Gitea?

using nix official gitea service 

### Database

PostgreSQL

**Comment by silverwind** [comment]
Maybe `<empty commit message>` placeholder. Likely this issue affects more places than just this list, so a shared template would be good to make it re-usable elsewhere.
