### ISSUE TITLE
Add support for `latest` in Run-URL

### ISSUE THREAD

**Issue by JOKUE2002** [go-gitea/gitea#27911]
### Description

Whilst trying to access the latest run of my action, I noticed, that the URL `https://my-gitea.tld/user/repo/actions/runs/latest` would always point to the run with the ID 0 (like `https://my-gitea.tld/user/repo/actions/runs/0`). This would also work with any other word (e.g. 'hello', 'world', 'anything', ...) instead of `latest`.

Would love to see "latest" to point to the newest run (run w/ highest ID) and any other word to point nowhere.

Couldn't reproduce on try.gitea.io because I have no action-runner I can access or repurpose available

### Gitea Version

1.20.5

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

2.42.0

### Operating System

Ubuntu 16.04.7 LTS

### How are you running Gitea?

Downloaded binary with a systemctl service

### Database

SQLite

**Comment by KN4CK3R** [comment]
The parameter behind `/run/` is supposed to be a number and a failed number conversion just results in `0`. This should be a proposal.

**Comment by fuxiaohei** [comment]
In `Github Actions`. The `latest` is not supported. For example in Gitea repo, I get  runs link https://github.com/go-gitea/gitea/actions/runs/6863940854, but https://github.com/go-gitea/gitea/actions/runs/latest is 404.

There is another problem.  
https://github.com/go-gitea/gitea/actions/runs/6863940854 is from `docker-dryrun` workflow. 
But  previous one https://github.com/go-gitea/gitea/actions/runs/6863940853 is from `db-tests` workflow.  
The latest run can be from any workflow. Should we provide `latest` in this case ?

**Comment by JOKUE2002** [comment]
> I am wondering why it is working on this [0] gitea server. 
For starters it appears to be a forgejo server...

But would still love to see this in gitea. 
If you for example have a repository with a single workflow (e.g. building a node project), getting the latest would make deployment using gitea more simple than before.

**Comment by monogatron** [comment]
Oh you're right. I just saw the UI and assumed that it is a gitea server. But after your comment I looked again and scrolled down a bit: "Powered by Forgejo"

**Comment by lunny** [comment]
Resolved by #31808
