### ISSUE TITLE
After hiding and unhiding commit checks, there are only four checks available

### ISSUE THREAD

**Issue by nanguanlin6** [go-gitea/gitea#27928]
### Description

take https://gitea.com/xorm/xorm/pulls/2364 for example. 
This PR has eight checks. After hiding and unhiding commit checks, there are only four checks on the web page.
Regression of https://github.com/go-gitea/gitea/pull/26284
cc @yp05327 

### Screenshots

Before: 
![before](https://github.com/go-gitea/gitea/assets/70063547/f9307d34-9fac-4725-a1bd-c02a5c599dbd)
After:
![after](https://github.com/go-gitea/gitea/assets/70063547/c9ce519a-7964-470f-aa91-8a5f8754affd)

### Gitea Version

current main

### Can you reproduce the bug on the Gitea demo site?

Yes

### Browser Version

none

**Comment by lng2020** [comment]
The scroll bar of these commit lists sometimes messes with the scroll bar of the whole web page. Though failed to find a way to steadily reproduce it.

**Comment by lng2020** [comment]
Perhaps we should not confine the height. 
https://github.com/go-gitea/gitea/blob/8557a9455b06c2e17982e9bae5263617500cf5b4/web_src/css/repo.css#L3082-L3086

**Comment by wxiaoguang** [comment]
->  Fix the overflow style for "Hide all checks" #27932

**Comment by silverwind** [comment]
https://github.com/go-gitea/gitea/pull/27932 changes it to 6 visible items.
