### ISSUE TITLE
Project description renders awfully.

### ISSUE THREAD

**Issue by RdrSeraphim** [go-gitea/gitea#2792]
- Gitea version (or commit ref): 1.1.4
- Git version: 
- Operating system: Windows 10
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (any project page with a description)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
Hiya, I was viewing my repo on my Gitea instance and noticed that the description of the project looks very.... bad. Removing "Microsoft YaHei" from `body`'s font-family in Chrome Inspector worked fine, but I'm not sure if this is modifiable on my end. I'm sure I'm not the only one with this occurring, so maybe this should be something modified in code?

## Screenshots
<small>Done on try.gitea.io for easy comparison.</small>

**Before Removing "Microsoft YaHei" from `body`'s font-family**: https://i.imgur.com/47DPaTz.png
**After**: https://i.imgur.com/cGn6h03.png

**Comment by sapk** [comment]
You can use custom/template to use the font that suite you the best by overriding the css file or adding one. 

For details : https://docs.gitea.io/en-us/customizing-gitea/

**Comment by andrew-boyarshin** [comment]
I wonder if changing font stack would improve overall reading experience. Medium for example uses
`medium-content-sans-serif-font,-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Oxygen,Ubuntu,Cantarell,"Open Sans","Helvetica Neue",sans-serif`

Omitting the first one (Medium specific), it can be a great set of time-tested fonts picked by pros whose job is to make content legible. This font-family set, combined with `text-rendering: optimizelegibility', improved font rendering throughout the whole Gitea. The only thing I am not sure about is eastern language family. I suppose *Microsoft YaHei* is only available on Windows, so it might not be a good one to use. If the Medium font set renders everything well, why use current ones?

**Comment by andrew-boyarshin** [comment]
And it can be done in addition to transition to building Semantic UI from LESS sources, without global `!important` overrides as it is done now.

**Comment by sapk** [comment]
font-family is now: `Lato,-apple-system,BlinkMacSystemFont,system-ui,Segoe UI,Roboto,Helvetica,Arial,sans-serif`. I don't remember when it was changed (maybe when changed for language compatibility) but I think we can close this issue.
Feel free to re-open the issue if you still have the same issue.
