### ISSUE TITLE
Organization repository count includes private repositories

### ISSUE THREAD

**Issue by jrjake** [go-gitea/gitea#27926]
### Description

If I mark a repository as private in an organization, that repository is still shown in the count for users who can't access it. See example below.

### Gitea Version

1.20.5

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/118236421/d0fc7b34-0d9c-42d3-b6aa-09d40679ce75)

It states there is 1 repository (the private one) but has 0 in the list.

### Git Version

2.39.2

### Operating System

Debian 12

### How are you running Gitea?

Docker

### Database

PostgreSQL

**Comment by lng2020** [comment]
Could u provide more information about what's the type of the org, public, internal, or Private? And what's the relationship between the user and the org?

**Comment by wfjake** [comment]
It is public organization with private repository. The screenshot is taken when not signed in.

**Comment by JakobDev** [comment]
This is already fixed with #25928

**Comment by wfjake** [comment]
I see in that PR mentions of backport, should it be fixed in 1.20.5 (current version I am running)? Or did backport not happen?

**Comment by lng2020** [comment]
It seems not be backported.

**Comment by wfjake** [comment]
Okay, makes sense. I will close this issue and re-open if I encounter it after release and upgrade to 1.21. Thank you all!
