### ISSUE TITLE
The release is lost after mirror synchronization

### ISSUE THREAD

**Issue by ItsFated** [go-gitea/gitea#27936]
### Description

我有一个clash-verge仓库的镜像,然后在镜像中发布了新版本,并上传了附件。
但是在一次同步镜像后,发布的新版本丢失了。同时我的附件也没有在页面中显示，但是文件和数据库中都有。
**我得问题是**：镜像仓库是否可以发布独立的版本，即便同步后也依然存在？如果不支持，那我该如何删除已经发布的版本，在数据库和附件目录中的产生的文件。

I had a mirror of the clash-verge repository, and then published the new version in the mirror and uploaded the attachment。 but after a synchronous mirror, the new version of the release was lost and my attachment was not displayed in the page but in the file and database
**My question is**: Can a mirror repository publish a separate version and still exist even after synchronization? If not, how do I delete the released version, the generated files in the database and attachment directory

![image](https://github.com/go-gitea/gitea/assets/13051752/2dbe97cd-460a-42a4-9436-e4670c504ed7)
![image](https://github.com/go-gitea/gitea/assets/13051752/c0d04b09-6cea-41fe-abde-0317971232d9)
![image](https://github.com/go-gitea/gitea/assets/13051752/567f92d4-e077-4da0-9dc7-ce897de4443c)

### Gitea Version

1.20.5

### Can you reproduce the bug on the Gitea demo site?

Yes

### Git Version

2.40.1

### Operating System

Proxmox 8.0.2

### How are you running Gitea?

Run in docker

### Database

MySQL/MariaDB

**Comment by lng2020** [comment]
I don't know if a method exists to `a mirror repository publish a separate version and still exist even after synchronization`. 
As for `delete the released version, the generated files in the database and attachment directory`,  `gitea admin repo-sync-releases` will set all releases identical with pull-mirror upstream.

**Comment by lng2020** [comment]
duplicate with https://github.com/go-gitea/gitea/issues/22066?

**Comment by ItsFated** [comment]
> duplicate with #22066?

Yes, I will close this issue.


> I don't know if a method exists to `a mirror repository publish a separate version and still exist even after synchronization`. As for `delete the released version, the generated files in the database and attachment directory`, `gitea admin repo-sync-releases` will set all releases identical with pull-mirror upstream.

Thank you for your reply. I will try to delete release files and database records.

**Comment by ItsFated** [comment]
I deleted files and records in the database and restarted Gitea in Docker, Gitea can still be used normally after restart
![image](https://github.com/go-gitea/gitea/assets/13051752/255dc5d5-88e4-47c0-9ed9-f10397def3fa)
![image](https://github.com/go-gitea/gitea/assets/13051752/0541025f-e8ef-4029-9fa2-f46d962da694)
