### ISSUE TITLE
Gitea "InitIssuesIndexer, open index: incompatible version, 5 is supported"

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#2793]
- Gitea version (or commit ref): 1.2.2
- Git version: 2.7.4
- Operating system: Linux Mint
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist: https://gist.github.com/ahme-t/03e24a734b1d6fdfc65d53f464d628ca

## Description
Gitea start error. Details in log file.

**Comment by lafriks** [comment]
You can just delete issue.bleve from indexers directory and it will be regenerated

**Comment by lafriks** [comment]
I think this is fixed in master branch with #2524

**Comment by lafriks** [comment]
@ethantkoenig can you backport it to 1.2?

**Comment by ghost** [comment]
Thanks solved

**Comment by ethantkoenig** [comment]
@lafriks That would require also backporting #2387.

FYI, this error can only happen when the bleve library is updated, so as long as we don't update bleve on the 1.2 release branch, this fix isn't strictly necessary

**Comment by lafriks** [comment]
@ethantkoenig Could it be that bleve was updated between 1.1 and 1.2?

**Comment by ethantkoenig** [comment]
No. If it was, we would have run into this problem a long time ago

**Comment by lafriks** [comment]
@ethantkoenig what bleve index version is used in master branch?

**Comment by ethantkoenig** [comment]
7, if I recall correctly

**Comment by lafriks** [comment]
ok, I'm closing this issue than
