### ISSUE TITLE
发生了一个错误:  SyncRepoBranches, mssql: 不能在具有唯一索引“UQE_branch_s”的对象“dbo.branch”中插入重复键的行

### ISSUE THREAD

**Issue by mengyufeng** [go-gitea/gitea#27948]
### Description

发生了一个错误:

SyncRepoBranches, mssql: 不能在具有唯一索引“UQE_branch_s”的对象“dbo.branch”中插入重复键的行。重复键值为 (118,

### Gitea Version

1.21.0+rc2-48-g6eadad822

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

exe

### Database

None

**Comment by lunny** [comment]
duplicated with #25909
