### ISSUE TITLE
Mapping Oid Groups to more than one Team

### ISSUE THREAD

**Issue by samotelf** [go-gitea/gitea#27944]
### Description

I have configured Gitea for SSO with AAD following https://blog.gitea.com/feature-preview-mapping-oidc-groups-to-teams/
I wonder if it's possible to assign several groups instead of one has it's mentioned in the guide.

for instance:
{"105fe9f2-ae3c-4ae1-8888-d4f8edd48507":{"security":["security"]}}
{"13136346-2bf6-42d8-7777-2322a4093c73":{"helpdesk":["helpdesk"]}}

If so, how can it be done? I tried several combinations with no avail.

Thank you.

### Gitea Version

1.20.5

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

2.40.1

### Operating System

Debian 12

### How are you running Gitea?

Docker

### Database

SQLite

**Comment by KN4CK3R** [comment]
```json
{
  "105fe9f2-ae3c-4ae1-8888-d4f8edd48507": {
    "org1": [
      "team1"
    ],
    "org2": [
      "team2",
      "team3"
    ],
  }
}
```

**Comment by samotelf** [comment]
Hello KN4CK3R. 
Thank you for your reply.
Won't that map the group ID "105fe9f2-ae3c-4ae1-8888-d4f8edd48507" to both org1 and org2 and teams?

Per your documentation, the correct way is aad group id + org + team.
So I would like:
{"105fe9f2-ae3c-4ae1-8888-d4f8edd48507":{"security":["security"]}} for aad security team + org security + team security and {"13136346-2bf6-42d8-7777-2322a4093c73":{"helpdesk":["helpdesk"]}} for aad helpdesk team + org helpdesk + team helpdesk.

**Comment by samotelf** [comment]
Ah, you're assuming that all my users will be in the same group in aad.  
what if they aren't in the same group? Is it possible to do it?

**Comment by KN4CK3R** [comment]
My example just shows that membership in `105fe9f2-ae3c-4ae1-8888-d4f8edd48507` assigns the user to `team1` in `org1` and to `team2` and `team3` in `org2`.

If you want to map another membership to different teams just adjust the json:
```json
{
  "105fe9f2-ae3c-4ae1-8888-d4f8edd48507": {
    "security": [
      "security"
    ]
  },
  "13136346-2bf6-42d8-7777-2322a4093c73": {
    "helpdesk": [
      "helpdesk"
    ]
  }
}
```
