### ISSUE TITLE
Mirrors should not migrate `refs/pull` and then the relative commits will be gone.

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#27961]
### Gitea Version

main

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

Some filters should be applied in https://github.com/go-gitea/gitea/blob/main/services/mirror/mirror_pull.go#L225-L235 to not sync `refs/pull` for git mirror.

### Database

None

**Comment by ericLemanissier** [comment]
Hi @lunny
It looks like this still happens, in spite of https://github.com/go-gitea/gitea/blob/846f6187168c807e1353d46d5d2260bf077b43cd/services/mirror/mirror_pull.go#L478-L480
![image](https://github.com/user-attachments/assets/faed0d9d-6fe7-4192-89fc-6ed7372c05c3)
Is there a known work-around ?

**Comment by ericLemanissier** [comment]
Thanks ! I'll test it when it's released
