### ISSUE TITLE
as a user editing a comment i would like not to lose my submission if it turns out my session had ended

### ISSUE THREAD

**Issue by KiaraGrouwstra** [go-gitea/gitea#27975]
### Feature Description

i sometimes take my time updating an issue comment, to the point where my session is no longer active.
when i submit my updated comment at that point, it initially shows an empty comment, while upon refreshing i learn that my update had not gone thru.

i feel the UX here could be improved by having the UI warn the user, ideally while retaining the info submitted.

tested on: codeberg

**Comment by KN4CK3R** [comment]
Related to #27109, #24253, #17705 and #22907
