### ISSUE TITLE
PR revisions tab show more commits after being merged

### ISSUE THREAD

**Issue by deguif** [go-gitea/gitea#2797]
- Gitea version (or commit ref): 1.2.1+6-g33e1641
- Git version: 
- Operating system: Docker
- Database:
  - [x] PostgreSQL
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (https://try.gitea.io/deguif/test-pr-commits)

## Description
After merging a PR, the revisions tab on the PR page show more commits than when the PR was merged.
For example, in my case the PR had one commit in its revisions tab, once merged it got a lot more commits.

**Comment by lafriks** [comment]
Can you provide steps to reproduce that?

**Comment by deguif** [comment]
Yes sure.
Just to confirm the issue, I reproduced it on https://try.gitea.io/deguif/test-pr-commits
That's since I upgraded to 1.2 that the bug appeared (previously I was using Gitea 1.1.0 before upgrading to 1.2).

Here the steps to reproduce:
1) - Create a new branch with one commit and push it on the repository
2) - Create a PR from this branch to the master branch
3) - Add commits to master and push them
4) - Merge previous PR
5) - Commits that were not in the PR branch but that they were pushed to master, will appear on the PR.

Here the git history of master and PR branch before merging PR
1) PR branch
```
* c79331c - (HEAD -> test-one-commit, origin/test-one-commit) Added one commit in the branch (François-Xavier de Guillebon 8 minutes ago)
* 6722783 - first commit (François-Xavier de Guillebon 11 minutes ago)
```

2) Master branch
```
* 9cbf1c3 - (HEAD -> master, origin/master) Added test2.txt (François-Xavier de Guillebon 6 minutes ago)
* 5a82c4a - Added test1.txt (François-Xavier de Guillebon 7 minutes ago)
* 6722783 - first commit (François-Xavier de Guillebon 10 minutes ago)
```

**Comment by lafriks** [comment]
Thanks, confirmed

**Comment by deguif** [comment]
Thanks.
