### ISSUE TITLE
Integrate badges of services

### ISSUE THREAD

**Issue by tboerger** [go-gitea/gitea#28]
I would suggest to include a specific amount of badges, I would suggest a list of these:

* DroneCI, like [![Build Status](http://github.dronehippie.de/api/badges/kleister/kleister-api/status.svg)](http://github.dronehippie.de/kleister/kleister-api)
* Codecov.io, like [![codecov](https://codecov.io/gh/gin-contrib/location/branch/master/graph/badge.svg)](https://codecov.io/gh/gin-contrib/location)
* Go report, like [![Go Report Card](https://goreportcard.com/badge/github.com/gin-contrib/location)](https://goreportcard.com/report/github.com/gin-contrib/location)
* Go doc, like [![GoDoc](https://godoc.org/github.com/gin-contrib/location?status.svg)](https://godoc.org/github.com/gin-contrib/location)
* Docker, like [![](https://images.microbadger.com/badges/image/kleister/kleister-api.svg)](http://microbadger.com/images/kleister/kleister-api "Get your own image badge on microbadger.com")
* Gitter, like [![Join the chat at https://gitter.im/go-gitea/gitea](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/go-gitea/gitea?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

Anything that I missed?

**Comment by xinity** [comment]
list is fine, not sure we should add more btw

**Comment by tboerger** [comment]
I think with these badges we got everything you can use for a Go project.
