### ISSUE TITLE
Add new separate repositories for issues and pullrequests

### ISSUE THREAD

**Issue by give-me-my-toblerone** [go-gitea/gitea#280]
Currently Gogs has to 2 repositories for each repo:

    one for the source code, for example https://try.gogs.io/[user]/[repo].git
    one for wikis, for example https://try.gogs.io/[user]/[repo].wiki.git

Could you please add another for issues and for pull requests? For example

    https://try.gogs.io/[user]/[repo].issues.git
    https://try.gogs.io/[user]/[repo].pr.git

This would be extremely useful because users can backup all their data (code/issues/wikis/prs). And even more useful, if I want to move from one server to another server, I could just git clone and git push all my repos easily (which at the moment is not possible).

**Comment by thibaultmeyer** [comment]
issues and PRs are saved on database, you have just to run `gitea dump` to retrieve a backup containing all repo and the SQL backup.

You can also use your database tools like pg_dump or mysqldump...

**Comment by tboerger** [comment]
It doesn't make sense to put that into a repository, but feel free to provide another feature request that provides a ui to export and import that data on the repository settings.

**Comment by lunny** [comment]
We provide all that features via [go-sdk](https://github.com/go-gitea/go-sdk).
