### ISSUE TITLE
Mirrors: Releases, Issues

### ISSUE THREAD

**Issue by Aetherinox** [go-gitea/gitea#28011]
### Description

Not sure if this is an issue, or a feature request.

When I use the migration feature, the repo itself, release tags, and the wiki get copied and works great.
However, the releases page is empty, and also none of the issues get migrated over. I'm not sure if this is intentional or if I've done something wrong.

### Gitea Version

1.20.4

### Can you reproduce the bug on the Gitea demo site?

Yes

## Releases Page (w/ Tags)
![image](https://github.com/go-gitea/gitea/assets/118329232/86acdf65-9b29-47b7-bdfc-d7498b161387)

![image](https://github.com/go-gitea/gitea/assets/118329232/cf5b2baf-4691-4940-b606-50353d4745eb)

## Issues
![image](https://github.com/go-gitea/gitea/assets/118329232/4a3f45c1-42d1-4633-9c55-5a9c11de47a6)

![image](https://github.com/go-gitea/gitea/assets/118329232/0f924c4b-eb9d-45d4-a450-6333bb0922c1)

### Git Version

2.42.1

### Operating System

Ubuntu 20.04 LTS

### How are you running Gitea?

Running binary from releases page
Same issue on Gitea demo site.

### Database

MySQL/MariaDB

**Comment by JakobDev** [comment]
This is intentional. The Mirror function juts mirrors the Git Repo and nothing else.

**Comment by Aetherinox** [comment]
Went searching a bit deeper, appearntly this has been requested multiple times and one PR is currently in place to take care of it (I think).

- #25112
- #18369
- #20311

Hopefully taken care of soon, this is a huge thing.

**Comment by techknowlogick** [comment]
Merging into linked issue
