### ISSUE TITLE
repository.upload config  dont work

### ISSUE THREAD

**Issue by Zhe28** [go-gitea/gitea#28016]
### Description

this is my app.ini config.

![image](https://github.com/go-gitea/gitea/assets/87906539/22308402-c174-45c3-9334-3af686cea529)

and restart software, it shows that

![image](https://github.com/go-gitea/gitea/assets/87906539/733ba08b-24eb-49ff-a472-9cb09a7dfffc)

the console dont report any error log. i miss something ? 

### Gitea Version

1.20.5

### Can you reproduce the bug on the Gitea demo site?

Yes

### Git Version

git version 2.41.0.windows.3

### Operating System

windows 23H2

### How are you running Gitea?

i download it from github .  run new-item command to start it on windows

### Database

SQLite

**Comment by lng2020** [comment]
fixed by https://github.com/go-gitea/gitea/pull/27985 in 1.21 and later. But I didn't backport to 1.20.x because there is no error toast. Probably should use another alert form to inform user in 1.20.x.
