### ISSUE TITLE
Gitea does not link to line in source display

### ISSUE THREAD

**Issue by cmdntd** [go-gitea/gitea#28015]
### Description

I use "Reference in new issue" at a line in source. But its link just lead to "View rendered", in stead of that line in source.
How could I fix this? How could I set like link below?

```bash
# Link created from "reference in new issue"
/src/commit/acf7c554e56a23c46c8c4172d0a9beeffb2fe575/vi-ori.md#L10

# I checked. It is ok if I change link above like this:
/src/commit/acf7c554e56a23c46c8c4172d0a9beeffb2fe575/vi-ori.md?display=source#L10
```

### Gitea Version

1.20.5

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![nuomat](https://github.com/go-gitea/gitea/assets/1112881/acb885b9-f296-463c-8c4a-419fa4d1ca76)

### How are you running Gitea?

Docker

### Database

MySQL/MariaDB

**Comment by KazzmanK** [comment]
When I read you Issue, I wondered that this trick would draw a piece of code, like it is in Review or Github. 
Instead , in Issue it is 

![image](https://github.com/go-gitea/gitea/assets/13328513/b7e97e49-e991-4c0a-8115-62beb247e14d)

**Comment by cmdntd** [comment]
Yes. I hope for new repo.

**Comment by yp05327** [comment]
Fixed by #26364

**Comment by KazzmanK** [comment]
> Fixed by #26364

I`ve checked in 1.21.9 and see no changes in Issues

![image](https://github.com/go-gitea/gitea/assets/13328513/f8846d44-924d-4d18-b5ef-46973be41983)

I was expecting not breaking list at least, at most - a part of referenced file embedded into comment

**Comment by yp05327** [comment]
I'm sorry. I have simply tested and it seems that it was fixed so I closed this issue.
Can you provide your approach to reproduce this issue?

**Comment by wxiaoguang** [comment]
I have fixed it, and it has a much better UI now.


https://demo.gitea.com/wxiaoguang/test1/issues/1

![image](https://github.com/user-attachments/assets/34b01d1d-727f-4ae8-86fa-9da19204563d)

https://demo.gitea.com/wxiaoguang/test1/issues/2

![image](https://github.com/user-attachments/assets/a4e84311-5768-4d08-beaf-6ab84001bef7)
