### ISSUE TITLE
Unable to Add SMTP Authentication Source

### ISSUE THREAD

**Issue by mohammed90** [go-gitea/gitea#2802]
- Gitea version (or commit ref): 1.2.2
- Git version: 
- Operating system: Darwin
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant

## Description

When trying to add a new authentication source, select `OAuth2` then change it to SMTP. Trying to add an SMTP authentication source after so gives no response. Checking the Chrome console, I found the following error logs:

```
An invalid form control with name='oauth2_key' is not focusable.
An invalid form control with name='oauth2_secret' is not focusable.
```

It seems to happen with all options. This only happens after the user select OAuth2 then change their mind.

**Comment by lafriks** [comment]
Fixed by #2889
