### ISSUE TITLE
Support skipping Gitea Action workflows [ci skip] [no ci] ...

### ISSUE THREAD

**Issue by jacksgt** [go-gitea/gitea#28020]
### Description

Hello, thanks everyone for the awesome Gitea Actions feature!

GitHub Actions (and many other CI tools, too) has a feature that allows the user to skip running CI when a particular keyword is part of the commit message.
GitHub documentation: https://docs.github.com/en/actions/managing-workflow-runs/skipping-workflow-runs

> You can skip workflow runs triggered by the `push` and `pull_request` events by including a command in your commit message:  
>    [skip ci]
>    [ci skip]
>    [no ci]
>    [skip actions]
>    [actions skip]

It seems that this is currently not supported by Gitea (can anyone else confirm this?).
Short term, it should be added to the list of Unsupported features: https://docs.gitea.com/next/usage/actions/comparison
Medium term we should of course implement this feature.

### Gitea Version

1.20.5

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

![Screenshot 2023-11-13 at 16-56-33 blog](https://github.com/go-gitea/gitea/assets/11589682/69b1f5ee-aa7f-4a7c-aeb4-8a31a02d31ee)

### How are you running Gitea?

Gitea Helm chart version 9.5.1: https://gitea.com/gitea/helm-chart/

### Database

MySQL/MariaDB

**Comment by jacksgt** [comment]
I believe the check should be implemented here: https://github.com/go-gitea/gitea/blob/79394b340d227182f94bae48cb08a091c78f2ea2/modules/actions/workflows.go#L211

**Comment by JhonyGabriel** [comment]
@lunny, following the thread, in my workflows, 
at version 1.21, auto-cancellation of simultaneous jobs was implemented if the type event is push, like described in issue #25716. I would like to suggest that when using [ci skip] on the commit message, the running jobs will are not cancelled at all.

**Comment by denyskon** [comment]
@JhonyGabriel It should already work that way. The skip ci check happens before the auto-cancellation, so running workflows are not being cancelled if there's a skip ci string in the commit
