### ISSUE TITLE
Tags not visible after upgrade to 1.20.5

### ISSUE THREAD

**Issue by dawnstrider** [go-gitea/gitea#28043]
### Description

I am trying to migrate from GOGS to GITEA. I have successfully taken all data, migrated to 1.0.2, then upgraded all the way to 1.19.4. I did "doctor recreate-table" with 1.19.4 to fix the table issues from previous versions.

Now, when I upgrade to 1.20.5, my repos loose all their tags in the UI. They are still there when i do a checkout, but not visible in the UI anymore.

### Gitea Version

1.20.5

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

Self-hosted on Ubuntu with the binary file.

### Database

None

**Comment by JakobDev** [comment]
The tags are read from the database. Have you tried to push with the tags to the repo, to maybe trigger Gitea to add the branches to the database? I think this should also be added to the Admin dashboard.

**Comment by dawnstrider** [comment]
Thanks for the hint. I found a solution with your remark:

To populate the "releases" table, which seems to be used for the tags since 1.20.x, I need to run "_gitea-.... admin repo-sync-releases_" which will put all tags into the releases table.

Afterwards, the tag list is updated again on the UI.
