### ISSUE TITLE
branch does not exist

### ISSUE THREAD

**Issue by AuspeXeu** [go-gitea/gitea#28056]
### Description

```
2023/11/14 18:18:16 ...s/web/repo/branch.go:58:Branches() [E] LoadBranches: branch does not exist [repo_id: 158 name: master]
2023/11/14 18:18:58 ...s/web/repo/branch.go:58:Branches() [E] LoadBranches: branch does not exist [repo_id: 158 name: master]
```
Only shows `1` but I have `2` branches in the repo, one of which is called `master`.

![image](https://github.com/go-gitea/gitea/assets/2115696/3006c5a2-4204-4ef3-bf0a-fddf0203f356)

### Gitea Version

1.21.0

**Comment by lunny** [comment]
Please run sync branches on admin panel as a workaround.

**Comment by AuspeXeu** [comment]
That worked. Thanks.

**Comment by yinheli** [comment]
Thanks, It works

**Comment by chnorton** [comment]
Is there any information on what the cause of this is? Appreciate that there's a workaround when it happens, but it's pretty concerning that information is just being lost from the database.

**Comment by lunny** [comment]
I think it's a bug. It's possible after the upgrade, user haven't visit the repository UI but push something first. The pushupdate functions haven't check and do a sync and directly add a new branch, then the sync will never be triggered.

**Comment by dongfo** [comment]
how to fix lost data?

**Comment by lunny** [comment]
> how to fix lost data?

https://github.com/go-gitea/gitea/issues/28056#issuecomment-1811664310
