### ISSUE TITLE
pulls/issue page very slow with >19000 repos

### ISSUE THREAD

**Issue by somera** [go-gitea/gitea#28055]
### Description

On my gitea instance with 19000 repositories and 3200 ogas the pulls page need

![image](https://github.com/go-gitea/gitea/assets/8334250/ad41aa05-bac5-456b-bc15-b82e4c1cae4f)

in 1.20.5 it was fast.

Possible SQL query changes.

### Gitea Version

1.21.0

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

2.42.0

### Operating System

Ubuntu 20.04.x

### How are you running Gitea?

gitea-1.21.0-linux-amd64

### Database

PostgreSQL

**Comment by somera** [comment]
In older gitea versions I reported some performance issues with many repos/mirrors and orgas. ;)

I try to analyse which query is the problem here.

**Comment by somera** [comment]
I see
```
==> gitea.log <==
2023/11/14 17:45:15 ...eb/routing/logger.go:68:func1() [W] router: slow      GET /pulls for xx.xx.xx.xx:0, elapsed 3047.5ms @ user/home.go:329(user.Pulls)
```
and this
```
gitea.log:2023/11/14 17:51:40 ...sues/issue_search.go:499:IssueIDs() [I] [SQL] SELECT count(*) FROM "issue" INNER JOIN "repository" ON "issue".repo_id = "repository".id WHERE issue.repo_id=$1 AND (issue.is_closed=$2) AND (issue.is_pull=$3) [7954 false true] - 958.121µs
gitea.log:2023/11/14 17:51:40 ...sues/issue_search.go:499:IssueIDs() [I] [SQL] SELECT "issue".id FROM "issue" INNER JOIN "repository" ON "issue".repo_id = "repository".id WHERE issue.repo_id=$1 AND (issue.is_closed=$2) AND (issue.is_pull=$3) ORDER BY "issue"."updated_unix" DESC, "issue"."created_unix" DESC, "issue"."id" DESC [19500 false true] - 1.283654ms
```
is the problem:
```
$ grep "sues/issue_search.go:499:IssueIDs()" gitea.log | wc -l
38280
```
38280 queries on my instance for the pulls page. Wow.

**Comment by KazzmanK** [comment]
what is the use for `join `here? Just to be sure what issue is still referenced by existing repo? 
looks like repository join can easily be dropped here.

**Comment by somera** [comment]
I have no issues in my gitea instance. I have a lot of mirrors and for some projects I'm using pull requests. At the moment all pull requests are closed.

The question is, why the change in 1.21.0? Why the new two selets for every repository?

**Comment by somera** [comment]
the design here is wrong.

When I have no issues but 1000000 project, then you check for every project; "is there an issue".

**How did you come up with the idea of doing it like that?**

**Comment by somera** [comment]
No issues but ~39000 SQL queries.

![image](https://github.com/go-gitea/gitea/assets/8334250/3147528a-c73d-4fbb-829b-c31f9c60b68e)

**Comment by lng2020** [comment]
> Or how much queries will be made if there are 2000 issues/pulls?
We refactor the search engine here to support multiple engines, such as melisearch, es, etc. But when using the default db engine, it indeed somehow includes some duplicate search. I notice this abnormal behavior too.

**Comment by somera** [comment]
It's possible to fix this in 1.21.1?

**Comment by somera** [comment]
@delvh will this be not fixed? Or not fixed in 1.21.1?

**Comment by somera** [comment]
I sav whis was removed from 1.21.1

This is the time for issues page (with no existing issues) with 1.21.1

![image](https://github.com/go-gitea/gitea/assets/8334250/b359785b-079a-4476-9bdc-4cb13e2579e2)

**Comment by somera** [comment]
Any updates here? Will this be fixed?

If yes -> in which release?

If not -> why not?

**Comment by lng2020** [comment]
> If not -> why not?
 
AFAIK, no one is working on it.

**Comment by somera** [comment]
Sounds not good. You changed the process. Cause with no issues and closed pull requests my Gitea instance needs 26-30 seconds.

**Comment by somera** [comment]
I'm using my gitea instance only with one user. I have 19200 repos and ~3100 orgas.

Issues
![image](https://github.com/go-gitea/gitea/assets/8334250/c04074c5-7664-4ffd-a2e3-2463fcfa1e77)

Pull-Requests
![image](https://github.com/go-gitea/gitea/assets/8334250/c8aefac4-5931-49bc-a0f5-343967dc0286)

My question is, why the design is so?

When I take a look on my case. No isues, but the indexer is checking all repos? And all my Pulls are closed. Means, the side should be just loaded. If I open the 310 closes pull-requests, the details will be loaded.

**Comment by somera** [comment]
And with 1.20.x I saw the pull request when I open the pull-requests tab. There was no problems and it needed ~500ms.

**Comment by wolfogre** [comment]
@somera I fully understand your question, but I cannot explain it in a few sentences. If you want to understand the whole story, you need to read

- #26012
- #28304

Or, you may simply hope that the problem can be resolved. Please wait patiently.

**Comment by somera** [comment]
I can't reopen it.

This is how it looks like in 1.21.2 -> with the fix.

![image](https://github.com/go-gitea/gitea/assets/8334250/66c6721c-5c2f-4dec-8c3c-4a635a7fdeba)

Nothing changes.

I don't understand why so much queries to show TWO open pull requests and just show the number with 338 closed pull requests.

**Comment by wolfogre** [comment]
@somera It hasn't been backported to v1.21.2 because it's breaking, see https://github.com/go-gitea/gitea/pull/28385#issuecomment-1849369514

Could you please try the latest nightly version? Or you can wait for v1.22.
