### ISSUE TITLE
Caching issue is back

### ISSUE THREAD

**Issue by somera** [go-gitea/gitea#28057]
### Description

I see this
`2023/11/14 18:23:54 models/db/context.go:178:GetByBean() [I] [SQL] SELECT "id", "setting_key", "setting_value", "version", "created", "updated" FROM "system_setting" WHERE "setting_key"=$1 LIMIT 1 [revision] - 639.796µs`
when I go to my profile and start page.

I'm using memcached.

Looks like #22281

### Gitea Version

1.21.1

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

2.42.0

### Operating System

Ubuntu 20.04.x

### How are you running Gitea?

gitea-1.21.0-linux-amd64

### Database

PostgreSQL

**Comment by lunny** [comment]
How many times the query occupied?

**Comment by somera** [comment]
3376 times.

**Comment by wxiaoguang** [comment]
-> Fix system config cache expiration timing #28072

**Comment by somera** [comment]
> Do you have the full log?

Do you still need that?

**Comment by wxiaoguang** [comment]
> > Do you have the full log?
> 
> Do you still need that?

Not needed now, thank you very much!

**Comment by somera** [comment]
@wxiaoguang why is the query (in my case 3228 times)

```
2023/11/15 18:50:28 models/db/context.go:178:GetByBean() [I] [SQL] SELECT "id", "setting_key", "setting_value", "version", "created", "updated" FROM "system_setting" WHERE "setting_key"=$1 LIMIT 1 [revision] - 984.36µs
2023/11/15 18:50:28 models/db/context.go:178:GetByBean() [I] [SQL] SELECT "id", "setting_key", "setting_value", "version", "created", "updated" FROM "system_setting" WHERE "setting_key"=$1 LIMIT 1 [revision] - 561.283µs
2023/11/15 18:50:28 models/db/context.go:178:GetByBean() [I] [SQL] SELECT "id", "setting_key", "setting_value", "version", "created", "updated" FROM "system_setting" WHERE "setting_key"=$1 LIMIT 1 [revision] - 635.435µs
2023/11/15 18:50:28 models/db/context.go:178:GetByBean() [I] [SQL] SELECT "id", "setting_key", "setting_value", "version", "created", "updated" FROM "system_setting" WHERE "setting_key"=$1 LIMIT 1 [revision] - 634.959µs
```
needed on the http://domain/git/org/orgname/dashboard page for every orga? For the orga list?

**Comment by wxiaoguang** [comment]
Because the "cache time" is not updated correctly, it is a bug. That's why https://github.com/go-gitea/gitea/pull/28072 fixes it.

**Comment by somera** [comment]
@wxiaoguang I know that this is fixed. But I try to understand why so much queries are needed on the Dashboard page for an orga. But it make no sense to show the orga list on the dashboard page.

**Comment by wxiaoguang** [comment]
> But I try to understand why so much queries are needed on the Dashboard page for an orga

The avatar module needs to read system settings to decide how to render an avatar. 1.21 contains an enhancement for the setting system, it brings the bug: the system setting revision was read again and again.

**Comment by somera** [comment]
Now the start page need

![image](https://github.com/go-gitea/gitea/assets/8334250/577ffec2-ed41-4ea0-8f49-c54aec5e557f)

Looks good.
