### ISSUE TITLE
Add edit option to root of repo for README.md

### ISSUE THREAD

**Issue by allthedoll** [go-gitea/gitea#28059]
### Feature Description

I think it would be great if Gitea had the ✏️ icon to edit the `README.md` file from the root of the repository (the `Files` tab). At present, you must actually click on the `README.md` file to get the edit option.

I asked about this in [Discord](https://discord.com/channels/322538954119184384/977026554909581334/1171857288454213675).

### Screenshots

- `Files` tab with missing edit option highlighted with red box
  <img width="1241" alt="missing-edit-option" src="https://github.com/go-gitea/gitea/assets/5758031/bdddf984-8757-4908-b25c-26277829a6db">

- Edit option available once you click into the `README.md` file
  <img width="515" alt="edit-option-available" src="https://github.com/go-gitea/gitea/assets/5758031/fee695ec-6127-403a-84e2-38d4bf7cd1f2">

- Example of edit option being available at root of the repo on GitHub
  <img width="879" alt="GitHub-example" src="https://github.com/go-gitea/gitea/assets/5758031/71a50fa2-48d2-465a-8ac7-d3c8e36adaf5">

**Comment by JakobDev** [comment]
This one should be easy to done in just a few minutes. I will create a PR.
