### ISSUE TITLE
Gitea using two ports

### ISSUE THREAD

**Issue by ware32** [go-gitea/gitea#28066]
### Feature Description

It could be possible to gitea could listen on two ports?
Our local server listens in 3000 port https://mylocalserver.domain.com:3000, but we need to change it to https://mylocalserver.domain.com and the oldest url (port 3000) continues working.
¿Could be possible by modifying app.ini?

thanks

**Comment by lunny** [comment]
I don't think Gitea side should support that.

**Comment by yp05327** [comment]
You can install Nginx or Apache and set listening 2 ports (or more) in the config file.
Then set pushing all requests from these 2 ports to your local Gtiea service which you already have.
Notice that you should modify the default port of your local Gitea service, 
as the default port 3000 in Gitea will be used by Nginx or Apache.
