### ISSUE TITLE
$ in math `\text{}` doesn't render

### ISSUE THREAD

**Issue by nschloe** [go-gitea/gitea#28070]
### Description

MWE:

```markdown
$\text{$b$}$
```

Gitea output:

![screenshot_2023-11-15-100633](https://github.com/go-gitea/gitea/assets/181628/103b847e-71c7-4d77-b8bf-fc7b7540edf3)

Native KaTeX output:

![screenshot_2023-11-15-100651](https://github.com/go-gitea/gitea/assets/181628/be1d1dfb-0215-4a09-91b8-45daf1c80cb9)

This is _not_ an issue with bracket delimiters

````markdown
\(\text{$b$}\)
\[
\text{$b$}
\]
```math
\text{$b$}
```
````

![screenshot_2023-11-17-081825](https://github.com/go-gitea/gitea/assets/181628/a737f665-1151-494e-a401-02b7f52f385d)

(Except for the fact `math` code blocks don't center the math, cf. https://github.com/go-gitea/gitea/issues/27602.)

### Gitea Version

1.22.0+dev-326-gf65977df3

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

https://try.gitea.io/

### Database

None

**Comment by yp05327** [comment]
Reproduce:
![image](https://github.com/go-gitea/gitea/assets/18380374/88032504-abb4-4e12-986a-f9563f247aa6)
![image](https://github.com/go-gitea/gitea/assets/18380374/287ac112-c1e6-4c5f-848d-12e5630ddb6f)

![image](https://github.com/go-gitea/gitea/assets/18380374/3580f5c6-b355-46f4-81f2-dd4b2e9c6e7c)
![image](https://github.com/go-gitea/gitea/assets/18380374/a96fd0ee-3ec2-4457-87c0-723cc7be6614)
Then I removed all `$`, I got:
![image](https://github.com/go-gitea/gitea/assets/18380374/b26e34c9-8679-43a5-b00e-79333a0aeaa7)

In GitHub:
``` math
$\text{$b$}$
```
↓ code
![image](https://github.com/go-gitea/gitea/assets/18380374/f353fb46-b1b7-4dfb-9261-32eb9eba06a2)

**Comment by nschloe** [comment]
@yp05327 Your accidentally added too many `$` in the display-math example; it works fine there.

**Comment by yp05327** [comment]
Ah, I understanded this issue.

Do you mean that
```
$\text{$b$}$
```
and
![image](https://github.com/go-gitea/gitea/assets/18380374/5dba8dda-0d39-43f5-a344-02f5da07b9d9)

should have same result?

**Comment by nschloe** [comment]
Almost.

```
$\text{$b$}$
```

and

```
\(\text{$b$}\)
```

should give the same result.

**Comment by wxiaoguang** [comment]
Markdown is not a strict language, we we have no strict parser for it, it's impossible to guess which `$` is the real stop marker at the moment. GitHub doesn't render it either.


$\text{$b$}$


So, using non-ambiguity quotes like`\(\text{$b$}\)` is the best approach.

**Comment by wxiaoguang** [comment]
OK, managed to make it work by some small changes, will propose some new PRs to improve.

![image](https://github.com/user-attachments/assets/9600a4a8-e0af-486a-894e-b6fc82ad5028)

**Comment by wxiaoguang** [comment]
1.23 nightly is ready and I think it should have been fixed, feel free to take a try

![image](https://github.com/user-attachments/assets/2fc36145-a531-4d79-aa20-84531c387547)

**Comment by nschloe** [comment]
Confirmed fixed.
