### ISSUE TITLE
Using multiple action urls

### ISSUE THREAD

**Issue by vjarskee** [go-gitea/gitea#28076]
### Feature Description

For example, enter a variable `ACTIONS_URLS_QUEUE = self, https://github.com` that can be used to try to clone the action from self, and if unsuccessful, try to clone from github.com, and on the last failure throw error

**Comment by lunny** [comment]
Similar proposal has been posted but rejected.

**Comment by vjarskee** [comment]
> Similar proposal has been posted but rejected.

I couldn't find it, can you provide a link? Why was it rejected?

**Comment by lunny** [comment]
#24789
