### ISSUE TITLE
cant run gitea in 443 port

### ISSUE THREAD

**Issue by ware32** [go-gitea/gitea#28077]
### Description

I cant run gitea in 443 port, I have replaced 3000 in the app.ini file but no success.
¿is it not possible to change?

### Gitea Version

v1.20.5

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

Local server

### Database

None

**Comment by somera** [comment]
https://docs.gitea.com/installation/install-from-binary?_highlight=port#running-gitea-on-another-port

**Comment by techknowlogick** [comment]
Solved in chat. Pointed to doc re:setcap
