### ISSUE TITLE
1.21 Dashboard feed is too visually dense

### ISSUE THREAD

**Issue by Kwonunn** [go-gitea/gitea#28082]
### Description

After installing 1.21 I immediately noticed that the dashboard feed has become much more visually dense, which I find very tiring to look at.

I think the main culprits in this are the reduced margin/padding and the background boxes around the commit hashes.

I suspect I'm not the only one to dislike this, so I think it should be discussed here.

I would like to add that I am a fan of moving the timestamp to the first line.

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/39026963/44ae6b0a-ba3f-4eba-b6c7-b859965c63ef)

### Gitea Version

1.21

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

Linux x86_64

### Browser Version

Firefox

**Comment by lunny** [comment]
For background boxes around the commit hashes, I think maybe you have a custom theme? Maybe you need to change them on your theme.

**Comment by mpeter50** [comment]
For comparison, what do you think about the built-in dark theme's look? Do you also find that to be too dense?
It looks like this:

![image](https://github.com/go-gitea/gitea/assets/83356418/5173087c-80df-462a-89b9-4ec351545632)

I'm not a dev, so don't take this as an offer or something (it just bothers me a little too, but wouldn't have searched for it if I don't look for new issues before updating), but if so do you think more visible dividers or a minimum height for a section (which one?) would help?

Personally I think its better this way for those sections where there are multiple lines, but I see why 1-2 line sections can be bothering.

**Comment by Kwonunn** [comment]
I do have a custom theme, but even with the default arc-green I think it's quite 'busy' looking.

I'm not a UI expert, but the reason I think they look busy is because the blocks introduce extra lines for the eye to register when reading a line, and because they emphasize the commit hash which is not really the most important part of the Dashboard feed.

**Comment by Kwonunn** [comment]
> more visible dividers
I don't think increasing the opacity of the dividers would help much, instead I think just adding more margin around them would create a divider through negative space which is very easy to read quickly. (IMO at least, this might just be preference)

> minimum height
I would have to do some tests with this myself, I don't know if it would help. 

Thank you for your suggestions!

**Comment by silverwind** [comment]
Thoses lists use a shared template `flex-list` now, and it's the same density as the issue list. I guess one will get used to it, thought I also wouldn't mind re-designing the feed list to boxes with more padding, like github frontpage.

**Comment by silverwind** [comment]
Yes, I think we can de-emphasize the hashes in the UI and plan doing that at some point, so it will be part of https://github.com/go-gitea/gitea/issues/29641. As for this issue, I see nothing else to do.
