### ISSUE TITLE
Unable to pass PostgreSQL connection params

### ISSUE THREAD

**Issue by PKizzle** [go-gitea/gitea#28083]
### Description

With the recent changes in https://github.com/go-gitea/gitea/blame/79394b340d227182f94bae48cb08a091c78f2ea2/modules/setting/database.go#L160C6-L160C35 it is no longer possible to specify custom connection parameters like `binary_parameters=yes` by appending them to the `Database.Name`.
Instead of the actual parameters the parameter separator is passed to `getPostgreSQLConnectionString`.

### Gitea Version

v1.21.0

### Can you reproduce the bug on the Gitea demo site?

No - irrelevant since issue is configuration related

### How are you running Gitea?

Helm chart v9.5.1 on Kubernetes cluster v1.28.3

### Database

PostgreSQL

**Comment by lunny** [comment]
related #27723

**Comment by wxiaoguang** [comment]
->  Fix incorrect pgsql conn builder behavior #28085

**Comment by PKizzle** [comment]
I need to add this parameter in order to connect to the PostgreSQL database via pgbouncer.
 
My database is named `gitea` hence I set `NAME` to `gitea?binary_parameters=yes`.
