### ISSUE TITLE
Cannot access custom locale keys in 1.21

### ISSUE THREAD

**Issue by danparisd** [go-gitea/gitea#28081]
### Description

We use a custom en-US locale file, which has a custom section at the bottom and has a few sub items that are custom. Like this:

```
[wa]
footer_agreement = you agree
```

In 1.20 we accessed those values in our custom templates via `{{.locale.Tr "wa.footer_agreement"}}` for example. This worked fine in 1.20. In testing 1.21 these values are blank.

I tried changing to `{{ctx.locale.Tr "wa.footer_agreement"}}` but this doesn't work. I've looked at all the locale related commits in 1.21 that I could find and nothing is sticking out to me as being the cause here.

Gitea is definitely picking up our custom locale file because we have customized some of the gitea provided keys and our values are being displayed for those.

Please advise. I'm happy to troubleshoot or look at the code if someone can point me in the right direction.

### Gitea Version

1.21

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

running in Docker rootless. Building a custom image with the customizations loaded in the build.

### Database

MySQL/MariaDB

**Comment by wxiaoguang** [comment]
`ctx.Locale.Tr`

* #27231
* #27856

**Comment by danparisd** [comment]
Oh wow, I didn't notice the capitalization change. I got it working.

This should be listed as a breaking change in the blog post.

**Comment by danparisd** [comment]
I made a PR for the blog

https://gitea.com/gitea/blog/pulls/320
