### ISSUE TITLE
$GITHUB_OUTPUT not available between jobs

### ISSUE THREAD

**Issue by kristophercrawford** [go-gitea/gitea#28091]
### Description

I copied the workflow file from https://github.com/go-gitea/gitea/pull/24230 and ran this on my Gitea instance. The result of the jobs is captured below in screenshots.

<img width="892" alt="image" src="https://github.com/go-gitea/gitea/assets/32402434/f088fd5f-dd4b-4ec2-9f7e-30a3aab4ca86">

<img width="903" alt="image" src="https://github.com/go-gitea/gitea/assets/32402434/56c6a761-0e6b-4c5a-8027-6ebd023179a0">

### Gitea Version

 1.21.0+rc2-55

### Can you reproduce the bug on the Gitea demo site?

Yes

### Git Version

2.30.2

### Operating System

Ubuntu 22.04

### How are you running Gitea?

Pre-compiled binary for arm64 on an Orange Pi 5, running through systemd (gitea and act_runner).

### Database

MySQL/MariaDB

**Comment by lng2020** [comment]
That workflow file doesn't work for me either.

**Comment by ednxzu** [comment]
Same thing, 
I opened an issue [here](https://gitea.com/gitea/act_runner/issues/428) because I'm not sure whether it is a gitea or act runner problem.

**Comment by yp05327** [comment]
I know the reason.
I think this was fixed by https://github.com/go-gitea/gitea/pull/28149

The output results will be saved in DB, but before this fix, the target table does not exsit.
So try the latest version, or add this table by yourself, can fix this issue.

**Comment by ednxzu** [comment]
Yup, moving to 1.21.1 worked for me. Thanks for looking into it. @kristophercrawford are you still having the issue ?

**Comment by kristophercrawford** [comment]
No change after updating to Gitea version 1.21.1. Where is the `gitea.db` file located? I am using the compiled binary installation file on a physical machine running MySQL as the backend database.

<img width="1612" alt="image" src="https://github.com/go-gitea/gitea/assets/32402434/862d630a-adac-4324-8125-8ddd19c379f7">

**Comment by kristophercrawford** [comment]
Here is what I am seeing on the db side:

```sql
MariaDB [gitea]> describe action_task_output;
+--------------+--------------+------+-----+---------+----------------+
| Field        | Type         | Null | Key | Default | Extra          |
+--------------+--------------+------+-----+---------+----------------+
| id           | bigint(20)   | NO   | PRI | NULL    | auto_increment |
| task_id      | bigint(20)   | YES  | MUL | NULL    |                |
| output_key   | varchar(255) | YES  |     | NULL    |                |
| output_value | mediumtext   | YES  |     | NULL    |                |
+--------------+--------------+------+-----+---------+----------------+
4 rows in set (0.002 sec)

MariaDB [gitea]> select * from action_task_output\G
*************************** 1. row ***************************
          id: 1
     task_id: 822
  output_key: output2
output_value: 8c8c7b6b-ef4b-45bb-a87c-5613a3e9c224
*************************** 2. row ***************************
          id: 2
     task_id: 822
  output_key: output1
output_value: 2023-11-29T12:17:08+00:00
2 rows in set (0.001 sec)

MariaDB [gitea]>
```

No errors in the `gitea.log` after upgrading to 1.21.1. The log message here is from before the upgrade.

```
root@dev-pi:/var/lib/gitea/log# grep '\[E\]' gitea.log
2023/11/29 12:08:05 ...ions/runner/utils.go:45:pickTask() [E] Cannot find needs for task 821: FindTaskOutputByTaskID: Error 1146 (42S02): Table 'gitea.action_task_output' doesn't exist
```

**Comment by kristophercrawford** [comment]
Fresh install of 1.21.1 works on bare metal, upgrading from 1.21.0+rc2-55 to 1.21.1 is what didn't work for me.

**Comment by yp05327** [comment]
Fresh install `1.21.0+rc2`, run the workflow, it don't work. Then upgrade it to `1.21.1`, rerun the workflow, it worked.
Tried both Mysql 8.0.28 and Sqlite3. 😕

ps: I can only get `1.21.0+rc2` from `dl.gitea.com`, where did you get `1.21.0+rc2-55`?

**Comment by yp05327** [comment]
Thanks for your test and report. I think this information is helpful and important for us to detect the porblem.

**Comment by yp05327** [comment]
Which `ROOT_URL` (Gitea instance URL) when you register the runner?

**Comment by kristophercrawford** [comment]
I have tried setting act_runner to use 127.0.0.1:3000, 192.168.10.88:3000, and my external domain. The only time I am seeing output in the job2 data is when I have the `ROOT_URL` set to the internal IP of 192.168.10.88:3000.

**Comment by kristophercrawford** [comment]
Actually, disregard all of what I said. I was only selecting re-run all jobs after changing my `ROOT_URL` and observing no in output in the job2 data. I believe what I am observing now is a different bug.

If I switch the `ROOT_URL` to the external domain and make a new change and commit to the repo, I see output in job2 data as expected.
