### ISSUE TITLE
1.21 broke Linux EOL in code editor

### ISSUE THREAD

**Issue by testdasi** [go-gitea/gitea#28097]
### Description

Updated to 1.21 and now any change via web editor always use Windows EOL, quite possibly because the browser itself runs in a Windows PC.

The stupid part is the editor itself successfully detected these are bash scripts, which must be Linux!
I can't find any documentation on how to permanently use Linux EOL so now I'm stuck.

Tried revert back to 1.20 and of course gitea blocked it too.

### Gitea Version

1.21

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

Gitea docker on Ubuntu.
Browser access on Windows PC.

### Database

None

**Comment by silverwind** [comment]
> any change via web editor always use Windows EOL, quite possibly because the browser itself runs in a Windows PC.

That should not be the behaviour I tested. Do you have a `.editorconfig` file in the repo? If not, it should use LF already, the browser OS is not part of the detection in the Monaco editor, as far as I'm aware. It should give you LF when no .editorconfig is present.

**Comment by silverwind** [comment]
@testdasi please let me know what [this](https://microsoft.github.io/monaco-editor/playground.html?source=v0.44.0#XQAAAAIUAQAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscpr6MsNg4vHoYKiujoNF7STKsikuAnq3yOVCHCMPueylLD-VoHOlF3w7elBXLBzOq_Ka4_q7xdHjgZ816TR650ms14N1DvUJ2VMmrE3JxsFVAsJ10g4GoLDneKIarapH9FeS22-0LgGuPBqc3r1bW7Od_iiAuh-FUMe9Z2G5BzBa5XwOHj9peFGELupDprrG1qY93NKtI4K6VZhrmmh8QpXP6vk2o) displays on your affected machine:

<img width="96" alt="image" src="https://github.com/go-gitea/gitea/assets/115237/ed14746d-8e4f-4a51-b8a6-8b3ac8632582">

**Comment by testdasi** [comment]
It's "\r\n" for both Chrome and Firefox.
![image](https://github.com/go-gitea/gitea/assets/51292604/e191a2ad-3384-4bdf-9f22-aba923484058)

**Comment by silverwind** [comment]
Interesting, so Monaco seems to use OS defaults for files without a dominant ending. I think we should default it to `\n` but have a config option in case someone wants to change this default.
