### ISSUE TITLE
Cannot delete a user token

### ISSUE THREAD

**Issue by dapepin** [go-gitea/gitea#28092]
### Description

Deleting a user token with a different one (an admin account for examples), may end up in failure (404 in my case).

### Gitea Version

1.21.0

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

linux

### How are you running Gitea?

Self-hosted, dockerized.

### Database

PostgreSQL

**Comment by dapepin** [comment]
Duplicate of  #27598 
Please backport ae419fa49403537725c806a5f3f1e5b274f52eb7 to the 1.21 branch

**Comment by lng2020** [comment]
Closed as the backport #28099 is merged
