### ISSUE TITLE
Is there a way to disable "Clone in VSCode"

### ISSUE THREAD

**Issue by haq1an** [go-gitea/gitea#28108]
### Description

This might not be categorized as "Bug", but I couldn't find a more proper type.

I'm looking for a way to disable "Clone in VSCode".

I tried enable "DISABLE DOWNLOAD_SOURCE_ARCHIVES" in the app.ini, but it just deleted all the other options but the vscode one. Also, I don't think this parameter actually blocks http/ssh request, correct me if I'm wrong. Cuz I find that the vscode option calls local vscode app, hence I couldn't do anything on the network level to deny it. Even if the button is gone, users can still trigger it if they know the uri. 

Is there a parameter I was missing that can achieve what I'm trying to do? Or which part of the source code I should be looking for to make it happen?

### Gitea Version

1.19.2

### Can you reproduce the bug on the Gitea demo site?

Yes

### Git Version

2.25

### Operating System

Ubuntu 20.04

### How are you running Gitea?

Installed by binary.

### Database

PostgreSQL

**Comment by lng2020** [comment]
I don't think there is an option because it's hard-coded. You can remove that `js-clone-url-vsc` line.
https://github.com/go-gitea/gitea/blob/247927a9b51cea88db6f7d2dee25471339feb51b/templates/repo/home.tmpl#L133-L143

**Comment by haq1an** [comment]
> I don't think there is an option because it's hard-coded. You can remove that `js-clone-url-vsc` line.
> 
> https://github.com/go-gitea/gitea/blob/247927a9b51cea88db6f7d2dee25471339feb51b/templates/repo/home.tmpl#L133-L143

This is what I've done so far.

Just to add a bit background story here:
Our dev team is trying to secure the our code without effecting too much user experience. So I put the gitea server in our bastion network, allowing port 3000 traffic only for webui access, and I disabled downloading use app.ini. Therefore, user can only get access(clone/download) codes within the bastion network with authentication and audit.(I understand that it's more of a low-hanging fruit situation, like user can still do copy/paste.)

So as you can see, the vscode clone function doesn't really fit my design and I can do very little thing about it since it's hardcoded and not manageable on the network level. So it might be nice to add a switch to this feature in the future release. 

But still, thanks for the frontend solution.

**Comment by lafriks** [comment]
This should not be created as option in app.ini if this only for customizing UI. This can be already be implemented by adding custom css:

```css
.js-clone-url-vsc { display: none }
```

**Comment by mstup** [comment]
I would vote to add this possibility to control it in **app.ini** file.
