### ISSUE TITLE
1.21 Statistical error. type/bug

### ISSUE THREAD

**Issue by jobo-zt** [go-gitea/gitea#28116]
### Description

Modifying a file online for the first time (102 lines in total) only adds a space, resulting in statistical errors. Co-ownership1 file has been changed Including 102 insertions and 102 deletions

### Gitea Version

1.21

### Can you reproduce the bug on the Gitea demo site?

Yes

### Git Version

internal

### Operating System

win10

### How are you running Gitea?

./gitea web

### Database

SQLite

**Comment by techknowlogick** [comment]
Thanks. This is due to a line ending bug in 1.21.0 and aPR has been submitted and needed to fix that will be available in the next minor release
