### ISSUE TITLE
[UX issue] File edit auto-complete shouldn't interfere with typing and instead use a shortcut like shift+enter

### ISSUE THREAD

**Issue by ell1e** [go-gitea/gitea#28114]
### Description

The file edit auto-complete shouldn't interfere with typing and use a shortcut like shift+enter. Auto-completing on enter is a fundamentally disruptive and kind of destructive default, because I may simply want to enter a new line. This is even worse with more free form files like markdown files, where Gitea currently seems to have an autocomplete active, where the suggestions are going to be generally very unhelpful, very random, and I'm way more likely to want to enter a new line than pick any of the auto-complete suggestions.

To make it more discoverable, simply add the shortcut to the popup after changing it to something more sane like shift+enter, like this:

![Screenshot from 2023-11-18 17-21-18](https://github.com/go-gitea/gitea/assets/64124388/8ef2c7b7-2937-484c-9859-0d925f0b7c57)

### Screenshots

Pressing enter here should enter a new line, not write "This" twice:
![Screenshot from 2023-11-18 17-21-17](https://github.com/go-gitea/gitea/assets/64124388/7227d9e8-4a71-4bd4-aeba-efda1da80435)

### Gitea Version

 1.22.0+dev-334-ge88377470

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

Linux

### Browser Version

Firefox 120.0b9

**Comment by silverwind** [comment]
> To make it more discoverable, simply add the shortcut to the popup after changing it to something more sane like shift+enter

https://github.com/go-gitea/gitea/pull/30548 fixes this. Tab key is to complete suggestions 😉.
