### ISSUE TITLE
migration from Github fails: You are not allowed to import local repositories.

### ISSUE THREAD

**Issue by jxsl13** [go-gitea/gitea#2811]
- Gitea version (or commit ref): d545e32 (docker)
- Git version: 2.13.5
<img width="867" alt="bildschirmfoto 2017-10-31 um 14 15 27" src="https://user-images.githubusercontent.com/371944/32225832-0f854082-be47-11e7-9c68-3b8204bfc4f2.png">
<img width="865" alt="bildschirmfoto 2017-10-31 um 14 20 43" src="https://user-images.githubusercontent.com/371944/32225833-0fa00110-be47-11e7-80cb-558fb0a557fd.png">

- Operating system: debian 8
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:
nothing suspicious in logs
## Description

I try to migrate a private github repo, which should be called the same as I want to call it.

## Screenshots
<img width="867" alt="bildschirmfoto 2017-10-31 um 14 15 27" src="https://user-images.githubusercontent.com/371944/32225880-32392ec2-be47-11e7-9150-d7b48c9ef1f1.png">
<img width="865" alt="bildschirmfoto 2017-10-31 um 14 20 43" src="https://user-images.githubusercontent.com/371944/32225881-3253dd80-be47-11e7-8aa2-e6f4092d80de.png">

**Comment by lafriks** [comment]
GitHub does not support ssh authorization with username/password

**Comment by lafriks** [comment]
Use GitHub https:// url
