### ISSUE TITLE
MySQL/MariaDB: Unique Constraint on Branches doesn't respect casing: UQE_branch_s

### ISSUE THREAD

**Issue by sebastian-sauer** [go-gitea/gitea#28131]
### Description

In a repo with two branches `feature/test_case` and `feature\Test_Case` gitea throws a 500 exception when syncing branches as the unique constraint is violated.

`SyncRepoBranches: Error 1062 (23000): Duplicate entry '<redacted_branch_name>' for key 'UQE_branch_s'`

This error happened after an upgrade to 1.21.0 on an existing repo.

Workaround is to rename one of the branches.

Typically having this type of different branch names only based on casing is not needed (imho it's a bug ;) ) - but we shouldn't have a 500 page when accessing the repo.

### Gitea Version

1.21.0

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

Linux

### How are you running Gitea?

Official binary

### Database

MySQL/MariaDB

**Comment by yorliuk** [comment]
I got the same error in Gitea log after updating to 1.21. 
`...dules/context/api.go:105:ServerError() [E] SyncRepoBranches: Error 1062 (23000): Duplicate entry '<BRANCH_NAME>' for key 'branch.UQE_branch_s'`

But I can't find such branch in DB.
`mysql  Ver 8.0.28 for Linux on x86_64 (MySQL Community Server - GPL)`

**Comment by silverwind** [comment]
Related: https://github.com/go-gitea/gitea/issues/25909

**Comment by sebastian-sauer** [comment]
Are we "allowed" to remove a unique constraint in a patch release?

**Comment by yorliuk** [comment]
> I got the same error in Gitea log after updating to 1.21. `...dules/context/api.go:105:ServerError() [E] SyncRepoBranches: Error 1062 (23000): Duplicate entry '<BRANCH_NAME>' for key 'branch.UQE_branch_s'`
> 
> But I can't find such branch in DB. `mysql Ver 8.0.28 for Linux on x86_64 (MySQL Community Server - GPL)`

It helped: https://github.com/go-gitea/gitea/issues/25909#issuecomment-1637254581

**Comment by silverwind** [comment]
> Are we "allowed" to remove a unique constraint in a patch release?

Anything reasonable is possible, but I think the solution is to make the field case-sensitive.
