### ISSUE TITLE
Gitea Actions - Follow logs

### ISSUE THREAD

**Issue by kimdre** [go-gitea/gitea#28156]
### Feature Description

I would love to have the option to follow Action logs automatically when I view them while the job is running.

**Comment by nodiscc** [comment]
I think this is a duplicate of https://github.com/go-gitea/gitea/issues/25186.

Maybe the title of [this issue](https://github.com/go-gitea/gitea/issues/25186) should be changed to include `Follow logs` because that's the first thing I tried to search for when looking for this feature request.

> [Actions] Auto scroll feature ("Follow Logs")
