### ISSUE TITLE
After migration from 1.20.5 to 1.21.0  - lost some branches on multiple repos

### ISSUE THREAD

**Issue by olivier-med** [go-gitea/gitea#28158]
### Description

Upgraded to 1.21 (from 1.20.5) few days ago, but only today we notice that we lost access to some branches in multiple repo.

No error in gitea.log when going to a repo, excepted for some where the page is unavilable - Error 500
023/11/21 14:49:33 ...s/web/repo/branch.go:58:Branches() [E] LoadBranches: branch does not exist [repo_id: 176 name: master]

All branches are available using git command line.

Our gitea/git server host more than 300 repo with a lot of activity from many dev/testers/scientists (without trouble since ages).

### Gitea Version

1.21.0

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/68896554/1f026f8b-5b96-421e-8024-6223e7b03a27)

but in command line

![image](https://github.com/go-gitea/gitea/assets/68896554/f37d75f2-1c94-4632-8ce0-6bb1a6eedb38)

When no luck on some repo

![image](https://github.com/go-gitea/gitea/assets/68896554/39e736b8-83ce-4431-837e-9be48ef6ba63)

### Git Version

2.40.1 WP v2

### Operating System

Debian 10 + docker-ce 19.03.13

### How are you running Gitea?

Debian 10 + docker-ce 19.03.13
Official docker image 1.21.0
Postgres server using official docker image postgres:11.22-bullseye

### Database

PostgreSQL

**Comment by delvh** [comment]
https://discord.com/channels/322538954119184384/322538954119184384/1175359016919105597

**Comment by olivier-med** [comment]
Why discord ? and no chan there following your link.

**Comment by delvh** [comment]
![image](https://github.com/go-gitea/gitea/assets/51889757/c7f97964-77e3-4474-ba86-431e798ea0e2)

**Comment by olivier-med** [comment]
Thanks :)
