### ISSUE TITLE
High CPU Usage and Log Overflow with Frequent FetchTask Requests from Multiple Runners in Gitea Actions

### ISSUE THREAD

**Issue by yanhao98** [go-gitea/gitea#28165]
### Description

I am experiencing significant issues with Gitea Actions in a setup involving a large number of runners (60 machines). These runners are making requests to /api/actions/runner.v1.RunnerService/FetchTask at a very high frequency, which is leading to two major problems:

High CPU Usage on Gitea Server: The frequent requests from these numerous runners are causing an excessively high CPU usage on my Gitea server. This is concerning as it affects the overall performance and responsiveness of the server.

Log File Overload: My server logs are being overwhelmed with entries related to FetchTask. The sheer volume of these log entries is making it difficult to track other important logs and potentially masking other crucial information.

I am seeking guidance or a solution to mitigate these issues. Ideally, I am looking for a way to manage the frequency of these FetchTask requests or any other recommendation that could help in optimizing the performance and log management under such a scenario.

### Gitea Version

1.21.0

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

<img width="1521" alt="image" src="https://github.com/go-gitea/gitea/assets/37316281/ad2cd1a6-70ad-4c97-8fac-72afc135a4eb">
<img width="906" alt="image" src="https://github.com/go-gitea/gitea/assets/37316281/84f807f3-aa4c-45ae-bcfd-9a02509dddf9">

### How are you running Gitea?

docker

### Database

PostgreSQL

**Comment by wolfogre** [comment]
May be related to #24543.

**Comment by yanhao98** [comment]
> May be related to #24543.

Okay, I'll close this issue.
