### ISSUE TITLE
Save draft button unavailable for new releases

### ISSUE THREAD

**Issue by alissoncastanha** [go-gitea/gitea#28173]
### Description

After we update to 1.21.0, the save draft button is not available for new releases.

![image](https://github.com/go-gitea/gitea/assets/76269489/2266b88c-3658-4712-979f-b09346c9f654)

For draft releases saved before updating, the button is shown.

![image](https://github.com/go-gitea/gitea/assets/76269489/5b719e1f-b7ff-44ee-b994-2373e2867269)

### Gitea Version

1.21.0

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

CentOS 7

### How are you running Gitea?

We are running with CentOS 7 and systemd. The version was downloaded from https://dl.gitea.io/gitea/1.21.0/gitea-1.21.0-linux-amd64.

### Database

MySQL/MariaDB

**Comment by lng2020** [comment]
fix -> Fix missing buttons #28179
