### ISSUE TITLE
Attach files to release

### ISSUE THREAD

**Issue by JetpackDuba** [go-gitea/gitea#282]
Hello!
Basically the same as [this](https://github.com/gogits/gogs/issues/1614) Issue.
Imo this is a really necessary feature.

**Comment by couling** [comment]
I looked into this today and found that there is already a stub for it in that there is a column in the `attachment` table to reference a release.  It is ignored and there is nothing in the UI to use it.

**Comment by couling** [comment]
FYI. I'm working through this.  I'm new to this project so its taking me some time.

**Comment by appleboy** [comment]
@couling Can't waiting for your PR. 👍
