### ISSUE TITLE
cli installation

### ISSUE THREAD

**Issue by stephanfriedrich** [go-gitea/gitea#2820]
Hi 
iam using ansible to install gitea on my raspberrypi.
it would be nice if there is a way to install gitea not only via web-wizard but also via cli.

**Comment by Morlinest** [comment]
I think you can create `app.ini` file and admin user using ansible. Something as creating app.ini through docker env variables.

**Comment by stephanfriedrich** [comment]
thx for your reply, but i dont use docker. i use ansible with an plain raspberrypi server.

**Comment by aoyawale** [comment]
you can template `app.ini` and use get_url to download the binary and the init/systemd file.

**Comment by stephanfriedrich** [comment]
@jlozadad @Morlinest 
ah ok sorry, you are right.
its really simple i only need to create a `giteaUserPath/custom/conf/app.ini` with correct data and with that the server starts without wizard-configuration.
as you explained i created an admin account with `gitea admin` command


thx for your help, *maybe you should update or extend the gitea documentation*
