### ISSUE TITLE
Issue will be detected as PR when we check `First-time contributor`

### ISSUE THREAD

**Issue by yp05327** [go-gitea/gitea#28224]
### Description

![image](https://github.com/go-gitea/gitea/assets/18380374/6fedbe56-c4f6-4898-a6f5-9ad4ba26378d)
https://gitea.com/gitea/blog/issues/322

I will fix it later.

### Gitea Version

latest

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

gitea.com

### Database

None

**Comment by lng2020** [comment]
I thought it was on purpose. It kind of makes sense to me because creating an `issue` will count as a contribution to one's personal profile. Though GitHub doesn't consider this as `first-time-contributor`.
