### ISSUE TITLE
[1.21.1] Force initial configuration on existing conf 

### ISSUE THREAD

**Issue by mrdev023** [go-gitea/gitea#28229]
### Description

When i update to 1.21.1, it force to reconfigure gitea "Initial configuration". 
When i downgrade to 1.21.0, gitea work again

### Gitea Version

1.21.1

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

docker

### Database

SQLite

**Comment by neonmaus** [comment]
I can confirm that, it just happened to me too

**Comment by ghnp5** [comment]
Came here to say the same.
I'm using a subpath, e.g.  my.domain.com/git/  , in case it makes any difference.

Is there a fix for this yet?

(I'm going to rollback to the previous version now.)

**Comment by techknowlogick** [comment]
Sorry about this. There was a race condition with the release workflow that pushed the rootless image to latest. I've manually overwritten the latest tag with the appropriate information, and you can continue to pull latest now.

See #28230 for more details. Please re-open if a pull of latest doesn't resolve your issue.
