### ISSUE TITLE
JavaScript WARNING/ERROR: JavaScript promise rejection

### ISSUE THREAD

**Issue by somera** [go-gitea/gitea#28226]
### Description

I have this https://github.com/run-llama/llama_index mirror in my gitea. And Chrome/FF shows:

![image](https://github.com/go-gitea/gitea/assets/8334250/a841d82a-d96e-4dfb-8915-456e44b06c68)

On GitHub I can't see this Warning/Error.

### Gitea Version

1.21.0

### Can you reproduce the bug on the Gitea demo site?

Yes

### Git Version

2.43.0

### Operating System

Ubuntu 22.04.3 LTS x86_64

### How are you running Gitea?

gitea-1.21.0-linux-amd64

### Database

PostgreSQL

**Comment by somera** [comment]
I get same message for https://github.com/tensorflow/tensorflow

**Comment by wxiaoguang** [comment]
Please provide enough logs: "Open browser console to see more details"

----

Although there is no enough feedback, I could guess that it's caused by : Copy citation file content, in APA and BibTex format, on repo home page #19999  , the citation-js failed to parse some data in CITATION.cff

**Comment by somera** [comment]
@wxiaoguang as I write, t can be reproduce on try.gitea.io.

But ...

![image](https://github.com/go-gitea/gitea/assets/8334250/12e914c7-0ffa-4724-b17a-c0731f7c69ed)

**Comment by milkbrother666** [comment]
me too.
![image](https://github.com/go-gitea/gitea/assets/47425802/6c90dea9-49d8-4456-b22e-877374470abe)

**Comment by wxiaoguang** [comment]
They are different problems.

The author's problem is caused by #19999 when there is an invalid date in CITATION file.

The `getConfig/ClickToLoad` problem is highly likely caused by some buggy browser plugins/extensions.

**Comment by milkbrother666** [comment]
> They are different problems.
> 
> The author's problem is caused by #19999 when there is an invalid date in CITATION file.
> 
> The `getConfig/ClickToLoad` problem is highly likely caused by some buggy browser plugins/extensions.

You're right.
I don't have this problem when I use Google Chrome incognito mode.
Thanks.

**Comment by somera** [comment]
Looks like it is fixed in 1.21.4

**Comment by redsky-air** [comment]
This is likely an external browser store plugin bug, and after I eliminated it, it didn't issue a warning. Gitea1.21.4
