### ISSUE TITLE
Viewed files counter is reset when performing a review

### ISSUE THREAD

**Issue by saneks222** [go-gitea/gitea#28239]
### Description

**Familiarized with the issue** 
https://github.com/go-gitea/gitea/issues/26854 ,
https://github.com/go-gitea/gitea/issues/20681

Looks like the problem persists 

**Gitea Version:** 1.21.0

**Steps to Replay**:

Create a repo
Create a PR with a large number of modified files
Start viewing the PR, marking each viewed file as "viewed" using the checkboxes
Once the first 100 files are marked as viewed, click the "load more" button at the end of the page to load the remaining files

**Expected behavior**:

100 files are marked as viewed 
Viewed files counter at the top of the page displays 100

**Actual behavior**:

100 files marked as viewed 
the viewed files counter at the top of the page displays 0

![image](https://github.com/go-gitea/gitea/assets/66480963/620d20c0-3891-4991-b4ca-9772d209492f)

### Gitea Version

1.21.0

### Can you reproduce the bug on the Gitea demo site?

Yes

### Git Version

1.21.0

### How are you running Gitea?

Official docker image.

### Database

PostgreSQL

**Comment by sillyguodong** [comment]
closed by #29448
