### ISSUE TITLE
Broken Link in SECURITY.md

### ISSUE THREAD

**Issue by ElectricalBoy** [go-gitea/gitea#28248]
### Description

https://github.com/go-gitea/gitea/blob/4d7c063f9e0fde9ce12af9b30e0e1ecdcf11c3d1/SECURITY.md#L7

The link to the previous vulnerabilities (<https://about.gitea.com/security>) is broken - gives HTTP 404 instead.

### Gitea Version

4d7c063

**Comment by lunny** [comment]
Fixed.
