### ISSUE TITLE
Gitea v1.21.1 no longer loads custom CSS, images

### ISSUE THREAD

**Issue by Darthagnon** [go-gitea/gitea#28249]
### Description

I upgraded from gitea gogit v1.20.4 with [this custom CSS/image theme](https://codeberg.org/Darthagnon/gitea-github-theme), to gitea gogit v1.21.1. I'm on Win10 amd64, running it off my local machine, which is assigned a domain name by the router `pc-name.rh.local`. My conf is below. Upon upgrading, the CSS/custom theme no longer loads, and the browser console is full of 404 for the (still present) theme files. 

###

### Gitea Version

1.21.1

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://pastebin.com/Sfyw1tXu

### Screenshots

![Gitea not loading theme](https://github.com/go-gitea/gitea/assets/20792748/5fd5b19f-dd00-417d-a4b7-44800f5a8df4)

### Git Version

Gitea v1.21.1

### Operating System

Win10

### How are you running Gitea?

Fresh release, Windows gogit amd64 binary downloaded from Github, run as per the above config.

### Database

SQLite

**Comment by Bisstocuz** [comment]
Check out https://blog.gitea.com/release-of-1.21.0/#breaking-changes

**Comment by Darthagnon** [comment]
That seems to have fixed it, but a bit of a strange change, no? Hasn't `public` always been the default serve folder for most webservers? Thought anyone who'd be wanting to host their own git would know this, meaning the change is just a hindrance.

**Comment by lng2020** [comment]
Close as answered.  See PR https://github.com/go-gitea/gitea/pull/25907 for details about why we changed this.
