### ISSUE TITLE
Markdown render: math at the end of list item incorrectly indents next item

### ISSUE THREAD

**Issue by nschloe** [go-gitea/gitea#28259]
### Description

MWE:

```markdown
1. a 
   \[
   x
   \]
2. b
```

Screenshot (Nov 2023):

![screenshot_2023-11-28-174758](https://github.com/go-gitea/gitea/assets/181628/ec6a783e-7ae9-4ca7-9874-8ca0e273bad7)

### Gitea Version

1.22.0+dev-370-g4d7c063f9

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

https://try.gitea.io/

### Database

None

**Comment by wxiaoguang** [comment]
Will fix it in 1.23

![image](https://github.com/user-attachments/assets/2d67328a-c78f-4e2f-aff3-fd42b96759c0)

**Comment by wxiaoguang** [comment]
1.23 nightly is ready and I think it should have been fixed, feel free to take a try

![image](https://github.com/user-attachments/assets/c2666d14-f181-4308-a0db-aeb7880dffbc)

**Comment by nschloe** [comment]
Confirmed working.
