### ISSUE TITLE
Change Password on Sign-in Option No Longer Shown

### ISSUE THREAD

**Issue by MorganTheGull** [go-gitea/gitea#28258]
### Description

Editing a Users Password through the Site Administration no longer gives an option to force the user to change their password on the next login.

### Gitea Version

1.21.1

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/11876690/d5e378b0-7c69-45eb-892d-c161b42a7f6b)

### How are you running Gitea?

N/A

### Database

MYSQL

**Comment by jolheiser** [comment]
An enhancement for this was requested in https://github.com/go-gitea/gitea/issues/18815

Currently forcing a password change is available when creating users, but not when editing.

**Comment by colejohnson66** [comment]
@MorganAbrams lied here. We've done this before, but not through the GUI. We "hacked" the database to set the `must_change_password` column in the `user` table. :)
