### ISSUE TITLE
Commit search breaks when looking for opening square bracket "["

### ISSUE THREAD

**Issue by pcamilo89** [go-gitea/gitea#28269]
### Description

When trying to filter commits on a repo where the commit message have the type of commit enclosed in square brackets, e.g. "[build] Update libraries to next mayor version", the search doesn't behave as expected.
The different cases I tried were:
- When you search for a tag enclosed in square brackets, e.g. "[build]", it shows a bunch of results that doesn't match the search.
- when you search for a tag but missing the starting square bracket, e.g. "build]", the search gives the correct results.
- when you search for a tag enclosed in square brackets and escape the opening bracket, e.g. "\\[build]", the search gives the correct results.
- when you search only for an opening square bracket, e.g. "[", it shows an error page.
- when you search only for an opening square bracket and escape it, e.g. "\\[", it shows all the commits that have an opening square bracket which is the correct result.

### Gitea Version

1.21.0

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

When you search for "[" shows this error page
![image](https://github.com/go-gitea/gitea/assets/655782/ab667a32-918f-430a-9af2-5f68d2de0835)

### Git Version

2.40.1, Wire Protocol Version 2 Enabled

### Operating System

Debian GNU/Linux 11

### How are you running Gitea?

gitea/gitea:1.21.0 Docker image

### Database

None

**Comment by lng2020** [comment]
FYI, keywords are used here which lacked some checks.
https://github.com/go-gitea/gitea/blob/8b45a4d3668b433eaca68c1f06f40181a9fb1e9b/modules/git/repo_commit.go#L149-L151

**Comment by me-heer** [comment]
Hi, can I work on this?

**Comment by me-heer** [comment]
The [default behavior](https://git-scm.com/docs/git-log#Documentation/git-log.txt---basic-regexp) of `--grep` in `git log` is to interpret the keyword as a regular expression. 

If we want our keywords to be interpreted as 'strings', we should use [`-F` flag](https://git-scm.com/docs/git-log#Documentation/git-log.txt---basic-regexp).

I'm not sure if using regular expressions was the intended behavior previously.
