### ISSUE TITLE
gitea actions not working

### ISSUE THREAD

**Issue by zhangbaojia** [go-gitea/gitea#28277]
### Description

The steps are as follows:
    step1:  Installing gite
![gitea](https://github.com/go-gitea/gitea/assets/19427334/601f561c-1c29-4929-acc0-326fe4e07670)

    step2:  Modify file app.ini and get Token

    step3: Installing act_runner 
![gitea-runner](https://github.com/go-gitea/gitea/assets/19427334/893d7c16-c7b6-49ba-ac3c-5474d2cfd489)

    step4:  add  yarml
![yaml](https://github.com/go-gitea/gitea/assets/19427334/7bbe98dd-0e1f-4593-b3d5-3987277dc0be)

    step5:  runners configuration
![lookup](https://github.com/go-gitea/gitea/assets/19427334/263126f3-31b7-4e7a-8217-6f05c7e94b97)

    step6:   commit and push

    setp7:   output result
![nonfun](https://github.com/go-gitea/gitea/assets/19427334/afd6ddd8-02fd-49d9-bca5-e89b90e5ce3f)

Why is the compilation not performed? Is there any configuration missing?

   

### Gitea Version

1.21

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

CPE OS Name: cpe:/o:centos:centos:7             Kernel: Linux 3.10.0-862.el7.x86_64

### How are you running Gitea?

Install "gitea" and "act-runner" simultaneously using docker on a single server.
![gitea-runner](https://github.com/go-gitea/gitea/assets/19427334/0c058012-4822-42a2-8bc4-2e38ffb71638)

### Database

SQLite

**Comment by zhangbaojia** [comment]
docker logs 

    giteaLog:
![gite_log](https://github.com/go-gitea/gitea/assets/19427334/b48b0570-50df-42b6-9bd3-e339885e6dd4)

    act-runnerLog:
![runner_logs](https://github.com/go-gitea/gitea/assets/19427334/07c5e8ce-bb4e-4e09-b0c9-01be47e32fb9)

**Comment by yp05327** [comment]
`runs-on` should match runner's label.

ps: When we check matching runner, it seems that we should also check the runner's status.

**Comment by zhangbaojia** [comment]
runner：
![image](https://github.com/go-gitea/gitea/assets/19427334/0d2e4e9e-37b7-4c36-953b-6b7dd94ddd28)

runs-on：
![image](https://github.com/go-gitea/gitea/assets/19427334/b03348dd-0542-49c2-a163-45e40c8958c4)

 but it still did not take effect！

**Comment by yp05327** [comment]
Have no idea. So strange. 😕

**Comment by zhangbaojia** [comment]
After many tests, it was found that the problem was that the installation of runner on an offline server could not even run the basic operation。

![微信截图_20231201212313](https://github.com/go-gitea/gitea/assets/19427334/b295fab0-b612-42d0-8799-9c444ddd9151)


![微信截图_20231201211828](https://github.com/go-gitea/gitea/assets/19427334/bc32befd-0df7-43b3-838f-3c2be7526c87)

**Comment by yp05327** [comment]
I tried to run Gitea in DevContainer and disabled the network interface of docker in the host.
But I didn't reproduce this issue. 😕

**Comment by lunny** [comment]
This is because your labels are not matched.
