### ISSUE TITLE
Error after editing script in webpage

### ISSUE THREAD

**Issue by abosaad11** [go-gitea/gitea#28274]
### Description

There's a new bug where if I edit a script in the web browser (as usual) I get an error. I confirmed this by migrating the Github repository again and it works, but as soon as I edit this file I get  an error. Editing this file is a trivial task, I do it on Github and on my home Gitea instance. 

Sample of the error on https://try.gitea.io/xkc65869/cruel/actions/runs/5:

```
Traceback (most recent call last):
  File "./cruelbuild", line 1256, in <module>
    update_magisk(configs['kernel']['magisk'].get('version'))
  File "./cruelbuild", line 615, in update_magisk
    run(cmd, check=True)
  File "/opt/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['usr/magisk/update_magisk.sh', 'delta']' returned non-zero exit status 1.
```

Sample of the error on my home Gitea:

```
Traceback (most recent call last):
  File "/root/.cache/act/4a63210b3f0f72e9/hostexecutor/./cruelbuild", line 1256, in <module>
    update_magisk(configs['kernel']['magisk'].get('version'))
  File "/root/.cache/act/4a63210b3f0f72e9/hostexecutor/./cruelbuild", line 615, in update_magisk
    run(cmd, check=True)
  File "/usr/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'usr/magisk/update_magisk.sh'
```

I can assure you that this file `usr/magisk/update_magisk.sh` exists in the repository. If I changed a single character in it I will get this error, even if changed that character back to what it originally was, I get the error.

### Gitea Version

https://try.gitea.io/xkc65869/cruel/actions/runs/5:

### Can you reproduce the bug on the Gitea demo site?

Yes

### Git Version

1.22.0+dev-372-gcb8298b71

### How are you running Gitea?

On try.gitea.io and at home.

### Database

None

**Comment by lng2020** [comment]
> /root/.cache/act/4a63210b3f0f72e9/hostexecutor/./cruelbuild

I guess it's about relative path since the runner uses the cached script.

**Comment by abosaad11** [comment]
> > /root/.cache/act/4a63210b3f0f72e9/hostexecutor/./cruelbuild
> 
> I guess it's about relative path since the runner uses the cached script.

Should both the original and edited scripts exist in same path? I don't know what to do here. The workflow uses actions/checkout so I think it should copy the file anyway right?

**Comment by abosaad11** [comment]
Updating my local Gitea to `1.21.1` fixed this. But it's still present in  try.gitea.io `1.22`  https://try.gitea.io/xkc65869/cruel/actions/runs/6 .

**Comment by wxiaoguang** [comment]
It doesn't look like a Gitea problem.

Please confirm why `usr/magisk/update_magisk.sh` fails. I can see `set -e` in the script, any failed command in it also causes " non-zero exit status".


```
Traceback (most recent call last):
  File "./cruelbuild", line 1256, in <module>
    update_magisk(configs['kernel']['magisk'].get('version'))
  File "./cruelbuild", line 615, in update_magisk
    run(cmd, check=True)
  File "/opt/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['usr/magisk/update_magisk.sh', 'delta']' returned non-zero exit status 1.
```
