### ISSUE TITLE
Indicate commit verification in commit feeds

### ISSUE THREAD

**Issue by hazycora** [go-gitea/gitea#28281]
### Feature Description

Since the commit UI in feeds has been brought closer to how they are elsewhere since #27356, I think it would make sense to indicate verification here like is the case everywhere else.

The background colour to the commit hashes makes it look like my commits aren't verified. After updating to the latest release, I forgot that commit hashes didn't previously have a background colour indicating verification and thought something had broken with my signatures!

I'm not sure if this is something that can easily be changed, I don't know if the commit structs being used in the template there have their Verification defined. If this is something that could be done, please consider it! :3

### Screenshots

Currently: 
![image](https://github.com/go-gitea/gitea/assets/72580505/38954b4c-289d-4baa-9997-69ed7b354b82)
Instead it should indicate the commits are signed like everywhere else in the app
![image](https://github.com/go-gitea/gitea/assets/72580505/794b237d-1158-49ca-8dd6-f31c4d5e7307)

**Comment by silverwind** [comment]
With https://github.com/go-gitea/gitea/issues/29641, the plan is to remove these signature indicators in the hash, so all hashes render the same everywhere, so I think I will reject this.
