### ISSUE TITLE
latest 1.20.6 version (release yesterday) is older than 1.21.1 

### ISSUE THREAD

**Issue by dominiquefournier** [go-gitea/gitea#28289]
### Description

I use an automatic update script to maintain the gitea service.
The latest version was 1.**21**.1 until yesterday where a 1.**20**.6 version was released.
https://github.com/go-gitea/gitea/releases

It breaks the database with error log :
 `Your database (migration version: 280) is for a newer Gitea, you can not use the newer database for this old Gitea release (260).`
I think there is a version number error : it should be 1.21.2, no ?

### Gitea Version

1.21.1

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

Debian

### How are you running Gitea?

I use the https://github.com/go-gitea/gitea/releases repository

### Database

MySQL/MariaDB

**Comment by lng2020** [comment]
No. We released 1.20.6 because there is a security fix so the user still using 1.20.x should update their instance.  You can check the changelog.
For your case, you can skip this version because the same fix applies to 1.21.1 too.

**Comment by lng2020** [comment]
Sorry. GitHub release will auto-set the newest one as the latest. We will change that later. 
ref: https://github.com/go-gitea/gitea/issues/28291#issuecomment-1831684546
