### ISSUE TITLE
Version Mismatch Error When Using MariaDB with Gitea 1.20.6

### ISSUE THREAD

**Issue by pomcom** [go-gitea/gitea#28291]
### Description

Encountered a version mismatch error when starting Gitea `1.20.6` with MariaDB `10.6.16`. The error indicates that the database migration version (280) is for a newer Gitea, but I am running the current latest release. The configuration specifies MySQL, but the binary logs suggest SQLite support, potentially leading to confusion about the database compatibility. Need clarification or a fix to ensure proper database and Gitea version alignment.

"Your database (migration version: 280) is for a newer Gitea, you can not use the newer database for this old Gitea release (260)."

### Gitea Version

1.20.6 built with GNU Make 4.3, go1.20.11

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

Precompiled binary

### Database

MySQL/MariaDB

**Comment by wxiaoguang** [comment]
260 means Gitea 1.20, 280 means Gitea 1.21

You must have upgrade the instance to 1.21, then you should keep using the new version, but not downgrade.

**Comment by wxiaoguang** [comment]
Unless there is a bug in Gitea's release procedure, eg: the `latest` points to a wrong release.

You could try to manually set the Gitea version to 1.21 explicitly.

**Comment by pomcom** [comment]
I am confused about the release cycle. The latest version from yesterday on https://github.com/go-gitea/gitea/releases is v.1.20.6 (which triggers the missmatch error). Since my update script always pulls the last release, that is the one that got used this morning and failed to start. The version from two days ago (v.1.21.1) works fine.

**Comment by pomcom** [comment]
I think the issue can be closed. I did not see, that there are releases for  a 1.20.x Version and 1.21.x version.

**Comment by wxiaoguang** [comment]
So  there is a bug in Gitea's release procedure

![image](https://github.com/go-gitea/gitea/assets/2114189/c2d3b435-c746-45db-a539-c8c612a1226e)

**Comment by pomcom** [comment]
Does gitea support two release streams (1.20.x and 1.21.x) ?

**Comment by wxiaoguang** [comment]
> Does gitea support two release streams (1.20.x and 1.21.x) ?

IIRC usually no. When 1.21 is released, usually there won't be new releases for 1.20. But this time old 1.20 has some important security fixes, so it gets an unusual release.

**Comment by lunny** [comment]
I think 1.21.1 has been set as latest release manually.

**Comment by truebits** [comment]
Similar issue with my snap-managed gitea installation.
It was autoupdated and broke several hours ago.
`
gitea   v1.20.6   6670   latest/edge    gitea       -
Your database (migration version: 283) is for a newer Gitea, you can not use the newer database for this old Gitea release (260).
`
