### ISSUE TITLE
[Enhancement] Notify reviewer added in pull request via codeowners file

### ISSUE THREAD

**Issue by mg-cloud** [go-gitea/gitea#28297]
### Feature Description

This could be an enhancement of #24910 
This pull request added the neat codeowners feature to automatically add reviewer to pull request upon creation.
However, the reviewer are not notified by email unlike when added manually after the pull request is created.

I didn't find any discussion around that in the parent issue so i dunno if this was done on purpose or if this could be a nice enhancement of this feature.

**Comment by lunny** [comment]
This should be considered as a bug but not a proposal.
