### ISSUE TITLE
Allow multiple HTTP proxies depending on remote URL

### ISSUE THREAD

**Issue by eNBeWe** [go-gitea/gitea#28290]
### Feature Description

For an internal Gitea Instance I need to configure multiple proxies to mirror Git-Repositories.

I. e.:
* To mirror repositories from github.com use Proxy A
* To mirror repositories from someinternal.network.local use Proxy B

I know that Gitea uses the system proxy by default, which solves one of the requirements, but not both at the same time.
Git allows to configure the proxy "by url".

**Comment by wxiaoguang** [comment]
I guess you need a more smart proxy server/delegate to apply complex rules.

**Comment by wxiaoguang** [comment]
In a complex environment, the proxy rules could also be quite complex. IMO Gitea should focus on its core feature, but not become a full-featured proxy client.
