### ISSUE TITLE
PR can't be merged after manual conflict resolution

### ISSUE THREAD

**Issue by JetpackDuba** [go-gitea/gitea#283]
- Gitea version (or commit ref): Commit: e6da2cf2cbff4d550cf938548233a59ceef6528e
- Git version: 2.7.4
- Operating system: Linux Mint  18
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite

## Description
If I do a PR with conflicts, gitea says that I have to merge branch manually ( `This pull request can't be merged automatically because there are conflicts.` ). I've done it but the message does not disappear. I closed the PR, then reopened it and now if I go to the merge request I get the following message everytime:
> The conflict checking is still in progress, please refresh page in few moments. 

![seleccion_009](https://cloud.githubusercontent.com/assets/16917468/20649966/b1af09b4-b4cb-11e6-8c82-e316660bb864.png)

## Steps to reproduce
- Create new PR with a conflict between the 2 branches
- Merge manually the branch fixing the conflicts
- Close the PR
- Reopen it

**Comment by Bwko** [comment]
I'm able to semi reproduce this bug. My Gitea keeps nagging about: 

> This pull request can't be merged automatically because there are conflicts.

I'll look into this.

**Comment by JetpackDuba** [comment]
If you don't close it, you'll get this message. If you close it and then reopen it, `The conflict checking is still in progress, please refresh page in few moments.` will appear

**Comment by Bwko** [comment]
I've opened & closed the PR multiple times:
![conflict](https://cloud.githubusercontent.com/assets/23573579/20745763/fdb71fd6-b6e2-11e6-94f4-db0db2afc585.png)

Was you PR relatively large?

**Comment by lunny** [comment]
I can't reproduce it. Any more clues?

**Comment by strk** [comment]
Check the logs, I bet you got a panic in a goroutine (saw that happening) so some parts of the code are just waiting for something that will never happen (hearing back from the goroutine). It would help if panic messages were included in the logs but they only go to either stdout or stderr (I'm not sure which one).

So my suggestion is:
 - restart Gitea (or Gogs) redirecting stdout and stderr somewhere
 - check all logs if it still happens

**Comment by strk** [comment]
See #210 for the missing stderr/stdout redirection

**Comment by JetpackDuba** [comment]
I've tried it again in a windows pc and I get the same behavior as @Bwko 
> This pull request can't be merged automatically because there are conflicts. 

I'm testing this with small PR

**Comment by Bwko** [comment]
So the behavior is the same on Linux (I'm on Linux) & Windows. 
At least we need to show a message that this PR has been merged.

**Comment by JetpackDuba** [comment]
@strk I'm getting an error when restarting Gitea in my Linux Mint:
![imagen](https://cloud.githubusercontent.com/assets/16917468/20771654/9707f0b8-b74a-11e6-8c77-2eb18be014a6.png)

Entrada desconocida (Spanish) -> Unknown input

[gogs.log.zip](https://github.com/go-gitea/gitea/files/623017/gogs.log.zip)

I can share with you my Database and repos (They are just test repos) if it's necessary to debug it

**Comment by Bwko** [comment]
If you could share your repo it would help us a lot. Googling the git apply error points me to a whitespace error. Are there any [whitespace 'like' ](https://en.wikipedia.org/wiki/Whitespace_character)characters in your reppo/PR?

**Comment by JetpackDuba** [comment]
@Bwko oke! Tonight I will attach my repo, I'm not at home atm

**Comment by JetpackDuba** [comment]
DB SQL backup and my repo:
[Gitea.zip](https://github.com/go-gitea/gitea/files/625632/Gitea.zip)
User: test@gmail.com
Password: TestTest
If you need something else I'll try to help!

**Comment by Bwko** [comment]
@aeab13 Thanks for your help :+1: 
The bug somehow only exists in your repo (on my machine it sometimes shows the same error). But when I switch back to my own installation I'm not able to reproduce this bug.

- I think the easiest solution is to prevent the execution of the .testPatch method (which produces the error). I'ts pretty useless to test a patch with 0 commits and 0 files changed.

- A better solution would be to automatically mark this PR as merged. And thus avoiding the all the pre merge checks. But I don't know if this solution is possible.

**Comment by bkcsoft** [comment]
Title changed to clarity

**Comment by JetpackDuba** [comment]
@bkcsoft thanks for changing the title!
@Bwko thanks to you!
I've reinstalled my OS and I'll try again to create a PR with conflicts to try to reproduce it again.

PD: Does this issue still need more feedback? (I'm talking about the label)

**Comment by Bwko** [comment]
@aeab13 Could you check if #368 fixes your issue?

**Comment by JetpackDuba** [comment]
@Bwko  I'll test it tonight!

**Comment by JetpackDuba** [comment]
I'm having some problems with mysql in my machine.
I'll test tomorrow the changes :s Sorry!

**Comment by JetpackDuba** [comment]
I've tested changes in #368 
The message `The conflict checking is still in progress, please refresh page in few moments.` has disappeared but I'm still getting `This pull request can't be merged automatically because there are conflicts.` after manual merge  and I can't see commits and changed files. So the problem is still the same with different message :p 
EDIT: I can't see commits and changed file in the selected pull request only if I close it and reopen it.
![spectacle bz3630](https://cloud.githubusercontent.com/assets/16917468/21082953/be9a1b84-bfe6-11e6-9f3c-8420440a5acc.png)

EDIT2: I've checked the PR again and now I can see commit and files changed but still getting the same message

**Comment by Bwko** [comment]
@aeab13 Thanks for testing. 
My PR fixed the bug that was causing the `The conflict checking is still in progress, please refresh page in few moments.` error.

I haven't found a good solution on how to mark the conflicting PR as merged. So for now I don't know how to solve this issue :worried:
Maybe someone else has any idea?

**Comment by JetpackDuba** [comment]
I would like to try to fix it but I haven't got time to do that right now :s 
If it is not fixed in a month or so, I'll try.
Thanks for trying it @Bwko ! :D

**Comment by lunny** [comment]
@aeab13, if you have no time, could you give some idea about where the problem is?

**Comment by lunny** [comment]
move this to 1.1 and feel free to change it back if someone has good idea.

**Comment by grissiom** [comment]
@lunny I think `git merge-base --is-ancestor` will help you to detect whether a PR has been merged manually or not. I a PR has already been merged, `git merge-base --is-ancestor pull/x/head HEAD` will return 0. If the PR has not been merged, it will return 1.

**Comment by lunny** [comment]
@Bwko could you try to send another PR followed @grissiom 's advice?

**Comment by Bwko** [comment]
@lunny & @grissiom I'll take a look at that

**Comment by Bwko** [comment]
I'm almost done with this :smile: 
Do we want to automatically set a PR to merged or do we want to show a message that this PR was manually merged?

**Comment by lunny** [comment]
How github do that?

**Comment by andreynering** [comment]
I think GitHub marks as merged.

**Comment by Bwko** [comment]
@aeab13 Could you test #719?

**Comment by JetpackDuba** [comment]
I'll do it tomorrow!

**Comment by Bwko** [comment]
@aeab13 Any updates on this issue? :roll_eyes:

**Comment by JetpackDuba** [comment]
Sorry, I am having some issues with my computer and I can't test it right now. I am sorry :/
