### ISSUE TITLE
Unable to open database file: The system cannot find the path specified

### ISSUE THREAD

**Issue by yp05327** [go-gitea/gitea#28300]
### Description

On windows:
![image](https://github.com/go-gitea/gitea/assets/18380374/d9445070-8ee7-48ef-82f7-f9336ec2f9a4)

### Gitea Version

1.21.0

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

gitea-1.21.0-windows-4.0-amd64.exe

### Database

None

**Comment by yp05327** [comment]
After I created `data` folder manually. It worked.

**Comment by KazzmanK** [comment]
It was something about this earlier....

**Comment by yp05327** [comment]
@lunny 
We call `checkDatabase` before `PrepareAppDataPath` which partly caused this issue,
because this will not happen in Linux, so maybe it is also related to XORM?

**Comment by lunny** [comment]
> @lunny We call `checkDatabase` before `PrepareAppDataPath` which partly caused this issue, because this will not happen in Linux, so maybe it is also related to XORM?

Why call `checkDatabase` before `PrepareAppDataPath` will cause the issue?

**Comment by yp05327** [comment]
This issue start from v1.20.1

**Comment by yp05327** [comment]
This is caused by #25944.
Before this patch, when Gitea start, `data` folder will be created automatically.
After this patch, `data` folder will not be created, which caused this issue.

When we call `checkDatabase`, XORM will try to open `data/gitea.db`, but `data` folder does not exist.
And it seems that XORM will not automatically create folder when `gitea.db` is in an non-exist folder in windows.

**Comment by yp05327** [comment]
For example, you can modified the code here:
![image](https://github.com/go-gitea/gitea/assets/18380374/d6791e46-b148-4ea4-8bd5-29576431cbdf)

Then build and run Gitea in linux.
After click the install button, `checkDatabase` will return `true`, and we have modified the code above, so it will return and not run the codes below.
Then you can see an empty `gitea.db` in `data` folder:
![image](https://github.com/go-gitea/gitea/assets/18380374/38afecb2-80b2-41f5-bbda-f948e0fbe2dc)
(`gitea.db` is empty)
![image](https://github.com/go-gitea/gitea/assets/18380374/5e74e300-2d31-45d1-ba35-67b3c804c997)
So we can know that in linux, `checkDatabase` will create both `data` folder and `gitea.db`.
And I think this is done by XORM.

Then build a windows version without any modify and run it in windows.
After click the install button, `checkDatabase` will return `false`, and we didn't modify the code above, so it will return and not run the codes below.
Then you can see that nothing changed in the root path. No `data` folder and of cause no `gitea.db`.


After more tests, I found that `checkDatabase` will return `false` here:
![image](https://github.com/go-gitea/gitea/assets/18380374/252aa706-d62c-444b-8746-5b05903392d3)

In `CheckDatabaseConnection`, all operations are handled by XORM I think, so it seems that there's a bug in XORM when OS is windows?
![image](https://github.com/go-gitea/gitea/assets/18380374/d435931f-e031-4171-81a5-104ebcb3f0f0)

**Comment by wxiaoguang** [comment]
The fix should be this:  Fix incorrect directory path handling for SQLite3 database file #28374
