### ISSUE TITLE
Show commits to a branch in PR

### ISSUE THREAD

**Issue by kolaente** [go-gitea/gitea#2830]
When a user pushes a commit to a branch which has an open PR, this commit should appear as a comment in the PR. Basically like it does in Github.

This is probably "nice to have" but after working with Github for some time, it bothers me somehow that this isn't implemented in Gitea.

(I don't know if there already is an issue about this, if yes please point me to it.)

**Comment by lafriks** [comment]
It is already is WIP for version 1.3.0 - see PR #2548

**Comment by kolaente** [comment]
Coooool 😄
