### ISSUE TITLE
Update Note and Warning markdown highlighting with GitHub's changes

### ISSUE THREAD

**Issue by yardenshoham** [go-gitea/gitea#28316]
### Feature Description

Since July 21st, GitHub has made a few changes to their feature. We introduced it into Gitea with https://github.com/go-gitea/gitea/pull/21711. Now we need to update the implementation to match GitHub's, including a syntax change. An example of the current implementation on GitHub:

> [!NOTE]  
> Highlights information that users should take into account, even when skimming.

> [!TIP]
> Optional information to help a user be more successful.

> [!IMPORTANT]  
> Crucial information necessary for users to succeed.

> [!WARNING]  
> Critical content demanding immediate user attention due to potential risks.

> [!CAUTION]
> Negative potential consequences of an action.

Docs: https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts https://github.com/orgs/community/discussions/16925

**Comment by lng2020** [comment]
So, If I understand correctly, GitHub no longer supports 
```
>**NOTE**
>something
```

Instead, it uses 
```
>[!NOTE]  
>something
```

That's a breaking change. Should we follow what GitHub did?

**Comment by yardenshoham** [comment]
I think we should follow GitHub on this feature
