### ISSUE TITLE
Error reported after upgrade

### ISSUE THREAD

**Issue by imaxun** [go-gitea/gitea#28317]
### Description

![image](https://github.com/go-gitea/gitea/assets/29112991/f4d0a95e-19c3-4f6c-82aa-72e8348847fd)

### Gitea Version

1.21.1

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

Error reported after upgrade

### Database

None

**Comment by imaxun** [comment]
GetRecentlyPushedBranches, Error 1267 (HY000): Illegal mix of collations (utf8mb4_0900_ai_ci,IMPLICIT) and (utf8mb4_general_ci,IMPLICIT) for operation '='

**Comment by AdamMajer** [comment]
this is MariaDB? Or what database is this?

And what "upgrade"? What did you actually upgrade?

**Comment by imaxun** [comment]
> 这是玛丽亚数据库？或者说这是什么数据库？
> 
> 什么“升级”？你实际上升级了什么？

v1.21.0  -> 1.26  -> 1.21.1
mysql

**Comment by imaxun** [comment]
<img width="1714" alt="image" src="https://github.com/go-gitea/gitea/assets/29112991/3bdf95f7-f83c-4df8-ae61-f5b28d043272">

**Comment by KN4CK3R** [comment]
https://docs.gitea.com/administration/command-line#doctor-convert
