### ISSUE TITLE
Repositories tab doesn't work from profile page

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#28326]
### Description

When I click on 'repositories' from my profile the url changes but the current page gets reloaded without showing any new information. See the attached screenshot.

### Gitea Version

1.21.0+22-g4b89c0f99

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

![Screenshot from 2023-12-02 21-48-27](https://github.com/go-gitea/gitea/assets/152197675/5495c160-3e82-4e47-964b-c7da8cb952c5)

### Git Version

git version 2.30.2

### Operating System

Debian 10

### How are you running Gitea?

It's being run through NGINX as an inverse proxy. Using the proxy_pass directive.

### Database

SQLite

**Comment by racc-ode** [comment]
Everything works fine when I append /gitea to my domain settings:

https://git.raccode.com/gitea/raccode?tab=repositories

Any reason why some pages cannot be served directly from the root url?

**Comment by yp05327** [comment]
> Everything works fine when I append /gitea to my domain settings:

Do you mean that you want to access your Gitea instance by https://git.raccode.com (without `/gitea`)?
But it didn't work until you appended `/gitea` to the `ROOT_URL` in app.ini?

**Comment by wxiaoguang** [comment]
> Any reason why some pages cannot be served directly from the root url?

`https://git.raccode.com/gitea/raccode` means the default `overview` page, if there is a profile page, then it is the profile page.


`https://git.raccode.com/gitea/raccode?tab=repositories` means the repositories page.
