### ISSUE TITLE
openpgp error on Debian package upload

### ISSUE THREAD

**Issue by williamdes** [go-gitea/gitea#28324]
### Description

```
openpgp: invalid argument: user id field contained invalid characters
```

I did not configure anything in the gitea config for packages. Maybe I am missing something ?
This error can maybe be handled upper in the code and provide a better hint

### Gitea Version

1.21.0

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

See: https://docs.gitea.com/next/usage/packages/packages/debian#publish-a-package
```
PUT /api/packages/wdes/debian/pool/bookworm/main/upload HTTP/2
```

the curl command outputs the server reply: `openpgp: invalid argument: user id field contained invalid characters`

### How are you running Gitea?

Docker rootless

### Database

MySQL/MariaDB

**Comment by KN4CK3R** [comment]
Why "name" did you give to Gitea in your settings? Looks like you used an invalid character there.

**Comment by williamdes** [comment]
https://github.com/keybase/go-crypto/blob/de78d2cb44f4360c724f681478689e314d00bf96/openpgp/packet/userid.go#L33C16-L33C72

says:
```go
// NewUserId returns a UserId or nil if any of the arguments contain invalid
// characters. The invalid characters are '\x00', '(', ')', '<' and '>'
```
