### ISSUE TITLE
actions task displays an incorrect time

### ISSUE THREAD

**Issue by ExplodingDragon** [go-gitea/gitea#28323]
### Description

I'm using sqlite and found this bug during a routine weekly check, not sure how to reproduce it for now.

![图片](https://github.com/go-gitea/gitea/assets/33776693/a1f7d2fa-e8d3-40f6-a64f-a899fb770b4d)
![图片](https://github.com/go-gitea/gitea/assets/33776693/247f33c3-c0dd-44e4-a129-f0de249a7daf)
![图片](https://github.com/go-gitea/gitea/assets/33776693/bd03fe57-9ba2-4589-9a3f-a35ddf677bcc)

### Gitea Version

main

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

systemd

### Database

SQLite

**Comment by yp05327** [comment]
The duration in the first pic is calculated by the records in `action_run` table,
and in the second pic, it is calculated by the records in `action_task_step` table.
So it seems that the data in `action_task_step` table is correct but the data in `action_run` table is incorrect.

**Comment by yp05327** [comment]
It seems that this run was scheduled twice.

`yesterday` (above the wrong duration`) is `Updated` time. Not the `Started` time and `Stopped` time.
And the schedule is `weekly`, and the run before this run is `2 weeks ago`, so the last updated time of this run should be `1 weeks ago`? But it is `yesterday` here.

So I guess: `yesterday` it was scheduled again (or maybe other operations?) , and the `Started` time was updated.
But this run is already been done, so the status should be done and it would not run again.
So the `Stopped` time should be the last stopped time which won't be updated for ever, so the duration becomes minus number here.
So if my guess is correct, the date of `yesterday` would be about `105h37m21s` after the real `Stopped` time.

**Comment by yp05327** [comment]
Ok, I got it.
![image](https://github.com/go-gitea/gitea/assets/18380374/bc8ae551-49ca-4fa4-abd6-02b81ed4fd9b)

**Comment by yp05327** [comment]
This issue is not related to cron job.
And there's a easy way to reproduce:
- stop all your runners which can pick up the workflow.
- trigger the workflow, and the status will be waiting as there's no runners to run it.
- cancel it, the status will become failure.
- start your runner, rerun it
- after it finished, you will get a minus duration time.
