### ISSUE TITLE
"Actions" tab says "There are no workflows yet."

### ISSUE THREAD

**Issue by eduardosm** [go-gitea/gitea#28332]
### Description

"Actions" tab says "There are no workflows yet.", which is not true.

The tab shows "1", which suggest that there is a workflow running. Additionally, status icons appear in commits and PRs.

### Gitea Version

1.21.1

### Can you reproduce the bug on the Gitea demo site?

Yes

https://try.gitea.io/endfkbyn/test2/actions

### Log Gist

There are not relevant logs

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/761151/de645d83-0043-4c04-8c51-c18d4966378b)

### Git Version

The one included in the Docker image

### Operating System

Linux ARM64

### How are you running Gitea?

Official Docker image (gitea/gitea:1.21)

### Database

PostgreSQL

**Comment by yp05327** [comment]
Maybe in this page we should have a branch selector.
