### ISSUE TITLE
Failed to add comment to a PR - slice out of range

### ISSUE THREAD

**Issue by ghazninattarshah** [go-gitea/gitea#28347]
### Description

2023/12/04 16:59:48 .../context_response.go:86:HTML() [E] Render failed: failed to render template: repo/diff/conversation, error: template error: builtin(bindata):repo/diff/conversation:1:16 : executing "repo/diff/conversation" at <index .comments 0>: error calling index: reflect: slice index out of range
----------------------------------------------------------------------
{{$resolved := (index .comments 0).IsResolved}}
                ^
----------------------------------------------------------------------

### Gitea Version

1.21.1

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

<img width="1366" alt="image" src="https://github.com/go-gitea/gitea/assets/7168293/3ae9e9fd-f326-4871-8775-48607cf864f0">

### Git Version

1.21.1

### How are you running Gitea?

In virtual machine using the docker rootless image from docker hub

### Database

PostgreSQL

**Comment by KN4CK3R** [comment]
Any idea how to reproduce that error?

Could you test if #28351 fixes your problem?
