### ISSUE TITLE
Reconfiguration after update to 1.20.6 (Docker)

### ISSUE THREAD

**Issue by xcojonny** [go-gitea/gitea#28342]
### Description

Hej,

after updating gitea to 1.20.6 the initial configuration page is shown -> so my instance is broken. I haven't change anything else.

Any Ideas?

### Gitea Version

1.20.6

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/xcojonny/34e91ee0e2861fcaf8b843d3b2e2f7fb

### How are you running Gitea?

Docker on Ubuntu

### Database

MySQL/MariaDB

**Comment by lng2020** [comment]
So where are your old database, `data` folder, or `app.ini` mounting at?

**Comment by lng2020** [comment]
The instance didn't ping the db. I think the app.ini causes it somehow went wrong. You can inspect yourself.
