### ISSUE TITLE
Community TOC Nominations 2024

### ISSUE THREAD

**Issue by jolheiser** [go-gitea/gitea#28350]
It's time for the yearly election for community TOC members!
https://github.com/go-gitea/gitea/blob/main/CONTRIBUTING.md#technical-oversight-committee-toc

This issue is **only** for collecting nominations, the actual vote will be done with votesup as we did last year to ensure no one is pressured to vote a certain way.

Please put your name forward or nominate another (willing) maintainer, ideally along with a simple description of why said person would make a good candidate. We will send out a separate notification once we have the vote ready after collecting nominations.

If you are nominated by someone else, please feel free to accept/deny the nomination as well so we can constrain the ballot to people interested in running.

**If you are not a Gitea maintainer, please refrain from commenting, we will be marking them as off-topic. Any conversation regarding this issue can happen on Discord, Discourse, or Matrix.**

cc @go-gitea/maintainers

**Comment by jolheiser** [comment]
I would like to run again. I will admit I had far less time this year than I anticipated, however I tried to stay abreast of current issues and to communicate in chat when issues arose. I am extremely fond of this project and would love to continue being a voice for it (which I plan on doing officially or unofficially :grin:).

I have been with the project since early 2019 and have accrued a fair amount of org/business/historical knowledge in that time, which I think continues to make me a good fit. I've also been able to help with various documentation and CI issues, along with a smattering of bug fixes.

-----

If I could hijack my own post to nominate someone as well, I think @delvh would be a fantastic choice. I think he has touched nearly every PR in the last year or so and focuses on making our processes better constantly.

**Comment by wxiaoguang** [comment]
Thank you for nominating 🙏, while I'd like to abstain (I also abstained last year) and leave the chance to others 😄

**Comment by denyskon** [comment]
@wxiaoguang Do you mean that you don't want to accept the nomination or that you won't nominate anybody/vote?

**Comment by wxiaoguang** [comment]
> Do you mean that you don't want to accept the nomination or that you won't nominate anybody/vote?

Sorry for my unclear comment. I meant "not accept the nomination for me". (ps: I won't nominate or vote either because I don't know how TOC work)

**Comment by 6543** [comment]
There are 6 members in the TOC, 3 decided by the gitea company and 3 elected as with in here. gitea company members can not be elected.

They do administrative tasks, promote gitea ... and are the last to decide on hard questions/decissions.

**Comment by 6543** [comment]
As **jolheiser** wrote, i can just copy paste ;) that more or less.

If you have future questions about the TOC just ask on discord/matrix and ping **us** (people are bussy ;) )

**Comment by puni9869** [comment]
> Thanks @jolheiser for organising this and for serving as a TOC member in 2023.
> 
> I'd like to nominate the following people:
> 
> * @delvh - through managing the last couple releases and doing lots of other management tasks like issue moderation they have proven the willingness to take a huge responsibility for the project
> * @wxiaoguang - through always ensuring a great code quality and never acting frivolous when it comes to reviews they have shown to me just the right attitude to make decisions which result in a positive technical impact for the project
> * @silverwind - here basically the same reasons  as with my previous nominee, from my point of view they are always ensuring that the project is moving in the right direction
> 
> I want to thank every current TOC member for their hard work - especially with a demand for PR reviews larger than ever, big changes starting with huge functionality improvements and ending with everything related to Gitea Ltd and all the other challenges which appeared during this year, all of you have been doing a great job managing the project. I'd like for these nomination choices not to be seen as any sort of criticism towards the current TOC members. I am only involved in Gitea for a few months now and the maintainers nominated by me are those who had the biggest impact on my contributions and my view of the project during these months :)

Same for me.

**Comment by delvh** [comment]
I have no idea yet how much time I'll have next year, but yes, I accept the nomination.

**Comment by delvh** [comment]
Well… if no one else applies/gets nominated, then we at least have an easy choice since there are only three candidates for three seats at the moment :laughing:

**Comment by jolheiser** [comment]
@6543 was your comment meant to say you also are applying?

If so we have myself, 6543, delvh, and then if @silverwind wishes to confirm their nomination.

**Comment by lunny** [comment]
I nominate @KN4CK3R . I think he has the ability to resolve complext issues according to his contributions, especially for  Packages and Storages.

**Comment by KN4CK3R** [comment]
Thank you for the nomination, accepting 👍

**Comment by 6543** [comment]
I would nominate @lafriks , @jolheiser  and @silverwind

**Comment by pat-s** [comment]
@delvh @silverwind @KN4CK3R

**Comment by jolheiser** [comment]
A vote has been started and all maintainers should have received an email with instructions to cast a ballot. 

If you did not, please let me know here, via email, or on Discord.

/cc @go-gitea/maintainers

**Comment by kerwin612** [comment]
I would nominate @wxiaoguang  , @6543  and @silverwind

**Comment by denyskon** [comment]
@go-gitea/maintainers

Another reminder that voting is still open and less than 50% have already voted. We should have a participation of at least 50% for the results of the election to be considered legitimate I think.... so please vote if you didn't already!

**Comment by tboerger** [comment]
I vote for @6543, @lafriks and @silverwind

**Comment by 6543** [comment]
Thanks for the nomination.

But the vote is already running: https://vote.heliosvoting.org/helios/elections/cf112912-a5c1-11ee-b29b-026c14065f7c/voters/list

**Comment by jolheiser** [comment]
The election is closed, thanks to everyone who voted!
https://vote.heliosvoting.org/helios/elections/cf112912-a5c1-11ee-b29b-026c14065f7c/view

Screenshot as well in case the URL stops working:
![election results](https://github.com/go-gitea/gitea/assets/42128690/645d67e4-af8b-49bb-b720-87bd288c8798)

**Comment by 6543** [comment]
@silverwind do you accept it?
