### ISSUE TITLE
after delete all applications still trigger webhook

### ISSUE THREAD

**Issue by cruvie** [go-gitea/gitea#28377]
### Description

I use gitea and drone
1 add drone application in gitea
2 grant drone
3 tagger a webhook by edit and commit .drone.yml
4 delete all application and withdraw all application
5 edit and commit .drone.yml will still trigger a webhook
<img width="1477" alt="Xnip2023-12-07_00-47-40" src="https://github.com/go-gitea/gitea/assets/55651847/7460f0df-974c-4771-bd3e-fae415abfa9c">
<img width="1353" alt="Xnip2023-12-07_00-52-09" src="https://github.com/go-gitea/gitea/assets/55651847/4ed4d648-004e-4311-b9d8-f97a19bfd3ca">

### Gitea Version

1.21.1

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

docker mac with m2

### Database

None

**Comment by yp05327** [comment]
Drone will automatically create a webhook in your repository. You should also remove it.
