### ISSUE TITLE
Compare changes and new pull requests take a very long time.

### ISSUE THREAD

**Issue by MsBuggy** [go-gitea/gitea#2837]
- Gitea version (or commit ref): 1.2 windows-amd64
- Git version: 2.11.0 windows
- Operating system: windows 2008 R2 _16 CPU cores and 16GB RAM_
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description

I try to create pull requests and the 'compare changes' step takes 10 minutes!  Create pull requests make the browser crashed!

**Comment by lflare** [comment]
How big of a repository are we talking about here? Do you have any logs?

**Comment by webjoel** [comment]
In my case is a little slow too, repo is very big, an solution is add gauge/loading image for feedback to user. It's possible?

If yes, is good add too in apply merge pull request, what is very slow too e no exixsts feedback to user, only the loading in the browser title.

My repo size is: 1,8 GB.

Issue related: #601

**Comment by adelowo** [comment]
I am currently experiencing this too on a project with a size of `146MB`. :)

**Comment by lunny** [comment]
@adelowo maybe you can send a pull request.

**Comment by adelowo** [comment]
@lunny I will try to take a look at it in the coming week hopefully. 

By the way, mine takes 3 -5 minutes without causing a  browser crash

**Comment by lunny** [comment]
@MsBuggy @webjoel @adelowo is this still a problem?

**Comment by webjoel** [comment]
@lunny I am using an old version (commit 1b2aff0), I have not yet been able to upgrade to the latest version, so I'm not sure if the problem persists in the new ones, but in this one I'm using the slowness continues.

**Comment by adelowo** [comment]
@lunny I no longer have access to the repository so I will not be able to test that

**Comment by zeripath** [comment]
Ok that Gitea version is before the substantial speed up pr #4921 @Typeless made was pulled.

**Comment by webjoel** [comment]
@lunny @lafriks  Is it possible for this PR ( #4921 ) to inner in 1.7.x release? Or is it only 1.8?

Anyway, for me can close this issue, since other related issues were also closed, so the best should have generated performance gain.

**Comment by lafriks** [comment]
@webjoel only bug fixes are backported

**Comment by 1902sysad** [comment]
im having this issue, is there any workarounds?

**Comment by typeless** [comment]
I encountered this for a couple of times. I tried to sample the timings with `ps -u git -o cmd` manually and got
```
CWD CMD
-   /volume1/homes/git/gitea/gitea web
-   /bin/git -c credential.helper= -c protocol.version=2 -c filter.lfs.required= -c filter.lfs.smudge= -c filter.lfs.clean= remote add -f 1565248623376910366 /volume1/homes/git/gitea/repositories/saturn/large-repo.git
-   /var/packages/Git/target/libexec/git-core/git fetch 1565248623376910366
-   git-upload-pack /volume1/homes/git/gitea/repositories/saturn/large-repo.git
-   /var/packages/Git/target/libexec/git-core/git rev-list --objects --stdin --not --all --quiet
```
I guess `git remote add -f` is probably the one taking long time.

**Comment by typeless** [comment]
Looking into it further, that should be at https://github.com/go-gitea/gitea/blob/1608f63e396c78bcbea3605b812556ddf441a6c4/modules/git/repo_compare.go#L55

**Comment by typeless** [comment]
A quick workaround, I assume, is to decouple `git remote add` and `git fetch.`
And then make `git fetch` fetches only the branch in question, not all the other refs.

**Comment by typeless** [comment]
@1902sysad Hey, if you know how to build Gitea from source, please try https://github.com/go-gitea/gitea/pull/7797/files to see if it fixes your problem.

**Comment by 1902sysad** [comment]
Thank you we will be trying this soon
