### ISSUE TITLE
Assigning a PR to a user group

### ISSUE THREAD

**Issue by MrVrops** [go-gitea/gitea#28370]
### Feature Description

Hello everyone,

In order to improve our workflow, we would like to assign groups of users to the organization instead of individual users. (Cf. screenshot)

This option doesn't seem to exist, so we thought it would be a good idea to request this features.

Thanks for all.

Sincerely,

### Screenshots

![PR](https://github.com/go-gitea/gitea/assets/25271722/252b048e-b157-4fd8-93be-f75080b471f4)

**Comment by delvh** [comment]
Feel free to reopen if I misunderstood your request incorrectly.

**Comment by MrVrops** [comment]
Thank you for your reply.

In fact I'd like to be able to add, for example, the "Owner" group in the "Assignees" drop down, so that it's automatically assigned to all the people in the "Owner" group instead of adding them one by one manually.

I've tried putting "Owners/" as a prefix in this field but I can't get any results.

Thanks for all.
