### ISSUE TITLE
"Actions" tab is empty when workflow runs exists

### ISSUE THREAD

**Issue by harryzcy** [go-gitea/gitea#28389]
### Description

The actions tab does not show workflows. But from the PR, I can click into the workflows.

I enabled the actions for this repository just before this PR. The actions are working for my other repositories that I enabled previously in Gitea 1.20.

### Gitea Version

1.21.1

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

<img width="1285" alt="image" src="https://github.com/go-gitea/gitea/assets/37034805/fd78de67-4170-4404-8079-542c599d5a8f">
<img width="1315" alt="image" src="https://github.com/go-gitea/gitea/assets/37034805/715e5a81-26a9-497c-85d3-763eec6ee558">
<img width="985" alt="image" src="https://github.com/go-gitea/gitea/assets/37034805/e4ff6cd4-cca4-4267-b793-318be6a222eb">

### How are you running Gitea?

Docker container.

### Database

PostgreSQL

**Comment by yp05327** [comment]
Maybe duplicate #28332

**Comment by harryzcy** [comment]
@yp05327 Thanks for pointing out
