### ISSUE TITLE
[feat request]: support links shortcut in markdown files

### ISSUE THREAD

**Issue by diamante0018** [go-gitea/gitea#28398]
### Feature Description

On GitHub, I can fill out an MD file with something along the lines of

```md
[Git](git-link)

# At the bottom of the file for "tidiness"
[git-link]:          https://git-scm.com/
```

This feature is not supported on Gitea and will not display the right link correctly When clicking the first "Git"

You can see here that Gitea will process this specialized syntax with something like this:
![image](https://github.com/go-gitea/gitea/assets/37080671/efc3c0dd-b6d4-4d87-807c-e0f329113714)

Once clicked the link will of course redirect to a non-existent page (.../branch/master/git-link)

I would love to see this feature here, I just recently started my own self-hosted Gitea instance and I love it.

### Screenshots

This feature is used heavily on GitHub on a repo like this one which I recommend viewing in case one is interested in learning more about what GitHub supports.

https://github.com/official-stockfish/Stockfish/blob/master/README.md

**Comment by a1012112796** [comment]
looks your format is wrong, example:
```
[Git](git-link) ❌
[Git][git-link] ✅
------

[git-link]:          https://git-scm.com/

```

[Git](git-link) ❌
[Git][git-link] ✅
------

[git-link]:          https://git-scm.com/

**Comment by diamante0018** [comment]
You are right, I used the incorrect syntax 🤯 

All good, I can confirm there is no longer a feature request by me.
