### ISSUE TITLE
Mirroring github repo results in much larger Gitea repo size

### ISSUE THREAD

**Issue by rh101** [go-gitea/gitea#28407]
### Description

Source repository: 
https://github.com/axmolengine/axmol

It's recently undergone changes that squashed commit history prior to November 2019, and a general clean-up (and perhaps rebase), which brought the repository from 1.2GB to 80MB or so.  

Checking this: https://api.github.com/repos/axmolengine/axmol

Results in this:
![image](https://github.com/go-gitea/gitea/assets/8603230/81a654f0-abe8-4b7f-b9dc-33f80e205bc1)

Now, if I use Gitea to mirror that repository, the result is not 80MB, but rather 1.2GB:
![image](https://github.com/go-gitea/gitea/assets/8603230/ab4e6999-9c5d-4587-89aa-22a5ffb05744)

Is there anything I can do to fix this? Did I miss some setting, or is there something that needs to be fixed on Github's side to sort out this issue?

To reproduce:
1 - Select New Migration via the UI
2 - Select Github, then fill out the info:
![image](https://github.com/go-gitea/gitea/assets/8603230/9be28d21-df49-4c5f-a364-56ec34f0bd73)

### Gitea Version

1.21.1

### Can you reproduce the bug on the Gitea demo site?

Yes

### Git Version

2.40.1

### How are you running Gitea?

This issue can be reproduced using the https://try.gitea.io/ site.

Personally running Gitea from the official docker image on a NAS.

### Database

PostgreSQL

**Comment by yp05327** [comment]
Migrate repo from other places, will exec the following cmd:
```
git clone --mirror https://github.com/axmolengine/axmol
```
You can try this command in your local. You will see the size will be about 1.2GB.
Without `--mirror`, it will be about `80MB`
```
git clone https://github.com/axmolengine/axmol
```

**Comment by rh101** [comment]
> Migrate repo from other places, will exec the following cmd:
> 
> ```
> git clone --mirror https://github.com/axmolengine/axmol
> ```
> 

Thank you for testing that. I'll close this given it is an issue with the source repo, and not Gitea.
