### ISSUE TITLE
Actions workflows list should show workflow names

### ISSUE THREAD

**Issue by alekitto** [go-gitea/gitea#28405]
### Description

Hi there,
Thanks for the great project!

I’ve enabled actions in a few repositories, and I noticed that the workflow list shows the filename of the workflow even if the name is set.
I think that the name should be shown instead if set on the root level of the workflow (and if the workflow itself is parseable) and use the filename only as fallback.

### Screenshots

![IMG_8247](https://github.com/go-gitea/gitea/assets/1257206/bb3a1cc0-e271-43db-bc0f-37a6e260e22e)

This is a screenshot of a random repository on the demo site

### Gitea Version

1.21

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

N/A

### Browser Version

N/A

**Comment by yp05327** [comment]
Maybe duplicated: #25912
