### ISSUE TITLE
using a native gitea emoji causes error 500

### ISSUE THREAD

**Issue by flare04** [go-gitea/gitea#28414]
### Description

When leaving a comment and adding a gitea emoji causes a error 500

Dec 11 17:51:51 hammerhead gitea[2670978]: 2023/12/11 17:51:51 [65
76b187] router: completed POST /<org>/<repo>/pulls/192/files/reviews/comments f
or <ip address>:54076, 500 Internal Server Error in 72.6ms @ repo/pull_review
.go:52(repo.CreateCodeComment)

### Gitea Version

Gitea version 1.19.3 built with GNU Make 4.1, go1.20.4 : bindata, sqlite, sqlite_unlock_notify

### Can you reproduce the bug on the Gitea demo site?

Yes

### Git Version

git version 2.39.3

### Operating System

Rocky Linux release 8.9 (Green Obsidian)

### How are you running Gitea?

We run gitea using systemd, from a download from website

### Database

SQLite

**Comment by lunny** [comment]
What's the emoji? Can you paste it here?

**Comment by flare04** [comment]
![image (11)](https://github.com/go-gitea/gitea/assets/1712083/499ae675-1208-4753-90d9-fce319d7c652)
Facepalm was the icon

**Comment by wxiaoguang** [comment]
https://docs.gitea.com/help/faq#why-are-emoji-broken-on-mysql

![image](https://github.com/go-gitea/gitea/assets/2114189/807925a6-c24e-4412-829d-fee2bd99d002)

**Comment by flare04** [comment]
We are using sqlite, is that applicable to the MYSQL issue as well ?

**Comment by wxiaoguang** [comment]
SQLite is not affected by it, and I have never seen emoji-related bugs with SQLite.

Could you provide more details?

1. 1.19.x is quite out-dated. Could you try 1.21.x?
2. Are there more related logs? I guess there shouldn't just be one line saying `500 Internal Server Error`.
3. Could you provide a reproducible setup with detailed steps? Then other people could try to reproduce.

**Comment by wxiaoguang** [comment]
No more feedback, I think this issue can be closed, feel free to reopen if there are more clues.

**Comment by flare04** [comment]
Sorry for being late to respond
You are corect we do use mysql will fix this up
