### ISSUE TITLE
Would there be any network or efficiency limitations if users are required to upload through Gitea?

### ISSUE THREAD

**Issue by eastonsuo** [go-gitea/gitea#28417]
Perhaps metadata could be stored using a 'verify' action after being stored in S3. 
Would there be any network or efficiency limitations if users are required to upload through Gitea?

_Originally posted by @eastonsuo in https://github.com/go-gitea/gitea/issues/28410#issuecomment-1849495319_

**Comment by lunny** [comment]
And another problem is the uploading need secrets which should be kept on backend. So uploading from git lfs directly should not work.

I think the performance is good enough. Why don't you try it before asking the question?
