### ISSUE TITLE
Team permission `read` is ignored if all permission fields are `none`

### ISSUE THREAD

**Issue by YannMagnin** [go-gitea/gitea#28434]
### Description

When I try to change a team permission to `read`, the request is completely ignored if all fields of the permission map are set to `none`. I understand the idea behind this mechanism, but since the description of the `read` status is `Members permissions will be decided by below permission table` I'm questioning if its not a bug?

Would it be possible to explicit the `read` permission even if all fields are set to `none` ?

### Gitea Version

1.21.1, 1.21.2

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

Linux Mint, EndeavourOS

### How are you running Gitea?

Official binaries, and running from systemd and command-line

### Database

SQLite

**Comment by yp05327** [comment]
What do you mean `if all fields of the permission map are set to none`, normally they should not be `none`. 🤔
