### ISSUE TITLE
Allow to specify branch masks to exclude from recently pused branch notifications

### ISSUE THREAD

**Issue by lafriks** [go-gitea/gitea#28447]
### Feature Description

Currently if there are multiple branches that are never merged into default, like `release/*` etc pushing changes to them shows recent branch notification with button to create new PR for 6 hours that takes up quite much space for whole working day.

There could be two ways to implemented this:
1) do not show notifications for branches that are protected (like when setting branch protection for `release/*` would not show notification to create PR for these branches)
2) Allow to specify global (app.ini) setting with wildcard to what branches always ignore for this notification, for example `main,release/*`

**Comment by lafriks** [comment]
Fixed in #31748

**Comment by wolfogre** [comment]
👍 Oh right, it can be done by just protecting branches.
