### ISSUE TITLE
cli.HelpFlag = nil can be used now when update urfave/cli to v2.26.0

### ISSUE THREAD

**Issue by dacheng-gao** [go-gitea/gitea#28444]
### Description

In fact, it's not a bug but rather a TODO that needs attention. I've noticed a TODO at cmd/main.go:L53. Fortunately, the related issue on urfave/cli has been resolved in version v2.26.0. Therefore, it should be safe for us to update the version and comment out the TODO.

The issue was tracked here: [urfave/cli/issues/1794](https://github.com/urfave/cli/issues/1794), and the fix is included in the release: [v2.26.0](https://github.com/urfave/cli/releases/tag/v2.26.0).

If you find this proposal suitable, I'll proceed with a minor fix.

### Gitea Version

main

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

Actually I'm not running Gitea.

### Database

None

**Comment by wxiaoguang** [comment]
Thank you for your report.

It doesn't seem a easy work to propose a "minor fix", because it has a long story .....

My decision is to just remove that code. ->  Improve CLI code #28482
