### ISSUE TITLE
Deleting repos from the Admin-panel resets all search filters

### ISSUE THREAD

**Issue by bkcsoft** [go-gitea/gitea#2844]
- Gitea version (or commit ref):  2406094 (https://try.gitea.io)
- Git version: 2.13.5
- Operating system: Debian (Docker)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

When deleting repos from the admin-panel, all search filters (search name, sort order, etc) are reset because on deletion we don't pass those in.

**Comment by adelowo** [comment]
Fixed in #6033
