### ISSUE TITLE
Wrong checkbox mark render

### ISSUE THREAD

**Issue by KazzmanK** [go-gitea/gitea#28445]
### Description

All checkmarks across UI are rendered incorrectly.
On demo site it is displayed correctly.
Locally, on same browser it is not.
Styles seems to be close to equal

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/13328513/85d7e299-9dee-485a-b74f-cde470caa746)

### Gitea Version

1.21.2

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

Win11

### Browser Version

120

**Comment by wxiaoguang** [comment]
Check your local instance's assets.

The checkbox is provided by an embedded CSS font:

```
@font-face{font-family:Checkbox;src:url(data:application/x-font-ttf;charset=utf-8;base64,AAEAAAALAIAAAwAwT1MvMg8SBD8.........
```

**Comment by KazzmanK** [comment]
Font-face portion on CSS asset is identical

**Comment by wxiaoguang** [comment]
It doesn't seems a Gitea problem since the demo site works.

Please confirm your local instance's assets are 100% the same as the official release and your browser doesn't have special configurations.

If the problem still exists, please provide a reproducible setup with detail steps. Otherwise if there is no reproducible setup, other people couldn't know what happens.

**Comment by KazzmanK** [comment]
The problem that in my windows build this symbol is just `?` , but in try.gitea.io it is not
![image](https://github.com/go-gitea/gitea/assets/13328513/81ccf85a-5fd0-4382-a608-a24d3d4c9ae1)

on my instance it is 
![image](https://github.com/go-gitea/gitea/assets/13328513/de0c80e4-ad1c-48b8-9a78-2f0447cfc42d)

**Comment by wxiaoguang** [comment]
Which release are you using? (eg: how do you get your Gitea program?)

**Comment by wxiaoguang** [comment]
Which release are you using? (eg: how do you get your Gitea program?)

**Comment by KazzmanK** [comment]
Holly... it was our fault. Sorry for disturbing. Style was altered, although we are using official builds.
