### ISSUE TITLE
Duplicated commits in commit chart

### ISSUE THREAD

**Issue by raptyk** [go-gitea/gitea#28459]
### Description

I performed certain operations on a Git repository (changing commit comments), which caused new commit IDs to be generated. The structure of the repository remains identical, but the old commits are no longer available in the repository. 

For example, when I push to an empty repository in Gitea, they are not visible. However, the old Gitea repository displays everything twice in the "Commit chart" view. 

**Is there a way to force a re-read of all commits (refresh the repository)? 
Is it possible to delete these commits somehow from the database or clear the cache in Gitea?**

### Screenshots

![duplicated-commits](https://github.com/go-gitea/gitea/assets/5106486/485c96e2-ff4f-41c0-8ae2-704d716558ef)

### Gitea Version

1.21.1

### Can you reproduce the bug on the Gitea demo site?

No

### Browser Version

Chrome - latest

**Comment by wxiaoguang** [comment]
Maybe https://git-scm.com/docs/git-gc

**Comment by wxiaoguang** [comment]
No more feedback, I think this issue can be closed, feel free to reopen if there are more clues.
