### ISSUE TITLE
MINIMUM_KEY_SIZE_CHECK value wrongly evaluated

### ISSUE THREAD

**Issue by karolyi** [go-gitea/gitea#28451]
### Description

Hey,

when `MINIMUM_KEY_SIZE_CHECK = true` in the config (default), the UI settings will say:
![image](https://github.com/go-gitea/gitea/assets/987055/7f667d19-4465-4e3f-bdad-9acaad941963)

Which is false. Turning the option off will place a checkmark in place of the 'option disabled' icon.

I think the configuration option is badly evaluated and thus confusing. Or the option description is worded wrongly.

### Gitea Version

1.21.2

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

irrelevant

### How are you running Gitea?

In a FreeBSD jail.

### Database

MySQL/MariaDB

**Comment by karolyi** [comment]
Damn, I completely misunderstood. My bad.

**Comment by karolyi** [comment]
I thought I understood it wrong, but it seems I still was right.

Setting the option `MINIMUM_KEY_SIZE_CHECK = true` will result in "Disable Minimum Key Size Check = ✗"
Turning the option `MINIMUM_KEY_SIZE_CHECK = false` will result in "Disable Minimum Key Size Check = ✔"

Aside from it being worded completely confusing, it's evaluated wrongly too.

**Comment by wxiaoguang** [comment]
Regression of #13860

The old code has commented out the code.

![image](https://github.com/go-gitea/gitea/assets/2114189/7eab70e7-944a-4cc2-a30b-91c51589855e)
