### ISSUE TITLE
Adding Legal Pages does not work anymore (files in "public" directory not accessible)

### ISSUE THREAD

**Issue by King555a** [go-gitea/gitea#28463]
### Description

I created legal pages for my Gitea installation some time ago and it worked. I followed the documentation at https://docs.gitea.com/administration/adding-legal-pages

Today, after the update to 1.21.2, I noticed that the pages are not working anymore. I get a 404 error in the browser console and there is only a white page. The HTML files are still in the correct directory. I placed another (new) file there and it also did not work.

I don't know since which version this does not work anymore, maybe one of the last updates did this, not the current one.

### Gitea Version

1.21.2

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

2.43.0

### Operating System

Ubuntu 18.04.6 LTS x64

### How are you running Gitea?

Installed as a package and running as a systemd service with https://gitlab.com/packaging/gitea

### Database

MySQL/MariaDB

**Comment by wxiaoguang** [comment]
Yes, the document is outdated. You need to use path: /path/to/custom/public/**assets**/privacy.html
