### ISSUE TITLE
MigratePost: Clone: signal: killed

### ISSUE THREAD

**Issue by husky2017** [go-gitea/gitea#2847]
- Gitea version (or commit ref):  1.2.2 
- Git version:  git version 1.8.3.1
- Operating system: Centos 3.10.0-693.el7.x86_64 && 8G DDR3 I3-4160
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

2017/11/04 14:22:29 [...routers/repo/repo.go:107 handleCreateError()] [E] MigratePost: Clone: signal: killed

## Description
   Migration: https://github.com/torvalds/linux.git

   Get error..

   help me, thank you !!
...

**Comment by lafriks** [comment]
Most probably migration needs to be made asynchronous otherwise for large repositories it can timeout

**Comment by husky2017** [comment]
Mr.lafriks, thank you。visiting GitHub is very slow in China, so i need cache something。

**Comment by hetykai** [comment]
@lafriks Thank you, it looks like a good solution, I'll try it.

**Comment by davidak** [comment]
Does it solve the problem for you, @husky2017 @hetykai?

Then it can get documented at https://docs.gitea.io/en-us/troubleshooting/

And maybe configure it that way on demo instance.

**Comment by hetykai** [comment]
> Does it solve the problem for you, @husky2017 @hetykai?
> 
> Then it can get documented at https://docs.gitea.io/en-us/troubleshooting/
> 
> And maybe configure it that way on demo instance.

Yes, it works for me.

**Comment by lunny** [comment]
Please feel free to reopen it.
