### ISSUE TITLE
app.ini changes are reset after pod restart

### ISSUE THREAD

**Issue by zim32** [go-gitea/gitea#28476]
### Description

I found similar issue but it is closed and I can not comment. 
https://github.com/go-gitea/gitea/issues/24146

I am using minikube, install gitea using HELM without any changes.
I want to change ROOT_URL to my custom url,  but when I change app.ini and restart pod my changes got lost.

Steps to reproduce:

1) SSH  into minikube
`minikube ssh`

2) Become root
`sudo su`

3) Create dummy file to make sure file is there after restart
```
echo 'Dummy' > /tmp/hostpath-provisioner/default/gitea-shared-storage/gitea/conf/foo.txt
```

4) Modfidy app.ini. Change ROOT_URL to some custom url f.e. https://custom.local

5) Ctrl+D from minikube to host

6) Delete gitea pod
```
minikube kubectl -- delete pod gitea-YOUR_POD_ID
```

7) SSH  into minikube
`minikube ssh`

8) Make sure dummy file still exists 
```
stat /tmp/hostpath-provisioner/default/gitea-shared-storage/gitea/conf/foo.txt
```

9) Check /tmp/hostpath-provisioner/default/gitea-shared-storage/gitea/conf/app.ini file
```
cat /tmp/hostpath-provisioner/default/gitea-shared-storage/gitea/conf/app.ini | grep ROOT_URL
```

10) Custom url was discarded and default url is used
`ROOT_URL = http://git.example.com`

### Gitea Version

1.21.1

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

2.40.1

### Operating System

Ubuntu

### How are you running Gitea?

```
helm repo add gitea-charts https://dl.gitea.com/charts/
helm install gitea gitea-charts/gitea
```

### Database

PostgreSQL

**Comment by lunny** [comment]
Can you send this to help chart repository?

**Comment by zim32** [comment]
> Can you send this to help chart repository?

Which one? Can you send the link?

**Comment by zim32** [comment]
Solved by modifying values in custom values.yaml file like this:

```yaml
gitea:
  config:
    server:
      ROOT_URL: https://custom.domain
      DOMAIN: custom.domain
```
