### ISSUE TITLE
REST API /api/v1/admin/users?source_id=1 does not work

### ISSUE THREAD

**Issue by khmarbaise** [go-gitea/gitea#28475]
### Description

The given REST API end point does not give back anything.
```
root@Debian-bullseye-latest-amd64-base ~ # curl -H "Authorization: token XXXXXXX"  http://localhost:3000/api/v1/admin/users?source_id=1
[]
```
 But If I use `?sourceid=1` instead I got the following:
```
 curl -H "Authorization: token XXXX"  http://localhost:3000/api/v1/admin/users?sourceid=1
[{"id":1,"login":"administrator","login_name":"","full_name":"Administrator","email":"giteaadmin@soebes.team","avatar_url":"https://secure.gravatar.com/avatar/XXXXXX?d=identicon","language":"en-US","is_admin":true,"last_login":"2023-12-10T16:13:38Z","created":"2023-08-27T11:58:59Z","restricted":false,"active":true,"prohibit_login":false,"location":"","website":"","description":"","visibility":"private","followers_count":0,"following_count":0,"starred_repos_count":0,"username":"administrator"},{"id":3,"login":"khmarbaise","login_name":"","full_name":"Karl Heinz Marbaise","email":"khmarbaise@gitea.soebes.team","avatar_url":"https://gitea.soebes.team/avatars/XXXXX","language":"en-US","is_admin":false,"last_login":"2023-12-06T19:29:26Z","created":"2023-11-10T19:57:30Z","restricted":false,"active":true,"prohibit_login":false,"location":"","website":"","description":"","visibility":"private","followers_count":0,"following_count":0,"starred_repos_count":0,"username":"khmarbaise"}]
```
That mean in consequence the generate API documentation `https://server/api/swagger` is wrong.

### Gitea Version

1.21.0

### Can you reproduce the bug on the Gitea demo site?

Yes

### Git Version

2.40.1

### Operating System

Linux Debian-bullseye-latest-amd64-base 5.10.0-26-amd64 #1 SMP Debian 5.10.197-1 (2023-09-29) x86_64 GNU/Linux

### How are you running Gitea?

Running inside Docker container.

### Database

PostgreSQL

**Comment by yardenshoham** [comment]
That's expected. `sourceid` is not a valid parameter so it's ignored. When you query with `source_id=0` you should see some results.

**Comment by khmarbaise** [comment]
The problem is that the generated API documentation https://server/api/swagger is wrong. It shows exactly the parameter `source_id` which is wrong.. based on the given examples... Also see https://try.gitea.io/api/swagger#/admin/adminSearchUsers  there you see the given parameter `source_id` as described.

**Comment by yardenshoham** [comment]
The generated documentation is not wrong. `source_id` is the correct parameter. You are getting results with `sourceid` because it's ignored. The same will happen if you use any other Invalid query parameter, such as `sourceidreallyreal`.

**Comment by wxiaoguang** [comment]
yardenshoham is right and the document is right.

@khmarbaise  maybe you misunderstood the meaning of "source_id". If you do not have users who are created with "auth source (login source)" id=1, you won't see anything by `?source_id=1`
