### ISSUE TITLE
`GET /orgs/{org}/repos` lists only repos of an organization that enable code

### ISSUE THREAD

**Issue by VicOsewe** [go-gitea/gitea#28483]
### Description

The REST API only returns repos with `codeview` enabled in the settings.

### Gitea Version

1.21.0

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

Running inside Docker container.

### Database

PostgreSQL

**Comment by lunny** [comment]
It's by design. Github also doesn't support list all repositories. https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#list-organization-repositories

**Comment by KlavsKlavsen** [comment]
@lunny where in above link to github does it state that it doesn't in fact list all repositories? (it states that it returns all types by default)
and where in gitea docs does it state that getrepos - specificly does not in fact support returning all repos? Its not even that its not the default to return all (as it is for github) - its not possible to list the repos if codeview isn't enabled for it.

**Comment by eeyrjmr** [comment]
> @lunny where in above link to github does it state that it doesn't in fact list all repositories? (it states that it returns all types by default) and where in gitea docs does it state that getrepos - specificly does not in fact support returning all repos? Its not even that its not the default to return all (as it is for github) - its not possible to list the repos if codeview isn't enabled for it.

by the fact github doesn't has the concept of disabling codeview thus all repositories return code.
You could say Gitea offering a non-codeview repository is an enhancement (a good one) and thus this request is more of an enhancement not a bug

**Comment by KlavsKlavsen** [comment]
seriously? so you call it ListRepos.. and it doesn't in fact list all repos - and you consider that a feature? 

a repo is MORE than code (in both gitea and github) - and in github you get ALL repos - unless you choose repos of a specific type. 

Suggested solution IMHO would be to:
1)add a "type" filter - and default to all (like github does) - or 
2)remove the (un-mentioned in docs) filtering of repos shown, based on if they have code or not.

We'll gladly contribute a PR to remove the filtering out of repos that don't have "codeview" enabled - so it does what the docs say it does (and what you would expect).

Or do you seriously mean that the codeview setting - decides wether or not it is in fact a repo? (and thus should decide if its shown in repolist endpoint) ? If so - pls. expain why its still shown in repolist in UI?
 
If its shown in repolist in UI - it should be returned in repolist from API by default.

**Comment by KlavsKlavsen** [comment]
This isn't waiting on feedback from me afaik?

**Comment by delvh** [comment]
I do tend to agree that it seems rather weird that `ListOrgRepos` only returns repos where code is enabled.

@KlavsKlavsen the issue was closed because the label was never removed.
This seems to be caused especially by a miscommunication:
I think lunny's focus was the `does not list **all** repos`, while yours and the focus of the issue reporter was on `only repos with code enabled`.

However, as I said, I consider this to be a bug as well, thus I'm reopening this issue and removing the label.
PR fixes are always welcome.

**Comment by KlavsKlavsen** [comment]
Great. I'll ask @VicOsewe to submit a PR (she's also an employee of Obmondo.com :)
