### ISSUE TITLE
Mass import existing repositories

### ISSUE THREAD

**Issue by vasyakrg** [go-gitea/gitea#28497]
### Feature Description

gitlab already mass import from github.
gitea not.
Would love to move from gitlab to gitea, but there are so many repositories and it would be almost unrealistic to migrate all hands.

**Comment by lng2020** [comment]
I think you can write a script or search for the existing scripts.

**Comment by hramrach** [comment]
Sounds like #21049

**Comment by vasyakrg** [comment]
https://gitea.realmanual.ru/pub/gitea-importer

**Comment by lunny** [comment]
duplicated with #2569
