### ISSUE TITLE
"Explore" visible when disabled

### ISSUE THREAD

**Issue by JVimes** [go-gitea/gitea#28503]
### Description

I set `service.explore`'s `REQUIRE_SIGNIN_VIEW` but I still see the Explore link atop the login page. Clicking it doesn't go anywhere. Seems like a bug?

My config has:

```ini
[service.explore]
REQUIRE_SIGNIN_VIEW = true
```

### Gitea Version

1.21.1

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/6148201/ae4e6fbb-c52d-4d15-90e3-1ee4ac14137b)

### How are you running Gitea?

Self hosted in docker

### Database

SQLite

**Comment by yardenshoham** [comment]
`REQUIRE_SIGNIN_VIEW` doesn't disable Explore, it only makes it redirect to the login page when clicked if you are not logged in.

**Comment by JVimes** [comment]
Ah, thanks. I thought it would hide it from navbar since I wasn't signed in.
