### ISSUE TITLE
Workflow is stuck on completion in web interface

### ISSUE THREAD

**Issue by hakito** [go-gitea/gitea#28508]
### Description

I am running gitea actions for several builds on a windows server. After a certain point the web interface no longer captures output from the console.

The upcoming steps show as completed but also have no console output. The _Complete Job_ hangs although the Job succeeded in `act_runner.exe`.

Btw: I could not reproduce it locally on my test environment (with HTTP instead of HTTPS).

### Gitea Version

1.21.2

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/320853/15e6519f-91b0-4c68-9f1a-b038bea9189a)

![image](https://github.com/go-gitea/gitea/assets/320853/8e10d4ae-c9a6-477b-9305-69963f1c003a)

### Operating System

Docker

### How are you running Gitea?

Gitea server running in docker container from `gitea/gitea:latest`
act_runner.exe 0.2.6 runs on `windows:host` (Windows Server 2019 Version 1809 Build 17763.4737)

### Database

MySQL/MariaDB

**Comment by lng2020** [comment]
I think it's a duplicate of #28109

**Comment by hakito** [comment]
Maybe it's related. It says that it shows the job as running though all tasks have completed. In my case the task is not completing and also the console output is incomplete.

My workaround so far is to redirect the console output of the _verbose_ tasks to a file.

**Comment by lng2020** [comment]
Well, you're right. That issue is more like a data inconsistency and yours is more like a communication with gitea instance and act runner. I encounter the same issues occasionally too. Maybe it's about the design of act runner(I'm not really sure).

**Comment by hakito** [comment]
No it never completed.

I am further investigating the problem. So I registerd my local act_runner (Win 10 Pro 22H2). It completed without any problems.

Now I am running a debug build of act_runner and I get an error at:

https://gitea.com/gitea/act_runner/src/commit/8c8a8ce40151ec5c28eeb80b24a83c9a509a3839/internal/pkg/report/reporter.go#L266

> error(*github.com/bufbuild/connect-go.Error) *{code: CodeInternal (13), err: error(*fmt.wrapError) *{msg: "marshal message: string field contains invalid UTF-8", err: error(google.golang.org/protobuf/internal/impl.errInvalidUTF8) *(*error)(0xc00038ea10)}, details: []*github.com/bufbuild/connect-go.ErrorDetail len: 0, cap: 0, nil, meta: net/http.Header nil, wireErr: false}

But the returned error is silently discarded in `RunDaemon`

**Comment by hakito** [comment]
We have a unit test wich compares _Apples_ with _Pears_ in german. On the Windows Server the content of the row is:

>  Passed TestCompare (\x8epfel,Birnen,-1) [< 1 ms]

`\x8` is not the character `Ä` . I think this might be the problem.

**Comment by delvh** [comment]
Ah, how I begin to hate MySQL.
Could you check whether the CHARSET in your DB is `utf8mb4`?

**Comment by hakito** [comment]
It is:

```
mysql> SELECT @@character_set_database, @@collation_database;
+--------------------------+----------------------+
| @@character_set_database | @@collation_database |
+--------------------------+----------------------+
| utf8mb4                  | utf8mb4_0900_ai_ci   |
+--------------------------+----------------------+
```

**Comment by hakito** [comment]
I opened an [issue in the act_runner repo](https://gitea.com/gitea/act_runner/issues/452). So this can be closed here I think.
