### ISSUE TITLE
Error save upload chunk with actions/upload-artifact@v2

### ISSUE THREAD

**Issue by hakito** [go-gitea/gitea#28506]
### Description

When using the `v2` version of upload artifact the upload fails:

```
gitea-1  | 2023/12/18 11:04:13 .../artifacts_chunks.go:45:saveUploadChunk() [I] [artifact] check chunk md5, sum: pcwU+a1IiInda19R0IZ8fw==, header:
gitea-1  | 2023/12/18 11:04:13 ...actions/artifacts.go:255:uploadArtifact() [E] Error save upload chunk: md5 not match
```

It seems that the md5 sum is missing for some reason. It works with  `v3`. But this version does not work with the `exec` command to test a workflow manually.

### Gitea Version

1.21.1

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

docker

### How are you running Gitea?

Using image gitea/gitea:latest
The `act_runner.exe` runs as a service on the windows machine.
The job runs on the host (`windows:host`)

### Database

None

**Comment by Zettat123** [comment]
Gitea always check md5 checksum when uploading artifacts.
https://github.com/go-gitea/gitea/blob/9483ccd463d31d465599eb4a0cc5621bc2caaf70/routers/api/actions/artifacts_chunks.go#L43-L53

However, md5 checksum was introduced in [actions/upload-artifact v3.1.0](https://github.com/actions/upload-artifact/releases/tag/v3.1.0). So the `v2` version does not work.

**Comment by hakito** [comment]
Well it's ok for me if only newer versions are working. But it's annoying that [v3 does not work with exec locally](https://gitea.com/gitea/act_runner/issues/449) :-(

Should we close this issue here?
