### ISSUE TITLE
Allow customizing messages in `cmd/serv.go`

### ISSUE THREAD

**Issue by sepsol** [go-gitea/gitea#28517]
### Feature Description

Allow customizing responses sent to clients from `cmd/serv.go`, especially messages from [this switch block](https://github.com/go-gitea/gitea/blob/4ea522fecfd8f2d6b51466cb9ab6772f4594bf2e/cmd/serv.go#L172-L179):

```go
func runServ(c *cli.Context) error {
	// ...
	switch key.Type {
	case asymkey_model.KeyTypeDeploy:
		println("Hi there! You've successfully authenticated with the deploy key named " + key.Name + ", but Gitea does not provide shell access.")
	case asymkey_model.KeyTypePrincipal:
		println("Hi there! You've successfully authenticated with the principal " + key.Content + ", but Gitea does not provide shell access.")
	default:
		println("Hi there, " + user.Name + "! You've successfully authenticated with the key named " + key.Name + ", but Gitea does not provide shell access.")
	}
	// ...
}
```

This would be useful for both localization as well as adding custom branding.

### Screenshots

```
$ ssh -T git@GIT_SERVER
Hi there, USER_NAME! You've successfully authenticated with the key named KEY_NAME, but Gitea does not provide shell access.
If this is unexpected, please log in with password and setup Gitea under another user.
```

**Comment by lunny** [comment]
It's a small change. Maybe you can hold them in your fork. I don't think it's necessary to have a configuration for that.

**Comment by sepsol** [comment]
I would argue that It'd still be useful for rebranding a custom Gitea instance. It'd be great if it took `APP_NAME` from the `custom/conf/app.ini` or something like that.

**Comment by wxiaoguang** [comment]
If you would like to rebrand, you would need to change a lot, but not only these strings. Theoretically you have to maintain your own changes.

APP_NAME is for the whole instance's name, it isn't for rebranding.
