### ISSUE TITLE
Failed to push after upgrading to 1.2.3 from 1.1.3

### ISSUE THREAD

**Issue by jbub** [go-gitea/gitea#2851]
- Gitea version (or commit ref): 1.2.3 (docker)
- Git version: 2.15.0
- Operating system: ubuntu 16.04 (docker)
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist: https://gist.github.com/jbub/1900e74fb2625506fcd5cde5f3d669cd

## Description

After upgrading from 1.1.3 to 1.2.3 i receive and error on push to repo: `UpdatePublicKey: Failed to update public key: EOF`, i already tried running "Resync pre-receive, update and post-receive hooks of all repositories.", nothing helps.

Thank you

**Comment by lafriks** [comment]
Check your local root url value in app.ini

**Comment by jbub** [comment]
Thank you, seems like i do not specify it so it should be the default of:
`LOCAL_ROOT_URL = %(PROTOCOL)s://%(HTTP_ADDR)s:%(HTTP_PORT)s/`

**Comment by jbub** [comment]
I can see this in the logs:

```
[Macaron] 2017-11-04 17:30:47: Started POST /api/internal/ssh/17/update for 127.0.0.1
[Macaron] 2017-11-04 17:30:47: Completed /api/internal/ssh/17/update 403 Forbidden in 1.645482ms
```

**Comment by lafriks** [comment]
@jbub does your app.ini file contains `INTERNAL_TOKEN`? If not gitea needs write permissions to app.ini file at least once when starting to generate it

**Comment by jbub** [comment]
Seems like its working now, dont know what happened, did not really change anything. Thanks anyway.

**Comment by jbub** [comment]
@lafriks yes it does have the `INTERNAL_TOKEN`

**Comment by klingtnet** [comment]
I've had the same issue:

```sh
$ git push
Gitea: Internal error
UpdatePublicKey: Failed to update public key: EOF
error: failed to push some refs to 'gitea@git.klingt.net:alinz/heft.git
```
the push still succeeded, though.
I could fix this by running `Rewrite '.ssh/authorized_keys' file (for Gitea SSH keys). There is no need to do this if you are using the built-in SSH server.` from the admin dashboard.

**Comment by klingtnet** [comment]
UPDATE: If anybody still faces this issue—maybe with gitea 1.4.1—then try to restart gitea. Gitea accepted my SSH keys after the restart, again.

**Comment by yobert** [comment]
This happened to me also, exactly the same way. Gitea version 1.5, using built in SSH server. After it ran for a week, I had to restart it to get SSH push to work again. Same 403 error on the API calls.
