### ISSUE TITLE
Let markdown editor continue lists on enter

### ISSUE THREAD

**Issue by unmovable-october-barricade** [go-gitea/gitea#28513]
### Feature Description

When writing a list, checklist, or numbered list in issue markdown (e.g. using -, - [ ], 1. syntax at the start of the line), it would be awesome to have the editor automatically add that syntax at the beginning of the next line when typing enter.
Basically, I'd like the same behavior that is already supported on github.

**Comment by wxiaoguang** [comment]
Fixed by #31406
