### ISSUE TITLE
MIPS-le version not working

### ISSUE THREAD

**Issue by viktike** [go-gitea/gitea#2852]
- Gitea version (or commit ref): master
- Git version: 2.9.3
- Operating system: Linux 2.6.22.19 mips GNU/Linux
- Database (use `[x]`):
  - [x] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
I was trying to run gitea on various CPU architectures, but it won't start on the MIPS little endian machine:
```
./gitea-master-linux-mipsle 
FATAL: kernel too old
Segmentation fault
```
The file command shows:
```
gitea-master-linux-mipsle: ELF 32-bit LSB executable, MIPS, MIPS32 version 1 (SYSV), statically linked, for GNU/Linux 3.2.0, BuildID[sha1]=5541ce6e9454f1d5e3e044dc40c4317b188b658b, not stripped
```
CPU: _BCM5300 rev 1 pkg 0 at 600 MHz_

Is the kernel really too old? (there is no way to upgrade it, it's read only) Or is the uClibc library is the problem, do I need glibc?

**Comment by kubeliv** [comment]
According to Go's minimum requirements, at least 2.6.23 is required.
Source: https://github.com/golang/go/wiki/MinimumRequirements#linux

**Comment by viktike** [comment]
Okay, but if I build this, manually, setting:
```
export GOOS=linux
export GOARCH=mipsle
```
Then it produces a different binary (notice no Linux 3.2.0 in this):
```
gitea: ELF 32-bit LSB executable, MIPS, MIPS32 version 1 (SYSV), statically linked, stripped
```

And it actually tries to run (tought not working):
```
2017/11/04 21:07:57 [T] AppPath: /opt/data/gitea
2017/11/04 21:07:57 [T] AppWorkPath: /opt/data
2017/11/04 21:07:57 [T] Custom path: /opt/data/custom
2017/11/04 21:07:57 [T] Log path: /opt/data/log
2017/11/04 21:07:57 [I] Gitea v1.1.0+722-gd91fe525
2017/11/04 21:07:57 [I] Log Mode: Console(Trace)
2017/11/04 21:07:57 [I] XORM Log Mode: Console(Trace)
2017/11/04 21:07:57 [I] Cache Service Enabled
2017/11/04 21:07:57 [I] Session Service Enabled
2017/11/04 21:07:57 [I] Run Mode: Development
2017/11/04 21:07:59 [I] Listen: http://172.24.20.1:3000
2017/11/04 21:07:59 [....io/gitea/cmd/web.go:123 runWeb()] [E] Failed to start server: listen tcp 172.24.20.1:3000: errno -9
```
Seems like the _gracehttp_ fails to create it's socket, due to some `bad file descriptor` error.
