### ISSUE TITLE
Smudge error, 404 after delete/recrate LFS repo

### ISSUE THREAD

**Issue by JVimes** [go-gitea/gitea#28521]
### Description

After deleting/recreating an LFS repo with the same name, pulls give

    Error downloading object: lfs.png (3c04f0d): Smudge error: Error downloading lfs.png (3c0...915): [3c0...915] Not Found: [404] Not Found

Repro steps:

1. Push a local repo that has an LFS file.
2. Delete the server repo.
3. Create a server repo with same name.
4. Push the local repo again.
5. Clone from server. Here I get "Smudge error... [404] Not Found".

### Gitea Version

1.21.1

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

Happens on self-hosted and Gitea.com.

### Database

None

**Comment by wxiaoguang** [comment]
You need to re-push all LFS files. Because LFS sync the files by your local "remote information"

->  How to force LFS to re-upload binary assets #2703

**Comment by JVimes** [comment]
Thank you. I needed `git fetch --prune` or similar before pushing the second time.
