### ISSUE TITLE
Regression in Automatic Issue/PR Referencing in Wiki Pages after Upgrading to 1.21.2

### ISSUE THREAD

**Issue by loncardom** [go-gitea/gitea#28526]
### Description

After upgrading from Gitea version 1.20.5 to 1.21.2, I encountered an issue with the automatic issue and pull request referencing feature in Wiki pages. Previously, in version 1.20.5, this functionality was operating as expected. However, since the update to 1.21.2, the feature appears to be non-functional.

I was able to reproduce this issue on a test repository: https://try.gitea.io/loncardom/test/wiki/Home.

This leads me to two questions:

1. Was this capability in Wiki pages an unintended feature in 1.20.5?
2. Is this change in functionality from version 1.20.5 to 1.21.2 a bug, or was it an intentional removal of the feature?

It's worth noting that the [official documentation](https://docs.gitea.com/usage/automatically-linked-references#issues-and-pull-requests) does not explicitly mention Wiki pages in the context of automatic linking, yet this feature was operational in the earlier version (1.20.5).

Gitea is awesome btw.
Thanks

### Gitea Version

1.21.2

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

Running Gitea through docker, though this issue is reproducible on try.gitea.io

### Database

None

**Comment by wxiaoguang** [comment]
A regression of

* #26365


Before, the wiki content also renders `#1` as an issue link.


![image](https://github.com/go-gitea/gitea/assets/2114189/03a91997-6327-4d34-9386-e76028d01445)
