### ISSUE TITLE
Cannot read properties of undefined (reading 'error')

### ISSUE THREAD

**Issue by alecov** [go-gitea/gitea#28538]
### Description

When trying to assign an issue to a project, this appears on console:

```
       POST https://xxxxxxxxxx/org/repo/issues/projects 404 (Not Found)
send @ jquery.js:9940
ajax @ jquery.js:9521
(anonymous) @ repo-issue.js:332
(anonymous) @ index.js?v=1.21.2:91
yl @ index.js?v=1.21.2:91
Ll @ repo-issue.js:331
(anonymous) @ repo-issue-list.js:72
(anonymous) @ index.js?v=1.21.2:225
Gc @ index.js?v=1.21.2:225
(anonymous) @ repo-issue-list.js:40
dispatch @ jquery.js:5145
un.handle @ jquery.js:4949
Show 4 more frames
Show less

repo-issue-list.js:80 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'error')
    at repo-issue-list.js:80:42
(anonymous) @ repo-issue-list.js:80
Promise.catch (async)
(anonymous) @ repo-issue-list.js:79
(anonymous) @ index.js?v=1.21.2:225
Gc @ index.js?v=1.21.2:225
(anonymous) @ repo-issue-list.js:40
dispatch @ jquery.js:5145
un.handle @ jquery.js:4949
Show 2 more frames
Show less
```

The only relevant log line seems to be this:
```
2023/12/19 18:58:07 ...eb/routing/logger.go:102:func1() [I] router: completed POST /org/repo/issues/projects for xxxxx:xxxxx, 404 Not Found in 40.7ms @ context/permission.go:59(web.registerRoutes.RequireRepoReader)
```

### Gitea Version

1.21.2

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

Arch

### How are you running Gitea?

Official Docker image

### Database

SQLite

**Comment by yp05327** [comment]
The log means user have no read permission of project unit, can you provide more information?

**Comment by alecov** [comment]
@yp05327 Sorry for the delay.

The user is owner of an organization. I have created a project and am trying to assign an issue to said project, then that error appears.

I'm running the official Gitea Docker image, and I have upgraded from an older installation. Not sure what more info I can provide.

I wonder if the user does not have some permission since this is an upgrade?

**Comment by yp05327** [comment]
There's a bug in old versions, but it should be fixed in #23675 🤔 

Maybe the root reason is broken data in DB. So if you can access your database, you can check `team_unit` table, whether the owner team's `access_mode` is 4.
ps: `org_id` is the IDs in `user` table, `team_id` is the IDs in `team` table.

**Comment by alecov** [comment]
> There's a bug in old versions, but it should be fixed in #23675 🤔
> 
> Maybe the root reason is broken data in DB. So if you can access your database, you can check `team_unit` table, whether the owner team's `access_mode` is 4. ps: `org_id` is the IDs in `user` table, `team_id` is the IDs in `team` table.
> 
> Edited: Or in `access` table, whether your `access_mode` is 4.
> 

Thanks for the support.

It does look that all `access_mode`s are 4, except for IDs 6 and 7 (looks unused?):
PS: my user is ID 1.

```sqlite
sqlite> select * from team_unit;
id|org_id|team_id|type|access_mode
1|3|1|1|4
2|3|1|2|4
3|3|1|3|4
4|3|1|4|4
5|3|1|5|4
6|3|1|6|1
7|3|1|7|1
8|3|1|8|4
9|3|1|9|4

sqlite> select * from team;
id|org_id|lower_name|name|description|authorize|num_repos|num_members|includes_all_repositories|can_create_org_repo
1|3|owners|Owners||4|10|2|1|1

sqlite> select * from access;
id|user_id|repo_id|mode
1|1|1|4
2|1|2|4
3|1|3|4
4|2|1|4
5|2|2|4
6|2|3|4
7|2|4|4
8|1|4|4
9|2|5|4
10|1|5|4
13|1|9|4
14|2|9|4
15|2|11|4
16|1|11|4
17|1|13|4
18|2|13|4
19|2|14|4
20|1|14|4
21|2|15|4
22|1|15|4
```

> If you change the log level to `trace`, I think you can get some logs like:
> 
> > Permission Denied: User xxx cannot read xxx in Repo xxx
> > User in Repo has Permissions: xxxx

Here's what I get:
```
2024/03/11 18:29:46 ...ontext/permission.go:63:func66() [T] Permission Denied: User <User 1:xxx> cannot read <UnitType:8:TypeProjects> in Repo <Repository 2:xxx>
User in Repo has Permissions: {AccessMode:owner Units:[0x4005344ea0 0x4005344f30 0x4005344ff0 0x40053450e0 0x4005345170] UnitsMode:map[]}
```

**Comment by yp05327** [comment]
Thanks for your report.
IIRC, I have met this issue before. I will check it.

**Comment by yp05327** [comment]
Can you also dump related data in `team_user` table? 🙏 
It seems that `GetUserRepoTeams` returns empty result.

**Comment by alecov** [comment]
> Can you also dump related data in `team_user` table? 🙏 It seems that `GetUserRepoTeams` returns empty result.

Absolutely, here it goes:

```
sqlite> select * from team_user;
id|org_id|team_id|uid
1|3|1|1
2|3|1|2
```

**Comment by yp05327** [comment]
It seems that projects unit is disabled.

**Comment by alecov** [comment]
OK. How do I enable it?

[app.ini.txt](https://github.com/go-gitea/gitea/files/14591245/app.ini.txt)

**Comment by alecov** [comment]
Hi. Would I have any further support for this?

I see nothing in the docs for "enabling" the projects unit, it looks like it is just always enabled. I can also edit the project (name, description, etc.), I presume this would be unavailable if Gitea had this unit disabled.

Any help is appreciated.

**Comment by lunny** [comment]
You can enabled projects on repository setting.

**Comment by alecov** [comment]
Duh. Indeed. Sorry for that, never suspected this would be a per-repo setting.

Closing this. Thanks for your patience and support.
