### ISSUE TITLE
Long package version name causes overflow

### ISSUE THREAD

**Issue by kittenswolf** [go-gitea/gitea#28534]
### Description

A version name the length of a SHA1 hash (40 chars) causes an overflow in the version list.

Repro on try.gitea.io: https://try.gitea.io/kw-test/-/packages/generic/package-test/6444144e52f72414b474981ba98f6211f66dbac9

### Screenshots

![grafik](https://github.com/go-gitea/gitea/assets/26834699/91e22ee4-3c32-49cf-a55c-89854246d35c)

### Gitea Version

1.21.2

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

Windows 10

### Browser Version

Firefox 120.0.1 (64-Bit)

**Comment by me-heer** [comment]
Hi, can I work on this?

**Comment by delvh** [comment]
sure
