### ISSUE TITLE
Git blame view still fails to display some "prior to change" markers

### ISSUE THREAD

**Issue by jessey-git** [go-gitea/gitea#28545]
### Description

This is a follow up to #28280 now that the instance is running a version with that fix.  Seems like some aspects of git history traversal are still being lost for files that have had quite the bit of history to them. As such many of the "prior to change" markers are not present or navigable.

Several examples all surrounding line 211 in the following file:
Gitea: https://projects.blender.org/blender/blender/blame/branch/main/source/blender/editors/interface/interface_ops.cc#L211
Github: https://github.com/blender/blender/blame/main/source/blender/editors/interface/interface_ops.cc#L211

### Gitea Version

1.21.2+424-g250f99304

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

Own build - https://projects.blender.org/

### Database

SQLite

**Comment by KN4CK3R** [comment]
Fix in #28572
