### ISSUE TITLE
[Feature] Automatically connect a package release to a specific repositiory (specifically looking at container registries right now)

### ISSUE THREAD

**Issue by ravensorb** [go-gitea/gitea#28540]
### Feature Description

Use the standard annotation (like github does) to connect a container release to specific repository.  The one that github uses is "org.opencontainers.image.source".  If this matches an existing repo within the system it will automatically link the two.

**Comment by KN4CK3R** [comment]
More or less a duplicate. See "Set repository link from package metadata" in #19270.

**Comment by ravensorb** [comment]
And I thought I had read through all of the open issues before posting! Thanks...
