### ISSUE TITLE
Delete branch failed after PR merged.

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#2854]
#![image](https://user-images.githubusercontent.com/81045/32411627-0f6f23b0-c21b-11e7-93c5-d15ee51849fc.png)

Steps:
1. Create a PR,
2. Push the PR's commits to master, Then push to the PR's branch. The PR will be automatically merged, it works fine.
3. Click `delete branch` on the merged PR, but it shows failed as the screenshot.

**Comment by lafriks** [comment]
@lunny I think it could be related to #2797

**Comment by lunny** [comment]
It seems it's resolved but I don't know which PR fixed this.
