### ISSUE TITLE
CreateIssuesIndexer: invalid argument

### ISSUE THREAD

**Issue by alphatr** [go-gitea/gitea#2855]
- Gitea version (or commit ref): v1.2.3
- Git version: 2.15.0
- Operating system: ArchLinux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist: https://gist.github.com/alphatr/c3344a2d7b9f5c17b46351052f765704

## Description

I use the vagrant to run gitea, and the `ISSUE_INDEXER_PATH` is in the shared folder, it will throw error, if I move the `ISSUE_INDEXER_PATH` to other path, it work ok.
...

**Comment by lunny** [comment]
You can delete the indexers folder and restart `gitea web`

**Comment by alphatr** [comment]
@lunny I do that and also received this error, see my log gist, create and open have received the error
