### ISSUE TITLE
gitea升级之后仓库消失 但仓库的文件都还在 请问如何恢复

### ISSUE THREAD

**Issue by vera-byte** [go-gitea/gitea#28573]
### Description

<img width="291" alt="image" src="https://github.com/go-gitea/gitea/assets/42960387/a3c85562-2ec6-4b89-9064-776ddab569c8">
<img width="1406" alt="image" src="https://github.com/go-gitea/gitea/assets/42960387/efde5bc1-1ada-4a53-bd71-11d75a24a23f">

### Gitea Version

1.21.1

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

docker compose 运行

### Database

MySQL/MariaDB

**Comment by lunny** [comment]
Please speak English.
