### ISSUE TITLE
Searching commits gives error 500

### ISSUE THREAD

**Issue by BenGH28** [go-gitea/gitea#28575]
### Description

I have gitea in docker container with searching/indexing enabled.  Upon searching the repo for a keyword I see an error 500 at the top of the page.

### Gitea Version

1.21.3

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/BenGH28/4858551f7e9fa9c367168e73f6f5fe9e

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/45215137/25cc45a4-e0c9-4be2-9555-fa6cc1a0472d)

### Git Version

2.40.1

### Operating System

Ubuntu

### How are you running Gitea?

I'm running the docker image with docker version 20.10.7

### Database

MySQL/MariaDB

**Comment by wxiaoguang** [comment]
Sorry for the bug. ->  Fix 500 error of searching commits #28576

**Comment by BenGH28** [comment]
Thanks for fixing it👍

**Comment by wxiaoguang** [comment]
The backport for 1.21 is

* #28579

After the merge and 1.21 branch finishes its CI work, you could use 1.21 nightly 🙏
