### ISSUE TITLE
Create pull request from an organization fork to a user repo failed.

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#2857]
When you fork a repo from a user to an organization, and then when create a pull request, you will get 404. It seems
```
{{if .SignedUser.HasForkedRepo .BaseRepo.ID }}{{.SignedUser.Name}}:{{end}}
```
didn't consider this situation.

![image](https://user-images.githubusercontent.com/81045/32415224-1320a122-c271-11e7-820e-11d50c7d95e2.png)

**Comment by renothing** [comment]
![screenshot from 2017-11-05 23-04-59](https://user-images.githubusercontent.com/261274/32416074-1166630a-c27e-11e7-997b-6e3c45135c41.png)
another two problem:
1: when my repo is forked from others, you can't send pull requet to myself across branchs
2: can't send pull request across forks

this is github
![screenshot from 2017-11-05 23-09-11](https://user-images.githubusercontent.com/261274/32416102-7ee3ec0e-c27e-11e7-9309-2ace0bc94976.png)

**Comment by lunny** [comment]
@renothing please fire another issue. We could resolve that via another PR.
