### ISSUE TITLE
Changelog for 1.21 missing CI approval notice

### ISSUE THREAD

**Issue by WeirdPtr** [go-gitea/gitea#28570]
### Description

When upgrading from 1.20.5 to 1.21.2 the CI pipeline status checks were ignored in PRs.

I checked the release notes before updating the instance [here](https://blog.gitea.com/release-of-1.21.0#breaking-changes), however nothing mentioned this change.

After investigating the database i found out, that when a repo had status checks enabled but no custom pattern was supplied it skipped the check.

When i updated the field `status_check_contexts` to `[*]` status checks worked again.

Query used to find "broken" branch status check entries:
```sql
select
    protected_branch.status_check_contexts,
    repository.id
from repository
     join protected_branch
       on protected_branch.repo_id = repository.id
where protected_branch.enable_status_check
      and ( protected_branch.status_check_contexts is null
            or protected_branch.status_check_contexts = 'null' )
```

### Gitea Version

1.21.2

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

2.20.1

### Operating System

Debian

### How are you running Gitea?

Docker Compose
Image: gitea/gitea:1.21

### Database

PostgreSQL

**Comment by kstruessmann** [comment]
Behaviour has changed as a result of this PR: Support for status check pattern (#24633)

**Comment by Zettat123** [comment]
The feature introduced in #24633 should be compatible with `status_check_contexts`. However, if one or more of `status_check_contexts` is not a legal glob expressions, `glob.Compile` will fail and the contexts cannot match.

 https://github.com/go-gitea/gitea/blob/21229ed2c8ed00f57100adf9ebc5f4a08da9a66e/routers/web/repo/pull.go#L653-L663

I'll try to make a PR to fix it
