### ISSUE TITLE
Fork self repository to self

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#2858]
Currently we can fork a repository to the owner himself. Steps:
1. fork user repository to an organization
2. fork organization forked repository to user and change a different name.

![image](https://user-images.githubusercontent.com/81045/32415334-4baeb130-c273-11e7-8c88-573628f23e9e.png)

![image](https://user-images.githubusercontent.com/81045/32415332-41685640-c273-11e7-9ac5-cbd743ef352e.png)

**Comment by lunny** [comment]
I have tested that github will not allow to do that second step.

**Comment by Morlinest** [comment]
And what if you fork your repo to org1, then fork from org1 to org2 and then fork from org2 back to you?

**Comment by lunny** [comment]
Yes, all these actions should be checked. Now your steps is ok.
