### ISSUE TITLE
Emoji and mention autocomplete shift the view

### ISSUE THREAD

**Issue by jpraet** [go-gitea/gitea#28595]
### Description

When triggering the emoji or mention autocomplete with `:` or `@` in a review comment, the view gets shifted under the sticky header.

### Screenshots

![Recording 2023-12-23 at 14 15 31](https://github.com/go-gitea/gitea/assets/2212615/b4ed622a-3a15-4e11-ad4e-30456e6fa62b)

### Gitea Version

1.22.0+dev-469-g33439b733

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

Windows

### Browser Version

Google Chrome 120.0.6099.130

**Comment by wxiaoguang** [comment]
->  Improve the scroll behavior for emoji/mention list #28597
