### ISSUE TITLE
Integrate Gitea with Sourcegraph

### ISSUE THREAD

**Issue by sgabenov** [go-gitea/gitea#28609]
### Feature Description

There is a product called Sourcegraph https://sourcegraph.com/ that can be integrated with any git host repository.
There was a thread in sourcegraph repo about gitea integration, but it seems that the work on it's integration is blocked. I wonder, are there any plans on it's integration. The initial issue is here: https://github.com/sourcegraph/sourcegraph/issues/343

Is anyone is interested in this integration?
<img width="1265" alt="image" src="https://github.com/go-gitea/gitea/assets/15741789/4712fffb-b0d4-455f-8c32-fd3f2f4ad00a">

**Comment by lunny** [comment]
I think it needs to be implemented by Sourcegraph side? Since there is no standard protocol?
What can we do in Gitea Side?

**Comment by techknowlogick** [comment]
Login with Gitea is already supported in sourcegraph because of oidc, however sourcegraph will need to be able to call Gitea API.
