### ISSUE TITLE
3MB - repo.upload limitation - still seeing issue - self-hosted

### ISSUE THREAD

**Issue by N0AGI** [go-gitea/gitea#28604]
### Description

hi - I have looked at and tried [this](https://github.com/go-gitea/gitea/issues/3586) issue report and the fix.  However,  I am still not seeing this issue fixed in my self-hosted docker instance.  

Please find the attached screenshots for reference.  

- my /data/conf/app.ini file has been updated w/ some crazy limits
- restarted my docker instance
- looked into my web.ui source and for whatever reason the file size/count limits still get server populated by lower default limits.

can someone please advise.  Thanks in advance

### Screenshots

<img width="371" alt="0" src="https://github.com/go-gitea/gitea/assets/74984418/480a95e6-7b1f-4919-b8b6-577fbcf0fcf2">
<img width="257" alt="0 2" src="https://github.com/go-gitea/gitea/assets/74984418/cfc19da2-af9e-4b3e-8d24-f4931b8f972f">
<img width="932" alt="0 1" src="https://github.com/go-gitea/gitea/assets/74984418/96790cae-b9d1-49e5-bc87-c98ef1197dbe">
<img width="632" alt="1" src="https://github.com/go-gitea/gitea/assets/74984418/6f293c40-aef4-486c-a29c-d0ac5ecadabd">

### Gitea Version

1.20.1 built with GNU Make 4.4.1.go1.20.6

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

Windows 11, firefox browser

### Browser Version

firefox 121.0 (64-bit)

**Comment by lng2020** [comment]
I think it's `FILE_MAX_SIZE` under `repository.upload`
https://docs.gitea.com/next/administration/config-cheat-sheet#repository---upload-repositoryupload

**Comment by N0AGI** [comment]
Thank you. I shall give that a try in a bit.

**Comment by N0AGI** [comment]
> I think it's `FILE_MAX_SIZE` under `repository.upload` https://docs.gitea.com/next/administration/config-cheat-sheet#repository---upload-repositoryupload

hi @lng2020 - that worked.  I somehow managed to overlook the setting.  Thank you again very much
