### ISSUE TITLE
A dependency npm library `citeproc` which is licensed under CPAL or AGPL. I think it's not compatible with MIT. We need to revert this PR or use another library instead.

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#28614]
This PR introduced a dependency npm library `citeproc` which is licensed under CPAL or AGPL. I think it's not compatible with MIT. We need to revert this PR or use another library instead.

_Originally posted by @lunny in https://github.com/go-gitea/gitea/issues/19999#issuecomment-1869262439_

**Comment by jolheiser** [comment]
https://github.com/go-gitea/gitea/pull/21815#issuecomment-1315018744
