### ISSUE TITLE
github.run_id does not match run id

### ISSUE THREAD

**Issue by GammaGames** [go-gitea/gitea#28621]
### Description

Based on this thread: https://github.com/orgs/community/discussions/26965 I would expect to be able to use `${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}` to create a link to the action run. When using this on a server it is inserting as 272, 273, etc instead of the actual 43, 44, etc which gives a 404 link.

### Gitea Version

1.21.2

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

Docker 

### Database

SQLite

**Comment by denyskon** [comment]
I think github.run_number is the right one - at least it works for me

**Comment by GammaGames** [comment]
You're right, thank you!
