### ISSUE TITLE
send pull requet across different repo's branch when repo is forked

### ISSUE THREAD

**Issue by renothing** [go-gitea/gitea#2862]
two problem:
**1: when my repo is forked from others, you can't send pull requet to myself across branchs**
![screenshot from 2017-11-05 23-04-59](https://user-images.githubusercontent.com/261274/32426795-cd97cf68-c2f7-11e7-9f3f-d0b3d42c0573.png)

**2: can't send pull request across forks (send pull requst between forks)**
this is github pull request across forks 
![screenshot from 2017-11-05 23-09-11](https://user-images.githubusercontent.com/261274/32426804-e426f902-c2f7-11e7-96a9-27cd60bcca6d.png)

**Comment by oscarlofwenhamn** [comment]
This would be a very good addition, and something that would improve Gitea drastically in my meaning. Hopefully it can be picked up soon, fingers crossed!

**Comment by 6543** [comment]
I'ts posible now

**Comment by oscarlofwenhamn** [comment]
Nice, great feature addition!
