### ISSUE TITLE
Forked repository is compared wrong

### ISSUE THREAD

**Issue by webjoel** [go-gitea/gitea#2863]
- Gitea version (or commit ref): cdc4600
- Git version: 2.7.4
- Operating system: Linux 64 Ubuntu
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

Comparison of changes / New Pull request is not comparing the forked repository, but rather the origin repository. (Image 1 and image 2).

When I change the URL manually the "compare" works as expected. (Image 3).

## Screenshots

Image 1:
![captura de tela de 2017-11-06 15-23-03](https://user-images.githubusercontent.com/1946348/32454910-c3e30590-c307-11e7-8c43-5794498c7989.png)

Image 2:
![captura de tela de 2017-11-06 14-49-42](https://user-images.githubusercontent.com/1946348/32454926-cc3f93a2-c307-11e7-8b90-5ed29a984f6b.png)

Image 3:
![captura de tela de 2017-11-06 14-49-34](https://user-images.githubusercontent.com/1946348/32454937-d39465ec-c307-11e7-9411-d31a1f8df090.png)

**Comment by lafriks** [comment]
@lunny could this be related to your latest changes?

**Comment by lunny** [comment]
@lafriks I will check it.

**Comment by zxjon22** [comment]
I've just come across this myself. I was in a fork and clicked the `New Pull Request` button and the pull request was created against the original repository, not the fork.

HTML for the `New Pull Request` button when in the fork looks like this

```html
<a class="ui green button " href="/[original]/Repo/compare/master...jon:master">New Pull Request</a>
```

... when it should be
```html
<a class="ui green button " href="/[fork]/Repo/compare/master...jon:master">New Pull Request</a>
```

**Comment by lunny** [comment]
Could not reproduce it on master, I will close this and feel free to reopen it.

**Comment by webjoel** [comment]
This can be tested in:

https://try.gitea.io/webjoel/teste2_1

Pressing in button "compare changes" (image 1). Result is comparassion of other repository (origin fork).

Please repon this issue.

**Comment by lunny** [comment]
Is this still a problem?

**Comment by zeripath** [comment]
I think this bug has been solved by me quite a while ago. Therefore I'm closing it.
