### ISSUE TITLE
act runner timezone can not work

### ISSUE THREAD

**Issue by yedajiang44** [go-gitea/gitea#28645]
### Description

Setting environment variables does not take effect
```
    environment:
      - TZ=Asia/Shanghai
```
Installing tzdata can solve the problem
```
apk install tzdata
```
So I want that to be done when building the image

### Gitea Version

 1.21.2 

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

docker

### Database

None

**Comment by lunny** [comment]
Should this be moved to act runner repository?

**Comment by yedajiang44** [comment]
no~the image is `gitea/act_runner`, make by gitea

**Comment by yp05327** [comment]
I think @lunny means move this issue to https://gitea.com/gitea/act_runner

**Comment by yedajiang44** [comment]
oooooh~ I got it...
