### ISSUE TITLE
Proposal: Merge docs into this repo

### ISSUE THREAD

**Issue by techknowlogick** [go-gitea/gitea#2865]
This is a thought I have had (as well as it has been mentioned in discord by others), but perhaps the docs repo should be merged into this repo.

Some pros of this:
* When submitting PRs, devs can submit docs in same commit (this reduces friction for su
* An extra step to drone can happen on merges that autobuild and push docs (to keep them fresh)

I'd be open to making a PR for this, however my (simple) approach would be to create a docs folder, and just dump a copy of HEAD into it, this may lose history though.

**Comment by lafriks** [comment]
docker yml also need to be updated so that docs site is updated from main repository

**Comment by andreynering** [comment]
Thanks for your suggestion. Here's my opinion:

I kind of like the idea for small projects. But Gitea is big and is cleaner to have code/issues/PRs separated IMHO.

Also, some Gitea users may not know Go, but may like to contribute to docs. They currently don't need to clone 5,700+ commits to do it.

> I'd be open to making a PR for this, however my (simple) approach would be to create a docs folder, and just dump a copy of HEAD into it, this may lose history though.

With Git Subtrees would be possible to merge the repos preserving the history.

**Comment by lafriks** [comment]
Idea for moving docs to main repo is to be able submit documentation together with updated code otherwise docs stay out of date

**Comment by lunny** [comment]
So maybe send docs commit from docs repo to gitea repo via giteabot when commit pushed to CI. We almost declaim docs repo and docs.gitea.io keep the latest documents. And you can find history docs on your gitea instance `/docs` .

**Comment by lafriks** [comment]
For me target is to get docs updated when new features are implemented and having it other repository just gets into way as nobody is willing to submit other PR to update docs

**Comment by techknowlogick** [comment]
Thinking about this now, I probably don't need to bring history over as when PRs are accepted they are squashed to that history would be lost anyway. So I'll submit a PR with what's in HEAD tonight.
