### ISSUE TITLE
Gamification: Add profile achievements (similar to GitHub profile achievements)

### ISSUE THREAD

**Issue by CodeShakingSheep** [go-gitea/gitea#28653]
### Feature Description

Just want to drop the idea to add profile achievements to Gitea as I really like the ones on GitHub and it would incorporate some gamification on Gitea. Inspired by [GitHub achievements](https://github.com/Schweinepriester/github-profile-achievements). I'm aware that this is quite a huge request. Might make sense to just start with a few simple ones in the beginning. Curious about thoughts / ideas.

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/19874562/926f588f-a593-4ec8-a96a-6e9bd66424c9)

**Comment by delvh** [comment]
I think that is already implemented, but on a `decide yourself when someone gets a badge` basis.

**Comment by techknowlogick** [comment]
Yup, closing as badges exist. And as @delvh, you can add badges to users based on your preferences. (right now, it's via DB inserts, but I'm working on an API endpoint to make it easier to manage)

**Comment by CodeShakingSheep** [comment]
Is this documented anywhere? I couldn't find it. Thanks.

**Comment by delvh** [comment]
At the moment only by looking through the PR adding them: https://github.com/go-gitea/gitea/pull/20607
