### ISSUE TITLE
Search inside a repo gives error 500

### ISSUE THREAD

**Issue by RastaTaz** [go-gitea/gitea#28655]
### Description

When performing a search inside a repo, I have a 500 error response, then page footer and then some additional content somewhat related to search results (but unreadable): see screenshot.
Error shown in the page is the same as container logs in gist link.

Can't reproduce issue on demo as search box doesn't show in version used by demo.

### Gitea Version

1.21.3 (= "latest" docker image as of date of current issue opening)

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/RastaTaz/87d8d10e01a0668078b7942c622fc15e

### Screenshots

![2023-12-29_19-46](https://github.com/go-gitea/gitea/assets/28950854/c20c2bdc-6d71-4afd-8bd0-8a3b6967fffc)

### Git Version

The one in the official docker image

### Operating System

Ubuntu 22.04

### How are you running Gitea?

I used official docker image with external SQL server (MariaDB installed on docker host) behind NginX reverse proxy.

### Database

MySQL/MariaDB

**Comment by KN4CK3R** [comment]
That's already fixed in #28576 but not released.

**Comment by wxiaoguang** [comment]
(so you can use the 1.21 nightly release)
