### ISSUE TITLE
TortoiseGit issue tracker plugin

### ISSUE THREAD

**Issue by amuagarwal** [go-gitea/gitea#28650]
### Feature Description

Looking for issue tracker something like https://tortoisegit.org/docs/tortoisegit/tgit-dug-bugtracker.html which allow user to select issue assigned from gitea repo and commit the changes with some configurable pre-define commit message

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/7331483/fb698f32-b505-4049-8bfc-a66f4d1edb5e)

**Comment by KN4CK3R** [comment]
You need a TortoiseGit plugin for that which can talk to the service. Gitea (as a server, this repo) already offers an api which this plugin can use.
As this is the wrong place to ask for such a plugin, I will close this issue.
