### ISSUE TITLE
Docker: Backup fills up entire disk

### ISSUE THREAD

**Issue by mathius1111** [go-gitea/gitea#28669]
### Description

When creating a backup the disk is continuously written to until I stop it or it takes up the entire disk. The first time it wrote over 400GB of data for a new instance with one user and one 47 KiB repo.

I've tried a few different backup commands including:

Run on the server:

./gitea dump -c /data/gitea/conf/app.ini 

Run from WSL2:

docker exec -u git -it -w /tmp $(docker ps -qf "name=gitea-gitea-1") bash -c '/app/gitea/gitea dump -c /data/gitea/conf/app.ini --file /tmp/gitea-dump.zip'

docker exec -u git -it -w /data/gitea/backups $(docker ps -qf name="gitea-gitea-1") bash -c '/app/gitea/gitea dump -c /data/gitea/conf/app.ini'

### Gitea Version

1.21.3 built with GNU Make 4.4.1, go1.21.5 : bindata, timetzdata, sqlite, sqlite_unlock_notify

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

Windows via Docker

### How are you running Gitea?

Docker image: gitea/gitea:latest

### Database

SQLite

**Comment by joshtrichards** [comment]
Any chance your `log/` folder has some overly large log in it? Or, possibly, any of the folders that get included in the dump:

https://docs.gitea.com/administration/backup-and-restore#backup-command-dump

Maybe do some digging around with `du` for the folders listed just to rule out the obvious.
