### ISSUE TITLE
wiki default branch name is "master" and is not configurable

### ISSUE THREAD

**Issue by na-Itms** [go-gitea/gitea#28685]
### Description

Hello,
When creating a new repository and creating its wiki from the web interface, the wiki repository's default branch is "master". This cannot be seen on the web interface, but it appears when cloning the wiki.

This is reproducible on the test instance, see for instance https://try.gitea.io/na-Itms/wikibranchname.wiki.git

This is surprising and inconsistent with git's defaults, as well as gitea's own default for `repository.DEFAULT_BRANCH` (#19354).

I assume the default should be `main`, and this should be configurable either with a configuration key (`repository.DEFAULT_WIKI_BRANCH` maybe?), or in the repository's settings on the web interface.

### Gitea Version

1.22.0+dev-511-g657b23d63

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

I am using try.gitea.io to demonstrate the issue. I am personally running the latest release of gitea on Ubuntu, installed from binary.

### Database

MySQL/MariaDB

**Comment by Arduhat** [comment]
Why is this a problem...? Master is a typical name for default branch

**Comment by techknowlogick** [comment]
> Why is this a problem...? Master is a typical name for default branch

We allow for branch name customization elsewhere, and so it would be expected that the same could apply to wikis too
