### ISSUE TITLE
Self-hosted Gitea has been getting slow since last month.

### ISSUE THREAD

**Issue by pramilaniroshan** [go-gitea/gitea#28698]
### Description

Hi team,

We have been using a self-hosted Gitea for almost a year now. We are utilizing Docker and Nginx reverse proxy deployment. For user storage, we are using LDAP. The issue we've encountered is that since last month, we have been experiencing timeout errors during user login, PR creation, code reviews, and PR merging. Occasionally, we also encounter 500 errors when creating PRs. We have a significant number of open PRs in our repositories.also I notice that if someone merged a PR, after merge conflict checking last almost 1hour. What could be the reason for this?

Regards,
Pramila

### Gitea Version

1.18.0

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/pramilaniroshan/1dcad69217f130c4e09c934cfca7c0ce

### Git Version

git version 2.36.3

### Operating System

NAME="Amazon Linux" VERSION="2" ID="amzn" ID_LIKE="centos rhel fedora" VERSION_ID="2" PRETTY_NAME="Amazon Linux 2"

### How are you running Gitea?

 Run from docker
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.16.2
PRETTY_NAME="Alpine Linux v3.16"

### Database

MySQL/MariaDB

**Comment by ganeshkbhat** [comment]
i am not a maintainer but just checking back. have you tried restarting the server - irrespective of codebase issues or not?

**Comment by lunny** [comment]
Please upgrade to recent stable version. i.e. v1.21.3

**Comment by pramilaniroshan** [comment]
Thank you very much, before upgrade We've mounted our Gitea volume on Amazon EFS.Additionally, can we check for any database slowness in our RDS? I'm not sure if this slowness is coming from that

**Comment by lunny** [comment]
From the line `2024/01/05 05:17:58 [6594f34d-14] router: slow      GET /thameera/device-mgt-core/src/commit/16d2a062da82ed05c611ba2aa5c20315546aecdc/features/dynamic-client-registration/org.wso2.carbon.dynamic.client.registration.server.feature/pom.xml for 47.128.120.145:0, elapsed 3456.0ms @ context/repo.go:429(context.RepoAssignment)`, we can see it should be from disk(EFS).
For AWS EFS, it has 3 modes. For some modes, it will limit your disk io rate. Maybe you can have a check for that.

**Comment by pramilaniroshan** [comment]
Everything is now working smoothly after fixing the EFS issues. Thanks
