### ISSUE TITLE
Unable to Push to NPM Package Registry

### ISSUE THREAD

**Issue by jreker** [go-gitea/gitea#28692]
### Description

I cannot push packages to the npm repo of my Organization and my personal account. I created the access tokens and so on as described in the documentation but it says that the permission to upload package is not permitted.
I got http 403:
(anonymized)

```
npm notice Publishing to https://git.gitea.com/api/packages/username/npm/ with tag latest and default access
npm ERR! code E403
npm ERR! 403 403 Forbidden - PUT https://git.gitea.com/api/packages/username/npm/packagename - no permission to upload this package
npm ERR! 403 In most cases, you or one of your dependencies are requesting
npm ERR! 403 a package version that is forbidden by your security policy, or
npm ERR! 403 on a server you do not have access to.
```

Can anybody help? Also with allowing anything for the token will not work.

### Gitea Version

1.21.2

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

Docker

### Database

MySQL/MariaDB

**Comment by lunny** [comment]
I cannot reproduce it in main branch

1 confirm your token have enough permissions. Check token scope contains `packages`
2 how did you run `npm publish`? Check your `.npmrc` configuration.

**Comment by jreker** [comment]
Hi lunny, 

thank you for your information. I figured it out. 
The problem was, that i specified the repository inside the package.json file:
```    "start": "tsc -w"
  },
  "repository": {
    "type": "git",
    "url": "https://gitea.company.com/organization/project.git"
  },
  "keywords": [
    "react",
```

When i remove this attribute the publish is successful. This URL is not public available, maybe that is the problem? The documentation says that is have to be public readable: https://docs.npmjs.com/cli/v10/configuring-npm/package-json#repository

Maybe thats was my problem.
