### ISSUE TITLE
Cannot clone local actions with self-signed cert

### ISSUE THREAD

**Issue by GammaGames** [go-gitea/gitea#28693]
### Description

My `app.ini` has the following:
```toml
[actions]
ENABLED = true
DEFAULT_ACTIONS_URL = self
```

And my runner's `config.yaml` has:
```yaml
runner:
  insecure: true
```

I have an action hosted on the server, but when I try to run the action with `uses: Actions/test-action@main` it fails with:

```
Extracting content to '/var/run/act/'
  ☁  git clone 'https://gitea-domain/Actions/test-action' # ref=main
  cloning https://gitea-domain/Actions/test-action to /root/.cache/act/Actions-test-action@main
Unable to clone https://gitea-domain/Actions/test-action refs/heads/main: Get "https://gitea-domain/Actions/test-action/info/refs?service=git-upload-pack": tls: failed to verify certificate: x509: certificate signed by unknown authority
Get "https://gitea-domain/Actions/test-action/info/refs?service=git-upload-pack": tls: failed to verify certificate: x509: certificate signed by unknown authority
```

### Gitea Version

1.21.3

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

Docker (both gitea and the runner)

### Database

None

**Comment by Zettat123** [comment]
It's a bug on the `act_runner` side. The [`insecure`](https://gitea.com/gitea/act_runner/src/commit/e14f42c40ac91d032c6a7c3e912646e55b2031a8/internal/pkg/config/config.example.yaml#L26-L27) option should work when cloning a repository from the Gitea instance

**Comment by Zettat123** [comment]
I've created a [pull request](https://gitea.com/gitea/act/pulls/92) to support cloning actions from the Gitea instance when the `insecure` option is `true`

**Comment by lunny** [comment]
Close as it's only act/act_runner related.
