### ISSUE TITLE
Start Page slow with large actions table

### ISSUE THREAD

**Issue by realslacker** [go-gitea/gitea#28707]
### Description

I am using Gitea v1.21.3, and my actions table is about 4.5G. I have 87 repos and belong to several orgs with additional repos.

When logging in the initial query to populate the start page takes 45 seconds to run. After adding two indexes the run time is down to 6.5 seconds... still a long time, but better.

New Indexes:

1. user table created index on:
     - id
     - visibility
     - keep_activity_private
     - type
2. team_user table created index on:
    - uid

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/552756/6eee5e66-e3ab-4dcc-9418-637cff96d2a7)

### Gitea Version

1.21.3

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

Windows 10

### Browser Version

Firefix 121.0

**Comment by techknowlogick** [comment]
Thanks for this report. Which DB are you using? And, just because I'm curious, how many rows are in the actions table, what timespan do they cover, and is the significant number of rows in the actions table primarily due to mirrors updating or some other reason?

**Comment by lunny** [comment]
Maybe duplicated #28155 and resolved by #28546

**Comment by realslacker** [comment]
@techknowlogick We are using MariaDB 11.1, there currently 6,140,941 records in the table. Records range from Sept 30 2019 to today. It looks like the majority of the operations are op_type = 5, which looks to me to be commits.

**Comment by lunny** [comment]
Since #28546 merged, I think this can be closed. Please feel free to reopen it if there is further information.
