### ISSUE TITLE
Alpine package registry: Not all possible fields are present in generated APKINDEX.tar.gz

### ISSUE THREAD

**Issue by joniw** [go-gitea/gitea#28704]
### Description

Hello,

in the current code for [generating the APKINDEX.tar.gz](https://github.com/go-gitea/gitea/blob/release/v1.21/services/packages/alpine/repository.go#L206) the following [supported fields](https://wiki.alpinelinux.org/wiki/Apk_spec#APKINDEX_Format) are not created and saved:

- k: - provider priority, integer (corresponds to provider_priority in PKGINFO), optional
- i: - install if (corresponds to install_if in PKGINFO, concatenated by spaces into a single line)

It would be nice if these fields can be added. I noticed the problem when installing the salt-minion package and the corresponding startup package (salt-minion-openrc) was not installed.

With regards
Joniw

### Gitea Version

1.21

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

Test instance in Kubernetes

### Database

PostgreSQL

**Comment by mintyhippoxyz** [comment]
@joniw Can you manually install the sub package or do I have it even worse?

```
$ apk add vault vault-openrc
ERROR: unable to select packages:
  vault-openrc (no such package):
    required by: world[vault-openrc
```

**Comment by joniw** [comment]
In my case there is no problem to install the package manually when i workaround #26691.

At this moment i rewrite the architecture of built packages with the [workaround described](https://github.com/go-gitea/gitea/issues/26691#issuecomment-1887978354) in the issue.

**Comment by mintyhippoxyz** [comment]
Thanks. I do seem to have something more going on. My openrc sub package isn't even listed in the APKINDEX so I'll have to dig into that more.
