### ISSUE TITLE
Compatibility with seaweedfs (s3) broken

### ISSUE THREAD

**Issue by infinitisno** [go-gitea/gitea#28714]
### Description

Hello.

It seems [this commit](https://github.com/go-gitea/gitea/commit/7818121d50fd9ce3739c3d2221402841781e04b9) broke the compatibility with seaweedfs s3.

Gitea fails to start with following error in the logs: `[F] code.gitea.io/gitea/modules/storage.Init failed: expected element type <VersioningConfiguration> but have <ListBucketResult>`

I'm using simple configuration which was working fine before:
```
STORAGE_TYPE = "minio"
SERVE_DIRECT = true
MINIO_ENDPOINT = "s3.guix.uz:443"
MINIO_ACCESS_KEY_ID = "#minio_access_key_id#"
MINIO_SECRET_ACCESS_KEY = "#minio_secret_access_key#"
MINIO_BUCKET = "gitea"
MINIO_USE_SSL = true
```

It should be easy to reproduce if you have seaweedfs instance.

### Gitea Version

Gitea version 1.21.2 built with go1.21.5 : pam, sqlite, sqlite_unlock_notify

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/0x450x6c/525b74eba4c8ef40eb01dca9e54ae38b

### Operating System

nixos

### How are you running Gitea?

I'm using nixos's gitea module.

### Database

PostgreSQL

**Comment by dajrivera** [comment]
Get Bucket Versioning was implemented in seaweedfs in https://github.com/seaweedfs/seaweedfs/pull/4998, included in seaweedfs 3.60. However, the implementation was returning a malformed response (reported in https://github.com/seaweedfs/seaweedfs/issues/5155).

The fix has been merged to the master branch and should be available in the next seaweedfs release.

For the meantime, I'm using the following in my nginx proxy as a workaround:

```
if ( $args ~ .*versioning.* ) {
    return 200 '<VersioningConfiguration xlmns="http://s3.amazonaws.com/2006-03-01/"><Status>Suspended</Status></VersioningConfiguration>';
}
```
