### ISSUE TITLE
Add a `--skip-db` option to `gitea dump`

### ISSUE THREAD

**Issue by JulienPalard** [go-gitea/gitea#28720]
### Feature Description

As [the docs says](https://docs.gitea.com/administration/backup-and-restore):

> Gitea admins may prefer to use the native the MySQL and PostgreSQL dump tools instead.

So it would be nice to have a `--skip-db` in `gitea dump` to avoid dumping the database twice per backup, saving a bit of time.

**Comment by maltegrosse** [comment]
Flags to skip or include certain objects would be great. As all my container are built automatically, I dont want to backup them. As container sizes can be quite heavy, a `--skip-packages` would be a nice feature.
