### ISSUE TITLE
Over-Escaped Wiki Page Title

### ISSUE THREAD

**Issue by mohammed90** [go-gitea/gitea#2872]
- Gitea version (or commit ref): 61f5c22
- Git version: 2.7.4
- Operating system: Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL): [Link to page](https://try.gitea.io/nobody/wiki_over-escape_bug/wiki/Home-%26-Test)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

The title of a Wiki page is over-escaped if it contains any special character. It's displayed properly on the main page of the Wiki, [here](https://try.gitea.io/nobody/wiki_over-escape_bug/wiki/_pages).

## Screenshots

<img width="470" alt="gitea wiki overescaped" src="https://user-images.githubusercontent.com/2636183/32508729-4d342050-c3fc-11e7-92e5-148de8fbe45e.png">

**Comment by makarchuk** [comment]
Problem is `Sanitatize` call in [this](https://github.com/go-gitea/gitea/blame/master/templates/repo/wiki/view.tmpl#L4) line.  
It was added 9 month ago, but I don't see why. I removed it and still can't get XSS 
![screenshot from 2017-11-19 15-23-39](https://user-images.githubusercontent.com/13999738/32990621-b38fa690-cd3d-11e7-87fe-a6bef304aebc.png)
