### ISSUE TITLE
Git push lfs file error: LFS: Client error 

### ISSUE THREAD

**Issue by alvin6233** [go-gitea/gitea#28738]
### Description

**error detail:**
LFS: Client error &{%!!(string=https) %!!(string=) %!!(*url.Userinfo=<nil>) %!!(string=code.test.org.cn) %!!(string=/digo/test.git/info/lfs/objects/ed79025f8bea018c8925f43b6304a27e462335b6ec5e6f8a222c2726153844b3/77474499) %!!(string=) %!!(bool=false) %!!(string=) %!!(string=) %!!(string=)}s(MISSING) from HTTP 413

**deploy**
gitea helm chart

### Gitea Version

1.21.2

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

Gitea was deployed through helm and the domain name and certificate were set through value.yaml ingress.

### Database

None

**Comment by lunny** [comment]
413 means the object is too large? What's the LFS storage backend in your Gitea instance?

**Comment by alvin6233** [comment]
> 413 means the object is too large? What's the LFS storage backend in your Gitea instance?

The data disk is mounted with Alibaba Cloud NAS.

**Comment by alvin6233** [comment]
Found a solution: by now there is a parameter that allows to customize the client_max_body_size but it's actually called proxy-body-size.
With the annotation nginx.ingress.kubernetes.io/proxy-body-size it is possible to tune the body size for individual ingress resources.

reference link: https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#custom-max-body-size
