### ISSUE TITLE
The second dependency in issue is marked as private

### ISSUE THREAD

**Issue by mature-woman** [go-gitea/gitea#28732]
### Description

In the **dependencies** block of the **issues** section, the **second** dependency displays a lock icon with the caption "_You do not have permission to view this dependency_" (translated from russian)

This dependency is issue **within the same public repository**, and **i am an administrator** and should see ALL issues, even private ones

If you go to this issues directly, it is displayed **without any problems**

_I will provide additional information upon request_

### Screenshots

![изображение](https://github.com/go-gitea/gitea/assets/21334019/5a86ee74-b216-4531-911d-330c1c990e0f)

### Gitea Version

1.22.0+dev-514-gdd5693387 built with GNU Make 4.3, go1.21.4 : bindata

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

Ubuntu 22

### Browser Version

Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:120.0) Gecko/20100101 Firefox/120.0

**Comment by mature-woman** [comment]
3 projects

1 project depends on 2 projects
Project 3 depends on projects 1 and 2

in the "BLOCK" section of project 1 only project 3 is displayed

1 project (blockchain): 
![изображение](https://github.com/go-gitea/gitea/assets/21334019/725792e1-c43f-4951-a28b-4d1db1900afa)

2 project (chat): 
![изображение](https://github.com/go-gitea/gitea/assets/21334019/1a292c39-5553-45df-a671-8254921a32bb)

3 project (forum):
![изображение](https://github.com/go-gitea/gitea/assets/21334019/cdfdd780-07fd-4a84-9bb9-e8e1507f7e43)

**Comment by colejohnson66** [comment]
#27722

**Comment by mature-woman** [comment]
> Dupe of #27722

sorry
