### ISSUE TITLE
Editor removes BOM

### ISSUE THREAD

**Issue by dsteinbe11** [go-gitea/gitea#28743]
### Description

If a file is edited with the built-in editor, the BOM is removed after the commit.

The file is UTF-8-BOM, after the commit it´s UTF-8.

I have reproduced this issue with your demo site, see:
https://try.gitea.io/dsteinbe/editor-bom-issue

### Gitea Version

1.21.3

### Can you reproduce the bug on the Gitea demo site?

Yes

### Git Version

2.40.0, Wire Protocol Version 2 Enabled

### Operating System

windows

### How are you running Gitea?

service

### Database

SQLite

**Comment by crackedmind** [comment]
yeh, it's annoying

**Comment by silverwind** [comment]
Maybe it's because we don't set the `perserveBOM` option on Monaco's `getValue`:

https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.ITextModel.html#getValue
