### ISSUE TITLE
Incorrect timeago

### ISSUE THREAD

**Issue by crackedmind** [go-gitea/gitea#28747]
### Description

Why it shows 2 years instead of 1 ?

### Gitea Version

1.21.3

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/1381503/8aeba0ed-554a-4c8c-afa5-e41039ba2143)

### Git Version

2.34.1

### Operating System

Ubuntu

### How are you running Gitea?

[gitea-1.21.3-linux-amd64](https://github.com/go-gitea/gitea/releases/download/v1.21.3/gitea-1.21.3-linux-amd64)

### Database

SQLite

**Comment by yardenshoham** [comment]
We use https://github.com/github/relative-time-element to render this with the attribute `tense="past"`
