### ISSUE TITLE
gitea terraform state file

### ISSUE THREAD

**Issue by serialt** [go-gitea/gitea#28750]
### Feature Description

Terraform  state file can stored in gitlab with http, gitea has plans to support it ?

**Comment by puni9869** [comment]
You can commit the .state files in the repo.

**Comment by sgabenov** [comment]
Would be a very nice feature to have. I believe the better description of this feature can be found here:
https://developer.hashicorp.com/terraform/language/settings/backends/http
https://docs.gitlab.com/ee/user/infrastructure/iac/terraform_state.html
