### ISSUE TITLE
2FA push "Authentication failed"

### ISSUE THREAD

**Issue by mature-woman** [go-gitea/gitea#28755]
### Description

After **activating 2FA** i cannot **push** using the **HTTPS** protocol. 
After **disabling 2FA** everything is **working**.

### Gitea Version

1.22.0+dev-514-gdd5693387 built with GNU Make 4.3, go1.21.4 : bindata

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![изображение](https://github.com/go-gitea/gitea/assets/21334019/50c1558b-57c8-43fd-9178-e3ac6548eba4)

### Git Version

git version 2.34.1

### Operating System

Ubuntu 22 (Linux 6.2.0-39-generic x86_64)

### How are you running Gitea?

Compiled by myself

### Database

MySQL/MariaDB

**Comment by lafriks** [comment]
If you have 2FA enabled you can not use the user's password for git push, you have to create either app token in user settings or use that instead of password or use ssh protocol.

**Comment by mature-woman** [comment]
> If you have 2FA enabled you can not use the user's password for git push, you have to create either app token in user settings or use that instead of password or use ssh protocol.

_For some reason, the built-in SSH server in Gitea does not work in loopback mode on my server/router/cloudflare (does not connect at all), which is why I use HTTPS (i do not want to deal with this right now)._

**i will try app token, thanks!**
