### ISSUE TITLE
Logs error for DISABLE_QUERY_AUTH_TOKEN even though not specified

### ISSUE THREAD

**Issue by lonix1** [go-gitea/gitea#28758]
### Description

When my gite docker instance starts it logs this:
> 2024/01/10 06:58:15 .../setting/security.go:168:loadSecurityFrom() [W] Enabling Query API Auth tokens is not recommended. DISABLE_QUERY_AUTH_TOKEN will default to true in gitea 1.23 and will be removed in gitea 1.24.

But in my `app.ini` I did not set `DISABLE_QUERY_AUTH_TOKEN`.

### Gitea Version

1.21.3

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

docker

### Database

SQLite

**Comment by techknowlogick** [comment]
This log happens when the value is set to false, but default it is false. So if you don't have it defined, then it'll be false and show you the warning.

**Comment by lunny** [comment]
I think `IsSet` should be checked. If user haven't set it. It can be ignored.

**Comment by nodiscc** [comment]
This error message sneaks into the stdout for the `gitea actions generate-runner-token` command and breaks scripts which use the output of this command to register runners (https://github.com/nodiscc/xsrv/blob/master/roles/gitea_act_runner/tasks/act-runner.yml#L176).

I think the message should not be displayed at all if `DISABLE_QUERY_AUTH_TOKEN` is not set at all in the configuration file.

Can we reopen this?
