### ISSUE TITLE
Gitea  action not working whenever gitea instance running under subpath 

### ISSUE THREAD

**Issue by Shakthijuego** [go-gitea/gitea#28763]
### Description

My repo located at https://giteainstance.com/git/user/repo. Checkout action for gitea action failed with error 
`fatal: repository 'https:///giteainstance.com/user/repo/' not found`

### Gitea Version

1.21.0

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

Behind nginx under subpath

### Database

None

**Comment by lng2020** [comment]
reference https://github.com/actions/checkout/issues/1242
IMO it's not a bug of Gitea

**Comment by Shakthijuego** [comment]
That seems the case.  However just forking action/checkout doesn't seems to fix. Service prefix even being ignored in gitea action runner. Remote gitea action not being handled properly.

```
- name: Check out repository code with subpath
   uses: https://giteainstance.com/git/repo/checkout.git@v3

```

**Comment by lng2020** [comment]
I'm not saying forking this repo on your Gitea instance. I mean you may find someone may fork this repo and modify it to support the suburl feature.

**Comment by Shakthijuego** [comment]
Yes thank you. Checkout action got working with 'uses: ischanx/checkout@06c611454073903c9d44641d7e085b21115d3dcf'
I will raise a separate issue for https://gitea.com/gitea/act_runner to support 'uses' command with subpath.

**Comment by Shakthijuego** [comment]
For any ones reference: This code is responsible for ignoring subpath in  action. (Search for newRemoteAction) https://gitea.com/gitea/act/src/branch/main/pkg/runner/step_action_remote.go

**Comment by Shakthijuego** [comment]
Agree. I am planning to remove subpath in gitea instance or  make it work via redirecting in nginx. There seems no other solution.
