### ISSUE TITLE
All checks show as successful although skipped

### ISSUE THREAD

**Issue by hakito** [go-gitea/gitea#28761]
### Description

In a PR all checks show as successful although some of them had been skipped because of an unsuccessful job.

I think it should only show as successful if all jobs were successful.

### Gitea Version

1.21.2

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/320853/4e263ede-bbf8-4949-a4d1-4d844e9ef92b)

### How are you running Gitea?

Docker

### Database

None

**Comment by lunny** [comment]
Skipped is not error, so it's successful. This is because commit status has no state of skipped but Gitea Actions have.

**Comment by hakito** [comment]
Ok - but if they have been skipped because of an unsuccessful previous job - they should have the error status (like when they a job is aborted).

Guess I have a `preparation` job and a `test` job.

* The `preparation` job fails
* The `test` job is marked as skipped
* I manually re-run the `preparation` job and it runs successfully.

Now the PR is green although `test` was never executed.

**Comment by Zettat123** [comment]
Tested a workflow on GitHub. In GitHub, when we re-run a single job, the job's dependents are also re-run.

<img width="600px" src="https://github.com/go-gitea/gitea/assets/15528715/568b4e17-2d26-443e-82fb-9456af4d7afd" />
