### ISSUE TITLE
CI/CD or pipeline integration

### ISSUE THREAD

**Issue by geraldsamosir** [go-gitea/gitea#28779]
### Feature Description

hello gitea team 

I want to ask how about you make an integrating work like github or gitlab so if we use gitea in bare-metal server could be integrated to do auto deploy to to our production server

**Comment by 6543** [comment]
I dont exactly get your question.

I would say by do "git" things you can connect tools listening on webhooks. witch create actions like you describe.

so you eiter use gitea actions. or external tools like woodpecker-ci, drone...
