### ISSUE TITLE
footer.tmpl not load

### ISSUE THREAD

**Issue by wangzhiqiang** [go-gitea/gitea#28772]
### Description

https://docs.gitea.com/next/administration/customizing-gitea#example-plantuml

Using plantuml through this document, but footer.tmpl is not effective

6bd7ffca6666:/data/gitea/templates$ echo $GITEA_CUSTOM
/data/gitea
6bd7ffca6666:/data/gitea/templates$ tree 
.
└── custom
    └── footer.tmpl

1 directories, 1 files
6bd7ffca6666:/data/gitea/templates$ 

### Gitea Version

1.21.3

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

2.40.1

### Operating System

linux

### How are you running Gitea?

 run from docker
I deployed a service
https://gitea.wangzq.cn/

### Database

SQLite

**Comment by KN4CK3R** [comment]
`footer.tmpl` must be in `custom`.

**Comment by wangzhiqiang** [comment]
![image](https://github.com/go-gitea/gitea/assets/2043458/2a07871c-0301-4ccd-9f6e-28b8c7115cfd)
footer.tmpl in custom dir
