### ISSUE TITLE
Error 404 on branch creation

### ISSUE THREAD

**Issue by webjoel** [go-gitea/gitea#2881]
- Gitea version (or commit ref): e22be08
- Git version: 2.7.4
- Operating system: Linux Ubuntu x64
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (https://try.gitea.io/webjoel/teste)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

When creating a branch from the list of branches, error 404 occurs. This happens even though I logged in and was the owner of the repository.

## Screenshots

![captura de tela de 2017-11-10 11-01-26](https://user-images.githubusercontent.com/1946348/32659652-d6f1eff0-c606-11e7-8cb5-8d5bdcde41f1.png)

![captura de tela de 2017-11-10 11-01-34](https://user-images.githubusercontent.com/1946348/32659661-dd5f6692-c606-11e7-9459-8bebec5c7645.png)

**Comment by lafriks** [comment]
Looks like because of route change
