### ISSUE TITLE
Bad url to submodules, if add submodules with relative path and use apache proxy 

### ISSUE THREAD

**Issue by nikitos1881** [go-gitea/gitea#2882]
- Gitea version (or commit ref): 1.2.3
- Git version: 2.14.3
- Operating system: ubuntu 12.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [*] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [*] No
  - [ ] Not relevant
![bug_gitea](https://user-images.githubusercontent.com/33552084/32672979-3a6678f6-c65e-11e7-8dfa-ff372f0fcd71.png)

- Log gist:

## Description
configure gitea to use apache proxy
app.ini
[server]
ROOT_URL = https://domain:3001/git

In apache conf add
ProxyPass   /git http://127.0.0.1:3001
ProxyReversePass   /git http://127.0.0.1:3001

In gitea creeate two repositories: test1 and test2
Clone repositories test1 and test2
add file to repository test1 and test2 and commit&push

repositories test1 add submodule 
	path = test_submodules
	url = ../test2.git
commit& push repository test1

Open in browser gitea site and login. Open repository test1 , hover the mouse cursor to link submodules and click. Error 500, bad url.

**Comment by zig** [comment]
Hello, this bug is still present in `gitea-1.10.3-linux-amd64` (official built)

**Comment by zig** [comment]
Thanks for reopening the bug. 

As an additional note : the bug occurs when ROOT_URL is not the top directory of the server and is  not reproduced on https://try.gitea.io/

**Comment by MatthieuParis** [comment]
This bug is still present with version 1.11.4 of Gitea.
Reverse-proxying with Nginx and ROOT_URL set to "https://some.sample.host/gitea".

When clicking on a submodule link, the "gitea" part of the root URL is forgotten.

Thanks for Gitea: I've been enjoying it very much for half a year now.

**Comment by zeripath** [comment]
Fixed by #11098
