### ISSUE TITLE
Redirect after merge pull commit isn't working

### ISSUE THREAD

**Issue by somera** [go-gitea/gitea#28828]
### Description

When I mere a pull requests

![image](https://github.com/go-gitea/gitea/assets/8334250/ced999d4-5bbc-4667-a90b-d95cf6dbd2a0)

the redirect isn't working. In Chrome I see only this

![image](https://github.com/go-gitea/gitea/assets/8334250/c48a5fba-73d5-4b5c-b5b7-f6b06598340b)

in 1.21.3 it worked. I was redirected to the result page.

### Gitea Version

1.21.4

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

2.43.0

### Operating System

Ubuntu 22.04.3 LTS x86_64

### How are you running Gitea?

Downloaded gitea-1.21.4-linux-amd64

### Database

PostgreSQL

**Comment by somera** [comment]
Same problem with FF.

**Comment by delvh** [comment]
Do you have JS enabled?

**Comment by somera** [comment]
Yes. Cause and I didn't change nothing between the update from 1.21.3 to 1.21.4. My last pull merge with 1.21.3 was ~10 days ago without any issues. And after the update to 1.21.4 I see only the redirect json in Chrome and FF.

**Comment by somera** [comment]
The merge is working. But the redirects after isn't -> something changes here.

**Comment by delvh** [comment]
Sounds like #28140 iintroduced a regression then…

**Comment by delvh** [comment]
What happens if you clear your browser cache? Does the issue persist then?

**Comment by somera** [comment]
> What happens if you clear your browser cache? Does the issue persist then?

Isn't working. I use gitea only witch chrome. And for testing I cleared browser cache.

I used FF only to check the issue. Cause I don't use FF for gitea.

Can you reproduce this issue on your gitea instance?

**Comment by lunny** [comment]
> Sounds like #28140 iintroduced a regression then…

Maybe related with https://github.com/go-gitea/gitea/pull/28140/files#r1399519508

**Comment by somera** [comment]
@lunny will be this fixed in 1.21.5?

**Comment by lunny** [comment]
If we can fix it, I think it's very possible. But I cannot reproduce this on my local machine. I'm using FF.

**Comment by somera** [comment]
I have same problem with FF.

**Comment by somera** [comment]
Same problem with Edge.

**Comment by somera** [comment]
> If we can fix it, I think it's very possible. But I cannot reproduce this on my local machine. I'm using FF.

Any updates here? I can't be the only one with the problem.

I tested it on Windows and Linux.

**Comment by somera** [comment]
Same problem in 1.21.5

**Comment by somera** [comment]
I found the problem.

It's an Layer-8 problem!!!

After upgrade to 1.21.4 and 1.21.5 I forgot to compile the release cause I need the public folder for my Nginx proxy. After I did it now it work's.

Mea culpa.
