### ISSUE TITLE
User impersonation

### ISSUE THREAD

**Issue by mixman68** [go-gitea/gitea#2883]
- Gitea version (or commit ref): 1.2.3
- Git version: debian9 version
- Operating system: debian9
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

Impersonation feature is relevant for me. I manage a small gitea with few persons whose complain about bad permissions, ssh key issue. Impersonate user should be a good option for assistance user.

**Comment by lafriks** [comment]
Not a best option but as workaround you can copy password hash from `user` table, change password, login with that user, update user password hash back in database

**Comment by mixman68** [comment]
It is a request because we have leaved gitlab and one of our admin use this often in gitlab. I will communicate your suggestion

**Comment by lafriks** [comment]
Yes, I understand, I just giving you temporary workaround while this feature is not implemented

**Comment by bkcsoft** [comment]
@lafriks @djgreg13 I think you can login with an accesstoken no?

**Comment by techknowlogick** [comment]
api sudo functionality now possible to "impersonate" users.

**Comment by lunny** [comment]
resolved by #4809

**Comment by lunny** [comment]
@ewildgoose that maybe a new feature request?
