### ISSUE TITLE
Branch and tag dropdown menu not working

### ISSUE THREAD

**Issue by facorazza** [go-gitea/gitea#28833]
### Description

I believe since the upgrade from 1.20 to 1.21 I stopped seeing the branches and tags from the dropdown menu as shown in the screenshot.

The console logs throws the following when opening the dropdown:

```js
TypeError: me is null
    insert runtime-dom.esm-bundler.js:10
    kt runtime-core.esm-bundler.js:5246
    Et runtime-core.esm-bundler.js:5156
    Ne runtime-core.esm-bundler.js:5028
    Gs runtime-core.esm-bundler.js:6008
    hs runtime-core.esm-bundler.js:5843
    Ki runtime-core.esm-bundler.js:5539
    Ne runtime-core.esm-bundler.js:5015
    di runtime-core.esm-bundler.js:5428
    ii runtime-core.esm-bundler.js:5319
    Et runtime-core.esm-bundler.js:5167
    Ne runtime-core.esm-bundler.js:5028
    ti runtime-core.esm-bundler.js:5773
    run reactivity.esm-bundler.js:178
    node_modules index.js:10
    te runtime-core.esm-bundler.js:158
    X runtime-core.esm-bundler.js:357
runtime-core.esm-bundler.js:226:12
```

Both the branch and tags lists aren't shown.

### Gitea Version

1.21.4

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![Screenshot from 2024-01-17 17-08-53](https://github.com/go-gitea/gitea/assets/20555025/8f70b67d-0ecf-47cc-b20a-c80d60c2700c)

### How are you running Gitea?

Docker deployment

### Database

PostgreSQL

**Comment by wxiaoguang** [comment]
It seems quite strange ... Gitea is using Vue for that component, it has been tested against various browsers by many users for long time.

Could you elaborate how to reproduce your problem?

1. Could you reproduce it on https://try.gitea.io?
1. Are you using custom templates (remove them and retry)? Could you reproduce it on your side by starting a clear/fresh docker instance?
1. What browser are you using?

**Comment by yp05327** [comment]
Supplement:
Maybe you also need to check your browser extensions. Sometimes they may cause strange issues.

**Comment by facorazza** [comment]
The issue was due to [Madeleine.js](https://github.com/beige90/Madeleine.js/tree/master) that I use to visualize STLs.
By removing the changes to the footer I now get the dropdown menu working as expected.
Madeleine.js hasn't seen any updates in quite a while so I'll have to find another way to view STLs in Gitea. If you have any suggestion please let me now. 
Thank you for the help
