### ISSUE TITLE
unable to PushUpdateAddTag to Repo: unable to get tag Commit: object does not exist

### ISSUE THREAD

**Issue by yp05327** [go-gitea/gitea#28843]
### Description

![image](https://github.com/go-gitea/gitea/assets/18380374/20e8ce45-1dd1-4c1e-9d31-3116cabb63f1)

Using gogit and migrate https://github.com/torvalds/linux with releases

https://github.com/torvalds/linux/tree/v2.6.11
![image](https://github.com/go-gitea/gitea/assets/18380374/2e3e0079-2423-428c-8a95-e2c84302e24f)

not sure whether this is a bug

### Gitea Version

latest

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

build

### Database

None

**Comment by lunny** [comment]
Looks like the tag point to a tree. I remember I have read the code about the related problem.

**Comment by lunny** [comment]
I believe this is a git's edgecase which only happen on linux itself. Maybe we need some trick to ignore it to avoid failure on gitea.

```
objecttype tagrefname:short v2.6.11-treeobject c39ae07f393806ccf406ef966e9a15afc43cc36aobjectname 5dc01c595e6c6ec9ccda4f6f69c131c0dd945f8ccreator contents This is the 2.6.11 tree object.

NOTE! There's no commit for this, since it happened before I started with git.
Eventually we'll import some sort of history, and that should tie this tree
object up to a real commit. In the meantime, this acts as an anchor point for
doing diffs etc under git.
```
