### ISSUE TITLE
incorrect name with push

### ISSUE THREAD

**Issue by kajvans** [go-gitea/gitea#28858]
### Description

hi everyone,
it is possible for me to clone private git repositories what in my eyes is a little weird. 
is there a place where you can set that you need to login. in the same category when i push to a repo it uses my github username so that also gives a lot of problems because than i cant easily find because the name is not set in the databasew.

### Gitea Version

1.21.3

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

1.21.3

### Operating System

raspberry os lite

### How are you running Gitea?

i am running it on a raspberry 4 8gb using docker

### Database

MySQL/MariaDB

**Comment by jolheiser** [comment]
Can you reproduce this on try.gitea.io? I see you've answered "no" on the form, so I'm just making sure.

I'm assuming you have credentials cached somewhere, though if you're able to reproduce this on another instance we would greatly appreciate a security report to `security@gitea.io`

Regarding your username, that is something you set with git, for example covered here https://git-scm.com/book/en/v2/Getting-Started-First-Time-Git-Setup under "Your Identity".
```sh
$ git config --global user.name "John Doe"
$ git config --global user.email johndoe@example.com
```
The above sets it globally, which may not be what you want. It can be set per-repo and even has finer controls if you need.

Gitea will link commits to your account by matching the email used.

**Comment by kajvan** [comment]
i cant create account on try.gitea.io i just get error 500 so i want to try but cant

**Comment by jolheiser** [comment]
Ah I see as well, I'll have someone poke it and let you know!

**Comment by kajvans** [comment]
the cloning of private repository is think it indeed because of saved credentials but no idea where, did not set anything in git config. Still when pushing to repository in vscode i does not go to my account but just some account with my username. the push also is not visible in the home screen. this is not because of github because i did log out.

**Comment by kajvans** [comment]
did set my username and did github OAuth2 with my account and now in the repo it shows my account but still nothing in the homepage that i did push
