### ISSUE TITLE
Render failed, failed to render template: broken pipe / connection reset by peer

### ISSUE THREAD

**Issue by nowanti** [go-gitea/gitea#28869]
### Description

After upgrading from 1.19.4 to 1.21.4 (deployed in docker mode, only the image version number has been modified), execute docker-compose logs-f and see the error log that is constantly refreshed:
```log
gitea  | 2024/01/20 23:27:50 .../context_response.go:86:HTML() [E] Render failed: failed to render template: home, error: write tcp 127.0.0.1:3000->127.0.0.1:40978: write: connection reset by peer
gitea  | 2024/01/20 23:27:50 .../context_response.go:88:HTML() [E] plainTextInternal (status=500): write bytes failed: write tcp 127.0.0.1:3000->127.0.0.1:40978: write: connection reset by peer
gitea  | 2024/01/20 23:27:50 ...eb/routing/logger.go:102:func1() [I] router: completed GET / for 127.0.0.1:40978, 200 OK in 2.9ms @ web/home.go:32(web.Home)
...
gitea  | 2024/01/20 23:27:56 .../context_response.go:86:HTML() [E] Render failed: failed to render template: home, error: write tcp 127.0.0.1:3000->127.0.0.1:41002: write: connection reset by peer
gitea  | 2024/01/20 23:27:56 .../context_response.go:88:HTML() [E] plainTextInternal (status=500): write bytes failed: write tcp 127.0.0.1:3000->127.0.0.1:41002: write: connection reset by peer
gitea  | 2024/01/20 23:27:56 ...eb/routing/logger.go:102:func1() [I] router: completed GET / for 127.0.0.1:41002, 200 OK in 3.0ms @ web/home.go:32(web.Home)
```

### Gitea Version

1.21.4

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/12849039/00cffafd-1b5f-47de-a1a0-6216733268a9)

### Git Version

2.43.0

### Operating System

Linux NaNas 4.4.302+ #69057 SMP Sat Sep 23 21:44:10 CST 2023 x86_64 GNU/Linux synology_apollolake_918+

### How are you running Gitea?

deployed via docker

### Database

SQLite

**Comment by nowanti** [comment]
> Check your ROOT_RUL setting on your app.ini. It should not be 127.0.0.1 if it's running on a docker container.

I checked it, and it looks like this: `https://git.xxx.com/` can be accessed normally in both the old version and the current version, but the current version keeps reporting errors in the log, which seems to be slow in response.

**Comment by nowanti** [comment]
> After upgrading from 1.19.4 to 1.21.4

Correction: the old version number is 1.19.3

**Comment by wxiaoguang** [comment]
It seems that it's related to your network or reverse proxy.

Usually "connection reset by peer" means that the connection is closed unexpectedly (not by GItea, but by downstream or client)

If it doesn't affect your daily usage, it could just ignore it.


If it affects your daily usage, you need to debug it step by step:

1. Test the connection by `curl` on the docker's host to see whether it triggers the error
    * If yes, try to start a clear/fresh instance on a clear host and try to reproduce, if it could still reproduce, please report the detailed steps.
    * If no, check you reverse proxy and network.

**Comment by wxiaoguang** [comment]
Feel free to reopen if there are more clues and/or there is a reproducible setup with detailed steps.
