### ISSUE TITLE
TypeError: WeakMap key undefined (caused by extension DarkReader's bug)

### ISSUE THREAD

**Issue by keval6b** [go-gitea/gitea#28861]
### Description

```
JavaScript error: TypeError: WeakMap key undefined must be an object or an unregistered symbol (https://try.gitea.io/ @ 529:36). Open browser console to see more details.
```

```
worker port event error 
Object { type: "error", data: undefined }
index.js:30:76443
    Tg https://try.gitea.io/assets/js/index.js?v=1.21.4:30

```

This does not occur in a private window, I have tried to clear cookies and site data, no change.

### Screenshots

![Screenshot_20240119_200337](https://github.com/go-gitea/gitea/assets/33595996/0c1edc35-f764-40cb-9dda-02f6b6475105)

### Gitea Version

1.22.0+dev-575-gd68a613ba

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

Firefox

### Browser Version

121.0

**Comment by techknowlogick** [comment]
You wouldn't happen to be using the "dark reader" extension?

**Comment by techknowlogick** [comment]
possibly related: https://github.com/go-gitea/gitea/issues/28226

**Comment by puc9** [comment]
> You wouldn't happen to be using the "dark reader" extension?

Disabling the dark reader extension for gitea fixed it for me

**Comment by thechubbypanda** [comment]
Goddammit darkreader

**Comment by wxiaoguang** [comment]
On Gitea side, we could do this: Avoid duplicate JS error messages on UI #28873

**Comment by staticfrost** [comment]
had this happening to me too. thanks for fixing it!
