### ISSUE TITLE
Unable to cancel action jobs after Upgrading to Gitea 1.21.4

### ISSUE THREAD

**Issue by ysicing** [go-gitea/gitea#28862]
### Description

After upgrading to Gitea 1.21.4, I have noticed that I am unable to cancel Action Jobs. When I click the cancel button, the Job continues running without being terminated.I have noticed that new tasks are not triggering as expected. When I push changes or manually trigger a workflow, the corresponding tasks are not being initiated.

### Gitea Version

1.21.4

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/8605565/ae83fa32-25d2-4cef-92ad-65d363da572a)
![image](https://github.com/go-gitea/gitea/assets/8605565/af17d06f-9a92-49f4-b207-226e9c81ec9d)

### How are you running Gitea?

k8s

### Database

SQLite

**Comment by techknowlogick** [comment]
What does the agent look like? Are the containers still running?

**Comment by ysicing** [comment]
@techknowlogick  sqlite database is experiencing an issue.
