### ISSUE TITLE
Container packages ignore `REQUIRE_SIGNIN_VIEW`

### ISSUE THREAD

**Issue by Shuenhoy** [go-gitea/gitea#28875]
### Description

Our site has enabled `REQUIRE_SIGNIN_VIEW`, however, we can still `docker pull` a public image.
This problem had been reported in #20863 and #20873 seemed to have fixed this for other types of package, but not for container.

### Gitea Version

1.21.2

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

docker

### Database

PostgreSQL

**Comment by KN4CK3R** [comment]
It does not ignore that flag:
https://github.com/go-gitea/gitea/blob/1df06e3f399307c14b60a2b88e1b26cedc1ae2f9/modules/context/package.go#L95-L98

Did you perform a docker logout?

**Comment by Shuenhoy** [comment]
Hi @KN4CK3R, please check this snapshot:

![image](https://github.com/go-gitea/gitea/assets/2196156/03b70212-8d36-418d-ba0a-2d77998ef7a4)

Or am I missing something and the login information can be stored somewhere else?

**Comment by KN4CK3R** [comment]
No, my bad... The container registry uses the internal ghost user for anonymous requests and the ghost user is not `nil`. Therefore the test does not return no access rights... I will send a fix soon.

**Comment by KN4CK3R** [comment]
Fixed in #28877. Thank you for the report.
