### ISSUE TITLE
metrics: add metric for unread system notices

### ISSUE THREAD

**Issue by r10r** [go-gitea/gitea#28906]
### Feature Description

I think it would be great if gitea had a metrics for the number of unread system notices 
(web UI path **/admin/notices**, model https://github.com/go-gitea/gitea/blob/main/models/system/notice.go)

```prometheus
# HELP gitea_system_notices Number of system notices
# TYPE gitea_system_notices gauge
gitea_system_notices 524
```
It would be even greater if it possible to distinguish between success and error notices.  (See **NOTICE_ON_SUCCESS** settings in https://docs.gitea.com/administration/config-cheat-sheet) e.g.: 

```prometheus
# HELP gitea_system_notices Number of system notices
# TYPE gitea_system_notices gauge
gitea_system_notices{type="success"} 123
gitea_system_notices{type="error"}  0
```

I really like to contribute and can create a PR if you consider this useful.

**Comment by r10r** [comment]
Just a note to myself. Merged PR's that add new metrics:

* [include build info in Prometheus metrics #22819](https://github.com/go-gitea/gitea/pull/22819)

**Comment by KN4CK3R** [comment]
Just a note: the system notices didn't get much love and may be removed in the future.

**Comment by r10r** [comment]
> Just a note: the system notices didn't get much love and may be removed in the future.

Thanks for the information. I thought that adding these metrics would be a rather easy task and a real 
benefit for monitoring. Is there any chance to keep the system notices in long term ? 
Is there an issue for the removal of system notices ?

Maybe you give me some advice how to monitor gitea system health (task/job errors) with prometheus / grafana ?
The only thing that comes to my mind is processing the logfiles (loki, grok_exporter ...)

**Comment by lunny** [comment]
Merge into #14724
