### ISSUE TITLE
gitea not starting as a homebrew service on macOS

### ISSUE THREAD

**Issue by Fryguy** [go-gitea/gitea#28918]
### Description

I installed gitea just now via homebrew on macOS.  However, the homebrew service kept failing with an obscure error code `#19968`.

Playing around, I noticed that the plist file described the working directory as `/opt/homebrew/opt/gitea/libexec`, however that directory didn't exist (`/opt/homebrew/opt/gitea` existed, just not the `libexec` subdir).  So, I created the directory manually and now everything is working.

I noticed in that gitea directory there's also a systemd unit file named `homebrew.gitea.service` that also has the working directory set to `/opt/homebrew/opt/gitea/libexec`, so it's possible this also applies to linux environments as well.

### Gitea Version

Gitea version 1.21.4 built with GNU Make 3.81, go1.21.6 : bindata, sqlite, sqlite_unlock_notify

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

macOS 13.6.3

### How are you running Gitea?

homebrew installation / brew services on macOS (M1)

### Database

None

**Comment by lunny** [comment]
Hi, Gitea for Brew now maintained in the brew official repository. Please submit an issue there.

ref https://github.com/Homebrew/homebrew-core/blob/master/Formula/g/gitea.rb
