### ISSUE TITLE
Update docs to reflect that runner tokens are now reusable

### ISSUE THREAD

**Issue by scottyeager** [go-gitea/gitea#28911]
### Feature Description

With https://github.com/go-gitea/gitea/pull/27304, action runner registration tokens are now reusable. However the docs still specify that they are single use:

https://github.com/go-gitea/gitea/blob/1ca947baece4863a1af2c9114a1f67c81a351d0c/docs/content/usage/actions/quickstart.en-us.md?plain=1#L63-L64

**Comment by lunny** [comment]
Would you like to send a PR to fix that?

**Comment by scottyeager** [comment]
Sure, happy to!

PS, I didn't see an issue form type for documentation.
