### ISSUE TITLE
Pull Request Timeout (Error 500)

### ISSUE THREAD

**Issue by ReptoxX** [go-gitea/gitea#28930]
### Description

Whenever i try to open up a pull request on my rather large repository, it doesn't work and eventually returns error 500.
```
NewPullRequest: unable to run ls-files -u -z! Error: git ls-files -u -z: context deadline exceeded
```

I tried running this command on my own and it never finishes (even after 3+ hours).

### Gitea Version

1.21.4

### Can you reproduce the bug on the Gitea demo site?

Not tried

### Log Gist

https://gist.github.com/ReptoxX/ba4d12fbd111393904fb351e7e949d0f

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/13363890/21168dfc-1d7a-4ef2-bf48-0e873cb5ae76)
![image](https://github.com/go-gitea/gitea/assets/13363890/f615ac8e-ff31-4d17-9054-9a39458134e1)

### Git Version

2.40.1, Wire Protocol Version 2 Enabled

### Operating System

Ubuntu 18.04.6

### How are you running Gitea?

We run gitea through docker with traefik as a reverse proxy solution inside a docker compose file. Together with postgres as the database

### Database

PostgreSQL

**Comment by lschwahn** [comment]
Duplicates #27967

**Comment by yp05327** [comment]
As it is duplicated, I will close this one. Feel free to reopen it if you have any problems.
