### ISSUE TITLE
Apply LANDING_PAGE config variable options for logged in users

### ISSUE THREAD

**Issue by schaffman5** [go-gitea/gitea#2893]
- Gitea version (or commit ref): 1.2.3
- Git version: N/A
- Operating system: All
- Database (use `[x]`): Any
  - [X] PostgreSQL
  - [X] MySQL
  - [X] MSSQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:

## Description
Currently the LANDING_PAGE server config option works only for users that are not logged in.  It may be useful for Gitea administrators to specify a landing page for all users.  This could also extend the current landing page options from 'home' or 'explore' to also include 'organizations'.

**Comment by lunny** [comment]
resolved by #2894
