### ISSUE TITLE
Displayed order of topics is inconsistent between repo list and repo page

### ISSUE THREAD

**Issue by wackbyte** [go-gitea/gitea#28936]
#### Problem

The order of a repository's topics is different when viewed in a repo list versus when viewed on the repo's page itself. See the screenshots below for an example.

#### Expected behavior

I would expect the ordering to be consistent between the two pages, either by being sorted or by staying in insertion order. Personally, I would prefer them to be sorted (as they already are on the repo page).

#### Demo

- Repo list <https://try.gitea.io/glaggleland>
- Repo page: <https://try.gitea.io/glaggleland/topics>

### Screenshots

Order while adding:
![Entering the topics A, C, and B in that order](https://github.com/go-gitea/gitea/assets/29505620/ecd76c29-6b38-45de-a0cd-ec13073f3b6a)

Order after adding (on repo page):
![List of topics A, B, and C in that order](https://github.com/go-gitea/gitea/assets/29505620/401052f6-9ff4-4891-b3cc-d4b433002083)

Order in the repo list on the user profile:
![List of topics A, C, and B in that order](https://github.com/go-gitea/gitea/assets/29505620/4cb33862-a260-47e9-92b1-8539f617bd8d)

(These screenshots are from the reproduction of the issue on a local test instance I built, not from try.gitea.io, but the same issue occurs there.)

### Gitea Version

ba24e0ba61b1b66f58c8448f27272d1d6d14f60c

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

NixOS

### Browser Version

Librewolf 121.0.1

**Comment by wackbyte** [comment]
I think [this](https://github.com/go-gitea/gitea/blob/ba24e0ba61b1b66f58c8448f27272d1d6d14f60c/models/repo/topic.go#L200) is the offending code; it toggles between sorting topics by name or by repo count.

**Comment by wackbyte** [comment]
I believe I've found the root of the issue.

The repo page ([view](https://github.com/go-gitea/gitea/blob/ba24e0ba61b1b66f58c8448f27272d1d6d14f60c/routers/web/repo/view.go#L938), [template](https://github.com/go-gitea/gitea/blob/ba24e0ba61b1b66f58c8448f27272d1d6d14f60c/templates/repo/home.tmpl#L33)) uses [`FindTopics`](https://github.com/go-gitea/gitea/blob/ba24e0ba61b1b66f58c8448f27272d1d6d14f60c/models/repo/topic.go#L200) to get the list of topics, which sorts them by name.

However, the repo list ([view](https://github.com/go-gitea/gitea/blob/ba24e0ba61b1b66f58c8448f27272d1d6d14f60c/routers/web/explore/repo.go#L147), [template](https://github.com/go-gitea/gitea/blob/ba24e0ba61b1b66f58c8448f27272d1d6d14f60c/templates/explore/repo_list.tmpl#L51)) uses the [`Topics` field of the `Repository` struct](https://github.com/go-gitea/gitea/blob/ba24e0ba61b1b66f58c8448f27272d1d6d14f60c/models/repo/repo.go#L182), which I assume is not sorted.

**Comment by stuzer05** [comment]
Can we fix milestones list sorting as well? It's not alphabetical

**Comment by wackbyte** [comment]
I can look into it
