### ISSUE TITLE
The code comment dispeared after resolving/unresolving a comment

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#28949]
### Description

The code comment dispeared after resolving/unresolving a comment

### Gitea Version

main

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

<img width="1019" alt="图片" src="https://github.com/go-gitea/gitea/assets/81045/f5225ac0-f201-4194-9631-b6446b70b287">

### How are you running Gitea?

gitea.com

### Database

None

**Comment by yp05327** [comment]
Can you provide the URL?

**Comment by lunny** [comment]
https://gitea.com/gitea/blog/pulls/340

**Comment by yp05327** [comment]
I can see it on my phone.
![IMG_3301](https://github.com/go-gitea/gitea/assets/18380374/7715e381-f46e-4976-aae8-805637bfa1f7)

**Comment by wxiaoguang** [comment]
Maybe the reason is: "ShowOutdatedComments" defaults to "false", so you won't see the "outdated" comments.

- This PR might also provide some information:  Do not render empty comments #29039 

Maybe it actually should default to true.

![image](https://github.com/go-gitea/gitea/assets/2114189/44c682f5-11d1-4ac4-a9e2-123aca580f8b)

**Comment by lunny** [comment]
But the experience is very odd when I click the `resolve the conversation` and then the comment disapeared.

**Comment by wxiaoguang** [comment]
> But the experience is very odd when I click the `resolve the conversation` and then the comment disapeared.

Even if it doesn't disappear by clicking "resolve the conversation", it would also disappear when you refresh the page.

Indeed it is a design problem. Maybe it should tell the user that "The outdated comment won't show" on the UI.

**Comment by wxiaoguang** [comment]
->  Improve user experience for outdated comments #29050
