### ISSUE TITLE
Pull requests for repository with git-lfs fail with 'batch request: missing protocol: ""'

### ISSUE THREAD

**Issue by wgaulke** [go-gitea/gitea#28947]
### Description

Dear Gitea team,

I have carefully read through related issues regarding git-lfs. I cannot figure out how to make it work on my gitea instance. I tried  `git config lfs..locksverify false` in the repository dir, but no change.

Thank you in advance for your valuable time!

## Error

Creating a pull request in a git-lfs repository fails with:

```
NewPullRequest, Push: team/repo-for-project:branch team/repo-for-project:refs/pull/144/head push failed: exit status 1 - Remote "/home/git/gitea-repositories/team/repo-for-project.git" does not support the Git LFS locking API. Consider disabling it with:
  $ git config lfs..locksverify false
batch request: missing protocol: ""
```

## Git-LFS

```
git-lfs/3.4.1 (GitHub; linux amd64; go 1.21.1)
git version 2.43.0

LocalWorkingDir=
LocalGitDir=
LocalGitStorageDir=
LocalMediaDir=lfs/objects
LocalReferenceDirs=
TempDir=lfs/tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file,ssh
UploadTransfers=basic,lfs-standalone-file,ssh
GIT_EXEC_PATH=/usr/lib/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

## Git

```
git version 2.43.0

LocalWorkingDir=
LocalGitDir=
LocalGitStorageDir=
LocalMediaDir=lfs/objects
LocalReferenceDirs=
TempDir=lfs/tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file,ssh
UploadTransfers=basic,lfs-standalone-file,ssh
GIT_EXEC_PATH=/usr/lib/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

## Setup

* gitea as systemd service
* nginx frontend proxy

### Gitea Version

1.21.4

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

git version 2.43.0

### Operating System

ubuntu 22.04 LTS

### How are you running Gitea?

Gitea is run as systemd service. 

### Database

MySQL/MariaDB

**Comment by techknowlogick** [comment]
This will be fixed in 1.21.5 relesed. PR details can be found here: https://github.com/go-gitea/gitea/pull/28851

**Comment by wgaulke** [comment]
@techknowlogick thank you for you answer 👍

**Comment by wgaulke** [comment]
@Voscha in #23765 - an old issue - you mentioned, that you solved the error by removing old git lfs hooks from the respository.

Would you be so kind to share the details of your solution / guide to do it? I am currently somehow stuck in solving it for my repo. Maybe we can help others as well. 

Thank you :)

**Comment by Voscha** [comment]
Hi, The solution is mentioned in the comments. If your repository have an hooks subdir, delete the files in that dir. I hope, this helps you. -------- Ursprüngliche Nachricht --------Von: Werner ***@***.***>Datum: Mo., 5. Feb. 2024, 15:24An: go-gitea/gitea ***@***.***>Cc: Voscha ***@***.***>, Mention ***@***.***>Betreff: Re: [go-gitea/gitea] Pull requests for repository with git-lfs fail with 'batch request: missing protocol: ""' (Issue #28947)
@Voscha in #23765 - an old issue - you mentioned, that you solved the error by removing old git lfs hooks from the respository.
Would you be so kind to share the details of your solution / guide to do it? I am currently somehow stuck in solving it for my repo. Maybe we can help others as well.
Thank you :)

**Comment by wgaulke** [comment]
@Voscha Thanks for your answer. I was somehow bling / did not think that is was so simple. Was able to fix that.
