### ISSUE TITLE
Push mirror from gitea to github no longer works

### ISSUE THREAD

**Issue by mvdkleijn** [go-gitea/gitea#28944]
### Description

This: https://docs.gitea.com/usage/repo-mirror#setting-up-a-push-mirror-from-gitea-to-github

No longer works since Github no longer supports password authentication.
My suggestion is:

- either update the feature and docs to allow it to work again **or**
- remove it from the codebase and docs

In any case, a note should be added to the docs that this no longer works.

Note: I'm not providing anything on demo site because not needed

### Gitea Version

1.21.4

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

2.40.1, Wire Protocol Version 2 Enabled

### Operating System

2.40.1, Wire Protocol Version 2 Enabled

### How are you running Gitea?

Docker but not relevant for issue.

### Database

None

**Comment by jolheiser** [comment]
Did you try with a PAT like the docs say?
It's still working on my instance, so if it still doesn't work for you we may need to look further.

**Comment by mvdkleijn** [comment]
@jolheiser Yes. Unless I'm not reading something correctly?

What I do, exactly step by step:

On Github:
- Go to https://github.com/settings/tokens/new
- Create new personal access token (classic)
- Set name, expiration (none in this case)
- Select public_repo
- Click generate token
- Copy generated token

On Gitea:
- Go to repo settings -> mirror settings
- Git remote url: https://github.com/mvdkleijn/<my private repo>.git
- Drop down authorization
- Enter username: mvdkleijn
- Enter PAT as password
- Select "sync when commits are pushed"
- Enter 0 for mirror interval
- Click add push mirror
- Go to main repo page
- Go back to settings
- Click "sync now" button and wait
- Refresh screen if needed
- Witness a gloriously small "error" with following contents on hover:

```
push failed: remote: Support for password authentication was removed on August 13, 2021.
remote: Please see https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication.
fatal: Authentication failed for 'https://github.com/mvdkleijn/*************.git/'
 - remote: Support for password authentication was removed on August 13, 2021.
remote: Please see https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication.
fatal: Authentication failed for 'https://github.com/mvdkleijn/*************.git/'
 - remote: Support for password authentication was removed on August 13, 2021.
remote: Please see https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication.
fatal: Authentication failed for 'https://github.com/mvdkleijn/*************.git/'
```

Please note that the private repo on Github is newly created and empty.

My conclusion: it don't work.

**Comment by jolheiser** [comment]
I am unable to reproduce, it is still working when I make a new test on my instance. (I cannot test on try because mirroring is turned off on the demo)

You made a token with `public_repo` and later mention the repo on GH is private, which would be a problem.

The only way I can achieve the error "remote: Support for password authentication was removed on August 13, 2021." is if I put a non-token in that field.

I can try to test with a few other combinations.

**Comment by mvdkleijn** [comment]
> I am unable to reproduce, it is still working when I make a new test on my instance. (I cannot test on try because mirroring is turned off on the demo)
> 
> You made a token with `public_repo` and later mention the repo on GH is private, which would be a problem.
> 
> The only way I can achieve the error "remote: Support for password authentication was removed on August 13, 2021." is if I put a non-token in that field.
> 
> I can try to test with a few other combinations. 

Thanks for helping out in any case 

I **am** trying to mirror to a private repo as a backup. I don't know what permission would be necessary for that.

The token I'm using is a "classic" token and not the newer style. That's what I copied to the password field.

When testing, are you using a private repo on github and classic token, pushing **to** github?

**Comment by mvdkleijn** [comment]
**Note**: While I am trying to push to a private repo, I selected the public_repo permission on purpose due to that being in the Gitea docs.

I'll try again later today with a token that has full permissions, both classic and new styles.

**Comment by mvdkleijn** [comment]
OK, nevermind. I don't know what was going on. Retested it and it works. Closing.
