### ISSUE TITLE
Can't load the install page

### ISSUE THREAD

**Issue by kmahyyg** [go-gitea/gitea#2895]
- Gitea version (or commit ref): 1.2.3
- Git version:2.7.4
- Operating system: Ubuntu 16.04LTS
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:
All looks fine.  No error.
## Description

Why semantic.min.css loading cost at least 1min ?
I cannot load the install page.

...

**Comment by lunny** [comment]
Please give more detail so that we can find the issue.

**Comment by kmahyyg** [comment]
such as?

**Comment by lafriks** [comment]
@kmahyyg erros in system or gitea logs
