### ISSUE TITLE
Activity Feed privacy is not updated with repo privacy

### ISSUE THREAD

**Issue by coolaj86** [go-gitea/gitea#2896]
- Gitea version (or commit ref): 1.0.1
- Git version: 2.7.4
- Operating system: Ubuntu 16.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

When I change my project to private I expect that my activity related to that project should also become private.

However, Activity Feed items remain public after changing the project to private.

Workaround:

```sql
UPDATE action SET is_private = 1 WHERE repo_name = 'private-project';
```

## Screenshots

Change repo to private:

![screen shot 2017-11-12 at 12 17 57 am](https://user-images.githubusercontent.com/122831/32696812-12aa1b38-c73f-11e7-9b53-2668d1b8e1fc.png)

Activity still shows public:

![screen shot 2017-11-12 at 12 18 17 am](https://user-images.githubusercontent.com/122831/32696813-16f61796-c73f-11e7-940b-f72892ee8868.png)

**Comment by lafriks** [comment]
Yes but it's showing only for those who has access for this repository. Nobody who don't have access to this repository should not be able to see that repository activities on dashboard. At least I'm not able to reproduce that so that I can see activities when logged in with user who has no access to that repository

**Comment by coolaj86** [comment]
I can confirm the behavior is as you describe on try.gitea.org, which is the expected behavior.

Thank you.
