### ISSUE TITLE
Many golang links are outdated and don't use https.

### ISSUE THREAD

**Issue by macifell** [go-gitea/gitea#28979]
### Description

Some links to the golang site use http instead of https, and many of them also point to golang.org instead of go.dev.

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/26522946/a668d703-f0b3-4474-bdc5-46a85f450163)

### Gitea Version

1.21

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

Linux

### Browser Version

Firefox 122.0

**Comment by delvh** [comment]
Closed by #28980
