### ISSUE TITLE
[SP] Translate error

### ISSUE THREAD

**Issue by busslina** [go-gitea/gitea#28989]
### Description

Bad: Cheques
Good: Chequeos

Corrected: Activar chequeos del estado de salud...
Better alternative: Activar comprobaciones del estado de salud...

### Gitea Version

1.21.4

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![imagen](https://github.com/go-gitea/gitea/assets/73592852/6948fe22-221a-4f76-8df5-7fb833286202)

### How are you running Gitea?

Self Hosted

### Database

PostgreSQL

**Comment by yp05327** [comment]
Gitea is using `crowdin` for the localization. 
https://github.com/go-gitea/gitea?tab=readme-ov-file#translating

So we will not maintain other languages except English here.
You can access and contribute https://crowdin.com/project/gitea in crowdin.

**Comment by busslina** [comment]
> Gitea is using `crowdin` for the localization. https://github.com/go-gitea/gitea?tab=readme-ov-file#translating
> 
> So we will not maintain other languages except English here. You can access and contribute https://crowdin.com/project/gitea in crowdin.

Cool, done

https://crowdin.com/editor/gitea/68/enus-es?view=comfortable&filter=basic&value=0#q=cheque
