### ISSUE TITLE
Windows - Code indexer fails due to long command line

### ISSUE THREAD

**Issue by Sebazzz** [go-gitea/gitea#28985]
### Description

Observed in the log:

```
2024/01/30 08:13:20 ...exer/code/indexer.go:128:func2() [E] Codes indexer handler: index error for repo 329: fork/exec C:/Program Files/Git/bin/git.exe: The filename or extension is too long.
2024/01/30 08:13:20 ...queue/workergroup.go:102:doWorkerHandle() [E] Queue "code_indexer" failed to handle batch of 2 items, backoff for a few seconds
```

Turning on debug logging, Gitea attempts to execute the command as follows:

```
2024/01/30 08:13:20 ...dules/git/command.go:290:Run() [D] git.Command.RunDir(D:\Gitea\data\repositories\minszw\smart-ns.git): "C:/Program Files/Git/bin/git.exe" -c protocol.version=2 -c credential.helper= -c filter.lfs.required= -c filter.lfs.smudge= -c filter.lfs.clean= ls-tree --full-tree -l 1fe04fdf997673b19f538b378fd53210d3ed5d09 -- .gitignore .osv-config.toml ".run/Command-line_ create organization.run.xml" ".run/Standalone (no browser).run.xml" [every file in the repository here]
```

In our case, this amounts to about 502000 character command line. This exceeds [the limit of 32767 characters in Windows](https://devblogs.microsoft.com/oldnewthing/20031210-00/?p=41553), and thus the command fails.

### Gitea Version

1.21.4

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

git version 2.39.2.windows.1

### Operating System

Windows Server 2022

### How are you running Gitea?

go-gitea version (but happens with git version too) `1.21.4 built with GNU Make 4.3, go1.21.5 : bindata, sqlite, sqlite_unlock_notify` connected to MSSQL

### Database

MSSQL

**Comment by wxiaoguang** [comment]
Similar:

->  search indexer broken: ...exer/code/indexer.go:128:func2() [E] Codes indexer handler: index error for repo 29: fork/exec /usr/bin/git: argument list too long #28584
