### ISSUE TITLE
Comment types checked out "Assignee" but still showing that activity/comment in issue page

### ISSUE THREAD

**Issue by hardiklakhalani** [go-gitea/gitea#28991]
### Description

I checked off Comment type "Assignee" but still showing that activity/comment in issue page. Snapshots attached. It's happening in our existing version 1.20.5  &  In Gitea test Instance 1.22.0+dev-625-g3e8414179

https://try.gitea.io/yashmehta2nd/dasdasdad/issues/1

### Gitea Version

1.22.0+dev-625-g3e8414179

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/82162165/d6b7234a-be9d-47d2-8ca5-1570532b41c8)
![image](https://github.com/go-gitea/gitea/assets/82162165/fb90cda3-b3ec-4124-bc44-c875e56ec6c8)

### Operating System

Asustor Naas

### How are you running Gitea?

Selfhosted via Docker on Asustor Naas v1.20.5

### Database

None

**Comment by yp05327** [comment]
But in the screenshot 1, "Assignee" isn't checked off?

**Comment by hardiklakhalani** [comment]
Oh, it's opposite. Apologies team.
