### ISSUE TITLE
Wiki migration from self-hosted GitLab fails if GitLab does not use master as default branch name

### ISSUE THREAD

**Issue by heapifyman** [go-gitea/gitea#29000]
### Description

When migrating a project including Wiki from a self-hosted GitLab instance the Wiki does not get migrated if GitLab does **not** use `master` as the default branch name.

Project code will be migrated but Wiki will be empty.

The log shows the following error message:

> gitea  | 2024/01/31 15:54:13 ...s/repository/repo.go:104:MigrateRepositoryGitData() [W] Clone wiki: exit status 128 - fatal: Remote branch master not found in upstream origin

This is probably caused by hard-coded `Branch:        "master",` in `MigrateRepositoryGitData`, line 102 - see https://github.com/go-gitea/gitea/blob/0b1a42ce0f7f8e22d7905bde803d60444c9a9f0b/modules/repository/repo.go#L102

**Steps to reproduce**

1. Change default branch name of GitLab instance to `main` - this will result in both project repository and wiki repository to use `main` as default branch name
2. In gitea, start a migration from GitLab
3. Select "Wiki"
4. Click "Migrate repository"

**Result**

- Code repository is migrated
- Wiki repository is not migrated

**Expected Result**

both code repository and wiki repository should be migrated

### Gitea Version

gitea:latest and gitea:nightly

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

![swappy-20240131_160917](https://github.com/go-gitea/gitea/assets/274236/fa142ed7-d99e-425d-b798-06bbaa4f22fa)

![swappy-20240131_163251](https://github.com/go-gitea/gitea/assets/274236/98696923-67e8-4cbb-8d05-a5558a107b56)

### Git Version

2.43.0

### Operating System

Linux

### How are you running Gitea?

docker compose, following instructions here: https://docs.gitea.com/next/installation/install-with-docker#basics

### Database

None

**Comment by yp05327** [comment]
It depends on GitLab's version:
https://docs.gitlab.com/ee/user/project/wiki/index.html#configure-a-default-branch-for-your-wiki
So maybe we need to add an option in the migration page.

**Comment by techknowlogick** [comment]
Thanks for your investigation and detailed report @heapifyman. I suspect the fix for this would be to either fetch the branch name from the Gitlab api or from the initial git clone when fetching the wiki.

**Comment by KN4CK3R** [comment]
Because Gitea uses the hardcoded `master` Branch for Wikis.

**Comment by lunny** [comment]
We need to store the default branch in database for wiki repository first and then first this problem.

**Comment by lunny** [comment]
Or we can rename GitLab's default branch to `main` when migrating.

**Comment by KN4CK3R** [comment]
`main` may be a better default for GitLab but the name can be anything.

> The default branch for your wiki repository depends on your version of GitLab:
> 
> - GitLab versions 14.1 and later: Wikis inherit the default branch name configured for your instance or group. If no custom value is configured, GitLab uses main.
> - GitLab versions 14.0 and earlier: GitLab uses master. 
> 
> For any version of GitLab, you can rename this default branch for previously created wikis.

https://docs.gitlab.com/ee/user/project/wiki/#configure-a-default-branch-for-your-wiki

**Comment by wxiaoguang** [comment]
->  Make wiki default branch name changable #29603
