### ISSUE TITLE
Copying a code block line contains a trailing newline

### ISSUE THREAD

**Issue by drifter75** [go-gitea/gitea#29012]
### Description

when you copy a code block using the copy button it results in a trailing new line.

https://try.gitea.io/andrewimeson/actions_schedule

### Gitea Version

1.21.4

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

using docker

### Database

PostgreSQL

**Comment by silverwind** [comment]
IIRC this was done because it matched GitHub behaviour, but I see GitHub had changed it to remove the newline, so we should follow suit.
