### ISSUE TITLE
Ineficient repo search fetching

### ISSUE THREAD

**Issue by moritztim** [go-gitea/gitea#29014]
### Description

The repo list / search interface on the homepage is paginated and so is the http response for the request that's made to get it. And whenever you go to another page, another request is sent. I think this could be made noticeably faster by only actually sending one page at a time, along with page count, since that's the only information the client seems to need.

### Screenshots

![network dev tool screenshot](https://github.com/go-gitea/gitea/assets/90388353/5c306ff1-7750-478b-a000-7a60b791b400)

### Gitea Version

1.21.4

### Can you reproduce the bug on the Gitea demo site?

No, because the home page isn't accessible there. 

### Operating System

n/a

### Browser Version

n/a

**Comment by moritz-t-w** [comment]
On second thought I'm not sure I categorized this correctly

**Comment by lunny** [comment]
Did you mean it will send so many requests when the page load?

**Comment by moritz-t-w** [comment]
No, whenever you go to the next page in the paginated repo list, it requests the entire repo list with all of its pages, instead of just the current page (and total page count).

**Comment by moritz-t-w** [comment]
![image](https://github.com/go-gitea/gitea/assets/90388353/b6ae3f0c-05f2-4670-abf8-95b35c53b041)
To be clear, I am talking about the list to the right, where it says "**Repositories `839`**"

**Comment by moritz-t-w** [comment]
My mistake. It's not actually implemented the way I said, I must have looked at the wrong request :joy:
