### ISSUE TITLE
"This commit is contained in" overflows the box

### ISSUE THREAD

**Issue by colejohnson66** [go-gitea/gitea#29016]
### Description

As shown in the screenshot below, the "this commit is contained in" list overflows the summary box.

### Gitea Version

1.21.4

### Can you reproduce the bug on the Gitea demo site?

Untested

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/11381599/f14facf8-b261-447a-8799-e10f0ff56f6a)
![image](https://github.com/go-gitea/gitea/assets/11381599/6da814ac-8ba9-4733-8632-409216b890f2)

### How are you running Gitea?

Service on Windows Server

### Database

MySQL/MariaDB

**Comment by silverwind** [comment]
Maybe we should try a `overflow-wrap: anywhere` global CSS rule to fix these issues once and for all, but may have side-effects on elements that do not expect their content to wrap.

**Comment by colejohnson66** [comment]
It's in a flexbox, so adding `overflow-warp:anywhere` to the `div.tag-area` element does this:

![image](https://github.com/go-gitea/gitea/assets/11381599/0e08ad94-eab6-4aca-96f3-2ad98a8448e6)

**Comment by silverwind** [comment]
Right, in this case the correct solution will be `flex-wrap: wrap` on the parent node.

And sadly, it already highlights why we can't have global `overflow-wrap: anywhere`.

**Comment by colejohnson66** [comment]
`flex-wrap: wrap` does indeed fix the issue:

![image](https://github.com/go-gitea/gitea/assets/11381599/05a344f9-ccbc-4527-9fa6-9fe51b3171dd)

**Comment by delvh** [comment]
The funny thing is: I originally designed the box so that it should already do that (compare with the screenshot in #25180).
I thought I designed it resilient enough not to have this type of problem, but apparently something else must have changed in the meantime…
