### ISSUE TITLE
Project Board-Column-Titles are without ellipsis

### ISSUE THREAD

**Issue by zokkis** [go-gitea/gitea#29029]
### Description

When Creating a Column to a Project with a really long name its overflowing

https://gitea.com/zokki/Tests/projects/2343

### Screenshots

![Screenshot from 2024-02-02 16-18-56](https://github.com/go-gitea/gitea/assets/72873130/160aab65-1ddc-4d42-905c-6fa6d4a9c892)

### Gitea Version

1.21.5

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

Linux

### Browser Version

Firefox v122

**Comment by wxiaoguang** [comment]
Title: it should have been fixed

![image](https://github.com/user-attachments/assets/e05f7eae-7eaa-4cef-bd13-320ccbb153ff)

**Comment by wxiaoguang** [comment]
Attachment: it should have been fixed

![image](https://github.com/user-attachments/assets/b22ea8f9-ea10-4f50-9d0a-23ae7e0ed5cc)
