### ISSUE TITLE
Edited Project-Column titles missing the number of issues

### ISSUE THREAD

**Issue by zokkis** [go-gitea/gitea#29031]
### Screenshots

![Screenshot from 2024-02-03 03-07-04](https://github.com/go-gitea/gitea/assets/72873130/b2f17ee1-2e40-401b-a02d-2c593936295c)

### Gitea Version

1.21.5

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

Linux

### Browser Version

Firefox v122

**Comment by wxiaoguang** [comment]
It should have been fixed

![image](https://github.com/user-attachments/assets/89a52bab-61c7-47c7-88fa-596dc85e7274)
