### ISSUE TITLE
Circular loading spinner is an oval on mobile

### ISSUE THREAD

**Issue by lukeh990** [go-gitea/gitea#29041]
### Description

When doing any operation that starts a loading spinner on mobile. It is always an oblong shape instead of a perfect circle. Most notably I see this when loading the user dashboard, logging in with passkey, or in any loading spinner. 

### Screenshots

![IMG_0226](https://github.com/go-gitea/gitea/assets/20286772/17d68ecf-45b8-437e-be99-caed48296a18)

### Gitea Version

1.21.5

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

iOS 17.3

### Browser Version

AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.3 Mobile/15E148 Safari/604.1

**Comment by yardenshoham** [comment]
Can't reproduce on chrome
![image](https://github.com/go-gitea/gitea/assets/20454870/5c78f09f-771b-4b4b-967e-e1e95783e316)

**Comment by techknowlogick** [comment]
I've seen this on Gitea.com using the mobile safari browser. I can't replicate using a desktop browser even after changing viewport, so I'll have to figure out how to finally set up the remote developer console so I can see what happening.

**Comment by lukeh990** [comment]
I was able to recreate it again on a Mac. The easiest way I found of replicating it is with the passkey prompt. It was even too on the desktop viewport. It is most certainly a webkit issue. I tired poking around with the CSS and it look like the `aspect-ratio: 1` set on the `.is-loading:after` selector is not being enforced as the width and height are not the same. 
<img width="1100" alt="Screenshot 2024-02-04 at 13 57 38" src="https://github.com/go-gitea/gitea/assets/20286772/13d5fbea-4385-4731-99a9-43bd8f4619ef">
<img width="394" alt="Screenshot 2024-02-04 at 13 51 09" src="https://github.com/go-gitea/gitea/assets/20286772/71b072a0-f03a-4283-b6c1-af24704182b9">

**Comment by lukeh990** [comment]
I think I've managed to isolate the issue to the border properties. I created a codeine and started adding individual components of the gitea `.is-loading::after` selector. It looked fine up until I added the border in. After that  it just suddenly jumped. See this [codepen](https://codepen.io/lukeh990/pen/ZEPRzJJ) (Only view with safari). 

I made a little diagram of what is happening: 
<img width="770" alt="Screenshot 2024-02-04 at 14 22 53" src="https://github.com/go-gitea/gitea/assets/20286772/7c7d81ff-872c-48e2-8fa4-eb58ae5f0b7d">

Here is what the codepen window looks like: 
<img width="971" alt="Screenshot 2024-02-04 at 14 21 25" src="https://github.com/go-gitea/gitea/assets/20286772/2915d0b8-27d9-4563-9a89-4ffb6021844c">
