### ISSUE TITLE
Protect SSH (and HTTP)

### ISSUE THREAD

**Issue by jacksgt** [go-gitea/gitea#2905]
- Gitea version (or commit ref): 1.2.2
- Operating system: Debian 9 Stretch
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:
```
swarm_gitea.1.ibp3uqa9nkp8@cubieserver    | 2017/11/11 14:30:55 [W] SSH: Handshaking was terminated: EOF
swarm_gitea.1.yi79ft8qdzlb@cubieserver    | 2017/10/31 16:09:17 [W] SSH: Handshaking was terminated: EOF
swarm_gitea.1.ibp3uqa9nkp8@cubieserver    | 2017/11/11 14:43:32 [...a/modules/ssh/ssh.go:140 func1()] [E] SSH: Error on handshaking: read tcp 10.255.0.7:2222->10.255.0.2:2477: read: connection reset by peer
swarm_gitea.1.ibp3uqa9nkp8@cubieserver    | 2017/11/11 14:43:48 [...a/modules/ssh/ssh.go:140 func1()] [E] SSH: Error on handshaking: read tcp 10.255.0.7:2222->10.255.0.2:4374: read: connection reset by peer
swarm_gitea.1.yi79ft8qdzlb@cubieserver    | 2017/10/31 17:20:18 [...a/modules/ssh/ssh.go:140 func1()] [E] SSH: Error on handshaking: read tcp 10.255.0.7:2222->10.255.0.2:35502: read: connection timed out
swarm_gitea.1.yi79ft8qdzlb@cubieserver    | 2017/10/31 18:03:36 [...a/modules/ssh/ssh.go:140 func1()] [E] SSH: Error on handshaking: read tcp 10.255.0.7:2222->10.255.0.2:53959: read: connection reset by peer
swarm_gitea.1.ibp3uqa9nkp8@cubieserver    | 2017/11/11 14:43:56 [...a/modules/ssh/ssh.go:140 func1()] [E] SSH: Error on handshaking: read tcp 10.255.0.7:2222->10.255.0.2:1873: read: connection reset by peer
swarm_gitea.1.ibp3uqa9nkp8@cubieserver    | 2017/11/11 14:43:56 [...a/modules/ssh/ssh.go:140 func1()] [E] SSH: Error on handshaking: write tcp 10.255.0.7:2222->10.255.0.2:2663: write: connection reset by peer
swarm_gitea.1.yi79ft8qdzlb@cubieserver    | 2017/10/31 18:03:36 [W] SSH: Handshaking was terminated: EOF
swarm_gitea.1.yi79ft8qdzlb@cubieserver    | 2017/10/31 19:05:44 [...a/modules/ssh/ssh.go:140 func1()] [E] SSH: Error on handshaking: read tcp 10.255.0.7:2222->10.255.0.2:2029: read: connection reset by peer
swarm_gitea.1.ibp3uqa9nkp8@cubieserver    | 2017/11/11 14:44:00 [...a/modules/ssh/ssh.go:140 func1()] [E] SSH: Error on handshaking: write tcp 10.255.0.7:2222->10.255.0.2:3020: write: connection reset by peer
swarm_gitea.1.ibp3uqa9nkp8@cubieserver    | 2017/11/11 14:44:04 [...a/modules/ssh/ssh.go:140 func1()] [E] SSH: Error on handshaking: read tcp 10.255.0.7:2222->10.255.0.2:3548: read: connection reset by peer
swarm_gitea.1.yi79ft8qdzlb@cubieserver    | 2017/11/01 02:30:37 [...a/modules/ssh/ssh.go:140 func1()] [E] SSH: Error on handshaking: read tcp 10.255.0.7:2222->10.255.0.2:36847: read: connection reset by peer
swarm_gitea.1.yi79ft8qdzlb@cubieserver    | 2017/11/01 02:42:29 [...a/modules/ssh/ssh.go:140 func1()] [E] SSH: Error on handshaking: read tcp 10.255.0.7:2222->10.255.0.2:36811: read: connection reset by peer
swarm_gitea.1.ibp3uqa9nkp8@cubieserver    | 2017/11/11 14:44:23 [...a/modules/ssh/ssh.go:140 func1()] [E] SSH: Error on handshaking: read tcp 10.255.0.7:2222->10.255.0.2:3940: read: connection reset by peer
swarm_gitea.1.ibp3uqa9nkp8@cubieserver    | 2017/11/11 14:44:23 [...a/modules/ssh/ssh.go:140 func1()] [E] SSH: Error on handshaking: write tcp 10.255.0.7:2222->10.255.0.2:1832: write: connection reset by peer
swarm_gitea.1.yi79ft8qdzlb@cubieserver    | 2017/11/01 10:23:07 [W] SSH: Handshaking was terminated: EOF
swarm_gitea.1.yi79ft8qdzlb@cubieserver    | 2017/11/01 10:25:04 [W] SSH: Handshaking was terminated: EOF
swarm_gitea.1.ibp3uqa9nkp8@cubieserver    | 2017/11/11 14:44:27 [...a/modules/ssh/ssh.go:140 func1()] [E] SSH: Error on handshaking: write tcp 10.255.0.7:2222->10.255.0.2:2150: write: connection reset by peer
swarm_gitea.1.ibp3uqa9nkp8@cubieserver    | 2017/11/11 14:44:31 [...a/modules/ssh/ssh.go:140 func1()] [E] SSH: Error on handshaking: write tcp 10.255.0.7:2222->10.255.0.2:2585: write: connection reset by peer
swarm_gitea.1.yi79ft8qdzlb@cubieserver    | 2017/11/01 14:45:51 [...a/modules/ssh/ssh.go:140 func1()] [E] SSH: Error on handshaking: read tcp 10.255.0.7:2222->10.255.0.2:49158: read: connection reset by peer
swarm_gitea.1.ibp3uqa9nkp8@cubieserver    | 2017/11/11 14:44:34 [...a/modules/ssh/ssh.go:140 func1()] [E] SSH: Error on handshaking: write tcp 10.255.0.7:2222->10.255.0.2:2938: write: connection reset by peer
swarm_gitea.1.yi79ft8qdzlb@cubieserver    | 2017/11/01 14:45:52 [...a/modules/ssh/ssh.go:140 func1()] [E] SSH: Error on handshaking: ssh: invalid packet length, packet too large
swarm_gitea.1.yi79ft8qdzlb@cubieserver    | 2017/11/01 14:45:54 [...a/modules/ssh/ssh.go:140 func1()] [E] SSH: Error on handshaking: ssh: invalid packet length, packet too large
swarm_gitea.1.ibp3uqa9nkp8@cubieserver    | 2017/11/11 14:44:46 [...a/modules/ssh/ssh.go:140 func1()] [E] SSH: Error on handshaking: write tcp 10.255.0.7:2222->10.255.0.2:3277: write: connection reset by peer
swarm_gitea.1.ibp3uqa9nkp8@cubieserver    | 2017/11/11 14:44:50 [...a/modules/ssh/ssh.go:140 func1()] [E] SSH: Error on handshaking: write tcp 10.255.0.7:2222->10.255.0.2:4722: write: connection reset by peer
swarm_gitea.1.ibp3uqa9nkp8@cubieserver    | 2017/11/11 14:44:57 [...a/modules/ssh/ssh.go:140 func1()] [E] SSH: Error on handshaking: write tcp 10.255.0.7:2222->10.255.0.2:1235: write: connection reset by peer
swarm_gitea.1.ibp3uqa9nkp8@cubieserver    | 2017/11/11 14:45:00 [...a/modules/ssh/ssh.go:140 func1()] [E] SSH: Error on handshaking: write tcp 10.255.0.7:2222->10.255.0.2:1816: write: connection reset by peer
swarm_gitea.1.yi79ft8qdzlb@cubieserver    | 2017/11/01 16:23:09 [W] SSH: Handshaking was terminated: EOF
swarm_gitea.1.yi79ft8qdzlb@cubieserver    | 2017/11/01 19:31:37 [W] SSH: Handshaking was terminated: EOF
swarm_gitea.1.ibp3uqa9nkp8@cubieserver    | 2017/11/11 14:45:04 [...a/modules/ssh/ssh.go:140 func1()] [E] SSH: Error on handshaking: write tcp 10.255.0.7:2222->10.255.0.2:2160: write: connection reset by peer
swarm_gitea.1.ibp3uqa9nkp8@cubieserver    | 2017/11/11 14:45:24 [...a/modules/ssh/ssh.go:140 func1()] [E] SSH: Error on handshaking: write tcp 10.255.0.7:2222->10.255.0.2:4536: write: connection reset by peer
swarm_gitea.1.yi79ft8qdzlb@cubieserver    | 2017/11/01 19:31:51 [...a/modules/ssh/ssh.go:140 func1()] [E] SSH: Error on handshaking: read tcp 10.255.0.7:2222->10.255.0.2:35012: read: connection reset by peer
swarm_gitea.1.yi79ft8qdzlb@cubieserver    | 2017/11/01 19:32:11 [W] SSH: Handshaking was terminated: EOF
```

## Description

I get a lot of brute-force attacks on my SSH Port of Gitea (see logs above) (I'd be interested in what the traffic looks like on try.gitea.io). For normal SSH, one can use tools like [fail2ban](http://www.fail2ban.org/wiki/index.php/Main_Page) to ignore/drop such brute-force connections.

While fail2ban is commonly used for the openbsd sshd server, Gitea uses its own SSH server, so it is not compatible.

However, I recently came across [BadActor](https://www.badactor.org/) (https://github.com/jaredfolkins/badactor), which is "an in-memory application driven jailer written in Go". Therefore I think it can be integrated nicely into Gitea.

Additionally, I can also be used to protect brute-force attacks on the HTTP endpoints as well as the API.

**Comment by kolaente** [comment]
But fail2ban actually does only read logfiles and creates iptables, so it shoudl be possible to set up with gitea, shouldn't it? (Only need to point fail2ban to the logfile of the ssh-server... or is the real problem ther is no ssh logfile?)

**Comment by lafriks** [comment]
I would prefer that fail2ban would be used to read gitea logs

**Comment by kolaente** [comment]
@lafriks I'd also prefer that 😄 

So the real problem is there isn't really a dedicated logfile for ssh login (attemts)?

**Comment by jacksgt** [comment]
Can you (@lafriks , @kolaente ) provide any explanation to _why_ you would prefer an external solution?

Personally, I favor an integrated solution (especially since this one is written in Go, too, and should therefore be relatively easy to include), because the user does then not need to set up another service, failed / brute-force login attempts can be immediately shown to the administrator and an included solution can be tested and integrated way better (than any external one).

**Comment by bkcsoft** [comment]
@jacksgt In short, integrations (especially optional once like this) makes it a pain to test (since you have to test _all_ the different components). And it also adds to maintainence toil.

**Comment by kolaente** [comment]
@jacksgt I agree with @bkcsoft, also I think we don't need to reinvent the wheel, fail2ban does a pretty good job at this.

**Comment by jacksgt** [comment]
@bkcsoft Sure, but after the developers tested it *once*, *all* the users benefit from it. According to that logic, removing every single optional setting (multiple databases, multiple authentication backends, ...) would be a good idea.

@kolaente I agree with you, no need to reinvent the wheel, just use BadActor, it's already written ;-)

But I guess I see your point: unless someone steps up and submits a pull request, no interest in this feature.

**Comment by bkcsoft** [comment]
@jacksgt I'd actually prefer if the "multiple auth backends" went away 😂 Though not completely, but just redesigned into a single RPC that sends `{username, password string}` and returned `{success bool}`. That way Gitea can focus on fixed set of auth backends, while allowing the community to write and maintain their own auth backends 😉

**Comment by jacksgt** [comment]
While I personally prefer a direct service directly integrated (like [BadActor](https://www.badactor.org/)), I guess this Issue can be closed for now: https://github.com/go-gitea/gitea/pull/3949

**Comment by skylord123** [comment]
I think this may need to be re-opened.

I am not getting any log events for my SSH server with failed login attempts. I only get them for the web server.

**Comment by lunny** [comment]
Did you use OpenSSH or internal SSH?

**Comment by guillep2k** [comment]
There's a new log system that can help with this. It should be easy enough to normalize Gitea errors to feed fail2ban efficiently. What programs like fail2ban need is:

* A log file where all auth-related problems are logged.
* The messages in the log should include the originating IP address.
* The messages in the log should be easy to regexp to.
* The format for auth-related messages should be relatively stable (not change often), and not without proper notice (e.g. changelog).
* The messages for auth-related problems should be listed somewhere in the docs.

For example, the following should work:

```
2017/11/01 02:30:37 [...a/modules/ssh/ssh.go:140 func1()] [E] SSH: Error on handshaking: read tcp 10.255.0.7:2222->10.255.0.2:36847: read: connection reset by peer
```

That's all. Yes, that's an actual log from Gitea (taken from the first comment of this post). As long as the message is recognizable and has the proper information, it's usable. Here's a sample filter file for fail2ban (drupal.conf):

```
# Fail2Ban filter to block repeated failed login attempts to Drupal site(s)
#
#
# Drupal must be setup to use Syslog, which defaults to the following format:
#
#   !base_url|!timestamp|!type|!ip|!request_uri|!referer|!uid|!link|!message
#
#

[INCLUDES]

before = common.conf


[Definition]

failregex = ^%(__prefix_line)s(https?:\/\/)([\da-z\.-]+)\.([a-z\.]{2,6})(\/[\w\.-]+)*\|\d{10}\|user\|<HOST>\|.+\|.+\|\d\|.*\|Login attempt failed for .+\.$

ignoreregex =


# DEV Notes:
#
# https://www.drupal.org/documentation/modules/syslog
#
# Author: Lee Clemens
```

The conf file accepts multiple `failregex` entries, so log messages don't need to be too similar.

So I think the job here is to:

* Identify the security-related messages.
* Check their "_parseability_".
* Normalize/correct when needed.
* Make sure they all point to the same log.
* List them in the docs.
* Place a warning in the source file for maintainers, so they don't change them inadvetently.

**Comment by skylord123** [comment]
> Did you use OpenSSH or internal SSH?

@lunny I believe it is the internal one. I am using the official docker container on the latest version as of posting.

**Comment by denji** [comment]
https://bitbucket.org/sshguard/sshguard/src/v2.3.1/src/parser/attack_scanner.l#lines-302:304

**Comment by huebnerf** [comment]
Like @skylord123, i have the same problem of no ssh auth logs being present in the gitea log. This occurs for both, OpeSSH and internal ssh.

When trying to log into a non existing user, there are no logs generated at all.
When trying to push a commit to a repo with no valid key registered in gitea, just [SQL] logs are generated for me.

I am running gitea in a docker container, which binds its ssh port directly to the host and is reachable fine from the outside.

Should i open a new issue for this?

**Comment by lunny** [comment]
@huebnerf It depends on your log configuration.

**Comment by huebnerf** [comment]
My configs log section looks like this:
```
[log]
ROOT_PATH = /data/gitea/log
MODE      = file
LEVEL     = info
```
`START_SSH_SERVER` is on its default value `false`.
Will the ssh logs be printed to the logfine only if the internal server is used?

**Comment by skylord123** [comment]
> @huebnerf It depends on your log configuration.

Yes please elaborate. What settings do I need to correctly get failed SSH attempts to show in the log?
