### ISSUE TITLE
conduct@gitea.com: User not found

### ISSUE THREAD

**Issue by oliverpool** [go-gitea/gitea#29055]
### Description

Following the [Gitea Community Code of Conduct](https://github.com/go-gitea/gitea/blob/0d136df3f0b3920d34ce850499e1346fbff29e30/CODE_OF_CONDUCT.md) (introduced in #23188) I sent an email to conduct@gitea.com.

I received an `Undelivered Mail Returned to Sender` reply stating:
```
<conduct@gitea.com>: host m1.feishu.cn[54.221.254.138] said: 550 verify address
    failed, User not found conduct@gitea.com (in reply to RCPT TO command)
```

What is the correct e-mail address to contact the Gitea Project Stewards regarding the Code of Conduct?

### Gitea Version

main

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

-

### Database

None

**Comment by techknowlogick** [comment]
Thank you for your report. I will open a ticket with our email provider to investigate. In the mean time, please feel free to email me at my username @gitea.com and I'll be able to bring it to the rest of the TOC.

In case anyone comes across this thread in the future, please send reports to the appropriate email address, this is just a one off situation. If there are issues with the email in the future please create an issue

**Comment by techknowlogick** [comment]
Closing as the ticket has been resolved with the email provider. The above mentioned report is in review with the TOC, but that is managed separately from this issue.
