### ISSUE TITLE
Code Review Comment Creation 500 in Gitea Version 1.21.3

### ISSUE THREAD

**Issue by Menah3m** [go-gitea/gitea#29063]
### Description

I am using Gitea version 1.21.3, and when creating a code review comment, an error occurs with the following message:

2024/01/30 14:27:51 .../context_response.go:86:HTML() [E] Render failed: failed to render template: repo/diff/conversation, error: template error: builtin(bindata):repo/diff/conversation:1:16 : executing "repo/diff/conversation" at <index .comments 0>: error calling index: reflect: slice index out of range
<img width="1494" alt="image" src="https://github.com/go-gitea/gitea/assets/24191438/b4dda77c-fcbf-4aa7-9acd-27cc51f71ad8">

I noticed that this issue has been fixed in #28351 by the official team, but it seems the fix is not effective. Could you please help investigate how to resolve this issue?

### Gitea Version

1.21.3

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

https://github.com/go-gitea/gitea/assets/24191438/a46e7aa4-36e9-4bf8-aaf3-56a6d68c1dfd

### Git Version

2.39

### Operating System

CentOS7

### How are you running Gitea?

Kubernetes cluster

### Database

PostgreSQL

**Comment by lunny** [comment]
Can you try to upgrade to 1.21.5?

**Comment by wxiaoguang** [comment]
1.21.5 doesn't help.

The root problem is that your PR is closed and outdated, so https://github.com/go-gitea/gitea/pull/29049 might help (in next release 1.21.6 , aka nightly at the moment)

**Comment by lunny** [comment]
I think this has been fixed by #29086 @wxiaoguang ?

**Comment by wxiaoguang** [comment]
Yes, but 1.21.6 hasn't been released yet.
