### ISSUE TITLE
SurrealDB as a database

### ISSUE THREAD

**Issue by itsezc** [go-gitea/gitea#29087]
### Feature Description

Add SurrealDB as a storage layer for Gitea. Indirectly, this will allow for the usage of many storage engines underneath from FoundationDB, TiKV to RocksDB, and eventually SurrealKV.

With a massive growth in installations and adoptions, Surreal is a viable option for Gitea and its wider community.

**Comment by lunny** [comment]
It seems no Golang standard driver support from SurrealDB. Since Gitea depends on [xorm](https://gitea.com/xorm/xorm), it's impossible to use a database that `xorm` doesn't support.

**Comment by lunny** [comment]
I don't think it's a problem since we also support MSSQL which is the close source. We just need to check the driver's license.

**Comment by wxiaoguang** [comment]
Is it really feasible? SurrealDB uses a different syntax than SQL.

**Comment by wxiaoguang** [comment]
> Is it really feasible? SurrealDB uses a different syntax than SQL.

I don't think SurrealDB uses standard SQL or works with Gitea SQL statements. If it is not feasible, I think this proposal could be closed. Correct me if I am wrong.

**Comment by itsezc** [comment]
> > Is it really feasible? SurrealDB uses a different syntax than SQL.
> 
> I don't think SurrealDB uses standard SQL or works with Gitea SQL statements. If it is not feasible, I think this proposal could be closed. Correct me if I am wrong.

Unfortunately, surreal does not use standard SQL, as there is far too many features they provide than what standard SQL syntax allows for intuitively and also doesn't work with Gitea SQL statements at this time.

**Comment by lunny** [comment]
I think we have to refuse this proposal at this time. Maybe we can reopen once upstream supports it.

**Comment by phughk** [comment]
SurrealDB developer here. I can confirm we aren't a standard dialect of SQL and only support SurrealQL which has a lot of differences. So I think this can be closed. Thank you for the interest and efforts though! We may try to open it in the future again if we get true SQL support.
