### ISSUE TITLE
Javascript error: same origin policy

### ISSUE THREAD

**Issue by Silther** [go-gitea/gitea#29080]
### Description

I get an error from my browser that Gitea tried to access forbidden elements to to SOP

### Gitea Version

1.21.1 (-rootless)

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/97352673/8e5cace6-d407-4b4b-aba1-582e60f2f4bf)

![image](https://github.com/go-gitea/gitea/assets/97352673/47476834-44a6-4d65-ae17-aa6bf21fd304)

### How are you running Gitea?

portainer stack

### Database

SQLite

**Comment by wxiaoguang** [comment]
> Lol, that should only be a grafical bug of bitwaden. The same javascript error also happens on the demo website
> 
> But will test it with disabled bitwarden.

Could you help to provide the embedded HTML? Then we can make Gitea ignore these non-same origin resources, then there will be no error anymore.

**Comment by wxiaoguang** [comment]
> how can I do that?

Could you also try to figure out the outer `iframe` code?

ps: I proposed a fix #29081.

**Comment by silverwind** [comment]
> > ps: I proposed a fix #29081.
> 
> when ready I could test it with a rootless docker image

We can't do builds for pull requests, so you'd have to build from source and run that.

What are the minimal steps to reproduce? Just install the Bitwarden extension and open Gitea? Any specific settings made in the extension?

**Comment by silverwind** [comment]
Odd, because I'm also a Bitwarden user on Firefix and have never seen this error. There must be something different about your setup.

**Comment by silverwind** [comment]
My extension does not have this "Show auto-fill menu on form fields" option, maybe that is causing the iframe? Try toggling it off. What's the version of your extension? Mine is 2024.1.1.

**Comment by silverwind** [comment]
As per [this](https://community.bitwarden.com/t/just-released-new-inline-auto-fill/61436/50) the feature is only enabled for Bitwarden Cloud users, not self-hosted like mine is.

**Comment by silverwind** [comment]
No, it's fine. https://github.com/go-gitea/gitea/pull/29081 will fix it, one way or another.

**Comment by wxiaoguang** [comment]
> > ps: I proposed a fix #29081.
> 
> when ready I could test it with a rootless docker image

1.21 nightly is ready by #29089
