### ISSUE TITLE
Can't upload big rpm to repo

### ISSUE THREAD

**Issue by alicetails** [go-gitea/gitea#29110]
### Description

Hello!

When I try to upload big RPM (~300M) file to package repo with curl:

`curl --user user --upload-file big.rpm https://git.example.com/api/packages/user/rpm/upload
`
I got an error:

```
Feb 09 09:01:14 LXC-Gitea-192 gitea[5200]: 2024/02/09 09:01:14 .../packages/rpm/rpm.go:29:apiError() [E] Error 1406 (22001): Data too long for column 'value' at row 1
Feb 09 09:01:14 LXC-Gitea-192 gitea[5200]: 2024/02/09 09:01:14 .../packages/rpm/rpm.go:30:func9() [T] plainTextInternal (status=500): Error 1406 (22001): Data too long for column 'value' at row 1
Feb 09 09:01:14 LXC-Gitea-192 gitea[5200]: 2024/02/09 09:01:14 ...eb/routing/logger.go:102:func1() [I] router: completed PUT /api/packages/GP20/rpm/upload for 192.168.88.11:0, 500 Internal Server Error in 10039.8ms @ rpm/rpm.go:111(rpm.UploadPackageFile)
```

Small RPMs uploading successfully

### Gitea Version

1.21.5

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

Debian GNU/Linux 10 (buster) in LXC on Proxmox

### How are you running Gitea?

Deployed from Turnkey image, updated manually

### Database

MySQL/MariaDB

**Comment by KN4CK3R** [comment]
Out of curiosity; Could you enable SQL logging in your config for your upload? There will be a `INSERT INTO package_property ...` query which leads to the error. Could you paste this query here if it does not contain sensitive data? What does make this value so big? Are there lots of changelog lines or files? Is your rpm file public so I could have a look?
