### ISSUE TITLE
SSPI logins don't redirect away from sign-in page

### ISSUE THREAD

**Issue by Craig-Holmquist-NTI** [go-gitea/gitea#29116]
### Description

With 1.21.5, after logging in through SSPI, the login succeeds, but the user remains on the sign-in page instead of redirecting to the home page.

### Gitea Version

1.21.5

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

Before logging in:
![before_login](https://github.com/go-gitea/gitea/assets/106619833/91a4057b-2cde-4a28-a78d-cf388cf7d16f)

Immediately after logging in with SSPI:
![after_login](https://github.com/go-gitea/gitea/assets/106619833/aebd1b8a-a2a2-4504-b68b-9640cc5e7e95)

Screenshots are from Edge 121 but happens with multiple browsers.

### Git Version

2.39.1

### Operating System

Windows Server 2019

### How are you running Gitea?

gitea-1.21.5-windows-4.0-amd64.exe downloaded from Github.

### Database

SQLite

**Comment by wxiaoguang** [comment]
I think it is related to #26105 . After that change, if the user has signed in, then "/user/login" should also redirect.

**Comment by wxiaoguang** [comment]
After this fix:  Make "/user/login" page redirect if the current user has signed in #29583 , maybe this problem could be resolved.
