### ISSUE TITLE
Actions on Danger Zone of repository returns error 404 if user not owner

### ISSUE THREAD

**Issue by webjoel** [go-gitea/gitea#2911]
- Gitea version (or commit ref): e9728bf
- Git version: 2.7.4
- Operating system: Linux ubuntu x64
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

Actions (Transfer Ownership, Erase Wiki Data and Delete This Repository) in Repository Settings > Danger Zone returns errors 404 if user not owner, but user is admin.

## Screenshots

![captura de tela de 2017-11-14 08-39-14](https://user-images.githubusercontent.com/1946348/32776159-cdf57f6a-c918-11e7-8834-57840ccb80e5.png)

![captura de tela de 2017-11-14 08-39-28](https://user-images.githubusercontent.com/1946348/32776167-d3f8cf48-c918-11e7-9143-f14be07228de.png)

**Comment by lafriks** [comment]
I can not seem to reproduce this on latest master. Is this repository is under organization or user owned? And by admin did you mean system admin or team with admin role for specified repositories?

**Comment by webjoel** [comment]
Yes, this repository is under organization.

"Admin" is the user permission "Administrator permissions".

In my case, exist an team with access for an organization, but not all is administrator, but the user what has administrator permission occurs problem.

**Comment by webjoel** [comment]
Steps for to test:

1 - Logged with Owner;
2 - Create a organization;
3 - Create an user with "Administrator permissions";
4 - Create a team in organization created in step 2;
5 - Add in team (created in step 4) the user created in step 3;
6 - Create an repository in organization created in step 2;
7 - Logged with user created in step 3;
8 - Open repository created in step 6;
9 - Press Settings and go Danger Zone;
10 - Try do actions.

**Comment by lafriks** [comment]
What rights team need to have?

**Comment by webjoel** [comment]
![captura de tela de 2017-11-16 11-45-54](https://user-images.githubusercontent.com/1946348/32894386-d093c298-cac3-11e7-9188-31723c1b9434.png)

**Comment by webjoel** [comment]
This bug has been fixed in some commit. :)
