### ISSUE TITLE
Question: Does Gitea have CI Build Status Area?

### ISSUE THREAD

**Issue by Madmorgan007** [go-gitea/gitea#2912]
Hi,

I'm moving from Gogs to this and wondering if or when you might have CI/Build reporting area that I can update the system from my build agent if my code has passed or failed. via some API or would you do what Gitlab do? This is not in Gogs but there is a issue for it. [4631](https://github.com/gogits/gogs/issues/4631) & [813](https://github.com/gogits/gogs/issues/813)
Thanks

**Comment by lafriks** [comment]
Yes there is status API: https://try.gitea.io/api/v1/swagger#/repository/repoCreateStatus

gitea jenkins & drone plugins already supports that out of the box

**Comment by lafriks** [comment]
Currently it only supports displaying status in Commits tab but PR status display is in WIP and will be in 1.4.0 release

**Comment by Madmorgan007** [comment]
Sweet thanks for the feed back

**Comment by LukeOwlclaw** [comment]
@lafriks:  I understand that showing the status in the PR tab is WIP (as of May 2019) --> https://github.com/go-gitea/gitea/pull/2519
But the status in Commits tab should be done by done, right?
Where exactly should the status show up? I cannot find it after creating a status via the API link you posted. Could you provide a screenshot? Thanks!
