### ISSUE TITLE
Uprade fromv1.1.0 to v1.2.3

### ISSUE THREAD

**Issue by DickerPeter** [go-gitea/gitea#2914]
- Gitea version (or commit ref):
- Git version: v1.1.0
- Operating system: Unbuntu 17.10
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x ] MySQL
  - [ ] MSSQL
  - [ ] SQLite

## Description

Good day,

Is there any guidance on how to upgrade from version 1.1.0 to 1.2.3?

I tried the following steps but unfortunately without success:

gitea Folder renamed to gitea old

created a new folder with gitea
here then the version 1.2.3 installed with an extra database

Then I copied the following folders with content into the new directory
- custom
- data

and wanted to start it then.
Unfortunately, that did not work

Did I do something wrong or miss something?

Many thanks for the help

**Comment by lunny** [comment]
any logs?

**Comment by DickerPeter** [comment]
I could now narrow down the problem to apache first

```
Wed Nov 15 13:16:05.904927 2017] [proxy: error] [pid 7938] (111) Connection refused: AH00957: HTTP: attempt to connect to 127.0.0.1:3000 (127.0.0.1) failed
[Wed Nov 15 13:16:05.905077 2017] [proxy_http: error] [pid 7938] [client IP:51457] AH01114: HTTP: failed to make connection to backend: 127.0.0.1
[Wed Nov 15 13:16:06.261066 2017] [proxy: error] [pid 7939] (111) Connection refused: AH00957: HTTP: attempt to connect to 127.0.0.1:3000 (127.0.0.1) failed
[Wed Nov 15 13:16:06.261151 2017] [proxy_http: error] [pid 7939] [client IP:51458] AH01114: HTTP: failed to make connection to backend: 127.0.0.1, referer: https://git.domain.de/
```

**Comment by DickerPeter** [comment]
I found the mistake.

It was a rights issue.
When installing the backup root was set instead of git as a group and owner
