### ISSUE TITLE
UserLinkAccount: pq: value too long for type character varying(25)

### ISSUE THREAD

**Issue by MadalinNitu** [go-gitea/gitea#29142]
### Description

Gitea version 1.21.1 built with GNU Make 4.4.1, go1.21.4 : bindata, timetzdata, sqlite, sqlite_unlock_notify
Git version: 2.40.1
Operating system: Ubuntu 22.04 LTS (Docker gitea/gitea:1.21.1)
Database: PostgreSQL
Log gist:
	2024/02/12 09:56:14 ...eb/routing/logger.go:68:func1() [I] router: polling   GET /user/events for 192.168.100.85:0, elapsed 3170.7ms @ events/events.go:18(events.Events)
	2024/02/12 09:56:15 .../auth/linkaccount.go:169:linkAccount() [E] UserLinkAccount: pq: value too long for type character varying(25)
	2024/02/12 09:56:15 ...eb/routing/logger.go:102:func1() [I] router: completed POST /user/link_account_signin for 192.168.100.85:0, 500 Internal Server Error in 97.1ms @ auth/linkaccount.go:113(auth.LinkAccountPostSignIn)

### Gitea Version

1.21.1

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

I'm running gitea with docker image. I want to link my existing account to an account from my Keycloak environment.

### Database

PostgreSQL

**Comment by silverwind** [comment]
Likely this one: https://github.com/go-gitea/gitea/blob/f3eb835886031df7a562abc123c3f6011c81eca8/models/user/external_login_user.go#L64

What is the name of the auth provider on Keycloak? Should be > 25 characters.

**Comment by wxiaoguang** [comment]
@KN4CK3R IIRC you have reviewed some similar issues before?

**Comment by MadalinNitu** [comment]
> Likely this one: https://github.com/go-gitea/gitea/blob/f3eb835886031df7a562abc123c3f6011c81eca8/models/user/external_login_user.go#L64
> 
> What is the name of the Provider on Keycloak? Should be > 25 characters.

Yep, I have the URL for my Keycloak, which is long with 28 characters. I can't change it because it's internal and follows my naming convention. 

Is it possible to expand the limit for the Gitea authentication URL?

**Comment by silverwind** [comment]
Yes, I think we should add a migration to something like 100 chars.

**Comment by KN4CK3R** [comment]
> @KN4CK3R IIRC you have reviewed some similar issues before?

Yes, was this: https://github.com/go-gitea/gitea/pull/28664#issuecomment-1872635604

> Yep, I have the URL for my Keycloak, which is long with 28 characters. I can't change it because it's internal and follows my naming convention.

The url is unrelated. Do you really use a name longer than 25 characters?
![grafik](https://github.com/go-gitea/gitea/assets/1666336/d7dfe161-c143-4cf9-9d11-2709ea47abd7)

**Comment by MadalinNitu** [comment]
Oh, now I realize that the name displayed in the Gitea settings is only for display purposes. 
I'm not sure why I thought it had to be the same as the client ID. 

I changed the authentication name to "Keycloak", and everything works fine now. 

Thank you very much.
