### ISSUE TITLE
Failed to update size for repository with 2 replicas of gitea during concurrent git push

### ISSUE THREAD

**Issue by govind32088** [go-gitea/gitea#29156]
### Description

2024/02/13 09:40:18 ...s/repository/push.go:38:handler() [E] pushUpdate failed: Failed to update size for repository: updateSize: lstat /data/git/gitea-repositories/gitea_admin/govindtest.git/refs/heads/branch-1707817199-2f7ffc69e8f6457d817b615cfaf193be.lock: no such file or directory

I am running gitea with 2 replicas on **kubernetes** and running concurrent request towards gitea using shell script which perform following:

![image](https://github.com/go-gitea/gitea/assets/36735680/bdbc6e08-3987-4d57-913f-5b35110e5b51)

I am running above script concurrently with 50 request, I am getting 'pushUpdate Failed' Error. I am running the shell script using WSL and on client side I am not getting any error but in Gitea  log i can see this problem. In the Gitea UI , I can see 46 branch were successfully created but 4 were missing due to 'pushUpdate Failed' Error

In the past same issue is raised and based on below ticket this issue was already fixed and merged.
https://github.com/go-gitea/gitea/issues/22386

### Gitea Version

1.21.0 (Gitea 9.6.0 tar helm chart)

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

git version 2.40.1

### Operating System

windows

### How are you running Gitea?

using Kubernetes

### Database

PostgreSQL

**Comment by lunny** [comment]
Please upgrade to v1.21.5, I think this has been fixed by #28285

**Comment by govind32088** [comment]
Thanks Lunny. I have upgraded to V1.21.5 and i can confirm i don't see this issue any more.

**Comment by govind32088** [comment]
But i see another problem related to performance degradation between 1.21.0 and 1.21.5. Concurrent Git clone operation taking longer on 1.21.5. I will share with you my finding shortly.

**Comment by techknowlogick** [comment]
Are you using the helm chart or installing Gitea in k8s another way?

**Comment by lunny** [comment]
> But i see another problem related to performance degradation between 1.21.0 and 1.21.5. Concurrent Git clone operation taking longer on 1.21.5. I will share with you my finding shortly.

Let's post another issue.
