### ISSUE TITLE
Pull request created by deleted user can not be opened

### ISSUE THREAD

**Issue by perlfisch** [go-gitea/gitea#29159]
### Description

One of our users created a pull request and his account was deleted later on. Attempting to open this pull request results in the standard error page with return code 500. Other pull requests created by the same account are fine.

Attempting to open the pull requests results in Gitea logging the following line:

2024/02/13 11:32:58 ...rs/web/repo/issue.go:1405:ViewIssue() [E] LoadAttributes: user does not exist [uid: 47, name: , keyid: 0]

Behavior is independent of the permissions of the account used to open the page. No other errors are logged.

### Gitea Version

v1.21.5

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

Debian 12

### How are you running Gitea?

Packages provided by gitea on Github

### Database

PostgreSQL

**Comment by KN4CK3R** [comment]
Was that user assigned to the PR or has left a review comment? For both I see some problems with deleted users. Or was the user just the poster of the PR?

**Comment by KN4CK3R** [comment]
Could you test if #29161 fixes your problem? Otherwise we need more info.

**Comment by perlfisch** [comment]
Thanks for looking into this!

> Was that user assigned to the PR or has left a review comment? For both I see some problems with deleted users. Or was the user just the poster of the PR?

The user created the PR and it is possible that he was assignee or left review comments. I am unable to tell whether this is the case, as I can not open the PR.

> Could you test if https://github.com/go-gitea/gitea/pull/29161 fixes your problem? Otherwise we need more info.

I am unable to deploy unofficial releases into the production infrastructure this is occurring on. How would you recommend obtaining additional information about the cause of the issue?

**Comment by KN4CK3R** [comment]
If you have access to the database, check if one of these queries has a result. If yes, then #29161 will fix your issue.

```sql
select * from comment join issue on (issue.id = comment.issue_id) where assignee_id = 47 and issue.index = ?
select * from review join issue on (issue.id = review.issue_id) where reviewer_id = 47 and issue.index = ?
```
Replace the `?` with the PR id you see in the url.

**Comment by perlfisch** [comment]
Yep, that seems to be the issue then.

```
select * from comment join issue on (issue.id = comment.issue_id) where assignee_id = 47 and issue.index = ?
```
returns two rows and

```
select * from review join issue on (issue.id = review.issue_id) where reviewer_id = 47 and issue.index = ?
```
Returns one row for the PR in question

Thanks again for the quick responses!

**Comment by KN4CK3R** [comment]
Then you can just change the `reviewer_id` to `-1` (or any other existing user id) to restore that PR.

**Comment by perlfisch** [comment]
Yep, that worked, thanks a lot again for your help! Feel free to close this issue now or once the PR is merged.

**Comment by wxiaoguang** [comment]
wait for backport
