### ISSUE TITLE
Long list of build status not visible on commit view

### ISSUE THREAD

**Issue by gzzi** [go-gitea/gitea#29154]
### Description

Hello,

In the view of a commit, if the build list is long, it's impossible to see status of all the builds. It's cut at the top of the window.

I propose that the list goes down instead of up or that we can click on the cross/tick to see the full list in a separate page.

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/24816508/13a97ff3-3c26-49b5-a872-c48365b2d2f6)

### Gitea Version

1.20.5

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

Windows

### Browser Version

Firefox 122.0

**Comment by silverwind** [comment]
This should be corrected by the popper.js [`flip`](configs.js) behaviour, maybe we have not enabled it yet.

**Comment by 99rgosse** [comment]
> This should be corrected by the popper.js [`flip`](https://popper.js.org/docs/v2/modifiers/flip/) behaviour, maybe we have not enabled it yet.

I tried to add 
`      popperOptions: {
        modifiers: [
            {
          name: 'flip',
          options: {
            fallbackPlacements: ['bottom', 'right'],
            },
          }
        ],
       },`

in https://github.com/go-gitea/gitea/blob/main/web_src/js/features/repo-commit.js#L66 but maybe I'm in the wrong place ?

**Comment by silverwind** [comment]
It's a good place, but even better would be for all tippy instances, e.g. here:

https://github.com/go-gitea/gitea/blob/2d8756a9607ee6029ad7a44985e9751988d5fdaa/web_src/js/modules/tippy.js#L10

Also I think `flip` should be enabled by default in tippy.js, so maybe it es enabled but not working correctly. Try if any other popper.js options work.

**Comment by silverwind** [comment]
I think you need to upgrade to v1.21. That popup received a number of enhancements and it does seem to flip correctly for me as well:

<img width="470" alt="image" src="https://github.com/go-gitea/gitea/assets/115237/b0b1fcbf-4a4d-4974-b862-e174991f8482">

**Comment by 99rgosse** [comment]
Excellent, thanks for the clarification @silverwind 
We will upgrade quickly then !
