### ISSUE TITLE
JS error: JavaScript promise rejection: TypeError: null is not an object (evaluating 'userSettings.serverConfig.environment.vault'). Open browser console to see more details.

### ISSUE THREAD

**Issue by KerryXEX** [go-gitea/gitea#29177]
### Description

Since the last 2 docker gitea versions I see this error on every page:
JavaScript promise rejection: TypeError: null is not an object (evaluating 'userSettings.serverConfig.environment.vault'). Open browser console to see more details.

I couldn't find anything on the web and also not in Gitea settings and wiki.

After checking that this also happens on the Gitea Demo site, I noticed this is a Mac Safari (17.2.1) issue (doesn't happen on Edge or Chrome. I also tried to uncheck security/privacy features of Safari and Devmode options but nothing changed.

Any ideas what might trigger this in Safari?

Thanks

### Gitea Version

gitea/gitea:latest  1.21.5

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

macOS sonoma 14.2.1

### How are you running Gitea?

Docker container on Synology DSM

### Database

MySQL/MariaDB

**Comment by wxiaoguang** [comment]
I think it is a bug of bitwarden

* https://github.com/bitwarden/clients/issues/6562

**Comment by silverwind** [comment]
Extension issue, please update it.

**Comment by KerryXEX** [comment]
Thanks alot - you're right, Bitwarden issue!
