### ISSUE TITLE
Gitea action user avatar broken on edit

### ISSUE THREAD

**Issue by TheZoker** [go-gitea/gitea#29178]
### Description

When the gitea-action runner posts a comment on a PR or issue, the avatar on the left works fine. But when the runner now edits a post, the avatar is broken (see screenshot)

### Gitea Version

1.21.5+16-g732d511e0

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/1368405/c1758cb0-bcd0-413d-a91c-cdbce48722ae)

### How are you running Gitea?

Docker

### Database

None

**Comment by wxiaoguang** [comment]
wait for backport

**Comment by lunny** [comment]
closed by #29307

**Comment by TheZoker** [comment]
I can confirm, that this issue is solved in the latest version. Thanks 🎉
