### ISSUE TITLE
Gitea ZIP Download of LFS Files downloads the pointer

### ISSUE THREAD

**Issue by wienans** [go-gitea/gitea#29181]
### Description

Using LFS in my repo and downloading the zip file of the repo downloads the pointers of the LFS Files instead of the correctly stored LFS File. If i go to the file in the Browser and klick the single file download it downloads the correct file.

I wanted to test it on try.gitea.io but currently the register / sign in pages timed out and i am not sure if LFS is active on the Server.

important app.ini config
```
[server]
SSH_DOMAIN = 
DOMAIN = 
HTTP_PORT =  
ROOT_URL = 
APP_DATA_PATH = 
SSH_AUTHORIZED_KEYS_BACKUP = true
DISABLE_SSH = false
SSH_PORT =  
LFS_START_SERVER = true
OFFLINE_MODE = false
LFS_JWT_SECRET =
```

### Gitea Version

1.21.5

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

2.42.0, Wire Protocol Version 2 Enabled

### Operating System

Windows

### How are you running Gitea?

1.21.5 built with GNU Make 4.3, go1.21.6 : bindata, sqlite, sqlite_unlock_notify
downloaded from your server

### Database

SQLite

**Comment by yp05327** [comment]
Tested in GitHub. Not sure which is better, but GitHub has the same behavior.
https://github.com/yp05327/testlfs

**Comment by techknowlogick** [comment]
Gitea just provides the archive that git exports which means it only provides pointers. There is an enhancement request open already to include the files in the archive. I am closing this in favour of that one.
