### ISSUE TITLE
Add extra 'Projects' layer

### ISSUE THREAD

**Issue by tonk** [go-gitea/gitea#2918]
Currently the Gitea server has 'two levels', the Organisation and Repository levels.

I very often work for an organisation, doing a project that contains multiple repositories.
Now I'm creating an Organisation for each project, but is not the way I really want this to go.

It would be (in my opinion) be way better to have three levels, Organisation, Project and Repository levels.

**Comment by lafriks** [comment]
I think Projects could be some kind of meta layer that should not be under organization but so that existing repositories could be added to them like links. This way same repository could be reused in multiple projects and also project could contain repositories from multiple organizations

**Comment by tonk** [comment]
Agree. To be honest, I'm not hooked on names, like Project or implementation. So I don't mind which way some functionality like would be implemented.

As I don't code in Go (yet, first training next week :-)) I'm not able to really help getting it in.

**Comment by RyanSquared** [comment]
Relevant? #363

**Comment by lunny** [comment]
duplicated with #363
