### ISSUE TITLE
Update branch by merge UI problem in mobile view

### ISSUE THREAD

**Issue by yp05327** [go-gitea/gitea#29189]
### Description

![image](https://github.com/go-gitea/gitea/assets/18380374/d5810887-2d58-4b2c-9f2b-264ec88bc1a8)

### Gitea Version

latest

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

build

### Database

None

**Comment by charles7668** [comment]
This problem can be reproduced when the screen width is equal to or greater than 768.

![圖片](https://github.com/go-gitea/gitea/assets/30816317/ae5dad02-b88e-4768-be53-77cebefe646f)
