### ISSUE TITLE
Contributors page doesn't look good on mobile view

### ISSUE THREAD

**Issue by sahinakkaya** [go-gitea/gitea#29192]
### Description

Contributors page doesn't look good on mobile view.

See it here: https://try.gitea.io/kamiya/Xray-core/activity/contributors

### Screenshots

<img width=587 src="https://github.com/go-gitea/gitea/assets/32161460/b8590a08-fc18-4aa2-9e91-aa479e7b0daa"/>

### Gitea Version

latest

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

-

### Browser Version

-

**Comment by silverwind** [comment]
Hmm, I thought we had media query that makes these single-column on mobile, should re-verify.

**Comment by sahinakkaya** [comment]
The title showing date range is also too big. I think it should fit on a single line.

**Comment by sahinakkaya** [comment]
And also the dropdown menu on the right of the title.

**Comment by silverwind** [comment]
Dropdown text can be reduced to `Commits`, Font size maybe slightly reduced.

**Comment by yp05327** [comment]
related: https://github.com/go-gitea/gitea/pull/27882#discussion_r1387587849

**Comment by silverwind** [comment]
https://github.com/go-gitea/gitea/pull/29597
