### ISSUE TITLE
500 while creating users

### ISSUE THREAD

**Issue by Infinoid** [go-gitea/gitea#29218]
### Description

When an admin of a limited/private server goes to create a new user, the `User visibility` field of the "Create User Account" page has a bug.  Specifically, after the form submission validation is rejected, the `User visibility` dropdown seems to be mapping the wrong values.

This looks very similar to #25951, but it happens in gitea 1.21.5, and only happens after a form submission error.

Gitea configuration:
```ini
[service]
DISABLE_REGISTRATION              = true
DEFAULT_USER_VISIBILITY           = limited
ALLOWED_USER_VISIBILITY_MODES     = limited,private
```

Steps to reproduce:

1. Have a gitea instance configured as described above
2. Log in as an admin user
3. Attempt to create a new user through the `/admin/users/new` page, but fail the form validation
4. Correct the form fields and submit again
5. 500 internal server error

I compared the DOM trees before and after the validation failure, and the dropdown box selection no longer has the classes `active` and `selected`.

Before validation failure:
```html
<div class="item active selected" data-tooltip-content="Visible only to authenticated users" data-value="1" id="_aria_auto_id_16" role="option" tabindex="-1" aria-label="Visible only to authenticated users">Limited</div>
```

After validation failure:
```html
<div class="item" data-tooltip-content="Visible only to authenticated users" data-value="1" id="_aria_auto_id_16" role="option" tabindex="-1" aria-label="Visible only to authenticated users">Limited</div>
```

That might be the problem?  I'm not completely sure, but it looks likely to me.

### Gitea Version

1.21.5

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/50254/332e8af9-43fe-4c55-af21-f421a24adee9)
![image](https://github.com/go-gitea/gitea/assets/50254/12ed90a5-fd0f-43c9-a6a4-9d4c6cb29bf9)
![image](https://github.com/go-gitea/gitea/assets/50254/51b57dc0-9c94-4685-af5c-365dca81d577)

### How are you running Gitea?

official docker image, GOARCH=arm64

### Database

PostgreSQL

**Comment by Infinoid** [comment]
I tried today's "nightly" docker build, and confirmed that this is fixed.  Thanks!

Wish the UI had some unit tests to prove these things tho...

**Comment by silverwind** [comment]
Can't really unit-test a HTML form, but a [e2e test](https://github.com/go-gitea/gitea/tree/main/tests/e2e) might be able to.
