### ISSUE TITLE
API endpoint to configure default branch and protected branches is missing

### ISSUE THREAD

**Issue by nblock** [go-gitea/gitea#2922]
- Gitea version: 1.2.3

## Description
Gitea allows to configure the default branch and protected branches via GITEA_URL/org/repo/settings/branches but I could not find an API alternative in the local Swagger documentation.

**Comment by davidlt** [comment]
I am also looking for such API especially since 1.4.1 set random default branch on `git push --mirror` ( https://github.com/go-gitea/gitea/issues/3913 ). Thus I wanted to use API to reset it back to `master`.

**Comment by davidlt** [comment]
Looks like GitHub supports it at least since 2012: https://developer.github.com/changes/2012-10-24-set-default-branch/

It's done via `PATCH /repos/:owner/:repo` : https://developer.github.com/v3/repos/#edit

**Comment by jonasfranz** [comment]
Currently you cannot update repository at all.

**Comment by jonasfranz** [comment]
Getting the DefaultBranch is support.

**Comment by sankethpb** [comment]
any updates on this? Is this already supported in Gitea 1.5.x and above?

**Comment by lunny** [comment]
@sankethpb nobody are working on this.

**Comment by davidsvantesson** [comment]
If wildcard protected branches (#2529) get implemented it is necessary to consider how this affect the API. 

I would suggest two API endpoints:
- **...{repo}/branches(/{branch})** corresponds to actual branches and only gives some limited information on **effective** branch protection (e.g. if branch is protected, number of approvals required, name of effective branch protection)
- **...{repo}/branch_protections(/{branch})** where branch is a configured branch protection (specific branch or wildcard). To edit a branch protection this endpoint should be used.
