### ISSUE TITLE
Migration from own gitlab not working

### ISSUE THREAD

**Issue by kimjohans** [go-gitea/gitea#29224]
### Description

gitea:
OS: Linux Debian 12, up-to-date
Installed as binary

Configuration added to app.ini:
```
[migration]
ALLOWED_DOMAINS = my-gitlab
BLOCKED_DOMAINS =
ALLOW_LOCALNETWORKS = true
SKIP_TLS_VERIFY = true
```

(restarted gitea service after each app.ini change)

- Tested also with IP, with empty ALLOWED_DOMAINS and with missing [migration] block.
- Tested without BLOCKED_DOMAINS
- With and without token (which is valid)
- With http and https

Always the message "migrate.permission_denied_blocked":
German "Du kannst von keinen nicht erlaubten Hosts importieren. Bitte fragen deinen Administrator, die Einstellungen ALLOWED_DOMAINS/ALLOW_LOCALNETWORKS/BLOCKED_DOMAINS zu überprüfen."

I also tried it with "git" migration (one of the other options in gitea), bit the result is the same.

![grafik](https://github.com/go-gitea/gitea/assets/43292439/7d0eecd6-23cf-48d2-a4a7-05e423583b98)

The log file is not very helpful in the case:

```
2024/02/17 17:49:25 .../context_response.go:68:HTML() [D] Template: repo/migrate/gitlab
2024/02/17 17:49:25 ...eb/routing/logger.go:102:func1() [I] router: completed POST /repo/migrate for 192.168.1.175:51000, 200 OK in 16.4ms @ repo/migrate.go:151(repo.MigratePost)
```

Of course i tried to clone my gitlab repo again (to ensure, it is working): yes, working like always and cloned the repository to my computer.

### Gitea Version

1.21.4 built with GNU Make 4.3, go1.21.5 : bindata, sqlite, sqlite_unlock_notify

### Operating System

Linux Debian 12

### How are you running Gitea?

Downloaded from gitea.io two hours ago

### Database

MySQL/MariaDB

**Comment by delvh** [comment]
https://docs.gitea.com/administration/config-cheat-sheet#migrations-migrations

**Comment by kimjohans** [comment]
I used that URL to add the migration block to my app.ini.

**Comment by lunny** [comment]
It's `[migrations]` not `[migration]`.

**Comment by kimjohans** [comment]
Many thanks to lunny !

You know the feeling, when you try to find the error the whole day ... then a collegue looks over your should, pointing to a typo and that is the solution ?! Hmpf !!

Why is that block not automatically (by default) written in the app.ini ?

Can this ticket pls. can be switched into "enhancement" ?
I think will not be the last idiot with that stupid mistake :)

**Comment by lunny** [comment]
Since there are hundreds of options, I don't think putting all options on the generated app.ini is a good idea. I think we can add a workaround label here and close it.

**Comment by delvh** [comment]
as per @lunny
