### ISSUE TITLE
There is no ability to get "Ready Time" for pull request via Open API

### ISSUE THREAD

**Issue by acherkashin** [go-gitea/gitea#29240]
### Feature Description

Hi,

Thank you for your work, guys!

I'm trying to build some charts to determine our bottlenecks in the code review process. 
I need to determine when pull request switched from "WIP" to "Ready to Review" state. 

I reviewed all available methods in swagger, however I didn't find how I can find that. I was looking for API to get the following (see SS) event when user changes title.

<img width="828" alt="Pasted_Image_18_02_2024__15_24" src="https://github.com/go-gitea/gitea/assets/9947582/8a021e13-8e61-4e8a-9aa4-fd3dc8e6476f">

It is how I did in Gitlab, in gitlab's merge requests I could get all its notes (system and users ones) and find a note with text "marked this merge request as ready".

**Comment by delvh** [comment]
[GET /repos/{owner}/{repo}/issues/{index}/timeline](https://gitea.com/api/swagger#/issue/issueGetCommentsAndTimeline)

**Comment by acherkashin** [comment]
@delvh It solves my problem, thank you 🙏
