### ISSUE TITLE
Do not rebuild your dev container now

### ISSUE THREAD

**Issue by yp05327** [go-gitea/gitea#29252]
### Description

As we have bump go version to 1.22. I tried to rebuild my dev container.
But the base image of go:1.xx-bullseye image uses the latest git(2.43.1) as default, which will cause a bug mentioned in #29155, after the rebuild I can't run Gitea in dev container any more.

A quick fix is add this in your config file.
``` text
"features": {
  "ghcr.io/devcontainers/features/git:1": {
    "version": "2.43.0"
  }
}
```

### Gitea Version

latest

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

dev

### Database

None

**Comment by wxiaoguang** [comment]
If it is still a problem, there could be a patch like the backport for #29157 : tolerate the git 2.43.1 GIT_FLUSH bug

**Comment by yp05327** [comment]
> If it is still a problem, there could be a patch like the backport for #29157 : tolerate the git 2.43.1 GIT_FLUSH bug

Updated the description. Manually set the git version in config files is ok.
