### ISSUE TITLE
skip ci for Pull Request

### ISSUE THREAD

**Issue by wienans** [go-gitea/gitea#29265]
### Feature Description

Similar to the already existing skip ci flag fo commits. Skipping CI for the complete pull Request. For example a doc pull request which does not need CI

**Comment by a1012112796** [comment]
you can do it by https://github.com/dorny/paths-filter

**Comment by silverwind** [comment]
`paths-filter` is great, yeah, but for unsophisticated repos, it might still be useful to accept the tag from the PR title.
