### ISSUE TITLE
JavaScript promise rejection: TypeError: Cannot read properties of undefined (reading 'facebook.json'). Open browser console to see more details.

### ISSUE THREAD

**Issue by xiaoxinpro** [go-gitea/gitea#29273]
### Description

Gitea upgraded from 1.20.5 to 1.21.5, and the Web frontend gives an error:

```
JavaScript promise rejection: TypeError: Cannot read properties of undefined (reading 'facebook.json'). Open browser console to see more details.
```

The problem persisted even after Chrome's cache was cleared.

browser console output:

```
VM32:8298 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'facebook.json')
    at getConfig (<anonymous>:8298:42)
    at ClickToLoad.init (<anonymous>:11099:37)
    at ClickToLoad.callInit (<anonymous>:3140:18)
    at <anonymous>:11401:33
    at Array.forEach (<anonymous>)
    at Object.init (<anonymous>:11399:26)
getConfig @ VM32:8298
init @ VM32:11099
callInit @ VM32:3140
(anonymous) @ VM32:11401
init @ VM32:11399
await in init (async)
apply @ VM32:11467
(anonymous) @ VM50:3
(anonymous) @ VM50:5
inject @ inject.js:114
(anonymous) @ inject.js:211
Show 2 more frames
Show less
```

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/11443745/a7522d6c-036c-422b-819f-f7974cf55b4a)

### Gitea Version

1.21.5

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

Windowns

### Browser Version

Chrome 121.0.6167.185

**Comment by wxiaoguang** [comment]
It is caused by your browser extension's bug.

If you don't like to see the message, you could add your customized CSS styles to hide such prompts (`.js-global-error { display: none; }`

**Comment by xiaoxinpro** [comment]
Closing the browser extension `DuckDuckGo` can resolve this issue

**Comment by wxiaoguang** [comment]
> Maybe we can somehow detect when a error is not coming from our scripts, and don't display errors from third-party scripts like extensions.

And maybe it's time to stop showing the JS errors to end users? Only show it in dev mode and for site admin?

**Comment by silverwind** [comment]
Can be reproduced with a Violentmonkey script:

```js
// ==UserScript==
// @name        Gitea error trigger
// @match       http://localhost:3000/*
// ==/UserScript==
(async () => {
  throw new Error("error from userscript");
})()
```

**Comment by silverwind** [comment]
So I checked it: It is possible in Firefox to detect extension scripts via `error.stack?.includes('moz-extension://')`, but that does not work in Chrome. So yes I think we should go with @wxiaoguang's suggestion.
