### ISSUE TITLE
gitea.com: 500 error when reset password

### ISSUE THREAD

**Issue by Jengro777** [go-gitea/gitea#29278]
### Description

![image](https://github.com/go-gitea/gitea/assets/35259040/ec8d85bc-0e84-4d34-91e8-56ab1f7dd9f3)

![image](https://github.com/go-gitea/gitea/assets/35259040/978e1d7c-0dd0-4136-8790-ae5416c4cf0d)

![image](https://github.com/go-gitea/gitea/assets/35259040/26471ff9-e109-4e3e-a862-0accf090519e)

### Gitea Version

gitea.com

**Comment by yp05327** [comment]
@lunny

**Comment by henry99a** [comment]
same to me

**Comment by wolfogre** [comment]
Confirmed, I can find the panic log of [gitea.com](http://gitea.com/) and can reproduce it locally. I'm trying to figure it out.
