### ISSUE TITLE
PGSQL auth fails during install

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#2928]
- Gitea version (or commit ref):  1.2.3
- Git version:  2.15.0
- Operating system: FreeBSD 11.1
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description

When configuring the PostgreSQL database I see the following error:

```Database setting is invalid: pq: unknown authentication response: 10``` 

The same error is reported in the logs when using unix socket types instead of http.

The issue is I am using SCRAM-SHA-256 authentication for the gitea user, the upstream pq library does not support this from what I can tell.

Is it possible to use a library which does support this?

**Comment by lafriks** [comment]
Depends on used library lib/pq#608

**Comment by ghost** [comment]
With pq not being updated are there plans to use another library for this functionality?

**Comment by ghost** [comment]
Any updates here?

**Comment by lunny** [comment]
@evitalis do you know any other driver fix this issue?

**Comment by lunny** [comment]
maybe we could try this one https://github.com/jackc/pgx

**Comment by ghost** [comment]
I am not familiar with Go enough to suggest an alternative library. But given the inactivity of the current one it may be worth looking into another to keep up with PostgreSQL features and security improvements.

**Comment by jsan4christ** [comment]
Have the same problem, any leads?
Database setting is invalid: pq: SSL is not enabled on the server

**Comment by techknowlogick** [comment]
Please test if #6640 resolves your issue.
