### ISSUE TITLE
Create a commit status API not working

### ISSUE THREAD

**Issue by Madmorgan007** [go-gitea/gitea#2929]
- Gitea version (or commit ref): 1.2.3 Windows 4.0 AMD 64
- Git version: 2.13.2.Windows.1
- Operating system: Windows 10 1709
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [X ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [X ] Yes 
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

Hi,

I have been trying to update a commit has to highlight that a build has passed or failed using the API documented here.

[https://try.gitea.io/api/v1/swagger#/repository/repoCreateStatus](https://try.gitea.io/api/v1/swagger#/repository/repoCreateStatus)

I have giving a Json string to my server locally and I keep getting a 404

```
[Macaron] 2017-11-17 09:33:36: Started POST /api/v1/repos/madmorgan007/test2/statuese/b10209b06dd49520cc3264be3878928d94a9c0c8?token=41cb2d57e2d7e94aac10f51317cc1b3cd2b10d00 for 127.0.0.1

[Macaron] 2017-11-17 09:33:36: Completed /api/v1/repos/madmorgan007/test2/statuese/b10209b06dd49520cc3264be3878928d94a9c0c8?token=41cb2d57e2d7e94aac10f51317cc1b3cd2b10d00 404 Not Found in 41.4675ms
```
I also tried it on the API site that lets you run the command agents http://try.gitea.io and that failed as well see images

## Screenshots

![image](https://user-images.githubusercontent.com/19917093/32941359-77a30850-cb7d-11e7-98b8-e4b2b929ea29.png)

![image](https://user-images.githubusercontent.com/19917093/32941377-8778bacc-cb7d-11e7-8964-103d48fbee47.png)

**Comment by lunny** [comment]
The API should be `/api/v1/repos/madmorgan007/test2/statuses/b10209b06dd49520cc3264be3878928d94a9c0c8?token=41cb2d57e2d7e94aac10f51317cc1b3cd2b10d00`
not
`/api/v1/repos/madmorgan007/test2/statuese/b10209b06dd49520cc3264be3878928d94a9c0c8?token=41cb2d57e2d7e94aac10f51317cc1b3cd2b10d00 404 Not Found in 41.4675ms`

**Comment by Madmorgan007** [comment]
them two lines are the same I got them from CMD window of Gitea

**Comment by Madmorgan007** [comment]
Final worked out the issue I was using latest release but if i use master the api has what i need.
