### ISSUE TITLE
Return plugin name in error message if act_runner daemon can not find it.

### ISSUE THREAD

**Issue by georgewei** [go-gitea/gitea#29290]
### Feature Description

I try to integrate Gitea and SonarQube by following the article https://mp.weixin.qq.com/s/1h9wki9F_AV_-V8IQ3kOgw, but the action fails with the message "Error response from daemon: plugin not found".  Wish the plugin name can be returned in this message, so I can try to manually install the plugin. 

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/28130/04406212-634b-4211-b931-ca1b15e6d33f)

**Comment by georgewei** [comment]
This problem is also reported in Gitea forum: https://forum.gitea.com/t/gitea-actions-sonarqube/8599

**Comment by silverwind** [comment]
First we need to find out where the error came from, https://gitea.com/gitea/act_runner or https://gitea.com/gitea/act would have been my bet but a quick search in those sources does not reveal anything for string `plugin not found`.

**Comment by georgewei** [comment]
> First we need to find out where the error came from, https://gitea.com/gitea/act_runner or https://gitea.com/gitea/act would have been my bets but a quick search in those sources does not reveal anything for string `plugin not found`.

This error message is returned by Docker: act_runner calls Docker to create a network, but it fails. Please check the parameters of Docker command.

I'm using Windows Server 2019 and I installed docker 17.10.0-ee-preview-3 from Microsoft repository, for Docker EE Preview is the only one which can use linux containers on Windows Server. The installation script is as following:

```
Install-WindowsFeature -Name Hyper-V
Install-WindowsFeature -Name containers
Restart-computer
Install-Module -Name DockerMsftProvider -Repository PSGallery -Force
Install-Package Docker -ProviderName DockerProvider -RequiredVersion preview -force
// Switch Docker to using Linux containers
[Environment]::SetEnvironmentVariable("LCOW_SUPPORTED", "1", "Machine")
Restart-Service Docker
```
Installed Docker version infomation is as following:
![image](https://github.com/go-gitea/gitea/assets/28130/8d11be01-29f5-461e-affe-dcca4ce44a29)

After that, I got the error "Error response from daemon: plugin not found" when I run the action manually.

I tried to manually create Docker network, one failed and one succeeded, as following:
![image](https://github.com/go-gitea/gitea/assets/28130/996c1d52-2540-46b2-aae8-2b5dd938eb3b)

**Comment by silverwind** [comment]
Sounds like a issue with your docker daemon. If you find out what's missing, we can add it do the docs.

**Comment by wxiaoguang** [comment]
![image](https://github.com/go-gitea/gitea/assets/2114189/9ce538fb-d01c-4f49-8066-7b3d6968d89a)


> docker 17

TBH, it seems that it is too old to run Gitea related features.  At least, you should make sure your docker version >= 20

**Comment by georgewei** [comment]
> Sounds like a issue with your docker daemon. If you find out what plugin is missing, we can add it do the docs.

I mean you'd better check the command to call Docker to create network. As my test result, command "docker create network --driver transparent <network name>" works fine.

**Comment by georgewei** [comment]
> ![image](https://private-user-images.githubusercontent.com/2114189/306835259-9ce538fb-d01c-4f49-8066-7b3d6968d89a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1NzAzNjgsIm5iZiI6MTcwODU3MDA2OCwicGF0aCI6Ii8yMTE0MTg5LzMwNjgzNTI1OS05Y2U1MzhmYi1kMDFjLTRmNDktODA2Ni03YjNkNjk2OGQ4OWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjJUMDI0NzQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWE2ZmIwODUzOWU4MzIxZDI0YWE4ZTU2Yzc5NDE1Yjk1ZTNiY2FjNmZlNTkxNDE2YWEyNmU5NDg0ODY2NTE5MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.0_a9WLL5jjnWh7BzZC80Tybzq4tL6noFtj1iR3QkqtM)
> 
> > docker 17
> 
> TBH, it seems that it is too old to run Gitea related features. At least, you should make sure your docker version >= 20

As I know, the official community edition does not support use Linux containers on Windows Server, so I have to install the enterprise edidtion Preview from Microsoft.

**Comment by wxiaoguang** [comment]
> As I know, the official community edition does not support use Linux containers on Windows Server, so I have to install the enterprise edidtion Preview from Microsoft.

But old versions just do not work. And actually Docker < 20.10.6 never really works in modern days anymore:

*  #18050 

See: https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.14.0 & https://about.gitlab.com/blog/2021/08/26/its-time-to-upgrade-docker-engine/

**Comment by silverwind** [comment]
We do [not document](https://docs.gitea.com/usage/actions/act-runner#requirements) a minimum version for docker, but clearly we should. Likely v23 as of today to stay within the range of supported versions.

**Comment by silverwind** [comment]
Not an issue in this repo, please move it to https://gitea.com/gitea/act_runner
