### ISSUE TITLE
act_runner in windows with docker and hyperv - bridge network plugin error

### ISSUE THREAD

**Issue by dvgoyeneche** [go-gitea/gitea#29315]
### Description

When executing a workflow in a windows runner (docker desktop using windows containers and hyperv)
could not find plugin bridge in v1 plugin registry: plugin not found

### Gitea Version

v1.21.5

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

On premise

cc

### Database

None

**Comment by silverwind** [comment]
https://github.com/go-gitea/gitea/issues/29290 is about the same error.

Please show `docker --version`.

**Comment by dvgoyeneche** [comment]
![image](https://github.com/go-gitea/gitea/assets/49909762/3a9d7445-fada-496c-a8e4-142d0d40330e)

**Comment by silverwind** [comment]
Do the answers in https://stackoverflow.com/questions/49603170/docker-could-not-find-plugin-bridge-in-v1-plugin-registry-plugin-not-found help?

**Comment by dvgoyeneche** [comment]
I tried it but not working

**Comment by dvgoyeneche** [comment]
I think act_runner needs a bridge docker network to run the image, but in windows it is not possible

**Comment by silverwind** [comment]
Hmm, maybe it can be made to use this nat driver which as per these answers is about equivalent.

**Comment by dvgoyeneche** [comment]
But the error "could not find plugin bridge in v1 plugin registry: plugin not found"  is specifying that needs the plugin bridge

**Comment by silverwind** [comment]
I'm not that familiar with act_runner, but it does seem to expose an option for this:

https://gitea.com/gitea/act_runner/src/branch/main/internal/pkg/config/config.go#L137-L148

**Comment by dvgoyeneche** [comment]
ok could you move to act_runner repo?

**Comment by silverwind** [comment]
No, it needs your feedback etc. Please open it there: https://gitea.com/gitea/act_runner
