### ISSUE TITLE
Gitea 1.3.0 with SSH server enabled crashes with SIGSEGV when pushing to SSH

### ISSUE THREAD

**Issue by lapin-b** [go-gitea/gitea#2933]
- Gitea version (or commit ref): 1.3.0
- Git version: 2.15.0
- Operating system:
  - Client: ArchLinux
  - Server: Debian Stretch
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist: [there it is](https://gist.github.com/lapin-b/d224ce3d375841f0df3f2a5ec48f76d7)

## Description
When I want to push with `git push` to the included SSH server, Gitea crashes with a SIGSEGV. This crash is easily reproductible.

### How to reproduce
1. Download and install a copy of Gitea 1.3.0 to upgrade an older version
2. Start it with `gitea web` with embeded SSH server enabled
3. `git push` commits to remote. It should crash with a SIGSEGV

## Screenshots
*Not revelant*

**Comment by pztrn** [comment]
Looks like https://github.com/go-gitea/gitea/issues/2885

**Comment by lunny** [comment]
#2923 need to be back port to v1.3 @lafriks

**Comment by lafriks** [comment]
@lunny yes, I will do it
