### ISSUE TITLE
Find alternative(s) to Bountysource

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#29331]
As [Bountysource is dead](https://github.com/bountysource/core/issues/1586), we should find alternative(s).

Come up in #29330

## suggestions:
- [ ] [algora.io](https://console.algora.io/org/go-gitea/bounties)
- [ ] https://polar.sh/
- [ ] ...

---
_please comment if you know a good one so we can add it to the suggestions_

**Comment by denyskon** [comment]
@techknowlogick Did we now decide to use algora.io? Can this be closed?

**Comment by techknowlogick** [comment]
@denyskon a good way to evaluate it's to run some live tests to see the full experience. I also think that we don't necessarily need to be limited to one.

**Comment by lunny** [comment]
Sicne [algora.io](https://console.algora.io/org/go-gitea/bounties) has been used. I think we can close this one.
