### ISSUE TITLE
Edit file times out for large files after recent cat-file bugfix

### ISSUE THREAD

**Issue by brechtvl** [go-gitea/gitea#29346]
### Description

To reproduce:
* Create new new repository with Apache 2.0 license
* Click LICENSE file and Edit File
* Operation times out

Happens for any larger text file, works fine for a small file.

I bisected the cause down to #29297.

### Gitea Version

1.21.6

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

Running locally on Linux with own build, but also happens on try.gitea.io.

### Database

None

**Comment by brechtvl** [comment]
CC @KN4CK3R as the author of this pull request.

I imagine this could affect more than just editing files.

**Comment by KN4CK3R** [comment]
Nice... talked about that problem in the note here https://github.com/go-gitea/gitea/pull/29297#discussion_r1497848315 Calling `Close` multiple times is undefined behaviour.

**Comment by KN4CK3R** [comment]
Fixed in #29354
