### ISSUE TITLE
Inserts spaces when pasting text in the browser

### ISSUE THREAD

**Issue by juanico10** [go-gitea/gitea#29345]
### Description

When I paste text into the browser, the text is entered line by line with a tab stop.

### Screenshots

![example](https://github.com/go-gitea/gitea/assets/95724863/c411427d-6612-4fd6-93ad-61fb2303a59c)

Example Gitea demo site:
![example_site_demo](https://github.com/go-gitea/gitea/assets/95724863/24995ae6-b495-4e49-a17e-e4cc928dac28)

### Gitea Version

Versión: 1.21.0

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

KDE neon 5.27

### Browser Version

Firefox 123.0 (64-bit)

**Comment by silverwind** [comment]
Can you reproduce when pasting into the editor on right on https://microsoft.github.io/monaco-editor/playground.html?source=v0.46.0?

**Comment by JuanRodenas** [comment]
Hello, here is the example:
![example_monaco](https://github.com/go-gitea/gitea/assets/95724863/95f749bd-1785-4d61-8a27-5e920cc5c656)

**Comment by JuanRodenas** [comment]
Oh my god, I have tried with chromium and the error does not appear!
![example_monaco](https://github.com/go-gitea/gitea/assets/95724863/2e87764c-2a48-49e1-913f-0a3d0bbd5eb4)

Don't close the problem, I'm going to check what it could be and post the resolution here in case it happens to someone else.

**Comment by silverwind** [comment]
It certainly works in my Firefox v124, so I wonder if it's an extension or other browser setting issue.

**Comment by JuanRodenas** [comment]
I have opened firefox in troubleshooting mode and it keeps popping up. I will open a case where you have indicated me and they can solve the problem. Thank you very much
