### ISSUE TITLE
Time tracking start/stop link to port not reverse proxy address

### ISSUE THREAD

**Issue by b4d** [go-gitea/gitea#2934]
- Gitea version (or commit ref):4683e54
- Git version: 2.11.0
- Operating system: Debian 9.2
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

I am using gitea via Apache reverse proxy, that shoots port 3000 to my gitea.domain.com.

The problem is that time tracknig plugin "start" and "stop" buttons link to domain.com:3000 instead of gitea.domain.com.

Time tracking works ok, but when I click start or stop, it tries to resolve domain.com:3000 and the request fails miserably.

Same thing happens if I try to add time manually "Add" button in the popup adds the time, but redirects me to domain.com:3000 again instead of gitea.domain.com

Probably the time tracker should consider the settings and act accordingly.

**Comment by jonasfranz** [comment]
Could you please add your config.ini?

**Comment by b4d** [comment]
I have app.ini :)

```
APP_NAME = git.site.org
RUN_USER = git
RUN_MODE = prod

[database]
DB_TYPE  = mysql
HOST     = localhost:3306
NAME     = prod_gitea
USER     = prod_gitea
PASSWD   = 123456
SSL_MODE = disable
PATH     = data/gitea.db

[repository]
ROOT = /home/git/gitea-repositories

[server]
SSH_DOMAIN   = site.org
HTTP_PORT    = 3000
ROOT_URL     = https://site.org:3000/
DISABLE_SSH  = false
SSH_PORT     = 22
OFFLINE_MODE = false

[mailer]
ENABLED = false

[service]
REGISTER_EMAIL_CONFIRM = false
ENABLE_NOTIFY_MAIL     = false
DISABLE_REGISTRATION   = true
ENABLE_CAPTCHA         = false
REQUIRE_SIGNIN_VIEW    = false

[picture]
DISABLE_GRAVATAR        = false
ENABLE_FEDERATED_AVATAR = true

[session]
PROVIDER = file

[log]
MODE      = file
LEVEL     = Info
ROOT_PATH = /var/log/gitea/

[security]
INSTALL_LOCK   = true
SECRET_KEY     = 1234
INTERNAL_TOKEN = 1234
```

Now that I am looking, could this line be the problem:
`ROOT_URL     = https://site.org:3000/`

maybe it should point to
`ROOT_URL     = https://localhost:3000/`

**Comment by b4d** [comment]
Okay, I have changed that to:
`ROOT_URL     = https://git.site.org`

and this tracking problem is resolved.

I wonder if I broke something else along the way. Otherwise consider this one closed :)

**Comment by JonasFranzDEV** [comment]
The `ROOT_URL` should point to the final destination of your Gitea instance. (in your case: `gitea.domain.com`)

**Comment by b4d** [comment]
Cool, thanks for the node in the right direction, sometimes that is all we need :)
