### ISSUE TITLE
Emote Icon 📦 Causes 500 Internal Server Error on Migration or Updating Repo Description

### ISSUE THREAD

**Issue by oDinZu** [go-gitea/gitea#29350]
### Description

As an example, I clone or migrate a repository from GitHub https://github.com/cpm-cmake/CPM.cmake

Then I update the settings as intended and copied over the description with the icon and produce a 500 Internal Server Error

Maybe it has something to do with my nginx security configuration or maybe something to do with the unicode char? This error created a bunch of headaches/confusion for me  because it was intermittent and couldn't determine the reason until today. I tested the migration with/without the emote icon.

Hopefully, this bug report will save you time on this tiny nuance that is difficult to pinpoint. It worked with the icon on testing it via Gitea's demo site.

### Gitea Version

Version: 1.16.6

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

SEE SCREENSHOT

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/18726788/c8d341eb-6f57-4123-9e45-4558ceb6d4dd)

### Git Version

2.25.1

### Operating System

Ubuntu

### How are you running Gitea?

Compiled from Source

### Database

MySQL/MariaDB

**Comment by techknowlogick** [comment]
Hi, thank you for your report. Two things 1. could you use the latest stable version of Gitea (1.21.6 at the time of writing), and 2. mysql/maria even though they say you are using utf8, it doesn't include the emoji set so you'll need to adjust your DB to use utf8mb4. There is a tool built into Gitea that can help you: https://docs.gitea.com/next/administration/command-line#doctor-convert

**Comment by oDinZu** [comment]
Thank You @techknowlogick
