### ISSUE TITLE
GetReleaseCountByRepoID causes Gitea Actions to not display a single thing.

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#29364]
### Description

I just found this bug in my instance where Actions seems unresponsive and the UI is outright borked.

Any job that was run when I try to open them shows an empty screen, browser console log showed an error and then I went to the server logs to investigate and was able to extract the pertinent logs.

No idea what is causing this. Since it seems to be a database error, maybe because I'm using Neon (https://neon.tech)?

I'm not able to reproduce on try.gitea.com.

### Gitea Version

1.21.6

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/lmorais-dev/a8c36044a1c399a99353f0f1a99ff32d

### Screenshots

![Screenshot from 2024-02-24 02-47-11](https://github.com/go-gitea/gitea/assets/154244251/d58b363f-ded8-40f9-a78f-3372561e5c42)
![Screenshot from 2024-02-24 02-47-22](https://github.com/go-gitea/gitea/assets/154244251/d615b32e-a5c1-4727-b1f6-e9e76286ee89)

### Git Version

2.34.1

### Operating System

Ubuntu 22.04.3 LTS

### How are you running Gitea?

I'm running using a docker-compose deployment on AWS.

### Database

PostgreSQL

**Comment by wxiaoguang** [comment]
> No idea what is causing this. Since it seems to be a database error, maybe because I'm using Neon (https://neon.tech)?

Yup, it seems to be so .... could you try an official PostgreSQL?

**Comment by lmorais-dev** [comment]
> > No idea what is causing this. Since it seems to be a database error, maybe because I'm using Neon (https://neon.tech)?
> 
> Yup, it seems to be so .... could you try an official PostgreSQL?

Yeah, I can give it a try is there a migration guide?

**Comment by lmorais-dev** [comment]
Using a traditional PostgreSQL deployment fixed the issue. Forgot to mention that not only Actions was unresponsive, the entire application and web hooks were kinda broken. It is fixed now and I was able to migrate all data without further problems.
