### ISSUE TITLE
Add a link to user's commits in contributors graph

### ISSUE THREAD

**Issue by sahinakkaya** [go-gitea/gitea#29365]
### Feature Description

In Github's contributors page, one can directly filter user's commits on specified date range by clicking "n commits". It should be possible to do it here too. 

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/32161460/782b8e90-6a9c-4fe8-8b24-29212ceef5e6)

If anyone is interested here is the link filtering the commits for:
- user named `sahin`
- repository named `my-repo`
- default branch named `master`
- after date `2021-12-11`
- before date `2022-01-01`
- authored by `some-address@some-domain.tld`

http://localhost:3000/sahin/my-repo/commits/branch/master/search?q=after%3A2021-12-11%2C+before%3A2022-01-01%2C+author%3Asome-address%40some-domain.tld

This link can be obtained by entering the following search term in the repository's commits page:

`after:2021-12-11, before:2022-01-01, author:some-address@some-domain.tld`

**Comment by sahinakkaya** [comment]
It might be a good first issue. If someone wants to implement it, please let me know. Otherwise I will try to fix this in this week.

**Comment by sahinakkaya** [comment]
@silverwind can you label this with good-first-issue if you think same so?

**Comment by silverwind** [comment]
Interesting, didn't know we support such queries yet.

**Comment by sahinakkaya** [comment]
I am starting working on this. A PR should be ready in couple of hours.
