### ISSUE TITLE
Multiple-Line commit message

### ISSUE THREAD

**Issue by sinnlosername** [go-gitea/gitea#2939]
- Gitea version (or commit ref): 1.3.0+rc1
- Git version: 2.7.4
- Operating system: Ubuntu 16.04
- Database (use `[x]`):
  - [x] MySQL
- Can you reproduce the bug at https://try.gitea.io:
  - [x] No: Didn't find a matching commit

## Description
Only the first line of a commit message is shown.

## Screenshots
How it looks in gitea:
Commit history -> https://i.imgur.com/oVDhmAP.png
Commit view -> https://i.imgur.com/lXAfOxV.png

The whole commit message (from a discord webhook):
https://i.imgur.com/9BeVaIS.png

**Comment by makarchuk** [comment]
What is expected behaviour here?   
It would be really strange to show all lines of commit message, it can be really long

**Comment by lafriks** [comment]
I think full message should be shown only when viewing commit diff page

**Comment by lafriks** [comment]
And also collapsed by default and expandable when clicked on

**Comment by sinnlosername** [comment]
You could also collaps it in the commit list, like github does.

**Comment by davydov-vyacheslav** [comment]
@lafriks , maybe another way is to make tooltip with multiline information over singlelined current behavior. At least, this way affects UI changes less

**Comment by lafriks** [comment]
@davydov-vyacheslav it's also an option. Only disadvantage of that is you can not copy text from it if you need it

**Comment by makarchuk** [comment]
I implemented @davydov-vyacheslav's idea, you're welcome to take a look and criticize me if I did anything wrong.

**Comment by sinnlosername** [comment]
I think something similar to github would be a good idea, because as @lafriks said, it's not possible to copy something. Also, it's not that good to read.

**Comment by sondr3** [comment]
My pull request for this at #2980 is now complete (I hope), if anyone would like to test it I'd greatly appreciate it.

**Comment by lunny** [comment]
resolved by #2980
