### ISSUE TITLE
Session time out resulted in the admin system status frame become a login page.

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#29391]
### Description

Staying in the admin dashboard for enough time until login session timeout. Then the system status frame will become a login page. It was caused by #29163.

### Gitea Version

main

### Can you reproduce the bug on the Gitea demo site?

I think yes, but I haven't tested it.

### Screenshots

<img width="1334" alt="image" src="https://github.com/go-gitea/gitea/assets/81045/b3b8089c-208b-4e4f-8b17-f410d5d0e9ed">

### How are you running Gitea?

localhost

### Database

MySQL/MariaDB

**Comment by yardenshoham** [comment]
I was under the impression the csrf token is valid for a very very long time. I will fix this. Is there a way to reproduce it or make the token expire after one minute?

The fix is to just add an `HX-Redirect` header on the response if the token expired

**Comment by lunny** [comment]
You can open two pages, one page stay in the admin panel, another one you can exit the system manually. I think you can find it immediately.

**Comment by yardenshoham** [comment]
https://github.com/go-gitea/gitea/pull/29405
