### ISSUE TITLE
markdown: wrong hostname in commit url with empty ROOT_URL

### ISSUE THREAD

**Issue by milahu** [go-gitea/gitea#29404]
### Description

when i leave ROOT_URL empty
then gitea uses `http://localhost` as hostname in commit urls
but gitea should produce urls without hostname

ping @KN4CK3R via #28909

repro https://try.gitea.io/milahu/test-gitea-markdown-wrong-commit-url

part of #19345

### Gitea Version

1.21.6

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

gitea runs in a container on localhost, accessed from localhost
so gitea thinks that its hostname is "localhost", but that is wrong

### Database

None

**Comment by lunny** [comment]
`ROOT_URL` is almost a MUST set option especially if you run gitea on the container.

**Comment by milahu** [comment]
> `ROOT_URL` is almost a MUST set option

that is the problem...
the same gitea instance should work on `localhost` and `somewhere.com`
and the `localhost` version should have no links to `somewhere.com`

this already works with file links, only commit links are broken

**Comment by KN4CK3R** [comment]
Gitea is currently not build to be fully domain independend and may never be. Some parts (like the commit url) can be transformed but that's not possible everywhere. Here is an issue with more information: #19345
