### ISSUE TITLE
Uncaught TypeError: e.getModifierState is not a function

### ISSUE THREAD

**Issue by yp05327** [go-gitea/gitea#29414]
### Description

![image](https://github.com/go-gitea/gitea/assets/18380374/827cbd39-a988-4188-8ec3-0b2dc0aca64a)
I think this is not caused by browser extensions, as I have closed all of them that I could.

Reproduce:
1. Open a repo, and click add new file.
2. At the input box of filename, select `LICENSE` from the list:
![image](https://github.com/go-gitea/gitea/assets/18380374/709e3266-bc96-4ebb-9306-49b1cd54f5f7)

### Gitea Version

latest

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

build

### Database

None

**Comment by lng2020** [comment]
I think it's https://github.com/microsoft/monaco-editor/issues/4213

**Comment by yp05327** [comment]
I think https://github.com/microsoft/monaco-editor/issues/4325 is better and they are trying to fix it.

**Comment by Attacktive** [comment]
I downgraded to `0.44.0` and am happy with it.

**Comment by silverwind** [comment]
Bug seems to not affect Firefox at least.
