### ISSUE TITLE
Gravatar display error in profile mode

### ISSUE THREAD

**Issue by remyslab** [go-gitea/gitea#2941]
- Gitea version (or commit ref): 7e6c198
- Git version:
- Operating system: Debian Jessie
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ x ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ x ] No
  - [ ] Not relevant
- Log gist:

## Description
On profile mode, big gravatar display doesn't work, I have an error : Sorry, the parameters you provided were not valid 
But little displays work on all the website. 
Gitea runs in a docker container with : 
`docker run -d --name=gitea -p 50:22 -p 88:3000 -v "$PWD"/gitea/:/data gitea/gitea:latest`

## Screenshots
![screenshot](https://user-images.githubusercontent.com/26518119/33016831-43115c02-cdf0-11e7-9e44-45813aefb640.png)

**Comment by lafriks** [comment]
What url does have for image?

**Comment by remyslab** [comment]
For the big display (doesn't work) : https://secure.gravatar.com/avatar/44e2d25dbaa9cb03e22ebf2be13ea88c?d=identicon?s=290

Little display (works) : https://secure.gravatar.com/avatar/44e2d25dbaa9cb03e22ebf2be13ea88c?d=identicon

**Comment by lafriks** [comment]
Looks like to be related to our gravatar integration

**Comment by ethantkoenig** [comment]
This has been fixed by #3069.
