### ISSUE TITLE
Can't create repository behind nginx reverse proxy

### ISSUE THREAD

**Issue by Phoenix616** [go-gitea/gitea#2942]
- Gitea version (or commit ref): 1.1.0+771-g7e6c198
- Git version: 1.9.1
- Operating system: Debian 7.11
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist: Nothing special in the logs. Just shows that it returned 200: https://gist.github.com/7d6de273198fd5f1930710fc9edb69ed
- Nginx access log (nothing in the error log): `1.2.3.4 - - [20/Nov/2017:15:52:49 +0100] "GET /repo/create HTTP/1.1" 499 0 "-" "BrowserUserAgent"`

## Description

I am trying to setup Gitea behind an nginx (1.12.1) reverse proxy to enable ssl. (via proxy_pass) Everything seems to work fine besides the fact that the repository creation page (under /repo/create) does not load and eventually times out. (according to the nginx log) Accessing the page via the direct port and creating a repo works fine.

I already tried setting proxy_connect_timeout, proxy_send_timeout, proxy_read_timeout and send_timeout to higher values (150, 600, 60000) but none of them do the trick. The page works without issues when directly connecting to the port and the gitea log/console looks the same as it does when using the port.

app.ini repository:

```
DOMAIN           = code.website.tld
HTTP_ADDR        = sub.website.tld
HTTP_PORT        = 3000
ROOT_URL         = https://code.website.tld/
```

**Comment by davydov-vyacheslav** [comment]
as for me, I have 

DOMAIN                 = localhost
ROOT_URL               = https://[myOuterHost]:[myOuterIp]/
HTTP_ADDR              = 0.0.0.0
HTTP_PORT              = [localGiteaIp]
LOCAL_ROOT_URL         = %(PROTOCOL)s://%(DOMAIN)s:%(HTTP_PORT)s/

and in apache ( I hope It doesn't have any global differences ):
ProxyPass        "/" "http://127.0.0.1:[localGiteaIp]/"
ProxyPassReverse "/" "http://127.0.0.1:[localGiteaIp]/"

and in router configuration just remap [localGiteaIp] of specific machine to [myOuterIp]


Hope, that helps

**Comment by mashov** [comment]
It's work for me:  
app.ini:
DOMAIN           = gitea.domain.com
HTTP_ADDR        = 0.0.0.0
HTTP_PORT        = 3000
ROOT_URL         = https://gitea.domain.com

nginx:
location / {
                proxy_pass http://localhost:3000;
                proxy_set_header Host             $host;
                proxy_set_header X-Real-IP        $remote_addr;
                proxy_set_header X-Forwarded-For  $proxy_add_x_forwarded_for;
                #max_body_size will allow you to upload a large git repository
                client_max_body_size 100M;
        }
;)

**Comment by Phoenix616** [comment]
Yeah I tried it with just these settings (I had some extra timeout stuff and headers in there) and still not difference. I suspect it might be caused by some kind of CSRF (cross site request forgery) protection, not sure if gitea has that. (I had to change something in [jenkins](https://wiki.jenkins.io/display/JENKINS/CSRF+Protection) for it to work behind an nginx proxy, that's where the idea comes from)

**Comment by Phoenix616** [comment]
I'm not sure what exactly fixed this but after a recent update it started working. (I don't think anything in the setup changed at all so I guess it was a change in gitea?) Feel free to close this if nobody else has this issue.
