### ISSUE TITLE
Wrong UI for lastest commit info when commit message is too long

### ISSUE THREAD

**Issue by yp05327** [go-gitea/gitea#29438]
### Description

local:
![image](https://github.com/go-gitea/gitea/assets/18380374/3b30a1d6-71b7-4b0c-990d-b4f88af6423e)

try.gitea.io:
https://try.gitea.io/yp05327/testrepo/src/branch/testcompare/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

### Gitea Version

latest

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

build

### Database

None

**Comment by wxiaoguang** [comment]
Regression of #24420 (using "display: flex")

When using "flex", the x-axis is not limited by default, just like #28489 , there could be more similar problems.

Maybe it should be documented somewhere.
