### ISSUE TITLE
Commit graph blurry on HiDPI screens

### ISSUE THREAD

**Issue by michaelkuhn** [go-gitea/gitea#2943]
- Gitea version (or commit ref): 7e6c198
- Operating system: Linux/Chrome
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes: https://try.gitea.io/frankenstein/cpython/graph

## Description

On HiDPI screens, the commit graph is blurry. I have opened a PR for gitgraph.js to fix this: https://github.com/bluef/gitgraph.js/pull/3
This should also be pulled into Gitea to fix the problem.

## Screenshots

![blurry-canvas](https://user-images.githubusercontent.com/4062614/33033218-fb268dde-ce23-11e7-8405-72f1788068f6.png)

**Comment by lunny** [comment]
closed by #2957
