### ISSUE TITLE
repo search fails when REPO_INDEXER_PATH is unset: No source code matching your search term found

### ISSUE THREAD

**Issue by milahu** [go-gitea/gitea#29431]
### Description

to enable the repo indexer
it is not enough to set `REPO_INDEXER_ENABLED`

```
[indexer]
REPO_INDEXER_ENABLED = true
```

additionally, i have to set `REPO_INDEXER_PATH`

```
[indexer]
REPO_INDEXER_ENABLED = true
REPO_INDEXER_PATH = data/indexers/repos.bleve
```

otherwise the repo search always returns

> No source code matching your search term found.

in contrast, the issue indexer works without setting `ISSUE_INDEXER_PATH`

the [config cheatsheet](https://docs.gitea.com/next/administration/config-cheat-sheet#indexer-indexer) has wrong default values
for `ISSUE_INDEXER_PATH` and `REPO_INDEXER_PATH`

the actual default values are

```
ISSUE_INDEXER_PATH = data/indexers/issues.bleve
REPO_INDEXER_PATH = data/indexers/repos.bleve
```

maybe the repo search is trying to read from `indexers/repos.bleve`
and fails because the index is at `data/indexers/repos.bleve`

continue https://github.com/go-gitea/gitea/issues/25857#issuecomment-1633419147

### Gitea Version

1.21.6

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

on localhost in a container

### Database

None

**Comment by yp05327** [comment]
The logic is here:
![image](https://github.com/go-gitea/gitea/assets/18380374/45feec11-0f40-442d-8fd0-701bfa0f7b82)
First, `APP_DATA_PATH` will be added before the default value `indexers/repos.bleve`
And the default value of `APP_DATA_PATH` is `AppWorkPath/data`.
So the default value of `REPO_INDEXER_PATH` is `AppWorkPath/data/indexers/repos.bleve`
Then, it is not related when you use the default value, but when `APP_DATA_PATH/indexers/repos.bleve` is not an absolute path, `AppWorkPath` will be added.

So I can't see the relationship between `No source code matching your search term found.` and `REPO_INDEXER_PATH`.
Did you change `APP_DATA_PATH` but the real data path is `data`?

ps: It seems that the description in [config cheatsheet](https://docs.gitea.com/next/administration/config-cheat-sheet#indexer-indexer) is not correct.
