### ISSUE TITLE
Ability to Disable PGP/GPG Keys

### ISSUE THREAD

**Issue by inferenceus** [go-gitea/gitea#29454]
### Feature Description

I have migrated from PGP keys to SSH keys and now enforce that only SSH keys are used on my server. I saw pull request #29447 is related to disabling SSH keys (the opposite of what I'm asking for here), and issue #20549 includes GPG keys but no SSH keys.

Is it possible to do the same as what's happening in PR #29447 for PGP/GPG keys?

**Comment by delvh** [comment]
Probably.
TBH, I half expected that exact request to pop up when reviewing the PR  :laughing:

**Comment by inferenceus** [comment]
> Probably. TBH, I half expected that exact request to pop up when reviewing the PR 😆

PGP gets a lot of love despite its shortcomings (that's off-topic and an entirely different issue), but SSH seems to be scarcely-used. It would indeed be nice if this was implemented so I can just disable legacy PGP keys.

I already made an attempt at removing PGP from the UI at least, but I wasn't familiar enough with the Gitea codebase and it was too high-risk, so I just dropped it and hoped it would be possible. Now, here I am after seeing that the same thing is wanted, but for SSH keys (unfortunately the *opposite* of what I want)...

**Comment by inferenceus** [comment]
You guys are working on this?

**Legendary.**

**Comment by lunny** [comment]
See #29486

**Comment by inferenceus** [comment]
@lunny 

> See #29486

You guys knocked it out of the park with this one.

Everyone is always "PGP this" and "GPG that", never "based SSH".

You are the first project I'm aware of which allows doing this. You have my thanks; much appreciated.
