### ISSUE TITLE
Network error during merge PR

### ISSUE THREAD

**Issue by yorliuk** [go-gitea/gitea#29455]
### Description

I got a popup with alert "Network error" after clicking "Create squash commit" in my Gitea.
There are no logs presents in the Gitea server docker container for that request.

### Gitea Version

1.21.6

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

No server logs

### Screenshots

<img width="1733" alt="image" src="https://github.com/go-gitea/gitea/assets/55086718/d62b9dec-82d6-456b-8285-a9cd5f720aae">

### Git Version

2.40.1

### Operating System

Alpine Linux 3.18

### How are you running Gitea?

Dockerized Alpine Linux 3.18 on Ubuntu 18.04.6 LTS host EC2 instance.

### Database

MySQL/MariaDB

**Comment by techknowlogick** [comment]
It's weird that it'd show you the padding at the end (padding added for msie message etc), as that comes from the reverse proxy.

**Comment by wxiaoguang** [comment]
> It's weird that it'd show you the padding at the end (padding added for msie message etc), as that comes from the reverse proxy.

It could also be wrong error message due to JS errors.

**Comment by yorliuk** [comment]
Request to merge PR was blocked by WAF rule. Issue solved.
Thank you all.
