### ISSUE TITLE
repo page still shows incorrect clone url under different domain names

### ISSUE THREAD

**Issue by darkclip** [go-gitea/gitea#29462]
### Description

I reported this issue weeks ago, see #29084 , it was quickly patched and marked as fixed.
But after the merge of that patch, the bug is still there.

### Gitea Version

1.21.7

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

![wrong](https://github.com/go-gitea/gitea/assets/2414081/adaa16b5-38df-4d17-96a3-4f324d75648c)

### How are you running Gitea?

docker

### Database

None

**Comment by ravensorb** [comment]
same is try for packages

**Comment by lunny** [comment]
> same is try for packages

Packages should be another issue.

**Comment by darkclip** [comment]
> I cannot reproduce it in my local both main and v1.21. How did you reproduce it on try site?

Just as I stated in the original issue report #29084, set `ROOR_URL = https://git.aaa.com:8443/`, then visit through `https://git.bbb.com/`.

**Comment by darkclip** [comment]
I suspect it's because `templates/repo/clone_script.tmp` is not being set with `url.port = window.location.port;.`
But I'm not sure.

**Comment by wxiaoguang** [comment]
Unfortunately , #29085 didn't fix the "clone_script.tmpl" .....

@silverwind would you like to take a look?

**Comment by silverwind** [comment]
Ah, I wasn't aware that `clone_script` was still a thing. I thought we had replaced it entirely with the web component, but apparently not.

**Comment by silverwind** [comment]
https://github.com/go-gitea/gitea/pull/29470
