### ISSUE TITLE
"Show this place on a map" doesn't work

### ISSUE THREAD

**Issue by stuzer05** [go-gitea/gitea#29472]
### Description

https://try.gitea.io/stuzer05

this button 
![image](https://github.com/go-gitea/gitea/assets/23124682/d3fe571f-d048-4be3-85c3-7dda0ebb8100)
will redirect you to 404 on https://try.gitea.io/Kyiv

### Gitea Version

trunk

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

-

### Database

None

**Comment by wxiaoguang** [comment]
Sorry I made a mistake in  #29236, the link shouldn't be there, will fixed by  Fix incorrect user location link on profile page #29474
