### ISSUE TITLE
Gitea personal access token not show up in Jenkins project config page

### ISSUE THREAD

**Issue by chenliangomc** [go-gitea/gitea#2948]
This issue is about the Gitea plugin for Jenkins.

Jenkins is the latest LTS version (2.73.3), deployed to standalone Apache Tomcat v8.5.23 running on top of oracle-java8: Java(TM) SE Runtime Environment (build 1.8.0_60-b27), Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode).

Git and PostgreSQL are hosted inside docker container (gitea/gitea:latest, library/postgresql:alpine).

- Gitea version (or commit ref): afa85f9 built with: bindata, sqlite [got from /app/gitea/gitea -v within the docker container]
- Git version: 1.9.1 [the git that is run by tomcat on the host system of the docker containers]
- Operating system: Ubuntu 14.04
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

Added a new GIT repository to gitea, and set it as 'public', Jenkins can pull source code from gitea and build; then re-config the repository as 'private', Jenkins can not pull; add newly created gitea personal access token in Jenkins project config page, under 'source code management' section, with AJAX pop-up; the token is shown in Jenkins' credentials page, but when going back to project config page, the token is not available in the credentials drop-down menu for the repository in 'source code management' section.

**Comment by chenliangomc** [comment]
screenshot https://imgur.com/a/549Vh
I had some problems to uploading the screenshot here.

Also I can not submit issue to https://github.com/jenkinsci/gitea-plugin

**Comment by techknowlogick** [comment]
@chenliangomc Jenkins has a JIRA instance for issues to be raised for plugins, you can find the link to JIRA on the [plugin page](https://wiki.jenkins.io/display/JENKINS/Gitea+Plugin).

The link to open tickets for the gitea-jenkins plugin is: http://issues.jenkins-ci.org/secure/IssueNavigator.jspa?mode=hide&reset=true&jqlQuery=project+%3D+JENKINS+AND+status+in+%28Open%2C+%22In+Progress%22%2C+Reopened%29+AND+component+%3D+%27gitea-plugin%27

**Comment by chenliangomc** [comment]
Sorry I just realize that personal access token is for API access, not for checking out code.

Close this.
