### ISSUE TITLE
[Feature] Ansible Galaxy package manager

### ISSUE THREAD

**Issue by lonix1** [go-gitea/gitea#29483]
### Feature Description

Would be nice to have a gitea-based Ansible Galaxy package manager.

Doesn't need to be fancy... just roles and maybe collections. The same "keep it simple" approach as was done for the other gitea package managers.

**Comment by KN4CK3R** [comment]
Last time I looked at that thing there was a ****load of endpoints. Visit https://galaxy.ansible.com/api/v3/openapi.json and unfold `paths`. I don't know Ansible, so I don't know whats needed for the "keep it simple" approach.

**Comment by delvh** [comment]
Done
