### ISSUE TITLE
Change locking automation back

### ISSUE THREAD

**Issue by yardenshoham** [go-gitea/gitea#29491]
### Description

For the past 2 days, I wake up to this:
![image](https://github.com/go-gitea/gitea/assets/20454870/3843b6de-54b8-408a-8783-ae55e9096539)
![image](https://github.com/go-gitea/gitea/assets/20454870/1651337c-7ad0-4e95-bdb5-720671c67f37)

This is happening because of https://github.com/go-gitea/gitea/pull/29436. I don't understand why it adds a comment, this is practically spam.

I suggest we either:
1. Revert https://github.com/go-gitea/gitea/pull/29436 and keep using giteabot for locking  (the bot knows when to comment and when to lock without comment, see https://github.com/GiteaBot/gitea-backporter/blob/c76b28699e142a4f5903131df223c6cafb80d7d5/src/lock.ts)
2. Remove the comments from the current CI

**Comment by techknowlogick** [comment]
the comments have been removed from the current CI
