### ISSUE TITLE
Landing page organizations

### ISSUE THREAD

**Issue by agaida** [go-gitea/gitea#2949]
- Gitea version (or commit ref): v1.1.0-771-g7e6c198f 

## Description
Landing page = org. is pretty cool, thank you very much for it - there is only one thing that is not so nice. We have some organistions for internal use only - there will never be public repos in it. So these organisations shoud have a private/non-public flag or should only been shown when at least one repository in it could be watched with the viewers rights.  

Sample: https://git.lxqt.org - administration, container and instances will never contain any public stuff.

**Comment by techknowlogick** [comment]
This is similar (not the same though) to the following feature request: #2908 

This comment is just so that the two tickets are linked.

**Comment by lunny** [comment]
This is duplicated with #714 and has a PR #1763
