### ISSUE TITLE
Unable to open checker on windows

### ISSUE THREAD

**Issue by yp05327** [go-gitea/gitea#29509]
### Description

https://github.com/go-gitea/gitea/issues/29349#issuecomment-1972295839

### Gitea Version

1.21.7

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

run binary

### Database

None

**Comment by charles7668** [comment]
I think the problem may be that Windows can't handle signals like Linux does, but in reality, the checker is working correctly.

In Linux, the exit code is 9, which corresponds to the signal "kill". However, in Windows, it always returns 1.

![image](https://github.com/go-gitea/gitea/assets/30816317/bc7996b1-c6f1-41b4-aa31-1ad8d7bd903b)

**Comment by wxiaoguang** [comment]
Hmm .... I have question for that code long time ago (https://github.com/go-gitea/gitea/pull/19006#issuecomment-1059939315)

But I don't have Windows environment at the moment .... if the code could be refactored and improved, I could help to review & approve.
