### ISSUE TITLE
API: POST `releases/{id}/assets` should accept `application/octet-stream`

### ISSUE THREAD

**Issue by silverwind** [go-gitea/gitea#29502]
### Feature Description

Adding release assets on GitHub's API [accepts `application/octet-stream`](https://docs.github.com/en/rest/releases/assets?apiVersion=2022-11-28#upload-a-release-asset) while Gitea's API [accepts `multipart/form-data`](https://github.com/go-gitea/gitea/blob/c7dcb58b1d96970959a5c8ac8d3955e4b7d027df/routers/api/v1/repo/release_attachment.go#L155-L156).

It should be made to accept both which is necessary for actions like [`ncipollo/release-action`](https://github.com/ncipollo/release-action) to work.

**Comment by KN4CK3R** [comment]
Strange that this essential endpoint is not Github compatible.
