### ISSUE TITLE
The `app.ini` seems like missing one line

### ISSUE THREAD

**Issue by Origami404** [go-gitea/gitea#29510]
### Description

Hello, as I was carefully reading through all the options in `app.ini`, I noticed that this line seems to be off. It appears to be a description of a configuration item, but the next line doesn't have a corresponding configuration item.

Link:
https://github.com/go-gitea/gitea/blob/58ce1de994c2a036ebf7137c143ce193694d740d/custom/conf/app.example.ini#L958

### Gitea Version

58ce1de994c2a036ebf7137c143ce193694d740d

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

Not related.

### Database

None

**Comment by wxiaoguang** [comment]
Good catch! The content should be 

```
; Close issues as long as a commit on any branch marks it as fixed
DEFAULT_CLOSE_ISSUES_VIA_COMMITS_IN_ANY_BRANCH = false
; Allow users to push local repositories to Gitea and have them automatically created for a user or an org
ENABLE_PUSH_CREATE_USER = false
ENABLE_PUSH_CREATE_ORG = false
```


(regression of #15807)
