### ISSUE TITLE
The usage of `NewRequestWithValues(t, "PATCH", url, data)` doesn't work in tests

### ISSUE THREAD

**Issue by yp05327** [go-gitea/gitea#29514]
### Description

~~`PATCH` request will read data from `Form`, but `NewRequestWithValues` will insert data into `Body`, so these data will not be readed correctly.~~
As title, the usage of `NewRequestWithValues(t, "PATCH", url, data)` doesn't work in tests
![image](https://github.com/go-gitea/gitea/assets/18380374/6b5c0d4a-6c87-42a2-9e19-f5b4666ecad5)

e.g.
![image](https://github.com/go-gitea/gitea/assets/18380374/eb223ec7-d234-49c6-84d6-8baa9d056db9)
![image](https://github.com/go-gitea/gitea/assets/18380374/2eec292e-5da9-4d04-a25c-36f2b0f93718)
![image](https://github.com/go-gitea/gitea/assets/18380374/e52c1458-3d9e-4944-97e9-50672d1d37d6)

### Gitea Version

latest

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

build

### Database

None

**Comment by yp05327** [comment]
For `Form`, if the type of the field is `*string`, it doesn't work, but if it is `string`, it works.

**Comment by yp05327** [comment]
@lunny 
It seems that this issue is because `gitea.com/go-chi/binding` doesn't support non-struct pointer.
https://gitea.com/go-chi/binding/pulls/5

**Comment by yp05327** [comment]
Any plan to finish it, API requests with form type body can not be applied correctly which looks like a big bug.

**Comment by lunny** [comment]
https://gitea.com/go-chi/binding/pulls/5 merged.

**Comment by yp05327** [comment]
Then the next step is adding result check in theses tests to confirm whether it works.

**Comment by lunny** [comment]
Can you help to send a PR?

**Comment by yp05327** [comment]
It seems that it does not work. Still got empty items.
I will send a PR to test it first, then let's fix it.

**Comment by yp05327** [comment]
@lunny 
the origin PR is not enough, create a new one to fix this issue:
https://gitea.com/go-chi/binding/pulls/16
