### ISSUE TITLE
Allow forking without a repo ID

### ISSUE THREAD

**Issue by CanisHelix** [go-gitea/gitea#29512]
### Feature Description

Forking a repository via the web UI currently requires visiting a /repo/fork/{{repoid}} URL. This makes it cumbersome to create a link that starts a fork, because the repository ID is only available via the API. While it is possible to create a link, doing so requires extra steps.

To make it easier to have a "Fork me!"-style links, introduce the /{username}/{repo}/fork route, which will start the forking process based on the repository in context instead.

This would bring gitea in line with Github's behavior too.

**Comment by wxiaoguang** [comment]
I guess the title could be "Allow forking **without** a repo ID"?

**Comment by CanisHelix** [comment]
> I guess the title could be "Allow forking **without** a repo ID"?

Good spot, really should have coffee earlier :-D
