### ISSUE TITLE
[Feature Request] Gotify Webhook Support

### ISSUE THREAD

**Issue by OdinVex** [go-gitea/gitea#29548]
### Feature Description

Gotify is a great Notifications server (push such as for SMS/Android) that uses a REST API, I'd love to get notifications when builds are available/complete or something's pushed and the implementation would be rather easy to do (but I don't know Go). Would Gitea consider Gotify webhook support?

**Comment by techknowlogick** [comment]
Merging into https://github.com/go-gitea/gitea/issues/1089
