### ISSUE TITLE
act_runner is not execute!

### ISSUE THREAD

**Issue by zhangbaojia** [go-gitea/gitea#29556]
### Description

@yp05327  Let me explain my operation in detail. Best if I can help.   Shut it down if can't help!

### Screenshots

1、the server does not have an external network
![微信截图_20240303164954](https://github.com/go-gitea/gitea/assets/19427334/e88fa3ff-0334-4b53-8c1d-dcb85c30b290)
![微信截图_20240303164854](https://github.com/go-gitea/gitea/assets/19427334/a12a2891-4c13-4787-9e14-6603305ee674)

2、download gite and act_runner from another server with a network,  docker load them ;
![微信截图_20240303154617](https://github.com/go-gitea/gitea/assets/19427334/aa3e01ff-0a24-4dda-83e5-520e197c1875)

3、run
![微信截图_20240303154659](https://github.com/go-gitea/gitea/assets/19427334/c4753031-af83-4b96-9217-44757bdf3199)

4、docker network agents
![微信截图_20240303155153](https://github.com/go-gitea/gitea/assets/19427334/4d654bd5-5cbc-4f75-ab25-b3a64914d9c7)
![微信截图_20240303162426](https://github.com/go-gitea/gitea/assets/19427334/43da319e-f184-426b-84e3-6078e1e31c41)

5、installation and configuration is  complete
![微信截图_20240303163720](https://github.com/go-gitea/gitea/assets/19427334/1f65cae9-e95f-4b4d-9335-e7473461541f)

6、create “demo.yaml”
![微信截图_20240303163609](https://github.com/go-gitea/gitea/assets/19427334/e17f6fe1-a5b1-41e3-969e-118ecd108ab6)

7、 did not run after push
![image](https://github.com/go-gitea/gitea/assets/19427334/858c27be-f38a-42af-8c81-69c4c4da4488)

### Gitea Version

1.21.7

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

Screenshots

### Browser Version

Microsoft Edge 122.0.2365.66

**Comment by techknowlogick** [comment]
What do the logs of the act_runner say?

**Comment by zhangbaojia** [comment]
![image](https://github.com/go-gitea/gitea/assets/19427334/65736219-b9f3-4356-b7c1-51842b60e2c4)

**Comment by lunny** [comment]
What's your ROOT_URL on app.ini ?

**Comment by zhangbaojia** [comment]
gite app.ini
![微信截图_20240304134716](https://github.com/go-gitea/gitea/assets/19427334/091b9c34-bb2b-4570-b9b4-8604ca2f61c6)
![微信截图_20240304134751](https://github.com/go-gitea/gitea/assets/19427334/c1ed9b3c-216f-4a93-84c7-8dcd587c8452)

runner config.yaml
![微信截图_20240304134816](https://github.com/go-gitea/gitea/assets/19427334/e2a509e6-3478-4f43-adcb-8b1d18722cc5)
![微信截图_20240304134827](https://github.com/go-gitea/gitea/assets/19427334/62316c85-561e-44fd-b98a-628354c67d27)

**Comment by lunny** [comment]
So you can try `ping 192.168.71.202` from act_runner docker to test whether the network works between act_runner and gitea. If not, change your ROOT_URL to the correct one.

**Comment by zhangbaojia** [comment]
see Setp 4 【figure 2】 ping gitea:3000

**Comment by zhangbaojia** [comment]
ping 192.168.71.202
![image](https://github.com/go-gitea/gitea/assets/19427334/45123ce2-f2b6-4711-942b-0ccc64492230)

**Comment by lunny** [comment]
<img width="377" alt="image" src="https://github.com/go-gitea/gitea/assets/81045/e49075ab-156b-4a49-a5a9-c7cc363d6bd3">
I'm confused that why the act_runner is connected to 172.20.0.3's 3000 but not 192.168.71.202's 9197

**Comment by wolfogre** [comment]
Please hold on, I think it has nothing to do with the runner.

The problem is that the push operations do not trigger any runs, instead of runs that are not executed by the runner. So I believe it's also caused by broken git hooks.

Since the problem seems related to the network, I guess maybe the Git hooks cannot connect to the root URL. Please check what happened if you attach to the gitea container and run `curl 192.168.71.202:9197`.

**Comment by zhangbaojia** [comment]
this?
![image](https://github.com/go-gitea/gitea/assets/19427334/7738a51e-29e1-4a22-a0e2-850b36a535a2)
![image](https://github.com/go-gitea/gitea/assets/19427334/7947c050-8fee-4a41-bec7-aa06e7263b13)
![image](https://github.com/go-gitea/gitea/assets/19427334/d0e35c43-3242-4f42-83fe-5922b10bd21b)

**Comment by zhangbaojia** [comment]
docker network:
![image](https://github.com/go-gitea/gitea/assets/19427334/5eddce36-d9e3-471b-a1d0-5e17cf1fbcb0)

gitea curl:
![image](https://github.com/go-gitea/gitea/assets/19427334/d7bbc1f7-23df-474a-998c-9a7c05785fac)

runner curl:
![image](https://github.com/go-gitea/gitea/assets/19427334/de63cf6c-a417-45f0-8b2c-52e36d71dc3f)

**Comment by zhangbaojia** [comment]
runner config.yaml
![image](https://github.com/go-gitea/gitea/assets/19427334/013db8c7-35be-472a-8daa-e469141e40f5)

runner restart
![image](https://github.com/go-gitea/gitea/assets/19427334/4b5e1de2-69bd-482b-8dc2-cdeaa20910fd)

**Comment by wolfogre** [comment]
I still believe the problem is not about the runner, but with the git hook. Maybe you can wait for #29494.

**Comment by charles7668** [comment]
Hmm... if I use a reverse proxy, then ROOT_URL = 9197 and HTTP_PORT = 3000 work fine.

**Comment by zhangbaojia** [comment]
> I still believe the problem is not about the runner, but with the git hook. Maybe you can wait for

i agree

**Comment by zhangbaojia** [comment]
> ROOT_URL = 9197

ROOT_URL  configured

![image](https://github.com/go-gitea/gitea/assets/19427334/f31d1ecd-ba20-4e19-bbba-9472b2c6c4e4)

**Comment by yp05327** [comment]
@zhangbaojia 
Does git hook fix solved your problem?
