### ISSUE TITLE
gitea-1.21.2 is not compatible with Windows 7

### ISSUE THREAD

**Issue by znsoooo** [go-gitea/gitea#29586]
### Description

After testing in all patch versions between v1.20.0 and v1.21.7 (including both gogit and non-gogit versions), I found that all versions<=v1.21.1 are running normally on Windows 7, and all versions>=v1.21.2 are crashed on Windows 7. (there even isn't any logs print out)

Run program in CMD:
![The highest supported version of Gitea for Windows 7 is v1.21.1](https://github.com/go-gitea/gitea/assets/34830785/2d0cdd89-1725-448b-a538-d5d8d2b01522)

As we all know Windows 7 is no longer supported by Microsoft, but the compatibility bug occurred only between the patch version v1.21.1 and v1.21.2. So I suspected that a minor change might have caused this compatibility issue. 

If possible, it is hoped that this issue can be solved in future releases.

### Gitea Version

1.21.2

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

2.34.0.windows.1

### Operating System

windows 7

### How are you running Gitea?

Download Windows EXE file from: https://dl.gitea.com/gitea/

### Database

None

**Comment by znsoooo** [comment]
> Because Gitea 1.21 was built by Golang 1.21 which have dropped support for windows 7. https://tip.golang.org/doc/go1.21#windows

But why v1.21 and v1.21.0 and v1.21.1 can work well?

**Comment by lunny** [comment]
> > Because Gitea 1.21 was built by Golang 1.21 which have dropped support for windows 7. https://tip.golang.org/doc/go1.21#windows
> 
> @lunny But why v1.21 and v1.21.0 and v1.21.1 can work well?

It's wired. Maybe it's related to Golang's minor version? I have no idea.

**Comment by KN4CK3R** [comment]
Can confirm but I get an error message:
```
> gitea-1.21.7-windows-4.0-386.exe
Exception 0xc0000005 0x8 0x0 0x0
PC=0x0

runtime.asmstdcall()
        /usr/local/go/src/runtime/sys_windows_386.s:35 +0x25 fp=0x22fdb8 sp=0x22fdb4 pc=0x4780f5
```
And that's expected behaviour https://github.com/golang/go/issues/64602

> The fact that your program built with 1.21.4 was running without problems may have been luck.

Should be the same in our case.

**Comment by techknowlogick** [comment]
Hi @znsoooo, sorry for the comment from algora above. There was a bug where it detected a trigger word from the golang URL posted. If you wish I can also refund the tip you provided.

Sadly, the project itself is unable to support older versions of Golang as Gitea does use features from newer versions of golang. So this error is expected as it is related to Golang's supported OSes. However, if you are interested in an extended support release that is built with a lower version of Golang please reach out to me and I can help you with that.

I will now close this issue.

**Comment by znsoooo** [comment]
@KN4CK3R @techknowlogick Thank you for your answers!
