### ISSUE TITLE
The logger not output messages when logging fatal

### ISSUE THREAD

**Issue by free1139** [go-gitea/gitea#2958]
I have been trying to install gitea (master and v1.3) today, but when i finish install it from browser, the go program was exited without any error messages, when i run "./gitea web" again, it can not be restarted.

I have debugged it, and i found "code.gitea.io/gitea/modules/log".Fatal  was using go channel to output messages,  maybe os.Exit was called before outputting messages .

My server system information:
Linux iZ23mbdnjl9Z 3.2.0-4-amd64 #1 SMP Debian 3.2.78-1 x86_64 GNU/Linux
CPU: 1 core

Maybe need to fix this code:
![image](https://user-images.githubusercontent.com/2360572/33125447-7a1ae6ce-cfbb-11e7-83a8-1ad429b6266f.png)

Official output:
![image](https://user-images.githubusercontent.com/2360572/33124789-24e76512-cfb9-11e7-9d73-f2431121fcf3.png)

Expect output:
![image](https://user-images.githubusercontent.com/2360572/33125083-3c483b4a-cfba-11e7-9028-5f2489463fd4.png)

**Comment by lunny** [comment]
Which file do you find the `os.Exit`?

**Comment by free1139** [comment]
code.gitea.io/gitea/modules/log/log.go

**Comment by lafriks** [comment]
You need to set rights for git user rights to have write access to that directory

**Comment by free1139** [comment]
Yes, it have no rights, the problem is that the official logger not output error message in this case, it's hard to installing without source code debugging, maybe it's not appropriate for newcomers.

**Comment by lunny** [comment]
This should be a bug of log module. The log haven't write to console or file and the application exited.

**Comment by wxiaoguang** [comment]
It should have been fixed by 
* https://github.com/go-gitea/gitea/pull/19994
