### ISSUE TITLE
Login page does not redirect if already authenticated

### ISSUE THREAD

**Issue by Abyss777** [go-gitea/gitea#29582]
### Description

In some major release, behavior after successful login was changed.

I have kerberos authorization in apache reverse proxy

```
    <Location /user/login>
        AuthType Kerberos
        AuthName "Kerberos Login"
        KrbAuthRealms AD.LOCAL
        KrbMethodNegotiate on
        KrbServiceName Any
        KrbLocalUserMapping On
        Krb5Keytab /etc/apache2/keytabs/gitea.keytab
        Require valid-user

        RewriteEngine On
        RewriteCond %{LA-U:REMOTE_USER} (.+)
        RewriteRule . - [E=RU:%1]
        RequestHeader set X-WEBAUTH-USER %{RU}e
        RequestHeader unset Authorization
    </Location>
```
That sets `X-WEBAUTH-USER` header only for `/user/login` location because I need unauthorized access to some gitea pages.

And proxy authorization enabled

```
ENABLE_REVERSE_PROXY_AUTHENTICATION = true
```

I'm not sure, but before 1.21 or even 1.20 after user click on Login button in right upper corner, he will be redirected to login page, get successful authentication via proxy header and then just redirected to default `/` page.

But in the latest releases redirect does not happen, user gets authenticated (sees his avatar in right upper corner) but still on the login page.

User usually doesn't understand that he is authenticated and complains that SSO don't works.

Could you please revert behavior and redirect from login page if proxy authentication was successful. 

### Gitea Version

 1.21.7

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

Official docker image 

### Database

MySQL/MariaDB

**Comment by wxiaoguang** [comment]
It is a regression of #26105. 

TBH, I regret that I approved it too quickly at that time .... it needs some more complicated designs to satisfy various cases now  .....
