### ISSUE TITLE
Review by commit dropdown (PR files changed tab) shows Committer not Author

### ISSUE THREAD

**Issue by sebastian-sauer** [go-gitea/gitea#29588]
### Description

The review by commit dropdown in the PR files changed view shows the committer of a commit and not the author.
I think we should change this to the author as it is displayed in Commits tab of a PR.

### Gitea Version

1.21.7

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

Gitea Binary 1.21.7 downloaded via the official download site

### Database

None

**Comment by sebastian-sauer** [comment]
If this bug is "accepted" i'd by happy to provide a PR for this.

**Comment by delvh** [comment]
Sounds good to me
