### ISSUE TITLE
Gitea returns a 500 when searching for %00

### ISSUE THREAD

**Issue by Bwko** [go-gitea/gitea#296]
- Gitea version (or commit ref): 27d66855eb642b22852b557cbb8ffd7781d73d4e
- Git version: 2.10.2
- Operating system: Arch linux
- Database:
  - [x] PostgreSQL 9.6.1 en_US.utf8
  - [ ] MySQL
  - [ ] SQLite
- Log gist: `2016/11/28 23:43:28 [...itea/routers/home.go:93 RenderRepoSearch()] [E] SearchRepositoryByName: Count: pq: invalid byte sequence for encoding "UTF8": 0x00`

Go to your local Gitea server, enter %00 behind ?q=  (like http://localhost/explore/repos?q=%00) and Gitea returns a 500 error

**Comment by lunny** [comment]
The error returned by postgres. For Golang, 
```
utf8.ValidString(url.QueryUnescape("%00"))
```
will return true. but postgres don't think so.

**Comment by tboerger** [comment]
Should we add a list of strings that get stripped before sending to the db?

**Comment by lunny** [comment]
Yes, I think maybe we have to write a regex? to limit the keyword.

**Comment by thibaultmeyer** [comment]
a regexp to avoid all non-printable chars could be useful. Of maybe is the job of the ORM to sanitize data before send it to SQL server ?

**Comment by lunny** [comment]
Sounds reasonable. Maybe it's the `database/sql` drivers' work :)

**Comment by bkcsoft** [comment]
It's a limitation in PostgreSQL
http://stackoverflow.com/questions/28813409/are-null-bytes-allowed-in-unicode-strings-in-postgresql-via-python
https://www.postgresql.org/message-id/4A271678.6010405@postnewspapers.com.au

**Comment by Bwko** [comment]
@lunny could you fix this?

**Comment by lunny** [comment]
Just ignoring `%00` could fix this bug. But if there are other characters will result in 500?

**Comment by Bwko** [comment]
To my knowledge `%00` are the only characters that result in a 500
