### ISSUE TITLE
After migrating from gogs push doesn't work

### ISSUE THREAD

**Issue by Bwko** [go-gitea/gitea#2960]
The [upgrade from gogs](https://docs.gitea.io/en-us/upgrade-from-gogs/ ) docs are outdated
The option `Rewrite all update hook of repositories ` is now called  `Resync pre-receive, update and post-receive hooks of all repositories.`

Second: all pre-/post/update hook files are now called `gitea`. So when you run this command it creates new hooks instead of replacing the old Gogs hooks. When somebody pushes to the repo the old Gogs hook results in an error.

**Comment by lunny** [comment]
User should remove that script manually, auto remove them is dangerous.

**Comment by Bwko** [comment]
Then we should change the docs :)
But what is exactly "dangerous" about it?

If it's dangerous we should warn the user, just like we do when a user removes a repo.

**Comment by lunny** [comment]
@Bwko we don't know that hook scripts are from Gogs or user customize scripts.

**Comment by akramparvez** [comment]
Had a similar issue, removing hooks from Gogs fixed it. 
Solution: [https://github.com/go-gitea/gitea/issues/3558#issuecomment-372429183](url)
