### ISSUE TITLE
Badges API test failure

### ISSUE THREAD

**Issue by techknowlogick** [go-gitea/gitea#29602]
Due to the bug of CI/test, the test failures are never caught:

![image](https://github.com/go-gitea/gitea/assets/2114189/6fdb4394-ae66-4d45-9a2b-bbf26ea4b27f)

_Originally posted by @wxiaoguang in https://github.com/go-gitea/gitea/issues/23106#issuecomment-1977899432_

**Comment by silverwind** [comment]
Related to https://github.com/go-gitea/gitea/pull/28102?
