### ISSUE TITLE
Question about how to enable "Actions"

### ISSUE THREAD

**Issue by xinmans** [go-gitea/gitea#29601]
### Description

按照这个指引设置了默认启用action 
https://docs.gitea.com/zh-cn/next/usage/actions/faq#是否可以在我的实例中默认启用新仓库的actions
您可以选择默认启用actions单元以适用于所有新仓库。
[repository]
DEFAULT_REPO_UNITS = ...,repo.actions

也配置了action 启用。

[actions]
ENABLED = true

创建新repo时，没有快速帮助，就一个啥都不是的页面，没法弄。

如何解决？

### Gitea Version

1.27.1

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

use action

### Database

None

**Comment by charles7668** [comment]
有截圖嗎

**Comment by lunny** [comment]
Please speak in English.

**Comment by yp05327** [comment]
What do you mean `啥都不是的页面`?

You can only check whether your settings are correct after create a repo, as if all things are correct, you will see the `Actions` tab.
![image](https://github.com/go-gitea/gitea/assets/18380374/23996293-41df-471a-a8c1-f53d2091feed)
