### ISSUE TITLE
UI enhancements for work with many organisations

### ISSUE THREAD

**Issue by culmat** [go-gitea/gitea#2961]
- Gitea version (or commit ref):
- Git version: 074f6c1
- Operating system: Windows
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

Currently organisations are the only way to structure repos into a hirarchy, see #2918 
This leads to creation of many orgs. 
While repo selection has filters, when i need to select an org, i get an unfiltered list / drop down and have to scroll through. It would be nice to have a filter here too.

## Screenshots

For repos I get a filter - this is nice :-)
![2017-11-23 09_42_25-matthias cullmann - dashboard - gitea_ git with a cup of tea](https://user-images.githubusercontent.com/638519/33164559-a7299b6a-d033-11e7-9880-2e8eb8086214.png)

For orgs no filter  ...
![2017-11-23 09_43_14-matthias cullmann - dashboard - gitea_ git with a cup of tea](https://user-images.githubusercontent.com/638519/33164579-bed69a38-d033-11e7-84f0-c835468605cc.png)

When selecting the owner of a new repo, I have to scroll through the list. Keyboard navigation is not really working (only first letter on FireFox Quantum) and the list is not even ordered ...

![2017-11-23 09_44_39-new repository - gitea_ git with a cup of tea](https://user-images.githubusercontent.com/638519/33164626-f45bb71a-d033-11e7-9968-c13bd086d8ce.png)

**Comment by tonk** [comment]
Just asking: Is there still progression in this?

**Comment by lunny** [comment]
@tonk nobody are working on this.
