### ISSUE TITLE
Cannot add user to organization

### ISSUE THREAD

**Issue by tomposmiko** [go-gitea/gitea#2962]
version: 1.3.0-rc1
It's OK with v1.2.3 .

Backend: MySQL.

I can add user to the system, but when I try to add it to an organization, it says 'User does not exist.'

**Comment by free1139** [comment]
I remove the nickname, only use account name to do it, it works well.

Example to add:
testing(testing) -- 'User does not exist'
testing -- pass

**Comment by lafriks** [comment]
If you press F12 in browser do you see any javascript errors there when adding user to team?

**Comment by lunny** [comment]
I confirmed this is a bug. And no js error.

**Comment by tomposmiko** [comment]
Thaks, I did not have time so far to respond.
