### ISSUE TITLE
Gitea fails to complete all checks with more than 1 pattern in "Enable status check"

### ISSUE THREAD

**Issue by makar112233** [go-gitea/gitea#29628]
### Description

Hello.
I have a branch, which is protected with setting "Enable status check" and Build server, which is sending statuses of build in Gitea.
When I set **only one** pattern in a field, all checks are considered successful.
When I set **multiply** patterns in a filed, I got an error "Some required checks are missing" 
You can see it on screenshots.

### Gitea Version

1.21.7

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

Multiply pattern

![sc1](https://github.com/go-gitea/gitea/assets/122980447/648fa3fb-c455-463a-8c5d-9943f5342767)

PR checks failed

![sc2](https://github.com/go-gitea/gitea/assets/122980447/2ac27363-9d01-4d75-b0dd-2d569274d363)

Single patterns

![sc3](https://github.com/go-gitea/gitea/assets/122980447/d6802845-2bcb-4d02-b6ce-3f78c7a5c105)

PR checks successful

![sc4](https://github.com/go-gitea/gitea/assets/122980447/6589302c-b4f5-484b-904e-4d6770189073)

### Git Version

latest

### Operating System

linux

### How are you running Gitea?

self-hosted

### Database

PostgreSQL

**Comment by wxiaoguang** [comment]
Maybe there could be a workaround, for example, use these rules?

```
*Complete*
*Build*
*Build*
```

(duplicate the `Build`)

Haven't tested it, but the bug seems to be caused by unmatched rules count & matched count.

**Comment by makar112233** [comment]
@wxiaoguang may be I didn’t understand the question, but in the field “Status check patterns” you need to write build tasks names, not statuses.
Example:
My build server send to Gitea status of these tasks, named:
```
Task1 Compile
Task2 Build
Task3 non-related
```
and in the field “Status check patterns” I need to specify
```
*Compile*
*Build*
```
It means that if Task1 and Task2 statuses will be “OK”, I would be able to merge.
But now this rule works only for one pattern. See screenshots below.

**Comment by wxiaoguang** [comment]
I meant that in you case, there are 2 patterns to match 3 results. Could you try this one?

```
*Compile*
*Build amd64*
*Build el8*
```

Use 3 rules to match 3 results, maybe it could be a workaround.

**Comment by wxiaoguang** [comment]
The changed behavior is from #29143, because the old behavior is considered to be a "bug".

If I understand correctly, suppose there are some results:

```
Task1 Compile
Task2 Build amd64
Task3 Build el8
```

And the rules are: 

```
*Compile*
*Build*
```

Before 29143, then the blow cases all pass:

```
Task1 Compile
Task2 Build amd64
(Task3 fails)
```

```
Task1 Compile
(Task2 fails)
Task3 Build el8
```

```
Task1 Compile
Task2 Build amd64
Task3 Build el8
```

----

After 29143, by using 3 rules:

```
*Compile*
*Build amd64*
*Build el8*
```

Only the result with all tasks succeeding is considered to pass.
