### ISSUE TITLE
500 error while upgrade from 1.6.x to 1.21.7 (Render failed, failed to render template: user/dashboard/dashboard, error: template error: builtin(bindata):user/dashboard/feeds:107:19)

### ISSUE THREAD

**Issue by SunRain** [go-gitea/gitea#29624]
### Description

After upgrading from 1.6.x to 1.21.7, this error appears on my Index page

```
Render failed, failed to render template: user/dashboard/dashboard, error: template error: builtin(bindata):user/dashboard/feeds:107:19 : executing "user/dashboard/feeds" at <index .GetIssueInfos 1>: error calling index: reflect: slice index out of range
----------------------------------------------------------------------
					{{$comment := index .GetIssueInfos 1}}
					              ^
```

### Gitea Version

1.21.7

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![Screenshot_20240306_153025](https://github.com/go-gitea/gitea/assets/864544/a087abcf-3f27-4717-84a2-0d8001d2418e)

### Git Version

2.40.1

### Operating System

Docker with unraid 6.12.4

### How are you running Gitea?

Docker with unraid 6.12.4

### Database

SQLite

**Comment by wxiaoguang** [comment]
You could bypass the error by truncating (delete all) your "action" table (or backup it first before emptying it)

**Comment by wxiaoguang** [comment]
->  Avoid issue info panic #29625
