### ISSUE TITLE
Locale FR not working and errors on issue-event structure

### ISSUE THREAD

**Issue by yomeuh** [go-gitea/gitea#2963]
- Gitea version (or commit ref): 1.3.0 or 1.3.0rc1
- Git version:
- Operating system: Debian 9
- Database (use `[x]`):
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
We used version 1.2.3 and eveything was fine.
When we tried 1.3.0 or 1.3.0rc1, our browsers showed bad structure on issue events as in #1413
Multiple browsers were affected (firefox, safari, chromium on OS X and epiphany, chromium on linux), only one was right, because it was a fresh install and never wen't on gitea... the browser is in french but gitea displays in english !
I cleared cookies in Epiphany and it switched to english and the structure went right.

**Comment by lunny** [comment]
Hi, could you give some screenshots?

**Comment by yomeuh** [comment]
Here is the bug in chromium:
![snapshot](https://user-images.githubusercontent.com/12572278/33247486-6cf068aa-d2ec-11e7-8563-3c03946f5272.png)

**Comment by yomeuh** [comment]
If it can help:
- this morning I test with a fresh FR install of chromium, the bug was there.
- I used a "locale switcher" to set EN locale,
- then I deleted gitea cookies and reload the page,
- now it's in english, without the bug.

**Comment by lafriks** [comment]
Fixed by  #3017
