### ISSUE TITLE
De-emphasize signed commits

### ISSUE THREAD

**Issue by silverwind** [go-gitea/gitea#29641]
I think the current UI gives too much attention to signed commits. Big green box on commit page, green box on commit hashes. Signing is important but not so important that we have to plaster the UI with these colors. I think a simple "verified" icon should be enough when viewing the commit detail page, and no indicator at all on commit hashes.

<img width="431" alt="image" src="https://github.com/go-gitea/gitea/assets/115237/7cec31f0-783e-4f11-b692-230301e0522f">
<img width="1333" alt="Screenshot 2024-03-06 at 22 50 58" src="https://github.com/go-gitea/gitea/assets/115237/cd71cd12-84c9-4ab2-bd59-6cfea07f4d30">

**Comment by BlenderDefender** [comment]
For comparison: This is, how it looks like on GitHub:
Commit list:
![grafik](https://github.com/go-gitea/gitea/assets/61777131/4c9191dc-bcdb-49f8-9239-a56511a46fb9)

Commit details:
![grafik](https://github.com/go-gitea/gitea/assets/61777131/d21f724f-7910-43f8-bf7c-2f48f0543a54)

**Comment by BlenderDefender** [comment]
Could look something like this:
![image](https://github.com/go-gitea/gitea/assets/61777131/0197e6c8-070a-4842-a0b7-1490815c1a30)
![image](https://github.com/go-gitea/gitea/assets/61777131/13d9d77a-d61f-42f4-a265-52af8a40dd21)

**Comment by BlenderDefender** [comment]
Other layouts where this badge would appear:
![grafik](https://github.com/go-gitea/gitea/assets/61777131/9d3a3901-dace-48b2-9e0d-c5590d21a337)
![grafik](https://github.com/go-gitea/gitea/assets/61777131/a5d4293d-3059-4ea5-b3e9-53c8386842aa)
![grafik](https://github.com/go-gitea/gitea/assets/61777131/6b06340b-91ae-43c6-b7be-d7352a2b4734)

**Comment by BlenderDefender** [comment]
Clicking the badge would trigger a modal:
![grafik](https://github.com/go-gitea/gitea/assets/61777131/cdbbe5c3-c876-4e88-86e4-f49923ee1ba0)
![grafik](https://github.com/go-gitea/gitea/assets/61777131/45260fca-6e9f-4af2-8028-f3f26e2014b8)
