### ISSUE TITLE
Link to change proposal process broken

### ISSUE THREAD

**Issue by svarlamov** [go-gitea/gitea#2964]
https://github.com/go-gitea/gitea/blob/master/CONTRIBUTING.md#discuss-your-design

The link to 'change proposal process' in the CONTRIBUTING.md is broken on Github

**Comment by appleboy** [comment]
It is working for me

**Comment by svarlamov** [comment]
When I click on "change proposal process" I get this:

![gitea-gh-404](https://user-images.githubusercontent.com/10859025/33192385-3856d192-d0fd-11e7-9678-90b5da645964.png)

**Comment by techknowlogick** [comment]
I can verify that the link takes you to: https://github.com/go-gitea/proposals which is a 404 and I see the same as the screenshot above

@appleboy perhaps as an owner you have access to hidden repos that we do not?

**Comment by lunny** [comment]
This process has been changed but not document. We only add an issue and mark as proposal. So  https://github.com/go-gitea/proposals is unnecessary.

**Comment by techknowlogick** [comment]
Thanks for the information @lunny :smile:
