### ISSUE TITLE
Can NOT edit issue content  GetUserById: context canceled

### ISSUE THREAD

**Issue by zjjhot** [go-gitea/gitea#29647]
### Description

when re-edit some issue content (not occur everytime) 
after click Save button , full content of issue disappeared.
after refresh page , the issue  still display last time content before edit. 

console output as :

2024/03/04 16:01:56 ...ices/auth/session.go:61:SessionUser() [E] GetUserById: context canceled

### Gitea Version

main branch

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

![I9`X$IVG~5`%JM } _~JN%M](https://github.com/go-gitea/gitea/assets/79889452/cf82af0e-9f7a-4766-9e0b-8b586dd97eb9)

### Git Version

main branch

### How are you running Gitea?

windows

### Database

mssql server

**Comment by yp05327** [comment]
Can you provide more logs? 
The log in your screenshot looks like you `refresh` the page, so the context canceled. Not related to the issue.

**Comment by zjjhot** [comment]
Sorry, this issue is related to the brand of the browser. 
This error will not occur in Chrome and Edge browsers, but only in 360 browser.

In that case, it may be a problem with the browser itself, not with Gitea.
