### ISSUE TITLE
Gitea Scrollbar is ugly (again)

### ISSUE THREAD

**Issue by mrexodia** [go-gitea/gitea#29652]
### Description

Apparently Chrome started supporting `scrollbar-color` and now Gitea looks ugly:

![image](https://github.com/go-gitea/gitea/assets/2458265/d6fd7fd8-86ae-4f52-bbb7-ffbcb8e0c6d5)

### Gitea Version

1.22.0+dev-969-g26653b196

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

It reproduces in try.gitea.io

### Database

None

**Comment by silverwind** [comment]
I would say the rendering is expected, at least that's how Firefox has been rendering for a long time now.

**Comment by KN4CK3R** [comment]
> Question is thought, whether we should do away with the scrollbar coloring completely.

Yes, please 🙏

**Comment by silverwind** [comment]
Waiting for more feedback. ❤️ or 👎 above post please whether you want custom scrollbars or not. Personally I don't care as MacOS overlay scrollbars are always native.

**Comment by ExplodingDragon** [comment]
firefox style looks good , maybe it can be emulated in chrome.
![图片](https://github.com/go-gitea/gitea/assets/33776693/d7b1e268-af44-4d57-80ee-e3dee51023d5)

**Comment by silverwind** [comment]
I think the vote clearly shows that people prefer default scrollbars. We shouldn't try to "emulate" anything. Let the browser decide. Can always be changed with a [userstyle](https://github.com/stylish-userstyles/stylish) if people prefer.

**Comment by aceArt-GmbH** [comment]
Chrome just got support for standard scroll bar styling https://caniuse.com/?search=scrollbar-color

**Comment by silverwind** [comment]
https://github.com/go-gitea/gitea/pull/29800
