### ISSUE TITLE
Flaky test `TestMergeRequiredContextsCommitStatus`

### ISSUE THREAD

**Issue by silverwind** [go-gitea/gitea#29661]
https://github.com/go-gitea/gitea/actions/runs/8199270074/job/22424432087

```
--- FAIL: TestMergeRequiredContextsCommitStatus (0.00s)
    commit_status_test.go:62: 
        	Error Trace:	/home/runner/work/gitea/gitea/services/pull/commit_status_test.go:62
        	Error:      	Test case failed
        	Test:       	TestMergeRequiredContextsCommitStatus
        	Messages:   	Test case 4 failed
FAIL
```

**Comment by yp05327** [comment]
This test is added in #29631
for case 4, `CommitStatus` are
```
{
    {Context: "Build 1", State: structs.CommitStatusSuccess},
    {Context: "Build 2", State: structs.CommitStatusSuccess},
    {Context: "Build 2t", State: structs.CommitStatusSuccess},
},
```
the rule is 
```
{"Build*", "Build 2t*", "Build 3*"},
```
and why expected result is `structs.CommitStatusPending`, all of them are success 🤔

**Comment by charles7668** [comment]
> This test is added in #29631 for case 4, `CommitStatus` are
> 
> ```
> {
>     {Context: "Build 1", State: structs.CommitStatusSuccess},
>     {Context: "Build 2", State: structs.CommitStatusSuccess},
>     {Context: "Build 2t", State: structs.CommitStatusSuccess},
> },
> ```
> 
> the rule is
> 
> ```
> {"Build*", "Build 2t*", "Build 3*"},
> ```
> 
> and why expected result is `structs.CommitStatusPending`, all of them are success 🤔

This is related to #29143. If a rule is added, then at least one matching action needs to exist.

discussion in #29631
