### ISSUE TITLE
Shim `/v3/repos` API for `actions/checkout`

### ISSUE THREAD

**Issue by silverwind** [go-gitea/gitea#29676]
### Description

Under condition `!ref && !commit`, `actions/checkout` calls out to the GitHub API:

https://github.com/actions/checkout/blob/8eb1f6a495037164bea451156472f35fdd6bafc0/src/github-api-helper.ts#L26

```
::group::Determining the default branch
Retrieving the default branch name
Not found.
```

It will fetch `/api/v3/repos/[user]/[reponame]` which is not available on Gitea's API. I wonder whether we should make some shims specific for this because the action it by far the most commonly action to use.

Original issue report: https://github.com/go-gitea/gitea/issues/29654

**Comment by silverwind** [comment]
This was reported in Discord, I asked the user to share more details on how they are running into this issue.

**Comment by silverwind** [comment]
Yes, this section confirms that the affected code is only used when git is not available:

https://github.com/actions/checkout/blob/8eb1f6a495037164bea451156472f35fdd6bafc0/src/git-source-provider.ts#L74

**Comment by silverwind** [comment]
I think we may consider just requiring `git` in the image. It's only unfortunate that `actions/checkout` fails with such an confusing error message. Maybe we should validate presence of `git` itself in `act-runner` to make the error reason clear.

**Comment by silverwind** [comment]
The only other two API calls I see in this fallback code are here:

https://github.com/actions/checkout/blob/8eb1f6a495037164bea451156472f35fdd6bafc0/src/github-api-helper.ts#L135-L136

These go to `/repos/{owner}/{repo}/tarball/{ref}` and `/repos/{owner}/{repo}/zipball/{ref}`. I think this is unversioned API that is likely present on Gitea.

**Comment by silverwind** [comment]
I don't think it's wise to require `git` after all. There may be more scenarios where it won't be there and I assume GitHub must have had good reasons for adding that fallback download via archive.

**Comment by nyanotech** [comment]
> This was reported in Discord, I asked the user to share more details on how they are running into this issue.

I guess I should say on this bug; I'm the user who reported it in discord, and #29654 is my report of this.

The details are in #29654, but in short, the actions workflow that I have that runs into this is basically [this example](https://gitea.com/actions/checkout#checkout-multiple-repos-private); the second repo's ref isn't plumbed in via the normal means.

Manually specifying a ref to check out in the action works around this issue.

**Comment by silverwind** [comment]
Closing in favor of https://github.com/go-gitea/gitea/issues/29654.
