### ISSUE TITLE
when I visit actions and activity happen 500

### ISSUE THREAD

**Issue by zunmx** [go-gitea/gitea#29736]
### Description

This repo create by idea, The default branch is master, but the default branch for gitea is main, 
When I change branch to main, and delete master branch, it's works

### Gitea Version

1.22.0+dev-808-g4ba642d07

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/35682146/f972f5f0-eef0-431c-8516-e16f1bf592fa)
![image](https://github.com/go-gitea/gitea/assets/35682146/eac2e18e-20f9-4d22-a442-a5179fd4b66f)

### Git Version

 2.43.0

### Operating System

CentOS Stream release 9

### How are you running Gitea?

github pull Repository, build it.

### Database

SQLite

**Comment by zunmx** [comment]
change branch log.
![image](https://github.com/go-gitea/gitea/assets/35682146/f7354b75-1765-4a65-8cd1-c362591748f7)

**Comment by lunny** [comment]
Please upgrade to latest 1.22 versions and sync branches on admin panel.

**Comment by yp05327** [comment]
How do IDEA create the repo ( I mean the repository in Gitea, not the git repo)? By plugin?
I don't think this is an issue from Gitea, as you can select default branch when create repos:
web ui
![image](https://github.com/go-gitea/gitea/assets/18380374/307f289b-914b-4e16-a764-98a725a7ce1b)
api:
https://github.com/go-gitea/gitea/blob/857243bed7f9dccdc597c2941df41e821781cb0f/modules/structs/repo.go#L120-L150

**Comment by zunmx** [comment]
sorry, my english is not good,  What I want to express is to manually create a Repository on Gitea and use idea to create branch  commit and push.

I tried a few times but couldn't reproduce the problem, I was surprised.
