### ISSUE TITLE
Actions status is incorrect

### ISSUE THREAD

**Issue by harryzcy** [go-gitea/gitea#29745]
### Description

See link: https://gitea.com/gitea/act/actions/runs/222

### Gitea Version

N/A

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

On gitea.com

### Database

None

**Comment by yp05327** [comment]
Maybe related: #25179
IIRC, it is not supported yet.

**Comment by lunny** [comment]
I think we can close this one because of duplicated with #25179

**Comment by harryzcy** [comment]
> I think we can close this one because of duplicated with #25179

Closing
