### ISSUE TITLE
Broken images url in commit

### ISSUE THREAD

**Issue by fintara** [go-gitea/gitea#2976]
- Gitea version (or commit ref): 1.3.0+rc1
- Git version: 2.15.0
- Operating system: Arch Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
Images in commit have the following URL:
`/$USER/$REPO/raw/$COMMIT/$PATH/$FILENAME`
has to be:
`/$USER/$REPO/raw/commit/$COMMIT/$PATH/$FILENAME`

I believe it was fine before 1.3.0-rc1.

## Screenshots
![screenshot_2017-11-26_12-14-39](https://user-images.githubusercontent.com/4290594/33239521-91612466-d2a3-11e7-8402-38948297f76d.png)

**Comment by lafriks** [comment]
I have submitted PR to fix this
