### ISSUE TITLE
Error loading packages page

### ISSUE THREAD

**Issue by pmandalka** [go-gitea/gitea#29762]
### Description

After Update from 1.21.7 to 1.21.8 I get an error on the packages page:

![image](https://github.com/go-gitea/gitea/assets/93120661/deb5f4d0-4068-4317-9f15-ddef8f850919)

### Gitea Version

1.21.8

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

1.21.8

### Operating System

Linux

### How are you running Gitea?

Official Docker images 
![image](https://github.com/go-gitea/gitea/assets/93120661/8233f8ca-ffb2-409b-95f3-6929cf1ab601)

### Database

PostgreSQL

**Comment by pmandalka** [comment]
I now downgraded to 1.21.7 - not it works again - is it seems to be a 1.21.8 problem

**Comment by wxiaoguang** [comment]
Sorry, my fault, a backport is missing  Fix incorrect package link method calls in templates #29580
