### ISSUE TITLE
Render failed, failed to render template

### ISSUE THREAD

**Issue by ronaldocherokee** [go-gitea/gitea#29773]
### Description

Problem to access TAB Packages after upgrade from 1.21.7 to 1.21.8.

Render failed, failed to render template: repo/packages, error: template error: builtin(bindata):package/shared/list:23:16 : executing "package/shared/list" at <.FullWebLink>: can't evaluate field FullWebLink in type *packages.PackageDescriptor
----------------------------------------------------------------------
					<a href="{{.FullWebLink}}">{{.Package.Name}}</a>
					           ^
----------------------------------------------------------------------

### Gitea Version

1.21.8

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/108280406/b5f58152-1cf7-4aa7-9e23-51e39bfd0085)

### Operating System

Docker (gitea/gitea:1.21.8)

### How are you running Gitea?

Docker image: gitea/gitea:1.21.8

### Database

SQLite

**Comment by wxiaoguang** [comment]
Sorry for the inconvenience.

* Known Issues
    * Browsing "packages" pages might cause 500 error, it could be fixed by updating to pre-1.21.9:
        * Docker image: use `gitea/gitea:1.21-nightly` and `gitea/gitea:1.21-nightly-rootless`
        * Binary: download from https://dl.gitea.com/gitea/1.21/

**Comment by lunny** [comment]
Fixed by #29764

**Comment by silverwind** [comment]
New release should be forthcoming soon.
