### ISSUE TITLE
Upload packages failed. Render failed on webpage

### ISSUE THREAD

**Issue by frank2002** [go-gitea/gitea#29771]
### Description

There is a problem uploading the container packages. 
For the privacy purpose, I created a private organization and upload the container to this organization. The uploading on the client is successful. However, on Gitea, it shows a 500 Render Error, with no packages successfully shown. No ways to manage the packages. 
I have tried to use https://gitea.xxxxx.com/api/swagger#/  to delete the package and upload again, but the problem persist,

### Gitea Version

 1.21.8

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/frank2002/2830868183fee897195b3f2766af01b1

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/20471771/f5aff321-660c-45e8-99af-15c2075b6ccb)

### Git Version

 2.40.1, Wire Protocol Version 2 Enabled

### Operating System

Debian 12

### How are you running Gitea?

Docker

### Database

SQLite

**Comment by lunny** [comment]
This has been fixed by #29764 and will be released in v1.21.9. You can also upgrade to v1.21-nightly.

**Comment by frank2002** [comment]
> This has been fixed by #29764 and will be released in v1.21.9. You can also upgrade to v1.21-nightly.

Greate. Thanks!

**Comment by wxiaoguang** [comment]
* Known Issues
    * Browsing "packages" pages might cause 500 error, it could be fixed by updating to pre-1.21.9:
        * Docker image: use `gitea/gitea:1.21-nightly` and `gitea/gitea:1.21-nightly-rootless`
        * Binary: download from https://dl.gitea.com/gitea/1.21/
