### ISSUE TITLE
Update version.json when new release comes out

### ISSUE THREAD

**Issue by sasuw** [go-gitea/gitea#29795]
### Description

In the upgrade script `contrib/upgrade.sh` is the line

```
giteaversion=$(curl --connect-timeout 10 -sL https://dl.gitea.com/gitea/version.json | jq -r .latest.version)
```

Currently, https://dl.gitea.com/gitea/version.json returns
```
{"latest":{"version":"1.21.7"}}
```
causing the script not to recognize that Gitea 1.21.8 is available. The script should be adjusted to reflect the latest version or the `version.json` should be changed in-sync with new releases.

### Gitea Version

1.21.7

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

Release package from github.com

### Database

None

**Comment by delvh** [comment]
@techknowlogick

**Comment by techknowlogick** [comment]
I've updated it, however I may consider making this dynamic. Our CDN allows for running scripts to generate pages (it's how I made the dynamic file listing), so I could fetch from the git repo itself to see the latest tag.

Will keep this open as a tracking item.

**Comment by wxiaoguang** [comment]
Maybe it should wait for 1.21.9 , since 1.21.8 has a known issue ....

**Comment by lunny** [comment]
It's now 1.21.8, so this can be closed.

**Comment by yp05327** [comment]
maybe related: docs can also use this JSON file to automatically update to the latest version?

**Comment by LauKr** [comment]
Just a quick note, the version currently is 1.21.10 instead of 1.21.11.

**Comment by lunny** [comment]
> Just a quick note, the version currently is 1.21.10 instead of 1.21.11.

Updated.
