### ISSUE TITLE
PR shows unrelated commits after merge

### ISSUE THREAD

**Issue by mxmehl** [go-gitea/gitea#2981]
- Gitea version (or commit ref): 1.2.3
- Git version: 2.1.4
- Operating system: Debian 8
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

After I merged Pull Requests, the PR page sometimes shows commits which are completely unrelated to what the PR has been about. It seems to include commits which happened between creating the branch/PR and the actual merge.

As an example, please see [PR 29](https://git.fsfe.org/FSFE/fsfe-website/pulls/29) on my installation by the user fbn_bmns which consisted of exactly [one commit](https://git.fsfe.org/FSFE/fsfe-website/commit/c35aafe3566c53d93bf5baf2520fc159f602161c). After merging it, it shows [22 commits](https://git.fsfe.org/FSFE/fsfe-website/pulls/29/commits) in total!

Why is this happening? Is this a Gitea bug? It would be good to have this fixed as it disables us having a decent overview about what happened in a PR after it has been merged...

**Comment by lafriks** [comment]
I believe this is duplicate of #2797 and is already fixed in master and will be fixed also in 1.3.0-rc2 release

**Comment by mxmehl** [comment]
You are right, this looks like my problem. Please excuse the duplicate, I didn't find this via the search.
