### ISSUE TITLE
The user profile follow button always shows "Follow", never "Unfollow"

### ISSUE THREAD

**Issue by yardenshoham** [go-gitea/gitea#29820]
### Description

To determine the string, the template looks at `$.IsFollowing`. See:
https://github.com/go-gitea/gitea/blob/66928946372c85cd41d404f63e3c1da1bdeca3ca/templates/shared/user/profile_big_avatar.tmpl#L120

Since https://github.com/go-gitea/gitea/pull/29248, the `IsFollowing` parameter is never set as the line that set it was deleted. [The relevant diff](https://github.com/go-gitea/gitea/pull/29248/files#diff-2b0b591787f16325539485e648a09ab6d3177f47dc129cfe84a35ffe141dfd19L39)

### Gitea Version

Current main

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

![demo](https://github.com/go-gitea/gitea/assets/20454870/909df6e1-5aad-4726-acec-cd3ef558f566)

### How are you running Gitea?

It doesn't matter

### Database

SQLite

**Comment by yardenshoham** [comment]
CC @zokkis

**Comment by silverwind** [comment]
Definitely need to fix this before 1.22.

**Comment by lng2020** [comment]
It also breaks the user description on the profile page. 
That PR is mainly focused on organization and accidentally deleted some code in the function `PrepareContextForProfileBigAvatar` that the user profile page also used. 
So I guess just added those codes back in the function `PrepareContextForProfileBigAvatar`?
