### ISSUE TITLE
Commits in the dashboard don't show signatures

### ISSUE THREAD

**Issue by b1ek** [go-gitea/gitea#29858]
### Description

If a commit is signed, it will not be shown as signed in the dashboard.

Steps to reproduce:

1. Add a GPG key to your account if it is not added already
2. Push a signed commit to a repository
3. It won't be shown as signed in the dashboard

### Screenshots

As you can see on this screenshot, the commit is shown as unsigned:

![a screenshot of a dashboard that shows that commit is unsigned](https://github.com/go-gitea/gitea/assets/57577711/4beb19de-dea2-4ac7-b03f-dd5118355ca0)

But it is actually signed

![a screenshot with full commit details, where it clearly says that the commit is signed](https://github.com/go-gitea/gitea/assets/57577711/025063f3-3146-4629-aaf0-95fe4d7a6f4d)

I have expected it to show like it is shown in the commit history (with the green badge):

![a screenshot of the commit history that shows a green badge with a lock symbol signaling that the commit is signed](https://github.com/go-gitea/gitea/assets/57577711/25cb7749-1c6e-4368-aaeb-19a7b5e6c7a5)

### Gitea Version

I am running the docker tag "gitea/gitea:1.21.3": 1.21.3 built with GNU Make 4.4.1, go1.21.5 : bindata, timetzdata, sqlite, sqlite_unlock_notify. The server's linux version is 6.4.12-arch1-1

### Can you reproduce the bug on the Gitea demo site?

I can, but I don't want to. The issue is pretty straightforward and can be confirmed by any gitea user that signs their commits

### Operating System

I am running Arch on linux 6.7.9-arch-1 x86

### Browser Version

I use Firefox Nightly, however it is not a browser specific issue since it doesnt have the CSS classes for that

![image](https://github.com/go-gitea/gitea/assets/57577711/eb6a4f01-caf1-4e25-b666-87d5a60c528b)
![image](https://github.com/go-gitea/gitea/assets/57577711/28c5db3d-89cb-421c-8ee8-c14ca6e90a10)

**Comment by silverwind** [comment]
While the issue is accurate, I don't think we should do it there as per https://github.com/go-gitea/gitea/issues/29641.

**Comment by yp05327** [comment]
duplicate #28281
