### ISSUE TITLE
Broken links to anchors for non-ASCII symbols on wiki TOC

### ISSUE THREAD

**Issue by crackedmind** [go-gitea/gitea#29877]
### Description

Anchors with non-ASCII symbols encodes twice and then isn't working anymore. Disabling javascript helps.

Create wiki page with title
```
# 气候宜人
```
It renders as `#user-content-%E6%B0%94%E5%80%99%E5%AE%9C%E4%BA%BA` but javascript modifies this to `#%25E6%25B0%2594%25E5%2580%2599%25E5%25AE%259C%25E4%25BA%25BA`

Seems it is regression since #29666 #29305

### Gitea Version

1.21.8

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

from command line

### Database

SQLite

**Comment by silverwind** [comment]
We should add some tests for these link rewrites with the fix.
