### ISSUE TITLE
AAD Login via OAuth fails with Dockerhub image "gitea/gitea" 

### ISSUE THREAD

**Issue by dominikschroeck** [go-gitea/gitea#29881]
### Description

I updated this morning to the most recent Gitea Docker image. Now I cannot login via AAD anymore using the AAD Oauth login. I just get sent back to the Homepage and the screen still looks like I am not logged in.

Could it be that the cookie is not set correctly?

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/28702562/febc09e6-e3ae-40de-9b93-0c58e42dd323)

### Gitea Version

1.21.8

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

MacOs 14.3.1

### Browser Version

Safari

**Comment by dominikschroeck** [comment]
Update: Downgrading the image to 1.21.7 helped solve this issue. So I suppose it is specific to 1.21.8

**Comment by wxiaoguang** [comment]
Does browser's "Private Window" (without any existing cookie) help?

Are you using Gitea under a sub-path behind reverse-proxy?

**Comment by dominikschroeck** [comment]
Yep, seems similar.
