### ISSUE TITLE
Render failed when opening PR with conversation

### ISSUE THREAD

**Issue by fhennig42** [go-gitea/gitea#29885]
### Description

I upgraded my gitea instance to version 1.21.7.
When I open certain PR's which already have a conversation/comments attached, I get the following error:
```
Render failed, failed to render template: repo/pulls/files, error: template error: builtin(bindata):repo/diff/conversation:4:45 : executing "repo/diff/conversation" at <0>: nil pointer evaluating *issues.Review.Type

{{$isNotPending := (not (eq (index .comments 0).Review.Type 0))}}

^
```

Since this looked similar to https://github.com/go-gitea/gitea/issues/29773 I also tried the newer versions 1.21.9 and even nightly with the same results.

### Gitea Version

1.21.7

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/fhennig42/7247399e2e87f6d7050414633661ff46

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/79085691/0f8aac4c-e3d2-4788-8bd4-0d5a980a49e9)

### Git Version

2.40.1

### Operating System

Ubuntu 22.04

### How are you running Gitea?

docker (official docker image managed by doker-compose)

### Database

None

**Comment by silverwind** [comment]
Hmm, not sure whether this is regression or not. Line is here:

https://github.com/go-gitea/gitea/blob/440be51a451baf08098501e300181cd77d798e11/templates/repo/diff/conversation.tmpl

**Comment by wxiaoguang** [comment]
It is not related to 29773, I think the root cause is that some database records are deleted then the template fails to render.

My guess is that the "review" is deleted.

I could remember a recent PR:  Workaround to clean up old reviews on creating a new one (#28554) #29264 

@6543 do you have more ideas?

**Comment by wxiaoguang** [comment]
A quick and dirty fix could be like this:  Fix template error when comment review doesn't exist #29888
