### ISSUE TITLE
Clicking cancel on application authorize shows successful page instead of something else

### ISSUE THREAD

**Issue by diamante0018** [go-gitea/gitea#29891]
### Description

Tested on try.gitea.io

To reproduce I created an empty repository.
I attempted to push using https on with git for windows version 2.43.0.windows.1
As shown in the screenshots below a new browser window opens and it asks me, the user, if I want to authorize the application to push to remote.

if I click cancel it will open a new page saying authorization was successful even though I declined.

Although the application was actually **not** authorized it's confusing and a fix would be nice

### Gitea Version

1.22.0+dev-1088-g34290a00c

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

![cancel](https://github.com/go-gitea/gitea/assets/37080671/7275307c-fffe-451d-bc76-a6cbfb9d902d)
![5](https://github.com/go-gitea/gitea/assets/37080671/49993847-2b00-4894-9009-70a1eddaaaa0)

### Git Version

Unknown, whatever is on try.gitea

### Operating System

Unknown, whatever is on try.gitea

### How are you running Gitea?

Unknown, whatever is on try.gitea

### Database

None

**Comment by wxiaoguang** [comment]
The "cancel" button is just a simple link: `<a href="{{.RedirectURI}}" class="ui basic primary inline button">Cancel</a>` , to your `http://127.0.01:54187`

So I guess "a new page saying authorization was successful even though I declined." is an incorrect message shown by your oauth app, not directly related to Gitea? In this case, Gitea didn't do authorize, it just redirects.

**Comment by diamante0018** [comment]
Oh really, sorry!
It honestly didn't cross my mind that this was not related to something outside of gitea.
So it's the app git for windows is using I assume. I'll dig deeper. I'll probably close this issue in a few hours once I turn on my pc to find out more about this

**Comment by diamante0018** [comment]
I was able to find what kind of application git for Windows is using and I found their Github. I'm sure they will be able to help me out given your response was that Gitea is basically just redirecting to whatever is running on my local host and I'm pretty sure it's their application.

**Comment by diamante0018** [comment]
I could swear sometimes when the page opens gitea automatically redirects me to that locahost without me clicking accept I don't think that's a git credentials manager issue but I can't repro consistently. Will keep this closed.
