### ISSUE TITLE
Allow redirecting 404 errors to 418 (teapot error)

### ISSUE THREAD

**Issue by EnderNon** [go-gitea/gitea#29895]
### Feature Description

 would be great as a joke function where, instead of an 404 page, you can have a 418 page that says something along the lines of being a teapot. It could be enabled by setting a value in app.ini as true so you wouldn't get this unless you're looking for it.

**Comment by KN4CK3R** [comment]
\*but why meme\*

**Comment by EnderNon** [comment]
> *but why meme*

because i thought it'd be funny

**Comment by EnderNon** [comment]
bump

**Comment by EnderNon** [comment]
ok nobody is going to ever do this
