### ISSUE TITLE
Unable to merge tracking into base: file name too long

### ISSUE THREAD

**Issue by yp05327** [go-gitea/gitea#29907]
### Description

- create a repo, add a file with long name (over 255 in linux)
- create a new branch, and commit some changes
- create a PR
- commit some changes to default branch
- go to the PR, you will see `Update branch by merge` button, and press it, then you will get this error:
![image](https://github.com/go-gitea/gitea/assets/18380374/ca9a2118-03e5-4c2b-b403-a78ddf8f9672)

### Gitea Version

latest

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

build

### Database

None

**Comment by yp05327** [comment]
https://serverfault.com/questions/9546/filename-length-limits-on-linux
It seems that the max length of filename in Linux is 255, but we can create a file with a name longer than this limit which will cause this issue.

**Comment by yp05327** [comment]
This was added in #29389 which is not correct enough.
https://github.com/go-gitea/gitea/pull/29389#discussion_r1501778024

**Comment by lunny** [comment]
The normal file system should allow file path length below 256?

**Comment by yp05327** [comment]
> The normal file system should allow file path length below 256?

Updated my comment above

**Comment by lunny** [comment]
Can we set git config like below in Gitea internal configuration?

```shell
git config core.longpaths true
```

**Comment by yp05327** [comment]
This may work in Windows, as Windows don't have file name length limit.
But in Linux, there's a limit of file name length, you can use `getconf NAME_MAX .` to see value.

**Comment by silverwind** [comment]
> ```shell
> core.longpaths
> ```

Is that a windows-specific option? I don't find it on https://git-scm.com/docs/git-config.

**Comment by lunny** [comment]
I just tested GH web editor, the filename can be longer than 255.

**Comment by yp05327** [comment]
I tried `git config core.longpaths true`, in Windows it works with no error.
But in Linux, we still has this problem.
So maybe we need detecting how long the filename can be in different OS.

**Comment by silverwind** [comment]
> I tried `git config core.longpaths true`, in Windows it works with no error. But in Linux, we still has this problem. So maybe we need detecting how long the filename can be in different OS.

No, let's just set on a common denominator, e.g. max. 255. We want repos to be portable.

**Comment by yp05327** [comment]
Ok, I will close this issue.
