### ISSUE TITLE
HTTP 500 on Packages of a repository

### ISSUE THREAD

**Issue by akirsch76** [go-gitea/gitea#29912]
### Description

When I click on packages in my repository with existing packages, I receive an HTTP 500, which is shown on the website.

Ein Fehler ist aufgetreten:

Render failed, failed to render template: user/overview/packages, error: template error: builtin(bindata):package/shared/list:23:16 : executing "package/shared/list" at <.FullWebLink>: can't evaluate field FullWebLink in type *packages.PackageDescriptor
----------------------------------------------------------------------
					<a href="{{.FullWebLink}}">{{.Package.Name}}</a>
					           ^
----------------------------------------------------------------------
Gitea-Version: 1.21.8

### Gitea Version

1.21.8

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

<img width="1225" alt="bug" src="https://github.com/go-gitea/gitea/assets/17491151/59d39902-1f12-4d6c-b8cc-d233b616aeb5">

### Operating System

Linux Docker Container

### How are you running Gitea?

As an application in TrueNAS Scale, which is a Docker container running with k3s.

### Database

PostgreSQL

**Comment by wxiaoguang** [comment]
Ref:  #29773

Sorry for the inconvenience.

* Known Issues
    * Browsing "packages" pages might cause 500 error, it could be fixed by updating to pre-1.21.9:
        * Docker image: use `gitea/gitea:1.21-nightly` and `gitea/gitea:1.21-nightly-rootless`
        * Binary: download from https://dl.gitea.com/gitea/1.21/

**Comment by akirsch76** [comment]
Thanks for the advice, and I'm sorry I haven't found this known issue.
