### ISSUE TITLE
Move issues from one repository to another on the same organization

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#2991]
Sometimes we need split one repository into multiple, but the issues can not be split. If this feature has been implemented, it's very useful. This operation could ask admin permission of organization.

**Comment by lofidevops** [comment]
At https://github.com/gogits/gogs/issues/4499 there was a suggestion to solve a similar request with a copy-and-close mechanism rather than a literal move. This would preserve issue and link history.

I'd also suggest that copying/moving issues between organizations is useful (not sure how to handle permissions).

**Comment by lunny** [comment]
Copy-and-close is better.

**Comment by WAMH** [comment]
Has this been addressed, or is there a workaround? It is a pain to copy an issue and all its comments and uploads. In our case, it is sometimes because of a simple mistake (posting on another repo by mistake, then needing to move the issue to the right repo)...

**Comment by lunny** [comment]
@WAMH no people are working on this.

**Comment by techknowlogick** [comment]
Setting review/confirmed label so stalebot ignores this issue

**Comment by 6543** [comment]
Idear: copy issue; close orig; delete comments on orig(they are moved); setup a redirect

**Comment by lifeofdan** [comment]
Yes, I would love this feature as well. In a big project, it is not uncommon for people to create the issue on the wrong repo and then need to move it later. Especially if the people creating the issue are not super familiar with the code base.

**Comment by sigma-frossignol** [comment]
People creating issues in the wrong repo is a recurring issue in my organisation, this feature would be really great.

**Comment by n3storm** [comment]
We have a triage project where we work on misc issues.
When issue grows to own project, it would be great to be able to move issues.

**Comment by lunny** [comment]
duplicated as #453
