### ISSUE TITLE
After deleting the review, the UI is broken.

### ISSUE THREAD

**Issue by HEREYUA** [go-gitea/gitea#29934]
### Description

Just as the title describes

**before：**

![image](https://github.com/go-gitea/gitea/assets/37935145/0228df4b-ad94-4b0c-ba5a-41f517b6f4d2)

**after：**

![image](https://github.com/go-gitea/gitea/assets/37935145/eaa54bae-d083-4981-bdbf-1c3e8f55e185)

Unsure if this is merely a display issue on the frontend, or if the review for the requested change should not have been deleted in the first place.

### Gitea Version

Latest

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

build

### Database

None

**Comment by wxiaoguang** [comment]
Maybe it is related to " Fix template error when comment review doesn't exist #29888 ": a quick and dirty fix for the 500 panic error of " Workaround to clean up old reviews on creating a new one #28554 "

**Comment by wxiaoguang** [comment]
->  Fix comment review avatar alignment #29935
