### ISSUE TITLE
The corners of the folded review files in pull request conversation page are not right.

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#29933]
<img width="939" alt="image" src="https://github.com/go-gitea/gitea/assets/81045/90c48712-e1ea-425d-b659-1c5e9ac427b0">

**Comment by silverwind** [comment]
I think I fixed this a long time ago with some CSS, must have regressed.

**Comment by HEREYUA** [comment]
It might be due to this CSS
![image](https://github.com/go-gitea/gitea/assets/37935145/d1d5e381-50d0-4f85-a206-d2708e50901b)
