### ISSUE TITLE
Cannot read properties of undefined (reading 'getAttribute')

### ISSUE THREAD

**Issue by yp05327** [go-gitea/gitea#29958]
### Description

a similar report: #23562
https://try.gitea.io/silverwind/symlink-test/pulls/11/files
![image](https://github.com/go-gitea/gitea/assets/18380374/a78eebee-ace3-417a-b73a-ffe51d178c4e)
![image](https://github.com/go-gitea/gitea/assets/18380374/80084f52-5494-4661-9201-00b20573946b)

### Gitea Version

latest

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

try.gitea.io

### Database

None

**Comment by wxiaoguang** [comment]
Dup:  JS error on pull files page #29956
