### ISSUE TITLE
Frontend error when view pull request files tab

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#29952]
Web browser: Firefox on macOS

It is displayed after one review comment has been deleted.

<img width="1412" alt="image" src="https://github.com/go-gitea/gitea/assets/81045/0dea210f-c157-4e89-8314-68b442cd7251">

**Comment by vinsonzou** [comment]
Only Chrome 123 or above is abnormal.

**Comment by lunny** [comment]
duplicated with #29956

**Comment by wxiaoguang** [comment]
> duplicated with #29956

It doesn't seem to be dup. They are related but maybe they are different problems.

**Comment by silverwind** [comment]
I think it's the same error. The error message is just different between Chrome and Firefox.
