### ISSUE TITLE
JS error on pull files page

### ISSUE THREAD

**Issue by wxiaoguang** [go-gitea/gitea#29956]
It looks like a regression of a recent PR (maybe Remove jQuery `.attr` from the archive download and compare page branch selector (#29918) )

Haven't got time to test or fix it. https://try.gitea.io/wxiaoguang/test/pulls/34/files (anonymous access)

![image](https://github.com/go-gitea/gitea/assets/2114189/a2e87382-63c7-4859-8b53-63452cbc8c46)

![image](https://github.com/go-gitea/gitea/assets/2114189/39ee33af-6101-42ae-9639-0315ad83786d)

**Comment by yp05327** [comment]
ps: https://try.gitea.io/wxiaoguang/test/ is a private repo

**Comment by wxiaoguang** [comment]
> ps: https://try.gitea.io/wxiaoguang/test/ is a private repo

I was doing some tests ... now it's public again 🤣

**Comment by vinsonzou** [comment]
Only Chrome 123 or above is abnormal.

**Comment by wxiaoguang** [comment]
> Only Chrome 123 or above is abnormal.

No. It isn't related to your browser. It is related to whether you have signed in.

**Comment by silverwind** [comment]
https://github.com/go-gitea/gitea/pull/29963
