### ISSUE TITLE
Cannot Start Gitea with OpenRC

### ISSUE THREAD

**Issue by hftsai256** [go-gitea/gitea#29954]
### Description

I recently upgraded Gitea from v1.17 to v1.21 (a side effect of upgrading Alpine Linux from v3.17 to v3.19). Gitea can no longer start with openrc. Here are the relevant error log I found in `/var/log/messages`:

```
Mar 21 02:30:17 gitea daemon.info supervise-daemon[790]: Supervisor command line: supervise-daemon gitea --start --pidfile /run/gitea.pid --respawn-delay 2 --respawn-max 5 --respawn-period 1800 --capabilities ^cap_net_bind_service --user gitea --env GITEA_WORK_DIR=/var/lib/gitea --chdir /var/lib/gitea --stdout /var/log/gitea/http.log --stderr /var/log/gitea/http.log /usr/bin/gitea -- web --config /etc/gitea/app.ini 
Mar 21 02:30:17 gitea daemon.err /etc/init.d/gitea[794]: Could not set iab: Operation not permitted
Mar 21 02:30:17 gitea daemon.warn supervise-daemon[791]: /usr/bin/gitea, pid 794, exited with return code 1
```

To my frustration, I cannot figure out what `iab` stands for in the above log after searching on the web for a day. Moreover, everything runs fine if I start it directly with `su gitea -c "gitea web"` and Gitea will start listening on port 3000. This makes me think something is wrong with `/etc/init.d/gitea`:
```
#!/sbin/openrc-run

supervisor=supervise-daemon
name=gitea
command="/usr/bin/gitea"
command_user="${GITEA_USER:-gitea}"
command_args="web --config '${GITEA_CONF:-/etc/gitea/app.ini}'"
supervise_daemon_args="--env GITEA_WORK_DIR='${GITEA_WORK_DIR:-/var/lib/gitea}' --chdir '${GITEA_WORK_DIR:-/var/lib/gitea}' --stdout '${GITEA_LOG_FILE:-/var/log/gitea/http.log}' --stderr '${GITEA_LOG_FILE:-/var/log/gitea/http.log}'"
pidfile="/run/gitea.pid"
extra_started_commands="reopen_log"
capabilities="^cap_net_bind_service"

depend() {
  use logger dns
  need net
  after firewall mysql postgresql
}

#https://github.com/go-gitea/gitea/issues/17976
#reload() {
#  ebegin "Reloading ${RC_SVCNAME}"
#  ${supervisor} ${RC_SVCNAME} --signal HUP --pidfile "${pidfile}"
#  eend $?
#}

reopen_log() {
  ebegin "Reopening logfile for ${RC_SVCNAME}"
  ${supervisor} ${RC_SVCNAME} --signal USR1 --pidfile "${pidfile}"
  eend $?
}
```

### Gitea Version

v1.21.6

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

2.43.0

### Operating System

Alpine 3.19

### How are you running Gitea?

Launch from `RC-init`:
```
rc-update add gitea
service gitea start
```

### Database

MySQL/MariaDB

**Comment by wxiaoguang** [comment]
Could you use your script to start some other service? eg: `sleep 1000`, I guess you might also see "Could not set iab: Operation not permitted" for other programs?

**Comment by hftsai256** [comment]
Thanks @wxiaoguang. That's a good catch. I have the same error with a different program. After digging around, I found the culprit was this line:
```
capabilities="^cap_net_bind_service"
```
It seems like an "unprivileged container" thing to me. I'm exposing port 3000 for HTTP and 22 for SSH, and leaving this line commented doesn't seem to impact SSH accessibility to my repo.

Thanks again.
