### ISSUE TITLE
OCI Packages failed to render template, error: template error

### ISSUE THREAD

**Issue by muthyo** [go-gitea/gitea#29970]
### Description

I am trying to push helm charts to a Gitea-registry, and I am getting the following error:

![gitea_1218rootless_broken](https://github.com/go-gitea/gitea/assets/72974367/239c1135-2f79-4be6-89f0-c7c4b535d9de)

The command used to push the helm chart is:

helm push chart.tgz oci://myregistry.mydomiain/myorganization

The output from the command says that it is pushed. When I try to view it in Gitea, it throws the 500 rendering error.

I can confim that the same command works on gitea 1.21.5-rootless.

Any ideas what is wrong?

Thanks in advance!

### Gitea Version

1.21.8-rootless

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

Podman container.

### Database

SQLite

**Comment by wxiaoguang** [comment]
Ref: #29773

Sorry for the inconvenience.

* Known Issues
    * Browsing "packages" pages might cause 500 error, it could be fixed by updating to pre-1.21.9:
        * Docker image: use `gitea/gitea:1.21-nightly` and `gitea/gitea:1.21-nightly-rootless`
        * Binary: download from https://dl.gitea.com/gitea/1.21/

**Comment by muthyo** [comment]
Thanks for fast support and sorry for not seeing the related issue!
