### ISSUE TITLE
关闭Javascript的错误提示

### ISSUE THREAD

**Issue by kekxv** [go-gitea/gitea#29987]
### Description

关闭这个错误提示，提供开关或者用户配置
<img width="997" alt="39489ce0764c5d4c1f25c418d6f7fd37" src="https://github.com/go-gitea/gitea/assets/15551108/1ca64b6e-511a-427b-8d97-f4ca5f6e80c5">

### Gitea Version

1.21

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

docker

### Database

None

**Comment by wxiaoguang** [comment]
It has been optimized by  Avoid duplicate JS error messages on UI (#28873) #28881  (in 1.21.5)
