### ISSUE TITLE
Login UI layout issue, the top marin of the login div missed.

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#29981]
<img width="1905" alt="image" src="https://github.com/go-gitea/gitea/assets/81045/a029f219-529d-4687-865b-b4d29f2fd1bc">

**Comment by wxiaoguang** [comment]
Regression of #29922? @silverwind 

The margin of page-content was removed:

```
.page-content {
  margin-top: 15px;
}
```

**Comment by silverwind** [comment]
Ah I did not see that because my login ui is different:

<img width="1341" alt="image" src="https://github.com/go-gitea/gitea/assets/115237/b47689f8-73e5-4ee4-a633-2857df81fb3a">

**Comment by silverwind** [comment]
What exactly is necessary to reproduce such a login ui?

**Comment by wxiaoguang** [comment]
I think `.page-content` really needs this margin-top

We should use margin for outer spaces as much as possible. They could overlap gracefully.

**Comment by silverwind** [comment]
No, I think content should itself decide whether it want margin or not. Many tabbars want 0 margin. It's not for the `.page-content` to decide.

**Comment by silverwind** [comment]
And @lunny don't call it broken. A minor layout issue is far from "broken" :)

**Comment by silverwind** [comment]
The problem is the negative margins from fomantic on `.ui.grid`.

**Comment by lunny** [comment]
> And @lunny don't call it broken. A minor layout issue is far from "broken" :)

Please help me to change it to a proper word.

**Comment by silverwind** [comment]
I would call it "misalignment" or "layout issue".
