### ISSUE TITLE
Always support repo code search even if the indexer is not enabled

### ISSUE THREAD

**Issue by arbitrary-dev** [go-gitea/gitea#29996]
### Feature Description

Here it says that Gitea supports "Repository code search":
https://docs.gitea.com/installation/comparison?_highlight=repository&_highlight=code&_highlight=search#code-management

Yet I was disappointed, when I couldn't find one on a running testing instance browsing a couple of repos:
https://try.gitea.io/

Please add it.

**Comment by arbitrary-dev** [comment]
>The try site and default instances haven't enabled it.

Why so?

And, is there anywhere in the docs a description on how to enable it?

**Comment by lunny** [comment]
https://docs.gitea.com/administration/repo-indexer?_highlight=indexer#setting-up-the-repository-indexer

**Comment by 6543** [comment]
@arbitrary-dev be aware your text is formulated harsh and undreandly ... exactly the "demand"ing part!

This is a foss project, if you want to demand anything you can only do so if you have a contract by paying (not donating by the way ...) witch you dont!

**Comment by wxiaoguang** [comment]
Actually I am writing one:  Support repo code search without external indexer #29998

**Comment by arbitrary-dev** [comment]
Cool, thanks! @wxiaoguang

Then it seems like the current documentation is a bit ambiguous on the topic.
It says "Repository code search: ✓", when in reality it is:

Repository code search: ✓ *

\* external indexer required

<hr/>

Some people just need to grow up and stop being offended by mere words :)

**Comment by wxiaoguang** [comment]
Here is Gitea Community Code of Conduct, we encourage to use positive and "welcoming and inclusive language"

https://github.com/go-gitea/gitea/blob/main/CODE_OF_CONDUCT.md

**Comment by 6543** [comment]
>  external indexer required

Thats wrong you can set belve as indexer witch is compiled in ...

**Comment by arbitrary-dev** [comment]
> witch

*which
