### ISSUE TITLE
Wiki support

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#3]

**Comment by lunny** [comment]
Proposal

I would like to create a wiki git repo related a git repo. So we need add two new fields on Repository ```
```
WikiRepoId int64
IsWiki bool
```

If ```repo.WikiRepoId == 0```, then it's wiki is not enabled. If ```IsWiki```, then it should be hidden on repo list.
A wiki git repo could be named with ```<repoName>-wiki.git```
A wiki path is a markdown file on wiki git repo. A wiki path is allowed to have a ```/```. When creating a wiki page, it will create a git file and generate a commit. When modify a wiki page, it will generate a commit. Every wiki page could have its history.

A wiki git repo could be also cloned via ```<repoName>-wiki.git```.

**Comment by tboerger** [comment]
I would prefer ```repo.WikiRepoId IS NULL``` if there is no wiki. Beside that it sounds good to me.

**Comment by makhov** [comment]
@tboerger NULL in MySQL is very specific type and if you can **don't** use it, you should don't use it.

**Comment by tboerger** [comment]
@makhov but it's more conventional to keep an field empty instead of setting it to 0 just to show "there is no link".

**Comment by makhov** [comment]
If @lunny does not mind, I'll make it.

**Comment by lunny** [comment]
OKay. @makhov

**Comment by slothbag** [comment]
Wiki would be awesome
