### ISSUE TITLE
Embed bindata optionally

### ISSUE THREAD

**Issue by tboerger** [go-gitea/gitea#30]
I would like to embed the bindata optionally based on a build tag, since we are running a Go application I really love the feature to server everything from the single file.

**Comment by bkcsoft** [comment]
Cannot up-vote this issue enough, this is _killing_ my dev-speed because I have to recompile all the time for things that aren't even being compiled :unamused:

**Comment by bkcsoft** [comment]
Maybe add a `pre-compile`-tag as well while we're at it, which pulls in `templates/, scripts/, public/` for a _truly_ single-binary release :wink:

**Comment by strk** [comment]
My PR #78 is solely about the optionality of embedding

**Comment by tboerger** [comment]
Solved via #354
