### ISSUE TITLE
The buttons on the file view page are not aligned

### ISSUE THREAD

**Issue by yardenshoham** [go-gitea/gitea#30009]
### Screenshots

![image](https://github.com/go-gitea/gitea/assets/20454870/7f884e73-cbbc-4b3c-bb09-bb80724ca950)

### Gitea Version

current main

### Can you reproduce the bug on the Gitea demo site?

Yes

### Browser Version

.

**Comment by silverwind** [comment]
Did https://github.com/go-gitea/gitea/pull/30007 fix it?

**Comment by silverwind** [comment]
Pretty sure it's fixed an try confirms it: https://try.gitea.io/silverwind/symlink-test/src/branch/master/asciicast.cast
