### ISSUE TITLE
Revisions tab and commit signature

### ISSUE THREAD

**Issue by deguif** [go-gitea/gitea#3000]
- Gitea version (f148a4a):
- Git version:
- Operating system:
- Database:
  - [x] PostgreSQL
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] not yet

## Description
When displaying the revisions tab on a PR, when there are commit signatures, this error is shown:
`template: repo/commits_table:45:90: executing "repo/commits_table" at <.Verification.Verifi...>: can't evaluate field Verification in type interface {}`

**Comment by deguif** [comment]
Need testing on my side, as this probably due to wrong docker image. I suspect wrong version for latest tag on my machine.

**Comment by deguif** [comment]
@lafriks sorry, the bug is my fault. I should have investigated a little more before creating the issue.
This was due to docker compose which doesn't pull latest image when it already has it locally. It instead used my local latest image which was old. That's why commit verification were not present.

This can be closed, and sorry again for this.

**Comment by sapk** [comment]
@deguif you can close the issue yourself if no admin as done it before you read this message.

**Comment by lafriks** [comment]
Thanks for letting know
