### ISSUE TITLE
No matching online runner with label: {label_name}, even though such a runner exists

### ISSUE THREAD

**Issue by kerem0comert** [go-gitea/gitea#30001]
### Description

Hello,

I have a Runner to run Gitea Actions with. This has worked in the past, but abruptly stopped working after some time. The Actions are supposed to run after each commit, but they either stay in the "Waiting" state without any logs, or I can see the error message in the UI that says "No matching online runner with label", even though that label exists on the Runner. I tried with several different labels, but in every case the Job could not find the runner with label. 
Looking forward to any help that you could provide.

### Gitea Version

1.21.5

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

2024/03/22 11:45:42 ...eb/routing/logger.go:102:func1() [I] router: completed GET /user/settings/actions/runners for [IP], 200 OK in 13.5ms @ setting/runners.go:98(setting.Runners)
2024/03/22 11:45:43 ...eb/routing/logger.go:102:func1() [I] router: completed POST /api/actions/runner.v1.RunnerService/FetchTask for [IP], 200 OK in 35.3ms @ <autogenerated>:1(http.Handler.ServeHTTP-fm)
2024/03/22 11:45:45 ...eb/routing/logger.go:102:func1() [I] router: completed POST /api/actions/runner.v1.RunnerService/FetchTask for [IP], 200 OK in 34.8ms @ <autogenerated>:1(http.Handler.ServeHTTP-fm)
2024/03/22 11:45:46 .../context_response.go:68:HTML() [D] Template: user/settings/runner_edit
2024/03/22 11:45:46 ...eb/routing/logger.go:102:func1() [I] router: completed GET /user/settings/actions/runners/4 for [IP], 200 OK in 16.3ms @ setting/runners.go:135(setting.RunnersEdit)
2024/03/22 11:45:47 ...eb/routing/logger.go:102:func1() [I] router: completed GET /admin/actions/runners for 10.212.134.206:0, 200 OK in 15.6ms @ setting/runners.go:98(setting.Runners)
2024/03/22 11:45:47 ...eb/routing/logger.go:102:func1() [I] router: completed POST /api/actions/runner.v1.RunnerService/FetchTask for [IP], 200 OK in 34.8ms @ <autogenerated>:1(http.Handler.ServeHTTP-fm)
2024/03/22 11:45:48 ...eb/routing/logger.go:102:func1() [I] router: completed GET /admin/actions/runners for 10.212.134.206:0, 200 OK in 16.5ms @ setting/runners.go:98(setting.Runners)
2024/03/22 11:45:48 ...d/actions/runners.go:137:RunnerDetailsEditPost() [D] RunnerDetailsEditPost success: /user/settings/actions/runners/4
2024/03/22 11:45:48 ...eb/routing/logger.go:102:func1() [I] router: completed POST /user/settings/actions/runners/4 for [IP] 303 See Other in 7.6ms @ setting/runners.go:155(setting.RunnersEditPost)
2024/03/22 11:45:49 .../context_response.go:68:HTML() [D] Template: user/settings/runner_edit
2024/03/22 11:45:49 ...eb/routing/logger.go:102:func1() [I] router: completed GET /user/settings/actions/runners/4 for [IP], 200 OK in 15.9ms @ setting/runners.go:135(setting.RunnersEdit)
2024/03/22 11:45:49 ...eb/routing/logger.go:102:func1() [I] router: completed POST /api/actions/runner.v1.RunnerService/FetchTask for [IP], 200 OK in 35.0ms @ <autogenerated>:1(http.Handler.ServeHTTP-fm)

### Screenshots

![issue_1](https://github.com/go-gitea/gitea/assets/42437138/1d5e1550-aefa-4868-8d40-23045518be79)
![issue_2](https://github.com/go-gitea/gitea/assets/42437138/f0fcc807-2a43-4c1a-880e-6f329675b372)

### Git Version

1.21.5

### Operating System

Linux

### How are you running Gitea?

It is ran through a Docker container.

### Database

None

**Comment by yp05327** [comment]
The owner of the repository is an organization or yourself or other users? As the runner type is individual.

**Comment by kerem0comert** [comment]
It belongs to an organization, and no - I cannot see the runner under individual repositories (even though the logs state of the screenshot that I attached to my first post is available, under the Actions tab for each repo). The runner is also Idle in ```admin/actions/runners```.

**Comment by lunny** [comment]
Your screenshot displayed the runner belongs to some repository because its `type` is individual.
In `admin/actions/runners`, it will displayed all runners on this instances but you have to check the scopes while the `type`.

**Comment by yp05327** [comment]
> It belongs to an organization

Then you need an organization or repository level runner, the runner you are using is individual.

For more information, you can see the document here:
https://docs.gitea.com/usage/actions/quickstart#set-up-runner
https://docs.gitea.com/usage/actions/act-runner#runner-levels

But, it seems that the description of individual level runner is missing in docs. 😕 
![image](https://github.com/go-gitea/gitea/assets/18380374/2be63d80-a27c-4dcf-a9cb-621c2e359b87)

**Comment by kerem0comert** [comment]
As the Gitea instance admin, can I have access to a runner that another user has created to change its type?
Maybe because the docs are missing, but I am not sure how to change the type of an existing runner. From ```admin/actions/runners``` I can see that the type of my runner is ```individual``` but when I click the edit icon for that runner I can only change its description, or delete this runner.

![runner_update](https://github.com/go-gitea/gitea/assets/42437138/c2ed8980-f5b3-41d5-b681-a3c044bb5f2b)

**Comment by lunny** [comment]
> As the Gitea instance admin, can I have access to a runner that another user has created to change its type? Maybe because the docs are missing, but I am not sure how to change the type of an existing runner. From `admin/actions/runners` I can see that the type of my runner is `individual` but when I click the edit icon for that runner I can only change its description, or delete this runner.
> 
> ![runner_update](https://private-user-images.githubusercontent.com/42437138/320466822-c2ed8980-f5b3-41d5-b681-a3c044bb5f2b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1ODA2NzIsIm5iZiI6MTcxMjU4MDM3MiwicGF0aCI6Ii80MjQzNzEzOC8zMjA0NjY4MjItYzJlZDg5ODAtZjViMy00MWQ1LWI2ODEtYTNjMDQ0YmI1ZjJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDEyNDYxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzN2Q3ZTBlOWYxZWVkZDcwZWE4ZGRlMzI5NDNiYTYwMTQxYmNhOThjMzYwM2ZiODZmMzZmZmQ2MWNkZTAxNmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YL36ICwSpkzq2awKUWq7w0GRoATpj8_fxPjSFfE9tpA)

Type cannot be changed.

**Comment by kerem0comert** [comment]
The issue is resolved, by recreating the runner with ```type: organisation```. Thanks for moving me into the right direction!
