### ISSUE TITLE
Disable Minimum Key Size Check shown as × despite MINIMUM_KEY_SIZE_CHECK = false

### ISSUE THREAD

**Issue by lwlwlwlw** [go-gitea/gitea#30019]
### Description

"Disable Minimum Key Size Check" is shown as × when MINIMUM_KEY_SIZE_CHECK = false,
and it is shown as ✓ when MINIMUM_KEY_SIZE_CHECK = true or absent,
at page "http://server:port/admin/config"

I assume the opposite is correct.

### Gitea Version

1.21.9

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

Gitea on Windows 10 22H2.

### Database

None

**Comment by wxiaoguang** [comment]
It has been fixed by  Remove duplicate option in admin screen and now-unused translation keys #28492 , but not backported ....
