### ISSUE TITLE
Add time tracking features for project management

### ISSUE THREAD

**Issue by yomeuh** [go-gitea/gitea#3003]
## Description
Maybe others would like such enhancements, our team would love them to evaluate our project plans
- ability to see time tracking value in issues list
- ability to see the total time tracking at the end of the list, at least in the issues list for a specific milestone
- as an extra, ability to set "time planned" to compare with effective time
![snapshot-issue-list](https://user-images.githubusercontent.com/12572278/33271982-cc6c9e24-d356-11e7-89ba-e22a51d348c1.png)
![snapshot-time-planned](https://user-images.githubusercontent.com/12572278/33271980-cc3d1f3c-d356-11e7-9132-c957e738a06c.png)
![snapshot-total-time](https://user-images.githubusercontent.com/12572278/33271979-cc299ff2-d356-11e7-8b2f-e71c29eb0dee.png)
![snapshot-milestone-stats](https://user-images.githubusercontent.com/12572278/33271981-cc50b42a-d356-11e7-9bbd-8541ee0c55b4.png)

**Comment by kolaente** [comment]
This overlaps with #2615 I think, but yours goes deeper.

**Comment by xak2000** [comment]
Also it should be possible to edit or at least remove already tracked time.

For example:
- I can accidentally track wrong number (80h instead of 8h).
- I can forget to press "stop" button after "start" and remember this after two weeks.

And it should be possible to undo this or change these tracked values, or else it would be to dangerous function to use.

**Comment by kolaente** [comment]
@xak2000 would you mind opening a separate issue for this?

**Comment by xak2000** [comment]
Is this issue alreay implemented? I thought it can be part of this issue (see bullets in first message).
Opened #3447.

**Comment by MrHaroldA** [comment]
It looks like #3341 fixes all, but:

> as an extra, ability to set "time planned" to compare with effective time

I can't seem to find a separate request for that? Is this still on the project scope? This will allow us to plan our milestones/sprints without the need of a calculator ;)

**Comment by lunny** [comment]
There are no plan time in current implementation I think.
