### ISSUE TITLE
Assign a specific branch for the issue being created when using API.

### ISSUE THREAD

**Issue by maks-mishin** [go-gitea/gitea#30044]
### Feature Description

It became necessary to assign a specific branch for the issues being created when using the API.

It is possible to assign a branch to an issue when using the GUI (screenshot), but there is no such field when creating issues via the API.

### Screenshots

![Assign branch](https://github.com/go-gitea/gitea/assets/24493995/eeb3ba08-48d3-4cf7-98ae-75fea0cd3a60)

**Comment by lunny** [comment]
This has been implemented https://docs.gitea.com/api/1.22/#tag/issue/operation/issueListIssues .

**Comment by maks-mishin** [comment]
Thanks! Today I discovered this functionality and closed the issue.
