### ISSUE TITLE
`git grep` error `signal: killed`

### ISSUE THREAD

**Issue by KN4CK3R** [go-gitea/gitea#30069]
If a search query produces more then 50 results the grep call is canceled which results in a `signal: killed` error from `scanner.Err()`.

@wxiaoguang

**Comment by wxiaoguang** [comment]
Oh yes, you are right, I'm on it now

**Comment by wxiaoguang** [comment]
Fix git grep search limit, add test #30071 

Added a test, without the fix, the test fails with "signal: killed"
