### ISSUE TITLE
Show "_comment" of composer.json

### ISSUE THREAD

**Issue by thojo0** [go-gitea/gitea#30075]
### Feature Description

Show the content of "_comment" from `composer.json` on the package page.

https://getcomposer.org/doc/04-schema.md#-comment

**Comment by KN4CK3R** [comment]
Does Packagist show these comments? If yes, could you link an example package?

**Comment by thojo0** [comment]
`_comment` doesn't get used, but the README so I think the README would be the better option.
Just look at almost any project on Packagist for the README:
Example: [laravel/laravel](https://packagist.org/packages/laravel/laravel)
Maybe just show the README of the linked repository.

**Comment by KN4CK3R** [comment]
Already have a branch ready which reads the readme file too. Will create a PR soon.

**Comment by thojo0** [comment]
I will close this as 'not planned' because README is the better option.
