### ISSUE TITLE
app.ini.sample is ignored by .gitignore

### ISSUE THREAD

**Issue by jonasfranz** [go-gitea/gitea#3007]
- Gitea version (or commit ref): 4d85c1d3c875609b57219ab7b74678f5876dbccb
- Git version: not relavent
- Operating system: not relavent
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

custom/conf/app.ini.sample is actually ignored by .gitignore but is present in the repository.

https://github.com/go-gitea/gitea/blob/4d85c1d3c875609b57219ab7b74678f5876dbccb/.gitignore#L48

**Comment by lunny** [comment]
That's not an issue I think.

**Comment by lafriks** [comment]
Actually it might be... wouldn't changes be ignored on that file by git?

**Comment by jonasfranz** [comment]
@lafriks That happend in my case. (I don't know if it caused by my editor or git itself)

**Comment by kolaente** [comment]
@lafriks I've added a standard configuration for the issue dependencies in that file, but it apparantly still got commited (although it is ignored).... hmmmmmmmmmm....

Apparently the folder only is ignored, not the file itself. Weired though.

**Comment by lunny** [comment]
@kolaente even if some files were added `.gitignore` they also could be added to git via `git add -f`. And after they were added, any changes will be followed by git.

**Comment by techknowlogick** [comment]
As this issue is marked as `WONTFIX` can it be closed?
