### ISSUE TITLE
When adding code comment the note suggesting markdown with octicon doesn't show the octicon

### ISSUE THREAD

**Issue by yardenshoham** [go-gitea/gitea#30082]
### Screenshots

![image](https://github.com/go-gitea/gitea/assets/20454870/b8328099-b5e7-4de9-ba6f-36a85c3ba2c6)

### Gitea Version

current main

### Can you reproduce the bug on the Gitea demo site?

Yes

### Browser Version

.

**Comment by silverwind** [comment]
Noticed a similar issue on devtest page http://localhost:3000/devtest/flex-list:

<img width="453" alt="image" src="https://github.com/go-gitea/gitea/assets/115237/cb43200f-e4ad-42d5-86e0-fd0ea6d460ff">

**Comment by silverwind** [comment]
It seems those octicons do not exist, or at least `markup` is `markdown`:

https://primer.github.io/octicons/
