### ISSUE TITLE
Update 1.21.0 to 1.21.8 on W10 fails with “unable to create mail queue”

### ISSUE THREAD

**Issue by MotronicAG** [go-gitea/gitea#30080]
### Description

Hi
Gitea runs here via Chocolatey on a W10 Server. After the Update from 1.21.0 to 1.21.7 or 1.21.8 it no longer starts…

If i start it without Admin rights (common case) it shows:
C:\Users\Server>C:\ProgramData\chocolatey\lib\gitea\tools\gitea.exe web --config “C:\ProgramData\chocolatey\lib\gitea\tools\custom\conf\app.ini”
2024/03/16 15:31:47 …etting/repository.go:292:loadRepositoryFrom() [W] SCRIPT_TYPE “bash” is not on the current PATH. Are you sure that this is the correct SCRIPT_TYPE?
2024/03/16 15:31:47 cmd/web.go:242:runWeb() [I] Starting Gitea on PID: 15012
2024/03/16 15:31:47 …etting/repository.go:292:loadRepositoryFrom() [W] SCRIPT_TYPE “bash” is not on the current PATH. Are you sure that this is the correct SCRIPT_TYPE?
2024/03/16 15:31:47 cmd/web.go:111:showWebStartupMessage() [I] Gitea version: 1.21.8 built with GNU Make 4.3, go1.21.8 : bindata, sqlite, sqlite_unlock_notify
2024/03/16 15:31:47 cmd/web.go:112:showWebStartupMessage() [I] * RunMode: prod
2024/03/16 15:31:47 cmd/web.go:113:showWebStartupMessage() [I] * AppPath: C:/ProgramData/chocolatey/lib/gitea/tools/gitea.exe
2024/03/16 15:31:47 cmd/web.go:114:showWebStartupMessage() [I] * WorkPath: C:\ProgramData\chocolatey\lib\gitea\tools
2024/03/16 15:31:47 cmd/web.go:115:showWebStartupMessage() [I] * CustomPath: C:\ProgramData\chocolatey\lib\gitea\tools\custom
2024/03/16 15:31:47 cmd/web.go:116:showWebStartupMessage() [I] * ConfigFile: C:\ProgramData\chocolatey\lib\gitea\tools\custom\conf\app.ini
2024/03/16 15:31:47 cmd/web.go:117:showWebStartupMessage() [I] Prepare to run web server
2024/03/16 15:31:48 routers/init.go:112:InitWebInstalled() [I] Git version: 2.44.0, Wire Protocol Version 2 Enabled (home: C:\ProgramData\chocolatey\lib\gitea\tools\data\home)
2024/03/16 15:31:48 …les/setting/cache.go:75:loadCacheFrom() [I] Cache Service Enabled
2024/03/16 15:31:48 …les/setting/cache.go:90:loadCacheFrom() [I] Last Commit Cache Service Enabled
2024/03/16 15:31:48 …s/setting/session.go:77:loadSessionFrom() [I] Session Service Enabled
2024/03/16 15:31:48 …es/setting/mailer.go:203:loadMailerFrom() [W] connecting over insecure SMTP protocol to non-local address is not recommended
2024/03/16 15:31:48 …es/setting/mailer.go:237:loadMailerFrom() [I] Mail Service Enabled
2024/03/16 15:31:48 …s/storage/storage.go:176:initAttachments() [I] Initialising Attachment storage with type: local
2024/03/16 15:31:48 …les/storage/local.go:33:NewLocalStorage() [I] Creating new Local Storage at C:\ProgramData\chocolatey\lib\gitea\tools\data\attachments
2024/03/16 15:31:48 …s/storage/storage.go:166:initAvatars() [I] Initialising Avatar storage with type: local
2024/03/16 15:31:48 …les/storage/local.go:33:NewLocalStorage() [I] Creating new Local Storage at C:\ProgramData\chocolatey\lib\gitea\tools\data\avatars
2024/03/16 15:31:48 …s/storage/storage.go:192:initRepoAvatars() [I] Initialising Repository Avatar storage with type: local
2024/03/16 15:31:48 …les/storage/local.go:33:NewLocalStorage() [I] Creating new Local Storage at C:\ProgramData\chocolatey\lib\gitea\tools\data\repo-avatars
2024/03/16 15:31:48 …s/storage/storage.go:186:initLFS() [I] Initialising LFS storage with type: local
2024/03/16 15:31:48 …les/storage/local.go:33:NewLocalStorage() [I] Creating new Local Storage at O:\GitLfs
2024/03/16 15:31:48 …s/storage/storage.go:198:initRepoArchives() [I] Initialising Repository Archive storage with type: local
2024/03/16 15:31:48 …les/storage/local.go:33:NewLocalStorage() [I] Creating new Local Storage at C:\ProgramData\chocolatey\lib\gitea\tools\data\repo-archive
2024/03/16 15:31:48 …s/storage/storage.go:208:initPackages() [I] Initialising Packages storage with type: local
2024/03/16 15:31:48 …les/storage/local.go:33:NewLocalStorage() [I] Creating new Local Storage at C:\ProgramData\chocolatey\lib\gitea\tools\data\packages
2024/03/16 15:31:48 …s/storage/storage.go:219:initActions() [I] Initialising Actions storage with type: local
2024/03/16 15:31:48 …les/storage/local.go:33:NewLocalStorage() [I] Creating new Local Storage at C:\ProgramData\chocolatey\lib\gitea\tools\data\actions_log
2024/03/16 15:31:48 …s/storage/storage.go:223:initActions() [I] Initialising ActionsArtifacts storage with type: local
2024/03/16 15:31:48 …les/storage/local.go:33:NewLocalStorage() [I] Creating new Local Storage at C:\ProgramData\chocolatey\lib\gitea\tools\data\actions_artifacts
2024/03/16 15:31:58 …les/queue/manager.go:108:]() [E] Failed to create queue “mail”: unable to open level db at C:/ProgramData/chocolatey/lib/gitea/tools/data/queues/common: Zugriff verweigert
2024/03/16 15:31:58 …ces/mailer/mailer.go:424:NewContext() [F] Unable to create mail queue

And with admin rights:
C:\WINDOWS\system32>C:\ProgramData\chocolatey\lib\gitea\tools\gitea.exe web --config “C:\ProgramData\chocolatey\lib\gitea\tools\custom\conf\app.ini”
2024/03/16 15:29:21 …etting/repository.go:292:loadRepositoryFrom() [W] SCRIPT_TYPE “bash” is not on the current PATH. Are you sure that this is the correct SCRIPT_TYPE?
2024/03/16 15:29:21 cmd/web.go:242:runWeb() [I] Starting Gitea on PID: 13956
2024/03/16 15:29:21 …etting/repository.go:292:loadRepositoryFrom() [W] SCRIPT_TYPE “bash” is not on the current PATH. Are you sure that this is the correct SCRIPT_TYPE?
2024/03/16 15:29:21 cmd/web.go:111:showWebStartupMessage() [I] Gitea version: 1.21.8 built with GNU Make 4.3, go1.21.8 : bindata, sqlite, sqlite_unlock_notify
2024/03/16 15:29:21 cmd/web.go:112:showWebStartupMessage() [I] * RunMode: prod
2024/03/16 15:29:21 cmd/web.go:113:showWebStartupMessage() [I] * AppPath: C:/ProgramData/chocolatey/lib/gitea/tools/gitea.exe
2024/03/16 15:29:21 cmd/web.go:114:showWebStartupMessage() [I] * WorkPath: C:\ProgramData\chocolatey\lib\gitea\tools
2024/03/16 15:29:21 cmd/web.go:115:showWebStartupMessage() [I] * CustomPath: C:\ProgramData\chocolatey\lib\gitea\tools\custom
2024/03/16 15:29:21 cmd/web.go:116:showWebStartupMessage() [I] * ConfigFile: C:\ProgramData\chocolatey\lib\gitea\tools\custom\conf\app.ini
2024/03/16 15:29:21 cmd/web.go:117:showWebStartupMessage() [I] Prepare to run web server
2024/03/16 15:29:22 routers/init.go:112:InitWebInstalled() [I] Git version: 2.44.0, Wire Protocol Version 2 Enabled (home: C:\ProgramData\chocolatey\lib\gitea\tools\data\home)
2024/03/16 15:29:22 …les/setting/cache.go:75:loadCacheFrom() [I] Cache Service Enabled
2024/03/16 15:29:22 …les/setting/cache.go:90:loadCacheFrom() [I] Last Commit Cache Service Enabled
2024/03/16 15:29:22 …s/setting/session.go:77:loadSessionFrom() [I] Session Service Enabled
2024/03/16 15:29:22 …es/setting/mailer.go:203:loadMailerFrom() [W] connecting over insecure SMTP protocol to non-local address is not recommended
2024/03/16 15:29:22 …es/setting/mailer.go:237:loadMailerFrom() [I] Mail Service Enabled
2024/03/16 15:29:22 …s/storage/storage.go:176:initAttachments() [I] Initialising Attachment storage with type: local
2024/03/16 15:29:22 …les/storage/local.go:33:NewLocalStorage() [I] Creating new Local Storage at C:\ProgramData\chocolatey\lib\gitea\tools\data\attachments
2024/03/16 15:29:22 …s/storage/storage.go:166:initAvatars() [I] Initialising Avatar storage with type: local
2024/03/16 15:29:22 …les/storage/local.go:33:NewLocalStorage() [I] Creating new Local Storage at C:\ProgramData\chocolatey\lib\gitea\tools\data\avatars
2024/03/16 15:29:22 …s/storage/storage.go:192:initRepoAvatars() [I] Initialising Repository Avatar storage with type: local
2024/03/16 15:29:22 …les/storage/local.go:33:NewLocalStorage() [I] Creating new Local Storage at C:\ProgramData\chocolatey\lib\gitea\tools\data\repo-avatars
2024/03/16 15:29:22 …s/storage/storage.go:186:initLFS() [I] Initialising LFS storage with type: local
2024/03/16 15:29:22 …les/storage/local.go:33:NewLocalStorage() [I] Creating new Local Storage at O:\GitLfs
2024/03/16 15:29:22 …s/storage/storage.go:198:initRepoArchives() [I] Initialising Repository Archive storage with type: local
2024/03/16 15:29:22 …les/storage/local.go:33:NewLocalStorage() [I] Creating new Local Storage at C:\ProgramData\chocolatey\lib\gitea\tools\data\repo-archive
2024/03/16 15:29:22 …s/storage/storage.go:208:initPackages() [I] Initialising Packages storage with type: local
2024/03/16 15:29:22 …les/storage/local.go:33:NewLocalStorage() [I] Creating new Local Storage at C:\ProgramData\chocolatey\lib\gitea\tools\data\packages
2024/03/16 15:29:22 …s/storage/storage.go:219:initActions() [I] Initialising Actions storage with type: local
2024/03/16 15:29:22 …les/storage/local.go:33:NewLocalStorage() [I] Creating new Local Storage at C:\ProgramData\chocolatey\lib\gitea\tools\data\actions_log
2024/03/16 15:29:22 …s/storage/storage.go:223:initActions() [I] Initialising ActionsArtifacts storage with type: local
2024/03/16 15:29:22 …les/storage/local.go:33:NewLocalStorage() [I] Creating new Local Storage at C:\ProgramData\chocolatey\lib\gitea\tools\data\actions_artifacts
2024/03/16 15:29:22 routers/init.go:131:InitWebInstalled() [I] SQLite3 support is enabled
2024/03/16 15:29:22 routers/common/db.go:23:InitDBEngine() [I] Beginning ORM engine initialization.
2024/03/16 15:29:22 routers/common/db.go:30:InitDBEngine() [I] ORM engine initialization attempt #1/10…
2024/03/16 15:29:22 cmd/web.go:194:serveInstalled() [I] PING DATABASE sqlite3
2024/03/16 15:29:22 cmd/web.go:194:serveInstalled() [W] Table system_setting Column version db default is , struct default is 1
2024/03/16 15:29:22 cmd/web.go:194:serveInstalled() [W] Table project Column card_type db default is 0, struct default is
2024/03/16 15:29:22 cmd/web.go:194:serveInstalled() [W] Table project Column card_type db nullable is false, struct nullable is true
2024/03/16 15:29:22 cmd/web.go:194:serveInstalled() [W] Table hook_task has column repo_id but struct has not related field
2024/03/16 15:29:22 routers/init.go:137:InitWebInstalled() [I] ORM engine initialization successful!
2024/03/16 15:29:22 …er/issues/indexer.go:77:func1() [I] PID 13956: Initializing Issue Indexer: bleve
2024/03/16 15:29:22 …xer/stats/indexer.go:39:populateRepoIndexer() [I] Populating the repo stats indexer with existing repositories
2024/03/16 15:29:22 …er/issues/indexer.go:97:func1() [F] Unable to initialize Bleve Issue Indexer at path: C:/ProgramData/chocolatey/lib/gitea/tools/data/indexers/issues.bleve Error: cannot open index, metadata missing

I tried this:
https://github.com/go-gitea/gitea/issues/28388
But with no success. Any ideas?

Thanks
Ralf

### Gitea Version

1.21.0

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

2.44.0

### Operating System

W10 Pro 10.0.19045

### How are you running Gitea?

Gitea is installed via chocolatey.

### Database

SQLite

**Comment by wxiaoguang** [comment]
It seems a different problem

```
2024/03/16 15:29:22 …er/issues/indexer.go:97:func1() [F] Unable to initialize Bleve Issue Indexer at path: C:/ProgramData/chocolatey/lib/gitea/tools/data/indexers/issues.bleve Error: cannot open index, metadata missing
```

Maybe the bleve data is corrupted. So maybe it needs to remove the `data/indexers/issues.bleve`

**Comment by MotronicAG** [comment]
Hi
After removing `data/indexers/issues.bleve` it worked perfect again!
Thanks!
