### ISSUE TITLE
The location of buttons in wiki home page is wrong?

### ISSUE THREAD

**Issue by yp05327** [go-gitea/gitea#30097]
### Description

![image](https://github.com/go-gitea/gitea/assets/18380374/20ffddb1-76ac-4ee8-99ad-0689f7cbd752)

### Gitea Version

latest

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

build

### Database

None

**Comment by silverwind** [comment]
Looks a regression from https://github.com/go-gitea/gitea/pull/29894, I will investigate. Looks this CSS is missing:

```css
.ui[class*="right aligned"].grid > .column,
.ui[class*="right aligned"].grid > .row > .column,
.ui.grid > [class*="right aligned"].row > .column,
.ui.grid > [class*="right aligned"].column.column,
.ui.grid > .row > [class*="right aligned"].column.column {
  text-align: right;
  align-self: inherit;
}
