### ISSUE TITLE
View at this point in history is 404 in wiki revisions page

### ISSUE THREAD

**Issue by yp05327** [go-gitea/gitea#30098]
### Description

- access:
https://try.gitea.io/yp05327/longlonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglong/wiki/Home?action=_revision
- click the button:
![image](https://github.com/go-gitea/gitea/assets/18380374/0d68702c-559e-4304-ba91-a5f5c9c97309)
- you will see 404 page
![image](https://github.com/go-gitea/gitea/assets/18380374/31820c6c-3255-4177-bf14-249f0934df20)

maybe we need to hide this button in wiki page?

### Gitea Version

latest

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

build

### Database

None

**Comment by lunny** [comment]
Maybe hiding it is a quick fix.

**Comment by wxiaoguang** [comment]
->  Revert "Show View at this point in history for every commit (#29122)" #30295
