### ISSUE TITLE
Add a website at gitea.io

### ISSUE THREAD

**Issue by auuuuuzzzzzpallauzzzzz** [go-gitea/gitea#301]
Why isn't there a website like gogs.io?

**Comment by tboerger** [comment]
Because it's a work in progress. The website will be automatically published when we add content to https://github.com/go-gitea/website, https://github.com/go-gitea/docs, https://github.com/go-gitea/blog and https://github.com/go-gitea/redirects.

**Comment by strk** [comment]
Meaning: there *is* a website (gitea.io) - only not nice yet.
Want to help ?
