### ISSUE TITLE
Author name not in the middle in commit list page

### ISSUE THREAD

**Issue by yp05327** [go-gitea/gitea#30129]
### Description

https://github.com/go-gitea/gitea/pull/29989#issuecomment-2022058844

### Gitea Version

latest

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

build

### Database

None

**Comment by lunny** [comment]
I don't think it's a bug. I think it's OK to not vertical center aligned.

**Comment by yp05327** [comment]
Before #29989, it was. So the behavior changed unexpected, as this PR is just for fixing different username color.

**Comment by silverwind** [comment]
I guess we can fix it.

**Comment by silverwind** [comment]
@yp05327 it seems best to revert `tw-flex` because table cells with display: flex behave strangely. Can you try solving the whitespace issue by just removing it in the HTML template instead where appropriate?

**Comment by yp05327** [comment]
In template, there was no whitespace, but in browser, there was.
And I don't know why, now I can't see whitespace. 😕 
![image](https://github.com/go-gitea/gitea/assets/18380374/60d9edb8-a650-4732-9993-783bda24c8d0)
