### ISSUE TITLE
`Generic Package Registry` should allow `:` to support archlinux `pacman`

### ISSUE THREAD

**Issue by loynoir** [go-gitea/gitea#30134]
### Feature Description

`Generic Package Registry` should support archlinux `pacman`

https://docs.gitea.com/usage/packages/generic

>  The filename. It can contain only lowercase letters (a-z), uppercase letter (A-Z), numbers (0-9), dots (.), hyphens (-), pluses (+), or underscores (_).

For example, archlinux `core` repo contains `:`.

https://geo.mirror.pkgbuild.com/core/os/x86_64/

> dialog-1:1.3_20240101-1-x86_64.pkg.tar.zst
dialog-1:1.3_20240101-1-x86_64.pkg.tar.zst.sig
grub-2:2.12-2-x86_64.pkg.tar.zst
grub-2:2.12-2-x86_64.pkg.tar.zst.sig
iptables-1:1.8.10-1-x86_64.pkg.tar.zst
iptables-1:1.8.10-1-x86_64.pkg.tar.zst.sig
iptables-nft-1:1.8.10-1-x86_64.pkg.tar.zst
iptables-nft-1:1.8.10-1-x86_64.pkg.tar.zst.sig
less-1:643-1-x86_64.pkg.tar.zst
less-1:643-1-x86_64.pkg.tar.zst.sig
lz4-1:1.9.4-3-x86_64.pkg.tar.zst
lz4-1:1.9.4-3-x86_64.pkg.tar.zst.sig
minizip-1:1.3.1-1-x86_64.pkg.tar.zst
minizip-1:1.3.1-1-x86_64.pkg.tar.zst.sig
vi-1:070224-6-x86_64.pkg.tar.zst
vi-1:070224-6-x86_64.pkg.tar.zst.sig
wpa_supplicant-2:2.10-8-x86_64.pkg.tar.zst
wpa_supplicant-2:2.10-8-x86_64.pkg.tar.zst.sig
zlib-1:1.3.1-1-x86_64.pkg.tar.zst
zlib-1:1.3.1-1-x86_64.pkg.tar.zst.sig

Would be nice 

- or let `Generic Package Registry`  to allow `:`.

- or support `Pacman Package Registry`.

**Comment by wxiaoguang** [comment]
agree to relax the filename checking.

-> Relax generic package filename check #30135
