### ISSUE TITLE
JS error when loading more lines in diff view

### ISSUE THREAD

**Issue by M393** [go-gitea/gitea#30141]
### Description

This error happens when clicking multiple times in a row on the load-more-lines button:
```
repo-code.js:195 Uncaught (in promise) DOMException: Failed to set the 'outerHTML' property on 'Element': This element has no parent node.
    at http://vmlinux03data:3000/assets/js/index.js?v=1.21.10:101:15689
    at Generator.next (<anonymous>)
    at u (http://vmlinux03data:3000/assets/js/index.js?v=1.21.10:101:12477)
```
Url path: `/[org]/[project]/commit/[commit-hash]`

### Gitea Version

1.21.10

### Can you reproduce the bug on the Gitea demo site?

No.
Looks like the button gets disabled while loading more text with 1.22, so could not reproduce it there.

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/56256405/f41c7780-6fe8-4479-b9c2-a405cb45a61f)

### Git Version

2.20.1

### Operating System

Debian 10

### How are you running Gitea?

Downloaded `gitea-1.21.10-linux-amd64` from release page

### Database

MySQL/MariaDB

**Comment by yp05327** [comment]
> Looks like the button gets disabled while loading more text with 1.22, so could not reproduce it there.

Yes, as this has been fixed in #29385 by using htmx instead of jQuery, plz wait the new release of v1.22.
I will close this issue, feel free to reopen if you have more questions.
