### ISSUE TITLE
Newly pushed branches and issue track number on commit messages not appearing since upgrade to 1.21.7

### ISSUE THREAD

**Issue by twostarsmco** [go-gitea/gitea#30157]
### Description

We upgraded Gitea from 1.16.x to 1.21.7.
Initially it appeared to be working fine until we had noticed the following problems:

#### Newly pushed branches are not appearing on Gitea. 
As per the title; they are accessible with `git` command but not appearing on Gitea's web interface. Running "Sync missed branches from git data to databases" on admin Dashboard temporary fixes issue. However, any branches pushed after that are not appearing so I have to push that button every time there's a new branch pushed.

#### Commits with issue tracking number on its messages are not appearing on corresponding issue.
Before the upgrade, if a commit contains a string "#(number)", that commit is automatically shown at the bottom of correspnding issues / PR . They are no longer showing up.

### What we've noticed

- I am aware of [#28056#issuecomment-1811664310](https://github.com/go-gitea/gitea/issues/28056#issuecomment-1811664310). As per above, it does not fix the issue permanently.
- The problems occure on newly created repository after the upgrade.
- Around the time branch is pushed, Gitea logs `401 Unauthorized` (see log gist).

I suspect there is some incorrect configuration somewhere, that became relevant only in the recent version. I am attaching relevant part of `app.ini` for Gitea, `docker-compose.yml`, and `default.conf` for Nginx.

[app.ini.txt](https://github.com/go-gitea/gitea/files/14788446/app.ini.txt)
[default.conf.txt](https://github.com/go-gitea/gitea/files/14788447/default.conf.txt)
[docker-compose.yml.txt](https://github.com/go-gitea/gitea/files/14788448/docker-compose.yml.txt)

### Gitea Version

1.21.7

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/twostarsmco/7243cdfb5a864e8f9735c4589bb78a4c

### Git Version

2.40.1

### Operating System

Linux

### How are you running Gitea?

On our internal server, using official Docker image, along with Docker-Compose and Nginx.
Gitea is accessible through sub-path like `http://mydomain.example.com/git/`

### Database

SQLite

**Comment by lunny** [comment]
Please run `Resynchronize pre-receive, update and post-receive hooks of all repositories.` before run `Sync missed branches from git data to databases` and `Sync tags from git data to database`

**Comment by lunny** [comment]
You can also run `./gitea doctor` to detect possible errors.

**Comment by twostarsmco** [comment]
We ran all three maintenance operations but problem still persists. (Does `Sync tags from git data to database` refer to [this command](https://docs.gitea.com/next/help/faq#missing-releases-after-migrating-repository-with-tags)?)

`gitea doctor check` shows OK for all 5 checks.
I also tried `gitea doctor recreate-table`. It shows one warning:

> ...2@v2.25.7/command.go:267:Run() [W] Table system_setting Column version db default is , struct default is 1

I will try creating new clean container of Gitea, with and without the Nginx to isolate the problem. If there is anything I can do to diagnose the problem, please let me know.

**Comment by twostarsmco** [comment]
The problem did reproduce on new container (with v1.21.7 and v1.21.10 image), but NOT when I used v1.16 image.

Steps to reproduce:

1. Create a local git repository with `main` and `develop` branches.
2. Switch to `develop` branch, change something, and then `git commit -m "#1"`.
3. On server, execute `docker-compose up -d` using the following `docker-compose.yml`.
```yml
version: '3.5'
services:
  gitea:
    container_name: giteatest
    image: gitea/gitea:1.16
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    ports:
      - 3001:3000
```
4. Create a new repository on Gitea. Set it as `origin` on local repo.
5. Create an issue `#1` on Gitea.
6. Push local `main` branch to `origin`. (Note that `main` appears on Gitea on all versions.)
7. Push local `develop` branch to `origin`.
8. Check if `develop` branch appears on Gitea, and if the commit on `develop` branch can be referenced on issue `#1`.
9. Edit `docker-compose.yml`, change the version of image, and try the steps above again.

**Comment by wxiaoguang** [comment]
Thank you for your detailed report!

Could you share 2 screenshots of `Newly pushed branches shown` and `Commits with issue tracking number shown`? It could help to quickly understand the problem and we could focus on the same problem. I will take a look.

**Comment by twostarsmco** [comment]
My apologies, it was because `docker` on our server was out of date.

I went through Gitea's release notes and found that docker version >= 20.10.6 is now required since v1.17.0. Updated the package, problems seems to be gone for now. I would like to keep eye on it for a day or two, then close this issue.

Thank you anyway for your assistance.
