### ISSUE TITLE
Large gitea-actions stops running at ~3hours

### ISSUE THREAD

**Issue by CkovMk** [go-gitea/gitea#30161]
### Description

I'm running gitea-actions for some linux image building task. It takea hours to finish on a regular machine. The gitea-action job stops at around 3 hours after begin, without any reported error on the webui. Build a smaller image, if the job is able to complete within 3 hours, it runs successfully. I already allocate an 12-core VM on a modern CPU to run the actions, there's almost no way I could increase the performance.

Is there a hard limit on how long a single job can run? Is there any way to configure the limit?

(not sure if this is the right place to report bugs about actions / runners...)
Thanks

### Gitea Version

1.21.6

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/29831136/c6ad628f-bba9-4fd8-80a6-af89fd787f90)

### Operating System

Debian bullseye

### How are you running Gitea?

Official docker image

### Database

MySQL/MariaDB

**Comment by dav64** [comment]
I think you have kept the default actions timeout

Take a look at the config file and update the `ENDLESS_TASK_TIMEOUT`
https://docs.gitea.com/administration/config-cheat-sheet?_highlight=config#actions-actions

**Comment by CkovMk** [comment]
That is the solution. Thanks

**Comment by corpix** [comment]
Will add more context, because I has been hit by same behavior. In my case increasing `ENDLESS_TASK_TIMEOUT` was not enough because runner has [it's own](https://gitea.com/gitea/act_runner/src/commit/d1d3cad4b0bfd0bfc5df344306f304043ff63223/internal/pkg/config/config.example.yaml#L25) `runner.timeout` setting
