### ISSUE TITLE
Always need manual trigger "Sync missed branches from git data to databases"

### ISSUE THREAD

**Issue by maxid** [go-gitea/gitea#30164]
### Description

Always need manual trigger "Sync missed branches from git data to databases" fixed create new branch missing

### Gitea Version

1.21.4 ~1.21.8

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

Always need manual trigger "Sync missed branches from git data to databases" fixed create new branch missing### 

### Git Version

2.40.1

### Operating System

centos 7

### Gitea Version
1.21.8 built with GNU Make 4.4.1, go1.21.8 : bindata, timetzdata, sqlite, sqlite_unlock_notify
### Git Version
2.40.1, Wire Protocol Version 2 Enabled
### Repo Count	
265
### System Status
|||
| ---- | ----|
|Current Goroutines|69|
Current Memory Usage|82 MiB
Total Memory Allocated|98 GiB
Memory Obtained|238 MiB
Pointer Lookup Times|0
Memory Allocations|2204340482
Memory Frees|2203820486
Current Heap Usage|82 MiB
Heap Memory Obtained|214 MiB
Heap Memory Idle|108 MiB
Heap Memory In Use|106 MiB
Heap Memory Released|75 MiB
Heap Objects|519996
Bootstrap Stack Usage|2.4 MiB
Stack Memory Obtained|2.4 MiB
MSpan Structures Usage|1.3 MiB
MSpan Structures Obtained|2.6 MiB
MCache Structures Usage|4.7 KiB
MCache Structures Obtained|15 KiB
Profiling Bucket Hash Table Obtained|8.1 MiB
GC Metadata Obtained|10 MiB
Other System Allocation Obtained|1.1 MiB
Next GC Recycle|159 MiB
Since Last GC Time|69.4s
Total GC Pause|1.5s
Last GC Pause|0.000s
GC Times|9505

### Database

SQLite

**Comment by lunny** [comment]
Please run `Sync hooks` task on admin panel first.

**Comment by maxid** [comment]
not work

**Comment by lunny** [comment]
Can you find more logs or run gitea doctor to get some results?
