### ISSUE TITLE
Ownership transfer "awaits confirmation" despite me being an Organization owner

### ISSUE THREAD

**Issue by flyingstar16** [go-gitea/gitea#30187]
### Description

I run a single-user Gitea instance with a couple of organizations (of which I'm the only admin) that I use for "categorizing" my repositories.

I realized today that when I transfer a repository to it the confirmation message is

> This repository has been marked for transfer and awaits confirmation from "`<org name>`"

even though there is no transfer confirmation needed (or, indeed, requested).

This message may confuse users and should only be displayed if the confirmation has been requested by the new owner(s).

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/582280/85b55629-ffc8-47f4-b687-e0d034941f35)

### Gitea Version

1.21.9

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

Debian

### Browser Version

Firefox 115.8.0esr (64-bit)

**Comment by netzwerkgoettin** [comment]
Hi,

same here for gitea:1.21.11 (Docker).
Nothing serious, just a little confusing 🙂

Cheers,
  Marianne

**Comment by flyingstar16** [comment]
Thank you!
