### ISSUE TITLE
Action running in archived repository

### ISSUE THREAD

**Issue by Sirherobrine23** [go-gitea/gitea#30220]
### Description

Actions running in archived repositores, if not are to run

### Gitea Version

latest

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/50121801/c46c15eb-2ad1-40ad-8efc-ee604f40d69c)

### Git Version

2.34.1

### Operating System

Ubuntu

### How are you running Gitea?

custom build to Ubuntu server

### Database

SQLite

**Comment by lunny** [comment]
You can disable actions as workaround.
