### ISSUE TITLE
enable usage of absolute urls for reusable workflows

### ISSUE THREAD

**Issue by jonas-switala** [go-gitea/gitea#30246]
### Feature Description

Reusing workflows seems quite similar to reusing actions at first glance. They share several common issues. For example:
- Accessing workflows/actions from private repositories
- Distinguishing workflows/actions hosted on github.com or locally  

For actions, this issue can be resolved by using absolute URLs (As described here https://docs.gitea.com/next/usage/actions/comparison#absolute-action-urls) and embedding the access token (As described in https://github.com/go-gitea/gitea/issues/25929)
However, this is currently not supported for reusable workflows:

calling workflow snippet:
```
### jobs:
  validate-manifests:
    uses: https://${{ secrets.GITHUB_TOKEN }}:{instance}/{owner}/{repo}/.gitea/workflows/validate.yaml@v1.0.0
```
output:
```
expected format {owner}/{repo}/.{git_platform}/workflows/{filename}@{ref}. Actual 'https://${{ secrets.GITHUB_TOKEN }}:{instance}/{owner}/{repo}/.gitea/workflows/validate.yaml@v1.0.0' Input string was not in a correct format
```

This leads to several inconveniences when working with reusable workflows or even makes them unusable for some use cases:
- reusable workflows can't be hosted in private repos since there is no way to use a token with sufficient permissions
- the only way to use reusable workflows not hosted publically on github.com is to set DEFAULT_ACTIONS_URL=self which
  - requires absolute URLs for all GitHub-hosted actions on the Gitea instance (which might be the majority of actions)
  - prohibts users from using reusable workflows hosted on github.com, since without absolute URLs there is no way to specify where a reusable workflow might be hosted
 
# Possible Solution
I think the cleanest way to solve this is to make the same URL options available for reusable workflows that are already implemented for actions (e.g. absolute URLs with embedded tokens)

**Comment by silverwind** [comment]
Indeed we have to support the same URL prefix mechanism like we do on actions, e.g. assume a `https://github.com` for unprefixed URLs.

**Comment by Zettat123** [comment]
Hi @jonas-switala , using absolute URLs for reusable workflows is already supported by [gitea/act#104](https://gitea.com/gitea/act/pulls/104). Could you try the new version of `act_runner`?

**Comment by jonas-switala** [comment]
I finally found some time to test this and can confirm that the absolute URLs work (using gitea v1.22.3 and act-runner v0.2.10). I still have some problems using the embedded token for auth, but I think that is a better fit for this issue: https://github.com/go-gitea/gitea/issues/25929.
As far as I am concerned this issue can be treated as fixed. Thanks to everyone involved :)
