### ISSUE TITLE
Github actions are shown at gitea actions when the reposity is a github mirror.

### ISSUE THREAD

**Issue by yekanchi** [go-gitea/gitea#30244]
### Description

if you mirror a repository from Github to Giteaand you have some Github actions. they yml files and some running history of Github actions are show inside the Gitea actions tab, I think it's weird.

### Gitea Version

1.22 dev

### Operating System
windows

### How are you running Gitea?
local

**Comment by lunny** [comment]
I don't think we have migrated the history actions tasks log. Maybe it triggered the actions when migrating.

**Comment by yekanchi** [comment]
> I don't think we have migrated the history actions tasks log. Maybe it triggered the actions when migrating.

I checked again, yes it's triggered, it's not migrated.

**Comment by yekanchi** [comment]
this is an example , a mirror repository of cache actions in local gitea casues actions to show up. whie the local repository has disabled actions.
![image](https://github.com/go-gitea/gitea/assets/25511175/ce28fcb2-b3de-4f21-b42b-808834400b47)

![image](https://github.com/go-gitea/gitea/assets/25511175/0ae96835-106d-4655-b96c-d4b6c2ffc544)

**Comment by Zettat123** [comment]
This is weird. I noticed that there are some scheduled workflows in this repository. I guess some of the scheduled workflows might be running after the migration and before disabling Actions.

And I agree that we should disable Actions for mirror repositories by default (#30350)

**Comment by somera** [comment]
I have same problem.

**Comment by Zettat123** [comment]
You can use the doctor command added in #32424 to disable "Actions" unit for mirrors.

**Comment by lunny** [comment]
Sorry, I think this hasn't been backported to v1.22.4 @Zettat123

**Comment by somera** [comment]
It's ok. ;) I have my python script to patch this. ;)
