### ISSUE TITLE
cannot disable swagger

### ISSUE THREAD

**Issue by relikd** [go-gitea/gitea#30254]
### Description

1) set `ENABLE_SWAGGER = false`
2) `systemctl restart gitea`
3) API is still enabled

### Gitea Version

1.21.10

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

Arch

### How are you running Gitea?

pacman gitea binary

### Database

SQLite

**Comment by techknowlogick** [comment]
Swagger is a UI for easy API documentation. Disabling swagger does not disable the API. The API is required for application functionality.

**Comment by relikd** [comment]
Actually, I was refering to the config parameter. ... But I was about to close this issue anyway. Apparently I forgot to uncomment the "[api]" header. With the header set, the API is disabled as the config comment suggests.
