### ISSUE TITLE
loadOrCreateAsymmetricKey called when oauth2 is disabled

### ISSUE THREAD

**Issue by pboguslawski** [go-gitea/gitea#30266]
### Description

When oauth2 is disabled in config with
```
[oauth2]
ENABLE = false
```
gitea is still trying to generate private key using jwtsigningkey.go:386:loadOrCreateAsymmetricKey(). Shouldn't [`oauth2.Init`](https://github.com/go-gitea/gitea/blob/1195be41a13d2198ab644c8558549edd74485510/routers/init.go#L140) be skipped in this scenario?

### Gitea Version

1.21.10

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

compiled from sources

### Database

MySQL/MariaDB

**Comment by lunny** [comment]
I think some codes mixed Gitea as OAuth2 provider and Gitea as OAuth2 client.

**Comment by hawicz** [comment]
It also creates the private key in the wrong path.  Here's a patch that fixes both of those problems
[oauth_init.patch](https://github.com/user-attachments/files/16054350/oauth_init.patch)

**Comment by lunny** [comment]
> It also creates the private key in the wrong path. Here's a patch that fixes both of those problems [oauth_init.patch](https://github.com/user-attachments/files/16054350/oauth_init.patch)

I cannot reproduce the error that the private.key in the wrong place.
