### ISSUE TITLE
webauthn failed with error 500 after upgrade to 1.21.10

### ISSUE THREAD

**Issue by olivn** [go-gitea/gitea#30271]
### Description

After upgrade to 1.21.10 from 1.21.7 webauthn authentications fail with error 500

x

### Gitea Version

 1.21.10 built with GNU Make 4.3, go1.21.8 : bindata, sqlite, sqlite_unlock_notify

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/olivn/dec559a9e16b39086f9293f3ab10e3ab

### Git Version

git version 2.35.3

### How are you running Gitea?

running  binary gitea-1.21.10-linux-amd64 downloaded from https://dl.gitea.com/gitea/1.21.10/

### Database

SQLite

**Comment by olivn** [comment]
Webauthn  is also failing in versions gitea-1.21.9-linux-amd64 and gitea-1.21.8-linux-amd64.
Reverting to gitea-1.21.7-linux-amd64 is OK

**Comment by techknowlogick** [comment]
Are you using Gitea under a subpath? As well, could you try in incognito mode?

**Comment by olivn** [comment]
Are you using Gitea under a subpath?      YES
As well, could you try in incognito mode?  working for Incognito mode

**Comment by wxiaoguang** [comment]
> As well, could you try in incognito mode? working for Incognito mode

It's caused by inconsistent cookie path " Fix incorrect cookie path for AppSubURL (#29534) #29552 ", clear existing cookie could resolve the problem.

**Comment by olivn** [comment]
Purging the cookies has fixed the problem.
Thanks
