### ISSUE TITLE
Code markup style regression

### ISSUE THREAD

**Issue by KN4CK3R** [go-gitea/gitea#30292]
The inner background is new. Don't know if that is intended but here it looks strange:
![grafik](https://github.com/go-gitea/gitea/assets/1666336/75535ef5-c4a0-432c-bc86-fa78ab7006f5)

**Comment by wxiaoguang** [comment]
Related to  Render embedded code preview by permlink in markdown #30234  ?

It changed some "markup code" styles.

**Comment by wxiaoguang** [comment]
Well, it is, there is a really annoying CSS style overriding game.

**Comment by wxiaoguang** [comment]
->  Refactor markup code block styles #30294

**Comment by wxiaoguang** [comment]
> -> Refactor markup code block styles #30294

Update: I give up
