### ISSUE TITLE
Can't autenticate via LDAP

### ISSUE THREAD

**Issue by cccaballero** [go-gitea/gitea#3029]
- Gitea version (or commit ref): 1.2.3
- Git version: 2.11.0
- Operating system: Debian
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

2017/11/29 16:18:24 [T] Dialing LDAP with security protocol (0) without verifying: false
2017/11/29 16:18:24 [T] LDAP will bind directly via UserDN template: dc=cfg
2017/11/29 16:18:24 [T] Binding with userDN: dc=cfg%!(EXTRA string=carlos.caballero)
2017/11/29 16:18:24 [D] LDAP auth. failed for dc=cfg%!(EXTRA string=carlos.caballero), reason: LDAP Result Code 49 "Invalid Credentials": 
2017/11/29 16:18:24 [W] Failed to login 'carlos.caballero' via 'LDAP JC': user does not exist [uid: 0, name: carlos.caballero, keyid: 0]

## Description

I have configured LDAP (simple auth) authentication and I am not able to login, the login page always says: "Incorrect username or password.". There is some weird log messages.

**Comment by robe2** [comment]
I was having similar problems too.  Mine turned out to be because I had another account with same email address as one I had for the LDAP I was trying to log in with.

Though I never turned on logging to confirm, but worked after I changed email address of the local account.

I should add I was using gitea 1.3.0rc2

**Comment by lafriks** [comment]
you seems to have wrong settings. Can you add screenshot of ldap login source settings?

**Comment by cccaballero** [comment]
![screenshot-code cfg jovenclub cu-2017-11-29-14-03-39](https://user-images.githubusercontent.com/3727802/33393810-62b9a2ec-d50e-11e7-9347-21f406503651.png)

**Comment by cccaballero** [comment]
Hi guys, I still can't configure gitea to use the LDAP. 
If I use a tool like JXplorer and set dc=cfg as user dn and (&(objectClass=posixAccount)(uid=myusername)) as filter it finds the user with "myusername" as username. But in the gitea config using dc=cfg as User DN and (&(objectClass=posixAccount)(uid=%s)) as User Filter, it still not log in throwing the same messages in logs.
I have attached an example of the LDAP structure
![ladp tree](https://user-images.githubusercontent.com/3727802/34732934-b16c6e60-f534-11e7-85bf-4a3e66efa4f6.png)

**Comment by lafriks** [comment]
For simple with user DN must be something like `uid=%s,ou=Users,dc=example` see more at docs: https://docs.gitea.io/en-us/authentication/

**Comment by lunny** [comment]
Closed for now and please feel free to reopen it.
