### ISSUE TITLE
Actions and mobile UI problem's 

### ISSUE THREAD

**Issue by Sirherobrine23** [go-gitea/gitea#30303]
### Description

On some pages, the buttons are misaligned from the text and remain inside it, and the actions have transparent parts that make the screen ineligible

### Screenshots

![Screenshot_20240406-042747_Chrome](https://github.com/go-gitea/gitea/assets/50121801/cacebdfd-d827-46eb-8b1c-166d9e3bc242)

![Screenshot_20240406-043326_Chrome](https://github.com/go-gitea/gitea/assets/50121801/217a52b4-16ef-41ef-bcf5-1b27d74c0649)

![Screenshot_20240406-043637_Chrome](https://github.com/go-gitea/gitea/assets/50121801/14a0172b-76d3-4ac3-be9e-0f4a6109d550)

This is same to Desktop

### Gitea Version

latest

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

Ubuntu Server

### Browser Version

123.0.6312.99 64 bits

**Comment by silverwind** [comment]
These is a regression from https://github.com/go-gitea/gitea/pull/30162 as the mobile CSS targets `input` and that element was previouly hidden but now is visible. I will fix it soon.

**Comment by silverwind** [comment]
https://github.com/go-gitea/gitea/pull/30308 and https://github.com/go-gitea/gitea/pull/30309 will fix all problems.
