### ISSUE TITLE
API add endpoint to list secrets

### ISSUE THREAD

**Issue by uvulpos** [go-gitea/gitea#30311]
### Feature Description

I want to enhance the tea cli tool to be able to manage secrets. Therefore I need an EP to list all secrets (not expose them, just list the names). Currently it is just possible to put or delete secrets. Possibly this EP exists already but is not documented.

### Screenshots

<img width="1439" alt="Screenshot 2024-04-06 at 23 44 11" src="https://github.com/go-gitea/gitea/assets/53957681/f1a26cae-1c34-490e-92fb-11d97565df3b">

**Comment by mattfysh** [comment]
for now a workaround is to create a matching variable as a pointer to the secret

**Comment by jtran** [comment]
Does PR #30656 resolve this issue? It should be in Gitea 1.22.

**Comment by uvulpos** [comment]
LGTM @jtran I think we are done here 🙂  👍🏻
