### ISSUE TITLE
Search an organization's repos

### ISSUE THREAD

**Issue by svarlamov** [go-gitea/gitea#3031]
- Gitea version (or commit ref): dab2b35

- Can you reproduce the bug at https://try.gitea.io:
Yes, on a user's page we have search and on an organization's page we have no search :cry: 
User example: https://try.gitea.io/geek1011
Org example: https://try.gitea.io/gitea

## Description

To date, I have not been able to find a way to search an organization's repositories (even if I am the owner and we have a ton of repos under the org). This is a bit annoying with a bunch of repos and it would be great to be able to search them (by name at least) same as on the user's profile page. What would this involve? I haven't looked to deep through the code on this, but I imagine it's probably just a front-end template fix?

**Comment by techknowlogick** [comment]
I feel your pain, I have a couple of orgs with >100 repos in them and I have to use the explore page to filter for the repos I need.

I'm looking into adding this now, but if I get sidetracked and someone wants to pick it up later I'll put my notes here.

It isn't just a front-end template fix, as I've added `{{template "explore/search" .}}` to right under where the "create new repo for org" button is on the org profile template (`/templates/org/home.tmpl`), and 1. it throws an error (`<eq .SortType "newest...>: error calling eq: invalid type for comparison`), and 2. if I remove the sort dropdown it shows the correct search box in the org home page, however when I enter anything and search it will just add what is needed to the URL, but won't filter the page.

So what is needed is: ensure the type of SortType is a string, has a default value of newest, and add the filtering ability to org home page route. Of course the search bar will also need to be added to the template.

**Comment by richmahn** [comment]
@techknowlogick Looking into implementing this, both for my company and upstream Gitea. Are there any reasons you found this isn't doable, or just hasn't been interest?

**Comment by lafriks** [comment]
@richmahn it was just that because of code refactoring that PRs had to be redo so it was closed but feel free to implement it in new PR

**Comment by richmahn** [comment]
@lafriks Ok, thanks. Will do.

**Comment by richmahn** [comment]
So, signaling intent to work on this issue as well. Will add any notes to this comment like @techknowlogick did above:

* Currently reviewing the previous PR that was closed to make sure I'm not missing anything needed for this to work.
