### ISSUE TITLE
When I create an issue I get an email

### ISSUE THREAD

**Issue by svarlamov** [go-gitea/gitea#3033]
- Gitea version (or commit ref): dab2b35

## Description

When I create an issue on an organization's repo where I am a watcher, I get an email that my user created an issue. I find this functionality a bit odd, and it's cluttering my inbox. What do you guys think?

**Comment by lunny** [comment]
This should be a bug.

**Comment by svarlamov** [comment]
This is also happening when I comment on my issue...

**Comment by Superpat** [comment]
The deeper issue is lack of customization in email reception. I dont mind receiving an email after creating an issue.

**Comment by mrsdizzie** [comment]
This has since been fixed
