### ISSUE TITLE
Disable Action unit by default when mirroring a repo?

### ISSUE THREAD

**Issue by yp05327** [go-gitea/gitea#30350]
### Feature Description

For a mirror, the workflows are designed for the original repo, so something like secrets would not work or some unexpected things may happen? e.g. CD run twice when there's a runner with same label and no secret checks or something which would block the CD? ( original and mirror)

**Comment by lunny** [comment]
I think it already can be disabled from the repository setting.

**Comment by yp05327** [comment]
Changed the title to `By default`

**Comment by wienans** [comment]
Similar for templates. Would be nice to disable it by default so my the devs can enable it if they added configuration but don’t need to think about disabling it when it is not used.

**Comment by yp05327** [comment]
maybe we can add an option when create a mirror repo

**Comment by wienans** [comment]
For creating a repo from template we already have many options, one checkbox more shouldn’t be a huge disruption in UX I think.

and it would be nice if the workflows itself are disabled after creating it not actions tab from the repo settings.

**Comment by lng2020** [comment]
![image](https://github.com/go-gitea/gitea/assets/70063547/827aea02-8753-4519-88f1-7748e0dee2a0)
I've already found a place(and other related code) to modify the repo unit. But I'm not sure about which unit should be included for the `mirror` and `template` repos.
Should only the `action` unit be removed or other units(`wiki`, `project`, etc) should be removed too? I think currently we do not support other units for both the `template` or `mirror` repos (although there is a PR that tried to mirror other staff IIRC)

**Comment by lng2020** [comment]
Or should we turn `DefaultTemplateRepoUnits` and `DefaultMirrorRepoUnits` into settings in `app.ini`?

**Comment by yp05327** [comment]
> Should only the action unit be removed or other units(wiki, project, etc) should be removed too?

I think this is based on the mirror options.
![image](https://github.com/go-gitea/gitea/assets/18380374/2db473da-f931-4a0c-b440-70772c771631)
