### ISSUE TITLE
How to limit the size of repository?

### ISSUE THREAD

**Issue by yixiubest** [go-gitea/gitea#30356]
### Feature Description

如何设置仓库的最大容量？我尝试在app.ini中添加以下配置，但似乎不起作用：

[repository]
ROOT = /data/git/repositories
MAX_REPOS_SIZE = 500

有全局的或者单个仓库的设置途径吗？感谢告知

**Comment by lunny** [comment]
Please speak in English.

**Comment by lunny** [comment]
It's not supported yet. There is a PR to fix this. #21820

**Comment by Gitttttttt** [comment]
ok, thks
