### ISSUE TITLE
Awkward behavior of "Repositories" on my profile page

### ISSUE THREAD

**Issue by svarlamov** [go-gitea/gitea#3035]
- Gitea version (or commit ref): 033ad9a
- Can you reproduce the bug at https://try.gitea.io:
  - Yes, https://try.gitea.io/YOUR_USERNAME (you will not see repos from organizations that do show up on your dashboard under the 'all' tab...)

## Description

On the dashboard, when you're viewing 'all' repositories, you get an awesome searchable list of all of the repos that you have access to. Great. The problem starts when you click on "Show more repositories ..." That takes you to /YOUR_USERNAME where the "Repositories" tab is selected. This is where the weirdness begins...

First of all, you do not see any repos that are not explicitly owned by you. Bug or feature? I think bug. Github shows you repos where you are a collaborator/team member, likewise, if this page is linked to from the 'all' repos tab of the dashboard, then it should show the same data.

Second -- and perhaps most interestingly -- a search on this page yields repos that I don't own! It shows me all of the repos where I am a collaborator or team member -- which is great for me! Except for when I click on one of them, the link is wrong and gives me a 404. Let's say the repo is own by organization xyz and my username is abc. The link should be xyz/reponame, but instead, I get sent to abc/reponame. This is a pretty unfortunate bug to have a on one of the most used pages of the application...

**Comment by lunny** [comment]
@lafriks Is this only for 1.3? I would like move this to 1.4 and if some PR sent, back port to 1.3.

**Comment by lafriks** [comment]
@lunny I don't think we need to add issues to 1.4 if we backport them as otherwise these items will be in changelog for both 1.3.1 and 1.4.0 that is not exactly right as it will be fixed already in 1.3.1.

**Comment by lunny** [comment]
Answered in discord, just copy it to here. 
> We have resolved that, changlog will follow the milestones and labels. We can deleted all PRs which labeled backport*

**Comment by svarlamov** [comment]
@ethantkoenig Thank you for your PR. I'm now running on Gitea 3b89ee5 but still not seeing any repos on my profile page where I am just a team member with admin access

**Comment by ethantkoenig** [comment]
@svarlamov Yes, as I mentioned in the description of #3093, that PR *only* fixed the broken link issue. That is why this issue is still open :smile:

**Comment by lunny** [comment]
I think github have similar behaviors. So I will move this to 1.x.x.
