### ISSUE TITLE
ignore invalid workflow "files-changed.yml": unknown on type

### ISSUE THREAD

**Issue by yp05327** [go-gitea/gitea#30351]
### Description

![image](https://github.com/go-gitea/gitea/assets/18380374/999fb77f-f350-4497-a36e-32144b19ca64)
ps: files-changed.yml comes from Gitea

### Gitea Version

1.22.0+dev-1313-gd7013c26c8

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

build

### Database

None

**Comment by yp05327** [comment]
It seems that it is caused by act
branches type is map[string]interface{} here
![image](https://github.com/go-gitea/gitea/assets/18380374/1cb5d9ff-9d83-42b0-b101-cc135b7a835a)

**Comment by silverwind** [comment]
I think we definitely need to fix this to get our own repo to work in gitea actions. Workflow in question is here:

https://github.com/go-gitea/gitea/blob/main/.github/workflows/files-changed.yml

**Comment by Zettat123** [comment]
This issue could be fixed by https://gitea.com/gitea/act/pulls/118

**Comment by Zettat123** [comment]
Close by https://gitea.com/gitea/act/pulls/118
