### ISSUE TITLE
parseRemoteUpdateOutput: unexpected update line " * [new ref]               refs/pull/30346/head  -> refs/pull/30346/head"

### ISSUE THREAD

**Issue by yp05327** [go-gitea/gitea#30352]
### Description

![image](https://github.com/go-gitea/gitea/assets/18380374/89b266b6-277c-4947-98ab-71791a559dc8)
Not sure whether this is a bug.

### Gitea Version

1.22.0+dev-1313-gd7013c26c8

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

build

### Database

None

**Comment by lunny** [comment]
It should be and maybe it has been reported in another issue.

**Comment by yp05327** [comment]
same to #27010

**Comment by yp05327** [comment]
But I didn't mirror a repo, just run `git push --mirror xxx` in my local Gtiea dev folder.
