### ISSUE TITLE
Option to change commit author for push mirrors

### ISSUE THREAD

**Issue by CodeShakingSheep** [go-gitea/gitea#30367]
### Feature Description

I have a GitHub mirror setup for one of my Gitea repositories (direction push). So, every time I push commits to my Gitea repository they are mirrored to the GitHub repository. I just started using this feature for the first time and I figured that in GitHub it shows my Gitea user as commit author (including my Gitea user's email address; checked it with adding `.patch` to the GitHub commit URL.

However, I would prefer the GitHub commit author to be my GitHub user (and associated GitHub user email address) rather than my Gitea user. So, my feature request is an additional setting for push mirrors to determine the commit author. I read a [similar request in the GitLab forum](https://forum.gitlab.com/t/how-can-i-use-another-user-for-the-mirroring-user/89341) and [here](https://stackoverflow.com/questions/750172/how-do-i-change-the-author-and-committer-name-email-for-multiple-commits) are some possible approaches about how to change the author for multiple commits. So, in theory this should be possible. Just not sure about performance implications though. Still, would love to see this feature realized to keep more privacy on GitHub.

**Comment by KN4CK3R** [comment]
Changing the commit author would change the git history and then the source and target repositories are different (no mirror anymore). You could use a git hook to execute a script outside of Gitea which does that job but I don't see much need for this to be build into Gitea.

**Comment by lunny** [comment]
I think you can do that with Gitea Actions. It's more flexible than making it a feature of Gitea.
