### ISSUE TITLE
evaluate comrak as Markdown parser, renderer

### ISSUE THREAD

**Issue by nschloe** [go-gitea/gitea#30366]
### Feature Description

Recently, [comrak](https://github.com/kivikakk/comrak) gained support for math parsing. It now fulfills most of (everything?) what Gitea requires, so it's perhaps worthwhile considering it as a parser/renderer. GitLab already has and [step-by-step replaces their own quirks](https://gitlab.com/gitlab-org/ruby/gems/gitlab-glfm-markdown/-/issues/11).

My main motivation for suggesting this stems from Gitea's various math bugs, e.g.:

- #28259
- #28070
- #27834
- #27777
- #27618
- etc.

**Comment by delvh** [comment]
Erm… How is gitea supposed to include Rust code as a Go project?

**Comment by nschloe** [comment]
I thought it might be possible since GitLab, written in Ruby, does the same.

**Comment by KN4CK3R** [comment]
They use it as library with Ruby binding, nothing we want to do.

**Comment by nschloe** [comment]
Alright, thanks for the input. Closing.
