### ISSUE TITLE
500 internal server error after logging in when 2fa should appear.

### ISSUE THREAD

**Issue by grheard** [go-gitea/gitea#30379]
### Description

After the login where it should be asking for the 2FA token I am getting a 500 internal server error.

From the docker logs console I see the following:

> 2024/04/09 20:43:53 .../context_response.go:68:HTML() [D] Template: home
> 2024/04/09 20:43:53 ...eb/routing/logger.go:102:func1() [I] router: completed GET / for 192.168.2.1:0, 200 OK in 2.4ms @ web/home.go:32(web.Home)
> 2024/04/09 20:43:56 .../context_response.go:68:HTML() [D] Template: user/auth/signin
> 2024/04/09 20:43:56 ...eb/routing/logger.go:102:func1() [I] router: completed GET /user/login?redirect_to=%2fgitea%2f for 192.168.2.1:0, 200 OK in 6.2ms @ auth/auth.go:146(auth.SignIn)
> 2024/04/09 20:44:02 ...eb/routing/logger.go:102:func1() [I] router: completed POST /user/login for 192.168.2.1:0, 303 See Other in 28.3ms @ auth/auth.go:179(auth.SignInPost)
> 2024/04/09 20:44:02 ...ters/web/auth/2fa.go:36:TwoFactor() [E] UserSignIn: not in 2FA session
> 2024/04/09 20:44:02 .../context_response.go:68:HTML() [D] Template: status/500
> 2024/04/09 20:44:02 ...eb/routing/logger.go:102:func1() [I] router: completed GET /user/two_factor for 192.168.2.1:0, 500 Internal Server Error in 1.1ms @ auth/2fa.go:26(auth.TwoFactor)

This is a personal gitea docker instance (from gitea/gitea:latest) running on my unraid nas for personal projects. I haven't used this instance for about 6 months, but I was keeping up with the docker image updates as they came out. So unfortunately I cannot tell you when the login stopped working but I can tell you its running 1.21.10.

Any help in correcting this would be appreciated.

### Gitea Version

1.21.10

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

unraid 6.12.6

### How are you running Gitea?

gitea is installed from docker hub using the gitea/gitea:latest image

### Database

PostgreSQL

**Comment by techknowlogick** [comment]
Are you running gitea under a subpath? Can you see if 2fa works in "incognito" mode?

**Comment by grheard** [comment]
> Can you see if 2fa works in "incognito" mode?

It works.

Now I feel embarrassed.

As soon as it worked in incognito mode I went back ad used the 'forget about this site' to clear everything about my gitea instance from the browser. Upon a fresh visit it all works as expected.

Thanks for jogging my mind about one of the most basic steps in debugging web site issues.
