### ISSUE TITLE
HTTP 500 when displaying runner management

### ISSUE THREAD

**Issue by vanyle** [go-gitea/gitea#30378]
### Description

When accessing https://mygiteaurl.com/admin/actions/runners/ I get a 500 error.

```
An error occurred:

Render failed, failed to render template: admin/actions, error: template error: builtin(bindata):shared/actions/runner_list:76:40 : executing "shared/actions/runner_list" at <.BelongsToOwnerName>: error calling BelongsToOwnerName: runtime error: invalid memory address or nil pointer dereference
----------------------------------------------------------------------
						<td><span data-tooltip-content="{{.BelongsToOwnerName}}">{{.BelongsToOwnerType.LocaleString ctx.Locale}}</span></td>
						                                  ^
----------------------------------------------------------------------
```

The issue persist after restarting Gitea. I think my database is in an incorrect state.
It occured after messing with creating Gitea Runners.

### Gitea Version

1.21.10

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/vanyle/9a2bcdc8da1a17d2c692ebe8965de8b7

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/9964043/ca300d7f-368d-4e28-a0a3-a6048a04e59f)

### Git Version

2.40.1

### Operating System

Linux (Ubuntu)

### How are you running Gitea?

I am using Docker.
`sudo docker compose up`

### Database

SQLite

**Comment by Zettat123** [comment]
Steps to reproduce the bug:

1. Create a repo. Copy the runner registration token of the repo.
2. Delete the repo.
3. Use the token copied in step 1 to register a runner. The runner can be successfully registered.
4. Visit the runner list page then the error will appear.
