### ISSUE TITLE
No padding between buttons and above line in Project view UI.

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#30388]
<img width="1330" alt="image" src="https://github.com/go-gitea/gitea/assets/81045/1bf7ddbb-2a49-4efe-af24-ad21134eeb17">

**Comment by silverwind** [comment]
What page is this? User?

**Comment by lunny** [comment]
It's http://localhost:3000/teabot/-/projects/2

**Comment by yp05327** [comment]
This issue has been fixed, but PR didn't link to it correctly, so close it.
