### ISSUE TITLE
New Version Release Banner/Info 

### ISSUE THREAD

**Issue by RamblingGeekUK** [go-gitea/gitea#30391]
### Feature Description

For those of us running on prem, could we have a banner that pops up when you have released a new version, this would help us keep on top of releases and not fall behind.

**Comment by lunny** [comment]
This has been implemented. It will only be seen by administrators in top of admin panel.

**Comment by RamblingGeekUK** [comment]
Curious, I am an admin and I have never seen it, we are on version 1.21.3

**Comment by wxiaoguang** [comment]
Because it has been disabled by default for long time:  Configure update checker on installation page #21655

**Comment by RamblingGeekUK** [comment]
Thanks, I've looked at the config cheat sheet and can't see an option to turn it on or see anything in the UI. What am I missing?

**Comment by lunny** [comment]
ref: https://docs.gitea.com/administration/config-cheat-sheet?_highlight=update_checker#cron----check-for-new-gitea-versions-cronupdate_checker

**Comment by RamblingGeekUK** [comment]
Ah, I didn't find it, I searched for the word "update", thank you for taking the time to send me the link, it is working now. 

![image](https://github.com/go-gitea/gitea/assets/7108949/96be6fdf-fffe-4aee-a56a-b58468a6990e)
