### ISSUE TITLE
Smartypants

### ISSUE THREAD

**Issue by Fastidious** [go-gitea/gitea#3040]
Implement Blackfriday Smartypants settings, as [implemented](https://github.com/gogits/gogs/blob/6f2347fc71f17b5703a9b1f383a2d3451f88b741/conf/app.ini#L145-L150) in [gogs](https://github.com/gogits/gogs/search?utf8=✓&q=smartypants&type=).

**Comment by bkcsoft** [comment]
Any particular reason for implementing that? To me it just feels like segregating markdown even further...

**Comment by Fastidious** [comment]
@bkcsoft, It is already part of Blackfriday. It is useful for those -- like me -- who use git repositories as wikis, or knowledge base. It [improves typography](https://daringfireball.net/projects/smartypants/). It doesn't segregate markdown, it enhances it. It comes from the creator of markdown.
