### ISSUE TITLE
Unable to create repository

### ISSUE THREAD

**Issue by JohnZp** [go-gitea/gitea#30410]
### Description

Firstly, I try to create repository through the web page, but I can not find create button
![1712821174991](https://github.com/go-gitea/gitea/assets/25192317/39fee31b-7764-4bac-b88d-a36a14565691)

Then, I try create through pushing ,  and i've  referred to this document  [ref](https://docs.gitea.com/zh-cn/usage/push), Also restarted the docker instance. 

![image](https://github.com/go-gitea/gitea/assets/25192317/47535dd4-d0e3-4473-9c92-7682556fcf9d)
![image](https://github.com/go-gitea/gitea/assets/25192317/f5d707bd-3342-4e2e-a011-f5ef1b836a6f)
I don't know what's going on

### Gitea Version

1.22-night

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

Alpine Linux v3.19

### How are you running Gitea?

docker 
refer https://docs.gitea.com/zh-cn/installation/install-with-docker

### Database

SQLite

**Comment by lunny** [comment]
Which image do you running? `gitea/gitea:latest`?

**Comment by JohnZp** [comment]
> Which image do you running? `gitea/gitea:latest`?

YES

**Comment by yp05327** [comment]
Which browser are you using. And can you try again in a clean environment? e.g. no bowser extensions, the latest version of Chrome.

**Comment by JohnZp** [comment]
> Which browser are you using? And are there any errors in the browser console or Gitea? And can you try again in a clean environment? e.g. no bowser extensions, the latest version of Chrome.
I'm using the latest edge browser, and it does no work, my phone has no problem accessing through Chrome. Also, why can't I push when I set ENABLE_PUSH_CREATE_USER =true?

**Comment by lunny** [comment]
They should be put under `[repository]` section on app.ini

**Comment by zokkis** [comment]
@JohnZp So it is fixed now?

**Comment by yp05327** [comment]
I don't think so, have no idea about the the web UI bug.

**Comment by JohnZp** [comment]
It's work properly, thank you  brothers
