### ISSUE TITLE
Getting CORS error

### ISSUE THREAD

**Issue by Aditya1523** [go-gitea/gitea#30440]
### Description

![Screenshot 2024-04-12 at 3 34 15 PM](https://github.com/go-gitea/gitea/assets/113169558/4bb92039-a3fb-4bde-9e8b-3307f6374e21)

### Gitea Version

gitea:1.21.5-rootless

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

Deployed on to kubernetes

### Database

None

**Comment by lafriks** [comment]
This does not seems problem in gitea but rather error in tool used

**Comment by silverwind** [comment]
Gitea does not use CORS in default configuration, so this is a configuration error. Check that your `ROOT_URL` is correct and if you have `STATIC_URL_PREFIX` on a different origin, you need to setup CORS yourself.

**Comment by Aditya1523** [comment]
"Yes, that's accurate. By default, Gitea doesn't employ CORS. However, I've configured the CORS policy and added the CORS configuration to the INI file. Despite this, I'm still unable to initiate cross-origin requests."
<img width="457" alt="Screenshot 2024-04-15 at 1 10 30 PM" src="https://github.com/go-gitea/gitea/assets/113169558/87579350-6a14-4bf5-9863-cd8c4382520f">

**Comment by silverwind** [comment]
Maybe you need `HEADERS = Authorization`
