### ISSUE TITLE
New file jquery.minicolors.png after update the branch

### ISSUE THREAD

**Issue by yp05327** [go-gitea/gitea#30442]
### Feature Description

After update the branch, I got this new file, is this an issue? or just ignore it?
![image](https://github.com/go-gitea/gitea/assets/18380374/84786984-dc88-4b57-a822-37af0fce2efa)

**Comment by silverwind** [comment]
The file is gone since https://github.com/go-gitea/gitea/pull/30055, but as it is not in .gitignore, it may show up if you build the 1.22 branch and then switch to main. Either delete it manually or we add `public/assets/img/webpack` to gitignore.

**Comment by silverwind** [comment]
I guess we can restore the gitignore entry with a comment like "remove after 1.22 goes EOL".
