### ISSUE TITLE
Octotree support.

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#3045]
see https://github.com/buunguyen/octotree, currently octotree will visit /api/v3 but not /api/v1.

**Comment by lunny** [comment]
Add an issue on that repository https://github.com/buunguyen/octotree/issues/467

**Comment by sapk** [comment]
We could try to setup a v3 api and re-use func of v1 that are compatible and for the rest add it to the todo list ?

**Comment by lafriks** [comment]
I think we should add API to v3 only these parts that are fully compatible with github

**Comment by lunny** [comment]
@lafriks yes, we can do it easier.

**Comment by alexanderadam** [comment]
What if there would be another approach and the functionality of Octotree would directly integrated into gitea?

**Comment by mrsdizzie** [comment]
Closing since upstream Octotree has said they can't support Gitea.

**Comment by lunny** [comment]
Git master announced supported Gitea https://chrome.google.com/webstore/detail/git-master/klmeolbcejnhefkapdchfhlhhjgobhmo
