### ISSUE TITLE
[FR] Displaying of hex colors

### ISSUE THREAD

**Issue by gsantner** [go-gitea/gitea#3047]
- Gitea version (or commit ref): v1.3.0

## Description
GitHub added displaying of hex colors in rendered markdown some time ago, I just noticted it today. have to admit, to like it very much and find it useful, so suggesting it for gitea too. See screenshot below how it is visualized, or the referenced issue. I usually paste them in some color viewer, or guess colors, but having them directly shown is a really nice idea.

<https://github.com/gsantner/markor/issues/144>

![screenshot_2017-12-01__14-33_3](https://user-images.githubusercontent.com/6735650/33484900-ab556440-d6a4-11e7-99b6-16f0cfaa5144.png)

**Comment by gsantner** [comment]
activity

**Comment by sglux** [comment]
Yes, indeed, this would be nice to have.
@lunny what does the label you added mean?  It is since 2017 on milestone 1.x.x and we have 1.14.6 right now ;-)

**Comment by lunny** [comment]
That label will prevent stale bot mark it as stale. That means I think the issue should not be closed directly.

**Comment by gsantner** [comment]
this is how it looks nowadays on github: ![grafik](https://user-images.githubusercontent.com/6735650/132580275-00b8d5fb-9b20-4b93-a2e7-6bee3420e5a4.png)
