### ISSUE TITLE
Gitea 1.22 detected as virus by windows defender

### ISSUE THREAD

**Issue by yp05327** [go-gitea/gitea#30488]
![image](https://github.com/go-gitea/gitea/assets/18380374/d0fd8082-3fac-4f3a-979b-fbbbef66595a)
When download gitea 1.22 from dl.gitea.com, I got a warning from windows defender.
1.21.10 is fine.

**Comment by yp05327** [comment]
`gitea-1.22.0-rc0-windows-4.0-amd64.exe` is also ok

the detected virus is `Trojan:Win32/Wacatac.B!ml`

**Comment by 42wim** [comment]
That's an issue with defender, they seem to be labeling almost every Go program with `Trojan:Win32/Wacatac.B!ml`
See also https://go.dev/doc/faq#virus

For fun, try compiling a go windows binary that just prints "hello world" and upload it to virustotal.com :)

**Comment by silverwind** [comment]
Maybe it needs some kind of signature in the binary. How to other go programs avoid this?

**Comment by silverwind** [comment]
https://go-review.googlesource.com/c/vscode-go/+/565679 may have helped, also see https://github.com/golang/vscode-go/issues/3182.

**Comment by 42wim** [comment]
Afaik there is no general way for the "little man", thats the sad state of antivirus at the moment. We're having the same issue with in-house software, even with certificate signing.

You can upload it to the different antivirus and have them check it and whitelist it. 
https://www.microsoft.com/en-us/wdsi/filesubmission

**Comment by silverwind** [comment]
Likely it just searches for some static strings in the binary which then causes the false-positive, so maybe it's possible to eliminate/obfuscate these parts of the binary.

https://mrd0x.com/bypass-static-detection-windows-defender/

**Comment by yp05327** [comment]
I can't reproduce this on my personal PC. But my PC is Windows 11. 
My office's PC is Windows 10, and may have some special settings from the company (not sure).
