### ISSUE TITLE
(Optionally) expose SSH and GPG public keys via HTTP

### ISSUE THREAD

**Issue by silverwind** [go-gitea/gitea#3049]
GitHub has a useful feature where they expose SSH public keys on URLs like https://github.com/silverwind.keys. I think it would be great if Gitea would provide something similar, enabled by an option, which would expose both the SSH and GPG public keys of its users.

SSH keys should be sanitized to not include the comment, and GPG keys could be concatenated. To allow easy automation, there should be two routes, maybe `/sshkeys` and `/gpgkeys`, and possible also `/keys` that maps to SSH.

**Comment by sapk** [comment]
Could be based on what is behind : `/user/keys` `/user/gpg_keys`

**Comment by techknowlogick** [comment]
This currently exists (for SSH at least). You can see an example here: https://try.gitea.io/techknowlogick.keys

**Comment by techknowlogick** [comment]
On github there is also https://github.com/techknowlogick.gpg

**Comment by silverwind** [comment]
Nice, SSH keys looks like a recent addition I must have missed. Agree on adding GPG for feature parity.

**Comment by sapk** [comment]
This is still needed and wait for #4193

**Comment by lunny** [comment]
closed by #6610
