### ISSUE TITLE
Get a list of all commits from a repository will lost some file sometimes

### ISSUE THREAD

**Issue by udlenbo** [go-gitea/gitea#30492]
### Description

gitea version: 1.18.1 or 1.21.1
sometimes, we use "http://xx/api/v1/repos/yourgroup/yourrepo/commits?sha=0710d43a4b4297d3dd7161673b09ac811aa908cb&stat=true&page=1&limit=1" to search, fill will be lost but sometimes it will display.

### Gitea Version

1.18.1 or 1.21.1

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

use the same url, sometimes a file lost, but sometimes will display.
- query first
![image](https://github.com/go-gitea/gitea/assets/65267591/d63e3953-8959-4818-82cd-3798f5975c0f)

- query again
![image](https://github.com/go-gitea/gitea/assets/65267591/f147d223-d92f-4867-a7ad-516703913354)

### How are you running Gitea?

run from docker

### Database

None

**Comment by udlenbo** [comment]
can someone help me?

**Comment by lunny** [comment]
Can you reproduce it on https://try.gitea.io ?

**Comment by udlenbo** [comment]
> Can you reproduce it on https://try.gitea.io ?

Yes
repository url: https://try.gitea.io/udlenbo/commit_miss_file.git

please look at this commit, we can find 22 files were changed
![image](https://github.com/go-gitea/gitea/assets/65267591/f40344c0-5f37-40a0-aa6c-65e509985f76)

but when we use "https://try.gitea.io/api/v1/repos/udlenbo/commit_miss_file/commits?sha=24def873bc58ad90b6be802275fea81e7b97b2ab&stat=true&page=1&limit=1"
there are only 21 files found
![image](https://github.com/go-gitea/gitea/assets/65267591/cd38ebff-5fc6-4692-b515-defdd7aa3a38)

**Comment by KN4CK3R** [comment]
With the try link it happens sometimes but I can't reproduce it locally.

**Comment by wxiaoguang** [comment]
Unable to reproduce either, but I think this will fix:  Fix commit file status parser #30602

**Comment by wxiaoguang** [comment]
The 1.21-nightly is ready, could you try it?

https://hub.docker.com/r/gitea/gitea/tags
