### ISSUE TITLE
405 Method Not Allowed: [no body]. But actually it is the right method

### ISSUE THREAD

**Issue by yixiubest** [go-gitea/gitea#30491]
### Description

When I use POST to request the `/admin/users` interface:
![image](https://github.com/go-gitea/gitea/assets/38375081/99664bb3-ee91-45eb-ae28-72a03cc96b7a)

a 405 error is reported：`405 Method Not Allowed: [no body]`.

What else, the request was send by `RestTemplate`, like this(the param(RequestBody) is not null):
`restTemplate.exchange(
                    url,
                    HttpMethod.POST,
                    getEntity(token, param),
                    typeReference
            );`

The server logs:
`2024/04/15 15:33:41 ...eb/routing/logger.go:102:func1() [I] router: completed POST /admin/users for 172.16.60.93:61303, 405 Method Not Allowed in 0.4ms @ web/goget.go:20(web.goGet)`

Is this a bug or else? Thanks for help.

### Gitea Version

1.21.7

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

docker

### Database

None

**Comment by yp05327** [comment]
URL is not correct. It should have `/api/v1/`

you can check the samples in docs:
https://docs.gitea.com/development/api-usage

**Comment by Gitttttttt** [comment]
Oh it's my fault, I should pay more attention to it.
