### ISSUE TITLE
Non-admin user doesn't show repo dummy description

### ISSUE THREAD

**Issue by wxiaoguang** [go-gitea/gitea#30502]
(just to record, haven't looked into it, the UI looks pretty strange because there is a search input)

![image](https://github.com/go-gitea/gitea/assets/2114189/d25e1f1c-5434-4fb3-ae1b-852567402a18)

![image](https://github.com/go-gitea/gitea/assets/2114189/217f6b90-9a01-4de1-a381-61887a3f8e49)

**Comment by silverwind** [comment]
I can reproduce. Somehow `.Repository.DescriptionHTML` is not set.

**Comment by yp05327** [comment]
This #2167

**Comment by silverwind** [comment]
Thanks for digging that out. Seems a pointless change to me, I would revert it.

**Comment by yp05327** [comment]
About revert, see https://github.com/go-gitea/gitea/pull/3711/files#diff-7b2f4730100b2cf03a0e1d7cf7ca47d394b2a8db5ee7141f58643113026ea295R8
And it was revert in #5836
