### ISSUE TITLE
Propose to restart 1.22 release

### ISSUE THREAD

**Issue by wxiaoguang** [go-gitea/gitea#30501]
## The problem

1.22-rc0 is problematic:

* It is never really published, it is still in "draft" status on GitHub.
* Almost no bug report from 1.22-rc0, it's really questionable whether there are users using it.
* There are too many big changes in main branch, it would make it quite difficult to backport bug fixes for 1.22 in the future. And many bug fixes were missing due to various reasons.

## Proposal

Drop 1.22-rc0 and 1.22 branch, restart the 1.22 release (1.22-rc1 and a new 1.22 branch) from main branch some time later.

## Requirements

1. Pause unnecessary / pure refactoring changes before 1.22.1 or 1.22.2. A refactoring PR could only be merged in this period if:
    * It is for a bug fix and the refactoring is pretty good to have
    * It is well tested and good for some pending PRs, it should be covered by enough test cases
    * It could be backported from main to 1.22.x and doesn't seem to cause problems
    * (also could be slightly relaxed if enough maintainers/TOC agree)
2. Focus on fixing existing bugs and regressions

* [x] Rename v1_23 migrations to v1_22
* [x] Move merged PRs from 1.23 to 1.22 milestone
    * If a PR isn't in 1.22-legacy (no backport/done): move it to 1.22 milestone
    * If a PR is in 1.22-legacy: add "skip-changelog" to it and leave it in 1.23 milestone
* [x] Close unnecessary legacy 1.22 backports
* [x] Release 1.22-rc1 from main branch
    * [x] rename old 1.22 branch to 1.22-legacy
    * [x] tag 1.22-rc1
    * [x] hard reset / force push 1.22 branch by main branch.

**The TODO list is moved to #30731**

* [ ] Prepare a new changelog (there are a lot of new changes)
* [ ] Prepare a release note and explain why, and tell users that 1.22-rc1 and later won't be able to downgrade to 1.22-rc0 (and they shouldn't because many bugs are only fixed in 1.22-rc1)
    * "There will be no impact to end users who are using 1.22-rc0, they could safely upgrade to 1.22-rc1 and get more bug fixes and new enhancements"
* [ ] Announce and encourage users to test the RC1 release.
* [ ] Release 1.22.0 in one week if rc1 is stable enough.

**Comment by silverwind** [comment]
> There are too many big changes in main branch

There will always be big refactors and I don't want the release cycle to dictate when those can merge because that unnecessarily hinders progress.

So imho, get RC1 out now, and don't wait too long for release. Don't over-complicate the releases.

**Comment by wxiaoguang** [comment]
> > There are too many big changes in main branch
> 
> There will always be big refactors and I don't want the release cycle to dictate when those can merge because that unnecessarily hinders progress.
> 
> So imho, get RC1 out now, and don't wait too long for release. Don't over-complicate the releases.

I believe there are still many regressions, please provide stable releases to end users. RC release should be generally stable, but not contains many regressions or bugs.

**Comment by silverwind** [comment]
> I believe there are still many regressions, please provide stable releases to end users

That's why we have a period of usually 2+ months from branch creation to release so that any regressions will be backported. If something does not get noticed in the period, it likely wasn't important enough.

**Comment by silverwind** [comment]
BTW I personally don't mind if we reset `release/v1.22` to `main`, at least it makes some of my backports easier.

**Comment by wxiaoguang** [comment]
It seems difficult to reach a consensus, please release manager and TOC decide.

**Comment by lunny** [comment]
Why did you close this? I think at least 3 of us agreed to do so.

**Comment by wxiaoguang** [comment]
> Why did you close this? I think at least 3 of us agreed to do so.

If there is a consensus, then just do it. I think this issue won't provide any more useful information.

**Comment by silverwind** [comment]
I guess I remain neutral on this topic. I think 1.22 branch is shaping up well enough for a release, so no immediate need to "reset".

**Comment by wxiaoguang** [comment]
Another sample, 1.22 is broken for backporting: https://github.com/go-gitea/gitea/pull/30570#issuecomment-2064529003

**Comment by silverwind** [comment]
That's just us having missed another backport.

**Comment by silverwind** [comment]
@go-gitea/technical-oversight-committee we need a decision, either reset the v1.22 branch now or not. I don't care which way it chosen but I know @wxiaoguang has been withholding some backports into v1.22.

**Comment by wxiaoguang** [comment]
> I don't care which way it chosen but I know @wxiaoguang has been withholding some backports into v1.22.

Let me clarify the situation:

* I didn't mean to intentionally "withhold", but the 1.22 branch has too many differences, it is really difficult to backport bug fixes from main
* I guess nobody clearly knows whether 1.22 branch is correctly maintained.
* Even worse, few end users really used 1.22-rc0, you can see that there is almost no bug report from 1.22-rc0, it's really questionable whether there are users using it.

And I insist that:

* I have objection for "merging not fully tested refactoring PRs during RC period".
* I do not think keeping backporting almost everything into 1.22 is right (it already happened due to some recent frontend refactoring PRs).

**Comment by silverwind** [comment]
At this point, I think main branch is equally stable as release/v1.22. So could just delete the branch, fork it off main and then make RC 1 from it. Better do this sooner rather than later.

**Comment by wxiaoguang** [comment]
I believe main branch is more stable than 1.22 because 1.22 is really broken and nobody really maintains it carefully.

I will show you another example (by a quick search):  Fix long branch name overflows #30345  . I can see it is in 1.23, it has 1.22-backport label, but I can't tell whether it is really backported.

I think I have shown many examples, it doesn't make sense or is worth to continue working on the current 1.22 in my mind.

**Comment by silverwind** [comment]
https://github.com/go-gitea/gitea/pull/30345 wasn't backported because I forgot about it and I'm generally not thrilled to do manual backports.

**Comment by wxiaoguang** [comment]
> #30345 wasn't backported because I forgot about it and I'm generally not thrilled to do manual backports.

That's why 1.22 is broken. If you saw one bug in a house, then it must be not only one bug in the house.

**Comment by techknowlogick** [comment]
@silverwind https://discord.com/channels/322538954119184384/1067189205035393084/1231978296909107211

**Comment by theoludwig** [comment]
> Almost no bug report from 1.22-rc0, it's really questionable whether there are users using it.

I am a user of 1.22-rc0: https://git.theoludwig.fr/
Didn't find important bugs, at least for my basic usage.

If the 1.22 release is restarted, delete `release/v1.22` branch, and create it again from `main`, how will it impact users from v1.22-rc0 to upgrade to 1.22-rc1?

**Comment by wxiaoguang** [comment]
> If the 1.22 release is restarted, delete `release/v1.22` branch, and create it again from `main`, how will it impact users from v1.22-rc0 to upgrade to 1.22-rc1?

No impact, just get many bug fixes and new enhancements 😄

**Comment by lunny** [comment]
> > Almost no bug report from 1.22-rc0, it's really questionable whether there are users using it.
> 
> I am a user of 1.22-rc0: https://git.theoludwig.fr/ Didn't find important bugs, at least for my basic usage.
> 
> If the 1.22 release is restarted, delete `release/v1.22` branch, and create it again from `main`, how will it impact users from v1.22-rc0 to upgrade to 1.22-rc1?

The only drawback is you cannot downgrade from 1.22-rc1 -> 1.22-rc0 which is different from a traditional Gitea minor version upgrade.

**Comment by wxiaoguang** [comment]
The TODO list is moved to #30731
