### ISSUE TITLE
To clone the project locally, execute 'make build' and get the following error

### ISSUE THREAD

**Issue by rnb3ds** [go-gitea/gitea#30512]
### Description

To clone the project locally, execute 'make build' and get the following error:

`Running go generate...
no required module provides package code.gitea.i; to add it:
        go get code.gitea.i
make: *** [makefile:782: generate-go] Error 1`

![image](https://github.com/go-gitea/gitea/assets/20226005/d9dc49f6-dace-4b52-b080-a9566616897e)

### Gitea Version

master

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

My running environment: 

win10、Git Bash、make 4.2、go 1.22

### Database

None

**Comment by rnb3ds** [comment]
Makefile is not modified, project new clone downloaded.

**Comment by lunny** [comment]
This is because windows command line has limitation for output. And since Gitea have more and more packages, `GO_PACKAGES` is too long.

**Comment by rnb3ds** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。

**Comment by rnb3ds** [comment]
> This is because windows command line has limitation for output. And since Gitea have more and more packages, `GO_PACKAGES` is too long.

That's the reason. Thank you！

**Comment by silverwind** [comment]
According to https://stackoverflow.com/questions/3205027/maximum-length-of-command-line-string, command length limit is either 32k or 8k. I think we'd need to avoid passing so long command lines to really fix it.

**Comment by silverwind** [comment]
So instead of passing all go files to `go generate`, I think we could scan for `//go:generate` comments and only pass these.

> Go generate scans the file for directives, which are lines of the form,
>
> //go:generate command argument...
>
> (note: no leading spaces and no space in "//go") where command
is the generator to be run, corresponding to an executable file
that can be run locally. It must either be in the shell path
(gofmt), a fully qualified path (/usr/you/bin/mytool), or a
command alias, described below.

**Comment by jolheiser** [comment]
Wait why are we not already running `go generate ./...`?

**Comment by silverwind** [comment]
https://github.com/go-gitea/gitea/pull/30529 should fix it. @rnb3ds can you try it?

**Comment by silverwind** [comment]
> Wait why are we not already running `go generate ./...`?

No idea but it seems to have some useless exclusion of certain test files, at least for `vet`.

**Comment by silverwind** [comment]
We could alternative pass every known module that has `go:generate` statements, e.g.:

```
modules/charset/escape.go:4://go:generate go run invisible/generate.go -v -o ./invisible_gen.go
modules/charset/escape.go:6://go:generate go run ambiguous/generate.go -v -o ./ambiguous_gen.go ambiguous/ambiguous.json
modules/options/options_bindata.go:8://go:generate go run ../../build/generate-bindata.go ../../options options bindata.go
modules/templates/templates_bindata.go:8://go:generate go run ../../build/generate-bindata.go ../../templates templates bindata.go true
modules/migration/schemas_bindata.go:8://go:generate go run ../../build/generate-bindata.go ../../modules/migration/schemas migration bindata.go
modules/public/public_bindata.go:8://go:generate go run ../../build/generate-bindata.go ../../public public bindata.go true
``à
