### ISSUE TITLE
downgrade database version from 280" to'189" is not supported and may result in loss of data integrity.

### ISSUE THREAD

**Issue by x2358473** [go-gitea/gitea#30517]
### Description

我使用的mysql数据库。今天从1.21.10更新到1.21.11后运行就报错了

### Gitea Version

1.21.11

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

1.21.10

### Operating System

linux

### How are you running Gitea?

docker 

### Database

MySQL/MariaDB

**Comment by lunny** [comment]
I think you upgraded to a wrong version. 189 is a previous version. For minor versions, there will be no database version changes.

**Comment by x2358473** [comment]
> 我认为您升级到了错误的版本。 189 是以前的版本，应该是 1.14.x 。对于次要版本，不会有数据库版本更改。

我是使用的docker版本，从hub.docker上拉取的latest版本。然后把docker中的/data映射到本地目录。之前的升级都正常。但是这次的升级出现了问题

**Comment by x2358473** [comment]
> 我认为您升级到了错误的版本。 189 是以前的版本，应该是 1.14.x 。对于次要版本，不会有数据库版本更改。

![WechatIMG1481](https://github.com/go-gitea/gitea/assets/26506220/76fa332e-c7df-460a-a1e2-b82ce79e0856)
![Uploading WechatIMG1482.jpg…]()

**Comment by x2358473** [comment]
![Uploading WechatIMG1482.jpg…]()

**Comment by lunny** [comment]
You are running wrong docker. It's OK for me.
<img width="1504" alt="image" src="https://github.com/go-gitea/gitea/assets/81045/fb8c2dac-9dd5-48f1-8811-e8cd3e821c23">

**Comment by x2358473** [comment]
> 你运行了错误的docker。对我来说还好。 <img alt="图像" width="1504" src="https://private-user-images.githubusercontent.com/81045/322761797-fb8c2dac-9dd5-48f1-8811-e8cd3e821c23.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyNTgxMTIsIm5iZiI6MTcxMzI1NzgxMiwicGF0aCI6Ii84MTA0NS8zMjI3NjE3OTctZmI4YzJkYWMtOWRkNS00OGYxLTg4MTEtZThjZDNlODIxYzIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDA4NTY1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjNTQ2NjYxY2ViZWRkNTFiMzljYWIxMTBkYzIyMzM4MGRkYmZhOTVmMzQzZmQ4MTU3ZjRmMGU2ZmM3MGVlMWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IxnUFCKrc6NODy3EYez-q7CYIIgSPCEye-6uqPpiRmo">

我可能知道原因了。我使用了registry-mirrors 到aliyuncs,可能他的latest没有同步。所以是旧的
