### ISSUE TITLE
import from gogs /github.

### ISSUE THREAD

**Issue by poloskey** [go-gitea/gitea#30521]
### Description

import from gogs/github will faill unless you set the in app.ini under [repository] the  DEFAULT_BRANCH to master

to reproduce: 

add a repository to a user  (gitea/data/gitea-repositories/user/
go in gui to user settingss -> Reposistories -> choose addapt files to import reposistory

the branch button on the imported repository  will give a error 404

now set the in app.ini under [repository] the  DEFAULT_BRANCH = master,  restart gittea and try to import another one
or remove the imported one. 

the branch button will work as expected

Don't forget to push the button  "Delete any repositories that are missing their Git files" before importing the same repository again.

maby make a note of this the docs?

### Gitea Version

1.221.11

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

2.25.1

### Operating System

ubuntu/linux

### How are you running Gitea?

using the lastest binary from gitea.com

### Database

None

**Comment by lunny** [comment]
Can you reproduce this on https://try.gitea.io ? And can you give an example repository?

**Comment by yp05327** [comment]
I can reproduce it.
