### ISSUE TITLE
Admin config page UI regression

### ISSUE THREAD

**Issue by wxiaoguang** [go-gitea/gitea#30524]
![image](https://github.com/go-gitea/gitea/assets/2114189/9809c7d4-d163-4bf8-8510-d13dc6e5eb0e)

**Comment by silverwind** [comment]
Only a problem on light theme.

**Comment by silverwind** [comment]
For comparison, original fomantic ui:

<img width="175" alt="image" src="https://github.com/go-gitea/gitea/assets/115237/ae8aa4f4-dd4b-4d37-9bdb-93e568ba9254">
<img width="184" alt="image" src="https://github.com/go-gitea/gitea/assets/115237/e2ed26d3-80f3-4049-b4b9-d1d4ea06d80b">

So I think we add only that border.
