### ISSUE TITLE
Gitea 1.3.0 fails to start

### ISSUE THREAD

**Issue by klingtnet** [go-gitea/gitea#3052]
I just upgrade to gitea 1.3.0 from 1.2.3 and now the service fails to start.
The problem is that the oauth2 plugin seems to ignore the working directory:

```
$ echo $PWD
/home/gitea/gitea
$ /usr/bin/gitea web --port 10000 --config /home/gitea/gitea/custom/conf/app.ini
# ...
2017/12/01 16:17:18 [...uth/oauth2/oauth2.go:47 Init()] [E] Fail to create dir /usr/bin/data/sessions/oauth2: mkdir /usr/bin/data: permission denied
```
Gitea was build from source: https://github.com/klingtnet/klingt.net/blob/master/build/gitea/Makefile

**Comment by klingtnet** [comment]
This is where gitea crashes: [/modules/auth/oauth2/oauth2.go#L45](https://github.com/go-gitea/gitea/blob/master/modules/auth/oauth2/oauth2.go#L45)

**Comment by 0rzech** [comment]
I think the root issue here is that by default Gitea wants to create its data directory next to executable file, what seems undesirable more often than not. IMHO, it should default to `${XDG_CONFIG_HOME}/gitea` on Linux and similar directory on other supported operating systems.

@klingtnet Could you try to run Gitea the following way?
```
GITEA_CUSTOM='/home/gitea/gitea/custom' /usr/bin/gitea web --port 10000
```

**Comment by 0rzech** [comment]
I think the real issue is that by default Gitea wants to create its data directory next to executable file, what seems undesirable more often than not. IMHO, it should default to `${XDG_CONFIG_HOME}/gitea` on Linux and similar directory on other supported operating systems.

@klingtnet Could you try to run Gitea the following way?
```
GITEA_CUSTOM='/home/gitea/gitea/custom' GODEBUG=netdns=go /usr/bin/gitea web --port 10000
```
This way you won't have to relate on `PWD`.

PS. The `GODEBUG=netdns=go` is not required, but seems to be a good choice for performance reasons, unless your networking setup is too complicated for Go's net library.
PS. II Please make backups before experimenting with the way you run Gitea. I don't take any responsibility. You know your setup the best and if you choose to follow my advices, you do it at your own risk.

**Comment by 0rzech** [comment]
I think the real issue is that by default Gitea wants to create its data directory next to executable file, what seems undesirable more often than not. IMHO, it should default to `${HOME}/gitea` on Linux and similar directory on other supported operating systems.

**Comment by 0rzech** [comment]
@klingtnet Could you try to run Gitea the following way?
```
GITEA_CUSTOM='/home/gitea/gitea/custom' GODEBUG=netdns=go /usr/bin/gitea web --port 10000
```
This way you won't have to relate on `PWD`. This is also how it is done in [Dockerfile](https://github.com/go-gitea/gitea/blob/master/Dockerfile#L31) and it's the [recommended](https://docs.gitea.io/en-us/customizing-gitea/) way override default _custom_ directory placement.

PS. The `GODEBUG=netdns=go` is not required, but seems to be a good choice for performance reasons, unless your networking setup is too complicated for Go's net library.
PS. II Please make backups before experimenting with the way you run Gitea. I don't take any responsibility. You know your setup best and if you choose to follow my advices, you do it at your own risk.

**Comment by 0rzech** [comment]
@klingtnet Could you try to run Gitea the following way?
```
GITEA_CUSTOM='/home/gitea/gitea/custom' GODEBUG=netdns=go /usr/bin/gitea web --port 10000
```
It will pick your `app.ini` and assume anything else is relative to `/home/gitea/gitea/custom`, AFAIK. This way you won't have to rely on `PWD`. This is also how it is done in [Dockerfile](https://github.com/go-gitea/gitea/blob/master/Dockerfile#L31) and it's the [recommended](https://docs.gitea.io/en-us/customizing-gitea/) way to override default _custom_ directory placement.

PS. The `GODEBUG=netdns=go` is not required, but seems to be a good choice for performance reasons, unless your networking setup is too complicated for Go's net library.
PS. II Please make backups before experimenting with the way you run Gitea. I don't take any responsibility. You know your setup best and if you choose to follow my advices, you do it at your own risk.

**Comment by klingtnet** [comment]
@0rzech Thank you for your detailed response.
I tried to set `GITEA_CUSTOM`—also double checked its value—but the error is still the same, i.e. gitea tries to write to `/usr/bin/data`.

**Comment by 0rzech** [comment]
@klingtnet You're welcome. Could you also post `APP_DATA_PATH` setting value from your `app.ini`? I guess it might have been set to `/usr/bin/data` during installation due to lack of `GITEA_CUSTOM` environment variable.

**Comment by klingtnet** [comment]
You're a wizard, setting `APP_DATA_PATH` fixed the problem!
The key did not exist in my `app.ini` so I added `APP_DATA_PATH = /home/gitea/gitea/data` to the `[server]` section.

**Comment by klingtnet** [comment]
I have closed the issue but may considerto set `APP_DATA_PATH` to `pwd` if unset?

**Comment by 0rzech** [comment]
@klingtnet If `APP_DATA_PATH` was absent, then Gitea defaulted to 'next-to-binary location'. I think the best way is to run Gitea the way I presented in my second comment. Once you added the `APP_DATA_PATH` to your `app.ini`, it should work fine from now on. Just make sure all other paths in your `app.ini` are set to proper values and all existing data is in right place.

**Comment by 0rzech** [comment]
@klingtnet If `APP_DATA_PATH` was absent, then Gitea defaulted to "next-to-binary location".

I think the best way is to run Gitea using the command I presented in my second comment. Once you added the `APP_DATA_PATH` to your `app.ini`, it should work fine from now on. This means the `conf/app.ini` should be in `data` directory as well, resulting in `/home/gitea/data/conf/app.ini`.

Also make sure all other paths in your `app.ini` are set to proper values and all existing data is in right place.

**Comment by klingtnet** [comment]
@0rzech One note to `GODEBUG=netdns=go`, it looks like this is already the default behaviour and does not need to be set explicitly: https://golang.org/src/net/net.go

**Comment by 0rzech** [comment]
@klingtnet Yes, you're right. I have even pointed it out myself [here](https://github.com/go-gitea/gitea/pull/2927#pullrequestreview-80666199).

Btw. it looks like your installation might become a bit messy, because you have `/home/gitea/gitea/custom` and `/home/gitea/data` now. `GITEA_CUSTOM` is better to have the same value as `APP_DATA_PATH`, IMO. If everything is kept default except for `GITEA_CUSTOM` itself, then your Gitea directories should look like:

```
${GITEA_CUSTOM}/avatars
${GITEA_CUSTOM}/conf
${GITEA_CUSTOM}/indexers
${GITEA_CUSTOM}/log
${GITEA_CUSTOM}/sessions
```
etc.
