### ISSUE TITLE
The sub menu of repository code is not high enough

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#30536]
<img width="1323" alt="image" src="https://github.com/go-gitea/gitea/assets/81045/07f216f5-a480-4f0c-b361-c26b7f55773c">

**Comment by silverwind** [comment]
Please clarify what is wrong.

**Comment by silverwind** [comment]
That's the language stats bar. Do you see a tooltip when hovering over it?

**Comment by lunny** [comment]
I cannot reproduce it now.
