### ISSUE TITLE
Comment count in issue list does not count inline comments

### ISSUE THREAD

**Issue by silverwind** [go-gitea/gitea#30549]
### Description

https://try.gitea.io/silverwind/symlink-test/pulls

<img width="1333" alt="image" src="https://github.com/go-gitea/gitea/assets/115237/8b50c6e8-920c-40f7-b9d3-876a7fec3fd1">

Comment count here says "1" but it should be "2" as there is one regular and one inline review comment.

### Gitea Version

main

### Can you reproduce the bug on the Gitea demo site?

Yes

**Comment by metiftikci** [comment]
related to #22419 ?
