### ISSUE TITLE
Code search result border-radius problem

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#30540]
<img width="1312" alt="image" src="https://github.com/go-gitea/gitea/assets/81045/2f2d44c3-2aa6-44bc-ad49-79d6317cff2b">

**Comment by silverwind** [comment]
Looks like it wasn't completely fine on 1.21 either:

<img width="39" alt="image" src="https://github.com/go-gitea/gitea/assets/115237/338040c8-88f5-4b6b-af37-3f958baef831">

main:

<img width="59" alt="image" src="https://github.com/go-gitea/gitea/assets/115237/9a1ec736-b4b6-4135-9aa8-80282f26924e">
