### ISSUE TITLE
Job description should be same in actions list page and view page

### ISSUE THREAD

**Issue by yp05327** [go-gitea/gitea#30567]
### Feature Description

https://gitea.com/gitea/gitea-docusaurus/actions
![(@`19)IB(~`B4 Y89G3AI(J](https://github.com/go-gitea/gitea/assets/18380374/57bbf96b-edc2-40ba-b7d6-887ac294837b)
https://gitea.com/gitea/gitea-docusaurus/actions/runs/1401
![P %1S9GDWY%MBFY`1NI3)`A](https://github.com/go-gitea/gitea/assets/18380374/8e3b9d2c-a873-4fd2-9eac-ff7ff3fc0076)

**Comment by silverwind** [comment]
Not sure I follow. Which one of the two would you change, and how?

**Comment by yp05327** [comment]
I will do this. 😄
