### ISSUE TITLE
Incorrect notification message box in dashboard

### ISSUE THREAD

**Issue by yp05327** [go-gitea/gitea#30566]
### Description

![image](https://github.com/go-gitea/gitea/assets/18380374/2a19e8b9-0976-4840-a7dc-165a08c7be11)

### Gitea Version

1.23.0+dev-158-g2da1dcfc21

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

build

### Database

None

**Comment by silverwind** [comment]
Regression from https://github.com/go-gitea/gitea/pull/30214.

**Comment by wxiaoguang** [comment]
> Regression from #30214.

That's why I do not think it should use flex everywhere. It should only be used when we are 100% sure about its children.

**Comment by silverwind** [comment]
Flex is fine but I must have overlooked this child 😆

**Comment by yp05327** [comment]
![image](https://github.com/go-gitea/gitea/assets/18380374/2ecab8ac-1b74-4b6d-9fb6-4ce3d23513a3)
@silverwind 
Is this expected? It looks too long.

**Comment by wxiaoguang** [comment]
->  Fix flash message for flex-container #30657
