### ISSUE TITLE
Selected workflow will not be highlighted

### ISSUE THREAD

**Issue by yp05327** [go-gitea/gitea#30578]
### Feature Description

![image](https://github.com/go-gitea/gitea/assets/18380374/0c83cbab-97d1-4edc-a40d-161b7964c62c)
IIRC, it will be highlighted when workflow was selected before.

**Comment by yp05327** [comment]
It seems that this is caused by #30325

active item background is overwitted by `.ui.vertical.menu .item`
![image](https://github.com/go-gitea/gitea/assets/18380374/e35ac59f-2c0d-41b1-b1eb-47d8f4e85895)

**Comment by lunny** [comment]
Looks like not only this menu, many other menus have the same problem.

**Comment by yp05327** [comment]
@lunny
I think we should add this to 1.22 milestone.

**Comment by wxiaoguang** [comment]
->  Add missing menu active item background back #30897
