### ISSUE TITLE
Minor copy changes to commit(s)/branch(es) tab

### ISSUE THREAD

**Issue by mmarif4u** [go-gitea/gitea#3058]
- Gitea version (or commit ref): - Git version: d8d38ed

## Description
If there is one commit or branch, the copy should be `1 Commit` instead of `1 Commits`, and same for branch.

## Screenshots
![selection_001](https://user-images.githubusercontent.com/1280585/33511815-d00dad92-d75d-11e7-9497-d9a1795352f4.png)

**Comment by techknowlogick** [comment]
@mmarif4u I've just created a PR for this change.
