### ISSUE TITLE
Module not found error when building v1.21

### ISSUE THREAD

**Issue by pboguslawski** [go-gitea/gitea#30596]
### Description

`make build` worked fine a few days before for same gitea source and now throws

```
+ make build
rm -rf public/assets/js public/assets/css public/assets/fonts public/assets/img/webpack
npx webpack
assets by status 20.3 MiB [cached] 163 assets

ERROR in ./node_modules/mermaid/dist/mindmap-definition-617cf8dd.js 4:0-56
Module not found: Error: Package path ./dist/cytoscape.umd.js is not exported from package /my/path/gitea-build/node_modules/cytoscape (see exports field in /my/path/gitea-build/node_modules/cytoscape/package.json)
 @ ./node_modules/mermaid/dist/mermaid-934d9bea.js 3535:38-80
 @ ./node_modules/mermaid/dist/mermaid.core.mjs
 @ ./web_src/js/markup/mermaid.js 34:39-37:5
 @ ./web_src/js/markup/content.js 1:0-45 7:2-15
 @ ./web_src/js/index.js 20:0-76 105:2-20 110:2-19

webpack 5.88.2 compiled with 1 error in 33361 ms
```
Similar problem described on https://github.com/langgenius/dify/issues/3613

### Gitea Version

1.21

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

Compiled from sources.

### Database

MySQL/MariaDB

**Comment by silverwind** [comment]
Maybe your `node_modules` broke somehow, try running `make clean-all` and then retry `make build`.

**Comment by xiaoqingrong** [comment]
I have the same problem. I use  Apple mac M1。use docker build：`docker buildx build --platform=linux/amd64 -t test/dify-web:v1.3.7 .`，and cytoscape installed。bug have this errors
<img width="1052" alt="image" src="https://github.com/go-gitea/gitea/assets/28303597/8630c1c9-b963-407c-8d78-b02682716cdf">

**Comment by xiaoqingrong** [comment]
> I have the same problem. I use Apple mac M1。use docker build：`docker buildx build --platform=linux/amd64 -t test/dify-web:v1.3.7 .`，and cytoscape installed。bug have this errors <img alt="image" width="1052" src="https://private-user-images.githubusercontent.com/28303597/324665636-8630c1c9-b963-407c-8d78-b02682716cdf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4Mzk0NTUsIm5iZiI6MTcxMzgzOTE1NSwicGF0aCI6Ii8yODMwMzU5Ny8zMjQ2NjU2MzYtODYzMGMxYzktYjk2My00MDdjLThkNzgtYjAyNjgyNzE2Y2RmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDAyMjU1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5MDc0YTgzNzhiN2EyOTYxMWUzMDdjNDE1NTBhZjQ2M2RlYzUxZmIwYWRlZmE0N2M3NzgwZmRlODE0NzA4M2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Zsys75clO4q57QO8DKpLCq1Wk8mVWNgdNOGVq_wS0w4">

I was fine before, but not lately

**Comment by xiaoqingrong** [comment]
I was fine before, but not lately

**Comment by silverwind** [comment]
Seems like upstream issue in that package:

https://github.com/cytoscape/cytoscape.js/issues/3239

**Comment by silverwind** [comment]
What's strange is that v1.21 uses `3.26.0` while the issues are reported with `3.29.0`.

**Comment by wxiaoguang** [comment]
I also occasionally experience the similar problem. I just do `rm -rf node_modules` and then `make build`, then everything goes well.

I think it is the npm/webpack's problem, for example, if there is a network error (or use ^C to stop the npm process), then the `node_modules` directory would go corrupted. Removing `node_modules` directory and restart the `build`, then no error.

**Comment by pboguslawski** [comment]
Problem occurs in automatic build process every time (empty node_modules, no network errors, etc.). Build process and source code were not changed in the meantime.

The problem is caused by running `make generate-images` before `make build` (we use custom logo and favicon) and removing `--no-package-lock` from `make generate-images` in `Makefile` resolves this issue for us.

Please verify and fix.

**Comment by silverwind** [comment]
Hmm yeah `make generate-images` is somewhat of an oddball. Maybe we should just put those dependencies into package.json. At least the problematic `canvas` dependency is listed as `optionalDependency` so will not fail the whole install if it fails:

https://github.com/fabricjs/fabric.js/blob/c27a21883eda49b7a7bfcc32f49eb59a099a1536/package.json#L74

**Comment by silverwind** [comment]
On topic here: Let's wait on https://github.com/cytoscape/cytoscape.js/issues/3239 and a future mermaid.js update to resolve this hopefully.

**Comment by silverwind** [comment]
https://github.com/go-gitea/gitea/pull/30713 updates main branch to the fixed cytoscape version.

**Comment by yp05327** [comment]
Is this issue fixed after bump the version of dependencies?

**Comment by silverwind** [comment]
Pretty sure it should.
