### ISSUE TITLE
Proposal: cancel the reminder of this merge request on the page

### ISSUE THREAD

**Issue by x2358473** [go-gitea/gitea#30611]
### Feature Description

![WechatIMG1486](https://github.com/go-gitea/gitea/assets/26506220/fed629cd-432e-4f98-af69-7e4a0ff1b757)
想取消页面上的这个合并请求的提醒。请问在哪里设置。看了所有的设置项都没有找到。因为这个提醒即使合并的也不会即使更新。
en:
I want to cancel the reminder of this merge request on the page. Can you tell me where to set it up? I looked at all the settings and couldn't find them. Because even if this reminder is merged, it will not be updated.

**Comment by yp05327** [comment]
It seems like a bug? It should disappear when you created a PR.

**Comment by yp05327** [comment]
I can confirm this issue, and will be fixed by #25812
