### ISSUE TITLE
Broken avatar css on main page

### ISSUE THREAD

**Issue by stuzer05** [go-gitea/gitea#30624]
### Description

![image](https://github.com/go-gitea/gitea/assets/23124682/acb452bd-c5f9-4ec9-bf02-7af647e81edf)

avatar is cun vertically

![image](https://github.com/go-gitea/gitea/assets/23124682/15ce3360-2a66-4a7f-b935-5619f22959eb)

### Gitea Version

trunk

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

docker

### Database

None

**Comment by lunny** [comment]
regression of #30547

**Comment by wxiaoguang** [comment]
->  Fix dropdown text ellipsis #30628
