### ISSUE TITLE
frp + nginx reverse proxy + ssl = push 403

### ISSUE THREAD

**Issue by RedCarl** [go-gitea/gitea#30636]
### Description

I used frp + nginx reverse proxy + ssl, and a 403 error occurred when I cloned and pushed.
![image](https://github.com/go-gitea/gitea/assets/71010647/5e7e84af-fd75-49d1-a38d-921b0023f540)
I tried removing ssl, but it didn't work.
If you remove frp and directly access 192.168.10.81:3000, there will be no problem.

### Gitea Version

1.21.10

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

docker

### Database

MySQL/MariaDB

**Comment by lunny** [comment]
So that's FRP system's problem? Maybe you need to investigate that system?

**Comment by lunny** [comment]
Sorry, according to your architecture, FRP will connect to nginx and nginx connect with Gitea. So FRP will not connect to Gitea.

**Comment by RedCarl** [comment]
![image](https://github.com/go-gitea/gitea/assets/71010647/15d6a6a6-fd13-44e4-8cc1-4a77a16afbd8)
Is it possible that it is a protocol problem? I chose tcp

**Comment by wolfogre** [comment]
> I just want to know if gitea does not support frp

I guarantee Gitea can work well with frp because my Gitea instance works with frp and https for years.

@RedCarl Please note that it's almost impossible to help you without your network topology, reverse proxy configuration information. These have gone beyond the scope of Gitea discussions and are more like an operations issue.

**Comment by wolfogre** [comment]
I will close this issue. If you still can't solve it, I can personally offer some help. You can find me in the QQ group. I believe you speak Chinese.
