### ISSUE TITLE
AutoSignIn: permission denied --> HTTP 500

### ISSUE THREAD

**Issue by gehoida** [go-gitea/gitea#30639]
### Description

I have installed gitea using docker in my homelab using the docker compose file from the documentation.
After some time I get a http 500 failure. 

the docker log states:

stdout
04/22/2024
08:12:03 AM
2024/04/22 08:12:03 ...ers/web/auth/auth.go:128:checkAutoLogin() [E] **AutoSignIn: unable to updateSession: regenerate session: open /data/gitea/sessions/d/6/d657f36258355c57: permission denied**
stdout
04/22/2024
08:12:03 AM
2024/04/22 08:12:03 ...eb/routing/logger.go:102:func1() [I] router: completed GET /user/login for 192.168.1.14:62305, 500 Internal Server Error in 6.7ms @ auth/auth.go:146(auth.SignIn)

It seems to be an issue with expired sessions but I am not sure.

Any idea how to fix this?

### Gitea Version

1.21.10

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

version: "3"

networks:
  gitea:
    external: false

services:
  server:
    image: gitea/gitea:1.21.10
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=db:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=XXXX
      - GITEA__mailer__ENABLED=true
      - GITEA__mailer__FROM='XXXX'
      - GITEA__mailer__PROTOCOL=smtps
      - GITEA__mailer__SMTP_ADDR=XXXX
      - GITEA__mailer__USER='XXXX'
      - GITEA__openid__ENABLE_OPENID_SIGNIN=false
      - GITEA__openid__ENABLE_OPENID_SIGNUP=false
      - GITEA__service__DISABLE_REGISTRATION=true
      
    restart: always
    networks:
      - gitea
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
    depends_on:
      - db

  db:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=XXXX
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=XXXX
      - MYSQL_DATABASE=gitea
    networks:
      - gitea
    volumes:
      - ./mysql:/var/lib/mysql

### Database

MySQL/MariaDB

**Comment by lunny** [comment]
> 2024/04/22 08:12:03 ...ers/web/auth/auth.go:128:checkAutoLogin() [E] AutoSignIn: unable to updateSession: regenerate session: open /data/gitea/sessions/d/6/d657f36258355c57: permission denied

There is no permission to access the file path.

**Comment by gehoida** [comment]
wow, that was fast. du to the reason i'm quiet a newbie, how to I grant permission?

**Comment by lunny** [comment]
> wow, that was fast. du to the reason i'm quiet a newbie, how to I grant permission?

This is the skill of Linux which is not belong to this topic. Simply, you can run command `ls -l` to check all files are belongs t  to Git user and another problem is you may need to check whether the mount of `/data` permissions works well.

**Comment by wxiaoguang** [comment]
If you are using `image: gitea/gitea:1.21.10`, then I think the `./gitea` directory (from the config `- ./gitea:/data`) should be like this:

```
$ ls -n
drwxr-xr-x  5 1000 1000 4096 Aug 21  2021 git
drwxr-xr-x 19 1000 1000 4096 Dec 17 23:20 gitea
drwx------  2    0    0 4096 Aug  9  2021 ssh
```

You could try to run `sudo chown -R 1000:1000 ./gitea/git ./gitea/gitea` , or just have a new/fresh depolyment, then docker image could prepare everything correctly for you.

**Comment by gehoida** [comment]
Thank you for the response. I have dug a bit deeper in the session context of gitea. I have changed to use db instead of file. I only use it in my homelab with no external access, so for me this is sufficient. It seems that i have to level up my linux skills.
