### ISSUE TITLE
Sort type Newest for isues/pull request is not working

### ISSUE THREAD

**Issue by PDuijst** [go-gitea/gitea#30642]
### Description

The sort Newest is sorting the same as "Recently updated".

### Gitea Version

1.21.11

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/167179430/b26cc2e5-4767-48e0-b12f-676aa34361c6)

### Git Version

1.21.11

### Operating System

Linux

### How are you running Gitea?

Building gitea by myself
OS: Ubuntu 22.04 LTS
gitea is running with systemd

### Database

MSSQL

**Comment by PDuijst** [comment]
Thanks for the quick fix. Cherry-picked the commit into V1.21.11.

**Comment by lunny** [comment]
Added a label `backport/v1.21` for #30644
