### ISSUE TITLE
Release for old tag not initialized correctly in frontend

### ISSUE THREAD

**Issue by stklcode** [go-gitea/gitea#3066]
- Gitea version (or commit ref): 1.3.0
- Git version: 2.11
- Operating system: Linux amd64
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (https://try.gitea.io/test/test-3066/)
  - [ ] No
  - [ ] Not relevant
- Log gist: -

## Description

When creating a release from an old tag, the description is not initialized correctly, as branch and number of commits since this release are missing. Commit hash is shown correctly.
The latest release yet shows correctly shows e.g. `5 commits to master since this release`.
The fresh created older release always shows `0 commits to since this release` (branch missing)

**Reproduce:**
* Go to "Releases" on a project wiht multiple unreleased tags
* Draft a new release 
* Select branch. fill tag name and description and release

## Screenshots
![screenshot_20171202-210620](https://user-images.githubusercontent.com/12963621/33519406-14959504-d7a6-11e7-9c08-8baa0a338a04.png)

**Comment by ethantkoenig** [comment]
@stklcode I'm unable to reproduce this. Could you either
* provide more detailed instructions for how to reproduce, or
* make https://try.gitea.io/test/chi public (I get a 404 when I try to view, so I'm assuming it's private)

**Comment by stklcode** [comment]
@ethantkoenig Sorry, didn't look at the privacy level of the project (just picked a random one of the test account). Just created a public project to not mess up with other test repos https://try.gitea.io/test/test-3066/

I have to slightly change the problem description though:
*When creating a new release, the number of commits since seems to always be 0  and the branch is missing.*
