### ISSUE TITLE
UI border-radius inconsistent problems

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#30673]
- [x] Repository Activity
<img width="1047" alt="image" src="https://github.com/go-gitea/gitea/assets/81045/e08c66ac-862b-46ad-9885-bd1cb5b965a6">

- [x] Repository Actions Secrets
<img width="1060" alt="image" src="https://github.com/go-gitea/gitea/assets/81045/5132edb5-7512-4a13-9194-29f67f958d62">

- [x] Repository Actions Variables
<img width="1050" alt="image" src="https://github.com/go-gitea/gitea/assets/81045/6a0653d0-a742-4077-b4b3-bacda5bf6194">

- [x] File editor
<img width="1313" alt="image" src="https://github.com/go-gitea/gitea/assets/81045/a2ab7e48-07b5-4b5e-a220-9dfc76255fdd">

- [x] File editor preview
<img width="1309" alt="image" src="https://github.com/go-gitea/gitea/assets/81045/5de51699-5908-47b3-b015-a6d06488f186">

- [x] User profile
<img width="329" alt="image" src="https://github.com/go-gitea/gitea/assets/81045/d5934cb2-1a94-4615-b7ba-d2e332f404d5">

- [x] Admin -> Identity & Access -> User Emails
<img width="1636" alt="image" src="https://github.com/go-gitea/gitea/assets/81045/dcf1285f-8a0c-4c31-81f4-3ac23107b84f">

- [x] Admin -> Code Assets -> Repositories
<img width="274" alt="image" src="https://github.com/go-gitea/gitea/assets/81045/9fb22864-7e52-45d0-ad31-86c421e0891e">

- [x] Admin -> Integrations -> Webhook
<img width="1177" alt="image" src="https://github.com/go-gitea/gitea/assets/81045/4ca724f0-30f3-4646-b5de-ebb80f3e6ee5">

- [x] Admin -> Actions -> Variables
<img width="1172" alt="image" src="https://github.com/go-gitea/gitea/assets/81045/4c9971c1-86a8-4206-a2aa-cb768f718c48">

- [x] Admin -> System Notices
<img width="1187" alt="image" src="https://github.com/go-gitea/gitea/assets/81045/a5fbe020-3cfa-4cbf-9b88-4a7b34050af6">

- [x] Org setting -> Webhooks
<img width="1069" alt="image" src="https://github.com/go-gitea/gitea/assets/81045/1ddf1b78-4b61-41e2-a00e-1d4cb7e145ea">

- [x] Org setting -> Labels
<img width="1061" alt="image" src="https://github.com/go-gitea/gitea/assets/81045/f8af5110-e877-4e26-aebf-6445c898f0b8">

- [x] Org Setting -> Blocked Users
<img width="1047" alt="image" src="https://github.com/go-gitea/gitea/assets/81045/a9d248a3-4a18-4770-bbfc-5f2d87a5a960">

- [x] Org Setting -> Actions -> Secrets
<img width="1070" alt="image" src="https://github.com/go-gitea/gitea/assets/81045/3a09a596-97e7-44d5-8176-6ad45ef3bb7f">

- [x] Org Setting -> Actions -> Variables
<img width="1048" alt="image" src="https://github.com/go-gitea/gitea/assets/81045/b1573122-8d33-413d-8aaa-571a49cd308e">

- [x] Org -> Teams -> Members/Repositories setting for a Team
<img width="814" alt="image" src="https://github.com/go-gitea/gitea/assets/81045/a3976ae2-3775-4139-83bc-9e5b549eab2c">

- [x] New migration
<img width="334" alt="image" src="https://github.com/go-gitea/gitea/assets/81045/f82e1105-4b35-4ec3-9177-a98558834daa">

- [x] notification -> subscriptions
<img width="1296" alt="image" src="https://github.com/go-gitea/gitea/assets/81045/71eae05d-6140-45be-826d-9b976b3ec66f">

- [x] User settings -> Blocked users
<img width="1046" alt="image" src="https://github.com/go-gitea/gitea/assets/81045/635c9988-9497-4d79-9e5d-d24caaf3c59d">

- [x] User settings -> Actions -> Secrets
<img width="1055" alt="image" src="https://github.com/go-gitea/gitea/assets/81045/e9ff1fa9-d004-4ce4-beac-3517c171173c">

- [x] User settings -> Actions -> Variables
<img width="1045" alt="image" src="https://github.com/go-gitea/gitea/assets/81045/333dab07-5d74-40e8-9c26-b888fa877e31">

- [x] User setttings -> Webhooks
<img width="1050" alt="image" src="https://github.com/go-gitea/gitea/assets/81045/4a9cf90f-5b08-493c-8caf-941fbc3c0f94">

**Comment by silverwind** [comment]
I see these are because of various `.ui.segment` constructs. Should pretty much all be fixable with some `:has` magic.

**Comment by lunny** [comment]
The two places border-radius missed.

- [ ] Admin -> Code Assets -> Repositories
<img width="274" alt="image" src="https://github.com/go-gitea/gitea/assets/81045/9fb22864-7e52-45d0-ad31-86c421e0891e">

- [ ] Admin -> System Notices
<img width="1187" alt="image" src="https://github.com/go-gitea/gitea/assets/81045/a5fbe020-3cfa-4cbf-9b88-4a7b34050af6">

**Comment by silverwind** [comment]
> The two places border-radius missed. @silverwind
> 
>     * [ ]  Admin -> Code Assets -> Repositories
> 
> 
> <img alt="image" width="274" src="https://private-user-images.githubusercontent.com/81045/325065213-9fb22864-7e52-45d0-ad31-86c421e0891e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0ODQ3MTYsIm5iZiI6MTcxNDQ4NDQxNiwicGF0aCI6Ii84MTA0NS8zMjUwNjUyMTMtOWZiMjI4NjQtN2U1Mi00NWQwLWFkMzEtODZjNDIxZTA4OTFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDMwVDEzNDAxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2MDEyMjFmM2MxMmJiMWU5ZmFiODE5MDZmOTA1N2YzYTQ5MWQ3Y2M1N2I3OWE4YjdhMmJkMzY4YTIwMzRjYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UAja9ykdAgrMCJWqLL9PYzLNAx-IGGb9iBSdVL_KpWs">
> 
>     * [ ]  Admin -> System Notices
> 
> 
> <img alt="image" width="1187" src="https://private-user-images.githubusercontent.com/81045/325065582-a5fbe020-3cfa-4cbf-9b88-4a7b34050af6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0ODQ3MTYsIm5iZiI6MTcxNDQ4NDQxNiwicGF0aCI6Ii84MTA0NS8zMjUwNjU1ODItYTVmYmUwMjAtM2NmYS00Y2JmLTliODgtNGE3YjM0MDUwYWY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDMwVDEzNDAxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhYjlmN2IwNzU0N2NmODMyYWEwOTAyMTc1NjZlNDViNzkzZTNkZjM3ODZjOGM4M2EwY2M1MTc1YTk2NjUyODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.enSHSuSm-M3orTcckBsF5c7gQTCaGkAVvnD5GUoCi00">

Could not reproduce these:

https://github.com/go-gitea/gitea/pull/30707#issuecomment-2078944730
https://github.com/go-gitea/gitea/pull/30707#issuecomment-2078947985

**Comment by lunny** [comment]
I can reproduce them in both firefox, chrome, and local/try.gitea.io .

**Comment by silverwind** [comment]
I can reproduce `/admin/notices` when table is not empty, the other I still cannot.
