### ISSUE TITLE
New pull request imagediff js error

### ISSUE THREAD

**Issue by stuzer05** [go-gitea/gitea#30683]
### Description

![image](https://github.com/go-gitea/gitea/assets/23124682/24bae820-9223-43f9-a559-c71d5c90fec6)

I commited single image and trying to make new pr. See the error

### Gitea Version

trunk

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

dokcer

### Database

None

**Comment by silverwind** [comment]
I can't seem to reproduce. I added a PNG, then updated a PNG, both without that JS error in the diff.

What kind of image is it? PNG? Could you try to reproduce against https://try.gitea.io/?

**Comment by wxiaoguang** [comment]
->  Refactor imagediff and fix regression bug #30694

**Comment by stuzer05** [comment]
> I can't seem to reproduce. I added a PNG, then updated a PNG, both without that JS error in the diff.
> 
> What kind of image is it? PNG? Could you try to reproduce against https://try.gitea.io/?

Cannot recreate on test instance

**Comment by wxiaoguang** [comment]
To reproduce: https://try.gitea.io/wxiaoguang/test/commit/d8f8ecd64ac8c9d7c3afcf9b64485e723276fb2e
