### ISSUE TITLE
Branch overview page 

### ISSUE THREAD

**Issue by Bwko** [go-gitea/gitea#307]
I'd like to see something like the [github branch overview page](https://github.com/go-gitea/gitea/branches).

- [x] List branches
- [ ] Create branches
- [x] Delete branches
- [x] Compare branches.

See gogits/gogs#2310

**Comment by bkcsoft** [comment]
Shortened the title, I was confused whether it was a "Add branch" overview or add "Branch overview" until I read the upstream issue :)

**Comment by KangoV** [comment]
Would this allow the deletion of a branch?

**Comment by lunny** [comment]
You can delete a branch after that's merged from forked repo to source repo. This feature has been implemented I remember.

**Comment by Bwko** [comment]
@KangoV Yes i want to create something like githubs implementation.

**Comment by neilherbertuk** [comment]
Would be extremely interested in seeing this implemented!

**Comment by lunny** [comment]
~Sorry, This has been implemented in v1.3.~

**Comment by lunny** [comment]
Branch compare left

**Comment by Nobodys** [comment]
Is this still in development or dropped? I would really love to see and use this feature.

**Comment by lunny** [comment]
@Nobodys currently nobody are working on this.

**Comment by KaKi87** [comment]
Any news on this ? It would be so cool

**Comment by lunny** [comment]
@Bwko @KaKi87 I changed the issue content and now it's a check list.

**Comment by KaKi87** [comment]
Hey there, any news on this ?

**Comment by 6543** [comment]
@Bwko `Compare branches.` is here with the "Create Pull"

**Comment by 6543** [comment]
and what is the usecase of `Create branches` ? how should this work ?!?

**Comment by KaKi87** [comment]
@6543 `git checkout -b` or `git checkout --orphan`, depending on the user's choice. How else ?

**Comment by 6543** [comment]
But wich usecase?

If you argue to edit via web later -> editor can create a new branch

**Comment by KaKi87** [comment]
What if I want to create a new branch for someone else to use ?

**Comment by lafriks** [comment]
@KaKi87 you can do that from Code tab branch selection dropdown

**Comment by KaKi87** [comment]
I see that dropdown, but it's only displaying the list of existing branches, there is no add/edit/remove buttons there.

**Comment by lunny** [comment]
@KaKi87 It's some tricky. You could browser the commit code root path and in the dropdown, input the name you want to tag. and click the `create branch xxxxx` on the changed dropdown.

**Comment by KaKi87** [comment]
Oh, I see it now. Well, it's pretty hidden. I still maintain that regrouping all these features on a dedicated page would be a good idea. :)

**Comment by 6543** [comment]
closed since beside the "Create Branch" witch github aso do not have on the overview ... all is solved & more

note: creating branch via UI is supported
