### ISSUE TITLE
Add MDX linter for docs directory.

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#30743]
Since Gitea's documentation are now building with docusaurus v3 which support MDX syntax. So some wrong syntax will break the documentation building. Maybe https://npmjs.org/eslint-plugin-mdx is a good choice.

**Comment by silverwind** [comment]
Would mdx files be named `.mdx`? If so, we can distinguish by file extension for which linters run on what. Would not recommend putting MDX content into `.md`.

**Comment by lunny** [comment]
This can be closed as docs moved to https://gitea.com/gitea/docs.
