### ISSUE TITLE
Javascript promise error on dashboard

### ISSUE THREAD

**Issue by shootie22** [go-gitea/gitea#30768]
### Description

Hi, I'm facing an issue with Gitea after a fresh install.  
I freshly installed Gitea version 1.22.0+rc1-3-gd07019f539 from binary and adopted a repository.  
  
The main page shows this error and shows no content on the main body of the page:  
`JavaScript promise rejection: Cannot read properties of null (reading 'State'). Open browser console to see more details.`  

![image](https://github.com/go-gitea/gitea/assets/39218788/2a6171d8-d382-4906-9a70-6c49a82f84f9)

In my browser's console I can see:
```
DashboardRepoList.vue:254 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'State')
    at DashboardRepoList.vue:254:76
    at Array.map (<anonymous>)
    at Proxy.searchRepos (DashboardRepoList.vue:251:32)
```
The Gitea logs don't seem to show any errors. I tried looking around online but I couldn't find anything too useful D:  
Any help is appreciated. Thanks.

### Gitea Version

1.22.0+rc1-3-gd07019f539

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/39218788/d6ade199-275a-4c39-961d-2065c23ecd5e)

### Git Version

git version 2.34.1

### Operating System

Ubuntu 24.04 LTS

### How are you running Gitea?

Binary downloaded from https://dl.gitea.com/gitea/1.22/

### Database

MySQL/MariaDB

**Comment by silverwind** [comment]
Comes from here: https://github.com/go-gitea/gitea/blob/a3d9f0d9151dbdcd77bf68f70b8e9497da5f2d3f/web_src/js/components/DashboardRepoList.vue#L254

It does not seem to not be a recent regression.

**Comment by silverwind** [comment]
@shootie22 can you open browser devtools, network tab, find the last request to `/repo/search` and post the response JSON?

**Comment by surinara** [comment]
I get the same error.

**Comment by wxiaoguang** [comment]
I think it is related to a recent change, the `latest_commit_status` could be nil. @lunny

**Comment by wxiaoguang** [comment]
->  Fix dashboard commit status null access #30771

**Comment by lunny** [comment]
> I think it is related to a recent change, the `latest_commit_status` could be nil. @lunny
> 
> By this:
> 
>     * [Cache repository default branch commit status to reduce query on commit status table #29444](https://github.com/go-gitea/gitea/pull/29444)

It's weird. #30700 should have resolve the problem.

**Comment by wxiaoguang** [comment]
The backend bug has been fixed, but the nil/null is still passed to frontend.

**Comment by shootie22** [comment]
Thanks for being so fast to reply, everyone. 🙂  
I'm at work now, but I will provide more details as soon as I get home.

**Comment by shootie22** [comment]
> @shootie22 can you open browser devtools, network tab, find the last GET request to `/repo/search` and post the response JSON?

I think one of these two should be the response:
```{"success_fraction":0,"report_to":"cf-nel","max_age":604800}```

`{"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v4?s=mLkdCyVnBspjjfnAacUgzJaS8uzopX5dqjc%2BQV9Wm%2F6eF%2F1g9aJkCCC7yGsYyvgJk6H1t5ochGRMtHTRKfOwV%2F6W5g014ClukG7nObTHZ%2FN6W5feDBJ8yv8w26iZDUlXBI9n"}],"group":"cf-nel","max_age":604800}`
  
It's worth mentioning that I am routing this install through Cloudflare. Even so, I get the same behavior through the local address.
