### ISSUE TITLE
Code search + repo indexer

### ISSUE THREAD

**Issue by KazzmanK** [go-gitea/gitea#30761]
### Description

In 1.22 there is new feature to search through code by `git grep`
If no code indexer is enabled there is a message

![image](https://github.com/go-gitea/gitea/assets/13328513/b709979b-0b0d-4155-ae45-7198df543636)

But in my  app.ini indexer is enabled

``` ini
[indexer]
REPO_INDEXER_ENABLED = true
REPO_INDEXER_PATH = indexers/repos.bleve
MAX_FILE_SIZE = 1048576
ISSUE_INDEXER_PATH = indexers/issues.bleve
```

is this message (to enable indexer) is expected or I`m doing something wrong?

### Screenshots

none

### Gitea Version

1.22.0-rc1

### Can you reproduce the bug on the Gitea demo site?

No

### Browser Version

120

**Comment by wxiaoguang** [comment]
Oops, my mistake. -> Rename CodeIndexerEnabled to IsRepoIndexerEnabled #30762
