### ISSUE TITLE
time tracker still works when issues closed

### ISSUE THREAD

**Issue by renothing** [go-gitea/gitea#3077]
Gitea version (or commit ref): 1.3.0
Git version: 2.11
Operating system: Linux amd64
Database (use [x]):
 PostgreSQL
 MySQL
 MSSQL
 SQLite
Can you reproduce the bug at https://try.gitea.io:
 Yes (https://try.gitea.io/test/chi/releases)
## Description

...

## Screenshots
![screenshot from 2017-12-03 22-08-00](https://user-images.githubusercontent.com/261274/33526108-9a65b490-d876-11e7-8e94-633e6b1b9bea.png)

**Comment by lafriks** [comment]
Is this request to automatically stop timer when closing PR?
Otherwise I don't see why one could not add additional time for closed issue (like for testing, deployment etc)

**Comment by renothing** [comment]
no,when I close issues, the tracker still working.

**Comment by lafriks** [comment]
I don't think tracker should be disabled when issue is closed. What if someone wants to add time after issue is closed like in use cases I mentioned in previous comment?
