### ISSUE TITLE
Git grep search error

### ISSUE THREAD

**Issue by ymefg** [go-gitea/gitea#30785]
### Description

I'm encountering a failure when attempting to perform code searches in one specific repository of mine. This issue is exclusive to this particular repository; searching works fine in other repositories. Even when I try to create a new repository similar to the problematic one, I can't reproduce the issue.

![image](https://github.com/go-gitea/gitea/assets/23009387/3074c8c2-7c13-45e0-ad7d-d9afbfa499d6)

Here's the additional information about the repository:

- It has only one branch named "main".
- All files are .md files.
- There is a file named "readme.md".
- The rest of the files have Chinese names, such as "通信协议.md".

### Gitea Version

1.22.0+rc1

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

CentOS

### How are you running Gitea?

docker compose

### Database

SQLite

**Comment by wxiaoguang** [comment]
Could you login to the Gitea server and find the "repo.git", and "cat config" to see its content?

**Comment by wxiaoguang** [comment]
One more question: what's you git version?

**Comment by ymefg** [comment]
> Could you login to the Gitea server and find the "repo.git", and "cat config" to see its content?

Sorry, Gitea is deployed on the servers of the company I work for, and I'm off duty now. Also, due to the International Labor Day holiday, it'll be at least five days before I can send you the config and git version. I'll send the them once I'm back at work.

**Comment by wxiaoguang** [comment]
No problem. Since you are using CentOS, I guess the git version might be old. If it is possible, it's worth to try to upgrade to the latest git version.

**Comment by yp05327** [comment]
![image](https://github.com/go-gitea/gitea/assets/18380374/e5d8566a-4dd2-4407-a201-de898dc98744)
If the search key word is Chinese, I got this error

**Comment by wxiaoguang** [comment]
Reproduced, will propose a fix.

**Comment by wxiaoguang** [comment]
->  Fix grep search #30843
