### ISSUE TITLE
styles are still broken on project cards

### ISSUE THREAD

**Issue by stuzer05** [go-gitea/gitea#30788]
### Description

![image](https://github.com/go-gitea/gitea/assets/23124682/2238922d-cf9c-40aa-a74d-5bcf986cf70c)

### Gitea Version

trunk

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

docker

### Database

None

**Comment by silverwind** [comment]
Which commit hash are you on exactly? https://github.com/go-gitea/gitea/pull/30687 should have fixed it.

**Comment by stuzer05** [comment]
[564102c](https://github.com/go-gitea/gitea/commit/564102ce89f53d6bd2fdbaa33416e4287d6fe9a8)

**Comment by silverwind** [comment]
Link to try.gitea.io with repro?

**Comment by stuzer05** [comment]
https://try.gitea.io/stuzer05/test-release/projects/5401

**Comment by wxiaoguang** [comment]
->  Fix issue card layout #30800
