### ISSUE TITLE
tcp: write: broken pipe: [E] Render failed: failed to render template + [E] plainTextInternal (status=500)

### ISSUE THREAD

**Issue by update-freak** [go-gitea/gitea#30792]
### Description

In the log it show the following:

2024/04/30 23:21:27 .../context_response.go:87:HTML() [E] Render failed: failed to render template: home, error: write tcp 127.0.0.1:3000->127.0.0.1:50284: write: broken pipe
2024/04/30 23:21:27 .../context_response.go:89:HTML() [E] plainTextInternal (status=500): write bytes failed: write tcp 127.0.0.1:3000->127.0.0.1:50284: write: broken pipe

Installed via docker compose on Synology NAS.

### Gitea Version

gitea-1.22.0

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![log](https://github.com/go-gitea/gitea/assets/40196995/c4df7d11-60ff-4f70-a9ed-c82f383ced60)

### Operating System

Synology DSM

### How are you running Gitea?

Docker Container

### Database

None

### Additional remarks
I already did this setting: Administration -> Konfiguration -> Einstellungen -> Gravatar deaktivieren

**Comment by wxiaoguang** [comment]
It is a false alarm. Some error messages are reported too aggressively.

If you didn't experience any problem during usage, it's safe to ignore them.

**Comment by wxiaoguang** [comment]
If there are some problems when browsing the pages ..... it looks more like an OS/envorinment related problem.

Usually `write: broken pipe` means the TCP connection breaks too early (in most cases, it shouldn't be related to Gitea itself)

**Comment by update-freak** [comment]
ok, thanks for the info. I didn't have any problems in usage and only saw this message in the logs.
Feel free to close this issue when you want to close this issue

**Comment by wxiaoguang** [comment]
->  Ignore uesless error message "broken pipe" #30801 

Let's make Gitea never show such useless logs 😁
