### ISSUE TITLE
When using repo indexer search code in Chinese, you will get 500 error

### ISSUE THREAD

**Issue by yp05327** [go-gitea/gitea#30797]
### Description

When I enable the repo indexer, and search code in Chinese, I got a 500 error
``` ini
[indexer]
REPO_INDEXER_ENABLED = true
```
![image](https://github.com/go-gitea/gitea/assets/18380374/9e1b11a4-581f-4b59-858a-54be56edb842)

### Gitea Version

latest

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

build

### Database

None

**Comment by yp05327** [comment]
same to #30317

**Comment by wxiaoguang** [comment]
->  Fix bleve fuzziness #30799
