### ISSUE TITLE
Can support oceanbase? is tidb supported?

### ISSUE THREAD

**Issue by sprappcom** [go-gitea/gitea#30793]
### Feature Description

need distributed sql. what is the best option so far for use with gitea?

**Comment by lunny** [comment]
TiDB has been supported.

**Comment by techknowlogick** [comment]
I'd point you towards tidb, I've confirmed that Gitea works with their hosted offering. Not sure about oceanbase, if you try it out with them, please let us know. I'll close this issue now.
