### ISSUE TITLE
Merged origin/master today and get error in some pages

### ISSUE THREAD

**Issue by yusiwen** [go-gitea/gitea#308]
- Gitea version (or commit ref): 65197187069dfe3407e8954bb5af32ee688b0da4
- Git version: 2.10.2
- Operating system: Ubuntu 16.04 x64
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Log gist:

## Description

Today I've pull origin/master in my local master branch, and when I click "Explore" on the page,  I got:

```
template: explore/repo_list:19:8: executing "explore/repo_list" at <.DescriptionHTML>: can't evaluate field DescriptionHTML in type *models.Repository
```

**Comment by tboerger** [comment]
Please update to the latest version, this have been fixed with https://github.com/go-gitea/gitea/pull/299

**Comment by tboerger** [comment]
Sorry, just have seen it's not fixed correctly. @lunny can you fix that?

**Comment by lunny** [comment]
I will check this.

**Comment by lunny** [comment]
@tboerger do you reproduced that? I cannot.
@yusiwen maybe you have to `make clean & make build`.

**Comment by yusiwen** [comment]
@lunny 
After `make clean & make build`, the newest binary file `gitea` is generated under `bin` folder, not in the project root path as it was before. So my service script can't start it. After I copied it to project root path, I restarted gitea, the problems are gone.

Thanks.

**Comment by tboerger** [comment]
There is an pending pull request which builds the binary to the root folder again

**Comment by tboerger** [comment]
I have marked the issue as invalid, it was just related to outdated sources.

**Comment by tboerger** [comment]
BTW, you can also call make only once, e.g. make clean build

**Comment by yusiwen** [comment]
@tboerger 
Thanks.  Will the binary be put under `bin` folder from now on or put back to project root? I runned gitea from `bin` folder, it complained about not found `app.ini` in `bin/custom/app.ini`, and a lot of errors as well before it exited.

**Comment by strk** [comment]
Will be in the root, see #247

**Comment by yusiwen** [comment]
@strk I see, thanks
