### ISSUE TITLE
broken styles on branch selector when creating an issue

### ISSUE THREAD

**Issue by stuzer05** [go-gitea/gitea#30802]
### Description

![image](https://github.com/go-gitea/gitea/assets/23124682/8692ae7d-0fe0-432e-940d-217c97cf3650)
![image](https://github.com/go-gitea/gitea/assets/23124682/9ad830d1-4385-4508-88d0-48388dcec6fc)

### Gitea Version

1.22.0+rc1-23-ga988237eb4

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

docker

### Database

None

**Comment by stuzer05** [comment]
also, how to remove branch selection?

**Comment by stuzer05** [comment]
And labels have a wierd padding 
![image](https://github.com/go-gitea/gitea/assets/23124682/2f7b1c65-8001-43c2-812f-325a1e808e9d)

**Comment by wxiaoguang** [comment]
ps: actually there is a longstanding question in my mind: why there is a branch selector when creating an issue? I don't know how it works .... does anyone know?

**Comment by wxiaoguang** [comment]
->  Fix branch selector UI #30803

**Comment by stuzer05** [comment]
> ps: actually there is a longstanding question in my mind: why there is a branch selector when creating an issue? I don't know how it works .... does anyone know?

Honestly, I don't know either. Useless functionality, imo. Also these branch refs become 404 when branch is deleted

**Comment by wxiaoguang** [comment]
I think we could make a quick fix for 1.22 and remove this likely useless branch selector from the issue page. 🤔

**Comment by stuzer05** [comment]
> I think we could make a quick fix for 1.22 and remove this likely useless branch selector from the issue page. 🤔

That would be awesome
