### ISSUE TITLE
[API] No edit history shown afer editing an issue's body

### ISSUE THREAD

**Issue by Android-X13** [go-gitea/gitea#30807]
### Description

1. Create an issue (either via the web interface or the API)

2. Edit the issue via the API

```
body=$(curl -s http://localhost:3000/api/v1/repos/$org/$repo/issues/$i \
  -H "Accept: application/json" \
  -H "Authorization: token $TOKEN" | jq -r .body)

body+=$'\n\n'"Test 1"$'\n\n'"Test 2"

curl -s -X 'PATCH' http://localhost:3000/api/v1/repos/$org/$repo/issues/$i \
  -H "Accept: application/json" \
  -H "Authorization: token $TOKEN" \
  -H "Content-Type: application/json" \
  -d "{ \"body\":\"$body\" }"
```

3. Refresh the page in the browser, the issue content has changed but there is no indication that it has been edited or edit history. Basically the `issue_content_history` table is not touched when editing issues via API calls.

### Gitea Version

1.21.11

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

Binary download, systemd

### Database

None

**Comment by yp05327** [comment]
@lunny 
This is an deprecated API. Not sure whether we need to fix it.
