### ISSUE TITLE
broken styles on hover in activity

### ISSUE THREAD

**Issue by stuzer05** [go-gitea/gitea#30808]
### Description

![image](https://github.com/go-gitea/gitea/assets/23124682/8358e854-b22a-4643-99e2-9783807ce0bf)

both on main screen and profile

### Gitea Version

trunk

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

docker

### Database

None

**Comment by wxiaoguang** [comment]
It's related to the tippy style change @silverwind

**Comment by silverwind** [comment]
Yes, this is related to the removal of the default 1rem padding.

**Comment by silverwind** [comment]
Problem is, this lib does not expose any way to allow modifying these tippy instances:

https://github.com/razorness/vue3-calendar-heatmap/blob/955626176cb5dc3d3ead8120475c2e5e753cc392/src/components/CalendarHeatmap.vue#L200-L204

**Comment by silverwind** [comment]
So I think the proper solution is to pass `tooltip=false` to the lib and instantiate our own tippy.

**Comment by wxiaoguang** [comment]
> So I think the proper solution is to pass `tooltip=false` to the lib and instantiate our own tippy.

That's what I said in https://github.com/go-gitea/gitea/pull/30732#issuecomment-2085395594 :

> I still do not think it is safe to backport.

Now we have limited time to fix this new regression.

**Comment by silverwind** [comment]
It's fine, it's a minor cosmetical issue.

**Comment by wxiaoguang** [comment]
I also proposed one.  Fix activity heat map padding & locale #30823
