### ISSUE TITLE
Show modal will cause body width becomeing smaller

### ISSUE THREAD

**Issue by yp05327** [go-gitea/gitea#30816]
### Description

![image](https://github.com/go-gitea/gitea/assets/18380374/336a3b38-f0f2-42cc-8884-7f7310d6e8a3)

### Gitea Version

latest

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

build

### Database

None

**Comment by yp05327** [comment]
![image](https://github.com/go-gitea/gitea/assets/18380374/5d0a1c83-58d9-4121-a857-631c85371c1e)
margin-width will become bigger and bigger

**Comment by yp05327** [comment]
https://forum.freecodecamp.org/t/issues-with-bootstrap-5-2-modal/570924

**Comment by yp05327** [comment]
but it seems that margin-right is from bootstrap 🤔

**Comment by silverwind** [comment]
The `tw-overflow-hidden` on body could maybe replaced with `pointer-events-none` on the dimmer to inhibit scrolling the body while modal is open.

**Comment by silverwind** [comment]
Margin is coming from fomantic modal module:

https://github.com/fomantic/Fomantic-UI/blob/59d9b409879ad9413ea0a3efa4ab2e51017ad9b9/src/definitions/modules/modal.js#L611-L617

**Comment by silverwind** [comment]
https://github.com/go-gitea/gitea/pull/30831 will fix it.
