### ISSUE TITLE
ui bug on mobile on releases page

### ISSUE THREAD

**Issue by stuzer05** [go-gitea/gitea#30821]
### Description

![image](https://github.com/go-gitea/gitea/assets/23124682/6796b107-ea92-4ab6-bf73-212dd827ac86)

on pixel 8 pro

### Gitea Version

trunk

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

docker

### Database

None

**Comment by silverwind** [comment]
There is now different behaviour after recent changes. Imho we need to switch to a 2-row layout here on small viewport, or even on larger ones.

<img width="576" alt="image" src="https://github.com/go-gitea/gitea/assets/115237/337d3e7d-dc1c-4078-9c36-b9deb01c0425">
