### ISSUE TITLE
Pr page js error ci is null

### ISSUE THREAD

**Issue by stuzer05** [go-gitea/gitea#30852]
### Description

![image](https://github.com/go-gitea/gitea/assets/23124682/33cbddcc-78da-4ca4-8721-e151c572d77b)
![image](https://github.com/go-gitea/gitea/assets/23124682/b03cdd90-a4f0-42a5-a3b8-10d6f3f80d43)
![image](https://github.com/go-gitea/gitea/assets/23124682/1e345e24-5fe5-432e-93a6-7692a90b0616)

### Gitea Version

1.22.0+rc1-42-gc445a85528

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

docker

### Database

None

**Comment by silverwind** [comment]
Was fixed by https://github.com/go-gitea/gitea/pull/30838.
