### ISSUE TITLE
Activity pages (besides Pulse) seem to no longer work

### ISSUE THREAD

**Issue by kemzeb** [go-gitea/gitea#30851]
### Description

Not sure if other users encountered this, but it appears that the contributors, contributor frequency, and recent commit graphs seem to no longer work currently i.e. I don't see any chart data.

To reproduce this, simply look at any of these pages while in a repository with recent commits.

The backend seems fine as I do see JSON responses from the related endpoints (e.g. /{username}/{repo}/activity/data for the `Contributors` page). Because of this, it looks like this maybe a problem with the frontend.

I also decided to checkout 21331be30cb8f6c2d8b9dd99f1061623900632b9 (when the contributors graph was introduced) and rebuilt my dev environment. Weirdly enough I still have the same problem, so I'm not sure what's going on (maybe some direct/transitive dependency causing this break?). 

### Gitea Version

53b55223d167c3fc996dd0278a656f421408ace7

### Can you reproduce the bug on the Gitea demo site?

Yes

### Git Version

git version 2.44.0

### Operating System

Debian

### How are you running Gitea?

In a Docker dev container firing up a Gitea dev environment using the `launch.json` configurations found in Gitea's VSCode docs.

I did also use try.gitea.io and looked for other user repos with chart data but they seem to have the same problem.

### Database

SQLite

**Comment by lunny** [comment]
It works for me. 0f3e717a1abb2b2161b87dac557beb6475224a2e

**Comment by kemzeb** [comment]
After doing the following:
- Made my fork up-to-date with gitea's main
- Built the project with: `TAGS="bindata sqlite sqlite_unlock_notify" make build`
- Created a new Gitea repository where I snatched all the commits in a project with 736 commits and merged their `main` onto mine
- Navigated to the `Contributors` page
- Disabled my browser cache and reloaded the page

I still have the problem:
<img width="1187" alt="Screenshot 2024-05-03 at 9 31 28 AM" src="https://github.com/go-gitea/gitea/assets/60799661/94ccb533-fe09-4e60-9a83-01234ba957ec">

The x-axis appears to be correct, but I am not seeing any chart data. I also realized that I'm not seeing any contributor graphs. I'm running on a chromium-based browser. I also checked Firefox and Safari (i.e. I'm using MacOS v14.4.1) and encountered the same problem. Not sure what's going on on my end.

Looking for more examples, I encountered the terraform-provider-gitea [project](https://gitea.com/gitea/terraform-provider-gitea/activity/contributors) where I also see the issue.

**Comment by lunny** [comment]
It works for me both chrome and firefox web browser in macOS.

<img width="1330" alt="image" src="https://github.com/go-gitea/gitea/assets/81045/0bcfc584-2b9f-4b83-b202-91ed63ae22c9">

**Comment by KazzmanK** [comment]
No issues for me too, in light and dark themes.

@kemzeb , may it be issue with database sync or custom theme?
Admin-Maintenance-> click on all sync operations.

**Comment by kemzeb** [comment]
No console or network errors, I still see the the JSON responses are successful; I used Safari, Brave, and Firefox and I don't see anything. I also went on a separate Windows machine with Firefox and I still don't see any chart data. I have used both light and dark themes for each browser.

**Comment by kemzeb** [comment]
Here's how it looks on my Windows machine running Firefox (with some of the JSON response shown):
![Screenshot 2024-05-03 135111](https://github.com/go-gitea/gitea/assets/60799661/cd764cff-a75a-425e-aa33-4a041db70491)

**Comment by kemzeb** [comment]
I have read the PR that introduced this change and my best guess so far has to do with some problem associated to date and time handling (I'm from the US).

**Comment by kemzeb** [comment]
Update: it looks like I am right. I changed my operating system to use a European date and time and I can now see the chart data. I'll see if I can make a patch for this (not a frontend wizard but I have read some of the code last night)!.

**Comment by kemzeb** [comment]
Alright working on this 👍

**Comment by snoweuph** [comment]
will this be in `1.22.1` or will it stay broken till `1.23.0` for stable users?
because I can reproduce it on my [Instance](https://git.euph.dev/Snoweuph/Dotfiles/activity/contributors) running `1.22.0`

**Comment by snoweuph** [comment]
okay?
 
anything I can do to help debugging rn?

**Comment by snoweuph** [comment]
Side Information: I did the upgrade to 22 just 3 days ago, so I should have the bugfix already, right?

So I guess, I have a weird bug in thte backend, though I would exspect server and not go binary releated

**Comment by kemzeb** [comment]
> Side Information: I did the upgrade to 22 just 3 days ago, so I should have the bugfix already, right?

Yes, v1.22.0 should have it.

> So I guess, I have a weird bug in thte backend, though I would exspect server and not go binary releated

After looking at the [code](https://github.com/go-gitea/gitea/blob/803b0c9ab43f809e47f42fad951e7f5fb6652e42/services/repository/contributors_graph.go#L270-L273) that builds these Unix times, I haven't been able to determine the cause (or if the problem resides elsewhere). If you wish, you can open a new issue so that we can track this potential bug.

**Comment by snoweuph** [comment]
> > Side Information: I did the upgrade to 22 just 3 days ago, so I should have the bugfix already, right?
> 
> Yes, v1.22.0 should have it.
> 
> > So I guess, I have a weird bug in thte backend, though I would exspect server and not go binary releated
> 
> After looking at the [code](https://github.com/go-gitea/gitea/blob/803b0c9ab43f809e47f42fad951e7f5fb6652e42/services/repository/contributors_graph.go#L270-L273) that builds these Unix times, I haven't been able to determine the cause (or if the problem resides elsewhere). If you wish, you can open a new issue so that we can track this potential bug.

I just opend up #31248
