### ISSUE TITLE
Impossible to use OpenID tokens more than a 255-byte length

### ISSUE THREAD

**Issue by arzustudent** [go-gitea/gitea#30868]
### Description

Attempting to use a OpenID token more than 255 bits in length results in a 500-Server error. Tested in both gitea and forgejo.

# Versions affected:
All

# Reproduction steps:
Compile any version of gitea
Use PostgreSQL as the database
Add a new OAuth source using a provider that supports tokens of over 255 bits in length (e.g burgerauth)
Attempt to use a OpenID account link using this provider

# Problematic file
[Line 939 in /routers/web/auth/oauth.go](https://github.com/go-gitea/gitea/blob/main/routers/web/auth/oauth.go#L939)
Suspected to be an issue with PostgreSQL limiting a table to 255 bits, as the error is returned by pq.

# Full error and log
Server:
...rs/web/auth/oauth.go:946:SignInOAuthCallback() [E] UserLinkAccount: pq: value too long for type character varying(255)

Client (admin):
An error occurred:
UserLinkAccount, pq: value too long for type character varying(255)

### Gitea Version

982b20d259e5bcd94377820ca3559112add36a1b

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/arzustudent/22bfcc007282aa2ff4d4ae2e26ec0abb

### Screenshots

N/A

### Git Version

git version 2.43.0

### Operating System

EvolutionOS Busybox/Linux & Fedora GNU/Linux

### How are you running Gitea?

Compiled from source using GNU Make and the latest version of go, on EvolutionOS Busybox/Linux. Also reproduced on Fedora GNU/Linux, using forgejo and GNU Make.

### Database

PostgreSQL

**Comment by arzustudent** [comment]
Note this is against compliance of the OCID specifications, which do not state a data limit for OpenID Identity Tokens. I recommend removing the limit, and so allowing tokens of all sizes to be able to be used, which would be especially useful for more space-consuming JWT token algorithms like RSA.

**Comment by wxiaoguang** [comment]
For "OpenID Identity Token": do you mean the "sub" field? https://openid.net/specs/openid-connect-core-1_0.html

```
sub
    REQUIRED. Subject Identifier. A locally unique and never reassigned identifier within the Issuer for the End-User, which is intended to be consumed by the Client, e.g., 24400320 or AItOawmwtWwcT0k51BayewNvutrJUqsvl6qs7A4. It MUST NOT exceed 255 ASCII [[RFC20]](https://openid.net/specs/openid-connect-core-1_0.html#RFC20) characters in length. The sub value is a case-sensitive string.
```

**Comment by arzustudent** [comment]
> For "OpenID Identity Token": do you mean the "sub" field? https://openid.net/specs/openid-connect-core-1_0.html
> 
> > sub
> > REQUIRED. Subject Identifier. A locally unique and never reassigned identifier within the Issuer for the End-User, which is intended to be consumed by the Client, e.g., 24400320 or AItOawmwtWwcT0k51BayewNvutrJUqsvl6qs7A4. It MUST NOT exceed 255 ASCII [[RFC20]](https://openid.net/specs/openid-connect-core-1_0.html#RFC20) characters in length. The sub value is a case-sensitive string.

Possibly. I am not the primary maintainer of burgerauth, so I will review the source code to make sure that it's not a problem with upstream burgerauth.
