### ISSUE TITLE
Migration from 298 to 280 possible? (Database, error)

### ISSUE THREAD

**Issue by tgrothe** [go-gitea/gitea#30867]
### Description

Hi, I'm using Gitea with Docker compose ... As far, I'm using the nightly image build, but I would like to change to latest image build.

I get the following message at starting:

`...ations/migrations.go:628:Migrate() [F] Migration Error: Your database (migration version: 298) is for a newer Gitea, you can not use the newer database for this old Gitea release (280).`

Is there a chance to "downgrade" the version back to 280?

### Gitea Version

1.21.11

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

2.40.1

### Operating System

Debian 12

### How are you running Gitea?

Within a `docker-compose.yml`.

### Database

MySQL/MariaDB

**Comment by KN4CK3R** [comment]
You can downgrade with a backup 😃 I don't think you can rollback these 18 migrations. You could switch to a fixed digest and then to a non-nightly version when that version is newer.

**Comment by tgrothe** [comment]
> You could switch to a fixed digest and then to a non-nightly version when that version is newer.

That was my thought too, to wait a little until the "latest" version is updated... Thanks. :)

**Comment by wxiaoguang** [comment]
1.22-nightly is pretty stable now and it will become 1.22.0 soon. Welcome to try it!

**Comment by tgrothe** [comment]
> 1.22-nightly is pretty stable now and it will become 1.22.0 soon. Welcome to try it!

Thanks, I will try it.

**Comment by tgrothe** [comment]
@wxiaoguang Looks very good, Gitea is running (with `image: gitea/gitea:1.22-nightly`):

![grafik](https://github.com/go-gitea/gitea/assets/85501570/fa0545e9-ff2a-4a9f-b8c0-6fba1c77601c)

Thanks. I think, once version 1.22 is released under "latest" I can switch to this image. :)
