### ISSUE TITLE
render markdown in html in markdown

### ISSUE THREAD

**Issue by KiaraGrouwstra** [go-gitea/gitea#30863]
### Feature Description

it would be nice if gitea could render markdown in html in markdown.
on github this now lets us use html `<details>` tags while still allowing us to write markdown inside.

**Comment by wxiaoguang** [comment]
Gitea already supported it?

https://try.gitea.io/wxiaoguang/test/issues/33

```
<details>
    <h1>title</h1>
    <a href="/">link</a>
</details>
```

![image](https://github.com/go-gitea/gitea/assets/2114189/010ed33c-65cc-4032-ba9e-5785dccde37a)

**Comment by KiaraGrouwstra** [comment]
apologies, i forgot a breakline before starting my codeblock and it failed to render.
i'll close unless that's a bug.
