### ISSUE TITLE
Does not redirect back to the project page after creating an issue.

### ISSUE THREAD

**Issue by layonferreira** [go-gitea/gitea#30864]
### Description

Go to projects -> new issue

In new issue -> create issue

Page redirects to the new issue show page instead of the project page.

### Gitea Version

v1.21.11

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

I'm using the latest docker image.

### Database

None

**Comment by layonferreira** [comment]
I missed this context on my description:
But it looks like this was a regression since it looks like it was working on [17211](https://github.com/go-gitea/gitea/pull/17211) and https://github.com/go-gitea/gitea/pull/23971

**Comment by wxiaoguang** [comment]
Fix incorrect issue form #30881

**Comment by wxiaoguang** [comment]
ps: the problem is not simply a regression, so the fix will only be in 1.22
