### ISSUE TITLE
MSSQL error `DROP INDEX IF EXISTS: Incorrect syntax near the keyword ‘IF’`

### ISSUE THREAD

**Issue by wxiaoguang** [go-gitea/gitea#30872]
https://forum.gitea.com/t/add-support-for-sha256-git-repositories-failed/9062

> 2024/04/30 17:15:03 routers/init.go:72:mustInitCtx() [F] ...  failed: migrate: migration[286]: Add support for SHA256 git repositories failed: DROP INDEX IF EXISTS [IDX_commit_status_context_hash] ON [commit_status] mssql: Incorrect syntax near the keyword ‘IF’.

@lunny

**Comment by silverwind** [comment]
Which MSSQL version? The forum link seems 404.

https://learn.microsoft.com/en-us/sql/t-sql/statements/drop-index-transact-sql?view=sql-server-ver16 indicates 2016 and above supports `IF EXISTS` clause.

**Comment by lunny** [comment]
The forum is under maintaining. https://discord.com/channels/322538954119184384/537668686173962260/1237579999708577803
