### ISSUE TITLE
Portainer webhook support

### ISSUE THREAD

**Issue by AR2000AR** [go-gitea/gitea#30899]
### Feature Description

I am currently using Portainer to deploy and update docker-compose stacks hosted on my gitea instance. I would like to be able to add a proper webhook to automatically update my stacks when pushing to the repos. Currently I make it work using the `Gitea` webhook.

References :
https://docs.portainer.io/user/docker/stacks/webhooks
https://docs.portainer.io/user/docker/stacks/add#gitops-updates

**Comment by lunny** [comment]
Maybe we can do that after #19307

**Comment by techknowlogick** [comment]
Closing/Merging this into https://github.com/go-gitea/gitea/issues/1089

A (temporary) workaround, as an alternative to what you are doing, could be to send a webhook via Gitea Actions. Although your workaround may be more effective
