### ISSUE TITLE
Commit hashes are different sizes and overflow on homepage

### ISSUE THREAD

**Issue by JanRomero** [go-gitea/gitea#30919]
### Description

Sorry if this is a dupe, I searched for everything that came to mind...

After upgrading to 1.22.0-rc1 the homepage has this problem with commit ids both in Firefox and Edge. This only happens for long commit messages and is reproducible on try.gitea.io if you can find or fake a long message. For example, go to [Lunny’s activity](https://try.gitea.io/lunny?tab=activity) and use dev tools to make one of the commit messages longer.

It seems to be fixed by adding `flex-shrink: 100;` to the commit message `<span>`, but not sure if that will cause problems elsewhere. I’ve only played around in the browser tools.

Thank you!

### Screenshots

![grafik](https://github.com/go-gitea/gitea/assets/7873027/446877c6-adc3-4c75-89f7-947df0d77a94)

### Gitea Version

1.22.0-rc1

### Can you reproduce the bug on the Gitea demo site?

Yes

### Browser Version

Firefox and MsEdge latest

**Comment by wxiaoguang** [comment]
->  Fix some UI regressions for commit list #30920
