### ISSUE TITLE
LFS client version too old

### ISSUE THREAD

**Issue by rekcah1986** [go-gitea/gitea#30913]
### Description

**docker log:** failed to synchronize LFS objects for repository: LFS client version too old, please upgrade your LFS client greater than v2.4.0

### Gitea Version

latest

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/3055444/70dc6a11-052c-47d4-8e51-acaf3c442fd9)

### Git Version

2.40.1

### Operating System

docker image gitea/gitea

### How are you running Gitea?

I created a container based on the 'gitea/gitea' image in Docker. When syncing the mirror's original repository, I found that LFS could not be pulled correctly.

### Database

SQLite

**Comment by wolfogre** [comment]
The error seems to be returned by the mirror source server. Could you please provide more information about it? What is it? GitHub, Gitlab, or what? Or is it a public repo that you can share with us?
