### ISSUE TITLE
Incorrect migration protocol from Gitlab

### ISSUE THREAD

**Issue by linuxoid69** [go-gitea/gitea#30938]
### Description

Good afternoon.
I have a question.
Why when I make a migration request via **HTTPS** I see **HTTP** in the logs?

When I try to perform a clone via: 
`git clone https://gitlab.my-itclub.ru/devops/shedding.git`
I don't get an error
I see the error only through 
`git clone http://gitlab.my-itclub.ru/devops/shedding.git`

### Gitea Version

1.21.11

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

https://gist.github.com/linuxoid69/7a615e23b4bd1e212e3f5de0b93090d6

### Screenshots

![migration_fail](https://github.com/go-gitea/gitea/assets/2655695/43a6fb8d-9604-4b2f-bac9-d3ad2f4181ab)

### Git Version

2.40.1

### Operating System

Alpine Linux v3.18.6

### How are you running Gitea?

docker 
run as gitea/gitea:1.21.11 without args 

### Database

PostgreSQL

**Comment by lunny** [comment]
Maybe it's related. The clone URL is the address from the information back from GitLab's repository information API.

<img width="430" alt="image" src="https://github.com/go-gitea/gitea/assets/81045/b638c4c7-6553-4768-a509-10ade48311ff">

**Comment by linuxoid69** [comment]
> Maybe it's related. The clone URL is the address from the information back from GitLab's repository information API.
> <img alt="image" width="430" src="https://private-user-images.githubusercontent.com/81045/329770619-b638c4c7-6553-4768-a509-10ade48311ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MzE3MTMsIm5iZiI6MTcxNTQzMTQxMywicGF0aCI6Ii84MTA0NS8zMjk3NzA2MTktYjYzOGM0YzctNjU1My00NzY4LWE1MDktMTBhZGU0ODMxMWZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDEyNDMzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjYzU1MTQxNzJiMzc1MGNjMmVjODk3MTJhMTNlY2ZmYjM2ZWY0YWIwY2M2MGU5NTMyMGFiYzA0Y2NhOTIwNWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0Ms1LaCqo_Cfbf38ogF6JPQnt_D-W_zs8cHgvRdzlC4">

I changed **external_url** in Gitlab config to https and it resolved
@lunny thx so much
