### ISSUE TITLE
Label in upload and new file button not show more

### ISSUE THREAD

**Issue by webjoel** [go-gitea/gitea#3094]
- Gitea version (or commit ref): 3b89ee5
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (https://try.gitea.io/webjoel/teste)
  - [ ] No
  - [ ] Not relevant

## Description

Font-size in upload e new file buttons were replace after issue #3091, now not show label more.

problem (font-size: 1em) in index.css:
`.ui .menu:not(.vertical) .item .button {
    padding-bottom: .78571429em;
    padding-top: .78571429em;
    font-size: 1em;
}`

## Screenshots
![captura de tela de 2017-12-05 09-01-05](https://user-images.githubusercontent.com/1946348/33604576-9fc30ea6-d99d-11e7-9d3c-ebcfbe11a1ca.png)

**Comment by silverwind** [comment]
I'll check this out later.
