### ISSUE TITLE
repo directory path styles

### ISSUE THREAD

**Issue by stuzer05** [go-gitea/gitea#30940]
### Description

![image](https://github.com/go-gitea/gitea/assets/23124682/c45ce00d-1e22-4d64-86b7-0574bd36f7cc)

path block is too short

### Gitea Version

1.22.0+rc1-72-ge94723f2de

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

docker

### Database

None

**Comment by wxiaoguang** [comment]
Regression of Improve repo button row layout (#30668)
