### ISSUE TITLE
Dash in URL breaks hyperlink parsing

### ISSUE THREAD

**Issue by svarlamov** [go-gitea/gitea#3095]
- Gitea version (or commit ref): 3b89ee5
- Example: https://try.gitea.io/svarlamov/foobar-issues-example/issues/1

## Description

When posting an issue by cut-n-pasting a URL like https://example.com/something/my-link the URL parsing works and I get a pretty hyperlink after posting. However, this url https://sample.example.com/:i:/p/foobar/helloworld-foo?abc=123 breaks. Ie., the link is only the `https://sample.example.com/:i:/p/foobar/helloworld` part, whereas `-foo?abc=123` just looks like normal text and when I click on the part that got recognized as a link, it directs me without the `-foo?abc=123` part -- which is not where I wanted to go!

I have this problem quite often when posting links to screenshots in Gitea (because the image upload is very painful, ref #3032)... But even now that I'm posting URLs, it's still not happy... 😢 

## Screenshots

![image](https://user-images.githubusercontent.com/10859025/33613316-ea551644-da06-11e7-8994-30771b87ec4f.png)

**Comment by lukewatts** [comment]
Is there any update on if this is being looked into? Or when a fix might be implemented?

**Comment by lafriks** [comment]
@lukewatts This PR #3354 could possible solve this

**Comment by lunny** [comment]
Since #3354 merged, I'll close this one. Please feel free to reopen it.
