### ISSUE TITLE
Initialization of the Repository index fails

### ISSUE THREAD

**Issue by seijikun** [go-gitea/gitea#3098]
- Gitea version (or commit ref): 1.3.0
- Git version: 2.15
- Operating system: Gentoo Linux
- Database:
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist: [https://gist.github.com/seijikun/e28a3e135c7986f1f2b159964714b62f](https://gist.github.com/seijikun/e28a3e135c7986f1f2b159964714b62f)

## Description
The initialization of the repository index fails.
**Info that may be relevant / related:** The repo that is mentioned in the error is referenced as a submodule from one or more other repositories (that reside on the affected gitea instance aswell).

**Comment by lafriks** [comment]
Code search is enabled in that instance?

**Comment by seijikun** [comment]
I set `REPO_INDEXER_ENABLED = true` if that is, what you meant.
The error only occured after doing so.

**Comment by lafriks** [comment]
Yes that repository indexer for code search. (@ethantkoenig)

**Comment by ethantkoenig** [comment]
I'll take a look (hopefully tonight)

**Comment by lunny** [comment]
maybe we should ignore submodules?

**Comment by ethantkoenig** [comment]
@lunny Yes, I'll work on that as soon as I get the chance (most likely tomorrow).
