### ISSUE TITLE
home page title overflow

### ISSUE THREAD

**Issue by yp05327** [go-gitea/gitea#30982]
### Description

![image](https://github.com/go-gitea/gitea/assets/18380374/006f2c59-e97d-4cf2-80bc-cf49ee8e5361)

### Gitea Version

latest

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

cloud

### Database

None

**Comment by metiftikci** [comment]
@yp05327 can you still reproduce this? i can not

**Comment by yp05327** [comment]
It seems that this has been fixed
