### ISSUE TITLE
LFS: unable to push objects tracked by git LFS

### ISSUE THREAD

**Issue by flozz** [go-gitea/gitea#3101]
- Gitea version (or commit ref): master (c7fb6e30870ea1abff13a8214107e0747d293320)
- Git version: 2.11.0
- Operating system: Ubuntu 17.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant  (LFS seems to not be available)
- Log gist: https://gist.github.com/flozz/e235a55a88d4f6d74eed66fe8c9d7d47

## Description

I am not able to push objects tracked by git LFS anymore (tester on latest master). Steps to reproduce:

```
$ git git clone http://localhost:3000/test/test-lfs.git
Cloning into 'test-lfs'...
warning: You appear to have cloned an empty repository.

$ cd test-lfs

$ git lfs install
Updated git hooks.
Git LFS initialized.

$ git lfs track "*.txt" --lockable
Tracking "*.txt"

$ echo test > foobar.txt

$ git add -A
warning: CRLF will be replaced by LF in .gitattributes.
The file will have its original line endings in your working directory.

$ git commit -m test
[master (root-commit) 8fdb137] test
 2 files changed, 4 insertions(+)
 create mode 100644 .gitattributes
 create mode 100644 foobar.txt

$ git push
Username for 'http://localhost:3000': test
Password for 'http://test@localhost:3000': 
Username for 'http://localhost:3000': test
Password for 'http://test@localhost:3000': 
Locking support detected on remote "origin". Consider enabling it with:
  $ git config lfs.http://localhost:3000/test/test-lfs.git/info/lfs.locksverify true
Git LFS: (0 of 1 files) 0 B / 5 B                                                                               
LFS: Repository or object not found: http://localhost:3000/test/test-lfs/info/lfs/objects/f2ca1bb6c7e907d06dafe4687e579fce76b37e4e93b7605022da52e6ccc26fd2
Check that it exists and that you have proper access to it
error: failed to push some refs to 'http://localhost:3000/test/test-lfs.git'
```

**Comment by flozz** [comment]
LFS seems to be broken since PR #3016:

commit c80d147fa911c2aa711bc3f310d7bef11681230b works
commit 4035ab05fa2d2c8ec95d346fea91cab8211dab17 do not work

@sapk are you already working on this in your PR #3092 or is this a different bug?

**Comment by sapk** [comment]
This shoudl be fix by https://github.com/go-gitea/gitea/pull/3092/commits/93726dce7064a5629f5d348ddba5ae8eec6a66ea in the PR your reference. tests are failing since the docker image used for testing need to be updated. I will rebase to restart the tessts on drone.

**Comment by flozz** [comment]
Ok thank you, I will test with this commit then :D

**Comment by flozz** [comment]
I confirm it works with latest commit of PR #3092 :)

**Comment by sapk** [comment]
I hope to finish it tonigth. ;-)
