### ISSUE TITLE
Deleted branch still visible in branch list and 404 on access

### ISSUE THREAD

**Issue by MrTypename** [go-gitea/gitea#31018]
### Description

When I delete a branch by web interface or by 'git push' the branch is listed as deleted within the repo branch overview. Following the branch link I get a 404 error. Is this behaviour intended ? Note that after a 'restore' the branch is accessible again. How can I remove a deleted branch completely ?

Note: try.gitea.io is currently not accessible ?!

### Gitea Version

1.21.11

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![c0](https://github.com/go-gitea/gitea/assets/36326219/83f97662-ec8e-4e96-82b0-b29666a80d8e)
![c1](https://github.com/go-gitea/gitea/assets/36326219/1ff83bb2-6cc2-41df-a5da-daa52b5e35ef)

### Git Version

2.40.1

### Operating System

Ubuntu 22.04.4

### How are you running Gitea?

Docker image:
https://hub.docker.com/layers/gitea/gitea/1.21.11/images/sha256-0abba6432e37944cd13b47aa0c6ffb958e1a22d7b3795c723267ac92163b774f?context=explore

### Database

MySQL/MariaDB

**Comment by kemzeb** [comment]
Thanks for the bug report!

When you delete a branch, we do keep it around in the DB until [this cron job](https://github.com/go-gitea/gitea/blob/339bc8bc8fdb4ead3c43b4604b100f83e6f47cb5/services/cron/tasks_basic.go#L105) goes ahead and removes it and any other deleted branches. From reading the associated code it looks like it is done every midnight for branches that were deleted at least a day ago.

**Comment by kemzeb** [comment]
From looking around a bit further, you can even configure this particular cron task, see [here](https://github.com/go-gitea/gitea/blob/339bc8bc8fdb4ead3c43b4604b100f83e6f47cb5/custom/conf/app.example.ini#L2043) for more details. For some reason I can't find it in the web documentation so I may file an issue for that.

**Comment by kemzeb** [comment]
Created #31022 to add web docs for deleted branch cleanup. Let me know if you have any further questions.

**Comment by lunny** [comment]
We can remove the link of the branch name.

**Comment by MrTypename** [comment]
Thanks for your fast response. The cron task for this job was disabled. The issue is now solved.
