### ISSUE TITLE
Cant add Collaborator with username + fullname in round brackets

### ISSUE THREAD

**Issue by FCBone** [go-gitea/gitea#3102]
- Gitea version (or commit ref): 1.3.0+4-gb9abcb3
- Git version: git-1:2.1.4-2.1+deb8u5
- Operating system: Rasbian Jessie
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant

## Description

On Page "Repository"/settings/collaboration there is following bug:
Want to set new Collaborator
-->i'm searching for an user with the following specs:
Username: "usrnm"
Fullname: "fullnm"
-->the searched user is found and displayed like the following: usrnm (fullnm)
-->If i click on the shown user, than the Username inclusive the complete Fullname in round brackets are written within the "User searching"-Field.
-->After i'm clicking "Add New Collaborator" there comes the failure "The user does not exist."

If i'm deleting the fullname in the round brackets everything works fine.

I searched for such an issue but didn't found one like this, so hopefully it isn't doubled, if yes please close the issue and tell me in what issue, this is written, so i can watch this issue.

## Screenshots

I think this isn't really necessary, and i don't want to show any other user within this issue.

**Comment by svarlamov** [comment]
Might be similar to https://github.com/go-gitea/gitea/pull/2973

**Comment by svarlamov** [comment]
I can also confirm that I'm experiencing the same issue... Will investigate a potential fix -- there might also be other similarly-affected areas in the UI...

**Comment by lunny** [comment]
resolved by #3103
