### ISSUE TITLE
Project Group for multiple repositories.

### ISSUE THREAD

**Issue by KevinKrueger** [go-gitea/gitea#31038]
### Feature Description

The core idea comes from the BitBucket spectrum by combining several repositories into one project group.

I think it would be sufficient for the start if you can create a project group then:
1. create a completely new project in the group or
2. assign an existing repository to a group.

first "only" visual grouping 

What do you think?

### Screenshots

https://confluence.atlassian.com/bitbucketserver/creating-projects-776639848.html
https://confluence.atlassian.com/bitbucketserver/creating-repositories-776639815.html

**Comment by crabdancing** [comment]
This is not only a good idea, it's also critical for scalable deployment setups, e.g., where you need to have the same deploy key across a large swath of repositories.

**Comment by lunny** [comment]
What's the different from #1872 ?

**Comment by techknowlogick** [comment]
Merging into 1872
