### ISSUE TITLE
Fail to serve RPC(upload-pack)

### ISSUE THREAD

**Issue by sudoexec** [go-gitea/gitea#31036]
### Description

When cloning a git repo(184M,40000 commits), git client failed with:
```
remote: aborting due to possible repository corruption on the remote side.
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
```

server logs:
```
2024/05/21 06:39:04 .../web/repo/githttp.go:485:serviceRPC() [E] Fail to serve RPC(upload-pack) in /data/git/repositories/xxx/xxx.git: exit status 128 - error: pack-objects died of signal 9
error: git upload-pack: git-pack-objects died with error.
fatal: git upload-pack: aborting due to possible repository corruption on the remote side.
```

### Gitea Version

1.21.11

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

2.45.1

### Operating System

Kubernetes

### How are you running Gitea?

Kubernetes

### Database

None

**Comment by lunny** [comment]
Maybe this helpful for you. https://confluence.atlassian.com/bitbucketserverkb/git-operations-fail-due-to-git-pack-objects-died-with-error-849169949.html

**Comment by sudoexec** [comment]
> Maybe this helpful for you. https://confluence.atlassian.com/bitbucketserverkb/git-operations-fail-due-to-git-pack-objects-died-with-error-849169949.html

Thanks for your reply, but those method don't help. The error as below:
```
error: pack-objects died of signal 9
```

When I execute `git repack`, the memory grow from 2.85G to 3G(total 4G), and then `git repack` quit.

**Comment by sudoexec** [comment]
It's not gitea's fault.
In my case, what I ignore is earlyoom kill the process.
