### ISSUE TITLE
Notifications remains after repository or issue deleted.

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#3105]
![image](https://user-images.githubusercontent.com/81045/33693416-c4122b3e-db2d-11e7-83f5-0cf28ebb1373.png)

**Comment by ethantkoenig** [comment]
I would like to make a friendly observation that we wouldn't have this problem if we used foreign keys.

**Comment by svarlamov** [comment]
@ethantkoenig I found it really crazy that Gitea doesn't use FKs after digging into the code the last few days... May I ask why this is the case?

**Comment by lunny** [comment]
@ethantkoenig @svarlamov I didn't implement FK in xorm.
