### ISSUE TITLE
API ListActionTasks is not sorted chronologically

### ISSUE THREAD

**Issue by mattfysh** [go-gitea/gitea#31066]
### Description

These are currently randomly sorted. Can they be updated to be sorted in reverse chronological order, i.e. the same as the Web UI?

https://github.com/go-gitea/gitea/blob/ec771fdfcdbc74320b1ef0252444aa5cddd50a04/routers/api/v1/repo/action.go#L562-L565

### Gitea Version

1.22.0+rc1-106-gedbf74c418

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

Via the helm chart

### Database

None

**Comment by lunny** [comment]
It's sorted by created time. I don't think it's a bug maybe an enhancement is better.

**Comment by mattfysh** [comment]
Hi Lunny, I’m not seeing it being sorted that way when I call the API, and
if you look at the source code I linked to you see there is no order clause
given to the FindAndCount method

**Comment by lunny** [comment]
Yes, there is no explicit order clause in `FindAndCount`. So the database should have a default one. Commonly it should be the `id asc` which is the same order as the `created`.

**Comment by mattfysh** [comment]
I’m not sure what the confusion is here but you’re saying that the endpoint
is sorted and I’m telling you it’s not

**Comment by mattfysh** [comment]
the web runtime correctly does a FindAndCount with ordering declared:

https://github.com/go-gitea/gitea/blob/ec771fdfcdbc74320b1ef0252444aa5cddd50a04/routers/web/shared/actions/runners.go#L77-L85

the API runtime does not:

https://github.com/go-gitea/gitea/blob/ec771fdfcdbc74320b1ef0252444aa5cddd50a04/routers/api/v1/repo/action.go#L562-L565

**Comment by mattfysh** [comment]
following up on request from @lunny in discord

> Could you give some proposals which order options should the API provide

I propose that the API should return the workflow_runs in the same order that the web runtime currently sorts the list, ie. add `IDOrderDesc: true`

@chesteripz @wolfogre do you have any thoughts?

**Comment by wolfogre** [comment]
> you’re saying that the endpoint is sorted and I’m telling you it’s not

In the absence of an explicit ﻿ORDER BY clause, different databases may return query results in varying orders due to their unique underlying implementations and optimizations.

So I believe @mattfysh did meet a "random" order result via API.

> I propose that the API should return the workflow_runs in the same order that the web runtime currently sorts the list

It makes sense. I think we can just drop the option `IDOrderDesc`, since it will be useless if it always true, and it is what `FindRunOptions` and `FindScheduleOptions` do.

So #31150
