### ISSUE TITLE
Bad ui in mobile view when the language is not english

### ISSUE THREAD

**Issue by yp05327** [go-gitea/gitea#31071]
### Description

in english: (not too bad)
![IMG_3912](https://github.com/go-gitea/gitea/assets/18380374/02c43814-d142-44e4-8d6e-130390584380)

in other language:
![IMG_3911](https://github.com/go-gitea/gitea/assets/18380374/935d1f3a-621c-4ff1-91ca-1101e7cc8b7f)

### Gitea Version

latest

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

gitea.com

### Database

None

**Comment by silverwind** [comment]
You mean remove the "Normal File" to make space for filename?

**Comment by silverwind** [comment]
Multiline layout is likely a good idea here to show sufficient amount of filename characters.

**Comment by yp05327** [comment]
![IMG_3956](https://github.com/go-gitea/gitea/assets/18380374/40cce688-cd3e-4b56-bcb7-228046a328c3)

a new problem

**Comment by silverwind** [comment]
> ![IMG_3956](https://private-user-images.githubusercontent.com/18380374/334350708-40cce688-cd3e-4b56-bcb7-228046a328c3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4ODk4NDIsIm5iZiI6MTcxNjg4OTU0MiwicGF0aCI6Ii8xODM4MDM3NC8zMzQzNTA3MDgtNDBjY2U2ODgtY2QzZS00YjU2LWJjYjctMjI4MDQ2YTMyOGMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI4VDA5NDU0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhYWI2ZGU2ZGU0MjIzZDk1MDcyZDA1YzU0MTcxNWQ5Mzc0ZmM3NGM2ZGIxMDI0NjQxZWJmYzUxOWJhZDUzYjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.y0uE6YDLLtOZ3xRpv7sZfxSusKJyFUyRIcgpYtDSHQo)
> 
> a new problem

Already fixed this overflow in https://github.com/go-gitea/gitea/pull/31091, if you give it a try.

**Comment by yp05327** [comment]
I think maybe you have already fixed it, so I reported it here. 😄
