### ISSUE TITLE
Creating a new release doesn't update list of releases properly

### ISSUE THREAD

**Issue by lordmulder** [go-gitea/gitea#31085]
### Description

After recently updating to Gitea 1.21.11, I'm experiencing the problem when I create a new release it's not showing at the top, as used to be, but at the very end. First I though the release had not been created at all, tried to create it again, but got an error that it already exists. Then I noticed that the release is actually showing up at very end, of the very last page. The same applies to the "Tags" view! Tried to delete it and then re-create it, but didn't change anything. Also I noticed that, on the "overview" page, my project is showing as "Updated last month", even though I pushed new commits and created a new release today. So, it seems that something isn't updating correctly...

### Gitea Version

1.21.11

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/lordmulder/f8788f55c189a978f5b6828e26560b61

### Screenshots

![grafik](https://github.com/go-gitea/gitea/assets/470590/e18143d6-ac81-4e8c-91dd-ab5c2899a31d)

![grafik](https://github.com/go-gitea/gitea/assets/470590/ba5f2567-2570-4e22-8cae-6acbcf57814e)

### Git Version

2.43.0

### Operating System

Linux (Ubuntu Server 24.04)

### How are you running Gitea?

Using the pre-built binaries form dl.gitea.com, latest "stable" version.

### Database

SQLite

**Comment by lordmulder** [comment]
Okay, after upgrading to version **1.22.0** today, I actually saw a warning that my repository is out of sync in Gitea GUI, which I did _not_ see before with version 1.21.11. The suggested fix to run _"Resynchronize pre-receive, update and post-receive hooks of all repositories"_ actually seems to fix my problem, but only after I also pushed a new commit and re-created the tag.

**Comment by lunny** [comment]
So now your instance is normal and the warning disappeared?

**Comment by lordmulder** [comment]
Yes, it seems so. But only after I applied the suggested fix _and_ then pushed another commit.

Had to create a "fake" commit, so that there was something new that I could push.

Don't know why the problem occurred in the first place. Whether it will happen again, only the future will tell 😏
