### ISSUE TITLE
PR feature merge hints

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#311]
After pushing a new branch to forked repository, on original repository or forked repository, It should have hints to create a new pull request.

**Comment by bkcsoft** [comment]
Like GitHub/GitLab has a `Create merge/pull-request`-button when a new branch has been pushed?

If so, a `View Pull Request`-button as well when there is an open PR for the current branch :)

**Comment by kolaente** [comment]
Superseeded by https://github.com/go-gitea/gitea/issues/13196
