### ISSUE TITLE
[ Mail ] Render title

### ISSUE THREAD

**Issue by Sharaf5** [go-gitea/gitea#31108]
### Description

Rigistration email title is alway "Welcome to gitea" even with my instance AppName is "DevOps"

> issue Regen :
> Start any gitea instance
> - make sure AppName is anything rather than gitea
> - make sure mail is enabled and functional
> create new user and check `Send user registiratiin notification`
> check the mail `body` you would find your `AppName`
> check the mail `title` you would find `Welcome to gitea`

I tried looking for local translation, then understood it's hard coded in locals
however I don't see where the title is renderd in code : seems title is always static
Any way to make it render this title for the site name itself

### Gitea Version

1.22.0-rc1

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![Screenshot_20240527_162313](https://github.com/go-gitea/gitea/assets/36330265/b789e353-e11f-480c-83c7-6bbc78a7fa85)

### Operating System

dockerized

### How are you running Gitea?

inside docker

### Database

None

**Comment by alex-kattathra-johnson** [comment]
I'd like to pick this up as a first issue to work on.

**Comment by SunnyWan59** [comment]
Is it possible for me to work on this?

**Comment by kemzeb** [comment]
Does #31562 close this issue?

**Comment by 6543** [comment]
Yes
