### ISSUE TITLE
Repository categories tab looks wired on dashbaord

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#31115]
<img width="465" alt="image" src="https://github.com/go-gitea/gitea/assets/81045/db2368fc-4993-4c87-af19-5c0ba4bd59f5">

**Comment by silverwind** [comment]
What's weird? Looks as expected. There is not enough space to render all so it moves the overflow into "...".

**Comment by lunny** [comment]
<img width="109" alt="image" src="https://github.com/go-gitea/gitea/assets/81045/1a9073da-ea50-4568-9215-09444caf9c6d">
I mean the two lines should be more close like other tabs?

**Comment by silverwind** [comment]
Hmm yes, there was no space there in 1.21, likely a small visual regression.
