### ISSUE TITLE
memcache support broken

### ISSUE THREAD

**Issue by tgerczei** [go-gitea/gitea#31114]
### Description

After upgrading to 1.22.0 from 1.21.11 I see that the Gitea server fails to start when cache.ADAPTER is set to "memcache".

### Gitea Version

1.22.0

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

https://gist.github.com/tgerczei/2cf428ee26c0d04bc0e7df1ec0f6e81a

### How are you running Gitea?

Via the  gitea/gitea:1.22.0-rootless image pulled from Docker Hub.

### Database

None

**Comment by tgerczei** [comment]
Sorry, I did search for the open issues first, didn't think of checking closed ones too so I hadn't realized I was duping. Thanks!

**Comment by wxiaoguang** [comment]
1.22-nightly is ready, could you try it? Thank you for reporting the issue and sorry for the inconvenience

**Comment by tgerczei** [comment]
Thank you! I've been running it for about 2 hours now, and it seems to have fixed this. Kudos!
