### ISSUE TITLE
Missing memcache adapter

### ISSUE THREAD

**Issue by hwaastad** [go-gitea/gitea#31123]
### Description

After upgrading to 1.22, gitea failes to start with the following message:
```
code.gitea.io/gitea/modules/cache.Init failed: cache: unknown adapter 'memcache'(forgot to import?)
```
app.ini:
```
[cache]
ENABLED = true
ADAPTER = memcache
INTERVAL = 60
HOST = <memcache-host>
```

### Gitea Version

1.22.0

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

Running gitea container gitea/gitea:1.22.0-rootless

### Database

PostgreSQL

**Comment by eeyrjmr** [comment]
Duplicate of #31102
This has been fixed in the 1.22 nightlyies

**Comment by wxiaoguang** [comment]
Sorry for the inconvenience, please use 1.22 nightly:

https://hub.docker.com/r/gitea/gitea/tags?page=&page_size=&ordering=&name=1.22-nightly-rootless

**Comment by hwaastad** [comment]
Great. closing in favor of https://github.com/go-gitea/gitea/issues/31102
