### ISSUE TITLE
Project Board view, not all the columns' border radius are circle.

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#31129]
Only the last column's border radius is circle.

<img width="1198" alt="image" src="https://github.com/go-gitea/gitea/assets/81045/494e1bfc-3f17-4658-80f7-0dd9eb54d6c1">

**Comment by silverwind** [comment]
Can't reproduce. Can you provide a example on https://demo.gitea.com?

**Comment by silverwind** [comment]
https://github.com/go-gitea/gitea/pull/31204 will fix it.
