### ISSUE TITLE
gitea 1.22 docker image started having "illegal instruction (core dump)" issue

### ISSUE THREAD

**Issue by chriseizus** [go-gitea/gitea#31138]
### Description

gitea 1.22 docker image started having "illegal instruction (core dump)" issue

rollback to 1.21 has no issue but 1.22 is showing only above error in the container log

### Gitea Version

1.22

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

1.22

### Operating System

RHEL 8.9

### How are you running Gitea?

through docker image

### Database

SQLite

**Comment by wxiaoguang** [comment]
And what's the CPU arch? Mismatched CPU arch would also lead to "illegal instruction" crash.

**Comment by chriseizus** [comment]
This is not changed and it works in 1.21 but failed in 1.22

processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 63
model name      : Intel(R) Xeon(R) Platinum 8362 CPU @ 2.80GHz
stepping        : 0
microcode       : 0xd00037b
cpu MHz         : 2793.437
cache size      : 49152 KB
physical id     : 0
siblings        : 6
core id         : 0
cpu cores       : 6
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
