### ISSUE TITLE
404 ERROR when I want to make a PULL REQUEST 

### ISSUE THREAD

**Issue by soufDev** [go-gitea/gitea#3113]
I have many project in gitea, in other project I can make a pull request easily, but in one of them when I try to make a pull request I have 404 ERROR, I will put a screen shot for more details.
thank you.

![capture du 2017-12-07 13-09-46](https://user-images.githubusercontent.com/15775944/33714624-efb3d860-db4f-11e7-9baa-572246a685d2.png)

**Comment by zxjon22** [comment]
Wonder if this is related to #2863 - you've deleted the original repo and are just using the fork?

**Comment by soufDev** [comment]
okey thank you

**Comment by soufDev** [comment]
no I deleted the fork and I already go to the original repo but it still the same, I think I have to reupload the origin repo
