### ISSUE TITLE
"command line instructions" for agit PR is incorrect

### ISSUE THREAD

**Issue by Shuenhoy** [go-gitea/gitea#31135]
### Description

See the screenshot.  Possible options may be `git fetch -u refs/pull/123/head:agit-topic` or  `tea pr co --branch 123` with `tea`.

### Gitea Version

1.22.0

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/2196156/5b28569e-834d-4fae-a4aa-1d680402acd5)

### How are you running Gitea?

Docker

### Database

PostgreSQL

**Comment by lunny** [comment]
Thank you for the reporting. And I think maybe we can add `tea` support later. see #31219
