### ISSUE TITLE
Review Menu Shown Behind

### ISSUE THREAD

**Issue by metiftikci** [go-gitea/gitea#31144]
### Description

after #31062 popup menu shown behind if section collapsed

all headers are sticky and their `z-index` are same. so upper menu cant visible on front

https://github.com/go-gitea/gitea/blob/4fe415683e685838fde4e11f14f0309bbadb36e4/templates/repo/diff/box.tmpl#L113

if i decrease z-index of second header it work but i believe this is not the correct solution

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/29250154/7b300e83-2253-4e44-a908-cd5397be4d36)

Edit:

Github uses extra class for menu's header

![image](https://github.com/go-gitea/gitea/assets/29250154/15dc60c8-ee54-4982-960f-992311a23738)

### Gitea Version

latest

### Can you reproduce the bug on the Gitea demo site?

No

### Browser Version

latest

**Comment by silverwind** [comment]
Ideally such menus shouldn't be z-fighting with the page elements in first place and this could be achieved by using tippy dropdown instead of fomantic dropdown.
