### ISSUE TITLE
Nginx reverse proxy setup returns bad request error with documentation config

### ISSUE THREAD

**Issue by Chamber3399** [go-gitea/gitea#31141]
### Description

Not sure if this is a bug tbh, I recently setup gitea 1.22.0 via docker image (never used gitea before), following the documentation on nginx reverse proxy.
Seems the **proxy_set_header Host $host** is causing a 400 bad request error.

Removing it fixes access to the webgui. However, when performing a git clone command, it would redirect to the webgui for authentication and authorization, which works, but an **ERR_SSL_PROTOCOL_ERROR** is thrown right after.

server config looks like this

```
[server]
APP_DATA_PATH = /data/gitea
DOMAIN = domain.com
SSH_DOMAIN = domain.com
ROOT_URL = https://domain.com/
DISABLE_SSH = false
SSH_PORT = 22
SSH_LISTEN_PORT = 22
LFS_START_SERVER = true
LFS_JWT_SECRET = 
OFFLINE_MODE = false
```

proxy config like this

```
server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name domain.*;

    include /config/nginx/ssl.conf;

    location / {
       
        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app gitea-ip;
        set $upstream_port 3000;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
        proxy_set_header Connection $http_connection;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

    }
}
```

I also tried the $http_host variable, but this also throws a bad request error
also tried the provided swag template for gitea

```
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    server_name domain.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    location / {
        
        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app gitea-ip;
        set $upstream_port 3000;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;

    }

    location ~ (/gitea)?/info/lfs {
        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app gitea-ip;
        set $upstream_port 3000;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;

    }
}
```

which does work for the webgui, but no git cloning.
cloning without the reverse proxy through http does work

### Gitea Version

1.22.0

### Operating System

Unraid

### How are you running Gitea?

Gitea runs on docker
Postgresql 15 docker as a database
Swag docker as reverse proxy (nginx)

each docker container has a unique LAN IP address, 443 is forwarded to swag

### Database

PostgreSQL

**Comment by wxiaoguang** [comment]
I am not sure whether you have mixed some different web servers together.

* `Seems the proxy_set_header Host $host is causing a 400 bad request error`: the question is "which program reports that 400 error"? UnRAID web server or Gitea?
* `but an ERR_SSL_PROTOCOL_ERROR is thrown right after`: it means that your web server's SSL part doesn't work properly.


----

* If you use Gitea under the same domain as UnRAID web, then you must put Gitea in a sub-path.
* If you use Gitea on a dedicated domain, which doesn't conflict with UnRAID, then you could try to look into the logs to figure out which part fails (nginx or Gitea)

The official document is here: https://docs.gitea.com/administration/reverse-proxies

**Comment by Chamber3399** [comment]
Thx for the fast response,

I have a subdomain config for each of my services running, so there should be no collision between any requests.
It's a bit weird to my that the webgui does work perfectly when removing the "proxy_set_header Host $host;", only thing that is not working is git.

I also checked the error log on both the proxy and the gitea server (error level set to debug), with no errors in both

**Comment by wxiaoguang** [comment]
Could you try to only use the sample from official doc?

https://docs.gitea.com/administration/reverse-proxies#nginx


```
server {
    #add here:
    server ...
    listen ...
    ssl ....

    # the official config
    location / {
        client_max_body_size 512M;
        proxy_pass http://localhost:3000;
        proxy_set_header Connection $http_connection;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
```

**Comment by Chamber3399** [comment]
This config gives me a 400 bad request error for the webgui, which is fixed when removing the "proxy_set_header Host $host;", I get no errors in both gitea log or the swag log (checking now if maybe I can set a better log level on the reverse proxy to make sure I get them all)

**Comment by wxiaoguang** [comment]
That's really weird. Most users are using Gitea behind nginx, this is the first report for "400" error. It's highly likely related to the reverse proxy config in my mind.

TBH I have no more idea about it. If you could provide a reproducible setup (eg: a docker compose) and it could reproduce on my machine, then I could try to continue to figure out.

**Comment by Chamber3399** [comment]
Hi,

so this is really weird, I just removed the whole proxy subdomain config file and started from scratch, copy pasted the config in the docs you also linked.... and now it seems to be working.

Been raging on this for a week, but it seems to work now with the following config:

```
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    server_name subdomain.*;
    add_header X-Robots-Tag "noindex, nofollow, nosnippet, noarchive";
    include /config/nginx/ssl.conf;
    add_header Strict-Transport-Security "max-age=15768000; includeSubDomains; preload;";
    client_body_buffer_size 400M;

    location / {
        client_max_body_size 512M;
        proxy_pass http://ip:3000;
        proxy_set_header Connection $http_connection;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

}
```

I think the issue was some config files that swag includes by default in their templates that are incompatible with gitea, the "include /config/nginx/proxy.conf;" line probably. Not sure what specific setting causes the error though.

Thank you very much for your help, really appreciate it

**Comment by wxiaoguang** [comment]
Glad to help. I think this issue could be closed. Feel free to open a new issue if there is anything wrong.
