### ISSUE TITLE
Slash in Docker package

### ISSUE THREAD

**Issue by lolen** [go-gitea/gitea#31159]
### Description

When publishing a docker image to packages and the name is `example.com/owner/repository/app:latest`, there is a problem with formatting the name when there is a slash (`/`)

Repository example:
https://demo.gitea.com/lolen/docker

Packages:
https://demo.gitea.com/lolen/docker/packages

### Gitea Version

1.23.0+dev-151-gc93cbc991e

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/3825268/56277322-0d83-4500-beca-5b1d4a850426)

### How are you running Gitea?

This is the latest version (1.22) running with binary and reverse proxy on nginx according to the official documentation, but I also reproduced this step on demo.gitea.com

### Database

None

**Comment by wxiaoguang** [comment]
What's your nginx config? The config document has been improved in 1.22

https://docs.gitea.com/administration/reverse-proxies

**Comment by wxiaoguang** [comment]
According to your screenshot, the URL `docker%2Fsecond` is right and expected. It must be escaped that way.
