### ISSUE TITLE
[Bug] Preview Changes

### ISSUE THREAD

**Issue by TimerWolf** [go-gitea/gitea#31157]
### Description

> 
> I have not test this a lot but it seems like "files" only created within gitea says "not found" when you try to use the "preview changes" tab, files that has a "local repo" as well works without any problems
> 
> I can't reproduce the bug, on [demo](https://gitea.com/Whiskey/Bug-1.22.0-PreviewTab/src/branch/main) site, but it worked fine in "1.21.11"

### Gitea Version

1.22.0

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/TimerWolf/16025f3b31158a59e86885050cabda51

### Screenshots

![Gitea](https://github.com/go-gitea/gitea/assets/6242514/5129fa94-ab05-48fb-9fbd-ed441a8295d3)

### Git Version

2.34.1

### Operating System

Ubuntu 22.04.3 (LTS)

### How are you running Gitea?

I download the version from github, i use the "gitea-1.22.0-linux-amd64" binary

### Database

MySQL/MariaDB

**Comment by wxiaoguang** [comment]
It's related to a recent permission check.  Will propose a fix soon.

**Comment by wxiaoguang** [comment]
->  Fix markup preview #31158
