### ISSUE TITLE
v1.22 cannot start with read-only rootfs (regression)

### ISSUE THREAD

**Issue by zdzichu** [go-gitea/gitea#31169]
### Description

Since v1.22, to be exact since https://github.com/go-gitea/gitea/commit/effb405cae88474c27f5c8322a2627019af1cf64  , Gitea tries to save generated `JWT_SECRET` and fails when the filesystem is read-only.
In earlier versions, setting `oauth2.ENABLE(D)` to False was enough to workaround this. Now the write is unconditional and prevents startup. (The idea for workaround came from https://github.com/wkulhanek/docker-openshift-gitea/issues/4)

Nb. I appreciate irony of big FIXME added by this commit.

### Gitea Version

1.22.0

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

```
Generating /data/ssh/ssh_host_ed25519_key...
Generating /data/ssh/ssh_host_rsa_key...
chown: /data/gitea/conf/..data: Read-only file system
chown: /data/gitea/conf/app.ini: Read-only file system
chown: /data/gitea/conf/..2024_05_29_14_34_44.3251774344/app.ini: Read-only file system
chown: /data/gitea/conf/..2024_05_29_14_34_44.3251774344: Read-only file system
chown: /data/gitea/conf/..2024_05_29_14_34_44.3251774344: Read-only file system
chown: /data/gitea/conf: Read-only file system
chown: /data/gitea/conf: Read-only file system
Generating /data/ssh/ssh_host_ecdsa_key...
Server listening on :: port 22.
Server listening on 0.0.0.0 port 22.
2024/05/29 18:07:03 cmd/web.go:242:runWeb() [I] Starting Gitea on PID: 19
2024/05/29 18:07:03 ...es/setting/oauth2.go:152:loadOAuth2From() [F] save oauth2.JWT_SECRET failed: failed to save "/data/gitea/conf/app.ini": open /data/gitea/conf/app.ini: read-only file system
Received signal 15; terminating.
```

### Operating System

Linux containers on k8s

### How are you running Gitea?

I'm using official `gitea/gitea:1.22.0` container image on self-hosted kubernetes. I'm using self-written helm chart.

Relevant parts of config:
```
[security]
INSTALL_LOCK = true

[oauth2]
ENABLED = false
JWT_SECRET = {{ .Release.Name | sha256sum | trunc32  | b64enc }}
```
(I know this way of generating secret is predictable, but I'ts ok for my usecase)

### Database

PostgreSQL

**Comment by wxiaoguang** [comment]
It is somewhat breaking but it is necessary for users to prepare the JWT_SECRET which is used as a general secret.

Just like other secrets (internal token, lfs jwt secret), please prepare them ahead correctly if you'd like to make the config file read-only.

**Comment by wxiaoguang** [comment]
> JWT_SECRET = {{ .Release.Name | sha256sum | trunc32  | b64enc }}

It looks really risky. Please prepare it by `./gitea generate secret JWT_SECRET`

And you could provide the secrets by files by using something like `JWT_SECRET_URI = file://.......`, then it could be shared across all containers.

**Comment by zdzichu** [comment]
> It is somewhat breaking but it is necessary for users to prepare the JWT_SECRET

But the JWT_SECRET is prepared and provided in app.ini file. Gitea insist in rewriting the file nevertheless.

**Comment by wxiaoguang** [comment]
> > It is somewhat breaking but it is necessary for users to prepare the JWT_SECRET
> 
> But the JWT_SECRET is prepared and provided in app.ini file. Gitea insist in rewriting the file nevertheless.

If the "prepared" one is not right (can't be used by Gitea), then Gitea will try to generated a new one and write it back.

So, please use the suggestion above: `./gitea generate secret JWT_SECRET` to generate a correct secret.

**Comment by zdzichu** [comment]
Using gitea-generated secret indeed works. Thanks for the suggestion.
Nb. I have 3 "secret" values in config now, INTERNAL_TOKEN, SECRET_KEY and JWT_SECRET. Feels like overkill.

**Comment by wxiaoguang** [comment]
Actually there is one more "LFS_JWT_SECRET" 😭 

That's why I left that "FIXME" in code, I think they should be simplified one day.
