### ISSUE TITLE
Will the support of Dingtalk be considered？

### ISSUE THREAD

**Issue by JermineHu** [go-gitea/gitea#3118]
- Gitea version (or commit ref):  `e22be08`
- Git version:  `git version 2.13.5`
- Operating system:
     **` Docker / Alpine `**
- Database (use `[x]`):
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:

## Description

**_Many companies use Dingtalk in the company, of course, we are also using it. We really hope that Gitea can support it. Recently, Gogs has already supported Dingtalk's Webhook. We have used Gitea as a repository, but it has not yet been supported._**

## Screenshots

**The Gitea webhook menu！**

![tim 20171208154120](https://user-images.githubusercontent.com/18027793/33755980-4609eeaa-dc2e-11e7-885d-cc1c3813e68a.png)

**The Gogs webhook menu！**

![tim 20171208152204](https://user-images.githubusercontent.com/18027793/33755981-46468644-dc2e-11e7-8437-7d096a35375b.png)

**Comment by lunny** [comment]
has been resolved via https://github.com/go-gitea/gitea/pull/2777, will release in v1.4
