### ISSUE TITLE
Markdown preview not found when Issue tracker and Pull requests are disabled

### ISSUE THREAD

**Issue by jorisdrenth** [go-gitea/gitea#31180]
### Description

The wiki markdown editor has an error where the preview gives "Not found" when the Issue tracker and Pull requests are disabled on a repository.

Steps to reproduce:
- create a repo
- go to settings
- uncheck "Enable Repository Issue Tracker" and "Enable Repository Pull Requests" and save the settings
- go to the wiki tab
- click "Create the first page"
- click on "Preview"

You will now see "Not found" in stead of a preview of your markdown.

The browser console will show a 404 on the URL "POST
https://demo.gitea.com/jorisdrenth/issue_test_2/markup"

### Gitea Version

1.22

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

Debian

### How are you running Gitea?

Binary, on a Debian based dedicated VPS.

### Database

SQLite

**Comment by MaxWipfli** [comment]
This was fixed by #31158
