### ISSUE TITLE
Template errors after update

### ISSUE THREAD

**Issue by Pawel-Bedn4rczyk** [go-gitea/gitea#31199]
### Description

Hi when I update gitea version. I can't run docker anymore.
I get many template errors like:

```
2024/05/31 13:30:34 ...ates/htmlrenderer.go:140:wrapTmplErrMsg() [F] Gitea can't run with template errors: template error: custom:admin/dashboard:5 : function "Str2html" not defined
----------------------------------------------------------------------
                                <p>{{(ctx.Locale.Tr "admin.dashboard.new_version_hint" .RemoteVersion AppVer) | Str2html}}</p>
                                                                                                                ^^^^^^^^
----------------------------------------------------------------------
```

When I start new instance of gitea docker with clean data everything works fine ;(

Any help or hint? Thanks

### Gitea Version

1.22

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

Linux 6.1.79-Unraid x86_64

### How are you running Gitea?

Docker selfhosted

### Database

MySQL/MariaDB

**Comment by wxiaoguang** [comment]
It has been document in the release blog:


![image](https://github.com/go-gitea/gitea/assets/2114189/b0872025-f839-4def-938d-de7bcb40a18c)

![image](https://github.com/go-gitea/gitea/assets/2114189/f930f1a7-e16b-4c8b-8131-cb424898d84e)

**Comment by wxiaoguang** [comment]
Your log `custom:admin/dashboard:5` shows that you are using "custom templates". If you don't need the custom templates, you could simply remove them.

**Comment by Pawel-Bedn4rczyk** [comment]
Ok thx for help  @wxiaoguang . I resolved it by copied all new templates from repo and put some changes from my old templates now it works again ;)
