### ISSUE TITLE
Use ghcr.io because of Docker Hub is blocked

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#31208]
### Feature Description

Docker Hub blocked access to people on the US sanctions list. I see that you are using the Google(gcr.io) repository, but there is no Github(ghcr.io) repository. Could you add it as well?
You could also change the links to the images in the documentation
It's also hitting the issue https://github.com/go-gitea/gitea/issues/22922

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/170831530/3b7bcfe6-f3e8-4ad7-97ca-aa634fe6288f)

**Comment by lunny** [comment]
ghcr.io's free plan only include 500MB storages which is too less to store all the Gitea docker images.

**Comment by zc-devs** [comment]
Quay and Public ECR might be the options as well. You can use [skopeo](https://github.com/containers/skopeo) to copy images between registries.

**Comment by techknowlogick** [comment]
As a somewhat related note: I am funding work on packages to be able to have per-user quotas, which means once implemented we could have Gitea.com be our primary image location.

**Comment by techknowlogick** [comment]
@qwe1231adsd is dl.gitea.com being blocked for you? You should be able to get binaries from there at least

**Comment by qwe1231adsd** [comment]
> @qwe1231adsd is dl.gitea.com being blocked for you? You should be able to get binaries from there at least

The binaries on your site are available, but I'm using Docker. I would like to get ready images as before via Docker Hub, but build the image each time - this..... I haven't fully mastered Docker yet, sorry about that
