### ISSUE TITLE
Login/Register pages show a JavaScript error

### ISSUE THREAD

**Issue by makeforfun** [go-gitea/gitea#31206]
### Description

https://gitea.com/user/login
https://gitea.com/user/sign_up
https://gitea.com/user/settings/account
https://gitea.com/issues
https://gitea.com/notifications
https://gitea.com/milestones
https://gitea.com/pulls

### Screenshots

![jpg](https://github.com/go-gitea/gitea/assets/171019309/f9e0ee28-a190-4336-8812-ec5aa0d95901)

### Gitea Version

1.23.0

### Can you reproduce the bug on the Gitea demo site?

Yes

### Browser Version

Browser 1.23.0

**Comment by lunny** [comment]
What's your web browser and version? Can you clean the web browser cache?

**Comment by makeforfun** [comment]
https://www.palemoon.org

Console
![jpeg](https://github.com/go-gitea/gitea/assets/171019309/a5fa9f93-ada8-4be3-aae3-08c7224345e9)

Accounts page.
![jpg](https://github.com/go-gitea/gitea/assets/171019309/0c588f23-ab2d-430b-b7d0-a096b7e52bcd)

**Comment by lunny** [comment]
Looks like it's related to htmx. Maybe we need to report upstream. https://github.com/bigskysoftware/htmx

**Comment by silverwind** [comment]
Upstream bug: https://github.com/bigskysoftware/htmx/issues/2581

**Comment by silverwind** [comment]
Fix was merged into PaleMoon and will be included in next release 33.2.0.
