### ISSUE TITLE
Broken comment's author

### ISSUE THREAD

**Issue by stuzer05** [go-gitea/gitea#31213]
### Description

All old comments and every new comment displays as by Ghost account

![image](https://github.com/go-gitea/gitea/assets/23124682/80ef8bbb-e6f2-42bb-8fe9-8a5cc7cd7162)

### Gitea Version

1.23.0+dev-164-ga4275951ba

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

docker dev

### Database

PostgreSQL

**Comment by MaxWipfli** [comment]
I have just bisected this, and the regression happened with #30490. I will take a look at this.
