### ISSUE TITLE
Docker build broken due to dependency dario.cat/mergo missed.  dario.cat domain has expired.

### ISSUE THREAD

**Issue by vsysoev** [go-gitea/gitea#31220]
### Description

Docker build broken due to missed dependency Dario.cat/mergo. Build with cached dependency works fine.

### Gitea Version

1.22

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

2.30.2

### Operating System

Linux Debian, All

### How are you running Gitea?

 docker build --build-arg GITEA_VERSION=v1.22.0 -t dev.sarov.local/integrasdl/gitea:v1.22.0 .

### Database

SQLite

**Comment by KN4CK3R** [comment]
It's used by https://github.com/go-git/go-git/blob/c4390a64249356c285c069c6cc833e81539a55d8/repository.go#L17
Maybe we could use https://github.com/darccio/mergo as workaround.

**Comment by silverwind** [comment]
This shouldn't be an issue when you are using a GOPROXY. Can you check why you aren't using one?

**Comment by silverwind** [comment]
Also check if you can reach the default GOPROXY from your build machine:

- https://proxy.golang.org/
- https://sum.golang.org/
- https://index.golang.org/

**Comment by techknowlogick** [comment]
Thanks for this report. I will close it now as the domain has been renewed, and so using a replace in go.mod is no longer needed.
