### ISSUE TITLE
modules/templates/helper.go:110: undefined: url.PathEscape

### ISSUE THREAD

**Issue by gsantner** [go-gitea/gitea#3123]
- Gitea version (or commit ref): 5b30964e541ef65f25e4247b4a8a854452ae9f51
- Git version: 2.11
- Operating system: Deb
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite

## Description
Tried to start/compile latest version of gitea, but it is not possible because of error below:

```
modules/templates/helper.go:110: undefined: url.PathEscape
```

![gnome-shell-screenshot-8e9zaz](https://user-images.githubusercontent.com/6735650/33789675-9826cd92-dc7a-11e7-9632-377f3427fc38.png)

**Comment by lunny** [comment]
Your Go version?

**Comment by gsantner** [comment]
go version go1.7.1 linux/amd64

**Comment by bkcsoft** [comment]
`url.PathEscape` requires 1.8 according to the tags on https://github.com/golang/go/commit/7e2bf952a905f16a17099970392ea17545cdd193

**Comment by bkcsoft** [comment]
Our docs (wrongly) states 1.7 as the lowest version... but we don't test that 😒 https://docs.gitea.io/en-us/install-from-source/ https://github.com/go-gitea/gitea/blob/master/.drone.yml#L77

**Comment by gsantner** [comment]
This happend already 2 or 3 times now (go version too old) :D.
It's not only for me but for all users: Can you please write down minimum system requirements and keep them updated? Also maybe place this in Issue template.

Another notice, Debian Stable is packaged until 1.7 <https://packages.debian.org/stretch/golang>, so all debian users have to rely on non-packaged golang versions now - who do build gitea from source

**Comment by bkcsoft** [comment]
This was why we moved `docs/` into this repo. So that we can update the requirements _in_ the PR affecting them. #2874 

As for Debian users, either install golang 1.8 from source or use the pre-compiled Gitea binaries 🙁

**Comment by gsantner** [comment]
Thanks!

Boots with `go version go1.9.2 linux/amd64`.

Another comment from Riot: Tag for v1.3.1 is missing, but seems somehow to be released, somehow not?
