### ISSUE TITLE
Markdown image paste regressions

### ISSUE THREAD

**Issue by wxiaoguang** [go-gitea/gitea#31230]
Regression of  Downscale pasted PNG images based on metadata #29123 :

1. The pasted image is not clickable (unable to view the full image)
2. The URL path doesn't contain sub-path if the Gitea instance is deployed under a sub-path.
    * From discord report: Pasting image from the clipboard the Javascript (Paste.js) embeds the image via html code but the src attribute is set to value: `/attachments/<GUID>`. Using a configuration in which the Gitea application is served on a subpath of the domain name, for example: `https://domain.name/git` the image is not rendered.

**Comment by silverwind** [comment]
Both issues indicate there is some backend processing that works on `![]` images, but not on the `<img>` variant, so not strictly a regression from that PR because `<img>` worked before as well.

**Comment by silverwind** [comment]
Can confirm above suspicion, there is [transformImage](https://github.com/go-gitea/gitea/blob/aace3bccc3290446637cac30b121b94b5d03075f/modules/markup/markdown/transform_image.go#L15) which apparently is never applied on user-supplied `<img>` tags.

**Comment by silverwind** [comment]
Yeah so this is no easy fix in backend because `<img>` tags do not go through goldmark AST processing I think, they likely go through as raw html.

**Comment by wxiaoguang** [comment]
Actually it is a regression. No matter how markdown / img work, as an end users:

1. I would like to click an image to show the full size (especially when it is a full-size screenshot)
2. I would like to deploy Gitea under a sub-path and paste images into the editor

I do not care about `<img>` or something else, but now:

1. I can't
2. I can't

----

As a developer, I think there is an undefined / unclear behavior for the embedded `<img>` tag when it has a relative `src` link. But I do not think it's worth to make it more complex than it should be at the moment.

**Comment by wxiaoguang** [comment]
->  Make pasted "img" tag has the same behavior as markdown image #31235

**Comment by silverwind** [comment]
> I would like to click an image to show the full size (especially when it is a full-size screenshot)

At least Firefox has the built-in on all images "Open image in new tab" 😉
