### ISSUE TITLE
Activity pages (besides Pulse) brocken - Server sends negative Unix-time 

### ISSUE THREAD

**Issue by snoweuph** [go-gitea/gitea#31248]
### Description

The Activity Tab are loading a long time, and then are just empty. 
This does not seeme to be the  same problem as: #30851

This happens to all Repos on my Instance:.
Test Repo: https://git.euph.dev/Snoweuph/Dotfiles/activity/contributors

it looks like my server is sending negative unix time:
https://git.euph.dev/Snoweuph/Dotfiles/activity/contributors/data
specificly all unixtimestamps are `-62135596800000`

### Gitea Version

22.0

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://pastebin.com/LU9eVE2W

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/76737863/7282de62-fbdd-4763-92ba-b5637d725845)
![image](https://github.com/go-gitea/gitea/assets/76737863/b325b387-4bde-4d04-b3fa-20113d98e5a7)

### Git Version

2.20.1

### Operating System

Debian 10 - Kernel 4.19.0-26

### How are you running Gitea?

I run gitea as a Systemd Service.

gitea.service
```service
[Unit]
Description=Gitea (Git with a cup of tea)
After=syslog.target
After=network.target

[Service]
RestartSec=2s
Type=simple
User=git
Group=git
WorkingDirectory=/var/lib/gitea/
ExecStart=/usr/local/bin/gitea web --config /etc/gitea/app.ini
Restart=always
Environment=USER=git HOME=/home/git GITEA_WORK_DIR=/var/lib/gitea

[Install]
WantedBy=multi-user.target
```

app.ini
```ini
APP_NAME = Giteuph
RUN_USER = git
RUN_MODE = prod
WORK_PATH = /var/lib/gitea

[oauth2]
JWT_SECRET = ...

[security]
INTERNAL_TOKEN = ...
INSTALL_LOCK = true
SECRET_KEY = ...

[database]
DB_TYPE = mysql
HOST = 127.0.0.1:3306
NAME = gitea
USER = gitea
PASSWD = ...
SCHEMA =
SSL_MODE = disable
CHARSET = utf8
PATH = /var/lib/gitea/data/gitea.db
LOG_SQL = false

[repository]
ROOT = /home/git/gitea-repositories

[attachment]
MAX_SIZE = 1000

[server]
SSH_DOMAIN = git.euph.dev
DOMAIN = git.euph.dev
HTTP_PORT = 3000
ROOT_URL = https://git.euph.dev/
DISABLE_SSH = false
SSH_PORT = 22
LFS_START_SERVER = true
LFS_JWT_SECRET = ...
OFFLINE_MODE = false

[storage.packages]
STORAGE_TYPE = local
PATH = /mnt/gitea-data/packages

[mailer]
ENABLED = true
SMTP_ADDR = box.euph.email:465
FROM = noreply@euph.email
USER = noreply@euph.email
PASSWD = ...

[service]
REGISTER_EMAIL_CONFIRM = true
ENABLE_NOTIFY_MAIL = true
DISABLE_REGISTRATION = true
ALLOW_ONLY_EXTERNAL_REGISTRATION = false
ENABLE_CAPTCHA = true
REQUIRE_SIGNIN_VIEW = false
DEFAULT_KEEP_EMAIL_PRIVATE = false
DEFAULT_ALLOW_CREATE_ORGANIZATION = true
DEFAULT_ENABLE_TIMETRACKING = true
NO_REPLY_ADDRESS = noreply.localhost

[picture]
DISABLE_GRAVATAR = false
ENABLE_FEDERATED_AVATAR = false

[openid]
ENABLE_OPENID_SIGNIN = false
ENABLE_OPENID_SIGNUP = false

[session]
PROVIDER = file

[log]
MODE = file
LEVEL = info
ROOT_PATH = /var/lib/gitea/log
REDIRECT_MACARON_LOG = true
MACARON = console

[ui]
THEMES = gitea-auto,gitea-light,gitea-dark,catppuccin-latte-blue,catppuccin-latte-flamingo,catppuccin-latte-green,catppuccin-latte-lavender,catppuccin-latte-maroon,catppuccin-latte-mauve,catppuccin-latte-peach,catppuccin-latte-pink,cat$
DEFAULT_THEME = gitea-auto

[actions]
ENABLED = true
```

### Database

MySQL/MariaDB

**Comment by snoweuph** [comment]
I did a small test:
```bash
root@euph:~/test# cat main.go 
```
```go
package main

import (
        "fmt"
        "time"
)

func main() {
        now := time.Now()
        fmt.Println("The current time and date is:", now)
}
```
```bash
root@euph:~/test# go run main.go 
The current time and date is: 2024-06-04 15:35:18.373897005 +0000 UTC m=+0.000015481
```

**Comment by snoweuph** [comment]
@kemzeb you said:
> After looking at the [code](https://github.com/go-gitea/gitea/blob/803b0c9ab43f809e47f42fad951e7f5fb6652e42/services/repository/contributors_graph.go#L270-L273) that builds these Unix times, I haven't been able to determine the cause (or if the problem resides elsewhere). If you wish, you can open a new issue so that we can track this potential bug.

so, im just now building a gitea binary myself, based on the v22 tag and im changing it up to return the `strconv.Atoi` of the date, instead of trying to parse it

**Comment by snoweuph** [comment]
well, my compiled binary ( compiled  on the Server) directly crashes (using make build)  so I guess, I will have to try somethign else

**Comment by snoweuph** [comment]
I fixed it, by installing a nwer git version with sha256 support (the newest one) from source.

the git on debian 10 is to old

**Comment by snoweuph** [comment]
On Linode `Debian 10`, the `git` version is `2.20` which is not working with the new version of gitea, solution: install git from source

**Comment by kemzeb** [comment]
Glad that you were able to solve it! Did not expect it to be because of an outdated git

**Comment by snoweuph** [comment]
Yea, same
