### ISSUE TITLE
Allow team names of length 36 to accommodate UUIDs 

### ISSUE THREAD

**Issue by tobiasbp** [go-gitea/gitea#31241]
### Feature Description

When integrating _Gitea_ with other systems, I have the need to create organization teams the correspond to an external resource. As there is no way to tag a team, I would like to name the with a _UUID_ that matches the _UUID_ of my external resource. Users will never see the team names, so there are no UI issues with users wondering about the _UUID_ names for teams.

Currently, the maximum length of a team name is _30_ characters. I would like to have that changed to _36_, which is the length of a _UUID_ (32 hex characters and 4 hyphens).

I'm happy to make a PR with the change, if someone could point to the current definition in the code. I am unable to find it.   

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/5671083/805c74e3-98d7-4cd6-80c2-4e3b31ec4950)

**Comment by KN4CK3R** [comment]
We could/should increase the length even more.

**Comment by silverwind** [comment]
What is the maximum team length name on GitHub/GitLab?

**Comment by KN4CK3R** [comment]
Looks like they don't have a limit. These are 200 a:
![grafik](https://github.com/go-gitea/gitea/assets/1666336/b323d0bd-eb00-498f-81ba-5c09de9df3a5)

**Comment by philippbeckmann** [comment]
This collection implies the max length on GitHub ist 255: https://github.com/dead-claudia/github-limits

**Comment by delvh** [comment]
I'm fine with anything below 255, so if there's a PR to change it, I'll approve it.

**Comment by silverwind** [comment]
> I'm fine with anything below 255, so if there's a PR to change it, I'll approve it.

you likely meant "at or below" 😛

**Comment by tobiasbp** [comment]
Where in the code should the change be made?

**Comment by delvh** [comment]
```go
modules/structs/org_team.go
27:     Name                    string `json:"name" binding:"Required;AlphaDashDot;MaxSize(30)"`
43:     Name                    string  `json:"name" binding:"AlphaDashDot;MaxSize(30)"`
```
I just had a look at the data model (`/models/organization/team.go#79`), and it looks like that already supports chars up to length 255.
So no need to change anything else

**Comment by silverwind** [comment]
I assume xorm would auto-migrate the column to the new size, right? If yes, then it is a 1-2 line change ideally acompanied by a small test that creates a team at the new maximum length.

**Comment by techknowlogick** [comment]
@silverwind we require a migration for struct changes that would affect the DB, because even though automigrations will happen, we've run into cases in the past with too large of a version jump in the migration, then some auto-assumed migrations would be skipped (I haven't looked at this specific case though if it'd need the migration/struct change, but from above it seems it is just the validation that needs to be updated).

**Comment by delvh** [comment]
> I assume xorm would auto-migrate the column to the new size, right

As I said, not needed, it's already `varchar 255`

**Comment by tobiasbp** [comment]
So, is the only thing needed then to change these values to 255?
````
modules/structs/org_team.go
27:     Name                    string `json:"name" binding:"Required;AlphaDashDot;MaxSize(30)"`
43:     Name                    string  `json:"name" binding:"AlphaDashDot;MaxSize(30)"`
````

**Comment by techknowlogick** [comment]
@tobiasbp yes, although I'd suggest making the change locally, compiling, and testing to see if the names can then handle the additional length (in case we are missing another validation area).
I would recommend against bumping the length all the way up to 255 as some filesystems don't like really long paths.

**Comment by delvh** [comment]
So, let's say 63?

**Comment by silverwind** [comment]
> @tobiasbp yes, although I'd suggest making the change locally, compiling, and testing to see if the names can then handle the additional length (in case we are missing another validation area). I would recommend against bumping the length all the way up to 255 as some filesystems don't like really long paths.

255 is fine for all common file systems: https://github.com/sindresorhus/valid-filename/blob/main/index.js

**Comment by techknowlogick** [comment]
@silverwind  the folder length is not enough to look at, some FS (in mobile so I can't link) look at the full path as well. I want to say it's exFAT, but it might be another (common one).
I ran into it on my synology, and iirc that's using some btrfs derivative (caveat, I was using an encrypted drive which added additional constraints)

**Comment by silverwind** [comment]
> > @tobiasbp yes, although I'd suggest making the change locally, compiling, and testing to see if the names can then handle the additional length (in case we are missing another validation area). I would recommend against bumping the length all the way up to 255 as some filesystems don't like really long paths.
> 
> 255 is fine for all common file systems: https://github.com/sindresorhus/valid-filename/blob/main/index.js

Thought Windows does have a [restriction called MAX_PATH](https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry) that limits the full path length to 260 chars. I don't think team names can end up as filenames but for stuff that can, I think 64 is a good limit.

**Comment by tobiasbp** [comment]
So... What do we want?
* 63
* 127
* 255

**Comment by KN4CK3R** [comment]
Maoam and 255.

**Comment by silverwind** [comment]
Team name is not represent in file system so could go to 255, but if it ever will be, 63 seems like the safe option and I don't see a use case for team names longer than that, so I'd go with safe option 63.

**Comment by techknowlogick** [comment]
Ah, sorry, yes, my bad. I was thinking org name, even though you all have been saying team name this entire time. Please ignore my previous concerns. 255 is definitely a good choice for team name.

**Comment by silverwind** [comment]
Repo and org name limitations need to be investigated separately, I posted some regexes in https://github.com/go-gitea/gitea/issues/4150#issuecomment-2142204117, but there is also a length limit.

**Comment by techknowlogick** [comment]
closing due to merged PR
