### ISSUE TITLE
actions/upload-artifact@v4 is not available

### ISSUE THREAD

**Issue by xuegao-tzx** [go-gitea/gitea#31256]
### Description

This is the yml configuration：
```
- name: Upload build reports
        uses: actions/upload-artifact@v4
        with:
          name: assembleRelease
          compression-level: 9
          path: build/app/outputs/flutter-apk/app-release.apk
```
the error is:
```
With the provided path, there will be 1 file uploaded
::warning::Artifact upload failed with error: GHESNotSupportedError: @actions/artifact v2.0.0+, upload-artifact@v4+ and download-artifact@v4+ are not currently supported on GHES..%0A%0AErrors can be temporary, so please try again and optionally run the action with debug mode enabled for more information.%0A%0AIf the error persists, please check whether Actions is operating normally at [https://githubstatus.com](https://www.githubstatus.com).
::error::@actions/artifact v2.0.0+, upload-artifact@v4+ and download-artifact@v4+ are not currently supported on GHES.
```

### Gitea Version

1.22.0

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

<img width="1701" alt="image" src="https://github.com/go-gitea/gitea/assets/86029709/de48f1e1-3259-4353-89f1-6e836b582bb8">

### Git Version

git version 2.39.3 (Apple Git-146)

### Operating System

MacOS 14 arm64

### How are you running Gitea?

[Installation from binary](https://docs.gitea.com/installation/install-from-binary)

### Database

SQLite

**Comment by yp05327** [comment]
see #28853

**Comment by yp05327** [comment]
Yes, but
> christopherhx/gitea-upload-artifact@v4 and christopherhx/gitea-download-artifact@v4 are removing the GHES error message until GitHub removes the not supported fatal error themself.
>
> I don't like how GitHub blocks GHES using hardcoded asserts, until they support them officially

(https://github.com/go-gitea/gitea/issues/28853#issuecomment-1905013276)

> Needs both https://gitea.com/gitea/act_runner/pulls/473 and https://gitea.com/gitea/act_runner/pulls/471 on the runner side and patched actions/upload-artifact@v4 / actions/download-artifact@v4, like christopherhx/gitea-upload-artifact@v4 and christopherhx/gitea-download-artifact@v4, to not return errors due to GHES not beeing supported yet.

(#28965)

**Comment by lunny** [comment]
I have sent https://gitea.com/gitea/blog/pulls/378 as a workaround.
