### ISSUE TITLE
[Bug] Activity Page Contributors -  type dropdown breaks non-English locale

### ISSUE THREAD

**Issue by snoweuph** [go-gitea/gitea#31261]
### Description

When changing the Display Language to German in the Gitea Footer and trying to change the type in the contributors tab, from commits to any of the other ones, they don't get select and just end up empty.

### Gitea Version

1.22.0

### Can you reproduce the bug on the Gitea demo site?

Yes: https://gitea.com/Dominik_Saeume/nhplus/activity/contributors

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/76737863/cfcd6df5-ba04-4d0a-a6a4-ba617dcc6b5a)

### How are you running Gitea?

https://demo.gitea.com/

**Comment by wxiaoguang** [comment]
Actually, it breaks in all languages other than English. It is a code-level bug.

**Comment by wxiaoguang** [comment]
->  Fix Activity Page Contributors dropdown #31264
