### ISSUE TITLE
Wiki page not rendered

### ISSUE THREAD

**Issue by sandman7920** [go-gitea/gitea#31274]
### Description

When the wiki page contains a `+` sign in the title, the friendly link is not working.
A non-friendly link works ok (carrot right link)

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/3589417/d3a9d5b8-8cdf-4572-a3a1-9d4534ba8303)

### Gitea Version

1.22.0

### Can you reproduce the bug on the Gitea demo site?

<strike>Yes</strike> No

### Browser Version

Firefox 126.0.1

**Comment by lunny** [comment]
What's your demo repository link?

**Comment by sandman7920** [comment]
Sorry, the issue is not reproducible on the demo site.
The issue was fixed with `nocanon` proxy pass parameter on the `Apache Side`
