### ISSUE TITLE
"Clean up expired data" not working when hosting under a subpath

### ISSUE THREAD

**Issue by d-danilov** [go-gitea/gitea#31285]
### Description

When hosting under a subpath behind a reverse proxy (say, `http://myserver.local/gitea` as ROOT_URL), button "Clean up expired artifacts" in Site Administration->Code Assets->Packages (`/admin/packages`) does not work, resulting in a 404 instead. 

The button POSTs to `/admin/packages/cleanup`, while expected to POST to `/gitea/admin/packages/cleanup`, where `/gitea` prefix is the subpath Gitea is being hosted on. If I manually add the subpath prefix to HTML via browser inspector, the button works, like this: `<form method="post" action="/gitea/admin/packages/cleanup">`

This seems to be due to missing usage of `AppSubUrl` [here](https://github.com/go-gitea/gitea/blob/ab1948d4a30aee919ba1ffc2402a2a9a7222e68c/templates/admin/packages/list.tmpl#L8), like its used in [other](https://github.com/go-gitea/gitea/blob/ab1948d4a30aee919ba1ffc2402a2a9a7222e68c/templates/admin/repo/unadopted.tmpl#L34) [places](https://github.com/go-gitea/gitea/blob/ab1948d4a30aee919ba1ffc2402a2a9a7222e68c/templates/org/home.tmpl#L20).

### Gitea Version

1.12.10

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

Systemd

### Database

None

**Comment by wxiaoguang** [comment]
Fix some URLs whose sub-path is missing #31289
