### ISSUE TITLE
Fail to create '/.ssh'

### ISSUE THREAD

**Issue by rain0r** [go-gitea/gitea#313]
- Gitea version (or commit ref): Git Service 0.9.99.0915
- Git version: 2.9.0
- Operating system: OpenBSD
- Database (use `[x]`):
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Log gist:https://gist.github.com/rain0r/6c83dece2fbeebfb88bb14d9c8514113

## Description

I get this error message when starting gitea via supervisord. Starting as the gitea user ("git") works fine and without any problems. 
This is the supervisord entry for gitea:

    [program:gogs]
    directory=/home/git/
    command=/home/git/start-gitea.sh
    autostart=true
    autorestart=true
    startsecs=10
    stdout_logfile=/var/log/gogs/stdout.log
    stderr_logfile=/var/log/gogs/stderr.log
    user = git
    environment = PATH="/usr/local/bin/:%(ENV_PATH)s"
    environment = HOME="/home/git/", USER="git"
    stopasgroup=true

**Comment by tboerger** [comment]
Sorry but I'm not familiar with supervisord. But I would like to know why don't you use the system init service? =)

**Comment by rain0r** [comment]
Good question, acutally! ;-)

I moved from Linux to OpenBSD and it was convenient to just copy the supervisord config.

However: it works with rc init.

**Comment by tboerger** [comment]
Ok, so let's close that for now since the regular init system works.

**Comment by strk** [comment]
If Gitea source tree does include a `supervisord` script that does not work this ticket should remain open.
