### ISSUE TITLE
no icons work

### ISSUE THREAD

**Issue by blade10101** [go-gitea/gitea#31312]
### Description

I was having issues with gitea, where the icon's to go to settings or to create a repo's won't respond. So I erased the whole thing and recreated it, but after logging in as admin, it does the same thing.

### Gitea Version

1.22.0

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

git version 2.34.1

### Operating System

Ubuntu 22.04

### How are you running Gitea?

docker-compose.yml file

### Database

None

**Comment by wxiaoguang** [comment]
What browser are you using? 

I couldn't really understand what icons you meant, could you show some screenshots?

> Can you reproduce the bug on the Gitea demo site?
> No

If it can't be reproduced on gitea demo site .... it doesn't look like a common bug .....

**Comment by blade10101** [comment]
I have found out its a chrome issue.... I used the tor browser and I was able to login

Jun 11, 2024 12:31:32 AM wxiaoguang ***@***.***>:
