### ISSUE TITLE
"New pull request" button shown when viewing tag/commit

### ISSUE THREAD

**Issue by ethantkoenig** [go-gitea/gitea#3132]
- Gitea version (or commit ref): master
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (https://try.gitea.io/ethantkoenig/sandbox/src/commit/ccd21f083756c783bc4725512edb9992183ff941, click on the "New pull request" button for the 404)
  - [ ] No
  - [ ] Not relevant

## Description

When viewing a tag or commit, the "new pull request" button is shown. If you click on the link, you will get a 404, since the head of a PR must be a branch.

I think that ideally the button should not be shown when viewing a tag/commit.

**Comment by Albert221** [comment]
I'd like to work on that.

**Comment by lafriks** [comment]
@Albert221 I think there is already PR to fix this

**Comment by Albert221** [comment]
@lafriks could you confirm? I don't see any opened PRs addressing that

**Comment by lafriks** [comment]
@ethantkoenig wrote that in #3133 description that it fixes this issue but in code somehow I don't see this

>

**Comment by ethantkoenig** [comment]
Oh, I forgot to push my latest changes to #3133. Yes, #3133 will fix this issue

**Comment by lafriks** [comment]
Fixed by #3133
