### ISSUE TITLE
Can't open details page of a npm package with namespace

### ISSUE THREAD

**Issue by trading-peter** [go-gitea/gitea#31321]
### Description

I have npm packages that I push into gitea's package system.
If these packages are part of a namespace the link to the detail page for the packages breaks.

![image](https://github.com/go-gitea/gitea/assets/11567985/ed7cc445-86ac-465c-becc-8963d0b7c817)

The `@tp/` namespace cause the detail link to be `.../tp-elements/-/packages/npm/@tp%2Ftp-avatar/1.0.0` which returns a 404

![image](https://github.com/go-gitea/gitea/assets/11567985/df904d3c-a2da-44c0-83a2-53dbfecad59f)

### Gitea Version

1.22.0

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

Self-hosted with docker

### Database

PostgreSQL

**Comment by wxiaoguang** [comment]
It seems that your reverse proxy doesn't satisfy: https://docs.gitea.com/administration/reverse-proxies#general-configuration

```
Make sure the reverse-proxy does not decode the URI. The request https://git.example.com/a%2Fb should be passed as http://gitea:3000/a%2Fb.
```

**Comment by trading-peter** [comment]
Oh wow,

I had a trailing slash after the port. Removed it and now it works.

So `proxy_pass http://localhost:3000;` instead of `proxy_pass http://localhost:3000/;`

Thanks a lot!
