### ISSUE TITLE
Add .profile README overview tab to organization pages

### ISSUE THREAD

**Issue by axeldvera** [go-gitea/gitea#31326]
### Feature Description

Previously, user hazycora made a pull request with a feature that was discarded (apparently by mistake, as it was confused with another similar pull request).

in the PR the user "added the overview tab everywhere the organization tabs are visible (of course, only when the .profile repo and a README file exist, matching the behavior for user profile pages)"

The closed PR link is the following:

https://github.com/go-gitea/gitea/pull/27125

We would like to be able to obtain this functionality since, if we add a readme that is too long in the "repositories" section, they remain far below the page, making it difficult to view them.

Can this lost PR be recovered? thank you so much!

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/56047727/506510dc-b19f-4208-be6e-bb75ec662e90)

**Comment by a1012112796** [comment]
Hmm, How  about limit max height of `profile README` on ui?

**Comment by axeldvera** [comment]
> Hmm, How about limit max height of `profile README` on ui?

We don't want that restriction. We have been using github for a long time and are used to that functionality. We would like to have the same "Overview" tab as is already being used in the personal profile.

**Comment by kemzeb** [comment]
Looks like #31373 introduced an overview tab to house the profile README, so this issue should be resolved.
