### ISSUE TITLE
Cannot select milestone in issues

### ISSUE THREAD

**Issue by stuzer05** [go-gitea/gitea#31336]
### Description

![image](https://github.com/go-gitea/gitea/assets/23124682/0d32b88e-919d-42da-99d6-23b4f1ced31a)

when selecting milestone on new issue

### Gitea Version

1.23.0+dev-211-gfc2d75f86d

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

docker

### Database

PostgreSQL

**Comment by lunny** [comment]
What's the repository link on the demo site?

**Comment by stuzer05** [comment]
> What's the repository link on the demo site?

Sorry, cannot reproduce on demo

**Comment by kemzeb** [comment]
From analyzing the commit history and manually testing, this appears to be a regression from #30506, specifically  the change made in [this ](https://github.com/go-gitea/gitea/blob/78e8296e113e2fd9259ec05fe87035427821ea0b/web_src/js/features/repo-legacy.js#L275) line.

**Comment by wxiaoguang** [comment]
->  Fix JS error when creating new issue #31383
