### ISSUE TITLE
Large Actions artifacts (> ~8MB) will fail checksum when merging their chunks

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#31354]
ref: https://forum.gitea.com/t/large-actions-artifacts-8mb-will-fail-checksum-when-merging-their-chunks/9291

I'm using a self-hosted Gitea 1.22.0, with the patched version of `upload-artifact@v4` (https://github.com/ChristopherHX/gitea-upload-artifact@v4), and am trying to upload a ~1.8GB artifact.

From the Actions step:
```
Uploaded bytes 1851809172
Finished uploading artifact content to blob storage!
SHA256 hash of uploaded artifact zip is 5445b7ac4b993cbc01f349b0ec90b8ebceee564cff62ce9a529fdb9ce1326886
Finalizing artifact upload
::error::Failed to FinalizeArtifact: Unexpected token 'E', "Error merge chunks%0A" is not valid JSON
```
When looking at the Gitea server logs, this matches up to this error message:

`...artifactsv4.go:363:finalizeArtifact() [E] Error merge chunks: update artifact error checksum is invalid`

I did some tests, and it looks like any artifacts that are bigger than roughly 8MB will fail to be merged when finalizing the upload.

**Comment by VAllens** [comment]
I also encountered the same problem.
Has there been any progress?
