### ISSUE TITLE
Promise rejection when filtering branch in commit graph

### ISSUE THREAD

**Issue by amrsoll** [go-gitea/gitea#31376]
### Description

[self-hosted private Gitea 1.22]

In the commit graph, I start filtering for the master branch.

![image](https://github.com/go-gitea/gitea/assets/24782867/f5031ae0-a1c8-4ace-b22c-316eaf9a62e9)

I sometimes get the following error, although a page refresh fixes it.

> JavaScript promise rejection: un.getElementById is not a function. Open browser console to see more details.

![image](https://github.com/go-gitea/gitea/assets/24782867/8c5acbb0-5300-4aff-9ee7-e2c412ba1bbb)

In the console I get

```
Uncaught (in promise) TypeError: un.getElementById is not a function
    si repo-graph.js:72
```

![image](https://github.com/go-gitea/gitea/assets/24782867/d10eae4a-5cb5-4598-9846-f55473c2a444)

When looking up the JS, this is the part it refers to

```js
  const updateGraph = () => {
    const queryString = params.toString();
    const ajaxUrl = new URL(url);
    ajaxUrl.searchParams.set('div-only', 'true');
    window.history.replaceState({}, '', queryString ? `?${queryString}` : window.location.pathname);
    document.getElementById('pagination').innerHTML = '';
    hideElem('#rel-container');
    hideElem('#rev-container');
    showElem('#loading-indicator');
    (async () => {
      const response = await GET(String(ajaxUrl));
      const html = await response.text();
      const div = document.createElement('div');
      div.innerHTML = html;
*FAIL* document.getElementById('pagination').innerHTML = div.getElementById('pagination').innerHTML;
      document.getElementById('rel-container').innerHTML = div.getElementById('rel-container').innerHTML;
      document.getElementById('rev-container').innerHTML = div.getElementById('rev-container').innerHTML;
      hideElem('#loading-indicator');
      showElem('#rel-container');
      showElem('#rev-container');
    })();
  };
```

### Gitea Version

1.22.0

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

Debian

### How are you running Gitea?

Self hosted, running on the host debian system (a VM, not a container), using the pre-built binaries from official release

### Database

MySQL/MariaDB

**Comment by wxiaoguang** [comment]
Could you try 1.22-nightly? I guess it should have been fixed there.

**Comment by wxiaoguang** [comment]
Oops, it's only fixed in main(1.23) nightly, not in 1.22-nightly ....

**Comment by wxiaoguang** [comment]
->  Fix repo graph JS #31377

**Comment by wxiaoguang** [comment]
1.22-nightly with the fix is ready, could you take a try?

**Comment by amrsoll** [comment]
If you mean to ask me to test out on our system config, I am unfortunately unable because our production VM is a snowflake that I cannot easily replicate 😅 I imagine it works if you already had it fixed in an upcoming version

**Comment by techknowlogick** [comment]
@homjay, are you getting this on the commit graph page too, or a different page?

**Comment by lunny** [comment]
> > @homjay, are you getting this on the commit graph page too, or a different page?
> 
> 
> 
> Thanks for replying. I get this on every page.
> 
> But now I have identified this was caused by the Zotero plugin in the Safari browser.

So I think that's a different problem. I'm going to close this one.
