### ISSUE TITLE
Can't show .gitignore file

### ISSUE THREAD

**Issue by ChristmasZCY** [go-gitea/gitea#31370]
### Description

[gitea.log](https://github.com/user-attachments/files/15834720/gitea.log)

### Gitea Version

Gitea version 1.22.0 built with GNU Make 4.3, go1.22.3 : bindata, sqlite, sqlite_unlock_notify

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/61818189/85c92481-8b54-40ff-b79c-58fb2678d882)
![image](https://github.com/go-gitea/gitea/assets/61818189/08632b09-9521-4983-a92c-68e2e79ce7d9)

### Git Version

git version 2.39.3

### Operating System

RockyLinux 9

### How are you running Gitea?

Runing command-line from https://dl.gitea.io/gitea/1.22.0/gitea-1.22.0-linux-amd64
Running with `./gitea web --port 12345`

### Database

SQLite

**Comment by lunny** [comment]
Can you reproduce it on https://demo.gitea.com?

**Comment by ChristmasZCY** [comment]
> 你能[在 https://demo.gitea.com](https://demo.gitea.com) 上重现它吗？

I'm sorry I can't, It's OK at `https://demo.gitea.com/`, but it doesn't work at my server

**Comment by lunny** [comment]
Maye it's related to your reverse proxy?

**Comment by hmyu-ocean** [comment]
There is no proxy, but there's pthsics firewall.
All website besides other app, other file at local gitea are OK. Only .gitignore file is wrong, at any repository

> Maye it's related to your reverse proxy?

**Comment by wxiaoguang** [comment]
It's 99% related to your firewall.

I guess other files like `.env` are also forbidden in your environment by the firewall.

**Comment by ChristmasZCY** [comment]
> It's 99% related to your firewall.
> 
> 
> 
> I guess other files like `.env` are also forbidden in your environment by the firewall.

All right， I'm contacting with Suppliers.

**Comment by wxiaoguang** [comment]
I will close this issue as completed. If there are still problems related to Gitea itself, feel free to reopen or open a new issue.

Thank you.
