### ISSUE TITLE
Update password forced after OIDC auth following container restart

### ISSUE THREAD

**Issue by rdmcguire** [go-gitea/gitea#31403]
### Description

Following upgrade to 1.22.0, I am confronted with the "Update Password" form following authentication from provisioned OIDC provider. If I do set the password (not sure what this is for since I'm authenticating via OIDC) I can sign in and subsequently sign out / back in without being prompted by the form. The issue comes back if the Gitea pod restarts.

Gitea is installed via helm, chart version gitea-10.2.0. This did not happen prior to the upgrade to 1.22.0.

### Gitea Version

1.22.0

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

linux/kubernetes

### How are you running Gitea?

Gitea is deployed to kubernetes via helm. OIDC provider is keycloak.

### Database

PostgreSQL

**Comment by wxiaoguang** [comment]
It seems something wrong but I couldn't really understand the full context.

Could you elaborate the details? If you could provide a reproducible setup with detailed steps (sample: https://github.com/go-gitea/gitea/issues/30680#issuecomment-2076299869) , then it would be easier to figure out what's wrong.

**Comment by ma-die** [comment]
I had the same problem with the helm-chart admin account and it seems related to https://github.com/go-gitea/gitea/pull/27626. 
A bug fix for the helm-chart is discussed in https://gitea.com/gitea/helm-chart/issues/673 and released with chart version 10.3.0.
