### ISSUE TITLE
Incorrect attachment path in the activity markdown when sub-path is used

### ISSUE THREAD

**Issue by wxiaoguang** [go-gitea/gitea#31411]
`https://domain.name/<subpath>/attachments/guid`

![image](https://github.com/go-gitea/gitea/assets/2114189/e9b3072c-9b5a-4ac8-b335-aa58c4147482)

**Comment by tmnvanderberg** [comment]
If nobody objects I'll have a look :)

**Comment by wxiaoguang** [comment]
It will be fixed by  Refactor markup render system #32612 

![image](https://github.com/user-attachments/assets/1b7842b1-3378-453a-a300-08270c7ce692)
