### ISSUE TITLE
Discourse not working, https://discourse.gitea.io/ . Question : Is gitea using go-git?

### ISSUE THREAD

**Issue by sprappcom** [go-gitea/gitea#31414]
### Description

1. pls open a discussion tab so we can all discuss instead of using discourse.
2. is gitea using go-git?
https://github.com/go-git/go-git
on go-git website it says gitea is using it.

### Gitea Version

1

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

internal repo

### Database

None

**Comment by techknowlogick** [comment]
Hi, the forum was moved to although the old link should(tm) redirect, let me look into why it isn't. And yes, we are using go-git. There is a build flag that you can pass when compiling Gitea that will use go-git for some operations (our CLI tool `tea`, also uses it). It is especially helpful for Windows, as Windows has some oddities that go-git doesn't run into.
