### ISSUE TITLE
Label Dropdown does not display correctly

### ISSUE THREAD

**Issue by jswolf19** [go-gitea/gitea#31415]
### Description

The label dropdown on the issues page and pull requests page does not have a maximum height and overflows to the right in version 1.22.0. There was not a problem in 1.21.11.

As I don't have a login for demo.gitea.com, I cannnot check reproduction there. The problem does not seem to occur on the new issue page.

new issue
![image](https://github.com/go-gitea/gitea/assets/519875/177f012a-c2e9-423a-82a9-9f1ffc628e24)

existing issue
![image](https://github.com/go-gitea/gitea/assets/519875/cc188da4-97c1-49f9-8db9-a047ba6b9c46)

new pull request
![image](https://github.com/go-gitea/gitea/assets/519875/bca3ad1e-b9d1-4cd8-9ab1-c3a0a6f70837)

existing pull request
![image](https://github.com/go-gitea/gitea/assets/519875/daa423e7-efec-4a72-a548-3b2ded81dee4)

### Gitea Version

1.22.0

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

2.45.2

### Operating System

linux 

### How are you running Gitea?

I've installed opensuse package 1.22.0-lp155.1.2 into an opensuse container running on opensuse.

### Database

MySQL/MariaDB

**Comment by brechtvl** [comment]
I can confirm the issue on projects.blender.org and demo.gitea.com.

![gitea_dem_overflow](https://github.com/go-gitea/gitea/assets/450909/2a7d785a-a1b7-4dbc-84c3-2d50af645437)
