### ISSUE TITLE
The link to bypass .git-blame-ignore-revs in the blame view links to the wrong file

### ISSUE THREAD

**Issue by noodlebox** [go-gitea/gitea#31429]
### Description

When revisions are hidden from the blame view, the URL for the link to bypass this feature appends `?bypass-blame-ignore=true` to the path of `.git-blame-ignore-revs` (`$revsFileLink` again) instead of to that of the current file.

https://github.com/go-gitea/gitea/blob/1c1545268743d7d4536a5ff2a137af7c255f45c8/templates/repo/blame.tmpl#L5
https://github.com/go-gitea/gitea/blob/7b8e418da1e082786b844562a05864ec1177ce97/options/locale/locale_en-US.ini#L1087

On the demo site: https://demo.gitea.com/noodlebox/test/blame/branch/main/README.md

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/308464/b8ed2f1c-6a1c-4b01-82f7-bac7affaf879)

### Gitea Version

N/A

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

N/A

### Browser Version

Any

**Comment by wxiaoguang** [comment]
I have an idea to fix it in 1.23 but it needs some new framework-level mechanism to handle URLs. 🤔

**Comment by wxiaoguang** [comment]
Oops, it is a longstanding bug (maybe nobody ever used that link before), we can have a quick fix for it:

->  Fix the link for .git-blame-ignore-revs bypass #31432
