### ISSUE TITLE
JS error all across gitea

### ISSUE THREAD

**Issue by stuzer05** [go-gitea/gitea#31460]
### Description

![image](https://github.com/go-gitea/gitea/assets/23124682/46320372-4647-4c4e-80cf-ab5f4dd922a4)

### Gitea Version

1.23.0+dev-265-g49b8716c40

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

docker

### Database

PostgreSQL

**Comment by wxiaoguang** [comment]
It has been fixed in the latest main, by #31444
