### ISSUE TITLE
LaTex in markdown doesn't shown in somecase

### ISSUE THREAD

**Issue by tsctsc6** [go-gitea/gitea#31465]
### Description

We can input LaTex in markdown by using dollar symbol, but if I type some text before LaTex, the LaTex don't work in gitea web page.For more info, see Screenshots.

### Gitea Version

1.22.0

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/93368014/c31edab1-dd6d-40c2-9454-3e38f1c31dcf)
![image](https://github.com/go-gitea/gitea/assets/93368014/33714d04-bfc1-48fc-ac69-aa5175ad602f)
And in other markdown editor, Latex work well.
![image](https://github.com/go-gitea/gitea/assets/93368014/268665e4-1a8b-4633-9286-85d73a9b0cd1)

### Git Version

git version 2.45.2.windows.1

### Operating System

window10

### How are you running Gitea?

Installation from binary

### Database

SQLite

**Comment by wxiaoguang** [comment]
Does it work if you add a space after the comma `,` ?

**Comment by wxiaoguang** [comment]
```
$a \to b$

Hi,$a \to b$
```


$a \to b$

Hi,$a \to b$

GitHub also requires that there should be a space after comma, and I think the requirement is right, because a correct sentence always contains that space.

**Comment by tsctsc6** [comment]
I see, thank you.

**Comment by wxiaoguang** [comment]
Thank you for your report.

The problem in markdown world is that there is no standard in many cases. If there would be some syntax standards for "latex in markdown", then we could strictly follow them.
