### ISSUE TITLE
Binary Files (.xlsx, .docx) are not shown in the code search results.

### ISSUE THREAD

**Issue by sharpSteff** [go-gitea/gitea#31469]
### Description

When enabling repository indexer for zip-archive based files like .xlsx oder .docx, I would expect gitea to show these files in the code search as paths (without any preview).

Probably more a feature request than a bug.

### Gitea Version

1.22.0

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

docker

### Database

MySQL/MariaDB

**Comment by KN4CK3R** [comment]
You expect to find text inside binary files?

**Comment by sharpSteff** [comment]
no, I just like have the files listed in the search results, without any preview

**Comment by yp05327** [comment]
@KN4CK3R means:
Listing them in the search results means we need to find text inside these binary files.
Are you expect to do this?

**Comment by sharpSteff** [comment]
@yp05327 no, I just want to list the binary files in the search results (without preview) if the filename matches the search-query

**Comment by yp05327** [comment]
we already have file name search.
![IMG_4053](https://github.com/go-gitea/gitea/assets/18380374/5bbce5de-8550-4d61-8ab6-a19025020f5f)
it will go to:
https://gitea.com/gitea/docs/find/branch/main

**Comment by sharpSteff** [comment]
@yp05327 wow great, thats basically the functionality I'm looking for. Is it possible to enable this file search also organistation-wide?

**Comment by lunny** [comment]
> @yp05327 wow great, thats basically the functionality I'm looking for. Is it possible to enable this file search also organistation-wide?

Please open another issue for the proposal and I will close this one since it's not planned to index binary files.
