### ISSUE TITLE
Support for multiply External tracker issues in commits

### ISSUE THREAD

**Issue by makar112233** [go-gitea/gitea#31483]
### Feature Description

Hi.
We are using JIRA as an External Issue tracker for Gitea.
We noticed, that if you specify multiple Jira issues in the commit message, only the last will be converted to a link.
I think it is not a bug. 
Could you, please, support this feature it the future?

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/122980447/cd21d0c0-f313-4436-91c5-6fc45c27a341)

**Comment by lunny** [comment]
Did you mean it's a bug or not? Maybe it should be a bug?

**Comment by makar112233** [comment]
@lunny  it is not a bug.
I think, that this issue could be closed, because we found a solution: use regular expressions 
`(([A-Z0-9]+)-([0-9]+))`

**Comment by makar112233** [comment]
See the solution above.
