### ISSUE TITLE
Unable to delete all unactivated accounts

### ISSUE THREAD

**Issue by ggodlewski** [go-gitea/gitea#31480]
### Description

I'm trying to get rid of spam users (over 800 of them)
I changed them to inactive following instructions from https://blog.roberthallam.org/2022/11/mass-delete-remove-purge-users-in-gitea/
Because I'm using sqlite3 it was: `UPDATE user SET is_active = 'f' WHERE email != 'my@email';`
In the UI all the users except mine are marked inactive.

Then I run `Delete all unactivated accounts`
It says `Started Task: Delete all unactivated accounts` using greenish text.

Nothing happens. I still have over 800 accounts.

### Gitea Version

1.22.0

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/ggodlewski/c17fb25618c3fac0539ae6891da66b6f

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/818238/66886cc8-d986-44bc-a4fb-f387af9989f4)
![image](https://github.com/go-gitea/gitea/assets/818238/f6690bcf-89b8-4fb6-bd34-f8b12658684c)

### Git Version

2.45.1

### Operating System

docker @ ubuntu

### How are you running Gitea?

docker container: gitea/gitea:latest

### Database

SQLite

**Comment by kemzeb** [comment]
Are these accounts new?

If this is the case, what I believe is happening currently is that when you run this task, we would only delete accounts that are older than some certain amount of time. Looking at this particular task in the [code](https://github.com/go-gitea/gitea/blob/053e5829a388ce32dce4ff0ab97158b7b2a2fcc4/services/cron/tasks_extended.go#L30), we would only delete inactive users who are 3 hours old by default (this would be different if you explicity set [ACTIVE_CODE_LIVE_MINUTES](https://docs.gitea.com/next/administration/config-cheat-sheet#service-service) in your config).

**Comment by wxiaoguang** [comment]
Not all inactive accounts could be deleted, there are more checks in DeleteInactiveUsers

**Comment by ggodlewski** [comment]
I set ACTIVE_CODE_LIVE_MINUTES to 180 (was empty). Still nothing.

Inactive account from Dec 13, 2023 not deleted.
User doesn't have repos/orgs/packages 
https://github.com/go-gitea/gitea/blob/main/services/user/user.go#L291C1-L291C6

The only thing I can think of is that I'm getting this green confirmation but the tasks is not executed.
How are those tasks executed?

**Comment by Clortox** [comment]
I'm experiencing this problem as well with gitea 1.22.3. The newest account was made 7 days ago. Did you have any luck finding a workaround?

**Comment by JcDenis** [comment]
Same problem here.
Task failed because it was trying to delete organization.
Response from log here is:
`Task: Delete all unactivated accounts canceled: xyz is an organization not a user`
