### ISSUE TITLE
Issue comments are not updated after editing (if attachments are disabled)

### ISSUE THREAD

**Issue by ukct** [go-gitea/gitea#31485]
### Description

Attempting to edit a comment and then save it results in a javascript error withn repo-issue-edit.js, if attachments are disabled.

To reproduce:

* disable support for attachments
(https://docs.gitea.com/administration/config-cheat-sheet#issue-and-pull-request-attachments-attachment - set enabled to false)

From the UI:

* create new issue
* add a comment
* edit that comment
* saving the edit will throw a javascript error in the saveAndRefresh method in repo-issue-edit.js, when attempting to iterate through dropzoneInst

This appears to be a new issue introduced in 1.22. 

### Gitea Version

1.22.0

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

Helm gitea chart 

### Database

PostgreSQL

**Comment by wxiaoguang** [comment]
The problem will be fixed by:  Refactor dropzone #31482 

For 1.22 it needs a simple&separate fix:  Fix dropzone JS error when attachment is disabled #31486

**Comment by wxiaoguang** [comment]
Fixed by  #31486 and it is in 1.22-nightly
