### ISSUE TITLE
Avatar size in issues Mentions

### ISSUE THREAD

**Issue by mmarif4u** [go-gitea/gitea#3149]
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes
  - [ ] No
  - [ ] Not relevant

## Description
Currently it shows like that(screenshot below). Is it suppose to be like that?

## Screenshots
![selection_001](https://user-images.githubusercontent.com/1280585/33827213-8466bbd0-dea2-11e7-95b5-29f0111e9b5a.png)

**Comment by lafriks** [comment]
Seems to be that css is not loaded, this is bug

**Comment by mmarif4u** [comment]
Upgraded my installation. CSS is loaded properly there and showing proper list. It must be related to try.gitea.io.

**Comment by lafriks** [comment]
Yes, tested and locally for me it also works so it is just for try.gitea.io as it uses custom `head.tmpl` and it needs to be updated. @bkcsoft ?

**Comment by lafriks** [comment]
try.gitea.io template updated, does work now correctly
