### ISSUE TITLE
Pushlog are unavailable in gitea 1.3.x @ docker

### ISSUE THREAD

**Issue by davydov-vyacheslav** [go-gitea/gitea#3150]
Prerequisites:
* Gitea Version: 2cb6c51
* docker container image (latest as of 2017/11/22)

Hi,
previously I used Gitea project on raspberry pi, where I installed the product directly into the system.
Recently I have upgraded environment and now I switched to docker containers on NAS system. Transition was almost without issues. 
Unfortunately I experience only one issue: when I make push to master, I expected the system's dashboard shows me something like this:
```
davs pushed to master at davs/pushlog-issue
    ca8771a1be commit 3
    abed6bb441 commit 2
    e952de7309 initial commit
```

But after transition these new push logs are not available so far.
I hope that I have configuration issue and need your assist, please.

Attached app.ini:
[app.ini.txt](https://github.com/go-gitea/gitea/files/1547512/app.ini.txt)

Thanks,
Slava

**Comment by lunny** [comment]
@davydov-vyacheslav maybe the version should be v1.3.x ?

**Comment by lunny** [comment]
How did you migrate to new system and what's the error displayed when you push?

**Comment by davydov-vyacheslav** [comment]
@lunny , yes, sorry, 1.3.x 
migrate processs was like a charm:
- make database backup on source system (RPi)
- restored database on target system (NAS)
- started up the gitea on target system (NAS) . Migration process during first start was without issues

Attached logs during push
[push.log](https://github.com/go-gitea/gitea/files/1547750/push.log)

**Comment by lunny** [comment]
have you rewrite all public keys on admin panel?

**Comment by davydov-vyacheslav** [comment]
@lunny , sorry, where and what should I rewrite?

**Comment by programmeroftheeve** [comment]
I was having a similar issue with my repos, have you checked the permissions on the githooks to make sure that they are executable?

Example path: `</path/to/gitea/data>/git/<owner>/<repo>/hooks`.

**Comment by lafriks** [comment]
@davydov-vyacheslav go to admin panel and click "Rewrite all authorized keys" link

**Comment by davydov-vyacheslav** [comment]
@lafriks , thank for your reply. But, is it what you mean:
>> Rewrite '.ssh/authorized_keys' file (for Gitea SSH keys). There is no need to do this if you are using the built-in SSH server.

(I really don't think that it is necessary as I don't use ssh for gitea)

I did that and 
>> Resync pre-receive, update and post-receive hooks of all repositories.
as well 

but still nothing after push ...
Updated logs are:

[gitea.log2.txt](https://github.com/go-gitea/gitea/files/1549419/gitea.log2.txt)

**Comment by davydov-vyacheslav** [comment]
@btaidm , thank you for your reply as well !

I checked following path:
> /data/git/repositories/[user]/[project].git/hooks 

it has rights for 'git' user as well as Gitea RUN_USER in app.ini.
actually, everything under /data/git/repositories/ belongs to git:git user

**Comment by programmeroftheeve** [comment]
@davydov-vyacheslav  As they should. However, I was talking about the permissions on the hooks files, not just the owner and group.

run ```ls -l``` in one of the hooks directory, you should get something similar to this:

```
-rwxr-xr-x    1 1000     1000           478 Sep 14 15:33 applypatch-msg.sample
 ^^^
```
with the executable bit set. I pointed out the bits that need to be set for gitea. ```chmod u+rwx``` will give you the proper permissions for the hooks file. That will need to run on each of the files and
in the ```*.d``` directories.

**Comment by davydov-vyacheslav** [comment]
@ btaidm , thank you so much! that really helped!

Many thanks :)
