### ISSUE TITLE
Error on ssh/gpg page after gpg key add [docker]

### ISSUE THREAD

**Issue by tuxfanou** [go-gitea/gitea#3151]
- Gitea version (or commit ref): b82519c
- Operating system: linux (docker)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes (provide example URL) : https://try.gitea.io/user/settings/keys
  - [ ] No
  - [ ] Not relevant
- Log gist: https://gist.github.com/tuxfanou/4fb20c69fda836b79bb1549b14653468

## Description

After added gpg key in my profile, an error occurred each time I going to ssh/gpg settings :

template: user/settings/keys_gpg:19:55: executing "user/settings/keys_gpg" at <.Expired.IsZero>: can't evaluate field Expired in type *models.GPGKey

**Comment by lafriks** [comment]
Seems to be introduced by #3142

**Comment by sapk** [comment]
Is it fix by #3153 ?

**Comment by lunny** [comment]
resolved by #3153
