### ISSUE TITLE
unauthorized: reqPackageAccess when pushing to container registry

### ISSUE THREAD

**Issue by dlmw** [go-gitea/gitea#31531]
### Description

I successfully logged in to my user with `docker login`. I logged in with my usual username/password. When I push the image, I get the error `unauthorized: reqPackageAccess`.

What's the issue?

### Gitea Version

1.22.0

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

Docker Swarm

### Database

PostgreSQL

**Comment by kemzeb** [comment]
Thanks for the bug report! Are there any logs that you would be able to provide from your Gitea instance associated with you pushing to your registry?

**Comment by dlmw** [comment]
```
2024/07/07 08:32:03 ...eb/routing/logger.go:102:func1() [I] router: completed POST /v2/dlmw/minecraft/blobs/uploads/ for 10.0.0.2:0, 401 Unauthorized in 1.1ms @ packages/api.go:42(packages.ContainerRoutes.func2.1.reqPackageAccess.4)
2024/07/07 08:32:03 ...eb/routing/logger.go:102:func1() [I] router: completed POST /v2/dlmw/minecraft/blobs/uploads/ for 10.0.0.2:0, 401 Unauthorized in 1.1ms @ packages/api.go:42(packages.ContainerRoutes.func2.1.reqPackageAccess.4)
```

I think those are the relevant ones.

**Comment by delvh** [comment]
You need to supply a PAT to authenticate yourself to Gitea (this has nothing to do with Docker). Your token needs either `packages.Read` or `packages.Write` permission, in this case probably write, and you must be allowed to push a package to the given user.,

**Comment by dlmw** [comment]
How do I do that if it's not related to Docker?

**Comment by delvh** [comment]
![grafik](https://github.com/go-gitea/gitea/assets/51889757/97133152-cd34-4e98-affa-9688a3d1c735)

**Comment by dlmw** [comment]
Thank you. A bit off-topic but is there a way to push an image to a repository instead of a user?

**Comment by delvh** [comment]
No, but you can link a package to a repo once it has been pushed.

**Comment by olsonpm** [comment]
I don't understand why a PAT is required.  The [docs mention](https://docs.gitea.com/usage/packages/container) it's only for the case of 2FA
