### ISSUE TITLE
Can't run  make generate-images

### ISSUE THREAD

**Issue by alicetails** [go-gitea/gitea#31537]
### Description

Hi guys! I have gitea setup on VM (no docker)

I wanna to update logos to custom. According to docs i shall run make generate-images, but there is no makefile, how can i regenerate logos without reinstalling gitea?

I tryed to download repo with makefile and executed make generate-images, it was executed with no errors, but nothing changed

### Gitea Version

1.22.0

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

2.20.1

### Operating System

Debian GNU/Linux 10 (buster) in LXC on Proxmox

### How are you running Gitea?

Was installed from TurnKey, rebuild with separate DB and LFS

### Database

PostgreSQL

**Comment by silverwind** [comment]
You need a source checkout of the gitea repo to run it, it's not part of the binary distributions.

**Comment by alicetails** [comment]
Hi, @silverwind ! I solved it another way. I've modified tmpl files and now everything is good. Thank you!
