### ISSUE TITLE
OpenWRT (.ipk) packages

### ISSUE THREAD

**Issue by ExplodingDragon** [go-gitea/gitea#31532]
### Feature Description

`openwrt` packages are modified  of the `debian` packages, and the indexing is similar to `archlinux`.   refer to `rpm` for routing patterns.

**Comment by ExplodingDragon** [comment]
I'll be submitting a new PR later.

**Comment by KN4CK3R** [comment]
What's the cost/benefit ratio of OpenWRT packages in Gitea? I think the userbase is very small?

**Comment by ExplodingDragon** [comment]
> What's the cost/benefit ratio of OpenWRT packages in Gitea? I think the userbase is very small?

**Openwrt** / **immortalwrt** is popular in China, most people use x86 hosts to build home routes for VPN or for home lab .   [Google Search](https://www.google.com/search?q=openwrt+%E6%90%AD%E5%BB%BA)
