### ISSUE TITLE
Building 1.18.5 not successful for go.jolheiser.com modules

### ISSUE THREAD

**Issue by zcopado** [go-gitea/gitea#31534]
### Description

Upon attempting to build the docker image for gitea v1.18.5, it fails as follows:

> 420.2 go: downloading go.jolheiser.com/pwn v0.0.3
> 420.2 go: downloading go.jolheiser.com/hcaptcha v0.0.4
> 421.4 Running go generate...
> 421.5 go: downloading go.jolheiser.com/pwn v0.0.3
> 421.5 go: downloading go.jolheiser.com/hcaptcha v0.0.4
> 421.5 go: downloading github.com/mattn/go-sqlite3 v1.14.15
> 423.0 go: downloading github.com/lunny/vfsgen v0.0.0-20220105142115-2c99e1ffdfa0
> 423.0 go: downloading github.com/shurcooL/httpfs v0.0.0-20190707220628-8d4bc4ba7749
> 423.2 generating bindata for migration
> 423.3 generating bindata for options
> 423.8 generating bindata for public
> 425.2 generating bindata for templates
> 425.9 CGO_CFLAGS="-g -O2 -DSQLITE_MAX_VARIABLE_NUMBER=32766" go build -v  -tags 'bindata timetzdata sqlite sqlite_unlock_notify' -ldflags '-s -w  -X "main.MakeVersion=GNU Make 4.3" -X "main.Version=1.18.5" -X "main.Tags=bindata timetzdata sqlite sqlite_unlock_notify"' -o gitea
> 425.9 go: downloading go.jolheiser.com/pwn v0.0.3
> 425.9 go: downloading go.jolheiser.com/hcaptcha v0.0.4
> 426.1 get "go.jolheiser.com/hcaptcha": found meta tag vcs.metaImport{Prefix:"go.jolheiser.com/hcaptcha", VCS:"git", RepoRoot:"https://git.jojodev.com/jolheiser/hcaptcha.git"} at //go.jolheiser.com/hcaptcha?go-get=1
> 426.1 get "go.jolheiser.com/pwn": found meta tag vcs.metaImport{Prefix:"go.jolheiser.com/pwn", VCS:"git", RepoRoot:"https://git.jojodev.com/jolheiser/pwn.git"} at //go.jolheiser.com/pwn?go-get=1
> 428.6 modules/hcaptcha/hcaptcha.go:12:2: reading go.jolheiser.com/hcaptcha/go.mod at revision v0.0.4: git ls-remote -q origin in /go/pkg/mod/cache/vcs/ef3d79b39382e527acfd165be9b783d048675767dd531fc8f9a1d98b0456091c: exit status 128:
> 428.6   fatal: could not read Username for 'https://git.jojodev.com': terminal prompts disabled
> 428.6 Confirm the import path was entered correctly.
> 428.6 If this is a private repository, see https://golang.org/doc/faq#git_https for additional information.
> 428.6 modules/auth/password/pwn.go:12:2: reading go.jolheiser.com/pwn/go.mod at revision v0.0.3: git ls-remote -q origin in /go/pkg/mod/cache/vcs/786a97460bd4f3de914d0fc0218c25c3cf69c8ace8bb4b23e40bdf769bf2e325: exit status 128:
> 428.6   fatal: could not read Username for 'https://git.jojodev.com': terminal prompts disabled
> 428.6 Confirm the import path was entered correctly.
> 428.6 If this is a private repository, see https://golang.org/doc/faq#git_https for additional information.
> 428.6 make: *** [Makefile:733: gitea] Error 1

Now, looking at these modules here, they report their repositories correctly:

- https://pkg.go.dev/go.jolheiser.com/pwn --> https://gitea.com/jolheiser/pwn.git

- https://pkg.go.dev/go.jolheiser.com/hcaptcha --> https://gitea.com/jolheiser/hcaptcha.git

Apologies, but my 'go' familiarity is limited, so, look as I may, I could not find a work around for this, where the correct repository location could be properly set to "override" what is being reported. 

How can I get beyond this to properly build a v1.18.5 image?

### Gitea Version

1.18.5

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

2.45.2

### Operating System

MacOS Sonoma 14.5

### How are you running Gitea?

We utilize gitea in K8s.

### Database

PostgreSQL

**Comment by jolheiser** [comment]
Generally the go proxy should have accounted for this, I haven't hosted those modules since I moved them into the repo directly. 
I'll add a proper redirect for them in a moment, which should fix the issue.

**Comment by zcopado** [comment]
Thank you @jolheiser. The last time we built this image was July 2023, and this was not a problem then. 

Cheers, and thank you for the prompt response.

**Comment by techknowlogick** [comment]
Hi @zcopado it is strongly recommended that you use the current stable version of Gitea as it has bug fixes and security patches that aren't included in 1.18.X
Can I ask why you are using the EOL-version instead of something more recent?

**Comment by zcopado** [comment]
@techknowlogick - of course. We utilize gitea as a basis for an internal service offering. We customize templates, etc, and every time we upgrade, we have to go through the process of adapting the templates, etc.

We are currently planning a jump to gitea 1.20.x within the next 30 - 60 days, but we only update 1-2x annually. 

Our current stable version is on v1.18.5. Hope that helps clarify.

**Comment by jolheiser** [comment]
I've updated my webserver for those two modules. Good luck with your update! 🙂

**Comment by zcopado** [comment]
@jolheiser - Worked like a charm. Cheers.
