### ISSUE TITLE
Transfering ownership of repo with issues in a project board to another org breaks project board columns

### ISSUE THREAD

**Issue by gira0** [go-gitea/gitea#31538]
### Description

Hello everyone, I've noticed that when I move repositories that currently has issues in the project board to another organization, the project board still has the issues from the moved repo which now kinda break the columns they are in. Sometimes other issues can't be moved in or out of the bugged columns. The only solution I currently have is to go to the moved repositories and edit the issues so they don't have the project board referenced there. 

I think a solution would be that if you transfer ownership to another organization that all issues in that repo get their project board reference removed and that this would be mentioned in the warning. 

I've replicated the issue on the demo instance, you can find my bugged project board here: https://gitea.com/aurora-testorg1/-/projects/3256

If you need any further information of testing from my side, please let me know!

### Gitea Version

1.22.0

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

![ezgif-4-387a0728e5](https://github.com/go-gitea/gitea/assets/19488367/5c9efbdb-b9b8-4a15-9a1c-81428c543999)
(When my mouse goes to the top left I'm reloading the website)

### Git Version

2.43.5

### Operating System

RedHat 8.10

### How are you running Gitea?

I've replicated this on my local instance (release downloaded from github) and on demo.gitea.com

### Database

PostgreSQL

**Comment by lunny** [comment]
Fixed by #31770
