### ISSUE TITLE
Update Swagger documentation for REST Api methods

### ISSUE THREAD

**Issue by lraubuch** [go-gitea/gitea#31552]
### Feature Description

When checking the REST Api documentation I came across the method to add a collaborator to a repository.
In the [documentation](https://docs.gitea.com/api/1.20/#tag/repository/operation/repoCheckCollaborator) it said, that the payload body needs to contain a permission value which was expected. Unfortunately there was no documentation of what that string value should be to set the appropriate permissions.
After digging deep into the [code](https://github.com/go-gitea/gitea/blob/b270b30aebf42fb45d9a57288cf3dcbfa842a760/models/perm/access_mode.go#L46) I found that the permission can be one of three values. 

IMHO this should be documented in the Swagger documentation of the REST Api.

### Screenshots

![grafik](https://github.com/go-gitea/gitea/assets/35454706/94f77718-a4e4-4871-a9f6-62ec07be0950)

**Comment by wolfogre** [comment]
It's missed. I think it's not difficult to add it.
