### ISSUE TITLE
Some template strings not replaced in documentation

### ISSUE THREAD

**Issue by M393** [go-gitea/gitea#31555]
### Description

`@minNodeVersion@` `@minGoVersion@` `@version@`
https://docs.gitea.com/installation/install-from-binary but also on other pages

### Gitea Version

1.22.0

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

https://docs.gitea.com/

### Database

None

**Comment by jolheiser** [comment]
Thanks for the report! 

I see https://gitea.com/gitea/docs/issues/10 also reported, so I'm going to close this one for now.
It must have been missed in the docs repo changes.
