### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#31568]
### Description

Hi,
Yesterday we upgraded from 1.21.10 to 1.22.1.
1.21.10 was running with around 500 MB RAM used.
1.22.1 goes crazy with RAM while having a lot of reads on the disks and being so slow users think it is broken.

We have lots of messages like these in the logs:
2024/07/05 14:23:45 ...eb/routing/logger.go:68:func1() [W] router: slow POST /somecontext/blabla for 172.29.254.107:55682, elapsed 3078.6ms @ repo/githttp.go:477(repo.ServiceUploadPack)

Any ideas?
Thanks a lot!

### Gitea Version

1.22.1

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![usage_over_Time](https://github.com/go-gitea/gitea/assets/142231390/a7e8e788-efc2-434e-9cee-4b63606e44fd)
![top](https://github.com/go-gitea/gitea/assets/142231390/2c11cc9d-610d-4a48-9006-5aee1b477aa9)

### Git Version

2.43.5

### Operating System

Oracle Linux 8

### How are you running Gitea?

Using the downloads from Github for Linux AMD64, running as service on OL8.

### Database

MySQL/MariaDB

**Comment by MICCustomsSolutions** [comment]
We have lots of messages like these in the logs:
2024/07/05 14:23:45 ...eb/routing/logger.go:68:func1() [W] router: slow      POST /somecontext/blabla for 172.29.254.107:55682, elapsed 3078.6ms @ repo/githttp.go:477(repo.ServiceUploadPack)

**Comment by MICCustomsSolutions** [comment]
We have lots of messages like these in the logs:
2024/07/05 14:23:45 ...eb/routing/logger.go:68:func1() [W] router: slow      POST /somecontext/blabla for 172.29.254.107:55682, elapsed 3078.6ms @ repo/githttp.go:477(repo.ServiceUploadPack)

**Comment by MICCustomsSolutions** [comment]
Seems to be the same issue as #31565 
Disabling the index fixes the issue.
