### ISSUE TITLE
Typo inside ``Camo#Allways``

### ISSUE THREAD

**Issue by litetex** [go-gitea/gitea#31575]
### Description

The value of ``Camo#Allways`` seems to have a typo. It should be ``Camo#Always`` with one ``l``.

Can be found here:
https://github.com/search?q=repo%3Ago-gitea%2Fgitea%20ALLWAYS&type=code
* https://github.com/go-gitea/gitea/blob/12cb1d2998f2a307713ce979f8d585711e92061c/modules/setting/camo.go#L12
* https://github.com/go-gitea/gitea/blob/12cb1d2998f2a307713ce979f8d585711e92061c/docs/content/administration/config-cheat-sheet.en-us.md?plain=1#L592
* https://github.com/go-gitea/gitea/blob/12cb1d2998f2a307713ce979f8d585711e92061c/modules/markup/camo.go#L41
* https://github.com/go-gitea/gitea/blob/12cb1d2998f2a307713ce979f8d585711e92061c/custom/conf/app.example.ini#L526

**Comment by lunny** [comment]
Close as @charles7668 's feedback.

**Comment by wxiaoguang** [comment]
But it is indeed a typo. `all_ways` should be `ALL_WAYS` according to the naming style (underline between words).

**Comment by SuperSandro2000** [comment]
Since gitea has no strict config validation, it is really easy to miss configure this.
