### ISSUE TITLE
Add scroll to dropdowns

### ISSUE THREAD

**Issue by stuzer05** [go-gitea/gitea#31589]
### Description

If there're too many option in dropdowns, ui kinda breaks

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/23124682/b5fe69af-313e-4839-9193-0f8470f7a2dd)

### Gitea Version

 1.23.0+dev-300-g5791a73e75

### Can you reproduce the bug on the Gitea demo site?

Yes

### Browser Version

latest chrome

**Comment by wxiaoguang** [comment]
It seems to be a UI regression, the dropdown menu lost max-height limit.
