### ISSUE TITLE
How to have multiple docker instances on the same host system?

### ISSUE THREAD

**Issue by sprappcom** [go-gitea/gitea#31592]
### Description

i think this is a bug as i can only have 1 docker instance per host.

### Gitea Version

1.22

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

1. i followed the example, created it. try to create another version but it doesnt work with docker compose

2. how to have nginx running as tls terminator frontend with docker container when i cant bridge the host default network (without any extra startup configuration)

### Database

MySQL/MariaDB

**Comment by lunny** [comment]
This is a common usage about docker, it's not a special question with Gitea. You can find some docker documentations to know about that.
