### ISSUE TITLE
Set more environment variables to allow their use in custom hooks

### ISSUE THREAD

**Issue by afdev82** [go-gitea/gitea#316]
In order to write custom hooks that use some variables, Gitea should export them in the environment.

For example, currently I need to know the user that is pushing a branch.
I think this could be easily done adding an `os.Setenv` line like [here](https://github.com/gogits/gogs/blob/7e15ff9486cde36b76f3d39b7db23f89278acb7d/cmd/serve.go#L256).

**Comment by strk** [comment]
#317 adds one such variable, do you have a list of variables you think should be exposed ?

**Comment by afdev82** [comment]
@strk Yes, I opened the #317 :stuck_out_tongue: 
I don't have a list, I think it's enough to know the user that is pushing (for my actual needs).
I saw that also the https://github.com/gogits/gogs/pull/3921, I think we should agree how many variables to expose and document that.
I exported the name, because I don't think it's a good idea to expose the id. IMHO for a custom hook it would be enough to have the name (to whitelist it).

**Comment by lunny** [comment]
since #317 is in 1.1, so I change this to 1.1

**Comment by tboerger** [comment]
I would take that into the 1.0 release because users like @afdev82 are able to provide hooks for protected branches until we release native protected branches. This change is quite simple.

**Comment by lunny** [comment]
Then what's the status of #317? If #317 will be merged in 1.0, this could be changed to 1.0

**Comment by tboerger** [comment]
It just needs another lgtm

**Comment by bkcsoft** [comment]
@afdev82 was this supposed to be closed with #317 ? otherwise feel free to reopen it (it got closed automagically by merging 317)

**Comment by afdev82** [comment]
@bkcsoft Yes, it's fine. Thanks ;)

**Comment by afdev82** [comment]
I didn't understand the target version, I thought was the 1.0.0 release in the end.

**Comment by tboerger** [comment]
You are right, it will be available for 1.0.0
