### ISSUE TITLE
Update docs to include different Redis connections 

### ISSUE THREAD

**Issue by davama** [go-gitea/gitea#31618]
### Feature Description

Good Day Everyone,

I am looking into making our gitea highly-available. We have a redis-sentinel cluster and wanted to see if gitea supports it.
Looking around i found this interesting comment: https://github.com/go-gitea/gitea/issues/16017#issuecomment-851935738

I tested this on our dev gitea and it works well.

When i look at the [redis module](https://github.com/go-gitea/gitea/blob/main/modules/nosql/manager_redis.go ) i see it uses a case switch for different Redis implementations.

Can we update the documentation so that folks are aware of these features?
Willing to submit PR.

Thank you for your consideration 

Thanks,
Dave

**Comment by lunny** [comment]
It's kind of you to send contributions. Please send docs PR to https://gitea.com/gitea/docs.

**Comment by davama** [comment]
@lunny 

thank you for responding

PR is here: https://gitea.com/gitea/docs/pulls/38

**Comment by kemzeb** [comment]
Should we close this since the PR was merged?
