### ISSUE TITLE
Pipeline Report Result Plugin System

### ISSUE THREAD

**Issue by uvulpos** [go-gitea/gitea#31611]
### Feature Description

A pipeline can produce artifacts like [Unit Test Reports](https://learn.microsoft.com/en-us/azure/devops/pipelines/test/review-continuous-test-results-after-build?view=azure-devops), [OWASP Zap Scan Reports](https://github.com/zaproxy/zaproxy), Sonarcube Quality Reports from [code scanners](https://github.com/SonarSource/sonar-scanner-npm),... and I was thinking about a configureable pipeline run page, where you could visualize the data via a web container or something. So gitea would just build a plugin system and companies or open source projects could then develop their basic integration of their tooling.

Is that an idea you would like to think further about it, or is this way out of scope for Gitea + Gitea Actions?

**Comment by lunny** [comment]
This could be completed with an action. So for Gitea's responsibility, it can support some standard artifacts formats. When actions upload artifacts, special formats files can be viewed online instead of downloading.
