### ISSUE TITLE
Using a custom theme causes syntax highlighting of code previews to appear all white

### ISSUE THREAD

**Issue by drac-dot-gay** [go-gitea/gitea#31614]
### Description

i use a custom theme on my gitea instance, and it causes source code previews to be all white. you can see an example [here](https://vcs.cozydsp.space/cozy-dsp/comber/src/branch/main/src/lib.rs)

when i edit the file in the web, the colors work as expected

### Gitea Version

1.22.1

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/8054329/92d42128-01f9-48ed-adda-24bb020848cf)
![image](https://github.com/go-gitea/gitea/assets/8054329/d86d603e-c59a-48c6-bb48-d7dafe3b1e29)

### How are you running Gitea?

using the package provided by TrueNAS scale, which runs a docker image on kubernetes

### Database

None

**Comment by lsd-techno** [comment]
there is includes that are responsible to colorize code preview, I add those files/folders to custom to solve the issue: https://github.com/lsd-techno/gitea-theme/pull/4

**Comment by lunny** [comment]
Close per @lsd-techno 's workaround.

**Comment by murl-digital** [comment]
Should this be at least documented somewhere perhaps?

**Comment by lunny** [comment]
Maybe https://docs.gitea.com/awesome?_highlight=theme/awesome#themes is a good place to document it.
