### ISSUE TITLE
Actions tab `Running` spinner animation off-center

### ISSUE THREAD

**Issue by FrostKiwi** [go-gitea/gitea#31621]
### Description

This has been always bugging me since release of the Actions tab:
The loading spinner is not center aligned, so it wobbles like a broken wheel.
![spinner](https://github.com/user-attachments/assets/dd0c9fcd-9310-4544-96fd-c3a19bdbc0b2)

Having read this, you can now not unsee it any time you look into the actions tab.

### Gitea Version

1.22.1

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

Installed via binary

### Database

None

**Comment by silverwind** [comment]
Likely need to alter `transform-origin`on it.

**Comment by FrostKiwi** [comment]
> Likely need to alter `transform-origin` by like half a pixel, or report the bug to [octicons](https://github.com/primer/octicons) because I assume the SVG is off-center in the source as well.

Just rechecked it octicons, and there is no such misalignment. Then rechecked with browser other than Firefox and there is no such issue in Gitea either!
It's a Firefox specific bug.

**Comment by silverwind** [comment]
Might even be OS-related, it looks perfect for me in Firefox 129 on MacOS:

![](https://github.com/user-attachments/assets/09e6d5dc-2da3-4185-a87f-fa7a3c2c3ae4)

What's your OS?

**Comment by FrostKiwi** [comment]
Windows 11 and 10.
I'll follow this up in the Firefox issue tracker.
