### ISSUE TITLE
Untrusted CA ZEROSSL when uploading LFS objects

### ISSUE THREAD

**Issue by gesangtome** [go-gitea/gitea#31620]
### Description

When I am uploading a REPO with a GIT LFS object to my gitea instance, I get an error about SSL authentication: 

batch response: Post "https://xxx.git/info/lfs/objects/batch":
 tls: failed to verify certificate: x509: certificate signed by unknown authority

I confirm that gitea works fine in EDGE/Chrome, it uses SSL certificates issued by ZEROSSL, but it errors when pushing in GIT COMMAND.

### Gitea Version

Gitea 1.22.1 

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://static.linux-site.org/gitea.log

### Git Version

git version 2.45.2

### Operating System

K3s

### How are you running Gitea?

Official gitea docker image

### Database

MySQL/MariaDB

**Comment by wolfogre** [comment]
Hmm, I don't really think it's a bug of Gitea. It seems that the environment where you run the command missed some CA root certs. How did you apply the HTTPS certs? Did you use a reverse proxy like Nginx/Caddy, or did you configure it directly in Gitea to listen on port 443? What happens if you run `curl -v xxx.git/info/lfs/objects/batch`?

**Comment by wxiaoguang** [comment]
> I confirm that gitea works fine in EDGE/Chrome, it uses SSL certificates issued by ZEROSSL, but it errors when pushing in GIT COMMAND.

You need to add an intermediate cert to your issues cert. 

* https://help.zerossl.com/hc/en-us/articles/360060120113-Download-Certificate
* https://help.zerossl.com/hc/en-us/articles/360058296114-Missing-Intermediate-Certificate

And/or you need to update your local root ca files to recognize the latest zerossl certs.
