### ISSUE TITLE
Problem with adopting unadopted Repositories

### ISSUE THREAD

**Issue by muhamad** [go-gitea/gitea#31631]
### Description

Steps to reproduce it as it happened with me:

1. Create an organization with normal name like `online`.
2. In the filesystem go to repos directory and create directory with name `online`.
3. Put not less than 60 bare repository in that directory (I've 280 bar repo which are later be mirrored).
4. In Gitea go to `Site Administration` ->`Code Assets` -> `Repositories` then click on `Unadopted Repositories`.
5. In the search box write `online` then press search icon.
6. In the list of repositories start adopting them by pressing `Adopt Files`.
7. when you reach the 15th repository the adopted repositories from 1st to 14th will start getting listed again one by one when continuing adopting other repositories.

### Gitea Version

1.22.1

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

git version 2.45.0.windows.1

### Operating System

Windows 10 Pro 22H2

### How are you running Gitea?

As a windows service, but issue can be produced running as standalone application

### Database

SQLite

**Comment by muhamad** [comment]
Up to not get forgotten.

**Comment by muhamad** [comment]
No there is not, Also I was able to reproduce it again in gitea 1.22.2 using the executable "gitea-1.22.2-windows-4.0-amd64.exe".

To reproduce it do the following

1. Start gitea without database then create a user "X" and an organization "Y".
2. In the data folder for repos create a folder with name "Y".
3. In the folder `Y` run the powershell command `1..60 | % tostring 00 | % { git init --bare ".\$_.git" }` to create 60 bare repos in the format `xx.git`
4. Start adopting the bare repos in `Y`. when adopt all to the `50` - including it - everything still fine.
5. Once you adopt the repo `51` the repo `01` will re-apear in the `Unadopted Repositories` section again.
6. If you continue adopting repos the section `Unadopted Repositories` will keep showing adopted repos, I guess to keep the 50 entry per page.

**Comment by muhamad** [comment]
??

**Comment by wxiaoguang** [comment]
There are different "adopt" pages.

I think the problem you encountered is the admin page. But to be honest, I have no idea how to reproduce.

I managed to created 90 repositories:

```
for i in {10..99}; do git init --bare "$i.git"; done
```

Then I could adopt beyond 60:

![image](https://github.com/user-attachments/assets/0ad38de1-3209-46a2-91f1-fdcdb9fdb59b)

**Comment by muhamad** [comment]
Your're correct, I use the Adopt repositories from the admin page. I didn't migrate to latest gitea release, I will check and get back to you.

**Comment by wxiaoguang** [comment]
Thank you for the quick feedkback. I think this issue could be closed.
