### ISSUE TITLE
Wrong version in installation documentation

### ISSUE THREAD

**Issue by Choppel** [go-gitea/gitea#31630]
### Description

Up to a month ago the documentation at https://docs.gitea.com/installation/install-from-binary#downloading-with-wget stated the current version number so that the commands could be used directly.
Now, on the whole page, there is only @version@ which looks like a placeholder for the current version number. Is this by design or is this a bug?

### Gitea Version

1.22.1

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

N/A

### Database

None

**Comment by lunny** [comment]
This has been reported https://gitea.com/gitea/docs/issues/10
