### ISSUE TITLE
When I enable HTTPS and pushed, it said that "Gitea: Internal Server Connection Error."

### ISSUE THREAD

**Issue by LynYugiri** [go-gitea/gitea#31647]
### Description

My CA cert is self-signed. I enabled HTTPS protocol by set " PROTOCOL = https                                                                       CERT_FILE = /var/lib/gitea/ssl/https.crt
 KEY_FILE = /var/lib/gitea/ssl/https.key".
Git clone repos by https protocol is OK, but error used ssh protocol.Used ssh protocol to pull or push, It said that "Gitea: Internal Server Connection Error
fatal: Could not read from remote repository

Please make sure you have the correct access rights
and the repository exists."
And used https protocol to push, it said "
remote: Gitea: Internal Server Connection Error 
To https://ip:3000/Sniventals/test.git
! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://ip:3000/Sniventals/test.git' "

### Gitea Version

1.22.1

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/Creeper-xie/208139810da9c2840f03a59282986211

### Screenshots

![ResizedImage_2024-07-17_13-16-45_1871](https://github.com/user-attachments/assets/dee09dbe-cf1d-4551-90f3-abcd4480a649)
![ResizedImage_2024-07-17_13-35-43_2075](https://github.com/user-attachments/assets/895d24e9-8541-4bc2-81ec-1014c71cdd9f)

"gp" alias to "git push"

### Git Version

2.45.2

### Operating System

Debian SID

### How are you running Gitea?

I download gitea from this Github release.
https://github.com/go-gitea/gitea/releases/tag/v1.22.1

### Database

PostgreSQL

**Comment by amix307** [comment]
@Creeper-xie when you set https, you must change ROOT_URL in app.ini too

**Comment by lunny** [comment]
Can you paste your configuration about ROOT_URL and LOCAL_ROOT_URL?

**Comment by ccheath** [comment]
> remote: Gitea: Internal Server Connection Error
> To https://ip:3000/Sniventals/test.git
> ! [remote rejected] master -> master (pre-receive hook declined)
> error: failed to push some refs to 'https://ip:3000/Sniventals/test.git' "

I'm having the same issue after a fresh install...

**Comment by techknowlogick** [comment]
@Creeper-xie @ccheath are you able to adjust the local_root_url to be http://localhost:3000 ?

**Comment by ccheath** [comment]
@techknowlogick thanks for the reply... I did try that (and also 127.0.0.1)... resolved the issue by checking the /etc/hosts and found that my localhost line was commented out (facepalm)

**Comment by techknowlogick** [comment]
@ccheath glad to hear :)
