### ISSUE TITLE
Please help about Jupyter file support

### ISSUE THREAD

**Issue by ChanLicher** [go-gitea/gitea#31654]
### Description

I 100% followed the instruction of external renderers on the docs, and even fork the repository to build a new docker image. No matter what it return an error:

**Render, jupyter render run command jupyter-nbconvert [--stdin --stdout --to html --template basic] failed: exec: "jupyter-nbconvert": executable file not found in $PATH**

Part of logs:
```
`2024/07/18 02:39:06 ...es/charset/escape.go:41:EscapeControlReader() [E] Error whilst escaping: jupyter render run command jupyter-nbconvert [--stdin --stdout --to html --template basic] failed: exec: "jupyter-nbconvert": executable file not found in $PATH
Stderr: 
2024/07/18 02:39:06 ...ers/web/repo/view.go:535:renderFile() [E] Render: jupyter render run command jupyter-nbconvert [--stdin --stdout --to html --template basic] failed: exec: "jupyter-nbconvert": executable file not found in $PATH
Stderr: 
2024/07/18 02:39:06 ...eb/routing/logger.go:102:func1() [I] router: completed GET /ChanLicher/3d_hippocampus/src/branch/master/newtrain.ipynb for 10.60.13.108:6275, 500 Internal Server Error in 12.8ms @ repo/view.go:774(repo.Home)`
```

I just transferred my code to gitea a few days ago, maybe I am not familiar enough with gitea. But please offer some solutions of how to solve this issue.
![PixPin_2024-07-18_02-38-20](https://github.com/user-attachments/assets/cab8e9ed-38d7-4a28-8b94-56ddbf2c70e1)

### Gitea Version

1.22.1

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

Docker on Linux

### How are you running Gitea?

I first used the offical docker image, and tried to install external renderers using command line. After that, I tried to build a docker image with these renderers, but it still returned the same error as mentined above.

### Database

MySQL/MariaDB

**Comment by yp05327** [comment]
![image](https://github.com/user-attachments/assets/884aaa6a-03b2-4ff9-9dca-3e9b08b41830)
It is `jupyter nbconvert` in the document.
But in your error logs, it seems that you are using `jupyter-nbconvert`

**Comment by ChanLicher** [comment]
> ![image](https://private-user-images.githubusercontent.com/18380374/350823879-884aaa6a-03b2-4ff9-9dca-3e9b08b41830.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2ODA1NzYsIm5iZiI6MTcyMTY4MDI3NiwicGF0aCI6Ii8xODM4MDM3NC8zNTA4MjM4NzktODg0YWFhNmEtMDNiMi00ZmY5LTlkY2EtM2U5YjA4YjQxODMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDIwMzExNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5M2VmYjY3M2Q2ODc2ZTE0NjYzZjI4MDhkMzg5MTA3MTNhOWFjMWYxMGIyMGU2MmRkZGExYWQ0MmU0NTdjOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gTf2B9M_loXd7ecQHGsEABAtZ21y4DexVwaekYcwkjk) It is `jupyter nbconvert` in the document. But in your error logs, it seems that you are using `jupyter-nbconvert`

Sorry, I didn't mention that. I tried both "jupyter-nbconvert" and "jupyter nbconvert". Scroll down, and you can see another instruction about jupyter notebook, that one uses "jupyter-nbconvert".

**Comment by yp05327** [comment]
![image](https://github.com/user-attachments/assets/61abbb5c-0e03-4de5-9d25-67e247b5db1c)
I think the problem is this. Even you have installed them, but they are not in PATH, so Gitea can not use it.
As a simple solution, you can install them into `/usr/local/bin`,
``` Dockerfile
RUN PIPX_HOME=/opt/pipx PIPX_BIN_DIR=/usr/local/bin pipx install jupyter docutils --include-deps
```
See: https://github.com/pypa/pipx/issues/754

**Comment by yp05327** [comment]
And also if the rendering was failed, we should not show 500 error page, a flash error is enough I think.

**Comment by ChanLicher** [comment]
> ![image](https://private-user-images.githubusercontent.com/18380374/351149637-61abbb5c-0e03-4de5-9d25-67e247b5db1c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2OTgxNDQsIm5iZiI6MTcyMTY5Nzg0NCwicGF0aCI6Ii8xODM4MDM3NC8zNTExNDk2MzctNjFhYmJiNWMtMGUwMy00ZGU1LTlkMjUtNjdlMjQ3YjVkYjFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIzVDAxMjQwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1MjRmMzM4YjYyYWQzZDI3YTVkNDllYmQwYzRkNDNhZDRhMjUzN2Y5MWIxMzdiOWFhMjE5MTU4YjZiMTZjYmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mMsIugHBboJ6m675iQ9TpwsoHiEm72vzmd3di0CNnrs) I think the problem is this. Even you have installed them, but they are not in PATH, so Gitea can not use it. As a simple solution, you can install them into `/usr/local/bin`,
> 
> ```dockerfile
> RUN PIPX_HOME=/opt/pipx PIPX_BIN_DIR=/usr/local/bin pipx install jupyter docutils --include-deps
> ```
> 
> See: [pypa/pipx#754](https://github.com/pypa/pipx/issues/754)

It works! Thank you very much. I think you can add this to the docs. Wonderful project by the way.

**Comment by yp05327** [comment]
Update: There's a more simple solution.
https://gitea.com/gitea/docs/pulls/33

**Comment by ChanLicher** [comment]
Cool!
