### ISSUE TITLE
Cleanup of old action runs

### ISSUE THREAD

**Issue by saffis** [go-gitea/gitea#31653]
### Feature Description

Issue see here: [https://forum.gitea.com/t/cleanup-of-old-actions/9428](https://forum.gitea.com/t/cleanup-of-old-actions/9428)

Feature to automatically cleanup old action runs (e.g. keep only a configurable number of runs)
- Cleanup Database (commit_status, action_run, ...)
- Cleanup actions_log

**Comment by wolfogre** [comment]
Duplicated with #24256.
