### ISSUE TITLE
Actions workflow schedule to support UTC

### ISSUE THREAD

**Issue by keyallis** [go-gitea/gitea#31657]
### Feature Description

It is my understanding that [Github Actions schedule objects are all interpreted as UTC](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onschedule). After configuring some cron workflows and setting them to run at 9AM, I have noticed that they run at 9AM local time and not 9AM UTC. I am unsure if this was an intended effect or could be viewed as a bug.

I see the following as paths forward:
* Document that workflow schedules are configured to local time
* Change workflow schedules to instead be based on UTC
* Add a configuration value to allow cron to be interpreted as either local or UTC, default to use local to retain current behaviors and add documentation to clarify

For posterity here is my observed behavior:
Given a workflow defined to run as
```
on:
  schedule:
    - cron: "0 9 * * *"
```

I see job ran ~25 minutes ago at roughly that amount of time past 9AM local
![image](https://github.com/user-attachments/assets/16f06f34-e3a0-49f2-acb5-0c8dc111bfc7)

### Screenshots

![image](https://github.com/user-attachments/assets/40165b08-7279-4fd0-b132-e3aac023bd0f)

**Comment by wolfogre** [comment]
Confirmed, it's a bug. Before it gets fixed, you can specify the timezone like `TZ=UTC 0 9 * * *`.
