### ISSUE TITLE
Redis Go module not downloading

### ISSUE THREAD

**Issue by SSP6904** [go-gitea/gitea#31658]
### Description

I'm building the Gitea docker image using the source code. However, on every build command I'm using, the make command exits the command because of a go module not able to find it's required release. 

I looked up if the release is available, but the latest release is version v9.5.2. Not sure how I can resolve this issue. Can someone assist me?

```
modules/nosql/manager.go:14:2: reading github.com/redis/go-redis/go.mod at revision v9.5.3: unknown revision v9.5.3
```

[go-redis](https://github.com/redis/go-redis/releases)

### Gitea Version

1.22.1

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

Arch Linux

### How are you running Gitea?

Through docker

### Database

SQLite

**Comment by techknowlogick** [comment]
Oh weird. It did exist, I guess they must've deleted it. I can find evidence of it at https://github.com/redis/go-redis/issues/3010
I guess the nightly will start to fail soon too. I can create a PR for this and send it to main and our 1.22 release branch so builds can start again

**Comment by SSP6904** [comment]
Glad everyone fixed it for me. Thank you! 🙂
