### ISSUE TITLE
GSAP incompatible with MIT license, that is included in gitea binaries

### ISSUE THREAD

**Issue by mahlzahn** [go-gitea/gitea#31660]
### Description

[GSAP](https://github.com/go-gitea/gitea/blob/main/package-lock.json#L7531) is included as dependency to vue-bar-graph and has a non-free license.

See https://github.com/lafriks/vue-bar-graph/issues/14 and https://codeberg.org/forgejo/discussions/issues/193.

### Gitea Version

*

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

*

### Database

None

**Comment by techknowlogick** [comment]
Thanks again for reporting this, and mentioning it in chat. Looks like the library is only use for one function call: https://github.com/lafriks/vue-bar-graph/blob/6b64270871f43ae8500dbecbcbb5e378ef984574/src/components/VueBarGraph.vue#L294-L297 a temporary workaround could be to remove the animation, and then look at a longer term fix.

**Comment by techknowlogick** [comment]
@lafriks if I were to send a PR to your repo with that update, would you be able to cut a new release of it?

**Comment by lafriks** [comment]
> @lafriks if I were to send a PR to your repo with that update, would you be able to cut a new release of it?

@techknowlogick sure

**Comment by techknowlogick** [comment]
I have a PR now open https://github.com/lafriks/vue-bar-graph/pull/15 which removes gsap entirely.

**Comment by delvh** [comment]
Not closed yet, it is only merged into the dependency, not Gitea yet

**Comment by lafriks** [comment]
vue-bar-graph v2.1.0 has been published

**Comment by lunny** [comment]
Closed by #31705 and released in 1.22.2
