### ISSUE TITLE
PR Files changed view:  "Filter by commit" Dropdown not visible after clicking the button

### ISSUE THREAD

**Issue by sebastian-sauer** [go-gitea/gitea#31673]
### Description

The  "Filter by commit" dropdown on the PR files changed view will not be shown if you click on the button. 

The div gets the visible class when clicking the button but this does not show the dropdown. (display:none is still used from .dropdown class) 

Just tested this on demo.gitea.com:

https://demo.gitea.com/TEST_CODEOWNERS/gitea/pulls/1/files and then click on the commits button.

### Gitea Version

1.22.1

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

Gitea binary, demo.gitea.com

### Database

None

**Comment by yp05327** [comment]
I'm sorry, What is `Commits dropdown`? Do you mean this?
![image](https://github.com/user-attachments/assets/25ed0364-0ced-46f2-8613-4b32e81ccc70)
Or can you provide some screenshots?

**Comment by sebastian-sauer** [comment]
Yes - exactly. The "Filter by commit" dropdown. (i've updated the description, too)

**Comment by sebastian-sauer** [comment]
Caused by the change in https://github.com/go-gitea/gitea/pull/31281 (commit https://github.com/go-gitea/gitea/pull/31281/commits/482fee26dddfae75091809cf5522f708e89a4841)

The transition class has been removed. When adding the class, the dropdown will be visible.

@wxiaoguang as i don't know the reason behind the change i'm not sure if readding the transition class would break anything. Any thoughts on this?

**Comment by wxiaoguang** [comment]
Actually it  was an abuse of dropdown. The dropdown classes (like "transition visible") should be managed by the Fomantic UI JS, but not by Vue. Fomantic UI doesn't work directly with Vue.

**Comment by wxiaoguang** [comment]
->  Fix "Filter by commit" Dropdown #31695
