### ISSUE TITLE
Login form not password manager friendly

### ISSUE THREAD

**Issue by KN4CK3R** [go-gitea/gitea#31686]
### Description

Since #31530 the login form can't be used with external password managers (or simply behaviour driven users) which type `{username}[TAB]{password}[ENTER]` because the `Forgot password?` label gets the focus after pressing the tab key.

### Screenshots

![grafik](https://github.com/user-attachments/assets/34b1d38b-d259-4af2-a841-885eb8b7b487)

**Comment by silverwind** [comment]
Likely add `tabindex="-1"` to it.

**Comment by silverwind** [comment]
https://github.com/go-gitea/gitea/pull/31689

**Comment by silverwind** [comment]
> Why not move the forgot password? below the password entry?

Imho it looks better the way it is and others like GitHub and IMDB do agree on this design as well.
