### ISSUE TITLE
Internal Server Error accessing urls on try.gitea.io

### ISSUE THREAD

**Issue by strk** [go-gitea/gitea#3170]
- Gitea version (or commit ref): 9f033bf
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes, https://try.gitea.io/user/login?redirect_to=/gitea/gitea/issues/10

## Description

Clicked on "login" from https://try.gitea.io/gitea/gitea/issues/10, selected OpenID,
entered my URI, got redirected to my OpenID provider and back to get a 500 internal server error.

Upon trying again right now it worked, so the only useful information here would be in the server logs, if you keep them.

**Comment by strk** [comment]
Actually the `Internal Server Error` still occurs by just visiting this URL:
https://try.gitea.io/gitea/gitea/issues/10#issuecomment-1600

**Comment by strk** [comment]
And no need for the anchor of course, so just https://try.gitea.io/gitea/gitea/issues/10

**Comment by strk** [comment]
this ticket may have nothing to do with OpenID, anyway the ticket is visible from an anonymous window, only fails with 500 when I'm authenticated

**Comment by strk** [comment]
I was just hit again by the same issue, this time visiting https://try.gitea.io/gitea/gitea/pulls/5
this time as of ae9cc8f -- can anyone try to reproduce it or at least look at the logs ?

**Comment by strk** [comment]
https://try.gitea.io/gitea/gitea/issues/10 is also still triggering it for me

**Comment by strk** [comment]
@lunny did you succeed in reading the server logs about this ? And/or could you reproduce it ?
(I'm not sure if the chat bridge is still working, and I don't have access to discord)

**Comment by tboerger** [comment]
Should be related to the openid auth, with my regular user it works fine

**Comment by strk** [comment]
Can you extract anyting meaningful from the logs about this ? I don't see how authentication method should affect visiting an issue or pull request. Also my user is non-admin, can you try with a non-admin user ? There might also be other things which are different for me, maybe I'm a partecipant in those issues...

**Comment by strk** [comment]
I've just tried logging out and logging-in again, this time via GitHub. The problem persists, I still get a 500 visiting any issue of gitea/gitea

**Comment by lunny** [comment]
Still cannot reproduce

**Comment by lafriks** [comment]
@lunny I can reproduce that when logged in with strk user on try.gitea.io

**Comment by strk** [comment]
Next obstacle seems to be that @lunny is unable to read the logs of try.gitea.io -- can anyone else access those logs ? Or I'd file another issue just for that, as it seems very important to me to be able to read logs of a `try` server, often used to showcase bugs...

**Comment by lunny** [comment]
@strk is this still a problem?

**Comment by strk** [comment]
The URL is now a 404 so I've no idea if the problem still exists

**Comment by lunny** [comment]
The repo has been recreated so that that issue is lost.
