### ISSUE TITLE
old TLS version is not supported in SMTP auth method 

### ISSUE THREAD

**Issue by 6769** [go-gitea/gitea#31701]
### Description

Steps:
1. add a new SMTP auth method,  SMTP server which is using TLS1.0 and support the STARTTLS extension: https://docs.gitea.com/usage/authentication#smtp-simple-mail-transfer-protocol ;
2. add a normal user login with SMTP auth;
3. login will error 500

When the remote SMTP server is using the outdated TLS version (1.0-1.1), 
golang `crypto/tls` package using default [`Config`](https://pkg.go.dev/crypto/tls#Config) will reject to establish tls connection with remote server, and result in the login method failure.

log output:
```
...ers/web/auth/auth.go:249:SignInPost() [E] UserSignIn: failed to start StartTLS: remote error: tls: handshake failure
```

code [line](https://github.com/go-gitea/gitea/blob/main/services/auth/source/smtp/auth.go#L60) patch:
```
func Authenticate(a smtp.Auth, source *Source) error {
        tlsConfig := &tls.Config{
                InsecureSkipVerify: source.SkipVerify,
                ServerName:         source.Host,
+               MinVersion: tls.VersionTLS10,       //  By default, TLS 1.2 is currently used as the minimum.
        }
```

### Gitea Version

1.22.1

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

Ubuntu 18.04.6 LTS

### How are you running Gitea?

download precompiled binary file and run

### Database

SQLite

**Comment by levicki** [comment]
> When the remote SMTP server is using the outdated TLS version (1.0-1.1),
golang crypto/tls package using default [Config](https://pkg.go.dev/crypto/tls#Config) will reject to establish tls connection with remote server, and result in the login method failure.

As it well should.

Anything lower than TLS 1.2 should not be used today.

You should really upgrade that server to TLS 1.2 instead of asking devs to make less secure default configuration for everyone.

**Comment by silverwind** [comment]
The minimum TLS version is a limitation of golang, not us. Same issue as https://github.com/go-gitea/gitea/issues/31228 basically. If you really have to workaround, you can try adding the `GODEBUG="tlsrsakex=1"` environment variable, but that will be going away in a future golang version.
