### ISSUE TITLE
Tables with large images cause overflow in issue templates

### ISSUE THREAD

**Issue by bartvdbraak** [go-gitea/gitea#31709]
### Description

1. Create an issue using an issue template, e.g. https://demo.gitea.com/bartvdbraak/blender/issues/new?template=.gitea%2fissue_template%2ftodo.yaml
2. Embed an tables with large images in their cells, e.g.
```markdown
|   |   |   |   |   |
|---|---|---|---|---|
| ![image.png](https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Logo_Blender.svg/2560px-Logo_Blender.svg.png)  |   |   |   | ![image.png](https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Logo_Blender.svg/2560px-Logo_Blender.svg.png)  |
```
3. Look at preview overflowing

### Screenshots

![Screenshot_20240726_182023](https://github.com/user-attachments/assets/58e1f24a-cb5a-4038-8b35-d120e65ff46d)

### Gitea Version

Version: 1.23.0+dev-339-gb4ccef3dee

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

Linux

### Browser Version

Firefox 127.0 (64-bit)

**Comment by silverwind** [comment]
Could someone post a reproduction to https://demo.gitea.com/?
