### ISSUE TITLE
Weblate Alert: Repository outdated

### ISSUE THREAD

**Issue by ParsaNobahari** [go-gitea/gitea#31713]
### Feature Description

> "The VCS repository is not up to date with the upstream one. Please merge changes manually or set up hooks to automate this."
> Appeared 10 days ago, last seen 14 hours ago

you can easily follow this for your repo and it doesn't take more than a minute to setup: https://docs.weblate.org/en/latest/admin/continuous.html#automatically-receiving-changes-from-github

It automates receiving weblate changes, hassle-free and integrated with github.

note: only the project owner has access to apply this.

### Screenshots

![Screenshot from 2024-07-27 20-02-58](https://github.com/user-attachments/assets/2ac9bd9b-af9d-4c3f-a9b9-4b16b34219fb)

**Comment by wolfogre** [comment]
Sorry, I'm confused. Is it an ad for weblate or what? I don't get your proposal since it [already supports](https://docs.weblate.org/en/latest/admin/continuous.html#gitea-setup) Gitea. Or are you suggesting Gitea to use weblate for i18n?

**Comment by delvh** [comment]
I think I may be partially responsible for that as well, I got access to hosted weblate once to try out if it is worth switching to (https://hosted.weblate.org/projects/gitea/).
However, I never updated it past my initial test.
By the way, the only thing holding us back to migrating to weblate at this point is my non-knowledge of NixOS on how to deploy it there.
If we want to use it, we'll need our own Weblate.

**Comment by ParsaNobahari** [comment]
> Sorry, I'm confused. Is it an ad for weblate or what? I don't get your proposal since it [already supports](https://docs.weblate.org/en/latest/admin/continuous.html#gitea-setup) Gitea. Or are you suggesting Gitea to use weblate for i18n?

There is an adjustment that can be made on this github repository settings to make it convenient to "Automatically receiving changes from GitHub" and it can be done by the project owner or a person/s who have access to it.

Sorry if it seemed like an advertisement. I just wanted to make it to be as elaborate as it could be when writing it down, but obviously, it wasn't. I'm just a volunteer translator for projects on hosted.weblate.org, and I am not affiliated with them.

> I got access to hosted weblate once to try out if it is worth switching to (https://hosted.weblate.org/projects/gitea/).
However, I never updated it past my initial test.

Sorry if I don't correctly understand what you said, but Gitea is taking translations from hosted.weblate.org, right? If it is, you can consider doing what is being suggested by weblate documentation that I linked to to make commits more seamless.

Have a great day.

**Comment by techknowlogick** [comment]
https://crowdin.com/project/gitea is currently what we use for translations (if you'd like to contribute translations there we'd be very appreciative), and (as mentioned above) the hosted weblate was setup to evaluate if it was viable for us to switch to. Sadly while weblate is likely what we will be switching to (no timelines currently), the hosted option doesn't enable the options we need to continue with our existing workflow.
