### ISSUE TITLE
add gitea API specs in openAPI format

### ISSUE THREAD

**Issue by milahu** [go-gitea/gitea#31714]
### Feature Description

https://docs.gitea.com/api/1.22/ says

> Download OpenAPI specification: https://docs.gitea.com/redocusaurus/plugin-redoc-1.yaml

[openapi-python-client](https://github.com/openapi-generators/openapi-python-client) fails to read that yaml file

> Failed to parse OpenAPI document
>
> You may be trying to use a Swagger document; this is not supported by this project.

<details>

```
$ openapi-python-client generate --url https://docs.gitea.com/redocusaurus/plugin-redoc-1.yaml
Error(s) encountered while generating, client was not created

Failed to parse OpenAPI document

You may be trying to use a Swagger document; this is not supported by this project.

215 validation errors for OpenAPI
paths./admin/hooks.post.parameters.0.Parameter.in
  Input should be 'query', 'path', 'header' or 'cookie' [type=enum, input_value='body', input_type=str]
paths./admin/hooks.post.parameters.0.Reference.$ref
  Field required [type=missing, input_value={'name': 'body', 'in': 'b...ions/CreateHookOption'}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing
paths./admin/hooks/{id}.patch.parameters.1.Parameter.in
  Input should be 'query', 'path', 'header' or 'cookie' [type=enum, input_value='body', input_type=str]
...
```

</details>

but it works with [swagger-codegen](https://github.com/swagger-api/swagger-codegen)

```
swagger-codegen generate \
  -i https://docs.gitea.com/redocusaurus/plugin-redoc-1.yaml \
  -l python \
  -o gitea-client-python \
  -DpackageName=gitea_client
```

result: [gitea-client-python](https://github.com/milahu/gitea-client-python)

so ...

either reword https://docs.gitea.com/api/1.22/

```diff
-  Download OpenAPI specification
+  Download Swagger API specification
```

or provide gitea API specs in openAPI format as `gitea-api.yaml`

**Comment by lunny** [comment]
Hi, please send this issue to https://gitea.com/gitea/docs because docs have been splitted as a standalone repository.

**Comment by milahu** [comment]
moved to https://gitea.com/gitea/docs/issues/37
