### ISSUE TITLE
Branch rename does not update the tracked branch in pull requests

### ISSUE THREAD

**Issue by skarndev** [go-gitea/gitea#31716]
### Description

If you rename a remote branch through the Gitea UI, a pull request of this branch does not have its "pull from" branch renamed automatically. As a result, the PR becomes stale and no loger receives updates.

Maually altering the pull_request table record of this PR in the Gitea DB  is the current workaround to revive the stale pull request.

### Gitea Version

1.22.1

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

Direct installation, not containerized

### Database

PostgreSQL

**Comment by emrebdr** [comment]
I tested on my local and I see that If you change the name of a branch through Gitea UI that has a pull request, the pull request is getting broken. But I am not sure it is intended situation or not 🤔 

@lunny I wonder if this is intended?
