### ISSUE TITLE
Repository filter on Issues tab missing

### ISSUE THREAD

**Issue by SokolovskiR** [go-gitea/gitea#31723]
### Description

"Filter by repo" filter is missing in the Issues section. It was present in v 1.21.4

### Screenshots

<img width="454" alt="Screenshot 2024-07-29 at 14 15 52" src="https://github.com/user-attachments/assets/a0dbfe87-e563-43ec-b8b4-3828535b9fa4">
<img width="544" alt="Screenshot 2024-07-29 at 14 16 42" src="https://github.com/user-attachments/assets/4a44eaf3-55e3-4a72-9e87-a7e34a485970">

### Gitea Version

1.22.1

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

MacOS Sonoma 14.5

### Browser Version

Chrome 126.0.6478.185 (Official Build) (arm64), Safari 17.5 (19618.2.12.11.6)

**Comment by kemzeb** [comment]
This was removed in v1.22.0, specifically in https://github.com/go-gitea/gitea/pull/28304, due to performance and UX problems in the original implementation. There are plans to reimplement it and is being tracked in https://github.com/go-gitea/gitea/issues/31578.

**Comment by kemzeb** [comment]
Going to close this since it's a duplicate.
