### ISSUE TITLE
Deleting a User should redirect to /admin/users on success

### ISSUE THREAD

**Issue by lukewatts** [go-gitea/gitea#3172]
- Gitea version (or commit ref): 1.3.0
- Git version: 2.13
- Operating system: Win10
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x ] Not relevant
- Log gist:

## Description

When deleting a user in the following workflow `Admin Panel > Users tab > Edit > Delete User` the screen comes up asking to confirm the action. Then the overlay screen says it has successfully deleted the user. However the screen page remains on /admin/users/:id when the overlay fades out.

I feel it would be much better if an automatic redirect happened instead bringing you back to view all users at this point and display a flash message

**Comment by lunny** [comment]
We tested it on Chrome macOS. It redirected to `/admin/users/` after I deleted a user. Which browser are you using and any error on console?

**Comment by lukewatts** [comment]
I'm using chrome. Didn't notice any errors either.




Get Outlook for Android







On Tue, Dec 12, 2017 at 2:59 PM +0000, "Lunny Xiao" <notifications@github.com> wrote:












We tested it on Chrome macOS. It redirected to /admin/users/ after I deleted a user. Which browser are you using and any error on console?

**Comment by lafriks** [comment]
I can not seem to reproduce this, seems to be working just fine for me
