### ISSUE TITLE
User Settings UI [Gitea 1.3.1]

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#3173]
- Gitea version (or commit ref): 1.3.1
- Git version: Not sure (3rd party service - Teknik.io)
- Operating system: Windows Server 2016 Datacenter
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist: N/A

## Description

My provider recently updated to Gitea 1.3.1 and I noticed that the user settings UI is still the old one, the element floating is broken and "ssh_keys" (not translated) and "Two-Factor Authentication" lead to a 404.
Are these fixed in Gitea 9f033bf or was there a problem in the update procedure?

## Screenshots

Teknik 1.3.1 Settings

![teknik-settings](https://user-images.githubusercontent.com/9649385/33889320-a35aa218-df47-11e7-9d83-1fb0018ae444.png)

Gitea 9f033bf Settings

![gitea-settings](https://user-images.githubusercontent.com/9649385/33889327-a94e395a-df47-11e7-9a3e-72f5361552fb.png)

**Comment by lunny** [comment]
@megadr01d this is because your provider had added a customize template, they should upgrade the customize template.

**Comment by ghost** [comment]
> your provider had added a customize template

You're quite right, he did. Thanks for the pointer and quick reply.
I'm posting the issue [there](https://git.teknik.io/Teknikode/Teknik/issues/76), closing.
