### ISSUE TITLE
Gitea can not start with version 1.22.2

### ISSUE THREAD

**Issue by iluobei** [go-gitea/gitea#31737]
### Description

2024/07/30 08:56:46 ...ates/htmlrenderer.go:140:wrapTmplErrMsg() [F] Gitea can't run with template errors: template error: custom:repo_list:6 : function "repoAvatar" not defined

### Gitea Version

1.22.2

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

personal use

### Database

MySQL/MariaDB

**Comment by wolfogre** [comment]
Hmm, where did you get v1.22.2? Since I checked that the latest version is v1.22.1 for now.
