### ISSUE TITLE
gitea isn't using specified port and crashing

### ISSUE THREAD

**Issue by x-o-i-o-x** [go-gitea/gitea#31747]
### Description

Setting gitea up worked just fine. But when starting gitea with systemd, it fails with exit-code 1. It seems that gitea isn't using the port specified in the app.ini. I already looked at other issues like [this](https://github.com/go-gitea/gitea/issues/4257) one but all of them wheren't helpful.
Hope I mentioned everything and thanks for your help!

### Gitea Version

gitea-1.22.1-linux-amd64

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/x-o-i-o-x/f59383308b9b9e003161097d495962c7.js

### Git Version

2.39.2

### Operating System

Debian GNU/Linux 12 (bookworm) x86_64

### How are you running Gitea?

I installed gitea from the binary with this tutorial: https://www.apalrd.net/posts/2023/ultimate_gitea/
I execute it via systemd (Debian)

### Database

SQLite

**Comment by wxiaoguang** [comment]
The log says:

```
[F] Failed to start port redirection: listen tcp 0.0.0.0:80: bind: address already in use
```

So you already have other server applications running on the same port as Gitea.

**Comment by x-o-i-o-x** [comment]
Worked. Thank you!
