### ISSUE TITLE
Cannot add user to organisation with 1.3.x

### ISSUE THREAD

**Issue by moritz-h** [go-gitea/gitea#3174]
- Gitea version (or commit ref): 1.3.x
- Git version: 2.7.4
- Operating system: Ubuntu 16.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL) https://try.gitea.io/test-org2
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
Cannot add User to Organisation with Version 1.3.x The invite button is gone. Tried with fresh installation.
1.2.3 => woking
1.3.0 => no invite button
1.3.1 => no invite button

The screenshots show the organisation main page, but also on the members page there is no invite option: https://try.gitea.io/org/test-org2/members 

## Screenshots
This is version 1.2.3 There is a invite button
![gitea-add-org-1-2](https://user-images.githubusercontent.com/7849248/33890722-5865c334-df54-11e7-8a42-a0ee267fcb88.png)

This is https://try.gitea.io but same with 1.3.0 and 1.3.1
![gitea-add-org-1-3](https://user-images.githubusercontent.com/7849248/33890723-588b872c-df54-11e7-926b-b2751a753410.png)

**Comment by lunny** [comment]
Yes, we have removed this button so that all the members of an organization must be on at least one team.  You can add a member on teams setting.

**Comment by locness3** [comment]
I'm ok with requiring users to be on teams, but this implementation is counterintuitive.
