### ISSUE TITLE
Incorrect time ago (again)

### ISSUE THREAD

**Issue by Gr3q** [go-gitea/gitea#31746]
### Description

See https://github.com/go-gitea/gitea/issues/28747 and https://github.com/github/relative-time-element/issues/288

### Gitea Version

1.22.1

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![20240731_17h05m54s_grim](https://github.com/user-attachments/assets/7992b528-a3ce-4b7b-9914-b5570655e621)

### Operating System

Ubuntu 20.04

### How are you running Gitea?

Docker

### Database

MSSQL

**Comment by silverwind** [comment]
Fixed with https://github.com/go-gitea/gitea/pull/31750.
