### ISSUE TITLE
Gitea review tool: Need to add checkbox or some more reactions to Gitea PR review comments

### ISSUE THREAD

**Issue by ohohlova** [go-gitea/gitea#31767]
### Feature Description

Gitea review tool: Need to add checkbox or some more reactions to Gitea Pull Request review comments

It seems the Gitea review tool is missing some checkbox or other mechanism to allow the developer to mark comments as done/fixed. Of cource I can reply to each comment by word "ready" or "done", but it would be better to have more easy and convenient way to do it. Also I can add reactions to the comments, but currently Gitea has very limited set of reactions and I cound not found something suitable for "Ok, It's done".

Is there some way to add my custom reactions or checkbox to each comment?

### Screenshots

<img width="335" alt="Screenshot 2024-08-02 at 20 37 24" src="https://github.com/user-attachments/assets/755ce48b-b65e-4961-bfba-38fc1c2d111a">

**Comment by lunny** [comment]
![图片](https://github.com/user-attachments/assets/33a973db-c1bd-426c-9247-73bc10a0d683)
There is a button `Resolve conversation`. Is that what you want?

**Comment by ohohlova** [comment]
> ![图片](https://private-user-images.githubusercontent.com/81045/354687198-33a973db-c1bd-426c-9247-73bc10a0d683.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2MjI5MjksIm5iZiI6MTcyMjYyMjYyOSwicGF0aCI6Ii84MTA0NS8zNTQ2ODcxOTgtMzNhOTczZGItYzFiZC00MjZjLTkyNDctNzNiYzEwYTBkNjgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAyVDE4MTcwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3YzY5YmE3NjhjNDhmY2I1ZDc4ZGI1NWEzMmVlMDU5YmU0ZGMwNGRhZDFhYWMwOWZjZDM5ODcyMDQ0NGFmYzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DKxs6BSfP9LlLi9ND89yP4RRLCE3nsRejZGwKgPGHlk) There is a button `Resolve conversation`. Is that what you want?

No, I know about this button, but I think that comment should be marked as resolved by the author of the comment when he has already ensured and agree that it is fixed correctly. I propose to add some tool to mark the comment as fixed so that author of the comment can see it and then he will review it and mark as resolved.

**Comment by sebastian-sauer** [comment]
I think you can add reactions like a checkbox via configuration: ui.REACTIONS

https://github.com/go-gitea/gitea/blob/main/custom%2Fconf%2Fapp.example.ini#L1241-L1244

**Comment by ohohlova** [comment]
> I think you can add reactions like a checkbox via configuration: ui.REACTIONS
> 
> https://github.com/go-gitea/gitea/blob/main/custom%2Fconf%2Fapp.example.ini#L1241-L1244

Thanks. It seems to be a solution. But is it possible for users to do it? Or I have to contact some administrator to add more reactions?

This says
“For custom reactions, add a tightly cropped square image to public/assets/img/emoji/reaction_name.png”
Where can I do this?

**Comment by lunny** [comment]
> > I think you can add reactions like a checkbox via configuration: ui.REACTIONS
> > https://github.com/go-gitea/gitea/blob/main/custom%2Fconf%2Fapp.example.ini#L1241-L1244
> 
> Thanks. It seems to be a solution. But is it possible for users to do it? Or I have to contact some administrator to add more reactions?
> 
> This says “For custom reactions, add a tightly cropped square image to public/assets/img/emoji/reaction_name.png”
> 
> Where can I do this?

`Custom reactions` can be added by that Gitea instance maintainer who deployed the Gitea. And I don't think Gitea should support user-defined custom reactions.

**Comment by ohohlova** [comment]
Understood. Thanks.
