### ISSUE TITLE
scoped-access-token-mount not mounted anymore

### ISSUE THREAD

**Issue by meruiden** [go-gitea/gitea#31771]
### Description

Generating application tokens is currently broken on main because scoped-access-token-mount doesn't get properly mounted anymore. So i'm unable to select permissions

### Gitea Version

1.23.0+dev-377-g13439f119e built with GNU Make 4.4.1, go1.22.5 : bindata, timetzdata, sqlite, sqlite_unlock_notify

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![image](https://github.com/user-attachments/assets/9022bd57-8081-4209-b1d1-b1305c3eb4ca)

### Operating System

Docker on Ubuntu server

### How are you running Gitea?

Docker compose

```yaml
gitea:
    image: gitea/gitea:nightly

``` 

### Database

MySQL/MariaDB

**Comment by sillyguodong** [comment]
I came across the following warning:
![image](https://github.com/user-attachments/assets/0fd5ba62-ad73-486a-a603-7c713a21237a)

I found this comment: https://github.com/fengyuanchen/vue-feather/issues/8#issuecomment-1566422206
it works for me, but I am not sure if this is the correct solution.

**Comment by lunny** [comment]
> I came across the following warning: ![image](https://private-user-images.githubusercontent.com/33891828/357005040-0fd5ba62-ad73-486a-a603-7c713a21237a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0ODgwOTMsIm5iZiI6MTcyMzQ4Nzc5MywicGF0aCI6Ii8zMzg5MTgyOC8zNTcwMDUwNDAtMGZkNWJhNjItYWQ3My00ODZhLWE2MDMtN2M3MTNhMjEyMzdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEyVDE4MzYzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzYjllNzEzNWJhMjRjOGY0N2RkMGJlYWUyMWIwNWZhOTI5Y2Y4YjI4MDliYjY4Y2EwMmJmN2I5NWY4YTFhZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Wm8PaV4Cxfxm1mAQG-dFHwDXFa30BKJ2qTrG70hayX8)
> 
> I found this comment: [fengyuanchen/vue-feather#8 (comment)](https://github.com/fengyuanchen/vue-feather/issues/8#issuecomment-1566422206) it works for me, but I am not sure if this is the correct solution.

Looks like it's a better solution for me.
