### ISSUE TITLE
Edit in web and commit, the author are all username@noreply.gitea.com

### ISSUE THREAD

**Issue by yp05327** [go-gitea/gitea#31787]
### Description

In web ui, they seem no difference.
![image](https://github.com/user-attachments/assets/b4ea09f8-f87f-4918-8b40-5f0c2c5705b7)

But after you clone them, and see the git log, you will see that the authors are a bit strange.
![image](https://github.com/user-attachments/assets/4f6b8168-0ec6-4956-9cb1-d6dcfbfdceac)

### Gitea Version

1.23.0+dev-345

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

gitea.com

### Database

None

**Comment by wolfogre** [comment]
I think it's by design

<img width="1104" alt="image" src="https://github.com/user-attachments/assets/3393baba-f292-4e04-8e1f-8d5b483240e8">
