### ISSUE TITLE
Failed to add ssh key into repo

### ISSUE THREAD

**Issue by CircleCurve** [go-gitea/gitea#3178]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

I have created a git repo and try to adopt ssh key for authentication. After added ssh key into Deploy keys, it redirect to the error page that only contain 

template: repo/settings/deploy_keys:34:65: executing "repo/settings/deploy_keys" at <.CreatedUnix.FormatS...>: can't evaluate field FormatShort in type int64

This issue appear both my local docker environment (latest) and https://try.gitea.io
...

## Screenshots

![screen shot 2017-12-13 at 4 56 05 pm](https://user-images.githubusercontent.com/8490834/33930108-cf389482-e026-11e7-9760-0968934b751e.png)

![screen shot 2017-12-13 at 4 56 52 pm](https://user-images.githubusercontent.com/8490834/33930156-ec37fd20-e026-11e7-9d5b-4dca3b46bfe9.png)

![screen shot 2017-12-13 at 4 57 07 pm](https://user-images.githubusercontent.com/8490834/33930164-f2d4cffa-e026-11e7-85b8-5a9d55194b18.png)

**Comment by lafriks** [comment]
What version are you using?

**Comment by lafriks** [comment]
seems to be also related to #3142

**Comment by lunny** [comment]
should be fixed by #3146.

**Comment by CircleCurve** [comment]
I'm using the most latest version of gitea in docker 
![default](https://user-images.githubusercontent.com/8490834/33931779-08bf9b6a-e02c-11e7-9c0d-eacfc38d3230.png)

**Comment by lunny** [comment]
@CircleCurve  #3146 has not been reviewed and merged.

**Comment by CircleCurve** [comment]
@lunny Ok. Thanks you to solve my problem. I will go to use http instead of ssh at this time for development.
