### ISSUE TITLE
Permissions list missed when creating access token

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#31786]
### Description

When creating an access token, click permission, no options are listed any more.

![图片](https://github.com/user-attachments/assets/1bcdb939-6e6b-4474-afce-f832ec454f6e)

### Gitea Version

df7f1c2ead

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

localhost dev env

### Database

None

**Comment by wxiaoguang** [comment]
* #31771
* https://github.com/go-gitea/gitea/pull/31705#issuecomment-2266720098
