### ISSUE TITLE
Unable to upgrade from 1.17.4 to 1.22

### ISSUE THREAD

**Issue by amirad1** [go-gitea/gitea#31783]
### Description

**I am trying to migrate from gitea 1.17.4 to 1.22 but when I follow the instruction written in the docs, I get error in my repositories after update. 
Literally the database of gitea has experienced huge change from 1.17.4 to 1.22 and some new added tables can bee seen, 
what should I do with database changes ?**

### Gitea Version

1.17.4

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

ubuntu 24.04 and centos 7

### How are you running Gitea?

Binary on linux 

### Database

MySQL/MariaDB

**Comment by techknowlogick** [comment]
Hi. Thank you for opening this ticket. What errors or logs are you seeing?

**Comment by amirad1** [comment]
I see lots of errors especially in repositories 
When I open the repositories, I encounter 500 error and in the logs I can see are including this message 

```
2024/08/07 10:27:11 ...ers/web/repo/view.go:1050:renderHomeCode() [E] FindRecentlyPushedNewBranches: branch does not exist [repo_id: 9 name: dev]
2024/08/07 10:27:11 ...eb/routing/logger.go:102:func1() [I] router: completed GET /reponame for 192.168.30.56:63804, 500 Internal Server Error in 252.7ms @ repo/view.go:774
```

**Comment by Remmert-PBE** [comment]
Looks like this issue: https://github.com/go-gitea/gitea/issues/31163

**Comment by amirad1** [comment]
It seems in the 1.22.1 version, the 500 error is fixed but I still get the error log ? should I ignore it or not ?

**Comment by eeyrjmr** [comment]
its never a good idea to ignore an [E]
In the admin panel there is a sync branch action
![2024-08-10_11-08-1723284359](https://github.com/user-attachments/assets/2a7f0b3b-cd36-49cd-b7ab-dcd502a72b0b)

**Comment by amirad1** [comment]
thanks it worked by running sync branch action and upgrading to 1.22.1
