### ISSUE TITLE
LFS Lock list should display lock owner instead of repository owner

### ISSUE THREAD

**Issue by NateScarlet** [go-gitea/gitea#31784]
### Description

`$.Owner` here seems to be repository owner instead of LFS Lock owner
https://github.com/go-gitea/gitea/blob/94cca8846e7d62c8a295d70c8199d706dfa60e5c/templates/repo/settings/lfs_locks.tmpl#L33-L36

can not reproduce on demo site, because lfs not enabled

### Screenshots

![image](https://github.com/user-attachments/assets/40e3a79b-ed14-4ccd-b09f-9b76a7072919)

### Gitea Version

1.22.1

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

win11 22H2

### Browser Version

chrome 127

**Comment by wolfogre** [comment]
Confirmed. I'm going to fix it if no one is working on this.
