### ISSUE TITLE
API Endpoint to add Pull Request Review Comments

### ISSUE THREAD

**Issue by imgurbot12** [go-gitea/gitea#31782]
### Feature Description

Hello! Since gitea lacks support for [error annotations](https://docs.gitea.com/usage/actions/comparison#create-an-error-annotation) I am writing a small service that scans the output from a gitea actions command and manually posts a review attached to a service account linked to the associated pull-request via gitea's api.

However, while there is an [api to list existing review comments](https://demo.gitea.com/api/swagger#/repository/repoGetPullReviewComments) there is not one to add comments to a specified line/column/etc... to attach them as part of the review.

I would like to add a `POST /api/v1/repos/{owner}/{repo}/pulls/{index}/reviews/{id}/comments` endpoint to fix this.
I'm open to working on this myself but I'm not sure where to start and could use some direction.

Thanks!

**Comment by imgurbot12** [comment]
After further review it turns out you [CAN create comments](https://demo.gitea.com/api/swagger#/repository/repoCreatePullReview) during the review creation which I missed until i took a dive through the source code in an effort to start on a pull-request.

Apologies for the confusion.

**Comment by imgurbot12** [comment]
if anyone cares. I wrote an action designed specifically for gitea to automatically post a pr review based on github annotations using those api-calls: https://github.com/imgurbot12/prbot

**Comment by techknowlogick** [comment]
@imgurbot12 very cool!
