### ISSUE TITLE
Repository expolore pagination problem

### ISSUE THREAD

**Issue by hametan** [go-gitea/gitea#31807]
### Description

设置了过滤条件，如：非镜像，翻页未带上过滤参数。

### Gitea Version

1.22.1

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

打开 https://demo.gitea.com/explore/repos  点击过滤 ，点击非镜像，点第二页。

### Database

PostgreSQL

**Comment by lunny** [comment]
I don't it's a bug. When filters changed, you should visit from page 1 again.

**Comment by yp05327** [comment]
> I don't it's a bug. When filters changed, you should visit from page 1 again.

No. I can confirm this issue.
First, visit the first page, and change the filter.
Then click page 2, the filter is missing.

**Comment by yp05327** [comment]
#29231 forgot add these newly added params to pager
