### ISSUE TITLE
500 when viewing a repo without a `master` branch

### ISSUE THREAD

**Issue by yatesco** [go-gitea/gitea#3181]
- Gitea version (or commit ref): gitea/gitea:latest pulled yesterday
- Git version:git version 2.13.6 (Apple Git-96)
- Operating system: macos
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:

## Description
`gitea` throws a `500` if you view a repository without a master branch

To reproduce:
 - install a fresh gitea
 - create a new repo
 - `git push -u origin some-other-branch`
 - then view the repo in gitea and it throws a 500

P.S> - Loving `gitea` - thanks for everyone's hard work!

**Comment by lunny** [comment]
Because <repo>/HEAD is `ref: refs/heads/master` but there is no `master` branch.

**Comment by lunny** [comment]
resolved by #3240
