### ISSUE TITLE
Database conversion is a nightmare

### ISSUE THREAD

**Issue by sbourdeauducq** [go-gitea/gitea#31820]
### Description

The documentation should indicate clearly that the database type chosen during the first gitea installation is basically permanent.

Trying to switch from sqlite to psql is the complete opposite of "painless" and is a constant stream of bugs and problems; in fact it is one of the most frustrating sysadmin tasks I have ever attempted. There should be a warning about this, saying that if you expect your instance to grow, you need to select a scalable database server in the first place, or expect hell.

There is no official guide for converting database, and none of the unofficial ones work. Psql cannot read a SQL dump produced by sqlite because of course none of the database vendors could agree on a standard format. pgloader is crippled with bugs and completely unreliable, crashes with a "KABOOM!" message and an obscure error message indicating some data corruption. Using ``gitea --config /var/lib/gitea/custom/conf/app.ini dump --database postgres`` produces a dump that psql appears - at least on the surface - to be able to read, with the two caveats (1) gitea dump appears to ignore whatever --skip flags you pass to it so on a large instance it'll take ages to produce an archive of tens of gigabytes (2) you need to import the SQL file with ``SET synchronous_commit TO off; \i dump.sql`` otherwise the INSERT statements take forever to execute.

There are various recipes you can find online, e.g. https://forum.gitea.com/t/migrate-from-sqlite-to-postgresql/2269/2, apparently copy-pasting a hundred lines of obscure SQL statements in the hopes that things will work is considered "painless".

And even after you go through all this, you are greeted by this wonderful screen:
![image](https://github.com/user-attachments/assets/a52d0312-2d0a-4bc8-bcff-1d94afd97c99)

At this point I gave up and I'm going to suck up the poor performance of sqlite for another while.

### Gitea Version

1.21.1

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

NixOS package

### Database

None

**Comment by delvh** [comment]
Erm… How is that related to Gitea?
Switching DBs is always hard, no matter what application you are running.
Additionally, Gitea is not supposed to be doing anything there.
The `gitea dump` tool is intended for making backups of your current DB **for the same DB**.
For nothing else.
No one expected it to be able to do cross-DB migrations.

Making the switch easier is the job of other tools.
Gitea simply uses whatever DB you give it, and writes to it expecting the same type of DB. 

I can understand that you are frustrated because of the switch, but still I don't think Gitea is the right place to blame here.
If anyone, blame the missing standards of DBs.

**Comment by eeyrjmr** [comment]
> (2) you need to import the SQL file with SET synchronous_commit TO off; \i dump.sql otherwise the INSERT statements take forever to execute.


https://postgresqlco.nf/doc/en/param/synchronous_commit/

> RECOMMENDATIONS
> If data integrity is **less important** to you than response times (for example, if you are running a social networking application or processing logs) you can turn this off, making your transaction logs asynchronous

you opted to disable an integrity check for an import convenience that can and does expose you for an inconsistent database.

**Comment by KN4CK3R** [comment]
> The `gitea dump` tool is intended for making backups of your current DB **for the same DB**. For nothing else. No one expected it to be able to do cross-DB migrations.

I don't think that's right. We have the `--database` parameter to explicit generate a dump for different database type.

**Comment by eeyrjmr** [comment]
Have you used **gitea doctor** to check and repair any inconsistencies in the database prior to export

**Comment by eeyrjmr** [comment]
> No, but it doesn't seem there were any.
> 
> ```
> [1] Check paths and basic configuration
>  - [I] Configuration File Path:    "/var/lib/gitea/custom/conf/app.ini"
>  - [I] Repository Root Path:       "/var/lib/gitea/repositories"
>  - [I] Data Root Path:             "/var/lib/gitea/data"
>  - [I] Custom File Root Path:      "/var/lib/gitea/custom"
>  - [I] Work directory:             "/var/lib/gitea"
>  - [I] Log Root Path:              "/var/lib/gitea/log"
>  - [I] Static File Root Path:      "/nix/store/5cl1q3a3ng1nh8xr1dzybr8jsn2iyixa-gitea-1.21.11-data"
> OK
> 
> [2] Check Database Version
>  - [I] Expected database version: 280
> OK
> 
> [3] Check if user with wrong type exist
> OK
> 
> [4] Check if OpenSSH authorized_keys file is up-to-date
> OK
> 
> [5] Synchronize repo HEADs
>  - [I] All 201 repos have their HEADs in the correct state
> OK
> 
> All done (checks: 5).
> ```

Doctor can do more checks.
gitea doctor check --all
There is a --fix option to git gitea the ok to fix what it can


The gitea dump to a different database schema will create an SQL dump that *should* be compatible with the target database. There could be bugs with the xorm interface that produces an invalid dump file as it is advise to use the native db dump for backups. 
Databases are not trivial and equally are far from compatible between themselves 

Gitea talks to postgrs via xorm and it is those commands that are dumped but if postgrs needs or does others things internally to keep the database consistent to itself ... This is where the gap will be

**Comment by lunny** [comment]
> Would you like a documentation PR with this procedure, along with a warning that it is poorly tested and it is better to choose the right database during first installation?
> 
> The only thing is the `--skip` flags of `gitea dump` do not seem to have an effect, so there is no simple way to dump the database only, and I'm not familiar with the codebase.

Can you help to send a PR to https://gitea.com/gitea/docs ?
