### ISSUE TITLE
gitea won't start with LFS_START_SERVER = true

### ISSUE THREAD

**Issue by afry23** [go-gitea/gitea#3182]
- Gitea version (or commit ref): 1.14
- Git version: 2.14
- Operating system: FreeBS 11
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ x] Not relevant
- Log gist:

## Description
gitea is running fine but when I add LFS_START_SERVER = true to the app.ini gitea won't start.
I don't see any error message in my log files.
Git lfs is installed and I run git lfs install as root and as git user.
Lfs content path is set (and the path exist with permission for git user)
LFS_CONTENT_PATH = /var/db/gitea/data/lfs

Thx for your help.
Regards,

Andy
...

**Comment by afry23** [comment]
Some further infos:
when I start gitea from the command line as git user with:
gitea web -c /usr/local/etc/gitea/conf/app.ini
The output is:
 [...s/setting/setting.go:706 NewContext()] [E] Error saving generated JWT Secret to custom config: open /usr/local/etc/gitea/conf/app.ini.610373435.tmp: permission denied

LFS_JWT_SECRET is not set in my app.ini.
Did I miss something in the app.ini?

**Comment by lafriks** [comment]
When starting for the first time it needs write rights in that folder to generate LFS secret token. Add directory and app.ini file write rights for git user. After starting gitea you can remove them.

**Comment by afry23** [comment]
Ok, that worked. Thank you.
