### ISSUE TITLE
Git mirroring functionality disrupted post Docker update; sync queue error persists

### ISSUE THREAD

**Issue by bigcat26** [go-gitea/gitea#31827]
### Description

I am currently experiencing an issue with the mirroring functionality of Gitea. It appears that the synchronization feature for mirrored repositories has suddenly stopped working. This issue might have been triggered by a recent Docker container update or possibly when the disk reached full capacity. However, the disk has since been cleaned up to provide ample space, and Gitea is running without any error messages being reported.

**Problem Description**:

- The mirror repositories are not being updated at the scheduled intervals.
- Manually triggering a sync by clicking the sync button in the repository settings results in a log error stating `Unable to push sync request for to the queue for pull mirror repo[363]. Error: already in queue.`
- Restarting the Gitea Docker container does not resolve the issue, and the same error persists upon attempting to sync again.

**Expected Behavior**:

I expect the mirrored repositories to be synchronized at the predefined intervals or when manually initiated without any errors.

**Steps to Reproduce**:

1. Have a mirrored repository set up in Gitea.
2. Wait for the scheduled sync or manually click the sync button in the repository settings.
3. Check the Gitea logs for any errors.

**Gitea doctor output**:

```
[1] Check paths and basic configuration
 - [I] Configuration File Path:    "/data/gitea/conf/app.ini"
 - [I] Repository Root Path:       "/data/git/repositories"
 - [I] Data Root Path:             "/data/gitea"
 - [I] Custom File Root Path:      "/data/gitea"
 - [I] Work directory:             "/data/gitea"
 - [I] Log Root Path:              "/data/gitea/log"
OK

[2] Check Database Version
 - [I] Expected database version: 299
OK

[3] Check if user with wrong type exist
OK

[4] Check if OpenSSH authorized_keys file is up-to-date
OK

[5] Synchronize repo HEADs
 - [I] All 234 repos have their HEADs in the correct state
OK

All done (checks: 5).
```

### Gitea Version

1.22.1

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

docker image: `gitea/gitea:b3de72970178`

### Database

PostgreSQL

**Comment by lunny** [comment]
That means there is already a sync task in the queue and the queue data has been stored in disk.
Maybe you can just wait for a long time and try again?

**Comment by bigcat26** [comment]
> That means there is already a sync task in the queue and the queue data has been stored in disk. Maybe you can just wait for a long time and try again?

My Gitea container has been running for over 20 days without the queue being cleared. It seems likely that a task without a timeout is blocking the entire queue. Is there a way to manually clear this queue, such as by deleting file or database records, to unblock the process?

**Comment by lunny** [comment]
> > That means there is already a sync task in the queue and the queue data has been stored in disk. Maybe you can just wait for a long time and try again?
> 
> My Gitea container has been running for over 20 days without the queue being cleared. It seems likely that a task without a timeout is blocking the entire queue. Is there a way to manually clear this queue, such as by deleting file or database records, to unblock the process?

Yes. Just delete the queue directory after shutdown Gitea server.

**Comment by bigcat26** [comment]
> Yes. Just delete the queue directory after shutdown Gitea server.

It works. Thank you.
