### ISSUE TITLE
 Error when trying to add new google oauth provider via command line: "Command error: auth source is not activated"

### ISSUE THREAD

**Issue by matera-mos** [go-gitea/gitea#31831]
### Description

I'm trying to add new oauth google provider via command line to my gitea installation.
But I'm getting the following error:
``` 
$ gitea admin auth add-oauth --name external-google --provider google --key ${GOOGLE_KEY_PROVIDER} --secret ${GOOGLE_SECRET_PROVIDER}
Command error: auth source is not activated
```
When trying to add a new oauth provider from github this command works correctly.

### Gitea Version

gitea/gitea:1.22.1-rootless

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

git version 2.34.1

### Operating System

Ubuntu 22.04.4 LTS + docker

### How are you running Gitea?

The error was initially identified when using gitea in kubernetes via helm-charts. 
However, during the analysis, I reproduced the error by running gitea in a docker container.

### Database

SQLite

**Comment by yp05327** [comment]
![image](https://github.com/user-attachments/assets/e8adf745-8367-4c51-b133-82153ee3e931)
It seems that the provider name is `gplus`

**Comment by matera-mos** [comment]
Thanks @yp05327 , with this change works for me.

**Comment by lunny** [comment]
Although it's not a bug, but it's better to have a list of all supported oauth provider in the command line.
