### ISSUE TITLE
how set language on app.ini

### ISSUE THREAD

**Issue by bySabi** [go-gitea/gitea#3183]
- Gitea version (or commit ref): 1.3.1
- Git version:
- Operating system: macOS
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [X ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

How I can setup UI Language to English beside browser detected?

**Comment by lunny** [comment]
Remove all other languages except English on app.ini
```
[i18n]
LANGS = en-US,zh-CN,zh-HK,zh-TW,de-DE,fr-FR,nl-NL,lv-LV,ru-RU,ja-JP,es-ES,pt-BR,pl-PL,bg-BG,it-IT,fi-FI,tr-TR,cs-CZ,sr-SP,sv-SE,ko-KR
NAMES = English,简体中文,繁體中文（香港）,繁體中文（台灣）,Deutsch,français,Nederlands,latviešu,русский,日本語,español,português do Brasil,polski,български,italiano,suomi,Türkçe,čeština,српски,svenska,한국어
```

**Comment by bySabi** [comment]
works perflectly!

Thx
