### ISSUE TITLE
Power outage during merge request, causing the main branch to be unavailable and rendering the merge request function ineffective

### ISSUE THREAD

**Issue by Dark-YiFeng** [go-gitea/gitea#31834]
### Description

合并请求时断电，导致commit号存在Gitea时是00000000000000000000000000，导致main分支不可用，点击报错404，合并请求功能也404，动态功能500.

解决方案：删掉该代码库中refs目录下，heads目录下，main文件的错误数据(0000000000000000)，删掉logs目录下的对应错误数据，数据库中的错误数据也删除。

When merging requests, the power was cut off, resulting in the commit number being 00000000000000 in Gitea, causing the main branch to be unavailable. Clicking on it resulted in an error 404, and the merge request function was also 404, while the dynamic function was 500
Solution: Delete the error data (0000000) in the refs directory, heads directory, and main file of the code repository, delete the corresponding error data in the logs directory, and also delete the error data in the database.

### Gitea Version

1.21.0

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

本地部署，内网环境。

Local deployment, internal network environment.

### Database

None

**Comment by yp05327** [comment]
Is this a Gitea side bug? 🤔

**Comment by lunny** [comment]
What did you mean `the commit number being 00000000000000`?

**Comment by yp05327** [comment]
commit's SHA is 00000000000000000?

**Comment by eeyrjmr** [comment]
0000000000000 is reserved by git. I ran into a similar type of corruption a few years ago when I was using bare directories from a NAS (This is why I migrated to gitea)

**Comment by wxiaoguang** [comment]
Power outage could cause any damage to your system: file system, database, documents, etc. If a system is corrupted, you could only recover it by a backup, or drop these broken files.
