### ISSUE TITLE
template: repo/wiki/pages:21:36: executing "repo/wiki/pages" at <.UpdatedUnix>: can't evaluate field UpdatedUnix in type repo.PageMeta

### ISSUE THREAD

**Issue by snelweg** [go-gitea/gitea#3184]
after upgrade to latest gitea-master-linux-amd64, Gitea version 00bfa1d built with: bindata, sqlite

Debian 8.10

Linux xx 2.6.32-042stab125.3 #1 SMP Wed Sep 27 19:27:11 MSK 2017 x86_64 GNU/Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [X ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ X] No
  - [ ] Not relevant
- Log gist:

## Description
after upgrade to latest gitea-master-linux-amd64, Gitea version 00bfa1d built with: bindata, sqlite I can no longer save wiki pages.

...

## Screenshots

![gitea_1](https://user-images.githubusercontent.com/1257901/33941194-fd8d6f84-e011-11e7-912c-f4e653f3e0b2.png)

**Comment by snelweg** [comment]
Switching back to ./gitea-master-linux-amd64.old -v
Gitea version 074f6c1 built with: bindata, sqlite
does not show the error. Everything works as it did before.

**Comment by lunny** [comment]
@snelweg #3175 will fix this issue and will be merged after some minutes.

**Comment by lunny** [comment]
resolved by #3175

**Comment by snelweg** [comment]
I can confirm this is fixed now, thanks!
