### ISSUE TITLE
Config `DISABLE_USERS_PAGE` doesn't work.

### ISSUE THREAD

**Issue by Xu-zn** [go-gitea/gitea#31864]
### Description

When I set `DISABLE_USERS_PAGE` to true in `/etc/data/app.ini` and then restart the container, the `explore` still exists. The configuration is as follows.
```ini
[service.explore]
;;REQUIRE_SIGNIN_VIEW = true
DISABLE_USERS_PAGE = true
```
![image](https://github.com/user-attachments/assets/7bbf9032-7fa6-4962-aaf2-b4928e903389)

I tested other configuration like `[openid]` that both `ENABLE_OPENID_SIGNIN` and `ENABLE_OPENID_SIGNUP` were set to `false`, and that worked. As well, I find `[service.explore]` is not in [app.example.ini](https://github.com/go-gitea/gitea/blob/main/custom/conf/app.example.ini).

### Gitea Version

1.22.1

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

![image](https://github.com/user-attachments/assets/9b1ab7cd-5a1c-46d8-8acf-6847eefc4311)

### Operating System

docker

### How are you running Gitea?

version: "2"

services:
  server:
    image: gitea/gitea:latest-rootless
    restart: always
    volumes:
      - ./data:/var/lib/gitea
      - ./config:/etc/gitea
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "2222:2222"

### Database

SQLite

**Comment by lunny** [comment]
It's only for 1.23. https://docs.gitea.com/next/administration/config-cheat-sheet?_highlight=disable_users_page/next/administration/config-cheat-sheet#service---explore-serviceexplore

**Comment by Xu-zn** [comment]
Ok, I will update the version to 1.23. Thanks a lot.
