### ISSUE TITLE
Internal Error – 500 – when trying to log in with 2FA enabled

### ISSUE THREAD

**Issue by FrostyPenguin** [go-gitea/gitea#3187]
- Gitea version (or commit ref): [master: c06cc74](https://github.com/go-gitea/gitea/commit/c06cc740dea46f3aff58e0eded4208232bb5902d)
- Git version: 2.15.1
- Operating system: GNU (Running on arm64, distribution: Arch Linux ARM)
- Database (use '[x]'):
- [ ] PostgreSQL
- [ ] MySQL
- [ ] MSSQL
- [X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
- [X] Yes (provide example URL): [Sign in page](https://try.gitea.io/user/login?redirect_to=)
- [ ] No
- [ ] Not relevant
- Log gist: [GitHub gist](https://gist.github.com/FrostyPenguin/88c9a807051fd95ca660289fd31d1288)

## Description
After I updated my Gitea installation to the newest build in [master](https://dl.gitea.io/gitea/master/) (2017-12-13 18:00 UTC+1) signing in with 2FA was broken. Surprisingly, this is not a “local” issue as logging in to try.gitea.io with an already existent account that's got 2FA enabled did not work either.

I tried restarting my Browser (Firefox 57.0.2) in Safe Mode (with uMatrix, uBlock, and HTTPSEverywhere disabled), but that didn't help. So it must be a problem with some newer commits to Gitea's master branch.

**Even though at first sight this might look like #1851, it definitely is *a new and reproducible* bug as “downgrading” my Gitea binary to 1.3.1 solved the problem for me.**

## Screenshots

I'm not sure if you this will help you, but sure… here's a screen cast.

https://streamable.com/4jv6u

**Comment by kcotugno** [comment]
I'm see this also on v1.3.2 but I'm seeing a different error in my logs. `2017/12/15 05:32:05 [...routers/user/auth.go:224 TwoFactorPost()] [E] UserSignIn: illegal base64 data at input byte 0`

**Comment by thehowl** [comment]
I am working on this now. After 8 steps of git bisecting, I traced back the culprit to b7ebaf6d2078cbf4de00d0782be8bc1b1de644bb. Writing it down here in case I just go to sleep in a few minutes and forget about this issue entirely.
