### ISSUE TITLE
Branch protection should have a option to allow force push

### ISSUE THREAD

**Issue by silverwind** [go-gitea/gitea#31872]
### Feature Description

Currently it's not possible to allow force pushes on a branch that has branch protection enabled:

<img width="635" alt="image" src="https://github.com/user-attachments/assets/06474c17-321c-447f-bace-6c932c14a482">

Compare with GitHub which exposes a boolean option to control force pushes:

<img width="458" alt="image" src="https://github.com/user-attachments/assets/3d523431-f8ae-4a73-85fb-203a69b19919">

I think such a boolean option should be added.

**Comment by lunny** [comment]
Did you mean #28086 ?
