### ISSUE TITLE
UI localization error

### ISSUE THREAD

**Issue by kebox7** [go-gitea/gitea#31891]
### Description

Error in the Russian localization of the user interface when selecting labels in the organization's repository.

Original message:
https://github.com/go-gitea/gitea/blob/8b92eba21f5c5cca277b8101ada0ea7a1fb32ae0/options/locale/locale_en-US.ini#L1228

Translated message:
https://github.com/go-gitea/gitea/blob/8b92eba21f5c5cca277b8101ada0ea7a1fb32ae0/options/locale/locale_ru-RU.ini#L1120

### Screenshots

Russian translation (Error)
![ru](https://github.com/user-attachments/assets/abcb908b-a7b7-4ee0-a177-49b5e77616ce)

English translation (Ok)
![en](https://github.com/user-attachments/assets/6a85d6d9-4695-4a12-aaeb-f66cd49b73eb)

### Gitea Version

1.22.1

### Can you reproduce the bug on the Gitea demo site?

Yes

### Browser Version

Chrome  127.0.6533.120

**Comment by lunny** [comment]
Fixed in https://crowdin.com/editor/gitea/68/enus-ru?view=comfortable&filter=basic&value=0#q=org_labels_desc and will be released in v1.23.

**Comment by lunny** [comment]
Fixed by #31892

**Comment by KazzmanK** [comment]
Oh, I`m late.

`использовать с <strong>всеми` is not grammatically correct. `использовать со <strong>всеми` is better.
