### ISSUE TITLE
Markdown processor should not replace tokens like `__foo__` inside links

### ISSUE THREAD

**Issue by silverwind** [go-gitea/gitea#31897]
### Description

When  a link contains text like `__init__.py`, the markdown processor will incorrectly bolden the text and break the link. The same link works fine on GitHub.

### Gitea Version

main

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

Gitea (https://demo.gitea.com/silverwind/symlink-test/issues/4):

<img width="208" alt="image" src="https://github.com/user-attachments/assets/98fbfca3-d551-4134-99e2-428b9b01b187">

GitHub (https://github.com/silverwind/symlink-test/issues/17):

<img width="899" alt="image" src="https://github.com/user-attachments/assets/c7b4e7dc-ff5e-4f54-b28a-964928834cd3">

**Comment by wxiaoguang** [comment]
The same report from 2021 : Formatting tokens in URLs should not be parsed #17958

**Comment by silverwind** [comment]
Right, it's a duplicate.

**Comment by wxiaoguang** [comment]
FYI, it has been fixed on main
