### ISSUE TITLE
pull request can not filter by commit

### ISSUE THREAD

**Issue by youlin-chang** [go-gitea/gitea#31904]
### Description

![image](https://github.com/user-attachments/assets/ec5f03c8-f9cf-457b-990a-7f1755603231)
my gitea upgrade to 1.22.1，but this function can not work，can not filter by commit

### Gitea Version

1.22.1

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![image](https://github.com/user-attachments/assets/7732d872-5482-4db7-b5ef-9014626b2d2e)

### Git Version

2.45.2

### Operating System

ubutnu

### How are you running Gitea?

docker

### Database

None

**Comment by yp05327** [comment]
Do you mean that if you click it, this menu will not disappear?
![image](https://github.com/user-attachments/assets/a80d2fee-414d-426d-9a02-0700ef69d97b)

**Comment by wxiaoguang** [comment]
I have fixed it by " Fix "Filter by commit" Dropdown (#31695) #31696 "

Use 1.22-nightly
