### ISSUE TITLE
https://dl.gitea.com/gitea/@version@/gitea-@version@-linux-amd64 - HTTP request sent, awaiting response... 404 Not Found

### ISSUE THREAD

**Issue by BaseMax** [go-gitea/gitea#31918]
### Feature Description

Based on https://docs.gitea.com/installation/install-from-binary

root@maxbasecode:/var/www/html# ^C
root@maxbasecode:/var/www/html# wget -O gitea https://dl.gitea.com/gitea/@version@/gitea-@version@-linux-amd64
--2024-08-25 06:18:28--  https://dl.gitea.com/gitea/@version@/gitea-@version@-linux-amd64
Resolving dl.gitea.com (dl.gitea.com)... 2600:9000:25f7:8800:5:7d7c:f00:93a1, 2600:9000:25f7:200:5:7d7c:f00:93a1, 2600:9000:25f7:6e00:5:7d7c:f00:93a1, ...
Connecting to dl.gitea.com (dl.gitea.com)|2600:9000:25f7:8800:5:7d7c:f00:93a1|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-08-25 06:18:28 ERROR 404: Not Found.

root@maxbasecode:/var/www/html# chmod +x gitea
root@maxbasecode:/var/www/html#

**Comment by lunny** [comment]
This is a documentation problem.

**Comment by yp05327** [comment]
same to https://gitea.com/gitea/docs/issues/10
