### ISSUE TITLE
Please add Irish language to Gitea

### ISSUE THREAD

**Issue by aindriu80** [go-gitea/gitea#31919]
### Feature Description

Hi,

Can someone please add Irish to Gitea? I'm registered on https://crowdin.com/project/gitea but I don't see the Irish/Gaeilge.  Here are some details:

Language Code: ga

My Crowdin Profile: https://crowdin.com/profile/aindriu80/

About the language: https://en.wikipedia.org/wiki/Irish_language

Many thanks and great work !!

Aindriú

**Comment by lunny** [comment]
Language created and you have been invited as Proofreader of [Irish_language](https://en.wikipedia.org/wiki/Irish_language). You are welcome to do contribute to languages.

**Comment by aindriu80** [comment]
Go raibh míle maith agat || Thanks so much !!

**Comment by aindriu80** [comment]
> Language created and you have been invited as Proofreader of [Irish_language](https://en.wikipedia.org/wiki/Irish_language). You are welcome to do contribute to languages.

Irish has been translated 100% however there are no proof readers.  Can you add me as a proof reader please :-

![Screenshot from 2024-10-01 13-18-17](https://github.com/user-attachments/assets/bc7cec5e-3198-443a-93c5-a2acf38845ec)


Irish :- 
https://crowdin.com/project/gitea/ga-IE

My Profile:-
https://crowdin.com/profile/aindriu80
