### ISSUE TITLE
Can login but unable to load history: Invalid or unexpected token

### ISSUE THREAD

**Issue by fumiama** [go-gitea/gitea#31928]
### Description

> [!Note]
> I opened a new `InPrivate` window in the latest edge browser to erase any other factors.

### Symptom 1
If the screen is wide enough to display the full `login` button, it works and redirect to the login screen. Otherwise, clicking the three-bars menu button will not get any response.
### Symptom 2
By clicking full login button and login, I was redirected to the home page. However, the history area (blue tiles) will never come out and the `add` and `user icon` cannot response to my clicking operation. I opened the console and found an error `Uncaught SyntaxError: Invalid or unexpected token`.

<img width="1297" alt="截屏2024-08-27 下午9 23 01" src="https://github.com/user-attachments/assets/f4cc8d12-cb9d-4bac-a848-022af4768833">

### P.S.
This happened after I upgrade to version 1.22.1. I have only had one normal login (with history and all buttons working) after I found this issue.

### Gitea Version

1.22.1

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

2.43.5

### Operating System

Oracle Linux Server 9.4

### How are you running Gitea?

By using systemd service
```ini
[Unit]
Description=Gitea
After=network.target

[Service]
User=nobody
Group=nobody
Environment="HOME=/usr/local/share/gitea"
WorkingDirectory=/usr/local/share/gitea
ExecStart=/usr/local/bin/gitea -c /usr/local/share/gitea/custom/conf/app.ini

[Install]
WantedBy=multi-user.target
```

### Database

SQLite3

**Comment by lunny** [comment]
It's your network problem. Please disable Disable Gravatar from your admin panel -> settings.

**Comment by wxiaoguang** [comment]
> It's your network problem. Please disable Disable Gravatar from your admin panel -> settings.

How could `Uncaught SyntaxError: Invalid or unexpected token.` in index.js be related to "Gravatar"? And since JS doesn't work, how could users use the admin panel.

**Comment by fumiama** [comment]
> > It's your network problem. Please disable Disable Gravatar from your admin panel -> settings.
> 
> How could `Uncaught SyntaxError: Invalid or unexpected token.` in index.js be related to "Gravatar"? And since JS doesn't work, how could users use the admin panel.

I agree. The Gravatar just happened to be failed. It had loaded successfully but this issue still remained.

**Comment by wxiaoguang** [comment]
Some possible problems:

1. Your browser is too old.
1. Your reverse proxy or browser plugin changes/breaks the `index.js` file.
1. Your `index.js` doesn't match the official one's, make sure there is no such file in your gitea's custom dir.
1. Compare the `index.js` from your server with the correct one to see whether the contents are the same.
    * You could setup a new instance locally to get(download) the correct `index.js` by `wget` or `curl`.

**Comment by fumiama** [comment]
> Some possible problems:
> 
> 1. Your browser is too old (since you said "latest Edge", maybe it is not related)
> 2. Your reverse proxy or browser plugin changes/breaks the `index.js` file.
> 3. Your `index.js` doesn't match the official one's, make sure there is no such file in your gitea's custom dir.
> 4. Compare the `index.js` from your server with the correct one to see whether the contents are the same.
>    
>    * You could setup a new instance locally to get(download) the correct `index.js` by `wget` or `curl`.

Thanks for your hint, they are actually different.
```
md5 *.js
MD5 (index.js) = 12496c8a2bef28865f36f8f3b3b36e5d
MD5 (index_org.js) = bdd0eb02372a4f6a451cc8b3a40b761a
```
<img width="975" alt="截屏2024-08-28 下午6 09 59" src="https://github.com/user-attachments/assets/a24fb03b-e624-4415-9eac-21980b98fb78">

 I used `cloudflare` to proxy the service, maybe it's a problem of handling CF cache. I also enabled cache in nginx, but it seems to be OK. I paste the config here and you can check it.
```ini
server {
	listen 80;
	server_name gitea.xxx.xxx;

	#PROXY-START/
	location ^~ / {
		proxy_pass http://127.0.0.1:8000;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header REMOTE-HOST $remote_addr;
		proxy_set_header Upgrade $http_upgrade;
		proxy_http_version 1.1;
		# proxy_hide_header Upgrade;

		add_header X-Cache $upstream_cache_status;
		#Set Nginx Cache
		proxy_set_header Accept-Encoding "";
		sub_filter "127.0.0.1:8000" "gitea.xxx.xxx";
		sub_filter_once off;
		set $static_fileUePDfDAU 0;
		if ( $uri ~* "\.(gif|png|jpg|css|js|woff|woff2)$" ) {
			set $static_fileUePDfDAU 1;
			expires 1m;
		}
		if ( $static_fileUePDfDAU = 0 ) {
			add_header Cache-Control no-cache;
		}
	}
	#PROXY-END/

}
```

**Comment by wxiaoguang** [comment]
> Thanks for your hint, they are actually different.
> 
> ```
> md5 *.js
> MD5 (index.js) = 12496c8a2bef28865f36f8f3b3b36e5d
> MD5 (index_org.js) = bdd0eb02372a4f6a451cc8b3a40b761a
> ```
> 
> I used `cloudflare` to proxy the service, maybe it's a problem of handling CF cache. I also enabled cache in nginx, but it seems to be OK. I paste the config here and you can check it.

Well, maybe you could try to disable some CF options (for example: JS minify, etc)

**Comment by fumiama** [comment]
> Well, maybe you could try to disable some CF options (for example: Content optimizations, JS minify, etc)

I'm trying to figure it out but I think the optimizations will not change its behavior 😂. I turned off `Auto Minify`, nothing changed. Then I changed the nginx config to

```kt
server {
	listen 80;
	server_name gitea.xxx.xxx;

	#PROXY-START/
	location ^~ / {
		proxy_pass http://127.0.0.1:8000;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header REMOTE-HOST $remote_addr;
		proxy_set_header Upgrade $http_upgrade;
		proxy_http_version 1.1;
	}
	#PROXY-END/

}
```
and it worked once on my first login. After I opened a new InPrivate window, all things turns back 😭. So the nginx is not the core problem. The problem comes from CF.

**Comment by fumiama** [comment]
Then I cleaned the cache of CF. Still nothing changed. I'm quite sure that this problem happened after I update gitea, so maybe it is a problem of gitea's communication with CF?

**Comment by wxiaoguang** [comment]
> Then I cleaned the cache of CF. Still nothing changed. I'm quite sure that this problem happened after I update gitea, so maybe it is a problem of gitea's communication with CF?

No. Gitea is a standard HTTP server, it serves the `index.js` file correctly. Any network & reverse proxy (including CF) should also serve the file correctly but not breaks it.
