### ISSUE TITLE
Tags missing on master since v1.1.0

### ISSUE THREAD

**Issue by silverwind** [go-gitea/gitea#3194]
I noticed that since v1.1.0, release tags are no longer picked up by `git describe` (and in turn show wrong in the interface footer). For example, from the current GitHub master:

````console
$ git clone git@github.com:go-gitea/gitea.git .
$ git describe --tags
v1.1.0-894-g1687aa59
````
What's weird is that the missing tags *do* show on `git tag`:

````console
$ git tag | tail -1
v1.3.2
````

Anyone know what's up?

**Comment by lafriks** [comment]
No we can not tag master as it is way ahead and there is already PRs merged for next major release

**Comment by silverwind** [comment]
I'd be fine with removing the version number and just showing the commit hash. I see that https://try.gitea.io already has such a version in the footer:

<img width="199" alt="screen shot 2017-12-14 at 21 28 39" src="https://user-images.githubusercontent.com/115237/34012956-fc337746-e115-11e7-9e78-feff91e2e67a.png">

But when I build from the git source, I seem to always get the output of `git describe --tags` in my footer. I wonder if `try.gitea.io` is built differently, hmm.

**Comment by strk** [comment]
Commit has is part of the git-describe output (final part, after the "g").
In general, tagging *before* branching would fix this problem.
I think the procedure described in the documente added by PR https://github.com/go-gitea/gitea/pull/2609 (HOWTO_RELEASE) would give us that.

**Comment by lafriks** [comment]
At most we could tag RC1 on master but I don't see much point in that

**Comment by sapk** [comment]
If we want to put tag on master we should consider master has stable and use a develop branch (currently master branch) but that is not the same git flow than currently.

**Comment by silverwind** [comment]
Tag before branch would definitely work as the tag is also visible on the branch, see below example workflow:

```console
$ git init
$ git commit --allow-empty -m "first"
[master (root-commit) 8829b85] first
$ git tag v1.0.0 -m v1.0.0
$ git commit --allow-empty -m "second"
[master f6f310f] second
$ git describe
v1.0.0-1-gf6f310f
$ git branch branch
Branch 'branch' set up to track local branch 'master' by rebasing.
$ git checkout branch
Switched to branch 'branch'
Your branch is up to date with 'master'.
$ git describe
v1.0.0-1-gf6f310f

**Comment by sapk** [comment]
Just the rethinking of it as 1.5.0 release iscoming. 

I agree with @silverwind we could also tag master before but it will work only for major release 1.5.0 (that could be enough to mark progress) but we could not add minor tag 1.5.1 to master as it will differ from branch release where it should be. 

I propose another solution, couldn't we tag master as 1.5.0-dev and 1.6.0-dev after releasing 1.5.0 ? 
This way we know that it is a dev version of 1.X and will be consistent with default tag used without make env. https://github.com/go-gitea/gitea/blob/master/main.go#L24

**Comment by sapk** [comment]
Yes, that why I suggest 1.X.0-dev to show that it is a dev version as better alternative.

**Comment by lunny** [comment]
This is still a problem

**Comment by lafriks** [comment]
@lunny I think it is not as we now add 1.X.0-dev tags to master

**Comment by silverwind** [comment]
Yes, I think it is resolved. On master:

```
$ git describe
v1.7.0-dev-92-g6b0c2e9e3
```
