### ISSUE TITLE
No admin user 'admin' found. Creating now...

### ISSUE THREAD

**Issue by nihaocool** [go-gitea/gitea#31963]
### Description

==== BEGIN GITEA CONFIGURATION ====
2024/09/03 10:44:47 cmd/migrate.go:33:runMigrate() [I] AppPath: /usr/local/bin/gitea
2024/09/03 10:44:47 cmd/migrate.go:34:runMigrate() [I] AppWorkPath: /data
2024/09/03 10:44:47 cmd/migrate.go:35:runMigrate() [I] Custom path: /data/gitea
2024/09/03 10:44:47 cmd/migrate.go:36:runMigrate() [I] Log path: /data/log
2024/09/03 10:44:47 cmd/migrate.go:37:runMigrate() [I] Configuration file: /data/gitea/conf/app.ini
2024/09/03 10:44:47 ...2@v2.27.1/command.go:272:Run() [I] PING DATABASE postgres
2024/09/03 10:44:54 ...2@v2.27.1/command.go:272:Run() [W] Table oauth2_application Column confidential_client db default is true, struct default is TRUE
2024/09/03 10:44:55 ...2@v2.27.1/command.go:272:Run() [W] Table system_setting Column version db default is , struct default is 1
2024/09/03 10:44:56 ...2@v2.27.1/command.go:272:Run() [W] Table user Column max_repo_creation db default is '-1', struct default is -1
2024/09/03 10:45:02 ...2@v2.27.1/command.go:272:Run() [W] Table label Column archived_unix db default is , struct default is NULL
Wait for redis to become avialable...
gitea-redis-headless.nihao-cool.svc.cluster.local (10.244.85.199:6379) open
No admin user 'admin' found. Creating now...
Command error: CreateUser: name is reserved [name: admin]

### Gitea Version

latest

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

1

### Screenshots

1

### Git Version

1

### Operating System

1

### How are you running Gitea?

1

### Database

None

**Comment by lunny** [comment]
Please give more details. Looks like it's not an official Gitea binary/image?

**Comment by wxiaoguang** [comment]
The reason is there, you have seen " No admin user 'admin' found. Creating now...", then what does next sentence say?

**Comment by wxiaoguang** [comment]
` Command error: CreateUser: name is reserved [name: admin]`

`admin` is a reserved name, so it can't be used to create a user with that name.

You could try other names like `adm`, `root` or `adminuser`, etc
