### ISSUE TITLE
Cleanup actions expired logs not seems working

### ISSUE THREAD

**Issue by Shakthijuego** [go-gitea/gitea#31962]
### Gitea Version

1.22.1

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

These  configs does not have any impact. 
[actions]
LOG_RETENTION_DAYS = 1
ARTIFACT_RETENTION_DAYS = 1

No 'logs' related to removal of action logs

### Operating System

nginx

### How are you running Gitea?

Via nginx reverse proxy

### Database

SQLite

**Comment by lunny** [comment]
`LOG_RETENTION_DAYS` is only for coming 1.23.

**Comment by Shakthijuego** [comment]
Ok. I will for it.
