### ISSUE TITLE
Add searching capabilities to the tags page 

### ISSUE THREAD

**Issue by bsofiato** [go-gitea/gitea#31998]
### Feature Description

How do you feel about adding search functionality to `/{org}/{repo}/tags`? 
I think it would greatly enhance the UX when dealing with repos with huge amounts of tags. Moreover, both `/{org}/{repo}/commits/**` and `/{org}/{repo}/branches` already support searching, so why not ? :)

If you guys are cool with it, I can try to provide a PR for it.

**Comment by lunny** [comment]
Yes, it's great to have a search feather there. Please send a PR and I'm glad to review it.

**Comment by bsofiato** [comment]
Cool @lunny, gonna work on it during the week :)

**Comment by bsofiato** [comment]
Hey @lunny, I've just created the PR#32045 that implements this feature. :)
