### ISSUE TITLE
Team members can't rename branch but adding and deletion is possible

### ISSUE THREAD

**Issue by urz-hgw** [go-gitea/gitea#31993]
### Description

Hi,

it looks like there is a permission issue so that team members can't rename branches.

I can reproduce it like this:

There is an organization **O** with a Team **T**. 

The Team **T** has access to `specific repositories` with `General access` and at `Allow Access to Repository Sections` every section is set to **write**.
Then I add user **X** to the Team **T** .. **X** is NOT an owner of the organization.

Then I create a repository **REPO** inside the organization **O** and add the team **T** to it.
The user **X** now has the permission to add and delete a branch in **REPO**, but renaming a branch leads to a 404 error message.

The log output is
```
gitea-1    | 2024/09/06 09:25:21 ...eb/routing/logger.go:102:func1() [I] router: completed POST /O/REPO/settings/rename_branch for 192.168.82.13:52774, 404 Not Found in 20.2ms @ context/permission.go:17(web.registerRoutes.RequireRepoAdmin)
```

Best regards
Daniel

### Gitea Version

1.22.2

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

Debian 12

### How are you running Gitea?

Via docker

### Database

MySQL/MariaDB

**Comment by yp05327** [comment]
I'm not sure whether it is by design.
But it makes sense if user has write permission, they should can rename the branch. 🤔

**Comment by lunny** [comment]
If user can delete branch, it should have permission to create a new one.

**Comment by urz-hgw** [comment]
> If user can delete branch, it should have permission to create a new one.

Just to clarify: adding and deleting a branch works, it is renaming a branch, that causes an error message

**Comment by KebabLord** [comment]
I can verify the problem at Version: 1.22.1
deletion or creation is possible but /user/repo/settings/rename_branch returns 404

i'm glad that it will be fixed with new release
