### ISSUE TITLE
Unable to change user account source form any external to local

### ISSUE THREAD

**Issue by OCram85** [go-gitea/gitea#31996]
### Description

If your try to migrate any user to internal account type it fails with the error message `Non-local users are not allowed to change their username.`

Already tried to keep or change the user property values through ui: `Authentication Sign-In Name` or `Username`

### Gitea Version

1.22.2

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

See https://forum.gitea.com/t/ho-to-change-gitea-user-account-type/9682

### Operating System

Ubuntu LTS

### How are you running Gitea?

docker swarm stack

### Database

PostgreSQL

**Comment by OCram85** [comment]
Any ideas how I could change such user account name?

**Comment by lunny** [comment]
Looks like a bug. I will take a look this week.

**Comment by OCram85** [comment]
Any updates for this?
