### ISSUE TITLE
Protected branches system

### ISSUE THREAD

**Issue by DblK** [go-gitea/gitea#32]
One missing feature from gogs is a way to protect branches like Github does.
After the completion of the API implementation, we could easily add application like Drone to check the PR.

The UI need to be changed to add options to protect branches like this:
![image](https://cloud.githubusercontent.com/assets/832617/19982051/c16c721c-a204-11e6-8965-e187c2ef3377.png)

I suggest to add some columns in table (don't know how many yet) to store those options.
The "Merge" button from a PR should be activated is the conditions are not matched.

**Comment by tboerger** [comment]
Please don't prefix the issue with `[Feature]`, that should be done via labels. This is an important feature for an lgtm.co integration, so a big :+1: for that.

**Comment by lunny** [comment]
I think this need a proposal to describe it.

**Comment by DblK** [comment]
I will write it soon and remove this comments after I have done it.

**Comment by bkcsoft** [comment]
@lunny Agreed. I've looked into this issue before, and it requires a rewrite of how GitHooks are currently Exposed.

Reference: https://github.com/gogits/gogs/issues/776#issuecomment-238779355

**Comment by strk** [comment]
@DblK "proposal" proposed process is here https://github.com/go-gitea/proposals/pull/1

**Comment by thibaultmeyer** [comment]
+1 without protected branches system, Gitea will be not ready for a corporate environment where is not acceptable to ask at each developers to use the "fork and pull request" flow.

**Comment by lunny** [comment]
Before we can start protected branch, we have to finish the dependent features first:
- [ ] code review, this is based comment on code, but add a flag to disable merge button until the comment author close it.
- [ ] status check system, this is based webhook. and it's a specific webhook. We could define it like github.
- [ ] rebase the PR.

Implement every one feature will not result many commits, so we can do it step by step.
Welcome to improve it.

**Comment by Ritbit** [comment]
+1 desperately in need for this.

**Comment by bkcsoft** [comment]
@lunny no need for all that, just a simple `branch X can't be pushed to` would suffice to start with :slightly_smiling_face: 

As for status check, that would be fairly simple to implement really (if one does as GitHub API does)

**Comment by lunny** [comment]
#339 is the first part merged for this issue, so let's move it to v1.2.

**Comment by ghost** [comment]
Only thing stopping us moving to gitea now.
We have a company 1k dev strong.
Please, I urge the community to focus on this.

**Comment by ptman** [comment]
@exp10r3r Do you have any golang devs that could help?

**Comment by lunny** [comment]
@exp10r3r We have #339 merged a simple protected branch system. Of course we need more features.

**Comment by ghost** [comment]
@ptman Unfortunately, no. More than 50% from NodeJS, 10% php and the rest html/css.

@lunny I know, and I have been following development since you guys forked and personally using it since last 15 days.
The issue arose from the fact that I had given the rest of my team write access to the repo and marked master branch as protected.
I only want them to be able to push to the feature branch, after which a PR is made and only the person with push rights to master can merge this PR.
Imagine my surprise when a dev was merging his own PRs.
Obviously it was an oversight on my end, I should have tested this first hand.
I'm glad though that force pushes are not allowed, that would have been a nightmare.

Anyways, a good branch protection scheme will go a long way in increasing gitea's value proposition.

**Comment by ghost** [comment]
Even implementing [this](https://github.com/gogits/gogs/issues/4376) would go along a long way.

**Comment by svarlamov** [comment]
Now that we have protected branches and whitelisting, what would it take to add status checks similar to: https://help.github.com/articles/enabling-required-status-checks/

**Comment by lunny** [comment]
@svarlamov yes, we need only 1 PR to show the status check on PR UI since all data have been ready.

**Comment by lunny** [comment]
I think this issue has been resolved.
