### ISSUE TITLE
The Conan v2 software package seems to be unsupported

### ISSUE THREAD

**Issue by WangZhongDian** [go-gitea/gitea#32004]
### Description

The Conan v2 software package seems to be unsupported
![截图 2024-09-07 10-51-29](https://github.com/user-attachments/assets/25524c8f-1694-4e6f-a448-8e8cf5b8bacf)

### Gitea Version

1.22.2

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![截图 2024-09-07 11-01-43](https://github.com/user-attachments/assets/4166ac03-b9aa-465f-9d3d-54ecf62bf160)
new:/api/packages/youmetme/conan/v2/conans
The path URL has been changed to 'v2' in Conan v
old:
![image](https://github.com/user-attachments/assets/7dab4b8f-b9f0-4a5e-948e-051dd97f516f)

### How are you running Gitea?

docker

### Database

SQLite

**Comment by yp05327** [comment]
Can you provide some related Gitea's logs?

**Comment by WangZhongDian** [comment]
[gitea1.22.2-20240909170332.log](https://github.com/user-attachments/files/16928197/gitea1.22.2-20240909170332.log)
@yp05327

**Comment by WangZhongDian** [comment]
@yp05327 

It existed before the upgrade and still exists after the upgrade

**Comment by yp05327** [comment]
> addFileToPackageVersionUnchecked() [E] Error saving package blob in content store: mkdir /data/gitea/packages/70: permission denied

You need to check the permission of your filesystem.

**Comment by WangZhongDian** [comment]
@yp05327 
What kind of permissions do I need to give it, and why do Docker container images work properly with other packages
![截图 2024-09-10 08-53-35](https://github.com/user-attachments/assets/063b904e-cdcb-4d9e-9f93-754a5eda3403)

**Comment by WangZhongDian** [comment]
@yp05327 
Although it is unclear why Conan requires this permission and not others, the issue was indeed resolved after changing the permissions

**Comment by yp05327** [comment]
@KN4CK3R is familiar with the package system.
But I think they should be same.
