### ISSUE TITLE
Gitea does not send any emails

### ISSUE THREAD

**Issue by kolaente** [go-gitea/gitea#32006]
### Description

Since I think 1.22.0, Gitea does not send any emails. No issue/pr/other notifications, not even password reset mails. However, the test mail I can dispatch from the admin interface arrives in my inbox without issues.
I did not find anything relevant in the logs.

### Gitea Version

1.23.0+dev-467-ga5818470fe

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

Official docker image.

### Database

MySQL/MariaDB

**Comment by kolaente** [comment]
Maybe related to https://github.com/go-gitea/gitea/issues/19686, but then the test mail would not arrive

**Comment by lunny** [comment]
Can you paste your email configurations without credential content.

**Comment by kolaente** [comment]
```
[mailer]
ENABLED = true
SMTP_PORT = 587
SMTP_ADDR = mail.kolaente.de
FROM = "Gitea" <git@kolaente.de>
USER = git@kolaente.de
PASSWD = REDACTED

**Comment by lunny** [comment]
`PROTOCOL=smtp+starttls` Maybe you can try to add this item.

**Comment by kolaente** [comment]
Looks like that did not fix it. The test mail from the admin interface works, but for example a password reset does not.

**Comment by techknowlogick** [comment]
Could you check your admin interface to see how many workers the mail queue has? As the test might bypass the queue

**Comment by kolaente** [comment]
The mail queue has 0 workers. Shouldn't they grow based on demand?

**Comment by kolaente** [comment]
I've tried increasing the worker limit, but still no workers are created. Meanwhile there are 2k tasks in the queue.

How can I fix this?

**Comment by kolaente** [comment]
Updated to latest nightly and cleared the queue, that seems to have fixed it. Thanks!

**Comment by wxiaoguang** [comment]
Well, I used to be a "queue expert" 🤣
