### ISSUE TITLE
Using HighCharts to render Contributors?

### ISSUE THREAD

**Issue by yp05327** [go-gitea/gitea#32012]
### Feature Description

![image](https://github.com/user-attachments/assets/71098224-baab-4f17-a57a-16b4c437ee0c)
It seems that GitHub is planning to use HighCharts.
It seems good.

**Comment by kemzeb** [comment]
Hmm, exploring this further I realized that HighCharts has some [strict licensing ](https://shop.highcharts.com).

**Comment by techknowlogick** [comment]
Yup. seems it cannot be included: https://www.highcharts.com/forum/viewtopic.php?t=51078
