### ISSUE TITLE
Delete repository pop up hint message not format well in Simple Chinese.

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#3201]
![image](https://user-images.githubusercontent.com/81045/34044879-c3ba88a6-e1e1-11e7-8ab4-7ed345aedc15.png)

**Comment by muhfaris** [comment]
what this issue is available ?
i'm interesting to fix this problem

**Comment by lunny** [comment]
Yes, It's easy to fix. Please send a PR.

**Comment by muhfaris** [comment]
I think other person have fixed it

![scrot_2017-12-20--1513764247_761x357](https://user-images.githubusercontent.com/16787866/34201839-d6df1644-e543-11e7-9951-4fd6270e4d5f.png)

**Comment by lunny** [comment]
@muhfaris no. `<strong>%s</strong>` should be replaced but in fact didn't
