### ISSUE TITLE
Disable workflows when mirroring repository

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#32010]
### Feature Description

It would be able to disable all workflows when you first mirror a repo and have a setting to disable any additional workflows that appear specifically from a git pull of the mirror.

There might be several ways to get this done:

- option to disable external workflows on mirror creation
- repo level setting allowing to disable workflows (this could be used for other purposes as well)
     - repo setting to disable specifically `.github` workflows
     - repo setting to customize the .gitea/.gitub workflow file
- Add option to omit it from global runners

**Comment by yp05327** [comment]
Similar to  #30350. Same issue, but different solutions.
