### ISSUE TITLE
`migrations.ALLOWED_DOMAINS` doesn't work as expected with `PROXY_URL` set

### ISSUE THREAD

**Issue by wolfogre** [go-gitea/gitea#32024]
### Description

If  Gitea starts with config:

```
[proxy]
PROXY_ENABLED = true
PROXY_URL = http://127.0.0.1:7890
PROXY_HOSTS = *.github.com,github.com

[migrations]
ALLOWED_DOMAINS = "" ; blank means external hosts will be allowed
```

It will fail to migrate repos from github.com.

<img width="683" alt="image" src="https://github.com/user-attachments/assets/337b8b3f-d808-41c7-8ce9-a29776b01c5f">

Enabling `ALLOW_LOCALNETWORKS` can resolve it, but it's not the way as expected.

### Gitea Version

main (d9a7748cdc)

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

Command with binary.

### Database

SQLite

**Comment by wolfogre** [comment]
I believe it's an overlooked work of #27655.

**Comment by lunny** [comment]
Because proxy url should be added to allowed migration url automatically?
