### ISSUE TITLE
Repository home page show error file last commit message.

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#3202]
Compare github's home page 
https://github.com/go-gitea/gitea/tree/release/v1.0
![image](https://user-images.githubusercontent.com/81045/34045335-769bbde0-e1e3-11e7-8755-959b17045733.png)

vs https://try.gitea.io/gitea/gitea/src/branch/release/v1.0
![image](https://user-images.githubusercontent.com/81045/34045321-62516cb8-e1e3-11e7-92d5-5957db5f02f7.png)

**Comment by ethantkoenig** [comment]
Possibly related to https://github.com/go-gitea/git/pull/91. I will investigate as soon as I get the chance.

**Comment by lunny** [comment]
Repo.cache will be invoked in multiple go routines.

**Comment by lunny** [comment]
Maybe add a test some commit tree the same as github.

**Comment by lunny** [comment]
Confirmed release/v1.3 has no this issue.

**Comment by lunny** [comment]
resolved by #3240
