### ISSUE TITLE
Paste image cannot convert to img tag in windows.

### ISSUE THREAD

**Issue by seepine** [go-gitea/gitea#32039]
### Description

When using the Edge browser on macOS, pasting an image in an issue will automatically convert it into an img tag and set the width. On Windows, pasting will still use Markdown syntax.

macos 14
- edge 115.0.1901.203

windows10
- edge 128.0.2739.67

### Gitea Version

1.22.2

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

![image](https://github.com/user-attachments/assets/11721aaa-34b5-4ef7-8cb4-824472c942c3)

![image](https://github.com/user-attachments/assets/6faa1a88-1219-4e23-bb25-1802a4682e5b)

### How are you running Gitea?

in docker

### Database

None

**Comment by yp05327** [comment]
![image](https://github.com/user-attachments/assets/fb506782-e30a-4cad-8096-697a9581b0d0)
It seems that it is related to the monitor's DPI
