### ISSUE TITLE
Gravatar profile pictures won't upload

### ISSUE THREAD

**Issue by KoltesDigital** [go-gitea/gitea#32032]
### Description

I just updated the helm chart. On _Explore_ page, all profile pictures coming from Gravatar don't show up anymore. If I try to update my avatar from Gravatar, it still doesn't show up (I also tried with another email linked to a Gravatar picture). However if I delete the avatar (i.e. generate a random one) or upload a local file, it works as before, so I believe connection to S3 and permissions are correct.

On the Gitea demo site, the randomly generated profile picture still shows up after updating the avatar, which is not the same behavior, but is also broken.

### Gitea Version

1.22.2

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

![image](https://github.com/user-attachments/assets/6b600533-4376-4eb9-90b3-8d1d8a436464)

### How are you running Gitea?

I've updated the helm chart to 10.4.1, using Gitea 1.22.2.
Before updating: helm chart 10.1.4, using Gitea 1.21.11.

### Database

PostgreSQL

**Comment by yp05327** [comment]
Maybe a similar issue to #31075

**Comment by KoltesDigital** [comment]
@yp05327 thanks. Indeed it is. I've only looked for _gravatar_, as uploaded avatars have shown up.

**Setting `server.OFFLINE_MODE` to `false` worked.**

FTR, `{data path}/avatars` does not exist, and logs show nothing at the info+ level.

**Comment by yp05327** [comment]
I see. So it is caused by #28548.
