### ISSUE TITLE
Commit Search is unavailable 

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#3203]
On commits page, search commit will never show any commits.

**Comment by lunny** [comment]
It also effected release/v1.3

**Comment by ethantkoenig** [comment]
@lunny I can't reproduce (see screenshot), can you provide a more detailed description?

![image](https://user-images.githubusercontent.com/8990880/34067618-aec8a8a8-e1df-11e7-9fb1-42a9e94a7d60.png)

**Comment by lunny** [comment]
@ethantkoenig I think u r right!
