### ISSUE TITLE
Gitea `npm` repo: Incorrect or missing password

### ISSUE THREAD

**Issue by FrostKiwi** [go-gitea/gitea#32048]
### Description

We have Gitea hosted on a subpath: domain.com/git
I tried to setup npm package hosting following https://docs.gitea.com/usage/packages/npm . I generated a token for a public user via `curl -k -H "Content-Type: application/json" -d '{"name":"npm"}' -u user:password https://domain.com/git/api/v1/users/<user>/tokens`
Got a SHA1 token.

I setup my npmrc:
```
@<scope>:registry=https://domain.com/git/api/packages/<user>/npm/
//domain.com/git/api/packages/<user>/npm/:_authToken=<SHA1 token>
strict-ssl=false
```

I publish a package
```
npm notice
npm notice Publishing to https://domain.com/git/api/packages/<user>/npm/ with tag latest and default access
npm error code E401
npm error Incorrect or missing password.
npm error If you were trying to login, change your password, create an
npm error authentication token or enable two-factor authentication then
npm error that means you likely typed your password in incorrectly.
npm error Please try again, or recover your password at:
npm error   https://www.npmjs.com/forgot
npm error
npm error If you were doing some other operation then your saved credentials are
npm error probably out of date. To correct this please try logging in again with:
npm error   npm login
npm error A complete log of this run can be found in: C:\Users\<user>\AppData\Local\npm-cache\_logs\2024-09-16T08_57_19_988Z-debug-0.log
```
npm version `10.8.1`

Having followed the steps, but getting bumped for incorrect login. Is there a regression regarding npm and gitea? Did I do something wrong?

### Gitea Version

1.22.1

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

Binary install, Linux Server, forward proxy through nginx

### Database

None

**Comment by FrostKiwi** [comment]
Same deal on the demo site
```
npm notice Publishing to https://demo.gitea.com/api/packages/FrostKiwi/npm/ with tag latest and default access
npm error code E401
npm error Incorrect or missing password.
npm error If you were trying to login, change your password, create an
```
Tokens generated as per doc

**Comment by FrostKiwi** [comment]
Figured out a workaround. There is something wrong with how Gitea handles the auth token and how it interplays with npm. Not sure exactly why.

I managed to do publishing to Gitea's npm via basic auth, via `echo -n 'user:password' | base64`
and `//domain.com/git/api/packages/<user>/npm/:_auth=result`

**Comment by KN4CK3R** [comment]
Same as in Discord: Your token has no package access. You created a token without any scopes. If you create your token with `-d '{"name":"npm","scopes":["all"]}'` it should work.

**Comment by FrostKiwi** [comment]
> Same as in Discord: Your token has no package access. You created a token without any scopes. If you create your token with `-d '{"name":"npm","scopes":["all"]}'` it should work.

Ohhhhh, that needs to clarified in the documentation I think.

**Comment by theRotten0** [comment]
> Same as in Discord: Your token has no package access. You created a token without any scopes. If you create your token with `-d '{"name":"npm","scopes":["all"]}'` it should work.

how to create token with -d '{"name":"npm","scopes":["all"]}'  ?    in the webpage?  or where?  i didn't see the input place for  【   -d '{"name":"npm","scopes":["all"]}'  】  . can you infer them ? maybe reply with a image ?

**Comment by KN4CK3R** [comment]
It's the parameter in the curl request @FrostKiwi wrote in the issue. You can do the same on the UI in your account settings.
![grafik](https://github.com/user-attachments/assets/d337b193-d2cc-4d2d-92b0-2cada48aba33)

**Comment by theRotten0** [comment]
> {"name":"npm","scopes":["all"]}

thanks, it fixed ok.  

 but there is still another question:   now we can publish to personal register center ,   

but     How to publish npm **to the Organization** ? 

 if use the owner's token publish to org's register center uri, then nobody can config the packages.  even the systemSuperAdmin .    what's the right way to publish npm packages to organization ?    there is not so much things in the document.

**Comment by KN4CK3R** [comment]
The user just needs package permissions in the organization.

**Comment by theRotten0** [comment]
> The user just needs package permissions in the organization.
ok,thanks.

and Who have the  permissions ?


the user must be owner ?  or  be the administrator of stock ?     what  user have the  permissions  ?  or  how to config the user's   permissions   with an organization ?

**Comment by FrostKiwi** [comment]
Tested it out and works flawlessly. Indeed, user error around token creation.

@KN4CK3R Things I did not understand when following https://docs.gitea.com/usage/packages/npm and https://docs.gitea.com/development/api-usage#authentication :

- You can create Tokens from the UI.
  - How is that not the first thing written in https://docs.gitea.com/development/api-usage#authentication ?
- For tokens to work with packages, the package scope had to be given for Read & Write.

**Comment by KN4CK3R** [comment]
The package docs were written before tokens had scope support. But as Gitea is a community project you are just on PR away from changing that. :slightly_smiling_face:

**Comment by FrostKiwi** [comment]
> The package docs were written before tokens had scope support. But as Gitea is a community project you are just on PR away from changing that. 🙂

@KN4CK3R You are right. Created pull request https://gitea.com/gitea/docs/pulls/72 and opened https://github.com/go-gitea/gitea/issues/32078 to clear-up a small follow-up bug.
