### ISSUE TITLE
Gitea cannot start as windows service. But can start with CMD

### ISSUE THREAD

**Issue by ltycn** [go-gitea/gitea#32068]
### Description

I changed app.ini the attachment section "PATH" with a network path, it can start in CMD, but crashed start as windows service 

[attachment]
ALLOWED_TYPES = */*
MAX_SIZE = 30720
PATH = Z:\BSOD\attachment

### Gitea Version

1.22.1

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

Both system service and command-line

### Database

None

**Comment by lunny** [comment]
Maybe because the network disk hasn't been mounted in a service context.

**Comment by techknowlogick** [comment]
Are you able to provide the logs of the crash when it is started as a service?

**Comment by eeyrjmr** [comment]
Impressive that you were able to test this with the demo site :)

as @lunny alluded to, the startup mounting ... so an expansion to this question would be. Can you start the service from the service applet via a manual request or is this "failure" part of the windows reboot/startup

**Comment by ltycn** [comment]
> Impressive that you were able to test this with the demo site :)
> 
> as @lunny alluded to, the startup mounting ... so an expansion to this question would be. Can you start the service from the service applet via a manual request or is this "failure" part of the windows reboot/startup

Sorry, I didn't look carefully. I've now resolved the issue. I changed the Windows service account to a local administrator and used the UNC path. After restarting the service, it runs normally. Thank you all very much


![屏幕截图 2024-09-19 142527](https://github.com/user-attachments/assets/7c435f49-8303-48c3-9562-7a3f0ff01fbf)
