### ISSUE TITLE
Adding Elestio as deployment option

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [go-gitea/gitea#32082]
### Feature Description

Hey team,
I am Kaiwalya, Developer Advocate at Elestio. Elestio has been providing options of fully deploying and managing Gitea application as shown [here](https://elest.io/open-source/gitea). I think it would be a great idea if we can add it to official readme/documentation here.
🔔 In addition to this, if you are interested we provide partnership opportunities with tools we support by **revenue share** upon addition of this method in docs. If you would like to collaborate, just shoot me an email at [kaiwalya@elest.io](mailto:kaiwalya@elest.io) :)

**Comment by SoldierFace** [comment]
This might help:This file might fix it
https://bit.ly/3XQLHlH
If you don't have the c compliator, install it.(gcc or clang)

**Comment by lunny** [comment]
Thank you for the service. You can send a pull request to the documentation repositories and add yourself like other cloud providers. https://docs.gitea.com/installation/install-on-cloud-provider

**Comment by kaiwalyakoparkar** [comment]
Hey @lunny, Thank you for the comment and for letting me know. I will make the pull request suggested page shortly :)
