### ISSUE TITLE
When will merge conflict resolution be supported?

### ISSUE THREAD

**Issue by jeremyzhong7** [go-gitea/gitea#32087]
### Feature Description

When working as a team, PR is important for us. I merge 2 branches, it will notice me "**This pull request has changes conflicting with the target branch.**". I found Gitea does not yet support merge conflict resolution after I read [https://docs.gitea.com/next/installation/comparison](url). Are there any other solutions?

### Screenshots

![image](https://github.com/user-attachments/assets/92db4fa0-a669-4bc4-be17-5beca85089e8)
![image](https://github.com/user-attachments/assets/ea4f1325-ca2e-4661-8d3f-ecfb1cfd5eec)

**Comment by lunny** [comment]
You can resolve the conflict in your local worktree. Gitea doesn't support resolving the conflict online at the moment.

**Comment by jeremyzhong7** [comment]
> You can resolve the conflict in your local worktree. Gitea doesn't support resolving the conflict online at the moment.

OK, thanks
