### ISSUE TITLE
2FA not working

### ISSUE THREAD

**Issue by rubenelshof** [go-gitea/gitea#32091]
### Description

Upon opening Gitea I had to relogin.
After giving the username and password I had to enter the 2FA code but was rejected multiple times.
I than had to use the 2FA recovery key to login.

I have tried to re-enroll my phone but after scanning the QR code and typing in the resulting 2FA code I get the message 'The passcode is incorrect. Try again.'

I am able to enroll my phone on the demo site.

### Gitea Version

1.23.0+dev-496-g1fede04b83

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

Docker

### Database

PostgreSQL

**Comment by wxiaoguang** [comment]
> 99%: your server/mobile/pc time is out of sync, please make sure your all your devices have accurate time.

**Comment by rubenelshof** [comment]
I am almost 100% certain that the time's are all in sync.
Additionally I have also tried to enroll the phone via my laptop. Same issue.

**Comment by wxiaoguang** [comment]
What you see might not be what it is, especially when there is "timezone"

* Could you check your server time by  `date +%s`? The unix timestamp should be the same on all devices.
* Did you see any error message in Gitea log?

**Comment by rubenelshof** [comment]
I hadn't thought about the server time.
It was indeed out of sync. I have 2FA working again.
Thank you for helping out.
