### ISSUE TITLE
Mention comment link leads to

### ISSUE THREAD

**Issue by kuraga** [go-gitea/gitea#32100]
### Feature Description

In Gitea 1.18.3,
in the Issue editor,
`https://git.calculate-linux.org/calculate/calculate-overlay/pulls/94#isuecomment-893` is rendered to `#94` (and it's a link).

The proposition: to show that the link leads to the comment (not the issue itself).

P.S. The same, for the tooltip.

**Comment by delvh** [comment]
Please update to 1.22.
If I recall correctly, we already implemented something like this.

**Comment by kuraga** [comment]
It's not mine...
Well, let's the second commenter will be free to close it.

**Comment by kuraga** [comment]
Yes, it's true.
