### ISSUE TITLE
API responds with 201 before the created resource is ready

### ISSUE THREAD

**Issue by semyonf** [go-gitea/gitea#32111]
### Description

I'm creating and merging Pull Requests using Gitea's REST API, and sometimes it responds with HTTP 405 unless I include a delay between the API calls. Can you please make it respond with 201 only after the created resource is actually ready?

### Gitea Version

1.22.1

### Can you reproduce the bug on the Gitea demo site?

No, my network is slow and it acts like a delay by itself

### How are you running Gitea?

Locally, in Docker

### Database

MySQL/MariaDB

**Comment by yp05327** [comment]
What is the description of 405? I guess it maybe something like  `PR not in mergeable state`, `Please try again later`.
For each PR, a mergeable test will be run automatically, and this is a backend queue task.
So I guess the issue you met is that the PR is created but mergeable test is still running, so you can not merge it immediately until the test is finished.

**Comment by semyonf** [comment]
Yes it does say to try later, I guess it makes sense that the test has to run asynchronously, PRs can be quite large after all...

**Comment by yp05327** [comment]
Do you have any more questions?
I think this issue can be closed, as the delay is necessary.
