### ISSUE TITLE
Can not use NuGet package in multiple repositories

### ISSUE THREAD

**Issue by RickZeeland** [go-gitea/gitea#32132]
### Description

I can not find a way to use a NuGet package in multiple repositories even after uploading as "generic".
It seems a NuGet package can only be linked to one repository.
Am I missing something here?

### Gitea Version

1.22.2

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

2.46.1

### Operating System

Windows Server 2022 Standard

### How are you running Gitea?

gitea.exe web

### Database

PostgreSQL

**Comment by KN4CK3R** [comment]
Linking a package to a repository is just something visual at the moment. Usually it's the repository with its source. Therefore the intention is to link it to one repository.

**Comment by RickZeeland** [comment]
@KN4CK3R Ah thanks, so if I understand correctly I don't even need to link NuGet packages to repositories in Gitea to be able to use them from e.g. Visual Studio.

**Comment by KN4CK3R** [comment]
Yes, the "entrypoint" for Visual Studio is the owner of the package. Have a look at the docs (or the package page) which tells you what url you need to configure VS to use the registry.

**Comment by RickZeeland** [comment]
So linking to a repo is not necessary to be able to use the packages.

**Comment by KN4CK3R** [comment]
No, in future the link may control the package access but currently it just displays the package in the repo context.
