### ISSUE TITLE
NuGet repository does not accept symbol packages

### ISSUE THREAD

**Issue by colejohnson66** [go-gitea/gitea#32133]
### Description

We updated to 1.22.2, and it looks like Gitea is now responding HTTP 400 to symbol package pushes.

### Gitea Version

1.22.2

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

This is the output in Jenkins

![image](https://github.com/user-attachments/assets/57dcb126-c47a-4087-b12e-608882c8c4fb)

<details><summary>Text Form</summary>

> 13:12:42  [out] $ dotnet.exe nuget push --api-key ******** --source http://10.0.0.31/api/packages/{org}/nuget/index.json *.nupkg --skip-duplicate --symbol-api-key ********
> 13:12:43  warn : You are running the 'push' operation with an 'HTTP' source, 'http://10.0.0.31/api/packages/{org}/nuget/index.json'. Non-HTTPS access will be removed in a future version. Consider migrating to an 'HTTPS' source.
> 13:12:43  Pushing {package}.2024.925.1310.nupkg to 'http://10.0.0.31/api/packages/{org}/nuget'...
> 13:12:43  warn : You are running the 'push' operation with an 'HTTP' source, 'http://10.0.0.31/api/packages/{org}/nuget/'. Non-HTTPS access will be removed in a future version. Consider migrating to an 'HTTPS' source.
> 13:12:43    PUT http://10.0.0.31/api/packages/{org}/nuget/
> 13:12:43    Created http://10.0.0.31/api/packages/{org}/nuget/ 170ms
> 13:12:43  Your package was pushed.
> 13:12:43  Pushing {package}.2024.925.1310.snupkg to 'http://10.0.0.31/api/packages/{org}/nuget/symbolpackage'...
> 13:12:43  warn : You are running the 'push' operation with an 'HTTP' source, 'http://10.0.0.31/api/packages/{org}/nuget/symbolpackage/'. Non-HTTPS access will be removed in a future version. Consider migrating to an 'HTTPS' source.
> 13:12:43    PUT http://10.0.0.31/api/packages/{org}/nuget/symbolpackage/
> 13:12:43    BadRequest http://10.0.0.31/api/packages/{org}/nuget/symbolpackage/ 9ms
> 13:12:43  error: Response status code does not indicate success: 400 (Bad Request).
> 13:12:43  .NET Command Completed - Exit Code: 1

</p>
</details> 

### How are you running Gitea?

Windows Service

### Database

None

**Comment by lunny** [comment]
Which version did you upgrade from? Can that version work for you?

**Comment by colejohnson66** [comment]
I unfortunately can't, but I took a look at Gitea's code, and it looks like it gives 400 if the package is "bad" in some way, such as a missing PDB. I took a look inside the generated `snupkg` and indeed, there's no PDB inside. This makes sense as we switched to embedded PDBs (`<DebugType>Embedded</DebugType>`), so I think this was just a PEBKAC on my part.
