### ISSUE TITLE
In diff page, links in markdown files may not highlighted in sometimes

### ISSUE THREAD

**Issue by yp05327** [go-gitea/gitea#32136]
### Description

![image](https://github.com/user-attachments/assets/71f90006-8ef0-47e9-9a5c-80912e95b725)
https://gitea.com/gitea/docs/pulls/47/files

### Gitea Version

 1.23.0+dev-526-g3269b04d61 

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

gitea.com

### Database

None

**Comment by KN4CK3R** [comment]
Looks like the first round bracket is the reason.

**Comment by cloudchamb3r** [comment]
It seems to be a tokenizing issue with the chroma markdown lexer.
