### ISSUE TITLE
Add new checkbox code `- [ ]` for new line automatically on enter press in issue and PR text

### ISSUE THREAD

**Issue by timbze** [go-gitea/gitea#32135]
### Feature Description

It would be great if when adding a checkbox, an enter press for new line would automatically add another checkbox, like GitHub does.

Type in `- [ ] First point` and press enter. It's simply a newline. In GitHub, it automatically adds `- [ ] ` on the new line and it's ready to enter second point. Then, if you don't want another point you simply press enter again and it removes the checkbox code on the newline.

**Comment by wxiaoguang** [comment]
Done in  Add some handy markdown editor features #32400
