### ISSUE TITLE
[W] SyncReleasesWithTags: GetTags: exit status 128 - fatal: Not a git repository (or any of the parent directories): .git

### ISSUE THREAD

**Issue by strk** [go-gitea/gitea#3214]
Upon upgrading from Gogs-0.9-something to Gitea-1.3.2-dev I found a few of these messages in the logs:
> 2017/12/17 03:24:04 [W] SyncReleasesWithTags: GetTags: exit status 128 - fatal: Not a git repository (or any of the parent directories): .git

This ticket is to request to make the message more interesting by adding the repository name.
Would also be nice to know how to fix the problem, if problem needs be fixed...

**Comment by lafriks** [comment]
Check that your repositories directory is specified correctly in app.ini

**Comment by amit-handa** [comment]
yes, thanks @lafriks . I was running in docker on k8s. for some reason, even though file ownerships and docker process uids matched, it still had an issue reading the bare repos. 
I somehow solved it via hit and trial.
