### ISSUE TITLE
External wiki link opens in new window/tab, external issue link does not

### ISSUE THREAD

**Issue by strk** [go-gitea/gitea#3216]
It's an inconsistency: the "wiki" tab link, when using external wiki, opens in a new tab/window, while the "issues" tab link, when using external issues, opens int the same tab/window.

\cc @geek1011 (just because I remember you contributed UI stuff, so betting on you :)

**Comment by lafriks** [comment]
I think both external should be opening on new window

**Comment by strk** [comment]
Or both be controlled by the same configuration setting ...

**Comment by strk** [comment]
Pull request ready for this: #3228 for 1.3 branch and and #3227 for master
