### ISSUE TITLE
when pushing multiple architecture and os of the same container package, the registry override image with the latest.

### ISSUE THREAD

**Issue by ArKam** [go-gitea/gitea#32170]
### Description

Hi team,

I was pushing a container to the container registry as a feature test, when I found out that the registry doesn't support storing a container image for different architecture using the same image name.

If you build an image for both, linux/arm64 and linux/x86_64 or windows/arm64 and windows/x86_64 and try to push each resulting image to the container registry, the latest build will override the previous package.

With docker hub or quay or ghcr, you can have the same URL: forge.domain.tld/owner/package:version that deliver container version depending on the client spec (arm/x86_64) in here, from my understanding and test so far, I'll have to create an image with a name that specify <image_name>-arm64 or <image_name>-x86_64. 

### Gitea Version

1.22.2

### Can you reproduce the bug on the Gitea demo site?

Yes

### Git Version

provided by gitea/gitea:1.22.2

### Operating System

linux

### How are you running Gitea?

Using kubernetes to deploy gitea/gitea:1.22.2 release.

### Database

PostgreSQL

**Comment by lunny** [comment]
Can you describe your commands to upload the images or workflow file?

**Comment by hiifong** [comment]
I guess you forgot to create a multi-arch manifest.
![img_v3_02gr_2c08eb2a-4d6e-48dc-bc93-3ddb277d104g](https://github.com/user-attachments/assets/9b6e5658-50ba-482b-bace-3841c81a38bc)

```shell
docker manifest create \
    {gitea.domain}/{owner}/{image}:latest \
    {gitea.domain}/{owner}/{image}:amd64 \
    {gitea.domain}/{owner}/{image}:arm64

docker manifest push {gitea.domain}/{owner}/{image}:latest
```

**Comment by hiifong** [comment]
Multi-architecture best practices: https://docs.docker.com/build/building/multi-platform/

**Comment by hiifong** [comment]
> I guess you forgot to create a multi-arch manifest. ![img_v3_02gr_2c08eb2a-4d6e-48dc-bc93-3ddb277d104g](https://private-user-images.githubusercontent.com/89133723/388200796-9b6e5658-50ba-482b-bace-3841c81a38bc.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxOTY5MjcsIm5iZiI6MTczMjE5NjYyNywicGF0aCI6Ii84OTEzMzcyMy8zODgyMDA3OTYtOWI2ZTU2NTgtNTBiYS00ODJiLWJhY2UtMzg0MWM4MWEzOGJjLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIxVDEzNDM0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjOTIxNzJjMDlhMmY1ZTdmNDQyZWUxODhhNjk5NzYxOTg4Mzc3ZGUzZDI4ODVjMTQ0YmUwZmJiOTgxZTc4NjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.DY6aZzvhDxlNPyUCPRX3-Sbbp00uYMYUalpxUUI5hBo)
> 
> ```shell
> docker manifest create \
>     {gitea.domain}/{owner}/{image}:latest \
>     {gitea.domain}/{owner}/{image}:amd64 \
>     {gitea.domain}/{owner}/{image}:arm64
> 
> docker manifest push {gitea.domain}/{owner}/{image}:latest
> ```

![Uploading image.png…]()
However, this method will add some tags,it doesn't really solve your problem.Therefore, I recommend that you use docker buildx to create multi-architecture images.
```bash
docker buildx create --use --name {image}
docker buildx build --platform linux/amd64,linux/arm64 -t {gitea.domain}/{owner}/{image}:latest . --push
```
