### ISSUE TITLE
Language created and you have been invited as Proofreader of [Irish_language](https://en.wikipedia.org/wiki/Irish_language). You are welcome to do contribute to languages.

### ISSUE THREAD

**Issue by aindriu80** [go-gitea/gitea#32171]
Language created and you have been invited as Proofreader of [Irish_language](https://en.wikipedia.org/wiki/Irish_language). You are welcome to do contribute to languages.

_Originally posted by @lunny in https://github.com/go-gitea/gitea/issues/31919#issuecomment-2308930002_
            
Hi there !

Irish has been translated 100% however there are no proof readers :).  Can you add me as a proof reader for Irish please :-

Irish :- 
https://crowdin.com/project/gitea/ga-IE

My Profile:-
https://crowdin.com/profile/aindriu80

![Screenshot from 2024-10-01 13-18-17](https://github.com/user-attachments/assets/4581c35a-8048-4c75-815c-75e610c40ead)

**Comment by techknowlogick** [comment]
Updated, thanks so much!
