### ISSUE TITLE
No avatar with ssh upload

### ISSUE THREAD

**Issue by bauermarkus** [go-gitea/gitea#32187]
### Description

Even a avatar via Gravatar is set, there is no avatar seen in the commit

It is a repo cloned from a old, other gitea instance

### Gitea Version

1.22.2

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![image](https://github.com/user-attachments/assets/d10c52f9-ab58-429a-84bc-d3d5672ecc2b)

### Operating System

Docker

### How are you running Gitea?

Docker

### Database

PostgreSQL

**Comment by techknowlogick** [comment]
the email associated with that commit may not have been added to your user account.

**Comment by lunny** [comment]
SSH just verify the user with the key pushed the commits, but the authors of these commits will not be considered by the pusher. They will be considered by email.

**Comment by bauermarkus** [comment]
Any change to add this?

**Comment by techknowlogick** [comment]
@bauermarkus you'll need to check the email that is attached to the commit, and confirm it is associated with your account.

**Comment by techknowlogick** [comment]
You can see the email attached to a commit by looking at the commit itself in your command line using `git log`, or by adding `.patch` to the end of the URL when looking at a specific commit.
