### ISSUE TITLE
Allow user name "admin" to be created

### ISSUE THREAD

**Issue by dacrudg** [go-gitea/gitea#32181]
### Description

auth.go:570:createUserInContext() [E] CreateUser: name is reserved [name: admin]

Why can't we create a user named admin? This causes issues with my SSO setup where I use "admin" across all services, so now Gitea breaks when I login with SSO it tries to create that user and fails.

### Gitea Version

1.19.0 and 1.22.2

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

Myself in docker

### Database

MySQL/MariaDB

**Comment by eeyrjmr** [comment]
There is a reserved list
https://github.com/go-gitea/gitea/blob/9fd8b2621fb6e25e5cce7a5b5b08a993a145bc78/models/user.go#L715

**Comment by lunny** [comment]
This user name was reserved because of the router conflicts. `/admin` now will display the administrator console. But maybe we can use `/-/admin` instead.

**Comment by dacrudg** [comment]
> This user name was reserved because of the router conflicts. `/admin` now will display the administrator console. But maybe we can use `/-/admin` instead.

That would be great! And much appreciated
