### ISSUE TITLE
Should add a custom actions for updating and scanning the dependency 

### ISSUE THREAD

**Issue by sundaram2021** [go-gitea/gitea#32195]
### Description

i am setting up the gitea repo locally on my windows os and ran the cmd "make backend"
pkg started installing and along the way it also installed some virus(trojan) with the dependency
and i have to remove that virus and stop the installation

### Gitea Version

latest

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

no

### Database

None

**Comment by lunny** [comment]
I think those are false alerts. We have dependencies scanning enabled in this repository.  Can you post which packages are considered virus?

**Comment by wxiaoguang** [comment]
Official document: Why does my virus-scanning software think my Go distribution or compiled binary is infected? https://go.dev/doc/faq#virus

**Comment by sundaram2021** [comment]
![image](https://github.com/user-attachments/assets/dc021a33-dbfe-49e0-83f6-7834b0c96ea2)

see this is the problem ..
and windows security does not allow to proceed with the installation 
and it considered as server threat by it

**Comment by wxiaoguang** [comment]
It is a false report https://go.dev/doc/faq#virus

And google more: 

https://www.reddit.com/r/golang/comments/1729tuc/my_programs_keep_getting_flagged_as_viruses/

https://github.com/golang/go/issues/55042

https://forum.golangbridge.org/t/my-compiled-exe-file-is-declared-as-a-virus/34038/2

**Comment by sundaram2021** [comment]
okay cool.
I will try once more and inform

thanks :)
