### ISSUE TITLE
Template Render Error in User Settings

### ISSUE THREAD

**Issue by vanduc2514** [go-gitea/gitea#32203]
### Description

I try to use this template https://github.com/go-gitea/gitea/blob/main/templates/user/settings/navbar.tmpl for my self-hosted instance but Gitea throws this error

```
Render failed, failed to render template: user/settings/account, error: template error: custom:user/settings/navbar:7:18 : executing "user/settings/navbar" at <$.UserDisabledFeatures.Contains>: wrong number of args for Contains: want 1 got 2
----------------------------------------------------------------------
		{{if not (and ($.UserDisabledFeatures.Contains "manage_credentials" "deletion") (not $.EnableNotifyMail))}}
		                ^
----------------------------------------------------------------------
```

### Gitea Version

1.22.2

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

I'm running Gitea from Docker

### Database

PostgreSQL

**Comment by lunny** [comment]
You need to use the right template. Your gitea is 1.22.2 but you are using a main branch template.

**Comment by vanduc2514** [comment]
@lunny Thanks for the feedback, I use the nightly build (1.23-dev)  and it works
