### ISSUE TITLE
Gitea only shows first line of commit message

### ISSUE THREAD

**Issue by klingtnet** [go-gitea/gitea#3221]
Gitea only shows the first line of my commit message.
Take for example this repository (https://git.klingt.net/alinz/klingt.net/commits/branch/master) there are a lot of commits with multiline messages but for all of them only the title is shown.
This is most probably a configuration issue but I couldn't find a solution so I decided to open this issue.

PS: I am using gitea 1.3.2 and my configuration template can be found [here](https://git.klingt.net/alinz/klingt.net/src/branch/master/roles/gitea/templates/app.ini.tmpl).

**Comment by lafriks** [comment]
This has been implemented in #2980 and will be in release 1.4.0
