### ISSUE TITLE
Helm CM-Push doesn't work

### ISSUE THREAD

**Issue by Demmtop** [go-gitea/gitea#32227]
### Description

Hi Guys,
I tried to push helm charts to gitea repository as described in gitea helm documentation. The curl command works. But using helm repo add and helm cm-push doesn't works. I get a error message "Error: 404: could not properly parse response JSON: 404 page not found".
What is the problem?

### Gitea Version

1.22.1

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

Gitea is deployed as Kubernetes POD and used an offical gitea image

### Database

MySQL/MariaDB

**Comment by KN4CK3R** [comment]
Could you please add some logs to show which endpoints the client tries to call?

**Comment by Demmtop** [comment]
This is the curl command:
`curl --user xxxx:edcxxxxxxx63d5 -X POST --upload-file ./gitea-runner-1.tgz http://gitea.demmtop.local/api/packages/demmtop-entwicklung/helm/api/charts
`
This over helm:
` helm repo add --username xxxx  --password edcaxxxxxxx63d5 --insecure-skip-tls-verify gitea http://gitea.demmtop.local/api/packages/demmtop-entwicklung/helm
`
`helm cm-push ./gitea-runner-1.tgz gitea`

**Comment by KN4CK3R** [comment]
Works for me without problems:
```shell
$ helm repo add --username kn4ck3r --password kn4ck3r gitea https://gitea.local:3000/api/packages/KN4CK3R/helm
"gitea" has been added to your repositories
$ helm cm-push ./gitea-10.4.1.tgz gitea
Pushing gitea-10.4.1.tgz to gitea...
Done.
```

**Comment by Demmtop** [comment]
Ok, but my Gitea server runs without https.

**Comment by Demmtop** [comment]
Ok. I found the problem. CM-Push has a problem when the ower of the package is an organisation. Why does it work with the curl command?

**Comment by KN4CK3R** [comment]
That works too but your uploading user may not have enough permissions to upload packages to the organziation.

```
$ helm repo add --username kn4ck3r --password kn4ck3r gitea_org https://gitea.local:3000/api/packages/TestOrg/helm
"gitea_org" has been added to your repositories
$ helm cm-push ./gitea-10.4.1.tgz gitea_org
Pushing gitea-10.4.1.tgz to gitea_org...
Done.
```

**Comment by Demmtop** [comment]
Ok, I change my token. And now it works. Thanks.
