### ISSUE TITLE
Webhook Does Not Fire For New Repo

### ISSUE THREAD

**Issue by muellert** [go-gitea/gitea#32225]
### Description

I just installed gitea-1.22.3, upgrading from gitea-1.22.2, which had the same problem.

This is a test installation which has an org where I set a web hook to talk to a test installation of Jenkins. One repo existed in this org before I added the webhook. Then I created another repo in the same org, assuming it would be covered by the same webhook.

When I commit to the older repo, the webhook triggers, but when I commit to the newer repo, nothing happens. I verified this behaviour in tcpdump, as I couldn't see any logs.

Expected behaviour: If a webhook is set on the org level, it should be triggered according to the configured events for all repos in that org.

### Gitea Version

1.22.3

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

2.39.5

### Operating System

Debian 12.7

### How are you running Gitea?

I am running a downloaded binary standalone, under systemd.

I have written an Ansible role that I am using to install gitea. An outdated version of that role is here on Github.

### Database

PostgreSQL

**Comment by lunny** [comment]
Can you check you chose the right `Event On`? You could choose `All Events`.

<img width="158" alt="图片" src="https://github.com/user-attachments/assets/cba2ff20-ebbd-4441-9423-809cf32d34f4">

**Comment by muellert** [comment]
It's set to "Push Events". I'll retry with "all events".

**Comment by lunny** [comment]
> It's set to "Push Events". I'll retry with "all events".

Yes, that's the problem. `Push Events` doesn't include `Repository created`.

**Comment by muellert** [comment]
That shouldn't matter, or should it? Once I push to the new repo, it's a "Push Event" and should imho trigger the webhook.

**Comment by lunny** [comment]
Do you configure special branches? I still cannot reproduce it.

**Comment by muellert** [comment]
Today, I also can't reproduce the problem.
