### ISSUE TITLE
Changes lost when updating title or comment and navigating

### ISSUE THREAD

**Issue by hakito** [go-gitea/gitea#32223]
### Description

When adding a new comment for an issue, the browser navigation is blocked with a warning that changes will be lost.

This warning does not occur when editing issue titles or when editing an existing comment.

### Gitea Version

1.22.3

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

Docker

### Database

None

**Comment by Lieslot** [comment]
can i take this issue?

**Comment by hakito** [comment]
Sure - I cannot work on this. I was just reporting it.
