### ISSUE TITLE
Keep merged PR info in hidden branch

### ISSUE THREAD

**Issue by lafriks** [go-gitea/gitea#3222]
To make merged PR commit tab more stable and consistent for each PR there should be hidden branch created same as github does it - `refs/pull/x/head`

**Comment by lafriks** [comment]
I noticed that we do actually already keep such hidden branch, so it just needs to be reused in merged PR to display diff/commits from it

**Comment by lunny** [comment]
@lafriks and should that another PR or will be in #3188 ?

**Comment by lafriks** [comment]
@lunny that should be another PR to not make #3188 even larger
