### ISSUE TITLE
`Show Stats` does nothing

### ISSUE THREAD

**Issue by kuraga** [go-gitea/gitea#32226]
### Screenshots

1. Go to https://demo.gitea.com/kuraga/test/pulls/3/files

![image](https://github.com/user-attachments/assets/cbe0c2f8-574c-4991-814d-ab150ce9d69a)

2. Click `...` (`Diff Options`).
3. Click `Show Stats`.
4. Nothing happened?

![image](https://github.com/user-attachments/assets/fc6c2118-0c1f-479e-bfcf-52a76f284e6c)

6. `Show Stats` went gray.
7. Click `Show Stats`.
8. Nothing happened?
9. Click `...` (`Diff Options`).
10. `Show Stats` didn't switch back from gray.

![image](https://github.com/user-attachments/assets/f427e043-76cf-4ba7-9415-4775864d51d3)

### Gitea Version

1.23.0+dev-534-gf4b8f6fc40

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

Calculate Linux (Gentoo-based)

### Browser Version

129.0.6668.89 (Official build), (64 bit)

**Comment by wxiaoguang** [comment]
It seems to be a regression bug in 1.23 (not in 1.22)

**Comment by wxiaoguang** [comment]
OK, not really a regression: 

* If the PR only contains one changed file, then the left tree & stats won't show
* If the PR only contains more than one changed files, then the left tree & stats will show

**Comment by kuraga** [comment]
...and non-un-highlighting `Show Stats`...

**Comment by wxiaoguang** [comment]
> ...and non-un-highlighting `Show Stats`...

Yup, that's another UI problem. Not only `Show Stats`, most items in a dropdrown which don't refresh the page would have the same problem.

**Comment by kuraga** [comment]
Thanks!
