### ISSUE TITLE
Missing redirects after mirroring new project

### ISSUE THREAD

**Issue by somera** [go-gitea/gitea#32231]
### Description

When you try to mirror new project it stay in this state

![image](https://github.com/user-attachments/assets/b64908d4-3a69-463a-bb65-e089cd41f232)

In 1.22.2 at the and the process was redirected to the mirrored project. Not happening now.

### Gitea Version

1.22.3

### Can you reproduce the bug on the Gitea demo site?

Yes

### Git Version

2.47.0

### Operating System

Ubuntu 22.04.5 LTS

### How are you running Gitea?

gitea-1.22.3-linux-amd64

### Database

PostgreSQL

**Comment by wxiaoguang** [comment]
Unable to reproduce (tried on 1.23 and 1.22)

The page gets correctly reloaded after the migration finishes.

**Comment by somera** [comment]
@wxiaoguang thx for testing. I mirrored yesterday ~10 projects and had the problem.

Today restart of all services and I can't reproduce it. I think this was perhaps an caching problem? I'm using an nginx as proxy. And after every release I build the frontend and than I put it to nexus.

I'm closing this issue.

**Comment by wxiaoguang** [comment]
Maybe related to cache, maybe related to your stable browser page.

Some URL paths have been changed in 1.22.3.
