### ISSUE TITLE
Strange action errors in mirrored projects?!

### ISSUE THREAD

**Issue by somera** [go-gitea/gitea#32232]
### Description

After update to 1.22.3 I see many of errors

![image](https://github.com/user-attachments/assets/b218c669-5ee7-4bd8-a778-44949c0ef8cc)

in many mirrored projects?!

And than I saw this

![image](https://github.com/user-attachments/assets/e3544d5d-8b7b-41b5-a8e8-22b2a484da30)

or

![image](https://github.com/user-attachments/assets/d81af016-5d1f-4797-80df-8833fbbcf29d)

or

![image](https://github.com/user-attachments/assets/df7319bd-bc81-4ab2-a178-c9b0ca9a40be)

or

![image](https://github.com/user-attachments/assets/cee9a4f7-deb2-47b0-8810-ff0ec6deefde)

What was activated with 1.22.3 release? What happens here?

### Gitea Version

1.22.3

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

2.47.0

### Operating System

Ubuntu 22.04.3 LTS x86_64

### How are you running Gitea?

gitea-1.22.3-linux-amd64

### Database

PostgreSQL

**Comment by somera** [comment]
I see that

![image](https://github.com/user-attachments/assets/fc1522f3-baf4-4ed4-8765-1ef2a72411f0)

are activated. I didn't activate it.

**Comment by somera** [comment]
How can I fix it?

I can't go over the whole list and do it manualy.

When I deacticate the Actions in one specific project than I see the error

![image](https://github.com/user-attachments/assets/d46f88f7-b0be-4ef9-892f-10af47a9dbee)

and when I click on the x I get 404 error.

**Comment by somera** [comment]
@lunny ?

**Comment by somera** [comment]
@lunny I see more and more mirrors with ...

![image](https://github.com/user-attachments/assets/15b4b3bd-588b-457f-abd8-9265da3eb89b)

**Comment by lunny** [comment]
I have no idea, maybe it's related to #32120 . @yp05327 @Zettat123

**Comment by Zettat123** [comment]
> I see that
> 
> ![image](https://private-user-images.githubusercontent.com/8334250/375352159-fc1522f3-baf4-4ed4-8765-1ef2a72411f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4NzIxMDUsIm5iZiI6MTcyODg3MTgwNSwicGF0aCI6Ii84MzM0MjUwLzM3NTM1MjE1OS1mYzE1MjJmMy1iYWY0LTRlZDQtODc2NS0xZWYyYTcyNDExZjAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTRUMDIxMDA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWViYjkzZjM2MWNjYjhhZDI5OTJhNGQ1YWYyYWQ5MmE4NzlkN2IyM2Y1NGQ1ZWI5NTI3OThkZThlZWFlZDc4MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.8nhqSiKmhkmoFZ-0KtC5p-wRE0DUf-EBQ7ouYOnmTPg)
> 
> are activated. But not for all mirror.
> 
> And I didn't activate it.

Do you mean that  the "Actions" unit of some repositories are automatically enabled after upgrading to v1.22.3? If so, I think this issue is not related to #32120. Did you upgrade from v1.22.2 to v1.22.3?

**Comment by somera** [comment]
Example

![image](https://github.com/user-attachments/assets/37a76ecd-723c-45c6-9985-b0cb8e250c77)

![image](https://github.com/user-attachments/assets/919c2540-8e20-4077-9c33-47ee91d43c71)

I didn't activate the Actions for all the affected projects.

![image](https://github.com/user-attachments/assets/64fd013f-c74d-45e2-a5c4-0ce346fd2800)

And the red x is now after upgrade to 1.22.3.

When I add new mirror, Actions are activated

![image](https://github.com/user-attachments/assets/4ae592ed-7b5e-4160-b892-92a1f53d3f6e)

- Should the Actions be activated or not? If yes, what happens here for mirrors? Why I see the whole failed old history?
- Why will be the red x shown for mirrors? Looks like an error, but why is this now in 1.22.3?
- How can I check in the database which projects are affected? Can remove the red x for affected projects?

**Comment by somera** [comment]
I compared 1.22.2 (older status) and 1.22.3 instances for same mirrors.

1.22.2 -> actions tab is not activated
1.22.3 -> actions tab is activated

**Comment by Zettat123** [comment]
> When I add new mirror, Actions are activated -> is this right? Was this activated in 1.22.2 too?

Yes. New repositories (including mirrors) created in versions after v1.22 will have "Actions" enabled by default. See #27482. However, I don't think repositories created before v1.22 will automatically enable "Actions" after upgrading. I'll do some testing to confirm.

---

There is a proposal to disable "Actions" for mirror repositories by default. I support this idea.
- #30350

**Comment by yp05327** [comment]
When does these jobs start being triggered?

I'm sorry I don't know the language in your screenshot.
![image](https://github.com/user-attachments/assets/3827f3a9-c200-41e4-8134-38ae736a0883)
Does this mean `last month`?

And when did you upgrade the instance?

If the jobs are triggered before the update, it make sense. And I think this means before the update, the action unit is already enabled. But you said, they are disabled before the update, and enabled after the update, which is strange. 
But if they are all triggered after the update, it means during the update, action units was enabled. Then it should be a bug or something is wrong from Gitea side.

**Comment by Zettat123** [comment]
> But if they are all triggered after the update, it means during the update, action units was forcibly enabled. Then it should be a bug or something was wrong from Gitea side.

This is where I suspect a bug exists. But I can't find any evidence that Gitea forcibly enabled the "Actions" unit.

**Comment by yp05327** [comment]
@Zettat123 
Yes. I think it is the point, so I asked, and then we can know what happened.

**Comment by somera** [comment]
> When does these jobs start being triggered?
> 
> I can see some of them, but I'm sorry I don't know the language in your screenshot. ![image](https://private-user-images.githubusercontent.com/18380374/376454273-3827f3a9-c200-41e4-8134-38ae736a0883.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5NzM0NDYsIm5iZiI6MTcyODk3MzE0NiwicGF0aCI6Ii8xODM4MDM3NC8zNzY0NTQyNzMtMzgyN2YzYTktYzIwMC00MWU0LTgxMzQtMzhhZTczNmEwODgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE1VDA2MTkwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjODA5ZmI4YjAwMzcxODI4MzExOTJhMTFmMTI3OTY1MjcxZWI2MTVhMDUwNjZkYzE4MmYxYmZjZjBjNzI2OGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.V61fSXlO2WGtNDfZCFN9DSn1KT5Y0NEOk2uI42KfFVw) Does this mean `last month`?

It's German. And it mean last month.

I'm wondering too, that I see this actions.

> 
> And when did you upgrade the instance?

~2 days aftrer 1.22.3 was released.

> If the jobs are triggered before the update, it make sense. And I think this means before the update, the action unit is already enabled. But you said, they are disabled before the update, and enabled after the update, which is strange. And I have no idea about it yet. But if they are all triggered after the update, it means during the update, action units was forcibly enabled. Then it should be a bug or something was wrong from Gitea side.

But i didn't enable any actions. I checked a lot of mirrors and most of them has no activated actions.

**Comment by somera** [comment]
This https://github.com/auth0/go-auth0 is an mirror.

2 months ago
![image](https://github.com/user-attachments/assets/cde75107-6324-4ac2-8670-4b559dcdf592)

And 1.22.3 was upgraded on 09.10.2024

![image](https://github.com/user-attachments/assets/ab37e953-02ed-4a36-9100-93b2e179a2cc)

**Comment by yp05327** [comment]
> And here othe mirror with activated action but wihout any errors

This is because the trigger of these 2 workflows are creating PR to main branch and workflow_dispatch (manually excute)

**Comment by yp05327** [comment]
So IMO, actually, there's no bug and the only thing you need is #30350

**Comment by Zettat123** [comment]
> > And here othe mirror with activated action but wihout any errors
> 
> This is because the trigger of these 2 workflows are creating PR to main branch and workflow_dispatch (manually excute)
> 
> ps: for @Zettat123, the workflow files: https://github.com/stanford-oval/storm/tree/main/.github/workflows

I see. Actually, the "Actions" unit was enabled for all repositories, but only some of them had actions runs due to workflow triggers.

**Comment by somera** [comment]
Will the patch make it like it was before or does something still need to be fixed in the database?

**Comment by yp05327** [comment]
In another way, it is not difficult to implement a new options when migrating the repo.
But how to handle these existing mirrors, adding a migration or a maintenance operation or doctor?

**Comment by Zettat123** [comment]
To batch disable the "Actions" unit of existing mirrors, users can use the API [PATCH
 /repos/{owner}/{repo}](https://gitea.com/api/swagger#/repository/repoEdit) to update repos.

**Comment by somera** [comment]
And today I see first system messages

![image](https://github.com/user-attachments/assets/36924910-e5cb-4bc5-9200-f3b7c4d4a70b)

I missing here info to the project.

```
2024/10/15 19:50:18 ...eb/routing/logger.go:102:func1() [I] router: completed GET /repo/search?sort=updated&order=desc&uid=1&team_id=undefined&q=&page=1&limit=15&mode=&archived=false for 192.168.178.21:0, 200 OK in 95.1ms @ repo/repo.go:556(repo.SearchRepo)
2024/10/15 19:50:22 ...ns/schedule_tasks.go:87:startTasks() [E] CreateScheduleTask: SetJob: yaml: line 15: did not find expected key
        /source/services/actions/schedule_tasks.go:87 (0x1ec5678)
        /source/services/actions/schedule_tasks.go:24 (0x25858bc)
        /source/services/cron/tasks_actions.go:63 (0x25858bd)
        /source/services/cron/tasks.go:111 (0x25824c7)
        /source/modules/graceful/manager.go:92 (0xaa9d26)
        /source/services/cron/tasks.go:88 (0x258223a)
        /source/services/cron/tasks.go:67 (0x2586d93)
        /usr/local/go/src/reflect/value.go:596 (0x4fccc5)
                Value.call: call(frametype, fn, stackArgs, uint32(frametype.Size()), uint32(abid.retOffset), uint32(frameSize), &regArgs)
        /usr/local/go/src/reflect/value.go:380 (0x4fbdd8)
                Value.Call: return v.call("Call", in)
        /go/pkg/mod/github.com/go-co-op/gocron@v1.37.0/gocron.go:122 (0x2563904)
        /go/pkg/mod/github.com/go-co-op/gocron@v1.37.0/executor.go:87 (0x2561b31)
        /go/pkg/mod/github.com/go-co-op/gocron@v1.37.0/executor.go:213 (0x2562817)
        /go/pkg/mod/github.com/go-co-op/gocron@v1.37.0/executor.go:269 (0x25632b7)
        /usr/local/go/src/runtime/asm_amd64.s:1695 (0x47b0a0)
                goexit: BYTE    $0x90   // NOP
```

**Comment by somera** [comment]
Same #30244

**Comment by somera** [comment]
Can I use this
```
; [actions]
;; Enable/Disable actions capabilities
;ENABLED = false
```
to disable action temporary?

And this
```
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Cleanup expired actions assets
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;[cron.cleanup_actions]
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;ENABLED = true
;RUN_AT_START = true
;SCHEDULE = @midnight
```
to cleanup all the action jobs?

**Comment by yp05327** [comment]
It is a global setting for all repos, if you do not need to use actions in this instance, you can disable it globally.

Clean up only remove action job log, related data and artififacts, it will not delete those action jobs.

**Comment by somera** [comment]
> It is a global setting for all repos, if you do not need to use actions in this instance, you can disable it globally.

Thx,

> Clean up only remove action job log, related data and artififacts, it will not delete those action jobs.

hm.

Are you working on a solution to this problem?

The failed action jobs are flooding my system messages view.

**Comment by yp05327** [comment]
For existing mirrors, no good solution from me.

As it is related to `repo_unit` table in DB.
If there's a record with unit type 10 (action), and it is not globally disabled, then it means action unit is enabled.
We can not simply remove these records in migration, as users may need it.
So we can only do it by ourselves (cli or sql) or add a new maintenance operations, but it is not a usually used feature I think, so  maybe there's no worth to implement it.

↑ It is for the action jobs

And the commit status (`x` in dashboard repo list) is recorded in another table, and if you don't want to see them, maybe you also need to clean it.

So, as a summary, I have no good idea now for completely solving it for these **existing mirrors**.

**Comment by somera** [comment]
Understand. Means I have fix it for ~20.000 mirrors by myself. Or I do

> To batch disable the "Actions" unit of existing mirrors, users can use the API [PATCH /repos/{owner}/{repo}](https://gitea.com/api/swagger#/repository/repoEdit) to update repos.

this with an script for all the mirrors?

I this case I should send **only** has_actions = false as an json? Right?

This will disable the action. And how can I than fix this

![image](https://github.com/user-attachments/assets/50e65338-5506-4b9d-b3f7-fd89c53b0aab)

?

**Comment by Zettat123** [comment]
> I this case I should send only has_actions = false as an json? Right?

Yes. 

https://github.com/go-gitea/gitea/blob/9116665e9c1c01d882c919fb3058f7fdb695350e/routers/api/v1/repo/repo.go#L1018-L1027

**Comment by somera** [comment]
@Zettat123 I did this for ~3500 mirrors. Looks good.

And what should be removed in th database to remove this

![image](https://github.com/user-attachments/assets/32c2b16e-1363-462e-b00f-a8816eecf74b)

?

This is visible after I set has_actions = false. And click on the x or o show 404.

**Comment by lunny** [comment]
I think these commit status can be removed manually from the database with
```
delete from commit_status where repo_id = (select id from repository where is_mirror = true)
delete from commit_status_summary where repo_id = (select id from repository where is_mirror = true)
```

**Comment by somera** [comment]
> > I this case I should send only has_actions = false as an json? Right?
> 
> Yes. You only need to set the fields that need to be changed.

I have now a script which I run after I added some new mirrors.

But for the next release there will be a fix in gitea? Means, when I import new mirror "Actions" will be deactivated by default?

> I think these commit status can be removed manually from the database with
> 
> ```
> delete from commit_status where repo_id = (select id from repository where is_mirror = true)
> delete from commit_status_summary where repo_id = (select id from repository where is_mirror = true)
> ```

Thx. I try this next weekend with an Gitea-DB backup.

**Comment by somera** [comment]
@lunny is there a fix in the next release that for new mirrors "Actions" will be not activated?

**Comment by lunny** [comment]
Yes, I think there should be a PR to fix that but there is no ETA

**Comment by somera** [comment]
@lunny looks good for me after update to 1.23.1. Thx.
