### ISSUE TITLE
"failed to get git config safe.directory" during setup

### ISSUE THREAD

**Issue by TheMcSebi** [go-gitea/gitea#32237]
### Description

Hello :) 
I tried to setup gitea locally on my windows machine for testing, but I encountered the following error during setup:

```
routers/init.go:73:mustInitCtx() [F] code.gitea.io/gitea/modules/git.InitFull(ctx) failed: failed to get git config safe.directory, err: exit status 6 - error: invalid pattern: *
 - error: invalid pattern: *
```
Below, I tried to find out where this error could come from
```
C:\Users\sebas>git config --get safe.directory
K:/dev/wikiextractor

C:\Users\sebas>git config --global --list
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
user.name=Sebastian
user.email=1323131+TheMcSebi@users.noreply.github.com
safe.directory=F:/xampp.old/htdocs/adrema
safe.directory=K:/AI/stable-diffusion-webui
safe.directory=K:/GitHub/rmmagent
safe.directory=K:/dev/wikiextractor

C:\Users\sebas>git --version
git version 2.43.0
```

with little success

### Gitea Version

1.22.3-gogit-windows-4.0-amd64

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/TheMcSebi/b42a342c39aa32e8b630aca5aac902ad

### Screenshots

![image](https://github.com/user-attachments/assets/8e4265ec-db35-4ce3-b145-268984cc3050)

### Git Version

2.43.0

### Operating System

Windows 11 23H2

### How are you running Gitea?

Downloaded the amd64 gogit exe from github, ran it from cmd using "gitea web"

### Database

PostgreSQL

**Comment by wxiaoguang** [comment]
It seems to be a git's bug.

Could you try git 2.43.4 and/or some latest git (2.47.0)?

**Comment by wxiaoguang** [comment]
More details:

1. Gitea uses its own git config (not the current user's)
2. Gitea tries to do `git config --global --get \*` to check whether the `safe.directory` is correctly configured.

**Comment by TheMcSebi** [comment]
Thank you, that solved the issue.  
Apparently I've unknowingly been using some git executable that came with devkitPro for ages.  
Thanks again for the quick support and your work on this great project!

**Comment by gek64** [comment]
> More details:
> 
> 1. Gitea uses its own git config (not the current user's)
> 2. Gitea tries to do `git config --global --get safe.directory \*` to check whether the `safe.directory` is correctly configured. The wildcard is escaped as a regexp.
> 
> Maybe Windows or GitForWindows doesn't handle the `\*` correctly.

[MSYS2](https://www.msys2.org/) git(v2.47.0)
[Git for Windows](https://git-scm.com/downloads/win) git(v2.47.0.windows.1),
after running `git config --global --get safe.directory \*`, both show `error: invalid pattern: *`

Using msys2's git, gitea cannot start after initialization, the error is `failed to get git config safe.directory, err: exit status 6 - error: invalid pattern: *`
Using Git for Windows, gitea works fine after initialization

**Comment by TheMcSebi** [comment]
I couldn't find anything related to this issue on the git-for-windows github issues.
Do you think it would be helpful if I created a bug report over there or if I create a pull request to the gitea docs repo to mention this dependency?

**Comment by lunny** [comment]
Maybe send an issue to git-for-windows is better according to https://github.com/go-gitea/gitea/issues/32237#issuecomment-2407943663.

**Comment by gek64** [comment]
> I couldn't find anything related to this issue on the git-for-windows github issues. Do you think it would be helpful if I created a bug report over there or if I create a pull request to the gitea docs repo to mention this dependency?

This maybe a problem with [git based on cygwin](https://packages.msys2.org/base/git) rather than [git-for-windows](https://github.com/git-for-windows), according to this [msys2 documentation](https://www.msys2.org/docs/git/)
