### ISSUE TITLE
Deleting diff comment lefts buttons toolbar

### ISSUE THREAD

**Issue by kuraga** [go-gitea/gitea#32258]
### Description

At the Pull request page,
at the `Files Changed` tab,
deleting a comment isn't  visually complete.

The buttons toolbar is left (see the screenshot).

### Screenshots

![image](https://github.com/user-attachments/assets/28519778-940e-46b5-b4f5-cae591b01f08)

### Gitea Version

1.23.0+dev-567-g9df5ddaf44

### Can you reproduce the bug on the Gitea demo site?

Yes

### Browser Version

129.0.6668.100 (Official build), (64 bit)

**Comment by cloudchamb3r** [comment]
It would be better to mention that to reproduce issue, the deletion of comment should be happen in conversation tab.

**Comment by kuraga** [comment]
Thanks!

**Comment by lunny** [comment]
Should this affect 1.22?

**Comment by cloudchamb3r** [comment]
@lunny maybe yes the error prone line was wrote 3 years ago
