### ISSUE TITLE
Artifacts get lost, when re-running old workflows

### ISSUE THREAD

**Issue by hakito** [go-gitea/gitea#32256]
### Description

I just tried to re-run a job that was executed 2 weeks ago. We have set `ARTIFACT_RETENTION_DAYS = 7` in the _actions_ section.

The build job actually says that artifact upload is succesful. But the next job, that tries to fetch the artifact fails:

```txt
Total number of files that will be downloaded: 540
A 500 response code has been received while attempting to download an artifact
Exponential backoff for retry #1. Waiting for 5[4](https://HIDDEN/actions/runs/860/jobs/1#jobstep-1-4)75 milliseconds before continuing the download
A 500 response code has been received while attempting to download an artifact
Exponential backoff for retry #1. Waiting for [5](https://HIDDEN/actions/runs/860/jobs/1#jobstep-1-5)482 milliseconds before continuing the download
```

I also tried downloading the artifact manually and get the error: 

> artifact not found

I also tried to delete the artifact manually in the web interface.  This also returns a 200 code for the `DELETE` request. However the artifact does not disappear.

Here a part of the response from the artifacts `GET` request after the deletion attempt:

```
{
    "artifacts": [
        {
            "name": "Bin.Unprotected",
            "size": 80032963,
            "status": "expired"
        }
    ]
}
```

### Gitea Version

1.22.3

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

docker

### Database

MySQL/MariaDB

**Comment by Zettat123** [comment]
We should improve the `CreateArtifact` function to support updating uploaded artifacts when re-running a job.

https://github.com/go-gitea/gitea/blob/5242e520c499bf72ec21a8df2dbdee825f98ed78/models/actions/artifact.go#L57-L82
