### ISSUE TITLE
Comment button should be disabled on uploading images..

### ISSUE THREAD

**Issue by sangcheol12** [go-gitea/gitea#32262]
## on uploading 
![스크린샷 2024-10-15 오후 1 09 16](https://github.com/user-attachments/assets/1ca032db-9098-43ab-bba4-e36e98a289ad)

## when submit on uploading
![스크린샷 2024-10-15 오후 1 09 59](https://github.com/user-attachments/assets/c1224dfe-bfa0-45b1-a3ba-270e6e928cf8)

### Gitea Version

1.23

### Can you reproduce the bug on the Gitea demo site?

Yes

### Browser Version

chorme 129.0.6668.100

**Comment by yp05327** [comment]
GitHub will disable the button when file is uploading.
I didn't even notice this. Good issue. 😄
