### ISSUE TITLE
History of repository name change seem to be weired.

### ISSUE THREAD

**Issue by cloudchamb3r** [go-gitea/gitea#32269]
### Description

I don't know this is intended feature but In the dashboard feed history, it always shows that the repository name has changed from `<old repo name>` to `<current repo name>`

I actually changed repository name like this.
```
reponame -> reponame1
reponame1 -> reponame2
reponame2 -> reponame3
```

but they always shows 
```
reponame -> reponame3
reponame1 -> reponame3
reponame2 -> reponame3
```

### Screenshots

<img width="843" alt="Screenshot 2024-10-15 at 10 00 32 PM" src="https://github.com/user-attachments/assets/29346f86-e106-48e3-aa44-42374992378b">

### Gitea Version

1.23

### Can you reproduce the bug on the Gitea demo site?

Yes

### Browser Version

Chrome 129.0.6668.58

**Comment by cloudchamb3r** [comment]
I also figured out current implementation does not considering about next old name, gitea dosen't saving about change history, just saving old names in `action` table.

**Comment by lunny** [comment]
This is a known issue. Duplicate of #18007
