### ISSUE TITLE
Create a file with too many lines from web ui will get `Invalid CSRF token.` error

### ISSUE THREAD

**Issue by yp05327** [go-gitea/gitea#32284]
### Description

Reproduce:
Create a new file in browser, then input some texts, and copy paste them, if there's several million lines, it maybe very slow, but you can click commit. then you will see `Invalid CSRF token.` error

### Gitea Version

latest

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

build

### Database

None

**Comment by yp05327** [comment]
error log:
![image](https://github.com/user-attachments/assets/124ed2df-ce54-47a8-894c-1272e45f18a7)

**Comment by wxiaoguang** [comment]
Well, does it make sense? If there were billions or even more of lines, your browser could also crash, your disk could be full-filled, your OS could stop responding, etc.

**Comment by yp05327** [comment]
I can not find out what happened, as the dev tools crashed. So, for recording it, I created this issue. 
Is it a way to improve or can we do something better. e.g. limit the max lines?

**Comment by wxiaoguang** [comment]
Most likely that the form is too big (or corrupted) then backend fails to parse it correctly to get csrf.

**Comment by wxiaoguang** [comment]
Most code in Gitea doesn't work with large form, because the default limit of a form size is 32M

![image](https://github.com/user-attachments/assets/70d4e545-f40f-4751-bf80-d374974a4df9)


![image](https://github.com/user-attachments/assets/1dfaa372-da7e-4c8e-bef0-85bef56f2808)

**Comment by wxiaoguang** [comment]
Anything need to keep this issue open?
