### ISSUE TITLE
Add support for Apple Secure Enclave-backed private keys (or potentially remove SSH key verification for self-hosted instances?)

### ISSUE THREAD

**Issue by kmanwar89** [go-gitea/gitea#32297]
### Feature Description

Gitea currently supports cloning repositories using HTTPS and SSH, however, SSH keys cannot be verified if the private key is stored in the Apple Secure Enclave microprocessor.  This is achieved using an application such as [secretive](https://github.com/maxgoedjen/secretive), which allows a user to create a private/public keypair within the Secure Enclave, and exposes the public key file path for configuration purposes.  This works for every other application I've used with it, including GitHub, but does not work for Gitea.

### Screenshots

Github key, for instance, as exposed through Secretive's UI:

<img width="770" alt="Screenshot 2024-10-20 at 10 37 48 AM" src="https://github.com/user-attachments/assets/c8848695-ed69-4c1d-b036-431871836324">

And as it exists within my GitHub account settings:

<img width="636" alt="Screenshot 2024-10-20 at 10 38 41 AM" src="https://github.com/user-attachments/assets/55659c88-d571-4814-929e-31b0155453ad">

Adding the same key to my Gitea instance, which requires me to verify the key:

<img width="1051" alt="Screenshot 2024-10-20 at 10 41 32 AM" src="https://github.com/user-attachments/assets/540e1b8d-9165-494e-b9e2-759d5e8aa1e7">

Attempting to verify results in an error, as it can't find the private key, since it is stored in the SecureEnclave, even though the Secretive app should handle that communication between apps via Apple's native API:

<img width="860" alt="image" src="https://github.com/user-attachments/assets/2ddc2cf5-be73-4e58-849b-750151736bd1">

**Comment by wxiaoguang** [comment]
If you would really like to try to "verify" (for fun), you could use the `ssh-keygen`'s `-U` option, to make it use IdentityAgent provided by `secretive` https://github.com/maxgoedjen/secretive/blob/main/APP_CONFIG.md

```
$ man ssh-keygen
...
     -U      When used in combination with -s or -Y sign, this option indicates that a CA key resides in a ssh-agent(1).  See the CERTIFICATES section for more information.
```
