### ISSUE TITLE
Diff not updated after merging chained pull requests

### ISSUE THREAD

**Issue by RobinMaub** [go-gitea/gitea#32301]
### Description

Hello,

I have several PR chained targeting the same branch, but when I merge the first ones, I expect the diff to be updated (because main has been updated). so the diff is "old" and not really relevant. Is it normal or a bug ? Known ?

### Gitea Version

1.22.3

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

Ubuntu

### How are you running Gitea?

systemd

### Database

None

**Comment by cloudchamb3r** [comment]
That's correct behaviour. To apply changes on main/upstream branch, you should merge/rebase feature branch with current remotes' HEAD.

**Comment by RobinMaub** [comment]
Ok. It looks weird to me (Gitlab does not react the same at least) but thanks for your answer !
