### ISSUE TITLE
Minor visual glitch with file icon in comments

### ISSUE THREAD

**Issue by KazzmanK** [go-gitea/gitea#32316]
### Description

If I have a post with file attached, while editing post attachment`s part have wrong file icon

After I exit edit mode icon becomes normal

### Screenshots

Edit post mode
![image](https://github.com/user-attachments/assets/f0b40caa-2b09-44d9-8ad3-937d9a4fb8c4)

View mode
![image](https://github.com/user-attachments/assets/f4db1280-3a53-471f-a53f-d71ae1a1330b)

### Gitea Version

1.22.3

### Can you reproduce the bug on the Gitea demo site?

No

### Browser Version

120

**Comment by lunny** [comment]
Can you reproduce this on demo site? It maybe related to your configuration.

**Comment by yp05327** [comment]
I can reproduce it, the image src is this attachment
![image](https://github.com/user-attachments/assets/93dc43d1-386b-47ff-9a8b-abbf57cfb381)

**Comment by yp05327** [comment]
Yes, if it is a image, it is correct.

**Comment by yp05327** [comment]
Maybe comes from:
![image](https://github.com/user-attachments/assets/fb041c19-fda9-4c8f-aec2-6dd9d1e82d5c)
