### ISSUE TITLE
Organization wide file search

### ISSUE THREAD

**Issue by sharpSteff** [go-gitea/gitea#32315]
### Feature Description

It would be great to have a orga-wide file search.

**Comment by lunny** [comment]
Please give more details.

**Comment by yp05327** [comment]
Similar: #26299

**Comment by lunny** [comment]
So that this one can be closed because of duplication.

**Comment by yp05327** [comment]
Did #32210 support it?

**Comment by lunny** [comment]
Yes. Let's close this one and move to #26299

**Comment by sharpSteff** [comment]
@lunny great I think that works for me. Looking forwar to 1.23.0
