### ISSUE TITLE
[Question] What Md Gitea is using?

### ISSUE THREAD

**Issue by mmarif4u** [go-gitea/gitea#3231]
Can we have the link to it for referencing from it.

**Comment by lafriks** [comment]
Gitea is using https://github.com/russross/blackfriday for makrdown processing

**Comment by mmarif4u** [comment]
I am trying to create a task list, which is not mentioned in the above URL. It do works somehow but adding the bullet to it.
```
- [ ] Migrate the remaining posts
```
![selection_001](https://user-images.githubusercontent.com/1280585/34152650-470b7f02-e4ea-11e7-9a66-b60f348a0986.png)

**Comment by modmew8** [comment]
GitHub assigns a css class to the ul- and li-elements, if a checkbox is present:

```
<ul class="contains-task-list">
  <li class="task-list-item">
    <input checked="" class="task-list-item-checkbox" disabled="" id="" type="checkbox">Text
  </li>
</ul>
```
- [ ] like this

And the css rules for task-list-item remove the bullets using `list-style-type: none;`.

This is necessary to preserve the bullets for unordered lists, that are not task-lists.

- like this

So the parser should assign styled classes in case of a present task-list. (GitHub style)

Another way would be the parent-selector in [Selectors Level 4](https://drafts.csswg.org/selectors-4/#relational), that could be used to select li-Elements containing input-checkboxes. There would be no changes on the html parser necessary this way - but this is not supported by browsers yet (but achieveable with js).

**Comment by lofidevops** [comment]
This issue is missing some keywords which would make it easier to find: markdown, commonmark
