### ISSUE TITLE
MergePullRequest fails to trigger action

### ISSUE THREAD

**Issue by Fratee** [go-gitea/gitea#32335]
### Description

When merging a pull request the related actions that should trigger on:

```yaml
on:
  pull_request:
    types: [review_requested]
```

do not start and the gitea instance throws the following error:

`[E] an error occurred while executing the MergePullRequest actions method: gitRepo.GetRefCommitID: object does not exist [id: 32e9eaa99d775bb8922a6ac354a2c9b3dcfe834b, rel_path: ]`

This was working fine on 1.22.1

### Gitea Version

1.22.2 and 1.22.3

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

2.46.0.windows.1

### Operating System

Windows 10

### How are you running Gitea?

Self hosted on Windows

### Database

None

**Comment by Zettat123** [comment]
The use of `gitRepo.GetRefCommitID` was introduced by #31875. But I cannot reproduce this issue. Could you provide some detailed steps to reproduce it?

**Comment by lunny** [comment]
Wouldn't this workflow be triggered only when some code review requested?

**Comment by Zettat123** [comment]
> Wouldn't this workflow be triggered only when some code review requested?

Yes. But this error occurs before detecting workflows.

**Comment by Fratee** [comment]
I have branch protection and the pull request has been reviewed before merging. The author of the pull request is merging from the gitea interface. 

I can share the repo settings and the pipeline trigger. Is this enough?

**Comment by Zettat123** [comment]
I'd like to know some details about that PR.

1. Was this PR created from a fork?
2. What merge style did you use?
3. Did you merge this PR successfully?
4. Can you reproduce the bug on your Gitea?

**Comment by Fratee** [comment]
1. No. From a branch in the same repository.
2. Merge with merge commit. 
3. Yes but every action connected to the pull merged event did not trigger. 
4. Yes, on my self hosted gitea. I've now reverted to 1.22.1 but I can make more tests if you need. For the demo website it takes more time as I need to register a runner also.

**Comment by Zettat123** [comment]
Are there any workflows that are triggered by other events (like "push")? Can these workflows be triggered properly?

**Comment by Fratee** [comment]
Just updated to [gitea-1.22.4-windows-4.0-amd64.exe](https://github.com/go-gitea/gitea/releases/download/v1.22.4/gitea-1.22.4-windows-4.0-amd64.exe)
This version has is working fine.

The issue is still present in the GoGit 1.22.4 version

**Comment by Zettat123** [comment]
> The issue is still present in the GoGit 1.22.4 version

Are the versions(1.22.2 and 1.22.3) where you encountered the error also GoGit versions?

**Comment by Fratee** [comment]
Yes, where gogit versions

**Comment by Zettat123** [comment]
I can reproduce this issue on the GoGit version so I think it's related to GoGit. I'll try to create a PR to fix it.
