### ISSUE TITLE
Negative number of repositories after transferring ownerships of repos

### ISSUE THREAD

**Issue by typeless** [go-gitea/gitea#3233]
- Gitea version (or commit ref):
Gitea Version: 1.1.0+893-gf94c1b3

- Git version:
git version 2.7.4

- Operating system:
Ubuntu 16.04.3 LTS

- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
![image](https://user-images.githubusercontent.com/2606021/34189745-00214a02-e578-11e7-96b4-d1df479f4918.png)

  - [ ] No
  - [ ] Not relevant

- Log gist:

## Description
I transferred 29 repositories to another organization and found the repo number of the team become -29.
...

## Screenshots
![image](https://user-images.githubusercontent.com/2606021/34156240-4fb33052-e4f7-11e7-8856-f28f62d1d676.png)

**Comment by lafriks** [comment]
You should probably upgrade to more up to date gitea version. Or try on try.gitea.io if you can reproduce it there

**Comment by typeless** [comment]
@lafriks It's actually newer than v1.3 (I pulled it from the master regularly). The shown version 1.10+803 is another known issue https://github.com/go-gitea/gitea/issues/3194. I'll try to reproduce it on try.gitea.io later or just investigate it by myself. (this is not an urgent issue so I'll put it in my low priority TODOs too).

**Comment by typeless** [comment]
Looks like try.gitea.io can reproduce the problem too. See the edited report.

**Comment by ethantkoenig** [comment]
@typeless Could you please provide detailed instructions for reproducing?

**Comment by ethantkoenig** [comment]
Never mind, was able to reproduce locally. Investigating now

**Comment by lunny** [comment]
resolved by #3241
