### ISSUE TITLE
Store UserName in cookie without remembering session

### ISSUE THREAD

**Issue by programmeroftheeve** [go-gitea/gitea#3234]
- Gitea version (or commit ref): NA
- Git version: NA
- Operating system: NA
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
  - [x] NA
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
Use cookie to store username without using said cookie to keep user logged as is currently done. This way a http-proxy can use the cookie to log people using the server.

**Comment by lafriks** [comment]
From security point of view that actually is not a very good idea
