### ISSUE TITLE
Github/Gitlab Pages

### ISSUE THREAD

**Issue by mgite** [go-gitea/gitea#32340]
### Feature Description

It's 2024 and we need alternative to Github/Gitlab Pages feature, which is as easy to use. Gitea tries to be like Github and it's actions are compatible but i do not understand why does it take for so long to have feature as useful as that.

https://docs.gitea.com/help/faq?_highlight=pages/help/faq#does-gitea-have-a-githubgitlab-pages-feature

**Comment by lunny** [comment]
Duplicate of #302. We will not embed the pages feature unless the possible security problem can be resolved.
