### ISSUE TITLE
500 HTTP Error on Every Repo Page Suddenly

### ISSUE THREAD

**Issue by HendyTurtle** [go-gitea/gitea#32356]
### Description

When I open every page on my Gitea today (localhost on my own Win11 computer)(Yes, Windows), suddenly every repo I visit there is a `500 http error`, but it worked before. The Gitea version is the same. 
Here is the screenshot:
![image](https://github.com/user-attachments/assets/c143cc63-59e4-4a01-a3d2-580468427325)

### Gitea Version

 1.22.2 built with GNU Make 4.3, go1.22.6 : bindata, sqlite, sqlite_unlock_notify

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![image](https://github.com/user-attachments/assets/c143cc63-59e4-4a01-a3d2-580468427325)

### Git Version

 2.46.0

### Operating System

Windows 11 23H2

### How are you running Gitea?

I am running it in a exe

### Database

SQLite

**Comment by wxiaoguang** [comment]
0xc0000142 " it's a general error code for when windows is unable to start the application correctly. "

Maybe your "git" command can't run correctly.

**Comment by HendyTurtle** [comment]
#### Thank You

It was working before, but the error just occured yesterday suddenly.
But now it's working again.
---
#### 谢谢！
以前还可以正常用，就昨天突然就这样了。
但今天现在又能用了。

**Comment by HendyTurtle** [comment]
#### Thank You
It was working before, but the error just occured yesterday suddenly.
But now it's working again.
---
#### 谢谢！
以前还可以正常用，就昨天突然就这样了。
但今天现在又能用了。
