### ISSUE TITLE
Link to the artifacts of the **latest** run?

### ISSUE THREAD

**Issue by noppelmax** [go-gitea/gitea#32350]
### Feature Description

Hi,

We would like to link to the latest artifact. There is a relatively straightforward way this could be done. Right now one can link a specific run like this:

https://<url>/<owner>/<repo>/actions/runs/<runid>/artifacts/output

But you need to know the latest run id. We suggest to allow <runid> to be "latest", referring to the last run. This would be very helpful not only in the README.md. We could use the link in any other app as well. 

A word on the context: We are mainly building latex papers and having a link to the latest version would be very helpful. 

What do you think?

Regards,
Max

**Comment by lunny** [comment]
Did you mean #31808 ?

**Comment by noppelmax** [comment]
Ah ja! Perfect. Thank you! Looking forward for 1.23.
