### ISSUE TITLE
Gitea Cloud front page doesn't load without hotjar tracking script

### ISSUE THREAD

**Issue by siikanen** [go-gitea/gitea#32366]
### Description

This is a heads up of tracking scripts that potentially brake your webpage.

I tried to create Gitea cloud instance to evaluate Gitea for our use cases. However the front page  (https://cloud.gitea.com/instances) of the cloud does not even load without the hotjar tracking scripts. They are blocked on network level and there's nothing I can change there. 

I can however access the site over other networks.

### Screenshots

![image](https://github.com/user-attachments/assets/d7655d21-9315-4a6e-84c7-f1ab2134fa0f)

### Gitea Version

latest cloud

### Can you reproduce the bug on the Gitea demo site?

No

### Browser Version

Firefox 132.0b2

**Comment by lunny** [comment]
Thank you for your report. We’ve noted this issue. However, this repository is specifically for tracking Gitea itself, so I’ll close this ticket. For further assistance, please feel free to reach out to us at support@gitea.com.
