### ISSUE TITLE
Gitea service panics when attempting to clone/pull 

### ISSUE THREAD

**Issue by eeyrjmr** [go-gitea/gitea#32367]
### Description

upon upgrading to gitea-1.22.3 (from 1.22.2) on windows, any clone/pull via git results in a 500 error.  The WebUI "mostly" still functions but does slow down. 
Closer examination of the logs shows a panic 

> 2024/10/29 10:34:07 ...rs/common/errpage.go:26:RenderPanicErrorPage() [E] PANIC: runtime error: invalid memory address or nil pointer dereference

since this was a MINOR bump, the service was "downgraded" to 1.22.2.
gitea-1.22.3-windows-4.0-amd64.exe  and gitea-1.22.3-gogit-windows-4.0-amd64.exe were both tried and both exhibit the same issue 

### Gitea Version

1.22.3

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

https://gist.github.com/eeyrjmr/a4eb1e5e159a71fc6152210fb030f2c3

### Git Version

2.46.1

### Operating System

Windows

### How are you running Gitea?

Windows service 

### Database

MySQL/MariaDB

**Comment by wxiaoguang** [comment]
Regression of Don't init singing keys if oauth2 provider disabled (#32177)
