### ISSUE TITLE
[BUG]  error 'undefined: user.Search' on Docker build

### ISSUE THREAD

**Issue by SSP6904** [go-gitea/gitea#32376]
### Description

I'm getting an error message when attempting to build my forked version of Gitea, when it outputs an error right after grabbing the needed packages. Can someone explain this to me?

Output:

```
3084.2 routers/web/web.go:674:43: undefined: user.Search
```

### Gitea Version

unknown

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

Ubuntu

### How are you running Gitea?

Docker compose

### Database

MSSQL

**Comment by lunny** [comment]
Looks like the problem comes from the forked repository?

**Comment by SSP6904** [comment]
Most likely, yes.
