### ISSUE TITLE
Introduce New Canceled Status for Cancelled Actions

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#32386]
### Feature Description

When canceling an action, it will get the status Failed.
I would like to suggest that cancelled workflow runs will get their own "Canceled" status.

### Screenshots

I canceled the workflow run:
<img width="1355" alt="canceled" src="https://github.com/user-attachments/assets/011a9a46-174a-43ea-956e-73d10166341d">

It has the status failed.
<img width="992" alt="failed-filter" src="https://github.com/user-attachments/assets/2d0da1e5-e2cd-48a3-84b0-1f016ec50705">

**Comment by wxiaoguang** [comment]
Fixed by  Fix incomplete Actions status aggregations #32859
