### ISSUE TITLE
Unable to do some S3 download when using CloudFlare R2

### ISSUE THREAD

**Issue by l0u1sg** [go-gitea/gitea#32407]
### Description

Some elements no longer work when using Cloudflare R2. For example, organization icons no longer load, and we can no longer download repository archives. However, LFS storage works very well, and we can download LFS files correctly. Apparently, this is due to headers that aren't being processed.

### Gitea Version

1.22.0

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/l0u1sg/35b98653025f2cc975656ad29e4c2015

### Screenshots

![image](https://github.com/user-attachments/assets/6c91ddb8-1918-4c27-8ad7-c279e857184a)

### How are you running Gitea?

Gitea is running on Docker behind a reverse proxy

### Database

SQLite

**Comment by Zettat123** [comment]
Please add `MINIO_CHECKSUM_ALGORITHM = md5` to your configuration file.

![image](https://github.com/user-attachments/assets/759dab85-2aa2-4297-a61c-edd779b2ed2a)

See:
- https://github.com/go-gitea/gitea/pull/23768

**Comment by l0u1sg** [comment]
Oh thanks, i didn't see this option in the gitea documentation. It solve my issue.
