### ISSUE TITLE
Issue editing doesn't work

### ISSUE THREAD

**Issue by stuzer05** [go-gitea/gitea#32437]
### Description

When editing issue and pr, save button doesn't work. No errors, nothing

### Gitea Version

1.23.0+dev-623-g41b4ef825d

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

Docker

### Database

None

**Comment by wxiaoguang** [comment]
oops, I think I know the reason, will propose a fix

**Comment by wxiaoguang** [comment]
Maybe this could fix:  Correctly query the primary button in a form #32438
