### ISSUE TITLE
Gitea subdir / subpath reverse proxy almost worked, but slightly bugged.

### ISSUE THREAD

**Issue by AzulEterno** [go-gitea/gitea#32446]
### Description

Gitea subpath worked almost perfectly. But still has several bugs. First it's that you have to add a "/" at the end of reverse proxy egine url. That will cause some inconsistency. Second is /login/oauth cannot get correct result since default login url it's not subdirred like "/gitea/login/oauth". I tried to use 301 to redirect all /login/ to /gitea/login, it showed login succeed but never passed back to local program. Any idea how to fix it?

### Gitea Version

1.12.2

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

![image](https://github.com/user-attachments/assets/f092a752-e201-44cc-8463-09991ffede8b)

### How are you running Gitea?

Offical version inside docker.

### Database

PostgreSQL

**Comment by wxiaoguang** [comment]
1. the trailing slash: please correctly setup your reverse proxy https://docs.gitea.com/next/administration/reverse-proxies#nginx-with-a-sub-path
2. see this #31974
