### ISSUE TITLE
Why the height is too long

### ISSUE THREAD

**Issue by MINDOU520** [go-gitea/gitea#32454]
### Gitea Version

gitea-1.22.3-windows-4.0-386

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

![20241108193213](https://github.com/user-attachments/assets/b3687057-c8af-47aa-9b3d-4e8aa09d0f33)

### Git Version

Git-2.47.0.2-64-bit

### Operating System

Win11

### How are you running Gitea?

When I deploy Gitea on a local network in win11, other computers accessing the repository page with the Edge browser see overly long interface elements.

### Database

SQLite

**Comment by lunny** [comment]
What's the Edge browser's version?

**Comment by MINDOU520** [comment]
> What's the Edge browser's version?Edge 浏览器的版本是什么？

edge version 84.0.522.52

**Comment by MINDOU520** [comment]
> What's the Edge browser's version?

Updating the Edge browser resolved the issue; everything displays correctly now
