### ISSUE TITLE
Spurious dangling git lock files

### ISSUE THREAD

**Issue by bsofiato** [go-gitea/gitea#32456]
### Description

Sorry if this is still on your radar (I've searched the issues but found nothing related).

I've had some issues with some mirrors that fail to sync. By checking the Gitea alerts, I found that some repositories have dangling locks (see screenshot attached). 

![image](https://github.com/user-attachments/assets/e8328bb2-85fe-40d7-8fc9-1ecd35307fbb)

It seems that the issue arises when git processes terminate abruptly. I wrote a script that cleans those dangling locks, but I wonder if Gitea itself should do it (maybe some cronjob that runs from time to time). If you guys think it would be helpful, I can submit a PR.

P.S. Sorry in advance if Gitea already does that. I tried looking into the source code but found nothing relevant (I'm not an expert on Git's plumbing commands).

P.S. I don't know if this is a particular issue of my environment, still, I feel that eventually, git processes will end unexpectedly.

### Gitea Version

1.22.2

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

I run a custom built docker image of gitea based on version 1.22.2

### Database

PostgreSQL

**Comment by lunny** [comment]
Similiar as #22578

**Comment by bsofiato** [comment]
> Similiar as #22578

@lunny Cool. I'm gonna close this one and use the other :) thanks for the reply
