### ISSUE TITLE
Broken padding in issue/pr sidebar

### ISSUE THREAD

**Issue by stuzer05** [go-gitea/gitea#32453]
### Description

![image](https://github.com/user-attachments/assets/1fed2c29-126a-4c1b-8cdc-bdebb2a52c9c)

### Gitea Version

1.23.0+dev-635-g0f397ae09b

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

docker

### Database

None

**Comment by wxiaoguang** [comment]
Thank you for catching it. Maybe it is related to " Split issue sidebar into small templates #32444 ", will take a look and continue improving the sidebar.

**Comment by wxiaoguang** [comment]
-> Fix issue sidebar #32455
