### ISSUE TITLE
Please disable pprof HTTP listener of vendored TiDB

### ISSUE THREAD

**Issue by fawick** [go-gitea/gitea#3245]
/cc @tboerger @lunny

- Gitea version (or commit ref):
v1.3.2 (and still in master)
- Git version:
git version 2.15.1 (not relevant)
- Operating system:
linux/amd64
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:
  Not relevant
## Description

The vendored `github.com/pingcap/tidb` package sets up a own HTTP listener at localhost:8888. (see https://github.com/go-gitea/gitea/blob/bdf18560110ac642c196054be38729760a4bbc39/vendor/github.com/pingcap/tidb/tidb.go#L293-L295). 

Mind you, the variable in the quoted code lines is a different `EnablePprof` than `github.com/go-gitea/gitea/modules/settings.EnablePprof`!

~~I'd suggest to either combine the PPROF instances of TiDB and Gitea, or disable the TiDB one completely by setting `github.com/pingcap/tidb.EnablePprof` to `false`.~~
**(EDIT: That's not going work, as the lines in question are run during `tidb` package initialization, already.)** 

## Screenshots

(no screenshots)

**Comment by fawick** [comment]
For other Gitea users: For the currently vendored version of TiDB, set `TIDB_PPROF=0` in your gitea environment to prevent the additional HTTP listener on `localhost:8888` from being opened.

**Comment by tboerger** [comment]
This should be handled by TiDB, it's pretty crappy that they enable it by default...

**Comment by fawick** [comment]
It was handled by TiDB. The version vendored in Gitea does not have those changes, yet.

**Comment by fawick** [comment]
@tboerger: TiDB handled it in this PR: https://github.com/pingcap/tidb/pull/1541

That PR is older than the commit that added TiDB to Gitea (via go-xorm, I guess.)

**Comment by lunny** [comment]
Maybe we need to update tidb vendor

**Comment by tboerger** [comment]
Than some maintainer should update the dependencies.

**Comment by techknowlogick** [comment]
tidb now removed. Closing this issue.
