### ISSUE TITLE
Enale delete branch when requesting merge PR after successful build

### ISSUE THREAD

**Issue by stuzer05** [go-gitea/gitea#32466]
### Feature Description

There is an option in repo to delete PR branch by default when merging PR. Make this option also available when requesting auto-merge on successful checks

### Screenshots

![image](https://github.com/user-attachments/assets/cb056941-306d-41f8-b870-ef09608e5f85)
![image](https://github.com/user-attachments/assets/b44b5124-7d44-4ca2-bcd6-29b67da64410)

**Comment by lunny** [comment]
#32343
