### ISSUE TITLE
Repository Release 500 Error

### ISSUE THREAD

**Issue by House-Men** [go-gitea/gitea#32463]
### Description

When core.edito is not configured in .gitconfig, the release version reports the following error
```
CreateRelease, exit status 1 - error: Terminal is dumb, but EDITOR unset
Please supply the message using either -m or -F option.
 - error: Terminal is dumb, but EDITOR unset
Please supply the message using either -m or -F option.
```
.gitconfig configures core.edito=nano, and the released version reports the following error
```
CreateRelease, exit status 1 - Too many errors from stdin
error: There was a problem with the editor 'nano'.
Please supply the message using either -m or -F option.
 - Too many errors from stdin
error: There was a problem with the editor 'nano'.
Please supply the message using either -m or -F option.
```
.gitconfig configure core.edito=vim, release version POST URL "https://[host]/[organize]/[repository]/releases/new" infinite wait
```
root@test:~# ps aux | grep vim
git       199487  0.1  0.0  11088  8804 ?        S    13:53   0:00 /usr/bin/vim /var/lib/gitea/data/gitea-repositories/[organize]/[repository].git/TAG_EDITMSG
root@test:~# kill 199487
```
After kill vim pid
```
CreateRelease, exit status 1 - Vim: Warning: Output is not to a terminal
Vim: Warning: Input is not from a terminal

Press ENTER or type command to continueerror: vim died of signal 9
error: There was a problem with the editor 'vim'.
Please supply the message using either -m or -F option.
 - Vim: Warning: Output is not to a terminal
Vim: Warning: Input is not from a terminal

Press ENTER or type command to continueerror: vim died of signal 9
error: There was a problem with the editor 'vim'.
Please supply the message using either -m or -F option.
```

### Gitea Version

Gitea version 1.22.3 built with GNU Make 4.3, go1.22.8 : bindata, sqlite, sqlite_unlock_notify

### Can you reproduce the bug on the Gitea demo site?

Yes

### Git Version

git version 2.30.2

### Operating System

Debian 11(Linux 5.10.0-26-amd64 #1 SMP Debian 5.10.197-1 x86_64 GNU/Linux)

### How are you running Gitea?

Binary Download：https://dl.gitea.com/gitea/1.22.3/gitea-1.22.3-linux-amd64
Using systemd Running：https://github.com/go-gitea/gitea/blob/release/v1.22/contrib/systemd/gitea.service

### Database

PostgreSQL

**Comment by wxiaoguang** [comment]
It is not related to "EDITOR" or `core.editor` (do not set them)


The problem seems to be that the git command used to create the tag is not valid.

**Comment by wxiaoguang** [comment]
What's the "git" command when "create release"?

You could figure it out by either way:

1. Still set the "core.editor", when the editor process hangs, check its parent process to see the git command
2. Enable debug logs to see the git commands

I guess there is something wrong with you git command (mixed version? wrapped shell?)

**Comment by House-Men** [comment]
@wxiaoguang After commenting tag.gpgsign = true, everything works fine.

**Comment by wxiaoguang** [comment]
Glad to hear it it works.

Most Gitea's git config options should only be managed by Gitea itself
