### ISSUE TITLE
MariaDb: Slow Sql Query from notification table

### ISSUE THREAD

**Issue by sebastian-sauer** [go-gitea/gitea#32491]
### Description

We get nearly every 30seconds the following slow query log in our log files:

`...ties/notification.go:296:GetUIDsAndNotificationCounts() [W] [Slow SQL Query] SELECT user_id, sum(case when status= ? then 1 else 0 end) AS count FROM notification WHERE user_id IN (SELECT user_id FROM notification WHERE updated_unix >= ? AND updated_unix < ?) GROUP BY user_id [1 1731479575 1731479585] - 8.191264092s`

### Gitea Version

1.22.3

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

Binary

### Database

MySQL/MariaDB

**Comment by lunny** [comment]
Duplicate of #32390 and resolved by #32395

**Comment by sebastian-sauer** [comment]
Yes - i can confirm that the index mentioned in the PR solves the problem. 
Thanks
