### ISSUE TITLE
Failed to verify user: user does not exist [uid: 0, name: OAUTH_USER]

### ISSUE THREAD

**Issue by sebastian-sauer** [go-gitea/gitea#32490]
### Description

Analysing our gitea log files we see a lot of the following log messages:

`routers/web/web.go:121:func9() [E] Failed to verify user: user does not exist [uid: 0, name: OAUTH_USER]`

It looks like this is a log in web.go: 

[log.Error("Failed to verify user: %v", err)](https://github.com/go-gitea/gitea/blob/840ad7eefe2b49ab453b9a89b153a264a8c9f8a2/routers/web/web.go#L120-L121)

Having an error in the logs for every wrong auth attempt could explode the log files and hide other important messages.

Additional question: is the OAUTH_USER a special user? 

### Gitea Version

1.22.3

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

Binary + MariaDb

### Database

MySQL/MariaDB

**Comment by wxiaoguang** [comment]
What are the logs around it? Is there any one trying to use "OAUTH_USER" as user name to try to login?
