### ISSUE TITLE
[proposal] PR: scroll back to resolved conversation

### ISSUE THREAD

**Issue by XonqNopp** [go-gitea/gitea#32493]
### Feature Description

Sometimes PR can get huge. In all the activity, I find it great that when I post a new comment (be it in a review conversation or not), I directly come back to it once it has loaded the page, no need to scroll to find it.

However, when I go through all the conversations to see if I can resolve, every time I click on "resolve conversation" the page loads and I am back on top. I have to scroll my way through the page to find back the spot I was at. It would be very nice if we could be back at the location of the conversation after clicking on "resolve" (and the conversation being still hidden, not sure how achievable it is).

**Comment by jpraet** [comment]
What gitea version? Normally there should be no page reload when resolving a conversation since #28654.
