### ISSUE TITLE
Floccus sync breaks when logging into gitea web

### ISSUE THREAD

**Issue by Hr46ph** [go-gitea/gitea#32503]
### Description

I use Floccus addon in Ungoogled Chromium to sync bookmarks. I use git over https to my gitea deployment. For Floccus I created a new user and a personal repo that I can use. When I open a new tab and login with my own account to gitea web, Floccus addon is throws an error 404 page not found. I tried in Chromium and Google Chrome and I tested Floccus with Gitlab on all three browsers, and its only using Gitea that this happens.

I suspect its how Gitea web creates cookies. I have contacted the Floccus dev and he ensures me that Floccus does not share anything with sessions of the browsers. I think addons should be sandboxed that way.

### Gitea Version

1.22.3

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

macOS 15.1 Apple Silicon.

### How are you running Gitea?

Gitea is deployed using Helm on Kubernetes with redis and external postgres database.

### Database

PostgreSQL

**Comment by KN4CK3R** [comment]
Works without problems.
![grafik](https://github.com/user-attachments/assets/3928db06-af05-43ab-b752-dbb1f70be6b2)

**Comment by Hr46ph** [comment]
I’m not sure what the screenshot proves. I can replicate the issue 100% on different OS’es. 

The issue lies in using a different account for Floccus than the tab you login into Gitea with. When I switch to two different accounts on Gitlab it works fine.

when I login into a tab with the same account as I use for Floccus there is no issue obviously. 

I’ll be happy to provide more info if you’re willing to make more sense than just a screenshot.

**Comment by KN4CK3R** [comment]
Now I understand what your problem is. For historical reasons gitea supports session auth for the git web endpoints. Therefore the plugin indirectly uses the session of the current logged in user. I can't say if this will change in the near future but I don't think so.

**Comment by Hr46ph** [comment]
Right, ok. Not much else I can do then :).

Thanks for having a look at it. I'll look at other ways to use Floccus or another solution alltogether.
