### ISSUE TITLE
升级后web无法查看别的分支

### ISSUE THREAD

**Issue by xxzj990** [go-gitea/gitea#32517]
### Description

使用的docker版本，从1.17.3升级到1.22.3。
在web端查看分支只能看到默认分支，无法选择别的分支。

如截图所示，点击红色方框后只显示main分支，其实还有一个2.0的分支。

### Gitea Version

1.22.3

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![微信截图_20241115112822](https://github.com/user-attachments/assets/c7bbacac-b61b-4a55-8957-5e1186b03c39)

### Git Version

 2.45.2

### Operating System

unraid 6.9.1

### How are you running Gitea?

Docker 19.03.14

### Database

SQLite

**Comment by lunny** [comment]
Please speak in English.

Run sync branches from the admin panel UI.

![图片](https://github.com/user-attachments/assets/98a5841c-2a35-4c60-be05-f29b70624c22)
