### ISSUE TITLE
[UI] Merge the info in issue/pr for extra space 

### ISSUE THREAD

**Issue by mmarif4u** [go-gitea/gitea#3252]
Just a UI recommendation to merge the common things assigned to issue/pr like lables in on one lineers.

![selection_004](https://user-images.githubusercontent.com/1280585/34287705-f10d84e2-e723-11e7-8c4f-ae945898eaf4.png)
 
**Example:** mmarif added `ui` `server` `critical` label(s) 45 seconds ago

**Comment by lunny** [comment]
Duplicated of #834
