### ISSUE TITLE
The newline break is missing in Issue content

### ISSUE THREAD

**Issue by zjjhot** [go-gitea/gitea#32521]
### Description

The newline break is missing in Issue content ， for example 

--------------------
edit(OK):
1
2
3

preview tab (OK):
1
2
3

actual web page display as (newline break is missing) :
123
--------------------------

also see below

---------------------------
edit(OK):
```
> 1
> 2
> 3
```
preview(OK with quote block):
| 1
| 2
| 3

actual web page display as (newline break is missing) :
| 123

---------------------------

### Gitea Version

main branch

### Can you reproduce the bug on the Gitea demo site?

Yes

### Git Version

main branch

### Operating System

windows

### How are you running Gitea?

windows with ms sql server

### Database

SQLite

**Comment by lunny** [comment]
Regression from #32492

**Comment by wxiaoguang** [comment]
Will fix it

**Comment by wxiaoguang** [comment]
Let's try this:  Improve markdown rendering #32522

**Comment by wxiaoguang** [comment]
1.23 nightly is ready, could you take a try?

ps: before 1.23 frozen, there will be some more refactorings to the render system to make it maintainable and secure. if there is any regression, feel free to open an issue and I will fix them ASAP.
