### ISSUE TITLE
PANIC whilst trying to do migrate task

### ISSUE THREAD

**Issue by akaibukai** [go-gitea/gitea#32538]
### Description

Hello,
I'm running a fresh Gitea instance (latest 1.22.3 as of today with no repository at all yet as it's a new instance).

I wanted to mirror a Github repository (private).

As you can see below on the screenshot, I'm getting the following error:
`PANIC whilst trying to do migrate task: runtime error: index out of range [2] with length 2`

I have no clue about how to resolve this.

FWIW, The PAT token I'm using from Github is a classic one with everything checked (just to be sure it's not a permission issue).

According to older similar issues, this kind of error was supposed to be fixed from earlier versions already.

I'm ready to provide more information but right now I'm not sure what can be useful to share.

Thanks.

### Gitea Version

1.22.3

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![image](https://github.com/user-attachments/assets/fb5b4e81-10e2-4600-8ec4-3e92ad912cfc)
![image](https://github.com/user-attachments/assets/c25ea131-bb1a-4904-a92d-5f92f0f52bb9)

### How are you running Gitea?

I'm running Gitea using docker-compose.

### Database

PostgreSQL

**Comment by akaibukai** [comment]
Okay my bad! I made a typo on the repository address 🤦‍♂️

**Comment by lunny** [comment]
Can you paste the stack trace here from the log file or console?
