### ISSUE TITLE
[suggestion] "New Repository" on organization profile should default to current profile as owner

### ISSUE THREAD

**Issue by mqudsi** [go-gitea/gitea#3253]
When viewing an organization's homepage (e.g. `http://gitea/org/acme/dashboard`), and then using the "new repository" link in the menu bar up top, the default value of the "owner" field should be the organization that you were viewing (in this case, `acme`) and not the logged-in user, presuming the user has permissions/rights to do so for the current organization.

(Alternatively, a separate "Add repository" link could be added to the organization dashboard somewhere to create a new repository with the "owner" field defaulting to the currently-navigated organization.)

**Comment by mqudsi** [comment]
Can a contributor please mark this as confirmed? It's bitten me (and my colleagues) a number of times, creating a personal repo instead of a shared repo as a result. (Note that github implements the desired behavior described.)

**Comment by zeripath** [comment]
OK I'm looking at this. There are a number of problems with the dashboard...

**Comment by zeripath** [comment]
`/api/v1/repos/search?uid={{ORG_ID}}&q=&limit=15&mode=` doesn't give the same results as the `/{{ORG_NAME}}` profile page.
