### ISSUE TITLE
Voting for new owners between 2018/1/1 ~ 2018/12/31

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#3255]
As the description on our [CONTRIBUTING](https://github.com/go-gitea/gitea/blob/master/CONTRIBUTING.md#owners), the Gitea community has an election every year for owners. Only maintainers could be elected and if somebody don't want to be elected please send comment following this thread. And also, only maintainers could send his votes. Every maintainer could send 3 or less than 3 votes to other maintainers on the following comments and he cannot send the votes to himself. The voting is available from now to 2017/12/31.

**If you are not a maintainer of gitea, please don't send any comment here and if you do that the comment will be deleted. Speak to us on discord if you have any idea about the community election.**

**Comment by lafriks** [comment]
Voting for @lunny @bkcsoft @ethantkoenig

**Comment by strk** [comment]
Voting for @lunny @lafriks @ethantkoenig

**Comment by tboerger** [comment]
Voting for @lunny @bkcsoft @appleboy

**Comment by bkcsoft** [comment]
Voting for @lunny @appleboy @lafriks

**Comment by techknowlogick** [comment]
Voting for @lunny @lafriks @bkcsoft

**Comment by appleboy** [comment]
Voting for @lunny @bkcsoft @lafriks

**Comment by ethantkoenig** [comment]
Voting for @lunny @lafriks @bkcsoft

**Comment by Bwko** [comment]
Voting for @lunny @lafriks @bkcsoft

**Comment by sapk** [comment]
Voting for @lunny @lafriks @ethantkoenig

**Comment by makhov** [comment]
Voting for @lunny @bkcsoft @ethantkoenig

**Comment by pgaskin** [comment]
Voting for @lunny @lafriks  @ethantkoenig

**Comment by DblK** [comment]
Voting for @lunny @bkcsoft @ethantkoenig

**Comment by cez81** [comment]
Voting for @lunny @lafriks @ethantkoenig

**Comment by thibaultmeyer** [comment]
Voting for @bkcsoft @lunny @ethantkoenig

**Comment by daviian** [comment]
Voting for @lunny @lafriks @bkcsoft

**Comment by Morlinest** [comment]
Voting for @lunny @lafriks @ethantkoenig

**Comment by metalmatze** [comment]
Voting for @lunny @bkcsoft @appleboy

**Comment by andreynering** [comment]
Voting for @lunny @lafriks @ethantkoenig

**Comment by fuxiaohei** [comment]
Voting for  @lunny @lafriks @bkcsoft

**Comment by lunny** [comment]
Voting for @bkcsoft @lafriks @appleboy

**Comment by lunny** [comment]
20 maintainers voting, the results below:
@lunny 19
@lafriks 14
@bkcsoft 13
@ethantkoenig 10
@appleboy 4

So the new year owners are @lunny,  @lafriks and @bkcsoft .

**Comment by tboerger** [comment]
Congrats to the new owners.
