### ISSUE TITLE
在CentOS7中gitea以service 方式运行，ExecStart后面不能添加任何参数，否则启动不成功

### ISSUE THREAD

**Issue by HXHSHR** [go-gitea/gitea#32551]
### Description

```sh
[Unit]
Description=Gitea (Git with a cup of tea)
After=network.target
After=mysql.service

[Service]
RestartSec=2s
Type=simple
User=gitea
Group=gitea
WorkingDirectory=/var/lib/gitea/
ExecStart=/usr/local/bin/gitea web
Environment=USER=gitea HOME=/home/gitea GITEA_WORK_DIR=/var/lib/gitea
Restart=always
[Install]
WantedBy=multi-user.target
```
这样配置一切正常。
![image](https://github.com/user-attachments/assets/62ebc6e1-9e26-44cb-aca0-24b648e8d71e)

但当你尝试修改端口或者使用配置文件时，就会启动不成功：
```sh
[Unit]
Description=Gitea (Git with a cup of tea)
After=network.target
After=mysql.service

[Service]
RestartSec=2s
Type=simple
User=gitea
Group=gitea
WorkingDirectory=/var/lib/gitea/
ExecStart=/usr/local/bin/gitea web --config /etc/gitea/app.ini  -p 8102
Environment=USER=gitea HOME=/home/gitea GITEA_WORK_DIR=/var/lib/gitea
Restart=always
[Install]
WantedBy=multi-user.target
```
报错信息没有任何提示：
![image](https://github.com/user-attachments/assets/d3bc1c39-bd94-4f34-89bd-cf6ed812d472)
![image](https://github.com/user-attachments/assets/1950733a-4206-4da4-a800-7b26d4fc8d93)

奇怪的是，我手动启动`/usr/local/bin/gitea web --config /etc/gitea/app.ini  -p 8102`，这样是正常的。

### Gitea Version

1.22.3

### Can you reproduce the bug on the Gitea demo site?

Yes

### Git Version

git version 2.26.2

### Operating System

centos7.9

### How are you running Gitea?

我使用的二进制文件进行安装的Gitea，使用systemd 运行的gitea。
![image](https://github.com/user-attachments/assets/6b4ed0ec-4a27-47e6-b911-ea8fbfa22172)
```sh
[Unit]
Description=Gitea (Git with a cup of tea)
After=network.target
After=mysql.service

[Service]
RestartSec=2s
Type=simple
User=gitea
Group=gitea
WorkingDirectory=/var/lib/gitea/
ExecStart=/usr/local/bin/gitea web --config /etc/gitea/app.ini  -p 8102
Environment=USER=gitea HOME=/home/gitea GITEA_WORK_DIR=/var/lib/gitea
Restart=always
[Install]
WantedBy=multi-user.target
```
这样运行报错，日志不提供任何有效信息。当删除掉`--config /etc/gitea/app.ini  -p 8102`，那么就变正常了

### Database

MySQL/MariaDB

**Comment by charles7668** [comment]
I think the issue is you are start Gitea with User=gitea and Group=gitea, but this configuration does not allow access to read the app.ini file.

**Comment by lunny** [comment]
Closed due to the requirement in English
