### ISSUE TITLE
Clicking Star/Unstar, Watch/Unwatch buttons on star list or watch list page result in inconsistent result.

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#32561]
### Description

On watch list page, click watch/unwatch button, the button's state will be changed but the list will not be reloaded. So the number of watching is not equal to the total of watch users on this page. The same as star list page.

Regression from #29001

### Gitea Version

1.22

**Comment by yardenshoham** [comment]
https://github.com/go-gitea/gitea/pull/32570
