### ISSUE TITLE
Submodules not linked if file format not in default order

### ISSUE THREAD

**Issue by AdamMajer** [go-gitea/gitea#32568]
### Description

A submodule that is listed in .gitmodules as,

```
[submodule "jakarta-servlet"]
        url = ../../ALP-pool/jakarta-servlet
        path = jakarta-servlet
```

is not linked in the repository view. A submodule that is listed in the other order is linked correctly.

```
[submodule "jakarta-servlet"]
        path = jakarta-servlet
        url = ../../ALP-pool/jakarta-servlet
```

The gitmodules.txt doesn't seem to impose any particular order on values.

NOTE: Demo site is down at this second so can't check if I can reproduce it there.

### Gitea Version

1.22.2

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

![image](https://github.com/user-attachments/assets/b15961ff-64d3-42ba-b53e-a645e99da4f1)

### How are you running Gitea?

It's built and running with systemd, using core git tools

### Database

PostgreSQL

**Comment by wxiaoguang** [comment]
Bug ...........


![image](https://github.com/user-attachments/assets/c648ca97-a9a1-4f34-9fe8-0c8617410309)
