### ISSUE TITLE
Compilation from source fails

### ISSUE THREAD

**Issue by al-sabr** [go-gitea/gitea#3256]
arm64 and arm32

## Description

Compilation from source produce this :

Removing intermediate container b41259d53d37
Step 3/5 : RUN go get -u -d code.gitea.io/gitea
 ---> Running in 1e54dc5a510f
 ---> 5ac9d7356e34
Removing intermediate container 1e54dc5a510f
Step 4/5 : WORKDIR /go/src/code.gitea.io/gitea
 ---> 4d24d5274fa8
Removing intermediate container 6898ad55735a
Step 5/5 : RUN TAGS="bindata" make generate build
 ---> Running in 574365d69d99
make: *** No rule to make target 'generate'.  Stop.
The command '/bin/sh -c TAGS="bindata" make generate build' returned a non-zero code: 2

**Comment by tboerger** [comment]
You are not providing enough information. What image to you use? Which commands have you executed?

**Comment by tboerger** [comment]
This simply sounds like you are executing make in the wrong directory.

**Comment by al-sabr** [comment]
FROM troyfontaine/armhf-alpinelinux

RUN apk update && \
  apk add \
    git \
	alpine-sdk \
	binutils \
	gcc \
	musl-dev \
	openssl \
	make \
	go \
	sqlite && \
  rm -rf /var/cache/apk/*

RUN go env
RUN go get -u -d code.gitea.io/gitea
RUN cd /go/src/code.gitea.io/gitea
RUN TAGS="bindata,sqlite" make build

**Comment by tboerger** [comment]
As already stated on chat you just used the wrong path to execute make.
