### ISSUE TITLE
Add "Copy path to clipboard" button

### ISSUE THREAD

**Issue by kuraga** [go-gitea/gitea#32583]
### Feature Description

Good day!

1. At a commit page,
    and at a Pull Request page, in the `Files Changed` tab,
    and at a Compare page,

    1. at the each changed file's panel,
        at the header,
        alongside the file path,

    and/or

    2. in the tree side-panel,
        alongside the each file's name,

and

2. At a file page,

    at the header,

there is no the `Copy path to clipboard` button/icon/link.

The proposition is to add a such.

Thanks.

### Screenshots

![image](https://github.com/user-attachments/assets/9156c1fa-5850-4ccf-8047-2baa73985e4e)

**Comment by kuraga** [comment]
Yes.
(Sorry, Gitea demo site is down.)

**Comment by silverwind** [comment]
That said, we are missing the button in file view, I will add it later.

**Comment by silverwind** [comment]
It's be there but the demo site it outdated currently.
