### ISSUE TITLE
Web hook pull notifications .diff and .patch point to different pull and are not diffs

### ISSUE THREAD

**Issue by robe2** [go-gitea/gitea#3259]
- Gitea version (or commit ref):
- Git version: 1.3.0dev (also see similar issue on 1.3.2)
- Operating system: Debian 7
- Database (use `[x]`):
  - [x ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
 When a webhook for pull happens, it posts:

These 3 urls (pull number always same of course

>     "html_url": "https://try.gitea.io/robe2/test/pulls/1",
    "diff_url": "https://try.gitea.io/robe2/test/pulls/1.diff",
    "patch_url": "https://try.gitea.io/robe2/test/pulls/1.patch"

For try.gitea.io, I can't replicate the diff and patch pull pointing to a different pull, but the urls offered for diff and patch are not diff and patches , they are just the pull html page.

In my production environment these end up pointing to the wrong pull even though they do have the right pull number in the web hook post.  I suspect it might be because the pull it ends up pointing to has the repo deleted.
...

**Comment by strk** [comment]
I can reproduce: https://try.gitea.io/gitea/gitea/pulls/2.diff takes you to PR 1 ...

**Comment by strk** [comment]
PR #3293 implements the `.patch` endpoint

**Comment by strk** [comment]
I'd reopen this becasue only .diff is done via #3293 -- .patch has to wait for https://github.com/go-gitea/git/pull/103 to be merged first

**Comment by strk** [comment]
PR for .patch is https://github.com/go-gitea/gitea/pull/3305
