### ISSUE TITLE
Passkey login not working anymore

### ISSUE THREAD

**Issue by anbraten** [go-gitea/gitea#32595]
### Description

When trying to login with my Passkey to gitea.com I now get a http 403 error. Updating the passkey didn't help.

### Gitea Version

 1.23.0+dev-671-gc3dedcffa7 

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

https://gitea.com/

### Database

None

**Comment by wxiaoguang** [comment]
Maybe related to this, the webauthn lib was changed:  Fix: passkey login not working anymore #32623

**Comment by wxiaoguang** [comment]
The problem is that " Add Passkey login support #31504 " didn't store the flags, then webauthn now strictly checks the flags, need to figure out how to restore them .......
