### ISSUE TITLE
Code syntax highlight render failed

### ISSUE THREAD

**Issue by zjjhot** [go-gitea/gitea#32608]
### Description

Code syntax highlight render failed

### Gitea Version

a3881ffa3d90f3f017024f701ca8ef420d492224

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

![image](https://github.com/user-attachments/assets/e5a3c321-d17b-4353-b8f3-0f4bbd44f4e2)

![image](https://github.com/user-attachments/assets/a2392121-e18b-46eb-80e0-d24d6e3f92c9)

### Git Version

a3881ffa3d90f3f017024f701ca8ef420d492224

### Operating System

win11

### How are you running Gitea?

windows + ms sql server

### Database

MSSQL

**Comment by wxiaoguang** [comment]
The render system is still under refactoring, will fix soon.

**Comment by wxiaoguang** [comment]
Will by fixed by #32612 (by the way)

**Comment by zjjhot** [comment]
![Image_99537402170361.png](https://github.com/user-attachments/assets/299c431b-a613-4a15-8ce6-05ee2289a4b3)

![Image_99540951370464.png](https://github.com/user-attachments/assets/d2e9c119-6e2e-40b6-b10a-0da5dbc18811)

issue content preview markup error.

**Comment by wxiaoguang** [comment]
Oops, sorry for the inconvenience ....  https://github.com/go-gitea/gitea/pull/32640

Thank you very much for testing the edge version!
