### ISSUE TITLE
Installing Docker Root less per the manual using RHEL9.  Nothing changed starting it with docker compose up.  And nothing works.  Banner on top is "Gitea JavaScript code couldn't run correctly, please check your custom templates"

### ISSUE THREAD

**Issue by iamtristan** [go-gitea/gitea#32600]
### Description

Installing Docker Root less per the manual using RHEL9.  Nothing changed starting it with docker compose up.  And nothing works.  Banner on top is "Gitea JavaScript code couldn't run correctly, please check your custom templates"

This happens before and after installation.

Used the instructions here to the letter.

https://docs.gitea.com/installation/install-with-docker-rootless

### Gitea Version

1.22.3

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

RHEL9 via Docker Compose

version: "2"

services:
  server:
    image: gitea/gitea:1.22.3-rootless
    restart: always
    volumes:
      - ./data:/var/lib/gitea
      - ./config:/etc/gitea
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "2222:2222"

### Database

SQLite

**Comment by wxiaoguang** [comment]
`Gitea JavaScript code couldn't run correctly, please check your custom templates` means the outputed page is corrupted.

There could also be something wrong in your reverse proxy, please make sure every step you have done you could understand, otherwise don't do it.


If there is still a problem, please show a reproducible example with all config and detailed steps.

**Comment by iamtristan** [comment]
Hello -
Found it.  A severely hardened environment.

# Here was the problem within NGINX
add_header Content-Security-Policy     "default-src 'self'" always;

Thanks wxiaoguang for actually hinting it out :)

**Comment by iamtristan** [comment]
Works now with some changes...
