### ISSUE TITLE
mirror: LFS client version too old

### ISSUE THREAD

**Issue by scott-wong** [go-gitea/gitea#32611]
### Description

`epository/migrate.go:171:MigrateRepositoryGitData() [E] Failed to store missing LFS objects for repository: LFS client version too old, please upgrade your LFS client greater than v2.4.0`

I install the latest git-lfs version in the container, but it did not work.
![image](https://github.com/user-attachments/assets/64460eb7-df9f-466a-8be2-dae24e80d153)

#30913 

### Gitea Version

1.22.3

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

![image](https://github.com/user-attachments/assets/208e8502-5c61-44b5-9ec8-01edad16a088)

### Git Version

2.45.2

### Operating System

Docker

### How are you running Gitea?

docker compose

### Database

MySQL/MariaDB

**Comment by lunny** [comment]
Maybe this has been fixed by #32832 ? @hiifong

**Comment by hiifong** [comment]
> Maybe this has been fixed by #32832 ? @hiifong

No

**Comment by hiifong** [comment]
Fixed #32838
