### ISSUE TITLE
UI broken in compare page.

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#32617]
URL: https://demo.gitea.com/phoedos/pmd/compare/main...big-commit-simulation

![image](https://github.com/user-attachments/assets/755c0f5a-e58f-488e-9ead-b642744481c8)

**Comment by hiifong** [comment]
Now is Internal Server Error
![image](https://github.com/user-attachments/assets/0ee0e60c-6c7f-4a3d-accc-c6d79a21474a)

**Comment by yp05327** [comment]
This page works in my local. (But the repo is too big to migrate, so I cloned it, and only pushed two branches to my local server, I think there's no diffs)
![image](https://github.com/user-attachments/assets/765931ac-93c8-43fd-a3f8-37dd94666cd4)
I remember you are using MacOS. Maybe it is related.

**Comment by hiifong** [comment]
After I forked this repository to my account, and compare worked.
![image](https://github.com/user-attachments/assets/3e0c1971-181a-4d56-9ad8-4d91801c4fe0)

**Comment by hiifong** [comment]
Now working fine for me. Maybe the compare is too large and it takes time to load.
