### ISSUE TITLE
OpenID 2.0 login does not allow self-signed CA certificates for OpenID provider

### ISSUE THREAD

**Issue by danielfbm** [go-gitea/gitea#3261]
- Gitea version (or commit ref): 1.3  (index.docker.io/gitea/gitea:latest
- Git version: not relevant
- Operating system: not relevant
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
OpenID 2.0 login does not support self-signed CA certificates. 

this is a feature in golang's TLS client's implementation as mentioned [here](https://kubernetes.io/docs/admin/authentication/#openid-connect-tokens)

as in the kubernetes' case it is necessary to provide the CA file in order to avoid this issue.

yes, I understand that self-signed certificates are not a good option, but in our case we have multiple private deployment cases of our services and generally our customers don't have a certificate. As of OpenID's requirement to use https, we have no other way other than provide a self-signed certs for the moment. 
...

## Screenshots
<img width="829" alt="gitea" src="https://user-images.githubusercontent.com/5045502/34356653-9ef939bc-ea7a-11e7-9590-c9d32a8d2c04.png">

**Comment by lafriks** [comment]
You can add that certificate to trusted cert list in system than it should work.

**Comment by danielfbm** [comment]
I see. We mostly use docker for deployments and that means I would have to extend your image and create a bootstrapping script to change the container's OS settings. BTW, could you point to any relevant documentation on this? 

There are some other cases that might be conflicting with the solution above, for example using [rkt](https://coreos.com/rkt) that can control the user inside each container and maybe restrict the changes inside the container's OS.

**Comment by danielfbm** [comment]
Solved this issue following [this blog post](https://hackernoon.com/alpine-docker-image-with-secured-communication-ssl-tls-go-restful-api-128eb6b54f1f) and adding a bootstrap script to include certificates (only known in run-time)
