### ISSUE TITLE
Pull request creation has broken window

### ISSUE THREAD

**Issue by AdamMajer** [go-gitea/gitea#32636]
### Description

Screenshot created from
https://demo.gitea.com/AdamMajer/foobar/compare/main...test/foobar:main

### Screenshots

![image](https://github.com/user-attachments/assets/9f6ca23b-3ad4-41b3-88ac-fc78e17e12f4)

### Gitea Version

1.23.0+dev-686-gefb55cd8ef

### Can you reproduce the bug on the Gitea demo site?

Yes

### Browser Version

Firefox 128.4.0esr (64-bit)

**Comment by AdamMajer** [comment]
The pull request then looks broken too. I can see this breaking in Chrome as well.

https://demo.gitea.com/AdamMajer/foobar/pulls/1

![image](https://github.com/user-attachments/assets/745e6e1d-9294-4bd2-8dd2-dbd14c8512ea)

**Comment by wxiaoguang** [comment]
It should have been fixed in main, by  Fix issue sidebar regression #32598
