### ISSUE TITLE
Issue content render error in preview tab

### ISSUE THREAD

**Issue by zjjhot** [go-gitea/gitea#32639]
### Description

![Image_99540951370464](https://github.com/user-attachments/assets/895156f3-4a03-4237-a5ce-cf1f74f3c0f1)

![Image_99537402170361](https://github.com/user-attachments/assets/c7c2f4d3-f6a1-4513-8e6c-06d900ee82cf)

Issue content render error in preview tab

### Gitea Version

main branch

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

Windows msssql

### Database

MSSQL

**Comment by wxiaoguang** [comment]
Fix markup render regression and fix some tests #32640
