### ISSUE TITLE
Export and import image from running docker image - Not work

### ISSUE THREAD

**Issue by BasilioPV** [go-gitea/gitea#32630]
### Description

I want to backup the entire runnig image of my gitea repository. After export the running image and import them into a new gitea docker, the configuration initial page is shown. It's not possible to recreate the configured image on gitea?

### Gitea Version

1.22.3

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

Docker image. managed with portainer.

### Database

SQLite

**Comment by wxiaoguang** [comment]
Docker isn't designed to work that way.

For all docker containers (not only Gitea), you should copy the data volumes, but not the running image.

Check your docker volume setting and volume mapping, copy the data to your new server.

**Comment by BasilioPV** [comment]
Ok, Thanks!
