### ISSUE TITLE
Support Admin users to operate Authentications through API/CLI

### ISSUE THREAD

**Issue by danielfbm** [go-gitea/gitea#3264]
- Gitea version (or commit ref):  index.docker.io/gitea/gitea:latest
- Git version: not relevant
- Operating system: not relevant
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
To provide better automation and integration during deployment, I suggest adding Authentication APIs reserved to Administrators. This would greatly improve automated deployment methods having a Gitea deployed and running using our Authenticated method of choice.
...

**Comment by bkcsoft** [comment]
Are you referring to adding users using the API or adding login sources (OAuth, OpenID, etc)?

**Comment by danielfbm** [comment]
Both would be nice, but I am referring to login sources in this case

**Comment by 6543** [comment]
```sh
./gitea admin --help
NAME:
   Gitea admin - Command line interface to perform common administrative operations

USAGE:
   Gitea admin command [command options] [arguments...]

COMMANDS:
     create-user         Create a new user in database
     change-password     Change a user's password
     repo-sync-releases  Synchronize repository releases with tags
     regenerate          Regenerate specific files
     auth                Modify external auth providers
```
and api provides many ways to create/edit/things for admin too:
https://try.gitea.io/api/swagger#/admin
