### ISSUE TITLE
JS error when creating an issue

### ISSUE THREAD

**Issue by stuzer05** [go-gitea/gitea#32660]
### Description

Opne new issue page

```js
testhelper.ts:5 Uncaught ReferenceError: process is not defined
    at g (testhelper.ts:5:3)
    at Z (dom.ts:80:7)
    at cg.updateUiList (repo-issue-sidebar-combolist.ts:51:5)
    at cg.init (repo-issue-sidebar-combolist.ts:143:12)
    at ug (repo-issue-sidebar-combolist.ts:158:40)
    at repo-issue-sidebar.ts:52:69
    at Pe (dom.ts:65:7)
    at ce (dom.ts:91:10)
    at hg (repo-issue-sidebar.ts:52:3)
    at Mg (repo-issue.ts:659:3)
```

### Gitea Version

1.23.0+dev-720-g5a50b271e7

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![image](https://github.com/user-attachments/assets/fc1b12a7-4040-4a65-a777-db6eb9c67b4a)

### How are you running Gitea?

docker

### Database

None

**Comment by lunny** [comment]
I can't reproduce it in both my local machine and the demo site.

**Comment by stuzer05** [comment]
@wxiaoguang

**Comment by yp05327** [comment]
![image](https://github.com/user-attachments/assets/64050974-0b69-4e06-8799-1b74514c00a6)
I also got this error when editing my PR in the repo home page. 👀

**Comment by silverwind** [comment]
https://github.com/go-gitea/gitea/pull/32661 will fix it.

**Comment by wxiaoguang** [comment]
@silverwind yup, you see, I have warned that it would break without careful `typeof process` check. It is difficult to catch in production.

I would still again to do that trick

**Comment by silverwind** [comment]
I was wrongly assuming webpack to work similar to vite where env vars don't need to be declared explicitely in config, my fault.
