### ISSUE TITLE
Add incoming mail test item on admin dashboard

### ISSUE THREAD

**Issue by hiifong** [go-gitea/gitea#32665]
### Feature Description

Because incoming mail depends on plus addressing, if the mail provider does not support plus addressing, then incoming mail will not work. If the administrator is not aware of this, then they will waste a lot of time troubleshooting the problem. So I think we need to add this feature.

We can add a simple test by sending a test email to the `REPLY_TO_ADDRESS` address of the incoming mail. If the email can be received, it means that the current mail supports plus addressing.

If you have better ideas, you are welcome to leave your thoughts.

![image](https://github.com/user-attachments/assets/80cb6625-1c89-498a-afa3-b8df79a096a8)

**Comment by wxiaoguang** [comment]
Test for what purpose and how to really "test"?

**Comment by hiifong** [comment]
> Test for what purpose and how to really "test"?

@wxiaoguang Updated description

**Comment by hiifong** [comment]
Because smtp has no way of knowing if a message is bounced, I can't proceed with implementing the feature
