### ISSUE TITLE
500 upon authentik OAuth2/OpenID: login 

### ISSUE THREAD

**Issue by moan0s** [go-gitea/gitea#32674]
### Description

I configured Authentik and Gitea as described in [this manual](https://docs.goauthentik.io/integrations/services/gitea/). When trying to login via this OAuth-Flow I encounter a http 500 error and cannot log in via this flow. Reloading does not solve the problem (#5005).

The server log says: 

```
oauth2: error decoding JWT token: jws: invalid token received, not all parts available
```

Callback that fails with `500`: https://git.hyteck.de/user/oauth2/QZT%20Authentik/callback?code=c26c5f75c939524d98f5f67e3d58c6b6&state=08176cae-79d6-46a3-04c7-36670db77079 (not  the real code or state).

I specifically configured 
`samesite: Lax` as per https://github.com/go-gitea/gitea/issues/25542, same for `GITEA__server__ROOT_URL=https://git.hyteck.de` (I also tried including a backslash at the end)

I also set `GITEA__oauth2_client__ENABLE_AUTO_REGISTRATION=true`

I'm looking for ways to debug this further. Feel free to ask for more information.

### Gitea Version

1.22.3

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/moan0s/6e214403d9f1cd15265259455529b3fb

### Operating System

docker (running on ubuntu)

### How are you running Gitea?

Gitea is run as docker container started by a systemd service as deployed by the [mash-playbook](https://github.com/mother-of-all-self-hosting/mash-playbook), same for authentik.
Both run behind Traefik.

### Database

PostgreSQL

**Comment by KN4CK3R** [comment]
Works for me by following the linked tutorial. I even tried to use a name with a space like you did but that worked too.

**Comment by moan0s** [comment]
@KN4CK3R Okay, well I guess I check again if I really followed every step of the tutorial. Either way, the error message should be more clear IMHO.

Yeah, in my setup everything is publicly reachable

**Comment by lautriva** [comment]
Same problem for me

Maybe it would help, I'm using those configs:
```
DISABLE_REGISTRATION = true
REQUIRE_SIGNIN_VIEW = true
```

The idea is that the SSO will only let users to link their Authentik account with their existing gitea one

(no registration are allowed to let me control who can access to my instance)

**Comment by kat4ex** [comment]
It seems gitea cannot use JWE.

It is necessary to disable token encryption in the authentik provider.
![изображение](https://github.com/user-attachments/assets/aa4710bd-9392-449c-8db1-5d2ff94c67c8)

**Comment by moan0s** [comment]
Thank you so much, that was it!

**Comment by VIXNESS** [comment]
It's work  too:
copy from gitea config `app.ini` field `JWT_SECRET`  in  `[oauth2]`  to authentik config field: Encryption Key
