### ISSUE TITLE
actions/upload-artifact@v4 still not work

### ISSUE THREAD

**Issue by cikomesi** [go-gitea/gitea#32679]
### Description

i try some issues, for example : https://github.com/go-gitea/gitea/issues/31256
but they cannot works.

same action, if i use actions/upload-artifact@v3
it work well.

my job step is : 

     - name: Upload docker-compose.yml
        uses: actions/upload-artifact@v4
        with:
          name: docker-compose-file
          path: deploy/docker-compose.yml

my gitea/act_runner:nightly 
gitea/act_runner               nightly           b64ba8f68d0a   3 weeks ago     44.7MB

### Gitea Version

1.22.4

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

![](https://github.com/user-attachments/assets/f4ffb186-a7ac-4044-923d-15057fc5e268)

### Operating System

Ubuntu 22.04.3 LTS  aarch64

### How are you running Gitea?

docker compose

### Database

MySQL/MariaDB

**Comment by techknowlogick** [comment]
The logic for v4 support was merged into 1.23 and because it's rather significant it wasn't backported to 1.22 based on our backporting guidelines. We are close to an RC of 1.23 if you want to use that, or there are workarounds that others haven't posted in the linked issues that you could use.
