### ISSUE TITLE
Error when replying to code comment from "Conversation" tab

### ISSUE THREAD

**Issue by jpraet** [go-gitea/gitea#32684]
### Description

Replying to a code comment from "Conversation" tab gives an error on https://demo.gitea.com.
When replying to the same comment from the "Files Changed" tab, it works fine.

JS error:

```
Error: TypeError: e.closest(...) is null
    C0 repo-diff.ts:58
    Be dom.ts:361
repo-diff.ts:90:14
    C0 repo-diff.ts:90
    Be dom.ts:361
```

### Gitea Version

1.23.0+dev-727-ga1f56f83bf

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

![image](https://github.com/user-attachments/assets/fbe3b881-b8a5-43e2-a0ee-4f4b40e0f46f)

### How are you running Gitea?

https://demo.gitea.com/jpraet/test/pulls/1

### Database

None

**Comment by jpraet** [comment]
Could be a regression from #32596.

**Comment by wxiaoguang** [comment]
Fix JS error when reply commenton Conversation page #32685
