### ISSUE TITLE
Add Config Option for Custom Gravatar Mirror Sources

### ISSUE THREAD

**Issue by okatu-loli** [go-gitea/gitea#32690]
### Feature Description

In certain regions, such as China, Gravatar may be inaccessible due to network restrictions. To improve accessibility for users in these regions, it would be helpful to have the option to configure custom Gravatar mirror sources.

For example, sources like https://cravatar.com/ or https://cravatar.cn/ could be used as alternatives to the default Gravatar service.

It would be great if a configuration setting could be added to allow users to specify a custom Gravatar mirror URL in the settings, ensuring a more seamless experience for users facing connectivity issues with Gravatar.

**Comment by yp05327** [comment]
Are you looking for this?
![image](https://github.com/user-attachments/assets/34add11c-01c9-4b9a-9e51-ca948ec506cd)
https://docs.gitea.com/administration/config-cheat-sheet#picture-picture

**Comment by okatu-loli** [comment]
> Are you looking for this? ![image](https://private-user-images.githubusercontent.com/18380374/393666749-34add11c-01c9-4b9a-9e51-ca948ec506cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3MzkwMTUsIm5iZiI6MTczMzczODcxNSwicGF0aCI6Ii8xODM4MDM3NC8zOTM2NjY3NDktMzRhZGQxMWMtMDFjOS00YjlhLTllNTEtY2E5NDhlYzUwNmNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA5VDEwMDUxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1NjIxNjA2YTIyZWE2OTFiMGE1ODczNjI5OTNhNmQ5NzI0MmVmZmQyM2I5ODllMTBhMjU0MDQ0YjgxNWUwODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rWeD6ii7AC9RkbLAkEloxDfEr6VN3dGvCALslIk_yv8) https://docs.gitea.com/administration/config-cheat-sheet#picture-picture

Solved, thanks!
