### ISSUE TITLE
Issue number no longer clickable in pr title

### ISSUE THREAD

**Issue by stuzer05** [go-gitea/gitea#32700]
### Description

![image](https://github.com/user-attachments/assets/7feb5767-7649-4467-b6a5-a398f20f26d4)

### Gitea Version

1.23.0+dev-739-g576e31ae3b

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

docker

### Database

None

**Comment by wxiaoguang** [comment]
Related to the markup refactoring, will fix it.
