### ISSUE TITLE
There is an issue with recording the display time

### ISSUE THREAD

**Issue by Chen-Wendong** [go-gitea/gitea#32704]
### Description

There is an issue with recording the display time, as shown in the following figure:
![image](https://github.com/user-attachments/assets/02149736-298f-478f-992f-97e3828cbcf3)

### Gitea Version

1.22.4

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

systemd

### Database

None

**Comment by lunny** [comment]
Is your client's machine's date and time correct?

**Comment by Chen-Wendong** [comment]
> Is your client's machine's date and time correct?

My computer time is correct, it's Beijing time. The time point where the problem occurred was 11 months ago, and not all time points have problems

**Comment by wxiaoguang** [comment]
It is a bug

->  Incorrect relative times close to Jan 2024 #32716 

![image](https://github.com/user-attachments/assets/548983cb-8efd-4ae8-a1d2-62e8396e7d87)

**Comment by wxiaoguang** [comment]
Fixed by https://github.com/go-gitea/gitea/pull/32730
