### ISSUE TITLE
PR comment user tagging bug, users not found

### ISSUE THREAD

**Issue by stuzer05** [go-gitea/gitea#32702]
### Description

When I type `@` in pr comment (or elsewhere) I cannot find other members. Only myself and teams

### Gitea Version

1.23.0+dev-743-g171edfc793

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

docker

### Database

None

**Comment by wxiaoguang** [comment]
Does 1.22 have the same behavior? Is it a regression?

**Comment by wxiaoguang** [comment]
->  Fix mentionable users when writing issue comments #32715
