### ISSUE TITLE
Forking page branch selection dropdown list overflow when a long content item is selected.

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#32709]
![图片](https://github.com/user-attachments/assets/9d3af1c9-052d-4f9d-a431-d83216f21190)

**Comment by wxiaoguang** [comment]
I think you need to take a look at the devtest page, instead of copying the unclear legacy frontend code.

![image](https://github.com/user-attachments/assets/9fa3dc48-7a54-48f8-bb5a-2eed5d846da4)

**Comment by lunny** [comment]
The example bug comes from the forking page.
