### ISSUE TITLE
How to update the forked repo from original repo

### ISSUE THREAD

**Issue by ethan42411** [go-gitea/gitea#3271]
- Gitea version (or commit ref): 2f8c65c
- Git version: 2.11.0
- Operating system: raspberry pi(dietpi)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
## Description
Hi everyone,
I am a gitea's new user, I installed gitea on my raspberry pi which runs dietpi.
I have no idea to update the forked repo from original repo on the gitea's web gui.
When I forked a repo and then modified, I can used "Pull requests" to merge changes  to original repo, but if the original repo was modified, I can't use "Pull requests" like Github can press "switch the base" to change source and target.

Thanks

**Comment by thehowl** [comment]
Hey there, if you want to pull changes from the main repository you should probably do this from the command line instead of using pull requests:

```sh
git remote add upstream [main_fork_clone_url]
# every time you want to update
git pull upstream master
```

**Comment by muhfaris** [comment]
i agree with @thehowl, my advise do `git fetch` before `git pull`
```
git remote add upstream [main_fork_clone_url]
git fetch upstream
git pull upstream master
```

**Comment by ethan42411** [comment]
Thanks for your answer.
Is it possible add a option on web UI?

**Comment by lafriks** [comment]
I think this is duplicate of #2488 to update fork from web UI
