### ISSUE TITLE
Incorrect relative times close to Jan 2024

### ISSUE THREAD

**Issue by silverwind** [go-gitea/gitea#32716]
### Description

Example: https://gitea.com/gitea/docs/commits/branch/main?page=6

Renders like this currently for me:

<img width="95" alt="image" src="https://github.com/user-attachments/assets/3ad9afb1-72cf-4406-b1d9-14872822d795">

I suspect it might be https://github.com/github/relative-time-element/issues/250, but we should investigate whether this is really the case.

### Gitea Version

main

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

-

### Database

None

**Comment by wxiaoguang** [comment]
Maybe it seems to be related to to the leap year? There is Feb 29 in 2024.

**Comment by wxiaoguang** [comment]
Or maybe we should fork it ....... 

To be honest, GitHub doesn't really maintain their components.

**Comment by wxiaoguang** [comment]
Hmm, I know how to fix it now
