### ISSUE TITLE
Update Git SSH URL After IP Change

### ISSUE THREAD

**Issue by muellert** [go-gitea/gitea#32727]
### Description

I am running gitea on a VM where I recently changed the IP of that machine. If l look into a repo for the clone URLs, the HTTP URL gets updated with the new IP of the machine. The SSH URL however retains the old URL, and there does not appear to be any way to change the IP for that, short of going to the server and manually fiddling with the settings in the repos.

My expectation is that both URLs should be in sync, and automatically update to the new IP address.

### Gitea Version

1.22.3

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

Debian Bookworm

### How are you running Gitea?

I run gitea as a service under systemd.

### Database

PostgreSQL

**Comment by KN4CK3R** [comment]
Have a look in your configuration file. There should be an entry with your old IP.

**Comment by muellert** [comment]
Very good catch, but it still doesn't explain why the HTTP URL was correct without that change, while the git URL wasn't. Also, all the configuration items didn't mention git, only HTTP.

For the specific problem at hand, I made the change, and the URL was correct after that. I should look into the manual to see where this requirement is being mentioned.

**Comment by KN4CK3R** [comment]
If you put only the
```
[server]
DOMAIN = ...
```
setting into your app.ini without specifying 
```
[server]
SSH_DOMAIN = ...
```
it should use the `server,DOMAIN` setting to generate both links with the same domain.

**Comment by muellert** [comment]
Thank you, that worked! My bad. :(
