### ISSUE TITLE
The interface to get submission comparison information is not as expected

### ISSUE THREAD

**Issue by inbjo** [go-gitea/gitea#32723]
### Description

Hi, everyone.
I tried to use this API interface /repos/{owner}/{repo}/compare/{basehead}

The basehead parameter I passed into branch 1... Branch 2 returns normal results, but I pass in two different commit sha1 hashes from the same branch and it returns 404.

![2024-12-05_15-45](https://github.com/user-attachments/assets/89073b00-ac10-4b5d-8f56-116685815140)

I want to use this interface to get the files modified between two commit records under the same branch. But the result is not what I expected this seems to be a bug. if I am not using it the right way please let me know, thanks!

### Gitea Version

1.22.3

### Can you reproduce the bug on the Gitea demo site?

Yes

### Git Version

2.38.1

### Operating System

centos7

### How are you running Gitea?

Managing services with systemd via officially compiled binaries

### Database

MySQL/MariaDB

**Comment by ExplodingDragon** [comment]
repeat: https://github.com/go-gitea/gitea/issues/30655

**Comment by wxiaoguang** [comment]
->  Make API "compare" accept commit IDs #32801
