### ISSUE TITLE
reopening #27605 (Math blocks can't be directly preceded or followed by alphanumeric character)

### ISSUE THREAD

**Issue by nschloe** [go-gitea/gitea#32726]
### Description

Unless I'm missing something, the issue https://github.com/go-gitea/gitea/issues/27605 has reappeared despite its fix in https://github.com/go-gitea/gitea/pull/30175.

MWE:
```
a$x$ -$x$ 1$x$
```

Screenshot:

![screenshot_2024-12-05-152708](https://github.com/user-attachments/assets/c294ca62-3cdd-4178-aa3e-22c44db41b2d)

```
$a$1

$a$-

$a$x
```

![screenshot_2024-12-05-152735](https://github.com/user-attachments/assets/94c6fcac-55ac-4d53-99e1-4cf05f0e2f97)

This also concerns the `\(...\)` and `\[...\]` syntax.

### Gitea Version

1.23.0+dev-753-gc5422fae9a

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

demo.gitea.com

### Database

None

**Comment by wxiaoguang** [comment]
> `a$x$ -$x$ 1$x$`

What's the problem? If you'd like to render it, please add some spaces.

Otherwise, it's impossible to distinguish from `This is 10US$ and that is 20US$`, we shouldn't render everything between `$`, say here it is ` and that is 20US`.

**Comment by wxiaoguang** [comment]
> ###
> 
> Unless I'm missing something, the issue #27605 has reappeared despite its fix in #30175.

The issue doesn't "reappear", because there are enough tests in #30175:

![image](https://github.com/user-attachments/assets/ff362aad-feaa-481d-a6a2-a31beb305079)

**Comment by wxiaoguang** [comment]
By the way, maybe you might be interested in my recent refactoring PRs like #32728 

![image](https://github.com/user-attachments/assets/549fc74c-4013-46b2-b106-600415daa894)

**Comment by wxiaoguang** [comment]
Hmm, I see the misconception now. Actually #30175's title doesn't really match its test cases.

So, if `a$x$ -$x$ 1$x$` is a must to support, we need to clarify its usage first and design the cases to avoid interfering other daily sentences like `$1 and 20US$`.
    * the question is: why not write `$ax$ $-x$ $1x$`?

**Comment by wxiaoguang** [comment]
So if we support ``` $` ``` for inline math, then this issue (and maybe some related legacy issues) could be fully resolved?

**Comment by nschloe** [comment]
At least you could point anyone running into a `$`-syntax bug to the working ``$`...`$`` syntax. I myself would only use the latter anyway, and recommend everyone would do the same.

**Comment by nschloe** [comment]
> But I guess we couldn't remove it since it would be a breaking change.

Indeed, unfortunately so.

> After " Refactor markdown math render https://github.com/go-gitea/gitea/pull/32831 ", the $`x`$ will be supported, then other issues could be closed IMO (encourage users to use the new syntax)

Note that we'd also need `` ```math`` code blocks to get feature parity with GitHub/GitLab.

**Comment by wxiaoguang** [comment]
> Note that we'd also need `` ```math `` code blocks to get feature parity with GitHub/GitLab.

It is already support, right?

![image](https://github.com/user-attachments/assets/978135b2-1d66-4bc0-926e-2bdeb0e504ae)

**Comment by nschloe** [comment]
Right! Hadn't realized that.

**Comment by wxiaoguang** [comment]
Done in 1.23, let's use ``` $`...`$ ```

**Comment by nschloe** [comment]
This isn't working yet in 1.23.0+dev-789-g18061af490 (on demo.gitea.com).

**Comment by wxiaoguang** [comment]
> This isn't working yet in 1.23.0+dev-789-g18061af490 (on demo.gitea.com).

Demo site is at 18061af490 (5 days ago), it doesn't include #32831

You can get the latest main-nightly (from dl.gitea.com or dockerhub)
