### ISSUE TITLE
Code view path has less width than before

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#32753]
https://gitea.com/gitea/docs/src/branch/main/i18n/zh-cn/docusaurus-plugin-content-docs/version-1.22/administration

<img width="1329" alt="图片" src="https://github.com/user-attachments/assets/14f7417b-65cb-4061-9c1e-ac5920d1b795">

**Comment by silverwind** [comment]
It's caused by this removal:

https://github.com/go-gitea/gitea/pull/32213#discussion_r1874771955

As for why it was removed, no idea. I think we should restore the rule, @yp05327.

**Comment by wxiaoguang** [comment]
I removed it when refactoring the "isHome" logic. It is a mistake.

**Comment by wxiaoguang** [comment]
->  Fix repo home row-right grow #32763
