### ISSUE TITLE
Reference Gitea templete’s syntax

### ISSUE THREAD

**Issue by mkungla** [go-gitea/gitea#3275]
- Gitea version (or commit ref): *

## Description

Would be nice to have it in docs which arguments, pipelines, actions, methods, vars etc. are available within templates

**Comment by lafriks** [comment]
I don't think that's possible as it differs page from page

**Comment by mkungla** [comment]
true, however templates could for example just have block comment describing the struct. Maintaining docs would be probably quite a hassle

**Comment by lafriks** [comment]
Some basic stuff of course would be nice to be documented
