### ISSUE TITLE
403 Forbidden Error when updating labels via REST API

### ISSUE THREAD

**Issue by m4l0n** [go-gitea/gitea#32775]
### Description

As per title, I'm getting a 403 Forbidden Error when updating labels for issues via REST API. Tried with both the issue id and name. Seems to only happen to my instance (all repositories) running version 1.22.4 in Docker, as I've tested on the demo site (v1.23.0) and cloudron (1.22.4) without any issues.

### Gitea Version

1.22.4

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/m4l0n/eb982cd419bd05cf4924e0e886672774

### Screenshots

<img width="2203" alt="image" src="https://github.com/user-attachments/assets/dbf3e01b-aed7-45ef-a68b-a39852aa7f89">

### How are you running Gitea?

Docker installation

### Database

PostgreSQL

**Comment by yp05327** [comment]
It seems that your token does not have write permission to this repo.
Can you check it?

**Comment by m4l0n** [comment]
Hi @yp05327 

My token indeed has write permissions to both issue and repository, which is the same as what I've tried with demo.gitea.com and gitea.com, and cloudron
<img width="193" alt="image" src="https://github.com/user-attachments/assets/7c067557-4927-4c5f-94b0-1f7c2c650e9d">

**Comment by yp05327** [comment]
Does the user who created this token has write permission?

**Comment by m4l0n** [comment]
You're right - the user isn't added as a collaborator with write access to the repository. Solved. Thanks!

**Comment by yp05327** [comment]
No need to close this issue, we will fix the internal server error, and it will be closed automatically.
Thanks for your report.
