### ISSUE TITLE
You are not allowed to import local repositories.

### ISSUE THREAD

**Issue by strk** [go-gitea/gitea#3277]
Trying to migrate a repository from git@github.com:go-gitea/gitea.git results in this error message:

      You are not allowed to import local repositories.

... but it's not really a local repository !

**Comment by lafriks** [comment]
it's just that such syntax is not supported as migrations are not supported using ssh protocol (only local or http(s) are supported)

**Comment by lafriks** [comment]
Duplicate of #1635

**Comment by strk** [comment]
I see, thanks
