### ISSUE TITLE
wrong relative commit time

### ISSUE THREAD

**Issue by jakobzudrell** [go-gitea/gitea#32787]
### Description

The relative time shown for commit dates is wrong as seen in the screenshot (taken today) below.. 
Not that this is a super critical issue, but its odd and it incidentally occurred to me today.

 I've seen this mentioned in the closed issues, but were unable to comment on them, therefore the new issue.

### Screenshots

<img width="1444" alt="Screenshot 2024-12-11 at 00 02 55" src="https://github.com/user-attachments/assets/ff86666b-f61f-4404-89ea-fcb8cb905dd3">

### Gitea Version

1.22.4

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

Debian

### Browser Version

Firefox 133.0 & Safari 18.1.1

**Comment by silverwind** [comment]
This will be fixed in 1.22.5 with https://github.com/go-gitea/gitea/commit/063655c391a9f6f6b7cb50c818bc132103af92a4.

**Comment by wxiaoguang** [comment]
Try 1.22 nightly  https://dl.gitea.com/gitea/1.22-nightly/
