### ISSUE TITLE
Directory and files permission on repo file listing

### ISSUE THREAD

**Issue by joubertredrat** [go-gitea/gitea#328]
Hi guys,

One big git feature is versioning file and directory permissions (chmod) and I think that is good ideia to display this as optional on repository listing, as example below.

What you think guys?

![chmod_wireframe](https://cloud.githubusercontent.com/assets/1520407/20794301/bffeac24-b7b2-11e6-98aa-db81765cd089.png)

**Comment by lunny** [comment]
Windows?

**Comment by joubertredrat** [comment]
> Windows?

Sorry for windows users, but this power is privilege only for elite, linux users :star: :penguin:

But @lunny I liked your question, I will test to see if you have git server on windows, if it can versioning chmod from linux, I think that yes because git is OS agnostic.

**Comment by bkcsoft** [comment]
@lunny Git stores file-permissions as metadata (just that Windows throws them away on checkout), so there's no compat issue here :)

@joubertredrat as always, "benchmark" new features that hits Git, cache if appropriate :)

**Comment by lunny** [comment]
@bkcsoft you are right. Forgot that.

**Comment by tboerger** [comment]
But Git doesn't keep all flags.

**Comment by joubertredrat** [comment]
Ok guys, I'm noob but I will try to implement this.

**Comment by thibaultmeyer** [comment]
@joubertredrat I think is better to make it optional (create a configuration key on app.ini).

take care about the overhead too

**Comment by joubertredrat** [comment]
@0xbaadf00d yes, on first post I saw this
> I think that is good ideia to display this as optional on repository listing

Other good option is set to chmod be numeric `755` or string representation `-rw-rw-r--`.

**Comment by bkcsoft** [comment]
@tboerger it keeps `777` which are the ones that are relevant (from the screenshot)

**Comment by joubertredrat** [comment]
Oh, I need to try to implement this now that I know to programming in golang

**Comment by lunny** [comment]
@joubertredrat but I think make it configurable is better.

**Comment by joubertredrat** [comment]
Hi @lunny 

This is the idea. For me, this can be enabled or not by configuration and in configuration define if you want to see numeric `755` or string representation `-rw-rw-r--`. What you think?

**Comment by lunny** [comment]
@joubertredrat and maybe not display that to keep compatible with before?

**Comment by joubertredrat** [comment]
@lunny Yes, if not defined on configuration, don't display by default
