### ISSUE TITLE
paste screenshot into wiki page

### ISSUE THREAD

**Issue by misterkey952** [go-gitea/gitea#32802]
### Description

paste screenshot into wiki page then I get an error.
![image](https://github.com/user-attachments/assets/305afbc1-6851-4cd4-83b0-0382ddccfd23)
and the details is
![image](https://github.com/user-attachments/assets/fb2185ed-7f0a-4815-b34e-215ec75ee3a5)

### Gitea Version

gitea-1.22.4-gogit-windows-4.0-amd64.exe

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

I run a binary version gitea-1.22.4-gogit-windows-4.0-amd64.exe on windows with Administrator user。

### Database

MySQL/MariaDB

**Comment by wxiaoguang** [comment]
Uploading files in wiki is not supported yet ..... duplicate:  Uploads on the wiki #574
