### ISSUE TITLE
Enable testifylint and tenv linters in golangci-lint

### ISSUE THREAD

**Issue by TheFox0x7** [go-gitea/gitea#32842]
### Feature Description

[I have contributed this change to Forgejo](https://codeberg.org/forgejo/forgejo/pulls/4535) and I would like to upstream it to Gitea.

Let me know what's the best/recommended way to do this as it did end up large and not pleasant to look through.

I have a few more things that I want to upstream, but I'll have to see first how the codebases differ - maybe they aren't needed.

**Comment by silverwind** [comment]
One question: Why remove `skip-dirs`? As far as I'm aware, it may increase linting performance by not having golangci-lint crawl into `node_modules` etc. I'm not totally sure it works because it may need https://github.com/golang/go/issues/42965, but I figured at least it can not hurt.

**Comment by silverwind** [comment]
Also, I'm not sure whether the refactor for https://github.com/Antonboom/testifylint#require-error is really justified. It may be more useful being able to see "all errors" instead of just the first.

**Comment by silverwind** [comment]
Yeah I would suggest disabling `require-error` in your port, it's too much churn for questionable benefit. I guess with that rule disabled, the diff will be pretty managable, right?
