### ISSUE TITLE
REGISTRATION ACCOUNTS WITH GOOGLE OAUTH AND I ALLOW

### ISSUE THREAD

**Issue by icesai** [go-gitea/gitea#3284]
- Gitea version (or commit ref):289cd1c
- Git version:2.1.4
- Operating system:CentOS Linux release 7.4.1708
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:
no
## Description
I have to DISABLE_REGISTRATION.
I don't want  everyone to be members by  themself.
I want to login by using  google oauth2 .
Is it anyway to REGISTRATION  accounts which only i allow?
or, some anthoer good ideas?

**Comment by mohammed90** [comment]
Create a local account for them along with the OAuth2 account.
The same issue is tracked at #2768

**Comment by icesai** [comment]
thank you
