### ISSUE TITLE
Incorrect job status agreggations

### ISSUE THREAD

**Issue by TheFox0x7** [go-gitea/gitea#32857]
### Description

I believe AggregateJobStatus works incorrectly. First [found and reported in fork](https://codeberg.org/forgejo/forgejo/issues/3916).

Currently aggregation can return one of 4 states for a  job:
- Failure if all jobs are done and one is a fail
- Success if all jobs are done and none failed
- Waiting if none are running or done
- Finally running if none of the above apply

It ignores cancellations, blocks and skips completely despite those being states which might represent the run best - such as skip as an aggregate result when all jobs are completed and were skipped.

Rough reproducer is at: https://demo.gitea.com/TheFox0x7/bad-aggregation/actions and the github version https://github.com/TheFox0x7/repro. 

### Gitea Version

9264811217

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

![image](https://github.com/user-attachments/assets/f5728015-a644-43a1-b69d-dd9890b3e61b)

### How are you running Gitea?

I used demo site to demonstrate the issue.

### Database

None

**Comment by wxiaoguang** [comment]
I can see there are at least 2 problems here:
 
1. backend doesn't return "cancelled" status (`AggregateJobStatus`)
2. frontend doesn't support rendering "cancelled" icon & status (`templates/repo/actions/status.tmpl`, `web_src/js/components/ActionRunStatus.vue`)

**Comment by wxiaoguang** [comment]
Maybe this could work better:  Fix incomplete Actions status aggregations #32859
