### ISSUE TITLE
Change pprof labels to be conformat with prometheus spec

### ISSUE THREAD

**Issue by TheFox0x7** [go-gitea/gitea#32854]
### Feature Description

This would be [another port of my changes](https://codeberg.org/forgejo/forgejo/pulls/2933).

There are systems, like pyroscope allowing for continuous profiling which do not allow for `-` in labels leading to upload failure.

To resolve this names like `process-description` can be changed either to `processDescription` or `process_description`.

**Comment by silverwind** [comment]
Can you link to some docs that confirms that regex?

**Comment by wxiaoguang** [comment]
If I understand correctly, these "labels" are designed for internal profiling/tracing only, there is no guarantee that these names will always be stable or compatible. Should we really expose these labels to external systems? (I even can't remember where&when we exposed them)

**Comment by wxiaoguang** [comment]
> The labels are included in pprof endpoints and having them compatible would enable someone interested to continuously gather profiles. Current labels prevent importing goroutine profiles, rest works fine. It might be only grafana stack issue - Otel has profiles on experimental phase so I can't rely on it for a hard spec.

Maybe we should introduce a new function like this:

```
func withGracefulLifecycleLabel(ctx, lifecycleName) { 
    return pprof.WithLabels(ctx, pprof.Labels("graceful_lifecycle", lifecycleName))
}

terminateCtx = withGracefulLifecycleLabel(terminateCtx, "with-terminate") 
```

Then we only need to manage the one name in `withGracefulLifecycleLabel`, and we can put more comments (with the spec link) on that function.

**Comment by wxiaoguang** [comment]
Or introduce a const like `const DescriptionPProfLabel` and add comments there?
