### ISSUE TITLE
Unified primary button colors

### ISSUE THREAD

**Issue by silverwind** [go-gitea/gitea#32871]
Currently we are inconsistent with primary buttons. Code button is green, merge button and new issue button are primary.

<img width="119" alt="Screenshot 2024-12-17 at 05 59 29" src="https://github.com/user-attachments/assets/3065c547-b72e-4fc7-a8f6-9d2986bacd04" />
<img width="268" alt="Screenshot 2024-12-17 at 05 59 46" src="https://github.com/user-attachments/assets/53ce86dc-f536-468c-8b90-31673eff8fb9" />
<img width="159" alt="Screenshot 2024-12-17 at 05 59 37" src="https://github.com/user-attachments/assets/65a0c232-f738-4219-9371-c3095742db0f" />

I feel like all primary buttons should be the same color. The easiest way would be to make the code button primary as well. Or we do it like GitHub and make primary buttons green (diverging from primary links which are blue). I'm undecided whether green or primary (default blue) would be better.

**Comment by hiifong** [comment]
To be honest, I prefer green

**Comment by wxiaoguang** [comment]
> To be honest, I prefer green

GitHub uses green because its primary color is green.

Gitea's primary color is blue.

**Comment by lunny** [comment]
So maybe change it to blue?

Using green as the primary button color for Gitea could clash with its green logo, making the interface feel monotonous. Blue provides a complementary contrast, helping buttons stand out clearly while maintaining a balanced design. GitHub uses green buttons because its black logo allows for contrast; for Gitea, blue achieves a similar effect.

**Comment by xxfogs** [comment]
"Sync fork" too should use primary

![image](https://github.com/user-attachments/assets/79c09c74-679a-4b9b-a84c-59925fded81f)

If primary is in use for buttons, the theme can be adjusted to anyone's preferences

**Comment by wxiaoguang** [comment]
->  Use primary as button color #32949
