### ISSUE TITLE
When Administrator is logged in it should be visual different from normal user

### ISSUE THREAD

**Issue by xor-gate** [go-gitea/gitea#32885]
### Feature Description

When a user has the site administrator access rights a banner should be displayed so for users with two accounts e.g `xor-gate` and `xor-gate-admin` the `-admin` account with site administrator rights webgui should display a warning in a red box that all mutations are with the Admin account. This makes it more aware when I have developer hat on and devops admin hat on. I have attached a screenshot with a HTML/CSS hack (still not good) how I think this can be displayed.

I can look into the backend part to emit the correct HTML/CSS but I would need somebody to create the correct HTML/CSS.

### Screenshots

![Untitled](https://github.com/user-attachments/assets/c783f721-4b86-485a-9f7b-64eb6d26d70b)

**Comment by lunny** [comment]
I can see another two solutions
- A different top bar  background color for the administration account
- Combine an administrator small logo with the user's avatar in the top right bar.

**Comment by xor-gate** [comment]
Yeah that sounds better, and less GUI intrusive. If the navbar has different color is also enough. Then no UI element has to be added.

**Comment by xor-gate** [comment]
<img width="798" alt="Screenshot 2024-12-18 at 21 02 15" src="https://github.com/user-attachments/assets/748eee83-a7e2-4a06-9121-f82e2fa95b70" />

This is a draft with light-theme. Now I have just hacked to insert 100% red style inline in the HTML. 

With dark theme we need to invert the text if we want 100% red

<img width="1222" alt="Screenshot 2024-12-18 at 21 04 03" src="https://github.com/user-attachments/assets/78a34dba-57cb-4a41-a411-bb34cbe8e859" />

**Comment by xor-gate** [comment]
I think I would prefer the background color of the navbar and not a additional icon. It should be a little more visual intrusive than just a small icon.

**Comment by xor-gate** [comment]
As there is no general consensus. I'm closing this.
