### ISSUE TITLE
Cannot set labels inherited from organization via API

### ISSUE THREAD

**Issue by hwaastad** [go-gitea/gitea#32891]
### Description

Hi,
I'm not sure if this is a bug or a feature request.
Having labels defined in Organization, labels are available to use on a repo issue/pr
However, using API, labels are not accessible

I would like to be able to add labels inherited from org to issues/pull requests using API

### Gitea Version

1.22.6

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

Running Gitea docker container.( in k8s)

### Database

MySQL/MariaDB

**Comment by Zettat123** [comment]
I think this bug is related to #30943. We should also query label names from the org. I'll create a PR to fix it.
