### ISSUE TITLE
First time access to the dashboard is very slow

### ISSUE THREAD

**Issue by inbjo** [go-gitea/gitea#32903]
### Description

The phenomenon is that the first access to the dashboard is very slow, it takes tens of seconds, the second access is faster, I turned on the sql debug mode and found the longest took thirty seconds. Here is what I found by `\d+\.\d{4,}s` regular to get the SQL slow log statement.

The slow response seems to be caused by a slow sql, let me know if you need any other more detailed info!

2024/12/19 11:15:13 .../webhook/hooktask.go:185:FindUndeliveredHookTaskIDs() [I] [SQL] SELECT id FROM `hook_task` WHERE (is_delivered=?) AND (id > ?) ORDER BY `id` ASC LIMIT 100 [false 0] - 1.871860973s

2024/12/19 11:15:20 models/repo.go:215:CheckRepoStats() [W] [Slow SQL Query] SELECT `issue`.id FROM `issue` WHERE `issue`.num_comments!=(SELECT COUNT(*) FROM `comment` WHERE issue_id=`issue`.id AND type=0) [] - 8.436927296s

2024/12/19 11:16:17 ...ties/user_heatmap.go:72:getUserHeatmapData() [W] [Slow SQL Query] SELECT created_unix DIV 900 * 900 AS timestamp, count(user_id) as contributions FROM `action` WHERE act_user_id IN (SELECT `user`.id FROM `user` WHERE (keep_activity_private=? AND visibility IN (?,?)) OR id=? OR (type=? AND `user`.id IN (SELECT org_id FROM team_user WHERE uid=?))) AND repo_id IN (SELECT id FROM repository WHERE (`repository`.is_private=? AND `repository`.owner_id NOT IN (SELECT id FROM `user` WHERE type=? AND visibility IN (?))) OR `repository`.id IN (SELECT repo_id FROM `access` WHERE `access`.user_id=? AND `access`.mode>?) OR `repository`.id IN (SELECT `team_repo`.repo_id FROM team_repo INNER JOIN team_user ON `team_user`.team_id = `team_repo`.team_id WHERE `team_user`.uid=?) OR `repository`.owner_id=? OR (`repository`.is_private=? AND `repository`.owner_id IN (SELECT `org_user`.org_id FROM org_user WHERE `org_user`.uid=?))) AND user_id=? AND act_user_id=? AND (created_unix > ?) GROUP BY timestamp ORDER BY timestamp [false public limited 98 1 98 false 1 private 98 0 98 98 false 98 98 98 1703042145] - 31.661594759s

2024/12/19 11:16:20 ...activities/action.go:465:GetFeeds() [W] [Slow SQL Query] SELECT `id`, `user_id`, `op_type`, `act_user_id`, `repo_id`, `comment_id`, `is_deleted`, `ref_name`, `is_private`, `content`, `created_unix` FROM `action` WHERE act_user_id IN (SELECT `user`.id FROM `user` WHERE (keep_activity_private=? AND visibility IN (?,?)) OR id=? OR (type=? AND `user`.id IN (SELECT org_id FROM team_user WHERE uid=?))) AND repo_id IN (SELECT id FROM repository WHERE (`repository`.is_private=? AND `repository`.owner_id NOT IN (SELECT id FROM `user` WHERE type=? AND visibility IN (?))) OR `repository`.id IN (SELECT repo_id FROM `access` WHERE `access`.user_id=? AND `access`.mode>?) OR `repository`.id IN (SELECT `team_repo`.repo_id FROM team_repo INNER JOIN team_user ON `team_user`.team_id = `team_repo`.team_id WHERE `team_user`.uid=?) OR `repository`.owner_id=? OR (`repository`.is_private=? AND `repository`.owner_id IN (SELECT `org_user`.org_id FROM org_user WHERE `org_user`.uid=?))) AND user_id=? AND is_deleted=? ORDER BY `action`.`created_unix` DESC LIMIT 20 [false public limited 98 1 98 false 1 private 98 0 98 98 false 98 98 false] - 3.460767331s

### Gitea Version

1.22.6

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

2.38.1

### Operating System

centos7

### How are you running Gitea?

systemd

### Database

MySQL/MariaDB

**Comment by lunny** [comment]
Hi, I think the problem has been resolved in v1.23.0-rc0.

**Comment by inbjo** [comment]
> Hi, I think the problem has been resolved in v1.23.0-rc0.

I'll try to upgrade when the official 1.23.0 version is released
