### ISSUE TITLE
1.23.0-rc0 Site Administration not accessible

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#32917]
### Description

Try to access site administration as an admin user results in a 404 (Not found or not authorized).

### Gitea Version

1.23.0-rc0, also 1.23-nightly (2024-12-19)

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

dockerr

### Database

SQLite

**Comment by iFrozenPhoenix** [comment]
ok, had a custom head template and the admin url changed from 1.22 to 1.23

**Comment by lunny** [comment]
I updated the blog to add it to the break change part. https://blog.gitea.com/release-of-1.23.0-rc0/#major-breaking-changes
