### ISSUE TITLE
Wrong documentation link on webhooks repository settings page

### ISSUE THREAD

**Issue by Exagone313** [go-gitea/gitea#3291]
- Gitea version (or commit ref): v1.3.2 (latest master is concerned too)

## Description

When editing repository settings, on the webhooks page, there is a link that says:

"Learn more in the [webhooks guide](https://godoc.org/code.gitea.io/sdk/gitea)."

The link is defined here: https://github.com/go-gitea/gitea/blob/10b54df2b2efa539fbaa0bf624e81cb5da99f97a/routers/repo/webhook.go#L36
Used here in (en-US) locale: https://github.com/go-gitea/gitea/blob/50b7ba1b70d6b92a4bf7dbcaaa7ba5b904d398c2/options/locale/locale_en-US.ini#L934

I think the correct link is https://docs.gitea.io/en-us/webhooks/ but notice that this link may be localized, and I don't know how to deal with that (this would need to edit every locale accordingly I guess, if you don't have particular code for this, but maybe linking to en-us link is fine).

I'm going to submit a PR for changing this link like I described here.

**Comment by lunny** [comment]
resolved by #3292
