### ISSUE TITLE
Compressed Actions logs are not uploaded to object store

### ISSUE THREAD

**Issue by techknowlogick** [go-gitea/gitea#32926]
### Description

Gitea.com is configured to use zstd compression, as well as minio storage. While other assets that are configured to use minio, are uploaded to the object store, it seems that when the compression type is modified that it isn't uploaded. I see the compressed logs on disk still.

```ini
# ...
[actions]
ENABLED = true
STORAGE_TYPE=gitea_com_prod
LOG_COMPRESSION=zstd

[repo-archive]
STORAGE_TYPE=gitea_com_prod

[storage.actions_artifact]
STORAGE_TYPE=gitea_com_prod

[storage.gitea_com_prod]
STORAGE_TYPE = minio
# ...
```

Creating an issue for this so it doesn't get lost to the sands of time.

### Gitea Version

dc8f59baa54d4f47edab6feb76a6903947584326 (although it's been happening for longer than this commit)

### Can you reproduce the bug on the Gitea demo site?

Yes

### Git Version

2.43.5

### Operating System

Rocky Linux 9

### How are you running Gitea?

The binary from dl.gitea.com/gitea/nightly is downloaded on a periodic basis, and it's run using the systemd config copied from the docs.

### Database

MySQL/MariaDB

**Comment by Zettat123** [comment]
Maybe the configuration should be
```ini
# ...
[actions]
ENABLED = true
LOG_COMPRESSION=zstd

[storage.actions_log]
STORAGE_TYPE=gitea_com_prod
```
https://github.com/go-gitea/gitea/blob/f44712f22bc7bfce049c64c27f60453ff1e41a5c/modules/setting/actions.go#L92-L96
