### ISSUE TITLE
The Chinese translation prompt message of sync fork is wrong

### ISSUE THREAD

**Issue by hiifong** [go-gitea/gitea#32936]
### Description

![image](https://github.com/user-attachments/assets/7cc05967-b495-4229-919b-760c8d777a70)
![image](https://github.com/user-attachments/assets/f385c5bd-f537-416e-aed2-5f2943f6e906)

### Gitea Version

1.23-rc0

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

./gitea web

### Database

None

**Comment by wxiaoguang** [comment]
->  Fix locale #32937
