### ISSUE TITLE
"Code" button on the repository page is hard-coded to be green

### ISSUE THREAD

**Issue by xxfogs** [go-gitea/gitea#32948]
### Description

As the title suggests.

### Screenshots

![image](https://github.com/user-attachments/assets/9ba9bad1-a5e8-4d8a-a296-c65ecadcef7c)
![image](https://github.com/user-attachments/assets/5f58810e-0741-4306-b3e1-3161c7991f2c)

### Reproduction on Gitea Demo

![image](https://github.com/user-attachments/assets/9c4abc4a-8313-48c3-ad2a-3d655e3197de)

### Gitea Version

1.23.0+rc0

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

Debian GNU/Linux 12

### Browser Version

Firefox Browser ESR 128.5.0esr (64-bit)

**Comment by wxiaoguang** [comment]
Yup, it should use primary color ( Unified primary button colors #32871 )
