### ISSUE TITLE
RPC failed: curl 56 Recv failed: Connection was aborted

### ISSUE THREAD

**Issue by lukewatts** [go-gitea/gitea#3294]
- Gitea version (or commit ref): 1.3.0
- Git version: 2.13.2.windows.1
- Operating system: Windows 10
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant

## Description
I'm getting the following error while trying to push to a newly created repo:

```
git push -u origin master
Counting objects: 1016, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (951/951), done.
error: RPC failed; curl 56 Recv failure: Connection was aborted
fatal: The remote end hung up unexpectedly
Writing objects: 100% (1016/1016), 8.75 MiB | 4.70 MiB/s, done.
Total 1016 (delta 159), reused 0 (delta 0)
fatal: The remote end hung up unexpectedly
Everything **up-to-date**
```

The repo I'm pushing up is only 51.2MB

Gitea is installed on a server on our local network. Other repositories are pushing up just fine

**Comment by lafriks** [comment]
Do you see any errors in stdout, gitea.log or serv.log?

**Comment by lukewatts** [comment]
Nope. The logs are pretty bare. Only output what's enabled.

I'm just currently checking our proxy settings. The `curl 56 Recv failure` could be a proxy issue...

**Comment by lukewatts** [comment]
No it's not the proxy. I can curl directly using the same proxy address as in `git config --global http.proxy`

**Comment by lukewatts** [comment]
Figured it out after some StackOverflowing.

I had a an .exe file which was 15.5MB in the repo, therefor I needed to set my global `http.postBuffer` setting

From git bash ran:
```
git config --global http.postBuffer 157286400
```

Then everything worked fine!

Hope that help someone else

**Comment by Tchikadzegiorgi** [comment]
help

**Comment by Tchikadzegiorgi** [comment]
i have a same problem but dont anderstend how to run this git config --global http.postBuffer 157286400

**Comment by Ceebox** [comment]
@Tchikadzegiorgi Run it in Git Bash
