### ISSUE TITLE
Gitea docker container nightly cannot start

### ISSUE THREAD

**Issue by stuzer05** [go-gitea/gitea#32954]
### Description

Possible because of this https://github.com/go-gitea/gitea/pull/32924

```
/usr/bin/entrypoint: exec: line 38: /bin/s6-svscan: not found
```

### Gitea Version

image id 9981acd570bf

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

docker

### Database

None

**Comment by stuzer05** [comment]
```
apk add --no-cache s6
```

fixed the problem

**Comment by stuzer05** [comment]
Actually the path was the problem, `/bin/s6-svscan` -> `/usr/bin/s6-svscan`

Created a PR https://github.com/go-gitea/gitea/pull/32955

**Comment by pmainvil** [comment]
After updating image to gitea-latest, I get the following error on a Synology DSM 7.2.1 and the container stops.

/usr/bin/entrypoint: exec: line 38: /bin/s6-svscan: not found

**Comment by techknowlogick** [comment]
@pmainvil Your configuration has a hardcoded endpoint, please either let the image use the default, or update it to the new location.

**Comment by pmainvil** [comment]
No change to the "gitea/gitea latest" image settings loaded many months ago.  I simply upgraded the image to the latest version and it stopped working.  I had done multiple updates without over time without any problems.

![Image](https://github.com/user-attachments/assets/50d51b04-bded-41b9-bb0a-1ed5e3e78efc)

**Comment by dgarrison63** [comment]
I'm having the exact same issue as @pmainvil in that I upgraded gitea which is running on my Synology NAS.  Prior to the upgrade of the image, no issues at all.

The error messages i'm getting are this: /usr/bin/entrypoint: exec: line 38: /bin/s6-svscan: not found

I have not hardcoded anything and just left everything at the defaults in terms of entrypoint.

**Comment by titleistfour** [comment]
Exactly the same issue for me.  No changes from the default.  An update on Synology DSM 7.2.1 just broke my gitea container with the same error message: /usr/bin/entrypoint: exec: line 38: /bin/s6-svscan: not found

**Comment by titleistfour** [comment]
I ended up reverting to a previous specific tag version and that got my container back online.

**Comment by pmainvil** [comment]
Reverted to 1.23.0 and got it working.

**Comment by le-rou** [comment]
Same for me: Synology NAS, Portainer, same error message. I didn't set up anything custom. However, I noticed that the CMD was correct in the image, but not in the container - turned out, there was an override after all.
Fixed it like this:
- open gitea container
- click duplicate/edit
- under advanced: set Command and Entrypoint to default instead of override
- deployed under new name for safety

**Comment by pmainvil** [comment]
Was about to try your workaround, but updated/tested latest (1.23.3) and it worked OK.  All from container creation using the Container Manager.
