### ISSUE TITLE
Day ago count is wrong in dashboard

### ISSUE THREAD

**Issue by kebox7** [go-gitea/gitea#32981]
### Description

In some cases, the dashboard incorrectly counts the days that have passed. The screenshots below show the different cases:

**1. Correct (Now)**
![Sample 1](https://github.com/user-attachments/assets/7cd0d71f-d0d0-41e7-b6ed-73fca0c3b6a2)

**3. Wrong**
![Sample 2](https://github.com/user-attachments/assets/ef8c1cf2-3e35-40ef-83cb-08e4c0a3948c)

**4. Wrong**
![Sample 3](https://github.com/user-attachments/assets/c168a162-82cf-4f13-8119-36a1254abba9)

**6. Wrong**
![Sample 4](https://github.com/user-attachments/assets/68135014-5d18-40cd-b654-06ef68e0efec)

**7. Correct**
![Sample 5](https://github.com/user-attachments/assets/8be9d7a3-b1c4-4672-9f07-2f9dc4c0050d)

### Gitea Version

1.22.4

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

https://github.com/go-gitea/gitea/releases/download/v1.22.4/gitea-1.22.4-linux-amd64

Running on CentOS Linux 7 (Core)

### Database

SQLite

**Comment by wxiaoguang** [comment]
It has been fixed in 1.22.6 and 1.23-rc0
