### ISSUE TITLE
404 The page you are trying to reach either does not exist or you are not authorized to view it.

### ISSUE THREAD

**Issue by smeltsov** [go-gitea/gitea#32992]
### Description

Organisation
-- (1) Project
-- Repository 1
---- (2) Project for repo1
-- Repository 2
---- (3) Project for repo2

I am trying to create new issue within (2) but assign to project (1), after "Create Issue" you will get Error "404. The page you are trying to reach either does not exist or you are not authorized to view it."

### Gitea Version

1.22.6

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

![Bild_2024-12-26_124217552](https://github.com/user-attachments/assets/dd3338c7-633c-4778-8119-1bc7ac6b815e)

### Git Version

default of gitea

### Operating System

Ubuntu

### How are you running Gitea?

actuall docker image with ubuntu under windows 11

### Database

MSSQL

**Comment by wxiaoguang** [comment]
I guess it is because the return URL is not right ...... the "org project" + "create issue project and redirect back" has bugs.
