### ISSUE TITLE
Admin tip cover the dropdown icon

### ISSUE THREAD

**Issue by yp05327** [go-gitea/gitea#32991]
### Description

From : https://github.com/go-gitea/gitea/pull/32927
In my browser:
![image](https://github.com/user-attachments/assets/3b03c39c-c522-4552-97b4-00cfdaeea083)
In the PR's description:
![image](https://github.com/user-attachments/assets/8459710d-44ed-42a2-a327-3bcdf7c0512b)

It seems that the admin tip cover the dropdown icon

### Gitea Version

latest

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

build

### Database

None

**Comment by wxiaoguang** [comment]
Try to make it smaller:


```diff
diff --git a/web_src/css/modules/navbar.css b/web_src/css/modules/navbar.css
index b5bc95b058..b60d25977d 100644
--- a/web_src/css/modules/navbar.css
+++ b/web_src/css/modules/navbar.css
@@ -103,11 +103,11 @@
 #navbar .ui.dropdown .navbar-profile-admin {
   display: block;
   position: absolute;
-  font-size: 10px;
+  font-size: 9px;
   font-weight: var(--font-weight-bold);
   color: var(--color-nav-bg);
   background: var(--color-primary);
-  padding: 2px 4px;
+  padding: 2px 3px;
   border-radius: 10px;
   top: -1px;
   left: 18px;
```

**Comment by yp05327** [comment]
Maybe an icon or a border is better?
If it is a word ‘admin’ here, in other languages it maybe very long?

**Comment by wxiaoguang** [comment]
> If it is a word ‘admin’ here, in other languages it maybe very long?


![image](https://github.com/user-attachments/assets/2873c0ef-598b-4498-863f-441de03d4cbf)

**Comment by yp05327** [comment]
Personally, I prefer using an icon like sparkle-fill or sparkles-fill or something else, not a const word. Of cause, it is acceptable adjusting the font size.

**Comment by wxiaoguang** [comment]
> I prefer using an icon like sparkle-fill or sparkles-fill or something

I didn't find a suitable icon to show that "the current user is an admin", if the icon's meaning is not clear, it would mislead & confuse users.
