### ISSUE TITLE
Update the ref

### ISSUE THREAD

**Issue by utenus** [go-gitea/gitea#33003]
### Description

On the user side, nothing changed. Neither the permissions nor any updates. One day everything was ok and the next morning it was  errors, unfortunately. Of course, only one person has access to the repository and the repository itself is as private. Perhaps there is some error on official server.

```bash
> git push origin main:main
remote: error: cannot update the ref 'refs/heads/main': unable to append to './logs/refs/heads/main': Permission denied        

 ! [remote rejected] main -> main (failed to update ref)
error: failed to push some refs to 'gitea.com:repo/repo.git'
```

### Gitea Version

I don't know

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

It official gitea server.

### Database

None

**Comment by wxiaoguang** [comment]
> ```shell
>  unable to append to './logs/refs/heads/main': Permission denied  
> ```

The filesystem permission (chown/chmod) is not right in your git repositories.

**Comment by wxiaoguang** [comment]
> ### Can you reproduce the bug on the Gitea demo site?
> 
> Yes

Which repo on the demo site to reproduce?


> ### How are you running Gitea?
> 
> It official gitea server.
> error: failed to push some refs to 'gitea.com:repo/repo.git'

Which repo reproduces the error? `gitea.com:repo/repo.git` ? It seems that `https://gitea.com/repo/repo` doesn't exist.

**Comment by utenus** [comment]
@wxiaoguang I didn't know what to mark in the case of the gitea demo because issue is related to a private hidden repository on official gitea.

**Comment by wxiaoguang** [comment]
Then maybe you need to describe the problem clearly and tell the site admin of "gitea.com" that you need help with your private repo.

**Comment by utenus** [comment]
Maybe this is the solution. The question is how to contact them because I didn't see a place for such contact through their website.

**Comment by lunny** [comment]
Please send an email to support@gitea.com.

**Comment by techknowlogick** [comment]
Closing this as I believe I've received a support request for this and resolved it. Please lmk if that wasn't you and the issue still persists.
