### ISSUE TITLE
Pull Request List - Relative Dates Wrong

### ISSUE THREAD

**Issue by vektorblake** [go-gitea/gitea#33011]
### Description

Some of the relative dates shown on the `/pulls` list are incorrect. This example shows "13 days ago", when a hover reveals the real date is nearly a year in the past (today: Dec 27 2024, PR date: Jan 19, 2024).

![image](https://github.com/user-attachments/assets/ead17f70-056d-44e8-9792-18b0b7aac700)

### Gitea Version

1.22.3

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

Built to our own server privately

### Database

MySQL/MariaDB

**Comment by lunny** [comment]
If you can reproduce that in the demo site, can you put the link to that repository?

**Comment by wxiaoguang** [comment]
It has been fixed in 1.22.6 and 1.23-rc0
