### ISSUE TITLE
Create issue API endpoint responds with invalid URL

### ISSUE THREAD

**Issue by witten** [go-gitea/gitea#3302]
- Gitea version (or commit ref): 2f8c65c from https://hub.docker.com/r/gitea/gitea/
- Git version: 2.15.0
- Operating system: Debian GNU/Linux 9 (stretch) + Docker 17.12.0-ce
- Database:
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes
  - [x] No (create account is 500ing)
  - [ ] Not relevant
- Logs:

```
[Macaron] 2018-01-05 04:31:49: Started POST /api/v1/repos/myuser/myproject/issues for 76.121.104.139
[Macaron] 2018-01-05 04:31:49: Completed POST /api/v1/repos/myuser/myproject/issues 201 Created in 74.513327ms
```

## Description

When I create an issue via the API, I get back a response that includes an issue URL that 404s:

```
$ curl --request POST https://example.org/api/v1/repos/myuser/myproject/issues --user myuser:password --header "Accept: application/json" --header "Content-Type: application/json" --data '{ "body": "Test", "closed": false, "title": "Test" }' 
{"id":64,"url":"https://example.org/api/v1/repos/myuser/myproject/issues/64","number":48,"user":{"id":6,"login":"myuser","full_name":"","email":"myuser@noreply.example.org","avatar_url":"https://example.org/avatars/6","username":"myuser"},"title":"Test","body":"Test","labels":[],"milestone":null,"assignee":null,"state":"open","comments":0,"created_at":"2018-01-05T04:24:23Z","updated_at":"2018-01-05T04:24:23Z","pull_request":null}
```

Expected response: A working issue URL for the newly created issue.

It appears that the problem is that the "id" value is being substituted into the URL instead of the "number" field. If instead I go to the URL corresponding to the number value, `https://example.org/api/v1/repos/myuser/myproject/issues/48`, then it loads the newly created issue properly.

**Comment by lunny** [comment]
duplicated with #3297 and resolved by #3298
