### ISSUE TITLE
Autocomplete for issue does not work when creating a new pull request.

### ISSUE THREAD

**Issue by jelmore1674** [go-gitea/gitea#33026]
### Description

Whenever I create a pull request, the autocomplete for the issue to reference does not work. However, if I create a pull request, then edit it works as expected.

### Gitea Version

1.23-rc

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

Screenshots are from the demo site.

## Creating Pulll Request
<img width="1388" alt="image" src="https://github.com/user-attachments/assets/c3e025b0-cfb1-4b03-a7ff-51a5c6b93066" />

## Editing Pull Request
<img width="1013" alt="image" src="https://github.com/user-attachments/assets/bf2bb4d2-0c07-4d37-909e-ad0b0a4f65eb" />

### Git Version

2.45.2

### Operating System

rocky-linux 9

### How are you running Gitea?

Docker Compose

### Database

PostgreSQL

**Comment by wxiaoguang** [comment]
->  Make issue suggestion work for new PR page #33035
