### ISSUE TITLE
Cannot select "Initialize Repository" when creating a repo

### ISSUE THREAD

**Issue by Zettat123** [go-gitea/gitea#33060]
### Description

Cannot select "Initialize Repository"

![image](https://github.com/user-attachments/assets/2a89c93c-efef-4858-868b-8045427884b7)

### Gitea Version

latest

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

https://demo.gitea.com/

### Database

None

**Comment by lunny** [comment]
Caused by #32872

**Comment by wxiaoguang** [comment]
I am fixing it

**Comment by wxiaoguang** [comment]
->  Fix unittest and repo create bug #33061
