### ISSUE TITLE
explore repository wrong port number during port-forward

### ISSUE THREAD

**Issue by laoshaw** [go-gitea/gitea#3309]
I ssh forward a local port 5000 to the default 3000 of gitea on the remote server, everything works well, except that when I visit "explore" and click on the repositories on the page, they're "hard-coded" to port 3000 instead of 5000, so none of those repositories are accessible locally.

other stuff works fine though.

**Comment by lunny** [comment]
You can change them on `custom/conf/app.ini`.

**Comment by laoshaw** [comment]
yes the problem is that, you must use the same port for both local and the gitea(server, i.e. app.ini), if I forward a local port 5000 to gitea's 3000, then it won't work. 

anyway I can always forward 5000 to 5000 and it will work for now, still gitea should be seamless for port-forwarding at the explore page.

**Comment by lafriks** [comment]
You need such config options:
```
HTTP_PORT = 3000
ROOT_URL = http://your-domain-or-ip:5000/
```
