### ISSUE TITLE
Fuzzy search labels  when adding them to issues/PR's

### ISSUE THREAD

**Issue by mkungla** [go-gitea/gitea#3315]
- Gitea version (or commit ref): *
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

Would be nice to have fuzzy search labels when adding these to issues or PR's.
e.g fusejs

**Comment by noerw** [comment]
I'm looking to implement this, can someone help me get started? @silverwind

- Looks like these issue/pull filterable dropdowns are implemented via semantic dropdown. I don't find where these dropdowns are initiailized. Any pointers?
- Semantic dropdown [supports fuzzy search](https://semantic-ui.com/modules/dropdown.html#/settings) via `fullTextSearch` setting , is there a non-obvious reason this isn't enabled?
- Other filterable dropdowns (e.g. repo branch/tag selector) support fuzzy searching. They are implemented via `initFilterSearchDropdown()` or `initFilterBranchTagDropdown()` or a custom Vue component that (somewhat) supports fuzzy searching. Are there non-obvious obstacles to port the issue-property menus to these components?

**Comment by silverwind** [comment]
I think most dropdowns are initialized via HTML only. I never dealth with these parts but I assume there must be a way to specify option in HTML too. If it's not possible, I guess you'd have to initialize them via JS.

**Comment by noerw** [comment]
this was implemented somewhere around 1.15
