### ISSUE TITLE
New user does not see changes on dashboard

### ISSUE THREAD

**Issue by ThAchi1** [go-gitea/gitea#3343]
- Gitea version (or commit ref): 1.3.2
- Git version: 2.11.0
- Operating system: debian 9
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x ] No (CAN'T CREATE ADMIN ACCOUNT)
  - [ ] Not relevant
- Log gist:

## Description

On a new system I create admin1. From this account I create user1 and user2. Then I create a organization named team1. I add user1 and user2 to team1. I create a new repository for team1 named repo1. Then I do some things with this repository with different users. On the dashboard I see all changes, no matter with witch user I am logged in. This is what I expect.
THEN I create a third user with name user3. I add this user to team1. The dashboard for user3 shows nothing, it's empty. Then I commit changes from user3. User1 and user2 see all the changes as before. User3 sees only his changes.

Repeated this 3 times from scratch installation in different ways. The result is always as described above.

## Screenshots

team1 with user1 and user2:
![2018-01-10 16_07_12-gitea_ git with a cup of tea](https://user-images.githubusercontent.com/19573138/34781357-e91f4804-f625-11e7-8a29-9bbc23c7200b.png)
User2 sees what user1 and team1 do (same for user1):
![2018-01-10 16_10_51-user2 - dashboard - gitea_ git with a cup of tea](https://user-images.githubusercontent.com/19573138/34781398-043a5c32-f626-11e7-965e-5af152a00962.png)
Add user3 to team1:
![2018-01-10 16_13_44-gitea_ git with a cup of tea](https://user-images.githubusercontent.com/19573138/34781416-11259a06-f626-11e7-8f63-a5cbccec93b7.png)
User1 sees what all the others do, including user3 (same for user2):
![2018-01-10 16_16_55-user1 - dashboard - gitea_ git with a cup of tea](https://user-images.githubusercontent.com/19573138/34781466-303214f6-f626-11e7-9e80-c4a7cf6e06fa.png)
User3 only sees what he has done:
![2018-01-10 16_17_23-user3 - dashboard - gitea_ git with a cup of tea](https://user-images.githubusercontent.com/19573138/34781474-34d4ccba-f626-11e7-8eed-476a93acfb22.png)

**Comment by thehowl** [comment]
IIRC, user3 does not see his changes because being added later he does not auto-watch all the repos, thus the activities by other users do not show up. So he needs to watch the repos to see them on his dashboard. One quick workaround for this is from the dashboard, click the dropdown that says user3, and switch to the org: that should show all activity from the org, even before the user was added

**Comment by lafriks** [comment]
If user2 commits after user3 is added does user3 sees that commit?

**Comment by ThAchi1** [comment]
No. And that is exactly the problem I have. My first thought was, that user3 sees only the changes after he was created. Unfortunately user3 sees only his own changes, no matter what other users commit after the creation of user3. User1 and user2 see all changes, even the commits of user3.

**Comment by techknowlogick** [comment]
Closed with #4201
