### ISSUE TITLE
Repository

### ISSUE THREAD

**Issue by kevinl8890** [go-gitea/gitea#3344]
- Gitea version (or commit ref): 1.3.2
- Git version: 2.7.4
- Operating system: Ubuntu 16.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X] No
  - [ ] Not relevant
- Log gist:

## Description

 When I push a file to gitea repository the file owner be change to Bo-Yi Wu please check it in my attachment.

## Screenshots

![gitea_bugreport](https://user-images.githubusercontent.com/24778762/34784005-06204c22-f668-11e7-82c8-59cf81c59000.png)

**Comment by thehowl** [comment]
That is not the repository owner, simply who created the commit.

**Comment by kevinl8890** [comment]
Oh.. but the creator was wrong.
I am commit it but it show Bo-Yi Wu.

**Comment by kevinl8890** [comment]
I correct this problem.
It normal when I setting the user.name and user.email.
If the user.name and user.email are empty the creator will be Bo-Yi Wu. XD

**Comment by thehowl** [comment]
If user.name and user.email are not set on your user's gitconfig on your computer, then git AFAIK shouldn't even let you commit. Did you make the commit through the web gitea UI?

**Comment by kevinl8890** [comment]
I am commit via linux console. All commit in command line.
Actually I clone the repository first then add a file to commit.

**Comment by thehowl** [comment]
Didn't this happen, since you hadn't set name and email?

![image](https://user-images.githubusercontent.com/4681308/34789631-4540fc0e-f63f-11e7-95d5-195bbc201e46.png)

**Comment by kevinl8890** [comment]
My case was happened in Alibaba cloud and following is my step.

1. I create a repository in gitea web ui.
2. I clone this repository into my Linux directory.
3. I add a file into this directory.
4. Commit
5. Push
6. See the wrong creator in gitea web ui.

**Comment by zeripath** [comment]
Are you making commits directly from a docker instance?

**Comment by appleboy** [comment]
Can't reproduce in my machine.

**Comment by zeripath** [comment]
@kevinl8890 What did you use to create your alibaba cloud instance?
