### ISSUE TITLE
Activation is needed (again) during login

### ISSUE THREAD

**Issue by pwFoo** [go-gitea/gitea#3350]
Hi,

I use Gitea behind a RevProxy with OTP (gitea.domain.tld) and can reach it direct with an internal URL (gitea.internal.domain.tld). I have to activate my account (again) during login or some other actions (I have to check...).

I don't know why the activated account have to be activated again by email verification. Why could the activation triggered again? Because of OTP (RevProxy remove the OTP, so gitea will just get username and password, login works fine) or different urls (gitea.domain.tld and gitea.internal.domain.tld)?

Any idea / hint how to check and solve that problem?

**Comment by pwFoo** [comment]
Auth method is ldap

**Comment by lafriks** [comment]
Most probably because you use multiple domains so when switching between them it asks for authorization again

**Comment by pwFoo** [comment]
Each domain asks for login, but why I get the message that my user have to be activated by activation email (again)? My User is activated and active used.

User activation should be fired one time (after user creation / during first login).
But I don't know when / why user activation is triggered by gitea.
