### ISSUE TITLE
 webhooks created on organizations triggered on PRs lack PR information on some events

### ISSUE THREAD

**Issue by juanpablo-santos** [go-gitea/gitea#3351]
- Gitea version (or commit ref): 1.3.2
- Git version: 2.14.3
- Operating system: using official docker image
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

webhooks created on organizations triggered on PRs lack PR information on some events

occurs at least on synchronized, label_cleared and label_updated events

**Comment by lunny** [comment]
Cannot reproduce this, could you give more details?

**Comment by juanpablo-santos** [comment]
Hi @lunny, we're using the Gitea ones

thx!

**Comment by juanpablo-santos** [comment]
Hi,

I'm closing the issue, as it isn't happening any more on http://try.gitea.org (don't know when got fixed, though, it's been a while since I followed up with the issue). Just ftr, I've just tried with https://try.gitea.io/perry123/perry123-test/pulls/1 and I've got the following events, all showing the requested information (`json.pull_request`, `json.sender`, etc.):

* 3533f64a-ce65-4a1f-9a52-768e0b046fe4: opened pull request
* 2de7a6a9-6139-4c74-9e94-cfd007fbf8dd: new push to PR branch
* d571becd-cc9f-4014-a716-c46b1bff9a4e: updated pull request
* 36a81d8d-09d2-4cca-8c6d-7e70b157b8c3: label assigned to PR
* d259b940-595b-422b-aeb8-b46a5b73f8c8: PR assigned

thx,
juan pablo
