### ISSUE TITLE
ESLint config + build fail if PR code does not follow the config

### ISSUE THREAD

**Issue by thehowl** [go-gitea/gitea#3353]
In an attempt to have JavaScript code that is not an unmanageable mess where there are even mixed `"` and `'` for string literals, I would propose to add an [eslint](https://eslint.org/) config to gitea; public/js/* would then be checked for errors by the CI, to ensure that we have a consistent style in the JavaScript code.

**Comment by lafriks** [comment]
With prettier.io ;)

**Comment by silverwind** [comment]
Sounds good. You can add the `eslint` dependency to [`package.json`](https://github.com/go-gitea/gitea/blob/master/package.json), just need to make sure `npm install` runs before testing.

**Comment by sapk** [comment]
I think it is done now (https://github.com/go-gitea/gitea/blob/master/.eslintrc).
If I am mistaken feel free to re-open.

**Comment by silverwind** [comment]
Yes it is. `make build` will fail on ESLint errors.
