### ISSUE TITLE
Initial configuration screen - outdated info about databases

### ISSUE THREAD

**Issue by ShalokShalom** [go-gitea/gitea#3357]
See for yourself: TiDB is missing in the drop down, while MSSQL in the description text. 
![screenshot_20180112_115532](https://user-images.githubusercontent.com/6344099/34871998-b38dc6dc-f78f-11e7-8c93-41757db64c13.png)

**Comment by sapk** [comment]
tidb need a build tag to be available.

**Comment by ShalokShalom** [comment]
Ah, I see. That is the official binary, so is there a chance to enable this by default?

**Comment by sapk** [comment]
We could. For now, It is consider as experimental.
We could add it to integrations tests now that they are more complete to validate the use and activate it for releases.

**Comment by ShalokShalom** [comment]
Fine, great. ^-^
