### ISSUE TITLE
Configuration trigger for locales

### ISSUE THREAD

**Issue by ShalokShalom** [go-gitea/gitea#3363]
Currently, there seems no trigger to set the default locale.
I also suggest one additional config option, which adjusts the interface language according to the browser language.

**Comment by wxiaoguang** [comment]
It has been fixed. The first one will be used in the app.ini

**Comment by wxiaoguang** [comment]
Introduced by  Remove legacy unmaintained packages, refactor to support change default locale #19308 
* https://github.com/go-gitea/gitea/pull/19308
