### ISSUE TITLE
Description on Docker Hub is boring

### ISSUE THREAD

**Issue by kolaente** [go-gitea/gitea#3365]
IMHO, the description on https://hub.docker.com/r/gitea/gitea/ is really boring. It should have at least a link to the website and a short description about what Gitea is. Also a link to docs, maybe even an example docker compose file to quickly set it up (I have one which I'd be happy to share) would be great.

What do you think?

**Comment by lunny** [comment]
@kolaente I think you are right. Please give the text what you think it should be. And any others could also give more idea. After this issue end, we can change that description.

**Comment by thehowl** [comment]
quickly wrote a draft: https://gist.github.com/thehowl/cd950ae33a8519439ac58a644037bb1f

**Comment by kolaente** [comment]
Dockerfile (with description):

Use this dockerfile to get up and running quickly. You should change mysql user- and root password. When installing, you can reference the database container as host `db`.

This configuration will publicly expose ports `3000` and `22`.

```Dockerfile
version: '2'
services:
  web:
    image: gitea/gitea:1.3.2
    volumes:
      - ./data:/data
    ports:
      - "3000:3000"
      - "22:22"
    depends_on:
      - db
    restart: always
  db:
    image: mariadb:10
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=changeme
      - MYSQL_DATABASE=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=changeme
    volumes:
      - ./db/:/var/lib/mysql
```

@Off-Topic: is it currently possible to configure gitea with environment variables?

**Comment by sapk** [comment]
@kolaente yes done in #2201 and #2791

**Comment by xy2z** [comment]
@kolaente Shouldn't the image be `gitea/gitea:latest`?

**Comment by sapk** [comment]
If I am not mistaken, latest is on master that is not stable. We could provide a "stable" tag or maybe switch latest to last "stable" version. It reflect the branch on git master -> latest is unstable and branches for each version that receive backport when needed. Gitea at the start of the fork, receive a lot of change and was to be consider a work in progress as we break things maybe now we could start to provide stable instance.

**Comment by kolaente** [comment]
I think master is generally stable, but not guaranteed. So I wont nessecary use `master` (aka `latest`) in production.

**Comment by kolaente** [comment]
So, can we update it then to the description provided by @thehowl ?
@maintainers

**Comment by lunny** [comment]
@kolaente Since nobody have further idea, I think yes.

**Comment by kolaente** [comment]
Ping (again)

> So, can we update it then to the description provided by @thehowl ? @maintainers

**Comment by lunny** [comment]
@kolaente @thehowl done.

**Comment by kolaente** [comment]
Great, thanks!
