### ISSUE TITLE
Raw/Edit for the README in project overview

### ISSUE THREAD

**Issue by ShalokShalom** [go-gitea/gitea#3369]
I like this panel: 

![screenshot_20180114_151125](https://user-images.githubusercontent.com/6344099/34916779-c145fe2a-f93d-11e7-9a5d-7ab98688b0fc.png)

Here: https://try.gitea.io/ZeroNet/ZeroNet

This was always something that made me really upset in Github and confuses some users. 
The bar there makes it easier and simpler to contribute to the README, link it and so on.

**Comment by lunny** [comment]
Thanks for your like. We will close this one and please feel free to reopen it.
