### ISSUE TITLE
Hardcoded "localhost" error in 1.3.2

### ISSUE THREAD

**Issue by sailfish009** [go-gitea/gitea#3372]
- Gitea version (or commit ref): 1.3.2
- Git version: 2.15.1
- Operating system: Ubuntu 14.x
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

After update to 1.3.2 from 1.3.0, 
I couldn't load my local network gitea repository with mouse click.

NOTE: FOR EXAMPLE, my local network gitea server IP is 192.168.100.100, my computer IP is 192.168.100.99

Before (with v1.3.0)
http://192.168.100.100:3000/sailfish009/hello_world -- (mouse click) --> http://192.168.100.100:3000/sailfish009/hello_world

After (with v1.3.2)
http://192.168.100.100:3000/sailfish009/hello_world -- (mouse click) --> http://localhost:3000/sailfish009/hello_world

i couldn't load the repository because it is not localhost, it must  be 192.168.100.100 instead of "localhost".

**Comment by lafriks** [comment]
You should set that in app.ini root url to what you need

**Comment by sailfish009** [comment]
i didn't set app.ini in v1.3.0, why should i set app.ini in v1.3.2

**Comment by sailfish009** [comment]
downloaded app.ini.sample, didn't touched anything. temp work around.

$ cd [directory where gitea found]
$ wget https://raw.githubusercontent.com/go-gitea/gitea/master/custom/conf/app.ini.sample
$ mv app.ini.sample app.ini

**Comment by techknowlogick** [comment]
`app.ini` is needed so that Gitea knows what configuration values to use.

As you were able to find a work around can this issue be closed?
