### ISSUE TITLE
Uncommitable after renaming

### ISSUE THREAD

**Issue by ShalokShalom** [go-gitea/gitea#3378]
1) I renamed the repo
2) This error occurs: 
![screenshot_20180116_002425](https://user-images.githubusercontent.com/6344099/34965377-ddc02028-fa53-11e7-9bbb-388157f421f8.png)

**Comment by ShalokShalom** [comment]
By the way: The error message is German, anyway which language I choose in the UI

**Comment by lafriks** [comment]
That message come from git command so most probably depends on server locale

**Comment by ShalokShalom** [comment]
Thanks
