### ISSUE TITLE
@mentions on pull-request don't auto-populate

### ISSUE THREAD

**Issue by lukewatts** [go-gitea/gitea#3379]
- Gitea version (or commit ref): 1.8.3
- Git version: 2.15.1
- Operating system: Win 10 Pro

When my team try to @mention eachother no dropdown with suggestions appears. 

I think @mention should suggest users as you type after the @ symbol as it does here on Github

**Comment by thehowl** [comment]
Coming in 1.4.0 https://github.com/go-gitea/gitea/pull/3136 :)
