### ISSUE TITLE
Error gomail: could not send email 1: Auth: 535 5.7.8 Error: authentication failed: while sending SMTP mails

### ISSUE THREAD

**Issue by marove2000** [go-gitea/gitea#3380]
- Gitea version (or commit ref): d29aa76
- Git version: 2.15.1
- Operating system: Arch Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

When trying to activate sending mail via SMTP with the following configuration:

[mailer]
ENABLED = true
HOST    = mail.host.com:587
FROM    = no-reply@host.com
USER    = no-reply@host.com
PASSWD  = `$password#`

I get the error: gomail: could not send email 1: Auth: 535 5.7.8 Error: authentication failed:

## Solution

I have special characters in the SMTP password  ($ and #). Quoting the password:
```
PASSWD = `#password$`
```
was the solution.

I just want to post the solution if anybody has the same issue. Also I would ask if this should be documented in the app.ini documentation. I can imagine that similar errors can occur with the database-password.

**Comment by lafriks** [comment]
That would be good to document that in configuration cheatsheet and/or app.ini.sample

**Comment by marove2000** [comment]
I've made a pull request addressing this issue in sample.app.ini and it's documentation.

**Comment by techknowlogick** [comment]
Closing this as documentation has been merged. Thanks @marove2000 😄

**Comment by ascandella** [comment]
I just ran into this myself, except I never edited the config app.ini manually, it was done during the setup phase. It seems that (in `install.go`) we should write out a value surrounded by backticks to prevent this.

The simplest change would just be to backtick-surround mailer.PASSWD, but that strikes me as a band-aid. Perhaps the install code should be modified to use some helper that detects special characters (wrapping `SetValue()`) and auto-wraps them.

I'm happy to put together a PR and test if that sounds sane.
