### ISSUE TITLE
Autolinking as specified by the GFM spec

### ISSUE THREAD

**Issue by thehowl** [go-gitea/gitea#3381]
After some more research about how GitHub handles autolinking, I wound up finding the proper [GFM](https://github.github.com/gfm/#autolinks-extension-) spec. One of the goals of #3354 is that of porting over functionality, which was previously provided by JavaScript, into Go, which is why I do not intend to include this as part of the PR, seeing as that is already quite big. However, once it is merged, it might be good to replace the `linkProcessor` in `modules/markup/html.go` with a proper processor following the GFM specification - which should hopefully solve once and for all all issues regarding autolinking not working.

This would also fix #3095.

cc/ @ypnos

**Comment by techknowlogick** [comment]
Closing per merged PR
