### ISSUE TITLE
Provide upload and create new file buttons on empty repo

### ISSUE THREAD

**Issue by ShalokShalom** [go-gitea/gitea#3388]
This is also one thing, which seriously drove my crazy in the past about Github:

http://funkyimg.com/i/2Bm7a.png (Github is not accepting my screenshot, whysoever) 

I suggest offering these "Create new file" and "Upload file(s)" buttons here, instead of hiding them for no reason.

**Comment by lafriks** [comment]
You need to git init repo to be able to add anything to it, as you have chosen not to initialize it when creating, than I don't see how adding file would work as there is no repo yet to add to

**Comment by techknowlogick** [comment]
GitLab does this. You can do the "create new file"/"upload file" in it. It'll init the repo for you.

In Gitea it kind already does this (adding in a readme/license), except it only gives one chance for users to do this.

**Comment by lunny** [comment]
@lafriks we can init the repo if needed. I think it's a good idea to add this feature.

**Comment by ShalokShalom** [comment]
Yeah, cool ^-^

**Comment by ShalokShalom** [comment]
Is this still in consideration?

**Comment by lafriks** [comment]
It is but noone is currently working on that

**Comment by realies** [comment]
+1

**Comment by wxiaoguang** [comment]
It should have been fixed by:  Allow adding new files to an empty repo #24164
