### ISSUE TITLE
Security issue: scratch tokens are plaintext in the database

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#3389]
- Gitea version (or commit ref): 1.3.1
- Git version: 2.15.1
- Operating system: FreeBSD 11 x64
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

User scratch tokens are stored in plain text in the database. These should be encrypted because it will allow anyone with database access to grab the token and bypass 2 factor authentication. While not likely still should be considered an issue. I would also suggest in allowing for more than one token which would all be stored encrypted in some fashion in the database.

**Comment by ghost** [comment]
Any progress on resolving this?

**Comment by lunny** [comment]
Any suggest to resolve this problem?

**Comment by ghost** [comment]
I think for this you could store only the hashed or bcrypted value and handle it like a password. If the user loses said token then they just cannot recover their account, similar to how it works with GitHub if you lose your 2FA token.

**Comment by cezar97** [comment]
@lunny I agree with bcrypt: it's widely used and pretty secure: the interaction count is customizable for every need and uses salt by default. There are go implementations and lots of examples online: it shouldn't be too hard...

**Comment by TangentFoxy** [comment]
Another +1 for bcrypt as a valid, secure, and tuneable implementation for hashing. \^\^

**Comment by daviian** [comment]
@lunny @Guard13007 @cezar97 I suggest using the same KDF as we do for passwords. So PBKDF2 with SHA256. So we can almost copy/paste the hashing from user creation.
