### ISSUE TITLE
Mirror Repository have error commit count after sync

### ISSUE THREAD

**Issue by qianlongzt** [go-gitea/gitea#3391]
sorry for my pool english.

- Gitea version (or commit ref):  1.3.2 built with: bindata, sqlite
- Git version: 2.15.1
- Operating system: Ubuntu16.04 LTS
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io/qianlongzt/HDU-Guide/commits/branch/master
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

First Migration, commits count is right, if up-stream have more commits, after sync, mirror repository have error commit count

## Screenshots
![image](https://user-images.githubusercontent.com/18493471/35088310-5d4f8c4a-fc6e-11e7-9788-9bf7f77bc52a.png)

**Comment by lafriks** [comment]
Caching on mirror sync seems like are not reset

**Comment by qianlongzt** [comment]
![image](https://user-images.githubusercontent.com/18493471/35106402-159814e0-fca9-11e7-9d5d-dca0b81f13f6.png)


after a lot of sync, the count of commit is right. I set sync every hours(1h0m0s)

**Comment by lafriks** [comment]
Commit count is cached four 16 hours by default, so it will display correct count eventually

**Comment by cez81** [comment]
@lafriks Resolved in https://github.com/go-gitea/gitea/pull/4720
