### ISSUE TITLE
Gitea Issues - Attach files

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#3392]
- Gitea version (or commit ref): d29aa76
- Operating system: Windows
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [X] SQLite

## Description

I am trying to attach following files to an issue:
- Batch files (.bat files)
- Outlook Message files (.msg files)
- XML (.xml files)
- ZIP (.zip files)

and I have two kind of problems:
1) with Firefox v.57.0.4 it's not possible to attach zip files (even if it's present in the allowed types sections of app.ini file), I think that the problem is the mime type with which Firefox parse the zip files;
2) with any browser, I can't attach (batch, outlook message files and xml files). I tried to use the following configurations in app.ini:

```
[attachment]
; Whether attachments are enabled. Defaults to `true`
ENABLE = true
; Path for attachments. Defaults to `data/attachments`
PATH = data/attachments
; One or more allowed types, e.g. image/jpeg|image/png
ALLOWED_TYPES = image/jpeg|image/png|application/zip|application/gzip|application/x-gzip|application/x-gtar|application/x-tgz|application/x-compressed-tar|application/x-zip-compressed|application/x-7z-compressed|application/x-compressed|multipart/x-zip|application/octet-stream
; Max size of each file. Defaults to 32MB
MAX_SIZE = 10
; Max number of files per upload. Defaults to 10
MAX_FILES = 10
```

and

```
[attachment]
; Whether attachments are enabled. Defaults to `true`
ENABLE = true
; Path for attachments. Defaults to `data/attachments`
PATH = data/attachments
; One or more allowed types, e.g. image/jpeg|image/png
ALLOWED_TYPES = 
; Max size of each file. Defaults to 32MB
MAX_SIZE = 10
; Max number of files per upload. Defaults to 10
MAX_FILES = 10
```
but simply I can't attach those kind of files.

My question is: can you please let us attach any kind of files without checking the mime types (I suppose that it will solve also the Firefox problem)? Is there a workaround to attach any files in the actual version?

Thank you in advance

**Comment by lafriks** [comment]
To allow any files you can set `ALLOWED_TYPES = */*`

**Comment by ghost** [comment]
It works. Thank you very much @lafriks
