### ISSUE TITLE
unable to reconfigure gitea server AGAIN using the same email address

### ISSUE THREAD

**Issue by kaijajan** [go-gitea/gitea#3394]
- Gitea version (or commit ref): 1.3.2
- Git version: 2.13.2.windows.1
- Operating system: Windows 10 64
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

I tried to reinstall whole gitea thing after remove all files under gitea folder but gitea itself.
Then I attempt to configure the new gitea server with the same email address
The installation page prompt me the email has been used.
Any idea where I can remove all the settings from my computer?
Please help to fix the issue or please tell me where I can remove all gitea generate things

## Screenshots
https://imgur.com/a/rgIrh

**Comment by Megidd** [comment]
Probably you need to `DROP` the gitea database as well, before re-installing:

```
$ mysql -u root -p 
Enter password:
 
mysql> DROP DATABASE gitea;
Query OK, 50 rows affected (11.99 sec)
mysql> quit
Bye

$ 
```

**Comment by techknowlogick** [comment]
@kaijajan closing this ticket, please re-open if needed.
