### ISSUE TITLE
simple push email notification

### ISSUE THREAD

**Issue by luzik** [go-gitea/gitea#3397]
- Gitea version (or commit ref): 1.3.2
- Git version:
- Operating system: Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

It would be nice to have very simple email push notification made outside gitea and from inside of web interface to everyone that watch those repositories. Just simple email with gitea links to all commits included in push.
I found few other similar kinds, but those was more sophisticated ideas like diff in email or so.

**Comment by xor-gate** [comment]
An additional feature could be when a PR is created, and afterwards pushes are made into that PR branch pushes are notified.

**Comment by sapk** [comment]
If I have understand the need, It is now implemented. 
Feel free to re-open if it is not the case.

**Comment by thanegill** [comment]
@sapk Can you link to the documentation or PR that implements this?

**Comment by sapk** [comment]
@thanegill I may have gone to fast on this one. Gitea don't seems to send notification for git commit push.

**Comment by lunny** [comment]
@sapk https://github.com/go-gitea/gitea/blob/705b1e49a8b2ac8df377120f70f3548df15cdf49/modules/repofiles/action.go#L278

**Comment by sapk** [comment]
It doesn't seems to be implemented for email. Only to notify indexer and webhook.

**Comment by lunny** [comment]
@sapk OK. That's the problem.
