### ISSUE TITLE
Set environment variable branch name

### ISSUE THREAD

**Issue by m47730** [go-gitea/gitea#3398]
I'm using a post hook script to automatic deploy a project of mine, and i'm using environment variables to do a simple script.
Everything is working except in the variables i miss the branch name. Is it possible to add it?
Sorry, i'm very new to gitea and go, so i haven't made a pull request.
I think is a useful addition without any harm.

For reference: #316 and #317 

Thanks in advance

**Comment by lafriks** [comment]
You can already get branch name from ref
See: https://stackoverflow.com/questions/7351551/writing-a-git-post-receive-hook-to-deal-with-a-specific-branch

**Comment by m47730** [comment]
i completely missed this information!
I rewrote some line of the script and now it's working as i like!

Thanks
