### ISSUE TITLE
MSSQL Error trying to add user to org team

### ISSUE THREAD

**Issue by malweka** [go-gitea/gitea#3403]
- Gitea version (or commit ref): 1ce35724094f8edc124ffe4b4e1f06a99ad0c646
- Git version: 2.16
- Operating system: Windows Server 2012 R2
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist: 
[...routers/org/teams.go:107 TeamsAction()] [E] Action(add): mssql: Incorrect syntax near 'LIMIT'.
...
2018/01/20 14:02:41 [.../runtime/asm_amd64.s:509 call32()] [E] IsPublicMembership: mssql: Incorrect syntax near 'LIMIT'.

## Description

I'm using MS SQL Server 2014. Whenever  I try to add a user to an organization team. I get the error "mssql: Incorrect syntax near 'LIMIT'."

![error](https://user-images.githubusercontent.com/348391/35188683-3bb1c260-fe08-11e7-87be-ddaf0d808349.png)

The error is caused because  it's trying to run the following SQL statements:

``` 
SELECT * FROM team_user WHERE org_id=@p1 AND team_id=@p2 AND uid=@p3 LIMIT 1
SELECT * FROM org_user WHERE uid=@p1 AND org_id=@p2 LIMIT 1'
```
I was able to trace it to changes introduced on commit 515cdaa85d6087d91a61ebe74fae39e0c4bdf1c4 .  

file: models/org_team.go
```go
func isTeamMember(e Engine, orgID, teamID, userID int64) (bool, error) {
	return e.
		Where("org_id=?", orgID).
		And("team_id=?", teamID).
		And("uid=?", userID).
		Table("team_user").
		Exist()
}
```
and models/org.go
```go
func IsOrganizationMember(orgID, uid int64) (bool, error) {
	return x.
		Where("uid=?", uid).
		And("org_id=?", orgID).
		Table("org_user").
		Exist()
}

func IsPublicMembership(orgID, uid int64) (bool, error) {
	return x.
		Where("uid=?", uid).
		And("org_id=?", orgID).
		And("is_public=?", true).
		Table("org_user").
		Exist()
}
```
It looks like calling Exist() generate the code with LIMIT 1, which fails on MSSQL because it doesn't support LIMIT 1.  Reverting the changes to use  `Get(new(OrgUser))` fixes it. I'm assuming the error is coming from the ORM.

**Comment by lafriks** [comment]
@lunny this should be fixed in xorm
