### ISSUE TITLE
Add "no label" and "no milestone" filters

### ISSUE THREAD

**Issue by lofidevops** [go-gitea/gitea#3407]
- Gitea version (or commit ref):
- Git version: N/A
- Operating system: N/A
- Database (use `[x]`): N/A
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL) - URL pending
- Log gist: N/A

## Description

I am a project manager triaging issues. I want to filter for all issues without any label, and for all issues without any milestone, so that I know which issues I haven't yet triaged.

Related Gogs issues:
* https://github.com/gogits/gogs/issues/2622
* https://github.com/gogits/gogs/issues/1833
* https://github.com/gogits/gogs/issues/5014

## Suggested solution

* To the label filter list:
  * Add "No label" option
  * Rename "No selected label" to "All labels"
* To the milestone filter list:
  * Add "No milestone" option
  * Rename "No selected milestone" to "All milestones"

**Comment by dakira** [comment]
Yes, we need this. It would be such a time saver!

**Comment by bobemoe** [comment]
Any progress on this? Is there a workaround? Can I use the API to list the no-label and no-milestone issues or something?

**Comment by lunny** [comment]
Nobody are working on this I think.

**Comment by bobemoe** [comment]
Shame, it would be very useful.

I have found a way to do it with the API and the Linux JSON parser `jq`

```curl -sX GET "https://gitea.example.com/api/v1/repos/USER/REPO/issues" -H  "accept: application/json" | jq '.[] | select(.labels|length==0) | .number'```

This will list the issue numbers of all issues with no labels. It can quite easily be modified to work with milestones rather than labels.

**Comment by zeripath** [comment]
It's likely a very easy pr...

**Comment by bobemoe** [comment]
Maybe if you've got a dev env set up and are familiar with go and gitea ;) I'm thinking it would be much easier for me to extend the script to use the API to add a "needs attention" label to all the issues with no label OR milestone.

If I did that, could I add it to Gitea as a maintenance task or hook somehow without having to modify the code? (or cron it lol)

**Comment by kraptor** [comment]
This feature would be very nices to have...

**Comment by j123b567** [comment]
Also "no assignee" would be very helpfull.

**Comment by tyroneyeh** [comment]
Hello

Could try this patch https://github.com/tyroneyeh/gitea/commit/909cdc360f657daedf9a6cf23ad98f86e51eb1f6
![image](https://user-images.githubusercontent.com/1255041/174267605-33d62579-1e99-4502-b5be-bd88fe1b3100.png)
![image](https://user-images.githubusercontent.com/1255041/174267614-92857858-53f2-4819-9024-c1dd77ab3d65.png)

and in custom/templates/footer.tmpl add below script

```js
    var btn;
    if (btn = document.querySelector(".label-filter a")) {
        $('<a class="item">No lables</a>').on("click", function() {
            const labelids = "-"+ $(".label-filter-item").map(function(_, i) { return i.getAttribute("data-label-id"); }).get().join(",-");
            var labelsurl = "labels=", labelpos;
            if ((labelpos = location.search.indexOf(labelsurl)) > 0) {
                labelsurl = location.search.slice(labelpos);
                if ((labelpos = labelsurl.indexOf("&")) > 0)
                    return location.search = location.search.replace(labelsurl.slice(0, labelpos), "labels="+ labelids);
                return location.search = location.search.replace(labelsurl, "labels="+ labelids);
            }
            return location.search += (location.search.indexOf("?") == -1 ? "?" : "&") + labelsurl + labelids;
        }).insertAfter(btn);
    }
    if (btn = document.querySelector(".assignee-filter a")) {
        $('<a class="item">No assignees</a>').on("click", function() {
            const assigneeids = "-"+ $(".assignee-filter-item").map(function(_, i) { return i.getAttribute("data-assignee-id"); }).get().join(",-");
            var assigneeurl = "assignee=", assigneepos;
            if ((assigneepos = location.search.indexOf(assigneeurl)) > 0) {
                assigneeurl = location.search.slice(assigneepos);
                if ((assigneepos = assigneeurl.indexOf("&")) > 0)
                    return location.search = location.search.replace(assigneeurl.slice(0, assigneepos), "assignee="+ assigneeids);
                return location.search = location.search.replace(assigneeurl, "assignee="+ assigneeids);
            }
            return location.search += (location.search.indexOf("?") == -1 ? "?" : "&") + assigneeurl + assigneeids;
        }).insertAfter(btn);
    }
```
