### ISSUE TITLE
The use of dash (-) in repository names breaks cross-referencing in issues

### ISSUE THREAD

**Issue by djelenc** [go-gitea/gitea#3412]
- Gitea version (or commit ref): 82a7b02
- Git version: ?
- Operating system: irrelevant
- Database (use `[x]`): irrelevant
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes: see below
  - [ ] No
  - [ ] Not relevant
## Description

When you try to cross-reference an issue in a repository whose name contains a dash (`-˙ symbol), the automatic referencing breaks.

See here:
* [Cross-referencing when dash is used does not work](https://try.gitea.io/ZeroNet/ZeroNet/issues/3#issuecomment-1889)
* [Cross-referencing when dash is not used works](https://try.gitea.io/ZeroNet/ZeroNet/issues/3#issuecomment-1906)

Props to @lafriks for zeroing in the bug.

**Comment by HenrikBengtsson** [comment]
UPDATE 2018-01-26: For the issue in this comment, see Issue #3381 instead.

This appears to affect any URLs containing hyphens.  For example, in Gitea 1.3.2 the following URL:

* `http://singularity.lbl.gov/install-linux#build-an-rpm-from-source`

is rendered as [http://singularity.lbl.gov/install-linux#build](http://singularity.lbl.gov/install-linux#build-an-rpm-from-source)-an-rpm-from-source.  A workaround is to use Markdown links, e.g.

* `[http://singularity.lbl.gov/install-linux#build-an-rpm-from-source](http://singularity.lbl.gov/install-linux#build-an-rpm-from-source)`

**Comment by thehowl** [comment]
That is an entirely different issue: to solve these once and for all, I already opened #3381
