### ISSUE TITLE
Cannot show multi-lines of comment in the commit

### ISSUE THREAD

**Issue by liu-kan** [go-gitea/gitea#3427]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

Sometime, the commit comment is very long, and splited into multi-lines.
But username/projectName/commit/commitUUID can only show the first line, gogs shows multi-lines well. 
Can you please add this small feature?

## Screenshots
[Screenshots](https://ibb.co/koG9ib)

**Comment by lafriks** [comment]
Already implemented in #2980 and will be in release 1.4.0
