### ISSUE TITLE
Protecting a branch fails when branchname contains uppercase letters

### ISSUE THREAD

**Issue by Brezenabsalzer** [go-gitea/gitea#3428]
Hi,
I just noticed a strange behavior when protecting branches. It only works when the branch name contains lowercase letters only. Otherwise the branch will not be protected and users are able to push changes to the repo. The corresponding checkbox in the GUI is not checked as well. If it is checked again for a second time an error 500 is thrown.

- Gitea version (or commit ref): 1.3.2
- Git version: 2.16.1
- Operating system: Windows 7
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:
[..._protected_branch.go:171 SettingsProtectedBranchPost()] [E] UpdateProtectBranch: Insert: UNIQUE constraint failed: protected_branch.repo_id, protected_branch.branch_name

**Comment by thehowl** [comment]
Do you have two branches of the same name, although one has different casing? e.g. `master` and `MaSter`?
