### ISSUE TITLE
Can I change git command timeout through config file ?

### ISSUE THREAD

**Issue by comicfans** [go-gitea/gitea#3436]
Currently I have a huge git repo with many binaries , for easier use, we use web interface to download package (instead of git client or lfs ), and I'm facing git command timeout problem [original issue here](https://github.com/gogits/gogs/issues/4903)

Recently I've read that https://github.com/go-gitea/git/pull/104 is merged to makes git command timeout configurable , but I can not find any updates in config docs or gitea commit history, I wonder if this config option still not implemented on gitea side ?

**Comment by lunny** [comment]
I think someone could send a PR to add a option on `config.ini` to do that. It's a small PR and easy enough to do.
