### ISSUE TITLE
Dropbox login | ERROR 500

### ISSUE THREAD

**Issue by alexandrestein** [go-gitea/gitea#3437]
- Gitea version (or commit ref): f9a5cc4
- Git version: `2.15.0`
- Operating system: `Ubuntu Linux host but running in Docker with de standard latest image`
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No -> `the Dropbox login is not available`
  - [ ] Not relevant
- Log gist: 
I'm not sure what you're talking about but this looks to display the error:
``` log
[Macaron] 2018-01-31 11:50:35: Started GET /user/oauth2/dropbox for 145.239.14.126
[Macaron] 2018-01-31 11:50:35: Completed GET /user/oauth2/dropbox 307 Temporary Redirect in 1.948058ms
[Macaron] 2018-01-31 11:50:46: Started GET /user/oauth2/dropbox/callback?state=b809e90d-bfeb-48ec-9f4f-c591ed257bcc&code=t3gRdKRB6qgAAAAAAAAA3D9YWFDz1xUOvYjzvKtLzCU for 145.239.14.126
[Macaron] 2018-01-31 11:50:48: Completed GET /user/oauth2/dropbox/callback?state=b809e90d-bfeb-48ec-9f4f-c591ed257bcc&code=t3gRdKRB6qgAAAAAAAAA3D9YWFDz1xUOvYjzvKtLzCU 404 Not Found in 1.195064719s
[Macaron] 2018-01-31 11:50:48: Started GET /img/500.png for 145.239.14.126
```
## Description

When clicking on the Dropbox logo the navigation goes to the login page of Dropbox and valide the login.
But when I get back to the Gitea login page I get the error 500.

All other external login I deployed are working great.

## Screenshots

![capture d ecran de 2018-01-31 13-03-12](https://user-images.githubusercontent.com/5431025/35622162-23ac4b40-0687-11e8-8114-af0597330ba3.png)

**Comment by SuperSandro2000** [comment]
Reference: https://github.com/markbates/goth/issues/204 and https://www.dropbox.com/developers/reference/migration-guide
The goth library uses dropbox api v1 and it is no longer supported.

**Comment by SuperSandro2000** [comment]
https://github.com/markbates/goth/pull/205 the update has been merged into goth. 
https://github.com/markbates/goth/commit/bc7deaf077a50416cf3a23aa5903d2a7b5a30ada

**Comment by lunny** [comment]
Then we only need govendor update goth?

**Comment by SuperSandro2000** [comment]
I think so. I don't know about any api changes in goth. Just the URL endpoints got updated.
