### ISSUE TITLE
Ability to edit/remove already tracked issue time

### ISSUE THREAD

**Issue by xak2000** [go-gitea/gitea#3447]
## Description

It should be possible to edit or at least remove already tracked time.

For example:
- I can accidentally track wrong number (80h instead of 8h).
- I can forget to press "stop" button after "start" and remember this after two weeks.

And it should be possible to undo this or change these tracked values, or else it would be to dangerous function to use.

**Comment by jonasfranz** [comment]
I think that this is a duplicate of #2642.

> I can forget to press "stop" button after "start" and remember this after two weeks.

You could click on the "Cancel" button the abort the timestracking stopwatch.

**Comment by xak2000** [comment]
You are right, #2642 is the same.
