### ISSUE TITLE
gitlab oauth is broken because scope is not sent

### ISSUE THREAD

**Issue by captn3m0** [go-gitea/gitea#3449]
- Gitea version (or commit ref): `gitea/gitea:1.3.2`
- Git version: `2.13.5`
- Operating system: linux/amd64. Running using docker
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant (gitlab is not present as a authentication mechanism)
- Log gist:

## Description

GitLab OAuth does not work because scope is not sent as part of the authentication redirect. You can verify the issue on my gitea instance: <https://git.captnemo.in/user/oauth2/gitlab>

### Login Error at GitLab
![image](https://user-images.githubusercontent.com/584253/35748603-9315a9f6-0874-11e8-9924-1acc85310b34.png)

### Gitea Config

![image](https://user-images.githubusercontent.com/584253/35748619-ab6c2106-0874-11e8-94dc-df918546147c.png)

### GitLab App config
![image](https://user-images.githubusercontent.com/584253/35748671-d5a5a780-0874-11e8-9de9-16aa4319ac84.png)

**Comment by captn3m0** [comment]
Upgraded to the `1.4` docker image and the issue persists.

**Comment by internalfx** [comment]
I can confirm this issue on my system as well

**Comment by techknowlogick** [comment]
@captn3m0 I've just created a PR to pass the scope, however have you tried using OpenID Connect? I found that worked for me. The openid connect URL for gitlab is https://gitlab.com/.well-known/openid-configuration

**Comment by captn3m0** [comment]
Haven't tried it as I'm the only active user on my server. 

Thanks a lot for the PR :1st_place_medal:

**Comment by clarfonthey** [comment]
Also running into this problem.
