### ISSUE TITLE
Relaying to postfix - sslv3 alert bad certificate - SSL alert number 42

### ISSUE THREAD

**Issue by cljk** [go-gitea/gitea#3456]
- Gitea version (or commit ref):
`17655cd built with: bindata, sqlite`
- Git version:
- Operating system:
docker-image `gitea/gitea:latest`
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
have no admin rights or possibility to test
- Log gist:

## Description

I´m using the docker-image and tried configuring gitea to relay mails through my local postfix-installation.
relevant content of `app.ini`:
```
[mailer]
ENABLED = true
HOST    = 192.168.10.36:587
FROM    = git@vgb.org
USER    = git@vgb.org
PASSWD  =
```

`mail.log` of my postfix:
```
Feb  5 09:24:09 mail-db-um postfix/smtpd[32114]: connect from unknown[192.168.10.231]
Feb  5 09:24:09 mail-db-um postfix/smtpd[32114]: SSL_accept error from unknown[192.168.10.231]: 0
Feb  5 09:24:09 mail-db-um postfix/smtpd[32114]: warning: TLS library problem: error:14094412:SSL routines:ssl3_read_bytes:sslv3 alert bad certificate:s3_pkt.c:1487:SSL alert number 42:
Feb  5 09:24:09 mail-db-um postfix/smtpd[32114]: lost connection after STARTTLS from unknown[192.168.10.231]
Feb  5 09:24:09 mail-db-um postfix/smtpd[32114]: disconnect from unknown[192.168.10.231] ehlo=1 starttls=0/1 commands=1/2
```

The postfix server uses a valid ssl-cert (signed by letsencrypt) but not valid for the docker-instance (it´s valid for a DNS-name - not for the IP). So... essentialy from the perspective of gitea it´s NOT valid.... but I want it to relay nevertheless.... is that possible?

Could that be related to https://github.com/gophish/gophish/issues/171 ?

**Comment by lafriks** [comment]
You can set ~~`SKIP_VERIFY = false`~~
**edit:** `SKIP_VERIFY = true`

**Comment by cljk** [comment]
Ahhh... great

Essentially it was `SKIP_VERIFY = true` - but this worked ;-)

Thank you
