### ISSUE TITLE
welcome/install page sqlite path textbox default should be absolute

### ISSUE THREAD

**Issue by siochs** [go-gitea/gitea#3459]
- Gitea version (or commit ref): Gitea vb16c84d built with: bindata, sqlite
- Git version: 2.11.0
- Operating system: Debian GNU/Linux 9 (stretch)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
On Server:
```bash
$GiteaHome=/local/gitea
useradd -r -s /bin/bash -d $GiteaHome -m git
wget https://dl.gitea.io/gitea/master/gitea-master-linux-amd64 -O $GiteaHome/bin/gitea
chmod +x $GiteaHome/bin/gitea
chown -R git:git $GiteaHome
$GiteaHome/bin/gitea web
```
Browse welcome page, select SQLite and leave all the defaults. Create a rummy repo called testrepo. Add a public key for ssh authentication in Administration page. Then try this on the client:
```bash
git clone git@myserver:myuser/testrepo.git .
Cloning into '.'...
Gitea: Internal error
Failed to get repository: no such table: repository
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
```
This error can be fixed by editing /local/gitea/bin/custom/conf/app.ini
```
[database]
DB_TYPE  = sqlite3
HOST     = 127.0.0.1:3306
NAME     = gitea
USER     = gitea
PASSWD   =
SSL_MODE = disable
PATH     = /local/gitea/data/gitea.db (<- was data/gitea.db)
```
Well, this is not really a bug. But I think it would be nice to have the absolute path as default in the textbox for the database path on the welcome/install page:
![image](https://user-images.githubusercontent.com/5244312/35808018-d1997042-0a84-11e8-8485-1b3f0ddc8d4f.png)

## Note
This does not happen when running from docker:
```
docker run -p 3000:3000 gitea/gitea:latest
```
![image](https://user-images.githubusercontent.com/5244312/35808094-0e0b95fa-0a85-11e8-8e97-92ce476dd905.png)

**Comment by thehowl** [comment]
I disagree. Having a relative path is actually useful if moving gitea (its entire directory) to a new folder, or migrating the server. The docker image already handles the case and uses an absolute path from the configuration specified in the dockerfile.

**Comment by techknowlogick** [comment]
This is now the case
