### ISSUE TITLE
Allow custom regex patterns for linking external issues

### ISSUE THREAD

**Issue by tgdchmi2** [go-gitea/gitea#3468]
- Gitea version (or commit ref): 1.3.2
- Git version: 2.16.1
- Operating system: Linux
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
For external issue tracker: alphanumeric issue recognition does not work when:
- Key before the dash contains a number. Example: `BLG5-456`
- Key is enclosed in quotes. Example: `'BLG-456'` or `"BLG-456"`
- Key follows a slash: Example `BLG-123/BLG-564` (first key is recognized, second one not)

We think implementing so many additional 'rules' could lead to many false positives.
Thus we propose to add a third _External Issue Tracker Naming Style_ for specifying custom patterns to apply for matching issue keys. Then we could specify a pattern like `(WP-\d+)|(BLG5-\d+)` ourselves.
The matched group should then be used for replacing `{index}` in the _External Issue Tracker URL Format_.

**Comment by strk** [comment]
See also #7084 for an even more flexible mapping idea

**Comment by jonny64** [comment]
Hi, we have tasks/{uuid v4} as issue {index}, what should we do?
