### ISSUE TITLE
Downloading of artifacts (e.g. release files) using basic authentication

### ISSUE THREAD

**Issue by Skyr** [go-gitea/gitea#3473]
I'm running a private gitea instance (i.e. authentication is mandatory). For automatic deployment of released artifacts, I'd like to download them using wget. Unfortunately, it seems that basic authentication headers are not honored, `wget --user='...' --password='...' https://my.gitea/attachments/...` just downloads the login page.

Is there a way to allow this?

**Comment by thehowl** [comment]
Hey there, sorry about the delay:

wget apparently only sends the basic auth information on the second time around, if the first time fails (when making the req with no auth). So that means you have to pass `--auth-no-challenge` or use curl with the `-u username:password` option.

**Comment by Skyr** [comment]
Uh, this took a while for me to come back to this...

Thanks, this did the trick!
