### ISSUE TITLE
LDAP Bind: cannot put multiple attr for user filter

### ISSUE THREAD

**Issue by dolanor** [go-gitea/gitea#3479]
- Gitea version (or commit ref): 1.3.2+3-g88c363f
- Git version:
- Operating system: docker container in host Ubuntu 16.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

We can only use 1 `%s` in the LDAP user filter. If we try to match both the `uid` and the `mail`, the LDAP won't execute the query and will do nothing but show that it couldn't find the user, if you input both the username or the email.

Hence, a filter like this will work
```
(&(memberOf=cn=gitea,ou=apps,dc=mydomain,dc=com)(uid=%s))
```

But not this one
```
(&(memberOf=cn=gitea,ou=apps,dc=mydomain,dc=com)(|(uid=%s)(mail=%s)))
```

**Comment by lafriks** [comment]
Use `%[1]s` instead of `%s` than it should work

**Comment by dolanor** [comment]
!!!
Thank you! I forgot about that!
