### ISSUE TITLE
Mirrored repo releases sorted ascending order

### ISSUE THREAD

**Issue by cez81** [go-gitea/gitea#3496]
- Gitea version (or commit ref): 2cb4649 
- Git version: N/A
- Operating system: N/A
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL) https://try.gitea.io/cez81/gitea-releases/releases
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
From: https://discourse.gitea.io/t/is-there-a-way-to-report-bugs-outstide-github/207

After migrating a repository to Gitea releases are sorted in ascending order. The default behavior is to sort tag create time so it seems the tags when migrating should be done in reverse.

Related to: https://github.com/go-gitea/gitea/issues/3390

## Screenshots
![efbb7a32e03cfad56cad5c37e8c6c7d9747fcf6a_1_689x329](https://user-images.githubusercontent.com/9416498/36111753-785d9618-1027-11e8-832f-051c4b9f1598.png)

**Comment by lafriks** [comment]
Mirrored repositories should have been with tag creation time used... This should be bug
