### ISSUE TITLE
Swagger unable to make exemplary requests to prefixed Gitea instance

### ISSUE THREAD

**Issue by 0rzech** [go-gitea/gitea#3499]
- Gitea version (or commit ref): 1.3.2
- Git version: Not relevant
- Operating system: Not relevant
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
  - [x] Not relevant
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No, because it's installed in its own domain
  - [ ] Not relevant
- Log gist: Not relevant

## Description
When Gitea is not installed in its own domain (eg. `git.example.com`), but is prefixed instead (eg. `example.com/git`), the Swagger UI is unable to make exemplary `curl` requests.

URLs to `swagger.v1.json` itself are valid - `explore` field has `https://example.com/git/swagger.v1.json` value and the same address is under `[ Base URL: /api/v1 ]` line.

Nevertheless, Swagger UI tries to make requests to `https://example.com/api/v1/` endpoint, ignoring the `/git` prefix. This results with 404.

Maybe  `swagger.v1.json` could be changed to template containing line
```
"basePath": "{{AppSubUrl}}/api/v1",
```
instead of
```
"basePath": "/api/v1",
```
so [AppSubURL](https://github.com/go-gitea/gitea/blob/be1330ec89308f76557bd7fc708b1f16c703f429/modules/setting/setting.go#L87) is not ignored, or something?

**Comment by lunny** [comment]
If gitea is not installed, any URL except `/install` must not be visit, or it's a bug.

**Comment by 0rzech** [comment]
It happens after installation, when Gitea is deployed with path prefix (`AppSubURL`), eg. `gitea.io/try` instead of `try.gitea.io`, so when you click on `Explore` on main page, it redirects you to `gitea.io/try/explore/repos`.
