### ISSUE TITLE
Introduce latest link to latest release version on download page

### ISSUE THREAD

**Issue by juppin** [go-gitea/gitea#3500]
Hello great devs,

firstly, thank you for your hard and very good work on this project.

As i wrote an bash script to update my gitea to an new release, i thought about there could be a link to the latest release version or an file with the prefix of the newest version on the download page.

So i dont have to provide the download link to my script and it could run periodically with a cronjob...
Also the dockerfile could use it to build always with latest release version.

Many other project provide a latest link or a text file with latest release version.

What are your thoughts about that?

Greets juppi

**Comment by philfry** [comment]
github already provides a link to the latest stable release:
https://github.com/go-gitea/gitea/releases/latest

**Comment by juppin** [comment]
Here is my solution:
curl -s https://api.github.com/repos/go-gitea/gitea/releases/latest | grep 'browser_download_url' | cut -d\" -f4 | grep 'linux-amd64'
