### ISSUE TITLE
GET vs POST swagger.json

### ISSUE THREAD

**Issue by flyinprogrammer** [go-gitea/gitea#3501]
Was this file generated?
https://github.com/go-gitea/gitea/blob/fbdc00f46461bec024026b23f85fd1933ead6a96/public/swagger.v1.json#L3227

It seems this is using that json file:
https://try.gitea.io/api/swagger#/

But then what's going on between these three methods?
https://github.com/go-gitea/gitea/blob/master/routers/api/v1/repo/release.go#L16
https://github.com/go-gitea/gitea/blob/master/routers/api/v1/repo/release.go#L59
https://github.com/go-gitea/gitea/blob/master/routers/api/v1/repo/release.go#L99

And why is the swagger json wrong?
I'm happy to submit a patch - I just wasn't quite sure what was going on!

**Comment by sapk** [comment]
It was added/fixed by #3478 but it hadn't be backported to v1.4 branch since it is a new feature. I submitted #3811 to be sure that swagger is generated in PR that need it.

**Comment by adelowo** [comment]
I believe this can be closed
