### ISSUE TITLE
Setting external issue tracker in app.ini

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#3504]
It would be nice to be able to set those properties in app.ini to have inherited values for all projects in gitea:

![image](https://user-images.githubusercontent.com/5650043/36141535-5cf1a152-10a5-11e8-983e-6f766e4c562c.png)

**Comment by lafriks** [comment]
That can't be done using app.ini as this is per repository setting

**Comment by ghost** [comment]
It sounds reasonable to me to specify Tracker URL and Tracker Format in a place (app.ini or through UI) to avoid me to insert the same 2 pieces of information for all projects.

**Comment by lunny** [comment]
Maybe an API to set repository's external issue.
