### ISSUE TITLE
Wiki links do not handle spaces correctly

### ISSUE THREAD

**Issue by dakira** [go-gitea/gitea#3506]
- Gitea version (or commit ref): 4c9d9c2
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL) https://try.gitea.io/lunny/vscode/wiki
  - [ ] No
  - [ ] Not relevant

## Description

A link like `[[My Article]]` links to `My+Article.md` where it rather should link to `My-Article.md`. The Sidebar links in the above copy of the [microsoft/vscode-wiki](https://github.com/Microsoft/vscode-wiki/) are a good example.

**Comment by charlesreid1** [comment]
Looks like the relevant wiki template file is [templates/repo/wiki/view.tmpl on line 88](https://github.com/go-gitea/gitea/blob/ae30315a62644774756df64af0ca1ef405853a57/templates/repo/wiki/view.tmpl#L88), which contains:

```
{{.sidebarContent | Str2html}}
```

Str2html is a Go library [imported by helper.go](https://github.com/go-gitea/gitea/blob/2cb4649acf73ce9a7b6c2b3f707673d89a789f46/modules/templates/helper.go#L72) that turns markdown into HTML. It is unlikely the links are being improperly rendered by Str2html.

The sidebarContent variable is loaded and set in [wiki.go](https://github.com/go-gitea/gitea/blob/283e87d8145ac5dd61f86f61e347ffa684ac5684/routers/repo/wiki.go#L173-L186). 

This loads the sidebar content from [wikiContentsByName() (later in the same wiki.go file)](https://github.com/go-gitea/gitea/blob/283e87d8145ac5dd61f86f61e347ffa684ac5684/routers/repo/wiki.go#L100).

It renders the final sidebar content by calling markdown.RenderWiki(), which just calls [markup.RenderWiki in markup.go](https://github.com/go-gitea/gitea/blob/283e87d8145ac5dd61f86f61e347ffa684ac5684/modules/markup/markup.go#L65). This, in turn, calls a couple of layers of render functions, all in markup.go, until we get to the [render() function in markup.go](https://github.com/go-gitea/gitea/blob/283e87d8145ac5dd61f86f61e347ffa684ac5684/modules/markup/markup.go#L70), which contains the culprit line:

```
func render(parser Parser, rawBytes []byte, urlPrefix string, metas map[string]string, isWiki bool) []byte {
	urlPrefix = strings.Replace(urlPrefix, " ", "+", -1) /* <----- O NOES !!!!!! */
	result := parser.Render(rawBytes, urlPrefix, metas, isWiki)
	result = PostProcess(result, urlPrefix, metas, isWiki)
	return SanitizeBytes(result)
}
```

**Comment by dakira** [comment]
@charlesreid1 you are awesome. Thanks for the detailed explanation, too!
