### ISSUE TITLE
[Feature] add full name in issue assignee 

### ISSUE THREAD

**Issue by qianlongzt** [go-gitea/gitea#3509]
- Gitea version (or commit ref): 1.4.0 rc-1
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

if no full name , it's hard to know who are them in a big team.

## Screenshots

![image](https://user-images.githubusercontent.com/18493471/36165784-a22a35aa-112b-11e8-965a-c22d40a5ff7e.png)

**Comment by lafriks** [comment]
Fixed in #6710

**Comment by adelowo** [comment]
@lafriks Shouldn't this be closed since it's fixed already ?
