### ISSUE TITLE
XSS in issue and PR titles

### ISSUE THREAD

**Issue by pgaskin** [go-gitea/gitea#3510]
- Gitea version (or commit ref): 4c9d9c221a0628753f3dc16b469330ee096cbf18
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant

## Description
I discovered this issue while using my gitea instance.

When editing a title, it appears in the comments (`user changed title to .....`), which does not sanitize the html.

Demo (it's safe, just shows a message): https://try.gitea.io/geek1011/XSS/issues/2

**Comment by pgaskin** [comment]
To fix this issue, a translation (`issue.change_title_at`) needs to be changed, because it includes a `<b>` tag, which requires the use of the `Safe` filter, which skips sanitizing the HTML. After the translation and the template is changed, the title does not need to skip sanitation anymore.

**Comment by lafriks** [comment]
Title can be escaped separately
