### ISSUE TITLE
highDPI support for profile picture

### ISSUE THREAD

**Issue by suntorytimed** [go-gitea/gitea#3514]
- Gitea version (or commit ref):
6eaeb01
- Git version: irrelevant
- Operating system: irrelevant
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (https://try.gitea.io/user/settings/avatar and provide high resolution png (f.e. +500dpi) as custom avatar and use a display with highDPI scaling)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
A high resolution avatar is pixelated on highDPI displays (f.e. https://gitea.hibiki.eu/suntorytimes on a 4K UHD 32" display)

Offer/allow higherDPI profile pictures or SVG graphics.

To reproduce the bug it is necessary to set the highDPI scaling (f. e. on Gnome with Scale 200% in Displays settings) and use a profile with a high resolution avatar (https://gitea.hibiki.eu/suntorytimes)

## Screenshots
maybe you have to enlarge the screenshots to see the difference. To see the high resolution on a regular screen it is best to visit my profile page https://gitea.hibiki.eu/suntorytimes
Screenshot with highDPI:
![screenshot with highDPI](https://user-images.githubusercontent.com/2744377/36221064-32f88780-11bd-11e8-8e1e-9b1c7a582e79.png)

Screenshot with normal DPI:
![screenshot on regular DPI](https://user-images.githubusercontent.com/2744377/36221085-427a966c-11bd-11e8-8f77-8d1a00283048.png)

**Comment by silverwind** [comment]
The fix here should be pretty simple. The image is pulled from Gravatar with `s=290`. To support modern displays, I suggest changing this to 3 times the image width, e.g. `s=870` in this example. There are a few mobile devices that support 4 dppx, but those are primarily phones.

**Comment by suntorytimed** [comment]
@silverwind this would only fix the issue with Gravatar. A fix for "Use Custom Avatar" is also necessary (f.e. by saving the uploaded image in a higher resolution).

**Comment by suntorytimed** [comment]
Unfortunately I don't have a highDPI screen anymore to test this.

**Comment by lunny** [comment]
I think this has been resolved. @silverwind Could you help to confirm?

**Comment by silverwind** [comment]
Yes, all avatars on the UI are rendered with `AVATAR_RENDERED_SIZE_FACTOR` config option, which defaults to 3 currently, which is definitely HiDPI.
