### ISSUE TITLE
[[RFE] : creating users when authenticated through defined authentication source (like oauth2)

### ISSUE THREAD

**Issue by arrfab** [go-gitea/gitea#3520]
- Gitea version (or commit ref): 1.3.2
- Operating system: CentOS 7
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

Not a bug but request for enhancement : Actually, gitea permits users logged it through openid to have the corresponding user automatically created in gitea  : 
ENABLE_OPENID_SIGNIN = true
ENABLE_OPENID_SIGNUP = true

But it doens't work if one decides to create a authentication source like oauth2 (so tested with OpenID Connect on my side) : once authenticated, and redirected to gitea, it asks to either : 
 * login with existing (local) user (doesn't exist yet)
 * create a new user account

Of course I'd like to *only* allow people authenticated through oauth2 to sign in and so be registered automatically (so DISABLE_REGISTRATION  = true)

As discussed in #gitea on freenode, creating a RFE ticket here so that people can discuss it and/or track a potential status change

...

**Comment by schmitch** [comment]
is there actually some progress on this?

**Comment by jolheiser** [comment]
@schmitch Looks like #5123 is the current PR

**Comment by 6543** [comment]
closed by #5123
