### ISSUE TITLE
Wrong label on branch dropdown

### ISSUE THREAD

**Issue by vbrandl** [go-gitea/gitea#3525]
- Gitea version (or commit ref): 1.3.2
- Git version: 2.11.0
- Operating system: Debian 9
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant

https://try.gitea.io/foobar42/test-repository

## Description

When pushing a non-default branch (e.g. everything except `master`) to an empty repository, the dropdown menu for branch selection is wrongly labeled `master`. The dropdown menu shows the correct branches.

On further investigation I noticed that the link to the commits for the current branches links to https://try.gitea.io/foobar42/test-repository/commits/branch/master which produces a 404 error.

Also visiting the branches overview (https://try.gitea.io/foobar42/test-repository/branches/) lists `master` as default branch (which does not exist) but does not list the `develop` branch.

In general it seems like the UI gets confused when there is only one branch which at the same time is not the default branch.

## Screenshots

![](https://screenshotscdn.firefoxusercontent.com/images/7db18d81-edd5-4358-9903-5e1fca62ba09.png)

**Comment by lunny** [comment]
~should be fixed by #3190~
