### ISSUE TITLE
Git squash from Web interface

### ISSUE THREAD

**Issue by ange007** [go-gitea/gitea#3527]
- Gitea version (or commit ref): 283e87d 
- Git version: 2.15.0
- Operating system: Debian 9
- Database (use `[x]`):
  - [x] SQLite

## Description
Do you plan to implement a commits aggregation with Web interface? 
Since now in the case of using the **squash** function in the history of the commits, all the previous commits still remain.

![default](https://user-images.githubusercontent.com/2736539/36351299-352e465c-14b0-11e8-86c7-2c7c029bf54a.png)

Or am I probably not doing something right? I use an example from here: https://stackoverflow.com/a/5201642

**Comment by lafriks** [comment]
Or commits remain in source branch or in target branch?

**Comment by ange007** [comment]
I generate the union in the local repository and send the change to the remote repository.
In GitHub, this behavior worked fine (at least earlier).

**Comment by lafriks** [comment]
Can you create sample at try.gitea.io? In 1.4.0-rc1 there is already an option to squash merge pull request commits
