### ISSUE TITLE
PR acceptance blocked for PR creator

### ISSUE THREAD

**Issue by lucasfantacuci** [go-gitea/gitea#3543]
- Gitea version (or commit ref): 1.2.3

## Description

Our development team was thinking to use PR system to review our code, is there any feature to block the creator of the PR to accept it?

## Screenshots

![Image PR create](https://preview.ibb.co/gbEZ0n/Sem_t_tulo.jpg)
![Image PR accept](https://preview.ibb.co/nEsRD7/Sem_t_tulo.jpg)

On that example, the user administrator created de PR and accepted it.

**Comment by mbger** [comment]
Right now, I don't think so. Probably only possible when #2794 is done. But correct me if I'm wrong.

**Comment by thehowl** [comment]
I'm pretty sure that you can set a collaborator's permission to 'Read', and that should grant them ability to make PRs & such, but not push directly. Although, of course, a repo admin / someone with write access would be needed to merge the PR.

**Comment by lunny** [comment]
resolved by https://github.com/go-gitea/gitea/pull/3689

**Comment by cailyoung** [comment]
@lunny this is not resolved by #3689 - if the PR creator is on the whitelist they can merge. #2794 was abandoned. Is there any other issue in progress that would deliver this?

**Comment by lafriks** [comment]
@cailyoung you can set that PR needs at least one approval

**Comment by lunny** [comment]
@lafriks 's idea is correct.

**Comment by cailyoung** [comment]
@lafriks @lunny 

Apologies, we are not running 1.6.0 or newer. I will have a chat with the team here.

**Comment by cailyoung** [comment]
So #3748 fixes this - i.e. the PR creator cannot be an approver?

**Comment by lunny** [comment]
@cailyoung yes, one could not approve himself PR.
