### ISSUE TITLE
Mirror: if no content is fetched, updated should not be changed

### ISSUE THREAD

**Issue by Pofilo** [go-gitea/gitea#3548]
- Gitea version (or commit ref): 1.3.3
- Git version: _not relevant_
- Operating system: _not relevant_
- Database (use `[x]`):
  - [x] PostgreSQL
  - [x] MySQL
  - [x] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:
_not relevant_

## Description

In continuation of https://github.com/go-gitea/gitea/issues/1329 and of https://github.com/gogits/gogs/issues/4341 (of gogs project).

I think the updated time of mirrors in explore page should only be updated when someting changed in the mirror repo. This way, the firsts repos in the explore menu are only the most recently changed one.

They did it in this commit: https://github.com/gogits/gogs/commit/8d0417497b39aa196400d39c99bbd79cfb364f9f

## Screenshots

_not relevant_

**Comment by techknowlogick** [comment]
What's the policy on using code from gogs post-fork? If it's ok, I can create a PR with the linked code above.

I have >200 mirrored projects and so this ticket would be very useful for me.

**Comment by lunny** [comment]
There are some time for mirrored repositories.
1. Last Synced Time
2. Lastest Commit Time
3. Last Updated Time
Maybe theses times should be treated different

**Comment by appleboy** [comment]
PR: https://github.com/go-gitea/gitea/pull/3551
