### ISSUE TITLE
MySQL hints shown for PostgreSQL and MSSQL

### ISSUE THREAD

**Issue by bugreport0** [go-gitea/gitea#3556]
- Gitea version (or commit ref): 1.4.0rc1

## Description

On the installation page, under 'Initial configuration', the `db_helper` hint is only relevant to MySQL, but is also visible when selecting PostgreSQL or MSSQL. Hiding this hint when MySQL is not selected would allow to improve its wording.

**Comment by lafriks** [comment]
I think this was already fixed, please reopen if still problem
