### ISSUE TITLE
Too large webhook's response (>65K response) causes the webhook to be sent indefinitely

### ISSUE THREAD

**Issue by juanpablo-santos** [go-gitea/gitea#3561]
- Gitea version (or commit ref): 1.3.2
- Git version: 2.14
- Operating system: Gitea Docker image
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant (don't know if it is using mysql)
- Log gist:

## Description

For background see https://github.com/jenkinsci/generic-webhook-trigger-plugin/issues/42, but basically when a webhook's response is too big to not fit into hook_task.response_content (>65K response for MySQL), the webhook is fired, but it doesn't get updated (is_released, is_succeed and released remain at 0. Haven't tried to see what happens when there is too much information too on the request_content or the payload_content (e.g. a push webhook with way too many commits)

**Comment by lunny** [comment]
`hook_task.response_content` is designed as `TEXT` in mysql, which's max size is 65,535 bytes about 64KB. So maybe we should use `MEDIUMTEXT` or `LONGTEXT` for this column.

**Comment by juanpablo-santos** [comment]
Hi @lunny,

initially I thought of changing the column too, but according to https://stackoverflow.com/a/6766854, MEDIUMTEXT allows up to 16Mbits and LONGTEXT up to 64Gbits, which seemed too overkill to me. 

As the response appears to be used only on the webhook response panel, which by default only shows the last ten webhooks calls, and given that usually the system pinged will have its own logs too, wouldn't it make more sense to trim the response to, something like 60K, f.ex, and then append some text stating that the response has been trimmed? In anycase, we're not doing anything special with that table/columns, so going to MEDIUMTEXT would be ok for us.

also, what would happen now when the payload is too big to fit into `hook_task.payload_content`?

thanks,
juan pablo

**Comment by juanpablo-santos** [comment]
Hi,

in order to avoid the stale bot, anything else needed on this issue?

thx,
juan pablo

**Comment by kalvaro1215** [comment]
Hi,

I'm facing the same issue here :-)
Updating the SQL type to MEDIUMTEXT seems to be the correct approach but changing it may break futur Gitea's migration script...

**Comment by 42wim** [comment]
Fixed in #20038
