### ISSUE TITLE
Mirror settings -> interval: -1

### ISSUE THREAD

**Issue by Pofilo** [go-gitea/gitea#3562]
- Gitea version (or commit ref): _Not relevant_
- Git version: _Not relevant_
- Operating system: _Not relevant_ 
- Database (use `[x]`):
  - [x] PostgreSQL
  - [x] MySQL
  - [x] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist: _Not relevant_

## Description

Maybe I'm the only one needing this feature, I don't know. The mirror interval setting is taking a value in "h", "m", "s" (with 10 minutes as the minimal value on [try.gitea.io](https://try.gitea.io/) which is not printed but anyway).

Imagine I want a repo to be a mirror but without automatic syncing. This way, when a click to the `Sync Now` button, the equivalent of a `git pull` would be done. However, I don't want the sync to be automatic (just for my case, the branch would be deleted for example).

So the idea is that the mirror interval setting would take `-1` as a value and this would mean no automatic syncing. Is this a too specific and personal functionality or can it be useful to other people too ? (maybe I'm using the tools is a bad way ..)

## Screenshots

_Not relevant_

**Comment by lunny** [comment]
Have you tried 0?

**Comment by Pofilo** [comment]
Already tried with `0`, `-1` etc .. Same result : `Mirror interval is not valid`.

True on [try.gitea.io](https://try.gitea.io/).
