### ISSUE TITLE
Personal sidebar on the right not shown in IE 11

### ISSUE THREAD

**Issue by hhenkel** [go-gitea/gitea#3568]
- Gitea version (or commit ref): 1.4.0+rc1-12-g423c642 
- Git version: 2.15.0
- Operating system: Docker container from hub.docker.com
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes => Login using IE - no sidebar shown
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

When using IE 11 with gitea the personal sidebar on the right side is not shown, with firefox everyhting is okay. 

As a side note - the sidebar is shown in IE when choosing a organisation from the drop down

## Screenshots
IE 11 on try.gitea.io
![grafik](https://user-images.githubusercontent.com/2813782/36583784-615cb45a-1877-11e8-8605-5f29d92a478a.png)

Firefox on try.gitea.io
![grafik](https://user-images.githubusercontent.com/2813782/36583827-803eeffa-1877-11e8-81dc-60a74d1811af.png)

IE 11 on try.gitea.io with organisation selected
![grafik](https://user-images.githubusercontent.com/2813782/36583863-a3fe364e-1877-11e8-9c2b-2d12d000d6a5.png)

Firefox on try.gitea.io with organisation selected
![grafik](https://user-images.githubusercontent.com/2813782/36583870-abaa30e6-1877-11e8-93e9-820fc66a6309.png)

**Comment by lafriks** [comment]
Are there any javascript errors when you press `F12` and open `Console` tab?

**Comment by hhenkel** [comment]
@lafriks I'm not a IE user, but from what I see I would say there is no obvisious error in the console:
![grafik](https://user-images.githubusercontent.com/2813782/36603342-b97b1bf2-18ba-11e8-8f95-36fcfff15f3e.png)

**Comment by virtualdreams** [comment]
Short investigation ...

## Firefox:
![gitea_ff](https://user-images.githubusercontent.com/3603832/41083530-b02545d2-6a31-11e8-91b3-c694106d3615.png)

## Internet Explorer:
![gitea_ie](https://user-images.githubusercontent.com/3603832/41083537-b4016e06-6a31-11e8-8fe5-e8f6c1836efa.png)
