### ISSUE TITLE
Status API

### ISSUE THREAD

**Issue by bkcsoft** [go-gitea/gitea#357]
Just an issue to track that we need [Status API](https://developer.github.com/v3/repos/statuses/) for v1.1

**Comment by sbrl** [comment]
This issue has been closed - presumably because it's been implemented - but is there any way I can actually use it? I can't seem to find any documentation anywhere.

@bkcsoft

**Comment by zeripath** [comment]
This is documented in the Swagger api.

**Comment by sbrl** [comment]
Thanks for the reply, @zeripath! Unfortunately, I have absolutely no idea what "Swagger" is. Is there any documentation or some other resource on this at all that I could use to read up on it?

**Comment by jolheiser** [comment]
This might help. https://try.gitea.io/api/v1/swagger#/repository/repoListStatuses
This is the Swagger endpoint for the try instance. It is basically just the API endpoint.

**Comment by sbrl** [comment]
Oh, wow @jolheiser! I didn't even realise that the API documentation was built-in to my Gitea instance. I must have missed that in the Gitea documentation :P

Thanks so much!
