### ISSUE TITLE
GPG keys that do not expire default their expiry time to 0001-01-01

### ISSUE THREAD

**Issue by thehowl** [go-gitea/gitea#3573]
Example with my [GPG key](https://pgp.mit.edu/pks/lookup?op=vindex&search=0x40D328300D245DA5), which does not have an expiry time set.

![image](https://user-images.githubusercontent.com/4681308/36618267-c9f16588-18ea-11e8-95a4-2d3868626967.png)

**Comment by sapk** [comment]
That should come from that change https://github.com/go-gitea/gitea/commit/f2e20c81b66e6a937ecdb686f8d1011371433365#diff-b39af036c147da90df23fbbd6b50e41fL29 the check is not the same.

**Comment by lunny** [comment]
@sapk good catch. It's not zero. I will send a PR to fix that.

**Comment by sapk** [comment]
@lunny thanks for the PR, I haven't time to fix it and test it ^^
