### ISSUE TITLE
Use CONTRIBUTING.md as a deletable comment for making issues and pull requests

### ISSUE THREAD

**Issue by iddm** [go-gitea/gitea#3581]
This is a very nice feature of github: pasting `contributing.md` contents into a `content` field of a pull request or an issue. This would be cool if we supported it too.

**Comment by techknowlogick** [comment]
This is a dupe of #3491. Can this be closed?

**Comment by iddm** [comment]
According to the comments there - yes.

**Comment by techknowlogick** [comment]
@vityafx I just created a PR to add the documentation for the functionality at #3942

**Comment by iddm** [comment]
Thanks. I missed it.
