### ISSUE TITLE
Put latest commit title in the pull request to the title of the pull request

### ISSUE THREAD

**Issue by iddm** [go-gitea/gitea#3582]
For example, we have 5 commits and we are in the process of making a pull request. So, when the forms appears, it would be very nice to have the commit's title pasted into the pull request title. If we look at gitlab, we will see that it does so and it even puts commit content into a pull request description.

**Comment by thehowl** [comment]
GitHub takes the branch name, capitalizes it and changes dashes to spaces. We should decide what's best.

**Comment by iddm** [comment]
> GitHub takes the branch name, capitalizes it and changes dashes to spaces. We should decide what's best.

Do you mean, what is better between taking a branch name or latest commit title (eg gitlab vs github way)?

**Comment by eloyekunle** [comment]
Yes, I think that's what he means. Would be interesting to see what we choose.

**Comment by iddm** [comment]
What about implementing both and letting user or administrator or project owner to decide what he wants?

**Comment by eloyekunle** [comment]
Hmm. In Gitea settings then?

**Comment by iddm** [comment]
In gitea settings or project settings, yes.

**Comment by jonasfranz** [comment]
@vityafx I think that we should just decide which is the best way but I think we don't need an option for that.

**Comment by iddm** [comment]
Heh, I thought I proposed this in the first message but I didn't. Yes, that would also be good.

**Comment by eloyekunle** [comment]
Okay great. @vityafx Will you like to work on this? I'd love to myself.

**Comment by iddm** [comment]
> Okay great. @vityafx Will you like to work on this? I'd love to myself.

I don't know go lang and I don't want to spend time learning it as well, so it is better for everyone to let someone else who knows what to do to do this. 

So, @eloyekunle good luck :)

**Comment by eloyekunle** [comment]
Thanks @vityafx I'll jump right into it. @JonasFranzDEV, I might buzz you for clarifications as needed.
