### ISSUE TITLE
3MB upload size limit cannot be changed

### ISSUE THREAD

**Issue by jhenzely** [go-gitea/gitea#3586]
Hello.
I am trying to change the limit of maximum size of uploaded file into repository,
but after adjusting the value in config, I am still getting an error message:

"File size (6 MB) exceeds the maximum size of (3 MB)."

![upl_untitled](https://user-images.githubusercontent.com/12442261/36669190-546102cc-1af4-11e8-943a-71011e001527.jpg)

Config:
```
[attachment]
ENABLE = true
PATH = data/attachments
MAX_SIZE = 40
MAX_FILES = 5

```
===================================

- Gitea version (or commit ref):  1.3.2
- Git version: 2.16.2
- Operating system: CentOS 7
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL) applies globally
  - [ ] No
  - [ ] Not relevant

Thank You.

**Comment by lafriks** [comment]
Did you restart gitea after changing app.ini?

**Comment by jhenzely** [comment]
Hello lafriks.
Yes, sure.

**Comment by thehowl** [comment]
Can't reproduce. Are you sure you are modifying custom/conf/app.ini and not custom/conf/app.ini.sample?

**Comment by jhenzely** [comment]
Hello theowl. Thank You for reply.
Yes I was modifying the $GITEAHOME/custom/conf/app.ini
Now I have reinstalled the whole OS and I will try to reproduce it again in clear environment.

**Comment by jhenzely** [comment]
Hello.
I can confirm, that it is working now.

I reinstalled the whole OS 
CentOS 7, kernel: 3.10.0-693.17.1.el7.x86_64).

Thank You for quick reply.

**Comment by geimist** [comment]
I have installed gitea via docker on my Synology NAS (it works very fast :-) Thank you) But, I have the same problem with upload limit. 
Changes in the [attachment] section (app.ini) only work if I upload a file under "releases".

In the code section, it does not matter what I enter in the app.ini (and uploads are loaded to "/data/uploads" (not "/data/attachments"))

I restart and rebuil the Dockercontainer / and different versions. Now, I use gitea/gitea:latest

[attachment]
ENABLED         = true
PATH            = /data/attachments
ALLOWED_TYPES   = */*
MAX_SIZE        = 60
MAX_FILES       = 20 #
