### ISSUE TITLE
Show a link to your fork under the host repository

### ISSUE THREAD

**Issue by iddm** [go-gitea/gitea#3587]
When you have a repository of someone else and you forked it, show a link to your fork under the host repository title as shown:

[![example](https://i.imgur.com/5HbLItU.png)](https://i.imgur.com/5HbLItU.png)

Like that image above, but vice versa - show *your fork's* link in upstream page. This would be very useful because it will require only one click to get to your fork, now you have to go to the forks page and then only choose yourself.

**Comment by thehowl** [comment]
What's the use case for this? Especially since one source repository may have many different forks, whereas one fork may have only one source.

**Comment by Pofilo** [comment]
Well, for me, Github is really nice with this feature.
You look at the repo of someone, you know directly it is a fork and you have the link if needed.

For example on your profile @thehowl, we know directly that gitea is a fork.

**Comment by thehowl** [comment]
Yes, but OP is requesting the opposite if you pay attention. Linking the **fork** in the **upstream repo**.

**Comment by iddm** [comment]
@thehowl you can't have more than one your fork of source repository. But if you have organizations, you may fork into them. Then, I'd simply link the fork if it your forks count is 1. 

The story here is that as a user I want to perform less different actions to go to my fork from source repository page.

**Comment by thehowl** [comment]
Ah, touché, I guess this time I didn't pay enough attention! :sweat_smile: In that case, I guess I can see the point :) sorry about the confusion

**Comment by iddm** [comment]
@lunny yes, I know that. It could be quite simple: if you have one fork in your visibility area (your personal account and organizations you are in) - this fork is shown. Otherwise, nothing.

**Comment by iddm** [comment]
Also, It could be even better: modify the `fork` button so that if you have no forks in your visibility area - the popup window offers you making a fork in some place of your visibility area. Otherwise, if you have any forks, this popup also shows links to them. The same does github, for example. I have not checked whether the gitea has such behavior on the `fork` button yet or not. Is it so now?

**Comment by lunny** [comment]
@vityafx just need pull request.

**Comment by iddm** [comment]
@lunny I don't know `go` lang.. And I don't like it :) I'd do PRs of course if I could :)

**Comment by lunny** [comment]
@vityafx Maybe someone who likes `Golang` will do that. 😄

**Comment by 6543** [comment]
there now exist a fork list on upstream (link next to fork button)
and fork has link to upstream
