### ISSUE TITLE
Disallow merging until the CI bot reports about success build

### ISSUE THREAD

**Issue by iddm** [go-gitea/gitea#3588]
This is supported for the github and travis CI, for example. So, using a github and travis CI you may configure it so that it is impossible to merge the pull requests before the CI bot allows you.

**Comment by iddm** [comment]
Are there any estimations on this? Could we put a milestone on it? Do you guys have some discussions regarding issues, which goes where, for example? :)

**Comment by lunny** [comment]
This should be an option on branch protected I think.

**Comment by NicolasPetton** [comment]
Any update on this issue? I'd love to have something like this in gitea.

**Comment by lafriks** [comment]
@NicolasPetton noone is working on this currently

**Comment by japettyjohn** [comment]
Besides the integration with the pull request process itself, the merge requirement seems it could be met by adding to the required approvals a list of users/teams required in combination with the existing "number of required approvals" currently implemented.
