### ISSUE TITLE
Issues and PR user interface colors

### ISSUE THREAD

**Issue by bugreport0** [go-gitea/gitea#3590]
- Gitea version (or commit ref): 1.4.0rc1
- Can you reproduce the bug at https://try.gitea.io: Yes

## Description

Akin to #3589 : the colors of the Issues and Pull Requests filter toggle box are counter-intuitive:
* listing 'Open' items is colored **green**;
* listing 'Closed' items is colored **red**.

Common sense says that 'Open' issues are 'bad' and 'Closed' issues are 'good', but both categories are really neutral. How about changing 'Open' to blue (indicating that action is required) and making 'Closed' dark grey or so?

## Screenshots

![issues-pr-open](https://user-images.githubusercontent.com/32939607/36692030-dd8f003c-1b2e-11e8-9b56-9170100937bd.png)

![issues-pr-closed](https://user-images.githubusercontent.com/32939607/36692034-df9e2902-1b2e-11e8-9de9-189f96e0eb06.png)

**Comment by thehowl** [comment]
I'd rather stick with what GitHub and GitLab do to be honest. While I agree they should probably be more neutral, changing the colours could actually be rather confusing for users transitioning from what they already use. (I tried to find out what colours BitBucket issues used, but, bitbucket being the enterprise depressing product it is, the only hint of colour I could find in regard to issues where a slight pale green border around "CLOSED" and a pale grey around "OPEN". go figure)

**Comment by bugreport0** [comment]
A similar coloring issue exists on the 'Activity' page of a repository. Again, closed issues are colored red and new issues are colored green.

![repository-activity](https://user-images.githubusercontent.com/32939607/36812465-29bd86e0-1cc9-11e8-836c-fb310f717235.png)

**Comment by mrsdizzie** [comment]
Closing as this seems to be more of an opinion with no other reports/support for changing

**Comment by 6543** [comment]
-> custom themes and templates can always be used to change the look ;)
