### ISSUE TITLE
Localhost can visit gitea but visiting via nginx then some files will be 404 not found

### ISSUE THREAD

**Issue by everleek** [go-gitea/gitea#3595]
- Gitea version (or commit ref): 1.3.3
- Git version: default
- Operating system: centos 6.5 x64
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description

...

Localhost can visit gitea but visiting via nginx then some files will be 404 not found

See some screenshots

my nginx config

```
server {
    listen                     80;
    listen                     443 ssl;
    server_name                git.xxx.com;
    ssl_certificate            xxx;
    ssl_certificate_key        xxx;
    ssl_ciphers                xxx
    ssl_prefer_server_ciphers  on;
    ssl_protocols              TLSv1 TLSv1.1 TLSv1.2;
    ssl_session_cache          shared:SSL:5m;
    ssl_session_timeout        5m;

    if ($scheme = http) {
        return  301 https://$host$request_uri;
    }

    location / {
        proxy_pass        http://127.0.0.1:3000/;
        proxy_buffering   off;
        proxy_set_header  Host $http_host;
        proxy_set_header  X-Real-IP $remote_addr;
        proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header  X-Forwarded-Proto $scheme;
    
        location ~* \.(js|css|jpg|gif|png|bmp|swf)$ {
            expires  30d;
        }
    }
}
```

my gitea config

```
[server]
PROTOCOL                   = http
DOMAIN                     = git.xxx.com
ROOT_URL                   = https://git.xxx.com/
HTTP_ADDR                  = 127.0.0.1
HTTP_PORT                  = 3000
UNIX_SOCKET_PERMISSION     = 666
DISABLE_SSH                = false
START_SSH_SERVER           = false
BUILTIN_SSH_SERVER_USER    = 
SSH_DOMAIN                 = git.xxx.com
SSH_LISTEN_HOST            = 
SSH_PORT                   = 22
SSH_LISTEN_PORT            = %(SSH_PORT)s
```

## Screenshots

Web visit

![image](https://user-images.githubusercontent.com/174493/36782281-6fb8a12c-1cb3-11e8-8da2-d6b7d35a1d6f.png)

Localhost visit

![image](https://user-images.githubusercontent.com/174493/36782347-a6df3fda-1cb3-11e8-932f-fad072fcf60d.png)

**Comment by lunny** [comment]
It seems it's your ngnix problem?

**Comment by everleek** [comment]
I do not know, before has always been good, I upgraded 1.3.2 Suddenly, 1.3.2 localhost also can not access to gitea, upgrade to 1.3.3 then local can, but the remote can not. :(
