### ISSUE TITLE
Can't merge PR on an organization's repo

### ISSUE THREAD

**Issue by feakuru** [go-gitea/gitea#3596]
- Gitea version (or commit ref): 
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:
2017/11/15 20:09:56 [...io/gitea/cmd/serv.go:172 runServ()] [F] Repository does not exist: username/reponame
## Description

When I try to merge a PR in a repository of an organization, I see a plain 500. Logs (see above) contain an error indicating that such a repository does not exist **in my user**, which is true.
Just now, after a few retries, I was able to merge the PR, but I didn't change anything.

**Comment by appleboy** [comment]
What is your gitea version?

**Comment by feakuru** [comment]
@appleboy sorry, forgot to mention it.
> Gitea version f64c232 built with: bindata, sqlite
> git version 2.11.0
> Linux hostname 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19) x86_64 GNU/Linux

**Comment by thehowl** [comment]
what was your git remote, locally?

**Comment by lunny** [comment]
I will close this issue. Please feel free to reopen it.
