### ISSUE TITLE
CFM incompatibility

### ISSUE THREAD

**Issue by rlex** [go-gitea/gitea#3597]
- Gitea version (or commit ref): 1.4.0-rc1
- Git version:
- Operating system: Ubuntu 16.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
Technically not a bug, but a design issue?
I'm trying to deploy gitea using ansible. While i can download, install and run it, even when i have configs pointing to existing DB with created user, when i overwrite config (ie with another ansible run) i'm still welcomed with install page after restart. I need to fill admin user & press install to get to my gitea instance.
I initially thought that https://github.com/go-gitea/gitea/issues/3246 was related, however even after putting INTERNAL_TOKEN in config file i still get that issue.

Here is the diff between my auto-generated config and config gitea generated after i pressed "install": https://gist.github.com/rlex/71e5365db2ec335851c75b6d09b2f714 (test install anyway, so no worries over some data that might leak)

As you can see, most of changes are just whitespaces.

**Comment by lafriks** [comment]
Use https://docs.gitea.io/en-us/command-line/ gitea cli command generate secrets&tokens. Also you need to set install lock to true

**Comment by cody-vibe** [comment]
This is only available on master. Is it OK if I back-port the generate feature to 1.4 branch?

**Comment by thehowl** [comment]
To answer the question directly: `INSTALL_LOCK` **MUST** be set to true in order for the install page not to show up.

**Comment by lafriks** [comment]
@sdwolfz we usually do not backport new features in such late stage before the release
