### ISSUE TITLE
Create PR directly from web-ui file editing

### ISSUE THREAD

**Issue by chinglinwen** [go-gitea/gitea#3598]
- Gitea version (or commit ref): v1.3.2
- Git version:  git version 1.8.3.1
- Operating system: Centos 7
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

Create pull request directly from web-ui file editing.

**Comment by mrsdizzie** [comment]
You can do this now : )
