### ISSUE TITLE
render geojson

### ISSUE THREAD

**Issue by lucacorsato** [go-gitea/gitea#3599]
- Gitea version (or commit ref):
- Git version: 1.4 rc1
- Operating system: Ubuntu 16.04
- Database (use `[x]`):
  - [ x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ x] Not relevant
- Log gist:

## Description
  ##Hi,
<img width="1000" alt="schermata 2018-03-01 alle 10 02 26" src="https://user-images.githubusercontent.com/1077445/36835828-bd7105ce-1d37-11e8-931e-1e3e928d0d04.png">

would it be useful to implement a rendering function for the geographic file .geojson, as in Gist with the rendered blob?

thanks

luca
...

**Comment by thehowl** [comment]
You can always use a custom renderer: https://docs.gitea.io/en-us/config-cheat-sheet/#markup-markup

**Comment by lafriks** [comment]
leaflet js lib could be used for this easily

**Comment by noerw** [comment]
Willing to implement this!
Adding more JS dependencies (thinking of leaflet) to gitea is fine?

**Comment by lunny** [comment]
@noerw I think we should give an option to let people enable/disable it.

**Comment by sonicnkt** [comment]
Any progress on this implementation?

**Comment by noerw** [comment]
@sonicnkt Sorry, no I didn't get to this. I'm still interested though..

**Comment by aschrijver** [comment]
FYI It is also suggested on Codeberg (with reference to this): https://codeberg.org/Codeberg/Community/issues/342

**Comment by gary-kim** [comment]
@noerw Would you mind if I try this?

**Comment by noerw** [comment]
@gary-kim sure, go ahead :+1:

**Comment by n0toose** [comment]
Hi, could you please clarify where this issue was fixed?

**Comment by delvh** [comment]
https://github.com/go-gitea/gitea/issues/3599#issuecomment-370135962
