### ISSUE TITLE
NoCommitterAccount: user does not exist

### ISSUE THREAD

**Issue by Pofilo** [go-gitea/gitea#3602]
- Gitea version (or commit ref): 1.3.3
- Git version: 2.7.4
- Operating system: Ubuntu 16.04.4 LTS
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No (no access to logs)
  - [ ] Not relevant
- Log gist:

## Description

I'm running my own instance of Gitea and I have some mirrors (linked to github mostly).
I have a lot of logs like this one which are errors:

```
[...ea/models/gpg_key.go:385 ParseCommitWithSignature()] [E] NoCommitterAccount: user does not exist [uid: 0, name: noreply@github.com, keyid: 0]
```

I don't know if this is relevant to the screenshot, plus I don't find any dock explaining what it means.

Does someone know what it means ? I have so many logs due to this thing I don't understand.

## Screenshots

![image](https://user-images.githubusercontent.com/7527594/36862544-687f8324-1d87-11e8-8d8c-0e3738945e98.png)

**Comment by lafriks** [comment]
Yes this is not real error and should be lowered to information level in log
