### ISSUE TITLE
Change admin password in Gitea

### ISSUE THREAD

**Issue by plaidshirtakos** [go-gitea/gitea#3603]
- Gitea version (or commit ref): 1.3.3
- Git version: 2.14.1
- Operating system: Ubuntu 17.10 x64
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ X] Not relevant
- Log gist:

## Description

I created an admin user with a password, that contains a special character. Installation of Gitea was successful, but I can't login. I can't get new password, because it says:

`Sorry, Register Mail Confirmation has been disabled.`

I tried command gitea admin change-password, but command is not recognized.

**Comment by Pofilo** [comment]
What is the special character you are talking about ?
Knowing it can help.

**Comment by plaidshirtakos** [comment]
It was a "@".

**Comment by lunny** [comment]
You can change any user's password via `gitea admin` command.

**Comment by plaidshirtakos** [comment]
I get 

> gitea: command not found

for every `gitea `commands. Gitea is up and running on server.

**Comment by lafriks** [comment]
@plaidshirtakos probably gitea binary is not in path, so you need to use full path to it

**Comment by plaidshirtakos** [comment]
Thanks, command executed successfully.

**Comment by techknowlogick** [comment]
Closing this ticket.
