### ISSUE TITLE
Modal dialogs and consistency

### ISSUE THREAD

**Issue by bugreport0** [go-gitea/gitea#3605]
- Gitea version (or commit ref): 1.4.0rc1
- Can you reproduce the bug at https://try.gitea.io: Yes

## Description

There are multiple kinds of modal dialogs in Gitea with completely different semantics. They share strings in the translation file, blocking any attempt to have a decent user experience.

One kind is the 'delete' dialogs with a trashcan that offer 'No' and 'Yes' choices, see #3589. These can't be dismissed (cancelled) by clicking in an empty region.

Another kind is the 'Label Modification' [sic] dialog which acts completely different for some reason. This 'No' choice uses the 'No' string of the 'delete' dialogs, so I can't turn this into 'Cancel'. Good news is this one can be dismissed by clicking outside of it. But out of the blue this one sports a 'Modify √' button with a check-mark for fun.

I keep running into all kinds of user interface inconsistencies; I can't document all of them in the spare time that I have. Is there anyone even paying attention to Gitea as a whole? It feels like it's just different parts cobbled together. Sorry for the frustration.

Just dumping some other issues (I've got tons more) for future reference:
* there is no way to tell you're filtering a repository issue list other than clicking all drop-down boxes
* the 'new release' button on the releases page has a smaller size/font than other pages
* button order in 'create release' and 'edit release' is different
* clicking a milestone name opens its list of issues, clicking an issue name does nothing
* on the installation page, checkboxes have flying tooltips, these are nowhere to be found elsewhere
* the sub header text on the 'create milestone' and 'edit milestone' is different
* same for the sub header on 'create release' and 'edit release' (I'm fixing both in my translation)
* open milestones are colored green, closed milestones are colored red (see #3590 too)
* the 'Initial commit' string can't be changed from the translation file
* the 'ZIP' and 'TAR.GZ' strings (releases page) can't be changed from the translation file

## Screenshots

![delete-yes](https://user-images.githubusercontent.com/32939607/36870057-b7e86fd0-1d95-11e8-9270-681495bbb804.png)

![edit-label](https://user-images.githubusercontent.com/32939607/36870064-bd2f62d2-1d95-11e8-9ccb-50150d5c0074.png)

**Comment by bugreport0** [comment]
The 'Add Time' dialog decides to spice things up by randomly changing button order.

![add-time](https://user-images.githubusercontent.com/32939607/36919656-f1184b34-1e55-11e8-9b43-0c9d9d26dd3c.png)

**Comment by thehowl** [comment]
>Is there anyone even paying attention to Gitea as a whole? It feels like it's just different parts cobbled together. Sorry for the frustration.

Yeah, you're not wrong. Both from a UX and a code point of view there should probably be more attention to the project as a whole, but in an open source project such as this one, where a lot of people come and go (myself included), it can be quite hard to have 'core developers' who keep track of everything and create cohesion in the project.

**Comment by bugreport0** [comment]
@thehowl Thanks for the reply.

The entire thing is frustrating because Gitea is pretty amazing. It's an awesome standalone (self-hosted) development tool. But the UI and translation issues make it a diamond in the rough. Appreciated by those seeing its potential.

With a bit of polish and marketing, I'm pretty sure it could be one of the most popular open source development tools. It's easy. It's functional. It's great. Except for the paint job.

**Comment by thehowl** [comment]
About that: I've actually worked on a blogpost for the next version (1.4) which is more appealing than the previous posts. I'm sure another pair of eyes to check on it wouldn't hurt, if you have the time :) https://github.com/go-gitea/blog/pull/54

**Comment by bugreport0** [comment]
@thehowl Took a look, sent a PR. Great work. I found the original style a bit over-excited, so I tried to reword it using the voice of my recent translation work.

**Edit**: I don't know how any of this works, but I think this is my PR to you: https://github.com/thehowl/blog-1/pull/1

**Comment by bugreport0** [comment]
The repository settings 'Danger Zone' is again different, but looks very good for invasive operations (old wording shown here).

![transfer-ownership](https://user-images.githubusercontent.com/32939607/36995399-d8ce111e-20ab-11e8-945b-5ea41c352567.png)

**Comment by wxiaoguang** [comment]
It has been improved by #24289 , no "black" dialog any more.
