### ISSUE TITLE
Custom tmpl files not loading

### ISSUE THREAD

**Issue by pgodwin** [go-gitea/gitea#3608]
- Gitea version (or commit ref): 1.3.3 
- Git version: 2.14.1
- Operating system: Windows Server 2012 R2 (6.3 Build 9600)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:
https://gist.github.com/pgodwin/00c90c8af325dd9fb13fd5a4cb5e5df2

## Description
I'm attempting to use custom extra_links.tmpl file with gitea but it doesn't seem to load.

I've put the file in `custom/templates/custom/extra_links.tmpl`. It's content is included below:

    <a href="#">TEST URL</a>

If I copy over the base templates from source to `/custom/templates/` the footer custom template then loads. 

Do I need to copy over all the templates from source to `custom/templates/` in order for custom templates to work? Or is this something not supported in 1.3 (head.tmpl doesn't seem to have anything for it in the 1.3 branch).

**Comment by lafriks** [comment]
I think extra_links template was added only 1.4

**Comment by thehowl** [comment]
yep: https://github.com/go-gitea/gitea/commit/45c264f681e3f7e1a22a191029836a690959aac3
