### ISSUE TITLE
receiving HTTP/500 if filename not simple-alphabetic

### ISSUE THREAD

**Issue by dextarr** [go-gitea/gitea#3609]
- Gitea version (or commit ref): 1.3.3
- Git version: 2.7.4
- Operating system: Ubuntu 16.04.4 LTS
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

2018/03/02 08:29:52 [...routers/repo/view.go:54 renderDirectory()] [E] GetCommitsInfo: GetCommitByPath (/rbroken): Length must be 40:

## Description

we generate the filenames in a repo using a script. the script broke and some of the files have '\r' as its first character.
push to gitea still works, but trying to select the repository on the web interface returns http/500.

reproducable:
```
x:~$ mkdir git-broken
x:~$ cd git-broken   
x:~/git-broken$ date >$(echo -e "\015broken")
x:~/git-broken$ git init
Initialized empty Git repository in /home/x/git-broken/.git/
x:~/git-broken$ git add .
x:~/git-broken$ GIT_AUTHOR_EMAIL=git-broken@ GIT_AUTHOR_NAME=git-broken git commit -m "first commit"
[master (root-commit) 2453160] first commit
 Author: git-broken <git-broken@>
 1 file changed, 1 insertion(+)
 create mode 100644 "\rbroken"
x:~/git-broken$ git log -p
commit 24531607b88e3f2fa00aedaaa26fadbd457d06c7
Author: git-broken <git-broken@>
Date:   Fri Mar 2 08:47:05 2018 +0100

    first commit

diff --git "a/\rbroken" "b/\rbroken"
new file mode 100644
index 0000000..2428687
--- /dev/null
+++ "b/\rbroken"
@@ -0,0 +1 @@
+Fri Mar  2 08:46:26 CET 2018
x:~/git-broken$ git remote add origin https://try.gitea.io/git-broken/git-broken.git
x:~/git-broken$ git push -u origin master
Username for 'https://try.gitea.io': git-broken
Password for 'https://git-broken@try.gitea.io': 
Counting objects: 3, done.
Writing objects: 100% (3/3), 244 bytes | 0 bytes/s, done.
Total 3 (delta 0), reused 0 (delta 0)
To https://try.gitea.io/git-broken/git-broken.git
 * [new branch]      master -> master
Branch master set up to track remote branch master from origin.
x:~/git-broken$ ls -libaF
total 18
144232 drwxrwxr-x  3 x x  4 Mar  2 08:46 ./
     7 drwxr-xr-x 63 x x 99 Mar  2 08:45 ../
144239 -rw-rw-r--  1 x x 29 Mar  2 08:46 \rbroken
144243 drwxrwxr-x  8 x x 13 Mar  2 08:47 .git/
x:~/git-broken$
```

## Screenshots

![image](https://user-images.githubusercontent.com/26901367/36888991-393e95f2-1df8-11e8-8e6c-7655c3452e77.png)

**Comment by dextarr** [comment]
maybe a duplicate of https://github.com/go-gitea/gitea/issues/2537

**Comment by lunny** [comment]
duplicated with #2537
