### ISSUE TITLE
It would be very nice to have autocompletions for `#` and `@` characters.

### ISSUE THREAD

**Issue by iddm** [go-gitea/gitea#3611]
When I am writing a description or commenting an issue or a pull request, I would like to see what I am gonna mention when I write the `#` character. I expect this to be an autocomplete list, just as in github. The same for `@` for mentioning organizations or people.

**Comment by sapk** [comment]
This is done at least for mention (maybe we need to add it to more text field ?). Since #3136

**Comment by iddm** [comment]
@sapk unfortunately this does not work for me on 1.4 version.

**Comment by thehowl** [comment]
can you elaborate? and are you actually on the 1.4 rc?

**Comment by iddm** [comment]
@thehowl yes, i am on it, installed a week or two ago. I have one user excepr me and organization. I can mention nothing but only myself.

**Comment by thehowl** [comment]
You mean the mention completion only shows your name? That's to be expected. It only lists the user who can be set as assignees, and as such have write access to the repository.

**Comment by iddm** [comment]
@thehowl that’s strange because people who makes prs don’t have any write access to the repository.

**Comment by iddm** [comment]
> @thehowl that’s strange because people who makes prs don’t have any write access to the repository.

So, are we going to do anything with this behavior?

**Comment by 6543** [comment]
`@ `works followup issue is at #16872
