### ISSUE TITLE
Cannot add attachments when editing an issue

### ISSUE THREAD

**Issue by mqudsi** [go-gitea/gitea#3618]
- Gitea version (or commit ref): 990709da8fa64d51d8005146da1728f960444abd
- Git version: N/A
- Operating system: N/A
- Database (use `[x]`): N/A
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist: N/A

## Description

When editing an issue, gitea does not offer an option to add a new attachment. The first post in an issue should always be fully editable so that relevant information may be added to it (if the team's workflow is so designed) so relevant information can always be accessible without searching through the entire thread.

## Screenshots

Here is a screenshot of the web ui as it appears when attempting to edit an issue:

![image](https://user-images.githubusercontent.com/606923/36928723-f126fb8c-1e4d-11e8-82df-e47ff2f267f1.png)

As can be seen, the prompt to drag-and-drop a file to upload is not present. There is no other limitation I can see on changes that can be made retroactively, so this should be supported.

**Comment by thehowl** [comment]
This is available on gitea, but it looks like it was removed by the instance administrator (section `[attachment]`, variable `ENABLE`, which must be set to true)

**Comment by thehowl** [comment]
Woops, should have paid more attention! Thanks for the explanation.

**Comment by NateScarlet** [comment]
Image pasting also don't work when editing.
Only way to use new image is paste it to comment field then ctrl+x the link

**Comment by blueworrybear** [comment]
Hi, I am working on this issue recently.

I would like to reuse **dropzone**'s UI to allow user editing attachment.

Here is the preview of current progress:

![edit-attachment0](https://user-images.githubusercontent.com/1456219/66313101-5b47f080-e944-11e9-8cff-1af43fb6e3d3.png)

When user click **edit** button on issue with attachments:

![edit-attachment1](https://user-images.githubusercontent.com/1456219/66313150-7581ce80-e944-11e9-885a-9b72988119e1.png)

I would like to know if it's a good idea. The update is almost done, just remaining `UpdateCommentContent` need to be updated.
