### ISSUE TITLE
Translatable Emails

### ISSUE THREAD

**Issue by kolaente** [go-gitea/gitea#3622]
It would be nice if Gitea could have translatable emails.

What do you think would be the best approach to this? Simply putting all emails as strings in the translation files?

**Comment by lunny** [comment]
Put the english email as a new file on crowdin and write some scripts or drone plugin to keep sync.

**Comment by kolaente** [comment]
You mean a sepereate file for every email?

**Comment by lunny** [comment]
No. A single file for every language.

**Comment by kolaente** [comment]
Do you think we'll need a new file or would it be ok to put this in the existing locale file(s)? (under a new section ofc)

**Comment by lafriks** [comment]
Could we instead use https://github.com/matcornic/hermes for email templates?

**Comment by kolaente** [comment]
@lafriks looks great, I like it! But we still need a way to store the translated strings somewhere.

**Comment by lafriks** [comment]
If you use this lib we could use same locale file as now for ui

**Comment by kolaente** [comment]
I've created another issue for HTML emails as thats probably something we should integrate seperately and put in the translations after the fact: #3892

**Comment by 6543** [comment]
closed by #16200
