### ISSUE TITLE
On Update to 1.4.0-rc2: Error on ALTER TABLE DROP COLUMN is_owner

### ISSUE THREAD

**Issue by w3p706** [go-gitea/gitea#3624]
- Gitea version (or commit ref): v1.3.2/3 => v1.4.0-rc2
- Git version: git version 2.7.4
- Operating system: Linux vserv24 4.4.0-112-generic #135-Ubuntu SMP Fri Jan 19 11:48:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
Hi

I update with the following procedure:
```
sudo systemctl stop gitea
sudo su git
cd /home/git/gitea
mv gitea gitea.old
wget https://github.com/go-gitea/gitea/releases/download/v1.4.0-rc2/gitea-1.4.0-rc2-linux-amd64
mv gitea-1.4.0-rc2-linux-amd64 gitea
chmod +x gitea
./gitea web
```

The following logs are genereated, gitea does not start up.

./log/gitea.log:
```
2018/03/05 08:11:49 [I] Migration: remove is_owner, num_teams columns from org_user
2018/03/05 08:11:49 [...itea/routers/init.go:60 GlobalInit()] [E] Failed to initialize ORM engine: migrate: do migrate: DROP COLUMN org_user.is_owner, org_user.num_teams: mssql: Fehler bei ALTER TABLE DROP COLUMN is_owner, da mindestens ein Objekt auf diese Spalte zugreift.
```
Translation of the error (4922):  ALTER TABLE ALTER COLUMN is_owner failed because one or more objects access this column.

./log/xorm.log: `2018/03/05 08:03:58 [I] [SQL] ALTER TABLE org_user DROP COLUMN is_owner, num_teams`

I see there is a default value on this column. If I generate a DROP COLUMN script in sql-server it gernerates:

```
ALTER TABLE dbo.org_user
	DROP CONSTRAINT DF__org_user__is_own__797309D9
GO
ALTER TABLE dbo.org_user
	DROP COLUMN is_owner
GO
```

**Comment by lafriks** [comment]
Code that needs to be run to drop column with constraint.
Select constraint name:
```
SELECT Name FROM SYS.DEFAULT_CONSTRAINTS WHERE PARENT_OBJECT_ID = OBJECT_ID('__TableName__') AND PARENT_COLUMN_ID = (SELECT column_id FROM sys.columns WHERE NAME = N'__ColumnName__' AND object_id = OBJECT_ID(N'__TableName__'))
```
Drop constraint:
```
ALTER TABLE __TableName__ DROP CONSTRAINT __ConstraintName__
```
And only then code to drop column
```
ALTER TABLE __TableName__ DROP COLUMN __ColumnName__
```
