### ISSUE TITLE
suggestion about graph

### ISSUE THREAD

**Issue by msongz** [go-gitea/gitea#3625]
currently graph entry is in the file history.
but it seems not much relative for the exact file.
how about moving the graph to the repo main page ?

**Comment by Ryuno-Ki** [comment]
Does someone remember, what graph is meant here?

**Comment by wxiaoguang** [comment]
This one?

![image](https://user-images.githubusercontent.com/2114189/172091229-352d998f-3443-49d4-aeca-d80212c94abc.png)

**Comment by Ryuno-Ki** [comment]
That would mean moving this code

https://github.com/go-gitea/gitea/blob/a9cc9c0f7afacb2e51cfd1885d392f56dca0c7f5/templates/repo/commits.tmpl#L9-L14

into

https://github.com/go-gitea/gitea/blob/a9cc9c0f7afacb2e51cfd1885d392f56dca0c7f5/templates/repo/sub_menu.tmpl#L2-L21

if I got that correctly?

**Comment by lunny** [comment]
I think keeping the graph under `Commits` is still good enough. We should keep less parent menus of repository to make it looks clear.

**Comment by Ryuno-Ki** [comment]
So closing this as won't fix?
I mean, we could reopen it if we change the mind.

**Comment by wxiaoguang** [comment]
Let's close this one. There could be new issues if new thoughts come.
