### ISSUE TITLE
pq: Cache lookup fail

### ISSUE THREAD

**Issue by oliviergareau** [go-gitea/gitea#3628]
- Gitea version (or commit ref): 1.3.3
- Git version: 2.11.0
- Operating system: Armbian
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:
2018/03/05 19:04:33 [I] Log Mode: File(Info)
2018/03/05 19:04:33 [I] XORM Log Mode: File(Info)
2018/03/05 19:04:33 [I] Cache Service Enabled
2018/03/05 19:04:33 [I] Session Service Enabled
2018/03/05 19:04:33 [I] Mail Service Enabled
2018/03/05 19:04:33 [I] Register Mail Service Enabled
2018/03/05 19:04:33 [...itea/routers/init.go:60 GlobalInit()] [E] Failed to initialize ORM engine: migrate: sync: pq: cache lookup failed for function 669

## Description

After a server reboot on version 1.3.3, gitea fails to start with the following error:
`[...itea/routers/init.go:60 GlobalInit()] [E] Failed to initialize ORM engine: migrate: sync: pq: cache lookup failed for function 669` . Google search did not return much about this error and gogs or gitea.

**Comment by lunny** [comment]
@WhiteRayne2 that means you ever manually deleted a function on your table `pg_proc`. It should be not related with Gitea.
