### ISSUE TITLE
Enable Multiarchitecture build for Docker Container

### ISSUE THREAD

**Issue by whatever4711** [go-gitea/gitea#3633]
Hi together,

let me suggest a new structure for your build:
It would be great if Docker builds are separated from the source repository. 

For Docker I already setup a multiarchitecture repository [whatever4711/docker-gitea](https://github.com/whatever4711/docker-gitea), which builds Containers for `amd64`, `i386`, `arm64`, and `arm32` with the same basic Dockerfile on CircleCI. Additionally, it tags those images accordingly, such that the call `docker run -it -p 2222:22 -p 3000:3000 whatever4711/gitea` downloads the version for your system and there is no need for several Dockerhub repositories anymore.

Referencing issue #2607 and PR #2927

Best regards

**Comment by sapk** [comment]
In previous PR related to docker (at least #1985), I try to setup to allow that and making a sub makefile under docker folder. That way we could keep it inside gitea repo. The direction that was taken was to keep gitea directly related stuff, like documentation, inside the same repo.
As for multi-arch, now that docker cli will support it natively we should wait for it to become stable. I previously make using the earliest `github.com/estesp/manifest-tool` (#1615) but split into multiple step to ease the process of reviewing as not all maintainers use docker. We could definitly improve my first try with your code for multi-arch image.

**Comment by sapk** [comment]
I think we can close this as we provide multi-arch image now. We only build them for linux/amd64 and arm64 but the base it there and there other issue to track missing platform like arm32 for rpi.
Feel free to re-open if needed.
