### ISSUE TITLE
Allow closing an issue with giving a reason

### ISSUE THREAD

**Issue by kolaente** [go-gitea/gitea#3637]
It would be nice if one could close an issue with giving a reason for that.
So, if I close an issue, there'd be a dropdown next to the `close` button specifying reasons like `done`, `wontfix` or `duplicate` etc. One should be able to specify these via admin/settings.

**Comment by thehowl** [comment]
Label + close or comment + close sound like valid substitutes for this.

**Comment by fnetX** [comment]
Is the current behaviour enough or do you still want to improve?
It's sometimes hard to track if a certain feature (like comment & close) was just unavailable back in 2018 or if it wasn't sufficient.

**Comment by lunny** [comment]
I would like to close this one, since we could use comment + close and with labels. @kolaente
