### ISSUE TITLE
Gitea Code-Search-Field is missing

### ISSUE THREAD

**Issue by Adrian-Voelker** [go-gitea/gitea#3641]
- Gitea version (or commit ref):
- Git version:  2.14.1
- Operating system: Ubuntu 17.10
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x ] Not relevant
- Log gist:

## Description

Hello Community,
first of all: Thank you for Gitea! I love it and i'm using it permanently :)

When inspecting a repository, the Code-Search-Field is missing and you cant search for code, files or phrases. 

In other issues and screenshots i've seen that it should be visible, but in Gitea-Version  1.4.0+rc1-17-g93f34fd its not there.( Also in other languages)
Hopefully i'm helping with opening this issue to make Gitea even greater.

### Missing Search field
![search_field_is_missing](https://user-images.githubusercontent.com/37142161/37099257-28bf646e-2220-11e8-971e-12bd780a38d6.png)

### Gitea-Version
![gitea-version](https://user-images.githubusercontent.com/37142161/37099255-289eba2a-2220-11e8-8b92-126f91431cd7.png)

**Comment by lafriks** [comment]
Search field is visible only if code search is enabled in `app.ini`. See `REPO_INDEXER_ENABLED` in https://docs.gitea.io/en-us/config-cheat-sheet/

Be warned that currently code search uses a lot of disk space for index file
