### ISSUE TITLE
OpenID Connect, 500 error on sign in

### ISSUE THREAD

**Issue by johanhugg** [go-gitea/gitea#3644]
- Gitea version (or commit ref): 1.1.0+1091-g1a835811
- Git version: not relevant
- Operating system: Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
After the recent merge to fix the Dropbox provider, it also broke the OpenID Connect provider. When clicking the sign in with OpenID Connect on the sign in page, a 500 error page is shown. #3437 
This merge did not only update the endpoint urls, and this is why it broke I think.

I tried downgrading the Gothic version in the latest Gitea, and it works.

**Comment by johanhugg** [comment]
> remove /data/gitea/sessions/oauth2/session_: no such file or directory

This is the error I receive from Gothic

**Comment by techknowlogick** [comment]
The same happens to me when I try to sign in with GitHub. (The 500 error being displayed to me, as well as the same log entry).

**Comment by lafriks** [comment]
Seems to be related to markbates/goth#192

**Comment by lafriks** [comment]
Fixed in #3661
