### ISSUE TITLE
Latest gitea container causes PostgreSQL database error, no longer launches

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#3646]
- Gitea version (or commit ref): don't know, gitea doesn't output this in the log when launching in docker (or only does so after the error occurs)
- Git version: docker image `gitea/gitea:latest`
- Operating system: docker / ubuntu 17.10 host
- Database (use `[x]`):
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X] No
  - [ ] Not relevant
- Log gist:

## Description

After I updated the docker container to the latest version (keeping all config data), it no longer launches. It seems to be stuck in a restart loop without ever successfully running, showing this in the log:

```
...
gitea_1  | 2018/03/08 18:38:00 [T] Custom path: /data/gitea
gitea_1  | 2018/03/08 18:38:00 [T] Log path: /data/gitea/log
gitea_1  | 2018/03/08 18:38:01 [T] AppPath: /app/gitea/gitea
gitea_1  | 2018/03/08 18:38:01 [T] AppWorkPath: /app/gitea
gitea_1  | 2018/03/08 18:38:01 [T] Custom path: /data/gitea
gitea_1  | 2018/03/08 18:38:01 [T] Log path: /data/gitea/log
gitea_1  | 2018/03/08 18:38:02 [T] AppPath: /app/gitea/gitea
gitea_1  | 2018/03/08 18:38:02 [T] AppWorkPath: /app/gitea
gitea_1  | 2018/03/08 18:38:02 [T] Custom path: /data/gitea
gitea_1  | 2018/03/08 18:38:02 [T] Log path: /data/gitea/log
gitea_1  | 2018/03/08 18:38:03 [T] AppPath: /app/gitea/gitea
gitea_1  | 2018/03/08 18:38:03 [T] AppWorkPath: /app/gitea
gitea_1  | 2018/03/08 18:38:03 [T] Custom path: /data/gitea
gitea_1  | 2018/03/08 18:38:03 [T] Log path: /data/gitea/log
...
```

The database log shows this:

```
db_1     | LOG:  database system was shut down at 2018-03-08 06:22:36 UTC
db_1     | LOG:  MultiXact member wraparound protections are now enabled
db_1     | LOG:  database system is ready to accept connections
db_1     | LOG:  autovacuum launcher started
db_1     | ERROR:  syntax error at or near "num_teams" at character 34
db_1     | STATEMENT:  ALTER TABLE "org_user" [is_owner num_teams]
db_1     | ERROR:  syntax error at or near "num_teams" at character 34
db_1     | STATEMENT:  ALTER TABLE "org_user" [is_owner num_teams]
db_1     | ERROR:  syntax error at or near "num_teams" at character 34
db_1     | STATEMENT:  ALTER TABLE "org_user" [is_owner num_teams]
db_1     | ERROR:  syntax error at or near "num_teams" at character 34
...
```

**Comment by lafriks** [comment]
Damn, looks like I broke it :(

**Comment by ghost** [comment]
Well unless it's my fault somehow? I wouldn't know that it is, but who knows. I haven't looked at that gitea in a while, but a month ago it still worked.

Can I provide you with anything to help figure out what is going on? I can't dump the entire database here (has some confidential projects) but I could figure out a way to give you access personally if that was of any help.

**Comment by lafriks** [comment]
@JonasT I have submitted PR to fix this. Somehow I had broken my written code after I did test it. Sorry for that

**Comment by ghost** [comment]
@lafriks so when will the docker container be updated? I just checked `gitea/gitea:latest` and launching it still results in the same error...

**Comment by lafriks** [comment]
@JonasT this fix should be already be in latest

**Comment by ghost** [comment]
Ah sorry, I forgot to cleanly recreate the container. Works now :smile:

**Comment by jsan4christ** [comment]
Thanks Lunny,

Centos 7 will not be happy with anything beyond 1.8.

But turns out my real problem was the firewall. It is back up now.
