### ISSUE TITLE
Gitea 1.4 fails to start on Raspberry Pi

### ISSUE THREAD

**Issue by duchenpaul** [go-gitea/gitea#3650]
- Gitea version (or commit ref): 1.4
- Git version: git version 2.11.0
- Operating system:  Raspbian stretch 
```
Linux Venus 4.9.59+ #1047 Sun Oct 29 11:47:10 GMT 2017 armv6l GNU/Linux
```
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

```
2018/03/08 22:17:29 [I] Log Mode: File(Info)
2018/03/08 22:17:29 [I] XORM Log Mode: File(Info)
2018/03/08 22:17:29 [I] Cache Service Enabled
2018/03/08 22:17:29 [I] Session Service Enabled
2018/03/08 22:17:29 [I] Mail Service Enabled
2018/03/08 22:17:29 [I] Migration: remove is_owner, num_teams columns from org_user
2018/03/08 22:17:29 [...itea/routers/init.go:60 GlobalInit()] [E] Failed to initialize ORM engine: migrate: do migrate: Drop table `org_user` columns [is_owner num_teams]: Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '[is_owner num_teams]' at line 1

```

## Description

I downloaded the latest gitea v1.4 for my raspberry pi, and it cannot startup.
raspberry pi model: pi zero w
link:
 [ https://dl.gitea.io/gitea/1.4/gitea-1.4-linux-arm-6 ](https://dl.gitea.io/gitea/1.4/gitea-1.4-linux-arm-6)

**Comment by duchenpaul** [comment]
Anyone has the similar issue like this?

**Comment by lunny** [comment]
duplicated with #3646

**Comment by ChangePlaces** [comment]
This isn't technically a duplicate because it's impossible to upgrade the mariadb server to 10.3 with the solution for more mainstream solutions, e.g. using a repository
