### ISSUE TITLE
Try.gitea.io returns Bad Gateway

### ISSUE THREAD

**Issue by Adrian-Voelker** [go-gitea/gitea#3654]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (https://try.gitea.io)
  - [ ] No
  - [ ] Not relevant

## Description

Try.gitea.io is not avaliable, it returns "Bad Gateway".

**Comment by techknowlogick** [comment]
@Adrian-Voelker Currently the server is out of space and is awaiting maintenance.

Per Discord: `demo server needs to be reinstalled, that will be done tomorrow
and because of new DO pricing we will get a bit more disk space for same price`

**Comment by UziTech** [comment]
[try.gitea.io](https://try.gitea.io) gives an `ERR_CONNECTION_REFUSED` error

**Comment by lafriks** [comment]
@UziTech yes, it is still being migrated. Should be back up next week

**Comment by UziTech** [comment]
Thanks. I found the temporary docs at https://app.swaggerhub.com/apis/gitea/gitea-api/1.1.1

from https://github.com/go-gitea/gitea/issues/194#issuecomment-373328193

**Comment by lafriks** [comment]
you can access swagger docs at your own instance at url: `https://<your-domain-or-ip>/api/swagger/`

**Comment by UziTech** [comment]
Nice 💯 I did not know that. Thanks

**Comment by jonasfranz** [comment]
try.gitea.io is up again -> Please close this issue

**Comment by nextlogic-ono** [comment]
It's down again.
