### ISSUE TITLE
upgrade to 1.3.3 shows 1.3.2 under each webpage

### ISSUE THREAD

**Issue by laoshaw** [go-gitea/gitea#3659]
replace 1.3.2 with 1.3.3 and restarted gitea, the new gitea is running, the website however still shows 1.3.2 at the bottom.

**Comment by Pofilo** [comment]
How did you upgrade Gitea?
We need more information to understand what happened !

**Comment by laoshaw** [comment]
I stopped gitea 1.3.2, replaced the binary with 1.3.3, then restarted gitea again, it works fine except that the webpage still tells me it's 1.3.2.  I failed to find a gitea upgrade doc, and used gogs upgrade doc as a reference.

Anyway I stopped gitea again, moved 'custom' directory away(keep data, indexers etc unchanged), restart gitea 1.3.3, saw a new custom/ directory with app.in, only two lines there though:

`
[security]
INTERNAL_TOKEN= <snip>
`
I then used the previous app.ini to overwrite this two liners app.ini, restart gitea, still everything works, but the version shows 1.3.2.

guess my question is, what's the procedure to upgrade from 1.3.2 to 1.3.3?

**Comment by lunny** [comment]
Did you have custom headers?

**Comment by laoshaw** [comment]
I only changed "Application Name", don't know what 'custom headers' mean.

**Comment by laoshaw** [comment]
sorry it's my fault, I tried it on a different server which ran a 1.3.2, 1.3.3. upgrade by just directly replace the 1.3.2 on the right server worked fine.
