### ISSUE TITLE
Feature Request | Markdown Link as GitHub does

### ISSUE THREAD

**Issue by alexandrestein** [go-gitea/gitea#3667]
## Description

It can be useful to know how to deal with the markdown.
I trued to make the changes on my own but I got too many errors and the software is really heavy.
Sorry...

It would only be a template update to have some thing similar to `GitHub` with the link `Styling with Markdown is supported`.
But in our case the link would point to [daring fireball](https://daringfireball.net/projects/markdown/syntax).

## Screenshots

![capture d ecran de 2018-03-13 15-36-31](https://user-images.githubusercontent.com/5431025/37349294-5f9b236e-26d6-11e8-8cb1-aec99c051a4d.png)

**Comment by jonasfranz** [comment]
I think that an external link is not a good idea.

**Comment by jonasfranz** [comment]
@alexandreStein You could add it to the docs at docs.gitea.io by creating a PR. I do not see any license information at the page itself. Do you know which license it is?

**Comment by alexandrestein** [comment]
Sorry.
You are right about the license.
The package is under BSD but there is nothing on the syntax page itself.
And I didn't found any syntax documentation in the source as well.

I'm not a licensing expert.
Does this mean that the page needs to be rewrite?
