### ISSUE TITLE
No button to merge PR

### ISSUE THREAD

**Issue by AntouanK** [go-gitea/gitea#3668]
- Gitea version (or commit ref): a2a49c9
- Git version: 2.15.0
- Operating system: docker
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
 Cannot merge PR anymore!
I pulled the latest docker image earlier today.
Now, when I open a PR in any private repo, there's no button to merge it! Am I missing something?
Seems like it's related to this commit https://github.com/go-gitea/gitea/commit/a2a49c93c78a81d1eaa6b0eaf84a0c3f4bcd2487 ? 

## Screenshots
![screenshot_2018-03-13_18-09-20](https://user-images.githubusercontent.com/4569111/37361017-c46a0446-26e9-11e8-949c-f779164e0465.png)

**Comment by lafriks** [comment]
Is master branch protected?

**Comment by AntouanK** [comment]
Yes, and develop. But from direct commits. Not PRs
I had it like that in previous versions and it worked fine.

**Comment by lunny** [comment]
Do you in whitelist on protected branch?

**Comment by AntouanK** [comment]
No, I didn't add anything in the whitelist.

**Comment by lunny** [comment]
Yes. https://github.com/go-gitea/gitea/pull/3544 ask you have to add the people who has permission to merge pull request, not repo writers any more.

**Comment by lafriks** [comment]
@lunny this should probably be changed if noone is specified in whitelist than everyone can merge, otherwise it will break a lot of instances

**Comment by lunny** [comment]
We need a migration?

**Comment by lafriks** [comment]
@lunny no just add if non are defined than everyone with write rights can merge

**Comment by lunny** [comment]
@lafriks but that's conflict with the push policy.

**Comment by lafriks** [comment]
@lunny kind of, direct push is still not possible. GitHub also allow merge to protected branches for writers but does not allow direct pushes. 
Currently it is possible to allow merge for everyone with write rights only by keeping this list manually up to date that is not best option and will confuse many users as it was working for them in up to 1.4.x

**Comment by lafriks** [comment]
Also it is currently not possible to set that users can merge but not push directly. As if adding user to whitelist will actually make branch protection a bit useless... I think we have made it worse with #3544 than it was before...

**Comment by Chri-s** [comment]
What would be a good solution? Adding a second whitelist for users which are allowed to merge but not to push directly to the branch? And perhaps allowing everyone with write access to merge if both whitelists are empty?

For my workflow it is important that some users have write access to the repository but don't have any chance to push or merge into the protected branches.

**Comment by lunny** [comment]
@Chri-s @lafriks  add a whitelist to set who can merge pull request. And then the old whitelist is only who can push directly. The new whitelist is optional, if it is not checked, then the people who can push directly could merge pull request like currently master version. And it's default not checked for compitable. So that both your requirement could be resolved.
