### ISSUE TITLE
Enhance closed PR and Issue status in the list

### ISSUE THREAD

**Issue by mmarif4u** [go-gitea/gitea#3669]
Currently the closed PRs list is showing copy like `opened two months 2 ago` etc.
![selection_002](https://user-images.githubusercontent.com/1280585/37383260-991b64da-2782-11e8-9fe0-e3bf56f582e4.png)

Suggestion: change the copy based on the PR status like closed, merged etc with the latest time.
e.g: if merged `closed and merged 20 mins ago`, if closed with out merge `closed 20 mins ago` etc.

What you guys think.

**Edit:**  same goes for issues but with closed keyword.

**Comment by lafriks** [comment]
no need to say `closed and merged` as when merged it can not be left open so saying `merged 29 mins ago` would be better

**Comment by mmarif4u** [comment]
@lafriks you are right. :)
