### ISSUE TITLE
SCRIPT_TYPE setting is not working

### ISSUE THREAD

**Issue by gdudas** [go-gitea/gitea#367]
- Gitea version (or commit ref): 0.9.99.0915
- Git version: 2.4.11
- Operating system: Linux amd64
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Log gist:

## Description

When there is no bash on the system, git push gives an error, even if SCRIPT_TYPE is set to sh.

remote: env: can't execute 'bash': No such file or directory
remote: error: hook declined to update refs/heads/master

**Comment by bkcsoft** [comment]
I think you need to run `Rewrite all update hook of repositories (needed when custom config path is changed)` in the admin-panel under Dashboard :)

**Comment by tboerger** [comment]
Exactly like @bkcsoft said, you need to rewrite the hooks via admin ui

**Comment by tboerger** [comment]
If you got further questions to that feel free to join our gitter chat
