### ISSUE TITLE
Search code in repository

### ISSUE THREAD

**Issue by mmarif4u** [go-gitea/gitea#3671]
- Gitea version (or commit ref): 1a83581

I have enabled search code in repository. I have few files from gitea like head.tmpl, app.ini, Default for labels etc in it.

If i search for `enhancement`, i get the following result.
```
#14dfd9 duplicate
#97df14 enhancement
#dfb014 api
```

But if i search for `#97df14` or `97df14`, it does not return anything. Nothing found.

Another example, i search for `SECRET_KEY` which is in app.ini, it returns nothing found. 
Search for `localhost` return correct file and location which is app.ini.

Same for `custom.css`, which is in head.tmpl file, nothing found. But if i search for `Custom` it do return the correct files and code area.

Am i missing something here?

**Comment by techknowlogick** [comment]
It could be that the indexing isn't fully complete. Have you run these same tests again later on?

**Comment by techknowlogick** [comment]
Closing. Please re-open if you are still experiencing this.
