### ISSUE TITLE
dashboard customization

### ISSUE THREAD

**Issue by laoshaw** [go-gitea/gitea#3677]
The dashboard shows 20 newest items, can this be changed? ideally with a navigation bar at the bottom that can page down to more items? Say I would like to review the recent 50 items instead of 20, is this configurable?

**Comment by appleboy** [comment]
This https://github.com/go-gitea/gitea/blob/4163cdf3ea6d6ca43b694de0c15cc93659d6c2b3/custom/conf/app.ini.sample#L62-L63

**Comment by laoshaw** [comment]
from what I can tell this config option is about how many repos on explorer page, not how many commits on dashboard?

**Comment by hoxnox** [comment]
This feature was in gogs. I wonder why it was removed...

**Comment by lunny** [comment]
@hoxnox The dashboard has been rewritten via Vue, but I don't against add it back.

**Comment by mrsdizzie** [comment]
Fixed in #12469
