### ISSUE TITLE
JavaScript syntax highlighting breaks

### ISSUE THREAD

**Issue by realies** [go-gitea/gitea#3682]
The title should be concise enough. Tested against `1324d62 `.

<img width="651" alt="screen shot 2018-03-16 at 22 48 41" src="https://user-images.githubusercontent.com/5107843/37548064-4edf4ebc-296d-11e8-81d0-9320628a0b3e.png">

The comment highlighting continues until EOF.

**Comment by lafriks** [comment]
As our used library for syntax highlighting is not maintained anymore we should probably switch to https://github.com/PrismJS/prism for example

**Comment by tankerkiller125** [comment]
@lafriks As another note regarding prism has the autoloader plugin would greatly reduce the amount of JS being moved around as it would be loading one language at a time instead of all of them the way highlightjs currently does.

**Comment by lafriks** [comment]
@tankerkiller125 that would be doable but problem is that for larger diff/code pages prism performance is quite bad :(

**Comment by daviian** [comment]
@lafriks Maybe we should use something like https://github.com/alecthomas/chroma

This one is also used in Huge AFAIK

**Comment by SylEze** [comment]
Hey, any news about this issue?
I'm currently facing the same problem in C++ when using Doxygen style comments:

Over a structure:
![2019-06-21_10-08-26](https://user-images.githubusercontent.com/14373103/59908032-be9d2980-940c-11e9-9c23-f2ca85e059a8.png)

Over a function member:
![2019-06-21_10-08-59](https://user-images.githubusercontent.com/14373103/59908033-be9d2980-940c-11e9-820c-9b3d29227217.png)
