### ISSUE TITLE
Raspbian arm-6 upload files number and size limited to 5 and 3MB

### ISSUE THREAD

**Issue by BRMateus2** [go-gitea/gitea#3686]
- Gitea version (or commit ref): 88aef6e #3684 Gitea 1.4 Master 20180318 binary
- Gitea version (or commit ref): Gitea 1.4 gitea-1.4-linux-arm-6 binary
- Git version: 2.11.0
- Operating system: Raspbian Stretch Lite (Debian CLI) RPI-2-ModelB arm-6
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:
2018/03/18 00:25:07 [I] Log Mode: File(Info)
2018/03/18 00:25:07 [I] XORM Log Mode: File(Info)
2018/03/18 00:25:07 [I] Cache Service Enabled
2018/03/18 00:25:07 [I] Session Service Enabled
2018/03/18 00:25:08 [I] Git Version: 2.11.0
2018/03/18 00:25:08 [I] SQLite3 Supported
2018/03/18 00:25:08 [I] Run Mode: Production
2018/03/18 00:25:11 [I] Listen: http://0.0.0.0:60005
2018/03/18 00:25:11 [I] LFS server enabled

## Description
I can provide direct access to the Raspberry;
I have installed and running from binary _with_ an NGINX proxy (HTTP/HTTPS->HTTPS->Gitea), everything works ok except somewhat the most important thing:
*I cannot upload more than 5 files in Google Chrome
*I cannot upload anything larger than 3MB
*The configuration file is loaded correctly, as I have removed the cfg file and it went to "First Install", and port works (60005)

This is possible an arm-6 code issue?
$gitea/custom/conf/app.ini
[code]
APP_NAME = Gitea Distributed Version Control System
RUN_USER = git
RUN_MODE = prod

[attachment]
ENABLE = true
ALLOWED_TYPES = */* #Consider this the "all files" as github bugs
MAX_SIZE = 20
MAX_FILES = 1000

[security]
INTERNAL_TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYmYiOjE1MjEzMTM4NzR9.fPSFUhfJC0tSGguvpPb1DER1uvLFY-dZ3iY1yFbjX1o
INSTALL_LOCK   = true
SECRET_KEY     = <secret>

[database]
DB_TYPE  = mysql
HOST     = 127.0.0.1:60006
NAME     = Gitea
USER     = gitea
PASSWD   = H2U0Evu6Osca2lPL
SSL_MODE = disable
PATH     = data/gitea.db

[repository]
ROOT = /home/git/gitea-repositories

[server]
SSH_DOMAIN       = localhost
DOMAIN           = localhost
HTTP_PORT        = 60005
ROOT_URL         = http://localhost:60005/
DISABLE_SSH      = false
SSH_PORT         = 60000
LFS_START_SERVER = true
LFS_CONTENT_PATH = /home/git/Gitea/data/lfs
LFS_JWT_SECRET   = <secret>
OFFLINE_MODE     = false

[mailer]
ENABLED = false

[service]
REGISTER_EMAIL_CONFIRM            = false
ENABLE_NOTIFY_MAIL                = false
DISABLE_REGISTRATION              = false
ENABLE_CAPTCHA                    = false
REQUIRE_SIGNIN_VIEW               = false #If false, anonymous can see public reps
DEFAULT_KEEP_EMAIL_PRIVATE        = false
DEFAULT_ALLOW_CREATE_ORGANIZATION = true
DEFAULT_ENABLE_TIMETRACKING       = true
NO_REPLY_ADDRESS                  = example

[picture]
DISABLE_GRAVATAR        = false
ENABLE_FEDERATED_AVATAR = true

[openid]
ENABLE_OPENID_SIGNIN = true
ENABLE_OPENID_SIGNUP = true

[session]
PROVIDER = file

[log]
MODE      = file
LEVEL     = Info
ROOT_PATH = /home/git/Gitea/log
[/code]

## Screenshots
![img0](https://user-images.githubusercontent.com/21206853/37562324-425b7b7a-2a44-11e8-95e1-887e2f6494f3.png)

##Related
https://github.com/go-gitea/gitea/issues/3586

**Comment by lunny** [comment]
see https://docs.gitea.io/en-us/config-cheat-sheet/

**Comment by BRMateus2** [comment]
I did that already, I've tried for many hours different "attachment" positions, as I have included the configuration file (and deleted just to be sure Gitea is loading it, as I wrote it went to fresh install; replaced back and settings back). Restart every time, even reboot to be sure.
... fixed ENABLE, to ENABLED, no effects as true is default
[attachment]
ENABLED = true
ALLOWED_TYPES = */*
MAX_SIZE = 20
MAX_FILES = 1000
...

Even tried attachments but doesn't work.

**Comment by BRMateus2** [comment]
Oh well, I found the problem!!!
Taken from https://github.com/go-gitea/gitea/blob/master/custom/conf/app.ini.sample
Documentation is somewhat misleading and doesn't point to this, browser settings are another configuration topic:
[repository.upload]
; Whether repository file uploads are enabled. Defaults to `true`
ENABLED = true
; Path for uploads. Defaults to `data/tmp/uploads` (tmp gets deleted on gitea restart)
TEMP_PATH = data/tmp/uploads
; One or more allowed types, e.g. image/jpeg|image/png. Nothing means any file type
ALLOWED_TYPES =
; Max size of each file in MB. Defaults to 3MB
FILE_MAX_SIZE = 3
; Max number of files per upload. Defaults to 5
MAX_FILES = 5
