### ISSUE TITLE
gitea instance for a single organization

### ISSUE THREAD

**Issue by waozixyz** [go-gitea/gitea#3687]
hey dear gitea community!
This is not an issue, just an idea.

i was wondering what people think of having a gitea instance for just a single organization and adding configurations for this case scenario.

some configurations that would include this is:
 - not allowing users to create organizations
 - having a simplified url such as git.<your-domain>.<tld> would actually be the organization url of the gitea repository.
 - replacing the home page the the organization repository

another more far fetched idea is to try and federate gitea instances, allowing people to fork and request pull requests from any gitea instance ;)

**Comment by Treora** [comment]
I would likewise love to have a single user/organisation per instance, with federation between instances for collaboration. Some of the relevant discussion I found so far:
 - Federation for organization, repositories and users #1612
 - Support federated pull requests #184
 - Support federated login for guest users (OpenID) #185

FYI past few days I have been playing with gitea's templates to hide the things that seem irrelevant for a single-user instance (and to more generally make a minimal interface). See [code.treora.com](https://code.treora.com) for the current status.

**Comment by ad-si** [comment]
@Treora Cool! Would be interested in the code as well :grin:

**Comment by giteauser** [comment]
@Treora Just realize people can still browse to pages like /explore and see who the admin user is at /explore/users

**Comment by kolaente** [comment]
You can set the limit for new organisations to 0 to prevent users from creating new orgs.

**Comment by Treora** [comment]
@spaceywolfi, @ad-si: in case you are still interested, I just extracted my template modifications into a repo, published [here](https://code.treora.com/gerben/my-gitea-templates) (sorry for the delay). Be warned it is quite hacky and unfinished.

**Comment by fhennig** [comment]
Just found this issue through google and wanted to know if there are any updates on this issue?

**Comment by r0bbie** [comment]
Noticed this issue had been closed - has it now been implemented?
