### ISSUE TITLE
Github to Gitea repository migration script

### ISSUE THREAD

**Issue by mehulsbhatt** [go-gitea/gitea#3688]
Is there any way where i can migrate all my github repository to private gitea server using any command or script.

**Comment by JonasFranzDEV** [comment]
I've created a tool to migrate all github repositories to your gitea instance. It also supports transferring issues etc. to gitea optionally.

https://git.jonasfranz.software/JonasFranzDEV/gitea-github-migrator

This command will transfer all of your github repos to gitea without transferring issues and other stuff.
```bash
gitea-github-migrator migrate-all \
    --gh-user username \
    --gh-token GITHUB_TOKEN \
    --url http://gitea-url.tdl \
    --token GITEA_TOKEN \
    --owner 1
    --only-repo
```
Replace `--owner 1` with the user's id who should own the repositories in gitea.

**Comment by mehulsbhatt** [comment]
Thank you so much
