### ISSUE TITLE
Posibility to display Full Name in comments and commits

### ISSUE THREAD

**Issue by JulianScharunge** [go-gitea/gitea#3697]
is it possible to display the Full Name attribute of a User in posts and commits instead of username.  I'm using AD Autentication wiith 'cn'  as  username. It is a combination of numbers and letters wich is perfect for users to log in because its shorter to type. But if other users want to know who wrote a comment it would be much nicer to display the full name.

**Comment by ghost** [comment]
It was requested for asignees as well over #3509.

I think there should be setting somewhere which we control if we want to show full names for users, organizations, teams (I think teams should also have full names as well) and repositories (I think repositories should also have full names or titles too!) in any page.

When I look at my dashboard, I want to see real names, not url slugs.

**Comment by Exagone313** [comment]
I have *the opposite* suggestion, to be able to display the nickname everywhere even if you enter `Full name`. It could be a setting set by the named user rather than other users. (I want to display my nickname in favor of my full name, but I want to display both on my profile.)

**Comment by lafriks** [comment]
Yes this could be option, might be even as user preference

**Comment by pat-s** [comment]
Would love to have this as well. Are there any plans to integrate this feature in the near future?

**Comment by HoffmannP** [comment]
So sometimes we need a username for easy typing and/or AD/LDAP authentication. We possibly want to keep the full name for official stuff. Why don't we let users *change* a new nickname (as opposed to the username) from either two of the previous to something the like and show this nickname everywhere?
Would mean to add another userfield, set it's default to the username and change every display to this (keep displaying the full name on hoover).
Seems easy peasy and full freedom?
