### ISSUE TITLE
Cronless webhooks

### ISSUE THREAD

**Issue by xPaw** [go-gitea/gitea#37]
Is there any reason why webhooks are run on cron and not on each push? The delay is really annoying every time someone pushes and it can take up to a full minute to see the changes in IRC.

**Comment by tboerger** [comment]
Some kind of queue system for async jobs would make sense instead of using a cron system.

**Comment by vtolstov** [comment]
Yes i think about this, but for workaround fix i add ability to run hook every second =)

**Comment by tboerger** [comment]
> Yes i think about this, but for workaround fix i add ability to run hook every second =)

:+1:

**Comment by lunny** [comment]
@xPaw, do you think we can close this? Or maybe we need real time web hook?

**Comment by tboerger** [comment]
There have been a commit/merge short time ago for gogs with realtime web hooks.

**Comment by lunny** [comment]
Yes, I see. And which is better? Cronless or not?

**Comment by tboerger** [comment]
IMHO the cronless variant. I will create a PR for all stuff merged the last days. Then we can discuss which makes sense for us :)

**Comment by lunny** [comment]
OKay!

**Comment by lunny** [comment]
This has been resolved via #139, so I think we can close this.
