### ISSUE TITLE
Search a repository

### ISSUE THREAD

**Issue by Fastidious** [go-gitea/gitea#3701]
- Gitea version (or commit ref):
- Git version: `N/A`
- Operating system: `N/A`
- Database (use `[x]`): `N/A`
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:

## Description

I have looked, and I have not found the ability to search the contents of a repository (like GitHub allows, for example). Could it be implemented?

**Comment by lunny** [comment]
If you mean search the code, gitea has implemented this issue. You could enable it on app.ini.

**Comment by Fastidious** [comment]
@lunny where? I searched `app.ini.sample` and found nothing related to search.

**Comment by lunny** [comment]
see https://docs.gitea.io/en-us/config-cheat-sheet/
```
Indexer (indexer)
ISSUE_INDEXER_PATH: indexers/issues.bleve: Index file used for issue search.
REPO_INDEXER_ENABLED: false: Enables code search (uses a lot of disk space).
REPO_INDEXER_PATH: indexers/repos.bleve: Index file used for code search.
UPDATE_BUFFER_LEN: 20: Buffer length of index request.
MAX_FILE_SIZE: 1048576: Maximum size in bytes of files to be indexed.
```
