### ISSUE TITLE
email notify setting

### ISSUE THREAD

**Issue by jingzhaoyang** [go-gitea/gitea#3702]
I want to be able to send an email to the assigned person in issue, not to all the followers.
How do you set this?

**Comment by lunny** [comment]
It's not supported now.

**Comment by jingzhaoyang** [comment]
Thank you for your reply. Another question is whether issue can only assign one person？

**Comment by lunny** [comment]
@jingzhaoyang currently yes.

**Comment by kolaente** [comment]
@jingzhaoyang I've opened a pr for multiple assignees: #3705

**Comment by jingzhaoyang** [comment]
@kolaente  It's great.

**Comment by wxiaoguang** [comment]
Followers should unsubscribe the notifications if they do not want to receive emails.
