### ISSUE TITLE
.editorconfig settings not working

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#3703]
- Gitea version (or commit ref): 1.3.3
- Git version: N/A
- Operating system: Windows/OS X
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No (It's down)
  - [ ] Not relevant
- Log gist: N/A

## Description

`.editorconfig` settings are not being honored anymore. For example, `insert_final_newline = true` is not inserting a final new line in Gitea's own `.editorconfig` file.
Also confirmed that `trim_trailing_whitespace = true` is not trimming anything on my personal files.

https://github.com/go-gitea/gitea/blob/master/.editorconfig

**Comment by megadr01d** [comment]
Invalid, human error.
