### ISSUE TITLE
Cannot get commits via API

### ISSUE THREAD

**Issue by Ceda-EI** [go-gitea/gitea#3710]
- Gitea version (or commit ref): 1.3.3
- Git version: 2.16.2
- Operating system: Arch Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

There should be an option for getting the commits from the API. However, since in most of projects, the number of commits is huge, there should also be an option to get a specified number of commits.

## Screenshots
Irrelevant

**Comment by sapk** [comment]
Fixed by #6408.
