### ISSUE TITLE
Raise failed authentication log entry to warning

### ISSUE THREAD

**Issue by Darcara** [go-gitea/gitea#3713]
- On Gitea version: 1.4.0+rc3
- Database: MySQL

## Description

Currently failed authentication attempts are logged as info into gitea.log.
All executed SQL queries are also logged as info into xorm.log which means increases file size and disk writes. 
In order to avoid the size and write problem I have increased log level to warn, but that leaves my fail2ban without the required log lines.

Alternatively add an option to disable the xorm log, or log executed SQL queries as debug, which should be better for production servers with several active users.

As an aside it would be nice to have a log of failed password reset requests .

**Comment by mckaygerhard** [comment]
related to the #2512 fiuuu from number 2XXX to 3XXX and still not reolved.. amount of 100 issues happened!? seems gitea development features raises mor and more bugs?

**Comment by lunny** [comment]
@Darcara `As an aside it would be nice to have a log of failed password reset requests .` is not resolved by #3726. Maybe you could create a new issue to describe that or I will reopen this one.

**Comment by Darcara** [comment]
I made #3745 and thanks for your fast work, much appreciated :)
