### ISSUE TITLE
no session provider 'mysql'

### ISSUE THREAD

**Issue by donlui** [go-gitea/gitea#3717]
- Gitea version (or commit ref): 1.4.0
- Git version: 2.7.4
- Operating system: Ubuntu 17.04
- Database:
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist: https://gist.github.com/donlui/a91a6ad3bc22e5198db9132742d1d865

## Description

when i try use mysql session provider, gitea print error

`panic: session: unknown provider 'mysql'(forgotten import?)`

**Comment by lafriks** [comment]
Currently only values `memory`, `file` or `redis` is supported for session storage. Probably we need to update `github.com/go-macaron/session` dependency to support this...
