### ISSUE TITLE
Issues compiling on windows

### ISSUE THREAD

**Issue by Dokman** [go-gitea/gitea#3718]
- Gitea version (or commit ref): https://github.com/go-gitea/gitea/commit/04b7fd87b9d74aa6a0c559ac218546978bbf6f33
- Git version: 2.0
- Operating system: Windows 10
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x ] No
  - [ ] Not relevant
- Log gist:

## Description

When i go to compile it for windows it give me errors
...
Error Log
   C:\Users\Sergi\AppData\Local\.meteor\packages\meteor-tool\1.6.1\mt-os.windows.x86_64\tools\static-assets\server\mini-files.js:43:13:
   Surprising path:
   /Users/Sergi/AppData/Local/.meteor/packages/stylus/2.513.13/plugin.compileStylusBatch.os/npm/node_modules/meteor/compileStylusBatch/node_modules/nib/lib/nib/size.styl
   at toDosPath
   (C:\Users\Sergi\AppData\Local\.meteor\packages\meteor-tool\1.6.1\mt-os.windows.x86_64\tools\static-assets\server\mini-files.js:43:13)
   at Object.convertToOSPath
   (C:\Users\Sergi\AppData\Local\.meteor\packages\meteor-tool\1.6.1\mt-os.windows.x86_64\tools\static-assets\server\mini-files.js:56:12)
   at Object.wrapper (C:\tools\fs\files.js:1517:25)
   at readFile (packages/compileStylusBatch/plugin/compile-stylus.js:123:21)
   at Array.map (<anonymous>)
   at processSourcemap (packages/compileStylusBatch/plugin/compile-stylus.js:143:52)
   at StylusCompiler.compileOneFile (packages/compileStylusBatch/plugin/compile-stylus.js:179:23)
   at async.eachLimit (packages/caching-compiler/multi-file-caching-compiler.js:115:45)
   at
   C:\Users\Sergi\AppData\Local\.meteor\packages\stylus\2.513.13\plugin.compileStylusBatch.os\npm\node_modules\meteor\caching-compiler\node_modules\async\lib\async.js:182:20
   at replenish
   (C:\Users\Sergi\AppData\Local\.meteor\packages\stylus\2.513.13\plugin.compileStylusBatch.os\npm\node_modules\meteor\caching-compiler\node_modules\async\lib\async.js:317:21)
   at
   C:\Users\Sergi\AppData\Local\.meteor\packages\stylus\2.513.13\plugin.compileStylusBatch.os\npm\node_modules\meteor\caching-compiler\node_modules\async\lib\async.js:328:15
   at Object.async.forEachLimit.async.eachLimit
   (C:\Users\Sergi\AppData\Local\.meteor\packages\stylus\2.513.13\plugin.compileStylusBatch.os\npm\node_modules\meteor\caching-compiler\node_modules\async\lib\async.js:221:35)
   at StylusCompiler.processFilesForTarget (packages/caching-compiler/multi-file-caching-compiler.js:95:11)

## Screenshots
![image](https://user-images.githubusercontent.com/2290904/37875406-cd9c18b6-303e-11e8-9be5-8889a2cd70e2.png)

**Comment by lafriks** [comment]
I don't see anything related to gitea in errors

**Comment by Dokman** [comment]
so what i have to setup? or there is no support on windows?

**Comment by edacval** [comment]
https://github.com/meteor/meteor/issues/5372

**Comment by lunny** [comment]
Don't think that's gitea related.
