### ISSUE TITLE
Refactor createComment for Issue assignees

### ISSUE THREAD

**Issue by kolaente** [go-gitea/gitea#3722]
IMHO, the structure to create a comment when assigning or un-assigning someone to an issue is terrible, it is not clear at who (un)assigned who. I think each of these "events" (`assigned someone`, `assigned itself`, `unassigned someone`, `unassigned itself` should be a seperate comment type instead of saving an extra pararmeter for _every comment_ for this.

(I'll do this some time, probably once #3705 is merged, sorry if I wasn't very clear with what I mean)

**Comment by delvh** [comment]
I think that's already implemented since a long time.
