### ISSUE TITLE
Compare button on upstream repo leads to 404

### ISSUE THREAD

**Issue by mxmehl** [go-gitea/gitea#3727]
- Gitea version (or commit ref): 1.4.0
- Git version: 2.1.4
- Operating system: Debian 8
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No 
  - [x] Not relevant: does not work

## Description

Scenario: I, user `joe`, forked repository `repo` of another user called `upstream`.

Now, if I am on joe/repo and click on the green compare button, everything works as expected and I see the "Compare Changes" window. However, this doesn't work on upstream/repo, there I see a 404 error.

I noted that the 404 does not appear if I'm owner of the upstream repository's organisation.

The links of the button look like this:

`https://git.example.org/upstream/repo/compare/master...joe:master` from forked repo -> works
`https://git.example.org/upstream/repo/compare/master...upstream:master` from upstream repo -> doesn't work

I cannot check how the links looked like in 1.3, but I was told by a user on my Gitea instance that it worked before.

**Comment by ghost** [comment]
> I cannot check how the links looked like in 1.3, but I was told by a user on my Gitea instance that it worked before.

I can confirm that.

**Comment by lafriks** [comment]
Does link `https://git.example.org/upstream/repo/compare/master...master` work?

**Comment by mxmehl** [comment]
> Does link https://git.example.org/upstream/repo/compare/master...master work?

No, this also generates an 404. As repo or organisation owner it seems to work though.

**Comment by lafriks** [comment]
What rights does user `joe` does for upstream repo? Is it private or public?

**Comment by ghost** [comment]
Please note that the 'New Pull Request' button in the Pull Requests tab works perfectly and generates this link:

```
https://git.example.org/upstream/repo/compare/master...joe:master
```

**Comment by mxmehl** [comment]
> What rights does user `joe` does for upstream repo? Is it private or public?

No specific permissions (i.e. no organisation or team member, or collaborator). The repo is public.

**Comment by adelowo** [comment]
Sent a PR for this already

**Comment by notgood** [comment]
Broken for me since today upgrade to 1.7.1.

My scenario: repo owned by organization, no forks, green compare button generates link /orgname/reponame/compare/master...MyUsername:master, which is failing horribly with 404.
Going through Pull Requests->New Pull Request generates /orgname/reponame/compare/master...master, working as expected.

**Comment by zeripath** [comment]
Argh. We need better UI tests. 

@adelowo do you think we should just revert your patch.

**Comment by adelowo** [comment]
@zeripath Argh, yes, my bad, I didn't test all scenarios

I will look at this again during the weekend but it should be reverted in the main time

**Comment by adelowo** [comment]
See https://github.com/go-gitea/gitea/issues/5924#issuecomment-459868372

**Comment by dmolineus** [comment]
Another thing, I see here. The given url does not url encode the branch name which leads to another 404 even if user prefix wouldn't be there.

1. Expected link `customer-projects/***-photo/compare/master...hotfix%2Fphp-7-compatiblity`
2. Acutal link `customer-projects/***-photo/compare/master...username:hotfix/php-7-compatiblity`

**Comment by lunny** [comment]
@dmolineus which version are you using? I think this has been resolved by #6098

**Comment by dmolineus** [comment]
@lunny Im using `1.7.2 built with go1.11.5`. The mentioned PR isn't released yet, so maybe it's resolved. Thanks for pointing it out.

**Comment by mrsdizzie** [comment]
Should be resolved from linked PRs
