### ISSUE TITLE
repo folder created in lower case only

### ISSUE THREAD

**Issue by mjsurette** [go-gitea/gitea#3728]
- Gitea version (or commit ref): 321cc2a3d0f267f8b0f5bb4365572636f1ce0443
- Git version: 2.11.0
- Operating system: raspbian
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x ] No - can't get https://try.gitea.io to work
  - [ ] Not relevant
- Log gist:

## Description
When I create a repository with a mixed case name, ie testMe
the http link is http://raspberrypi.local:3000/msurette/testMe.git
and the ssh link is git@raspberrypi.local:msurette/testMe.git

Both of these are what I would expect.  However the folder is created as
git@raspberrypi.local:msurette/testme.git

This makes no difference on Windows and Mac filesystems, but on linux filesystems case matters.  The http link works due to browser magic, but not ssh/rsync which does not have case folding.

Mike
...

**Comment by lunny** [comment]
Any error displayed?

**Comment by mjsurette** [comment]
My bad!  It's ok now.  Sorry for the noise.

**Comment by lunny** [comment]
@mibcat duplicated with #4011, please discuss there.
