### ISSUE TITLE
Codebase language

### ISSUE THREAD

**Issue by pinkmonkeybutt** [go-gitea/gitea#373]
Gogs is **Go 75.6% Groff 10.2% CSS 8.8% JavaScript 3.9% Shell 1.3% Makefile 0.1% Batchfile 0.1%**
Gitea is **JavaScript 64.1% Go 20.0% HTML 9.3% CSS 3.7% Groff 2.5% Shell 0.2% Other 0.2%**

How is this possible?

**Comment by lunny** [comment]
Which tool did you use?

**Comment by thibaultmeyer** [comment]
It probably due to the fact that `public/plugins` directory is full of JavaScript files

![image](https://cloud.githubusercontent.com/assets/1005086/21073448/58c6239c-bede-11e6-8768-683135211063.png)

**Comment by metalmatze** [comment]
You might ask questions like this at https://gitter.im/go-gitea/gitea 😉 😊

**Comment by tboerger** [comment]
It can also be related to the vendor directory that Gogs doesn't include.
