### ISSUE TITLE
users/search API results appear to be incorrectly limited by ui/EXPLORE_PAGING_NUM value

### ISSUE THREAD

**Issue by ag-wood** [go-gitea/gitea#3731]
- Gitea version (or commit ref): 1.3.2
- Git version: 1.8.3.1
- Operating system: RedHat Enterprise Linux 7.4
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X] No - don't know how to/access is an issue.
  - [ ] Not relevant
- Log gist:

## ISSUE:
Using the users/search API with a limit option that is greater than the value configured for ui/EXPLORE_PAGING_NUM in app.ini results in the limit that is passed being ignored.

**Comment by adelowo** [comment]
___Un-stale___

**Comment by lafriks** [comment]
wasn't this fixed recently?

**Comment by adelowo** [comment]
I believe it was but I cannot find the PR.

Once I get home, I can properly for it :)

**Comment by lunny** [comment]
@lafriks I think it's not, see #6579
