### ISSUE TITLE
list of all issues/PRs of all owned repos 

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#3732]
## Description
`list of all issues of all owned repos`

from a [blog article Flexible issue management](https://foonathan.net/blog/2018/03/15/issue-management-trello-ifttt.html)

> Like many open source developers I use GitHub to publish my work. It comes with a built-in issue tracking system, however, it isn’t that great.
The main issue - no pun intended - I have with it is that there is not an easy way to see all open issues and pull requests on all repositories you have.

I can hardly give a better description of the issue.

apologies if this is already possible and I've missed it, thanks

**Comment by Pofilo** [comment]
`<insert host>/pulls?type=your_repositories&repo=0&sort=&state=open`
`<insert host>/issues?type=your_repositories&repo=0&sort=&state=open`

Do you mean something else ?
Those are obtained through the top bar: `Issues` and `PR`.

_Edit: We can find the same stuff in Github._

**Comment by ghost** [comment]
thanks it's great in gitea; still can't find it in GitHub but thanks anyway!
