### ISSUE TITLE
https://home.tuxlinuxien.com:9999/ student id /session_3_ex

### ISSUE THREAD

**Issue by 16301094** [go-gitea/gitea#3735]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

...

**Comment by lafriks** [comment]
No description
