### ISSUE TITLE
Error message should have given better error message on what is wrong at least if there is any minimum

### ISSUE THREAD

**Issue by boskiv** [go-gitea/gitea#3737]
- Gitea version (or commit ref): 321cc2a
- Git version: -
- Operating system: docker
- Database (use `[x]`):
  - [ x ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ x ] Not relevant
- Log gist:
https://gist.github.com/boskiv/cffeafcba8dc8b46fa7e095266f1ef25
## Description
Changing mirror interval to `5m` , raise non-informal message
Minimum available interval `10m`

## Screenshots

![screen shot 2018-03-29 at 11 23 26](https://user-images.githubusercontent.com/1939783/38078324-9040daa2-3344-11e8-93e4-35a79b7f0522.png)

**Comment by Ryuno-Ki** [comment]
The minimum interval is depending on a setting:

https://github.com/go-gitea/gitea/blob/73382d2132f8f242245d83f66c92761e0b477b91/routers/web/repo/setting.go#L190-L203

and

https://github.com/go-gitea/gitea/blob/73382d2132f8f242245d83f66c92761e0b477b91/routers/web/repo/setting.go#L319-L324

The translation key is `"repo.mirror_interval_invalid"`. See its translation

https://github.com/go-gitea/gitea/blob/73382d2132f8f242245d83f66c92761e0b477b91/options/locale/locale_en-US.ini#L864

I don't know, how to inject a value (the configured minimum interval) there.

**Comment by Ryuno-Ki** [comment]
Thanks, @zeripath
