### ISSUE TITLE
Release will not trigger "tag" in drone

### ISSUE THREAD

**Issue by jonasfranz** [go-gitea/gitea#3738]
- Gitea version (or commit ref): 43fc430
- Database (use `[x]`):
  - [x] SQLite

## Description
Drone will not start the pipeline if I create a release (=tag) via Gitea. But if I push a tag to Gitea it will. I think that this is caused by the fact that gitea won't push the tag to itself rather then simply creating the tag without triggering a build / webhook.

**Comment by lunny** [comment]
should be fixed by #3929

**Comment by benschweizer** [comment]
Can someone confirm this?
Looks like webhooks get fired for pushed tags, but not when they are created from the release page.

**Comment by benschweizer** [comment]
So the webhook is different. Creating a new release fires 'release' where pushed tags fire 'push'. I assume this should be handled at receiver side, I'll check the drone code.
