### ISSUE TITLE
Non-English wiki page names doesn't work for a relative links

### ISSUE THREAD

**Issue by nick-korsakov** [go-gitea/gitea#3746]
- Gitea version (or commit ref): 1.4.0
- Git version: 2.11.0
- Operating system: Debian 9.4 (amd64).
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes - [wiki page with reproduction](https://try.gitea.io/nick.korsakov/one/wiki)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

Reproduction:

- visit [wiki page](https://try.gitea.io/nick.korsakov/one/wiki);
- visit first link "Страница";
- you will jump to "/wiki/_pages" instead of "/wiki/Страница".

Expected behavior:

- visit [wiki page](https://try.gitea.io/nick.korsakov/one/wiki);
- visit first link "Страница";
- jump to "/wiki/Страница" page.

At the same time:

- relative links for an English-named pages and any absolute links works fine;
- visit other three links on [wiki page](https://try.gitea.io/nick.korsakov/one/wiki);
- and all of it will work as expected.

**Comment by jonasfranz** [comment]
Could you please post the used markdown?

**Comment by nick-korsakov** [comment]
```markdown
- [Страница](Страница) - doesn't work (Russian relative link).
- [Страница](https://try.gitea.io/nick.korsakov/one/wiki/Страница) - works (Russian absolute link).
- [Page](Page) - works (English relative link).
- [Page](https://try.gitea.io/nick.korsakov/one/wiki/Page) - works (English absolute link).
```

**Comment by lunny** [comment]
Closed now and please feel free to reopen it if it's still an issue.
