### ISSUE TITLE
Admin cannot access all teams via API

### ISSUE THREAD

**Issue by mxmehl** [go-gitea/gitea#3747]
- Gitea version (or commit ref): 1.4.0
- Git version: 2.1.4
- Operating system: Debian 8
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

I am admin on my Gitea installation and created an API key for me. Although having the highest access permission, I cannot access the API `orgs/{org}/teams` if I'm not member of this organisation (example: "other-org"):

```
$ curl -s -X GET "https://git.example.org/api/v1/orgs/other-org/teams" -H  "accept: application/json" -H "Authorization: token ce106f4de28xxxx"
{"message":"Must be an organization member","url":"https://godoc.org/github.com/go-gitea/go-sdk/gitea"
```
In the web interface I can see all information about the organization and the teams. Accessing the exact same information via API for organisations I'm member of works perfectly fine.

This behaviour is unexpected because the Admin should be able to access the same information via API as via web interface.

**Comment by yp05327** [comment]
I think this has been fixed by #6483.
