### ISSUE TITLE
[Feature] Hide Users and Orgs from public

### ISSUE THREAD

**Issue by mmarif4u** [go-gitea/gitea#3749]
Currently when `require_sign_in` is set to false, non logged in users can see all other users and organizations which in some cases may not be a good idea as some people may want to keep them private. Only show public repositories.

A setting in app.ini to enable/disable this would be nice feature to have.

**Comment by adilinden** [comment]
Yes, was looking for this too. Using organization to group repositories. Showing only organizations with public repos to to the un-logged-in would be a nice feature.

**Comment by NetOpWibby** [comment]
I'm looking to transition to Gitea from my self-hosted GitLab instance and this is a feature that I miss. `REQUIRE_SIGNIN_VIEW = true` is nice but I'd like to have _some_ public repos.

**Comment by agaida** [comment]
I would like private orgs too - somethings should stay private - and showing some empty organizations (because all repos are private/hidden isn't really helpful

**Comment by ghost** [comment]
And hiding users/organizations with a template keeps them discoverable by trying URLs. I'd like to make my admin user or other sensitive users private and undiscoverable.

**Comment by SoulSeekkor** [comment]
I'd like to add a +1 to this, looking to switch from Bitbucket but need to be able to have organizations not show up for users that don't have permissions for repos in them first.

**Comment by markg85** [comment]
Just to add a "me too".
Though personally i don't have a use for it. I can imagine people working for organisations where they prefer to keep it hidden but still organized. Thus having an option to mark an organization as private would be sane there.

**Comment by SoulSeekkor** [comment]
Yeah the fact that organizations show up for a user even though they have no permissions on any repos within it is keeping me from potentially switching over to soley using Gitea.

**Comment by stevoh6** [comment]
Hi, I was looking for this too. "Using organization to group repositories. Showing only organizations+users with public repos to to the un-logged-in" would be a nice feature.  We would like to have some hidden organizations/users with private repos together with some public organizations/users/repos.

**Comment by lunny** [comment]
Private organization has been implemented and merged into master.

**Comment by markg85** [comment]
It apparently is this commit: https://github.com/go-gitea/gitea/commit/64ce159a6eacc81962d07a8f5ef7f69c17365363

Someone should probably close this issue.

**Comment by stevoh6** [comment]
Hi all, I updated gitea to newest version and do some testing. Repositories are fine, they are hidden, but even I setup correct config settings (FORCE_PRIVATE = true, DEFAULT_PRIVATE = private, DEFAULT_ORG_VISIBILITY = private)  Users and organization are still visible even the new one. 
There isnt also any setting regarding Users. Repositories working fine. Should I create defect, or I missing something?

Edit: it will be in 1.8.x ?

**Comment by lafriks** [comment]
@stevoh6 private organization option will be in 1.8.0

Users will still be visible to all

**Comment by brallow** [comment]
I need that too. 
I need a git server which collaborate with 2 or more different organizations. They should NOT to see each other (including their org/repo) at all.

**Comment by sapk** [comment]
@brallow this should be available in the 1.8.0+ versions. You can try the latest stable version : https://github.com/go-gitea/gitea/releases/tag/v1.8.2
