### ISSUE TITLE
Dashboard does not show repositories for user

### ISSUE THREAD

**Issue by adilinden** [go-gitea/gitea#3750]
- Gitea version (or commit ref): 1.4.0 installed from binary d/l
- Git version: 2.11.0
- Operating system: Debian 9 amd 64
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X] No
  - [ ] Not relevant
- Log gist:

## Description
I have several organizations with repos and a user with repos. On Dashboard page the organization repos show up properly, but the personal repo count is '0', although there are several repos present.

I created private repo on try.gitea.io. When I go to dashboard it properly shows one repo in Dashboard.

Is this a bug in 1.4.0 or some issue with my settings or install? 

<img width="1017" alt="screen shot 2018-04-03 at 12 35 29 am" src="https://user-images.githubusercontent.com/1149715/38231223-427aa910-36d7-11e8-95eb-3ce5c8caed4a.png">
<img width="1024" alt="screen shot 2018-04-03 at 12 35 19 am" src="https://user-images.githubusercontent.com/1149715/38231224-428d91c4-36d7-11e8-8d22-f9a06c8648e4.png">
<img width="400" alt="screen shot 2018-04-03 at 12 35 00 am" src="https://user-images.githubusercontent.com/1149715/38231225-429cc2c0-36d7-11e8-894e-400b8c41b690.png">

...

**Comment by adilinden** [comment]
I built gitea commit d877bf7e, now reports as Gitea Version: 1.1.0+1126-gd877bf7e, and issue remains the same. That's the same commit as try.gitea.io reports.

**Comment by adilinden** [comment]
I wiped the install and started all over. All is working now. No idea why or what was going on. I didn't do anything that deviated from instructions. My setting with (app.ini) with the new install are identical. So I really don't know.

This can be files as "cannot be reproduced" and this issue can be closed.

**Comment by adilinden** [comment]
Sorry, there's a bug! Tuesday night installed Gitea. Wednesday created 1 user and 7 organizations. Migrated 49 repositories to Gitea. There are 24 mirrors (GitHub) and 25 standard repositories.

This morning my list of repos is 0. Because I organized repos into groups utilizing organizations (this is personal hosting) the "Dashboard" in invaluable in seeing and finding repos that I am looking for. I didn't take screenshot last night. But as I added each repo the Dashboard repo count increased appropriately and the list was populated. This morning the list is gone.

Screenshots attached.
<img width="422" alt="screen shot 2018-04-05 at 9 07 49 am" src="https://user-images.githubusercontent.com/1149715/38371039-1e01bd36-38b1-11e8-8997-4f155c68c6b4.png">
<img width="417" alt="screen shot 2018-04-05 at 9 08 03 am" src="https://user-images.githubusercontent.com/1149715/38371042-2199914e-38b1-11e8-8a29-9598104cb782.png">

**Comment by Morlinest** [comment]
@adilinden Hi.

1. Can you open any "missing" repo?
1. Do you see your repos in "Explore" page?
1. Any logs from gitea?
1. How you run gitea (docker container or directly)?
1. Can you check response of "repo widget" api call (F12 -> "network" tab -> "search?uid=.....") in your browser?

**Comment by adilinden** [comment]
Hi @Morlinest,

Yes, everything is there. I run Gitea directly. But on my firewall I run haproxy as the port is used for multiple different backend servers. On the Gitea server itself I run nginx as a reverse proxy to provide SSL with Gitea bound to localhost:3000 only.

Having me look at api call lead me to identify the source of the issue. On the haproxy I have /api directed to the wrong backend, resulting in /api not being available from the outside. When accessed from my local network, directly accessing nginx without haproxy, all is fine.

That solves this mystery - my confusion resulted from me accessing the server from different location. Plus as I am a frequent user of VPN for remote access, whether VPN was engaged also changed the behaviour.... 

Perhaps this allows me to dig into the next quest I am on, extending the repositories list to more then 15 repos. I'd like to see all repos that a user has access to in a single list, across all orgs and users. I see that the widget call to the api included a limit of 15.

That resolves this!

Thanks,
Adi

**Comment by Morlinest** [comment]
@adilinden Great you found the problem and solved it :).

Right now, to increase number of searched repos you can
- set `setting.UI.User.RepoPagingNum` in _app.ini_ (probably best way, but can affect another pages too)
- or create own template _templates/base/head.tmpl_ and change `<meta name="_search_limit" content="{{.SearchLimit}}" />` (e.g. `<meta name="_search_limit" content="100" />`).
- or create own template _templates/user/dashboard/dashboard.tmpl_ with custom `:search-limit="searchLimit"` (e.g. `:search-limit=100`).

Edit: Or you can rewrite `<meta name="_search_limit" content="100" />` on your proxy :D

**Comment by Morlinest** [comment]
I think this issue can be closed as problem was solved and it was not gitea related problem anyway.
