### ISSUE TITLE
Different internal and external port

### ISSUE THREAD

**Issue by ad-si** [go-gitea/gitea#3751]
- Gitea version (or commit ref): 1.4
- Git version: 2.7.4
- Operating system: Ubuntu 16.04.3
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist: -

## Description

I'm running gitea in Docker on port 3000 and map the external port 80 to the Docker port.
So far everything works as expected (e.g. http://code.adriansieber.com/adrian/dotfiles), but there is one problem: The clone URL is incorrect, because it sill displays the 3000 port:
http://code.adriansieber.com:3000/adrian/dotfiles.git

Is there a way to fix this?
If not, I guess there should be way to explicitly set the external port, right?

**Comment by mxmehl** [comment]
How does the `[server]` section in your Gitea config look like? I guess you made a mistake there.

**Comment by ad-si** [comment]
```ini
[server]
APP_DATA_PATH    = /data/gitea
PROTOCOL         = http
DOMAIN           = code.adriansieber.com
HTTP_PORT        = 3000
LANDING_PAGE     = explore
...
```

**Comment by lafriks** [comment]
Set `ROOT_URL = http://code.adriansieber.com/`

**Comment by ad-si** [comment]
So this overwrites the generated one `%(PROTOCOL)s://%(DOMAIN)s:%(HTTP_PORT)s/` ?

This is not clear from the documentation. I guess it should be clarified there...

**Comment by lafriks** [comment]
Please feel free to submit PR to improve docs

**Comment by ad-si** [comment]
Haha damn, I should have tested it before creating the merge request.
@lafriks Setting the ROOT_URL does not seem to change anything!
(What is it good for then anyways 🤔)

**Comment by ad-si** [comment]
@lafriks Ups, my fault, had a typo, sorry. Works as advertised 😁
