### ISSUE TITLE
Feature request: Buttons for "next commit" and "former commit" in commit view

### ISSUE THREAD

**Issue by kernie** [go-gitea/gitea#3753]
- Gitea version (or commit ref): 1.4.0
- Git version: 
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
When opening the commit view to see code changes I would be happy to see somewhere a button which leads to the "next commit" and one that goes to the "former commit". 

Reading thru commit changes involves too much clicks at the moment. 

Thank you for this great software development tool!
Maarten
...

**Comment by vijfhoek** [comment]
Note that the "former commit" button you mention already exists in the form of a "parent" button:

![image](https://user-images.githubusercontent.com/345785/40945978-756a7d9a-685b-11e8-8567-d82c34b64d82.png)

However, implementing the "next commit" button, or in git terminology browsing to a child commit, would be fairly more involved, considering a commit could have several children in case of branching.

I am not that well-versed in this part of git, but I can imagine it'd be fairly involved and maybe even quite an expensive operation, let alone the UI work needed to display all those children.
