### ISSUE TITLE
Force pushing after first commit 

### ISSUE THREAD

**Issue by realies** [go-gitea/gitea#3756]
When creating a repo and having an initial commit, then forcing pushing the second commit, the preview of the changed file in Gitea shows there is only one commit. Going to the repository home, it says there's two commits. When previewing the changed file on the master branch, it looks like it's a mix between the initial commit and the force pushed change.

**Comment by lafriks** [comment]
What version are you using?

**Comment by realies** [comment]
`4c6e170`
