### ISSUE TITLE
Migrate issues, releases and pull requests from GitHub

### ISSUE THREAD

**Issue by jonasfranz** [go-gitea/gitea#3757]
Improve the migration functionality by adding support for migrating

- [ ] Issues
- [ ] Releases
- [ ] Pull Requests

from GitHub.

**Comment by techknowlogick** [comment]
@jonasfranz closing due to your wonderful tool.

for others coming to this issue here is the tool I am talking about: https://git.jonasfranz.software/JonasFranzDEV/gitea-github-migrator

**Comment by dschaper** [comment]
Is there an updated URL for that tool? It looks like the site has been taken down.

**Comment by techknowlogick** [comment]
@dschaper see: https://gitea.com/gitea/migrator

**Comment by jolheiser** [comment]
https://gitea.com/gitea/migrator
