### ISSUE TITLE
I need a feature that bulk imports into the repository

### ISSUE THREAD

**Issue by axlrose** [go-gitea/gitea#376]
I need a feature that bulk imports into the repository
I now use the repo to achieve synchronization, my warehouse on github on the regular synchronization to the local
, Because the warehouse too much one to build trouble, so would like to get hold of the bulk import function, set a format automatically from a file in the specified format bulk import
thanks

- Gitea version (or commit ref): master
- Git version: 2.10.2
- Operating system: windows linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x ] MySQL
  - [x] SQLite

**Comment by tboerger** [comment]
I don't understand, what should be done by the bulk import?

**Comment by bkcsoft** [comment]
If you're referring to https://github.com/gogits/gogs/issues/3493 I still believe that this should be done in a separate tool

**Comment by lunny** [comment]
It's easy to do that via Gitea's API. So let's close this one.
