### ISSUE TITLE
Manipulate git repo from command line - ok to do?

### ISSUE THREAD

**Issue by adilinden** [go-gitea/gitea#3762]
- Gitea version (or commit ref): 1.4.0
- Git version: 2.11.0
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:

## Description

- Is it possible to mark a repo as read-only, for all except some users?
- Is it safe to manipulate a repo with git client directly on server rather than via ssh?
...

**Comment by adilinden** [comment]
I am not sure if I can delete my own issue - it almost seems silly to continue as I think I answered my own question in trying to describe the "issue".

I would like to populate and maintain a repo via scripting on the local server, rather than mirroring by gitea or external access via ssh. This has led to two questions:

1. Is it safe to manipulate a git repo via local git client on the same machine as gitea?

> I would think that this is safe assuming that gitea involvement in ssh access is strictly for the purpose of authentication and the interaction with repo is directly between client git and server git. But I want to be certain.

2. Is it possible to mark a repo as read-only for all access via ssh/https?

> This may be a useless question. I can just create a dedicated (machine) user for the sole purpose of writing to the git repo. As the repo is going to be public there this user would be the only user with write permissions. This user could also be a user account on the server itself. That user then instead of accessing the gitea repo directly would loopback via ssh just like any other server.

That still leaves the question, can I have a private repo, where one user is read-write and a bunch of users read-only?

**Comment by braincoral** [comment]
> 2. Is it possible to mark a repo as read-only for all access via ssh/https?

The default for public repos is that only the owner has write access and everyone else has read-only access. You can add collaborators with write access under `Settings -> Collaboration`.

> That still leaves the question, can I have a private repo, where one user is read-write and a bunch of users read-only?

If the repo is set to private you can add a user as a collaborator with read-only access under `Settings -> Collaboration`. If the repo is private, then only people added as collaborators will be able to see it.

**Comment by adilinden** [comment]
Thank you @braincoral! That definitely answers the question sufficiently.
