### ISSUE TITLE
How to build custom docker image

### ISSUE THREAD

**Issue by ilius** [go-gitea/gitea#3764]
- Gitea version (or commit ref): 7000b41
- Git version: 2.15.0
- Operating system: Ubuntu 16.04.4 LTS (Gitea inside docker 18.03.0-ce)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

We have a test in our go project, that runs 20 clone operations (with go-git) concurrently in different go routines, from the same given repo (and the URL looks like `ssh://git@try.gitea.io/ilius/test-repo.git` but from our own gitea instance)

Some of those clone operations fail with `error in clone: ssh: handshake failed: EOF`, and sometimes some of them fail with `error in clone: ssh: handshake failed: read tcp IP:PORT->IP:10022: read: connection reset by peer`
With try.gitea.io, only the second error (`read: connection reset by peer`) happens.

They all use the same ssh private key.

Although most of clone operations succeed. But even one failure makes our test fail.

**Comment by lafriks** [comment]
Could it be OpenSSH server limitation? If so possibly sshd_config needs some option changed.

**Comment by ilius** [comment]
To confirm that, I need to modify ssh config inside docker and build my own docker image
I modified "docker/etc/ssh/sshd_config" file, and ran `make` in `docker/` directory. But it gives me this error:

```
docker build --disable-content-trust=false -t gitea/gitea:latest .
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /home/ubuntu/go/src/code.gitea.io/gitea/docker/Dockerfile: no such file or directory
Makefile:10: recipe for target 'docker' failed
make: *** [docker] Error 1
```

Do you have any documentation on how to build my own custom docker image?

**Comment by nubenum** [comment]
You need to run `sudo make docker` in the root of the gitea directory, not in the docker subdirectory (see the Makefiles). I was able to build the image like that just now.

**Comment by ilius** [comment]
@nubenum Thank you very much
