### ISSUE TITLE
Gitea fails to Install using CockroachDB (PostgreSQL replacement)

### ISSUE THREAD

**Issue by techknowlogick** [go-gitea/gitea#3765]
- Gitea version (or commit ref): ed4935e6962fbbe2628904233c58f47987db49e1
- Git version: n/a
- Operating system: MacOS 10.13.4
- Database (use `[x]`):
  - [X] PostgreSQL (CockroachDB 2.0)
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Not relevant
- Log gist: https://gist.github.com/techknowlogick/11a017d4342efbe1498622d76af69456

## Description
First, I know CockroachDB is not supported as a DB by this project, however as it is mostly equivalent with postgresql I tried installing Gitea using it as the DB. It did not work. It got through the creating of the tables, and even inserted values into the `versions` table for the migrations, but once actually starting to serve web interface after installation it fatal errors. Above you can see all of the output from the stdout/stderr from the cli, but the most important line from `log/gitea.log` is:
```
2018/04/05 21:58:00 [...itea/routers/init.go:60 GlobalInit()] [E] Failed to initialize ORM engine: sync database struct error: pq: column name "numeric_precision_radix" not found
```
When trying to go through install page again (after DB has been created from previous attempt, I get the error in the screenshot below).

Again CockroachDB is not supported (at least currently), and so please close this ticket if it is an invalid request, or perhaps keep it open as a proposal for future support.

## Screenshots
![screen shot 2018-04-05 at 10 55 20 pm](https://user-images.githubusercontent.com/164197/38370189-79075d80-3924-11e8-99d0-090720906328.png)

**Comment by zllovesuki** [comment]
They do [list](https://www.cockroachlabs.com/docs/stable/sql-feature-support.html) quite a few things that are not compatible (yet).

**Comment by mqudsi** [comment]
What version of cockroach db is this? Version 2.0 should have this field:

from `src/github.com/cockroachdb/cockroach/pkg/sql/information_schema.go`:
```sql
CREATE TABLE information_schema.columns (
	TABLE_CATALOG            STRING NOT NULL,
	TABLE_SCHEMA             STRING NOT NULL,
	TABLE_NAME               STRING NOT NULL,
	COLUMN_NAME              STRING NOT NULL,
	ORDINAL_POSITION         INT NOT NULL,
	COLUMN_DEFAULT           STRING,
	IS_NULLABLE              STRING NOT NULL,
	DATA_TYPE                STRING NOT NULL,
	CHARACTER_MAXIMUM_LENGTH INT,
	CHARACTER_OCTET_LENGTH   INT,
	NUMERIC_PRECISION        INT,
	NUMERIC_SCALE            INT,
	DATETIME_PRECISION       INT,
	CHARACTER_SET_CATALOG    STRING,
	CHARACTER_SET_SCHEMA     STRING,
	CHARACTER_SET_NAME       STRING,
	GENERATION_EXPRESSION    STRING
);
```

**Comment by techknowlogick** [comment]
@mqudsi Ah yes, I've edited my comment above to note I was using version 2.0. It is likely as @zllovesuki has suggested that perhaps something related to this query isn't supported by cockroachdb yet. 

The specific query that is failing is:
```
SELECT column_name, column_default, is_nullable, data_type, character_maximum_length, numeric_precision, numeric_precision_radix ,
    CASE WHEN p.contype = 'p' THEN true ELSE false END AS primarykey,
    CASE WHEN p.contype = 'u' THEN true ELSE false END AS uniquekey
FROM pg_attribute f
    JOIN pg_class c ON c.oid = f.attrelid JOIN pg_type t ON t.oid = f.atttypid
    LEFT JOIN pg_attrdef d ON d.adrelid = c.oid AND d.adnum = f.attnum
    LEFT JOIN pg_namespace n ON n.oid = c.relnamespace
    LEFT JOIN pg_constraint p ON p.conrelid = c.oid AND f.attnum = ANY (p.conkey)
    LEFT JOIN pg_class AS g ON p.confrelid = g.oid
    LEFT JOIN INFORMATION_SCHEMA.COLUMNS s ON s.column_name=f.attname AND c.relname=s.table_name
WHERE c.relkind = 'r'::char AND c.relname = $1 AND s.table_schema = $2 AND f.attnum > 0 ORDER BY f.attnum;
```
(where $1 is user and $2 is public).

**Comment by mqudsi** [comment]
@knz any ideas?

**Comment by lunny** [comment]
I think this is blocked by https://github.com/go-xorm/xorm/issues/802

**Comment by knz** [comment]
Please file on the cockroach github, link to this issue and cc me there. Thanks
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by techknowlogick** [comment]
Just submitted a ticket on the cockroach github: cockroachdb/cockroach#24846

**Comment by knz** [comment]
As per https://github.com/cockroachdb/cockroach/issues/24846#issuecomment-381760597:

> Unfortunately the column numeric_precision_radix is implemented for information_schema.sequences but not information_schema.columns which your query is using. This is why the query fails.

> In CockroachDB the only type that uses the radix 10 is decimal (also called numeric) and every other type uses radix 2. Is there any way you can use a CASE expression to determine this in your query instead of using numeric_precision_radix?

**Comment by knz** [comment]
(we'll probably add the missing column to a later version of CockroachDB. My comment above is a suggestion for a workaround until then.)

**Comment by knz** [comment]
Actually maybe other types other than `decimal` also use radix 10. We can check together.

**Comment by fire** [comment]
I have interest in this.

**Comment by lunny** [comment]
There is a PR #11875

**Comment by efossas** [comment]
installed gitea 1.15.10 (helm chart 5.0.1) with cockroachdb v21.2.6.

when provisioning the database, make sure this cluster setting is on:
`sql.defaults.serial_normalization: 'sql_sequence'`

currently seeing 2 errors that cause 500s on Dashboards, Issues, & Pull Requests pages:

```
GetUserHeatmapDataByUserTeam: pq: unknown function: to_timestamp()
userRepoIDs: ctxUser.GetAccessRepoIDs: pq: could not determine data type of placeholder $1
```

the first error is that cockroachdb does not have the to_timestamp() function. not sure what the second error is about.

i smoke tested a bunch of stuff in Gitea, and so far have only ran into those two errors.

**Comment by lunny** [comment]
Yes, since [xorm](https://gitea.com/xorm/xorm) have declared it supports `cockroachdb`. For Gitea, there is less issues to be handle. Could you paste the second error's generated SQL so that we can find something.

**Comment by efossas** [comment]
absolutely, happy to help in any way i can. here are all the sql queries generated for the GET request to /issues:

```
2022/02/27 21:58:44 Started GET /issues for 127.0.0.1:37450
2022/02/27 21:58:44 models/user.go:1340:getUserByID() [I] [SQL] SELECT "id", "lower_name", "name", "full_name", "email", "keep_email_private", "email_notifications_preference", "passwd", "passwd_hash_algo", "must_change_password", "login_type", "login_source", "login_name", "type", "location", "website", "rands", "salt", "language", "description", "created_unix", "updated_unix", "last_login_unix", "last_repo_visibility", "max_repo_creation", "is_active", "is_admin", "is_restricted", "allow_git_hook", "allow_import_local", "allow_create_organization", "prohibit_login", "avatar", "avatar_email", "use_custom_avatar", "num_followers", "num_following", "num_stars", "num_repos", "num_teams", "num_members", "visibility", "repo_admin_change_team_access", "diff_view_style", "theme", "keep_activity_private" FROM "public"."user" WHERE "id"=$1 LIMIT 1 [1] - 3.617285ms
2022/02/27 21:58:44 ...s/issue_stopwatch.go:67:HasUserStopwatch() [I] [SQL] SELECT "id", "issue_id", "user_id", "created_unix" FROM "public"."stopwatch" WHERE (user_id = $1) LIMIT 1 [1] - 2.728579ms
2022/02/27 21:58:44 models/user.go:651:GetOrganizations() [I] [SQL] SELECT "user".*, count(repo_id) as org_count FROM "public"."user" INNER JOIN "public"."org_user" ON "org_user".org_id="user".id LEFT JOIN (SELECT id as repo_id, owner_id as repo_owner_id FROM repository WHERE ("repository".is_private=$1 AND "repository".owner_id NOT IN (SELECT id FROM "user" WHERE type=$2 AND visibility IN ($3))) OR "repository".id IN (SELECT repo_id FROM "access" WHERE user_id=$4 AND mode>$5) OR "repository".owner_id=$6 OR "repository".id IN (SELECT "team_repo".repo_id FROM team_repo INNER JOIN team_user ON "team_user".team_id = "team_repo".team_id WHERE "team_user".uid=$7) OR ("repository".is_private=$8 AND "repository".owner_id IN (SELECT "org_user".org_id FROM org_user WHERE "org_user".uid=$9))) repository ON "repository".repo_owner_id = "org_user".org_id WHERE ("org_user".uid=$10) GROUP BY "user".id,"user".lower_name,"user".name,"user".full_name,"user".email,"user".keep_email_private,"user".email_notifications_preference,"user".passwd,"user".passwd_hash_algo,"user".must_change_password,"user".login_type,"user".login_source,"user".login_name,"user".type,"user".location,"user".website,"user".rands,"user".salt,"user".language,"user".description,"user".created_unix,"user".updated_unix,"user".last_login_unix,"user".last_repo_visibility,"user".max_repo_creation,"user".is_active,"user".is_admin,"user".is_restricted,"user".allow_git_hook,"user".allow_import_local,"user".allow_create_organization,"user".prohibit_login,"user".avatar,"user".avatar_email,"user".use_custom_avatar,"user".num_followers,"user".num_following,"user".num_stars,"user".num_repos,"user".num_teams,"user".num_members,"user".visibility,"user".repo_admin_change_team_access,"user".diff_view_style,"user".theme,"user".keep_activity_private ORDER BY "user"."name" ASC [false 1 private 1 0 1 1 false 1 1] - 12.826551ms
2022/02/27 21:58:44 models/user.go:529:GetActiveRepositoryIDs() [I] [SQL] SELECT "repository"."id" FROM "public"."repository" INNER JOIN "public"."repo_unit" ON repository.id = repo_unit.repo_id WHERE "repo_unit"."type" IN ($1) AND is_archived=$2 AND (owner_id = $3) GROUP BY repository.id [UnitTypeIssues false 1] - 4.578558ms
2022/02/27 21:58:44 models/user.go:564:GetActiveOrgRepositoryIDs() [I] [SQL] SELECT "repository"."id" FROM "public"."repository" INNER JOIN "public"."team_user" ON repository.owner_id = team_user.org_id INNER JOIN "public"."team_repo" ON ($1 != $2 and repository.is_private != $3) OR (team_user.team_id = team_repo.team_id AND repository.id = team_repo.repo_id) WHERE (team_user.uid = $4) AND is_archived=$5 GROUP BY repository.id [true false true 1 false] - 1.199347ms
2022/02/27 21:58:44 routers/user/home.go:423:buildIssueOverview() [E] userRepoIDs: ctxUser.GetAccessRepoIDs: pq: could not determine data type of placeholder $1
2022/02/27 21:58:44 ...dels/notification.go:711:GetNotificationCount() [I] [SQL] SELECT count(*) FROM "public"."notification" WHERE (user_id = $1) AND (status = $2) [1 1] - 2.824677ms
2022/02/27 21:58:44 Completed GET /issues 500 Internal Server Error in 30.288457ms
```

**Comment by lunny** [comment]
This is an known issue which #11875 try to fix.

**Comment by ZsBT** [comment]
I don't see improvements with Gitea 1.22.2 and Cockroach v24.2.0.
Did anyone find a workaround? I could not find yet due to ORM environment.

**Comment by techknowlogick** [comment]
@ZsBT sadly, what's required is that cdb needs to have additional support for PostgreSQL compatibility (one such example is the datetime function we use for heatmap calculations is missing in cdb). There is probably functionality we could disable for cdb to at least somewhat work as a db for gitea, but even adding in the logic to give a subpar experience adds additional maintenance overhead for the other DBs and the application itself.

I might look at this again in the future, but to clean up the list of issues I've opened, I'm going to close this now. If someone else wants to look into it, please feel free to ask to have it re-opened. Closing this ticket doesn't mean this will never happen or there is any opposition to adding support for cdb.

**Comment by ZsBT** [comment]
Thanks, indeed this is more likely a CockroachDB issue, therefore I opened https://github.com/cockroachdb/cockroach/issues/131306 .
