### ISSUE TITLE
SSH not accessible / configuration issue?

### ISSUE THREAD

**Issue by redradrat** [go-gitea/gitea#377]
- Gitea version (or commit ref): master
- Git version: 2.8.3
- Operating system: gitea/gitea Docker Image | Alpine 3.4
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite

## Description

There might be something wrong with the sshd config on the gitea docker image. Spinning up a fresh container and adding my ssh key, logging in with

    ssh -l git INSTANCEADDRESS -p PORT

is not possible.

Output sshd.log

    rexec line 21: Unsupported option PrintLastLog
    User git not allowed because account is locked
    input_userauth_request: invalid user git
    Failed none for invalid user git from XXX.XXX.XXX.XXX port XXXXX ssh2
    Failed publickey for invalid user git from XXX.XXX.XXX.XXX port XXXXX ssh2
    Connection closed by XXX.XXX.XXX.XXX port XXXXX

With the latest gogs image that is not the case.

**Comment by redradrat** [comment]
To clarify:

gogs responds to the ssh login with
```
PTY allocation request failed on channel 0
Hi there, You've successfully authenticated, but Gogs does not provide shell access.
If this is unexpected, please log in with password and setup Gogs under another user.
Connection to XXX.XXX.XXX.XXX closed.
```

Which is the expected response, and confirms the sshd config.

**Comment by bkcsoft** [comment]
@tboerger @xinity  IIRC you guys knows the docker-image best

**Comment by tboerger** [comment]
Will get into that directly when I'm launching try.gitea.io

**Comment by tboerger** [comment]
So https://github.com/go-gitea/gitea/pull/386 will solve this issue. But be warned that we would like to restructure some of the volume directories because it got currently a pretty weird too deep nested structure.
