### ISSUE TITLE
Page not reacting while long-running migration/mirror initialization

### ISSUE THREAD

**Issue by kb-1000** [go-gitea/gitea#3770]
- Gitea version (or commit ref): 1.4.0
- Git version: not relevant, 2.16.3.windows.1
- Operating system: not relevant, Windows
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL) https://try.gitea.io/kaeptmblaubaer1000/cpython.git
  - [ ] No
  - [ ] Not relevant
- Log gist: not relevant

## Description

The response is delayed as long as the download takes.
It should rather either show that the download is in progress, or the progress (like GitHub Desktop does).

**Comment by tankerkiller125** [comment]
This really needs to be resolved, on large repos the page will timeout and break the repo causing a 500 error.

**Comment by techknowlogick** [comment]
Please review https://docs.gitea.io/en-us/config-cheat-sheet/ for `git.timeout` settings and increase the timeouts.

**Comment by kb-1000** [comment]
Please reopen this issue!

**Comment by zeripath** [comment]
The problem is how to fix this. Clearly we should put this clone in a separate goroutine and return. But  we probably need to monitor the migration somehow.

I guess a quick fix is to see if just sticking the clone and it's following parts in a goroutine is enough.

**Comment by zeripath** [comment]
Not stale - sorry that was my fault for not removing the stale tag. It shouldn't happen anymore.

**Comment by zeripath** [comment]
@kaeptmblaubaer1000 is there any chance you could test my pr to see if it solves your issue?

**Comment by kb-1000** [comment]
If it doesn't wait for completion of mirror / import clone before returning the response page, then it solved the issue... but unfortunately I can't test it, as I don't have Go on my computer (only on my phone) and I don't currently use Gitea anyway, because there is currently no need for it for me.

**Comment by tankerkiller125** [comment]
@zeripath If you are currently running Gitea someplace try cloning the emoji-data repo (https://github.com/iamcal/emoji-data) if it continues and doesn't freeze AND you don't get a 500 error when you go to the repo in gitea then you've resolved the issue. If it freezes then it's not fixed and if you get a 500 error then that means that some sort of "Please Wait while we clone the Repo" page needs to be created and displayed.

Note: the Emoji-Data repo is about 2GB (raw git) make sure you have enough space before cloning.

**Comment by mrsdizzie** [comment]
Should be fixed as these have been moved into queues and now show "loading" icons for migration instead of just waiting until finished
