### ISSUE TITLE
Copy to Clipboard button is missing when SSH is enabled, HTTP is disabled.

### ISSUE THREAD

**Issue by awwong1** [go-gitea/gitea#3771]
- Gitea version (or commit ref): 1.4.0
- Git version: 2.1.4
- Operating system: Raspbian `Linux raspberrypi 4.9.35-v7+ #1014 SMP Fri Jun 30 14:47:43 BST 2017 armv7l GNU/Linux`
- Database (use `[x]`):
  - [x] MySQL
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Not relevant

## Description

Copy to Clipboard button is missing when SSH is enabled, HTTP is disabled.

This can be toggled by setting `custom/conf/app.ini`
```ini
[repository]
DISABLE_HTTP_GIT = false

DISABLE_HTTP_GIT = true #this should also show the copy to clipboard button
```

Expected fuctionality is Copy to Clipboard button stays no matter what this setting is.

## Screenshots

When SSH and HTTPS are both enabled:
![screen shot 2018-04-08 at 10 11 03 pm](https://user-images.githubusercontent.com/2760111/38479004-c3185dd2-3b79-11e8-8177-660b5777c343.png)

When only SSH is enabled:
![screen shot 2018-04-08 at 10 11 36 pm](https://user-images.githubusercontent.com/2760111/38479026-e09de502-3b79-11e8-85d8-1b721d729962.png)

**Comment by appleboy** [comment]
fix in https://github.com/go-gitea/gitea/pull/3773

**Comment by lunny** [comment]
@appleboy please send a backport to v1.4.1

**Comment by appleboy** [comment]
@lunny See https://github.com/go-gitea/gitea/pull/3774
