### ISSUE TITLE
About ssh clone/push/pull question?

### ISSUE THREAD

**Issue by yadgen** [go-gitea/gitea#3775]
- Gitea version (or commit ref): 1.4.0
- Git version: 2.17.0
- Operating system: CentOS7
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description
The following link, I met the same problem with this user. How can I solve it?
https://discourse.gitea.io/t/solved-ssh-cloning-times-out/195

**Comment by sbrl** [comment]
Looks like that issue was solved on the discourse, @yadgen. Perhaps you could close this issue now?
