### ISSUE TITLE
Cant delete a realease without deleting a tag

### ISSUE THREAD

**Issue by couling** [go-gitea/gitea#378]
There is a strong connection between tags and releases in Gitea.  When you create a release gitea also creates a tag if the tag name doesn't already exist.  When you delete a release it also deletes the tag.

This has two main flaws:
- It's easy to create a tag when you intended to reuse one (or visa versa).
- It's impossible to delete a release without deleting the tag.

Suggested enhancements to resolve this:

- Option to *not* delete a tag while deleting release
- Indication on create release screen to show when an existing tag is being used
- Link from releases screen to change a regular tag into a release

**Comment by bkcsoft** [comment]
@tboerger more of a feature/enhancement right?

**Comment by tboerger** [comment]
@bkcsoft bug and feature at the same time, at least in my opinion.

**Comment by lunny** [comment]
So we can simply don't delete the tag when deleting a release! Tags could be delete via git or Gitea API, so that we could not provide ui to delete it currently.
