### ISSUE TITLE
Members removed from team/repository keep watches

### ISSUE THREAD

**Issue by michaelkuhn** [go-gitea/gitea#3782]
- Gitea version (or commit ref): 38a9cda
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes: https://try.gitea.io/7tl9ebtg7mio/test

## Description

When removing members from a team, they lose access to the respective repositories but keep their watches on the repository. This allows them to receive notifications via e-mail even if they should not be able to access the repository.

Reproducer (see link above): I added lunny to the test team, gave the team access to the repository and then removed lunny again. He still has a watch on the repository.

**Comment by mqudsi** [comment]
This should be tagged with a security label and perhaps assigned a CVE.

**Comment by lunny** [comment]
@mqudsi it will only show the wrong watch but there is no wrong permission.

**Comment by mqudsi** [comment]
@lunny thanks, that's much better :)

**Comment by axifive** [comment]
Perhaps need to add security or priority label?

**Comment by daviian** [comment]
Just wanted to mention that I'm already working on it. Including https://github.com/go-gitea/gitea/issues/3343 and https://github.com/go-gitea/gitea/issues/4149, because it's closely related

**Comment by techknowlogick** [comment]
Closed with #4201
