### ISSUE TITLE
Can not use drone when close the registration?

### ISSUE THREAD

**Issue by ilaziness** [go-gitea/gitea#3785]
drone login error mesage:
```shell
"cannot register xxx. registration closed
```

**Comment by mxmehl** [comment]
Please provide some more information. What registration did you close, Gitea's or Drone's? Please show the config for both.

I assume you have closed Drone's registration. Probably you don't have `DRONE_OPEN = true` or didn't set/created an admin on Drone.

Anyway, I really think this is an issue with your Drone settings and doesn't belong here.

**Comment by ilaziness** [comment]
@mxmehl thinks. I closed gitea‘s and drone's registration.I thought it was gitea's fault,because drone authenticate users through the gitea.
