### ISSUE TITLE
Pushes via deployment write keys do not trigger reindex

### ISSUE THREAD

**Issue by mqudsi** [go-gitea/gitea#3795]
- Gitea version (or commit ref): `38a9cda`
- Git version: n/a
- Operating system: n/a
- Database (use `[x]`): n/a
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes: https://try.gitea.io/mqudsi/test-deploy
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

It seems pushes to repos with rw deployment keys do not trigger a reindex of the repo or the "commit" event.

1. Create repo
2. Add deployment key with write access
3. Push to repo with deployment key
4. webui does not reflect changes, repo continues to show as if new

Reproduced on try.gitea: https://try.gitea.io/mqudsi/test-deploy
That repo *appears* blank, but it has content.

**Comment by lunny** [comment]
@bjoe2k4 need more investigation.

**Comment by mqudsi** [comment]
Not regular ssh key push, pushing with rw-enabled deployment keys.

**Comment by zeripath** [comment]
Yep, taking a look at gitea cmd/serv.go the environment settings aren't properly set.

**Comment by zeripath** [comment]
I've pushed a branch to github but not opened a PR just yet until I've had a chance to test it

**Comment by lunny** [comment]
@mqudsi maybe you can confirm that #5935 fix this issue.

**Comment by dakira** [comment]
@lunny I can confirm this fixes the issue.
