### ISSUE TITLE
Wiki toolbar icons missing on iOS

### ISSUE THREAD

**Issue by andysh-uk** [go-gitea/gitea#3797]
- Gitea version (or commit ref): 1.4.0 release
- Git version: 2.11
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description

On mobile Safari (iOS 11.2 & 11.3) not all the wiki toolbar icons don’t show up. Works fine on desktop (Firefox).

This used to occur on Gitea 1.3 also. 

I couldn’t see an existing ticket for this, and it only seems to occur on my server (Gitea is reverse proxied by Apache 2.4 using HTTPS.)

## Screenshots

![f47333ba-1e3e-4770-a21a-4cebe4b62fb1](https://user-images.githubusercontent.com/12907944/38773239-9d531ca4-4015-11e8-9cdd-5be0156eb465.jpeg)

**Comment by jonasfranz** [comment]
cannot reproduce that at try.gitea.io

**Comment by lafriks** [comment]
seems to be browser if blocking font files for some reason. Check in browser development tools is there are any error.

**Comment by andysh-uk** [comment]
It turned out it was mod_pagespeed that was enabled globally in Apache.

Adding “ModPagespeed off” to my Gitea virtual host resolves this.
