### ISSUE TITLE
 Landing and withdrawal problem ,WEB refresh

### ISSUE THREAD

**Issue by nopost** [go-gitea/gitea#3801]
- Gitea version (or commit ref):1.4.0dev
- Git version:1.8.3
- Operating system:centos 7.4
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

———————— Chinese original text ————
问题1：登陆退出问题
nginx反向代理。用户在WEB界面执行退出操作，要几次之后才能真正退出。
问题2:用户资料修改问题
管理用户。设置导入本地库权限。不管怎么改，前面的勾都是不勾选的，查了数据库是已该过的
问题3:后端提交，前台web不刷新
#2898 一样的问题

==================================
————————————MT———————————
Question 1 : Landing and withdrawal problem 
Nginx reverse proxy. Users can perform exit operations on the WEB interface only after several times. 
Question 2 : User data modification 
Manage the user. Set the local library permissions to import. No matter how to change, the front hook is unchecked. The database is checked. 
Question 3: Backend submission, front desk web does not refresh 
#2898 The same problem 

=================================

———————— Chinese original text ———————
故障重现：
官网https://try.gitea.io/nopost/nopost。
新建的库。后面push了3次，前台依然没刷新。。...

————————————MT———————————

Fault recurrence ：
The official network https://try.gitea.io/nopost/nopost.
The new library. After push 3 times, the front desk is still not refreshed. ...

Operation steps（操作步骤）:

git clone https://try.gitea.io/nopost/nopost.git
touch README.md
git add README.md
git commit -m "first commit"
git push -u origin master

touch README.md1
git add README.md1
git commit -m "first commit2"
git push origin master

touch README.md2
git add README.md2
git commit -m 'xx'
git push origin master

## Screenshots

[root@VM_60_3_centos home]# cat /proc/mounts
rootfs / rootfs rw 0 0
sysfs /sys sysfs rw,relatime 0 0
proc /proc proc rw,relatime 0 0
devtmpfs /dev devtmpfs rw,nosuid,size=498596k,nr_inodes=124649,mode=755 0 0
securityfs /sys/kernel/security securityfs rw,nosuid,nodev,noexec,relatime 0 0
tmpfs /dev/shm tmpfs rw,nosuid,nodev 0 0
devpts /dev/pts devpts rw,relatime,gid=5,mode=620,ptmxmode=000 0 0
tmpfs /run tmpfs rw,nosuid,nodev,mode=755 0 0
tmpfs /sys/fs/cgroup tmpfs ro,nosuid,nodev,noexec,mode=755 0 0
cgroup /sys/fs/cgroup/systemd cgroup rw,nosuid,nodev,noexec,relatime,xattr,relea                                                                                                                                                             se_agent=/usr/lib/systemd/systemd-cgroups-agent,name=systemd 0 0
pstore /sys/fs/pstore pstore rw,nosuid,nodev,noexec,relatime 0 0
cgroup /sys/fs/cgroup/pids cgroup rw,nosuid,nodev,noexec,relatime,pids 0 0
cgroup /sys/fs/cgroup/net_cls,net_prio cgroup rw,nosuid,nodev,noexec,relatime,ne                                                                                                                                                             t_prio,net_cls 0 0
cgroup /sys/fs/cgroup/devices cgroup rw,nosuid,nodev,noexec,relatime,devices 0 0
cgroup /sys/fs/cgroup/freezer cgroup rw,nosuid,nodev,noexec,relatime,freezer 0 0
cgroup /sys/fs/cgroup/hugetlb cgroup rw,nosuid,nodev,noexec,relatime,hugetlb 0 0
cgroup /sys/fs/cgroup/cpu,cpuacct cgroup rw,nosuid,nodev,noexec,relatime,cpuacct                                                                                                                                                             ,cpu 0 0
cgroup /sys/fs/cgroup/blkio cgroup rw,nosuid,nodev,noexec,relatime,blkio 0 0
cgroup /sys/fs/cgroup/cpuset cgroup rw,nosuid,nodev,noexec,relatime,cpuset 0 0
cgroup /sys/fs/cgroup/perf_event cgroup rw,nosuid,nodev,noexec,relatime,perf_eve                                                                                                                                                             nt 0 0
cgroup /sys/fs/cgroup/memory cgroup rw,nosuid,nodev,noexec,relatime,memory 0 0
configfs /sys/kernel/config configfs rw,relatime 0 0
/dev/vda1 / ext3 rw,noatime,data=ordered 0 0
systemd-1 /proc/sys/fs/binfmt_misc autofs rw,relatime,fd=30,pgrp=1,timeout=0,min                                                                                                                                                             proto=5,maxproto=5,direct,pipe_ino=9705 0 0
mqueue /dev/mqueue mqueue rw,relatime 0 0
hugetlbfs /dev/hugepages hugetlbfs rw,relatime 0 0
debugfs /sys/kernel/debug debugfs rw,relatime 0 0
tmpfs /run/user/0 tmpfs rw,nosuid,nodev,relatime,size=101624k,mode=700 0 0
[root@VM_60_3_centos home]#
login as: root
Authenticating with public key "imported-openssh-key"
Last login: Sun Apr 15 22:45:37 2018 from 10.154.134.52
[root@VM_60_3_centos ~]# service gitea restart
Redirecting to /bin/systemctl restart gitea.service
[root@VM_60_3_centos ~]#

PS：真心不会英语。。。翻译怕影响描述。机器翻译不是很靠谱！
 PS: I really can't speak English. Translation is afraid of affecting the description. Machine Translation is not very reliable!

**Comment by jonasfranz** [comment]
Please submit your issue at English since the most developers/useres cannot read chinese (or whatever language you wrote)

**Comment by nopost** [comment]
ok。 I'm under Machine TrI'm under Machine Translation. I'm afraid of the inaccuracy of Machine Translationanslation.
