### ISSUE TITLE
Error upgrading 1.0.1 to 1.4.0

### ISSUE THREAD

**Issue by Datapole** [go-gitea/gitea#3803]
- Gitea version (or commit ref): 1.4.0
- Git version: 2.7.4
- Operating system: Ubuntu server 16.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:
2018/04/16 16:51:47 [...routers/user/home.go:61 retrieveFeeds()] [E] GetFeeds: Error 1054: Unknown column 'act_user_name' in 'field list'
2018/04/16 16:51:47 [D] Template: status/500
## Description
Hello, when upgrading from 1.0.1 to 1.4.0, we have issues: the home page does not work (error 500), and the log shows unknown columns in the database. In your migration process, we never see any database update operation or file. We just replaced the gitea binary file as told in your process (https://docs.gitea.io/en-us/upgrade-from-gogs/), but I guess we have to make changes in the database, right?
How can we make these changes?

Thanks

...

**Comment by lunny** [comment]
Did you upgrade from Gogs or Gitea v1.0.1?

**Comment by Datapole** [comment]
Hello, thanks for your quick reply. We first had Gogs, and then migrated to Gitea 1.0.1 more than one year ago.
This issue, as mentioned in the title, is about migrating from Gitea 1.0.1 to 1.4.0.

**Comment by Datapole** [comment]
As the update from 1.0.1 to 1.4.0 was not working, we put the old 1.0.1 binary back on the server, and did not change the database. We are now unable to push modifications on any repository. In the logs of Gitea, we can see each time we try to push something: `[T] No update task is presented: 4bd2ecbe-048d-468f-b644-c3217f9489f2` (`4bd2ecbe-048d-468f-b644-c3217f9489f2` is changing every time).

Could you please help with this too, please?
Thank you

**Comment by daviian** [comment]
Migration is done on startup of the binary. It checks your database schema version and performs migration steps as needed.

If you are going back to old binary v1.0.1 you should also restore your database.

**Comment by Datapole** [comment]
Hi, yes we did restore back our database afterwards, and it still makes the same error.

**Comment by lafriks** [comment]
It is safer to do 1.0.x -> 1.2.x -> 1.3.x -> 1.4.x upgrade

**Comment by sondr3** [comment]
Isn't that something that should be displayed as a warning on the upgrade page? I do feel that you should be able to upgrade from 1.0.x to the latest stable release and not expect anything to break.

**Comment by TangentFoxy** [comment]
Does Gitea use Semantic Versioning?

**Comment by lunny** [comment]
@Guard13007 I think yes.

**Comment by lunny** [comment]
@lafriks I think @sondr3 is right. Maybe we could deny upgrade from 1.0.x -> 1.4.x by dbversion check.

**Comment by Datapole** [comment]
@lafriks If you are right, it should be written in the upgrade docs. (Maybe it is, but I did not find it)
