### ISSUE TITLE
Dashboard shows error 404

### ISSUE THREAD

**Issue by rrrnld** [go-gitea/gitea#3809]
- Gitea version (or commit ref): 1.3.2
- Git version: 2.16.2
- Operating system: CentOS Linux release 7.4.1708 (Core)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL (MariaDB)
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

https://gist.github.com/heyarne/4147166b4326063029f71617fa58f943

## Description

I've set up gitea and successfully creating a test repository (including an issue and a file upload to verify that general usage works ok. My dashboard continues to show me a 404 error. Is this normal? I have configured gitea to listen to a high port and be exposed via a reverse proxy that provides access on port 443. Relevant config:

```
[server]
LOCAL_ROOT_URL   = http://localhost:64625/
SSH_DOMAIN       = my.domain.name
DOMAIN           = my.domain.name
HTTP_PORT        = 64625
ROOT_URL         = https://my.domain.name/
DISABLE_SSH      = false
SSH_PORT         = 22
```

Any idea what causes this? Or is this intended?

## Screenshots

![screenshot-2018-4-17 gitea git with a cup of tea](https://user-images.githubusercontent.com/525780/38890604-2d7c7bd6-4282-11e8-9733-3cf8aaa990d2.png)

**Comment by lafriks** [comment]
Can you please try to reproduce that on latest 1.4.0 version?

**Comment by rrrnld** [comment]
Still the same behavior unfortunately. I will try and set it up on another server and close the issue if it doesn't persist.

**Comment by lafriks** [comment]
You have probably set nginx in front that tries to send index.html request to gitea. I had such bad configuration once for myself.
