### ISSUE TITLE
Email notification for new pull request is undistinguishable from that for a new issue 

### ISSUE THREAD

**Issue by strk** [go-gitea/gitea#381]
See https://github.com/gogits/gogs/issues/3305

**Comment by lunny** [comment]
I think this have been resolved via 6f9a95f83. Please feel free to reopen it.

**Comment by strk** [comment]
I don't see anything related to mail notification body in that commit. Can we test this on try.gitea.io ? (ie: enable mail notification there, with email confirmation)

**Comment by lunny** [comment]
I have tested locally.
see https://github.com/go-gitea/gitea/commit/6f9a95f83020e215ebe3942bd541da34791dd043#diff-d5eea3b2c0d4c92d62e12b34eb8da2c0R158
and 
https://github.com/go-gitea/gitea/commit/6f9a95f83020e215ebe3942bd541da34791dd043#diff-91afb18937651f768645eff6cf5779a8R157

**Comment by strk** [comment]
But mail subject remains the same ?

**Comment by lunny** [comment]
Yes. Your issue only said the link is not correct.

**Comment by strk** [comment]
The original report saied: "It *even has the wrong link", so was just an extreme :)
You can see an example github PR notification here: https://github.com/gogits/gogs/issues/3305#issuecomment-234873593

Anyway, no problem closing this now, will reopen next time I face the issue (after I upgrade to Gitea, which I didn't do yet)

**Comment by tboerger** [comment]
> I don't see anything related to mail notification body in that commit. Can we test this on try.gitea.io ? (ie: enable mail notification there, with email confirmation)

Enabled now.
