### ISSUE TITLE
allow PullsAllowMerge/PullsAllowRebase to be enabled via configuration

### ISSUE THREAD

**Issue by jstrachan** [go-gitea/gitea#3813]
I wonder if we could add a configuration so that we can enable the flags `PullsAllowMerge/PullsAllowRebase` OOTB on all newly created repositories? 

Then whether we create new repositories via the web UI or REST API they could come with some of these boxes enabled? 

Otherwise its painful; folks have to go into the web UI and tweak newly created repos if they want them to work with PRs:
<img width="485" alt="repo-config" src="https://user-images.githubusercontent.com/30140/38024621-7fe90278-327d-11e8-85b3-6f59a272aeba.png">

I originally raised this as an issue against the REST API - but it turns out there isn't a REST API I can see to configure the repository options and this issue affects repos created via the web UI too
https://github.com/go-gitea/go-sdk/issues/100

**Comment by adelowo** [comment]
This is enabled by default this days I believe

**Comment by jstrachan** [comment]
@adelowo ah awesome thanks!

**Comment by apricote** [comment]
For reference, all merge styles are enabled for new repos here https://github.com/go-gitea/gitea/blob/master/models/repo.go#L1311
