### ISSUE TITLE
How can I update gitea?

### ISSUE THREAD

**Issue by san127127** [go-gitea/gitea#3817]
I updated my gitea from 1.3.2 to 1.4.0 by replacing "gitea-1.3.2-windows-4.0-386.exe" by "gitea-1.4.0-windows-4.0-386.exe".

After doing this, I can't push anything onto the server. When I try to push, I got this line on command line "remote: ./hooks/pre-receive.d/gitea: line 2: D:/Version Control/Gitea/gitea-1.3.2-windows-4.0-386.exe: No such file or directory" because those hooks contains a path to the old gitea exe.

It seems there is no migration guide for this. How can I update gitea? Am I supposed to update those hooks one by one manually?

**Comment by lafriks** [comment]
It is recommended to use more generic name like `gitea.exe` (just rename after download) to not have such issues.

In admin options (`https://<your-domain>/admin`) there is option (`Resync pre-receive, update and post-receive hooks of all repositories.`) to rewrite all hooks with new path:
![image](https://user-images.githubusercontent.com/165205/38973678-c09248e6-43af-11e8-9fdf-2e19f80cc3dc.png)

**Comment by san127127** [comment]
Thanks, I will try this tomorrow.
I don't think I am the only one having this problem, maybe this is worth mentioning in docs.

**Comment by lafriks** [comment]
Yes we would need some help on docs, so if you can submit PR for that it would be great

**Comment by techknowlogick** [comment]
@csleead I'm closing this ticket now, but feel free to re-open if needed.
