### ISSUE TITLE
Issues filtering by label

### ISSUE THREAD

**Issue by nferrari** [go-gitea/gitea#3819]
- Gitea version (or commit ref): 1.4
- Git version: 2.14.1
- Operating system: Debian
- Database:
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] [Yes](https://try.gitea.io/issues?q=&type=all&state=open&labels=1383&milestone=&assignee=)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

On the global Issues screen (not the one inside a repo), filtering on a label (by clicking on it), does NOT filter the issues list.

And more globally, wouldn't it be nice to have similar list page here and on the Issues tab page of a repo? Just asking.

Thank you!

**Comment by nferrari** [comment]
To be more specific: it is also not possible to see all issues assigned to a team member globally, while it's possible on a specific repo.

**Comment by rvillablanca** [comment]
I have checked this bug in my own gitea and try.gitea.io. The only problem I see is in the main issues screen there are many tags with same name and color, `bug` for example, but they have differents id between different repos so if you select the `bug` tag, then you will get only issues for that repo, not for all.

**Comment by nferrari** [comment]
I'm sorry, I checked twice to be sure and I can confirm the bug about filtering on labels. 

I've made my own simple repo, with 2 different issues, having each a single label. On the main issues screen, clicking on a label does NOT filter on this label: both issues stays in the list while the label id can be seen on the URL.

**Comment by techknowlogick** [comment]
Closed with referenced PRs
