### ISSUE TITLE
Change "company name" in installation

### ISSUE THREAD

**Issue by kolaente** [go-gitea/gitea#3828]
IMHO we shouldn't use the term "Company name" here, as we don't primarily target companies.

![bildschirmfoto von 2018-04-21 15-31-03](https://user-images.githubusercontent.com/13721712/39084648-282bcda4-4579-11e8-92aa-7de0e2fd8f2d.png)

**Comment by lafriks** [comment]
Why not, small company is also company ;)

**Comment by lunny** [comment]
We can use organization install company since the customer maybe a person, a company or an organization and etc.

**Comment by kolaente** [comment]
> Why not, small company is also company ;)

@lafriks Sure, but we're talking about the _site title_ here, not a field called "Company Name".
I for example don't have a company, but still use Gitea to host all my personal projects. I simply think the term "Company Name" is a bit misleading here.

> we should probably write "You can enter your company name here." so that it doesn't sound like it always has to be a company name.

This sounds like a good idea to me.

**Comment by techknowlogick** [comment]
Just created #3935 which updates text to suggested text
