### ISSUE TITLE
Simpler UX for OAuth2 login with GitHub

### ISSUE THREAD

**Issue by coolaj86** [go-gitea/gitea#3837]
UX Review: Current Behavior
=====

[![](https://i.imgur.com/zmPcRiU.png)](https://youtu.be/xeWG-tjIkj8)

Long Read
====

I have enabled OAuth2 for GitHub

I’ve also changed my theme so that Login with GitHub is prominent.

When a user clicks to Login with GitHub (or any OAuth2 provider) for the first time, they are dropped at a screen that asks them to login or create an account.

I’ve watched people then attempt to sign in using their GitHub username and password because it isn’t clear to them that they’re continuing an account creation process.

I think that this could be simplified if the Login / Create Account page were laid out side-by-side, or if the order were reversed.

Better yet, have them enter their email or login, then click “next” and then, based on whether or not that account exists, present them with the appropriate “login” or “create account” screen.

I’m going to try and get some help from a friend of mine who does frontend to modify the theme and provide a suggestion and potentially a pull request.

Templates for Reference
=====

* <https://github.com/go-gitea/gitea/blob/master/templates/user/auth/link_account.tmpl>
* <https://github.com/go-gitea/gitea/blob/master/templates/user/auth/signin_inner.tmpl>
* <https://github.com/go-gitea/gitea/blob/master/templates/user/auth/signup_inner.tmpl>

Potential Conflicts
=====

The "inner" templates are also used on these pages:

* <https://github.com/go-gitea/gitea/blob/master/templates/user/auth/signin.tmpl>
  * See https://try.gitea.io/user/login
* <https://github.com/go-gitea/gitea/blob/master/templates/user/auth/signup.tmpl>
  * See https://try.gitea.io/user/sign_up

**Comment by coolaj86** [comment]
For reference, this is the screen that has confused several people:

![screen shot 2018-05-11 at 3 35 34 pm](https://user-images.githubusercontent.com/122831/39947962-1e1522c6-5531-11e8-9352-f89d3885a731.png)

**Comment by lafriks** [comment]
Any suggestions what to change?

**Comment by coolaj86** [comment]
I'll post back with another screenshot once I modify the template.

Although it'll be quick to modify the template as an interim solution, I think the best solution will be to change the flow - similar to what Google, Slack, and others do:

* 1a. Let the user know that they were successful: **Thanks for signing in with [[sso provider]], [[username]].**
* 1b. Ask the user for their email address: "Please input your email address:"
* 1c. The user clicks "Next".
* 2a. On submit check if the user exists or not, then display the appropriate options:
* 2*. (some claim this is a security vulnerability, but that's bogus as you can test for the existence of the user in many ways and the the user isn't private anyway)
* 2b. Ask the user for their password depending on whether or not they exist in the system
  * "Please enter your [[sitename]] password" (as to avoid confusion with their [[sso provider]] password). 
  * "Please create a password for [[sitename]]" (or, for security, let people disable passwords for security and set up 2FA instead - such as "QR Code" or "Magic Link"). Also display the captcha.
  * Or "Enter or create your password" if the "security" measure of not being able to probe an account name is being held to, and only show the capcha afterwards
* 2c. The user clicks "login" or "create account"

**Comment by larshp** [comment]
Suggest not asking the user for setting a recovery password. If signing in with GitHub, I guess GitHub is responsible for the recovery process if needed?

OAuth is a great way to get rid of passwords for smaller sites.

**Comment by coolaj86** [comment]
@larshp The problem is that github routinely goes down from DDOS attacks.

That's one of the benefits of using a self-hosted git solution.

What we really need is federated authentication, but that doesn't exist yet. There's no financial incentive for a large company to develop an open protocol (i.e. email) that a competitor could use. Instead, protocols with built to preserve vendor lock-in (like OAuth2) ensure their creator's survival (i.e. Facebook). Then there are some valiant efforts from non-profits like Mozilla, but the solutions that they come up with are too politically charged (i.e. ads are evil, non-anonymity is evil, etc - more about why it's politically morally superior than the benefit to the user) and/or geeky (requiring manual steps, like OpenID) to make it into mainstream.

**Comment by aaronpk** [comment]
> What we really need is federated authentication, but that doesn't exist yet. 

This sounds like a great use case for IndieAuth. https://www.w3.org/TR/indieauth/

IndieAuth is an OAuth 2.0 extension, which avoids the centralized problems with existing OAuth solutions by using DNS for "registration" of client IDs and user IDs. Every user account is identified by a URL (for Gitea this could be your Gitea user page), and client IDs are also URLs (would be the Gitea instance home page in this case.) 

To log in to your Gitea instance, I would enter my own Gitea profile URL. Your instance would then do discovery on my URL to find where to send me to authorize the login on my own OAuth server (my Gitea server), which would then send me back to your Gitea where it would be able to verify the authorization code against my Gitea instance.

I'd be happy to walk through this in more detail if you're interested!

**Comment by tantek** [comment]
I think IndieAuth makes a lot of sense as the way to implement a federated login protocol to provide a "simpler UX for OAuth2" login for Gitea as this issue is named.

It would also be possible to provide support for the "with GitHub" portion (as originally noted in the issue) without having to ask / wait for GitHub to implement IndieAuth, by adding https://indieweb.org/RelMeAuth support.

https://indielogin.com/ is an example of an open source service that supports both of those, IndieAuth as @aaronpk suggested and RelMeAuth, and is in daily use by folks signing-into the IndieWeb.org site.

(Originally published at: http://tantek.com/2018/155/t1/)

**Comment by clarfonthey** [comment]
I ran into this today and I find it very confusing that oauth requires users to type in a password and captcha for their account. Additionally, clicking the "sign in with ___" button makes it unclear whether I'm going to have the option of linking with an existing account.

IMHO, we should be able to disable captcha and password requirements for oauth-created accounts, so that you can have an empty password need be. It might also be beneficial to allow clearing passwords if you use oauth, so that you really don't have a password managed by your gitea account, and just from this external provider.

**Comment by ghost** [comment]
@coolaj86 how would you describe IndieAuth to your friend?

**Comment by aaronpk** [comment]
Here's a post I just wrote explaining IndieAuth and how it solves a number of the challenges with OAuth in this context. 

https://aaronparecki.com/2018/07/07/7/oauth-for-the-open-web

**Comment by coolaj86** [comment]
@jhabdas I wouldn't.

Total tangent, but here goes...

All Authentication Sucks
======

For years I've been working on a protocol I call OAuth3 (but I'd like to come up with a better name). It's like a peer version of OIDC or a convenient version of IndieAuth.

However, there have been a number of roadblocks and challenges. Having something work peer-to-peer (decentralized) and be convenient, is neigh unto impossible (but it is possible).

The problem with all existing auth solutions is that they're in one of two camps: Proprietary/Centralized (OAuth2 implementations) or complicated for a non-technical user OpenID/IndieAuth.

What Could Succeed
======

The way I believe that peer authentication will succeed is by providing a solution that primarily executes on the client device (keypair authentication) but, by default, syncs the public keys to a shared server (with a centralized well-known server as the default), and uses a static page (or 3rd party app if on a phone) - no server APIs required to function - in essentially the way a browser plugin (or native Facebook/Google OAuth on phones) works to manage the exchanges.

Ultimately, browsers need to adopt such a protocol, but it most be open and compatible between browsers. The same is true for smart phones. Until then, the centralized server would serve as a "broker" to serve the user's preferences to other client-side apps.

Most importantly, people need to be able to login like they're used to. It must be *easier* than the current solutions, not more difficult (and how better to make it easier than by removing the most frustrating - and least secure - part of login: passwords).

What it might look like
======

### *First Login on a Device*

1. I click "Login"
2. A pop-up to "generic-auth.org" opens up (better branding, but you get the idea)
3. The user types in their email address (or domain name)
4. The part after the '@' (if email) is checked for  a `/.well-known/peer-auth/index.json` 
  * on 200 OK, redirect to that with `?subject={email}` for the next step and save the user's choice
  * on 404 continue using generic-auth.org
5. I get a push notification on my device (or an email with a "magic link")
  * also, generic-auth.org could link to facebook, twitter, google, etc (though a true peer-auth site could not as that would require having a developer account)
6. I click the link in email (or the "Allow" option on the push notification) and I'm logged in (or, if using 2FA), I put in a passphrase or totp code
7. I accept any grants (email address, photo access, etc) as needed
8. I'm now logged in
  * The static app on generic-auth.com (or my custom auth site) caches that this site is allowed login

### *Secondary Login on Device*
1. Behind the scenes the app loads a hidden iframe or postmessage to generic-auth.org
2. The app is either told to use generic-auth.org, or the peer auth the user supplied before
3. The app is given a pseudonymous pairwise identifier and short-expiry token without any interaction
4. The user is simply "logged in" with 0 interaction
5. The app silently renews the token (completely client-side, no server implementation), as needed
6. If necessary, a grants dialog appears asking for my email address, photo access, etc

### *Logout*
1. When the user clicks "log out" in any web app (or app) that is passed via iframe or postmessage to the client-side and all private keys are deleted.
2. This means that client-side tokens cannot be renewed (as they were securely generated with client-side private keys)
3. Likewise an iframe or postmessage is opened for each of the list of sites which have been granted a token, causing their short-lived tokens to expire immediatley
4. The generic-auth.org server (or the peer auth server) are notified that they may remove "Chrome on Jon's Macbook Pro" (or whatever) and its public keys from the list of authenticated devices.

### *Security*
* No cookies, only tokens
* Client-side token generation
* Short-lived tokens
* Optional (but default) sync of public tokens and of grants per app/site
* Only Facebook has a properly secure login that could feasibly be used on its own as-is
  * Twitter, Google, etc do not support PPIDs and are therefore insecure by default and cannot provide any information that could be used for encryption, etc, as all of the ids are shared among all apps/sites

But That's not a PERFECT Solution!
======

If you're on one side of a chasm and you want to migrate a host of people to the other side, you need a bridge. Something like generic-auth.org (in the hypothetical scenario above) acts as that bridge. The migration would be complete when browsers and phones natively support open-protocol peer-based authentication that doesn't require 3rd party apps to bridge the gap anymore (like how Chrome has proprietary Google auth implemented).

Until that time you have the problem of OpenID/IndieAuth if you go for the "Perfect" peer solution - it requires too much knowledge and effort to intentionally use it. My mom is unlikely to create a website and link it to her other accounts with HTML tags.

The truly "perfect" solution then is the solution that people who don't care about technology and who don't understand the risks with their current login and authentication setups will adopt out of convenience, and perhaps a sense of individuality or pride, but certainly not for being the most technically correct solution.

The Catch-22
====

Peer-to-Peer can either be convenient for end-users or convenient to develop. It simply can't be both.

The saving grace is that if it's implemented in JavaScript and used in native apps through a web view, we only need a single implementation for the client-side and only 3 to 5 APIs for the server side (sync public keys, send email / push notifications, sync pairwise grants) - none of which require knowing anything about security or keypair signing and encryption - just opaque files, simple messages, and plain-old JSON.

**Comment by coolaj86** [comment]
@aaronpk Perhaps I misunderstood and need to read carefully. Perusing https://indieauth.com/ what I got was "This is a reboot of OpenID that requires you to create a webpage and link to it".

Perhaps that's not at all related to "IndieAuth" that we're talking about here (I didn't read your article yet, but I will now).

**Comment by aaronpk** [comment]
Yeah sorry for the confusion. I've started the (very slow) process of shutting down `indieauth.com` because I never should have launched a service with the same name as the spec. That site is not a good representation of the concepts behind IndieAuth.

Please do check out the blog post, it does a much better job of explaining the actual goals and motivations of the spec.

**Comment by pkit** [comment]
I'm not sure what's going on here.
But current flow cannot be called SSO or "OpenID Connect support" by any margin.
The whole point in Oauth2 (OpenID) is to store all users in ONE place.
I.e. currently gitea does not support any auth other than local.

**Comment by lafriks** [comment]
@pkit local user needs to be created anyway or otherwise how would you reference/add rights etc for it if it is not saved?

**Comment by daviian** [comment]
@lafriks I think it's not necessary to create a "complete" local user. E.g. the user doesn't necessarily need a password if he gives up using https protocol.
The Oauth user is still able to use ssh and can login with his external provider.

**Comment by coolaj86** [comment]
There is no need for requesting a password to be created. It can be set to something random and later set via email reset if necessary.

This is what needs to be communicated:

```
This is your first time signing in as `foouser` via `github.com`, but `foouser` does not exist here.

Would you like to

* Create a new account `foouser`?
* Link your `github.com` account with an existing account?
```

What I think would be best, in all cases, is to ignore the password altogether and simplify to a single flow across the board:

```
[begin if oauth]
You're signed in as `foouser` via `github.com` for the first time.

We need to confirm your email address just this once so that we have a recoverable link to your account in the future.
[end if oauth]

What's your email?

Thanks, go click the confirmation link.
```

Again no password needed.

In fact, passwords only add vulnerability to a web application. Without a password a person's account can be compromised via email. With a password the account can be compromised via any number of publicly available username/password lists, and still via their email. Passwords are a weak link that corrupts any chain you put them in (unless the password is a secondary authentication  rather than a primary authentication - such as requiring it to make account changes after 15 minutes of inactivity).

**Comment by lunny** [comment]
If no password enabled, user should be denied when clone or push via http/https

**Comment by coolaj86** [comment]
@lunny that could be handled by showing the user a device code and instructing them to use `git config credential.helper store` (or by asking them to upload their ssh key right away).

Or they could create a password and be warned that a password reduces the security of their account.

However, the password issue as not as pressing or as easy to fix as the original issue that the current create account page is really confusing for people trying to login with GitHub.

**Comment by lunny** [comment]
@coolaj86 Yes, I agree with you.

**Comment by grothesque** [comment]
I tried try.gitea.io and I've noticed this issue as well: it's confusing that gitea requires one to choose a local password even when authentication is done with an external account.  (The other possibility, "linking", is, if I understand correctly, to entrust one's password at the other service with the gitea instance - this seems outright dangerous!)

On our gitlab server, we regularly get contributions (e.g. issues are opened) by people who log in with their github or google account.  Doing the same with gitea is too complicated and creates too much of a barrier for one-of-a-time contributors.

**Comment by coolaj86** [comment]
@grothesque "linking" just means that you enable multiple styles of login. People may pick the same password, but that is not the intent.

**Comment by grothesque** [comment]
@coolaj86, that's reassuring, thank you for the explaination.  Let me explain why I was confused.

When a new user signs in to try.gitea.io using a github account, a page shows up with the instructions: "Sign in with existing credentials to link your existing account to this account. Or register a new one."  Below, two boxes are visible, one with the title "sign in", the other one "register".  The first box clearly corresponds to the first option "sign in with existing credentials", and to me that meant "with existing *github* credentials", even more so because my github username was already filled-in!

Now, thanks to your explaination, I understand that "sign in" in the above case means: sign in with a previously created local gitea account and link it to the github account.  IMHO this is not at all clear to a new user.

If you ask me, the action of linking an existing gitea account should be moved to the settings section of gitea.  I also believe that the registering of a new account should be automatic with a random password, that can be changed later if necessary.

**Comment by daviian** [comment]
@grothesque 
I agree with you that OAuth login should transparently create an account and perfrom the log in as requested. However IMO setting a random password is a bad habit. Instead I prefer to disable "local" sign-in and http(s) cloning since the user doesn't know the password anyway.

A naive approach to the "account linking problem" can be to look for a local user with the same email address or username and ask the user for actions in that event.
I believe a user who performs OAuth login is either a completely new user or has forgotten about his/her existing user at all.
So my suggestions would be to remind the OAuth user that he has to set a password to be able to use http(s) cloning perhaps with a horizontal banner below navigation, include a link that directs them to password setup and local account linking.

**Comment by coolaj86** [comment]
@grothesque @daviian I've started work on this (baby steps, highest value lowest cost first):
https://github.com/go-gitea/gitea/pull/5006

**Comment by coolaj86** [comment]
Progress. Here's a screencap and video of the requested changes:

[![](https://i.imgur.com/LRldREV.png)](https://youtu.be/jM8NL4IMM5Y)

https://youtu.be/jM8NL4IMM5Y

**Comment by grothesque** [comment]
AJ ONeal wrote:

> Okay, I've got something that's ready to test (I'd say the 20% of the
> work that provides 80% of the most important solutions)

I just tested it.  It's a clear improvement, thanks!

I noticed an incosistency: During the intial sign-in process, when one
returns from github to gitea, a form is shown with the title

"Add Email and Password (for Account Recovery)"

However, the only two text fields are "username" and "email address".
Shouldn't the title be rather

"Add email address (for account recovery)"

?

**Comment by coolaj86** [comment]
@grothesque Good catch.

I made each PR independent from the other so that they could be accepted as small changes, without any merge conflicts, rather than a lump change.

Because of that, I updated the wording in one PR, but not in the other that also modified the same template.

I’ll see if I can find better wording that will apply to both equally well and add a commit for it.

**Comment by ix5** [comment]
As it currently stands, you cannot delete your account without sending a password-reset request to your backup email.
I guess this is a problem with all actions that gitea wants you to confirm with your own password. How do we solve this?

**Comment by strk** [comment]
I suggest we request confirmations by email rather than by password

**Comment by lgommans** [comment]
I too would love to see this merged! I was halfway through writing my own modifications when I found this thread and the version [mentioned earlier](https://github.com/go-gitea/gitea/issues/3837#issuecomment-427624778) seems perfect.

Any idea when the pull requests might be merged? Being able to use the releases without maintaining local patches and building from source every time there is a release would be a huge benefit in my opinion.

**Comment by solderjs** [comment]
@lgommans I'm reworking my original PR set so that it will apply against v1.9-dev.

I would love to have some help if you have a few hours. We could pair for a little bit and then split up to conquer and test. The work consists of manually going through the old PR, finding the new place where things go (as there has been some refactoring), and working it back in.

I'm open to any technology, but if you sent me and email (important) and _then_ opened a gchat / google hangouts with me, that seems to work well enough: coolaj86@gmail.com

**Comment by lgommans** [comment]
@solderjs I sent you an email ~25 minutes ago, not sure if it ended up in spam maybe? (Gmail's filters are rather aggressive)

**Comment by solderjs** [comment]
@lgommans I check my email manually because if I had notifications on my phone would be buzzing every few minutes all day long.

I'm in MST. I can't make tomorrow work because I'll asleep when you're first available and just getting out of church when you're no longer available, but I'll keep in touch and find a time that works. If I'm already done with this PR, I'm sure that there will be another to work on soon.

**Comment by solderjs** [comment]
# Testers Wanted

I've got everything rebased. It would be great if a few people other than myself could build from through this branch and identify any issues:

https://github.com/solderjs/gitea/tree/ux-master

**Comment by lgommans** [comment]
Works! Steps I took:

1. I replaced the contents of my $GOPATH/src/code.gitea.io/gitea directory with the repository above and ran `git checkout ux-master`
1. Run the regular build command
1. Install the binary on my server
1. It first didn't start, apparently it needed to be able to change the config file, so I gave it write permissions (`chmod 0600`) and it worked.
1. Then my reverse proxy couldn't reach it: I configured `0.0.0.0` as the listening address but it was listening on `[::]` only. The latest release did not have this issue. I hardcoded the v4 address of the server and that worked.
1. Added an oauth2 auth source in `https://$gitea/admin/auths/new`, for which I needed to:
1.1. [Register an application on GitHub](https://github.com/settings/developers)
1. Opened a private browser window and went to `https://$gitea/user/oauth2/GitHub?redirect_to=`. This redirected to GitHub, I logged in, clicked Authorize, and got a 500 internal server error[1]. Figuring that the site did not create a session when redirecting, I went to the homepage, then clicked sign in and continued the flow from there, and that worked.

[1] 2019/04/14 11:03:02 routers/user/auth.go:595:handleOAuth2SignIn() [E] UserSignIn: could not find a matching session for this request

So in summary:

- Not sure if it's a bug that this error[1] is possible?
- Not sure if it's a regression that it now listens on v6-only?

I'm also wondering if there is any reason the email address is still required. The purpose is account recovery, but if someone doesn't want that, we could make it an optional field and let it default (on empty submission) to something that will never exist like `<username>@nowhere.local`. Do we want to the email address being optional an option?

Thanks for all the work on this!

**Comment by solderjs** [comment]
# 500

I haven't been able to nail down the source of the 500. I also haven't been able to reliably reproduce it.  

Are you saying that you get it every time a new user signs up, even when the server hasn't been rebooted?

Are you also saying that you only get it when clicking the direct link in the url bar, but not when clicking it from the sign up page?

I'm thinking as a hack I could just have the user redirected to a special page that clicks the login button for them a second time.

I'd love help solving this.

# IPv6

I didn't make in changes in that area. `master` represents `v1.9-dev`. I listen on `localhost` and have my reverse proxy connect to that, so I haven't experienced this issue.

# Email Address

There does need to be some sort of local identifier by which accounts can be linked and to which notifications can be sent. In any case, it would be high complexity to create an account without one with the current codebase.

**Comment by lgommans** [comment]
Testing some more, I can reliably reproduce the 500 when using private navigation. The first time I go through the flow, i.e. with no cookies already set, it fails. I noticed that in the redirect to Github, it sets a cookie, `_gothic_session`, with an expiration time of right now. The browser, of course, does not return it. The second time around, it also sets that cookie, but it does return it.

The error I see in the logs appears in two places in the source code: in `vendor/github.com/markbates/goth/gothic/gothic.go` lines 302 and 311. I modified both and observed that the error is the former, on line 302, in the function `GetFromSession`.

I can't reproduce it on your system. Not sure what the difference is, but the browser just returns the gothic cookie (though your system also sets it with "Expires: 2019-04-right:this:second").

Do you have any idea?

**Comment by lunny** [comment]
@lgommans could you send a PR to upstream to fix that?

**Comment by lgommans** [comment]
@lunny I don't know the code well enough to tell whether this is an issue on ghotic's side, on gitea's side, or even on my side (since soldierjs' hosted version does not have the issue). I can hardly read Go code so for me it would take hours to track this down. Someone familiar with the code can probably track down a session bug in a few minutes, at least to figure out if it's an issue in the library or in gitea.

**Comment by bendem** [comment]
Just setup gitea for internal use with our own openid provider and I was very confused by this. The point of openid for us is to remove the need for login (in fact, we would much prefer gitea not have a login form at all). What we did in our case (but is very confusing) is connect gitea to both openid and ldap while disabling registration. That way the user cannot create a local password and has to link to their ldap account. This way they are still able to update their password directly in the ldap and have it take effect in gitea.

The first connection of a new user is really confusing (after that, SSO does its magic and they never have to fill a form again).

What we would like: 
* disable login using a user that doesn't come from an external authentication source
* fetch the email from openid (no need to ask the user for their email, openid gives it to you)
* don't ask for password (again, that's the point of openid)
* the user stored is just a reference (sub field) to the openid user with the email and name cached in db to be able to send him notifications

With those points in place, the login flow on gitea's side can be entirely transparent with the user seeing exactly none of it.

**Comment by lgommans** [comment]
@bendem I think this thread is more about GitHub login integration, not sure if there is another ticket where general oauth/ldap integration/UX is more fitting or if it would fit better in a new one. (I'm not any sort of moderator by the way, just observing.)

**Comment by 6543** [comment]
with auto account create and other oauth2 improvements you now should be able to do as you propose :)
