### ISSUE TITLE
Explore does not start if the organization matches the search string

### ISSUE THREAD

**Issue by tomposmiko** [go-gitea/gitea#3838]
hi,

With latest Gitea version if I search for a string it does not match for organization.
In case I know the organization but I don't know the repository name or if I just want to browse (explore) an organization it's hard to do the work.

Actually the whole browser could be more 'fancy'.
It would be great if it was more efficient in using real estate. There is a lot of unused space less information, eg. repo size, owner could be there.
Also it would be great if it was a realtime search like how 'my repositories' works.

**Comment by tomposmiko** [comment]
Are you going to consider this request?
IMO it would make the users` life much simpler.

**Comment by lunny** [comment]
If you know some organization's full name, just visit <your gitea domain>/<organization name> .

**Comment by silkentrance** [comment]
works for me

![image](https://github.com/go-gitea/gitea/assets/6068824/d2f29af5-1b5c-431b-ba61-c00677eb331c)

![image](https://github.com/go-gitea/gitea/assets/6068824/054b4b09-2887-42ed-a754-328b987601f2)

**Comment by wxiaoguang** [comment]
Hmm ... good catch. This issue is quite old and no progress since then, maybe the search result depends on the indexer or something else but I can't tell.

So I will close this issue as complete and feel free to reopen if there is still any problem. Thank you all!
