### ISSUE TITLE
Wrong content type for orgEditTeam

### ISSUE THREAD

**Issue by nblock** [go-gitea/gitea#3843]
- Gitea version 1.3.3
- Git version: 2.11.0
- Operating system: Debian Stretch
- Database (use `[x]`):
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:

## Description
The swagger documentation for https://try.gitea.io/api/swagger#/organization/orgEditTeam specifies the content type as application/json while only form data works.

Extracted from #3600

**Comment by 6543** [comment]
@nblock I can't reproduce it!

maby you got into this trap: https://github.com/go-gitea/gitea/pull/9556

can you try it again and if it works close this issue?

**Comment by nblock** [comment]
@6543 I no longer have access to the code and tooling mentioned in the bug report. Therefore, I rather close this issue.
