### ISSUE TITLE
Markdown parsing incorrectly for video links

### ISSUE THREAD

**Issue by coolaj86** [go-gitea/gitea#3845]
Gitea version 1.4.0 

Go version 1.1.0

This snippet in the README.md should create an image that links to the YouTube video:

```
[![Free SSL with Greenlock.js](https://i.imgur.com/Y8ix6Ts.png)](https://youtu.be/e8vaR4CEZ5s)
```

Like this:

[![Free SSL with Greenlock.js](https://i.imgur.com/Y8ix6Ts.png)](https://youtu.be/e8vaR4CEZ5s)

Instead it creates an `<a>` tag with an empty string that cannot be clicked on for the YouTube video and a second link to the picture, which links to the picture itself.

Example:

https://git.coolaj86.com/coolaj86/greenlock-express.js/src/commit/dfabdd15dd04742a7af296b70ad84d674f956953/README.md

**Comment by coolaj86** [comment]
[This commit](https://git.coolaj86.com/coolaj86/greenlock-express.js/src/commit/dfabdd15dd04742a7af296b70ad84d674f956953/README.md) on my own gitea instance demonstrates that the link is parsed incorrectly.

**Comment by jhabdas** [comment]
Also not parsing `video` tags properly. See [example demo here](https://git.habd.as/comfusion/hall-of-mirrors/src/commit/398a3d9a17ae3e614f3a7fad385a5608457f9857/README.md).

**Comment by laoshaw** [comment]
Just found out this bug, it's impractical to embed any video without fixing this, as shown a pic for the video is very helpful.

**Comment by laoshaw** [comment]
@coolaj86 gitea 1.6.0 seems fixed this, I can click on the image then it jumps to youtube and starts playing.

still, if you self-host the video, you need click on the image to see the video, then click on the video to play it, it would be nice if I can play the video with one click though
