### ISSUE TITLE
[Suggestion] Make home.tmpl visible with Signin-View enabled

### ISSUE THREAD

**Issue by cht47** [go-gitea/gitea#3846]
Hello,
when you set `REQUIRE_SIGNIN_VIEW` to true, the frontpage/home is not visible, only the login form will show up. If you login your home is replaced by the dashboard. So you never see it. 

The signin view is a good feature to improve security for the code, but I would like to show a nice company logo and maybe some introduction, especially if used in intranet and internet. 

Any possibility to show the home.tmpl with signin_view enabled? Maybe beneath the login form, or the login form is only forced if you click any other link or does anyone has confidential information on home?

Cheers!

**Comment by nillith** [comment]
Why can't you just add a new opt in option instead of changing the default behavior? I upgraded from 1.1 to 1.5 now all the users,  organizations and public repositories are exposed. What can I do? Stick with 1.1?
