### ISSUE TITLE
Element alignments in layout broken

### ISSUE THREAD

**Issue by daviian** [go-gitea/gitea#3851]
- Gitea version (or commit ref): master / fb2f8dcf
- Git version: 2.15.0
- Operating system: Linux 15d03918bd01 4.14.34-v7+ #1110 SMP Mon Apr 16 15:18:51 BST 2018 armv7l Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL) https://try.gitea.io/
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

Introduced with PR https://github.com/go-gitea/gitea/pull/2750, upgrading our UI to be more responsive, the vertical alignment is broken.
See screenshots below. Guess the screenshots don't cover all glitches.

But the main menu and the stackable menu don't align with the feed on the dashboard, as it was in previous versions. Especially noticeable at the gitea logo, and avatar image of the users.

On the repository view the clone panel stands out, etc.

## Screenshots

![gitea-dashboard](https://user-images.githubusercontent.com/5477981/39318764-454dcd10-497f-11e8-8318-013ba15b1157.png)
![gitea-dashboard-mobile](https://user-images.githubusercontent.com/5477981/39318765-456b7e00-497f-11e8-99f7-0a8bc6cc8b08.png)
![gitea-repo](https://user-images.githubusercontent.com/5477981/39318766-4586f662-497f-11e8-953f-0a0a548d259f.png)
![gitea-repo-mobile](https://user-images.githubusercontent.com/5477981/39318767-45a3aabe-497f-11e8-8566-e5cd9b76207f.png)

**Comment by lunny** [comment]
Did you have custom css file?

**Comment by daviian** [comment]
No. And these are screenshots from try.gitea.org
So you should see this too.

**Comment by nsrosenqvist** [comment]
A lot of UI elements look out of alignments on mobile device screen sizes. The "code, issues, etc." menu looks broken (border only around first element). Each row for files under code are misaligned and takes up way to much vertical space.
