### ISSUE TITLE
Failed to initialize OAuth2 support: Error 1071: Specified key was too long; max key length is 767 bytes

### ISSUE THREAD

**Issue by silverwind** [go-gitea/gitea#3859]
- Gitea version (or commit ref): https://github.com/go-gitea/gitea/commit/7ea4bfc56172faf588142ee5637f35c0344f7534
- Git version: 2.17.0
- Operating system: Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant

## Description

After updating to today's master, I got the mentioned error related to commit https://github.com/go-gitea/gitea/commit/5a62eb30df3a04e76e465824f525b4ffd920b562. Database is MariaDB 10.1.32 with default character set utf8mb4. Reverting the commit fixes the error.

CC: @lafriks.

**Comment by lunny** [comment]
utf8mb4 is not supported currently

**Comment by gsantner** [comment]
happens here too. have that db since gogs, migrated to gitea and was never a problem before.

**Comment by silverwind** [comment]
Which of these should I change to support gitea? (They are all at their default)

```
localhost> show variables like '%character_set%';
+--------------------------+----------------------------+
| Variable_name            | Value                      |
+--------------------------+----------------------------+
| character_set_client     | utf8                       |
| character_set_connection | utf8                       |
| character_set_database   | utf8mb4                    |
| character_set_filesystem | binary                     |
| character_set_results    | utf8                       |
| character_set_server     | utf8mb4                    |
| character_set_system     | utf8                       |
| character_sets_dir       | /usr/share/mysql/charsets/ |
+--------------------------+----------------------------+
```

**Comment by silverwind** [comment]
Tracked the issue down to [this line](https://github.com/lafriks/xormstore/blob/3a80a383a04b29ec2e1bf61279dd948aa809335b/xormstore.go#L73) which defines a indexed `VARCHAR(400)`. Is it an option to change that to `VARCHAR(191)`? Note that my other tables use the old `utf8` charset, not sure why it's attempting to use `utf8mb4` on this table.

**Comment by silverwind** [comment]
Found a workaround from https://github.com/go-gitea/gitea/pull/3516#issuecomment-366648794:

```
innodb_file_format = Barracuda
innodb_large_prefix = 1
innodb_default_row_format = dynamic
```

In summary, mariadb < 10.2 and mysql < 5.7 don't support longer indexed colums by default. above setting apply the settings that are default on newer versions. I realize that upgrading mariadb would be the proper solution, but the [Arch package](https://www.archlinux.org/packages/extra/x86_64/mariadb/) still seems to be stuck on 10.1 and I don't want to compile it myself.

**Comment by drsect0r** [comment]
Found another workaround, create the table manually with an adjusted primary index length.

```sql
CREATE TABLE `oauth2_session` (
  `id` varchar(400) NOT NULL,
  `data` text,
  `created_unix` bigint(20) DEFAULT NULL,
  `updated_unix` bigint(20) DEFAULT NULL,
  `expires_unix` bigint(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `oauth2_session`
  ADD PRIMARY KEY (`id`(191));
COMMIT;
```

**Comment by thehowl** [comment]
Yes, it looks like I didn't add the primary key in the end :man_facepalming: You are indeed right - the maximum you can go with the 767 bytes and utf8 limit is 255 characters.
