### ISSUE TITLE
[E] Failed to initialize ORM engine: migrate: do migrate: pq: column "is_fsck_enabled" does not exist

### ISSUE THREAD

**Issue by kenny-ngo** [go-gitea/gitea#3864]
This happens during migration. 

- Gitea version (or commit ref): v1.4.0
- Git version:
- Operating system: Ubuntu
- Database (use `[x]`):
  - [ x ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite

## Description
Compiled from source then try to execute the binary. That when this happens
gitea@slave:~$ ./gitea web
2018/04/30 02:44:08 [T] AppPath: /home/gitea/gitea
2018/04/30 02:44:08 [T] AppWorkPath: /home/gitea
2018/04/30 02:44:08 [T] Custom path: /home/gitea/custom
2018/04/30 02:44:08 [T] Log path: /home/gitea/log
gitea@slave:~$ tail -10 log/gitea.log
2018/04/30 02:30:52 [I] Migration: adds comment to an action
2018/04/30 02:30:53 [I] Migration: regenerate git hooks
2018/04/30 02:30:53 [...itea/routers/init.go:60 GlobalInit()] [E] Failed to initialize ORM engine: migrate: do migrate: pq: column "is_fsck_enabled" does not exist
2018/04/30 02:44:08 [I] Log Mode: File(Info)
2018/04/30 02:44:08 [I] XORM Log Mode: File(Info)
2018/04/30 02:44:08 [I] Cache Service Enabled
2018/04/30 02:44:08 [I] Session Service Enabled
2018/04/30 02:44:08 [I] Mail Service Enabled
2018/04/30 02:44:08 [I] Migration: regenerate git hooks
2018/04/30 02:44:08 [...itea/routers/init.go:60 GlobalInit()] [E] Failed to initialize ORM engine: migrate: do migrate: pq: column "is_fsck_enabled" does not exist
gitea@slave:~$

**Comment by lafriks** [comment]
From what version were you upgrading?

**Comment by cweickhmann** [comment]
I have the same problem coming from "e90bbca" and trying to use "2fcd9b6".

- Gitea version (or commit ref): 2fcd9b6
- Git version: 2.15.2
- Operating system: Docker 18.03.1-ce, build 9ee9f40 on Ubuntu 16.04
- Database
  - [x] PostgreSQL (version: 9.6.3)
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite

`gitea=> select * from version;` returns:
```
 id | version
----+---------
  1 |      39
(1 row)
```
which seems to be a rather new version. Is it possible that at some point, migration starts, fails and leaves the database schema _saying_ it's a newer version than it actually is?

I've got a running container of an older gitea version (e90bbca), so we're not crashed here. But I don't get it, and the log entry is pretty cryptic, too.
