### ISSUE TITLE
Gitea unable to start

### ISSUE THREAD

**Issue by drsect0r** [go-gitea/gitea#3865]
- Gitea version: Docker 907f7f0a49e0
- Git version: 
- Operating system: Debian 8
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
Gitea appears to be stuck in a loop and is unable to start, displaying the messages below. Only thing related I could find is commit https://github.com/go-gitea/gitea/commit/cb87f29b76f661d9c726579067c9c64db55fd970.
```
WARNING: ca-certificates.crt does not contain exactly one certificate or CRL: skipping
2018/04/30 09:57:31 [T] AppPath: /app/gitea/gitea
2018/04/30 09:57:31 [T] AppWorkPath: /app/gitea
2018/04/30 09:57:31 [T] Custom path: /data/gitea
2018/04/30 09:57:31 [T] Log path: /data/gitea/log
WARNING: ca-certificates.crt does not contain exactly one certificate or CRL: skipping
2018/04/30 09:57:32 [T] AppPath: /app/gitea/gitea
2018/04/30 09:57:32 [T] AppWorkPath: /app/gitea
2018/04/30 09:57:32 [T] Custom path: /data/gitea
2018/04/30 09:57:32 [T] Log path: /data/gitea/log
WARNING: ca-certificates.crt does not contain exactly one certificate or CRL: skipping
2018/04/30 09:57:33 [T] AppPath: /app/gitea/gitea
2018/04/30 09:57:33 [T] AppWorkPath: /app/gitea
2018/04/30 09:57:33 [T] Custom path: /data/gitea
2018/04/30 09:57:33 [T] Log path: /data/gitea/log
WARNING: ca-certificates.crt does not contain exactly one certificate or CRL: skipping
2018/04/30 09:57:34 [T] AppPath: /app/gitea/gitea
2018/04/30 09:57:34 [T] AppWorkPath: /app/gitea
2018/04/30 09:57:34 [T] Custom path: /data/gitea
2018/04/30 09:57:34 [T] Log path: /data/gitea/log
```

**Comment by daviian** [comment]
There's already a discussion about that warning: https://github.com/gliderlabs/docker-alpine/issues/30

Guess we should implemented the workaround mentioned here https://github.com/gliderlabs/docker-alpine/issues/30#issuecomment-372020089

**Comment by pojntfx** [comment]
I have the same problem using the latest gitea docker image. Any workarounds? Tried gliderlabs/docker-alpine#30 (entered the commands into the running container from the OpenShift web console; should I do this differently?) but that did not work, still the same error. I'm using postgresql as my database.

**Comment by NoMoreNicksLeft** [comment]
I have this same problem. The linked alpine issue fix does not work for me. This loops forever.

**Comment by ivarlovlie** [comment]
probably unrelated, but this loop/error only occurs when i set `START_SSH_SERVER` to `true`

**Comment by lafriks** [comment]
That's because gitea can not bind on 22 port probably

**Comment by UtechtDustin** [comment]
@lafriks 
I also get the same output (without the warning)
```
2018/06/20 19:06:35 [T] AppPath: /opt/gitea/gitea
2018/06/20 19:06:35 [T] AppWorkPath: /opt/gitea
2018/06/20 19:06:35 [T] Custom path: /opt/gitea/custom
2018/06/20 19:06:35 [T] Log path: /opt/log
```
Gittea dont start and i got also no errors (also not in the log file).

**Comment by ptrcnull** [comment]
Still happens for me on the latest Docker image.

- Gitea version: Docker fa6ca546d614
- Database: SQLite

EDIT: nvm, fixed it. for anyone reading: check your disk space

**Comment by danst0** [comment]
Same here. Latest Docker image. app.ini is ignored.

**Comment by Marco77577** [comment]
And also here. Is there no solution?

**Comment by daknuett** [comment]
Well the last time I had to wait for the next image and it started working again.

A possible workaround is to explicitly tag the version that works, instead of using `latest`.

**Comment by zeripath** [comment]
Hmm they should always work! If they're not working you need to open an issue.

**Comment by techknowlogick** [comment]
I will lock this conversation so that any new issue can be resolved in open tickets.
