### ISSUE TITLE
do not see all the submenus

### ISSUE THREAD

**Issue by andruwa13** [go-gitea/gitea#3874]
`http://site/user/settings`

![- webakcent it 2018-05-01 13-01-33](https://user-images.githubusercontent.com/5846351/39469255-ff496238-4d3f-11e8-8271-c687763d3ef1.png)

**Comment by lunny** [comment]
This is depending your language translation and your screen resolutions.

**Comment by lafriks** [comment]
Probably we should move them to side menu as it was before...

**Comment by lunny** [comment]
@lafriks If we can resolve the mobile compatible, I think that's ok to move to left side menu.

**Comment by andruwa13** [comment]
@lunny language - Ukrainian, screen resolutions - 1280 x 800 (13')

**Comment by daviian** [comment]
@lafriks @lunny Thought there has already been an attempt to reduce number of menu items by combining related ones? And here it is: https://github.com/go-gitea/gitea/issues/2271

IMO there's a lot we can merge.

**Comment by lunny** [comment]
Yes, this issue is duplicated with #2271.
