### ISSUE TITLE
[E] Failed to initialize ORM engine: this user requires mysql native password authentication.

### ISSUE THREAD

**Issue by brian9206** [go-gitea/gitea#3876]
- Gitea version (or commit ref): 1.4
- Git version:
- Operating system: CentOS 7
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
MySQL version: 8.0

The server won't start up and the log shows the following error message:
```
[...itea/routers/init.go:60 GlobalInit()] [E] Failed to initialize ORM engine: this user requires mysql native password authentication.
```

This error is caused by the [go-sql-driver/mysql](https://github.com/go-sql-driver/mysql/blob/a8b7ed4454a6a4f98f85d3ad558cd6d97cec6959/errors.go#L24). 
It seems there is no way to set `AllowNativePasswords` in gitea config

Is there any workaround for this issue?

**Comment by lunny** [comment]
It seems gitea could add allowNativePasswords options on connstr to do that.

**Comment by brian9206** [comment]
so there is no workaround for now? my server is down because of that at the moment

**Comment by silverwind** [comment]
> there is no workaround for now?

See https://github.com/gogits/gogs/issues/5187#issuecomment-383271349
