### ISSUE TITLE
Allow to cherry-pick commit to other branch

### ISSUE THREAD

**Issue by lafriks** [go-gitea/gitea#3880]
It would allow to backport commits to other branches more easily from UI. Of course that would work only for commits that does not have conflicts with target branch

**Comment by guillep2k** [comment]
I think it would be great. Since this would be automatic, Gitea can not only sign the new PR but also certify that it's an actual cherry-pick of the original PR.

**Comment by nacho-domatix** [comment]
Is there a way to help (financially) to accelerate this? I would be glad to contribute.

**Comment by zeripath** [comment]
Unfortunately this is is unlikely to make it into 1.16 but feel free to drop me message on discord <@zeripath> or on element <@zeripath:matrix.org>, or post a message on our discord #job channel.

**Comment by lunny** [comment]
Or you can use https://www.bountysource.com/teams/gitea/issues?tracker_ids=47456670

**Comment by nacho-domatix** [comment]
I tried to contact @zeripath. Bountysource could be the way. I'm not sure how much I should offer tho. Any ideas @lunny?

**Comment by lunny** [comment]
Sorry, I don't know. The number of money is not equal to the value of the feature. How much do you want to donate depends on yourself.

**Comment by nacho-domatix** [comment]
Well, a donation is one thing and asking someone (a budget) to develop something is another thing. I guess both are welcome in this (and any) opensource project, but I'm trying to find out more about the second option, where money equals the time of the developer (kind of).
