### ISSUE TITLE
User contributions in the last year

### ISSUE THREAD

**Issue by naiba** [go-gitea/gitea#3888]
Like GitHub profile.
[https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/](https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/)

**Comment by DaMatrix** [comment]
Hate to bump an old-ish issue, but this seems to me a rather important feature which shouldn't be **too** hard for someone who knows more or less what they're doing.

**Comment by naiba** [comment]
@DaMatrix It can give people a sense of accomplishment and let others see what you have done in the past year.

**Comment by lunny** [comment]
@naiba why close this issue?

**Comment by naiba** [comment]
I have lost confidence in the gitea community. On the one hand, because everyone is not familiar with the original design of gogs, on the one hand gitea is not so open, it seems more cautious.

So please don't reopen this issue, of course you can copy it. : )

**Comment by tboerger** [comment]
> I have lost confidence in the gitea community. On the one hand, because everyone is not familiar with the original design of gogs, on the one hand gitea is not so open, it seems more cautious.

And now please explain where Gitea is not open? And I also don't understand your reference to Gogs...

**Comment by naiba** [comment]
@tboerger 
1. https://github.com/gogs/gogs/pull/5277
2. https://github.com/go-gitea/gitea/pull/4166

**Comment by tboerger** [comment]
That doesn't argue for your statement... There had been an open question and you just closed the PR. But if you think that this isn't open to get a question fine that you are using Gogs.

Gitea got webhooks on organization level within the same database table, and your PR would drop all existing organization level webhooks. So it's great that you think we don't understand our codebase... Looks like it's the absolute opposite.

**Comment by naiba** [comment]
@tboerger Ok, thank you for your persistence.
