### ISSUE TITLE
root is blank

### ISSUE THREAD

**Issue by hzmsrv** [go-gitea/gitea#3893]
- Gitea version (or commit ref):newest
- Git version: newest
- Operating system: win10
- Database (use `[x]`):
  - [X ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X ] No
  - [ ] Not relevant
- Log gist:

## Description
visit every projects are showing 500 error
...
2018/05/03 00:51:01 [I] Log Mode: File(Info)
2018/05/03 00:51:01 [I] XORM Log Mode: File(Info)
2018/05/03 00:51:01 [I] Cache Service Enabled
2018/05/03 00:51:01 [I] Session Service Enabled
2018/05/03 00:51:02 [I] Migration: add lfs lock table
2018/05/03 00:51:04 [I] Migration: add reactions
2018/05/03 00:51:05 [I] Migration: add pull request options
2018/05/03 00:51:05 [I] Migration: add writable deploy keys
2018/05/03 00:51:06 [I] Migration: remove is_owner, num_teams columns from org_user
2018/05/03 00:51:06 [I] Migration: add closed_unix column for issues
2018/05/03 00:51:09 [I] Git Version: 2.17.0
2018/05/03 00:51:10 [I] Git config user.name set to Gitea
2018/05/03 00:51:10 [I] Git config user.email set to gitea@fake.local
2018/05/03 00:51:11 [I] SQLite3 Supported
2018/05/03 00:51:11 [I] Run Mode: Production
2018/05/03 00:51:12 [I] Listen: http://0.0.0.0:3000
2018/05/03 00:51:12 [I] LFS server enabled
2018/05/03 00:57:36 [...ules/context/repo.go:348 func1()] [E] RepoAssignment Invalid repo C:\Windows\system32\config\systemprofile\gitea-repositories\XXXX\XXXXX.git: no such file or directory

**Comment by lunny** [comment]
is directory C:\Windows\system32\config\systemprofile\gitea-repositories\XXXX\XXXXX.git exist?

**Comment by hzmsrv** [comment]
no! even they exist. the project pages still show 500

**Comment by hzmsrv** [comment]
it is the database problem. some bug destroy the database

**Comment by lunny** [comment]
@hzmnet any detail?

**Comment by daviian** [comment]
@hzmnet I don't believe this is a database problem.
Reason: path of repository is determined by three factors. The root path from app.ini, the repo owner name and the actual repository name.

**Comment by hzmsrv** [comment]
it is the database 's problem. the repository in the database was broken or mixed. so when you restore those file from the database are not working.
