### ISSUE TITLE
Non-square avatars get distorted

### ISSUE THREAD

**Issue by rrrnld** [go-gitea/gitea#3898]
- Git version: Not relevant
- Gitea version (or commit ref): 1.4.0
- Operating system: Debian
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

Non-square avatars get distorted / displayed as squares. The perfect circle that I attached can be used to reproduce this problem.

## Screenshots

Original:
![circle](https://user-images.githubusercontent.com/525780/39661936-a714c1c0-505a-11e8-886e-33aaa67b6f28.png)

After upload:
![screen shot 2018-05-05 at 11 51 48](https://user-images.githubusercontent.com/525780/39661942-bc05c69c-505a-11e8-937f-1d15e3449b29.png)

**Comment by thehowl** [comment]
Thank you for the issue! We already have one for this, though: #1268

**Comment by rrrnld** [comment]
My bad! I'll close it.
