### ISSUE TITLE
Search in private repositories

### ISSUE THREAD

**Issue by deanpcmad** [go-gitea/gitea#390]
The same as https://github.com/gogits/gogs/issues/3947

I'd like to be able to easily search my private repos. Maybe like the way GitHub does it on the home page when logged in?

**Comment by Bwko** [comment]
Duplicate of #207 and already fixed by #222

**Comment by lunny** [comment]
So I will close this one. Please discuss on #222. And @Bwko, maybe you should change #222's title?

**Comment by deanpcmad** [comment]
Ah I missed that! Thanks :)
