### ISSUE TITLE
Use HMAC for signing webhooks

### ISSUE THREAD

**Issue by captn3m0** [go-gitea/gitea#3901]
- Gitea version (or commit ref): 1.4.1
- Git version: NA
- Operating system: NA
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

Several tools rely on standard GitHub webhooks, which include a `X-Hub-Signature` header to validate the webhook. Gitea sends the `secret` in the payload JSON itself, which doesn't work for all services.

The standard github event signature is a simple HMAC-SHA1 of the request payload with the secret as the key. [[Docs](https://developer.github.com/webhooks/securing/#validating-payloads-from-github)]

## Screenshots

![image](https://user-images.githubusercontent.com/584253/39667842-84589710-50dc-11e8-8d82-99823cb834cd.png)

**Comment by simbo1905** [comment]
Is there a security label that can be added to this ticket? The current method of sending the secret in the payload in plain text is considerably less secure than GitHub, GitLab, BitBucket and Gogs that are hashing the payload.

**Comment by titpetric** [comment]
Is somebody working on this? I'd like to implement it against the GitHub specs (HMAC-SHA1), if somebody volunteers to field the PR. Would love to see this in a future version to integrate against Abstruse CI.

**Comment by titpetric** [comment]
I tracked down the relevant commit adding this in gogs: [3609efe2](https://github.com/gogs/gogs/commit/3609efe2e3d562547ae6497d67d56be7626727d0). The signature header there is prefixed with `X-Gogs`, suggesting we should have `X-Gitea` here.

**Comment by lunny** [comment]
@titpetric Nobody are working on this. Please send a PR to fix this.

**Comment by titpetric** [comment]
Migrated to drone, which supports the current Gitea payloads, was for the best.

**Comment by simbo1905** [comment]
We are using adnanh/webhook and wrote matching rules that work for either Gitea or Github. The point here is not that you cannot match on a secret in the body the point is that it is a less secure approach.

**Comment by titpetric** [comment]
@simbo1905 I agree 100%, but effectively this either means choose a limited set of CI’s that support Gitea, or switch out Gitea for a more secure alternative. I didn’t necessarily want to PR against abstuse CI and at the same time, any PR against gitea might take weeks or months in the pipeline before being merged (if). The reality is that we needed to choose what works without having to build it out on either side.

**Comment by lunny** [comment]
@titpetric Not all PRs took a long time. For those PRs which needs more review and tests, we have to spend more time on it to reduce bugs or regressions . A PR to fix this issue is welcome.

**Comment by urbanswelt** [comment]
I am here to test the PR =)

**Comment by techknowlogick** [comment]
@urbanswelt please see linked PR

**Comment by zobo** [comment]
Ah.. Missed it by a day :)  https://github.com/go-gitea/gitea/pull/6430

Btw: I also added Header("X-Hub-Signature", "sha256=" + t.Signature). to be compatible with more clients.

**Comment by urbanswelt** [comment]
@techknowlogick 

Back from Testing:

Fresh compiled from Master branch today and initial setup done.

Signature would be generated when we fill up the "Secret" field.

![image](https://user-images.githubusercontent.com/2138928/55069250-e38b3600-5083-11e9-89c8-c5c06ee9a469.png)

#6430 will handle the json body if i see that correct.
Perfect work so far ! ;-)

**Comment by zobo** [comment]
Correct. Should I create a different issue to track that part?
