### ISSUE TITLE
Better escaping in various repositories places

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#3903]
- Git version: 2.11.0
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Operating system: Debian Stretch
- Gitea version (or commit ref): 1.4.1
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

**Comment by lafriks** [comment]
Can you please send details to security@gitea.io ?

**Comment by cezar97** [comment]
@lafriks Done.
I didn't send a mail first because sanitizing the input solved the security part anyway.

**Comment by cezar97** [comment]
Also I see that writing markdown in the description get rendered as markdown in the README. Also a bug.

As I've reported a lot of escaping related stuff here, should I open an issue for each one? I've only updated the title with a more generic one.

**Comment by Siesh1oo** [comment]
Not sure what is happening behind the scenes, probably this comment is already outdated: wrapping all user-provided content in iframe Tag with sandbox attribute would solve this.

The alternative of complete sanitation seems much harder, or even impossible unless allowed html is restricted to a very small subset of static html (and even then the sanitation code would seem fragile and error-prone).

**Comment by jonasfranz** [comment]
@lafriks @ghost I close this issue assuming that it got already fixed.
