### ISSUE TITLE
Placement of Gitea in the subdirectory on the website

### ISSUE THREAD

**Issue by Mauladen** [go-gitea/gitea#3904]
Good afternoon, I have a domain 'example.ru', set up Gitea I managed using it but I want to place it in 'example.ru/gitea'

How can I do that?

**Comment by Mauladen** [comment]
@lafriks Thank you, I successfully solved this issue, I think you need to somehow expand the wiki so that users can immediately find the information they need and easily configure gitea + nginx

**Comment by lafriks** [comment]
Any help on docs with samples how to configure would me more than helpful. We are lacking manpower to write docs :)

**Comment by Mauladen** [comment]
I think to do while translation into the Russian language and then add how to make nginx + gitea a couple of moments which I understood

**Comment by lafriks** [comment]
Great, thanks :)
