### ISSUE TITLE
"My repositories" on home page when logged in

### ISSUE THREAD

**Issue by deanpcmad** [go-gitea/gitea#391]
Similar to the way GitHub does it, I'd like to see all the repos I'm assigned to. At the moment I have to go to the org that repo is in and then view the repo that way which can be annoying

**Comment by lunny** [comment]
Currently there is `My Repositories` and `Collaborative Repositories` on the home page when you logged in. This is almost the same with Github. I think you mean `Collaborative Repositories` and Gitea already satisfied with your requirement.
