### ISSUE TITLE
default branch is random after git push --mirror

### ISSUE THREAD

**Issue by davidlt** [go-gitea/gitea#3913]
- Gitea version (or commit ref):
Official 1.4.1 from github
- Git version:
git version 2.17.0
- Operating system:
Fedora 27 (server) / Fedora 28 (client)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

- Create a new repository
- git clone --mirror https://github.com/restic/restic.git
- cd restic
- git remote add testing https://try.gitea.io/blah/restic.git
- git push --mirror testing

[..]
To https://try.gitea.io/blah/restic.git
 * [new branch]        refs/changes/38/232138/1 -> refs/changes/38/232138/1
 * [new branch]        refs/changes/39/232139/1 -> refs/changes/39/232139/1
 * [new branch]        refs/changes/40/232140/1 -> refs/changes/40/232140/1
 * [new branch]        refs/changes/41/232141/1 -> refs/changes/41/232141/1
 * [new branch]        refs/changes/42/232142/1 -> refs/changes/42/232142/1
 * [new branch]        refs/changes/43/232143/1 -> refs/changes/43/232143/1
 * [new branch]        refs/changes/60/231960/1 -> refs/changes/60/231960/1
 * [new branch]        refs/changes/61/231961/1 -> refs/changes/61/231961/1
 * [new branch]        refs/changes/62/231962/1 -> refs/changes/62/231962/1
 * [new branch]        refs/changes/63/231963/1 -> refs/changes/63/231963/1
 * [new branch]        refs/changes/64/231964/1 -> refs/changes/64/231964/1
 * [new branch]        refs/changes/65/231965/1 -> refs/changes/65/231965/1
 * [new branch]        refs/changes/66/231966/1 -> refs/changes/66/231966/1
 * [new branch]        refs/changes/67/231967/1 -> refs/changes/67/231967/1
 * [new branch]        refs/changes/68/231968/1 -> refs/changes/68/231968/1
 * [new branch]        refs/changes/69/231969/1 -> refs/changes/69/231969/1
 * [new branch]        refs/changes/70/231970/1 -> refs/changes/70/231970/1
 * [new branch]        add-coc -> add-coc
 * [new branch]        add-webdav-server -> add-webdav-server
 * [new branch]        master -> master
 * [new branch]        prune-aggressive -> prune-aggressive
 * [new branch]        refs/pull/1002/head -> refs/pull/1002/head
 * [new branch]        refs/pull/1003/head -> refs/pull/1003/head
 * [new branch]        refs/pull/1004/head -> refs/pull/1004/head
[..]

Default branch: refs/changes/60/231960/1 (which is not even the first pushed?)
[..]
 * [new branch]        refs/changes/60/231960/1 -> refs/changes/60/231960/1
[..]

So now for each "forked" repo you need to change settings to set default branch to master or whatever else.

This change happened with 1.4.1 (most likely due to https://github.com/go-gitea/gitea/pull/3715 ).

**Comment by techknowlogick** [comment]
@davidlt This is unlikely be be released in 1.5.0, but perhaps 1.5.1.

The way we could fix this is keep existing logic, but perhaps if we see a "master" branch is there then we assume it is default. That way edge case that was resolved with the linked PR could still be covered, but for everyone else this stays the same.

**Comment by davidlt** [comment]
Maybe this should be moved to 1.5.1 milestone?

**Comment by daviian** [comment]
Basically the problem's origin is here https://github.com/go-gitea/gitea/blob/05dcfcfc33fb91416b6342439f4abf58b316cfef/cmd/hook.go#L185

The first reference with at least one commit will become the default branch, because it is only set for a "bare" repository.
The orderof references depends on the git cmd output.

**Comment by jvstein** [comment]
I saw this issue while migrating data from another git server using `git push --mirror`.

I tried pushing the default branch first and then using `--mirror`, but that resulted in extremely poor performance on the mirror command as it added the new branches.

It would be very helpful to be able to update the default branch via the API. I ended up doing it manually, which took a while.

**Comment by Spongman** [comment]
how does one change the default branch? i just pushed my new repo and the default branch is NOT `master`...

**Comment by zeripath** [comment]
I believe this is fixed now. Please reopen if this is still a problem.
