### ISSUE TITLE
Wrong access control after installation.

### ISSUE THREAD

**Issue by fduxiao** [go-gitea/gitea#3915]
I've found that after I chose `Require Sign-In to View Pages` and installed gitea, anyone could access the website without logging in. See my example at https://test-skgbdmorhk.now.sh. You could see the source code [here](https://zeit.co/fduxiao/test/skgbdmorhk/source). You may also have a check of the configure with username `root` and password `123456` (Don't ruin it !!!)
Everything will work if I restart the service (I tried on another server. After I restarted the service, it worked well.) or build the docker image with a previous config (which I also included in the source code). I found this because I tried to setup a private `doc-site` and I found I could hardly keep them private (since `now` could not `restart` a deployment), or I could not specify the correct url (since I could not tell the url before the service is deployed) (See [now](https://now.sh)).
I have to rebuilt the docker for now with current code (`now` demand exact one `EXPOSE`) but the same issue occurred with the docker image of ID c3220cdfd801.
I think this should be an issue. Do I miss something?

**Comment by bsilva-bentlabs** [comment]
Please fix.  I just installed Gitea for an organization and I'm pretty sure they're going to disallow it with this bug.

Thanks,
Brad

**Comment by bsilva-bentlabs** [comment]
> Please fix. I just installed Gitea for an organization and I'm pretty sure they're going to disallow it with this bug.
> 
> Thanks,
> Brad

Hmm... It appears this only occurs on first start of the server.   So far, every subsequent restart of the service or server reboots, the feature behaves as expected.  

so, this is of far lower importance than I'd first thought.

Brad

**Comment by techknowlogick** [comment]
This is resolved in 1.14-dev.
