### ISSUE TITLE
Question! PR status

### ISSUE THREAD

**Issue by JorTurFer** [go-gitea/gitea#3916]
Hi,

I want move from Gogs to this and wondering if or when you might have CI/Build reporting area that I can update the system from my build agent if my code has passed or failed. I know that commit status is integrated... Is PR status integrated also? 
Best rewards

**Comment by lunny** [comment]
see https://github.com/go-gitea/gitea/pull/2519

**Comment by techknowlogick** [comment]
Closing this issue as question answered
