### ISSUE TITLE
HTTP 500 ERROR on issues.

### ISSUE THREAD

**Issue by Kasi-R** [go-gitea/gitea#3918]
- Gitea version (or commit ref): 1.3.3 (Updated to 1.4.1, bug is still apparent)
- Git version: 2.11.0
- Operating system: Linux 64bit, Debian 9.
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description

Clicking User/Repository/Issues caused a HTTP 500 ERROR. We think this happened because the user who created the issue deleted his account and recreated it under the same name. Tried recreating the bug at https://try.gitea but no luck. 

```/usr/local/go/src/net/http/server.go:1918 (0x6d2df3)
/usr/local/go/src/net/http/server.go:2619 (0x6d5ad3)
/usr/local/go/src/net/http/server.go:1801 (0x6d1ccc)
/usr/local/go/src/runtime/asm_amd64.s:2337 (0x45fc40)
[Macaron] 2018-05-07 19:02:31: Completed /USER/REPO/issues 500 Internal Server Error in 60.707623ms
```

**Comment by lunny** [comment]
the log is not detailed.

**Comment by MacLake** [comment]
We also get a 500 every time when we add an issue or a comment to an issue on Gitea. Neverteless Gitea does what it should before showing a 500.

We use SQLite (tried to switch to PostgreSQL with migrating the existing db,  but that didn’t work out) on Debian Stretch.

**Comment by lunny** [comment]
SQLite has an known database lock problem when multiple peoples are using it.

**Comment by lafriks** [comment]
probable duplicate of sqlite locking issue

**Comment by biju-ps** [comment]
We also have the same issue. Getting 500 error everytime when creating /update issues.   Very few developers is using this repo. So no question of simultaneous every time  
On Sqlite and Ubuntu 18.04 .

**Comment by zeripath** [comment]
@biju-ps Your screenshots posted on an alternative issue show that you're using 1.6.1 which is not only very old but contains a serious security vulnerability. Multiple issues have been fixed since that release including several fixes for potential causes for your issue. Please update to 1.7.4 and consider opening a new issue if you can replicate on 1.7.4 - however please provide logs and preferably a simple way to replicate your issue.
