### ISSUE TITLE
Upgrade failed from 1.0.1 to 1.4.1

### ISSUE THREAD

**Issue by misterpoesy** [go-gitea/gitea#3920]
- Gitea version (or commit ref):
- Git version: 2.11
- Operating system: Windows 2008 R2
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ x] Not relevant
- Log gist:

## Description

I want to upgrade from 1.0.1 to the latest(1.4.1), and many  repositories in use now. I just download the 'gitea-1.4.1-windows-4.0-amd64.exe' and run in gitea folder. It exit and error logs shown as below:

`2018/05/08 17:08:11 [I] Log Mode: File(Info)
2018/05/08 17:08:11 [I] XORM Log Mode: File(Info)
2018/05/08 17:08:11 [I] Cache Service Enabled
2018/05/08 17:08:11 [I] Session Service Enabled
2018/05/08 17:08:11 [I] Mail Service Enabled
2018/05/08 17:08:11 [I] Migration: use new avatar path name for security reason
2018/05/08 17:08:11 [W] ignore avatar 01f07ce8fd534b19284c34bfae34538a rename: strconv.ParseInt: parsing "01f07ce8fd534b19284c34bfae34538a": invalid syntax
2018/05/08 17:08:11 [W] ignore avatar 0283b0742248498f786d0a333e8b52ae rename: strconv.ParseInt: parsing "0283b0742248498f786d0a333e8b52ae": invalid syntax
......
2018/05/08 17:08:11 [W] ignore avatar 046adc086fa4b14734da8b50dbdd033f rename: strconv.ParseInt: parsing "046adc086fa4b14734da8b50dbdd033f": invalid syntax

**2018/05/08 17:08:11 [...itea/routers/init.go:60 GlobalInit()] [E] Failed to initialize ORM engine: migrate: do migrate: Avatar user is not exist**
`

**Comment by daviian** [comment]
@misterpoesy Looks like you already did that migration some time ago!? Otherwise the avatar name would be an integer.
