### ISSUE TITLE
Login via oauth2 github authentication

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#3924]
- Gitea version (or commit ref): docker container @ 1.4.1
- Git version:
- Operating system: centos
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

Maybe only a question/Maybe a bug:

If I try to login via existing github credentials, I end up on the login/account creation page.
I expected to be logged in after successful authentication via github. Is this wanted behaviour,
or am I doing something wrong?

If this is wanted behaviour, what is the advantage of using oauth2 authentification, if I need to register the account in gitea and authenticate again ?

Greetings,
Benjamin

**Comment by techknowlogick** [comment]
You'll need to link a gitea account to your github, which is why it is showing you login/account creation.

**Comment by lafriks** [comment]
yes we have issue to improve that

**Comment by ghost** [comment]
ok thanks for the clarification
