### ISSUE TITLE
lack of comments in the sample configuration file for some fields

### ISSUE THREAD

**Issue by mikolysz** [go-gitea/gitea#3928]
The sample configuration file, located at custom/conf/app.ini.sample, lacks comments for some fields. Some comments have small mistakes in them, mostly grammar-related. I'll submit a pr to fix some of them but maintainer help will be needed for adding comments to fields in the list below, because I don't have the appropriate expertise with gitea and don't fully understand their meaning:
The questions below shouldn't be answered here but in the comments directly (or maybe in separate doc articles) so that someone not deeply familiar with gitea will know what those configuration parameters mean when configuring.

## The repository section:
- ROOT (what is it for)?
- SCRIPT_TYPE (along with an explanation of what values are allowed)
- Explain what mirror syncing is and what the fields are for (I can't find this anywhere in the documentation),
- same for patch testing.
- change ; Force ssh:// clone url instead of scp-style uri when default SSH port is used to something that actually makes sense 
- ; Separate the values by commas. The preview tab in edit mode won't show if the file extension doesn't match (but what should it match)?
- ; Separate extensions with a comma. To line wrap files without an extension, just put a comma. But where to put that comma? at the end of the list? at the beginning? is the default trailing comma the missing one or is it just that, a trailing comma? THis needs more explanation. 
##repository.local
What does local even mean? what are those paths for? local copies? what do local copies mean? 

## repository.upload

WHat are file uploads? what's considered a file upload? is a  pused file considered a file upload?

## ui
- ; Max size of files to be displayed (default is 8MiB) (What do we mean by displayed)? Displayed wherwe? 
- ; Whether the email of the user should be shown in the Explore Users page (email of what user) 

## ui.meta
If I'm not mistaken, those are the <meta> tags displayed in the rendered html? this should be mentioned in an explanation comment.

## markdown

It should be explained what the line break extension is for.

## server
- Explain the syntax of ROOT_URL

## ssh
- ; Root path of SSH directory, default is '~/.ssh', but you have to use '/home/git/.ssh'. (why? so why is it  the default? can git be replaced by RUNNING_USER if it's != git?

## db
- ; For iterate buffer, default is 50
    ITERATE_BUFFER_SIZE = 50
    What is iterate buffer?

## indexer
Explain What it is and what it's for.

## security
Explain:
```
COOKIE_USERNAME = gitea_awesome
COOKIE_REMEMBER_NAME = gitea_incredible
; Reverse proxy authentication header name of user name
REVERSE_PROXY_AUTHENTICATION_USER = X-WEBAUTH-USER
```

- ; True when users are allowed to import local server paths (what are those)

## webhook
More explanation

**Comment by techknowlogick** [comment]
@devil418 The information you are likely looking for can be found on this page: https://docs.gitea.io/en-us/config-cheat-sheet/

Please feel free to submit a PR with updated comments

**Comment by techknowlogick** [comment]
Closing this as #3946 has been merged.

@devil418 thanks for the PR.
