### ISSUE TITLE
try.gitea.io return bad gateway error

### ISSUE THREAD

**Issue by willshiel** [go-gitea/gitea#3934]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [X ] Yes (https://try.gitea.io)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
The 'Try Gitea' button on the home page returns a bad gateway error when clicked.
...

**Comment by techknowlogick** [comment]
Thanks for letting us know. This will be resolved by #3931
