### ISSUE TITLE
Bug in issues

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#394]
When visit issues, it will display others' issues. Visit https://try.gitea.io/issues to reproduce this issue.

![image](https://cloud.githubusercontent.com/assets/81045/21218535/02caf2bc-c2ec-11e6-8a2f-bc0bbe5a75e8.png)

**Comment by tboerger** [comment]
So the user ID seems to be missing in one of the queries

**Comment by lunny** [comment]
Yes. I will see and fix it.

**Comment by tboerger** [comment]
Pull requests are also affected: https://try.gitea.io/pulls

**Comment by lunny** [comment]
OKay. One PR fixes two.
