### ISSUE TITLE
Oauth2 don't fly with mysql/mariadb

### ISSUE THREAD

**Issue by agaida** [go-gitea/gitea#3944]
- Gitea version (or commit ref): latest git
- Git version: 2.17.0
- Operating system: debian stretch 
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X ] Not relevant
- Log gist:

## Description

after upgrading to current git i get an
```
2018/05/10 15:30:48 [...itea/routers/init.go:64 GlobalInit()] [E] Failed to initialize OAuth2 support: Error 1071: Specified key was too long; max key length is 767 bytes
```
this is clearly a 'bug' with mariadb - gitea try to create the oauth2_ table and fails creating it because the primary key is to long, refs: https://stackoverflow.com/questions/41176482/mariadb-wont-create-table-with-large-varchar-as-primary-key

**Comment by agaida** [comment]
going back to v1.1.0-1167-g8d5f58d83 kind of 'solve' that for me

**Comment by agaida** [comment]
https://dev.mysql.com/doc/refman/5.5/en/charset-charsets.html - might give some hints too. So right now i 'fixed' it with
```
CREATE TABLE IF NOT EXISTS `oauth2_session` (`id` VARCHAR(400) PRIMARY KEY NOT NULL, `data` TEXT NULL, `created_unix` BIGINT(20) NULL, `updated_unix` BIGINT(20) NULL, `expires_unix` BIGINT(20) NULL) DEFAULT CHARSET latin1 ENGINE = myisam;
```
but imho this is really dirty

Edit: Hmm, innodb would work too, but such long primary keys should be considered dirty anyways - what about a hash as id?

**Comment by techknowlogick** [comment]
utf8mb4 doesn't work, however utf8 does. no need for latin1 or myisam.

**Comment by thehowl** [comment]
See #3859

**Comment by agaida** [comment]
utf8 don't work - https://github.com/go-gitea/gitea/issues/3859#issuecomment-386355900

```
mysql> SHOW CHARACTER SET;
+----------+-----------------------------+---------------------+--------+
| Charset  | Description                 | Default collation   | Maxlen |
+----------+-----------------------------+---------------------+--------+
| latin1   | cp1252 West European        | latin1_swedish_ci   |      1 |
| ascii    | US ASCII                    | ascii_general_ci    |      1 |
| utf8     | UTF-8 Unicode               | utf8_general_ci     |      3 |
| utf8mb4  | UTF-8 Unicode               | utf8mb4_general_ci  |      4 |
| utf16    | UTF-16 Unicode              | utf16_general_ci    |      4 |
| utf32    | UTF-32 Unicode              | utf32_general_ci    |      4 |
+----------+-----------------------------+---------------------+--------+
```
