### ISSUE TITLE
New repositories have all pull request options disabled.

### ISSUE THREAD

**Issue by de-vri-es** [go-gitea/gitea#3952]
We recently updated gitea. One of the new features this introduced is the option to disable specific pull request merge strategies (merge, rebase, squash).

All old repositories have all of these options available. However, every new repository we create has all of them disabled. I also couldn't find a way to set defaults globally.

We have quite a few repositories, so manually having to enable these options is rather a nuisance. Did I miss something? If not I believe that a global default for this would be very useful. Alternatively, simply having them all enabled by default is also good for us.

**Comment by lafriks** [comment]
Do you create that form UI or API?

**Comment by de-vri-es** [comment]
This was directly from the web interface. I didn't try with the API.

**Comment by pjanx** [comment]
I have used the API with the same results, and I haven't been able to find an API endpoint to change it.

**Comment by lunny** [comment]
You have to change it on the UI currently as I know.

**Comment by de-vri-es** [comment]
Would it be an option to simply set the defaults to true until someone has the time to implement configurable defaults? It would improve usability a lot for me.

I wanted to submit a PR for this, but I got quite confused by Go, and I don't have the time to learn it sadly. But I imagine changing a default is a simple patch?

**Comment by de-vri-es** [comment]
@lafriks: awesome, thanks! :+1: And @lunny for the quick review.
