### ISSUE TITLE
crowdin error when trying to execute tests locally

### ISSUE THREAD

**Issue by mikolysz** [go-gitea/gitea#3977]
- Gitea version (or commit ref): c14870c5ac52bf9d2d8b884222b4743accf9d929
- Git version: 1.9.1
- Operating system: ubuntu 12.04 lts (runnign as a vm on vagrant. Host OS is win 7 x64).
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x ] Not relevant
- Log gist: STDOUT and STDERR of `drone exec` https://pastebin.com/DFhL8L43

## Description

WHen executing 'drone exec' in the gitea directory, the tests fail. I get a long log (link above), but those two lines seem to be the most important:
```
[download_translations:L0:0s] 2018/05/16 11:50:57 error while building languages: Error from crowdin: Requested project does not exist or API key is not valid (error code 1)
```
It seems that to execute tests, I need an api key for crowdin? Is that true, and, if so, how to optain it?

**Comment by techknowlogick** [comment]
A workaround that I do for testing is to remove that section from `.drone.yml`, I also remove the discord section as well.

Note: make sure not to commit these changes.

**Comment by mikolysz** [comment]
In that case, I believe a script like run-tests.sh that modifies the file appropriately would be needed. If that's too hard or impossible for some other reason, a mention in the readme would suffice.

**Comment by lunny** [comment]
Maybe a new ENV local could be added so that ignore some tests.

**Comment by stevegt** [comment]
@devil418 You can get an API key for crowdin by signing up at their site, then looking under your account settings.  I haven't figured out where to put it yet though...  

(later edit:)  `drone exec` has --secrets and --secrets-file flags, but a bigger issue is that even when completely removing crowdin and discord stanzas from .drone.yml, I later hit `failed to parse profiles: open integration.coverage.out: no such file or directory`; not sure if it's something I broke in .drone.yml, or if there's something missing from the testing section of CONTRIBUTING.md.
[drone.yml.gz](https://github.com/go-gitea/gitea/files/2041921/drone.yml.gz)

(still later:)  Okay, I'm going to conclude that `drone exec` is not intended to be run by anyone other than a maintainer.  I've also removed the coverage bits from .drone.yml, and now drone is trying to push a new image to dockerhub:

<pre>
[docker_docs:L341:124s] + /usr/local/bin/docker tag 00000000 gitea/docs:latest
[docker_docs:L342:124s] + /usr/local/bin/docker push gitea/docs:latest
[docker_docs:L343:124s] The push refers to a repository [docker.io/gitea/docs]
[docker_docs:L344:125s] dcb9aa504a9c: Preparing
[docker_docs:L345:125s] 97d75450208b: Preparing
[docker_docs:L346:125s] 00ce309518aa: Preparing
[docker_docs:L347:125s] f295bdb1762a: Preparing
[docker_docs:L348:125s] c9e8b5c053a2: Preparing
[docker_docs:L349:125s] denied: requested access to the resource is denied
[docker_docs:L350:125s] time="2018-05-26T21:13:44Z" level=fatal msg="exit status 1"
</pre>
 
[drone.yml.gz](https://github.com/go-gitea/gitea/files/2041969/drone.yml.gz)
