### ISSUE TITLE
500 when user is deleted

### ISSUE THREAD

**Issue by sdfdgthy65e4rgthyjyt** [go-gitea/gitea#398]
If a user creates an issue, and then the user deletes his account, the page with opened/closed issue doesn't load anymore, but I get a 500.
I couldn't reproduce this on try.gitea.io because I also get a 500 if I try to delete my user account, but I was able to reproduce this with Gogs. See this https://try.gogs.io/nlfbqggh/MyTestRepo/issues  (note: I'm not user `nlfbqggh`, my username was `xxxxxxxx`. I created an issue and then deleted my user account).

**Comment by lunny** [comment]
Which version are you tested in?
