### ISSUE TITLE
Monitoring page fails - probably during a problem with an unavailable source for mirrored repositories

### ISSUE THREAD

**Issue by SlavekB** [go-gitea/gitea#3980]
- Gitea version (or commit ref): 1.4.1
- Git version: 2.1.4
- Operating system: Debian GNU/Linux 8.x
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
In my instance of Gitea I have several mirrors of GIT repositories. However, the source server of these mirrors is now unavailable for some time.

## Screenshots
System Notices are properly reported about failure of mirror synchronization:

> Failed to update mirror repository...

But Monitoring page now fails:

> template: admin/monitor:52:19: executing "admin/monitor" at <.Start.FormatLong>: can't evaluate field FormatLong in type time.Time

**Comment by SlavekB** [comment]
I can confirm that when the source server for mirrors is available, Monitoring page is working again.

**Comment by ghost** [comment]
I think it's caused by this PR #3142

**Comment by daviian** [comment]
@SlavekB @yasuokav Are you able to verify that the PR fixes that issue?

**Comment by ghost** [comment]
@daviian Yes, it works for me now.

**Comment by lunny** [comment]
closed by #4203
