### ISSUE TITLE
What variables are available to the link_account template?

### ISSUE THREAD

**Issue by coolaj86** [go-gitea/gitea#3987]
As per https://github.com/go-gitea/gitea/issues/3837 I'd like to update the `link_account` template to give a clearer message.

For example:

```
It appears that this is you first time logging in with <<provider>> as <<username>>.
Is that right?

[[ No, I'd like to link to my existing <<sitename>> account ]]

[[ Yes, Let me set a backup password for <<sitename>> ]] 
```

Where might I find the documentation to know what's available on that page?

**Comment by wxiaoguang** [comment]
IMO the variables are in the render context data, no document. You could refer to the code context.

And it's not feasible to write documents for every template variable at the moment, the code itself should tell developers how it works in most cases. If something is unclear, either use a better/clearer variable name, or add enough comments.
