### ISSUE TITLE
DOS line endings in files created by wiki

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#3989]
- Gitea version (or commit ref): 1.4.1
- Git version: 2.11.0-3+deb9u2
- Operating system: Debian 9.4
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant

## Description

If I create a new page in the gitea wiki, it creates the markdown files with DOS line endings. Is is possible to use Unix line endings?

**Comment by lunny** [comment]
Maybe a config option with line endings.

**Comment by ghost** [comment]
Yes, it would be better solution.
