### ISSUE TITLE
SSH Repo URL is incorrect

### ISSUE THREAD

**Issue by methodbox** [go-gitea/gitea#4013]
- Gitea version (or commit ref): 1.3.2
- Git version: 2.7.4
- Operating system: macOS
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description
I can't reproduce the issue using your test site because it doesn't allow SSH without keys; I'm not uploading a key to your test site.

That being said gitea *is* creating the directory where I specified during setup on the server.

It is NOT providing the correct SSH URL:

```git remote add origin git@[IP address]:myuser/fetchDNS.git```

As noted in another issue #4011 this is also wrong due to the case-INsensitivity of gitea.

But it is also wrong based on the configuration I specified during setup:

```/home/myuser/repos```   <- Repos directory

This *is* the directory where the repo was created, which means the SSH URL should be:

```git remote add origin git@[IP address]:/home/myuser/repos/fetchDNS.git```

When I manually change the remote URL in my local git settings it works.

If something this fundamental is broken in a test setup I will likely need to look for a different solution or go back to using my UI-less git configuration as before.

Installing Git with default configuration is far less buggy. It seems like the default Git behavior should carry over, but that doesn't appear to be the case.
...

**Comment by techknowlogick** [comment]
Another user experienced the same issue as you (#3627), and @daviian wrote a better reply to them than I could, so I'll copy it here

-----
Hi,

To clarify the SSH url: the stuff after the colon is for internal use in gitea. Gitea itself provides the mapping to the actual repository location.
So what you do when using the original path is bypassing gitea, which shouldn’t be possible at all!

One reason this happens is that you set your SSH key in the authorized_keys file yourself with e.g. ssh-copy-id. However that’s wrong and you should definitely let gitea handle this file.
Furthermore everytime a user adds an SSH key via gitea web-UI the authorized_keys file gets overwritten.

Another thing is that usually the user from the SSH url is git or whatever is configured in the app.ini and not the actual gitea-user itself.

The first thing you should try now is to go into the Admin settings on the gitea UI and execute:

1. Update the ‘.ssh/authorized_keys’ file with Gitea SSH keys. (Not needed for the built-in SSH server.)
2. Resynchronize pre-receive, update and post-receive hooks of all repositories.

After that you HAVE to set your SSH keys through gitea web-UI.

Hopefully that solves your issue!

**Comment by methodbox** [comment]
I’ll give that a shot. Note the URL will still (I assume) mismatch with the case-sensitivity but I assume this mapping by Gitea would solve that?

**Comment by daviian** [comment]
@methodbox Did it work? Can this issue be closed?

**Comment by techknowlogick** [comment]
Closing this issue. Please re-open if the above does not solve the issue.

**Comment by methodbox** [comment]
Sorry, yes that seems to work okay.
