### ISSUE TITLE
Failed to upload files to '' with error: git push origin master: exit status 1 - remote: ***

### ISSUE THREAD

**Issue by gerroon** [go-gitea/gitea#4015]
- Gitea version (or commit ref):
- Git version: server git version 1.7.10.4, client 2.17
- Operating system: Debian Wheezy i386
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x ] Not relevant

## Description

This is what I get when I try to upload 2 xml files in the web UI into an newly created Repository

Failed to upload files to '' with error: git push origin master: exit status 1 - remote: *** Project description file hasn't been set[K remote: error: hook declined to update refs/heads/master[K To /home/git/gitea-repositories/USER/TEST.git ! [remote rejected] master -> master (hook declined) error: failed to push some refs to '/home/git/gitea-repositories/USER/TEST.git'

**Comment by techknowlogick** [comment]
@gerroon Have you run "rewrite git hooks" in the admin panel?

**Comment by gerroon** [comment]
@techknowlogick 

I do not see any rewrite git hook but I tried "Resynchronize pre-receive, update and post-receive hooks of all repositories.", it did not change the negative outcome of the operation.

**Comment by lafriks** [comment]
Are there any error in gitea.log?

**Comment by techknowlogick** [comment]
Closing. please re-open if needed.
