### ISSUE TITLE
[...s/setting/setting.go:887 NewContext()] [E] Error parsing git revision version: strconv.ParseUint: parsing "GIT": invalid syntax

### ISSUE THREAD

**Issue by gerroon** [go-gitea/gitea#4017]
- Gitea version (or commit ref): d94472e
- Git version: 2.1git version 2.17.GIT
- Operating system: Debian Wheezy i386
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x ] Not relevant
- Log gist:

## Description
I just compiled a newer version of Git (it was 1.7.10.4) now this is the message I get when i try to run gitea in the terminal.

[...s/setting/setting.go:887 NewContext()] [E] Error parsing git revision version: strconv.ParseUint: parsing "GIT": invalid syntax

...

**Comment by lunny** [comment]
This should not an issue now since we used `github.com/mcuadros/go-version` to compare the git version. Closing now and please feel free to reopen it.
