### ISSUE TITLE
Branch protection with regex support

### ISSUE THREAD

**Issue by sebastian-sauer** [go-gitea/gitea#4024]
- Gitea version (or commit ref): 1.4.1
- Git version: not relevant
- Operating system: not relevant
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
  - [x] not relevant
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

Currently branch protection is only available for named branches. In order to e.g. only allow specific colleagues to push into release branches it would be great if we could configure a regex for branch protection. This would allow us to protect all branches matching release and not having to protect each individual branch.

**Comment by lafriks** [comment]
There is already feature request for this #2529
