### ISSUE TITLE
Improve profile avatar settings UI

### ISSUE THREAD

**Issue by daviian** [go-gitea/gitea#4025]
## Description

Current UI to manage profile avatars is confusing.
It is not clear how to use the provided form.
1. It's not clear how to set a random avatar. It isn't even mentioned that this is possible at all.
2. It's not obvious how to unset a custom avatar and change it to use gravatar.
  Do I have to click "Delete Avatar" or select the radio button "Lookup Avatar By Email Address" and "Update Avatar"

## Screenshots

Screenshots of a first draft will follow.

#### Can also solve

https://github.com/go-gitea/gitea/issues/600
https://github.com/go-gitea/gitea/issues/1268
https://github.com/go-gitea/gitea/issues/3514

**Comment by wxiaoguang** [comment]
Related issues have all been resolved, and the UI has been changed a lot.
