### ISSUE TITLE
Gitea does not appear in Snap store

### ISSUE THREAD

**Issue by lofidevops** [go-gitea/gitea#4026]
- Gitea version (or commit ref): Any
- Git version: Any
- Operating system: Ubuntu
- Database (use `[x]`):
  - [x] N/A
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Not relevant
- Log gist: N/A

## Steps to reproduce

* Visit Snap store website
* Search for Gitea

## What should happen?

* Gitea listed on website
* Can install from command line with `snap install gitea`

## What happens instead?

* Website error message: Sorry, we couldn’t find "gitea"
* Command line error message: `error: snap "gitea" not found`

## Related links

* https://snapcraft.io/search?q=gitea
* https://github.com/go-gitea/gitea/issues/2539

**Comment by lunny** [comment]
I'm trying to do that.

**Comment by lafriks** [comment]
@lunny I already did :)

**Comment by lunny** [comment]
But gitea still cannot be searched in store?

**Comment by lafriks** [comment]
Don't know why. It shows as built & published but not when searching, might be some delay. Also version is v1.1.0+commit sha. To get normal version numbers we would need to switch develop -> master -> release/ workflow and tag versions on master

**Comment by techknowlogick** [comment]
I can't search either, but I am able to see: https://build.snapcraft.io/user/go-gitea/gitea

**Comment by techknowlogick** [comment]
Per snap [docs](https://docs.snapcraft.io/core/usage): `Anybody can publish a snap, but doing a Snap Store search will only find snaps that are published to the stable release channel`

**Comment by lafriks** [comment]
But than we need to push current master branch build to stable that does not seems to be right :)

**Comment by lunny** [comment]
@lafriks I haven't been familiar with Snap, don't know about that. Of course, we should not set master as stable.

**Comment by tbraeutigam** [comment]
There's two options in that case:
 - Wait until a new release and push that from edge to stable
 - Do a manual build an upload it (in the snapcraft.yaml file, you can specify tags) -- this part is not automated though.

The easier option is definitely the former, and seeing how it's available (thanks! and great to see!) via edge for curious people, I think this should be fine?

**Comment by lofidevops** [comment]
Speaking as a curious person, `sudo snap install gitea --edge` worked for me :) thanks for pointing out that it's available. If I find any issues I'll try to log them before the next release (when this issue is resolved and Gitea appears in the store for everyone).

**Comment by popey** [comment]
I was super excited to hear about gtiea being a snap! Thanks for making it. I also was curious and installed on my home server. It works great! 

You might be interested to learn that we ([snapcrafters](https://github.com/snapcrafters) ) have been putting some code in the yaml to detect whether it's time to build a stable release or just build to edge. We simply look for the most recent stable tagged release, compare it with what's in the beta channel, and decide at that point whether to git checkout the stable release or build edge. That way you can have one yaml, and build for both stable and unstable builds. If it builds a stable release, you can push that to the beta channel and ask your community to test it. if you're happy with the build, push that release to stable. Subsequent builds will be tip of master and pushed to edge, until another upstream stable release rolls around.

There's a few examples of this in the snapcrafters repo. The [obs-studio](https://github.com/snapcrafters/obs-studio/blob/master/snap/snapcraft.yaml) one is probably simplest. The key parts to note are the `override-build:` which does the version detection, and `version-script:` which sets the version number in the snap.

Hope that's useful. Ping if you need info / help etc.

<3

**Comment by lafriks** [comment]
we currently do new `release/1.x` branch from master and tag on that branch, so on master we do have no tags. So I seem not to find way to have built beta/stable releases from these branches to be published automatically.

**Comment by techknowlogick** [comment]
Perhaps we could have a drone plugin that'll do snapcraft releases? This would of course require creating a snap drone plugin first.

**Comment by lunny** [comment]
@techknowlogick seems a good idea.

**Comment by popey** [comment]
Heya! Any progress on this? I'd love to be able to install a stable version of gitea from the snap store soon. Anything I can do to help?

**Comment by techknowlogick** [comment]
@popey no progress yet, but snap has a docker image: https://hub.docker.com/r/snapcore/snapcraft/ that we could probably leverage instead of building a drone-plugin

**Comment by lunny** [comment]
I think @lafriks had created an account to publish gitea to snap store. When we release a stable version, we can publish it I think.

**Comment by lafriks** [comment]
@lunny not really... snapcraft builds only master branch so we can't really release stable there, only edge... If we want to build from other branches also, we need to build them manually or setup drone to do that somehow and publish to snapcraft store

**Comment by lafriks** [comment]
@popey if you have any ideas on how we could automatically build other branches & tags on them and publish to snap store, ideas are more than welcome

**Comment by popey** [comment]
Sure! For some other snaps (one I linked to above) we do some simple detection shell script magic in the snapcraft.yaml. Essentially we use `snap info <snapname>` to find out what version is currently published in the store. If the latest stable release (gained from the github api, wget or whatever) is higher, we use `git checkout` commands to get the right tagged version and build that. If the latest release is already in the beta channel then we just build the latest master branch. This allows one yaml to build both stable and unstable builds.

See the `override-build` section in https://github.com/snapcrafters/obs-studio/blob/master/snap/snapcraft.yaml#L38 and the `version-script` section above that for an example.

Something like that could work for you?

**Comment by lafriks** [comment]
@popey but you are not building edge version from master than, right? Also we do not tag on master branch but on `release/v1.x` branches, will that work?

**Comment by lofidevops** [comment]
Also shows up on the snapcraft website. 🎉

**Comment by lunny** [comment]
how to submit a stable version?

**Comment by popey** [comment]
Well, it's "kinda" fixed. :) The store UI has changed so it exposes snaps which exist in channels other than stable. As gitea is only in edge, it now appears.

So what's exposed on the store is the contents of the 'edge' channel, that is the latest build, which may (or may not) be completely unstable and unsuitable for end users.

I'd recommend making a stable build of your latest release and pushing that to the stable channel. That way people can install gitea and stay on the stable release. 

Sorry @lafriks I missed your question. You certainly could build from any tag, as you can use a scriptlet (as I indicated) to do whatever git magic you want to grab the right source revision / tag and build it.

**Comment by lafriks** [comment]
I can not seem to find a way to trigger building other than master branch from their build system. As much as I understand we would have to build our own snap package and upload to their store to get that. But for that we need drone support for that
