### ISSUE TITLE
Team members able to see issues for private repositories not part of team

### ISSUE THREAD

**Issue by bkraul** [go-gitea/gitea#4029]
- Gitea version (or commit ref): b574af2 
- Git version: 2.15.0
- Operating system: Ubuntu 18.04 LTS (docker)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant

## Description
This issue was discovered trying to target the opposite situation. Basically what happens is that when a team is added to an organization, the user in the team can see the list of issues for all projects in the organization, but not able to click on them (getting instead a 404 error).

The correct behavior should be that no issues for private repositories should be visible if the repositories are not part of the team in question.

## Screnshots
![image](https://user-images.githubusercontent.com/14616851/40454592-f55202c8-5eae-11e8-8189-f7e6136c7a42.png)
![image](https://user-images.githubusercontent.com/14616851/40454597-fcffebc0-5eae-11e8-8d83-eb1b5fa0c557.png)

**Comment by techknowlogick** [comment]
Closed with #4034
