### ISSUE TITLE
Please update App Version to 1.4.1 for 1.4.1 tag

### ISSUE THREAD

**Issue by awwong1** [go-gitea/gitea#4041]
- Gitea version (or commit ref): https://github.com/go-gitea/gitea/tree/abc159637c2ec430d7636e35c6829f7fe0458864
- Git version: `1.4.1`
- Operating system: `n/a`

## Description

Please update the application version to match the latest release.

https://github.com/go-gitea/gitea/blob/abc159637c2ec430d7636e35c6829f7fe0458864/main.go#L24

Still shows `1.4.0-dev` in https://github.com/go-gitea/gitea/releases/tag/v1.4.1

**Comment by lafriks** [comment]
Version is updated using go build tags, see Makefile

**Comment by awwong1** [comment]
That's for the response, @lafriks. I am running Gitea on my raspberry pi. I didn't put `go-bindata` in my path, but I found that I could generate a functioning executable just by running `go build`.

I will proceed by using the Makefile in the future, by running `make build`. Thanks for your time.
