### ISSUE TITLE
Provide support for blob url

### ISSUE THREAD

**Issue by shollander** [go-gitea/gitea#4048]
Please provide support for blob access via urls. Most major git web servers (GitHub, Gitlab, etc. )provide this functionality. For example, https://gitea/org/repo/blob/<sha_1>/file.

I am trying to use ReviewBoard as a code review tool with Gitea, but it doesn't work since ReviewBoard needs to be able to pull files by blob id. Gitea currently provides permalink support using commit id, but not blob id.

See https://www.reviewboard.org/docs/manual/dev/admin/configuration/repositories/git/ for more information.

**Comment by lafriks** [comment]
Fixed by #5334
