### ISSUE TITLE
ssh broke

### ISSUE THREAD

**Issue by UtechtDustin** [go-gitea/gitea#4049]
After install gitea i saw that the ssh login broke with the error message

> TY allocation request failed on channel 0
> Hi there, You've successfully authenticated, but Gitea does not provide shell access.
> If this is unexpected, please log in with password and setup Gitea under another user.
> Connection to dustin-utecht.de closed.

So i found that gittea should run with a other user then root.

How i can fix it that i can login with (root) ssh again ?
What should i expect when i run gitea with a other user, that nothing brakes ?

**Comment by hamaluik** [comment]
I foolishly installed gitea under my normal user account (not root), but it still broke ssh. Now all I can do is log in under a root account. How do I revert this silly behaviour?

**Comment by daviian** [comment]
You've to undo the changes under ~/.ssh/authorized_keys, such that all gitea related stuff is removed and your original ssh public key is in there.

**Comment by UtechtDustin** [comment]
@daviian 
After i remove the stuff from authorized_keys, can i run gittea with a other user without permission issues ?

**Comment by daviian** [comment]
@Falseee 
Yes that's possible. After switching user you should go to the admin panel in gitea and start the rewrite authorized_keys file job.
