### ISSUE TITLE
Failed to disable attachments

### ISSUE THREAD

**Issue by w2ak** [go-gitea/gitea#4061]
- Gitea version (or commit ref): 4ba9745 with Docker
- Git version: 2.15
- Operating system: Docker on Ubuntu 16.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No because it involves configuration
  - [ ] Not relevant
- Log gist: not relevant?

## Description

In my app.ini configuration I put
```
[attachment]
PATH = /data/gitea/attachments # This was here because of the template
ENABLED = false
```
However, I was able on my gitea to open an issue and attach a picture in it. Here are some of the reasons I could think about, I would love to know if you have an idea about this:
* The attachment was a picture
* The user attaching it is an admin
* The 'ENABLED = false' option doesn't work (bug?)

I am not used to debugging in gitea, please give me some instructions if you want some information (are there relevant logs for this kind of problem?).

**Comment by w2ak** [comment]
Just to be sure, I tested on the same server with a non-administrator account and same result, I was able to upload a picture.

**Comment by lunny** [comment]
I confirm this is a bug, when `ENABLED = false`, it's in fact enabled and it's disabled when `ENABLED = true`.
