### ISSUE TITLE
Use correct terminology in description on Docker Hub

### ISSUE THREAD

**Issue by mbger** [go-gitea/gitea#4063]
## Description

Thanks to #3365 the description for [Gitea on Docker Hub](https://store.docker.com/community/images/gitea/gitea) with the quick setup guide is way better than it used to be. I would only suggest to use the correct terminology here. The description currently says:

> Dockerfile (with description):
>
> Use this dockerfile to get up and running quickly. You should change mysql user- and root password. When installing, you can reference the database

Since what's shown in this example is actually not a [`Dockerfile`](https://docs.docker.com/engine/reference/builder/#usage) but a [`Compose file`](https://docs.docker.com/compose/compose-file/) I'd say *Dockerfile* should be replaced with *Compose file* here.

**Comment by zeripath** [comment]
This does need doing - it confused me when I first looked at Gitea. 

It's probably quite a quick fix and an easy PR

**Comment by techknowlogick** [comment]
I've just updated the documentation.
