### ISSUE TITLE
Copy/paste issues with diffs

### ISSUE THREAD

**Issue by silverwind** [go-gitea/gitea#4076]
Copying content from a diff like [this](https://try.gitea.io/go-gitea/gitea/commit/15f6ec96327d69d19fcce937811214e113341f58), I see inconsistent behaviour between browsers.

Firefox copies double newlines:
````
    claims := jwt.MapClaims{

      "repo": repo.ID,

      "op":   lfsVerb,

-     "exp":  now.Add(5 * time.Minute).Unix(),

+     "exp":  now.Add(setting.LFS.HTTPAuthExpiry).Unix(),

      "nbf":  now.Unix(),

    }

    if user != nil {
````

Safari copies line numbers:
````

claims := jwt.MapClaims{
--
269 | 269 | "repo": repo.ID,
270 | 270 | "op":   lfsVerb,
271 |   | -			"exp":  now.Add(5 * time.Minute).Unix(),
  | 271 | +			"exp":  now.Add(setting.LFS.HTTPAuthExpiry).Unix(),
272 | 272 | "nbf":  now.Unix(),
273 | 273 | }
274 | 274 | if user != nil {
````

Chrome seems alright:
````
    claims := jwt.MapClaims{
      "repo": repo.ID,
      "op":   lfsVerb,
-     "exp":  now.Add(5 * time.Minute).Unix(),
+     "exp":  now.Add(setting.LFS.HTTPAuthExpiry).Unix(),
      "nbf":  now.Unix(),
    }
    if user != nil {
````

I will probably attempt a fix later, but feel free to contribute as well.

**Comment by Larivact** [comment]
For Firefox it can be fixed by replacing the `<pre>` tags in the `<td class="lines-code ">` cells with `<div style="white-space:pre">`.

**Comment by silverwind** [comment]
Related here: The `+` and `-` from a diff should not be copied. It can be done by using CSS pseudo elements with `user-select: none`.
