### ISSUE TITLE
Many links broken

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#4081]
- Gitea version (or commit ref): 15f6ec9
- Git version: N/A
- Operating system: N/A
- Database (use `[x]`): N/A
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
    - https://try.gitea.io/yasuokav/link-test/issues/2
    - https://try.gitea.io/yasuokav/link-test/src/branch/master/README.md
  - [ ] No
  - [ ] Not relevant
- Log gist: N/A

## Description
The link should be 
`https://try.gitea.io/yasuokav/link-test/issues/1` 
instead of 
`https://try.gitea.io/yasuokav/link-test/issues/yasuokav/link-test/issues/1`

Please check the links above for more details.

I think this issue because of #4058 @JonasFranzDEV 

## Screenshots
N/A

**Comment by sapk** [comment]
It should be related to the remove of leading '/' when base isn't absolute (with a scheme). This test should be change to add a check if base start with a '/' to keep it.
As this error is related to a suggested solution of mine ^^.

**Comment by lunny** [comment]
@JonasFranzDEV   And I'm afraid release/v1.4 is also affected.

**Comment by sapk** [comment]
@lunny fix is ready. I will backport it.
