### ISSUE TITLE
Why big repos are working on Gitea and not in Gogs

### ISSUE THREAD

**Issue by enric1994** [go-gitea/gitea#4098]
After three months using Gogs, I am planning to move all my repos to Gitea.

Reason?
When pushing a 6GB repository to Gogs it fails with that error:
```Counting objects: 3, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (2/2), done.
error: RPC failed; HTTP 413 curl 22 The requested URL returned error: 413 Request Entity Too Large
fatal: The remote end hung up unexpectedly
Writing objects: 100% (3/3), 4.49 GiB | 215.48 MiB/s, done.
Total 3 (delta 0), reused 1 (delta 0)
fatal: The remote end hung up unexpectedly
Everything up-to-date
```

Otherwise, with Gitea it works like a charm!

I know that this is not exactly an issue but, **why it works in Gitea and not in Gogs?**

PD 1: I used the latest Docker images to do the tests
PD 2: I also did the tests pushing a 4GB file directly to try.gogs.io and try.gitea.io and both failed!

Thanks

**Comment by techknowlogick** [comment]
In regards to PD 2, that is likely because try.gitea.io is usually low on disk space due to it being a demo install.

**Comment by enric1994** [comment]
Yes.. I suppose that was the disk space:
```
Compressing objects: 100% (2/2), done.
error: RPC failed; HTTP 413 curl 22 The requested URL returned error: 413 Request Entity Too Large
fatal: The remote end hung up unexpectedly
Writing objects: 100% (3/3), 4.49 GiB | 215.48 MiB/s, done.
Total 3 (delta 0), reused 1 (delta 0)
fatal: The remote end hung up unexpectedly
Everything up-to-date

```

**Comment by lunny** [comment]
@enric1994 maybe because your different reverse proxy settings? We have did some performance optimizations after forked from Gogs but I don't think that will result in big differences. And we should have more  performance optimizations i.e. https://github.com/go-gitea/gitea/issues/4002

**Comment by enric1994** [comment]
@lunny I am not using any proxy, just a docker-compose with the DVCS and the DB: 
1. PostgresSQL with Gogs (**can't** push 6GB)
2. MySQL with Gitea (**can** push 6GB)

PD: The push is done via HTTP! I read it requires a lot of RAM

**Comment by lunny** [comment]
Glad to see that. Since we have thousands of commits different from Gogs, I cannot tell you which commits made it.

**Comment by enric1994** [comment]
Finally, I noticed that with SSH I can push big repos on both plattforms.

Thanks.

**Comment by rom111419** [comment]
Additional decision for NGINX https://github.com/go-gitea/gitea/issues/5805#issuecomment-477523202
