### ISSUE TITLE
gitgraph

### ISSUE THREAD

**Issue by kjellkvinge** [go-gitea/gitea#410]
feature request/discussion:

I know there have been some feature requests for something that visually shows the branches in a repository.

for instance gogits/gogs#1339

I have played a bit with https://github.com/bluef/gitgraph.js - see screnshot: http://imgur.com/aPlsCtY

I know this feature is not scheduled for next release, but what is your thoughts on this apporach? I could create a pull-request of this approach would be considered.

**Comment by tboerger** [comment]
I like that and we are open for pull requests. But I think this can be merged after 1.0 branch.

**Comment by lunny** [comment]
resolved by #428
