### ISSUE TITLE
Search issue or PR by its id / index number

### ISSUE THREAD

**Issue by HerrHase** [go-gitea/gitea#4109]
- Gitea version (or commit ref): 1.3.2
- Git version:
- Operating system: Ubuntu
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [*] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [*] Not relevant
- Log gist:

## Description
I have often the Problem that i want to search by the ID. Is there a way to add a search like this, "#<id>"?

**Comment by Aviortheking** [comment]
+1 & maybe make it work too for this part
![image](https://user-images.githubusercontent.com/15822031/58942103-6532ca80-877d-11e9-9e71-49437c1b90f9.png)

**Comment by alexanderadam** [comment]
@Charliekenney23, I'm just curious: [do you have any open PR regarding this issue](https://github.com/go-gitea/gitea/issues/5462#issuecomment-445098047)?

**Comment by Charliekenney23** [comment]
@alexanderadam Ah sorry, totally forgot about this. I got really busy after saying I'd take this. Anyone else is welcome to pick it up.

**Comment by tyroneyeh** [comment]
Hello

Could try the script to search issue #ID or PR #ID

![image](https://user-images.githubusercontent.com/1255041/170813586-dbd1fbff-beac-4dce-ab72-74235fe34fa1.png)

Below code please paste to custom/templates/custom/footer.tmpl
```
<script>
!function(){var e,t,n;if((e=document.querySelector(".search"))&&(t=e.querySelector("button"))){var o,i,l=document.querySelector("input[name=q]"),r=document.querySelector(".form");if(t.type="button",r.addEventListener("submit",(function(e){""!=r.q.value&&e.preventDefault()})),l.addEventListener("keydown",(function(e){var t=l.value.trim(),n=t.match(/([\w/]+)#(\d+)/);if(13==e.keyCode&&t){if(""==t.replace(/[#0-9]/g,"")&&!i.disabled||-1!=t.indexOf("#"))return i.click();r.submit()}else n&&(i.disabled=!1)})),t.addEventListener("click",(function(){r.submit()})),(n=document.querySelector(".filter .blue.button.repo"))||document.querySelector(".page-content.repository"))o=n?n.title+location.pathname.replace("milestones","milestone"):location.pathname.replace("milestones","milestone"),i=t.cloneNode(),n&&!n.title&&(i.disabled=!0),i.type="button",i.textContent="#",i.title="#ID search",i.style.padding="10px",i.addEventListener("click",(function(){var e,t=l.value.trim(),n=t.match(/([\w/]+)#(\d+)/);return""==t.replace(/[#0-9]/g,"")?location=o+(t?"/"+t.replace("#",""):""):n&&n.length&&(e=document.querySelector("[title*='"+n[1]+"']",document.querySelector(".filter")))?location=e.title+location.pathname+(n[2]?"/"+n[2]:""):void r.submit()})),e.appendChild(i)}}();
</script>
```

**Comment by tyroneyeh** [comment]
Demo Video:
https://user-images.githubusercontent.com/1255041/170909636-02bfe3b3-85fb-4761-835e-d45cacb3ecdc.mp4

**Comment by tyroneyeh** [comment]
Demo Videos:

https://user-images.githubusercontent.com/1255041/170910170-c3f199ab-715b-4376-beb8-af69cbb35b40.mp4

**Comment by lunny** [comment]
> Demo Videos:
> 
>  hashtagsearch-2022-05-30_11.07.46.mp4

Looks interesting.

**Comment by nicorac** [comment]
> Could try the script to search issue #ID or PR #ID

That's great, and it works perfectly... till the function will be implemented in Gitea 😉
Thank you very much!

**Comment by tyroneyeh** [comment]
There are other options for this, but it's still a draft #19646

**Comment by yp05327** [comment]
I think what we need is `Go To #xxxx issue's page`, not `search issue by id`, it will cause a lot of problems in search algorism.
When I want to access a issue which I know the issue id, I will open another issue and edit the issue id in the url, then press `Enter`. This is not friendly I think.

@tyroneyeh's idea looks good to me. Can you create a PR ?

**Comment by tyroneyeh** [comment]
Hi @yp05327 

Please check #24479

**Comment by lunny** [comment]
We should follow GH to have a domain search language like `number:69` but not mix the keyword and the number.
