### ISSUE TITLE
Add option to exclude directories in diff (pull request)

### ISSUE THREAD

**Issue by jraats** [go-gitea/gitea#4111]
- Gitea version (or commit ref): 1.4.0
- Git version: 2.1.4
- Operating system: Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
We build a lot of GO code and include the vendor directory (go-dep). The diff of our pull requests are extremely large due all the files in the vendor directory. Is is possible to add a configuration in the app.ini to let Gitea know which directories to exclude? E.g. "./vendor"

**Comment by jraats** [comment]
How do you guys want to implement this? Is a global configuration via the INI file correct? Or is it better to implement this in specific project settings? Maybe I can look into it and create a PR :)

**Comment by lunny** [comment]
@jraats Please feel free to create a PR. Nobody are working on this now.

**Comment by jraats** [comment]
@daviian I agree bloat the repository settings too much is not a great idea!
If I'm not mistaken Github uses https://github.com/github/linguist to "detect blob languages, ignore binary or vendored files, suppress generated files in diffs, and generate language breakdown graphs". Gitea already suppresses binary data. I also would like to suppress vendored files in diffs. I think this works by using the "vendor.yml" file. When a file in the PR matches a regex in "vendor.yml" the file is omitted in the PR with the text "diff suppressed".

What do you think about building this functionality in Gitea? Loading vendor.yml in RAM and check if the file matches one of the known regexes. If the regex passes show "diff suppressed" with a link to explicit show the diff.

**Comment by daviian** [comment]
@jraats Great idea. There's also go port for githubs linguist available - https://godoc.org/github.com/generaltso/linguist. Perhaps we could use that.

**Comment by 42wim** [comment]
I've made an ugly hack for excluding the go vendor https://github.com/42wim/gitea/commit/171e795e861103b2f10662879f97d9a9d21e58fe
If you put "go" in the repo topic, it'll exclude the vendor completely (a downside is that the filenames aren't visible either).  

Unfortunately at the moment I don't have the time to actually make this into something decent.

**Comment by matheusmb** [comment]
Any updates on this? I would like to exclude/hide the Jest snapshots from the diff view

**Comment by mrsdizzie** [comment]
I will try and put up an initial PR for this soon

**Comment by lafriks** [comment]
Yes, it is, closing
