### ISSUE TITLE
Hello! Ride the wave!! (Re: MS + Github)

### ISSUE THREAD

**Issue by coolaj86** [go-gitea/gitea#4116]
![screen shot 2018-06-04 at 12 01 04 pm](https://user-images.githubusercontent.com/122831/40933564-172f1248-67ef-11e8-8593-01b67be09292.png)

A la https://github.com/go-gitea/gitea/issues/4108

Thousands making the exodus - It's time to shine!!

<small>
Sidenote:

Also, maybe something like this to make installing super easy?
https://git.coolaj86.com/coolaj86/gitea-installer.sh
</small>

**Comment by benyanke** [comment]
Or how about a docker quick-start? A one-liner which could allow someone to start tinkering with it on their workstation?

**Comment by techknowlogick** [comment]
@benyanke please see https://hub.docker.com/r/gitea/gitea/ for docker qiuckstart

**Comment by benyanke** [comment]
@techknowlogick I was even thinking right in the readme, for very rapid testing - I always appreciate that when I'm trying to decide between several projects. Perhaps something like:

```
Want to try it on your own system? Try it with docker!

1) docker run -p 3000:3000 gitea/gitea:latest
2) Visit `localhost:3000/install`
3) Scroll to the bottom and select `Install Gitea` (defaults will be fine for a test)
4) Create an account to login on your new git server!

Note: this is not production ready, only suitable for testing and tinkering. For more information, visit our Docker Hub repository: https://hub.docker.com/r/gitea/gitea/
```

**Comment by markuman** [comment]
And than all it needs to move from github to gitea https://git.osuv.de/m/move2gitea (works for me, maybe not sufficient for you)

**Comment by denji** [comment]
@markuman + https://github.com/silky/clone-all

**Comment by techknowlogick** [comment]
Closing this now. Feel free to make specific PRs for the comments above.
