### ISSUE TITLE
How to pronounce Gitea?

### ISSUE THREAD

**Issue by coolaj86** [go-gitea/gitea#4118]
Can you tell me how to pronounce this?

1. Gitty
0. Gih-tee
0. Git-tee
0. Gih-tee-a
0. Gitty-uh
0. Gittee-uh

Audio samples of me trying: https://youtu.be/YtmFGp4DbV8

I'm making a Screencast on how to migrate to Gitea.

**Comment by techknowlogick** [comment]
I can't answer for others, but after watching the youtube video both 2 & 3 are ways that I pronounce it. As it is supposed to be a combination of Tea, and Git I think 4,5&6 can be excluded as the drink tea doesn't have an additional sound at the end.

**Comment by axifive** [comment]
I think that the third

**Comment by techknowlogick** [comment]
ping @thehowl as you had feedback for this on Discourse: https://discourse.gitea.io/t/how-to-pronounce-gitea/161

**Comment by coolaj86** [comment]
I think that's what I went with: [How to Migrate to a Microsoft Github Alternative: Gitea](https://youtu.be/dTvTBlzKqgg)

**Comment by coolaj86** [comment]
I won't be offended if this doesn't get added, but just a thought to help with branding: Add pronunciation to README.md https://github.com/go-gitea/gitea/pull/4123

## FAQ

**How do you pronounce Gitea?**

Gitea is pronounced [/ɡɪ’ti:/](https://youtu.be/EM71-2uDAoY) as in "gi-tea" with a hard g.
