### ISSUE TITLE
Where is default admin password?

### ISSUE THREAD

**Issue by zloidemon** [go-gitea/gitea#4120]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ X] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X ] Not relevant
- Log gist:

## Description

Hello, after installation into docker by compose i still don't understand how to login into admin panel. Google didn't help me find default admin password on your web site.

**Comment by l0go** [comment]
Just use the password for the first account you made

**Comment by techknowlogick** [comment]
@zloidemon There is no default password during the install process you would be prompted to create a user, otherwise the first user registered to Gitea becomes the admin.

**Comment by zloidemon** [comment]
@techknowlogick thank you. Found at bottom on the install page. I seem better add checking that form before installing with modal window to avoid installation.

**Comment by lqhuang** [comment]
Hey. But if I have set `DISABLE_REGISTRATION=true` from docker environment, how can I login as `admin`? I can't create a new user. And `localhost:3000/install` page is not available (`404`) to access.

**Comment by zeripath** [comment]
Use the command line tool `gitea admin create-user`. Ensure you have set the config values correctly in particular the -c option for the app.ini.

See https://docs.gitea.io/en-us/command-line/

**Comment by lqhuang** [comment]
@zeripath Thanks. Yeah, for now, I did this to initialized manually after creating docker successfully. But it still need do some extra "hack in" work, which cannot left everything in a single `yaml` configuration.

In `docker-compose`, there is still no `post-run`/`postUp`/`onrun` feature to execute custom action after container is ready. I think that is a much better way to initialize. See [docker-compose issue#1510](https://github.com/docker/compose/issues/1510) and [docker-compose issue#1809](https://github.com/docker/compose/issues/1510) for more discussions.

or let `gitea` add a specific process to handle this `DISABLE_REGISTRATION=TRUE` case.
