### ISSUE TITLE
Discord Oauth2 support

### ISSUE THREAD

**Issue by l0go** [go-gitea/gitea#4125]
Read the title!

**Comment by chaoticryptidz** [comment]
I want this so bad.

**Comment by sinni800** [comment]
Gotta upgrade goth first, then it seems easy to add. The current vendored goth is too old.

**Comment by techknowlogick** [comment]
@sinni800 I've just updated Goth in my linked PR, can you try it out?

**Comment by sinni800** [comment]
Oh I completely oversaw the PR that you made. That changed pretty much the same things so it would work just fine.
