### ISSUE TITLE
Filter by topic not possible

### ISSUE THREAD

**Issue by shelweg** [go-gitea/gitea#4136]
- Gitea version (or commit ref): latest master 05-Jun-2018
- Git version: 
- Operating system: Window 7 Pro
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL) https://try.gitea.io/explore/repos
  - [ ] No
  - [ ] Not relevant

## Description

topics are not clickable in repo overviews, so you have no chance to filter the shown repos by topic
this seems to be consistent on all repo lists. 
- All repo overview (or explore view): https://try.gitea.io/explore/repos
- Organiszation's repository overview: https://try.gitea.io/go-gitea

## Screenshots
![grafik](https://user-images.githubusercontent.com/8866579/40984383-10454e2c-68e2-11e8-8cbe-bff1725a8157.png)
![grafik](https://user-images.githubusercontent.com/8866579/40984934-47cc6104-68e3-11e8-9b15-6a324f7801db.png)

**Comment by axifive** [comment]
I also noticed and already started working on this.

**Comment by axifive** [comment]
Created a new icon for the topic category: [figma](https://www.figma.com/file/oVspE6bI2ZVKi1dKKrn1ZN/Octicons-Plus?node-id=3694%3A17)

![topic 1](https://user-images.githubusercontent.com/844963/41202831-847913ca-6cd7-11e8-8581-987297e9e516.png)

**Comment by lunny** [comment]
closed by #4505
