### ISSUE TITLE
[Feature Request] Password protected repos

### ISSUE THREAD

**Issue by BNolet** [go-gitea/gitea#4138]
I'd like to be able to create a private repo and give conditional access to individuals by giving them the password and the link.

Happy to provide guidance on implementation if required.

**Comment by UnnoTed** [comment]
Source code encryption would be cool too...

**Comment by axifive** [comment]
@BNolet, As a workaround, you can create new User and add it as collaborator with **Read** permissions. And then post the link with username and password.

**Comment by BNolet** [comment]
@axifive I'll use that for now, thanks for the tip :)

**Comment by BNolet** [comment]
@UnnoTed Not entirely sure what the point of that would be. Besides, you could encrypt it locally then commit the encrypted version

**Comment by UnnoTed** [comment]
@BNolet The idea is to host important code on untrusTed places, like a cheap vps... Encrypting it before a commit would lose the point of using git.

**Comment by techknowlogick** [comment]
Gitea doesn't have this at the current moment, but I use keybase.io for all my encrypted git needs.

**Comment by BNolet** [comment]
@UnnoTed Damn I feel dumb

**Comment by BNolet** [comment]
What is kind proposal compared to kind feature?
