### ISSUE TITLE
SSH_PORT setting does not change clone url

### ISSUE THREAD

**Issue by wucke13** [go-gitea/gitea#4139]
- Gitea version: 1.3.2 Docker
- Git version: built-in
- Operating system: linux86_64
- Database:
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant

## Description

When setting the SSH_PORT to 7022, the ssh port displayed in the clone URL still keeps unmentioned (`git@git.domain.tld:user/repo.git`).
Relevant lines from my `docker-compose.yml`:
```
      - START_SSH_SERVER=true
      - SSH_PORT=7022
      - SSH_LISTEN_PORT=22
```
What am I missing?

**Comment by techknowlogick** [comment]
@wucke13 are those environment variables you are using in your docker compose? Please see list of docker environment variables that are supported: https://docs.gitea.io/en-us/install-with-docker/

**Comment by techknowlogick** [comment]
@wucke13 what does your app.ini say in regards to those settings?

Edit: 1.4.2 is the latest version and may have some fixes that aren't in 1.3.2

**Comment by wucke13** [comment]
From `app.ini`:
```
SSH_PORT         = 22
```
However, since that is under the `[server]` section, im unsure whether it references the port of the ssh server or the port displayed in GUI? 

Regarding the version: Under [https://hub.docker.com/r/gitea/gitea](https://hub.docker.com/r/gitea/gitea/) the user is advised to user version *1.3.2*, under [https://docs.gitea.io/en-us/install-with-docker/](https://docs.gitea.io/en-us/install-with-docker/) to use *latest*. Which one ist the way to go?

Furthermore, *latest* in docker hub does not resolve to *1.4.2*.

**Comment by lafriks** [comment]
Latest in docker is from master branch. For stable releases it is recommend to use 1.4 docker tag

**Comment by wucke13** [comment]
Thanks @lafriks . I think it would be good to communicate that on both of the pages I linked.
I changed my `docker-compose.yml` to tag `1.4`, however the error still persists.

I changed the value `SSH_PORT` from `22` to `7022`. That did the trick. For further reference, this settings corespondents to the port displayed in the UI, not the port the internal ssh server uses.
