### ISSUE TITLE
[...tea/models/update.go:147 PushUpdate()] [E] updateIssuesCommit: strconv.ParseInt: parsing "issuecomment-328479278": invalid syntax

### ISSUE THREAD

**Issue by AloisMahdal** [go-gitea/gitea#4141]
- Gitea version (or commit ref): 1.1.0 
- Git version: 2.14.4
- Operating system: Debian 9 (server), Fedora 27 (client)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

Got this when pushing to a new repo:

    $ git push --set-upstream gvc master 
    Counting objects: 109, done.
    Delta compression using up to 8 threads.
    Compressing objects: 100% (55/55), done.
    Writing objects: 100% (109/109), 16.17 KiB | 8.09 MiB/s, done.
    Total 109 (delta 54), reused 107 (delta 54)
    remote: Resolving deltas: 100% (54/54), done.
    remote: 2018/06/05 18:37:07 [...tea/models/update.go:147 PushUpdate()] [E] updateIssuesCommit: strconv.ParseInt: parsing "issuecomment-328479278": invalid syntax
    To gitea.vornet.cz:netvor/slop-copr-build.git
     * [new branch]      master -> master
    Branch master set up to track remote branch master from gvc.

The mentioned string can be indeed found in one of commit messages:

    cxxopts needs less ancient gcc

    Ref.: https://github.com/naelstrof/slop/issues/86#issuecomment-328479278

It looks like some hook tries to parse `#issuecomment-328479278`; from
inside of URL as issue reference.

The push seems to have succeeded, though.

**Comment by techknowlogick** [comment]
@AloisMahdal I know you marked as "not relevant" in regards to try.gitea.io, however your issue may have been fixed in a version that is more recent than 1.1.0. Could you try to replicate on try.gitea.io?

Thanks,
@techknowlogick

**Comment by AloisMahdal** [comment]
Sorry for being sloppy :-)

I tried it with the test instance: `fa3ceb6`.  Indeed, the error message is not reproduced there.

**Comment by techknowlogick** [comment]
@AloisMahdal excellent. In that case I'm going to close this as there have been many commits to gitea since version 1.1.0, and upgrading means you'll get a lot of new features and bug fixes.

Please feel free to open more issues, and also ask on the forum for support questions: https://discourse.gitea.io/
