### ISSUE TITLE
New Field Request: Ability to set Profile Pic with LDAP

### ISSUE THREAD

**Issue by benyanke** [go-gitea/gitea#4144]
It would be neat to be able to set profile picture with LDAP. I suppose this would be best implemented as a URL, but I know there are multiple ways of implementing images in ldap.

**Comment by tcs-ulli** [comment]
gogs can this maybe its easy to copy that feature ?

**Comment by lunny** [comment]
@tcs-ulli could you point where is the code base?

**Comment by mq2035** [comment]
In openldap attribute name is jpegPhoto (from inetOrgPerson), it is binary and it is stored in LDAP.

working code example (in java)
https://github.com/xwiki-contrib/ldap/tree/master/ldap-authenticator

**Comment by dl5rcw** [comment]
Using fusiondirectory, the jpegPhoto as mentioned by @mq2035 really makes sense. It should be updated like the other entries to pull changes from ldap.

**Comment by helmut72** [comment]
Yes, would be good, as I have stored jpegPhoto in my Samba4/LDAP server. Many Applications use the photo from LDAP server, which makes sense.

**Comment by lafriks** [comment]
Only problem could be with sync, how to check and download images only if they have been changed to not download all user images on every sync

**Comment by benyanke** [comment]
That would be an additional piece needed. Most apps I've seen do it on individual login, and then refetch on an administrator's cache clear, or when a scheduled job runs.

**Comment by helmut72** [comment]
> Only problem could be with sync, how to check and download images only if they have been changed to not download all user images on every sync

Let the user decide in his settings.

**Comment by lafriks** [comment]
I was just thinking if there is more optimal way to check if image has changed

**Comment by helmut72** [comment]
It would be a good start if there is just a `sync every x day/hour` setting with 0 to disable. Then it's the administrators choice. Better than no ldap photo sync.

**Comment by nedvedad** [comment]
Or check/download avatar on each user login.

**Comment by SonGokussj4** [comment]
Any chance for me to try that in Docker? I'm using v1.15.0 docker image. (centos 7) Can't try this as local installation.

**Comment by zeripath** [comment]
OK I've pushed up a docker image based on 1.16 (v1.16.0-dev-195-gd01836f4f) - this PR can't be backported to 1.15 without significant work (and as it would be a feature would be unlikely to be merged.)

https://www.eldritchkitty.com/~andrew/gitea-1.16.0-dev-195-pr-16851.tar.gz

if the image needs updating please discuss with me on discord or matrix. Similarly if a backport to 1.15 is wanted.

**Comment by SonGokussj4** [comment]
Okay so if I want to just try that and then go back I should **not** just rename image in docker-compose.yml from gitea:1.15 to gitea:1.16-dev (as I renamed your docker) (and there back to 1.15)

I should stop my current Gitea instance, copy folder with data and try your docker image on that?

**Comment by zeripath** [comment]
Ah you want to use your current data!

You would need to backup or copy your db as there are some database migrations.

(There's a small bug in 1.15.0 dump which will break login_source so you would need to use your db backups or wait for 1.15.1 - which is imminent)

**Comment by SonGokussj4** [comment]
I would try that in production in my company so... To be safe, I will wait :-) So when 1.15.1 is out, I will update to that, then try to use your 1.16.0-dev, report functionality, then I can go back to 1.15.1?

**Comment by SonGokussj4** [comment]
1.15.1 here. Should I wait for your docker build and go back to 1.15.1 after I try it? Or I have to duplicate my environment and try that on duplicated DB to be sure.

**Comment by zeripath** [comment]
You will need to back up your db, duplicate it and use the image I provided above. 

The reason is that once you use a 1.16-dev build your db is migrated and so you would not be a able to go back to 1.15.

**Comment by SonGokussj4** [comment]
Finally at work. Did try your image but error happened. Are you sure (did you try it?) it works?

```
# I've imported your image
docker import https://www.eldritchkitty.com/~andrew/gitea-1.16.0-dev-195-pr-16851.tar.gz

# Renamed
docker image tag b63236d14157 gitea/gitea:1.16.0-dev

# Modified docker-compose.yml
services:
  server:
    image: gitea/gitea:1.16.0-dev

# Started
$ docker-compose up
gitea_ldap_test_db_1 is up-to-date
Creating gitea_ldap_test_server_1 ... error

ERROR: for gitea_ldap_test_server_1  Cannot create container for service server: b'No command specified'

ERROR: for server  Cannot create container for service server: b'No command specified'
ERROR: Encountered errors while bringing up the project.
```

**Comment by zeripath** [comment]
Sigh.

Works for me.

**Comment by SonGokussj4** [comment]
Docker inspect gitea/gitea:1.16.0-dev, it will give me {"Config": {"Cmd": null, ...}, ...}
When I googled the problem it gave me "you have no Cmd in dockerfile".

**Comment by zeripath** [comment]
It'll be the way it was exported. Clearly `docker export` did not work and is not the correct thing to do. I'm not certain how to make that work properly.

I have pushed up an xz compressed binary to https://www.eldritchkitty.com/~andrew/gitea-v1.16.0-dev-219-g4b6e023a1-pr-16851-linux-amd64.xz which once decompressed you can use to replace the /app/gitea/gitea binary within a working docker.

**Comment by SonGokussj4** [comment]
Thanks. I copied it to a running container and there is a new field "Avatar Attribute" and entered "thumbnailPhoto"

My `ldapsearch -x -W -D xxx` shows:

```
mail: mymail@MYCOMPANY.CZ
mobile: +420123456789
thumbnailPhoto:: /9j/4AAQSkZJRgABAQEA8ADwAAD/4R1kRXhpZgAATU0AKgAAAAgACwEPAAIAA
 AASAAAAkgEQAAIAAAAKAAAApAEaAAUAAAABAAAArgEbAAUAAAABAAAAtgEoAAMAAAABAAIAAAExAA
...
```

- Updated Authentication Source. 
- Tried logout, login
- Tried `Admin --> Monitoring --> Synchronize external user data`
- Tried to change from `User Profile --> Avatar --> Look Up Avatar by Email Address` to `Use Custom Avatar` and back

Still the random avatar. What should I do so that it will pull it out from LDAP?

https://i.imgur.com/zA2LxYh.png

**Comment by zeripath** [comment]
hmm... the avatar was only being updated if something else was updated on the user - I've changed that.

The other question is whether your ldap is giving us the data as []byte or as a base64 encoded string. If it's the latter then it's not currently handling that.

https://www.eldritchkitty.com/~andrew/gitea-v1.16.0-dev-225-g929885e0c-pr-16851-linux-amd64.xz

**Comment by SonGokussj4** [comment]
If I enter my `thumbnailPhoto` into https://codebeautify.org/base64-to-image-converter, it gives me my picture. So I think (and I can't change that) it's base64.

**Comment by zeripath** [comment]
@SonGokussj4 did you try the update above?

**Comment by SonGokussj4** [comment]
Hi. No I didn't. We use base64 for image and you wrote it doesn't handle the base64 so I didn't even try.

**Comment by zeripath** [comment]
I don't think you can assume that you're using base64 from that output. If you look at your output above:

```
thumbnailPhoto:: /9j/4AAQSkZJRgABAQEA8ADwAAD/4R1kRXhpZgAATU0AKgAAAAgACwEPAAIAA
 AASAAAAkgEQAAIAAAAKAAAApAEaAAUAAAABAAAArgEbAAUAAAABAAAAtgEoAAMAAAABAAIAAAExAA
...
```

There is a double `:` after the field's name. That could imply that the object is stored as []byte but it's being rendered as base64. My code explicitly asks for the bytes. Now you were previously expecting synchronization to occur - it wasn't because of an oversight - but it does happen now. So it would be helpful to know if my interpretation above is correct or if I have to read the data and detect it's base64 and then do a conversion.

Because if I have to convert for you - it is very likely that there will have to be conversions for others. 

If I don't then that's fine and I can save 200 lines of code messing around with dealing with this issue.

**Comment by SonGokussj4** [comment]
That makes sense. Thanks for the explanation. 
I'll try that right away.

**Comment by SonGokussj4** [comment]
So I updated the file, restarted gitea `docker-compose restart`, entered `thumbnailPhoto`, then tried log-out, log-in, synchronize data, nothing.
Then I downed docker `docker-compose down` and started it again `docker-compose up -d`, logs show me this:

```
server_1  | Downgrading database version from '194' to '189' is not supported and may result in loss of data integrity.
server_1  | If you really know what you're doing, execute `UPDATE version SET version=189 WHERE id=1;`
server_1  | Received signal 15; terminating.
gitea_ldap_test_server_1 exited with code 0
```

**Comment by zeripath** [comment]
OK I think I've got it working completely now! (Discovered our test ldap actually had jpegPhoto attributes already so was able to use that.) I wasn't actually passing the attribute to the LDAP request.

https://www.eldritchkitty.com/~andrew/gitea-v1.16.0-dev-261-ga3e051a30-pr-16851-linux-amd64.xz

**Comment by SonGokussj4** [comment]
Hi, sorry for the delay, I wasn't at work till now. And...

**It WORKS!!**

I had to do `Monitoring -> Synchronize external user data` but I think the newly added user should have his picture there. Will through today.
