### ISSUE TITLE
Unable to update Avatar E-Mail address

### ISSUE THREAD

**Issue by DasLeo** [go-gitea/gitea#4147]
- Gitea version (or commit ref): 1.4.2
- Git version: 2.17.0
- Operating system: Ubuntu 18.04 from LXD Container Image
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description

Whenever I try to change my mail address to be compatible with my gravatar, I'm getting an error:
```Uploaded file is not a image.```
...

## Screenshots
![image](https://user-images.githubusercontent.com/3002846/41020439-2bc85bd6-6963-11e8-9fe6-7734a2bf80c8.png)

**Comment by daviian** [comment]
@DasLeo You've already noticed that this is fixed in latest master, so it will be in version 1.5

@lafriks ~Should we backport https://github.com/go-gitea/gitea/pull/3988 ?~ Nevermind ;-) Too late now as we are releasing 1.5 soon anyway

**Comment by DasLeo** [comment]
Thanks for the fast response, issus is closed now.
Just a few days to wait.
