### ISSUE TITLE
Allow a team access to all repositories

### ISSUE THREAD

**Issue by mrichar1** [go-gitea/gitea#4153]
-  Gitea version (or commit ref):fa3ceb6
- Git version: 1.8.3.1
- Operating system: try.gitea.io
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

Is there a way in which a team can be set up such that it automatically has write access over all repos, including ones yet-to-be-created?

Alternatively, can there be a way to bulk-add repos to the team rather than having to add them through the auto-complete form? And/or have a way to add teams to a repo, similar to the `Collaboration` tab in the repo settings?

**Comment by lunny** [comment]
We could add an option on team settings to automatically add repository and for an owner it's default true and other team default false to keep compatible with old version.

**Comment by lunny** [comment]
duplicated with #3642
