### ISSUE TITLE
Issue options is displaced when label is added

### ISSUE THREAD

**Issue by anikdas012** [go-gitea/gitea#4154]
- Gitea version (or commit ref): 1.3.0
- Git version: 2.7.4
- Operating system: Ubuntu 16.04 LTS
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

- When an issue is opened, the Labels/Milestone/Assignee options appear on the right side of the description box. (See attachment 1)
- After issue title and description have been written and the issue has been created, the options still appear on the right side. (See attachments 2)
- If a newly created issue is opened for editing, the options section still appears on the right. (See attachment 3) But, then, if any label is selected, the section comes down below the comment box and stays there. (See attachment 4)

This makes it very hard to check the labels, the milestones and―most importantly―the person assigned because there are always a lot of comments in between. Scrolling down for long periods is uncomfortable.

## Screenshots

![capture_1](https://user-images.githubusercontent.com/17808161/41045684-a7203d32-69ca-11e8-9e8f-5f85314da802.png)
![capture_2](https://user-images.githubusercontent.com/17808161/41045687-aa927d04-69ca-11e8-976e-e1fb2668a345.png)
![capture_3](https://user-images.githubusercontent.com/17808161/41045689-ac2ae12e-69ca-11e8-9b40-a35035de86f4.png)
![capture_4](https://user-images.githubusercontent.com/17808161/41045695-afd950a8-69ca-11e8-834d-4402b942a6cf.png)

**Comment by lafriks** [comment]
Can you reproduce that also on https://try.gitea.io/? For me on latest 1.4.2 version it seems to be working correctly

**Comment by lunny** [comment]
Please feel free to reopen it.
