### ISSUE TITLE
Different url for repository

### ISSUE THREAD

**Issue by phasianus** [go-gitea/gitea#4155]
- Gitea version (or commit ref): 1.4
- Git version:
- Operating system: Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

I should be nice to configure different url for repository - not only automatic generated. F.e.: URL for amins/wiki/browse... : http://server1.com/gitea, url for client access http://server1.com/gitea/repository...

Why? I should be able to configure different authentication scheme for web acesss and git clients access.

Maybe it is possible, but I am not able to find it - sorry th case.

**Comment by lunny** [comment]
It's some difficult to do.

**Comment by phasianus** [comment]
I do not know the code. But I think it is useful. Like GlitBlit: there are alternative url in config file and git url for clients are constructed against these urls.
