### ISSUE TITLE
Allow migration from Subversion

### ISSUE THREAD

**Issue by jmckenna** [go-gitea/gitea#4158]
It would be nice to support migrating from an SVN repository.  An example repository: https://svn.osgeo.org/osgeo/foss4g/

(background: the [OSGeo foundation](https://osgeo.org) leveraged subversion for many years, and much information is still stored there)

**Comment by HaasJona** [comment]
I suggest you follow this tutorial instead: https://www.atlassian.com/git/tutorials/migrating-overview

And then just import the resulting git repo into Gitea.

Automatically converting an SVN repository is not easily implemented, as you probably want to map SVN user names to longer Git user names and add e-mail addresses to them for example.

**Comment by lunny** [comment]
I have ever converted all SVN repos to git repos by some scripts and then write a script via Gitea's API to import to Gitea.

**Comment by Morlinest** [comment]
@jmckenna It is better to convert SVN repositories yourself, using git-svn for example (git svn clone). If you are using standard structure, it's very easy. There are almost always some steps you should do (e.g. resolving authors). Every SVN can be used in different way, so there are more ways to convert it (some of them can takes days to do so).

IMO Gitea should focus (at least for now) on storing git repositories and improve services around them, not converting another SCM types to git. But PR's are welcomed :)
