### ISSUE TITLE
Gitea webui do not refresh after first push, and never refresh status of repo

### ISSUE THREAD

**Issue by HotMykeul** [go-gitea/gitea#4159]
- Gitea version (or commit ref): 809babb (docker latest image)
- Git version: git version 2.15.2 (server side), git version 2.11.0 (client side)
- Operating system: OMV4 (debian 9), Docker version 18.03.1-ce, build 9ee9f40
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:
https://gist.github.com/HotMykeul/a56a4f745bea9c6da8e4abe3e853b679

## Description
After a push of a repository test created from the webui, cloned to a client, modified and pushed commit, when I want to see changes in the webui, nothing is refreshed:
![image](https://user-images.githubusercontent.com/1063311/41055166-cdf7ed42-69c0-11e8-839f-ec2e56efe635.png)

(I push over https protocol through a nginx - letsencrypt reverse proxy)
It seems I have no error in xorm.log (only select in db) and only one error in gitea.log related to bad password (typing error)
I can clone again the repository, all tree is here so gitea handle correctly the push.
The problem is just the webui

**Comment by lafriks** [comment]
Check if your partition where git repositories are stored does not have noexec flag. You can check it by running `cat /proc/mounts` on docker server.

**Comment by HotMykeul** [comment]
Thank you it work now.
