### ISSUE TITLE
project.issues.git

### ISSUE THREAD

**Issue by a7hybnj2** [go-gitea/gitea#4160]
Provide functionality similar to project.wiki.git for issues as well.  
Make project.issues.git a stand alone repo to easy pull and manage issues.

**Comment by kolaente** [comment]
With each issue in a seperate folder with markdown files for comments and such?

**Comment by a7hybnj2** [comment]
Popular request: Export issues to Excel and/or generate PDF #4808

I like the idea of making the issues a git repo because then you could pull and manage them just like wiki or main repo. Better than exporting to PDF like #4808

**Comment by lunny** [comment]
@a7hybnj2 It's difficult to do that since all issues are stored in database.

**Comment by lafriks** [comment]
I'm setting this as won't fix because of current architecture I don't see how this could be implemented via git protocol
