### ISSUE TITLE
​Issue label names missing in timeline and break-down after too many changes

### ISSUE THREAD

**Issue by anikdas012** [go-gitea/gitea#4169]
- Gitea version (or commit ref): 1.3.0
- Git version: 2.7.4
- Operating system: ubuntu 16.04 LTS
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

- After every new change in an issue label, an entry is added below the issue description box. But the entries are missing the label names. The highlighted space for label name shows the time instead. (See attachment 1)

- After another label change, the next entry in the timeline/event is placed pretty far to the right. (See attachment 2)

- Every time there is a change in label assignment, a new entry is added to the right of the previous one, and the Labels/Milestone/Assignee section shifts to the right as well, and the comment section gets shrunk. (See attachment 3)

- As more changes are performed, the comment section shrinks even more (see attachment 4), and eventually the section breaks down and goes outside the screen (see attachment 5).

## Screenshots

![capture_1](https://user-images.githubusercontent.com/17808161/41081624-62e8375e-6a4d-11e8-81f2-7378a8c952be.png)
![capture_2](https://user-images.githubusercontent.com/17808161/41081626-640b14c6-6a4d-11e8-8c5e-e11aa235d275.png)
![capture_3](https://user-images.githubusercontent.com/17808161/41081628-668a7b10-6a4d-11e8-8abd-17451975f13c.png)
![capture_4](https://user-images.githubusercontent.com/17808161/41081630-67b375be-6a4d-11e8-9041-e7c7ff570784.png)
![capture_5](https://user-images.githubusercontent.com/17808161/41081631-69433af4-6a4d-11e8-8544-73e6d996daf5.png)

**Comment by lafriks** [comment]
I can not reproduce that in latest version, please upgrade to 1.4.2
