### ISSUE TITLE
Written permission for use of "Git" in "Gitea" and "Git merge logo" in the "Teacup merge logo"

### ISSUE THREAD

**Issue by coolaj86** [go-gitea/gitea#4175]
https://git-scm.com/about/trademark

> ... you may not use any of the Marks as a syllable in a new word or as part of a portmanteau (e.g., "Gitalicious", "Gitpedia") used as a mark for a third-party product or service without Conservancy's written permission. For the avoidance of doubt, this provision applies even to third-party marks that use the Marks as a syllable or as part of a portmanteau to refer to a product or service's use of Git code.

trademark@sfconservancy.org is cited as the relevant contact for asking permission.

I'd like to use gitea in a product offering. As such, I'd like to make sure that Gitea has the proper permission to use the "Git" mark and "Git merge logo" image.

(In turn, I'd also like to request permission from Gitea to use its mark and logo)

Given the great number of projects that integrate the "Git" mark and "Git merge" logo, I would hope this is not a problem, but I want to make sure that things are cleared.

Has someone already gotten permission for this project?

**Comment by jorng** [comment]
Interesting... the Git trademark policy for the logo seems to be in direct contention with the licensing of the artwork: [CC BY 3.0](https://creativecommons.org/licenses/by/3.0/)

**Comment by dg01d** [comment]
The Gitea logo is of a teacup, with a merge icon displayed:-

<img width="89" alt="screen shot 2018-06-24 at 17 21 26" src="https://user-images.githubusercontent.com/1061809/41821092-71d3b5d4-77d3-11e8-8e69-4f95ef7c7077.png">

Whereas the Git-SCM logo is:

<img width="57" alt="screen shot 2018-06-24 at 17 21 58" src="https://user-images.githubusercontent.com/1061809/41821096-820f2ff0-77d3-11e8-837e-079644d89326.png">

The two are clearly different logos, more importantly, a google image search for "Merge Icon" or "Fork Icon" throws up hundreds of instances of similar iconography, mostly consisting of a sequence of dots joined by lines.

I think in the absence of good evidence supporting Git-SCM's claims, there is nothing to be concerned about regarding the use of such an icon in the Gitea Logo.

**Comment by lafriks** [comment]
I did contact them half year ago but did not get any response. Closing issue
