### ISSUE TITLE
Can not suport git revision version contains '-' 

### ISSUE THREAD

**Issue by duffiye** [go-gitea/gitea#4178]
- Gitea version (or commit ref): v1.4
- Git version: 2.18.0-rc1
- Operating system: centos 6
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

         2018/06/08 03:57:01 [...s/setting/setting.go:890 NewContext()] [E] Error parsing git revision version: strconv.ParseUint: parsing "0-rc1": invalid syntax

## Description

Can not suport git revision version contains '-' ;

     	revisionVersion, err := strconv.ParseUint(splitVersion[2], 10, 64)
		if err != nil {
			log.Fatal(4, "Error parsing git revision version: %v", err)
		}

maybe can do it like this:

         revisionVersion, err := strconv.ParseUint(strings.SplitN(splitVersion[2], "-", 1), 10, 64)

**Comment by duffiye** [comment]
rv := strings.SplitN(splitVersion[2], "-", 2)
                log.Info(rv[0])
                revisionVersion, err := strconv.ParseUint(rv[0], 10, 64)

**Comment by 6543** [comment]
should be the case now, feel free to ask for reopen if you have still issues with it
