### ISSUE TITLE
JavaScript error when Uploading a file via Webinterface

### ISSUE THREAD

**Issue by BeryJu** [go-gitea/gitea#4179]
- Gitea version (or commit ref): 1.3.2 (Debian package 1.3.2+dfsg-3)
- Git version: 2.17.1
- Operating system: Debian unstable
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:
https://gist.github.com/BeryJu/c24cc44ef68dbabafb36d6e9de71d12e
## Description

When I try to upload a file via the Webinterface, just a blue box appears: 
![grafik](https://user-images.githubusercontent.com/1932513/41149327-997e4c9a-6b0b-11e8-9a5b-f03193549878.png)

If I look into the Browser Developer console, it tells me this:
![grafik](https://user-images.githubusercontent.com/1932513/41149395-b9bba764-6b0b-11e8-96a8-f7960e2b43bd.png)

This seems to indicate that vue.js is running development mode for some reason, even though my settings file has `RUN_MODE = prod` set.

FYI: I am also running Gitea behind an apache2 Reverse Proxy for Let's Encrypt. This shouldn't impact this behavior in any way.

**Comment by lunny** [comment]
Is this still a problem?

**Comment by BeryJu** [comment]
I haven't used gitea much since I opened this bug, so cannot confirm that this bug still exists.
