### ISSUE TITLE
Upgrade from windows 386 to amd64

### ISSUE THREAD

**Issue by T100D** [go-gitea/gitea#4180]
- Gitea version (or commit ref): 1.4.2
- Git version: 2.17.1.windows.2
- Operating system: Windows 10
- Database:
  - [X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes

## Description

Wen we replace the gitea-1.4.2-windows-4.0-386.exe file with the gitea-1.4.2-windows-4.0-amd64.exe file to from 32bit to 64 bit, the repository is empty and a new administration account is deployed.

The old data is not present anymore. 

When we go back to the 32bit version of gitea, the repository and accounts are back again.

Is ther a way to upgrade to the 64 bit version without losing data?

**Comment by lafriks** [comment]
check that your data is not saved in system32 folder (32-bit vs 64-bit will have different (System32 vs SysWOW64). You need to reconfigure gitea to use other folders not system ones.

**Comment by T100D** [comment]
Thank you @lafriks.
Thit solved the problem. Now the db is in c:\gitea\data\, and we changed this in the config file.
