### ISSUE TITLE
Markdown: URL is rendered incorrectly if name starts with @

### ISSUE THREAD

**Issue by tastytea** [go-gitea/gitea#4186]
- Gitea version (or commit ref): 1.4.2
- Git version: 2.16.4
- Operating system: Gentoo Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description

I want to put this link in a markdown file: `[@tastytea@soc.ialis.me](https://soc.ialis.me/@tastytea)`.
On my instance, this link is rendered to https://schlomp.space/tastytea/tastytea@soc.ialis.me as can be seen here: https://schlomp.space/tastytea/test

On [try.gitea.io](https://try.gitea.io/tastytea/fediverse-url/src/branch/master/README.md) the link is rendered correctly. I couldn't find an issue or a commit message between 1.4.2 and now referring to this problem.

**Comment by tastytea** [comment]
upgrading to 1.5.0_rc1 solved this.

**Comment by ghost** [comment]
@tastytea can this issue be closed then?

**Comment by tastytea** [comment]
That's fine by me.
