### ISSUE TITLE
When clicking on label selector while filling an issue and selecting no label, it reloads the page completely

### ISSUE THREAD

**Issue by dolanor** [go-gitea/gitea#4190]
- Gitea version (or commit ref): 1.4.0+rc2-5-gc0e0fb7
- Git version: 2.7.4
- Operating system: Linux (docker container)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

https://try.gitea.io/dolanor/lol/issues/1
press labels to select 1, but don't select any and click somewhere else. The page will reload fully.

**Comment by lafriks** [comment]
It is currently expected behaviour when adding label or assignees to existing issue/pr

**Comment by wxiaoguang** [comment]
That's a really annoying problem, more details in 

* https://github.com/go-gitea/gitea/issues/17705

I think this one could be closed.
