### ISSUE TITLE
When issue has pictures uploaded, each page refresh fully download pictures instead of using cache

### ISSUE THREAD

**Issue by dolanor** [go-gitea/gitea#4191]
- Gitea version (or commit ref): 1.4.0+rc2-5-gc0e0fb7
- Git version: 2.7.4
- Operating system: Linux (docker container)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

The images uploaded to an issue in gitea don't seem to be cached and are downloaded again every time we reload the page.

You can check it for yourself here: https://try.gitea.io/dolanor/lol/issues/1#issuecomment-3469

## Screenshots

![capture du 2018-06-09 00-27-35](https://user-images.githubusercontent.com/928722/41183629-0d0b98e6-6b7c-11e8-9d53-42d3841708e9.png)

**Comment by adelowo** [comment]
Whoops

**Comment by wxiaoguang** [comment]
The cache should work fine now.


![image](https://user-images.githubusercontent.com/2114189/177243353-bd868e1a-3710-4c2f-adb6-f9b24f50860d.png)

![image](https://user-images.githubusercontent.com/2114189/177243489-f2dedb40-acc0-4676-81ed-9686f8e65640.png)
