### ISSUE TITLE
File Upload Limit on macOS cannot be changed

### ISSUE THREAD

**Issue by T100D** [go-gitea/gitea#4199]
- Gitea version (or commit ref): 1.4.2 built with: bindata, sqlite
- Git version: git version 2.15.1 (Apple Git-101)
- Operating system: macOS 10.13.5 Sierra
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ X ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ X ] No
  - [ ] Not relevant
- Log gist:
Nothing in de logs, changed levels to Trace

## Description

When uploading a file the 3MB limit keeps up even when the settings are changed.

## from app.ini:

[attachment]
ENABLE = true
PATH = data/attachments (tried an absolute path even so)
ALLOWED_TYPES = */*
MAX_SIZE = 10
MAX_FILES = 5

## Screenshots
https://user-images.githubusercontent.com/12442261/36669190-546102cc-1af4-11e8-943a-71011e001527.jpg

**Comment by T100D** [comment]
The installation is done from binary, this could be the problem. Not sure.

**Comment by lunny** [comment]
After you change the app.ini, you have to restart the gitea

**Comment by T100D** [comment]
After some testing, the attachment limit is working for the "releases" page.
But it is not working for the "Code" page. < different setting?

**Comment by ghost** [comment]
@T100D You may need the following settings
```
[repository.upload]
; Max size of each file in megabytes. Defaults to 3MB
FILE_MAX_SIZE = 3
```

**Comment by T100D** [comment]
@yasuokav That did the trick for me, could not find that in the default help available.

**Comment by ghost** [comment]
@T100D https://github.com/go-gitea/gitea/blob/master/custom/conf/app.ini.sample
