### ISSUE TITLE
Readme update

### ISSUE THREAD

**Issue by xinity** [go-gitea/gitea#42]
we should update logo and description at least in the README.MD

**Comment by joubertredrat** [comment]
Current readme have a lot of unecessary informations

**Comment by joubertredrat** [comment]
I think that need to remove README_ZH.md, put on README.md only essential informations and add other information on documentation site.

**Comment by tboerger** [comment]
Most of us can't provide translations for this readme anyway, so I would also suggest to remove it and move most parts to the website/documentation page.

**Comment by bkcsoft** [comment]
Agreed that translated README should be on website/in docs-repo instead. If people update it they may not be able to translate it.

@lunny Thoughts?

**Comment by lunny** [comment]
I agreed although I know many gogs' users on china. Please do it.

**Comment by xinity** [comment]
PR on it's way: https://github.com/go-gitea/gitea/pull/65

**Comment by lunny** [comment]
It seems this will be resolved via #65 ?
