### ISSUE TITLE
passwords with spaces seem to fail?

### ISSUE THREAD

**Issue by internalfx** [go-gitea/gitea#4200]
- Gitea version (or commit ref): 1.4.2
- Git version:
- Operating system: Ubuntu 18.04
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

If your postgres password contains a space, gitea will not install.

## Screenshots

![image](https://user-images.githubusercontent.com/583701/41196396-126691f6-6bf4-11e8-8421-1b809b7d58f6.png)

**Comment by bkcsoft** [comment]
https://github.com/go-gitea/gitea/blob/85414d8b754639cae1a9c361bbdc0714f06b87c1/models/models.go#L216-L223

`QueryEscape` should be `PathEscape` :slightly_smiling_face:

**Comment by lunny** [comment]
@bkcsoft could you send a PR to fix that?

**Comment by techknowlogick** [comment]
@lunny / @bkcsoft I've just sent a PR for this at #4275 Please review.
