### ISSUE TITLE
Browser always displays a vertical scroll bar with bottom status bar cropped

### ISSUE THREAD

**Issue by mircolino** [go-gitea/gitea#4202]
Gitea version: 1.4.2
Git version: 2.17.1.windows.2
Operating system: Windows 10 & Windows Server 2016
Database: SQLite
Can you reproduce the bug at https://try.gitea.io: yes

The right-side vertical scroll bar is always displayed, even when rendering pages shorter than the browser window, and the bottom status bar is alway cropped.
Tried both Chrome and Edge on different machines with different screen resolution.

![browser](https://user-images.githubusercontent.com/1192337/41196477-d1fb6b58-6bf5-11e8-8b36-0363b4931a66.jpg)

**Comment by lunny** [comment]
Which browser did you use?

**Comment by mircolino** [comment]
It's happening on both Chrome 67 and Edge 42.

**Comment by mhaluska** [comment]
Same here, visible in all browsers.
gitea -v
Gitea version 1.4.2 built with: bindata, sqlite

**Comment by mircolino** [comment]
Anywhere the html page is shorter than the browser window ( like for example [https://try.gitea.io/mhaluska/test](https://try.gitea.io/mhaluska/test) ) will show the issue on all my browsers/systems.
And I can still replicate it on all our local repos in version 1.4.2

But I can confirm that it has been resolved in (June 20) master version.

**Comment by lafriks** [comment]
Closing as fixed in 1.5.0

**Comment by lunny** [comment]
@lafriks which PR fix this?
