### ISSUE TITLE
Mailer test email still contains 'Gogs'

### ISSUE THREAD

**Issue by mjwwit** [go-gitea/gitea#421]
- Gitea version (or commit ref): 8559d6f267324241496b8611bc8e6f76efe869b7
- Git version: Not relevant
- Operating system: Not relevant
- Database: Not relevant
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist: Not relevant

## Description
The Gitea Mailer test mail still contains 'Gogs' in its subject and body. Changing this to Gitea will benefit consistency.

**Comment by tboerger** [comment]
Solved via #422
