### ISSUE TITLE
Repository owned by group, not organisation

### ISSUE THREAD

**Issue by belliash** [go-gitea/gitea#4211]
Please implement the ability to create a repositories owned by a group within the organisation. Actually only personal or owned by organisation repositories can be created. They are accessible by: organisation/repo_name. This has a major disadvantage. An organisation that is working on few projects cannot create two repositories for two different project with the same name and/or group repos by group.

With this issue implemented, I imagine that repositories could be accessed by organisation/group/repo_name. Thus Same organisation would be able to create several projects and repos under it w/o the need to prefix repo name with project name.

**Comment by lunny** [comment]
I thinks this is duplicated with  #3840

**Comment by belliash** [comment]
Yep, sounds similar.
Any chance to get this implemented? :+1:
