### ISSUE TITLE
Keep database password from preseeded configuration file

### ISSUE THREAD

**Issue by tarelda** [go-gitea/gitea#4217]
- Gitea version (or commit ref): fa3ceb6
- Git version: not relevant to the issue
- Operating system: alpine:latest
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL (MariaDB)
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist: Not relevant

## Description

I created fat gitea docker container, which contains also all other required services. It is just the way that suits my deployment. Issue I bumped into is, that database password is automagically generated in entrypoint and correctly seeded into configuration file, but when using installer it just omits it.
My expected behaviour is that when I preseed password it has to be kept instead of zeroing it. 
Can this be fixed or at least available with feature switch like --enable-preseeded-config ?

**Comment by tarelda** [comment]
This is not a solution, because it disables installer, which I explicitly want to avoid. 
What is more, I can't come up with single reason, why installer doesn't keep password from config while reading all of the other settings.

**Comment by tarelda** [comment]
@bkcsoft, it seems you are wrong
https://github.com/go-gitea/gitea/blob/master/routers/install.go
https://github.com/go-gitea/gitea/blob/85414d8b754639cae1a9c361bbdc0714f06b87c1/models/models.go#L133
https://github.com/go-gitea/gitea/blob/85414d8b754639cae1a9c361bbdc0714f06b87c1/modules/setting/setting.go#L675

**Comment by lunny** [comment]
should be closed by #4284
