### ISSUE TITLE
gitea creates world readable file permissions on repos

### ISSUE THREAD

**Issue by kolargol** [go-gitea/gitea#4218]
Hi,

Is there any reason why gitea creates too broad file permissions for repositories on the system (644)?

OS: OpenBSD
Gitea version: 1.3.2

thanks.

**Comment by savyajha** [comment]
I'm facing the same issue on Arch Linux with gitea 1.4.2

**Comment by SagePtr** [comment]
I just chmod repositories root directory to 700 (assuming owner and group are git:git and gitea is run under git:git too). That makes directory inaccessible by anyone else (except git and root of course).

**Comment by lafriks** [comment]
Setting repositories root directory to correct rights to not have repositories accessible with all users as @SagePtr mentioned
