### ISSUE TITLE
NL Translation proposal

### ISSUE THREAD

**Issue by T100D** [go-gitea/gitea#4219]
- Gitea version (or commit ref): 1.4.2 & master
- Operating system: All operating systems

## Description

In the nl_NLl translation ther is a confusing statement.

file
gitea/options/locale/locale_nl-NL.ini
  `settings.update_settings=Instellingen bewerken`

should be
  `settings.update_settings=Instellingen opslaan`

Reason is that in the settings interface is already about changing settings.
The button is meant to save them, now it tells met to change them instead of save them.

**Comment by techknowlogick** [comment]
Thank you for discovering this. If you'd like to contribute a fix all the translations are done on crowdin. For instructions please see: https://github.com/go-gitea/gitea/blob/master/CONTRIBUTING.md#translation

**Comment by T100D** [comment]
Maybe someday, i am trying to learn al the fun stuff, an again discovered something new :-)

**Comment by techknowlogick** [comment]
@T100D I've just submitted a translation on your behalf.

**Comment by techknowlogick** [comment]
Closing this as the translation has been submitted, and now it is just waiting for review from another translator.
