### ISSUE TITLE
Wiki pages does not rendered

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#4221]
I migrated [my repo](https://github.com/somenxavier/apunts-acces-uib-per-a-majors-de-25-anys) to [gitea](http://git.somenxavier.xyz/somenxavier/apunts-acces-uib-per-a-majors-de-25-anys). All is fine except that I cannot see certain wiki pages. For example [`Col·laboradors`](http://git.somenxavier.xyz/somenxavier/apunts-acces-uib-per-a-majors-de-25-anys/wiki/Col%C2%B7laboradors). Why?

My gitea version is 1.4.2 (binary). I have used sqlite3.

![captura de pantalla_2018-06-11_16-37-54](https://user-images.githubusercontent.com/89915/41238261-d29cb534-6d95-11e8-8d01-ecf4eae062d4.png)
![captura de pantalla_2018-06-11_16-37-24](https://user-images.githubusercontent.com/89915/41238262-d2fc4b5c-6d95-11e8-8a33-ee890de922f9.png)

**Comment by ghost** [comment]
This bug happened to me too.
This issue is caused because Github doesn't escape the file name.
(Similar issue #4090)
![001](https://user-images.githubusercontent.com/2960293/41263130-ebd9ec26-6e1f-11e8-8706-2dda98cbd3bc.jpg)

**Comment by ghost** [comment]
So, what's the solution, at least temporal?

**Comment by markuman** [comment]
Clone the wiki, rename strange looking filenames, commit and push?

**Comment by ghost** [comment]
But I have not `%` files when I clone it from gitea:

![captura de pantalla_2018-06-12_20-17-06](https://user-images.githubusercontent.com/89915/41308983-aeb63ab2-6e7d-11e8-8e0d-c6fbe0a842f0.png)

I have UTF-8 encoding

**Comment by ghost** [comment]
Rename
`Col·laboradors.md` -> `Col%C2%B7laboradors.md`
`Enumeració-de-les-versions.md` -> `Enumeraci%C3%B3-de-les-versions.md`
and then push to remote server

**Comment by ghost** [comment]
Oh!, come on. From user perspective, it complicates the life. gitea should convert UTF-8 bash names to URL encoded names

**Comment by markuman** [comment]
well, it's not a problem of the wiki/gitea. It can handle such crappy filenames while creating: https://git.osuv.de/m/trash/wiki/Col%C2%B7laboradors

![bildschirmfoto 2018-06-14 um 15 33 28](https://user-images.githubusercontent.com/3920157/41415212-54180362-6fe8-11e8-9f9f-feb48b97ec55.png)


My guess is, that the problem was (or is) the import function, which doesn't handle the filenames correctly - or as mentioned before by @yasuokav 

>  This issue is caused because Github doesn't escape the file name.

So to fix your project wiki, you need to fix it manually.

**Comment by ghost** [comment]
@markuman OK. Solved (manually).
Should I close the bug or maintained open for bug in import function?

**Comment by VegaSE** [comment]
What about Windows repo? Percentage in filename bad idea.
We ran into this while trying to write a wiki.
The Windows user cannot update the repositories.

**Comment by lunny** [comment]
I think this has been resolved by #24143
