### ISSUE TITLE
Why use `gitea` over `gogs` ?

### ISSUE THREAD

**Issue by lenormf** [go-gitea/gitea#423]
Hi,

The README lacks explanations as to how `gitea` is better than `gogs`, could you please expand on that? I see the features list, but that's not very helpful to someone who isn't familiar with everything that `gogs` do in the first place.

Thanks.

**Comment by strk** [comment]
The current goal is shipping a 1.0.0 version which has no new feature,
so from a user point of view there should be nothing that gitea does
and gogs doesn't.

Moreover, Gitea doesn't have an official release yet, so the user does
not even have the choice.

The only reason for using Gitea over Gogs at this moment is to contribute
in making it better, as acceptance of contributions in Gitea should be
easier to make. In the long run, our belief is that this ease of contribution
would make Gitea reacher in terms of features, and safer in terms of bugs.

**Comment by lenormf** [comment]
Aren't those principles shared by the `gogs` project as well? Or is that why the project was forked.

**Comment by strk** [comment]
Gogs is managed by a single person, who is the original author.
The community asked many times to share responsibility but this
was never accepted. So yes, this is the reason why the project
was forked.

Read more on https://blog.gitea.io/2016/12/welcome-to-gitea/

**Comment by lenormf** [comment]
Great, thanks for your quick answers.

**Comment by ptman** [comment]
https://github.com/go-gitea/website/issues/40
