### ISSUE TITLE
Missing support of checksum files

### ISSUE THREAD

**Issue by typeless** [go-gitea/gitea#4231]
- Gitea version (or commit ref):
 1.1.0+1364-ge3b77f9
(It's actually quite close to the tip and it's what is shown on my Gitea's homepage.

- Git version: 
git version 2.7.4

- Operating system:
"16.04.3 LTS (Xenial Xerus)"

- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

The log was added by me for debugging.
```
Jun 11 15:08:22 DIR-101 gitea[25815]: allowedTypes: [image/jpeg image/png application/zip application/gzip] fileType: text/plain; charset=utf-8
```

## Description
Copy-and-pasted from https://github.com/drone-plugins/drone-gitea-release/issues/9#issuecomment-396510386

The plugin doesn't work if I add the checksum parameter to .drone.yml. The logs I added show that it's due to the .txt file for the checksum is not in the set of allowedTypes.

It's not a necessary parameter for me but I think having the issue open here can save others' time from diagnosing it.

...

**Comment by tboerger** [comment]
You have to allow the mime type for text files within your Gitea app.ini (setting ALLOWED_TYPES, for reference: https://docs.gitea.io/en-us/config-cheat-sheet/#attachment-attachment)
