### ISSUE TITLE
Commit message is truncated on gitea webpage

### ISSUE THREAD

**Issue by cvvergara** [go-gitea/gitea#4246]
- Gitea version (or commit ref): Gitea Version: 1.3.3 
- Git version:
```
git --version
git version 2.11.0
```
- Operating system:
```
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.4 LTS
Release:        16.04
Codename:       xenial
```
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
    - [x] provided URL examples on the description
  - [ ] Not relevant

- Log gist:
  - [x]  I don't have the rights to see the logs

## Description
Commit message can be seen on github
https://github.com/cvvergara/geos/commit/d390b76990a899c6443a0aa4f35ea6e730332bd9

But not on gitea
https://git.osgeo.org/gitea/geos/geos/commit/d390b76990a899c6443a0aa4f35ea6e730332bd9

I can see on my clone:
```
commit 0039c291ba1a153958ce64109402a0a42ccf7c29
Author: Daniel Baston <dbaston@gmail.com>
Date:   Mon Jun 11 09:30:17 2018 -0400

    [CMake] Restore GEOS_VERSION defines in geos_c.h
    
    Fixes #882
    Closes https://github.com/OSGeo/geos/pull/105

```

back reference:
https://git.osgeo.org/gitea/sac/gitea-service/issues/4

...

## Screenshots

- github image

![image](https://user-images.githubusercontent.com/5035290/41424051-96e405b8-6fc2-11e8-9b0d-365135f402c4.png)
- gitea image for the same commit

![image](https://user-images.githubusercontent.com/5035290/41424122-cbed61be-6fc2-11e8-8f7d-bd4d0d68e09a.png)

**Comment by ghost** [comment]
Duplicate of #4060 ?
