### ISSUE TITLE
Corrupted repository archive after downloading

### ISSUE THREAD

**Issue by GridPrple** [go-gitea/gitea#4248]
- Gitea version (or commit ref): 1.4.1
- Git version: 2.16.2
- Operating system: Windows
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant

## Description
Folder with large size(2GB) have been LFS tracked, committed and pushed to a Gitea server.
After downloading a ZIP archive and trying to decompress it I get an error that this archive is not recognized as an archive. (screenshot attached at the bottom)
After that I downloaded the TAR.GZ archive from the web UI and tried to decompress it but I got that the archive had an unexpected end.(screenshot attached at the bottom)

Does anyone know what can cause this?

## Screenshots
ZIP Archive
![image](https://user-images.githubusercontent.com/12370552/41451884-d919c264-7077-11e8-9464-467a990f1de3.png)

TAR.GZ Archive
![image](https://user-images.githubusercontent.com/12370552/41451953-295a4e60-7078-11e8-807e-5ef7a8dd14c1.png)

**Comment by francoism90** [comment]
Are you sure the download was correctly? This could also be server issues.
Could you tell a bit more about your settings.

**Comment by GridPrple** [comment]
Sorry for the delay. 
It seems that the downloaded archive is not complete.
When I click on the button to generate ZIP archive there is a long waiting for the server to create the archive, but at one point the Webpage refreshes and shows error 500 on it. If I click F5 the download windows pops up for the archive. After the download the archive is ~500MB while if I use "git archive ..." the size is ~900MB.

What exactly would you like to know about the setup?

**Comment by Vodianoi** [comment]
Same for me,
My server is on a Raspberry Pi 3, I don't know if it is an hardware issue but it happens only on big sized projects.
I got a 1.2GB project and I only get a 177MB zip and most of files disappeared (mostly source code files).

I think the server can't handle too much files and it crashes so the zip isn't complete or is corrupted.

Here's journalctl output:

> Jun 21 14:56:02 rPi3 gitea[603]: [Macaron] 2018-06-21 14:56:02: Started GET / for 192.168.1.34
Jun 21 14:56:03 rPi3 gitea[603]: [Macaron] 2018-06-21 14:56:03: Completed GET / 200 OK in 164.953525ms
Jun 21 14:56:03 rPi3 gitea[603]: [Macaron] 2018-06-21 14:56:03: Started GET /api/v1/repos/search?uid=1&q=&limit=15&mode= for 192.168.1.34
Jun 21 14:56:03 rPi3 gitea[603]: [Macaron] 2018-06-21 14:56:03: Completed GET /api/v1/repos/search?uid=1&q=&limit=15&mode= 200 OK in 23.491271ms
Jun 21 14:57:17 rPi3 gitea[603]: [Macaron] 2018-06-21 14:57:17: Started GET [PATH] for 192.168.1.34
Jun 21 14:57:18 rPi3 gitea[603]: [Macaron] 2018-06-21 14:57:18: Completed GET [PATH] 200 OK in 775.599045ms
Jun 21 14:57:20 rPi3 gitea[603]: [Macaron] 2018-06-21 14:57:20: Started GET [PATH]/releases for 192.168.1.34
Jun 21 14:57:20 rPi3 gitea[603]: [Macaron] 2018-06-21 14:57:20: Completed GET [PATH]/releases 200 OK in 161.879013ms
Jun 21 14:57:22 rPi3 gitea[603]: [Macaron] 2018-06-21 14:57:22: Started GET [PATH]/archive/source.zip for 192.168.1.34
Jun 21 14:57:27 rPi3 gitea[603]: [Macaron] 2018-06-21 14:57:27: Completed GET [PATH]/archive/source.zip 200 OK in 5.439877038s

**Comment by GridPrple** [comment]
Again late,
I am accessing the server directly. Here is the log:

> Jun 27 16:43:35 scib003 gitea[16253]: [Macaron] 2018-06-27 16:43:35: Started GET /Gen5/PortableApps for 10.185.19.30
> Jun 27 16:43:35 scib003 gitea[16253]: [Macaron] 2018-06-27 16:43:35: Completed GET /Gen5/PortableApps 200 OK in 72.959954ms
> Jun 27 16:43:36 scib003 gitea[16253]: [Macaron] 2018-06-27 16:43:36: Started GET /vendor/plugins/cssrelpreload/loadCSS.min.js for 10.185.19.30
> Jun 27 16:43:36 scib003 gitea[16253]: [Macaron] [Static] Serving /vendor/plugins/cssrelpreload/loadCSS.min.js
> Jun 27 16:43:36 scib003 gitea[16253]: [Macaron] 2018-06-27 16:43:36: Completed GET /vendor/plugins/cssrelpreload/loadCSS.min.js 304 Not Modified in 244.02µs
> Jun 27 16:43:36 scib003 gitea[16253]: [Macaron] 2018-06-27 16:43:36: Started GET /vendor/plugins/semantic/semantic.min.css for 10.185.19.30
> Jun 27 16:43:36 scib003 gitea[16253]: [Macaron] 2018-06-27 16:43:36: Started GET /vendor/plugins/cssrelpreload/cssrelpreload.min.js for 10.185.19.30
> Jun 27 16:43:36 scib003 gitea[16253]: [Macaron] [Static] Serving /vendor/plugins/cssrelpreload/cssrelpreload.min.js
> Jun 27 16:43:36 scib003 gitea[16253]: [Macaron] 2018-06-27 16:43:36: Completed GET /vendor/plugins/cssrelpreload/cssrelpreload.min.js 304 Not Modified in 252.591µs
> Jun 27 16:43:36 scib003 gitea[16253]: [Macaron] 2018-06-27 16:43:36: Started GET /vendor/plugins/jquery/jquery.min.js for 10.185.19.30
> Jun 27 16:43:36 scib003 gitea[16253]: [Macaron] 2018-06-27 16:43:36: Started GET /vendor/plugins/emojify/emojify.min.js for 10.185.19.30
> Jun 27 16:43:36 scib003 gitea[16253]: [Macaron] 2018-06-27 16:43:36: Started GET /vendor/plugins/jquery.areyousure/jquery.are-you-sure.js for 10.185.19.30
> Jun 27 16:43:36 scib003 gitea[16253]: [Macaron] 2018-06-27 16:43:36: Started GET /vendor/plugins/highlight/highlight.pack.js for 10.185.19.30
> Jun 27 16:43:36 scib003 gitea[16253]: [Macaron] [Static] Serving /vendor/plugins/jquery.areyousure/jquery.are-you-sure.js
> Jun 27 16:43:36 scib003 gitea[16253]: [Macaron] 2018-06-27 16:43:36: Completed GET /vendor/plugins/jquery.areyousure/jquery.are-you-sure.js 304 Not Modified in 558.574µs
> Jun 27 16:43:36 scib003 gitea[16253]: [Macaron] [Static] Serving /vendor/plugins/emojify/emojify.min.js
> Jun 27 16:43:36 scib003 gitea[16253]: [Macaron] 2018-06-27 16:43:36: Completed GET /vendor/plugins/emojify/emojify.min.js 304 Not Modified in 1.170044ms
> Jun 27 16:43:36 scib003 gitea[16253]: [Macaron] 2018-06-27 16:43:36: Started GET /vendor/plugins/autolink/autolink.js for 10.185.19.30
> Jun 27 16:43:36 scib003 gitea[16253]: [Macaron] [Static] Serving /vendor/plugins/autolink/autolink.js
> Jun 27 16:43:36 scib003 gitea[16253]: [Macaron] 2018-06-27 16:43:36: Completed GET /vendor/plugins/autolink/autolink.js 304 Not Modified in 373.48µs
> Jun 27 16:43:36 scib003 gitea[16253]: [Macaron] 2018-06-27 16:43:36: Started GET /vendor/plugins/clipboard/clipboard.min.js for 10.185.19.30
> Jun 27 16:43:36 scib003 gitea[16253]: [Macaron] [Static] Serving /vendor/plugins/jquery/jquery.min.js
> Jun 27 16:43:36 scib003 gitea[16253]: [Macaron] 2018-06-27 16:43:36: Completed GET /vendor/plugins/jquery/jquery.min.js 304 Not Modified in 5.553745ms
> Jun 27 16:43:36 scib003 gitea[16253]: [Macaron] 2018-06-27 16:43:36: Started GET /vendor/plugins/vue/vue.min.js for 10.185.19.30
> Jun 27 16:43:36 scib003 gitea[16253]: [Macaron] [Static] Serving /vendor/plugins/clipboard/clipboard.min.js
> Jun 27 16:43:36 scib003 gitea[16253]: [Macaron] 2018-06-27 16:43:36: Completed GET /vendor/plugins/clipboard/clipboard.min.js 304 Not Modified in 845.092µs
> Jun 27 16:43:36 scib003 gitea[16253]: [Macaron] 2018-06-27 16:43:36: Started GET /vendor/plugins/semantic/semantic.min.js for 10.185.19.30
> Jun 27 16:43:36 scib003 gitea[16253]: [Macaron] 2018-06-27 16:43:36: Started GET /js/index.js?v=17b7ffb6cc1f3588d20dda49ffb651f0 for 10.185.19.30
> Jun 27 16:43:36 scib003 gitea[16253]: [Macaron] 2018-06-27 16:43:36: Started GET /vendor/assets/octicons/octicons.min.css for 10.185.19.30
> Jun 27 16:43:36 scib003 gitea[16253]: [Macaron] [Static] Serving /vendor/assets/octicons/octicons.min.css
> Jun 27 16:43:36 scib003 gitea[16253]: [Macaron] 2018-06-27 16:43:36: Completed GET /vendor/assets/octicons/octicons.min.css 200 OK in 630.66µs
> Jun 27 16:43:36 scib003 gitea[16253]: [Macaron] [Static] Serving /vendor/plugins/semantic/semantic.min.css
> Jun 27 16:43:36 scib003 gitea[16253]: [Macaron] 2018-06-27 16:43:36: Completed GET /vendor/plugins/semantic/semantic.min.css 304 Not Modified in 13.346845ms
> Jun 27 16:43:36 scib003 gitea[16253]: [Macaron] 2018-06-27 16:43:36: Started GET /css/index.css?v=17b7ffb6cc1f3588d20dda49ffb651f0 for 10.185.19.30
> Jun 27 16:43:36 scib003 gitea[16253]: [Macaron] [Static] Serving /vendor/plugins/vue/vue.min.js
> Jun 27 16:43:36 scib003 gitea[16253]: [Macaron] 2018-06-27 16:43:36: Completed GET /vendor/plugins/vue/vue.min.js 304 Not Modified in 4.513509ms
> Jun 27 16:43:36 scib003 gitea[16253]: [Macaron] [Static] Serving /js/index.js
> Jun 27 16:43:36 scib003 gitea[16253]: [Macaron] 2018-06-27 16:43:36: Completed GET /js/index.js?v=17b7ffb6cc1f3588d20dda49ffb651f0 304 Not Modified in 3.16816ms
> Jun 27 16:43:36 scib003 gitea[16253]: [Macaron] 2018-06-27 16:43:36: Started GET /vendor/plugins/highlight/github.css for 10.185.19.30
> Jun 27 16:43:36 scib003 gitea[16253]: [Macaron] [Static] Serving /vendor/plugins/highlight/github.css
> Jun 27 16:43:36 scib003 gitea[16253]: [Macaron] 2018-06-27 16:43:36: Completed GET /vendor/plugins/highlight/github.css 200 OK in 282.656µs
> Jun 27 16:43:36 scib003 gitea[16253]: [Macaron] [Static] Serving /css/index.css
> Jun 27 16:43:36 scib003 gitea[16253]: [Macaron] 2018-06-27 16:43:36: Completed GET /css/index.css?v=17b7ffb6cc1f3588d20dda49ffb651f0 200 OK in 1.85047ms
> Jun 27 16:43:36 scib003 gitea[16253]: [Macaron] [Static] Serving /vendor/plugins/semantic/semantic.min.js
> Jun 27 16:43:36 scib003 gitea[16253]: [Macaron] 2018-06-27 16:43:36: Completed GET /vendor/plugins/semantic/semantic.min.js 304 Not Modified in 9.584329ms
> Jun 27 16:43:36 scib003 gitea[16253]: [Macaron] [Static] Serving /vendor/plugins/highlight/highlight.pack.js
> Jun 27 16:43:36 scib003 gitea[16253]: [Macaron] 2018-06-27 16:43:36: Completed GET /vendor/plugins/highlight/highlight.pack.js 304 Not Modified in 20.576426ms
> Jun 27 16:43:36 scib003 gitea[16253]: [Macaron] 2018-06-27 16:43:36: Started GET /img/gitea-sm.png for 10.185.19.30
> Jun 27 16:43:36 scib003 gitea[16253]: [Macaron] [Static] Serving /img/gitea-sm.png
> Jun 27 16:43:36 scib003 gitea[16253]: [Macaron] 2018-06-27 16:43:36: Completed GET /img/gitea-sm.png 200 OK in 729.987µs
> Jun 27 16:43:36 scib003 gitea[16253]: [Macaron] 2018-06-27 16:43:36: Started GET /vendor/assets/font-awesome/css/font-awesome.min.css for 10.185.19.30
> Jun 27 16:43:36 scib003 gitea[16253]: [Macaron] [Static] Serving /vendor/assets/font-awesome/css/font-awesome.min.css
> Jun 27 16:43:36 scib003 gitea[16253]: [Macaron] 2018-06-27 16:43:36: Completed GET /vendor/assets/font-awesome/css/font-awesome.min.css 200 OK in 1.467093ms
> Jun 27 16:43:40 scib003 gitea[16253]: [Macaron] 2018-06-27 16:43:40: Started GET /Gen5/PortableApps/archive/master.zip for 10.185.19.30
> Jun 27 16:43:41 scib003 gitea[16253]: [Macaron] 2018-06-27 16:43:41: Completed GET /Gen5/PortableApps/archive/master.zip 200 OK in 1.759425483s
> Jun 27 16:43:43 scib003 gitea[16253]: [Macaron] 2018-06-27 16:43:43: Started GET /Gen5/PortableApps/archive/master.tar.gz for 10.185.19.30
> Jun 27 16:44:43 scib003 gitea[16253]: [Macaron] 2018-06-27 16:44:43: Completed GET /Gen5/PortableApps/archive/master.tar.gz 404 Not Found in 1m0.044218999s
> Jun 27 16:44:43 scib003 gitea[16253]: [Macaron] 2018-06-27 16:44:43: Started GET /img/500.png for 10.185.19.30
> Jun 27 16:44:43 scib003 gitea[16253]: [Macaron] [Static] Serving /img/500.png
> Jun 27 16:44:43 scib003 gitea[16253]: [Macaron] 2018-06-27 16:44:43: Completed GET /img/500.png 304 Not Modified in 688.164µs
> Jun 27 16:44:43 scib003 gitea[16253]: [Macaron] 2018-06-27 16:44:43: Started GET /vendor/assets/font-awesome/css/font-awesome.min.css for 10.185.19.30
> Jun 27 16:44:43 scib003 gitea[16253]: [Macaron] [Static] Serving /vendor/assets/font-awesome/css/font-awesome.min.css
> Jun 27 16:44:43 scib003 gitea[16253]: [Macaron] 2018-06-27 16:44:43: Completed GET /vendor/assets/font-awesome/css/font-awesome.min.css 200 OK in 1.527626ms
> Jun 27 16:44:44 scib003 gitea[16253]: [Macaron] 2018-06-27 16:44:44: Started GET /img/favicon.png for 10.185.19.30
> Jun 27 16:44:44 scib003 gitea[16253]: [Macaron] [Static] Serving /img/favicon.png
> Jun 27 16:44:44 scib003 gitea[16253]: [Macaron] 2018-06-27 16:44:44: Completed GET /img/favicon.png 200 OK in 1.13272ms

**Comment by GridPrple** [comment]
bump

**Comment by lafriks** [comment]
zip preperation should probably be made async
