### ISSUE TITLE
Allow signed commits to be required

### ISSUE THREAD

**Issue by hlandau** [go-gitea/gitea#4249]
GitHub allows protected branches to require signed commits. This is a blocking issue for adoption of Gitea by some projects.

**Comment by lunny** [comment]
There should be an option on protected branches like below:
![image](https://user-images.githubusercontent.com/81045/41471232-a3788078-70e5-11e8-9add-3b63ba83a82a.png)

**Comment by clarfonthey** [comment]
It would be nice if we could also do this for releases/tags only. I don't think that signing every commit is necessary, but I want to enforce it for releases.

**Comment by clarfonthey** [comment]
This feature seems like a no-brainer; could it be marked as confirmed so it doesn't become stale?

**Comment by dvn0** [comment]
No movement on this? Would anyone familiar with the relevant part of the Gitea codebase be interested in mentoring me on getting this implemented? I'm relatively new to Go, and would be happy to work on getting this feature implemented with a little bit of assistance.

**Comment by lunny** [comment]
At first, you should add an option on protected branch page to add an option `deny all commits no signed` which default is unchecked.

Then you should change code on cmd/serv.go or cmd/hooks.go to test if the commit unsigned allowed on that branch.

**Comment by djbrown** [comment]
Any news on this?

**Comment by lunny** [comment]
The idea is to add an option and check the signed commits on prereceive hook.

**Comment by zeripath** [comment]
This has only really become practicable since #7631 was merged.

It's not just a case of enforcing commits are signed - commits from merging PRs have to be signed and we need to indicate whether such a commit will be signed and likely indicate why it wouldn't be. We would need to add a block on attempting to merge a pr if it wouldn't be signed.

**Comment by jamesponddotco** [comment]
What would be a good bounty to help speed development on this issue?

**Comment by lafriks** [comment]
Any bounty is good ;)

**Comment by jamesponddotco** [comment]
**Bounty posted:**
https://www.bountysource.com/issues/59720659-allow-signed-commits-to-be-required

**Comment by zeripath** [comment]
OK so #9708 represents an implementation of this.

There are a couple of points to be made:

* Depending on your server configuration you may not be able to merge PRs into your protected branch. (Remember these have to be signed too.)
* Similarly, You may not be able merge CRUD actions into your protected branch.

There are few extension options which probably need discussion to see if there is interest:

* Allow repo admin to push unsigned
* Allow repo admin to merge unsigned
