### ISSUE TITLE
GPG signature verification

### ISSUE THREAD

**Issue by ekozan** [go-gitea/gitea#425]
feature request/discussion:

Github just added GPG signature verification, this would be a cool feature in gogs as well.
https://github.com/blog/2144-gpg-signature-verification

ported from https://github.com/gogits/gogs/issues/2981

I think it's a realy nice to have feature

**Comment by tboerger** [comment]
Yeah, makes sense to expose this to the user.

**Comment by ekozan** [comment]
@bkcsoft have started some work on this subject if i remember well :) 

Or not :)

**Comment by gsantner** [comment]
The option "SSH-Keys" in personal settings could be renamed to just "Keys" to hold SSH and GPG

**Comment by lunny** [comment]
@gsantner Yes, just like Github do

**Comment by ekozan** [comment]
@sapk

**Comment by gsantner** [comment]
https://github.com/gogits/gogs/pull/3127

**Comment by lunny** [comment]
Yes, I noticed that PR.

**Comment by bkcsoft** [comment]
I could port that PR during the holidays 🙂

**Comment by bkcsoft** [comment]
@ekozan I didn't have time before sapk started on it

**Comment by sapk** [comment]
This is implemented. It maybe needed to be more tested and added to more page (currently only in commit list and commit page). But this issue could be closed, I think.

**Comment by dakira** [comment]
@sapk Wow. I just noticed this was being worked on. Great stuff, thanks for the contribution!

**Comment by ekozan** [comment]
Yeah
