### ISSUE TITLE
go-bindata is no longer maintained

### ISSUE THREAD

**Issue by jonasfranz** [go-gitea/gitea#4250]
go-bindata is no longer maintained as stated here: https://github.com/jteeuwen/go-bindata#warning

We should replace it with a maintained alternative like [packr](https://github.com/gobuffalo/packr).

**Comment by lunny** [comment]
But maybe continue with https://github.com/go-bindata/go-bindata ?

**Comment by lunny** [comment]
I don't like `packr build`.

**Comment by bkcsoft** [comment]
@lunny You don't need to run `packr build`, you could (like we do now with `go-bindata`) run `packr` followed by `go build` :|

**Comment by axifive** [comment]
And there is another maintained alternative: https://github.com/rakyll/statik

**Comment by tboerger** [comment]
I would suggest fileb0x

**Comment by edacval** [comment]
Arch Linux uses https://github.com/shuLhan/go-bindata

**Comment by sapk** [comment]
https://github.com/mjibson/esc is simple to use.

**Comment by tboerger** [comment]
Esc doesn't support tags, tags are required for gitea.

**Comment by lunny** [comment]
Just found https://github.com/shurcooL/vfsgen, I think it maybe a better solution than others because it's a library and could be put in vendor and will resolve package dependency on building process. We can write a command with a special build flag which will only be run on build process.

**Comment by lafriks** [comment]
@lunny I tested it a bit some time ago and it does looks quite good: https://github.com/lafriks/gitea-rewrite-experiment/tree/master/modules/template

**Comment by tboerger** [comment]
I'm using filb0x so far for other projects which is working really good.
