### ISSUE TITLE
Libravatar.org is shutting down on 2018-09-01

### ISSUE THREAD

**Issue by daviian** [go-gitea/gitea#4252]
Libravatar is closing in september 2018. Unfortunately there is no direct equivalent.
So we can remove support for it than.

Reference:
https://blog.libravatar.org/posts/Libravatar.org_is_shutting_down_on_2018-09-01/

**Comment by techknowlogick** [comment]
It looks like there is some hope for it to continue: https://wiki.libravatar.org/shutdown-coordination/

**Comment by techknowlogick** [comment]
https://pad.riseup.net/p/libravatar-future-irc There is a discussion this Sunday in regards to the future. Looks like fedora will probably take over hosting.

**Comment by strk** [comment]
Note that libravatar support does NOT depend on any centralized service. It is a protocol description, anyone willing to publish his/her own avatar can do so. NOTHING relies on libravatar.org specifically, so there's no point in removing the support for the protocol.

**Comment by techknowlogick** [comment]
@strk yes, but if it shuts down then some code will need to be changed due to the fallback not being available. Good news though is that it looks like it wont be shutdown.

**Comment by strk** [comment]
The fallback is configurable, IIRC.
Of course if we have a default we should make sure it is functional.

--strk;

**Comment by techknowlogick** [comment]
Shutdown not happening anymore (just migrating to a new owner)

Source: https://git.launchpad.net/~libravatar/libravatar/commit/?id=7e81b7c09815f031ac456dbb3b8e42bc43e23024
