### ISSUE TITLE
Clicking on the Code-tab leads to invalid URL

### ISSUE THREAD

**Issue by cleverer** [go-gitea/gitea#4259]
- Gitea version (or commit ref): 1.4.2
- Git version: 2.17.0
- Operating system: macOS 10.13.4
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No, but on https://git.damutten.ch/Nicolas/todolist
  - [ ] Not relevant
- Log gist:

## Description
When browsing a tag, clicking on the Code-tab leads to an invalid url/404. It incorrectly gets linked to src/**branch**/_tagname_ instead of src/**tag**/_tagname_.

## Screenshots
![ezgif-1-d7c9ebecac](https://user-images.githubusercontent.com/1735317/41500340-ba94b1f0-718f-11e8-8113-85ed205dbb8b.gif)

**Comment by daviian** [comment]
As far as I see this issue only occurs on the release/1.4 branch and not on master. Is this correct?

@johnrazeur of course, we are happy if you do!

**Comment by johnrazeur** [comment]
Yes, the issue doesn't occurs on master.

**Comment by cleverer** [comment]
@daviian It seems like it, yes. Just wanted to comment on it, but you were a few seconds faster…
I reinstalled it with `brew reinstall --devel` and it works like a charm now.

@johnrazeur Thanks for offering to help!

I'm closing the issue for now.

**Comment by lunny** [comment]
@cleverer I would like stay this on v1.4.3 @johnrazeur please send a PR to release/v1.4

**Comment by cleverer** [comment]
Found the commit, which fixes the behaviour: 3a6f3c8c119927b4ed9ea814342f1b15bd29d93d, #3908

**Comment by daviian** [comment]
Fixed by #4263
