### ISSUE TITLE
Cannot create multiple forks from a repo

### ISSUE THREAD

**Issue by lukewatts** [go-gitea/gitea#4269]
There's two issues here it seems:

1. If I fork a repo (call it myorganisztion/app) and I now have lukewatts/app then I cannot create a second fork of myorganisation/app (let's say I want lukewatts/app-2)

2. If I fork repo myorganization/app to lukewatts/app I cannot then fork lukewatts/app to lukewatts/app2. I get a "UID cannot be empty" error message (Image attached)

![gitea-cannot-fork-from-my-own-repos](https://user-images.githubusercontent.com/4622166/41535933-f112792a-72fb-11e8-87eb-50fbda5960c8.PNG)

- Gitea version (or commit ref): 1.3.0
- Git version: 2.13.2
- Operating system: Win8.1/Windows Server 2012R2
- Database (use `[x]`): 
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x ] Yes (provide example URL) https://try.gitea.io/repo/fork/6381
  - [ ] No
  - [ ] Not relevant
- Log gist: N/A

**Comment by lunny** [comment]
1. This is not allowed on github either.
2. This maybe a bug.

**Comment by lunny** [comment]
Sorry, I think this is expected as github does.
