### ISSUE TITLE
User with limited permissions when self registered

### ISSUE THREAD

**Issue by reinerj** [go-gitea/gitea#427]
Hi,

we plan to go live with Gitea for a bigger project where we expect to have many user. The current problem we face is that when a user register (what he should do) he can create as example organisations, or can create own repos. 

We need that user can register but by default they should be only able to create issues. Otherwise our platform will end up to something like Github. We expect to have more then 1000 public repos. 

We plan to go live soon but with the current restrictions it will simple mot be possible to restrict users in what the able to do.

What is missing from our point of view is a user role as "reporter". Later an admin can grant more right that they can create own repo a example. 

Would be nice this could be implemented in Gitea. 

Thank you 
Reiner

**Comment by tboerger** [comment]
I think you are not the only one with this kind of restriction.

**Comment by lunny** [comment]
@tboerger maybe this should be put in 1.1.0?

**Comment by tboerger** [comment]
I talked with him on Gitter, if that is easy to realize it would help him to bring up his project based on gitea. So if we can make it fast it should be awesome, otherwise it have to be delayed which potentially means he got to skip gitea for that :(

**Comment by reinerj** [comment]
Yes, without limited permissions we cannot use Gitea to go live. I assume many others will run in the same issue or they run something wide open.

Thank you 


> Am 20.12.2016 um 16:24 schrieb Thomas Boerger <notifications@github.com>:
> 
> I talked with him on Gitter, if that is easy to realize it would help him to bring up his project based on gitea. So if we can make it fast it should be awesome, otherwise it have to be delayed which potentially means he got to skip gitea for that :(

**Comment by RickZeeland** [comment]
We would like this behavior / setting too:
> by default they should be only able to create issues.
I will Post a bounty on it !

**Comment by freswa** [comment]
I'd really like to use gitea for customer projects. But at the moment they could copy the whole source code if they want. For most of the projects it's ok, for some it's not. Also I agree with @reinerj in regards of the chaos a customer can make when creating repos and/or organisations.

Imho a customer/reporter:
1) should not be able to create repos
2) should not be able to create orgs
3) may optionally see the code
4) may optionally see the wiki

What I think we need:
1) Two switches. One for the user to disable repo creation for him and one switch to enable/disable repo creation for new users.
2) We already have the DISABLE_REGULAR_ORG_CREATION switch for that.
3) Another role "reporter" which limits the user to only see the Wiki and Issues. 
4) A switch in the repository options to allow/deny the role "reporter" wiki ro access.

**Comment by RickZeeland** [comment]
@freswa : you probably know this, but 	changes to the configuration can be made in C:\Projects\Gitea\custom\conf\app.ini

	Service (service)
	DISABLE_REGISTRATION: Disable registration, after which only admin can create accounts for users.
	SHOW_REGISTRATION_BUTTON: Indicate whether to show registration button or not.

**Comment by freswa** [comment]
@RickZeeland I know those options. But regardless of selfregistered or not you don't want to add the "disable repo creation" option to every user manually, do you?

**Comment by 6543** [comment]
since #6274 is merged we could add a setting to **app.ini** witch by default make new user to this type of

**Comment by dbuse** [comment]
Any news on this? I would really like @6543 's suggestion of an ini setting and/or an option to change this via the API.

**Comment by rjnienaber** [comment]
@6543, so reading the ini file and setting the `IsRestricted` column of the user in the database seems straightforward.  However, is that enough? If the use case is to restrict newly registered users from creating their own repos, it seems we would need to set [MaxRepoCreation](https://github.com/go-gitea/gitea/blob/62a4879e84c7474dd72ab0eb4c54923f2690510c/models/user.go#L846) to 0 as well?
