### ISSUE TITLE
dump from a script run from crontab fails with unset USER

### ISSUE THREAD

**Issue by gullevek** [go-gitea/gitea#4276]
- Gitea version (or commit ref): 1.4.2
- Git version: 2.17.1
- Operating system: Debian
- Database (use `[x]`):
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:

## Description

Running dump from a shell script from crontab will fail as the user check in go checks for USER which can be unset

sample:
crontab

> 0 0 * * *  git /bin/backup_gitea.sh

backup_gitea.sh

```
#!/bin/bash
cd "/backup/gitea/"
/usr/local/bin/gitea dump -c /etc/gitea/app.ini
```

will fail with "empty user"
2018/06/19 01:00:02 ...s/setting/setting.go:994 NewContext()] [E] Expect user 'git' but
          current user is:

adding 'export USER=$(whoami)' before the gitea dump will make the dump work

Reference in code:
https://github.com/go-gitea/gitea/blob/71dee6b7c09242707028cdfe23373a1f88d6a663/modules/user/user.go#L11

Something like this might be a better approach to get the user
https://golangcode.com/get-the-current-username-name-and-home-dir-cross-platform/

**Comment by bwint** [comment]
I have the same problem.

Thank you very much @gullevek for providing a solution!

**Comment by alexdohmen** [comment]
Another solution for docker container is to use the --user switch. The user is equal to the RUN_USER.
