### ISSUE TITLE
Add Merge Strategy Option to Swagger API

### ISSUE THREAD

**Issue by mohammed90** [go-gitea/gitea#4277]
- Gitea version (or commit ref): N/A
- Git version: 3f2f575
- Operating system: N/A
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:
N/A
## Description

Currently the UI allows for multiple PR merge strategies controlled by the form value "do". The funcs allow for this control, but the Swgger API doesn't expose the option.

The SDK is also missing the feature as seen [here](https://godoc.org/code.gitea.io/sdk/gitea#Client.MergePullRequest). Should I create another issue for the SDK in its corresponding repo?

## Screenshots

N/A

**Comment by 6543** [comment]
@Mohammed90 https://gitea.com/api/swagger#/repository/repoMergePullRequest

-> API now has a `do` field wich is interpreted as Enum: [ merge, rebase, rebase-merge, squash ]

**Comment by 6543** [comment]
@Mohammed90 if you are fine with - can you close this issue?

**Comment by 6543** [comment]
PS: for the SDK there is a PR https://gitea.com/gitea/go-sdk/pulls/146

**Comment by Mohammed90** [comment]
That PR is not merged yet. I'll close it when it's merged.
