### ISSUE TITLE
Merge notification email is empty

### ISSUE THREAD

**Issue by kolaente** [go-gitea/gitea#4279]
- Gitea version (or commit ref): d84da8f
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes, probably

## Description

When a pr is merged, Gitea automatically sends an email to everyone. But that email does not contain anything that indicates there was a merged pr. Instead, I get this: 
```
---
View it on Gitea. 
```

And the title of the pr as email title.

It should at least say something like `Merged #xyz` (like on Github)

**Comment by Perflyst** [comment]
Same with new issues without any content, maybe there should be the name of the issue and with closed issues.
