### ISSUE TITLE
how to update gitea indexer

### ISSUE THREAD

**Issue by laoshaw** [go-gitea/gitea#4283]
running 1.4.1 and when I search a text inside a repo, I saw old reference(e.g. I renamed a file) that has a 404 link, how can I flush those older index info that is no longer valid?

is there a command I can run cron with to refresh the indexer files? or, if I delete the file will it be generated automatically soon?

last, the indexer file is huge, for my 200MB repo I have a 2GMB indexer file, which is a surprise, but fine.

**Comment by lafriks** [comment]
Yes you can delete index file and restart gitea than it will be regenerated

**Comment by laoshaw** [comment]
I have to remove the whole indexer directory and restart gitea. Thanks.
