### ISSUE TITLE
Native mobile apps for gitea

### ISSUE THREAD

**Issue by nxglabs** [go-gitea/gitea#4290]
I represent NXG Labs Pvt Ltd, we are a software development company based out of Pune, India. We are currently using Gitea for our internal source control needs. We were thinking of developing mobile client for gitea but budget constraints dont allow us to do so. How many of you would be interested in buying an installation wide license of Android and iOS native apps for USD 99 one time fees. Please note that for now the apps wont be open source, may be in future we can make those open-source.

**Comment by lunny** [comment]
@nxglabs maybe you can upload it to appstore and you will find who would like to pay for that.

**Comment by nxglabs** [comment]
Thanks @lunny. Its a good suggestion but the apps are not ready yet. We want to take a call on whether to make it or not based on level of interest here in the community.

**Comment by vtolstov** [comment]
I'm interest on opensource version, but can pay for it like for osmand. What do you think?

**Comment by strk** [comment]
I'm sure fundraising for an opensource version would be successful

**Comment by techknowlogick** [comment]
@nxglabs Here is a post on the forum about someone asking about a mobile app https://discourse.gitea.io/t/app-for-android/302

I'm going to close this ticket now as it has been open for a week and recommend you continue this conversation over in the forum.

Personally I may use an app, but 99 USD is waaay to expensive for me.
