### ISSUE TITLE
Integrate static websites

### ISSUE THREAD

**Issue by tboerger** [go-gitea/gitea#43]
It should be awesome to have support for static websites like with jekyll on github. I read about https://github.com/spf13/hugo for that. References to https://github.com/gogits/gogs/issues/1314.

**Comment by nounoursheureux** [comment]
So you'd like to have a branch named `gitea-pages` for example, which would automatically serve the files ?

**Comment by tboerger** [comment]
> So you'd like to have a branch named gitea-pages for example, which would automatically serve the files ?

Yeah, something like that. And maybe we need an admin option to enable/disable this behavior because not everybody have the required wildcard DNS record to let that work nice.

**Comment by nounoursheureux** [comment]
I'm gonna try to implement the first part: serving static files from a git branch

**Comment by nounoursheureux** [comment]
We could just serve the file on the `/:user/:reponame/static/*` routes, I tried to implement this and it is working well. But I don't know if this may cause security issues because everything would be under the same domain.

**Comment by lunny** [comment]
Yes, you MUST not serve .git dir and it's sub dirs and files to anyone.

**Comment by tboerger** [comment]
Does routing by subdomains work with the underlying framework?

**Comment by lunny** [comment]
Domain binding is not a requirement on a self-hosted git service? @tboerger

**Comment by tboerger** [comment]
Of course it's not a requirement, but it should be configurable by the admin if the static pages are bound to a subdomain or on a subfolder :)

**Comment by tboerger** [comment]
Binding to a subfolder can be a security problem because a small javascript snippet can steal the user session cookie.

**Comment by nounoursheureux** [comment]
I don't think we should make possible to bind it to a subfolder if it causes a security problem :lock:

**Comment by fabian-z** [comment]
@tboerger Maybe consider using [HttpOnly](https://www.owasp.org/index.php/HttpOnly) and [SecureFlag](https://www.owasp.org/index.php/SecureFlag) cookies?

**Comment by tboerger** [comment]
However we can solve that, this feature won't do it into the next/first release of gitea. Wikis, pull requests and some UI polishing are much more important :)

**Comment by tboerger** [comment]
Project is dead, close.
