### ISSUE TITLE
Issue reference backlinks are missing

### ISSUE THREAD

**Issue by stevegt** [go-gitea/gitea#4302]
As of 85414d8b we're missing the "{user} referenced this issue {date}" backlinks that github creates when another issue references the current one.  I'll link this issue to #3134 and vice versa so both show an example of what these should look like -- see below.

These links are pretty important; they turn github issues from disjoint threads into an interlinked, multi-threaded mesh.  They help to prevent and converge duplicates, and probably have a role in community-building. 

In my own case, as soon as we had created more than a few issues and users in our local Gitea install, I immediately started wanting these backlinks.  This is the sort of problem that #1029 exposes.

I'm trying to figure out the right way to tackle this; do we somehow detect and create the backlinks on the fly as we render the HTML?  Or do we use a backlinks table that gets populated as the references are created?  If the latter, we would want to scan through existing comments at migration to create the initial table content when upgrading from older versions, right?

**Comment by cryptix** [comment]
> As of ... we're missing ..

I wonder why this is marked as a _feature_? The above sounds much more like a regression.

**Comment by cryptix** [comment]
Thanks for the clearification.

**Comment by cryptix** [comment]
sorry for the meta-noise but should feature tracking issues really be considered stale?

I for one would really like to try gitea once these things are in.

**Comment by mxmehl** [comment]
Do I see correctly that this issue would be solved with #3695 being merged?
