### ISSUE TITLE
Migration for topic validation fails

### ISSUE THREAD

**Issue by Treora** [go-gitea/gitea#4303]
- Gitea version (or commit ref): latest docker image 9431640caf3a, presumably corresponding to commit e2721b6.
- Operating system: Ubuntu
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ x ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ x ] Not relevant
- Log gist:
```
2018/06/23 21:31:53 [I] Migration: Reformat and remove incorrect topics
2018/06/23 21:31:53 [I] This migration could take up to minutes, please be patient.
2018/06/23 21:31:53 [I] Validating existed topics...
2018/06/23 21:31:53 [...itea/routers/init.go:60 GlobalInit()] [E] Failed to initialize ORM engine: migrate: do migrate: no such table: topic
```

## Description

Upgrading to the latest version fails for me with the above error. I have never created topics (not even sure how to), maybe that is relevant here. The migration appears to have been added last week in #4258, so perhaps @axifive may want to look at this.

**Comment by techknowlogick** [comment]
@Treora Thanks for the ticket this will hopefully be resolved with #4297

**Comment by axifive** [comment]
@Treora, Thank you for the report! Fixed in https://github.com/go-gitea/gitea/pull/4297/commits/8d0787c1a957284872741459038f7ce1112489f2

@daviian, Similar error for v69 migration, unsynced table field
```
2018/06/24 18:06:39 [I] Migration: move team units to team_unit table
2018/06/24 18:06:39 [...itea/routers/init.go:60 GlobalInit()] [E] Failed to initialize ORM engine: migrate: do migrate: no such column: unit_types
```

**Comment by daviian** [comment]
@axifive You might have run the migration twice.

**Comment by axifive** [comment]
@daviian, It seems you are right. Сhecked again migration from 1.3, everything is fine
