### ISSUE TITLE
Create new file from the web ui when the repo is created

### ISSUE THREAD

**Issue by shuhaowu** [go-gitea/gitea#4308]
- Gitea version (or commit ref): 1.4.2
- Git version:
- Operating system: Ubuntu
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

If a git repository is created without any files in it (without any branch/commit/etc), you cannot create a new file from the web ui.

**Comment by lunny** [comment]
I think your first requirement has been implemented.

**Comment by daviian** [comment]
@shuhaowu You can create a directory by specifying a full path when creating a new file. Git doesn't allow to check in an empty folder.

**Comment by shuhaowu** [comment]
Ah I see how it works. I think the second issue still stands so I'm going to change this issue to be that one exclusively.

**Comment by bjoe2k4** [comment]
Seeing the same issue. Create new file/Upload File button is only shown after a branch and initial commit has been created.

**Comment by zeripath** [comment]
I think this is a reasonable thing to have - it should be possible to do.

**Comment by lunny** [comment]
Right!

**Comment by rrimc69** [comment]
+1 same issue. Created bare repo from scratch, in GUI, no initial file addition possible from the GUI in the bare repo after creation.

**Comment by aiso-net** [comment]
+1 same issue. Created bare repo from scratch, in GUI, no initial file addition possible from the GUI in the bare repo after creation.

**Comment by eksiscloud** [comment]
+1, same here.

Is there some real reasons why creating a new file to empty repo in GUI is impossible?

**Comment by carlheaton** [comment]
> +1, same here.
> 
> Is there some real reasons why creating a new file to empty repo in GUI is impossible?

AFAIK git doesn't allow it / see empty directories, so the feature would require a file such as ".keep" creating.

**Comment by theAkito** [comment]
> AFAIK git doesn't allow it / see empty directories, so the feature would require a file such as ".keep" creating.

How is a new file an empty directory? The root directory is already "indexed" in a way, since it's the root of the Git repository. Then, you can always add files to the repository.

**Comment by lunny** [comment]
resolved by #24164
