### ISSUE TITLE
Custom Access-Control-Allow-Origin header in raw data

### ISSUE THREAD

**Issue by edoaxyz** [go-gitea/gitea#4309]
## Description
I noticed that raw data are sent without including the Access-Control-Allow-Origin header. This is necessary if someone wants to use this data with javascript because Chrome (or other web browsers) won't accept this data without this header specified as Access-Control-Allow-Origin:"*". Another issue like this was submitted in [Gogs](https://github.com/gogs/gogs/issues/3987) and I noticed that it's already been closed.

**Comment by edoaxyz** [comment]
I requested it as a custom feature that can be set in app.ini and if someone wants to apply it is at his own risk.

**Comment by sapk** [comment]
@edoaxyz It would be more logical to use a reverse proxy to do custom use case. You can use various webserver to do the job like Apache, nginx, caddy, traefik, etc ...

**Comment by sapk** [comment]
For example you can find basic configuration on [gitea docs](https://docs.gitea.io/en-us/reverse-proxies/) or even on [archlinux wiki](https://wiki.archlinux.org/index.php/Gitea#Configure_nginx_as_reverse_proxy)

**Comment by techknowlogick** [comment]
This now exists in Gitea
