### ISSUE TITLE
[Feature Request] Sandstorm.io Integration

### ISSUE THREAD

**Issue by boredland** [go-gitea/gitea#4310]
I really like this fork and I really like how Gogs got integrated into the sandstorm platform. Since the integration looks quite straightforward, creating as such for Gitea would be an option. Do you see any downsides on that?
https://github.com/cem/gogs-sandstorm

**Comment by GitHubGeek** [comment]
Would love to see Gitea running on Sandstorm :+1:

**Comment by xavier83** [comment]
will it be possible to get _**gitea**_ working with **sandstorm**?

**Comment by 6543** [comment]
As I think no maintainer use sandstorm, they wont do this.

As I understand it only is about packaging gitea for sandstorm, this depend on sandstorm's community ...
