### ISSUE TITLE
[Feature Request] Commit Graph: Make number of lines configurable

### ISSUE THREAD

**Issue by thomask77** [go-gitea/gitea#4319]
Hi!

Right now, the number of lines in the commit graph view is fixed to 100, which is too few in most cases.

  * https://github.com/go-gitea/gitea/blob/e2b2fd6e78a3181fa490f299f4c257eb5e0cc35d/models/graph.go#L44

This should be made configurable in the `app.ini` file.

**Comment by kjellkvinge** [comment]
I agree, ref #832

**Comment by hetykai** [comment]
+1
If pagination  is to hard to implement, this will be a good solution.
