### ISSUE TITLE
uploaded images are not updated in real time

### ISSUE THREAD

**Issue by laoshaw** [go-gitea/gitea#4326]
- Gitea version (or commit ref): 1.4.2
- Git version: 2.7.4
- Operating system: ubuntu 16.04 64bit
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [X ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ X] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

Upload images to a directory via web UI(or command line git-push), refer it in a markdown file in the same directory, first displayed fine, then replace it with a different image, or same image with different name, the markdown will display the old images, i.e. the markdark inside gitea web interface is not syncing up with the real image files in git repositories.

**Comment by lunny** [comment]
Could you provide a URL on https://try.gitea.io
