### ISSUE TITLE
[Security] Log out only deletes browser cookies

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#4336]
- Gitea version (or commit ref): all
- Git version: not relevant
- Operating system: not relevant
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

**Comment by axifive** [comment]
> Issue already reported on mail two months ago but never got an answer.

Thanks, can you refer to that another problem?

**Comment by axifive** [comment]
I can't reproduce this. Tried signout and request with saved cookie.
Can you provide more information?

**Comment by cezar97** [comment]
Thanks for your feedback @axifive.
Can't re-test it in the next days, but I'll let you know.
Thanks for your patience.

**Comment by cezar97** [comment]
@axifive,
when I first sent an email to security@gitea.io ( two months ago! ) I mentioned that Remeber me is required ( I forget to say that here ).
Today, after your ping, I tested again in a hurry ( unsuccessfully ) so just to be sure I delayed my response in the next days. But I'm glad you already reproduced it successfully.

**Comment by cezar97** [comment]
> Thank you for the Gitea security research, this is extremely important for the further successful development of the project.

BTW that's what I wanted to hear from the Gitea Team... I also appreciate it as an user...

**Comment by lafriks** [comment]
@cezar97 not to be picky but I did respond to your reports. It just that we all (including Gitea Team) here are voluntary developers working in their free time so not everything can be done so fast as we would like. We still have to do our daily work to get money :) Anyway we are thinking on way to get word out about reported security issues to more Gitea maintainers

**Comment by cezar97** [comment]
> ... voluntary developers in their free time ...

Maybe I forgot this, as I'm used to bug bounties where there's someone that answer in a relatively short time.
So, I'd like to apologise for my comments ( I've already updated them ) and say thank you for your work. As you said, Gitea is possible because of you all :smile:.
@lafriks Thank you for your kind comment.
