### ISSUE TITLE
[Security] Ability to logout user and more

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#4337]
- Gitea version (or commit ref): all
- Git version: not relevant
- Operating system: not relevant
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Screenshots
None

**Comment by Siesh1oo** [comment]
Quick fix could wrap all user content in iframe with sandbox attr set; all recent browsers support this.

**Comment by zeripath** [comment]
Fixed by #10462, #10465
