### ISSUE TITLE
[Feature Request] User biography

### ISSUE THREAD

**Issue by Perflyst** [go-gitea/gitea#4339]
Currently there is no user bio.
I personally use them for my PGP fingerprint, but there are other useful ideas for which a biography like GitHub/GitLab would be good.

I haven't found anything about it either, if you can activate the biography or something similar.

**Comment by techknowlogick** [comment]
Note for anyone taking this on. The `user` table already has `description` as a column you'll just need to surface that in the interface for visibility and allowing users to change the content.

**Comment by lunny** [comment]
I don't think it's a necessary feature for a self-hosted git service but not a online service.
