### ISSUE TITLE
Cannot push anything to gitea repo

### ISSUE THREAD

**Issue by BorisBrock** [go-gitea/gitea#4342]
- Gitea version (or commit ref): 1.4.3
- Git version: ?
- Operating system: Synology DSM 6.2 (Linux)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant

## Description
I have just installed gitea on my Synology DiskStation. Then I created two repositories using the gitea web interface. After that I cloned the repositiries to my local harddrive, added a file and committed.

So far everything worked fine and as expected.

Then I tried to push the repos back to my gitea instance:

> git push -u origin master

This resulted in the following error:

> Counting objects: 3, done.
> Writing objects: 100% (3/3), 214 bytes | 214.00 KiB/s, done.
> Total 3 (delta 0), reused 0 (delta 0)
> To http://myurl:4000/myusername/myproject.git
>  ! [remote rejected] master -> master (pre-receive hook declined)
> error: failed to push some refs to 'http://myurl:4000/myusername/myproject.git'

The error is 100% reproducible. No matter what, I cannot push _anything_ to my gitea server.

**Comment by lafriks** [comment]
See gitea.log if there are any errors

**Comment by techknowlogick** [comment]
Closing. Please re-open with applicable logs.
