### ISSUE TITLE
[Discussion] Gnupg to docker image to allow blocking unsigned commits on pre-receive-hook

### ISSUE THREAD

**Issue by sphrak** [go-gitea/gitea#4344]
Hello everyone,
Was about to add [this](https://github.com/github/platform-samples/blob/master/pre-receive-hooks/block_unsigned_commits.sh) `pre-receive` hook to my repository in gitea in order to block non-signed commits. However it failed and I found out the gnupg package wasnt included in the docker build.

Now this does not come without a cost of course to install the gnupg package costs us `54MB` which is quite a lot considering the whole gitea image weighs in at just shy of ~`75MB`.

So I mainly started this issue to discuss if it would be: 
* Possible to have `gnupg` package added to Dockerfile?
* If not are there other creative solutions/alternative libraries to circumvent this "limitation"? 

.. Or should I simply just manually install it and call it a day?

Kindly,
sphrak

**Comment by lafriks** [comment]
You can just create new dockerfile based in gitea and just add gnupg package

**Comment by techknowlogick** [comment]
Closing this as hopefully we will have this feature baked into Gitea. See #4249 As a workaround @JonasFranzDEV option will likely work for you.
