### ISSUE TITLE
gitea can not escape [[ ]] pair in markdown

### ISSUE THREAD

**Issue by laoshaw** [go-gitea/gitea#4346]
- Gitea version (or commit ref):
- Git version: 1.4.2
- Operating system: ubuntu 16.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

I was tying to document a bash code snippet that contains [[ ... ]] and it will never show up after I saved it, not even with using `...` or ``` code ``` , the [[ ]] pair just disappears

**Comment by ghost** [comment]
Same as #2168.

**Comment by daviian** [comment]
Duplicate of https://github.com/go-gitea/gitea/issues/2168
