### ISSUE TITLE
[Translation] delete_inactivate_accounts -> Delete all inactive accounts

### ISSUE THREAD

**Issue by Pofilo** [go-gitea/gitea#4354]
- Gitea version (or commit ref): _Not relevant_
- Git version: _Not relevant_
- Operating system: _Not relevant_
- Database (use `[x]`): 
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

In the admin page, in the Dashboard -> Operations, the first operation (in English) is:
`Delete all inactive accounts`

However, I wanted to know what inactive means (1 week, 1 month, 1 year ?). After some researches, I found that the string is the translation of `delete_inactivate_accounts` which calls the function `DeleteInactivateUsers` of `models/user.go`.
If we look at the function, it deletes users not activated.

So there is a misunderstanding between _inactive_ and _inactivate_. It seems that other languages are also badly translated. How can we fix the meaning of the function in all the different languages ?

**Comment by daviian** [comment]
@Pofilo Except en-US all translations are managed in crowdin https://crowdin.com/project/gitea . Changes in en-US need a PR.
