### ISSUE TITLE
why When gitea Run as Windows Service Mode can not get the config,but succ in command type?

### ISSUE THREAD

**Issue by wadereye** [go-gitea/gitea#4356]
- Gitea version (or commit ref):1.4.3
- Git version:2.1.2
- Operating system:Windows 2008 R2
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ X] No
  - [ ] Not relevant
- Log gist:

## Description
When I use Command mode,I start gitea   normal，and then ,I　can sign in the website,and use all the function very well.

But I try to close the command window,and register the gitea as windows service as the follow command:
sc create gitea start= auto binPath= ""C:\gitea\gitea.exe" web --config "C:\gitea\custom\conf\app.ini""
I am sure I　replace the dir to my local dir.
and the service start well,I can also open the website.
but ,I can not sign In.And the website remind me user login error.
then, I Remove the service,and try to open in command window.it work well.
then,I run as windows service again.I got the same error as before.

any body has the same error?or what is the wrong way I　did?

Thanks.
...

**Comment by lafriks** [comment]
Because windows service working directory is always c:\windows\system32. You need to define gitea data directory system environment variable with the gitea data directory

**Comment by wadereye** [comment]
Thanks,I Got it.thank you very much!

**Comment by fipcomatt** [comment]
@lafriks can you state explicitly what the "gitea data directory system environment variable" is named? I've tried setting 'GITEA_DATA', 'GITEA_DATA_DIR', 'APP_DATA_PATH', 'GITEA_CUSTOM_DIR', and 'GITEA_WORK_DIR' and none seem to have any effect.

**Comment by lunny** [comment]
Maybe we need update docs about windows service best practice.
