### ISSUE TITLE
[Security] CSRF Vulnerability on API

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#4357]
- Gitea version (or commit ref): every version with swagger api
- Git version: not relevant
- Operating system: not relevant
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

**Comment by lunny** [comment]
Because Gitea's UI are also using some APIs, so the APIs support many authorizations(session is one of them). But have you found any missing permissions checking? Could you send a security email to security@gitea.io?

**Comment by cezar97** [comment]
> Because Gitea's UI are also using some APIs

Oh, right.
Regarding missing permission, no I haven't found any. I was only showing that if the user session can be used to authenticate the API, this can be abused as described above. Didn't know it was an intended result.
Just for the record, what if this is used to add a key to a repository? Then someone would have read / write access to it ( even if private ). That's worse than adding an email that can't even be used to reset the password ( API can't set an email as primary ), as I said in the issue description.
I haven't any other info to send over email.

**Comment by lunny** [comment]
I think you are right. Maybe we should use different routes for UI and APIs.

**Comment by cezar97** [comment]
The easiest fix I can suggest is that the Gitea's UI, instead of using session, use it's own token like the ones in user settings and so then the API can reject session as an authentication factor. Not sure how this token should be handled ( It is shown in the settings? It can be regenerated by the user? ), but at least this approach doesn't require a complete API and UI's change. BTW, this should be generated when user is created and maybe a migration ( ? ) for existing accounts.

**Comment by techknowlogick** [comment]
Perhaps we could use the CSRF token as a second factor

**Comment by cezar97** [comment]
I agree with you @techknowlogick.
Session authentication with a CSRF check would fix it.

**Comment by beeonthego** [comment]
Is someone working on this issue now? if not, I will prepare a PR and check whether a token (or basic auth) has been used to authenticate. the check can be added to reqToken handler. There are a few minor changes, non breaking.
