### ISSUE TITLE
1.5.0-rc1 does not use 1.5.0-rc1 as version

### ISSUE THREAD

**Issue by jonasfranz** [go-gitea/gitea#4359]
- Gitea version (or commit ref): 1.5.0-rc1

## Description

Gitea shows as version in footer: "280ebcb" but it should be "1.5.0-rc1".
I'm using docker with `gitea/gitea:1.5.0-rc1`.

## Screenshots
![screenshot-2018-7-4 gitea jonas franz software](https://user-images.githubusercontent.com/5757182/42269803-74035d42-7f7f-11e8-9241-3968e63b454f.png)

**Comment by lafriks** [comment]
Yeah sees to be something with drone git@next plugin.
Steps to reproduce problem (what also git@next plugin does):
```
$ git init
Initialized empty Git repository in ...

$ git remote add origin https://github.com/go-gitea/gitea.git

$ git fetch --depth=50 origin +refs/tags/v1.5.0-rc1:
remote: Counting objects: 5768, done.
remote: Compressing objects: 100% (4948/4948), done.
remote: Total 5768 (delta 757), reused 4192 (delta 517), pack-reused 0
Receiving objects: 100% (5768/5768), 18.50 MiB | 7.89 MiB/s, done.
Resolving deltas: 100% (757/757), done.
From https://github.com/go-gitea/gitea
 * tag               v1.5.0-rc1 -> FETCH_HEAD

$ git checkout -qf FETCH_HEAD

$ git describe --tags --always | sed 's/-/+/' | sed 's/^v//'
280ebcb
```
