### ISSUE TITLE
[Bug] Deleting account updates repository time

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#4361]
- Gitea version (or commit ref): 2e3475f
- Git version: not relevant
- Operating system: not relevant
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

**Comment by daviian** [comment]
@cezar97 
Thanks for reporting. Do you accidently know if this is a regression from 1.5-rc?

**Comment by cezar97** [comment]
Can't get hands on a stable release at the moment so I've just test it on try.gitea.io. I'm sorry.
