### ISSUE TITLE
Options to send outbound HTTP requests via a HTTP proxy

### ISSUE THREAD

**Issue by silverwind** [go-gitea/gitea#4364]
To mirror a HTTPS-hosted repository, I recently had the need to send outbound HTTP requests from gitea via a HTTP proxy server, but found that gitea does not seem to come with a configuration option to define such a proxy.

I imagine we could have options like this (prefixed with OUTBOUND to avoid confusion with options concerning inbound requests):
```
[server]
OUTBOUND_HTTP_PROXY=https://1.2.3.4
OUTBOUND_HTTPS_PROXY=https://1.2.3.4
````

**Comment by silverwind** [comment]
> export environment variables

Thanks, this worked for me. Shall we close this issue?

**Comment by lafriks** [comment]
Yes, I think it can be closed as no need to reinvent wheel if OS already provides such functionality

**Comment by silverwind** [comment]
Actually, it's not the OS providing this, but golang itself ;)

**Comment by lafriks** [comment]
in Gitea case yes, GoLang provides that but other utilities will use it also so it's system-wide setting :)
