### ISSUE TITLE
gitea dump not sucess by file lock

### ISSUE THREAD

**Issue by tldzyx** [go-gitea/gitea#4372]
- Gitea version (or commit ref): gitea-1.4.3-windows-4.0-amd64.exe
- Git version: git version 2.18.0.windows.1
- Operating system: Windows Server 2008 R2
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:
**file lock when dump**

## Description
When I try the gitea dump command, it's faulure by a file lock, see below picture.
...

## Screenshots

![image](https://user-images.githubusercontent.com/5987706/42306294-0e9f79a8-8061-11e8-9fb5-b699b23a4c79.png)

**Comment by lunny** [comment]
Maybe that's a problem to dump the indexer files.

**Comment by tldzyx** [comment]
just simply stop gitea service, then dump, finally start gitea service, the backup will be sucess. but the gitea service really stop during the backup term.

**Comment by lafriks** [comment]
closing as answered

**Comment by M0ns1gn0r** [comment]
Well, that's a workaround, of course. But I cannot afford to stop gitea just to make a backup. I also believe that the *.lock file doesn't contain any meaningful info and is not needed to be backed up at all.

@lafriks Can you filter out `store.lock` during backup?

**Comment by lafriks** [comment]
Please feel free to submit PR for this but taking backup of running software is mostly not a good idea as you can get backup of inconsistent state
