### ISSUE TITLE
Old version of jQuery (1.11.3) 

### ISSUE THREAD

**Issue by kjellkvinge** [go-gitea/gitea#4384]
Ref https://github.com/gogs/gogs/issues/5318

The 1.x branch is not supported anymore, but it should be possible to upgrade to 1.12.6 which is from may, 2016. 1.11.3 is from april 2015.

Would ut be possible to move to the supported 3.x branch?

**Comment by ghost** [comment]
Why not just bump the major?

**Comment by kjellkvinge** [comment]
It's more work to migrate to 3.x. stuff might break and some (very old) browsers would not be supported. But moving to 3.x would stil be the best soullution IMHO. 

 https://jquery.com/upgrade-guide/3.0/

**Comment by thebrownfox** [comment]
Wouldn't be better to drop all of that instead of major or minor update?
You know, there is no need to support old browsers. This is kind of app that is used primarly by devs who use to have up to date sw. Also, you can support older browsers without jquery. I've noticed there is vuejs in gitea and the jquery is the last thing you want to do in that case. Let it die

**Comment by techknowlogick** [comment]
Let's not assume that all devs have latest machines. This project has users with all kinds of resources, for example my laptop is as powerful as a rasperrypi, and some enterprises are still stuck on 32bit versions of windows 7.

That being said we have a baseline for browsers that we do support (the same baseline that semantic UI has).

It should also be noted that not all users of Gitea have JS enabled in their browser, and the FSF recommends that for ethical code hosting JS is not required: https://www.gnu.org/software/repo-criteria.en.html

I am supportive of moving to the latest in the 1.x branch of jQuery in hopes of eventually replacing all functionality that requires it with Vue.js.

**Comment by ghost** [comment]
> I am supportive of moving to the latest in the 1.x branch of jQuery in hopes of eventually replacing all functionality that requires it with Vue.js.

I'm happy to help on the Vue.js implementation when the time comes. And thanks for linking to the GNU website I was on it for about 2 hours yesterday reading about censorship and [Microsoft Malware](https://www.gnu.org/proprietary/malware-microsoft.html).

**Comment by vintprox** [comment]
Vue is love 😁 I hope somebody will be able to figure out how to put Vue 3 (once it's released) in Gitea, which makes sense for unlabored frontend interface for plugins and stuff!
