### ISSUE TITLE
Pushing to fresh repo while on a non-master branch confuses the web interface

### ISSUE THREAD

**Issue by AuspeXeu** [go-gitea/gitea#4385]
- Gitea version: 1.4.3
- Git version: 1.8.3.1
- Operating system: CentOS
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist: N/A
## Description
Web interface shows non-existing branch. As can be seen in the screenshot. The branch `next` is displayed by the web interface, however only a branch `master` exists. This situation was created as follows.

1. Create a new repo
2. Check out a different repo locally and switch to a non-master branch
3. Use this repository to push to the new gitea repo created in 1.
4. The branch on this new repo is now for example `next`
5. Create a new `master` on this repo and delete the `next` branch
6. The web interface will still show `next` as the current branch

## Screenshots
![screen shot 2018-07-06 at 11 41 38](https://user-images.githubusercontent.com/2115696/42374889-a047889a-8111-11e8-883f-29d6aa6168af.png)

**Edit:** This also affects all the links in the directory. You have to explicitly switch to master branch, otherwise all file links will lead you to a 404 page.

**Comment by lunny** [comment]
When a default branch is deleted which branch will be the default branch on git?

**Comment by 6543** [comment]
fixed
