### ISSUE TITLE
[Proposal] New admin API Routes

### ISSUE THREAD

**Issue by cleverer** [go-gitea/gitea#4387]
In order to delete a user via the API, he mustn't be part of any organisation. Right now it's not possible to get all orgs of an user. I propose a new Route `GET /api/v1/admin/users/:username/orgs`. The route already exists, but without the admin, so it only returns public memberships. I think, as admin you should be able to see those.

Another solution would be a listing of all orgs (`GET /api/v1/admin/orgs`). The user then could be tested for org membership for all orgs.

A third route which is missing for me is `GET /api/v1/admin/users`, which would be essential for user syncing.

**Comment by shashvat-kedia** [comment]
@lunny @cleverer Can I work on this? I am new to this project could you help me get started? Thanks

**Comment by cleverer** [comment]
>@lunny @cleverer Can I work on this? I am new to this project could you help me get started? Thanks

@sd1998 I'd love to help, but unfortunately I don't know more than you...

**Comment by lunny** [comment]
@sd1998 You are welcome. You can find codes about `GET /api/v1/users/:username/orgs` as an example.

**Comment by lunny** [comment]
The `/api/v1/admin` APIs is for site administrator. I think it could do anything for management convenience.

**Comment by zeripath** [comment]
Heya! Have you considered using the Sudo API feature to get this information? That way you can do this in Gitea 1.6.0 without waiting for these new APIs. 

A lot of deficiencies with the API can simply be workarounded using Sudo.

**Comment by 6543** [comment]
close this, as zeripath pointed to sudo option ...

If a specific api is needed, just as for that specific in a new issue
