### ISSUE TITLE
Show summary of reviews

### ISSUE THREAD

**Issue by jonasfranz** [go-gitea/gitea#4390]
Code reviews should be shown at the sidebar of a pull request like GitHub does.

Blocked by #3748

**Comment by lafriks** [comment]
I would prefer them to be shown just before merge button. Sidebar is getting too crowded

**Comment by lunny** [comment]
I would like @lafriks' idea. Github also show all reviewers before merge button. But github shows suggest reviewers on sidebar.

**Comment by jonasfranz** [comment]
#3748 got implemented! Ready to get implemented.
