### ISSUE TITLE
use lfs crash with TortoiseGit

### ISSUE THREAD

**Issue by RelicOfTesla** [go-gitea/gitea#4392]
- Gitea version (or commit ref): gitea-1.5.0-rc1-windows-4.0-386
- Git version: git version 2.18.0.windows.1
- TortoiseGit: **2.6.0.0**
- Operating system: win7
- Database: SQLite

## Description
```
mkdir a
cd a
git init
git lfs track "*.msi"
git add .gitattributes
echo aaa>a.msi
git add a.msi
git commit -a -m "init"
git remote add origin relicOfTesla@RelicOfTesla.iok.la:RelicOfTesla/bigfile.git
git push -u origin master
cd ..
mkdir b
git clone relicOfTesla@RelicOfTesla.iok.la:RelicOfTesla/bigfile.git
cd bigfile
explorer.exe .
## 1.right click directory menu.
## 2. click [TortoiseGit - commit]
## now. TortoiseGit crash...
```
**But  use github.com. it's OK. not crash .**

**Comment by lafriks** [comment]
Is there are anything relevant in gitea.log? Also it would be good to report this also to tortoisegit project

**Comment by RelicOfTesla** [comment]
gitea.log nothing error log. 
I don't known how can i see the tortoisegit.log
Im think TortoiseGit support lfs. because it's stable with github.com.
It's only crash in gitea clone (LFS)repository

**Comment by lafriks** [comment]
Could this be related to this: https://gitlab.com/tortoisegit/tortoisegit/issues/3164

**Comment by RelicOfTesla** [comment]
thanks
