### ISSUE TITLE
Adding custom settings page

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#4393]
- Gitea version (or commit ref): 1.4.1
- Git version:  2.17.0
- Operating system: W10
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ X] Not relevant
- Log gist:

## Description
I customize the navbar.tmpl in 'custom\templates\user\settings' to include a link to my own, new settings tab page. But when I add the matching file with the same name in 'custom\public\user\settings' it does not work. Am I doing it wrong? 
...

## Screenshots
![ISettings page with my new tab "Theme"](https://i.imgur.com/GCLX4x4.png)
![IError](https://i.imgur.com/obEr58e.png)

**Comment by gsantner** [comment]
would it be possible to get some "default unused" custom routes, where the admin could place some custom logic in a file while still being able to use normal release binaries? Like `/custom/1/`, `/custom/2` ?

**Comment by daviian** [comment]
This would be some kind of plugin system.
There's already an issue about that (https://github.com/go-gitea/gitea/issues/661), however since go doesn't support it natively on every platform there is currently no way to support that.

**Comment by lafriks** [comment]
As @daviian noted that this should be done as part of #661

**Comment by techknowlogick** [comment]
Closed as this is marked as won't fix. Another slightly related ticket is #2012
