### ISSUE TITLE
Pictures in wiki acting just like pictures in main project.git

### ISSUE THREAD

**Issue by a7hybnj2** [go-gitea/gitea#4395]
Allow Picture in the WIKI #4376

No I did not mean to make it easier. I did indeed upload pictures to the wiki via git and referenced those pictures with MD in the wiki files. This resulted in a logon popup to be displayed while accessing that page. When moving the same image and md file to my main project.git directory I was not prompted for a logon.

**Comment by gsantner** [comment]
The refs in general seem to have stopped working. Mirroring e.g. <https://github.com/mattdelfante/Blackjack> makes all images disappear.

Image ref on gitea resolves to <https://%gitea%/BlackJack/readMeImages/inGamePicOne.PNG>, which does not exist.Works fine on GitHub

**Comment by a7hybnj2** [comment]
In my case I had a folder "content" with the pictures in it then the .md would look at that folder. When I have the .md file and "content" on the .git side of things it works just fine. but If I mv/cp that same .md file and content folder to the wiki side it doesn't work and I get hit with a logon prompt which even if I logon it still doesn't seem to work.

I have also tried having the content on the .git side and having the wiki.md reference that but, I could not get that to work either.

**Comment by a7hybnj2** [comment]
What don't close it. It is still an ongoing issue. There just has been no progress made. More issues referencing this same issue have been made since this one.

Bad Bot!
