### ISSUE TITLE
Request: understanding binary updates

### ISSUE THREAD

**Issue by flobee** [go-gitea/gitea#4396]
Hi 
Can you please help/ guide me to get in touch.
 i have added [1] because of missing docs and i try to find a way to update related docs to sent a pull request and end up to this message.

My request: What happens at the DB side when upgrading to a new binary version when just using eg. [2]?

[1] https://github.com/flobee/public/blob/master/shell/gitea/INSTALL_gitea_README.md.sh
[2] https://dl.gitea.io/gitea/master/gitea-master-linux-amd64

Kind regard
Florian

**Comment by jonasfranz** [comment]
If you will install the master version you linked, it's going to upgrade your database to the current database version. This includes some migrations which will run. These migrations may contain some refactoring, new columns etc.

**Comment by flobee** [comment]
Hi, thx for reply.
hmm. Which event triggers the mirgration/setup for the configured db? ./gitea web ? or other action/s (also?) ? 
Or is it just implemented in the master binary downloads? If so: Wouldnt it makes sence to have a './gitea [setup|mirgration|upgrade]' action then to skip those parts from the regulary work and offer it for all versions self build/ binary/ cross platforms?

**Comment by jonasfranz** [comment]
Everything which uses the database will check which database version you're using and will upgrade automatically. This mechanism is implemented in all version / releases including master, and regualar releases like 1.5.0.

**Comment by jonasfranz** [comment]
This action will only be triggered if necessary. Where is the point of having a separate command for this since it is required for the upgrade?

**Comment by flobee** [comment]
Hi, I'm just asking/wondering: If any user which logs in (ssh or web interface), an db migration event will be tiggered? Or only the none deamonized events? Then it would be "./gitea web"? 

> This action will only be triggered if necessary

A kind of unclear for me because: i have to connect to the Db first to check if its not up to date. If each request to the binay will trigger those events. its just a situation of time/number of users when the server crashes :+1:  just a thought...
I think its not implemented in that way but i dont know and the docs not telling about upgrades... so i try to bring it up :)

**Comment by jonasfranz** [comment]
@flobee The migration will be started after you exchanged to binary and after you start gitea's webserver via ./gitea web or ./gitea.

**Comment by flobee** [comment]
:) thx :+1:

**Comment by flobee** [comment]
Adds project support for [debian (9)](https://wiki.debian.org/Gitea#Install_gitea_using_binay_packages_from_orgin)
