### ISSUE TITLE
Change the email for vulnerabilities

### ISSUE THREAD

**Issue by tszym** [go-gitea/gitea#44]
For Gogs, there were an email address in the `README` to report critical security issues.
In gitea's `README`, the address is still the same, and prevent active maintainers to get the reports and fix security issues.

Please active maintainers of gitea, update the `README` to advertize an email adress for security issues that will be read.

Next step could be a PGP key, but that's not the purpose of this issue.

Regards

**Comment by lunny** [comment]
Good idea.

**Comment by lunny** [comment]
Done. 1e50c8464c5906ed405d1109ba68fc0b790c45db
