### ISSUE TITLE
migrate  gerrit  with gitea

### ISSUE THREAD

**Issue by wjx0912** [go-gitea/gitea#4400]
gerrit is a useful code review system(https://www.gerritcodereview.com/)

has anyone migrate   with gitea(use docker) success?

**Comment by jalcine** [comment]
"Merge" might be a bad title for this.

Do you mean for Gerritt to do some kind of auto-importing of Gitea hosted repositories? I could see the use-case for that.

Gitea and Gerritt are definitely two separate projects tho.

**Comment by wjx0912** [comment]
@jalcine 
where is the use-case?

**Comment by jalcine** [comment]
Gerrit could serve as the project tracking and code review tool whereas Gitea would manage just repository hosting.

I'm aware that Gerritt has that functionality as well.

**Comment by wjx0912** [comment]
so, How to integrate them together?

**Comment by wjx0912** [comment]
@jalcine 
still understand?  Stupid IQ!
