### ISSUE TITLE
[Theme] Arc Green needs a little more love

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#4403]
Opening an issue here since [theme repo](https://github.com/go-gitea/gitea-darkmode) now deprecated with the inclusion of `arc-green` into the main codebase.

New theme looks great but has some usability issues which need to be addressed:

### Wiki formatting toolbar icons invisible

![git habd as_comfusion_after-dark_wiki_home__edit iphone x](https://user-images.githubusercontent.com/440298/42447364-2f2f4d3a-83ac-11e8-863f-55fe23992ab5.png)

Original issue: https://github.com/go-gitea/gitea-darkmode/issues/6
Unmerged PR: https://github.com/go-gitea/gitea-darkmode/pull/8

### Zebra striping in README tables unreadable

![git habd as_comfusion_after-dark iphone x](https://user-images.githubusercontent.com/440298/42447467-8c6d120c-83ac-11e8-8cbc-02e648945630.png)

Original issue: https://github.com/go-gitea/gitea-darkmode/issues/3

### Highlight.js Improperly rendering fenced code blocks

![git habd as_comfusion_after-dark iphone x 1](https://user-images.githubusercontent.com/440298/42447551-ded02b7e-83ac-11e8-9b97-d8725c3376f8.png)

Original issue: https://github.com/go-gitea/gitea-darkmode/issues/4

**Comment by ghost** [comment]
@techknowlogick the updates look fantastic and I see you also darkened the background on the wiki edit page which was a bit of an eyesore. in review I see the zebra striping hasn't carried over to tables on the wiki pages themselves ([example](https://git.habd.as/comfusion/after-dark/wiki)). want me to open another issue for that?

<img width="630" alt="screen shot 2018-07-16 at 4 39 44 pm" src="https://user-images.githubusercontent.com/440298/42749693-23fc25b2-8917-11e8-9548-98a474d4eec5.png">

**Comment by techknowlogick** [comment]
@jhabdas a new ticket is good, but a new PR would be even better.

**Comment by ghost** [comment]
Sounds good. I'll send a pull up after I find a few more nits.
