### ISSUE TITLE
DEFAULT_PRIVATE not woring when enabled

### ISSUE THREAD

**Issue by leepfrog-ger** [go-gitea/gitea#4405]
- Gitea version (or commit ref): 1.4.2
- Git version: not relevant
- Operating system: Windows
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant

## Description

Setting `DEFAULT_PRIVATE = true` has no effect for me. No matter if that option is set to true or false the "private" checkbox is not ticked.

Setting `FORCE_PRIVATE = true` works as expected (checkbox is ticked and cannot be unticked)

**Comment by seese** [comment]
I think "true" is not a valid value for the key DEFAULT_PRIVATE. Try "private" instead.

; Default privacy setting when creating a new repository, allowed values: last, private, public. Default is last which means the last setting used.
DEFAULT_PRIVATE = last
