### ISSUE TITLE
NotFoundOrServerError()   [id: 0, uid: 0, owner_name: vendor, name: plugins]

### ISSUE THREAD

**Issue by chliang** [go-gitea/gitea#4410]
- Gitea version (or commit ref):1.5.0-rc1
- Git version:2.18
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:
```
2018/07/10 10:46:53 [...s/context/context.go:147 NotFoundOrServerError()] [E] GetRepositoryByOwnerAndName: repository does not exist [id: 0, uid: 0, owner_name: vendor, name: plugins]

```
## Description

...

**Comment by lafriks** [comment]
Need more information on when such error is displayed and for what url

**Comment by ghost** [comment]
As the OP is a bit quiet and I have exactly the same symptoms I like to give some informations on my installation:

Gitea version 1.5.0, but I saw it also on 1.4.3 (and ignored it)
Using MySQL/MariaDB as the database, xorm.log shows no errors.

I noticed it, when using a crawler for generating a sitemap. When remote systems are accessing my installation, it happens quite seldom. So it's more an annoyance than a real issue (for me).

The log message, only the "name:" differs, the other fields say the same:
`2018/08/19 23:16:10 [...s/context/context.go:147 NotFoundOrServerError()] [E] GetRepositoryByOwnerAndName: repository does not exist [id: 0, uid: 0, owner_name: vendor, name: assets]`

The following links, referenced from /vendor/librejs.html (the "JavaScript licenses" page) create this issue:
- /vendor/assets/swagger-ui/
- /vendor/assets/font-awesome/fonts/
- /vendor/assets/font-awesome/css/
- /vendor/plugins/pdfjs/
- /vendor/assets/octicons/
- /vendor/plugins/u2f/

**Comment by ghost** [comment]
@lafriks What additional info do you need, so the "status/needs-feedback" label can be removed?

**Comment by LaughingBlue** [comment]
My Gitea version was 1.5.3 and after got this problem I upgrade to the latest 1.6.0, but the problem still existed.
I reproduce this symptom by running gitea in terminal with 
`$ gitea web  --port 443`,
after that I stop the gitea and restart it again without `port` variable like
 `$ gitea web`
and then I can't modify my repos with these kinds of error msgs
```
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'MyGiteaAddress.git'
```
And got the log msg as same as yours
```
2018/11/26 22:01:21 [...s/context/context.go:147 NotFoundOrServerError()] [E] GetRepositoryByOwnerAndName: repository does not exist [id: 0, uid: 0, owner_name: vendor, name: plugins]
```
I solve this problem by remove the line `LOCAL_ROOT_URL   = http://localhost:443/` in config file`app.ini` section`[server]` . And then restart gitea again, all works fine.

Hope this helps.

---

### EDIT:
Sorry, I just noticed that I've got these error log for a long time. The earliest one was 10/23
```
2018/10/23 00:55:15 [...s/context/context.go:147 NotFoundOrServerError()] [E] GetRepositoryByOwnerAndName: repository does not exist [id: 0, uid: 0, owner_name: vendor, name: plugins]
```
So my problem was only "Can't modify my repos after running `gitea web  --port 443`" and seems that not relate to the error log.

**Comment by lafriks** [comment]
@chliang can you confirm that local_root_url is valid for you?
