### ISSUE TITLE
[Bug] Notifications remains after repository deletion

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#4416]
- Gitea version (or commit ref): 3e445cc
- Git version: not relevant
- Operating system: not relevant
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

**Comment by cezar97** [comment]
Duplicate of #3105?

**Comment by cezar97** [comment]
@lunny if you could update the title in issue #3105 including all the repository notifications and not only of issues deleted, this can be closed as duplicate as they are nearly the same. Or you want them separated?
