### ISSUE TITLE
[Privacy] Gitea leaks hidden email addresses

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#4417]
- Gitea version (or commit ref): 3e445cc
- Git version: not relevant
- Operating system: not relevant
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

**Comment by msg7086** [comment]
Just hit this bug due to the CSRF issue. Got a long list of Email addresses for every victim of that issue.

(Automatically followed OP, then got notifications of all events, leaking the Email addresses.)

![email-leaking](https://user-images.githubusercontent.com/206155/43812115-b50fe426-9a8d-11e8-9575-ddcc66fd5093.png)

**Comment by techknowlogick** [comment]
For anyone looking to solve this issue, the line you can change is here: https://github.com/go-gitea/gitea/blob/95f2e2b57beedcdeb2b9623dc86e26f252fdd7bd/models/issue_mail.go#L102 it passes all emails into the function, but what could be done is to loop over emails and then individually pass them into the `SendIssueMentionMail` function (the last argument in that function is where the emails get passed in)

**Comment by HenrikBengtsson** [comment]
Not a complaint, just asking for clarification: This fix means that email notifications for issues will be sent out to each watcher independently starting with Gitea 1.5.1, correct?  This means that users will no longer be able to do 'Reply All' to continue an email-only thread on the topic, correct?

**Comment by lafriks** [comment]
@HenrikBengtsson yes
