### ISSUE TITLE
Security / Display Issue with Commits - who commited?

### ISSUE THREAD

**Issue by cht47** [go-gitea/gitea#4422]
- Gitea version (or commit ref): f096e69 / 1.5
- Git version: 2.16.4
- Operating system: CentOS 7.5
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
I've added some accounts for students which where working on a research project. It seems like they created multiple SSH Keys and added it to their account to get access to the repository but they didn't set their name/mail address correctly on some computers. Now in the commit history I don't see who did the commit as the name is not clickable and not linked to the gitea account who has access to the private repo.

A solution would be to link every user to the gitea user who has that public SSH key associated with his account. 

I'm new to git so sorry if there is an easy git command to get out who commited, but I expect to see this information in gitea :)

## Screenshots

![gitea_issue](https://user-images.githubusercontent.com/2283180/42569375-9ed9257e-8510-11e8-9da6-c6862914e4a9.png)

**Comment by lafriks** [comment]
Currently gitea does not support limiting of pushing only own commits. So whatever is written in commit is what will be later used to match users

**Comment by lafriks** [comment]
I think there was issue for such feature but I can't seem to find it so leaving this one open for now
