### ISSUE TITLE
LDAP user sync does not work (here)

### ISSUE THREAD

**Issue by cklabautermann** [go-gitea/gitea#4433]
- Gitea version (or commit ref): 1.4.0, 1.4.2,1.4.3,1.5.0RC2
- Git version: 2.7.4-0ubuntu1.4
- Operating system: Ubuntu Server 16.04.4 AMD64
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description

my auth setup includes 
- bind to a ms-AD unencrypted 
- with a RO userid
- a user search base where the users are
- a user filter pointing to a group in a **completely different** OU
- user synchronisation activated (at least marked)

Things that work:
- manually adding a user and authenticating them via LDAP. If a user is not member in the filter group, they can not login.

Things that do not work:
- users in my filter group being automatically synchronized

Additionally all users authenticating via ldap **get deactivated** if I dare to execute a manual user synchronisation via web frontend.

Can anybody tell me what I am doing wrong?
Not sure if screenshots could help here but I can upload some on demand.

Thanks,
Claudio

**Comment by lunny** [comment]
@cklabautermann is this still a problem?

**Comment by cklabautermann** [comment]
@lunny yes, unfortunately it still does not work. Can you help?
Thanks in advance
