### ISSUE TITLE
[LDAP-Authentication] Special Characters

### ISSUE THREAD

**Issue by neurolag** [go-gitea/gitea#4434]
- Gitea version (or commit ref): c784ac5
- Git version: 2.7.4
- Operating system: `Linux 4.4.0-042stab130.1 #1 SMP Tue May 22 09:19:34 MSK 2018 x86_64 x86_64 x86_64 GNU/Linux`
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] ~~MySQL~~ MariaDB
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log:
```
2018/07/12 13:13:30 [W] Failed to login '~Tutti~' via 'RomHackersWorld': Invalid pattern for attribute 'username' [~Tutti~]: must be valid alpha or numeric or dash(-_) or dot characters
```
https://github.com/go-gitea/gitea/blob/master/models/login_source.go#L405-L407

## Description
Some members of our community (our community-leader, for example) have special characters in their username which natively is supported by LDAP and also gitea.  
His username, for example, is `~Tutti~`.

When logging in a strange error message appears (see screenshot below).  
The user isn't migrated and is unable to log in.

I think the way to check the username when logging in via LDAP should be changed a little.
Thanks for the support in advance

## Screenshots
![image](https://user-images.githubusercontent.com/7085564/42632047-439b8a7c-85dc-11e8-8077-9a7b7e0232c4.png)

**Comment by SBird1337** [comment]
I can confirm that users with, as far as I can tell, non-alphanumeric characters in their username cannot be migrated from LDAP to Gitea (In fact can't even get past the Gitea Authentication Module)

Since both Gitea and LDAP support more than alphanumeric characters I don't think it is intended that the Gitea LDAP Module does not.

**Comment by HoffmannP** [comment]
Our University does not have any unique special-char-free speaking names in it's Active Directory. I hence have to use the non-speaking cryptic username alika X4NA4P. It's would be nice if gitea would just filter illegal characters at least as a workaround (eg. "Peter Hoffmann" -> "Peter_Hoffmann" oder "PeterHoffmann" or what ever).
Would a pull request adding this functionality be accepted?

**Comment by neurolag** [comment]
This issue still persists.
Please reopen this issue.
