### ISSUE TITLE
[Accessibility] URL Parsing issue when generating links in Issue editor

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#4435]
- Gitea version (or commit ref): efd202f
- Git version: n/a
- Operating system: Stretch
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
  - [x] Not sure, it's not in English at current
- Log gist: n/a

## Description

URLs with `id` query string parsed into two separate links, example here:
https://git.habd.as/comfusion/after-dark/issues/1#issue-2

See screenshot below. Notice the right hand side of the `=` is an internal link whereas the rest of the link is expected save for the query string value as exhibited in the above.

## Screenshots

<img width="747" alt="screen shot 2018-07-12 at 7 44 34 pm" src="https://user-images.githubusercontent.com/440298/42631219-1138fdf0-860c-11e8-96ce-e89be7a07896.png">

**Comment by davidak** [comment]
I noticed the same problem with links like: https://medium.com/liberapay-blog/the-second-year-of-liberapay-c017b73c9721

The last part is recognized as commit ID.

**Comment by ghost** [comment]
@davidak just saw your related bug. please let me know if I should close this or, if related, let's link them :relaxed:

**Comment by davidak** [comment]
@jhabdas i'm not sure which one you mean. feel free to link it when you think it's related. I would not consider my last bugreport about URL detection related. This report is fine.

**Comment by ghost** [comment]
https://github.com/go-gitea/gitea/issues/4496

**Comment by jhabdas** [comment]
@stale keep

**Comment by ghost** [comment]
@stale keep

**Comment by jhabdas** [comment]
wow. github is not changing the casing of my text. oof. try sending a message to @stale (all-lower). that can't be good.

**Comment by ghost** [comment]
wow. github is now changing the casing of my text. oof! try sending a message to @stale (all-lower). that can't be good.
