### ISSUE TITLE
redirect to login page after account activation

### ISSUE THREAD

**Issue by davidak** [go-gitea/gitea#4439]
- Gitea version (or commit ref): 1.1.0+1408-ge87c540a
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io: no, i got no mail
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

When a user creates a new account and clicks the activation link in the e-mail, he want's to login and use the account. So redirect him to the login page and not to the homepage.

**Comment by adelowo** [comment]
I would take a look at this again this weekend

**Comment by davidak** [comment]
I tested again on https://try.gitea.io (Gitea Version: 477ef46).

After registration, i'm directly logged in and don't got an e-mail. So this problem does not longer occur.
