### ISSUE TITLE
Is 1.5 released?

### ISSUE THREAD

**Issue by freswa** [go-gitea/gitea#4444]
While on Github the latest release is 1.4.3 and that's also the case for discourse.gitea.io, for dl.gitea.io the release of version 1.5 is available for download.
So what is the latest release?

**Comment by lunny** [comment]
latest stable release is 1.4.3

**Comment by lafriks** [comment]
1.5.0-rc1 has been released that is why there is 1.5 in dl.gitea.io

**Comment by tomByrer** [comment]
Looks like v1.5 'final' is posted: https://dl.gitea.io/gitea/1.5/

**Comment by lunny** [comment]
@tomByrer that's release branch, not final.

**Comment by sondr3** [comment]
I understand the confusion though, there's no indication that the files in that directory are the RC version and not the final release. Naming them with their full release information is both easy and eliminates this problem entirely.

**Comment by fnordsh** [comment]
There's also a 1.5 tag in the docker repo. So this is not really version 1.5?
Is tag 1.4.3 really version 1.4.3? How to tell?
https://hub.docker.com/r/gitea/gitea/tags/

**Comment by lafriks** [comment]
Directories `1.4`, `1.5` are built from release branch so these directories always contain latest 1.4.x, 1.5.x version binary

**Comment by lafriks** [comment]
Final release will be in `1.5.0` directory

**Comment by lafriks** [comment]
@gertmenke 1.5.0-rc1 + backported fixes to release/1.5 branch

**Comment by fnordsh** [comment]
Ah, that esplains the different timestamps. :-)
