### ISSUE TITLE
Contributions system (Like GitHub)

### ISSUE THREAD

**Issue by DaMatrix** [go-gitea/gitea#4448]
(ommiting info, as this is a feature request)

Continuation of #3888

Can we have contributions like on GitHub? See https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/

**Comment by sondr3** [comment]
I didn't respond to the previous one but I have no idea what's up with OP in that one. I don't think it's an important feature, but a nice-to-have feature instead. I'd rather the focus of development for Gitea be on bigger issues and if this is so important for you, do it yourself or sponsor it.

My two cents at least.

**Comment by lunny** [comment]
duplicated with #6
