### ISSUE TITLE
Allow PRs to be marked as WIP (thus preventing them to be accidentally merged)

### ISSUE THREAD

**Issue by gergelypolonkai** [go-gitea/gitea#4453]
One thing I really miss from GitLab (I think this feature is non-existent on GitHub) is the ability to mark a pull request as WIP (Work in Progress). All GitLab MRs whose title begins with `WIP:` is blocked from being merged.

I don’t know if this would fit the plans for Gitea, but it could be definitely helpful for some.

**Comment by JulienTant** [comment]
Hi, i'm willing to try to implement this in gitea, but before I wanna make sure that you're not working on it on your side.

I imagine building this in two PRs :

1) Disable to ability to merge a PR when the title starts by `WIP:` (maybe we can make this configurable ?)
2) An hypotetical second PR to add "helpers" like : 
- "When the title starts with WIP:, add a button "remove WIP status" that edits the title to remove WIP:
- When we create a PR, add a description with a link like "[Add WIP: to the title](#) to prevent this PR to be accidentally merged"
