### ISSUE TITLE
LFS access token authentication

### ISSUE THREAD

**Issue by Andersbiha** [go-gitea/gitea#4454]
- Gitea version (or commit ref): 1.5.0-rc1
- Git version: 2.18.0
- Operating system: Ubuntu 16.04
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
The current LFS implementation lacks support for access token based authentication.
Due to this users with 2FA enabled is unable to interact with LFS repos.

As far as i can tell it should be pretty straightforward to implement this in the [parseToken](https://github.com/go-gitea/gitea/blob/181b3a8f0988ab729270279e6e12534cb52628cc/modules/lfs/server.go#L517) function in the LFS server module.

Let me know if i should look further into correcting this  :+1:

**Comment by jonasfranz** [comment]
Feel free to create a PR for this.
