### ISSUE TITLE
TLS certificates

### ISSUE THREAD

**Issue by sitilge** [go-gitea/gitea#4455]
gitea.io uses an invalid security certificate. The certificate is only valid for the following names: *.netlify.com, netlify.com Error code: SSL_ERROR_BAD_CERT_DOMAIN

**Comment by techknowlogick** [comment]
Which browser and OS are you using?

**Comment by sitilge** [comment]
`ff 61.0.1` and `arch 4.17.5`

**Comment by lafriks** [comment]
Seems correct letsencrypt certificate for me

**Comment by sitilge** [comment]
@lafriks apparently, something happened to the certificates. The question is - what exactly? I removed the old certs, loaded the new ones, they work perfectly now.

**Comment by techknowlogick** [comment]
@sitilge probably something was cached. Closing this issue now.
