### ISSUE TITLE
Removing Team Members causes Instance Corruption

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#4466]
- Gitea version (or commit ref): 1.4.3 (also 1.4.1)
- Git version: one of the latest
- Operating system: Windows Server 2012
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] MSSQL Server 2014 - 12.0.2000
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description
to reproduce:
1. create Organization
2. create Repository within Organization
3. Add Team and Team Member 
4. Remove added Team Member
Klick on on "Remove" ends with error:
  	err:	"  read tcp 192.168.1.120:56709->192.168.1.120:49398: i/o timeout"
	ok:	false

Then Gitea became useless for all users:
Loading Sites toggles between Error 500 and empty Organization/Repository list. Always Error 500 loading Issues and Pull Requests. Random behaviour (for example: once loaded another Profile).

Also can't clone (not allowed access) or push (repository not found) created repository. 
After restarting Gitea everything is fine but the Member was not removed.

**Comment by leepfrog-ger** [comment]
I think this is the same as my issue in #4362
