### ISSUE TITLE
500 in commit graph when commit description contain "DATA:"

### ISSUE THREAD

**Issue by m0xf** [go-gitea/gitea#4467]
- Gitea version (or commit ref): 1.4.3, fe78154
- Git version: 2.10
- Operating system: Windows
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (https://try.gitea.io/m0xf/test/graph)
  - [ ] No
  - [ ] Not relevant
- Log gist:

2018/07/18 19:56:15 [...uters/repo/commit.go:91 Graph()] [E] GetCommitGraph: Failed parsing grap line:* DATA:| (HEAD -> master)|8fbe54a333ecc27e55e137c8194d14fcdfd131ef|2018-07-18 19:56:10 +0300|m0xf|m0xf@yaru|8fbe54a|test DATA:. Expect 1 or two fields

## Description

If commit description contain "DATA:", gitea show 500 error on commit graph.

**Comment by kjellkvinge** [comment]
I think I have a fix for this. I could also make som tests for these kinds of issues (parsing commit messages in graphItemFromString() in models/graph.go)

This is kind of related to #1189.
