### ISSUE TITLE
Discuss manual backup (gitea dump)

### ISSUE THREAD

**Issue by issmirnov** [go-gitea/gitea#448]
Hello everyone,

Reposting gogits/gogs#2924 so that we can keep track of it here. 

There is a hidden command called `dump` that creates a zip file with the config (`custom/conf/app.ini`), `gitea-db.sql` and a nested zip of the repos. 

It would be really good to have this behavior documented on the website, and also some tips on how to perform a restore. The way I see it, one can download a fresh binary of gitea, set up the same file structure and somehow import the sql file. I personally have very little experience with SQL so am not sure how this is done.

I'm in the middle of moving servers, so would be happy to be the guinea pig on migrating a gitea installation. I'm also a huge fan of markdown so can help with documentation if needed.

---

- Operating system: Ubuntu 14.04 LTS
- Database:
  - [X] MySQL

**Comment by lunny** [comment]
You are right! And I think we need an enhanced dump which could dump-mysql or dump-sqlite and a restore command. Please feel free to send PR to go-gitea/docs to help us improve the documents.

**Comment by tboerger** [comment]
Maybe we can really integrate a restore command that imports everything that have been dumped before.

**Comment by lunny** [comment]
Of course we will.

**Comment by bkcsoft** [comment]
>  integrate a restore command that imports everything that have been dumped

I have a branch for that :trollface:

**Comment by lunny** [comment]
Please send a PR.

**Comment by lunny** [comment]
So I think this issue has been resolved for your PR? And now we need a restore command, but that should be another issue or PR.

**Comment by lunny** [comment]
@issmirnov

**Comment by issmirnov** [comment]
@lunny Agreed, let's close this one. Perhaps @bkcsoft can open a FR tracker / working PR if there's already some work done on implementation.
