### ISSUE TITLE
Redirect to LANDING_PAGE when logged in user opens /user/login

### ISSUE THREAD

**Issue by michaelschufi** [go-gitea/gitea#4480]
- Gitea version (or commit ref): 3e445cc
- Git version: 2.15.2
- Operating system: CentOS Linux release 7.5.1804
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
It would be nice if the LANDING_PAGE redirect also occurs when a user opens "/user/login".
I am not quite sure if this is a duplicate of the resolved issue #2893.

**Comment by lunny** [comment]
Please feel free to reopen it.
