### ISSUE TITLE
Can't change CanImportLocal in User Administration

### ISSUE THREAD

**Issue by Cyber1000** [go-gitea/gitea#4482]
- Gitea version (or commit ref): fe78154
- Operating system: ubuntu (within docker)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ x] No --> setting is within administration of users
  - [ ] Not relevant
- Log gist:

## Description
If I edit a user in administration view I can change the CanImportLocal flag, but after saving the flag vanishes ...
The message "Der Account „%s“ wurde aktualisiert." is a bug too, the message comes with %s, instead of the real user name.

## Screenshots

![image](https://user-images.githubusercontent.com/1142765/43009976-76a6e0ce-8c3f-11e8-84d7-b8dc73bd6026.png)

**Comment by techknowlogick** [comment]
`IMPORT_LOCAL_PATHS` is likely set to false in app.ini (or not set at all which then defaults to false). Please set to true, and try again. More information here: https://docs.gitea.io/en-us/config-cheat-sheet/

**Comment by Cyber1000** [comment]
IMPORT_LOCAL_PATHS wasn't set. It seems that if the user is a administrator it always automatically gets the default of IMPORT_LOCAL_PATHS. 

Now if IMPORT_LOCAL_PATHS=true and I deselect CanImportLocal on a administrative user, it gets selected again automatically when saving. On a normal user I can switch between true and false now. Is this intended behavior?

**Comment by lafriks** [comment]
Yes that is intended behaviour

**Comment by Cyber1000** [comment]
Sorry to answer so late, but it's still a little bit strange to me that I check checkboxes, save the site, it says "Account was updated" and afterwards I find that a checkbox has magically rechanged it's flag. A deactivated checkbox or an error-message on saving would be more conclusive for the user.

Also the "Der Account „%s“ wurde aktualisiert." with the %s within doesn't sound to be intended. Seems like the accountname wasn't but in the string properly.

Thanks!

**Comment by jxsl13** [comment]
Still persists: The message "Der Account „%s“ wurde aktualisiert." is a bug too, the message comes with %s, instead of the real user name.

Seems to be this line, where no username is being added to the string: https://github.com/go-gitea/gitea/blob/801843b0115e29ba2304fa6a5bea1ae169a58e02/routers/admin/users.go#L229

**Comment by Cyber1000** [comment]
Ok thanks, perhaps I'll have a look at it, when I'm having more time. At least it is a minor bug ...

**Comment by kolaente** [comment]
@Cyber1000 @jxsl13 I've approved the correct translation on crowdin, it should land in Gitea with the next sync of locales.
