### ISSUE TITLE
punctuation mark recognized as part of URL

### ISSUE THREAD

**Issue by davidak** [go-gitea/gitea#4496]
- Gitea version (or commit ref): ec43e56
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io: yes, tested there
  - [ ] Yes (provide example URL) https://try.gitea.io/davidak/kotkratom/issues/1
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

will this be fixed in https://github.com/go-gitea/gitea/pull/4146?

similar to https://github.com/go-gitea/gitea/issues/4143

## Screenshots

![screenshot from 2018-07-22 01-25-06](https://user-images.githubusercontent.com/91113/43040811-1998282e-8d4e-11e8-848c-af4b14d1e072.png)

**Comment by Wqrld** [comment]
I think this is intended as urls can contain question marks just fine (https://google.com?query=null). I am not sure about dots and exclamation marks though

**Comment by davidak** [comment]
>I think this is intended as urls can contain question marks just fine

@Wqrld also at the end?

This is my http://test.de/?

This is my http://test.de/!

This is a http://test.de/.

This is a http://test.de/)

**Comment by mrsdizzie** [comment]
This has been fixed as of f2de5dc

**Comment by techknowlogick** [comment]
Closed per above comment.
