### ISSUE TITLE
Add possibility for user to have several email addresses

### ISSUE THREAD

**Issue by choucavalier** [go-gitea/gitea#4497]
On GitHub, it's possible to have several email addresses.

Would it be possible to do the same in gitea?

**Comment by lafriks** [comment]
It is already possible. User can add additional email addresses in his settings

**Comment by choucavalier** [comment]
On 22.07.2018 07:43, Lauris BH wrote:
> It is already possible. User can add additional email addresses in
> his settings

Ah, sorry. I didn't see that! Thanks for the quick reply.

**Comment by KimonHoffmann** [comment]
Is there a possibility to synchronize email aliases from LDAP?
From quick glance at ldap.go I suppose not, is that assessment correct?

**Comment by lafriks** [comment]
Yes, user will have only primary email synced, other email addresses user can add in his settings

**Comment by KimonHoffmann** [comment]
Alright, thanks for clarifying this!
