### ISSUE TITLE
Web pages are often stuck

### ISSUE THREAD

**Issue by haohetao** [go-gitea/gitea#4506]
- Gitea version (or commit ref):5.0-rc2
- Git version:
- Operating system:windows 10 64bit
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
Web pages are often stuck，binary download from https://dl.gitea.io/gitea/
git server is local
## Screenshots
![qq 20180724150725](https://user-images.githubusercontent.com/4592571/43130012-3c001b58-8f68-11e8-9620-82193fe81fd2.png)

Longer delay,1.6s

**Comment by jonasfranz** [comment]
Only issues written in English are accepted, please reopen after you translated it to English.

**Comment by Wqrld** [comment]
What is stuck? Your screenshot just shows show loading (Which shouldn't happen on a local server)

**Comment by haohetao** [comment]
It did happen
![qq 20180814163822](https://user-images.githubusercontent.com/4592571/44081170-a946dea8-9fe0-11e8-80ba-c62cbae67f33.png)
My computer configuration is
cpu:intel i7 7700k
memory:16GB
hard disk:2TB+2TB raid0

**Comment by haohetao** [comment]
It's very slow when open when browser repository

**Comment by lunny** [comment]
How big are your repo?

**Comment by haohetao** [comment]
5,737 files
260MB size
the page bottom show:
Gitea Version: 1.5.0 Page: 2400ms Template: 1779ms

**Comment by Siesh1oo** [comment]
Can confirm; larger repos (Linux kernel, Android repo to name a few examples) take >8-10seconds even on high-end machines.

For each request a huge number of git-list-rev and git-cat-file calls are spawned.

**Comment by lunny** [comment]
@Siesh1oo this is a known issue for big repo. duplicated with #491
