### ISSUE TITLE
Display src and dest repos on 'New Pull Request' page?

### ISSUE THREAD

**Issue by barrylapthorn** [go-gitea/gitea#4511]
- Gitea version (or commit ref):
- Git version: 1.4.3
- Operating system: Windows
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

Is it possible to add the source and forked repositories to the new pull request screen?  It's confusing to new users (!) to only see 'base' and 'compare'.

Better would be:

    '<org>/<src-repo>' / branch

and

    '<user>/<forked-repo>' / <forked-repo-branch>

A tool tip would be sufficient, or at least some indication that the RHS ('compare') is the fork.

## Screenshots
![image](https://user-images.githubusercontent.com/1275154/43184011-07f3c7a2-8fdf-11e8-8c6c-ba739b28fc16.png)

![image](https://user-images.githubusercontent.com/1275154/43184298-09292c06-8fe0-11e8-81ec-0c941b9e550e.png)

**Comment by 6543** [comment]
fixed on master
