### ISSUE TITLE
Error in locale uk-UA

### ISSUE THREAD

**Issue by covrom** [go-gitea/gitea#4518]
- Gitea version (or commit ref): 7a30208e05d202062f8ca74c2637273d8bc23a77
- Git version: 2.17
- Operating system: Ubuntu
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:

## Description
Bad string 803 in locale file "locale_UK-UA.ini"
As result:
panic: fail to set message file(uk-UA): key-value delimiter not found: Цей запит тягнеться через відсутність інформації про вилучення.
...

## Screenshots

![2018-07-26 13-08-51](https://user-images.githubusercontent.com/10372209/43256631-01addac0-90d6-11e8-8334-1d1c61ebae0f.png)

**Comment by lafriks** [comment]
Fixed also on crowdin
