### ISSUE TITLE
Repositories sorting

### ISSUE THREAD

**Issue by lefta** [go-gitea/gitea#452]
Gitea is great for small projects, but some features are missing for (very?) big projects, [Atom](https://github.com/atom) being the perfect example of what I am meaning. With this kind of huge project, some issues arise. I'm dividing those issues in multiple bug reports for easy tracking.

One of those issues is that it is currently a pain to find a specific repository in repositories list. Providing a button to sort repositories, eventually with a default setting, would make big projects more easily browsable. Options that I have in mind would include, but not restricted to:
* Last updated (the current and only one available)
* Last created
* Name
* Propose your ideas ;)

All these options would be available in ascending and descending order.

**Comment by Bwko** [comment]
Gets fixed when #222 is merged

**Comment by lefta** [comment]
I checked bug reports, but not PRs, sorry

**Comment by tboerger** [comment]
This feature have been moved to 1.1.0

**Comment by lunny** [comment]
fixed by #222
