### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Taunty** [go-gitea/gitea#4523]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

ERROR 4000000004 !!!!

**Comment by techknowlogick** [comment]
Please provide more information when opening issues

**Comment by Taunty** [comment]
A white border around the badge notification  like on the pic

 [image1.jpeg]

Le 27 juil. 2018 à 13:54, techknowlogick <notifications@github.com<mailto:notifications@github.com>> a écrit :


Please provide more information when opening issues

**Comment by jonasfranz** [comment]
@Taunty you cannot add images via email

**Comment by Taunty** [comment]
Okay then look at this —-> ⭕️

Le 27 juil. 2018 à 17:14, Jonas Franz <notifications@github.com<mailto:notifications@github.com>> a écrit :


@Taunty<https://github.com/Taunty> you cannot add images via email
