### ISSUE TITLE
Wrong Link when referencing a commit hash on README.md

### ISSUE THREAD

**Issue by krombel** [go-gitea/gitea#4536]
- Gitea version (or commit ref): 1.5.0+rc2-2-g5a7830e0e

- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No (Bad Gateway)
  - [ ] Not relevant

## Description
When adding a commit hash to README.md the hash gets linkyfied to
`http://host/testOrg/testRepo1/src/branch/master/commit/<commitID>` instead of
`http://host/testOrg/testRepo1/commit/<commitID>`

**Comment by SagePtr** [comment]
Also, in /api/v1/markdown preview (while editing file through web), not only for commit references wrong link href is generated, but for issue links too.
Example markdown:
```
# test

Commit 056dd42

Issue #1
```
Result is:
```
<h1>test</h1>

<p>Commit <a href="https://{domain}/{user}/{repo}/src/branch/master/commit/056dd42" rel="nofollow">056dd42</a></p>

<p>Issue <a href="https://{domain}/{user}/{repo}/src/branch/master/issues/1" rel="nofollow">#1</a></p>
```
Should be:
```
<h1>test</h1>

<p>Commit <a href="https://{domain}/{user}/{repo}/commit/056dd42" rel="nofollow">056dd42</a></p>

<p>Issue <a href="https://{domain}/{user}/{repo}/issues/1" rel="nofollow">#1</a></p>
```

**Comment by lunny** [comment]
Since #4545 moved to 1.9.0, move this to 1.9.0 too.
