### ISSUE TITLE
Could not load cert file with Let's Encrypt apache 

### ISSUE THREAD

**Issue by fazlerabbi37** [go-gitea/gitea#4537]
- Gitea version (or commit ref): 5a7830e
- Git version: 2.7.4
- Operating system: Ubuntu Server 16.04 LTS
- Database (use `[x]`):
  - [ x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
I am trying to install gitea under a domain with SSL cretificate from Let's Encrypt but I am getting the following error:

``.../cmd/web_graceful.go:37 runHTTPS()] [E] Failed to load https cert file 0.0.0.0:3000: open /etc/letsencrypt/live/domain.tld/fullchain.pem: permission denied``

While I can confirm that the file is readable by all user, group and others and is working as beacuse my default apache config contains the same cretificate file and working fine. 

Gitea ``app.ini``:

```
PROTOCOL         = https
SSH_DOMAIN       = domain.tld
DOMAIN           = domain.tld
HTTP_PORT        = 3000
ROOT_URL         = https://domain.tld/
DISABLE_SSH      = false
SSH_PORT         = 22
CERT_FILE        = /etc/letsencrypt/live/domain.tld/fullchain.pem
KEY_FILE         = /etc/letsencrypt/live/domain.tld/privkey.pem
```
Please help me out by showing what am I doing wrong.

...

**Comment by lafriks** [comment]
If you are already using Apache in front int would be recommended to use https termination in Apache not in gitea

**Comment by fazlerabbi37** [comment]
I am sorry. I could not understand you. Are you suggesting that I should put the CERT and KEY file in apache config?

**Comment by lafriks** [comment]
Yes and set gitea in http mode and listen only in localhost. Apache should be used as reverse proxy in front t

**Comment by lafriks** [comment]
Also please use gitea forum for such questions

**Comment by fazlerabbi37** [comment]
Still no luck! Now I am getting 404 on ``https://domain.tld/gitea``. 


Gitea ``app.ini``
```
[server] 
PROTOCOL         = http 
SSH_DOMAIN       = localhost 
DOMAIN           = localhost 
HTTP_PORT        = 3000
ROOT_URL         = http://localhost:3000
DISABLE_SSH      = false
SSH_PORT         = 22
```
Apache config file ``gitea.conf``
```
<VirtualHost *:443>
    
    SSLCertificateFile /etc/letsencrypt/live/domain.tld/fullchain.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/domain.tld/privkey.pem
    Include /etc/letsencrypt/options-ssl-apache.conf
    
    ProxyPreserveHost On
    ProxyRequests off

    <Proxy *>
         Order allow,deny
         Allow from all
    </Proxy>

    ProxyPass /gitea http://localhost:3000
    ProxyPassReverse /gitea http://localhost:3000

</VirtualHost>

```
---

I could not find any proper/complete documentation for this issue, like how to config apache for reverse-proxy as sub-directory with SSL and there were no topic/thread discussing the issue on forum so I opened an issue here.

**Comment by lafriks** [comment]
You should use in app.ini:
```
[server] 
PROTOCOL         = http 
SSH_DOMAIN       = your-domain.ltd
DOMAIN           = your-domain.ltd 
HTTP_ADDR      = localhost
HTTP_PORT        = 3000
ROOT_URL         = https://your-domain.ltd/gitea/
DISABLE_SSH      = false
SSH_PORT         = 22
```

**Comment by lafriks** [comment]
See docs here: https://docs.gitea.io/en-us/reverse-proxies/
