### ISSUE TITLE
Login not possible

### ISSUE THREAD

**Issue by d00ndy** [go-gitea/gitea#4541]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
I am not able to login after opening gittea start page. Only 404 error is shown. 
Error message in gotten.log: 2018/07/29 13:41:15 [...s/context/context.go:147 NotFoundOrServerError()] [E] GetRepositoryByOwnerAndName: repository does not exist [id: 0, uid: 0, owner_name: , name: user]

**Comment by techknowlogick** [comment]
Thanks for the report @d00ndy 
Would you be able to provide more information such as which version of Gitea you are using, which OS you are using, and which version of Git you are using?

**Comment by d00ndy** [comment]
Hello, 
I am using git version 2.7.4 and Gitea version 280ebcb built with: bindata, sqlite 


Example page: https://knupfer.biz/git/

Further Logging: 
2018/07/30 12:00:55 [I] Log Mode: File(Debug)
2018/07/30 12:00:55 [I] XORM Log Mode: File(Debug)
2018/07/30 12:00:55 [I] Cache Service Enabled
2018/07/30 12:00:55 [I] Session Service Enabled
2018/07/30 12:00:55 [I] Git Version: 2.7.4
2018/07/30 12:00:55 [I] SQLite3 Supported
2018/07/30 12:00:55 [I] Run Mode: Production
2018/07/30 12:00:56 [I] Listen: http://0.0.0.0:3000/git
2018/07/30 12:00:56 [I] LFS server enabled
2018/07/30 12:01:23 [D] Session ID: ABC
2018/07/30 12:01:23 [D] CSRF Token: XXX
2018/07/30 12:01:23 [D] Template: home
2018/07/30 12:01:24 [D] Session ID: ABC
2018/07/30 12:01:24 [D] CSRF Token: XXX
2018/07/30 12:01:24 [...s/context/context.go:147 NotFoundOrServerError()] [E] GetRepositoryByOwnerAndName: repository does not exist [id: 0, uid: 0, owner_name: , name: user]
2018/07/30 12:01:24 [D] Template: status/404

**Comment by lafriks** [comment]
Looks like you have not set correctly reverse proxy. See in docs how to setup it with subdirectory

**Comment by lafriks** [comment]
Please use forum for such questions
