### ISSUE TITLE
Proposal: quick compare buttons at branch list

### ISSUE THREAD

**Issue by SagePtr** [go-gitea/gitea#4547]
- Gitea version (or commit ref): any
- Git version: any
- Operating system: any
- Database: any
- Can you reproduce the bug at https://try.gitea.io: no (server down)

## Description

On /{user}/{repo}/branches  page, there is brief list of branches.

Github shows compare button or pull request link for each non-default branch, which compares branch to default branch (usually master) and proposes to create Pull request (or links to pull request itself).

This functionality is missing in gitea. Would be good to implement this in gitea.

## Screenshots

![](https://habrastorage.org/webt/tq/bz/u6/tqbzu6fircwwfqo77ifpp1djllm.png)

**Comment by SagePtr** [comment]
To person who will edit template file (repos/branch/list.tmpl):
This part looks misaligned:
```
<td>
{{if .IsDeleted}}
	<s><a href="{{$.RepoLink}}/src/branch/{{.Name}}">{{.Name}}</a></s>
	<p class="time">{{$.i18n.Tr "repo.branch.deleted_by" .DeletedBranch.DeletedBy.Name}} {{TimeSinceUnix .DeletedBranch.DeletedUnix $.i18n.Lang}}</p>
{{else}}
	<a href="{{$.RepoLink}}/src/branch/{{.Name}}">{{.Name}}</a>
	<p class="time">{{$.i18n.Tr "org.repo_updated"}} {{TimeSince .Commit.Committer.When $.i18n.Lang}}</p>
</td>
{{end}}
```
`</td>` and `{{end}}` must swap places (not critical because closing `</td>` could be omited)

**Comment by ghost** [comment]
Related: #3683 #4567
