### ISSUE TITLE
Raw URL Web Request Redirection Loop On Spaces In Filename

### ISSUE THREAD

**Issue by atom0s** [go-gitea/gitea#4549]
- Gitea version (or commit ref): a74426d631e3311cc3c460ae9917f76f0221f4de
- Git version: 2.17.1.windows.2
- Operating system: Windows Server 2012 R2 Standard
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant - Doesn't load, still 502 bad gateway error.
- Log gist:
 N/A

## Description

Gitea has issues serving URLs that Gogs otherwise used to server without issue when requesting /raw/ related data from an external source. The issue seems to only trigger for me so far when there is a space in a file name.

For example, on Gogs, both of these are valid but Gogs will offer you the first link when clicking the 'Raw' button to view the file:
```
https://example.com/SomeOwner/SomeRepo/raw/master/data/Some File Name.xml
https://example.com/SomeOwner/SomeRepo/raw/branch/master/data/Some File Name.xml
```

Gitea on the other hand gives you the 2nd one instead with the /branch/ part added to the url. On all other files, Gitea will work with either link, except files with spaces in the name so far. (Other special characters may cause issues too, haven't tested anything further than that at the moment.)

Instead, Gitea will get stuck in a redirect loop and eventually error out with:
```
https://example.com/SomeOwner/SomeRepo/raw/master/data/Some%20File%20Name.xml/branch/master/data/Some%20File%20Name.xml/branch/master/data/Some%20File%20Name.xml/branch/master/data/Some%20File%20Name.xml/branch/master/data/Some%20File%20Name.xml/branch/master/data/Some%20File%20Name.xml/branch/master/data/Some%20File%20Name.xml/branch/master/data/Some%20File%20Name.xml
```

And 404.

**Comment by lunny** [comment]
I think this has been resolved. Please feel free to reopen it.
