### ISSUE TITLE
Termux

### ISSUE THREAD

**Issue by skyrimp** [go-gitea/gitea#4552]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

...

**Comment by techknowlogick** [comment]
Please add details and re-open if needed.
