### ISSUE TITLE
Enabling arc-green theme

### ISSUE THREAD

**Issue by Fastidious** [go-gitea/gitea#4557]
- Gitea version (or commit ref): `280ebcb`
- Git version: `N/A`
- Operating system: `Ubuntu`
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:

## Description

Trying to enable `arc-green`. Added:

```
[ui]
DEFAULT_THEME = arc-green
```

Yet, it isn't showing. What could I be missing?

**Comment by techknowlogick** [comment]
@Fastidious Themes were added in 1.6.0-dev, you are using 1.5.0-rc2. If you want to use built in theme please update, otherwise you can follow instructions here: https://github.com/go-gitea/gitea-darkmode to get it working on your version.

**Comment by Fastidious** [comment]
@techknowlogick one last thing, where can I find 1.6.0-dev?

**Comment by techknowlogick** [comment]
If you are using docker then pull the `:latest` tag, or if you are using just the binary you can find the most recent binary here: https://dl.gitea.io/gitea/master/

Please note: As you can tell by the name it is a dev release and so there may be broken things that get released. If you want to ensure you have a stable version please use an RC, or a fully released version.
