### ISSUE TITLE
custom/template not work after update

### ISSUE THREAD

**Issue by EnricoFerro** [go-gitea/gitea#4561]
- Gitea version (or commit ref):  d572336 ( probably from a74426d )
- Git version: 
- Operating system: Linux Ubuntu 
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X] No
  - [ ] Not relevant
- Log gist:

## Description

In Docker after update from be4ec0c  to d572336  the custom/templates is not more read ( in particular after the modification of  template/home.tmpl.  
The public image ( custom/public/img ) is not affected.

Probably the cause is the a74426d commit.

## Screenshots
Before:
![image](https://user-images.githubusercontent.com/25525316/43419419-1b88f808-9441-11e8-8f2e-7d1b2b5b6637.png)

After:
![image](https://user-images.githubusercontent.com/25525316/43419479-466accfe-9441-11e8-8433-a9a4faa8f42a.png)

**Comment by LER0ever** [comment]
Hi, same issue here. Probably the [this line](https://github.com/go-gitea/gitea/commit/a74426d631e3311cc3c460ae9917f76f0221f4de?diff=split#diff-a4fec05dc3a0e1923fa6e6af59ab2b69R115) in [this commit](https://github.com/go-gitea/gitea/commit/a74426d631e3311cc3c460ae9917f76f0221f4de) caused the `tplFileSys` to be initialized more than it should be?

**Comment by sankethpb** [comment]
could this be back-ported to 1.5.2 ?

**Comment by lafriks** [comment]
I don't think 1.5 branch has that problem

**Comment by sankethpb** [comment]
We are facing the same issue in 1.5.1, in docker image.

**Comment by strk** [comment]
I don't have problems with custom templates with 1.5.1
(but I'm not using Docker)
