### ISSUE TITLE
SSH deploy key access right bug

### ISSUE THREAD

**Issue by pzillmann** [go-gitea/gitea#4564]
- Gitea version (or commit ref): 1.4.0
- Git version: 2.11.0
- Operating system: Debian Stretch Linux 4.9.0-7-amd64 #1 SMP Debian 4.9.110-1 (2018-07-05) x86_64 GNU/Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

Using gitea's internal ssh server. Setup-ed one deploy key for one repository. This deploy key has suddenly access to all of the organisation's repositories.

**Comment by lunny** [comment]
@pzillmann could you send more detail to security [at] gitea.io
