### ISSUE TITLE
Make fork independent from original repository

### ISSUE THREAD

**Issue by tobias--** [go-gitea/gitea#4566]
- Gitea version (or commit ref): 1.4.3
- Git version: 
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

A fork currently can not be converted to a "normal" repository other than by pushing into a new repository. When a repository is a fork, pull requests will be pointing to the original repository by default, which might not be wanted in case the fork diverges.

**Comment by adelowo** [comment]
What other platform has this feature ? I don’t think this would be nice to have though

**Comment by strk** [comment]
I think this would be very nice to have. Don't care who else has it.

**Comment by techknowlogick** [comment]
With mirrors you can "Convert to Regular Repository", perhaps the same could be done for forks. One concern with this is that we need to ensure that users don't use this as a way to bypass the repository limits (which forks don't count against).

**Comment by JulienTant** [comment]
I'm thinking out loud about an idea: 

1) When you create a PR from a fork, you stay on your current repository page (in term of URL) BUT the default branch is `{originalUser}:{originalRepoDefaultBranch}`. You will find in the "base branch" select branches from your repository and from the original one. This can be done by just listing them like this :

- originalUser:master
- originalUser:develop
- originalUser:feature1 
- master
- develop
- myFeature 

Or by using the semantic UI grouping options :

- Original repository
  - master
  - develop
  - feature1
- My fork
  - master
  - develop
  - myFeature

2) In the setting page of your fork, you will find a new option "Default PR destination" which is set to "original" by default (to keep the current behavior and not disturb existing users), that you can set to "this repository"

**Comment by benharri** [comment]
Both gitlab and github allow converting forks into normal repositories. I'd like to be able to do this as well.

**Comment by DanTheMan827** [comment]
I would love this ability, I have a project that started as a fork but the improvements were never accepted into the main repository.

Now the fork has evolved into its own project.

I could delete the repository and re-push the commits to a new one, but that would also delete all of the issues, releases, and network information.

**Comment by CirnoT** [comment]
>Both gitlab and github allow converting forks into normal repositories. I'd like to be able to do this as well.

Where exactly? GitHub points to manual guide https://help.github.com/en/github/creating-cloning-and-archiving-repositories/duplicating-a-repository
