### ISSUE TITLE
Enhance /compare/ for tags and abbreviated commit shas

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#4567]
Gitea version (or commit ref): `55d9ddf`

## Description

This works:
<samp>/compare/d40cdb7ded29d1f406a2575ee03030b32f6d7114...2964016d5ae44fb587b96802f4e2bceadff6b2ee</samp>

This doesn't but probably should:
<samp>/compare/d40cdb7...2964016</samp>

This doesn't but probably should:
<samp>/compare/v1.1.1...v1.1.2</samp>

Basically anything that is commitish should compare with assumption 7 chars in the commit sha is enough to ensure uniqueness.

**Comment by saitho** [comment]
Supporting short hashes is be related to https://github.com/src-d/go-git/issues/602, since Gitea uses go-git to check if the reference exists.

**Comment by richmahn** [comment]
@saitho Do you know why though you can see a commit with a short commit hash? E.g. http://localhost:3000/root/test/commit/d42f998 works for me

**Comment by saitho** [comment]
Hmm... haven't tried that yet. Maybe that's one doesn't rely on go-git? I'll look into that. :)

**Comment by richmahn** [comment]
I wonder if it has to do something in the likes of a "git log | grep <short hash>" or something to then find the long hash from the output?

**Comment by zeripath** [comment]
I just pushed a commit to the #6991 PR which adds the ability to use the commit SHA.
