### ISSUE TITLE
Non-SVG image links don't link to intended website

### ISSUE THREAD

**Issue by Eisfunke** [go-gitea/gitea#4569]
- Gitea version (or commit ref): Tested on 1.2.3 and 40bbc73
- Operating system: Tested on Ubuntu 16.04.5 LTS and Arch Linux
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
    Seems down, so I can't check. 

## Description

When embedding an image with a link like this
`[![test](https://img.shields.io/badge/test-yes-green.svg)](https://example.org)`
in a markdown file in Gitea, it correctly shows as the image and links to the intended website.

Though when the linked image is not an svg, like this
`[![test](https://img.shields.io/badge/test-no-red.png)](https://example.org)`
it doesn't link to the intended website, but only to the image itself.

You can see it here: https://git.eisfunke.com/Eisfunke/test/src/branch/master/README.md

On Github it works: https://github.com/Eisfunke/test/blob/master/README.md

**Comment by mappu** [comment]
I can confirm this issue still affects 1.5.1.

Markdown content like `[![](doc/image.thumb.png)](doc/image.png)` creates a link to `image.thumb.png`, not `image.png`.
