### ISSUE TITLE
Gitea not sending email to 'watcher' on a commit/push

### ISSUE THREAD

**Issue by mgoddard27** [go-gitea/gitea#4574]
- Gitea version (or commit ref): Gitea Version: 1.5.0+rc1-73-gd0fef4395 
- Git version: 1.8
- Operating system: CentOS7
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x ] No ( that site is currently down )
  - [ ] Not relevant
- Log gist:

## Description

A push up to the repo does not send an email to the watcher.

**Comment by adjurk** [comment]
Can confirm on Gitea Version 1.4.2
