### ISSUE TITLE
Pull Requests can be listed without having the corresponding permission

### ISSUE THREAD

**Issue by L-P** [go-gitea/gitea#4587]
- Gitea version (or commit ref): 1.4.3 (docker)
- Git version: 2.15.2
- Operating system: Alpine 3.7 (docker)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X] No (try is down)
  - [ ] Not relevant
- Log gist:

## Description
I created an "extern" team on an organization with read-only access to code
only, and assigned a single repository to it. (see the attached screenshot)

When going to `/pulls` with an account assigned to this extern team (and this
team only) I can list all pull requests, including the title, author, date
number of comments and open/closed status.  
When trying to access the details of a single PR I get the expected 404.

Being able to list the pull requests when I specifically disabled the right to
access them is an information leak and a security issue.

## Screenshots
 ![Permissions screen](https://user-images.githubusercontent.com/947312/43513592-746d4756-957e-11e8-80b7-45dfbc0d1836.png)

**Comment by lunny** [comment]
This should be fixed if exist by #5314
