### ISSUE TITLE
Use github gitignore list

### ISSUE THREAD

**Issue by tboerger** [go-gitea/gitea#46]
What do you guys think about just using the gitignore list provided by github? You can see the full list here: https://github.com/github/gitignore

**Comment by nounoursheureux** [comment]
I also thought about making this proposition, so :+1:

**Comment by tszym** [comment]
Not sure to see how you plan to do, but a running instance of gitea should not rely on someting managed by GitHub, or be restricted in features in case of unavailability.

For the first point, the main reason is that it tooks away some freedom from the users where it should be able to customize the config, gitignore files included.

**Comment by tboerger** [comment]
I would integrate it with ```git subtree```, that way we can track upstream changes but also being free in adding or removing stuff.

**Comment by tboerger** [comment]
Another option should be to just fetch a subset of the gitignores and replace the currently available files.

**Comment by tszym** [comment]
Modify forked repos and keeping them synced with upstream is a pain.

Replace the current files sounds better.
The ideal way would be to have all the gitignore files in one conf folder (like now) and allow the user to just add files to use more gitignore.

This way, if I want to add a gitignore for, say Haskell, I just have to add a file named `haskell._` (where `_` is *whatever*) in the conf directory and *Haskell* woud appear in the available choices, with the item's name based on the filename.

But this goes with removing the pain to use bindata for gitignore files.

**Comment by tboerger** [comment]
> Modify forked repos and keeping them synced with upstream is a pain.

Not really, with subtree it's absolutly not a pain.

> But this goes with removing the pain to use bindata for gitignore files.

Removing bindata is IMHO not an option. Make it a little bit more flexible that you can add additionally files to a specific folder sounds much better because generally i prefer the single file deployments of go projects.

**Comment by tszym** [comment]
Not being a go person at all, I don't know what's bebind *single file deployment*, but this sounds like something without config file.

We already have a config file for the instance, so, as long as the config size is reasonable, I don't see the point to have gitignore as bindata.

> I would much more prefer to have Gogs failing to start with an explicit error message when the file is missing in config.

With a lookup on the gitignore folder on start, this is not a problem anymore.

**Comment by tboerger** [comment]
Even the custom config file is just optional if you need to change something.

**Comment by tboerger** [comment]
And anyway, removing bindata is really offtopic for this issue.

**Comment by matt-h** [comment]
The github gitignore list sounds good to me since it already a very complete list.
It is also MIT license so it is compatible.

**Comment by dentmaged** [comment]
Use github's gitignore list but allow users to change it (just have it in the ```config``` directory).

**Comment by lunny** [comment]
I think this issue could be closed since #63 has been merged to develop.
