### ISSUE TITLE
PANIC 'runtime error: index out of range' on pull request

### ISSUE THREAD

**Issue by nuno-silva** [go-gitea/gitea#4603]
- Gitea version (or commit ref): 1.4.3
- Git version: 2.16.4
- Operating system: Gentoo Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist: https://gist.github.com/nuno-silva/5bef3d8dd47523a1ed7d461349f34a9f

## Description

I was editing a comment on a pull request. When I tried to submit the comment, I got an internal server error. Since then, the page for this pull request always fails with `runtime error: index out of range`. Other pages in gitea work.

I remember starting time tracking while editing the comment.

I couldn't reproduce the error in try.gitea.io so far.

Any pointers on where to start debugging the error would be appreciated.
...

**Comment by lunny** [comment]
@nuno-silva could you upgrade to v1.4.3 and confirm the bug is still there?

**Comment by nuno-silva** [comment]
@lunny the error is still happening on v1.4.3. I've updated the gist and issue description.

**Comment by nuno-silva** [comment]
@lunny I was able to reproduce the bug again in v1.4.3.

Simply opening a new issue and writing either of these in a comment triggers an internal error:

```
[[https://www.freedesktop.org/software/systemd/man/networkd.conf.html#DUIDType=]]
```

```
[[=]]
```

In try.gitea.io (9c354a5), the rendered comment is empty, but does NOT trigger an internal error: 
https://try.gitea.io/nuno-silva/test/issues/3

**Comment by nuno-silva** [comment]
As a workaround, I altered the affected comment's content in the database:
```
update comment set content="workaround" where issue_id=504 and id=1392;
```

**Comment by lunny** [comment]
It seems `master` have fixed that issue.

**Comment by nuno-silva** [comment]
Yes. `[[=]]` seems to be invalid markdown anyway, so as long as it doesn't crash I think it's acceptable behaviour.
Reopen if you disagree.
