### ISSUE TITLE
setup improvement with app.ini template

### ISSUE THREAD

**Issue by thimmy687** [go-gitea/gitea#4605]
Hey at all,

is it possible to create a well described maximum app.ini file, comparable to the approach of Gitblit.

would be very helpful.

Best Regards

**Comment by rawsta** [comment]
Do you mean like: https://github.com/go-gitea/gitea/blob/master/custom/conf/app.ini.sample

**Comment by thimmy687** [comment]
Yes I already saw this. 
But maybe it is possible to have it directly on the machine.

Or as minimum an link to this source

**Comment by rawsta** [comment]
The app.ini.sample ist linked as "Complete List" in the docs at: https://docs.gitea.io/en-us/customizing-gitea/
But having it as a starting point in the custom folder would be a nice-to-have.
