### ISSUE TITLE
Gitea Service problem

### ISSUE THREAD

**Issue by Fretice** [go-gitea/gitea#4608]
- Gitea version (or commit ref):1.5
- Git version:2.18.0
- Operating system: centos 6.9
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
I used this [gitea](https://github.com/go-gitea/gitea/blob/master/contrib/init/centos/gitea) shell script to create a service . i had changed the script by my gitea path , but unfortunately it throw a error :
 runuser: cannot set groups: Operation not permitted
...

**Comment by lafriks** [comment]
Check https://serverfault.com/questions/176137/what-does-runuser-cannot-set-groups-mean

**Comment by lafriks** [comment]
Questions if only it is not confirmed gitea bug should be posted to gitea forum
