### ISSUE TITLE
https://godoc.org/github.com/go-gitea/go-sdk is broken

### ISSUE THREAD

**Issue by tjyang** [go-gitea/gitea#461]
## Description
In https://github.com/go-gitea/gitea/README.md, https://godoc.org/github.com/go-gitea/go-sdk is broken.

...

**Comment by tboerger** [comment]
Indeed, we need to append /gitea

**Comment by tjyang** [comment]
Thanks for the info.  https://godoc.org/code.gitea.io/sdk/gitea is the correct URL.
