### ISSUE TITLE
UX: Tags and Releases operation

### ISSUE THREAD

**Issue by msg7086** [go-gitea/gitea#4612]
- Gitea version (or commit ref): 1.5 nightly
- Database:
  - MySQL
- Can you reproduce the bug at https://try.gitea.io:
  - Yes

## Description

We have tags and releases, just like what we found on GitHub. However they behave differently.

1. On GitHub, we are given a dropdown list to pick an existing tag, or an Edit Tag button to draft a release on existing tags. In Gitea, we have to type an existing tag manually. No link on an existing tag leads to draft a release for it.

2. On GitHub, a tag is a tag, a release is a release. Deleting a release has no harm to a tag. In Gitea, there's no way to revert the action of drafting a release for an existing tag. Whenever a release is deleted, the corresponding tag, even if it was created before, gets deleted as well. No alt option was given to the user.

Both behaviors bring discomfort to those who creates or deletes releases on the website for existing tags.

What's your opinion? Are they expected behaviors / by design? Shall those be improved in later versions?

Cheers

**Comment by lafriks** [comment]
I think this can be improved

**Comment by DjSni** [comment]
There should also be a way to delete tags that have been pushed through git.
Also, there is no way to delete release assets. If the release is deleted, the assets will remain in the folder.

#677

**Comment by lunny** [comment]
I think this is outdated. So closing it.
