### ISSUE TITLE
How can I configure Gitea to use SendGrid API

### ISSUE THREAD

**Issue by chanhlt** [go-gitea/gitea#4621]
I have a problem when deploying Gitea to Google Compute Engine.
Gitea cannot send notification email because Google block port 25, 587, 465.
However, I have a SendGrid API key and I am planning to use it (as Google recommend).
But I don't know how to configure.

Can anyone teach me about this?

- Gitea version (or commit ref):
- Git version: 1.5.0-rc2
- Operating system: Debian 9
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

...

**Comment by techknowlogick** [comment]
You can also use sendgrid with port 2525: https://sendgrid.com/docs/API_Reference/SMTP_API/getting_started_smtp.html

**Comment by chanhlt** [comment]
@techknowlogick : Thanks a lot. I works perfect!
