### ISSUE TITLE
gitea loss of avatars after update

### ISSUE THREAD

**Issue by abhinand-tw** [go-gitea/gitea#4629]
- Gitea version (or commit ref): update to 1.4.3 from 1.3.2
- Git version: 2.15.2
- Operating system: ubuntu 14.04
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

Hello!
After update gitea container to 1.4.3 from 1.3.2 we have loss all avatars.
When adding avatars manually again, i found out that they are saved in /app/gitea/data/avatars.
In this folder (app/gitea/data)  i also saw "indexers" and "sessions" folders.
We have "sessions" folder in /data/data dir (the dir use for store data as described in the documentation with docker use
  volumes:
      - ./gitea:/data )
I thout that to save all the necessary data for the operation of the gitea (sessions, users, avatars and other), we need to use the "data" folder on the host (or named volume). But this is not onough, wee still need save data from many folders (/app/gitea/data/avatars or /app/gitea/data). 

Please specify the full list of folders that we need to save, for a successful update of the gitea if using docker and store all data (sessions, vatars and others working data)

Best regards,
Danilin Maxim

**Comment by lafriks** [comment]
all `/app/gitea/data` should be backed up

**Comment by abhinand-tw** [comment]
There is nothing in the documentation about this, right?

**Comment by Siesh1oo** [comment]
@lafriks : last time I tried (couple of weeks ago), gitea dump command did not back this up, even if documentation says otherwise. Full-disk backup is working, tho
