### ISSUE TITLE
Please update to the laest version? is the msg i get on my SMLoader v1.9.2.. and then it takes me to a site that says this 404 eror no buttion that says update?

### ISSUE THREAD

**Issue by mehofmeyr** [go-gitea/gitea#4633]

**Comment by mehofmeyr** [comment]
![update deezer](https://user-images.githubusercontent.com/42046436/43775701-868b3242-9a45-11e8-99c4-c94d4b936a44.png)

**Comment by SagePtr** [comment]
Gitea is git self-hosting software, it's not related to SMLoadr (which just uses Gitea to host their repo).
You should ask SMLoadr developers for help, not Gitea developers.

**Comment by mehofmeyr** [comment]
thanx
