### ISSUE TITLE
Docs: how to use Gitea without assets compiled?

### ISSUE THREAD

**Issue by TomaszGasior** [go-gitea/gitea#4646]
Please add to docs information about how to use Gitea without assets compiled. I mean: which files are needed to be copied&pasted with binary to get Gitea working without the whole repository.

**Comment by lafriks** [comment]
Not sure what would be use case for this as it would just add confusion especially on updates

**Comment by TomaszGasior** [comment]
* On my shared hosting there are  problems with compilation with assets so I have to use gitea without assets compiled. It seems to me problem is related to restricted hosting configuration, not to Gitea itself.
* [Documentation](https://docs.gitea.io/en-us/install-from-source/) says: "Bundling assets into the binary using the bindata build tag can make development and testing easier, but is not ideal for a production deployment". It means in production gitea compiled without assets is better than with. Am I wrong?

**Comment by lunny** [comment]
Just
```
go build
```
If you want `sqlite` support, also
```
go build -tags=sqlite
```

**Comment by TomaszGasior** [comment]
And which assets files should be copied to get working binary?

**Comment by lafriks** [comment]
That sentence in documentation is not meant like that. Idea is that for development porpoise it would be time consuming for every change in resources to rebuild binary but for production use it is recommend to use embedded resources (bindata)

**Comment by lafriks** [comment]
Also you can prebuild binary on your machine and than just copy it to your server. No need to compile it on that server

**Comment by TomaszGasior** [comment]
Nope. I use Linux and I don't have working local FreeBSD installation. I don't want to waste time to install the whole operating system to build one binary.
Still, I think instruction which assets files should be copied could be useful for some people.

**Comment by lafriks** [comment]
You can build FreeBSD binary also on Linux, it is especially easy if you don't need sqlite support

**Comment by lafriks** [comment]
In future please use forum (https://discourse.gitea.io/) for such questions

**Comment by qzmfranklin** [comment]
> Just
> 
> ```
> go build
> ```
> 
> If you want `sqlite` support, also
> 
> ```
> go build -tags=sqlite
> ```

Thanks for the info. Without that, what public assets should I add to the working directory of gitea? Thanks.

**Comment by qzmfranklin** [comment]
> Not sure what would be use case for this as it would just add confusion especially on updates

There ARE use cases that would require building the program without using assets. The fact that you cannot imagine any of those use cases does not mean that there is no such use cases.

Discussions won't be as helpful as people are generally expecting if you just focus on questioning askers' motivations. Please provide concrete instructions to help people achieve what they are asking for.

**Comment by lunny** [comment]
As @lafriks said, that method is only for development locally. So we haven't instructions for that and will not give one because it maybe out of date some day. We  recommend you to use `make` to compile `Gitea`.
