### ISSUE TITLE
Docs: mention about gmake on FreeBSD

### ISSUE THREAD

**Issue by TomaszGasior** [go-gitea/gitea#4647]
I am not sure this problem occurs in all situations but on my shared hosting with SSH access and FreeBSD OS I have to use `gmake` command instead `make` to manually compile Gitea. It seems to be it would be good to mention this in the documentation on the "Installation from source" page.

**Comment by lafriks** [comment]
Feel free to submit PR with such changes as at least I don't have much FreeBSD experience :)

**Comment by sondr3** [comment]
https://github.com/go-gitea/gitea/pull/4446?

**Comment by TomaszGasior** [comment]
I will check it.

**Comment by TomaszGasior** [comment]
I checked it. It works if I try to build Gitea from the master but this PR is not backported to current stable (which I tried to build the first time).

**Comment by lunny** [comment]
@TomaszGasior I don't think it's necessary to back port that PR to v1.5. You can copy that make file and build yourself.

**Comment by lafriks** [comment]
@TomaszGasior we are already short on people who help on documentation so we can't keep it up version specific as in 1.6.0 it will be already solved

**Comment by TomaszGasior** [comment]
Okay. Thanks for info!
