### ISSUE TITLE
Home button should be hidden when LANDING_PAGE is set to "explore" or "organizations"

### ISSUE THREAD

**Issue by 0rzech** [go-gitea/gitea#4648]
- Gitea version (or commit ref): 1.4.3
- Git version: Not relevant
- Operating system: Not relevant
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
  - [x] Not relevant
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist: Not relevant

## Description

When `app.ini` contains `LANDING_PAGE = explore`, all of the three buttons (the cup, `Home` and `Explore`) point to the same place. This is redundant and kind of confusing. See [here](https://orzechowski.tech/git) for an example.

So what would I expect? When `LANDING_PAGE` is set to `home`, both home and explore buttons should be visible, as they point to different locations. When `LANDING_PAGE` is set to `explore` or `organizations`, the home button should be hidden and explore button should just be labelled `home`, as it is it's real role now.

**Comment by techknowlogick** [comment]
Perhaps instead of renaming explore to home, just remove the home link when the above situation occurs.

**Comment by 0rzech** [comment]
@techknowlogick I think it should be renamed to home, because this is exactly what explore button means when `LANDING_PAGE` is `explore` or `organizations`.

**Comment by 0rzech** [comment]
@techknowlogick The home button is removed in above situation. Explore is just additionally renamed to home, because this is exactly what explore button means when `LANDING_PAGE` is `explore` or `organizations`. Also, this will be consistent for people visiting different instances of Gitea. Home-labelled button will always be there for them, just defaulting to different pages. Of course, if you still want me not to rename explore in addition to hiding home, just let me know and I will update PR.
