### ISSUE TITLE
"The cup" and "home" buttons are redundant

### ISSUE THREAD

**Issue by 0rzech** [go-gitea/gitea#4649]
- Gitea version (or commit ref): 1.4.3
- Git version: Not relevant
- Operating system: Not relevant
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
  - [x] Not relevant
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL): https://try.gitea.io
  - [ ] No
  - [ ] Not relevant
- Log gist: Not relevant

## Description

"The cup" and `Home` buttons have exactly the same role. Not a big deal, but it's a bit weird and somewhat confusing. One of these should be removed for better consistency.

**Comment by 0rzech** [comment]
@xxxtonixxx @kplaczek Could you elaborate on what's good in having two buttons with exactly same role next to each other?

**Comment by ghost** [comment]
@0rzech what do you see when you browse Gitea from a terminal browser?

**Comment by 0rzech** [comment]
@jhabdas I don't use terminal browser, but what does it have to do with my question?

**Comment by 0rzech** [comment]
@jhabdas I guess you already know how to answer yourself, so please feel free to post it. But what does it have to do with my question anyways?

**Comment by 0rzech** [comment]
@jhabdas Does having two buttons with identical role placed next to each other help you browse Gitea from terminal?

**Comment by 0rzech** [comment]
@jhabdas Is having two buttons with identical role placed next to each other necessary for you to browse Gitea from terminal?

**Comment by 0rzech** [comment]
@jhabdas Does having two buttons with identical role placed next to each other help you browse Gitea from terminal?

**Comment by ghost** [comment]
![screenshot_20180810-011510](https://user-images.githubusercontent.com/440298/43914699-1d08bc72-9bf8-11e8-9d14-f9ba6d2f8900.jpg)

Indeed.

**Comment by 0rzech** [comment]
@jhabdas So you actually use only one of the buttons, not both, right?

**Comment by 0rzech** [comment]
@jhabdas Thanks for the screenshot. So you actually use only one of the buttons, not both, right?

**Comment by techknowlogick** [comment]
The image is for branding and the home link is to go home, the image is also linked to go home because that is a user experience that users have been trained to use where the icon/logo of a site in the top left corner of the site takes you home. The home link is for users who don't have that expectation.

**Comment by 0rzech** [comment]
@techknowlogick Thanks for clarification. Maybe we could merge both buttons into one with icon and text?

**Comment by lafriks** [comment]
@0rzech we can not as on moblie layout icon is shown always but Home link is moved to burger submenu

**Comment by 0rzech** [comment]
@lafriks Ah, forgot about that. Thanks.
