### ISSUE TITLE
head.tmpl cannot be customized - crashes

### ISSUE THREAD

**Issue by methodbox** [go-gitea/gitea#4655]
- Gitea version (or commit ref): 1.5
- Git version: 2.18
- Operating system: CentOS
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

Please excuse the fact that I’m on mobile and cannot fully complete this form.

The issue is simple: creating [gitea root dir]**/custom/templates/base/head.tmpl** and importing the *default* **head.tmpl will not allow Gitea to run.**

**Putting a simple head.tmpl with just html allows it to run** but this prevents making simple modifications (like removing buttons) a real pain.

I’ve worked around it by making a custom .../custom/templates/header.tmpl (not a typo) and importing JS to remove the elements I don’t want.

If there is a better way to modify the navigation links than replacing the head.tmpl with my own, slightly modified version, I’m all ears.

**Comment by lafriks** [comment]
Yes there is custom/templates/custom/... templates that can be used to add css and scripts. See docs section customization for more details

**Comment by lafriks** [comment]
In future please use forum (https://discourse.gitea.io/) for such questions

**Comment by methodbox** [comment]
I put the parts in bold that are important here. You reacted to the wrong statement.

You guys constantly close issues that are actual issues; wondering if you actually read the issue.
