### ISSUE TITLE
Discord Webhook Links To API JSON

### ISSUE THREAD

**Issue by atom0s** [go-gitea/gitea#4656]
- Gitea version (or commit ref): https://github.com/go-gitea/gitea/commit/a74426d631e3311cc3c460ae9917f76f0221f4de
- Git version: 2.17.1.windows.2
- Operating system: Windows Server 2012 R2 Standard
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist: N/A

## Description

When a Discord web hook is sent to a Discord server, the output looks fine, however the main link is to the API call of the hook creation, instead of being to the actual thing. For example, if a web hook is called on an issue being created, Discord will display the main link title properly, but it will link to the API such as:
https://git.example.com/api/v1/repos/Example/Example/issues/55

Instead of to the actual issue link of:
https://git.example.com/Example/Example/issues/55

**Comment by atom0s** [comment]
Side note, this does not happen with webhook callbacks that are responses to issues, just the initial callback for when the issue is first opened. The other callbacks so far appear to all work properly and give the correct links.

Edit - This is also affecting the issue close hook, the url for that one is wrong as well. Not too sure where to look in the Gitea source to check other hooks as well easier. I'm not familiar with Go or Gogs/Gitea's layout of code to know where to look since these are format generated strings.

**Comment by baxandrei** [comment]
I encounter this problem at present, on gitea-1.11.0-rc1-linux-amd64 version

**Comment by jolheiser** [comment]
> I encounter this problem at present, on gitea-1.11.0-rc1-linux-amd64 version
> 
> ```
> https://www.git.baxandrei.ro/api/v1/repos/EternumKings/FeedBack/issues/22
> INSTEAD OF
> https://www.git.baxandrei.ro/EternumKings/FeedBack/issues/22
> ```

This is fixed by #9661 and should be in `1.11.0-rc2` and the full release.
