### ISSUE TITLE
Changing Theme [ui] doesn’t work

### ISSUE THREAD

**Issue by methodbox** [go-gitea/gitea#4657]
- Gitea version (or commit ref):1.5
- Git version: 2.18
- Operating system: CentOS 
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

Setting default theme as per documentation does nothing.

[ui]
DEFAULT_THEME = arc-green

No change.

**Comment by techknowlogick** [comment]
@methodbox when filling out tickets please ensure you fill out all the details so you can be helped fully. The setting is likely not in the version of Gitea you are using. It is in 1.6.0-dev

**Comment by methodbox** [comment]
Then you should update your documentation to reflect this.

**Comment by LER0ever** [comment]
Hi @techknowlogick , I can confirm that theme option in Gitea master branch does not work as well.
`Gitea Version: 8da45ae` running on docker swarm. Can we reopen this one?

Relevant lines:
```
[repository.upload]
TEMP_PATH = /data/gitea/uploads

[ui]
DEFAULT_THEME = arc-green

[server]
APP_DATA_PATH    = /data/gitea
```

**Comment by methodbox** [comment]
From your own documentation, with no reference to version:

>Customizing the look of Gitea

>Gitea has two built-in themes, the default theme gitea, and a dark theme arc-green. To change the look of your Gitea install change the value of DEFAULT_THEME in the ui section of app.ini to another one of the available options.

**Comment by lafriks** [comment]
Just tested and setting in app.ini for latest master branch:
```
[ui]
DEFAULT_THEME = arc-green
```
works just fine

**Comment by brettphillips05** [comment]
In case someone stumbles upon this and wastes an inordinate amount of time to get the theme working, verify that you are at least running Gitea version `1.6.0`. After trying and failing a bunch, I noticed that I was running version `1.5.0`. The end of the [Customization document](https://docs.gitea.io/en-us/customizing-gitea/) mentions the following: 

> As of version 1.6.0 Gitea has built-in themes

I updated to the most recent version of Gitea and theme is active

**Comment by shoodabean** [comment]
The fix for me was the [ui] header should be lowercase, uppercase seems not to work.
