### ISSUE TITLE
windows sc insert system service, restart the operating system, gitea does not start

### ISSUE THREAD

**Issue by adleader** [go-gitea/gitea#4666]
- Gitea version (or commit ref): all version
- Git version: Git-2.14.2-64-bit
- Operating system: windows 2008
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [*] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

- windows sc insert system service, restart the operating system, gitea does not start

**Comment by lafriks** [comment]
You have to provide `start= auto` to `sc install`

**Comment by adleader** [comment]
@lafriks @zacheryph @ndarilek @clee @jbcrail 
The gitea has been set to auto in the system service, but the problem remains, I hope developers can test it in Windows 2008, I suspect that it is a problem of packaging binary. I use the scheduled task, boot gitea.exe startup, and can not run gitea

**Comment by lafriks** [comment]
Can you run gitea.exe from command line? What output do you get?
