### ISSUE TITLE
custom/templates override does not work

### ISSUE THREAD

**Issue by methodbox** [go-gitea/gitea#4671]
- Gitea version (or commit ref): 1.5
- Git version: 2.18
- Operating system: CentOS 
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

This was previously closed as a “question” about a subject which was not the purpose of the issue.

I want to be clear: this is NOT using custom/templates/custom.

Please do not close this and refer to your docs or forum, as this is **not working as documented. From your own docs:

>Customizing Gitea pages

>The custom/templates folder allows changing every single page of Gitea. Templates to override can be found in the templates directory of Gitea source. Override by making a copy of the file under custom/templates using a full path structure matching source.

The issue is simple: creating **[gitea root dir]/custom/templates/base/head.tmpl** and importing the **default head.tmpl** will not allow Gitea to run, which means it can’t be overridden.

Putting a simple head.tmpl with just html allows it to run but this prevents making simple modifications (like removing buttons) a real pain.

I’ve worked around it by making a custom .../custom/templates/header.tmpl (not a typo) and **importing JS to remove** the elements I don’t want, which is a hack, not a solution.

If there is a better way to modify the navigation links than replacing the head.tmpl with my own, slightly modified version, I’m all ears.

**Comment by SagePtr** [comment]
Do you use base/head.tmpl from `master` branch and not from `release/v1.5` branch ?
It may be incompatible due to addition of extra variables.
For me, head.tmpl from master branch doesn't work either if i use it with 1.5 gitea version.

**Comment by methodbox** [comment]
Honestly, your website makes it pretty obscure as to what the actual branch is that is “current”.

I’m using the 1.5 binary.

Let me know if there’s a better option - and maybe update the docs.

Edit - I just realized I think you mean the version of head.tmpl from master with the 1.5 binary, and yes that’s what I did.

Maybe that’s the issue.

It would be nice to have some clarification on exactly which is the “stable” branch, etc.

1.5 is the latest version of the binary on Gitea.io.

**Comment by 0rzech** [comment]
@methodbox If I'm not mistaken, you just have to look for release matching your binary on [releases](https://github.com/go-gitea/gitea/releases) page and just click appropriate tag under `Latest release` link on the left. Currently this would mean clicking on [v1.5.0](https://github.com/go-gitea/gitea/tree/v1.5.0).

**Comment by methodbox** [comment]
Okay the help is appreciated. I’ll have to test this Tues and post back as this is in a private environment I do not have remote access to.
