### ISSUE TITLE
http error 500 in apache reverse

### ISSUE THREAD

**Issue by anikdas012** [go-gitea/gitea#4676]
- Gitea version (or commit ref): 1.4.3
- Git version: 2.7.4
- Operating system:  Ubuntu 16.04.5 LTS
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:
Aug 12 11:49:58 ubuntu gitea[3330]: [Macaron] 2018-08-12 11:49:58: Completed GET / 500 Internal Server Error in 8.997548ms
Aug 12 11:51:58 ubuntu systemd[1]: Stopping Gitea (Git with a cup of tea)...
Aug 12 11:51:58 ubuntu gitea[3330]: 2018/08/12 11:51:58 Exiting pid 3330.
Aug 12 11:51:58 ubuntu systemd[1]: Stopped Gitea (Git with a cup of tea).
Aug 12 11:51:58 ubuntu systemd[1]: Started Gitea (Git with a cup of tea).
Aug 12 11:51:58 ubuntu gitea[3482]: 2018/08/12 11:51:58 [T] AppPath: /usb/gitea
Aug 12 11:51:58 ubuntu gitea[3482]: 2018/08/12 11:51:58 [T] AppWorkPath: /usb/Git
Aug 12 11:51:58 ubuntu gitea[3482]: 2018/08/12 11:51:58 [T] Custom path: /usb/Git/custom
Aug 12 11:51:58 ubuntu gitea[3482]: 2018/08/12 11:51:58 [T] Log path: /usb/Git/log
Aug 12 11:52:00 ubuntu gitea[3482]: 2018/08/12 11:52:00 Serving 127.0.0.1:3000 with pid 3482
Aug 12 11:52:19 ubuntu gitea[3482]: [Macaron] 2018-08-12 11:52:19: Started GET / for 113.35.108.77
Aug 12 11:52:19 ubuntu gitea[3482]: [Macaron] PANIC: session(start): chtimes /usb/Git/data/sessions/1/b/1bd2cacac532694a: operation not permitted
Aug 12 11:52:19 ubuntu gitea[3482]: /usr/local/go/src/runtime/panic.go:502 (0x3d21b)
Aug 12 11:52:19 ubuntu gitea[3482]: /srv/app/src/code.gitea.io/gitea/vendor/github.com/go-macaron/session/session.go:156 (0x3accb7)
Aug 12 11:52:19 ubuntu gitea[3482]: /srv/app/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/context.go:79 (0x365457)
Aug 12 11:52:19 ubuntu gitea[3482]: /srv/app/src/code.gitea.io/gitea/vendor/github.com/go-macaron/inject/inject.go:157 (0x340bdf)
Aug 12 11:52:19 ubuntu gitea[3482]: /srv/app/src/code.gitea.io/gitea/vendor/github.com/go-macaron/inject/inject.go:135 (0x3409c7)
Aug 12 11:52:19 ubuntu gitea[3482]: /srv/app/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/context.go:121 (0x36560f)
Aug 12 11:52:19 ubuntu gitea[3482]: /srv/app/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/context.go:112 (0x36556f)
Aug 12 11:52:19 ubuntu gitea[3482]: /srv/app/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/recovery.go:161 (0x37450f)
Aug 12 11:52:19 ubuntu gitea[3482]: /srv/app/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/logger.go:40 (0x3681af)
Aug 12 11:52:19 ubuntu gitea[3482]: /srv/app/src/code.gitea.io/gitea/vendor/github.com/go-macaron/inject/inject.go:157 (0x340bdf)
Aug 12 11:52:19 ubuntu gitea[3482]: /srv/app/src/code.gitea.io/gitea/vendor/github.com/go-macaron/inject/inject.go:135 (0x3409c7)
Aug 12 11:52:19 ubuntu gitea[3482]: /srv/app/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/context.go:121 (0x36560f)
Aug 12 11:52:19 ubuntu gitea[3482]: /srv/app/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/context.go:112 (0x36556f)
Aug 12 11:52:19 ubuntu gitea[3482]: /srv/app/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/logger.go:52 (0x373b03)
Aug 12 11:52:19 ubuntu gitea[3482]: /srv/app/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/logger.go:40 (0x3681af)
Aug 12 11:52:19 ubuntu gitea[3482]: /srv/app/src/code.gitea.io/gitea/vendor/github.com/go-macaron/inject/inject.go:157 (0x340bdf)
Aug 12 11:52:19 ubuntu gitea[3482]: /srv/app/src/code.gitea.io/gitea/vendor/github.com/go-macaron/inject/inject.go:135 (0x3409c7)
Aug 12 11:52:19 ubuntu gitea[3482]: /srv/app/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/context.go:121 (0x36560f)
Aug 12 11:52:19 ubuntu gitea[3482]: /srv/app/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/router.go:187 (0x3754bb)
Aug 12 11:52:19 ubuntu gitea[3482]: /srv/app/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/router.go:294 (0x36f1fb)
Aug 12 11:52:19 ubuntu gitea[3482]: /srv/app/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/macaron.go:220 (0x36943f)
Aug 12 11:52:19 ubuntu gitea[3482]: /srv/app/src/code.gitea.io/gitea/vendor/github.com/gorilla/context/context.go:141 (0x5c9433)
Aug 12 11:52:19 ubuntu gitea[3482]: /usr/local/go/src/net/http/server.go:1947 (0x24f527)
Aug 12 11:52:19 ubuntu gitea[3482]: /usr/local/go/src/net/http/server.go:2694 (0x2519ab)
Aug 12 11:52:19 ubuntu gitea[3482]: /usr/local/go/src/net/http/server.go:1830 (0x24e57f)
Aug 12 11:52:19 ubuntu gitea[3482]: /usr/local/go/src/runtime/asm_arm.s:1015 (0x6b033)
Aug 12 11:52:19 ubuntu gitea[3482]: [Macaron] 2018-08-12 11:52:19: Completed GET / 500 Internal Server Error in 10.395452ms

## Description
I've installed gitea 1.4.3 from binary in my ubuntu server 16.04. At first it showed me installation page but after restart it is showing me `currently unable to handle this request.
HTTP ERROR 500` . Runnig `sudo journalctl -f -u gitea.service` in terminal gives above output. I'm using apache reverse to run the server. 
...

**Comment by lafriks** [comment]
Looks like you are using usb drive to store gitea data with file system that doesn't support chtimes

**Comment by anikdas012** [comment]
Thank you. My problem is solved now.
