### ISSUE TITLE
Cannot recover from backup of gitea 1.4.0

### ISSUE THREAD

**Issue by fbettag** [go-gitea/gitea#4681]
- Gitea version (or commit ref):
- Git version: 1.4.0
- Operating system: FreeBSD 11.1 / Ubuntu 16.04
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
Trying to migrate (dump/restore) on gitea 1.4.0 on FreeBSD and move it to Ubuntu 16.04 running 1.5.0. I also tried every major release from 1.0.0 to 1.5.0 and i always get "[E] Fail to initialize ORM engine: sync database struct error: Unknown col name in indexe" with a different column in each version.

This database dump works fine on FreeBSD but when i try to start gitea web on 1.4.0 on Ubuntu, it won't start. Ideally i want 1.5.0 but best of all would be a running version.

If i remove all columns in question, this goes as far as ssh keys owner_id, which gets removed. is there any manual way to do db migration?
...

**Comment by lafriks** [comment]
It would be recommended to first run same version as you were running on freebsd. Does it give you any error?

**Comment by fbettag** [comment]
I already tried the 1.4.0 that my pkg info on freebsd shows me :) i downloaded the binary on Ubuntu with wget and i tried to alter table user drop column XYZ whatever it was reporting me.

To be totally honest, this was an old gogs installation that got migrated over with gitea 1.1. So i assume that there is still some db-fields that didn't get migrated.
