### ISSUE TITLE
Activated tick gets removed after while.

### ISSUE THREAD

**Issue by linuxshokunin** [go-gitea/gitea#4689]
- Gitea version (or commit ref): b37ca4a. I'm using the docker image with tag 1.5.
- Git version: 1.8.3.1
- Operating system: Arch Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
I have gitea installed on k8s cluster. Gitea is configured to authenticate with Ldap. 
Authentication is working fine but after while, the users' activated tick gets removed. 
Do you know why?

**Comment by linuxshokunin** [comment]
I don't have email settings so I manually activate each user.

**Comment by lafriks** [comment]
Check that your ldap sync settings are correct

**Comment by linuxshokunin** [comment]
I disabled ldap sync now. That job deactivate all ldap users.

**Comment by daviian** [comment]
Closed in favor of https://github.com/go-gitea/gitea/issues/3815

If you think this issue doesn't exactly match yours feel free to reopen.

Also related to: https://github.com/go-gitea/gitea/issues/4402, https://github.com/go-gitea/gitea/issues/4067 and https://github.com/go-gitea/gitea/issues/4433
