### ISSUE TITLE
Can't easily create a PR on my own fork.

### ISSUE THREAD

**Issue by JulienTant** [go-gitea/gitea#4698]
- Gitea version (or commit ref): 1.5.0
- Git version: git version 2.17.1
- Operating system: ubuntu
- Database :
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

If you create a fork of a project and decide to create a PR that you want to merge into your own fork, then your only choice is to edit the URL by hand because by default you will be redirected to the "main" project.

I expected to be able to create a pull request into my own project.

**Comment by lafriks** [comment]
I think there is already issue for this

**Comment by JulienTant** [comment]
Oh I found it, I was probably to tired yesterday night :-) https://github.com/go-gitea/gitea/issues/4566
