### ISSUE TITLE
Binary upgrade from gogs 0.9.71.0809 Failed to initialize ORM engine

### ISSUE THREAD

**Issue by termlimit** [go-gitea/gitea#470]
- Gitea version (or commit ref): 1.0.0 v6aacf4d
- Git version: 1.7.10.4
- Operating system: Debian 7
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:

## Description
Similar to https://github.com/gogits/gogs/issues/3759. Downloaded gitea binary and ran ./gitea web:
2016/12/24 00:25:14 [T] Custom path: /gogs/gogs/custom
2016/12/24 00:25:14 [T] Log path: /gogs/gogs/log
2016/12/24 00:25:14 [I] Gitea v6aacf4d
2016/12/24 00:25:14 [I] Log Mode: File(Info)
2016/12/24 00:25:14 [I] Cache Service Enabled
2016/12/24 00:25:14 [I] Session Service Enabled
2016/12/24 00:25:14 [I] Mail Service Enabled
2016/12/24 00:25:14 [I] Notify Mail Service Enabled
2016/12/24 00:25:14 [I] Migration: set comment updated with created
2016/12/24 00:25:14 [...itea/routers/init.go:53 GlobalInit()] [E] Fail to initialize ORM engine: migrate: do migrate: Sync2: no such index: IDX_comment_"idx_comment_IDX_comment_issue_id"
...

**Comment by termlimit** [comment]
I followed the comment for gogs #3759 and now the error is:
2016/12/24 00:50:14 [T] Custom path: /gogs/gogs/custom
2016/12/24 00:50:14 [T] Log path: /gogs/gogs/log
2016/12/24 00:50:14 [I] Gitea v6aacf4d
2016/12/24 00:50:14 [I] Log Mode: File(Info)
2016/12/24 00:50:14 [I] Cache Service Enabled
2016/12/24 00:50:14 [I] Session Service Enabled
2016/12/24 00:50:14 [I] Mail Service Enabled
2016/12/24 00:50:14 [I] Notify Mail Service Enabled
2016/12/24 00:50:14 [I] Migration: create user column diff view style
2016/12/24 00:50:14 [I] Git Version: 1.7.10.4
2016/12/24 00:50:14 [I] SQLite3 Supported
2016/12/24 00:50:14 [I] Run Mode: Production
2016/12/24 00:50:15 [I] Listen: https://0.0.0.0:3000
2016/12/24 00:50:15 [....io/gitea/cmd/web.go:632 runWeb()] [E] Fail to start server: open : no such file or directory

I was running the database in mysql on a centos machine before migrating to debian and sqlite around Gogs v0.9.60. Latest Gogs 0.9.113 is working after the fix above

**Comment by lunny** [comment]
Yes, 

DROP INDEX idx_comment_IDX_comment_issue_id;

**Comment by lunny** [comment]
I think maybe you have no correct filepath for `setting.CertFile` and `setting.KeyFile`?

**Comment by termlimit** [comment]
Would gogs run if that was wrong? I am running Gogs without issue for a
while now and SSL works and my certs are correct

**Comment by lunny** [comment]
Gitea moves all files in `conf` to `options` excepts `app.ini`. Maybe you could `cp -r ./conf ./options`.

**Comment by termlimit** [comment]
yea as I saved my pr for the config page, I noticed the pr that stated that
in there. I will try that in the am and report back

**Comment by termlimit** [comment]
Tried:
`
cd custom
cp -r conf/ options/
`
and then run gitea, same error as
previous:
`
[....io/gitea/cmd/web.go:632 runWeb()] [E] Fail to start server: open : no
such file or directory
`
Formatting in email.

**Comment by lunny** [comment]
```
cp -r conf/ options/
```
not `cd custom`

**Comment by termlimit** [comment]
Gogs has conf under the custom directory. You want options in the root path
with the gitea binary? That is not where conf is.

**Comment by lunny** [comment]
No. Gitea move `locale` and others from `conf/` to `options/` except `app.ini`.

**Comment by termlimit** [comment]
Probably a misunderstanding on my part, but I want to make sure I am
providing accurate feedback.

My current gogs directory structure:
custom/
data/
log/
public/
scripts/
templates/
LICENSE
README.md
README_ZH.md
gogs*

under custom/:
conf/
https/

Under conf/:
app.ini

Under https/:
cert.pem
key.pem

The docs say to copy conf/ to options/. The only thing in my conf/ is the
app.ini which you state stays in conf/. If I follow your instructions I
would have the following under custom/
conf/
https/
options/

Nothing would exist in options except a copy of app.ini. My https directory
would not be under options. I hope that all makes sense. I am standing by
for more questions, maybe an error in translating your intent to English? I
included a screenshot with my dirs from gogs

**Comment by termlimit** [comment]
Attachments don't email I guess.
![gogs-dirs](https://cloud.githubusercontent.com/assets/4793694/21470295/a149b1ca-ca36-11e6-8389-8ab5dcc276fd.jpg)

**Comment by lunny** [comment]
```
drwxr-xr-x  2 git git     4096 Dec 25 16:29 conf
drwxr-xr-x  3 git git     4096 Dec 25 16:32 custom
drwxr-xr-x  4 git git     4096 Dec 25 16:35 data
-rwxr-xr-x  1 git git 15269664 Dec 25 16:31 gitea
drwxr-xr-x  2 git git     4096 Dec 25 16:33 log
drwxr-xr-x  7 git git     4096 Dec 25 16:27 options
drwxr-xr-x  8 git git     4096 Dec 25 16:28 public
drwxr-xr-x 10 git git     4096 Dec 25 16:29 templates
```
This is one of my working instance. Maybe you can try copy `conf` and `options` from gitea source to your root dir.

**Comment by termlimit** [comment]
What is in your options/ dir?

**Comment by lunny** [comment]
https://github.com/go-gitea/gitea/tree/master/options

**Comment by termlimit** [comment]
I thought all of that was embedded in the binary release?

**Comment by termlimit** [comment]
The instructions for moving to gitea should note that this needs to be
copied. None of that exists in gogs under conf/

**Comment by lunny** [comment]
Yes, you are right. If you are using a bindata binary, it's no need! I will send a PR to correct it.

**Comment by termlimit** [comment]
OK I got it up and running. Here is what I recommend for the upgrade documentation.

As gitea user:
```
cd ~
eg /home/<USER>/
wget https://github.com/go-gitea/gitea/archive/v1.0.0.zip
unzip v1.0.0.zip
cp -r gogs gitea
cp -r giteav1.0.0/options gitea/options
cp -r gogs-repositories/ gitea-repositories
cp -r gogs-data/ gitea-data/
vim gitea/custom/conf/app.ini
```
Change gogs specific information:
```
[database]
PATH = /home/<USER>/gogs/data/<DATABASE>.db
[attachment]
PATH = /home/<USER>/gogs-data/attachments
[picture]
AVATAR_UPLOAD_PATH = /home/<USER>/gogs-data/avatars
[log]
ROOT_PATH = /home/<USER>/gogs/log
#to
[database]
PATH = /home/<USER>/gitea/data/<DATABASE>.db
[attachment]
PATH = /home/<USER>/gitea-data/attachments
[picture]
AVATAR_UPLOAD_PATH = /home/<USER>/gitea-data/avatars
[log]
ROOT_PATH = /home/<USER>/gitea/log
```

After that I was able to get gitea up and running without issue. This is with the binary version as well. Let me know if you need more information I can elaborate more or push this change to the docs if you are all in agreement.

**Comment by lunny** [comment]
Great! Could you send a PR to docs repo?

**Comment by termlimit** [comment]
Done, this can be closed now.
