### ISSUE TITLE
[Security] Stored XSS. Account Takeover possilble.

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#4703]
- Gitea version (or commit ref): any version with external issue tracker
- Git version: not relevant
- Operating system: not relevant
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

**Comment by techknowlogick** [comment]
Thoughts from top of my head, we could use net/url and validate that external issue tracker is a valid URL and the protocol of URL is http/https.

May have time in several hours to look into where to add this into code.

Thanks for report 😄

**Comment by cezar97** [comment]
Thank you @lafriks for the quick fix!

**Comment by lafriks** [comment]
@cezar97 thanks for report ;)

**Comment by cezar97** [comment]
Seems that existing settings are not forced to the new rules. See https://try.gitea.io/cezar97/Gitea_Issue_XSS. Can be done something for this?
PS: I know that the alert doesn't show aything, but that's beacuse cookies are now HtttpOnly. Other payloads like the 2) explained in the report works, if someone set they before the fix.
