### ISSUE TITLE
Try to update 1.4.5 to 1.5

### ISSUE THREAD

**Issue by kleper** [go-gitea/gitea#4712]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ x] No
  - [ x] Not relevant
- Log gist:

## Description

I have this error trying to update to last version:
2018/08/14 18:19:43 [...itea/routers/init.go:60 GlobalInit()] [E] Failed to initialize ORM engine: migrate: do migrate: Insert team units: Error 1062: Duplicate entry '1-1' for key 'UQE_team_unit_s'

**Comment by lunny** [comment]
>just clear table team_unit and restart the gitea should resolve your issue. Your issue is different from others.

see #4663
