### ISSUE TITLE
Users in Team with Administrator permissions get 404 when accessing repository

### ISSUE THREAD

**Issue by weirdbiz** [go-gitea/gitea#4713]
Gitea version (or commit ref): 1.5.0
- Git version: 2.18.0-windows.1
- Operating system: Windows 7 Professional
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

**Issue**: Users in Team with Administrator permissions get 404 when accessing private repository.

Steps to reproduce:

0. _User1_ creates: Organization, Private Repository inside it, Team with Administrative permissions to that Repository.
1. _User1_ adds _User2_ to the Team created before.
2. _User2_ opens link to the Repository and gets 404.

Bug is reproducible only with Teams that have Administrator permissions. Teams with Read or Write permissions work fine.

**Comment by weirdbiz** [comment]
Sorry, forgot important thing: Repository should be Private.

**Comment by adelowo** [comment]
Can confirm bug exists.... Would look at sending a fix before the day runs out

**Comment by rvillablanca** [comment]
when is possible get this fix ? I mean, are you planning make a minor release for this ?

**Comment by adelowo** [comment]
It will be backported to 1.5 

I’ve sent a PR already ( #4719 ) and it requires approval from one more maintainer
