### ISSUE TITLE
I suggest the ssh button to generate ssh address when using js to get the current page host way.

### ISSUE THREAD

**Issue by insionng** [go-gitea/gitea#472]
This allows the correct host to be obtained by default without properly configuring the [server] ROOT_URL address.

**Comment by lunny** [comment]
Thanks. Could you send a PR to gitea?

**Comment by tboerger** [comment]
The ssh is not equal to the Web host, so this doesn't work. The value just needs to be exposed to the installer

**Comment by lunny** [comment]
He means after you install a new instance of gitea, ssh clone address' host is empty.

**Comment by tboerger** [comment]
It's not empty, it just defaults to the wrong hostname.

**Comment by tboerger** [comment]
The setting https://github.com/go-gitea/gitea/blob/master/conf/app.ini#L102 is responsible for the host displayed there.

**Comment by lunny** [comment]
So we need send a bug fix?

**Comment by tboerger** [comment]
That's not a bug, it's simply not exposed on the installation wizard

**Comment by typeless** [comment]
> The setting https://github.com/go-gitea/gitea/blob/master/conf/app.ini#L102 is responsible for the host displayed there.

Why is there an 's' after $(DOMAIN)?

**Comment by tboerger** [comment]
> I thought that is a supported interpolation syntax 😆

That's how the ini lib implemented the interpolation ;)
