### ISSUE TITLE
FontAwesome Icons not displayed when using apache Reverse Proxy

### ISSUE THREAD

**Issue by vmario89** [go-gitea/gitea#4723]
- Gitea version (or commit ref): 1.5.0 (cfe6941) // 11.08.2018 (latest)
- Git version:2.17.1
- Operating system: Ubuntu 18 LTS on Odroid X4
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description
Hi,
i installed Gitea on my Odroid and i am using it via SSL. It works properly accessing it on the internal ip address or its provided ServerName like defined in apache vhost. Because i have my host behind a NAT i am forwarding it to another server to access it from outside via the real sub domain. So i got
- Server A behind NAT (static public ip, port forwarding via my home Router) - with Apache 2.4 running ReverseProxy (forwards http to https)
- Server B in public - with Apache 2.4 running ReverseProxy

This all works fine without any errors in log files.  **The only problem: font awesome icons are not loaded and not displayed but without any error message.** The problem does not occure on every place in UI but for example in the user edit menu.

The funny thing is that i set all vhosts to loglevel debug and no error log on Server A or B tell me sth about missing ressources which could not be loaded. also firefox/edge inspectors show absolutely zero error on console

...

## Screenshots

###Loading it directly from the host accessing it's IP adress / ServerName as provided in apache vhost
![grafik](https://user-images.githubusercontent.com/5631071/44176219-49284480-a0e9-11e8-97e2-5e4857f8468c.png)
![grafik](https://user-images.githubusercontent.com/5631071/44176746-55ad9c80-a0eb-11e8-91f5-1c4994ea9465.png)
![grafik](https://user-images.githubusercontent.com/5631071/44176779-70801100-a0eb-11e8-91bc-7be2fc5e54c3.png)

###Loading it via Reverse Proxy from another host
![grafik](https://user-images.githubusercontent.com/5631071/44176273-770d8900-a0e9-11e8-9d02-dd8458c16e96.png)
![grafik](https://user-images.githubusercontent.com/5631071/44176740-52b2ac00-a0eb-11e8-87f0-92cb942e252c.png)
![grafik](https://user-images.githubusercontent.com/5631071/44176797-7f66c380-a0eb-11e8-8f37-d5f6a15a2682.png)

Do you have any idea what could cause this?

**Comment by vmario89** [comment]
some addition: i compared the access logs when accessing on internal ip vs accessing from outside.

there are 3 files which are not loaded:
192.168.1.114 - - [15/Aug/2018:23:21:15 +0200] "GET /img/favicon.png HTTP/1.1" 200 12267 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:61.0) Gecko/20100101 Firefox/61.0"
192.168.1.114 - - [15/Aug/2018:23:21:17 +0200] "GET /vendor/assets/font-awesome/css/font-awesome.min.css HTTP/1.1" 200 7255 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:61.0) Gecko/20100101 Firefox/61.0"
192.168.1.114 - - [15/Aug/2018:23:21:17 +0200] "GET /vendor/assets/font-awesome/fonts/fontawesome-webfont.woff2?v=4.6.3 HTTP/1.1" 200 72912 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:61.0) Gecko/20100101 Firefox/61.0"

but they are accesible from outside when typing them in browser URL

**Comment by lafriks** [comment]
Check in browser development tools (F12) if there are any errors in console

**Comment by lafriks** [comment]
Also please ask questions in gitea forum (https://discourse.gitea.io/)

**Comment by vmario89** [comment]
Hi. The developer console shows no error

**Comment by lafriks** [comment]
That is strange :)

**Comment by GLedoussal** [comment]
I had the same problem and found this issue with google. I'm using Apache as a reverse proxy and all font awesome icons were missing with no error in the console.

After disabling ModPageSpeed on my gitea virtualhost, icons are showing.
