### ISSUE TITLE
User can approve or reject his/her own PR

### ISSUE THREAD

**Issue by adelowo** [go-gitea/gitea#4728]
- Gitea version (or commit ref): bc06ab4a31c54c5d164d53ec16d5c1089be9c3fe
- Git version: 2.15.2 (Apple Git-101.1)
- Operating system: MacOS
- Database (use `[x]`): 
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes ( https://try.gitea.io/lanre.adelowo/dotfiles/pulls/1#issuecomment-7378 )
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

A user can approve and/or reject a PR (s)he created... This behaviour doesn't exist on Github for example

> PS : (s)he can still merge the PR but cannot leave an approval or rejection review

...

<img width="1920" alt="screen shot 2018-08-16 at 15 27 51" src="https://user-images.githubusercontent.com/12677701/44214847-fa21f400-a168-11e8-9b0a-fb13001e9d05.png">
<img width="1920" alt="screen shot 2018-08-16 at 15 27 54" src="https://user-images.githubusercontent.com/12677701/44214848-fa21f400-a168-11e8-9e06-ea85dadb0d77.png">

**Comment by adelowo** [comment]
This is not for merging but for reviewing only.... You obviously can merge but not review

**Comment by adelowo** [comment]
@lunny uploaded some screenshots above... Hovering over those buttons give you the warning information

**Comment by lunny** [comment]
@adelowo you are right.
