### ISSUE TITLE
Long markdown tables are not scrollable horizontally

### ISSUE THREAD

**Issue by null-git** [go-gitea/gitea#4733]
- Gitea version (or commit ref): 1.5.0
- Git version: 2.18.0
- Operating system: Arch Linux
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
Markdown tables are not scrollable if they are longer than the markdown view container. See:
https://try.gitea.io/null-git/test2/src/branch/master/README.md or screenshot
**Expected result:** have a scroll bar at the bottom of the table an make it scrollable so that one can read the complete table content in the web view.

## Screenshots
https://s8.postimg.cc/hm89vtlh1/Screenshot_at_2018-08-16_21-08-42.png

**Comment by adelowo** [comment]
See #4401

**Comment by lafriks** [comment]
I think this is already fixed
