### ISSUE TITLE
Documentation / installation from binary : keep the same directory in the examples

### ISSUE THREAD

**Issue by tcharlss** [go-gitea/gitea#4735]
- Gitea version: 280ebcb
- Operating system: Linux
- Installation: from binary

## Description

The documentation is a bit confusing to newcomers such as myself regarding the installation directory, and thus the configuration.
There are 3 different installation directories given in the examples:

* In [Installation from binary](https://docs.gitea.io/en-us/install-from-binary/), it's `/usr/local/bin/`
* In [Run as a service](https://docs.gitea.io/en-us/linux-service/), it's `home/git/gitea/`
* Then in the [example supervisor configuration](https://github.com/go-gitea/gitea/blob/master/contrib/supervisor/gitea), it's `/home/git/go/src/github.com/go-gitea/gitea/`

After reading all this, I was a bit confused and kept asking myself "which one should I use in the end" ?
I think all the articles and all the examples should use the same directory to clear things up.

**Comment by lafriks** [comment]
Installation from binary would be recommended one. Other places need to be updated to conform to that
