### ISSUE TITLE
同一个组织内，允许对单个代码仓库进行权限控制

### ISSUE THREAD

**Issue by Sinoprise** [go-gitea/gitea#4736]
现在的模式是，同一个组织内的团队，共享所有代码库的权限，能否实现单个代码库按照不同人，或者不同团队进行权限控制。
另外增加一个选项，设置显示“探索”相关的内容？

这样，对于某些企业内部进行代码控制很有必要，谢谢。

**Comment by lunny** [comment]
Please speak English since this is a global community.
