### ISSUE TITLE
Change Git Release description

### ISSUE THREAD

**Issue by thimmy687** [go-gitea/gitea#4737]
- Gitea version (or commit ref): 1.5.0
- Git version: 2.18.0
- Operating system: Windows
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

Can't edit description of existing releases. 

...

**Comment by lafriks** [comment]
Can not seem to reproduce that. When clicking on edit link that is near release title I can edit description and title

**Comment by relikd** [comment]
I do have the same problem. A repository I had up and running on github. All releases (created via github GUI) can't be edited. There isn't even a clickable link. I can only open the tag which will show the tree state.

`Gitea version 1.10.0 built with GNU Make 4.2.1, go1.13.4 : bindata, sqlite, pam`

**Comment by relikd** [comment]
Are tags handled differently than releases?
You can try with a vanilla gitea installation and this repository: https://github.com/relikd/baRSS

In the installation step I disabled all external services (Local Mode is enabled).
Also disabled Self-Registration.

**Comment by relikd** [comment]
@lafriks 
And if I open the edit URL directly, it opens the edit form field (compared to a non-existing tag where I get a 404). However, after I click on save I get the 404 error and nothing is updated.
(also notice this "wrong" edit form does not show the branch / commit selection)

![screen](https://user-images.githubusercontent.com/1321720/70848624-d06c0080-1e74-11ea-8c15-23f59c42c1b0.png)

**Comment by lunny** [comment]
@relikd could you reproduce that on https://try.gitea.io ?

**Comment by relikd** [comment]
yup. Migrate from this URL: https://github.com/relikd/baRSS

**Comment by lunny** [comment]
https://try.gitea.io/lunny/baRSS/releases I didn't get 404.

**Comment by relikd** [comment]
How is this even possible? Here, with and without mirror. Both not working:

https://try.gitea.io/asdglkashdgask/baRSS/releases
https://try.gitea.io/asdglkashdgask/baRSS2/releases

**Comment by mrsdizzie** [comment]
@relikd you need to do a *migration* with your Github credentials to have the option to migrate issues and releases (among other things)

Push and mirror will only have what is stored in git itself which is the code and tags. 

You can edit releases but not tags, so you would need to do a full migration from Github to have releases (as @lunny has done in that example). Migration is what copies over anything not stored in git from Github.

So new->migration and then put in the repo URL and your Github credentials in order to see the extra migration options.

**Comment by relikd** [comment]
Alright, but then why do I need to use my credentials at all? The API is publicly accessible even without credentials, e.g.: https://api.github.com/repos/relikd/baRSS/releases
I'm hesitant to store my login credential on my publicly accessible server especially when there is no real need for.

Further, If I import the repo via manual push all tags create a non-editable release.
Then how should I modify that information afterwards?

**Comment by lunny** [comment]
@relikd Because github will limit the request limitation if you are using a public credential. You will fail after serval requests.

**Comment by relikd** [comment]
Is it possible to use github access tokens instead?
Either a token per user or a single admin token for all users?
OR at the very least, use a redirect to github to authenticate?

Again, I find it very shady to input my plain-text password into a third party application...

**Comment by lunny** [comment]
@relikd Yes, an access token is OK.

**Comment by relikd** [comment]
Perfect. I can't find a documentation on what is the minimum set of token scopes.  `public_repo` does not seem to be enough, gitea failes with "Migrating from X failed."
