### ISSUE TITLE
Unable to switch branches in Chrome

### ISSUE THREAD

**Issue by ansig** [go-gitea/gitea#4739]
- Gitea version (or commit ref): b1ad573 
- Git version: 2.15.2
- Operating system: Alpine Linux v3.7 (Docker)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ X ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ X ] No
  - [ ] Not relevant
- Log gist:

## Description

We have a fairly large Git repository (187440 checkins and 133 branches at the time of writing and the repository itself is quite large on disk too, around 1.8 GB) and I am looking into migrating this into Gitea. One minor error I noticed is that when viewing the repo in Chrome, we are unable to switch branches in the drop down menu.

The menu simply will not extend for this repository, but in Firefox it works and if I check another smaller repo, it works fine in both Chrome and Firefox.

I can see the following error in the developer tools console when viewing the large repo in Chrome:

```
Uncaught RangeError: Maximum call stack size exceeded
    at Function.ga [as find] (jquery.min.js:2)
    at m.fn.init.find (jquery.min.js:2)
    at HTMLDivElement.<anonymous> (index.js?v=59da7734b062331f8e9c9b672413e7b3:2228)
    at Function.each (jquery.min.js:2)
    at m.fn.init.each (jquery.min.js:2)
    at initFilterBranchTagDropdown (index.js?v=59da7734b062331f8e9c9b672413e7b3:2216)
    at initRepository (index.js?v=59da7734b062331f8e9c9b672413e7b3:466)
    at HTMLDocument.<anonymous> (index.js?v=59da7734b062331f8e9c9b672413e7b3:1873)
    at j (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
```

We do not have as many branches, for example, https://try.gitea.io/ahmedlhanafy/gitlab-ce and there I do not see this error. We do have a lot of tags though (171079) and viewing them is hard on Firefox as well (the drop down is VERY slow if I switch to tags, but it does eventually seem to be able to show them all).

I do not see any strange characters in any of our branch or tag names (only \W plus forward slashes and dashes, I think.

Other info:

Chrome - 68.0.3440.106
Firefox - 61.0.2

## Screenshots

In Chrome:

![bild](https://user-images.githubusercontent.com/450102/44269077-be079580-a233-11e8-8a37-3d0a17e3647d.png)

In Firefox:

![bild](https://user-images.githubusercontent.com/450102/44269175-0f178980-a234-11e8-8129-b5a7e9fca754.png)

**Comment by lafriks** [comment]
For such large branch/tag count there probably need some optimizations to show only first 100 probably and than load from server when typing in filter input
