### ISSUE TITLE
Provide system for saving credentials

### ISSUE THREAD

**Issue by dobrakmato** [go-gitea/gitea#4741]
- Gitea version (or commit ref): 1.5.0-dev (#1b2aff0)
- Git version: git version 2.11.0
- Operating system: Debian 9
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

I was recently migration a lot of projects from git server to gitea instance. On each migration I had to type *Clone Authorization* credentials. It would be cool, if these could be saved somewhere in settings, and when migration repository, user could just choose credentials that would be used for cloning the repository.

**Comment by lunny** [comment]
You can do migration via Gitea API
