### ISSUE TITLE
Is it possible to have Wiki, Issues and Pull Requests disabled by default for new repositories ?

### ISSUE THREAD

**Issue by jbsarrodie** [go-gitea/gitea#4750]
- Gitea version (or commit ref): 1.5.0
- Git version: 2.18.0.windows.1
- Operating system: Windows
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

Hi, First of all thank you all for the great work on Gitea. That's really good!

I'm using Gitea as part of a custom solution based on [Archi](https://www.archimatetool.com/) and its [collaboration plugin](https://github.com/archimatetool/archi-modelrepository-plugin). In this context I'm defining a custom configuration and set of templates & locales.

I'd like to have Wiki, Issues and Pull Requests disabled by default for new repositories. In fact I'd like to even be able to disable some of them completely. Is there a way to do this through app.ini or other (maybe not documented) trick ?

For the moment I'm planning to hack templates, but that's not a good solution IMHO.

Regards,

JB

**Comment by lunny** [comment]
I think it's not difficult, need some config option in app.ini.

**Comment by lafriks** [comment]
@jbsarrodie new options

**Comment by gsantner** [comment]
Would welcome some more `app.ini` options aswell, could work just as `DEFAULT_ENABLE_TIMETRACKING` do.
Always do disable Wiki and Issues on new repos and enable it when required. Especially when using gitea for much repo mirrors this just means more clicks :D. (I don't want users to create issues or something on mirrors e.g. ).

**Comment by andreas-h** [comment]
Sorry for hijacking this issue a bit -- please let me know if I should rather create a separate issue.

What I would really like is to be able to have PRs, Wiki and Issues disabled by default *for forks only*, and enabled by default otherwise.  In our organisation, several people will work with their own copies i.e. forks of a repo, but we want to keep issues etc in the central repo.

**Comment by alexanderadam** [comment]
Similar to that it could be useful to have a setting to use external issue trackers by default if possible (i.e. `https://github.com/go-gitea/gitea/issues`).

**Comment by 6543** [comment]
yes:

https://github.com/go-gitea/gitea/blob/5c0697ad1ecbd25ff245a93ea5af55c07817249e/custom/conf/app.example.ini#L54-L60
