### ISSUE TITLE
document description can't render emoji

### ISSUE THREAD

**Issue by akkuman** [go-gitea/gitea#4753]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (https://try.gitea.io/Akkuman/test_commit_emoji)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

document description can't render emoji

## Screenshots

![深度截图_选择区域_20180821200037.png](https://i.loli.net/2018/08/21/5b7bfefe8c7f1.png)

**Comment by lunny** [comment]
should be closed by #5168
