### ISSUE TITLE
The docker image did not install git-lfs

### ISSUE THREAD

**Issue by Haixing-Hu** [go-gitea/gitea#4756]
- Gitea version (or commit ref):  Gitea version ce7c64c built with: bindata, sqlite
- Git version: git version 2.15.2
- Operating system: docker image gitea/gitea 
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description

The docker image of gitea did not install git-lfs. Therefore the client side could commit lfs objects but cannot pull lfs objects.

Following procedure will reproduce the problem:

- install a docker image gitea/gitea
- create a repository and add some binary file.
- git lfs track the binary file.
- push to the repository
- try to clone the repository in another place. It will fail to pull the lfs object.

**Comment by lafriks** [comment]
But server does not need to have git-lfs installed for it to work on client side

**Comment by Haixing-Hu** [comment]
@lafriks No，the server must have the git-lfs installed to make the gitea work correctly.  If the server has no git-lfs, checking out a lfs repository always failed. But if it installed, checking out succeeds.

**Comment by lafriks** [comment]
Are you talking about editing files from UI?

**Comment by sapk** [comment]
@Haixing-Hu Can you provide more details on an example/story when gitea failed because it missed git-lfs ? For exemple what command you used.

**Comment by techknowlogick** [comment]
@Haixing-Hu following up on @sapk's question. Would you be able to provide more details?

**Comment by techknowlogick** [comment]
Closing as needs-feedback. Please re-open if needed.
