### ISSUE TITLE
500 error creating pull request for LFS repo

### ISSUE THREAD

**Issue by DarkMorford** [go-gitea/gitea#4760]
- Gitea version (or commit ref): 1.5.0
- Git version: 2.18.0.windows.1
- Operating system: Windows Server 2016
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant

## Description
Creating a pull request on a repository that uses LFS produces a 500 error.

Relevant log snippet:

    2018/08/21 10:19:06 [...routers/repo/pull.go:839 CompareAndPullRequestPost()] [E] PushToBaseRepo: Push: exit status 1 - batch request: missing protocol: "G:\\GitRepos\\storageteam\\qualificationtools.git/info/lfs"
    error: failed to push some refs to 'G:\GitRepos\storageteam\qualificationtools.git'

**Comment by Akcaxup** [comment]
Pull Request is not created if assigned participant in this moment.

**Comment by lafriks** [comment]
I think there was already issue reported about this

**Comment by lunny** [comment]
related with #4463, but that issue is merging issue not creating.

**Comment by iCodeSometime** [comment]
This is happening for me as well

**Comment by zeripath** [comment]
I think I've finally found the cause and a workaround:

I suspect that you have git-lfs version greater than 2.3.4 installed on your server and gitea user has a .gitconfig file containing:

```ini
[filter "lfs"]
	clean = git-lfs clean -- %f
	smudge = git-lfs smudge -- %f
	process = git-lfs filter-process
	required = true
```

If you remove that that should act as a workaround.

**Comment by zeripath** [comment]
This is a duplicate of #732
