### ISSUE TITLE
git push error after upgrade git server from 1.8 to 2.1

### ISSUE THREAD

**Issue by pc10201** [go-gitea/gitea#4763]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description

I use CentOS 7 and install git 1.8,after I upgrade git from 1.8 to 2.1.
I can not push
...

**Comment by lafriks** [comment]
what error do you get?

**Comment by pc10201** [comment]
I think it is OK now.
I forget restart the gitea process.
