### ISSUE TITLE
'latest' tag seems to be broken - docker

### ISSUE THREAD

**Issue by ToeiRei** [go-gitea/gitea#4766]
- Gitea version (or commit ref): 'latest' docker image as of >1.5
- Operating system: photonOS by vmware
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant

## Description

`docker run --name=Gitea -v gitea-data:/data -p 22:22 -p 3000:3000 --net=DMZ --ip=10.0.0.4 -d gitea/gitea:latest`

bails out as follows:

```
docker: Error response from daemon: chown /var/lib/docker/volumes/gitea-data/_data: invalid argument.
See 'docker run --help'.
```

while
`docker run --name=Gitea -v gitea-data:/data -p 22:22 -p 3000:3000 --net=DMZ --ip=10.0.0.4 -d gitea/gitea:1.5`

just works fine.

Details about the image tagged as 1.5:
- sha256:cf381b60bc302b6a484b677d547af73f289365a023879a53c5b8ca513b5f0156
- Size: 75.4 MB
- Created:  2018-07-12 18:13:34
- Build on Docker 17.12.0-ce on linux, amd64

gitea-data is a named volume living on a NFS server.

**Comment by daviian** [comment]
How do you mount the nfs volume into the docker container?

**Comment by daviian** [comment]
I think your problem could be somehow related to https://github.com/moby/moby/pull/33695

**Comment by ToeiRei** [comment]
That shouldn't be able to break things that hard. It's got to do with chown... at least in some way as I squash root on NFS as usual.

**Comment by ToeiRei** [comment]
anything I am able to help here?

**Comment by lafriks** [comment]
I don't know how gitea docker image would have broken as not much has changed either in build process nor dockerfile. Did you try nocopy? I found this recommendation in multiple places for such problem

**Comment by ToeiRei** [comment]
I use nocopy. But the main question still remains: 1.5 and 1.5.1 work perfectly. Why not :latest?

**Comment by lafriks** [comment]
I have no explanation for that :(

**Comment by ToeiRei** [comment]
Okay. Back to the root(s): I'm going to build it locally.
