### ISSUE TITLE
gitea 1.5

### ISSUE THREAD

**Issue by stspqxl** [go-gitea/gitea#4767]
When a team is set up as a management authority, the team warehouse is opened to 404.
If a team is set to write, all items are allowed to be used normally.
The gitea version is 1.5.

在把一个团队设置成为管理权限的时候，团队仓库打开就404；
如果把一个团队设置成为写入，全部项目允许，才能正常使用
gitea 版本是1.5

**Comment by lunny** [comment]
This has been fixed via #4719

**Comment by stspqxl** [comment]
error is  https://hub.docker.com/r/gitea/gitea/

tags:1.5
