### ISSUE TITLE
DISABLE_REGISTRATION reset to false

### ISSUE THREAD

**Issue by RickZeeland** [go-gitea/gitea#4768]
- Gitea version (or commit ref): 1.5
- Git version: 2.11
- Operating system: Windows 10
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
In the app.ini file the setting **DISABLE_REGISTRATION** was reset to false after upgrading to Gitea 1.5,
we don't want anyone to be able to register themselves.
No further complaints (till now 👍 )

**Comment by lafriks** [comment]
Upgrade does not change values set in app.ini
