### ISSUE TITLE
Admin team's permission is dependent on user selected permissions

### ISSUE THREAD

**Issue by adelowo** [go-gitea/gitea#4771]
- Gitea version (or commit ref): 6ca8fbd2f94a1a02e1776a1d62ad2fb897839e47
- Git version: git version 2.15.2 (Apple Git-101.1)
- Operating system: MacOS
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant

## Description

STEPS :

- Create new team
- In permissions, choose any of read and write, then untick code, issues, pull requests .
- Then choose Administrator access in permissions
- Then Update settings

- Add a repository to the team,
- Add a non admin user to the team 
- Access the repository, The user would not have any of the unticked permissions earlier even though he is in a team with admin access. ( for instance, he cannot view issues, PRs )

I would expect that the admin team gets all available permissions regardless of the selection(s)

**Comment by lunny** [comment]
admin Team should have write permissions of all the units on the repositories of the organization.

**Comment by lunny** [comment]
should be fixed by #5314 , close now and please feel free to reopen.
