### ISSUE TITLE
No document about how to setup Active Directory account

### ISSUE THREAD

**Issue by dlintw** [go-gitea/gitea#4781]
- Gitea version (or commit ref):
- Git version: any
- Operating system: any
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

The ldap document is too simple for setup an Active Directory for Windows account.  Could anyone give an example there?

**Comment by lafriks** [comment]
Docs contains all samples needed on how to setup for MS AD. Specific parts are marked as `Example for Microsoft Active Directory (AD): ` check https://docs.gitea.io/en-us/authentication/

**Comment by dlintw** [comment]
Thanks. I just check zh-tw version and it is empty.
