### ISSUE TITLE
Access-Control-Allow-Origin at try.gitea.io

### ISSUE THREAD

**Issue by sustrik** [go-gitea/gitea#4787]
I am making a browser-based application that uses Gitea API. I wanted to test it against try.gitea.io

However, it doesn't work because Access-Control-Allow-Origin is not set. Can it be possibly set to * ?

**Comment by SagePtr** [comment]
For example, put your own nginx before gitea as reverse proxy and configure header there.

**Comment by lafriks** [comment]
That would be security issue. You can always set up your local test instace with sqlite.
