### ISSUE TITLE
Migrate issues and wikis options when migrating from github

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#479]
On migrate UI, we could provide checkboxes to issues and wikis when the clone URL is a github URL and after that be checked. wikis and issues will both be migrated when codes migrated.

**Comment by FM-96** [comment]
I think Bitbucket and GitLab support would also be great, if that's possible.

**Comment by lunny** [comment]
If there are APIs, I think it's yes.

**Comment by bkcsoft** [comment]
Importing issues and merge requests from GitLab will be a PITA since they have separate indexes. Meaning we'll get collisions everywhere...

**Comment by dakira** [comment]
Here's a script that does this: https://lolg.it/herby/gh2gogs

**Comment by dakira** [comment]
@ryanburnette You can get an export tarball somewhere from github. If I remember correctly you also get that through the Github API. The script (which needs to be run with nodejs) just goes through the tarball and uses the Gogs API to create all the issues and pullrequests. I'd much rather write something that adds this directly to the DB. Should be quite easy, really.

**Comment by techknowlogick** [comment]
Here is a project that works with Gitea API: https://git.jonasfranz.software/JonasFranzDEV/gitea-github-migrator

**Comment by cpetry** [comment]
Any news on issue migration from gitlab? Some ideas?

**Comment by lunny** [comment]
Will be fixed by https://github.com/go-gitea/gitea/pull/6290

**Comment by lunny** [comment]
Closed by #6290 in v1.9. @techknowlogick
