### ISSUE TITLE
Docker SSH server key does not persist

### ISSUE THREAD

**Issue by Shadow53** [go-gitea/gitea#4791]
- Gitea version: docker gitea/gitea:latest (1.5.0)
- Git version: N/A
- Operating system: Fedora Server w/ Docker
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

If Gitea is set up in a Docker container and allows SSH for git, restarting the container (in this case via `docker stack deploy`/`rm`) causes the server's SSH key to change and a warning to appear on the machine attempting to push/pull to/from the server.

This is likely more of a documentation issue, as I was able to fix the issue by adding a volume mounted in the container at `/data/ssh` - this works for bind mounts and standard volumes. Just something where the container's SSH server keys can persist.

**Comment by sapk** [comment]
If you redeploy/update a docker service a new container is started so all the filesystem is lost. It is recommended in the docs to use a volume for the path /data (https://docs.gitea.io/en-us/install-with-docker/#basics).

**Comment by Shadow53** [comment]
Well whoops. I thought I had copied the documentation when I set up the Docker container, which should have copied the volume bit. Guess I didn't. My bad :sweat_smile:
