### ISSUE TITLE
Macaron logs are output to console instead of to file as configured

### ISSUE THREAD

**Issue by lukasbestle** [go-gitea/gitea#4795]
- Gitea version (or commit ref): 1.5.0
- Git version: 2.18.0
- Operating system: macOS 10.11
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
  - [x] No access to the logs
- Log and config gist: https://gist.github.com/lukasbestle/ee3aa793ce1223b5aa92a9aca1818b17

## Description

I have configured Gitea to write its logs to file (see the Gist I linked to above). However the Macaron logs are still output to console even though I'd expect them to be output to the `logs/http.log` file.

Please let me know if you need any further information

**Comment by lunny** [comment]
Is this a upstream macaron problem?

**Comment by lukasbestle** [comment]
I’m not comfortable enough with the Gitea codebase, but given that the logging options are Gitea options and there is [no related issue in the Macaron repo](https://github.com/go-macaron/macaron/issues), I’d say it’s probably an issue in Gitea itself.

Can you reproduce the issue on your machine?

**Comment by lafriks** [comment]
I think this option depends on environment setting for macrond (development or production)

**Comment by lukasbestle** [comment]
Ping

**Comment by lunny** [comment]
should be fixed by #5667 ?
