### ISSUE TITLE
Fork button is unclickable if user is not logged in

### ISSUE THREAD

**Issue by SagePtr** [go-gitea/gitea#4798]
- Gitea version (or commit ref): b63e2e0
- Git version: any
- Operating system: any
- Database (use `[x]`): any
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL) https://try.gitea.io/go-gitea/lgtm (open in incognito window)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

Open any gitea repo being not signed in (for example, in new private mode window).
`Watch` button is clickable and leads to /user/login
`Star` button is clickable and leads to /user/login too
`Fork` button pretends being clickable (has hover and pressed state), but does absolutely nothing when clicking and does not receive focus with Tab key.

Supposed behavior: it should redirect to /user/login page too (as two other buttons near it)

**Comment by techknowlogick** [comment]
There is "can this user fork this repo" logic, and if a user is not logged in then the application doesn't know if a user can fork it or not, and so it would be misleading to allow a user to click on the fork button, but it turns out they can't fork.

**Comment by SagePtr** [comment]
Maybe for unauthenticated users this button should redirect back to repo page after logging in, so user can login and click it again.
Or it should show popup hint about not being logged in (like "Sign in to fork this repo") instead of no reaction at all.
