### ISSUE TITLE
Gamemaker studio 2: Modified files have modification time as "59 minutes from now"

### ISSUE THREAD

**Issue by CoderReece** [go-gitea/gitea#4804]
- Gitea version (or commit ref): Latest Release from current date.
- Git version: 2.18.0
- Operating system: Windows 10
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:
No logs at the moment.

## Description
I believe this is a software compatibility issue. I've been using gitea for some time now since Gamemaker studio 2 forced me over from svn. I like git it's helpful.

This issue is that after pushing a commit to the repo the modified files say "59 minutes from now" as the modification date. I've tried applying commits for other projects not using gamemaker studio and the time is correct.

## Screenshots

Screenshot is 6 minutes after the issue. effected files are "53 minutes from now"
![timeissue](https://user-images.githubusercontent.com/8761891/44677473-e6f70a00-aa2d-11e8-8500-fe5e156f0355.PNG)

**Comment by SagePtr** [comment]
Does "git log" command run from local repo prints correct time or shifted by 59 minutes too? 
If shifted, this is issue with software you are making commits with, looks like wrong timezone setting.

**Comment by CoderReece** [comment]
> Date:   Mon Aug 27 19:09:55 2018 +0100

It looks correct however i am unsure of what "+0100" is. could that be an offset?

**Comment by CoderReece** [comment]
I can't find anything in the git documentation on how to change the repo time.

**Comment by SagePtr** [comment]
+0100 is timezone (UTC+1)

**Comment by CoderReece** [comment]
I know that i just don't know how to apply that to the git i'm very new to git

**Comment by SagePtr** [comment]
And another question: does http://time.is/ shows right time or it detects clock wrong?

**Comment by SagePtr** [comment]
Then computer time seems to be correct, and what about server time on which your gitea instance is installed? You can check it with developer tools of any browser, open Network tab, reload page with your remote repo and look "Date" response header.

**Comment by CoderReece** [comment]
Hmm the response header date is behind the current time, right now the time is 00:34
Date: Mon, 27 Aug 2018 22:34:39 GMT

**Comment by SagePtr** [comment]
So it's problem with server clock then, ask server administrator to adjust it

**Comment by CoderReece** [comment]
This is strange the server time is now wrong and the webserver also reports a different time however the commits are 10 seconds off, in which i can live with.

It might be because I've got it going through an apache reverse proxy.

Although do you know why this wasn't happening with my previous projects outside of gamemaker?
