### ISSUE TITLE
Restore: lack of information

### ISSUE THREAD

**Issue by markuman** [go-gitea/gitea#4805]
When restore a gitea instance, everything works for me, execept for the build-in wiki when the paths of `gitea` binary and location of `app.ini` changed.  
Because all repositories with a wiki in-use have `pre-`, `update`and `post-receive` hooks with hardcoded path for `gitea` binary and `app.ini`.   
Luckily this can be fixed with the power of grep and sed

when the former location of `gitea` binary was `/home/olduser/gitea/gitea` and is now `/app/gitea/gitea`

```
grep -rl '/home/olduser/gitea/gitea' gitea-repositories/* | while read filename; do 
    sed -i 's,/home/olduser/gitea/gitea,/app/gitea/gitea,g' "$filename"; 
done
```

and for the former location of `/home/olduser/gitea/custom/conf/app.ini`, which is now `/data/gitea/conf/app.ini`

```
grep -rl '/home/olduser/gitea/custom/conf/app.ini' gitea-repositories/* | while read filename; do 
    sed -i 's,/home/olduser/gitea/custom/conf/app.ini,/data/gitea/conf/app.ini,g' "$filename"; 
done
```

Maybe this someone runs into the same trouble...and maybe this should be added (in some form) to the restore documentation? What do you think?

**Comment by lunny** [comment]
You can rewrite then on Admin Panel.

**Comment by techknowlogick** [comment]
Please feel free to open PR adding this to the restore documentation. This already exists on the troubleshooting page.

I will now close this issue.
