### ISSUE TITLE
Export issues to Excel and/or generate PDF

### ISSUE THREAD

**Issue by fiLLLip** [go-gitea/gitea#4808]
- Gitea version (or commit ref):
1.5.0
- Git version:
2.17.0.windows.1
- Operating system:
Windows Server 2012 R2
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:
Not applicable

## Description
I use the issue tracker to track issues reported from a client. Now the client wanted the issue list with statuses (and comments) exported to a Excel file or PDF.
I then have three feature requests:

- Export issue list based on current filter to Excel
- Export all issues with comments based on current filter to PDF
- Export current issue with comments to PDF

## Screenshots
Not applicable

**Comment by techknowlogick** [comment]
Sounds like a good use case for using the API.

**Comment by a7hybnj2** [comment]
This functionality would be awesome.

(Well, now that the title has changed it does match my issue...thanks)

**Comment by a7hybnj2** [comment]
project.issues.git #4160

**Comment by a7hybnj2** [comment]
go away stale bot. quit killing good ideas.

**Comment by razzlez** [comment]
This is super relevant for companies.

**Comment by guillep2k** [comment]
As proposed by @techknowlogick, I also think this would be better implemented as a companion tool using API rather than implemented inside Gitea.

**Comment by lunny** [comment]
So how about to implement it in https://gitea.com/gitea/tea ?

**Comment by IvanSivak** [comment]
Hi everyone, I have made a small python utility that will fetch the Gitea issues through the API and export them to CSV (Excel). Hope it helps someone: https://github.com/botx-cloud/gitea_issues_exporter
