### ISSUE TITLE
Export notifications through the API

### ISSUE THREAD

**Issue by gergelypolonkai** [go-gitea/gitea#4811]
- Gitea version (or commit ref): c784ac5
- Git version: 2.17.1
- Operating system: Fedora 27
- Database (use `[x]`):
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

It would be nice to access notifications via the API, just like on GitHub: https://api.github.com/notifications
...

**Comment by adelowo** [comment]
@lunny can I work on this ?

**Comment by lunny** [comment]
@adelowo yes, please!

**Comment by gergelypolonkai** [comment]
@adelowo did you have time to work on this?

**Comment by adelowo** [comment]
Sadly enough No.. @gergelypolonkai 

I will try to get to it next week

**Comment by mmarif4u** [comment]
@adelowo that will be great. As I am planning to add notifications to the Android app(GitNex) to make it more user interactive.

Waiting for this important API implementation.

https://gitlab.com/mmarif4u/gitnex

**Comment by xxxtonixxx** [comment]
I'm waiting this feature too. I use gitnex :smile:

**Comment by mmarif4u** [comment]
@xxxtonixxx thanks for using GitNex. I know this is one of the important feature. :)

**Comment by 6543** [comment]
GitHub has a well structured api about that https://developer.github.com/v3/activity/notifications/#list-your-notifications is there any update?

**Comment by lunny** [comment]
@6543 nobody are working on this.

**Comment by 6543** [comment]
## Status: Ready only Tests needed and depend on two PR!

# -> #4811

**Comment by 6543** [comment]
Interested people can test this PR now
