### ISSUE TITLE
issue uploading attachments on 1.5.0

### ISSUE THREAD

**Issue by ryanburnette** [go-gitea/gitea#4815]
- Gitea version (or commit ref): 1.5.0
- Git version: 2.7.4
- Operating system: ubuntu 16.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No https://try.gitea.io/pppp/neovim/issues/2
  - [ ] Not relevant
- Log gist:

## Description

When I try to upload files it fails. See the error log below.

- directory permissions are good
- disk not full

## Screenshots

![screen shot 2018-08-28 at 12 36 12 pm 2](https://user-images.githubusercontent.com/2252601/44737533-4271d800-aac0-11e8-862c-52356f544ab0.png)

**Comment by adelowo** [comment]
Cannot replicate though.. Can you run `SELECT * FROM attachment WHERE uuid="xxxxxx"` on the db ?

**Comment by ryanburnette** [comment]
![screen shot 2018-08-28 at 1 18 43 pm](https://user-images.githubusercontent.com/2252601/44739114-ea89a000-aac4-11e8-9e89-8eb028934048.png)

**Comment by ryanburnette** [comment]
I also rsynced the uploaded files back to my desktop and they appear to be in working order.

**Comment by ryanburnette** [comment]
I tried 1.4.0 and have the same issue. Must be something with my system.

**Comment by ryanburnette** [comment]
I tracked down this issue and it wasn't in Gitea.
