### ISSUE TITLE
Error 500 when add ssh keys on Windows platform.

### ISSUE THREAD

**Issue by kempliu** [go-gitea/gitea#4816]
- Gitea version (or commit ref):179123d
- Git version:git version 2.16.2.windows.1
- Operating system: Windows Server 2016/10
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:
2018/08/29 07:20:26 [...user/setting/keys.go:96 KeysPost()] [E] AddPublicKey: 'ssh-keygen -lf C:\Users\ELITEB~1\AppData\Local\Temp\gitea_keytest516028331' failed with error 'exec: "ssh-keygen": executable file not found in %PATH%': 

## Description
I can run ssh-key in Command Line Model and Git Bash. Also copied ssh-keygen.exe to the same path of gitea.exe without luck.
...

**Comment by leepfrog-ger** [comment]
You need to add the folder where ssh-keygen is located to the PATH environment variables. Default would be `C:\Program Files\Git\usr\bin\`.

Then restart the whole system to make sure the contents of PATH are not still in cache (or close all command prompts/processes and start gitea again).

**Comment by lafriks** [comment]
closing as answered
