### ISSUE TITLE
Support to readme in rst format

### ISSUE THREAD

**Issue by joubertredrat** [go-gitea/gitea#482]
Hi guys,

For future I think that is good idea to support rst format to be processed on view, what you think?

https://github.com/silexphp/Silex
https://try.gitea.io/joubertredrat/Silex

Thanks.

**Comment by tboerger** [comment]
We already got an issue where somebody suggested an external renderer for that. AFAIK there is no mature go lib out there to render rst

**Comment by tboerger** [comment]
And here is a Gogs issue for that https://github.com/gogits/gogs/issues/211

**Comment by lunny** [comment]
This has been discussed in #374 .
