### ISSUE TITLE
Associate one team to more organizations - Feature Request [kind/feature]

### ISSUE THREAD

**Issue by tomtom125** [go-gitea/gitea#4822]
Hi,

It would be great if  an admin could associate one team to more than one organization in gitea web ui and with rest API.
With this "team grouping" would be much more easier and faster to associate team members to more orgs, than associate user to more orgs one by one, especially if there is more than 10 users.

Thanks.
Tom

**Comment by lafriks** [comment]
Such global groups would be also needed to implement group syncing from LDAP

**Comment by lunny** [comment]
duplicated with #3642
