### ISSUE TITLE
Proposal: gitlab importer

### ISSUE THREAD

**Issue by ascandella** [go-gitea/gitea#4825]
you Id like to migrate my self hosted gitlab instance to gitea. I can see that there are APIs on both ends that probably do what I want but wanted to sanity check here before I go build something new.

I imagine I’d create this as a stand-alone tool that could perhaps be upstreamed if desired. 

Is this something you all would be interested in, or should I just build a one off tool for myself?

Edit: I found https://github.com/MarcelSimon/MigrateGitlabToGogs/blob/master/README.md

Thoughts on the current process (is it sufficient?) from the view of the gitea team? It looks like it doesn’t migrate over users, perhaps intentionally?

**Comment by techknowlogick** [comment]
There is a github migrator that was built by @JonasFranzDEV found at https://git.jonasfranz.software/JonasFranzDEV/gitea-github-migrator

Perhaps you might be able to use that as a base to speed up your development.

I've also made a simple script for migrating Gitlab/Github -> Gitea that you can find here: https://gist.github.com/techknowlogick/c2367e03baff9f16b3c5cc9d9a5d13ca (it only has github->gitea code in it right now but you swap out github lib for gitlab lib)

**Comment by ascandella** [comment]
Do the scripts you link also provision users, repo attributes like web hooks, other (2fa?)

Basically my ideal tool takes a running gitlab and a clean install gitea and makes the gitea as close to the gitlab configuration as possible. Passwords may need to be reset, but other than that all my deploy keys are there, my hooks, my repos owned properly by me

**Comment by techknowlogick** [comment]
I'm not sure about the first link (there has been a lot of development on it since I last looked), but the second link (my gist) only does the equivalent of a `git clone`

**Comment by ascandella** [comment]
Cool, I will close this for now and try out the existing solutions, and report back if I come up with something better
