### ISSUE TITLE
APP_NAME doesn't support accents/diacritics, and may stop gitea

### ISSUE THREAD

**Issue by danilogalisteu** [go-gitea/gitea#4830]
- Gitea version (or commit ref): 1.5.0
- Git version: 2.18.0
- Operating system: Win 2008 (server), Win7 (client)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

I added a word with an accent to APP_NAME ("Repositório"), and it was not shown correctly in the web interface, as in the screenshot below. Then I changed the "app.ini" coding from ANSI to Unicode, and the gitea service would not start. Finally, I changed the coding to UTF-8, and the name was shown as expected. "app.ini" was edited with Windows' Notepad.

## Screenshots

![app_name](https://user-images.githubusercontent.com/10237982/44871549-7d633f80-ac69-11e8-9876-c38854f3ad65.png)

**Comment by lafriks** [comment]
Only UTF-8 is supported and I don't see need to change that.
ASCII is charset dependant and can not be guessed automatically.

**Comment by danilogalisteu** [comment]
I understand, although I wouldn't have expected it to fail with such a simple input.
Is this or should this be documented somewhere? I couldn't find anything related in issues or docs.
Thanks anyway for the feedback!
