### ISSUE TITLE
Gitea API - Cannot add comment to PR when using external issue tracker

### ISSUE THREAD

**Issue by chanhlt** [go-gitea/gitea#4832]
- Gitea version (or commit ref):
- Git version: 1.5.0
- Operating system: Debian 9
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL): https://try.gitea.io/chanhlt/test-repo/pulls/1
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

When I try to use API to add comment to a pull request.
It works perfectly if I use built-in issue tracker.
However, when I change to use an external one like Redmine.
I cannot use the API anymore.
I get 404 error.

## Screenshots
Using built-in issue tracker
![](https://image.ibb.co/nhMAUe/Screen_Shot_2018_08_31_at_14_31_44.png)

Using external issue tracker

![](https://image.ibb.co/dNeavK/Screen_Shot_2018_08_31_at_14_22_36.png)

**Comment by lunny** [comment]
Which API did you use to add comment?
