### ISSUE TITLE
Repo shows up as bare after migrating from svn

### ISSUE THREAD

**Issue by kolaente** [go-gitea/gitea#4833]
- Gitea version (or commit ref): b9ae16d
- Git version: 2.1.4
- Operating system: Debian 8
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant

## Description

After migrating an old svn repo following the guide [here](https://git-scm.com/book/en/v2/Git-and-Other-Systems-Migrating-to-Git), the repo still shows up as bare in the ui, meaning it only shows instructions on how to initialize it instead of showing the code. The code is in the repo, when I clone the repo manually I get all the code.
When I commit & push a test file manually after this, the UI acts normal.

**Comment by lafriks** [comment]
Did you see any errors in gitea.log?

**Comment by lunny** [comment]
I think this maybe unrelated with gitea if svn to git is not right. @kolaente

**Comment by rkCSD** [comment]
@lafriks @kolaente 
Here are some errors which may be related to the issue:

### http.log
`2018/08/31 21:41:33 [...routers/repo/http.go:391 serviceRPC()] [E] fail to serve RPC(upload-pack): exit status 141 - {[101 114 114 111 114 58 32 103 105 116 45 117 112 108 111 97 100 45 112 97 99 107 32 `

### serv.log
```
2018/08/31 10:04:41 [...io/gitea/cmd/serv.go:181 runServ()] [F] Repository does not exist: rkcsd/tex
2018/08/31 10:04:42 [...io/gitea/cmd/serv.go:181 runServ()] [F] Repository does not exist: rkcsd/tex
2018/08/31 13:18:32 [...io/gitea/cmd/serv.go:263 runServ()] [F] User konrad does not have level write access to repository rkcsd/flyspray.git
2018/08/31 13:18:33 [...io/gitea/cmd/serv.go:263 runServ()] [F] User konrad does not have level write access to repository rkcsd/flyspray.git
2018/08/31 13:18:34 [...io/gitea/cmd/serv.go:263 runServ()] [F] User konrad does not have level write access to repository rkcsd/flyspray.git
2018/08/31 13:18:35 [...io/gitea/cmd/serv.go:263 runServ()] [F] User konrad does not have level write access to repository rkcsd/flyspray.git
2018/08/31 13:18:36 [...io/gitea/cmd/serv.go:263 runServ()] [F] User konrad does not have level write access to repository rkcsd/flyspray.git
2018/08/31 13:18:37 [...io/gitea/cmd/serv.go:263 runServ()] [F] User konrad does not have level write access to repository rkcsd/flyspray.git
2018/08/31 13:18:38 [...io/gitea/cmd/serv.go:263 runServ()] [F] User konrad does not have level write access to repository rkcsd/flyspray.git
```

(@kolaente asked me to scan the log files for it, cause the instance we're talking about, here, is running on a server managed by me; @kolaente has no access to the log files)

**Comment by kolaente** [comment]
I think it should not even show me the repo when I don't have access. But it'd be interesting to know where these `Repository does not exist: rkcsd/tex` errors come from.

**Comment by kolaente** [comment]
@lunny He is the admin of the instance where the issue occurred, which is why he has access to the logs and I don't.

**Comment by lunny** [comment]
Maybe it's your username is `rkCSD` on gitea but you clone via `rkcsd`?
