### ISSUE TITLE
Use local fonts instead of Google Fonts

### ISSUE THREAD

**Issue by theel0ja** [go-gitea/gitea#4837]
<img width="243" alt="screen shot 2018-08-31 at 22 32 25" src="https://user-images.githubusercontent.com/5832930/44932355-c3093080-ad6d-11e8-8e67-fb4bc200eae2.png">

You can download Google Fonts here: https://google-webfonts-helper.herokuapp.com/fonts

**Comment by 6543** [comment]
+1
