### ISSUE TITLE
Load Fonts is to slow

### ISSUE THREAD

**Issue by kekxv** [go-gitea/gitea#4839]
Load Fonts is to slow ，Maybe it can be removed or changed to local.
url：
https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic&subset=latin

**Comment by ghost** [comment]
If not changed to local and served with the site they can block the page. Also China blocks some Google domains which could cause 10s page loads depending on browser and location—even outside CN in AsiaPac.

**Comment by ghost** [comment]
Related #4837
