### ISSUE TITLE
Formatting issues in Admin Config

### ISSUE THREAD

**Issue by explorigin** [go-gitea/gitea#484]
- Gitea version (or commit ref): 1.0
- Git version: N/A
- Operating system: Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io: No, don't have admin access
## Description
See attached screenshots of Admin Panel -> Configuration.  Text is overflowing containers. These formatting issues happen in both Firefox and Chrome.

<img width="892" alt="image" src="https://cloud.githubusercontent.com/assets/697818/21486593/98434a90-cb7c-11e6-8cae-1f98bac352d1.png">

<img width="572" alt="image" src="https://cloud.githubusercontent.com/assets/697818/21486571/32372500-cb7c-11e6-86a9-a99f9c6cc07e.png">

**Comment by issmirnov** [comment]
+1

 Admin -> Configuration -> session configuration is missing a data row.

**Comment by lunny** [comment]
@issmirnov your problem is the same as this one? if not, could you please fire another issue so we can resolve them one by one.

**Comment by issmirnov** [comment]
@lunny sure, filed #517

**Comment by lunny** [comment]
@issmirnov Thanks!
