### ISSUE TITLE
Unable to use arc-green using styles.css

### ISSUE THREAD

**Issue by eloo** [go-gitea/gitea#4843]
- Gitea version (or commit ref): 1.5.0
- Git version:     2.11.0
- Operating system: Debian 9
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
I'm trying to use the darkmode (arc-green) in my fresh installation by placing the files from gitea-darkmode inside my gitea directory but it doesn't work.
Maybe i missed something in the steps. 
I have simply placed the files in my gitea directory:    
Static File Root Path:    /var/lib/gitea

and this looks like
.
├── custom
├── data [error opening dir]
├── gitea.pid
├── indexers [error opening dir]
├── log [error opening dir]
├── public
│   └── styles.css
└── templates
    └── custom
        └── header.tmpl

So did i miss something?

Thx for your help

**Comment by ghost** [comment]
To use the dark theme modify `app.ini` as specified in [Customizing the look of Gitea](https://docs.gitea.io/en-us/customizing-gitea/#customizing-the-look-of-gitea) then restart Gitea.

**Comment by techknowlogick** [comment]
@jhabdas the dark theme is not in version 1.5.0 of Gitea, it will be released when 1.6.0 is released.

Edit: From reading the ticket it sounds like @eloo is using https://github.com/go-gitea/gitea-darkmode

**Comment by eloo** [comment]
@techknowlogick yes exactly.. i was trying to add the darkmode using the instructions from gitea-darkmode

**Comment by lafriks** [comment]
For questions please use gitea forum

**Comment by gerroon** [comment]
Why is this in the documentation if it is not in the release? I cant even find 1.6 to download

https://docs.gitea.io/en-us/customizing-gitea/

I have been trying to add this arc-green thing for a while :(


EDIT: Ok the latest nightly from 9/10/2018 works. This must be added just now, because my version was not older than 1 week. Good job, thanks for the addition.

**Comment by lafriks** [comment]
Because we don't currently have versioned documentation
