### ISSUE TITLE
Error 500 on wiki from a mirrored migrated repo

### ISSUE THREAD

**Issue by explorigin** [go-gitea/gitea#485]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite

Whatever is on try.gitea.io ^^^^^^^^^

- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)  https://try.gitea.io/tim_thecookiejar.me/gallery/wiki
  - [ ] No
  - [ ] Not relevant
- Log gist:
```
[...routers/repo/wiki.go:56 renderWikiPage()] [E] GetBranchCommit: object does not exist [id: refs/heads/master, rel_path: ]
```
## Description

Error 500 on wiki from a mirrored migrated repo. https://try.gitea.io/tim_thecookiejar.me/gallery/wiki

**Comment by lunny** [comment]
Hi, I cannot reproduce that. This is my test repo: https://try.gitea.io/lunny/builder. It's OKay. Any further information?

**Comment by lunny** [comment]
I will test it more.

**Comment by lunny** [comment]
Maybe a mirrored repo should not have a wiki project?
