### ISSUE TITLE
Images broken / shows half

### ISSUE THREAD

**Issue by madscientista** [go-gitea/gitea#4850]
- Gitea version (or commit ref): 1.5.0
- Git version: 2.18.0
- Operating system: Debian 9
- Database (use `[x]`):
  - [X ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X ] No
  - [ ] Not relevant
- Log gist: 

## Description

Avatar shows half, so does images.

## Screenshots

https://s33.postimg.cc/yjexx5olr/Screenshot_20180902-144546.jpg

**Comment by lunny** [comment]
I think that's because your network is slow.

**Comment by SagePtr** [comment]
In my Google Chrome your server does not even open, ERR_SSL_VERSION_OR_CIPHER_MISMATCH.
Works on Mozilla Firefox only. 
[SSLLabs report](https://www.ssllabs.com/ssltest/analyze.html?d=bugs.moedesu.ga) some browsers don't support it's cipher. Maybe it's unrelated to partially broken images, but your nginx looks bad confirured. Try to open repo directly without reverse proxy and if there is no bug (if avatar file on disk was uploaded partially - try to reupload it again) - then it looks like nginx problem.
