### ISSUE TITLE
Cannot install *stable* Gitea snap

### ISSUE THREAD

**Issue by lofidevops** [go-gitea/gitea#4869]
- Gitea version (or commit ref): Any
- Git version: Any
- Operating system: Debian-based
- Database (use `[x]`): N/A
- Can you reproduce the bug at https://try.gitea.io: N/A
- Log gist: N/A

## Steps to reproduce

* Visit Snap store website
* Search for Gitea

## What should happen?

* Can install from command line with `snap install gitea`

## What happens instead?

* Can only install with `snap install gitea --edge`, which matches the development branch, not the stable branch

## Related links

#2539
#4026 

Relevant-looking discussion from #4026 :

> @lafriks: Also we do not tag on master branch but on release/v1.x branches, will that work?
>
> @popey You certainly could build from any tag, as you can use a scriptlet (as I indicated) to do whatever git magic you want to grab the right source revision / tag and build it.
>
> @lafriks: I can not seem to find a way to trigger building other than master branch from their build system. As much as I understand we would have to build our own snap package and upload to their store to get that. But for that we need drone support for that

**Comment by anicolaides** [comment]
I can confirm that the only channel available is edge.

**Comment by lafriks** [comment]
Unless someone builds drone plugin for this I don't see way to fix this currently

**Comment by 6543** [comment]
@lofidevops still the case?

**Comment by techknowlogick** [comment]
Closing a we now publish a stable version
