### ISSUE TITLE
Offline mode still trying to load css from googleapis

### ISSUE THREAD

**Issue by LarrysGIT** [go-gitea/gitea#4871]
- Gitea version (or commit ref): master
- Git version: N/A
- Operating system: N/A
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
Offline mode set to "true", still trying to load css from fonts.googleapis.com, which causes slowness in a network isolated environment (no internet access).
<link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700|Source+Code+Pro:300,600|Titillium+Web:400,600,700" rel="stylesheet">

## Screenshots
![image](https://user-images.githubusercontent.com/7692156/45065352-052ecb00-b0fc-11e8-88a4-2c38008949fb.png)

**Comment by techknowlogick** [comment]
Thank you for your report @LarrysGIT. This issue is currently being tracked in #4837
