### ISSUE TITLE
Error: Resource temporarily unavailable

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#4873]
- Gitea Version: 1.5.1 (Go1.10.1)
- Operating system: Client: Ubuntu 14.4; Server: Windows
- Git version: 2.18.0
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description

When issueing (seemingly expensive) git commands like `git subtree push` and `git submodule add`, I am seeing following errors (complete output), respectively:

    git push using:  https://server/orga/TestApps.git master
    Enumerating objects: 1183, done.
    Counting objects: 100% (1183/1183), done.
    Delta compression using up to 4 threads.
    Compressing objects: 100% (636/636), done.
    Writing objects: 100% (1183/1183), 9.70 MiB | 1.04 MiB/s, done.
    Total 1183 (delta 678), reused 846 (delta 524)
    remote: Resolving deltas: 100% (678/678), done.
    remote:       1 [main] bash 5740 fork: child -1 - forked process 2976 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
    remote: hooks/pre-receive: fork: retry: Resource temporarily unavailable
    remote: 1278874 [main] bash 5740 fork: child -1 - forked process 316 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
    remote: hooks/pre-receive: fork: retry: Resource temporarily unavailable
    remote: 3486808 [main] bash 5740 fork: child -1 - forked process 5524 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
    remote: hooks/pre-receive: fork: retry: Resource temporarily unavailable
    remote: 7674766 [main] bash 5740 fork: child -1 - forked process 4612 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
    remote: hooks/pre-receive: fork: retry: Resource temporarily unavailable
    remote: 16643732 [main] bash 5740 fork: child -1 - forked process 4512 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
    remote: hooks/pre-receive: fork: Resource temporarily unavailable
    To https://server/orga/TestApps.git
     ! [remote rejected]     a14e8311b774f168351486aaa666aadd07bab129 -> master (pre-receive hook declined)
    error: failed to push some refs to 'https://server/orga/TestApps.git'
    #Return code: 1

and

    Cloning into '/data/workdir/git/repo'...
    remote: Enumerating objects: 20, done.
    remote: Counting objects: 100% (20/20), done.
    remote: Compressing objects: 100% (20/20), done.
    remote: Total 20 (delta 5), reused 0 (delta 0)
    Unpacking objects: 100% (20/20), done.
    [master 0d53eaf] Added submodule repo
     2 files changed, 4 insertions(+)
     create mode 160000 repo
    Enumerating objects: 5, done.
    Counting objects: 100% (5/5), done.
    Delta compression using up to 4 threads.
    Compressing objects: 100% (3/3), done.
    Writing objects: 100% (3/3), 429 bytes | 429.00 KiB/s, done.
    Total 3 (delta 1), reused 0 (delta 0)
    remote:       1 [main] bash 1576 fork: child -1 - forked process 4304 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
    remote: ./hooks/update.d/gitea: fork: retry: Resource temporarily unavailable
    remote: 1077096 [main] bash 1576 fork: child -1 - forked process 3420 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
    remote: ./hooks/update.d/gitea: fork: retry: Resource temporarily unavailable
    remote: 3267889 [main] bash 1576 fork: child -1 - forked process 5884 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
    remote: ./hooks/update.d/gitea: fork: retry: Resource temporarily unavailable
    remote: 7526358 [main] bash 1576 fork: child -1 - forked process 5424 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
    remote: ./hooks/update.d/gitea: fork: retry: Resource temporarily unavailable
    remote: 15650635 [main] bash 1576 fork: child -1 - forked process 4000 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
    remote: ./hooks/update.d/gitea: fork: Resource temporarily unavailable
    remote: error: hook declined to update refs/heads/master
    To https://server/orga2/repo2
     ! [remote rejected] master -> master (hook declined)
    error: failed to push some refs to 'https://server/orga2/repo2'
    #Return code: 1

For the latter error message I found `./hooks/update.d/gitea` on my server. So it seems to be a problem on the server side. Agreed?

Content of `./hooks/update.d/gitea`:

    #!/usr/bin/env bash
    "D:/Bin/Gitea/gitea-1.5.1-windows-4.0-amd64.exe" hook --config='D:/Bin/Gitea/custom/conf/app.ini' update $1 $2 $3 

This [SO entry](https://stackoverflow.com/questions/12079087/fork-retry-resource-temporarily-unavailable#12079684) suggests to increase the number of available file descriptors. How would this be possible on a Windows machine? Is there a configuration option for Gitea?

Note: This is a temporary problem. When issueing the same command again, the problem usually does not occur again.

Note2: The server has only limited resources. Which type of resource would I need to increase?

**Comment by varunsridharan** [comment]
I am facing the same issue but this happens random when opening the website !!

**Comment by techknowlogick** [comment]
Please don’t comment on closed issues, your report will be lost. Instead please open a new issue and fill out the issue template completely
