### ISSUE TITLE
Enhancement: Hide user setting "SSH / GPG Keys" if SSH disabled

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#4874]
- Gitea Version: 1.5.1 (Go1.10.1)
- Operating system: Client: Ubuntu 14.4; Server: Windows
- Git version: 2.18.0
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description

If the administrator disabled SSH globally (`DISABLE_SSH=true`), I'd expect that users cannot [configure personal SSH certificates](https://localhost:3000/user/settings/keys)

Would it be feasible to hide this tab from the user settings page?

**Comment by adelowo** [comment]
That page has more than ssh, you can also configure GPG keys there annd from the looks of it, that button is already disabled 

![screen shot 2018-09-05 at 23 06 40](https://user-images.githubusercontent.com/12677701/45124054-d8f96580-b160-11e8-8126-32f0be84e2e0.png)
