### ISSUE TITLE
Add the ability to disable Wiki & Issues from API

### ISSUE THREAD

**Issue by deanpcmad** [go-gitea/gitea#488]
I've recently moved to Gitea from GitLab. I wrote a script to extract the GitLab backup, create repos using the Gitea API and then push the contents of those repos.

For a number of my projects I want to use an external issue tracker so it would be nice to be able to disable or set the external issue tracker URL and URL format from the API on creation and when updating a project.

Thanks for your hard work on Gitea so far, I'm really liking it 😄

**Comment by lunny** [comment]
Is there a github API to do this?

**Comment by bkcsoft** [comment]
@lunny Yes. https://developer.github.com/v3/repos/#edit

```
PATCH /repos/:owner/:repo
{
  has_wiki: false,
  has_issues: false
}
```

**Comment by adelowo** [comment]
Bummer

**Comment by davidsvantesson** [comment]
This issue have been implemented.
