### ISSUE TITLE
Missing Migration-- Error 1054: Unknown column 'ref' in 'field list'

### ISSUE THREAD

**Issue by psywhale** [go-gitea/gitea#4882]
- Gitea version (or commit ref): bd1bf2a0720b771cfe2fac3fef0fd9edd68f6317
- Git version: 2.7.4 
- Operating system: ubuntu bionic
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x ] Not relevant
- Log gist:

## Description

missing migration.. 

2018/09/06 11:09:42 [I] Migration: add is_fsck_enabled column for repos
2018/09/06 11:09:42 [I] Migration: add size column for attachments
2018/09/06 11:09:42 [I] Migration: add last used passcode column for TOTP
2018/09/06 11:09:42 [I] Migration: add language column for user setting
2018/09/06 11:09:42 [I] Migration: add multiple assignees
2018/09/06 11:09:43 [...itea/routers/init.go:60 GlobalInit()] [E] Failed to initialize ORM engine: migrate: do migrate: Error 1054: Unknown column 'ref' in 'field list'

**Comment by techknowlogick** [comment]
@psywhale which version did you upgrade from?

**Comment by psywhale** [comment]
1.0.2 -> 1.5 -> master

**Comment by psywhale** [comment]
1.5 also had a migration error with "is_fsck_enabled" column missing but master fixed that.

**Comment by psywhale** [comment]
I am trying to migrate from gogs and the documentation said to use a 1.0.X version. Which worked great. Then I tried to upgrade to 1.5 and got migration errors

**Comment by psywhale** [comment]
something to do with this? https://github.com/go-gitea/gitea/blob/e95417ea2c0d9b5e0be0c0f7bf82eabb40919c33/models/migrations/v64.go#L29

**Comment by psywhale** [comment]
my issue table as it now stands:


mysql> describe issue;
+---------------+--------------+------+-----+---------+----------------+
| Field         | Type         | Null | Key | Default | Extra          |
+---------------+--------------+------+-----+---------+----------------+
| id            | bigint(20)   | NO   | PRI | NULL    | auto_increment |
| repo_id       | bigint(20)   | YES  |     | NULL    |                |
| index         | bigint(20)   | YES  |     | NULL    |                |
| poster_id     | bigint(20)   | YES  |     | NULL    |                |
| name          | varchar(255) | YES  |     | NULL    |                |
| content       | text         | YES  |     | NULL    |                |
| milestone_id  | bigint(20)   | YES  |     | NULL    |                |
| priority      | int(11)      | YES  |     | NULL    |                |
| assignee_id   | bigint(20)   | YES  |     | NULL    |                |
| is_closed     | tinyint(1)   | YES  |     | NULL    |                |
| is_pull       | tinyint(1)   | YES  |     | NULL    |                |
| num_comments  | int(11)      | YES  |     | NULL    |                |
| deadline_unix | bigint(20)   | YES  |     | NULL    |                |
| created_unix  | bigint(20)   | YES  |     | NULL    |                |
| updated_unix  | bigint(20)   | YES  |     | NULL    |                |
| closed_unix   | bigint(20)   | YES  | MUL | NULL    |                |
+---------------+--------------+------+-----+---------+----------------+

**Comment by psywhale** [comment]
alter table issue add column ref varchar(255) after num_comments;

fixed this issue but now another migration error see #4883
