### ISSUE TITLE
Migration Issue: missing issue_watch table

### ISSUE THREAD

**Issue by psywhale** [go-gitea/gitea#4883]
- Gitea version (or commit ref): bd1bf2a0720b771cfe2fac3fef0fd9edd68f6317
- Git version: 2
- Operating system: ubuntu
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
After issue #4882  now another migration issue

2018/09/06 12:21:34 [I] Log Mode: File(Info)
2018/09/06 12:21:34 [I] XORM Log Mode: File(Info)
2018/09/06 12:21:34 [I] Cache Service Enabled
2018/09/06 12:21:34 [I] Session Service Enabled
2018/09/06 12:21:34 [I] Mail Service Enabled
2018/09/06 12:21:34 [I] Register Mail Service Enabled
2018/09/06 12:21:34 [I] Notify Mail Service Enabled
2018/09/06 12:21:34 [I] Migration: remove stale watches
2018/09/06 12:21:34 [...itea/routers/init.go:60 GlobalInit()] [E] Failed to initialize ORM engine: migrate: do migrate: Error 1146: Table 'gogs.issue_watch' doesn't exist

**Comment by lafriks** [comment]
Closing this as not really gitea bug but bad migration from gogs
