### ISSUE TITLE
Profile language not respected after launching the browser

### ISSUE THREAD

**Issue by OndrejSpanel** [go-gitea/gitea#4884]
- Gitea version (or commit ref): bd1bf2a
- Git version: N/A
- Operating system: N/A
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes (provide example URL) - https://try.gitea.io/
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

Whenever I go to the gitea web page after launching the browser, my language switches back to Czech (which is my preferred browser content language). I have however chosen English as my Gitea UI language. I need to go to my user profile, I see the English is already selected there and I have to press "Změnit profil" (which is Update Profile translated to Czech) to really have Gitea in English.

## Screenshots
![image](https://user-images.githubusercontent.com/6927223/45182737-736dad80-b222-11e8-9d28-00d227608958.png)

**Comment by OndrejSpanel** [comment]
To prevent any misunderstanding: I do not want Gitea shown in my browser language. I want it shown in English, but it currently shows in Czech until I press Změnit profil (Update profile) each time I visiting Gitea first time after starting the browser,, in spite of me selecting English in the Gitea profile.

I think this might be because Czech is my preferred browsing language (Google Chrome settings / Advanced / Languages / Order languages based on your preference), because I do not know where would Gitea get Czech from otherwise, but this is just my guess.

**Comment by SagePtr** [comment]
Probably gitea should not respect anything other than profile language if user is signed in - in this case language should be taken from user profile, not from cookie. If user switches language via bottom language selector - if he is signed in - this should change profile language, if not - this should change cookie. In other words, cookie should be respected only for guest user.

And also global configuration option for default language would be nice. If not set - autodetect by browser Accept-Language header, like now. If set - gitea should use it for guest users and new user profiles instead of guessing it.

**Comment by OndrejSpanel** [comment]
I did not notice the  bottom language selector before at all. Once I changed that to English, it no longer shows me Czech at all, even after restarting the browser.

I agree once signed in the profile preference should be respected. Otherwise it might be less confusing to remove the profile preference completely and use only the bottom selector.

**Comment by Monter** [comment]
Up. Still not solved. Please consider Gitea start (for unregistered users) always in English, which is universal, and then everyone can change language or log in and then the change would take place according to the profile settings.

**Comment by nferrari** [comment]
Hi,

Let's confirm once more this issue is still ongoing.

> I did not notice the bottom language selector before at all. Once I changed that to English, it no longer shows me Czech at all, even after restarting the browser.

That does NOT work for me. I need to set back the language to English **everytime** I go back to my Gitea instance if the browser has been restarted, even if I'm logged and my language setting is set to English.

**Comment by bastien-solutions** [comment]
Just to confirm, I still have the issue in v1.13.4

**Comment by theonlynexus** [comment]
Issue still present in v1.15.0
