### ISSUE TITLE
User not Sync with Active Directory

### ISSUE THREAD

**Issue by vbose1** [go-gitea/gitea#4889]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

...

## Screenshots

![image](https://user-images.githubusercontent.com/34274349/45218111-0b6fa380-b2c4-11e8-9006-c7efc44eb5ed.png)
![image](https://user-images.githubusercontent.com/34274349/45218142-293d0880-b2c4-11e8-8664-3583893ca056.png)

I use above configuration to fetch AD users.
And I also update the app.ini to sync user on every hour
[cron.sync_external_users]
RUN_AT_START = true
SCHEDULE = @every 1h
UPDATE_EXISTING = true

It's run every hour and not display any error in log. But did not fetch any user.

**Comment by lafriks** [comment]
Please see docs page on what enter on each fields. User filter seems incorrect, same as email attribute. Also it is recommended that first and last name attributes are provided

**Comment by vbose1** [comment]
@lafriks after apply as you mention fields I getting these log

2018/09/09 23:39:10 [T] Doing: SyncExternalUsers

2018/09/09 23:39:10 [T] Doing: SyncExternalUsers[New AD]

2018/09/09 23:39:10 [T] Dialing LDAP with security protocol (0) without verifying: false

2018/09/09 23:39:10 [T] Bound as BindDN CN=Vishwajeet Bose,OU=xxx,DC=CCSI,DC=local

2018/09/09 23:39:10 [T] Fetching attributes 'sAMAccountName', 'name', 'name', 'proxyAddresses', '' with filter (&(objectCategory=Person)(sAMAccountName=*)) and base CN=*,OU=xxx,DC=CCSI,DC=local

2018/09/09 23:39:10 [...gitea/models/user.go:1536 SyncExternalUsers()] [E] LDAP Search failed unexpectedly! (LDAP Result Code 32 "No Such Object": 0000208D: NameErr: DSID-03100238, problem 2001 (NO_OBJECT), data 0, best match of:
	'OU=xxx,DC=CCSI,DC=local'
 )

still not getting users from AD

**Comment by lafriks** [comment]
Please screenshot again your values

**Comment by vbose1** [comment]
![image](https://user-images.githubusercontent.com/34274349/45344970-a1f0dd00-b5c2-11e8-9562-4670b9f179f8.png)
![image](https://user-images.githubusercontent.com/34274349/45344987-b03ef900-b5c2-11e8-9a01-deb0720928fe.png)
