### ISSUE TITLE
Markdown Link Limitation

### ISSUE THREAD

**Issue by mwaeckerlin** [go-gitea/gitea#4891]
- Gitea version (or commit ref): 05abd03
- Git version: 2.15.0
- Operating system: Alpine Linux v3.7
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL 5.7
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes https://try.gitea.io/mrw/test in README.md
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

In Markdown, you can mark links in a text and list them at the end.

Gitea does not provide this possibility, so I open this feature request.

## Screenshots

![grafik](https://user-images.githubusercontent.com/4056726/45232097-8f2e8d80-b2ce-11e8-942d-912917871bf5.png)

## Example

Example from https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#links

```
[You can use numbers for reference-style link definitions][1]

Or leave it empty and use the [link text itself].

URLs and URLs in angle brackets will automatically get turned into links. 
http://www.example.com or <http://www.example.com> and sometimes 
example.com (but not on Github, for example).

Some text to show that the reference links can follow later.

[arbitrary case-insensitive reference text]: https://www.mozilla.org
[1]: http://slashdot.org
[link text itself]: http://www.reddit.com
```

This should render like this:

[You can use numbers for reference-style link definitions][1]

Or leave it empty and use the [link text itself].

URLs and URLs in angle brackets will automatically get turned into links. 
http://www.example.com or <http://www.example.com> and sometimes 
example.com (but not on Github, for example).

Some text to show that the reference links can follow later.

[arbitrary case-insensitive reference text]: https://www.mozilla.org
[1]: http://slashdot.org
[link text itself]: http://www.reddit.com

**Comment by Eisfunke** [comment]
This is probably an issue of [blackfriday](https://github.com/russross/blackfriday), the Markdown library Gitea uses, rather than Gitea itself.

**Comment by mwaeckerlin** [comment]
> This is probably an issue of [blackfriday](https://github.com/russross/blackfriday), the Markdown library Gitea uses, rather than Gitea itself.

Thank you for the hint. It seems, that it exists as extension in blackfriday, but must be enabled. When I was looking for existing tickets there. I found: https://github.com/russross/blackfriday/issues/447

So: Could you please enable all the nice extensions available in blackfriday?

**Comment by mwaeckerlin** [comment]
… and I suggest to document the supported and non supported markdown features of gitea. At least, I didn't find any documentation on this.

**Comment by mwaeckerlin** [comment]
@Eisfunke ping

**Comment by andrewdunndev** [comment]
I'll second a request for the footnotes extension.

**Comment by mwaeckerlin** [comment]
Please check blackfriday configuration and please check my message above, @Eisfunke,  @lafriks or anyone else…

**Comment by Eisfunke** [comment]
I'm not really the person to ask, sorry. I just happened to know what markup parser Gitea uses from a different tiny thing I worked on here.

**Comment by mwaeckerlin** [comment]
@Eisfunke, any Idea who could take care about this? The ticket is now lying around since several months and no one cares. As it seems, the feature is available in the library, but not used in gitea.

**Comment by zeripath** [comment]
Hi! We're very open to PRs.

The main issue is that we're currently hunting down bugs so our time to do additional features is limited. If you can either make a pr or explain very clearly what it is we need to do to enable this feature  we should be able to add this.

**Comment by mwaeckerlin** [comment]
@zeripath, I agree that bug fixing has higher priority. As far as I understand according to the docs: There is this feature in blackfriday (as described above), that is not available in gitea. So I suppose the solution is something like either enable the feature (if it needs configuration) or update blackfriday.

I am already happy, if the stale-bot does not close the ticket before it is done.

**Comment by Cherrg** [comment]
feature was enabled by #6362, i think this could be closed
