### ISSUE TITLE
api shows wrong email address

### ISSUE THREAD

**Issue by ryanburnette** [go-gitea/gitea#4899]
- Gitea version (or commit ref): 1.5.1
- Git version:
- Operating system: linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

The API shows my email address as ryanburnette@code.ryanburnette.com, but I changed it in my profile. Is this an error?

```json
[
    {
        "id": 37,
        "url": "https://code.ryanburnette.com/api/v1/repos/ryanburnette/decently-smart-target/issues/1",
        "number": 1,
        "user": {
            "id": 1,
            "login": "ryanburnette",
            "full_name": "Ryan Burnette",
            "email": "ryanburnette@code.ryanburnette.com",
            "avatar_url": "https://secure.gravatar.com/avatar/80ca3efd5f4440f4f7103e0a3ad932bb?d=identicon",
            "language": "en-US",
            "username": "ryanburnette"
        },
        "title": "Test",
        "body": "This is a test issue.",
        "labels": [],
        "milestone": null,
        "assignee": null,
        "assignees": null,
        "state": "closed",
        "comments": 0,
        "created_at": "2018-09-09T15:55:11Z",
        "updated_at": "2018-09-09T15:55:47Z",
        "closed_at": null,
        "due_date": null,
        "pull_request": null
    }
]
```

**Comment by adelowo** [comment]
I couldn’t replicate this though... Are there more steps to take than just updating the email address?

**Comment by ryanburnette** [comment]
@adelowo  You got the correct email address in the API response?

**Comment by adelowo** [comment]
Yes, I did...  I got the correct email in the "issue created" webhook

**Comment by ryanburnette** [comment]
Hmm. Maybe try changing your email then see if you get the old one.

**Comment by ryanburnette** [comment]
@adelowo My apologies for the suggestion. This is an issue on my instance... so some set of circumstances lead to it.
