### ISSUE TITLE
Release page loads slow with a lot of tags

### ISSUE THREAD

**Issue by deanpcmad** [go-gitea/gitea#490]
Copied from https://github.com/gogits/gogs/issues/3094

- Gitea version (or commit ref): 1.0
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

I've just created a mirror repository for the rails repo and upon viewing the "Releases" tab, it takes forever to load, sometimes not loading at all which can cause nginx to timeout

Please see #491 as well

**Comment by bkcsoft** [comment]
not an enhancement, it's a bug. I added release pagniation a while back but I seem to have missed this for-loop here that _still_ loop over _all_ tags 😒 https://github.com/go-gitea/gitea/blob/master/routers/repo/release.go#L77

**Comment by bkcsoft** [comment]
Just flipping that for-loop around and using `ctx.Repo.GitRepo.GetTag(r.TagName)` should make it _way_ faster, and TBH we probably don't need the caching anymore since we're not fetching _all_ tags in one go :)

**Comment by deanpcmad** [comment]
Yeah I saw there is pagination so I did wonder why it was slow, that explains it :)

**Comment by JetpackDuba** [comment]
Will you fix it for 1.0.1 or only 1.1? Imo it should be in both :P

**Comment by lunny** [comment]
@deanpcmad, could you please test if #527 resolved your problem since I think there are also some improvements should be taken in future.

**Comment by deanpcmad** [comment]
@lunny sure, is there a build for it?

**Comment by lunny** [comment]
https://dl.gitea.io/gitea/master/, you can find your proper version.

**Comment by bkcsoft** [comment]
@aeab13 personally this isn't a bug and should only go into 1.1, but others can of course over-rule me 😉

**Comment by JetpackDuba** [comment]
I'm not who opened the issue but in my case using Windows 10 and MSSQL, I've cloned VS CODE github repo and tags page takes 8.8 seconds to load :S

**Comment by deanpcmad** [comment]
Hey, I've just tried it (version 09dabe2) but it is still very slow to load the tags page. If you want to test it yourself locally, mirror the https://github.com/rails/rails repo

**Comment by JetpackDuba** [comment]
Now it loads in 1sec! That's better!

**Comment by lunny** [comment]
Yes. But it's not perfect. It needs further improvement later.

**Comment by lunny** [comment]
On macOS and sqlite, rails still spent 10s.

**Comment by lunny** [comment]
https://try.gitea.io/lunny/rails/releases. v1.2+ have resolve this issue entirely.
