### ISSUE TITLE
Unable to assign topics to repos

### ISSUE THREAD

**Issue by Xdeposh** [go-gitea/gitea#4903]
- Gitea version (or commit ref): 1.5.1
- Git version: 2.18.0
- Operating system: Windows 10
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
I am unable to assign any topic to any repo. I get the current message
`Topics must start with a letter or number, can include hyphens(-) and must be no more than 35 characters long`

## Screenshots

![capture](https://user-images.githubusercontent.com/9025171/45312618-d5812800-b52c-11e8-809c-2992d3f09abc.PNG)

**Comment by techknowlogick** [comment]
@Xdeposh are you able to add the topic "`test`"? and just that? In addition to the help text in your screenshot, topics can't have spaces.

**Comment by Xdeposh** [comment]
Well, I am just stupid.. Yes, without space I can add topics. Thanks for the help :D
