### ISSUE TITLE
Failed to initialize ORM engine

### ISSUE THREAD

**Issue by Madmorgan007** [go-gitea/gitea#4904]
- Gitea version (or commit ref): 8ee9922fe68531a47ce6ba8eefaf146a0a78549c 
- Git version:
- Operating system: Debian on Raspberry Pi
- Database (use `[x]`):
  - [x ] MySQL

- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x ] Not relevant
- Log gist:

## Description
Hi,

I have just upgraded my version of Gitea to latest Master and I can not start my server.

Thanks

Here is part of the log.

2018/08/27 15:17:16 [I] Log Mode: File(Info)
2018/08/27 15:17:16 [I] XORM Log Mode: File(Info)
2018/08/27 15:17:16 [I] Cache Service Enabled
2018/08/27 15:17:16 [I] Session Service Enabled
2018/08/27 15:17:16 [...itea/routers/init.go:60 GlobalInit()] [E] Failed to initialize ORM engine: dial tcp 127.0.0.1:3306: getsockopt: connection refused
2018/08/27 15:17:17 [I] Log Mode: File(Info)
2018/08/27 15:17:17 [I] XORM Log Mode: File(Info)
2018/08/27 15:17:17 [I] Cache Service Enabled
2018/08/27 15:17:17 [I] Session Service Enabled
2018/08/27 15:17:20 [I] Git Version: 2.1.4
2018/08/27 15:17:21 [I] Run Mode: Production
2018/08/27 16:07:37 [I] Listen: http://0.0.0.0:3000
2018/08/27 16:07:37 [I] LFS server enabled
2018/09/10 19:24:43 [I] Log Mode: File(Info)
2018/09/10 19:24:43 [I] XORM Log Mode: File(Info)
2018/09/10 19:24:43 [I] Cache Service Enabled
2018/09/10 19:24:43 [I] Session Service Enabled
2018/09/10 19:24:43 [I] Migration: add label descriptions
2018/09/10 19:24:47 [I] Migration: add merge whitelist for protected branches
2018/09/10 19:24:50 [I] Migration: add is_fsck_enabled column for repos
2018/09/10 19:24:54 [I] Migration: add size column for attachments
2018/09/10 19:24:55 [I] Migration: add last used passcode column for TOTP
2018/09/10 19:25:03 [I] Migration: add language column for user setting
2018/09/10 19:25:04 [I] Migration: add multiple assignees
2018/09/10 19:25:07 [I] Migration: add u2f
2018/09/10 19:25:09 [I] Migration: add login source id column for public_key table
2018/09/10 19:25:11 [I] Migration: remove stale watches
2018/09/10 19:25:12 [I] Migration: Reformat and remove incorrect topics
2018/09/10 19:25:12 [I] This migration could take up to minutes, please be patient.
2018/09/10 19:25:12 [...itea/routers/init.go:60 GlobalInit()] [E] Failed to initialize ORM engine: migrate: do migrate: Sync2: Error 1071: Specified key was too long; max key length is 767 bytes

2018/09/10 19:25:13 [I] Log Mode: File(Info)
2018/09/10 19:25:14 [I] XORM Log Mode: File(Info)
2018/09/10 19:25:14 [I] Cache Service Enabled
2018/09/10 19:25:14 [I] Session Service Enabled
2018/09/10 19:25:14 [I] Migration: Reformat and remove incorrect topics
2018/09/10 19:25:14 [I] This migration could take up to minutes, please be patient.
2018/09/10 19:25:14 [...itea/routers/init.go:60 GlobalInit()] [E] Failed to initialize ORM engine: migrate: do migrate: Sync2: Error 1071: Specified key was too long; max key length is 767 bytes

2018/09/10 19:25:16 [I] Log Mode: File(Info)
2018/09/10 19:25:21 [I] XORM Log Mode: File(Info)
2018/09/10 19:25:21 [I] Cache Service Enabled
2018/09/10 19:25:21 [I] Session Service Enabled
2018/09/10 19:25:21 [I] Migration: Reformat and remove incorrect topics
2018/09/10 19:25:21 [I] This migration could take up to minutes, please be patient.
2018/09/10 19:25:29 [...itea/routers/init.go:60 GlobalInit()] [E] Failed to initialize ORM engine: migrate: do migrate: Sync2: Error 1071: Specified key was too long; max key length is 767 bytes

2018/09/10 19:25:35 [I] Log Mode: File(Info)
2018/09/10 19:25:35 [I] XORM Log Mode: File(Info)
2018/09/10 19:25:35 [I] Cache Service Enabled
2018/09/10 19:25:35 [I] Session Service Enabled
2018/09/10 19:25:35 [I] Migration: Reformat and remove incorrect topics
2018/09/10 19:25:35 [I] This migration could take up to minutes, please be patient.
2018/09/10 19:25:36 [...itea/routers/init.go:60 GlobalInit()] [E] Failed to initialize ORM engine: migrate: do migrate: Sync2: Error 1071: Specified key was too long; max key length is 767 bytes

2018/09/10 19:25:41 [I] Log Mode: File(Info)
2018/09/10 19:25:41 [I] XORM Log Mode: File(Info)
2018/09/10 19:25:41 [I] Cache Service Enabled
2018/09/10 19:25:41 [I] Session Service Enabled
2018/09/10 19:25:41 [I] Migration: Reformat and remove incorrect topics
2018/09/10 19:25:41 [I] This migration could take up to minutes, please be patient.
2018/09/10 19:25:42 [...itea/routers/init.go:60 GlobalInit()] [E] Failed to initialize ORM engine: migrate: do migrate: Sync2: Error 1071: Specified key was too long; max key length is 767 bytes

2018/09/10 19:25:44 [I] Log Mode: File(Info)
2018/09/10 19:25:44 [I] XORM Log Mode: File(Info)
2018/09/10 19:25:44 [I] Cache Service Enabled
2018/09/10 19:25:44 [I] Session Service Enabled
2018/09/10 19:25:44 [I] Migration: Reformat and remove incorrect topics
2018/09/10 19:25:44 [I] This migration could take up to minutes, please be patient.
2018/09/10 19:25:45 [...itea/routers/init.go:60 GlobalInit()] [E] Failed to initialize ORM engine: migrate: do migrate: Sync2: Error 1071: Specified key was too long; max key length is 767 bytes

2018/09/10 19:25:48 [I] Log Mode: File(Info)
2018/09/10 19:25:48 [I] XORM Log Mode: File(Info)
2018/09/10 19:25:48 [I] Cache Service Enabled
2018/09/10 19:25:48 [I] Session Service Enabled
2018/09/10 19:25:48 [I] Migration: Reformat and remove incorrect topics
2018/09/10 19:25:48 [I] This migration could take up to minutes, please be patient.
2018/09/10 19:25:48 [...itea/routers/init.go:60 GlobalInit()] [E] Failed to initialize ORM engine: migrate: do migrate: Sync2: Error 1071: Specified key was too long; max key length is 767 bytes

**Comment by techknowlogick** [comment]
See #2979

**Comment by DumboJet** [comment]
I have Gitea on a Debian (10 buster) and PostgreSQL and I get something similar:

```
routers/init.go:86:GlobalInit() [F] ORM engine initialization failed: dial tcp 127.0.0.1:4511: connect: connection refused
```

I have not tried to update Gitea, although I don't know if it updates automatically somehow...
It was working fine so far and I am not sure what has changed.
I might have updated the OS packages, but I am not sure if that could be the root of the problem.

When I do a `psql --version`, I get:
```
psql (PostgreSQL) 11.6 (Debian 11.6-1.pgdg100+1)
```
