### ISSUE TITLE
Arc Green (dark) theme Review result is near unreadable

### ISSUE THREAD

**Issue by OvermindDL1** [go-gitea/gitea#4909]
- Gitea version (or commit ref):  bd1bf2a
- Git version:  2.7.4
- Operating system:  Ubuntu 18.04
- Database (use `[x]`):
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant (because it is not using the Arc Green theme)
- Log gist:  N/A

## Description

The Arc Green theme review result is not themed well, fairly unreadable, black text on dark background.  See image.  The background needs to be changed up, the 'rejected' review needs to be more obvious (perhaps a red tinted background?), etc...

## Screenshots

![image](https://user-images.githubusercontent.com/401605/45372512-66e2af80-b5aa-11e8-84c4-6b9313779cca.png)

**Comment by lafriks** [comment]
Yes my PR #4682 resolves this issue
