### ISSUE TITLE
Cannot create repository for organisation (using API)

### ISSUE THREAD

**Issue by b0wter** [go-gitea/gitea#4913]
- Gitea version (or commit ref): 8ee9922
- Git version: XX
- Operating system: Linux/Docker
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

I am trying to create a repository for an organization using the REST API. I am using the following curl command:

```
curl -v -X POST "https://try.gitea.io/api/v1/orgs/organization_one/repos" -H "Authorization: token MYTOKEN" -H "Content-Type: application/json" -H  "accept: application/json" --data '{"name": "testrepo"}'
```

but I am receiving an error 404. According to the api docs getting all the repositories for an organization is the same api endpoint but you use a GET instead of a POST:

```
curl -v -X GET "https://try.gitea.io/api/v1/orgs/organization_one/repos" -H "Authorization: token c50fee7a5a3efbe786134a9665959963d9ad469b" -H "Content-Type: application/json" -H  "accept: application/json" --data '{}'
```

and it works perfectly.

**Comment by jmls** [comment]
if you look at the swagger api docs, you will see that POST is to `/org/{org}/repos` and GET is to `/orgs/{org}` :)

![image](https://user-images.githubusercontent.com/929523/45379028-ea29f280-b5f6-11e8-9f03-a89066576522.png)
![image](https://user-images.githubusercontent.com/929523/45379093-147bb000-b5f7-11e8-8f15-ab3cbc06bb46.png)

**Comment by b0wter** [comment]
What a nice way to feel stupid 😓
Thanks for the help, works perfectly now!

**Comment by jmls** [comment]
fwiw, I find the difference annoying and inconsistent ;) And I don't even use gitea yet :) Just looking at the project to see if it fits with our requirements
