### ISSUE TITLE
hostname/DOMAIN used as subpath in templates somehow?

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#4915]
- Gitea version (or commit ref): docker - gitea/gitea:latest
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant (deals with custom config)
- Log gist:
```
gitea_1       | [Macaron] 2018-09-12 04:24:44: Started GET / for 172.68.143.94
gitea_1       | [Macaron] 2018-09-12 04:24:44: Completed GET / 200 OK in 3.83089ms
gitea_1       | [Macaron] 2018-09-12 04:24:45: Started GET /git.me.host/vendor/assets/octicons/octicons.min.css for 172.68.143.94
gitea_1       | [Macaron] 2018-09-12 04:24:45: Completed GET /git.me.host/vendor/assets/octicons/octicons.min.css 404 Not Found in 4.221723ms
gitea_1      
```

## Description

Gitea seems to be using the hostname (defined in ini as DOMAIN) to decide on the addresses for templates as a suburl, when used behind Traefik. I'm unsure if this is still the trailing slash issue
encountered on nginx.

Based on the separated templates (using the AppSubUrl variable in templates/base.tmpl) from 5 days ago, maybe it's just that it's broken there?

Or maybe it's still just that gitea acts weird around trailing slashes (...why... does it still do this?) :cry: 

why would it gobble domain into the templates?

**Comment by lafriks** [comment]
Can you provide parts of app.ini about domain/subpath/appurl?

**Comment by ghost** [comment]
used the example ini, changing the domain and setting DB type to sqlite.

```
[server]
; The protocol the server listens on. One of 'http', 'https', 'unix' or 'fcgi'.
PROTOCOL = http
DOMAIN = git.me.host
ROOT_URL = %(PROTOCOL)s://%(DOMAIN)s:%(HTTP_PORT)s/
; The address to listen on. Either a IPv4/IPv6 address or the path to a unix socket.
HTTP_ADDR = 0.0.0.0
HTTP_PORT = 3000

...

DB_Type=sqlite3


```

**Comment by lafriks** [comment]
app.ini looks good. Can you check what paths are in rendered html when you view source from browser when opening page?

**Comment by ghost** [comment]
```
<link rel="stylesheet" href="git.me.host/vendor/plugins/semantic/semantic.min.css">
	<link rel="stylesheet" href="git.me.host/css/index.css?v=69c0cd75067b7801ae667465a9ee03c3">
```

**Comment by ghost** [comment]
could just be templating not prefixing the url with /? or should that be in the config, prefixed there?

**Comment by ghost** [comment]
(ref="domain/assets" instead of, i.e. "https://domain/assets", or "/domain/assets")

**Comment by lafriks** [comment]
It should not include domain part at all

**Comment by ghost** [comment]
I'm headed off to bed. Thank you @lafriks for helping out so far :)

**Comment by ghost** [comment]
I'll check to see if this issue still exists...

**Comment by mrsdizzie** [comment]
Does not seem reproducible in current version
