### ISSUE TITLE
Markdown table cell value centering support

### ISSUE THREAD

**Issue by Orefa** [go-gitea/gitea#4916]
- Gitea version (or commit ref):1.5.1
- Git version: git version 2.18.0.windows.1
- Operating system: Windows Server 2016
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
add this code to you markdown file

```markdown
| 参数 | 类型 | 说明 | 是否必填 |
| :----: | :----: | :----: | :----: |
| code | string | 机构编码  | 是 |
```
then push to gitea repository

Centered on GitHub, not centered on Gitea

| 参数 | 类型 | 说明 | 是否必填 |
| :----: | :----: | :----: | :----: |
| code | string | 机构编码  | 是 |

**Comment by lafriks** [comment]
Please describe your issue

**Comment by Orefa** [comment]
> 
> 
> Please describe your issue


add this code to you markdown file
```
| 参数 | 类型 | 说明 | 是否必填 |
| :----: | :----: | :----: | :----: |
| code | string | 机构编码  | 是 |
```
then push to gitea  repository

Centered on GitHub, not centered on Gitea
