### ISSUE TITLE
Wording in "last changed date"

### ISSUE THREAD

**Issue by hoellen** [go-gitea/gitea#4917]
- Gitea version: d918e63
- Git version: 2.18
- Operating system: CentOS
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

If the last changed date of a file in repository is more then 1.5 years ago, then it should say "2 years ago", instead of "1 year ago". 
In the example screenshot you can see the last changes on the file has been made on 26 Nov 2016. And that is in my opinion more "2 years ago" then "1 year" atm.

## Screenshots
![grafik](https://user-images.githubusercontent.com/11299996/45405031-9accdc00-b661-11e8-98ee-f14e14ed5703.png)

**Comment by lafriks** [comment]
I think there already was issue about that
