### ISSUE TITLE
API missing or incorect informations for issues and pr

### ISSUE THREAD

**Issue by vfricou** [go-gitea/gitea#4922]
- Gitea version (or commit ref): 1.5.1
- Git version: 2.11.0
- Operating system: Debian 9.4
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes https://try.gitea.io/api/v1/repos/vfricou/test/issues and  https://try.gitea.io/api/v1/repos/vfricou/test/pulls
  - [ ] No
  - [ ] Not relevant
- Log gist: No relevant log found according to theses issues

## Description
For issues case, API sort only open issues. 
In case of statistics or migration attempt, it cause information loosing.

Steps to reproduce : 
  - create one issues without any particular specifications
  - close this issues
  - create another issues without no more specifications
  - let open them
  - check API url http://<hostname>/api/v1/repos/<owner>/<reponame>/issues to see only opened issues is present.

For pull requests case, API sort only open pull request and sort null information for merged.

Update : for PR API request, only pr with branch not deleted are correctly displayed. All PR with branch deleted after merge are displayed with null entry by API return.

Steps to reproduce :
  - create one pull request without any particular specifications
  - merge this PR
  - check API url http://<hostname>/api/v1/repos/<owner>/<reponame>/pulls to see a null entry
  - create a second PR without no more specifications
  - let open them
  - check API url http://<hostname>/api/v1/repos/<owner>/<reponame>/pulls to see actual PR content and previous merged content isn't displayed. In place we see null entry.

**Comment by vfricou** [comment]
No news about this ?

**Comment by lunny** [comment]
@vfricou I think this is compatible with github api v3. If you want to get all issues, you should give a parameter `state=all` the default value is `open`. see https://developer.github.com/v3/issues/#list-issues-for-a-repository

**Comment by vfricou** [comment]
Thanks for answer @lunny but, problem. So the problem is to import repositories to gitlab it couldn't found all of fields needed to import. 

I'll open an issue to them to check this.
