### ISSUE TITLE
upload binary files bypassing git

### ISSUE THREAD

**Issue by laoshaw** [go-gitea/gitea#4924]
I have some large binary files that would like to store in gitea, but no need to increase git size, can gitea handle that, i.e. a web-based file manager that is not using git but is part of gitea?

**Comment by laoshaw** [comment]
really just want to upload them via web interface, git-lfs is fine if it works, I tried it before elsewhere and it was very hard to use for me.

have not yet found any doc on how to use git-lfs with gitea though.

can I view the git-lfs binary files via gitea's UI after they're pushed in?

**Comment by lafriks** [comment]
I think this is out of gitea scope. You can use owncloud/nextcloud for that
