### ISSUE TITLE
Proposal: gitea admin create-user random password

### ISSUE THREAD

**Issue by SagePtr** [go-gitea/gitea#4931]
- Gitea version (or commit ref): 1.6.x
- Git version: any
- Operating system: any
- Database (use `[x]`): any

## Description

It would be good addition to #4489 (Force user to change password), as new admin-created users have temporary passwords - would be nice to add random password generator option to ```gitea admin create-user``` commans.

Example syntax: ```gitea admin create-user --name=jane --email=jane@example.org --random-password```

Or just imply ```--random-password``` if no ```--password=xxxxxxxx``` set.

If random password parameter specified, new password should be printed to stdout on successful user creation to make admin copy it and send to new user. Or if mail is configured, this temporary password may be also sent to new user's email.

Probably random password should be composed of characters which are hard to mistype (without 0 O, i l 1 and other similar pairs)

**Comment by adelowo** [comment]
@SagePtr are you potentially working on this ? Else I can

**Comment by SagePtr** [comment]
@adelowo I didn't started working on it yet, better if you work on this feature because i'm less experienced in golang
