### ISSUE TITLE
Not able to push code

### ISSUE THREAD

**Issue by vbose1** [go-gitea/gitea#4934]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:

## Description
Not able to push code when repository is created under organization. When I transfer repository on user then I can able to push.

error message as below

Pushing development
Remote: User permission denied
Error encountered while pushing to the remote repository: Git failed with a fatal error.
unable to access 'http://xxx.xxx.xxx.xxx:3000/xxxx/xxxxxxx.git/': The requested URL returned error: 403
...

**Comment by lafriks** [comment]
Does user has rights for that organization repository?

**Comment by vbose1** [comment]
Find the solution repository was created by default in Owner team. My team was different.

**Comment by vbose1** [comment]
@lafriks Can I delete Owner team?

**Comment by lafriks** [comment]
Owner team can not be deleted. You can add repository to multiple teams. In Team settings click link `0 repositories` and add repository to that team.
