### ISSUE TITLE
User/org repository listing API

### ISSUE THREAD

**Issue by pyhedgehog** [go-gitea/gitea#494]
Right now gogs and gitea has implemented [`GET /api/v1/user/repos`](https://developer.github.com/v3/repos/#list-your-repositories).
Please implement also those two:
 - [x] [`GET /api/v1/users/:username/repos`](https://developer.github.com/v3/repos/#list-user-repositories)
 - [x] [`GET /api/v1/orgs/:org/repos`](https://developer.github.com/v3/repos/#list-organization-repositories)

**Comment by bkcsoft** [comment]
Just mentioning #64 to keep track of API-related issues :)

**Comment by bkcsoft** [comment]
@lunny @tboerger maybe have a `kind/api`?  we already have a `kind/ui` 😉

**Comment by lunny** [comment]
Yes, I just want to say

**Comment by tboerger** [comment]
> @lunny @tboerger maybe have a kind/api? we already have a kind/ui 😉

Please document ALL labels on the infra docs :(

**Comment by lunny** [comment]
It seems this could be closed?

**Comment by awwalker** [comment]
Oh before I did /users/:username/repos the /orgs/:org/repos wasn't checked...does this mean it was added already? I didn't support it in my PR...

**Comment by lunny** [comment]
sorry, you are right. /orgs/:org/repos didn't be implmented.

**Comment by awwalker** [comment]
Thats ok I think I'll have time later this week to get it done if no one else is working on it...

**Comment by lunny** [comment]
@awwalker any news?

**Comment by awwalker** [comment]
@lunny School has been crazy recently but I can try and get this done this week/end.
