### ISSUE TITLE
Add Touch Support for Mobile Editing

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#4942]
Sorry no template in FastHub-Libre so please enjoy freeform issue goodness. :blush:

On Brave browser for Android, both in Standard and Desktop view, markdown file editing is not easy as:

1. In Mobile View touching inside a text area or editable region to edit files causes erroneous characters to output to the screen, rendering copy/paste inaccessible.
2. In Brave Mobile Desktop View long-pressing to select words and highlight text is not possible as the gesture seems to be swallowed by some other handler. Pasting, however, _does_ work in this view.

Verdict? Needs some UX love, and cross-browser testing on mobile browsers using different platforms so basic file editing is possible using a soft or virtual keyboard.

Many thanks to the team for continuing to provide a stellar self-hosted alterative to Gogs.

**Comment by insertjokehere** [comment]
I'm seeing a similar (related?) issue on Chrome for Android; when editing a markdown file:

* `it<space>` -> `it`
* `was` -> `ititwas`
* `<space>` -> `ititwasititwas`

**Comment by lafriks** [comment]
I have same also on github so this could be browser bug

**Comment by ghost** [comment]
Tested GitHub and was not able to reproduce. By default GitHub doesn't offer a file editor unless in Desktop View so perhaps that's some kind of UX workaround in their UI.

Also reproduced issue in [Via](https://github.com/LakorTi/Via) mobile browser on Android. Each screen touch causes the last untrimmed full word to duplicate itself in the editor even when focus is lost.

Obviously this isn't a top priority but it is indeed a bug of some sort.

**Comment by ghost** [comment]
Letting this one go.

P.s. Bot says "You can re-open it if needed." but that's not necessarily true.
