### ISSUE TITLE
Typo in German translation 

### ISSUE THREAD

**Issue by Siesh1oo** [go-gitea/gitea#4956]
- Gitea version (or commit ref): 1.5.0+rc1-214-g552d8d3a4
- Git version: Not relevant
- Operating system: Not relevant
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

"Selbstegistrierung deaktivieren" --> is missing letter 'r'

## Screenshots
![bildschirmfoto 2018-09-18 um 22 29 54](https://user-images.githubusercontent.com/6906374/45714720-b6b90c00-bb92-11e8-8dcf-0257234eb036.png)

**Comment by lafriks** [comment]
Translations are managed using crowdin. Please suggest changes in https://crowdin.com/translate/gitea/68/enus-de
