### ISSUE TITLE
Add support for multiple emails per user

### ISSUE THREAD

**Issue by RyanSquared** [go-gitea/gitea#4957]
- Gitea version (or commit ref):
- Git version: N/A
- Operating system: Linux [hostname] 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u4 (2018-08-21) x86_64 GNU/Linux running under Docker: `gitea/gitea:latest` updated as of this issue creation

- Database (use `[x]`):
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:

## Description

GitHub allows for users to add multiple emails, listing one as the "primary" email. This is useful as it allows users to have various GPG keys with different emails associated with an account without having verification issues.

This feature is essential for Gitea's verification, as right now my commits are showing as unverified, because the email used to sign them is different than the one associated with my account.

**Comment by lafriks** [comment]
It just historicaly how it was easier to add. GitHub also has it this way

**Comment by RyanSquared** [comment]
GitHub has a dedicated section for managing emails. Not sure whether that's new or not with the redesign. GitHub also mentions that it's the "primary" email, which indicates you can have at least a secondary.

 Onto another issue, it appears as though only one email is being parsed from my key. GitHub says the key is: "Email addresses:  ryan@hashbang.sh   vandor2012@gmail.com" I know that I ran `gpg --export --armor ryan@hashbang.sh`, but after putting it into Gitea, it was listed as `vandor2012@gmail.com`.

**Comment by RyanSquared** [comment]
To clarify on the issue: Gitea expects the key to be made from `vandor2012@gmail.com`. However, the signature is parsed as coming from `ryan@hashbang.sh`
