### ISSUE TITLE
Add a section in README.md describing how to upgrade from existing Gogs setup

### ISSUE THREAD

**Issue by typeless** [go-gitea/gitea#496]
I used to have it done by 

1. `mkdir gitea` as the working directory for the Gitea server.
2. Symlink the `public` and  `templates` directories from the Gitea source tree under the `gitea` directory.
3. Symlink the `data` directory from the existing Gogs installation under the `gitea` direcotry.
4. Put the `gitea` executable under the `gitea` directory.

But it needs more testing and confirmations to ensure this is the correct.

It seemed to be possible to have both servers running simultaneously given that SQLite3 will manage the transactions properly under multi-process. Though I doubt this is still reliably feasible as the two project continue to diverge.

Anyway, a clear and reliable upgrading path is helpful.

**Comment by lunny** [comment]
see https://docs.gitea.io/en-us/upgrade-from-gogs/

**Comment by perfaram** [comment]
What are the main differences from Gogs, anyway ?

**Comment by strk** [comment]
Not many differences in functionality, yet.
Difference is in governance, which some of us think
will result in faster development.

**Comment by tboerger** [comment]
The upgrade path is documented in the docs page. We should keep the readme simple and push the people to the localized docs page.
