### ISSUE TITLE
Guide regarding reverse proxy setup for Caddy

### ISSUE THREAD

**Issue by victpork** [go-gitea/gitea#4963]
- Gitea version (or commit ref): f6eb669
- Git version:
- Operating system: Ubuntu Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
On page https://docs.gitea.io/en-us/reverse-proxies/ the guide for Caddy setting subpath reverse proxy does not work on me, which is 
```
git.example.com {
    proxy /git/ http://localhost:3000 # Note: Trailing Slash after /git/
}
```
took me some time to figure out it should be
```
git.example.com {
    proxy /git/ http://localhost:3000  {  # Note: Trailing Slash after /git/ 
          without /git
    }
}
```
I'm using Caddy 0.11.0 . Let me know if this only happens on me or the doc needs update.

**Comment by tankerkiller125** [comment]
Mine is working perfectly with caddy as a reverse proxy, I do have some custom settings though so I will have to get that config off my server sometime when I get a chance.

**Comment by sapk** [comment]
@mkishere What is the value of `ROOT_URL` in your config file ? Make sure to have it config like specified at the end of doc when using sub-path proxy (https://docs.gitea.io/en-us/reverse-proxies/#using-caddy-with-a-sub-path-as-a-reverse-proxy-1)

**Comment by victpork** [comment]
I remember I did set the ROOT_URL with /git/ at the end as the document told, and still gitea return 404 for requests that prefix with the /git/ path.

But since I have switched settings (switching from subpath to subdomain), I'll need some time to reproduce and stick the logs to here.

**EDIT**: Just tried again setting ROOT_URL to http://domain/git/ , path prefix with /git/ requests to gitea still returns 404. The index page generates links with /git/ prefix though.

Excerpt from curl localhost:3000 :
```html
<script src="/git/vendor/plugins/jquery/jquery.min.js"></script>
        <script src="/git/vendor/plugins/jquery.areyousure/jquery.are-you-sure.js"></script>
```
Log (from docker-compose logs gitea):
```text
gitea_1         | [Macaron] 2018-09-24 07:25:57: Started GET /git/vendor/plugins/jquery/jquery.min.js for 118.142.94.222
...
gitea_1         | [Macaron] 2018-09-24 07:25:57: Completed GET /git/vendor/plugins/jquery/jquery.min.js 404 Not Found in 4.298407ms
```
```
