### ISSUE TITLE
Avatar not displayed when hide email address

### ISSUE THREAD

**Issue by ejouvin** [go-gitea/gitea#4965]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
Did it on the try gitea here : https://try.gitea.io/ejouvin/MyPRTest

I've create a new account and put a different email address for the avatar and the profile.

On first commit, the email address is not hidden. The avatar is "well" displayed.
After setting my email as hidden, but the email for avatar is correct, the avatar is not displayed for next commit.
Then I set the email address as visible, and avatar is correctly displayed for next commits.

Is it correct that hidding email has impact on the avatar displaying ?
It could be the case if the profile email is same as avatar email, but in other case I am not sure.

...

**Comment by lafriks** [comment]
Yes it is current behaviour as users are identified by email
