### ISSUE TITLE
pprof is public accessible even when ENABLE_PPROF=false

### ISSUE THREAD

**Issue by krombel** [go-gitea/gitea#4966]
- Gitea version (or commit ref): 364c029
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes: e.g. https://try.gitea.io/debug/pprof/heap?debug=1

## Description

I do not expect to have those debug information public available.

Those get added in go-macaron/toolbox
https://github.com/go-gitea/gitea/blob/364c02924607eeebbe7d76983a7c5e45e9017fe0/vendor/github.com/go-macaron/toolbox/toolbox.go#L136-L140
which got added in [#1290](https://github.com/go-gitea/gitea/pull/1290/files#diff-7aa71b75b5fddf1332a485052ffbca9aR117):
https://github.com/go-gitea/gitea/blob/364c02924607eeebbe7d76983a7c5e45e9017fe0/routers/routes/routes.go#L127-L134

Badly there does not seem to be an option to disable this without removing the Toolbox completly.

//EDIT: As a temporary workaround I added this to my nginx config:
```
        location /debug {
                return 403;
        }
```

**Comment by L-P** [comment]
I can confirm this issue is present on the official v1.5.1 docker image.
