### ISSUE TITLE
How To do Code review in Gitea

### ISSUE THREAD

**Issue by vbose1** [go-gitea/gitea#4968]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:

## Description
I am using Gitea in my local environment. I need code review for pull request. Can anybody help how to do..
...

**Comment by techknowlogick** [comment]
@vbose1 which version of Gitea are you using?

The functionality is is 1.6.0-dev (which will soon be most recent stable as the project will release an RC is the coming week assuming plans stay the same) and so you'll need to change to that version if you need comments on code in your PRs.

**Comment by vbose1** [comment]
So I have one more query how to update the Gitea. I have running through windows services.

**Comment by lafriks** [comment]
Please use Gitea forum for such questions
