### ISSUE TITLE
How to add inline comments on code in PRs?

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#4970]
- Gitea version (or commit ref): 1.5.1

## Description

According to https://docs.gitea.io/en-us/comparison/ we can use

> Pull/Merge request inline comments

But how? Is there an option I have to enable?

**Comment by techknowlogick** [comment]
Closed as duplicate of #4968 

The functionality is is 1.6.0-dev (which will soon be most recent stable as the project will release an RC is the coming week assuming plans stay the same) and so you'll need to change to that version if you need comments on code in your PRs.

**Comment by ghost** [comment]
Thanks again for you quick response!

I am a little confused. The linked doc compares Gitea 1.6.0 which is not officially available, yet? *puzzled*

Maybe you should consider adding the version the doc applies to. Or even better add a note for each feature which is available soon.

**Comment by lafriks** [comment]
We do not currently have versioned documentation
