### ISSUE TITLE
Cannot remove user from organization (MSSQL)

### ISSUE THREAD

**Issue by vzro** [go-gitea/gitea#4972]
- Gitea version (or commit ref): 1.4.1 / 1.5.1
- Git version: 2.17.0
- Operating system: Windows Server 2016 (1607 / 14393.2430)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
When trying to remove a member from an organization, the service freezes and has to be restarted.
...

**Comment by lafriks** [comment]
Do you get any errors in gitea.log?

**Comment by vzro** [comment]
This is all I got in it:

2018/09/22 00:50:36 [I] Log Mode: File(Info)
2018/09/22 00:50:36 [I] XORM Log Mode: File(Info)
2018/09/22 00:50:36 [I] Cache Service Enabled
2018/09/22 00:50:36 [I] Session Service Enabled
2018/09/22 00:50:36 [I] Mail Service Enabled
2018/09/22 00:50:36 [I] Register Mail Service Enabled
2018/09/22 00:50:36 [I] Notify Mail Service Enabled
2018/09/22 00:50:36 [I] Git Version: 2.17.0
2018/09/22 00:50:36 [I] SQLite3 Supported
2018/09/22 00:50:36 [I] Run Mode: Production
2018/09/22 00:50:36 [I] Listen: http://0.0.0.0:2199
2018/09/22 00:50:36 [I] LFS server enabled
2018/09/22 00:53:20 [...routers/org/teams.go:107 TeamsAction()] [E] Action(remove): AccessibleReposEnv: read tcp 10.0.75.1:55379->10.0.75.1:1433: i/o timeout
2018/09/22 00:53:38 [...s/context/context.go:235 func1()] [E] UserSignIn: sql: expected 9 destination arguments in Scan, not 1
2018/09/22 00:53:38 [...routers/repo/http.go:180 HTTP()] [E] Users with two-factor authentication enabled cannot perform HTTP/HTTPS operations via plain username and password. Please create and use a personal access token on the user settings page
2018/09/22 00:53:38 [...routers/repo/http.go:141 HTTP()] [E] invalid credentials

**Comment by vzro** [comment]
I've also noticed that, in the log directory, an empty file called 'http' is created. I'm not sure whether or not this relates to the actual problem/bug, just thought it would be helpful to mention it.

**Comment by vzro** [comment]
A quick addendum: Every request inside Gitea, after trying to remove the user from the organization, results in a 404 page (screenshot attached).

![capture](https://user-images.githubusercontent.com/23323304/45913123-45cc5b00-be03-11e8-9432-0040081beafd.PNG)

**Comment by vzro** [comment]
Can anyone, from Gitea or not, help me verify this?
Thanks!

**Comment by sapk** [comment]
@rzo you seems to have a request that timeout. `read tcp 10.0.75.1:55379->10.0.75.1:1433: i/o timeout`. It seems to have corrupt the database and leave it in an unstable state. Gitea should have catch it and revert to a stable state. Can you provide the exact commit or release of the log since line 107 of teams.go seems irrelevant on master? And any more logs of others errors after ?

**Comment by vzro** [comment]
@sapk I'm not sure if I understood you correctly.

The log I posted above is all there's to it. I mean, the only file with content inside the logs folder.

Every request after trying to remove the user results in 404 and 500 errors.

I'm not sure I could say the database is 'corrupted', given that it takes a service restart to make things work normally again.

I just can't remove any user from the organization.

**Comment by vzro** [comment]
Hey, guys... Can anyone help with this?
What else can I provide to further help the investigations?

**Comment by sapk** [comment]
#4282 mssql integrations tests are near ready to be setup. Those show that some parts of gitea are not fully working on mssql. I didn't see at first glance failing user removal but that maybe the integrations tests that didn't cover this corner.
