### ISSUE TITLE
Error when I select a "due date" in a spanish web interface.

### ISSUE THREAD

**Issue by luismanolo** [go-gitea/gitea#4974]
- Gitea version (or commit ref): 36e7cb9
- Git version: 2.17.1
- Operating system: Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X] No
  - [ ] Not relevant

## Description

when I set a "Due Date" in a new Issue with a spanish lang, I have this error:

The due date is invalid or out of range. Please use the format 'yyyy-mm-dd'.

## Screenshots

![capture-due-date-gitea](https://user-images.githubusercontent.com/1156216/45964275-9b804d80-c025-11e8-95d0-5d7d8f059932.png)

**Comment by lafriks** [comment]
Yes we need better date picker/valiadation

**Comment by ronnieoverby** [comment]
I get this error in in an "english web interface" whatever that is :)

**Comment by AlexDunmow** [comment]
I get this error too.

**Comment by mckaygerhard** [comment]
present in lasted 1.6.0 released, whatever languaje selected, the title of the issue must be changed to "no date picker in issue due date"

**Comment by lunny** [comment]
duplicated with #5226
