### ISSUE TITLE
PANIC: index out of range when viewing org file in repository

### ISSUE THREAD

**Issue by howdoicomputer** [go-gitea/gitea#4982]
- Gitea version (or commit ref): 1.5.1
- Git version: 2.14.1
- Operating system: Ubuntu 17.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes: https://try.gitea.io/howdoicomputer/org-test
  - [ ] No
  - [ ] Not relevant
- Log gist: https://gist.github.com/howdoicomputer/4b85078aea5750c042bd7b9292d7f65f

## Description

I checked in an org file to a private repository. I'm able to pull the file and view the diff but rendering it in the web view produces a blank page and stack trace.

**Comment by howdoicomputer** [comment]
It looks like Gitea fails to render if goorgeous fails to parse. I pushed a simpler test.org file and it rendered fine.

**Comment by howdoicomputer** [comment]
This is an upstream issue: https://github.com/chaseadamsio/goorgeous/issues/82

Goorgeous cannot parse org files with empty headerlines.

**Comment by zeripath** [comment]
Ok, although the original cause of this bug is in an upstream library - now that we know about it we should recover from panics within that library and just render the text with an error.

See https://blog.golang.org/defer-panic-and-recover

We should also have a root handler for Macaron that does a similar recover and returns a gitea 500. Probably with two different levels of information depending on the production mode. (I.e. report stack trace or not)

**Comment by adelowo** [comment]
@zeripath There is already a handler for recovery. I believe the application should keep on
running. I have run into a few waves of panic too

https://github.com/go-gitea/gitea/blob/a967cf9e99461bbd89b8b26fd41faf9f4ed06010/routers/routes/routes.go#L55

https://github.com/go-macaron/docs/blob/master/en-US/middlewares/core_services.md

**Comment by zeripath** [comment]
Ah but that is not good enough - the user gets a blank page.

**Comment by igor9292** [comment]
colleagues, and you can make the file appear just text,
file was displayed without formatting?

**Comment by howdoicomputer** [comment]
There is also this open issue that suggests replacing goorgeous with another library.

https://github.com/go-gitea/gitea/issues/5710
