### ISSUE TITLE
Cuchillo means knife, Tenedor means Fork.

### ISSUE THREAD

**Issue by n3storm** [go-gitea/gitea#4989]
https://github.com/go-gitea/gitea/blob/b5b39a56ad9efc09d7e830f764a40ba39a76066c/options/locale/locale_es-ES.ini#L353

I think it looks a bit unproffesional to show this translation but I don't know how to change it as translation comes from Crowdin.

Fork word should not be translated by the way, else no spanish speaker developer will understand.

**Comment by SagePtr** [comment]
Update it on crowdin: https://crowdin.com/project/gitea
