### ISSUE TITLE
Apply external markup rendering to non-text files

### ISSUE THREAD

**Issue by causal-agent** [go-gitea/gitea#4996]
- Gitea version (or commit ref): 1.4.3
- Git version: 2.18.0
- Operating system: FreeBSD 11.2-RELEASE
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

Currently, files are only checked against external markup extensions when the file is a text file: https://github.com/go-gitea/gitea/blob/fc0001caa1e9873a86990f7815a75d8f75fbc309/routers/repo/view.go#L201-L214

I would like to be able to use external markup renderers to render previews of some binary formats, similar to how PDFs can be displayed inline. Instead, I always get the "view raw" page for binary files.

**Comment by HarvsG** [comment]
I have the same issue trying to render docx files using pandoc. I created an issue #7614.

**Comment by HarvsG** [comment]
As you identified the type of rendering is determined by this switch
https://github.com/go-gitea/gitea/blob/fc0001caa1e9873a86990f7815a75d8f75fbc309/routers/repo/view.go#L200-L269

But interestingly I cant see a `case base.IsBinaryFile(buf):` or  a `default:` case that would manage binary files. So they must either be handles before the switch or after it.
