### ISSUE TITLE
Unable to delete inactive users

### ISSUE THREAD

**Issue by cyrakuse** [go-gitea/gitea#4997]
- Gitea version (or commit ref): 1.5.1
- Git version: 2.18.0
- Operating system: windows 2008 R2
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x ] No
  - [ ] Not relevant
- Log gist:

## Description

I have configured LDAP authentication.
When i've seen that my filter was not good, i modified it to restrict more.
After i wanted to delete inactive users with the link in the dashboard and i obtain an error message :
"rename C:\Windows\system32\config\systemprofile\.ssh\authorized_keys.tmp C:\Windows\system32\config\systemprofile\.ssh\authorized_keys: Le processus ne peut pas accéder au fichier car ce fichier est utilisé par un autre processus"
and the inactive users are not deleted.

**Comment by lafriks** [comment]
Do you use OpenSSH server on windows?

**Comment by cyrakuse** [comment]
I don't know.
I need to install OpenSSH on the server ?

**Comment by lafriks** [comment]
@cyrakuse if not than you need to set in app.ini to use builtin ssh server
