### ISSUE TITLE
Upgrade gopkg.in/testfixtures.v2

### ISSUE THREAD

**Issue by typeless** [go-gitea/gitea#4998]
Encountered a deadlock while working on #2040 

See https://github.com/go-gitea/gitea/blob/master/vendor/gopkg.in/testfixtures.v2/sqlite.go#L25-L40
`tx.Rollback` is missing. It has been fixed upstream.
I cannot find the document about upgrading the vendored packages. It used to be govendor. I am not sure about the current approach so here is the issue. Hopefully you guys could help.

**Comment by adelowo** [comment]
`make vendor` https://github.com/go-gitea/gitea/blob/b8d048fa0d2cdd0781051990d34cb3681a8ae114/Makefile#L176

**Comment by typeless** [comment]
@adelowo Thanks for the hint. I am looking up dep now.

hmm ... `make vendor` has been hanging for quite a while. Is that normal? I should have added `-v` 😆

**Comment by adelowo** [comment]
> hmm ... `make vendor` has been hanging for quite a while. Is that normal? I should have added `-v` 😆

Usually slow on my end too but I think it's my internet connection
