### ISSUE TITLE
Add Repository only View

### ISSUE THREAD

**Issue by Spenhouet** [go-gitea/gitea#5002]
Could it be possible to add an option that allows an user only to view a repository he/she is member of.

What I'm proposing is that the user can only open the repository over the unique URL. The user can't enter any other URL.

Instead of this:

![image](https://user-images.githubusercontent.com/7819068/46356720-934a9280-c663-11e8-9c69-4521676d22bb.png)

The user is only able to see the following:

![image](https://user-images.githubusercontent.com/7819068/46356744-a3fb0880-c663-11e8-85dc-a901898792cc.png)

There is no header. The user can't enter anything else (also not over URL).

This would be optimal for our use case.
A user with one repository (everything created via API) and the link to this repository with login data is shared with the user. The user can see only the repository view and work on this repository. He/she is unable to see anything else.

I would like to propose this as a feature request. The implementation detail would need to be discussed. I personally think about it in permission rights.

**Comment by wxiaoguang** [comment]
https://github.com/go-gitea/gitea/blob/main/custom/conf/app.example.ini#L949-L957

Now you can disable some "units". Feel free to reopen if there is still a problem
