### ISSUE TITLE
A repo with more than 10000~ files takes long time to show the page

### ISSUE THREAD

**Issue by typeless** [go-gitea/gitea#502]
- Gitea version (or commit ref):
```
$ ./gitea --version
Gitea version 6aacf4d
```
- Git version:
```
$ git --version
git version 2.7.4
```
- Operating system:
```
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.1 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.1 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
```
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

https://try.gitea.io/test/too-many-files

## Description
```
mkdir too-many-files
cd too-many-files
for i in {1..10000}; do touch $i; done
git init
git add .
git commit -m "Initial commit"
git remote add origin https://try.gitea.io/test/too-many-files.git
git push -u origin master
```
Then use web browser to load the page.
...

P.S. 
1. It will eventually have a response, just taking very long time.
2. If your server is set up with systemd, `systemctl status gitea.service` will show some interesting/strange *phenomenon*, which could be informative.

**Comment by joubertredrat** [comment]
Maybe pagination to prevent this?

**Comment by lunny** [comment]
Ignore files after show some, this is also github does.

**Comment by azlan** [comment]
My repo doesn't have 10k files, but just 550 commits. Opening 'Commits' tab takes more than 2 seconds.

`[Macaron] 2016-12-28 10:57:55: Completed /zxcv/MyRepo/commits/master 200 OK in 2.3113341s`

**Comment by typeless** [comment]
@azlan Can you specify the details of the problem in another ticket ?

**Comment by lunny** [comment]
I will check that

**Comment by metalmatze** [comment]
Yes. Github just limits at 1000 files. I think that should be somewhat reasonable for a web UI, you can always check out locally or know what you're looking for an change the url, maybe use a search too. Idk how practical pagination might be for that. I don't see a real value in browsing thousands of files through pagination.

**Comment by lunny** [comment]
So we could also limits at 1000 files to fix this issue.

**Comment by bkcsoft** [comment]
@lunny maybe add pagination in the future?

**Comment by bkcsoft** [comment]
or at least some kind of lazy-loading (`Press here to load more`)

**Comment by lunny** [comment]
That's another issues. Currently we have to limit 1000 files just like Github to fix this one.

**Comment by bkcsoft** [comment]
This seems related as well: https://github.com/gogits/gogs/issues/3022 (see https://github.com/gogits/gogs/issues/3094 for reference)

**Comment by tboerger** [comment]
We got this kind of issue multiple times now.

**Comment by lunny** [comment]
I will move this to v1.2 since there is no PR to fix this.

**Comment by tycho** [comment]
Since gitea seems to be the future of gogs, and the gogs issue is basically dead... any commentary on the proposed solution in the original post of https://github.com/gogits/gogs/issues/3022?

**Comment by lunny** [comment]
This should be fixed on v1.2

**Comment by tycho** [comment]
I'm not asking when it will be fixed, but rather how.

**Comment by lunny** [comment]
Just like github, will limit the numbers shown in the UI.

**Comment by tycho** [comment]
Have a diff?

**Comment by JeffreyLeeSpokeo** [comment]
1000 commits is still a lot and makes the page really slow. It should be no more than 100 and then paginate from there

**Comment by lunny** [comment]
This is the files page, not commits page. Commits page has paginate.

**Comment by JeffreyLeeSpokeo** [comment]
I see sorry that was my mistake. For some reason I thought it mean like 1000 of files and/or commits in a PR. I deleted my comment

**Comment by ppKrauss** [comment]
Hi, I have commited ~4000 itens at [this repo](https://github.com/datasets-br/city-codes) and there are no update (~1h!) at Github site and `git clone`... It is the same "bug" here?  

I must suppose that no commit will do, so I must to sendo 999, 999, etc. pushes?

**Comment by typeless** [comment]
This has been fixed.
