### ISSUE TITLE
Issues: Assigned to me

### ISSUE THREAD

**Issue by jeppech** [go-gitea/gitea#503]
This is a much needed feature, to easily keep an overview over issues assigned to yourself. A PR was made on Gogs here https://github.com/gogits/gogs/pull/3560

**Comment by lunny** [comment]
We need a cherry-pick from Gogs. @jeppech Could you do that?

**Comment by jeppech** [comment]
I will give it a try.

**Comment by jeppech** [comment]
@lunny Unfortunately, I am unable to figure this out, at the moment.

**Comment by lunny** [comment]
I have reviewed that Gogs PR. It's difficult to cherry-pick to Gitea since Gitea has changed a lot. We will rewrite this part according the PR.

**Comment by jeppech** [comment]
That's what I found out as well. And as I'm not that familiar with Go/Gitea, I didn't know what to keep nor remove.

**Comment by upwell** [comment]
Any plan on this feature? Really need it.

**Comment by lunny** [comment]
This could be beginning after #530 ? I think.

**Comment by lunny** [comment]
~~It seems this is also a bug in v1.0.1~~
