### ISSUE TITLE
External markup renderers can't use in-repo images

### ISSUE THREAD

**Issue by pjanx** [go-gitea/gitea#5031]
- Gitea version (or commit ref): 1.5.1
- Git version: master
- Operating system: Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant

## Description

The logic in modules/markup/markdown's `(*Renderer).Image` is inaccessible to external renderers. Relative image URLs pass through unchanged and wrong.

I can think of two solutions:
 - Expose `urlPrefix`  to the process as an environment variable, such as `GITEA_PREFIX_SRC=/user/repo/raw/branch/master/subdir/` and `GITEA_PREFIX_RAW=/user/repo/raw/branch/master/subdir/`. Then you can at least wrap external tools in scripts; asciidoctor just needs to have the `imagesdir` attribute set appropriately.
 - Change all relative image `src`s in a `PostProcess` step to point to a `/raw/` location because they are pointless anyway (a brute force solution would be to use `<base href=>` in the header template).

**Comment by pjanx** [comment]
Slight generalization of my workaround for nginx, works only for a project's root README:
```
# Circumventing Gitea issue #5031
# Must not catch POST /user/login, that is an awful surprise
set $redirectable 1;
if ($request_method !~ ^(HEAD|GET)$) {
        set $redirectable 0;
}
if ($request_uri !~ ^(/[^/]+/[^/]+)$) {
        set $redirectable 0;
}
if ($redirectable) {
        return  301 https://$host$request_uri/;
}
```
```
#!/bin/sh
external-markup-renderer-invocation | perl -pe '
    # The URL must end with a slash; since <script> does not
    # come through, I had to resolve that in nginx.conf
    s,(<img src=")([^/]*?"),$1raw/branch/master/$2,g'
```
```
RENDER_COMMAND = /path/to/that/script
```

**Comment by Eisfunke** [comment]
I noticed this too (when using Pandoc as markdown parser) and was just about to open an issue about this.

I would prefer the approach using an environment variable, as this would be more flexible. If there are no objections and I get around to it, I'll try to make a PR doing that.

Also, thanks for the workaround script!
