### ISSUE TITLE
Language for not logged in users

### ISSUE THREAD

**Issue by Monter** [go-gitea/gitea#5036]
- Gitea version (or commit ref): latest and olders
- Database (use `[x]`):
  - [x ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x ] Yes (provide example URL)

## Description

How to set up gitea so that visitors to the site without login will by default turn on the selected language instead of compatible with the visitor browser?
For example, I would like to set up to always activate the English language.

**Comment by pjanx** [comment]
You can always remove undesired languages. And perhaps you should, translations have very mixed quality.

```
[i18n]
LANGS = en-US,zh-CN,zh-HK,zh-TW,de-DE,fr-FR,nl-NL,lv-LV,ru-RU,uk-UA,ja-JP,es-ES,pt-BR,pl-PL,bg-BG,it-IT,fi-FI,tr-TR,cs-CZ,sr-SP,sv-SE,ko-KR
NAMES = English,简体中文,繁體中文（香港）,繁體中文（台灣）,Deutsch,français,Nederlands,latviešu,русский,Українська,日本語,español,português do Brasil,polski,български,italiano,suomi,Türkçe,čeština,српски,svenska,한국어
```

**Comment by adelowo** [comment]
Looks like a duplicate of https://github.com/go-gitea/gitea/issues/4884

**Comment by Monter** [comment]
> You can always remove undesired languages

I know, but this is not a solution to the problem. By removing languages and leaving two basic ones (eg English and your own) despite setting English as default after logging in, visitors from my country will by default receive an interface in a language other than English. And I would like English to be the default, leaving the site visitor to change language.

**Comment by lesderid** [comment]
Was this fixed?
