### ISSUE TITLE
change highlightjs theme

### ISSUE THREAD

**Issue by r6m** [go-gitea/gitea#5037]
Hi, Is there any option to change the highlightjs theme? like in app config?

**Comment by axifive** [comment]
Currently there isn't such parameter in the config.

**Comment by r6m** [comment]
How can I add these kind of features? In install page? where is the value saved for such configs?
Generally I mean the contribution steps. :)

**Comment by mrsdizzie** [comment]
Closing as highlight.js is no longer used
