### ISSUE TITLE
en: many buttons labeled "click here"

### ISSUE THREAD

**Issue by coolaj86** [go-gitea/gitea#5039]
I came across this:

![screen shot 2018-10-07 at 10 45 37 am](https://user-images.githubusercontent.com/122831/46584256-4cbbb600-ca1e-11e8-9747-0f9b02d0c51e.png)

And then looked in `options/locale/locale_en-US.ini` to find that there are a ton of things (presumably buttons) labeled "click here".

The visual design language of a button is already supposed to clearly communicate "click here".

How about we drop those "click here" prefixes and rephrase them as verbs?

```
"Click here to x the y" => "X y"
"Click here to reset the password" => "Reset password"
```

**Comment by lunny** [comment]
@coolaj86 I agree with you although I'm not an English native speaker. Please send a PR.
