### ISSUE TITLE
Wrong version information in 1.5.1

### ISSUE THREAD

**Issue by pvgoran** [go-gitea/gitea#5040]
- Gitea version (or commit ref): 1.5.1
- Git version: (irrelevant)
- Operating system: (irrelevant)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

https://github.com/go-gitea/gitea/blob/v1.5.1/main.go#L24 says:

```
var Version = "1.5.0-dev"
```

So Gitea shows a wrong version in logs, in the Web interface, and in CLI, for example:

```
> /nix/store/rc2ajcxinkmnkdas78563vra7v1a8nsb-gitea-1.5.1-bin/bin/gitea --version
Gitea version 1.5.0-dev
```

**Comment by coolaj86** [comment]
Did you do `TAGS="bindata" make generate all` when building?

If you just run `go build` it'll use the literals in `main.go`. If you run the makefile, it'll build with the dynamic strings as expected.

See https://www.atatus.com/blog/golang-auto-build-versioning/

**Comment by pvgoran** [comment]
> Did you do `TAGS="bindata" make generate all` when building?

Well, it was built as part of [Nixos distribution](https://nixos.org/), and frankly, I don't know whether it was `go build` or `make` or something other (the go build specifics in Nixos are quite confusing to my untrained eye).

> If you just run `go build` it'll use the literals in `main.go`. If you run the makefile, it'll build with the dynamic strings as expected.

So, the "wrong" version in the source file is by design, then...

When building gitea with the recommended/expected way, where does the build system get the version number to use? From the version control system?

**Comment by techknowlogick** [comment]
Here is the line of the make file that injects the version: https://github.com/go-gitea/gitea/blob/master/Makefile#L36 (based on CI server for gitea, and if that is not available then based on git). It's not wrong by design, as running `go build` directly isn't part of design, the project recommends using the make file to build project.

Please use the [forum](https://discourse.gitea.io/) for any follow up discussion.
