### ISSUE TITLE
some user after login, home page freeze

### ISSUE THREAD

**Issue by maxid** [go-gitea/gitea#5043]
- Gitea version (or commit ref): 378af8e
- Git version: 2.16.1
- Operating system: server centos 7, client mac+chrome 69.0.3497.100
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description
some user after login, home page freeze
```bash
[Macaron] 2018-10-08 11:40:38: Completed GET / 200 OK in 1m24.187145695s
```
...

## Screenshots

![image](https://user-images.githubusercontent.com/927429/46591927-d76ce580-caf0-11e8-9764-3e79cd53f2a7.png)

**Comment by lafriks** [comment]
It should be DNS request first if I remember correctly
