### ISSUE TITLE
Migrate from dep to golang modules (vgo)

### ISSUE THREAD

**Issue by lafriks** [go-gitea/gitea#5044]

**Comment by coolaj86** [comment]
Hey! I already did that in my local branch and it was super easy. Takes about 10 minutes (mostly parsing and downloading deps).

```
go mod init
```

But then updating docker and all that... not quite as quick perhaps.

I'll make a PR for as far as I got, but it'll be missing some things, of course.

**Comment by lunny** [comment]
So when 1.7.0 is coming, we will drop go1.10 support.

**Comment by lafriks** [comment]
@coolaj86 yes updating drone build steps including step for checking if dependencies are correct also needs to be fixed

**Comment by coolaj86** [comment]
```
go: converting Gopkg.lock: stat github.com/boltdb/bolt@ccd680d8c1a0179ac3d68f692b01e1a1589cbfc7: unknown revision ccd680d8c1a0179ac3d68f692b01e1a1589cbfc7
```

Do we have a custom patched version of boltdb committed to the repo?

**Comment by techknowlogick** [comment]
@coolaj86 iirc yes https://github.com/go-gitea/bolt

**Comment by coolaj86** [comment]
Actually... we don't.

```
rg bolt
Gopkg.lock
111:    "index/store/boltdb",
149:  name = "github.com/boltdb/bolt"
153:  source = "github.com/go-gitea/bolt"

Gopkg.toml
91:  name = "github.com/boltdb/bolt"
93:  source = "github.com/go-gitea/bolt"
```

The only place it shows up is in the lock file.

**Comment by techknowlogick** [comment]
oh you know what that dependency might have been removed when tidb was removed.

**Comment by coolaj86** [comment]
I see that `bleve` also uses bolt. Should I assume that our `bolt` modifications for `tidb` and not for `bleve`?

**Comment by techknowlogick** [comment]
the modifications were so that bolt builds on mips platforms, but maybe it's time to use https://github.com/etcd-io/bbolt instead (if bleve supports it)

**Comment by coolaj86** [comment]
I was hoping to be able to use `go mod`s new `replace` feature, but it looks like we'll still have to have a gitea version if nothing more than to rename the package from `bbolt` back to `bolt`: https://github.com/etcd-io/bbolt/issues/129

Or the bleve maintainers will have to migrate: https://github.com/blevesearch/bleve/issues/783

**Comment by techknowlogick** [comment]
@coolaj86 As you can see from my comment in the (bleve) ticket you linked I created a PR to upgrade to use bbolt, however I'm having some trouble with failing tests. If you are keen on solving those issues I can give you access to my fork.

**Comment by techknowlogick** [comment]
blevesearch/bleve#783 has successfully been completed, which means  we can drop support for regular bolt, and just use bbolt for everything!
