### ISSUE TITLE
URL formatting breaks in PR comments due to hyphens in org or repo names

### ISSUE THREAD

**Issue by Alofoxx** [go-gitea/gitea#5047]
- Gitea version (or commit ref): 1.5.1 
- Git version:  Not relevant
- Operating system: Ubuntu 16
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL) --> https://try.gitea.io/alofoxx/testing-pr-comments/pulls/1#issuecomment-8071
  - [ ] No
  - [ ] Not relevant
- Log gist: Not relevant

## Description
URL formatting breaks in PR comments when there is a hyphen in the URL (as there would be in any repo name that contains a hyphen). I recreated the issue in your demo site.
https://try.gitea.io/alofoxx/testing-pr-comments/pulls/1#issuecomment-8069

The parsing seems to not care about the hyphen in the "issuecomment-xxxx" when there are no other hyphens involved in the url. When the repo name has a single hyphen the parsing breaks at the issuecomment^- hyphen. When there are hyphens in the team name that owns the repo - the parsing breaks on the first one seen:

https://somesite.com/my^-orgname/repo-name/issuecomment-xxxx

This affects our install due to hyphens in repo names and hyphens in the org names that own the repo.

## Screenshots
![screen shot 2018-10-09 at 12 10 02 am](https://user-images.githubusercontent.com/1343190/46652761-ea1b0500-cb58-11e8-8546-3fb74d21cc4a.png)

**Comment by ghost** [comment]
duplicated with #4435
