### ISSUE TITLE
Unable to build from source

### ISSUE THREAD

**Issue by ijsnow** [go-gitea/gitea#5056]
- Gitea version (or commit ref): fb3954f (master at time of posting)
- Git version: 2.15.0
- Operating system: MacOS High Sierra 10.13.6
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist: https://gist.github.com/ijsnow/a780615ba1a9e5f26cc1fdd5cd046d57

## Description

Running `TAGS="bindata" make generate all` as described in the README results in an error. I've got Go 1.11 installed if that makes a difference.

**Comment by ijsnow** [comment]
That seemed to work. Should the README tell you to clone it into `$GOPATH/src/code.gitea.io/gitea` instead of `$GOPATH/src/github.com/go-gitea/gitea`? 

I know the code is hosted there too but I think most people will find these steps first on GitHub (like me) so there first assumption would be to clone it into `$GOPATH/src/github.com/go-gitea/gitea`.

**Comment by techknowlogick** [comment]
Here are instructions for dealing with source: https://docs.gitea.io/en-us/install-from-source/, also https://docs.gitea.io/en-us/hacking-on-gitea/

**Comment by kawing-chiu** [comment]
The `code.gitea.io` site is just too slow to access from my location. Is there a way to build on `github.com/go-gitea/gitea`?
