### ISSUE TITLE
Upgrade from 1.4.3 to 1.5.2 fails (PostgreSQL 10.5)

### ISSUE THREAD

**Issue by barthalion** [go-gitea/gitea#5057]
- Gitea version (or commit ref): 1.4.3 / 1.5.2
- Git version: 2.19.0
- Operating system: Arch Linux ARM
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist: https://gist.github.com/barthalion/65736b06046acde0284b0d65883f9f64

## Description
I am trying to upgrade my personal 1.4.3 instance to 1.5.2, unfortunately migrations fail as shown in the log gist above. The server runs Postgresql 10.5; I couldn't find any similar issue here (although I admit I could have missed it.)

Let me know if I can provide anything more to help with debugging.

**Comment by barthalion** [comment]
It worked, thank you!

**Comment by lunny** [comment]
Is this still a problem?

**Comment by barthalion** [comment]
Upgrade from 1.5.x to 1.6 worked fine, no idea about 1.4 → 1.6.
