### ISSUE TITLE
FR: Create pull request comment via API

### ISSUE THREAD

**Issue by marvincaspar** [go-gitea/gitea#5060]
## Description

In our CI/CD pipeline we use a static code analysis and I want to create a job, which creates comments on a pull request file if there is a code smell. 

I didn't find any API call for this action.

**Comment by jmls** [comment]
On a more general note - surely it would be better practice to "eat your own dog food" and make the gitea UI only use publicly available api calls ? That way any shortcomings in the api would be exposed very quickly.

There are several instances where the api does not have the same functionality as the UI - yet the UI *has* to be calling some rest endpoint

**Comment by andrzejressel** [comment]
@mc388 You can use issue comment api for that: https://try.gitea.io/api/swagger#/issue/issueCreateComment

I've just checked that and it works fine.

**Comment by lunny** [comment]
@jereksel I think he means comment on code lines on pull request review.

**Comment by marvincaspar** [comment]
Thats right @lunny

**Comment by 6543** [comment]
@marvincaspar can we close this in faifour of https://github.com/go-gitea/gitea/issues/5733
