### ISSUE TITLE
./gitea without 'web' ignores commandline flags

### ISSUE THREAD

**Issue by coolaj86** [go-gitea/gitea#5065]
Bug
===

Command line flags are ignored when run without `web`, even though the `CmdWeb` Action is taken.

```
./gitea web -p 2000
```

```
./gitea -p 2000
```

The default behavior should probably either be to print the help message or to find a way to shim and run `./gitea` as if it had been run as `./gitea web`.

https://github.com/go-gitea/gitea/blob/master/main.go#L52

Proposal
=======

I vote `./gitea` should be have as `./gitea help`. Thoughts?

**Comment by lafriks** [comment]
it did show help by default previously but was change some time ago to current behaviour

**Comment by coolaj86** [comment]
Both a proposal AND a **bug**.

If it's going to do what it's doing now, we probably should make it work consistently.
