### ISSUE TITLE
Cloning/pulling/pushing fails multiple times before succeeding

### ISSUE THREAD

**Issue by chipsenkbeil** [go-gitea/gitea#5067]
- Gitea version (or commit ref): fc0001c
- Git version: 2.19.0
- Operating system: Mac 10.13.6 (client); Docker using gitea/gitea:latest image (server)
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist: ???

## Description

I'm running Gitea through Docker behind [jwilder/nginx-proxy](https://github.com/jwilder/nginx-proxy). I've exposed port 22 of the Gitea as port 2222 on my server and added my public key to my Gitea account.

Gitea is configured to work with postgres (also in a Docker container) and I followed [this doc](https://docs.gitea.io/en-us/install-with-docker/) to get set up via _docker-compose_.

When cloning, pushing, or pulling from my Gitea instance, it fails one or more times before finally succeeding. Is there anything obvious that I should be checking to see why this is happening?

Nothing in the postgres or gitea docker container logs indicate an issue is happening.

## Screenshots

Succeeds on the 4th attempt:

![gitea clone failing](https://user-images.githubusercontent.com/2481802/46769039-6c6e0b00-ccb8-11e8-9faa-c94a5b9c19ad.gif)

Below is me cloning a repo I made on the try.gitea.org website:

<img width="881" alt="screen shot 2018-10-10 at 6 10 41 pm" src="https://user-images.githubusercontent.com/2481802/46769182-eacaad00-ccb8-11e8-8900-93b32bdf286e.png">

To remove any confusion, `gcl` is a git clone alias provided by a zsh plugin I'm using:

<img width="274" alt="screen shot 2018-10-10 at 9 27 30 pm" src="https://user-images.githubusercontent.com/2481802/46775036-62a5d100-ccd3-11e8-8e9f-783a02b54466.png">

**Comment by lafriks** [comment]
Check that you don't have multiple postgresql instances running with same name in same docker network

**Comment by techknowlogick** [comment]
Closing issue. Please open a post in the [forum](https://discourse.gitea.io/) if this is still an issue.
