### ISSUE TITLE
gogs vs gitea

### ISSUE THREAD

**Issue by pjebs** [go-gitea/gitea#5080]
Can you explain the difference between this project and `gogs` (eg features etc)
Also the history behind why `gitea` diverged.

It would be awesome if that info was in the readme so potential users can understand the difference.

**Comment by jonasfranz** [comment]
> Why was gitea forked?

-> https://blog.gitea.io/2016/12/welcome-to-gitea/

Feature comparison: https://docs.gitea.io/en-us/comparison/
