### ISSUE TITLE
Installation on Pi Zero (linux-arm-6) failed with code=exited, status=210/CHROOT

### ISSUE THREAD

**Issue by mcuix** [go-gitea/gitea#5081]
Failed installation og the linux-arm-6 (1.52) on a pi zero, with following error:
```
Process: 8229 ExecStart=/home/git/gitea/gitea web (code=exited, status=210/CHROOT)
 Main PID: 8229 (code=exited, status=210/CHROOT)

```
- Gitea version (or commit ref): 1.52
- Git version: 2.11.0
- Operating system: Pi Zero W- Raspbian GNU/Linux 9.4 (stretch)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ x] Not relevant
- Log gist:

## Description
```
● gitea.service - Gitea (Git with a cup of tea)
   Loaded: loaded (/etc/systemd/system/gitea.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Sat 2018-10-13 10:33:21 UTC; 846ms ago
  Process: 8229 ExecStart=/home/git/gitea/gitea web (code=exited, status=210/CHROOT)
 Main PID: 8229 (code=exited, status=210/CHROOT)
```

**Comment by lafriks** [comment]
Did you add user and working dir environment variables?

**Comment by techknowlogick** [comment]
Closing. If you are still having this problem please open a post in the [forum](https://discourse.gitea.io/)
