### ISSUE TITLE
api/issues: Set custom date

### ISSUE THREAD

**Issue by mappu** [go-gitea/gitea#5084]
- Gitea version (or commit ref): 1.5.2
- Git version: 2.19
- Operating system: Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:

## Description

Hi,

I'm writing an importer for Fossil issues to Gitea issues. The Gitea API allows to create and manage issues, but always with the current date only; it can't create an issue or comment using a past date. This means my importer loses some fidelity.

I would like the option, in the API, to specify a custom date when creating or modifying a ticket. Probably this functionality should only be available to administrators (or repo owners).

**Comment by adelowo** [comment]
Interesting, Github doesn't support a custom date too... https://developer.github.com/v3/issues/#create-an-issue

**Comment by lafriks** [comment]
It should be in internal API that only administrator should be able to call

**Comment by shashvat-kedia** [comment]
@lafriks Can I work on this?

**Comment by lunny** [comment]
@sd1998 Please!

**Comment by 6543** [comment]
I think we should go the way to enhance & integrate things into gitea's own included migration tool instead :) 

so I'll close this for now. If really needed ask for reopen it.
