### ISSUE TITLE
Autolinking commit hashes might break some links

### ISSUE THREAD

**Issue by vbrandl** [go-gitea/gitea#5088]
- Gitea version (or commit ref): 4090204
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes https://try.gitea.io/foobar19/foobar-repo/issues/1
  - [ ] No
  - [ ] Not relevant

## Description

When posting a link, that ends in something that could be a commit hash, the auto linking feature for commit hashes breaks the actual link. I tried with the link [github.com/schemaorg/schemaorg/issues/1912#issuecomment-429827337](https://github.com/schemaorg/schemaorg/issues/1912#issuecomment-429827337) but Gitea will detect it as [github.com/schemaorg/schemaorg/issues/1912#issuecomment](https://github.com/schemaorg/schemaorg/issues/1912#issuecomment), `-` and [https://[gitea instance]/[user]/[repo]/commit/429827337](https://try.gitea.io/foobar19/foobar-repo/commit/429827337). An example of this can be seen in https://try.gitea.io/foobar19/foobar-repo/issues/1.

This only happens for auto detected links. Using the Markdown link syntax `[]()` produces a correct link.

**Comment by lunny** [comment]
duplicated with #5047

**Comment by jhabdas** [comment]
Duplicate of #4435

**Comment by ghost** [comment]
ditto with #4435
