### ISSUE TITLE
Incorrect status is shown on commit detail

### ISSUE THREAD

**Issue by filipnavara** [go-gitea/gitea#5103]
- Gitea version (or commit ref): dd62ca7 
- Git version: 2.8
- Operating system: Windows
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (https://try.gitea.io/filipnavara/test/pulls/1/commits)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

The commit status displayed on the Commits tab on Pull Request is correctly the status reported for the particular commit. When the commit detail is open though the status displayed is taken for the HEAD or master branch, not for the correct commit.

## Screenshots

![image](https://user-images.githubusercontent.com/1764393/47148803-03971c00-d2d2-11e8-8215-05ef6f0f8c2e.png)

![image](https://user-images.githubusercontent.com/1764393/47148821-13166500-d2d2-11e8-878a-4cea7a8f1939.png)

**Comment by ollien** [comment]
Hi,

I'm interested in taking a crack at fixing this. I know this sounds silly, but how are you enabling commit status to begin with? I've scoured for the answer and having a bit of trouble.

**Comment by filipnavara** [comment]
Gitea implements the same API for statuses as GitHub: https://developer.github.com/v3/repos/statuses/

I created the example above by manually calling the API endpoint through Fiddler. There's a Golong API binding for the statuses at https://github.com/go-gitea/go-sdk.

**Comment by filipnavara** [comment]
It is not stale issue, still a very real bug.

**Comment by filipnavara** [comment]
Looks like similar issue as #5649, a PR was submitted for that one.

**Comment by filipnavara** [comment]
Fixed via #5650
