### ISSUE TITLE
PR single comments are not visible on Conversations tab

### ISSUE THREAD

**Issue by filipnavara** [go-gitea/gitea#5105]
- Gitea version (or commit ref): 8db3bdc 
- Git version: 2.8
- Operating system: Windows
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (https://try.gitea.io/filipnavara/test/pulls/2)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

- Go to "Files changed" in PR
- Add comment on a line and submit with "Add single comment"
- Observe that the comment is not visible in the timeline on the Conversations page (https://try.gitea.io/filipnavara/test/pulls/2)

Adding a comment by starting a review and then submitting it with "Comment" button is visible on the Conversations page (eg. https://try.gitea.io/filipnavara/test/pulls/1).

**Comment by jonasfranz** [comment]
This is not a bug, it's expected behaviour. Please try to add "Single Comment" at GitHub. It won't show up at the timeline.

**Comment by filipnavara** [comment]
@JonasFranzDEV Definitely not true. I tried it now - https://github.com/filipnavara/test/pull/1.

**Comment by jonasfranz** [comment]
@filipnavara At the time the feature got developed, this was not true. But I don't know if we want to go with GitHub's solution because it results in having no difference between Comments inside a Review (type Comment) and Code comments.

**Comment by jonasfranz** [comment]
@filipnavara Please have a look at the 4. TODO item at #3748 

An option for solving this issue might be to automatically create a review if a single comment gets added. But we should discuss if we want this actually since it bloats the timeline.

**Comment by filipnavara** [comment]
It's been working like that in GitHub for at least a year and I use it all the time. Sometimes it's delayed by few seconds due to some infrastructure issues, but it always showed up. The problem is that there's no way whatsoever to tell that someone has commented on the code without actually going to the code and scrolling down.

Note that GitHub also has the notion of commenting on specific commit, which IIRC, didn't show up on the PR.

**Comment by jonasfranz** [comment]
@filipnavara E-Mail notifications will be sent. But I see your point and I propose to add this functionality to "Add single comment".

**Comment by filipnavara** [comment]
E-mail notifications are great if they are enabled, which was not the case for us. ;-)

**Comment by filipnavara** [comment]
Apparently even single comment on a specific commit in a PR still shows up on GitHub now (https://github.com/filipnavara/test/pull/2), but I am fairly certain that was not always the case or that I hit some edge cases where it was not included in the conversation.

**Comment by andreymal** [comment]
I think it's an important feature. It's very easy to miss a helpful or important comment without it. The GitHub behavior does not matter here.

**Comment by lakesare** [comment]
As a side note, - right now Github does always show single comments, but it's true that it can get delayed, e.g. one of my comments got delayed 18 minutes.

**Comment by lafriks** [comment]
I agree that single comment should show just like review comment
