### ISSUE TITLE
HTTP Error 500 when publishing openid url

### ISSUE THREAD

**Issue by simmstein** [go-gitea/gitea#5106]
- Gitea version (or commit ref): 1.5.0
- Git version: 2.1.14
- Operating system: Debian GNU/Linux Jessie
- Database:
  - [ ] PostgreSQL
  - [x] MySQL (5.5.60-0+deb8u1)
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

```
2018/10/18 16:26:18 [I] [SQL] update user_open_id set show = not show where id = ? []interface {}{3}
2018/10/18 16:26:18 [...g/security_openid.go:120 ToggleOpenIDVisibility()] [E] ToggleUserOpenIDVisibility: Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'show = not show where id = ?' at line 1
```

## Description

After I added my OpenID access using my configuration panel (Profil / Configuration / Security), I wanted to publish on my public profile the OpenID URL. After clicking on the button, I see a HTTP Error 500.

## Screenshots

![](https://upload.deblan.org/u/2018-10/5bc89a07.png)

**Comment by filipnavara** [comment]
Hmm, seems to be issue with "show" being a keyword in MySQL and not being quoted in the SQL syntax.

**Comment by filipnavara** [comment]
I guess changing this line:

https://github.com/go-gitea/gitea/blob/801843b0115e29ba2304fa6a5bea1ae169a58e02/models/user_openid.go#L96 

to something like `x.Exec("update user_open_id set \"show\" = not \"show\" where id = ?", id)` should help.

**Comment by filipnavara** [comment]
@strk I will be happy to submit a PR, but I cannot test it properly since I don't have MySQL setup at the moment.

**Comment by strk** [comment]
On Thu, Oct 18, 2018 at 06:32:43PM +0000, Filip Navara wrote:
> @strk I will be happy to submit a PR, but I cannot test it properly since I don't have MySQL setup at the moment. 

There are integrations tests running as part of the testsuite,
maybe you could try to add tests for OpenID usage ?
(challenging task, mind you!)

**Comment by strk** [comment]
also I guess @simmstein would be up to test your PR ?

**Comment by simmstein** [comment]
Of course! I just need a binary beause it's the way I choose to use gitea.
