### ISSUE TITLE
Run multiple Gitea pods in Kubernetes

### ISSUE THREAD

**Issue by abulfatmasimov** [go-gitea/gitea#5108]
- Gitea version (or commit ref): 1972383
- Git version: 2.15.2
- Operating system: Linux
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

We would like to know if running multiple Gitea instances inside Kubernetes is supported. We managed to scale it up to run in multiple pods by pointing to the same database and using shared Kubernetes volume amongst pods via pointing paths in Gitea configuration to the shared volume. I do not see any problems so far, but would like to know what would be potential issues we could face with running multiple instances which share same database and storage.

**Comment by BetaCat0** [comment]
Hi @abulfat-masimov . Here's one problem you should care about so far is that the SSH key storage problem under multi-instance. Generally SSH public keys are stored in `/data/gitea/ssh` directory when using system based SSH tool. That may rasie an unexpected authorzation error using SSH for operations. I suggest enabling Gitea build-in SSH server by specifing `START_SSH_SERVER = true` and also change the `SSH_LISTEN_PORT` in `[server]`  config part (still use default `SSH_PORT = 22` for serving). You can take a look at [Complete List](https://github.com/go-gitea/gitea/blob/master/custom/conf/app.ini.sample)  for more infomation . Hope this can help.

**Comment by Sluggerman** [comment]
great, thanks @techknowlogick! I'll reach out to them to ask if they have Gitea running in scaled mode.

**Comment by bogdanpetrea** [comment]
@techknowlogick: That article is about dropping the SFTP support and unfortunately it's about running a single instance of Gitea in a non-Kubernetes environment. We are currently working on running Gitea on Kubernetes, but we decided to have multiple Gitea instances, logically separated from each other. That's not really the scaling you are probably looking for.

**Comment by abulfatmasimov** [comment]
I guess even if we manage to forward write traffic (POST,PUT) to a single Gitea instance to mitigate risks with corruption, yet it will not be scalable solution as such. I think If something like pessimistic  locking could be implemented in Gitea to support simultaneous writes, that would be a real game changer.

**Comment by lunny** [comment]
@feluxe I think 3) is unnecessary. 4) needs some codes change.

**Comment by BetaCat0** [comment]
@feluxe This looks like somekind of a master-replica solution. As @abulfat-masimov said, it still needs a R/W router to avoid risks of corruption and may not alleviate the writing pressure of main instance (potential SPOF problem).

**Comment by jfelten** [comment]
I've been thinking about this, but lack understanding of where the resource conflicts might be.   I think the best way would be to use a stateful set that uses a common queue service for write requests.  A lot would depend on the type of file storage and persistence, but I believe postgres at least can be fed from a queue.  Other than that you could have a stateful set with db replication set up somehow and fancy file storage that handles concurrency for you.  I created a helm chart for gitea but it only uses a single replica, which is enough for our usage.

**Comment by schmitch** [comment]
actually the biggest problem is that redis-ha is not supported.
I mean you can run a redis service of your cloud provider. but you can't use redis-ha helm chart since redis clients need to be sentinal aware.

**Comment by benyanke** [comment]
What's the current state of this? I'm currently considering setting up Gitea for a production environment, and curious if fully HA mode is supported yet.

**Comment by DhavalW** [comment]
Hello, this issue seems to have auto closed. Has it been implemented ?
I'm considering Gitea for production use as well and would like to know if thats a good idea.

**Comment by lunny** [comment]
I think you can follow @feluxe 's comment.
