### ISSUE TITLE
Reaction-emojis should not have a human skin colour

### ISSUE THREAD

**Issue by tastytea** [go-gitea/gitea#5130]
- Gitea version (or commit ref): dea3d84
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes
  - [ ] No
  - [ ] Not relevant

## Description

The thumbs-up and thumbs-down emojis currently have a human skin colour, whereas the faces are in "smiley-yellow". The thumbs should be in that same yellow.

## Screenshots

![screenshot_2018-10-20t17 46 33](https://user-images.githubusercontent.com/3681516/47257587-5e21ab00-d47f-11e8-989b-c171e4b9b77d.png)

**Comment by lafriks** [comment]
We should switch to twemoji to achieve this. Probably also moving the parsing emoji tags and converting to image tags in golang side

**Comment by Dmole** [comment]
Should gitea not stick to utf8 and let the web browser decide what it looks like? ( Internet Explorer has pigment neutral emoji)  ... at least use a custom font for vector instead of rasterizing them.

**Comment by tankerkiller125** [comment]
@Dmole if you use UTF-8 and let browsers decide how things look some emoji can get extremely confusing as each browser has a different emoji setup and some companies have imagined some emojis differently than others, I can't think of an example off the top of my head but I know that there are several emoji where on one phone it portrays happiness and on the other it looks angry/sad

**Comment by tastytea** [comment]
Are bots deciding what an important issue is and what is not? Did you have a discussion about the ethical implications? Where can I read it?

**Comment by techknowlogick** [comment]
@tastytea It was discussed in the maintainers chat channel, as well as you can find the PR for it here: https://github.com/go-gitea/gitea/pull/5243

It is being used as a tool to help the maintainers to ping issues that may need feedback. We have been able close several issues that needed to be closed, but were just forgotten. As well, it reminded some maintainers of open PRs that could easily be merged. Some issues that stalebot ping'd should remain open, and we've been able to keep them open, so a maintainer is still making a final decision.

**Comment by tastytea** [comment]
Since I know next to nothing about go or web development, I have resorted to a hotfix for now: Overwriting the 6 reaction-emojis with Twemojis. If you want to do the same you need to download:

* [1f44d.png](https://github.com/twitter/twemoji/blob/master/assets/72x72/1f44d.png) as `thumbsup.png`
* [1f44e.png](https://github.com/twitter/twemoji/blob/master/assets/72x72/1f44e.png) as `-1.png`
* [1f606.png](https://github.com/twitter/twemoji/blob/master/assets/72x72/1f606.png) as `laughing.png`
* [1f615.png](https://github.com/twitter/twemoji/blob/master/assets/72x72/1f615.png) as `confused.png`
* [2764.png](https://github.com/twitter/twemoji/blob/master/assets/72x72/2764.png) as `heart.png`
* [1f389.png](https://github.com/twitter/twemoji/blob/master/assets/72x72/1f389.png) as `tada.png`

And then copy the files to `public/vendor/plugins/emojify/images` before compiling.

![screenshot_2019-10-30T13-30-03](https://user-images.githubusercontent.com/3681516/67858432-09dcec80-fb11-11e9-9bd5-10d86e827737.png)

**Comment by Dmole** [comment]
UTF8:
👍 👎🙂🙁💓🎉

**Comment by PopeRigby** [comment]
I'd support using Twemoji
