### ISSUE TITLE
Connect gitea to go-git

### ISSUE THREAD

**Issue by pjebs** [go-gitea/gitea#5135]
Is there someway for gitea to use go-git: https://github.com/src-d/go-git as it's backing git service?

**Comment by lafriks** [comment]
It is planned and is WIP already

**Comment by pjebs** [comment]
https://github.com/go-gitea/gitea/issues/5138 seems to contradict the response here.

**Comment by lafriks** [comment]
@pjebs no it does not, in one you asked if it is possible to configure in this if we could use it. Yes we can and will use it but that requires rewrite :)
