### ISSUE TITLE
Add Gitea to kubernetes chart repository

### ISSUE THREAD

**Issue by ekozan** [go-gitea/gitea#514]
For Tracking 

I'll make a Pr on this repo for install script configurable with envariable ;) 

https://github.com/kubernetes/charts/pull/346

**Comment by tboerger** [comment]
Looks like you are using the vanilla app.ini, but we got a customized app.ini within our docker container.

**Comment by ekozan** [comment]
Yeah i know, i'll use it :) 


They are any way to use env var for automatique configuration ? or i need to make an script on S6 ?

**Comment by tboerger** [comment]
Currently it's not possible to configure Gitea via env variables.

**Comment by sapk** [comment]
Does #2201 implement enough env variable for config to fix this ?

**Comment by lunny** [comment]
@ekozan why close this?
