### ISSUE TITLE
FireFox U2F Dongle Not Detected

### ISSUE THREAD

**Issue by gudenau** [go-gitea/gitea#5143]
- Gitea version (or commit ref): 1.5.2
- Git version: 2.11.0
- Operating system: Debian Stretch
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite3
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

When attempting to add a [YubiKey](https://www.yubico.com/) with FireFox it reports that it is not supported. I have it enabled in about:config, `security.webauth.u2f;true`.

## Screenshots
![image](https://user-images.githubusercontent.com/5642329/47329098-0fb80c00-d639-11e8-92a1-c772c1892320.png)

**Comment by jonasfranz** [comment]
When do this alert appears? Instant, when you click on your key or after approx. 30 seconds?

Did you installed the drivers for your "YubiKey"?

**Comment by gudenau** [comment]
Sorry, was preoccupied.

The drivers are loaded, this is Linux and it works on GitHub. That message appears as soon as you hit the add button.

**Comment by gudenau** [comment]
Firefox v63.0 (64-bit)

YubiKey NEO and YubiKey 4 I think.

**Comment by nogweii** [comment]
Firefox 61+ uses WebAuthN, which is different from the U2F Javascript API that Chrome introduced. I haven't taken a look through Gitea's code, but that might be why it doesn't detect the security key - it uses the older (deprecated) API rather than the newer standardized one.

**Comment by lafriks** [comment]
Works for me with YubiKey 5 on both Firefox 63 and Chrome on Windows and Linux

**Comment by rugk** [comment]
I can confirm it works on try.gitea.io as expected with Firefox and Fedora 29 here. (with `security.webauth.u2f` enabled obviously – as it has been said the new WebAuthn API is not yet supported by Gitea)

**Comment by tamalsaha** [comment]
I am seeing the same error on Ubuntu 18.04 + Chrome 71.0.3578.98 . 

![u2f-chrome](https://user-images.githubusercontent.com/94814/51084995-d0550500-16e7-11e9-9000-98ff3798a612.png)

**Comment by rugk** [comment]
@tamalsaha Did you enable `security.webauth.u2f` in `about:config` in Firefox?

Otherwise it won't work, as gitea still uses the legacy u2f API, instead of WebAuthn.

**Comment by tamalsaha** [comment]
I am using Chrome. I can use U2F with Google services from this same Chrome installation.

**Comment by rugk** [comment]
Sorry, but this issue here is about Firefox. Better create a new issue then, if you encounter problems.

**Comment by tamalsaha** [comment]
Thanks.  I have filed #5720

**Comment by rugk** [comment]
No bot, this is still an issue. And it will be. It's a bug, after all…

**Comment by bricewge** [comment]
Just to report that I had the same issue when using Firefox Nightly 64.0a1 (2018-09-09) with a Yubikey NEO and enabeling `security.webauth.u2f`, as @rugk recommended, fixed it.

**Comment by 6543** [comment]
@gudenau does it still not work ?
mine work fine ...

**Comment by foggy1** [comment]
Confirmed that this is still an issue as pictured above on Firefox 70.0.1 on Manjaro Linux as well as latest Firefox developer addition on MacOS (latest Catalina). I have `security.webauth.u2f` set to true and use it on many other sites.

**Comment by lunny** [comment]
I'm using Firefox(72.0.1) on macOS(10.14.5) . It's OK for me.

**Comment by sapk** [comment]
Do you use gitea under a subpath ? (like found in https://github.com/go-gitea/gitea/issues/10231#issuecomment-584836417)

**Comment by 6543** [comment]
@gudenau whats your current version of gitea you use?
