### ISSUE TITLE
Emojis not rendering in Repo view or Commit view

### ISSUE THREAD

**Issue by tonysgi** [go-gitea/gitea#5150]
- Gitea version (or commit ref): 2ce72d4 
- Git version: 2.15.2
- Operating system: Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes https://try.gitea.io/tonysgi/EmojiTest/src/branch/master
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
In the repo listing, any commit comments are not rendering the emoji in the code listing although it renders the emoji on the last commit comment at the top of the listing.  Browsing the commit itself shows the emoji also not rendering in the commit comment header.  See screenshots.
...

## Screenshots

![image](https://user-images.githubusercontent.com/1932681/47375851-36b92100-d6bf-11e8-9c2f-5f37fae3d56d.png)

![image](https://user-images.githubusercontent.com/1932681/47375894-52242c00-d6bf-11e8-88b0-bb6a44c12369.png)

**Comment by jamesa** [comment]
I'd like to take a crack at this.
