### ISSUE TITLE
As a new user, the heatmap does not render until you have submitted the first commit.

### ISSUE THREAD

**Issue by tonysgi** [go-gitea/gitea#5151]
- Gitea version (or commit ref): 2ce72d4 
- Git version: 2.15.2
- Operating system: Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes - Create a new user to see bug
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
As a new user, the heatmap does not render until you have submitted the first commit.  Until that happens, it is perpetually displaying the "heatmap.loading" icon.

## Screenshots
![image](https://user-images.githubusercontent.com/1932681/47377120-703f5b80-d6c2-11e8-9470-96ca1c6a16d1.png)

_Originally posted by @tonysgi in https://github.com/go-gitea/gitea/pull/5131#issuecomment-432329383_

**Comment by kolaente** [comment]
Normally it shouldn't show "heatmap.loading", there should be a text. 

I think it doesn't load because the API returns `null` if the user has no actions yet, which the js library then fails to parse. I'll submit a patch tomorrow

**Comment by sapk** [comment]
@kolaente I already proposed a fix. You are right, it is because the array is not init (in the api reply) and the json representation is `null` not `[]`.

**Comment by kolaente** [comment]
@sapk Great! Thanks!
