### ISSUE TITLE
Where do git repos get stored

### ISSUE THREAD

**Issue by pjebs** [go-gitea/gitea#5155]
If I was to deploy this on a server, would I be able to recreate the "Github" experience?

Where and how do the repos get stored? Are they just folders in the host's filestructure with `.git` directories?

What is the best process to backup all the repos on a regular basis?

**Comment by adelowo** [comment]
The path to your git repos can be configured in the config file, See repository in https://docs.gitea.io/en-us/config-cheat-sheet/ 

As for backing up, there is the `dump` command, So you run `gitea dump`  ( https://docs.gitea.io/en-us/backup-and-restore/ )

**Comment by pjebs** [comment]
Do you think github will be doing this technique. It seems to hinder scaling gitea horizontally.

**Comment by lunny** [comment]
You could use a distributed file system but mount them on the server.

**Comment by pjebs** [comment]
Are you talking about something like Elastic Block Service (AWS)?
