### ISSUE TITLE
api request url for dependencies in issues is wrong

### ISSUE THREAD

**Issue by nitwhiz** [go-gitea/gitea#5156]
- Gitea version (or commit ref): 1.6.0-rc1
- Git version: 2.17.1
- Operating system: Ubuntu Server 18.04 x64
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

I'm hosting gitea in a subfolder called `/gitea/` via Apache (Reverse)Proxy.

Therefore my api base url is `/gitea/api/v1`. Now on searching issues with the provided input it queries `/api/v1/repos/gitea/<user>/<repo>/issues?q=...` - which of course 404s.

It should be `/gitea/api/v1/repos/<user>/<repo>/issues?q=...` instead.

**Comment by nitwhiz** [comment]
@kolaente made this feature possible AFAIK

**Comment by kolaente** [comment]
Yeah, maybe I forgot to pay attention to the base path, I'll look into this tomorrow.

**Comment by nitwhiz** [comment]
**Simple workaround while this isn't resolved**

In apache config:
```
Redirect /api/v1/repos/gitea/ /gitea/api/v1/repos/
```

**Comment by kolaente** [comment]
PR is up: #5247
