### ISSUE TITLE
Merge conflict resolution, Revert specific commits or a merge request, Cherry-picking changes

### ISSUE THREAD

**Issue by pjebs** [go-gitea/gitea#5158]
In the https://docs.gitea.io/en-us/comparison/ page, it says those 3 features are not implemented.

I was wondering whether it was purely a UI factor why they are aren't implemented given that GitLab CE is open-source and contains those features?

**Comment by lunny** [comment]
@pjebs  Just because currently no people are working on that. I think it's important and should be implemented.

**Comment by sebastianmacias** [comment]
@lafriks thanks for reopening this

**Comment by 6543** [comment]
this are multible feature requests ... so I'll split this up to handle this independent of each ... another

**Comment by 6543** [comment]
and ther revert is in  #8448 and #6375

**Comment by lunny** [comment]
@6543 Please add a check list to track these issues.

**Comment by 6543** [comment]
@lunny its @pjebs issue so i can't do that ...

**Comment by delvh** [comment]
As I've just noticed this issue (because of #20905), two thirds of the issue are already implemented by now: 
![image](https://user-images.githubusercontent.com/51889757/185810399-1d66b76d-b369-420a-bd7a-e89e3c4dc33b.png)
I'd say the remaining part is already #9014, so this issue can be closed.
