### ISSUE TITLE
When pushing commits, an error log displayed always

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#5159]
Gitea version: master
Database: sqlite
Output: stderr
Push: git-external-ssh

When pushing commits, an error log displayed always:

[.../runtime/asm_amd64.s:1333 goexit()] [E] updateRepoIndexer: exit status 128 - fatal: git cat-file 347c00beb4f51bb2a7b4aeb6b6700e7ca2900086: bad file

**Comment by HoffmannP** [comment]
Which version are you using?
Where do you see this error? Is it in a log file, the gitea stdout/stderr or part of the git-ssh/http-response?
I can't confirm it.

**Comment by lunny** [comment]
@HoffmannP I can reproduce that and I will investigate it.
