### ISSUE TITLE
Heatmap on arc-green theme looks out of place

### ISSUE THREAD

**Issue by atomicptr** [go-gitea/gitea#5164]
- Gitea version (or commit ref): 2ce72d4
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant

## Description

As you can see in the screenshot below the heatmap doesn't look like it probably should when using the arc-green theme.

## Screenshots

![image](https://user-images.githubusercontent.com/674705/47425595-16569880-d78b-11e8-9632-bd2044344132.png)

**Comment by SagePtr** [comment]
I think heatmap should use different transparency of green rather than gradient from white to green.

**Comment by sapk** [comment]
The libs seems to support custom gradient. The colorRange option could be a ui option of gitea to set along the theme.
https://github.com/DKirwan/calendar-heatmap
