### ISSUE TITLE
Admin Config -> Session Info missing a data row

### ISSUE THREAD

**Issue by issmirnov** [go-gitea/gitea#517]
- Gitea version (or commit ref): 1.0.0 (6aacf4d)
- Operating system: Ubuntu 14.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X] No (no admin access)
  - [ ] Not relevant

## Description

There is a missing row of data under Admin Panel -> Configuration -> Session Configuration

![image](https://cloud.githubusercontent.com/assets/5771615/21505776/5acbba3c-cc1f-11e6-99cd-5315a567933e.png)

It seems "session provider" or "provider config" is missing data, hence all rows are shifted up.

**Comment by lunny** [comment]
No. That's PR will partially resolve #484 not this one.
