### ISSUE TITLE
Support Access Token when performing git operations

### ISSUE THREAD

**Issue by gastaldi** [go-gitea/gitea#5175]
- Gitea version (or commit ref): 1.6
- Git version: 2.19.0
- Operating system: Fedora
- Database:
  - [x] PostgreSQL
  - [] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant

## Steps to reproduce:

1. Create an access token in your account 
2. Create a private repository
3. git clone https://try.gitea.io/user/your_private_repo
- Username: user
- Password: Your Access Token
4. Perform some changes and `git commit`
5. `git push`
- Username: user
- Password: Your Access Token

You should see an Authentication Failed error

## Description
GitHub supports authentication using a Personal Access Token as the password (which means that when performing a git push, I can specify my token as the password). 
https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/#using-a-token-on-the-command-line

Gitea also supports Access Tokens. It would be nice if I could use the API token as the password when running `git push`.

**Comment by lafriks** [comment]
I think this should be already possible

**Comment by gastaldi** [comment]
@lafriks it seems that the problem is that an admin cannot push to any repository. Is there any way to bypass that?

**Comment by gastaldi** [comment]
This is the scenario I am facing:
- Having two users: Alice and Bob. Alice is Admin, Bob is a normal user. 
- Alice generates an Access Token and creates a repository under Bob's account using the [Sudo support](https://docs.gitea.io/en-us/api-usage/). 
- Now Alice wants to push content to this repository. `git clone` succeeds but `git push` fails with `User permission denied`

**Comment by gastaldi** [comment]
Seems to be a duplicate of https://github.com/go-gitea/gitea/issues/4292

**Comment by gastaldi** [comment]
Closing it, since #4292 seems to be the problem I am facing
