### ISSUE TITLE
API should list commits

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#5181]
This is a feature request for the API to support more details for reporting. I would like to access:
- List commits (just like [GitHub](https://developer.github.com/v3/repos/commits/#list-commits-on-a-repository))

This would enable reporting integration to query the api to determine, over a period:
- number of commits in a repo

splitted from #760

**Comment by HoffmannP** [comment]
I'm currently working on it (only the GET-Part b/c see following:)
The CommitAPI depends on the TreeAPI so I woun't be able to fully implement it until #4185 is done.
POSTing a commit will be absolutely postponed until the TreeAPI is done as it doesn't make sense to create an commit without a tree object.

**Comment by HoffmannP** [comment]
First steps are done: https://github.com/HoffmannP/gitea/commit/df6edc54c9da4af6ea6a3a64c2fe86039a728485

**Comment by richmahn** [comment]
@HoffmannP #4185 has been merged and closed, so it is done.

**Comment by sapk** [comment]
The github api style is done in #6408.
