### ISSUE TITLE
Several heatmap problems

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#5191]
- Gitea version (or commit ref): aeb5655
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes
  - [ ] No
  - [ ] Not relevant
## Description

1. The Heatmap doesn't display even it's not on mobile screen size (heatmap needs 1200XN to show)

2. Flicker glitch
![1](https://user-images.githubusercontent.com/2960293/47548963-86a11d80-d935-11e8-8a11-31b1a01d271b.gif)

3. Months are overlapping each other (Related: https://github.com/DKirwan/calendar-heatmap/issues/18)
![2](https://user-images.githubusercontent.com/2960293/47549365-c4eb0c80-d936-11e8-83c6-4dfb7b338deb.png)

4. Days are not correct
![3](https://user-images.githubusercontent.com/2960293/47556943-81020280-d94a-11e8-9ae8-3d889649a9aa.png)

**Comment by lunny** [comment]
@kolaente It's better to send PRs to upstream.
