### ISSUE TITLE
License Question - Removing Footer

### ISSUE THREAD

**Issue by rs-development** [go-gitea/gitea#5197]
## Description

Is it okay to remove the links to used libraries and their licenses from the footer?

**Comment by sapk** [comment]
Since some are MIT license, I would say no (example: https://github.com/moment/moment/blob/develop/LICENSE)

**Comment by clarfonthey** [comment]
I think the first immediate question is when and why you want to do this. Because if you're the only user of the instance, it's probably fine. Otherwise it gets complicated.

**Comment by rs-development** [comment]
I was reworking it and it came up to my mind. So it will stay where it is right now :+1: 

Thank you very much
