### ISSUE TITLE
Can't login with SMTP authentication

### ISSUE THREAD

**Issue by joubertredrat** [go-gitea/gitea#52]
Hi guys, 

Same issue here, if user already exists on base, login normal, but if doesn't exist user, get error on login.
```
[Macaron] 2016-11-01 14:42:07: Completed /user/login 500 Internal Server Error in 1.364496ms
```
Reference: https://github.com/gogits/gogs/issues/3824

**Comment by joubertredrat** [comment]
Strange, on my Gogs in production, have this issue, but on my fork of Gitea is working without problems, I will try test with Gitea master branch.

**Comment by lunny** [comment]
Does Gitea master branch have the bug?

**Comment by joubertredrat** [comment]
@lunny Tested with Ubuntu 16.04 in Digital Ocean and compiled from source, worked fine. I think that can be closed this.

**Comment by lunny** [comment]
OK. Just close now. Please feel free to reopen it if you find further information.
