### ISSUE TITLE
Integration test for MySQL is not configured correctly

### ISSUE THREAD

**Issue by typeless** [go-gitea/gitea#5204]
Not sure if it is deliberate or not, the `test-mysql` tag in `.drone.yml` is declared twice. As a result, it seems that the integration test for MySQL does not run. What has been run is actually `make integration-test-coverage`.

**Comment by techknowlogick** [comment]
One is only run when the branch is master, and the other is run several other cases (see `when` part of the yaml for more details).

Now, I'm not sure if that is deliberate (why only mysql in that case), and so I will leave this open in case anyone has insight into it.

Thank you for raising this ticket.

**Comment by lafriks** [comment]
Yes it is intended so as when pushed to master and for pulls it calculate test coverage but for tags not
