### ISSUE TITLE
Make the repository list on the Dashboard site show all repositories

### ISSUE THREAD

**Issue by rs-development** [go-gitea/gitea#5205]
## Description

The repository overview and the right side of the Dashboard is showing only 15 entries.  I'd like to make it show all available repositories. I checked the template file it seems to me there is no option to make it show all repositories.

Any Idea how i could make it show all repos?

## Screenshots
 gitea/templates/user/dashboard/dashboard.tmpl

![image](https://user-images.githubusercontent.com/35149229/47616880-a0bc3680-dac2-11e8-9008-4b68360c555c.png)

**Comment by HoffmannP** [comment]
https://github.com/go-gitea/gitea/blob/a2ee2a3c67304920a968c1c852e43b3dc2d7c3e7/modules/setting/setting.go#L345 is the line defining the number of repositories loaded. It's currently not easy configurable. Is this something you think shoud be changed? There are hundred of settings in this file so it's realy hard to tell which should be configurable and how.

**Comment by techknowlogick** [comment]
Easily changed (easy, as in no need to recompile), see: https://github.com/go-gitea/gitea/blob/a2ee2a3c67304920a968c1c852e43b3dc2d7c3e7/custom/conf/app.ini.sample#L103

**Comment by rs-development** [comment]
Thank you very much :+1:
