### ISSUE TITLE
play audio files with html5 <audio> tag

### ISSUE THREAD

**Issue by milahu** [go-gitea/gitea#5206]
im abusing gitea for file hosting

gitea does already play mp4 video files
and aac / mp3 audio in mp4 containers
via the html5 &lt;video&gt; tag

please make gitea also play audio files
like opus, vorbis, aac, mp3, flac, wav
using the html5 &lt;audio&gt; tag

[lets just ignore webm, weba, etc
h.264 and opus are my codecs of choice]

see here
https://tools.woolyss.com/html5-audio-video-tester/
for browser support

**Comment by laoshaw** [comment]
how does video tag work? my video tag inside the markdown was ignored, can you give an example?

**Comment by laoshaw** [comment]
@milahu what do you mean by 'open the src page for that file'? I uploaded a few mp4 and would like to play it out of the typical markdown pages at gitea

**Comment by laoshaw** [comment]
the a-href works for mp4 files, what I'm really trying to see if the video tag works in gitea, e.g. in a markdown I can do something like:

`<video style="width:100%" controls><source src="small.mp4" type="video/mp4">Your browser does not support the video tag.</video>`

is this possible at all? tried a while it never worked, no video is shown, in fact in the rendor html page all the video tags and sections are removed, it's like gitea's parser removed any video tags in the markdown file before converting markdown to html for view.
