### ISSUE TITLE
Markdown Image Hyperlinking Error

### ISSUE THREAD

**Issue by hughesjs** [go-gitea/gitea#5207]
- Gitea version (or commit ref): 49d666f
- Git version: N/A
- Operating system: Ubuntu 18.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes (provide example URL) @ https://try.gitea.io/issuetestcase1/issuetest
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

When adding an image with a link using markdown, attempting to open the link opens the image instead.

I copied the discord button on [this repo](https://github.com/izy521/discord.io/blob/master/README.md)'s README to test as it works great on Github but fails on my repo (obviously I change the parameters to match my discord server).

**Comment by jamesa** [comment]
I'd like to try to work on this.

**Comment by LER0ever** [comment]
My PR #4675 would solve this and another similar issue (#4569 ) once it gets merged.
Could you try the patch @hughesjs to see if it works for you?

**Comment by hughesjs** [comment]
Apologies for the late reply, been dealing with some family issues. Can confirm that this has been fixed on the current master build. Thanks guys, great job!
