### ISSUE TITLE
"Preview Changes" on web editor not working

### ISSUE THREAD

**Issue by alpe12** [go-gitea/gitea#5209]
- Gitea version (or commit ref): 1.6.0-rc1
- Git version: 2.17.1
- Operating system: Ubuntu Minimal 18.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist: Nothing unusual. But the post request returns this:

> template: repo/diff/section_unified:1:11: executing "repo/diff/section_unified" at <.file>: can't evaluate field file in type *models.DiffFile

If no change is made to the files, it sucessfully shows "There are no changes to show.", but if something changes, it doesn't work (stuck on "Loading…"), and analyzing the POST request it returns the error above.

I tried:
- Going back to gogs and test there. It works.
- I use it behind a reverse proxy. So, I tried removing this, changing protocol to https and directly accessing it.
- I upgraded from gogs. So I though this could be the problem and temporarly renamed the data/ folder and started new (except for app.conf).
- Tried removing almost all modifications I made to the config.
- Using version 1.6.

I'm out of ideas.

**Comment by alpe12** [comment]
Tested now.
Yes. Using Firefox, IE and Edge on Windows. Same problem.
Tried on another computer too (Ubuntu, Firefox).

**Comment by alpe12** [comment]
Just created this empty file and tried to edit it (and preview).
https://try.gitea.io/alpe12/test/_edit/master/testfile

**Comment by alpe12** [comment]
![](https://user-images.githubusercontent.com/8551127/47682347-d5a3b880-dbaa-11e8-878c-57c1779dceaf.png)

**Comment by theAkito** [comment]
This issue has been resolved.

**Comment by lunny** [comment]
Closed now and feel free to reopen it.

**Comment by lonix1** [comment]
@lunny I also have this problem with dockerised gitea 1.9.1, ubuntu, sqlite, firefox latest.

It just says "Loading..." and doesn't show preview.

The console has this error:

> Failed to load ‘http://localhost:3000/api/v1/repos/bob/techno/markdown’. A ServiceWorker passed a promise to FetchEvent.respondWith() that rejected with ‘TypeError: NetworkError when attempting to fetch resource.’.

And the suspicious thing is that gitea is running on a different port, not the `3000` shown above. And everything else works...

**Comment by lunny** [comment]
@lonix1 That should be your configuration's problem. You can go discord or discourse forum to discuss your problem.

**Comment by lonix1** [comment]
@lunny Thanks for the tip, I found the problem in the config. :+1: 

For anyone else with this problem, please note that the docs don't explain properly. If you are using docker, and you use ports 4000:3000 (for example) instead of the default 3000:3000, then this must be in the config:

````
HTTP_PORT = 3000
ROOT_URL = http://localhost:4000/
````

I thought they must both be equal to the internal docker port, but that is not correct. `ROOT_URL` must be set to the external docker port!
