### ISSUE TITLE
Repo keeps being 'bare' even if it is not

### ISSUE THREAD

**Issue by typeless** [go-gitea/gitea#521]
- Gitea version (or commit ref):
```
$ ./gitea --version
Gitea version 6aacf4d
```
- Git version:
```
$ git --version
git version 2.7.4
```
- Operating system:
```
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.1 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.1 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
```
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

```
$ sudo journalctl -u gitea
```
```
Dec 28 15:24:05 DIR-101 gitea[26904]: [Macaron] 2016-12-28 15:24:05: Started GET /mura/repo-manifests for 192.168.222.65
Dec 28 15:24:05 DIR-101 gitea[26904]: 2016/12/28 15:24:05 [D] Session ID: 18e0d643614cbd89
Dec 28 15:24:05 DIR-101 gitea[26904]: 2016/12/28 15:24:05 [D] CSRF Token: vbaOsqCBITYP1Sg1-JR3E0CfNCOOMTQ4MjkwMTIyMjQ1Mjk2MjkwNg==
Dec 28 15:24:05 DIR-101 gitea[26904]: 2016/12/28 15:24:05 [D] Bare repository: /mura/repo-manifests
Dec 28 15:24:05 DIR-101 gitea[26904]: 2016/12/28 15:24:05 [D] Template: repo/bare
Dec 28 15:24:05 DIR-101 gitea[26904]: [Macaron] 2016-12-28 15:24:05: Completed /mura/repo-manifests 200 OK in 25.286817ms
```

## Description

It shows the 'Quick Guide' page like I had never pushed any file.
I looked into the code by finding the string `Bare repo` and the symbol `IsBare` and found there is not many way to set it to `false` (The expected correct value). Not sure what's going on but literally I can not add any new repo from now on.

P.S. 

1. This can be reproduced with HEAD (f686a32e), 
2. Using SQLite from shell to read `data/gogs.db`, it shows the column `is_bare` of the repo is actually `1`.

```
$ sqlite3 data/gogs.db
```
In SQLite:
```
sqilte> select is_bare from repository where name == "repo-manifests";
1
```
3. It appears that this happens only when `git push` with SSH and HTTP does not exhibit the problem.

**Comment by lunny** [comment]
Hi, I cannot reproduce this. Could you give any further information?

**Comment by typeless** [comment]
@lunny I am trying to diagnose the problem further. Can you enlighten me about where the entry point is when users doing `git push` via SSH?

I suppose it is `gitea serv` (cmd/serve.go) but I am not sure since I didn't see the logging message I added there. 😕

**Comment by lunny** [comment]
Yes, you are right. When push via SSH, `gitea serv` will be invoked. Config file is `~/.ssh/authorized_keys` file. You can find `command="/Users/lunny/gopath/src/code.gitea.io/gitea/gitea serv key-1 ...`, the default log will be write to `log/serv.log`. And notice don't print anything to console.

**Comment by bkcsoft** [comment]
Push via SSH does through `cmd/update.go` (called from `.git/hooks/update` :)

**Comment by typeless** [comment]
It turns out this is caused by `~/.ssh/authorized_keys` which has to be regenerated. (Thanks Denis Denisov @denji). 

This can be closed.
