### ISSUE TITLE
fatal: Could not read from remote repository.  Please make sure you have the correct access rights and the repository exists.

### ISSUE THREAD

**Issue by symgryph** [go-gitea/gitea#5211]
[gitea.service.txt](https://github.com/go-gitea/gitea/files/2523460/gitea.service.txt)
- Gitea version (or commit ref):
- Git version: 2.19.0
- Operating system: Centos 7.5
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:
https://gist.github.com/symgryph/521309620e2a236c4d113d725ae8569b
## Description
I am unable to clone private repos via ssh. It works fine over https, or if I use the 'internal' ssh that comes with gitea. I can get into the system, log things etc, but alwas get the titel for my error. The file exists in proper directory, and the git user has write/read access to the repo.

I am using an attched systemd service file to start gitea as a non root user. Gitea is fronted by a caddy proxy (web stuff is fine).
[gitea.service.txt](https://github.com/go-gitea/gitea/files/2523462/gitea.service.txt)

[app.txt](https://github.com/go-gitea/gitea/files/2523447/app.txt)
[sshd_config.txt](https://github.com/go-gitea/gitea/files/2523450/sshd_config.txt)

...

**Comment by lunny** [comment]
Could you try `ssh -vvv ...` to give more logs?

**Comment by symgryph** [comment]
For some reason if you use UpperCaseNames it converts them all to lower case causing the ssh to bork up. If I just use lowecase everything works. Verified that this is a bug, since I created a new repo and used camel case, the ssh directory was all lower case.

**Comment by symgryph** [comment]
Figured it out NOT camel case. You can't set git's user as /bin/false you HAVE to allow for logins.....
