### ISSUE TITLE
Dashboard heatmap always loading on mysql 8

### ISSUE THREAD

**Issue by gaydin** [go-gitea/gitea#5220]
- Gitea version (or commit ref): d4e62787644bf08e5044b7aeb36c0080cd892fef
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

https://gist.github.com/gaydin/ee00f012fbefe913daa53a98c0c55f1c

## Description
Maybe need changed 
https://github.com/go-gitea/gitea/blob/master/models/user_heatmap.go#L26
```UNIX_TIMESTAMP(DATE_FORMAT(FROM_UNIXTIME(created_unix), '%Y%m%d'))```
to
```UNIX_TIMESTAMP(DATE(FROM_UNIXTIME(created_unix)))```

**Comment by kolaente** [comment]
Does this also fail in mysql 5/ mariadb 10?

**Comment by gaydin** [comment]
I tested on MySQL 5.6.37 - work fine. 
Trouble with mysql 8.0.13 only. 
After changing DATE_FORMAT to DATE works fine on MySQL 5.6 and 8

**Comment by sapk** [comment]
@gaydin do you know how to make a PR ? 
If not maybe we could add a label `good first issue` to attract new contributor ?
