### ISSUE TITLE
Topics are (inconsistently) converted to lower-case

### ISSUE THREAD

**Issue by michael-brade** [go-gitea/gitea#5222]
- Gitea version (or commit ref): 1.6.0-rc.1
- Operating system: Debian unstable
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite

## Description

A stream of inconsistencies regarding case-sensitivity of topics:

* open a repository, select "Manage Topics", type "**API**", press Enter. 
* the topic is now converted to a lowercase "**api**" in a green box.
* now click the "Done" button and watch the green box: it shows "**API**" again! 
* However, don't get your hopes up too soon: reload the current page (F5) and voila: it shows "**api**" again.

What I would expect: keep the topic as it is, don't lowercase or uppercase it.

**Comment by lafriks** [comment]
It is intentionally converted to lowercase to not have problems later and also have compatibility with GitHub (it also lowercases topics)

**Comment by michael-brade** [comment]
See here: https://github.com/go-gitea/gitea/issues/5171#issuecomment-432888248 and here: https://blog.gitea.io/2018/08/gitea-1.5.0-is-released/

I don't agree with "not have problems later", it is easy enough to do case-insensitive comparisons; and I don't mind being different from GitHub where it is possible to do it better than GitHub :smiley:  (better in this case: the user has the freedom to decide)

**Comment by lafriks** [comment]
@michael-brade but than there still be problem anyway as most probably someone will decide in your place. Let's say someone in other org/repo will add topic `ApI` and even if you will try to add `api` or `API` it will still be converted to `ApI` as topics are global to whole server. I agree that there is a bug that it jumps to lowercase, than back to uppercase and than again lowercase but otherwise I think lowecase should be enforced on this.

**Comment by lafriks** [comment]
I don't think that problem is currently present, in database all topics are currently already lowercase so it is only UI bug that needs to be fixed

**Comment by michael-brade** [comment]
I think you misunderstood this one. With clutter I meant items you don't want to see in general, with typos of all sorts you can imagine. Adding uppercase letters doesn't make this kind of clutter worse. The only solution to this would be to limit suggestions to those of the current user/org, but I don't think this would be easy.

BTW: is it possible to delete a topic from the database by removing the last usage of it?

**Comment by lafriks** [comment]
I don't think topics are deleted when not used any more currently. As for being case insensitive I'm against it as it will add clutter and will render them less useful. Especially taking into account if used in future in federation when we get to that.

**Comment by lunny** [comment]
Maybe we should add a whitelist to convert `api` to `API` and etc.

**Comment by lafriks** [comment]
IMHO that is not needed as that will still not cover all

**Comment by michael-brade** [comment]
Ok, I changed it for my own server to case-sensitive. And I have to say, gitea is really good code! It is very easy to find my way around in it and to understand what's going on. Lovely. If anyone is interested, here is the patch that makes Topics case-sensitive:

```go
diff --git a/models/topic.go b/models/topic.go
index 678795a3d..69071a39b 100644
--- a/models/topic.go
+++ b/models/topic.go
@@ -21,7 +21,7 @@ func init() {
        )
 }
 
-var topicPattern = regexp.MustCompile(`^[a-z0-9][a-z0-9-]*$`)
+var topicPattern = regexp.MustCompile(`^[A-Za-z0-9][A-Za-z0-9-]*$`)
 
 // Topic represents a topic of repositories
 type Topic struct {
@@ -127,7 +127,7 @@ func SaveTopics(repoID int64, topicNames ...string) error {
 
                var found bool
                for _, t := range topics {
-                       if strings.EqualFold(topicName, t.Name) {
+                       if topicName == t.Name {
                                found = true
                                break
                        }
@@ -141,7 +141,7 @@ func SaveTopics(repoID int64, topicNames ...string) error {
        for _, t := range topics {
                var found bool
                for _, topicName := range topicNames {
-                       if strings.EqualFold(topicName, t.Name) {
+                       if topicName == t.Name {
                                found = true
                                break
                        }
diff --git a/public/js/index.js b/public/js/index.js
index 0bc28c4f9..5351d4040 100644
--- a/public/js/index.js
+++ b/public/js/index.js
@@ -2523,12 +2523,12 @@ function initTopicbar() {
             },
         },
         onLabelCreate: function(value) {
-            value = value.toLowerCase().trim();
+            value = value.trim();
             this.attr("data-value", value).contents().first().replaceWith(value);
             return $(this);
         },
         onAdd: function(addedValue, addedText, $addedChoice) {
-            addedValue = addedValue.toLowerCase().trim();
+            addedValue = addedValue.trim();
             $($addedChoice).attr('data-value', addedValue);
             $($addedChoice).attr('data-text', addedValue);
         }
@@ -2553,7 +2553,7 @@ function initTopicbar() {
                     rules: [
                         {
                             type: 'validateTopic',
-                            value: /^[a-z0-9][a-z0-9-]{1,35}$/,
+                            value: /^[A-Za-z0-9][A-Za-z0-9-]{1,35}$/,
                             prompt: topicPrompts.formatPrompt
                         },
                         {
diff --git a/routers/repo/topic.go b/routers/repo/topic.go
index 63fcf793f..3fa1205e7 100644
--- a/routers/repo/topic.go
+++ b/routers/repo/topic.go
@@ -30,7 +30,7 @@ func TopicsPost(ctx *context.Context) {
        invalidTopics := make([]string, 0)
        i := 0
        for _, topic := range topics {
-               topic = strings.TrimSpace(strings.ToLower(topic))
+               topic = strings.TrimSpace(topic)
                // ignore empty string
                if len(topic) > 0 {
                        topics[i] = topic
```
