### ISSUE TITLE
[BUG] Due date format issue

### ISSUE THREAD

**Issue by mmarif4u** [go-gitea/gitea#5226]
- Gitea version (or commit ref): 5fc0a12

- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes
  - [ ] No
  - [ ] Not relevant

I guess the following image would explain the issue better.

![capture](https://user-images.githubusercontent.com/1280585/47705779-86b95a00-dc62-11e8-82c0-b0bac20e26ab.PNG)

**Comment by lafriks** [comment]
It is on issue page

**Comment by kanozec** [comment]
But I saw the response of  "https://try.gitea.io/api/v1/repos/{userName}/{repoName}/issues/1/deadline"  in the chrome console is 401

And the request payload is {due_date: "2017-02-17T00:00:00.000Z"}

This issue seems not caused by error formating

**Comment by kolaente** [comment]
@kanocz anything in the logs?

**Comment by kanozec** [comment]
I only have the browser console log.

![screen shot 2018-10-31 at 7 43 44 pm](https://user-images.githubusercontent.com/30459655/47786081-9198eb00-dd45-11e8-9c0b-52a3df4701e5.png)



Actually, I have some trouble to run gitea on my local.

**Comment by kolaente** [comment]
@kanocz What was the response?

Also, if you have problems running Gitea locally, feel free to ask in [our Discord server](https://discord.gg/NsatcWJ) or [the forum](https://discourse.gitea.io/).

**Comment by jamesa** [comment]
This also happens in the Swagger dashboard for the same request.

**Comment by kolaente** [comment]
Looks like this was broken by #4840 (among other things)

**Comment by kanozec** [comment]
@kolaente  Yes, I trace the code and make some experiments. I found that
```golang 
ctx.Data["IsApiToken"] = true
``` 
does not be executed while checking user is signed.

So
```golang
func reqToken() macaron.Handler {
	return func(ctx *context.Context) {
		for  key := range ctx.Data{
			fmt.Printf("Key: %s |Value: %v\n", key, ctx.Data[key])
		}
		if true != ctx.Data["IsApiToken"] {
			ctx.Error(401)
			return
		}
	}
}
```
always gets 401 error.


### #5249 shows the solution to fix this bug

**Comment by kolaente** [comment]
I've opened #5249 to fix this and other issues.

**Comment by nikitasius** [comment]
why this issue is closed?

Problem still here:

![image](https://user-images.githubusercontent.com/3670331/50082569-98929480-01f1-11e9-8f5c-7cbd4e064ccd.png)

on https://try.gitea.io

**Comment by kolaente** [comment]
It looks like it returns an error 500, so maybe some other thing is broken and the error message is just not good...

**Comment by nikitasius** [comment]
Yep, it send a payload:
![image](https://user-images.githubusercontent.com/3670331/50087889-c253b780-0201-11e9-9322-c6c60d2767d0.png)
and receive nothing
![image](https://user-images.githubusercontent.com/3670331/50087911-d13a6a00-0201-11e9-9914-b3b5ad6e3a4d.png)

**Comment by lunny** [comment]
@nikitasius could you confirm that #5250 didn't resolve the issue?

**Comment by nikitasius** [comment]
> @nikitasius could you confirm that #5250 didn't resolve the issue?

Hi, it was on your **official demo**. If you don't see on your official demo same error - guess it's fixed. Just check.
