### ISSUE TITLE
Gitea does not render time string in a dashboard

### ISSUE THREAD

**Issue by Difrex** [go-gitea/gitea#5231]
- Gitea version: e28801f
- Git version: 2.15.3
- Operating system: Debian 8
- Database:
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

Gitea does not render time string in a dashboard. This problem appeared in version 1.4. and reproduces each time when I update the Gitea installation. I use built-in static and run Gitea under docker. You can see that problem at https://gitea.difrex.ru/explore/repos.

## Screenshots

![2018-10-31-115630_364x123_scrot](https://user-images.githubusercontent.com/3982213/47777140-20394800-dd05-11e8-9913-99d53657c294.png)

**Comment by lafriks** [comment]
Can not seem to reproduce that. Are you using custom files for translation or templates?

**Comment by Difrex** [comment]
No, just official statically linked binary in Docker.

My Dockerfile:
```Dockerfile
FROM gitea/gitea:1.6

RUN sed -i 's/1000/999/g' /etc/passwd
RUN sed -i 's/1000/999/g' /etc/group
```

And Nginx config:
```nginx
server {
    ...
    client_max_body_size 512M;

    access_log /var/log/nginx/gitea.log;
    error_log /var/log/nginx/gitea.err;

    error_page 500 502 503 504 /5xx.html;
    location = /5xx.html {
        root /var/www/gitea;
        internal;
    }

    sendfile on;
    send_timeout 300s;
    location /avatars {
        alias /var/lib/gitea/data/avatars;
    }

    location / {
	    proxy_pass http://127.0.0.1:3000;
    }
}
```
