### ISSUE TITLE
500 error creating pull request

### ISSUE THREAD

**Issue by zaaksam** [go-gitea/gitea#5235]
- Gitea version (or commit ref): 31a738b (by docker image gitea/gitea:1.5.2)
- Operating system: macOS 10.14
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ x ] Not relevant

## Description

log:

```
[...routers/repo/pull.go:803 CompareAndPullRequestPost()] [E] GetPatch: signal: killed
```

**Comment by lafriks** [comment]
Could this be memory related?

**Comment by lafriks** [comment]
This would also need more information on how to reproduce this

**Comment by zaaksam** [comment]
I clicked the "NewPullRequest", and then change the "merge into" branch, it happened.

It is normal for others to create PR.

**Comment by dmarov** [comment]
encountered the same issue on FreeBSD 11.1-RELEASE-p13, Gitea version 1.6.4, DB_TYPE  = sqlite3, seems like it is related to particular gitea user
log message:
[...routers/repo/pull.go:734 PrepareCompareDiff()] [E] GetDiffRange: ParsePatch: Unquote: invalid syntax
it disappears after user which creates pull request have been recreated

**Comment by zeripath** [comment]
What is the failing username? Did they have a valid email address?

**Comment by dmarov** [comment]
username: BuldakovIlya, had valid email address

**Comment by zeripath** [comment]
Damn I was hoping the name was pathological somehow. There are several issues that my PR #5774 solved.

**Comment by zeripath** [comment]
@dmarov were you able to ever get this bug to fire for other users, and after recreating the user did it is ever occur again?

Presumably that broken user was created in an earlier version of Gitea?

**Comment by dmarov** [comment]
This bug fired just 2 times since we use gitea, it fired for me and for user I mentioned previously. no other occurencies. After recreating of user it didn't happen again. User was created in earlier version of gitea but now it is up to date.

**Comment by zeripath** [comment]
Ok so I think this might have been a migration related issue. 

If we can't get more information about it I don't think we can do more about it and we should leave this bug closed. 

Hopefully, no one else will have this issue...

**Comment by bkmgit** [comment]
Hi,
Getting this error on Gitea 1.9.3 running on Cent OS 7. It is possible to merge the pull requests using the command line on a different computer, for example following 
* http://www.bartread.com/2014/02/12/git-basics-how-to-merge-changes-from-a-different-fork-into-your-own-branch/
* https://stackoverflow.com/questions/6022302/how-to-apply-unmerged-upstream-pull-requests-from-other-forks-into-my-fork
and then pushing the changes

Specifically, within the main repository one is working in, one can:

    git remote add somefork https://my.gitea.ip:3000/cool/fork
    git fetch somefork
    git checkout master
    git merge somefork/master
    git push

**Comment by lunny** [comment]
@bkmgit please fire another issue.

**Comment by bkmgit** [comment]
@lunny Thanks, done #8351
