### ISSUE TITLE
access repo Home: You are not allowed to access any section of this repository.

### ISSUE THREAD

**Issue by shadowsingle** [go-gitea/gitea#5253]
- Gitea version (or commit ref):
 v1.5.x v1.4.x v1.2.x
- Git version:
git  1:2.11.0-3
- Operating system:
debian 9.5
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:
http://paste.ubuntu.com.cn/4364718

## Description
1、./gitea web
2、 init data and create first users
3、 create repo （jump 404 website ）
4、click repo url the problem is still.

add trace code in view.go
http://paste.ubuntu.com.cn/4364715
and i found the len(ctx.Repo.Repository.Units) is 0 .
but i found the table ([repo_unit ](http://paste.ubuntu.com.cn/4364718)) on database that  can found 5 record.

## Screenshots 
x

**Comment by shadowsingle** [comment]
2018/11/02 12:09:36 [T] home ctx: {Context:0xc209065320 Cache:0xc2084957d0 csrf:0xc20a5bb000 Flash:0xc2094f3220 Session:{RawStore:0xc20a589b80 Manager:0xc20992f0e0} Link:/deepin/dx EscapedLink: User:0xc2090a0200 IsSigned:true IsBasicAuth:false Repo:0xc20972d2b0 Org:0xc209948120} len units: 0
2018/11/02 12:09:36 [T] home repo: {AccessMode:owner IsWatching:false IsViewBranch:true IsViewTag:false IsViewCommit:false Repository:0xc208ca5080 Owner:0xc2090a0200 Commit:0xc20a6211e0 Tag:<nil> GitRepo:0xc20a654ce0 BranchName:master TagName: TreePath: CommitID:a5e79a3f6af912077a13a314d5a2c17920ec22e1 RepoLink:/deepin/dx CloneLink:{SSH: HTTPS: Git:} CommitsCount:1 Mirror:<nil> PullRequest:0xc20a626920}
2018/11/02 12:09:36 [T] home repository: {ID:1 OwnerID:1 OwnerName:deepin Owner:0xc2090a0200 LowerName:dx Name:dx Description:askdjalkdf Website: DefaultBranch:master NumWatches:1 NumStars:0 NumForks:0 NumIssues:0 NumClosedIssues:0 NumOpenIssues:0 NumPulls:0 NumClosedPulls:0 NumOpenPulls:0 NumMilestones:0 NumClosedMilestones:0 NumOpenMilestones:0 NumReleases:0 IsPrivate:false IsBare:false IsMirror:false Mirror:<nil> ExternalMetas:map[] Units:[] IsFork:false ForkID:0 BaseRepo:<nil> Size:0 IndexerStatus:<nil> IsFsckEnabled:false Topics:[] CreatedUnix:1541125852 UpdatedUnix:1541125857}
2018/11/02 12:09:36 [...routers/repo/VIEW.go:306 Home()] [E] Home: You are NOT allowed TO access any section of this repository.
2018/11/02 12:09:36 [D] Template: STATUS/404
[Macaron] 2018-11-02 12:09:36: Completed GET /deepin/dx 404 NOT Found IN 190.167384ms

**Comment by lunny** [comment]
should be fixed by #5314 , close now and please feel free to reopen.
