### ISSUE TITLE
Implement Pull Requests history

### ISSUE THREAD

**Issue by iddm** [go-gitea/gitea#5254]
It would be nice to have history of changes in the pull requests as it is in gitlab, for example: if someone pushes commit with `force`, it would be nice to have diff of what was before this push, so, probably, we should store changes for that and notify user on each push event as in gitlab.

**Comment by singalen** [comment]
Rebase and force-push is a natural workflow of PR that is not accepted immediately.
Of course, one could close one PR and open another one, but it would be much better to keep a history of PR and its reviews.

**Comment by vityafx** [comment]
@lafriks I am not sure I understand what you were saying.

**Comment by lafriks** [comment]
I asked if anyone has ideas on how to store/get previous changes that have been removed from branch by force push

**Comment by vityafx** [comment]
What about storing them in the gitea's database?

**Comment by singalen** [comment]
The question is about the record format, I believe.
I don't have the experience with git database format, but gerrit or gitlab formats should do.

Particularly, each PR version can be saved as a hidden branch; the comments to the commits would be stored the way they are now. 
You may even want to reimplement gerrit's master feature: use or calculate a mapping between different versions of same commit across PR versions in `Change-Id:` field, and display a history of a **commit**.

**Comment by alvardes** [comment]
Actually I just discovered this issue. I think this is the same as the one I opened: #12604. 

The related work in progress pull request is: #12665

**Comment by singalen** [comment]
Yay, thanks a ton!
