### ISSUE TITLE
Clojure .gitignore file is not created properly.

### ISSUE THREAD

**Issue by soulawaker** [go-gitea/gitea#5257]
- Gitea version (or commit ref): 225c489
- Git version: 2.17.1
- Operating system: linux
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)  
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
Clojure .gitignore file is not created properly.
Show the result on URL https://try.gitea.io/abcd785/GitignoreTest/src/branch/master/.gitignore
...

**Comment by sapk** [comment]
It seems that the source file is a link https://github.com/github/gitignore/blob/master/Clojure.gitignore 
And it wasn't well imported (empty file) in gitea https://github.com/go-gitea/gitea/blob/master/options/gitignore/Clojure
