### ISSUE TITLE
Feature request: Expand diff for more context

### ISSUE THREAD

**Issue by BhaaLseN** [go-gitea/gitea#5263]
GitHub allows a diff to be expanded, in case more context than the configured context lines is needed for a review. Clicking the symbol above/below the lines numbers here:
![Expand Context](https://user-images.githubusercontent.com/826052/47952136-20d31800-df6b-11e8-84fd-5a9c665d5a9f.png)
expands the diff in the respective direction to show more context:
![More context](https://user-images.githubusercontent.com/826052/47952138-2cbeda00-df6b-11e8-963c-05b412dc0ecd.png)

Update: GitHub now supports expanding _both_ ways for files that have more than one hunk of change.
![Expand goes both ways](https://user-images.githubusercontent.com/826052/54771023-bd3d4480-4c04-11e9-828f-b4aafb0581bc.png)

**Comment by shaba** [comment]
+1

**Comment by starhel** [comment]
+1 This is probably one of the most important features allowing fast and pleasant code review.

**Comment by Maximusya** [comment]
Yes, please

**Comment by petrdunaj** [comment]
for our whole team 7* (+1)

**Comment by guillep2k** [comment]
This has been implemented in #8924
