### ISSUE TITLE
Include submodules in release-archives

### ISSUE THREAD

**Issue by tastytea** [go-gitea/gitea#5265]
- Gitea version (or commit ref): 1.5.3

## Description

If I push a tag, Gitea creates a release with archives of the sourcecode. If I use a git submodule in my repo, the corresponding directory in the archives is empty.

I think it would be nice if the submodule was included in the archives – if it is on the same server and belongs to the same user/organization.

**Comment by paranoico** [comment]
I need this feature also, for git submodules. Or may be add some other similar package like git-subrepo.

Moreover why is it stale if no body in Git team has responded? That is wrong.

**Comment by zilti** [comment]
Seems like #4773 is "the same" issue as this one; over there there's slightly more activity

**Comment by tastytea** [comment]
Duplicate of <https://github.com/go-gitea/gitea/issues/4773>
