### ISSUE TITLE
Hide Gitea's version in production

### ISSUE THREAD

**Issue by Deuchnord** [go-gitea/gitea#5271]
- Gitea version (or commit ref): 1.5.3 (8733384)

## Description

As an administrator of my Gitea instance, I'd like to hide its version (or the commit hash). It is a common practice to do that, for instance on Web server and language interpreters, mainly for security purpose, so it would be less easy for a potential attacker to find vulnerabilities. Is it possible?

### Currently

![Screenshot of the footer of Gitea showing "© Gitea version: 8733384"](https://user-images.githubusercontent.com/7600265/47963018-de224600-e025-11e8-9f44-b867291ea03d.png)

### Expected

![Screenshot of the footer of Gitea showing "© Powered by Gitea."](https://user-images.githubusercontent.com/7600265/47963035-17f34c80-e026-11e8-8c5c-6093151646fb.png)

**Comment by ghost** [comment]
https://github.com/go-gitea/gitea/blob/8733384e20b31f887cb8d8d4196cab939d49ab4b/custom/conf/app.ini.sample#L616-L621

**Comment by Deuchnord** [comment]
Worked like a charm, thank you ☺️
