### ISSUE TITLE
When deleting a remote branch, gitea suggests creating a pull request

### ISSUE THREAD

**Issue by kolaente** [go-gitea/gitea#5279]
- Gitea version (or commit ref):  48badd5
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

When I delete a remote branch with `git push origin --delete branch`, Gitea suggests creating a pull request:

```bash
remote: 
remote: Create a new pull request for 'branch':
remote:   https://git.kolaente.de/kolaente/api/compare/master...branch
remote: 
To ssh://git.kolaente.de:9022/kolaente/api.git
 - [deleted]         branch
```

**Comment by adelowo** [comment]
https://github.com/go-gitea/gitea/pull/5166

**Comment by lunny** [comment]
@techknowlogick this is a new feature on v1.7 so no backport was sent to v1.6
