### ISSUE TITLE
gitea source code zip detected as virus/malware

### ISSUE THREAD

**Issue by Harish1n1ly** [go-gitea/gitea#528]
- Gitea version: **1.0.0 (6aacf4d)**
## Description

Chrome automatically removes the file gitea-1.0.0.zip after download with error **Virus detected**
**File URL:** https://github.com/go-gitea/gitea/archive/v1.0.0.zip
**Chrome Version:** 57.0.2950.4 (Official Build) dev (64-bit)

Windows Defender also reports this as malware: [screenshot](https://cloud.githubusercontent.com/assets/8962050/21538506/d30232d8-cdc3-11e6-8475-4c619b009c8c.jpg)

**Comment by thibaultmeyer** [comment]
@Harish1n1ly Could you submit file to [VirusTotal](https://www.virustotal.com) and paste the report link ?

**Comment by denji** [comment]
https://github.com/go-gitea/gitea/blob/v1.0.0/public/js/index.js ([VirusTotal](https://www.virustotal.com/en/url/8697f916197ace339f5989db40be06ad8fa95e5658d1bc248779759d3d69cac9/analysis/1483000185/))

#### `https://github.com/go-gitea/gitea/archive/v1.0.0.zip`
* https://virusscan.jotti.org/en-US/filescanjob/qjtao23xc2
* https://www.virustotal.com/en/url/46063cb91041153d7ee5ef8ed5d7d57eebd7c209408127c5d4da684270e6203e/analysis/1482999884/

**Comment by thibaultmeyer** [comment]
You don't have scan archive file but the URL (not the same thing for VirusTotal)

**index.js**
https://www.virustotal.com/fr/file/51e5f87b23e57b9bdd7c122143a55237a4ffb8c712753d0deff5b91e2e635a49/analysis/1483000531/


File is clean, is just a false positive due to the Zip compression algorithm

**Comment by denji** [comment]
Windows Defender is also RNG algorithms.

**Comment by Harish1n1ly** [comment]
Extracted the zip in a Linux machine and copied index.js to Windows, Immediately removed as malware by Windows Defender. It is not related to compression.

Strangely, Defender does not report when any change is made to the file before copying. Just added an empty line, it does not have any problem.
Looks like false positive, but this may affect downloads by Windows/Chrome users.

**Comment by thibaultmeyer** [comment]
Only Windows users with Windows Defender. I dont have this issue on my Win 10 with Avast Pro.

Maybe you can submit a PR to add an empty line to this file and explain it will fix false positive detection with Windows Defender

**Comment by tboerger** [comment]
And since we have not really changed the index.js it must also apply for Gogs. Beside that I suggest to use our prebuilt binaries from https://dl.gitea.io which embeds the public folder into the binary.

**Comment by tboerger** [comment]
So what do we want to do here? How can we solve that false-positive?

**Comment by thibaultmeyer** [comment]
Maybe is possible to use the virustotal API for each file pushed to dl.gitea.io ? it could avoid this kind of ticket in the future.

**Comment by Harish1n1ly** [comment]
@tboerger : Gogs zip downloads just fine. ~~Gitea 1.0 prebuild binaries are not working for me.~~

The problem seems to be resolved with latest index.js though. I just tried the following,

> wget https://raw.githubusercontent.com/go-gitea/gitea/master/public/js/index.js
> wget https://raw.githubusercontent.com/go-gitea/gitea/release/v1.0/public/js/index.js

Defender only reports problem with second file and removes it.

**update:** The binaries are working fine. I thought they were installers.

**Comment by lesderid** [comment]
I believe this is the right place to report false positives (for Windows Defender):
https://www.microsoft.com/en-us/security/portal/submission/submit.aspx

**Comment by Bwko** [comment]
I've contacted the Microsoft defender team and they cant find anything suspicious.
So I think this is a false positive.

**Comment by lunny** [comment]
So let's close this one. Please feel free to reopen it.
