### ISSUE TITLE
 Drone is not recognizing gitea release creation

### ISSUE THREAD

**Issue by xoxys** [go-gitea/gitea#5288]
- Gitea version (or commit ref): 1.5.3
- Git version:
- Operating system: RHEL
- Database (use `[x]`):
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant

## Description
As mentioned [here](https://github.com/drone/drone/issues/2519) and [here](https://github.com/go-gitea/gitea/issues/3738) for me, there seems to be some issues with gitea webhooks.

if i create a release from the gitea ui (creates also a tag in background), drone does not recognize it and is not running the pipeline.

If i instead push a tag from command line to remote repo, drone will run twice. One run for the push and one run for the tag... That duplicates the runtime. Is this the expected behavior?

**Comment by tboerger** [comment]
> If i instead push a tag from command line to remote repo, drone will run twice. One run for the push and one run for the tag... That duplicates the runtime. Is this the expected behavior?

This have been explained at https://github.com/drone/drone/issues/2519#issuecomment-436541036, this is really the expected behavior.

**Comment by tboerger** [comment]
> So yes i am not sure if this is the correct behavior and asked to the gitea team also. I am not sure if it makes sense to run it twice in case of an git push tag. What is worng with this question?

You have pushed a commit that have not been on the server before and a tag at the same time. That's why 2 events are triggered. That's as explained by brad an expected behavior.

**Comment by zdk123** [comment]
I am also interested in this issue, especially if this is the expected behavior:

> if i create a release from the gitea ui (creates also a tag in background), drone does not recognize it and is not running the pipeline.

For a large repo, I'd like to trigger drone without having to clone the whole repo.

**Comment by xoxys** [comment]
Tested the same szenario with cloud.drone.io and github and this setup do it right. If i create a release at github web drone runs a single task for the new tag. If i create a new tag at the command line and push these new tag drone runs only once also to handle the new tag. Sorry but i think there is an issue at drone or gitea site handling this szenario.

**Comment by tboerger** [comment]
Have you checked within the webhooks page if gitea is sending a webhook if you create a tag via web ui? If it sends a webhook but no build starts even if the tags checkmark within drone is checked than it's a bug within drone. If no webhook gets sent it's a bug within gitea.

**Comment by xoxys** [comment]
Ah thanks to pointing me in this direction. Will check this
