### ISSUE TITLE
Disable release zip

### ISSUE THREAD

**Issue by pindi31** [go-gitea/gitea#5292]
Hi,

I would like to disable the creation of zip/tar of release version.
Each time a tag a version gitea create a zip but i don't need it and it takes some space.
My version of gitea is 1.4.1

Thanks

**Comment by jpraet** [comment]
Could this issue be reopened please? I am also interested in the feature to disable the zip creation for each tag.

**Comment by brennen** [comment]
I'd, likewise, appreciate this feature - though a better solution might be code to check and delete the oldest of the cached zip / tar.gz files.  These are getting crawled by bots on a large-ish repo and filling a 50 gig filesystem every couple of days for me.  I might be able to mitigate that at the webserver level or with a robots.txt, but it's an unexpected failure mode.

**Comment by 6543** [comment]
I think switched to async arch generateion .. but dont know if it's done for release too jet

**Comment by Gergosz2** [comment]
I also would like to see this zip/tar disable function in the near releases.

In one of our project we have a repo with some submodule, and sub-submodules.  For the ease of use the coordinator keeps the main repo up to date, so cloning it , or checking out one of its commit repesents a so called release.

**Comment by zeripath** [comment]
Why don't you just change the templates to remove it from the webpages.

**Comment by lovkiymusic** [comment]
hello guyz, it's nice improvement, give it a chance please :)

**Comment by wait-what** [comment]
I would also like to see this feature

**Comment by lunny** [comment]
The source zip and tar.gz files are shared from archives. So that there is no extra space will be used. And I think maybe you want a feature to disable archives but I don't recommend you do that.

**Comment by techknowlogick** [comment]
It's only generated on demand, and cleared on a cron. To hide it the templates can be modified.
