### ISSUE TITLE
Page Crash on new issue

### ISSUE THREAD

**Issue by alexmejiaec** [go-gitea/gitea#5297]
- Gitea version (or commit ref): v464dcd1
- Git version: git version 2.16.2.windows.1
- Operating system: Windows server 2012
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (https://try.gitea.io/emejia/Test_Incident/issues/new)
  - [ ] No
  - [ ] Not relevant
- Log gist: Unable to obtain One

## Description
Server crashes when you perform the following tasks in the given order :
- Browse a repo as Collaborator with write permissions
- Create new Issue  + Set Title + Set Description 
- Upload any Picture
- Set Asignee
- Set Branch
- Hit "Create Issue" button

## Screenshots
It just kills the page
![sin titulo](https://user-images.githubusercontent.com/18557728/48225895-33cf5900-e36c-11e8-9600-ebf9b1fb7c39.png)

**Comment by techknowlogick** [comment]
Closing as it has been resolved by SQLite locking PRs. Please upgrade Gitea, and try again.
