### ISSUE TITLE
s3fs filesystem

### ISSUE THREAD

**Issue by pjebs** [go-gitea/gitea#5301]
Since gitea relies on the local filesystem to store the git projects, it obviously limits horizontal scalability.

Has anyone tried to use AWS S3 or Digital Ocean Spaces as the datastore?

Has anyone attempted to use [s3fs](https://github.com/s3fs-fuse/s3fs-fuse), [s3ql](https://bitbucket.org/nikratio/s3ql/), [s3backer](https://github.com/archiecobbs/s3backer), [yas3fs](https://github.com/danilop/yas3fs), [goofy](https://github.com/kahing/goofys) or  [riofs](https://github.com/skoobe/riofs)?

If so, has performance been "minimally acceptable"?

**Comment by lafriks** [comment]
Please ask questions in Gitea Forum - https://discourse.gitea.io/
