### ISSUE TITLE
Pull requests UI failed in Chinese but not in English

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#5304]
![bug](https://user-images.githubusercontent.com/81045/48240620-6c277380-e40e-11e8-89b0-d6fefe6bc46d.png)

**Comment by jonasfranz** [comment]
Can you point out where the bug is?

**Comment by lunny** [comment]
cannot reproduce now.

**Comment by lafriks** [comment]
Closing, please reopen if there is still a problem in latest version
