### ISSUE TITLE
Deleting branch does not trigger update's hook via the UI

### ISSUE THREAD

**Issue by vinhpooh** [go-gitea/gitea#5309]
- Gitea version (or commit ref): 1.40 (also tested on 1.60 rc2)
- Git version: 2.9.3
- Operating system: SLES12 SP1
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
When disabling the deletion of a branch in update's hook on a repository, Gitea perform a "git branch -d <branch_name>" so it does not trigger the hook.

It should use "git push --delete <remote_name> <branch_name>" or "git push <remote_name> :<branch_name>" like the creation of a branch via the UI.

**Comment by lafriks** [comment]
Using remote push would require local checkout that would be quite performance killer. I think this way is better
