### ISSUE TITLE
Dump Permission problem

### ISSUE THREAD

**Issue by nobicycle** [go-gitea/gitea#5315]
Thanks for gitea.

- Gitea version 1.5.3-3
- Git version:2.19.1
- Operating system: Manjaro/Arch
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X ] Not relevant
- Log gist:

## Description
$sudo -u git gitea dump -c /etc/gitea/app.ini
2018/11/11 12:30:58 [...s/setting/setting.go:808 NewContext()] [E] Failed to create '/.ssh': mkdir /.ssh: permission denied

This command used to work under previous installations/versions of gitea

Under the Arch package, gitea service runs under git user. See gitea.service below.

[app.ini.txt](https://github.com/go-gitea/gitea/files/2569061/app.ini.txt)
[gitea.service.txt](https://github.com/go-gitea/gitea/files/2569062/gitea.service.txt)

**Comment by yyu0378** [comment]
I think you need "cd /home/git",then try again.

**Comment by nobicycle** [comment]
Hi,
> cd /home/git"

I don't use a single git directory. The local git repos are in several places.

**Comment by a7hybnj2** [comment]
I just ran into this same issue. I ended up just manually backing everything up and am currently updating. I will try to dump again once I am on the latest version.

**Comment by nobicycle** [comment]
Under gitea 1.6.3 , the line below works. I added _cd /var/lib/gitea_
Maybe it worked under  previous versions. Closed

`sudo -u gitea /bin/bash -c cd /var/lib/gitea; gitea dump -c /etc/gitea/app.ini
`
