### ISSUE TITLE
Please make it possible to only dump database

### ISSUE THREAD

**Issue by brueggemannapollo** [go-gitea/gitea#5322]
- Gitea version (or commit ref): 1.6
- Git version: 2.16.4
- Operating system: SLES15
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:

## Description
Please make it possible to only dump database. We like to migrate to another database backend and I tried to dump the database in new sql syntax, but we have the problem that our git repositories are using >100G diskspace. This needs hours to be zipped but we only need the sql export.

**Comment by SagePtr** [comment]
Why not to do it with any SQL backup stuff? For mysql:
mysqldump -u **username** -p**password** **dbname** > file.sql

**Comment by lafriks** [comment]
As suggested for database only backups use database dedicated tools (MySQL -> mysql, PostgreSQL -> psql, sqlite -> backup db file)
