### ISSUE TITLE
Indexer restart the index database after restart

### ISSUE THREAD

**Issue by gerroon** [go-gitea/gitea#5325]
Hi

It seems like the indexer rebuilds the whole code search index from scratch everytime I restart Gitea. To be sure I waited over a day to make sure it indexed everything, though I can t be sure but whole day sounds enough for a repo around 1.2GB The index db stabilized around 620MB so I am sure it stopped indexed before I restarted

I am using Gitea Version: 34696f4 on Debian Testing

**Comment by techknowlogick** [comment]
To clarify: The repo is 1.2GB and the code search index is only 620MB?

If yes, that's unusual as the index is normally bigger than the repo. Do you have a lot of binary files in your git repo?

**Comment by gerroon** [comment]
Yeah the total repo is like 1.2GB and the indexer tops around 620MB. 

I am not sure about binaries, this particular instance is mostly git mirros like Blender repo etc
