### ISSUE TITLE
Error when trying to clone a repository via HTTPS

### ISSUE THREAD

**Issue by shootie22** [go-gitea/gitea#5327]
- Gitea version (or commit ref): e7128e8 
- Git version: 
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X] No
  - [ ] Not relevant
- Log gist:

## Description

When trying to clone a rather large repo (~2 gigs), users get an error. I haven't modified anything at all related to Gitea or the server it is hosted on, really. It just suddenly stopped working. It works if we try to clone other smaller repos and it also works for users who already have the project cloned and are actively working on it. Push, pulls & fetches are working normally for those who already have the project. Here's the error the user gets when trying to clone the project:

```
fatal: The remote end hung up unexpectedly
fatal: protocol error: bad pack header
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
```

**Comment by lafriks** [comment]
What git version (both on server and client) are you using? please attach also gitea.log errors

**Comment by shootie22** [comment]
`git version 2.11.0` on the server which apparently is the latest version
`git version 2.17.1.windows.2` on the client
[client log.txt](https://github.com/go-gitea/gitea/files/2573750/client.log.txt)
[gitea.log.txt](https://github.com/go-gitea/gitea/files/2573751/gitea.log.txt)
[http.log.txt](https://github.com/go-gitea/gitea/files/2573752/http.log.txt)

**Comment by shootie22** [comment]
Any updates?

**Comment by angularsen** [comment]
Same here. I don't see anyting special in the logs.
[gitea.log](https://github.com/go-gitea/gitea/files/2742127/gitea.log)
[http.log](https://github.com/go-gitea/gitea/files/2742128/http.log)

No changes on server, it just failed when I tried to fetch from a computer I hadn't used in a while so it was fetching some older history. `git clone` fails on both computers, so it seems like the data is corrupt maybe?
