### ISSUE TITLE
完善一下后台设置功能

### ISSUE THREAD

**Issue by mm8m6m7m** [go-gitea/gitea#5332]
能在后台控制面板直接设置附件大小啊等等那些,每次都要编辑app.ini又要重启生效,这样不好吧

**Comment by lunny** [comment]
Please speak English.

**Comment by mm8m6m7m** [comment]
Improve the background setting function.  You can set the size of the attachment directly in the background control panel, and so on. Every time you edit app. ini, you have to restart it. That's not good?
