### ISSUE TITLE
Improve the background setting function.

### ISSUE THREAD

**Issue by mm8m6m7m** [go-gitea/gitea#5333]
You can set the size of the attachment directly in the background control panel, and so on. Every time you edit app. ini, you have to restart it. That's not good?

**Comment by mm8m6m7m** [comment]
How to solve this problem? Modification of app.ini will not take effect.
![image](https://user-images.githubusercontent.com/20329685/48462392-f575e600-e812-11e8-8279-6ac51c295770.png)

**Comment by lunny** [comment]
You have to restart gitea after you change that app.ini file.

**Comment by mm8m6m7m** [comment]
Restart will not take effect.  
![image](https://user-images.githubusercontent.com/20329685/48463036-949bdd00-e815-11e8-81b1-187719ca8e13.png)

**Comment by mm8m6m7m** [comment]
Restart will not take effect.   
![image](https://user-images.githubusercontent.com/20329685/48463067-b09f7e80-e815-11e8-9e80-15fcc7c163fa.png)

**Comment by lunny** [comment]
Cannot reproduce that. Which version are you running?

**Comment by mm8m6m7m** [comment]
https://dl.gitea.io/gitea/1.6/gitea-1.6-linux-amd64    1.6
![image](https://user-images.githubusercontent.com/20329685/48464189-a2536180-e819-11e8-8712-16fb0182de39.png)

**Comment by lunny** [comment]
@yasuokav is right. @mm8m6m7m My setting is for upload file on creating issue interface.

**Comment by mm8m6m7m** [comment]
OK
