### ISSUE TITLE
ListReleases() In /routers/api/v1/repo/release.go should set lower PageSize for GetReleasesByRepoID()

### ISSUE THREAD

**Issue by terrywh** [go-gitea/gitea#5336]
``` Go
// /routers/api/v1/repo/release.go:79
releases, err := models.GetReleasesByRepoID(ctx.Repo.Repository.ID, models.FindReleasesOptions{
		IncludeDrafts: ctx.Repo.AccessMode >= models.AccessModeWrite,
		IncludeTags:   false,
	}, 1, 2147483647)
```
Current pageSize is 2147483647. 

* Maybe it should be set to `MAX_RESPONSE_ITEMS` ? 
* Maybe this Page / PageSize should can be controlled by a parameter?

**Comment by lafriks** [comment]
We should implement paging in all API methods that returns list like it is done in github:
https://developer.github.com/v3/#pagination

**Comment by terrywh** [comment]
is there a timeline for this? 
(We are using this api for an automation system; i'm not inclined to delete all the Releases ...... ).

**Comment by lunny** [comment]
@terrywh please confirm #5831 fix this.
