### ISSUE TITLE
Webhooks don't work with deployment keys

### ISSUE THREAD

**Issue by tarelda** [go-gitea/gitea#5337]
- Gitea version (or commit ref):  6efdcae
- Git version: 2.15.2
- Operating system: Alpine Linux inside Docker
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

When trying to push into repository using RW deployment key webhooks are not triggered whilst with normal user's key everything works fine.

**Comment by techknowlogick** [comment]
Related to #3795

**Comment by zeripath** [comment]
Should now be fixed.
