### ISSUE TITLE
The database is set incorrectly during installation!(MSSQL and SQLITE3)

### ISSUE THREAD

**Issue by kevin928** [go-gitea/gitea#5338]
- Gitea version (or commit ref):
- Git version: latest
- Operating system: windows 10 pro
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ X] MSSQL
  - [ X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X ] No
  - [ ] Not relevant
- Log gist:

## Description
I use Docker for windows

docker run -d --name=gitea -p 10022:22 -p 10080:3000 -v C:\Users\kevin\gitea:/data gitea/gitea:latest
...

## Screenshots
![aa](https://user-images.githubusercontent.com/5638731/48488930-d56b1480-e85c-11e8-839e-99e220f14d4a.jpg)
![aaa](https://user-images.githubusercontent.com/5638731/48488931-d603ab00-e85c-11e8-8e84-170fe1313645.jpg)

**Comment by lafriks** [comment]
You need to set to correct host yourself as gitea can not detect your servers hostname for mssql

**Comment by lunny** [comment]
You can mysql example https://docs.gitea.io/en-us/install-with-docker/
