### ISSUE TITLE
Admin page not switching language

### ISSUE THREAD

**Issue by Bwko** [go-gitea/gitea#534]
- Gitea version (or commit ref): At least since 6bcff78
- Operating system: Linux
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant

Go to the admin page, switch to whatever language. 
Admin page stays in English.

**Comment by bkcsoft** [comment]
Is this because there's no translation or because of a bug?

**Comment by Bwko** [comment]
It's a bug, the translations exists.

**Comment by lunny** [comment]
Which OS and Browser that you tested, I cannot reproduce that on macOS & latest Safari.

**Comment by Bwko** [comment]
Found the problem: Somehow a en-US lang cookie is set under the /admin path. And a nl-NL cookie is set under the / path
When you change your language it changes the / lang cookie to that language, and leaving the /admin lang cookie on en-US

**Comment by lunny** [comment]
Is this a bug?

**Comment by Bwko** [comment]
@lunny Yes, but I don't know how/why the /admin lang cookie got set. 
But i'ts easy to reproduce the bug: use a cookie editor and create a /admin lang cookie.

**Comment by lunny** [comment]
Move this to 1.x.x since I cannot reproduce this and no one to send PR to fix this.

**Comment by lunny** [comment]
Just close this since we can not reproduce it any more. Please feel free to reopen it.
