### ISSUE TITLE
Webhook for triggering sync of a mirrored repo

### ISSUE THREAD

**Issue by calind** [go-gitea/gitea#5342]
I'm mirroring a repo from github and it would be nice if I could add a webhook in github so that whenever I push to the github repo, the gitea repo is updated as well.

**Comment by fzwoch** [comment]
I think this can be accomplished with this API: `POST ​/repos​/{owner}​/{repo}​/mirror-sync`

**Comment by xeruf** [comment]
yep, but seems to be impossible in the current form as it requires authentication via token - entering it as secret on github does not work

references:
https://docs.gitea.io/en-us/api-usage/
<img width="662" alt="image" src="https://user-images.githubusercontent.com/13354331/177842465-eed724d8-9cac-45f6-9808-7452d1db759c.png">

**Comment by lunny** [comment]
Closed as I think it's resolved.
