### ISSUE TITLE
FR: Clickable file link in commits view

### ISSUE THREAD

**Issue by gerroon** [go-gitea/gitea#5343]
Hi

It will be very helpful if there isa  clickable link to the source file while in commits/diff view. There is "Browse source" but that just takes to the root of the source treee not the folder where the file is or the file itself.

thanks

**Comment by HarshitOnGitHub** [comment]
@gerroon Have you tried `View File` in top right corner in the diff box. I think it will serve your purpose:
![image](https://user-images.githubusercontent.com/16687990/48955246-ef9aa600-ef72-11e8-8288-4d7a1d141dfd.png)

**Comment by lafriks** [comment]
View file would open file with that version
