### ISSUE TITLE
Language Savant

### ISSUE THREAD

**Issue by Hcreak** [go-gitea/gitea#5345]
Are there any plans for gitea to get a status-bar that shows how much of different code its used in the git?

And when you click on it you see the different languages that are used and how many % of the code that is used of that language in the git?

Its a really neat feature that i really miss!

**Comment by adelowo** [comment]
PR - https://github.com/go-gitea/gitea/pull/4824
Issue - https://github.com/go-gitea/gitea/issues/2165
