### ISSUE TITLE
Enable IntegratedAuthentication (ActiveDirectory) for MSSQL

### ISSUE THREAD

**Issue by road42** [go-gitea/gitea#5349]
- Gitea version (or commit ref): latest
- Git version: 2.19.1
- Operating system: Windows Server 2012 R2
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [X] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:

## Description

I'd like to use the integrated authentication for a mssql database. I already looked into the sourcecode:
 
On this line the connectionString is created:
https://github.com/go-gitea/gitea/blob/127f4770566e09504a3efe4c4282cee049bad0e1/models/models.go#L239

It seems that gitea uses xorm as or-mapper.
xorm uses the mssql-driver from: https://github.com/denisenkom/go-mssqldb

The driver has the following documentation:

> user id - enter the SQL Server Authentication user id or the Windows Authentication user id in the DOMAIN\User format. On Windows, if user id is empty or missing Single-Sign-On is used.

## Solution?

I already tried to leave "user id" and/or "password" in the configuration empty, but it did not connect to the database.

It should be possible to leave the password and username field empty to connect to a mssql database.

**Comment by lafriks** [comment]
I don't think driver supports integrated authentication

**Comment by lafriks** [comment]
To use AD auth you still need to provide username and password

**Comment by lunny** [comment]
So if there is an config on ini file to enable integration login when MSSQL used. Then we only need to put username and password empty. Is that OK?

**Comment by road42** [comment]
I checked if you can simply leave `user id=` and `password=` empty in the connection string.

```go
engine, err = xorm.NewEngine("mssql", "server=<server>;database=<database>;user id=;password=")
```

It still works.
 Like the documentations of `go-mssqldb` says:

> On Windows, if user id is empty or missing Single-Sign-On is used.

I think a simple switch in the config file or just letting me pass no "user id" and/or "password" should to it.

**Comment by cboehme** [comment]
I just set up Gitea 1.22.0 with MSSQL and Windows Integrated Authentication without problems. My database configuration is
```
[database]
DB_TYPE = mssql
HOST = dbhost.example.com:1433
NAME = gitea
USER =
PASSWD =
SCHEMA =
SSL_MODE = disable
CHARSET = utf8
LOG_SQL = false
```

It works like a charm. I think this issue can be closed as the feature is working.
