### ISSUE TITLE
open conf/locale/locale_en-US.ini: no such file or directory after the first start

### ISSUE THREAD

**Issue by 2Belette** [go-gitea/gitea#535]
- Gitea version (or commit ref):4607.cbcb436-1
- Git version:
- Operating system: ArchLinux
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
I have download the AUR package from https://aur.archlinux.org/packages/gitea-git/
Everything is ok during the installation but after the first run I don't get the install page, the systemd unit failed with this message : 
open conf/locale/locale_en-US.ini: no such file or directory

Any idea how to quickly fix this ?
thanks

**Comment by Bwko** [comment]
> Any idea how to quickly fix this ?

Yes copy the [options](https://github.com/go-gitea/gitea/tree/release/v1.0/options) dir into your installation folder and rename it to conf
Or compile Gitea from source

**Comment by tboerger** [comment]
That sounds like a bug within the package because the files are not properly located

**Comment by Bwko** [comment]
@2Belette Your welcome
@tboerger The v1.0 prebuilt binary has the same problem: Never mind, stupid mistake :persevere:
