### ISSUE TITLE
possible bug: User can access repos not assigned to them

### ISSUE THREAD

**Issue by hardikdangar** [go-gitea/gitea#5351]
- Gitea version (or commit ref):    1.5.0 built with: bindata, sqlite
- Git version: 2.14.1
- Operating system: ubuntu 16.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x ] SQLite
- Can you reproduce the bug at https://try.gitea.io: 
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X ] Not relevant
- Log gist:

## Description
If you create organization and assign user to organization and create repository via organization. then that repository can be accessed by member who is not a part of that organization via url. they can see the code directly.

If i make the repo private then team members can not see the repo. so is there any way i can force non oganization users to not see the repos they are not part of organization.
...

**Comment by lunny** [comment]
This is designed and we already have a PR to fix your issue. see https://github.com/go-gitea/gitea/pull/1763
