### ISSUE TITLE
Integration with tools providing security

### ISSUE THREAD

**Issue by tvvignesh** [go-gitea/gitea#5352]
It would be great to have integration with tools like [NSP](https://medium.com/node-security) or [Snyk](https://snyk.io) to allow vulnerability scanning out of the box. Something like Github's vulnerability scanning for the repository.

Currently, I am planning to do this at the CI/CD stage via Jenkins and NSP.

**Comment by mrsdizzie** [comment]
This seems like something that could be done via API
