### ISSUE TITLE
Option to invite users via Email

### ISSUE THREAD

**Issue by tvvignesh** [go-gitea/gitea#5353]
It would be great to have the ability for admins to invite other users to the repo to signup over mail. 
Currently, we are doing this by sharing the repository URL and asking them to sign up but would be good to have an email invite option.

**Comment by tobiasBora** [comment]
Also interested !

**Comment by lunny** [comment]
We can add an option to invitation signup mode. Enable invitation number in app.ini and default to zero.
We need a table to save the invitation emails and inviters. And when the signup mode is invitation, only the user whose email on that table could be registered successfully.

**Comment by treasuretron** [comment]
also interested in this! Thanks!

**Comment by yunginnanet** [comment]
+1

**Comment by daanbreur** [comment]
Also interested

**Comment by yunginnanet** [comment]
Interested in this, to avoid the stalebot from reaping it.

**Comment by xtexChooser** [comment]
Hi, I'm trying to get a registered user to join the organization, but I can't find the way, can you tell me?

**Comment by 6543** [comment]
"Add team member invite by email **#20307**" got merged ... next things will be in v1.19.0 if somebody do take it - groundwork is done now

**Comment by kdumontnu** [comment]
Does anyone object if I close this issue and open a new one with the new request (to enumerate number of invites)? The new request seems a bit different from the original issue.

**Comment by 6543** [comment]
@kdumontnu go on ... ps: link it to this issue :)
