### ISSUE TITLE
docker install gitea, git ssh clone issue

### ISSUE THREAD

**Issue by M2shad0w** [go-gitea/gitea#5358]
env docker gitea:latest

git clone git clone  git@{domain}:{user}/web.git
```
正克隆到 'web'...
git@{domain}:{user}: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
fatal: 无法读取远程仓库。
```
but fllowing is ok
```
git clone  ssh://git@{domain}:10022/{user}/server.git

```
i don't know why

**Comment by lunny** [comment]
you should specify the port

**Comment by lafriks** [comment]
You have to either change host server OpenSSH port or use second option
