### ISSUE TITLE
missing list endpoint for /orgs/

### ISSUE THREAD

**Issue by fragfutter** [go-gitea/gitea#5361]
- Gitea version (or commit ref): 1.5.3
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

the api endpoints for orgs and teams are missing list options. I would like to get a list of all team ids. Either by querying "GET /teams/" and get all teams (or all team ids) or by querying "GET /orgs/" to get all orgs and then query each org for it's teams.

**Comment by lunny** [comment]
see https://try.gitea.io/api/swagger, you can list all teams of an organization via `/orgs/{org}/teams` and you can get all your organization via `/user/orgs`.

**Comment by fragfutter** [comment]
and finding all organizations (not only mine)?
