### ISSUE TITLE
Webhook issues send more event

### ISSUE THREAD

**Issue by RelicOfTesla** [go-gitea/gitea#5364]
- Gitea version (or commit ref):
- Git version:
- Operating system: windows
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
1. Set WebHook to [https://oapi.dingtalk.com/robot/send?access_token=xxxxxx]
2. Click [Issues] And input content. 
3. Set [Assignees],  more peoples(>=3)
4. Create issues
5. My DingTalk receive ***4+*** message, Only one second!.
I see [Webhook]->[Recent Deliveries]
```
actionCard4:   Issue opened:
```
```
actionCard3:   Issue assigned to C
```
```
actionCard2:   Issue assigned to B
```
```
actionCard1:   Issue assigned to A
```
...

## Screenshots

![_20181120195117](https://user-images.githubusercontent.com/4145299/48772242-bd810e00-ecfe-11e8-92dd-fee365caf91a.png)

**Comment by adelowo** [comment]
I think this is the expected result as they are technically individual events although batched together as one. 

- Create issue
- Assign user A.
- Assign user B.
- Assign user C.

**Comment by RelicOfTesla** [comment]
Please note the time, if this WEBHOOK is just a message notification, or mail push. Then, it will result in the newly created work order, running out of multiple records at once. If more people choose, it may even send  dozens of e-mails repeatedly.

**Comment by lunny** [comment]
@adelowo this should be a bug.

**Comment by adelowo** [comment]
@lunny If I select "issue", I expect to get webhook for issues' assignments

<img width="1920" alt="screenshot 2018-11-20 at 14 09 30" src="https://user-images.githubusercontent.com/12677701/48775671-0f5d7000-ecce-11e8-8562-d45004a064b7.png">

**Comment by adelowo** [comment]
> Please note the time, if this WEBHOOK is just a message notification, or mail push. Then, it will result in the newly created work order, running out of multiple records at once. If more people choose, it may even send dozens of e-mails repeatedly.

Oh I get this, sorry for the misunderstanding.

@lunny 👍
