### ISSUE TITLE
Format string not formatted when administrating a user

### ISSUE THREAD

**Issue by vbrandl** [go-gitea/gitea#5368]
- Gitea version (or commit ref): 2a6d3ba
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant

## Description

When changing a user in the admin area and saving the changes, at least when using the german language pack, the UI will confirm the changes with `Der Account „%s“ wurde aktualisiert.` (The account has been updated). I could not test it on try.gitea.io since I cannot the admin panel. I also did not test if this is true for other languages, but it looks like a format string is not formatted.

## Screenshots

![screenshot](https://user-images.githubusercontent.com/20639051/48799989-c676dd00-ed08-11e8-9428-e0d541ff2d3b.png)

**Comment by lunny** [comment]
I think this maybe a translation problem. Could you try english version UI?

**Comment by vbrandl** [comment]
You are right. The English message does not contain the username: https://github.com/go-gitea/gitea/blob/b97af15de67b04fd259bd70a4abbc873f12e9491/options/locale/locale_en-US.ini#L1416
It's the key `users.update_profile_success` in the German language bundle, that is wrong. I will create a PR for this later

**Comment by bugreport0** [comment]
We could create a unit test that compares the format-string 'signature' of translations to make sure translations line up correctly. The signature is just the percent-signs with formats, like:
- `Added user %s` has signature `%s`
- `Step %u of %u complete for user %s` has signature `%u%u%s`

We can then:
- read the English translation 'truth' mapping `string_key` to `signature`
- read other translations to check `signature` matches for `string_key`

I used this on a different project and it's worked great to catch errors.

**Comment by vbrandl** [comment]
I also thought of that, but the order of the format patterns might differ. So the signature would be something like a hashmap with the pattern as key and the number of occurrences as value.

**Comment by lunny** [comment]
@bugreport0 Good idea. Could you send a PR to do that? And but currently our translation will be committed by a robot automatically.

**Comment by vbrandl** [comment]
From the format of the used string, I guess, gitea does not use named placeholder in format strings, but take this (admittedly conceived) example: `User %s visited %d minutes ago` vs `Vor %d Minuten besuchte der Nutzer %s diese Seite`. What I'm trying to say is, that the order of the placeholders might change depending on the language.

The first one would have the signature `%s%d` while the second one would be `%d%s`. Maybe the signature should be a hashmap, mapping the format string to the number of occurrences of the pattern. For the above example, this would be `{ "%s" => 1; "%d" => 1 }` in both cases.

**Comment by lafriks** [comment]
@bugreport0 un GoLang you can reorder with such syntax: `%#[1]s`
