### ISSUE TITLE
Display README.md from docs/, .github/, or other (.gitea/ ?)

### ISSUE THREAD

**Issue by johnstonjs** [go-gitea/gitea#5370]
- Gitea version (or commit ref): 1.5.3
- Git version: 2.9.3
- Operating system: Various
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist: N/A

## Description

First, thank you for making such a fantastic tool!

GitHub has an ability to display a _README.md_ file not in the repository's root, as long as it's in either docs/ or .github/.  The feature is [documented here](https://help.github.com/articles/about-readmes/).

## Suggestion

I'd find it useful to have a similar capability for gitea, replicating this capability of GitHub.  Perhaps we could even have it read another folder, like /.gitea.

**Comment by binaryplease** [comment]
I would also be interested in this. More specifically it would be nice to be able to specify a file directly in an arbitrary path of the repo
