### ISSUE TITLE
Gitea cannot get sshPublicKey from LDAP

### ISSUE THREAD

**Issue by MrCirca** [go-gitea/gitea#5375]
- Gitea version (or commit ref):
- Git version: v1.6.0-rc2
- Operating system: Debian
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:
https://gist.github.com/MrCirca/800954bd928e2595b1ed80dfaaff895a
## Description
Hello, i have configured Gitea gets data from LDAP. Gets all data except sshPublicKey
Database has not write something in publickey table

**Comment by lafriks** [comment]
Need more specific information, what ldap server, how configured auth source?

**Comment by MrCirca** [comment]
LDAP server is OpenLDAP. I configured auth source from Gitea GUI.

**Comment by lafriks** [comment]
Can you show also auth source configuration parameters (removing sensitive information)? It should be working as we have integration tests against OpenLDAP so this must be configuration problem most probably

**Comment by MrCirca** [comment]
I use anonymous bind
![2018-11-22-165152_1916x1163_scrot](https://user-images.githubusercontent.com/6732767/48909885-268b9180-ee77-11e8-9885-2930ad19d04c.png)

**Comment by lafriks** [comment]
Do you see any errors in gitea.log when authorizing?

**Comment by MrCirca** [comment]
No i dont. Tommorow i will send you full log

**Comment by MrCirca** [comment]
When i login....
https://gist.github.com/MrCirca/bd4c185c395e3515b0592ff606dedf32

When i do Synchronize external user data....
https://gist.github.com/MrCirca/9abce000521a08b6368dc53e32afd487

Gitea doesnt write public_key in database
