### ISSUE TITLE
YAML frontmatter rendered improperly

### ISSUE THREAD

**Issue by mcnesium** [go-gitea/gitea#5377]
Exemplary, in a Jekyll project, markdown files have a YAML front matter like this default one in `index.md`:
```markdown
---
# Feel free to add content and custom Front Matter to this file.
# To modify the layout, see https://jekyllrb.com/docs/themes/#overriding-theme-defaults

layout: default
---
```
Gitea tries to render it as if it was regular Markdown:

![screenshot from 2018-11-22 10-28-41](https://user-images.githubusercontent.com/476060/48894061-12796d00-ee42-11e8-8473-e560b6d8e576.png)

Instead, it should detect it being the YAML frontmatter and render it properly, e.g. like this (screenshot created by adding four spaces in front of each line in the front matter):

![screenshot from 2018-11-22 10-30-03](https://user-images.githubusercontent.com/476060/48894032-02618d80-ee42-11e8-8a5b-ddb8e29c7f86.png)

- Gitea Version: 4c1f1f9

**Comment by mcnesium** [comment]
refresh/unstale

**Comment by natedalliard** [comment]
There is an open pull request for gogs: https://github.com/gogs/gogs/pull/4643

**Comment by dakira** [comment]
I have the same problem. Would be nice if the front matter just weren't rendered at all.

**Comment by davidsvantesson** [comment]
@zeripath Do you think the change to goldmark makes a difference for this issue, does it have any specific support for it?

**Comment by dakira** [comment]
@davidsvantesson I haven't checked how it looks now, but Goldmark definitely has support for yaml frontmatter. It is used as the default renderer for Hugo which does also have yaml frontmatter.

**Comment by zeripath** [comment]
@davidsvantesson @dakira we would need to use the https://github.com/yuin/goldmark-meta extension.

I guess it would probably be quite easy to do. The issue is deciding whether to always enable it or not.

I mean yaml front matter is a particular extension to commonmark - it may not be expected.
