### ISSUE TITLE
OpenID Connect authentication source gives 500 error with "SignIn: no provider for foo exists"

### ISSUE THREAD

**Issue by LittleColin** [go-gitea/gitea#5380]
I am adding an Authentication Source for OpenID Connect. I've tried several OpenID Connect providers but all of them result in the following error when I click the OpenID Connect logo on the login screen so I suspect it's not even trying to use the configuration.

`[...routers/user/auth.go:520 SignInOAuth()] [E] SignIn: no provider for foo exists`

(where foo is whatever name I gave the authention name in the free-text field)

- Gitea version (or commit ref): e08c7e5 
- Git version: n/a
- Operating system: 
- Database (use `[x]`):
  - [ X ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ X ] Not relevant - no admin access to try
- Log gist:

## Description

See above

## Screenshots

Just shows 500 error after clicking OpenID Connect logo on login screen.

**Comment by tvvignesh** [comment]
@lunny I got the same 500 error when trying Office 365 Sign In via OpenID. Is this fixed? 

Also, I was wondering if there is a way to restrict only users from a specific domain to login - is it available in Gitea?

**Comment by tvvignesh** [comment]
Got the 500 error fixed by fixing my autodiscovery URL and upgrading to Gitea 1.6.1 but still wondering how to restrict signups to a domain.
