### ISSUE TITLE
Web editor bug

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#5385]
![web_editor_bug](https://user-images.githubusercontent.com/81045/48932216-a0825000-ef35-11e8-9db3-21752f91eedd.gif)

**Comment by lafriks** [comment]
Is it only me or that gif is way to fast to understand what is going on? :)

**Comment by sapk** [comment]
I slow it down by 10x but I don't know exactly what is the bug.
![ezgif com-gif-maker](https://user-images.githubusercontent.com/4052400/48949637-f5739580-ef38-11e8-8eba-66334efbed2f.gif)

**Comment by Etzelia** [comment]
I snapped the error at the end, if that helps.
![](https://i.gyazo.com/511f6ec65085f1e5f5cda6d033451bfc.png)

**Comment by lafriks** [comment]
Need error from gitea.log

**Comment by SagePtr** [comment]
What hooks are used in this repository? If nothing except the default hooks, try to "Resynchronize pre-receive, update and post-receive hooks of all repositories." and reproduce error.
