### ISSUE TITLE
[Features request] Mardown vendor gantt.

### ISSUE THREAD

**Issue by liweiv** [go-gitea/gitea#5390]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

```mermaid
gantt
title project plan
dateFormat YYYY-MM-DD
```

![image](https://user-images.githubusercontent.com/1586298/48943300-c6234f80-ef5d-11e8-908f-0c92a5813c4c.png)
https://mermaidjs.github.io/

**Comment by lafriks** [comment]
duplicate of #3340

JS can be also added using custom header including mermaidjs and adding init script

**Comment by lunny** [comment]
I would like add a gantt on milestones about issues.

**Comment by lunny** [comment]
@lafriks yes, I know but maybe it could be rendered by external tool.
