### ISSUE TITLE
BSD0 license cites someone's name

### ISSUE THREAD

**Issue by khanzf** [go-gitea/gitea#5397]
The BSD0 license cites the name of "Copyright (C) 2006 by Rob Landley <rob@landley.net>".
It seems that the license should default to the name of the creator.

I am using 1.4.3 on FreeBSD 11.2-RELEASE-p1

Great job on this project!

**Comment by lafriks** [comment]
We are using license files from https://github.com/spdx/license-list/

**Comment by khanzf** [comment]
Awesome. But it might be a good idea to not blindly import them. Otherwise, by default we're licensing code to 3rd parties by default.

**Comment by lunny** [comment]
@khanzf BSD package is not our official package and Gitea use MIT license.

**Comment by techknowlogick** [comment]
I've opened up this issue in the linked repo: https://github.com/spdx/license-list/issues/23. Closing an locking this. Please continue discussion there.
