### ISSUE TITLE
React vs Vue

### ISSUE THREAD

**Issue by pjebs** [go-gitea/gitea#5402]
Has this project fully committed to Vue over React from here onwards?
I feel that although Vue is technically superior, the benefit is only minor and is far outweighed by React having facebook's backing and resources + the endless amount of third party React libraries we can leverage.

Vue, despite growing faster at present, doesn't have the libraries or the clout of React.

**Comment by pjebs** [comment]
When was this decision made? Since only a few components have been implemented in Vue, it can still be changed. Was the debate comprehensive with all the competing merits discussed by the key people? 

I know most people here are probably backend Go developers. Any front-end key people's opinions would be greatly appreciated (**assuming the comprehensive discussion hadn't already happened and a decision conclusively made**).

**Comment by techknowlogick** [comment]
> facebook's backing and resources + the endless amount of third party React libraries

Facebook (and many others) also backs vuejs: https://opencollective.com/vuejs https://www.patreon.com/evanyou and there are also many vue third party libraries.

**Comment by pjebs** [comment]
https://trends.google.com/trends/explore?date=2016-11-30%202018-11-26&geo=US&q=reactjs,vuejs

Vue and React have stabalised now with React slightly ahead.

**Comment by pjebs** [comment]
There is no way at the moment there are more high-quality third party vue components compared to high-quality react components. It won't even be close.

**Comment by pjebs** [comment]
> Facebook (and many others) also backs vuejs: https://opencollective.com/vuejs https://www.patreon.com/evanyou and there are also many vue third party libraries.

That's actually my point. React doesn't need donations because Facebook pays the developers $$$.
Vue on the other hand (despite some company backing - including some small donations by Facebook to keep them on their toes), relies on donations to survive.

**Comment by pjebs** [comment]
https://www.npmjs.com/package/react-calendar-heatmap 
**This is an alternative to the recently implemented Vue calendar heatmap.**

**Comment by lunny** [comment]
I think two reasons:
1) Reactjs' license is too restrict for open source
2) Some maintainers are familiar vuejs better than reactjs .

**Comment by pjebs** [comment]
facebook relicensed it as MIT due to developer backlash 1 year ago: 

https://thenextweb.com/dd/2017/09/25/facebook-re-licenses-react-mit-license-developer-backlash/

https://github.com/facebook/react/blob/master/LICENSE

**Comment by pjebs** [comment]
**I personally feel this is a mistake for gitea in the long-term.** In terms of development ease, vuejs is only slightly better. But the rest of the ecosystem makes React way better for a project like this. Both are super simple to learn too.

**Comment by techknowlogick** [comment]
Having a large company supporting an opensrouce project shouldn't be a way to judge that project as successful. Gitea has some corporate backing, enough to cover server hosting costs, but not enough to have full time developers on it, and yet it still manages to release a fantastic piece of software.

Anyway, it has been decided that Gitea will be using Vuejs by maintainers, and as such I will be closing this issue. If you wish to have followup discussion please open a thread in the forum.

**Comment by pjebs** [comment]
@techknowlogick  Can you leave it open for 24 hours?

I simply can't find a comprehensive discussion on React vs Vue on the forum (or anywhere).

@0xbaadf00d @adelowo @appleboy @axifive @BetaCat0 @bkcsoft @daviian @ethantkoenig @geek1011 @JonasFranzDEV @kolaente @lafriks @lunny @Morlinest @sapk @strk @tboerger @thehowl 

Can we have a debate/discussion on this somewhere (perhaps on the forum).

It really should be properly sorted rather than 1 person wanting a heat-map component, finding a good Vue based one, and then essentially setting Vue as the standard for the future of this great project.

**Comment by appleboy** [comment]
@pjebs we can move the discussion to https://discourse.gitea.io/

**Comment by tboerger** [comment]
This decision had been made back in time within the maintainers chat. There are already vue components within gitea besides the heatmap, so it's obvious to implement the heatmap feature with vue as well.

More maintainers are familiar with vue, there are less for react.

Since the maintainers are building all that in there limited spare time, I guess nobody of them wants to rebuild the current components with react.

I personally prefer the vue code.

**Comment by tboerger** [comment]
And it sucks pretty much to highlight every maintainer just because you want to restart the discussion.
