### ISSUE TITLE
Delete, edit or remove review comments from the Conversation tab

### ISSUE THREAD

**Issue by Lonami** [go-gitea/gitea#5408]
- Gitea version (or commit ref): 1.6.0
- Git version/Operating system/Database: Not relevant
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (https://try.gitea.io/haloworld/haloworld/pulls/1)
  - [ ] No
  - [ ] Not relevant
- Log gist: Not a crash.

## Description

The Conversation tab does not have buttons to edit or remove review comments. One must select the files tab. The point of the issue is to implement such missing feature.

## Screenshots

Conversation tab, no way to edit or remove the comment:
![image](https://user-images.githubusercontent.com/6297805/49022995-82675a80-f196-11e8-8ed0-aeb4d427b733.png)

Files tab, can edit and remove the comment:
![image](https://user-images.githubusercontent.com/6297805/49023028-914e0d00-f196-11e8-8056-356b358ffac3.png)

I checked for "delete comment" and "remove comment" before in both open and closed issues and couldn't find anything relevant, so I hope this isn't a duplicate.

**Comment by NotAFile** [comment]
This issue is still relevant

**Comment by youssefsharief** [comment]
test

**Comment by kanaksony** [comment]
Yes please, we need to edit the review action. Example If I have finished a review with Comment as a selection from radiogroup and later I want to change it to finish with "Request Changes".

![image](https://user-images.githubusercontent.com/6097596/120528940-9b04fb00-c3f9-11eb-84cc-f472ed9654be.png)

**Comment by wxiaoguang** [comment]
It has been added

![image](https://github.com/user-attachments/assets/53af15b9-ed21-4e13-96c1-49c2fad8db20)
