### ISSUE TITLE
lighttpd reverse proxy not working

### ISSUE THREAD

**Issue by SuNNjek** [go-gitea/gitea#5411]
- Gitea version (or commit ref): 1.6.0
- Git version: 2.11.0
- Operating system: Raspbian 9
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
I'm trying to set up Gitea with lighttpd as a reverse proxy. Because I also have another site on my domain, I want to run at a subpath like so: https://(domain)/git/. For now I've used the settings from the [Gogs FAQ](https://gogs.io/docs/intro/faqs#how-do-i-set-up-a-sub-url-with-lighttpd%3F), but I'm running into a few errors:

- When I log in I get redirected to https://(domain)/git/git throwing a 404
- When I try to create a repository, I get the error "Invalid csrf token.". In the cookie setting the CSRF token is the wrong path again.

I'm running lighttpd 1.4.50.
Is there any difference between setting up lighttpd with Gogs as opposed to Gitea? I've noticed it's missing in Gitea's FAQ as well.

## Screenshots

![gitea2](https://user-images.githubusercontent.com/20151081/49042965-e9eacd80-f1c9-11e8-8d39-04a220ef53b2.png)

![gitea1](https://user-images.githubusercontent.com/20151081/49043112-641b5200-f1ca-11e8-8467-c3e577b59fe5.png)

**Comment by lafriks** [comment]
It should be same as in gogs. Just check that you have correct urls in app.ini

**Comment by SuNNjek** [comment]
I do have my ROOT_URL set to https://(domain)/git/
I have also copied the example from the Gogs FAQ almost verbatim (except for exchanging the path of course).
I also tried removing the trailing slash but that just breaks it more.

**Comment by SuNNjek** [comment]
After trying various things I've decided to abandon this approach and have Gitea running on a subdomain instead. I'm going to close this issue now
