### ISSUE TITLE
U2F 404 error on registration

### ISSUE THREAD

**Issue by rugk** [go-gitea/gitea#5412]
- Gitea version (or commit ref): 1.6.0
- Git version: irrelevant
- Operating system: Debian
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description
Get a 404 on `…/user/settings/security/u2f/register` as I can see when I try to verify the security key.

It is likely some redirect issue or nginx proxy forwarding issue or so…
...

STR:
1. Register new key.
2. Enter name.
3. Click add button.
4. Popup comes up, verify hardware key by press. (that works)

What happens:
still loading

What should happen:
continue to add key

## Screenshots

It does not end loading:

![404](https://user-images.githubusercontent.com/11966684/49047181-e4e04b00-f1d6-11e8-8a2d-83df618bef08.png)

**Comment by mteyssier** [comment]
I got the same error due to a misconfigured ROOT_URL.
Hope this helps.

**Comment by lafriks** [comment]
Can you verify you have correct root url requested?

**Comment by rugk** [comment]
```
ROOT_URL      = https://sub.domain.example/subdirectory
```

Yes, it's correctly set. Also, I'd guess otherwise much more things may break…

**Comment by rugk** [comment]
Still happens. It does two requests (one from website and one from service worker) that end up in 404 errors, after you already pressed the button on your u2f device.

**Comment by zeripath** [comment]
I'm closing this issue as it has received no updates since 2019. Please reopen if there are further issues.
