### ISSUE TITLE
Display 2fa status for all users on Admin's User account list.

### ISSUE THREAD

**Issue by bugbounce** [go-gitea/gitea#5414]
- Gitea version (or commit ref): Not Relevant
- Git version: Not relevant
- Operating system: Not relevant
- Database (use `[x]`): Not relevant
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
For Site administrators it would be helpful to see the 2fa status for all registered users.
...

<img width="1125" alt="screenshot 2018-11-27 at 13 31 38" src="https://user-images.githubusercontent.com/35751394/49067045-d156d380-f21a-11e8-8420-1cb0223445e3.png">

**Comment by r-52** [comment]
If no one is working on this one, could I take a look the next days?

**Comment by lafriks** [comment]
noone is currently working on so you are free to look at this, thanks :)

**Comment by fizzyade** [comment]
This is an important feature for organisations, making sure that your team have 2fa.  

Infact, I'd go as far as to say that there should be an option in team that will only allow access if 2fa is currently enabled on the users account.

**Comment by sapk** [comment]
For insight, you can base yourself on https://github.com/go-gitea/gitea/pull/7621/files that display 2fa status of org member.

**Comment by fizzyade** [comment]
Am I correct in saying that this shows the 2fa status once a user has been added to the organisation?  This I can see in my version.

What I need to be able to do, is see the 2fa status before I add the user to ensure that they've enabled 2fa.

**Comment by sapk** [comment]
@fizzyade yes that for user in organisation. 
I just mention this because tests, UI  and some part of code could be re-used or already exist.

https://github.com/go-gitea/gitea/pull/7621/files#diff-50ac9f9eb4533caadad36718d8cbccd0R37
https://github.com/go-gitea/gitea/pull/7621/files#diff-99af862ff39d136ada33d1bc83487e44R66

**Comment by sapk** [comment]
To respond to @bugbounce, the existing solution is another option (yet similar to option 2) already existing.
There is a function to retrieve the 2fa status of a user list and  return a map linking userid to 2fa status. This map can be linked to context and re-used for display.

**Comment by bugbounce** [comment]
Is anybody working on this ? I think I can manage this in the coming week or so.

**Comment by guillep2k** [comment]
@bugbounce please feel free. 😄

**Comment by zeripath** [comment]
Fixed by #12515
