### ISSUE TITLE
Review not marked as outdated after file deletion

### ISSUE THREAD

**Issue by iyzana** [go-gitea/gitea#5417]
- Gitea version (or commit ref): 1.11.0+dev-120-gac6accef0 (exists since 0da8bc9 / tag v1.6.0)
- Git version: 2.15.3
- Operating system: gitea docker container
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

Steps to reproduce:
- create a new pr, which adds a new file
- add a review to that file
- delete the file again

Repro url: https://try.gitea.io/succcubbus/review-deletion-outdated-repro/pulls/3

Expected:
- review is marked as outdated

Actual:
- review is still shown fully

**Comment by adelowo** [comment]
Yet another valid bug :)
