### ISSUE TITLE
Heatmap renders black squares now

### ISSUE THREAD

**Issue by centennialwebmaster** [go-gitea/gitea#5420]
- Gitea version (or commit ref):
- Git version: commit 2949043 
- Operating system: linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [X] https://try.gitea.io/
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
Heatmap is no longer using shaded colors.  Heatmap squares are now black only.

...

## Screenshots
![image](https://user-images.githubusercontent.com/43613689/49104314-a638a800-f24b-11e8-80a0-f362abdbb578.png)

**Comment by tonivj5** [comment]
Ref https://github.com/go-gitea/gitea/pull/5401#issuecomment-442004127
