### ISSUE TITLE
Links in .org files get mutilated

### ISSUE THREAD

**Issue by zilti** [go-gitea/gitea#5424]
- Gitea version (or commit ref): 1.6.0
- Git version: 2.14.3
- Operating system: NetBSD 8
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes https://try.gitea.io/zilti/OrgTest
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

Links inserted as `[[src/test.org][Testlink]]` will link to the URL `src/test` instead of `src/test.org`.

**Comment by sunbing81** [comment]
Is this issue resolved?

**Comment by lafriks** [comment]
Closing as fixed in migration to go-org library
