### ISSUE TITLE
org-mode rendering causes gitea crash

### ISSUE THREAD

**Issue by adamcavendish** [go-gitea/gitea#5430]
- Gitea version (or commit ref): 1.6.0
- Git version: 2.19.1
- Operating system: Ubuntu 16.04
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL) https://try.gitea.io/adamcavendish/Andersbakken-rtags
  - [ ] No
  - [ ] Not relevant
- Log gist: https://paste.ubuntu.com/p/DCHRRvYCMR/

## Description

Org-mode rendering crashes gitea, though it seems goorgeous's fault. Is it ok to fallback into plain text rendering if goorgeous is not working righ?

**Comment by lunny** [comment]
@adamcavendish could you send a report to upstream repository? https://github.com/chaseadamsio/goorgeous
