### ISSUE TITLE
proposal: include docs how to deploy/install in a shared environment, or state it's not possible

### ISSUE THREAD

**Issue by benzkji** [go-gitea/gitea#5433]
## Description

First, forgive me if this is not the right place to ask for this. But I wandered through docs and read alot, and it seems an installation requires at least some kind of administrative privileges on a server, and also, it probably is not supported on shared hosting environments?

But, as far as I've come now, this seems to be easily possible? just Go and git are required as the very base...would be cool if this could be better explained in the install instructions...as there really is no need to create a specific user for running gitea? 

What I've done: Downloaded binary, put in a separate directory, run it with a specific --port (as this is needed in my shared hosting env, with nginx reverse proxy), called the web frontend, configured database, clicked install, and everything seems ok for now. Might there be some issues when it comes to SSH access for git?

**Comment by benzkji** [comment]
As I see it now, everything is probably working. Only having SSH on port 22 will be not possible, I guess.

**Comment by mckaygerhard** [comment]
yes, due the gitea are a fork of gogs many of the documentation are so ambogous.. some wants more avanced (specially those that wants to package it) and does must try too many times to see what happened!

by example the install from sources does no specify what files must be installed if we does not build using bindata falvor build! also does not xplain in detils those flavors (there's two related to sqlite)

**Comment by mckaygerhard** [comment]
about the installation.. seem using a bindata build the gitea can be run as a cgi application.. but the socket are not well docukented! pufff

**Comment by lafriks** [comment]
Feel free to submit PR with added docs as that is something we really need help with

**Comment by mckaygerhard** [comment]
well i was taking about that we need information.. i have some idea how to deploy as cgi app, but we need to detail about socket flavor event use a port number.. and the compilation process have some hardcoded paths..

**Comment by benzkji** [comment]
well, my issue was another. as this is open source, one needs to dive in oneself, occasionaly. feel free to submit a PR with your findings, or post another, concrete issue, describing your problem (you'll need to provide quite some information, when posting an issue...)

**Comment by mckaygerhard** [comment]
i understand but how we writing or pull a PR if we do not have clear that we have found! by example i compile gitea and i see "options/label" and "options/readme", if i compile without "bindata" i must include that directories in the path/system to deploy? **so how can i write/contribute to documentation if we have not clear that gitea does!**

**Comment by benzkji** [comment]
then, ask, if you got a specific question...

**Comment by mckaygerhard** [comment]
i just asked: now officialy some needs before commig to the cgi related!  in #5466 lest see how faster will answered that
