### ISSUE TITLE
Feature: show Heatmap for Team

### ISSUE THREAD

**Issue by michael-brade** [go-gitea/gitea#5440]
Please also show the heatmap for a team or an organization.

I think it would be preferable to show it just for a selected team, since the team page already has two columns, and the heatmap could be shown above the team members and to the right of the team name panel.

**Comment by jpraet** [comment]
If this is about a heatmap for the activities on a team's repositories, then this is handled in #14159.
If this is about a heatmap for the activities of the team members, then not.

**Comment by zeripath** [comment]
@michael-brade I'm closing this issue as per above. Please re-open and explain what additional things are needed if not.

**Comment by michael-brade** [comment]
Well, this was about the part handled in #14159 and it was about the activities of all the repositories of an Organization.

However, I cannot find the implementation of #14159. What is the URL in gitea to see that dashboard or page? I compiled 1.14.0+dev-403-gf3acb6a3a

**Comment by michael-brade** [comment]
Aha! I found it. Just for reference, it is under `<gitea url>/org/<orgname>/dashboard`.

But with commit 8af9d40 I don't have anything on the left next to "Activities". I can't select any of my teams there.
