### ISSUE TITLE
Admin cannot delete repository via API if he is not the owner of the organization

### ISSUE THREAD

**Issue by ccaspers** [go-gitea/gitea#5442]
- Gitea version (or commit ref): d487a76
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No (cannot become admin there)
  - [ ] Not relevant
- Log gist:

## Description
When logged in as an admin, I can delete arbitray repositories using the web interface. The same is not true when using the API. When trying to delete a repository by requesting `DELETE https://gitea.example.com/api/v1/repos/{owner}/{repo}`, the response's status code is 403 with the body `{"message":"Given user is not owner of organization.","url":"https://godoc.org/github.com/go-gitea/go-sdk/gitea"}`

**Comment by lunny** [comment]
But in fact you should delete a repo as admin via `/api/v1/admin/repos/delete`?

**Comment by ccaspers** [comment]
@lunny if this is possible, documentation is missing on gitea's swagger ui. The route you mention is not listed here https://try.gitea.io/api/swagger
