### ISSUE TITLE
Can't login as user@company.com with ldap authentication enabled

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#5444]
- Gitea version (or commit ref): v1.6.0
- Git version: 2.17.1
- Operating system: Ubuntu 18.04.1
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:
```
xxxx/xx/xx xx:xx:xx [W] Failed to login 'user@company.com' via 'local_ldap': Invalid pattern for attribute 'username' [user@company.com]: must be valid alpha or numeric or dash(-_) or dot characters
xxxx/xx/xx xx:xx:xx [I] Failed authentication attempt for user@company.com from xxx.xxx.xxx.xxx
```

## Description

Additional information:

* OpenLDAP:  2.4.45
* Authentication type: LDAP (simple auth)
* User DN: uid=%s,ou=my_ou,dc=example,dc=com
* User Filter: (&(objectClass=inetOrgPerson)(uid=%s))

Obviously the "@" character is not in a class of allowed characters for "username". Will it be possible to add the "@" in the next version?

**Comment by ghost** [comment]
Sorry, I put the issue in the comment field instead of the description field.

**Comment by lafriks** [comment]
There was already request to add this but `@` can not be added as allowed character as could lead to side effects in other places later on. It would be ok tho to have it replaced or domain part removed for username with additional option

**Comment by ghost** [comment]
I have seen that you can also authenticate via SMTP. For now this is a workaround. Thanks for the quick answer.

**Comment by techknowlogick** [comment]
Closing this issue as a workaround is present. If you have any follow up questions please feel free to open a thread on the [forum](https://discourse.gitea.io/)
