### ISSUE TITLE
keep video html5 tags valid in markdown

### ISSUE THREAD

**Issue by laoshaw** [go-gitea/gitea#5448]
at the moment the video-html5-tag is removed from markdown when it's rendered to html5 page, can we keep it so that we can embed video files directly in markdown and watch it from gitea?

**Comment by uberhalit** [comment]
It seems like it's not possible to embed a video in markdown. The workaround is pretty bad tbh and does not work as intended with local files: `[![video](data/thumbnail.png)](data/video.mp4)` won't link to the raw video but instead to the gitea page of the video resource. Workaround to the workaround:
`[![video](data/thumbnail.png)](../../../raw/branch/master/data/video.mp4)`

**Comment by 6543** [comment]
@laoshaw can you test if this is still the case?

**Comment by laoshaw** [comment]
`[![video](data/thumbnail.png)](data/video.mp4)` will jump to a new gitea page and you can play video.mp4 from there, so not direct embed video in gitea but a workaround.

for `[![video](data/thumbnail.png)](../../../raw/branch/master/data/video.mp4)` it does not jump to a new page, instead it downloads the file directly.

the best still will be "video" tag support, before then  I will use the first option here to get by.

**Comment by lalo-mx** [comment]
Does anyone know if there is an issue for "video" tag support?
