### ISSUE TITLE
Feature to disable "delete repository" option

### ISSUE THREAD

**Issue by yarumair** [go-gitea/gitea#5452]
A very nice to have feature is ability to disable "delete repository" option for users. 
Admin can however delete any repository. This could be implemented within organization or at global level.

Since deleting a repository is unrecoverable so i think there should be some option to remove this ability from user level and retain it for admin only.

**Comment by lunny** [comment]
For an organization, only owners team could delete repositories on this organization. For a person repository, he should have the ability to delete it.
