### ISSUE TITLE
Feature: Allow team user to create repository directly in organization

### ISSUE THREAD

**Issue by yarumair** [go-gitea/gitea#5453]
Feature request to allow team user (other than owner) of the organization to directly add a repository inside organization. 

Currently a user has to create and repository and then transfer it to organization

**Comment by lunny** [comment]
The team who has write permission could create repositories.

**Comment by yarumair** [comment]
HI Lunny,

Iam using v1.6.0 and when i created a new repo and it was created under my name. Iam a member of team who has admin rights, i even switched the context to organization.

is there anything iam missing here?

**Comment by tkurbad** [comment]
I'd like to request this feature, too.

**Comment by lunny** [comment]
Currently, only owner team could create repositories on organization, I think we can add an option on team to allow the team to create repositories or not.

**Comment by tkurbad** [comment]
> Currently, only owner team could create repositories on organization, I think we can add an option on team to allow the team to create repositories or not.

That would be exactly what I am looking for.

**Comment by joebeadle** [comment]
When will this feature be made available?

**Comment by lunny** [comment]
Nobody are working on this.

**Comment by igor9292** [comment]
https://github.com/go-gitea/gitea/issues/5114

**Comment by lunny** [comment]
@igor9292 is right. This is duplicated. Please move to #5114 to discuss further.
