### ISSUE TITLE
Can't see private repositories shared with me on the sharing users' profile

### ISSUE THREAD

**Issue by markusamshove** [go-gitea/gitea#5454]
I was expecting to see a private repository, which is shared with me, on the profile of the user who shared it with me.

To reproduce, I've created two users on `try.gitea.io` (version hash `2d707fe`):

*Granter*
Name: granter
Password: granter

*Receiver*
Name: receiver
Password: receiver

The user `granter` has created two repositories, `PublicRepository` and `PrivateRepository`.
The repository `PrivateRepository` has granted write permissions to `receiver`.

When I log in as `receiver`, I can see the repository `PrivateRepository` on the homepage on the right hand side.
However, when I go to https://try.gitea.io/granter (still logged in as `receiver`), I can only see the `PublicRepository` although I have permissions for `PrivateRepository`.

I think this is not intentional and should also list private repositories on the users profile, if I have at least read permissions

**Comment by markusamshove** [comment]
how do I de-stale it? :)

**Comment by anger32** [comment]
> I think this is not intentional and should also list private repositories on the users profile, if I have at least read permissions

This is a very annoying bug for our dev team =(.
