### ISSUE TITLE
Code comment fails when responding to an older comment which was made on a line which doesnt exist anymore

### ISSUE THREAD

**Issue by kolaente** [go-gitea/gitea#5455]
- Gitea version (or commit ref): bc42b3a
- Operating system: Alpine (running in docker)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Probably
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

Following scenario:

1. I add a new code to the end of a file, which makes the file longer
2. Someone reviews it, stating that extra function in unnessecary. Creates a review comment on the code.
3. Because of said review, I remove the extra code at the end.
4. The comment from earlier on that line is still there
5. I try to answer it and get a 500 error because the line of code doesn't extist anymore.

Logs:
```
2018/12/03 12:53:31 [.../repo/pull_review.go:80 CreateCodeComment()] [E] CreateCodeComment: LineBlame[refs/pull/19/head, /data/git/repositories/vikunja/app.git, lib/models/task.dart, 86]: exit status 128 - fatal: file lib/models/task.dart has only 83 lines
```

I guess that comment should be marked as outdated when the line disappears.

\cc @JonasFranzDEV

**Comment by jameyg** [comment]
This is still a bug, we encountered it today. The comment in question no longer appears in the "Files Changed" view but it does appear in the "Conversation" view still. It seems like the comment should not be showing in the "Conversation" view once the offending line has disappeared from the branch.

**Comment by guillep2k** [comment]
@jameyg What Gitea version are you using?

**Comment by jameyg** [comment]
@guillep2k We just encountered this issue again today, we're using version 1.10.3. A colleague tried to reply to a comment about some lines that had disappeared. This was on the main conversation view of the PR.

**Comment by zeripath** [comment]
Is your code non utf-8?

**Comment by mrsdizzie** [comment]
This is 'fixed' as the comments are now marked as outdated when the code is changed, though the whole code review area could use some rethinking
