### ISSUE TITLE
Feature Request: keeping repo and wiki together

### ISSUE THREAD

**Issue by 4001982248998** [go-gitea/gitea#5459]
When transferring a repo with wiki to a second Gitea server, it would be nice to be able to somehow include the wiki in the cloned repository.

There currently is no option to import the wiki from the repository origin, or even synchronize the wikis.

**Comment by jsfaint** [comment]
You can create a 'New Miragtion' in the target gitea
When mirage repo from outside(github/gitea), gitea will mirage the wiki too.

**Comment by 4001982248998** [comment]
thank you, @jsfaint ! This unfortunately does only work when there is a direct connection between the two hosts. In my case we are working with a SSH tunnel setup.

**Comment by jsfaint** [comment]
@4001982248998 emm, got it. It looks like you need access remote gitea server via proxy.
I'm not sure if environment variables `http_proxy`, `https_proxy` and `socks_proxy` works for this case.
Set these environment variables for local gitea server, then create new migration.

**Comment by lunny** [comment]
I think we have done this. Please feel free to reopen it.
