### ISSUE TITLE
[improve]Search issue or pr by id

### ISSUE THREAD

**Issue by 0000005** [go-gitea/gitea#5462]
- Gitea version (or commit ref):1.6.0
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
I have hundreds of thousands issues and pr. When i want to associate pr with issue,i have to search by issue title. it's very inconvenient. Because after a long time, we created a lot of issue and many of the titles look very similar(same function have a lot bugs).
So i need search pr or issue by id.Such as "#1001".
It's very Important for me.

...

## Screenshots

pic1:
![image](https://user-images.githubusercontent.com/9690089/49436382-f4bde780-f7f3-11e8-933f-cc0426b1b1a2.png)
pic2:
![image](https://user-images.githubusercontent.com/9690089/49436403-0acba800-f7f4-11e8-99a1-307b9f29c441.png)

**Comment by 0000005** [comment]
Can you tell me which release  will implement this feature?

**Comment by lafriks** [comment]
When someone sends PR for it, there is no planning and noone gets paid, so hard to tell :)

**Comment by 0xch4z** [comment]
I'll take this issue.

**Comment by alexanderadam** [comment]
Duplicate of #4109

**Comment by lunny** [comment]
Please continue in #4109
