### ISSUE TITLE
custom URL path format

### ISSUE THREAD

**Issue by milahu** [go-gitea/gitea#5464]
the current URL path format looks like

/$user/$repo/$command/branch/$branch/$filepath

i want the freedom to make it look like

/$user/$repo/branch/$branch/$filepath._$command

with the exception
/$user/$repo/branch/$branch/$filepath
if $command == raw
[redirect or alias from $path._raw to $path]

new restriction:
you cant store files with extension ._$command
as alternative, allow to use 'query format' as in
/$user/$repo/branch/$branch/$filepath?$command
which might annoy some web crawlers [SEO...]

examples:

```
/user/repo/raw/branch/master/file     to /user/repo/branch/master/file
/user/repo/src/branch/master/file     to /user/repo/branch/master/file._src
/user/repo/commits/branch/master/file to /user/repo/branch/master/file._commits
/user/repo/_edit/branch/master/file   to /user/repo/branch/master/file.__edit
/user/repo/_delete/branch/master/file to /user/repo/branch/master/file.__delete
```

... or make urls even shorter, by assuming 'branch/master' as default selector:

```
/user/repo/raw/branch/master/file     to /user/repo/file
/user/repo/src/branch/master/file     to /user/repo/file._src
/user/repo/commits/branch/master/file to /user/repo/file._commits
/user/repo/_edit/branch/master/file   to /user/repo/file.__edit
/user/repo/_delete/branch/master/file to /user/repo/file.__delete
```

use case. how is this useful? for example, to [easily] include other files from a markup file, such as images, scripts, videos, etc. without using the prefix ../../../raw/branch/master/ [static] or rewriting the path as in [markdown.Image](https://github.com/go-gitea/gitea/blob/master/modules/markup/markdown/markdown.go#L104) [dynamic]

this would make gitea more like a content management system.

the path format should be visible to api clients. [print as html meta tag?]

would gitea devs accept an implementation of this request?

- Gitea version: 1.6.0

**Comment by lafriks** [comment]
Theoretically this could be already possible to implement using nginx rewrite rules. I don't see much use case for this built in directly in gitea
