### ISSUE TITLE
build from source not very documented, questions

### ISSUE THREAD

**Issue by mckaygerhard** [go-gitea/gitea#5466]
## Description

1. the documentation now includes "build from source" but then in instalation instructions those are not focused and not in sync with "build from source"..  this due instalation  only assumed that we downloaded from binary and make a binary.. not a specific build.. **so if we compiled by example without bindata what files must be instaled in our paths! (so we do not will include all the gitea sources of course!)**
2. About bindata make build flavor: the documentation said: "_Bundling assets into the binary ... To include assets, they must be built separately using the generate make task._" **so that are too unclear and ambigous. the tag "bindata" will include or not the assets and everithing in the binary or not?**
3. in the same topic of the previous, in the tarball theres a "options" directory that iclude the README's LICENCE's and other files "templates" used into the gitea when manage git repositories, this are always embebed into gitea binary or not?
4. more questions sure will comming, but please answer very detailed the previously

**Comment by mckaygerhard** [comment]
a demostration of the proble seems are in the log when start the daemon compiled in no-bindata mode:

> panic: fail to set message file(en-US): open conf/locale/locale_en-US.ini: no such file or directory

those files seems are the located under "options" directory

**Comment by mckaygerhard** [comment]
please i need some of the answers, wicht files must be copied to the instal paths? 

a demostration of the proble seems are in the log when start the daemon compiled in no-bindata mode:

> panic: fail to set message file(en-US): open conf/locale/locale_en-US.ini: no such file or directory

those files seems are the located under "options" directory

**Comment by mckaygerhard** [comment]
IF i uses binary donwload, **in cgi mode with a socket path, where will be search the files if all are from the binary path?!**, taking in consideration that files in cgi must be exposed in the webserver and are working with request and response and not as deamon!

**Comment by techknowlogick** [comment]
1. If you build from source without bindata tag, then files being in the same path as gitrepo (as that will allow you to commit the changes to assets if you make any)
2. using TAG bindata will include binary assets in binary.
3. these will be included in binary if you use bindata tag

Make sure to keep built binary (for dev) in root of git repo so it can use assets if not bundled into binary.

Using socket path should not have an effect on assets (again, for non-gitea development purposes it is recommended that you bundle assets into binary).

Closing this issue for now. Please ask questions such as this in forum (https://discourse.gitea.io/)

**Comment by mckaygerhard** [comment]
as @techknowlogick suggested: https://discourse.gitea.io/t/issue-5466-improve-documentation-and-colaboration/769 please answer me due you only answered one question here, and the other too are not that i said!

**Comment by mckaygerhard** [comment]
well stil no tech answers on the threat topic at the forum..
