### ISSUE TITLE
Proposal: Add KiwiIRC as a chat system, either as Gitea plugin or core feature.

### ISSUE THREAD

**Issue by srmcgann** [go-gitea/gitea#5469]
Kiwi IRC (https://github.com/kiwiirc/kiwiirc) would like to explore the possibility of partnering and implementing Kiwi as a communications platform within Gitea, in the same manner as Mattermost on Github and Gitlab. Kiwi is a robust, open, highly customizable, web-based IRC client that can enable Gitea users to communicate easily on projects, with the potential to integrate tightly with Gitea hooks for in-channel notifications (builds, pushes, etc). 
Kiwi is actively developed by a staff of 7 developers, and other open source contributors. If this proposal is accepted, we could begin working on one or more PR's to integrate Kiwi into Gitea. Looking forward to working together!

**Comment by lafriks** [comment]
You are more than welcome submit PR's for webhook support but I'm not sure if there is anything more to be integrated. If anything more than webhooks can you please describe more on what kind of integration

**Comment by srmcgann** [comment]
Hi @lafriks, our hope is that Gitea can benefit by including a system for users to chat with each other, share code and files/images, similar to how slack works, but with tight integration with Gitea. This kind of thing has been implemented in Github and Gitlab (using the Mattermost chat platform). Kiwi is FOSS and has been around for a long time, making it perfect for such a thing. Ideally Kiwi would be added to the Gitea core as an optional module or plugin that can be enabled by whomever installs Gitea. Kiwi would run on the same hardware as Gitea, and enable users to collaborate and get in-channel notices whenever something is pushed, merged, updated, etc. The channel(s) would be accessed via a link to the same server that Gitea runs on.

**Comment by adelowo** [comment]
> Kiwi is FOSS and has been around for a long time, making it perfect for such a thing. Ideally Kiwi would be added to the Gitea core as an optional module or plugin that can be enabled by whomever installs Gitea. Kiwi would run on the same hardware as Gitea, and enable users to collaborate and get in-channel notices whenever something is pushed, merged, updated, etc.

I believe this is already possible with webhooks.

**Comment by srmcgann** [comment]
Basically, we (Kiwi) would be getting exposure and an opportunity to perform, and Gitea would be getting a valuable new feature. For example, Gitlab comes packaged with Mattermost at its core, as a communications platform which can be optionally enabled via config. As an embedded solution, it is streamlined for ease of installation (pretty much zero effort required), and comes ready with a suite of webhooks already configured out of the box. Of course Kiwi *could* be rigged up as an external plugin, but such would surely require extra work on the part of the user. Perhaps a demo of Kiwi would help shed some light: https://kiwiirc.com/nextclient/irc.freenode.net/#gitea-test

**Comment by lafriks** [comment]
But if I understand kiwi is just client and still needs irc server, right?

**Comment by kolaente** [comment]
What more would you need which could not be done via webhooks? Maybe incoming webhooks, but IMHO that'd be another pr, nothing special with kiwi integration.

**Comment by ShalokShalom** [comment]
I would be very interested in this, once Kiwi has added history support. 

Also, it should be clearly distinguished between pure client support or still relying on a host like kiwiirc.com

[Mattermost now gets support in Gitea ](https://github.com/mattermost/mattermost-server/issues/10923) so in order to shine, tight integration and history support should be included.

**Comment by lunny** [comment]
@ShalokShalom If I'm not wrong, that's issue was only be closed since there is a vote for that but not it's resolved.

**Comment by ShalokShalom** [comment]
The Mattermost dev describes this implementation as trivial and important.

**Comment by Dark-Feather** [comment]
I have a KiwiIRC instance alongside my Gitea install -- I put a link to the KiwiIRC vHost into `custom/templates/custom/extra_links.tmpl` and I have an InspIRCd/Anope stack that KiwiIRC ties to. 

It would be nice if #1089 would allow us to use [irker](https://gitlab.com/esr/irker) or something similar as a webhook target for notifications.

**Comment by Dark-Feather** [comment]
I have successfully been able to get https://github.com/jesopo/bitbot to work to take Gitea POST JSON hooks and publish them to channel. Combining that with https://github.com/prawnsalad/KiwiIRC.git, https://github.com/inspircd/inspircd, and https://github.com/anope/anope and I have a self-contained chatops stack implemented.

**Comment by ShalokShalom** [comment]
@techknowlogick Why is this closed?
