### ISSUE TITLE
Webhooks randomly fail with 408 timeout

### ISSUE THREAD

**Issue by sbrl** [go-gitea/gitea#5470]
- Gitea version (or commit ref): 1.6.0 (latest stable release
- Git version: git version 2.17.1 (on the server)
- Operating system: Ubuntu Server 18.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist: ?

## Description
I've setup a webhook between my server and a server at a remote location, I'm getting random failures. Some webhooks go through fine, and others die for some strange reason.

Setup:
 - Git Server:
     - Gitea behind nginx
 - Remote server:
      - [webhook](https://github.com/adnanh/webhook) behind nginx

Gitea claims the following in the webhook log:

```
Delivery: Post https://ci.starbeamrainbowlabs.com/hooks/laminar-config-check: read tcp 5.196.73.75:54504->x.y.z.w:443: i/o timeout
````

...but the remote server's nginx claims that it's Gitea's fault for not sending a complete request in time:

```
5.196.73.75 - - [04/Dec/2018:20:48:05 +0000] "POST /hooks/laminar-config-check HTTP/1.1" 408 0 "-" "GiteaServer"
```

The remote server has a good-quality fibre line. The git server has a stable 100mb/sec connection from KimSufi / OVH. Why the timeout?

Annoyingly, it _always_ works if I hit "test delivery" - it's only genuine push events that are causing problems.

## Screenshots
![selection_094](https://user-images.githubusercontent.com/9929737/49472617-cba75200-f807-11e8-8eff-5d90fdd1ec68.png)

**Edit:** Nope, it doesn't always work with the "test delivery" button. I've just got this:

![selection_095](https://user-images.githubusercontent.com/9929737/49473210-53da2700-f809-11e8-882a-84c94ff23359.png)

....clicking the "test delivery" button again causes the next one to succeed though.

**Comment by sbrl** [comment]
Anyone at all? @lunny? Someone?

**Comment by barryp** [comment]
I'm getting a similar thing sort of randomly

    Delivery: Post http://www.home:9100/hooks/deploy-site: read tcp 10.0.0.107:12078->10.0.0.101:9100: i/o timeout

If I try a Test Delivery, it usually works fine, although that could be because the first invocation already did some time-consuming downloads - and the second invocation can complete much quicker.  I'm using the same  [webhook](https://github.com/adnanh/webhook) @sbrl is using, although not behind nginx.  The script it invokes can take maybe 5-15 seconds, perhaps even longer.  It'd be nice to know what the timeout was, and even better if it could be configurable.

**Comment by sbrl** [comment]
I think the timeout is already configurable, @barryp. It's this in `custom/app.ini`:

```ini
[webhook]
DELIVER_TIMEOUT = 60
```

....60 is the value I have set. If I try the "test" delivery, it does work fine some of the time. If I try it manually with `curl` _from the same host_, it _always_ works. I think it's definitely a bug in Gitea.

**Comment by sbrl** [comment]
I can confirm that this is still an issue with the latest v1.7.0 release of Gitea.

**Comment by sbrl** [comment]
Furthermore, I have a `tcpdump` capture that demonstrates the issue. It's a HTTPS connection, but hopefully still proves useful. Contact me (my email address is `bugs at starbeamrainbowlabs dot com`) to obtain said dump.

_(Note to self: It's in my downloads)_

**Comment by joyqat** [comment]
Have the same problem
![image](https://user-images.githubusercontent.com/10184445/53627628-e9882580-3c43-11e9-97d4-7f31decdca7d.png)
It might be a network problem. Does Gitea have a "retry when failed" config?

**Comment by lunny** [comment]
@sbrl You can send message to me on discord.

**Comment by sbrl** [comment]
Looks like I have issues with GitHub sending Webhooks to the same server, so I think it's probably a network issue. Thanks for investigating though!

**Comment by c0h1b4** [comment]
I am having this same issues on a kubernetes deployment of Gitea with Drone.io.

Randomly Delivery: Post https://xxxxx/hook?...: dial tcp: i/o timeout

Sometimes it goes smooth, sometimes it stalls. Then if I press "Test Delivery" it goes thru. An auto retry with a X number of tries would probably fix it.

**Comment by lafriks** [comment]
That could also be network connectivity issues or dns problems

**Comment by c0h1b4** [comment]
No. The issue here is that I'm using a small arm cluster with kubernetes. Sometimes the timeout is > 5 secs. I fixed increasing the webhook timeout to 30 secs. But I believe that an automatic retry for a custom number of tries would be very welcome.

**Comment by sbrl** [comment]
What a co-incidence, @c0h1b4! My situation was something like this:

Gitea server ----> [ Internet ] -----> Home router ------> Raspberry Pi

If you're having issues with arm, maybe it's a bug in the linux networking stack for arm? I've no clue how to start debugging that though.

I'm pretty sure it's a network issue and nothing to do with Gitea. I know this because I setup a GitHub webhook that pointed tot he same place, and it also failed randomly in the exact same fashion.

I ended up writing a PHP proxy script that does the automatic retry that I run on a more stable box in the cloud (incidentally, this is the same box that has the Gitea server running). Said script looks a bit like this: https://pastebin.com/Un9B01s1

Very curious indeed.

**Comment by src386** [comment]
I think I have the same issue, in a amd64 Docker environment.
Test delivery never worked (i/o timeout) but using curl with the same url works.
Tested both https (via traefik) and http (direct container to container).

Adding the ```DELIVER_TIMEOUT = 60``` option slightly improves the situation, now I get HTTP 500, at least it's something.

**Comment by sbrl** [comment]
Have you tried it with GitHub too, @src386?

**Comment by deanpcmad** [comment]
I'm also having this issue and I've tried multiple ways of trying to fix it...

- Gitea in a docker container at home
- Gitea running normally at home
- Gitea on Docker on a VPS
- Gitea running normally on a VPS
- Both a clean database and imported database

I get the same i/o timeout issue no matter what I do. Of course webhooks are quite important especially with CI/CD. I was hoping to move to Gitea this weekend but after spending hours trying to get this work, I'm not sure now lol

**Comment by c0h1b4** [comment]
> I'm also having this issue and I've tried multiple ways of trying to fix it...
> 
> * Gitea in a docker container at home
> * Gitea running normally at home
> * Gitea on Docker on a VPS
> * Gitea running normally on a VPS
> * Both a clean database and imported database
> 
> I get the same i/o timeout issue no matter what I do. Of course webhooks are quite important especially with CI/CD. I was hoping to move to Gitea this weekend but after spending hours trying to get this work, I'm not sure now lol
> 
> Edit: using the latest stable version of Gitea btw which is 1.9.4
> 
> Another edit an hour later: I've sorted it. Turns out Drone checks if there's a `.drone.yml` file and if there isn't one, it won't allow a webhook? Very odd but glad I've sorted it!

Did you tried playing with the `DELIVER_TIMEOUT` parameter in the config? It helped me to fix this issue.

**Comment by sbrl** [comment]
Many root causes, 1 symptom.

**Comment by Veitor** [comment]
same problem..
- I have set `DELIVER_TIMEOUT=30` and still timeout. 
- I execute `curl <webhook URL>` command inside my gitea container, it's very fast and no problem.
- I test webhook within another repository, it's worked. This repository's webhook URL is same with previous repository's webhook URL, all they are my Drone CI adress.
 How can it time out?
![image](https://user-images.githubusercontent.com/7483890/75736641-c4d3fb80-5d38-11ea-8168-69af34e72903.png)
![image](https://user-images.githubusercontent.com/7483890/75736695-dcab7f80-5d38-11ea-90b0-a1d19981a8ff.png)
![image](https://user-images.githubusercontent.com/7483890/75736767-0e244b00-5d39-11ea-9541-03a5ec64135f.png)

**Comment by Veitor** [comment]
> same problem..
> 
> * I have set `DELIVER_TIMEOUT=30` and still timeout.
> * I execute `curl <webhook URL>` command inside my gitea container, it's very fast and no problem.
> * I test webhook within another repository, it's worked. This repository's webhook URL is same with previous repository's webhook URL, all they are my Drone CI adress.
>   How can it time out?
>   ![image](https://user-images.githubusercontent.com/7483890/75736641-c4d3fb80-5d38-11ea-8168-69af34e72903.png)
>   ![image](https://user-images.githubusercontent.com/7483890/75736695-dcab7f80-5d38-11ea-90b0-a1d19981a8ff.png)
>   ![image](https://user-images.githubusercontent.com/7483890/75736767-0e244b00-5d39-11ea-9541-03a5ec64135f.png)

ok. I have solved this problem.
my gitea repository's webhook is Drone URL. and the point is that CI `repository - setting - Main - Configuration` specified  yaml file named `.drone.yml`, and my git repository's file named `drone.yml`!!
that's worker after modified file name... :)

However, this problem should not caused timeout error, network has no problem!

**Comment by deanpcmad** [comment]
^ Yeah my thoughts too

**Comment by sbrl** [comment]
Glad you fixed it! :D

Although for future reference if you see these symptoms, it's almost certainly the particular issue I experienced here.

**Comment by ryanlelek** [comment]
This thread helped. 
- increased `DELIVER_TIMEOUT` to 30 (or 60) but still had issues
- curl-ing from the container worked fine
- adding `.drone.yml` to repo fixed the problem (if your webhook destination is Drone)
Not scientific, sharing my vague experience with others that find this via search :)
