### ISSUE TITLE
The DUMP command does not create any SEQUENCE objects when using postgresql

### ISSUE THREAD

**Issue by oicq1699** [go-gitea/gitea#5472]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:

## Description

I use postgresql 11, Gitea version 1.6.0, I use the dump command to generate a backup file, When I perform the restore operation, the system reports table_id_seq does not exist error. I checked the gitea-db.sql file and found that there are no statements for creating all SEQUENCE objects. I tried to export with the pg_dump command that comes with postgresql, everything works fine. I think this should be a bug.

**Comment by ghost** [comment]
This looks to be the same as #4407

**Comment by oicq1699** [comment]
> This looks to be the same as #4407

Yes, the same problem, but it has not been solved. I also use the methods you provide to recover the database.

**Comment by lafriks** [comment]
Closing as duplicate of #4407

**Comment by belminf** [comment]
@oicq1699 FYI, had similar issue. Posted how I fixed it at #4407 .
