### ISSUE TITLE
Display the branch name in the commit view

### ISSUE THREAD

**Issue by oto-ledger** [go-gitea/gitea#5473]
- Gitea version (or commit ref): 1.6
- Git version: unknown
- Operating system: 
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

Would it be possible to display the branch a commit belongs to when displaying in the commit tab?
When managing multiples branches and having a peer review system, it's quite tedious to make sure the commit being reviewed belongs to a branch or another.
Many thanks,

## Screenshots

For example on the try.gitea.io
https://try.gitea.io/mike/ha-jdbc/commit/9ca1d6d82f3d0d7ba68f738812f84d26f6019df2

We don't even know it's a commit on master (I even haven't checked)

**Comment by adelowo** [comment]
/reviewed/confirmed

**Comment by adelowo** [comment]
Can this be reopened until https://github.com/go-gitea/gitea/pull/5950 is merged?

**Comment by zeripath** [comment]
Sorry it was closed automatically when the git PR was merged
