### ISSUE TITLE
No push with integrated SSH server

### ISSUE THREAD

**Issue by benzkji** [go-gitea/gitea#5474]
- Gitea version (or commit ref): 1.6
- Git version: 2.11.0
- Operating system: Ubuntu
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description

Push to repos does not work, using the built in SSH server.
https://gist.github.com/benzkji/74668d1ed5f25596861ce944749047ea

I'am running gitea behind a reverse proxy, but SSH is exposed directly (61005). The server is running, but produces the stack trace when trying to push.

```
LOCAL_ROOT_URL   = http://localhost:62070/
DOMAIN           = localhost
HTTP_PORT        = 62070
ROOT_URL         = https://realdeal.com/
DISABLE_SSH      = false 
START_SSH_SERVER = true
SSH_DOMAIN       = realdeal.com
SSH_PORT         = 61005
SSH_LISTEN_PORT  = 61005
```

maybe related: #3226 / #1685 (same error)
though, my `LOCAL_ROOT_URL` is set (hopefull correctly), I can `wget http://localhost:62070/`

**Comment by lunny** [comment]
Maybe add depends on mysql or postgres?

**Comment by benzkji** [comment]
@lunny why? It now works, finally. I added

    HTTP_ADDR = 127.0.0.1

but not sure if that was it. I also changed some systemd settings (removed type=simple, added after=network.target).

systemd is still sometimes is a mysterium, for me at least.

**Comment by lunny** [comment]
right you should add two after, one is for network, another is for your database.
