### ISSUE TITLE
Migration failed: SSL Certificate problem: unable to get Local Issuer

### ISSUE THREAD

**Issue by toni-moreno** [go-gitea/gitea#5475]
- Gitea version (or commit ref): fdec258 
- Git version: git inside gitea 2.18.1
- Operating system: (working on docker oficial image gitea/gitea) alpine 3.8.1
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:
````bash
2018/12/05 12:15:21 [.../api/v1/repo/repo.go:409 Migrate()] [E] MigrateRepository: Clone: exit status 128 - fatal: unable to access 'https://%3Ccredentials%3E@myserver/my-repo.git/': SSL certificate problem: unable to get local issuer certificate

2018/12/05 12:16:04 [.../api/v1/repo/repo.go:409 Migrate()] [E] MigrateRepository: Clone: exit status 128 - fatal: unable to access 'https://%3Ccredentials%3E@myserver/my-repo.git/': SSL certificate problem: unable to get local issuer certificate
````

## Description
Can not clone from internal (self-signed ) gitlab servers and there is not option into the UI to configure the git client config like 
````
git config http.sslVerify false
````

 How can I allow the migration from "unsecured" SSL gitlab servers?
...

**Comment by lafriks** [comment]
You can import ssl certificate in server certificate store and restart gitea as workaround

**Comment by lunny** [comment]
@toni-moreno you could change `git config --global http.sslVerify false` on gitea server host.

**Comment by toni-moreno** [comment]
export GIT_SSL_NO_VERIFY=true  on the docker image work for me Thank you!!

**Comment by giorgosn** [comment]
> git config --global http.sslVerify false

It did not worked for me. On a gitea server and a jankins server.
