### ISSUE TITLE
bug: cannot edit branch once issue was created

### ISSUE THREAD

**Issue by mckaygerhard** [go-gitea/gitea#5476]
- Gitea version (or commit ref): 1.6.0
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

In issues cannot edit the branch associated once the issue was created!

## Screenshots

![canot-edit-associated-brand](https://user-images.githubusercontent.com/1571724/49517520-c59a8b00-f872-11e8-9a65-dacce3b36c1d.png)

**Comment by mckaygerhard** [comment]
@Etzelia do you see in image the "master" asociated branch? in the issue, once created i try to change the related associated branch and i cannot do it! pufff!

**Comment by lafriks** [comment]
It is not bug, it is just way it is implemented

**Comment by mckaygerhard** [comment]
umm ok so then we need a feature to edit/change if a user make misctake or get wrong branch right?

**Comment by mckaygerhard** [comment]
this was resolved at 1.7.1 ?? what about 1.6.X ??? not all users have golang 1.11 and vendors provide security patches backported to golang 1.8 and 1.9!
