### ISSUE TITLE
Can't clone using SSH

### ISSUE THREAD

**Issue by BakkFail** [go-gitea/gitea#5479]
- Gitea version (or commit ref): 1.3.2
- Git version: 2.7.4
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
Hello, I just installed Gitea for a personal use. Everything was working fine, until I discovered that SSH clone just doesn't function. Cloning using HTTP is completely functional, but I get `Permission denied (public key)` all the time. However, I can connect with SSH and get the `Hi there, You've successfully authenticated, but Gitea does not provide shell access. If this is unexpected, please log in with password and setup Gitea under another user.` message. I just don't know what to do at that point.

...

**Comment by er1z** [comment]
Are you using embedded SSH server or external one? 

> `Hi there, You've successfully authenticated, but Gitea does not provide shell access. If this is unexpected, please log in with password and setup Gitea under another user.`

It's normal because shell is restricted to git-only things.

**Comment by BakkFail** [comment]
I'm using OpenSSH. (and I know that shell is not available, it was just to show that my key was accepted)

**Comment by BakkFail** [comment]
Yes

**Comment by zeripath** [comment]
Hmm. Ok, what user is gitea running under? It should not be root! It should be, by default, git.

Does this git user have access to the gitea repositories and can change them? I.e. are they owned by git?

**Comment by techknowlogick** [comment]
Please also update to a more recent version of Gitea (1.7.1 was just released), and try again.

**Comment by techknowlogick** [comment]
Closing issue. Please open a post in the [forum](https://discourse.gitea.io/) if this is still an issue.
