### ISSUE TITLE
404 for API request against /user/{username}/orgs

### ISSUE THREAD

**Issue by ChriFo** [go-gitea/gitea#5485]
- Gitea version (or commit ref): 328e38e built with: bindata, sqlite
- Git version: 2.15.3
- Operating system: Docker/Alpine
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant

## Description

An GET request against https://try.gitea.io/api/v1/user/krischan157/orgs should return one organization called _tree_. But the response is an HTTP 404.

The GET request against https://try.gitea.io/api/v1/user/orgs is correctly returning the tree organization.

For both requests the user krischan157 was used for authorization.

**Comment by lunny** [comment]
You should visit `https://try.gitea.io/api/v1/users/krischan157/orgs` but not `https://try.gitea.io/api/v1/user/krischan157/orgs`

**Comment by ChriFo** [comment]
@lunny Thanks. You are right. But the request against https://try.gitea.io/api/v1/users/krischan157/orgs ist empty, too. Response code ist 200.
