### ISSUE TITLE
Upgrading from v1.4.3 to v1.6.0 failed

### ISSUE THREAD

**Issue by oliviergareau** [go-gitea/gitea#5491]
- Gitea version (or commit ref): v1.6.0
- Git version: 2.11.0
- Operating system: Debian GNU/Linux 9 (stretch) 4.14.52
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist: [Link](https://gist.github.com/oliviergareau/6296fc6c36beb796363bece35f1e4de5)

## Description

I have been using Gitea v1.4.3 for the past ~5 months without any issues and have decided to upgrade to v1.6.0. I have made a full backup with `gitea dump` prior to upgrading. After, I did a `git checkout` on the v1.6.0 tag, built the binary with `make`, and restarted gitea. It seems like the database migration is failing? Reverted back to v1.4.3 for the time being and gitea seems to run just fine :smiley:. 

Thank you in advance for your time and for making such a great free git service!

**Comment by lunny** [comment]
could you give some detail of the logs?
