### ISSUE TITLE
Support Webhook for Typetalk?

### ISSUE THREAD

**Issue by is2ei** [go-gitea/gitea#5496]
## Description

HI, 
It looks gitea has webhook feature for some chat apps (i.e. Slack, Discord). How about supporting [Typetalk](https://www.typetalk.com) too? If this suggestion is acceptable, I'd like to create PR.

**Comment by techknowlogick** [comment]
@is2ei PRs are very welcome 😄

**Comment by is2ei** [comment]
Created PR. Could you review it, please? 😺 
https://github.com/go-gitea/gitea/pull/5548
