### ISSUE TITLE
Support deleting org via api

### ISSUE THREAD

**Issue by abulfatmasimov** [go-gitea/gitea#5499]
- Gitea version (or commit ref): 1.6.0
- Git version: 2.15.3
- Operating system: Linux
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

At the moment, deleting organization seems only possible via WebUI. Asking to make it available via API as well.

**Comment by shashvat-kedia** [comment]
@lafriks Can I work in this?

**Comment by techknowlogick** [comment]
@sd1998 yes

**Comment by techknowlogick** [comment]
Closing as PR has been merged.

**Comment by abulfatmasimov** [comment]
Thank you @sd1998 and team for this!
