### ISSUE TITLE
Closer Github UI look

### ISSUE THREAD

**Issue by DblK** [go-gitea/gitea#55]
When we have a look to Gitea compared to Github it's look alike but there are several color and menu ui tweak that still need to be done.

On the other hand, semantic ui provide a good template that look like Github better than Gitea do.
I think an improvement can be done around semantic to see why Gitea doesn't seems to look as it should.
Maybe an update of the vendor css or something else.

After this step, the theming feature should be a plus  (I will make another issue for that).

**Comment by tboerger** [comment]
Nope, forget it. We are forced to look different than GitHub, otherwise we will end up like this: https://gitbucket.github.io/gitbucket-news/gitbucket/2016/03/20/change-user-interface.html

**Comment by DblK** [comment]
I didn't know about that.
Thanks
