### ISSUE TITLE
serviceworker.js & manifest.json not found

### ISSUE THREAD

**Issue by yarumair** [go-gitea/gitea#5505]
- Gitea version (or commit ref):1.6.0
- Git version:2.17.1
- Operating system:ubuntu 18.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ x] No
  - [ ] Not relevant
- Log gist:
https://gist.github.com/yarumair/090ea2332e8ef7f3cfa0412a783dbe0c
## Description
Iam getting `404` both for ` /manifest.json` and `/serviceworker.js`.

I have setup gitea behind nginx proxy as:
```
server {
	listen 443 ssl;
	server_name xxx.xxx.xx;
	
	
	ssl_certificate /etc/letsencrypt/live/xxx.xxx.xx/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/xxx.xxx.xx/privkey.pem;

	client_max_body_size 0;

	location / {
		proxy_pass https://localhost:2052;
	}

	location ~ /\.ht {
			deny all;
	}

	
	access_log /var/log/nginx/xxx.xxx.xx.access.log;
	error_log /var/log/nginx/xxx.xxx.xx.error.log;
}
```
Following files/folders are placed here `/var/lib/gitea/custom`
```
robots.txt
public
templates
https
```
Following is the link for `app.ini`

https://gist.github.com/yarumair/74d4dfc14dac520f32903141b86d414d

No error at nginx level for this.

**Comment by lunny** [comment]
could you reproduce that on https://try.gitea.io

**Comment by yarumair** [comment]
HI @lunny 

Iam not sure i can do it. Since, i have done certain customization in app.ini and also using custom folder. Moreover iam running behind nginx as proxy. Not sure if this is possible to replicate on https://try.gitea.io.

On try.gitea.io both `manifest.json` and `serviceworker.js` are showing fine.

If you see my log there is one consistent error:

`[...s/context/context.go:147 NotFoundOrServerError()] [E] GetRepositoryByOwnerAndName: repository does not exist [id: 0, uid: 0, owner_name: !api, name: 2.0]`

which led me to believe that somehow Gitea is treating both the files as repository and searching for them.

So any pointers in right direction to debug are highly appreciated
