### ISSUE TITLE
Nginx returns "upstream timed out" when IPv6 is enabled on the host

### ISSUE THREAD

**Issue by mircolino** [go-gitea/gitea#5513]
I have both nginx v1.15.7 and gitea 1.6.1 running on a Windows 2016 server with both ipv6 and ipv4 stacks enabled and with ipv6 priority (ping gitea.contoso.com resolves to an ipv6 address).

Gitea config:

```
[server]
PROTOCOL         = https
DOMAIN           = gitea.contoso.com
HTTP_ADDR        = gitea.contoso.com
HTTP_PORT        = 3000
CERT_FILE        = C:/Inet/cert/contoso.pem
KEY_FILE         = C:/Inet/cert/contoso.pem
ROOT_URL         = https://git.contoso.com/
```

Nginx config:

```
server {
    listen                  public.contoso.com:443 ssl;
    server_name             ~(?i)^git\.contoso\.com$;

    location /              {
        proxy_pass          https://gitea.contoso.com:3000;
    }
}
```

With the above configuration gitea listens by defaults to the ipv4 address while nginx proxies to the ipv6 address and returns "upstream timed out" error.

If I explicitly configure gitea with the ipv6 address (instead of the hostname) everything works fine.

Is there a way to have gitea adhere to current Windows ip stack prioritization?

**Comment by veita** [comment]
Normally this should not be an issue if Gitea proxied by Nginx on the same host would be configured to listen on the loopback interface, either with an ipv4 or ipv6 address.

Is there a reason to provide the Gitea service on both port 443 and 3000, and not doing SSL offloading on Nginx?
