### ISSUE TITLE
Upgrade on freebsd from repo 1.4 to 1.6 left the database untouched

### ISSUE THREAD

**Issue by ralf-freihaendig** [go-gitea/gitea#5519]
- Gitea version (or commit ref): 1.6
- Git version: 
- Operating system: freeBSD
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:

## Description
Upgrade using the repo from 1.4 to 1.6.

The "gitea admin change-password" command quit with an error. 
It misses the columns:
- user.must_change_password 
- user.language

Created the columns manually by using sqlite3 and the command ran successfully again. 
Please check the migration process.

**Comment by techknowlogick** [comment]
Closing. Please re-open if the above suggestion didn't work.
