### ISSUE TITLE
Wrong domain name in repository url

### ISSUE THREAD

**Issue by yusiwen** [go-gitea/gitea#552]
I've run my own gitea instance for a long time and it works fine all the time until today, I git pulled the latest `master` branch from here. And the URL of every repo becomes something like `git@localhost:USER/REPO.git`, which should be `git@MYDOMAIN:USER/REPO.git`.

In `custom/conf/app.ini` , I've set `DOMAIN` to my domain, and it worked before. What's wrong? Is there something changes in the config file?

- Gitea version (or commit ref): b7e1bccc501c5246e6f8b9bed4853b90e9a447c5
- Git version: 2.10
- Operating system: Ubuntu 16.04 X64
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant

Thanks

**Comment by 0xbaadf00d** [comment]
Same here, it seems only "ssh" link is affected.

**Comment by yusiwen** [comment]
OK, it works after adding `SSH_DOMAIN` to my `custom/conf/app.ini`, in the `server` section.

Thanks

**Comment by guyspr** [comment]
Would be nice to see this added in the config cheat sheer (https://docs.gitea.io/en-us/config-cheat-sheet/). I ran into this issue and was able to find it here, but would have found it more quickly if it was documented.

**Comment by appleboy** [comment]
@guyspronck This PR https://github.com/go-gitea/docs/pull/75

cc @lunny @tboerger
