### ISSUE TITLE
Dashboard not displaying commit activity details

### ISSUE THREAD

**Issue by oliviergareau** [go-gitea/gitea#5528]
- Gitea version (or commit ref): v1.6.1
- Git version: 2.11.0
- Operating system: Debian GNU/Linux 9 (stretch) 4.14.52
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist: [LINK](https://gist.github.com/oliviergareau/018598e49dc7602f48dfec947e3327a9)

## Description

Upgraded from v1.4.3 to v1.6.1. Everything seems to work fine, except the Dashboard, which won't display recent commit details anymore. Log details are attached in the gist above, and a screenshot is available on imgur at the link below. :smiley: 

## Screenshots
https://i.imgur.com/rnZsONb.png

**Comment by lunny** [comment]
could you reproduce that on https://try.gitea.io ? I cannot reproduce it locally.

**Comment by oliviergareau** [comment]
I can't reproduce it on try.gitea.io.

**Comment by smorks** [comment]
I'm having the same issue on 1.6.0, running on Arch Linux, with MySQL as the database.

I checked the "action" table (i'm assuming that's where the info is coming from) and no commits since i upgrade from 1.5.3 to 1.6.0 have been added to the action table.

i couldn't find any relevant errors in any gitea log files either.

i'll try and do some deeper investigation to see if I can figure out why it's happening.

**Comment by oliviergareau** [comment]
I just tried creating a new repo and pushing to it. It seems that the commits are showing up in the dashboard, but commits from **before migrating to 1.6.1 are not showing up**. So in my case it does not seem to be a permissions issue.

Also, looking at my log gist in OP, there seems to be an error:
`ERROR: invalid character '\n' in string literal`

Screenshot of newer commits appearing: https://i.imgur.com/QjrJBpW.png

So I guess it is safe to say that this bug is for the most part harmless, since soon enough there will not be any old commits displayed on my dashboard, right?
