### ISSUE TITLE
File names truncated in table view

### ISSUE THREAD

**Issue by veita** [go-gitea/gitea#5529]
- Gitea version (or commit ref): 1.6.1
- Git version: 2.11.0
- Operating system: Debian Stretch
- Database (use `[x]`):
  - [ x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ x] Not relevant
- Log gist:

## Description
File names are being truncated in tabular views. Since we have several repositories with many files with common prefixes it is impossible to select the desired file e.g. from the project main page.

On the other hand, there's more than enough space left for the commit messages. Given, that by common convention, the commit message headline is limited to 50 characters this should usually be the case. So a solution could be to make file name columns wider and decrease the width of commit headline columns. Ideally these could be configuration parameters.

## Screenshots
![gitea-column-width-issue](https://user-images.githubusercontent.com/419665/49858308-da3bcd80-fdf4-11e8-9c81-3f04fe11f16c.png)

**Comment by veita** [comment]
Prevent this from being closed: The problem persists in version 1.7.1.

**Comment by zeripath** [comment]
Hi could you check in try and on 1.8-rc. We put a title attribute on the filenames to help them be more visible.

Would that solve your issue?

**Comment by veita** [comment]
With `Gitea Version: 1.8.0+rc3` there's no visible change.

**Comment by zeripath** [comment]
OK yeah it looks like #6258 wasn't backported to v1.8

**Comment by zeripath** [comment]
OK it's now backported to the 1.8 branch.

**Comment by zeripath** [comment]
Do the changes on https://try.gitea.io look ok for you?

**Comment by veita** [comment]
The problem still is there with 1.8.0 and 1.9.0+dev-193-g46373e765.

See https://try.gitea.io/veita/gitea-issue-5529/src/branch/master/filenames

**Comment by techknowlogick** [comment]
When hovering over I get the full filename ![Screen Shot 2019-05-04 at 3 41 53 PM](https://user-images.githubusercontent.com/164197/57184027-33c79600-6e83-11e9-9d60-d4e585ae9577.png)

**Comment by veita** [comment]
OK, now I see. But unfortunately we have many long file names with a common prefix in our repos. Given such a situation, I think it is a little bit cumbersome to perform a binary search hovering over the table to find the desired file. I would prefer a more suitable column width (as GitHub), or a configuration parameter to customize it.

**Comment by lunny** [comment]
@veita Github is still not so long?

**Comment by zeripath** [comment]
Hmm, it should be possible to make the length settable - and perhaps make the thing horizontally scroll automatically ?

The problem is that we're getting exponential increase in our settings and I suspect that making things scrollable by default will break things.

So three options:

1. Add yet another settable option as above.
2. Is there a better truncation scheme? Would it be better to do some starting characters ... some ending characters?
3. Add a UI switch that would just display the full names?

I think 2 and/or 3 may be the correct answers - I suspect that most of us when hit by a long filename will read the first 10-15 characters and then skip to the end and read backwards.

**Comment by veita** [comment]
A fourth solution would be to use a more reasonable default for the column with.

[Gitea](https://try.gitea.io/veita/gitea-issue-5529/src/branch/master/filenames) only shows [~35](https://try.gitea.io/veita/gitea-issue-5529/src/branch/master/filenames) characters while [GitHub](https://github.com/veita/gitea-test/tree/master/filenames) shows [~82](https://github.com/veita/gitea-test/tree/master/filenames) characters with similar font settings.

The large user base and long experience of GitHub suggests that their settings are near the optimum.

**Comment by zeripath** [comment]
Hmm... I think you're right and we have the balance the wrong way round here. How about:

![Screenshot from 2019-05-05 15-13-46](https://user-images.githubusercontent.com/1824502/57195266-68515580-6f48-11e9-91aa-6a4c2c92b14f.png)

That is eight wide for the filename, five wide for the commit summary with a title on the cell of the commit message to get the summary?

**Comment by veita** [comment]
This looks way better than before.

The common convention for the headline of commit messages is a maximum lenght of 50 characters. With your suggestion 50 characters seem to be displayable without an ellipsis, which is good with respect to usability.

**Comment by zeripath** [comment]
The trouble is it looks worse on tables with not-so-long filenames.

We really need some better styling here.

I think what is wanted is:
```
<filename><commit>                 <details>  
<filename><commit>                 <details>  
<filename><commit>                 <details>  
<filename><commit>                 <details>  
```
If at least one commit is long and all filenames are short:
```
<filename><commit>                <details>  
<filename><commit-------------->  <details>
<filename><commit>                <details>
```
  
if commits are all short and at least one filename is long:
```
<filename>              <commit>  <details>  
<filename--------------><commit>  <details>
<filename>              <commit>  <details>  
<filename>              <commit>  <details>  
```

and I guess we want a long filename to override the commit?

**Comment by veita** [comment]
You're right.

GitHub also tries to balance out file names and commit comments. 

https://github.com/veita/gitea-test/tree/master/filenames
https://github.com/veita/gitea-test/tree/master/filenames-short
https://github.com/veita/gitea-test/tree/master/filenames-50-chars-commit-message

**Comment by lafriks** [comment]
This could probably be achieved using flex layout or table columns

**Comment by lunny** [comment]
And another possible change is github is almost full width but gitea only about 60% width.
