### ISSUE TITLE
Diff split view paints the whole line for both the new and the old version in a single color

### ISSUE THREAD

**Issue by alvaroaleman** [go-gitea/gitea#553]
- Gitea version (or commit ref): 1.0.0
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes: https://try.gitea.io/test/gitea/commit/d4924d45d6d4e991240d207a834d8d6709781449?style=split 

## Description

The split view mode always paints the whole line for both the new and the old version in a single color. This is especially irritating when a line was changed, because then it is completely red which makes it look like that line was removed.

IMHO the view should:

* Display lines that were added white on the left side and green on the right side
* Display lines that were modified red on the left and green on the right side
* Display lines that were removed red on the left and white on the right side

**Comment by lunny** [comment]
resolved by #584
