### ISSUE TITLE
[PR] Diff Stats

### ISSUE THREAD

**Issue by Cellebyte** [go-gitea/gitea#5532]
- Gitea version (or commit ref): af6bce3
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes https://try.gitea.io/tester1234/gitea/pulls/2/files
  - [ ] No
  - [] Not relevant
- Log gist:

## Description
Click show Diff Stats in the provided pull request, scroll down and the files do not scroll down. The diffs in the background are scrolling.
...

## Screenshots

![screenshot from 2018-12-12 16-08-41](https://user-images.githubusercontent.com/16540824/49878615-47b52180-fe28-11e8-901d-28c0a799247e.png)

**Comment by Cellebyte** [comment]
It is not stale its a bug in the frontend view.

**Comment by 6543** [comment]
`style="overflow-y:auto;">` ?

**Comment by 6543** [comment]
I'll look at it

**Comment by 6543** [comment]
ok got it :)

-> https://github.com/go-gitea/gitea/pull/8581
