### ISSUE TITLE
Get a single commit

### ISSUE THREAD

**Issue by lflare** [go-gitea/gitea#5535]
- Gitea version (or commit ref): 0bd802e3e15f9da15a1e973052e6b9a78f11f92e
- Git version: N.A
- Operating system: N.A
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

As Drone 1.0.0 RC 2 rolls about, it brought about a really useful cron feature to automatically schedule builds. Unfortunately as fast as the excitement came about, it was put down, as Gitea has not started to support the [API endpoint @ https://developer.github.com/v3/repos/commits/#get-a-single-commit](https://developer.github.com/v3/repos/commits/#get-a-single-commit) necessary for the cron feature to work.

A similar issue from the other project has also been brought up @ gogs/gogs#5546

**Comment by techknowlogick** [comment]
Will be solved by #5843
