### ISSUE TITLE
Local requests redirected to HTTPS when using Let's Encrypt or redirecting HTTP to HTTPS

### ISSUE THREAD

**Issue by gregkare** [go-gitea/gitea#5540]
- Gitea version (or commit ref): master
- Operating system: macOS, Linux
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant

## Description

We ran into this after setting up Let's Encrypt, but I think it's an issue as well with a regular TLS setup with regular certificates. The auto-generated `LOCAL_ROOT_URL` is `https://localhost:${HTTP_PORT}`, so internal requests (for example when cloning a repo) are to `https://localhost:${HTTP_PORT}/api/internal/repo/user/repo`, which doesn't contain a valid cert for localhost. Setting it to `http://localhost:${PORT_TO_REDIRECT}` does not help, as all requests not going to the Let's Encrypt validation endpoint (`/.well-known/acme-challenge/*`) get redirected to HTTPS. So as far as I can see it's also the case when not using Let's Encrypt but `REDIRECT_OTHER_PORT` is set to `true`

We worked around it by setting `LOCAL_ROOT_URL = https://example.com/`, making the requests go through the public URL using TLS.

Local requests should probably not be redirected to HTTPS. If not, then the TLS and Let's Encrypt guides should mention that having to set `LOCAL_ROOT_URL` to the domain name is required.

What do you think?

**Comment by techknowlogick** [comment]
I think maybe setting `LOCAL_ROOT_URL` to `ROOT_URL` if LE is enabled (I think that is what you are suggesting in your 2nd paragraph) is the best route, as then it won't fail due to localhost not having a valid cert.

However, docs with this caveat are also accepted.

**Comment by techknowlogick** [comment]
This has been solved in another PR
