### ISSUE TITLE
Add SSH keys on login from LDAP

### ISSUE THREAD

**Issue by NomAnor** [go-gitea/gitea#5545]
- Gitea version (or commit ref): master
- Git version: 2.20.0
- Operating system: Arch Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
The SSH keys in the LDAP directory are only added to the user accounts when the synchronization task is run not when a user first logs in.

This means that a user can't push as soon as he is logged in and he needs to add the key himself making the key storage in LDAP not so useful.

Is it possible to add the keys when the user is created on first login?

**Comment by zeripath** [comment]
Hi @NomAnor I wonder if you could test #5557 and see if that fixes your issue?

**Comment by zeripath** [comment]
@NomAnor, #5557 has been merged into the master branch. Does that solve your issue? If so, could you close this.

**Comment by lafriks** [comment]
Closing as fixed
