### ISSUE TITLE
git pull "Failed to receive SOCKS5 connect request ack."

### ISSUE THREAD

**Issue by MidAutumnMoon** [go-gitea/gitea#5550]
- Gitea version (or commit ref): v1.6.1
- Git version: 2.19.1
- Operating system: Ubuntu 18.04 with 4.18.0-12-generic
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description

I used binary to install. Everything is pretty fine while installing and server configuring.

I run nginx as reverse proxy, and used SSL service provided by Let's Encrypt with certbot. Web service works well and basic git actions work well such as git fetch or clone are also ok.

But when I pull something, git echoed:

```
fatal: unable to access 'https://<server>/../<proj>.git/': Failed to receive SOCKS5 connect request ack.
```

occuring wherever I tried(except on the server itself :P).

Here is my app.ini(ignored some lines link mailer or image etc.)
```
...

[server]
SSH_DOMAIN       = <domain>
DOMAIN           = localhost
LOCAL_ROOT_URL   = %(PROTOCOL)s://%(HTTP_ADDR)s:%(HTTP_PORT)s/
HTTP_PORT        = <port>
ROOT_URL         = https://<server>/
DISABLE_SSH      = false
SSH_PORT         = 22
LFS_START_SERVER = true
LFS_CONTENT_PATH = /<path>/data/lfs
LFS_JWT_SECRET   = <token>
OFFLINE_MODE     = false

[database]
DB_TYPE  = sqlite3
HOST     = <host>
NAME     = <name>
USER     = <user>
PASSWD   = 
SSL_MODE = disable
PATH     = /<path>/data/g.db

...

```

And it's the nginx conf part:
```
server {
    server_name <domain>;

    location / {
        proxy_pass http://localhost:<gitea port>;
    }

    listen 443 ssl; 
    ssl_certificate <...>
    ssl_certificate_key <...>
    include <...>
    ssl_dhparam <...>

}

```

Want can I do? Is this my network's fault? Or is there any config I mistaked?

**Comment by MidAutumnMoon** [comment]
I have added my ssh key. But no effect.

**Comment by MidAutumnMoon** [comment]
I found something interesting.

Sometimes I will failed push, got `Failed to receive SOCKS5 connect request ack`.
But after a while I push again- it works!

How could this happen? It's my network problem?

**Comment by lunny** [comment]
I think that's your local proxy problem.
