### ISSUE TITLE
LICENSE texts are are not correctly formatted

### ISSUE THREAD

**Issue by tastytea** [go-gitea/gitea#5552]
- Gitea version (or commit ref): 1.6.1
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant

## Description

When I add a new repository and select a license, the LICENSE file is missing space and double-newlines, at least for [GPL-2.0-only](https://try.gitea.io/tastytea/license_test2/src/branch/master/LICENSE), [GPL-3.0-only](https://try.gitea.io/tastytea/license_test/src/branch/master/LICENSE), [GPL-3.0-or-later](https://try.gitea.io/tastytea/license_test3/src/branch/master/LICENSE) and [BSD-4-Clause](https://try.gitea.io/tastytea/license_test4/src/branch/master/LICENSE).

The GPL-3.0 licenses are also having a corrupted URL in [line 3](https://try.gitea.io/tastytea/license_test/src/branch/master/LICENSE#L3).

Correctly formatted GPL-3.0 license: https://www.gnu.org/licenses/gpl-3.0.txt

## Screenshots

![screenshot_2018-12-16t16 50 52](https://user-images.githubusercontent.com/3681516/50055717-6da13580-014a-11e9-8cd0-f768e4abf05b.png)

**Comment by zeripath** [comment]
Hmm... I'm not sure that the formatting is necessarily incorrect.  All of the other licenses in `options/license` are similarly formatted. I'll put a PR in to fix the urls though.

**Comment by tastytea** [comment]
It may not be technically incorrect, but it is hard to read for humans and I don't see any advantage.

**Comment by techknowlogick** [comment]
@zeripath this is the script that pulls the latest license files from the SPDX repo: https://github.com/go-gitea/gitea/blob/801843b0115e29ba2304fa6a5bea1ae169a58e02/scripts/generate-licenses.go#L20

**Comment by zeripath** [comment]
Heya @tastytea , so the issue with the url is coming from our upstream ( https://github.com/spdx/license-list-data ) - please could you open an issue there?

They've changed their formatting to match your preferred style - which I agree is nicer - so I've run our update script (`go run scripts/generate-licenses.go`) and added a PR for this #5558.

**Comment by tastytea** [comment]
I've reported the [issue](https://github.com/spdx/license-list-data/issues/42) upstream.

**Comment by techknowlogick** [comment]
Closing this issue as PR has been merged.
