### ISSUE TITLE
Crash in V75 Migration and old database

### ISSUE THREAD

**Issue by trebonian** [go-gitea/gitea#5560]
- Gitea version (or commit ref): fe55ab2a68
- Git version:
- Operating system: Linux
- Database (use `[x]`): 
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x ] Not relevant
- Log gist:

## Description
Latest version errors out with no such table "stop_watch" when migrating V75 on the following statement:

+	if _, err := x.Exec(builder.Delete(condDelete("user_id")).From("stop_watch")); err != nil {
--
 		return err
	}
 
In my version of SQLite - the table is called stopwatch (no underscore character). I have a very old database so this may be related to that. I replaced the tablename with "stopwatch", rebuilt gitea and it worked.

...

**Comment by jlelse** [comment]
I have the same error running the latest docker image
