### ISSUE TITLE
Can I get the difference between different versions through API?

### ISSUE THREAD

**Issue by mojie126** [go-gitea/gitea#5561]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

Can I get the difference between different versions through API?

**Comment by kolaente** [comment]
You mean the differences between two commits? AFAIK currently not, but you can get the differences between two branches when appending `compare/master...other-branch` to the url of your repo

**Comment by mojie126** [comment]
> You mean the differences between two commits? AFAIK currently not, but you can get the differences between two branches when appending `compare/master...other-branch` to the url of your repo

Hopefully, you can get the list of differences by API

**Comment by tboerger** [comment]
That should be implemented for the linked drone pull request.

**Comment by Coding-Kiwi** [comment]
Yes this would be awesome! An endpoint for pull request diffs is already there, is this feature much work?

**Comment by dineshsalunke** [comment]
BUMP, any idea on when can we expect this feature or if it even is in works ?
I don't mind taking a jab at this, we need this feature for the above drone related pull request too. ( Note: I am a newbie in go )

**Comment by wxiaoguang** [comment]
I think most work should have been done in  feat(api): implement branch/commit comparison API #30349  and  Make API "compare" accept commit IDs #32801
