### ISSUE TITLE
Possible XSS in issue dependancies

### ISSUE THREAD

**Issue by zarunet** [go-gitea/gitea#5565]
- Gitea version (or commit ref): release 1.6.1
- Git version: 2.11.0
- Operating system: Debian 9.6
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes, at https://try.gitea.io/Simia_/test-repository/issues/1
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

When adding an issue with an HTML tag in the title, said HTML doesn't seem to be escaped.

In this example, the `<select>` tag in the title is displayed as an actual `<select>`

![2018-12-19_14-43-35](https://user-images.githubusercontent.com/43345608/50224323-eea43b00-039d-11e9-959a-ba638e25c357.png)

**Comment by zeripath** [comment]
I can confirm this.

**Comment by zeripath** [comment]
@simia-zaru Can you please email security@gitea.io

**Comment by zeripath** [comment]
Similarly for milestone descriptions.

**Comment by zeripath** [comment]
Actually there's a flash on the application of a milestone title to an issue whereby it will execute an embedded script.

**Comment by techknowlogick** [comment]
@simia-zaru thanks for the report. You will be thanked in our release blog post.
