### ISSUE TITLE
Issues and Milestones due today are marked as overdue

### ISSUE THREAD

**Issue by znegva** [go-gitea/gitea#5566]
- Gitea version (or commit ref): 1.6.1
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
Issues and Milestones can get an `Due date`.
If the due date is set to the current day it gets supplemented by the text `Overdue`.
In listings `Overdue` entries get their Due-Date colored red.

In fact [if something is overdue, it should have been done before now](https://www.macmillandictionary.com/dictionary/british/overdue) - if something is due today I still have time to do it 😄 

My suggestion would be to call something overdue if it really was due to yesterday or before.  
And I would suggest to add an additional state like `Due today` (which could be colored maybe yellow in listings)

## Screenshots
![screenshot 2018-12-19 at 14 59 37](https://user-images.githubusercontent.com/7450884/50224674-c23cee80-039e-11e9-98fd-883b9bcc6719.png)

**Comment by kolaente** [comment]
This is because due dates are saved as unix timestamps. So when you save a due date for lets say the 21.12.2018, it is saved as 21.12.2018 00:00. So, if it's the 21.12.2018 15:00, it makes perfect sense to compare it that way. IMHO we should change it when saving.
