### ISSUE TITLE
Feature request to include the issues during repo migration/mirroring

### ISSUE THREAD

**Issue by pankajazad** [go-gitea/gitea#5578]
- Gitea version (or commit ref):1.6.1
- Git version:2.20
- Operating system: windows 10 x64
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

... The repo migration or mirroring process in gitea clones only the repository and not the issues associated with that. I think if gitea is used for migration or mirroring it can copy the relevant relational tables from .db file pertaining to that repo and make them available at the location where the repo is being migrated or mirrored. And why stop at that, the other information like wiki etc. can also be taken along.
I am aware that it might not be very simple but it'll definitely be worthwhile to at least consider it. Any other views are welcome.

**Comment by kolaente** [comment]
The mirror feature only mirrors git repos. There are a lot of platforms which don't have issues/prs/wikis associated with git repos.

I'd recomend you to use a tool like https://git.jonasfranz.software/JonasFranzDEV/gitea-github-migrator if you want to migrate repos with issues and prs. Maybe one could extend that to provide a morror function.

**Comment by pankajazad** [comment]
for keeping gitea compatible with other platforms which lack support for issues/prs/wikis associated with git repos this is fine but if we have gitea servers at both ends then its is good feature to have. Maybe the gitea-github-migrator tool can be added to gitea as a plugin or as third party library thereby making gitea a complete repo hosting solution.

**Comment by techknowlogick** [comment]
Closing as per @kolaente message.
