### ISSUE TITLE
Support versioning for documentation

### ISSUE THREAD

**Issue by adelowo** [go-gitea/gitea#5588]
- Gitea version (or commit ref):  not relevant
- Git version:  not relevant
- Operating system: not relevant
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ x] Not relevant
- Log gist:

## Description

I expect to be able to view docs for `v1.6`,`v1.5` and `master`'s. This has bitten me a few times, 
the most recent being the lets encrypt integration. I think by the time it was available on the docs,
`1.6` wasn't released yet but I went to tweak the config thinking how I missed that part of the docs earlier - I think I was running `1.5.3` in production then.

Another one that comes to mind is https://github.com/go-gitea/gitea/issues/5376#issuecomment-441181799

So ideally, we'd have something like https://docs.gitea.io/en-us/master and https://docs.gitea.io/en-us/${version}

> https://docs.gitea.io/en-us/ can start redirecting to https://docs.gitea.io/en-us/master

**Comment by bmackinney** [comment]
This could be fairly straightforward if the team is willing/interested in offloading docs hosting to www.netlify.com. I'm willing/able to do the work - I think it requires:
- [x] create `netlify.toml` and configure deployments
- [ ] create branches if necessary for subdomains. release/v1.7.docs.gitea.io may not work. 
- [ ] modify layouts to indicate current branch, link to other versions.

**Comment by techknowlogick** [comment]
Documentation is already on netlify

**Comment by bmackinney** [comment]
I see that now 

- [ ] update `docs/README.md`

**Comment by wxiaoguang** [comment]
FYI, there are some works, but no progress.

* https://github.com/go-gitea/gitea/pull/17879
* https://github.com/go-gitea/gitea/pull/17905

**Comment by lunny** [comment]
Fixed by https://gitea.com/gitea/gitea-docusaurus
New documentation site is https://docs.gitea.com and there is a blog PR https://gitea.com/gitea/blog/pulls/247
