### ISSUE TITLE
[Bug]Issue list of milestone didn't contain pr

### ISSUE THREAD

**Issue by 0000005** [go-gitea/gitea#5590]
- Gitea version (or commit ref):
- Git version:1.6.2
- Operating system: centos
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
![image](https://user-images.githubusercontent.com/9690089/50390101-a5713400-076d-11e9-84c0-1dd6575eed4d.png)
![image](https://user-images.githubusercontent.com/9690089/50390103-abffab80-076d-11e9-99f7-cc8fe026fb5e.png)
The milestone list page shows 75 closed issue and 2 open issue,But the milestone detail page shows 68 closed issue and 2 open issue.I guess the milestone detail page did not include the related pr.so this is a bug.

**Comment by lafriks** [comment]
I think @lunny fixed this in 1.7.0
