### ISSUE TITLE
The files from private repositories can be downloaded via direct link

### ISSUE THREAD

**Issue by pavelxdd** [go-gitea/gitea#5591]
- Gitea version (or commit ref): 4586ae3
- Git version: 2.17.1
- Operating system: Ubuntu bionic, Linux 4.4.0-139-generic
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant

## Description

The files from the private repository can be downloaded via direct link (tested with `wget` and `curl`).

For now I have patched this with this patch:

````patch
diff --git a/routers/routes/routes.go b/routers/routes/routes.go
index 5d9a6b31f..bcb7f3c2c 100644
--- a/routers/routes/routes.go
+++ b/routers/routes/routes.go
@@ -738,12 +738,12 @@ func RegisterRoutes(m *macaron.Macaron) {
 
 		m.Get("/compare/:before([a-z0-9]{40})\\.\\.\\.:after([a-z0-9]{40})", repo.SetEditorconfigIfExists,
 			repo.SetDiffViewStyle, repo.MustBeNotBare, reqRepoCodeReader, repo.CompareDiff)
-	}, ignSignIn, context.RepoAssignment(), context.UnitTypes())
+	}, reqSignIn, context.RepoAssignment(), context.UnitTypes())
 	m.Group("/:username/:reponame", func() {
 		m.Get("/stars", repo.Stars)
 		m.Get("/watchers", repo.Watchers)
 		m.Get("/search", reqRepoCodeReader, repo.Search)
-	}, ignSignIn, context.RepoAssignment(), context.RepoRef(), context.UnitTypes())
+	}, reqSignIn, context.RepoAssignment(), context.RepoRef(), context.UnitTypes())
 
 	m.Group("/:username", func() {
 		m.Group("/:reponame", func() {
````

But as far as I understand this patch breaks files downloading via direct link for public repositories.

**Comment by adelowo** [comment]
Interestingly enough, in incognito mode, I am able to also download an attached issue image 
for a private repository on GitHub.

**Comment by kolaente** [comment]
@pavelxdd Could you provide an example url scheme? I cannot reproduce this when trying to download either full zips or individual files (via `http://gitea.tld/user/repo/src/branch/master/filename`)

**Comment by pavelxdd** [comment]
@kolaente sure
`https://gitea.tld/organization/repo/raw/branch/master/filename`

**Comment by A-UNDERSCORE-D** [comment]
I am unable to verify this using that example at `https://git.ferricyanide.solutions/A_D/test-repo/raw/branch/master/test_fi`

**Comment by lunny** [comment]
@pavelxdd could not reproduce it on latest 76060613efa85b828ff06de3172d94d00e580726

**Comment by pavelxdd** [comment]
I'm not able to reproduce it on latest revision either.
