### ISSUE TITLE
Cannot access public repo

### ISSUE THREAD

**Issue by vufa** [go-gitea/gitea#5592]
- Gitea version (or commit ref): 1.6.2
- Git version:
- Operating system: Debian
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

I deploy gitea from source, from tag 1.5.x to the latest(1.6.2). If a user not sign in and try to access /explore/repos, will be redirect to /user/login. But if deploy gitea with a new database, and create a public repo in gitea, access /explore/repos without sign in can list all public repos.

I think it is upgrading from the old version to the new version, go-xorm will auto-adjust tables in database, which cause this problem.

How to solve it? thank you.

**Comment by vufa** [comment]
@lunny Thanks for your reply, I exported the database to sql file on server and imported it to local database, then the local gitea has the same problem. I tried to start and stop local gitea but the problem still exists.

**Comment by vufa** [comment]
@lunny Any news?

**Comment by lunny** [comment]
Please check your custom/app.ini file, maybe you enabled `REQUIRE_SIGNIN_VIEW`

**Comment by vufa** [comment]
Thank you for your answer. Not enable `REQUIRE_SIGNIN_VIEW`in `app.ini`, and I have reinstalled gitea, deleted and recreated the database, create repos and users, really a huge job, the problem has been solved:), I will close this issue.
