### ISSUE TITLE
GC_ARGS maybe not loaded?

### ISSUE THREAD

**Issue by YukiUnHappy** [go-gitea/gitea#5593]
- Gitea version (or commit ref): 1.6.1
- Git version: 2.11.0
- Operating system: Debian 9.5 x64
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description

I have modified the app.ini as follows, but no one can show in Git Configuration page.

```ini
[git]
GC_ARGS  = "--prune=now"
```

```ini
[git]
GC_ARGS  = --prune=now
```

I just google it and find out a same question solved by [fix '[git] GC_ARGS' is not loaded](https://github.com/gogs/gogs/commit/0376e59520a8538291e3b571142aa6ce0a8682de) for Gogs, it is exist the same question for Gitea?

**Comment by dfredell** [comment]
I agree I'm not seeing the git GC args in the web interface.

**Comment by bogi788** [comment]
It seems the config parser turns GC_ARGS into "GcArgs", while in the code the attribute is referred to as "GCArgs". The options are picked up if you name the setting (in app.ini) G_C_ARGS to also turn the 'C' uppercase.
