### ISSUE TITLE
First indentation is shorter by one character

### ISSUE THREAD

**Issue by freemanix** [go-gitea/gitea#5596]
Gitea version: 1.6.0, 1.5.0

## Description

The first level indentation in file preview is in fact by one character shorten than all other levels indentations. For example, if the tab size is 8, first indentation will be 7 characters, not 8. This breaks many source codes rendering.

In the built-in web editor, the indentation works as expected. 

## Screenshots

Gitea .go code on GitHub:

![indent-github](https://user-images.githubusercontent.com/46109266/50423953-bea4de00-085c-11e9-89a3-44fed6fae056.PNG)

Gitea .go code on Gitea itself:

![indent-gitea](https://user-images.githubusercontent.com/46109266/50423954-bea4de00-085c-11e9-8b82-6c52588bd163.PNG)

**Comment by freemanix** [comment]
Any progress on this?

**Comment by lunny** [comment]
@freemanix Nobody is working on this.

**Comment by freemanix** [comment]
I spent some time going for this issue and it is CSS based. Specifically, this line for `.lines-code` style:

https://github.com/go-gitea/gitea/blob/608781f8806ad810e13ac6dc479bf5eac7a40b96/public/less/_repository.less#L370-L372

emits space, but breaks tab character rendering in browser. Removing this CSS rule will result in perfect rendering of tab widths, but of course, without initial padding (caused by` content: ' '`). Maybe we could remove the `:before` rule and add some left padding to the `<table> <td>`?
