### ISSUE TITLE
Czech translation

### ISSUE THREAD

**Issue by j123b567** [go-gitea/gitea#5605]
- Gitea version (or commit ref): 1.6.2
- Git version: N/A
- Operating system: N/A
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
Gitea is now translated 100% to Czech but there is probably missing proofreader for this language so only 20% is approved from the past with many errors (all issues are reported in crowdin).

Can you please approve these translations or make me proofreader for this language?

**Comment by lafriks** [comment]
Can you please contact me in crowdin?

**Comment by j123b567** [comment]
I have send you a message via crowdin.

**Comment by techknowlogick** [comment]
Closing as it is being dealt with out of band
