### ISSUE TITLE
Gantt Diagrams for Issues

### ISSUE THREAD

**Issue by geniepro** [go-gitea/gitea#5606]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
Is it possible to view the Gantt Diagram for Issue List?

PS. GanttProject is preferred as client.
...

**Comment by lafriks** [comment]
It is not and most probably is out of scope for Gitea. You can use API to get issue data and generate file to import into your preferred tool
