### ISSUE TITLE
Can I pay for this?

### ISSUE THREAD

**Issue by coolaj86** [go-gitea/gitea#561]
I like to have the security of knowing that the software I use has some sort of plan to allow me to purchase a copy so that I know I can depend on the continued development of the software and have some access to support for bugs in existing features or pay bounties for desired features.

Is there any marketplace or business planned for this?

**Comment by lunny** [comment]
There is no marketplace and business plan currently. We are trying all our best to fix bugs and security problems ASAP. For new features, we first will implement Gitea via Gitea. If some feature is slight or someone have time, it may be implemented. However you can file an issue to describe your requirements. Since we made a community according https://github.com/go-gitea/gitea/blob/master/CONTRIBUTING.md, I think we could continue the development. Maybe we will set a donate account after we know how to spend the money on Gitea.

**Comment by strk** [comment]
@coolaj86 you can surely pay anyone to get support and custom development. For development, what you pay to be developed has to pass the approval of at least 2 maintainers to be accepted. For support it's just between you and your developer of choice.

**Comment by coolaj86** [comment]
@lunny Thanks. I'd like to incentivize the development of 'Login with GitHub' and importing Issues from GitHub. I'll create an issue for those things.

@strk exactly why I'd rather work with the existing team in some way

**Comment by tboerger** [comment]
Login with github is covered by the issue for an OAuth2 consumer. I think importing from github should be a standalone tool

**Comment by thewhitetulip** [comment]
@lunny how about we start a patreon or something on bountysource?

**Comment by tboerger** [comment]
And who should receive that? We can setup bountysource to give the opportunity that people can pay individuals for getting features implemented. The gitea team itself doesn't pay anything except @lunny who got to pay the domain once a year.

**Comment by lunny** [comment]
@tboerger I think we may need a more power host so that we can publish docker every PR! 💯

**Comment by tboerger** [comment]
> @tboerger I think we may need a more power host so that we can publish docker every PR! 💯

You don't want to do that for every PR. I have already talked about that with @bkcsoft, IMHO we will do that based on tags assigned to the PR. Maybe this logic will be part of the teabot that launches containers that got a specific tag assigned and it destroys the instance when the tag gets removed.

And as this will reduce the required resources a lot we can also launch that on our sponsored droplet. So more or less unrelated to this issue :P

**Comment by lunny** [comment]
OKay with that.

**Comment by coolaj86** [comment]
You guys are on to something huge here. If you can get federated accounts working (and good migrations) you could replace github. This is fast, lightweight, runs on an RPi. It's perfect.

I will be surprised if within a year or so you don't have a non-profit, b-corp, or foundation of some sort (like what npm did) with support plans. If that's something you want to do that is.

There's all this talk about decentralization, but no one actually does it - they build distributed protocols that have a central authority and store all of their decentralized code on centralized authorities and host all of their communication on centralized authorities.

You've got an opportunity to actually be the change everyone is talking about right at the center of where all the code happens. :)

**Comment by thewhitetulip** [comment]
@tboerger Well, I do not know about patreon, but bountysource would be nice, that would give the money directly to those who fixes issues, and since gitea/gogs is amazing, I feel there is a need for bountysource.

**Comment by lunny** [comment]
Currently bountysource is a good choice.

**Comment by xor-gate** [comment]
Bountysource is the way to go, people who fix get the credits. Most people do this in their "spare time".

**Comment by tboerger** [comment]
I have enabled bountysource now. So if you want to pay for something create a bounty and the community will benefit of it.

**Comment by coolaj86** [comment]
I don't see a link to bountysource on the home page or the github page. Where is it?

**Comment by tboerger** [comment]
> I don't see a link to bountysource on the home page or the github page. Where is it?

It's automatically linked within the issues, but bountysource got a small open issue that it doesn't get rendered properly:

<img width="702" alt="bildschirmfoto 2017-01-24 um 22 41 46" src="https://cloud.githubusercontent.com/assets/156964/22268099/79f70b00-e286-11e6-9f83-e67d5546f3cf.png">

**Comment by benyanke** [comment]
`Maybe we will set a donate account after we know how to spend the money on Gitea.`

You'll be able to find things to spend on it, I'm sure! You should really set up something ASAP, especially given the github news.

Even if it just sits in an account for a year, I'd highly encourage you to do so

**Comment by tboerger** [comment]
We are already registered on opencollective :)

**Comment by coolaj86** [comment]
You've got to put a call to action in the README so people have an idea of what to do and what will happen as a result of what they contribute:

Like this https://github.com/go-gitea/gitea/pull/4117

Or better yet, add some details:

Goals:

* $750/month - we'll self host
* $1,500/month - we'll integrate one new OAuth2 provider each month
* $5,000/month - we'll have a team member dedicated full-time to the project
* $15,000/month - we'll close out 10 small, 5 medium, and 1 large issue each month

Rewards:

* $5/month - get listed as a sponsor
* $100/month - up to 3 sponsors can be listed at the top of the readme as core sponsors

Just pick some goals and run with them.

**Comment by davidak** [comment]
I suggest [Liberapay](https://liberapay.com/). It is open source, run by a non-profit organization and funded through it's own service. Unlike Patreon, Bountysource (salt) etc it has no fees (except from payment provider). You can donate $0.01 every week if you want! You can also set goals...

**Comment by jonasfranz** [comment]
@coolaj86 If you are searching a migration tool to migrate issues to gitea, checkout "gitea-github-migrator" I wrote: https://git.jonasfranz.software/JonasFranzDEV/gitea-github-migrator
