### ISSUE TITLE
fatal: the remote end hung up unexpectedly fatal: the remote end hung up unexpectedly

### ISSUE THREAD

**Issue by yb3616** [go-gitea/gitea#5614]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

I guess it's gitea's bug, cause i found it done well in gogs.

## Screenshots

![default](https://user-images.githubusercontent.com/8839021/50553245-eae9b000-0cdd-11e9-90db-1ba212241662.PNG)

**Comment by lafriks** [comment]
Did you migrate from gogs?

**Comment by yb3616** [comment]
@lafriks No, Gitea and gogs are independent on my vps

**Comment by lunny** [comment]
Could you give more logs here?

**Comment by Evsio0n** [comment]
Seems I have a same issue here at:
>Enumerating objects: 11, done.
Counting objects: 100% (11/11), done.
Delta compression using up to 12 threads
Compressing objects: 100% (9/9), done.
Writing objects: 100% (9/9), 926 bytes | 926.00 KiB/s, done.
Total 9 (delta 6), reused 0 (delta 0)
error: RPC failed; HTTP 504 curl 22 The requested URL returned error: 504
fatal: the remote end hung up unexpectedly
fatal: the remote end hung up unexpectedly
Everything up-to-date

**Comment by zeripath** [comment]
@Evsio0n: We need some more information:

* What version of Gitea?
* What platform?
* What do the server logs say?

If you are running 1.11.1 please upgrade to the head of release/v1.11 as there are several critical bugs in that release. We will get 1.11.2 out very soon.

**Comment by francipvb** [comment]
Hello,

I am registered in the server version 1.12.0+dev-82-g3723b0647. I don't have administrative access to the server so I cannot provide logs.

Cheers,

**Comment by zeripath** [comment]
@francipvb that's quite an old version of 1.12 I recommend your team updates.

Without logs or further information there is little we can do to help. Anything could be going wrong.

**Comment by guillep2k** [comment]
@francipvb You mean `try.gitea.io`?

**Comment by francipvb** [comment]
Hello,


Sorry, my problem was a very big request. I got an HTTP 413 error and
that was causing it. This may be the same problem on the original issue
report...


Cheers,

-- 
Cuando tus fuerzas terminan, las de mi Dios comienzan.

**Comment by francipvb** [comment]
> Hello, Sorry, my problem was a very big request. I got an HTTP 413 error and that was causing it. This may be the same problem on the original issue report... Cheers,

My Fault... The reporter was pushing via SSH...

**Comment by guillep2k** [comment]
Glad you've found the solution, @francipvb 

Closing for the time being. If anyone happen to find a similar issue, please try our Discord channel for help or open a new issue.

**Comment by bool64-llc** [comment]
anyone who has this issue, try to increase ~nginx/like `client_max_body_size`
