### ISSUE TITLE
Repository avatars

### ISSUE THREAD

**Issue by rapardington1** [go-gitea/gitea#5625]
## Description

Back in June 2018, Gogs added repository avatars to it. (see https://github.com/gogs/gogs/pull/5221 for more details.)

Can we get this added to Gitea?

## Screenshots
Shots from Gogs:

![repolist](https://user-images.githubusercontent.com/46328553/50611384-13380100-0ece-11e9-8e8d-e2a8a6b1ed24.png)

![homepage](https://user-images.githubusercontent.com/46328553/50611409-277bfe00-0ece-11e9-94d4-ed5e0490604c.png)

**Comment by sergey-dryabzhinsky** [comment]
Well, gogs not included all of my changes.
Repo icons available only at:
- repos lists
- repo page

Right pannel missing repo and org icons.

I can try to adjust my previous work for gitea.

**Comment by lunny** [comment]
@sergey-dryabzhinsky Thanks. Please send your PRs and we will review that.

**Comment by lunny** [comment]
And @rapardington1 @sergey-dryabzhinsky, it seems this is duplicated with #694. Let's discuss further there and I will close this one.
