### ISSUE TITLE
Show number of commits ahead/behind in branch overview

### ISSUE THREAD

**Issue by vijfhoek** [go-gitea/gitea#5628]
Like #5326, but in the branch overview, like this:

![image](https://user-images.githubusercontent.com/345785/50683452-674bfe00-1012-11e9-9858-bb2a1d2d9322.png)

This would be massively useful for deleting old branches, to check if they happen to have commits that aren't merged to develop yet (so you can't accidentally delete work).

**Comment by vijfhoek** [comment]
Do we want to close this issue? Seems to me that feature requests like these should not be marked stale and be closed after a few months.

**Comment by morph027** [comment]
Stumbled into the same use case yesterday (after finally switching to wonderful gitea). It would be nice. Discussion here or in #5326 ?

**Comment by saitho** [comment]
I'll try to implement this feature.
