### ISSUE TITLE
Gitea's models/repo.go Repository.IsBare means that a repository is Empty

### ISSUE THREAD

**Issue by zeripath** [go-gitea/gitea#5629]
- Gitea version (or commit ref): master

## Description

Gitea's models/repo.go Repository.IsBare means that a repository is empty rather than that the repository is actually a bare repository in git terms. This is confusing and should probably be renamed IsEmpty.

**Comment by adelowo** [comment]
I believe this can be checked with `git config --get core.bare`

**Comment by zeripath** [comment]
It's not that it's difficult to check whether a repository is git bare but that gitea bare means something completely different from what git bare means. It's just confusing and should be called IsEmpty. 

I'm not sure there are any reasons to check if a repository is bare - imho we should only ever have bare repos on the server, any use of a non bare repo should be refactored away.

I also wonder if it's really necessary to have it set on every call and whether the places that check it should just be rewritten to properly cope with empty repositories.

**Comment by lunny** [comment]
@zeripath yes, it's something confusing. I think Gitea's IsBare means `empty or bare git`.
