### ISSUE TITLE
Assigning a PR causes the server to hang

### ISSUE THREAD

**Issue by apricote** [go-gitea/gitea#5639]
- Gitea version (or commit ref): `v1.7.0-rc1`, 5a1ea37
- Git version: `2.17.1`
- Operating system: Ubuntu 16.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL) https://try.gitea.io/apricote/rebase-conflict/pulls/1
  - [ ] No
  - [ ] Not relevant
- Log gist: https://gist.github.com/apricote/4cfb8b63feac29bdf85ab0be224f59bd

### Summary

When assigning a user to a PR, Gitea will never complete the `POST` request, from now on the Gitea Instance is "broken" and will not answer most requests. Restarting the server  solves the problem until a user is assigned to a PR again.

The Log shows incoming requests, but they never succeed/complete:

```
[Macaron] 2019-01-04 17:26:12: Started POST /organization1/repository2/issues/assignee for 172.18.0.1
[Macaron] 2019-01-04 17:26:12: Started GET /organization1/repository2/pulls/42 for 172.18.0.1
```

Some requests still complete, for example, our instance is configured to require a login, accessing the PR page from an incognito browser window redirects me to the login page and renders it.

### Steps to reproduce

Initially, the error happened in our company instance. I was able to reproduce the error on try.gitea.io.

* Access a PR in the Web Interface (example https://try.gitea.io/apricote/rebase-conflict/pulls/1).
* Change Assignee of PR and add a user.
* Click outside of the Assignee window to send the request.
* The request will never complete, the site is stuck in loading

**Comment by lafriks** [comment]
I would not recommend running company instance on sqlite but @zeripath mentioned issue could be the cause

**Comment by pixelspark** [comment]
Experiencing this as well but on 1.9.4 (also SQLite). Can I help in any way (e.g. where to look for logs?)

**Comment by lunny** [comment]
@pixelspark Please open another issue and give some details.
