### ISSUE TITLE
UI: 2FA code entry field is a "counter"

### ISSUE THREAD

**Issue by 0x5c** [go-gitea/gitea#5645]
- Gitea version (or commit ref): `30560b0`
- Git version: 2.15.3
- Operating system: Docker image (on Debian 9.6 stretch)
- Database:
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes
  - [ ] No
  - [ ] Not relevant
- Log gist: most probably not needed

## Description

The field for the 2FA code is a "counter" field. Repro: login on a 2FA enabled account.

## Screenshots
![gitea_2fa_box](https://user-images.githubusercontent.com/5877043/50726470-67fc9700-10db-11e9-802b-7628859918b4.png)

**Comment by jonasfranz** [comment]
This is the expected behaviour since this is the input type `number`. The "counter" is feature provided by your browser.
