### ISSUE TITLE
error during dump command: Failed to dump database: no such table: user

### ISSUE THREAD

**Issue by jryan128** [go-gitea/gitea#5648]
- Gitea version (or commit ref): 1.6.2 built with: bindata, sqlite
- Git version: git version 2.11.0
- Operating system: Debian
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant

## Description
git@gitea:~$` gitea dump -c /etc/gitea/app.ini
2019/01/05 20:38:55 Creating tmp work dir: /tmp/gitea-dump-249881383
2019/01/05 20:38:55 Dumping local repositories.../home/git/gitea-repositories
2019/01/05 20:38:56 Dumping database...
2019/01/05 20:38:56 Failed to dump database: no such table: user

**Comment by mikescandy** [comment]
Confirm the issue also with version 1.7.0 (also using SQLite)

**Comment by jryan128** [comment]
Replacing relative path with absolute path in db.PATH does fix the issue for me.

**Comment by msreedata** [comment]
As @jryan128 mentioned, absolute path works fine. 
Also if you do a pushd/cd to the gitea workdir and run the backup command (without changing the absolute path), the backup goes through fine
