### ISSUE TITLE
Error when creating / editing files with a leading dot

### ISSUE THREAD

**Issue by AkiraNorthstar** [go-gitea/gitea#5652]
- Gitea version (or commit ref): 1.6.3 30560b0f
- Git version: 2.20.1 (on host system)
- Operating system: linux x86_64 / fedora 29
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (see screenshots)
  - [ ] No
  - [x] Not relevant : All variants have the same error (self hosted, try.gitea.io)
- Log gist: [gitea.log](https://gist.githubusercontent.com/AkiraNorthstar/9a07ba99cb4f72d619c0a7b8f79b2d4c/raw/559c520333855f0c714238546461539606623f78/gitea-dot.log) and [xorm.log](https://github.com/go-gitea/gitea/files/2730702/xorm.log)

## Description
Creating / editing a file with a leading point that it is either not created (screenshot 1 + 2), or if it is created, it does not include the leading point. This phenomenon also occurs when you have an existing file (such as .drone.yml) and edit it via the gitea web editor. This file would renamed to drone.yml (without leading dot)

Tested versions:
1.6.2 (2631f7f6) = works
1.6.3 (30560b0f) = does not work!
1.7.x (all commits) = do not work!

Each versions are tested with Docker [(docs)](https://docs.gitea.io/en-us/install-with-docker/) and as self-compiled rpm packages under fedora 29.
It seems to me that, starting with version 1.6.2, something has changed that causes this error.

## Screenshots
The creation of a file with a leading point:
![screenshot_2019-01-06 repotest-dot](https://user-images.githubusercontent.com/16691957/50739136-35869300-11dc-11e9-8e21-85e49bc40f51.png)

Error message after commit:
![screenshot_2019-01-06 repotest-dot 1](https://user-images.githubusercontent.com/16691957/50739137-39b2b080-11dc-11e9-8848-78290df42bb9.png)

File after creating (without leading dot):
![screenshot_2019-01-06 repotest-dot 2](https://user-images.githubusercontent.com/16691957/50739138-3c150a80-11dc-11e9-8a34-c1acb951e0b4.png)

EDIT: add gitea.log and xorm.log

**Comment by zeripath** [comment]
Heya, so this is due to the fix for the security issue that led to 1.6.2. An alternative fix is in my pull request #5621

**Comment by AkiraNorthstar** [comment]
With commit #5702 it is again possible to edit and create files with a leading dot via the web interface without being renamed.

A thank you to all who participated!
Best regards,

AkiraNorthstar
