### ISSUE TITLE
1.7.0 lfs regression

### ISSUE THREAD

**Issue by TankTheFrank** [go-gitea/gitea#5657]
- Gitea version (or commit ref): 1.7.0-rc1/1.7.0-rc2
- Git version: 2.19.2
- Operating system: linux/armv7
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

I'm using gitea with drone for ci. Up until 1.7.0 everything works fine but with 1.7.0 rc1/rc2 repositories with lfs cannot be cloned by drone. **The repo is public** but it fails with an authorization error.

Switching the binary back to 1.6.3 fixes everything again (keeping the same database, repos, config, etc that 1.7.0 used).

```
Downloading resources/assets/fonts/raleway/raleway-v12-latin-100.svg (59 KB)
Error downloading object: resources/assets/fonts/raleway/raleway-v12-latin-100.svg (7199b8d): Smudge error: Error downloading resources/assets/fonts/raleway/raleway-v12-latin-100.svg (7199b8d7358b032d9dcccf78ec238eda71ef303b12eb2e27a5a219c474bfac9b): 
    batch response: Git credentials for https://<repo_url - redacted>/info/lfs not found.
```

Edit:
This request returns 200 before 1.7.0, 401 in 1.7.0:
```
[D] LFS request - Method: POST, URL: /<repo>.git/info/lfs/objects/batch, Status 401
```

**Comment by lunny** [comment]
Have reproduced this: when you clone via `http/https`, it's ok. When you clone via `SSH`, it will failed because it `http` requires authentication, but no password provided and also git will not ask to input password.

**Comment by lafriks** [comment]
@lunny it should not ask password for public repo

**Comment by lunny** [comment]
A public repo and REQUIRE_SIGNIN_VIEW is not set true, the password could not be ask.

**Comment by TankTheFrank** [comment]
@lunny 

The cloning is done via http/https in this case, not ssh. Drone always provides an auth token, even for public repos (see my commit linked for details). Maybe this token was completely missing in your tests when http/s worked?

The "main" repo itself is cloned just fine up until that batch lfs request.
