### ISSUE TITLE
Feature request: allow anonymous push

### ISSUE THREAD

**Issue by tobiasBora** [go-gitea/gitea#5662]
## Description

I need sometimes to work with several people, and I do not want to create an account for them on my private server, and I also don't want to lose time/make things too complicated by asking them their public key. For that reason, would it be possible to add an option to create a repository that is both publically clonable *and pushable*? It would also be nice to be able to hide this kind of repository so that only people with the good url can push to it.

A bonus point is given if it is possible for a given repository to have both a "read only" url and a "read and write" url !

Thank you for the great job!

**Comment by tobiasBora** [comment]
Well this is not what I was talking about, as I'm talking about a "no key" (and no authentication) write access. Having the url should be enough to push. I would like that feature first because I want to keep the process as simple as possible as the users are not familliar with git, and asking them to create a key, send me the key, wait for me to accept it... it long and complicated, and it scales poorly with the number of users.

**Comment by apricote** [comment]
If you really do not care about security, you can create one keypair with read/write access and send the private key along with the link to the users.

This at least removes the round trip time for you to accept their key.

**Comment by tobiasBora** [comment]
Thanks @apricote  for your answer. For the keypair, indeed it works, but it's sadly a bit too complicated for people that already are afraid to use git.

Your second method is really interesting and I confirm it works, but there are three drawbacks:
- first, if at some point someone wants to be anoying, he could connect with this guest user, and change the password. That would forbid everyone to send anything after that. Moreover, he could even change the name of the guest user, and create basically a new account
- second, if I use a single account for all my "public writable repo" someone could also use this guest account to get the list of the other "publicly shared" repo, and access to the url of some repositories he shouldn't have access to.
- lastly, someone could also use this guest account to create new repositories, which is not supposed to be possible with a "public link". (but this is fixable by setting to 0 the number of repo I guess)

Do you know if I could "lock" a user, so that he can only git clone/git push, but not connect to the web interface ? I tried to check the box "disable connection", but I can't push anymore.
