### ISSUE TITLE
Links to commits in comments don't update after repo transfer

### ISSUE THREAD

**Issue by jaroel** [go-gitea/gitea#5664]
Hi, 

When I transfer a repo to another org, then existing links to commits in comments are not updated to reflect that change.

I've seen this in Gitea Version: 1.4.3 .

**Comment by jaroel** [comment]
I'm guessing I'm confused, because a full link to a commit looks just like a link with just the commit hash.
In a comment `https://git.uwkm.nl/jan/niet_voor_jos/commit/ccc6f31b176915a86c5ea617da71e612c3a95c37` and `ccc6f31b176915a86c5ea617da71e612c3a95c37` look the same (`ccc6f31b17`), but aren't.

So this actual issue might be that full links to commits aren't converted to just the hash?

**Comment by jaroel** [comment]
Sorry, nope. Any hash will link to the current repo, even if it isn't a commit in the repo.

**Comment by lunny** [comment]
Closing as outdated.
