### ISSUE TITLE
Issue due-dates are shown in English regardless of current language

### ISSUE THREAD

**Issue by saltymouse** [go-gitea/gitea#5670]
- Gitea version (or commit ref): d3dc07f
- Git version: 2.17.1
- Operating system: Ubuntu Server 18.04
- Database:
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes https://try.gitea.io/testtestsetset/test-date-format-language/issues
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
Due-dates shown on the Issues page are shown in English regardless of the currently used UI language.
Switch to any non-English language (from the language switcher at the bottom of the page) and the dates are still shown in their English format (e.g. Jan 09, 2019)

Somewhat related: Milestone due-dates don't use the same date format as issues but are instead display in a more universal format (e.g. 2019-01-23), so it's more readable in any language, but perhaps they should be unified to use the same date display template?
...

## Screenshots
*Issues* (Japanese UI) shows English language.
![gitea-issue_date_language_test-ja](https://user-images.githubusercontent.com/7547649/50876711-d9a54f80-1411-11e9-8fa4-8d60a5c585bb.png)

*Milestones* (Japanese UI) shows generic/unformatted date.
![gitea-milestone_date_language_test-ja](https://user-images.githubusercontent.com/7547649/50876754-fb063b80-1411-11e9-95ad-c2a44e7dbb09.png)

**Comment by Ryuno-Ki** [comment]
The relevant template for issues is

https://github.com/go-gitea/gitea/blob/73382d2132f8f242245d83f66c92761e0b477b91/templates/shared/issuelist.tmpl#L101-L108

and for milestones

https://github.com/go-gitea/gitea/blob/73382d2132f8f242245d83f66c92761e0b477b91/templates/repo/issue/milestones.tmpl#L80

FormatShort is defined in

https://github.com/go-gitea/gitea/blob/73382d2132f8f242245d83f66c92761e0b477b91/modules/timeutil/timestamp.go#L89-L92

and Deadline in

https://github.com/go-gitea/gitea/blob/73382d2132f8f242245d83f66c92761e0b477b91/models/issues/milestone.go#L91

I can see `timeutil` having localised version, but where would I pull the `Location` information from?

**Comment by wxiaoguang** [comment]
Two choices:

1. make user can set their timezone in their preference (setting) page.
2. render date/time by frontend (JS)

Each of them has Pros/Cons.

A similar problem:  #17760
* https://github.com/go-gitea/gitea/pull/17760

**Comment by Ryuno-Ki** [comment]
Are, the joy of internationalisation. Okay, your PR appears to be almost ready for merge. I'll put this on the backburner for now.

**Comment by yardenshoham** [comment]
I fixed this
