### ISSUE TITLE
Can't unassign removed collaborators

### ISSUE THREAD

**Issue by vijfhoek** [go-gitea/gitea#5673]
- Gitea version (or commit ref): 30560b0

## Description

I just removed a collaborator (chris) from a project, but he's still an assignee on a few pull requests, and he can't be removed because he doesn't appear in the dropdown, and clicking `Clear assignees` does nothing.

### The assignees:
![image](https://user-images.githubusercontent.com/345785/50888564-427ece80-13f6-11e9-9de7-cf8c4d0aa6da.png)

### The dropdown:
![image](https://user-images.githubusercontent.com/345785/50888590-4f032700-13f6-11e9-93a1-e09a8c8f8473.png)

**Comment by davidsvantesson** [comment]
I think assignees shall be automatically be removed when they are not assignable any longer (changed access)

**Comment by 6543** [comment]
I'll take care of this now
