### ISSUE TITLE
Can you provide the installation package for openwrt system?

### ISSUE THREAD

**Issue by mirroro** [go-gitea/gitea#5674]
Gitea is a very good software, there are raspberry pie, linux, windows version, I want to install on openwrt, do not know how to compile into ipk, can you provide download installation package of openwrt version? Thanks very much！

**Comment by philippbeckmann** [comment]
Hi, you better request this at the [issue tracker of the OpenWRT package project](https://github.com/openwrt/packages)

**Comment by mirroro** [comment]
Well, as you can see, many of your versions are worse than openwrt, and the development system is expected to be busier.

**Comment by TankTheFrank** [comment]
They provide a working binary already for mips routers, just use linux-mipsle one and it follow the instructions for any other system.

**Comment by mirroro** [comment]
I don't know much about the openwrt system either. The installation software uses the opkg install filename. ipk.

**Comment by philippbeckmann** [comment]
Well, you don't need to use the opkg system. You can ssh into the system and install gitea manually, like on any linux system. But you will need to make an init script.
