### ISSUE TITLE
Add support for a .gitea folder

### ISSUE THREAD

**Issue by dfrrt5r6uyfrt** [go-gitea/gitea#568]
Like [.github](https://github.com/blog/2111-issue-and-pull-request-templates). I actually recommend to use another name, like `.templates` or something, in order to not be dependent on a specific name.

**Comment by metalmatze** [comment]
We could also use .github as a fallback if there's no other folder.

**Comment by tboerger** [comment]
Maybe .scm :)

**Comment by lunny** [comment]
`.gitea` and fallback to `.github` should be OKay!
