### ISSUE TITLE
Gitea fails to start: Failed to initialize ORM engine: sync database struct error: Error 1265: Data truncated for column 'theme' at row 1

### ISSUE THREAD

**Issue by wyattoday** [go-gitea/gitea#5681]
- Gitea version (or commit ref): https://github.com/go-gitea/gitea/commit/dd13327382f76b7a5d2b5e98e75a6aaa9a67c313
- Git version: Latest
- Operating system: Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

2019/01/09 16:43:38 [...itea/routers/init.go:61 GlobalInit()] [E] Failed to initialize ORM engine: sync database struct error: Error 1265: Data truncated for column 'theme' at row 1
2019/01/09 16:43:39 [...itea/routers/init.go:61 GlobalInit()] [E] Failed to initialize ORM engine: sync database struct error: Error 1265: Data truncated for column 'theme' at row 1
2019/01/09 16:43:39 [...itea/routers/init.go:61 GlobalInit()] [E] Failed to initialize ORM engine: sync database struct error: Error 1265: Data truncated for column 'theme' at row 1
2019/01/09 16:43:40 [...itea/routers/init.go:61 GlobalInit()] [E] Failed to initialize ORM engine: sync database struct error: Error 1265: Data truncated for column 'theme' at row 1
2019/01/09 16:43:40 [...itea/routers/init.go:61 GlobalInit()] [E] Failed to initialize ORM engine: sync database struct error: Error 1265: Data truncated for column 'theme' at row 1

## Description

Using the latest gitea version fails to start. Likely due to changes not being made to the database.

**Comment by techknowlogick** [comment]
Ping @adelowo

**Comment by adelowo** [comment]
Taking a look at this right now.

@wyattoday what version of MySQL are you running? I cannot replicate this on `5.7.20`? And is this a fresh database or a previously used one?

**Comment by kimpenhaus** [comment]
Having the same issue with the latest docker container - updated by watchtower (so also a previously used one). Running against `10.3.7-MariaDB`. It's a previously used db

**Comment by adelowo** [comment]
Sorry folks, I'm getting to my computer in a few minutes and will pull down an `8.X` MySQL image to test and submit a patch.

**Comment by kimpenhaus** [comment]
I've found a workaround to get my container up and running. The `theme` entries of all users inside the db had `NULL` value. Updating that value to `gitea` (as default) fixed it for me. I guess the migration alters the column to `NOT NULL` without respecting existing data?

**Comment by adelowo** [comment]
Yeah, I believe that is the fix, but I want to test on a 8.X Mysql DB before doing anything. Downloading the docker image right now

**Comment by adelowo** [comment]
I didn't want to set `gitea` as the default so as not to interfere with the value of `DEFAULT_THEME` if set

https://github.com/go-gitea/gitea/blob/31aa00fa4b6a5e77b5bd4d29628860ff88eb4029/models/user.go#L170-L175

**Comment by adelowo** [comment]
Note to self --- Always Test on 5.X and 8.X

**Comment by securitaas** [comment]
Same for me. Setting the default theme to "gitea" for all users works.

**Comment by adelowo** [comment]
@securitaas What commit are you running? This was fixed in 
https://github.com/go-gitea/gitea/pull/5682

**Comment by tokidoki11** [comment]
Hi, I have the some problem when trying to update from 1.7.1 to 1.8.3
Database is mysql 8.0.12

The latest entry on log is
```[...itea/routers/init.go:84 GlobalInit()] [E] ORM engine initialization failed: sync database struct error: Error 1265: Data truncated for column 'theme' at row 1```
