### ISSUE TITLE
possible `/api/v1/user/repos` misbehavior

### ISSUE THREAD

**Issue by Iced-Sun** [go-gitea/gitea#5687]
- Gitea version (or commit ref): 1.6.3
- Git version: 2.17.1
- Operating system: ubuntu bionic
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gitea.io: 
- Log gist:

## Description

Drone CI uses ```/api/v1/user/repos``` to fetch the user repo info. Upon the first time when a repo is created as a fork, say 'user/repoA' -> 'org/repoA',  the API does report the newly created 'user/repoA'. Then:
1. delete 'user/repoA' ( ```/api/v1/user/repos``` do also reflects it);
2. fork 'org/repoA' to 'user/repoA' again.

Now ```/api/v1/user/repos``` never reports 'user/repoA'  as a repo belongs to 'user'.

**Comment by lunny** [comment]
Can you reproduce that on https://try.gitea.io ?
