### ISSUE TITLE
Android native application

### ISSUE THREAD

**Issue by mmarif4u** [go-gitea/gitea#5689]
Hello everyone,

I thought to share this idea with you all, what you think of free, open source native mobile client for Android?.

Well, personally i think it's a good idea. So i started some work on the client itself and it's coming along nicely so far even though i have less time to work on it.

What is done:
- Login
- Organizations list
- Repository list
- Create new repository
- About
- Logout

There are few things in my list which i need to work on(at least for initial release):
- Issues
- Milestones
- Create new issue

Source code will be available under GPLv3 and anyone can build by themselves. I will release it in F-droid store. I have no plans to release it in Play store(no google please).
I will also need community help to improve and add features in the future. I will share repository link when repo is ready.

And by the way right now i have no timeline for the initial release. I want to release it when there are at least few working features available like issues, create issue etc.

Here are some screens for your eyes. :)
![create-repo](https://user-images.githubusercontent.com/1280585/50982142-79103280-1537-11e9-9d96-ac261229f1bb.png)
![login](https://user-images.githubusercontent.com/1280585/50982145-79103280-1537-11e9-8dc1-62cf069a9f15.png)
![nav-menu](https://user-images.githubusercontent.com/1280585/50982146-79a8c900-1537-11e9-9d03-2d6ba38a8a56.png)
![org-list](https://user-images.githubusercontent.com/1280585/50982147-79a8c900-1537-11e9-8116-8d329044d4a9.png)
![repo-list](https://user-images.githubusercontent.com/1280585/50982148-79a8c900-1537-11e9-9af7-02b883d5bf1b.png)

What do you guys think?

**Comment by tonivj5** [comment]
I can't wait to try it 😍  🎉

**Comment by tankerkiller125** [comment]
My only question is why no google? I understand privacy and all that but in the end most people are not going to get F-Droid just to get this app, Even though I firmly take a stance of privacy I am one of those people who would not download apps from F-Droid, the Google store although a privacy concern in some cases, in the end, is much safer than 3rd party software stores.

**Comment by mmarif4u** [comment]
@tankerkiller125 I believe you already answered your own question in this regard. But we will see in the future if there is any demand to push it to GPlay. 

But for now, APK and F-droid will be more than sufficient. :)

**Comment by mmarif4u** [comment]
@dxas90 yes I know about PWA. It's just that I am more into backend technologies and native apps. :)

**Comment by mmarif4u** [comment]
Evening All,

Current status:
- Added create new organization
- Redesign the app layouts (who don't love eye candy :) )
- New icons and design updates
- Refactor parts of the code (wip)

Updated login screen  
![login](https://user-images.githubusercontent.com/1280585/51322250-d6f4cb00-1a9f-11e9-8d71-dcd632dea2b5.png)

Repository is ready at GitLab, still empty though. Once i push the code after the refactor to the repository, anyone can pull and build for testing. :)
https://gitlab.com/mmarif4u/gitnex/

I need community help with App Logo. If you have ideas, please do share them in the issue below.  
https://gitlab.com/mmarif4u/gitnex/issues/1

For updates please follow me on Mastodon if you are on it.  
https://mastodon.social/@mmarif

**Comment by mmarif4u** [comment]
Hello All,

I have pushed the source code and released an early pre alpha which you guys can test and help report issues. 

https://gitlab.com/mmarif4u/gitnex/tags/pre-alpha1

Check the readme too for more details.  
https://gitlab.com/mmarif4u/gitnex/blob/develop/README.md

See you on the other side. :)

**Comment by misterzym** [comment]
android 7.0
redmi note 4
not work - "can not installed", but developer option install apk - ON
:(

**Comment by mmarif4u** [comment]
@misterzym try this. Setting => Additional Setting => Privacy => Unknown source

Hope this help.

**Comment by mmarif4u** [comment]
Hello,

I will close this issue but before that, I would like to tell about the progress of the app.
Everything is coming up nicely. Quite a lot of things are implemented already. Check out the readme for features, screenshots etc. The app is currently tagged as last pre-alpha 9.
https://gitlab.com/mmarif4u/gitnex/blob/master/README.md

Download and release notes
https://gitlab.com/mmarif4u/gitnex/releases

If you have any questions/suggestions/fixes, please post at the issue tracker.
