### ISSUE TITLE
Feature Request: Define superset of labels and selection of relevant ones for each repo

### ISSUE THREAD

**Issue by pankajazad** [go-gitea/gitea#5696]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
Currently I have to define labels for each repository separately even if they have some commonality. It would be great to have a feature to define a superset of the issue labels and then make selection from them for each repository. One more possibility could be, to have export and import facility for issue labels to facilitate their inclusion across different repositories. 
...

**Comment by apricote** [comment]
It is already possible to create a file containing a set of initial labels for new repos.
This is not the solution that you and I would prefer, but it might help you in the meantime:

https://docs.gitea.io/en-us/customizing-gitea/#customizing-gitignores-labels-licenses-locales-and-readmes

**Comment by apricote** [comment]
There is a default file in the repository, you can find it here: https://github.com/go-gitea/gitea/blob/master/options/label/Default

**Comment by pankajazad** [comment]
Thanks a lot.
