### ISSUE TITLE
[UI] File-view box overflows text

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#5698]
## Description

The Readme box overflows text.

## Screenshots

![image](https://user-images.githubusercontent.com/8215278/51025991-c919e400-158d-11e9-8f57-b3a7f19eaa82.png)

**Comment by lunny** [comment]
What's your OS, browser and version?

**Comment by ghost** [comment]
Opera browser (latest as of posting) , Debian GNU/Linux stretch, and the version that was running on try.gitea.io five days ago
