### ISSUE TITLE
Allow colon in closing issue from commit message

### ISSUE THREAD

**Issue by znegva** [go-gitea/gitea#5699]
- Gitea version (or commit ref): 1.6.1
- Git version: --
- Operating system: --
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

Gitea-Issues can be closed, reopened or referenced in commit messages.
The same keywords as in github are used, see [here](https://github.com/go-gitea/gitea/blob/5a1ea37f577e5f085e122593ccbd7cd9e23a8f65/models/action.go#L55).
Githubs description of the feature is described [here](https://help.github.com/articles/closing-issues-using-keywords/).

Inside github it is possible to use a colon between keyword and issue-number, eg
```
Fixed the critical bug
closes: #123
``` 

This is not possible with gitea, only keywords __directly__ followed by the issue number are recognised:
```
Fixed the critical bug
closes #123
``` 

It would be great if an optional colon `:` could be supported.  
If I read the source code correctly this should be feasible by slightly extending the [regex used to detect the keywords](https://github.com/go-gitea/gitea/blob/5a1ea37f577e5f085e122593ccbd7cd9e23a8f65/models/action.go#L67).

Depending on your understanding, communication with the issue tracker is additional information that is not necessarily related to the actual commit.
Especially if you use the commit messages in addition in other ways (e.g. to create documentation or changelogs) issue-related stuff is often unimportant.  
The ability to structure issue references more clearly makes it easier to ignore these references where they are not needed.

## Additional Infos

- [Linux Kernel Team has Commit Conventions that use the described form to close bugs/issues](https://git.wiki.kernel.org/index.php/CommitMessageConventions)
- [trailers in git commit messages](https://git-scm.com/docs/git-interpret-trailers/2.8.0)

**Comment by guillep2k** [comment]
Fixed by #7207?
