### ISSUE TITLE
the goal of this fork?

### ISSUE THREAD

**Issue by wookiecooking** [go-gitea/gitea#57]
I understand the leader of the gogs team is MIA and nothing published in the past month, but with this starting to get traction now, I would like to know if this will be merge back in if development resumes in gogs, or will you be competing?

**Comment by tboerger** [comment]
If @Unknwon comes back and give write/admin access to more people i believe that the codestream gets back.

**Comment by tboerger** [comment]
This is just my opinion but i hope that @lunny or @fuxiaohai got the same opinion :)

**Comment by lunny** [comment]
Me too. @tboerger @fuxiaohei

**Comment by tboerger** [comment]
As this is not a real issue i will close this. If you've got further questions feel free to reopen it.

**Comment by cryptix** [comment]
I just saw that gogits/gogs [0.6.3](https://github.com/gogits/gogs/releases) was released.

Does this fork still have a purpose and/or will the changes from here be back ported to gogs?
