### ISSUE TITLE
Support to Last login

### ISSUE THREAD

**Issue by joubertredrat** [go-gitea/gitea#57]
Hi guys,

This issue https://github.com/go-gitea/gitea/issues/8 propose option to have more control to admin, but don't have plans for this concept.

As alternative, I think that is possible to add one field on user only to set last time login for first Gitea release. What you think guys?

![gitea_last-login](https://cloud.githubusercontent.com/assets/1520407/19983203/372b3354-a1f0-11e6-98a8-445d63b464cf.png)

**Comment by lunny** [comment]
If there is no guys to do that currently, this could be moved to 1.1.0

**Comment by tboerger** [comment]
I have moved it to `1.x.x` because it doesn;t have a high priority yet. If somebody wants to implement that feel free to do it.

**Comment by joubertredrat** [comment]
@okay @tboerger I will try this

**Comment by lunny** [comment]
@joubertredrat, great, you can move it to 1.0.0 after you send a PR.

**Comment by tboerger** [comment]
Just fixed the milestone, it's already done within 1.0.0
