### ISSUE TITLE
Branch sorting (branches and PR page)

### ISSUE THREAD

**Issue by RatkoR** [go-gitea/gitea#5709]
- Gitea version (or commit ref): 176a604
- Git version: 2.17.1
- Operating system: ubuntu
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ X] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

Can branches be sorted by last commit date or maybe by date created? They are now sorted alphabetically and this doesn't help me much when I'd like to find my most recent branch.

I have to go and type it's name, it would be much easier to pick it if it was up front in list.

This goes for "Branches" page or when creating a new pull request.

## Screenshots

![branches](https://user-images.githubusercontent.com/6648783/51079495-3cc00c00-16c8-11e9-8de8-4a1ce7e28710.png)

Here, `test4` branch would come first in list if they were sorted by last commit date.

**Comment by swuecho** [comment]
Anyone give some guide for this issues. I will try to implement.
