### ISSUE TITLE
Standardizing styles

### ISSUE THREAD

**Issue by Fastidious** [go-gitea/gitea#572]
I submitted this as [a ticket on Gogs](https://github.com/gogits/gogs/issues/3842), same applies to Gitea. It seems the styles used on the wiki differ from those on the rest of Gitea.

*Want to back this issue?*
* [Post a bounty on it!](https://www.bountysource.com/issues/40585447-standardizing-styles?utm_campaign=plugin&utm_content=tracker%2F47456670&utm_medium=issues&utm_source=github)* We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F47456670&utm_medium=issues&utm_source=github)

**Comment by Fastidious** [comment]
Adding the referred ticket text here, for better reference, and less clicks:

The style used throughout Gogs isn't the same as the one used on the wiki, the wiki font is smaller, for example. 

**The repo looks like:**

![screen shot 2016-11-02 at 7 11 03 am](https://cloud.githubusercontent.com/assets/8352292/19926587/c5772d64-a0cb-11e6-9dc6-87d3241e83da.png)

**The wiki look like:**

![screen shot 2016-11-02 at 7 11 26 am](https://cloud.githubusercontent.com/assets/8352292/19926597/d25a5592-a0cb-11e6-94ee-603acf14a390.png)

Could the same style be used throughout? Wiki font family and size should match the repository one (first screenshot). Also, editors should be standardized too:

**This one (awesome!)**

![screen shot 2016-11-02 at 7 14 26 am](https://cloud.githubusercontent.com/assets/8352292/19926643/17e472aa-a0cc-11e6-8e53-0284ed73e4c7.png)

**Versus this one (not so great)**

![screen shot 2016-11-02 at 7 14 44 am](https://cloud.githubusercontent.com/assets/8352292/19926654/22cdbb0e-a0cc-11e6-913d-b1b7adf12c2a.png)

Notice that editor icons/functions are not consistent.

**Comment by Fastidious** [comment]
This is still not addressed, even though is set to milestone 1.2.0 (we are on 1.3.X now).

**Comment by lunny** [comment]
@Fastidious This have been moved to `1.x.x` on 19 Apr 2017

**Comment by Fastidious** [comment]
The stale bot needs to put a sock in it. 😊

**Comment by 6543** [comment]
style improved and changed a lot
