### ISSUE TITLE
Chrome U2F Dongle Not Detected

### ISSUE THREAD

**Issue by tamalsaha** [go-gitea/gitea#5720]
- Gitea Version: 1.6.0+rc1-246-gbf7a11254 
- Operating system: Ubuntu 18.04
- Chrome: 71.0.3578.98

## Description
I am using Chrome. I can use U2F with Google services from this same Chrome installation. But Gitea will not detect the U2F dongle.

![u2f-chrome](https://user-images.githubusercontent.com/94814/51089478-bab10100-1722-11e9-93fa-271d7fa42c4b.png)

Similar issue for FireFox https://github.com/go-gitea/gitea/issues/5143

**Comment by jonasfranz** [comment]
Which U2F device do you use?

**Comment by tamalsaha** [comment]
I am using https://www.amazon.com/dp/B018Y1XXT6/

**Comment by jonasfranz** [comment]
I've tried to reproduce this at Chromium 71.0.3578.98 and it works fine for me. I'm using Feitian ePASS FIDO NFC. Did you test other browsers?

**Comment by tamalsaha** [comment]
I have tried on Firefox. After I enabled u2f in about:config, I see the following:

![firefox-u2f](https://user-images.githubusercontent.com/94814/51208548-d521e080-18c2-11e9-97f6-ba4c969e1a92.png)

**Comment by techknowlogick** [comment]
Are you able to try to add the key to github?

**Comment by tamalsaha** [comment]
Yes. I am currently using it with Chrome + Github.

**Comment by tamalsaha** [comment]
Oh! I was doing local testing. Thanks for the clarification.
