### ISSUE TITLE
Got notified for gitea new releases

### ISSUE THREAD

**Issue by laoshaw** [go-gitea/gitea#5723]
How can I get notified when there is a new gitea release available? Is it possible to show a notice on my own gitea site(e.g. update self-check and prompt the user), or I can subscribe to some list to get notified?

**Comment by mmarif4u** [comment]
@laoshaw the easiest would be to subscribe to this repo releases. Click on Watch in this repo and choose Releases only. New feature added by GitHub.

**Comment by mrsdizzie** [comment]
Closing as there are multiple ways to be notified of a new Gitea release
