### ISSUE TITLE
web edit: dotfiles getting renamed

### ISSUE THREAD

**Issue by cybre-finn** [go-gitea/gitea#5727]
- Gitea version (or commit ref): v1.6.3
- Git version: ?
- Operating system: Debian
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
When editing or creating a file starting with a dot (e.g. .drone.yml) via the "new file" web feature, the dot gets stripped off.

**Comment by zeripath** [comment]
#5702 will fix this...

**Comment by lunny** [comment]
@zeripath maybe we need a separate PR to fix this issue.
