### ISSUE TITLE
Code comments not interpreted correctly

### ISSUE THREAD

**Issue by Fastidious** [go-gitea/gitea#573]
Again, this is [a Gogs issue](https://github.com/gogits/gogs/issues/3766) that remains a Gitea issue. This applies to wiki **and** issues entries as well.

**Comment by bkcsoft** [comment]
I can't see the plaintext content so it's very hard to debug (as I mentioned in that issue)

**Comment by Fastidious** [comment]
@lunny, indeed. Or, as I replied on the original issue, just try it.

**Comment by lunny** [comment]
resolved by #1660
