### ISSUE TITLE
about git push -f

### ISSUE THREAD

**Issue by mojie126** [go-gitea/gitea#5731]
Wishing to increase the authority to control compulsory push restrictions

**Comment by zeripath** [comment]
It's not quite clear what you're asking. Gitea has protected branches so only certain users can push to that branch. Are you talking about adding a git hook for push - as in an arbitrary script that will check a commit and ensure that it passes some test?

OK, well obviously we can't produce a UI for that - it would mean allowing users to arbitrarily upload scripts that would be run on push. If you are the administrator and owner of the gitea server you should be able to edit the repository on the filesystem to add such a git hook - however remember that will be run during pushes so could lock the system.

Another option is to use the Gitea webhook system - the push will be accepted and then a webhook will be called which could then checkout the pushed commits and do the tests - it could then comment back on a PR or automatically push on to the master.

**Comment by lunny** [comment]
@zeripath I think he means we should add an option on protected branch to disallow users who have push permission to force push. @mojie126 Is that your issue?

**Comment by mojie126** [comment]
是的，限制强制推送，可以控制谁能强制推送...

**Comment by lafriks** [comment]
But when setting protected branch it will already be protected from forced push even if set that user are allowed to do push to that branch

**Comment by lunny** [comment]
@lafriks I think @mojie126 means he want to give somebody push permission but cannot force push. Currently gitea didn't split them as two options.

**Comment by lafriks** [comment]
But it already works this way. If I specify branch protection and whitelist user who can push to that branch that user will be able to push new commits but won't be able to force push

**Comment by 0x5c** [comment]
Could the OP be asking for a repository setting? Ie: blanket denying of force-pushes

**Comment by davidsvantesson** [comment]
I think this would be solved with the combination of setting _writers_ as push whitelist (similar as suggested in #8288) and wildcard branch protection (#2529). Then you can disable force pushing of the complete repository but still allow normal pushes.

**Comment by lunny** [comment]
How to allow someone could push but cannot force push then?

**Comment by guillep2k** [comment]
> 
> 
> How to allow someone could push but cannot force push then?

Can [this](https://github.com/olshanov/git-hooks/blob/master/pre-receive.deny-force-push-to-branches) be helpful for inspiration?

**Comment by davidsvantesson** [comment]
There is already a database element for this; `CanPush` in `ProtectedBranch`. Currently it is always false (not used in any way)

**Comment by davidsvantesson** [comment]
What seem to be wanted here (google translated from Chinese):
> Yes, limit forced push, you can control who can force push...

I don't see the point of enabling force pushing for everyone to a protected branch (that would be like not protecting the branch). So it does only make sense in combination of a whitelist. And I suppose it should be different whitelists for who can push normal and who can force push? What is the use case here?

**Comment by mrsdizzie** [comment]
closing per lack of feedback
