### ISSUE TITLE
Adding PR Reviews through API

### ISSUE THREAD

**Issue by mojie126** [go-gitea/gitea#5733]
Hope to add PR comments through API

**Comment by zeripath** [comment]
OK if logging in with basic authentication

```bash
curl -X POST "$APP_URL/api/v1/repos/$OWNER/$REPO_NAME/issues/$PULL_NUMBER/comments" -u "$USER" -H "Content-Type: application/json" --data '{ "body": "A new comment" }'
```
See the API information for other ways to log in.

--- 
I've just realised this is only for comments - I think review is not yet implemented in the API.

**Comment by mojie126** [comment]
这个不是添加到issues里了么...？
我的意思是能不能直接在PR里添加评论...

**Comment by lunny** [comment]
@mojie126 please speak English :(

**Comment by morph027** [comment]
Coming here from https://discourse.gitea.io/t/approve-reject-pull-requests-via-api/1115/3

Was looking for the same as we're trying to use Drone CI as "reviewer".

**Comment by morph027** [comment]
Also see #5060

**Comment by psychomario** [comment]
I'd like to work on this if it's not already being worked on?

My thoughts are an extra endpoint at `/repos/{owner}/{repo}/pulls/{index}/review`:

- GET returns array of approvals/rejections with the review comments if applicable
- DELETE allows the current user (or sudo'd admin) to remove their approval
- PATCH allows the current user (or sudo'd admin) to add their approval/rejection+comments

If this is agreed I can begin to implement this and I'll create a PR when done.

**Comment by lunny** [comment]
@psychomario I think no others will work on this. Maybe you could also add a comment but without approval/rejection

**Comment by alexanderadam** [comment]
Interesting issue! This would be required for integrating automated PR tools like [Pronto](https://github.com/prontolabs/pronto#pronto) (see also [this issue](https://github.com/prontolabs/pronto/issues/275)) or [Danger](https://github.com/danger/danger).

**Comment by 6543** [comment]
@mojie126 can you generalise the issue title to something like "API Endpoints for CodeReview"

**Comment by 6543** [comment]
I'll take a look at this later

**Comment by Tchoupinax** [comment]
What's up with this feature ? :)

**Comment by 6543** [comment]
dont have time to implement it jet :(

**Comment by tbe** [comment]
I'll get my feed wet on this feature, and will try to implement it over the weekend

**Comment by 6543** [comment]
@tbe a hint: https://github.com/go-gitea/gitea/blob/master/CONTRIBUTING.md#api-v1

describes the places you have to look at etc...

**Comment by 6543** [comment]
and the [github api docs](https://developer.github.com/v3/pulls/reviews)
may help you - thanks

**Comment by 6543** [comment]
I'll finaly take it :)

**Comment by MarkusAmshove** [comment]
@6543 thats great!

If you need any help or guidance on what different use-cases could be, feel free to ask :-)

**Comment by 6543** [comment]
@MarkusAmshove you can look at https://github.com/go-gitea/gitea/pull/11224#issuecomment-619637195 to see the progress

**Comment by 6543** [comment]
everybody who want to test it ... #11224 is considered as ready, only tests have to be added and in some cases there could be a code optimisation ... but the functionalety is ready :)

**Comment by 6543** [comment]
@MarkusAmshove :point_up: you perhaps want to have a look at it?

**Comment by MarkusAmshove** [comment]
> @MarkusAmshove :point_up: you perhaps want to have a look at it?

I’ll give it a try locally 🥳

**Comment by MarkusAmshove** [comment]
I’ve given it a try and this works really well! It covers all the use cases I have in mind 🤗
