### ISSUE TITLE
Random 500 error Invalid connection

### ISSUE THREAD

**Issue by lucableve** [go-gitea/gitea#5736]
- Gitea version (or commit ref): 1.7
- Git version: 1.8.3.1
- Operating system: Centos 7
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL (MariaDB 10.2)
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description
Hi,
after gitea installation I have random 500 errors. The logs return this:
2019/01/15 01:59:48 [...itea/routers/home.go:138 RenderRepoSearch()] [E] SearchRepositoryByName: Count: invalid connection
2019/01/15 01:59:49 [...itea/routers/home.go:138 RenderRepoSearch()] [E] SearchRepositoryByName: Count: invalid connection
2019/01/15 02:00:25 [...itea/routers/home.go:138 RenderRepoSearch()] [E] SearchRepositoryByName: Count: invalid connection
2019/01/15 02:09:37 [.../gogits/cron/cron.go:92 Run()] [E] MirrorUpdate: invalid connection

I have this system: Nginx reverse proxy to gitea :3000 on Db mysql (engine : mariadb 12)

**Comment by zeripath** [comment]
The http proxy isn't the connection that your errors are referring to. The problem appears to be with the communication between Gitea and the db. Does the xorm.log reveal anything?

**Comment by lucableve** [comment]
xorm.log not have errors. 
I forgot to tell you I have installed vestacp panel but 
I have configured manually reverse proxy and db.


I started server gitea and this is log before first error invalid connection:

> 2019/01/15 13:16:57 [I] Log Mode: File(Info)
> 2019/01/15 13:16:57 [I] XORM Log Mode: File(Info)
> 2019/01/15 13:16:57 [I] Cache Service Enabled
> 2019/01/15 13:16:57 [I] Session Service Enabled
> 2019/01/15 13:16:57 [I] Git Version: 1.8.3.1
> 2019/01/15 13:16:57 [I] SQLite3 Supported
> 2019/01/15 13:16:57 [I] Run Mode: Production
> 2019/01/15 13:16:57 [I] Listen: http://0.0.0.0:3000
> 2019/01/15 13:17:57 [...s/context/context.go:235 func1()] [E] GetUserById: invalid connection

this is my db config app.ini

> [database]
> DB_TYPE  = mysql
> HOST     = ip:3306 //Same problem with localhost and 127.0.0.1
> NAME     = name
> USER     = usr
> PASSWD   = psswd
> SSL_MODE = disable
> PATH     = data/gitea.db

**Comment by lucableve** [comment]
I started server gitea and this is log before first error invalid connection:

> 2019/01/15 13:16:57 [I] Log Mode: File(Info)
> 2019/01/15 13:16:57 [I] XORM Log Mode: File(Info)
> 2019/01/15 13:16:57 [I] Cache Service Enabled
> 2019/01/15 13:16:57 [I] Session Service Enabled
> 2019/01/15 13:16:57 [I] Git Version: 1.8.3.1
> 2019/01/15 13:16:57 [I] SQLite3 Supported
> 2019/01/15 13:16:57 [I] Run Mode: Production
> 2019/01/15 13:16:57 [I] Listen: http://0.0.0.0:3000
> 2019/01/15 13:17:57 [...s/context/context.go:235 func1()] [E] GetUserById: invalid connection

this is my db config app.ini
[database]
DB_TYPE  = mysql
HOST     = ip:3306 //Same problem with localhost and 127.0.0.1
NAME     = name
USER     = usr
PASSWD   = psswd
SSL_MODE = disable
PATH     = data/gitea.db

**Comment by zeripath** [comment]
Ok your Gitea version doesn't make sense. We haven't released 1.8.3.1 that appears to be your git version which is quite old. I think that's the default version of git on centos 7 so it should be upgraded. If git has been upgraded Gitea doesn't appear to be using it. This was mentioned in another issue if you look for it.

The MariaDB version you're reported also doesn't quite make sense. There's also no version 12 of Maria dB.

**Comment by lucableve** [comment]
I'm sorry , I have confused version, have fixed first comment.
Try update git version

**Comment by typeless** [comment]
By 'random' errors, do you mean some queries work fine? Did it fail with some types of queries and work for others?

**Comment by lunny** [comment]
That's an error from mysql driver. Maybe we should upgrade the driver library.

**Comment by zeripath** [comment]
May be there are dead connections in the pool?

**Comment by typeless** [comment]
@lucableve I guess @lunny was right. You may try to upgrade the driver library and see if that works.
I am not sure where the driver library in question is though.

Edit: probably [this](https://github.com/go-gitea/gitea/tree/master/vendor/github.com/go-sql-driver/mysql)

Edit2: also https://github.com/go-sql-driver/mysql/issues/836

**Comment by lucableve** [comment]
Ok, I try this solution, update you

**Comment by lucableve** [comment]
I downloaded binary master to test fix @lunny @zeripath  but error occurs again.
Do I have to try the source version?

**Comment by luxiaok** [comment]
The same error and situation kept a long time.

**Comment by samek** [comment]
With 1.7.1 is much better, but we still do get them.

**Comment by bobemoe** [comment]
I've been researching this over at #6804. I've tried Gitea 1.9-dev which should include the fix above, but still same issue. 

I think @zeripath is right, dead connections in the pool.  Watch mysql processlist, error happens straight after connection timeout (60s in my mysql.cnf)

But why did the update not work?

**Comment by zeripath** [comment]
Because I suspect the connections are timing out due to deadlocks
