### ISSUE TITLE
Show 404 ERROR when show a commit view with too more files changed

### ISSUE THREAD

**Issue by FalconWu2017** [go-gitea/gitea#5749]
- Gitea version (or commit ref):1.6.4
- Git version:2.10
- Operating system:Windows 2012 data center
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:

2019/01/17 14:47:25 [D] Detected encoding: utf-8 (fast)
> There are the same 100 lines above.

2019/01/17 14:47:25 [...uters/repo/commit.go:215 Diff()] [E] GetDiffCommit: Wait: exit status 128
2019/01/17 14:47:25 [D] Template: status/404
## Description

It will be 404 when you show commit  that are more then 100 files changed in the commit.
The `MAX_GIT_DIFF_FILES` set max number of files in diff view.If I change this setting to large enough，it will be OK.
But in any case,404? Not good.

**Comment by delvh** [comment]
I think the behavior was vastly improved in the meantime.
Please check if your issue still exists, and reopen this issue if yes.
