### ISSUE TITLE
Allow issues to be deleted

### ISSUE THREAD

**Issue by Larivact** [go-gitea/gitea#5775]
- Gitea version (or commit ref): 1.7.0

## Description

I think repository owners should be able to delete issues. For example to clean up accidentally created issues. GitHub supports this since November 7, 2018: https://help.github.com/articles/deleting-an-issue/.

**Comment by adelowo** [comment]
Sounds nice... 

Looks like I have a handful of PRs to make today 🙏🙏

**Comment by davydov-vyacheslav** [comment]
looks like copy of #923 ;)

**Comment by lunny** [comment]
@techknowlogick but I think site administrators should have abilities to delete issues on admin panel to maintain the site.

**Comment by techknowlogick** [comment]
@lunny I agree. This issue was closed because it is a duplicate. I kept original open.

**Comment by adelowo** [comment]
@lunny GitHub has it's own on the issues page ( The sidebar). Should I follow that model or use the admin panel as you mentioned.

> I hope to work on this during the weekend

**Comment by lunny** [comment]
@adelowo I think admin panel issues management is necessary and github's model could be a configuration that site admin could disable it.
