### ISSUE TITLE
Disallow empty titles

### ISSUE THREAD

**Issue by Larivact** [go-gitea/gitea#5781]
Reproducible at https://try.gitea.io (currently dbb4aee).

## Description

* [ ] Issue titles can consist of just spaces. Such issues cannot be selected in the issue list.
* [ ] Wiki page titles can consist of just spaces. Such pages cannot be selected in the wiki tab.
* [ ] Pull request titles can consist of just spaces. Such pull requests cannot be selected in the pull request tab.

**Comment by adelowo** [comment]
Whoops

Will send a PR ASAP
