### ISSUE TITLE
Minor UI tweaks

### ISSUE THREAD

**Issue by Larivact** [go-gitea/gitea#5782]
- Gitea version (or commit ref): 1.7.0

## Behavior

* [ ] `templates/repo/create.tmpl` – Once you select a license you can no longer deselect it.
* [ ] External issue trackers: The issues tab should have an [external-link-alt](https://fontawesome.com/icons/external-link-alt?style=solid) icon and link directly to the external tracker so that you can see the URL by hovering over it.
* [ ] When you select an issue/pull request the toggle button transitions to open & close buttons, which is not only problematic because it still looks like a toggle button but also doesn't make sense because you are never able to open or close an issue/pull request, it's either open or closed, you only ever have one choice (to toggle the current state). I suggest the transition to be removed and instead display an open or close button next to the toggle button.
<br>![select_issue](https://user-images.githubusercontent.com/8731884/51436722-cce6ee00-1c92-11e9-99da-4b8ab73f7943.png)
* [ ] The above check boxes should not be displayed for repositories where you are not allowed to open or close issues/pull requests.
* [ ] 404 pages of files, issues, pull requests, releases and wiki pages should include the repository header if the repository exists.
* [ ] Reset password should directly tell you when a code is invalid: https://try.gitea.io/user/reset_password?code=x
* [ ] `public/js/index.js` – When editing the labels of an existing issue (see screenshot), the labels are currently saved with every select / deselect, which just leads to unnecessary spam. The labels should only be saved after closing the popup, which is also the way GitHub does it.<br>![label_popup](https://user-images.githubusercontent.com/8731884/51436275-68279580-1c8a-11e9-92d7-7cb9f478612f.png)

## Visuals

* [ ] `templates/repo/header.tmpl` – Visually disable fork button on own repositories (you cannot clone them) by adding `disabled` class .<br>
![disable_fork](https://user-images.githubusercontent.com/8731884/51436354-b25d4680-1c8b-11e9-8f0f-fb01f5b2b6bf.png)
* [ ] `templates/repo/home.tmpl` – Give *New Pull Request* button a text label instead of a cryptic icon. <br>![pull-button](https://user-images.githubusercontent.com/8731884/51436297-dff5c000-1c8a-11e9-9b64-ca17a36ced97.png)
* [ ] `public/less/themes/arc-green.less` – The dark theme should use a less vibrant color for green buttons, I suggest `#87ab63`, the same color used for links.

**Comment by jolheiser** [comment]
I think I'll give this a go. I'll make a WIP PR once I've made some progress.

EDIT: The PR can be followed at #5980
