### ISSUE TITLE
Minor routing and status code issues

### ISSUE THREAD

**Issue by Larivact** [go-gitea/gitea#5784]
- Gitea version (or commit ref): 1.7.0

## Description

* [x] While Internal Server Errors display 500 they return a 404 status code.
* [x] Missing commits sometimes return a 500 instead of a 404 (seems to be fixed):
https://try.gitea.io/lunny/wewe/commit/000000 returns 404
https://try.gitea.io/lunny/wewe/commit/0000000 returns 500
* [x] If there are no wiki pages, any wiki page returns a 200:
https://try.gitea.io/lunny/wewe/wiki/doesnotexist
* [x] Missing wiki pages should return a 404 instead of redirecting to the index:
  https://try.gitea.io/gittea/curl/wiki/doesnotexist
* [x] Invalid issue / pull requests identifiers redirect to the first issue / pull request instead of returning a 404
 https://try.gitea.io/lunny/wewe/issues/doesnotexist
 https://try.gitea.io/lunny/wewe/pulls/doesnotexist
* [ ] `/user/repo/commit/` and `/user/repo/commits/` should probably redirect to the default branch.

**Comment by adelowo** [comment]
💯

**Comment by lunny** [comment]
I think we can close this now. And I don't agree we should redirect `/user/repo/commit/` to  repository homepage.
