### ISSUE TITLE
Error migrating from version 1.4.3 to version 1.7

### ISSUE THREAD

**Issue by rafaeldeda** [go-gitea/gitea#5792]
- Gitea version (or commit ref): 1.4.3
- Git version: 2.16.4
- Operating system: Linux CentOS 7 x64
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [X] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X] No
  - [ ] Not relevant
- Log gist:

## Description

Guys, we're having trouble migrating Gitea version 1.4.3 to version 1.7. The following is an image illustrating this problem. Emphasize that this problem was reported in issue 4360 (still open) and to reinforce this problem, reopen as a new issue. I did the drop index manually as suggested but when I try to migrate a timeout occurs as mentioned in issue 4360 reported by the employee vinnyaju. I await good news.
Note: Open this new issue as a way to get the attention of the community by the time the issue 4360 is open.

"2019/01/21 09:32:41 [...itea/routers/init.go:61 GlobalInit()] [E] Failed to initialize ORM engine: migrate: do migrate:
Drop table `issue` columns [assignee_id]: mssql: ALTER TABLE DROP COLUMN assignee_id failed because one or more objects access this column."

Thank you!

## Screenshots

![capturar](https://user-images.githubusercontent.com/6736940/51476718-7dc1bb80-1d6d-11e9-8756-8a2d5ec3de88.PNG)

**Comment by lunny** [comment]
duplicated with #4360
