### ISSUE TITLE
Downloads old tar.gz file and on new file got 404 at the webUI

### ISSUE THREAD

**Issue by maxreb** [go-gitea/gitea#5793]
- Gitea version (or commit ref): 8a92544 (Current Docker Version)
- Git version: 2.14.4
- Operating system: Linux Docker
- Database (use `[x]`):
  - [x] PostgreSQL
- Can you reproduce the bug at https://try.gitea.io:
  - [x] No

## Description
I've got a collegue who has created a new git repository on my gitea server. At first everything seemed to work but now everytime he is pushing new commits (with new files) I can't download the files but got a 404 on the webUI. When I try to download the .tar.gz or zip file of the current repository the only files included are the files from the first commit. It is a public repository and I am an employee of that repository. The URL is e.g.:
`https://git.myserver.com/My.Collegue/esz/src/branch/refs/remotes/origin/master/frozen_inference_graph_100k.pb`

`git clone` or `git pull` works like a charme and does not make any problems. 

Yes, I am behind a reverse proxy (nginx) but even if I try to connect directly (docker localhost) I've run into the same problem

## Screenshots

![image](https://user-images.githubusercontent.com/39700092/51479387-5deebf80-1d8e-11e9-84d5-ec86b30a61da.png)

**Comment by lafriks** [comment]
Can not seem to reproduce that, can you reproduce this problem in https://try.gitea.io/?

**Comment by maxreb** [comment]
No i can not. My user is the administrator, the other user is just a user.

**Comment by lafriks** [comment]
I tried both behind reverse proxy and directly and can not reproduce it both using admin user or normal

**Comment by zeripath** [comment]
@maxreb Do you have ENABLE_GZIP set by any chance?

**Comment by maxreb** [comment]
> @maxreb Do you have ENABLE_GZIP set by any chance?

@zeripath I don't have that enabled in my `app.ini`. 

I can't reproduce it either with the actual version (8a92544). It seems that while one commit/push something went corrupt. If noone has any idea what could have triggered this phenomen, I think we can close this issue and I'll ask my collegue to reupload the whole thing in a new repository.
