### ISSUE TITLE
Override embedded bindata

### ISSUE THREAD

**Issue by tboerger** [go-gitea/gitea#58]
Let's integrate a mechanism where we can override the embedded go-bindata with real files on the filesystem. A pretty simple option is to integrate a function that checks first predefined paths for the requested file, if it doesn't exist just use the current bindata behavior. That makes the addition of licenses or customization of gitignores really easy and it sounds like lowhanging fruits :)

**Comment by lunny** [comment]
It sounds good. But I cannot give you a help because I'm not familiar with go-bindata.

**Comment by linquize** [comment]
Some users may want to replace those default values with the one on their file system. So they do not need to compile the program. Isn't it?

**Comment by tboerger** [comment]
I'm familiar enough with go-bindata. This is a small task i would like to do.

@linquize that way every user that wants to do that is able to do that without compiling any binary.

**Comment by tboerger** [comment]
Ok, I really missed something. This already works. If you put new files into conf/ they are already available additionally to the embedded files from go-bindata. I tried it with another locale, added the locale to conf/locale/ and to custom app.ini and it simply works like expected.
