### ISSUE TITLE
Make Pull Request message from PR #4716 configurable

### ISSUE THREAD

**Issue by luxifr** [go-gitea/gitea#5801]
PR #4716 introduced a feature that will output a link to create a PR when pushing to a repo. Personally, I find it pretty annoying and I couldn't find any meaningful discussion on the PR about whether this is at all sensible, to begin with.

I'd argue that teams who already use a PR workflow don't really need this message and teams who decidedly don't use a PR workflow will be just as annoyed as I am because it clutters their output when pushing stuff - every - single - time! While I myself don't do this, I could imagine that this may even break some people's automation when it relies on Git's output on push.

As I wouldn't assume that this is meant to implement some sort of agenda to push people to adopt the PR workflow, this should be optional. Ideally, this should be configurable globally and the global default should be overridable per repository and even per branch. But for starters, a global "on/off" switch for this "feature" should be the least before shipping this.

**Comment by luxifr** [comment]
bump

**Comment by flozzone** [comment]
This message annoys some of our developers too, since we just migrated to gitea we don't use pull requests at the moment (We will do so later on). But for now we would really like to see a possibility to enable/disable the displaying of this message within the global configuration file.

@JulienTant since you implemented this feature, would it be possible for you to add a configuration flag to disable the message?

**Comment by guillep2k** [comment]
We could (should?) suppress the message if PRs are disabled for the repository.

**Comment by JulienTant** [comment]
Hi, I implemented that moons ago and currently won’t find time to make any change on that.

**Comment by zeripath** [comment]
You can change the `templates/repo/issue/view_content/pull.tmpl` template as it stands now. (It's a bit hairy as that template is a bit complex - and frankly it shouldn't be there.)

Probably the best improvement would be to make these things be templatable in some way. Easiest option being just a global template with per repo templates (probably from a file in the default branch .gitea directory) being an extension.

If you can't offer a PR yourself and really want this feature - try to help spec this out further and/or consider offering a bounty on bountysource.

**Comment by flozzone** [comment]
@jolheiser This is exactly what I was looking for. Thanks!
