### ISSUE TITLE
Issue export

### ISSUE THREAD

**Issue by a7hybnj2** [go-gitea/gitea#5803]
- Gitea version (or commit ref): 1.5.2
- Git version: 2.19.1
- Operating system: freeBSD Jail
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [X] SQLite

## Description

This is a question because I messed it up!

I have 2 versions of gitea running 1.4.0 and 1.5.2 and I have active repos in both. I need to migrate the repos from 1.4.0 -> 1.5.2 with the **issues** intact.

Yes - I could, and will if needed, go into each repo and manually copy all the issues over but I would like a way to export and import. Any help would be great!

**Comment by lunny** [comment]
duplicated with #4808
