### ISSUE TITLE
Got "fatal: Could not read from remote repository" when pull from windows repository use ssh.

### ISSUE THREAD

**Issue by fftyjw** [go-gitea/gitea#5807]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [√ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ √] No
  - [ ] Not relevant
- Log gist:

## Description

I use gitea on windows with "START_SSH_SERVER" set to true. But when I pull my repository. I got the following error:
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
The Troubleshooting section in gitea document only give some checklist for linux, but none for windows.

**Comment by gfwing** [comment]
1. did you upload your ssh public key to your gitea account?

2. how do you run the gitea? command line gitea -web or run as service?
please make sure all path are correct and expected as setting.
the path (HOME) may different when you execute gitea as service.

[https://docs.gitea.io/en-us/specific-variables/](https://docs.gitea.io/en-us/specific-variables/)
