### ISSUE TITLE
LDAP problem

### ISSUE THREAD

**Issue by ptman** [go-gitea/gitea#5808]
- Gitea version (or commit ref): 1.7.0
- Git version: docker image
- Operating system: docker
- Database (use `[x]`):
  - [x] PostgreSQL
- Can you reproduce the bug at https://try.gitea.io:
  - [x] No

## Description

LDAP gives protocol error on gitea 1.7.0, works fine using 1.6.4.

**Comment by ptman** [comment]
2019/01/23 12:57:29 [...dels/login_source.go:390 LoginViaLDAP()] [E] LDAP Search failed unexpectedly! (LDAP Result Code 2 "Protocol Error": )

**Comment by lafriks** [comment]
@ptman could you apply #5816 patch on release/v1.7 branch and try if that fixes your problem?

**Comment by ptman** [comment]
Yes, 1.7.1 fixed this, thank you!
