### ISSUE TITLE
Console logger keeps logging after changing default logger

### ISSUE THREAD

**Issue by willemvd** [go-gitea/gitea#581]
Gitea version (or commit ref): 1.0.0 (6aacf4d)

When setting the default logger to something else then "console", it will still log to console on Trace level.

Failing configuration:
[log]
MODE = file
LEVEL = Info
ROOT_PATH = /var/log/gitea

Seems that changing the default logger will not remove the existing console logger that is attached in the settings.go init() 

Workaround which at least limits the console logging:
[log]
MODE = console, file
LEVEL = Info
ROOT_PATH = /var/folders/5c/s85y9_014bd95y0x1wzr1vjm0000gn/T/log

[log.console]
LEVEL = Critical

**Comment by lunny** [comment]
closed by #602
