### ISSUE TITLE
How can the admin change another guy's username?

### ISSUE THREAD

**Issue by yanOnGithub** [go-gitea/gitea#5822]
Another guy's username is readonly when the admin open the user profile.

**Comment by lafriks** [comment]
It is not possible currently but this should be added to user administration page then

**Comment by lafriks** [comment]
yes, that should be enaugh

**Comment by adelowo** [comment]
Duplicate of https://github.com/go-gitea/gitea/issues/1818

**Comment by mxmehl** [comment]
For future reference, it is also necessary to rename the folder of the user in gitea's ROOT path, otherwise the links on the profile page break.

**Comment by yanOnGithub** [comment]
> gitea's ROOT path
What do you mean by ROOT path? Do you mean the gitea-repositories folder? or the GITEA_HOME folder?

**Comment by mxmehl** [comment]
> What do you mean by ROOT path? Do you mean the gitea-repositories folder? or the GITEA_HOME folder?

The former. In app.ini, it's defined as `ROOT` inside the `[repository]` section. This directory contains one folder per user/organisation, and this is the one you'll have to rename.

**Comment by aveao** [comment]
For further future reference, you'll also want to update user's repositories to point to the right owner_name.

This is what we had to do to move a user (other than also moving the directory):
`UPDATE public.user SET name = 'newname', lower_name = 'newname' WHERE name = 'oldname';`
`UPDATE public.repository SET owner_name='newname' WHERE owner_id=123;`
