### ISSUE TITLE
Unable to merge pull request

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#5824]
- Gitea version (or commit ref): 386e531
- Git version: git version 2.20.1
- Operating system: macOS
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:
```
[...routers/repo/pull.go:589 MergePullRequest()] [E] Merge: Writing sparse-checkout file to /Users/user/giteatmp/tmp/local-repo/merge-70720432.git/.git/info/sparse-checkout: open /Users/user/giteatmp/tmp/local-repo/merge-70720432.git/.git/info/sparse-checkout: no such file or directory
```
## Description

Use squash merge style
@typeless

**Comment by typeless** [comment]
~~@yasuokav Have you mixed up with other changes?
The message should be at [L452](https://github.com/go-gitea/gitea/blob/386e5312a4830ae9f87d00d7d95c8c849d50a06f/models/pull.go#L452), not L589.~~

oops, I confused the file path. sorry.

**Comment by typeless** [comment]
I have no access to a MacOS machine for now.
But I have a conjecture that the `info` directory under `.git` might not exist under certain circumstances.

Can you comment out https://github.com/go-gitea/gitea/blob/386e5312a4830ae9f87d00d7d95c8c849d50a06f/models/pull.go#L399 and look into the path to verify that?

I can submit a patch to create `.git/info`, but it'd be better if we can make sure.

**Comment by typeless** [comment]
@yasuokav https://github.com/go-gitea/gitea/pull/5825 

If you can verify this PR, that would be nice.

**Comment by ghost** [comment]
> @yasuokav #5825
> 
> If you can verify this PR, that would be nice.

This PR will cause another problem.
```
[...routers/repo/pull.go:589 MergePullRequest()] [E] Merge: Writing sparse-checkout file to /Users/user/giteatmp/tmp/local-repo/merge-915998714.git/.git/info/sparse-checkout: open /Users/user/giteatmp/tmp/local-repo/merge-915998714.git/.git/info/sparse-checkout: permission denied
```

```
cd info
cd: permission denied: info

...
drwxr-xr-x  hooks
drw-------  info
drwxr-xr-x  logs
drwxr-xr-x  objects
...
```

**Comment by typeless** [comment]
My bad. I have updated the PR.

**Comment by ghost** [comment]
@typeless This PR solves this problem! Thank you
