### ISSUE TITLE
How can the admin force an existing user to change his password on the next login?

### ISSUE THREAD

**Issue by yanOnGithub** [go-gitea/gitea#5827]
The user is not new. He is an existing user. The "force password change" checkbox is only available when the admin creates the user. The checkbox is gone for existing users.

**Comment by yanOnGithub** [comment]
I have seen #4340.

**Comment by yanOnGithub** [comment]
Is it sufficient to set user.must_change_password=1 in gitea.db?

**Comment by lafriks** [comment]
yes
