### ISSUE TITLE
Question: Will it accidentally deletes other temp directories?

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#5828]
For example, my local-repo folder is in `/tmp/local-repo`

https://github.com/go-gitea/gitea/blob/ec31ee1c1cd028dc59292e19d4b1c9dd954ba364/models/pull.go#L399
`local-repo` and `merge-xxxxxx.git`
Both of these two directories will be deleted after a PR was merged.
So my question is what happens if merging multiple PRs at the same time. Is it a potential problem? Because `local-repo` will be deleted as well.

**Comment by lafriks** [comment]
`local-repo` will not be deleted for each merge unique directory is created

**Comment by ghost** [comment]
> `local-repo` will not be deleted for each merge unique directory is created

@lafriks Please check #5829
