### ISSUE TITLE
Entire "LOCAL_COPY_PATH" directory is getting deleted after a PR was merged

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#5829]
- Gitea version (or commit ref): 1.7.0 / cd83c2c
- Git version: 2.20.1
- Operating system: macOS
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

Related: #5828

https://github.com/go-gitea/gitea/blob/ec31ee1c1cd028dc59292e19d4b1c9dd954ba364/models/pull.go#L399

`path.Dir` return `local-repo` directory and `os.RemoveAll` will delete the entire `local-repo` directory after a PR was merged

**Comment by zeripath** [comment]
This is also the case for the editor...

**Comment by lafriks** [comment]
yes, you ar right, it should be:
```go
defer os.RemoveAll(tmpBasePath)
```

**Comment by typeless** [comment]
@yasuokav Would you like to submit a patch?

**Comment by ghost** [comment]
@typeless I will do it soon
