### ISSUE TITLE
Allow pagination for git tree API

### ISSUE THREAD

**Issue by richmahn** [go-gitea/gitea#5837]
The git tree API only allows showing the first 1000 files of a repo. GitHub does not allow showing more, understandable for a free, public Git service, requiring the user/app to clone the whole repo. Yet this is exactly what my organization would like to avoid when showing a list of the files a user can get in an app. Better is to add paging where the `truncated` field in the response is true until we get to the last page.

**Comment by lunny** [comment]
Closed by #5838
