### ISSUE TITLE
Git tag support in the UI

### ISSUE THREAD

**Issue by silverwind** [go-gitea/gitea#5842]
The UI is currently missing support for git tags. I propose the following additions:

- A page that lists all tags `/user/repo/tags`
- Handling of individual tag URLs `/user/repo/tags/{tag}`. They could either redirect to the tagged commit or present a individual page like GitHub does.
- If a commit is tagged, show it on the commit page and maybe on the commit list.
- Show a counter of tags in the repository statistics.

Related: https://github.com/go-gitea/gitea/issues/5693 (possible prereq?)

**Comment by JLuc** [comment]
Also add an easy-to-use button to git tag

**Comment by johanneshiry** [comment]
We're also missing this feature. Is there any progress on this feature request so far?

**Comment by jolheiser** [comment]
I believe this has been mostly implemented. 

* [list tags](https://try.gitea.io/jolheiser/go-test/tags)
* [currently redirect to code view using tag tree](https://try.gitea.io/jolheiser/go-test/src/tag/testest)
* This has not been implemented yet on the commits page, however it can be seen on the [graph](https://try.gitea.io/jolheiser/go-test/graph), and can be seen on an individual [commit page](https://try.gitea.io/jolheiser/go-test/commit/f9e2014a31246c782530ae39d4f4c346e6e68fd8)
* ![tags](https://user-images.githubusercontent.com/42128690/107656662-01e38600-6c4a-11eb-82b8-9b3f8b2c2acc.png)
