### ISSUE TITLE
Autolinked URLs: fragment components not included in generated link

### ISSUE THREAD

**Issue by veita** [go-gitea/gitea#5844]
## Description

Some autolinked URLs are not linked correctly. E.g.

```
https://github.com/go-gitea/gitea/?p=aaa/bbb.html#ccc-ddd
```

is rendered without the fragment component. The same URL works on GitHub:

https://github.com/go-gitea/gitea/?p=aaa/bbb.html#ccc-ddd

**Comment by lunny** [comment]
Which gitea version are you using?

**Comment by veita** [comment]
Gitea version 1.6.3 or 1.6.4.

**Comment by veita** [comment]
The issue exist also in version 1.7.1.

**Comment by zeripath** [comment]
@veita could you give an example of a Gitea path that doesn't work on try.gitea.io . It would hello to completely identify and fix this issue

**Comment by veita** [comment]
Just put the link given in the issue description into a `README.md` or wiki page. Then you'll see that `#ccc-ddd` is not rendered as a part of the generated link.

**Comment by techknowlogick** [comment]
Closing per merged PR

**Comment by veita** [comment]
I can confirm that the issue is fixed in Gitea 1.8.0.
