### ISSUE TITLE
Add none to license selection

### ISSUE THREAD

**Issue by 0x5c** [go-gitea/gitea#5861]
- Gitea version (or commit ref): Docker 1.7.0, 3fa49f3

## Description
When creating a repository, the license selector lacks a no-license option, forcing the user to selects a license if the selector is clicked by accident.

## Screenshots
I would provide some, but the issue is not really _visual._

**Comment by Larivact** [comment]
Duplicate of #5782.

**Comment by 0x5c** [comment]
"Duplicate of a meta-issue" but ok

**Comment by 0x5c** [comment]
Note that searching for potentially existing issues relating the same problem **will not** return meta-issues.
@Larivact

**Comment by techknowlogick** [comment]
Other issue is meta issue, will keep this one open
