### ISSUE TITLE
Heatmap: hue gradient instead of saturation

### ISSUE THREAD

**Issue by davidak** [go-gitea/gitea#5864]
- Gitea version (or commit ref): 1.7
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

GitHub is perfect.

### Gitea

![screenshot from 2019-01-26 17-44-33](https://user-images.githubusercontent.com/91113/51790180-10a98e00-2192-11e9-9cfc-f1eca0c265f0.png)

### GitHub

![screenshot from 2019-01-26 17-44-53](https://user-images.githubusercontent.com/91113/51790186-1b642300-2192-11e9-9e49-101ef06740fa.png)

### GitLab

![screenshot from 2019-01-26 17-45-23](https://user-images.githubusercontent.com/91113/51790196-346cd400-2192-11e9-89c4-04a8fbbae706.png)

**Comment by zeripath** [comment]
I'm not sure. I've never quite been able to understand GitHubs hue gradient - saturation seems intuitive to me.

**Comment by davidak** [comment]
@zeripath darker color means more activity. I think that's commonly used for visualization.

The current implementation seems too simple in that space.

It looks too dark and feels depressing to me. It should have the bright green of the logo included.

**Comment by 0x5c** [comment]
Ah yes, that's the problem that I was having with it, without knowing what it was.

I might be able to make a palette today.

**Comment by 0x5c** [comment]
Okay, so I took a look at the three palettes, and they all are gradient on hue, saturation, *and* value.
What seems to be different is the curves done on the colour-picker; GitHub and GitLab both do a curve towards the saturated/high-value corner, while Gitea does a curve in the opposite direction.

**Comment by 0x5c** [comment]
I've done some work on colouring

## Current palette
![](https://coolors.co/export/png/d0e7da-a0cca8-6fb078-399778-007616)

## Proposed palette n°1
Partial, not really suitable as-is.
![](https://coolors.co/export/png/e8fccf-b2e898-4eab6b-609926-134611)

## Proposed palette n°2
![](https://coolors.co/export/png/cde5b3-9fdb81-71bc5c-609926-025900)

Those proposition only contain 5 colours; it is assumed that the first one is the current (`#F4F4F4`).
The Gitea colour (`#609926`) is included in both, at the before-last position.
Feel free to modify or expand on these.

**Comment by davidak** [comment]
@0x5c thank you!

The gradient in the first palette looks a bit hard. The color in the middle looks very unnatural. Maybe that is what you mean with "not suitable as-is".

The seconds palette looks great! Could you try it out with the actual heatmap in the browser?

Here are profiles i found with actual activity:

https://codeberg.org/hw?tab=activity
https://codeberg.org/wahn?tab=activity

**Comment by 0x5c** [comment]
No problem!
I'll try it, and maybe tweak prop2 a slight bit.
As for prop1, this is exactly what I meant, but I included it as a possible starting point for someone else, as it's what I used as a base for prop2.

**Comment by 0x5c** [comment]
Ewwwwww
So the boxes are not coloured by CSS styles, which means I'll have to manually replace the colours.

**Comment by 0x5c** [comment]
I have not yet been able to try recoloring, but I suspect that it will cause problems as the squares are somehow anti-aliased *(why?)*.

I was able, however, to create this 3rd version, which now follows an entirely convex curve.

## Proposed palette n°3
![](https://coolors.co/export/png/cde5b3-9fdb81-66c74b-609926-025900)

**Comment by davidak** [comment]
@0x5c 3. looks good!

I just used GIMPs replace color tool on a screenshot. Looks perfect!

![screenshot from 2019-01-28 17-55-32](https://user-images.githubusercontent.com/91113/51853075-b4787280-2327-11e9-93e3-cc218bbe3720.png)

When it's this small and i go back 1 meter from the display, the contrast is not that high. I can hardly tell a difference between the 2. and 3. color. I think it's a little better on GitHub since it's a different color tone.

**Comment by 0x5c** [comment]
Oh nice!
I see what you mean for colour 2/3, but I don't think that it would be *that* much of a problem?
I could try a slight variation on colour 2 (one in the palettes).

**Comment by 0x5c** [comment]
## Palette proposition v4
Slightly tweaked the first one from `#cde5b3` to `#d8efbf`.
(actual first is still `#f4f4f4`)
![](https://coolors.co/export/png/d8efbf-9fdb81-66c74b-609926-025900)

**Comment by davidak** [comment]
Yeah, it might not be a problem. Already a huge improvement to the current colors.

**Comment by 0x5c** [comment]
Welp
The colours are auto-generated by [cal-heatmap](https://cal-heatmap.com/), which seems to have no concept of *humans are supposed to see this*.
It takes two colours, and then proceeds to create the most eye-stabbing gradient possible. It's also the reason why the heatmap squares have fudgy edges, even on the showcase site.

I do not see how, using this library, the colours of the heatmap could be fixed.

**Edit:**
Note that github uses absolute and defined values (the ones in the legend) for the colours.

**Comment by davidak** [comment]
@0x5c so, when there is no better library we have to submit bugreports upstream and maybe find someone who can fix it. It could optionally be possible to set the colors manually.

**Comment by zeripath** [comment]
Looking at the upstream if we just don't set the legendColors we should be able to use the .q1-.q5 css to set the colors

**Comment by 0x5c** [comment]
Seems to be an issue of how thing are done (upstream, that is).
As for better libraries, I think that the issues is of actually choosing, as there seems to be a ton of heatmap libraries that use the exact same dataset (would only need changes on the client side).

**Comment by 0x5c** [comment]
Nice of the upstream documentation to making this clear 😅.

**Comment by zeripath** [comment]
Actually I think it's not q1 but in here: https://github.com/go-gitea/gitea/blob/0b510725c97452bac57ff0080df10f6177aa2a6e/public/less/_base.less#L609

**Comment by 0x5c** [comment]
If the palette I proposed is liked, I'd like to attempt making a PR, although I could need pointers on how to tackle Gitea's code.

**Comment by zeripath** [comment]
So simply changing those 6 classes should do it?

**Comment by zeripath** [comment]
@0x5c I think would be a quite simple PR - just change the less code, commit and put up a pr with screenshots of what it used to look like and what it now looks like.

**Comment by zeripath** [comment]
Changing the values in the less file, then run `make generate-stylesheets`should do it afaics

**Comment by 0x5c** [comment]
Okay, so
```none
Each colors correspond to a CSS class, formatted like .q{n}.
```
That's clearly definable in CSS, which means that
- It would actually fix #5164
- It would supersede #5165

**Comment by zeripath** [comment]
At least in master we're actually using the vue-calendar-heatmap module rather than that cal-heatmap package.

**Comment by 0x5c** [comment]
*What?* Where is the PR for that?

**Comment by jolheiser** [comment]
https://github.com/go-gitea/gitea/pull/5401

**Comment by zeripath** [comment]
Those are actually less files so you then need to generate-stylesheet but yes.

**Comment by 0x5c** [comment]
Simple PR then :)
~~Would setting up a dev environment be required?~~ *Edit: When I think, things become clear: **TESTING***

**Comment by cdlm** [comment]
Please take care of reversing the palette in the dark theme, so that higher contrast to the background color (more visual pop) signifies more contributions. I've just updated to 1.7.1 and it's backwards :-)

![gitea arc-theme backwards heatmap gradient](https://user-images.githubusercontent.com/136339/52567533-dc2e0700-2e0c-11e9-861a-01c1a8bd5545.png)

**Comment by 0x5c** [comment]
The dark theme will need its own palette

**Comment by zeripath** [comment]
How's things with this? Are you ready for a pr? I know the deadline for 1.8 is coming up so if want this change in 1.8 a PR is needed soon.

**Comment by 0x5c** [comment]
I had *massive* issues with my computer, but that is solved now. I will be working on that today.

**Comment by kolaente** [comment]
@0x5c Any updates on this?

**Comment by 0x5c** [comment]
Oh damn, I had forgotten about this.

**Comment by MayMeow** [comment]
I have implemented this on https://kittyverse.co/may?tab=activity (you can check). Implemented is palette 4. If its ok i can make pull request. or implemetn any other palette. :)

**Comment by davidak** [comment]
@MayMeow looks good. please create a PR.

**Comment by 0x5c** [comment]
Oh damn, I had forgotten about this.

Thank you for making the PR :)

**Comment by MayMeow** [comment]
@0x5c @cdlm  Sorry about that :) i didnt used dark theme so i didnt know
