### ISSUE TITLE
Webhook empty text

### ISSUE THREAD

**Issue by FriedrichVonSchnitzel** [go-gitea/gitea#5865]
- Gitea version (or commit ref): a757920
- Git version:
- Operating system: Debian (docker)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:
``` 4ebaceaf-ecfd-4522-8873-bdff299d4244 2019-01-26 23:44:58 UTC
Request
Response
200
Headers
Request URL: https://hooks.slack.com/services/.../.../..........
Request method: POST
Content-Type: application/json
X-GitHub-Delivery: 4ebaceaf-ecfd-4522-8873-bdff299d4244
X-GitHub-Event: issues
X-Gitea-Delivery: 4ebaceaf-ecfd-4522-8873-bdff299d4244
X-Gitea-Event: issues
X-Gogs-Delivery: 4ebaceaf-ecfd-4522-8873-bdff299d4244
X-Gogs-Event: issues
Content
{
  "channel": "#channel",
  "text": "",
  "username": "Gitea",
  "icon_url": "http://domain.com:3000/img/gitea-sm.png",
  "unfurl_links": 0,
  "link_names": 0,
  "attachments": [
    {
      "fallback": "",
      "color": "",
      "title": "",
      "text": ""
    }
  ]
}
```
## Description
Webhooks to slack contain empty texts when notifying about milestones assigned to issues. 
The bug occurs regardless of what is selected in the webhook settings (Trigger on: All events / Custom Events... - all selected). Example Webhook request from "Recent deliveries" provided above. 
...

## Screenshots

![untitled](https://user-images.githubusercontent.com/16023334/51794265-35702680-21cf-11e9-8dfe-901ceae212ef.png)

**Comment by KubqoA** [comment]
It's probably due to the fact, that the [slack webhook implementation for issues](https://github.com/go-gitea/gitea/blob/5704b21165a28b72d502fdea6ba5c6fdf6b3b05e/models/webhook_slack.go#L134) doesn't check for `api.HookIssueMilestoned` and `api.HookIssueDemilestoned`. Maybe I could write you a PR.
