### ISSUE TITLE
Git clone via SSH hangs when markup.asciidoc is partially defined in config

### ISSUE THREAD

**Issue by dllud** [go-gitea/gitea#5866]
- Gitea version (or commit ref): 1.7.0
- Git version: 2.11.0
- Operating system: Debian 9 (stable)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
Adding the `markup.asciidoc` section to the `app.ini` config file without having *all* properties defined causes git clone via ssh to hang.
I bumped into this issue after adding the `markup.asciidoc` section to my old config file, but I was able to reproduce the issue on a new installation with a config file generated from scratch by gitea `1.7.0`.

Adding the section, with all properties defined, causes no problem (example bellow):
```ini
[markup.asciidoc]
ENABLED = false
; List of file extensions that should be rendered by an external command
FILE_EXTENSIONS = .adoc,.asciidoc
; External command to render all matching extensions
RENDER_COMMAND = "asciidoc --out-file=- -"
; Don't pass the file on STDIN, pass the filename as argument instead.
IS_INPUT_FILE = false
```

Commenting or deleting just one property causes the hang:
```ini
[markup.asciidoc]
ENABLED = false
; List of file extensions that should be rendered by an external command
;FILE_EXTENSIONS = .adoc,.asciidoc
; External command to render all matching extensions
RENDER_COMMAND = "asciidoc --out-file=- -"
; Don't pass the file on STDIN, pass the filename as argument instead.
IS_INPUT_FILE = false
```

Even adding just the section header causes ssh git clone to hang:
```ini
[markup.asciidoc]
```

This issue seems related to #5386.

**Comment by zeripath** [comment]
The problem is caused by any `log.Warn` in `func NewContext()` in `setting.go`.

The issue is that these are outputted on stdout which confuses git.
