### ISSUE TITLE
DISABLE_REGULAR_ORG_CREATION is not working

### ISSUE THREAD

**Issue by lachnerd** [go-gitea/gitea#5882]
- Gitea version (or commit ref): 1.7.0
- Git version: ?
- Operating system: Linux - Docker
- Database (use `[x]`): mariadb 10.3.14
- Can you reproduce the bug at https://try.gitea.io: Not relevant
- Log gist:

## Description

I tried DISABLE_REGULAR_ORG_CREATION=true to limit orga-creation only to admin users but still all users are able to create organizations.

I set the property to false & true in case i misunderstood the meaning but it didn't help.

**Comment by adelowo** [comment]
Hi, @lachnerd Thanks for the bug report. That config value wasn't actually being used while creating the user. I have sent a patch though.
