### ISSUE TITLE
org problem with file

### ISSUE THREAD

**Issue by igor9292** [go-gitea/gitea#5898]
- Gitea version (or commit ref): 1.7
- Git version:2.1.12
- Operating system: rhel 7
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL) https://try.gitea.io/howdoicomputer/org-test
  - [ ] No
  - [ ] Not relevant
- Log gist: ere

Why is this not working? http 500 when click on test.org

**Comment by ghost** [comment]
Maybe related to this issue: chaseadamsio/goorgeous#82

**Comment by igor9292** [comment]
what logs are needed? There is nothing in the logs for this error.

**Comment by ghost** [comment]
duplicate with #4982

**Comment by zeripath** [comment]
If you were running a local instance of Gitea, could you put up some logs. I guess you're only testing on try.gitea.io, and haven't run Gitea locally yet?

@yasuokav That's suspiciously close to what we're seeing - it would be excellent to see the error in the logs so we can actually find out where the error is being thrown.

My main issue is that the error isn't being caught and instead we're getting a panic so you don't see the Gitea 500 page.

**Comment by ghost** [comment]
@zeripath you can check the log on #4982 because the test repo is the same

**Comment by zeripath** [comment]
Thanks @yasuokav. I'll close this and take a look at that.
