### ISSUE TITLE
Remove all watchers from a repository

### ISSUE THREAD

**Issue by markusamshove** [go-gitea/gitea#5917]
- Gitea version (or commit ref): 1.7
- Database (use `[x]`):
  - [x] PostgreSQL
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Not relevant

## Description

I've migrated all our corporate repositories to a selfhosted Gitea instance and we're liking it a lot so far.

The migration was done via the REST API for every repository we had on another hosting service.

I'd like to turn on email notifications for mentions and PRs, but the migration sadly added all users as watchers to all repositories.

Is it possible to remove all watcher from all repositories? At the moment developers would get emails even for repositories they don't care about.

**Comment by markusamshove** [comment]
Maybe there is a save SQL statement I can run? :-)

**Comment by lafriks** [comment]
Yes you can easily remove that using sql

**Comment by sebastian-sauer** [comment]
What you should keep in mind is that currently all users of a team will watch new repos added to the team by default and i think a new user added to a team will watch all repos of the team automatically.

There is a merged PR for 1.8 (#5852) to disable this automatic behaviour.

**Comment by markusamshove** [comment]
`DELETE FROM watch` was all I had to do and was save to execute.
Gitea needed to be restarted to see the changes in the UI.

The setting from #5852 will fix the original issue, so I'm closing 😄
