### ISSUE TITLE
Cannot delete branch protection when branch is deleted

### ISSUE THREAD

**Issue by exploide** [go-gitea/gitea#5922]
- Gitea version (or commit ref): 1.7.0
- Operating system: Debian
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite

## Description

When a branch was configured with protection but deleted at a later point in time, the protection is still visible in the settings. Unfortunately I cannot delete the protection because when clicking the edit button, the branch protection settings page results in a 404. I also cannot push to the branch to recreate it because it is protected.

I can probably only delete it with database access.

Ideally Gitea wouldn't go into this state. Now that such cases already exist, maybe the branch protection can automatically be deleted when Gitea detects that the branch is missing.

**Comment by lafriks** [comment]
imho it should not be possible to delete protected branches...

**Comment by zeripath** [comment]
How did you delete the protected branch?

Looking at DeleteBranchPost(...) it shouldn't be possible... Nor should it be possible from CleanUpPullRequest(...)

**Comment by exploide** [comment]
Don't know, it wasn't me deleting the branch but this inconsistent state is present for a while. Probably it got deleted when these additional checks weren't implemented yet.

If you tell me this cannot happen again then I'm fine with deleting this manually from the database (if possible). Alternatively, a future version of Gitea could have a cleanup routine or something for such cases. You decide :P

**Comment by lafriks** [comment]
Closing as currently it should not be possible to delete protected branch. Reopen if you can provide way to reproduce this
