### ISSUE TITLE
Database Error on update to 1.7.1

### ISSUE THREAD

**Issue by vbonline** [go-gitea/gitea#5923]
- Gitea version (or commit ref):
- Git version: 1.7.1
- Operating system: Ubuntu 18.04.1
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:
2019/02/01 09:52:22 [I] ORM engine initialization attempt #10/10...                                         
2019/02/01 09:52:23 [...itea/routers/init.go:81 GlobalInit()] [E] ORM engine initialization failed: sync database struct error: Error 1138: Invalid use of NULL value

## Description
Trying an update from gitea-1.60 to gitea.1.7.1. gitea-1.7.1 doesn't start, error in logfile pointing to error in mysql database.
...

**Comment by techknowlogick** [comment]
Are you able to enable DB logging, and post the SQL statement that is failing? Info on how to enable that can be found here: https://docs.gitea.io/en-us/config-cheat-sheet/

**Comment by vbonline** [comment]
Enabled DB-Logging, downloaded latest Master Binary, restarted and it worked without error.

Disabled DB-Logging restarted and gitea-1.7.1 works without an error.

Slightly baffled, but everything is fine now.
