### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by pandelix** [go-gitea/gitea#5930]
I downloaded "gitea-1.7.0-rc2-windows-4.0-386.exe" for installation, but the command window just flashed  across. My server system was Windows 2008 R2. I also reinstalled the system for this purpose, but it was useless.

**Comment by techknowlogick** [comment]
The binary can't be double clicked to open, you must run the command in an already opened command window. Please see: https://docs.gitea.io/en-us/install-from-binary/ for more information.

Closing this issue for now, and please feel free to continue this discussion in the forum: https://discourse.gitea.io/

**Comment by pandelix** [comment]
No, no, No. I found the problem. I haven't installed "git" yet. However, it can be opened by double-clicking, but you can't see the error message when you double-click on it.
