### ISSUE TITLE
Respository's home page not updated after first push

### ISSUE THREAD

**Issue by FloMiau** [go-gitea/gitea#5933]
- Gitea version (or commit ref): 1.7.0
- Git version: 2.17.1
- Operating system: Ubuntu 18.04 LTS
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
I think it is the same problem as in Issue #3458

The fix was:
https://github.com/go-gitea/gitea/issues/3458#issuecomment-381531981

**Comment by lunny** [comment]
any more details?

**Comment by Sebazzz** [comment]
We noticed this happening after a migration from SVN to gittea using Subgit.
