### ISSUE TITLE
Add more logging to the startup process

### ISSUE THREAD

**Issue by markusamshove** [go-gitea/gitea#5953]
- Gitea version (or commit ref): 1.7.1
- Operating system: SuSe Linux 12
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

At the moment when upgrading Gitea to a new version, it always seem to do some kind of background job before the instance is ready.

The log isn't really transparent about what it is doing, so everytime I update our production instance it is starting up quietly for around 2 long minutes before my heart is greeted with a relieving `Listen: http://0.0.0.0:3000`.

I've had startup failures in earlier updates where there also wasn't any log and I had to figure out what was going on.

It would help me a lot when Gitea would do some more logging on the startup, e.g. before the webserver is started and serving.
This could be either about starting/finishing jobs or being more verbose in general.

**Comment by zeripath** [comment]
Heya @MarkusAmshove, I think you're right. At present we both too verbose and not verbose enough.

I think our logging infrastructure needs a bit of an overhaul:
* Our router log should be emitting in the standard form and probably to http.log - my pr doesn't do this properly either. 
* In keeping with this, only the Macaron router should be allowed to touch http.log
* It should be possible to with configuration to redirect different module logs to different places. Turning on debug and trace for particular things should be easy and relatively cheap. 
* If we are going to have log rotation built in we should compress etc.
* As an aside we should handle `kill -HUP` correctly.

The trouble is, if not done correctly these are breaking changes - but if we're going to do this we should do it sooner rather than later.

**Comment by markusamshove** [comment]
I had to restart the Gitea service today and since the update to 1.7.1 the log is the following (with `INFO` log):

```
2019/02/05 08:30:54 [I] Log Mode: File(Info)                                                                                      
2019/02/05 08:30:54 [I] XORM Log Mode: File(Info)                                                                                 
2019/02/05 08:30:54 [I] Cache Service Enabled                                                                                     
2019/02/05 08:30:54 [I] Session Service Enabled                                                                                   
2019/02/05 08:30:54 [I] Mail Service Enabled                                                                                      
2019/02/05 08:30:54 [I] Notify Mail Service Enabled                                                                               
2019/02/05 08:30:55 [I] Git Version: 2.12.3                                                                                       
2019/02/05 08:34:42 [I] SQLite3 Supported                                                                                         
2019/02/05 08:34:42 [I] Run Mode: Production                                                                                      
2019/02/05 08:34:43 [I] Listen: http://0.0.0.0:3000                                                                               
2019/02/05 08:34:43 [I] LFS server enabled          
```

The startup takes around 4 minutes, which is extremly high compared to earlier startups (so just my experience) and I have no indication what Gitea is doing.
Increasing the log level to `Trace` I get the information I need (doing cleanup jobs), but then I'm flooding the log files while GItea is running for days.

I would love to see such tasks in the startup log be mentioned, because I have no idea if I just broke something or I have to wait a bit longer :smile:

**Comment by lunny** [comment]
@MarkusAmshove are you running gitea on Windows?

**Comment by markusamshove** [comment]
```
Distributor ID: SUSE
Description:    SUSE Linux Enterprise Server 12 SP3
Release:        12.3
```
