### ISSUE TITLE
 team in the organization to create repositories within the organization

### ISSUE THREAD

**Issue by igor9292** [go-gitea/gitea#5958]
- Gitea version (or commit ref): 1.7
- Git version: 2.1.2
- Operating system: rhel
- Database (use `[x]`):
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X] No
  - [ ] Not relevant
- Log gist:

Question

Is it possible to allow the team in the organization to create repositories within the organization?
Neither when “Write Access” rights are set, nor when “Adminitstrator Access” rights are set, this feature is not provided.

The only thing that can be done is to drive all users into the owners of the organization, but here there are a couple of minuses:
• inconvenient admin - in the owners, I can not add a command - all will have to add manually;
• dangerous - any user will be able to delete any repository within the organization, and of the organization itself with all repositories.

**Comment by igor9292** [comment]
I found another problem when I do the owners of the organization, then they can not do push in the repository of the organization, if they are not administrators Gitea. 

If you are an organization owner and not a Gitea administrator and you have not created an organization Admins group where you are enabled, you will not be able to push the repository you created

**Comment by lunny** [comment]
@igor9292 please fire another issue to report that since this one is duplicated with #5114, I will close this one, please discuss there further.
