### ISSUE TITLE
API endpoint for updating repository description

### ISSUE THREAD

**Issue by hannekot** [go-gitea/gitea#5960]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
I don't see that there is a way to edit the repository description using the Gitea API, is this a feature that will be added? I see that you can edit the organization description, so why not the repository description

**Comment by shatterstone** [comment]
being able to edit a repo via API would be good. My specific needs would be to set the private boolean via API. I figure that's similar enough that I could piggyback onto this issue as well :)

**Comment by adelowo** [comment]
- [ ] Edit Repo description.
- [ ] Toggle visibility status.
- [ ] Toggle archival status of a repo

**Comment by richmahn** [comment]
My org wants me to take this on, so will be adding this API endpoint like Github's.

**Comment by richmahn** [comment]
To add to the list:

- [ ] Change repo name

**Comment by tomtom125** [comment]
Is there any improvements on this issue? It would be great if it will be available in the next Gitea version:)

**Comment by richmahn** [comment]
@tomtom125 Just got it done!

**Comment by tomtom125** [comment]
Thanks! :)
