### ISSUE TITLE
Webhook for Microsoft Teams

### ISSUE THREAD

**Issue by frunika** [go-gitea/gitea#5964]
Would be useful to have Webhook Support for Microsoft Teams.

[Microsoft Teams Incoming Webhooks First Steps](https://docs.microsoft.com/de-de/outlook/actionable-messages/send-via-connectors)

[Microsoft Teams Message Card Reference](https://docs.microsoft.com/de-de/outlook/actionable-messages/message-card-reference)

Where could I start to implement. Do we just need a "template"?

**Comment by jolheiser** [comment]
[This search should be a good place to start](https://github.com/go-gitea/gitea/search?q=discord&type=Code)   
  
Anywhere there is a Discord (or other) webhook will likely need some slight modifications to allow for another webhook.

**Comment by neilherbertuk** [comment]
+1 for this, just moved from mattermost (which supports Slack webhooks) to Microsoft Teams. Would be extremely useful to have full support for this.

**Comment by road42** [comment]
I'll use that too. I thought about writing some kind of WebApi converting gitea webhooks to teams. @frunika tell me please if there is something to test.

**Comment by dangrier** [comment]
@road42 Microsoft Teams webhooks are now in master if you still wanted to try them out

**Comment by techknowlogick** [comment]
Closing per merged Pr

**Comment by frunika** [comment]
Works perfect! :)
