### ISSUE TITLE
can't evaluate field UseSendmail in type interface

### ISSUE THREAD

**Issue by lsampaioweb** [go-gitea/gitea#5972]
- Gitea version (or commit ref): 4a747ae built with: bindata, sqlite, sqlite_unlock_notify
- Git version: 2.18.1
- Operating system: Mac OSX Mojave with docker 2.0.0.2 (30215)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [X] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X] No
  - [ ] Not relevant
- Log gist:
template: admin/config:187:21: executing "admin/config" at <.Mailer.UseSendmail>: can't evaluate field UseSendmail in type interface {}

## Description
Today I ran "docker image pull gitea/gitea:latest", and now every time I go to the page "admin/config" I get the error message above. The other pages are ok.

**Comment by techknowlogick** [comment]
Thanks for reporting this 😄 This is likely related to this line: https://github.com/go-gitea/gitea/blob/master/templates/admin/config.tmpl#L187

There was recently a PR to add new mailer types, where this option was deprecated. I'll create a PR for this in a few hours, unless you want to create one first.

**Comment by zeripath** [comment]
Sorry!

I missed that!
