### ISSUE TITLE
Change U2F app.ini.sample

### ISSUE THREAD

**Issue by jolheiser** [go-gitea/gitea#5982]
Creating this issue to tie in any relevant other issues caused by this. 
This is the cause of #4260 #4692 #5394 #5406 #5526 (maybe others as well, linking them here for a quick reference to close any as needed with PR, and to link back to this issue)

[These lines](https://github.com/go-gitea/gitea/blob/master/custom/conf/app.ini.sample#L664-L669) in the `app.ini.sample` are referencing a key from a different section (which is [invalid](https://ini.unknwon.io/docs/howto/work_with_values#recursive-values)), and so when users copy the `app.ini.sample` over their own, the default values are causing Gitea to crash on startup.  
  
I'd be happy to put in a PR to fix it, however I'd like opinions on the "best" way to do it.  
1. We could move those three values out of the [server] section and into the default section so everything has access to them.
2. We could add those three values to the [U2F] section (I don't particularly like this implementation, as it means more redundancy)
3. We could change the sample values to some other generic format and/or comment them out, implying users will need to change them to get them working. i.e. `APP_ID = http://localhost:3000/`

**Comment by techknowlogick** [comment]
I like option 3 (commenting out existing values, and adding a note that users need to change them to get them working.
