### ISSUE TITLE
Repo header formatting issue

### ISSUE THREAD

**Issue by jolheiser** [go-gitea/gitea#5985]
- Gitea version (or commit ref): master
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

There is an issue with the new formatting of repo headers when it comes to [forked](https://try.gitea.io/jolheiser/test2) or [mirrored](https://try.gitea.io/jolheiser/gitea) repositories.  
Looks like it may be a result of #5945?

## Screenshots

![gitea-header](https://user-images.githubusercontent.com/42128690/52377995-0efe8680-2a2c-11e9-9a12-ac6293f4c682.png)
)

**Comment by lunny** [comment]
@silverwind could you check this issue?

**Comment by silverwind** [comment]
Yeah will do.
