### ISSUE TITLE
Empty commit graph

### ISSUE THREAD

**Issue by strk** [go-gitea/gitea#599]
- Gitea version (or commit ref): 79d527195d98d74867a067ce93a4dace2b86d2bb (1.1.0-dev)
- Can you reproduce the bug at https://try.gitea.io:
  Yes - https://try.gitea.io/strk/qgis/graph

Commit graph is empty

**Comment by Bwko** [comment]
@kjellkvinge Could you look at this?

**Comment by kjellkvinge** [comment]
Sure. I'll look at it.

It looks like width of the canvas (the graph) takes up all the space. On my laptop i can see the graph and the commitref.
![screenshot from 2017-01-05 22-51-56](https://cloud.githubusercontent.com/assets/3092520/21698952/c6cba450-d399-11e6-97c7-a1586f41de1d.png)

@strk is this what you get? or is it completely empty?

If there is any UI wizards out there, I would love some input on how to solve this :smile: 

I will try some different approach to make the graph more useful on repos with a lot of branches.

**Comment by strk** [comment]
It just has the lines on my laptop, not the commits.

**Comment by strk** [comment]
Right-click -> ViewImage on the graph results in this (black bars are outside the image):

![screenshot from 2017-01-05 23-23-31](https://cloud.githubusercontent.com/assets/289678/21699907/0f734132-d39e-11e6-96a3-69bf8d39d6b0.png)

**Comment by kjellkvinge** [comment]
which browser is this?

**Comment by bkcsoft** [comment]
So the image is too wide, maybe we should use full-width container? as there's a lot of dead-space to use on a 1920x1080-screen (see image)

![2017-01-06-024824_1916x1036_scrot](https://cloud.githubusercontent.com/assets/4726179/21704582/ad75f8a4-d3ba-11e6-8257-f97447c8aba9.png)

**Comment by bkcsoft** [comment]
Just doing something like this could work:

![2017-01-06-025456_1916x1036_scrot](https://cloud.githubusercontent.com/assets/4726179/21704747/8a9ce954-d3bb-11e6-9619-a7e6d4e48b6a.png)

**Comment by strk** [comment]
On Thu, Jan 05, 2017 at 02:35:34PM -0800, Kjell Kvinge wrote:
> which browser is this?

Firefox 50.1.0+build2-0ubuntu0.16.04.1

**Comment by Bwko** [comment]
This got fixed by #608
