### ISSUE TITLE
UI button clarification

### ISSUE THREAD

**Issue by abulfatmasimov** [go-gitea/gitea#5993]
- Gitea version (or commit ref): 1.7.1
- Git version: 2.18.1
- Operating system: Linux
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

Can you please clarify what is this PR shortcut button for? Users complain that they get 404 when trying to create PR using this button. From the code, it looks like this button is only designed for PR from user's forked repository, but I could not find any description for this in the documentation.

## Screenshots

<img width="1149" alt="screen shot 2019-02-07 at 12 42 24" src="https://user-images.githubusercontent.com/43572996/52412491-d4055d00-2ad6-11e9-99f8-3e57bf33ccde.png">

**Comment by jolheiser** [comment]
Yes, that shortcut is for making PRs from a user's fork. From what I can tell, the button works the same whether clicked on the upstream repo or the forked repo.  
Users will currently get a 404 if they click it and *do not* have a fork.  
  
[This PR](https://github.com/go-gitea/gitea/pull/5929) should at least partially fix the issue.

**Comment by silverwind** [comment]
GitHub had at some point in time a very similar green button, but they have since renamed it to "New Pull Request" and removed the green coloring. I think we should follow suit.

**Comment by jolheiser** [comment]
> GitHub had at some point in time a very similar green button, but they have since renamed it to "New Pull Request" and removed the green coloring. I think we should follow suit.

That is part of the planned list of UI updates in my PR #5980

**Comment by abulfatmasimov** [comment]
IMHO, that button should be made inactive if does not meet those conditions (no fork, no upstream repo). This will make it better from UX perspective.

**Comment by jolheiser** [comment]
GitHub's default action is to open a [blank](http://prntscr.com/mi0xpf) PR page, for reference.

**Comment by abulfatmasimov** [comment]
Yes, this is exactly what majority of users would expect.

**Comment by techknowlogick** [comment]
Closed per linked PR.
