### ISSUE TITLE
Integration with YouTrack

### ISSUE THREAD

**Issue by visteras** [go-gitea/gitea#5999]
- Gitea version (or commit ref): 6ad834e 
- Git version: 2.18.1
- Operating system: Docker Package
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:
Not relevant
## Description

I can integrate Gitea with YouTrack from JetBrains? 
I can add new VCS server(with other url) in settings on YT, but i need set type of server: GitHub or GitLab... how i think if Gitea will be react as GitHub or GitLab this can worked? It would be useful... when YouTrack is really cool task manager, but without integration from gitea i need used other solutions(

**Comment by kolaente** [comment]
AFAIK this is nothing we can do. That's something the people over at Jetbrains need to implement.

Or is that only some kind of plugin someone would have to build for YouTrack?

**Comment by visteras** [comment]
I found REST api for YT: https://www.jetbrains.com/help/youtrack/standalone/youtrack-rest-api-reference.html
Will this improve the situation?
P.S. Since for small teams, YouTrack is completely free, and it’s convenient to settings up, I think integration with it will be interesting enough for many.

**Comment by lafriks** [comment]
I don't think this API can be used for VCS integration in YouTrack so there is not much we can do. Gitea support must be created in YouTrack internally. Please reopen if I'm wrong

**Comment by visteras** [comment]
Why? This API can be used for any app, this API used in other JetBrains products for integrations.

**Comment by lafriks** [comment]
YouTrack REST API lets you perform programmatically various actions in the tracker:

* Importing issues from your current bug tracking system — for smoother migration to YouTrack.

* Creating, modifying, and performing other operations programmatically — so you can seamlessly integrate YouTrack into your environment. For example, via automated issue submission from third-party applications.

* Manipulating projects, users, groups, roles, issue link types, and custom attributes.

**Comment by lafriks** [comment]
I don't see how anything above relates to Gitea or VCS but feel free to reopen with more detailed description on how Gitea could be integrated

**Comment by xf-** [comment]
https://blog.jetbrains.com/youtrack/2019/07/whats-next-youtrack-roadmap-2019-q3-q4/
Gogs is planed - maybe drop a comment in the youtrack ticket.

**Comment by nafigator** [comment]
Minimal integration with youtrack on gitea side can include:
1. Ability to configure URL to youtrack.
2. Resolve task number in commit to http-link.
For example conventional commit:
```bash
feat: Implement cool feature

AWRD-234
```
must be exposed to http-link:
```bash
feat: Implement cool feature

<a href="<configured URL/issue/AWRD-234>">AWRD-234</a>
```
3. Same thing for branches in pull requests. If branch contains issue number it must be exposed to youtrack link.
