### ISSUE TITLE
Delete Current Avatar sets avatar to gravatar icon

### ISSUE THREAD

**Issue by strk** [go-gitea/gitea#600]
- Gitea version (or commit ref): 79d527195d98d74867a067ce93a4dace2b86d2bb (1.1.0-dev)
- Can you reproduce the bug at https://try.gitea.io:
  Yes

I've no idea why but hitting "Delete Current Avatar" button in an organization
page turns the avatar into a Gravatar logo. Hitting "Update Avatar Setting"
after that gives a new random avatar (which doesn't happen again upon hitting
"Update Avatar Setting" again).

**Comment by bkcsoft** [comment]
AFAIK Organizations shouldn't even hit Gravatar 😕

**Comment by glothriel** [comment]
Well. The same function is invoked when user deletes avatar. Organizations in gitea/gogs are in fact User instances.

**Comment by lunny** [comment]
move this to v1.2 since no PR to fix this.

**Comment by elvarb** [comment]
Also means that if you import users from ldap when gravatar is enabled and then disable gravatar the default user avatar will become the avatar generator instead of whatever default avatar you have.

**Comment by elvarb** [comment]
Deleting the ldap user and resyncing just means you get the random avatar again instead of the default avatar.

**Comment by elvarb** [comment]
There is no way to have the default avatar show up for all users, its either default gravatar logo or the random avatar generator. Few options I see

* Setting to disable random avatar generator, fall back to default avatar png
* Setting to use any avatar generator, for example http://avatars.adorable.io/
