### ISSUE TITLE
Create Admin CLI for listing users

### ISSUE THREAD

**Issue by randyesq** [go-gitea/gitea#6001]
- Gitea version (or commit ref): 1.7.1
- Git version: 2.18.1
- Operating system: gitea docker image (alpine)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
I would like to be able to create the first (admin) user without the Web UI. After starting up gitea with `gitea web`, I would like to be able to use the admin CLI to create a user. However, since I am running in a container that may be restarted at any time, it would be best to have a way to check if a user is already created before attempting to create it.

Right now, you can just do `gitea admin create-user ...` and if the return code is 0, it was created. If it is 1, then the user _may_ exist, or something else may have gone wrong. It would be better to be able to have a command that lists users instead of having to try and create it to see if it already exists.
...

**Comment by adelowo** [comment]
So I am thinking something like `admin list` with flags like `--name "oops"` ( to use as a query to search for related users). But how would this deal with pagination if say 200 users exist, looks like a whole lot of data to fit in at once.

**Comment by jolheiser** [comment]
Resolved by https://github.com/go-gitea/gitea/pull/10492
