### ISSUE TITLE
[feature proposal] Local time zone in timestamps

### ISSUE THREAD

**Issue by oscarlofwenhamn** [go-gitea/gitea#6004]
- Gitea version (or commit ref): 1.7.1
- Git version: n/a
- Operating system: RHEL 7.5
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist: n/a

## Description

As a user, I would like to (at least have the option to) see timestamps presented in my local timezone. As several users can be located in different time zones, it would be a better experience to see timestamps presented in a way that corresponds to the local time. 

My local solution to this is a short script that adjusts the stamp using the js Date-function placed in the footer:
```javascript
window.onload=function(){
    var times = document.getElementsByClassName("time-since");
    for (var i = 0; i<times.length; i++){
		var localTime = new Date(times[i].getAttribute("data-content"));
		if(localTime != "Invalid Date"){
			times[i].setAttribute("data-content", localTime.toString());
		}
    }
}
```
though as I am not very experienced in javascript, a better solution is probably possible. Regardless of implementation, this is my proposal.

## Screenshots
Current
![image](https://user-images.githubusercontent.com/44643697/52482828-9c6be300-2bb2-11e9-8701-88d5f12944f6.png)

Proposed 
![image](https://user-images.githubusercontent.com/44643697/52482959-ed7bd700-2bb2-11e9-87ed-3630e891e6ed.png)

**Comment by oscarlofwenhamn** [comment]
In order to get rid of the "(Central European Standard Time)", i added a regex replace, ending up with 
```javascript
localTime.toString().replace(/ *\([^)]*\) */g, "")
```
which brings it all down to a more similar ui size as the original.

**Comment by NateScarlet** [comment]
Good work
Maybe you should use `localTime.toLocaleString`
This function give a translated result
![image](https://user-images.githubusercontent.com/21083014/54326457-5f778e00-4641-11e9-9258-fef80e821411.png)

**Comment by NateScarlet** [comment]
A userscript to use with current version:

```js
// ==UserScript==
// @name     Gitea local time
// @version  1
// @run-at   document-end
// @include  *
// ==/UserScript==

(function() {
  /**
   * @type {HTMLMetaElement}
   */
  const meta = document.querySelector('meta[name=keywords]');
  if (!(meta && meta.content.split(',').includes('gitea'))) {
    return;
  }
  /**
   * @type {NodeListOf<HTMLSpanElement>}
   */
  const times = document.querySelectorAll('span.time-since.poping.up');
  for (const i of times) {
    const localTime = new Date(i.dataset.content);
    if (isNaN(localTime)) {
      continue;
    }
    i.dataset.content = localTime.toLocaleString();
  }
})();
```

**Comment by lunny** [comment]
@NateScarlet could you send a PR to fix that?

**Comment by oscarlofwenhamn** [comment]
Brilliant, nice addition @NateScarlet. And thanks for the help with a PR, I haven't been sure enough of my solution and the workflow to make one.
