### ISSUE TITLE
Add custom headers to emails

### ISSUE THREAD

**Issue by jcabillot** [go-gitea/gitea#6008]
- Gitea version (or commit ref): 1.7.1
- Git version: n/a
- Operating system: docker gitea/gitea:1.7.1
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x ] Not relevant
- Log gist: n/a

## Description

I would like to be able to filter emails from Gitea with my mail client (Thunderbird but it's not revelant).
Currently it's not possible for me because the sender used in my configuration is shared with another services and the subject for PR look likes [project] <issue title> <id> (no mention of Gitea).
What would be great is to be able to specify a custom header.

Is that something Gitea can implement ?

**Comment by zeripath** [comment]
You can edit the templates that are used to make the emails. I think if you copy templates/email to custom/templates/email and change them there and restart Gitea that should do it.

**Comment by zeripath** [comment]
@jcabillot does that solve your issue?

**Comment by markusamshove** [comment]
I've created new templates in e.g. `custom/templates/mail/issue/comment.tmpl` but the mails don't change.

I'm using sendmail

**Comment by jcabillot** [comment]
Hmm I think I can work with that, thanks.
