### ISSUE TITLE
SSH_LISTEN_PORT config directive

### ISSUE THREAD

**Issue by sztanpet** [go-gitea/gitea#603]
I wanted to enable the built-in SSH server, but it was listening on port 0.
The directive to set the ssh listen port is not documented on https://docs.gitea.io/en-us/config-cheat-sheet/
I think it should default to the value of SSH_PORT if unset.
Not sure if this should be two issues or not (setting the default value and documenting the option).

**Comment by lunny** [comment]
`SSH_PORT` is will be shown in UI, `SSH_LISTEN_PORT` is the really listen port.
