### ISSUE TITLE
Error when upgrading from 1.5.3 pq: column "id" of relation "issue_dependency" already exists

### ISSUE THREAD

**Issue by rawbertp** [go-gitea/gitea#6036]
- Gitea version (or commit ref): 1.5.3
- Git version: 2.17.1
- Operating system: Ubuntu 18.04.2
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:
```
2019/02/11 14:40:53 [I] Migration: add issue_dependencies
2019/02/11 14:40:53 [...itea/routers/init.go:61 GlobalInit()] [E] Failed to initialize ORM engine: migrate: do migrate: Error creating issue_dependency_table column definition: pq: column "id" of relation "issue_dependency" already exists
```

## Description
When upgrading from 1.5.3 to 1.6.4 or 1.7.1 I'm getting the abovementioned error.
I tried dropping the "issue_dependency" table but this doesn't help.

```
gitea=# select * from version;
 id | version 
----+---------
  1 |      70
```

**Comment by rawbertp** [comment]
Any ideas, anyone...?

**Comment by zeripath** [comment]
Ok so you're having trouble in this migration file https://github.com/go-gitea/gitea/blob/master/models/migrations/v70.go

I suspect that although you say you have dropped the table you haven't removed the primary key index. You need to drop that aswell. Then the migration should run.

**Comment by rawbertp** [comment]
Thanks for your advice, but it still doesn't work. I do not get why it complains about an already existing column, even though the corresponding table has been dropped before?!

```
gitea=# select * from pg_indexes where tablename = 'issue_dependency';
 schemaname |    tablename     |       indexname       | tablespace |                                       indexdef
------------+------------------+-----------------------+------------+--------------------------------------------------------------------------------------
 gitea      | issue_dependency | issue_dependency_pkey |            | CREATE UNIQUE INDEX issue_dependency_pkey ON gitea.issue_dependency USING btree (id)
(1 row)

gitea=# alter table issue_dependency drop constraint issue_dependency_pkey;
ALTER TABLE
gitea=# select * from pg_indexes where tablename = 'issue_dependency';
 schemaname | tablename | indexname | tablespace | indexdef
------------+-----------+-----------+------------+----------
(0 rows)

gitea=# drop table issue_dependency;
DROP TABLE
```

**Comment by zeripath** [comment]
`DROP INDEX issue_dependency_pkey`

**Comment by rawbertp** [comment]
Sorry, but that doesn't work...

```
gitea=# drop index issue_dependency_pkey;
ERROR:  cannot drop index issue_dependency_pkey because constraint issue_dependency_pkey on table issue_dependency requires it
HINT:  You can drop constraint issue_dependency_pkey on table issue_dependency instead.
gitea=# alter table issue_dependency drop constraint issue_dependency_pkey;
ALTER TABLE
gitea=# drop index issue_dependency_pkey;
ERROR:  index "issue_dependency_pkey" does not exist
gitea=# drop table issue_dependency;
DROP TABLE
```

**Comment by zeripath** [comment]
Try dropping the index after the table has been dropped...

**Comment by rawbertp** [comment]
```
gitea=# drop table issue_dependency;
DROP TABLE

gitea=# DROP INDEX issue_dependency_pkey;
ERROR:  index "issue_dependency_pkey" does not exist
```

**Comment by zeripath** [comment]
*sigh*

Right so it appears that somehow you're ending up with the dependency table being created earlier than migration v70 is expecting.

There are two options:

* Can you build a gitea? If so you could hack around sections of https://github.com/go-gitea/gitea/blob/master/models/migrations/v70.go removing the issue dependency table section.

That is to be completely explict remove lines: https://github.com/go-gitea/gitea/blob/6cb127d4973da26e351605ebeac0717aed036177/models/migrations/v70.go#L18-L31

* A slightly easier but probably less optimal option is just to set the version marker in your database to 70.

```sql
UPDATE version SET version = '70';
```

(I think that's the right SQL)
