### ISSUE TITLE
Enable mail template customization

### ISSUE THREAD

**Issue by kolaente** [go-gitea/gitea#6037]
It currently is not possible to customize email templates by using the [customize system](https://docs.gitea.io/en-us/customizing-gitea/). I looked in the code, it seems like Gitea does not look for customized templates.

Relevant bit (among others): `models/mail.go:167`

**Comment by FalconWu2017** [comment]
The current mail template is too low, and I would like to customize it too.

**Comment by zeripath** [comment]
I think it actually does look for customisable templates.

**Comment by lunny** [comment]
I think @zeripath is right. I haven't test it, but see https://github.com/go-gitea/gitea/blob/master/modules/templates/static.go#L174 . Customize mail template should be OK.

**Comment by small75** [comment]
the mechanism of customization works
