### ISSUE TITLE
Pullrequest dependencies are disabled when internal issue tracker is disabled

### ISSUE THREAD

**Issue by markusamshove** [go-gitea/gitea#6039]
- Gitea version (or commit ref): master

## Description

When selecting an external issue tracker in the repository settings (see 1st screenshot), it is no longer possible to add dependencies between pull requests.

In our current workflow, we do use an external issue tracker for all of our repositories.

However, we're leveraging PRs and would love to be able to have dependencies between PRs (which does work when internal issue tracker is enabled).

## Screenshots

![grafik](https://user-images.githubusercontent.com/2401875/52583765-b61a5e00-2e30-11e9-9118-fdc6708b3677.png)

**Comment by markusamshove** [comment]
I tried to have a go on this, but I'm kinda lost on how to implement this.

My first try was to pull out the option from ` Enable Repository Issue Tracker` as an additional option, which can be enabled when either PRs or Issues are enabled.

However, the name `issue dependencies`  and the option `EnableDependencies`  in `IssueConfig` wouldn't make sense anymore.
Also, the DB table seems to be `issue_dependencies`, so when trying to do it clean I have to change the database, translation keys etc..

Is there another approach I could to?
Is an additional option in for pull request config, to have 2 options, a better idea?

I think this needs a bit of design thought from the Gitea side, as this would be my first PR and got kinda huge :-)

**Comment by MarkusAmshove** [comment]
Still relevant  :-)

**Comment by 6543** [comment]
@bhalbright you are mor familiar with this code ...
