### ISSUE TITLE
Remove time - subtract time - delete time commit

### ISSUE THREAD

**Issue by a7hybnj2** [go-gitea/gitea#6042]
- Git version: 1.5.2

add ability to manage time in 'issues'.

If you accidentally add an incorrect time or forget to stop a timer and hit stop instead of cancel then your stuck with a ridiculous time log.

an easy way to make a quick fix would be to allow entering negative numbers via "add time" then the record of the error exists and it can just be commented.

*I was under the impression that I saw a similar issue about a year ago but I could not find it.*

**Comment by a7hybnj2** [comment]
This would still be awesome if implemented. I haven't messed it up recently but when I do I have to recreate the whole issue with correct times.

**Comment by a7hybnj2** [comment]
I just messed up my timer again. I am glad I hit end time instead of cancel though because the text that reads something like "timer started ___ ago" was only saying 1 hour and I refreshed and still only reading 1 hour.

When I hit "stop" it read 1:24 so I would have lost 24 mins of issue tracking...

Anyway I would be fine if the

```
if time < 0 than complain
```
was removed and you could just add negative minutes...

**Comment by no-go** [comment]
Hi @a7hybnj2,

take a look to `https://docs.gitea.io/en-us/api-usage/` the swagger API (create a token). There is a `/repos/{owner}/{repo}/issues/{index}/times` to "GET" all tracked times (and its index) of an issue. The "DELETE" version `/repos/{owner}/{repo}/issues/{index}/times/{id}` adds a negative time to "delete" the tracked time entry. Maybe this is a "non gui" workaround for you.

For example `curl -X DELETE "http://localhost:3000/api/v1/repos/meister/test/issues/2/times/5?token=a5db9..........ssssLongTokenxxx" -H  "accept: application/json"` deletes/substract in user meister, repo test, issue 2 the 5th comment entry (= it was a stop event of the time tracker).

**Comment by noerw** [comment]
duplicate, closing in favor of #2642
