### ISSUE TITLE
PR inline comments don't fire webhook at creation - but do fire when comment edited

### ISSUE THREAD

**Issue by shatterstone** [go-gitea/gitea#6051]
- Gitea version (or commit ref):1.6.1, 1.7.1
- Git version:
- Operating system: linux docker
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes (provide example URL) https://try.gitea.io/cyclop5/test/pulls/1/files
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
With a webhook set to fire on all events, if someone enters an inline code comment, the webhook will not fire. However, if someone later *edits* that same comment, the webhook will fire.  (screenshot shows where the comments are entered at. ) 

To reproduce:

create a webhook that will fire for all events.
create a PR
go to the files changed tab, and enter a comment/review inline.

Expected behavior: webhook will fire
(webhook is not actually firing)

 
![screen shot 2019-02-12 at 3 28 43 pm](https://user-images.githubusercontent.com/24799480/52669188-1239bc80-2edb-11e9-81bd-1ef3319f5f68.png)

...

**Comment by davidsvantesson** [comment]
On the edit of review comment, you actually get a "issue comment" webhook, because code is shared with issues and there is no check if it is a pull request or issue. So there is actually two issues.
Why there is no webhook in the first case I don't know.

**Comment by lunny** [comment]
I think this has been resolved. Please feel free to reopen it.
