### ISSUE TITLE
Better 404s

### ISSUE THREAD

**Issue by Larivact** [go-gitea/gitea#6052]
- Gitea version (or commit ref): 7f38e2d
- reproducible at https://try.gitea.io/

## Description
* [ ] UI 404 pages should say something below the 404 image and ideally provide a search box (compare https://try.gitea.io/-404 and https://github.com/404). While using title case in the title is consistent, "Page Not Found" strikes me as odd.
* [x] API 404s currently just return an entirely empty 404 response. Some message and a link to the API documentation would be nice (compare https://try.gitea.io/api/v1/404 and https://api.github.com/notfound).

**Comment by jolheiser** [comment]
For a search box, what would be different from clicking on the "Explore" tab from the 404 page other than saving 1 click? (Not bashing on click saving, it's important from a UI standpoint of course)

**Comment by lunny** [comment]
This has been fixed by #6077
