### ISSUE TITLE
Automatically add labels to repositories on creation 

### ISSUE THREAD

**Issue by adelowo** [go-gitea/gitea#6055]
- Gitea version (or commit ref): 7f38e2d0dedfc3e04994272196cda53e4ad20354
- Git version: git version 2.17.2 (Apple Git-113)
- Operating system: MacOS
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

I expect to be able to create a repo, file issues and add labels immediately. 
Currently, I have to manually enable a label set individually created for every 
single repository.

**Comment by jolheiser** [comment]
Are you thinking just add that to the repo creation form, or did you have something else in mind?  
  
If you're not working on this I wouldn't mind doing it. This is definitely something I've thought about when creating a repo before.

**Comment by adelowo** [comment]
I was actually thinking of a config. But it seems too trivial for a config value, your suggestion for it
being added to the repo creation form is way better.

I am not working on this so you can pick this one up

**Comment by markusamshove** [comment]
When clicking on labels for the first time, there is a Default set suggested to add.
Maybe we could make several sets for an organization and have a choice when creating a repository (and where the default set is suggested now) ? 

That way an organization can create multiple sets which I can chose from

**Comment by adelowo** [comment]
I think it is fine Gitea provides only the ___Default___ label.

You can already create multiple sets, just add your new label set to the ___options/label___ directory

**Comment by markusamshove** [comment]
Ah I see. Was wondering how to add new sets  :-)

**Comment by troygeiger** [comment]
Could you have it as a user or organization option?
