### ISSUE TITLE
api request for issue always returns nil for milestone

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#6056]
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes (provide example URL)

example url: https://try.gitea.io/api/v1/repos/nexustrap/issue_missing_milestone_api_v1/issues/1?access_token=dc52cb4688603549d465e10ffa0b371b05489ada

## Description

Create an repository, issue and milestone on try.gitea.io.
Assign the milestone to the newly created issue.

curl -X GET "https://try.gitea.io/api/v1/repos/nexustrap/issue_missing_milestone_api_v1/issues/1?access_token=dc52cb4688603549d465e10ffa0b371b05489ada" -H "accept: application/json"

The resulting json shows milestone = 'nil'

## Screenshots

![bildschirmfoto vom 2019-02-13 13-44-33](https://user-images.githubusercontent.com/5076310/52712666-96507a80-2f95-11e9-85ff-b5d65456d5ba.png)

**Comment by sankethpb** [comment]
@lafriks Is there any workaround for this in 1.7.2?
Would be great to have it back ported to 1.7.3, thank you.
