### ISSUE TITLE
Line wrapping in the newest version

### ISSUE THREAD

**Issue by theAkito** [go-gitea/gitea#6064]
- Gitea version (or commit ref): 7a72aa623e9640907fb6dd65e86c62d29b981b62
- Git version: 2.11.0
- Operating system: DietPi v6.21.1
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
I just updated from 0b510725c to 7a72aa623e9640907fb6dd65e86c62d29b981b62 . I noticed that files now always include line breaking/wrapping and I didn't find a way to turn it off. I assume this is a new "feature", as this is also confirmed on try.gitea.io.

Another issue is, that in a file I have the line numberings suddenly stop at a certain point. It just happens in this specific file and I can't reproduce this on try.gitea.io with random input. Didn't try the original input, as the file has confidential data in it.

## Screenshots

![2019-02-14 00_47_17-gitea-error1](https://user-images.githubusercontent.com/26848976/52752215-54095680-2ff2-11e9-986f-4c33560697d9.png)

**Comment by oscarlofwenhamn** [comment]
Do you have a link to the example on try.gitea.io, to illustrate the issue?

**Comment by lafriks** [comment]
Example: https://try.gitea.io/Etzelia/plural/src/branch/master/plural-gen/ordinals.xml.go

**Comment by oscarlofwenhamn** [comment]
It also looks like this is suffering from the same issue with highlighting as I brought up here #6057.

**Comment by theAkito** [comment]
@lafriks @oscarlofwenhamn Thank you for the attention to this bug. I hope this can be resolved effectively.

**Comment by silverwind** [comment]
This is related to wrapping introduced in https://github.com/go-gitea/gitea/pull/5927. We need to change how line numbers are generated, ideally using CSS counters and `::before`. I will have a look a bit later.

**Comment by theAkito** [comment]
> 
> 
> This is related to wrapping introduced in #5927. We need to change how line numbers are generated, ideally using CSS counters and `::before`. I will have a look a bit later.

Well, so this mess is actually a feature... I need this solved ASAP, or I have to stay on a previous version of Gitea, because this is a really terrible mess, I can't really focus on doing my work due to this.

Or I have to remove e5cd80e0219f10818f43e8cab6b9c814cb1cd796 manually...

**Comment by silverwind** [comment]
I'm happy if collaborators agree to reverting https://github.com/go-gitea/gitea/pull/5927 as I'm not sure when I get around to a proper fix which will take some time.

**Comment by theAkito** [comment]
Thanks for a quick resolution. 👍

**Comment by oscarlofwenhamn** [comment]
FTR: The highlighting still looks to be broken even after this PR.

**Comment by silverwind** [comment]
https://github.com/go-gitea/gitea/issues/6057 is a different issue, certainly not related here.
