### ISSUE TITLE
Hard-coded copyright line from 0BSD license

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#6065]
#5558 updates 1.7.0 to add proper spacing to the license files from the spdx license list upstream. However, I noticed the license/copying file for 0BSD includes the copyright line with a hard-coded name in the license text. I think this copyright line needs to be removed as per [the spirit](https://landley.net/toybox/license.html) of 0BSD and fact modern source control systems are capable of tracing this sort of thing easily back to an author (read: Black Duck).

I'm opening this issue as a reference/justification for updating SPDX license list to update the license text.

**Comment by techknowlogick** [comment]
Closing as duplicate of #5397

**Comment by ghost** [comment]
@techknowlogick thanks sorry I never thought in a trillion years someone else wouldn't of duped this—I didn't even check.
