### ISSUE TITLE
[API] Deleting an unexisting repo returns undocumented response

### ISSUE THREAD

**Issue by bogdanpetrea** [go-gitea/gitea#6069]
- Gitea version (or commit ref): 7a72aa6
- Git version: whatever is on try.gitea.io
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes, actually the only place I tried

## Description
When trying to delete a repository that doesn't exist, the API returns an undocumented error code (prob 500) and an error message, when [it could just as well return a successful response](https://stackoverflow.com/questions/6439416/deleting-a-resource-using-http-delete#comment33002038_6440374).

Tested via [Swagger](https://try.gitea.io/api/swagger#/repository/repoDelete):
```sh
curl -X DELETE "http://try.gitea.io/api/v1/repos/bogdan/doesntexist" -H  "accept: application/json"
```
Code | Details
-- | --
Undocumented | TypeError: NetworkError when attempting to fetch resource.

This might also apply to other resources.

**Comment by lafriks** [comment]
It should return 404 imho

**Comment by bogdanpetrea** [comment]
After checking again on a local instance it seems 404 is indeed returned, but there's a problem with [https://try.gitea.io](try.gitea.io)'s Swagger. I get the `NetworkError` for everything I try.
