### ISSUE TITLE
Push to mirror possible?

### ISSUE THREAD

**Issue by HaasJona** [go-gitea/gitea#6071]
- Gitea version (or commit ref): 1.7.1
- Git version: 2.20.1
- Operating system: Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

Pushing to mirror is currently impossible as there is a check in https://github.com/go-gitea/gitea/blob/01c10a951b9db0b9f020ef657ca71eb5e5882a84/cmd/serv.go#L214.

Is this a hard technical limitation or is it only forbidden because it is slightly dangerous? Do you think this can be enabled?

Usecase: Create a up-to-date mirror of the official source code repository, but push experimental/internal features into a private and mirroring gitea instance first, which is also used by CI runners and so on.

Branches like master would always be up-to-date with upsteam because of the mirroring and would be protected by local pushes, while you could push feature-branches that are not upstream.

**Comment by HaasJona** [comment]
Sorry, this is a duplicate of #6054

**Comment by HaasJona** [comment]
I've commented out these checks locally and it seems to work fine.

**Comment by lunny** [comment]
duplicated with #2280
