### ISSUE TITLE
README.md not working with Git LFS

### ISSUE THREAD

**Issue by qmnl** [go-gitea/gitea#6073]
- Gitea version (or commit ref): 353282e
- Git version: 2.20.1
- Operating system: Linux with Docker
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

When creating a `README.md` file and tracking it with Git LFS, it will be displayed in the wrong way. When individually clicking the `README.md` and downloading it (View raw), the right content gets downloaded.

## Screenshots

![s](https://user-images.githubusercontent.com/16321843/52808772-fc6cf880-308e-11e9-9f62-def5ef9c9b43.png)

![a](https://user-images.githubusercontent.com/16321843/52808857-32aa7800-308f-11e9-8522-78a5465715d0.png)

**Comment by zeripath** [comment]
Hmm... I can't believe that anyone would place their markdown readme file in LFS - however, I suppose for completeness sake I can adjust this.

Should we be allowing other formats like readme pdf etc?

**Comment by qmnl** [comment]
I tracked my `README.md` with Git LFS by accident (by tracking all files with Git LFS), but if you include Base64 images in the `README.md`, there is a good reason to track the `README.md` with Git LFS.

> Should we be allowing other formats like readme pdf etc?

Not as part of this issue, but generally why not?

**Comment by zeripath** [comment]
It would simplify the code somewhat, we just make the readme section call the view file section with the appropriate information and set the template similarly
