### ISSUE TITLE
502 Bad Gateway after setting config

### ISSUE THREAD

**Issue by jscottelblein** [go-gitea/gitea#6076]
Using the latest Docker image, I can load Gitea as a fresh install, then I have to go into the config section to get it all setup, after doing so and clicking the Save button I get an immediate 502 Bad Gateway upon refresh.

My app.ini after changing the settings looks like this:

```
[server]
APP_DATA_PATH    = /data/gitea
SSH_DOMAIN       = my.domain.name
HTTP_PORT        = 3000
ROOT_URL         = /giteadoc/
DISABLE_SSH      = false
SSH_PORT         = 22
LFS_CONTENT_PATH = /data/git/lfs
DOMAIN           = my.domain.name
LFS_START_SERVER = true
LFS_JWT_SECRET   = C9T0La0v6LOYFRedactedXdCVaPWN4U
OFFLINE_MODE     = false
```

The server section on a fresh install looks like this:

```
[server]
APP_DATA_PATH    = /data/gitea
SSH_DOMAIN       = localhost
HTTP_PORT        = 3000
ROOT_URL         = 
DISABLE_SSH      = false
SSH_PORT         = 22
LFS_CONTENT_PATH = /data/git/lfs
```

When I stop and then start the container, it just repeatedly spams this:

![image](https://user-images.githubusercontent.com/1524526/52822325-fd922b80-3076-11e9-9a43-fe81ad4ee0ee.png)

Any idea what's wrong?

**Comment by techknowlogick** [comment]
Are you able to get more details from the /data/gitea/logs directory in your container?

**Comment by jscottelblein** [comment]
@techknowlogick  It's repeating this over and over:

```
2019/02/15 12:23:52 [I] Log Mode: File(Info)
2019/02/15 12:23:52 [I] XORM Log Mode: File(Info)
2019/02/15 12:23:52 [I] Cache Service Enabled
2019/02/15 12:23:52 [I] Session Service Enabled
2019/02/15 12:23:52 [I] Beginning ORM engine initialization.
2019/02/15 12:23:52 [I] ORM engine initialization attempt #1/10...
2019/02/15 12:23:52 [I] ORM engine initialization successful!
2019/02/15 12:23:52 [I] Git Version: 2.18.1
2019/02/15 12:23:52 [...les/indexer/issue.go:64 InitIssueIndexer()] [E] InitIssuesIndexer: create index, invalid argument
```

**Comment by techknowlogick** [comment]
Ok, so it seems like whats happening is this line is error-ing out: https://github.com/go-gitea/gitea/blob/master/modules/indexer/issue.go#L64

So it seems it is failing to create the issue index. Sadly the error it is giving you is a bit vague.

Would you be able to provide the `indexer` values in your config?

**Comment by jscottelblein** [comment]
Happy to. Here's what's in the app.ini after I've run the setup and run into the problem. Comparing it with the original app.ini that is created on a fresh init, it sees to be the same:

```
[indexer]
ISSUE_INDEXER_PATH = /data/gitea/indexers/issues.bleve
```

And I've confirmed that the path/file does exist on the host.

I'm wondering if maybe there's some issue with the data folder being mounted to the host file system rather than a volume?

Here's the docker run I use to create the Gitea container if it helps at all:

`docker run --name gitea --restart unless-stopped --publish 9023:3000 --env TZ=America/Chicago -d --mount src="/c/Users/My Cloud/AppData/Roaming/DockerConfigs/Gitea/Data",dst=/data,type=bind gitea/gitea:latest `

**Comment by lunny** [comment]
@STaRDoGG which version are u using? could you try to upgrade to the latest version to test it?
