### ISSUE TITLE
New GPG key for @lafriks

### ISSUE THREAD

**Issue by ArchangeGabriel** [go-gitea/gitea#6086]
Latest release is signed by a new GPG key for @lafriks, that was apparently generated today (and not the former one). Any reason why so?

**Comment by nicoulaj** [comment]
Also I think the 1.7.2 tag + binaries were deleted and recreated, received two notifications

**Comment by techknowlogick** [comment]
There was a PR that wasn’t backported to the 1.7.2 release and so @lafriks was able to sort that out. I can confirm this is ok. You can verify yourself that the commit signed is ok, and the binaries are signed by our official gpg key.

**Comment by lafriks** [comment]
@ArchangeGabriel I created new GPG key for use from my work as I had no laptop with me, all is ok :)

**Comment by ArchangeGabriel** [comment]
OK, thanks to both of your for those precisions.
