### ISSUE TITLE
Better presentation for files attached to issues

### ISSUE THREAD

**Issue by ctrlaltca** [go-gitea/gitea#6089]
- Gitea version (or commit ref): 1.7.0
- Git version: 2.14.5
- Operating system: Slackware64 14.2
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant (the demo doesn't allow non-image uploads)
- Log gist:

## Description
Looking at the view rendering issue attachments, it seems that only images have a special handling.
If you attach files of other types (eg. pdf, txt, odt, ..) an icon with a tooltip containing the file name is rendered.
If an issue contains more than one attachment, it's quite hard to look for a specific attachment on desktop, and impossible on mobile without downloading them all.
It would be nice to have at least the file name printed (alone or alongside the icon), or even better to have an icon like the one already used for newly uploaded files

## Screenshots
The screenshot is from an issue containing 2 pdf and 3 odt attachments. There's no way to discriminate between the files:
![schermata 2019-02-15 alle 18 48 09](https://user-images.githubusercontent.com/1631111/52874594-508ce100-3152-11e9-8d94-282305c06d31.png)
The icon used for newly uploaded files is way nicer:
![schermata 2019-02-15 alle 18 49 52](https://user-images.githubusercontent.com/1631111/52874850-0821f300-3153-11e9-94f0-7564daae8a9c.png)

**Comment by silverwind** [comment]
Kind of related: I'd like to see the image preview in the footer removed for image attachments that are already displayed inline.

**Comment by Mikanoshi** [comment]
Also... why is it so huge? :D Changed style to 24px, looks just fine.

**Comment by renevdzee** [comment]
What about making it look the same as release-attachments? like this:

![image](https://user-images.githubusercontent.com/2150703/67303904-6463c080-f4f3-11e9-8b17-3c7004981189.png)

This is what I changed to make it look like this (v1.9.3): [patch.txt](https://github.com/go-gitea/gitea/files/3756814/patch.txt)
I edited the templates in my custom/templates/ folder. I had to add a number of style-keywords because I didn't want to change any stylesheets (I don't know how to do this better in semantic-ui)

(would also fix issue #6501)

**Comment by guillep2k** [comment]
@renevdzee I would _really_ love that. And I've been wishing to hide the pictures already shown in the contents block (but that's more difficult to implement.... perhaps if the HTML parser adds a custom attribute to the `<img>` files? Can that be targeted somehow with CSS rules and match by URL?).

**Comment by guillep2k** [comment]
@renevdzee care to make a PR?

**Comment by lunny** [comment]
closed by #11141
