### ISSUE TITLE
Link to code comment in mails is wrong on single comment

### ISSUE THREAD

**Issue by markusamshove** [go-gitea/gitea#6092]
When leaving just one comment on a pull request, a notification mail gets sent.

However, the single comment doesn't show up in the conversation view of the PR (is this expected for non-review-comments?), which leads to a wrong link.
The correct link for the single comment would have `/files/`  in there to switch to the files view and therefore be able to place the view on the correct comment anchor.

[This](https://github.com/go-gitea/gitea/blob/8c8ac1a16260c075e854bd370812284e0121613e/models/mail.go#L159) seems to be the appropriate place to put the `/files/` into the link depending on the `CommentType`.

I've tried

```
        if comment != nil {
-               data = composeTplData(subject, body, issue.HTMLURL()+"#"+comment.HashTag())
+               if comment.Type == CommentTypeCode {
+                       data = composeTplData(subject, body, issue.HTMLURL()+"/files/#"+comment.HashTag())
+               } else {
+                       data = composeTplData(subject, body, issue.HTMLURL()+"#"+comment.HashTag())
+               }
        } else {
                data = composeTplData(subject, body, issue.HTMLURL())
        }

```

but I'm sadly not able to test it locally, because I'm having a hard time setting up mail in the docker instance.

**Comment by lafriks** [comment]
I think problem is that single comment does not shows up in conversation tab but it should

**Comment by markusamshove** [comment]
Okay, I was wondering if that was the case.
I agree that it should show in the conversations list.

Do we keep this issue or close it in favour of one targeting specific the conversations list?

**Comment by markusamshove** [comment]
Closed in favor of #6110

**Comment by zeripath** [comment]
Markus you should be able to set the mailer to dummy in order to see what would be mailed.

**Comment by markusamshove** [comment]
Thanks, I'll keep that in mind for the future.
For this one, I think lafriks confirmed that it is a bug, so the problem doesn't sit in mailing :-)
