### ISSUE TITLE
Feature Request: Ability to mark Organization as private

### ISSUE THREAD

**Issue by bkraul** [go-gitea/gitea#6093]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
The ability to mark organizations private so that they will not show in the explore section for non-logged in users (if the site allows public viewing) or users that do not belong to the particular organization, would be nice. This is already set at the repository level, but it would be nice to have that option at the organization level.

**Comment by techknowlogick** [comment]
Closed as duplicate. I’m afraid I’m on mobile right now so I can’t find the ticket number, but a PR for this is in 1.8 milestone

**Comment by bkraul** [comment]
Tracked on #714 PR #1763

**Comment by techknowlogick** [comment]
Thanks for linking :)
