### ISSUE TITLE
1.7.2 Build issue - "compress/zlib.a(__.PKGDEF/): unexpected end at 44947, want 4941"

### ISSUE THREAD

**Issue by 4oo4** [go-gitea/gitea#6096]
- Gitea version (or commit ref): 1.7.2
- Golang version: 1.11.5
- Git version: 2.20.1
- Operating system: Ubuntu 16.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:
```
go build -i -v  -tags 'bindata' -ldflags '-s -w -X "main.Version=1.7.2" -X "main.Tags=bindata"' -o gitea
# code.gitea.io/gitea
2019/02/16 11:11:02 /usr/lib/go-1.11/pkg/linux_amd64/compress/zlib.a(__.PKGDEF/): unexpected end at 44947, want 4941
Makefile:266: recipe for target 'gitea' failed
```

## Description
I'm attempting to build gitea from source, using the steps listed here: https://docs.gitea.io/en-us/install-from-source/ , and my build gets stuck at this point, running `make clean` and trying again didn't seem to help. I recently upgraded golang from 1.10 to 1.11 and was able to build 1.7.1 without any issues.

Cheers

**Comment by lafriks** [comment]
Seems like problem with GoLang installation

**Comment by 4oo4** [comment]
@lafriks Yeah I figured, definitely not gitea since another golang project fails to build now. Did a few test builds after upgrading to the new golang version, not sure what happened in between then and now.

**EDIT:** I think the most recent package version released on 2/11/19 is what broke it, I was originally installing go from this repo: https://launchpad.net/~gophers/+archive/ubuntu/archive, but when I install go 1.11.5 from here (https://launchpad.net/~longsleep/+archive/ubuntu/golang-backports) it fixed the build for this as well as the other go project I was trying to build before. I sent an email to the package maintainer to have them look into it.
