### ISSUE TITLE
Single comments aren't shown in conversation list

### ISSUE THREAD

**Issue by markusamshove** [go-gitea/gitea#6110]
- Gitea version (or commit ref): master
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant

[Link to try.gitea.io](https://try.gitea.io/singlecomment/singlecomment/pulls/1)

## Description

I've added a [single comment](https://try.gitea.io/singlecomment/singlecomment/pulls/1/files#issuecomment-10122) to the PR, which is not shown in the [conversation list](https://try.gitea.io/singlecomment/singlecomment/pulls/1).

**Comment by markusamshove** [comment]
I've found that the template is missing stuff for comment type 21 [here](https://github.com/go-gitea/gitea/blob/master/templates/repo/issue/view_content/comments.tmpl#L274).

However, I don't seem to be able to navigate to single comments within the template, as they're saved within the diff.
But I can't figure out how to get to `Diff` from `Comment`

**Comment by mrsdizzie** [comment]
Should be fixed as linked example now works
