### ISSUE TITLE
Shields-like service for Gitea Repos

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#6114]
- Gitea version (or commit ref): 1.7.1
- Git version: Any
- Operating system: Any
- Database (use `[x]`):
  - [x] PostgreSQL
  - [x] MySQL
  - [x] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist: n/a

## Description

Many, many, many repos use shields.io to perform useful tasks such as using JSONPath to grab peer dependencies, report on licenses and provide links to chatrooms. However, Shields uses CloudFlare which places a `__cfduid` cookie on visitors' `README` files thereby hurting privacy rights afforded to EU persons under GDPR. Please help us with privacy and stand apart from GitHub et al. in adding a feature which allows users to create their own shields and host them on the IndieWeb.

## Screenshots

N/A

**Comment by ghost** [comment]
Note shields may be adjusting course: https://github.com/badges/shields/issues/3026

**Comment by techknowlogick** [comment]
Thank you for your suggestion. Closing this as won't fix as shields is a giant project in itself, and would take away from the core project.

Edit: you can also self-host it if you are concerned re: privacy https://github.com/badges/shields/blob/master/doc/self-hosting.md

**Comment by ghost** [comment]
Fair enough. It was worth a shot. I don't think it'll take anything quite so complex to land a feature covering 80–90% of user needs. So I hope there is some reconsideration of this in the future.
