### ISSUE TITLE
No Repository / Organization menu in IE 11

### ISSUE THREAD

**Issue by JimauveLaGuimauve** [go-gitea/gitea#6116]
- Gitea version (or commit ref): **Gitea Version: 1.7.0**
- Git version: **Not relevant** *(git version 1.8.3.1)*
- Operating system: **Linux CentOS 7.4 (1708) on server** and **Win 10 on client side**
- Database:
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL) : On the dashboard : https://try.gitea.io/ 
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

Hello all, 

We have a little problem with the **navigation menu** in the dashboard on IE 11 . (But it work perfectly on Chrome). The compagny where I work want us to deal with IE. So we can't really use GiTea for this issue.
The issue is also present on try.gitea.io

There is a problem with the heat map too, but we have disconnected it with 
`ENABLE_USER_HEATMAP=FALSE`
in the conf file.

I don't think it could come from the compagny proxy because it work on chrome.

## Screenshots
Here is a few screen shot : 
On our server : 
![onourserver](https://user-images.githubusercontent.com/10958872/53002328-c764fb00-342c-11e9-84ef-411542398d6d.PNG)

On Try Git Tea : 
![trygitea](https://user-images.githubusercontent.com/10958872/53002344-cf249f80-342c-11e9-8e8d-93c1688886eb.PNG)

And the version of Internet explorer 11 we are using : 
![aboutie](https://user-images.githubusercontent.com/10958872/53002393-e5326000-342c-11e9-8e6a-cb12fe509ebb.PNG)

Thank :)

**Comment by JimauveLaGuimauve** [comment]
Just to be sure this is what I expect to get with IE
![image](https://user-images.githubusercontent.com/10958872/53002671-84efee00-342d-11e9-9842-1cf2801858ea.png)

**Comment by lunny** [comment]
Should we still support IE 11?

**Comment by djpbessems** [comment]
Internet Explorer 11 is still integrated in Windows Server 2016, which will be end of life 1/11/2022; before then, it is not unexpected to still receive a larger amount of visitors using that browser (think of citrix-sessions where developer teams work on their code).

**Comment by techknowlogick** [comment]
Sadly, I too am required to use IE11 in some situations as well.

**Comment by lafriks** [comment]
I have fixed heatmap to work on IE11 but I have no idea why repo menu is not visible in IE11 as there are even no errors to begin with

**Comment by lafriks** [comment]
Updating vuejs to latest version fixes also repo menu 🎉

**Comment by JimauveLaGuimauve** [comment]
Thank Lafriks for the fix :)
