### ISSUE TITLE
Site footer isn't fixed on commits graph page

### ISSUE THREAD

**Issue by pavelxdd** [go-gitea/gitea#6118]
- Gitea version: master
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant

## Description

Open https://try.gitea.io/swoldemi/NervBot/graph and scroll down the page. The site footer scrolls with page content.

## Screenshots

https://imgur.com/7aj2xdL

**Comment by silverwind** [comment]
Unsure if this is related to my lastest footer changes, but I'll take it as a good opportunity to switch `body` to a vertical flexbox layout. Should have a PR for this soon.

**Comment by sms-system** [comment]
This is because element with id `git-graph-container` has the attribute `float: left;` and this breaks the flow.

`display: flow-root;` on parent element `.ui.container` will solve this problem.
