### ISSUE TITLE
Upgrading from Gogs - unknown database type mssql

### ISSUE THREAD

**Issue by LukeMauldin** [go-gitea/gitea#6124]
- Gitea version (or commit ref): 1.0.2
- Git version: 2.17.1
- Operating system: Ubuntu
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [X] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:
2019/02/19 11:35:16 [I] Log Mode: File(Trace)
2019/02/19 11:35:16 [I] Cache Service Enabled
2019/02/19 11:35:16 [I] Session Service Enabled
2019/02/19 11:35:16 [...itea/routers/init.go:53 GlobalInit()] [E] Fail to initialize ORM engine: Fail to connect to database: Unknown database type: mssql

## Description
Attempting to upgrade from Gogs with a SQL database.  Below is the relevant part of app.ini:
```
[database]
DB_TYPE = mssql
HOST = XXXX
NAME = Gitea
USER = GiteaWriter
PASSWD = XXX
SSL_MODE = disable
```
When running:
`gitea web --config /data/gitea/custom/conf/app.ini` I receive the error in the log file above.  From what I can see from the docs, mssql should be supported database type.

**Comment by techknowlogick** [comment]
Mssql is indeed supported, but can you confirm the version Of gitea you are using is 1.0.2 as perhaps that version doesn’t have mssql support. If you are following the upgrade path you might be able to just skip that version. Of course make sure to backup everything first.

**Comment by LukeMauldin** [comment]
I think it was a problem with 1.0.2. I was using that version because I was upgrading from Gogs. I exported the Gogs database into SQLite format and then I was able to import into Gitea.
