### ISSUE TITLE
CodeMirror text editor do not show  focus prompt.

### ISSUE THREAD

**Issue by FalconWu2017** [go-gitea/gitea#6129]
- Gitea version (or commit ref):1.7.1
- Git version:2.20.1.windows.1
- Operating system:windows 7
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MSQL
  - [ ] MSSQL
  - [x ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
Some CodeMirror has some minor problems，such as in wiki edit form.If you move mouse cursor to middle of the text，it will not show me the focus prompt，I don't know where the text will be inserted.

**Comment by Cherrg** [comment]
I couln't reproduce this on my side. (firefox/chrome/chromium on ubuntu). So let me ask some questions ;)

- Is it still there?
- How much content was on the wiki page?
- What browser did you use?
- Did you open very many other tabs?
- Any steps to reproduce?
- Was your gitea server or your browser Win 7?
- How good was your connection to gitea?
  - WLAN, LAN, WAN...
  - Was the page fully loaded?

**Comment by FalconWu2017** [comment]
1. It is OK for now.  
1. Not so much.  
1. used to be Chrome version 71 maby.,It's long time ago.I use Chrome 74 for now.
1. It is not more then 10 tabs.
1. Just cheate new page. not any more.
1. browser win7.
1. I think internet connection is well.
@Cherrg
