### ISSUE TITLE
Wiki only projects

### ISSUE THREAD

**Issue by jmthackett** [go-gitea/gitea#613]
Hello gitea people,

I'd really like it if a project could be wiki-only, but still with the ability to git clone/push etc as usual. I'd see this feature as supporting writing-only repos.

**Comment by lunny** [comment]
We will implement `Team Units` on v1.1. That means you could let some team only see wiki of some repos on organization.

**Comment by appleboy** [comment]
@jmthackett Please help to try this PR #1297
