### ISSUE TITLE
Require password policies configuration

### ISSUE THREAD

**Issue by misterpoesy** [go-gitea/gitea#6133]
- Gitea version (or commit ref):
- Git version: 
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

In sample config file [app.ini.sample](https://github.com/go-gitea/gitea/blob/master/custom/conf/app.ini.sample), I can config MIN_PASSWORD_LENGTH of security section. But password like '0123456789' still not secure. Implementation of custom password policies configuration is strongly recommended.

**Comment by mrsdizzie** [comment]
This was implemented as PASSWORD_COMPLEXITY https://docs.gitea.io/en-us/config-cheat-sheet/#security-security
