### ISSUE TITLE
Feature Request: GET/POST/DELETE reactions via API

### ISSUE THREAD

**Issue by meteorlxy** [go-gitea/gitea#6134]
## Description

GET/POST/DELETE reactions of issues/comments via API

- Github API: https://developer.github.com/v3/reactions - Github can get reactions via issueComments API directly by adding custom media type `application/vnd.github.squirrel-girl-preview+json`
- Gitlab API: https://docs.gitlab.com/ce/api/award_emoji.html - Gitlab have to get reactions via extra requests

**Comment by meteorlxy** [comment]
Will this feature be supported?

**Comment by 6543** [comment]
#8313 is about the same issue

**Comment by 6543** [comment]
#8823 is wip to sove this but i like to get #8886 before in ...

**Comment by 6543** [comment]
@meteorlxy #9220 is here :tada:
