### ISSUE TITLE
last updated in repo list is not updated

### ISSUE THREAD

**Issue by noerw** [go-gitea/gitea#6136]
- Gitea version (or commit ref): 1.7.2
- Git version: 2.16.5
- Operating system: debian
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description
On my instance, the `Updated X time ago` information (as shown in the explore page for example) is not updated when I push commits to repositories.
This happens since at least v1.6, as the last updated timestamp currently says "Updated 3 months ago".
I am not sure why I can't reproduce this on try.gitea.io, could it be a DB migration path problem?

**Comment by noerw** [comment]
- It does not seem to be a migration issue, as it also happens with newly created repos.
- This does not occur when committing in the webinterface.

Could this be related to incorrect ssh / authorized_keys setup?

**Comment by lafriks** [comment]
check that there are no errors in gitea.log or serv.log when pushing to repositories

**Comment by lafriks** [comment]
also check that your filesystem does not have noexec in fstab for partition where repositories are stored
