### ISSUE TITLE
Deploy keys will not be deleted at repo delete

### ISSUE THREAD

**Issue by xoxys** [go-gitea/gitea#6138]
- Gitea version (or commit ref): v1.7.1
- Git version:
- Operating system: CentOS7
- Database (use `[x]`):
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:

## Description
If you add a deploy key to a repository and delete the repo, the deploy key will persist in deploy_key table and reference a repo which does not exist anymore. The key also stays included in authorized_keys and can be result in problems if the key is used for other repositorys but in a different mode (read/write).

**Comment by jolheiser** [comment]
I believe this was fixed in #5939  
Updating to 1.7.2 should fix this issue.

**Comment by xoxys** [comment]
@jolheiser thanks, I will upgrade and report back

**Comment by xoxys** [comment]
Fixed. But I have to clean up my database by my own.
