### ISSUE TITLE
Deleting organisation while user is still in it, causes 500 error

### ISSUE THREAD

**Issue by sigio** [go-gitea/gitea#614]
Version: 6aacf4d
OS: Debian stable
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Not relevant

## Description

I've created some organisations, but wanting to keep them 'hidden' from the explore mode to non-logged in users. It seems that this wasn't possible, so I wanted to remove these organisations again.

I had created the orgs with my regular user account, and later removed them with the administrator account.

When logging in with my regular user account, the dashboard, issues and pull-request pages would give 500 errors, explore would work correctly.

It seems that the entries are not removed from the org_user table, after manually removing these, the 500 error disappeared:

sqlite> select * from org_user;
1|1|3|0|0|0
2|2|3|1|1|1
3|2|4|0|1|1
4|2|5|0|1|1

As my only remaining org had org_id 3, I did the following:

sqlite> delete from org_user where org_id > 3;
sqlite> select * from org_user;
1|1|3|0|0|0
2|2|3|1|1|1
sqlite>

this solved this issue, but removing a non-empty org should not be possible, or cascade and remove the relevant org_user entries.

**Comment by lunny** [comment]
It seems this issue has been resolved.

**Comment by glothriel** [comment]
I tried to reproduce it. I faced all the above problems, in addition also removing the organization from admin account yielded with 500 error. This error was triggered:
https://github.com/go-gitea/gitea/blob/master/models/user.go#L923

Btw, why is organization an User instance?

**Comment by Bwko** [comment]
@glothriel Did you set a custom avatar for that organisation?

**Comment by sigio** [comment]
I had custom avatars for the orgs

**Comment by glothriel** [comment]
@Bwko Nope

**Comment by appleboy** [comment]
I can reproduce this issue and fix in this pull request https://github.com/go-gitea/gitea/pull/633.

**Comment by appleboy** [comment]
Reproduce process in https://try.gitea.io/ :

1. Create organization
2. Create a report on the organization
3. Delete organization.
