### ISSUE TITLE
Consider dropping IE 11 support

### ISSUE THREAD

**Issue by silverwind** [go-gitea/gitea#6147]
This came up in https://github.com/go-gitea/gitea/pull/6139.

In my opinion it's time we drop IE11 support. It's cumbersome to test on for non-Windows users and has a ton of weird bugs that are never going to be fixed. I think we should put a statement to only support modern (evergreen) browsers.

Do we have any statistics how many users use IE on the gitea website?

**Comment by sondr3** [comment]
This gets a big thumbs up from me as well, Microsoft is all in on the new version of Edge running Blink and IE11 will only get fixes for very serious issues, it's about as dead in the water as it gets. Furthermore, I would be very surprised if the kind of people who use Gitea are also the same kind of people who use IE11.

**Comment by techknowlogick** [comment]
@sondr3 sadly I am one of those people who are required to use IE11 some of the time.

Also there are no analytics being collected on the main site.

Edit: I do recognize I am in the minority and so I won’t be a blocker to dropping support

**Comment by silverwind** [comment]
Windows 7 will EOL in around 11 months and from that point on, the only "supported" remaining version will be on Windows 10 LTSB. A shame really that MS does not seem to intend to kill it off entirely.

**Comment by 0x5c** [comment]
Seems to me like breaking compatibility *to* make a statement should be avoided. However, if maintaining said compatibility actively hinders the development of gitea, then it it should be considered.

**Comment by silverwind** [comment]
Also notable: GitHub also [no longer supports IE11](https://help.github.com/en/articles/supported-browsers).

**Comment by silverwind** [comment]
I think it's time we do this in the next major version (1.13).

**Comment by 6543** [comment]
I think we can put it to milestone 1.13?

**Comment by silverwind** [comment]
Indeed, 1.13 was my plan too.
