### ISSUE TITLE
Deactivated administrators are not deactivated?

### ISSUE THREAD

**Issue by michelvosje** [go-gitea/gitea#6151]
- Gitea version (or commit ref): 3b612ce built with go1.11.5 : bindata, sqlite, sqlite_unlock_notify
- Git version: 2.18.1
- Operating system: Docker
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [X] SQLite
- Log gist:

## Description
A week ago we deactivated a user account which was marked as an administrator account. The person assigned to the user account has left the organisation. We assumed that the user would not be able to login again into Gitea.

Today we found out he was able to create a new non-administrator account for somebody else (no worries it's contract related). I just tried it out and i see that deactivated administrator accounts still administrator rights. For us this is unexpected behaviour of Gitea which i wanted to report.
...

## Screenshots
![image](https://user-images.githubusercontent.com/5354633/53181418-ca601700-35f7-11e9-90d3-20a93cc13e05.png)

**Comment by jolheiser** [comment]
One thing to note, `Activated` is referring to email activation when you have enabled `REGISTER_EMAIL_CONFIRM` in settings.  
To stop someone from signing in, you would need to check `Disable Sign-In` when editing them.

**Comment by lunny** [comment]
@michelvosje @jolheiser I think I have sent https://github.com/go-gitea/gitea/pull/6115 merged in v1.7.3 should fix this problem. An unactived user should also be deny login except he clicked the activation link on the confirm email.

**Comment by michelvosje** [comment]
So am i correct that it is not possible to see from the overview of User Accounts which account is marked as enabled/disabled? I'd have to manually click all accounts 1 by 1 to see which one is and is not disabled?

From a security perspective i don't think that is correct. As an administrator i don't care who has and who has not clicked the email activation link.

**Comment by lafriks** [comment]
Most probably both options would be nice to see

**Comment by adelowo** [comment]
Might be a little confusing if both options are there. I think Activated can be swapped out for @michelvosje 's suggestion
