### ISSUE TITLE
404 when compare code

### ISSUE THREAD

**Issue by FalconWu2017** [go-gitea/gitea#6155]
- Gitea version (or commit ref):1.7.2
- Git version:1.20.1
- Operating system:windows server 2012 datacenter
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

2019/02/22 10:41:09 [D] CSRF Token: 
2019/02/22 10:41:10 [T] ParseCompareInfo[5]: does not have fork or in same repository
2019/02/22 10:41:10 [D] Template: status/404

## Description
If request the url like '/compare/master...userName:fix3' it will lead to 404 page.
This is wrong url,it default compare local repo and fork repo, but I don't have any fork repos existed.I want compare two branchs in same repo.

**Comment by 0x5c** [comment]
Is it like #3727 ?

**Comment by FalconWu2017** [comment]
Yes,it is.

**Comment by lunny** [comment]
This has been resolved by https://github.com/go-gitea/gitea/pull/6098
