### ISSUE TITLE
Severe Security Issue: full read only access to git repos without authentication

### ISSUE THREAD

**Issue by uwebartels** [go-gitea/gitea#6157]
- Gitea version (or commit ref): dfad569, 1.7.1
- Git version: 2.18.1
- Operating system: Alpine Linux v3.8.2
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
when using an url from a pull request, I can see the content of the pull request without authentication. After that I'm able to browse through all repositories - still without authentication.
...
<img width="1348" alt="screenshot" src="https://user-images.githubusercontent.com/2845222/53244417-1d46d680-36ab-11e9-9042-c523f809ddb1.png">

**Comment by uwebartels** [comment]
this seems to be the visibility flag in the repositories. sorry.

**Comment by lunny** [comment]
This is a public repository.
