### ISSUE TITLE
app.ini settings cause "new organization" not shown any more

### ISSUE THREAD

**Issue by vosdbk** [go-gitea/gitea#6158]
- Gitea version (or commit ref): 1.7.2
- Git version: 2.20.1
- Operating system: Centos 7 / Windows 10
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL with Centos 7
  - [ ] MSSQL
  - [x] SQLite with Windows 10
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
Once you change the follow settings from
```
[admin]
DISABLE_REGULAR_ORG_CREATION = false
[service]
DEFAULT_ALLOW_CREATE_ORGANIZATION = true
```
to
```
[admin]
DISABLE_REGULAR_ORG_CREATION = true
[service]
DEFAULT_ALLOW_CREATE_ORGANIZATION = false
```
Then, what ever you change it to what, the menu "new organization" will be not shown any more for existed users

---

## Screenshots
1. The settings with running gitea
![settings in app.ini](https://user-images.githubusercontent.com/2115591/53250304-1e045a80-36f5-11e9-9755-d26dec801a87.png)
2. The interface you get, just missing "new organization"
![user interface](https://user-images.githubusercontent.com/2115591/53250314-22c90e80-36f5-11e9-8f70-a13bbd6da597.png)

**Comment by vosdbk** [comment]
PS:
If you change it to "allowed to create new organization" then register a new user, this new user has the create menu, but existed user such as register during "not allowed to create new organization" time, won't see the create menu any more

**Comment by adelowo** [comment]
That value is persisted to the database for each user so the user created during "not allowed" has the field in the DB as "not allowed".

**Comment by techknowlogick** [comment]
Closing per @adelowo’s comment.
