### ISSUE TITLE
Pages, but as subdir rather than subdomain

### ISSUE THREAD

**Issue by andrewdunndev** [go-gitea/gitea#6163]
Pages has been proposed in several other issues, to enumerate some:

 - #302
 - #2208
 - #3834

However there is an assumption that you must use subdomains as this is how github/gitlab have implemented them. Some are suggesting bundling of caddy (e.g. #1721) but this is making a choice for people that is uncomfortable (e.g. I enjoy running a simple go binary behind nginx for tls termination, I don't particularly want nginx->caddy->gitea or to learn/use caddy for just gitea)

Rightfully proposed by @techknowlogick in #302, if you're going to do subdomain pages you might as well work that through the CI route. However many users are going to be interested in static page hosting without having a CI system.

It could be possible to run these pages as subdirectories, maybe with a prefix of `~/` of some kind where `~/organization` provides a static page for the organization and `~/organization/repo` does the same for repo (switch `organization` for `user`), with some complexity in access control (e.g. don't show static pages to users who have not logged in, if that's the intent).

So, this can me marked dupe and closed, but I'll offer one twist:

This is an interesting feature and we'd be willing to fund it directly. We cannot bounty-source and we cannot easily donate to the project but we can contract directly with a developer(s) who want to take this work on as long as you propose a plan that upstream is willing to bite on. It would be the lowest risk for us to work with proven contributors or maintainers of this project.

**Comment by lunny** [comment]
There are some security reasons to be consider when using subdir than subdomain.

**Comment by sblisesivdin** [comment]
I think even a static page website thing is not necessary. Wiki feature can be used to built sites with subdir. The thing is people want to host documentation and project related websites with this. No need to repeat the GitHub or GitLab on this feature.
