### ISSUE TITLE
Only issue access for user w/o read git repo

### ISSUE THREAD

**Issue by gusta70** [go-gitea/gitea#6169]
In repo settings, in contributor section add extra issue access permission.
With this permission user can only access issue for repository.

**Comment by lafriks** [comment]
You can do this already in organization team settings

**Comment by gusta70** [comment]
How?
I see limited and private only.
How can i help with this?

**Comment by lafriks** [comment]
When you create organization, you can create new team team there where you can set your needed rights and add org repositories and users to it

**Comment by gusta70** [comment]
i try but...
please explain, how to add one user to team, who has only issue permission, and without read git repo
