### ISSUE TITLE
authentication questions and feature request

### ISSUE THREAD

**Issue by laoshaw** [go-gitea/gitea#617]
- Gitea version (or commit ref):
- Git version: 1.0
- Operating system: Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ *] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [* ] Not relevant
- Log gist:

## Description

Can I set something like export USER and export PASSWD so that I do not need enter username and password for git operations?

Also is it possible to implement two-way authentication? How safe is it to host gitea on the internet?
...

**Comment by lunny** [comment]
Save USER and PASSWD is git's things, I think it has implemented it. For two-way authentication, please go to https://github.com/go-gitea/gitea/issues/179 to discuss.
