### ISSUE TITLE
--name and --username consistency issue in CLI

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#6174]
- Gitea version (or commit ref): 1.7
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Not relevant

## Description
In create-user --name is used, but in change-password --username is used instead.

**Comment by ngourdon** [comment]
Which one should we keep ?
I think "--name" is better. We know we're talking about user in these commands.

We should keep both parameters to ensure backward compatibility for a while.

I can contribute on this if we're OK.

**Comment by mrsdizzie** [comment]
I think this should always be --username when referring to the actual username

username is a term with a specific meaning (the username), where as name is not. 

Also, an account has both a username and then a separate name/full name field so it should always use the phrase username when referring to the actual username (which this case is).
