### ISSUE TITLE
Password expiration date

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#6175]
## Description

It would be nice if it would be possible to set an expiration date for a user's password so that they'd have to change it after a set period of time (or date).

**Comment by jolheiser** [comment]
This doesn't directly implement the requested feature, but I thought I'd post it here so people can use it as a temporary fix with 1.8+

#6193 will add the `MustChangePassword` options to the API for creating/editing a user, so this could viably be done with a cron job until the feature is potentially implemented.
