### ISSUE TITLE
using latest gitea docker image unable to set arc-green theme

### ISSUE THREAD

**Issue by vtolstov** [go-gitea/gitea#6179]
i'm using gitea/gitea:latest via app.ini set arc-green theme, but nothing changed when i'm access my gitea instance via browser.
In browser i see gitea version: 6efdcae
Also how can i check that i have issues dependencies feature?

**Comment by lafriks** [comment]
That is default theme. Check your user preferences, there you can set your user preferred theme

**Comment by vtolstov** [comment]
@lafriks thanks, but i don't see in profile settings any things related to theme

**Comment by lafriks** [comment]
Yeah it should probably moved to section where language selection is. Currently it is under account settings:
![attels](https://user-images.githubusercontent.com/165205/53374754-f665fa00-3961-11e9-8721-481b212e43bd.png)

**Comment by vtolstov** [comment]
and if i don't have this item?

**Comment by vtolstov** [comment]
![image](https://user-images.githubusercontent.com/481307/53417430-9f563880-39e6-11e9-9b17-8bab58750980.png)

**Comment by lafriks** [comment]
Looks like you have old version that does not support themes

**Comment by vtolstov** [comment]
but i see in my webui  in git.unistack.org  Gitea Version: 6efdcae

**Comment by vtolstov** [comment]
does it possible that some update in db does not work properly? I have gitea installed from he beginning of time when it forked from gogs =)

**Comment by lafriks** [comment]
Themes was added in Gitea 1.6.0, you have older version installed. Update to latest 1.7.2 version and you can set default theme

**Comment by Kasurus** [comment]
In 1.7.2 there seems to be no option to change the theme over the web UI.
I changed to the dark theme by adding this to `custom/conf/app.ini`:

`DEFAULT_THEME=arc-green`

**Comment by vtolstov** [comment]
@lafriks how can it possible that i have old gitea version if i pull docker image via docker pull gitea/gitea:latest ?

**Comment by vtolstov** [comment]
nevermind, this is docker issue.

**Comment by 001101** [comment]
installed it today from https://dl.gitea.io/gitea/1.7.4/gitea-1.7.4-linux-amd64

and also don't have the option to select the themes, did also added the two themes in the app.ini

when i change the default theme to arc-green in app.ini, it now works!
but after some small changes in the templates it also drops this error as a signed in user:

_template: base/head:152:21: executing "base/head" at <.SignedUser.Theme>: can't evaluate field Theme in type interface {}_

after removing the 151-157 if lines and just placing `<link rel="stylesheet" href="{{AppSubUrl}}/css/theme-{{DefaultTheme}}.css">` it works!

**Comment by jolheiser** [comment]
User themes are part of 1.8

**Comment by 001101** [comment]
> User themes are part of 1.8

Strange that i am now using arc-green with 1.7.4

**Comment by jolheiser** [comment]
The default theme option was added in 1.6
Users can choose their own theme in 1.8

Regarding your error, if you are using 1.7.x you must pull your template from the `release/v1.7` branch. The `release/v1.8` and `master` branch both have User Theme functionality in the template.

**Comment by 001101** [comment]
alright thanks, now i get it. @lafriks did not say what version he is using!
