### ISSUE TITLE
Redirect to signin page when trying to open a private repository

### ISSUE THREAD

**Issue by bouffa** [go-gitea/gitea#6182]
- Gitea version (or commit ref): 594f591 
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL) : https://try.gitea.io/bouffa/test/wiki/Home 
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

When a not signed-in user/visitor tries to open a private repository using a direct link (or a wiki page of a private repository), I would expect it to be redirected to the sign-in page instead of the 404 page of the current behavior. Shouldn't be this the expected behavior in this case?

**Comment by techknowlogick** [comment]
This would leak private information. As it would allow non authenticated users to determine if a specific repo exists
