### ISSUE TITLE
404's on files within sub directory

### ISSUE THREAD

**Issue by Nubston** [go-gitea/gitea#6187]
- Gitea version (or commit ref):1.7.1
- Git version:2.20.0
- Operating system: Windows Server 2016 Standard
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ x ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ x ] No 
  - [ ] Not relevant
- Log gist:

## Description

when i try to accsess a file within this sub folder it just 404s i can get into the folder inside that folder but if i try to open the file it just 404's how can i fix this
urlto offendign subdirectory: https://git.thetofushop.net/Nubston/MyFirstApp/src/branch/master/My%20First%20App

**Comment by lunny** [comment]
Migrate your repo to https://gitea.com/lunny/MyFirstApp/src/branch/master/My%20First%20App/Program.cs and it seems it worked. Maybe your reverse proxy server misconfigured.

**Comment by Nubston** [comment]
figured it otu for anyone who has this issue in the future

add this to your web.config on the sub domain you are using for reverse proxy if you are using IIS
 			 
`<security>
         <requestFiltering>
            <denyUrlSequences>
               <clear />
            </denyUrlSequences>
            <fileExtensions allowUnlisted="true">
               <clear />
            </fileExtensions>
         </requestFiltering>
      </security>`

**Comment by Nubston** [comment]
i dont no how to make that code layout properly hopefuly you understand

**Comment by multinerd** [comment]
@Nubston you life saver! I was going crazy thinking it had something to do with document browsing. 

Cleaner format:
```
    <system.webServer>
        ...
        <security> 
            <requestFiltering> 
                <denyUrlSequences> 
                    <clear /> 
                </denyUrlSequences> 
                <fileExtensions allowUnlisted="true"> 
                    <clear /> 
                </fileExtensions> 
            </requestFiltering> 
        </security>
        ...
    </system.webServer>
```
