### ISSUE TITLE
Unable to set labels on issues

### ISSUE THREAD

**Issue by silverwind** [go-gitea/gitea#6191]
Reproduced on https://try.gitea.io/silverwind/symlink-test/issues/1, but should affect any issue. 

1. Create new issue without any labels
2. Try to set a 'bug' label by clicking it in the dropdown and closing the dropdown by clicking outside
3. Page initially shows the label, but then reloads and label is gone

Maybe related to https://github.com/go-gitea/gitea/pull/5980 @jolheiser.

**Comment by lunny** [comment]
Cannot reproduce on your link! macOS chrome

**Comment by silverwind** [comment]
Hmm, looks to affect Firefox only, testing further.

**Comment by jolheiser** [comment]
Isn't Javascript just *so much fun*?  
Is there any error in browser dev console?

**Comment by silverwind** [comment]
Issue found, it is a race condition between `location.reload` and `updateIssueMeta` (which is async). I guess it only worked by sheer luck in Chrome.

**Comment by jolheiser** [comment]
Ah, shoot. Thanks for the catch!
