### ISSUE TITLE
False information in "merged by"

### ISSUE THREAD

**Issue by strk** [go-gitea/gitea#6199]
Gitea version 1.5.2 shows a pull request as "merged by <committer>" but the merge was actually done by somebody else (`<committer>` does not have write access to the repo).

The information about _who_ did the merge was lost.

Can this happen when the merge is a forward-merge ?
It sounds like a bug to me, to loose such information.

**Comment by strk** [comment]
Where you can see this problem live: https://git.osgeo.org/gitea/geos/geos/pulls/70#issuecomment-3854

**Comment by strk** [comment]
@lafriks do you have any idea about this ? (pinging you as the author of https://github.com/go-gitea/gitea/pull/3368)

**Comment by strk** [comment]
For comparison, github seems to always say `merged by <authenticated_user_at_time_of_push>`, which I guess implies checking each of the commits being pushed to a repository against existing PRs and spotting which ones are being manually merged.

\cc @dbaston

**Comment by strk** [comment]
Interesting read: https://help.github.com/en/articles/about-pull-request-merges
\cc @mloskot

**Comment by 0x5c** [comment]
1.*5.2?*

**Comment by lafriks** [comment]
@strk can you reproduce this on try.gitea.io? There have been changes about this, and I think it should be already fixed in latest version

**Comment by 0x5c** [comment]
Looking at the latest messages on the thread, the PR closed itself as merged when the (locally merged) commit was pushed by someone.
