### ISSUE TITLE
Change Password page is "sticky"

### ISSUE THREAD

**Issue by strk** [go-gitea/gitea#620]
When going to the "Password" tab in the user settings the form get automatically filled by Javascript (I think) with the effect of having your browser ask you for confirmation before leaving the page again.
Stumbled upon this while going trough all tabs in the Settings page.

Haven't tried on try.gitea.io but I guess that's how it works there too.
My tests were done locally against 1.1.0-dev (f4feeecc3af089a105c9a1ad976a78cd6856b407)

**Comment by metalmatze** [comment]
Isn't that specific and an implementation detail of your browser? How would we change this behaviour?

**Comment by strk** [comment]
I haven't dug but I suspect the problem is with having Javascript
write into the form, rather than shipping the default form content
directly with the HTML

**Comment by glothriel** [comment]
I suspect it's Your browser's password manager filling the form. When the form is non-empty, there is javascript's beforeunload event, that tries to warn You, that You are trying to leave non-empty form.

**Comment by bkcsoft** [comment]
yeah, the areYouSure-plugin is doing the asking... might make that an optionally injected script for the pages that actually needs it (issue, wiki, anything with an editor) instead

**Comment by tboerger** [comment]
This doesn't happen without password autofill.

**Comment by bkcsoft** [comment]
@tboerger there's a `no-autofill` setting for input-boxes IIRC

**Comment by tboerger** [comment]
> @tboerger there's a no-autofill setting for input-boxes IIRC

I don't get this field prefilled automatically.
