### ISSUE TITLE
Gitea 1.6.2 failed to start after restart with error Invalid object name 'SYS.INDEXES'

### ISSUE THREAD

**Issue by eMuonTau** [go-gitea/gitea#6201]
- Gitea version (or commit ref):gitea-1.6.2-windows-4.0-amd64
- Git version: 2.21.0.windows.1
- Operating system: Windows Server 2012 R2
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:
2019/02/27 19:59:03 [I] Log Mode: File(Info)
2019/02/27 19:59:03 [I] XORM Log Mode: File(Info)
2019/02/27 19:59:03 [I] Cache Service Enabled
2019/02/27 19:59:03 [I] Session Service Enabled
2019/02/27 19:59:03 [...itea/routers/init.go:60 GlobalInit()] [E] Failed to initialize ORM engine: sync database struct error: mssql: Invalid object name 'SYS.INDEXES'.
## Description

This happened after i restarted my server. If there is any other way that i can provide more info please let me know.

**Comment by techknowlogick** [comment]
Hi @Noderino, first thing is you'll likely want to upgrade to the latest version as we've fixed some major security vulnerabilities, also the DB library has been updated which might solve the problem.

Are you able to connect directly to MSSQL to run queries manually against it?

**Comment by eMuonTau** [comment]
Yes i can connect to MSSQL without a problem. I also tried to replace gitea.exe with newer versions and latest but i am still getting same error.

**Comment by eMuonTau** [comment]
This is the log before first "Invalid object name" error.

2019/01/29 18:45:40 [...routers/repo/http.go:137 HTTP()] [E] invalid credentials
2019/01/29 18:45:40 [...routers/repo/http.go:137 HTTP()] [E] invalid credentials
2019/01/29 18:46:15 [...routers/repo/http.go:137 HTTP()] [E] invalid credentials
2019/01/29 18:46:15 [...routers/repo/http.go:137 HTTP()] [E] invalid credentials
2019/02/27 13:10:07 [I] Log Mode: File(Info)
2019/02/27 13:10:07 [I] XORM Log Mode: File(Info)
2019/02/27 13:10:07 [I] Cache Service Enabled
2019/02/27 13:10:07 [I] Session Service Enabled
2019/02/27 13:10:08 [...itea/routers/init.go:60 GlobalInit()] [E] Failed to initialize ORM engine: Unable to open tcp connection with host '127.0.0.1:1433': dial tcp 127.0.0.1:1433: connectex: No connection could be made because the target machine actively refused it.
2019/02/27 13:11:07 [I] Log Mode: File(Info)
2019/02/27 13:11:07 [I] XORM Log Mode: File(Info)
2019/02/27 13:11:07 [I] Cache Service Enabled
2019/02/27 13:11:07 [I] Session Service Enabled
2019/02/27 13:11:22 [...itea/routers/init.go:60 GlobalInit()] [E] Failed to initialize ORM engine: sync database struct error: mssql: Invalid object name 'SYS.INDEXES'.

**Comment by lunny** [comment]
Which version of your database?

**Comment by eMuonTau** [comment]
SQL Server 2014

**Comment by eMuonTau** [comment]
@lunny Do you mean version number in dbo.version table? It is 74

**Comment by lunny** [comment]
@Noderino No. I means your SQL Server.
