### ISSUE TITLE
Problem with migration

### ISSUE THREAD

**Issue by Monter** [go-gitea/gitea#6204]
- Gitea version (or commit ref): newest on local server and TryGITEA too
- Database (use `[x]`):
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
https://try.gitea.io/aaaax/Awesome-WAF

## Description

I found a problem with the project import from GH - the import is not correct, in particular the readme.md content (see
https://try.gitea.io/aaaax/Awesome-WAF
relative to the original:
https://github.com/0xInfection/Awesome-WAF

**Comment by techknowlogick** [comment]
Closing as migration worked, it's just the markdown rendering terminates due to having issues with some of the script tags (this issue of terminating early is already another issue #2246)

**Comment by Monter** [comment]
The claim that "migration works" in relation to a reported error is like saying that a car with a punctured tire works because the engine starts. No offense ;-)
I am waiting for a solution.
