### ISSUE TITLE
Issue sort by due date

### ISSUE THREAD

**Issue by stevegt** [go-gitea/gitea#6206]
#2533 added due dates to issues, but we seem to have no way to sort by due date when reporting, and I can't find an outstanding issue in github discussing this either.  I'll take a look at adding this, but wanted to check in here before trying to tackle it in case I'm missing something.  Anyone know of any work on this?

**Comment by lunny** [comment]
@stevegt nobody are working on this. PR is welcome. @techknowlogick I think enhancement is better for this issue.

**Comment by stevegt** [comment]
merged in #6244
