### ISSUE TITLE
Managing /robots.txt

### ISSUE THREAD

**Issue by sztanpet** [go-gitea/gitea#621]
My use-case is simply to hide gitea from well-behaved search engines but still expose it on the internet.
Not sure how fine-grained it would need to be, but for my use-case I simply need to deny everything to everyone.

**Comment by metalmatze** [comment]
If you're running gitea behind a proxy you might be able to serve a `/robots.txt` right now. But maybe we should add it to gitea itself.

**Comment by sztanpet** [comment]
Indeed, if there is a robots.txt in the custom path, gitea will serve that file, so maybe this just needs documentation?

**Comment by tboerger** [comment]
Please file an issue or a pull request on the docs repo. For this repo it's invalid because it's already implemented.

**Comment by tboerger** [comment]
Just to make it clear, you can place a robots.txt into the custom/ folder, restart gitea and this file will get served
