### ISSUE TITLE
Mirror repositories on organization are missing on dashboard.

### ISSUE THREAD

**Issue by rbouikila** [go-gitea/gitea#6217]
- Gitea version (or commit ref): 1.7.2
- Git version: 2.11.0
- Operating system: OrangePI (Debian on ARM)
- Database (use [x]):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
 - Yes (provide example URL)
 - No
 - Not relevant
- Log gist:

## Description:
I set up a mirrors from Github. All seems to work perfectly.
By checking the dashboard, it does not appear in the list of mirrors.

## Screenshots
![image 1](https://user-images.githubusercontent.com/4258294/53606779-4e983880-3bbc-11e9-87b5-0b97ace60985.png)

**Comment by lunny** [comment]
Cannot reproduce this.

**Comment by rbouikila** [comment]
I update my gitea version 1.7.2 to 1.7.3.
I have same issue. I create mirror repository from github but it's not appear to mirror list.

API command : /api/v1/repos/search?uid=1&q=&limit=15&mode=mirror
![api_1](https://user-images.githubusercontent.com/4258294/53771479-faa29200-3ee2-11e9-9350-ef0339f81ba9.png)

API command : /api/v1/repos/search?uid=1&q=&limit=15&mode=mirror&exclusive=1
![api_2](https://user-images.githubusercontent.com/4258294/53771482-fd9d8280-3ee2-11e9-926e-bc2b0eec2024.png)

**Comment by lunny** [comment]
Is that mirror repository on your individual or organization ?

**Comment by rbouikila** [comment]
It is a mirror repository on the organization.

**Comment by lunny** [comment]
So the problem maybe mirror repository on the organization didn't shown on dashboard. Maybe you could change the title?

**Comment by rbouikila** [comment]
I update title issue.

**Comment by lunny** [comment]
@rbouikila I don't think you changed the right title. The bug should be mirror repositories on organization are missing on dashboard `mirrors` type. Am I right?

**Comment by rbouikila** [comment]
Yes that's it. i update title.

**Comment by mrsdizzie** [comment]
I tried to reproduce this also but can't.

Can you give an exact list of steps to reproduce this on try.gitea.io?

I tried:

new migration
Make owner orginization
choose mirror option for migration type

Then it shows up on the orginization dashboard under the mirrors section

**Comment by rbouikila** [comment]
Hi, 

i create "myorga1" organisation to "try.gitea.io". 
i create "choosealicense" mirror to "myorga1".

when i go to mirrors dashbord, i not see mirror repository.

<img width="423" alt="Screen" src="https://user-images.githubusercontent.com/4258294/55657113-8026a400-57f9-11e9-94f4-fb2b5568c5ba.png">

**Comment by mrsdizzie** [comment]
That screenshot above doesn't appear to be from the organization dashboard, but rather the user dashboard. It has the "Organisation" button above which isn't present on the organization dashboard.

Are you sure you are looking at:

 https://try.gitea.io/org/myorga1/dashboard

You can switch the Dashboard context with the dropdown menu on the top left like so:

<img width="453" alt="Screen Shot 2019-04-05 at 5 30 01 PM" src="https://user-images.githubusercontent.com/1669571/55657517-78024080-57c8-11e9-96ab-4ae0000f720e.png">

**Comment by rbouikila** [comment]
hi mrsdizzie,

Indeed, it is not a bug. I can see the mirror in the dashboard.

Thank you for the explanation.

I close this issue.
