### ISSUE TITLE
Cannot go to my fork when on main org project

### ISSUE THREAD

**Issue by bkraul** [go-gitea/gitea#6222]
- Gitea version (or commit ref): 8e266c3
- Operating system: Ubuntu 18.04 (docker)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
Not being able to click on the forks of a project in order to get to my own fork of the organizational project I have forked. Again, I am set as an owner of the organization. I think this may be related to #6195. The desired behavior is that I would see a list of the forks and be able to click on my fork to navigate to it.

## Screenshots
![image](https://user-images.githubusercontent.com/14616851/53655927-41f4fe00-3c17-11e9-96f8-88a33d65f06b.png)

I have also tested this with a developer (non-owner) of the org and the result is the same, he can't get to the list of forks, whereas in the past he could. Area now appears disabled.

**Comment by jolheiser** [comment]
Ahhh, this is a side effect of my PR #5980. 
Instead of disabling the whole button, it needs to allow listing the forks still. I will try to get a fix in for this soon.

**Comment by bkraul** [comment]
The behavior now works as intended, however, there is a small inconsistency with the link. All the others show as active links, but the one for fork shows gray as disabled. Clickable, but with a disabled style:

![image](https://user-images.githubusercontent.com/14616851/53850990-b9fa5580-3f82-11e9-9d1b-db6ab2cb1b6a.png)

I could be wrong, but shouldn't the number of forks show up in  the darker style?
