### ISSUE TITLE
OAuth2 consumer support

### ISSUE THREAD

**Issue by willemvd** [go-gitea/gitea#623]
To be able to use SSO functionality in a (corporate) environment we would like to be able to login using OAuth2
This would mean a area in the admin panel/app.ini to setup OAuth2 token and authorize urls (or maybe give a option to select a default implementation from https://godoc.org/golang.org/x/oauth2#pkg-subdirectories), client_id and client_secret.

**Comment by bkcsoft** [comment]
Closed as duplicate https://github.com/go-gitea/gitea/issues/26
