### ISSUE TITLE
Version 1.7.3 home.tmpl does not work

### ISSUE THREAD

**Issue by MyLive** [go-gitea/gitea#6238]
- Gitea version (or commit ref): 1.7.3
- Git version: 2.20.1
- Operating system: ubuntu 18.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:

## Description

Version 1.7.3 home.tmpl does not work
Gittea is started with Systemd
WorkingDirectory=/opt/gitea

-rw-r--r-- 1 root root 351 Mar  4 16:03 /opt/gitea/custom/templates/home.tmpl

**Comment by jolheiser** [comment]
Are there any errors in the logs or on the page?  
Based on that path it looks like you're using a custom template, when was it last updated?

**Comment by MyLive** [comment]
No, i dont see any error in the log ( loglevel = debug )

**Comment by techknowlogick** [comment]
What isn't working about it? Is it that Gitea doesn't start up, or you can't see any changes made to the template? Or something else?

**Comment by MyLive** [comment]
Gittea works, but the home.tmpl doesnt work.

I see no changes :-)

**Comment by lunny** [comment]
That's your user-defined home.tmpl?

**Comment by MyLive** [comment]
Yes

**Comment by jolheiser** [comment]
Can you send a screenshot of how it isn't working, or what you expect to see that you don't?

**Comment by techknowlogick** [comment]
I think this might be related to perhaps a missing custom env variable

**Comment by MyLive** [comment]
The Template have only the Content
`
{{template "base/head" .}}
Test
{{template "base/footer" .}}
`
But the home Site have the normal Content :-/
@techknowlogick which var did you mean ?

**Comment by MyLive** [comment]
Solved ..
@techknowlogick  you're right ..

I have forgotten to set GITEA_CUSTOM Env var.

Thanks a lot for the hint :+1:
