### ISSUE TITLE
Clicking `Releases` causes 500

### ISSUE THREAD

**Issue by Fastidious** [go-gitea/gitea#624]
Clicking on the `Releases` tab will cause an error 500, if there are no releases. Can be experienced on [Try Gitea](https://try.gitea.io).

**Comment by jomp16** [comment]
Log: [...ters/repo/release.go:75 Releases()] [E] Releases: no more pages.

I think the following line is the culprit: https://github.com/go-gitea/gitea/blob/61306fa737f693c3b325d9a8da047ba0b939537e/routers/repo/release.go#L74

Maybe instead of showing 500, show a page with "no releases"?
