### ISSUE TITLE
Document pprof  configuration

### ISSUE THREAD

**Issue by adelowo** [go-gitea/gitea#6240]
- Gitea version (or commit ref): `master`
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

- Cheat sheet ( https://docs.gitea.io/en-us/config-cheat-sheet/ ) doesn't contain `ENABLE_PPROF` and `PPROF_DATA_PATH` .
- Command line docs ( https://docs.gitea.io/en-us/command-line/ ) doesn't contain the `enable-pprof` command line option when using `gitea serve`

**Comment by adelowo** [comment]
I will write this up before the weekend ends

**Comment by jolheiser** [comment]
Stumbled across this issue, seems we can close it. 

`ENABLE_PPROF` is in the cheat sheet, and as far as I can tell there is no longer a command-line option for it. (Although, I wonder if that would be a good thing to add...)

**Comment by jolheiser** [comment]
My apologies, I confused `serve` with `web`. 

We do not have it documented for `serv`, though since it's mostly an SSH passthrough, I'm not entirely sure when it gets used off the top of my head.

**Comment by xor-gate** [comment]
Gitea `serv` in combination with `PPROF` envvars is used to profile the cpu/memory consumption of the SSH passthrough.

**Comment by jolheiser** [comment]
> Gitea `serv` in combination with `PPROF` envvars is used to profile the cpu/memory consumption of the SSH passthrough.

I am aware of this, however the `serv` command is never directly used by a human (that I know of), only by Gitea itself when invoked for SSH.  
Given that, the config makes sense, however I'm not sure when the CLI flag would be used in that situation.

The entire `serv` command is undocumented because it's not a command users are expected to invoke manually.

**Comment by zeripath** [comment]
Frankly if you are wanting to pprof gitea serv you are in way too deep and you should be asking for help. No documentation is going to cover such problems.
