### ISSUE TITLE
AUTO_WATCH_NEW_REPOS = false does not seem to work

### ISSUE THREAD

**Issue by troygeiger** [go-gitea/gitea#6242]
- Gitea version (or commit ref): 1.7.2
- Git version: 2.17.0.windows.1
- Operating system: Windows Server 2016
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
With the option [service] AUTO_WATCH_NEW_REPOS = false, all members of organizations still are automatically watching when the repo is created. 

Thanks!
...

**Comment by markusamshove** [comment]
I can confirm this

**Comment by sebastian-sauer** [comment]
Hi, this option will be introduced with  1.8.0 (see the label at https://github.com/go-gitea/gitea/pull/5852 ).

**Comment by troygeiger** [comment]
Excellent! Thank you.
