### ISSUE TITLE
Pre-receive hook always reject the push to the remote repository

### ISSUE THREAD

**Issue by parambath92** [go-gitea/gitea#6249]
Pre-receive hook under gitea has a shell script which is working. But after updating and resynchronizing pre-receive the hook it rejects all the push from the local repo even after giving the correct commit message matching the regular expression. The script is as shown:

```bash
#!/usr/bin/env bash
INPUT_FILE=$1
START_LINE=`head -n1 $INPUT_FILE`
PATTERN="^(PROJ):"
if ! [[ "$START_LINE" =~ $PATTERN ]]; then
  echo "Your commit message is not formatted correctly. Your message should be in the format: ('PROJ: commit message’)"
  exit 1
fi
```

**Comment by lunny** [comment]
Need more detail to reproduce.
