### ISSUE TITLE
Rest API, doesnt show releases of Migrated Repository

### ISSUE THREAD

**Issue by wlauppe** [go-gitea/gitea#6251]
- Gitea version (or commit ref):1.7.3
- Git version: 2.11.0
- Operating system:debian stretch
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

If I create a repository via the migration tool  releases dont show up in the rest response. 

Steps to reproduce: 
click on "+" "new migration"
enter https://github.com/go-gitea/gitea into "clone url" 

query the rest interface via bash (or swagger) 

token=xxx
usern=xxx
server=server .name

curl -X GET "https://$server/api/v1/repos/$user/gitea/releases?access_token=$token" -H  "accept: application/json"

 No  migrated releases are  shown, if you create a new release in this  this repository the rest api returns a result, but the migrated ones are still missing.

**Comment by wlauppe** [comment]
![releases](https://user-images.githubusercontent.com/3273201/53899846-68fa6800-403b-11e9-81f6-6676aedf9af9.png)

hiere is a screenshot, the newly entered release "test" is shown in the api, the migrated ones are not.

**Comment by techknowlogick** [comment]
There is a difference between releases and tags. Note in your screenshot how the new release you created looks different from the imported tags.

**Comment by wlauppe** [comment]
ah ok, thats confusing, but the migrated repository still lists 53 releases, so they must have been imported? or not? 
![releases2](https://user-images.githubusercontent.com/3273201/53900742-7a447400-403d-11e9-903c-21b6d4a7b796.png)

**Comment by techknowlogick** [comment]
just like on github the releases tab includes tags as well as releases.

**Comment by wlauppe** [comment]
Thanks for the quick reply, so to summerize: 
even if counterintuitive at first it works as intended. 
Releases are not imported from github only tags are. 
Tags can not by queried at the moment by the rest api but will be in the 1.8 release
https://github.com/go-gitea/gitea/issues/2738
