### ISSUE TITLE
DigitalOcean Marketplace

### ISSUE THREAD

**Issue by oflak** [go-gitea/gitea#6252]
What do you think of adding Gitea to the @digitalocean [Marketplace](https://marketplace.digitalocean.com/category/all)?

**Comment by techknowlogick** [comment]
That's a great idea. I've just applied to become a DO Marketplace vendor to allow us to distribute Gitea via the DO Marketplace.

**Comment by techknowlogick** [comment]
Sadly my application didn't go through due to a JS error on the submission form, I will try a different browser.

Edit: A different browser didn't work, looks like form submissions are broken. Will try again later.

**Comment by lunny** [comment]
@techknowlogick I have submitted that successfully.

**Comment by techknowlogick** [comment]
![Screen Shot 2019-04-17 at 3 12 57 PM](https://user-images.githubusercontent.com/164197/56314536-5c315f80-6123-11e9-9df2-a2e1229d64d0.png)

Listing request has been submitted.
