### ISSUE TITLE
Feature request: diffing images

### ISSUE THREAD

**Issue by mateusza** [go-gitea/gitea#6255]
## Description
This is a feature request.

The feature is visual comparison of images.
This feature is available in GitHub and BitBucket:
https://help.github.com/en/articles/rendering-and-diffing-images

![image](https://user-images.githubusercontent.com/7002/53908567-ec25b900-404f-11e9-9bbb-cbc9312af3de.png)

Ideally following methods of comparing images should be implemented:
- side by side
- overlay
- blend
- mark changed pixels

**Comment by arthur-bauer** [comment]
Yes please. This would make a big difference for us here.

**Comment by saitho** [comment]
Hey there. I submitted a pull request for the "side by side" part.
That part was pretty easy. The others would require more work. ;)

**Comment by lunny** [comment]
closed by #6784
