### ISSUE TITLE
Heatmaps don't render on my instance

### ISSUE THREAD

**Issue by veeara282** [go-gitea/gitea#6259]
- Gitea version (or commit ref): 1.7.3
- Git version: 2.17.1
- Operating system: Ubuntu 18.04.2 LTS (GNU/Linux 4.18.0-1011-azure x86_64)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description

These errors show up in the console after a long time of waiting for AJAX requests to complete:

```
Failed to load resource: the server responded with a status of 404 (Not Found)
Failed to load resource: the server responded with a status of 404 (Not Found)
```

The test instance is running at http://iiab-staging.eastus.cloudapp.azure.com/gitea/. I may take down this VM at any time with or without notice. Please let me know if I should leave it up.

## Screenshots

![Screenshot of Gitea test instance with the console panel open](https://user-images.githubusercontent.com/2768977/53928207-42e2c100-4057-11e9-8295-f8a3e9713cee.png)
![Screenshot of Gitea test instance with "Loading Heatmap..." throbber](https://user-images.githubusercontent.com/2768977/53928332-b4bb0a80-4057-11e9-9a97-d340f73756e3.png)

**Comment by apricote** [comment]
The requested URL is missing the prefix:

* Requested URL: http://iiab-staging.eastus.cloudapp.azure.com/api/v1/users/m-anish/heatmap
* Correct URL: http://iiab-staging.eastus.cloudapp.azure.com/gitea/api/v1/users/m-anish/heatmap

**Comment by veeara282** [comment]
I've fixed this by following the [reverse proxy instructions](https://docs.gitea.io/en-us/reverse-proxies/).
