### ISSUE TITLE
Link to issues in other repositories

### ISSUE THREAD

**Issue by exploide** [go-gitea/gitea#6264]
- Gitea version (or commit ref): 1.7.0

## Description

In a comment, when referencing an issue from an other repository, e.g. `https://git.example.org/MyOrg/wood/issues/119` it is rendered as `#119`, even when it links to the other repository, and not the one I'm currently commenting. This is a bit confusing.

GitHub solves this by rendering `wood/#119` in this case (or even `OtherOrg/wood/#119` when within another organisation). Would be great if Gitea adopts this.

Hopefully I correctly searched for duplicates. Have not found something like this.

**Comment by stani0502** [comment]
I tried but is not working in here https://try.gitea.io/stani0502/coba.
i tried commit and put message on commit to link to this issue https://try.gitea.io/stani0502/test/issues/1.
Is it the correct way to link it ?

Gitea Version: 8d01b98
