### ISSUE TITLE
Show project name in wiki page title

### ISSUE THREAD

**Issue by rixx** [go-gitea/gitea#6265]
Currently, the ``<title>`` of a wiki page is currently rendered as ``Page name – Gitea``. Adding the project name (``Page name – Project name – Gitea``) would be very helpful, otherwise you'll end up with five open "Home – Gitea" tabs on your hands.

**Comment by mrsdizzie** [comment]
Agree, title should include the specific project name at least (that information is more useful than the app name imo)

As a sort of work around, you could create a file at custom/templates/custom/header.tmpl with the following content and it will reset the page title as you've described.

```
<script>
document.title = "{{if .Title}}{{.Title}} - {{end}} {{if .Repository.Name}}{{.Repository.Name}} - {{end}}{{AppName}}";
</script>
```

If there is any idea of what would be a better default than exists now I'd be happy to create a pull request.

**Comment by rixx** [comment]
I think anything containing both the title and the project name is fine, so your suggestion would work well.

**Comment by lunny** [comment]
@mrsdizzie could you send PR for that.
