### ISSUE TITLE
Closing issues from commits comments

### ISSUE THREAD

**Issue by rvillablanca** [go-gitea/gitea#6266]
- Gitea version (or commit ref): 1.7.3
- Git version: 2.11.0
- Operating system: Debian 9.6/Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant

## Description

I am not being able to close some issues from commits messages such as fix #n, close #x, etc.
In the attached image you can see the issue must have been closed but it was not, I had to close it manually by pressing close button (check the seconds interval).

**Update**

We have test with other branch than master and the issue is not closed, but when using master the issue is closed. Is this default behaviour ? Can it be changed ?

## Screenshots

![image](https://user-images.githubusercontent.com/1508272/53964923-02bf2500-40cf-11e9-9c0a-be5f1970d6cb.png)

**Comment by CL-Jeremy** [comment]
https://github.com/go-gitea/gitea/blob/7780ea88907197abf6166bedc8b3021489444ea3/custom/conf/app.ini.sample#L40

**Comment by rvillablanca** [comment]
Thanks @CL-Jeremy

**Comment by rvillablanca** [comment]
I have enabled the option `DEFAULT_CLOSE_ISSUES_VIA_COMMITS_IN_ANY_BRANCH` but I think this is another problem. Our repository table in the mysql database doesn't have any column called `close_issues_via_commit_in_any_branch`.

![db](https://user-images.githubusercontent.com/1508272/54403608-6d63f800-46af-11e9-84f4-53fbcf46a9ec.png)

This could be the reason why I can't change this option in the repository settings.

![admin](https://user-images.githubusercontent.com/1508272/54403632-810f5e80-46af-11e9-9814-b91c9a01202f.png)

We have previously upgraded from version 1.7.2 to 1.7.3, then to version 1.7.4 but in no one the column is being created.

What could we be doing wrong ?

**Comment by CL-Jeremy** [comment]
Apologies for my carelessness. This option is fairly new and has not yet been merged.

In fact, the change in behavior you have encountered only came with 1.7.0, after https://github.com/go-gitea/gitea/pull/5622 was merged.

The aforementioned option for reverting this change wasn't introduced until https://github.com/go-gitea/gitea/pull/5992, which was merged but not yet shipped with any of the current releases. I'm also pretty new here so I can't say if you have to wait for the next major update, or maybe the next maintenance update (milestone: 1.8.0, but even the shipping of https://github.com/go-gitea/gitea/pull/5622 with 1.7.0 was supposed to be a "backport").

Hopefully this could be resolved timely.

**Comment by lafriks** [comment]
@CL-Jeremy option for closing issues on non-default branch will be supported only in 1.8.0

**Comment by lafriks** [comment]
fixed by #5992
