### ISSUE TITLE
Script contributor tests

### ISSUE THREAD

**Issue by stevegt** [go-gitea/gitea#6269]
We keep regressing in [CONTRIBUTING.md](https://github.com/go-gitea/gitea/blob/eaf9ded18201d8ad2587860ed98763ca040f0b71/CONTRIBUTING.md#testing-redux).  This time, it's starting to look like at least some contributors may not have been able to run drone tests since October 2018 (#6243).  The last time we touched this was back in #4053, #4055, #4070, and #4071. 

I think we need to:

- Script the drone testing that we're asking contributors to run, including fetching the right version of the drone cli tool, as well as the command line for running it. 
- Change the instructions in https://github.com/go-gitea/gitea/blob/master/CONTRIBUTING.md to ask people to just run that script. 

~~Both of these are handled by #6305.~~

**Comment by stevegt** [comment]
I've trimmed this issue; it originally included a suggestion that we run the script automatically at PR submission to ensure the script itself stays updated.  If that gets done it should probably be handled as a separate discussion and/or project.

**Comment by stevegt** [comment]
I've removed the script from PR #6305 -- if anyone is looking for it, you can grab a copy at https://github.com/stevegt/gitea/blob/drone-cli-bash/scripts/test-local.sh.  

The script only runs on Linux and should be replaced with a go version for portability; I'll work on that if nobody else gets to it first.

**Comment by stevegt** [comment]
Touching to make stale bot happy -- have been getting myself up to speed on go while working on another project; haven't forgotten about this.

**Comment by lunny** [comment]
Now we have used drone 1.x, so the `CONTRIBUTING.md` should also be updated again.

**Comment by wxiaoguang** [comment]
Now the development of Gitea doesn't need Drone, `make` works well.
