### ISSUE TITLE
Cannot manage my organisation "robots.txt"

### ISSUE THREAD

**Issue by tklein23** [go-gitea/gitea#6271]
I was able to create an organization "robots.txt", but now I cannot leave or manage it any more.

Reproducible on https://try.gitea.io/robots.txt :
* https://try.gitea.io/user/settings/organization in my profile > Manage Organizations
* When I click on the link for the organization, I get a 404 instead of the organization page.

Reproducible on https://codeberg.org/robots.txt in :
* Dashboard in the top navigation > Organization in the right widget > My Organizations
* When I click on the link for the organization, I get the real robot.txt, but not my organization.

**Comment by tklein23** [comment]
PS. And because I'm still in an org I cannot leave, I cannot even delete my user profile on try.gitea.org

**Comment by techknowlogick** [comment]
Can you go to https://codeberg.org/org/robots.txt/settings/delete to see if that works?

**Comment by tklein23** [comment]
Thanks, this worked.
