### ISSUE TITLE
2FA bypass when using API

### ISSUE THREAD

**Issue by ashimokawa** [go-gitea/gitea#6276]
- Gitea version (or commit ref): 1.7.3
- Git version: 2.20.1
- Operating system: Debian 9
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

When using gitnex (https://f-droid.org/fr/packages/org.mian.gitnex/) I can just log in to try.gitea.io by only typing in my password, even with 2FA enabled.

**Comment by techknowlogick** [comment]
@ashimokawa Please report all security reports to security@gitea.io

I will be deleting this issue so it isn't public.
