### ISSUE TITLE
Will PR merge in 1GB+ repo be slow?

### ISSUE THREAD

**Issue by yanOnGithub** [go-gitea/gitea#6287]
- Gitea version (or commit ref): 1.7.3
- Git version: git version 2.20.1.windows.1
- Operating system: windows 10 or 2012
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description

According to https://github.com/go-gitea/gitea/issues/6003#issuecomment-461850352
>When the Gitea Server performs a merge, it checks out your repository into a temporary location, runs git merge and then git pushes the new commit back into the main repository:

My repo is 1 GB+ in size. What is the expected run time of a PR and merge? Will it involve a 1GB+ git checkout? The server is probably on 7200rpm spinning disk. I have yet to try it.

**Comment by yanOnGithub** [comment]
I have just tested it. It took 39 sec to merge a PR on my 1GB repo. In windows resource monitor, I noticed disk activity to the gitea/data/tmp/local-repo/merge-XXXXXXX folder during the merge. The checkout is done lazily/on-demand. Can a clone or checkout be done in advance before the merge?

**Comment by yanOnGithub** [comment]
Ideally the run time of the merge should be proportional to the size of the change but not the size of the repo. I have a few GB of disk space to spare.

**Comment by zeripath** [comment]
@yanOnGithub I think there are a few more speed improvements possible with the merging of pull requests however, it should be much better than on older versions of gitea. 

Can I ask you to try to use the web editor or upload - the technique used in that code is almost the fastest I can think of without doing in memory index files.

**Comment by yanOnGithub** [comment]
#601 is closed in milestone 1.8.0. Let me try it after 2019 Mar 25

https://github.com/go-gitea/gitea/milestone/32?closed=1

**Comment by yanOnGithub** [comment]
What are web editor or upload?

> Can I ask you to try to use the web editor or upload - the technique used in that code is almost the fastest I can think of without doing in memory index files.

**Comment by yanOnGithub** [comment]
I have upgrade to 1.8.0. Merging PR completed in a few seconds. Thx.
