### ISSUE TITLE
AddCollaborator API return Unsupported Media Type

### ISSUE THREAD

**Issue by bclermont** [go-gitea/gitea#6294]
I tried with both Swagger UI and using go-sdk

```bash
curl -X PUT "http://git.example.com/api/v1/repos/xxx/yyy/collaborators/bruno?token=MYTOKEN" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"permission\": \"owner\"}"
```

```
[Macaron] 2019-03-10 03:33:08: Completed PUT /api/v1/repos/xxx/yyy/collaborators/bruno 415 Unsupported Media Type in 16.209798ms
```

**Comment by lunny** [comment]
Do you have permission to do that?

**Comment by bclermont** [comment]
I'm admin

and owner of the org:

![Screen Shot 2019-03-15 at 10 56 46](https://user-images.githubusercontent.com/474302/54405290-17c03780-4711-11e9-9eac-36f5d12ca1ae.png)

but... I suffer from https://github.com/go-gitea/go-sdk/issues/153 (might be unrelated)
