### ISSUE TITLE
Mark down image adds unexpected link

### ISSUE THREAD

**Issue by bjornbouetsmith** [go-gitea/gitea#6296]
- Gitea version (or commit ref): 1.5.3
- Git version:
- Operating system: Debian Stretch
- Database :
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes
  - [ ] No
  - [ ] Not relevant
https://try.gitea.io/bjornbouetsmith/test2/src/branch/master/README.md

## Description
When adding a image to a README.md gitea automatically adds a link to the same image, which makes it impossible to control what should happen when/if people clicks on the image. Just like the below image, which has been created with just the image markdown.

i.e.
![bjornbouetsmith](https://secure.gravatar.com/avatar/fd7ad6356aae22ddfb646fc86b0b576e?d=identicon)

I can see that it also happens here, so at least its consistent.

Expected result is that only the &lt;img&gt; tag is inserted and not a &lt;a href&gt;&lt;img&gt;&lt;/a&gt;

**Comment by zeripath** [comment]
Does using embedded html work?
