### ISSUE TITLE
[feature request - ui tweak] ssh key adding form UI usability

### ISSUE THREAD

**Issue by mateusza** [go-gitea/gitea#6298]
## Description
When adding new SSH key, key title should be automatically populated from public key comment field.

Additionally, in my personal opinion, swapping order of these two fields (making the key content textarea go above the title) would make it more intuitive. I often just paste the key into the first field available before realizing it's the "title" and the key should go into the other one.

The JS code:
```
var $sshKeyContent = $('#ssh-key-content')
$sshKeyContent.change(function() {
	var $sshKeyTitle = $('#ssh-key-title');
	if ( $sshKeyContent.val().length > 0 && $sshKeyTitle.val() === "" ){
		$sshKeyTitle.val( $sshKeyContent.val().trimRight().match( /^ssh-[^ ]* [^ ]* (.*)$/ )[1] );
	}
} );
```

## Screenshots

![image](https://user-images.githubusercontent.com/7002/54085765-cb0be380-4341-11e9-85fd-c2de68481b48.png)

**Comment by lunny** [comment]
Please send a PR to fix that.

**Comment by mateusza** [comment]
I just noticed this was already implemented 2 YEARS AGO in #950 but it only works when the key comment does not contain any spaces. I will fix that.

**Comment by Piraty** [comment]
please don't swap the textboxes. Since their purpose is clearly stated, it makes sense they way it is. And yes, the comment is inserted automatically into the "key name" field

**Comment by lunny** [comment]
This has been resolved.
