### ISSUE TITLE
admin create-user command should be idempotent

### ISSUE THREAD

**Issue by xythobuz** [go-gitea/gitea#6307]
Like other users (eg. in #2324) I'd like to install and configure gitea using ansible.
Thanks to #4948 the database can already be initialized before running gitea for the first time, so a user can be added.

However, I'd like to be able to repeatedly add the same user (resulting in no action), or use the create-user command to make a user admin that wasn't set as admin before. All this could be done with the existing create-user command interface.

Currently I'm getting the error:

    CreateUser: user already exists [ ... ]

When calling the command a second time with the same parameters. I'd like it to just pass.
This would greatly ease use of gitea with something like ansible.

Any plans on implementing this? Or hints on how I could do it myself?

**Comment by zeripath** [comment]
Ok you'd need to add an option here:

https://github.com/go-gitea/gitea/blob/master/cmd/admin.go#L43

Something like `--ignore-already-created` but more pithy.

Then adjust:

https://github.com/go-gitea/gitea/blob/master/cmd/admin.go#L345

To check if `models.IsErrUserAlreadyExist(err)` and if the option is set then return if not.

If you actually want to create or update then you should make another command that does that.
