### ISSUE TITLE
如何将gitea的派生分支更新到主干(gitea的仓库)的最新代码呢?

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#632]
如题, 找不到这个功能.

**Comment by tboerger** [comment]
If you can write only Chinese you should stay on QQ, here you got to write English because most of us don't know Chinese.

**Comment by xttianma** [comment]
补充,这个功能如有的话,
点击更新(来自主干)的时候,是否可以页面浏览合并的代码,如同合并请求那样?

**Comment by insionng** [comment]
表示管理方太矫情，中国诞生的项目不能说中文~
