### ISSUE TITLE
Label emojis aren't rendered in milestone view

### ISSUE THREAD

**Issue by Aragur** [go-gitea/gitea#6325]
- Gitea version (or commit ref): d7542bf
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes https://try.gitea.io/AragurDEV/LabelEmojiBug/milestone/400
## Description
Emojis in labels aren't rendering when using the milestone view.

## Screenshots

![Milestone View](https://user-images.githubusercontent.com/11004008/54353318-0107db00-4654-11e9-9f34-c650488e8ff6.png)
![Expected behavior](https://user-images.githubusercontent.com/11004008/54353329-08c77f80-4654-11e9-8b46-4bd130bb0b01.png)

**Comment by jolheiser** [comment]
Looks like this page also doesn't have the same UI changes made to the issues page.  
Thanks for catching this, I'll try to whip up a PR for it. 👍

**Comment by jolheiser** [comment]
Side-note, I cannot get to the posted milestone page. It seems that seeing the milestone page that lists all issues/PRs requires write access to either issues or pulls. Shouldn't it be read access to see the page?

https://github.com/go-gitea/gitea/blob/8fffb0616866cfe7a293b457d8703724666374cb/routers/routes/routes.go#L636-L638

**Comment by lunny** [comment]
@jolheiser I think that maybe another bug but after you change that to reqRepoIssuesOrPullsReader, you also need to change the UI to disable `Edit milestone` and change status of issues or pulls if user haven't reqRepoIssuesOrPullsWriter.

**Comment by jolheiser** [comment]
@lunny Sounds good. I'll open a new issue to address that, since I'd rather get the UI fixes in first for this issue.
