### ISSUE TITLE
Basic template - .SignedUser.Theme

### ISSUE THREAD

**Issue by DanielBaumert** [go-gitea/gitea#6326]
i copied the templates files from the repository folder to the `custom/templates` folder on my machine but now gitea throw me an error:

> template: base/head:152:21: executing "base/head" at <.SignedUser.Theme>: can't evaluate field Theme in type interface {}

https://github.com/go-gitea/gitea/blob/master/templates/base/head.tmpl#L152

**Comment by jolheiser** [comment]
User themes are part of 1.8+  
For 1.7.x you will need to download the template from the `release/v1.7` branch.
