### ISSUE TITLE
Incosistency when Repo already exists between create/migrate

### ISSUE THREAD

**Issue by bogdanpetrea** [go-gitea/gitea#6329]
- Gitea version (or commit ref): https://github.com/go-gitea/gitea/commit/d7542bfde3e46b5b11d2296e69f86a0e32ce9565
- Git version: 1.7.4
- Operating system: any
- Database: any
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant

## Description
There is an incosistency between handling an RepoAlreadyExists error between migrating a repo and creating a fresh one:
- [migrating repo](https://github.com/go-gitea/gitea/blob/7afe81f28e530c1c5aed1583654b3d772c368fa5/routers/api/v1/repo/repo.go#L412)
- [creating fresh repo](https://github.com/go-gitea/gitea/blob/7afe81f28e530c1c5aed1583654b3d772c368fa5/routers/api/v1/repo/repo.go#L232)

I think the migrating repo error response  (`409 Conflict`, `The repository with the same name already exists.`) should be used in both cases.

**Comment by wkulhanek** [comment]
This 409 is not documented on the /api/swagger. Could it be added, please?
