### ISSUE TITLE
LDAP client side certificate

### ISSUE THREAD

**Issue by mq2035** [go-gitea/gitea#6335]
question / feature request

My LDAP server (openldap) requires client side certificate (olcTLSVerifyClient=demand). Is there a way to configure LDAP authentication source with a dedicated certificate (and private key) and certificate truststore (for intermediate certificates)?

Since I can't set it up, as a result I have to use unencrypted connection to my LDAP server.
This feature (when implemented) would open road to SASL External authentication (bind to common name of the client certificate)

- Gitea version (or commit ref):1.7
- Operating system: docker
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite

**Comment by vishal-swarankar-sdl** [comment]
gitea gui/cli does not seem to have an option to pass on certs to it while adding an authentication source. 

is there a plan to support those use cases where ldap strictly demands clients to present the certificates?
