### ISSUE TITLE
gitea backup errors

### ISSUE THREAD

**Issue by mariuspana** [go-gitea/gitea#6337]
- Gitea version (or commit ref): 1.7.3
- Git version: 2.7.4
- Operating system: Ubuntu 16.04.6 LTS
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

After upgrading to 1.7.3 from 1.6.3 running gitea dump produces the following error:

$ ./gitea dump
2019/03/15 13:28:43 Creating tmp work dir: /tmp/gitea-dump-370916781
2019/03/15 13:28:43 Dumping local repositories.../gitea
2019/03/15 13:29:29 Dumping database...
2019/03/15 13:29:31 Failed to dump database: Error 1054: Unknown column 'approvals_whitelist_user_i_ds' in 'field list'

We can still dump the database using mysqldump however it was a convenience to use gitea dump directly. 

Thank you,
Marius

**Comment by jolheiser** [comment]
Has your database been updated since you updated Gitea?   
This should happen when you first start Gitea after updating, or alternatively by running `gitea -c path/to/app.ini migrate`

**Comment by mariuspana** [comment]
Thank you @jolheiser, I forgot to run `gitea migrate` and it seems that it did not run after the upgrade or it did not finish. I do not have logs to look through in this particular case to chase this further.
