### ISSUE TITLE
Add Search Box Everywhere

### ISSUE THREAD

**Issue by muellert** [go-gitea/gitea#6342]
- Gitea version (or commit ref):
- Git version: <= 1.7.4
- Operating system: Linux
- Database (use `[x]`):
  - [ X] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ X] No
  - [ ] Not relevant
- Log gist:

## Description

In my own gitea installation, which I initially started around gitea 1.3 or so, if I am clicking on "Explore" and then "Organizations", I don't get the search box above my repositories.
I've tried with a blank slate in a test installation, and it behaves the same way.

In "try.gitea.io", it works, though, there is a search box above the list of repositories with an additional drop-down menu for sorting. Also, the display is much more compact in try.gitea.io, but rather clunky on my local installations, irrespective of browser zoom settings.

I would like to have this search box for my own gitea as well, to speed up navigation, and having a way to adjust the display would also be nice (ie, having the search box and repo list starting at the top of the page).

**Comment by lunny** [comment]
Hi, organization repositories search has been implemented in recent some version.

**Comment by muellert** [comment]
Hi! Can you please tell me which version that might be? I have 1.7.4, and I thought that was the latest. I did my tests with 1.7.4.

**Comment by lunny** [comment]
That will be in v1.8

**Comment by kdumontnu** [comment]
I believe this is resolved.
