### ISSUE TITLE
GitNex - Android client for Gitea

### ISSUE THREAD

**Issue by mmarif4u** [go-gitea/gitea#6344]
Hi All,

I am happy to announce 1st stable release of GitNex v1.0.1. It is available in **F-droid**, **play store** and as **APK** to download. :tada: 

Download and more details
https://gitlab.com/mmarif4u/gitnex

Releases
https://gitlab.com/mmarif4u/gitnex/releases

**Comment by lafriks** [comment]
This should be added to external tool/integration section in doca

**Comment by mmarif4u** [comment]
I was thinking of something like this.
https://joinmastodon.org/apps

It's added already to the external tool/integration section.
https://docs.gitea.io/en-us/third-party-tools/

**Comment by techknowlogick** [comment]
Closing this issue as it has been added to thrd-party-tools.
