### ISSUE TITLE
Organization View Does Not Require Authentication

### ISSUE THREAD

**Issue by muellert** [go-gitea/gitea#6346]
- Gitea version (or commit ref): 1.7.4
- Git version:
- Operating system: Linux
- Database (use `[x]`):
  - [X ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

When accessing an URL for an organization, no authentication is required. This way, there is a potential information leak, as non-existent "organizations" will result in a 404.

The contained private repositories or project members are all inaccessible, though, but it would be nice if one could demand that accessing an organization also requires the user to be logged in, and possibly member of a certain group.

**Comment by lunny** [comment]
~That's by design for security consideration.~

**Comment by muellert** [comment]
Hmm? I would prefer to be able to hide organizations from unauthenticated views. How does showing them improve security?

**Comment by techknowlogick** [comment]
@muellert in 1.8.0 you can do exactly this, hide orgs from users who are unauthenticated

**Comment by lunny** [comment]
@muellert Forget my word, as @techknowlogick said, you could create private organizations when you upgrade to v1.8
