### ISSUE TITLE
New Migration Error Authentication failed: Clone: exit status 128

### ISSUE THREAD

**Issue by stani0502** [go-gitea/gitea#6347]
- Gitea version (or commit ref): 9f33aa6 
- Git version: 2.15.0.windows.1
- Operating system: Windows
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
When when i trying migrate my repository from gogs to gitea, i received this error

Authentication failed: Clone: exit status 128 - remote: invalid credentials fatal: Authentication failed for 'http://%3Ccredentials%3E@xx.xx.xxx.xxx:3000/xxxx/xxxxxx.git/'

## Screenshots
![image](https://user-images.githubusercontent.com/6171313/54491981-a98c9800-48fd-11e9-8e2f-34ca1d82867b.png)

**Comment by lunny** [comment]
Any detail logs? Is that password correct?

**Comment by stani0502** [comment]
This the log what i get

```
2019/03/17 21:22:12 [...routers/repo/http.go:169 HTTP()] [E] invalid credentials
2019/03/17 21:22:33 [...routers/repo/http.go:169 HTTP()] [E] invalid credentials
2019/03/17 21:22:39 [...routers/repo/http.go:169 HTTP()] [E] invalid credentials
2019/03/17 21:22:48 [...routers/repo/http.go:169 HTTP()] [E] invalid credentials
```

Yes I put valid user and password inside "Clone Authorization".

**Comment by lunny** [comment]
You account should not have `<` and `>`.

**Comment by stani0502** [comment]
> You account should not have `<` and `>`.

my account only contain alpha character only (A-Z, a-z), no special character.

**Comment by stani0502** [comment]
i think issue fix on version 1.8. but the migration is very hard from 1.7 to 1.8

**Comment by lunny** [comment]
What's your problem when upgrade from 1.7 to 1.8?

**Comment by stani0502** [comment]
I try copying the SQLite DB from version 1.7 to 1.8 the website cannot start, then i check the table structure is different. and then I redeploy fresh Gitea version 1.8 and register all user and repo manually

**Comment by lunny** [comment]
@stani0502 if you encountered problem when migrating from v1.7 to v1.8, please help to give some logs that we can resolve it.
