### ISSUE TITLE
Login with oauth2/OIDC of gitea.com as default

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#6352]
For federal gitea instances, I think login with an uniform account will be a good idea. So that  I would like to add an option on installation. This option will add https://gitea.com oauth2 to login source and default will be true.

**Comment by apricote** [comment]
How do you plan to generate Client Credentials for all new installations, and which account in Gitea.com will own the oAuth2 App?

**Comment by lunny** [comment]
@apricote haven't thought of that detail. Just notice that it maybe possible.

**Comment by jonasfranz** [comment]
@lunny This will require openid auto registration.

**Comment by lunny** [comment]
@jonasfranz yeah. So we should implement OpenID Provider at first? I think this maybe a step of a git federal.

**Comment by ailox** [comment]
To add a reference to one of the requirements:
OIDC auto registration is being worked on in this PR: https://github.com/go-gitea/gitea/pull/5123

**Comment by lunny** [comment]
Looks like it's impossible, so I close this one.
