### ISSUE TITLE
Failed to modify file after modifying warehouse name

### ISSUE THREAD

**Issue by duoduo007** [go-gitea/gitea#6358]
Gitea : 1.3.2
centos : 7.6
MySQL
![QQ图片20190318195652](https://user-images.githubusercontent.com/20541588/54528489-149aa500-49b8-11e9-9ba1-208e79914274.png)

When I push to gitea it was HTML 5
But when I modify the warehouse name HTML 50, modifying the file and deleting the created file will fail. I feel that the synchronization of modifying the warehouse name fails.

**Comment by lunny** [comment]
Could you reproduce that on https://try.gitea.io or https://gitea.com ?

**Comment by duoduo007** [comment]
[Unit]
Description=Gitea (Git with a cup of tea)
After=syslog.target
After=network.target
After=mysqld.service

[Service]
Type=simple
User=root
Group=root
ExecStart=/home/git/gitea web
Restart=always

[Install]
WantedBy=multi-user.target

I found that because of the use of svstemd boot mode, there is no problem with direct use of. / gitea boot now.

**Comment by lunny** [comment]
Did you configure your app.ini with absolute path?

**Comment by techknowlogick** [comment]
Closing this now, please feel to re-open if you have additional information.
