### ISSUE TITLE
Redundant info in schema

### ISSUE THREAD

**Issue by ethantkoenig** [go-gitea/gitea#636]
It seems that a lot of the tables in the schema store duplicate information.

For example, the `issue_user` table has an `issue_id` column, as well as `repo_id`, `milestone_id` and `is_closed` columns. However, the entries of the `repo_id`, `milestone_id` and `is_closed` columns can be determined using only `issue_id`, since that info is also stored in the `issue` table.

Is this redundancy intentional? The only benefit I can think of is faster reads (don't have to join), at the cost of slower writes, disk usage and cleanliness. Another downside of the redundancy is that it makes adding test fixtures more painful (if I change the `repo_id` of an issue, I need to remember to update the `issue_user` fixtures accordingly).

If there are pressing reasons for having duplicated information, then I'm fine leaving things as they are.  If there are not pressing reasons, I would be happy to revise the schema.

---

**Comment by andreynering** [comment]
When I made notifications I asked myself if I should delete that table. But I didn't know where it was used, so I kept.

I agree redundancy is bad most of the time. We just have to make sure we won't break anything.

Another thing we may discuss is if `mentions` and `assignees` (as examples) should be separated tables or if it should be kept on `issue_user` like today.

**Comment by tboerger** [comment]
I can just think that it got this redundancy because of the joins.

**Comment by ethantkoenig** [comment]
From looking at how we user the `IssueUser` struct, we could make the change without having to introduce any new joins.

**Comment by lunny** [comment]
seems closed by #638
