### ISSUE TITLE
Feature request: Template editor

### ISSUE THREAD

**Issue by elaine-jackson** [go-gitea/gitea#6360]
Unlike people who install from source, docker-compose users do not have a way to edit their templates (e.g. the german impressum, custom front page, etc). It'd be nice to have a simple template editor in the admin panel or even having templates accessible to compose users as another sort of config file. Thoughts?

**Comment by apricote** [comment]
(Using the `docker-compose` from the Docs)

The `custom` folder referenced in the "Customization" docs page is located at `/data/gitea` inside the offical Docker image: https://github.com/go-gitea/gitea/blob/96f1720d6907abd16641881d8f75177810ca29b2/Dockerfile#L52

The offical docker-compose file mounts the local folder `./gitea` to `/data`:

https://github.com/go-gitea/gitea/blob/96f1720d6907abd16641881d8f75177810ca29b2/docs/content/doc/installation/with-docker.en-us.md#L52-L53

That means you can place the templates in the local folder `./gitea/gitea/templates/footer.tmpl` (inside the container this file will have the path `/data/gitea/templates/footer.tmpl`)

* https://docs.gitea.io/en-us/install-with-docker/
* https://docs.gitea.io/en-us/customizing-gitea/

---

That said, your feature request for a Template Editor is still valid.

**Comment by irlcatgirl** [comment]
Did this change? Is it no longer valid or closed to inactivity?
