### ISSUE TITLE
UI for creating a new organisation is broken

### ISSUE THREAD

**Issue by adelowo** [go-gitea/gitea#6376]
- Gitea version (or commit ref): f7f2f12b68b16a2902c00e437fe3299f7ab97249
- Git version: `git version 2.17.2 (Apple Git-113)`
- Operating system: not relevant
- Database (use `[x]`): Not relevant
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes - Try to create a new organisation https://try.gitea.io/org/create
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Screenshots

<img width="1529" alt="Screenshot 2019-03-19 at 21 26 50" src="https://user-images.githubusercontent.com/12677701/54639500-cd7ee380-4a8d-11e9-8545-651ad33ba6f1.png">

**Comment by rakshith-ravi** [comment]
@lafriks shouldn't we close this issue now that the PR is merged?

And I noticed that the 1.8.0 milestone has nothing left once this is closed. So can we close this and create a new release or are we gonna test a little more?

**Comment by techknowlogick** [comment]
It's "fixed" however, perhaps we leave this open so that a more permanent solution could be found.

Edit: We just released RC2 of Gitea, so if you want to test it so we can release a final 1.8.0 that would be helpful

**Comment by zeripath** [comment]
@rakshith-ravi you really should take a look at my fix. It's really not a permanent solution and should only be considered a stopgap. I wouldn't really want this to stay in the code for too long - not least because I think it makes me look bad!

**Comment by rakshith-ravi** [comment]
Haha okay. I'll see if I (or someone from my team) can get that fixed up.  
But thanks for the fix anyway. The fact that we have a fix is good news. We'll get to cleaning it up asap.

Btw, @techknowlogick as per your request, I've migrated my company to 1.8.0-rc2 so I'll report any bugs that I find here. Will keep you guys posted.

**Comment by adelowo** [comment]
Can we close this as https://github.com/go-gitea/gitea/issues/6464 is now tracking the hack?

**Comment by techknowlogick** [comment]
@adelowo yup. Thanks for pointing that out.

Closing per above comment.
