### ISSUE TITLE
[Feature request] Pull requests: Allow to change target branch

### ISSUE THREAD

**Issue by 3l73** [go-gitea/gitea#6377]
When creating a new Pull request you decide which branch will be the target of the pull request. 

After creating it, it is not possible to change the target. 
In case it has to be change, you have to close the pull request including all notes etc. 

It would be a nice feature, if the user is able to change the target branch.

**Comment by richmahn** [comment]
Is there no other issue for this? I actually am working on this for my org's fork of Gitea. Trying to figure out how we can make this like GitHub and why it wasn't done like Github (currently it always just makes you do the PR to an org in the upstream)

**Comment by richmahn** [comment]
@lunny Have you seen any other issue like this?

**Comment by richmahn** [comment]
Oh wait, this is just to change the target once created. Read this wrong.
