### ISSUE TITLE
[Feature request] Pull requests: Test for code quality

### ISSUE THREAD

**Issue by 3l73** [go-gitea/gitea#6389]
During pull request the developer is able to check the code of the given changes.

Next to this kind of manually check it should be possible to configure additional automatic tests like linter or code sniffer.

These kind of tests could be registered globally und configured locally inside the repository/project.

A test could be executed on the local machine where the gitea service is located or remote by an REST-Request.

Inside the repository/project the owner could configure following behaviour
- the tests are deactivated (default)
- negative results treated as warnings
- negative results treated as errors and make a merge impossible until the issues are solved

The owner can exclude specific files or file patterns to be excluded from the test.

After the developer created a pull request or pushes changes inside an existing one, a timer starts to trigger the tests suits.

**Comment by jonasfranz** [comment]
That's already possible by using a CI like drone. There is in my opinion no need to run the linter on gitea itself.

**Comment by 3l73** [comment]
Question is, if there is the possibility to use the result in order to make a Pull request blocked until all issues are solved.

This request was not intended to integrate sniffer or linter itself in gitea, it is more in direction to integrate the service inside of a pull request.

**Comment by markusamshove** [comment]
Then it is a duplicate of #3588  :-)

**Comment by markusamshove** [comment]
Or #996 both kind of go into the same direction

**Comment by 3l73** [comment]
Thank for the hints on the other issues.

I will close this one.
