### ISSUE TITLE
push big file

### ISSUE THREAD

**Issue by kigkrazy** [go-gitea/gitea#6390]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
install gitea with follow docker-compose:
```
version: '2'

services:
  gitea:
    image: gitea/gitea:1.7.1
    container_name: gitea
    volumes:
      - /home/workspace/gitea:/data
    ports:
      - "9001:3000"
      - "9002:22"
    environment:
      - DISABLE_REGISTRATION=true
      - SHOW_REGISTRATION_BUTTON=false
    restart: always

```
push some big file ,but it show me this:
```
压缩对象中: 100% (26/26), 完成.
写入对象中: 100% (29/29), 145.38 MiB | 175.76 MiB/s, 完成.
Total 29 (delta 0), reused 0 (delta 0)
error: RPC failed; curl 55 Send failure: Broken pipe
fatal: The remote end hung up unexpectedly
fatal: The remote end hung up unexpectedly
Everything up-to-date
```
is the project too big?

**Comment by lunny** [comment]
Any logs from your server?
