### ISSUE TITLE
About locale zh-CN，letting "issue=工单" is troublesome.  简体中文本地化时将 issue 翻译成「工单」，这是令人困扰的

### ISSUE THREAD

**Issue by hnlxl** [go-gitea/gitea#6391]
- Gitea version (or commit ref):1.7.2, or `HEAD  b78cbbc` when creating this issue

> this question is about Chinese localization, so I will only use Chinese to describe it later.

## Description
中文三个本地化配置中关于 issue 的翻译如下：
-  gitea/options/locale/locale_zh-CN.ini：`issues=工单`  在626行. 
-  gitea/options/locale/locale_zh-HK.ini:：`issues=問題管理`  在287行. 
-  gitea/options/locale/locale_zh-TW.ini：`issues=問題`  在512行. 

「工单」这个意译基本上失败了，第一次看到界面的时候，我还以为工单是「Pull Request」。（「Pull Request 」翻译成了合并请求，感觉也有点过度意译了）非敏捷开发场景下，「issue」的实际含义可能是缺陷/Bug、疑问、讨论、待开发功能，敏捷开发场景下还可能是任务、改进、用例故事，几乎没有场景中回表示工单的含义。

我觉得还是翻译成`问题`比较好。实际上`问题`也是包含意译的效果的，简体中文语境下`问题`本来就是一个泛称的词，程序不运行（严重缺陷）、提示信息看不懂（疑问）、代码看着不工整（改进/讨论）、领导看着不爽（突发任务），都可以叫做问题。

## Screenshots
JIRA就是翻译成问题的，看起来并不违和。
![JIRA关于issue的翻译](https://user-images.githubusercontent.com/11850956/54671629-3f5c3900-4b31-11e9-83d3-2a8bb187f20f.png)

**Comment by hnlxl** [comment]
刚从培训资料里面发现的一个问题的专项定义：问题=目标与现状的差距。从这方面看，issue 翻译成问题是完全没问题的。

**Comment by lunny** [comment]
Please go to https://crowdin.com/translate/gitea/68/enus-zhcn to discuss that.
