### ISSUE TITLE
[API] Add type query param to filter issues and pr

### ISSUE THREAD

**Issue by mmarif4u** [go-gitea/gitea#6392]
Current issues API `/repos/{owner}/{repo}/issues` return both issues and pull requests.

Adding filter like type would enhance the output.

Issues:  
`/repos/{owner}/{repo}/issues?state=open&page=1&type=issues`

Pull requests:  
`/repos/{owner}/{repo}/issues?state=open&page=1&type=pulls`

**Comment by 6543** [comment]
works: https://try.gitea.io/api/swagger#/issue/issueListIssues
