### ISSUE TITLE
Upload LFS Objects from the browser

### ISSUE THREAD

**Issue by elaine-jackson** [go-gitea/gitea#6395]
This is a feature request. Let's offer a way to upload Git LFS objects from the web browser. Currently you have to do it from Git a browser upload of Git LFS objects would be convenient.

**Comment by zeripath** [comment]
Have you tried this since #5702 was merged?

If the file should be in the LFS as determined by the git attributes it will be stored in the LFS.

**Comment by zeripath** [comment]
I'm going to close this issue as this is possible since #5702
