### ISSUE TITLE
Intendation not shown correctly in file view

### ISSUE THREAD

**Issue by theAkito** [go-gitea/gitea#6407]
- Gitea version (or commit ref): b78cbbcaa25d03d07b77a010a26568182682c6f1
- Git version: 2.11.0
- Operating system: DietPi, based on Raspbian GNU/Linux 9 (stretch)
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No, can't register on try.gitea.io, returns code 500.
  - [ ] Not relevant
- Log gist:

## Description

Indentation is not shown correctly. If I remove the intendation at all and put the first character on the first place of the line, the intendation is entirely gone. If I press TAB to intend only once, then it shows up as if I pressed TAB and 3 times SPACE, in the file view, after commiting it.

## Screenshots

In edit mode, before commit.
![2019-03-21 18_19_44-Gitea-Bug_B](https://user-images.githubusercontent.com/26848976/54773379-be24a500-4c09-11e9-849a-b23a813331ac.png)

In file view, after commit.
![2019-03-21 18_19_44-Gitea-Bug_A](https://user-images.githubusercontent.com/26848976/54772004-c3342500-4c06-11e9-836f-8b40b05dba4f.png)

**Comment by lafriks** [comment]
Could be that there was already issue for this

**Comment by theAkito** [comment]
> 
> 
> Could be that there was already issue for this

Before opening an issue, I always search for an existing one. I didn't find any issue even remotely close to intendation.

**Comment by lafriks** [comment]
Could this be related to #5596 ?

**Comment by theAkito** [comment]
> 
> 
> Could this be related to #5596 ?

Seems reasonable, but I am not sure. Can I check somehow if they are related?
