### ISSUE TITLE
I want a team in organization can has all repository,not have to add it one by one

### ISSUE THREAD

**Issue by yashen** [go-gitea/gitea#6409]
## Description
In most of my case,all member has all repositories,just different permissions，
so I want a team in organization can has all repository,not have to add it one by one

**Comment by axifive** [comment]
Maybe for this case better add the second button: "Add all repositories"

**Comment by lunny** [comment]
@axifive I would like one checkbox to `all repositories` and don't need to really select all the repositories.

**Comment by axifive** [comment]
![Screenshot](https://user-images.githubusercontent.com/844963/54859489-c3274880-4d1e-11e9-9c9c-509ecea45f15.png)
@lunny, At this moment we have only search field without repositories list. So it seems to me that the checkbox conception doesn’t fit here.

**Comment by lunny** [comment]
@axifive When create a team, we can add a checkbox(default false) to enable all repositories or not. Then on this page's repositories, it will display like an Owner team. We only need add a column on team table maybe named `is_all_repositories` to do that.

**Comment by axifive** [comment]
@lunny Ok, I got it now.

**Comment by rlogiacco** [comment]
I also wish to see this implemented and I can try to give this a shot if anybody points me in the right direction....
