### ISSUE TITLE
Pull request ‘files changed’ page causes an error after renaming organization.

### ISSUE THREAD

**Issue by mokeyish** [go-gitea/gitea#6412]
Gitea should also modified the column `pull_request.head_user_name` with new team name.

- Gitea version (or commit ref):1.8
- Git version: 2.18
- Operating system: centos 7
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite

**Comment by lafriks** [comment]
Could you send relevant lines from gitea.log?

**Comment by mokeyish** [comment]
Sorry, I have lost the gitea.log. The reproduce steps is:1.create pull request;2.rename team;3.go to the 
`Files Changed` page of pull request will cause 500 error.     But If I modify the `pull_request.head_user_name` with new team name. will fix this error.

**Comment by lafriks** [comment]
Did you mean to rename organization?

**Comment by mokeyish** [comment]
yeah rename organization

**Comment by lunny** [comment]
I cannot reproduce this on the master branch.
