### ISSUE TITLE
How to Install in a Windows Container ?

### ISSUE THREAD

**Issue by FLeven** [go-gitea/gitea#6431]
I already tried to run it in a Windows Container, but gitea will just Exit without any error logged, git client was up and running inside the Container.

Is a windows Container supported at all and is there any guidance how to do it right?

**Comment by lunny** [comment]
Windows Container is not officially supported yet.

**Comment by FLeven** [comment]
Will this be supported anytime soon ?

**Comment by alexanderadam** [comment]
Probably only if there is some contributor who is willing to add a PR. But I guess for most users niche features like a Windows Container won't have any priority at all.

So my guess is, that no Windows Container support will be available unless _you_ add it.

**Comment by lafriks** [comment]
Also to build windows containers we would need windows server to run drone agent on
