### ISSUE TITLE
Can't update user dashboard

### ISSUE THREAD

**Issue by willy1920** [go-gitea/gitea#6433]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description
after revert git commit, user dashboard not updated but inside the project is updated
## Screenshots
![1](https://user-images.githubusercontent.com/21374073/54995900-7c756f00-4ffa-11e9-9f9d-32fde2b06fcd.PNG)
this picture was last commited when I was push to remote server
![2](https://user-images.githubusercontent.com/21374073/54995905-8303e680-4ffa-11e9-82d2-02ef848929fd.PNG)
this picture should be updated, but it's not updated

**Comment by lunny** [comment]
Is that repository on an organization?

**Comment by willy1920** [comment]
@lunny Yes
