### ISSUE TITLE
Error 500 when creating pull request

### ISSUE THREAD

**Issue by bkodre** [go-gitea/gitea#6460]
- Gitea version: 1.7.4
- Git version: 2.16.2.windows.1
- Operating system: Windows server 2012 R2
- Database :
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description
2019/03/28 13:21:58 [...routers/repo/pull.go:912 CompareAndPullRequestPost()] [E] PushToBaseRepo: Push: exit status 1 - warning: failed to restrict file handles (2)

**Comment by zeripath** [comment]
What version of git are you using?

https://stackoverflow.com/questions/50093771/git-clone-warning-failed-to-restrict-file-handles

**Comment by bkodre** [comment]
Git version is 2.16.2.windows.1
I will update git to the latest version.

**Comment by bkodre** [comment]
Now I have different error:

2019/03/29 09:39:15 [...routers/repo/pull.go:912 CompareAndPullRequestPost()] [E] PushToBaseRepo: Push: exit status 1 - error: cannot spawn hooks/pre-push: No such file or directory
error: waitpid for hooks/pre-push failed: No child processes

**Comment by zeripath** [comment]
I think you need to Regenerate hooks from the admin panel on Gitea

**Comment by bkodre** [comment]
I tried to regenerate hooks from command line (gitea admin regenerate hooks), but it didn't make any difference. I still get the same error.

**Comment by mrsdizzie** [comment]
pre-push is a client hook: I guess for the the obvious first -- does the pre-push hook exist in this repo locally and seem OK? If so, is sh.exe in your PATH? I think on newer versions of git for windows it is in ```C:\Program Files\Git\bin``` (or something similar depending on where git has been installed)

**Comment by bkodre** [comment]
pre-push file on gitea server was empty so i removed it and successfully created new pull request . 
It is ok to remove pre-push file in repository on gitea server?

On my local pc pre-push file is not empty, but has this code:
```
#!/bin/sh
command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/pre-push.\n"; exit 2; }
git lfs pre-push "$@"
```

**Comment by mrsdizzie** [comment]
OK great, and interesting.

Gitea itself doesn't create/manage/add ```pre-push``` hooks at all, so how an empty version would end up on the server isn't clear.

You might have a global pre-push hook on the server that is empty? That would get added to any new repos created by gitea, including when doing temporary clones for various tasks. Is it possible to check that? Perhaps the server user has git-lfs installed and it generated an empty hook somehow -- though again that isn't anything gitea itself manages. I've never used Windows or git-lfs so not very helpful beyond that :( If it repeats itself, I'd bet one of the two things above is the cause.

As for the local hook, presumably you need that or don't depending on git lfs use (as it says).

**Comment by bkodre** [comment]
Only one project on this gitea server has pre-push hook.

Server has git-lfs installed, could this be a problem?

Pull request on other projects are working fine.

**Comment by mrsdizzie** [comment]
@bkodre It wouldn't be possible for anyone here to be sure how that empty hook file got there, the above suggestions are just possibilities that you or your server/git administrator could look into if it is a reoccurring problem. In any case, it doesn't appear to be an issue with Gitea itself here but glad the particular issue with using Gitea was fixed.

**Comment by bkodre** [comment]
Deleting pre-push solved issue for me so i will close this issue.

 Thanks for your help.
