### ISSUE TITLE
Drone 1.0.0 yaml

### ISSUE THREAD

**Issue by techknowlogick** [go-gitea/gitea#6463]
Now that the Gitea org uses Drone 1.0.0 we should update the .drone.yml to align with the new format. The current one works, however due to the dropping of `groups` it takes longer to run.

I'm thinking we also have separate pipelines for each DB that gets tested, so that the services could be terminated sooner (which would decrease resource usage). If we do this we will probably have to have a build step in each pipeline though (a simple `TAGS="sqlite" make build` would likely be enough). Pipelines supports the `depends_on` param.

We also have an ARM server that can run docker builds to be able to publish arm builds of our docker image.

cc: @sapk (due to your ARM docker efforts)

**Comment by killua99** [comment]
Sorry if I might be confusing the TAGS thing.

But wouldn't be enough with something like this https://github.com/containous/traefik-library-image/blob/master/alpine/Dockerfile

**Comment by techknowlogick** [comment]
The dockerfile doesn't need to change as alpine is multi-arch, this issue is about updating Drone yaml so it connects makes use of our ARM agent.

**Comment by killua99** [comment]
Understood, I see so perhaps we have to split a bit the .drone.yml into multiple platform then.

https://docs.drone.io/user-guide/pipeline/multi-platform/ Something like this, I'm right? shall we create different issues for platforms ? or BD

**Comment by sapk** [comment]
The dockerfile is already multi-platform. With the multi-platform drone we just have to tag the image depneding on the host machine. My PR was generating various dockerfile based on the ref to enforce the base image link to an arch and use qemu to be able to run thoses arch on amd64.

**Comment by Kunde21** [comment]
It's a bit of bash ugliness, but this is the build script I use on all arches.  The key is to ensure that the arch is included in the docker tag, so everything can be pushed to the registry and a manifest generated for the multi-arch entry.

```bash
PATH=$PATH:/gopath/bin
GITEA_VERSION=v1.7.2

GODEBUG="netdns=go"
TAGS="bindata sqlite"

ARCH=$(case $(uname -m) in x86_64) echo "amd64"; ;; armv*) echo "arm"; ;; aarch64) echo "arm64"; ;; esac)
GITEA_VERSION=${DRONE_TAG-$GITEA_VERSION}

echo "$ARCH-$GITEA_VERSION" > .tags

apk update 
apk upgrade
apk add --no-cache git \
    bash \
    linux-pam \
    curl \
    make \
    tzdata \
    gcc \
    musl-dev \
    openssl \
    openssh \
    openssh-client \
    sqlite \
    sqlite-libs \
    wget ;

go get -u github.com/jteeuwen/go-bindata/...

wget https://github.com/go-gitea/gitea/archive/$GITEA_VERSION.tar.gz -O ../gitea.tar.gz
tar xf ../gitea.tar.gz --strip-components=1

go generate ./...

mkdir build_artifacts
go build -v -o ./build_artifacts/gitea -tags "$TAGS" -ldflags="-s -w -X 'main.Version=$GITEA_VERSION' -X 'main.Tags=$TAGS'"
mv docker ./build_artifacts/docker

./build_artifacts/gitea -h
```
