### ISSUE TITLE
Issue page tooltips and buttons broken on 1.7.5

### ISSUE THREAD

**Issue by bugreport0** [go-gitea/gitea#6469]
- Gitea version (or commit ref): 1.7.5
- Git version: 2.11.0
- Operating system: Linux arm6
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

Running Gitea 1.7.5 (`gitea-1.7.5-linux-arm-6`) on Linux and signing in with Safari 10.1.2 (10603.3.8) on OS X 10.10.5 I can not use the 'Start' or 'Add Time' Time Tracker buttons on the Issue page. Tooltips also don't show up. Other buttons on different pages may also be affected, I haven't looked much further yet.

This is a clear regression compared to Gitea 1.7.4 where tooltips show up and the buttons actually function correctly.

## Screenshots

No tooltip pops up and the button remains gray after clicking:

![no-tooltip-inactive-button](https://user-images.githubusercontent.com/32939607/55246224-103a7b80-5245-11e9-94d3-6a66ad246dcb.png)

**Comment by lunny** [comment]
Cannot reproduce this on my macOS Chrome.

**Comment by bugreport0** [comment]
Failed to reproduce myself right now, too. Maybe my browser had a stale cache. Closing now, will reopen if I manage to reproduce the issue.
