### ISSUE TITLE
Make webhooks follow redirects

### ISSUE THREAD

**Issue by h774211** [go-gitea/gitea#6472]
- Gitea version (or commit ref): all
- Git version: all
- Operating system: all
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description

I want Google Apps Script to handle webhooks but the script URL redirects to a one-time URL on another domain for security reasons and that causes an error.

**Comment by lunny** [comment]
I think webhook has the default setting of `http.Client` which will follow 10 times redirects.
