### ISSUE TITLE
illegal hardware instruction on arm-7

### ISSUE THREAD

**Issue by kenjican** [go-gitea/gitea#6476]
AMD64 version is ok on my ubuntu server.When I try to execute gitea-master-linux-arm7 web , system pop up the error message : illegal hardware instruction.

  CPU is Allwinner A20 ,I'm sure it is ARM V7 . The OS is armbian ubuntu 18.04.

   Anyone could solve this problem? Thanks

**Comment by lunny** [comment]
I think this is duplicated with #6367

**Comment by kenjican** [comment]
Thanks, I tried gitea-1.7.5-linux-arm-7 , it works. There should be bug in master branch.
