### ISSUE TITLE
Allow tags and 'HEAD' in compare endpoint

### ISSUE THREAD

**Issue by sonallux** [go-gitea/gitea#648]
- Gitea version (or commit ref): 1.0.1
- Git version: not relevant
- Operating system: not relevant
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist: not relevant

## Description
I am missing the option to also compare tags and 'HEAD' in the compare endpoint. Github allows there also tags and HEAD.

For example on github this is possible: https://github.com/go-gitea/gitea/compare/v1.0.0...HEAD

But with gitea it is not: https://try.gitea.io/gitea/gitea/compare/v1.0.0...HEAD

**Comment by wxd237** [comment]
I think compare between versionid and  'HEAD' is also need.such as `master...56b0228e72b9f62af41aa3e7c6b38f47424f5b47`

**Comment by ParticleCore** [comment]
Any update on this feature? It is the only thing that is preventing us from migrating to Gitea, we make heavy use of the tag compare for tracking changes between versions as well as presenting them in the changelogs.

**Comment by jsone-studios** [comment]
Closing, as this is fixed in 1.9.0 by #6991
