### ISSUE TITLE
Add email headers to suppress auto replies?

### ISSUE THREAD

**Issue by HenrikBengtsson** [go-gitea/gitea#6484]
Disclaimer: I know very little about the email protocol(s) out there.

I've implemented a poor-man's-email-to-Gitea API gateway that works alright. However, we're now getting auto replies (e.g. "I'm on vacation") to Gitea notifications from some users.  I started to look into how one could best detect and filter out such auto replies.  While doing this, I stumbled upon recommendations (e.g. [0], [1], and [2]) to set the email 'X-Auto-Response-Suppress' header field for _outgoing_ messages that you don't want to be auto-replied to.  AFAIU, at least Microsoft clients/servers look at these. 

Q1. Is it possible to configure the email _header_ fields for emails that Gitea sends out?

Q2. If not, if doable, may I propose that Gitea adds the `X-Auto-Response-Suppress` header field?

* \[0]: https://success.salesforce.com/ideaView?id=08730000000ZiXoAAK
* \[1]: https://www.jitbit.com/maxblog/18-detecting-outlook-autoreplyout-of-office-emails-and-x-auto-response-suppress-header/
* \[2]: https://it.cornell.edu/outlook2011mac-outlook2013win-outlook2016mac-outlook2016win-outlook-web/technical-details-auto-reply

**Comment by mrsdizzie** [comment]
It is not currently possible to configure the email header fields (that would be nice! but larger effort).

Seems reasonable to add this as a default header, github also uses ```X-Auto-Response-Suppress: All```

**Comment by HenrikBengtsson** [comment]
Wow, that was quick. Thank you all.

**Comment by mrsdizzie** [comment]
Thanks for suggestion!
