### ISSUE TITLE
Touch Drag - Drop Down Menus are interfering

### ISSUE THREAD

**Issue by modmew8** [go-gitea/gitea#6489]
- Gitea version (or commit ref): current try.gitea.io
- Git version: not relevant
- Operating system: not relevant
- Database (use `[x]`): not relevant
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

When navigating through the issue list on mobile and touchscreen devices you can't scroll when touching the dropdown menus. Instead, the touch down event leads to opening the dropdown menu, making it impossible to start a drag gesture around that area.

## Screenshots

![image](https://user-images.githubusercontent.com/6024058/55405657-da560980-555a-11e9-81f5-64c829a774cd.png)

Starting to drag in the red bordered area opens the dropdown menu making it impossible to touch there to start dragging down.

## Possible resolution?

I observed this issue on many touch input enabled applications, whenever they use the "touch down" event as a trigger. While this works well for mouse operation, this is impacting touch input heavily. Therefore lots of libraries support input gesture detection like "touched" or "clicked" - otherwise combine "touch down" and "touch up" events to detect "touched" and separate it from "touch drag".

Maybe the triggering event may be changed for these dropdown menues?

**Comment by wxiaoguang** [comment]
It has been fixed by  Fix Fomantic UI's touchstart fastclick, always use click for click events #23065
