### ISSUE TITLE
Error 500 when recreating a deleted branch

### ISSUE THREAD

**Issue by ngourdon** [go-gitea/gitea#6490]
- Gitea version (or commit ref): 1.4.0 (reproducible on https://try.gitea.io)
- Git version: 2.19.1
- Operating system: SLES 12
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

I cannot recreate a deleted branch with the same name in Gitea.
I get error page 500.

1. Create a branch from Gitea.
1. Delete the branch from Gitea.
1. Re-create the branch from Gitea.

Log :
2019/04/02 14:50:38 [...uters/repo/branch.go:235 CreateBranch()] [E] CreateNewBranch: CreateNewBranch: git checkout -b 2.0 1.0: exit status 128 - fatal: A branch named '2.0' already exists.

It seems gitea keeps a cache of the repo.

**Comment by balamut-andrey** [comment]
If you're using sqlite you need to build:
`TAGS="bindata sqlite sqlite_unlock_notify" make generate build`

**Comment by jolheiser** [comment]
Can you give a link to the https://try.gitea.io repository?
I cannot seem to reproduce.

Are your creating the branch from the web UI or locally and pushing?

**Comment by ngourdon** [comment]
all is done from the web UI.

At https://try.gitea.io/ngourdon/repo1 I can't re-create the branch 1.0

**Comment by jolheiser** [comment]
I'm not sure if I'm not following the same steps or not, but I cannot seem to reproduce still. 
I forked your repo and am using branch names `1.0` and `2.0`
![branches](https://user-images.githubusercontent.com/42128690/55421410-c8666d80-553e-11e9-8e21-80c81d28d5db.png)

**Comment by ngourdon** [comment]
Thanks for trying to reproduce.
I join an animated GIF to show the different steps

![gitea-branch](https://user-images.githubusercontent.com/31291059/55427045-75b0a400-5586-11e9-96fd-fa7b46018e28.gif)

**Comment by jolheiser** [comment]
I see! I was creating branches from commits, not directly from the dropdown. I will see if I can locate why that would cause an issue.

**Comment by mrsdizzie** [comment]
The UI says "Deleting a branch is permanent. It CANNOT be undone. Continue?" but clearly after you delete it, it shows up with a strikethrough its name on the branch page and you can undo that delete. ```branches/restore?branch_id=3&name=8``` suggests perhaps this message is wrong and it is intended for you to be able to recover deleted branches that are deleted this way (but no UI option to permanently delete them then I guess)
