### ISSUE TITLE
Corrupted indentation in "Files Changed" section of a pull request

### ISSUE THREAD

**Issue by gavlig** [go-gitea/gitea#6494]
- Gitea version (or commit ref): cd8cdbd 
- Git version: 2.21 on client (don't know what's on try.gitea but it's irrelevant)
- Operating system: linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (https://try.gitea.io/gavlig/indent_bug/pulls/1/files)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

Diff viewer(Files Changed) for pull requests corrupts indentation with "+-" signs. I don't know what would be a proper fix for this, but just removing them already solves the issue for me. I guess those can be added in the same column where the line numbers are. If that's an acceptable change i could make a PR for that

## Screenshots

![Screenshot from 2019-04-02 18-42-00](https://user-images.githubusercontent.com/668981/55420350-1bf4ad80-5577-11e9-9ecc-d146750b8f27.png)

Here i manually removed "+" signs for the code to become aligned

![Screenshot from 2019-04-02 18-42-26](https://user-images.githubusercontent.com/668981/55420354-1f883480-5577-11e9-8155-dd5b62b2a015.png)

**Comment by lafriks** [comment]
Viewing file also does ident same as in diff: https://try.gitea.io/gavlig/indent_bug/src/commit/eb951aee841acd700b2d51a6c296e592c1dedb34/main.cpp

**Comment by gavlig** [comment]
So the reason it's still indented is this issue: https://github.com/go-gitea/gitea/issues/5596
but it's a different bug
