### ISSUE TITLE
Attachment files don't display very well.

### ISSUE THREAD

**Issue by FalconWu2017** [go-gitea/gitea#6501]
1. For zip files show a meaningless big Icon。  
![image](https://user-images.githubusercontent.com/34147999/55449828-bb5d8300-55ff-11e9-9788-80b99534968c.png)   
I think it's better to display file names for ZIP files。 
2. For attachment images.do not need show attachement icon.    
![image](https://user-images.githubusercontent.com/34147999/55450018-7423c200-5600-11e9-82a7-419b327c7be5.png)   
**If only the user could customize the display style**

**Comment by bkraul** [comment]
Same here. It would be better to show a small file, perhaps one with a mime-related icon, and also show a file name. Maybe something leveraging fontAwesome.

**Comment by lunny** [comment]
closed by #11141
