### ISSUE TITLE
Time bug on mirror repository

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#6502]
Gitea's mirror repository display `three days after`.
![image](https://user-images.githubusercontent.com/81045/55486418-df03e600-565e-11e9-9dc5-344ab75f62f3.png)

Github display `just now` on the same file.
![image](https://user-images.githubusercontent.com/81045/55486494-fcd14b00-565e-11e9-8538-aade7f93ec14.png)

Repo link: https://gitea.com/lunny/go-astilectron-bundler

**Comment by mrsdizzie** [comment]
The date on that file at Github is April 6th, 2019 which *is* 3 days from today
<img width="197" alt="Screen Shot 2019-04-03 at 10 50 42 AM" src="https://user-images.githubusercontent.com/1669571/55488954-02974400-55ff-11e9-88da-ae3fff1e374f.png">

Magic ;)  If Gitea changed to say "just now", it would also probably still say "just now" for the next 3 days (and I bet GitHub does too). Also on this screen Github says "3 days from now" too:

 https://github.com/asticode/go-astilectron-bundler/blob/master/bundler.go

Gitea should maybe change to never show a time being "in the future" in this case, but the commit time is bad here and the code itself isn't doing anything wrong.

**Comment by lunny** [comment]
I think this has been resolved by #23988
