### ISSUE TITLE
attachments download url not encode

### ISSUE THREAD

**Issue by TimmyOVO** [go-gitea/gitea#6506]
- Gitea version (or commit ref): 1.8
- Git version: 2.19.1.windows
- Operating system: Windows10 1809
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (https://try.gitea.io/TimmyOVO/Test/releases)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
https://try.gitea.io/TimmyOVO/Test/releases/download/Test/test#abc.jpg
not working but when url encoded
https://try.gitea.io/TimmyOVO/Test/releases/download/Test/test%23abc.jpg
its work
...

## Screenshots
![PIC1](https://i.loli.net/2019/04/04/5ca5b772b4ac1.png)
![PIC2](https://i.loli.net/2019/04/04/5ca5b8729d975.png)

**Comment by zeripath** [comment]
_sigh_

The error is here:

https://github.com/go-gitea/gitea/blob/d3dc07f282936849897f861346777b47c8c388d3/templates/repo/release/list.tmpl#L80

There are multiple uses of EscapePound elsewhere in that file - I am very suspicious that some of these may not be correct, but I am not certain that they're wrong and would require looking at the source code in depth, which I cannot do here.

Paging @mrsdizzie: fancy a quick fix?

**Comment by zeripath** [comment]
@TimmyOVO if you want to send a PR, Changing line 80 of `templates/repo/release/list.tmpl` from:

```
 <a target="_blank" rel="noopener noreferrer" href="{{$.RepoLink}}/releases/download/{{$release.TagName}}/{{$attachment.Name}}"> 
```

to:

```
 <a target="_blank" rel="noopener noreferrer" href="{{$.RepoLink}}/releases/download/{{$release.TagName | PathEscape }}/{{$attachment.Name | PathEscape}}"> 
```

Although another option is to rationalise this endpoint so that it does a similar thing to endpoints that use `EscapePound` elsewhere.

**Comment by mrsdizzie** [comment]
Sure I'll make a PR for this (that suggestion above seems right, seems somebody just forgot to do any escaping on this part).
