### ISSUE TITLE
Problem with custom hooks gogs to gitea

### ISSUE THREAD

**Issue by araxy** [go-gitea/gitea#6509]
Hello,

I migrated from gogs to gitea.

I am in gitea version: 1.7.5

Everything seems to work. However, in my repository git I have custom_hooks folder with a post-receive file.

Now this is not displayed on gitea as on gogs, what to do ?

Thank you in advance

Regards,
Dylan

**Comment by jolheiser** [comment]
In your admin panel, running `Resynchronize pre-receive, update and post-receive hooks of all repositories.` might fix the issue.  
If you had anything in those existing files from Gogs, you may need to copy/paste the contents into the newly generated ones from Gitea.

**Comment by zeripath** [comment]
@araxy did that fix the issue?
