### ISSUE TITLE
Error: MergePullRequest()] [E] Merge: git push: error: src refspec develop does not match any.

### ISSUE THREAD

**Issue by OPSTime** [go-gitea/gitea#6517]
**Gitea version: Gitea version 1.7.5 built with go1.12.1 : bindata, sqlite, sqlite_unlock_notify**
**Git version: git version 1.8.3.1**
**Operating system: CentOS Linux release 7.6.1810 (Core) , 3.10.0-957.5.1.el7.x86_64**
**Database :  SQLite**

**Log :**

> 2019/04/05 11:45:20 [...routers/repo/pull.go:589 MergePullRequest()] [E] Merge: git push: error: src refspec develop does not match any.
> error: failed to push some refs to '/home/git/gitea-repositories/root/newtest.git'
> 
> 2019/04/05 11:45:20 [D] Template: status/500

**Description**
**create new branch develop**
```
git checkout master
git branch develop
git checkout develop
git push --set-upstream origin develop
echo 'develop' >develop
git add develop
git commit -m 'add develop'
git push

develop -> master，the merge was successful in the background
```

**create new branch develop_new**
```
git checkout develop
git branch develop_new
git checkout develop_new
git push --set-upstream origin develop_new
echo 'develop_new' >develop_new
git add develop_new
git commit -m 'add develop_new'
git push

develop_new -> develop, the merge failed in the background
```

**Comment by zeripath** [comment]
What kind of error do you get? I presume that when you write `develop -> master，the merge was successful in the background` you mean you did a pull request and merge?

**Comment by zeripath** [comment]
I am able to replicate on release/v1.7 but unable to duplicate on release/v1.8 and master.

@lyddragon can you replicate on any of the 1.8 rcs?
