### ISSUE TITLE
openid "installed" provider signup only?

### ISSUE THREAD

**Issue by schmitch** [go-gitea/gitea#6520]
currently I have created an OAuth2 application via the admin, however I know need to enable
```
[openid]
ENABLE_OPENID_SIGNIN = true
ENABLE_OPENID_SIGNUP = true
```

to allow self registration?
however wouldn't that expose my gitea instance to anybody that can provide a openid signup?

is there any way to actually configure gitea to only allow self registration for predefined openid / oauth2 providers?

**Comment by Jean-Baptiste-Lasselle** [comment]
> currently I have created an OAuth2 application via the admin, however I know need to enable
> 
> ```
> [openid]
> ENABLE_OPENID_SIGNIN = true
> ENABLE_OPENID_SIGNUP = true
> ```
> 
> to allow self registration?
> however wouldn't that expose my gitea instance to anybody that can provide a openid signup?
> 
> is there any way to actually configure gitea to only allow self registration for predefined openid / oauth2 providers?

Hi @schmitch You closed the issue, yet : did you manage to  spawn the configuration you desired ? (auto-registering OIDC auth allowed, but from limited providers ? )
