### ISSUE TITLE
Gitea not able to handle un-mergable branches' PR

### ISSUE THREAD

**Issue by rakshith-ravi** [go-gitea/gitea#6527]
- Gitea version (or commit ref): 1.8.0-rc2
- Git version: 2.17.1
- Operating system: Ubuntu 18.04.2
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL): https://try.gitea.io/rakshith-ravi/test/compare/master...fresh
  - [ ] No
  - [ ] Not relevant
- Log gist:
```
2019/04/06 12:48:31 [...routers/repo/pull.go:727 ParseCompareInfo()] [E] GetPullRequestInfo: GetMergeBase: exit status 1
2019/04/06 12:51:03 [...routers/repo/pull.go:727 ParseCompareInfo()] [E] GetPullRequestInfo: GetMergeBase: exit status 1
2019/04/06 12:51:13 [...routers/repo/pull.go:727 ParseCompareInfo()] [E] GetPullRequestInfo: GetMergeBase: exit status 1
```

## Description
When I create a new branch that's orphaned, then try to create a PR to the master branch, it gives a 500. Ideally, it should give a way to rebase it on top of master or at least show that "this is not possible because ......"

On a completely different note, how do you guys usually handle those kinds of PRs to master? Is there an "industry standard" way to handle it? Just curious. Also, is it possible to have gitea rebase an orphan branch on top of master or something like that? That would be really nice.

## Screenshots

Irrelevant

**Comment by zeripath** [comment]
Thank you so much @rakshith-ravi for this comprehensive test case. It allowed me to fix put a fix in very quickly.
