### ISSUE TITLE
Uploaded attachments of a release in a mirrored repo will never display if release tag already exists in an older commit

### ISSUE THREAD

**Issue by chotaire** [go-gitea/gitea#6535]
- Gitea version (or commit ref): 1.9.0+dev-61-g7ed65a98e
- Git version: 
- Operating system: Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

When mirroring e.g. a Github repository that has an older, not the current commit tagged v0.1 and a release created, no release will show up on the mirrored repository. So we're creating a release of v0.1 within the mirrored repository. This will work, but any uploaded attachments will never show. 

However, if the **current** commit is tagged v0.1 and then the repository gets mirrored and we're creating a release called v0.1 within the mirrored repository, uploaded attachments will finally show up.

There seems to be an issue with displaying release attachments when the release has the tag of an older (not the current) commit. This is a real issue as I can't seem to be able to create a release from a tag that has been set to an older commit (unlike on Github). 

Normal repositories might also be affected, but I have not seen it yet.

**Comment by chotaire** [comment]
I just checked, the uploaded file shows up in /archives so it simply doesn't get displayed in the UI.
I built gitea using the following howto: https://wiki.chotaire.net/linux-gitea

**Comment by chotaire** [comment]
I found the issue. In a mirrored repository, the directory **/releases** is never created. Doing so and re-uploading a release attachment will display the file.

**Comment by chotaire** [comment]
Finally I found what's causing this. Have fun with this one :(

**Comment by chotaire** [comment]
It turned out that I am also having random issues if there were any commits after tagging a release on the source repository. This is the only way I could reliably upload release attachments to a mirror repository:

- Tag a release on the source repository, do not commit anything else thereafter.
- Mirror the repository
- Create a release with the same name as the tag on the source repository and upload the release attachments right away during the creation
- After that you can continue committing on the source repository

**Comment by lunny** [comment]
I think this has been resolved. Let's close and feel free to reopen it if there is further information.
