### ISSUE TITLE
libcurl Windows - Unrecognized content encoding type

### ISSUE THREAD

**Issue by cataclysmic** [go-gitea/gitea#6537]
- Gitea version (or commit ref 
- Git version:  2.7.4
- Operating system: Ubuntu 16.04.
- Database (use `[x]`):
  - [ X ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ X ] No
  - [ ] Not relevant
- Log gist:

## Description

Trying to clone using git on Windows from gitea repository on Ubuntu Linux 16.04.
After a while of running I get the following error:

`Cloning into 'testprojekt'...`
`fatal: unable to access 'http://server/user/testprojekt.git/': Unrecognized content encoding type. libcurl understands deflate, gzip content encodings.`

Works fine when cloning from a Linux machine. Seems to be an issue wirh Content-Encoding and the windows curl client. Is there a way to configure this?

**Comment by lafriks** [comment]
can you reproduce this on try.gitea.io? what git client version are you using on windows?

**Comment by cataclysmic** [comment]
Cannot reproduce the error on try.gitea.io.
On Windows we tried two differnt clients: **git-gui version 0.21** based on **git version 2.15.1.windows.2**
and the current version of **Atom.io-IDE** with its integrate git system.

It must be some kind of server setting. But we are not using nginx or any different kind of reverse proxy. Cannot tell if that is used on try.gitea.io.

**Comment by lafriks** [comment]
There is reverse proxy in front of try.gitea.io

**Comment by cataclysmic** [comment]
Hm maybe that is handling and sending the correct header...
I'd be gratefull for any suggestion on how to configure it within gitea. Otherwise I might have to setup a reverse proxy here, too.

**Comment by lafriks** [comment]
You could try setting in `app.ini`:
```
[server]
ENABLE_GZIP = false
```

**Comment by cataclysmic** [comment]
Sadly didn't help. I will try install nginx reverse proxy tonight.
And will report if that solved the problem.

Thank you.

**Comment by cataclysmic** [comment]
Setup nginx reverse proxy but didn't.

I downloaded curl for Windows to investigate which response header is send.

Under nginx I get:
```
curl-7.64.1-win64-mingw\bin>curl.exe -I http://192.0.0.252
HTTP/1.1 200 OK
Server: nginx/1.10.3 (Ubuntu)
Date: Mon, 08 Apr 2019 15:08:09 GMT
Connection: keep-alive
Set-Cookie: lang=en-US; Path=/; Max-Age=2147483647
Set-Cookie: i_like_gitea=eb2ce913e0a2d3b6; Path=/; HttpOnly
Set-Cookie: _csrf=vdPYnpwxOsoDHnVvIEYbFqxMeDE6MTU1NDczNjA4OTYzOTUwMzQ3Mg%3D%3D; Path=/; Expires=Tue, 09 Apr 2019 15:08:09 GMT; HttpOnly
X-Frame-Options: SAMEORIGIN
```

Directly addressing gitea I get:
```
curl-7.64.1-win64-mingw\bin>curl.exe -H "Accept-Encoding: gzip" -I http://192.0.0.252:3000
HTTP/1.1 200 OK
Set-Cookie: lang=en-US; Path=/; Max-Age=2147483647
Set-Cookie: i_like_gitea=449f043214b6b590; Path=/; HttpOnly
Set-Cookie: _csrf=SDsS35dK1e50aZ2ftHtWxnr3nwQ6MTU1NDczNjEyNzU1NzUzNzU1Ng%3D%3D; Path=/; Expires=Tue, 09 Apr 2019 15:08:47 GMT; HttpOnly
X-Frame-Options: SAMEORIGIN
Date: Mon, 08 Apr 2019 15:08:47 GMT
```
There is no Content-Encoding tag sent. But I am completely out of the water here if that is necessary.

**Comment by lafriks** [comment]
It also did not work behind Nginx?

**Comment by cataclysmic** [comment]
Sadly no. I will investigate further. curl for Windows appears to requires some response like this
`Content-Encoding: gzip`
I will try to figure out whether it's possible to purely configure it in nginx.

**Comment by zeripath** [comment]
Your curl requests aren't testing the correct thing. You should try the project URL. In particular I assume that in your repository you have a blob that is compressed so if you can find that that's probably the correct thing to test. Git can be set to dial up the logging and I suggest you do that.

Which version of Gitea are you using? If earlier than 1.8 make sure you have `ENABLE_GZIP =false` set. This is unlikely to be the problem but it removes some uncertainties.

Tell me are you using an nginx proxy or other proxy service?

What's likely happening is that Gitea is not setting a content type for some compressed data or nginx is not happy with the content type we've set, so is looking at the data as it passed through and is setting a content type for us - git is then seeing that content type command and is interpreting it as saying that git should decompress the data. 

So look at your nginx configuration and see if you have some super aggressive compression policy or content-type detection policy. It might be that Gitea needs to ensure it always sends a header of application/octet-stream or some other header on these git endpoints to make nginx not try to content-type detect - but without knowing which one is failing it's very difficult.

If you're not using a proxy like Nginx I'll have another think. Initial googling turns up information suggesting content-type: UTF-8 to be the cause but I'm not certain we ever set that - if we do we should stop as it's wrong.

**Comment by cataclysmic** [comment]
Thanks for the ideas.

Using Gitea version 2.7.4.
I only installed nginx as reverse proxy after I got the same issue with connecting to gitea directly as I don't have the issue with try.gitea.io and that is behind nginx.

Currently there is no blob in the repository as it is a new repository initialized on gitea.

I also came across the `content-type: UTF-8` issue on the web and thought that I could see what gitea sends using curl but didn't get a content-type in the response.
Could you point out to me how to formulate the curl request to mimic a git request? 
Maybe I get a better idea of what's going on then.

**Comment by cataclysmic** [comment]
Dear programmers.
I found there error and it wasn't with gitea. I am so so sorry.
It had to do with our company proxy server which send bad headers for some requests.
We got it sorted.

I am very grateful for your great and quick support.
