### ISSUE TITLE
author "Gitea"

### ISSUE THREAD

**Issue by fawdlstty** [go-gitea/gitea#6539]
- Gitea version (or commit ref):c5ec66a
- Git version:2.7
- Operating system:centos 7.5 x64
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

I have write code and commit to gitea from two computer, all commit is mine, but another computer commit author "Gitea", I think it will be me too.

## Screenshots

![20190408164940](https://user-images.githubusercontent.com/7323999/55710974-5bf7dc80-5a1e-11e9-8108-9b6dd663ad5d.png)

**Comment by lafriks** [comment]
Could be that on one computer you have not correctly configured Author name/email? check:
```
git config --list
```

**Comment by fawdlstty** [comment]
thanks,
