### ISSUE TITLE
API to GET all changed files in Pull Request

### ISSUE THREAD

**Issue by romanresh** [go-gitea/gitea#654]
Make API for listing all changed files from a merge request like in GitHub:
https://developer.github.com/v3/pulls/#list-pull-requests-files

GET /repos/:owner/:repo/pulls/:number/files

**Comment by awwalker** [comment]
Is anyone currently working on this? If not I'd be happy to take a look

**Comment by lunny** [comment]
@awwalker Please send a PR.

**Comment by romanresh** [comment]
Hi, any news with this feature?

**Comment by awwalker** [comment]
@romanresh @lunny Sorry I haven't had time to work on this recently. Once school slows down again I may have time to revisit it but for now I won't be active on this.

**Comment by tonivj5** [comment]
:wink:

**Comment by xxxtonixxx** [comment]
:wink::wink:

**Comment by DAD713** [comment]
Was this ever implemented?

**Comment by lunny** [comment]
Not yet.

**Comment by patricematignon** [comment]
I see in the docs: https://developer.github.com/v3/pulls/#list-pull-requests-files

**Comment by waterdrop01** [comment]
In my case, being able to get the list of modified files will enable putting multiples micro-services in a single "mono-repo" on Gitea (one per folder), and still be able to handle CI/CD independently for each of the micro-services.

**Comment by jtackaberry** [comment]
I'm in the same boat as @waterdrop01.  I'm going to kludge my way around this, but an API in Gitea would enable a proper Drone extension to provide much cleaner integration.
