### ISSUE TITLE
gitea.service: Failed with result 'start-limit-hit'.

### ISSUE THREAD

**Issue by snelweg** [go-gitea/gitea#6540]
- Gitea version (or commit ref): 1.8 (gitea-1.8-linux-amd64
) upgrading from gitea-1.7-linux-amd64
Debian Linux xxxxx     2.6.32-042stab134.8 #1 SMP Fri Dec 7 17:16:09 MSK 2018 x86_64 GNU/Linux
gogs@xxxx:~/gitea$ cat /etc/debian_version
8.11

Wanted to upgrade from 1.7 to 1.8. But gitea 1.8 will not start on my machine:

`root@xxxxxx:~# systemctl status gitea
● gitea.service - Gitea (Git with a cup of tea)
   Loaded: loaded (/etc/systemd/system/gitea.service; enabled; vendor preset: enabled)
   Active: failed (Result: start-limit-hit) since Mon 2019-04-08 11:20:42 CEST; 4min 16s ago
  Process: 659 ExecStart=/home/gogs/gitea/gitea web (code=killed, signal=ABRT)
 Main PID: 659 (code=killed, signal=ABRT)

Apr 08 11:20:42 nas2.microkloon.nl systemd[1]: gitea.service: Unit entered failed state.
Apr 08 11:20:42 nas2.microkloon.nl systemd[1]: gitea.service: Failed with result 'signal'.
Apr 08 11:20:42 nas2.microkloon.nl systemd[1]: gitea.service: Service hold-off time over, scheduling restart.
Apr 08 11:20:42 nas2.microkloon.nl systemd[1]: Stopped Gitea (Git with a cup of tea).
Apr 08 11:20:42 nas2.microkloon.nl systemd[1]: gitea.service: Start request repeated too quickly.
Apr 08 11:20:42 nas2.microkloon.nl systemd[1]: Failed to start Gitea (Git with a cup of tea).
Apr 08 11:20:42 nas2.microkloon.nl systemd[1]: gitea.service: Unit entered failed state.
Apr 08 11:20:42 nas2.microkloon.nl systemd[1]: gitea.service: Failed with result 'start-limit-hit'.
`
When I switch back to 1.7 everything works again. What am I doing wrong?
(I once a long time ago used gogs, still using that username on my machine, but everything is Gitea now)

**Comment by lafriks** [comment]
Check gitea.log for errors

**Comment by snelweg** [comment]
> 
> 
> Check gitea.log for errors

gitea.log is not updated when using 1.8. So no messages about the error in the log file.

**Comment by snelweg** [comment]
Looks like I found the problem:

`gogs@nas2:~/gitea$ ./gitea
FATAL: kernel too old
Aborted
`

So no upgrading anymore for me then. Thanks.

**Comment by lafriks** [comment]
you can compile manually with older golang version (1.9). Check docs on how to do that.
