### ISSUE TITLE
"DEFAULT_ALLOW_CREATE_ORGANIZATION = false" is ignored during new user creation

### ISSUE THREAD

**Issue by igsol** [go-gitea/gitea#6542]
- Gitea version: 1.8.0-rc2
- Operating system: Linux
- Database:
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Not relevant

## Description
Precondition:
```ini
[service]
DEFAULT_ALLOW_CREATE_ORGANIZATION = false
```
After a brand new user is created he/she is able to create organization.

## Screenshots
1. ![image](https://user-images.githubusercontent.com/14091049/55725632-c60c8380-5a16-11e9-8d70-9ca5f55052c0.png)
2. ![image](https://user-images.githubusercontent.com/14091049/55725790-0d930f80-5a17-11e9-95da-6b07cf9fb746.png)

**Comment by lunny** [comment]
There is also another config item `DISABLE_REGULAR_ORG_CREATION` to control organization creation.

**Comment by adelowo** [comment]
Too many options ?

**Comment by lunny** [comment]
Yes, maybe only one is necessary.

**Comment by igsol** [comment]
@lunny , thanks for `[admin] DISABLE_REGULAR_ORG_CREATION = false`, I wasn't aware about it.
Despite the non obvious name, actually it's what I do really need.

**Comment by lafriks** [comment]
`DEFAULT_ALLOW_CREATE_ORGANIZATION` is used in ldap sync and user creation so this should be kept. Don't know about use case for disabling org creation completely

**Comment by zeripath** [comment]
#7017 will rewire it back in. Restoring it's functionality
