### ISSUE TITLE
Adding a user to an organization's team forces him/her to watch all repositories in the team repository list

### ISSUE THREAD

**Issue by CrustyApplesniffer** [go-gitea/gitea#6543]
- Gitea version (or commit ref): 1.7.1
- Git version: 2.10.2.windows.1
- Operating system: Windows 2008R2 Server 
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:

## Description
* Create an organization called ```Organization_Test```
* Create, in this organization, a team called ```Contributors``` that has write acces to issues
* Create the repository ```repo1``` in this organization and add it to the ```Contributors``` repository list 
![image](https://user-images.githubusercontent.com/37656975/55729450-77f78000-5a16-11e9-9c7b-28c3a8f9587a.png)

* Add the user ```pagaltier2``` to the organization and to the ```Contributors``` team
* Sign out and sign-in as pagaltier2

The repository ```repo1``` is under watching and, as pagaltier2, I'll receive all new issues notification
![image](https://user-images.githubusercontent.com/37656975/55729782-171c7780-5a17-11e9-9f06-99f590450318.png)

I think there should be an option to subscribe (or not) new users to repositories they have write access.

**Comment by lafriks** [comment]
Yes currently that is expected behavior

**Comment by sebastian-sauer** [comment]
For 1.8 there is a config option to disable the behaviour:

https://github.com/go-gitea/gitea/pull/5852
