### ISSUE TITLE
proper way to disable force push?

### ISSUE THREAD

**Issue by erpadmin** [go-gitea/gitea#6545]
Is this the proper way to global disable force pushing for gitea?
```
git config --system receive.denyNonFastForwards true
```

**Comment by lafriks** [comment]
That will disable force push on client side. To disable in gitea you need to use branch protection

**Comment by erpadmin** [comment]
The current design is not clear.

Enable Branch Protection description is "Prevent deletion and disable Git force pushing to the branch."  In practive this option requires Enable Push Whitelist is enabled and users added in order to do a fast-forward push.

Should the description be updated?  Or an independent option to specifically disable force pushing only be added?

**Comment by lunny** [comment]
@erpadmin Please send a PR to fix that doc.
