### ISSUE TITLE
Can not update LDAP with simple auth after creation

### ISSUE THREAD

**Issue by iddm** [go-gitea/gitea#6548]
After creating an LDAP authentication resource with simple authentication method I found several bugs:

1. During the creation, when I switch to `LDAP (simple auth)` there is still `Search Base` field there without red star above it. According to the documentation, this field should be hidden.
2. Even though creation goes okay, whenever I try to edit it, this `Search Base` field is shown and prevents me from submitting changes saying "This field must be filled".

- Gitea version d7542bf:
- Git version: not relevant
- Operating system: not relevant
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL (MariaDB)
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant

**Comment by vityafx** [comment]
This is really an annoying bug, guys. Right now many people who use the gitea and ldap + basic authentication are suffering from this user interface bug. This should be really simple to fix.

**Comment by ngourdon** [comment]
It seems the `Search Base` field is used with `LDAP (simple auth)` but it shouldn't be required. 
https://github.com/go-gitea/gitea/blob/master/modules/auth/ldap/ldap.go#L206
