### ISSUE TITLE
Markdown links are truncated (when URL contains number followed by slash)

### ISSUE THREAD

**Issue by nodiscc** [go-gitea/gitea#6551]
- Gitea version (or commit ref): 1.7.4
- Git version: 2.11.0-3
- Operating system: Debian 9 Stretch
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL - see below)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

When you paste an URL such as https://www.networkworld.com/article/3239677/the-osi-model-explained-how-to-understand-and-remember-the-7-layer-network-model.html in a Markdown file, and view the rendered markdown/html from the web interface, the generated link URL is truncated when a number followed by a slash is encountered (`7/the...`).

This happens for files in repositories and on wiki pages.

Examples:
 - https://try.gitea.io/nodiscc/test/wiki/Home
-  https://try.gitea.io/nodiscc/test/src/branch/master/README.md

I have looked for something similar at https://github.com/russross/blackfriday/issues but found nothing. Should I report it there?

## Screenshots

![a](https://user-images.githubusercontent.com/3950390/55823394-2112a900-5af1-11e9-9858-8c3d92ab4980.png)

**Comment by nodiscc** [comment]
Note that this URL is not affected: https://www.cisco.com/c/en/us/about/press/internet-protocol-journal/back-issues/table-contents-53/143-trill.html

**Comment by mrsdizzie** [comment]
This is fixed in master, but I think try.gitea.io hasn't been updated in a while for some reason. Particularly, this is initially fixed by #6445

**Comment by nodiscc** [comment]
Thank you, that was quick!

Duplicate of https://github.com/go-gitea/gitea/issues/4813 and fixed in master.
