### ISSUE TITLE
Incorrect word 'wyślik' in file locale_pl-PL.ini

### ISSUE THREAD

**Issue by maslykm** [go-gitea/gitea#6557]
Last char in polish word 'wyślik' (send) is incorrect. Correct word is 'wyślij'.
https://translate.google.pl/?hl=pl&tab=wT#view=home&op=translate&sl=pl&tl=en&text=wy%C5%9Blij%20plik
 
https://github.com/go-gitea/gitea/blob/7350e439bfa580d6693eac9848353e83e51a3525/options/locale/locale_pl-PL.ini#L581

**Comment by jolheiser** [comment]
Would you be able to suggest a fix on our [Crowdin project](https://crowdin.com/project/gitea)?
