### ISSUE TITLE
New Owner team member does not get watches for org repo's

### ISSUE THREAD

**Issue by RichieB2B** [go-gitea/gitea#656]
When adding a new member to an organisation Owner team, AddTeamMember() does not set watches for the new team member. Together with #653 that is pretty confusing behaviour and probably a bug.

**Comment by andreynering** [comment]
Since this is similar to https://github.com/go-gitea/gitea/issues/653, I think we can have a single issue for bugs in watching. Please edit https://github.com/go-gitea/gitea/issues/653 to add all bugs you know.
