### ISSUE TITLE
cannot delete uploaded file

### ISSUE THREAD

**Issue by Orefa** [go-gitea/gitea#6563]
- Gitea version (or commit ref):
gitea-1.7.5-windows-4.0-amd64.exe
- Git version:
git version 2.21.0.windows.1
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x ] No
  - [ ] Not relevant
- Log gist:

## Description
Please refer to the version of GitHub for release.
Attachments uploaded when the version is released are not viewable when editing and cannot be deleted. Server corresponding files are not deleted when the version is deleted
...

# THIS IS A DUPLICATE OF #677

**Comment by appleboy** [comment]
What kind of uploaded file do you want to delete?

**Comment by lunny** [comment]
files on issue

**Comment by Orefa** [comment]
> 
> 
> What kind of uploaded file do you want to delete?

files on Releases。
step 1：New Release ，upload some files，delete one file(this file was not deleted from the uploaded folder), Publish Release.
step 2：edit step 1 Release version，cannot view step 1 uploaded files，so，cannot delete uploaded files.

**Comment by bobemoe** [comment]
Looks like work is being done on this on #677?

You may be able to delete release attachment with the API if you have #6314  but i've not tried.

**Comment by 6543** [comment]
can we close this issue in fafour of #677?

@lunny
