### ISSUE TITLE
Make go1.11 the minimal version

### ISSUE THREAD

**Issue by coolaj86** [go-gitea/gitea#6568]
If we're willing to make go1.11 the minimal version I can make the build system much simpler and reduce the some of the build task times on drone by a factor of 10 (to the extent that much of the time is spent re-downloading dependencies).

Also, Windows support gets simpler.

The one thing that requires education is that people need to know that gitea CANNOT live in GOPATH when using `go.mod`.

In go1.13 the default behavior will change. I'm not sure if GOPATH will just be ignored or what they plan to do.

**Comment by sapk** [comment]
The main blocking problem is go-swagger currently not working outside GOPATH.

**Comment by solderjs** [comment]
@sapk Would it be okay to document that the minimum required version is go1.11 and iteratively make changes that don't break swagger (or errcheck)?

**Comment by sapk** [comment]
Personally, I am following golang recommendation of supporting the last two versions so no problem with that. But some os are not up to date on that and some user can be impacted by such choice. In fact, we are more in at minimum supporting the three last release without gcc (https://github.com/go-gitea/gitea/blob/master/.drone.yml#L59).

**Comment by lunny** [comment]
I think this has been resolved.
