### ISSUE TITLE
Can not see the reason of problems logging in using LDAP

### ISSUE THREAD

**Issue by iddm** [go-gitea/gitea#6571]
When I have set up my LDAP authentication resource and suddenly in the LDAP records there was an account with the email already registered in the gitea itself without ldap, I could not log in using the LDAP credentials and it was really hard to find the reason for this problem. I had to dig the logs and to find out this problem, however, gitea could simply say something like "This account's email conflicts with another one. Check the logs". This would help a little bit, but now it just says "Invalid user name and/or password" which is absolutely incorrect because actually both username and password **are** correct indeed.

- Gitea version (or commit ref): d7542bf
- Git version: not relevant
- Operating system: not relevant
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL (MariaDB)
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant

**Comment by lunny** [comment]
Email is uniqued on database, we only know your account/password is not matched I think.

**Comment by lunny** [comment]
Email is uniqued on database, we only know your account/password is not matched I think.

**Comment by vityafx** [comment]
> Email is uniqued on database, we only know your account/password is not matched I think.

I am not sure what does that mean. Do you mean you can't know what was the problem - mismatch of username and/or password or anything else? How do you log the error then? :)

**Comment by vityafx** [comment]
So sad this has not even beeen considered.
