### ISSUE TITLE
What's the equivalent of GOGS mailer SUBJECT_PREFIX

### ISSUE THREAD

**Issue by yanOnGithub** [go-gitea/gitea#6574]
- Gitea version (or commit ref): 1.8.0-rc2
- Git version:
- Operating system: windows
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

I want to prefix email subject with "[Myproject Gitea] "
https://gogs.io/docs/advanced/configuration_cheat_sheet

**Comment by lunny** [comment]
I think this is not implemented on Gitea.

**Comment by zeripath** [comment]
This wouldn't be too hard to implement, however I suspect it would be better to actually make our email templates customisable. (As I understand it they're only looked for under templates not custom?)

**Comment by lunny** [comment]
@zeripath right, the email templates cannot be customized currently.

**Comment by zeripath** [comment]
Ok, well TBH making them customisable like that is obviously better than yet another config flag in app.ini

I wonder what we would have to do to make them internationalised. I guess we would need to render them in context to the user who is being sent the mail and abstract out the data - that is probably just pass them the action object?

**Comment by zeripath** [comment]
Hmm. are we sure that mailer templates can't be customized?

https://github.com/go-gitea/gitea/blob/c168095afb80b7d17f7b7e34dc61eaa37b3ba0c2/modules/templates/dynamic.go#L96-L124

and 

https://github.com/go-gitea/gitea/blob/c168095afb80b7d17f7b7e34dc61eaa37b3ba0c2/modules/templates/static.go#L76-L110

would seem to imply that they should be able to be customized?

**Comment by zeripath** [comment]
Ah. I see this doesn't solve the issue as we're still not solving the subject line.
