### ISSUE TITLE
Opening empty repository -> error 500

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#6576]
I updated to 1.8. Repositories that were in Gitea, and no commit was pushed to, produce an error 500. When I commit something to those repositories, everything works again.

- Gitea version (or commit ref): 2551660
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

...

**Comment by zeripath** [comment]
Any chance you still have the logs for those 500s? 

Otherwise this is likely to be impossible to debug as I'm not certain how to go about replicating it.

**Comment by sbauer1799** [comment]
@zeripath What I found is the following error which belongs to this behaviour:

```
2019/04/03 16:47:25 [...ules/context/repo.go:580 func1()] [E] GetBranches: No branches in non-empty repository XXXXXXXXXXXXXXXX.git
2019/04/03 16:47:25 [D] Template: status/500
```

**Comment by zeripath** [comment]
This is quite interesting, because the only way this can happen is if the repository is actually empty according to git.

So is it that these were empty repositories which were previously marked as "bare" and have not migrated correctly as empty repositories into 1.8?

**Comment by sbauer1799** [comment]
@zeripath Those repositories were created with Gitea 1.7 and never used before. But I could open the repository page in the browser. After upgrading to Gitea 1.8 this was no longer possible, since I get the 500 error. Unfortunately I have no other old empty repository. The solution for me was to commit just something and Gitea worked again.

**Comment by zeripath** [comment]
Hmm. Were they created in an RC of 1.7? Basically the only way this should have happened is if your db was one of the ones that didn't properly undergo migration v78. 

If so I think this is probably a wontfix as it shouldn't happen in normal practice - although I do think that we should consider removing the is_empty columns from our tables and make our code robust enough to cope with situations like this. This sort of just redirect to 500 with an impenetrable error is very annoying behaviour which we should try to handle better.

Thank you for your report and continued use of Gitea.

**Comment by sbauer1799** [comment]
@zeripath I used the Docker image with 1.7 label from the beginning. I guess there is a good chance I started with a RC. Good to know this was already fixed. Thank you.

**Comment by alneo** [comment]
2019/08/19 15:39:03 ...ules/context/repo.go:594:func1() [E] GetBranches: No branches in non-empty repository XXXXXX
I did an update from 1.7.4 to 1.8.3 and 1.9.1 and in some repositories I get a 500 error
files exist along the path gitea-repositories
How to restore repositories?

**Comment by jackTheStark** [comment]
I am getting the same issue, I restored from linux-service v1.1.0 to docker v1.10.3.
