### ISSUE TITLE
Markdown ignores <a name="..."></a> anchors

### ISSUE THREAD

**Issue by rinnaz** [go-gitea/gitea#6577]
- Gitea version (or commit ref): 1.7.5
- Git version: 2.17.1
- Operating system: Ubuntu 18.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

Moved repo from github to gitea, and it seems that anchor points are not working.
Anchors are made that way:

```markdown
* [Introduction](#anchor-introduction)

# <a name="anchor-introduction"></a>Introduction
```

**Comment by cypriani** [comment]
The following works for me:

```
Table of contents
=================

* [Introduction](#introduction)

Introduction <a id="introduction"/>
============

Blah blah.
```

Please note I'm using `id`, not `name`.

**Comment by guillep2k** [comment]
There is a closed list of attributes allowed for each element. I'm surprised that `id` is in the list.

**Comment by zeripath** [comment]
The IDs come for free from the header elements automatically. Spaces are turned into hyphens.
