### ISSUE TITLE
Improve checkbox rendering

### ISSUE THREAD

**Issue by kenogo** [go-gitea/gitea#6578]
- Gitea version (or commit ref): 1.7.1
- Git version: any
- Operating system: any
- Database (use `[x]`):
  - [x] PostgreSQL
  - [x] MySQL
  - [x] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes ([provide example URL](https://try.gitea.io/kenogo/Checkbox-Rendering)):
  - [ ] No
  - [ ] Not relevant
- Log gist: not relevant

## Description

Anywhere in Gitea where markdown is rendered, a bullet is included in front of the checkbox. It's understandable, as the markdown syntax for checkboxes is `"- [ ]"` and leaving the `"-"` won't render a checkbox in Markdown. However, I think that handling it this way is very unusual, at least GitHub (see the checkbox above in this issue) and GitLab both ommit the bullet. Since the checkbox itself can work like a bullet, I feel that the current setup is rendundant.

I also think that checkboxes are rather hard to see right now and should take a darker color, although this was probably a conscious decision, while rendering the bullets was likely not.

## Screenshots

![Capture](https://user-images.githubusercontent.com/24212659/55945882-e96c4400-5c4b-11e9-9f83-40ca01175940.PNG)

**Comment by zeripath** [comment]
Already fixed.
