### ISSUE TITLE
Close/Reopen issue sends notification with the text of the issue

### ISSUE THREAD

**Issue by femaref** [go-gitea/gitea#6580]
- Gitea version (or commit ref): v1.8.0-rc2
- Git version:
- Operating system: devuan
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description

when closing/reopening an issue, the email doesn't say "Closed/Reopened issue #..." anymore, instead it sends the text of the issue.

**Comment by femaref** [comment]
how long do you estimate for this to be in rc or release?

**Comment by zeripath** [comment]
Ah it's currently not due to be backported. So is due to be in 1.9.

Could you comment on the pr #6581 explaining why it should be backported.
