### ISSUE TITLE
Repo setup as mirror, double quotes in pw for remote url causes error 500

### ISSUE THREAD

**Issue by ericbrumfield** [go-gitea/gitea#6582]
Running on Windows Server 2016 Standard.  I setup a new repo and configured it for mirroring.  Later I tried to change the update interval from 8h0m0s to 0h5m0s, after attempting this two or three times, I received an error 500 in gitea.

Digging through the gitea.log file, it stated GetTags exited status 128 - fatal: bad config line 10 in file ./config2019/04/11 05:55:19.  Failed to update mirror repository '': fatal bad config line 10 in file ./config2019/04/11 05:55:19

I opened the config to take a peek, the problem line is the url of my remote origin.  It did not end the double quotes.  I added the ending " to the line and the error went away, so somewhere in gitea it corrupted the config when attempting to updating repo settings and only changing the mirror interval.

After some digging, I believe it's a character issue in the credentials specified in the remote url. 
 The password I was given to use for the remote contains a double quote in it, so it seems it needs to be escaped so the url does not get munged.  I manually fiddled with the config and the web UI and could see the clone from url either truncate, or eventually gitea would surround it with ``, but then it would fail to sync.

**Comment by zeripath** [comment]
Hmm... OK looking at this it appears that the url is written here: 

https://github.com/go-gitea/gitea/blob/4ad65bb89b8fe5ede8bb6bbaea9b77af2c0cafd3/models/repo_mirror.go#L117-L126

which is called from

https://github.com/go-gitea/gitea/blob/4ad65bb89b8fe5ede8bb6bbaea9b77af2c0cafd3/routers/repo/setting.go#L43-L50

in particular this case statement:

https://github.com/go-gitea/gitea/blob/4ad65bb89b8fe5ede8bb6bbaea9b77af2c0cafd3/routers/repo/setting.go#L120-L155

**Comment by zeripath** [comment]
So the question is, should

https://github.com/go-gitea/gitea/blob/4ad65bb89b8fe5ede8bb6bbaea9b77af2c0cafd3/models/repo_mirror.go#L124

just always escape?

**Comment by zeripath** [comment]
Or should we even be doing this this way? Why aren't we using the `git remote` subcommands?

**Comment by zeripath** [comment]
@ericbrumfield What do you mean by end the double quotes? I'm not certain that when we write the file here we write any double quotes.

**Comment by zeripath** [comment]
The `"` in the password should be url-encoded as `%22` according to the URL RFC in which case we should be either barfing or encoding these ourselves.

**Comment by zeripath** [comment]
@ericbrumfield it looks like there's a major issue with the way we were managing this.

You have to url-escape the username and password components in URLs so putting a bare `"` in your password is invalid. It **must** be URL escaped to `%22`.

Now Gogs does a very naughty thing here arbitrarily escaping what it determines as the components without explaining that is what it is doing - if we want to be nice here we should split out the components and present them as separate fields but what we must not do is go around arbitrarily escaping parts of an URL. Either the user puts in a valid URL or not and if the URL is not valid we must barf. If you would like us to improve the UI here please open another issue but do not reference this issue.

PRs have been merged against 1.7, 1.8 and master to fix the underlying issue that causes the bad config. You should update your Gitea.

I can't fix the bad config files automatically. I very strongly recommend you look at the config files for those repositories and fix them by hand - there's no telling what go-ini has done to them and they could be **very** abnormal even if they don't throw problems. They will be at `gitea-repositories/username/repository.git/config` and the config files are described in https://git-scm.com/docs/git-config#_configuration_file . I am extremely sorry that I cannot fix this automatically or be more clear, but I say it again: You **must** check this and any mirrored config file yourself.

Finally I'm closing this issue - please do not reopen it.
