### ISSUE TITLE
option to hide site generation times

### ISSUE THREAD

**Issue by rugk** [go-gitea/gitea#659]
You are missing this from upstream: https://github.com/gogits/gogs/issues/3492

**Comment by willemvd** [comment]
It seems not to be in the docs on https://docs.gitea.io/en-us/config-cheat-sheet/

[other]
; Show time of template execution in the footer
SHOW_FOOTER_TEMPLATE_LOAD_TIME = false

**Comment by rugk** [comment]
Ah that's the issue. Indeed I only looked at the doc page.

**Comment by metalmatze** [comment]
@tboerger and I already discussed that once in private. Additionally we would like to drop the Go version too.

**Comment by tboerger** [comment]
We already got this option, so closing this issue.

**Comment by rugk** [comment]
> Additionally we would like to drop the Go version too.

AFAIK there is already an option for this.

**Comment by tboerger** [comment]
IMHO we should never display that. It just helps to find potential security issues

**Comment by lunny** [comment]
Anyone could send a PR to add SHOW_FOOTER_TEMPLATE_LOAD_TIME to cheatsheet?
