### ISSUE TITLE
[Feature Request] Add webhook for the matrix protocol

### ISSUE THREAD

**Issue by pinpox** [go-gitea/gitea#6590]
Under "Webhooks" in the admin or repo-settings page there are currently a few options for webhooks. It would be great to have one for matrix too, as it is probably not too hard to implement and would allow to forward to a lot of different protocols via the existing bridges too.

Is this someting you would consider merging? If so, I would give it a go and submit a pull requst.
EDIT: This might be another way of implementing this: https://t2bot.io/webhooks/

**Comment by savyajha** [comment]
Fwiw, this sounds really good. I don't have the chops to pull it off, but if it gets through I'd be massively thankful.

**Comment by binaryplease** [comment]
In the meantime, I'm building  a matrix bot to work around it. You can find it on my repos, but be warnend, it's not functional yet, work-in-progress.

**Comment by mrsdizzie** [comment]
Added in #10831
