### ISSUE TITLE
Move useless comments from source to Issues

### ISSUE THREAD

**Issue by bkcsoft** [go-gitea/gitea#66]
Running `make fixme todo` will print a nice list of `TODO/FIXME`-comments from source files. These should be moved to proper issues so that they can be 1) tracked and 2) people actually know about them :laughing: 

There are more instances of these comments throughout the code, and those should be moved as well.

Thoughts?

**Comment by strk** [comment]
The existence of `fixme` and  `todo` rules clearly makes those code comments NOT useless :)
If the issues creation/deletion can be automated then go for it, otherwise there's a risk of code and issues going out of sync.

I'd love for issues to be closer to code ..

**Comment by strk** [comment]
The existence of `fixme` and  `todo` rules clearly makes those code comments NOT useless :)
If the issues creation/deletion can be automated then go for it, otherwise there's a risk of code and issues going out of sync.

I'd love for issues to be closer to code ..

**Comment by strk** [comment]
The existence of `fixme` and  `todo` rules clearly makes those code comments NOT useless :)
If the issues creation/deletion can be automated then go for it, otherwise there's a risk of code and issues going out of sync.

I'd love for issues to be closer to code ..

**Comment by mrsdizzie** [comment]
Closing since we aren't going to remove these code comments

As an alternative to creating issues for each one there is this service which lists all TODO/fixme type comments for reference:

 https://www.tickgit.com/browse?repo=github.com/go-gitea/gitea

And also provides a link to open an issue from any particular comment
