### ISSUE TITLE
PR shows merge-able even though it wasn't

### ISSUE THREAD

**Issue by rakshith-ravi** [go-gitea/gitea#6603]
- Gitea version (or commit ref): 1.8.0-rc2
- Git version: 2.17.1
- Operating system: Ubuntu 18.04.2
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL): 
  - [x] No: Tried my best to reproduce it, but couldn't. Really sorry this time.
  - [ ] Not relevant
- Log gist:
```
fatal: could not set 'remote.1555169646517240158.url' to '/home/web/*******/repositories/software-team/**my-repo-name****.git'

2019/04/13 21:04:16 [...routers/repo/pull.go:593 MergePullRequest()] [E] Merge: git merge --no-ff --no-commit [/home/web/*******/data/tmp/local-repo/merge-730015198.git]: exec(660:PullRequest.Merge (git merge --no-ff --no-commit): /home/web/*********/data/tmp/local-repo/merge-730015198.git) failed: exit status 1(<nil>) stdout: Auto-merging CHANGELOG.md
CONFLICT (content): Merge conflict in CHANGELOG.md
Automatic merge failed; fix conflicts and then commit the result.
 stderr:  - 
2019/04/13 21:04:21 [...routers/repo/pull.go:593 MergePullRequest()] [E] Merge: git merge --no-ff --no-commit [/home/web/***************/data/tmp/local-repo/merge-294462215.git]: exec(676:PullRequest.Merge (git merge --no-ff --no-commit): /home/web/*************/data/tmp/local-repo/merge-294462215.git) failed: exit status 1(<nil>) stdout: Auto-merging CHANGELOG.md
CONFLICT (content): Merge conflict in CHANGELOG.md
Automatic merge failed; fix conflicts and then commit the result.
 stderr:  - 
```

## Description

So I got this very weird bug when trying to merge a PR to one of my repos. It showed me that the PR was merge-able and then threw this error when I tried to merge it (and gave me a 500). When I manually synchronised the branch with develop (the one I'm trying to merge it to), it worked well after that. Not sure how this happened. 

In case it matters, I got a "merge-able" PR first, then I made a small change to CHANGELOG.md and then it showed this, instead of telling me that it's no longer mergeable.

## Screenshots

Irrelevant

**Comment by supermar1010** [comment]
I have a similiar problem, we have PR which it says is mergable but if you click merge you get a 500.

Link to the PR: https://code.toold.xyz/Hochschule/WebAnClient/pulls/16

**Comment by MarkusAmshove** [comment]
Seems to be the opposite, but maybe same cause, as #6417

**Comment by rakshith-ravi** [comment]
Well, I personally haven't faced this issue again. I'll be closing this for now. For anyone else who stumbles upon this through google, please open a new issue.
