### ISSUE TITLE
Plugin system

### ISSUE THREAD

**Issue by shyim** [go-gitea/gitea#661]
- Gitea version (or commit ref):
- Git version:
- Operating system: macOs
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:

## Description

It were awesome if we had something like a plugin system. I made some changes to gitea to push notifications to Asana (Task-Managment system) and on any update i must merge the gitea repository with my patches and resolve the conflicts :(

**Comment by lunny** [comment]
You can send a PR to Gitea :)

**Comment by tboerger** [comment]
The 1.1.0 release is really not a target for a plugin system. Maybe you can tell us more about your Asana integration, possibly it's worth it to integrate it into the core until we get a plugin system built.

**Comment by shyim** [comment]
The user can insert a API Token in their user settings.
And if i add to my commit message "#asanaTaskID", will be a comment created on the asana ticket like
"New Commit: Datei Upload Plugin #227297458457220

http://host:3000/org/repo/commit/427ea88f10c0640f022a4e8ca83788d4120a5f16
"
So its possible to check easily commits in ticket system. This could be also extened to pull requests. 
I guess it could be a great basis for other task managment systems like trello/jira else

**Comment by ChangePlaces** [comment]
I fail to see how this is related to #1169 as this is about a general feature, whereas #1169 is a specific feature. poor show

**Comment by lunny** [comment]
There is also another issue #2222 duplicated with this but more discuss there. I will close this one and reopen #1169 .
