### ISSUE TITLE
Create subdirectory on install process

### ISSUE THREAD

**Issue by camlafit** [go-gitea/gitea#662]
- Gitea version (or commit ref): 1.0.1
- Can you reproduce the bug at https://try.gitea.io:
  - [x ] Not relevant
- Log gist:

## Description

During installation, if repository path is two level depth or more, gitea can't create repositories directory. A workaround is to create it before install process.

Should be usefull to allow a recursive mkdir to all directories creation during installation step.

**Comment by shyim** [comment]
Gitea creates currently recrusive. https://github.com/go-gitea/gitea/blob/master/routers/install.go#L183
Which os have you tested it?
I have tried on windows and it works correctly.

**Comment by tboerger** [comment]
Can somebody verify that it works on linux as expected?

**Comment by bkcsoft** [comment]
I would really like to see the logs for this, I'm guessing it's a permission-error.

**Comment by camlafit** [comment]
Hi

I can do a test tomorrow. I use 386 linux binary on jessie.

**Comment by Bwko** [comment]
@tboerger it works as expected on linux. The Gitea installer created this repository path `/home/bwko/multiple/levels/deep/some/more/levels/this/works`

**Comment by tboerger** [comment]
So maybe it's really just a permission issue?!

**Comment by camlafit** [comment]
Hi

Then I redo test following these options.

- binary path  : **/var/opt/gitea/gitea**
- execution : **su -l git -s /bin/bash -c "/var/opt/gitea/gitea web --config /var/opt/gitea/test/custom/conf/app.ini"**
- repositories path asked : **/var/opt/gitea/test/repositories**
- log path asked : **/var/opt/gitea/test/log**

version 1.0.1
debian jessie 386

And yes looks ok, probaly a mistake from mine, sorry. Maybe as presumed by @tboerger a permission issue on mine previous test.
