### ISSUE TITLE
Why recent commits of some repositories are not listed on the index page?

### ISSUE THREAD

**Issue by netjune** [go-gitea/gitea#6620]
- Gitea version (or commit ref): 8d40032
- Git version: 1.11.1
- Operating system: centos 7.5
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
Recent commits of some repositories are listed on the index page. Others are not listed. I don't known why. They are with the same setting just with diffrent name.

I can access the repositories and can push to all of them.

...

**Comment by lunny** [comment]
Which index page did you mean?

**Comment by netjune** [comment]
The default page after I login.

**Comment by netjune** [comment]
Commits of some repositories are not listed even though they are recent enough. Commits of these repositories may be never listed. But issues of these repositories of the same time are listed.

I can read and write the code of the repositories.

What setting may affect this?

**Comment by lunny** [comment]
Have you changed to the correct organization on top bar left side?

**Comment by netjune** [comment]
I switched to other organizations, then nothing was listed. 

The repositories are under one organization. But if I switch to the organization, nothing is listed.

I switch back to the default(my owner account), then some commits are listed as yesterday.

**Comment by qsodev** [comment]
I have the same issue for all repositories...no update on dashboard for a few months.

**Comment by lunny** [comment]
@qsodev any error messages on your log files?

**Comment by qsodev** [comment]
The only updates that I see on dashboard are created or transfered repositories. 
However each repository itself shows the correct commit history.
But also on the user profile page, the _last changed_ timestamp e.g. `Updated 2 months ago` under each repo in the list is incorrect.
It seems like it just stopped updating somethere in the past.

No Errors in log files.
`xorm.log` shows warnings and infos. I am not sure if this might be related to this issue.
For example, :
```
2019/01/23 20:15:48 [W] Table protected_branch has column id but struct has not related field
2019/01/23 20:15:48 [W] Table protected_branch has column repo_id but struct has not related field
2019/01/23 20:15:48 [W] Table protected_branch has column branch_name but struct has not related field
2019/01/23 20:15:48 [W] Table protected_branch has column can_push but struct has not related field
2019/01/23 20:15:48 [W] Table protected_branch has column enable_whitelist but struct has not related field
2019/01/23 20:15:48 [W] Table protected_branch has column whitelist_user_i_ds but struct has not related field
2019/01/23 20:15:48 [W] Table protected_branch has column whitelist_team_i_ds but struct has not related field
2019/01/23 20:15:48 [W] Table protected_branch has column enable_merge_whitelist but struct has not related field
2019/01/23 20:15:48 [W] Table protected_branch has column merge_whitelist_user_i_ds but struct has not related field
2019/01/23 20:15:48 [W] Table protected_branch has column merge_whitelist_team_i_ds but struct has not related field
2019/01/23 20:15:48 [W] Table protected_branch has column created_unix but struct has not related field
2019/01/23 20:15:48 [W] Table protected_branch has column updated_unix but struct has not related field
```
Or very often this:
```
2019/06/08 15:57:39 [I] PING DATABASE sqlite3
2019/06/08 15:57:40 [W] Table user Column diff_view_style db default is '''', struct default is ''
```

**Comment by lunny** [comment]
Could you try run `Resynchronize pre-receive, update and post-receive hooks of all repositories.` on admin panel and try again?

**Comment by qsodev** [comment]
That did not help... Still no update on dashboard.
But when I edit and commit a file in Gitea web editor, the dashboard gets updated.

**Comment by qsodev** [comment]
during investigation I found another issue which might be related:

- I create a repository empty without initializing files. 
- Then I clone create a file, commit and push to this repo.
- Gitea still shows the this repository as empty with the default info page, how to clone etc.

It seems that all git actions do no longer trigger the database or ui refreshes.

**Comment by lunny** [comment]
Check your `app.ini` and focus on `LOCAL_ROOT_URL` on `server` section.

**Comment by zeripath** [comment]
Two common causes come to mind:

* Is it possible you have your repositories on a noexec mounted filesystems? That would lead to Git not running hooks that are necessary to tell Gitea about pushes.
* If you're pushing using SSH you must login in as the Gitea user with a Gitea managed key. If you can SSH to a prompt using your key that's wrong.

**Comment by qsodev** [comment]
I think `LOCAL_ROOT_URL` is set correctly, because when I change it I get errors during pushes.
The repos are not mounted with noexec and I can run scripts with gitea user in the repo directory.
I tried to push with SSH and HTTPS. Both works fine. 
But still no update on dashboard or in the (no longer) "empty" repo.

**Comment by qsodev** [comment]
I just found out that for me this problem only affects the builtin ssh server.
When I don't use the internal ssh server then my dashboard gets updated.

**Comment by lafriks** [comment]
what version are you using?

**Comment by qsodev** [comment]
first it was <= 1.7 and recently I upgraded to 1.8.3

**Comment by qsodev** [comment]
I found out that it is related to systemd hardening.
These hardening options are present in gitea.service
```
CapabilityBoundingSet=
NoNewPrivileges=True
PrivateUsers=true
PrivateDevices=true
PrivateTmp=true
ProtectHome=true
ProtectSystem=strict
ProtectControlGroups=yes
ProtectKernelTunables=true
ProtectKernelModules=yes
ReadWritePaths=/etc/gitea/app.ini
LockPersonality=true
MemoryDenyWriteExecute=true
RestrictRealtime=true
SystemCallArchitectures=native
SystemCallFilter=@system-service
```
When I comment out `SystemCallFilter=@system-service`. Dashboard gets updated.
However removing this line is discouraged by package maintainers.
Does anyone have an idea how to fix this?

**Comment by yisiliang** [comment]
@

> I found out that it is related to systemd hardening.
> These hardening options are present in gitea.service
> 
> ```
> CapabilityBoundingSet=
> NoNewPrivileges=True
> PrivateUsers=true
> PrivateDevices=true
> PrivateTmp=true
> ProtectHome=true
> ProtectSystem=strict
> ProtectControlGroups=yes
> ProtectKernelTunables=true
> ProtectKernelModules=yes
> ReadWritePaths=/etc/gitea/app.ini
> LockPersonality=true
> MemoryDenyWriteExecute=true
> RestrictRealtime=true
> SystemCallArchitectures=native
> SystemCallFilter=@system-service
> ```
> 
> When I comment out `SystemCallFilter=@system-service`. Dashboard gets updated.
> However removing this line is discouraged by package maintainers.
> Does anyone have an idea how to fix this?

I have the same issue.
But my GITEA is running in Docker.

**Comment by yisiliang** [comment]
> @
> 
> > I found out that it is related to systemd hardening.
> > These hardening options are present in gitea.service
> > ```
> > CapabilityBoundingSet=
> > NoNewPrivileges=True
> > PrivateUsers=true
> > PrivateDevices=true
> > PrivateTmp=true
> > ProtectHome=true
> > ProtectSystem=strict
> > ProtectControlGroups=yes
> > ProtectKernelTunables=true
> > ProtectKernelModules=yes
> > ReadWritePaths=/etc/gitea/app.ini
> > LockPersonality=true
> > MemoryDenyWriteExecute=true
> > RestrictRealtime=true
> > SystemCallArchitectures=native
> > SystemCallFilter=@system-service
> > ```
> > 
> > 
> > When I comment out `SystemCallFilter=@system-service`. Dashboard gets updated.
> > However removing this line is discouraged by package maintainers.
> > Does anyone have an idea how to fix this?
> 
> I have the same issue.
> But my GITEA is running in Docker.

after "Resynchronize pre-receive, update and post-receive hooks of all repositories. ", seems it is ok now.

**Comment by ltGuillaume** [comment]
Please see if https://github.com/go-gitea/gitea/issues/9792#issuecomment-691291999 solves the issue for you as well.
