### ISSUE TITLE
Tags style tweaks

### ISSUE THREAD

**Issue by MayMeow** [go-gitea/gitea#6621]
- Gitea version (or commit ref): 1.8.0+rc3 / 1.9.0-dev
- Git version: 1.12.4
- Operating system:
- Database (use `[x]`):
  - [x] PostgreSQL
  - [x] MySQL
  - [x] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

Tags are missing bottom margin in project list.
Add new class to tags div that ensure this the list will have bottom margin.
Make Tags smaller (and / or maybe change style of labels) See example bellow

## Screenshots

1. Current Situation

![chrome_2019-04-15_08-37-42](https://user-images.githubusercontent.com/3164256/56112292-de225c80-5f5a-11e9-91d4-a621493f97cd.png)

2. Update style:

![chrome_2019-04-15_08-37-22](https://user-images.githubusercontent.com/3164256/56112283-d662b800-5f5a-11e9-81f7-061fb817a089.png)

**Comment by lunny** [comment]
Could you send a PR to fix that?

**Comment by Ha-yoon** [comment]
yes i can

**Comment by MayMeow** [comment]
Yes i can.

**Comment by techknowlogick** [comment]
Thanks for PR 😄 

Closing this issue as PR has been merged.
