### ISSUE TITLE
[Bug Report] OAuth Access Token endpoint does not support JSON

### ISSUE THREAD

**Issue by meteorlxy** [go-gitea/gitea#6624]
- Gitea version (or commit ref): https://try.gitea.io
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant

## Description

According to the [docs](https://docs.gitea.io/en-us/oauth2-provider/):

![image](https://user-images.githubusercontent.com/18205362/56112899-f2804c80-5f8e-11e9-952d-0d975969d3db.png)

### OK with `application/x-www-form-urlencoded`

![image](https://user-images.githubusercontent.com/18205362/56113065-57d43d80-5f8f-11e9-9b0f-455bfa2d78bc.png)

### Error with `application/json`

![image](https://user-images.githubusercontent.com/18205362/56113180-ae417c00-5f8f-11e9-9f9f-ed4bca654fa0.png)

**Comment by meteorlxy** [comment]
Ping for help @jonasfranz 😄

**Comment by jonasfranz** [comment]
@meteorlxy Thank you for reporting this bug. I've created a pull request to fix it: #6627
