### ISSUE TITLE
Error getting comments by API

### ISSUE THREAD

**Issue by jzrebiec** [go-gitea/gitea#663]
- Gitea version (or commit ref): master build from 12.01.2017
- Git version: 2.7.4
- Operating system: Kubuntu 16.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:
[Macaron] 2017-01-13 14:04:39: Started GET /api/v1/repos/:user/:repo/issues/comments?page=1&per_page=100 for 127.0.0.1
2017/01/13 14:04:39 [D] Session ID: b524ae117632e0ec
2017/01/13 14:04:39 [D] CSRF Token: ywVMzeEmcATmyrrK5W-2pdg01ZM6MTQ4NDMxMjY3OTgxNDYzMDM5MQ==
[Macaron] 2017-01-13 14:04:39: Completed /api/v1/repos/:user/:repo/issues/comments?page=1&per_page=100 500 Internal Server Error in 26.69987ms
2017/01/13 14:04:39 [...epo/issue_comment.go:52 ListRepoIssueComments()] [E] GetCommentsByRepoIDSince: Error 1052: Column 'created_unix' in order clause is ambiguous
## Description

When using url: /api/v1/repos/:user/:repo/issues/comments
I am getting error:
{"message":"Error 1052: Column 'created_unix' in order clause is ambiguous","url":"https://godoc.org/github.com/go-gitea/go-sdk/gitea"}
...

**Comment by ethantkoenig** [comment]
I get the same error with PostgreSQL. I believe it's because both the `issue` and `comment` tables have a `created_unix` column.

**Comment by ethantkoenig** [comment]
@jzrebiec I've created a PR (#665) which fixes the problem for me. Can you confirm that it works for you as well?
