### ISSUE TITLE
Close/Reopen issue improvements

### ISSUE THREAD

**Issue by femaref** [go-gitea/gitea#6630]
- Gitea version (or commit ref): 1.8.0-rc3
- Git version:
- Operating system: devuan
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description

Two followups to #6580:

- the sender of the email is the one who created the issue, not closed the issue
- the subject should contain Closed/Reopened, so it's immediately visible.

**Comment by mrsdizzie** [comment]
Sender name issue is fixed and mail subjects are customizable via templates: https://docs.gitea.io/en-us/mail-templates/
