### ISSUE TITLE
1.7.6 release unusual contents in .sha256 file

### ISSUE THREAD

**Issue by evanchiu** [go-gitea/gitea#6646]
- Gitea version (or commit ref): 1.7.6
- Git version: 2.15.1 (Apple Git-101)
- Operating system: macOS Mojave 10.14.4 (18E226)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

The contents of https://dl.gitea.io/gitea/1.7.6/gitea-1.7.6-linux-amd64.sha256 don't match the standard convention of gitea-<version>-linux-amd64:

```
curl https://dl.gitea.io/gitea/1.7.4/gitea-1.7.4-linux-amd64.sha256
195c6024906a8f1a08ac3b586144984e053d20628b770aa8976e2f4d40253335  gitea-1.7.4-linux-amd64
curl https://dl.gitea.io/gitea/1.7.5/gitea-1.7.5-linux-amd64.sha256
2afef775cb7acb56484630171dae4d0c0498d0a3f1a5e3f810deb7879fbe2ed4  gitea-1.7.5-linux-amd64
curl https://dl.gitea.io/gitea/1.7.6/gitea-1.7.6-linux-amd64.sha256
38ce49dd93e9b047d06b1601e36a1e62479052a9301992a83eb5fffd9428d12e  gitea-master-linux-amd64
```

This is probably related to the irregular build process mentioned in #6600, and similar to the issue in #6614

**Comment by lunny** [comment]
This should be a duplicated with #6600 and resolved by #6609
