### ISSUE TITLE
Support better search engines for indexing (elasticsearch, mysql/pgsql/sqlite fulltext or something else)

### ISSUE THREAD

**Issue by vitalif** [go-gitea/gitea#6648]
- Gitea 1.7.6
- Git 2.11
- Operating system: Linux
- Database: all
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Not relevant

## Description

Bleve indexer is very inefficient: it uses a lot of disk space and a lot of memory. Also it keeps all index mmap'ed all the time which makes Gitea crash when I enable it on my 32-bit server with just 1.4gb of git repositories after generating 2GB of index.

There exist a lot of more popular and efficient full-text search engines, starting with ones built into Postgres / MySQL / SQLite (MySQL's one is not the most efficient one, but it still works). Then there's Elasticsearch and so on. Index sizes are much smaller in Elasticsearch and Postgres (compared to size of indexed data).

**Comment by adamcavendish** [comment]
Hi I've also seen in the configuration files that there're two types of ISSUE_INDEXER_TYPE available. What is the differences between "db" and "bleve"? Is it safe to change from "bleve" into "db" in config files and then a simple restart?

**Comment by lunny** [comment]
@adamcavendish db will use database's `Like` to search issues. Your operations are safe. But both types are not inefficient.

**Comment by alexanderadam** [comment]
I guess this could fix things like #5694 #5277 #3448 and #2967 if implemented properly.

**Comment by jeffliu27** [comment]
Would love to help with the implementation for the elasticsearch code search backend! @lunny @jeblair

**Comment by rcarmo** [comment]
Just a note that SQLite has FTS indexing, and that it is quite efficient (I have gigabytes of plain text files indexed that way)

**Comment by rcarmo** [comment]
So no built-in, single binary SQLite search?

**Comment by lunny** [comment]
@rcarmo issues index support built-in SQLite search, code index support built-in bleve search.
