### ISSUE TITLE
Faster code indexing with git cat-file --batch

### ISSUE THREAD

**Issue by vitalif** [go-gitea/gitea#6649]
- Gitea 1.7.6
- Git 2.11
- Operating system: Linux

## Description

Gitea currently calls `git cat-file` two times for each indexed blob which makes indexing process very slow. There is a "batch" feature in Git: `git cat-file --batch` reads blob IDs line by line from STDIN, and writes their content into STDOUT. Gitea should support it to make indexing faster.

**Comment by lunny** [comment]
Thanks for your idea.

**Comment by yp05327** [comment]
@lunny
does this finished by #7199?

**Comment by lunny** [comment]
#7199 introduced the batch method and the following PRs have resolved the problem.
