### ISSUE TITLE
Text replacing issues in post requests

### ISSUE THREAD

**Issue by marcsiq** [go-gitea/gitea#6655]
- Gitea version (or commit ref): 1.8
- Git version: 2.17.1
- Operating system: Ubuntu 18.04.2
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
https://try.gitea.io/marcs/bug_test/compare/master...issue%232

If we try to pull-request branch "issue#N" into "master" we got error 404.
We can see from the log on our own server (caption below) that the issue is with the post request text replacing %23N (#N) by %2523N.

...

## Screenshots

Apr 16 17:15:02 rd1 gitea[19212]: [Macaron] 2019-04-16 17:15:02: Started GET /DSP/Prometheus/compare/develop...feature/issue%235 for 127.0.0.1
Apr 16 17:15:02 rd1 gitea[19212]: [Macaron] 2019-04-16 17:15:02: Completed GET /DSP/Prometheus/compare/develop...feature/issue%235 200 OK in 190.126663ms
Apr 16 17:15:06 rd1 gitea[19212]: [Macaron] 2019-04-16 17:15:06: Started POST /DSP/Prometheus/compare/develop...feature/issue%25235 for [::1]
Apr 16 17:15:06 rd1 gitea[19212]: [Macaron] 2019-04-16 17:15:06: Completed POST /DSP/Prometheus/compare/develop...feature/issue%25235 404 Not Found in 53.722988ms

**Comment by zeripath** [comment]
Hmm on try that appears to be working. Could you attempt to replicate on try?

**Comment by Marcsiq2** [comment]
https://try.gitea.io/marcs/bug_test/compare/master...issue%232

If you just try to create a pull request to merge "issue#2" into "master" i got a error 404

**Comment by zeripath** [comment]
Ah I see! Sorry I just did that!

**Comment by Marcsiq2** [comment]
And if you look at the URL when getting the error it replaces %232 (which represents #2 correctly) with %25232.

**Comment by zeripath** [comment]
I just noticed another issue try creating a file using the editor with a new branch say #3. You're redirected to something awful too.

**Comment by Marcsiq2** [comment]
Yeah, we also saw that problem! So it suggests it's somewhere in http text replacement.

**Comment by zeripath** [comment]
OK, so this one is due to:

https://github.com/go-gitea/gitea/blob/8d01b9857ffeb1408b3fe6ca2007de5a81eaacd6/templates/repo/issue/new_form.tmpl#L1

Here the link is being twice escaped.

**Comment by zeripath** [comment]
I'm fairly certain that that should never need to be EscapePounded

**Comment by Marcsiq2** [comment]
So, creating that template under `/custom/templates/repo/issue` and remove the escaping should do the trick?

**Comment by zeripath** [comment]
yeah

**Comment by Marcsiq2** [comment]
I'm gonna try it tomorrow then.
Thank you so much, I'm quite new on gitea but loving it so far. 😄

**Comment by zeripath** [comment]
The other bug I mentioned should be fixed by #6657
