### ISSUE TITLE
Feature Request: Cross-link commits mentioning other repos

### ISSUE THREAD

**Issue by stani0502** [go-gitea/gitea#6664]
- Gitea version (or commit ref):8d01b98
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
Refering to this pull request #6273, on this pull request say able to link issue to another repo
I tried in here https://try.gitea.io/stani0502/coba.
i tried commit and put url of the issue from different repo to link this issue https://try.gitea.io/stani0502/test/issues/1.
But is not working.
Let me know how the correct way to do that.

...

## Screenshots
![image](https://user-images.githubusercontent.com/6171313/56254436-5e7bc580-60f3-11e9-9404-a22bc9eae4f4.png)
![image](https://user-images.githubusercontent.com/6171313/56254472-82d7a200-60f3-11e9-9ad9-0c36b1591062.png)

**Comment by mrsdizzie** [comment]
I'm not sure I understand -- the box you have drawn in the first screenshot shows the issue reference as a link and when clicking on your example link of https://try.gitea.io/stani0502/coba it also shows the proper link where the text ```stani0502/test#1``` is a link to https://try.gitea.io/stani0502/test/issues/1

What are you expecting to happen?

**Comment by stani0502** [comment]
i expecting something like this
![image](https://user-images.githubusercontent.com/6171313/56259343-444ae300-6105-11e9-826f-24e4076ce5b0.png)

**Comment by techknowlogick** [comment]
Ah, so it's not that something isn't working. It's that something hasn't been implemented yet.

**Comment by stani0502** [comment]
ah okay, i thought that fixed for that kind feature.
