### ISSUE TITLE
[feature] - Add successfull build on branch protection

### ISSUE THREAD

**Issue by zopanix** [go-gitea/gitea#6665]
- Gitea version (or commit ref): N/A
- Git version: N/A
- Operating system: N/A
- Database (use `[x]`): N/A
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:
N/A
## Description
As a user, I want the possibility to force successful build on a pull request before merging is allowed.

Ideally, when creating a `branch protection`, I would like to have an additional checkbox called something like: 
`Enable Successful Build Check`
As description, I would put: `Enforce successful build from CI on last commit`

As a result, if the last build on a commit is successful, gitea SHOULD allow merging if all other requirements are met, if the build fails, it MUST not be possible to merge the current pull request even if other requirements are met.

**Comment by lunny** [comment]
I think you mean https://github.com/go-gitea/gitea/issues/996#issuecomment-368007123

**Comment by lunny** [comment]
duplicated with #3588
