### ISSUE TITLE
500 when select pull from branch in a fork repository for create a PR

### ISSUE THREAD

**Issue by FalconWu2017** [go-gitea/gitea#6668]
- Gitea version (or commit ref):1.7.6
- Git version:
- Operating system: win 2012
- Database (use `[x]`):
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:
2019/04/18 09:24:27 [...routers/repo/pull.go:749 PrepareCompareDiff()] [E] GetDiffRange: Wait: exit status 128
2019/04/18 09:24:27 [D] Template: status/500
-- url :   
/compare/master...XXX:ForkTest
## Description  
1. I have a repository named A.   
1. I fork A to a new repository and name B.   
1. I push a new branch named ForkTest to B.    
1. I want make a new PR in A to merge ForkTest.  
But if I select branch ForkTest want to merge,It will show me a 500 error.

**Comment by zeripath** [comment]
This is likely already fixed in 1.8 and master by #6555 and #6515 and their backports. Please try to reproduce on 1.8-rc and on try.

**Comment by FalconWu2017** [comment]
It is fixed.
