### ISSUE TITLE
Increase Accessbilty/Contrast in dark theme

### ISSUE THREAD

**Issue by xf-** [go-gitea/gitea#6687]
## Description
The contrast between background and font is low in dark theme. It is really exhausting using it. Depending on display/backlight and also features like "Low Blue Light" make sometimes hard to read the content. Compared to other dark themes the background is bright and font gray.
I like dark themes like YouTube or KDE breeze dark skin.

My suggestion wold be Lighthouse accessibility tool to test color contrast.
![image](https://user-images.githubusercontent.com/1295633/56446312-4ded6a00-6302-11e9-8641-a1a5761a8a9a.png)
https://github.com/GoogleChrome/lighthouse/
Also used in Google insight

**Comment by xf-** [comment]
Should be improved @bot :P

**Comment by BNolet** [comment]
As well, here: 
![image](https://user-images.githubusercontent.com/10198484/62176428-6f052400-b30f-11e9-990a-94f972542159.png)

**Comment by Jieiku** [comment]
I actually had some issues reading with the current contrast, so I made a new theme yesterday: https://github.com/Jieiku/theme-dark-gitea

**Comment by Ryuno-Ki** [comment]
@silverwind Would you be able to help me the source for the arc-green theme? As in: where did you find the values for the Less file?

https://github.com/go-gitea/gitea/blob/73382d2132f8f242245d83f66c92761e0b477b91/web_src/less/themes/theme-arc-green.less

I noticed that the file is around for a long time, but you seem to have the most familiarity with it.

KDE Breeze Dark colour palette is defined in https://develop.kde.org/hig/style/color/dark/

**Comment by Ryuno-Ki** [comment]
@TTWNO We touched the topic on Matrix before. Do you have ideas here?

**Comment by HubKing** [comment]
I hate that most dark themes (not just Gitea) are low-contrast. I don't know; maybe other people like it that way, but low-contrast dark themes defeat the purpose of dark theme. The background is still bright hurting my eyes, and the text is too dark to read when my monitor is set to the minimum brightness. To read the text, I would have to increase the monitor brightness, further scorching my eyes. 

Can't you just add another in-built theme, "high-contrast dark"? Refer to IntelliJ (Android Studio or any similar IDE).
![image](https://blog.jetbrains.com/wp-content/uploads/2018/10/idea-HighContrastTheme.png)

**Comment by silverwind** [comment]
I plan to make a proper dark theme now that all colors are in CSS variables. After that is done, we can talk about high-contrast themes that would probably build on the default light/dark themes.

**Comment by silverwind** [comment]
Yes, I think current dark theme has enough contrast. I have not ran WCAG on it yet, but I assume it'll be close to passing those tests.
