### ISSUE TITLE
"Delete all repository archives" is misleading

### ISSUE THREAD

**Issue by Oreolek** [go-gitea/gitea#6689]
Now that gitea has archived repositories, the "Delete all repository archives" option in admin dashboard can be misread, especially in translations.

**Comment by oscarlofwenhamn** [comment]
Indeed, I now realize I have been reading that as "Delete all archived repositories".

**Comment by lafriks** [comment]
Any suggestions for better wording?

**Comment by techknowlogick** [comment]
Perhaps "Delete all repositories' archives (ZIP, TAR.GZ, etc..)"?

**Comment by oscarlofwenhamn** [comment]
Definitely better. I will be honest and point out I'm not entirely clear regarding what the archives are, but @techknowlogick's wording makes it clear(er) that it's not archived repos that will be deleted.

**Comment by delvh** [comment]
> Perhaps "Delete all repositories' archives (ZIP, TAR.GZ, etc..)"?

A bit late, but:
Maybe we should still use singular for `repositories`:
`Delete all repository archives (ZIP, TAR.GZ, …)`
Sounds to me more natural than the current solution.
