### ISSUE TITLE
Error on commit (in UI) after renaming a repository

### ISSUE THREAD

**Issue by KangoV** [go-gitea/gitea#670]
- Gitea version (or commit ref): 1.0.0+109-ge5620f07
- Git version: 2.8.3
- Operating system: docker container: Linux 0c196eb4ba0f 4.4.0-53-generic 74-Ubuntu SMP (alpine 3.4.6)
- Database:
  - [x] PostgreSQL (v9.6.1)
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No (works fine)
  - [ ] Not relevant
- Log gist:

## Description

I've renamed a repository from repository-model to domain-model. I've tried editing README.md in the Gitea UI and get this:
```
Failed to update/create file 'README.md' with error: 
UpdateLocalCopyBranch [branch: master]: git pull origin master: exit status 1 - fatal: 
    '/data/git/gitea-repositories/monkeys/repository-model.git' does not appear to be 
    a git repository fatal: Could not read from remote repository. Please make sure you 
    have the correct access rights and the repository exists.
```
* The repository name has been changed correctly in the database.
* The repository in `gitea-repositories` has been changed correctly.

I'm not sure where the old name is being picked up from.

*But*, A commit from Eclipse remotely works fine. This is only failing using the Gitea UI.
*Update*: After committing successfully from Eclipse, it still fails in the UI with the same error.

**Comment by lunny** [comment]
Didn't reproduce this.

**Comment by KangoV** [comment]
@lunny No, neither could i on [try.gitea.io](https://try.gitea.io). Just wondering if this was a bug and it was fixed. I can't find anything though.

**Comment by KangoV** [comment]
I've restarted the app and the error has gone away. This occurs in gogs as well according to [gogs#3641](https://github.com/gogits/gogs/issues/3641).

I agree with the details in the gogs issue that it is or was a caching issue. When a new docker image is available, i'll test again.

**Comment by tboerger** [comment]
Looks like we can close that for now. Feel free to reopen the issue if you can reproduce it.

**Comment by francoism90** [comment]
Please re-open:
```
Failed to update/create file 'etc/nginx/nginx.conf' with error: UpdateLocalCopyBranch [branch: master]: git pull origin master: exit status 1 - fatal: '/var/lib/gitea/repo/francoism90/dotfiles.git' does not appear to be a git repository fatal: Could not read from remote repository. Please make sure you have the correct access rights and the repository exists. 
```
Renamed dotfiles repo to arch-config in GUI. Trying to create a new file within the GUI causes this issue.

Thanks!

EDIT:
After restarting gitea, the error is gone. Seems like a caching issue?

**Comment by lunny** [comment]
Which version are you in. @francoism90

**Comment by francoism90** [comment]
@lunny master (1.0.0+215-ge921dcf5).

FYI I'm running gitea as proxy using nginx, could this cause the caching issues?

Thanks.

**Comment by lunny** [comment]
Cannot reproduce this. Could you mean:

1. rename some repo to other name
2. Click `New File` and write something in file name and file content
3. Then it return an error

**Comment by francoism90** [comment]
@lunny correct. After restarting the gitea.service, the error is gone.

**Comment by lunny** [comment]
So strange. Let's keep it open.

**Comment by lunny** [comment]
I think this has been fixed sometime. I cannot reproduce it again. See https://try.gitea.io/lunny/ftpserver/src/branch/master/ttt.md
