### ISSUE TITLE
Template exception when rendering file list

### ISSUE THREAD

**Issue by mdeboer** [go-gitea/gitea#6708]
**Running version**: `b83114f`

I have many repo's and most of them work fine, today I entered a small one and one specific branch would not load and gave me this exception:

`template: repo/view_list:82:38: executing "repo/view_list" at <$commit.Summary>: invalid value; expected string`

Related template file:
https://github.com/go-gitea/gitea/blob/b83114f1407247415b184f77f8f2f6ecea8cb994/templates/repo/view_list.tmpl#L82

I did a bit of research and it appears commits with a summary ending with a `'` throw this exception. For instance:

`Merge branch 'foo'`

However this is fine:

`Merge branch 'foo' into bar`

**Comment by lafriks** [comment]
can you reproduce this on try.gitea.io?

**Comment by mdeboer** [comment]
Unfortunately not, which is weird as it seemed to be consistent. I switched back to the latest stable release (1.8.0) which works fine.

It is weird though because it was only at that page where it loads the file list. The other views showing all commits worked fine.

Does it help to mention it is a mirrored repository and I am using docker? I'll see if I can recreate it locally using docker.

Repo on try.gitea.io: https://try.gitea.io/mdeboer/test

**Comment by lafriks** [comment]
Try is also running in docker

**Comment by Aviortheking** [comment]
When I was on gitea.com I found the same error on one of @lunny repos
https://gitea.com/lunny/wtf

**Comment by saitho** [comment]
I cloned lunnys repository and looked into that. Those files are causing the exception:
- .editorconfig
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- LICENSE.md

commit_info.go calculates a mapping of file paths and commits. The files above are added to `remainingPathsForParent` and ultimately to the `heap` array. At some point they don't seem to be processed anymore.

**Comment by saitho** [comment]
Commit "37858d421073a878ffef2c308eb0c0bdd496960b" (Delete unused field from BarGraph widget) seems to have been visited already, which might be why the remaining files are not processed.
That's how far I've got... ^^

**Comment by bkraul** [comment]
As pointed in my duplicate, the only file I have in my commit that matches the list is `.editorconfig`. There might be something with that one.

**Comment by lafriks** [comment]
Problem is in `func getLastCommitForPaths`, some file tree entries does not get commit info assigned so that in the end we get error in template when accessing nil pointer properties.

@filipnavara this seems to be related to your code rewrite. Could you please check this out?

While debugging it seems to me that while traversing through commit parents `result[path]` does not get commit assigned but it does not get added to remaining paths to check either so it gets losts

**Comment by filipnavara** [comment]
I will look into it.

**Comment by filipnavara** [comment]
Removing the `seen` map from `getLastCommitForPaths` fixes it. It also makes it easier to reason about the correctness of the algorithm. Thanks to other changes made in #6686 it also doesn't noticably degrade performance. I have tested the change on the linked repositories and Rails and Linux repositories.

**Comment by bkraul** [comment]
When can we see this in upstream? @lafriks, thank you for flagging this critical!

**Comment by lafriks** [comment]
@bkraul fix has been merged, please test

@filipnavara thanks for fast fix 👍

**Comment by bkraul** [comment]
This is back to working on docker latest build. Thank you!
