### ISSUE TITLE
Read & write deploy keys

### ISSUE THREAD

**Issue by GeoffreyFrogeye** [go-gitea/gitea#671]
Being able to give write access to some deploy keys would be very useful for repositories where git is used as an archiving and propagation tool rather than a code versioning system. Such repositories include those used by tools like [pass](https://www.passwordstore.org/), [etckeeper](http://etckeeper.branchable.com/), and some dotfiles manager, where commits and push can be done semi-automatically and you don't want that tool to have a write access to all your repositories.

**Comment by tboerger** [comment]
Currently you can do that with separate accounts, but I would also integrate write access for deploy keys optionally

**Comment by bkcsoft** [comment]
We do have access tokens already right? shouldn't that be enough? or do they need more "control"?

**Comment by tboerger** [comment]
Access tokens are bound to a user, so this grants too much access.
