### ISSUE TITLE
Unsupported indexer queue type: redis

### ISSUE THREAD

**Issue by deanishe** [go-gitea/gitea#6712]
- Gitea version: 1.8.0
- Git version: 2.11.0
- Operating system: Debian 9.8
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

After upgrading to v1.8.0, `redis` no longer works for indexer queue type. Gitea fails to start with the following error:

```
[...itea/routers/init.go:95 GlobalInit()] [E] Failed to initialize issue indexer: Unsupported indexer queue type: redis
```

**Comment by lunny** [comment]
`Redis` queue has been merged on master.

**Comment by dragonandy** [comment]
Same issue here 
Ubuntu 18.04+MariaDB+gitea 1.8.1

upgraded to the latest 1.8.1 and gitea not starting
I switch back to the default `[indexer]` settings to get gitea running

```log
2019/05/09 17:18:25 [I] Log Mode: File(Info)
2019/05/09 17:18:25 [I] XORM Log Mode: File(Info)
2019/05/09 17:18:25 [I] Cache Service Enabled
2019/05/09 17:18:25 [I] Session Service Enabled
2019/05/09 17:18:25 [I] Beginning ORM engine initialization.
2019/05/09 17:18:25 [I] ORM engine initialization attempt #1/10...
2019/05/09 17:18:25 [I] ORM engine initialization successful!
2019/05/09 17:18:25 [I] Git Version: 2.21.0
2019/05/09 17:18:26 [...itea/routers/init.go:95 GlobalInit()] [E] Failed to initialize issue indexer: Unsupported indexer queue type: redis
```

**Comment by zeripath** [comment]
Yes redis indexer is on the 1.9 branch not 1.8

**Comment by deanishe** [comment]
Could you [update the docs to point out when a feature isn't actually in the latest stable release](https://docs.gitea.io/en-us/config-cheat-sheet/)?

> ISSUE_INDEXER_QUEUE_TYPE: levelqueue: Issue indexer queue, currently supports:channel, levelqueue, redis.

**Comment by lunny** [comment]
Right, we need a new document structure to show different version of documents.

**Comment by mrsdizzie** [comment]
When I've written anything about a feature only in master, I try to add some small text indicating that since the docs aren't versioned, like:
```
redis (as of Gitea 1.9)
```
Which can be helpful enough until there is a versioned document system. You can see similar text at the top of:

 https://docs.gitea.io/en-us/logging-configuration/

Not perfect but probably helps with issues like this.

**Comment by deanishe** [comment]
> Not perfect but probably helps with issues like this.

It lets you know that the docs may not apply to your version, but it's not particularly obvious which bits of the docs.

> The logging framework has been revamped in Gitea 1.9.0.

Could be clearer. The page makes clear that the `AccessLogger` is new in 1.9, but is that the only thing that's changed? "Revamped" sounds like it could mean quite extensive changes.

Still, I can always read the Markdown sources in `/docs` on the appropriate branch instead.

**Comment by zeripath** [comment]
I wonder if we should just do what other projects do and have the previous versions documents also published too?

**Comment by deanishe** [comment]
A bigger issue as I see it is that the official docs appear to be based on `master` and not the current stable release.

As long as there's only one version of the docs available, they should be for the current stable release, which is presumably what most users should be running.

**Comment by lafriks** [comment]
Most correct way would be to create option to choose docs version but I don't know how to do that with Hugo and multiple branches
