### ISSUE TITLE
Get 500 when add ssh key

### ISSUE THREAD

**Issue by mengyyy** [go-gitea/gitea#6715]
- Gitea version (or commit ref): 1.7.0 and 1.8.0
- Git version: 2.17.1
- Operating system: ubuntu 18.04.2 x64
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:
```
1.7.0
2019/04/23 10:46:07 [I] [SQL] BEGIN TRANSACTION
2019/04/23 10:46:07 [I] [SQL] INSERT INTO `public_key` (`owner_id`,`name`,`fingerprint`,`content`,`mode`,`type`,`login_source_id`,`created_unix`,`updated_unix`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?) []interface {}{1, "foo", "SHA256:...", "ssh-rsa AA...", 2, 1, 0, 1555987567, 1555987567}
2019/04/23 10:46:07 [I] [SQL] ROLL BACK
[Macaron] 2019-04-23 10:46:07: Completed POST /user/settings/keys 404 Not Found in 15.947892ms


1.8.0
2019/04/23 10:55:07 [I] [SQL] INSERT INTO `public_key` (`owner_id`,`name`,`fingerprint`,`content`,`mode`,`type`,`login_source_id`,`created_unix`,`updated_unix`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?) []interface {}{1, "foo", "SHA256:...", "ssh-rsa AA.....", 2, 1, 0, 1555988107, 1555988107}
2019/04/23 10:55:07 [I] [SQL] ROLL BACK
[Macaron] 2019-04-23 10:55:07: Completed POST /user/settings/keys 500 Internal Server Error in 246.62229ms
```

## Description
I run gitea as root but when I try to add ssh keys i get 500 error.

## Screenshots
![image](https://user-images.githubusercontent.com/10589755/56550472-4a830880-65b8-11e9-94b7-499aa76e801c.png)

**Comment by typeless** [comment]
From the timestamps of your log, it looks quite easy to reproduce.
But it seems that most people don't encounter this issue.

Where do you get the Gitea binrary? Do you build it from source or some package distributors?

**Comment by mengyyy** [comment]
> From the timestamps of your log, it looks quite easy to reproduce.
> But it seems that most people don't encounter this issue.
> 
> Where do you get the Gitea binrary? Do you build it from source or some package distributors?

Yes I get the Gitea binrary.
1.7.0  from https://dl.gitea.io/gitea/1.7.0/gitea-1.7.0-linux-amd64 
1.8.0 from github

I do not build it from source.

**Comment by lunny** [comment]
When create SSH key, gitea will save it on your /root/.ssh, maybe you can check the permission of that folder.

**Comment by lafriks** [comment]
or `/home/git/.ssh/...`

**Comment by mengyyy** [comment]
Oh………… 
before i install gitea I ran 
`chmod 400 ~/.ssh/authorized_keys && chattr +i ~/.ssh/authorized_keys && chattr +i ~/.ssh`

**Comment by jyling** [comment]
on what path will it be on the windows ?

**Comment by zeripath** [comment]
If you don't want to write authorized_keys files you can turn them off and switch to use a authorized keys command in the SSH server configuration. See https://docs.gitea.io/en-us/command-line/#keys
