### ISSUE TITLE
Migration failure 1.7.6->1.8.0: No such index: IDX_user_"idx_user_IDX_user_is_active"

### ISSUE THREAD

**Issue by tadly** [go-gitea/gitea#6718]
- Gitea version (or commit ref): 1.7.6
- Git version: ---
- Operating system: docker
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:
```
2019/04/23 11:48:27 [...itea/routers/init.go:82 GlobalInit()] [E] ORM engine initialization failed: migrate: do migrate: no such index: IDX_user_"idx_user_IDX_user_is_active"
2019/04/23 11:48:27 [I] Log Mode: File(Info)
2019/04/23 11:48:27 [I] XORM Log Mode: File(Info)
2019/04/23 11:48:27 [I] Cache Service Enabled
2019/04/23 11:48:27 [I] Session Service Enabled
2019/04/23 11:48:27 [I] Mail Service Enabled
2019/04/23 11:48:27 [I] Notify Mail Service Enabled
2019/04/23 11:48:27 [I] Beginning ORM engine initialization.
2019/04/23 11:48:27 [I] ORM engine initialization attempt #1/10...
2019/04/23 11:48:27 [I] Migration: add theme to users
2019/04/23 11:48:27 [I] Backing off for 3 seconds
2019/04/23 11:48:30 [I] ORM engine initialization attempt #2/10...
2019/04/23 11:48:30 [I] Migration: add theme to users
2019/04/23 11:48:30 [I] Backing off for 3 seconds
2019/04/23 11:48:33 [I] ORM engine initialization attempt #3/10...
2019/04/23 11:48:33 [I] Migration: add theme to users
2019/04/23 11:48:33 [I] Backing off for 3 seconds
...
```
## Description
I made sure every version from 1.7.0 up to 1.7.6 was working.
As soon as I upgrade from 1.7.6 to 1.8.0 I get the above error.

Indexes do exist and there's also one for `idx_user_IDX_user_is_active`
```sh
$ sqlite3 gitea.db .indexes | grep user_is_active
idx_user_IDX_user_is_active
```

**Comment by adelowo** [comment]
Looks like this is https://github.com/go-gitea/gitea/pull/5682 but it was fixed.. 

```

$ sqlite3 gitea.db
$ UPDATE users SET theme=""

```

**Comment by tadly** [comment]
Nope, not it especially as the error says: `no such index: IDX_user_"idx_user_IDX_user_is_active"`
I did try your suggestion anyways but again, didn't work.

The first `IDX_user_` prefix seems to much. No idea where this one is coming from though.

**Comment by adelowo** [comment]
The log you pasted doesn’t contain anything related to indexes though

**Comment by tadly** [comment]
Uhm the very first line?
```
2019/04/23 11:48:27 [...itea/routers/init.go:82 GlobalInit()] [E] ORM engine initialization failed: migrate: do migrate: no such index: IDX_user_"idx_user_IDX_user_is_active"
```
specifically: `no such index`

Anyways, the fact it says `"idx_user_IDX_user_is_active"` is wrong already which I've manually fixed but it still prefixes it with an additional `IDX_user_`.

So currently I'm stuck at
```
ORM engine initialization failed: migrate: do migrate: no such index: IDX_user_"IDX_user_created_unix"
```
while it **should be** just `IDX_user_created_unix`

Will have to investigate more some time later as I'm rather busy right now :(

**Comment by zeripath** [comment]
OK let's try to figure out which migration is doing this. What's the version number of your database?

```sql
SELECT * from Version;
```

**Comment by tadly** [comment]
Sorry for the delay. First of, I'm using the official [docker image](https://hub.docker.com/r/gitea/gitea) and am curious how the upgrade strategy for gitea usually is. Do you **have to** make sure you hit every version or could you (in theory) go from 1.7.0 straight to 1.8.0

As for the version, `77` is what I get.
Seems like I'm missing quite a bit... 78 - 84 ._.
As to how to apply them I'm not quite sure 🙄

**Comment by Cellebyte** [comment]
Same here from 1.7.3 to 1.8 Docker image.
2019/04/24 07:50:00 [...itea/routers/init.go:82 GlobalInit()] [E] ORM engine initialization failed: migrate: do migrate: Drop column failed: mssql: ALTER TABLE DROP COLUMN is_bare failed because one or more objects access this colum

**Comment by adelowo** [comment]
Oh sorry, I was on mobile and didn't see that :)

**Comment by ChriFo** [comment]
I am running v1.7.6 from Docker image with PostgreSQL.
Currently I am at version 77.

And I think I should wait with upgrade to 1.8 :smiley:

**Comment by xor-gate** [comment]
Same for me with Version 78.

**Comment by xor-gate** [comment]
Fixed for me with:
```

**Comment by adelowo** [comment]
Will send a fix after lunch

**Comment by ChriFo** [comment]
> I am running v1.7.6 from Docker image with PostgreSQL.
> Currently I am at version 77.
> 
> And I think I should wait with upgrade to 1.8 😃

Update to 1.8 was successful. Current version is 83.

**Comment by Cellebyte** [comment]
Same here from 1.7.6 to 1.8 Docker image.
```
2019/04/24 07:50:00 [...itea/routers/init.go:82 GlobalInit()] [E] ORM engine initialization failed: migrate: do migrate: Drop column failed: mssql: ALTER TABLE DROP COLUMN is_bare failed because one or more objects access this column
```
Cannot upgrade.

**Comment by adelowo** [comment]
@lafriks Since my pr doesn't fix everything, can we reopen this? The original post says `ORM engine initialization failed: migrate: do migrate: no such index: IDX_user_"idx_user_IDX_user_is_active"`

**Comment by tadly** [comment]
I do suspect that this is just **my** db being borked and not a general issue (the `IDX_user_"idx_user_IDX_user_is_active"` thing)

Still would appreciate it if anyone could help me fix this as doing a fresh setup would be rather tedious and time-consuming :sweat_smile:

**Comment by zeripath** [comment]
Try setting your version to 78 to skip the v78 migration - but do the work of the migration by hand.

**Comment by tadly** [comment]
@zeripath Actually did that already but now gitea isn't doing anything on startup.
Nothing in the logs (even if I set the level to `Debug`) and the version stays at 78 :/

I ended up doing the most stupid thing I could think of (Spoiler, it's working now):
 1. Manually drop **all** indexes (So everything from `.indexes` including the unique ones even though they would fail but I didn't care :D)
 2. Select all indexes from a fresh setup (`SELECT sql FROM sqlite_master WHERE type == 'index';`)
 3. Recreate all indexes using the previous commands
 4. `database is locked` (_WhatTheHeckWhyNowAllOfASuddon.jpg_)
 5. _indexes where recreated automatically_
 6. DB-Version is `83` now

I have this bad feeling that this isn't the last of it and that my db is quite messed up but that's not your guys fault.

Thanks for the help. I think we can close the issue again unless there are any objections?

**Comment by zeripath** [comment]
@tadly so it looks like you had a particularly broken db, I'm not sure how. I don't think `models/migrations/v78.go` could be responsible for that. Especially if the next migration in line fails too.

Dropping all the indexes and recreating them should be fine though.

Therefore I'm going to close this issue - I'm also going to change the title as I don't want people to refer to this unless they actually have a similar index problem - in which case we can reopen and reinvestigate.
