### ISSUE TITLE
show pdf attachment directly in markdown file

### ISSUE THREAD

**Issue by laoshaw** [go-gitea/gitea#6720]
I can do PDF attachment easily, can I show the PDF directly in the markdown file like what image-attachments are in gitea?

that is, if I do `[mypdf](my.pdf)` it will show the PDF in a embedded scroll-able window right in the middle of text, just like a picture in a html.

**Comment by dmikushin** [comment]
Gitea views PDFs with pdfjs in an <iframe>. Unfortunately, unlike <img>, the <iframe> is not a valid markup tag, and does not display anything. Perhaps, one would need to develop an [external renderer](https://docs.gitea.io/en-us/external-renderers/)
