### ISSUE TITLE
Feature Request: Dynamic Theme for Gitea

### ISSUE THREAD

**Issue by alexclst** [go-gitea/gitea#6726]
Safari in macOS 10.14.4 and above utilizes the CSS media `prefers-color-scheme` to let you dynamically change website styles when the overall system theme changes. I created a fairly crude dynamic theme that is a simple merge of the two existing themes, [theme-dynamic.css](https://github.com/go-gitea/gitea/files/3109369/theme-dynamic.css.zip). Including this, or something along those lines, as a theme built in to Gitea may make sense for those of us on Macs. I believe, too, that Microsoft, and maybe Google, are working to include similar support for the same CSS media queries in their browsers.

The one GUI area that does need some work in my theme, and so should be dealt with before a dynamic theme is shipped with Gitea, is that the heat map on the dashboard refuses to change colors dynamically, instead requiring a reload of the page to match the current theme.

But, other than that, this dynamic theme is something, or the idea of it if not my crude version, that I’d love to see included in Gitea.

**Comment by allgoewer** [comment]
prefers-color-scheme is now supported on most browsers:
https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme#Browser_compatibility

**Comment by jolheiser** [comment]
Though this issue is older, it seems https://github.com/go-gitea/gitea/issues/10927 had some fairly relevant discussion. I am going to close this one in lieu of the other. (The link to the other issue I posted should make a reference note, so we can still refer to this one if needed. Thanks for the interest and example file!)
