### ISSUE TITLE
teams/new => error

### ISSUE THREAD

**Issue by imknn** [go-gitea/gitea#6728]
teams/new => error

https://try.gitea.io/org/demozqyu/teams/new

![深度截图_选择区域_20190424102205](https://user-images.githubusercontent.com/11704766/56628026-d9585980-667a-11e9-9fe0-6b9bc125c2f3.png)

**Comment by lunny** [comment]
I get a 404 error returned and it seems that org is not exist any more.

**Comment by ZhengQinyu** [comment]
I've deleted that org. You can try adding one by yourself.

**Comment by ZhengQinyu** [comment]
> I get a 404 error returned and it seems that org is not exist any more.

This error occurred whenI am adding a team.
