### ISSUE TITLE
Mergeability of PRs is not updated when target branch got updates

### ISSUE THREAD

**Issue by markusamshove** [go-gitea/gitea#6734]
Tested on Gitea 1.8.0

Currently the status if a PR has conflicts to the target branch is not updated when there are new commits pushed to the target branch.

Scenario:

I branch off from master to implement a feature. When the feature is implemented, I first want to merge it into a QA branch via PR.
If master and QA have diverged too much (e.g. a lot of testing at the moment), I get conflicts from feature to QA, which is expected.

However, if I then merge master into QA the conflicts might be resolved. 
When I now look into the PR, it still says it has the same conflicts as before, which led me to the conclusion that the mergeability is not evaluated again if there are updates to the target branch.

I think this would be a great QoL feature

**Comment by lafriks** [comment]
Can you create such example in try.giyea.io?

**Comment by MarkusAmshove** [comment]
After testing it a bit more, I think it is more likely a cause of #6417 (using `apply` instead of `merge`), so that it *seems* like the PR isn't updated

**Comment by lafriks** [comment]
Even through a bit different fixing that should fix also this use case so closing this
