### ISSUE TITLE
[Feature request] Pull request: Allow administrator to change owner

### ISSUE THREAD

**Issue by 3l73** [go-gitea/gitea#6738]
- Gitea version (or commit ref): 1.x
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant

## Description

User story: As an administrator I would like to change the owner of a pull request.

Sometimes developers create pull requests in order to make a review of changes of another developer.

Normally the developer should create a pull request after his change(s) is/are ready to review.

In some situation the reviewer himself create the pull request. Since he becomes the owner of the pull request he is not able to accept or deny the changes.

...

**Comment by lafriks** [comment]
I don't see how that would work with forks for example

**Comment by lunny** [comment]
Just close and open a new one is OK.
