### ISSUE TITLE
Readme image extensions are case sensitive

### ISSUE THREAD

**Issue by worthy7** [go-gitea/gitea#6750]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
If I have files named
`banana.PNG`
`apple.png`

When referencing the image from markdown files, it will be picky about the case:
`[banana](banana.png)` won't work.
`[apple](apple.PNG)` won't work.

I'm not sure if this is intended or not, but by default case changes in names aren't recorded into git. So I have to full on delete, commit, remake the file with the correct filename if I want it to change. 
https://stackoverflow.com/questions/17683458/how-do-i-commit-case-sensitive-only-filename-changes-in-git

Because git doesn't care about case changes by default, I think Gitea shouldn't care about it either.
...

**Comment by Worthy7** [comment]
Whops, GitLab issue!
