### ISSUE TITLE
Too long description of organizations breaks UI

### ISSUE THREAD

**Issue by shaoran** [go-gitea/gitea#6755]
- Gitea version (or commit ref): 1.8.0 (https://dl.gitea.io/gitea/1.8.0/gitea-1.8.0-linux-amd64.xz)
- Git version: 2.11.0
- Operating system: Debian 9
- Database (use `[x]`):
  - [x] SQLite

## Description

- create a new organization and/or edit an existing one
- In the **description** field use more than 254 characters
- click on *update setting*

You'll get the following error:

    template: org/settings/options:41:110: executing "org/settings/options" at <eq .CurrentVisibility 0>: error calling eq: invalid type for comparison

The text field should allow max. 254 characters or the description in the database should allow more characters.

**Comment by adelowo** [comment]
I cannot replicate this. There is actually validation in place to protect against this kind of thing.

@shaoran How were you able to make a description of more than 254 characters

<img width="1676" alt="Screenshot 2019-04-26 at 17 08 41" src="https://user-images.githubusercontent.com/12677701/56821502-6a2f6080-6846-11e9-8591-c9b586278fde.png">

**Comment by mrsdizzie** [comment]
@adelowo that is the repo description -- this error is about the description of an org: if you go to https://example.com/org/orgname/settings you can see.

**Comment by adelowo** [comment]
Lol... I haven't had enough water today :) 

Will take a look at it

**Comment by shaoran** [comment]
@adelowo no problem, we all do mistakes. To answer your question, I copied and pasted a couple of paragraphs (3 to be precise) from our company homepage, that leads to more than 255 characters.

**Comment by mrsdizzie** [comment]
it looks like updating an org settings is maybe missing helper functions to check these types of things similar to what repos and org_teams have:

https://github.com/go-gitea/gitea/blob/81059a2567be0cd811ca10e3545282c9aa53276a/models/repo.go#L1675

https://github.com/go-gitea/gitea/blob/81059a2567be0cd811ca10e3545282c9aa53276a/models/org_team.go#L370

Updating an org uses updateUser:

https://github.com/go-gitea/gitea/blob/81059a2567be0cd811ca10e3545282c9aa53276a/models/user.go#L971-L974

But the truncating for a user happens in this BeforeUpdate:

https://github.com/go-gitea/gitea/blob/81059a2567be0cd811ca10e3545282c9aa53276a/models/user.go#L156

Which maybe doesn't happen for an org. I'm not totally familiar with how it all works though

**Comment by Cherrg** [comment]
This also affects the organisation name if there are added more than 40 letters

**Comment by Cherrg** [comment]
> Which maybe doesn't happen for an org. I'm not totally familiar with how it all works though

@mrsdizzie JFYI: I found, that organisations are nearly the same as users, they share the same model. It's a flag, so these update functions got called. It was just a missing variable for template.
