### ISSUE TITLE
Wiki pages with protected names are unviewable

### ISSUE THREAD

**Issue by Bwko** [go-gitea/gitea#676]
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL) [https://try.gitea.io/Bwko/VsCode/wiki/_pages](https://try.gitea.io/Bwko/VsCode/wiki/_pages)
  - [ ] No
  - [ ] Not relevant

## Description

Create a page with the title `_pages` or `_new`. The wiki page get's created but is unviewable.

**Comment by lunny** [comment]
It should return error message when creating.
