### ISSUE TITLE
[API] Best way for issues and PRs and it's count

### ISSUE THREAD

**Issue by mmarif4u** [go-gitea/gitea#6774]
Gitea 1.8.0

Currently reop info API return open issue count of issues.  
https://try.gitea.io/api/swagger#/repository/repoGet

While issues API return both PRs and issues.  
https://try.gitea.io/api/swagger#/issue/issueListIssues

If let's say there are 10 open issues and 2 open PRs, open issue count is 10. While issues API return 12 records inlcuding PRs.

Just an idea, inlucde the open PRs in the count OR exlucde PRs from the issues API.

**Comment by 6543** [comment]
with https://github.com/go-gitea/gitea/pull/12275 `X-Total-Count` header can be used

**Comment by 6543** [comment]
@mmarif4u does  #12275  close this?

**Comment by mmarif4u** [comment]
@6543 I guess this is pretty much resolved.
