### ISSUE TITLE
a problem with the navigation bar style

### ISSUE THREAD

**Issue by leafney** [go-gitea/gitea#6776]
- Gitea version (or commit ref): gitea/gitea:1.8.0   799f5e0
- Git version:
- Operating system: docker
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description
Used Docker of gitea/gitea:1.8.0
I found that the style of the navigation bar has some problems. When I add `background-color:red;` to `.full.height` class , the display looks like this. But I didn't find this problem in https://try.gitea.io . I saw that the version is different. I don't know if it has been fixed.

```
.full.height {
    flex-grow: 1;
    padding-bottom: 80px;
    background-color: red;
}
```

## Screenshots

![](https://qiniu.itfanr.cc/blog/20190427170938.png?imageslim)

**Comment by silverwind** [comment]
Pretty sure this was fixed in https://github.com/go-gitea/gitea/commit/dc52868e1e36af5db9db4472c58397544fdf17c7.

**Comment by lunny** [comment]
so @silverwind  could you send a back port of #6553 to release/v1.8 ?

**Comment by silverwind** [comment]
https://github.com/go-gitea/gitea/pull/6781

**Comment by techknowlogick** [comment]
Closed per merged PR
