### ISSUE TITLE
Mirroring of external repository does not work after rebase

### ISSUE THREAD

**Issue by samangh** [go-gitea/gitea#6783]
- Gitea version (or commit ref): 1.8.0 built with go1.12.4
- Git version: 2.21.0
- Operating system: Linux Debian
- Database (use `[x]`):
  - [ x] MySQL
- Can you reproduce the bug at https://try.gitea.io:
  - [ x] Yes 

## Description

If gitea is mirroring an external repository and the external repository undergoes a rebase or a force push (so that the histories diverge), then the mirrored repository fails to show those changes.

Steps to reproduce:

1. Create a repository with an inital commit on GitHub
2. Mirror this with gitea
3. Reword the initial commit, and force push up to Github
4. Observe that the changes are not shown on the master branch of the mirrored repository

For an example please see https://try.gitea.io/samangh/teset, which is supposed to be a mirror of https://github.com/samangh/test.

**Comment by samangh** [comment]
Interesting, if I delete the repository manually and then re-create with `git clone --mirror`, then gitea correctly mirrors the repository even if after forced pushes.

**Comment by yasuokav** [comment]
Have you ever modified "Mirror Interval"?

**Comment by yasuokav** [comment]
My mirror repo is getting weird after #6593 merged, can you check it? @zeripath 

The mirror is unable to update the new commits to the proper branch after I update the mirror settings.

xxxxx.git/config:

before:
```
[core]
    ...
[remote "origin"]
	url = https://xxxx
	fetch  = +refs/*:refs/*
	mirror = true
```
after mirror settings updated:
```
[core]
    ...
[remote "origin"]
	url = https://xxxx
	fetch = +refs/heads/*:refs/remotes/origin/*

```

**Comment by samangh** [comment]
> Have you ever update the mirror settings on the settings page?

No. I've just tried to manually mirror things by pressing the 'Sync' button.

Interesting, this is not 100% reproducible. I just setup another mirror on my local gitea server and the mirroring worked fine even with rebases. However, the example mirror that I setup on https://try.gitea.io/samangh/teset is still broken.

**Comment by zeripath** [comment]
Hmm... I wonder if this needs to be

```go
_, err = git.NewCommand("remote", "add", "origin", "--mirror", addr).RunInDir(repoPath)
```
