### ISSUE TITLE
请问我要如何升级呢？

### ISSUE THREAD

**Issue by bajins** [go-gitea/gitea#6786]
如果我要升级到最新版本，请问我要如何操作呢？
![image](https://user-images.githubusercontent.com/30252550/56863614-48231300-69eb-11e9-9602-6d356220d1e5.png)
![image](https://user-images.githubusercontent.com/30252550/56863620-5c671000-69eb-11e9-8de2-dcf5fe8b2f92.png)
使用最新版本需要手动修改这个文件！

**Comment by lafriks** [comment]
Please change title and description in English
