### ISSUE TITLE
Service worker js is a missing comma

### ISSUE THREAD

**Issue by dmolik** [go-gitea/gitea#6787]
https://github.com/go-gitea/gitea/blob/e6161b09fffe53273b6b91435f0dca39053920c8/templates/pwa/serviceworker_js.tmpl#L37

and 

https://github.com/go-gitea/gitea/blob/e6161b09fffe53273b6b91435f0dca39053920c8/templates/pwa/serviceworker_js.tmpl#L40

**Comment by lafriks** [comment]
Would you be willing to send PR?
