### ISSUE TITLE
Tests about Oauth with CI

### ISSUE THREAD

**Issue by CorentinWanteeed** [go-gitea/gitea#6798]
Hello,

After 1.8 was published, two branches has been merged to add Oauth feature with CI (Drone as my example), first was the feature and the second a patch (https://github.com/go-gitea/gitea/pull/6747) to fix a miss.

Could some tests be added for this feature ? Nothing was made about this and i think it is very sensitive. As we can see since the 1.8 publishing, i (and other people) have some problem with this feature and consequently the architecture of these people has broken.

Thank you :)
Regards,

**Comment by jonasfranz** [comment]
The oauth2 feature has integration and unit tests. you can propose test cases if you know more possible cases then already defined.
