### ISSUE TITLE
ERROR: template: repo/view_list:82:38: executing "repo/view_list" at <$commit.Summary>: invalid value; expected string

### ISSUE THREAD

**Issue by bkraul** [go-gitea/gitea#6800]
- Gitea version (or commit ref): ccf4783
- Operating system: docker (Ubuntu 18.04 LTS).
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
Pushing a latest commit to my project's fork (develop branch) I get this error message when I try to browse the fork's home:

```
template: repo/view_list:82:38: executing "repo/view_list" at <$commit.Summary>: invalid value; expected string
```

My last commit message is nothing special:
```
 git commit -m "Completed Agent handling. Introduced fluent validation"
```

Other repositories, including the upstream of the project I am forking appears fine. Why would this one be causing an issue?

**Comment by bkraul** [comment]
This error is **not** occurring with gitea docker tag 1.8.0. (commit 799f5e0). I suppose I am going to start archiving develop builds.

**Comment by adelowo** [comment]
Looks like a duplicate  of https://github.com/go-gitea/gitea/issues/6708

See this comment , does it apply to the files in your most recent commit 

https://github.com/go-gitea/gitea/issues/6708#issuecomment-487385367

**Comment by bkraul** [comment]
Yup, it applies (`.editorconfig`). Tracking OI now.
