### ISSUE TITLE
2FA OTP auth refuses code

### ISSUE THREAD

**Issue by arren-ru** [go-gitea/gitea#6805]
- Gitea version (or commit ref): 1.8.0
- Git version: 2.21.0
- Operating system: Archlinux
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

OTP auth refuses codes when registration was completed using early generated code in time window. I mean when next code generation window just started and code appears, this code was used to apply the OTP second factor.

So, when signin procedure requires OTP after login/password it should be done in same manner - early generated code, but it shouldn't be because of large time window. Seems the window in Gitea much smaller than usual 30s or might be shifted.

## Screenshots

![image](https://user-images.githubusercontent.com/828187/56945322-07dda500-6b51-11e9-8113-75ca8c7d3dfd.png)

**Comment by mdeboer** [comment]
Silly question maybe but have you checked your time(zone) settings? I use OTP on 1.8.0 and never had any issues.

**Comment by SagePtr** [comment]
It's advised to setup NTP on server, so its time will always be close to correct one. And turn on time synchronization on device you use for 2FA.

**Comment by arren-ru** [comment]
Didn't have opportunity to answer, I'll check that version with time synchronization.

**Comment by arren-ru** [comment]
Enabled systemd-timesyncd on host and all become fine with OTP
