### ISSUE TITLE
The language setting does not work when the browser restart

### ISSUE THREAD

**Issue by happystraw** [go-gitea/gitea#6808]
- Gitea version (or commit ref):1.8.0
- Git version:2.17.1
- Operating system:Ubuntu 19.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

> Browser: Chrome Version 74.0.3729.108
>
> Chrome > Settings > Languages > Order languages based on your preference: 
>
> - Chinese (Simplified)
> - Chinese
> - English
> - Chinese (Traditional)

How to reproduce:

1. Sign in with option `Remember Me`
2. `Setting > Public Profile > Language`: choose `English`
3. Close all windows, exit Chrome
4. Start Chrome and reopen website, such as  `try.gitea.io/`
5. The language of page will be Chinese, but `Setting > Public Profile > Language`  is still `English`

The language of page will be reset to the browser's default language

## Screenshots

![demo20190430_161253](https://user-images.githubusercontent.com/18533666/56950145-5dbd4780-6b67-11e9-910e-9c5741814c48.gif)

**Comment by adelowo** [comment]
There is an issue for this already I believe

**Comment by lunny** [comment]
duplicated with #4884
