### ISSUE TITLE
Submit the history html 404 pushed by client

### ISSUE THREAD

**Issue by ayanjoyful** [go-gitea/gitea#6809]
- Gitea version (or commit ref):
- Git version:1.7.6
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [*] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
![QQ图片20190430173321](https://user-images.githubusercontent.com/28719668/56953016-243c0a80-6b6e-11e9-967a-be6c8230dd5e.png)
As shown in figure:
The commit history in the red circle is from the client,Click on the error.Page 500.
Background the log Error Page 404
...

**Comment by lunny** [comment]
Could you confirm that v1.8.0 fix that?

**Comment by saitho** [comment]
Did you click on the commit hash or did you click on the commit message (7777777777)?
If latter one: that is because Gitea sees that as a possible SHA hash and links it to a commit.

Example on try.gitea.org (latest commit): https://try.gitea.io/saitho/test/commits/branch/test2

**Comment by mrsdizzie** [comment]
For consistency we probably shouldn't render the commit Subject with the post processors so there aren't any autolink type things generated -- which means every Subject in that main list view will link to the actual commit without the chance that some link elsewhere. 

Separate, this is probably another instance where if we checked if a hash existed first it wouldn't generate the link (though none of these subjects should end up links to elsewhere even if they are valid).

**Comment by lunny** [comment]
It seems this should be backport to release/v1.8
