### ISSUE TITLE
New oauth2.JWT_SECRET is missing from gitea generate secret

### ISSUE THREAD

**Issue by segevfiner** [go-gitea/gitea#6810]
- Gitea version (or commit ref): v1.8.0
- Git version: 2.20.1
- Operating system: Alpine 3.9.3
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
There is a new secret in the Gitea config since 1.8.0 (I think) named `oauth2.JWT_SECRET` but there is no command to per-generate it under `gitea generate secret`. That is, there is no `gitea generate secret JWT_SECRET`.

**Comment by techknowlogick** [comment]
`LFS_JWT_SECRET` can be used for oauth as well, but I'm going to keep this ticket open to update the command to be just `JWT_SECRET`.
