### ISSUE TITLE
Use runtime/debug for providing the version

### ISSUE THREAD

**Issue by sapk** [go-gitea/gitea#6812]
Since go1.12 we can get the version from runtime/debug for the main module (gitea itself) and also submodules (lib) we are using. https://github.com/golang/go/commit/45e9c5538b3956d98ef0337fc19ed8d45eb17090

So when we will only support 1.12 and 1.13 we could migrate to this system and clear some makefile and also wiil fix #4782 since we will not rely on env variable.

**Comment by zeripath** [comment]
This is probably fixed by #6836 and its backport #6839

**Comment by sapk** [comment]
This isn't the same. I suggest to use the fact that the module version (tag) is now available when building with mod. This will remove any need for a lot  of line in makefile.

**Comment by wxiaoguang** [comment]
I do not think Go's module version works well nor it satisfies Gitea's version mechanism.

`https://github.com/golang/go/issues/29228`

Correct me if I am wrong, feel free to re-open if there are more details or feasible plans.
