### ISSUE TITLE
'Issue' page issues

### ISSUE THREAD

**Issue by davydov-vyacheslav** [go-gitea/gitea#682]
Gitea version: latest (1.0.0+116-g69b86378   (by the way ... the footer shows 2016 year ;) )
Reproducible on try.gitea.io: https://try.gitea.io/davs/test-issue3/issues/1
Browser: safari

Hi,
there is some kind of bug in links on issue page:

I just did created issue in the project: https://try.gitea.io/davs/test-issue3/issues/1

and there are 2 broken links:
- one is on 'davs commented xxxx seconds ago': links to 
https://try.gitea.io/davs/test-issue3/issues/%!(EXTRA%20string=issue-51,%20template.HTML=%3Cspan%20class=

- second is on the comment entry: links to https://try.gitea.io/davs/test-issue3/issues/%!(EXTRA%20string=issue-51,%20template.HTML=%3Cspan%20class=
BTW, this issue is reproducible only when I access as unregistered user

![_1_-_test_issue_-_gitea__git_with_a_cup_of_tea](https://cloud.githubusercontent.com/assets/9931946/21995802/84eb06c2-dc2f-11e6-9403-245caa478351.png)

**Comment by tboerger** [comment]
Looks like this is related to the russian translation, on the english version everything is fine.

**Comment by Bwko** [comment]
This gets fixed when #657 gets merged

**Comment by einacio** [comment]
There's a similar bug in the spanish translation

this line:
```
issues.commented_at=`comentado <a href="#%s"> %s`</a>
```

should read:
```
issues.commented_at=`comentado <a href="#%s">%s</a>`
```


should I file a different issue since it's another language?

**Comment by lunny** [comment]
@einacio please fire another issue. I will close this issue since #657 merged.

**Comment by lunny** [comment]
Or maybe you could send a PR instead of an issue since you have know where is the problem.
