### ISSUE TITLE
Internal Wiki link return a 404 error

### ISSUE THREAD

**Issue by PiDroid-B** [go-gitea/gitea#6828]
- Gitea version (or commit ref): 1.8.0
- Git version: 2.11.0
- Operating system: Debian 9
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes ([example URL wiki-https-url](https://try.gitea.io/pidroid/wiki-https-url))
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
- Create a repository
- Click on Wiki tab and create a new page
- Show this page
- Copy https link on the top-right part of this page
- Open this link in webbrowser

==> Gitea return a 404 error

Repository OK : 
https return for repo : https://sub.domain.com/orga/repos.git   

Internal Wiki  Repo 404 Error : 
https returned for wiki : https://sub.domain.com/orga/repos.wiki.git
instead of https://sub.domain.com/orga/repos/wiki ?

**[EDIT]**
concern the webbrowser navigation only, the git cloning works well.

#### Cloning
`git clone https://sub.domain.com/orga/repos.git` :heavy_check_mark:
`git clone https://sub.domain.com/orga/repos.wiki.git` :heavy_check_mark:
It works well

#### Web navigation
`https://sub.domain.com/orga/repos.git` :heavy_check_mark:
`https://sub.domain.com/orga/repos.wiki.git` :x:
Different behavior between repo and this wiki

Maybe it doesn't matter...
**[/EDIT]**

## Screenshots

![Capture du 2019-05-02 15-04-31](https://user-images.githubusercontent.com/50204347/57077245-d2b98a00-6ceb-11e9-8577-043ade216bc5.png)

**Comment by techknowlogick** [comment]
Closing per comments on discord.
