### ISSUE TITLE
Add server config option for always rendering html code

### ISSUE THREAD

**Issue by pgaskin** [go-gitea/gitea#683]
- Gitea version (or commit ref): 1.0.1
- Git version: 2.9.3
- Operating system: Alpine Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant

## Description

I have a few repos of HTML code, in a repository on a server which only me and people I trust access. I would like there to be a server configuration option to always render html in repos. I am willing to add this feature myself.

**Comment by tboerger** [comment]
Are you talking about a feature like https://github.com/go-gitea/gitea/issues/302?

**Comment by pgaskin** [comment]
Not exactly

**Comment by pgaskin** [comment]
More like allowing rendering of files in the repo.

**Comment by tboerger** [comment]
Can you explain the use case for that? I don't get it yet ;)

**Comment by pgaskin** [comment]
I have repository with HTML templates. I would like to preview them easily without them being in a separate location. I trust all users with write access to the server, so I want to simplify things by allowing rendering it right out of the repository.

**Comment by pgaskin** [comment]
Something like changing the `ServeData` function in `routers/repo/download.go` to this:

````
func ServeData(ctx *context.Context, name string, reader io.Reader) error {
	buf := make([]byte, 1024)
	n, _ := reader.Read(buf)
	if n > 0 {
		buf = buf[:n]
	}

	ctx.Resp.Header().Set("Cache-Control", "public,max-age=86400")

	// Google Chrome dislike commas in filenames, so let's change it to a space
	name = strings.Replace(name, ",", " ", -1)

        if setting.Repository.AlwaysRenderRawFiles {
		ctx.Resp.Header().Set("Content-Disposition", fmt.Sprintf(`inline; filename="%s"`, name))
	} else if base.IsTextFile(buf) || ctx.QueryBool("render") {
		ctx.Resp.Header().Set("Content-Type", "text/plain; charset=utf-8")
	} else if base.IsImageFile(buf) || base.IsPDFFile(buf) {
		ctx.Resp.Header().Set("Content-Disposition", fmt.Sprintf(`inline; filename="%s"`, name))
	} else {
		ctx.Resp.Header().Set("Content-Disposition", fmt.Sprintf(`attachment; filename="%s"`, name))
	}

	ctx.Resp.Write(buf)
	_, err := io.Copy(ctx.Resp, reader)
	return err
}
````
The setting `AlwaysRenderRawFiles` would have to be added to `setting.go` with a default of false (for security)

**Comment by pgaskin** [comment]
I will open a PR

**Comment by pgaskin** [comment]
I have opened the PR, and it is ready. I have tested the feature myself too.

**Comment by tboerger** [comment]
What do others think about that? I don't really like the idea to render every document/file.

**Comment by pgaskin** [comment]
@tboerger I think that even though it is a security risk in most cases, there may be some cases, including my own, where it is needed. It really is not much of a security risk of there is only a few trusted people who are able to write to our create repositories.

**Comment by pgaskin** [comment]
@tboerger Also, in the issue about XSS with gogs' current implementation which is a ?render parameter, the author of the issue suggests for the option to be moved to the config file https://github.com/gogits/gogs/issues/3608

**Comment by pgaskin** [comment]
One example of people needing an option like this: https://github.com/gogits/gogs/issues/2593

**Comment by pgaskin** [comment]
Another few examples: https://github.com/gogits/gogs/issues/2283#issuecomment-181426550 and https://github.com/gogits/gogs/issues/2283#issuecomment-182239213 

The last one I put cannot be solved using something like GitHub pages because it involves viewing rendered raw history of a file

**Comment by tboerger** [comment]
IMHO this is something to solve for a separate tool. Many users don't get know how important this option can get

**Comment by pgaskin** [comment]
What if we do not document the option?

**Comment by bkcsoft** [comment]
I _really_ don't like undocumented options... Someone will see it in the code and turn it on without knowing the consequences of that... I'm with @tboerger on this one, Gitea is not made to work like a CDN, there are _many_ other projects out there that fit the purpose better. [Caddy](caddyserver.com) can even be setup to monitor your git-repo and [automagically serve](https://caddyserver.com/docs/git) from that.

**Comment by bkcsoft** [comment]
If I am to be completely honest, I vote to remove the `?render=1` option as well, since it is a _huge_ security-risk... or at least make a config-flag to disable it (though for backwards-compat I might consider having it enabled by default 😒 )

**Comment by lunny** [comment]
same with #685

**Comment by pgaskin** [comment]
Doesn't the csrf request token prevent this from being a security risk? If we make it not set the csrf cookie when sending the page, then wouldn't this be perfectly fine?

**Comment by strk** [comment]
How about clearly describing the security risk, in the current documentation ?
Because I understand the risk you see is already there.

**Comment by pgaskin** [comment]
@strk Yes, and also, I use this patch in my server, and many of my friends do as well. There have not been any problems so far. How should it be described?

**Comment by strk** [comment]
@geek1011 as @bkcsoft did on [IRC](https://kiwiirc.com/client/irc.freenode.net/#gitea):

```
18:49 < BKC> okey, here it goes. It is _extremly_ simple to make a HTML-file 
with a small script in that will take your CSRF-token and session-key, send 
those to a server that changes your password and stores that "for later use"
```

**Comment by lunny** [comment]
But my point is we can genearte files and push the files to servers.
we can push files via local/ssh/ftp/coloud storage/http and etc.
setup a hook running on Gitea itself.

Copy my point from Gitter.

And we can detect the repo's types. Hugo maybe the first type and other formats.
