### ISSUE TITLE
Display note about merge conflicts on WIP pull requests

### ISSUE THREAD

**Issue by saitho** [go-gitea/gitea#6831]
When a pull request is WIP it does not show if the branch has merge conflicts.
So, you can only see that a branch has merge conflicts when you remove the WIP from the pull request title.

I believe that to be important, since resolving the merge conflict would be part of the things to do. Therefore I suggest we also show that information, even if the PR is in WIP.

**Comment by saitho** [comment]
Gitea seems to already do that. Strangely that it didn't in our Gitea instance which I believe to be v1.8.1.

**Comment by lunny** [comment]
I don't remember any PR to resolve that.

**Comment by saitho** [comment]
I made a merge conflict on try.gitea.io:
https://try.gitea.io/saitho/test2/pulls/2

It does show which files are conflicted and the pull request is in WIP... :man_shrugging:

**Comment by lunny** [comment]
Thanks! @saitho
