### ISSUE TITLE
make links more visibles

### ISSUE THREAD

**Issue by Aviortheking** [go-gitea/gitea#6844]
- Gitea version (or commit ref): 1.9.0+dev-191-g2933ae4e8
- Git version: not relevant
- Operating system: linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
  - [x] Not relevant
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

Actually all different link in a commit have no differences  
maybe it could be changed to underline the current link like what github does

## Screenshots

![image](https://user-images.githubusercontent.com/15822031/57178300-5602e900-6e6e-11e9-8b0c-c5549a6ce94f.png)

**Comment by mrsdizzie** [comment]
This behavior will change after #6842 is merged where the text will only link to the commit in the list view

**Comment by Aviortheking** [comment]
oh ok so links will only go to the commit after taht ?

**Comment by mrsdizzie** [comment]
Yes, in the list view it only goes to the commit now. See:

 https://try.gitea.io/mrsdizzie/linktesting

When you click the commit you still get a link to the issue/PR in the summary on the commit view

**Comment by Aviortheking** [comment]
OK thanks !
