### ISSUE TITLE
Automatically translate before send translation to crowdin

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#6857]
We could also add automatically translations on some step of drone before uploading it to crowdin. But we should only change that changed items and added items on language files. That should reduce many translation operations. Anyone know any drone plugin could do that?

**Comment by lafriks** [comment]
I don't think automatic translation is good idea

**Comment by lunny** [comment]
@lafriks not entirely automatic translation. It also needs confirmation from human at the end but will reduce many time.

**Comment by lafriks** [comment]
Crowdin already shows automatic translation below that you can use

**Comment by lunny** [comment]
@lafriks right, Crowdin has, but we could click one less if automatic translation have filled that.

**Comment by comradekingu** [comment]
This is not a good idea. I don't understand why Weblate isn't used, but things being what they are, it doesn't need to be made more difficult to translate Gitea.

**Comment by lunny** [comment]
I think this cloud be closed.
