### ISSUE TITLE
cant find repository file

### ISSUE THREAD

**Issue by MajidDehnamaki** [go-gitea/gitea#6858]
hi.
I install gitea in my windows server and use PostgreSQL for the database.
everything is ok but I can't find my repository file
where gitea save them? I see git file in repository folder but cand find project file.

**Comment by lunny** [comment]
git bare repositories will not include work tree.

**Comment by MajidDehnamaki** [comment]
@lunny I don't understand
I have some file in a repository like README.md but i can't find them

**Comment by lunny** [comment]
I think you should know how git store the files at first.

**Comment by zeripath** [comment]
You need to clone your repository from Gitea over SSH through the Gitea user or http(s), the folders that represent Gitea's internal repositories should not be used directly except by Gitea.

**Comment by MajidDehnamaki** [comment]
thank for your help,i read about how git store the files and i understand.
