### ISSUE TITLE
Gitea dump not working

### ISSUE THREAD

**Issue by mjwwit** [go-gitea/gitea#686]
- Gitea version (or commit ref): 1.0.0+129-g6dd096b7
- Git version: n.a.
- Operating system: Official Docker image
- Database:
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:
Running `gitea dump -d postgres` yields:
https://gist.github.com/mjwwit/bbc97d024a12a286f27cd75b11ac5376

## Description
Trying to dump Gitea data using `gitea dump` on a gitea setup using sqlite3 causes the `SIGSEGV` error in the gist linked above. The output database format does not matter, the same error seems to happen regardless of the `-d` flag value (it even happens when the flag is absent).

**Comment by lunny** [comment]
Cannot reproduce it. How do you install Gitea?

**Comment by mjwwit** [comment]
I used the `latest` docker image yesterday.

**Comment by mjwwit** [comment]
I just tried to reproduce the issue by creating a clean Gogs setup, adding some testing data, upgrading it to Gitea, and then using `gitea dump`. This, however, seems to work just fine...

Can you guys think of a way I can debug what's going on?
