### ISSUE TITLE
GPG Key validation

### ISSUE THREAD

**Issue by vv01f** [go-gitea/gitea#6863]
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
- [x] Other stuff not relevant for the reported error.

## Description

tl;dr: validation of email address in the key material is wrong.

> This GPG key is not usable with any email address associated with your account.

This error message comes up when adding a pgp key without email address ([example](https://pgp.surfnet.nl/pks/lookup?search=0x9CD3A46248B660CA&fingerprint=on&op=index)), or supposedly with another email address, than the account got added with sending a confirmation code already … there are good reasons not to include addresses in the key, such as:
* not linking different addresses
* not having to use many keys
* not publishing addresses along with public keys

I want to argue:

1. A PGP public key does not need to contain an email address, in fact it's a bad practice anyways.
2. The addresses added to the account can be validated by confirmation codes and thus proof access to the account.
3. Validation for public keys should be done via encrypting a message and let the alleged bearer proof that he can decrypt.
4. Despite the link to [GitHub documentation](https://help.github.com/articles/about-gpg/) the behaviour of gitea is different as GitHub simply accepts such keys.

I suggest to make this error a warning and let the user proceed to use the key if he intends to. If validation is an important goal, the actual key material should be validated, not it's metadata.

**Comment by Dark-Feather** [comment]
@vv01f My domain is impacted in a similar way -- notably, we don't use SMTP at all. We worked around it by a couple principles in our deployment.
* We self-host Gitea, IRC, and OpenLDAP. 
* Gitea and IRC both disallow account creation and populate directly from OpenLDAP
* The mail attribute on our OpenLDAP accounts is set to `ircs://$domain:$port/$USER`
* Our GPG keys can have this attribute set by using `gpg --edit-key --allow-freeform-uid $keyid`
* Users set `git config user.email` to their mail attribute.

This allows us to tie the contact information on the GPG key and Git commits to the contact method of the organization for that identity -- email addresses and other external contact information are thus separated.

**Comment by maisiliymBridj** [comment]
Indeed, it would make a lot more sense if gitea asked the user to sign a nonce to prove ownership.

**Comment by LordMZTE** [comment]
Is anyone looking into fixing this? I'm having trouble adding my GPG key to my gitea instance because of this. Is there a workaround?

**Comment by techknowlogick** [comment]
Closing as there is a way to validate GPG keys without requiring emails
