### ISSUE TITLE
OAuth2 with MS Azure not working

### ISSUE THREAD

**Issue by Mr-Reca** [go-gitea/gitea#6866]
- Gitea version (or commit ref): 73ce024 with Go 1.12.1
- Git version: 2.13.7
- Operating system: openSUSE Leap 42.1
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:

## Description
I configured an Authentication Source using this guide [https://blog.anoff.io/2019-03-23-configure-azure-ad-for-gitea/](url) so I can use Azure Active Directory for authenticate the users.

After the 2FA, the browser shows the error `AADSTS50011: The reply url specified in the request does not match the reply urls configured for the application`.  I checked the redirect_uri and it has this format: `https://<host>:3000/user/oauth2/gitea/callback`

gitea.log has this error when I go to that page (with error 500):
`routers/user/auth.go:560 handleOAuth2SignIn()] [E] UserSignIn: could not find a matching session for this request`

I'm using MariaDB Ver 15.1 Distrib 10.0.30-MariaDB

**Comment by lunny** [comment]
Have #6345 fixed your problem?

**Comment by Mr-Reca** [comment]
I tried
