### ISSUE TITLE
Can't add ldap simple auth source

### ISSUE THREAD

**Issue by jcgruenhage** [go-gitea/gitea#687]
- Gitea version (or commit ref):1.0.0+126-g302fa429 (pulled from docker in the last few days
- Git version: has nothing to do with git
- Operating system: official docker container on a fedora host
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
Gitea prompts me to fill out "this field" with an arrow to the top left corner, where no field is.
I have filled out all required fields.
[I have put a demonstration of this behaviour on youtube.](https://youtu.be/v5-9wQ-KZxk)

It works fine via BindDN, so this is not that bad, but it would be better if simple auth worked too, since I gitea is now the only of my five or so webapps that has an entry in my ldap database..

**Comment by Bwko** [comment]
It tries to mark the `user_base` field, which is invisible when you select `LDAP (aimple auth)`
The console shows the following error: `An invalid form control with name='user_base' is not focusable.`

@shyim Could you take a look at this?

**Comment by tatref** [comment]
Hi,

I experience the same issue with LDAP BindDN authentication.
