### ISSUE TITLE
Wrong day when populating activity heapmap

### ISSUE THREAD

**Issue by dpedu** [go-gitea/gitea#6879]
- Gitea version (or commit ref): 1.9.0+dev-221-g4508380cf
- Git version: 2.20.1
- Operating system: Ubuntu 14.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL) - https://try.gitea.io/dpedu?tab=activity
  - [ ] No
  - [ ] Not relevant
- Log gist: No messages that correlate with this activity are logged on my instance.

## Description

When I perform some contributing-like activity on a Gitea instance (such as pushing commits, creating a repo, etc), Gitea populates a graphical heatmap of activity shown on my account's profile.

Gitea often highlights the wrong day when this is done. Seen screenshots.

On try.gitea.io, I performed the following steps to produce the screenshot below:

- Created an account on May 8 at around 8:50 AM Pacific time
- Created an empty repo.

The site correctly shows this on my profile, `Joined on May 08, 2019`. However, the heatmap put this activity under May 7th instead of the 8th, labeling me as a time traveler.

I use Gitea's official docker image - https://hub.docker.com/r/gitea/gitea/, which exhibits the same problem. I was unable to find any gitea config file settings relevant to time zones or time offsets. Gitea did not obey either setting the `TZ` env var (to `America/Los_Angeles`) nor  `/etc/localtime` nor `/etc/timezone`.

The expected result is that contributions show up on the day they were actually pushed into gitea.

## Screenshots

<img width="1207" alt="Screen Shot 2019-05-08 at 8 56 16 AM" src="https://user-images.githubusercontent.com/1266188/57389527-38d06200-716f-11e9-8b2b-2b82fb20fbfd.png">

**Comment by jolheiser** [comment]
Same as #6087?
