### ISSUE TITLE
How to insert the result of coverage(lcov.info) to gitea markdown?

### ISSUE THREAD

**Issue by droplet-js** [go-gitea/gitea#6880]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

...

**Comment by lunny** [comment]
You can create/edit file via API or just push your git change in README.md

**Comment by v7lin** [comment]
lcov.info 文件是由 flutter test --coverage 命令执行生成的，我想再 README.md 中动态引入，并不想执行完命令后手动 copy 到 README.md 中。

**Comment by lunny** [comment]
You should create a CI bot to update the `README.md` I think.

**Comment by v7lin** [comment]
这不是个好主意，每次commit都会触发coverage，使用使用ci工具额外再提交一次commit，岂不陷入无限循环么？

**Comment by lunny** [comment]
The bot commit could be skipped by bot itself.

**Comment by v7lin** [comment]
即使对ci触发条件作控制，也会增加一倍的commit。这不是个好主意
