### ISSUE TITLE
Misleading description at branch protection settings

### ISSUE THREAD

**Issue by jbeyerstedt** [go-gitea/gitea#6886]
- Gitea version (or commit ref): eb8632b

## Description
As also discussed in #6817, the description texts at the branch protection settings do not exactly describe, what will happen. This lead to confusion, when force pushing will be disallowed and when a "normal" push will also not be possible.

The text at the "Enable branch protection" checkbox says:
> Prevent deletion and disable Git force pushing to the branch.

This is would be, what I expect to happen, when the checkbox is activated. No-one will be able to delete this branch and force pushing will also not be possible. But the issue is, that any kind of pushing is disabled (which is not, what the text says).
> Then there is the "Enable push whitelist" button, which has the explanation:

Allow whitelisted users or teams to bypass push restrictions.
This does not clearly say, if the whitelist will only be allowed to push normally, or also be allowed to force push.

## Screenshots
![Bildschirmfoto 2019-05-09 um 07 53 30](https://user-images.githubusercontent.com/4568682/57430314-8f04da00-722f-11e9-8389-b1a82673d8e7.png)

**Comment by zeripath** [comment]
@jbeyerstedt do you think this just needs a simple change of wording?

If so, could you send a PR with your proposed changes? The settings are around:

 https://github.com/go-gitea/gitea/blob/2f21bc33a528894c085bf944666f668725f04d8a/options/locale/locale_en-US.ini#L1272

**Comment by jbeyerstedt** [comment]
Yes, this issue is just about the wording.
Thanks for the hint, where to find the description strings. I'll try to get into this and submit a pull request on the weekend.

**Comment by jbeyerstedt** [comment]
@zeripath Here's your pull request. (Now opened in the right repo)
And as I write, it was approved by someone. Thanks.
