### ISSUE TITLE
Issue links in pull request always point to the internal tracker

### ISSUE THREAD

**Issue by otbutz** [go-gitea/gitea#6888]
- Gitea version (or commit ref): 1.8.0
- Git version: 2.21.0
- Operating system: Ubuntu 18.04
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant

## Description
Mentioning an issue works properly in the main view of the repository. e.g a commit with `#123` in its message properly links to our Redmine issue tracker.
But if i use the same format in the description or in a comment of a pull request, the link points to the deactivated internal issue tracker.

**Comment by mrsdizzie** [comment]
Can you reproduce this in an example (on try.gitea.io) or give an exact list of steps to reproduce? I've tried to reproduce but it appears to work fine:

 https://try.gitea.io/mrsdizzie/test_issues/pulls/1#issuecomment-11512

**Comment by otbutz** [comment]
I've already tried to reproduce it but it worked fine on the test server.

The funny thing is that it now seems to work after I switched the Issue Tracker back and forth. It still looks like an error to me, as the settings were correct, but the pull request web page behaved incorrectly in the browser of a coworker who had not yet visited the page.

**Comment by mrsdizzie** [comment]
If you can reproduce it at all, let us know. Not saying there isn't possibly an error somewhere but without being able to see it there isn't anything to look at.

**Comment by otbutz** [comment]
I'm going to report the issue if i can reproduce it again. So far no problems with 1.8.0 and 1.8.1
