### ISSUE TITLE
[meta] Problem using try.gitea.io

### ISSUE THREAD

**Issue by BNolet** [go-gitea/gitea#6890]
When making an issue, you're asked if you can reproduce an issue and are invited to reproduce it on try.gitea.io

The problem is that at the time of writing this issue, the release is 1.9.0+dev-223-g6db3dc7c0. This is later than the 1.8.1 release which is the latest 'stable' release. 

It's impossible to reproduce an issue reliably if the version of the public test server is higher than that of the latest stable release. 

Yes, I realize this means that whatever issue I was testing might have been resolved, but that's besides the point.

**Comment by adelowo** [comment]
The point of that is to make sure the bug has(not) been fixed.. In your case, if it is a ___serious___ bug, it will be backported to `1.8.X`

It is still fine if you can't replicate it on `try.gitea.io`, just state the version you are using, someone will definitely check it out

**Comment by techknowlogick** [comment]
Yes, what @adelowo said is correct.
