### ISSUE TITLE
U2F/2FA, how to enable it and enroll myself?

### ISSUE THREAD

**Issue by markg85** [go-gitea/gitea#6891]
Hi,

The documentation on this is _really_ sparse!
I can only find some 'hint' that it even is possible in Gitea, but any documentation on how to enable it seems to be either completely missing or named so weirdly that you can't find it.

Some examples:
https://docs.gitea.io/en-us/authentication/ (makes no mention of it, at all!)
https://docs.gitea.io/en-us/ (mentions it in the features, but that's all)
https://github.com/go-gitea/gitea/blob/master/custom/conf/app.ini.sample (here calls it U2F but no documentation on how to use it)
In the user settings under security this is mentioned: "Your account must be enrolled in two-factor authentication to use security keys." but absolutely no way of figuring out how to enroll a user to use that.

I don't want to criticize Gitea, it's a marvelous project :)
But having some documentation on how to use this feature would be really welcome! I haven't figured it out yet.

Best regards,
Mark

**Edit**
Apparently on the security settings page (fur the user) there is a big ass button to enroll in 2FA right in the first section. I apparantly just didn't catch that at all at first. I only noticed it when watching this video about the feature: https://www.youtube.com/watch?v=sA4Id3Sc72M

Still leaves the above as valid, just not "as bad" as i thought it was.

**Comment by arren-ru** [comment]
The secret it that you don't really need anything to do with config to enable U2F. All default settings works.
The only condition is that you must have `https` between browser and server. U2F works only in this case.
Than go to `settings/security` and enable OTP, after that U2F become available.
