### ISSUE TITLE
After creating a mirror, "mirror of..." does not show the repo URL 

### ISSUE THREAD

**Issue by plaimbock** [go-gitea/gitea#6896]
- Gitea version (or commit ref): 1.8.1
- Git version: 2.5.5
- Operating system: CentOS 7 x86_64
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X] No
  - [ ] Not relevant
- Log gist:

## Description
With v1.8.1, after creating a mirror, "mirror of..." does not show the repo URL. I tried the same on try.gitea.io and "mirror of..." does show the repo URL. So I guess this has already been fixed in master.
...

**Comment by zeripath** [comment]
Hi could you check that the git on your Gitea server has `git remote get-url`? I'm not certain that we didn't anything special to fix this on master.

**Comment by michaelx** [comment]
I experienced the same behavior as OP with Gitea 1.8.1 and git 2.1.4.

Gitea 1.8.2 fixed it. Issue was get-url #7065 #7076 as @zeripath assumed.
