### ISSUE TITLE
Branch dropdown menu does not work

### ISSUE THREAD

**Issue by kgraefe** [go-gitea/gitea#6899]
- Gitea version (or commit ref): 1.8.1 built with go1.12.5 (linux-arm-6)
- Git version: 2.11.0
- Operating system: Debian GNU/Linux 9.8 (stretch) 
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X] No
  - [ ] Not relevant
- Log gist:

## Description

When clicking on the branches drop down the menu does not open. The arrow gets an arrow and nothing more happens.

I see 18 warnings in the javascript console: `jquery.min.js:3 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952` but that's all.

Also in the source tree there's only the master branch although this repository has multiple branches.

I cannot reproduce that on https://try.gitea.io so it seems be an issue of my instance. But I don't know how to tackle it.

## Screenshots

![gitea-branches-dropdown](https://user-images.githubusercontent.com/3797324/57524861-652fde00-7329-11e9-8f7a-5fb0e95e9893.png)
![gitea-branches-dropdown-source](https://user-images.githubusercontent.com/3797324/57524863-652fde00-7329-11e9-90d7-c934698f998f.png)

**Comment by lafriks** [comment]
Do you see any errors in gitea.log?

**Comment by kgraefe** [comment]
Unfortunately not. With `log.LEVEL=Debug` it just gives:

```
2019/05/15 13:13:22 [I] Log Mode: File(Debug)
2019/05/15 13:13:22 [I] XORM Log Mode: File(Debug)
2019/05/15 13:13:22 [I] Cache Service Enabled
2019/05/15 13:13:22 [I] Session Service Enabled
2019/05/15 13:13:22 [I] Beginning ORM engine initialization.
2019/05/15 13:13:22 [I] ORM engine initialization attempt #1/10...
2019/05/15 13:13:23 [I] ORM engine initialization successful!
2019/05/15 13:13:24 [I] Git Version: 2.11.0
2019/05/15 13:13:24 [I] SQLite3 Supported
2019/05/15 13:13:24 [I] Run Mode: Production
2019/05/15 13:13:29 [I] Listen: http://0.0.0.0:3000
2019/05/15 13:13:32 [D] Session ID: xxxxxxxxxxxxxxxx
2019/05/15 13:13:32 [D] CSRF Token: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX==
2019/05/15 13:13:32 [D] Template: pwa/serviceworker_js
2019/05/15 13:13:40 [D] Session ID: xxxxxxxxxxxxxxxx
2019/05/15 13:13:40 [D] CSRF Token: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX==
2019/05/15 13:13:41 [D] Template: repo/home
2019/05/15 13:13:41 [D] Session ID: xxxxxxxxxxxxxxxx
2019/05/15 13:13:41 [D] CSRF Token: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX==
2019/05/15 13:13:41 [D] Template: pwa/manifest_json
2019/05/15 13:13:43 [D] Session ID: xxxxxxxxxxxxxxxx
2019/05/15 13:13:43 [D] CSRF Token: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX==
2019/05/15 13:13:43 [D] Template: pwa/serviceworker_js
```

**Comment by kgraefe** [comment]
It turned out to be my Apache reverse proxy configuration. I had `SetOutputFilter INFLATE;proxy-html;DEFLATE` which apparently breaks the menu.

**Comment by waltervanzellaGVT** [comment]
> 
> 
> It turned out to be my Apache reverse proxy configuration. I had `SetOutputFilter INFLATE;proxy-html;DEFLATE` which apparently breaks the menu.

I am having a similar problem,  as reported in issue  #9569.
I am a newby on these topics and I have no idea what to do.  Where can I find these Apache configuration file? and  what did you change in order to solve ?
Thank you.
W.
