### ISSUE TITLE
Gitea fails to build on aarch64

### ISSUE THREAD

**Issue by clandmeter** [go-gitea/gitea#691]
Im reporting this upstream and will refer to this issue.

code.gitea.io/gitea/vendor/github.com/ngaut/log
vendor/github.com/ngaut/log/crash_unix.go:16: undefined: syscall.Dup2

**Comment by tboerger** [comment]
Thank you for the report.

**Comment by lunny** [comment]
`github.com/ngaut/log` is only used by `tidb`. I think we have to take tidb tag back and make tidb not default. Because I find `tidb` cannot be shared read. So SSH will never be succeed. @tboerger

**Comment by lunny** [comment]
I move this to 1.2 since we have to take tidb tag back to resolve this issue.

**Comment by tboerger** [comment]
The upstream lib solved the issue, so at least we can update the lib and get gitea building in arm64

**Comment by lunny** [comment]
You mean tidb fixed the issue?

**Comment by lunny** [comment]
but that resulted in a new issue https://github.com/ngaut/log/issues/7. @ngaut

**Comment by lunny** [comment]
@clandmeter please confirm #1132
