### ISSUE TITLE
Home page switch user does not display warehouse

### ISSUE THREAD

**Issue by 1093439315** [go-gitea/gitea#6924]
- Gitea version (or commit ref):docker 1.9.0+dev-236-g5ffc9656c
- Git version:
- Operating system:centos 7
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description

Home page switch user does not display warehouse,Only one user is like this.It is a organization，Other tissues are normal。
this is not correct:
![image](https://user-images.githubusercontent.com/18135235/57590772-86c6da80-7560-11e9-9344-cd58fc9fbd04.png)
this is normal:
![image](https://user-images.githubusercontent.com/18135235/57590816-afe76b00-7560-11e9-956f-7914e831c212.png)

**Comment by 1093439315** [comment]
![image](https://user-images.githubusercontent.com/18135235/57590859-eae99e80-7560-11e9-81c1-e6526af0a494.png)

**Comment by zeripath** [comment]
I suspect that this would be fixed by my pr #6897. Are you able to build from that pr to check if it fixes your issue?

**Comment by 1093439315** [comment]
yes,it fiexd

**Comment by 1093439315** [comment]
> I suspect that this would be fixed by my pr #6897. Are you able to build from that pr to check if it fixes your issue?

yes it fixed
