### ISSUE TITLE
Repository rename with change owner generate log spam

### ISSUE THREAD

**Issue by DoubleF1re** [go-gitea/gitea#6929]
- Gitea version (or commit ref): 1.8.1 and below
- Git version: any
- Operating system: Debian 8.11
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:
2019/05/13 16:22:08 [...s/context/context.go:149 NotFoundOrServerError()] [E] GetRepositoryByOwnerAndName: repository does not exist [id: 0, uid: 0, owner_name: X, name: Y]
## Description

This message spamming in logs after I rename repository from Y to Z and then from Z to Z1 and then change repository owner. Message very often - one per minute.

**Comment by lunny** [comment]
The log should be displayed when someone visit a non-exist repository.

**Comment by DoubleF1re** [comment]
Yeah, thanx. Our Teamcity with broken configuration cause Gitea this exception.
