### ISSUE TITLE
Error opening Pull requests with changed git submodules

### ISSUE THREAD

**Issue by ukos-git** [go-gitea/gitea#6945]
- Gitea version:
- Git version: 345bc06
- Operating system: docker container
- Database:
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Log gist:

## Description

Opening a new pull request for a freshly pushed branch sometimes gives an error with an unformated html file and the following message in a `<pre>` tag:

```
template: repo/diff/box:109:21: executing "repo/diff/box" at <call $.IsImageFile $file.Name>: error calling call: runtime error: invalid memory address or nil pointer dereference
```

url for this is `gitea.xyz/user/repo/compare/master...branch`

Not sure if this helps but this is the last line of the gitea.log:

```console
_issues`, `05/14 12:03:42 ^[[0m^[[32m...xorm/session_find.go:195:^[[32mnoCacheFind()^[[0m ^[[1;32m[I]^[[0m [SQL] ^[[1mSELECT `id`, `repo_id`, `name`, `content`, `is_closed`, `num_issues`, `05/14 12:03:42 ^[[0m^[[32m...xorm/session_find.go:195:^[[32mnoCacheFind()^[[0m ^[[1;32m[I]^[[0m [SQL] ^[[1mSELECT `id`, `user_id`, `repo_id`, `mode` FROM `access` WHERE (repo_id 05/14 12:03:42 ^[[0m^[[32m...s/context/context.go:138:^[[32mHTML()^[[0m ^[[1;34m[D]^[[0m Template: ^[[1mrepo/pulls/compare^[[0m
```

**Comment by lafriks** [comment]
Could it be that it is for added or deleted files?

**Comment by ukos-git** [comment]
I did the following to fix the error:

* reset one file that was staged for deletion
* rebased the branch on current master
* took everything to a new branch

Now the pull request works but it feels like a workaround.

**Comment by saitho** [comment]
I just stumbled upon the same issue. In my case it happens when the diff contains a submodule.
Like here: https://try.gitea.io/saitho/test2/compare/noimage...submodule2

**Comment by ukos-git** [comment]
I also have submodules activated for that branch but I also have git lfs active. Is there a possibility to add a bit more debug output for what is happening here?

**Comment by lunny** [comment]
So the problem is when your PR has a submodule. @ukos-git Could you change the title?
