### ISSUE TITLE
Error when merge pull request

### ISSUE THREAD

**Issue by zongwei007** [go-gitea/gitea#6946]
- Gitea version (or commit ref): 1.9.0+dev-249-g8b36f01f4
- Git version: 2.20.1
- Operating system: docker
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

```txt

2019/05/14 12:11:57 ...orm/session_exist.go:79:Exist() [I] [SQL] SELECT "id", "org_id", "team_id", "uid" FROM "team_user" WHERE (uid=$1) AND "team_id" IN ($2) LIMIT 1 []interface {}{2, 28},
[Macaron] 2019-05-14 12:11:57: Started GET /api/internal/branch/69/master for 127.0.0.1,
2019/05/14 12:11:57 modules/auth/auth.go:97:CheckOAuthAccessToken() [T] ParseOAuth2Token: signature is invalid,
2019/05/14 12:11:57 ...s/context/context.go:308:func1() [D] Session ID: dad04db9e123606d,
2019/05/14 12:11:57 ...s/context/context.go:309:func1() [D] CSRF Token: o5QUfe4WWRuQbs-M3v_LlmRjt2I6MTU1NzgzNTkxNzIxMTM1MDExMA==,
2019/05/14 12:11:57 .../xorm/session_get.go:95:nocacheGet() [I] [SQL] SELECT "id", "repo_id", "branch_name", "can_push", "enable_whitelist", "whitelist_user_i_ds", "whitelist_team_i_ds", "enable_merge_whitelist", "merge_whitelist_user_i_ds", "merge_whitelist_team_i_ds", "approvals_whitelist_user_i_ds", "approvals_whitelist_team_i_ds", "required_approvals", "created_unix", "updated_unix" FROM "protected_branch" WHERE "repo_id"=$1 AND "branch_name"=$2 LIMIT 1 []interface {}{69, "master"},
2019/05/14 12:11:57 routers/repo/pull.go:605:MergePullRequest() [E] Merge: git push: From /data/git/repositories/project/shell-asset,
[Macaron] 2019-05-14 12:11:57: Completed GET /api/internal/branch/69/master 200 OK in 2.41096ms,
	 * [new branch]      feat_archive -> head_repo/feat_archive,
	 * [new branch]      fixBug       -> head_repo/fixBug,
	 * [new branch]      master       -> head_repo/master,
	Automatic merge went well; stopped before committing as requested,
	remote: Gitea: Internal error        ,
	remote: Fail to detect force push: chdir /data/git/repositories/shell-asset.git: no such file or directory        ,
	To /data/git/repositories/project/shell-asset.git,
	 ! [remote rejected] master -> master (pre-receive hook declined),
	error: failed to push some refs to '/data/git/repositories/project/shell-asset.git',
2019/05/14 12:11:57 models/webhook.go:867:DeliverHooks() [T] DeliverHooks [repo_id: 69],
2019/05/14 12:11:57 ...s/context/context.go:138:HTML() [D] Template: status/500,
2019/05/14 12:11:57 models/pull.go:1298:AddTestPullRequestTask() [T] AddTestPullRequestTask [head_repo_id: 69, head_branch: master]: finding pull requests,
[Macaron] 2019-05-14 12:11:57: Completed POST /Project/Shell-Asset/pulls/83/merge 500 Internal Server Error in 158.425011ms
```

## Description

When I merge a pull request of repository `Project/Shell-Asset`, I got a 500 error. `Project` is a private organization and `shell-asset` is private repository also. I disabled git hook from app.ini but does not work.

**Comment by lafriks** [comment]
Have you changed git repository storage directory? Are you using docker?

**Comment by zongwei007** [comment]
@lafriks Yes. I use gitea with docker.  data volume mounted on host and no changed  recently.

**Comment by ihuro** [comment]
Same issue, but only on protected branches.
I use docker too.

**Comment by lafriks** [comment]
This could be related to this change #6608

**Comment by zongwei007** [comment]
Same as @ihuro , it can do merge successfully if I close the protection of master branch.

**Comment by lunny** [comment]
Which merge style did you use?

**Comment by lafriks** [comment]
Looks like it is caused by #6672 as now hooks are checking branch protection also for PR merges, cc @zeripath

**Comment by zeripath** [comment]
Agh! Sorry about this! 

@lafriks we can detect quite easily whether a push is being performed by gitea internally by checking the `SSH_ORIGINAL_COMMAND` which is set to `gitea-internal` if it's a gitea push etc. So we could remove protected branch checking if that's set - however, maybe we can do better. 

(I think there's actually another issue in #6672 - whereby:

https://github.com/go-gitea/gitea/blob/7dd983797c218d7ae45e67d79517e95ad3dd24b8/models/pull.go#L622-L636

Might be sending double hooks.)

I'll take a look. Sorry once again.

**Comment by zeripath** [comment]
OK, I think what we should do is to set (another) environment variable with the PR number we're merging - that will allow people to have hooks that detect PR merges.

**Comment by lunny** [comment]
This affected only when running gitea on docker

**Comment by lunny** [comment]
```
chdir /data/git/repositories/shell-asset.git: no such file or directory        ,
	To /data/git/repositories/project/shell-asset.git
```
It seems because the `repoUserName` env was blank.

**Comment by lunny** [comment]
@zongwei007 could you confirm that #6971 will fix this issue?

**Comment by zongwei007** [comment]
@lunny merge successfully on 1.9.0+dev-262-g96b412bb8.

**Comment by lunny** [comment]
@zongwei007 OK. I will close this one since it's duplicated.
