### ISSUE TITLE
No rate-limiting with 2FA

### ISSUE THREAD

**Issue by EpicnessTwo** [go-gitea/gitea#6950]
- Gitea version (or commit ref): 1.5.0
- Git version: Not Applicable
- Operating system: Not Applicable
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist: Not Applicable

## Description

When a user has 2FA enabled on their account, it can be easily brute forced as there's no rate-limiting on how many attempts a user can make to guess the 6 digit code.

Whilst this may seem like a slim chance of guessing the right code as there is 1 million combinations, the same issue still stands with the 2FA recovery code which may be harder to crack but they don't change every 30 seconds.

 I have also reported this bug to [Gogs](https://github.com/gogs/gogs/issues/5700) as they also have the same issue. 
...

**Comment by techknowlogick** [comment]
Closing this as the recommended ratelimiting is done via fail2ban, which we have documented here: https://docs.gitea.io/en-us/fail2ban-setup/

Unrelated: 1.5.0 is really out of date and has [security issues](https://cve.mitre.org/cgi-bin/cvekey.cgi?keyword=gitea) with it, you may want to upgrade.
