### ISSUE TITLE
Incorrect drone webhoook settings when using drone OAuth2

### ISSUE THREAD

**Issue by haozileung** [go-gitea/gitea#6955]
- Gitea version (or commit ref):  1.9.0+dev-254-g710245e81
- Git version: 
- Operating system: Mac
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description

When using drone OAuth2 mode with gitea, webhook actived by drone in table `webhook` has missing field `http_method`. Then the webhook stop working.

And, in repo's webhook setting page, I can not change and save this value.
## Screenshots

![image](https://user-images.githubusercontent.com/1173924/57762435-166fb300-7732-11e9-9d9c-5da8c78657a3.png)

**Comment by techknowlogick** [comment]
Closing as duplicate. Issue has been solved with #6951
