### ISSUE TITLE
Docker guidelines text

### ISSUE THREAD

**Issue by jmn** [go-gitea/gitea#696]
Hi,
Using latest Docker image:

There is a link in "Install Steps For First-time Run": "If you're running Gitea inside Docker, please read [Guidelines](https://github.com/go-gitea/gitea/tree/master/docker) carefully before you change anything in this page!" The link is to https://github.com/go-gitea/gitea/tree/master/docker contains configuration files.

Perhaps create a README.MD in the directory containing these outlines?

**Comment by tullo** [comment]
The readme exists in v0.9 https://github.com/go-gitea/gitea/tree/release/v0.9/docker but did not make it to current version for reasons unknown to me.

**Comment by tboerger** [comment]
Where do you get this information? The docker guide should be part of the docs

**Comment by tullo** [comment]
Maybe add a link to the [docs](https://docs.gitea.io/en-us/install-with-docker/) in a minimal readme.
I recently moved my stuff from gogs to gitea and could not remember how i started the gogs docker instance and googled "install gogs docker" where the the first hit gets you to https://github.com/gogits/gogs/tree/master/docker and i guess that the OP made the same assumptions as me and expected to find the info at the same location in the githea repo

**Comment by tboerger** [comment]
Than we should add readme files to every directory. IMHO a docs page is always the first source you should look at, and there you can also directly see it.

**Comment by jmn** [comment]
If Docker guidelines has been written, why not link to them in https://github.com/go-gitea/gitea/blob/74ed6dc3ad830d308a032fe213e9dfe83f954ffc/options/locale/locale_en-US.ini#L55

**Comment by jmn** [comment]
By the way, This is how https://docs.gitea.io/en-us/install-with-docker/ looks at the moment for me: (tested with Chromium, Chrome Canary on Windows 10)
![chrome_2017-01-25_00-27-13](https://cloud.githubusercontent.com/assets/35616/22271579/87887650-e295-11e6-9ece-6f27c80723c2.png)

**Comment by tboerger** [comment]
That's exactly the part I asked for.

**Comment by lunny** [comment]
It's a UI bug. @jmn could you fire an issue on go-gitea/docs ?

**Comment by jmn** [comment]
OK see go-gitea/docs/issues/85

**Comment by lunny** [comment]
Thanks.

**Comment by tboerger** [comment]
@lunny why should he report a theme issue to the docs?

**Comment by lunny** [comment]
@tboerger you mean that's hugo's bug?

**Comment by tboerger** [comment]
@lunny no, a theme bug. I'm pretty sure this is related to an unproperly pinned bootstrap version. As MetalMatze used the bootstrap 4 beta and they switched the grid system

**Comment by jmn** [comment]
It's hard to know which repo to report to for the website. The website shares the theme with Gitea the app?

**Comment by tboerger** [comment]
The repo "theme" is the shared Hugo theme for the website, docs, blog and code redirects.

**Comment by lunny** [comment]
So this issue should be moved to go-gitea/theme?

**Comment by jmn** [comment]
Pardon me for going off topic in the first place, the CSS issue is now at https://github.com/go-gitea/theme/issues/31

This issue is about the reference to documentation in "Install Steps For First-time Run": which is in this code https://github.com/go-gitea/gitea/blob/74ed6dc3ad830d308a032fe213e9dfe83f954ffc/options/locale/locale_en-US.ini#L55

**Comment by lunny** [comment]
I think go-gitea/theme#31 have resolved this. So let's close it. Please feel free to reopen it.

**Comment by tboerger** [comment]
We have to fix the link within Gitea itself.
