### ISSUE TITLE
Collaborators in repositories in private organisations cannot access repository

### ISSUE THREAD

**Issue by zeripath** [go-gitea/gitea#6962]
- Gitea version (or commit ref): 1.9.0+dev-257-g7dd983797
- Git version: N/A
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL - probably also
  - [x] MySQL
  - [ ] MSSQL - probably also
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL) https://try.gitea.io/TestOrgAnother/repository-with-collaborator
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

If I create a repository in a private organization and add a collaborator who is not a member of that organization they cannot access the repository despite it being it appearing on their dashboard.

## Screenshots

![Screenshot from 2019-05-15 20-54-32](https://user-images.githubusercontent.com/1824502/57804898-ae31c900-7753-11e9-8051-241e6e4321ff.png)
![Screenshot from 2019-05-15 20-54-29](https://user-images.githubusercontent.com/1824502/57804900-aeca5f80-7753-11e9-80a2-a419baf163db.png)

**Comment by mrsdizzie** [comment]
This seems to be from @lunny PR https://github.com/go-gitea/gitea/pull/6743

https://github.com/go-gitea/gitea/blob/7dd983797c218d7ae45e67d79517e95ad3dd24b8/models/repo_permission.go#L171-L174

Maybe there needs to be a check here if they are a collaborator (similar as below) and set access perms/not return if so?
