### ISSUE TITLE
Every public key after the first added is a 'duplicate' for MSSQL

### ISSUE THREAD

**Issue by btrepp** [go-gitea/gitea#697]
- Gitea version (or commit ref): d2bb8ef5039
- Git version: 2.9.1
- Operating system: Windows 10
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist: n/a

## Description

Using mssql results in every key after the first key being detected as already existing.
It appears the check for "does this key exists" is actually running "does any key exist"

`models/ssh_key.go line 360` is the line.

This is most likely caused by go-xorm. It appears as if it is ignoring the text condition for mssql.
A workaround is 
```has, err := x.Where("content=?",content).Where("type=?",KeyTypeUser).Get(&PublicKey{})```

...

**Comment by lunny** [comment]
There should be a checksum column for compression and as a query condition but not directly content.

**Comment by lunny** [comment]
@btrepp please confirm #911 has fixed this issue.
