### ISSUE TITLE
Unify issue and wiki editors

### ISSUE THREAD

**Issue by ypnos** [go-gitea/gitea#6975]
This is a feature request.

## Description

Right now there is a unintuitive feature discrepancy between issues and wiki pages:

* Issue comments can have attached files, wiki pages cannot (see #574)
* Wiki pages have a semi-WYSIYWG markdown editor UI, issues have a bare text form (related #5436)

It would be great if both could share one interface that is feature-complete.

**Comment by Cherrg** [comment]
sets sum the tasks up:

**Wiki**
- add Write/Preview Buttons like in issues
- add fileupload
  - backend+routes to allow file uploads to wiki repository 
  - add dropzone like in issues
  - add inplace file insert (paste directly in editor -> is really not much js, if dropzone i working)
- add media listing like _pages to list file tree (complete) and for defined paths
  - add an api for this
- add file select to codemirror to browse files and insert link, uses api above

**Issues**
- add codemirror editor as this is near enough to an wysiwyg editor

I will implement some of this, and link the PRs here

**Comment by 6543** [comment]
this is a dublicate of #5436

and gitea v1.11.0 close this anyway ...

**Comment by 6543** [comment]
@ypnos can you close this issue?

**Comment by ypnos** [comment]
Can wiki pages have attached files in 1.11? I don't see it in the changelog for RC1.

**Comment by 6543** [comment]
no they dont have attachments jet

**Comment by ypnos** [comment]
The aim of this issue is a consistent behavior and feature parity between Issue and Wiki editors.

**Comment by 6543** [comment]
lets leave it open ...

**Comment by wxiaoguang** [comment]
The editor problem has been fixed by latest editor refactoring PR

The wiki attachment problem is duplicate: #574
