### ISSUE TITLE
TestSearchRepos is broken

### ISSUE THREAD

**Issue by zeripath** [go-gitea/gitea#6977]
- Gitea version (or commit ref):1.9.0+dev-262-g96b412bb8

## Description

`TAGS="bindata sqlite sqlite_unlock_notify" make build test-sqlite\#TestSearchRepo` fails

**Comment by zeripath** [comment]
This has been broken since at least v1.7.0-dev and likely earlier.

**Comment by zeripath** [comment]
I've just spent all evening trying to figure this out and have failed. 

The closest I came to actually getting user2/repo1 indexed was after forcibly updating the repo I manage to get to:

https://github.com/sanjid133/gitea/blob/6fb58a8cdcd76aa45902e50da8f2b450fe9d3d35/models/repo_indexer.go#L155

But I never got past this before the search occurred.

Likely there is a timing issue or locking issue her but I don't understand enough to make this work.

@lunny do you have any idea how to solve this? @kolaente is this the issue you're experiencing on golang-ci?

**Comment by zeripath** [comment]
This issue is preventing #6961 from passing ci

**Comment by lunny** [comment]
I know this issue and will also spend some time to investigate it.

**Comment by kolaente** [comment]
@zeripath It could be related, but the tests which are failing in #6418 are `TestBleveSearchIssues`, unit tests, not integration tests.
