### ISSUE TITLE
Improve Assignee selection for issues / pr

### ISSUE THREAD

**Issue by sebastian-sauer** [go-gitea/gitea#6978]
- Gitea version (or commit ref): 1.8
- Git version: n/a
- Operating system: n/a
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

Currently the assignee selection for issues / pull requests is not searchable. When working in a large organisation with large teams it can be annoying to select the assignee of an issue.

I'd propose to make the current list searchable.

Open questions: 
- Is there a reason why this is not searchable?
- Should the milestone list be searchable too?
- Same for Labels?

I already did a first version of the filter for assignees.

Any feedback is much appreciated and if we agree on the open questions i'd be happy to create a PR for this UI enhancement.

Please see a screenshot below of the filterable assignee list (needed code changes are only inside the templates)

## Screenshots

![image](https://user-images.githubusercontent.com/1135157/57966957-287f6a80-7959-11e9-97b9-6eb2d7650be4.png)

**Comment by rlogiacco** [comment]
In my case this would be not usable unless the search facility operate both on username and other fields like email, first name and last name... @lunny is this what you intend as well or do we have a different approach?

**Comment by lunny** [comment]
I think we could search both username and full name. We have a page to do that on organization team settings.

**Comment by noerw** [comment]
this is implemented by now
