### ISSUE TITLE
Error 502 Bad Gateway on Update

### ISSUE THREAD

**Issue by suisseWalter** [go-gitea/gitea#6979]
- Gitea version (or commit ref):1.7.6 and 1.8.x
- Git version: 2.11.0
- nginx version: 1.10.3
- Operating system:Raspbian stretch 9
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ x] Not relevant
- Log gist:

## Description
I am currently trying to upgrade gitea from 1.7.6 to 1.8. But the Problem is that every time I try to do so I can't reach the server afterward and I just recieve a error.
" 502 Bad Gateway
nginx/1.10.3 " 
the Problem exists both with 1.8.0 and 1.8.1. Every upgrade before 1.8 worked flawless, I could just replace the gitea file with the new one and it worked. But now this doesn't work anymore. 
I have run <sudo apt-get update> <sudo apt-get upgrade> several times and everything is updated. Is it possible that there is a dependency that isn't correctly updated on raspbian? 
thanks for any suggestions.

...

## Screenshots
![502 bad gateway](https://user-images.githubusercontent.com/42143099/57967091-169ec700-795b-11e9-970c-1b1e4fd07009.png)

**Comment by lunny** [comment]
502 means your Gitea aren't running.

**Comment by zeripath** [comment]
I see you're on raspbian you need to run the arm6 build as the arm7 build is currently broken

**Comment by suisseWalter** [comment]
@zeripath  many thanks the arm6 build works. So what is the difference beetween the differnet arm builds? also shouldn't the arm7 build be marked somehow as broken?

**Comment by zeripath** [comment]
We're still investigating what the problem is - all we know is that it doesn't work on pi and pi-alikes at present.

PRs to update the documentation are welcome.

**Comment by wumoxi** [comment]
By Gitea deploys the container using the docker container, the container is restarted to access the service 502
