### ISSUE TITLE
编辑的时候不能传图片Editors cannot upload and modify or delete pictures

### ISSUE THREAD

**Issue by shijunti19** [go-gitea/gitea#6981]
- Gitea version (or commit ref):Gitea 当前版本: 1.8.0 刚升级当前版本: 1.8.1 也是
- Git version:最新
- Operating system:谷歌最新稳定
- Database (use `[x]`):sqlite
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:NO
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
编辑的时候不能传t图片，导致我无法描述，下面的拖动上传你们要改下，

我的处理建议，第一张图的时候就你们现在形势，有图了可以使用下面的形式
![image](https://user-images.githubusercontent.com/5392211/57968866-e11dcc00-79a2-11e9-9b95-2c48f06d30fb.png)

## Screenshots
这是回复，你看这图，我不能删除，不能上传，我除了整个删除一点办法都没
![image](https://user-images.githubusercontent.com/5392211/57968848-a3b93e80-79a2-11e9-98b4-6f2bed2d1362.png)

**Comment by saitho** [comment]
Can you translate the content of the issue into English as well? ;)

**Comment by saitho** [comment]
Guessing from the Google translation and some tests I believe his problem is that once you uploaded an image you can't remove it when editing the text. This is reproducable on try.gitea.io.

**Comment by lunny** [comment]
This is a known issue. duplicated with #3618
