### ISSUE TITLE
Default to logging to stdout/stderr under systemd

### ISSUE THREAD

**Issue by silverwind** [go-gitea/gitea#6987]
We get a number of issues like https://github.com/go-gitea/gitea/issues/6972 with no usable error information because apparently gitea does not log anything to the `stdout` and `stderr` when it encounters runtime errors. I'm not sure how these deployments are done, but I assume `log.mode` does not include `console`?

**Comment by lunny** [comment]
log.mode default will record nothing if you ignore that setting I think. @zeripath

**Comment by zeripath** [comment]
We can't detect if we're being run by systemd or not very easily - (I think if our parent is pid 0 that's probably the only way). Further people are very particular about logging so overriding them is not really acceptable.

However what we could do recommend is that the basic logging config is:

```
[Log]
Mode=error_console

[Log.error_console]
Mode=console
Stderr=true
Level=Error
```

That at least gives us

**Comment by silverwind** [comment]
Yes, no need to detect systemd, this is purely about documentation. I think we should adjust our `app.ini.sample` to include logging on stderr.

What is this `error_console` mode? It seems [undocumented](https://github.com/go-gitea/gitea/blob/8de76b6e646e91c41143242dc0a8d3ae05b35023/custom/conf/app.ini.sample#L538).

**Comment by zeripath** [comment]
You can name a logger whatever you like, the mode will default to the name if you don't provide it.

The ability to do this was mentioned here https://github.com/go-gitea/gitea/pull/6095 in the Subloggers section.

**Comment by silverwind** [comment]
I see. Why not just change the default for the `console` logger to include stderr?

````
[log.console]
LEVEL =
STDERR = true
````

**Comment by zeripath** [comment]
It's best to keep stderr for errors only. If you use [log.console] to configure that logger, then if you want to add a console logger for easy debugging then it becomes more difficult.

It doesn't really matter I guess - it's supposed to be configurable.

**Comment by silverwind** [comment]
Ah, so the `console` is bound to only log to `stdout`? In that case, your suggestion makes sense. Should we then define two default loggers, `console` and `error_console` to get both streams properly attached?
