### ISSUE TITLE
http return 500

### ISSUE THREAD

**Issue by inrg** [go-gitea/gitea#6988]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

...
======================================================

I think it's the GBK encoding problem.

2019/05/19 16:35:52 [...ters/repo/setting.go:112 SettingsPost()] [E] UpdateRepository: updateRepository: update: Error 1366: Incorrect string value: '\xE4\xBA' for column 'description' at row 1
2019/05/19 16:35:58 [W] parseRemoteUpdateOutput: unexpected update line " + 645c047...d32af2f refs/pull/3517/merge -> refs/pull/3517/merge  (forced update)"
2019/05/19 16:35:58 [W] parseRemoteUpdateOutput: unexpected update line " + 0c6558f...ad95329 refs/pull/3850/merge -> refs/pull/3850/merge  (forced update)"
2019/05/19 16:35:58 [W] parseRemoteUpdateOutput: unexpected update line " + c71c4bd...a20cb11 refs/pull/4076/merge -> refs/pull/4076/merge  (forced update)"
2019/05/19 16:36:05 [...ters/repo/setting.go:112 SettingsPost()] [E] UpdateRepository: updateRepository: update: Error 1366: Incorrect string value: '\xE6' for column 'description' at row 1
2019/05/19 16:36:23 [...ters/repo/setting.go:112 SettingsPost()] [E] UpdateRepository: updateRepository: update: Error 1366: Incorrect string value: '\xE6' for column 'description' at row 1

**Comment by lunny** [comment]
This should be a problem of your mysql charset setting. #6992 should fix that.
