### ISSUE TITLE
Notifications Questions

### ISSUE THREAD

**Issue by OlivierMary** [go-gitea/gitea#699]
Hi,

I missunderstand when gitea send mail notification, I had activated notification in app.ini and I received mail only when :
- Test mails from admin panel
- Ask for password
- A comment on my PR

I dont received mail when :
- New PR on my team repos
- New Ticket on my team repos
- New assignation on a PR on my team repos

I have something wrong ? Or it's "normal" with gogs/gitea ?

Thanks for your reply.

Informations:
- Gitea version (or commit ref): 1.0.1
- Git version: 2.11.0
- Operating system: Archlinux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:
None

**Comment by bkcsoft** [comment]
Do you watch the repos that you don't recieve emails for? There's a PR for automagically watching things that you have created 🙂

**Comment by OlivierMary** [comment]
Effectively that works better when all member follow, I was testing just with one team member that follow.
I thought all team member receives all notifications for all repo of team! My bad!

**Comment by rems4e** [comment]
Hi,

I can not assume that emails should be sent from the messages above, but I don't receive emails for a ticket created by another person on a repo I watch.

Is this normal ?
