### ISSUE TITLE
display page revisions on wiki

### ISSUE THREAD

**Issue by joubertredrat** [go-gitea/gitea#7]
Hi guys,

Wiki on Gogs is very fine, I liked a lot, but I think that is good idea to be possible see other revisions from page as a page history.

What you think?

Reference: https://github.com/gogits/gogs/issues/2991

**Comment by xinity** [comment]
not sure this should in a github wiki on on the hugo built documentation website.
any thought ?

**Comment by tboerger** [comment]
> not sure this should in a github wiki on on the hugo built documentation website.
> any thought ?

That doesn't have to do anything with that. We already got builtin wiki support within Gogs/Gitea, but you can not see the current revision of this sub git repo anywhere in the UI.

**Comment by strk** [comment]
I'm also missing the feature of seeing page edit history for wiki. @joubertredrat are  you going to provide a patch for that ?

**Comment by joubertredrat** [comment]
@strk for future you can compare your page versions, you need to see your current page revision.

Similar to this as example.

https://www.dokuwiki.org/dokuwiki?do=revisions
https://www.dokuwiki.org/dokuwiki?rev=1451603439
https://www.dokuwiki.org/dokuwiki?rev=1451603439&do=diff
