### ISSUE TITLE
Fix linting error

### ISSUE THREAD

**Issue by tboerger** [go-gitea/gitea#70]
Currently the go linter errors out on various places, we should fix that to increase the code quality.

**Comment by DblK** [comment]
Do you would like to have a huge PR or smaller PR by folder for example?
I saw on lint it misses several comments for each function.

Tell me what you want.

**Comment by xinity** [comment]
@DblK smaller PR are easier to review :)

so i'd vote for smaller ones

**Comment by tboerger** [comment]
:+1: for smaller prs, as @xinity said it's better to review

**Comment by tboerger** [comment]
But continue with the models, I already started parts within the makefile pr

**Comment by lunny** [comment]
Only `modules/bindata/bindata.go` not be fixed. But that file is generated by go-bindata. Any idea? @tboerger

**Comment by tboerger** [comment]
Switch to a proper bindata tool like fileb0x (but it doesn't support tags) or go.rice or somehow ignore it

**Comment by tboerger** [comment]
On the other side, we will drop the bindata from the repo soon, than it's not part of the repo anymore

**Comment by lunny** [comment]
But maybe we can ingore the golint check on Makefile at first. So that we an close this issue and ask all the PR to pass the golint.

**Comment by tboerger** [comment]
Maybe you can filter out the bindata package from the list temporary? Like grep -v

**Comment by strk** [comment]
@lunny if you find out how to ignore a single file, I'm all for going with it, especially as after a "make" invocation you'd have the bindata.go around and it might be annoying to get those false positives

**Comment by tboerger** [comment]
On the short term we can simply ignore the entire `code.gitea.io/gitea/modules/bindata` package.

**Comment by lunny** [comment]
So this could be closed via #303
