### ISSUE TITLE
Feature request:  Change default authentication provider for user registration.

### ISSUE THREAD

**Issue by couling** [go-gitea/gitea#700]
# Feature request:  Change default authentication provider for registration.

At the moment there are two mechanisms for creating an account:

1. An admin creates one manually.
2. If enabled anybody can run through the account registration procedure to create an account with LOCAL authentication.

This means that either users have to wait for a sysadmin to creat an account for them, or that sysadmins have no control over who signs up for an account.  It also means that user driven registration always uses local authentication and never an alternative (eg LDAP).

It would be good if gitea could allow *anyone* with a valid login (eg: a valid LDAP login) to create themselves an account.

------

Possible further extensions to this:

- A user attempting to log in with with a username and password which do not match a gitea user but will authorise with LDAP could be bounced to a pre-authorised account registration page ("Just add full name and email address to complete")

- Gitea could enforce that that gitea usernames and authentication provider (LDAP) usersnames match - at least for registration.

**Comment by tboerger** [comment]
There is already an open issue to provide a bootstrap config that enables ldap or other authentication sources directly from the beginning. Than nobody will be able to register on the wrong place

**Comment by couling** [comment]
Are you referring to  #209?  That's quite a different issue.

**Comment by couling** [comment]
Are you referring to  #209?  That's quite a different issue.  #209 is about automating setup from the point of view of the sysadmin during installation.  This issue is about allowing users to set themselves up on an established and running instance where they already have a single-sign-on user-name and password.

**Comment by bkcsoft** [comment]
LDAP-authentication is already possible when the admin goes through the installation-process so I don't really see the issue here?

**Comment by strk** [comment]
On Thu, Jan 19, 2017 at 10:26:12AM -0800, Philip Couling wrote:

> It would be good if gitea could allow *anyone* with a valid login (eg: a valid LDAP login) to create themselves an account.

This is already supported. Anyone with LDAP gets an account automatically
created upon first login. We disabled the registration and used a custom
template to provide a link to the external LDAP registration page.
Works fine.

**Comment by strk** [comment]
@couling did we respond to your concern ? Can this be closed ? (spring cleanup)
