### ISSUE TITLE
500/RuntimeError while browsing organization repo list

### ISSUE THREAD

**Issue by philippbeckmann** [go-gitea/gitea#7001]
- Gitea version (or commit ref): 1.8.1
- Git version: 2.21.0.windows.1
- Operating system: Windows Server 2019
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [X] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X] No
  - [ ] Not relevant
- Log gist: https://gist.github.com/philippbeckmann/5b9da6b2f45e5c940095a3dd4fa4d0de

## Description

When browsing an organization and switching to another page, an error 500 is displayed. The log reports "runtime error: invalid memory address or nil pointer dereference" (see gist).

**Comment by trgwii** [comment]
I'm having the same issue! Have had it for a while, but until Gitea 1.8.1, the IIS reverse proxy overtook the error page, which led me to believe IIS was doing something funky with that specific response from Gitea (Page 2 or more on any organization page). With 1.8.1 the Gitea 500 page is shown instead.

Another interesting quirk is that you have to be signed in for the error to occur.

My setup:

Gitea: 1.7.6, 1.8.1
Git version: git version 2.18.0.windows.1
Operating system: Windows Server 2012 Standard
Database: MSSQL

**Comment by philippbeckmann** [comment]
I just found out that the problem does not occur to admin users. Only non-admin users are affected??!?

**Comment by trgwii** [comment]
Confirmed, same result here.

Logged out / anonymous: Works
Normal user: 500 error
Admin / root user: Works

funky bug

**Comment by philippbeckmann** [comment]
This corresponds to the code in https://github.com/go-gitea/gitea/blob/release/v1.8/routers/user/home.go#L438

The stacktrace in my gist points to line 448

**Comment by lafriks** [comment]
Problem is actually somewhere here:
https://github.com/go-gitea/gitea/blob/v1.8.1/models/org.go#L728

or

https://github.com/go-gitea/gitea/blob/v1.8.1/routers/user/home.go#L448

**Comment by lafriks** [comment]
Could you check if branch https://github.com/lafriks/gitea/tree/backport/fix_repository_search fixes problem? I was not able to reproduce this problem locally

**Comment by lafriks** [comment]
It could be that on master this problem is already fixed by #6897

**Comment by zeripath** [comment]
I can backport that if liked

**Comment by lafriks** [comment]
I have branch with backported changes already, I was just not able to reproduce issue, so I'm not sure if it actually fixes the problem :)

**Comment by philippbeckmann** [comment]
Thank you, i'm just setting up a test environment to test a master build.

**Comment by philippbeckmann** [comment]
The issue is fixed in the current master. Thank you.

**Comment by philippbeckmann** [comment]
This issue is fixed in the current 1.8 build.
