### ISSUE TITLE
Variable placeholder not interpolated in german translation

### ISSUE THREAD

**Issue by itbane** [go-gitea/gitea#7007]
- Gitea version (or commit ref): 1.8
- Git version: 2.11
- Operating system: Debian 9 (Stretch)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:  #-

## Description

When changing another user account as an admin, the response shows a variable placeholder instead of the username, as seen in attached screenshot. This only seems to affect the german localization - in the english version, the username is not referenced when saving the changed user.

## Screenshots
![gitea-user-change](https://user-images.githubusercontent.com/39377549/58084181-b5752e80-7bba-11e9-8af3-27072342e18e.png)

**Comment by zeripath** [comment]
Please change translations at crowdin:

https://crowdin.com/translate/gitea/all/enus-de

**Comment by itbane** [comment]
In crowdin, this issue has been raised 7 months ago, but the preferred solution has not yet been approved.

**Comment by zeripath** [comment]
OK, let me see if I can change it. The most upvoted version is not the version you provided - which is correct?

**Comment by zeripath** [comment]
OK I don't have permission to do that.

**Comment by zeripath** [comment]
I recommend you drop a message to the managers on crowdin.
