### ISSUE TITLE
Display issue on mobile

### ISSUE THREAD

**Issue by isnanx** [go-gitea/gitea#7009]
- Gitea version (or commit ref): 1.8.1+5-g895764e7f
- Git version: 1.8.3.1
- Operating system: CentOS7 Kernel 3.10.0-957.5.1.el7.x86_64
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
Display not good on mobile inside an issue when more the one comments.

## Screenshots
![20190521202209](https://user-images.githubusercontent.com/49234985/58096343-73260e80-7c07-11e9-8414-441c6b6ab15d.jpg)

**Comment by wxiaoguang** [comment]
Although not perfect, better than before.

![image](https://user-images.githubusercontent.com/2114189/177246027-b02cd19a-9e39-431f-b8e8-f406f5c427d6.png)
