### ISSUE TITLE
Commit payload problem in webhooks

### ISSUE THREAD

**Issue by 0x1793d1** [go-gitea/gitea#7010]
- Gitea version (or commit ref): 1.8.1
- Git version: 2.20
- Operating system: Arch Linux ARM (in Docker)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant

## Description

I am using Drone CI and I noticed that when I commit directly in Gitea, the comitter attribute contains an incorrect email address and an empty username.
This doesn't prevent Drone from working, but there is no information about the user in the Drone builds.

**Comment by 0x1793d1** [comment]
OK, I understood why it didn't work: I had hidden my email address (the system returns the NoReplyAddress in that case) and when Gitea converts a commit to payload, it recovers the username with this email address (GetUserByEmail). Shouldn't we do something else?

**Comment by lunny** [comment]
This will protect user's privacy .
