### ISSUE TITLE
Failed to ailed to initialize issue indexer: leveldb: manifest corrupted (field 'comparer'): missing [file=MANIFEST-000042]

### ISSUE THREAD

**Issue by DerAndereAndi** [go-gitea/gitea#7013]
- Gitea version (or commit ref):1.8.1
- Git version: 2.11.0
- Operating system: Raspian Stretch
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

Gitea 1.8.1 stopped starting up while being without any load somewhen in the middle of the night.

There is no setting in `app.ini` to set anything related to the issue indexer, so it is using the default settings.

The log file shows:

```
2019/05/22 11:27:43 [I] Log Mode: File(Info)
2019/05/22 11:27:43 [I] XORM Log Mode: File(Info)
2019/05/22 11:27:43 [I] Cache Service Enabled
2019/05/22 11:27:43 [I] Session Service Enabled
2019/05/22 11:27:43 [I] Mail Service Enabled
2019/05/22 11:27:43 [I] Beginning ORM engine initialization.
2019/05/22 11:27:43 [I] ORM engine initialization attempt #1/10...
2019/05/22 11:27:44 [I] ORM engine initialization successful!
2019/05/22 11:27:44 [I] Git Version: 2.11.0
2019/05/22 11:27:44 [...itea/routers/init.go:95 GlobalInit()] [E] Failed to initialize issue indexer: leveldb: manifest corrupted (field 'comparer'): missing [file=MANIFEST-000042]
```

Please let me know if there is anything else I can provide.

Thanks for any help,
Andreas

**Comment by zeripath** [comment]
AFAIU You should just be able to delete the indexer files and they should repopulate.

**Comment by TheRealKerni** [comment]
Ah perfect. That worked!

Thank you.

**Comment by IanRCarter** [comment]
Sorry to revive a closed issue but I have come across the same problem this morning.

How do you 'delete the indexer files'?

**Comment by seichter** [comment]
Maybe somebody stopping by: had exactly the same issue and deleting `/var/lib/gitea/indexers/*` didn't work. There is another folder `/var/lib/gitea/data/indexers/*`. Emptying this one got me running again.

**Comment by S2-** [comment]
I had the same issue too, and in my case the `indexers` folder was in `<giteatPath>/gitea/data/indexers/`.
