### ISSUE TITLE
Crash when collaborator pushes/pulls to a private repo

### ISSUE THREAD

**Issue by tcpluess** [go-gitea/gitea#7018]
- Gitea version (or commit ref): Gitea version 1.8.1 built with go1.12.5 : bindata, sqlite, sqlite_unlock_notify
- Git version: git version 2.20.1
- Operating system: Debian GNU/Linux 9  Linux git 4.15.18-9-pve #1 SMP PVE 4.15.18-30 (Thu, 15 Nov 2018 13:32:46 +0100) x86_64 GNU/Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:
https://gist.github.com/tcpluess/4b4f899e4bfb2dff23323a21e1ca54ee

## Description
My colleague has created a private repository as follows:

![Screenshot_2019-05-22_17-18-37](https://user-images.githubusercontent.com/16662475/58186748-cbb3e500-7cb5-11e9-80eb-3781c28bd742.png)

And I am added as collaborator to that repo:

![Screenshot_2019-05-22_17-20-14](https://user-images.githubusercontent.com/16662475/58186825-ef772b00-7cb5-11e9-9c19-dbe9eb52fba0.png)

It worked fine to clone the repo and push to it, as one can see:

![Screenshot_2019-05-22_17-21-25](https://user-images.githubusercontent.com/16662475/58187005-3a913e00-7cb6-11e9-8e60-29d41c1b7b2d.png)

However, since he made the last commit, gitea silently crashes when I try to push again some changes or pull from the repo. I set the log level to Debug, but this doesn't give much more info.

I checked the `journalctl` as well (see gist) and also `dmesg` (see gist as well).

**Comment by zeripath** [comment]
Looks like it ran out of memory.

**Comment by zeripath** [comment]
Hmm so it looks like you're pushing over http. Can you check http log and the hook logs.

It might be worth checking if pushing over SSH works.

**Comment by zeripath** [comment]
I don't suppose you can reproduce on try?

**Comment by mrsdizzie** [comment]
how big is the repo you are trying to push/pull?

**Comment by lunny** [comment]
Have you enabled code search?

**Comment by tcpluess** [comment]
I perhaps found the problem. My Gitea instance was running in a LXC container with Debian 9. It seems like there is a compatibility issue with `systemd` running inside a container. [Here are some explanations why](https://stackoverflow.com/questions/51979553/is-it-recommended-to-run-systemd-inside-docker-container), even though this is for Docker, it seems also to apply for LXC.
I created a new container using Alpine Linux, and with that, Gitea works just fine on the very same repo.

So I close the issue for now as it seems it has nothing to do with Gitea.
