### ISSUE TITLE
PR display -1

### ISSUE THREAD

**Issue by mojie126** [go-gitea/gitea#7021]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
PR allows the page to be refreshed again if 500 errors occur during merging, and the PR tag will display - 1, which can't be eliminated.
...

**Comment by lunny** [comment]
duplicated with #7428 and fixed by #7518
