### ISSUE TITLE
Search in private organisations

### ISSUE THREAD

**Issue by pvdbergen** [go-gitea/gitea#7029]
- Gitea version (or commit ref): 1.8.0
- Git version: 2.17.1
- Operating system: ubuntu 18.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X] No
  - [ ] Not relevant
- Log gist:

## Description

Private organisation with private or public repos
search from
https://gitea.mysite.org/orgname  **not my real name - it's behinds a firewall anyway.
when logged in as a user who is a member of the Owners group...
fails to return any results

confirmation - on our test instance, 
organisation == public. search functions as expected

![Screenshot from 2019-05-24 17-36-03](https://user-images.githubusercontent.com/48226368/58310636-73621c00-7e4a-11e9-9887-d604e26843ce.png)

organisation == private, search stops functioning as expected - see screen shots

![Screenshot from 2019-05-24 17-34-54](https://user-images.githubusercontent.com/48226368/58310587-4b72b880-7e4a-11e9-872f-13acb60b3dd7.png)

organisation == limited behaves the same as public.

search from site admin portal works as expected.
https://gitea.mysite.org/admin/repos?q=test

however search and display of repos on the dashboard also limits the displayed repos when an organisation is private:
https://gitea.mysite.org/

org == private:

![Screenshot from 2019-05-24 17-48-49](https://user-images.githubusercontent.com/48226368/58311411-3bf46f00-7e4c-11e9-8c28-e9489251cfc5.png)

(note the two visible repos - one is owned but the logged in user who is admin, the other is public - and returns 500 error when clicked - not sure why - probably because that user is a member of the owners group - see next section)

org == public:

![Screenshot from 2019-05-24 17-48-16](https://user-images.githubusercontent.com/48226368/58311365-254e1800-7e4c-11e9-8644-9179daea0b04.png)

Next complication - this only appears to impact logged in users who are members of the Owner group.

logged in users who are team members of a team for the org are able to search as expected.

...

**Comment by lafriks** [comment]
I think this could be already fixed in 1.8.1

**Comment by zeripath** [comment]
Yeah it sounds a lot like the dual bug @mrsdizzie, myself and you fixed.

**Comment by lafriks** [comment]
Please reopen if problem persists in latest version

**Comment by pvdbergen** [comment]
Not fixed in 1.8.1 - issue still exists - how do I reopen it?

**Comment by zeripath** [comment]
Yes these fixes are on the release/v1.8 branch and the master branch. Try either of those.

**Comment by lafriks** [comment]
Please try with https://dl.gitea.io/gitea/1.8/ binary to check if it works. If not feel free to reopen
