### ISSUE TITLE
Suggestion - Use Riot/Matrix instead of Discord (or to use them both, but to feature Riot/matrix only?)

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#7030]
Riot/Matrix is Libre and Decentralized, shouldn't we promote it instead of promoting Discord?
I'm referring to the "Discord Chat" text link from https://gitea.io/

To get an idea of how Riot/Matrix looks like, you can visit this Librem 5 chat room https://riot.im/app/#/room/#community-librem-5:talk.puri.sm. You'll have to sign up, and for that you **don't** have to give your email.

**Comment by lafriks** [comment]
There are problem that we need private channels for specific user groups that imho riot/matrix does not support

**Comment by techknowlogick** [comment]
Thank you for your suggestion @Zig-03. We previously used matrix & IRC, but sadly it didn't work for us for several reasons, we may revisit this in the future, or like @lafriks said maybe look at mattermost.
