### ISSUE TITLE
Replying to comment to PR in split view fails

### ISSUE THREAD

**Issue by ptman** [go-gitea/gitea#7031]
But it works in unified view

- Gitea version (or commit ref): 1.8.1
- Git version: docker
- Operating system: docker
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes https://try.gitea.io/basti/gitea/pulls/1/files
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

I want to reply to comments in PRs, it only works in unified view, does nothing in split view

**Comment by lafriks** [comment]
I think there was issue already for this

**Comment by ptman** [comment]
Oh, I'm sorry to open a new one. Could you point me to the existing issue?

**Comment by rfwatson** [comment]
https://github.com/go-gitea/gitea/issues/4745

**Comment by lunny** [comment]
duplicated with #4745
