### ISSUE TITLE
U2F login not working behind reverse proxy

### ISSUE THREAD

**Issue by svengo** [go-gitea/gitea#7033]
- Gitea version (or commit ref): 1.8.1
- Operating system: docker@ubuntu 18.04
- Database (use `[x]`):
  - [x] MySQL
  - [ ] PostgreSQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
I am using gitea behind traefik as reverse proxy. I managed to add my YubiKey U2F device but cannot login. 

The connection *is* encrypted with https. This may happen because the secure connection is terminated in traeffik and gitea only "sees" an unencrypted connection from traeffik.

## Screenshots
The screenshot appears after I entered my credentials:

<img width="886" alt="Anmerkung 2019-05-24 201914" src="https://user-images.githubusercontent.com/2502366/58348993-64876380-7e62-11e9-8193-19617706e17a.png">

**Comment by OrfeasZ** [comment]
This is a duplicate issue (#6748) and will be fixed in 1.8.2 (which is not released yet).
