### ISSUE TITLE
Automatically merge PR when CI reports success

### ISSUE THREAD

**Issue by OrfeasZ** [go-gitea/gitea#7035]
It would be nice if Gitea would provide an option to automatically merge a PR when the associated CI reports a successful build, similar to GitLab's [merge when pipeline succeeds](https://docs.gitlab.com/ce/user/project/merge_requests/merge_when_pipeline_succeeds.html) feature. It is fairly common to wait for a build of a PR to succeed before manually merging it, so a feature like this would be very helpful, especially in cases where there's long running builds / tests. It would also very nicely complement #3588.

**Comment by noerw** [comment]
will be fixed by 9307

**Comment by jolheiser** [comment]
Closing; associated PR is merged. 🙂
