### ISSUE TITLE
Feature request: Cancel close issue

### ISSUE THREAD

**Issue by diogogithub** [go-gitea/gitea#7053]
**What can be improved:** Sometimes we click on "Close issue" accidentally

**Possible Solutions:**
- After closing there could be a countdown of say 10s allowing us to cancel such action;
- If the issue is reopened by the same person in less than a minute just remove both the close and the open from the issue's history.

**Comment by zeripath** [comment]
We could just do a modal?

**Comment by diogogithub** [comment]
Not sure if it is as good as the proposed solution as far as UX goes, but it is definitely a viable solution that I should have listed in my first comment.

**Comment by wxiaoguang** [comment]
I think the current behavior is good enough, the closed issue could be reopened.
