### ISSUE TITLE
Confirmation popup disappears

### ISSUE THREAD

**Issue by Xumeiquer** [go-gitea/gitea#7067]
- Gitea version (or commit ref): 03e4db4
- Git version: git version 2.20.1
- Operating system: Debian (gitea is running in Docker)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes
  - [ ] No
  - [ ] Not relevant
- Log gist:
There are no logs

## Description
It is a kind of wierd thing, it just happen when a confirmation pop up shows up that inmediatlly the popup shutdown. If I refresh the page it happens again. If I login with another browser and I perform the acction, the popup stays. On the other hand, if I do the browsers trick in the other way around it accurs exactlly the same, in the first browser the popup does not work and the second browser it works. I tryed with Chrome, Firefox, Safari, all the same, even with different combinations as first and second browser.

## Screenshots
![popup-error](https://user-images.githubusercontent.com/2176256/58488022-f0ea9c80-8168-11e9-9201-56c628c35ff8.gif)

**Comment by lunny** [comment]
Which repository on try.gitea.io, could you reproduce that?

**Comment by Xumeiquer** [comment]
Any repository, any kind of popup. 

For example this one: https://try.gitea.io/hezob/foo when trying to delete the repository.

**Comment by lunny** [comment]
No, I can't reproduce that on https://try.gitea.io

**Comment by Xumeiquer** [comment]
I have found the issue. It is uBlock Origin who is removing the popup so disabling it do the job.

I debugged a little bit the code until get it.

I case some one want to debug dipper this is the function which removes the popup.

```javascript
vAPI.SafeAnimationFrame.prototype = {
    start: function(delay) {
        if ( delay === undefined ) {
            if ( this.fid === undefined ) {
                this.fid = requestAnimationFrame(( ) => { this.onRAF(); } );
            }
            if ( this.tid === undefined ) {
                this.tid = vAPI.setTimeout(( ) => { this.onSTO(); }, 20000);
            }
            return;
        }
        if ( this.fid === undefined && this.tid === undefined ) {
            this.tid = vAPI.setTimeout(( ) => { this.macroToMicro(); }, delay);
        }
    },
```

Thanks.
