### ISSUE TITLE
is it possible upgrade from 1.1.4 to 1.8.1 ?

### ISSUE THREAD

**Issue by changchichung** [go-gitea/gitea#7070]
- Gitea version (or commit ref): 1.1.4
- Git version: 2.7.4
- Operating system: ubuntu 16.04
- Database (use `[x]`):
  - [X] MySQL

- Can you reproduce the bug at https://try.gitea.io:
  - [X] Not relevant

## Description

I have a running gitea instance which version is 1.1.4 , and I want to upgrade to 1.8.1 with no impact to the repository and user profiles.
so I download gitea-1.8.1 , stop gitea-1.1.4 , and start gitea-1.8.1 in the same working folder and configuration file , but gitea-1.8.1 won`t start .
```
2019-05-29 12:00:07 [git@hqs200 ~]$ ./gitea-1.8.1 web -p 3000
2019/05/29 12:03:08 [T] AppPath: /home/git/gitea-1.8.1
2019/05/29 12:03:08 [T] AppWorkPath: /home/git
2019/05/29 12:03:08 [T] Custom path: /home/git/custom
2019/05/29 12:03:08 [T] Log path: /home/git/log
^C
2019-05-29 12:03:11 [git@hqs200 ~]$ ./gitea-1.1.4 web -p 3000
2019/05/29 12:03:15 [T] Custom path: /home/git/custom
2019/05/29 12:03:15 [T] Log path: /home/git/log

2019/05/29 12:03:20 Serving [::]:3000 with pid 2129

```

is it possible to upgrade from 1.1 to 1.8 ? or I should use dump and restore(which still not implement in gitea ? ) 
...
and here is logfile
```
2019/05/29 12:05:15 [I] ORM engine initialization attempt #1/10...
2019/05/29 12:05:15 [I] Migration: move team units to team_unit table
2019/05/29 12:05:15 [I] Backing off for 3 seconds
2019/05/29 12:05:18 [I] ORM engine initialization attempt #2/10...
2019/05/29 12:05:18 [I] Migration: move team units to team_unit table
2019/05/29 12:05:18 [I] Backing off for 3 seconds
2019/05/29 12:05:21 [I] ORM engine initialization attempt #3/10...
2019/05/29 12:05:21 [I] Migration: move team units to team_unit table
2019/05/29 12:05:22 [I] Backing off for 3 seconds
2019/05/29 12:05:25 [I] ORM engine initialization attempt #4/10...
2019/05/29 12:05:25 [I] Migration: move team units to team_unit table
2019/05/29 12:05:25 [I] Backing off for 3 seconds
2019/05/29 12:05:28 [I] ORM engine initialization attempt #5/10...
2019/05/29 12:05:28 [I] Migration: move team units to team_unit table
2019/05/29 12:05:28 [I] Backing off for 3 seconds
2019/05/29 12:05:31 [I] ORM engine initialization attempt #6/10...
2019/05/29 12:05:31 [I] Migration: move team units to team_unit table
2019/05/29 12:05:31 [I] Backing off for 3 seconds
2019/05/29 12:05:34 [I] ORM engine initialization attempt #7/10...
2019/05/29 12:05:34 [I] Migration: move team units to team_unit table
2019/05/29 12:05:34 [I] Backing off for 3 seconds
2019/05/29 12:05:37 [I] ORM engine initialization attempt #8/10...
2019/05/29 12:05:37 [I] Migration: move team units to team_unit table
2019/05/29 12:05:37 [I] Backing off for 3 seconds
2019/05/29 12:05:40 [I] ORM engine initialization attempt #9/10...
2019/05/29 12:05:40 [I] Migration: move team units to team_unit table
2019/05/29 12:05:40 [I] Backing off for 3 seconds
2019/05/29 12:05:43 [I] ORM engine initialization attempt #10/10...
2019/05/29 12:05:43 [I] Migration: move team units to team_unit table
2019/05/29 12:05:43 [...itea/routers/init.go:82 GlobalInit()] [E] ORM engine initialization failed: migrate: do migrate: Insert team units: Error 1062: Duplicate entry '1-1' for key 'UQE_team_unit_s'
2019-05-29 12:06:24 [git@hqs200 ~]$ 
```
looks loke db migrate failed ?

**Comment by lafriks** [comment]
it is recommended to upgrade first to 1.2 then 1.3 etc

**Comment by zeripath** [comment]
Please tell me you made back ups of your database though?

If you didn't. Gitea is telling you where the problem is:

```
Migration: move team units to team_unit table
```

Ok so look at migrations.go:

https://github.com/go-gitea/gitea/blob/0081cd8dfe34bcd9182ccebb406000c17dcb8025/models/migrations/migrations.go#L194-L195

This is v69.go:

https://github.com/go-gitea/gitea/blob/57b2ce03d5081bdf7996879be2da300e8f4c6f58/models/migrations/v69.go#L13-L88

Your error is:

```
Insert team units: Error 1062: Duplicate entry '1-1' for key 'UQE_team_unit_s'
```

Which presumably is happening on line 69 and means that there is duplicate row in team_units.

Now to fix you're going to have to adjust the database by hand.

I think drop the team_unit table should be ok assuming that team still has its team_units column. Then before you run the migration again check that there aren't duplicate values in your team's team_units columns.

I would guess that there's a team in there that has a duplicated unit number in it.

**Comment by changchichung** [comment]
> Please tell me you made back ups of your database though?

yes , I clone a vm from orginal vm


> ```
> Insert team units: Error 1062: Duplicate entry '1-1' for key 'UQE_team_unit_s'
> ```

> Which presumably is happening on line 69 and means that there is duplicate row in team_units.
> Now to fix you're going to have to adjust the database by hand.

but I dont konw if there are more error like this.

> I think drop the team_unit table should be ok assuming that team still has its team_units column. Then before you run the migration again check that there aren't duplicate values in your team's team_units columns.

just drop the team_units table ? or maybe alter the vaule like +1000 or whatever ?

**Comment by changchichung** [comment]
> it is recommended to upgrade first to 1.2 then 1.3 etc

ok , maybe I will try this.
but every upgrade , I need to fll out the install form everytime ?
or I can just put the binary in the same folder and just execute by version number ?

**Comment by zeripath** [comment]
Just replace the binary don't do the install.

**Comment by changchichung** [comment]
I try the binary one by one , and from  1.4.0 to 1.5.0 the error happened .
so what should I do now ? try the minor version each one now ?

**Comment by changchichung** [comment]
from 1.4.3 to 1.5.0 m the error happened , if I dont change the data in DB , is there any other way to upgrade ? or is anything special between 1.4.3 and 1.5.0 ?

**Comment by lafriks** [comment]
Use latest version for each major version (1.4.3 -> 1.5.3 -> 1.6.4 -> 1.7.6 -> 1.8.1)

**Comment by changchichung** [comment]
@lafriks I already try to upgrade from 1.4.3 to 1.5.0 but still the same problem. Should I try 1.5.3?

**Comment by lafriks** [comment]
Yes you can skip all minor versions in between, just upgrade from 1.4.3 to 1.5.3 directly and then you can directly upgrade to 1.6.4

**Comment by changchichung** [comment]
still the same error.
I already run an instance version 1.4.3 , so I kill it and run version 1.5.3 , then the error happened again
```
2019-05-29 21:09:16 [git@hqs200 ~]$ ps -aux |grep git

git       2970  0.0  5.5 301764 56516 pts/0    Sl+  18:26   0:01 ./gitea-1.4.3 web -p 3000
git       3160  0.0  0.0  14540   936 pts/2    R+   21:09   0:00 grep --color=auto git
2019-05-29 21:09:22 [git@hqs200 ~]$ kill -9 2970
2019-05-29 21:09:28 [git@hqs200 ~]$ ps -aux |grep git
git       3170  0.0  0.0  14540   932 pts/2    S+   21:09   0:00 grep --color=auto git
2019-05-29 21:09:31 [git@hqs200 ~]$ ./gitea-1.5.3 web -p 3000
2019/05/29 21:09:43 [T] AppPath: /home/git/gitea-1.5.3
2019/05/29 21:09:43 [T] AppWorkPath: /home/git
2019/05/29 21:09:43 [T] Custom path: /home/git/custom
2019/05/29 21:09:43 [T] Log path: /home/git/log
2019/05/29 21:09:43 [I] Gitea v1.5.3 built with: bindata, sqlite
2019-05-29 21:09:45 [git@hqs200 ~]$ tail -30 log/gitea.log
2019/05/29 18:26:52 [I] Run Mode: Production
2019/05/29 18:26:52 [I] Listen: http://0.0.0.0:3000
2019/05/29 21:09:43 [I] Log Mode: File(Info)
2019/05/29 21:09:43 [I] XORM Log Mode: File(Info)
2019/05/29 21:09:43 [I] Cache Service Enabled
2019/05/29 21:09:43 [I] Session Service Enabled
2019/05/29 21:09:43 [I] Mail Service Enabled
2019/05/29 21:09:43 [I] Register Mail Service Enabled
2019/05/29 21:09:43 [I] Notify Mail Service Enabled
2019/05/29 21:09:43 [I] Migration: add label descriptions
2019/05/29 21:09:43 [I] Migration: add merge whitelist for protected branches
2019/05/29 21:09:43 [I] Migration: add is_fsck_enabled column for repos
2019/05/29 21:09:44 [I] Migration: add size column for attachments
2019/05/29 21:09:44 [I] Migration: add last used passcode column for TOTP
2019/05/29 21:09:44 [I] Migration: add language column for user setting
2019/05/29 21:09:45 [I] Migration: add multiple assignees
2019/05/29 21:09:45 [I] Migration: add u2f
2019/05/29 21:09:45 [I] Migration: add login source id column for public_key table
2019/05/29 21:09:45 [I] Migration: remove stale watches
2019/05/29 21:09:45 [I] Migration: Reformat and remove incorrect topics
2019/05/29 21:09:45 [I] This migration could take up to minutes, please be patient.
2019/05/29 21:09:45 [I] Validating existed topics...
2019/05/29 21:09:45 [I] Deleting incorrect topics...
2019/05/29 21:09:45 [I] Deleting 'repo_topic' rows for topics with ids = []
2019/05/29 21:09:45 [I] Deleting topics with id = []
2019/05/29 21:09:45 [I] Checking the number of topics in the repositories...
2019/05/29 21:09:45 [I] Deleting superfluous topics for repositories (more than 25 topics)...
2019/05/29 21:09:45 [I] Updating repositories 'topics' fields...
2019/05/29 21:09:45 [I] Migration: move team units to team_unit table
2019/05/29 21:09:45 [...itea/routers/init.go:60 GlobalInit()] [E] Failed to initialize ORM engine: migrate: do migrate: Insert team units: Error 1062: Duplicate entry '1-1' for key 'UQE_team_unit_s'
2019-05-29 21:10:01 [git@hqs200 ~]$ 
```

**Comment by changchichung** [comment]
> Now to fix you're going to have to adjust the database by hand.
> 
> I think drop the team_unit table should be ok assuming that team still has its team_units column. Then before you run the migration again check that there aren't duplicate values in your team's team_units columns.
> 
> I would guess that there's a team in there that has a duplicated unit number in it.

thanks , drop table team_unit and version 1.8.1 runs !
