### ISSUE TITLE
500/Runtime Error when getting tags via API

### ISSUE THREAD

**Issue by philippbeckmann** [go-gitea/gitea#7073]
- Gitea version (or commit ref): 1.8.1+6-g608f46e59
- Git version: git version 2.21.0.windows.1
- Operating system: Windows Server 2019
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist: https://gist.github.com/philippbeckmann/ac66da04209ab9c6dc26c0c173ab6fe8

## Description

When calling `/repos/{owner}/{repo}/tags` via Swagger, the error `runtime error: invalid memory address or nil pointer dereference` occurs.

The tested repos were migrated from another git server.

Edit2: The error can be reproduced on try.gitea.io: `curl -X GET "https://try.gitea.io/api/v1/repos/7073/gitea/tags" -H  "accept: application/json" -H  "authorization: Basic NzA3Mzp0ZXN0NzA3Mw=="`

**Comment by guillep2k** [comment]
I can't reproduce it now. Has it been addressed?

**Comment by techknowlogick** [comment]
Also am unable to reproduce. Will close, but @philippbeckmann please re-open if still an issue.

**Comment by philippbeckmann** [comment]
Hello, sorry for my late response. The issue can no longer be reproduced in version 1.9.0
