### ISSUE TITLE
[docs.gitea.io] Feature request: add anchors to sections

### ISSUE THREAD

**Issue by slonopotamus** [go-gitea/gitea#7083]
Currently, sections on https://docs.gitea.io/en-us/ do not have `<a name="...">`, so it is impossible to link to particular documentation section.

Hugo docs [have anchors](https://gohugo.io/templates/introduction/#access-a-predefined-variable), though I failed to find how this can be enabled in Hugo.

**Comment by techknowlogick** [comment]
It is currently possible to link to specific sections, ex https://docs.gitea.io/en-us/config-cheat-sheet/#ui-ui. However there is still no easy way to discover the specific anchor for each heading (to find the link I just pasted I had to view source).

**Comment by slonopotamus** [comment]
Oh. I didn't know headers with `id="..."` can also be linked with anchor. Okay, then you're right, the only missing piece is human-friendly way of discovering a link.

**Comment by jolheiser** [comment]
I was thinking of using a combination of Hugo shortcodes and the `anchorize` method.

[anchorize docs](https://gohugo.io/functions/anchorize/)  
[shortcodes docs](https://gohugo.io/content-management/shortcodes/)

**Comment by jolheiser** [comment]
Okay, I got back to this. There is a PR over on gitea.com  
https://gitea.com/gitea/theme/pulls/78

**Comment by lunny** [comment]
Closing this since https://gitea.com/gitea/theme/pulls/78 merged.
