### ISSUE TITLE
Repos avatar is UNKNOWN

### ISSUE THREAD

**Issue by Juexe** [go-gitea/gitea#7090]
- Gitea version (or commit ref):1.9.0+dev-309-g592924a34
- Git version:2.16.2 windows
- Operating system:windows server
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

The repository-avatar is invalid in page:

https://try.gitea.io/explore/repos
and
https://try.gitea.io/00000

## Screenshots
![image](https://user-images.githubusercontent.com/26461438/58680271-a734c880-8399-11e9-9dd1-15d695459a46.png)

![image](https://user-images.githubusercontent.com/26461438/58680299-ca5f7800-8399-11e9-9ea1-1704d3a28a9d.png)

![image](https://user-images.githubusercontent.com/26461438/58680360-11e60400-839a-11e9-965a-27ecf143b1e0.png)

**Comment by lunny** [comment]
will be fixed by #7087
