### ISSUE TITLE
Failed to initialize ORM engine: Error 1045: Unknown

### ISSUE THREAD

**Issue by kaoticfire** [go-gitea/gitea#7091]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X ] Not relevant
- Log gist:
...itea/routers/init.go:61 GlobalInit()] [E] Failed to initialize ORM engine: Error 1045: Unknown error 1045
## Description
Issue is causing service to not start and site connect is refused.
...

**Comment by zeripath** [comment]
Mysql Error 1045 is an access denied error - I suggest you check your database configuration
