### ISSUE TITLE
Auto-collapse or hide certain file on diff/PR

### ISSUE THREAD

**Issue by DblK** [go-gitea/gitea#7092]
On some project/language, there are files (for example VisualStudio Project file, etc.) that you must commit to have a working repository.
However, those file are managed by the IDE your are using and none of the changes are made by hand.

I would like to either auto-collapse the file to not spend time on review for file I won't watch or being able to specify (either inside the repository in `.gitea.yml`) or in settings inside gitea to list the files I want to ignore in those process (PR, Diff, etc...)

**Comment by lunny** [comment]
Right, this is a good idea. We could define some situations here. 
- [ ] according extensions
- [ ] specify sub folders
- [ ] specify filenames
- [ ] non-image binaries

**Comment by 6543** [comment]
I would NOT hide them because of securety conzerns - but then https://github.com/go-gitea/gitea/issues/8579 has to be there first

**Comment by DblK** [comment]
When I said "hide" I had in mind collapse like the ticket @6543 was mentioning.
When #8579 will be done, this feature can be easily implemented by auto-collapse some files.

**Comment by lunny** [comment]
I think we can put a file named `.gitea/pr_collapse` which have a format similiar with `.gitignore` to do that.

**Comment by guillep2k** [comment]
> 
> 
> I think we can put a file named `.gitea/pr_collapse` which have a format similiar with `.gitignore` to do that.

I've always wanted `/vendor` files to auto-collapse. 👍

**Comment by mpuromaki** [comment]
![diff](https://user-images.githubusercontent.com/23620092/71726255-2eba4c80-2e3f-11ea-89d1-6bf4d7a58864.PNG)

I would like to auto-collapse/hide/push-down diffs that have specific type of change (regexp?).

My use case is IDE generated changes to hundreds of files in each commit. These changes has to be included in the commits since they're checksums etc.

**Comment by zeripath** [comment]
yup I think this is fixed by #16773. Please reopen if that PR does not completely fulfil this request.
