### ISSUE TITLE
Treat an unrelated file as a branch in macOS

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#7094]
- Gitea version (or commit ref): fb4438a
- Git version: 2.20.1
- Operating system: macOS
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist: N/A
## Description

Getting 500 error when viewing branches page.
I'm not sure if this issue is caused by Gitea or go-git

## Screenshots

![](https://user-images.githubusercontent.com/2960293/58709439-260b1f00-83f5-11e9-8915-02dea4c5be0e.png)

**Comment by zeripath** [comment]
Somehow you've managed to add a `.DS_Store` file to the `~/gitea-repositories/owner/repo.git/refs/heads/` that'd break any git system.

You should delete it.

**Comment by yasuokav** [comment]
> Somehow you've managed to add a `.DS_Store` file to the `~/gitea-repositories/owner/repo.git/refs/heads/` this would break most git systems.
> 
> You should delete it.

This file is automatically created by macOS's Finder.
But this problem should not have happened before changing to go-git.

**Comment by lunny** [comment]
Maybe send an issue to upstream?
