### ISSUE TITLE
Make check boxes clickable in issues

### ISSUE THREAD

**Issue by troygeiger** [go-gitea/gitea#7097]
- Gitea version (or commit ref):1.8.2
- Git version:
- Operating system:All
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:

## Description
Would it be possible to have the check boxes clickable in issues where the user is assigned or has permission to edit; like the functionality in GitHub? 
...

**Comment by cuzzea** [comment]
Any update on this? Would love to see it on.

**Comment by lunny** [comment]
Noboy are working on this.

**Comment by lordyavin** [comment]
It is a pain the ass to edit a comment to check thing from a todo list. Please schedule this issue for the next milestones.

**Comment by zeripath** [comment]
This is actually the kind of issue that a small bounty might be able to spur development on.

**Comment by davidak** [comment]
It's even worse. You _can_ check boxes **after** you edited the comment, but it's lost when you reload the page. I would consider that a bug.

https://peertube.social/videos/watch/4be6219e-059d-4650-92cf-f0411f343b47

**Comment by zeripath** [comment]
PRs are welcome.

**Comment by viceice** [comment]
I've written a small greasemonkey / tampermonkey script to make gitea checkboxes clickable, see https://github.com/viceice/UserScripts/blob/master/gitea.cb.helper.js 🙃

**Comment by j2L4e** [comment]
There's a PR in the making.

A proper implementation needs a prop on the checkbox that states its position in the raw text. This needs to be done on the go side of things. As I haven't written a single line of go in my life and am, frankly, unwilling to dig into it right now, I'd highly appreciate if someone could do it for me so I can take care of the remaining JS stuff.

https://github.com/go-gitea/gitea/pull/14258#discussion_r552540733

**Comment by viceice** [comment]
@j2L4e I saw the pr after i finished my script 😅

**Comment by silverwind** [comment]
Github also allows to re-order task list items through a small drag handle on the left. I think this is also something we could implement via the `sortablejs` dependency that is already present.

**Comment by kdumontnu** [comment]
Bounty added! [![Bountysource](https://api.bountysource.com/badge/issue?issue_id=74933799)](https://www.bountysource.com/issues/74933799-make-check-boxes-clickable-in-issues)

If you'd like to promote this, please add
```
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=74933799)](https://www.bountysource.com/issues/74933799-make-check-boxes-clickable-in-issues)
```
To the Issue summary
