### ISSUE TITLE
Inconsistency in navbar create dropdown

### ISSUE THREAD

**Issue by Louis9902** [go-gitea/gitea#7098]
- Gitea version (or commit ref): 1.9.0+dev-307-g43cf2f3b5
- Git version: (not relevant)
- Operating system: (docker on windows host, not relevant)
- Database (use `[x]`):
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
Found some inconsistency regarding the user interface. In the navbar menu where you can create some repos etc. the hover highlight colour does not fit the list properly.
As you can see in the screenshot.

If found also out that this changes if you disable the element property underlined in the second screenshot. Then the result is as expected.
...

## Screenshots
![image](https://user-images.githubusercontent.com/16615577/58747580-5e4e4400-846d-11e9-8d0e-98c5e7addbc1.png)
![image](https://user-images.githubusercontent.com/16615577/58747621-fba97800-846d-11e9-97a6-748a233b9f5a.png)

**Comment by silverwind** [comment]
I also noticed this. I have no idea where this faulty inline style is coming from. I assume it is being added by JS, but my search so far did not yield any results.

**Comment by saitho** [comment]
> I assume it is being added by JS, but my search so far did not yield any results.

My guess is that the JavaScript of SemanticUI does that.
