### ISSUE TITLE
Missing asset placeholder on project list when project avatar is not specified

### ISSUE THREAD

**Issue by bkraul** [go-gitea/gitea#7099]
- Gitea version (or commit ref): 3fd1883
- Git version: 1.9.0+dev-312-g8a343dda3
- Operating system: docker (Ubuntu 18.04 LTS host)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL): https://try.gitea.io/Arrow
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
When a project avatar is not specified, the project list (both in explore and organizational listings) shows a "hole" placeholder. It would probably be better to either have a default project avatar, or to not even show the place holder. 

## Screenshots
![image](https://user-images.githubusercontent.com/14616851/58748780-013d9880-8443-11e9-86c1-d2cd0eb7047c.png)

**Comment by lunny** [comment]
will be fixed by #7087
