### ISSUE TITLE
Repo avatar alignment on Explore page

### ISSUE THREAD

**Issue by bkraul** [go-gitea/gitea#7103]
- Gitea version (or commit ref): 8eba27c
- Git version: 1.9.0+dev-314-g8eba27c79
- Operating system: docker (Ubuntu 18.04 LTS)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL): https://try.gitea.io/Arrow
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
The vertical alignment of the project avatar on the Explore page looks a little weird. It seems it would look better if it was vertically centered with the text, like it is on the project page. Looking closer, it looks like the one on the project page could be fine-tuned as well 😃 . (screenshots attached).
## Screenshots
![image](https://user-images.githubusercontent.com/14616851/58761294-4546a100-8508-11e9-9700-745a0f4aac3e.png)
![image](https://user-images.githubusercontent.com/14616851/58761307-5abbcb00-8508-11e9-88be-0168665133c5.png)

**Comment by saitho** [comment]
I was able to successfully align the repository avatar vertically using flexbox.
Just leaving some notes on the HTML and CSS I've used for now - I'm currently on Windows and can't add the changes on that. ^^

Repository page title part:
```
<div class="ui huge breadcrumb repo-title" style="display: flex;align-items: center;">
	<img class="ui avatar image" src="/repo-avatars/5564-f6a2875c257b57343b1a765f077d3ab4" style="margin-right: 0.5em;">	
	<div>
		<a href="/Arrow">Arrow</a>
		<div class="divider"> / </div>
		<a href="/Arrow/TestRepo">TestRepo</a>
	</div>
</div>
```

Repository list item header:
```
<div class="ui header">
	<div style="display: inline-flex;align-items: center;">
		<img class="ui avatar image" src="/repo-avatars/5564-f6a2875c257b57343b1a765f077d3ab4" style="margin-right: 0.5em;">
		<a class="name" href="/Arrow/TestRepo">TestRepo</a>
	</div>
	<div class="ui right metas">
		<span class="text grey"><i class="octicon octicon-star"></i> 0</span>
		<span class="text grey"><i class="octicon octicon-git-branch"></i> 0</span>
	</div>
</div>
```

**Comment by silverwind** [comment]
Maybe also bump the size if the avatar a bit so it matches the second screenshot more closely.

**Comment by bkraul** [comment]
@silverwind  Hmm...not sure, it would look too big...

**Comment by silverwind** [comment]
I think it should be at least slightly bigger than the highest letter. But I don't see why not make them the same size, given the font seems also to be the same size.

**Comment by bkraul** [comment]
Soooo, stale because it's not going to be addressed?

**Comment by saitho** [comment]
> Soooo, stale because it's not going to be addressed?

Stale because no one replied to this issue for two month.

**Comment by silverwind** [comment]
Looks okay currently:

<img width="300" alt="Screenshot 2023-05-01 at 21 54 26" src="https://user-images.githubusercontent.com/115237/235520061-183a9106-f64a-4c64-97f3-a33ef650ccd1.png">
