### ISSUE TITLE
What do team_unit.type=1 to 7 represent in the db?

### ISSUE THREAD

**Issue by yanOnGithub** [go-gitea/gitea#7104]
- Gitea version (or commit ref): 1.8.2
- Git version: git version 2.13.0.windows.1
- Operating system: windows 10
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description
Most of the data have all 7 types. Some data do not have all 7 types.

**Comment by zeripath** [comment]
https://github.com/go-gitea/gitea/blob/8eba27c79257c6bc68cefbdffbb36d3596e6d3ee/models/unit.go#L17-L26
