### ISSUE TITLE
Unable to migrate from 1.7.6 to 1.8.0 and beyond

### ISSUE THREAD

**Issue by lgrahl** [go-gitea/gitea#7105]
- Gitea version (or commit ref): v1.9.0+dev-314-g8eba27c79 (Docker)
- Git version: 2.20.1
- Operating system: Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist: https://gist.github.com/lgrahl/3e9992345ad6b83650492af4b2bbba61

## Description

First of all, many thanks for maintaining this awesome project! :+1: 

I'm trying to migrate from a 1.4.x database version to 1.8.0. I've been able to slowly migrate my database from 1.4.x to 1.7.6 but as soon as I try 1.8.0, I always run into an error for the following migration routine: `Migration[82]: hot fix for wrong release sha1 on release table`. This eventually fails with the cryptic error `ORM engine initialization failed: migrate: do migrate: no such file or directory`. I tried running the latest Docker tag to see if #6387 fixes it but that fails with the same error.

See the Gist linked above for a full log.

**Comment by lafriks** [comment]
Have you tried upgrading directly to 1.8.2?

**Comment by lgrahl** [comment]
Initially, yes. But I had a backup of the database and then tried incrementally upgrading to 1.7.6. The result was the same.

**Comment by lgrahl** [comment]
I've solved the mystery. My repository path changed and I misinterpreted the above error. Works fine for me now. :+1:
