### ISSUE TITLE
Unnecessary pull request restriction 

### ISSUE THREAD

**Issue by PlanetRenox-zz** [go-gitea/gitea#7106]
- Gitea version: 1.8.2
- Operating system: CentOs 7
- Database:
  - [x] SQLite
- Can you reproduce the bug?
  - [x] Yes 

## Description

Unable to approve own pull request if you are the only whitelisted user capable of approving requests. 

This restriction seems unnecessary.

**Comment by wxiaoguang** [comment]
If you the the only approver, why not just merge it?

From another point of view, "approve own pull request" seems also unnecessary .... GitHub also do not allow self-approve IIRC.

**Comment by delvh** [comment]
We allow approving your own PR at all?
No, just tested it, that's not possible, and I would like to keep it this way…

**Comment by eeyrjmr** [comment]
There is a way and it is if you are the admin of the repository. 

I opened a feature request to disable this since code review is beneficial (the repo admin can turn it off if they need to force something through).

**Comment by wxiaoguang** [comment]
> There is a way and it is if you are the admin of the repository.

If they are the only user, why just consider "Merge it" as approved and "Close it" as rejected? Why someone needs to approve their own PRs?

**Comment by eeyrjmr** [comment]
> > There is a way and it is if you are the admin of the repository.
> 
> If they are the only user, why not just consider "Merge it" as approved and "Close it" as rejected? Why someone needs to approve their own PRs?

Why enable branch protection if you are the only user.
