### ISSUE TITLE
Cannot fork repo I own, cannot push new branch to it (permission denied)

### ISSUE THREAD

**Issue by strk** [go-gitea/gitea#7110]
I'm experiencing this frustrating event on gitea.com:
1. I have a fork of gitea/tea
2. The "fork" button on gitea/tea is grayed out with message "you cannot fork a repository you own"
3. I cannot push a new branch to the main repo: "remote: User permission denied"
4. I cannot file a pull request from existing fork because that fork is not found by the pull-down menu

This is, as reported from gitea.com: Gitea Version: 1.9.0+dev-316-g9002c5157

**Comment by strk** [comment]
For the record: my fork is seen when hitting the "forks" button:
https://gitea.com/gitea/tea/forks
just isn't shown in the pull-down menu from https://gitea.com/gitea/tea/compare/master...master

**Comment by zeripath** [comment]
So if I understand the situation correctly you shouldn't be able to push a new branch to the main repo as there is a protected branch.

I think you're suffering from the poor design of the compare endpoint. 

I think your PR link should be:

https://gitea.com/gitea/tea/compare/master...strk:pulls-create 

but this screen is somewhat broken and I think it needs a lot more work.

**Comment by lunny** [comment]
2. You have a fork so that you cannot fork it twice, but I think it's not right that you could fork it to another organization. This should be improved.
3. You have no permission to push a branch to main repo because you have no write permission of that repository.
4. create a pull request from your fork repository should display correct UI. It shows https://gitea.com/gitea/tea/compare/master...strk:master , it's right. don't know why you get https://gitea.com/gitea/tea/compare/master...master

**Comment by strk** [comment]
I probably forked _before_ I was made an owner, or something like that.
Why I shouldn't have been able to fork to another organization ? That's my typical approach: fork to under my own name.

I get the master...master link if I go to "Pull requests" from the main repo, not from my fork (I didn't try my fork before).

**Comment by lafriks** [comment]
You should be able to fork repositories from organization to your own user...

**Comment by lunny** [comment]
@lafriks I think github allows user fork himself repositories to organizations.

**Comment by lunny** [comment]
@strk so when you click the `New Pull Request` button a main repository on github.com, it has the same behavior with gitea. You should click the button on your fork repository.

**Comment by strk** [comment]
@lunny github has a "compare across forks" link right above the selector. Clicking that link adds a "fork selector" pull-down menu.

**Comment by strk** [comment]
BTW, the version of Gitea we're running (1.5) does NOT have a way to `create a pull request from your fork repository`, or I cannot find it

**Comment by lunny** [comment]
@strk v1.5 is too old
