### ISSUE TITLE
https://docs.gitea.io/en-us/comparison/

### ISSUE THREAD

**Issue by grinapo** [go-gitea/gitea#7114]
*Accidentally* some features were forgotten in the comparison:
* supports hg/mercurial, svn/subversion
* supports wiki 
* self-hostable (unless they all are)

**Comment by lunny** [comment]
Please send a PR to that docs

**Comment by lafriks** [comment]
I compared only self-hostable solutions

**Comment by grinapo** [comment]
@lafriks me too. I try to extend it a bit but I'm doing too much at the moment, so either someone with more time want to extend it, or wait for me, or choose not to worry about it (which is not really fair, comparison-wise, though not entirely unexpected).

**Comment by Cherrg** [comment]
> supports hg/mercurial, svn/subversion

I don't know if this features are in the scope of gitea

>  here is how it compares to other `Git` self hosted options.

May someone can fill in the gaps. So the PR should be done really fast. Let's collect the information here, if they really should be added to comparison.

|                                                      |  Gitea | Gogs | GitHub EE | GitLab CE | GitLab EE | BitBucket | RhodeCode CE
|:------------------------------------------ | -- | -- | -- | -- | -- | -- | -- |
| Migration from hg/Mercurial         | X | X | ? | ? | X | ? | ? |
| Migrattion from svn/Subversion   | X | X | ? | ? | X | ? | ? |
| Support hg/Mercurial clients        | X | X | ? | ? | ? | ? | ? |
| Support svn/Subversion clients     | X | X | ✓| ? | ? | ? | ? |
| hg/Mercurial support                      | X | X | ? | ? | ? | ✓ | ? |
| svn/Subversion support                | X | X | ? | ? | ? | ✓ | ? |

Note some tools mentioned above uses third party tools for migration or uses command line and written a documentation how to migrate from XY. As this is not supported via UI I have crossed this.

I don't know if it is nessesary to add something to the comparison, if it is only supported by none or one.

> supports wiki

already there, look for `Integrated Git-powered wiki` 

> self-hostable (unless they all are)

as mentioned before, the all self hostable

**Comment by lafriks** [comment]
I don't really see much point for comparing support for other VCS as we are comparing **Git** hosting solutions

**Comment by grinapo** [comment]
@lafriks  Then please mention that *"this table contains **only git related** subjects since gitea only supports that; other VCS support may be available in the alternatives"*.

The main reason of mine was that I was looking around for *mercurial* UIs and lots of available "git" named UI actually support svn, hg and some else. Since I prefer to see what the developers say about thir own stuff first I have came here and seen that I can't tell whether it actually supports anything else, and I have noticed that some listed alternatives do. It may help true comparison of the alternatives, from your perspective. (Naturally I look around elsewhere, too, but that comes after you. :-))
