### ISSUE TITLE
Approvals number on pull request list

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#7116]
If the approvals number displayed on pull request list, that will help.

**Comment by Toxik1983** [comment]
Any indication on when this feature will be implemented? Our team processes a large number of PRs a day, and we use a system of 2 needed approvals. The PRs that have already been approved by one reviewer could more easily be prioritized by the other reviewers if this number was shown in the list.

**Comment by lafriks** [comment]
I think it's being worked on as should be available in 1.12

**Comment by otbutz** [comment]
https://github.com/go-gitea/gitea/pull/10238

**Comment by zeripath** [comment]
@otbutz #10238 almost completes this feature but it doesn't give an idea of how many reviews are required - which is why I didn't close this bug with that pr.

**Comment by otbutz** [comment]
Ah, thanks for that insight. But nevertheless, it's progress ;)

**Comment by camlafit** [comment]
This feature is asked by SPIP community as we have many PR. It'll helpful to process final review/merge with a one page to check state approval :)

**Comment by brunob** [comment]
I think this one could be closed now :)

**Comment by otbutz** [comment]
> @otbutz #10238 almost completes this feature but it doesn't give an idea of how many reviews are required - which is why I didn't close this bug with that pr.

Is that one covered?
