### ISSUE TITLE
Pull request merge strategy

### ISSUE THREAD

**Issue by rudineirk** [go-gitea/gitea#712]
A nice feature to have would be squash and rebasing options to accept a pull request, like github does.

![merge](https://cloud.githubusercontent.com/assets/5260987/22162970/168435bc-df38-11e6-9315-081880fb9e5d.png)

I think the UI for the merge options could be something like github, as it's very simple to select a merge option.

Github also has a project configuration UI to enable/disable the pull request merge modes on a per project basis. Not every project mantainers would like to leave all options enabled, so this could be necessary.
![merge_config](https://cloud.githubusercontent.com/assets/5260987/22163167/dd5688d4-df38-11e6-9e75-ed837ec7e993.png)

**Comment by bkcsoft** [comment]
(fixed the formatting on the bug-bounty-text)

**Comment by priyadarshan** [comment]
It would be so useful to be able to choose a merge strategy. If it helps, this is [how GitLab does it](https://docs.gitlab.com/ee/user/project/merge_requests/squash_and_merge.html), and this is how [BitBucket does it](https://confluence.atlassian.com/bitbucketserver/merge-a-pull-request-808488562.html).

**Comment by bkcsoft** [comment]
+1 on merge strategies, very helpful when I (as a contributor) know I have or will have lots of commits and it should be squashed.
