### ISSUE TITLE
From Jenkins HTTP 404/Not Found

### ISSUE THREAD

**Issue by rccclr** [go-gitea/gitea#7122]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
Error from Jenkins with connect to Gitea

org.jenkinsci.plugin.gitea.client.api.GiteaHttpStatusException: 
HTTP 404/Not Found
	at org.jenkinsci.plugin.gitea.client.impl.DefaultGiteaConnection.getObject
(DefaultGiteaConnection.java:900)

Any help is appreciated.

Many thanks
...

**Comment by rccclr** [comment]
Sorry, the problem is the name of the Organization.

Fix with correct value.

**Comment by rogeriorc** [comment]
This demands a better Error Message to the user.

**Comment by jolheiser** [comment]
We do not maintain the Gitea Jenkins plugin, you can find the repository here: https://github.com/jenkinsci/gitea-plugin
