### ISSUE TITLE
Statuses API only shows first 10 statuses

### ISSUE THREAD

**Issue by DavidRobinsonDk** [go-gitea/gitea#7136]
- Gitea version: 1.8.2 built with go1.12.5 : bindata, sqlite, sqlite_unlock_notify
- Git version: 2.20.1
- Operating system: Ubuntu Server 19.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes (https://try.gitea.io/api/v1/repos/dr/test/statuses/c07b30e95383d317fd01d475bbc782e8c79154fc?access_token=bb4a3d4df85b11c3d9777bc4a6d36f3e06b2f3a9)
  - [ ] No
  - [ ] Not relevant
- Log gist:
N/A

## Description
I have created much more than 10 statuses on the linked commit above. Yet the statuses API only shows the first 10. If it must be limited to 10, I believe it should at least be the 10 most recent.

**Comment by lunny** [comment]
should be closed by #7141

**Comment by zeripath** [comment]
#7141 does fix this - but it's not perfect the API returns a bare []api.Status with no space to say how many statuses there are - so you just have to page until you reach the end.
