### ISSUE TITLE
Set private status about Organization (not logged)

### ISSUE THREAD

**Issue by camlafit** [go-gitea/gitea#714]
- Gitea version (or commit ref): 1.0.1
- Git version:
- Operating system: Linux 386 Jessie
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ x ] MySQL / MariadDB
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ x ] Not relevant
- Log gist:

## Description

We can set repositories by default to private, then it's useful on internal git hosting , but explore user and organization public page provide all accounts and all organization ( https://try.gitea.io/explore/users & https://try.gitea.io/explore/organizations )

If we want an all private git hosting, we could set  private these page and allow display data only to connected account

...

**Comment by camlafit** [comment]
Result looks be similar, disable explore page can be an alternative ui configuration. An option to allow : 
* full view public (as actual)
* full only connected 
* filter to related organization/users to account connected

**Comment by DblK** [comment]
Do we agree that the option should be on the settings page of the organization?
So if I understand well, we should add a "Visibility" option with a dropdown with 3 choices and take those information in consideration to display (or not) the organization on various page.
Am I right?

**Comment by camlafit** [comment]
Hi

Yes, looks correct on each Organization we could have an option to allow visibility or not about Organization itself and user set in this Organization (public, to each user connected, only to user on same organization, never).

Looks enough as this. If an user can see an organization, he can see also all users related. Doesn't look required to have an option at user level.

**Comment by DblK** [comment]
Okay, I get the idea. What is the use of the fourth choice "Never"? How you will use it?

What about the repositories linked to an organization?
For public repositories:
- Visible if Organization is Public or ConnectedUser
- Invisible if Organization is Private

For private repositories:
- Visible if member are part of the organization AND has a role on this repository.
- Invisible th rest

**Comment by camlafit** [comment]
Hi

I've thought a "never" option if we need set private on any case a repository. Then should be accessible only with direct url. Never display on explore/organization.
In this case repositories should be accessible only on direct access.

About repositories looks great as proposed.

**Comment by DblK** [comment]
If the "never" option is implemented. The organization will be shown nowhere.
Not in the profil, not in the list even if we are member of that organization only by link.

That suppose you will keep the link outside of Gitea and hoping you won't loose it.
For me, I don't see the use of this fourth option.

I will begin the implementation without it.

**Comment by camlafit** [comment]
Hi

I'm agree "Never" option looks extrem. I don't have any use case in my
mind. But looking for possibles option, I find this possibility. Then I've
proposed it to be more complet on my suggestion. :)

**Comment by DblK** [comment]
Perfect. The suggestion was complete.
Actually I personally need this feature so I will implement it soon.

**Comment by bkcsoft** [comment]
Don't implement what you don't use, otherwise you'll never finish 😉

**Comment by camlafit** [comment]
Hi

I'm interested to test when you want :)

**Comment by DblK** [comment]
So the UI will be like this:

![image](https://cloud.githubusercontent.com/assets/832617/26248778/fcdb598c-3ca3-11e7-9c22-7d9f904d28a3.png)

**Comment by camlafit** [comment]
Hi

Looks great, maybe add a precision on Private option  as :
 Visible only to Organization members

**Comment by DblK** [comment]
I will add more options for this feature but you (@camlafit) can already test the PR and tell me if I have thing to do. I will check the activity feed just in case.

**Comment by camlafit** [comment]
Hi 

I'll test this afternoon.

**Comment by amigrave** [comment]
A lots of PR gets flagged as duplicates to this one but the status of #714 keeps stalled.
Is this issue solved in another way ?

**Comment by rakshith-ravi** [comment]
Are there any hopes of seeing this in 1.8?

**Comment by lunny** [comment]
It should be, see #1763

**Comment by rakshith-ravi** [comment]
Oh. Didn't see that. My bad. Thank you

**Comment by techknowlogick** [comment]
closed as PR has been merged :tada:

**Comment by camlafit** [comment]
Thanks a lot  :1st_place_medal:
