### ISSUE TITLE
404 error on the left side of the /pulls page (external issue tracker)

### ISSUE THREAD

**Issue by mindfl** [go-gitea/gitea#7140]
- Gitea version (or commit ref): 1.9.0+dev-325-g59e6a7b97 (try.gitea.io), or stable 1.8.2, or old stable 1.8.1
- Git version: 2.7.4
- Operating system: Ubuntu 16.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (https://try.gitea.io/pulls?type=all&repo=11986&sort=&state=open)
  - [ ] No
  - [ ] Not relevant
- Log gist: -

## Description

404 error on the left side of the /pulls page if repo is configured with no issue tracker, or with an external issue tracker.

### Similar issues

- https://github.com/go-gitea/gitea/issues/6302
- https://github.com/go-gitea/gitea/issues/5892
- https://github.com/go-gitea/gitea/issues/2447
- https://github.com/go-gitea/gitea/issues/1847

But the problem looks like still exists, or may be it's just a similar with closed issues.

### Steps to reproduce

1. Create a repository that is configured with no issue tracker, or with an external issue tracker
2. Create a Pull Request
3. Go to the https://try.gitea.io/pulls page
4. Press on a link on a left side
5. 404, but the filtered page like as repo with gitea internal issue tracker enabled is expected

### Steps to reproduce
![src_20190605-234302](https://user-images.githubusercontent.com/7414997/58989036-bb3e5700-87eb-11e9-8fd4-66c7386da804.png)
### Error
![src_20190606-000424](https://user-images.githubusercontent.com/7414997/58990488-a9aa7e80-87ee-11e9-89e7-5d164efa47ba.png)

**Comment by Toxik1983** [comment]
This issue is still present in 1.10.2. Our team only uses external trackers, so these links are always broken. Please implement a fix.

**Comment by lunny** [comment]
I think this is because you ever used internal issue tracker and then converted to external issue tracker. But this is a real bug that we should don't display those repositories which has external issue tracker enabled.

**Comment by Toxik1983** [comment]
> I think this is because you ever used internal issue tracker and then converted to external issue tracker.

I believe you are right. A lot of other projects work fine with a combination of PRs and external trackers. Isn't there some way to get rid of the old issue tracker data?

> But this is a real bug that we should don't display those repositories which has external issue tracker enabled.

I don't think that is correct. The /pulls page should just be a list of PRs, at least in our case. But there is an internal dependency on issues, because the links to the PRs of other projects with an external tracker enabled point to [organization]/[project]/issues/[id] but actually just redirect to [organization]/[project]/pulls/[id].

**Comment by guillep2k** [comment]
This may have been fixed in #10092

**Comment by Toxik1983** [comment]
> This may have been fixed in #10092

Thanks for mentioning this, I'll keep an eye on the release logs and update when it's available.

**Comment by Toxik1983** [comment]
> > This may have been fixed in #10092
> 
> Thanks for mentioning this, I'll keep an eye on the release logs and update when it's available.

Somehow I missed this in the 1.11.0 release log. I updated this morning and can confirm that this has been fixed.
