### ISSUE TITLE
Backups don't run because of incorrect user

### ISSUE THREAD

**Issue by dunestorm333** [go-gitea/gitea#7142]
- Gitea version (or commit ref): 1.9.0+dev-325-g59e6a7b97
- Git version: 2.20.1
- Operating system: Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:
./app/gitea/gitea dump -f /data/backups/import.zip                    
2019/06/05 21:03:39 ...s/setting/setting.go:828:NewContext() [F] Expect user 'git' but current user is: root

## Description
Despite my username being "git" matching the one in app.ini, gitea dump misidentifies my user as being root:

bash-4.4# echo $USERNAME                                                        
git                                                                             
bash-4.4# echo $USER                                                            
git

...

**Comment by techknowlogick** [comment]
How are you running your backups? Is it via crontab?

**Comment by dunestorm333** [comment]
@techknowlogick I'm running the backups manually, I haven't tried through crontab yet though it is running inside of a Docker container.
