### ISSUE TITLE
feature request: new column in user accounts overview for authentication source

### ISSUE THREAD

**Issue by matrix1000** [go-gitea/gitea#7145]
Please can you add a new column (authentication source) in the User accounts overview from admin panel?
This helps for a better overview of authentication source.
So that an admin can see all authentication source of all users in one page.

Many thanks.

- Gitea version (or commit ref): 1.8.2
- Git version: 2.17.1
- Operating system: debian
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ x ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ x ] Not relevant
- Log gist:

## Description

...

**Comment by lunny** [comment]
I think we can't  because a user could have multiple auth sources.

**Comment by matrix1000** [comment]
And why not a list of auth sources per user in the overview?
