### ISSUE TITLE
SessionProvider MySQL credentials are shown in the admin GUI as plaintext

### ISSUE THREAD

**Issue by vpr-ossteam** [go-gitea/gitea#7147]
- Gitea version (or commit ref): 1.8.1
- Git version: 2.7.4
- Operating system: Ubuntu 16.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
Greetings!
I'm using Gitea 1.8.1 with MySQL 5.7. And if I'm using MySQL for session storing purposes, I can see the credentials in GUI as plaintext. 

**Steps to reproduce**

1. Select MySQL like a sessions storage in the config file:
```
[session]
PROVIDER        = mysql
PROVIDER_CONFIG = someclient:somepassword@tcp(srv-mysql:3306)/someclient
```
2. Reload Gitea
3. Login in into Gitea with admin credentials
4. Follow this way: Site Administration ⇒ Configuration ⇒ Session Configuration ⇒ Provider Config

## Screenshots

![20190525-152945](https://user-images.githubusercontent.com/23170292/59055478-935bfb80-889e-11e9-90d5-6b99fc211fe0.png)

**Comment by markkrj** [comment]
I still can see the password. I'm on version 1.10.0.
![image](https://user-images.githubusercontent.com/13537652/69361304-f5e95e00-0c6a-11ea-86bc-71979a2969ef.png)

**Comment by zeripath** [comment]
This was reFixed in #9002 and #8984

**Comment by markkrj** [comment]
@zeripath Well, now it shows nothing:
![image](https://user-images.githubusercontent.com/13537652/69434813-238edf80-0d1d-11ea-8f18-d009c5e7b4ce.png)
Running 1.10.0+10-gade5ec5aa

But still better than showing credentials.

**Comment by zeripath** [comment]
Do you have/get any logs?

**Comment by markkrj** [comment]
No errors or strange logs in console, just usual router logs... I have the default [gitea.log](https://github.com/go-gitea/gitea/files/3880752/gitea.log). Tell me if you need more.
