### ISSUE TITLE
I can't do cross compile to ARM since vfsgen was added

### ISSUE THREAD

**Issue by esfraner** [go-gitea/gitea#7149]
- Gitea version (or commit ref): latest from master
- Git version: 2.11.0
- Operating system: Linux debian
- Database:
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
I can't do cross compile to ARM from x86_64 since vfsgen was added in #7080. If I use the [previous commit](https://github.com/go-gitea/gitea/commit/8eba27c79257c6bc68cefbdffbb36d3596e6d3ee) (using go-bindata) there isn't any problem :cry: 

I realized that the error comes from [`//go:generate go run -mod=vendor main.go`](https://github.com/go-gitea/gitea/blob/master/modules/options/options.go#L7) lines

I'm running this command: `GOOS=linux GOARCH=arm GOARM=7 TAGS="bindata" make generate build`
## Screenshots
![image](https://user-images.githubusercontent.com/22304628/59073887-55c09800-88c9-11e9-921f-0d44d3a3b98a.png)

**Comment by sapk** [comment]
What version of go do you use ?

**Comment by esfraner** [comment]
> What version of go do you use ?

I am using 1.11.10

**Comment by sapk** [comment]
Ok, I think it failed because it try to run the generation via vfsgen for arm.
Can you try this order of commands ? (generate without the cross flags)
```
make generate
GOOS=linux GOARCH=arm GOARM=7 TAGS="bindata" make build
```

**Comment by esfraner** [comment]
@sapk, thank you It was the problem :smile:
