### ISSUE TITLE
Pushes to Org repo show the Org itself pushing in the dashboard

### ISSUE THREAD

**Issue by silverwind** [go-gitea/gitea#7150]
To reproduce using current master at https://github.com/go-gitea/gitea/commit/8de0b0a3f06fe7879fb014d2624209e0e48455a0:

1. Create Org
2. Create Repo on Org
3. Push to the repo via SSH

On the dashboard feed it weirdly shows as if the org account itself did the push while it should be the user account:

<img width="497" alt="Screenshot 2019-06-07 at 09 48 07" src="https://user-images.githubusercontent.com/115237/59089111-a0620480-8909-11e9-93fa-5b55f462698c.png">

I think this regressed within in the last few weeks.

**Comment by kolaente** [comment]
Can confirm, this is somewhat annoying....
