### ISSUE TITLE
Can't create file via API

### ISSUE THREAD

**Issue by strahe** [go-gitea/gitea#7152]
- Gitea version (or commit ref): 1.8.2
- Git version: 
- Operating system: linux
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

always: Error: Unprocessable Entity

## Screenshots

![s](https://user-images.githubusercontent.com/7932644/59092056-40884f80-8943-11e9-96d2-faa9acbc66c5.png)

![s1](https://user-images.githubusercontent.com/7932644/59091869-d374ba00-8942-11e9-870b-dc943f6b2791.png)

**Comment by nopjmp** [comment]
Looks like you need to supply a message via the error message for the commit

https://github.com/go-gitea/gitea/blob/43cf2f3b55de4a69183966da2a6e0167592c733c/modules/structs/repo_file.go#L8-L28

**Comment by jolheiser** [comment]
The comment says it is optional and mentions a default message, however I could not find anything to support that in the code.   
Currently the message has no default, so it is correctly bound as `required`

@richmahn Looks like the comments were added in https://github.com/go-gitea/gitea/commit/43cf2f3b55de4a69183966da2a6e0167592c733c#diff-ec0f0f34b75aa5b40d1a7e55251a9c35  
Thoughts?

**Comment by nopjmp** [comment]
the binding in the struct is "Required" so the json parser will return an error.

**Comment by richmahn** [comment]
@jolheiser Interesting. I know I brought in the comments from another part of the code and guess that wasn't caught. Will see if message can be optional and will removed the required flag.

**Comment by richmahn** [comment]
I'll work on fixing this.

**Comment by richmahn** [comment]
Fixed in PR #7324
