### ISSUE TITLE
HTML escaping in code review comments

### ISSUE THREAD

**Issue by ptman** [go-gitea/gitea#7153]
- Gitea version (or commit ref): 1.8.2
- Git version:
- Operating system: docker
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes https://try.gitea.io/basti/gitea/pulls/1/files#issuecomment-11854
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

XSS in code review comments. <br> tag not escaped: https://try.gitea.io/basti/gitea/pulls/1/files#issuecomment-11854

**Comment by ptman** [comment]
Hmm.. it wasn't escaped here either, since markdown allows html?

**Comment by silverwind** [comment]
Markdown allows a limited subset of HTML (no `<script>` etc), see the [spec](https://spec.commonmark.org/0.29/#raw-html).

**Comment by zeripath** [comment]
@ptman I can't seem to get there to be a sanitisation problem. The resultant HTML is completely sanitised on render the only thing I would say is that downstream users of the comments could end up mis-sanitising.

**Comment by ptman** [comment]
ok, my bad. Maybe every place that can take markdown input should have a link to syntax to remind?
