### ISSUE TITLE
favicon.png update favicon.ico

### ISSUE THREAD

**Issue by timBen9527** [go-gitea/gitea#7155]
Tōngguò zì dìngyì fāngshì wúfǎ zài google Chrome zhōng wúfǎ xiǎnshì, jiànyì jiāng favicon.Png xiūgǎi wèi favicon.Ico géshì jìnxíng xiǎnshì
65/5000
Customizable cannot be displayed in google Chrome. It is recommended to change favicon.png to favicon.ico for display.

![image](https://user-images.githubusercontent.com/38236663/59143986-a3d9b680-8a03-11e9-85b9-6e4067bc9591.png)

![image](https://user-images.githubusercontent.com/38236663/59143962-39287b00-8a03-11e9-8cdc-fb650b834204.png)

**Comment by silverwind** [comment]
PNG favicons work in all modern browsers and I have a custom one that also works. Maybe something wrong with the PNG file you're using?

**Comment by Bryanpedini** [comment]
@xianlin6189 if you need a custom favicon for your gitea hosted website I think using a free online utility to convert PNG to ICO and just keeping a PNG copy locally with the ICO on the server, wouldn't be much of an hassle to do every time, since I don't think you change favicon this often...

**Comment by Ryuno-Ki** [comment]
The default icon is an SVG with a PNG as fallback:

https://github.com/go-gitea/gitea/blob/73382d2132f8f242245d83f66c92761e0b477b91/templates/base/head.tmpl#L22-L23

Works fine on my end. Which version of Google Chrome is affected?
(I suspect this issue is invalid)
