### ISSUE TITLE
does it support go-git?

### ISSUE THREAD

**Issue by catastrop** [go-gitea/gitea#7161]
go-git - https://github.com/src-d/go-git

**Comment by lunny** [comment]
I think you mean use go-git as a client library to interact with Gitea server? As I know, it's yes.

**Comment by catastrop** [comment]
>Git with a cup of tea, painless self-hosted git service

I mean can i use go-git instead of git.

**Comment by lunny** [comment]
We have moved some commands from `git command` to `go-git` and will keep moving.

**Comment by catastrop** [comment]
cool!
