### ISSUE TITLE
Allow edits from maintainers in PR

### ISSUE THREAD

**Issue by rugk** [go-gitea/gitea#717]
It would be nice to introduce the same feature that GitHub now has:
![prallowedits](https://cloud.githubusercontent.com/assets/11966684/19346855/def2cd6a-9145-11e6-9a5b-752adcc28494.png)

As far as I understand it this allows maintainers of the main repo, where you submit a PR to, to push to your PR. So they can now improve your PR without having to wait that the creator of the PR fixes the issues.

---

upstream issue: https://github.com/gogits/gogs/issues/3762

**Comment by bkcsoft** [comment]
This might be a bit hard at the moment, since we now only map `HasAccess(user, repo)` and not `HasAccess(user, repo, branch)`... And we would have to check which branches are being pushed, which might lead to security issues 🙁

**Comment by wxiaoguang** [comment]
* https://github.com/go-gitea/gitea/pull/18002
