### ISSUE TITLE
Can I access the review approval+reject+comment panel without waiting for a long diff to load?

### ISSUE THREAD

**Issue by yanOnGithub** [go-gitea/gitea#7172]
- Gitea version (or commit ref): 1.8.2
- Git version: 2.x
- Operating system: windows 2012
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

I often receive pull requests consist of 1000 lines changed scattered in 70 files. The diff takes a while to load. The approval+reject+comment panel is inaccessible before the diff is 100% loaded in the browser. I normally do code review with custom scripts outside Gitea.

**Comment by yanOnGithub** [comment]
If the gitea diff does not finish loading in a few minutes, I normally merge in CLI on client side, then push to the develop branch in gitea. The approval is bypassed. The PR is merged.

**Comment by yanOnGithub** [comment]
The diff may be 100 pages long. The html source is 170,000 lines long. The review button is still loading and inaccessible.
70 changed files with 5701 additions and 3125 deletions

![Picture1](https://user-images.githubusercontent.com/25423046/59236929-c3065d00-8c2a-11e9-91c2-dde7b12f3c07.png)

**Comment by yanOnGithub** [comment]
Reducing these numbers in the config file probably helps:

MAX_GIT_DIFF_LINES
MAX_GIT_DIFF_LINE_CHARACTERS
MAX_GIT_DIFF_FILES

**Comment by zeripath** [comment]
Hi @yanOnGithub I think we do need to look at this properly. I suspect that we need to make the diff page do some Ajax requests rather than do it all in one go.

**Comment by yanOnGithub** [comment]
I think @zeripath probably want to increase the capacity of the diff page. Consider something like midnight commander 2-panel interface. List of files on the left, and a diff of the selected file on the right. Consider supporting infinite scrolling on the diff panel. Humans TLDR and a way to locate something is needed.

3-panel design can be "directory tree" + "files in selected directory" + "diff of selected file"

Dumping the full diff of all changed files can overflow the browser. In the current design, some interactivity happens on each line. A large amount of DOM node or html source may be there to support the interactivity.

MAX_GIT_DIFF_LINES
MAX_GIT_DIFF_LINE_CHARACTERS
MAX_GIT_DIFF_FILES

Limiting these 3 config variables allowed the reviewer to click the approve and reject buttons. I am running ```git diff $mergeBase..$featureHead``` outside the browser anyway. A pull request with 180 MB files changed is looming. The PR comes with both text and binary files. I need the text file diffs for code review. Binary files are not analyzed in my code review.

Consider re-opening this issue for feature enhancement.

**Comment by yanOnGithub** [comment]
top and bottom panel design would allow long paths and lines

![image](https://user-images.githubusercontent.com/25423046/60307679-3e307880-9978-11e9-81c9-63bff0d268ad.png)
