### ISSUE TITLE
Search not working for administrator

### ISSUE THREAD

**Issue by salco** [go-gitea/gitea#7173]
- Gitea version (or commit ref): 1.8.0
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X] No
   - Since I'm not administrator
  - [ ] Not relevant

## Description
On my setup I activated the indexer.
Everything work fine for a normal user, I can search repo. and search for code inside them. But for user with administrator right (for the gitea server), they are unable to search anything.

So to resume, search for normal user work fine but search for administrator user doesn't work.
I put a screenshot of the result for administrator and one for the normal user. 

Can it be an issue in how the search work?
...

### Administrator
![searchAdmin](https://i.imgur.com/Sqz2GcH.png)
### Normal user
![searchNormal](https://i.imgur.com/NuZqcej.png)

**Comment by lunny** [comment]
Any logs on gitea server?

**Comment by salco** [comment]
I've tested with admin and normal and there is the result.
The log doesn't show anything different.
```
2019/06/10 12:56:35 [D] CSRF Token: eLYwtqlAUfxmpqJ4rW04cnTNOfY6MTU2MDE4NTM3ODQwNTYwMTMxNg==
2019/06/10 12:56:35 [D] Template: pwa/serviceworker_js
2019/06/10 12:56:35 [D] Template: pwa/manifest_json
2019/06/10 12:56:51 [D] Session ID: 0f7ba8d7d0d338ba
2019/06/10 12:56:51 [D] CSRF Token: izTZ5xmOAJPaNbEVpYtE9BtqujY6MTU2MDE2OTQxODg3MDY3NDIxOQ==
2019/06/10 12:56:51 [D] Template: org/home
2019/06/10 12:56:51 [D] Session ID: 0f7ba8d7d0d338ba
2019/06/10 12:56:51 [D] CSRF Token: izTZ5xmOAJPaNbEVpYtE9BtqujY6MTU2MDE2OTQxODg3MDY3NDIxOQ==
2019/06/10 12:56:51 [D] Template: pwa/manifest_json
2019/06/10 12:56:53 [D] Session ID: 0f7ba8d7d0d338ba
2019/06/10 12:56:53 [D] CSRF Token: izTZ5xmOAJPaNbEVpYtE9BtqujY6MTU2MDE2OTQxODg3MDY3NDIxOQ==
2019/06/10 12:56:53 [D] Template: pwa/serviceworker_js
```

**Comment by lunny** [comment]
It seems you didn't paste routes log?
