### ISSUE TITLE
500 error when PR comment

### ISSUE THREAD

**Issue by ferrmin** [go-gitea/gitea#7178]
- Gitea version (or commit ref):1.8.2
- Git version:2.17.1
- Operating system:Ubuntu 18.04.2 LTS
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Log gist:
```
[...routers/repo/pull.go:962 CompareAndPullRequestPost()] [E] NewPullRequest: newIssue: Error 1366: Incorrect string value: '\xF0\x9F\x98\xAC' for column 'content' at row 1
```

**Comment by lunny** [comment]
This has been fixed on v1.9 to set database as `CHARSET = utf8mb4`.
