### ISSUE TITLE
Long commit message hides commit status icon

### ISSUE THREAD

**Issue by timothyqiu** [go-gitea/gitea#7180]
- Gitea version (or commit ref): 1.8.2
- Git version: 2.11.0
- Operating system: Debian 9.9
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant

## Description

In the commits table (both in commits and pull request page), the commit status icon will be hidden if the commit message is too long.

I think the commit status icon is not part of the commit message. It'll be better if the icon is always shown.

## Screenshots

The long commit message is truncated with ellipsis, hiding the commit status icon.
![truncated](https://user-images.githubusercontent.com/372476/59247861-52c00180-8c53-11e9-9a66-5876c5cb9579.png)

Narrow the browser, and the commit status icon appears.
![narrow](https://user-images.githubusercontent.com/372476/59247870-59e70f80-8c53-11e9-810e-c7233e27ec3c.png)

**Comment by belliash** [comment]
I agree, icon should be always seen. Sometimes, the message is not cut and the "..." link is shown instead of icon.

**Comment by silverwind** [comment]
How does one get such a status icon? Does it need a CI?

**Comment by jolheiser** [comment]
@silverwind https://try.gitea.io/api/v1/swagger#/repository/repoCreateStatus  
I believe both Drone and Jenkins plugins use the endpoint.
