### ISSUE TITLE
 File diff suppressed because it is too large on a 82 line code file

### ISSUE THREAD

**Issue by Qubitium** [go-gitea/gitea#7184]
Gitea 1.8.2
---------------

We are getting "File diff suppressed because it is too large" notices on the diff page for tiny files that is less than 100 lines of total code. There must be some broken logic regarding the "limit" set in place for fil diff. 

Due to privacy, we obviously cannot post the actual file content here.

**Comment by apricote** [comment]
Check your config file for the `[git]` section, you can configure the limits in there.

> `MAX_GIT_DIFF_LINES`: 100: Max number of lines allowed of a single file in diff view.
> `MAX_GIT_DIFF_LINE_CHARACTERS`: 5000: Max character count per line highlighted in diff view.

Reference: https://docs.gitea.io/en-us/config-cheat-sheet/#git-git

As far as I understood the function [`ParsePatch`](https://github.com/go-gitea/gitea/blob/d578b71d61ee8131e8abf7f538b93d8c6cc6fe6d/models/git_diff.go#L421), if the file has more than `MAX_GIT_DIFF_LINES` lines, or any line is longer than `MAX_GIT_DIFF_LINE_CHARACTERS`, then the file diff is suppressed.

**Comment by diegomontoya** [comment]
@apricote  Thank you. We hit the per line 5000 char Max limit on special line of code containing const string. 

Perhaps the error msg can hint at the type of LIMIT instead of using the current catchall "File too large?" For tiny files with long lines, the current error msg is somewhat misleading.

**Comment by lunny** [comment]
yes, I think the message should be updated.
