### ISSUE TITLE
Empty commits not visible in repo page

### ISSUE THREAD

**Issue by silverwind** [go-gitea/gitea#7188]
Empty commits created via `git commit --allow-empty -m "empty commit"` do not show up in the repo page in the commit box above the file list. Example:

[Repo](https://try.gitea.io/silverwind/symlink-test) (Not OK)
[Commit](https://try.gitea.io/silverwind/symlink-test/commit/8e2cf0bbd561b4328cabcfe91639a4f1166abe1c) (OK)
[Commits](https://try.gitea.io/silverwind/symlink-test/commits/branch/master) (OK)

**Comment by silverwind** [comment]
I think it applies to any commit with a message that does not render visible HTML. I did a XSS test via commit message, the commit is absent in the repo overview:

![image](https://user-images.githubusercontent.com/115237/61180955-4991ce00-a61f-11e9-9a75-461bbe70dd46.png)

**Comment by filipnavara** [comment]
I verified that GitHub shows these empty commits (https://github.com/filipnavara/test-maestro):

![image](https://user-images.githubusercontent.com/1764393/61527211-336b7f80-aa1c-11e9-98b8-e09b1bc31211.png)
