### ISSUE TITLE
[Error 1053] Can't run gitea as a Windows Service

### ISSUE THREAD

**Issue by benjaminforras** [go-gitea/gitea#7201]
- Gitea version (or commit ref): 10effb396 (and 2f39fc7bb)
- Git version: 1.8.2+3-g10effb396 (and 1.9.0+dev-347-g2f39fc7bb)
- Operating system: Windows 10 Pro build 17134
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

I can create the service however I can't start it. (It runs fine when I run the exe as an user application.)
`Error 1053: The service did not respond to the start or control request in a timely fashion`

## Screenshots

No screenshots because I can't really switch language in the os.

**Comment by philippbeckmann** [comment]
Is there something in the Windows event log?

**Comment by TryHardDood** [comment]
Yeah, just that it timed out after 30000ms

**Comment by philippbeckmann** [comment]
What about the user? Does he habe sufficient rights to read/write the folders and to open a network connection?

**Comment by TryHardDood** [comment]
Probably.
When I started the exe it worked. (And I tried to launch the service with my account but that didn't work either)

**Comment by philippbeckmann** [comment]
Can you post your app.ini (minus passwords and secrets)?

**Comment by TryHardDood** [comment]
Of course

```
APP_NAME = Gitea: Git with a cup of tea
RUN_USER = NB-DELL-009$
RUN_MODE = prod

[oauth2]
JWT_SECRET = [snip]

[security]
INTERNAL_TOKEN = [snip]
RUN_USER       = NB-DELL-009$
INSTALL_LOCK   = true
SECRET_KEY     = [snip]

[database]
DB_TYPE  = sqlite3
HOST     = 127.0.0.1:3306
NAME     = gitea
USER     = gitea
PASSWD   = 
SSL_MODE = disable
PATH     = C:/gitea/data/gitea.db

[repository]
ROOT = C:/gitea/gitea-repositories

[server]
SSH_DOMAIN       = localhost
DOMAIN           = localhost
HTTP_PORT        = 3000
ROOT_URL         = [snip]
DISABLE_SSH      = false
SSH_PORT         = 22
LFS_START_SERVER = true
LFS_CONTENT_PATH = C:/gitea/data/lfs
LFS_JWT_SECRET   = [snip]
OFFLINE_MODE     = false

[mailer]
ENABLED = false

[service]
REGISTER_EMAIL_CONFIRM            = false
ENABLE_NOTIFY_MAIL                = false
DISABLE_REGISTRATION              = false
ALLOW_ONLY_EXTERNAL_REGISTRATION  = false
ENABLE_CAPTCHA                    = false
REQUIRE_SIGNIN_VIEW               = false
DEFAULT_KEEP_EMAIL_PRIVATE        = false
DEFAULT_ALLOW_CREATE_ORGANIZATION = true
DEFAULT_ENABLE_TIMETRACKING       = true
NO_REPLY_ADDRESS                  = noreply.example.org

[picture]
DISABLE_GRAVATAR        = false
ENABLE_FEDERATED_AVATAR = true

[openid]
ENABLE_OPENID_SIGNIN = true
ENABLE_OPENID_SIGNUP = true

[session]
PROVIDER = file

[log]
MODE      = file
LEVEL     = Info
ROOT_PATH = C:/gitea/log
```

**Comment by MartinSGill** [comment]
Had this same issue. 
The problem was that git was not in path at the system level.

**Comment by maximedezette** [comment]
I had the same issue today, that's how I fixed it:

To see what is the actual error, open a cmd in gitea folder and type the following command:

`cmd /k gitea.exe `(to avoid the window from closing)

![gitea_error](https://user-images.githubusercontent.com/27780296/68684888-83d99080-0569-11ea-9ab2-cbb42299f81e.JPG)

In my case, I added git to the path.
Then I launched the .exe with the same command:

![gitea_error2](https://user-images.githubusercontent.com/27780296/68685041-c9965900-0569-11ea-9960-2035d108494f.JPG)

I still had the 1053 error when I launched the service at that point: 

![error_service_git](https://user-images.githubusercontent.com/27780296/68685163-fb0f2480-0569-11ea-8bba-11b712689d0a.JPG)

So I went to the Gitea's logs (gitea/log/gitea.log) and had an error:

![error_gitea3](https://user-images.githubusercontent.com/27780296/68685390-5a6d3480-056a-11ea-98e6-b17f82c0043e.JPG)

Then I just created the role 'gitea' wich was missing and it solved the problem!

Hope this helps :)

**Comment by PlusoneWang** [comment]
This issue actually not resolve yet. Could we re-open it?

> I had the same issue today, that's how I've fixed it:
> 
> To see the actual error, open a cmd in gitea folder and type the following command:
> 
> `cmd /k gitea.exe `(to avoid the window from closing)
> 
> ![gitea_error](https://user-images.githubusercontent.com/27780296/68684888-83d99080-0569-11ea-9ab2-cbb42299f81e.JPG)
> 
> In my case, I added git to the path.
> Then I launched the .exe with the same command:
> 
> ![gitea_error2](https://user-images.githubusercontent.com/27780296/68685041-c9965900-0569-11ea-9960-2035d108494f.JPG)
> 
> I still had the 1053 error when I launched the service at that point:
> 
> ![error_service_git](https://user-images.githubusercontent.com/27780296/68685163-fb0f2480-0569-11ea-8bba-11b712689d0a.JPG)
> 
> So I went to the Gitea's logs (gitea/log/gitea.log) and had an error:
> 
> ![error_gitea3](https://user-images.githubusercontent.com/27780296/68685390-5a6d3480-056a-11ea-98e6-b17f82c0043e.JPG)
> 
> Then I just created the role 'gitea' wich was missing and it solved the problem!
> 
> Hope this helps :)

Not work for me. There is no log file generated. The log folder is empty.

**Comment by PlusoneWang** [comment]
This issue is actually unresolved. Could we re-open it?
Appreciate for any help in advance.

**Comment by zeripath** [comment]
@PlusoneWang please open another issue - with more information on your specific configuration i.e. complete version of gitea, your path and a suitably sanitized app.ini.

So far the above issues have been due to configuration and not due to a bug.

**Comment by dyangrun** [comment]
> I had the same issue today, that's how I've fixed it:
> 
> To see the actual error, open a cmd in gitea folder and type the following command:
> 
> `cmd /k gitea.exe `(to avoid the window from closing)
> 
> ![gitea_error](https://user-images.githubusercontent.com/27780296/68684888-83d99080-0569-11ea-9ab2-cbb42299f81e.JPG)
> 
> In my case, I added git to the path.
> Then I launched the .exe with the same command:
> 
> ![gitea_error2](https://user-images.githubusercontent.com/27780296/68685041-c9965900-0569-11ea-9960-2035d108494f.JPG)
> 
> I still had the 1053 error when I launched the service at that point:
> 
> ![error_service_git](https://user-images.githubusercontent.com/27780296/68685163-fb0f2480-0569-11ea-8bba-11b712689d0a.JPG)
> 
> So I went to the Gitea's logs (gitea/log/gitea.log) and had an error:
> 
> ![error_gitea3](https://user-images.githubusercontent.com/27780296/68685390-5a6d3480-056a-11ea-98e6-b17f82c0043e.JPG)
> 
> Then I just created the role 'gitea' wich was missing and it solved the problem!
> 
> Hope this helps :)

和我的状况一样，是因为windows server 没有安装 git，所以 gitea无法在path中找到git的执行程序，添加上之后就好了

same iusse,need install git,and add git path to system environment variables
