### ISSUE TITLE
Webhook x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by boukandouramhamed** [go-gitea/gitea#7203]
- Gitea version (or commit ref): 1.9.0+dev-311-gfb4438a81 
- Git version: 2.20.1
- Operating system: Centos 7 
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

Unable to add webhook for openshift origin pipeline (3.11). 

> Delivery: Post https://ip@:8443/apis/build.openshift.io/v1/namespaces/jenkins/buildconfigs/pipeline6/webhooks/somesecret/generic: x509: certificate signed by unknown authority

How can i use self signed webhooks in gitea ?

**Comment by langemar** [comment]
A similar issue was tracked by #2744 but the given solution is not suitable in an openshift/k8s environment. I'm seeking for a solution since a while in order to use openshift's oauth2/openID provider in gitea.

Grepping through the source code i even can't find where the trust-store might be initialised.

best regards

**Comment by lunny** [comment]
We should add a config on `[webhook]` to allow self-signed webhooks.

**Comment by langemar** [comment]
A more general option would be great to address not only webhooks.
As said I try to integrate gitea in openshift and want gitea to use the openID endpoint provided by openshift, which is accessible through tls endpoint secured by a cluster wide certificate.

The same is also true for every connection gitea make to external resources. This would include databases, indexers, auth providers (OpenID/OAuth2, LDAP and SMTP), webhooks (of coursce), Mailer, Cache (redis with TLS), Picture, log (at least smtp logs) and U2F.

Best regards

**Comment by nils91** [comment]
I had a similar problem installing a webhook to an jenkins instance using a selfsigned certificate. Adding the certificate (from jenkins) to the systems ca´s, which under ubuntu are in /etc/ssl/certs/ca-certificates.crt, solved the problem.

Best regards

**Comment by damobrisbane** [comment]
My workaround for cert not being available (docker) was to create and tag a new image with cert copied in, ie:

`
cat Dockerfile

FROM gitea:v0.2
COPY MYLOCALCACERT.crt /etc/ssl/certs
...
docker build -t gitea:v0.2-custcert .
`

Though I havde no idea what might be best practice around properly addressing this.

**Comment by langemar** [comment]
Hi damobrisbane,

openshift provides an operator to maintaine service certificates, there rolled automatically. So it is unpractical to rebuild the container once the operator did his job (requires additional monitoring and manuel work to trigger builds).

These certificates are used for cluster internal communication only and it is advised not to use external verifieable certificate root, see for example [this blog](https://www.openshift.com/blog/considerations-on-openshift-pkis-and-certificates).
For the outer world ocp routes (ingest proxy) can do a reencrypt using a custom certificate at the edge.

A proper solution would be to have a config line or hardcoded path where certificates can be placed and included as trust anchor on container start. Even better would be if the application monitors a path/configmap for additional certificates, but a container restart normally happens often enough to be safe with a start up solution.

best regards

**Comment by lunny** [comment]
Have you tried
```ini
[webhook]
; Allow insecure certification
SKIP_TLS_VERIFY = true
```
