### ISSUE TITLE
Endpoint /login/oauth/access_token doesn't return Access-Control-Allow-Methods

### ISSUE THREAD

**Issue by esfraner** [go-gitea/gitea#7204]
- Gitea version (or commit ref): bd55f6ff
- Git version: 2.11.0
- Operating system:  Linux debian
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x ] Not relevant
- Log gist:

## Description
Endpoint /login/oauth/access_token doesn't return Access-Control-Allow-Methods and give me CORS problem.
...

## Screenshots
![Screenshot_20190614_130928](https://user-images.githubusercontent.com/22304628/59505597-26e88a00-8ea6-11e9-9651-8f53aa1b0a86.png)

....

![Screenshot_20190614_1259032222](https://user-images.githubusercontent.com/22304628/59505062-a5442c80-8ea4-11e9-9982-3c58b112626a.png)

**Comment by zeripath** [comment]
What should it return exactly?

**Comment by esfraner** [comment]
@zeripath, it returns: `Access to fetch at 'https://git.[URL]/login/oauth/access_token' from origin 'http://localhost:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

**Comment by esfraner** [comment]
As you can see, in this GET method, appears `Access-Control-Request-Method` with its method: 
(No problem with the error 403, I only have to make a test OPTIONS request to show).

![Screenshot_20190615_010914](https://user-images.githubusercontent.com/22304628/59543473-b8d6ae00-8f0b-11e9-955e-da472e6301f3.png)


Then the request that I did to endpoint `/login/oauth/access_token` should have this header.

**Comment by sebastianwindeck** [comment]
Is this issue solved? 
I tried to access the endpoint from another resource for dev purpose 
with `[cors]` enabled. I would like to enable cors for the endpoint:
`/login/oauth/access_token`.

How can I enable gitea in the config file `app.ini` to set the header:

        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';

**Comment by zeripath** [comment]
Hmm

I think we might need a block like

https://github.com/go-gitea/gitea/blob/a3cc842e15eb5ed42c3125410d9c774314a286a5/routers/api/v1/api.go#L556-L563

For those Auth routes 

https://github.com/go-gitea/gitea/blob/73a093d60f6f09d2f8688585dc45198d1ec507ca/routers/routes/web.go#L385-L391

It will need a little bit of thought to know which need it.

**Comment by zeripath** [comment]
@esfraner @sebastianwindeck  Would you be able to try #14850 to see if that fixes your issue?
