### ISSUE TITLE
mirrored repositories do not carry over issues/PRs data

### ISSUE THREAD

**Issue by bryanpedini** [go-gitea/gitea#7217]
- Gitea version (copied from try.gitea.io): 1.9.0+dev-353-gcf2221e3a
- Git version: IDK what u use there..
- Operating system: IDK either
- Database: IDK either
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL): https://try.gitea.io/bryanpedini/gitea/issues/7196
  - [ ] No
  - [ ] Not relevant
- Log gist: _!?_

## Description
I don't know if this is intentional / a real "feature", but when mirroring a repository the data concerning issues / PRs do not carry over to the mirror, which, being a mirror should mirror everything (right?).

Title / bug could totally be the inverse, being that this is a feature and the real bug is on the commit screen.
Better explaination: I notices this on the ZXQ Labs Gitea server of @thehowl (an in real life friend of mine), where he mirrored a videogame repo, and by going into the commit history everything seems clean (# are not links, because Gitea understands that there isn't a issue page under that: [proof](https://try.gitea.io/bryanpedini/gitea/commits/branch/master)), however by going into the page of the single commit, magically that becomes a link, not of the remote (mirrored) server (say for example GitHub), but of the local mirror, which of course has no single issue / PR related page: as you can view [here](https://try.gitea.io/bryanpedini/gitea/commit/cf2221e3acce4d2c88c09976557ce3e73068baaf).

Three different very acceptable solutions would be
- to remove the link from the single commit page ([this one](https://try.gitea.io/bryanpedini/gitea/commit/cf2221e3acce4d2c88c09976557ce3e73068baaf))
- to REGEX the original URL of the mirror and link the issue to the "original" server (the one from which you mirror), but then it would be nice to include the same feature in the commit history too ([here](https://try.gitea.io/bryanpedini/gitea/commits/branch/master))
- less practicable but most "complete": build and integrate with the existing syncronization framework, the sync that is needed to fetch issues / PRs data alongside code, commits and branches

**Comment by Bryanpedini** [comment]
Hook me or @thehowl up (if he is willing and not busy / lazy with anything else) to try to help up with the code if ever needed!

**Comment by bryanpedini** [comment]
Any update yet?
It could have been useful when you migrated some Gitea modules on Gitea too...

Thanks in advance.

**Comment by lafriks** [comment]
Migration does support issues and PR. For mirrors it would be hard to sync issues and PR all the time as that would require scanning all issues and PR all the time for changes

**Comment by bryanpedini** [comment]
Isn't there an API endpoint to issue a scan of a repo, only beginning at a cerain offset?
Like the machine language for "get me all issues after ID 701" or something like that?

**Comment by lafriks** [comment]
But PR can be closed/repoened/commented etc, so you can't just check for new ones

**Comment by bryanpedini** [comment]
That's right... Fair enough...
But come on; it's GitHub, it HAS to have an endpoint that accepts things like "only changed" or "only new" as request parameters...
Am I wrong here?

**Comment by lafriks** [comment]
I don't think there is

**Comment by bryanpedini** [comment]
Damn it...
Close the issue then if there is nothing doable here, it would have been nice, but whatever - we can totally live without

**Comment by bryanpedini** [comment]
Thanks for your time at least.
Great to see support from the devs
