### ISSUE TITLE
mentioning users dropdown during message composition

### ISSUE THREAD

**Issue by bryanpedini** [go-gitea/gitea#7218]
- Gitea version (or commit ref): try.gitea.io (1.9.0+dev-353-gcf2221e3a)
- Git version: IDK
- Operating system: IDK
- Database (use `[x]`): IDK
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (URL not relevant)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
Try to mention somebody in this issue, try to mention me, a dropdown that helps you autocomplete appears;
Try to do the same thing on a Gitea hosted server, let's hope you remember the exact username...

**Comment by Bryanpedini** [comment]
This is actually more a "feature request" than a bug, but whatever...

PS: yes, I find it funny and entertaining into discovering bugs of open source programs whenever I have spare time to;
'cause who knows, maybe I'm helping getting that software better..

**Comment by lunny** [comment]
Sorry, I don't know what did you mean.

**Comment by Bryanpedini** [comment]
> 
> 
> Sorry, I don't know what did you mean.

this helpful dropdown that autocompletes mentions:
![dropdown](https://user-images.githubusercontent.com/45012292/59564489-c3965d80-9047-11e9-82f2-369e5cb59a2c.PNG)

**Comment by lunny** [comment]
I don't know which version you are using.

<img width="1430" alt="Jietu20190616-220709" src="https://user-images.githubusercontent.com/81045/59565230-2b1dce80-9083-11e9-9c55-ac90ba65e73f.png">

**Comment by Bryanpedini** [comment]
Oh, sorry... 1.7.5
Is that "feature" already implemented on newers? I created the issue just 'cause I didn't see any opened / closed issue on this topic so thought even on new releases it wasn't present...

**Comment by lunny** [comment]
@Bryanpedini yes, it has been implemented. You can always try the new feature on https://try.gitea.io

**Comment by Bryanpedini** [comment]
Is it enabled on current latest 1.8.2?
If it is, could you please take a look on #7216 to check if an update/upgrade could help, 'cause I'm currently waiting to upgrade my instace for that issue...

**Comment by Bryanpedini** [comment]
Also...

> @Bryanpedini yes, it has been implemented. You can always try the new feature on https://try.gitea.io

I did that here https://try.gitea.io/niaoked/test/issues/1 'cause was the first repo to come up under "explore".. but did dropdown didn't come up there on gitea try instance...

**Comment by lunny** [comment]
You cannot mention anyone you want currently, just the people your team members.

**Comment by Bryanpedini** [comment]
Aaaah, I see...
Could it then be a next feature like here in GitHub? (maybe?)

**Comment by lunny** [comment]
@Bryanpedini I think we can, but we need a better performance method to do that. Currently just find the people via database.

**Comment by Bryanpedini** [comment]
Maybe searching people in the database but just those people that have contributed at least once on the repository you are currently mentioning users in PRs or issues;
Or people that you currently have mentioned in the past;
Or that you have added at least once in any of your repositories;

Or any combination of those (caching would be nice too like in a temporary table or a view...)
(if it is possible, IDK..)

**Comment by lunny** [comment]
Yeah. It's possible. Need some PRs from some people. :)

**Comment by Bryanpedini** [comment]
Hahaha... yeah...

Hook me up if you need any help / idea (not practic with Golang but could figure out the logic, IDK)...
(maybe assign 1.x.x and kind/feature?)

**Comment by Worthy7** [comment]
This can be closed btw, the specified functionality is already there. (It's not perfect, but that's another issue)
