### ISSUE TITLE
LFS and deploy key: Authorization error on private repos

### ISSUE THREAD

**Issue by jonas-hagen** [go-gitea/gitea#7227]
- Gitea version: 1.8.2
- Git version: 2.19
- Operating system: Alpine (Server), Ubuntu (Client)
- Database: SQLite
- Setup: nginx as reverse proxy, OpenSSH server

## Description

LFS content can't be read from _private_  repos via SSH using a deploy key. On public repos, this works (presumably since pull request #5939 as mentioned in #6127).

gitea.log:
`2019/06/17 07:17:07 [D] LFS request - Method: POST, URL: /user/test.git/info/lfs/objects/batch, Status 401`

Possibly related: #7219.

**Comment by zeripath** [comment]
This is definitely a duplicate of #5478 and presumably of #7219  - and would definitely be fixed by #7224.

**Comment by zeripath** [comment]
Fix should be in next release of 1.8 - this was fixed in 1.9 since #6993

**Comment by jonas-hagen** [comment]
Thanks!
