### ISSUE TITLE
Web Services API for Organisations Returns Empty JSON Object

### ISSUE THREAD

**Issue by netlander** [go-gitea/gitea#7232]
- Gitea version (or commit ref): 1.8.1
- Git version: Not sure
- Operating system: Ubuntu Server 16.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

When using the swagger generated WebServices API to access the installation there is one end point that returns an empty JSON object.

Other end points such as for fetching users work as intended but haven't tested many end points yet.

This could be a bug or am I missing something?

## Screenshots

![image](https://user-images.githubusercontent.com/4721044/59626892-e9e5f700-9134-11e9-9591-8274d3e704ea.png)

**Comment by techknowlogick** [comment]
can the user whose token you are using access the admin portal?

**Comment by netlander** [comment]
Yes they can, it's the admin themselves.

**Comment by netlander** [comment]
No one on the dev team bothered give an answer one way or the other. This does not reflect well on the project as a whole. Maybe a return to GOGS is in order.

**Comment by guillep2k** [comment]
Just to get more info.... have you tried using the example `curl` command that appears in the swagger interface? I must be surely doing something wrong, but even if I go and use the `Authorize` button top-right of the page, I get `401 Unauthorized`. However, if I use the `curl` command that appears right below the test section as an example (copy-pasted) it worked correctly:

```
$ curl -X GET "https://____my_site_____/api/v1/admin/orgs" -H  "accept: application/json" -H  "authorization: Basic xxxxx_base64_value_xxxxxx"
[{"id":6,"username":"MyOrg","full_name":"My Organization","avatar_url":"https://____my_site_____/avatars/7a25c586044ba7e85e47b73326421f2e","description":"","website":"http://____my_site_____/","location":"My City","visibility":"public"}]
```

Also, adding -v to the `curl` command will help you diagnose the problem. At least you'll get the headers back and see if it's indeed an empty response (e.g. `HTTP/1.1 200 OK`, `Content-Length: 0`) or another error.
