### ISSUE TITLE
While open repository it gives 500, It working fine before 

### ISSUE THREAD

**Issue by ronaksatva** [go-gitea/gitea#7235]
- Gitea version (or commit ref): 1.8.2
- Git version: 2.17.1
- Operating system: Ubantu 15.x
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:
No log is generated in log folder.
## Description
I have host in my local network and suddenly it start giving 500 erros in few repository. So i can't able to push and pull it.  Other repository is working fine but few repository have this issues. And I check the log folder also but there is no log generated. 
...

## Screenshots
![gitea](https://user-images.githubusercontent.com/44358077/59654737-340ebd00-91b5-11e9-8828-c84ad141b87b.png)

But I have 4 notice under the administrator section for one of the repository which stops working.

![gitea1](https://user-images.githubusercontent.com/44358077/59654984-463d2b00-91b6-11e9-8fdc-dbaf3550020a.png)

Below is the details which i get from this system notice section.
Failed to health check repository (/mnt/Data/git/gitea-repositories/projects/XXX.git): exit status 3 - error: unable to mmap ./objects/11/dd8cab3a673cc1741e9e4c8ad3bb494a0e1e90: Input/output error error: 11dd8cab3a673cc1741e9e4c8ad3bb494a0e1e90: object corrupt or missing: ./objects/11/dd8cab3a673cc1741e9e4c8ad3bb494a0e1e90 error: inflate: data stream error (unknown compression method) error: unable to unpack header of ./objects/14/85255a99d83791ad71f70e70ff746c620537a4 error: 1485255a99d83791ad71f70e70ff746c620537a4: object corrupt or missing: ./objects/14/85255a99d83791ad71f70e70ff746c620537a4 error: inflate: data stream error (incorrect header check) error: unable to unpack header of ./objects/1b/fb49c59893c5239c6721afd655bb5741ca5e8f error: 1bfb49c59893c5239c6721afd655bb5741ca5e8f: object corrupt or missing: ./objects/1b/fb49c59893c5239c6721afd655bb5741ca5e8f error: inflate: data stream error (unknown compression method) error: unable to unpack header of ./objects/1d/e3eab8b96eab9eab01ba325bfe3c972ac30d2e error: 1de3eab8b96eab9eab01ba325bfe3c972ac30d2e: object corrupt or missing: ./objects/1d/e3eab8b96eab9eab01ba325bfe3c972ac30d2e error: inflate: data stream error (unknown compression method) error: unable to unpack header of ./objects/2f/c23fc5bbb84b9a770299b46a1565278bf2b40d error: 2fc23fc5bbb84b9a770299b46a1565278bf2b40d: object corrupt or missing: ./objects/2f/c23fc5bbb84b9a770299b46a1565278bf2b40d error: garbage at end of loose object '4f34ee72ae65c0c38a5ab50eeb849cf98dece3e7' error: unable to unpack contents of ./objects/4f/34ee72ae65c0c38a5ab50eeb849cf98dece3e7 error: 4f34ee72ae65c0c38a5ab50eeb849cf98dece3e7: object corrupt or missing: ./objects/4f/34ee72ae65c0c38a5ab50eeb849cf98dece3e7 error: inflate: data stream error (incorrect header check) error: unable to unpack header of ./objects/69/1cd1830d2800ac56e76bb4a59b1bd18bebaeba error: 691cd1830d2800ac56e76bb4a59b1bd18bebaeba: object corrupt or missing: ./objects/69/1cd1830d2800ac56e76bb4a59b1bd18bebaeba error: garbage at end of loose object '73216797ff6383aabebb62c7ed0df67768e126ac' error: unable to unpack contents of ./objects/73/216797ff6383aabebb62c7ed0df67768e126ac error: 73216797ff6383aabebb62c7ed0df67768e126ac: object corrupt or missing: ./objects/73/216797ff6383aabebb62c7ed0df67768e126ac error: inflate: data stream error (incorrect header check) error: unable to unpack header of ./objects/74/6ff9208a29473f4df4c783d34f9e7525620b5f error: 746ff9208a29473f4df4c783d34f9e7525620b5f: object corrupt or missing: ./objects/74/6ff9208a29473f4df4c783d34f9e7525620b5f error: corrupt loose object '76f614efb4c08929f9cb400dc9893d0e7693240c' error: unable to unpack contents of ./objects/76/f614efb4c08929f9cb400dc9893d0e7693240c error: 76f614efb4c08929f9cb400dc9893d0e7693240c: object corrupt or missing: ./objects/76/f614efb4c08929f9cb400dc9893d0e7693240c error: inflate: data stream error (incorrect header check) error: unable to unpack header of ./objects/7c/9841d166981089472eb505bc13d870e8134faf error: 7c9841d166981089472eb505bc13d870e8134faf: object corrupt or missing: ./objects/7c/9841d166981089472eb505bc13d870e8134faf error: corrupt loose object '831a7b7b6cc417499266880db689ca6dc7c185fc' error: unable to unpack contents of ./objects/83/1a7b7b6cc417499266880db689ca6dc7c185fc error: 831a7b7b6cc417499266880db689ca6dc7c185fc: object corrupt or missing: ./objects/83/1a7b7b6cc417499266880db689ca6dc7c185fc error: inflate: data stream error (incorrect header check) error: unable to unpack header of ./objects/89/403efd841c7530ac6073248967b82c1dc7f53d error: 89403efd841c7530ac6073248967b82c1dc7f53d: object corrupt or missing: ./objects/89/403efd841c7530ac6073248967b82c1dc7f53d error: inflate: data stream error (incorrect header check) error: unable to unpack header of ./objects/95/49541ebb5bf46c0b6ad95a4c302c1dabed5f56 error: 9549541ebb5bf46c0b6ad95a4c302c1dabed5f56: object corrupt or missing: ./objects/95/49541ebb5bf46c0b6ad95a4c302c1dabed5f56 error: garbage at end of loose object '9ea96b5c592cbb8eb198546c7e480fe30bf057ea' error: unable to unpack contents of ./objects/9e/a96b5c592cbb8eb198546c7e480fe30bf057ea error: 9ea96b5c592cbb8eb198546c7e480fe30bf057ea: object corrupt or missing: ./objects/9e/a96b5c592cbb8eb198546c7e480fe30bf057ea error: inflate: data stream error (incorrect header check) error: unable to unpack header of ./objects/a8/beca1c475d92930f3240264130c6a4916e9290 error: a8beca1c475d92930f3240264130c6a4916e9290: object corrupt or missing: ./objects/a8/beca1c475d92930f3240264130c6a4916e9290 error: inflate: data stream error (incorrect header check) error: unable to unpack header of ./objects/b4/14f663152a02fc0a8afd20557b316fd9b98dc1 error: b414f663152a02fc0a8afd20557b316fd9b98dc1: object corrupt or missing: ./objects/b4/14f663152a02fc0a8afd20557b316fd9b98dc1 error: corrupt loose object 'c13817bec1941b398b39f1b0bbf74026ceca3287' error: unable to unpack contents of ./objects/c1/3817bec1941b398b39f1b0bbf74026ceca3287 error: c13817bec1941b398b39f1b0bbf74026ceca3287: object corrupt or missing: ./objects/c1/3817bec1941b398b39f1b0bbf74026ceca3287 error: inflate: data stream error (incorrect header check) error: unable to unpack header of ./objects/c5/febf377781cbb9d4afbf2973bad6fd2c22b4f6 error: c5febf377781cbb9d4afbf2973bad6fd2c22b4f6: object corrupt or missing: ./objects/c5/febf377781cbb9d4afbf2973bad6fd2c22b4f6 error: inflate: data stream error (incorrect header check) error: unable to unpack header of ./objects/c7/81638d397155dee67734f706b82439ff54be0c error: c781638d397155dee67734f706b82439ff54be0c: object corrupt or missing: ./objects/c7/81638d397155dee67734f706b82439ff54be0c error: inflate: data stream error (incorrect header check) error: unable to unpack header of ./objects/ce/48133aa571349632e9ed1b752ca6d9d4ceedd7 error: ce48133aa571349632e9ed1b752ca6d9d4ceedd7: object corrupt or missing: ./objects/ce/48133aa571349632e9ed1b752ca6d9d4ceedd7 error: unable to mmap ./objects/cf/b4e82588b653bf4675bcbbf306f9d7f0afa9be: Input/output error error: cfb4e82588b653bf4675bcbbf306f9d7f0afa9be: object corrupt or missing: ./objects/cf/b4e82588b653bf4675bcbbf306f9d7f0afa9be error: inflate: data stream error (incorrect header check) error: unable to unpack header of ./objects/d2/803dd2c2f0300042925ce417186d274de0be53 error: d2803dd2c2f0300042925ce417186d274de0be53: object corrupt or missing: ./objects/d2/803dd2c2f0300042925ce417186d274de0be53 error: garbage at end of loose object 'efc1d315ad895b3476c3436d4a4956b7a300decb' error: unable to unpack contents of ./objects/ef/c1d315ad895b3476c3436d4a4956b7a300decb error: efc1d315ad895b3476c3436d4a4956b7a300decb: object corrupt or missing: ./objects/ef/c1d315ad895b3476c3436d4a4956b7a300decb error: garbage at end of loose object 'f10617a6fbef03be2516e41cb37667cc3316e5a9' error: unable to unpack contents of ./objects/f1/0617a6fbef03be2516e41cb37667cc3316e5a9 error: f10617a6fbef03be2516e41cb37667cc3316e5a9: object corrupt or missing: ./objects/f1/0617a6fbef03be2516e41cb37667cc3316e5a9 error: inflate: data stream error (incorrect header check) error: unable to unpack header of ./objects/fe/bc8ad1cc473fa4d90b16a86ca5b3113688b454 error: febc8ad1cc473fa4d90b16a86ca5b3113688b454: object corrupt or missing: ./objects/fe/bc8ad1cc473fa4d90b16a86ca5b3113688b454

Please help me out to solve this issue.

**Comment by zeripath** [comment]
Something horrible has happened to that repository and it looks very corrupted.

You probably need to drop to command line and do a git gc on the repository itself.

Was there a power outage or crash of Gitea whilst you were pushing? Is there anything illuminating in the logs earlier than this?

**Comment by ronaksatva** [comment]
> Something horrible has happened to that repository and it looks very corrupted.
> 
> You probably need to drop to command line and do a git gc on the repository itself.
> 
> Was there a power outage or crash of Gitea whilst you were pushing? Is there anything illuminating in the logs earlier than this?

I don't know is there any power outage or OS crash. But yesterday it was running good. Even I have more repository which give me 500 hundred error but there is no log for that.

**Comment by raisr** [comment]
I had a similar issue today. I migrated some repos to a new  gitea installation (Windows). Everything worked fine. I could access all repos (gui, git clone ,etc.). After 2 hours every repo showed a 500 error on the web ui. 

The logs contained lots of this error: 

019/07/10 23:26:07 [...ules/context/repo.go:581 func1()] [E] GetBranchCommit: exit status 128 - fatal: git show-ref: bad ref refs/heads/master

I gave the repo health check a try (http://.../admin?op=9). This finally produced system notices that helped me.

" error: unable to mmap ./objects/11/2b81036aef610e4f00bf4e0b616d2d4fc57e72: Permission denied"

The user running gitea had no write / modify permission on the repos folder. After updating the permissions everything worked fine. 

Maybe the admin dashboard shoud have an additional maintenance operation: Check Permissions.  Or a least check the permissions during the initial setup.

Cheers

**Comment by ronaksatva** [comment]
Does anyone get the solution for that? how to recover from it without deleting the whole repo and creating a new one

I got the below error for some other repo now.

Failed to health check repository (/mnt/Data/git/gitea-repositories/XXX/XXXXXX.git): exit status 3 - error: inflate: data stream error (incorrect header check) error: unable to unpack header of ./objects/32/bef97824e32705266cfadfdd0ce5c9add6c72c error: 32bef97824e32705266cfadfdd0ce5c9add6c72c: object corrupt or missing: ./objects/32/bef97824e32705266cfadfdd0ce5c9add6c72c error: inflate: data stream error (incorrect header check) error: unable to unpack header of ./objects/4b/46295fd66a3d963f0c0d0a84081170746049d9 error: 4b46295fd66a3d963f0c0d0a84081170746049d9: object corrupt or missing: ./objects/4b/46295fd66a3d963f0c0d0a84081170746049d9

**Comment by lunny** [comment]
@ronaksatva I think most probably it's file system permissions problem. Just as workaround of @raisr 's problem. Could you check that?
