### ISSUE TITLE
Incorrect time to display uploaded files

### ISSUE THREAD

**Issue by lw2590** [go-gitea/gitea#7239]
- Gitea version (or commit ref):1.8.3
- Git version:2.21.0
- Operating system:CentOS 7.4 x64
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description
The display time of uploading project files through gitea is incorrect. After 14 hours of uploading, please analyze the reasons. Thank you.
...
![image](https://user-images.githubusercontent.com/15713296/59671348-1579e780-91f0-11e9-8c4a-86067845b55e.png)

**Comment by lafriks** [comment]
Could it be that server time is not correct?

**Comment by 1902sysad** [comment]
I am facing the same issue. when I push files via ssh git or http git the date/time issue doesnt' appear for that file but when it is uploaded/edited/created on the gitea web interfaces it show the error. 

In the "action" table it seems the timestamp is advance of 12 hours. 

I checked also my timezone and my server's timezone they are the same. I cloned the repository and it seems the file have correct datetime.

**Comment by lw2590** [comment]
Okay, I'll try it your way. Thank you.




------------------ 原始邮件 ------------------
发件人: "1902sysad"<notifications@github.com>;
发送时间: 2019年7月5日(星期五) 下午5:56
收件人: "go-gitea/gitea"<gitea@noreply.github.com>;
抄送: "刘维国"<lw2590@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [go-gitea/gitea] Incorrect time to display uploaded files (#7239)




I am facing the same issue. when I push files via ssh git or http git the date/time issue doesnt' appear for that file but when it is uploaded/edited/created on the gitea web interfaces it show the error.
 
In the "action" table it seems the timestamp is advance of 12 hours.
 
I checked also my timezone and my server's timezone they are the same. I cloned the repository and it seems the file have correct datetime.

**Comment by lunny** [comment]
Could you confirm #7792 fix this one? I cannot reproduce this on my local.
