### ISSUE TITLE
Multiple merges in single commit breaks commit graph

### ISSUE THREAD

**Issue by eightfingers89** [go-gitea/gitea#7247]
- Gitea version (or commit ref): 1.7.6
- Git version: 
- Operating system: Centos
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X] No
  - [ ] Not relevant
- Log gist:

## Description

When more that one branch is merged as part of a single commit, the text output of "git log --graph" appears something like the following:
`* | | b9783c0c2 `
`* | | c6c684cd7 `
`| | *-------.   f91f7549e  Interesting commit`
`| | |\ \ \ \ \`
`| | | | | | | * 57759c11a `
`| | | | | | | * 9f1924f08  `

The parsing of the graph in public/vendor/plugins/gitgraph/gitgraph.js does not handle the "-" characters properly, resulting in an error that prevents display of commits subsequent to the line with the merge.

At line 391, changing:
`					color = flows[colomnIndex].color;`
to:
`				if (colomn === "-") {`
`					currentRow.splice(colomnIndex + 1, 1);`
`					color = flows[colomnIndex+1].color;`
`				}`
`				else {`
`					color = flows[colomnIndex].color;`
`				}`
Corrects the display, in our repository, but I am unsure of any side effects, particularly with the flows array.

**Comment by lafriks** [comment]
it should probably needs to be tested with latest gitgraph.js and if still not working reported upstream

**Comment by eightfingers89** [comment]
I originally tested with a copy of gitgraph.js after the the fix for #3382 so I will open one under bluef/gitgraph.js
