### ISSUE TITLE
Update go-git dependency to get performance fixes

### ISSUE THREAD

**Issue by filipnavara** [go-gitea/gitea#7248]
Go-git 4.12 (https://github.com/src-d/go-git/releases/tag/v4.12.0) was released now so Gitea should pick it up for the performance improvements.

**Comment by filipnavara** [comment]
Unfortunately the new commitgraph packages are still missing after the update (the plumbing/format/commitgraph and plumbing/object/commitgraph directories).

**Comment by zeripath** [comment]
Oh that's odd they should be there - try make vendor and see if they appear and were missed in the commit.

**Comment by filipnavara** [comment]
I cannot see them on GitHub web (for Gitea repo) so they must have been missed somewhere along the way. `make vendor` makes a mess on my Windows machine which is why I always ask others to do it for me.

**Comment by zeripath** [comment]
Ok they definitely should be there - but they're missing because git doesn't complain about new untracked directories. So our make vendor test will miss that they weren't added.

Could you open an issue and either myself or someone else will be able to fix the missing vendor files.

(What happens when you run make vendor?)

**Comment by lunny** [comment]
So is this a bug of `go`?

**Comment by lunny** [comment]
It seems `plumbing/format/commitgraph` and `plumbing/object/commitgraph` have never been referenced by other packages on go-git. Is that the reason the directories missing when vendoring?

**Comment by zeripath** [comment]
Nope I suspect the files get added when we do make vendor, but that we missed them when creating the pr and our make test-vendor case misses the fact that they're not added. 

I suspect these commit graph functions are not used anywhere in go git at present so it doesn't cause compilation issues that they're not present.

**Comment by lunny** [comment]
@zeripath I have executed `make vendor` locally again. But it also didn't copy that two directories.

**Comment by zeripath** [comment]
So just checking quickly it doesn't appear to be fixed using make vendor. Damn.

**Comment by sapk** [comment]
@filipnavara I forced the vendoring of package by using _ import of commitgraph packages. You can cherry-pick this commit ac4ebacf17409f42ef7456959ac64ea11679040e to have the needed deps vendored. Let me know if you need more deps.

**Comment by filipnavara** [comment]
@sapk Thanks! That's exactly what I needed.

**Comment by lunny** [comment]
@filipnavara @sapk So I think that #7276 is unnecessary. 
@filipnavara  You can just send a PR which reference the two directories and if you cannot run `make vendor` correctly, maintainers could help you with `make vendor` on that PR.

**Comment by sapk** [comment]
Yes @lunny it doesn't need to be merged (and it shouldn't). I just did it to verify that it only vendor referenced folder and it could ease the process of vendor for @filipnavara by just cherry-picking the commit (and removing _ import).

**Comment by zeripath** [comment]
This is an interesting finding for me - it basically means that's whilst developing there may be more useful functionality in our already vendored packages that we could use but don't know that is there - I did wonder why go-git appeared so sparse when I was looking for functionality. I'll have to have another look at it.
