### ISSUE TITLE
strk.kbt.io/git/go-libravatar is unstable for CI build

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#7251]
I encountered that go cannot access that library, see https://drone.gitea.io/go-gitea/gitea/10000/1/9 .

**Comment by lunny** [comment]
@strk If you don't want to store it on github, maybe you can move it to https://gitea.com

**Comment by philippbeckmann** [comment]
https://strk.kbt.io/projects/go/libravatar/index.html mentions a mirror on gitlab: https://gitlab.com/strk/go-libravatar

**Comment by strk** [comment]
Must have been a glitch, works now, right ?
GitHub can also be unstable, as well as gitlab.com or gitea.com.
The good thing about go is that it clones repos.
Continuously taking a fresh clone is just a silly thing modern CI do way too often.
How about using a docker image with a pre-cloned snapshot ?
