### ISSUE TITLE
Windows server 2008 R2 can‘t install gitea

### ISSUE THREAD

**Issue by Hem0o** [go-gitea/gitea#7252]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

...

**Comment by Hem0o** [comment]
Open gitea-1.8.3-windows-4.0-amd64.exe ，but it closes immediately.

**Comment by otbutz** [comment]
Are you absolutely sure that you're running Windows Server 2008 **R2**?

Go 1.11 dropped support for Windows Server 2008 and requires at least 2008R2. [source](https://github.com/golang/go/wiki/MinimumRequirements#windows)

BTW:

> On January 14, 2020, support for Windows Server 2008 and 2008 R2 will end.

You should probably look for a different OS (version) anyway.

**Comment by lunny** [comment]
Please run gitea on command line and give more details.

**Comment by Hem0o** [comment]
> Please run gitea on command line and give more details.

```
 panic: Git not found: exec: "git": executable file not found in %PATH%

goroutine 1 [running]:
code.gitea.io/gitea/modules/git.init.0()
        /go/src/code.gitea.io/gitea/modules/git/git.go:83 +0xe4f
```


**Is it necessary to install git first?**

**Comment by Hem0o** [comment]
> Are you absolutely sure that you're running Windows Server 2008 **R2**?
> 
> Go 1.11 dropped support for Windows Server 2008 and requires at least 2008R2. [source](https://github.com/golang/go/wiki/MinimumRequirements#windows)
> 
> BTW:
> 
> > On January 14, 2020, support for Windows Server 2008 and 2008 R2 will end.
> 
> You should probably look for a different OS (version) anyway.

Thank you!

**Comment by Cherrg** [comment]
> > Please run gitea on command line and give more details.
> 
> ```
>  panic: Git not found: exec: "git": executable file not found in %PATH%
> 
> goroutine 1 [running]:
> code.gitea.io/gitea/modules/git.init.0()
>         /go/src/code.gitea.io/gitea/modules/git/git.go:83 +0xe4f
> ```
> 
> **Is it necessary to install git first?**

Yeah git need to be installed on your system. May you have to restart your system or/and manually add the path to environment variables. 
(Is old, but may still works: https://stackoverflow.com/questions/26620312/installing-git-in-path-with-github-client-for-windows)

**Comment by Cherrg** [comment]
Until you got gitea running i would recomment to always run from command line: `gitea.exe web` (may with additional parameters) to see error messages. If gitea runs you could set a log path in app.ini.

If all is running well you could also configure as system service to run gitea. Take a look in gitea docs:
https://docs.gitea.io/en-us/windows-service/

**Comment by Hem0o** [comment]
> > > Please run gitea on command line and give more details.
> > 
> > 
> > ```
> >  panic: Git not found: exec: "git": executable file not found in %PATH%
> > 
> > goroutine 1 [running]:
> > code.gitea.io/gitea/modules/git.init.0()
> >         /go/src/code.gitea.io/gitea/modules/git/git.go:83 +0xe4f
> > ```
> > 
> > 
> > **Is it necessary to install git first?**
> 
> Yeah git need to be installed on your system. May you have to restart your system or/and manually add the path to environment variables.
> (It's old, but may still works: https://stackoverflow.com/questions/26620312/installing-git-in-path-with-github-client-for-windows)

I get it.Thank you very much!

**Comment by gsantner** [comment]
@lunny 
guess this can be closed
