### ISSUE TITLE
"Corrupted Content Error" in Firefox 67.0.2

### ISSUE THREAD

**Issue by memost** [go-gitea/gitea#7259]
Gitea version 1.7.0 built with: bindata, sqlite, sqlite_unlock_notify
git version 2.7.4
Server: Ubuntu 16.04 inside proxmox 5.2 hypervisor with local address. NAT, forward port with mikrotik.
Client: Linux mint 19.1 

- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:
nothing
## Description
I am trying to open a web-page and Firefox 67.0.2 show me this;
"""
Corrupted Content Error
The site at https://gitea.xxx.xxx:33000/ has experienced a network protocol violation that cannot be repaired.
The page you are trying to view cannot be shown because an error in the data transmission was detected.
    Please contact the website owners to inform them of this problem.
"""

chrome, chromium with latest verions works fine. Logs are clear.

**Comment by Cherrg** [comment]
I have seen something like this with a wrongly configured OpenVPN. (wrong compression... on server/client side).

Are you sure your network is ok? Does the problem still exists with latest version?

**Comment by memost** [comment]
> Are you sure your network is ok?

Other browsers (chrome and chromium) works fine. I tried several proxy settings.
I am tried working in incognito mode and it works. I think its local issue. sorry.

**Comment by SilverWolf32** [comment]
I got that issue for a moment yesterday, but restarting the server fixed it. (I didn't test with anything other than Firefox, unfortunately.)

**Comment by Th3Whit3Wolf** [comment]
I have same issue. I am using wikijs 2.0 and when I try and fail to backup the wiki via git gitea goes down.
