### ISSUE TITLE
No access to database after update/reinstallation

### ISSUE THREAD

**Issue by tonnico** [go-gitea/gitea#7261]
- Gitea version (or commit ref): 1.7.2 <-> 1.8.1
- Git version: 2.19.2
- Operating system: armv7l GNU/Linux
- Database:
  - [ ] PostgreSQL
  - [x] MySQL (MariaDB)
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:
[gitea.log](https://gist.github.com/Wurstnase/2db8283ac9db96f21cdf02fbe522d348)

## Description
I tried to update my gitea from 1.7.2 to the latest release. Unfortunately this wasn't working. So I deinstalled the 1.8.1 and reinstalled 1.7.2. I've seen the install page, when you connect the first time. Everything look ok. My personal account was still there. All repositories can be seen in the overview.

But:
When I click on any repo I will see only a 500 error page.
Where should the git-data be? In the MariaDB?

The log say that it is trying to read in /usr/local/gitea/gitea/gitea-repositories
...

## Screenshots

![image](https://user-images.githubusercontent.com/8709415/59823354-419b8280-932e-11e9-9a0b-f1a0953e9651.png)

**Comment by Wurstnase** [comment]
Well, learning it the hard way. Fortunately I still have all the repos on my laptop.

The default path for repositories was in the folder with gitea. Deinsalling gitea removed also the repos.
Shouldn't the repos placed somewhere else by default, or is it at least with the first setup possible to setup the folder for the repos?
