### ISSUE TITLE
Webhook for slack sent wrong username

### ISSUE THREAD

**Issue by stani0502** [go-gitea/gitea#7265]
- Gitea version (or commit ref):
- Git version: 1.8.3
- Operating system: ubuntu
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:

## Description
Issue on webhook for slack, when tried to modify release tag (edit or deleting), the notification always show the creator name.
For example :
1. User A creating tag v1.0.0
Slack Notification: `[RepoName] new release v1.0.0 published by User A`
2. User B updating content for tag v1.0.0
Select Notification: `[RepoName] new release v1.0.0 updated by User A`
3. User B delete tag v1.0.0
Select Notification: `[RepoName] new release v1.0.0 deleted by User A`
...

**Comment by sapk** [comment]
I think this come from https://github.com/go-gitea/gitea/blob/85202d4784758573f80f93dbbda97a444e7ece99/models/release.go#L467 and https://github.com/go-gitea/gitea/blob/85202d4784758573f80f93dbbda97a444e7ece99/models/release.go#L412 where it should be `doer` and not `rel.Publisher`

This could be tagged as a good first issue.

**Comment by lafriks** [comment]
wasn't this already fixed in 1.9.x?

**Comment by lunny** [comment]
#7774 should already fix a slack problem but not this one.
