### ISSUE TITLE
Proposal: Restrict viewing certain (security) issues

### ISSUE THREAD

**Issue by Oreolek** [go-gitea/gitea#7278]
Can we have a security filter? Gitlab has a checkbox that makes some issues visible only to "team members with at least Reporter access." 

This is relevant to even the issue form itself because Github suggests sending a email instead of opening a public issue if it's a security concern. Gitea can be better than Github in that way.

**Comment by kolaente** [comment]
There is #3217 on that topic as well

**Comment by lunny** [comment]
@kolaente Oh, yes. This is a duplicated one.
