### ISSUE TITLE
Broken links from issues to commits after renaming organization

### ISSUE THREAD

**Issue by dpifke** [go-gitea/gitea#7283]
- Git version: 1.8.1 and 1.9.0+dev-374-gbaefea311
- Operating system: Ubuntu 18.04 LTS
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes ([example URL](https://try.gitea.io/DaveTest2Organization/DaveTest2Repository/issues/1))
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

After renaming an organization, links to commits from issues return 404.   See example issue here:

https://try.gitea.io/DaveTest2Organization/DaveTest2Repository/issues/1

Renaming DaveTestRepository → DaveTest2Repository was OK, but renaming DaveTestOrganization → DaveTest2Organization caused the link in the above issue to break.

**Comment by lunny** [comment]
I think this has been resolved.
