### ISSUE TITLE
Any way to manage OAuth2 apps via REST API?

### ISSUE THREAD

**Issue by Ziars** [go-gitea/gitea#7290]
- Gitea version (or commit ref): 1.8.3
- Git version: 2.22.0
- Operating system: Ubuntu 16.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant

Greetings!

I’m using Drone+Gitea (v.1.8.3) stack and just ran into a problem with automating the authorization process. To add an app I have to manually go to GUI (Settings => Applications), add the app through section “Manage OAuth2 Applications”, take the resulting ID and Secret for further usage in Drone. Authorization itself works fine, the problem is that I have lots of such Gitea instances, which are regularly created and deleted by scripts. So, without having a way of adding an app via API, I have to either add it manually on every Gitea instance, or use a rude INSERT into database. Is there a more graceful way, or maybe I’m missing something?

Thank you in advance.

**Comment by n0guest** [comment]
Also, it'd be very good not only to create random credentials (as it now in Gitea UI). But also create your own - i.e. specify key and secret in API request.

PS: Are there any plans or milestone on this feature?

**Comment by lunny** [comment]
@n0guest There is no plan to do this.

**Comment by 6543** [comment]
closed by #11008 and released since 1.12.0
