### ISSUE TITLE
Custom HTML Page

### ISSUE THREAD

**Issue by marcsiq** [go-gitea/gitea#7291]
- Gitea version (or commit ref): 1.8.3
- Git version:
- Operating system: Ubuntu
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
Hi there, 
Could someone help me with a minor issue?

Im trying to create a new Link to a custom html page on the head navbar.
I already added the link into *extra_links.tmpl* to that newpage.html and the link works.
Now what I want is that page to have the same look as the home page.
In that html I can't use Gitea head and footer because if I include {{template "base/head" .}} it does not get parsed.

Any help?

**Comment by kolaente** [comment]
I think you don't have a choice here but to copy the head/footer from any of the other Gitea pages.

**Comment by Marcsiq2** [comment]
Yeah I got to that, but now the head/footer is static. I mean, it does not vary if the user is logged in or not.
