### ISSUE TITLE
Proposal: Store original author in database for use with migrated content

### ISSUE THREAD

**Issue by mrsdizzie** [go-gitea/gitea#7293]
New migration features are really nice! However, the way we are showing the user who imported the content as the author for everything feels confusing and hard to read, especially with lots of issues/PRs. I think it would be very hard to work on a large repo (like gitea) that has been migrated and shows the same username for every issue and PR.

I'd like to propose using the original author name for templates/display only (not mapping it to another user or anything complicated). Keep it simple but make things much easier to read.

An example of what it might look like:

Old:
<img width="844" alt="Screen Shot 2019-06-25 at 1 26 51 PM" src="https://user-images.githubusercontent.com/1669571/60121209-908f5080-9750-11e9-8a83-15e0e4060dec.png">

These are confusing, especially when there are dozens of comments. It also makes a link to that user on the local instance even if they don't exist. This also makes it possible for a different person to register somebody else's name and have it maybe look like they made those comments.

Some new ideas:

<img width="840" alt="Screen Shot 2019-06-25 at 1 47 02 PM" src="https://user-images.githubusercontent.com/1669571/60121316-c9c7c080-9750-11e9-9239-5a9a8724f267.png">

<img width="842" alt="Screen Shot 2019-06-25 at 1 47 51 PM" src="https://user-images.githubusercontent.com/1669571/60121347-d77d4600-9750-11e9-83e1-fd14f75275e3.png">

This makes it more clear who wrote the comment and gives a quick visual indication that it was copied over from Github. The username could link to their Github profile, or just nothing at all if that is easier (so people aren't mistakenly taken to a different site). And the avatar should be different than the user who ran the import as well probably.

There are other places we display the name that can change too, but this is just an example of what it might be like to use the real author name. If something like this seems ok, maybe other ideas for this can be discussed here as well.

**Comment by lunny** [comment]
@mrsdizzie Good idea. I just gave a simple handler with users and reactions when migrating issues. 

To implement your idea, we should add a new column named `original_author` on table `issues` and add a `orignal_url` on `repository` I think.

Another idea is if you are a site administrator, you could create all the users automatically with random password if you check some options. When you migrating from Github Enterprise to Gitea, it's a useful feature.

**Comment by jakimfett** [comment]
I rather like the second of the two new GUI presentation of the imported bits, @mrsdizzie.

@lunny would a user, authenticated with the original source i.e. Github (via OAuth or similar), be able to interact with their own imported comment(s)?

**Comment by lunny** [comment]
@jakimfett As my opinion, when a user login gitea instance with github OAuth2(or bind), we can assign the imported comments to that user so that he will have permission manage his comments.

**Comment by mrsdizzie** [comment]
@lunny we should also have ```original_author``` on table ```comments``` too right? Should we try and store the email too if we are going to try to link with existing accounts in the future?

**Comment by lunny** [comment]
@mrsdizzie Right, `issues` and `comments` should have an extra column `original_author` and `repoisitory` should store migrating link or we may have an external table named `repo_migration` which will store columns of migrated repository, i.e. migrating_url and etc.

 I think we cannot got email from github's API. We can link them back to github via login name.

**Comment by mrsdizzie** [comment]
@lunny OK I will try and do a PR for that then

**Comment by techknowlogick** [comment]
@mrsdizzie We should store user ID too, because Github allows users to change name, and if original user changes name a new user could impersonate them.

**Comment by lunny** [comment]
@techknowlogick You are right. github API will return id. @mrsdizzie

**Comment by mrsdizzie** [comment]
@lunny It seems we need to store ```original_author```and ```original_author_id``` for pulls table also, since we don't migrate issue if isPull and we create a pull instead which gitea then adds to issues table. Does that sound OK/seem right?

**Comment by lunny** [comment]
Closed by #7352
