### ISSUE TITLE
[build/ci] gpg-sign step failure

### ISSUE THREAD

**Issue by sapk** [go-gitea/gitea#7295]
The `ggp-sign` step is failing on drone: https://drone.gitea.io/go-gitea/gitea/10134/1/26 . That mean that no binary is released. The signing secret seems to be missing.

**Comment by sapk** [comment]
Looking at [dl.gitea.io](https://dl.gitea.io/gitea/master/), I would say that it is failing since 06/22/2019

**Comment by lunny** [comment]
I will investigate it.

**Comment by sapk** [comment]
This should be fixed before 1.9 release. So maybe add it to the milestone.

**Comment by lunny** [comment]
This should be resolved if https://drone.gitea.io/go-gitea/gitea/10218 runs successfully.

**Comment by sapk** [comment]
Seems to have failed. 
When it works if you re-sign the key can you re-upload with the new sign (new expire date) to pgp keyservers ?

**Comment by lunny** [comment]
@sapk I have updated the public key, see https://pgp.mit.edu/pks/lookup?op=vindex&fingerprint=on&search=0x2D9AE806EC1592E2. I think CI failed because it may cached the public key.

**Comment by techknowlogick** [comment]
@lunny did you update private key on drone?

**Comment by lunny** [comment]
I have but it still failed.

**Comment by lunny** [comment]
I think I made a mistake when I update secret key. If https://drone.gitea.io/go-gitea/gitea/10294 successfully, this should be resolved.

**Comment by sapk** [comment]
Perfect. Thanks @lunny :tada:
