### ISSUE TITLE
Attachment file type is not allowed

### ISSUE THREAD

**Issue by pditommaso** [go-gitea/gitea#7302]
- Gitea version (or commit ref): 1.8.1
- Git version: 2.7.4
- Operating system: Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

I've the following config for the attachments 

```
[attachment]
ENABLED       = true
PATH          = /var/lib/gitea/data/attachments/
MAX_SIZE      = 4
MAX_FILES     = 5
ALLOWED_TYPES = image/jpeg|image/png|application/zip|application/gzip
```

However, when uploading a zip file it says "File type is not allowed".

## Screenshots

<img width="854" alt="Screenshot 2019-06-26 at 16 56 10" src="https://user-images.githubusercontent.com/816968/60190710-65316200-9833-11e9-8a35-6e2bac366fb2.png">

**Comment by Vorlif** [comment]
Hi pditommaso, 

please try to add:
* application/octet-stream, 
* application/x-zip-compressed
* multipart/x-zip

**Comment by pditommaso** [comment]
Tried this, still no joy: 

```
ALLOWED_TYPES = image/jpeg|image/png|application/zip|application/gzip|application/octet-stream|application/x-zip-compressed|multipart/x-zip
```

**Comment by silverwind** [comment]
File input allows specifying types by extension too, try adding the `.zip` extension directly:

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file#accept

**Comment by silverwind** [comment]
If above does not work, we can probably add support by it by passing the value of `attachment.ALLOWED_TYPES` directly to the `<input>`, replacing `|` with `,` in process.
