### ISSUE TITLE
Error 404 when close issue on archived repo 

### ISSUE THREAD

**Issue by davidglezz** [go-gitea/gitea#7303]
Close this demo issue:  https://try.gitea.io/davidglezz/test/issues/1

Edit:
... and comment form is visible.
![image](https://user-images.githubusercontent.com/194784/60191165-3071da80-9834-11e9-8c16-386ae2865ebc.png)

Close and comment are write operations.

**Comment by lunny** [comment]
Close/Comment buttons should be hidden on archived repositories.

**Comment by davidglezz** [comment]
Related:

![image](https://user-images.githubusercontent.com/194784/60249007-213a6d80-98c4-11e9-98b0-148eb2fbfde9.png)

**Comment by Cherrg** [comment]
Sounds like ui only issue as routes already reject close request...

**Comment by Cherrg** [comment]
I'm working on it
