### ISSUE TITLE
Locked issue UI broken

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#7304]
![image](https://user-images.githubusercontent.com/81045/60193122-b2302b00-9869-11e9-917b-9fc35a767ff2.png)

**Comment by Cherrg** [comment]
May I ask whats broken there?
As I never used this feature before, I don't know what it should look like. 
(Should the symbol be placed more to the left?)

This is how it looks on my side:
![grafik](https://user-images.githubusercontent.com/24939127/60313722-7e83fc80-9960-11e9-88bb-86051f7a649a.png)

(The thing I found was a spelling bug in german translation on the lock message :)  )

**Comment by lunny** [comment]
Maybe on an archived repository I think.

**Comment by lunny** [comment]
see https://gitea.com/gitea/git/issues/72

**Comment by Cherrg** [comment]
-> may "locked repo" message is missing, i will check later today

**Comment by Cherrg** [comment]
does #7345 addresses or fix this issue?

**Comment by Cherrg** [comment]
is this line the problem? 
![grafik](https://user-images.githubusercontent.com/24939127/60606096-fddb5b00-9dba-11e9-98e4-6da2072f6f0a.png)

**Comment by lunny** [comment]
@Cherrg right.

**Comment by Cherrg** [comment]
#7355 should fix this
