### ISSUE TITLE
Code review comment UI broken

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#7310]
![image](https://user-images.githubusercontent.com/81045/60246204-cf5c0c80-98f0-11e9-8bb4-a01ed9f54c58.png)

**Comment by zeripath** [comment]
Damn I thought I had caught all these. Exactly where did this one appear?

**Comment by zeripath** [comment]
Yeah this was fixed by #7288. @lunny you should update gitea.com to account for this.

Unfortunately my pr #7279 was broken in so many ways - I can't understand how it got past my UI testing.

**Comment by lunny** [comment]
@zeripath you are right. Thanks! gitea.com has been updated.

**Comment by lunny** [comment]
@zeripath you are right. Thanks! gitea.com has been updated.
