### ISSUE TITLE
Closing issue(s) by using batch checkbox leaves wrong item ticked. 

### ISSUE THREAD

**Issue by bobemoe** [go-gitea/gitea#7311]
- Gitea version (or commit ref):  1.9.0+dev-382-gc37ec66ee 
- Operating system: Linux (Devuan)
- Browser: FireFox
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

Closing issue(s) by using batch checkbox leaves wrong item ticked. 

## Reproduce

1. View a list of OPEN issues with more than 1 issue.
2. Use the batch operations checkboxes to select the FIRST item
3. Use the batch operations close button to close the issue

## Expected
The issue is closed, and is removed from the list. No other issues are ticked.

## Actual
The issue is close and removed as expected, however the position it was at remains ticked. As the issues have all moved up to fill the space, now an unrelated issue is ticked.

## Problem
A second click of the close button could close the wrong issue. Or if we wish to do another batch operation we need to untick all the wrong ticks.

## Fix
Untick all checkboxes after batch operation, but only if the operation was CLOSE.

I can see this is useful to keep them ticked if we are modifying milestone or label as we may want to preform another operation on the same issues, so I don't think we want to remove this functionality completely.

**Comment by bobemoe** [comment]
Also I just noticed that even if we do want to do a second operation, that the batch operation buttons disappear after the first operation, and even thought the issues remain ticked, you have to untick/tick another one before the batch operation buttons re-appear.

**Comment by Cherrg** [comment]
The problem is caused by browser cache. Process is as followed:
- check some checkboxes and click an action button
- the command is run in background
- page is reloaded
- if not stated otherwise, the browser will remember checked boxes (and sometimes filled input fields) and checks them without triggering click events

So the still checked boxes are more likely a bug than a feature to keep them checked.

Simplest solution is to tell the browser explicitly to not remember checked boxes.

**Comment by Cherrg** [comment]
To keep checked boxes would be an additional feature request.

This could be done in 2 ways:
  1. remodel js and backend, so there is no need for page reload anymore
  2. backend remembers checked boxes (if action != delete) and checks them again

**Comment by Cherrg** [comment]
I just noticed that browsers like Chrome/Cromium ( -> webkit) don't show this behavior, they simply don't remember the checkboxes. 
May they don't count checkboxes and use id or name instead...

**Comment by Cherrg** [comment]
pr will fix firefox behavior

- close: deselect all checkboxes
- nonclose: show buttons for close/label/milestone...

**Comment by silverwind** [comment]
> remodel js and backend, so there is no need for page reload anymore

this would be ideal yes. We should eventually abolish all uses of page reloads in JS, that's just unnecessary.
