### ISSUE TITLE
Add support for gifs as comment attachments.

### ISSUE THREAD

**Issue by FelixK15** [go-gitea/gitea#7312]
## Description

Adding support for gifs as attachments for comments would be of great help for our current real-time project since it makes it easier to convey eg. what an issue actually looks like on the users PC without having to write elaborate repro steps. 

We're using gitea version 7f7c451.

## Screenshots

![image](https://user-images.githubusercontent.com/7531672/60258434-6c10b100-98d5-11e9-80f5-57ec3fee683a.png)

**Comment by lunny** [comment]
The file types could be customized.

**Comment by silverwind** [comment]
Should be `ALLOWED_TYPES` in `app.ini`. It's documentation inside `app.ini` could be improved to state what the default value is.

**Comment by mrsdizzie** [comment]
Per https://github.com/go-gitea/gitea/blob/master/custom/conf/app.ini.sample I believe it is
```
image/jpeg|image/png|application/zip|application/gzip
```

So to fix this issue add this to your app.ini:
```
[attachment]
image/jpeg|image/png|image/gif|application/zip|application/gzip
```

**Comment by silverwind** [comment]
Ah, right it's `attachment.ALLOWED_TYPES`, I was looking at `repository.upload.ALLOWED_TYPES` earlier. Both look good documentation-wise, this issue is invalid.

**Comment by FelixK15** [comment]
Thanks! That worked :)
