### ISSUE TITLE
Mirror cronjobs created huge load

### ISSUE THREAD

**Issue by SvOlli** [go-gitea/gitea#7315]
- Gitea version (or commit ref):1.8.3
- Git version: 2.11.0
- Operating system: stretch / stable
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description

On rare occasions (something like once a month) the mirror cronjobs create a load of > 120 on my system running 30-50 git commands in parallel. Is there any way to limit the number git clients run? I could not find something searching the documentation and default config.

**Comment by SvOlli** [comment]
It looks like the problem is not related to the mirror update but some other cronjob. Can anyone tell me what the root cause of these processes is?
```
git       4943 39.7  0.4 201360 123164 ?       R    19:31   0:41 git -c credential.helper= -c filter.lfs.required= -c filter.lfs.smudge= -c filter.lfs.clean= rev-list -1 626c9705d29ec93610e87517aee771c2ea500f5d -- package/python-pudb
git       4956 44.8  0.5 201864 123644 ?       R    19:31   0:43 git -c credential.helper= -c filter.lfs.required= -c filter.lfs.smudge= -c filter.lfs.clean= rev-list -1 626c9705d29ec93610e87517aee771c2ea500f5d -- package/python-singledispatch
git       4964 43.7  0.5 201864 123636 ?       R    19:31   0:41 git -c credential.helper= -c filter.lfs.required= -c filter.lfs.smudge= -c filter.lfs.clean= rev-list -1 626c9705d29ec93610e87517aee771c2ea500f5d -- package/python-crcmod
git       4966 45.2  0.4 201504 123152 ?       R    19:31   0:42 git -c credential.helper= -c filter.lfs.required= -c filter.lfs.smudge= -c filter.lfs.clean= rev-list -1 626c9705d29ec93610e87517aee771c2ea500f5d -- package/python-pyasn
git       4983 44.2  0.4 201068 122364 ?       R    19:31   0:39 git -c credential.helper= -c filter.lfs.required= -c filter.lfs.smudge= -c filter.lfs.clean= rev-list -1 626c9705d29ec93610e87517aee771c2ea500f5d -- package/python-pyasn-modules
git       4990 44.5  0.4 199284 119312 ?       R    19:31   0:39 git -c credential.helper= -c filter.lfs.required= -c filter.lfs.smudge= -c filter.lfs.clean= rev-list -1 626c9705d29ec93610e87517aee771c2ea500f5d -- package/tk
```

**Comment by lunny** [comment]
This git processes will be invoked when users visit repository home page. This happend before gitea v1.9. In v1.9, we use go-git library to instead `git rev-list -1`.

**Comment by lunny** [comment]
Closed as my last comment.
