### ISSUE TITLE
Too long "provider settings" in "Settings" breaks Textbox in UI

### ISSUE THREAD

**Issue by Krumbelfix** [go-gitea/gitea#7322]
- Gitea version (or commit ref): gitea/gitea:1.8.3
- Git version:    2.20.1
- Operating system: buntu 18.04.2 LTS / Docker | docker-ce 18.09.6~3-0~ubuntu-bionic
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL (percona-Container)
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X] No 
  - [ ] Not relevant
- Log gist:

## Description
the providersettings under the following url are outside of the textbox
https://git.host/admin/config
Found this issue but it seems to exist in 1.8.3 also:
https://github.com/go-gitea/gitea/issues/6769

## Screenshots
![image](https://user-images.githubusercontent.com/8148917/60341424-bca80d00-99ae-11e9-847a-a37967a4dd55.png)

**Comment by mrsdizzie** [comment]
This has been fixed on master (PR #6914) and will be in the next 1.9 release
