### ISSUE TITLE
Add Malayalam localization

### ISSUE THREAD

**Issue by joicemjoseph** [go-gitea/gitea#7327]
## Description

Please add configurations for Malayalam, an Indic family of language to translations.

**Comment by lunny** [comment]
Please go to https://crowdin.com/project/gitea to create one translation.

**Comment by zeripath** [comment]
Hmm... I think one of the owners/managers needs to set it up first?

**Comment by techknowlogick** [comment]
![Screen Shot 2019-06-29 at 11 52 14 AM](https://user-images.githubusercontent.com/164197/60386600-081cf280-9a65-11e9-9f1e-31b340f99038.png)
It's now been enabled.

**Comment by joicemjoseph** [comment]
where is the placeholders ?

**Comment by zeripath** [comment]
@joicemjoseph https://crowdin.com/translate/gitea/all/enus-mlin

Lots of translation strings in Gitea don't have placeholders. They're just direct strings to translate eg. `app_desc` "A painless, self-hosted Git service" those that do have placeholders will be obvious as they have %s or the like in the source string.

**Comment by joicemjoseph** [comment]
Thank you for your kind reply. 

For instance, the string 
`Sign In With`

after that we have tiled social login buttons.

In case of Malayalam, social buttons has to come first and then the translation for `Sign In With` should be placed.

How that can be gained

**Comment by zeripath** [comment]
Ah unfortunately I don't think there's a way of pushing those to the back. Perhaps instead of translating this directly you could translate it as a header e.g. Sign-in Options? 

There's likely to be other places however, where we do need to think more clearly about our placeholder placement - so it may be worth stacking these up and opening an issue.

**Comment by joicemjoseph** [comment]
>  Sign-in Options?

That sounds OK.
