### ISSUE TITLE
gitea broken after wrong hook file

### ISSUE THREAD

**Issue by jaqra** [go-gitea/gitea#7338]
- Gitea version: 1.8.3
- Git version: 2.18.0.windows.1
- Operating system: Windows
- Database: SQLite
- Can you reproduce the bug at https://try.gitea.io: no
- Log gist:

## Description
my hook file was wrong, i pushed repository and gitea does not count new commits and does not create releases after push tags

hook file is: gitea-repositories\rst-yazilim\stm-say.git\hooks\update.d
   exe file was wrong like:

```
#!/usr/bin/env bash "H:/gitea/giteaexe"
```

`giteaexe` instead of `gitea.exe`

## Screenshots

as you can see 1 releases with 2 tags

![gitea hata](https://user-images.githubusercontent.com/48099350/60430955-4225fa00-9c07-11e9-8055-78986abb122b.JPG)

as you see 4 commits but have much more

![gitea hata 2](https://user-images.githubusercontent.com/48099350/60431013-62ee4f80-9c07-11e9-844a-9c35d577c0f0.JPG)

**Comment by lunny** [comment]
Resync hooks on Admin Panel

**Comment by jaqra** [comment]
Its ok. Thank you
