### ISSUE TITLE
Add option to load suppressed diffs

### ISSUE THREAD

**Issue by silverwind** [go-gitea/gitea#7341]
Currently if a diff is suppressed because it's too large there is no way to load it like GitHub does:

Gitea:
<img width="1152" alt="Screenshot 2019-07-02 at 10 23 19" src="https://user-images.githubusercontent.com/115237/60496689-a0a8b200-9cb3-11e9-8f6c-72289ce07ef7.png">

GitHub:
<img width="1203" alt="Screenshot 2019-07-02 at 10 23 47" src="https://user-images.githubusercontent.com/115237/60496695-a3a3a280-9cb3-11e9-8606-9af203a64d30.png">

**Comment by br-aw** [comment]
When someone makes a large change, we need to be able to see it.

**Comment by guillep2k** [comment]
To avoid cluttering the diff view for the PR/commit/etc., this could be implemented with a page of its own; the commit diff page can provide a link in these cases so the user can open it in a new tab.

**Comment by brandonkal** [comment]
@guillep2k is on to something here. Being able to diff between arbitrary commits would be great.

I

**Comment by zeripath** [comment]
Tbh the whole diff generating structure needs review. 

Huge diffs that don't change lots of files are not truncated and in fact are read completely into memory affecting both the server and the client's ability to function.

With any sensible rearchitecture we'll be able to grab extra diffs but it's getting the time to do this.

(This is what I mean when I say the compare endpoint needs to be completely reviewed - there are serious flaws at every point.)

**Comment by iarepandemonium** [comment]
Chiming in that I need this, since it's causing problems in that I can't put comments on specific lines in PRs.

**Comment by lorenzocasasanta** [comment]
Has there neem any development on this?

**Comment by zeripath** [comment]
I am currently looking (again) at this - part of the problem is that our code for generating compare pages is rather complex and altogether too interrelated. 

This PR fixing this will be big and require lots of time.

**Comment by silverwind** [comment]
I think we should aim to have the same mechanism to generate diffs and code view. There currently seem to be two mechanisms at work which also product differences in syntax highlighting an such, for example https://github.com/go-gitea/gitea/issues/16434.

**Comment by delvh** [comment]
Has been implemented by now: 
![image](https://user-images.githubusercontent.com/51889757/235326499-0d8067bd-bc8f-4f89-8580-77a8d7a502f2.png)
