### ISSUE TITLE
Unable to set private repo('s) back to public

### ISSUE THREAD

**Issue by francoism90** [go-gitea/gitea#735]
- Gitea version (or commit ref): git
- Git version: master
- Operating system: Arch Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:

## Description
app.ini:
```
[repository]
; Force every new repository to be private
FORCE_PRIVATE             = false ; was true
```

Restarted the service, logged out; however every new repo will be Private instead of Public.
The Visibility toggle has no effect.

Thanks! :)

**Comment by lunny** [comment]
This only effect the new repository when creating.

**Comment by francoism90** [comment]
@lunny Correct, but now I've set FORCE_PRIVATE to ```false``` - new repo's should be public instead as private. But still every new repo is created as private and I'm unable to toggle/force it to another state.

**Comment by lunny** [comment]
I cannot reproduce this. 
When set FORCE_PRIVATE = false, then
![image](https://cloud.githubusercontent.com/assets/81045/22246745/402ff91e-e271-11e6-9d5b-a308fe58f2c9.png)

When set FORCE_PRIVATE = true, and restart Gitea,
![image](https://cloud.githubusercontent.com/assets/81045/22246733/2da387c0-e271-11e6-9df8-ffad4e830062.png)

Both are OK. I tested in master with sqlite.

**Comment by francoism90** [comment]
Never-mind, sorry for the confusion, I was editing the wrong app.ini. :/
Thanks for testing and will double-check next time!
