### ISSUE TITLE
Allow duplicate user e-mail addresses

### ISSUE THREAD

**Issue by silverwind** [go-gitea/gitea#7357]
I run a bot account and would like this account to use the same e-mail address as my main account, but when I try to set the bot's address, I get a error `The email address is already used.`.

I suggest removing this restriction, unless there are real reasons why a e-mail address must be unique in the system.

**Comment by techknowlogick** [comment]
One such reason is password resets via email would result in an unexpected outcome. A suggestion is some mail providers allow for an advanced way making an email account into many (ex. `me+bot1@silverwind.io` would still go to me@...., although I'm not sure if zoho does that, I know fastmail and gmail both have this functionality.)

**Comment by renothing** [comment]
I'd suggest you use Subaddressing  rather than change the code.  most common scene the email is the unique identity, especial recover password or OAuth2 provider.

**Comment by silverwind** [comment]
I know about sub-addressing (in fact, I do run a wildcard e-mail route on my domain), but in this case, I'm using a Exchange mailbox which does not support this feature.

> password resets via email

Is it really an issue? The only issue I see is the user might be logged in on the wrong account and the password reset might not work expected in that case.

Not familiar with oauth, but if the e-mail is used as the unique identifier, then it might as well be a valid reason to enforce uniqueness.

**Comment by lunny** [comment]
Hi, I think we can close this. Allowing duplicated user email will cause many unknown things I think.
