### ISSUE TITLE
reference error in PWA serviceworker

### ISSUE THREAD

**Issue by Oreolek** [go-gitea/gitea#7372]
`ReferenceError: caches is not defined` - serviceworker.js, line 60.

Appeared in #4730 PR, reproducible on https://try.gitea.io if you load Gitea **in Firefox.** Firefox doesn't have the `caches` variable.

**Comment by Cherrg** [comment]
Can you please add some more information like used Firefox version and OS, screenshoot, or a way to reproduce?

I've tried on my local machine and on https://try.gitea.io with Ubuntu 18 and FF 67.0.4 (64-Bit). Unluckily (or luckily) I don't got any error from service worker. Additionally I tried to manually uninstall SW,  disable/re-enable cache, to force update of SW.

Thanks

**Comment by techknowlogick** [comment]
FF 67.0.4 (64-bit), macOS 10.14.5, and I am getting same output as @Cherrg on try.gitea.io

**Comment by Oreolek** [comment]
UPD: that Firefox has `dom.caches.enabled` set to `false`, so the `caches` var is not defined on serviceworker registration.

**Comment by techknowlogick** [comment]
@Oreolek is this something that you changed? My FF says what I have it set to is the default.

**Comment by Oreolek** [comment]
yes
