### ISSUE TITLE
Repo with existing directory misleadingly fails with 500

### ISSUE THREAD

**Issue by commel** [go-gitea/gitea#7374]
Hi,

- Gitea version (or commit ref):
- Git version: 1.8.3
- Operating system: Windows Server 2019 DS 1809
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No (because i cant delete a repo without removing its directory there)
  - [ ] Not relevant

## Description

we switched servers (and datbase backends from sqlite3 to mssql) but keeped the repository directories. I needed to recreate the former existing repository entries in gitea. After clicking "create repository" it resulted in a 500 error page. After refresh the empty repository was available.

In the logs I found this:
`
2019/07/08 10:00:23 [...routers/repo/repo.go:146 handleCreateError()] [E] CreatePost: initRepository: initRepository: path already exists: d:\repos\secretuser\secretrepo.git`

The error is misleading (and probably not wanted in that way) here as it works in the background. A notification message would be better to inform that the directory is already existing.

**Comment by dimmuboy** [comment]
I have same error with empty MSSQL database and initial Gitea config. I tried add LOCAL_ROOT_URL   = http://127.0.0.1:3000 to config, change permissions, database but still same error.

**Comment by lunny** [comment]
@dimmuboy Did you also have an exist repository on the same path as your created?

**Comment by dimmuboy** [comment]
> @dimmuboy Did you also have an exist repository on the same path as your created?

No I created completely new repo dir

**Comment by lunny** [comment]
> > @dimmuboy Did you also have an exist repository on the same path as your created?
> 
> No I created completely new repo dir

So you should have a different issue as this one.

**Comment by dimmuboy** [comment]
> So you should have a different issue as this one.

Yes but IMHO it will be problem with database because main dir sctructure "repository/username/" was created. In original post @commel wrote about switch to MSSQL like me.

**Comment by wxiaoguang** [comment]
It has been fixed #24164 by the way
