### ISSUE TITLE
Gitea crash on windows

### ISSUE THREAD

**Issue by bkodre** [go-gitea/gitea#7378]
- Gitea version (or commit ref): 1.8.3
- Git version:
- Operating system: Windows
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description
Gitea has crashed, there is nothing in log files about crash. 
In windows event viewer is error event with message: "The gitea service terminated unexpectedly.  It has done this 2 time(s)."

It is possible to get some additional logs except those in log folder?

**Comment by Cherrg** [comment]
- you could increase log level in `app.ini`
   - under section `[log]`
   - set `LEVEL     = info` to some other value ` [Trace, Debug, Info, Warn, Error, Critical, Fatal, None]`
- may run git in console
   `path\to\gitea.exe web`

**Comment by zeripath** [comment]
Is it crashing during startup or just normal running?

If it's during startup - likely your configuration is incorrect. 1.9 will give better logging.

**Comment by bkodre** [comment]
It crashed during normal running.
