### ISSUE TITLE
gitea 1.9.0rc - missing binaries on tagged version

### ISSUE THREAD

**Issue by Cherrg** [go-gitea/gitea#7382]
Shouldn't there be some build binaries and changelog on release list?  

-> I don't know the whole workflow so I just asked. 

drone build failed on `tag-test` https://drone.gitea.io/go-gitea/gitea/10493/1/11

**Comment by mrsdizzie** [comment]
It has not actually been released yet (per error above)

**Comment by lunny** [comment]
tag-test failed.

**Comment by Cherrg** [comment]
I tried to reproduce on local machine by `make test`. Are there some requirements to run those tests?
 -> I got more and other error messages

**Comment by lunny** [comment]
It should not require others.

**Comment by techknowlogick** [comment]
This is the test that fails: https://github.com/go-gitea/gitea/blob/edc94c70413048107ea728ff330f32ca3de6df88/modules/git/repo_test.go#L15

It fails specifically by calling this function https://github.com/go-gitea/gitea/blob/edc94c70413048107ea728ff330f32ca3de6df88/modules/git/repo.go#L326 which calls CLI `git for-each-ref --sort=-committerdate refs/heads/ --count 1 --format=%(committerdate)`

I've been able to replicate locally:

```
mkdir test
cd test
git init
git remote add origin https://github.com/go-gitea/gitea
git fetch origin +refs/tags/v1.9.0-rc1
git for-each-ref --sort=-committerdate refs/heads/ --count 1 --format=%\(committerdate\)
```
The last command returns `` which on a standard repo clone, or even a repo that has clone depth 200 it'll return a formatted date.

**Comment by lunny** [comment]
Yes, it needs a full clone I think but why it didn't fail before maybe because we changed .drone.yml to new format this release.

**Comment by techknowlogick** [comment]
It only failed with this tag because we introduced this test since release of 1.8 with merge of other git repo (now stored at modules/git). I don't think a full clone is needed, only something at `refs/head` so code will have something to reference.

**Comment by techknowlogick** [comment]
Ok. I have a solution that I've created a PR.
