### ISSUE TITLE
Can't see if repository is private

### ISSUE THREAD

**Issue by jaqra** [go-gitea/gitea#7384]
When repository is private and has avatar, old lock icon does not show.
Cant see if repository is private or not.

![gitea1](https://user-images.githubusercontent.com/48099350/60822563-5beab280-a1ae-11e9-8c2e-02c56735001e.JPG)
![gitea](https://user-images.githubusercontent.com/48099350/60822574-6016d000-a1ae-11e9-87ee-365bf02d81a2.JPG)

**Comment by lunny** [comment]
I think maybe we have two choices:
* one is composite the two images as one
* use a different color on repository name.

**Comment by jolheiser** [comment]
What about moving the icon to the right side of the name?  
Would that look too cramped?

The `archived` icon is added to the right when applicable, perhaps they could be grouped together?

Examples (quick hack using browser tools, not a final proposal):
![gitea_private](https://user-images.githubusercontent.com/42128690/60825253-e6142600-a170-11e9-85d4-7c31cf777a5d.png)
![gitea_private_lock](https://user-images.githubusercontent.com/42128690/60825254-e6142600-a170-11e9-9ec1-270f30adf6d4.png)

**Comment by lunny** [comment]
Just change it like on repository list.

![image](https://user-images.githubusercontent.com/81045/60828163-5740f100-a1e4-11e9-95b5-ba23fd93bf9a.png)

**Comment by joelft** [comment]
Any chance this could be moved to 1.10.0 milestone so that 1.9.0 can be released? PR #7387 is already in the 1.10.0 milestone and addresses this issue.
