### ISSUE TITLE
Search commit via commit SHA(short or full)

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#7395]
Currently it will always search in commit message.

**Comment by gary-kim** [comment]
Could I try working on this?

**Comment by lunny** [comment]
@gary-kim Yes, please. Nobody others are working on this.

**Comment by gary-kim** [comment]
@lunny There doesn't seem to be a built in way in git to search via commit hashes. It should possible to get the full list then find matching commits and add it to the list but that won't exactly be an efficient process. Does that sound okay?

**Comment by lunny** [comment]
I think we can just use https://github.com/go-gitea/gitea/blob/master/modules/git/repo_commit.go#L121 to do that maybe.

**Comment by gary-kim** [comment]
I already have it made, it's just that its inefficient. I'll open a pull request after testing.
