### ISSUE TITLE
U2F issue on 1.10 on gitea.com

### ISSUE THREAD

**Issue by curbengh** [go-gitea/gitea#7399]
- Gitea version (or commit ref): 1.10.0+dev-26-gf03e5b7c3
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description
Three days ago, I successfully enrolled U2F (Yubikey 5) using FF 67 on gitea.com. But today I couldn't use it, doesn't work in Chrome 75 too. I didn't take any screenshot at this point though.

Later, after I disassociate the U2F from gitea.com, I can't re-enroll back. On FF, there was no response when I press on the Yubikey. The FF U2F permission popup on top left did went away when I press, but not the "Add security key" message.
Chrome showed "Could not read your security key".

No issue on v1.8.3 ([snopyta](https://git.snopyta.org/) and [nixnet](https://git.nixnet.xyz/)).

No issue on try.gitea.io (1.10.0+dev-26-gf03e5b7c3).
...

## Screenshots
No response on FF.
![firefox-u2f](https://user-images.githubusercontent.com/43627182/60880952-dafdea80-a283-11e9-8a26-cc9d4ff71d71.png)

![chrome-u2f](https://user-images.githubusercontent.com/43627182/60880973-e94c0680-a283-11e9-82f8-0902530221b2.png)

**Comment by lunny** [comment]
gitea.com use the same docker image as try.gitea.io and I tested on MacOS with login with U2F(yubikey 4 nano) it succeed.

Any javascript log on console?

**Comment by weyusi** [comment]
console doesn't show anything. I also can't mirror https://gitlab.com/curben/urlhaus-filter, but no issue on try.gitea.io.
I'll try again with a new account on gitea.com.

**Comment by weyusi** [comment]
I just tried, I'm able to re-enroll U2F again.
