### ISSUE TITLE
Is there any way to configure force use security connection with smtp?

### ISSUE THREAD

**Issue by zhanhb** [go-gitea/gitea#7402]
`smtp.office365.com` such as `my-account@outlook.com` support only starttls on port 587.
From the source I can see there's no protection for Man-in-the-middle and downgrade attack.
https://github.com/go-gitea/gitea/blob/5a438ee3c0303efcb9d1935ff521917fe8a109e8/services/mailer/mailer.go#L156-L162

**Comment by zhanhb** [comment]
Some mail provider may support both tls/starttls on port 587 such as `smtp.gmail.com`

**Comment by zhanhb** [comment]
If let me design a smtp client now, the configure key without considering historical compatible will be like like this.
```ini
security-connection=force-tls|force-startssl|tls|starttls|plain
```
```txt
force-tls: support only tls connection, usually on port 465
force-startssl: support only starttls connection, usually on port 587
tls: support only tls/starttls, can be configured on both 465/587
starttls: support starttls/plain, can be configured on port 587/25
plain: support plain, usually on port 25.
```

Maybe here gitea should add a key like `forcetls` to configured the third behaviour.

**Comment by andreymal** [comment]
I agree, `connection=plain` is needed for my specific case

**Comment by wxiaoguang** [comment]
The mailer system has been refactored. 

https://github.com/go-gitea/gitea/blob/main/custom/conf/app.example.ini

I think it should work for you case. Feel free to reopen if there is any problem

**Comment by zhanhb** [comment]
I read the source code carefully, and the corresponding relationship with the configuration I specified above is like this
```
PROTOCOL=smtps  => connection=tls-only
PROTOCOL=smtp+starttls  => connection=starttls-optional  // Downgrade attacks cannot be prevented
PROTOCOL=smtp  => connection=plain
```

There's no way to configure a value supports both `starttls` and `tls` or  `starttls` only.

**Comment by zhanhb** [comment]
The warning I would expect to see in the result log should look something like this:
```yml
start up:
    starttls-optional:
        WARNING("configured as starttls-optional, may be downgraded attack") if is not loopback address
    plain:
        WARNING() if is not loopback address
    try-all:
        WARNING("try-all should only be used for debugging the configuration, please use tls/tls-only/starttls/plain instead")
exchange:
    tls-only:
        ERROR("tls connection failed")
    starttls:
        ERROR("The server does not support starttls")
        ERROR("The server reports starttls supported, but failed to connect")
    tls:
         // INFO("tls connection failed")
         ERROR("The server does not support starttls")
         ERROR("The server reports starttls supported, but failed to connect")
    starttls-optional:
         // INFO("The server does not support starttls, use plain instead") // WARN?
         WARN("The server reports starttls supported, but failed to connect, use plain instead")
    try-all:
         might be any message combination above.
```
