### ISSUE TITLE
connectex: Only one usage of each socket address (protocol/network address/port) is normally permitted

### ISSUE THREAD

**Issue by bkodre** [go-gitea/gitea#7411]
- Gitea version (or commit ref): 1.8.3
- Git version:2.22.0.windows.1
- Operating system: Windows server 2012 R2
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description
Gitea is writting this message in log file every 200 milliseconds:

2019/07/10 07:32:18 [...s/context/context.go:238 func1()] [E] UserSignIn: dial tcp 127.0.0.1:3306: connectex: Only one usage of each socket address (protocol/network address/port) is normally permitted.
2019/07/10 07:32:18 [...s/context/context.go:238 func1()] [E] GetAccessTokenBySha: dial tcp 127.0.0.1:3306: connectex: Only one usage of each socket address (protocol/network address/port) is normally permitted.
20

What can be done to solve this issue.?

**Comment by bkodre** [comment]
Setting registry keys MaxUserPort to 65535 and TcpTimedWaitDelay to 30 solved the problem.
[Settings that can be Modified to Improve Network Performance](https://docs.microsoft.com/en-us/biztalk/technical-guides/settings-that-can-be-modified-to-improve-network-performance)

**Comment by zeripath** [comment]
For future suffers: see #7416 and  in particular https://github.com/go-gitea/gitea/issues/7416#issuecomment-510456611
