### ISSUE TITLE
git pull,first 401,and then 200

### ISSUE THREAD

**Issue by imamong** [go-gitea/gitea#7412]
run git pull in client:
```
zdh@CSZX:/doc/xx> git pull
Already up-to-date.
zdh@CSZX:/doc/xx> 
```

gitea server log will show two, first is 401, and ok, why ??????
```
[Macaron] 2019-07-10 17:01:38: Started GET /dev/XData/info/refs?service=git-upload-pack for 10.114.14.174
[Macaron] 2019-07-10 17:01:38: Completed GET /dev/XData/info/refs?service=git-upload-pack 401 Unauthorized in 629.013µs
[Macaron] 2019-07-10 17:01:38: Started GET /dev/XData/info/refs?service=git-upload-pack for 10.114.14.174
[Macaron] 2019-07-10 17:01:38: Completed GET /dev/XData/info/refs?service=git-upload-pack 200 OK in **88.473014ms**
```

can set to show one ?

**Comment by ardentsword** [comment]
If I'm not mistaken this is part of the HTTP authentication definition (https://en.wikipedia.org/wiki/Basic_access_authentication).
The server first responds with a 401 to notify the client that it needs to send its credentials. The client then sends a second request with its credentials and receives a 200.

**Comment by imamong** [comment]
tks
