### ISSUE TITLE
Move installation, wrong hook path

### ISSUE THREAD

**Issue by gizmo15** [go-gitea/gitea#7414]
Hi,

I use gitea 1.8.3 on a FreeBSD12. At the beginning, i use gitea on debian 8 and i migrate the data to the new env.

The installations are differents : on debian all data are in /home/git/gitea and on FreeBSD i use the package so the data are in /var/db/gitea.

When i want to push on the new env, i have this message : 
remote: ./hooks/pre-receive.d/gitea: line 2: /home/git/gitea: No such file or directory

And if i search this path in /var/db/gitea/gitea-repositories i found this path on every hook for all my git repo.

How can i change that?

Thanks for the help!

**Comment by zeripath** [comment]
Have you tried the Resynchronize hooks command on the admin page?

**Comment by gizmo15** [comment]
I haven't notice this line... thanks it's work!
