### ISSUE TITLE
Upgrade to master not working ?

### ISSUE THREAD

**Issue by theAkito** [go-gitea/gitea#7415]
- Gitea version (or commit ref): de facto: b04a1d9d639a285db6c3fb9fd675ccb22a04fd14 but should be: b84a251fca78784682d49e3699eaae51203f8ffd
- Git version: 2.11.0
- Operating system: DietPi (based on Raspbian Stretch)
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist: x

## Description
Ran the upgrade as shown here: https://docs.gitea.io/en-us/install-from-source/ to upgrade to master, without checking out to any version. `git branch` confirms `master` branch. But `git show` displays `commit b04a1d9d639a285db6c3fb9fd675ccb22a04fd14` which is an old commit from April 1st.

Now I did a `git fetch && git pull` in `$GOPATH/src/code.gitea.io/gitea`, so it updated to the newest commit. Then I ran `go get -d -u code.gitea.io/gitea`

### Is this a gitea or go bug?
____
____

# Workaround
1. 
```
cd "$GOPATH/src/code.gitea.io/gitea"
```
2.
```
git fetch && git pull
```
3.
```
go get -d -u code.gitea.io/gitea
```
4.
```
TAGS="bindata" make generate build
```

**Comment by jolheiser** [comment]
`go get -d -u code.gitea.io/gitea` *should* download the most recent version of `https://github.com/go-gitea/gitea`   
There are some cases where it would behave differently, but those are generally limited to using modules or other development.

----

I ran the following, moving `GOPATH` to a tmp location for testing

`GOPATH=/tmp/go go get -d -u code.gitea.io/gitea` 

And now `git show` is giving me b84a251fca78784682d49e3699eaae51203f8ffd (latest)

I reset my commit to the one you mentioned above (b04a1d9d639a285db6c3fb9fd675ccb22a04fd14) and ran my command again.  
`git show` is giving me b84a251fca78784682d49e3699eaae51203f8ffd again


Were any errors given by chance? I'm not sure what else could have happened.
