### ISSUE TITLE
Upgrade jquery to 3.x

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#7422]
Since 1.x and 2.x may include security problem, maybe we should upgrade to 3.x. And for compitable, we could use jQuery Migrate .

**Comment by sapk** [comment]
Or maybe drop it ? Is it used a lot ?

**Comment by lunny** [comment]
I think many javascript library depend on it.

**Comment by kjellkvinge** [comment]
Related:   #4384

**Comment by silverwind** [comment]
👍  on upgrade
👎  on jquery.migrate, better to update any usage of deprecated/removed API than to rely on such bandaid solutions.
