### ISSUE TITLE
REQUIRE_SIGNIN_VIEW not working

### ISSUE THREAD

**Issue by hb-i** [go-gitea/gitea#7427]
- Gitea version (or commit ref): 1.8.3
- Git version: 2.17.1
- Operating system: Ubuntu 18.04
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description

I have REQUIRE_SIGNIN_VIEW set to true in app.ini. However, you can still view and explore the site and repos without signing in. I've tried restarting the service and server multiple times.

## Screenshots

![image](https://user-images.githubusercontent.com/27036750/61078777-ab172a00-a3de-11e9-918c-e0c5d710d2ba.png)

**Comment by jolheiser** [comment]
Just to confirm, when running Gitea, can you navigate to `www.yourgitea.com/admin/config` as an admin and check that `Require Sign-In to View Pages` in the `Service Configuration` section is marked?  
  
If you want to navigate there manually:
1. Go to `Site Administration` (in the dropdown when clicking on your profile in the upper-right corner)
2. Click the `Configuration` tab
3. Scroll down to `Server Configuration`

Just want to make sure it's picking up the correct `app.ini` and not something else by accident.

**Comment by hb-i** [comment]
> Just to confirm, when running Gitea, can you navigate to `www.yourgitea.com/admin/config` as an admin and check that `Require Sign-In to View Pages` in the `Service Configuration` section is marked?
> 
> If you want to navigate there manually:
> 
> 1. Go to `Site Administration` (in the dropdown when clicking on your profile in the upper-right corner)
> 2. Click the `Configuration` tab
> 3. Scroll down to `Server Configuration`
> 
> Just want to make sure it's picking up the correct `app.ini` and not something else by accident.

![image](https://user-images.githubusercontent.com/27036750/61080303-03036000-a3e2-11e9-9b56-485d37c20d6a.png)

It's not marked. It's weird because it is picking the right app.ini file because when I enable/disable the `DISABLE_REGISTRATION` option, I can see the Register button appear and disappear at the top right after I restart service.

**Comment by jolheiser** [comment]
Can you provide me with 
1. The path to your `app.ini`
2. The command you (or the service) is using to start Gitea  

You can scrub anything if necessary, just make sure like paths are scrubbed the same.

I'm still thinking it's a configuration thing somewhere if it's not picking up that change.

**Comment by hb-i** [comment]
> Can you provide me with
> 
> 1. The path to your `app.ini`
> 2. The command you (or the service) is using to start Gitea
> 
> You can scrub anything if necessary, just make sure like paths are scrubbed the same.
> 
> I'm still thinking it's a configuration thing somewhere if it's not picking up that change.

Here you go.

https://pastebin.com/KLDQeLyv

Thanks.

**Comment by jolheiser** [comment]
You have `REQUIRE_SIGNIN_VIEW` declared twice.

In the pastebin, lines 44 and 50.

**Comment by hb-i** [comment]
> You have `REQUIRE_SIGNIN_VIEW` declared twice.
> 
> In the pastebin, lines 44 and 50.

Thanks embarrassing. Thank you. It worked!
![image](https://user-images.githubusercontent.com/27036750/61081570-c08f5280-a3e4-11e9-9757-e6ceac47394b.png)

**Comment by jolheiser** [comment]
Happy to help! 😄
