### ISSUE TITLE
Pull requests for project show -1

### ISSUE THREAD

**Issue by bkraul** [go-gitea/gitea#7428]
- Gitea version (or commit ref): 072bdfa (1.10.0+dev-31-g072bdfa3f)
- Operating system: docker container
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
For some reason, a project with a recently merged PR (there are no more outstanding PRs) is showing a -1 in its count badge.

## Screenshots
![image](https://user-images.githubusercontent.com/14616851/61087697-fbe94b80-a3fb-11e9-92f3-c4480fd92e27.png)

**Comment by Cliff2103** [comment]
We have found the same issue here, our count is on -2, we've found out that 2 of our PR were closed twice, which should not even be possible. So it looks like a bug on closing PRs.

**Comment by bkraul** [comment]
You are correct. I just merged a PR on another project and I can see the PR is closed twice, even though the merge operation only happened once:

![image](https://user-images.githubusercontent.com/14616851/61386113-4a25a100-a879-11e9-896e-d59df0291154.png)
