### ISSUE TITLE
search by keyword in issue

### ISSUE THREAD

**Issue by avelino** [go-gitea/gitea#743]
It is important for the project to have keyword search?

PR on gogs: https://github.com/gogits/gogs/pull/4015

**Comment by lunny** [comment]
For issues or codes or others?

**Comment by avelino** [comment]
@lunny sorry, `issue`

**Comment by lunny** [comment]
There is already a PR #530 to resolve this.

**Comment by lunny** [comment]
And duplicated with #379. Let's discuss there.
