### ISSUE TITLE
Incomplete digital display

### ISSUE THREAD

**Issue by shijunti19** [go-gitea/gitea#7433]
- Gitea version (or commit ref):all
- Git version:all
- Operating system:all
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
![image](https://user-images.githubusercontent.com/5392211/61103949-df561d80-a4a6-11e9-8071-4d07263f4e35.png)
source code:
![image](https://user-images.githubusercontent.com/5392211/61103954-e3823b00-a4a6-11e9-9d1c-60c12b149906.png)
**3 missing**

...

**Comment by lafriks** [comment]
imho this should be already fixed, please reopen if you can still reproduce this on try.gitea.io
