### ISSUE TITLE
Cron task for repo garbage collection

### ISSUE THREAD

**Issue by silverwind** [go-gitea/gitea#7436]
I think a cron task to garbage collect all repos (defaulting to 1 per day) would be quite useful to eliminate this manual activity. This is of course assuming it is a operation without any risks involved.

Or more generally, we could allow cron tasks to be set up for all manual tasks visible in Site Administration -> Dashboard in the UI.

**Comment by clarfonthey** [comment]
Noticed this is already a feature when searching for another bug. Think it should be closed?

**Comment by zeripath** [comment]
yup already implemented (a long time ago)
