### ISSUE TITLE
Adding an SSL Certificate to Docker Deployment

### ISSUE THREAD

**Issue by WDC** [go-gitea/gitea#744]
- Gitea version: 1.0.0+148-g521d429b
- Git version: 2.7.4
- Operating system: Ubuntu 16.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant

## Description
What is the preferred method of adding an SSL certificate to Gitea, when deployed using Docker? I have searched through the container, and cannot find `nginx` anywhere, and there seems to be no way of adding the certificates in the `app.ini` configuration file, or elsewhere.

Thanks for your time!

**Comment by tboerger** [comment]
I suggest to use q revers proxy for SSL termination, but if you really want to use Gitea for the SSL termination you can always find the `app.ini` within the volume `/data/gitea/conf/`, additionally just link your certs as volumes into the container and link them in the `app.ini`. If you got more questions like that feel free to take a look at our Gitter chat.
