### ISSUE TITLE
Why Not  Move the main repo from Github to Codeberg

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#7440]
I am not here to start flamewar .
But,I want to ask simple question. Why did you host main repo of Gitea on Github ?
Github is not Gitea Instance. So,Why not consider Moving to Codeberg.org (Alternative to Github) which is Hosted Instance of Gitea ?
Another Idea is that Why Not Host the Main Repo yourself ?

Thinking of Population of Github ? I think It's Not an Issue. You can just replace README.md with "Moved to Codeberg.org" .

This is my opinion though.

**Comment by jolheiser** [comment]
This is covered in our [README](https://github.com/go-gitea/gitea/blob/master/README.md#faq)  
As well as the original issue #1029 

We currently have Gitea's code set up as a [mirror](https://gitea.com/gitea/gitea_mirror) on https://gitea.com/ while we move everything over (issues, PRs, other repos, etc.)

If you are interested in following progress, I believe #1029 is still the most up to date place to look.

**Comment by varshitgithub** [comment]
OK :)
