### ISSUE TITLE
Change the name of the "Fork" Button

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#7441]
I think we all are Misinterpreting "Fork word" in Git. We must use Some other word in "Fork Button" .
[Please Read the Source where I learnt that Fork word in Fork Button is wrong.](https://drewdevault.com/2019/05/24/What-is-a-fork.html)

**Comment by lafriks** [comment]
Not really sure what that would solve and how that is really wrong as forking not always are used just to propose changes upstream but at many times to actually fork project in it's original sense. I don't really see any proposal on what to rename that button to
