### ISSUE TITLE
Issue label selection broken

### ISSUE THREAD

**Issue by silverwind** [go-gitea/gitea#7446]
On latest master, it's not possible to set a label on a issue. The page jumps to the top (I think through the hash link on the label element) and nothing happens. I think this is a regression from the jQuery update.

**Comment by cloonix** [comment]
Anything on the edit issue selection fields has no effect: Selecting the branch, the label, the milestone, assignee.

**Comment by gary-kim** [comment]
I believe this issue was fixed by 831288cc916d5301beaa0adc1d912d6748a4cdaa.

**Comment by lunny** [comment]
fixed by #7445
