### ISSUE TITLE
Allow commenting tickets via mail

### ISSUE THREAD

**Issue by strk** [go-gitea/gitea#745]
It would be useful to be able to reply to email notified upon ticket activity.
This is more or less what's requested to Gogs via https://github.com/gogits/gogs/issues/2602#issuecomment-233976184

It could be some `gitea readmail` comand reading a message from stdin, letting system administrators configure an email address forwarded to the command (would be easy in unix world). Implies holding a database with identifiers for threads/users to match.

**Comment by tboerger** [comment]
Not an easy task because multiple input ways have to be covered.

**Comment by Josue-T** [comment]
Hello,

Maybe the solution would be to add some parameter to access a pop3 mailbox and gitea will retrieve each 5 minutes the mailbox content. This way was already implemented in forum discurse.

**Comment by lafriks** [comment]
Or we could add smtp server to gitea :]

**Comment by lunny** [comment]
@lafriks We just need to check email via pop/IMAP protocol.

**Comment by lunny** [comment]
The problem is how we recognize which email is a comment to which repository's which issue. We need make a rule.

**Comment by ptman** [comment]
In-Reply-To or References header that matches an email that was sent from the issue? https://stackoverflow.com/questions/40998463/in-reply-to-and-reference-had-been-added-to-email-header-but-still-send-as-new-m

**Comment by lunny** [comment]
It seems right. We can include a header in the email we sent. But when user reply to this email, if the header will be copied to the reply email?

**Comment by a1012112796** [comment]
That's&nbsp;seems&nbsp;right. Here is the message in github email, may be we can try same style ...``
Date: Sun, 19 Apr 2020 07:43:39 -0700 From: Lunny Xiao <notifications@github.com&gt; Reply-To: go-gitea/gitea <reply@reply.github.com&gt; To: go-gitea/gitea <gitea@noreply.github.com&gt; Cc: Subscribed <subscribed@noreply.github.com&gt; Message-ID: <go-gitea/gitea/issues/745/616150955@github.com&gt; In-Reply-To: <go-gitea/gitea/issues/745@github.com&gt; References: <go-gitea/gitea/issues/745@github.com&gt; Subject: Re: [go-gitea/gitea] Allow commenting tickets via mail (#745) Mime-Version: 1.0 Content-Type: multipart/alternative;  boundary="--==_mimepart_5e9c639bb9db_2ac03fa88d0cd9681698d";  charset=UTF-8 Content-Transfer-Encoding: 7bit Precedence: list X-GitHub-Sender: lunny X-GitHub-Recipient: a1012112796 X-GitHub-Reason: subscribed List-ID: go-gitea/gitea <gitea.go-gitea.github.com&gt; List-Archive: https://github.com/go-gitea/gitea List-Post: <mailto:reply@reply.github.com&gt; List-Unsubscribe: <mailto:unsub+AGBLDSVFHOXULGY25KN7O554VBCJXEVBNHHAYF6MYI@reply.github.com&gt;,  <https://github.com/notifications/unsubscribe/AGBLDSQ4RV7B75FDV4HYPQLRNMEZXANCNFSM4C5SGZ3A&gt; X-Auto-Response-Suppress: All X-GitHub-Recipient-Address: 1012112796@qq.com
``


and it has a fast reply button, which I used&nbsp; now. I think It's also usefull.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Lunny Xiao"<notifications@github.com&gt;; 
发送时间: 2020年4月19日(星期天) 晚上10:43
收件人: "go-gitea/gitea"<gitea@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: Re: [go-gitea/gitea] Allow commenting tickets via mail (#745)





 
It seems right. We can include a header in the email we sent. But when user reply to this email, if the header will be copied to the reply email?

**Comment by a1012112796** [comment]
Here is my first time to try email reply in github, I found the commet publish by email is more slow to show on ui than comment directly . so maybe github also did the same things which we thinking :)

**Comment by a1012112796** [comment]
maybe we have send replies  message now ...
https://github.com/go-gitea/gitea/blob/9f959ac0641821148e46d0899b74cc714c858879/services/mailer/mail.go#L249-L258
So maybe only need to add something to recive email 😊

**Comment by strk** [comment]
A `gitea` commandline argument to "parse mail" would be enough for a
start. A system administrator would setup their favorite mechanism
to receive mail and would pipe the mail content to such new
commandline.

**Comment by a1012112796** [comment]
> A `gitea` commandline argument to "parse mail" would be enough for a
> start. A system administrator would setup their favorite mechanism
> to receive mail and would pipe the mail content to such new
> commandline.

It's reasonble, But I think we can also add built-in IMAP suport to recive email . it will be more easily for user to use.

**Comment by guillep2k** [comment]
> 
> 
> A `gitea` commandline argument to "parse mail" would be enough for a
> start. A system administrator would setup their favorite mechanism
> to receive mail and would pipe the mail content to such new
> commandline.

There's always the API...

**Comment by a1012112796** [comment]
https://github.com/emersion/go-imap
