### ISSUE TITLE
Organizations repo list broken

### ISSUE THREAD

**Issue by plessbd** [go-gitea/gitea#746]
- Gitea version (or commit ref): master as of 2017-01-24
- Git version: n/a
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:
master: https://gist.github.com/plessbd/b5c6542cec4dd02a248c9af0a0d96807
release: https://gist.github.com/plessbd/938decf1c447bf586369aa4c1f249bcc
## Description
Somewhere between the release and master when going to an organization view as a non admin the repositories seem to be "duplicated" with "empty" repositories.  they show up the same number of times as the actual repositories which show up below.  I have attached a screenshot, as well as xorm.log output from the release and master branches.

If there is anything else I can do please let me know.

![screen shot 2017-01-24 at 2 20 01 pm](https://cloud.githubusercontent.com/assets/683012/22262839/6c8de98e-e240-11e6-9310-3731cf731843.png)

**Comment by Bwko** [comment]
#749 fixes this issue :smile:

**Comment by plessbd** [comment]
I thought it would when I saw the pr :)

**Comment by lunny** [comment]
closed by #749
