### ISSUE TITLE
web-hook payload corrupted when commit label contain emoji

### ISSUE THREAD

**Issue by koekaverna** [go-gitea/gitea#7469]
- Gitea version (or commit ref): 1.8.3
- Git version: 2.20.1
- Operating system: Ubuntu 19.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description
I have web-hooks and it works fine.
But after pushing commit with emoji in label (ex. "Test:😀 ⚒")
My hook receives corrupted payload:
```
{
  "secret": "MySecret",
  "ref": "refs/heads/master",
  "before": "12207931c6be911a76f65524092e1a8ed6933ff2",
  "after": "bfbbc1a2d4d8a968058f7fab58213f36fe865a35",
  "compare_url": "https://git.mygit.net/MyRepo/site/compare/12207931c6be911a76f65524092e1a8ed6933ff2...bfbbc1a2d4d8a968058f7fab58213f36fe865a35",
  "commits": [
    {
      "id": "bfbbc1a2d4d8a968058f7fab58213f36fe865a35",
      "message": "Test:
```
It ends before emoji.

**Comment by lunny** [comment]
Did your mysql database use `utf8mb4` and your app.ini has `Charset=utf8mb4` option?

**Comment by lunny** [comment]
I think this is a configuration problme about mysql utf8mb4.
