### ISSUE TITLE
Feautre Request: Git Blame

### ISSUE THREAD

**Issue by plessbd** [go-gitea/gitea#747]
Github gives us to look at a blame page for a file:
![image](https://cloud.githubusercontent.com/assets/683012/22263094/3cf75d3a-e241-11e6-8a74-d110b54e9cd0.png)
resulting in something like: https://github.com/go-gitea/gitea/blame/master/CONTRIBUTING.md

It would be nice to have this feature in Gitea as well.

this is a duplicate of gogits/gogs#2606

**Comment by makhov** [comment]
Good idea. I'll try to make the feature. 
@tboerger assign it to me, please

**Comment by tboerger** [comment]
Solved via #32

**Comment by plessbd** [comment]
I do not believe this is solved by #32 or go-gitea/git#32
I believe that @makhov is still working on it in his feature branch https://github.com/makhov/gitea/tree/feature/blame

**Comment by tboerger** [comment]
You are right, properly checking the references helps :)

**Comment by lunny** [comment]
It seems `git blame` have to be used in a git workspace?

**Comment by strk** [comment]
@makhov  any news on this ?
This feature was considered in the Git hosting solution comparison table of notabug.org:
https://ethercalc.org/choose-the-git-host.html

**Comment by plessbd** [comment]
@makhov any news?  Would love t see this feature.

**Comment by plessbd** [comment]
Any progress on this?

**Comment by lunny** [comment]
@plessbd nobody on this issue now I think.

**Comment by bkcsoft** [comment]
Unassigned for lack of status :)

**Comment by lcges** [comment]
Who is working on this?

**Comment by ptman** [comment]
Assignees seems pretty empty to me

**Comment by lcges** [comment]
If I understand well?
The issue is up to you - but you have not done anything yet?

**Comment by dj-thd** [comment]
Any news? I would love to see that feature but unfortunately I'm not proficient with Go :(

**Comment by cdstg** [comment]
I also want lol

**Comment by ptman** [comment]
there's a fresh pull request, how is this stale?

**Comment by techknowlogick** [comment]
@ptman stalebot doesn’t know about linked PRs. This is something we are looking into updating

**Comment by NotAFile** [comment]
still an open pr
