### ISSUE TITLE
UserDoesNotHaveAccessToRepo when trying to create a ticket and assigning it

### ISSUE THREAD

**Issue by bohwaz** [go-gitea/gitea#7470]
- Gitea version (or commit ref): 1.8.3
- Git version: ?
- Operating system: Ubuntu
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x ] Not relevant
- Log gist:

## Description

This repo belongs to an organization where some members only have the right to read and write to issues.

When, as a repo admin, want to create a ticket assigned to a member of the organization that is limited to tickets read/write, Gitea fails with just a blank page saying "UserDoesNotHaveAccessToRepo".

If I create the ticket without any assignee, it works, and then I can assign the same person to the ticket without any issue.

**Comment by lunny** [comment]
@bohwaz could you reproduce that on https://try.gitea.io I think it may has been fixed.

**Comment by lafriks** [comment]
Closing as fixed, please reopen if it is not

**Comment by bohwaz** [comment]
Can confirm it's fixed, thanks!
