### ISSUE TITLE
Using slash (/) in wiki title gives 404

### ISSUE THREAD

**Issue by bobemoe** [go-gitea/gitea#7471]
- Gitea version (or commit ref): 1.10.0+dev-45-g4091e0dfe
- Git version: 2.11.0
- Operating system: Devuan Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No works as expected https://try.gitea.io/bobemoe/test/wiki/test%2Fing
  - [ ] Not relevant
- Log gist:

## Description

I've put a slash into one of my Wiki page titles, and now I can not access that page, it just 404's. 

#2869 seems to have fixed a similar issue

I've tested on try.gitea.io and it works fine so I suspect its my server setup? I'm using Apache 2.4.25-3+deb9u7 on a Virtualmin server. Using simple conf with apache proxy: 
```
ProxyPass / http://localhost:3000/
ProxyPassReverse / http://localhost:3000/
```

I have tried various values for `AllowEncodedSlashes` in apache conf, and it makes a difference but doesnt fix it:

* AllowEncodedSlashes On

    Asks me to authenticate with auth basic: `https://xxxx is requesting your username and password. The site says: “.”`

* AllowEncodedSlashes Off

    `The requested URL /bobemoe/test/wiki/test/ing was not found on this server.`

* AllowEncodedSlashes NoDecode

    Redirects me back to /bobemoe/test/wiki/_pages

Not sure where to look next? Any clues? Thanks.

**Comment by gary-kim** [comment]
You can fix this in your Apache proxy configuration. Append `nocanon` to your `ProxyPass` directive.

For example, this is my proxy configuration:
```
AllowEncodedSlashes NoDecode
ProxyPass / http://127.0.0.1:3000/ retry=0 nocanon
ProxyPassReverse / http://127.0.0.1:3000/
```

**Comment by gary-kim** [comment]
I'll make a pull request adding that to the documentation.

**Comment by bobemoe** [comment]
Thanks @gary-kim I can confirm this fixes my issue :)

**Comment by pine-clover** [comment]
Anyone know the fix for nginx?
