### ISSUE TITLE
404 when not logged in and trying to access a private repo

### ISSUE THREAD

**Issue by bohwaz** [go-gitea/gitea#7472]
- Gitea version (or commit ref): 1.8.3

Gitea shows a 404 page when trying to access a private repo if you are not logged in.

We find that this is disturbing for users, as there is no suggestion that the user should log in to access the repo. Most users just report that the repo doesn't work or that the URL we sent them doesn't work.

The error page should show something more useful than just 404, like a message saying that they need to login in order to access the repo.

**Comment by lunny** [comment]
This is by designed for security reason.

**Comment by bohwaz** [comment]
I don't think it is? Private doesn't mean "secret" by any means?

And also it's quite a bad user experience.

**Comment by jolheiser** [comment]
This is the same way other projects handle it as well, like GitHub and Gitlab.

Private generally comes down to "I don't want other people (except maybe collaborators) to know this exists" for one reason or another.


One thing you could do is set `REQUIRE_SIGNIN_VIEW` to `true` in your `app.ini`  
This would force anyone to log in before viewing a repo anyways, so if they have access they'd get in. If not, a 404 is still received as it should be.

**Comment by bohwaz** [comment]
Interesting. Would that require people viewing public repos to log in as well?

**Comment by jolheiser** [comment]
Yes it would.

**Comment by bohwaz** [comment]
OK then it's not a solution, we still need to have public repos well… public :)
