### ISSUE TITLE
[Gitea.com] How to remove repo with server error 500?

### ISSUE THREAD

**Issue by curbengh** [go-gitea/gitea#7473]
- Gitea version (or commit ref): 1.10.0+dev-26-gf03e5b7c3
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No (Somehow gitea.io can mirror it just fine).
  - [ ] Not relevant
- Log gist:

## Description
I tried to create a repo to mirror https://gitlab.com/curben/urlhaus-filter last week on gitea.com. Until today, [the repo](https://gitea.com/curben/urlhaus-filter) is still inaccessible with server error 500. The repo is still listed on [my profile](https://gitea.com/curben) (initially created as a private repo), but I couldn't remove it.

I also tried gitea.io which can mirror it just fine. I also tried a new account on gitea.com and [no issue](https://gitea.com/koshtram/urlhaus-filter) as well.

**Comment by lunny** [comment]
That should be a bug of gitea when migrating when something wrong. If you like, I could help you to remove that on admin panel.

**Comment by weyusi** [comment]
> If you like, I could help you to remove that on admin panel.

yes, please.

**Comment by curbengh** [comment]
I haven't remove the account. Able to mirror/sync https://gitlab.com/curben/urlhaus-filter, but #7399 still persists.
