### ISSUE TITLE
Wrong binary download for Gitea 1.9

### ISSUE THREAD

**Issue by veita** [go-gitea/gitea#7479]
1.) Download https://dl.gitea.io/gitea/1.9/gitea-1.9-linux-amd64
2.) Run it.

=> Gitea's start page announces `Gitea Version: 1.10.0+dev-14-g33b1027c7`

**Comment by techknowlogick** [comment]
It’s the correct binary, just tagged with an incorrect version. Closing this as a duplicate issue.
