### ISSUE TITLE
Reference and close issues across repositories

### ISSUE THREAD

**Issue by sonallux** [go-gitea/gitea#748]
## Description

Github has a feature to reference and close issues across repositories [link](https://github.com/blog/1439-closing-issues-across-repositories)

Big projects with multiple repositories for different components would benefit a lot from this feature. So it would be cool to have this in Gitea too.

**Comment by donbecker** [comment]
I'm a big fan of Gitea and this would be a great feature to have.

**Comment by lunny** [comment]
In fact, all changes needed are in https://github.com/go-gitea/gitea/blob/master/modules/markup/html.go

**Comment by donbecker** [comment]
@lunny Does that mean this issue is currently working/resolved in the current version of Gitea?

**Comment by lunny** [comment]
@donbecker no. I just pasted a clue to resolve this.

**Comment by mrsdizzie** [comment]
Gitea has this feature now as well
