### ISSUE TITLE
Please support openshift build webhooks

### ISSUE THREAD

**Issue by bzed** [go-gitea/gitea#7488]
- Gitea version (or commit ref): master
- Git version: HEAD
- Operating system: Debian
- Database (use `[x]`):
  - [X] PostgreSQL
  - [X] MySQL
  - [X] MSSQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist: not relevant

## Description

Please support openshift build webhooks. See the generic webhook part in
https://docs.openshift.com/container-platform/4.1/builds/triggering-builds-build-hooks.html
 - the POST request needs a formatted yaml file as data.

Thanks,

Bernd

**Comment by titou10titou10** [comment]
+1
The specs of the webhook trigger for OpenSHift are here: https://docs.openshift.com/container-platform/3.11/dev_guide/builds/triggering_builds.html

It has to be an HTTP`POST`request with a`"Content-Type"` header of  `"application/yaml"` or `"application/json"`  and the following payload (Shown as yaml):

    git:
      uri: "<url to gitea repository>"
      ref: "<optional git reference>"
      commit: "<commit hash identifying a specific git commit>"
      author:
        name: "<author name>"
        email: "<author e-mail>"
      committer:
        name: "<committer name>"
        email: "<committer e-mail>"
      message: "<commit message>"
    env: 
       - name: "<variable name>"
         value: "<variable value>"

**Comment by scorbin** [comment]
+1
Don't want to use gitlab with openshift

**Comment by lunny** [comment]
PR is welcome for those who are familiar with openshift.
