### ISSUE TITLE
gitea admin repo-sync-releases: cannot use existing config

### ISSUE THREAD

**Issue by wiphi** [go-gitea/gitea#7490]
- Gitea version (or commit ref): 1.8.3
- Git version: 2.7.4
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No (no shell access)
  - [ ] Not relevant
- Log gist:

```
git@gitea:~$ gitea -c /etc/gitea/app.ini admin repo-sync-releases
2019/07/16 13:43:43 [W] Custom config '/usr/local/bin/custom/conf/app.ini' not found, ignore this if you're running first time
2019/07/16 13:43:43 [...s/setting/setting.go:725 NewContext()] [E] failed to create '/usr/local/bin/custom/conf/app.ini': mkdir /usr/local/bin/custom: permission denied
```

## Description
I want to resync my repositories releases. The config file is stored in `/etc/gitea/app.ini`. The Gitea bin is stored in `/usr/local/bin/gitea`
I tried `gitea -c /etc/gitea/app.ini admin repo-sync-releases` but gitea ignored my config file in the `-c` argument. Gitea always use it's own location.

## Workaround
I copied the `app.ini` file to the custom location, that gitea desired and than it works.

P.S. Thanks for this awesome software 🙏

**Comment by zeripath** [comment]
Have you tried putting the -c after the repo-sync-releases or the admin?

This issue should be fixed in 1.9 as that code has been rewritten.

**Comment by wiphi** [comment]
> 
> 
> Have you tried putting the -c after the repo-sync-releases or the admin?
> 
Sure :)
```
git@gitea:~# gitea admin repo-sync-releases -c /etc/gitea/app.ini
Incorrect Usage: flag provided but not defined: -c

NAME:
   Gitea admin repo-sync-releases - Synchronize repository releases with tags

USAGE:
   Gitea admin repo-sync-releases [arguments...]
2019/07/18 08:42:11 [...tea.io/gitea/main.go:59 main()] [E] Failed to run app with [gitea admin repo-sync-releases -c /etc/gitea/app.ini]: flag provided but not defined: -c
```
and
```
git@gitea:~# gitea admin -c /etc/gitea/app.ini repo-sync-releases
Incorrect Usage. flag provided but not defined: -c

NAME:
   Gitea admin - Command line interface to perform common administrative operations

USAGE:
   Gitea admin command [command options] [arguments...]

COMMANDS:
     create-user         Create a new user in database
     change-password     Change a user's password
     repo-sync-releases  Synchronize repository releases with tags
     regenerate          Regenerate specific files
     auth                Modify external auth providers

OPTIONS:
   --help, -h  show help

2019/07/18 08:45:04 [...tea.io/gitea/main.go:59 main()] [E] Failed to run app with [gitea admin -c /etc/gitea/app.ini re
po-sync-releases]: flag provided but not defined: -c
```
> This issue should be fixed in 1.9 as that code has been rewritten.

Then I look forward to try it again with 1.9.

**Comment by zeripath** [comment]
Damn sorry that didn't work.

**Comment by wiphi** [comment]
I've tried it again with Gitea 1.9.3 and now it works with `gitea -c /etc/gitea/app.ini admin repo-sync-releases` very fine. 
Thank you 👍
