### ISSUE TITLE
docs issue with ISSUE_INDEXER_QUEUE_TYPE

### ISSUE THREAD

**Issue by silverwind** [go-gitea/gitea#7491]
app.ini says possible values are `channel` or `levelqueue` for this option:

````
; Issue indexer queue, currently support: channel or levelqueue, default is levelqueue
ISSUE_INDEXER_QUEUE_TYPE = levelqueue
````

but further down, it mentions a `redis` value:

````
; When `ISSUE_INDEXER_QUEUE_TYPE` is `redis`, this will store the redis connection string.
ISSUE_INDEXER_QUEUE_CONN_STR = "addrs=127.0.0.1:6379 db=0"
````

So is that that possible values are actually `channel`, `levelqueue` or `redis`?

**Comment by lunny** [comment]
@silverwind sorry missed that. #7494 will fix this.
