### ISSUE TITLE
Delete a file via web not giving errors, not allowing new branch if source branch protected

### ISSUE THREAD

**Issue by richmahn** [go-gitea/gitea#7492]
A few errors in v1.9-rc2, in that the Delete UI will not report an error if a bad filename, existing branch, etc. are given as then it throws an error in the template, since it uses the wrong template page for errors. It also won't let you delete and commit to a copy of the source branch if the source branch is protected, as it says that the new branch is protected, which it isn't.

**Comment by lunny** [comment]
Fixed by #7478
