### ISSUE TITLE
[Feature Request] badgerdb for database

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [go-gitea/gitea#7497]
I'm curious if anyone views this as a possability, [badgerdb](https://github.com/dgraph-io/badger) is a very fast embeddable open source kv database written in pure go. It seems like if it were implemented it would give users the ability to use an awesome database without having to install one and set it up.

**Comment by lunny** [comment]
Gitea depends on xorm which only supports DBMS so I don't think it's possible.
