### ISSUE TITLE
Remove comments in app.ini.sample?

### ISSUE THREAD

**Issue by silverwind** [go-gitea/gitea#7498]
Documentation in [`app.ini.sample`](https://github.com/go-gitea/gitea/blob/master/custom/conf/app.ini.sample) often runs out of sync with the [cheat sheet](https://github.com/go-gitea/gitea/blob/master/docs/content/doc/advanced/config-cheat-sheet.en-us.md#indexer-indexer) like for example https://github.com/go-gitea/gitea/issues/7491.

I'm thinking we might be better off removing all comments in the file and use the cheat sheet as the single source of truth, eliminating the need to update both.

**Comment by lunny** [comment]
Maybe we should generate cheat sheet by app.ini.sample. :)

**Comment by zeripath** [comment]
We could generate both from the code :-p

**Comment by mrsdizzie** [comment]
I think it would be best to move most things from config file to database per the discussed roadmap and then the config file would be left very small and could be easily documented in one place and would probably not be updated much

**Comment by lunny** [comment]
@zeripath I like the idea.

**Comment by lunny** [comment]
@mrsdizzie right.

**Comment by lunny** [comment]
Generating comments are better than removing them. So maybe we could close this or change the title.
