### ISSUE TITLE
Deployment key has access to all public repositories

### ISSUE THREAD

**Issue by asenci** [go-gitea/gitea#750]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

Note sure if this was the intended behavior, but adding a deployment key to a repository will allow access to all public repositories. Even with "Require Sign In View" enabled.

Example scenarios:
Public repository with deployment key: https://try.gitea.io/asenci/test1
Public repository with no deployment key: https://try.gitea.io/asenci/test2
Private repository with no deployment key: https://try.gitea.io/asenci/test3
Private repository with deployment key: https://try.gitea.io/asenci/test4

I would expect the deployment key to have access to "test1" and "test4", but it actually has access to "test2" as well:

```
$ git clone git@try.gitea.io:asenci/test1.git
Cloning into 'test1'...
remote: Counting objects: 3, done.
remote: Total 3 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (3/3), 229 bytes | 0 bytes/s, done.
Checking connectivity... done.
```
```
$ git clone git@try.gitea.io:asenci/test2.git
Cloning into 'test2'...
remote: Counting objects: 3, done.
Receiving objects: 100% (3/3), done.
remote: Total 3 (delta 0), reused 0 (delta 0)
Checking connectivity... done.

```
```
$ git clone git@try.gitea.io:asenci/test3.git
Cloning into 'test3'...
Gitea: Key access denied
Deploy key access denied: [key_id: 26, repo_id: 299]
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

```
```
$ git clone git@try.gitea.io:asenci/test4.git
Cloning into 'test4'...
remote: Counting objects: 3, done.
Receiving objects: 100% (3/3), done.
remote: Total 3 (delta 0), reused 0 (delta 0)
Checking connectivity... done.

```

This is specially confusing with "Require Sign In View" enabled, since I wouldn't expect "test2" to be accessible, despite it being a "public" repository.

For reference, Gogs has the same behavior:
https://github.com/gogits/gogs/issues/4058

**Comment by tboerger** [comment]
A public repo don't need any key at all. So I would say it's the expected behavior

**Comment by asenci** [comment]
With "Require Sign In View" disabled I would agree, since you have access to the repositories via HTTP anyway. But wouldn't one expect stricter access control with "Require Sign In View" enabled?

**Comment by asenci** [comment]
Just did some tests on GitHub and Bitbucket and they showed the same behavior, so it seems there is a consensus about this. :)

**Comment by lunny** [comment]
So this is not an issue and we can close this?

**Comment by asenci** [comment]
I believe so. Sorry for the trouble.
