### ISSUE TITLE
Adding a deploy key from copy/paste doesn't work

### ISSUE THREAD

**Issue by bohwaz** [go-gitea/gitea#7500]
- Gitea version (or commit ref): 1.8.3

## Description

If I do a `cat ~/.ssh/id_rsa.pub` and copy paste it in Gitea to the textarea to add a new deploy key, I get the error "Can not verify your SSH key: extractTypeFromBase64Key: invalid key format: illegal base64 data at input byte 168"

If I remove the line break in the middle, it works.

It seems that Gitea doesn't handle line returns inside keys.

**Comment by silverwind** [comment]
SSH Keys have no linebreaks in the middle, it's probably your terminal erronously adding them. Does adding the same faulty key on GitHub work, btw?

**Comment by bohwaz** [comment]
> SSH Keys have no linebreaks in the middle, it's probably your terminal erronously adding them. Does adding the same faulty key on GitHub work, btw?

Yes it works on github and gitlab.

> It may be possible that we can prevent such errors by stripping any `\r?\n` sequences from the added key on save because those should never appear in a key afaik.

Would be a good solution :)

**Comment by bohwaz** [comment]
Great, thank you :)
