### ISSUE TITLE
[Feature Request] Support proxy protocol

### ISSUE THREAD

**Issue by manuelluis** [go-gitea/gitea#7508]
Support proxy protocol connections for HTTP/HTTPS and SSH, so we can have the originating ip in the gitea log if we are behind a proxy.

https://www.haproxy.com/blog/haproxy/proxy-protocol/

**Comment by zeripath** [comment]
OK @manuelluis I have put a PR up to support this - but I think we need to be clear why Gitea needs to be aware of the proxy itself.

**Comment by manuelluis** [comment]
If gitea is behind a proxy like haproxy or nginx and we like to have the original ip in the gitea logs, we can use also the `X-Forwarded-For` header if the connections are HTTP or the proxy handle the HTTPS connections.
But in the case of SSH connections or if gitea handle the HTTPS and we don't break the SSL in the proxy, with the proxy protocol  we can have the original ip.

**Comment by zeripath** [comment]
So I think my PR does do that IIRC
