### ISSUE TITLE
Option to auto-watch on first interaction

### ISSUE THREAD

**Issue by guillep2k** [go-gitea/gitea#7512]
- Gitea version (or commit ref): Gitea version 1.8.3+2-g11f6ed4 built with go1.12.6 : pam, bindata, sqlite, sqlite_unlock_notify
- Git version: 1.8.3.1
- Operating system: CentOS 7
- Database (use `[x]`):
  - [*] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:

In the spirit of `AUTO_WATCH_NEW_REPOS`, it would be nice to have options to automatically add the user as a watcher on first interactions, like:

- `AUTO_WATCH_ON_CHANGES` = `true`: any write operation on a server's repository (like push) will subscribe the user to the repository.
- `AUTO_WATCH_ON_CLONE` = `true`: clone (u other relevant operations) will subscribe the user to the repository.
- `AUTO_ORG_MEMBER_VISIBLE` = `true`: member is visibile by default.

**Comment by 6543** [comment]
i think this is related: https://github.com/go-gitea/gitea/issues/8243

**Comment by lunny** [comment]
They should be the same.

**Comment by strk** [comment]
It should be "auto-subscribe", as "watch" is for all activities of a repository ?

**Comment by guillep2k** [comment]
> 
> 
> It should be "auto-subscribe", as "watch" is for all activities of a repository ?

@strk My original idea was to watch the entire repo after the users commits/pushes anything to it. It's implemented in #7657, but that PR is not up-to-date.

This is not the same as #7512. This is for subscribing to repos when commiting to them, while #8243 is for subscribing to issues that one creates. Sorry about my lousy description here.

**Comment by guillep2k** [comment]
This has been implemented to a satisfactory level. Suscription upon cloning could be implemented as well, but that would be very difficult to do as git has no hook to catch a clone operation (it had one but it was removed long ago).

Closing this.

**Comment by 6543** [comment]
@guillep2k think this is fine for now :D
