### ISSUE TITLE
models.SetEngine: Failed to connect to database: Unknown database type

### ISSUE THREAD

**Issue by plaidshirtakos** [go-gitea/gitea#7514]
- Gitea version (or commit ref): Gitea version 1.5.0 built with: bindata, sqlite
- Git version: git version 2.17.1
- Operating system: 18.04.2 LTS (Bionic Beaver)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x ] No
  - [ ] Not relevant
- Log gist:

## Description
I get error message for command gitea `admin change-password --username myusername --password asecurenewpassword` and command `gitea admin create-user --name newuser --password newpw --email mymail@mymail.com --admin 1` too .

Message:

> models.SetEngine: Failed to connect to database: Unknown database type:
> 2019/07/18 06:27:50 [I] XORM Log Mode: Console(Info)

## Screenshots
Not relevant.

**Comment by lunny** [comment]
Could you paste your database settings in app.ini

**Comment by plaidshirtakos** [comment]
@lunny :
```
[database]
DB_TYPE  = mysql
HOST     = 127.0.0.1:3306
NAME     = gitea
USER     = gitea
PASSWD   = qwert
SSL_MODE = disable
PATH     = data/gitea.db
```

**Comment by zeripath** [comment]
I suspect your Gitea admin command is not finding your config, the -c option should allow you to set it but it depends on your Gitea version.

Btw if you are genuinely using Gitea 1.5 I strongly recommend you update. There are multiple security issues in old versions of Gitea and you should update to at least 1.8 or one of the 1.9-rcs

**Comment by plaidshirtakos** [comment]
@zeripath : I upgraded to `gitea-1.8.3`, but facing still the same issue.

> models.SetEngine: Failed to connect to database: Unknown database type:

**Comment by zeripath** [comment]
The likely issue is that the Gitea admin command cannot find your config file. Either you have to set the -c option or environment variables as appropriate.

That is to be explicit you must:

```
gitea admin change-password -c ABSOLUTE_PATH_TO_CONFIG_FILE
```

**Comment by plaidshirtakos** [comment]
Is it about _app.ini_ conf file?

**Comment by zeripath** [comment]
Yes.
