### ISSUE TITLE
An API question

### ISSUE THREAD

**Issue by hsowan** [go-gitea/gitea#7515]
![image](https://user-images.githubusercontent.com/26451706/61436310-1af05c00-a96d-11e9-8d88-e28e224eb876.png)

the api would list **all** repos that the authenticated user owns or has access to?

* no pagination? 
* how to list **personal** repos (username/repo_name)

**Comment by davidsvantesson** [comment]
/repos/search allow to filter for repos for a particular user.

**Comment by hsowan** [comment]
> /repos/search allow to filter for repos for a particular user.

is there pagination for listing repos?

**Comment by sapk** [comment]
Hi @hsowan 

The api would list all repos that the authenticated user **owns** or **is member**.
This api call should correspond to the repo list you see on the right of the home page (like https://try.gitea.io/) under the default `All` tab
![image](https://user-images.githubusercontent.com/4052400/61504307-37c37880-a9db-11e9-9f9d-9df8acb79bdd.png)

If you want more details on the func behind the API call it all start here: https://github.com/go-gitea/gitea/blob/e0d6d2f97816f972d408308c740bacc450584e00/routers/api/v1/user/repo.go#L60

This specific api call doesn't support pagination but the underlining function support it and could be implemented https://github.com/go-gitea/gitea/blob/e0d6d2f97816f972d408308c740bacc450584e00/models/repo.go#L1993

You can play with the api on the try.gitea.io instance : https://try.gitea.io/api/swagger#/user/userCurrentListRepos

You can generate AccessToken on https://try.gitea.io/user/settings/applications to log on the API easely.

I hope it answer your question.

**Comment by sapk** [comment]
And for the `/repos/search` api call it does support paging via `limit` and  `page` pararms https://try.gitea.io/api/swagger#/repository/repoSearch

**Comment by hsowan** [comment]
> And for the `/repos/search` api call it does support paging via `limit` and `page` pararms https://try.gitea.io/api/swagger#/repository/repoSearch

Thank you very much

**Comment by hsowan** [comment]
> /repos/search allow to filter for repos for a particular user.

thanks
