### ISSUE TITLE
Use organization/user avatatar on Github mirrors

### ISSUE THREAD

**Issue by alexanderadam** [go-gitea/gitea#7526]
## Description

Just a nice to have: now, that each repository can have a logo, it would be nice to fetch the image from the owner (organisation or user) on mirrored repositories.

PS: thank you for your work!

**Comment by zeripath** [comment]
I think this is a duplicate issue. It's not a simple thing - you can't just use the original repository image. You need to mark the image in some way to say that this is not the original.

When you say mirror do you mean fork? Or an external mirror?

**Comment by alexanderadam** [comment]
Thank you for responding so fast @zeripath.

I mean external mirror but now that you wrote it, it also makes sense on forks I guess.
Can you please point me to the issue that it's duplicated from (I wasn't able to find it so I guess I searched somehow wrong)?

Why exactly have to image to be marked? Why should an image be handled differently if it came from a mirror?

**Comment by lunny** [comment]
owners' avatars or organization avatars are not repositories' avatars. I don't think it should be copied.

**Comment by alexanderadam** [comment]
> owners' avatars or organization avatars are not repositories' avatars

@lunny GitHub doesn't support this feature but often they are, right?
This seems to be true even for gitea:

![Screenshot_20190719_092845](https://user-images.githubusercontent.com/372620/61517549-ca7a0c80-aa07-11e9-9ef6-4e2e20a40124.png)

**Comment by lunny** [comment]
I will mark this as `won't fix` because github didn't support repository avatar but gitea supported. So when migrated a repository we should not copy owners' or organizations' avatars.
