### ISSUE TITLE
Create organization UI broken

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#7527]
![image](https://user-images.githubusercontent.com/81045/61533667-1bb5ea80-aa60-11e9-8396-16bb04bf1308.png)

**Comment by lafriks** [comment]
Could be that you are having old css? (Tyr Ctrl+f5)

**Comment by techknowlogick** [comment]
This is what I see on gitea.com:
![Screen Shot 2019-07-19 at 1 59 14 PM](https://user-images.githubusercontent.com/164197/61555441-6b2ef300-aa2d-11e9-982b-d8d0530b4e03.png)

**Comment by zeripath** [comment]
Seems to be correct on try.gitea.io too.

**Comment by lunny** [comment]
Force refresh resolved the problem.
