### ISSUE TITLE
Gitea cannot be installed on posgresql schema different to public

### ISSUE THREAD

**Issue by Rizzen59** [go-gitea/gitea#7534]
- Gitea version (or commit ref): 1.8.3 and 1.9.0-rc2
- Git version: 2.22.0
- Operating system: CentOS 7
- Database (use `[x]`):
  - [x] PostgreSQL (11)
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] Not relevant
  - [ ] No
- Log gist:

## Description
If default schema for user is different of public (the best way), schema  is created on gitea on the user default schema.
On boot, the check for existing column id on table version is executed on schema public , then gitea try to add column but column already exist on user's default schema and crash.

Log : 
SELECT column_name FROM INFORMATION_SCHEMA.COLUMNS WHERE table_schema = $1 AND table_name = $2 AND column_name = $3 [**public** version id]

**Comment by lafriks** [comment]
I think there was issue for this already, there was even draft PR to fix this but it never got finished

**Comment by lunny** [comment]
duplicated with #5152
