### ISSUE TITLE
Cant open repository after restart

### ISSUE THREAD

**Issue by paulartjomow** [go-gitea/gitea#7538]
- Gitea version (or commit ref): 1.4.0
- Git version: 2.11.0
- Operating system: Raspbian GNU/Linux 9 (stretch)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:
```
[Macaron] 2019-07-19 18:09:44: Started GET /Spigot/Lobby-System for 90.146.43.28
[Macaron] 2019-07-19 18:09:44: Completed GET /Spigot/Lobby-System 404 Not Found in 170.215696ms
```
## Description

I can't open a repository after restart. The error code on the webinterface is 500 but in the console its 404.

## Screenshots
![image](https://user-images.githubusercontent.com/24830552/61552924-6ed86f00-aa59-11e9-933f-859b769696f7.png)

**Comment by lafriks** [comment]
Check gitea.log for error

**Comment by Prixix** [comment]
`2019/07/19 18:31:53 [...ules/context/repo.go:577 func1()] [E] GetBranchCommit: object does not exist [id: 41e8f4c72c2012772a026e6879b3a49c80d49e7b, rel_path: ]` Can you help me with that?

**Comment by lafriks** [comment]
You should really update to latest Gitea version as 1.4.0 is quite old. Otherwise it looks something has broken in middle of git pushing and git data folder could be needed to be repaired

**Comment by Prixix** [comment]
Okay, updating gitea was a good idea but it doesnt fixed the problem. I deleted the whole repository and now it works.
