### ISSUE TITLE
Can't show "Issues" page (Error 500)

### ISSUE THREAD

**Issue by thibaultmeyer** [go-gitea/gitea#754]
- Gitea version (or commit ref): 1.0.0+154-g8555e888
- Git version: 2.11.0
- Operating system: CentOS 7
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No --> _Cause try.gitea.io is not up to date_
  - [ ] Not relevant
- Log gist:

## Description
Just go to _/issues_ or _/ORG_NAME/REPO_NAME/issues_, _/pulls_, ...

```
2017/01/25 07:19:28 [...routers/user/home.go:286 Issues()] [E] Issues: Find: no such column: true
2017/01/25 07:19:28 [...routers/user/home.go:286 Issues()] [E] Issues: Find: no such column: true
2017/01/25 07:19:30 [...routers/user/home.go:286 Issues()] [E] Issues: Find: no such column: true
2017/01/25 07:19:33 [...routers/user/home.go:286 Issues()] [E] Issues: Find: no such column: false
2017/01/25 07:29:12 [...outers/repo/issue.go:228 Issues()] [E] Issues: Find: no such column: false
2017/01/25 07:31:16 [...routers/user/home.go:286 Issues()] [E] Issues: Find: no such column: false
2017/01/25 07:31:18 [...routers/user/home.go:286 Issues()] [E] Issues: Find: no such column: false
```

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/41307783-can-t-show-issuee-page-error-500?utm_campaign=plugin&utm_content=tracker%2F47456670&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F47456670&utm_medium=issues&utm_source=github).

**Comment by lunny** [comment]
It maybe caused by #530

**Comment by thibaultmeyer** [comment]
Ok @lunny, I rebuild Gitea and look if issue is fixed

**Comment by thibaultmeyer** [comment]
Nope, I always get error 500


![image](https://cloud.githubusercontent.com/assets/1005086/22282551/7701d892-e2dd-11e6-8b98-ae1501fa49dc.png)

```
2017/01/25 09:04:33 [...routers/user/home.go:286 Issues()] [E] Issues: Find: no such column: false
2017/01/25 09:04:34 [...routers/user/home.go:286 Issues()] [E] Issues: Find: no such column: false
2017/01/25 09:04:35 [...routers/user/home.go:286 Issues()] [E] Issues: Find: no such column: false
2017/01/25 09:04:36 [...routers/user/home.go:286 Issues()] [E] Issues: Find: no such column: false
2017/01/25 09:04:37 [...routers/user/home.go:286 Issues()] [E] Issues: Find: no such column: false
2017/01/25 09:04:39 [...routers/user/home.go:286 Issues()] [E] Issues: Find: no such column: false
2017/01/25 09:04:47 [...routers/user/home.go:286 Issues()] [E] Issues: Find: no such column: false
2017/01/25 09:05:03 [...routers/user/home.go:286 Issues()] [E] Issues: Find: no such column: false
```

**Comment by lunny** [comment]
Yes, I'm trying to fix this.
