### ISSUE TITLE
Webhook for Sentry releases

### ISSUE THREAD

**Issue by alexanderadam** [go-gitea/gitea#7548]
## Release webhook

Sentry supports release creation via webhooks (In Sentry go to the `project` > `releases` > scroll to `webhook`).
![webhooks](https://user-images.githubusercontent.com/372620/61591616-014b5080-abc9-11e9-9403-16513224bce0.png)

This webhook [just needs the URL and JSON structure like this](https://docs.sentry.io/workflow/releases/?platform=browser#using-the-api) ([there are more parameters that might be interesting (i.e. `authors`, `commitCount` and `shortVersion` [for the short hash]) in the official API](https://docs.sentry.io/api/releases/post-organization-releases/))
```JSON
{
  "author_name": "Author Name",
  "version": "2da95dfb052f477380608d59d32b4ab9",
  "refs": [{
    "repository":"owner-name/repo-name",
    "commit":"2da95dfb052f477380608d59d32b4ab9",
    "previousCommit":"1e6223108647a7bfc040ef0ca5c92f68ff0dd993"
  }],
 "projects":["my-project","my-other-project"]
}
```

`projects` is something that has to be added manually though because these are the names of related Sentry projects.

## Commit webhook

Similarly to the release webhook it would be good being able to [push raw commit information as well](https://docs.sentry.io/workflow/releases/?platform=browser#alternatively-without-a-repository-integration):

```json
{
  "commits": [
    {
    "patch_set": [
      {"path": "path/to/added-file.html", "type": "A"},
      {"path": "path/to/modified-file.html", "type": "M"},
      {"path": "path/to/deleted-file.html", "type": "D"}
    ],
    "repository": "owner-name/repo-name",
    "author_name": "Author Name",
    "author_email": "author_email@example.com",
    "timestamp": "2018-09-20T11:50:22+03:00",
    "message": "This is the commit message.",
    "id": "8371445ab8a9facd271df17038ff295a48accae7"
    }
  ]
}
```

**PS:** maybe it would make sense to support [a generic template based solution for webhooks like proposed in issue 1089](https://github.com/go-gitea/gitea/issues/1089)?

**PPS:** [A gitea plugin for Sentry would be nice as well](https://github.com/getsentry/sentry/issues/15738). So it would be nice considering a Sentry PR if you are fluent in Python. :wink:

**Comment by MrMoronIV** [comment]
Is this something that has been implemented? Would be very interested to use this for my local sentry installation!

**Comment by lunny** [comment]
@MrMoronIV Nobody are working on this.
