### ISSUE TITLE
Webhook for XMPP / Jabber

### ISSUE THREAD

**Issue by alexanderadam** [go-gitea/gitea#7549]
It would be nice to have a XMPP webhook.
Maybe work from [this project](https://github.com/opthomas-prime/xmpp-webhook) could be used as an inspiration.

PS: maybe it would make sense to support a generic template based solution for webhooks?

**Comment by lunny** [comment]
You could write a bridge service to convert a gitea webhook to XMPP.

**Comment by genofire** [comment]
I have already write one - but that is not the same ... e.g. here is also Matrix support, why should gitea not merge a xmpp support?

**Comment by poVoq** [comment]
https://gitlab.com/navlost.eu/xmpp/components/webhooks

Supports Gitea now.
