### ISSUE TITLE
Gitea 1.7 and 1.8 just segfault: Ubuntu 14.04

### ISSUE THREAD

**Issue by philiplb** [go-gitea/gitea#7551]
- Gitea version (or commit ref): 1.7.6 and 1.8.3
- Git version:  2.22.0
- Operating system: Ubuntu 14.04, amd64
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist: N/A

## Description

I'm running Gitea 1.6.3 just fine on an Ubuntu 14.04 amd64 VM. I just wanted to upgrade to Gitea 1.8.3 but the only thing I get is this:

> Segmentation fault

Nothing more, no stack trace.

The same goes for Gitea 1.7.6 which I just tried afterwards.

Anything I could do here to at least get a stack trace or any more information?

**Comment by lafriks** [comment]
I think golang compiler does not support it anymore

**Comment by philiplb** [comment]
Oh, that would be a little unfortunate. I'm a bit stuck with this machine on Ubuntu 14.04 and want to upgrade it to Ubuntu 20.04 as soon as it's released. This would mean that I'm stuck with Gitea 1.6 until then.

**Comment by lafriks** [comment]
You can compile Gitea yourself from source using older golang compiler version (golang 1.9 should probably work). Check docs.gitea.io on how to do that

**Comment by philiplb** [comment]
Thank you for the answer. I successfully compiled from source with Go 1.11 and that binary worked.

Then I found my actual problem: wget failed a few times yesterday and my gitea-1.8.3-linux-amd64 was incomplete. I overlooked the successful download gitea-1.8.3-linux-amd64.3. So I can report, that the actual release binary just works fine as well with Ubuntu 14.04. m(
