### ISSUE TITLE
Syntax highlighting does not work in 1.9rc2

### ISSUE THREAD

**Issue by fincham** [go-gitea/gitea#7559]
- Gitea version (or commit ref): 1.9.0+rc2-1-ga29e667ef built with GNU Make 4.1, go1.12.7 : bindata,
sqlite, sqlite_unlock_notify
- Git version: 2.17.1
- Operating system: Ubuntu Bionic x86_64
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant

## Description

In this release the code highlighting does not activate when viewing files, even though index.js seems to call it. The `<code>` element ends up with an empty class string and no highlighting occurs. 

Downgrading to 1.8.3 fixes the problem.

**Comment by silverwind** [comment]
I can see this on try.gitea.io [here](https://try.gitea.io/silverwind/updates/src/branch/master/updates.js). I suspect it might be related to the recent jQuery update on the 1.9 branch.

**Comment by silverwind** [comment]
Seems like some kind of race condition with the highlight. If I do a no-cache reload in Firefox (CTRL-Shift-R), it highlights correctly.

**Comment by fincham** [comment]
Thanks for checking that. try.gitea.io was too slow / broken for me to find any actual files yesterday to confirm :(

**Comment by archtaurus** [comment]
i put  these to solve this problem for now ...
```
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.8/styles/github.min.css">
<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.8/highlight.min.js"></script>
<script>hljs.initHighlightingOnLoad();</script>
```

**Comment by fincham** [comment]
Hi there,

I'm now on 1.9.3 and this issue is still present, highlighting only activates maybe ~ 50% of the time on page loads :(

**Comment by lunny** [comment]
Could you try to clean the cache of browser?
