### ISSUE TITLE
Split view diff  with arc-green theme have white background 

### ISSUE THREAD

**Issue by relta-c** [go-gitea/gitea#7568]
- Gitea version (or commit ref):  v1.9.0-rc2 
- Git version: 2.16.4-lp151.3.4
- Operating system: openSUSE Leap 15.1
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes [ - here using arc-green](https://try.gitea.io/relta/dark-split-view/commit/46ad0370bfafa97d7e3abbb081fd44c8b3338b64?style=split)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
Split view diff with arc-green will display white background in added line.
I'm not really a web developer so I don't really know much about CSS and stuff
but after digging around a bit it seem to be a result from this line in `arc-green.less`:

`.repository .diff-file-box .code-diff-split tbody tr.add-code td:nth-child(1),`
`.repository .diff-file-box .code-diff-split tbody tr.add-code td:nth-child(2),`
 **_`.repository .diff-file-box .code-diff-split tbody tr.del-code td:nth-child(3),`_** <<
`.repository .diff-file-box .code-diff-split tbody tr.del-code td:nth-child(4),`
`.repository .diff-file-box .code-diff-split tbody tr.del-code td:nth-child(5),`
`.repository .diff-file-box .code-diff-split tbody tr.del-code td:nth-child(6) {`
`    background-color: #2a2e3a;`
`}`

Change it to 
 `.repository .diff-file-box .code-diff-split tbody tr.add-code td:nth-child(3),`
seem to fix the issue.

## Screenshots

![Screenshot_20190723_014402](https://user-images.githubusercontent.com/51981091/61656649-c3c1f280-acb0-11e9-9e81-758c26048721.png)

**Comment by silverwind** [comment]
Probably a regression from https://github.com/go-gitea/gitea/pull/7279.
