### ISSUE TITLE
[Branch View] [Bug] Restore Branch Button dont work

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#7569]
The Restore Branch Button dont work on Firefox (Linux/68.0.1 x64)

testet on Gitea 1.10

**Comment by 6543** [comment]
@lunny please  add the kind/bug  label so i can rename the issue name

**Comment by 6543** [comment]
http://localhost:3000/test/hometest/branches/restore?branch_id=22&name=merge-calcle produce page 404 is api brocken?

**Comment by techknowlogick** [comment]
It may 404 for GET requests, I believe it only accepts POST

**Comment by lunny** [comment]
Cannot reproduce on macOS Chrome and Firefox.

**Comment by 6543** [comment]
I'll test it on Windows and two different Linux systems today ...

**Comment by 6543** [comment]
Version: 1.10.0+dev-210-gc9546d4cd

System  |  Browser  |  Worked  |  Didn't 
----------- | ------------  | ----------- |  --------
5.2.8-1-MANJARO | Chrome 76 (64-Bit) | x | 
5.2.8-1-MANJARO | Chromium 76 (64-Bit) | x  |
5.2.8-1-MANJARO | Falkon 3.1.0 (QtWebEngine 5.13.0) | x   |
5.2.8-1-MANJARO | Firefox 68.0.1 (64-Bit) |   | x
5.2.8-1-MANJARO | Firefox Developer Ed. 69.0b12 (64-Bit) |   | x


WIP...

**Comment by 6543** [comment]
there is no pattern :(

**Comment by 6543** [comment]
it realy looks like Linux + Firefox dont open the link as POST but as GET request!

**Comment by lunny** [comment]
System  |  Browser  |  Worked  |  Didn't 
----------- | ------------  | ----------- |  --------
MacOS 10.14.5 | Chrome 76 (64-Bit) | x | 
MacOS 10.14.5 | Firefox 68 (64-Bit) | x  |
MacOS 10.14.5 | Safari 12.1.1 (64-Bit) | x  |

**Comment by 6543** [comment]
tested with current version https://github.com/go-gitea/gitea/commit/8a828500e689b7958e050ebd2dc46d380c3d6ae6

System: Linux 5.2 | Manjaro | Firefox 69.0.1 (64-Bit)

result: still exist

**Comment by 6543** [comment]
tested with e80fe201c0e7b1f7a73aa932d4a02068e044f0ce still exist :(

**Comment by 6543** [comment]
gone with **fomantic** :+1:
