### ISSUE TITLE
Organization created by Admin

### ISSUE THREAD

**Issue by lcges** [go-gitea/gitea#757]
- Gitea version (or commit ref): gitea version 1.0.1
- Git version: git version 2.11.0
- Operating system: FreeBSD 11.0
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant

Now the organization is created by the user and administrator.
A good option will be disable the user and give possibility only for the administrator.
Bring a more organized in small groups.

**Comment by lunny** [comment]
This should be resolved by https://github.com/go-gitea/gitea/pull/1763. I will close this and please feel free to reopen it.
