### ISSUE TITLE
Not able to override default logo

### ISSUE THREAD

**Issue by adpande** [go-gitea/gitea#758]
- Gitea version (or commit ref): 1.0.1
- Operating system: Ubuntu 16.04
- Database (use `[x]`): SQLite
- Can you reproduce the bug at https://try.gitea.io: Not relevant

## Description
I am not able to change the default gitea icon in top navigation bar. I have posted this on gitter channel and as per suggestions tried to override them in custom folder.
@bkcsoft has suggested to replace custom/public/img/gitea-large-resize.png and custom/public/img/gitea-lg.png. The logo in the menu-bar is gitea-lg.png.
But this is not working.
...

**Comment by strk** [comment]
Did you build gitea with the `bindata` tag ? Try w/out.
See #529

**Comment by Ahed91** [comment]
without `bindata` tag , I think it is not possible to override the public folder (when you create custom/public/img/favicon.png)
You can only overwrite robots.txt file (when you create custom/robots.txt)
templates, options, conf  are working correctly on 1.0.1

**Comment by tboerger** [comment]
This will be solved when https://github.com/go-gitea/gitea/pull/782 gets merged.
