### ISSUE TITLE
Wrong swagger api for AuthorizationHeaderToken  (apiKey)

### ISSUE THREAD

**Issue by hsowan** [go-gitea/gitea#7582]
![image](https://user-images.githubusercontent.com/26451706/61696155-689f0700-ad67-11e9-857e-c1692a972092.png)

The header should be `Authorization: token {token}`

**Comment by zeripath** [comment]
This is not simple to fix - the issue is that swagger generates this information and doesn't provide a way of adding token by default.

We could add a description to the AuthorizationHeader suggesting that people prepend with "token "
