### ISSUE TITLE
LDAP sync incorrectly assigns user attributes

### ISSUE THREAD

**Issue by polymeter** [go-gitea/gitea#7583]
- Gitea version (or commit ref): 1.9.0-rc2 (also reproduced on 1.8.3)
- Git version: 2.20.1
- Operating system: Debian 10 (buster)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant

## Description
I have an auth source with LDAP via BindDN configured. When User Sync is enabled and runs, the profile fields are always set to
* Full name = *username*
* Email = *username*@localhost

for all LDAP users, although proper values are available. This happens for existing users (fields are overwritten) as well as newly created ones.

For new (not yet synced) users, the fields are correctly populated on first login, so the LDAP config seems to be fine.

**Comment by roycec** [comment]
I encounter a similar problem (not using user sync). I can once correct the mail domain, but when I try to change something else in the profile, I get the error 

> e-mail already in use 

When I delete the user, in hope to recreate it with a new login, the error is the same

```
2019/08/30 16:14:44 ...dels/login_source.go:707:UserSignIn() [W] Failed to login 'user.name' via 'LDAP': e-mail already in use [email: user.name@ourcompany.de]
2019/08/30 16:14:44 routers/user/auth.go:165:SignInPost() [I] Failed authentication attempt for user.name from 10.xx.xx.xx
```

Gitea version: 1.9.1 
OS version: RHEL 7.6
Database: MySQL

**Comment by roycec** [comment]
ok, I found an "error" in my side ... the user I created as admin had the same email address than another (LDAP) user. So there was a dupicate mail address already configured. I think this solved my issue.

**Comment by lunny** [comment]
@polymeter could you also check if you have a duplicated email addresses.
