### ISSUE TITLE
Long delay on startup

### ISSUE THREAD

**Issue by beppler** [go-gitea/gitea#7584]
- Gitea version (or commit ref): 1.8.3
- Git version: 2.20.1
- Operating system: Debian 10
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X] No
  - [ ] Not relevant
- Log gist: https://gist.github.com/beppler/ef6e4dcc2ec2b88aa6d036d4037fc6ad

## Description

When starting gitea there are a long delay (apox 3 minutes) between the first logs and start listening requests.

This is not the same of #5953 because it happens always, not only when Gitea is upgraded.

**Comment by lunny** [comment]
Could you change the log level to trace and enable xorm log?

**Comment by zeripath** [comment]
Do you have repository indexing on?

**Comment by beppler** [comment]
Yes, I have repository indexing and it is using bleve.

```
[indexer]
ISSUE_INDEXER_PATH   = /var/opt/gitea/data/indexers/issues.bleve
REPO_INDEXER_ENABLED = true
REPO_INDEXER_PATH    = /var/opt/gitea/data/indexers/repos.bleve
```

**Comment by beppler** [comment]
Also, xorm.log for the period is on https://gist.github.com/beppler/e55dfbab135170eaa505395137697a88

**Comment by zeripath** [comment]
I bet the delay is bleve starting.

**Comment by lunny** [comment]
`bleve` should start asynchronously. see https://github.com/go-gitea/gitea/blob/8ec659722df32048561c713f2d533a20a7f0d5ef/routers/init.go#L97, the parameter is false.

**Comment by zeripath** [comment]
In my work on making Gitea respond to sign-up gracefully - these certainly seem to cause Gitea to lock and I've had to wrap the initialisation in a goroutine.

**Comment by beppler** [comment]
I changed the log level to Trace, [here](https://gist.github.com/beppler/bbdbb6cabf974ed55fce96f8f16d26bf) is the log generated during startup.

**Comment by zeripath** [comment]
@beppler it's the repo indexer.

**Comment by lunny** [comment]
>
2019/07/29 14:48:12 [T] Doing: DeletedBranchesCleanup
2019/07/29 14:50:55 [I] SQLite3 Supported

It's not indexer, it's cron taskes. Some taskes could be configed run at start but not on new go rountines.

**Comment by wxiaoguang** [comment]
Outdated
