### ISSUE TITLE
[Features] Can OATH2 Customize Service Providers

### ISSUE THREAD

**Issue by xlouc** [go-gitea/gitea#7588]
- Gitea version (or commit ref): 1.9.0-rc2
- Git version: 1.8.3.1
- Operating system: CentOS
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
Can OATH2 Authentication Provide Custom Service Providers instead of Using Service Providers such as Github?
...

**Comment by Project0** [comment]
Its possible to use an own OpenID connect provider, what do you want more? ;-) 
![image](https://user-images.githubusercontent.com/2286479/61787476-1fef5880-ae10-11e9-966d-b06c2d542532.png)

**Comment by mamying** [comment]
OK, that's enough for me.
