### ISSUE TITLE
CJK languages for issues search

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#759]
Since issues search have been implemented via #530, but it only supports English or non-CJK languages. We need a PR to support to CJK languages.

**Comment by tboerger** [comment]
Bleve seems to support it if I look at https://github.com/blevesearch/bleve/tree/master/analysis/lang/cjk

**Comment by lunny** [comment]
Yes, it supports but needs some codes.

**Comment by lunny** [comment]
This should have been resolved.
