### ISSUE TITLE
webhook  显示有触发请求，但是实际上响应接口并没有收到响应

### ISSUE THREAD

**Issue by vsenver** [go-gitea/gitea#7593]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

...

**Comment by lunny** [comment]
Please speak English
