### ISSUE TITLE
Cannot access files or folders inside folder named "LServer" on Chrome

### ISSUE THREAD

**Issue by FINDarkside** [go-gitea/gitea#7597]
- Gitea version (or commit ref): 1.10.0+dev-85-g635e7b38b
- Git version: 2.21.0.windows.1
- Operating system: Windows 10
- Database: Whatever is in try.gitea.io
- Can you reproduce the bug: https://try.gitea.io/TestUser3256/Test

## Description

Files inside folder named "LServer" cannot be accessed with Chrome 75. Trying to open any file or folder inside it gets you this:
```
This site can’t be reached 
The web page at https://try.gitea.io/TestUser3256/Test/src/branch/master/LServer/test.txt might be temporarily down or it may have moved permanently to a new web address.
ERR_FAILED
```

## Steps to reproduce:

* Open https://try.gitea.io/TestUser3256/Test with Chrome
* Open LServer folder
* Try to open the txt file or subfolder inside LServer

Seems to be caused by service worker, as removing or bypassing it makes everything work again.
Seems to work fine with Firefox 68 and Edge 44

**Comment by zeripath** [comment]
This is very interesting.

The request doesn't even get out of the browser. If you ctrl-F5 it works.

I think this is an issue with our recent upgrade to jquery 3.

**Comment by FINDarkside** [comment]
Added 3 additional folders to better demonstrate that it's somehow related to that specific folder name.

**Comment by jolheiser** [comment]
This is an ad-block issue. If you are using Chrome, I assume you are using uBlock or some derivative.

In the `EasyList` filter there is a pattern for `/lserver/*` which is why it never even makes it to the browser.  
As another example I found at random from that list `/oascache/*` you can see the same behavior in my test repo (https://try.gitea.io/jolheiser/Cache) when you click into `OASCache` and then `test.txt`

**Comment by zeripath** [comment]
I'm not sure that's there anything we can do from within Gitea to fix this so I'm going to mark this as invalid and close it.

**Comment by richmahn** [comment]
Interesting, I run adblocker and haven't modified it, yet I can open it.

**Comment by kolaente** [comment]
It seems to work with ublock origin on Firefox mobile, if it's an adblock problem shouldn't it also be blocked regardless of the browser as long as they're using the same list?

**Comment by jolheiser** [comment]
@kolaente That would be my guess as well. I can't say I dug too much into which lists contain it or how that specific ad-blocker responds, I tested using Chrome with uBlock Origin.  
  
It looks as though the list is actually in a repository over at https://github.com/easylist/easylist  
If you search for `lserver` you'll find it in `easylist_general_block.txt`
