### ISSUE TITLE
Allow to bypass sanitizer for external rendering

### ISSUE THREAD

**Issue by sapk** [go-gitea/gitea#7599]
Before doing a PR that may impact security I would like to have your advice

I would need to bypass the [sanitizer](https://github.com/go-gitea/gitea/blob/8ad64574ee80692ccc39c797ff88f65f09449412/modules/markup/markup.go#L87) by adding an option to external [markup](https://docs.gitea.io/en-us/config-cheat-sheet/#markup-markup) like DISABLE_SANITIZER. 

The goal is for issue like https://github.com/go-gitea/gitea/issues/5979 to be able to load JS libs (external or in public) like https://git.sapk.fr/Madeleine.js/examples/ajax.html

I think this would largely improve external rendering without introducing security risk by default but let the admin the possibility to load js or html that it trust.

**Comment by wxiaoguang** [comment]
Here it is: RENDER_CONTENT_MODE
