### ISSUE TITLE
Housekeeping

### ISSUE THREAD

**Issue by thibaultmeyer** [go-gitea/gitea#76]
It would be nice to have a button (on each repos settings page) to run a _housekeeping_ operation. This operation is useful to clean a repository and decrease is size.

Usually these two commands are run:
```
git prune
git gc --aggressive
```

**Comment by strk** [comment]
I think there's a periodic routine doing those things, (why) do you also want a button ?

**Comment by strk** [comment]
in any case, I guess if you provide a PR the approval process would be smoother :)

**Comment by thibaultmeyer** [comment]
I think manual housekeeping is better than periodic routine, cause is useless to run housekeeping on no-longer used/ archived repos.

Or maybe the periodic routine could be configured to ignore some repos ? (like a checkbox on each repos settings)

**Comment by strk** [comment]
I don't think the periodic routine can be configured, atm.
I guess an overall review of the system is needed, are you up for that ?
Ideally we'd have:
- Configurable periodic routine (frequency, exclusion list)
- Record of when the routine last run, shown in admin panel
- Button to force a run the routine for a single repository
- Button to force a run of the periodic routine

**Comment by 6543** [comment]
admin UI have button to "housekeep" all repos and I think there also exist a cronjob

**Comment by 6543** [comment]
I'll close feel free to ask for reopen if i missed something
