### ISSUE TITLE
[API] Issue events

### ISSUE THREAD

**Issue by qistoph** [go-gitea/gitea#760]
This is a feature request for the API to support more details for reporting. I would like to access:
- Issue events (just like [GitHub](https://developer.github.com/v3/issues/events/))

This would enable reporting integration to query the api to determine, over a period:
- number of issues closed

**Comment by bkcsoft** [comment]
Related to #64

**Comment by ghost** [comment]
Gitea doesn't have an API call to list commits still? Or am I missing something?

**Comment by Coriou** [comment]
Also wondering the same thing. I think it's not possible right now, or undocumented. I'll keep looking for a way

**Comment by lunny** [comment]
~@HoffmannP I think A has been implemented but B is not.~

**Comment by HoffmannP** [comment]
Can we rename this issue then? Alternativly close and reopen?

**Comment by lunny** [comment]
@HoffmannP I think I'm wrong. Neither are implemented.

**Comment by lunny** [comment]
@HoffmannP done.

**Comment by HoffmannP** [comment]
Wow, that was solved in record time! Thanks
