### ISSUE TITLE
[Branch View] save space, change pull button to a icon-only button

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#7605]
Oh, and if you want to save even more space, change the pull button to a icon-only button.

_Originally posted by @silverwind in https://github.com/go-gitea/gitea/pull/7520#issuecomment-514728279_

**Comment by lunny** [comment]
@6543 Is this resolved?

**Comment by 6543** [comment]
Not jet

**Comment by 6543** [comment]
But I'm not working on this at the moment ...

**Comment by 6543** [comment]
Should add this to the #7454 list
