### ISSUE TITLE
[Branch View] put all controll buttons in the same `td` and make them look similar

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#7606]
I think the current implementation takes away too much space from the important left-aligned column because having the buttons inside individual fixed columns introduces unnecessary spacing. I'd put all three buttons in the same `td` and make them look like this (remove `compact` class on the pull button):

![](https://user-images.githubusercontent.com/115237/61814988-8d6bab00-ae49-11e9-9b79-e227e8033eab.png)

Then right-align the diffstat and let the leftmost column take the remaining space.

_Originally posted by @silverwind in https://github.com/go-gitea/gitea/pull/7520#issuecomment-514727605_

**Comment by 6543** [comment]
blocked by https://github.com/go-gitea/gitea/pull/7602 https://github.com/go-gitea/gitea/pull/7604

**Comment by silverwind** [comment]
Not sure if that split-up was really necessary. Those two PRs conflict each other unfortunately. Maybe wait till #7602 is merged and then do the remaining changes in #7604 to achieve the equivalent of that screenshot?

**Comment by 6543** [comment]
i thought the contributor guidline tells me that if i like to get changes merged quik i should make smal  PRs wich a single wish/topic

**Comment by 6543** [comment]
i cann still klose the smal PRs and contribute to the big one?

**Comment by silverwind** [comment]
Yes, small changes get merged faster but your old one wasn't really *that* big. Anyways, I'd suggest sticking to the plan above. #7602 should probably be landed by tomorrow.

**Comment by 6543** [comment]
thx

**Comment by 6543** [comment]
is still not done

**Comment by 6543** [comment]
@silverwind ask for reopen this - i curently dont work on this ...

**Comment by 6543** [comment]
close this since this is no huge deal and if somebody came with good idears ... he can make it's own issue or pull
