### ISSUE TITLE
GOPROXY protocol support

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#7608]
If gitea could be as a goproxy server and all requested repositories could be stored on a special orgnization. That maybe a good idea.

ref: https://go.dev/ref/mod#goproxy-protocol

**Comment by lunny** [comment]
The benefit when gitea support goproxy protocol but not a third-party:

- [ ] all the information saved already in gitea(almost tags list, go mod file, source zip)
- [ ] private repositories support. No proxy will save your token or private repositories copy.
 
A goproxy protocol request likes below

```
GET $HOST:$PORT/gitea.com/gitea/gitea/@v/list
```
If gitea supports that,  the domain `gitea.com` will be a reserved username.

refs:
https://research.swtch.com/vgo-module
https://docs.gomods.io/intro/protocol/

**Comment by lafriks** [comment]
but problem is that pretty much any domain will have to be reserved username then...

**Comment by sapk** [comment]
And what it would do with external package (not a local repo) ? cache them also ?
From an architecture point, I feel that it would be better use one of the many goproxy implementation since it would be better to setuo it under another domain like goproxy.domain.com. Furtermore, one of the goal of the goproxy is to act as a cache in case of downtime of repo, implentating goproxy in gitea would lost this advantage.

**Comment by lunny** [comment]
@lafriks  No. Only the domain gitea itself. Mirrors could be any place because we know they mirrored from.

**Comment by lunny** [comment]
@sapk there are two functionality of goproxy protocol. One is for cache, another is for repositories.
Before go module come, go will get packages via go get that we only needs to provide a meta and a VCS(git) protocol.
Only go module time, above is also available but provide a direct protocol is better. It will accelerate directly visit because git is too slow for a go module protocol.
You can consider this is a go module protocol v2 rather than go get protocol v1.

**Comment by lunny** [comment]
When I and unknwon begin `gopm` repository on 2014 or 2015. We download github's `zip` or `tar.gz` source packages but not via git protocol. It's quick than `go get` that time. The goproxy is similiar.

**Comment by sapk** [comment]
@lunny I understand the speed-up but the trade-off are "big" (blocking some name, adding complexity, ...) compare to someone just setup a goproxy aside.
And for blocking name, technically module are not necessary FQDN at the base so it can interfere with a lot of other url. I think we better try to offer api endpoint (if needed) and work with goproxy implementation to help them speed there inital search on gitea.

On a side note, I haven't tested but GOPROXY should support a subfolder like GOPROXY=https://myproxy.com/sub-folder. (at least, it support it for file:// url)
If we implement goproxy, I think it would be better to offer sub-folder as an endpoint.

**Comment by lafriks** [comment]
we could set to reserved username `registry` to use for goproxy, maybe later also for npm, docker registries etc, so that it could be used with `GOPROXY=https://gitea.com/registry/go/` and for others we could use `https://gitea.com/registry/npm/` etc

**Comment by lunny** [comment]
@sapk @lafriks Yeah. Gitea could implement these package protocols for this instance's repositories (NOT for a cache proxy). The target is different from goproxy or athens . And as what @lafriks said, this should be a first step to support golang, furthermore we can support other language packages protocols.

For enterprises' public or private repositories, that will reduce an extra server(goproxies or other languages).

Once gitea implemented this and with go 1.13, we can just set `GOPROXY=https://myenterprise.com/registry/go,https://goproxy.io`

**Comment by s3rj1k** [comment]
Highly needed feature
