### ISSUE TITLE
Merging pull request causes 500 error.

### ISSUE THREAD

**Issue by PershingSquare** [go-gitea/gitea#7611]
- Gitea version (or commit ref): 1.10.0+dev-67-ge0d6d2f97
- Git version: 2.7.4, Git LFS 2.7.2
- Operating system: Alpine Linux v3.10
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No, our repo use git-lfs and I wasn't able to reproduce it on there.
  - [ ] Not relevant
- Log gist:
https://gist.github.com/PershingSquare/68118d48e13a082a749870cfa3a5e7cc
## Description
Every time I try to merge a pull request, I get a 500 server error. I have branch protection on master, with 1 approval required before merging.

## Screenshots
![what_the_page_looks_like](https://user-images.githubusercontent.com/39250540/61876343-7d7fb580-aea1-11e9-9ba2-56aec8b0b627.PNG)

**Comment by zeripath** [comment]
OK so looking at the gitea.log you've sent it appears that the panic is being caused at line 104 here:

https://github.com/go-gitea/gitea/blob/734aa965088fb72330f4ad744c187c614cce3d8b/models/branches.go#L102-L108

This is in turn called from:

https://github.com/go-gitea/gitea/blob/734aa965088fb72330f4ad744c187c614cce3d8b/models/branches.go#L94-L100

Which is from line 99 here: 

https://github.com/go-gitea/gitea/blob/734aa965088fb72330f4ad744c187c614cce3d8b/routers/private/hook.go#L89-L105

**Comment by zeripath** [comment]
Now that means that either `pr` is nil here, or `pr.Issue` is nil.

**Comment by zeripath** [comment]
OK, simple fix is to change `pr.Issue.ID` to `pr.IssueID`. However, when merging it shouldn't be pushing all of the branches so I'll look at that too.
