### ISSUE TITLE
[feature request]Support auto set username,email,password when use oidc

### ISSUE THREAD

**Issue by annProg** [go-gitea/gitea#7627]
- Gitea version (or commit ref): 1.8.3
- Git version:
- Operating system: 
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
When login with oidc, user need to set username , email and password.

Allow users to set user names and email, which will cause confusion inside the company. I hope to add an option to support  read username and email from oidc but not user input, and automatically set a random password(when add ssh key, password is useless).
...

## Screenshots
![image](https://user-images.githubusercontent.com/4145852/61930812-819af880-afb1-11e9-8105-fce14613d7cd.png)

**Comment by lunny** [comment]
There is already an issue to request that.
