### ISSUE TITLE
docker 安装的gitea的template在哪，在docker中死活找不到，/data里也没有

### ISSUE THREAD

**Issue by Castleeee** [go-gitea/gitea#7628]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

...

docker 安装求gitea网页静态文件的路径

**Comment by zeripath** [comment]
Please speak English on github. There is a #Chinese channel on discord if native language help is required.

Google translate suggests your question is asking: where the templates are stored on the docker build?

On docker they are compiled into the binary to make it easier to use. If you would like to customize gitea by providing altered templates see: https://docs.gitea.io/en-us/customizing-gitea/ 

The CustomPath is by default on Docker `/data/gitea`, therefore your custom templates would go into `/data/gitea/templates`.

A complete set of templates that would match the default set of templates would be to copy: https://github.com/go-gitea/gitea/tree/master/templates (with the branch changed as appropriate for your version) as `/data/gitea/custom/templates` but you should only copy and change what you need.

**Comment by Castleeee** [comment]
sorry for borther you。 I found how to use it thx。
