### ISSUE TITLE
Reverse proxy documentation regression

### ISSUE THREAD

**Issue by mrsdizzie** [go-gitea/gitea#7632]
Documentation for reverse proxy was updated recently in #7540 but I don't think it was tested because now the recommended settings for using reverse proxy in a subdir give:

```
AH00526: Syntax error on line 27 of /private/etc/apache2/extra/httpd-vhosts.conf:
AllowEncodedSlashes not allowed in <Proxy> context
```

**Comment by gary-kim** [comment]
Sorry, my bad, I didn't copy & paste check the subdirectory proxy configuration.
