### ISSUE TITLE
New Migration interface improvements

### ISSUE THREAD

**Issue by mrsdizzie** [go-gitea/gitea#7635]
When doing a migration, it doesn't show the options to migrate issues,pr,etc.. until you put in authentication information which is confusing and leads people to think those aren't available before even trying.

I think it should always show the checkboxes and perhaps just grey them out until information has been added (with text indicating why).

Also I think we should make it clear that you can add a token in the username field which is a very nice but also unknown feature for migration.

This would be nice to have for 1.9 since migration is new for this release and it would give a better first impression (and should be just a small ui change)

**Comment by fin-ger** [comment]
I ran into exactly this problem. Also, the password based authentication for the github API seems to be deprecated. So, for github migrations, the migration form should always ask for a Personal Access Token.

> You recently used a password to access an endpoint through the GitHub API using go-github. We will deprecate basic authentication using password to this endpoint soon:
> ...
> We recommend using a personal access token (PAT) with the appropriate scope to access this endpoint instead. Visit https://github.com/settings/tokens for more information.
> -- Email from github

**Comment by TheTechRobo** [comment]
This would be incredibly useful. I spent about an hour looking for how to migrate issues, PRs, etc.

**Comment by lunny** [comment]
We can add a middle page before current migration page. It will let you chose migration type, if you chose non-git, issues/pulls/releases ... will be displayed on the next page. If you chose git, the options will not be displayed.
<img width="181" alt="图片" src="https://user-images.githubusercontent.com/81045/83367056-29106500-a3e5-11ea-8be1-09bbe1db66a2.png">

**Comment by mrsdizzie** [comment]
@lunny only if we can use that drawing as the interface ; )

**Comment by lunny** [comment]
@mrsdizzie any idea? I will try to send a PR to do that.

**Comment by jolheiser** [comment]
Fixed by #12619
