### ISSUE TITLE
[1.9.0+rc2] Migrate from Github private repo fails

### ISSUE THREAD

**Issue by behnoodk** [go-gitea/gitea#7644]
- Gitea version (or commit ref): 1.9.0+rc2-14-g650fdceb5
- Git version: 2.17.1
- Operating system: Ubuntu 18.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

When trying to migrate a private Github repo, migration tool fails with following error:

`Authentication failed: Clone: exit status 128 - fatal: could not read Username for 'https://github.com': No such device or address`

I have tried following senarios:

1. Disable my two factor authentication and enter my username and password
2. Enter a Personal Access Token with full access on my account

As long as my repo is private the migrate tool fails. Finally if I make my repo public, migrate tool works as it should.

P.S. Gitea is awesome! Thank you :)

**Comment by dustalov** [comment]
I have the very same issue with the version 1.10.0+dev-129-g6c0c5c531 of Gitea. As a workaround, I specified the following clone URL, and it worked as a charm: `https://username:token@github.com/username/repo.git`.

**Comment by lunny** [comment]
could you confirm that #7917 fixed this issue?

**Comment by dustalov** [comment]
Sorry, my installation is running in a container on ARM64. Currently, I cannot build and test it.

**Comment by behnoodk** [comment]
I cannot upgrade my own instance right now. but if the pull request is merged and deployed on `try.gitea.io` which right now says `1.10.0+dev-190-g852876a98`, I just created an account and tried to migrate my private repo and it failed again with the error:
`
Authentication failed: Clone: exit status 128 - fatal: could not read Username for 'https://github.com': No such device or address
`

what I did was, I created a Personal Access Token with full permissions and provided that as my password in the migrate page and selected all the migration items : Wiki, Milestones, Labels, Issues, Pull Requests, Releases.

**Comment by wilsandbrink** [comment]
I'm running 1.9.2 which supposedly fixed this issue, yet I still have it.

**Comment by lrecknagel** [comment]
If anyone running into this and needs a "solution" in some way:
https://gist.github.com/lrecknagel/cdb5f85f150f5f15d882651b6119157e
