### ISSUE TITLE
About labels

### ISSUE THREAD

**Issue by jaqra** [go-gitea/gitea#7646]
What about:
- Add "done" (green) label to default labels
- Change "help wanted" label's color to "#fef2c0" (green will be done label's)
- Change "wontfix" label's color to "#424242" (white is not looks good)

**Comment by jaqra** [comment]
![labels](https://user-images.githubusercontent.com/48099350/61994825-5e8f4800-b088-11e9-82e4-644e2d448232.JPG)

**Comment by lafriks** [comment]
You can override defaults for your instance, see docs on how to customize

**Comment by jaqra** [comment]
@lafriks its not good for 'all' so wont be need to cumtomize ?

**Comment by lafriks** [comment]
Sorry did not understand your question

**Comment by jaqra** [comment]
I ask that `is not it what it should be?`.
If we change it on source code, everyone can use and wont be need to customize gitea options?

**Comment by lafriks** [comment]
I agree but to be honest I don't really see much use in done label and we can't really change defaults per every request as everyone has it own needs and preferences that's why it is customizable
