### ISSUE TITLE
Feature Request: Find file

### ISSUE THREAD

**Issue by maevic** [go-gitea/gitea#766]
I think it would be nice to have a fuzzy find file feature like the one on GitHub. If there are multiple subfolders this would really ease the process of finding a file.

**Comment by MarkusAmshove** [comment]
Please no stale :-)

The [File Finder](https://github.com/go-gitea/gitea/find/master) is a great tool and would add great UX for all the features in the/coming to the web UI, like blaming, log of a file, comparing, etc.
