### ISSUE TITLE
negative pull request count

### ISSUE THREAD

**Issue by cevin** [go-gitea/gitea#7673]
- Gitea version (or commit ref): 1.9.0-rc2 
- Git version: 2.9.5
- Operating system: centos
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant

![image](https://user-images.githubusercontent.com/338110/62113742-b24b9c80-b2e7-11e9-9b69-ff6bfa6e2c6f.png)

**Comment by lunny** [comment]
duplicated with #7428 and fixed by #7518
