### ISSUE TITLE
Render markdown bodies in emails

### ISSUE THREAD

**Issue by mjwwit** [go-gitea/gitea#768]
## Description
Notification emails being sent after issues are created contain the body of the issue. Generally speaking, markdown formatting is used to structure the body of issues, and Gitea renders this perfectly fine. The notification emails though, contain the unformatted markdown content. Gitea should render the body to HTML before putting it in the emails to improve readability.

**Comment by bkcsoft** [comment]
I think we already do this. We send both a `text/plain` and `text/html` in the emails. And `test/html` should be rendered correctly.

**Comment by mjwwit** [comment]
@bkcsoft Yes, there is a `text/plain` and a `text/html` version of the mail. The only rendered markup are links to issues/PRs though, and any other formatting seems to be sent as is. This looks extra chaotic because rendered html doesn't honor linebreaks in the source. I should have fixed the rendering of all markdown formatting in #803, but @lunny still got a `text/plain` email. I will do further debugging to see if I can resolve that.

**Comment by mjwwit** [comment]
Fixed by #1027
