### ISSUE TITLE
CMakeLists.txt highlighting

### ISSUE THREAD

**Issue by FlorianBen** [go-gitea/gitea#7685]
- Gitea version: 1.9.0-dev
- Git version: 2.17.1
- Operating system: Ubuntu 18.04
- Database:
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes: https://try.gitea.io/testCMake/CMakeListsHLjs/src/branch/master/CMakeLists.txt
  - [ ] No
  - [ ] Not relevant

## Description

Currently the file highlighting is triggered by the file name or the file extension, but sometime it is not enough. For instance, a CMakeLists.txt file is not recognized as a CMake file. As well, CMakeLists.txt files are case sensitive, so a cmakelists.txt should not be highlighted.
It may be fixed for CMakeLists by using a new file filter:
https://github.com/FlorianBen/gitea/commit/08f733310ccfaa77b86b6460fe7605fc04d4d627

**Comment by lafriks** [comment]
Please send PR with this

**Comment by lunny** [comment]
Closed by #7686
