### ISSUE TITLE
Cached repository archives grow space occupation indefinitevely

### ISSUE THREAD

**Issue by strk** [go-gitea/gitea#769]
Repository archives are only deleted upon explicit request ("Delete all repository archives" from admin dashboard). This results in an indefinite grow of disk space occupation. It may be good to allow for a periodic cleanup instead, maybe based on last access time.

**Comment by minecrafter** [comment]
I've completed a first implementation for this. I will be testing it tomorrow.

**Comment by tboerger** [comment]
> I've completed a first implementation for this. I will be testing it tomorrow.

When you got a PR we can update the milestone related to that.

**Comment by richbl** [comment]
Not sure where best to ask this question but, what's the purpose of these repo archives? Are these generated when a project release is made, or are they generated at some regular interval?

Thanks

Rich

**Comment by lunny** [comment]
@richbl when you download an archive from the repo UI, then it will produce an archive in your server disk, not only release.

**Comment by richbl** [comment]
@lunny, thanks. I see that now.
