### ISSUE TITLE
Implement a way to migrate with ssh keys

### ISSUE THREAD

**Issue by DblK** [go-gitea/gitea#7691]
Hi,

I think it might be linked to https://github.com/go-gitea/gitea/issues/7678, but I tried to make a migration (with mirror) on a private repository on github.
Since I have 2FA, I can not enter my credential.

So if we had the possibility to migrate repositories with an ssh key it should solve all my issues.
Thanks

**Comment by zeripath** [comment]
It's not just a clone of a repository anymore. We're getting more information from github like issues and prs - stuff which cannot be obtained over the ssh interface.

**Comment by mrsdizzie** [comment]
Migration supports using an application access token from Github which works with 2FA accounts.

There is a separate bug related to private repos on github though #7644 which you'd probably run into next

**Comment by DblK** [comment]
Thanks, I did not check the application access token for 2FA.
And definitively will look into #7644 for my private repo.

**Comment by lunny** [comment]
duplicated with #1635
