### ISSUE TITLE
1.9.0 breaks gogs web hooks

### ISSUE THREAD

**Issue by UziTech** [go-gitea/gitea#7692]
- Gitea version (or commit ref): 1.9.0
- Git version: 2.22.0.windows.1
- Operating system: Windows
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

v1.9.0 changes the default web hook to use `application/json` so any existing Gogs web hook which was setup to receive `application/x-www-form-urlencoded` data will break because there is no place to change it in a Gogs web hook.

This is more of an FYI for anyone looking for a fix.

I fixed it by creating a Gitea web hook with the `POST Content Type` set to `application/x-www-form-urlencoded`

**Comment by lunny** [comment]
It seems it's a breaking change I haven't noticed.

**Comment by 6543** [comment]
@aamsur this: https://github.com/go-gitea/gitea/pull/8402 should close this issue?

**Comment by lunny** [comment]
I think yes.

**Comment by aamsur-mkt** [comment]
@6543 yes, thanks @lunny
