### ISSUE TITLE
Gitea doesn't display README.md from other config directories

### ISSUE THREAD

**Issue by lmariscal** [go-gitea/gitea#7697]
- Gitea version (or commit ref): 1.8.3
- Git version: N/A
- Operating system: Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes https://try.gitea.io/lmariscal/readme-issue
  - [ ] No
  - [ ] Not relevant
- Log gist: N/A

## Description
Github allows to have your reposs README.md under `.github` directory as shown in https://github.com/nimgl/nimgl and https://github.com/ocornut/imgui but Gitea doesn't render neither readmes under `.github` nor under `.gitea`. You can live test it in the repo provided above.

This has been previously mentioned in https://github.com/go-gitea/gitea/issues/5370 but there has been no follow up.

## Screenshots

![2019-07-31 225837](https://user-images.githubusercontent.com/7671915/62264744-e5288a00-b3e6-11e9-823d-d2ed887ca239.png)
![2019-07-31 225913](https://user-images.githubusercontent.com/7671915/62264741-e48ff380-b3e6-11e9-80fa-28134661b730.png)
![2019-07-31 225858](https://user-images.githubusercontent.com/7671915/62264743-e48ff380-b3e6-11e9-97cc-db58b653e391.png)

**Comment by lunny** [comment]
I have reopened #5370, please follow that issue.
