### ISSUE TITLE
Allow adding a default set of githooks and webhooks

### ISSUE THREAD

**Issue by alvaroaleman** [go-gitea/gitea#770]
It would be nice if it was possible to configure a default set of githooks and webhooks in the admin interface and/or at organization level.

That default set should then be applied to all newly created repositories. It should also be possible to use the repository name as variable.

**Comment by charlesreid1** [comment]
Agreed! This would also make it much simpler to set up a static page hosting service, Github Pages style. You can create a webhook that triggers a site builder on commit to a particular branch, and have it installed on all pages by default.

**Comment by aunger** [comment]
I'm going to take a crack at this, but I'd like some design feedback on the question of **default** vs **all**.

For my purposes, adding an admin set of web hooks for **all repos** would be sufficient.  These would be invisible to the individual org and repo settings pages, and could only be altered by admin.  As the administrator of the system, I want my own set of hooks to fire upon pushes, for example.

As I understand #770, it requests **default** webhooks instead, which are copied into new orgs and new repos, and may then be altered or deleted by the org/repo owner.  This could work for my needs, too.

I can implement whichever is more likely to be merged.  Thanks!  Thoughts?

**Comment by techknowlogick** [comment]
Closed per merged PR
