### ISSUE TITLE
Statics build failed

### ISSUE THREAD

**Issue by sapk** [go-gitea/gitea#7701]
Since the update of src-d/go-git (#7688) the static builds fail for linux/386.

https://drone.gitea.io/go-gitea/gitea/11344/3/3

Two solutions:
- drop linux/386 support
- wait for a fix on go-git

**Comment by sapk** [comment]
@lunny already created an issue on there side: https://github.com/src-d/go-git/issues/1202

**Comment by lunny** [comment]
Since src-d/go-git#1202 merged. Maybe we need upgrade src-d/go-git ?
