### ISSUE TITLE
Webhooks triggered twice

### ISSUE THREAD

**Issue by 0x1793d1** [go-gitea/gitea#7702]
- Gitea version (or commit ref): 1.9.0
- Git version: 2.22.0
- Operating system: Debian Buster / Docker
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant

## Description

Hi,

Since 1.9.0, webhooks are triggered twice when committing via the website.

**Comment by lunny** [comment]
It seems there is one PR fixed that.

**Comment by 0x1793d1** [comment]
You mean #7684?, I saw this PR, but it doesn't seem to work for my case.

**Comment by lunny** [comment]
No, I mean https://github.com/go-gitea/gitea/pull/7516, but it seems it hasn't been fixed.

**Comment by zeripath** [comment]
So I think this is because we're now running commits through the git hooks - so the webhook actions in commit repo action are no longer needed.

@0x1793d1 are you sure that the webhooks you receive are absolutely the same?

**Comment by 0x1793d1** [comment]
@zeripath Yes, they are the same.

Result on try.gitea.io : https://webhook.site/#!/ad98b669-2775-45b5-a98e-164aed79aa48/01e88be5-81b8-4582-9cc9-f72ba6b3a8b3/1

**Comment by lunny** [comment]
It seems recent version fixed this. But I don't know which PR did that.

**Comment by lunny** [comment]
I can't reproduce this on one 1.9.0 gitea instance with drone 1.1.0.

**Comment by lunny** [comment]
@0x1793d1 could you check if you have two webhooks from the same ci server.

**Comment by 0x1793d1** [comment]
@lunny I am using Drone as CI server, and it receive two hooks when I commit via the website. I can reproduce this bug with a dummy webhook on try.gitea.io:

![image](https://user-images.githubusercontent.com/2362128/62657563-136a1480-b967-11e9-8515-9ee0ae4236e0.png)

**Comment by quantonganh** [comment]
> I can't reproduce this on one 1.9.0 gitea instance with drone 1.1.0.

I can reproduce this on Gitea 1.9.0 with Drone 1.2.1.

@lunny Please notice that #7726 is a bit different from this: it happened when we merge a PR. #7702 happened when we commit via web interface.

**Comment by quantonganh** [comment]
> So I think this is because we're now running commits through the git hooks - so the webhook actions in commit repo action might be no longer needed.

@zeripath You mean this? https://github.com/go-gitea/gitea/blob/master/modules/repofiles/action.go#L115

**Comment by zeripath** [comment]
Yeah that's my worry but I'm a busy at the moment to double check this.

**Comment by lunny** [comment]
I found this will occupy randomly in v1.9.0.

**Comment by sapk** [comment]
Looking at some logs, I can confirm that it add a task during post-receive call and a other one later after the post-receive ended.

**Comment by sapk** [comment]
I think that call to PushUpdate() should not be call anymore on web edit like in CreateOrUpdateRepoFile: https://github.com/go-gitea/gitea/blob/7ad67109d732bd560c8da0356aa555be467d786c/modules/repofiles/update.go#L117 since it now call via post-receive: https://github.com/go-gitea/gitea/blob/3563650bdb273045c55400ee9520a0f78fc90e76/routers/private/hook.go#L147

**Comment by sapk** [comment]
Deleting branch since to be triggered in double but I am not sure for the second call path.

**Comment by metal3d** [comment]
Is the "latest" docker image updated with that fix ? I updated image last friday (6 sept) and I still see that issue with Drone.
Thanks

**Comment by lafriks** [comment]
It should be, what kind of webhook was trigger for you twice?

**Comment by metaisfabien** [comment]
> Is the "latest" docker image updated with that fix ? I updated image last friday (6 sept) and I still see that issue with Drone.
> Thanks

For me gitea/gitea:last send twice gitea/gitea:1.10 send one time.

**Comment by adrianyorke** [comment]
I am seeing this behavior for 1.12.0+dev-161-gf6067a846/git version 2.20.1/Debian Buster/SQLite: 
![image](https://user-images.githubusercontent.com/30093433/73105075-a9d3c780-3f00-11ea-8126-7efb2a29d411.png)
![image](https://user-images.githubusercontent.com/30093433/73105107-c1ab4b80-3f00-11ea-8986-db21022d4d90.png)

**Comment by zeripath** [comment]
@adrianyorke that looks different, that's duplicate notifications and I suspect you may have two Gitea post-receive hooks in your repository. 

But please open a different issue if you don't

**Comment by adrianyorke** [comment]
Thanks for replying @zeripath.  Apologies, I was a little embarrassed when I realized I had added a comment to a Closed issue.  I really wasn't expecting a reply, especially "same day" so thank you.   I will experiment more and report back.  So far this is a "default installation" but let's see.

**Comment by john-kheir** [comment]
I can see this issue on 1.11.1 which supposed to be the last official release 
```
root@ff1a92d193e9:~# ./gitea --version
Gitea version 1.11.1 built with GNU Make 4.1, go1.13.8 : bindata, sqlite, sqlite_unlock_notify
```
![two triggers](https://user-images.githubusercontent.com/15011431/75447397-f2542a00-5971-11ea-85a3-4f85d78b0f8e.png)

**Comment by lafriks** [comment]
I think similar issue was fixed and will be in 1.11.2

**Comment by nagos** [comment]
Same stuff on 1.12.0+dev-20-gca181100c
![gitea](https://user-images.githubusercontent.com/183965/76908506-e3e69780-68b9-11ea-9ca2-d2a8b65fdd54.png)
Git push send duplicate triggers.
Gitea + drone.

**Comment by adrianyorke** [comment]
This is a closed thread but for anyone turning up here, my problem went away after the first day or so.   I didn't need to fix anything myself or change any config, the duplicate triggers just stopped happening.  Gitea has been stable since.

**Comment by nagos** [comment]
> This is a closed thread but for anyone turning up here, my problem went away after the first day or so. I didn't need to fix anything myself or change any config, the duplicate triggers just stopped happening. Gitea has been stable since.

You are right! Issue went away after i restarted gitea.
So my guess, when they add trigger during configuration, it got added twice. But after restart, it loads from configuration file correctly.
