### ISSUE TITLE
Failed to get repository: invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by gnaghi** [go-gitea/gitea#7720]
- Gitea version (or commit ref): 1.9.0
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

I updated gitea from 1.8 to 1.9.0 (Ubuntu 18.04), and I can no longer push or pull anything.
On the ssh client side, I have the following message : 
`Gitea: Internal error
Failed to get repository: Failed to get repository: invalid character '<' looking for beginning of value`

Inside gitea.log :
`routers/repo/http.go:97:HTTP() [E] GetUserByName: user does not exist [uid: 0, name: api, keyid: 0]`

And inside serv.log :
`[T] GetRepositoryByOwnerAndName: https://localhost:3000/api/internal/repo/XXXX/YYYY
[...io/gitea/cmd/serv.go:195 runServ()] [F] Failed to get repository: Failed to get repository: invalid character '<' looking for beginning of value`

Reverting back to 1.8 makes everything work again.

**Comment by zeripath** [comment]
I think you have both gitea-1.8 and gitea-1.9 installed at the same time.

If you change the name of the gitea binary you have to run the admin task: "Update the '.ssh/authorized_keys' file with Gitea SSH keys."

**Comment by gnaghi** [comment]
You were right : the service wasn't stopped, but I was able to connect to the web interface, and see the «1.9» version.
I stopped every instance of gitea, launched the 1.9 version, and I have new problem : 
- The web interface is not working
- Git push/pull isn't either.
- The gitea.log indicates that gitea is trying to update the database, but fails.

 `.../xorm/session_raw.go:226:Exec() [I] [SQL] CREATE TABLE `new_access_token_new` (`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, `uid` INTEGER NULL, `name` TEXT NULL,  `created_unix` INTEGER NULL, `updated_unix` INTEGER NULL, `token_hash` TEXT NULL, `token_salt` TEXT NULL, `token_last_eight` TEXT NULL,
 ...xorm/xorm/session.go:845:saveLastSQL() [I] [SQL] ROLL BACK
 routers/init.go:86:GlobalInit() [F] ORM engine initialization failed: migrate: do migrate: incomplete input`

Should I open another issue and close this one ?
I'll try updating from each version between 1.8 and 1.9.

**Comment by gnaghi** [comment]
Upating from 1.8 to 1.9 failed, the last version working for me is 1.8.3.

**Comment by lunny** [comment]
This is a know issue with database sqlite when upgrade from 1.8 to 1.9

**Comment by gnaghi** [comment]
I saw the commit (#7710), I'll wait for a release.

**Comment by imamong** [comment]
same error..

**Comment by lunny** [comment]
This has been fixed by https://github.com/go-gitea/gitea/pull/7765 and released on 1.9.1. Please confirm and if you have a different problem. Please open another issue.
