### ISSUE TITLE
Create admin user after container is created

### ISSUE THREAD

**Issue by fraballi** [go-gitea/gitea#7721]
Hi @Team.
Great effort!

How can I create once an admin user as a s6/ or through an init script, during bootstrapping, after containers deployment finishes (through a docker-compose). Skipping /install step.

Thanks.

**Comment by lunny** [comment]
./gitea admin create-user --help

**Comment by fraballi** [comment]
Yes, I know the command, thanks. What I need exactly is create that user
during deployment, without user manual intervention like s6/ run, setup or
finish scripts. Is it possible, where to place custom init scripts that run
once?

😉

**Comment by zeripath** [comment]
You could have the script write a lock file so that it knows it has been run?

**Comment by fraballi** [comment]
Thanks for your response, that seems a nice option, but does gitea have any
folder where to load default init scripts in a cohesive and standard way?
e.g pre, around, after/post initialization (e.g AOP pointcuts). I tried
several options:

- Bash script in /etc/init.d folder (fails)
- Bash script in /etc/s6/gitea folder (fails)
`exec gitea admin create-user --admin --access-token --username=****
--password=**** --email=***@***.*** --must-change-password=false"`

- Appending a line to /etc/s6/gitea/run or setup scripts (fails)
`echo "exec gitea admin create-user --admin --access-token --username=****
--password=**** --email=***@***.*** --must-change-password=false" >>
/etc/s6/gitea/run`

Then, when the container is running I manually exec my script and it works
like a charm.
So, the missing step here would be using best practices for gitea and move
on,

Thanks. ;-)

**Comment by fraballi** [comment]
Thanks for your response, that seems a nice option, but does gitea have any
folder where to load default init scripts in a cohesive and standard way?
e.g pre, around, after/post initialization (e.g AOP pointcuts). I tried
several options:

- Bash script in /etc/init.d folder (fails)
- Bash script in /etc/s6/gitea folder (fails)
`exec gitea admin create-user --admin --access-token --username=****
--password=**** --email=***@***.*** --must-change-password=false"`

- Appending a line to /etc/s6/gitea/run or setup scripts (fails)
`echo "exec gitea admin create-user --admin --access-token --username=****
--password=**** --email=***@***.*** --must-change-password=false" >>
/etc/s6/gitea/run`

Then, when the container is running I manually exec my script and it works
like a charm.
So, the missing step here would be using best practices for gitea and move
on,

Thanks. ;-)

**Comment by lafriks** [comment]
This should not be added in init script for security reasons

**Comment by fraballi** [comment]
I understand @lafriks , so what workaround can be done?

**Comment by lafriks** [comment]
usually this would be done either manually or by some automation (ansible/chef etc)

**Comment by fraballi** [comment]
I searched on gitea site and it does not talk on image build process?
Can you share those details, I'm trying to exhaust docker via instead doing
it from sources.
Thanks.

**Comment by lafriks** [comment]
It will not work in service also because only on gitea first start database structure will be initialized and I don't know if gitea cli command does that but this should be tested but you will have to preconfigure app.ini in docker image as this should be run only when gitea is fully configured

Anyway if you take into account previous issues than you could probably write docker entrypoint script to run that command and read password from docker secrets:

```
[ ! -f /data/admin_user_created ] && gitea .... --password=$(cat /run/secrets/gitea_admin_password) ... && touch /data/admin_user_created
```

**Comment by lunny** [comment]
I think you can create your `Dockerfile` and add that command there. For an official image, we cannot do that.
