### ISSUE TITLE
Incorrect Time is displayed when check the Submit time

### ISSUE THREAD

**Issue by suli3** [go-gitea/gitea#7723]
- Gitea version (or commit ref): 1.9.0 docker
- Git version:
- Operating system: Centos
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

The submit time is about 1 o'clock.
The Check time is about 2 o'clock.

The submit time description is right which is an hour ago, 
but the Exact moment should be about 1 o'clock on the morning of August 3, but now is about 15:21 of August 3 . . .

But where the wrong submit time come from?
I noticed that issue #7239 maybe the same problem or a very similar problem  ...

## Screenshots

![48RIZELJ}K)O`75{ER}H$PB](https://user-images.githubusercontent.com/1057425/62407004-04d8d180-b5e4-11e9-8a82-14ac6cc98254.png)

I hv checked the time in the docker and the server time, there are the same.
![QSHAP9R379L}68VS`)K9 MP](https://user-images.githubusercontent.com/1057425/62407006-099d8580-b5e4-11e9-9c35-8ea3bb77c4a3.png)

**Comment by lunny** [comment]
Should be closed by #7792
