### ISSUE TITLE
Syntax highlight in diff and edit preview broken

### ISSUE THREAD

**Issue by silverwind** [go-gitea/gitea#7728]
The highlighting code currently assumes a `pre > code` structure to work but this is not given for diff and edit previews. Given that `pre > code` is problematic in regards to introducing extra whitespace for text selection, I think we should introduce a new exclusive HTML class for syntax highlighting and use that everywhere.

**Comment by lafriks** [comment]
How that will work in markdown code sections

**Comment by silverwind** [comment]
Good point, if the markdown renderer can only output `pre > code`, we have to cover it via `.markdown pre > code`. On the other hand, I think some more expermentation is neccessary if `pre > code` can be made to work in regard to copy/paste.
