### ISSUE TITLE
PR files return 500

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#7735]
https://gitea.com/gitea/changelog/pulls/6/files

The repository was migrated from github, don't know if it's a migration bug or pull view bug.

**Comment by lafriks** [comment]
Anything in gitea.log?

**Comment by sharpSteff** [comment]
#7754 got the same issue with gitea 1.9.0+3-g6d441de
1.8.3+2-g11f6ed4 worked just fine

**Comment by lunny** [comment]
should be closed by #7854

**Comment by guillep2k** [comment]
So this should closed?

**Comment by lunny** [comment]
I think the problem is still there. I will test it locally.

**Comment by lunny** [comment]
This was fixed by #8564
