### ISSUE TITLE
gitea-1.9 version,Upload user profile error

### ISSUE THREAD

**Issue by mirroro** [go-gitea/gitea#7737]
Upload User Head Image Error Reporting Using Gitea Version 1.9。
The contents are as follows：

Bad Request: no CSRF token present

**Comment by wxk6b1203** [comment]
The same error occurred when using nginx as reverse proxy. Here is some of my settings:
```nginx
proxy_http_version 1.1;
 proxy_set_header Connection "Keep-Alive";
 #proxy_redirect off;
proxy_set_header Host $host;
proxy_set_header        X-NginX-Proxy   true;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_pass_header       Set-Cookie;
add_header 'Access-Control-Allow-Credentials' 'true';
proxy_pass_header X-CSRF-TOKEN;
proxy_set_header        Upgrade         $http_upgrade;
```

**Comment by wxk6b1203** [comment]
Not only this wrong with Chome 76, but also uploading attachments on issue. Maybe it is a serious problem with Chrome, not with gitea....................................

**Comment by caifenglin** [comment]
It's true that only chrom 76 can't upload pictures. Why does this happen?

**Comment by caifenglin** [comment]
Other browsers are fine.

**Comment by lunny** [comment]
#7955 is duplicated with this one. But it reports more avatars problem. So let's close this one.
