### ISSUE TITLE
Issue with "fatal: protocol error" on OpenBSD using git push

### ISSUE THREAD

**Issue by daemhan** [go-gitea/gitea#7747]
- Gitea version (or commit ref): 1.7.4 built with go1.12.1
- Git version: 2.21.0
- Operating system: OpenBSD 6.5
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist: no log entries from protocol error.

## Description

Using https to push to gitea from local. 

I was able to use git push -u origin master without issue. I added files, and tried to push these using git push, and received this error:
fatal: protocol error: bad line length character: POST

I removed the .git folder, reinitialized everything, and started adding files and directories to be tracked one by one when it dawned on me that the error occurred after I got tired of adding individual files/directories and added everything at once. While doing this one file/directory at a time, I got to the following and ran into the error:

git add roles/
git commit -m 'adding roles dir'
git push
fatal: protocol error: bad line length character: POST

I attempted to remove the folder from tracking, made a commit about the removal, tried to push again, and the same error comes up.

git rm -r roles/
git commit -m 'removing directory from tracking'
git push
fatal: protocol error: bad line length character: POST

## Screenshots
N/A

**Comment by lafriks** [comment]
What protocol are Gitea listening on? (http, fastcgi etc)

**Comment by lunny** [comment]
Could you use a recent version(1.9.0) than 1.7.4 ?

**Comment by daemhan** [comment]
Hello,

Notification failure. 

I'm currently using fastcgi for serving the front end, but I use https for git push/pull.

It is not possible to use 1.9.0 at this time.

**Comment by lunny** [comment]
Have you set `ROOT_URL` different from `LOCAL_ROOT_URL`.

**Comment by daemhan** [comment]
They are the same.

**Comment by lunny** [comment]
@daemhan You should change them. ROOT_URL should be http/https for user clone/pull/push, LOCAL_ROOT_URL should be your fastcgi protocol address.

**Comment by lafriks** [comment]
Closing as answered, please reopen if not
