### ISSUE TITLE
Migration misses release notes

### ISSUE THREAD

**Issue by IzzySoft** [go-gitea/gitea#7748]
- Gitea version (or commit ref): 1.9.0
- Git version: 2.1.4
- Operating system: Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
When migration a repo from Github or even from another Gitea instance (e.g. as mirror), while tags are coming along, release notes are lost (and probably attachments made to them as well – I did not test that as I have no attachments to any of my releases). Experienced this way with multiple repos:

* Github to Codeberg (Migration)
* Codeberg to my local Gitea (Mirror)
* Github to my local Gitea (Mirror)

Note that Codeberg currently runs Gitea 1.9.0 as well. At least in this constellation (Gitea 1.9.0 → Gitea 1.9.0) I had expected *everything* to come along.

If this is the expected behavior, please count this as a feature request. If not, it's a bug report. Not the highest prio in either case, but not "cosmetical" either (so at least medium :wink:).

**Comment by lunny** [comment]
We support migrating releases from github only. You have to fill github personal token on username and then you will find release/issues/prs options to select.

**Comment by IzzySoft** [comment]
I did that when migrating from Github to Codeberg – but still had to fill the release notes again as they were lost. To clarify: Tags came along and were shown in the "releases" tab. Just the notes (which in Gitea you create via the "New Release" button) were lost. Everything else came along fine.

**Comment by IzzySoft** [comment]
Ah, wait, ignore that: They came along from Github to Codeberg (with the exception of "Drafts without tags", which I already filed as separate issue), just not from Codeberg to my local Gitea. Which would make this issue here a feature request to have this functionality also available when migrating between Gitea instances.

Apologies for my confusion!

**Comment by IzzySoft** [comment]
As the stale bot chimed in: Shall I file this as a separate feature request then (to include all features of Github-to-Gitea migration also with Gitea-to-Gitea migration)?

**Comment by lunny** [comment]
@IzzySoft I think you can rename this issue's title or close this one and open a new one.

**Comment by IzzySoft** [comment]
Thanks @lunny – closing this then in favor of #8380.
