### ISSUE TITLE
Incorrect logging formatting

### ISSUE THREAD

**Issue by gabrieljackson** [go-gitea/gitea#775]
- Gitea version (or commit ref): 25663b58161c48bdc8e9cae900544378dede0d2b
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant

## Description

I searched and didn't see this issue noted anywhere so I figured I would open a new one.

Currently, the logging code is often formatted to output something like `"we ran into an error: %v", err`, but is then passed to something like `log.Fatal()`. This leads to incorrect formatting when the log is written.

Example: https://github.com/go-gitea/gitea/blob/master/cmd/web_graceful.go#L36

```
2017/01/27 15:11:22 4Failed to load https cert file %s: %v0.0.0.0:3000open /data/key.pem: permission denied
```

I have started a local branch to convert many of the log calls from `log.Fatal` to `log.Fatalf` or similar and would be happy to open a PR for it.

Edit: fixed a bunch of typos in the original issue description.

**Comment by bkcsoft** [comment]
>  would be happy to open a PR for it.

Please do 🙂

**Comment by tboerger** [comment]
I would say it's done so far. If you think there are various other places that needs to be fixed feel free to reopen this issue.

**Comment by lunny** [comment]
lost

**Comment by tboerger** [comment]
> lost

What do you mean?
