### ISSUE TITLE
Error 500 - SHH KEY integration fork

### ISSUE THREAD

**Issue by camilopt87** [go-gitea/gitea#7764]
I am using FORK as GUIO client of GITEA. the option REQUIRE_SIGNIN_VIEW IS TRUE. we generate de SSH KEY with fork. We wi add the key en gitea we have a error cod '500'.

Can you help me. How can I integrate FORK with gitea when gitea requiere password to see any page.

- Gitea version (or commit ref):
- Git version:  last
- Operating system: Windows 10
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ x] No
  - [ ] Not relevant
- Log gist:

## Description
 code error 500
...

**Comment by lafriks** [comment]
Check gitea.log for errors
