### ISSUE TITLE
Webhook "Test Delivery" silently drops some "Custom Events"

### ISSUE THREAD

**Issue by gim** [go-gitea/gitea#7768]
- Gitea version (or commit ref): 1.8.3 
- Git version: 2.22.0
- Operating system: Arch
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite

## Description

I attempted to create a Webhook for a new repository that posted to Discord.

As the very first measure after I registered the Webhook I used the 'Test Delivery' button at the bottom right of the 'Update Webhook' form to ensure that the system worked. However, no events were ever forwarded, and the 'Recent Deliveries' list remained empty. (I also tested that no events were posted by substituting the 'Target URL' for an address I control)

When I recreated the Webhook and specified "All Events" rather than "Custom Events" the 'Test Delivery' button worked as expected (using the original 'Target URL').

It feels like this may have occurred because I set the 'Custom Events' to be 'Issues' and 'Issue Comment' only, and the test message posted is "This is a fake commit".

If the above is correct: perhaps it would be worth bypassing the filters, issuing a warning, or tailoring the test message?

**Comment by lafriks** [comment]
I think there was issue for this as currently test button only works for git push events
