### ISSUE TITLE
File looses executable bit after editing through web interface

### ISSUE THREAD

**Issue by jovandeginste** [go-gitea/gitea#7771]
- Gitea version (or commit ref): 1.8.1
- Git version: n/a
- Operating system: n/a
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL) https://try.gitea.io/jovandeginste/test/src/branch/master/script
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

When I edit a file through Gitea's web interface, the file's modes are (re)set to 644, effectively losing the executable bit if it was set.

I understand that it's not trivial to change file modes through the web interface (eg. when creating new files), but I believe existing files should keep their modes.

The git log of the above repository:

```diff
commit 1635a011929aadf493be0863fb936f56b6ed4188
Author: Jo Vandeginste <Jo.Vandeginste@>
Date:   Tue Aug 6 11:42:38 2019 +0200

    Add an executable script
    
    Signed-off-by: Jo Vandeginste <Jo.Vandeginste@>

diff --git a/script b/script
new file mode 100755
index 0000000..516115d
--- /dev/null
+++ b/script
@@ -0,0 +1 @@
+Some command

commit b7aa45df3b4cb3a085e5b10cae36fbf4c8fed170
Author: jovandeginste <jo.vandeginste@>
Date:   Tue Aug 6 09:44:40 2019 +0000

    'script' updaten

diff --git a/script b/script
old mode 100755
new mode 100644
index 516115d..fa29636
--- a/script
+++ b/script
@@ -1 +1,3 @@
 Some command
+
+some edit
\ No newline at end of file
```

**Comment by jovandeginste** [comment]
So... it just won't be fixed then? What a strange procedure!

**Comment by dirien** [comment]
hi,

can we get this issue fixed? This is really annoying, especially when you work on scripts for infrastructure.

**Comment by ViktorNova** [comment]
+1 I can confirm this bug too
Running Gitea 1.9.5

**Comment by jovandeginste** [comment]
Has this been fixed?

**Comment by guillep2k** [comment]
@jovandeginste Yes, we've just merged a PR fixing this on the `master` branch (which will become Gitea 12.0 eventually). See #10607.

**Comment by lafriks** [comment]
It will be in version 1.11.2
