### ISSUE TITLE
How to uninstall / remove / reinstall gitea?

### ISSUE THREAD

**Issue by sky5454** [go-gitea/gitea#7772]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

I'd like to reinstall in My Ubuntu 16.04 for some reason(such as to change a user). And I don't know how to do it.

**Comment by lafriks** [comment]
dump MySQL database, copy all gitea files (you can use `gitea dump` command for that) and backup these files to other storage

**Comment by lafriks** [comment]
such questions should be better asked in [our forum](https://discourse.gitea.io/)
