### ISSUE TITLE
API call (commits/{ref}/statuses) dont work

### ISSUE THREAD

**Issue by DjSni** [go-gitea/gitea#7784]
- Gitea version (or commit ref): 1.9.0 Stable
- Git version: 2.17.1
- Operating system: Ubuntu 18.04.2 LTS (GNU/Linux 4.18.0-21-generic x86_64)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

curl -X GET "https://try.gitea.io/api/v1/repos/gitea/gitea/commits/master/statuses" -H "accept: application/json"

## Description
if i make an API call with "/repos/{owner}/{repo}/commits/{ref}/statuses" i get only an empty output back.

## Screenshots
![Screenshot_107](https://user-images.githubusercontent.com/31524614/62629305-311a8800-b92d-11e9-8087-37be18e6a6cc.png)
![Screenshot_106](https://user-images.githubusercontent.com/31524614/62629308-337ce200-b92d-11e9-9027-54acb3115577.png)
![Screenshot_105](https://user-images.githubusercontent.com/31524614/62629317-3546a580-b92d-11e9-89c0-e12f96e19890.png)

**Comment by sapk** [comment]
status are details attached by CI this is similar to Github API https://developer.github.com/v3/repos/statuses/. In the case of try.gitea.io, there is no CI configurated on this instance so no statuses.

**Comment by sapk** [comment]
After testing on gitea.com
Commit ref seems to work:
https://gitea.com/api/v1/repos/gitea/blog/commits/376fe18505499b3db05c2d9e4913cc141982b793/statuses
but not branch ref
https://gitea.com/api/v1/repos/gitea/blog/commits/master/statuses

**Comment by sapk** [comment]
Furthermore the url fields should be "https://gitea.com/api/v1/repos/gitea/blog/statuses/376fe18505499b3db05c2d9e4913cc141982b793" and not "https://gitea.com/api/v1/gitea/blog/statuses/376fe18505499b3db05c2d9e4913cc141982b793"
