### ISSUE TITLE
API documentation doesn't mention username is returned for users

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#7787]
- Gitea version (or commit ref): 1.10.0-dev
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant

## Description

I noticed that API calls returning user information (e.g. `/api/v1/user` or `/api/v1/admin/users`) include a `username` field, which is missing in the [Swagger](https://try.gitea.io/api/swagger#/user/userGetCurrent) documentation.
A sample return from `https://try.gitea.io/api/v1/user`:
```
{
    "login": "somelogin",
    ...
    "username": "someusername"
}
```

I was also able to reproduce this on a local installation with LDAP backend. It seems like the [definition](https://github.com/go-gitea/gitea/blob/master/templates/swagger/v1_json.tmpl#L9855) just needs to be updated, or am I missing something?

**Comment by 6543** [comment]
this is because of: https://github.com/go-gitea/gitea/blob/master/modules/structs/user.go#L35-L42
"...for backward compatibility"

we fist need update the SDK [Link](https://gitea.com/gitea/go-sdk/src/branch/master/gitea/user.go) and remove it later in a major release

**Comment by lunny** [comment]
Closed as now no `username` but `login`.
