### ISSUE TITLE
Vendor javascript libraries include some LGPL-licensed code

### ISSUE THREAD

**Issue by Nicolas-Duboc-IBM** [go-gitea/gitea#7798]
- Gitea version (or commit ref): 1.6.1, probably previous versions up to current master HEAD 3b97b9efbf9846181d1a6a967e0317d0cf66008f

## Description
The jquery.datetimepicker.js (https://github.com/go-gitea/gitea/blob/3b97b9efbf9846181d1a6a967e0317d0cf66008f/public/vendor/plugins/jquery.datetimepicker/jquery.datetimepicker.js) includes the "Parse and Format Library" copyrighted "2004 Baron Schwartz <baron at sequent dot org>"  and licensed under "GNU Lesser General Public License 2.1". (see at end of file).

So the Javascript licenses displayed at https://try.gitea.io/vendor/librejs.html is not correct.

And more important, the Gitea project is probably not compliant with this license by including it and distributing under an MIT license.

The "jquery.datetimeicker" is itself not compliant either.  This has been reported as issues https://github.com/xdan/datetimepicker/issues/169 and https://github.com/xdan/datetimepicker/issues/299 with no suitable answer I think.

**Comment by lunny** [comment]
blocked by upstream repository and if this keeps a long time, we should change the library.

**Comment by gary-kim** [comment]
I think the LGPL-3.0 license means that as long as the library itself is not relicensed and can be swapped out for a different version by the user, we are still in compliance. Gitea is an open source project so the user can easily recompile with a different version of that library. Feel free to correct me though (I should probably read the whole text at some point. I do use the GPL licenses a lot).

The information being incorrect in librejs.html is an issue though. Let's see what happens with the upstream repo.

**Comment by 6543** [comment]
jquery.datetimepicker.js is not used anymore

and if you look at https://try.gitea.io/js/licenses.txt you can not find `LGPL`

RESOLVED
