### ISSUE TITLE
upgrade from gogs(0.11.59.0627) to gitea(1.9.0) problem

### ISSUE THREAD

**Issue by yourchanges** [go-gitea/gitea#7799]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

try to upgrade from gogs(0.11.59.0627) to gitea(1.9.0)

1. force set version to 13

```
 update version set version = 13;
```

2. failed on migration script : v68, 

```
ORM engine initialization attempt #4/10 failed. Error: migrate: do migrate: Error 3098: The table does not comply with the requirements by an external plugin.
```

because we use mysql group relication, it requires table must has primary key, so re-create follow tables (need improvements):

```
drop table `repo_topic`;

CREATE TABLE `repo_topic` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `repo_id` bigint(20) DEFAULT NULL,
  `topic_id` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UQE_repo_topic_s` (`repo_id`,`topic_id`)
) ENGINE=InnoDB
```

3. failed on migration script: v81,

```
[E] ORM engine initialization attempt #7/10 failed. Error: migrate: do migrate: Error changing u2f_registration counter column type: Error 1146: Table 'gitea.u2f_registration' doesn't exist

```

there is a table named u2_f_registration (need improvements)

```
RENAME TABLE gitea.u2_f_registration TO gitea.u2f_registration;
```

4. failed on migration script: v82,

```
2019/08/08 09:28:16 ...ations/migrations.go:280:Migrate() [I] Migration[82]: hot fix for wrong release sha1 on release table
2019/08/08 09:28:16 .../xorm/session_raw.go:83:queryRows() [I] [SQL] SELECT `id`, `repo_id`, `sha1`, `tag_name` FROM `release` WHERE (is_tag=?) ORDER BY `id` ASC LIMIT 100 []interface {}{false} - took: 690.854µs
2019/08/08 09:28:16 .../xorm/session_raw.go:83:queryRows() [I] [SQL] SELECT `id`, `owner_id`, `name` FROM `repository` WHERE `id`=? LIMIT 1 []interface {}{33} - took: 545.869µs
2019/08/08 09:28:16 .../xorm/session_raw.go:83:queryRows() [I] [SQL] SELECT `id`, `name` FROM `user` WHERE `id`=? LIMIT 1 []interface {}{15} - took: 510.242µs
2019/08/08 09:28:16 routers/init.go:57:initDBEngine() [E] ORM engine initialization attempt #9/10 failed. Error: migrate: do migrate: repository does not exist

```

have no idea how to fix, just delete all the release data to skip.

5.

**Comment by yourchanges** [comment]
Here are table structure compare, it seems miss lost of index and column, but gitea 1.9.0 can run well.

https://drive.google.com/open?id=1LI0Y7OgeO1JrgaZ9vT2g2zjnDOZkv3VJ

**Comment by lunny** [comment]
removed all repositories which lost git data on admin panel and then run this migration.
