### ISSUE TITLE
Issue assignee's cant see their assigned issues in the Dashboard/Issues screen

### ISSUE THREAD

**Issue by slothbag** [go-gitea/gitea#78]
Not sure if there needs to be a row added to issue_user for assignees.. Currently there is not.

**Comment by linquize** [comment]
Duplicate of #69?

**Comment by da-kid** [comment]
@linquize No it isn't. This concerns the listing of issues in the users dashboard.

**Comment by makhov** [comment]
There is a «Assigned to you» link at Issues screen.

I guess, it's a good idea to show assigned issues at Dashboard like at Jira.

**Comment by slothbag** [comment]
This was actually reported as a bug, and is partially fixed in develop branch.  I will close this and open a more accurate issue.
