### ISSUE TITLE
Dump without Zipping

### ISSUE THREAD

**Issue by adrianschneider94** [go-gitea/gitea#7801]
Hi

I have the following case:
I want to setup backups of gitea newly but if all files are packed into one archive, my backup manager (restic) can't do deduplication properly and much more space is used.
So my question is:
Are there any caveats in just copying the files and doing a dump from SQL? Or is there anything extra in the dump command?

Best wishes
Adrian Schneider

**Comment by mrsdizzie** [comment]
That would work fine, and it is probably better to do that if you are already using a different backup system that you can just add more files to.

You can see exactly what it does here:

 https://github.com/go-gitea/gitea/blob/master/cmd/dump.go

**Comment by adrianschneider94** [comment]
Thanks 👌🏼

**Comment by adrianschneider94** [comment]
Little additional question out of interest:
What would happen if the SQL dump and the file dump are made with a delay?
With PITR of the database this should never be an issue, but what would happen else?

**Comment by lunny** [comment]
@adrianschneider94 some features may broken. Currently gitea will save commit status/PR base and head branch name/default branch on database.
