### ISSUE TITLE
Language cookie is not well restaured

### ISSUE THREAD

**Issue by thibaultmeyer** [go-gitea/gitea#7805]
- Gitea version (or commit ref): 1.9.0 built with GNU Make 4.1, go1.12.7 : bindata, sqlite, sqlite_unlock_notify
- Git version: 2.9.5
- Operating system: Linux CentOS
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes
  - [ ] No
  - [ ] Not relevant

## Description
If the Language cookie is deleted or just lost (because it expire but not the user session because of "Keep my session open"). A new cookie is created but is based on Browser "Accept-Language" rather than User profile settings. In my case, Gitea, switch to FR version although in my user profile I have set "English" for the language. 

- If I Logout and login, I get back the right language
- If I just click "Save" on my user profile, the right language come back

## How to reproduce
1. Open session
2. Change Gitea language to something else your Browser language (in my case, Browser is in FR and I want Gitea in EN)
3. Delete "lang" cookie
4. Refresh your page

**Comment by thibaultmeyer** [comment]
Any news about this bug ?

**Comment by Rychu-Pawel** [comment]
Same for me. A bit annoying 😕

**Comment by wxiaoguang** [comment]
It should have been fixed
