### ISSUE TITLE
Label sets don't make sense to a new user

### ISSUE THREAD

**Issue by Mikaela** [go-gitea/gitea#7812]
- Gitea version (or commit ref): (gitea.blesmrt.net) 1.9.0 and (try.gitea.io) 1.10.0+dev-154-gcde95f992  

- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL) - https://try.gitea.io/Mikaela/labeltest/labels
  - [ ] No
  - [ ] Not relevant

## Description

I have recently moved some repositories to Gitea and started using the issue tracker. When I first enter the labels menu, I see the first screenshot.

With the first repository I just created a new label as I assumed that the Label Set means that I am given a single label called "Default" which is not going to help me. With another repository I did accept the Default label set and was surprised that I was given actually useful labels (screenshot 2).

Request: could more information be added between the label set dropdown and the "Use Label Set" button? I wish it would have told me instead something like "*This will create 7 labels; bug, duplicate, enhancement, help wanted, invalid, question and wontfix*". I think having the label explanations visible wouldn't hurt either, but even without them, just the label names would be more helpful to know.

I am also wondering if I can return to this screen somehow with the repositories where I opted to not use a label set and import a label set regardless.

## Screenshots

![bildo](https://user-images.githubusercontent.com/831184/62823235-bf397d00-bb7e-11e9-980d-fa6b2fe998a9.png)

![bildo](https://user-images.githubusercontent.com/831184/62823269-ff98fb00-bb7e-11e9-8599-6037f4c78c08.png)

* * * * *

Edit: potentially related https://github.com/go-gitea/gitea/issues/6055 ?

**Comment by oscarlofwenhamn** [comment]
Not a bad idea, maybe simply list underneath the dropdown a list of labels in a set. "This will create 7 labels; bug, duplicate, enhancement, help wanted, invalid, question and wontfix" feels maybe a bit verbose, but simply something like:

| Default |
*(bug, duplicate, enhancement, help wanted, invalid, question, wontfix)*

or even, if length is an issue:

| Default |
*(bug, duplicate, enhancement, +4)*

**Comment by Mikaela** [comment]
I am able to reproduce at https://try.gitea.io/repo/create.

**Comment by oscarlofwenhamn** [comment]
Definately still a relevant issue
