### ISSUE TITLE
Add quoting mechanism

### ISSUE THREAD

**Issue by MGChecker** [go-gitea/gitea#7818]
- Gitea version (or commit ref): 1.8.2

I would like to be able to quote user contributions in issues, but have no option to copy the source code. That is why I have to re-add the source code of their comments if I want to quote them properly.

It would be much easier if it were possible to view the source of an issue comment and/or if there would be a quoting button, copying the comment you would like to quote with `>` marks on the left into the commenting form.

**Comment by MGChecker** [comment]
GitHub is actually offering the latter, if clicking on the three dots on the right of each comment.

**Comment by MGChecker** [comment]
Where is the value in keeping the count of open issues artificially small with mechanisms like this?

**Comment by guillep2k** [comment]
Perhaps he means this?:

![image](https://user-images.githubusercontent.com/18600385/66613054-7e6bdd80-eb9a-11e9-9f5d-57d42ae5cd3a.png)

**Comment by MGChecker** [comment]
Resolved by  #9043.
