### ISSUE TITLE
Add global setting for org creation

### ISSUE THREAD

**Issue by tboerger** [go-gitea/gitea#783]
We got a user that requested an option to configure globally to allow or disallow the creation of organizations. Currently every user can create an organization, but he needs an option to disable that globally. Maybe we should also add an option per user which can be set by an admin similar to `Maximum Repository Creation Limit` to allow specific users some amount of organizations.

**Comment by lunny** [comment]
It seems no-one to send PR for this. Maybe we need to move this to v1.2

**Comment by lunny** [comment]
@tboerger
