### ISSUE TITLE
Create file in a repository with Rest API (content, encoding and special chars escape)

### ISSUE THREAD

**Issue by fraballi** [go-gitea/gitea#7844]
What is the correct encoding and format for using this endpoint:
http://localhost:3000/api/swagger#/repository/repoCreateFile

I got this error (without base64 conversion):
[{"classification":"DeserializationError","message":"invalid character '\\n' in string literal"}]

Then I converted to base64 the file content and got another error:
Error in char 0

Also, how to escape correctly those special chars during file content extraction?

**Comment by fraballi** [comment]
*Many thanks, on your reply.*
*I had many issues with encoding and JSON deserialization. Ending chars and
line breaks fails for Go/JSON deserializer API, even if a base64 content is
sent to your REST API (Google/Stackoverflow answers)*

*Steps:*

*$my_file="the-file.yml"*
*1) File content:  *file_content=$(iconv -c -f $(file -b --mime-encoding $
*my_file*) -t UTF-8 $*my_file*)
2) Base64 conversion: base64_content=$(echo -n $file_content | base64)

*Choice)*
*I decided to use git push (so I had more than one file). *
*Do you have any API feature that uploads a folder into a repository?*

*;-)*

**Comment by fraballi** [comment]
Thanks, that seems to be the issue: UTF-16 replacing UTF-8.
Which conversion function shall be used for UTF-16?

I missed REST part in my previous thread, but that's it. Using "content"
part in a JSON payload.

Thanks for the help.

**Comment by richmahn** [comment]
I agree. I thought it was odd I had to use UTF-16 to encode it into base64 for our decoder to work. Apparently it works out of the box that way? I'll keep a bookmark on this issue and see if I can get the encoding to work with UTF-8

**Comment by zeeshan1112** [comment]
@richmahn How did you make it work with UTF-16 encoding?
`String bytesEncodedContent = Base64.getEncoder().encodeToString(content.getBytes(StandardCharsets.UTF_16));`
This did not help. I get characters as � in github viewer for special characters.
Any suggestions?

**Comment by richmahn** [comment]
@zeeshan1112 I believe I was just using an online base64 decoder to make the payload to Gitea. I don't think I was actually doing it in an app, but I could be mistaken as it was a year ago.
