### ISSUE TITLE
Default value for SSH_DOMAIN is not that of DOMAIN

### ISSUE THREAD

**Issue by Misterke** [go-gitea/gitea#785]
- Gitea version (or commit ref): 1.0.1
- Git version: 2.7.0
- Operating system: Raspbian Linux 4.4.38-v7+ #938 SMP armv7l GNU/Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io: *How to change app.ini there?*
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist: 

## Description
On transferring my setup from Gogs to Gitea, the SSH "URLs" provided for cloning a new or existing repository, were OK on Gogs, but not on Gitea.  On Gitea the domain part was missing.

I could easily fix it by adding in the [SERVER] section of app.ini, next to the already present DOMAIN value, also an SSH_DOMAIN with the same value.  Apparently, if the latter is absent, Gogs would use the value of the former for SSH domains, but Gitea does not seem to behave in the same way.

I consider this very minor, but the behavior Gogs had, does seem more "nice" and perhaps this difference is worth a mention in the upgrade from Gogs description.

**Comment by tboerger** [comment]
Are you sure that this behavior is the same on latest master?

**Comment by Misterke** [comment]
Just tried latest master: behavior changed in that now without specifying SSH_DOMAIN it seems to use "localhost" instead of just leaving things blank before.  As said, Gogs seemed to use the value of DOMAIN.
