### ISSUE TITLE
How can I get the username from gitea system instead of git local  customization userName in API

### ISSUE THREAD

**Issue by gxgxgxg** [go-gitea/gitea#7852]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
i can get commit informations with a commit hash in gitea API, but the message returned shows the username that printed in git logs,the username doesn't exist in gitea system,it's comes from git local user's setting , like this "git config --global user.name 'xxx'",how can i get the username in gitea system?
...

**Comment by lunny** [comment]
You can get that on your sever via `git config`.
