### ISSUE TITLE
Feature Request: Network Graph

### ISSUE THREAD

**Issue by Misterke** [go-gitea/gitea#786]
## Description

Basic idea: graphic representation of ``git log --graph --oneline.´´

In GitLab and some others called "Network View".  I really hope that gitea implements this soon.  Have been waiting for months for any movement on this on Gogs ...

**Comment by kjellkvinge** [comment]
@Misterke is this a duplicate of #428? If so, this is is implemented now. You can see it on try.gitea.io. There is a link "commit graph" when you look at commit log.

**Comment by Misterke** [comment]
Indeed, this is a duplicate of #428.  I did search for graph, but somehow must have missed that one.  I thought it was weird that this would not have been on other people's top-of-the-list, since there was quite some request for it on Gogs.  Anyway, sorry for the overhead and it seems I should checkout the master builds in favor of the last release ...

**Comment by Misterke** [comment]
Duplicate of #428
