### ISSUE TITLE
Gitea panic

### ISSUE THREAD

**Issue by rvillablanca** [go-gitea/gitea#7860]
- Gitea version (or commit ref): 1.9.0
- Git version: 2.11.0
- Operating system: Debian GNU/Linux 9.6 (stretch)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

https://gist.github.com/rvillablanca/16ca66169dd2c2ddf72bcf9afb5f511e

## Description

Gitea just crashed. I don't know how this happened but it seems related with gravatar library.

## Screenshots

No screenshots

**Comment by lunny** [comment]
Maybe @strk could give some help.

**Comment by strk** [comment]
Someone with access to the logs can tell what paniced...

**Comment by lunny** [comment]
@strk where we could send an issue for package `strk.kbt.io/projects/go/libravatar` ?

**Comment by lunny** [comment]
It seems a lock is need for that map read and write.
![image](https://user-images.githubusercontent.com/81045/63096829-7da33a80-bfa1-11e9-9040-375a82a9f855.png)

**Comment by strk** [comment]
On Thu, Aug 15, 2019 at 06:11:07AM -0700, Lunny Xiao wrote:
> @strk where we could send an issue for package `strk.kbt.io/projects/go/libravatar` ?

As written to that web page: to my email address,
or to the gitlab mirror.

**Comment by rvillablanca** [comment]
Is there any possibility to catch this panic ?

![image](https://user-images.githubusercontent.com/1508272/66210591-91f5e080-e690-11e9-867d-b8c0920796da.png)

**Comment by lunny** [comment]
It should be an upstream library problem.

**Comment by rvillablanca** [comment]
> It should be an upstream library problem.

I agree with this, it is a known library problem but it is also shutting down gitea. I think this should be logged and handled in every request by default in all http handlers. Is it allowed for an unhandled panic to shutting down the whole app ?

**Comment by guillep2k** [comment]
@lunny @strk I've just filed a PR in [go-libravatar](https://gitlab.com/strk/go-libravatar/merge_requests/1) to address this.
