### ISSUE TITLE
Error 1305: FUNCTION gitea.strftime does not exist

### ISSUE THREAD

**Issue by ramlev** [go-gitea/gitea#7861]
- Gitea version (or commit ref): 1.9.0 built with GNU Make 4.2.1, go1.12.7 : bindata, sqlite, sqlite_unlock_notify
- Git version:2.22.0
- Operating system: docker and the image: gitea/gitea:1.9
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x ] MySQL (mariadb)
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x ] No
  - [ ] Not relevant
- Log gist:

## Description

When logging in, the heatmap keeps loading, and if i try the endpoint through the Swagger API, i get this response

{
  "message": "Error 1305: FUNCTION gitea.strftime does not exist",
  "url": "https://my.host.com/api/swagger"
}

**Comment by jolheiser** [comment]
Did you change your database settings without a restart?  
That error is Gitea trying to run a SQLite function in the DB.  
https://github.com/go-gitea/gitea/blob/c42bde719ecf2dd8757453bed18e082d14c1d3fa/models/user_heatmap.go#L25

**Comment by ramlev** [comment]
/close

Docker container restart, and everything works.
