### ISSUE TITLE
Recaptcha doesn't work

### ISSUE THREAD

**Issue by mzch** [go-gitea/gitea#7870]
- Gitea version (or commit ref): 1.9.1
- Git version: 2.20.1
- Operating system: Debian GNU/Linux 10 (Buster)
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://gitfesta.com:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist: gitea.log: https://gist.github.com/mzch/464588c5e49c9841876d10222d04bbc3
                  daemon.log: https://gist.github.com/mzch/e0fb7674cf26d38ce4073d19b4670266

## Description
Using ReCaptcha, gitea shows captcha_incorrect
...

## Screenshots
![FireShot_Capture_003](https://user-images.githubusercontent.com/621178/63052638-d2e83900-bf1a-11e9-9887-43a1f1aacf12.png)

**Comment by Mikanoshi** [comment]
Same on 1.9.2.

**Comment by mzch** [comment]
This issue hasn't fixed in 1.10.0.

**Comment by zeripath** [comment]
Ok, unfortunately the logs you provided didn't give us any helpful information. Which means that it's likely communicating correctly.

Ensure that you have a correct sitekey and secret, and that your URL to recaptcha is correct.

Does Google recaptcha give you any information about what is happening?

There's very little logging in the code - we could add some more. Are you able to build Gitea? If so I could point you in the direction of where to add logging statements.

**Comment by mzch** [comment]
I made sure of my settings and they are correct.
And yes, I can build Gitea from source code. Please instruct where and what code I should add.

**Comment by baxandrei** [comment]
I have same problem with `v1.10.0-rc2 `. It says RECAPTCHA is incorrect (always) event if correct.

**Comment by baxandrei** [comment]
I have modified the source code for Recaptcha by adding the following:
```
func Verify(response string) (bool, error) {
	println("0")
	println(util.URLJoin(setting.Service.RecaptchaURL, apiURL))
	resp, err := http.PostForm(util.URLJoin(setting.Service.RecaptchaURL, apiURL),
		url.Values{"secret": {setting.Service.RecaptchaSecret}, "response": {response}})
	if err != nil {
		println("1")
		return false, fmt.Errorf("Failed to send CAPTCHA response: %s", err)
	}
	defer resp.Body.Close()
	body, err := ioutil.ReadAll(resp.Body)
	if err != nil {
		println("2")
		return false, fmt.Errorf("Failed to read CAPTCHA response: %s", err)
	}
	var jsonResponse Response
	err = json.Unmarshal(body, &jsonResponse)
	if err != nil {
		return false, fmt.Errorf("Failed to parse CAPTCHA response: %s", err)
	}

	println("4")
	return jsonResponse.Success, nil
}
```

First appears in console 0, which means the function was executed, then appears 3.
I never get code 1 (answer could not be sent to google) or code 2 (answer could not be read)
So, the problem is with response code 3.

**Comment by mzch** [comment]
apiURL is incorrect. Its correct URL is `/recaptcha/api/siteverify` I made PR.
