### ISSUE TITLE
No PGP signature on 1.9.1 tag/release

### ISSUE THREAD

**Issue by ArchangeGabriel** [go-gitea/gitea#7874]
Everything is in the title, in contrary to all previous versions since I started packaging Gitea for ArchLinux, this is the first one where the tag/release is not PGP signed. Is it expected? Can you fix that? Thanks.

**Comment by sapk** [comment]
I think it just that it is an other @go-gitea/owners that make this tag and he doesn't use gpg generally. I don't think we enforce gpg on tag. It was just the the owners that previously done the tags use it.

**Comment by sapk** [comment]
The binary is still signed.

**Comment by sapk** [comment]
For insight, on discord maintainer channel I suggest to let as it is instead of re-tagging 1.9.1 and plan to release 1.9.2 soon as they are already fixes after 1.9.1.

**Comment by lunny** [comment]
@sapk I always use gpg when I commit but missed tag.
@ArchangeGabriel Sorry for that and except the tag PGP signature, all binaries have signatures.

**Comment by ArchangeGabriel** [comment]
Of course, but we don’t package from binaries, we always build from sources. ;)

I’m not in favour of re-tagging either actually, because this is generally a bad practice (though some of the common issues with that would not apply here, since the same commit would be tagged).

I’ll disable signature checking for this one specific update, but would appreciate if you release process actually includes enforcing signing the tag in the future. ;) Since you already do for all binaries artifacts, this should not be a big deal. :)

**Comment by anthraxx** [comment]
Just a tiny hint, but one could also upload detatched signatures for the github source tarballs. This could even be done without re-tagging anything :smile_cat:

**Comment by sapk** [comment]
Maybe we should add this issue to milestone 1.9.2 so that we indicate it in changelog as kind of fix from previous release and close it as soon that 1.9.2 is release.

**Comment by techknowlogick** [comment]
Closed as new tag released and it is signed.

**Comment by ArchangeGabriel** [comment]
@lunny I can’t find your public key anywhere, and https://github.com/lunny.pgp is broken. Can you upload it to a keyserver?

**Comment by sapk** [comment]
Should be accessible here : https://pgp.mit.edu/pks/lookup?op=vindex&fingerprint=on&search=0x2D9AE806EC1592E2

**Comment by ArchangeGabriel** [comment]
@sapk That’s not @lunny key.

**Comment by sapk** [comment]
Sorry I read to quickly.

**Comment by lunny** [comment]
@ArchangeGabriel It's strange https://github.com/lunny.gpg return:
```
-----BEGIN PGP PUBLIC KEY BLOCK-----
Note: The keys with the following IDs couldn't be exported and need to be reuploaded C3B7C91B632F738A


=twTO
-----END PGP PUBLIC KEY BLOCK-----
```

@sapk  The tag is not signed by giteabot, but publishers. I tagged v1.9.2 and it displayed well.

![image](https://user-images.githubusercontent.com/81045/63652870-ef486900-c797-11e9-9006-5fb9a4bff819.png)

@ArchangeGabriel maybe it's github's problem?

**Comment by ArchangeGabriel** [comment]
Yes, GitHub is able to verify your signature but not to verify it. That is likely a bug on their side, but they are other places where you could upload your public key. :) Starting by this actual thread. ;)

**Comment by ArchangeGabriel** [comment]
@lunny I still can’t found your key anywhere. Can you upload your _public_ key somewhere accessible please? :)

**Comment by ArchangeGabriel** [comment]
(Or just reupload it on GitHub as instructed by https://github.com/lunny.gpg)

**Comment by lunny** [comment]
Let me try.

**Comment by lunny** [comment]
@ArchangeGabriel After I readded the same gpg public key, it now OK.

**Comment by ArchangeGabriel** [comment]
@lunny Thanks, perfect. :)
