### ISSUE TITLE
Commit status in PR view is incorrect

### ISSUE THREAD

**Issue by markusamshove** [go-gitea/gitea#7877]
- Gitea version (or commit ref): 1.9.1
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite

## Description

The new status view in the PR view correctly shows the statuses from the last commit:

![grafik](https://user-images.githubusercontent.com/2401875/63083783-e19a1480-bf49-11e9-92ca-0141a9095cca.png)

1. However the PR overview within the repository doesn't show any status:

![grafik](https://user-images.githubusercontent.com/2401875/63083844-0a220e80-bf4a-11e9-98cf-4cf33acc45ef.png)

2. When I look into my dashboard, the overview shows the status of that specific PR on the wrong PR (notice the awesome screenshotting skills with hovering over the link, you can see the difference between the organistations Vorlagen and Java):

![grafik](https://user-images.githubusercontent.com/2401875/63084086-ab10c980-bf4a-11e9-9822-05392a0777ed.png)

3. The same issue as the one of the dashboard sometimes shows up in the PR list, where a status check is annotated to a wrong PR (e.g. PR 171 showing the status of PR 70).

You can observe the first issue (status not showing up) on gitea.com: https://gitea.com/gitea/tea/pulls

All the PRs have a status check by CI and none shows them on the PR view.

I've waited with the creation of this issue for release 1.9.1, as I thought #7807 would fix them, but that wasn't the case.

**Comment by lunny** [comment]
closed by #8316
