### ISSUE TITLE
Add longer activity periods

### ISSUE THREAD

**Issue by noerw** [go-gitea/gitea#7879]
- Gitea version (or commit ref): 1.9.1

It would be great to have an activity overview for longer periods (yearly, all time) to get a feel for a projects scope over its full life time.

Was the maximum value of 1 month a performance consideration?

**Comment by hamarb123** [comment]
I would like an all time activity period please, I am not bothered about the performance of it, I also do not mind if it has to be enabled in a setting somewhere.

Thanks :)

**Comment by lafriks** [comment]
This is already fixed by #8829. It added yearly period. All-time period would be performance overkill

**Comment by noerw** [comment]
This is not a fix. To reiterate @hamarb123:
Can we let users (i.e. admins of small personal instances) decide what a performance overkill is? i.e. make 1 month the default max, but give the option to specify higher time ranges.

(Also: To make this view scalable, we could compute & store its state on each push, instead of an expensive query. Though I'm not sure about the complexity-usefulness tradeoff here.)
