### ISSUE TITLE
Bad default commit message of file upload in root directory

### ISSUE THREAD

**Issue by noerw** [go-gitea/gitea#7883]
- Gitea version (or commit ref):1.9.1
- Git version: 2.21.0
- Operating system: fedora 30
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes https://try.gitea.io/norwin/test/src/branch/master/
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
Uploading a file and not entering a commit message results in a commit message like `Uploaded files to '<dir>'`.
When files are uploaded to the root directory, the content inside the quotes is empty.

## Screenshots
![image](https://user-images.githubusercontent.com/7880552/63121826-e46e2700-bf94-11e9-9744-b7d6f0d1b97f.png)

**Comment by lafriks** [comment]
any suggestions on what it should be?

**Comment by fnetX** [comment]
`Upload files to '/'` sounds better. (Just generally adding a / before the var). Or, setting it to
`Upload files to root` (without quotes to differ from "root" dir), but this would probably require more than changing one line ...

**Comment by zeripath** [comment]
@fnetX that seems simplest. Fancy putting the fix in? It's likely a template issue.

**Comment by fnetX** [comment]
It's a translation thing.
`editor.upload_files_to_dir = Upload files to '%s'`
Should I somehow add the / to the string that is inserted there and hope it doesn't break, or update the locales? If the latter, how does this work? I've only been working as a translator so far, not as someone that changes the original string ...
