### ISSUE TITLE
error upgrade

### ISSUE THREAD

**Issue by bajins** [go-gitea/gitea#7886]
need to replace the binary file name after the upgrade, otherwise there will be an error in the push!

can be solved with commandsc
```bash
grep -rl "gitea-1.8-linux-amd64" ./* | xargs sed -i s/"gitea-1.8-linux-amd64"/"gitea-1.9.0-linux-amd64"/g
```

**Comment by techknowlogick** [comment]
Thank you for commenting this :)

There is a built in utility in Gitea that does this, if you go to admin dashboard and run the "Resynchronize pre-receive, update and post-receive hooks of all repositories." task.
