### ISSUE TITLE
Assigning a user or adding a label to an issue is not registered and also not updates the last-changed date/time

### ISSUE THREAD

**Issue by rikvdh** [go-gitea/gitea#789]
- Gitea version (or commit ref): master
- Git version: 2.1.4
- Operating system: Debian
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

When changing milestone, assignee and/or labels the last modified is not updated and also are these mutations not logged for issues/pull-requests.

Having this traceability is greatly appreciated.

**Comment by lunny** [comment]
This has been resolved I think. Please feel free to reopen it.
