### ISSUE TITLE
[Feature Request] Labels with icons

### ISSUE THREAD

**Issue by lonix1** [go-gitea/gitea#7891]
I've searched for similar issues but didn't find any (well, in page 1 anyway :smile:).

It would be nice to be able to use icons inside labels, the same way you sometimes see on Github and StackOverflow.

So for example, the stackoverflow "angular" label has a little angular logo inside it. And on github some repos show a little bug inside the "bug" label.

**Comment by jolheiser** [comment]
This is already possible with emoji.

https://try.gitea.io/jolheiser/Test1/labels

**Comment by silverwind** [comment]
Imho, keep it to emojis only.

**Comment by lonix1** [comment]
@jolheiser nice!
