### ISSUE TITLE
Closing issues keywords should be configurable

### ISSUE THREAD

**Issue by guillep2k** [go-gitea/gitea#7897]
- Gitea version (or commit ref): v1.9
- Git version:  -
- Operating system: -
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

[Issue close keywords](https://help.github.com/en/articles/closing-issues-using-keywords) should be translated. Perhaps parsed according to the PR creator's language.

See [models/action.go](https://github.com/go-gitea/gitea/blob/master/models/action.go) `issueCloseKeywords`

**Comment by techknowlogick** [comment]
We have WIP keywords be configurable via app.ini, perhaps something similar for close keywords?

**Comment by guillep2k** [comment]
Using the translation files sounds more like the Gitea way. 

> The goal of this project is to provide the easiest, fastest, and most painless way of setting up a self-hosted Git service.

😊

**Comment by lunny** [comment]
@guillep2k This should not be on translation file but follow WIP keywords. For Chinese we prefer close the issue via all these keywords `close,closed,fix,fixed,resolve,resolved,关闭,修复,解决`. A configuration item is better I think.

**Comment by guillep2k** [comment]
I have no problem of going with a setting for this particular case.

**Comment by guillep2k** [comment]
Thinking about it a little further, using translations will introduce a breaking change every time the translations are updated, so a setting is much better in that regard.

**Comment by sapk** [comment]
For an other PR, what about adding a advanced part at the installation page allowing to auto setup specific local config and filled them from translation file?

**Comment by guillep2k** [comment]
@sapk  Sounds nice. We should make a TODO list of features to implement on that page.
