### ISSUE TITLE
Adding an issue to a repo with multiple collaborators causes pk violation

### ISSUE THREAD

**Issue by slothbag** [go-gitea/gitea#79]
It appears a row for every collaborator in a repo is inserted into "issue_user" table when creating a new issue, however this table has a primary key on ID and is failing due to primary key violation.

**Comment by makhov** [comment]
Don't reproduce

**Comment by slothbag** [comment]
I just tried with latest master branch.. still happening. Steps to reproduce..

1. Create new repo
2. Add a 2nd user account to gitea
3. Add 2nd user from step 2 as a collaborator to repo from step 1
4. Create a new issue in repo.. click save

You will see the error ```pq: duplicate key value violates unique constraint "issue_user_pkey"```

**Comment by makhov** [comment]
I see. I saw at develop branch.

**Comment by slothbag** [comment]
So did this get fixed or is it already fixed on develop branch?

**Comment by makhov** [comment]
Already fixed on develop branch.

**Comment by slothbag** [comment]
Cool, thanks!
