### ISSUE TITLE
API tags (endpoint /tags and /git/tags)

### ISSUE THREAD

**Issue by DjSni** [go-gitea/gitea#7902]
- Gitea version (or commit ref): 1.10.0+dev-188-g2d0b90c96
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL) see description
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

if i query the list of tags via the API "https://try.gitea.io/api/v1/repos/gitea/gitea/tags" i get the ID or SHA of the tag.
A timestamp should also be specified there.

Example Current:
`[{"name": "v1.9.1", "id": "ab23e4b7f4cd0caafe0174c0e7ef6d651ba72889", "commit":{"url": "https://try.gitea.io/api/v1/repos/gitea/gitea/git/commits/ab23e4b7f4cd0caafe0174c0e7ef6d651ba72889", "sha": "ab23e4b7f4cd0caafe0174c0e7ef6d651ba72889"}, "zipball_url": "https://try.gitea.io/gitea/gitea/archive/v1.9.1.zip", "tarball_url": "https://try.gitea.io/gitea/gitea/archive/v1.9.1.tar.gz"}]`

If you now go further and use the ID or SHA value "ab23e4b7f4cd0caafe0174c0e7ef6d651ba72889".

https://try.gitea.io/api/v1/repos/gitea/gitea/git/tags/ab23e4b7f4cd0caafe0174c0e7ef6d651ba72889

you get the feedback:
`{"message": "object does not exist [id: ab23e4b7f4cd0caafe0174c0e7ef6d651ba72889, rel_path: ]", "url": "https://try.gitea.io/api/swagger"}`

EDIT:
according to swagger, this should be the kind of thing you're supposed to spend:

`{
  "author": {
    "avatar_url": "string",
    "created": "2019-08-22T01:43:31.399Z",
    "email": "user@example.com",
    "full_name": "string",
    "id": 0,
    "is_admin": true,
    "language": "string",
    "last_login": "2019-08-22T01:43:31.399Z",
    "login": "string"
  },
  "commit": {
    "author": {
      "date": "string",
      "email": "user@example.com",
      "name": "string"
    },
    "committer": {
      "date": "string",
      "email": "user@example.com",
      "name": "string"
    },
    "message": "string",
    "tree": {
      "sha": "string",
      "url": "string"
    },
    "url": "string"
  },
  "committer": {
    "avatar_url": "string",
    "created": "2019-08-22T01:43:31.399Z",
    "email": "user@example.com",
    "full_name": "string",
    "id": 0,
    "is_admin": true,
    "language": "string",
    "last_login": "2019-08-22T01:43:31.399Z",
    "login": "string"
  },
  "html_url": "string",
  "parents": [
    {
      "sha": "string",
      "url": "string"
    }
  ],
  "sha": "string",
  "url": "string"
}`

**Comment by DjSni** [comment]
@richmahn 
hmm... ok that may be so, but then it should also be explicitly in the swagger that only "annotated tags" are supported.
in my opinion all tags should be supported, otherwise you might want to change the endpoint to avoid confusion.

**Comment by DjSni** [comment]
cool, but could you add a timestamp to both endpoints /tags and /git/refs/tags?
That would make my work a lot easier.

**Comment by DjSni** [comment]
Thanks, but...
currently I'm doing an API query to get all the tags (but the used system requires a timestamp from each tag) so now I need to do an extra query to get the timestamp.
Since tags can also be commits, you have to do 2 different queries for each tag. I find the whole thing very complex "only" to get a date.

**Comment by sapk** [comment]
Details info added in #7989. Thanks @richmahn.
@DjSni If the issue still need work feel free to re-open it.

**Comment by DjSni** [comment]
That's exactly how I'd like it.

**Comment by sapk** [comment]
Maybe a additionnel  query param `with_timestamp` with a omitempty field in go struct ? By default this would output Github compatible result and additional data if requested.
