### ISSUE TITLE
Opening empty repository -> error 500

### ISSUE THREAD

**Issue by alneo** [go-gitea/gitea#7914]
- Gitea version (or commit ref): 1.9.1
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:
2019/08/19 16:18:03 ...ules/context/repo.go:594:func1() [E] GetBranches: No branches in non-empty repository /gitea-repositories/xxxxxxxx/xxxxxxxxxxx
2019/08/19 16:18:03 ...s/context/context.go:137:HTML() [D] Template: status/500
## Description

I did an update from 1.7.4 to 1.8.3 and 1.9.1 and in some repositories I get a 500 error
files exist along the path gitea-repositories
How to restore repositories?

**Comment by typeless** [comment]
If you can open the settings page of the repository, try to select a default branch.

**Comment by abread** [comment]
Happened to me as well. I'm not sure if it was introduced in 1.8 or 1.9.
Settings are inacessible and there are indeed no branches.

A branch is just a "pointer" to a commit, so until something is commited no branches actually exist

**Comment by lunny** [comment]
@abread how did you create that repository on gitea?

**Comment by abread** [comment]
Just the regular create button, without initializing it. At least one with 1.7.x/1.8.x, the others with older versions.

On August 23, 2019 2:40:39 AM UTC, Lunny Xiao <notifications@github.com> wrote:
>@abread how did you create that repository on gitea?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/go-gitea/gitea/issues/7914#issuecomment-524150235

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by typeless** [comment]
Can you query the database for the `is_empty` column of the `repo` table?
This column has been migrated from `is_bare` recently.
The index would probably need to be re-generated.

As per https://github.com/go-gitea/gitea/blob/master/modules/context/repo.go#L563.
It should return from the function normally if the repo is empty.

**Comment by abread** [comment]
That seems to be the issue `is_empty` is `NULL` on all repositories except the ones that are not empty and were visited, which are `0`.

**Comment by nuno-silva** [comment]
Please don't close.

**Comment by zeripath** [comment]
@nuno-silva are you still suffering this? What version of Gitea are you using?

Have you tried setting the values of is_bare manually?

**Comment by nuno-silva** [comment]
@zeripath yes, I have one repo still affected, using:
  - gitea 1.9.3
  - Go1.12.8
 
The repository has no commits (yet).
```
MariaDB [gitea]> select id,lower_name,is_bare,is_mirror,is_fork,is_empty,is_archived from repository where lower_name like 'laboratorios';
+-----+--------------+---------+-----------+---------+----------+-------------+
| id  | lower_name   | is_bare | is_mirror | is_fork | is_empty | is_archived |
+-----+--------------+---------+-----------+---------+----------+-------------+
| 484 | laboratorios |       1 |         0 |       0 |     NULL |        NULL |
+-----+--------------+---------+-----------+---------+----------+-------------+
1 row in set (0.00 sec)
```

note: this is the same gitea instance as @abread .

**Comment by holmesb** [comment]
In [my case](https://github.com/go-gitea/gitea/issues/8023), the problem was a mismatch between the port memcached was listening on and app.ini setting:

```
[cache]
HOST     = 127.0.0.1:<PORT>
````

**Comment by zeripath** [comment]
Just set the is_bare value to the correct thing for that repo and it will never happen again. You suffered a migration bug when changing versions - that migration is now fixed and should never happen again.

**Comment by nuno-silva** [comment]
@zeripath alright. You mean set `is_empty`, right (as @zeripath said)?. That works. Thank you!
