### ISSUE TITLE
Defining a custom SSH path for pulling/cloning repositories

### ISSUE THREAD

**Issue by christhulhu** [go-gitea/gitea#792]
- Gitea version -(or commit ref)-: 1.0.1
- Git version: 1.9.1
- Operating system: Ubuntu Linux 14.04LTS
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant

## Description
I have a server with following setup:

* I run a vserver with plesk as administration interface
* My domain and all subdomains are executed in the context of one user
* The files of my domain are under ``/var/www/vhosts/<domain>``
* My Gitea-installation is in a subdomain unter ``/var/www/vhosts/<domain>/<subdomain>``
* I separated the server from my repositories
 * Gitea runs under ``/var/www/vhosts/<domain>/<subdomain>/web``
 * The repositories are stored under ``/var/www/vhosts/<domain>/<subdomain>/gitea-repos``
* The domain-user is in a chroot-jail under ``/var/www/vhosts/<domain>``

### Problem
Gitea shows an URL where to clone/pull from a repository. It is in format
```
ssh://<domainuser>@<subdomain>:<port>:/<giteauser>/<repository>.git  
```
This would map to the absolute path ``/var/www/vhosts/<domain>/<giteauser>/<repository>.git`` - because of the chroot-jail.
But my repositories are _not_ under this absolute path, but in ``/var/www/vhosts/<domain>/<subdomain>/gitea-repos/<giteauser>/<repository>.git``

I tried to fix this issue by symlinking my repos to ``/var/www/vhosts/<domain>/repos`` and tell Gitea that it should use ``/repos`` as affix to its root-path.
I configured the ``app.ini`` file under the section ``[server]`` for both key ``DOMAIN`` and ``ROOT_URL``. I changes both to ``https://<subdomain>/repos`` with would bring the expected result in the Gitea GUI. The new pull/clone url would be ``ssh://<domainuser>@<subdomain>:<port>:/repos/<giteauser>/<repository>.git ``

But it also broke the Gitea webinterface, because Javascript and CSS cannot be loaded from the ROOT_URL ``<subdomain>/repos``. So without styling and Javascript the Gitea web is unusable.

I also tried to change the ``SSH_DOMAIN`` to ``<subdomain>:<port>/repos`` but it didn't have any effect.

### Remark
Working with http(s) is fine, all paths are mapped in a correct way.

## Request
Is there any possibility how to configure Gitea that it should use a custom SSH-Path for pulling/cloning?
Am I missing the right configuration? Or is this really a missing feature?

**Comment by bkcsoft** [comment]
Revert all configs you've done and only change
```
[repository]
ROOT = /path/to/gitea-repos
```
This will "do the right thing" and repos will be available at `git@domain:owner/repo.git` and `https://domain/owner/repos.git`.

**Comment by christhulhu** [comment]
Hi bkcsoft,

thanks for the hint. But since there were other problems with ssh-login under the chroot-jail, I took another solution:
* running gitea as a new user on the vps
* leaving the proxy-setup on the domain-user, forwarding the requests to gitea, running under another user

Now everything works fine. Thank you anyway.

Chris
