### ISSUE TITLE
Proposal: add repository to team from repository page

### ISSUE THREAD

**Issue by guillep2k** [go-gitea/gitea#7925]
- Gitea version (or commit ref): v1.9

## Description

Currently, to add a repository to a team the user needs to go: organization, teams[team], repositories, add. It would be cool if we could also do that from the repository pages, e.g. a "Teams" tab next to "Collaborators" or perhaps the "Collaborators" tab could serve both purposes.

The rationale is that a repository might have several teams involved (development, testing, etc.), so adding all teams from the same page without losing sight of the repository itself is desirable.

This will also have the advantage that the user can see to which teams is the repository assigned, without checking teams one by one.

**Comment by davidsvantesson** [comment]
Implemented in 1.10 (see referenced pr above)

**Comment by zeripath** [comment]
@davidsvantesson do you think we can close this issue?

**Comment by lunny** [comment]
@zeripath I think yes.
