### ISSUE TITLE
Dangling commits show 'undefined' branch

### ISSUE THREAD

**Issue by silverwind** [go-gitea/gitea#7928]
Dangling commits created like
```
git commit --allow-empty -m "this is force-pushed over"
git push
git reset --hard HEAD~1
git push -f
```
show a `undefined` branch on the UI:

https://try.gitea.io/silverwind/symlink-test/commit/18b49740a6d482078d0d7f8b8eaa2c9b28b32cd2

<img width="296" src="https://user-images.githubusercontent.com/115237/63421140-5ff22d00-c408-11e9-976d-4a666a1ca10c.png">

I think they should not show a branch indicator at all.

**Comment by lunny** [comment]
I think this has been resolved?

**Comment by zeripath** [comment]
appears to be. Closing as fixed.
