### ISSUE TITLE
Unable to add default webhook for Telegram

### ISSUE THREAD

**Issue by rchavik** [go-gitea/gitea#7932]
- Gitea version (or commit ref): 1.9.1
- Git version: 2.7.4
- Operating system: Linux 4.4.0-116-generic 140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X] No
  - [ ] Not relevant
- Log gist:

## Description

Tried adding Telegram as a default webhook resulted in a empty tab pane:

   Site Administration -> Default Webhooks ->  Add Webhook -> Telegram

Note: Adding Telegram webhook manually by repository does work.

## Screenshots

![image](https://user-images.githubusercontent.com/39490/63478361-c2543780-c4b3-11e9-9131-416b4168062f.png)

**Comment by gary-kim** [comment]
Looks like that was forgotten when the webhook was added. I'll make a PR with a fix.
