### ISSUE TITLE
URL to tag goes to branch if they have the same name

### ISSUE THREAD

**Issue by davidsvantesson** [go-gitea/gitea#7936]
- Gitea version (or commit ref): 1.10.0+dev-198-g111d31d68
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant

## Description
When a branch and a tag has the same name, entering the URL to the tag shows the branch instead.

Example: https://try.gitea.io/merle_noir/TestName/src/tag/BranchAndTagNameSame is URL to tag but it shows the content of the branch with the same name.

**Comment by lunny** [comment]
What do you think the proper behaviour?

**Comment by davidsvantesson** [comment]
Expected behavior:

- _{Repo}/src/branch/{refname}_: 404 if branch {refname} doesn't exist. If exist show branch.
- _{Repo}/src/tag/{refname}_: 404 if tag {refname} doesn't exist. If exist show tag.

Actual behavior:
- _{Repo}/src/branch/{refname}_: 404 if branch {refname} doesn't exist. If exist show branch.
- _{Repo}/src/tag/{refname}_: 404 if tag {refname} doesn't exist. If exist show **branch (in first case, if it exist)** otherwise show tag.

The reason for this is in _/modules/context/repo.go, func RepoRefByType_, the code first correctly determines if the branch or tag exist (depending on what is requested), but then first check if branch exist (line 610) regardless if branch or tag was requested.
