### ISSUE TITLE
Debugging/troubleshooting "System Notices"

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#7938]
- Gitea version (or commit ref): 1.9.1
- Git version: 2.20.1
- Operating system: Debian buster
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [x] Not relevant
- Log gist: n/a

## Description

System notices are reporting
```
Error while getting .editorconfig file: reference not found...
```
However I have no idea how to actually troubleshoot this problem because I have no context (not the missing editorconfig but how to get more information or root cause system notices). With just the type, description, and creation date I'd have to monitor all of our users actions to try and trace this...

I understand the usage of editorconfig (or what it is), I'm mainly asking:
1. What is the intended pathway to troubleshoot "System Notices"?
2. Can the "System Notices" provide more context in the future?

## Screenshots
![system_notices](https://user-images.githubusercontent.com/1933941/63519563-33e6b280-c4c1-11e9-8a29-1ed4548460f1.png)

**Comment by enckse** [comment]
FYI: I got lucky and was able to see the error and an action I performed that caused it (browsing to an uninitialized repository)

This certainly needs to be easier to figure out in the future

**Comment by charlesmorin** [comment]
Got the exact same thing. Impossible to reproduce as the message is way to vague. System logs isn't providing more details.

**Comment by enckse** [comment]
I'm fine to close this at this point with the assumption that #7943 will eventually be resolved/make diagnosing this specific case better.
