### ISSUE TITLE
Browsing to an uninitialized repository results in "System Notice" about editorconfig

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#7943]
- Gitea version (or commit ref): 1.9.1
- Git version: 2.20
- Operating system: Debian buster
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No (as it requires admin rights to view system notices)
  - [ ] Not relevant
- Log gist:

## Description

1. I have a repository that is not initialized
2. When I browse to it in the Web UI it shows the page about being not initialized
3. This is causing a "System Notice" about editorconfig to occur in the admin panel (I believe this is a bug)

```
Error while getting .editorconfig file: reference not found...
```

**Comment by lunny** [comment]
related with #7938

**Comment by enckse** [comment]
This is still opened, until something changes you'll continue to see potentially confusing/untrackable System Notices about this

**Comment by WozSoftware** [comment]
Just installed 1.9.6 with MSSql and can confirm get the same issue
