### ISSUE TITLE
Failed to synchronize tags to releases for repository

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#7945]
- Gitea version (or commit ref): 09ca391
- Git version: 2.22.0
- Operating system: macOS
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (https://try.gitea.io/yasuokav/cecil)
  - [ ] No
  - [ ] Not relevant
- Log gist:

```
...odels/repo_mirror.go:301:runSync() [E] Failed to synchronize tags to releases for repository: pushUpdateAddTag: GetTag: object does not exist [id: 0.11, rel_path: ]
```

## Description

This repository can reproduce this problem: https://github.com/jbevain/cecil.git

This error occurs when migrating or synchronizing the repository.

https://github.com/go-gitea/gitea/blob/ca6fb004ac50fc924861112403895d637c6a2d1d/modules/git/repo_tag.go#L156-L162

`show-ref` in this repository returns two lines of results instead of one
```
$git show-ref 0.11
12da1bf7e0e10278e05eeb23adfc72760bbb6668 refs/heads/release/0.11
ec814ea6357bff732a6217e9c3b263ea0fb450c0 refs/tags/0.11
```

**Comment by yasuokav** [comment]
@richmahn (#7138)

**Comment by j123b567** [comment]
This is not enough. If you have tag name `a/v1` and `v1` this still fails.

**Comment by sapk** [comment]
Maybe we should use go-git nos for this func : https://godoc.org/gopkg.in/src-d/go-git.v4#Repository.Tag
