### ISSUE TITLE
Git push first tag failed.

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#7946]
Gitea version: 1.9.2

This is the first time to push a tag to this repository. The tag push succeed but display an error information.
I have added protected branch on master and I'm the site administrator and I'm in the white list of push.
![image](https://user-images.githubusercontent.com/81045/63566326-42a39700-c59f-11e9-9a36-d217eed5ba62.png)

**Comment by lunny** [comment]
Just found the problem.

When pushing a tag, gitea will create two webhooks. 

https://github.com/go-gitea/gitea/blob/09ca3912301eb77e4f30c80753fbe0f0735dc5f2/modules/repofiles/action.go#L161

One is kind named `models.HookEventCreate`, another is `models.HookEventPush`. When you configured a webhook trigger `push`. It will read `api.PushPayload.Commits` but it's `nil` so that it will panic. and you will received above error.

And I think deleting a tag will also get that error.

**Comment by hooch** [comment]
👋 Finding myself here after upgrading from 1.7.4 to 1.9.2.

**Comment by guillep2k** [comment]
In any case, the function should fail gracefully for this kind of error (log something and move on).

**Comment by Sebazzz** [comment]
Is this fixed in 1.9.5? I cannot reproduce this issue.

**Comment by lunny** [comment]
One instance (1.9.5) I'm using still have this problem.
