### ISSUE TITLE
Unable update peronsal/repository/orgnization avatars

### ISSUE THREAD

**Issue by pan3793** [go-gitea/gitea#7955]
I just use official managed server gitea.com, but when I update avatar of person or organization, always return error `Bad Request: no CSRF token present`

**Comment by HaoweiCh** [comment]
save here, but only organization

**Comment by lunny** [comment]
If that's gitea.com instance problem but not gitea's, Please go to https://gitea.com/gitea/gitea.com/issues to file an issue.

**Comment by HaoweiCh** [comment]
`gitea version: 1.8.3 built with go1.12.6 : bindata, sqlite, sqlite_unlock_notify`

running in Docker...

I cannot update org avatar

**Comment by pan3793** [comment]
close this, new issue move to https://gitea.com/gitea/gitea.com/issues/4

**Comment by lunny** [comment]
I found that this is a bug of gitea but not a configuration error of gitea.com

**Comment by lunny** [comment]
I can reproduce this on macOS Chrome 76.
But I cannot reproduce this on macOS Firefox 68 and Safari 12.1.1

**Comment by lunny** [comment]
It should be related with serviceworker.

**Comment by pan3793** [comment]
Ummm, I have only tested it on macOS Chrome before, now it seems that the temporary solution is just to use Safari to upgrade avatars.

**Comment by iHaPBoy** [comment]
I found this bug in Chrome, only **NOT Chinese** filename can uploaded.

**Comment by steadfasterX** [comment]
> I found this bug on Chrome (macOS), only **letters, numbers, and the "-" and "+" characters** filename could uploaded.

same here (Linux) but it affects also german Umlauts (äüö)

**Comment by almindor** [comment]
Same here on a fresh install on arch linux server using Brave browser
