### ISSUE TITLE
Issues related commit activity (reference) is missing

### ISSUE THREAD

**Issue by davydov-vyacheslav** [go-gitea/gitea#7968]
- Gitea version (or commit ref): 1.10.0+dev-189-g08c63190c
- Reproducible on https://gitea.com

## Description

Somewhere in time, there is was an feature of issues mention /reference like this:
<img width="881" alt="Снимок экрана 2019-08-25 в 10 09 07" src="https://user-images.githubusercontent.com/9931946/63646754-8c67bb00-c720-11e9-8778-4283446977b7.png">

Now looks like it missed:
<img width="1207" alt="Снимок экрана 2019-08-25 в 10 01 59" src="https://user-images.githubusercontent.com/9931946/63646753-8c67bb00-c720-11e9-88b1-91763796ebee.png">

The link to the issue is: https://gitea.com/davs/testrepo/issues/1 

Is there a way to get this feature back?

**Comment by davydov-vyacheslav** [comment]
Ok. Got it. Just one comment: why “Fixed” has been determined and the issue has been closed after pushing the commits?

**Comment by davydov-vyacheslav** [comment]
@mrsdizzie but according to the image, the colon is just after the issue number. And it works for closing the issue, but not works to make reference. That was the just confusion of logic difference. 

Anyway, the answer of how it was worked has been obtained. Thank you. 

Should I close the issue or it’d be the reference for further someone’s PR?

**Comment by davydov-vyacheslav** [comment]
Is there a way to prioritize the issue?

**Comment by mrsdizzie** [comment]
https://github.com/go-gitea/gitea/pull/8101 should fix this particular case when it is done I believe

**Comment by lunny** [comment]
Should be closed by #8101
