### ISSUE TITLE
Docker sshd_config unconfigured for gitea

### ISSUE THREAD

**Issue by GijsVermarien** [go-gitea/gitea#7969]
- Gitea version (or commit ref): Gitea version 1.10.0+dev-209-g8c24bb9e4 built with GNU Make 4.2.1, go1.12.9 : bindata, sqlite, sqlite_unlock_notify
- Git version: git version 2.22.0
- Operating system: Docker version 18.09.7, build 2d0083d on 18.04.3 LTS (Bionic Beaver)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:

## Description
When I recreated my docker file, the ssh options were not working anymore, I now get the following error when trying to connect: 
`user@domain.com: Permission denied (publickey).`

The gitea logs show that: 
`User user from XX.XXX.XXX.XXX not allowed because not listed in AllowUsers`
`Connection closed by invalid user user XX.XXX.XXX.XXX port 46XXX [preauth]`

The AllowUsers file in /etc/ssh/sshd_config indeed only contains:
AllowUsers git

Is there any way to solve this problem so I can again use gitea, I cannot pull/push anything because of this issue.

I saw that issue #5623 relates to this, and the code reflects that gitea should be added as a user to AllowUsers, but somehow it is not.

**Comment by jpellegrini** [comment]
That file (`ssd_config`) is generated by s6 from a template, which is in `docker/root/etc/templates/sshd_config`. The only variable in the template is `SSH_PORT`. The user in `AllowedUsers`  should also be a variable.

Try modifying this line

```
AllowUsers git
```

into this:

```
AllowUsers ${USER}
```

in the template. Then rebuild the docker image. When you log into the container, you'll see the correct line in `/etc/ssh/sshd_config`.

**Comment by lunny** [comment]
This should be resolved by #8094

**Comment by GijsVermarien** [comment]
It is indeed resolved, I recreated the docker container with the latest image and it is working just fine now!
