### ISSUE TITLE
"Username or password is not correct" when running as windows service

### ISSUE THREAD

**Issue by DocumentRoot** [go-gitea/gitea#797]
- Gitea version (or commit ref): 1.0.1
- Git version: 2.11.0.windows.1
- Operating system: Windows 10
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
When running Gitea as windows service i cannot login to it, got "Username or password is not correct".
I have only one account, its root:password, password is copied from keepass, so no mistake here.
I stop service, run 'gitea web' manually, and now i can login. but not when i run it as a service.
...

**Comment by lunny** [comment]
Could you test it in master? I think there is already a PR to fix this.

**Comment by DocumentRoot** [comment]
Same on master (Gitea Version: 1.0.0+149-g8bc4319)
(I'm sure I recreate service with new name and gitea-master-windows-4.0-amd64.exe target)

I realized what happens, when I tried to clean install database running Gitea as a service...

Manual `gitea web` uses `data/` directory to store db,
but gitea service uses `c:\windows\system32\data` (even if relative to gitea.exe `data/gitea.db` exists)

So I delete c:\Windows\System32\data and create symlink:
`mklink /d c:\Windows\System32\data d:\bin\gitea\data`

Now it works, I can login to my old db.

**Comment by tboerger** [comment]
So you have to set proper paths within the app.ini, not really a Gitea bug.

**Comment by DocumentRoot** [comment]
Yes it can be fixed by app.ini, but the bug is default settings `PATH = data/gitea.db` leads to various paths if Gitea runs as `gitea.exe web` or as a service. User should realize it somehow and fix it.

Also, is this correct that the user app stores anything in c:\Windows\?
At major Windows upgrades, or at clean Windows install, when people make backup of c:\Users, it will lead to db loss.

**Comment by tboerger** [comment]
If the custom path isn't defined via environment variable it takes on Unix systems the path relative to the binary, for Windows it seems to be a different path. This is the current default behavior and it should be still the same behavior as Gogs.
