### ISSUE TITLE
RocketChat notification for pull request comment has not working hyperlink

### ISSUE THREAD

**Issue by mathysie** [go-gitea/gitea#7973]
- Gitea version (or commit ref): 1.9.2
- Git version:
- Operating system: Ubuntu 18.04
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

After placing a comment in a pull request, a notification is send to our Rocket.Chat. The notification tries to provide a hyperlink to the message with the syntax `<"hyperlink"|"name pull request">`. This is correct, however it is used as a header as well. Therefore, instead of making a hyperlink to the Gitea server, Rocket.Chat creates a hyperlink to show the contents of the comment.

I suggest to change the comment notification to:
```
[foo] New comment created by <"hyperlink to user"|"user">: <"hyperlink to comment"|"name pull request">
> "Comment contents"
```
This method will render all hyperlinks correctly.

## Screenshots

![Schermafdruk van 2019-08-25 14-11-30](https://user-images.githubusercontent.com/26286382/63649956-b3d07f00-c744-11e9-89bb-da3b37158562.png)

**Comment by lunny** [comment]
Which webhook type did you use?

**Comment by mathysie** [comment]
We are using the slack hook

**Comment by cornelk** [comment]
@mathysie please test again with v1.10.2 or later, this should be fixed with https://github.com/go-gitea/gitea/pull/9422

**Comment by lafriks** [comment]
Closing as fixed, reopen if there is still a problem
