### ISSUE TITLE
[Branch View] show "Included" Tag if it is merged manualy or Cloned from default branch

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#7976]
> If a repository use pull request, the merged label is unusable. But for others with no pull request, merged label is very usable. I will find time to review your PR.

so if the last commit is includet in default branch and folowing commit on default branch has a message wich `*[Mm]erge*<branch name>*`  then it is merged manualy and the merge flag sould also aperar

_Originally posted by @6543 in https://github.com/go-gitea/gitea/issues/7454#issuecomment-524643249_

**Comment by 6543** [comment]
## Things to find out:
how can i get the next commit of an commit in an go template ? + from that its text + who do template if <regex> ?
* [ ] if statement with regex in template
* [ ] get id of last commit of an branch
* [x] test if latest commit is in default branch  -> .CommitsAhead == 0
* [x] test if default branch has an commit after this mone -> .CommitsBehind > 0
* [ ] get id of folowing commit on default branch

**Comment by 6543** [comment]
# important question:
if a branch is 0 commits Ahead and at least 1 Behind default branch - indicates this a MERGE already?!?

**Comment by lunny** [comment]
Maybe only 0 commits Ahead if it was just merged.

**Comment by 6543** [comment]
> Maybe only 0 commits Ahead if it was just merged.

no because a merge generates a merge-comit ... wich is only on the default branch ...

**Comment by 6543** [comment]
so is it ok if ill do it that way?

**Comment by 6543** [comment]
https://github.com/go-gitea/gitea/pull/7979/commits/cc298fbac8c6b8808e08d0abb2652d8041eaa609 is doing it the short way ...

## Preview:
![](https://cloud.obermui.de/apps/gallery/preview.public/1456972?width=1600&height=1600&c=c7ce1aab93c94643af28760b2ebf6109&requesttoken=Xk0OmCixOpJuOZJfw4oVa6QQxur%2BuxfcPoKyUbd2RTc%3D%3AKWY412TJAvMvCsEw6LIsP%2BZCiNqvyEGlEe7qev0cJFI%3D&token=bG6GeSa6kqCQ2f3)
![](https://cloud.obermui.de/apps/gallery/preview.public/1456971?width=1600&height=1600&c=16da7eaff86c20f137c1e330168522f7&requesttoken=Xk0OmCixOpJuOZJfw4oVa6QQxur%2BuxfcPoKyUbd2RTc%3D%3AKWY412TJAvMvCsEw6LIsP%2BZCiNqvyEGlEe7qev0cJFI%3D&token=bG6GeSa6kqCQ2f3)

**Comment by 6543** [comment]
> Maybe only 0 commits Ahead if it was just merged.

if there is no commit between the branch to merge and the branch who is merged - without option --no-ff there is no merge commit ... you are right

**Comment by 6543** [comment]
smal notes I'll work with:

 * [ ] add new lable "Included" color:jelow
 * [ ] string wich tells: "this branch was manualy merged or is in some way already included in the default branch"
 * [ ] some code ...

**Comment by 6543** [comment]
-> https://github.com/go-gitea/gitea/pull/8449
