### ISSUE TITLE
Hold on some Repositories to top in Repositories List in Explore

### ISSUE THREAD

**Issue by FalconWu2017** [go-gitea/gitea#7981]
Some of Repositories are more important than others for me and the existing sorting are not very convenient to find them.

**Comment by guillep2k** [comment]
Starred repositories could be listed first.

@FalconWu2017 In the meantime, perhaps you could use topics to mark your repositories of interest?

**Comment by FalconWu2017** [comment]
@guillep2k  What does starred mean?I think it mean it is a good Repository but do not mean that I want to focu it any time. So I do not think this is a good idea.Maybe by watch is better.

**Comment by guillep2k** [comment]
![image](https://user-images.githubusercontent.com/18600385/63662221-0dac6580-c794-11e9-9eaf-19a6c027ba19.png)
A starred repository.

Its meaning is related to watch, but won't send notifications.
Watch can work for this purpose too.

**Comment by guillep2k** [comment]
In fact, there's already a page to list the starred repositories that might be of your interest:

![image](https://user-images.githubusercontent.com/18600385/63662442-cffc0c80-c794-11e9-8a2f-06c5e549b5fb.png)

(Top right button in your avatar)

**Comment by FalconWu2017** [comment]
Great. That's what I want. It would be better to put it on the right side of Explore.

**Comment by wxiaoguang** [comment]
More details in 

* https://github.com/go-gitea/gitea/issues/10375
