### ISSUE TITLE
Feature request: Auto close issue after user defined non-respons time span

### ISSUE THREAD

**Issue by buhtz** [go-gitea/gitea#7983]
When user open Issues the developers often ask back for more detailes.
They are waiting for response.

Lot of projects are closing the Issue in that case until the Issue opener respond. This is reasoned by the developers that they won't keep this waiting-for-response Issue in mind and come back in the future to close it if no response appears.

But this could be taken as unpolite by the Issue opener and other subscribers. It is not an elegant solution.

I would like to have a feature to close an Issue automaticly if no one (not only the opener!) responded after (e.g.) 30 days.

**Comment by lunny** [comment]
This could be done by some bots since git's API supports that.
