### ISSUE TITLE
Unable to push to an unprotected branch

### ISSUE THREAD

**Issue by Dewnisan** [go-gitea/gitea#7984]
- Gitea version (or commit ref): 1.9.2
- Git version:  2.23.0
- Operating system: Windows 2012 R2
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description

Pushing to an unprotected 'master' fails with the following error:
```
remote: Gitea: Internal error        
remote: retrieve protected branches information failed: invalid character '<' looking for beginning of value        
```

Pushing to other unprotected branches also fails with the same message.
This behavior does not occur on Gitea v1.8.3

## Screenshots

![image](https://user-images.githubusercontent.com/12575863/63680357-1fc1ee80-c7fc-11e9-9cfb-4296d88de7b7.png)

**Comment by lafriks** [comment]
Could this be duplicate of #7946 ?
