### ISSUE TITLE
Tag with "/" in name blocks pushing of tag with similar name

### ISSUE THREAD

**Issue by j123b567** [go-gitea/gitea#7985]
- Gitea version (or commit ref): 1.9.2
- Git version: 2.11.0
- Operating system: Debian 9.9
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes https://try.gitea.io/tagtest/tagtest1
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
If the repository has tag e.g. `a/v1` and also tag `v1`, then the later one cause problems with gitea. For git itself, it is completely valid scenerio.

Gitea receives the tag but reports

```
remote: Gitea: Internal Server Error
remote: Failed to Update: tagtest/tagtest1 Branch: v1 Error: PushUpdateAddTag: GetTag: object does not exist [id: v1, rel_path: ]
```
Tag is later not shown in releases but can be directly accessed by typing correct URL
for tag `a/v1` https://try.gitea.io/tagtest/tagtest1/src/tag/a/v1
for tag `v1` https://try.gitea.io/tagtest/tagtest1/src/tag/v1

## Steps to reproduce
``` sh
mkdir test
cd test
git init
git commit -m a
git tag a/v1
git tag v1
git remote add origin https://try.gitea.io/tagtest/tagtest2.git
git push -u origin master
git push --tags
```

This cause an error and tag `v1` is not visible in the UI but it should be.

**Comment by j123b567** [comment]
Possibly related to https://github.com/go-gitea/gitea/issues/7945

**Comment by j123b567** [comment]
After investigation, it is duplicate, so closing it.

**Comment by j123b567** [comment]
I must reopen the issue, because it was not duplicate. PR #7990 is wrong solution and issue #7945 is closed.

**Comment by richmahn** [comment]
Good catch. Yeah, the other issue was dealing with a branch with a similar name. Glad @guillep2k made a good fix for this.
