### ISSUE TITLE
[Branch View] [README] Screenshot Update

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#7986]
Update README Screenshot for Branch View after https://github.com/go-gitea/gitea/issues/7454

**Comment by 6543** [comment]
I think this is only locked by https://github.com/go-gitea/gitea/issues/7976

**Comment by 6543** [comment]
@lunny now we can update the Screenshot's lot of things happend sinse v1.10.0-RC1 ;)

**Comment by lunny** [comment]
So, I think maybe @go-gitea/maintainers and users could paste their favorite SCREENSHOTS here. Then we can chose some of them and update the README.

**Comment by zeripath** [comment]
One of my personal favourites is actually the 500 page with stack trace from the panic handler in Dev mode... :stuck_out_tongue: 

Making that taught me about how the go VM thinks about the stack. (Even though it's mostly a copy of the panic handler in macaron.)

**Comment by 6543** [comment]
![Bildschirmfoto zu 2019-10-16 11-24-47](https://user-images.githubusercontent.com/24977596/66912286-974d1680-f012-11e9-93f3-ca4abfa6a4c1.png)
![Bildschirmfoto zu 2019-10-16 11-27-30](https://user-images.githubusercontent.com/24977596/66912293-9ae09d80-f012-11e9-8e0d-54fb6b92126c.png)
![Bildschirmfoto zu 2019-10-16 11-29-41](https://user-images.githubusercontent.com/24977596/66912303-9fa55180-f012-11e9-8665-fa0d9b966ad4.png)
![Bildschirmfoto zu 2019-10-16 11-32-24](https://user-images.githubusercontent.com/24977596/66912306-a16f1500-f012-11e9-9ee8-2790c21839ee.png)
![Bildschirmfoto zu 2019-10-16 11-47-13](https://user-images.githubusercontent.com/24977596/66912312-a338d880-f012-11e9-87b2-968bad528d74.png)
![Bildschirmfoto zu 2019-10-16 11-48-33](https://user-images.githubusercontent.com/24977596/66912319-a46a0580-f012-11e9-9caf-0a84a70094a1.png)
![Bildschirmfoto zu 2019-10-16 11-49-01](https://user-images.githubusercontent.com/24977596/66912324-a633c900-f012-11e9-8ae6-b435bcbf3622.png)
![Bildschirmfoto zu 2019-10-16 11-57-12](https://user-images.githubusercontent.com/24977596/66912326-a7fd8c80-f012-11e9-8f98-52d4fcddbde5.png)

**Comment by 6543** [comment]
-> especialy the migrating status, migration github options, the heatmap, file edit and branch page are nice to look at

**Comment by kolaente** [comment]
@6543 Looks great! Do you think you could re-do them with the english UI? That way we can use them everywhere.

Offtopic: We should also put more screenshots of Gitea on the homepage...

**Comment by 6543** [comment]
Wait a day and I'll remake them

**Comment by lunny** [comment]
Dark mode screenshot, come from https://gitea.com/xorm/builder/pulls

![image](https://user-images.githubusercontent.com/81045/67064823-8d581e80-f19e-11e9-8983-1f6737be18c7.png)

**Comment by 6543** [comment]
# can someone creat a GIF of this ?:

![Bildschirmfoto zu 2019-10-18 21-54-22](https://user-images.githubusercontent.com/24977596/67124052-fe74f180-f1f1-11e9-8291-6942c0898ced.png)

**Comment by 6543** [comment]
![Bildschirmfoto zu 2019-10-18 21-53-34](https://user-images.githubusercontent.com/24977596/67124067-06cd2c80-f1f2-11e9-8641-e7cc782f6701.png)
![Bildschirmfoto zu 2019-10-18 21-47-12](https://user-images.githubusercontent.com/24977596/67124069-09c81d00-f1f2-11e9-9f13-781bd498df81.png)
![Bildschirmfoto zu 2019-10-18 21-45-33](https://user-images.githubusercontent.com/24977596/67124079-0cc30d80-f1f2-11e9-8bea-0e19885ddea2.png)
![Bildschirmfoto zu 2019-10-18 21-44-55](https://user-images.githubusercontent.com/24977596/67124088-10569480-f1f2-11e9-8321-cd9c180dcba2.png)
![Bildschirmfoto zu 2019-10-18 21-43-54](https://user-images.githubusercontent.com/24977596/67124092-13518500-f1f2-11e9-9ba7-62b4599df659.png)
![Bildschirmfoto zu 2019-10-18 21-42-54](https://user-images.githubusercontent.com/24977596/67124098-16e50c00-f1f2-11e9-80c7-dc5d7fc1c3f3.png)

**Comment by mrsdizzie** [comment]
> Code review, come from https://gitea.com/gitea/blog/pulls/109/files
> 
> ![image](https://user-images.githubusercontent.com/81045/67064941-05264900-f19f-11e9-9a2c-ba0a681fd1f2.png)

This one shows a bug with the edit/delete icons so probably not the best to use 😬

**Comment by 6543** [comment]
-> can someone creat a GIF of this ?
https://github.com/go-gitea/gitea/issues/7986#issuecomment-543912956

**Comment by guillep2k** [comment]
@6543 https://github.com/go-gitea/gitea/pull/6200#issue-256721646
It's low-res and in Chinese, but I think it's a cool picture.

**Comment by 6543** [comment]
no new screnshots ... so it's ready?

**Comment by 6543** [comment]
> > Code review, come from https://gitea.com/gitea/blog/pulls/109/files
> > ![image](https://user-images.githubusercontent.com/81045/67064941-05264900-f19f-11e9-9a2c-ba0a681fd1f2.png)
> 
> This one shows a bug with the edit/delete icons so probably not the best to use

I make one from avter someone wrote under a comment of mine
https://gitea.com/test-organisation/TestRepo/pulls/4/files#issuecomment-57669

**Comment by 6543** [comment]
![ezgif-2-7c98b9065172](https://user-images.githubusercontent.com/24977596/68078135-80f3d880-fdd0-11e9-98dc-41aeebe008e5.gif)

**Comment by 6543** [comment]
![Bildschirmfoto zu 2019-11-03 01-03-30](https://user-images.githubusercontent.com/24977596/68078431-ccf54c00-fdd5-11e9-903a-dbd62a7c08e0.png)

**Comment by 6543** [comment]
@lunny should i send a PR wich the new images @go-gitea/maintainers are thiese screenshots OK?

**Comment by lunny** [comment]
@6543 I'm OK.

**Comment by 6543** [comment]
@lunny where should i upload them?
-> use still https://image.ibb.co/
-> screenshot repo at gitea.com
-> some where else?

**Comment by lunny** [comment]
@6543 an image sites with global CDN is better than gitea.com. I think it's OK with https://image.ibb.co/ .

**Comment by 6543** [comment]
[gitea_screenshots.zip](https://github.com/go-gitea/gitea/files/3801278/gitea_screenshots.zip)

**Comment by 6543** [comment]
@techknowlogick if you like you can give them better names ;)

**Comment by 6543** [comment]
ready for review: #8813
