### ISSUE TITLE
go-source comment in code.gitea.io is wrong after transition to gitea.com

### ISSUE THREAD

**Issue by segevfiner** [go-gitea/gitea#7987]
For example, for `code.gitea.io/sdk`:
```html
<meta name="go-source" content="code.gitea.io/sdk https://gitea.com/gitea/go-sdk https://gitea.com/gitea/go-sdk/tree/master{/dir} https://gitea.com/gitea/go-sdk/blob/master{/dir}/{file}#L{line}">
```

Which is the URL pattern for GitHub. I think gitea itself is till on GitHub so both patterns are needed depending on where the repo is.

**Comment by lunny** [comment]
https://gitea.com/gitea/redirects/pulls/54 will fix this issue.
