### ISSUE TITLE
AppWorkDir is really AppWorkPath

### ISSUE THREAD

**Issue by akorn** [go-gitea/gitea#7988]
- Gitea version (or commit ref): v1.9

## Description

Related to #3549.

The docs at https://docs.gitea.io/en-us/install-from-source/ talk about AppWorkDir (with an unclear explanation of what it is/does); but the code nowhere actually references AppWorkDir, only AppWorkPath.

On the one hand, the name of the variable should be fixed either in the code or (probably) in the docs; on the other hand, the documentation should be improved to allow the administrator to get an understanding of what AppWorkPath is used for so they can set it meaningfully. This is #3549 territory though.

**Comment by akorn** [comment]
I suppose I'll just have to keep bumping this? Yay for conserving resources.

**Comment by zeripath** [comment]
Thanks for (re-)reporting. AFAICS this was fixed in #8567.
