### ISSUE TITLE
Is there any way I can add a gitignore at options/gitignore?

### ISSUE THREAD

**Issue by 1902sysad** [go-gitea/gitea#7998]
Hello Gitea Team,

the gitea styles and views can be override using /var/lib/gitea/custom but is there any way that I can also override or add on the options directory of the gitea especially the options/gitignore path here https://github.com/go-gitea/gitea/tree/master/options/gitignore without building from source?

Thank you :)

**Comment by lafriks** [comment]
Yes, just create file with same name in `custom/options/gitignore/` directory

**Comment by lafriks** [comment]
Please use https://discourse.gitea.io/ for such questions
