### ISSUE TITLE
Implement git-lfs

### ISSUE THREAD

**Issue by Schroedingers-Cat** [go-gitea/gitea#80]
Implementing git-lfs into gogs/gitea would be awesome for devs dealing with lots of binary files: https://git-lfs.github.com/

Ideally, it should be possible to 
* pull&push lfs objects via https and ssh
* configure the directory used to store lfs objects on the server
* automatically remove unused lfs objects if a repository gets deleted on the server

**Comment by vtolstov** [comment]
this can be closed...

**Comment by tboerger** [comment]
Solved
