### ISSUE TITLE
Unused attached images still show up on list of uploaded images for comment

### ISSUE THREAD

**Issue by bkraul** [go-gitea/gitea#8001]
- Gitea version (or commit ref): ca6fb004a
- Git version: 2.22.0
- Operating system: Ubuntu 18.04 (docker host)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL): https://try.gitea.io/Arrow/Project2/issues/1
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
When attaching images to a comment, the images are uploaded immediately if using copy/pasted. However, let's say I pasted an image I did not want to use, so I copy paste another one and end up using the latter one on the comment, I'd only want to see the one I used. However, right now, both images uploaded  are shown in the uploads bar for the comment, with no option of being able to delete unwanted attachments.

## Screenshots
![image](https://user-images.githubusercontent.com/14616851/63802472-53724680-c8d8-11e9-994a-eb7347be8511.png)

**Comment by lunny** [comment]
We need a delete action to the attachments.

**Comment by guillep2k** [comment]
This could be closed, as there's now implemented the possibility of deleting attachments.
