### ISSUE TITLE
Oauth2 provider: user end point not documented. User API url & scope keys?

### ISSUE THREAD

**Issue by poVoq** [go-gitea/gitea#8004]
- Gitea version (or commit ref): 1.9.2
- Git version: ?
- Operating system: Docker
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant

## Description
Oauth2 provider: user end point not documented. User API url & scope keys?

I would like to enable login via Gitea Oauth2 provider in my Kanboard instance with this Kanboard plugin:
https://github.com/kanboard/plugin-oauth2
It authorizes fine, but since I can not find any documentation on what to fill for User API URL and the individual scope keys it fails to create an user.

Might be related to this:
https://github.com/go-gitea/gitea/pull/5123

Thanks for looking into this!

**Comment by lunny** [comment]
Here is my example via Golang https://gitea.com/lunny/testGiteaOauth2

**Comment by poVoq** [comment]
Trying with is now from the link above:
```
		Name      string `json:"full_name"`
		Email     string `json:"email"`
		NickName  string `json:"login"`
		ID        int    `json:"id"`
		AvatarURL string `json:"avatar_url"`
```
