### ISSUE TITLE
link to create PR after push is missing after update from 1.8 to 1.9 on existing repos

### ISSUE THREAD

**Issue by morph027** [go-gitea/gitea#8013]
- Gitea version (or commit ref): 1.9.2
- Git version: 2.17.1
- Operating system: Ubuntu Bionic 18.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

This is the server side log when pushing a branch:

```
Aug 28 09:18:48 gitea gitea[12311]: 2019/08/28 09:18:48 modules/ssh/ssh.go:181:func1() [E] SearchPublicKeyByContent: public key does not exist [id: 0]
Aug 28 09:18:48 gitea gitea[12311]: [Macaron] 2019-08-28 09:18:48: Started GET /api/internal/serv/command/23/repo/test-testproject?mode=2&verb=git-receive-pack for 127.0.0.1
Aug 28 09:18:48 gitea gitea[12311]: [Macaron] 2019-08-28 09:18:48: Completed GET /api/internal/serv/command/23/repo/test-testproject?mode=2&verb=git-receive-pack 200 OK in 46.200043ms
Aug 28 09:18:48 gitea gitea[12311]: [Macaron] 2019-08-28 09:18:48: Started GET /api/internal/hook/pre-receive/repo/test-testproject?old=0000000000000000000000000000000000000000&new=e5d620284e950f7ac1fe361ab6a92ac01dd98d02&ref=refs%2Fheads%2Ffoo&userID=21&gitObjectDirectory=%2Fsrv%2Fgitea%2Frepositories%2Frepo%2Ftest-testproject.git%2F.%2Fobjects%2Fincoming-jai1uS&gitAlternativeObjectDirectories=%2Fsrv%2Fgitea%2Frepositories%2Frepo%2Ftest-testproject.git%2F.%2Fobjects&gitQuarantinePath=%2Fsrv%2Fgitea%2Frepositories%2Frepo%2Ftest-testproject.git%2F.%2Fobjects%2Fincoming-jai1uS&prID=0 for 127.0.0.1
Aug 28 09:18:48 gitea gitea[12311]: [Macaron] 2019-08-28 09:18:48: Completed GET /api/internal/hook/pre-receive/repo/test-testproject?old=0000000000000000000000000000000000000000&new=e5d620284e950f7ac1fe361ab6a92ac01dd98d02&ref=refs%2Fheads%2Ffoo&userID=21&gitObjectDirectory=%2Fsrv%2Fgitea%2Frepositories%2Frepo%2Ftest-testproject.git%2F.%2Fobjects%2Fincoming-jai1uS&gitAlternativeObjectDirectories=%2Fsrv%2Fgitea%2Frepositories%2Frepo%2Ftest-testproject.git%2F.%2Fobjects&gitQuarantinePath=%2Fsrv%2Fgitea%2Frepositories%2Frepo%2Ftest-testproject.git%2F.%2Fobjects%2Fincoming-jai1uS&prID=0 200 OK in 15.310619ms
Aug 28 09:18:48 gitea gitea[12311]: [Macaron] 2019-08-28 09:18:48: Started GET /api/internal/hook/post-receive/repo/test-testproject?old=0000000000000000000000000000000000000000&new=e5d620284e950f7ac1fe361ab6a92ac01dd98d02&ref=refs%2Fheads%2Ffoo&userID=21&username=repo for 127.0.0.1
Aug 28 09:18:48 gitea gitea[12311]: [Macaron] 2019-08-28 09:18:48: Completed GET /api/internal/hook/post-receive/repo/test-testproject?old=0000000000000000000000000000000000000000&new=e5d620284e950f7ac1fe361ab6a92ac01dd98d02&ref=refs%2Fheads%2Ffoo&userID=21&username=repo 200 OK in 166.081004ms
Aug 28 09:18:48 gitea gitea[12311]: [Macaron] 2019-08-28 09:18:48: Started POST /api/internal/ssh/23/update/60351 for 127.0.0.1
Aug 28 09:18:48 gitea gitea[12311]: [Macaron] 2019-08-28 09:18:48: Completed POST /api/internal/ssh/23/update/60351 200 OK in 21.996506ms
```

My local shell just gives:

```
git push --set-upstream origin foo
Total 0 (delta 0), reused 0 (delta 0)
To ssh://git.example.com:2222/repo/test-testproject.git
 * [new branch]      foo -> foo
Branch 'foo' set up to track remote branch 'foo' from 'origin'.
```

## Description

Today i've managed to update Gitea from 1.8.2 to 1.9.2 and after pushing a new branch, i'm missing the remote message to create a new PR introduced in #4716

**Comment by morph027** [comment]
Created a new org repo, forked into my user and pushed a branch and the beloved magic link is there...will check the repo hook settings...

**Comment by morph027** [comment]
When deleting a fork of a non-working repo and creating a new fork, the link also appears after pushing a new branch.

**Comment by lafriks** [comment]
From admin settings run `Resynchronize pre-receive, update and post-receive hooks of all repositories.` task:
![image](https://user-images.githubusercontent.com/165205/63863232-8854cb00-c9b6-11e9-899a-40bd1bf3b916.png)

**Comment by morph027** [comment]
Nothing changed. Looking at the filesystem, all projects got the same hooks (the initial bash script which loops over all hooks in .d directory and the gitea hook call in .d directory).

Not sure where the hook gets lost. Will try to enable more debug output and see, if i can find something related.

**Comment by morph027** [comment]
might be coincidence, but the last commit to hook cmd was 23 days ago...: https://github.com/go-gitea/gitea/commit/def84840dbce6d725618e1aeab4ca1f665600087

**Comment by morph027** [comment]
Also weird, we still got repos which are working without re-fork (in another organisation).

**Comment by morph027** [comment]
comparing a fresh fork (`user1`, where it's working) against a non-working fork (`user2`):

```
gitea:/srv/gitea/repositories# diff -Naur user1/repo.git/hooks/post-receive.d/ user2/repo.git/hooks/post-receive.d/gitea 
gitea:/srv/gitea/repositories# diff -Naur user1/repo.git/hooks/post-receive.d/gitea user2/repo.git/hooks/post-receive.d/gitea 
```

No difference.

**Comment by guillep2k** [comment]
Perhaps some users are using VS2019? In my VS2019 I'm not getting the remote messages in the `Source Control - Git` log, but I do get them if I use git from bash.

**Comment by morph027** [comment]
Nayh, just using command line ;)

**Comment by lunny** [comment]
@guillep2k the push link is more efficient than VS2019 I think. You can just click that link and create a PR in seconds.

**Comment by zeripath** [comment]
@morph027 are you sure that the hooks are even running? If your SSH key isn't managed by Gitea i.e. you can log in to the server to a shell then the hooks won't run because the environment won't get set because gitea serv won't get run.

As part of 1.11 I might pop a PR on that enforces pushes to Gitea repos have to be done in such a way that the hooks will run properly.

**Comment by morph027** [comment]
The SSH key is managed through Gitea Webinterface.

**Comment by zeripath** [comment]
Yeah sorry just reading your logs - I can see that the hooks are running.

OK, so does your test repository have another branch or is that the first commit - because if it is the first commit and you have no other branches it will get set as the default branch after you push it.

**Comment by morph027** [comment]
This happens on all existing projects which did have the PR message before the update...

**Comment by zeripath** [comment]
OK let's look at the logic.

The create a PR logic is in the post-receive hook and is determined by `gitea hook post-receive` here:

https://github.com/go-gitea/gitea/blob/2f73fff053527b9ab66d74063868846ae8eec5c7/cmd/hook.go#L175-L181

I.e the result from the pushing of a branch is `res["create"] = true.`

That's determined by here:

https://github.com/go-gitea/gitea/blob/2f73fff053527b9ab66d74063868846ae8eec5c7/routers/private/hook.go#L173-L240

The important parts are:

https://github.com/go-gitea/gitea/blob/2f73fff053527b9ab66d74063868846ae8eec5c7/routers/private/hook.go#L173

I.e. you're pushing the creation of a branch not deleting it.

https://github.com/go-gitea/gitea/blob/2f73fff053527b9ab66d74063868846ae8eec5c7/routers/private/hook.go#L185

I.e. the user is allowed to create PRs

https://github.com/go-gitea/gitea/blob/2f73fff053527b9ab66d74063868846ae8eec5c7/routers/private/hook.go#L204

i.e. the branch being pushed to is not the default branch - this is the problem with your testcase. 

https://github.com/go-gitea/gitea/blob/2f73fff053527b9ab66d74063868846ae8eec5c7/routers/private/hook.go#L221

i.e. There is not already a PR for this branch

**Comment by zeripath** [comment]
In 1.8 the logic was determined by:

https://github.com/go-gitea/gitea/blob/11f6ed4f8349119c8f9a5d57c43a0312365883d1/cmd/hook.go#L210-L248

The important parts are:

https://github.com/go-gitea/gitea/blob/11f6ed4f8349119c8f9a5d57c43a0312365883d1/cmd/hook.go#L210

* This is the same.

https://github.com/go-gitea/gitea/blob/11f6ed4f8349119c8f9a5d57c43a0312365883d1/cmd/hook.go#L217

* This is the same

https://github.com/go-gitea/gitea/blob/11f6ed4f8349119c8f9a5d57c43a0312365883d1/cmd/hook.go#L226

* This is the same

https://github.com/go-gitea/gitea/blob/11f6ed4f8349119c8f9a5d57c43a0312365883d1/cmd/hook.go#L237

* This is the same.

**Comment by zeripath** [comment]
The only difference I can see between 1.8 and 1.9 is that your testcase will "work" in 1.8 because 1.8 will not set the default branch to be the first thing that is pushed.

**Comment by zeripath** [comment]
Are there definitely no errors in your logs? That's the only way there could be a difference.

**Comment by morph027** [comment]
Any logs in particular? Should i set loglevel to trace?

**Comment by zeripath** [comment]
If you look at the code I've put up above for 1.9, all the points that would cause no output `log.Error` except for the case that you are pushing to the defaultBranch of a non-fork which doesn't log.

If you are pushing a non-default branch that you should either get a create the branch or visit the branch message. Compare the code between 1.8 and 1.9 I can't see how there could be a difference.

**Comment by morph027** [comment]
Huh, already forgot about ;)

We've upgraded to 1.10.2 recently and the behaviour still exists.

**Comment by zeripath** [comment]
Maybe it's the determination of isPullRequest allowed? As I wrote above the hook change I don't think can be the cause

**Comment by morph027** [comment]
Now running 1.11.3, even with `PULL_REQUEST_PUSH_MESSAGE = true` there's no consistent behaviour. Some forks are working, some not.

**Comment by zeripath** [comment]
OK can you tell me anything about the cases where this doesn't work? I'm gonna put a guess out here:

* The cases where it doesn't work are all forks from an organisation.
* They're limited to a particular organisation or orgs - maybe even a particular team reference in that organisation

Another question are the original forked repos are using an external issue tracker?

**Comment by morph027** [comment]
Hi!

Yes, both is true, all of our repos are forks of an organisation upstream and the upstreams are limited. Creating a PR through the webinterface works without problems.

At least in my case, i'm in the owners groups of the orgs.

And there are repos within the same organisation, where everything works.

None of the repos is using an external issue tracker.
