### ISSUE TITLE
Gitea falling into an endless initialization loop without errors on startup if the folder has no writing permissions

### ISSUE THREAD

**Issue by DNAlchemist** [go-gitea/gitea#8014]
- Gitea version (or commit ref): 1.10.0+dev-219-gab0f378d7
- Git version: 2.22.0
- Operating system: Alpine Linux v3.10
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:
2019/08/28 09:53:16 ...dules/setting/git.go:87:newGit() [I] Git Version: 2.22.0, Wire Protocol Version 2 Enabled
2019/08/28 09:53:16 routers/init.go:72:GlobalInit() [T] AppPath: /app/gitea/gitea
2019/08/28 09:53:16 routers/init.go:73:GlobalInit() [T] AppWorkPath: /app/gitea
2019/08/28 09:53:16 routers/init.go:74:GlobalInit() [T] Custom path: /data/custom
2019/08/28 09:53:16 routers/init.go:75:GlobalInit() [T] Log path: /data/gitea/log
2019/08/28 09:53:17 ...dules/setting/git.go:87:newGit() [I] Git Version: 2.22.0, Wire Protocol Version 2 Enabled
2019/08/28 09:53:17 routers/init.go:72:GlobalInit() [T] AppPath: /app/gitea/gitea
2019/08/28 09:53:17 routers/init.go:73:GlobalInit() [T] AppWorkPath: /app/gitea
2019/08/28 09:53:17 routers/init.go:74:GlobalInit() [T] Custom path: /data/custom
2019/08/28 09:53:17 routers/init.go:75:GlobalInit() [T] Log path: /data/gitea/log
2019/08/28 09:53:17 ...dules/setting/log.go:226:newLogService() [I] Gitea v1.10.0+dev-219-gab0f378d7 built with GNU Make 4.2.1, go1.12.9 : bindata, sqlite, sqlite_unlock_notify
2019/08/28 09:53:18 ...dules/setting/git.go:87:newGit() [I] Git Version: 2.22.0, Wire Protocol Version 2 Enabled
2019/08/28 09:53:18 routers/init.go:72:GlobalInit() [T] AppPath: /app/gitea/gitea
2019/08/28 09:53:18 routers/init.go:73:GlobalInit() [T] AppWorkPath: /app/gitea
2019/08/28 09:53:18 routers/init.go:74:GlobalInit() [T] Custom path: /data/custom
2019/08/28 09:53:18 routers/init.go:75:GlobalInit() [T] Log path: /data/gitea/log
2019/08/28 09:53:18 ...dules/setting/log.go:226:newLogService() [I] Gitea v1.10.0+dev-219-gab0f378d7 built with GNU Make 4.2.1, go1.12.9 : bindata, sqlite, sqlite_unlock_notify
2019/08/28 09:53:19 ...dules/setting/git.go:87:newGit() [I] Git Version: 2.22.0, Wire Protocol Version 2 Enabled
2019/08/28 09:53:19 routers/init.go:72:GlobalInit() [T] AppPath: /app/gitea/gitea
2019/08/28 09:53:19 routers/init.go:73:GlobalInit() [T] AppWorkPath: /app/gitea
2019/08/28 09:53:19 routers/init.go:74:GlobalInit() [T] Custom path: /data/custom
2019/08/28 09:53:19 routers/init.go:75:GlobalInit() [T] Log path: /data/gitea/log
2019/08/28 09:53:20 ...dules/setting/git.go:87:newGit() [I] Git Version: 2.22.0, Wire Protocol Version 2 Enabled
2019/08/28 09:53:20 routers/init.go:72:GlobalInit() [T] AppPath: /app/gitea/gitea
2019/08/28 09:53:20 routers/init.go:73:GlobalInit() [T] AppWorkPath: /app/gitea
2019/08/28 09:53:20 routers/init.go:74:GlobalInit() [T] Custom path: /data/custom
2019/08/28 09:53:20 routers/init.go:75:GlobalInit() [T] Log path: /data/gitea/log
2019/08/28 09:53:20 ...dules/setting/log.go:226:newLogService() [I] Gitea v1.10.0+dev-219-gab0f378d7 built with GNU Make 4.2.1, go1.12.9 : bindata, sqlite, sqlite_unlock_notify
2019/08/28 09:53:21 ...dules/setting/git.go:87:newGit() [I] Git Version: 2.22.0, Wire Protocol Version 2 Enabled
2019/08/28 09:53:21 routers/init.go:72:GlobalInit() [T] AppPath: /app/gitea/gitea
2019/08/28 09:53:21 routers/init.go:73:GlobalInit() [T] AppWorkPath: /app/gitea
2019/08/28 09:53:21 routers/init.go:74:GlobalInit() [T] Custom path: /data/custom
2019/08/28 09:53:21 routers/init.go:75:GlobalInit() [T] Log path: /data/gitea/log
2019/08/28 09:53:22 ...dules/setting/git.go:87:newGit() [I] Git Version: 2.22.0, Wire Protocol Version 2 Enabled
2019/08/28 09:53:22 routers/init.go:72:GlobalInit() [T] AppPath: /app/gitea/gitea
2019/08/28 09:53:22 routers/init.go:73:GlobalInit() [T] AppWorkPath: /app/gitea
2019/08/28 09:53:22 routers/init.go:74:GlobalInit() [T] Custom path: /data/custom
2019/08/28 09:53:22 routers/init.go:75:GlobalInit() [T] Log path: /data/gitea/log
2019/08/28 09:53:23 ...dules/setting/git.go:87:newGit() [I] Git Version: 2.22.0, Wire Protocol Version 2 Enabled
2019/08/28 09:53:23 routers/init.go:72:GlobalInit() [T] AppPath: /app/gitea/gitea
2019/08/28 09:53:23 routers/init.go:73:GlobalInit() [T] AppWorkPath: /app/gitea
2019/08/28 09:53:23 routers/init.go:74:GlobalInit() [T] Custom path: /data/custom
2019/08/28 09:53:23 routers/init.go:75:GlobalInit() [T] Log path: /data/gitea/log
2019/08/28 09:53:24 ...dules/setting/git.go:87:newGit() [I] Git Version: 2.22.0, Wire Protocol Version 2 Enabled
2019/08/28 09:53:24 routers/init.go:72:GlobalInit() [T] AppPath: /app/gitea/gitea
2019/08/28 09:53:24 routers/init.go:73:GlobalInit() [T] AppWorkPath: /app/gitea
2019/08/28 09:53:24 routers/init.go:74:GlobalInit() [T] Custom path: /data/custom
2019/08/28 09:53:24 routers/init.go:75:GlobalInit() [T] Log path: /data/gitea/log
2019/08/28 09:53:24 ...dules/setting/log.go:226:newLogService() [I] Gitea v1.10.0+dev-219-gab0f378d7 built with GNU Make 4.2.1, go1.12.9 : bindata, sqlite, sqlite_unlock_notify
2019/08/28 09:53:25 ...dules/setting/git.go:87:newGit() [I] Git Version: 2.22.0, Wire Protocol Version 2 Enabled
2019/08/28 09:53:25 routers/init.go:72:GlobalInit() [T] AppPath: /app/gitea/gitea
2019/08/28 09:53:25 routers/init.go:73:GlobalInit() [T] AppWorkPath: /app/gitea
2019/08/28 09:53:25 routers/init.go:74:GlobalInit() [T] Custom path: /data/custom
2019/08/28 09:53:25 routers/init.go:75:GlobalInit() [T] Log path: /data/gitea/log
2019/08/28 09:53:25 ...dules/setting/log.go:226:newLogService() [I] Gitea v1.10.0+dev-219-gab0f378d7 built with GNU Make 4.2.1, go1.12.9 : bindata, sqlite, sqlite_unlock_notify
2019/08/28 09:53:26 ...dules/setting/git.go:87:newGit() [I] Git Version: 2.22.0, Wire Protocol Version 2 Enabled
2019/08/28 09:53:26 routers/init.go:72:GlobalInit() [T] AppPath: /app/gitea/gitea
2019/08/28 09:53:26 routers/init.go:73:GlobalInit() [T] AppWorkPath: /app/gitea
2019/08/28 09:53:26 routers/init.go:74:GlobalInit() [T] Custom path: /data/custom
2019/08/28 09:53:26 routers/init.go:75:GlobalInit() [T] Log path: /data/gitea/log
2019/08/28 09:53:26 ...dules/setting/log.go:226:newLogService() [I] Gitea v1.10.0+dev-219-gab0f378d7 built with GNU Make 4.2.1, go1.12.9 : bindata, sqlite, sqlite_unlock_notify
2019/08/28 09:53:27 ...dules/setting/git.go:87:newGit() [I] Git Version: 2.22.0, Wire Protocol Version 2 Enabled
2019/08/28 09:53:27 routers/init.go:72:GlobalInit() [T] AppPath: /app/gitea/gitea
2019/08/28 09:53:27 routers/init.go:73:GlobalInit() [T] AppWorkPath: /app/gitea
2019/08/28 09:53:27 routers/init.go:74:GlobalInit() [T] Custom path: /data/custom
2019/08/28 09:53:27 routers/init.go:75:GlobalInit() [T] Log path: /data/gitea/log
2019/08/28 09:53:27 ...dules/setting/log.go:226:newLogService() [I] Gitea v1.10.0+dev-219-gab0f378d7 built with GNU Make 4.2.1, go1.12.9 : bindata, sqlite, sqlite_unlock_notify
2019/08/28 09:53:28 ...dules/setting/git.go:87:newGit() [I] Git Version: 2.22.0, Wire Protocol Version 2 Enabled
2019/08/28 09:53:28 routers/init.go:72:GlobalInit() [T] AppPath: /app/gitea/gitea
2019/08/28 09:53:28 routers/init.go:73:GlobalInit() [T] AppWorkPath: /app/gitea
2019/08/28 09:53:28 routers/init.go:74:GlobalInit() [T] Custom path: /data/custom
2019/08/28 09:53:28 routers/init.go:75:GlobalInit() [T] Log path: /data/gitea/log
2019/08/28 09:53:28 ...dules/setting/log.go:226:newLogService() [I] Gitea v1.10.0+dev-219-gab0f378d7 built with GNU Make 4.2.1, go1.12.9 : bindata, sqlite, sqlite_unlock_notify
2019/08/28 09:53:29 ...dules/setting/git.go:87:newGit() [I] Git Version: 2.22.0, Wire Protocol Version 2 Enabled
2019/08/28 09:53:29 routers/init.go:72:GlobalInit() [T] AppPath: /app/gitea/gitea
2019/08/28 09:53:29 routers/init.go:73:GlobalInit() [T] AppWorkPath: /app/gitea
2019/08/28 09:53:29 routers/init.go:74:GlobalInit() [T] Custom path: /data/custom
2019/08/28 09:53:29 routers/init.go:75:GlobalInit() [T] Log path: /data/gitea/log
2019/08/28 09:53:30 ...dules/setting/git.go:87:newGit() [I] Git Version: 2.22.0, Wire Protocol Version 2 Enabled
2019/08/28 09:53:30 routers/init.go:72:GlobalInit() [T] AppPath: /app/gitea/gitea
2019/08/28 09:53:30 routers/init.go:73:GlobalInit() [T] AppWorkPath: /app/gitea
2019/08/28 09:53:30 routers/init.go:74:GlobalInit() [T] Custom path: /data/custom
2019/08/28 09:53:30 routers/init.go:75:GlobalInit() [T] Log path: /data/gitea/log
2019/08/28 09:53:31 ...dules/setting/git.go:87:newGit() [I] Git Version: 2.22.0, Wire Protocol Version 2 Enabled
2019/08/28 09:53:31 routers/init.go:72:GlobalInit() [T] AppPath: /app/gitea/gitea
2019/08/28 09:53:31 routers/init.go:73:GlobalInit() [T] AppWorkPath: /app/gitea
2019/08/28 09:53:31 routers/init.go:74:GlobalInit() [T] Custom path: /data/custom
2019/08/28 09:53:31 routers/init.go:75:GlobalInit() [T] Log path: /data/gitea/log
2019/08/28 09:53:32 ...dules/setting/git.go:87:newGit() [I] Git Version: 2.22.0, Wire Protocol Version 2 Enabled
2019/08/28 09:53:32 routers/init.go:72:GlobalInit() [T] AppPath: /app/gitea/gitea
2019/08/28 09:53:32 routers/init.go:73:GlobalInit() [T] AppWorkPath: /app/gitea
2019/08/28 09:53:32 routers/init.go:74:GlobalInit() [T] Custom path: /data/custom
2019/08/28 09:53:32 routers/init.go:75:GlobalInit() [T] Log path: /data/gitea/log
2019/08/28 09:53:32 ...dules/setting/log.go:226:newLogService() [I] Gitea v1.10.0+dev-219-gab0f378d7 built with GNU Make 4.2.1, go1.12.9 : bindata, sqlite, sqlite_unlock_notify
2019/08/28 09:53:33 ...dules/setting/git.go:87:newGit() [I] Git Version: 2.22.0, Wire Protocol Version 2 Enabled
2019/08/28 09:53:33 routers/init.go:72:GlobalInit() [T] AppPath: /app/gitea/gitea
2019/08/28 09:53:33 routers/init.go:73:GlobalInit() [T] AppWorkPath: /app/gitea
2019/08/28 09:53:33 routers/init.go:74:GlobalInit() [T] Custom path: /data/custom
2019/08/28 09:53:33 routers/init.go:75:GlobalInit() [T] Log path: /data/gitea/log
2019/08/28 09:53:33 ...dules/setting/log.go:226:newLogService() [I] Gitea v1.10.0+dev-219-gab0f378d7 built with GNU Make 4.2.1, go1.12.9 : bindata, sqlite, sqlite_unlock_notify
2019/08/28 09:53:34 ...dules/setting/git.go:87:newGit() [I] Git Version: 2.22.0, Wire Protocol Version 2 Enabled
2019/08/28 09:53:34 routers/init.go:72:GlobalInit() [T] AppPath: /app/gitea/gitea
2019/08/28 09:53:34 routers/init.go:73:GlobalInit() [T] AppWorkPath: /app/gitea
2019/08/28 09:53:34 routers/init.go:74:GlobalInit() [T] Custom path: /data/custom
2019/08/28 09:53:34 routers/init.go:75:GlobalInit() [T] Log path: /data/gitea/log
2019/08/28 09:53:34 ...dules/setting/log.go:226:newLogService() [I] Gitea v1.10.0+dev-219-gab0f378d7 built with GNU Make 4.2.1, go1.12.9 : bindata, sqlite, sqlite_unlock_notify
2019/08/28 09:53:35 ...dules/setting/git.go:87:newGit() [I] Git Version: 2.22.0, Wire Protocol Version 2 Enabled
2019/08/28 09:53:35 routers/init.go:72:GlobalInit() [T] AppPath: /app/gitea/gitea
2019/08/28 09:53:35 routers/init.go:73:GlobalInit() [T] AppWorkPath: /app/gitea
2019/08/28 09:53:35 routers/init.go:74:GlobalInit() [T] Custom path: /data/custom
2019/08/28 09:53:35 routers/init.go:75:GlobalInit() [T] Log path: /data/gitea/log
2019/08/28 09:53:36 ...dules/setting/git.go:87:newGit() [I] Git Version: 2.22.0, Wire Protocol Version 2 Enabled
2019/08/28 09:53:36 routers/init.go:72:GlobalInit() [T] AppPath: /app/gitea/gitea
2019/08/28 09:53:36 routers/init.go:73:GlobalInit() [T] AppWorkPath: /app/gitea
2019/08/28 09:53:36 routers/init.go:74:GlobalInit() [T] Custom path: /data/custom
2019/08/28 09:53:36 routers/init.go:75:GlobalInit() [T] Log path: /data/gitea/log
2019/08/28 09:53:36 ...dules/setting/log.go:226:newLogService() [I] Gitea v1.10.0+dev-219-gab0f378d7 built with GNU Make 4.2.1, go1.12.9 : bindata, sqlite, sqlite_unlock_notify
2019/08/28 09:53:37 ...dules/setting/git.go:87:newGit() [I] Git Version: 2.22.0, Wire Protocol Version 2 Enabled
2019/08/28 09:53:37 routers/init.go:72:GlobalInit() [T] AppPath: /app/gitea/gitea
2019/08/28 09:53:37 routers/init.go:73:GlobalInit() [T] AppWorkPath: /app/gitea
2019/08/28 09:53:37 routers/init.go:74:GlobalInit() [T] Custom path: /data/custom
2019/08/28 09:53:37 routers/init.go:75:GlobalInit() [T] Log path: /data/gitea/log
2019/08/28 09:53:37 ...dules/setting/log.go:226:newLogService() [I] Gitea v1.10.0+dev-219-gab0f378d7 built with GNU Make 4.2.1, go1.12.9 : bindata, sqlite, sqlite_unlock_notify
2019/08/28 09:53:38 ...dules/setting/git.go:87:newGit() [I] Git Version: 2.22.0, Wire Protocol Version 2 Enabled
2019/08/28 09:53:38 routers/init.go:72:GlobalInit() [T] AppPath: /app/gitea/gitea
2019/08/28 09:53:38 routers/init.go:73:GlobalInit() [T] AppWorkPath: /app/gitea
2019/08/28 09:53:38 routers/init.go:74:GlobalInit() [T] Custom path: /data/custom
2019/08/28 09:53:38 routers/init.go:75:GlobalInit() [T] Log path: /data/gitea/log
2019/08/28 09:53:38 ...dules/setting/log.go:226:newLogService() [I] Gitea v1.10.0+dev-219-gab0f378d7 built with GNU Make 4.2.1, go1.12.9 : bindata, sqlite, sqlite_unlock_notify
2019/08/28 09:53:39 ...dules/setting/git.go:87:newGit() [I] Git Version: 2.22.0, Wire Protocol Version 2 Enabled
2019/08/28 09:53:39 routers/init.go:72:GlobalInit() [T] AppPath: /app/gitea/gitea
2019/08/28 09:53:39 routers/init.go:73:GlobalInit() [T] AppWorkPath: /app/gitea
2019/08/28 09:53:39 routers/init.go:74:GlobalInit() [T] Custom path: /data/custom
2019/08/28 09:53:39 routers/init.go:75:GlobalInit() [T] Log path: /data/gitea/log
2019/08/28 09:53:39 ...dules/setting/log.go:226:newLogService() [I] Gitea v1.10.0+dev-219-gab0f378d7 built with GNU Make 4.2.1, go1.12.9 : bindata, sqlite, sqlite_unlock_notify
2019/08/28 09:53:40 ...dules/setting/git.go:87:newGit() [I] Git Version: 2.22.0, Wire Protocol Version 2 Enabled
2019/08/28 09:53:40 routers/init.go:72:GlobalInit() [T] AppPath: /app/gitea/gitea
2019/08/28 09:53:40 routers/init.go:73:GlobalInit() [T] AppWorkPath: /app/gitea
2019/08/28 09:53:40 routers/init.go:74:GlobalInit() [T] Custom path: /data/custom
2019/08/28 09:53:40 routers/init.go:75:GlobalInit() [T] Log path: /data/gitea/log
2019/08/28 09:53:41 ...dules/setting/git.go:87:newGit() [I] Git Version: 2.22.0, Wire Protocol Version 2 Enabled
2019/08/28 09:53:41 routers/init.go:72:GlobalInit() [T] AppPath: /app/gitea/gitea
2019/08/28 09:53:41 routers/init.go:73:GlobalInit() [T] AppWorkPath: /app/gitea
2019/08/28 09:53:41 routers/init.go:74:GlobalInit() [T] Custom path: /data/custom
2019/08/28 09:53:41 routers/init.go:75:GlobalInit() [T] Log path: /data/gitea/log
2019/08/28 09:53:42 ...dules/setting/git.go:87:newGit() [I] Git Version: 2.22.0, Wire Protocol Version 2 Enabled
2019/08/28 09:53:42 routers/init.go:72:GlobalInit() [T] AppPath: /app/gitea/gitea
2019/08/28 09:53:42 routers/init.go:73:GlobalInit() [T] AppWorkPath: /app/gitea
2019/08/28 09:53:42 routers/init.go:74:GlobalInit() [T] Custom path: /data/custom
2019/08/28 09:53:42 routers/init.go:75:GlobalInit() [T] Log path: /data/gitea/log
2019/08/28 09:53:42 ...dules/setting/log.go:226:newLogService() [I] Gitea v1.10.0+dev-219-gab0f378d7 built with GNU Make 4.2.1, go1.12.9 : bindata, sqlite, sqlite_unlock_notify
2019/08/28 09:53:43 ...dules/setting/git.go:87:newGit() [I] Git Version: 2.22.0, Wire Protocol Version 2 Enabled
2019/08/28 09:53:43 routers/init.go:72:GlobalInit() [T] AppPath: /app/gitea/gitea
2019/08/28 09:53:43 routers/init.go:73:GlobalInit() [T] AppWorkPath: /app/gitea
2019/08/28 09:53:43 routers/init.go:74:GlobalInit() [T] Custom path: /data/custom
2019/08/28 09:53:43 routers/init.go:75:GlobalInit() [T] Log path: /data/gitea/log

## Description
Gitea falling into an endless initialization loop without errors on startup if the folder has no writing permissions.
I checked with REPO_INDEXER_PATH.

**Comment by lunny** [comment]
Sometimes gitea exit with missing logs. @zeripath I also found that.

**Comment by zeripath** [comment]
Hmm... Maybe there's Fatal being thrown during log initialisation?

**Comment by zeripath** [comment]
OK I think I see the problem.

https://github.com/go-gitea/gitea/blob/0a96e59884ca5c4fedc8c3d166d97f35b245ad6e/modules/log/log.go#L177-L181

I think there needs to be a `Flush()` in there or better yet, `Close()` should flush.

**Comment by zeripath** [comment]
Ah, may be it's simpler than that. You have console log turned off and then when it tries to log the problem it can't because there's nowhere for it to log to?
