### ISSUE TITLE
On repository creation dialog, the meaning of "private" should be explained.

### ISSUE THREAD

**Issue by micw** [go-gitea/gitea#8015]
- Gitea version (or commit ref): 9f33aa6

## Description

When creating a new repository, there's the option "mark this repository private". It should be explained that "private" means that only organisation members can see it and that otherwise anyone can see it. Currently it's very missleading because "private" usually means "visible for me" and not "visible for me any my team". Devs who are not very familar with gitea internas disable the "private" options often when creating new repos because they want their team to have access.

**Comment by techknowlogick** [comment]
Closed per merged PR
