### ISSUE TITLE
Show prominent warning and howto in user and admin interfaces when user-initiated password reset is impossible

### ISSUE THREAD

**Issue by Poikilos** [go-gitea/gitea#8017]
- Gitea version (or commit ref):  1.9.2 (Go1.12.9)
- Database (use `[x]`): unknown (admin unavailable)
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist: N/A

## Description
User-initiated reset says it is disabled, when in reality, e-mail is probably not configured, according to comments at https://github.com/go-gitea/gitea/issues/2247 which is closed for unknown reasons which the closer did not describe.

Expected behavior:
- Provide warning message such as [proposed by jolheiser](https://github.com/go-gitea/gitea/issues/2247#issuecomment-513620841). Whereas "disabled" is misleading (according to replies at which indicate that the message only appears when e-mail is not configured and that there is **no setting for it**), "disabled because e-mail is not configured" (maybe that on that admin side, and something like "is not configured" on the user side) would be more clear, and would point to the solution.
- Where the warning is shown prominently, also explain how to correct the issue (at least on the admin side).

![image](https://user-images.githubusercontent.com/7557867/63882077-43716a00-c99f-11e9-9756-b06c658597a6.png)

**Comment by jolheiser** [comment]
Fixed by #15117, which shows a better error to admin as well as logging a warning when that page is shown (so an admin looking for something in logs can maybe still find it)
