### ISSUE TITLE
Feature request: Display merged commit on PRs

### ISSUE THREAD

**Issue by filipnavara** [go-gitea/gitea#8027]
## Description

Gitea already tracks commit IDs for merged PRs (`PullRequest.MergedCommitID`). However, this information is currently only accessible through API endpoint. It would be immensely useful if the conversation view of the PR displayed it as well and made the commit link clickable.

## Screenshots

GitHub version of this feature:

![image](https://user-images.githubusercontent.com/1764393/63916408-ab27c380-ca38-11e9-833a-3bb45ac08f55.png)

**Comment by filipnavara** [comment]
Alternatively, it could be display in the footer as part of the "The pull request has been merged." message.

**Comment by lunny** [comment]
This is already implemented.
