### ISSUE TITLE
API response for label returns empty 'url' field

### ISSUE THREAD

**Issue by bobemoe** [go-gitea/gitea#8028]
- Gitea version (or commit ref):  1.10.0+dev-230-g187ae109d
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant

## Description
When fetching or creating a label, the url field in the json response is blank: 

https://try.gitea.io/api/v1/repos/bobemoe/test/issues/1/labels
```json
[
  {
    "id": 4150,
    "name": "bug",
    "color": "ee0701",
    "description": "Something is not working",
    "url": ""
  }
]
```

Expected that it will return the API url for editing the label, same as it does for an issue: 

https://try.gitea.io/api/v1/repos/bobemoe/test/issues/1
```json
{
  "id": 5668,
  "url": "https://try.gitea.io/api/v1/repos/bobemoe/test/issues/1",
  "number": 1,
  "user": {
    "id": 16866,
    "login": "bobemoe",
...
```

**Comment by sd1998** [comment]
@lunny Can I work on this?

**Comment by techknowlogick** [comment]
@sd1998 sure
