### ISSUE TITLE
not support "HEAD" http request

### ISSUE THREAD

**Issue by gonboy** [go-gitea/gitea#8030]
sometime, I want use gitea as file web server.
so need to download it.  if not support HEAD to get the file size. 
so can't calc the left time

**Comment by sapk** [comment]
Can you provide a example url on try.gite+9 ?

**Comment by bwenrich** [comment]
If I understand correctly, the intention is to determine the size of the object that would be sent, so a client application could generate a progress-bar of the download progress.

My quick testing shows that Gitea didn't provide the "Content-Length" attribute in the HTTP response header, so the client does not know the response size in advance.

```
# Example from an arbitrary file on try.gitea.io
$ curl --head https://try.gitea.io/gitea/gitea/src/branch/master/README.md
HTTP/2 200
content-type: text/html; charset=UTF-8
date: Sun, 01 Sep 2019 03:01:40 GMT
set-cookie: lang=en-US; Path=/; Max-Age=2147483647
set-cookie: i_like_gitea=<<removed>>; Path=/; HttpOnly
set-cookie: _csrf=<<removed>>; Path=/; Expires=Mon, 02 Sep 2019 03:01:40 GMT; HttpOnly
x-frame-options: SAMEORIGIN
```
```
# Example from a generic Apache server
$ curl --head https://domain.example.com/README.md
HTTP/1.1 200 OK
Date: Sun, 01 Sep 2019 03:04:17 GMT
Last-Modified: Sun, 18 Aug 2019 02:25:17 GMT
Accept-Ranges: bytes
Content-Length: 5934
content-type: text/html; charset=UTF-8
```

The Content-Length attribute is not mandatory for HTTP HEAD or HTTP GET, but could be useful in some cases.

**Comment by 6543** [comment]
did https://github.com/go-gitea/gitea/pull/14541 close this issue?
