### ISSUE TITLE
API Delete Repository Release marked as PreRelease does not delete attachments

### ISSUE THREAD

**Issue by falkzilm** [go-gitea/gitea#8036]
- Gitea version (or commit ref): 1.9.2
- Git version: 2.22.0
- Operating system: Docker Image
- Database (use `[x]`):
  - [x ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

Deleting of attachments via API Calls does not work neither are they deleted while deleting the pre release itself.

Delete Attachment API Call returns 404 not found, with correct parameters.

Request: 
`curl -X DELETE "https://try.gitea.io/api/v1/repos/testUserFalk/testAttachmentBug/releases/3279286/assets/351" -H  "accept: application/json" -H  "authorization: Basic dGVzdFVzZXJGYWxrOnRlc3QxMjM0NTY3OA==" -H  "Authorization: token c3fdd9c007274b1f73ff13e0bcc869cb8a85b650"`

Response:
`{
  "documentation_url": "https://try.gitea.io/api/swagger",
  "errors": null,
  "message": "Not Found"
}`

Deleting release seems to work, but somehow information is left over

Request:
`curl -X DELETE "https://try.gitea.io/api/v1/repos/testUserFalk/testAttachmentBug/releases/3279286" -H  "accept: application/json" -H  "authorization: Basic dGVzdFVzZXJGYWxrOnRlc3QxMjM0NTY3OA==" -H  "Authorization: token c3fdd9c007274b1f73ff13e0bcc869cb8a85b650"`

Response with Status Code 204

But if you look on release page you still see some release information. 
Release tag is also still present on project.

If you create a new release, old data are connected with the new release.

Expected Behaviour would be like in the web page itself, there you can delete a pre release correctly. 

Deleting attachments seems not be supported.

**Comment by 6543** [comment]
I'll take a look at it

**Comment by 6543** [comment]
@falkzilm this issue is about two different topics/issues:
1. Delete Tag on Release deletion too via API
2. error with release attatchment deletion

to 1.:
 * It work's as expected
 * I would leave it as it is (you can handle things more specific with API)
    - just delete release and then delete tag via git (`git push --delete origin tagname`) if you like to have same result than UI does

to 2: update income ...

**Comment by 6543** [comment]
... 2. works as expected on 1.11.0-dev (ed67bbe4442cc26fc64102c04d6fbea348f52e7c)

@falkzilm do you still have this problem on your side with current master branch version?

**Comment by 6543** [comment]
@lunny can you remove `confirmed` and add **lable** `status/needs-feedback ` plz?

**Comment by 6543** [comment]
@falkzilm can you close this ... if you are satisfied

**Comment by falkzilm** [comment]
Sorry reacting lately on this topic.
I cannot see any issues with my current running version 1.10.3 - so this can be closed indeed.
