### ISSUE TITLE
Give the icon and logo some love ❤️

### ISSUE THREAD

**Issue by dunderpate** [go-gitea/gitea#8038]
Hi everyone,

I am a big fan of the project, and thought I'd put some cycles into seeing what I could do with the icon and logo. Feel free to close this issue if it's not something you're interested in, but I thought it might make things look a big cleaner/nicer/professional/etc.

I've included an icon variant which I used to create the favicon and Windows ico files located in the icons.zip file. I've also done some work adapting an open-source SVG of a tea-cup into something that could be used in the project if desired.

Also, if you'd like to use the source files (XCF, SVG, etc.) I can provide them to you.

Great job on the wonderful project! 👍 

### Example

![screenshot_with_logo_and_icon](https://user-images.githubusercontent.com/53907850/63978599-51e18380-ca7c-11e9-9072-a789a6c9bacf.png)

### Icon variants

![2d_variant_transparent](https://user-images.githubusercontent.com/53907850/63977631-e696b200-ca79-11e9-8f34-df58506ea6a2.png)
![2d_variant_black_bg](https://user-images.githubusercontent.com/53907850/63977633-e696b200-ca79-11e9-8fb5-78aad8c502af.png)

### Vector variants

![logo_without_plate](https://user-images.githubusercontent.com/53907850/63977674-029a5380-ca7a-11e9-84bc-c3a052047e25.png)
![logo_with_plate](https://user-images.githubusercontent.com/53907850/63977675-029a5380-ca7a-11e9-8b33-27867a15bca1.png)

### Icon variants

[icons.zip](https://github.com/go-gitea/gitea/files/3557407/icons.zip)

**Comment by dunderpate** [comment]
Threw together a screenshot showing with the icon would look like in the header. The base for this screenshot was just snagged off Google Images so it's not mine.

![screenshot_with_icon](https://user-images.githubusercontent.com/53907850/63978135-42ae0600-ca7b-11e9-86da-5a1392c54ace.png)

**Comment by dunderpate** [comment]
Another screenshot with the icon, logo and favicon.

![screenshot_with_logo_and_icon](https://user-images.githubusercontent.com/53907850/63978537-2e1e3d80-ca7c-11e9-95c9-6d3a791f9e12.png)

**Comment by silverwind** [comment]
I have to say, I prefer the current flat logo more.

**Comment by dunderpate** [comment]
@silverwind Totally respect your opinion. It's a nice logo!

**Comment by guillep2k** [comment]
Me too, I prefer the current flat, monochrome logo. I think it blends nicely with the site's CSS theme, which uses clean, flat colors as well.

**Comment by dunderpate** [comment]
+1 for the open dialogue, keep the feedback coming everyone!

**Comment by jaqra** [comment]
Changes are good sometimes :)

**Comment by lafriks** [comment]
Looks nice but I would better like more stylized logo. Current one looks good but would be nice to have small improvements but imho full redesign is not needed

**Comment by dunderpate** [comment]
Right on, thanks again for the great project!
