### ISSUE TITLE
Issue numbers not linked in commits list

### ISSUE THREAD

**Issue by dunderpate** [go-gitea/gitea#8042]
- Gitea version (or commit ref): 1.9.0-dev built with go1.12.6
- Git version: 2.22.0
- Operating system: FreeBSD 12.0-RELEASE r341666 GENERIC  amd64
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
  - [x] https://try.gitea.io was down at the time this issue was authored
- Log gist:

## Description

I have an external issue tracker configured in a repository's settings, however the commits list messages don't have the issue number hyperlinked. I can confirm that the issue number is being linked properly when viewing a specific commit though. Please see the attached images for context.

If there is anymore information I can provide, feel free to let me know.

Thanks everyone!

### What I see in the commits list (incorrect)
![link_issue_commits_before](https://user-images.githubusercontent.com/53907850/64050284-296d8e00-cb3d-11e9-93d8-adc104e20876.png)

### What I expect to see in the commits list (correct)
![link_issue_commits_after](https://user-images.githubusercontent.com/53907850/64050283-296d8e00-cb3d-11e9-9314-ef3a791c1ca1.png)

### What I see on the commit page (correct)
![link_issue_commit_working](https://user-images.githubusercontent.com/53907850/64050285-296d8e00-cb3d-11e9-9f04-f3bd35f7ba5f.png)

**Comment by gary-kim** [comment]
Currently, those are not made into links.
@lafriks I remember you said there were issues with making links in pages such as the ones referenced. Should we look into fixing them for the 1.11 release?

**Comment by dunderpate** [comment]
Makes sense @gary-kim, I'm guessing it's performance related? In any case, thanks for the context. I'll wait to hear what comes out of the discussion.

**Comment by jaqra** [comment]
@garry-kim is that about to #8006 ?

**Comment by lafriks** [comment]
This is already fixed in 1.10 release
