### ISSUE TITLE
Scrum PM

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#805]
- Gitea version (or commit ref): `gitea/gitea:latest` Docker container
- Database (use `[x]`):
  - [x] PostgreSQL
  - [x] MySQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant

## Description

I want project management (following Scrum) in Gitea. In the settings there should be an option to choose between the current issue tracker and the Scrum PM. Btw I'm interested to write a big part of it myself.

**Comment by metalmatze** [comment]
I don't think gitea will ever support that out of the box.

We can however start a discussion to more deeply integrate https://taiga.io/ or https://wekan.io/ into gitea. Should be something you're looking for. :blush:

**Comment by ghost** [comment]
@metalmatze: Wekan is only a kanban board, so not really what I'm looking for, while Taiga is a pretty cool PM tool, but how'd you imagine such integration?

**Comment by metalmatze** [comment]
Well I've never used Taiga personally. But they have an API.
https://taigaio.github.io/taiga-doc/dist/api.html

So it should be possible to move things in taiga when issues are opened or closed in gitea. Or move cards (issues or whatever) in taiga after one pushes a fix for something. 
But that's to be discussed essentially.

**Comment by tboerger** [comment]
There is already a simple Gogs integration within the taiga core, this should be extended for a really productive combination of these tools. We should focus gitea really on the git hosting. Maybe we can really build a plugin system so that others can write apps that gets hooked into gitea

**Comment by ghost** [comment]
@metalmatze: Taiga isn't a simple kanban board (altough it can be one), but a whole PM tool with epics and user stories and things, so…

---

@tboerger: That currently only closes issues when mentioned in a commit message, right? I don't know how that could be extended. Btw a plugin system for Gitea would be very nice.

**Comment by tboerger** [comment]
Taiga can be used in kanban or in scrum mode. If you want to get an idea how it can be integrated just play around or read about github and waffle.io integration. Or take a look at the integration of github into trello.

**Comment by tboerger** [comment]
But to be clear, adding such a feature to the gitea core is for the current planning really out of the scope. If there is really the need for such a tool it should be better to build something standalone or via an external plugin into gitea. Because of that I'm closing the issue for now.

**Comment by ghost** [comment]
@tboerger: I know Taiga can be used in both kanban and Scrum mode, that's why I said `(altough it can be one)`. I've played around with Waffle before, but such integration would only be possible with Taiga's kanban mode (or Wekan), but not with Taiga's Scrum mode, right? That integration would be possible from Taiga's (and Wekan's) side, or does Gitea miss an API for that? Btw I totally understand such big feature would currently be really out of scope, so is there already an issue for a plugin system?

**Comment by tboerger** [comment]
AFAIK we provide the required api, this needs to be integrated within the taiga Gogs code. We already got an issue for the plugin system

**Comment by Caballerog** [comment]
In my personal opinion using Taiga and Wekan (internal projects), I believe that Taiga is so much weight and maybe more interesting use or integrated a Kanban system like Wekan. 

Any news about the integration? Thanks very much!

**Comment by emahuni** [comment]
The problem with all of the above-mentioned is portability... I love Gitea coz I can run it on windows without any problems.. Now pairing Gitea with those two will only mean that the feature can only be used by those with Linux boxes etc. I personally think that Gitea should have its own Scrum and Kanban intergrated into it.

**Comment by emahuni** [comment]
This guy has done something so far aimed at Gogs...
"
If anyone is interessted in working on this, feel free to contact me. I started working (https://github.com/mhtsbt/GogsBoard) on a gogs-powered kanban board. It's a seperate application that connects through the api:
"
 I think he should be helped.

 The sad part is I am not a Go developer. But I love this little fast app in my workflow.

**Comment by emahuni** [comment]
Please re-open this issue

**Comment by hubyhuby** [comment]
Yes please re-open the Kanban integration.
It is available in Gitlab aswell.

Exactly the same thing as gitlab would be perfect.
We already have the TAGS in Gitea, "all we need" for a version 1.0 is, representation of the isssues in a Kanban way :
- "No tags" issues are on the left in column "back logs" (DEFAULT)
- Closed issues are on the right in closed (DEFAULT)
- The user can creat columns by tag like "to do" (User specified). 

Once we have this, we can think of a nicer user interface with drag and drop for 1.1 ...

![gitlabkanban](https://user-images.githubusercontent.com/26340942/31608456-b9c690f6-b270-11e7-9fd8-bed719f782ef.jpg)

PS: maybe rename the title of the github issue with Kanban in it ?

**Comment by Caballerog** [comment]
+1

**Comment by lunny** [comment]
Looks good

**Comment by ghost** [comment]
While I have used gitlab's issue boards for project planning, and have experienced companies that use gitlab this way as well, I very recently have started using gitea for local development (gitlab is really very heavyweight to deploy locally....), and I am of mixed mind when I look at this topic here.  From my experiences many companies and groups often do use other planning/scrum/kanban tools (jira, pivatol, taigo, etc, all come to mind) even when they use gitlab (or github), and the real world result is actually so often a kind of duplication of issue management between the two.

I think the more correct answer would be creating better integration api's and methods, rather than trying to create a user experience around what will always be a subset of functionality offered by more highly specialized PM applications that already exist.  Do one thing, and do it well.

The kind of issues that exist with external tools is it is often necessary to manually copy and paste links to pull requests and branches so you can go from the external story or issue to the branch(es) related and pull requests that you are going to code review.  Yes, I have often experienced places that did that constantly.  Knowing how feature branches relate to stories in the PM system and automatically following their status as well as inserting direct links in external project management tools would be a major win.  Pairing up with an existing freely licensed PM application that also has light hosting requirements, and then improving such API integration together to achieve things like that I think would be great.  Be an eco-system, not a one-stop that always is lacking.

**Comment by tboerger** [comment]
I would also suggest to finally implement a plugin API and provide stuff like that as separate plugins instead of bloating the core even more with a niche feature that maybe gets rarely used.

**Comment by hubyhuby** [comment]
Hi,
Not sure how a nitch feature it is. It s always hard to say. In the business I work in this is a must have. Especially since we have to interact with end customer & testers, this kind of representation is more straight forward.
It gives feed backs on whats going on with his project to the customer.

On a developper perspective, I understand you don t see the use of it. After all it is just representing the same datas as "taggs". Why would we need this? 
I believe it is a customer / end user feature. Not a developer thing. It is very useful for people not in code....for exemple testers of your product or service... Mostly people not on this thread :D 

Now on the project perspective, maybe the remaining question would be : do we build a gitea for tester / end customers bug reporting ? Or do we build a gitea only for developpers ?

**Comment by metalmatze** [comment]
I don't think that gitea should get as bloated as e.g. GitLab. Connecting to a third party API seems like a much better option.

**Comment by SchoolGuy** [comment]
I am using gitea (and previously used Gogs) and the main advantage is that is offering pretty much the same functionality as github/...., BUT without the heavy load. I would agree to the comments that state a solution via an API. My reason is for that, you give every user the freedom which service he/she would like to use. You are not forcing them to use your solution which will obviously not be perfect (because nothing is perfect).

**Comment by gsantner** [comment]
If somebody is seeking, take a look at this: https://github.com/Incubaid/gitea-kanban

My honest opinion on this: table layout with dragndrop is not too much, but allows easy and lightweight visual management of issues.
Don't know if it really screams plugin, but if directly inside gitea, but for me looks like the biggest part of this is one rendered html template file. 😅
Thats what you can see too on the peoject above, most is boilerplate files and config (which gitea all has already), plus some additional logic for the table.^^

**Comment by r0bbie** [comment]
Very disappointed that this issue was closed without further consideration. We've just been examining whether to move to either Gitea or GitLab - I personally prefer the interface and simplicity of Gitea, but this was the essential missing feature that forced us towards GitLab for now. It's fair enough wanting to keep Gitea lightweight, but this is a fairly essential feature for a lot of people - having issues support is great, but if the workflow isn't in place to efficiently and effectively organise and work through those issues it's a significant drawback over other options.

**Comment by ptman** [comment]
I use kanboard and wekan and taiga have been mentioned. Webhooks to integrate better with external issue trackers should definitely be higher priority than implementing it as a feature

**Comment by lafriks** [comment]
@r0bbie if anyones create PRs for this, it will still be reviewed for inclusion in Gitea

**Comment by rakshith-ravi** [comment]
Hey @lafriks. I'm planning to work on this. I'm fairly experienced with open source and web development, but completely new to golang. Is there any boiler plate code or another half-implemented fork that I can work on top of?

**Comment by lafriks** [comment]
I'm not aware of anything such being started

**Comment by gsantner** [comment]
hey everbody wanting to start on this. Just noting that there is a (non-gitea-integrated) solution available for this using gitea API. It is an external Node.js application and can be found here: <https://github.com/Incubaid/gitea-kanban>.

I would suggest to maybe drop a message there or talk with the projects developers if they would maybe be open for joining forces or reusing something ;)

@rakshith-ravi  @Mikjaer @r0bbie

**Comment by Mikjaer** [comment]
@rakshith-ravi Im not well-versen in golang, i spend an afternoon reading gitea source and it seems doable. I've looked around and i think the best solution is to create a plugin-solution for gitea and then write our desired features as a plugin.

**Comment by emahuni** [comment]
wow that's great @gsantner

**Comment by yf-hk** [comment]
So is there a plugin system in gitea?

**Comment by lastlink** [comment]
I wrote a chrome extension for this purpose, already shows a kanban view of issues by labels. Supports gitea first, working on the other major ones as well. You can try it out on gitea.com. You must wait for the self host version to be approved b4 using that for you're own custom instances https://github.com/funktechno/git-kanban-enhanced-chrome-extension. Simple non self hosted extension - https://chrome.google.com/webstore/detail/git-kanban-enhance/ehoibkdpdgjcjnnalkbiidajafoimnaa
