### ISSUE TITLE
'Docker log' command doesn't show logs

### ISSUE THREAD

**Issue by holmesb** [go-gitea/gitea#8050]
Neither `docker logs` nor `kubectl logs` contain gitea.log content.  Need to log to stdout & stderr for these commands to work, but instead container logs to file: /app/gitea/log/gitea.log.  [Possible solution](https://serverfault.com/questions/599103/make-a-docker-application-write-to-stdout).

**Comment by lafriks** [comment]
You can set what logs do you want to output to stdout in app.ini
