### ISSUE TITLE
Redirect on repo name change

### ISSUE THREAD

**Issue by ethantkoenig** [go-gitea/gitea#806]
If `user1` renames `repo1` to `repo2`, it would be nice if all of the old `../user1/repo1/..` URLs redirected to the corresponding `../user1/repo2/..` URLs.

I'm happy to work on implementing this, but just want to make sure there is interest :smile:

**Comment by appleboy** [comment]
@ethantkoenig Good feature. Please feel free sends a new PR.

**Comment by KangoV** [comment]
Maybe, when changing repo details, we could assign/remove aliases. The old repo name would be listed as an alias. Just a thought.
