### ISSUE TITLE
Search index not updated when editing issue title

### ISSUE THREAD

**Issue by bobemoe** [go-gitea/gitea#8060]
- Gitea version (or commit ref):  1.10.0+dev-237-g765be7032
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant

## Description

When an issue title is edited, the issue can't be found using the new title, in fact it still appears in the search results using the old keywords!

I created issue with title "specific keyword"  then edited title and changed it to "renamed".

You can see the issue is not found in search for "renamed":

https://try.gitea.io/bobemoe/test/issues?type=all&state=open&labels=0&milestone=0&assignee=0&q=renamed

But can still be found for "specific keyword":

https://try.gitea.io/bobemoe/test/issues?type=all&state=open&labels=0&milestone=0&assignee=0&q=specific+keyword

**Comment by bobemoe** [comment]
Brilliant, this has fixed the issue, thanks for quick response :) 

I need to edit the title again to trigger the reindex. Is there any way to run a full re-index to catch anything that was edited before the fix was implemented?

**Comment by guillep2k** [comment]
@bobemoe You can stop Gitea, then safely remove the directory `indexers/issues.bleve` and restart Gitea again. The index will be rebuilt in a few seconds, or minutes if you've got a large number of issues.

**Comment by guillep2k** [comment]
@bobemoe The fix is not included in any release yet, but you can get it if you build from source.

**Comment by bobemoe** [comment]
Curious. I'm running the dev build, which I think it pretty up to date? I tested by editing my title on the above try.gitea which is now at 1.10.0+dev-245-gc027eac1d changed it to "renamed again" and then it appeared to get re-indexed! Also did a second test and with new issue and it also working as expected. 

Thanks for the tip about rebuilding the indexes, most useful :)

**Comment by guillep2k** [comment]
I'm not sure how try.gitea.io is installed, but it could be that it's forced to rebuild indexes upon installation (it's a docker image AFAIK).

**Comment by bobemoe** [comment]
This is working fine in web frontend (thanks again for fixing) but I've just noticed its still a problem when updating issue title or body through the API. Would you like me to open new issue?

**Comment by bobemoe** [comment]
Also a problem when editing issue body in the web frontend.

**Comment by guillep2k** [comment]
> 
> 
> This is working fine in web frontend (thanks again for fixing) but I've just noticed its still a problem when updating issue title or body through the API. Would you like me to open new issue?

Yes, please
