### ISSUE TITLE
Fatal: unable to access: SSL certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by Gooberpatrol66** [go-gitea/gitea#8063]
- Gitea version (or commit ref): 1.8.3
- Git version: 2.21.0
- Operating system: Gentoo
- Database (use `[x]`):
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
I created a new repo in gitea. I then followed the instructions in “Pushing an existing repository from the command line”.

```
git remote add origin https://localhost/gitea/user/project.git
git push -u origin master
fatal: unable to access 'https://localhost/gitea/user/project.git/': SSL certificate problem: unable to get local issuer certificate
```

SSL works without issue when I visit the web interface.

**Comment by lafriks** [comment]
You have to put issuer certificate in CA trust store:
https://wiki.gentoo.org/wiki/Local_certificates

**Comment by Gooberpatrol66** [comment]
That doesn't work. Am I supposed to do this, even if I'm using letsencrypt certificates?

**Comment by lafriks** [comment]
You should not be using `localhost` but full domain name if you have letsencrypt

**Comment by Gooberpatrol66** [comment]
Thanks
