### ISSUE TITLE
Prevent collision naming with a gitea-vendor directory

### ISSUE THREAD

**Issue by camlafit** [go-gitea/gitea#8072]
Hello 

To note a discussion with @sapk  discord, could be interesting to use a root directory as gitea-vendor/ or web-vendor/ or any other path to store all statics resources.

Could be solve with a different way #20 

Actual solution has two troubles :
* we must manage an hardcoded reserved keyword (an some name could be licit account/organization)
* An 500 error is raised without any information when we try to rename an organization with a keyword in this list.

**Comment by wxiaoguang** [comment]
`/assets` is reserved and it's for static resources.
