### ISSUE TITLE
why it works on both ports 80 and 3000??

### ISSUE THREAD

**Issue by jayjupdhig** [go-gitea/gitea#8080]
why it works on both ports 80 and 3000 when i use that manual -> http://192.168.80.223/

???

Regards, jan

**Comment by martijintro** [comment]
mean that: https://www.vultr.com/docs/how-to-install-gitea-on-debian-9

**Comment by sapk** [comment]
Quickly looking at the tutorial, I think that the app.ini indicate to gitea to listen to 0.0.0.0:3000 and nginx listen to 0.0.0.0:80 and forward to gitea. You can edit `app.ini` to listen only to local addresq 127.0.0.1 with the option `HTTP_ADDR=127.0.0.1`. https://docs.gitea.io/en-us/config-cheat-sheet/

**Comment by martijintro** [comment]
I entered a wrong URL after installation on the /install page -> http://localhost instead of http://FIXED_IP, mea culpa, thank you very much.
