### ISSUE TITLE
how to change the gitea uri (first call of the freshly installed application) AFTER set it...?

### ISSUE THREAD

**Issue by jayjupdhig** [go-gitea/gitea#8081]
how to change the gitea uri (first call of the freshly installed application) AFTER set it...?

**Comment by sapk** [comment]
You can edit you app.ini file and restart gitea to take effect. Please have a look at the documentation : https://docs.gitea.io/en-us/config-cheat-sheet/

**Comment by martijintro** [comment]
thx!!
