### ISSUE TITLE
Different problem with mirroring / sync

### ISSUE THREAD

**Issue by jayjupdhig** [go-gitea/gitea#8084]
There are many problems with mirroring/sync as described here (last entries): https://discourse.gitea.io/t/external-git-server/1425/13

- When i click "Synchronized", the commits from the mirror server will not be updated in the Web GUI. But they will be updated in the SourceTree GIT client connected to Gitea

- When i try to commit/push from the SourceTree client (connected with Gitea, not the mirror repo), i got a message with "read only" / 403.

-> The remote/mirroring repo has absolutely no problems with authentication - it never had. It uses basic authentication (Standard authentication by IIS - NOT "Windows Authentication") With SourceTree, it alway worked. -> So no reason for "read only"... The remote repo was never "read only". We need http basic auth for all, read, write, update, delete, whatever...

Regards, Jan

**Comment by martijintro** [comment]
And "private" seems to have nothing to do with the "read-only" / 403 problem.

Is "private" the option that prevents the read-only-access for everyone. (Similar to GitHub i think?)

Regards, Jan

**Comment by martijintro** [comment]
After a few day i saw the problem (which is not really) with the "Synchronize" button for remote repo in Gitea:

https://discourse.gitea.io/t/external-git-server/1425/13


**_"On the repo main page, there is only 1 entry in vertical direction - even if there are more than 1 commit. So i saw, you have to click on “x Commits” to view all of them…

But the “remote repository is read-only” problem still persists - and no, the remote repo is NOT read-only… how i should done the first (initial) commit when it’s read only…?

And i’m still able to commit on the remote repo when i’m directly connected to it. But not if Gitea is connected to it.

And the http basic auth url stored in gitea works when i copy/paste it to browser bar:

http://admin:password@192.168.80.20/WHATEVER

And SourceTree, where i can commit to the repo (directly, no over Gitea) also uses that http basic auth.

So problem 1 i not really a problem, but problem 2 is still unsolved!

How to solve it?

Thank you for your feedbacks,
Jan"_**


....ok, so the "remote repo is readonly" is sill present. I can't say it is a bug, but so it seems it is.

Maybe somebody can proof the opposite - that it's not a bug? If yes, i think we can close that issue.


Regards,
Jan

**Comment by martijintro** [comment]
How to make font bold and/or italic here?

There are "markers" like '_**', but they don't change the text format and will be show as plain text

**Comment by martijintro** [comment]
maybe the workaround it to commit/push only and directly to the remote repo. never push/commit to gitea.

but it's really really sub-optimal and nothing else..

**Comment by martijintro** [comment]
No anwser??

**Comment by lunny** [comment]
Which one is your current problem?

**Comment by martijintro** [comment]
“remote repository is read-only”

But it's NOT read-only... when i connect with SourceTree, it isn't.

**Comment by lafriks** [comment]
It is not really understandable from Your description where error is shown in Gitea or in SourceTree?

**Comment by martijintro** [comment]
1. create a repo on non git server A
2. do an initial commit
3. do a new migration on git server B, that server is with github
4. create a new migration with "mirror" option to the repo on git server A
5. set up the git repo from server B, the one with gitea
6. trying to commit & pull to the git repo on server B (gitea) will fail on that read-only problem

If there are any questions, don't hesitate to ask me.

**Comment by martijintro** [comment]
"It is not really understandable from Your description where error is shown in Gitea or in SourceTree?"

Gitea...

**Comment by 6543** [comment]
giteas repo type "mirror" only mirrors a contend !
if you like to work with it you can converte it to a normal repository - but then it wont mirror a other repository

**Comment by 6543** [comment]
you perhaps try to setup something like a gitlab mirror where you can also work on the mirror repo - but the technik behind isn't implemented in gitea jet (this can make sync conflict)

**Comment by martijintro** [comment]
OK, thx.

What is "contend" ?


"gitea akts like a real mirror - you CAN change things in the real world but the mirror only display a inverted version wich CANT BE MODIFIED"

...all ok, thx again! :-)

**Comment by 6543** [comment]
> What is "contend" ?
commits & branches

**Comment by martijintro** [comment]
ok thx
