### ISSUE TITLE
Error 404 - wrong related link in issue page

### ISSUE THREAD

**Issue by mbarinc** [go-gitea/gitea#8085]
- Gitea version (or commit ref):  1.10.0+dev-145
- Git version: 2.20
- Operating system: RedHat 7.3
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (https://try.gitea.io/mbarinc/test/src/branch/tag_001)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
If I open a Issue and relate it to a tag, when I try to go to this specific tag from the issue page by clicking the link near the issue name, I have an 404 error. This because in the url there is "branch" instead of "tag".

No errors if I create an Issue and relate it to a branch.

To reproduce the error:
1. start from https://try.gitea.io/mbarinc/test/issues
2. click on "tag_001"

**Comment by sapk** [comment]
The line to change make is here : https://github.com/go-gitea/gitea/blob/13388258a4ef1593784e8daf97506575cc284f61/templates/repo/issue/list.tmpl#L220-L222

We should check the ref type to display a branch link or tag link.

**Comment by SijmenSchoon** [comment]
I would like to give this a try as a first issue
