### ISSUE TITLE
make test -> fails

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#8089]
make test fail on linux 64bit

tested versions: 1.8.3; 1.9.2; current (https://github.com/go-gitea/gitea/commit/4cb1bdddc88580d20305415869d4c13827097bd9)

**Comment by 6543** [comment]
## runing ... on v1.9.2
```sh
go list ./... | grep -v /vendor/ | grep -v 'code.gitea.io/gitea/integrations' | while read line; do 
  GO111MODULE=on go test -mod=vendor -tags='sqlite sqlite_unlock_notify' $line
  error="$?"; [ "$error" == "0" ] || {
    echo "ERROR: $error; PACKAGE: $line" >> error.log
  }
done
```

**Comment by 6543** [comment]
code.gitea.io/gitea/models:
 - models/pull.go:225:apiFormat() [E] GetBranch[master]: no such file or directory
 - models/pull.go:225:apiFormat() [E] GetBranch[master]: no such file or directory
 - modules/base/tool.go:223:libravatarURL() [E] LibravatarService.FromEmail(email=): error mail: no address
 - modules/base/tool.go:223:libravatarURL() [E] LibravatarService.FromEmail(email=): error mail: no address
 - modules/base/tool.go:223:libravatarURL() [E] LibravatarService.FromEmail(email=): error mail: no address
 - models/org.go:308:isOrganizationOwner() [E] Organization does not have owner team: 2
 - models/org.go:308:isOrganizationOwner() [E] Organization does not have owner team: 9223372036854775807
 - odels/repo_mirror.go:243:runSync() [E] Failed to synchronize tags to releases for repository: GetTagCommitID: exit status 128 - fatal: mehrdeutiges Argument 'v0.2': unbekannter Commit oder Pfad existiert nicht
 - models/repo.go:1683:updateRepository() [E] Failed to update size for repository: UpdateSize: chdir /tmp/repos113439488/user11/repo9.git: no such file or directory

**Comment by 6543** [comment]
```
GO111MODULE=on go test -mod=vendor -tags='sqlite sqlite_unlock_notify' code.gitea.io/gitea/modules/git
--- FAIL: TestRepoIsEmpty (0.00s)
    repo_test.go:34: 
        	Error Trace:	repo_test.go:34
        	Error:      	Received unexpected error:
        	            	check empty: exit status 128 - fatal: Ihr aktueller Branch 'master' hat noch keine Commits.
        	Test:       	TestRepoIsEmpty
FAIL
FAIL	code.gitea.io/gitea/modules/git	1.866s
```

**Comment by 6543** [comment]
code.gitea.io/gitea/modules/repofiles
 - models/repo.go:499:mustOwnerName() [E] Error loading repository owner name: user does not exist [uid: 0, name: , keyid: 0]

**Comment by 6543** [comment]
modified https://github.com/go-gitea/gitea/pull/7980 for now ...

**Comment by techknowlogick** [comment]
These tests are run via our CI. It also runs using linux 64bit.

These tests should be passing, if they are failing then something should be reviewed with how the tests are being run. Looking at some of the fails above, it looks like the data isn't available for the tests.

**Comment by 6543** [comment]
I'll test on my local mashine ... and try to get the test passed

**Comment by 6543** [comment]
with the current version test ...
* **passes** on alpine edge
* and **fialed** on my dev pc (archlinux)
* and **fialed** also on a fresh archlinux container install

modules wich fail on arch:
```
ERROR: 1; PACKAGE: code.gitea.io/gitea/models
ERROR: 1; PACKAGE: code.gitea.io/gitea/routers/repo
```

**Comment by 6543** [comment]
> sudo pacman -S git-lfs
**fixed** it on the fresh arch install

so I'll close this for now ...
