### ISSUE TITLE
unit-test: make github migrations test optional

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#8090]
is there a option to disable `github_test.go` only if i like to test `modules/migrations`?

-> https://travis-ci.org/alpinelinux/aports/builds/580887167
-> https://github.com/alpinelinux/aports/pull/10887

**Comment by sapk** [comment]
We could provide our own testing module with a method similar to testing.Short() but for testing.External that would be called by test that call external services and return false by default except if a env variable is set ?

**Comment by 6543** [comment]
@sapk you mean only run github-migration-test if a env variable is set?

-> in this case we could use a gitHub-token as var witch is a drone secreat -> next problem solved

**Comment by sapk** [comment]
Yes that good enough (no need to over engineer this ny bad).

**Comment by 6543** [comment]
I'll close this for now -> if a error occure on e.g. alpine ... migration test is skiped ...
