### ISSUE TITLE
Webhooks Do Not Use Proxy Settings

### ISSUE THREAD

**Issue by cdoantsys** [go-gitea/gitea#8092]
- Gitea version (or commit ref): 1.9.2
- Git version: 2.23.0 
- Operating system: linux/amd64
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
In my environment Gitea does not have direct internet access, a proxy is required. I have been able to successfully mirror repositories and use the proxy to download other items. However, I am not able to post webhooks via Microsoft Teams. After further investigations it appears that the [http client](https://github.com/go-gitea/gitea/blob/master/models/webhook.go#L927) that is created in the [InitDeliverHooks](https://github.com/go-gitea/gitea/blob/master/models/webhook.go#L924) function in [webhook.go](https://github.com/go-gitea/gitea/blob/master/models/webhook.go) does utilize any proxy settings. 

#### Current Implimentation

```go
// InitDeliverHooks starts the hooks delivery thread
func InitDeliverHooks() {
	timeout := time.Duration(setting.Webhook.DeliverTimeout) * time.Second

	webhookHTTPClient = &http.Client{
		Transport: &http.Transport{
			TLSClientConfig: &tls.Config{InsecureSkipVerify: setting.Webhook.SkipTLSVerify},
			Dial: func(netw, addr string) (net.Conn, error) {
				conn, err := net.DialTimeout(netw, addr, timeout)
				if err != nil {
					return nil, err
				}

				return conn, conn.SetDeadline(time.Now().Add(timeout))

			},
		},
	}

	go DeliverHooks()
}
```

#### Proposed Implementation

```go
// InitDeliverHooks starts the hooks delivery thread
func InitDeliverHooks() {
	timeout := time.Duration(setting.Webhook.DeliverTimeout) * time.Second

	webhookHTTPClient = &http.Client{
		Transport: &http.Transport{
			TLSClientConfig: &tls.Config{InsecureSkipVerify: setting.Webhook.SkipTLSVerify},
			Proxy: http.ProxyFromEnvironment,
			Dial: func(netw, addr string) (net.Conn, error) {
				conn, err := net.DialTimeout(netw, addr, timeout)
				if err != nil {
					return nil, err
				}

				return conn, conn.SetDeadline(time.Now().Add(timeout))

			},
		},
	}

	go DeliverHooks()
}
```
I have implemented this in my environment and it is currently working.

**Comment by lunny** [comment]
@cdoantsys could you send a PR?

**Comment by wpmp** [comment]
Will this issue also be resolved in 1.9.4 or 1.10.0 only?

**Comment by lunny** [comment]
It will be on 1.10.0 only

**Comment by wpmp** [comment]
Too bad, thanks.
Hope 1.10.0 will come out soon :)
