### ISSUE TITLE
Gitea returns import path for organization

### ISSUE THREAD

**Issue by rutgerbrf** [go-gitea/gitea#8095]
- Gitea version (or commit ref): 1.9.2
- Git version: 2.22.0
- Operating system: Manjaro 18.0.4
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant

## Description

To quote:

> In module mode in Go 1.13, the go command checks all possible module paths in parallel for the requested package.

Gitea returns a non-valid Git fetch URL for e.g. `https://try.gitea.io/test`, as seen in the example below. This makes it impossible to use Go modules pulling dependencies from a private Gitea instance, because Go 1.13 expects no clone URL if it is not a valid repository path (see GitLab behavior). This issue is related to golang/go#34075. See that issue for more information.

```
$ curl https://try.gitea.io/test/?go-get=1  
<!doctype html>
<html>
        <head>
                <meta name="go-import" content="try.gitea.io/test git https://try.gitea.io/test/.git">
                <meta name="go-source" content="try.gitea.io/test _ https://try.gitea.io/test/src/branch/master{/dir} https://try.gitea.io/test/src/branch/master{/dir}/{file}#L{line}">
        </head>
        <body>
                go get try.gitea.io/test
        </body>
</html>
```

But test is an organization and this information should not be added, as it makes it impossible to retrieve dependencies using go get in Go 1.13.

**Comment by rutgerbrf** [comment]
There is some code which could be used in https://github.com/profects/gitea/tree/fix-go1.13-invalid-import-path, and I will probably create a merge request sometime soon. It would be nice if this issue could be fixed in a 1.9 minor release.

**Comment by lunny** [comment]
@rutgerbrf Please.

**Comment by transferkraM** [comment]
Just a + here to increase the pressure! ;)

**Comment by lunny** [comment]
@rutgerbrf I can confirm that your patch works.
