### ISSUE TITLE
Sonarqube gitea plugin

### ISSUE THREAD

**Issue by umutpiri** [go-gitea/gitea#8096]
I am using Gitea-Jenkins-SonarQube trio. It works great, using with sonarqube badges to see if quality gate is passed or not! But, I want to see sonarqube analysis results in my commits as inline comments. Is there an easy way to do it? 
I just saw https://github.com/lafriks/sonar-gitea-plugin, but I think it is not finished yet.
Thanks.

**Comment by lafriks** [comment]
Yeah, I want this also but had no time to work on this

**Comment by MarkusAmshove** [comment]
Gitea needs to have an API for PR reviews/comments on code for this to make sense, right? 
We already use sonarqube result for commit status (for checks on PRs), but comments on code about issues would be cool :-)

**Comment by lafriks** [comment]
@MarkusAmshove how do you get sonarqube results to Gitea commit status?

**Comment by MarkusAmshove** [comment]
I can get the Quality Gate status from the SonarQube Plugin for Jenkins and then simply POST it to the commit on Gitea.

The report itself is not part of the plugin. It is implemented in Groovy (e.g. Jenkins Pipeline) which uses the result of the analysis

**Comment by MarkusAmshove** [comment]
To give an example of the usage:

Jenkinsfile:
```groovy
// some build stage, e.g. Gradle for Java builds
stage('Build') {
    withSonarQubeEnv('our-sonar') {
        sh './gradlew build sonarqube'
    }
}

stage('QualityGate') {
    if(!isPullRequest()) { // checks for env.CHANGE_TARGET, because we only want to analyze HEAD builds
        timeout(time: 1, unit: 'HOURS') {
            def qualityGate = waitForQualityGate() // builtin method from the sonarqube plugin
            if(qualityGate.status != 'OK') {
                def message = "QualityGate failed: ${qualityGate.status}"
                giteapipeline.reportQualityGate(this, 'Organisation', 'Repository', 'failure', 'sonarqube/qualitygate', message)
                error "$message"
            }
            else {
                giteapipeline.reportQualityGate(this, 'Organisation', 'Repository', 'success', 'sonarqube/qualitygate', 'QualityGate OK')
            }
        }
    }
}
```

Within the pipeline library

```groovy
// Status can be: pending failure error success
static def reportQualityGate(script, organisation, repository, status, context, description) {
    def currentSha = getCurrentCommit(script)

    def request = [
            context: context,
            description: description,
            state: status,
            target_url: script.env.RUN_DISPLAY_URL
    ]

    def jsonRequest = JsonOutput.toJson(request)
    script.httpRequest(
            acceptType: 'APPLICATION_JSON',
            authentication: 'supersecret',
            contentType: 'APPLICATION_JSON',
            httpMode: 'POST',
            requestBody: jsonRequest,
            responseHandle: 'NONE',
            url: "http://gitea/api/v1/repos/$organisation/$repository/statuses/$currentSha")
}
```

I've used [this documentation](https://docs.sonarqube.org/latest/analysis/scan/sonarscanner-for-jenkins/#AnalyzingwithSonarQubeScannerforJenkins-AnalyzinginaJenkinspipeline) to find the steps and reported quality gate names of the sonarqube plugin.

**Comment by lkraider** [comment]
@lafriks I checked your repo, but it doesn't contain any source code changes regarding gitea? Do you have the changed sources? Could you upload there so we can contribute?

**Comment by lafriks** [comment]
@lkraider not yet, have not pushed changes as code still does not even compile :D

**Comment by lkraider** [comment]
@lafriks maybe push to a develop branch, where we can help?

**Comment by maulik-modi** [comment]
hi @lafriks , any luck with compilation, could you please commit as is?

**Comment by lafriks** [comment]
It is not really possible to implement this directly just as SonarQube plugin as it needs to be thighly integrated into SonarQube core and depend on SonarQube ALM integration. I submitted WIP PR (SonarSource/sonarqube#3248) to add Gitea ALM but I highly doubt it will be added anytime soon :(

**Comment by lafriks** [comment]
As I got reply in https://community.sonarsource.com/t/add-alm-integration-for-gitea/31175/4 SonarQube developers won't most probably add Gitea only option is to hack in extended ALM plugin that adds Gitea and extend mc1arke/sonarqube-community-branch-plugin#241 to use it

**Comment by lafriks** [comment]
I did some more investigation and pretty much it looks like there is no way to add Gitea to SonarQube as their developers won't even extend internal core java enum to add Gitea to it see SonarSource/sonarqube#3249 that would allow create Gitea plugin.

So pretty much only option is to fork SonarQube to add it or create alternative in Golang :D
