### ISSUE TITLE
Windows 7, Creating pull request gives 500 error

### ISSUE THREAD

**Issue by PrashamTrivedi** [go-gitea/gitea#810]
- Gitea version (or commit ref):  1.0.1
- Git version: 2.7.0Windows1
- Operating system: Windows 7
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:
```
Deleting old local copy [data\tmp\local-repo\1]: exit status 3
[...gitea/models/pull.go:432 testPatch()] [E] CreateRepositoryNotice: database table is locked
[...routers/repo/pull.go:706 CompareAndPullRequestPost()] [E] NewPullRequest: testPatch: UpdateLocalCopy: git clone master: exit status 128 - fatal: destination path 'data/tmp/local-repo/1' already exists and is not an empty directory.
```
## Description
Upon clicking `Create Pull Request` button in my hosted server, I get 500 errors.
...

Additional Information.
- Downloaded binary and running using windows service.
- I can't see `data/tmp/` anywhere.

**Comment by PrashamTrivedi** [comment]
FYI: This issue doesn't happen in gitea 1.0.0+193-gea8c8cd with updated git version:  2.8.3

**Comment by lunny** [comment]
Since it will not happened in 1.1, I will move this to 1.0.3.

**Comment by lunny** [comment]
Since v1.0.3 has been dropped. I will close this. Please upgrade to 1.1.x instead.
