### ISSUE TITLE
variables/tags in custom readme defined as "missing"

### ISSUE THREAD

**Issue by rmbleeker** [go-gitea/gitea#8102]
- Gitea version (or commit ref): 1.9.2
- Git version: 1.8.3.1
- Operating system: RHEL 7
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

I'm currently setting up and customizing Gitea within our organization. When trying out a custom readme file in `custom/options/readme` I noticed that the variables in that file (enclosed in curly brackets) are not expanded into their values. Even an exact copy of the **Default** readme file in https://github.com/go-gitea/gitea/blob/master/options/readme/Default does not work properly, all variables are expanded to the string **Missing**. The Default readme works however and generates a proper README.md file in the repo when initialized, filled with the name and description of the repo.

## Screenshots

![gitea_missing](https://user-images.githubusercontent.com/4312801/64346307-2ae1ff00-cff2-11e9-8a06-ad56a4f6cf15.PNG)

**Comment by wxiaoguang** [comment]
Outdated, please refer to the latest release.
