### ISSUE TITLE
Feature request: Embeddable .js option

### ISSUE THREAD

**Issue by jscottelblein** [go-gitea/gitea#8110]
I'd love to have the option to get an embeddable  link to a file when viewing any specific file in a repo.

**Example:**
On GH you can create Gists, and once you do, it offers an option to copy an embeddable .js file that you can put on any other site. If you're not already familiar with it, it looks like this:

![image](https://user-images.githubusercontent.com/1524526/64386567-1bb57e00-cfff-11e9-8921-691b54da115c.png)

**Which gives you a script like:**

`<script src="https://gist.github.com/STaRDoGG/70bc7807cfdb2a88a04dcad8474dbd07.js"></script>`

And then once run on a site, shows you the code, all pretty and formatted, etc.

It'd be awesome to be able to do the same thing with any file in a repo in Gitea as well, so we can embed code from our own repos into other sites.

Perhaps just clone and modify the Gist .js file and modify it to work with Gitea?

**Comment by lunny** [comment]
I think you can already do that, i.e. https://gitea.com/grafana/grafana/raw/branch/master/public/vendor/bootstrap/bootstrap.js

**Comment by csarn** [comment]
I just wanted to say that there are other people out there (i.e. me) that would like to have this feature :)

**Comment by techknowlogick** [comment]
folding this into https://github.com/go-gitea/gitea/issues/16670
