### ISSUE TITLE
gitea synchronize repository 

### ISSUE THREAD

**Issue by withlin** [go-gitea/gitea#8113]
hi，How does gitea synchronize code? Is there a related document? For example, I have two computer rooms, A and B respectively. The C personnel submit the code in the A machine room and automatically synchronize to the B machine room. do you have any better suggestions?

**Comment by typeless** [comment]
@withlin I am not familiar with the feature and its implementation.
You can have a look at the code at `/models/repo_mirror.go`.
AFAIK, if you have the `mirror` checked when `migrating` a repository, Gitea will register some webhooks and automatically push(or pull?) the updates of the other repository for you.

**Comment by guillep2k** [comment]
I hope I don't misunderstand the scope of your question, so please forgive me if I do.

Gitea is a project management system that is built around **git**. Git is a program used to synchronize source code among developers, no matter where they are located. I'd recommend reading the first few pages of the [git book](https://git-scm.com/book/en/v2) to learn about it.
