### ISSUE TITLE
Determine SSH Key Name by Comment

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#812]
- Gitea version (or commit ref): `gitea/gitea:latest` Docker container
- Database (use `[x]`):
  - [x] PostgreSQL
  - [x] MySQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant

## Description

I want Gitea to determine the SSH Key Name by using it's comment.

**Comment by lunny** [comment]
duplicated #424, please discuss there.

**Comment by ghost** [comment]
@lunny: No, I meant the following:

[![Screen Record](https://zippy.gfycat.com/AcclaimedDearestBrant.gif)](https://gfycat.com/AcclaimedDearestBrant)

**Comment by appleboy** [comment]
@wb9688 very clear.

**Comment by ghost** [comment]
@appleboy: Was that meant sarcastically? If so, you could click the GIF to see it at normal speed.

**Comment by appleboy** [comment]
@wb9688 No, I understood what you want. I will implement this feature.

**Comment by lunny** [comment]
@wb9688 I see.

**Comment by appleboy** [comment]
@lunny Reopen this issue?

**Comment by appleboy** [comment]
@wb9688 I created new PR to implement this feature. Please take a look at it.

**Comment by ghost** [comment]
Nice, thanks!
