### ISSUE TITLE
What happened to v1.9.3?

### ISSUE THREAD

**Issue by stbuehler** [go-gitea/gitea#8125]
Hi,

my cronjob looking for new gitea releases found a v1.9.3 tag and is now unhappy because there are no binaries for it...

Also it seems the tag was deleted later - it would be nice to know why :)

Thanks for all your work!

**Comment by sapk** [comment]
It was tagged for release but build failed because the xgo container was updated to 1.13. The xgo ci build will need to be fixed to 1.12 before and the release will be re-tagged.

**Comment by ArchangeGabriel** [comment]
@stbuehler I would advise to look for GitHub releases instead of tag, especially since re-tagging might happen. Note that you can even suscribe to them by email. ;)

**Comment by stbuehler** [comment]
I like installing software as debian packages from proper debian repositories, that is what the cronjob is for (it builds real simple debian packages though). I'm not quite sure why you think people writing cronjobs would consider release email subscriptions helpful... unless you wanted to suggest a procmail script handling those emails :)

Retrieving assets from github releases automatically isn't that much fun either, although I might need less requests now (i.e. less likely to hit the rate limit) with the new GraphQL API; it still can't filter much (e.g. no "only assets with filename matching <regex>"), and 74 assets are quite a lot (might end up hitting another limit - only 100 items (in a single list) per request allowed).

But please consider this: rewriting history of public git branches, retagging and republishing debian packages (with the same version) are all bad in very similar ways.

(Also, just fyi: right now I'm fetching from https://dl.gitea.io/gitea/, and need the git tags to know for sure which folders contain real releases, and which are just branches that get re-uploaded.)

I'm btw fine with closing this (actually surprised you didn't already) - thanks for the explanation! (even if I'm not happy about it)

**Comment by techknowlogick** [comment]
Some good news about dl.gitea.io is it actually has a JSON API, so your cronjob can parse releases that way.

Example: `curl -H "Accept: application/json" https://dl.gitea.io/gitea/`

Also even with a tag, the CI has to build the binaries, so if your cronjob had fetched tags, then looked for binaries there is a possibility that it could try to fetch before there are build. By using dl.gitea.io you ensure that the binaries are built.
