### ISSUE TITLE
download locations 1.9/ vs 1.9.3/

### ISSUE THREAD

**Issue by flobee** [go-gitea/gitea#8132]
- Gitea version (or commit ref): 1.9.2
- Operating system: linux-amd64
## Description

Hi
I'm using the following url to download latest 1.9* versions (https://dl.gitea.io/gitea/1.9/)
Currently: the linux-amd64 version does not contain the 1.9.3 ((https://dl.gitea.io/gitea/1.9.3/)) version like i expected. Worked already before... in accident?

```
gitea-1.9-linux-amd64 | 76 MiB | 09/07/2019 05:19:25 PM
gitea-1.9.3-linux-amd64 | 76 MiB | 09/07/2019 06:21:09 PM
```
Kind regards Florian

**Comment by lunny** [comment]
1.9 is a release branch.
1.9.3 is a tag on that branch.

**Comment by techknowlogick** [comment]
As lunny said, 1.9 is based on latest commit to release/v1.9 branch, and 1.9.3 is a specific tag. Will close this issue now.

**Comment by flobee** [comment]
Hi! Well: semver.org? 1.9 means any of 1.9 which means 1.9 matches to 1.9.* 
Thats why i'm asking! :-)
Kind regards

**Comment by guillep2k** [comment]
It's not the same. This doesn't follow `npm` rules, and doesn't need to. The 1.9 _branch_ is mutable, which means that whatever changes are approved for the next 1.9.x release will pile up there. It's a _working_ branch, not meant as a release outlet. It doesn't mean "the latest 1.9.x there is".
The 1.9.x tag (e.g. `1.9.2`) is the immutable repository snapshot formally released as such version.

**Comment by techknowlogick** [comment]
We don't actually follow semver entirely, you can read about the process in CONTRIBUTING.md, and the other related documentation for more details.

**Comment by flobee** [comment]
Thanks @guillep2k  and @techknowlogick 

I'm on the usage/ user side and dont compile the next. So there are difference in the point of view! :-)  OK!

It would make sence to have a: `https://dl.gitea.io/gitea/latest-stable/` then or 

how do you setup your scripts to get the new "stable/release" version? 

Using 'https://dl.gitea.io/gitea/master/' is probably not a release tag version. !?

The thing is: I always need to manuall check the latest, "stable", release to upgrade. But how? (without building it/ using git this way?) 

Hint: unstable -> testing -> stable vs. master / release (always a point of view discussion)
kind regards Florian

**Comment by guillep2k** [comment]
Sounds useful

**Comment by lunny** [comment]
@flobee you could always check semver only in your script and ignore all non-semver version.
