### ISSUE TITLE
using gitea via ssh tunnels fails in some ways

### ISSUE THREAD

**Issue by flobee** [go-gitea/gitea#8134]
- Gitea version (or commit ref):
1.9.3

- Operating system:
linux-amd64

## Description

When open a ssh tunnel to the gitea frontend, eg: address:3000 goes to localhost:3001 (`ssh -L 3001:127.0.0.1:3000 me@someserver` 
most basic things like login and browsing are working.

When start a review then it trys so send the post request to the configured address in the ini file. Which is an unknown address localy (until fixing network forwarding) but its a bug.

**Comment by HenrikBengtsson** [comment]
I can confirm this. It used to work but longer. I think it broke with gitea 1.9.0 +/- 0.0.1.

**Comment by lafriks** [comment]
check your app.ini, what is value for `ROOT_URL`

**Comment by HenrikBengtsson** [comment]
@lafriks, it's
```
ROOT_URL         = https://gitea.behind-vpn.example.org/
```
as it has always been.  To clarify the problem (at least for me), the Gitea instance is accessible only inside the organizations network (not public to the world).  To access it from the outside you need be on the organization's VPN.  An alternative I've used in the past is to use an SSH tunnel (as OP shows) - without the need for the VPN - and pointed my local browser to http://127.0.0.1:3001/.   Going to that localhost URL still works and redirects me to the Gitea web UI.  

However, several things now appear broken, including the ability to log in.  The https://localhost:3001/user/login?redirect_to= just sits there "spinning" forever.  (Interestingly, OP claims login works for them but other things are broken - maybe a different auth method - I use basic built-in accounts).  My best guess, without doing an actual troubleshooting, is that more things are now relying on absolute URL paths that include ROOT_URL, where in the past they used relative URL paths.

**Comment by flobee** [comment]
> @lafriks, it's
> ```
> ROOT_URL         = https://gitea.behind-vpn.example.org/
> ...
> ...
> ```
All of it: i agree! login also fails if i dont ssh to the server where gitea is running (because nginx proxy can solve this in that way)
