### ISSUE TITLE
icons in file comment don't display properly

### ISSUE THREAD

**Issue by StephenKingJJY** [go-gitea/gitea#8136]
- Gitea version (or commit ref):1.10.0+dev-254-g5fcef38f7
- Git version:Not relevant
- Operating system:Not relevant
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL) https://try.gitea.io/jqyy926/sdsdadasd/pulls/1/files/
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

...
There is maybe a css error. Icons represented for editing and deleting could not show properly in file page .

## Screenshots
![image](https://user-images.githubusercontent.com/17059523/64581668-95fa4f80-d3bd-11e9-8108-22aa9ef9eadc.png)

**Comment by guillep2k** [comment]
Strange... this is what I see (as I expect):

![image](https://user-images.githubusercontent.com/18600385/64585230-46d8fe00-d36e-11e9-96dd-677d5055da53.png)

Things that come to my mind:

* Perhaps you page rendered in a character encoding different from UTF-8?
* Perhaps your browser was unable to load some resources? Can you open the developer tools on your browser and check in the network tab if any requests ar failing?

**Comment by StephenKingJJY** [comment]
oh..I forgot to say. You must login in first.

**Comment by StephenKingJJY** [comment]
![image](https://user-images.githubusercontent.com/17059523/64587419-e1b6f400-d3d1-11e9-9582-dfa8ede5b4ab.png)
You can leave your own comment and find that.

**Comment by guillep2k** [comment]
Oh, now I see it! It's a template problem indeed. `.code-view` is overriding octicons font settings when the comment is inside a code review; perhaps only code should be wrapped in `.code-view`, while headers and such should be out of it.
`templates/repo/issue/view_content/comments.tmpl` wraps with `view-code`
`templates/repo/diff/section_unified.tmpl` uses octicons, but font gets overriden.
I'll leave that info here in case someone wants to pick up the issue.
