### ISSUE TITLE
authorized_keys inconsistency when using "admin regenerate keys"

### ISSUE THREAD

**Issue by NiklasRosenstein** [go-gitea/gitea#8138]
- Gitea version (or commit ref): 1.10.0+dev-271-g7eacdcf39
- Git version: 2.22.0
- Operating system: Alpine Linux 3.10.2
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

Adding an SSH key to your account adds an entry in `authorized_keys` with `command="/app/gitea/gitea serv key-X ..." ...`. Using the `gitea admin regenerate keys` command, those entries will be turned into `command="/usr/local/bin/gitea serv key-X ..." ...`.

**Comment by techknowlogick** [comment]
Are you passing the same configuration to the CLI command as you have `gitea web` (the `-c` flag is helpful in this case)?

Are you running gitea inside Docker?

**Comment by NiklasRosenstein** [comment]
Hey @techknowlogick,

I am using Gitea from a Docker container. I do not pass a `-c` flag to `gitea web`.

**Comment by zeripath** [comment]
The inconsistency is because when docker runs Gitea it runs Gitea from the /app/gitea/gitea path directly whereas when you run it from the command line you're running it from the symlink /usr/local/bin/gitea

Gitea just puts whatever is in $0 when it's run. 

It won't have any effects as far as I can tell.

We could change our docker to just put /app/gitea on the path and drop the symlink? Or replace the symlink with a script.

**Comment by lunny** [comment]
I think `gitea` has been the `PATH` in the docker.

**Comment by zeripath** [comment]
Docker runs /app/gitea/gitea directly from the /app/gitea directory:

https://github.com/go-gitea/gitea/blob/273a24f22676b73a648fd2a5467e385ec41e84e2/docker/root/etc/s6/gitea/run#L4-L6

There is no PATH change in Dockerfile.

The final step in Dockerfile is to create a symlink:

https://github.com/go-gitea/gitea/blob/273a24f22676b73a648fd2a5467e385ec41e84e2/Dockerfile#L64

This has two effects:

* When running Gitea from the command line in docker the $0 will not be the same as the docker run Gitea. Hence the /usr vs /app
* The AppWorkDir and hence custom will not be the same when running from docker command line compared with running from the docker. entry point

There are three possible solutions to the first part:

* Run as /usr in the s6 run 
* Add /app to the path and drop the symlink
* Make /usr a script shim which runs /app

The second has the following options:
* Change the docker build to use the LDFLAGS trick as I previously suggested. (Needed for the first two cases)
* Set these in the script.
