### ISSUE TITLE
GitHub mirror mail parsing error

### ISSUE THREAD

**Issue by SuperSandro2000** [go-gitea/gitea#8139]
- Gitea version (or commit ref): 1.10.0+dev-271-g7eacdcf39
- Git version: not applicable
- Operating system: Docker on Ubuntu
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
  - [x] Don't know, I don't have log access
- Log gist:
````
modules/base/tool.go:171:libravatarURL() [E] LibravatarService.FromEmail(email=imgbot[bot]@users.noreply.github.com): error mail: no angle-addr
````

## Description

Mirrored repos from GitHub that contain commits from https://imgbot.net/ yield the above parsing error.

**Comment by techknowlogick** [comment]
@strk should this be filed as an upstream bug?

**Comment by SuperSandro2000** [comment]
bump

**Comment by lunny** [comment]
It should be a upstream library's problem. `ParseAddress` in libravatar references `net/mail`.

**Comment by strk** [comment]
I guess we should catch the exception and continue with no avatar

**Comment by 42wim** [comment]
I think this can be closed ? the current code will show the error but just use the default Avatar when parsing fails.
