### ISSUE TITLE
Can't mirror private GitHub repos with token as password

### ISSUE THREAD

**Issue by SuperSandro2000** [go-gitea/gitea#8140]
- Gitea version (or commit ref): 1.10.0+dev-271-g7eacdcf39
- Git version: not applicable
- Operating system:
- Database (use `[x]`): Docker on Ubuntu
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL), can't provide URL
  - [ ] No
  - [ ] Not relevant
- Log gist:
````
routers/repo/repo.go:323:MigratePost() [E] MigratePost: GET https://api.github.com/repos/SuperSandro2000/xxxxxxxxxxx: 404 Not Found []
````

## Description

I want to mirror a private GitHub Repository and provide my login details via my username and a generated token. According to [this  page](https://github.com/settings/tokens/new) this should work but it yields a 500.

**Comment by SuperSandro2000** [comment]
Hey stale bot. This is not fixed.

**Comment by lunny** [comment]
How about use token as username?

**Comment by SuperSandro2000** [comment]
I think I used the wrong permissions on the token. Would be nice if a note about this could be added to the gui.
