### ISSUE TITLE
Gitea 1.9.3: when trying to create a new file with a directory in the path the filename is incorrect

### ISSUE THREAD

**Issue by ErickStaal** [go-gitea/gitea#8141]
Yesterday I tried to create a new file in one of my gitea 1.9.3 repo's with the following path:

[repo]/kube-controller-01/audit-policy.yaml,

however the file was created initially as:
[repo]/kube-controller-01/aud

It was possible to correct the filename when editing the file, nevertheless, this doesn't work nicely. (I read the documentation and I think I've done everything correctly).

Operating System: Ubuntu 18.04.3 LTS. Installed gitea 1.9.3 from binary download. Database: postgresql (default version Ubuntu 18.04.3 LTS).

**Comment by techknowlogick** [comment]
A few questions:
Have you created a file with this name before?
Are you creating this file in the web editor?
If using web editor, did the file name give you an auto-complete option instead of fully typing it out?

**Comment by ErickStaal** [comment]
Have you created a file with this name before: I encountered the error mainly when I had created a filename before but also have encountered it one time when I hadn't. However in that case I selected the name from an auto-complete option and edited the auto-completed name afterwards.
I indeed created the files in the web editor.
I got auto-complete options when creating the files. 

Thanks for your help.

**Comment by ErickStaal** [comment]
After some more checking it indeed seems to be related to the auto-complete option in the web editor. When I select a filename from the auto-complete dropdown and edit the filename by deleting and immediately reinserting this last letter of the filename everything works fine.
E.g. select filename test.yaml, so filename ends up in filename box, then edit filename in the box to test.yam, and immediately re-edit it to test.yaml, no more wrong filenames after the commit.

**Comment by lunny** [comment]
I think this could be closed. Please feel free to reopen it.
