### ISSUE TITLE
Mssql dump import

### ISSUE THREAD

**Issue by LukeMauldin** [go-gitea/gitea#8142]
- Gitea version (or commit ref): 1.9.3
- Git version: 2.18
- Operating system: Windows
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x ] Not relevant
- Log gist:

## Description
Current using sqlite as gitea database and want to transition to mssql. Ran ‘gitea dump —database mssql’ but encountered errors when trying to import .sql file.
The problem is that is .sql file uses the literal values of “true” and “false” for Boolean columns. Mssql requires the use of 1 and 0 for Boolean columns.

**Comment by techknowlogick** [comment]
Would you be able to file an upstream bug report for this? We use https://github.com/go-xorm/xorm for database operations.

**Comment by LukeMauldin** [comment]
Creates issue https://github.com/go-xorm/xorm/issues/1426
