### ISSUE TITLE
where can I find the db file

### ISSUE THREAD

**Issue by zuhairamahdi** [go-gitea/gitea#8150]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
we have gitea installed and using sqlite. but in the app.ini file it uses relative path instead of absolute:
`PATH     = data/gitea.db`
we are trying to migrate the database to MS SQL.

**Comment by sapk** [comment]
I don't know you full configuration so I can't say exactly where the db file is but you can use `find` command to search a file by name across your filesystem. 
```
find / -name gitea.db
```

**Comment by jolheiser** [comment]
There is an entry on the FAQ that might help as well.  
https://docs.gitea.io/en-us/faq/#where-does-gitea-store-x-file
