### ISSUE TITLE
[API] Provide correct MIME type when getting a raw text file

### ISSUE THREAD

**Issue by danielappelt** [go-gitea/gitea#8152]
- Gitea version (or commit ref): 1.10.0+dev-274-g3fd0eec90
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant

## Description

When fetching a raw text file via the API the content type header does not reflect the file's MIME type.
https://try.gitea.io/api/v1/repos/go-gitea/gitea/raw/public/js/draw.js

`Content-Type: text/plain; charset=utf-8`

Expected result would be:

`Content-Type: application/javascript`

When fetching an image file via the API, the content type seems to be set correctly though:
https://try.gitea.io/api/v1/repos/go-gitea/gitea/raw/public/img/404.png

`Content-Type: image/png`

This is related to issue #7620.

**Comment by silverwind** [comment]
There are security implications when serving scripts with the proper mime type because that allow browser to include then in `<script>` tags. If this is implemented, I suggest making the behaviour optional and default off. GitHub also serves as `text/plain`, FWIW:

```bash
$ curl -v https://raw.githubusercontent.com/go-gitea/gitea/master/web_src/js/jquery.js |& grep -i content-type
< content-type: text/plain; charset=utf-8
< x-content-type-options: nosniff

**Comment by silverwind** [comment]
I think we should keep to generic mime types, e.g. `text/plain` and `application/octet-stream` for binary data. SVG is an acceptable exception because we use that on the gitea UI.

We could expose a user-configurable config section where they can add their mime type mapping to still allow users to serve custom mime types if they so desire.

```ini
[download.mimetype.mapping]
.apk=application/vnd.android.package-archive
.js=application/javascript
```

**Comment by szatyinadam** [comment]
Can anyone check the PR for this issue? #15133
