### ISSUE TITLE
500 when cerete a new PR

### ISSUE THREAD

**Issue by FalconWu2017** [go-gitea/gitea#8158]
- Gitea version (or commit ref):1.9.3
- Git version:
- Operating system:
- Database (use `[x]`):
   - [ ] MySQL
- Log gist:

2019/09/12 10:05:33 ...ters/repo/compare.go:237:PrepareCompareDiff() [E] GetDiffRange: Wait: exit status 128

## Description
When I create a new PR use URL `/compare/master...UserBackdoor` show me 500.    

But for other branch it is work good. Is it about anything with my submit?

**Comment by FalconWu2017** [comment]
It is work today.I don't know why.

**Comment by lunny** [comment]
So let's keep an eye on that for a while.

**Comment by lafriks** [comment]
Let's close this issue currently, reopen if it happens again
