### ISSUE TITLE
only sc create gitea

### ISSUE THREAD

**Issue by ShangJunFengg** [go-gitea/gitea#8159]
![image](https://user-images.githubusercontent.com/28644545/64759770-b582ab00-d56a-11e9-82e7-618fe78db653.png)
![image](https://user-images.githubusercontent.com/28644545/64759787-bc112280-d56a-11e9-9fb0-21c9f82e3444.png)

**Comment by ThinOfSnowDance** [comment]
Why there is no logo?

**Comment by lunny** [comment]
We haven't embedded an application logo in windows binary.
