### ISSUE TITLE
Wrong swagger versioning - always 1.1.1

### ISSUE THREAD

**Issue by gregzawadzki** [go-gitea/gitea#8169]
Firstly i installed 1.8.3 (did not notice docker specified this one) and started testing how to migrate myself via API from bitBucket and add topics. Was getting 404 but had properly used API for adding topics.
I was using documentation from try.gitea server which stated it's version 1.1.1 After a while I found there is API documentation for each installation and my v 1.8 did not have topics yet. Upgraded to 1.9 and it did not have topics yet (still 1.1.1). Then upraded to beta 1.10 and finally in my copy of swagger i had my dreamed of topics. But docs is still 1.1.1

My suggestion is just to update version of docs as it changes. Because different docs revisions have same version number which can be confusing

Trying it out now and it seems (for API) not so painless one would say, but i still think gitea is great from what I see! ❤️ 

- Gitea version (or commit ref): 1.9.2/1.10.x
- Git version: does not apply
- Operating system: does not apply
- Database (use `[x]`):Does not apply
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist: Does not apply

**Comment by 6543** [comment]
reverence: https://github.com/go-gitea/gitea/pull/3572/files#r205924980

**Comment by 6543** [comment]
half working solution:
if you replace `1.1.1` with `{{AppVer}}`

at https://github.com/go-gitea/gitea/blob/master/routers/api/v1/api.go#L12

It works with stable versions but on dev the '+' mess around and you get `1.11.0&#43;dev-517-g1ea447aed ` for example

**Comment by noerw** [comment]
closed by #14654

> It works with stable versions but on dev the '+' mess around and you get 1.11.0&#43;dev-517-g1ea447aed for example

tracked in #14706
