### ISSUE TITLE
Enable Auto theming using Dark Mode CSS

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#8183]
For those who don't know,DarkMode CSS is new feature available in all latest browsers(Blink,Gecko,Webkit based).It themes the website based on System's theme.If the system does have Dark theme,then the site would have dark theme,and if the system has light theme ,then the site would have light theme.(One can also create custom behavioyr for each type).
Ref:
1.   [Introduction by Webkit](https://webkit.org/blog/8840/dark-mode-support-in-webkit/)
2.   [Mozilla Docs](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme)

I want Gitea to have arc-theme(name of dark theme in gitea) when the system is in dark mode and gitea(name of light theme in gitea) when the system is in light mode.

Atleast enable option named "Auto" under themes to enable automatic themes based on dark mode css

**Comment by clarfonthey** [comment]
Want to also add to this that this kind of thing would be very helpful for the official docs, which don't support user-specific themes, and could benefit from this parameter.
