### ISSUE TITLE
a way to convert sqlite to mssql

### ISSUE THREAD

**Issue by zuhairamahdi** [go-gitea/gitea#8186]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

Hi,

we are migrating from sqlite to MSSQL server. though now we are having a difficulties converting the `gitea.db` to the MSSQL formate

**Comment by jaqra** [comment]
Can you check this question & answers?

https://stackoverflow.com/questions/163079/exporting-from-sqlite-to-sql-server

**Comment by lunny** [comment]
@jaqra That's a common subject. I think there are many tools could move data from sqlite to sql server.

**Comment by zuhairamahdi** [comment]
the issue mostly is with creating the tables and keeping the indexing. I worked around this issue by creating a new instance of gitea to create the wanted database structure and then migrate the data to it. even with that there is a lot of manual work to be done for it to work.
