### ISSUE TITLE
repository root path to be in different server

### ISSUE THREAD

**Issue by zuhairamahdi** [go-gitea/gitea#8196]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

Hello,
I'm trying to move the repositories to a different server that we have other than the server where gitea.

we tried to change the `ROOT` in `app.ini` but it is with no use.

can anyone help with this issue?

**Comment by lunny** [comment]
How did you change that option?

**Comment by zuhairamahdi** [comment]
@lunny I tried in multiple ways. first was using the full path as if I was accessing through the file explorer:
`\\<server-ip-here>\c$\gitea\gitea-repositories`
secondly I tried to map the server to a local drive (I called `G:\`). all of these methods gave me an error stating the no file or directory exist.

**Comment by lunny** [comment]
I think only local path is supported there.

**Comment by guillep2k** [comment]
> 
> 
> @lunny I tried in multiple ways. first was using the full path as if I was accessing through the file explorer:
> `\\<server-ip-here>\c$\gitea\gitea-repositories`
> secondly I tried to map the server to a local drive (I called `G:\`). all of these methods gave me an error stating the no file or directory exist.

@zuhairamahdi  In Windows, network drives like `G:\` are specific to each user. For example, if you log in as "Administrator" and create `G:\` from a network path, services and other processes running with different credentials (`SYSTEM`, `NETWORK SERVICE`, `LOCAL SERVICE`, etc.) will not be able to see it. Even so, they won't unless they load the user profile (I don't know if that's the default for services). Finally, network drives can be "permanent" or "temporary"; the latter disappear when you log off.

Anyway, I'm not sure using a network path for repositories is advisable (file locks can be tricky).
