### ISSUE TITLE
Organizations and Microsoft Teams Webhook 404

### ISSUE THREAD

**Issue by troygeiger** [go-gitea/gitea#8202]
- Gitea version (or commit ref): 1.9.3
- Git version: 2.20.1.windows.1
- Operating system: Windows Server 2016
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:

## Description
When trying to add a MS Teams webhook, I receive a 404 error. It would seem that the post url /org/MyOrg/settings/hooks/msteams/new does not exist.
Thanks,

Troy
...

**Comment by lunny** [comment]
have you enable it on your app.ini?

**Comment by troygeiger** [comment]
Hi lunny. I wasn't aware of an option for it in the app.ini and can't seem to find anything on that in the Docs config cheat sheet. What is the name of the option I need to set?
I tested adding a teams webhook to a repo and that work with everything posting to teams. I just cannot seem to add the webhook on the org level without getting the 404 error once clicking the Add Webhook button.

**Comment by JulianSchneider** [comment]
I have the same issue. What is the difference between the global and the org settings? I don't get the global settings to work at all.

**Comment by lunny** [comment]
@JulianSchneider global webhooks haven't been implemented.
