### ISSUE TITLE
Windows 7 Fails to start as a service, Web command works

### ISSUE THREAD

**Issue by PrashamTrivedi** [go-gitea/gitea#821]
- Gitea version (or commit ref): 1.0.0+193-gea8c8cd
- Git version: 2.8.3
- Operating system: Windows 7
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:
 [...gitea/models/repo.go:154 NewRepoContext()] [E] Fail to set git user.name(exec(2:NewRepoContext(set user.name)) failed: exit status 255 stdout:  stderr: error: could not lock config file /home/SYSTEM/.gitconfig: No such file or directory
): error: could not lock config file /home/SYSTEM/.gitconfig: No such file or directory
## Description
Steps
- Got binary from master on 01st Feb. 
- Installed as a windows service.
- Trying to start windows service 
    - Above log is shown, And gitea service is not started.
- Open `services.msc` locate `gitea` service and click properties.
- Copy `Path to executable`
- Paste it in Command line.
- GitTea service is started normally.

This issue also happens in current binary
...

**Comment by lunny** [comment]
No idea about how to fix this.

**Comment by lunny** [comment]
Where the .gitconfig should be on windows? It seems it's a wrong .gitconfig place. @andreynering don't have windows environment.

**Comment by andreynering** [comment]
Should be on `current-user-folder/.gitconfig`

I never saw this error. Maybe you can config git to force the creation on the file?

```
git config --global user.name "..."
git config --global user.email "..."
```

**Comment by andreynering** [comment]
Also, check if git is available on PATH. You should be able to reach it on console.

**Comment by lunny** [comment]
Since we cannot reproduce it, let's move it to v1.2

**Comment by amann** [comment]
I have the same problem. On the command line everything works fine, but as service under Windows Server 2012 R2, I get following entires in the log file:
```
2018/07/16 15:12:04 [I] Log Mode: File(Info)
2018/07/16 15:12:04 [I] XORM Log Mode: File(Info)
2018/07/16 15:12:04 [I] Cache Service Enabled
2018/07/16 15:12:04 [I] Session Service Enabled
2018/07/16 15:12:04 [I] Git Version: 1.9.4.msysgit.0
2018/07/16 15:12:04 [...gitea/models/repo.go:144 NewRepoContext()] [E] Failed to set git 
user.name(exec(2:NewRepoContext(set user.name)) failed: exit status 255(<nil>) 
stdout:  
stderr: error: could not lock config file (null)/(null)/.gitconfig: No such file or directory): 
error: could not lock config file (null)/(null)/.gitconfig: No such file or directory
```
The version of Gitea used is 1.5 (https://dl.gitea.io/gitea/1.5/gitea-1.5-windows-4.0-amd64.exe)

**Comment by lafriks** [comment]
Set data/custom path to needed directory as as service on windows it gets system32 folder as current working directory
