### ISSUE TITLE
UX: When saving a comment edit, there is no indication of progress or error

### ISSUE THREAD

**Issue by abread** [go-gitea/gitea#8210]
- Gitea version (or commit ref): 1.9.2, 1.9.3
- Git version: any
- Operating system: any
- Database (use `[x]`): any
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes https://try.gitea.io/testASDL/asdfsadkfkjs/issues/1#issuecomment-23230
  - [ ] No
  - [ ] Not relevant

## Description

Start editing an issue comment.
When you hit save, the edit interface is closed and the only feedback you have of your edit being saved is the comment text changing (when the fetch that sends the edit succeeds).

This is usually fine, but when the network conditions are a bit slower, one gets frustrated not seeing their edit on the screen, and not seeing any sign of progress. It's easier to see when the edit is big or by manipulating the network latency in Chrome/Chromium's DevTools.

When I noticed this I also checked what happens when the request fails by enabling "Offline mode" in Chrome/Chromium's DevTools before clicking save. It just fails silently.

Fix suggestion: It should show an overlay on top of the editing interface  to indicate that it is being saved and the user should wait, and only close the interface after it's finished saving. If an error occurs, don't close the edit interface and tell the user it failed.

**Comment by abread** [comment]
It's still an issue, stale bot, just not a very important one

**Comment by wxiaoguang** [comment]
Dup of
* https://github.com/go-gitea/gitea/issues/1315
