### ISSUE TITLE
Starting issue text with issue reference "#<number> more text..." does not link issue

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#8214]
- Gitea version (or commit ref): 1.9.3
- Git version: 2.20.1
- Operating system: debian buster
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes [example here](https://try.gitea.io/enckse/example/issues/2)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

If I create an issue and start the text with an issue reference it will instead cause the rendered markdown to produce a header

```
#1 is my open issue
```
^ will not produce the link to issue number 1 but instead create a header entry in the markdown

## Screenshots

![Screenshot_2019-09-17 example](https://user-images.githubusercontent.com/1933941/65072991-f3634300-d95f-11e9-97e6-00eefc5e64ab.png)
![Screenshot_2019-09-17 example(1)](https://user-images.githubusercontent.com/1933941/65072998-f5c59d00-d95f-11e9-8547-e79e14806280.png)

Just to compare to github:

![Screenshot_2019-09-17 go-gitea gitea](https://user-images.githubusercontent.com/1933941/65073086-1db50080-d960-11e9-8e47-d4a870831b6e.png)
![Screenshot_2019-09-17 go-gitea gitea(1)](https://user-images.githubusercontent.com/1933941/65073159-45a46400-d960-11e9-89df-30b2a85c361a.png)

**Comment by guillep2k** [comment]
It is, however, the expected behavior, as `#` is a marker for a title. You can preceed the `#` with a space to "cheat" the marking:
```
#123  <--- It's a title
 #123 <--- It's not (it's a reference)
```

**Comment by lunny** [comment]
This should be an execution order problem. Maybe we should replace the `#123` before we render that as a markdown.

**Comment by enckse** [comment]
Unless this has been fixed as a side-effect and not linked to this issue - it is still open.

**Comment by lunny** [comment]
I think this has been fixed.
