### ISSUE TITLE
Add checks when the binary is moved or other crucial changes

### ISSUE THREAD

**Issue by guillep2k** [go-gitea/gitea#8215]
- Gitea version (or commit ref): 1.9.3

## Description

Ref: #8208

If a user changes `gitea` binary location, the server seems to work initially, but fails later when users attempt to push commits.

We should have some check of where the server was installed the last time and update hooks and `authorized_keys` automatically or at least give the user some warnings.

Perhaps there are other nice checks that can be done at startup.

**Comment by lunny** [comment]
We could randomly chose one repository and generate a new script and compare it with that script on repositories to test if it's the same. We can give a warning information on console or admin UI or notification?

**Comment by bagasme** [comment]
@lunny warnings should be thrown on both console and admin UI.

**Comment by guillep2k** [comment]
I think this check should be done at the instance start. It could share some code with "the doctor".

**Comment by lunny** [comment]
@guillep2k if you have many repository, this operation will spend many time when start. I don't think it's necessary to check that when start. A doctor command should be better. 

As I said, if you really want to check that, we can chose some of repositories randomly to check but not every one.

**Comment by guillep2k** [comment]
Yes, I just wanted to ping the stale-bot, sorry.

**Comment by lunny** [comment]
Aha, @stale !
