### ISSUE TITLE
Task lists should not have default list style

### ISSUE THREAD

**Issue by taai** [go-gitea/gitea#8227]
- Gitea version (or commit ref): 1.9.3

## Description
In the web interface, in a new issue I wrote a task list, but it is being displayed with default unordered list item circles at the beginning of each "task".
The markdown code example:

```
TODO:

- [ ] Do this
- [ ] Do that
```

For example, in Github it is displayed without the default unordered list item circles:

TODO:

- [ ] Do this
- [ ] Do that

## Screenshots

![image](https://user-images.githubusercontent.com/90734/65137408-f6b70700-da11-11e9-88ff-b0cb4169db78.png)

**Comment by davidak** [comment]
This is fixed in `1.13.0+dev-143-g94f60e199`.

![Screenshot from 2020-06-07 07-14-42](https://user-images.githubusercontent.com/91113/83960927-99f4c880-a88e-11ea-8edd-8375e1a37847.png)

https://try.gitea.io/davidak/test/issues/4
