### ISSUE TITLE
Commits counting is not correct

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#8228]
https://github.com/go-gitea/gitea, master has 7991 commits, last commit id is 3c0e6d11267bc9c45e6ff58b8c7a8511f4ccb0ab

![image](https://user-images.githubusercontent.com/81045/65144979-10287500-da4b-11e9-8c67-1f3bfc196622.png)

https://gitea.com/gitea/gitea_mirror is a mirror of above project, master has 7988 commits, last commit id is also 3c0e6d11267bc9c45e6ff58b8c7a8511f4ccb0ab

![image](https://user-images.githubusercontent.com/81045/65144963-06067680-da4b-11e9-9442-ec7ef00f696d.png)

When use git command

![image](https://user-images.githubusercontent.com/81045/65145154-6e555800-da4b-11e9-8d49-527ff8a3caaf.png)

This maybe caused by commits counting cache when the repositories are mirrors, the cache hasn't been cleared.

@lafriks

**Comment by lafriks** [comment]
Could be that there is problem on mirroring

**Comment by lunny** [comment]
Cannot reproduce it in a recent release. Just close it.
