### ISSUE TITLE
Milestones Endpoint (like /issues)

### ISSUE THREAD

**Issue by jag3773** [go-gitea/gitea#8232]
## Description

This is a feature suggestion to add a milestones view for a user like the current `/issues` endpoint.  This could either be built into the `/issues` page or possibly it warrants a whole new `/milestones` top level endpoint.

Functionality would be very similar to the `/issues` endpoint...

* Main view would show a list of all the milestones across all my repos (complete with progress bars like the typical milestones view in a repo shows)
* Side bar filter would allow you to narrow the scope by:
  * Organization
  * User
  * Repo

Similar to #7405, this would be a really helpful way to see timelines across several projects at one time.

**Comment by lunny** [comment]
Then which repositories' milestones should be displayed on that page?

**Comment by jag3773** [comment]
@lunny The idea is that it shows all of them, it's a "roll up view", just like how the `/issues` endpoint shows you issues from all of your repositories.

**Comment by bhalbright** [comment]
Just wanted to note here that I am working on this functionality

**Comment by bhalbright** [comment]
@jag3773 does this model sort of what you had in mind?

![demo](https://user-images.githubusercontent.com/32200834/67826238-e0cd4500-fa99-11e9-8762-36cfc560f3df.gif)

**Comment by jag3773** [comment]
YES!  That looks awesome @bhalbright ! 🎉

**Comment by bhalbright** [comment]
> YES! That looks awesome @bhalbright ! 🎉

Thanks @jag3773! One thing I left off was the edit/close/delete links under each milestone like you see in the milestones page under a specific repository. Is that okay or do you think it is necessary to be able to access those functions from the dashboard view?

**Comment by jag3773** [comment]
I would be OK either way on that one. The only problem I see with adding them is clutter.

Thinking as a project manager, it might be nice to have those links for quick access.  In particular, it would take several steps to close the milestone if those links aren't there–because clicking on one of those links takes you to a page that does not allow you to close the milestone, right?

**Comment by bhalbright** [comment]
> Thinking as a project manager, it might be nice to have those links for quick access. In particular, it would take several steps to close the milestone if those links aren't there–because clicking on one of those links takes you to a page that does not allow you to close the milestone, right?

Thanks, I'll add them back and see how it looks. I was torn on that but like you said if you want to close the milestone you'd have to click into it and then backtrack to the milestone list inside the repository which is a little annoying. I suppose a close function could be added to the milestone page but that would be a different issue.

**Comment by guillep2k** [comment]
I think that closing a milestone is not something that one does several times a day; a direct link to closing them seems like a "delete" button next to the repo name in the repository list.

**Comment by bhalbright** [comment]
I'm lacking on time at the moment with some things going on, so I think for now I'm going to leave off putting the edit/close/delete buttons on this new page. It is debatable anyway, it might just be better if these options were more easily available when you click into the milestone, which would be beyond the scope of this issue

**Comment by bhalbright** [comment]
I've marked the PR as ready to review
