### ISSUE TITLE
Commit changes diff box does not account for code whitespaces/indentation

### ISSUE THREAD

**Issue by cmarshall108** [go-gitea/gitea#8236]
The following screenshot is from gitea:

<img width="1668" alt="Screen Shot 2019-09-18 at 7 33 11 PM" src="https://user-images.githubusercontent.com/22750553/65195148-fd627000-da4b-11e9-94d0-fbfef1509b68.png">

The following screenshot is from github:

<img width="1679" alt="Screen Shot 2019-09-18 at 7 33 02 PM" src="https://user-images.githubusercontent.com/22750553/65195157-0a7f5f00-da4c-11e9-9f53-aa589716a715.png">

Both of the repos are the same, and both of the commits above in the screenshots are the same commits. Gitea does not account for the code whitespaces like Github does, i found this a bit confusing and weird. I'm assuming this is not an intended function.

**Comment by zeripath** [comment]
It's not the whitespace per se it's the word. Github is highlighting the words that change whereas we are highlighting only the minimal change.

I think GitHub is probably doing the correct thing even if it is not highlighting the minimal change

**Comment by wxiaoguang** [comment]
The diff seems correct on try.gitea.io (although it's different from github, but the spaces are correct)

https://try.gitea.io/wxiaoguang/test/commit/2738b8e18402ed2793cb38e85d81f7da4d77d8d8


![image](https://user-images.githubusercontent.com/2114189/177250410-71e74fec-55cb-4170-98b5-ff80f908a1f6.png)

**Comment by wxiaoguang** [comment]
ps: if you can not see whitespaces, make sure you are not affected by this : https://github.com/go-gitea/gitea/issues/19309
