### ISSUE TITLE
exec: "go-bindata": executable file not found in $PATH

### ISSUE THREAD

**Issue by cdslashetc** [go-gitea/gitea#824]
I followed the instructions from the website trying to compile gitea from source on Ubuntu 16.04 (I want PAM module which is not in prebuilt binary nor docker container).

```shell
rm -rf code
mkdir code
export GOPATH=$HOME/code
go get -d -u code.gitea.io/gitea
cd $GOPATH/src/code.gitea.io/gitea
# have also tried v1.0.0
git checkout v1.0.1
# try building without TAGS to rule that out as a problem
unset TAGS
make generate
...
modules/options/options.go:7: running "go-bindata": exec: "go-bindata": executable file not found in $PATH
modules/public/public.go:7: running "go-bindata": exec: "go-bindata": executable file not found in $PATH
modules/templates/templates.go:7: running "go-bindata": exec: "go-bindata": executable file not found in $PATH
Makefile:45: recipe for target 'generate' failed
make: *** [generate] Error 1
```

Originally, I was using syndbg/goenv with go 1.7. I have also tried golang 1.6 from Ubuntu repositories and more up-to-date version from LXC PPA.

go-bindata source appears to be in vendor/github.com/go-macaron/bindata

**Comment by cdslashetc** [comment]
Alright, just needed to:

```shell
export PATH=$PATH:$GOPATH/bin
```

When you install go from the official distribution, there is a message that tells you this, but I'm not sure how you're supposed to know this if you installed by some other mechanism like a distribution package.

```shell
ALL TESTS PASSED

---
Installed Go for linux/amd64 in /home/you/go.
Installed commands in /home/you/go/bin.
*** You need to add /home/you/go/bin to your $PATH. ***
```

**Comment by tboerger** [comment]
Maybe, yes. But we clearly say that setting up the Go environment is out of the scope of the instructions :)
