### ISSUE TITLE
Transfer repository without confirmation of new owner

### ISSUE THREAD

**Issue by Linux4** [go-gitea/gitea#8241]
- Gitea version (or commit ref): 1.10.0+dev-304-g3c0e6d112
- Git version: 2.23.0
- Operating system: Debian 10
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (https://try.gitea.io/root/transfer-ownership-test/)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

Users can transfer ownership of repositories without confirmation of the new repository owner, i think it would be a useful feature if the new owner has to confirm the transfer

**Comment by lunny** [comment]
This is a duplicated issue.
