### ISSUE TITLE
inform participants on UI too / autosubscribe to issue

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#8243]
Would be nice if I creat an issue it automaticly suscribe it.

If you creat a issue on own repos it already works, but if you creat a issue on a repo of an other user it doesnt!

- Git version: 1.10.0 and 1.8.3 tested

**Comment by mismeniet** [comment]
I agree, it is weird to need to subcribe to an issue created by yourself

**Comment by 6543** [comment]
@lunny add to 1.11.X roadmap

**Comment by 6543** [comment]
Closed in fafour of https://github.com/go-gitea/gitea/issues/7512

**Comment by guillep2k** [comment]
This is not the same as #7512. This is for subscribing to issues that one creates, while #7512 is for subscribing to repos when commiting to them. Sorry for my lousy description over there.
