### ISSUE TITLE
documentation is unclear

### ISSUE THREAD

**Issue by homburgs** [go-gitea/gitea#8247]
the online doc is unclear 
in section "Changing the default avatar" you wrote 
"Place the png image at the following path: custom/public/img/avatar\\_default.png"

it's not clear if the last backslash is part of the filename or if the following underscore should be escaped.

**Comment by jolheiser** [comment]
The backslash is attempting to escape the underscore in a markdown document I think. I'll look at adding a PR to fix it, thanks for pointing it out. 😄 

The correct path should be `custom/public/img/avatar_default.png`

Side-note, the current default avatar can be found at https://github.com/go-gitea/gitea/blob/master/public/img/avatar_default.png
