### ISSUE TITLE
Push first commit error

### ISSUE THREAD

**Issue by robincodex** [go-gitea/gitea#8248]
- Gitea version: 1.9.3 linux amd64
- Git version: 2.17.1
- Operating system: CentOS 7.3 64
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description

Yesterday, I upgraded Gitea from v1.6.3 to v1.9.3 and enabled https (v1.6.3 not enabled https).
`git push` and `git pull` is normal after finished,  Today, when I create an empty repo and push first commit, there was an error.
However, when I create a repository and create README by default, so there is no such error, then everything is normal.

## Screenshots

![image](https://user-images.githubusercontent.com/8408783/65305395-aa0c3100-dbb5-11e9-85f5-fb7dce236725.png)

**Comment by RobinCodeX** [comment]
OK, I should be wrong. I think this error happened in news.
I has push "add file" commit, but the news page not display update info.

![image](https://user-images.githubusercontent.com/8408783/65356013-f5f6be80-dc25-11e9-9d29-6e88219ce1f2.png)
![image](https://user-images.githubusercontent.com/8408783/65356023-ff802680-dc25-11e9-9d61-756d2c8b065c.png)

**Comment by lunny** [comment]
Please resync hooks on admin panel

**Comment by RobinCodeX** [comment]
> Please resync hooks on admin panel

I has run `Resynchronize pre-receive, update and post-receive hooks of all repositories.`
but the error still exist.

**Comment by lunny** [comment]
Any logs from your log directory.

**Comment by RobinCodeX** [comment]
Ok, I solved it. 
My `app.ini` file originally came from gogs, I remove LOCAL_ROOT_URL and change DOMAIN to my domain
