### ISSUE TITLE
Migration of a repo ends in 504 Gateway Time-out by nginx/1.14.2

### ISSUE THREAD

**Issue by jayjupdhig** [go-gitea/gitea#8250]
- Gitea version (or commit ref): Most current
- Git version: Most current
- Operating system: Debian 10 "Buster"
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ x] Not relevant
- Log gist:

## Description

Migration of a repo ends in 504 Gateway Time-out by nginx/1.14.2, that's all what i can say...

## Screenshots
![dfwefef](https://user-images.githubusercontent.com/42765391/65335966-bbf5d000-dbc5-11e9-8622-7f12c84eb9cb.jpg)

...and when i try to delete the failed (on migration/mirroring) repo, i get a 500-error. And that will cause that i can't delete the failed repo anymore!!!!!

Screenshot here:

![werter](https://user-images.githubusercontent.com/42765391/65336122-12fba500-dbc6-11e9-8fd3-93b06b886545.jpg)

WTF??

**Comment by martijintro** [comment]
Now it suddenly works - migration with option "mirror" was successful with the same (!!!!!) remote repo!

And: The failed repos was delete automatically.

Gitea seems to have tons of inconsistencies...

**Comment by martijintro** [comment]
How to get the logs to debug what happened and why?

**Comment by martijintro** [comment]
The only one difference between the 1st and the 2nd try is:

1st try: Initial commit on remote repo had comment: "initial commit"
2nd try: Initial commit on remote repo had commen "..."

?????????????????????????????

**Comment by martijintro** [comment]
Maybe there was a background process which caused that problem, i don't really believe that the inital commit's comment on the remote repo makes issues like that. That would be really strange...

**Comment by lunny** [comment]
I have sent a PR #6200 to try to fix this.

**Comment by martijintro** [comment]
ok thx

**Comment by martijintro** [comment]
How can i see on what release version that fix is integrated? Thank you for your feedbacks.

**Comment by 6543** [comment]
last stable release is 1.9.3 as https://github.com/go-gitea/gitea/releases tells you ...
and if I understand lunny right he like to have implemented the "background-migration" in v1.10.x ...

**Comment by guillep2k** [comment]
Issue #6200 was recently moved from milestone 1.10.0 to 1.11.0. It doesn't mean that it couldn't be added to some 1.10.x along the way.

**Comment by 6543** [comment]
:+1: @guillep2k

**Comment by lunny** [comment]
I moved #6200 because I found we could also migrate repos from github even if we have not background migrating implementation. To move forward v1.10, so I move it to v1.10.

**Comment by 6543** [comment]
@martijintro is your question/issue solfed

@lunny you mean 1.11.?

**Comment by martijintro** [comment]
yes
