### ISSUE TITLE
idea: tool to create patches

### ISSUE THREAD

**Issue by ShalokShalom** [go-gitea/gitea#8254]
Phabricator has such a tool, to create patches out of commits. I could use those for further usage, could you add such functionality?

SOLVED: I would also appreciate it as a downloadable file, so in the web view.

Thanks a lot :)

**Comment by lunny** [comment]
Did you mean https://gitea.com/gitea/tea/pulls/45.patch ?

**Comment by ShalokShalom** [comment]
Yeah, something like this. How to achieve this? Lets make some documentation around this?

**Comment by zeripath** [comment]
I believe this has been fixed with #8792 and #8470

**Comment by ShalokShalom** [comment]
This says CREATE patches, not download them. Please reopen, thanks.

**Comment by zeripath** [comment]
I'm confused. What exactly do you mean?

Is it that given a commit to a branch you would like to convert that to a patch file?

Or is it that you would like to select several commits and make a patch file or PR from those?

**Comment by lunny** [comment]
I think it means give two branches/commitids and return a patch file.

**Comment by ShalokShalom** [comment]
Sorry,  I have made the mistake of not reading properly, thanks a lot for your help :)
