### ISSUE TITLE
(Enhancement) Add "Review Required" Identifier on Pull Requests Targeting Protected Branches with Required Approvals

### ISSUE THREAD

**Issue by bagasme** [go-gitea/gitea#8257]
- Gitea version (or commit ref): 1.9.0
- Git version: 2.17.1
- Operating system: Ubuntu 18.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant (I couldn't access because of slow internet connection)
- Log gist:
(not relevant)

## Description
In `Pull Requests` tab of Gitea repository, there isn't `Review Required` text next to who and when the pull request that merge into protected branch with required approvals setting was made. Thus, users don't know whether a PR requires reviews/approvals without having to click into individual PR link.

## Screenshots

This screenshot below is from my `localhost` Gitea instance on my computer. I created `learnPRHomework` repository and set `master` branch protected with 1 required approval. Other user (`bagas`) open a pull request to this protected branch. Note that there isn't `Review Required` text as described in the description above:
![Screenshot_2019-09-22 learnPRHomework](https://user-images.githubusercontent.com/40219486/65384549-d8bd0f80-dd4d-11e9-87e5-429fb8d4caf9.png)

On the other hand, PR on GitHub with similar condition have `Review Required` text (the screenshot is from [linode-docs PRs](https://github.com/linode/docs/pulls):
![Screenshot_2019-09-22 linode docs](https://user-images.githubusercontent.com/40219486/65384577-1326ac80-dd4e-11e9-909d-acc5ccdb8c83.png)

**Comment by 6543** [comment]
I couldn't find the specific pull but its arlready implemented:

![Bildschirmfoto zu 2020-04-26 15-59-36](https://user-images.githubusercontent.com/24977596/80309731-151a8780-87d7-11ea-9cb9-e9165bed38c5.png)
