### ISSUE TITLE
Commits should only close/reopen issues if the issue has the correct branch

### ISSUE THREAD

**Issue by guillep2k** [go-gitea/gitea#8260]
- Gitea version (or commit ref): 1.9.3

## Description

Currently a commit can close or reopen an issue it is referencing, either if `repo.CloseIssuesViaCommitInAnyBranch` is set or when the commit is being pushed to the default branch. However, if `Issue.Ref` is set, it should be used instead of the default branch.

https://github.com/go-gitea/gitea/blob/63ff61615ec6aaa25887f8ce605c9082c106a34b/models/action.go#L603-L607

**Comment by adelowo** [comment]
It is there for backwards compatibility 

See https://github.com/go-gitea/gitea/pull/5992 and https://github.com/go-gitea/gitea/issues/5957

**Comment by guillep2k** [comment]
> 
> 
> It is there for backward compatibility
> 
> See #5992 and #5957

@adelowo Using `CloseIssuesViaCommitInAnyBranch` is alright, but if it's _not set_, an the issue is marked on branch `release` (`Issue.Ref` == `release`), a commit on `dev` should not close the issue.

**Comment by adelowo** [comment]
Ha true

**Comment by guillep2k** [comment]
This was fixed in #8875
