### ISSUE TITLE
The date of last sync (if use mirrors) does not match with "x days ago" on front page

### ISSUE THREAD

**Issue by jayjupdhig** [go-gitea/gitea#8264]
- Gitea version (or commit ref): Current
- Git version: Current
- Operating system: Debian 9 "Stretch"
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ x] Not relevant
- Log gist:

## Description

The date of last sync (if use mirrors) does not match: I get another value if i click on the project mirror settings button "Synchronize now". After clicking there, i will show me the current date/time (minus a few secs) for the last sync.

And that time/date value, on the top of "Synchonize now" button in project's mirror settings section, does not fit to the value i get on the from page, someting like "x days ago"

A few secs ago is not x days ago, hope you understand what i mean.

More here about the problem: https://github.com/go-gitea/gitea/issues/8252#issuecomment-534140138 

## Screenshots

No screenshots yet, it think it is not necessary to post some screenshots. If you need some, don't hesitate to ask. Thx.

**Comment by martijintro** [comment]
No anwser, or is it a feature instead of a bug? ;-)

**Comment by 6543** [comment]
I think you mix up <last change> with <last sync> ?

**Comment by martijintro** [comment]
maybe the `"x days ago" on front page` is the repo creation date and not the date of the last sync...(?)

**Comment by martijintro** [comment]
`I think you mix up last change with last sync ?`

That should be be the same if i only commit/push to the remote repo.

**Comment by 6543** [comment]
at the front a mirror is like a normal repo with an extra icon ...
-> Updated x  use the timestamp of the commit

**Comment by martijintro** [comment]
ok thx
