### ISSUE TITLE
Closed Issues show wrong user information

### ISSUE THREAD

**Issue by guillep2k** [go-gitea/gitea#8266]
- Gitea version (or commit ref): 1.9.3

## Description

The list of closed issues shows the name of the creator of the issue as the closer, even if the closer was different user.

![image](https://user-images.githubusercontent.com/18600385/65468934-054f5500-de3c-11e9-9597-6ffe14e40d69.png)

The picture above should say: `"opened 3 days ago by cga..., closed 3 days ago by sdg...."`

This is the view of the issue:

![image](https://user-images.githubusercontent.com/18600385/65469159-b35aff00-de3c-11e9-926b-12dc2b4ac53d.png)

**Comment by guillep2k** [comment]
We're not saving information about the user that closed the issue. Perhaps the message should be something like:

> opened 3 days ago by **poster**, closed 2 days ago

**Comment by RobH123** [comment]
Would be so much more helpful if the closer was shown as well without having to open the issue to see that. (And BTW, wouldn't it be nice if the issue number in the red box was also clickable like the issue title.)

**Comment by lunny** [comment]
@guillep2k could you confirm that if this has been resolved?

**Comment by guillep2k** [comment]
> 
> 
> @guillep2k could you confirm that if this has been resolved?

Sadly, no (2677d071f911fb91f382acfedaedc251bd807f70).

URL:
```
http://mytestsite:3000/test-org/test-repo/issues?q=&type=all&sort=&state=closed&labels=&milestone=0&assignee=0
```

The _issue list_ shows the wrong info. If I navigate into the issue, I can see the correct user that closed the issue as a comment. The problem is that the issue list (`/:userid/:repoid/issues`) does't have the closer info at hand in the `issue` table.

**Comment by lunny** [comment]
Maybe we can see more information via #9822 but not show too much information on list. If that, we can simply change the information like what @guillep2k said.
