### ISSUE TITLE
API: milestone

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#8268]
Can still create/get milestones when issuetraker is external

Gitea version: current

**Comment by lunny** [comment]
Pullrequests still will need milestones.

**Comment by 6543** [comment]
O right, i have the cas of an mirror with external issue traker

**Comment by 6543** [comment]
Is it worth catching this constelation, beside it only afects API and not UI

**Comment by 6543** [comment]
-> testing GitNex functions ...
Perhaps catch it there?

**Comment by 6543** [comment]
-> catch it on client side ...
