### ISSUE TITLE
Gitea cannot analysis html in markdown 

### ISSUE THREAD

**Issue by yzqdev** [go-gitea/gitea#8269]
- Gitea version (or commit ref):
- Git version: 2.12.0
- Operating system: windows 10 1903
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description
it cannot analysis html in markdown ,but github and gitee could. 
...

## Screenshots
below is gitea
![image](https://user-images.githubusercontent.com/20037151/65477827-1b035f80-deba-11e9-8ee9-c1038c52cff1.png)
below is github
![image](https://user-images.githubusercontent.com/20037151/65477939-84836e00-deba-11e9-9f1e-3a726b678d0b.png)

**Comment by bagasme** [comment]
What is your GitHub repo for this issue?

**Comment by yzqdev** [comment]
https://gitea.com/yzqdev/mark2html/src/branch/master/README.md
![image](https://user-images.githubusercontent.com/20037151/65506094-5ffcb580-defd-11e9-9053-38403f8cb96d.png)

**Comment by yzqdev** [comment]
> What is your GitHub repo for this issue?

It renders markdown unlike github. (rendering html in markdown)

**Comment by zapashcanon** [comment]
Also, it would be great to patch the HTML so that e.g. relative links/images render well (as it's done in pure MarkDown).

E.g. [here](https://git.zapashcanon.fr/zapashcanon/www.ocamlpro.com/src/branch/master/src/content/index.md) ; images are not rendered because HTML is not handled correctly (the link should be modified so that it points to the raw image).

**Comment by zeripath** [comment]
Please see: https://try.gitea.io/arandomer/www.ocamlpro.com/src/branch/master/src/content/index.md

**Comment by zeripath** [comment]
If that is all this issue is about I think we can finally close this as fixed.

**Comment by zapashcanon** [comment]
Great, thanks ! :)
