### ISSUE TITLE
Branch name conflict dev VERSUS dev/XXX

### ISSUE THREAD

**Issue by ejouvin** [go-gitea/gitea#8271]
- Gitea version (or commit ref): 1.9.3
- Git version: 2.20.1
- Operating system:
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No (did not try, because waiting for the password recovery)
  - [ ] Not relevant
- Log gist:

## Description
Fresh repository creation.
I created the branch dev and wanted to create a branch like dev/print
But there is an error about a name conflict with branch dev

...

## Screenshots
![image](https://user-images.githubusercontent.com/8817923/65493014-497d3c80-deb2-11e9-94a1-a8d61590d754.png)

**Comment by lafriks** [comment]
That correct error. By git rules you can not create new branch that has same start as already existing one:
Try running locally:
```sh
# git checkout -b master/test
fatal: cannot lock ref 'refs/heads/master/test': 'refs/heads/master' exists; cannot create 'refs/heads/master/test'
```

**Comment by ejouvin** [comment]
Ok sorry about that.
I really believed I was able to do it before.

My fault.
