### ISSUE TITLE
Allow Repo Administrators to (Force) Merge "Review Required" PRs

### ISSUE THREAD

**Issue by bagasme** [go-gitea/gitea#8272]
- Gitea version (or commit ref): 1.9.0
- Git version: 2.17.1
- Operating system: Ubuntu 18.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:
(not relevant)

## Description
In cases whether there is an open PR against protected branch that requires approved reviews from whitelisted reviewers, and all reviewers aren't available in time, repo administrators can still merge that PR. An example when this feature is useful is when a PR contains important security fixes.

## Screenshots

This screenshot is from my `localhost` Gitea instance on a computer. A user (which is repo administrator) open a PR against protected branch (`master`). Required approvals are 1. However, despite that he is an admin, he can't (force) merge his PR without approvals. That is, there isn't `Merge Pull Request` button.
![image](https://user-images.githubusercontent.com/40219486/65496477-bf010100-dee2-11e9-8a40-6de883301b2c.png)
On the other hand, on GitHub, there is `Merge Pull Request` button which allows admins to merge
PR without review approvals (that is, force merging).
![image](https://user-images.githubusercontent.com/40219486/65496762-42225700-dee3-11e9-909a-2c640bf3923c.png)

**Comment by lunny** [comment]
I think maybe I have resolved this on #7481 ?

**Comment by bagasme** [comment]
> I think maybe I have resolved this on #7481 ?

@lunny Yes this issue is duplicate. Please close.
