### ISSUE TITLE
Cross moved a little

### ISSUE THREAD

**Issue by JWo1F** [go-gitea/gitea#8274]
- Gitea version (or commit ref): 1.10.0+dev-315-g63ff61615
- Git version: 1.13
- Operating system: ArchLinux x64
- Database:
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes
  - [ ] No
  - [ ] Not relevant
- Log gist:
Not relevant
## Description
Error in layout. Cross moved a little in PR page (Request Changes).

## Screenshots
![image](https://user-images.githubusercontent.com/1540715/65497981-c8c73c00-dec3-11e9-99c6-bc8e531b2047.png)

**Comment by lunny** [comment]
I think this has been resolved.
