### ISSUE TITLE
API: GET/SET/DEL attachment on comment

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#8277]
cant find attachment options in swagger.
exist there an api to get/set/del attachements to issues/pull request comments

**Comment by 6543** [comment]
Needed for [GitNex](https://gitea.com/mmarif/GitNex/issues/56)

**Comment by bobemoe** [comment]
It is being discussed: #3690

**Comment by 6543** [comment]
Ok i close this in fafour of #3690
