### ISSUE TITLE
Creating new issue results in 500 server error

### ISSUE THREAD

**Issue by jscottelblein** [go-gitea/gitea#8279]
- Gitea version (or commit ref): 1.10.0+dev-325-gb19db40ea (running dockerized: gitea/gitea)
- Git version: 2.22.0
- Operating system: linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [X] SQLite

## Description

I just created a new repo, then went to the issues area to record a note to myself, submitted it, and it just takes me to an error 500. If you need any more specific info, just let me know.

## Screenshots

![capture](https://user-images.githubusercontent.com/1524526/65565075-7b26ef80-df14-11e9-882a-d0344674694d.gif)

**Comment by guillep2k** [comment]
Can you test if the problem arises when there are references to other issues? Can you try with a simpler message?

**Comment by STaRDoGG** [comment]
Working great again! Super quick fix, you guys rock. :D
