### ISSUE TITLE
v1.9.3 breaks with go1.13

### ISSUE THREAD

**Issue by carnott-snap** [go-gitea/gitea#8280]
- Gitea version (or commit ref): `v1.9.3`

## Description
Several dependent modules (`code.gitea.io/sdk/gitea`, `github.com/goreleaser/goreleaser`, etc.) are depending on pre-release versions of `v1.10.0`, due to issues with the new go1.13 toolchain. This is unfortunate and could cause breaking changes during the release cycle of `v1.10.0`. Could you release a backport to the `v1.9.x` line to fix these issues, or provide some other means of remediation for this issue?

## Screenshots
```
[user@localhost ~]$ go version
go version go1.13 linux/amd64
[user@localhost ~]$ go get code.gitea.io/gitea
go: finding code.gitea.io/gitea v1.9.3
go: downloading code.gitea.io/gitea v1.9.3
go: extracting code.gitea.io/gitea v1.9.3
go get: code.gitea.io/gitea@v1.9.3 requires
        github.com/go-macaron/cors@v0.0.0-20190309005821-6fd6a9bfe14e9: invalid pseudo-version: revision is longer than canonical (6fd6a9bfe14e)
[user@localhost ~]$ go get code.gitea.io/gitea@master
go: finding code.gitea.io master
go: finding code.gitea.io/gitea master
[user@localhost ~]$ cat go.mod 
module test

go 1.13

require code.gitea.io/gitea v1.10.0-dev.0.20190924182911-b19db40eab5d // indirect
```

**Comment by ArchangeGabriel** [comment]
Dupe: https://github.com/go-gitea/gitea/issues/8126
