### ISSUE TITLE
API: make acces token optionaly [specify]

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#8287]
Version: https://github.com/go-gitea/gitea/commit/c6fb7fe27c16c4e43d4d8dbe4d2ff4b3c4c52a29

Is related to https://gitea.com/mmarif/GitNex/issues/57 (make login optional)

**Comment by davidsvantesson** [comment]
You are aware of REQUIRE_SIGNIN_VIEW?

There are a number of APIs that can be accessed without login. For example, you can try these:
curl -X GET "https://try.gitea.io/api/v1/repos/search?q=test" -H "accept: application/json"
curl -X GET "https://try.gitea.io/api/v1/repos/merle_noir/TestName" -H "accept: application/json"
