### ISSUE TITLE
Incorrectly displayed block with source code in *.md files

### ISSUE THREAD

**Issue by egrekov** [go-gitea/gitea#8291]
## Description
Incorrectly displayed block with source code in *.md files. For the correct display of the block with the source code, you need to add an additional line feed.

* [readme.md](https://github.com/egrekov/test)  file in github (correct view)
* [readme.md](https://try.gitea.io/Testssss/test-markdown/src/commit/ce53cdb8338e1176d1071819562623a6c1535483/readme.md) file in try.gitea.io **without** additional line feed (not correct view)
* [readme.md](https://try.gitea.io/Testssss/test-markdown/src/branch/master/readme.md) file in try.gitea.io **with** additional line feed (correct view)

**Comment by bagasme** [comment]
Please specify Gitea version this issue has affected, together with your setup. When you opened this issue, you should fill the questionnaire template that automatically created.

**Comment by egrekov** [comment]
@bagasme, I apologize, I will correct
- Gitea version (or commit ref):
`Gitea Version: 1.10.0+dev-326-gc05b89a5a`
- Operating system:
`Docker image gitea/gitea:latest`
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [X] SQLite
- Can you reproduce the bug at https://:
  - [X] Yes [url to try.gitea.io](https://try.gitea.io/borin/test/src/commit/20d153d1441de922b3ebb104d963f1e086c923df/README.md)
  - [ ] No
  - [ ] Not relevant

**Comment by lafriks** [comment]
Depends on russross/blackfriday#536

**Comment by delvh** [comment]
I have no idea what this issue is talking about at this point in time, hence closing it.
If it is still present, please update your example links, and reopen it.
