### ISSUE TITLE
Labels sorting by colour 

### ISSUE THREAD

**Issue by marcsiq** [go-gitea/gitea#8293]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

... 
We are using same colours for same "type" of labels so it would be great to be able to sort the labels by colour. :)

**Comment by bagasme** [comment]
@Marcsiq2 Any further explanation?

**Comment by bobemoe** [comment]
Interesting idea, there is talk about attaching a weight to labels for prioritizing the issues here https://github.com/go-gitea/gitea/issues/2616 may be slightly related?

**Comment by bobemoe** [comment]
To do this I actually prefixed my labels with kind/ or type/ (like they do here) etc as they are sorted alphabetically, however that makes selecting them with the keyboard from a long list almost imposable.

**Comment by wxiaoguang** [comment]
Color is not sortable. 

Now Gitea supports scoped labels, and in the future the prioritized labels would also help.
