### ISSUE TITLE
PDF files not showing in renderer

### ISSUE THREAD

**Issue by mehalter** [go-gitea/gitea#8294]
- Gitea version (or commit ref): 1.9.3
- Git version: 2.16.5
- Operating system: CentOS
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

PDF Files are not showing in the renderer, the `/vendor/plugins/pdfjs/web/viewer.html?file=...pdf` request has `X-Frame-Options: DENY` header. I can follow the link and serve the file, but the header option doesn't allow it to be in the `iframe`. When I set the headers in my apache config, it doesn't apply to the `/vendor/plugins/pdfjs/web/viewer.html?file=....pdf` requests.

## Screenshots

![image](https://user-images.githubusercontent.com/1591837/65713816-fea52580-e067-11e9-840e-67a650ec7a50.png)

**Comment by HarvsG** [comment]
As I found in #8299 some external rendering was broken by https://github.com/go-gitea/gitea/commit/867f46f78e5777d7bafe83cda3244c1001ce3e60, not sure if it would have affected PDF files, but may be worth checking.

**Comment by mehalter** [comment]
Yeah the generated HTML looks good and seems ok. I'm trying to figure out why the headers are setting X-Frame-Options to DENY instead of SAMEORIGIN only for the PDF.js links. Do you have any idea why this would be different than the headers of the rest of the site?

**Comment by HarvsG** [comment]
@mehalter Since I'm not having any issues on my side I wonder if it could be your browser? Have you tried from different browsers/clients? Some browsers/browser extensions make changes that interfere with iframes for security reasons.

**Comment by mehalter** [comment]
Yeah I had that thought too, and it is broken on all browsers/clients that I have tried on several devices.

**Comment by mehalter** [comment]
Is there anything in the codebase that would have the pdf.js link be assigned different headers? the `/vendor/plugins/pdfjs/web/viewer.html?file=....pdf` link? All my other renderer file types work just fine. But the pdfjs links in particular are getting assigned this header.

**Comment by lunny** [comment]
Which browser are you using?

**Comment by mehalter** [comment]
I have tried with Firefox and qutebrowser on linux, and firefox and chrome on android.

**Comment by guillep2k** [comment]
@mehalter #8300 has some code changes about rendering external files. Could that fix your problem? You can checkout that PR by using:

```
pull=8300
git fetch upstream "pull/$pull/head:pull-$pull"
git checkout "pull-$pull"
```

But you need to check in a **testing environment**; otherwise it might wreck havoc in your installation (there was a bug in migrations that deleted the attachments from the file system and I don't know if the fix has been merged into this particular PR yet).

**Comment by guillep2k** [comment]
>  external files. Could that fix your problem? You can checkout that PR by using:

Or perhaps you could attempt applying that commit individually? It would be safer and you'd skip migrations, etc.
