### ISSUE TITLE
Gitea -> Drone connection

### ISSUE THREAD

**Issue by nihadtz** [go-gitea/gitea#8296]
Hello,

We have strange issue using Drone with Gitea.

IF we do commits, create branch, pull request or anything vi UI in Gitea it will trigger drone to do something, as you can see on screenshoot.

IF we push anything from our local repositories to Gitea it doesn't trigger Drone at all. No request in log at all, as you can see on screenshoot.

We have tried every option in Webhooks for Trigger On every time same issue, and Drone in docker container.

We have update to latest version of Gitea and drone is fresh also

- Gitea version (or commit ref): 1.9.3
- Git version: 2.17.0 
- Operating system: Ubuntu 18.04

## Screenshots

![gitea-drone](https://user-images.githubusercontent.com/46897537/65751650-76785c00-e10b-11e9-8b6f-e5be86ec31bb.png)

**Comment by nihadtz** [comment]
Issue is when we are pushing commits via SSH, doing it via HTTP does everything ok

**Comment by lunny** [comment]
Have you take a look at webhook history?

**Comment by nihadtz** [comment]
Nothing in webhook history, but i think i have found solution. Built in SSH server needs to be used to achieve usage via SSH

**Comment by sapk** [comment]
I think that you may need to regenerate git hooks to use with openssh. 
This is maybe related to [Git error after updating to a new version of Gitea](https://docs.gitea.io/en-us/install-from-binary/#git-error-after-updating-to-a-new-version-of-gitea)
But I would suggest you to stay with the built-in ssh server.

**Comment by nihadtz** [comment]
I have solved this by turning on built in SSH server

Works perfect now
