### ISSUE TITLE
[Bug] [Branch View] Wrong link for cross PR

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#8305]
Gitea Version: 1.10.0+dev-289-g8b54b58bc (gitea.com)

How to reproduce:

1. forc a project
2. make a branch and push some commits to it
3. make a PR to the original project from this branch
-> 4. go to branch view at the forge repo, you can see the PR Nubers but you cant open them corectly

Tested Repo: https://gitea.com/6543/GitNex/branches

-> gitea missed that the pull request is on a other repo than the own branch
(instead of https://gitea.com/mmarif/GitNex/pulls/70 you get to https://gitea.com/6543/GitNex/pulls/70)

**Comment by lunny** [comment]
Is this still a problem?

**Comment by guillep2k** [comment]
If I understand this correctly, it's fixed by #8670

**Comment by 6543** [comment]
I'll check ..

**Comment by 6543** [comment]
@lunny YES
@guillep2k NO

this is more a frontend issue

**Comment by 6543** [comment]
Stil here
