### ISSUE TITLE
How to set Custom Path

### ISSUE THREAD

**Issue by laoshaw** [go-gitea/gitea#831]
- Gitea version (or commit ref):6aacf4d
- Git version:2.7.4
- Operating system:ubuntu 16.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

cd /tmp
gitea web
  Custom path: /path/where/gitea/is/installed/custom
Even though I run gitea from /tmp, it still reports its "Custom path" is the same as where "gitea" is installed, is it possible to set the "Custom path" to where I run gitea instead of where it is installed, i.e. /tmp/custom in this case.

**Comment by lunny** [comment]
```
./gitea help web
NAME:
   gitea web - Start Gitea web server

USAGE:
   gitea web [command options] [arguments...]

DESCRIPTION:
   Gitea web server is the only thing you need to run,
and it takes care of all the other things for you

OPTIONS:
   --port value, -p value    Temporary port number to prevent conflict (default: "3000")
   --config value, -c value  Custom configuration file path (default: "custom/conf/app.ini")
   --pid value, -P value     Custom pid file path (default: "/var/run/gitea.pid")
```

**Comment by laoshaw** [comment]
Thanks. I read that and tried that already, "mkdir -p /tmp/xyz; cd /tmp/xyz; gitea web --config /tmp/xyz/custom/conf/app.in" it still points to /gitea/install/path/custom/conf/app.in, no way to change that.

**Comment by tboerger** [comment]
The custom path can be configured with the environment variable `GITEA_CUSTOM`, so this is not a bug, it's more a documentation issue.

**Comment by laoshaw** [comment]
Looked into the code it seems a better env is GITEA_WORK_DIR:

```
GITEA_WORK_DIR=`pwd` gitea web
```

**Comment by lunny** [comment]
maybe we should send a PR to add a document.
