### ISSUE TITLE
Cannot update custom avatar.

### ISSUE THREAD

**Issue by tosone** [go-gitea/gitea#8310]
- Gitea version (or commit ref): 1.10.0+dev-334-gc6fb7fe27 and 1.9.3
- Git version: 1.10.0+dev-334-gc6fb7fe27 and 1.9.3
- Operating system: linux
- Database (use `[x]`):
  - [x] PostgreSQL
  - [x] MySQL
  - [x] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

After I choose an image and update it as a new customer avatar.

Response: Bad Request: no CSRF token present.

**Comment by lunny** [comment]
This has been reported previously.

**Comment by lunny** [comment]
duplicated with #7955
