### ISSUE TITLE
Sometime jump to static pic when login 

### ISSUE THREAD

**Issue by unsciorg** [go-gitea/gitea#8311]
- Gitea version (or commit ref): 1.12.9
- Git version: 2.2.1
- Operating system: Centos 7
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist: None 

## Description

Sometimes it jumps to a static pic (such as the green cup or a js file ) when I login , I have to type homepage url  to jump to homepage.

I click the login button, but it jump to https://mydomain.com/img/gitea-lg.png

## Screenshots
![image](https://user-images.githubusercontent.com/15797571/65843077-4e366a80-e362-11e9-8df7-0d771b522a1d.png)

**Comment by lunny** [comment]
This is still a bug because static files will follow session.

**Comment by lunny** [comment]
I think this has been resolved.
