### ISSUE TITLE
API: handle reactions to comments

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#8313]
```
GET     /repos/{owner}/{repo}/issues/comments/{id}/reactions
PUT     /repos/{owner}/{repo}/issues/comments/{id}/reactions
DELETE  /repos/{owner}/{repo}/issues/comments/{id}/reactions
```

**Comment by 6543** [comment]
GitHub docu https://developer.github.com/v3/issues/comments/#reactions-summary

**Comment by 6543** [comment]
@mmarif4u what is earyer to process:

```json
[
  {
    "id": 0,
    "username": "6543",
    "reaction": "heart",
  },
  {
    "id": 4,
    "username": "6543",
    "reaction": "laugh",
  },
  {
    "id": 8,
    "username": "mmarif",
    "reaction": "laugh",
  },
  {
    "id": 10,
    "username": "user1",
    "reaction": "confused",
  }
]
```
or
```json
[
  {
    "reaction": "heart",
    "users": [ "6543" ]
  },
  {
    "reaction": "laugh",
    "users": [ "6543", "mmarif" ]
  },
  {
    "reaction": "confused",
    "users": [ "user1" ]
  }
]
```

**Comment by guillep2k** [comment]
```
[
  {
    "reaction": "heart",
    "users": [ "6543" ]
  },
  {
    "reaction": "laugh",
    "users": [ "6543", "mmarif" ]
  },
  {
    "reaction": "confused",
    "users": [ "user1" ]
  }
]
```
Is better: more concise, no ids exposed.

**Comment by mmarif4u** [comment]
I agree with @guillep2k, that is the right way to do it. :+1:

**Comment by 6543** [comment]
Ok I'll work on this tomorow

**Comment by 6543** [comment]
PUT / DELETE use
```json
{
    "reaction": "heart",
    "users": [ "6543" ]
 }
```
I could make it eaven mor simpler by just allow a string to be send or
```json
"reaction": "heart"
```
but i leave it open so admins have an API to send ractions for other users too

**Comment by zeripath** [comment]
Don't forget Sudo allows an admin to act like any other user - so you should only add that if you're going to allow the admin to set multiple user's reactions.

**Comment by lafriks** [comment]
imho we should follow GitHub API compatibility:
https://developer.github.com/v3/reactions/

Link above is just reaction counts by type in issue details API

**Comment by 6543** [comment]
@lafriks @techknowlogick one downside:

consider a issue with 15 comments -> each had ~ 10 reactions
-> api return user information in the worst case  150 times (dedundancy)
 and if there all other users we still load a huge amount of user information wich isnt used ...
and if an app like to load more about a user it still kan get it by its name

**Comment by 6543** [comment]
# proposal2
`GET  /repos/{owner}/{repo}/issues/comments/{id}/reactions` **return:**

```json
reaction: "heart"
```

`PUT/DELETE  /repos/{owner}/{repo}/issues/comments/{id}/reactions` **consume:**

```json
a
```

**Comment by lafriks** [comment]
I don't agree as most probably you will still want to have user avatar url, user url, we do return this format in all other api, so I would not like this to be different. Reaction summary (counts by type) you will already have them in issue/pr/comment API. These are details so you really need to request them rarely - when you really want to know exact details

**Comment by 6543** [comment]
@lafriks 
`GET /repos/{owner}/{repo}/issues/{index}` as no reaction info
`GET /repos/{owner}/{repo}/pulls/{index}` also

a `GET /repos/{owner}/{repo}/issues/comments/{id}` do NOT exist!
and `GET /repos/{owner}/{repo}/issues/comments` has no reaction info

this is same at `GET /repos/{owner}/{repo}/issues/{index}/comments`

**Comment by 6543** [comment]
so add a "reactions_light" or so type wich has smal foodprint to :arrow_up: API endpoints?

and make  `/repos/{owner}/{repo}/issues/comments/{id}/reactions` like github?

**Comment by 6543** [comment]
@lafriks github has a similar aproach: https://developer.github.com/v3/issues/#reactions-summary

**Comment by 6543** [comment]
one thing wich is not goog at this reaction_summary_api: we can no add custom reactions that easely!

**Comment by 6543** [comment]
@lafriks I'm thinking of #8811

**Comment by 6543** [comment]
# Proposal.3

## reaction endpoint

`GET  /repos/{owner}/{repo}/issues/comments/{id}/reactions`
**consume:** `null`
 **return:**
```json
[
  {
    "id": 1,
    "user": {
      "login": "octocat",
      "id": 1,
      "avatar_url": "https://github.com/images/error/octocat_happy.gif",
      "url": "https://api.github.com/users/octocat",
      ..... (gitea_api_user) 
      "type": "User",
      "site_admin": false
    },
    "content": "heart",
    "created_at": "2016-05-20T20:09:31Z"
  }
]
```

`PUT/DELETE  /repos/{owner}/{repo}/issues/comments/{id}/reactions`
**consume:**
```json
content: "heart"
```
 **return:**
http code

## Extend issue/pr/comment API

add a reaction field: (api.reaction_summary)
```json
"reactions": [
  {
    "reaction": "heart",
    "users": [ "6543" ],
    "count": 1
  },
  {
    "reaction": "rocket",
    "users": [ "octa" ],
    "count": 1
  }
],
"reactions_count": 2,
"reactions_url": "/repos/{owner}/{repo}/<issues/comments/pull ...>/{id}/reactions"
```

**Comment by lafriks** [comment]
### Extend issue/pr/comment API

Github for this is better imho

```json
"reactions": {
  "total_count": 5,
  "+1": 3,
  "-1": 1,
  "laugh": 0,
  "confused": 0,
  "heart": 1,
  "hooray": 0,
  "url": "{owner}/{repo}/issues/comments/{id}/reactions"
}
```

**Comment by 6543** [comment]
@lafriks what if i like to add "rocket" :rocket:?
this is no array types are hardcoded :(

**Comment by 6543** [comment]
I'll do it te github way, but dont blamevme for limitating api afterwards ...

**Comment by 6543** [comment]
## Gitea Reactions Summary

```json
"reaction_summary": [
  {
    "reaction": "heart",
    "users": [ "6543" ],
    "count": 1
  },
  {
    "reaction": "rocket",
    "users": [ "octa" ],
    "count": 1
  }
],
"reactions_counter": 2,
```
