### ISSUE TITLE
Feature Request: don't limit commit-graph to 100 commits

### ISSUE THREAD

**Issue by Misterke** [go-gitea/gitea#832]
Pull request commithgraph / timeline #428 adds a very useful graphical representation of the relationship between commits (and basically branches), but the current implementation is limited to the most recent 100 commits.   Ideally, when scrolling down, the next commits should be added to the graph.   Alternatively, paging could also be used (although the resulting graph doesn't give as good of an overview). 

While at it, allowing to specify the ordering of the commits would be useful (switching between --date-order and --topo-order).

**Comment by lunny** [comment]
@kjellkvinge

**Comment by kjellkvinge** [comment]
I will look into this. There is some points to consider:

1. performance
2. how the js-lib will handle redraw
3. User experience
4. Complexity

I think my first approach would be something like fossil timeline: 

http://fossil-scm.org/index.html/timeline

you can paginate by clicking "older", and user can set how many commits you want.

**Comment by Misterke** [comment]
@kjellkvinge, I love the Fossil timeline visualization.  The graphics look so much more "orderly" than the current commitgraph in gitea. As you pointed to it, I wonder whether getting that type of visualization would be easy/possible/difficult/out-of-the-question?

**Comment by bkcsoft** [comment]
Pagination is required. But we can scroll-load the next page...

**Comment by Pofilo** [comment]
I completely agree with @bkcsoft.
However, if it is to hard to implement, why not adding the 100 variable as a parameter in the configuration ?
