### ISSUE TITLE
Closed issues sends an email from author - not closer

### ISSUE THREAD

**Issue by worthy7** [go-gitea/gitea#8320]
Hi there, quite simply when an issue is closed by ANYONE, an email is sent to all those concerned but the "from" is from the original issue creator - not the person who closed this issue.

This makes it look at first glance as if the author closed the issue! In work, this makes it look like my colleges are closing issues when in reality it's me or another administrator. Until one opens the website and then they can see who really closed it.

**Comment by lunny** [comment]
Could you give more detail about your gitea version and OS?

**Comment by worthy7** [comment]
© Gitea Version: 1.8.2  API Website Go1.12.5
I believe we're running on Ubuntu

**Comment by guillep2k** [comment]
In the latest master (1.10.0+dev-363-ge2a638864), what I'm getting is:

![image](https://user-images.githubusercontent.com/18600385/65921293-38ec2b00-e3b8-11e9-82ba-cf5300a91acf.png)

* The user in the `From:` field is the site admin; neither the closer or the opener of the issue.
* The mail subject is the current title of the issue.
* The mail body is the text of the first comment of it (i.e. `issue.content`).

All of this is very confusing. Nowhere in the mail says that it's an issue being closed, or who did close it.

**Comment by worthy7** [comment]
I just tried to test but I get an error 500 when trying to even make/comment on an issue...
https://try.gitea.io/worthy7/Test/issues/new

**Comment by worthy7** [comment]
Here our our service settings in the config. I didn't set this up but I can change it.
The only thing that I thought might be relevant is the `DEFAULT_KEEP_EMAIL_PRIVATE`
But when I went to try and learn about it at https://docs.gitea.io/en-us/config-cheat-sheet/
It's not there.

> [service]
> REGISTER_EMAIL_CONFIRM            = false
> ENABLE_NOTIFY_MAIL                = true
> DISABLE_REGISTRATION              = false
> ALLOW_ONLY_EXTERNAL_REGISTRATION  = false
> ENABLE_CAPTCHA                    = false
> REQUIRE_SIGNIN_VIEW               = false
> DEFAULT_KEEP_EMAIL_PRIVATE        = false
> DEFAULT_ALLOW_CREATE_ORGANIZATION = true
> DEFAULT_ENABLE_TIMETRACKING       = true
> NO_REPLY_ADDRESS                  = noreply.example.org

**Comment by worthy7** [comment]
Sorry, here are the Mailer settings too:

[mailer]
ENABLED     = true
HOST        = ms.ourcompany.co.jp:25
FROM        = gitea@theserver.ourcompany.co.jp
# USER        = gitea
SKIP_VERIFY = true

**Comment by worthy7** [comment]
So what's happening is, we get the email from the "gitea@theserver.ourcompany.co.jp" email address, but the NAME attached to it is the username of the person who did the action.

And my issue is that on `close issue` that user should not be the author of the issue, but instead should be the closer of the issue.

Sorry I should have checked our custom settings before writing the issue up.

**Comment by guillep2k** [comment]
You are right, the e-mail address and the name in the `From:` field don't match; I think that's expected. However, in my case the name in the `From:` field *is* the doer.

Gitea had a lot of changes since 1.8.2. Many of them in the notification system. I didn't test with 1.9.3 (latest release), but I expect you would get a different outcome. Is it possible for you to install a test instance in your server with 1.9.3 and check?

PS: I don't know what happens with try.gitea.io lately. Perhaps it's time to clean that up?

**Comment by worthy7** [comment]
Ok I'll ask our guy to upgrade and I'll reopen if the issue is still there
Thanks
