### ISSUE TITLE
to be able fork own repo to different names

### ISSUE THREAD

**Issue by ikozhukhov** [go-gitea/gitea#8328]
- Gitea version (or commit ref):
- Git version: 1.9.3
- Operating system: DilOS
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

example: i have created a mirrors of external repos and configured sync time.
i want create another repo as fork of mirrored repo for local commits, but i can't.
another example where i hate github: i can see 'illumos' repo and can fork it to my account only to one repo. 'openzfs' repo based on 'illumos' repo, but i can't for separate repo to my account if i did fork of one. i want separate repos because better to PR and both are repos have different commits on 'master' in the same time.
i like 'bitbucket' approach where i can fork own repo or remote repo to new name and use it.
i'd like to see the same ability in the fantastic one binary gitea!
help me please in this usecase!

**Comment by lunny** [comment]
I don't think this should be supported.

**Comment by 6543** [comment]
@ikozhukhov
if you realy like to have a "forg" you can do it manualy:  https://gist.github.com/niksumeiko/8972566

**Comment by 6543** [comment]
Or use a Organisation:
A:
 1. Creat a Org (if you have none)
 2. Forg repo to Org
B:
 1. Creat a Org (if you have none)
 2. Move repo to Org
 3. Forg repo to you

**Comment by guillep2k** [comment]
> 
> 
> Or use a Organisation:
> **A:**
> 
>     1. Creat a Org (if you have none)
> 
>     2. Forg repo to Org
> 
> 
> **B:**
> 
>     1. Creat a Org (if you have none)
> 
>     2. Move repo to Org
> 
>     3. Forg repo to you

You cannot create an organization if you're not the site admin, AFAIK.

**Comment by 6543** [comment]
found a better solution: just "migrate" !
