### ISSUE TITLE
Can't create Gogs Webhook

### ISSUE THREAD

**Issue by aamsur-mkt** [go-gitea/gitea#8332]
- Gitea version (or commit ref): 1.10.0+dev-350-g36bcd4cd6
- Git version:
- Operating system: Ubuntu 18.04
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes - https://try.gitea.io/aamsur/test/settings/hooks/gogs/new
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
When i create a webhook with gogs, it always showing an error **_HTTPMethod cannot be empty._**

## Screenshots

![gitea](https://user-images.githubusercontent.com/52022433/65952433-13205e00-e46c-11e9-8205-e68b40df9a2f.gif)

**Comment by lunny** [comment]
duplicated with #7692
