### ISSUE TITLE
Make contributing to a private repository easier

### ISSUE THREAD

**Issue by strk** [go-gitea/gitea#835]
This is an idea for discussion about simplifying contributions to a private repository.
Currently for a contributor who wants to send a pull request for a private repository these steps are needed:

 1. Fork the repository
 2. Grant read access to the fork to anyone who have to review and can merge his contribution

I'm not sure if pull requests are allowed at all at the moment, because a user reported being unable to do so (maybe because made a member/contributor of the organization?).

Anyway my idea is to automatically create, upon forking a repository, a team representing "all the users who had read access to the repository being forked", and grant this new team read permission on the fork. The user forking the repository should be warned about the creation of such team so he can remove the permission if so willing. Or be given a choice at fork time...

Even better it would be if the team would be an actual "proxy" to the permissions in the original fork, so to follow changes in the original organization, but as I can envision such a thing could become very complex, a snapshot would be a great start already.
 
What do you think ?

@bkcsoft

**Comment by lunny** [comment]
The only way to contribute to a private is to join that repository. If you can fork that repository, so that you have read access to that repository.

**Comment by strk** [comment]
@lunny: right, you obtain read access to the repository, you fork, but then the ones who are supposed to be pulling from your fork won't have read access to it (to the fork), unless an explicit action is taken by the contributor to grant those permissions. This is what this ticket is about. Making that explicit action easier or maybe not even needed by default.

What is not easy now is figuring out *who* needs to have read access to  your fork, for example. You know you want the ones who have "merge" rights to read it, but more likely all the ones who do have "read" rights on the original repo (so to also include reviewers). It's probably a more rare use case that you want your custom changes (your fork) to be unreadable by the people who could read the original repo you forked from...

**Comment by bkcsoft** [comment]
@strk You _can_ make a PR from your fork to upstream though... Upstream does not require read-access to your fork :)

**Comment by strk** [comment]
Are you sure ? Did you try ? How could the "Files Changed" tab work ?
I think I only tried pulling the changes via commandline git because
the forker could not file a PR possibly due to being part of the
original team (I might have filed another ticket for that).

**Comment by bkcsoft** [comment]
Where the integration-test for this? :trollface:

**Comment by strk** [comment]
I've created a private repo and made you a collaburator
with read access, please send a PR: https://try.gitea.io/strk/private

**Comment by bkcsoft** [comment]
@strk Done 🙂 https://try.gitea.io/strk/private/pulls/1

**Comment by strk** [comment]
Sorry, I merged with the button before trying to do it on commandline.
Want to send another ? :)

**Comment by bkcsoft** [comment]
@strk I left a comment and a new PR for you to test :)
