### ISSUE TITLE
[UI] /issues page side menu width

### ISSUE THREAD

**Issue by jaqra** [go-gitea/gitea#8350]
Why side menu has `width` and `margin`. Can we remove them all to shown as 100% width?

When organization name long, can't see repository names. Can we also add title attribute to shown on hover?

![issues](https://user-images.githubusercontent.com/48099350/66027879-84135480-e504-11e9-88d2-fbea44128249.png)

**Comment by guillep2k** [comment]
Can you provide a screenshot of what would be the result of the proposed change?

**Comment by jaqra** [comment]
The main problem is i cant see REPOSITORY1 or REPOSITORY2 currently

This is what i think for new style. But someone can propose better looks

![issues](https://user-images.githubusercontent.com/48099350/66042457-25120780-e525-11e9-9c53-be35768b0384.png)

**Comment by guillep2k** [comment]
For me this change should be OK. Some languages tend to have longer titles (Spanish is my case) and many times the styles do not work very well with them. Can you send a PR for this?

**Comment by jaqra** [comment]
I can send after 6 hours
