### ISSUE TITLE
500 error creating pull request

### ISSUE THREAD

**Issue by bkmgit** [go-gitea/gitea#8351]
- Gitea version (or commit ref): Gitea 1.9.3
- Git version: 1.8.3.1
- Operating system: Cent OS 7
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [X] MariaDB
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X] No
  - [ ] Not relevant
- Log gist:
Not sure what to put here. Log contains only SQL command history.

## Description

500 error obtained when trying to merge a pull request through the web interface.  It is possible to merge the pull requests using the command line on a different computer, for example following

* http://www.bartread.com/2014/02/12/git-basics-how-to-merge-changes-from-a-different-fork-into-your-own-branch/
 * https://stackoverflow.com/questions/6022302/how-to-apply-unmerged-upstream-pull-requests-from-other-forks-into-my-fork
 
and then pushing the changes.

Specifically, within the main repository one is working in, one can:

    git remote add somefork https://my.gitea.ip:3000/cool/fork
    git fetch somefork
    git checkout master
    git merge somefork/master
    git push

Old related issues include #5253 #1434 #6460 #7636
...

**Comment by guillep2k** [comment]
There are some important incompatibilities in git versions prior to 1.9.0. Check [Gitea's README](https://docs.gitea.io/en-us/#system-requirements). Please consider upgrading git.

**Comment by bkmgit** [comment]
Thanks, upgrading git resolved the issue.
