### ISSUE TITLE
Link notifications to the comment anchor

### ISSUE THREAD

**Issue by bobemoe** [go-gitea/gitea#8362]
The notifications are great, giving a quick link to the issues that has been updated, but when an issue has lots of comments I find myself spending a lot of time scrolling down to get to the latest comment. Would it be possible to link to the latest comment anchor? 
(e.g `.../issues/184#issuecomment-7758` rather than just `.../issues/184`)

This is already done in the email notification (https://github.com/go-gitea/gitea/issues/1669) its easy there because each update has its own email, which can contain a specific link.

I guess the problem with the notification in the web fronted is that multiple updates for a single issue are all rolled into one notification. What happens if there is a combination of comments and non-comment updates? Do we:

* Link to the top of the issue (as we do now)
* Have one notification per update? (bit spammy, do we mark them all read when one is read?)
* Link the the first new comment?
* Link to the last new comment?
* Provide some buttons so the user can choose?
* Provide a summary showing the types of updates?
* Highlight all the updated elements when loading the issue page?

I see some discussions going on about the notification system over here: https://github.com/go-gitea/gitea/issues/145 but had hoped this could be a quick fix, however upon consideration of the above list it looks like it needs some more thought... hmm... thoughts?

**Comment by guillep2k** [comment]
I thinks the easiest and most sensible option would be to link to the first new comment.
