### ISSUE TITLE
Mail notification on commit

### ISSUE THREAD

**Issue by dimmuboy** [go-gitea/gitea#8365]
- Gitea version (or commit ref): 1.9.3
- Git version: 2.22.1
- Operating system: Arch Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:
   None
## Description

I don't know how should it works but I don't get mail notifications about new commits.
I have repo in my watchlist it's starred too.
I'm member of team where repo is.
I have correct mail address and mail server setup (test mail works).
In config file is enabled DEFAULT_EMAIL_NOTIFICATIONS and ENABLE_NOTIFY_MAIL

**Comment by bobemoe** [comment]
I don't _think_ this is implemented yet. There is discussion (and possibly a fork with this) along with other notification improvements over at https://github.com/go-gitea/gitea/issues/145

**Comment by lunny** [comment]
We needs a PR to implement that.

**Comment by lunny** [comment]
I remember one of @guillep2k 's PR will fix this.

**Comment by guillep2k** [comment]
@lunny Sorry, my PRs were about updating references from commit messages, but commits do not send mail notifications per-se. `CommitRepoAction()` should handle this, and it creates an `action` through `models.NotifyWatchers`, but mails are not generated AFAIK.

**Comment by lunny** [comment]
Implement `NotifyPushCommits` will resolve the issue?

**Comment by guillep2k** [comment]
It looks like most of `CommitRepoAction` should be moved to notifications. But for a minimal implementation yes, `NotifyPushCommits` would be enough.

**Comment by guillep2k** [comment]
Bump!

**Comment by bendem** [comment]
On top of that, a visual indicator in the PR's conversation about new commit would also help.

**Comment by alam-R** [comment]
As a workaround for mailing pushing events, I have created a minimal Java Service to handle a push webhook and map it to mail.
It needs a lot of customization but it can be a workaround for small projects.
For anyone who is interested: https://github.com/alam-R/giteaWebhookMailProxy 

Cheers!

**Comment by Zyzto** [comment]
any news on this ?

**Comment by techknowlogick** [comment]
Closing this as emails happen on commits (at least to PRs), and they are added to PR conversations.
