### ISSUE TITLE
Update gitea?

### ISSUE THREAD

**Issue by jayjupdhig** [go-gitea/gitea#8367]
Hi there

"**Updating to a new version**
You can update to a new version of Gitea by stopping Gitea, replacing the binary at /usr/local/bin/gitea and restarting the instance. The binary file name should not be changed during the update to avoid problems in existing repositories."

(https://docs.gitea.io/en-us/install-from-binary/)

This seems to be only the previos step before updating, to remove the binary file. (This can't be the update process itself??)

So what i have to do AFTER removing that file? (=The update process itself in my opinion)

Can't see any information related to my issue on https://docs.gitea.io/en-us/install-from-binary/

Thank you for your feedbacks.

Best regards, Jan

**Comment by 6543** [comment]
well if i understand you are confused that the only step to upgrade gitea is to replace the binary?

**Comment by guillep2k** [comment]
Gitea contains migration procedures as part of its code. When you run a new Gitea on an older installation all the needed procedures trigger automatically, provided the previous version was not too old. Gitea maintainers put a lot of effort in keeping backward compatibility as much as possible.

As @6543 said, for a vanilla installation you just need to replace the binary. If you have some custom templates or translations, you'd probably need to take a look at those as well.

What you can't do is to run the binary in a different location or with a different name (e.g. `gitea-new`) as that would break many things.

**Comment by martijintro** [comment]
thank you very much, will try that.

**Comment by sapk** [comment]
@martijintro I think that your question has been answered. 
I will close this issue so. 
Feel free to re-open it if needed.
