### ISSUE TITLE
Gmail does not work with Gitea

### ISSUE THREAD

**Issue by jayjupdhig** [go-gitea/gitea#8368]
Do i need to set a special setting? (SSL, TLS, whtever..) ? 

What is the default for mail servers?

That does not work:

```
ENABLED = true
HOST    = smtp.gmail.com
FROM    = xxx@gmail.com
USER    = xxx@gmail.com
PASSWD  = ......
```

Why? Thank you for your feedbacks.

Regards, Jan

**Comment by homburgs** [comment]
![image](https://user-images.githubusercontent.com/2833290/66130517-1ba2a100-e5f2-11e9-8783-df13f8e0ad76.png)

**Comment by martijintro** [comment]
Thank you very much!

I know that, but what i need to configure here?

```
ENABLED = true
HOST    = smtp.gmail.com
FROM    = xxx@gmail.com
USER    = xxx@gmail.com
PASSWD  = ......
```

if the default setting for gitea mailing unencrypted, so i need to add some parameters? (What are the default connection options?)

Regards, Jan

**Comment by homburgs** [comment]
Have a look https://docs.gitea.io/en-us/config-cheat-sheet/ at Section Mailer

**Comment by martijintro** [comment]
thx

**Comment by martijintro** [comment]
smtp.gmail.com:587 does not work, as described here: https://github.com/gogs/gogs/issues/4310

Then i will look on that manual..

**Comment by martijintro** [comment]
Maybe i need to restart gitea service first before the new config will be applied...(?)

**Comment by martijintro** [comment]
How can i use SSL instead if TLS with Google Mail Server smtp.gmail.com:465 ?

Can't see any options to switch to SSL here: https://docs.gitea.io/en-us/config-cheat-sheet/

**Comment by homburgs** [comment]
of course

**Comment by martijintro** [comment]
Now it works, thx, i added a few paramters then i restarted the gitea service:

```
ENABLED        = true
HOST           = smtp.gmail.com:587
FROM           = xxx@gmail.com
USER           = xxx@gmail.com
PASSWD         = ......
**MAILER_TYPE    = smtp
IS_TLS_ENABLED = true**
```

Have a nice day, thx again!! :-)

**Comment by guillep2k** [comment]
Perhaps it would be interesting to add this to the docs as a sample GMail configuration?

**Comment by martijintro** [comment]
Why not, i think GMail server will used a lot...

But i'm not 100% sure the "MAILER_TYPE" parameter is required or not. Maybe it's not. (?)

"IS_TLS_ENABLED" seems to be required, it was not working without it..

**Comment by LostSoulfly** [comment]
I was not able to use TLS with gmail.. it would fail every time.

However, using port 465 worked for me without TLS..

```
[mailer]
ENABLED = true
HOST    = smtp.gmail.com:465
FROM    = *********.server@gmail.com
USER    = **********.server@gmail.com
PASSWD  = **************
MAILER_TYPE    = smtp
IS_TLS_ENABLED = false
```

**Comment by riccardodivirgilio** [comment]
Hello I'm having trouble with my gmail config:

I get this when testing the config
Failed to send a testing email to 'riccardo@rotostampa.com': gomail: could not send email 1: NewClient: tls: first record does not look like a TLS handshake

My config:

    [mailer]
    ENABLED        = true
    FROM           = workflow.sender@gmail.com
    MAILER_TYPE    = smtp
    HOST           = smtp.gmail.com:587
    IS_TLS_ENABLED = true
    USER           = workflow.sender@gmail.com
    PASSWD         = `...`
    USE_SENDMAIL   = false

**Comment by lafriks** [comment]
please do not comment on closed issues, for community support please use https://discourse.gitea.io/ or Gitea discord chat

**Comment by mariusrugan** [comment]
@riccardodivirgilio as @LostSoulfly above said, confirming it works without IS_TLS_ENABLED=true

```
[mailer]
ENABLED        = true
HOST           = smtp.gmail.com:587
FROM           = xyz@gmail.com
USER           = xyz@gmail.com
PASSWD         = ***
MAILER_TYPE    = smtp
IS_TLS_ENABLED = false
HELO_HOSTNAME  = example.com
```
