### ISSUE TITLE
[Question] how to integrate translation tools

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#8372]
How can I integrate Translation Tools like **Crowdin** or **Weblate** and so ...

**Comment by 6543** [comment]
should also in scope of https://github.com/go-gitea/gitea/issues/1029 ...

**Comment by jolheiser** [comment]
Here is the [Weblate Documentation](https://docs.weblate.org/en/latest/admin/continuous.html#gitea-setup)

**Comment by 6543** [comment]
and how about Zanata, because Framasoft host a free instance [link](https://trad.framasoft.org/)

**Comment by techknowlogick** [comment]
For Crowdin the Gitea project pulls and pushes new translations via the CI system. As for Zanata you’d have to ask that project for instructions, usually it is very similar to how GitHub integration would work.

Closing this for now. Please feel free to continue this discussion on discord or the forum.

**Comment by 6543** [comment]
ok ... i was going to close this anyway
