### ISSUE TITLE
[Bug] Go-Dependency | invalid pseudo-versio

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#8387]
go: github.com/go-macaron/cors@v0.0.0-20190309005821-6fd6a9bfe14e9: invalid pseudo-version: revision is longer than canonical (6fd6a9bfe14e)

**Comment by 6543** [comment]
needed for https://github.com/alpinelinux/aports/pull/10887

**Comment by techknowlogick** [comment]
This is resolved in gitea 1.10-dev, We are unable to backport it.

Gitea 1.9.x does not support go1.13

**Comment by 6543** [comment]
@techknowlogick alpinelinux user are still on giea version 1.8.3 !
an i had a PR wich get tehm 1.9.3 but **this** is blocking it and to wait until 1.10.x has its first stable release will take a wile :(

**Comment by techknowlogick** [comment]
@6543 sadly this error is caused by an upstream library, and we have resolved this, but sadly in a way that can't be backported. 1.10 milestone is almost complete (less than 5 PRs left).

**Comment by 6543** [comment]
this: https://tip.golang.org/doc/go1.13#version-validation
is telling me that we would only add one line in go.mod

**Comment by 6543** [comment]
the diff would be:

```diff
diff --git a/go.mod b/go.mod
index 2c137af81..629d35ea7 100644
--- a/go.mod
+++ b/go.mod
@@ -46,7 +46,7 @@ require (
        github.com/go-macaron/binding v0.0.0-20160711225916-9440f336b443
        github.com/go-macaron/cache v0.0.0-20151013081102-561735312776
        github.com/go-macaron/captcha v0.0.0-20190710000913-8dc5911259df
-       github.com/go-macaron/cors v0.0.0-20190309005821-6fd6a9bfe14e9
+       github.com/go-macaron/cors 6fd6a9bfe14e9
        github.com/go-macaron/csrf v0.0.0-20180426211211-503617c6b372
        github.com/go-macaron/i18n v0.0.0-20160612092837-ef57533c3b0f
        github.com/go-macaron/inject v0.0.0-20160627170012-d8a0b8677191
```

**Comment by techknowlogick** [comment]
Please send PR for this against release/v1.9 banch :)

**Comment by 6543** [comment]
THANKS

**Comment by 6543** [comment]
with the first changes `make` will get an errror but `go build` run just fine ...
after it the diff looks similar but now make run too ...

ill send the filan patch as PR ...

**Comment by 6543** [comment]
@techknowlogick  https://github.com/go-gitea/gitea/pull/8389
