### ISSUE TITLE
Referenced issue link erroneously added when # is used in a code block

### ISSUE THREAD

**Issue by bobemoe** [go-gitea/gitea#8397]
- Gitea version (or commit ref): 1.10.0+dev-377-gbc5a479fe

## Description

I see recently new functionality https://github.com/go-gitea/gitea/issues/4302 that adds a backlink to the referencing issue.  

However its being added if #{id} is found in a code block, e.g:

```
this probably shouldn't reference #8137 
not sure if github does this too, this will be a good test!
EDIT: it does not!
```

See https://try.gitea.io/bobemoe/test/issues/4

I also notice if you edit your comment, you get a duplicate reference link.

**Comment by guillep2k** [comment]
This should be fixed by #8261
