### ISSUE TITLE
Non-existant documentation for where we're at presently

### ISSUE THREAD

**Issue by techzilla** [go-gitea/gitea#84]
The fork was very necessary, Gogs was created and likely funded as a go language marketing initiative, thus when it's time-line was over it achieved it's goals.   It's own documentation reflects this concern, placing higher priority on appearance than utility.

We need to take a final archive of their documentation, and clear the project of Gogs documentation.  
Or if we already have a Wiki in progress, it should be prominent.

**Comment by tboerger** [comment]
Feel free to open pull requests for this repository or the docs repository to replace the gogs references.

**Comment by voltagex** [comment]
Also any plans for sending changes upstream?

**Comment by voltagex** [comment]
@tboerger could you enable Issues on the website repo so I can have some discussions over there?

**Comment by tboerger** [comment]
I'm not an admin. @lunny any reason to disable issues for the docs repo?

**Comment by tboerger** [comment]
@volagex as long as it's upstreamable yes. But it wi get difficult soon :)

**Comment by lunny** [comment]
It's a default rule since it is forked from gogs. I have enabled it. @tboerger @voltagex
