### ISSUE TITLE
Snap Package Fails to Complete Install After Trying to Register

### ISSUE THREAD

**Issue by mowestusa** [go-gitea/gitea#8406]
-->

- Gitea version (or commit ref): Snap Package installed
latest/edge | v1.9.0-dev+git29.d578b71 | 27 March 2019

- Operating system: Fedora 31 beta Workstation (installed snap package)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description
The snap package appears to install without issue. I can go to localhost:3001 and the Gitea page appears. I click on "Register" to complete the install of Gitea. I accept all the currently checked defaults. I add may administrator user. I click install and the following error screen comes up.
...

## Screenshots
![191006ErrorScreen-AfterInstallGiteat](https://user-images.githubusercontent.com/31476924/66278663-50745980-e879-11e9-8b49-a923375aeb71.png)

**Comment by bagasme** [comment]
Any log gist?

**Comment by pokemaster7** [comment]
I can reproduce this issue. Further attempts to relaunch `gitea web` fail without error message. The log file show errors like the following:

```
2019/12/08 14:36:15 [...itea/routers/init.go:95 GlobalInit()] [E] Failed to initialize issue indexer: mkdir indexers: read-only file system
```

Note that `gitea web` requires root permissions to run when installed as a snap package.
