### ISSUE TITLE
Make Protected Branches -> Approvals section easier to understand

### ISSUE THREAD

**Issue by worthy7** [go-gitea/gitea#8407]
Small issue concerning UX design which at least caused me a little bit of confusion.

1. `Allow only to merge pull request with enough positive reviews of whitelisted users or teams.`
   -> `Allow merging of pull requests only with enough positive reviews from approvers.`

2. `Whitelisted reviewers:` -> `Reviewers:`

3. default text set to `Search contributing teams or users...`

4. Add a checkbox first saying "Require approvals", when unchecked the two options are disabled, when checked, the "number of approvals" is minimum 1 and the input for Approvers should be "required" (input required). Doing a dynamic calculation to see if they match is not worth it since team sizes can change in the future

For reference here is how GitHub looks
![image](https://user-images.githubusercontent.com/4762399/66278857-f52d8000-e8e7-11e9-8f1b-51d1f4c1fcb9.png)

I made a mock-up design for someone to follow:
![image](https://user-images.githubusercontent.com/4762399/66278961-ee533d00-e8e8-11e9-98b3-dbd947c57e7f.png)

Open for discussion!

**Comment by bagasme** [comment]
Please consider also the case when the approvers are *writers*, as per #8288 (which I open the issue).
