### ISSUE TITLE
Active Directory not working

### ISSUE THREAD

**Issue by Mr-Reca** [go-gitea/gitea#8413]
- Gitea version (or commit ref): gitea:latest from Docker
- Git version: gitea:latest from Docker
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:

## Description
I'm trying to configure AD Authentication. I followed all guides on Internet, but the output is the same:
```
2019/10/07 15:26:12 ...dels/login_source.go:717:UserSignIn() [W] Failed to login '<username>' via 'AD': user does not exist [uid: 0, name: <username>, keyid: 0]
2019/10/07 15:26:12 routers/user/auth.go:167:SignInPost() [I] Failed authentication attempt for <username> from <source_ip>
```

I'm using now the config above in Authentication Source (sorry it's in Spanish):

Is it possible to "automate" this process when using Docker? In case the pod is restarted or I update the info. Or is this info stored in the MySQL, so I will need some script to deploy it from scratch? 
...

## Screenshots
![imagen](https://user-images.githubusercontent.com/17903554/66325919-5d03bb00-e928-11e9-9bed-3bee1260abed.png)

**Comment by guillep2k** [comment]
I guess `<username>` is something you replaced, not something that actually shows up in your log, isn't it?

**Comment by Mr-Reca** [comment]
Yes. I put a “placeholder” because of internal policies.

**Comment by guillep2k** [comment]
Anyway, you need to replace some of the values depending on your configuration. For example, for my own system ("miempresa.es"), it should be something like this:

- ***Báse de búsqueda de usuarios***: `CN=Users,dc=miempresa,dc=es`. Notice that it's `CN=` and not `OU=`; also in my case it's `Users` and not `Usuarios` (my server was installed in English, but I believe that this doesn't change with the server language).

- ***DN de Usuario***: same considerations.

There are other kinds of queries that can be used, including using the `OU=` parameter, but they must exist in your AD configuration in order to work.

You could check some tool like [this](http://www.joeware.net/freetools/tools/adfind/index.htm) (I don't know it, it just popped up on a search) to test your search parameters.

Please notice that this is not a support forum. If you're still having problems, please ask in the `#Configuration` channel of our [Discord server](https://discord.gg/NsatcWJ), or in our [forum](https://discourse.gitea.io/).

**Comment by Mr-Reca** [comment]
I also tried that configuration.

I opened the issue because there are lots of links with configurations and none of them works. I think that maybe something is missing (in documentation or implementation of LDAP)

**Comment by Mr-Reca** [comment]
Hi @guillep2k ,

I tried AdFind and the same query does not work in Gitea. Is it better to close this issue and talk through the forum, or do you think it can be something? Is it possible to test this feature with another AD?

Thank you so much for your time,

**Comment by guillep2k** [comment]
@Mr-Reca The AD feature is not only used in many installations (it's a popular way of using Gitea) but it's also tested every time a single line of code is added to Gitea in our [continuos integration tests](https://drone.gitea.io/go-gitea/gitea/13546). Everything is susceptible of having bugs and we're far from 100% test coverage, so bugs *can still slip in*.

Anyway, [check this link](https://discourse.gitea.io/t/using-samaccountname-for-ldap-login/860/7) and search around the forum; you might find the solution there.

Feel free to leave this issue open if you feel that it's a bug in Gitea.

**Comment by markkrj** [comment]
Considering Active Directory, your User DN is wrong. It must be CN=username,OU=your,OU=user,OU=organization,OU=unity,DC=your,DC=domain. But you really must consider using an bind DN, it is more secure.

**Comment by Mr-Reca** [comment]
Hi @markkrj 

I'm trying now withou LDAPS for testing, I'll set it up later. Is it safer to user BindDN? When I check this option, Gitea says that this value will be stored in raw.

I'll try to change my user DN. Thank you so much for your time,

**Comment by lafriks** [comment]
User DN should probably be:
```
CN=%s,OU=Usuarios,OU=<department>,OU=<office>,DC=<domain>,DC=<local>
```

Does `sAMAccountName` is the same as `CN=` for users?

If it is not that it will not work and you should use something like this for user filter:
```
(&(objectCategory=Person)(!(UserAccountControl:1.2.840.113556.1.4.803:=2)))
```

**Comment by lafriks** [comment]
Also for AD I would probably recommend using `LDAP (via BindDN)`

Of course you need to create service user in AD for this

**Comment by Mr-Reca** [comment]
> 
> 
> User DN should probably be:
> 
> ```
> CN=%s,OU=Usuarios,OU=<department>,OU=<office>,DC=<domain>,DC=<local>
> ```
> 
> Does `sAMAccountName` is the same as `CN=` for users?
> 
> If it is not that it will not work and you should use something like this for user filter:
> 
> ```
> (&(objectCategory=Person)(!(UserAccountControl:1.2.840.113556.1.4.803:=2)))
> ```

No, it's not the same. the CN in User DN is the display name. sAMAccountName is the username

**Comment by lafriks** [comment]
That is why id does not work as you enter user CN but user filter filters it out as it does not match

**Comment by Mr-Reca** [comment]
So I could configure to use `displayName` which matchs with DN, but I am not able to use `sAMAccountName` ?

**Comment by finkr** [comment]
set "LEVEL=debug" in the file `app.ini` to see error messages (restart required)
