### ISSUE TITLE
Commiting an empty file on the WebUI is ignored

### ISSUE THREAD

**Issue by theAkito** [go-gitea/gitea#8420]
- Gitea version (or commit ref): b84a251fc
- Git version: any
- Operating system: any
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant

## Description

Not sure if this is intended.
Commiting an empty file on the WebUI does not work.

**Comment by LukBukkit** [comment]
I can reproduce this issue.
I guess if you're able to upload empty files, you should also be able to create them via the web ui. This feature would be useful for creating new directories online with empty `.gitkeep` files.
I'll try to create a pull request.

**Comment by Akito13** [comment]
> 
> 
> I can reproduce this issue.
> I guess if you're able to upload empty files, you should also be able to create them via the web ui. This feature would be useful for creating new directories online with empty `.gitkeep` files.
> I'll try to create a pull request.

In my case I was creating files where the file name was primarily important, so I wanted to create the files with the correct filenames, before filling them with content. So creating empty files has several purposes.

Additionally, even if it was intended, there should still be an error or warning message. There was none, whatsoever though. At first I thought, the connection dropped or something like that.

**Comment by LukBukkit** [comment]
There's no error or warning, because the editor just changes a hidden textarea, which was required for the form to work.
But I'm close to the solution.
