### ISSUE TITLE
Help link on Empty Repository Quick Guide

### ISSUE THREAD

**Issue by bagasme** [go-gitea/gitea#8421]
- Gitea version (or commit ref): 1.9.0
- Git version: 2.17.1
- Operating system: Ubuntu 18.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:
(not relevant)

## Description
On empty repository, there is `Quick Guide` when visiting `Code` tab. The `Help` link for cloning the repo is [Git-Basics-Getting-a-Git-Repository](http://git-scm.com/book/en/Git-Basics-Getting-a-Git-Repository), which redirect to [Git - Getting a Git Repository (Pro Git v2 Book)](https://git-scm.com/book/en/v2/Git-Basics-Getting-a-Git-Repository). Perhaps the `Help` link should be reworded to `Getting a Git Repository on Pro Git Book`.

Also, the link to [GitHub Help](https://help.github.com/en/articles/cloning-a-repository) can be added besides the Pro Git link.

Thus, the wording should be:
```
Need help? See Getting a Git Repository on Pro Git Book or GitHub's Cloning a repository guide for details.
```
## Screenshots

This screenshot is from my `localhost` instance, when setting up code mirror to [Hugo repo](https://github.com/gohugoio/hugo):
![image](https://user-images.githubusercontent.com/40219486/66367123-1613d500-e9bd-11e9-82aa-06784ed40ac1.png)

**Comment by wxiaoguang** [comment]
Gitea is not the same as GitHub, and they may differ more and more. The GitHub help would mislead newbies.
