### ISSUE TITLE
Template error when trying to visit mirror settings page

### ISSUE THREAD

**Issue by wsand02** [go-gitea/gitea#8437]
- Gitea version (or commit ref): 1.10.0+dev-380-g356e1a70e
- Git version: Not sure since it's gitea.com
- Operating system: Not sure since it's gitea.com
- Database (use `[x]`): Not sure since it's gitea.com
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL) Create a new mirror and try to visit the settings page
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
When I try to visit the settings of a mirror on gitea I keep getting this error:

```
template: repo/settings/options:91:65: executing "repo/settings/options" at <.Mirror.Username>: can't evaluate field Username in type interface {}
```

## Screenshots
![image](https://user-images.githubusercontent.com/29465936/66469129-9d2d7f80-ea87-11e9-944c-de4007f1337f.png)

**Comment by bagasme** [comment]
I need more comprehensive log instead of just error message...

**Comment by wilsandbrink** [comment]
I won't be able to provide that since I don't have access to the gitea.com and try.gitea.io logs.

**Comment by bagasme** [comment]
So can you reproduce this issue on your local Gitea server?

**Comment by wilsandbrink** [comment]
I'm not currently hosting a gitea instance.
