### ISSUE TITLE
[Feature Request] At Pull Request: download patchfile [Button]

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#8444]
add a option to download the patch of the PullRequest

GitLab has a buton and Github does via link

For example:
-> https://patch-diff.githubusercontent.com/raw/alpinelinux/aports/pull/10887.patch
-> https://patch-diff.githubusercontent.com/raw/alpinelinux/aports/pull/10887.diff

**Comment by bagasme** [comment]
What about your use case for this feature request?

**Comment by zeripath** [comment]
It's basically copying GitHub functionality, but allows Gitea to function a bit like a patch server. I could imagine it being necessary to form part of federation or to allow Gitea to integrate with other VCS s.

It's not a high priority issue afaics just a nice to have.

**Comment by lunny** [comment]
@6543 Did you mean https://gitea.com/gitnex/GitNex/pulls/122.patch ?

**Comment by 6543** [comment]
@zeripath you are right :low_prio: ... this is a note for a nice to have fumction
@lunny this are only demo links how it can look like (kan add a gitlab demo too butvdont think it is nessesary)

**Comment by zeripath** [comment]
I think @lunny means that the code for this is already present:

https://gitea.com/gitea/log/pulls/10.patch

https://gitea.com/gitea/log/pulls/10.diff

(Which are both public PRs so anyone should be able to see.)

I guess the issue is that the links aren't displayed anywhere.

**Comment by lunny** [comment]
Yes, so we only need a button or a link on a suitable place.

**Comment by 6543** [comment]
I'm searching in the docu if there is a note ..

**Comment by 6543** [comment]
and I'll search for the button too - perhaps i find a place

**Comment by 6543** [comment]
@lunny does gogs have this too?

**Comment by 6543** [comment]
![Bildschirmfoto zu 2019-10-10 17-22-19](https://user-images.githubusercontent.com/24977596/66582762-946da400-eb82-11e9-8fba-05339a4a7ff9.png)

make "Show  Diff Stats" to a dropdown menue "Diff Options" wich contain
 * "Show Stats"
 * "Download Patch"
 * "Download Diff"

?

**Comment by guillep2k** [comment]
Sounds reasonable.

**Comment by 6543** [comment]
-> https://github.com/go-gitea/gitea/pull/8470
