### ISSUE TITLE
Warn 'Invalid cookie header' when used gitea repo for config server 

### ISSUE THREAD

**Issue by DawN1ng** [go-gitea/gitea#8457]
- Gitea version (or commit ref): 1.10.0
- Git version: 1.8.3.1
- Operating system: Linux RHEL7
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

When I use a gitea repo for spring cloud config server, There comes too many warn logs
about the Invalid cookie header and keep coming up.

WARN 7764 --- [nio-8888-exec-1] o.a.h.c.protocol.ResponseProcessCookies  : Invalid cookie header: "Set-Cookie: _csrf=xCfr5yFPsDUg9_On8A-8jG3UmsY6MTU3MDc2MDgyNDk2NzQ5MjY0NA; Path=/; Expires=Sat, 12 Oct 2019 02:27:04 GMT; HttpOnly". Invalid 'expires' attribute: Sat, 12 Oct 2019 02:27:04 GMT

I used to think that it was something else due to other components of my project. But when I change the repo source of config server from gitea repo to other git repo, it works.

Probably similar to this question :
https://discourse.gitea.io/t/gitea-over-http-attempts-to-set-cookie-error/917

## Screenshots
![issue](https://user-images.githubusercontent.com/16551517/66620437-0a215080-ec13-11e9-89c9-caf107ed9e8d.png)

**Comment by guillep2k** [comment]
May be your problem is related to this?
https://github.com/gradle/gradle/issues/1596#issuecomment-305180645

Note: the project is unrelated, just the problem is the same.

**Comment by DawN1ng** [comment]
@guillep2k Yep,it's the same problem about httpclient standard or sth.but I don't think it's the same cause and I don't get any help or solution from that question actually.

**Comment by guillep2k** [comment]
The comment I linked to before was pointing to a "known" [bug in Apache](https://issues.apache.org/jira/browse/HTTPCLIENT-1077).

If in your case it really is a bug in Apache, then nothing can be done in Gitea. The solution would be simply to upgrade Apache to a newer version.
