### ISSUE TITLE
Can't set collaborator permissions with only keyboard

### ISSUE THREAD

**Issue by Jookia** [go-gitea/gitea#8460]
- Gitea version (or commit ref): 1.9.1
- Git version: 2.23
- Operating system: Arch Linux
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
https://try.gitea.io/Jookia/test/settings/collaboration
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

When managing collaborators in repository settings, any changes to user permissions made just by using the keyboard to focus the drop down menu and arrows to select an item do not save. I looked at the HTML and saw that the saving only happens onclick, which isn't triggered when using the keyboard.

Because of this you can't set collaborator permissions with only the keyboard. This is a significant roadblock for accessibility.

## Screenshots

Bug isn't visible in a screenshot

**Comment by zeripath** [comment]
Is this still the case?

**Comment by Jookia** [comment]
Yes, I haven't written the rest of the dropdown menu accessibility code as I've been doing other things. I needed to do an audit of the dropdown menus in HTML for a reason I forget- I think so I could test all of them. I'll try having a shot at this sometime this month.

**Comment by fsologureng** [comment]
I think this issue is resolved. At least I could added @jookia as a collaborator in my test repo with just keyboard interaction.

**Comment by wxiaoguang** [comment]
Fixed by https://github.com/go-gitea/gitea/pull/19861#issuecomment-1143576632 and confirmed by Jookia: https://github.com/go-gitea/gitea/pull/19861#issuecomment-1144781891

I will close this issue.
