### ISSUE TITLE
Possibility Of Login with Both Ldap and Open ID to same account

### ISSUE THREAD

**Issue by kstan79** [go-gitea/gitea#8464]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x ] Not relevant
- Log gist:

## Description
I wish to allow user to login via openid from web console, but clone checkout/push/etc using ldap password. The reason behind is we have internal keycloak server which bind to ldap. 
At this moment, gitea require to maintain internal password when I bind account to openid server. I know there is alternative way like using certificate file but that is not preferable option due to it added complexity of deployment.

**Comment by strk** [comment]
Sounds like a great idea, any chance you'll be able to think about how it could be implemented ?
Right now OpenID accounts are considered "local" so I guess we could switch from local to LDAP to do that. See also https://github.com/go-gitea/gitea/issues/1124 as I think it's somewhat related

**Comment by flortsch** [comment]
For me, this actually works. In Gitea, I setup an LDAP backend (FreeIPA) and OpenID provider (Keycloak). I can login with LDAP information, and on first login with OpenID, I can link to the existing Gitea account from the LDAP backend. With this, both OpenID via browser and repo interactions on the terminal via LDAP login work.

**Comment by lunny** [comment]
As @flortsch said, I will close this and please feel free to reopen it.
