### ISSUE TITLE
How to allow push from server to repo on protected branch?

### ISSUE THREAD

**Issue by thestepafter** [go-gitea/gitea#8472]
- Gitea version (or commit ref):
- Git version: 2.17.1
- Operating system: Ubuntu 18.04
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

So I am using a deployment service (Laravel Forge) and I want to automatically push production updates back to a protected branch before I deploy new updates. I am encountering this issue though and I'm not sure what the recommended approach would be. I had this working fine in Gitlab with a protect branch and the same SSH deploy key. (write access is enabled in Gitea for this branch.)

```
remote: Gitea: protected branch master can not be pushed to
```

What is the recommend approach with Gitea for pushing updates from production back to the repo on a protected brach?

**Comment by zeripath** [comment]
You could add a whitelist.

Deploy keys act as the repository owner so if you add the repository owner to the whitelist that should work.

(Now, that might be difficult with an organisation but let me think)

We could add another option to the protection to allow writing deploy keys to push.

**Comment by thestepafter** [comment]
I solved this by adding my individual key (as organization and repository owner) to the server and setting `.ssh/config` to use that key when pushing back to the Gitea server.

The additional option sounds like a great idea @zeripath.
