### ISSUE TITLE
Proposal: list of URL schemes to support in markdown rendering

### ISSUE THREAD

**Issue by guillep2k** [go-gitea/gitea#8490]
Currently we're allowing only http and https schemes (protocols) in links rendered markdown. There are users that want others, like ftp (e.g. #8478)

Currently, this renders nothing:
```
[My link](ftp://www.mysite.com)
```

There are a number of [other schemes we could support](https://en.wikipedia.org/wiki/List_of_URI_schemes), and some of them could be very useful, like the aforementioned ftp, VS Code extensions, cvs, ed2k, torrent, git, ssh, magnet, maps, sftp, skype, svn, etc.

I'm not sure which ones could pose a security problem, so I propose adding an `app.ini` settings with the list of desired schemes. The obvious default is `http, https`, but perhaps we want to add `ftp` and others, so let's hear out your ideas.

**Comment by silverwind** [comment]
Seems like a good addition. `mailto:` is another common scheme. Does anyone have insight on what possible security concerns could be?

**Comment by bkmgit** [comment]
Link to [uri schemes](https://en.wikipedia.org/wiki/List_of_URI_schemes) is helpful. Consistency with either Github or Gitlab markdown links is probably reasonable.
