### ISSUE TITLE
simple api to embed notifications from other software [Discusion]

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#8505]
a simple api wich drone or a for example something like self hosted discord can notify the user that new infos are available

the idear came in mind while i was thinking about a chat system in gitea and the conclusion was that this is not giteas busines but gitea oauth2 + external chat would be great the only thing wich would be useful if gitea kann notify if messages are arived ...

**Comment by guillep2k** [comment]
This seems like a duplicate of #1089

**Comment by 6543** [comment]
do have webhooks the posebilety to add something to notifications ?
