### ISSUE TITLE
missing "percent sign" in locale_pl-PL.ini

### ISSUE THREAD

**Issue by mariuszmaximus** [go-gitea/gitea#8507]
file:   options/locale/locale_pl-PL.ini

action --> commit_repo
wrong version: 
`commit_repo=wypycha do <a href="%[1]s/src/branch/%[2]s">%[3]s</a> w<a href="%[1]s">[4]s</a>`

correct version
`commit_repo=wypycha do <a href="%[1]s/src/branch/%[2]s">%[3]s</a> w<a href="%[1]s">%[4]s</a>`

**Comment by zeripath** [comment]
Hi!

Our translations are kept on crowdin and need to be changed there. However, as this is quite a clear fix I've fixed it for you and approved it already.

FYI this one would be https://crowdin.com/translate/gitea/all/enus-pl#q=commit_repo

Thanks.

**Comment by mariuszmaximus** [comment]
Thank you very much
