### ISSUE TITLE
500 error when migrating with mirror

### ISSUE THREAD

**Issue by wsand02** [go-gitea/gitea#8514]
- Gitea version (or commit ref): 1.10.0+dev-433-gdb0d4ffdc
- Git version: 2.17.1
- Operating system: Linux (Ubuntu 18.04)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No Something was wrong with the site just received 500 erros
  - [ ] Not relevant
- Log gist:
https://gist.github.com/wilsandbrink/f12c802b7c76c2859e7bc42bb0c5939a

## Description
If I migrate repository without mirroring it works fine and I get the new cloning interface. But if I mirror it I mean I still get the repo, it's just that I receive a 500 error. It's just a little annoying that's all.

## Screenshots
Hard to screenshot.

**Comment by 6543** [comment]
do you use two-factor auth?

**Comment by 6543** [comment]
convirmed ... I'll try to fix it

**Comment by 6543** [comment]
@zeripath can you add bug and backport to 1.10.x lable?

**Comment by wilsandbrink** [comment]
How do I test the version with the fix?

**Comment by wilsandbrink** [comment]
@lunny #8526 fixed the issue.

**Comment by wilsandbrink** [comment]
Reopening issue until merged.

**Comment by 6543** [comment]
@wilsandbrink well noticed ...
