### ISSUE TITLE
account password recovery error 500

### ISSUE THREAD

**Issue by 8ctopus** [go-gitea/gitea#8521]
- Gitea version (or commit ref): 1.10.0-rc1
- Git version: 2.17.1
- Operating system: Ubuntu 18.04.3 LTS
- Database (use `[x]`):
  - [x] MySQL
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes

Upgrading from 1.9.4 to 1.10.0-rc1 breaks account password recovery after I enter the new email address and click the "Recover Account" button. There's the call stack.

2019/10/15 06:07:56 ...les/context/panic.go:35:1() [E] PANIC:: regexp: Compile("][ !\"#$%&'()*+,./:;<=>?@\\\\^_{|}~`-"): error parsing regexp: missing closing ]: `[ !"#$%&'()*+,./:;<=>?@\\^_{|}~`-`
        /usr/local/go/src/regexp/regexp.go:311 (0x6bdaf1)
        /go/src/code.gitea.io/gitea/modules/password/password.go:31 (0x10a2214)
        /usr/local/go/src/sync/once.go:66 (0x484b02)
        /usr/local/go/src/sync/once.go:57 (0x10a1c3c)
        /go/src/code.gitea.io/gitea/modules/password/password.go:28 (0x10a1c0d)
        /go/src/code.gitea.io/gitea/modules/password/password.go:46 (0x10a1ca2)
        /go/src/code.gitea.io/gitea/routers/user/auth.go:1338 (0x131e000)
        /usr/local/go/src/reflect/value.go:460 (0x4977d5)
        /usr/local/go/src/reflect/value.go:321 (0x496f93)
        /go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:177 (0x9a6bf9)
        /go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:137 (0x9a65a9)
        /go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:121 (0x9d5f38)
        /go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:112 (0x112eb11)
        /go/src/code.gitea.io/gitea/modules/context/panic.go:39 (0x112eafd)
        /usr/local/go/src/reflect/value.go:460 (0x4977d5)
        /usr/local/go/src/reflect/value.go:321 (0x496f93)
        /go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:177 (0x9a6bf9)
        /go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:137 (0x9a65a9)
        /go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:121 (0x9d5f38)
        /go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:112 (0xaa35f5)
        /go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/session/session.go:192 (0xaa35e0)
        /go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:79 (0x9d5de0)
        /go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:157 (0x9a6909)
        /go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:135 (0x9a6698)
        /go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:121 (0x9d5f38)
        /go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:112 (0x9e75d9)
        /go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/recovery.go:161 (0x9e75c7)
        /go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/logger.go:40 (0x9d9ab3)
        /go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:157 (0x9a6909)
        /go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:135 (0x9a6698)
        /go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:121 (0x9d5f38)
        /go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:112 (0x9e6910)
        /go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/logger.go:52 (0x9e68fb)
        /go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/logger.go:40 (0x9d9ab3)
        /go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:157 (0x9a6909)
        /go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:135 (0x9a6698)
        /go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:121 (0x9d5f38)
        /go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/router.go:187 (0x9e87f6)
        /go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/router.go:294 (0x9e227d)
        /go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/macaron.go:220 (0x9dae4a)
        /go/src/code.gitea.io/gitea/vendor/github.com/gorilla/context/context.go:141 (0xc4104d)
        /usr/local/go/src/net/http/server.go:2007 (0x754133)
        /usr/local/go/src/net/http/server.go:2802 (0x757583)
        /usr/local/go/src/net/http/server.go:1890 (0x752f24)
        /usr/local/go/src/runtime/asm_amd64.s:1357 (0x466bd0)

**Comment by 8ctopus** [comment]
my guess is that #6230 introduced the bug

**Comment by guillep2k** [comment]
I'll take this.
