### ISSUE TITLE
Too many space between commit message and updated date on tree view.

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#8522]
<img width="1141" alt="image" src="https://user-images.githubusercontent.com/81045/66819302-58b34f80-ef71-11e9-903f-9928043cfc3c.png">

**Comment by MayMeow** [comment]
Working on it. 

![Screenshot from 2019-10-29 23-52-23](https://user-images.githubusercontent.com/3164256/67815476-5095fc80-faa7-11e9-977b-a2659a6f47a8.png)

you can check it here https://kittyverse.co/

**Comment by lunny** [comment]
Closed by #8757
