### ISSUE TITLE
OAuth2 provider "userinfo" support

### ISSUE THREAD

**Issue by carlokok** [go-gitea/gitea#8534]
Gitea has an OAuth2 provider that can be used to connect applications. ConcourseCI requires that Gitea has a "userinfo" endpoint though, which it currently does not provide. userinfo seems to be fairly simple (https://connect2id.com/products/server/docs/api/userinfo) and part of openid connect (there is a separate issue from someone else to provide that)/

**Comment by fizzyduck** [comment]
I've been trying to set up vouch-proxy [https://github.com/vouch/vouch-proxy/](url) to use Gitea as an OAuth2 provider ant it also seems to require the "userinfo" endpoint.

**Comment by sikmir** [comment]
The same problem with [Wekan](https://github.com/wekan/wekan), it also requires the "userinfo" endpoint.

**Comment by lunny** [comment]
In fact we have one https://gitea.com/api/swagger#/user/userGetCurrent , but It may not satisfied the standard.

**Comment by sikmir** [comment]
> In fact we have one https://gitea.com/api/swagger#/user/userGetCurrent , but It may not satisfied the standard.

Sample request/response:
```
>> GET /login/oauth/userinfo
Authorization: Basic <access_token>
Accept: application/json

<< HTTP/1.1 200 OK
Content-Type: application/json

{
    "sub": "248289761001",
    "name": "Jane Doe",
    "preferred_username": "j.doe",
    "email": "janedoe@example.com"
}
```

**Comment by 6543** [comment]
sub = ?!?
name = user.full_name
preferred_username = user.username
email = user.email
picture = user.avatar_url

**Comment by 6543** [comment]
I made a draft PR ... feel free to look at ...

**Comment by aaronpk** [comment]
`sub` is short for "subject" and is supposed to be a unique identifier for the user account, not necessarily something human readable. You could use an internal database ID for example.

**Comment by sikmir** [comment]
Keep it open.

**Comment by ppaulweber** [comment]
@lafriks what's the status about this issue and referenced PRs? I was trying to integrate Gitea with Concourse CI but it seems that still the missing `userinfo` endpoint in the latest `gitea` release is a showstopper for a proper OAuth integration.

**Comment by kevung** [comment]
I confirm this would be very useful to use in combination with Jupyterhub.
https://oauthenticator.readthedocs.io/en/latest/getting-started.html

**Comment by reivilibre** [comment]
Another instance where this would be useful is with setting up Grafana to use Gitea with OAuth, which also expects an OpenID-compatible 'UserInfo' endpoint.

https://grafana.com/docs/grafana/latest/auth/generic-oauth/

**Comment by lunny** [comment]
ref: https://openid.net/specs/openid-connect-core-1_0.html#UserInfo

**Comment by mcansky** [comment]
would a bounty help to get this moving ?
this would be really useful to advocate for Gitea by showing it works for a bunch more other services properly.

**Comment by 6543** [comment]
@mcansky bounty's do help, even smal one show that this is valued ...

**Comment by mcansky** [comment]
> @mcansky bounty's do help, even smal one show that this is valued ...

ok, I will organise one through https://www.bountysource.com/issues/82089047-oauth2-provider-userinfo-support ? I will check how exactly that works on the accounting side;
how is the usual "load" of the developers on the project ? are some of you all the time on it or is it mostly "on the side" ?

**Comment by 6543** [comment]
It's  all free spare time

**Comment by mcansky** [comment]
ok, let's do this :D there is now a $100 bounty on this feature; my main interest is to get OAuth2 provider features complete so that other tools can fully use Gitea as OAuth2 provider such as ConcourseCI as this is a blocking point for my company to get the pair to match as part of Git Hosting + CI/CD offerings.

**Comment by titpetric** [comment]
I added the userinfo endpoint in the PR. It isn't tested, but as long as `ctx.User` is filled out on the request, this should be it. From what I understand, the `reqSignIn` in the `/login/oauth` group definition should fill this out.

Do you have the ability to test the PR (build with `make` and test?).

**Comment by mcansky** [comment]
all right, let's see how the PR goes, and in the meantime I will get something ready to test; thanks a lot for your prompt action !

**Comment by NLH-Software** [comment]
I've needed a correct working userinfo endpoint to secure a location at my webspace with the openid authorization from gitea. So I developed a working and complete solution which checks against the valid token. I pushed it today and created a pull request.
For testing, just checkout the version from my source branch, build it (tested on arm64 and amd64) and use it on your environment.
Maybe I will add the usage of the scope later. (so an admin can select which field he requests from gitea)

Should fix this issue.

**Comment by techknowlogick** [comment]
Closing as both linked PRs are now merged. @NLH-Software if you are bountyhub you can claim the bounty.

**Comment by mcansky** [comment]
thank you all !!

**Comment by fizzyduck** [comment]
Thank you, your effort on this is much appreciated!

**Comment by ppaulweber** [comment]
Thx @NLH-Software :pray: I'll give it a try ASAP for my use case (see: https://github.com/go-gitea/gitea/issues/8534#issuecomment-661789052).

**Comment by NLH-Software** [comment]
> Thx @NLH-Software 🙏 I'll give it a try ASAP for my use case (see: [#8534 (comment)](https://github.com/go-gitea/gitea/issues/8534#issuecomment-661789052)).

If you have problems, let me know and we can find out, which configuration is needed.

**Comment by mcansky** [comment]
I tested out adding gitea as Oauth provider for a concourse ci setup with docker; I followed https://docs.gitea.io/en-us/oauth2-provider/ and https://concourse-ci.org/generic-oauth.html Unfortunately I am still getting an error :

![image](https://user-images.githubusercontent.com/148204/122642799-794f8780-d10c-11eb-8cbb-bef639079f55.png)

I used a freshly built docker image (mcansky/gitea:latest) locally. Happy to do a debug session one of these days if it can help figure out something.

**Comment by NLH-Software** [comment]
> I tested out adding gitea as Oauth provider for a concourse ci setup with docker; I followed https://docs.gitea.io/en-us/oauth2-provider/ and https://concourse-ci.org/generic-oauth.html Unfortunately I am still getting an error :
> 
> ![image](https://user-images.githubusercontent.com/148204/122642799-794f8780-d10c-11eb-8cbb-bef639079f55.png)
> 
> I used a freshly built docker image (mcansky/gitea:latest) locally. Happy to do a debug session one of these days if it can help figure out something.

Can you try https://concourse-ci.org/generic-oidc-auth.html for setup? Probably this should work. Implemented is the userinfo like in the comment from november 19 and described at https://openid.net/specs/openid-connect-core-1_0.html#UserInfo mentioned by lunny.

I tested it successfully with grafana and mod_auth_openidc for apache, so I think you must use the oidc authentication variant.
