### ISSUE TITLE
GlobalInit()] [E] Failed to initialize ORM engine: migrate: do migrate: CreateIndexes RepoUnit: pq: relation "IDX_repo_unit_S" already exists

### ISSUE THREAD

**Issue by strk** [go-gitea/gitea#854]
As of commit 94130da63a31da59207dd7c4f12aa46fde17ab5b I cannot start Gitea against the development database I've been using so far, due to this error:
```
2017/02/06 17:56:09 [I] Migration: create repo unit table and add units for all repos
2017/02/06 17:56:09 [...itea/routers/init.go:54 GlobalInit()] [E] Failed to initialize ORM engine: migrate: do migrate: CreateIndexes RepoUnit: pq: relation "IDX_repo_unit_created_unix" already exists
```

I think the call comes from here:
```
models/migrations/v16.go:       if err := sess.CreateIndexes(&repoUnit); err != nil {
```

I'm not sure why that migration is even attempted to be performed, given the DB is already at version 16:
```
=# select * from version;
 id | version 
----+---------
  1 |      16
(1 row)
```

@lunny ideas ?

**Comment by strk** [comment]
I've fixed this by dropping the `repo_unit` table. Could be I tried the repo_unit branch before...

**Comment by lunny** [comment]
yes, because you tried that PR
