### ISSUE TITLE
[remote rejected] master -> master (pre-receive hook declined) error: failed to push some refs to

### ISSUE THREAD

**Issue by KrishnaAryan** [go-gitea/gitea#8556]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

...

**Comment by guillep2k** [comment]
Could you please give us more context?

**Comment by zeripath** [comment]
It's not like the issue template doesn't ask you to give us this information. You haven't even told us what when you saw this. 

This is frankly just rude and I'm of half a mind to just close this issue immediately.
