### ISSUE TITLE
Feature request: set time tracking value for other user

### ISSUE THREAD

**Issue by camdarley** [go-gitea/gitea#8559]
## Description

Sometimes, as a project manager, I have to manually set the amount of time my developers spent on a feature.
Currently, if I add time tracking to an issue, the tracked time is set on my own user.
Would be great to be able to add a time amount for another user.
Could be either through the API: add optional user_id in the POST request when adding times to issues, or in the UI, having a user field in the time tracking popup, or both
Only repo administrator and owner could be able to set another user.
Regards.

**Comment by lunny** [comment]
I think that issue track time should be counted as assignees' not the current user.

**Comment by camdarley** [comment]
I agree, but as there can be multiple assignees on an issue we would still need an additional field to choose which assignee we need to track time of.

**Comment by 6543** [comment]
@camdarley I'll work on the times API endpoints at #9200 if you have suggestions .., let me know :)

**Comment by camdarley** [comment]
Hi @6543, sorry for my late response.
I would suggest to add a `user` optional parameter in the body of request to `/repos/{owner}/{repo}/issues/{id}/times`.
If omitted, default value is set to current user.
Also, only users with admin rights on the current repository should be allowed to use the `user` parameter.

**Comment by camdarley** [comment]
Or even simpler: add a POST option to `/repos​/{owner}​/{repo}​/times​/{user}`

**Comment by 6543** [comment]
@camdarley it is already in #9200 (as optional parameter in the body of reqest)
dont like to add to mouch api endpoints for a single option

more info: [here](https://github.com/go-gitea/gitea/pull/9200/files#diff-60c76f8155c8138ba14d1ef937a53503R97-R101)

**Comment by zeripath** [comment]
Or just use Sudo?

**Comment by 6543** [comment]
sudo can only use the admin

but the optinal parameter allow allow also repoOwners to set ... thoungt this is a good way to go ...

-> but yes **sudo API** prevent us from adding mouch code usw ...
