### ISSUE TITLE
404 when regenerating oauth2 secret

### ISSUE THREAD

**Issue by Martmists-GH** [go-gitea/gitea#8568]
- Gitea version (or commit ref): Latest
- Git version: Latest
- Operating system: Arch Linux x64
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description

I am unable to regenerate the secret for an Oauth2 application.

## Screenshots

![image](https://user-images.githubusercontent.com/16361449/67054960-93baac00-f146-11e9-828d-3f0c05b94347.png)

after clicking regenerate secret:

![image](https://user-images.githubusercontent.com/16361449/67054982-a7661280-f146-11e9-9a4c-b8bfd811f74f.png)

**Comment by jolheiser** [comment]
Can you please provide your logs around the time of a 404?
