### ISSUE TITLE
PR Split view missing line break indicator

### ISSUE THREAD

**Issue by marcsiq** [go-gitea/gitea#8574]
- Gitea version (or commit ref): 1.10-rc1
- Git version:
- Operating system: ubuntu
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

https://try.gitea.io/marcs/bug_test/pulls/3/files?style=split&whitespace=

Pull request Split view does not show line jumps.

As you can see in the link above I edited the first and the last line of the file but when reviewing it on Split view it does not show the line break from line 4 to line 114 as it is shown in unified view.

**Comment by lunny** [comment]
Is this still a problem?

**Comment by Marcsiq2** [comment]
We're running 1.10.1 and it's still a problem, however I've seen that this has been fixed in [try gitea](https://try.gitea.io/marcs/bug_test/pulls/3/files?style=split&whitespace= ) so it won't be a problem from 1.11 I imagine.

Thank you very much!
