### ISSUE TITLE
Can't create PR via Gitea UI on forked repository

### ISSUE THREAD

**Issue by kklocek** [go-gitea/gitea#8576]
- Gitea version (or commit ref): 1.9.3
- Git version: 2.18.0.windows.1
- Operating system: Windows 10
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist: Not relevant

## Description

I have repository A and B.
B is a fork of repository A.
When on B repository page I clicked "pull request" I am redirected to A repository page, where I can merge my branch into repository A, but I just want to merge my branch into repository B.
It works when I put Pull Request URL by hand.

## Screenshots

![gitea](https://user-images.githubusercontent.com/9058693/67081606-c214a780-f197-11e9-8f13-bc76fe1a4472.png)

**Comment by zeripath** [comment]
So if this is urgent, it is possible to create a pr you may just have to do it manually. The URL would be:

/Owner/Reponame/compare/base-branch...Username:head-branch

The UI though doesn't currently expose this

**Comment by kklocek** [comment]
> 

> 
> 
> So if this is urgent, it is possible to create a pr you may just have to do it manually. The URL would be:
> 
> /Owner/Reponame/compare/base-branch...Username:head-branch
> 
> The UI though doesn't currently expose this

Thank you for that, I make PR manually, but I think it's bug all in all in UI.

**Comment by zeripath** [comment]
Agreed we need to improve it

**Comment by blueworrybear** [comment]
@zeripath @lunny @kklocek 

Hi, I try to fix this issue by redirecting to `/headUser/currentRepo/compare` instead of `/baseRepoUser/currentRepo/compare` when user click `create pull request`.

The dropdown menu now will show branches from both current repository and base repository.

However, I am not sure whether to merge this update to v1.9 branch or master. Need some suggestion... 🤔 

![demo](https://i.imgur.com/fuhHydA.png)

**Comment by lunny** [comment]
@blueworrybear Please send a PR to master at first.

**Comment by kklocek** [comment]
Thank you again Gitea team!
