### ISSUE TITLE
table alignment not rendered properly from README.md

### ISSUE THREAD

**Issue by dmatetelki** [go-gitea/gitea#8577]
Writing a table in README.md generates a proper HTML but the alignment="center" is not rendered properly.

Table alignment is correct in the issue.

Is it a CSS thing? (I'm not a web developer)
gitea-1.9.0

```
| a11111    | b1111    | c1111    |
|-----------|:--------:|---------:|
| a1        |    b1    |       c2 |
| a3        |    b2    |       c3 |

```

Correct here (note: it's text):

| a11111    | b1111    | c1111    |
|-----------|:--------:|---------:|
| a1        |    b1    |       c2 |
| a3        |    b2    |       c3 |

Not from README.md (note it's included image): 

 ![misaligned](https://user-images.githubusercontent.com/640615/67189931-63e20180-f3ef-11e9-87d8-c697c0523ad9.png)

**Comment by cipherboy** [comment]
@lunny I think this issue can be closed. I can't reproduce on a recent build:

![Screenshot from 2020-07-09 17-43-35](https://user-images.githubusercontent.com/914030/87093778-bd06f500-c20b-11ea-86b2-af2c381d6607.png)
