### ISSUE TITLE
[Bug] API return 500 when repository is empty

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#8582]
Came Up in https://gitea.com/gitnex/GitNex/issues/154

- Gitea version (or commit ref): 1.9.4 & 1.10.0-rc1
- Can you reproduce the bug at https://try.gitea.io: at gitea.com ...

API call should not return 500 as HTTP status!

query: `https://code.obermui.de/api/v1/repos/6543/empty/contents`
responce: `{"message":"object does not exist [id: master, rel_path: ]","url":"https://code.obermui.de/api/swagger"}`  + http-code: 500

**Comment by lunny** [comment]
May related to https://github.com/go-gitea/gitea/pull/8541

**Comment by 6543** [comment]
I dont think so - 1.9.4  has same problem

**Comment by jonasfranz** [comment]
Can be reproduced at try.gitea.io: https://try.gitea.io/api/v1/repos/JonasFranzDEV/empty/contents
