### ISSUE TITLE
Not able to build master branch following instructions in documentation

### ISSUE THREAD

**Issue by hiteshnayak305** [go-gitea/gitea#8605]
- Gitea version (or commit ref): master
- Git version: git version 2.23.0.windows.1
- Operating system:windows 10
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:https://gist.github.com/hiteshnayak305/069ddadfa9bfb1ec8dc2630a81c1a84f

## Description
I am not able to build master branch trying to build after issue https://github.com/go-gitea/gitea/issues/8603 resolved.

steps followed 
go get -d -u code.gitea.io/gitea
cd "$GOPATH/src/code.gitea.io/gitea"
TAGS="bindata sqlite sqlite_unlock_notify" make generate build
...

**Comment by hiteshnayak305** [comment]
It is found that " around tags is not required. Can it be corrected in documentation. It is confusing.
`TAGS="bindata sqlite sqlite_unlock_notify"`

**Comment by zeripath** [comment]
Heya! Sorry you found it confusing. Which document were you looking at and where?

Glad you got it building in the end.

**Comment by hiteshnayak305** [comment]
Actually I am still not able to build. Is Dockerfile compatible building on windows system?

Following places flags are wrapped with double quotes which is causing error in cmd
/.bat file

https://docs.gitea.io/en-us/install-from-source/
![image](https://user-images.githubusercontent.com/22023863/67190016-d4e3e200-f40c-11e9-95a5-5bb3ecfc3fe2.png)

https://docs.gitea.io/en-us/hacking-on-gitea/
![image](https://user-images.githubusercontent.com/22023863/67190064-eaf1a280-f40c-11e9-8d99-12d38c9b3112.png)

**Comment by hiteshnayak305** [comment]
I am able to build now. Please do the needful to documentation and close the issue.

One thing i want to know my build .exe is only 60 mb but released versions are around 100mb . why?

**Comment by zeripath** [comment]
Ah you're building on Windows. Sigh. 

Ok those docs expect you to be working in a reasonable shell which cmd is not. Powershell might work otherwise you might need a cygwin or other such environment.

I'm gonna defer to @lunny and his expertise here. 

You need to set the TAGS as an environment variable before running make - that's what the TAGS="..." is trying to do.

I think trying to build a docker on windows might fail though - I don't know if xgo can cross-compile from Windows.

**Comment by hiteshnayak305** [comment]
Successfully build from cmd.
```sh
@echo on
go get -d code.gitea.io/gitea
C:
cd "%GOPATH%/src/code.gitea.io/gitea"

set TAGS=bindata sqlite sqlite_unlock_notify
make clean
make generate
make build
```

**Comment by hiteshnayak305** [comment]
One thing i want to know my build .exe is only 60 mb but released versions are around 100mb . why?
Is there any problem in my build?

**Comment by zeripath** [comment]
Are you sure you shouldn't have `"` around those TAGS?

e.g.

```bat
set TAGS="bindata sqlite sqlite_unlock_notify"
```

If you haven't embedded SQLite into the binary that could explain why it is 40Mb smaller.

**Comment by hiteshnayak305** [comment]
`GO111MODULE=on` go build -mod=vendor -v  -tags '"bindata sqlite sqlite_unlock_notify"' `-ldfl......`

is invalid statement giving error as :
# code.gitea.io/gitea
usage: link [options] main.o
  -B note
        add an ELF NT_GNU_BUILD_ID note when using ELF
  -E entry
        set entry symbol name
  -H type
        set header type

No proper usage of statement
ref:attached log

**Comment by hiteshnayak305** [comment]
If you haven't embedded SQLite into the binary that could explain why it is 40Mb smaller. ?

**Comment by guillep2k** [comment]
> 
> 
> Are you sure you shouldn't have `"` around those TAGS?
> 
> e.g.
> 
> ```batchfile
> set TAGS="bindata sqlite sqlite_unlock_notify"
> ```
> 
> If you haven't embedded SQLite into the binary that could explain why it is 40Mb smaller.

In Windows Command Prompt, the quotes become part of the variable:

```
C:\> set HELLO="HELLO HOW ARE YOU?"
C:\> set | findstr HELLO
HELLO="HELLO HOW ARE YOU?"

C:\> set HELLO=HELLO HOW ARE YOU?
C:\> set | findstr HELLO
HELLO=HELLO HOW ARE YOU?
```

Yes, it's very frustrating. Writing "proper" batch files in Windows is a dark art full of caveats, workarounds and lots of toads 🐸. I think git-bash should be used to build under Windows (although I didn't tried).

**Comment by jolheiser** [comment]
When I develop Gitea on Windows, I use Git Bash, which so far has allowed me to use the same commands as our documentation.

**Comment by hiteshnayak305** [comment]
Is embedding SQLite into binary necessary. My 60mb binary working fine till now

**Comment by jolheiser** [comment]
Embedding SQLite (library) is only necessary if you plan on using SQLite.  
According to your original issue you use it, so it will need to be embedded.

**Comment by hiteshnayak305** [comment]
But how come it is working fine with my old installation?

**Comment by jolheiser** [comment]
> Successfully build from cmd.
> 
> 
> ```shell
> @echo on
> go get -d code.gitea.io/gitea
> C:
> cd "%GOPATH%/src/code.gitea.io/gitea"
> 
> set TAGS=bindata sqlite sqlite_unlock_notify
> make clean
> make generate
> make build
> ```

Looks like you embedded SQLite

**Comment by hiteshnayak305** [comment]
But i got 60mb binary from above build process

**Comment by jolheiser** [comment]
When I build Gitea locally on Windows, mine is also ~60mb.  
My guess is when it's built with xgo vs natively the size is larger for some reason.
