### ISSUE TITLE
Is it possible to add an armhf docker image for raspberry pi?

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#8606]

**Comment by sapk** [comment]
Hi, which version of RPi do you use ?

**Comment by bokugaoyori** [comment]
My apologies for the delayed response. I am using Raspberry Pi 3 B+ model which only officially supports the 32-bit arm architecture (armhf).

**Comment by ZetaPhoenix** [comment]
This is a duplicate request of #531. Any chance we can get this building soon?

**Comment by ZetaPhoenix** [comment]
Still relevant as last I checked there is no armhf version.
