### ISSUE TITLE
when the sub issue summit the duplicate emoji, then emoji panel can be removed.

### ISSUE THREAD

**Issue by palytoxin** [go-gitea/gitea#8610]
- Gitea version (or commit ref): v1.11.0-dev-56-g28f60bb5c
- Git version: 2.23.0
- Operating system:macOS 10.15 (19A602)
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL) https://try.gitea.io/palytoxin/repo1/issues/1#issuecomment-23696
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

...

## Screenshots
![Screen Recording 2019-10-21 at 2 52 43 PM](https://user-images.githubusercontent.com/1829328/67183142-59d1fa00-f413-11e9-974b-2614818949ad.gif)

I created PR [https://github.com/go-gitea/gitea/pull/8609](fix pr)

**Comment by zeripath** [comment]
Fixed by #8609
