### ISSUE TITLE
PANIC on reset/recover password

### ISSUE THREAD

**Issue by echodreamz** [go-gitea/gitea#8625]
- Gitea version (or commit ref): 1.10.0-rc1
- Git version: 2.23.0
- Operating system: CentOS 7
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [] Not relevant
- Log gist:
`2019/10/21 23:22:40 ...les/context/panic.go:35:1() [E] PANIC:: regexp: Compile("][ !\"#$%&'()*+,./:;<=>?@\\\\^_{|}~`-"): error parsing regexp: missing closing ]: `[ !"#$%&'()*+,./:;<=>?@\\^_{|}~`-`
	/usr/local/go/src/regexp/regexp.go:311 (0x6bdaf1)
	/go/src/code.gitea.io/gitea/modules/password/password.go:31 (0x10a2214)
	/usr/local/go/src/sync/once.go:66 (0x484b02)
	/usr/local/go/src/sync/once.go:57 (0x10a1c3c)
	/go/src/code.gitea.io/gitea/modules/password/password.go:28 (0x10a1c0d)
	/go/src/code.gitea.io/gitea/modules/password/password.go:46 (0x10a1ca2)
	/go/src/code.gitea.io/gitea/routers/user/auth.go:1338 (0x131e000)
	/usr/local/go/src/reflect/value.go:460 (0x4977d5)
	/usr/local/go/src/reflect/value.go:321 (0x496f93)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:177 (0x9a6bf9)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:137 (0x9a65a9)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:121 (0x9d5f38)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:112 (0x112eb11)
	/go/src/code.gitea.io/gitea/modules/context/panic.go:39 (0x112eafd)
	/usr/local/go/src/reflect/value.go:460 (0x4977d5)
	/usr/local/go/src/reflect/value.go:321 (0x496f93)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:177 (0x9a6bf9)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:137 (0x9a65a9)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:121 (0x9d5f38)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:112 (0xaa35f5)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/session/session.go:192 (0xaa35e0)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:79 (0x9d5de0)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:157 (0x9a6909)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:135 (0x9a6698)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:121 (0x9d5f38)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:112 (0x13b5cba)
	/go/src/code.gitea.io/gitea/modules/gzip/gzip.go:139 (0x13b5cad)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:79 (0x9d5de0)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:157 (0x9a6909)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:135 (0x9a6698)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:121 (0x9d5f38)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:112 (0x9e75d9)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/recovery.go:161 (0x9e75c7)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/logger.go:40 (0x9d9ab3)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:157 (0x9a6909)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:135 (0x9a6698)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:121 (0x9d5f38)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:112 (0x9e6910)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/logger.go:52 (0x9e68fb)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/logger.go:40 (0x9d9ab3)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:157 (0x9a6909)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:135 (0x9a6698)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:121 (0x9d5f38)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/router.go:187 (0x9e87f6)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/router.go:294 (0x9e227d)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/macaron.go:220 (0x9dae4a)
	/go/src/code.gitea.io/gitea/vendor/github.com/gorilla/context/context.go:141 (0xc4104d)
	/usr/local/go/src/net/http/server.go:2007 (0x754133)
	/usr/local/go/src/net/http/server.go:2802 (0x757583)
	/usr/local/go/src/net/http/server.go:1890 (0x752f24)
	/usr/local/go/src/runtime/asm_amd64.s:1357 (0x466bd0)
`

## Description
Received a 500 error after clicking the "recover" button when resetting a password. I did request another password reset, redid it a few times and never got the error again, however, reporting anyways just in case.

**Comment by guillep2k** [comment]
Thank you for reporting. This has been fixed by #8524.

**Comment by echodreamz** [comment]
> Thank you for reporting. This has been fixed by #8524.

Thank you! Guess I should have did a bit better searching :)
