### ISSUE TITLE
clone failed, permission denied when using ssh 

### ISSUE THREAD

**Issue by zhangxiang36** [go-gitea/gitea#8628]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x ] No
  - [ ] Not relevant
- Log gist:

## Description

I installed gitea on my windows computer as git server,and used the option START_SSH_SERVER = true in app.ini. 
Clone, push action are fine when using http, but not ssh. 

I want to use ssh to clone or push branch. 
I add the pub_key through the web UI.

when I run the command below
$ git clone git@192.168.2.6:xiang.zhang/rEvent2.git

I got the message :
Cloning into 'rEvent2'...
git@192.168.2.6: Permission denied (publickey).
fatal: Could not read from remote repository.

here is the debug info:

$ ssh -vT git@192.168.2.6
OpenSSH_7.6p1, OpenSSL 1.0.2n  7 Dec 2017
debug1: Reading configuration data /c/Users/xiang.zhang/.ssh/config
debug1: /c/Users/xiang.zhang/.ssh/config line 2: Applying options for 192.168.2.6
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: Connecting to 192.168.2.6 [192.168.2.6] port 22.
debug1: Connection established.
debug1: identity file C:/Users/xiang.zhang/.ssh/id_rsa_gitea type 0
debug1: key_load_public: No such file or directory
debug1: identity file C:/Users/xiang.zhang/.ssh/id_rsa_gitea-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_7.6
debug1: Remote protocol version 2.0, remote software version SSHBlackbox.10
debug1: no match: SSHBlackbox.10
debug1: Authenticating to 192.168.2.6:22 as 'git'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: diffie-hellman-group14-sha1
debug1: kex: host key algorithm: ssh-rsa
debug1: kex: server->client cipher: aes128-cbc MAC: hmac-sha2-256 compression: none
debug1: kex: client->server cipher: aes128-cbc MAC: hmac-sha2-256 compression: none
debug1: sending SSH2_MSG_KEXDH_INIT
debug1: expecting SSH2_MSG_KEXDH_REPLY
debug1: Server host key: ssh-rsa SHA256:8qlkcf/TChPWY8ZKQJK5rcaEtu1U5Hibi67ML5Qgrag
The authenticity of host '192.168.2.6 (192.168.2.6)' can't be established.
RSA key fingerprint is SHA256:8qlkcf/TChPWY8ZKQJK5rcaEtu1U5Hibi67ML5Qgrag.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '192.168.2.6' (RSA) to the list of known hosts.
debug1: rekey after 4294967296 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey after 4294967296 blocks
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey
debug1: Next authentication method: publickey
debug1: Offering public key: RSA SHA256:OfMMCluE0ztfUFrI0vFsccbODPoPZIeDHUI76MPJsZk C:/Users/xiang.zhang/.ssh/id_rsa_gitea
debug1: Authentications that can continue: publickey
debug1: No more authentication methods to try.
git@192.168.2.6: Permission denied (publickey).

I don't know what problem is. Thanks for your help.

**Comment by zhangxiang36** [comment]
Here's my app.ini content:

APP_NAME = DBNBC git service
RUN_USER = git
RUN_MODE = dev

[oauth2]
JWT_SECRET = waIUyFjQJj5i6T0YKkUsaezhhP02vXHFK52zKMyryi0

[security]
INTERNAL_TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYmYiOjE1NzE2NDAzMzl9.LXZLdxJF5UQe1qhDaOuH8m21xxHOO4mgdEIoq6Qu9mo
INSTALL_LOCK   = true
SECRET_KEY     = zWtMmdTN7ThlliyJn5RQjfsqNTVJGcK4bUJAPLlKLenvqh99SLa4kBMeP8vjnren

[database]
DB_TYPE  = mysql
HOST     = 127.0.0.1:3306
NAME     = gitea
USER     = root
PASSWD   = zx198363
SSL_MODE = disable
CHARSET  = utf8mb4
PATH     = D:\gitea\data\gitea.db

[repository]
ROOT = C:/Users/xiang.zhang/gitea-repositories

[server]
SSH_DOMAIN       = 192.168.2.6
DOMAIN           = 192.168.2.6
HTTP_PORT        = 3000
ROOT_URL         = http://192.168.2.6:3000/
DISABLE_SSH      = false
SSH_PORT         = 22
LFS_START_SERVER = true
LFS_CONTENT_PATH = D:/gitea/data/lfs
LFS_JWT_SECRET   = fWEWn94rLgFGSvZiC-oDon_E0OirF6qPpJ0Y7mGsOAU
OFFLINE_MODE     = false
START_SSH_SERVER = true 
[mailer]
ENABLED = false

[service]
REGISTER_EMAIL_CONFIRM            = false
ENABLE_NOTIFY_MAIL                = false
DISABLE_REGISTRATION              = false
ALLOW_ONLY_EXTERNAL_REGISTRATION  = false
ENABLE_CAPTCHA                    = false
REQUIRE_SIGNIN_VIEW               = false
DEFAULT_KEEP_EMAIL_PRIVATE        = false
DEFAULT_ALLOW_CREATE_ORGANIZATION = true
DEFAULT_ENABLE_TIMETRACKING       = true
NO_REPLY_ADDRESS                  = noreply.example.org

[picture]
DISABLE_GRAVATAR        = false
ENABLE_FEDERATED_AVATAR = true

[openid]
ENABLE_OPENID_SIGNIN = true
ENABLE_OPENID_SIGNUP = true

[session]
PROVIDER = file

[log]
MODE      = file
LEVEL     = info
ROOT_PATH = D:/gitea/log

**Comment by zeripath** [comment]
You have START_SSH_SERVER set but the port set to 22. Are you sure that Gitea is listening on that port and that you don't have a different SSH server eg. OpenSSH listening on that port? Non-privileged servers are not usually allowed to open port 22 (even on windows)

On startup Gitea should log which port it is listening on.
