### ISSUE TITLE
Unable to resolve pull request, when a file with a conflict is modified later to the same content as on the destination

### ISSUE THREAD

**Issue by bluecatchbird** [go-gitea/gitea#8630]
- Gitea version (or commit ref): 1.9.4 
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes: https://try.gitea.io/blubb1/blubb/pulls/1
  - [ ] No
  - [ ] Not relevant

## Description
Its not possible to resolve a pull request, when a file with a conflict is modified later to the same content as on the destination branch.

## Screenshots
![Screenshot_2019-10-22 blubb](https://user-images.githubusercontent.com/11939569/67286854-64a39200-f4da-11e9-940a-0e6d624fa068.png)

**Comment by guillep2k** [comment]
Resolving conflicts through the web interface is not currently supported. Conflicts should be resolved in a local copy and pushed back to your PR.

If this is a feature request, it would be cool to have this, of course! But this would be a duplicate of #5158

**Comment by zeripath** [comment]
I think this is describing a situation whereby there is actually no conflict but Gitea incorrectly there is.

**Comment by bluecatchbird** [comment]
@zeripath you are right! there is no conflict, but gitea shows one.

**Comment by zeripath** [comment]
Heya could you test again on master I think we may have inadvertently resolved this.
