### ISSUE TITLE
New Issue Missing Milestone Comment

### ISSUE THREAD

**Issue by jaqra** [go-gitea/gitea#8644]
gitea does not create milestone comment on new issue
I also tried it on try.gitea.io

https://try.gitea.io/jaqra/Foo/issues/4

**Comment by jaqra** [comment]
@lunny

**Comment by lunny** [comment]
@jaqra that maybe a bug.

**Comment by jaqra** [comment]
@lunny look at this https://github.com/go-gitea/gitea/pull/8221/files

before that `changeMilestoneAssign` creates comment with `createMilestoneComment`

after that there is no call for `changeMilestoneAssign`

canges is https://github.com/go-gitea/gitea/pull/8221/files#diff-d5eea3b2c0d4c92d62e12b34eb8da2c0L1122-R1122
