### ISSUE TITLE
Pull request 500 error

### ISSUE THREAD

**Issue by bkodre** [go-gitea/gitea#8646]
- Gitea version: 1.9.4
- Git version: 2.22.0
- Operating system: ubuntu 18.04
- Database :
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description
I get 500 error on creating new pull request.  
Pre-push file does not exist on gitea server.

Logs:
```
2019/10/23 14:27:44 routers/repo/pull.go:751:CompareAndPullRequestPost() [E] PushToBaseRepo: Push: exit status 1 - \nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/pre-push.\n
	error: failed to push some refs to '/data/git/repositories/company/product.git'
```

**Comment by zeripath** [comment]
Presumably "company/product.git" is a forked repo -  I would take a look at the original base repos git.

**Comment by bkodre** [comment]
Nope this repo is not a fork. I get this error when i try to create pull request to merge changes from feauture branch to master branch on original repo in gitea.

**Comment by zeripath** [comment]
So it's a very odd error message I think there must be something in your git config somewhere that is adding git hooks to temporary repositories.

**Comment by bkodre** [comment]
Config file in this repo contains:
        
    [core]
	repositoryformatversion = 0
	filemode = false
	bare = true
	symlinks = false
	ignorecase = false

**Comment by zeripath** [comment]
It's won't be that repo that has the weird config. It's the newly created temporary repo that you don't see. We almost always create a temporary repo with shared object data to prevent the temp repo from destroying the real repo.

Something is telling git to create repositories with git-lfs hooks when git-lfs is not installed.

**Comment by lunny** [comment]
Since you enabled LFS, gitea will check if your have installed git lfs when start. But why it reported error when running.

**Comment by bkodre** [comment]
Are there some other config files that can affect this repo?

**Comment by bkodre** [comment]
So global git config could do this?

**Comment by bkodre** [comment]
Do we need to have git lfs client instaled on server?

**Comment by zeripath** [comment]
You shouldn't need git-lfs but if you have previously installed and removed git-lfs you need to ensure that it's been removed completely.

I would just try creating a git repo on the server and see if that gets lfs hooks added - if it does you haven't removed git-lfs completely

**Comment by bkodre** [comment]
No i did't have git lfs client installed.

**Comment by bkodre** [comment]
I created new repo and two hooks are created pre-receive and post-receive

pre-receive:

    #!/usr/bin/env bash
    data=$(cat)
    exitcodes=""
    hookname=$(basename $0)
    GIT_DIR=${GIT_DIR:-$(dirname $0)}

    for hook in ${GIT_DIR}/hooks/${hookname}.d/*; do
    test -x "${hook}" || continue
    echo "${data}" | "${hook}"
    exitcodes="${exitcodes} $?"
    done

    for i in ${exitcodes}; do
    [ ${i} -eq 0 ] || exit ${i}
    done


post-receive:

     #!/usr/bin/env bash
     data=$(cat)
     exitcodes=""
     hookname=$(basename $0)
     GIT_DIR=${GIT_DIR:-$(dirname $0)}

     for hook in ${GIT_DIR}/hooks/${hookname}.d/*; do
     test -x "${hook}" || continue
     echo "${data}" | "${hook}"
     exitcodes="${exitcodes} $?"
     done

     for i in ${exitcodes}; do
     [ ${i} -eq 0 ] || exit ${i}
     done

**Comment by guillep2k** [comment]
@bkodre Those are the "parent" hooks. They execute their "child" hooks in a directory which is named after the hook with `.d` at the end. In my test repo:

```
$ pwd
/home/giteatest/gitea-repositories/test-user/test-repo.git/hooks

$ find
.
./applypatch-msg.sample
./commit-msg.sample
./post-update.sample
./pre-applypatch.sample
./pre-commit.sample
./pre-push.sample
./pre-receive.sample
./update.sample
./fsmonitor-watchman.sample
./pre-rebase.sample
./prepare-commit-msg.sample
./pre-receive.d
./pre-receive.d/gitea          <-- a child hook
./pre-receive                  <-- the parent hook
./update.d
./update.d/gitea
./update
./post-receive.d
./post-receive.d/gitea         <-- a child hook
./post-receive                 <-- the parent hook
```

**Comment by zeripath** [comment]
I would double check your Gitea repositories don't have the LFS hooks given this finding

**Comment by bkodre** [comment]
I checked all hooks (also child hooks) and i found lfs hook in one of the. Removal of this lfs hook solved pull request error.
