### ISSUE TITLE
UserSignIn: PAM not supported

### ISSUE THREAD

**Issue by JKingweb** [go-gitea/gitea#865]
- Gitea version (or commit ref): 1.0.1
- Git version: 2.7.4
- Operating system: Linux (Ubuntu 16.04)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:
```
2017/02/07 20:52:13 [...routers/user/auth.go:117 SignInPost()] [E] UserSignIn: PAM not supported
2017/02/07 20:52:19 [...s/context/context.go:168 func1()] [E] UserSignIn: PAM not supported
2017/02/07 20:52:19 [...routers/repo/http.go:111 HTTP()] [E] UserSignIn error: %v: PAM not supported
```
## Description

When I try to use PAM to sign in with a previously created user, I receive an HTTP 500 error and the above lines appear in the Gitea log (debug logging shows only sessions IDs and CSRF tokens in addition). My PAM setup works for several other services, including Gogs. Running Gitea as root has no effect, nor does starting from a fresh installation. However, a colleague of mine with a practically identical installation has no issues at all.

**Comment by lunny** [comment]
Do you build Gitea with `tags=pam` ?

**Comment by JKingweb** [comment]
I downloaded the pre-built binary (for amd64).  PAM is listed as an authentication source in the admin panel, if that means anything.

Nothing is printed to /var/log/auth.log upon my attempts.

**Comment by lunny** [comment]
I need to test for confirm that.

**Comment by tboerger** [comment]
The prebuilt binaries are *not* built with the PAM tag, if you really want to use PAM you have to build it from source, sorry for that.

**Comment by JKingweb** [comment]
Ah, thanks for the clarification, and sorry to waste your time.

I think I'll stick with Gogs in that case, since I don't have to compile that myself to get PAM.  I'll definitely keep an eye on Gitea, though. :)

**Comment by tboerger** [comment]
We got another issue open where we plan to provide different "flavors" of gitea to enable different build tags. Maybe we can add one flavor with PAM support, but that needs to be tested properly.
