### ISSUE TITLE
error msg about new file and upload file

### ISSUE THREAD

**Issue by shenlijun** [go-gitea/gitea#8664]
- Gitea version (or commit ref): 1.9.4
- Git version: 2.23.0
- Operating system: Windows Server 2019 Datacenter
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description

1. failed to create new file;
2. upload file to repository got error msg, but upload seccessfully

## Screenshots

![1](https://user-images.githubusercontent.com/8860591/67462919-078f1400-f673-11e9-85d5-53988d6233e2.png)
![2](https://user-images.githubusercontent.com/8860591/67462927-09f16e00-f673-11e9-8bc8-3ecd34bfc475.png)

**Comment by zeripath** [comment]
Do you have antivirus running?

**Comment by shenlijun** [comment]
> Do you have antivirus running?

And same error in a Server 2016 VM without antivirus

**Comment by shenlijun** [comment]
I found it,  these errors just with git in MSYS2. use normal git for windows works fine.

**Comment by shenlijun** [comment]
I found it, create errors just with git in MSYS2. use normal git for windows works fine.
but same error when upload

**Comment by zeripath** [comment]
I'm closing this issue as it relates to an extremely old version of gitea and there have been no reports since October 2019.
