### ISSUE TITLE
Can't upload files on try.gitea.io

### ISSUE THREAD

**Issue by bobemoe** [go-gitea/gitea#8666]
Gitea Version: 1.11.0+dev-87-g3c63c3ace

When attempting to upload csv, txt, xls, pdf or gz files to a comment I get the error "You can not upload files of this type".

The only ones I've got it to work with so far are png, jpg and zip.

**Comment by lunny** [comment]
This is a configuration problem.

**Comment by warnat** [comment]
Don't rely on try.gitea.io  
Set up your own server and set all configurations like you need.
It's one program, isn't it ?

**Comment by bobemoe** [comment]
@warnat I do have local instances, but it's nice to be able to provide a publicly accessible example when reporting bugs.
