### ISSUE TITLE
Can't download CSV attachment (just opens in browser)

### ISSUE THREAD

**Issue by bobemoe** [go-gitea/gitea#8667]
- Gitea version (or commit ref): 1.11.0+dev-39-g7c4c01c0f
- Git version: 2.11.0
- Operating system: Devuan2
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
Blocked by #8666 

## Description

I'm trying to attach a CSV file to a comment but other users are having trouble downloading it to open in excel. It looks like its opened directly as text in the browser, and there is no way to download it with the original filename. (I can right click download it with the UUID filename but that has lost the .csv extension and confuses some users)

**Comment by bobemoe** [comment]
Maybe there should be a link to download as well as a link to display/render?  https://github.com/go-gitea/gitea/issues/6089 is displaying the attachments better, maybe this could included there?

**Comment by bobemoe** [comment]
Could well be missing that header. You wouldn't want it on all file types though, like images.. so would we define a list, or leave it up to the end user by provided a link for both?

**Comment by guillep2k** [comment]
I agree with @silverwind about the missing [Content-Disposition header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition).

Regarding inline content (e.g. images) that get a UUID for file name, maybe the following will work without losing its inline property:

```
Content-Disposition: inline; filename="...."
```

It's a valid value, but I don't know how many browsers pick that up.

**Comment by silverwind** [comment]
I don't think `inline` with filename will work. Browsers will navigate to the source URL and any save functionality will use the filename from the URL supposedly. I don't see much of an issue triggering downloads for everything, at least filenames can be preserved that way.

**Comment by guillep2k** [comment]
> 
> 
> I don't think `inline` with filename will work. Browsers will navigate to the source URL and any subsequent save functionality will use the filename from the URL supposedly. I don't see much of an issue triggering downloads for everything, at least filenames can be preserved that way.

I've just tested with a quick `.htaccess` and it works better than I anticipated. It doesn't change the URL (it shouldn't), but honors the header by using the chosen file name in the _save as_ dialog:

![image](https://user-images.githubusercontent.com/18600385/67589945-138cdb80-f730-11e9-9655-4af4b58cad98.png)

My crude `.htaccess`:

```
<Files bird.jpg>
    Header add Content-Disposition "inline; filename=\"dog.jpg\""
</Files>
```

So, for files with an UUID as a name, it could be useful, especially if they are inline.

I've also tested with the picture embedded in a page (which is what the inline keyword is for):

![image](https://user-images.githubusercontent.com/18600385/67590504-9a8e8380-f731-11e9-9078-ea05cf5f0ade.png)


```
<!DOCTYPE html>
<html>
<head>
        <title>Bird picture</title>
</head>
<body>
        <p>Here's the inline picture of a bird:</p>
        <p><img src="bird.jpg"></p>
</body>
</html>
```

It works fine with the versions I've got in my PC of Firefox, Chrome, Edge and even IE.

**Comment by bauermarkus** [comment]
Hey
I have the same issue with an ".eml" file

**Comment by silverwind** [comment]
I think it can be solved it via browser settings, for example in Firefox under Preferences - Applications, there should be an entry for the specific type. At least in 1.18, gitea will no longe force the browser to download for certain file types, like it did before.
