### ISSUE TITLE
Notification in PR: too many files changed in this diff

### ISSUE THREAD

**Issue by taai** [go-gitea/gitea#8668]
- Gitea version (or commit ref):  1.10.0+dev-427-gf9aba9ba0
- Git version: 2.23.0
- Operating system: Debian
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant

## Description
I have a PR with 126 changed files, but I can't review the changes, because only 100 files are being shown in "Files Changed" tab. And at the bottom of the page there is a notification ```Some files were not shown because too many files changed in this diff```
At least I would like to see the list of changed files, if showing the contents of all the files is too much to display...

Also when clicked on button "Show Diff Stats", the list of files was not scrollable, because of CSS ```.ui.sticky.fixed: position: fixed;```.
...

## Screenshots

![image](https://user-images.githubusercontent.com/90734/67478466-ce4fa780-f664-11e9-8ace-c4892bc7d6a9.png)

...and at the bottom of the page
![image](https://user-images.githubusercontent.com/90734/67478508-e3c4d180-f664-11e9-9ef2-83dda4b4345d.png)

**Comment by lunny** [comment]
you can change 100 on app.ini

**Comment by taai** [comment]
@lunny Thank you, it works! I should have RTFM. 😄  What about the "Show Diff Stats" button and the list of files? Should I better open a new issue?

For anyone who reads this in the future, now I use these settings in my ```app.ini```:
```[git]
MAX_GIT_DIFF_LINES = 1000
MAX_GIT_DIFF_FILES = 1000
```

**Comment by taai** [comment]
@lunny Oh, cool, it is fixed AND there are new features ("Download Patch File" and "Download Diff File") in version 1.11.0+dev-87-g3c63c3ace! 👍
