### ISSUE TITLE
[note] Store kind of service identifyed by url in DB

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#8672]
If we had a table to look up for example "https://framagit.org" as gitlab instance ... "https://code.gitea-instance.com" as gitea ...

 * We could format issues from this websites in markdown ...
 * or later cross reverence betwen gitea instances [federation]
 * at migration detect gitlab instaces and als migrate issues etc in future
 * or federated features in general could use this

**Comment by guillep2k** [comment]
If I understand you correctly, you say that for each issue/pr/comment we can have some associated data in a different table or column which contains pre-processed metadata related to the message? Similarly to what we are doing for mentions in `issue_user.is_mentioned`, for example?

**Comment by 6543** [comment]
no ... I'll try to explane it later in short & simple

**Comment by 6543** [comment]
For https://docs.gitea.io/en-us/migrations-interfaces/ the platform kind is writen in code ... can we detect this with a function and cache it ...

**Comment by lunny** [comment]
@6543 we have store the URL on repository when migrated a repository from external URL.

**Comment by 6543** [comment]
I'll close this because service identifyer is done by '#'

as proposed in #9084
