### ISSUE TITLE
Error 500: Heatmap and Repo List Not Loading

### ISSUE THREAD

**Issue by bkraul** [go-gitea/gitea#8673]
- Gitea version (or commit ref): 3c63c3a
- Git version: 1.11.0+dev-87
- Operating system: docker (Ubuntu 18.04 LTS host)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description
The Heatmap and the Repo List to the right are not loading after running commit 3c63c3a. This works properly on the previous commit I have archived, which is c2fca23. The web developer console shows multiple 500 errors on some of the API endpoint calls.

## Screenshots
With 3c63c3a:
![image](https://user-images.githubusercontent.com/14616851/67497352-76547900-f643-11e9-81e9-827f39368627.png)
![image](https://user-images.githubusercontent.com/14616851/67498002-67ba9180-f644-11e9-828c-b5b61eae613c.png)

With c2fca23:
![image](https://user-images.githubusercontent.com/14616851/67497614-d77c4c80-f643-11e9-9f1e-065e1ec40d15.png)
![image](https://user-images.githubusercontent.com/14616851/67498097-8882e700-f644-11e9-9273-6ca0fbe4f505.png)

**Comment by lunny** [comment]
closed by #8675
