### ISSUE TITLE
Easier-to-perform actions on issues

### ISSUE THREAD

**Issue by ethantkoenig** [go-gitea/gitea#868]
Right now, to perform an action (close, add label, etc.) on an issue, a user must go to the issue's page. This can be burdensome if a user wants to perform an action on several issues, as they have to navigate to each issue's page.

It would be cool if we did something like Github, where you can perform actions on several issues from the issues page.

I would be happy to work on this, but just want to confirm there is interest.

**Comment by lunny** [comment]
Please do it. I just put this in v1.2. But if you are faster enough, I don't mind put it to v1.1.

**Comment by lunny** [comment]
resolved by #926
