### ISSUE TITLE
If database for gitea is missing,  is there any chance to recover?

### ISSUE THREAD

**Issue by LodeSNA** [go-gitea/gitea#8680]
- Gitea version (or commit ref): 1.7.1
- Git version: 2.2.1
- Operating system: CentOS 6.10
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant

Hi.

Bad today, for some reason my PostgreSQL database for gitea just gone, and of course no backup. But the /gitea-repositories is fine, I found my config and *.git dir.

In *.git dir, what's "/objects" and "/pull" use for? I just found some file in "/objects" like distributed storage something...There's my code? That file size is close my code's size...maybe.

any chance to recover?

Thx.

**Comment by zeripath** [comment]
Ok, so gitea-repositories will be all the code. 

If you are restarting Gitea move those away first. If you create a repo with the same name in Gitea it will delete those files. So do that first.

Once those are moved you can then recreate and push these repositories to Gitea. You will have lost the issues, teams and users etc - but you have the code.

(We really need a way for Gitea to recover from existing repositories.)

**Comment by saytesnake** [comment]
Thanks, zeripath! It work! Well, now I need to rebuild that teams and users or other  #things.

**Comment by Windly213** [comment]
I encountered this problem today... I found a solution here: https://discourse.gitea.io/t/messed-up-database/1187

To prevent it to be swallowed by time, I copy the solution to here. 

Go to gitea's repository>user>.git folders, do the following.

credit: buddyspencer
> Ok, it was fairly easy.
> 
> I just took those repos. For exampe: bla.git
> Then I just did an git clone bla.git and I was done. Now I can push them to my newly created repos.
