### ISSUE TITLE
[FR][UI] Aggregate listing of tracked times

### ISSUE THREAD

**Issue by noerw** [go-gitea/gitea#8684]
Currently, the tracked times feature is hardly usable for things like billing, where I need to have an overview of total time spent, ideally across multiple repos.
This time spent metric needs to be filterable by the date the time was logged.

We currently have no GUI for this, but the API provides the needed data via `/user/times`.
Additionally, it would be nice to have aggregate values per issue, user & repo

**Comment by 6543** [comment]
@noerw will #9373 close this?

**Comment by 6543** [comment]
Or do you mean creating a UI?

**Comment by noerw** [comment]
closing as duplicate / related to #4870
