### ISSUE TITLE
allow reCAPTCHA  request URL can be configured

### ISSUE THREAD

**Issue by BillSJC** [go-gitea/gitea#8692]
- Gitea version (or commit ref): 1.9.0+
- Git version: Not relevant
- Operating system:  Ubuntu 18.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

I said that some region cannot access reCAPTCHA  (because Google were blocked) so the js file load from Google will be unavaliable, i issued it in #6818  , and it do fix the question that user cannot acces js files in some region. However, when i try to verify the whole login process, i found the request domain on gitea SERVER still be `www.google.com` when js file is from `www.recaptcha.net` . Then i still FAIL to finish the process.

If it's possible, request domain on gitea server can be configured as same as the js file's domain

**Comment by zeripath** [comment]
I don't understand your question. Are you talking about the configuration of recaptcha on Gitea.com ? Or are you talking about the configuration of your own Gitea server?

#6820 which is part of 1.9 will allow you to configure your own recaptcha service as you see fit. AFAICS there is no reference to any Google domain in the Gitea code, so if you have configured recaptcha correctly and are using a version of Gitea 1.9+ you should be able to configure recaptcha as you see fit. If not, can you find the place in the code that is doing this. 

If you are asking about Gitea.com or try.gitea.io that's fine, just make it clear.
