### ISSUE TITLE
how toupgrade from gogs 0.11.34 to gitea?

### ISSUE THREAD

**Issue by yctn** [go-gitea/gitea#8703]
im running gogs 0.11.34
can anyone provide me instructions on which steps i should take in order to get to the latest version of gitea?

https://docs.gitea.io/en-us/upgrade-from-gogs/
only speaks about upgrade from Gogs, version 0.9.146 and older,

**Comment by lunny** [comment]
You can search on issues to find out some workaround.

**Comment by jolheiser** [comment]
https://github.com/go-gitea/gitea/issues/4286
