### ISSUE TITLE
git lfs push fails by ssh url

### ISSUE THREAD

**Issue by fangd123** [go-gitea/gitea#8715]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
I added the setting of LFS in my gitea server following the document, but when I push the file to the git server, it tells that:
```
WARNING: Authentication error: Authentication required: Authorization error:  http://xxxxxx.git/info/lfs/locks/verify
Check that you have proper access to the repository
batch response: Authentication required: Authorization error: http://xxxxxx.git/info/lfs/objects/batch                                                                                                                        
Check that you have proper access to the repository
```
the config file of .git is :
```
[lfs "https://xxxxxx.git/info/lfs"]
        access = basic
```
my config of gitea server is:
```
LFS_START_SERVER = true
; Where your lfs files reside, default is data/lfs.
LFS_CONTENT_PATH = /home/git/data/lfs
```
What should I do to solve the problem?
...

**Comment by zeripath** [comment]
It's hard to be sure what the problem is here. Certainly the web address of your lfs appears strange - but that could be because you've censored it unusually. 

Is the http address of lfs component actually pointing to your Gitea instance?

**Comment by fangd123** [comment]
I doubt me that my address is started with "http://" not "https://", but after I modified the address to "http://", the git created the new lfs component which started with "https://" when I  `push` the git
