### ISSUE TITLE
Repository description not escaped

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#8717]
- Gitea version (or commit ref): e3875ac
- Git version: 2.17.1
- Operating system: Ubuntu
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL): https://try.gitea.io/cezar97/Gitea_Issue_Escaping
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

Related: #3903

## Screenshots
![3](https://user-images.githubusercontent.com/2960293/67685750-034b5980-f9d9-11e9-8c19-06464f775eb8.png)
![4](https://user-images.githubusercontent.com/2960293/67685754-047c8680-f9d9-11e9-94cd-1fa030e2058b.png)

**Comment by 6543** [comment]
-> https://github.com/go-gitea/gitea/blob/master/templates/repo/home.tmpl#L8

**Comment by zeripath** [comment]
https://github.com/go-gitea/gitea/blob/e3875ace913ca428804acc9a9ee1cd0b06cd8026/models/repo.go#L831-L839

The HTML is sanitised preventing any security issue. It is escaped.

**Comment by 6543** [comment]
done at https://github.com/go-gitea/gitea/pull/6306
