### ISSUE TITLE
"shodowPassword VirtualSession failed" when visit "/admin/config"

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#8718]
- Gitea version (or commit ref): 1.10.0 / e3875ac
- Git version: 2.17.1
- Operating system: Ubuntu 18.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:
```
...uters/admin/admin.go:224:shadownURL() [E] shodowPassword VirtualSession failed: parse {"Provider":"file","ProviderConfig":"/path/data/sessions","CookieName":"i_like_gitea","CookiePath":"","Gclifetime":86400,"Maxlifetime":86400,"Secure":false,"CookieLifeTime":0,"Domain":"","IDLength":0,"Section":"","IgnoreReleaseForWebSocket":false}: first path segment in URL cannot contain colon
```

## Description

N/A

## Screenshots
N/A

**Comment by archfish** [comment]
same issue with 
Database: PostgreSQL
Gitea version: 1.11.0+dev-164-g8d8aecd3c built with GNU Make 4.2.1, go1.13.4 : bindata, sqlite, sqlite_unlock_notify
Git version: 2.22.0
