### ISSUE TITLE
Sign-in redirection broken on non-standard HTTP ports

### ISSUE THREAD

**Issue by flipreverse** [go-gitea/gitea#8721]
- Gitea version (or commit ref): 1.9.4
- Git version: 2.20.1
- Operating system: Ubuntu 19.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x ] Not relevant
- Log gist:

I run Gitea behind an Nginx instance (reverse proxy). My Nginx is available on port 9443. Hence, my Gitea url is https://my.domain:9443/git/.
When I select the sign-in form (`/user/login?redirect_to=%2fgit`) via the link in the top right corner, enter my credentials, and click sign-in, I get redirected to https://my.domain/git/. 
I expect Gitea to redirect me to https://my.domain:9443/git/.
If I, however, directly navigate to the sign-in form (`/user/login`), it works as expected.

```
[server]
SSH_DOMAIN       = my.domain
DOMAIN           = my.domain
HTTP_PORT        = 3000
ROOT_URL         = https://my.domain:9443/git/
```

**Comment by zeripath** [comment]
I believe that this has been fixed already.
