### ISSUE TITLE
Wiki mirror upstream address keep old when change mirror repository address

### ISSUE THREAD

**Issue by renothing** [go-gitea/gitea#8732]
- Gitea version (or commit ref):1.9.4
- Git version:2.22.0
- Operating system: Docker
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [Y] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

when change mirror repository's upstream address, its wiki mirror upstream address does not synchronized with changes and kept old one.

**Comment by lunny** [comment]
I think this has been resolved, I cannot reproduce it in v1.20
