### ISSUE TITLE
Log in with IdentityServer

### ISSUE THREAD

**Issue by highboi51** [go-gitea/gitea#8736]
Hi, i have inquiry.

We have a Asp.Net Core website that uses [IdentityServer](https://identityserver.io/) for auth.
We would like to deploy an instance of gitea that allows us to re-use the same login credentials. Is such a thing possible with current gitea?

**Comment by guillep2k** [comment]
If your product is configured to support OAuth2 or LDAP, then it's natively supported by Gitea.

**Comment by 6543** [comment]
@highboi51 "We use IdentityServer -- the Open Source OpenID Connect and OAuth 2.0 framework for .NET." ...
gitea support OpenID and OAuth2 so it only is a configuration thing
