### ISSUE TITLE
500 When Open PR

### ISSUE THREAD

**Issue by FalconWu2017** [go-gitea/gitea#8743]
- Gitea version (or commit ref):1.9.4
- Git version:2.20.1 windows .1
- Operating system:windows 
- Database (use `[x]`):
  - [ ] MySQL
- Log gist:
2019/10/30 14:08:51 routers/repo/pull.go:303:PrepareMergedViewPullInfo() [E] GetCompareInfo: exit status 128 - fatal: ambiguous argument 'a5e691b37ba5324d20da34a2b56f291a14b3829c...refs/pull/164/head': unknown revision or path not in the working tree.
	Use '--' to separate paths from revisions, like this:
	'git <command> [<revision>...] -- [<file>...]'
## Description
URL:http://xxx.xxx.xxx.xxx/xxxx/xxxx/pulls/164

**Comment by zeripath** [comment]
I'm fairly certain that this has been fixed. Therefore I'm closing this. @FalconWu2017 please reopen if the problem persists.
