### ISSUE TITLE
gitea Incorrect time to display uploaded files

### ISSUE THREAD

**Issue by netlol** [go-gitea/gitea#8761]
![2019-10-31_123336](https://user-images.githubusercontent.com/33304953/67920585-ba192680-fbdf-11e9-9e76-abe5a5582681.png)
- Gitea version (or commit ref):1.95
- Git version:2.22.0
- Operating system:Windows 10 or windows 2019
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
The display time of uploading project files through gitea (seem only windows platform has this issue)is incorrect(only on Web Interface is wrong). After 14 hours of uploading, please analyze the reasons. Thank you.
...

**Comment by lunny** [comment]
You can config them on app.ini.

**Comment by netlol** [comment]
I try too add this in my app.ini and restart gitea, seem nothing change.
[time]
FORMAT = UnixDate
DEFAULT_UI_LOCATION = Asia/Taipei

**Comment by netlol** [comment]
I think I solved the problem.
As long as I don't set FORMAT to an empty string, RFC1123 or UnixDate ,the display time is correct.
