### ISSUE TITLE
Can not create first admin user from cli on Gitea +  PostgreSQL DB

### ISSUE THREAD

**Issue by toni-moreno** [go-gitea/gitea#8763]
- Gitea version (or commit ref):
Docker version latest (20'19/10/31)
- Git version:
- Operating system:
docker 
- Database (use `[x]`):
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:

## Description
Can not create admin user from cli inside docker. ( from the WebUI the process is working fine)
this is the output from the command line
```bash
user@server:~/$ docker exec -it $(docker ps  | grep gitea | awk ' { print $1 } ')  /app/gitea/gitea admin create-user --admin --username gitadmin --password gitadmin --email gitadmin@test.com --must-change-password false
2019/10/31 16:33:13 ...dules/setting/git.go:87:newGit() [I] Git Version: 2.22.0, Wire Protocol Version 2 Enabled
2019/10/31 16:33:13 .../xorm/session_raw.go:74:queryRows() [I] [SQL] SELECT count(*) FROM "user" WHERE (type=0) - took: 3.746177ms
2019/10/31 16:33:13 .../xorm/session_raw.go:81:queryRows() [I] [SQL] SELECT "id", "lower_name", "name", "full_name", "email", "keep_email_private", "email_notifications_preference", "passwd", "passwd_hash_algo", "must_change_password", "login_type", "login_source", "login_name", "type", "location", "website", "rands", "salt", "language", "description", "created_unix", "updated_unix", "last_login_unix", "last_repo_visibility", "max_repo_creation", "is_active", "is_admin", "allow_git_hook", "allow_import_local", "allow_create_organization", "prohibit_login", "avatar", "avatar_email", "use_custom_avatar", "num_followers", "num_following", "num_stars", "num_repos", "num_teams", "num_members", "visibility", "repo_admin_change_team_access", "diff_view_style", "theme" FROM "user" WHERE (id!=$1) AND "lower_name"=$2 LIMIT 1 []interface {}{0, "gitadmin"} - took: 318.024µs
2019/10/31 16:33:13 main.go:111:main() [F] Failed to run app with [/app/gitea/gitea admin create-user --admin --username gitadmin --password gitadmin --email gitadmin@test.com --must-change-password false]: CreateUser: pq: relation "user" does not exist
````
...

**Comment by lunny** [comment]
Have you tried run `gitea migrate` before this command?

**Comment by BagaSiva** [comment]
Hi Toni,

I have deployed a Gitea container on Kubernetes cluster that uses PostgreSQL DB. As part of automation, I have to create the admin users first to procedd further. I have tried API and Curl command. But none of the approaches work. 

Seems you also had similar challenge. 
Could you help me to fix this issue.

**Comment by asoltesz** [comment]
@BagaSiva 
You should be able to create the admin user but only the database schema installation and the general auto-installer process has been finished. You may wait for a specified amount of time or monitor this index page (I think it throws 503 until the auto-install finishes).

Then, you may execute something like this with kubectl exec in the container:

exec su-exec git gitea admin create-user --name=gitea --password=gitea --email=test@xx.com --admin --must-change-password=false

**Comment by Slayug** [comment]
I faced the same problem, to solve this I created a `Dockerfile` with the `start.sh` script

_start.sh_
wait until the gitea home page is available (200 on localhost:3000) then create the gitea admin
in same time run gitea (will init the database and start Gitea)
```Bash
#!/bin/bash

ATTEMPT=0
MAX_ATTEMPT=20
while true; do
    sleep 1
    ATTEMPT=$(($ATTEMPT + 1))
    STATUS_CODE=$(curl -LI localhost:3000 -o /dev/null -w '%{http_code}\n' -s)
    if [ $STATUS_CODE = "200" ]; then
        echo "Gitea is ready"
        echo "Create Gitea admin"
        gitea admin create-user --admin --username $ADMIN_USER --password $ADMIN_PASSWORD --email your@email.org --must-change-password=false
        exit 0
    elif [ $ATTEMPT = $MAX_ATTEMPT ]; then
        exit 1
    fi;
done & /usr/bin/entrypoint
```

_Dockerfile_
```Dockerfile
FROM gitea/gitea:1.12.5

COPY start.sh .

ENTRYPOINT ["./start.sh"]
```

ADMIN_USER and ADMIN_PASSWORD are set via env vars.
If the user already exists, no problem we just got `CreateUser: user already exists` in the logs.
