### ISSUE TITLE
When I run the "git push heroku master" command, gives the error below, how to solve?

### ISSUE THREAD

**Issue by ezequielllbarbosa** [go-gitea/gitea#8773]
C:\Users\trabalhos\git\releases\gestao-obra-inteligente>git push heroku master

Enumerating objects: 604, done.
Counting objects: 100% (604/604), done.
Delta compression using up to 4 threads
Compressing objects: 100% (453/453), done.
Writing objects: 100% (604/604), 13.85 MiB | 600.00 KiB/s, done.
Total 604 (delta 120), reused 604 (delta 120)
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> App not compatible with buildpack: https://buildpack-registry.s3.amazonaws.com/buildpacks/heroku/java.tgz
remote:        Could not find a pom.xml file! Please check that it exists and is committed to Git.
remote:
remote:        More info: https://devcenter.heroku.com/articles/buildpacks#detection-failure
remote:
remote:  !     Push failed
remote: Verifying deploy...
remote:
remote: !       Push rejected to gestao-obra.
remote:
To https://git.heroku.com/gestao-obra.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/gestao-obra.git'

Enumerating objects: 604, done.
Counting objects: 100% (604/604), done.
Delta compression using up to 4 threads
Compressing objects: 100% (453/453), done.
Writing objects: 100% (604/604), 13.85 MiB | 600.00 KiB/s, done.
Total 604 (delta 120), reused 604 (delta 120)
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> App not compatible with buildpack: https://buildpack-registry.s3.amazonaws.com/buildpacks/heroku/java.tgz
remote:        Could not find a pom.xml file! Please check that it exists and is committed to Git.
remote:
remote:        More info: https://devcenter.heroku.com/articles/buildpacks#detection-failure
remote:
remote:  !     Push failed
remote: Verifying deploy...
remote:
remote: !       Push rejected to gestao-obra.
remote:
To https://git.heroku.com/gestao-obra.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/gestao-obra.git'

**Comment by zeripath** [comment]
Git.heroku.com doesn't appear to be a Gitea server.

You're pushing from a command line not using Gitea.

Where is the Gitea issue here?

I suggest you read the error in your git message and look at heroku.com help pages:

```
remote: Building source:
remote:
remote: -----> App not compatible with buildpack: https://buildpack-registry.s3.amazonaws.com/buildpacks/heroku/java.tgz
remote: Could not find a pom.xml file! Please check that it exists and is committed to Git.
remote:
remote: More info: https://devcenter.heroku.com/articles/buildpacks#detection-failure
```

If Gitea is actually involved here somewhere please feel free to reopen but I cannot see the relevance of this issue to Gitea therefore I'm closing this as off-topic

**Comment by BV-SS** [comment]
![Screenshot (66)](https://user-images.githubusercontent.com/65727171/85386775-a309b900-b561-11ea-9ac6-1e91b0632dda.png)
getting error while deploying on heroku 

i successfully added all the files on .git repo
also i have my Procfile and requirements.txt ready in that folder 
but it seems pip is not able to install some repositories on my remote Heroku 
..below error always shows up on running "git push heroku master"
also i used 'masterbranch' branch nothing helped 
![Screenshot (67)](https://user-images.githubusercontent.com/65727171/85386696-8a010800-b561-11ea-9942-1b12cb0793d1.png)
