### ISSUE TITLE
Update database from Git Repositories

### ISSUE THREAD

**Issue by tcyrus** [go-gitea/gitea#8774]
- Gitea version (or commit ref): 1.9.2
- Git version: N/A
- Operating system: Ubuntu
- Database (use `[x]`):
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:

## Description

My database server had an issue unrelated to Gitea, but I lost some of the database records. I restored a backup of the database, but some of the repositories are missing from this copy.

I was wondering if there was an admin command to do the reverse of "Reinitialize all missing Git repositories for which records exist", where it would "Reinitialize all missing records for which Git repositories exist".

**Comment by guillep2k** [comment]
You can enable `IMPORT_LOCAL_PATHS = true` in `app.ini` and manually import those repositories. They will be created anew in the database; no issues/PRs/labels/etc will exist but the code will be there. For this to work you must first move them out of their current location (i.e. from `gitea-repositories/{owner}/...` to another directory).
I know it isn't much, but may be it will help.

**Comment by guillep2k** [comment]
This, however, could be an interesting function for a Gitea utility to have.

**Comment by zeripath** [comment]
Yeah I think we should make it possible recover data - however, it's a slightly difficult situation. With a completely brand new Gitea do you create users for each of the recovered repositories? - but they might have meant to be organisations so this is probably not correct. So you should probably leave it till users are created - and then restore?

**Comment by guillep2k** [comment]
> 
> 
> Yeah I think we should make it possible recover data - however, it's a slightly difficult situation. With a completely brand new Gitea do you create users for each of the recovered repositories? - but they might have meant to be organisations so this is probably not correct. So you should probably leave it till users are created - and then restore?

It's pretty easy: recreate those that have a matching user, report those that don't. 😁

**Comment by lunny** [comment]
Since `push to create feature` has been implemented, I think we can close this now.
