### ISSUE TITLE
A new subcommand named `doctor` to detect all the possible problems

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#8781]
A new `doctor` subcommand could check gitea's running status, it could includes:

- [ ] Repositories file system permissions. It could read `app.ini` to get running user and check if all the repositories could be read/write by the user.
- [ ] Repositories Hooks script address. It could check if all the repositories hooks script address is current binary's address.

Welcome to add more.

**Comment by guillep2k** [comment]
- [ ] Repositories under `gitea-repositories` that are missing from the database, and the other way around.
- [ ] `authorized_keys` script address.
- [ ] Assets that are found in `data/attachment` but are not linked in gitea, and the other way around.
- [ ] Automatically detect all running instances.
- [ ] Search for `app.ini`; try to figure out its configuration.

**Comment by sapk** [comment]
Can you review what functions are already implemented in doctor command to keep progress ?

**Comment by sapk** [comment]
This command  could include #2762

**Comment by lunny** [comment]
@sapk I have checked one on @guillep2k 's list.

**Comment by sapk** [comment]
It happen many times that users don't find where are some folder/path used by gitea (like the custom folder). Maybe we could dump those information when running doctor command ?

**Comment by guillep2k** [comment]
> 
> 
> ~It happen many times that users don't find where are some folder/path used by gitea (like the custom folder). Maybe we could dump those information when running doctor command ?~
> Edit: Nevermind those are visible in the admin ui.

@sapk I'm sure it won't hurt, anyway.

**Comment by guillep2k** [comment]
> 
> 
> It happen many times that users don't find where are some folder/path used by gitea (like the custom folder). Maybe we could dump those information when running doctor command ?

@sapk #10064 😄

As you've mentioned, the configuration tab in settings is also very useful because oftentimes the users do have Gitea running and they only need to e.g. customize it.

**Comment by lunny** [comment]
Closed and thanks @guillep2k
