### ISSUE TITLE
Releases/tags/issues from GitHub not migrated with mirror

### ISSUE THREAD

**Issue by ltguillaume** [go-gitea/gitea#8796]
- Gitea version (or commit ref):
- Git version: 1.9.4 and 1.9.5 (via Arch repo)
- Operating system: Arch Linux for ARM
- Database:
  - [ ] PostgreSQL
  - [x] MySQL (MariaDB 10.4.8)
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes: https://try.gitea.io/sdjfjsadfoiuiw4/
  - [ ] No
  - [ ] Not relevant
- Log gist: (no errors found in log)

## Description
Perhaps I misunderstood how mirrored migrations (should) work (I have found virtually no documentation on the matter, other than some blog posts by people who wrote scripts for it), but compared to a regular migration, I noticed the following:

1. Releases are not migrated, tags are _sometimes_ migrated (tried DroidShows repo 4 times, tags were migrated 1 time, releases never)
2. Issues are not migrated
3. Activity is not migrated (should it?)

Items seem to be migrated just fine for non-mirror migrations.

I'm using the web interface to initiate a migration and used a GitHub Personal access token for authentication (also tried master password on my local Gitea instance once, no difference found).

**Comment by guillep2k** [comment]
Hi, indeed, mirrors and migrations are different things and have different purposes. A migration in Gitea is a one-time event, and depending on the source might or might not migrate issues and other non-git information. If I reacall correctly, Github is currently the only source that supports migration of those elements. The purpose of the migration is to leave the previous vendor and start using Gitea :wink:.

A mirror, instead, is a git-only, read-only copy that can "refresh" in configurable regular intervals (configuration in `app.ini`, but you can force a manual refresh in the repository settings). You will be able to create/update your own set of issues and other non-git data, but they will be unrelated to the source repository. The purpose of a mirror is to have a "close by" copy of the source and perhaps control local access permissions.

**Comment by ltGuillaume** [comment]
Thanks for the reply. I was unsure about this, since there is no documentation. Although it does make sense, I really needed to hear the rationale behind it before I could fully understand it, so thank you. I'm quite sure I won't be the only one 😊

I suppose the Wiki is mirrored because is implemented as a "branch" of the repo.

**Comment by ltGuillaume** [comment]
Does authentication have any function for mirrors?

**Comment by guillep2k** [comment]
@ltGuillaume Never used those, but I think so, yes.
