### ISSUE TITLE
[Feature Request] activity add options ("all" and "year")

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#8797]
Version: current

![Bildschirmfoto zu 2019-11-02 21-57-47](https://user-images.githubusercontent.com/24977596/68076952-ee493e80-fdbb-11e9-9240-d190c20e1565.png)

**Comment by lafriks** [comment]
I don't think all time is reasonable

**Comment by guillep2k** [comment]
> 
> 
> I don't think all time is reasonable

I agree. Only for the smallest repos perhaps.
