### ISSUE TITLE
[Bug] Commit Graph: pagination sometimes drop last

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#8798]
repo wich has this problem: https://gitea.com/gitnex/GitNex/graph

"Last" go to https://gitea.com/gitnex/GitNex/graph?page=3
but in realety it is https://gitea.com/gitnex/GitNex/graph?page=4

so affected versions are: current, 1.10?

**Comment by jaqra** [comment]
There is 249 commits.
gitea.com shows 100 commit in each page
**Can not** be 4 pages.

You can see older commits if it did not start from new repository

**Comment by 6543** [comment]
@jaqra you mean gitea takes the number of commits on default branch to calculate the pagesbwichvare needed?

**Comment by jaqra** [comment]
Here is the code to get commit count

https://github.com/go-gitea/gitea/blob/cf2fc22b1cacc6621a1c91af118490510d366f76/routers/repo/commit.go#L49

**Comment by 6543** [comment]
notevpagination was addet at #8360

**Comment by 6543** [comment]
@jaqra I don't look deep into this particular code jet ...
this is a note wich I/someone can pic up to fix :)

but you got the problem or shuld i describe it better?

**Comment by jaqra** [comment]
@6543 i did
