### ISSUE TITLE
Password complexity check should be skipped on external auth sources

### ISSUE THREAD

**Issue by silverwind** [go-gitea/gitea#8821]
- Gitea version (or commit ref): https://github.com/go-gitea/gitea/commit/ee5249889d7f9f3fbda4aa87dd3202753ed595cb

## Description

When adding a new user using a external auth source like LDAP, the option `PASSWORD_COMPLEXITY` is validated which prevents a admin from creating a new user with below error message while there is no actual password field visible in the UI. This check should be skipped for cases where gitea does not actually store a password.

## Screenshots

<img width="454" alt="Screen Shot 2019-11-04 at 10 44 10" src="https://user-images.githubusercontent.com/115237/68111838-5b5df080-fef0-11e9-8de6-8191e37bc95e.png">

**Comment by guillep2k** [comment]
Looks like the root cause for #8558
