### ISSUE TITLE
How to backup an account when you don't have access to the host

### ISSUE THREAD

**Issue by snowc0de** [go-gitea/gitea#8827]
I was wondering how I could download all data from my account on my computer from the website https://gitea.com 

I wanted to centralize my data on one computer so how could I download all the data from my account?

Thanks in advance!

**Comment by lafriks** [comment]
Just clone/mirror your repositories to your computer

**Comment by chopin2712** [comment]
Yes but is there any way to clone all data at once. For example if I want to send my entire profile to another host, could I?

**Comment by lunny** [comment]
You could write some scripts to do that. Or we should implement this on `tea` command.

**Comment by chopin2712** [comment]
I don't know how to create a script for that, and what is a tea command?

**Comment by techknowlogick** [comment]
@chopin2712 you could a programming language of your choice to pull a list of all the repos on a gitea instance belonging to your user, and then use git clone against that list.

Information about the `tea` command can be found here: ﻿﻿https://gitea.com/gitea/tea/

**Comment by chopin2712** [comment]
Yes but is there anyway to do it automatically? I believe that organizations who have lots of different projects would be bored to copy and paste all project's names one by one in a  sh file. It 's not my case but I am curious.
