### ISSUE TITLE
Pull request branch delete message could be in the log

### ISSUE THREAD

**Issue by xor-gate** [go-gitea/gitea#883]
- Gitea version (or commit ref): 1.0.0+245-g40f43777
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes: https://try.gitea.io/admin1337/kkkk/pulls/2

## Description

I'm not sure how many people would prefer inside the log that a branch is removed after pull (last line is relevant):

```
 admin1337 added the enhancement label 17 seconds ago
 admin1337 closed 10 seconds ago
 admin1337 removed branch XXX
```

Currently many operations are logged and displayed (in issues and PRs) why don't we add the `removed branch XXX` ?

**Comment by lunny** [comment]
Yes. Lost one.
