### ISSUE TITLE
[Bug/Feature Request] Markdown parse Relative Links

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#8830]
Version: 1.11.0+dev-163-g86a44f6b4

## Support Relative Links

for example:
`![picture](img/00.png)`
**currently:** `https://<gitea-instance/<user>/img/00.png`
**how it should be:** `https://<gitea-instance/<user>/s/raw/branch/<branch>/img/00.png`

we also should parse something like:
**this:**  `<img src="metadata/en-US/phoneScreenshots/02.png" width="200" />` 
**to:** `<img src="https://<gitea-instance/<user>/s/raw/branch/<branch>/metadata/en-US/phoneScreenshots/02.png" width="200" />`

since other github and gitlab? support this avter repo migration lot of broken links hapen ...

**Comment by 6543** [comment]
related to: #8813

**Comment by guillep2k** [comment]
It can be done. I wander what are the possible ramifications (e.g. is there any security concern?); it shouldn't use the branch but the commit sha, I guess.

**Comment by pztrn** [comment]
In Gitlab for example specifying:

```
[the text](/the/url)
```

link will be rendered with root prefix (branch, commit SHA, etc), so URL will be valid in any mode (commit, branch viewing).

**Comment by 6543** [comment]
still not solved

**Comment by zeripath** [comment]
What do we make the links absolute to and how do we determine that?

There are multiple places that markdown is rendered.

We'd either need to have a set path that a markdown path is relative to (likely different for each type of markdown) or need to detect the relative path at the time of saving and absolute it. We would need to be careful about how we send the absolute path to the renderer over the API too.

It's not an insurmountable problem but it does need a bit of thought.

**Comment by guillep2k** [comment]
>
> What do we make the links absolute to and how do we determine that?

We could have different repo meta contexts. The repo meta drives the creation of links and such.
