### ISSUE TITLE
[API] times: use Index instead ID's and dont expose ID's

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#8833]
While All Issue API Endpoints are structured like this:
`/repos/{owner}/{repo}/issues/{index}/<endpoing>` and use index
timetrack API is not:
`/repos/{owner}/{repo}/issues/{id}/times`

does this have any meanings?!?

**Comment by zeripath** [comment]
We also need to add the ability to adjust time tracking. @6543 I think there were a couple of issues that referenced this.

**Comment by noerw** [comment]
Another problem: the API returns internal IDs (user, issue ID), which is neither consistent with other APIs, nor meaningful to a data consumer.

This PR is blocked by this issue: https://gitea.com/gitea/tea/pulls/54
