### ISSUE TITLE
Invalid email can be made primary and also logged in with.

### ISSUE THREAD

**Issue by masudur-rahman** [go-gitea/gitea#8837]
From [`account`](https://gitea.com/user/settings/account) section:
If any user adds an email address to his account, he can't make it primary unless he **verifies** it. Hence, he **can't** login with the email address.

But from [`profile`](https://gitea.com/user/settings) section:
Any user can add any email address and he **doesn't** need to verify it. Also it automatically becomes **primary** email and he **can login** using that email address.

**Comment by lunny** [comment]
Change email address on profile section needs to be verified according configuration when register required email verify.

**Comment by lunny** [comment]
I think this has been resolved.
