### ISSUE TITLE
when i use a non default port, the port of repo link is always 3000

### ISSUE THREAD

**Issue by czs208112** [go-gitea/gitea#8838]
- Gitea version (or commit ref): 1.9.5
- Git version: 1.8.3.1
- Operating system: centos7 64
- Database (use `[x]`): MySQL 5.7
- Can you reproduce the bug at https://try.gitea.io: NO

## Description
 i change default port to 3123 , restart service ,then create a repo, but the port of repo link is always 3000。 

## Screenshots
![image](https://user-images.githubusercontent.com/7848823/68198891-e4138400-fff7-11e9-831a-97b0d52ad13c.png)

**Comment by lunny** [comment]
How did you change your app.ini? Could you paste them?

**Comment by czs208112** [comment]
> How did you change your app.ini? Could you paste them?

thank for your relpay。 it's my fault.  i changed "HTTP_PORT",but not change "ROOT_URL"。
when "ROOT_URL" is also changed with "http://xxxx.xxx:3123/" ，my question is resolved。
![image](https://user-images.githubusercontent.com/7848823/68205363-111a6380-0005-11ea-8a80-b64ee1aaf798.png)

**Comment by czs208112** [comment]
so maybe "ROOT_URL" should cancel in app.ini? i think it's a redundancy condition。
or port only config once is a good idea。
