### ISSUE TITLE
Deleted user's (Ghost) avater image generates error 500

### ISSUE THREAD

**Issue by ashimokawa** [go-gitea/gitea#8853]
- Gitea version (or commit ref): 1.10-rc2
- Git version: 2.20.1
- Operating system: Debian 10
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL (mariadb)
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X] No (READ DESCRIPTION)
  - [ ] Not relevant
- Log gist:

`
2019/11/06 08:19:24 ...uters/user/avatar.go:29:Avatar() [E] Requested avatar for invalid user: user does not exist [uid: 0, name: Ghost, keyid: 0]
`

## Description

When a user, who created an issue, deletes itself, the issue is re-assigned to "Ghost", who does not have an image.

https://codeberg.org/user/avatar/Ghost/-1 generates error 500

See here:

https://codeberg.org/crimeflare/cloudflare-tor/issues/16

This does not happen on try.gitea.io because someone created a Ghost user there when it was not yet blacklisted. So the avatar is there.

https://try.gitea.io/Ghost

**Comment by ashimokawa** [comment]
on codeberg.org we worked around the problem by putting a valid image in a file called

/etc/gitea/public/user/avatar/Ghost/-1

**Comment by 6543** [comment]
@techknowlogick can you add this to 1.10.2 ?

**Comment by 6543** [comment]
@techknowlogick / @lunny can you add Milestone 1.10.2 ?
