### ISSUE TITLE
Custom icons don't work with CDN configuration

### ISSUE THREAD

**Issue by RalphORama** [go-gitea/gitea#8854]
- Gitea version (or commit ref): 1.9.5
- Git version: 2.17.1
- Operating system: Ubuntu Server 18.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist: https://gist.github.com/RalphORama/8971298a0734ac3724b9765e5652f222

## Description

I have gitea set up with a CDN [as specified in the docs](https://docs.gitea.io/en-us/reverse-proxies/#using-two-nodes-and-two-domains).  I'm trying to change the default user avatar ([also specified in the docs](https://docs.gitea.io/en-us/customizing-gitea/#changing-the-default-avatar)) by placing my custom image in `/var/lib/gitea/custom/public/img/avatar_default.png`, but the default avatar doesn't change.

I've tried:

- Restarting gitea (duh)
- Clearing my browser cache
- Clearing my browser cache & purging all files on CloudFlare 
  - only my CDN is under CloudFlare)

Unfortunately, none of these attempts fixed the issue.

**Comment by lunny** [comment]
I think v1.9.5 haven't support that feature. refs: #7911

**Comment by RalphORama** [comment]
Sounds good.  I suppose I could create a `custom` folder on my CDN and modify templates in `custom` to point at custom assets.

**Comment by RalphORama** [comment]
**Update:** Not sure what was going on with file caching, but I loaded the site on a different computer and the change took effect.  Probably some CloudFlare weirdness.
