### ISSUE TITLE
Issues list should show days till due and who it is assigned to.

### ISSUE THREAD

**Issue by vincentdavis** [go-gitea/gitea#8859]
- Gitea version 1.9.4
- Operating system: Ubuntu
- [ X ] PostgreSQL
  
## Description
When at the domain.com/issues page. Add the due date if there is one and who it is assigned to.
Why I want this. I manage a team of developers who each work on several projects. I need a way to manage the due dates across all the projects. This seems like a minimal feature addition that will have a lot of value to me and of course many others.

I am willing to pay a bounty, git tip, coffee card, amazon gift. for this being accepted and implemented soon. I did make a contribution through the sponsor link above.

**Comment by davidsvantesson** [comment]
The assignees are already listed (as avatars). It is also possible to sort on due date, but it would make sense to show it in the list as well.

**Comment by mrsdizzie** [comment]
It currently does show who the issue is assigned to (if there is an assignee). Will make a PR to add the due date same as it shows in the repo issues list.

Probably more improvements that could be made but adding the date is a simple fix will do a PR for that

**Comment by vincentdavis** [comment]
@mrsdizzie 
I don't see where it shows who it is assigned to. Am I blind? See screen shot below.


![image](https://user-images.githubusercontent.com/232564/68347710-1636eb80-00b5-11ea-8a76-d5c08062d437.png)

**Comment by 6543** [comment]
@vincentdavis think so ... 1.10.0 is here soon
on 1.11.0-
![Bildschirmfoto zu 2019-11-07 01-57-01](https://user-images.githubusercontent.com/24977596/68350830-ed891300-0101-11ea-93a4-4c0bdb90c75a.png)
dev it looks like:

**Comment by vincentdavis** [comment]
@6543 
Thank you!

Seems like this should be closed then.
