### ISSUE TITLE
Review page should not get refresh on adding comment

### ISSUE THREAD

**Issue by atishhamte** [go-gitea/gitea#8861]
- Gitea version (or commit ref): 1.9.4
- Git version: 2
- Operating system: Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
On doing code review of pull request, on every comment, page is getting refresh. You can make use of AJAX kind to register the comment without refreshing the page.
This is very painful while reviewing files more than 100 with huge content.

**Comment by jpraet** [comment]
+1, reviewing large pull requests is a real pain because of this

**Comment by andre161292** [comment]
This is a really annoying one, when reviewing large PRs. Would love to see activity here. :)
