### ISSUE TITLE
Add Retry on http requests (dont cancel migration if one error ocure)

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#8869]
gitea Version:  1.11.0+dev-110-gc4bc5abda

Migrating gitea WITHOUT pullrequests and releses works:
https://gitea.com/test-organisation/gitea-mig-test

PullRequest test: https://gitea.com/6543/mig-test2
Releases test: https://gitea.com/6543/rel

**Comment by lunny** [comment]
Once there is any network error on the migration, it will rollback. So we have to add some retry for all the http request.

**Comment by 6543** [comment]
@lunny title changed ...
