### ISSUE TITLE
git-blame view does not show profile icons correctly

### ISSUE THREAD

**Issue by hapasa** [go-gitea/gitea#8870]
- Gitea version (or commit ref): 1.10
- Git version:  1.8.3.1
- Operating system: Red Hat Enterprise Linux Server release 7.6 (Maipo)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X ] Not relevant
- Log gist:

## Description

If in settings

DISABLE_GRAVATAR        = true
ENABLE_FEDERATED_AVATAR = true

the git-blame view will display generic coffee cup avatar, while it the Dashboards the local avatar is correctly displayed.

In git-blame:
`<img class="ui avatar image" src="/img/avatar_default.png" title="Harri">`

In Dashboard:
`<img class="ui avatar image" src="/user/avatar/harri/-1" alt="">`

...

## Screenshots

![image](https://user-images.githubusercontent.com/8208561/68400545-822e5800-0178-11ea-8e57-5595d2f0fa5a.png)

![image](https://user-images.githubusercontent.com/8208561/68400682-b6a21400-0178-11ea-8825-b238bfefbb64.png)

**Comment by mrsdizzie** [comment]
Do you have a full example you can link to? The main reason this would happen is if that particular commit you cropped in the screenshot has a different e-mail address than the user with the icon

**Comment by jolheiser** [comment]
Per the Discord conversation it seems this was caused by emails not matching.

**Comment by hapasa** [comment]
Indeed it was email address mismatch.  However, it was not at all obvious to sort out, especially since in the Dashboard the correct avatar was showing.
