### ISSUE TITLE
I'm still receiving email notifications for issue comments while not watching repo and not being subscribed to issue

### ISSUE THREAD

**Issue by strk** [go-gitea/gitea#8879]
I saw this happening on gitea.com, but cant remember the exact issue it was occurring for.
@lunny might recall

**Comment by strk** [comment]
Found the reference: https://gitea.com/gitea/go-sdk/pulls/185#issuecomment-79877
This is Gitea Version: 1.11.0+dev-110-gc4bc5abda

**Comment by lunny** [comment]
Is this still a problem?

**Comment by strk** [comment]
@6543 did you complete your [work](https://gitea.com/gitea/go-sdk/pulls/185#issuecomment-79938) on this ?

**Comment by 6543** [comment]
#9535

**Comment by 6543** [comment]
Jes I'll finish but think in 2/3 weeks I'll start coding again ...

**Comment by 6543** [comment]
@strk feel free to pick this up if you need it soon

**Comment by guillep2k** [comment]
> 
> 
> @6543 did you complete your [work](https://gitea.com/gitea/go-sdk/pulls/185#issuecomment-79938) on this ?

@strk this particular issue should be fixed for you. The PR @6543 is working on is an enhancement that will let you unsubscribe from a particular issue without unwatching the repository (i.e. the user will still get notifications for other issues in that repository). Since this issue was about you receiving notifications despite not watching the repository, that PR is unrelated.

**Comment by strk** [comment]
I was not watching but I was a partecipant due to some interaction. I understand explicit unsubscribe is the only way to fix this. I don't need this soon, but I'd rather only close this ticket when the problem is really fixed (problem of receiving notifications while not watching repo and not being subscribed)

**Comment by 6543** [comment]
I'll finaly take this issue :) - will send a pull when #10401 is merged, then I have to look at
`services/mailer/mail_issue.go` anyway...

**Comment by 6543** [comment]
@strk bugfix: #10475
