### ISSUE TITLE
branch/tag field is inaccessible after issue creation

### ISSUE THREAD

**Issue by kernie** [go-gitea/gitea#8880]
- Gitea version (or commit ref): 1.9.5
- Git version: 2.17.1
- Operating system: Ubuntu 18.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
Hi,

when I create a new issue and didn't choose a branch/tag, but want to add it afterwards, the field is deactivated. All other fields are accessible.
Is this by purpose?

Thanks,
Maarten

**Comment by guillep2k** [comment]
Duplicate of #5476
