### ISSUE TITLE
Row alignment issue in git-blame view

### ISSUE THREAD

**Issue by hapasa** [go-gitea/gitea#8881]
- Gitea version (or commit ref):  1.10.0+rc2-9-g68b7f9f3f
- Git version: 1.8.3
- Operating system: Red Hat Enterprise Linux Server release 7.6 (Maipo)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

the rows in two columns in git-blame view do not match.
Tried with Chrome, IE, Firefox.   Upgrade from Gitea 1.7.3, no custom CSS in use.
...

## Screenshots
![image](https://user-images.githubusercontent.com/8208561/68476554-486a5980-022b-11ea-9972-56639bc0afaa.png)

**Comment by mrsdizzie** [comment]
(I think) This is general problem of how blame was designed where the entire contents are inside a single table row and can't possible ever work right all the time:

 https://github.com/go-gitea/gitea/blob/d9be82bd003d2dfd1c2bd31bf871d49c898b5c6b/templates/repo/blame.tmpl#L39

and

 https://github.com/go-gitea/gitea/blob/d9be82bd003d2dfd1c2bd31bf871d49c898b5c6b/routers/repo/blame.go#L223

The view part would probably need to be redesigned at least to have each commit/blame be its own table row similar to diff view

**Comment by septatrix** [comment]
This can also be easily observed at this official repo: ([gitea.com - gitea/tea](https://gitea.com/gitea/tea/blame/branch/master/modules/git/url.go))

**Comment by camlafit** [comment]
Hello

We confirm this behavior for example on https://git.spip.net/spip-contrib-extensions/formidable/blame/branch/v4/formidable_fonctions.php or https://try.gitea.io/asahiocean/AsahiOcean/blame/branch/main/README.md

Mac / Firefox / 90.0.2  :
![Capture d'ecran 2021-08-12 a 12 22 00](https://user-images.githubusercontent.com/209915/129183358-c77b3c83-5ab3-4cc1-85a3-842813e3a80f.png)

Mac / Safari :
![Capture d'ecran 2021-08-12 a 12 27 41](https://user-images.githubusercontent.com/209915/129183624-26226f35-d974-4efc-8406-631fe22880fa.png)

Could be partially solve with theses changes
```
.blame-info {  
    line-height: 20px;  
‎}  

 .lines-commit .ui.avatar.image {  
‎height: 16px;  
‎width: 16px;  
}
```

But I presume this patch will broke with other use case as size are in pixel.

**Comment by wxiaoguang** [comment]
It should have been fixed in latest version.
