### ISSUE TITLE
Dashboard context should not changed when navigate with top menus.

### ISSUE THREAD

**Issue by kybin** [go-gitea/gitea#889]
- Gitea version (or commit ref): 1.0.0+247-g2f13d31f
- Git version: try.gitea.io
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

Gitea changes my dashboard context (organization) when I navigate through top menu buttons.
Which is slightly cumbersome. 

Thanks.

**Comment by lunny** [comment]
I think maybe we can add a global option or remove the organization options on the top menu
