### ISSUE TITLE
Use separate test repository for Github migration tests

### ISSUE THREAD

**Issue by mrsdizzie** [go-gitea/gitea#8895]
We should create a test repo that is never touched or modified and use that for github migration tests. As seen in #8893, tests were broke from re-opening an old issue that then changed the modification time of a milestone.

Would be better not to test things that might be updated or change randomly.

**Comment by lunny** [comment]
Right. I think maybe `git` repository is better since it has been archived.

**Comment by guillep2k** [comment]
Why not fork any of those under go-gitea and use the fork?

**Comment by mrsdizzie** [comment]
Forking doesn't copy most any of the things actually tested. Just need a set of milestones, issues, releases, etc...

@lunny we should use a new repo because you might want to add future tests and that could be hard with an archived repository that you can't modify. Also it might as well be very intentional that the repo only exists to be tested

**Comment by lunny** [comment]
@mrsdizzie but you also have to archive it to avoid someone create issues accidentally?

**Comment by mrsdizzie** [comment]
@lunny it is ok to create new issues (new issues are created on go-gitea/gitea all the time and that is what we test now). 

We should just have a test repo so there is no reason for anybody to ever modify old issues/milestones/etc...

Having a test repo is just like the unit and integration tests we have where it is clear that the information is only there to be tested and you should be cautions if making any additions.

**Comment by lunny** [comment]
OK. Here we go. https://github.com/go-gitea/test_repo

**Comment by mrsdizzie** [comment]
@lunny ok great when I have some time will look into replacing the current tests/data ty!

**Comment by mrsdizzie** [comment]
@lunny if possible to give me permission to create milestones, release, etc.. if not you should create anything we need to test in that repo then we can update the current tests

**Comment by lunny** [comment]
@mrsdizzie Thanks! Done. Now you have permissions to create issues/milestones/releases, etc... on that repository.

**Comment by mrsdizzie** [comment]
Thx @lunny ill do in a few days when back
