### ISSUE TITLE
[CI] If one test failed cancle all

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#8898]
I often see CI tasks wich already failed but still need recources

**Comment by mrsdizzie** [comment]
It should show all failures imo -- if there are 10 failures it doesn't make sense to stop at the first one, fix it, run again, see the 2nd one, fix it, etc...

A majority of the failed builds/resources are  by people not running even unit tests locally first as recommended

**Comment by 6543** [comment]
@mrsdizzie thought about this point ... problem is `make test` fail multible times - on local because of missing test settings/requirements ...

 *  `...ces/mirror/mirror.go:200:runSync() [E] Failed to synchronize tags to releases for repository: GetTagCommitID: exit status 128 - fatal:`
 *  `models/repo.go:548:mustOwnerName() [E] Error loading repository owner name: user does not exist [uid: 0, name: , keyid: 0] `
* `...s/repo_permission.go:154:func1` -> `expected: []int64{}   actual  : []int64(nil)   `

.... but I'm looking forward to drone.gitea.com wich more people can cancle manualy ...

**Comment by zeripath** [comment]
The issue with make test is that it runs with tests logging at trace level .

We need to resurrect the use gitea.com log module and then we can initialise the logger with Json
