### ISSUE TITLE
Excessively long pull request descriptions are not being truncated

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#8900]
- Gitea version (or commit ref): 1.11.0+dev-192-g9ae4c17cb
- Git version: 2.22.0
- Operating system: Linux (Debian Buster)
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (https://try.gitea.io/whalehub/tvrename)
  - [ ] No
  - [ ] Not relevant
- Log gist: N/A

## Description

On GitHub, descriptions of pull requests that exceed the 70 character limit are truncated and the user has the option to click on a button to show the full description. On Gitea, the entire description is displayed no matter how long it is which leads to long descriptions breaking the UI.

## Screenshots

![vivaldi_2019-11-09_22-04-59](https://user-images.githubusercontent.com/44198148/68535148-eea68400-033d-11ea-8181-163cf6a11786.png)

**Comment by zeripath** [comment]
Damn I think this is a regression. I'm sure we used to have this auto truncate.

**Comment by silverwind** [comment]
IIRC, this was previously truncated on the server because getting CSS truncation to work there was borderline impossible last I tried because of the table layout.

**Comment by whalehub** [comment]
@zeripath @silverwind Any update on this?

**Comment by silverwind** [comment]
Example is 404, can you restore?

**Comment by zeripath** [comment]
I'm not getting anything particularly wrong on 1.11.

@whalehub what did you mean about being truncated - do you mean at merge?

**Comment by silverwind** [comment]
It's the last commit description that is overflowing. I played with it a bit but found no easy solution to wrap it. I think it has to either be truncated server-side or made that `<th>` be made a flexbox outside the table.

**Comment by zeripath** [comment]
@silverwind could you give me a bit of the html that's been outputted and I might be able to find which template is creating it.

**Comment by silverwind** [comment]
https://try.gitea.io/silverwind/symlink-test
https://github.com/silverwind/symlink-test

```html
<span class="grey has-emoji commit-summary" title="longlonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglong"><a href="/silverwind/symlink-test/commit/793d9f2cf2022db1d2cb4a4af3a0faf697f3e391" class="default-link">longlonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglong</a>
</span>
```

I'd say, truncate server-side like to 72 chars. Could do similar js expander like we have for multiline messages.

**Comment by zeripath** [comment]
Actually I don't think you need to do server truncation.

as a hack if you change line 9 of commit_page.tmpl to:

```html
<h3 class="has-emoji commit-list"><span class="message-wrapper">{{RenderCommitMessage .Commit.Message $.RepoLink $.Repository.ComposeMetas}}</span>{{template "repo/commit_status" .CommitStatus}}</h3>
```

Then you get wrapping.

Clearly this is not the answer but it does point a way to the solution...
