### ISSUE TITLE
ReUse general translations

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#8906]
we should reuse general termes more often!

found dubble strings in [locale_en-US.ini](https://github.com/go-gitea/gitea/blob/master/options/locale/locale_en-US.ini) :

```
issues.dependency.cancel = Cancel
issues.dependency.remove = Remove
delete_key = Remove
settings.delete_collaborator = Remove
members.remove = Remove
[settings] cancel = Cancel
editor.cancel_lower = Cancel
editor.cancel = Cancel
issues.cancel = Cancel
issues.add_time_cancel = Cancel
issues.cancel_tracking = Cancel
milestones.cancel = Cancel
release.cancel = Cancel
```

and there are more ...

**Comment by guillep2k** [comment]
We should check case by case. In some language families it's possible to use the same word for different concepts or in different context, while in other families you need different words. For example, "day" in English can mean "jour" and "journée" in French and they mean different things. Or in Spanish you need to match the adjective "gender" (feminine/masculine) with the noun.

**Comment by 6543** [comment]
@guillep2k I'll close this issue (cleanup my issue list)
