### ISSUE TITLE
Delete User with default avatar fails

### ISSUE THREAD

**Issue by simonc92** [go-gitea/gitea#891]
- Gitea version (or commit ref): 1.0.0
- Git version: 2.1.4
- Operating system: Debian Jessie
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X] No
  - [ ] Not relevant
- Log gist:  [...uters/admin/users.go:256 DeleteUser()] [E] DeleteUser: Fail to remove /home/user/gitea/data/avatars/4: remove /home/user/gitea/data/avatars/4: no such file or directory

## Description
 When I try to delete a user i get the error above. The user i wanted to delete didnt changed avatar. The user have the default avatar when logged in. (This blue thing).

**Comment by lunny** [comment]
maybe you mean v1.0.1?

**Comment by simonc92** [comment]
Oops my fault. I mean 1.0.0. I updated the Issue.

I was able to delete the user by creating the missing avatar. Just added a file called "4" into data/avatars/.

**Comment by lunny** [comment]
But I think this have been resolved by 1.0.1. Could you try that version?

**Comment by simonc92** [comment]
I updated to 1.0.1. It has been fixed. Thanks a lot. I installed 1.0.0 frim binary because the docs say 1.0.0.

> wget -O gitea https://dl.gitea.io/gitea/1.0.0/gitea-1.0.0-linux-amd64

**Comment by lunny** [comment]
It's a document problem. Let's discuss there.

**Comment by tboerger** [comment]
Dropped the bug and milestone because it have already been fixed.
