### ISSUE TITLE
Can't tab away from selectable dropdown menus

### ISSUE THREAD

**Issue by Jookia** [go-gitea/gitea#8919]
- Gitea version (or commit ref): master
- Git version: master
- Operating system: Debian
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

After merging #8638 selectable dropdown menus now seem to grab focus. I did some bisection on my original branch and found it was introduced just by adding semantic.dropdown.js unchanged from upstream.

**Comment by Jookia** [comment]
I found wrong. The issue is that my fix for clicking not working with the keyboard brought about another problem: Whenever a select box is tabbed away from, the selection is confirmed. This is done by clicking on the element. Which refocuses it like you would expect when clicking normally.

**Comment by ppst0** [comment]
The same problem. Choose create new repo, selecting License and then can't select another field even with mouse click.

Use latest docker image from docker hub (133c950411eb)
![git with screen cap](https://user-images.githubusercontent.com/22620387/68569858-40e7c200-0470-11ea-864f-772524f1cad1.gif)

**Comment by Jookia** [comment]
Ok, #8921 is up as a hotfix. It reverts my change that showed this broken behaviour but it still needs to be fixed properly

**Comment by guillep2k** [comment]
I think this issue can be closed. If anything is missing from ARIA support because of #8921, that should be a different issue.
