### ISSUE TITLE
Feature request: Change destination of PR

### ISSUE THREAD

**Issue by neunzehnachtneun** [go-gitea/gitea#8922]
Just in short, I would really appreciate a feature to change the destination of an existing pull request, like Bitbucket has implemented.

Thanks in advance.

If this feature already exists, please someone could explain how to do. I didn't find it. Neither in the docs nor by try-and-error.

**Comment by guillep2k** [comment]
You mean the target repository/target branch? That would invalidate the PR comments and reviews. What's the point, if it's much easier to create a new PR from the same branch?

**Comment by neunzehnachtneun** [comment]
Well thanks for intervening, I just thought from my use case. I a small project we just decided to merge no longer into master generally but into the develop branch. So a few open PRs need either a destination update or we have to create new PRs based on the old ones. In this specific case this feature would be really useful, as the comments and reviews stay valid.
But in general I totaly agree, to reject this idea.

**Comment by guillep2k** [comment]
As a "once only" workaround you could try updating the pull_request table (make a backup first!) changing the base_branch column to your needs. Make sure to use the index column to refer to PR numbers, since the ID is an internal value and not what you see in the UI.

**Comment by neunzehnachtneun** [comment]
Oh, thanks. This is really helpful.
I will close this issue, as you are right, there are no real use cases for this feature.
