### ISSUE TITLE
Oauth2: Not possible to link existing account

### ISSUE THREAD

**Issue by Shuro** [go-gitea/gitea#8923]
- Gitea version (or commit ref): 1.11.0+dev-210-g74bb292fe (docker / latest)
- Git version: 2.22.0
- Operating system: Vmware PhotonOS (docker)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
  - [x] not possible
- Log gist:

## Description

I migrated my gitea installation to the docker gitea instance, everything works fine so far, except logging in via google Oauth2.

## Steps to reproduce:

1. Visit oauth2 login path: https://git.domain.tld/user/oauth2/Google
2. log in with google account
3. redirect back to https://git.domain.tld/user/link_account# 
4. switch to "Link to Existing Account"
5. Type in Username and press enter

### Expected behavior:
- get asked for user password
- login
- oauth2 account bound

### Actual behavior:
- Landing again on https://git.domain.tld/user/link_account# , register tab
- switch to "Link to Existing Account" reveals the error: "Password cannot be empty."
- there was and is no password field (see attached screenshot)

## Screenshots

![Bildschirmfoto_2019-11-11_15-29-49](https://user-images.githubusercontent.com/944030/68595255-60dfab80-0499-11ea-9ca8-cd07ed44353a.png)

**Comment by baxandrei** [comment]
I have same problem.

**Comment by SkYNewZ** [comment]
Move to `Gitea version 1.10.1 built with GNU Make 4.1, go1.13.4 : bindata, sqlite, sqlite_unlock_notify` has fixed this issue for me https://github.com/go-gitea/gitea/issues/9066

**Comment by zeripath** [comment]
Ok closing as fixed. Please reopen if still a problem.
