### ISSUE TITLE
add 'fp-info-cache' to the default kicad ignore file.

### ISSUE THREAD

**Issue by a7hybnj2** [go-gitea/gitea#8928]
The default kicad ignore file should have 'fp-info-cache' included. It is a file the does not need to be tracked.

**Comment by a7hybnj2** [comment]
I just learned of gitignore.io and they have fp-info-cache in their defaults for kicad.

**Comment by zeripath** [comment]
It's already in there on master:

https://github.com/go-gitea/gitea/blob/f88715e29c8cd6865b69eb8e692d051d977e93a5/options/gitignore/KiCad#L15

**Comment by a7hybnj2** [comment]
@zeripath what version is master? I just upgraded to 1.10.1 and its still not there. Any idea when master will become a release?

**Comment by zeripath** [comment]
it will be 1.11. We'll have a RC soonish I think
