### ISSUE TITLE
Using gitea:latest docker image cant change theme?

### ISSUE THREAD

**Issue by thepenguinthatwants** [go-gitea/gitea#8929]
Hi!
Using docker-compose and traefik
postgres:9.6 and gitea/gitea:latest

I changed the registration settings on app.ini and it worked but adding this

[ui]
THEMES = arc-green
DEFAULT_THEME = arc-green
THEME_COLOR_META_TAG = `#6cc644`

didnt change the default theme.

**Comment by thepenguinthatwants** [comment]
It did change the gloabl theme, but didnt change the users theme?

**Comment by sapk** [comment]
Currently, if the user as the default theme (not arc-green) set before it will keep the default theme currently but will not be able to set it again if it change from the settings.

An easy fix should be to check available theme here: https://github.com/go-gitea/gitea/blob/01a4a7cb14b3a48f9e8115d5bc93af7ae17f1275/models/user.go#L196
with a func similar to https://github.com/go-gitea/gitea/blob/171b3598778a1ecd0a921c71ed6755bfef68f7f0/modules/auth/user_form.go#L253 which check if theme exist.

**Comment by thepenguinthatwants** [comment]
Hi!

Thanks for the explanation.

**Comment by fractalf** [comment]
You can change the theme of an existing user by editing the database
```
sqlite> select id,name,theme from user;
1|foobar|gitea
sqlite> update user set theme='arc-green' where id=1;
sqlite> select id,name,theme from user;
1|foobar|arc-green
```
