### ISSUE TITLE
Spelling mistake

### ISSUE THREAD

**Issue by rmbleeker** [go-gitea/gitea#8933]
There is a spelling error in the following line:
https://github.com/go-gitea/gitea/blob/e4e6d48e30da944192263f7ad812dfa78f03ae27/options/locale/locale_en-US.ini#L1715
This should read "Maxim**um** number of repositories"

**Comment by guillep2k** [comment]
@rmbleeker Thank you!

**Comment by rmbleeker** [comment]
You're welcome. We've been using Gitea for quite a while now within our organization but the error only just caught my eye.
