### ISSUE TITLE
dump stops after first line

### ISSUE THREAD

**Issue by michaelboke** [go-gitea/gitea#8941]
- Gitea version (or commit ref): 1.11.0+dev-218-g4b3fc7493 built with GNU Make 4.2.1, go1.13.4 : bindata, sqlite, sqlite_unlock_notify
- Git version: 2.22.0
- Operating system: Linux / docker
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:

## Description

I am trying to make a dump for a backup of my database and repository but the dump command stops right after the first line of output.

```
bash-5.0$ gitea dump -V
2019/11/12 23:57:15 ...dules/setting/git.go:87:newGit() [I] Git Version: 2.22.0, Wire Protocol Version 2 Enabled
bash-5.0$ 
```

No backup file or whatsoever is created. I was actually on the way of exporting the data and migrate to postgres. Some help or pointers would be appreciated.

**Comment by techknowlogick** [comment]
Could you attempt using the `-c` flag on this command and pass the full path to the config file? This seems like you are `exec`-ing into the docker container, and by doing so you have a different workingdir.

**Comment by michaelboke** [comment]
No i do think i got it already, i checked out the code and started debugging with breakpoints.

It seems that a migration went wrong and did not added some columns to the sqlite database, but for some reason it was reporting it was on version 109. So i put this back to 107 and run the migrations again. Now it is working and exporting again.

The funny part is that i did not get the error messages output, although in the code there are some lines  like `log.Fatalf` but those are not output to the console. (seems to be in the log file)

But thanks, will close this one now
