### ISSUE TITLE
"You cannot upload any more files"

### ISSUE THREAD

**Issue by jscottelblein** [go-gitea/gitea#8947]
Using the latest Gitea, I'm trying to drop a folder containing a bunch of files into the File Upload area, and after about 5 successful uploads, any beyond that just show a thumbnail with an X over it, and the above tooltip on them.

Is there some way around this so I can upload as many as I want at once? I don't immediately see anything in the config area.

**Comment by lunny** [comment]
```ini
[repository.upload]
; Max number of files per upload. Defaults to 5
MAX_FILES = 5
```
