### ISSUE TITLE
[BUG] [UI] emoji dont work in markdown list

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#8953]
version 1.10.0 and current

preview: https://gitea.com/gitea/gitea.com/issues/8

**Comment by guillep2k** [comment]
This is something that should be done on the client side (like GitHub does). Adding it to markdown will probably create a lot of incompatibilities, and it's also a unnecessary burden for the server.

I'm sure there must be some cool js library add-on we could add for this. 😉

**Comment by mrsdizzie** [comment]
Agree, this is another example of why the library we use (emojify) isn't great compared to what Github and others have which allow this feature to work here (github).

**Comment by mrsdizzie** [comment]
Looks like Github uses this:

 https://github.com/github/gemoji

And perhaps this is a somewhat similar go equivalent (or at least a place to start):

 https://godoc.org/github.com/knq/emoji
