### ISSUE TITLE
Favicon missing

### ISSUE THREAD

**Issue by rugk** [go-gitea/gitea#896]
- Gitea version (or commit ref): 1.0.1
- Operating system: Debian
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant

## Description

After upgrading from Gogs, my favicon is wrong. I've installed gitea in a subdirectory, so I am using a special `ROOT_URL` with a subdir.

In Gogs I had the right favicon, but Gitea seems to not include it in the HTML source, so Firefox uses the `favicon.ico` at the root URL, which is obviously wrong.

**Comment by rugk** [comment]
Your bountysource is destroying the formatting/markdown of these issues…

**Comment by bkcsoft** [comment]
BountySource is a known issue yes :)

**Comment by rugk** [comment]
I think this was a caching issue. When you can reproduce it you can reopen it.
