### ISSUE TITLE
[BUG] [API] GET /user "language" empty

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#8961]
version current gitea.com

return "language": "" eaven if English is set in profile

**Comment by lunny** [comment]
Is this a bug?

**Comment by 6543** [comment]
Dont know ... ned more research ...

**Comment by 6543** [comment]
@lunny I'll look at it if this is a privacy feature or a bug ...

**Comment by 6543** [comment]
@lunny it is a bug .. send PR
