### ISSUE TITLE
Do not remove public/ dir

### ISSUE THREAD

**Issue by rugk** [go-gitea/gitea#897]
I saw you switched to the one-binary-to-rule-it-all system… :smile: 

However I'd just wanted to let you know that it is really useful to have all the static files in one directory (`/public`). E.g. when using an reverse-proxy as nginx you can serve these files faster and maybe even pre-compressed (statically), which is easy when you have all files to serve in one dir.
Also you can easily set come caching headers in nginx for instance.

Currently I am using the dir from this repo, so please do not remove it.

**Comment by lunny** [comment]
That's an option on compile process

**Comment by tboerger** [comment]
Why should we remove this directory? It's just embedded into our prebuilt binaries. Maybe we can publish at some point the public directory together with the binaries, than you can easily serve the public files on your own.
