### ISSUE TITLE
Minify semantic.dropdown.custom.js

### ISSUE THREAD

**Issue by guillep2k** [go-gitea/gitea#8971]
Thanks to #8598 now `/js/index.js` minified (58KB👍). However, `/js/semantic.dropdown.custom.js` (141KB) is still not (it's not a vendored library).

**Comment by silverwind** [comment]
We can import from `index.js` so it will be put in the main bundle. I'm working on a PR that will enable us to use `import` syntax and other modern JS features.

**Comment by lunny** [comment]
I also send a #8975 to allow us pack serval js to index.js.

**Comment by silverwind** [comment]
@Jookia is there some way to verify whether the customization from https://github.com/go-gitea/gitea/pull/8638 works? For example on https://try.gitea.io/repo/create, I don't see any `aria-*` attributes on the dropdown HTML. Is it already broken?

````html
<div class="ui selection owner dropdown" tabindex="0">
  <input type="hidden" id="uid" name="uid" value="476" required="">
  <span class="text" title="silverwind"><img class="ui mini image" src="/user/avatar/silverwind/-1">
      silverwind</span>
  <i class="dropdown icon" tabindex="0"><div class="menu" tabindex="-1"></div></i>
  <div class="menu" tabindex="-1">
    <div class="item active selected" data-value="476" title="silverwind" tabindex="-1">
      <img class="ui mini image" src="/user/avatar/silverwind/-1">
      silverwind
    </div>
      <div class="item" data-value="16251" title="silverwind-org" tabindex="-1">
        <img class="ui mini image" src="/user/avatar/silverwind-org/-1">
        silverwind-org
      </div>
      <div class="item" data-value="1069" title="my-cool-organization" tabindex="-1">
        <img class="ui mini image" src="/user/avatar/my-cool-organization/-1">
        my-cool-organization
      </div>
  </div>
</div>

**Comment by Jookia** [comment]
That's not a dropdown menu, it's a dropdown selection. The language selection at the bottom of the page has aria-* attributes

**Comment by silverwind** [comment]
Thanks, I see the attributes there.
