### ISSUE TITLE
GitHub Releases: Markdown format hiccups (1.9.5 & 1.9.6)

### ISSUE THREAD

**Issue by HenrikBengtsson** [go-gitea/gitea#8977]
I noticed that there were some Markdown issues here on GitHub for the [1.9.5 release](https://github.com/go-gitea/gitea/releases/tag/v1.9.5).  It looks like there's a missing newline or whitespace, which causes the updates to be rendered as raw monospace text.  I thought it was a one time mistake, but it happened to today's [1.9.6 release](https://github.com/go-gitea/gitea/releases/tag/v1.9.6) as well, so, maybe an issue with the @GiteaBot(?!?).

![gitea-1 9 6](https://user-images.githubusercontent.com/1616850/68820159-447d7380-063f-11ea-8317-8c7b6865cbaf.png)

![gitea-1 9 5](https://user-images.githubusercontent.com/1616850/68820241-80183d80-063f-11ea-85c9-9db9c9e60cb3.png)

![gitea-1 9 4](https://user-images.githubusercontent.com/1616850/68820202-62e36f00-063f-11ea-8551-f55410ce08f3.png)

**Comment by techknowlogick** [comment]
Thanks for the report :)

Giteabot takes the text from when we tag, and GH treats it as plaintext, so we have to manually go in and clean up it later. There are only a few of us with access to edit these notes, and so they haven't been cleaned up yet. I will update this now.

**Comment by HenrikBengtsson** [comment]
Got it and thxs. Didn't know it could be edited afterward.
