### ISSUE TITLE
highlight.js stylesheet clashes with dark mode for markdown code blocks

### ISSUE THREAD

**Issue by charlesreid1** [go-gitea/gitea#8980]
- Gitea version (or commit ref):

```
$ curl -X GET "https://git.charlesreid1.com/api/v1/version" -H  "accept: application/json"
{"version":"1.11.0+dev-234-gdad67cae5"}
```

- Git version:

```
$ git --version
git version 2.23.0
```

- Operating system: `linux`
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes - https://try.gitea.io/asdf_asdf_asdf/test-repo
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

Currently, the order in which CSS stylesheets are applied means that a stylesheet from highlight.js called `default.min.css` gets applied _before_ the dark mode theme stylesheet `theme-arc-green.css`. It redefines the color of `.hljs` text to be dark and hard to make out against the background of the gitea dark theme. (I notice this stylesheet does not affect try.gitea.io, but does affect the version referenced above.)

There is also a `style.bundle.css` that gets applied before `theme-arc-green.css`. I actually cannot figure out where this stylesheet comes from. I've scoured the templates and modules but haven't found anything. This stylesheet also defines the color of text in the `.hljs` class to be dark.

Further deepening the mystery, the CSS files mentioned above are not in the raw html of the page included with `<link>` tags, they seem to be automatically inserted or applied after/on top of `theme-arc-green.css`. Without these stylesheets, the color scheme looks the way it's supposed to.

## Screenshots

<img width="1136" alt="Screen Shot 2019-11-14 at 00 35 08 " src="https://user-images.githubusercontent.com/368075/68839983-a4dbd780-0676-11ea-9034-9e1db99789ab.png">

Here is a shot from the Firefox inspector, with the color attribute set and unset:

<img width="1531" alt="Screen Shot 2019-11-14 at 00 36 24 " src="https://user-images.githubusercontent.com/368075/68840121-eff5ea80-0676-11ea-9e55-c7fa4e43a331.png">

<img width="1515" alt="Screen Shot 2019-11-14 at 00 36 34 " src="https://user-images.githubusercontent.com/368075/68840156-fbe1ac80-0676-11ea-9427-be70fe13e193.png">

**Comment by charlesreid1** [comment]
I should also mention that I tried to define a more readable text color in custom CSS and added a `<link>` to it in `custom/templates/custom/header.tmpl`, but this did not work for the same reason that `theme-arc-green.css` does not have its style applied - namely, whatever mechanism is applying these stylesheets applies them after those custom CSS styles are applied.

**Comment by silverwind** [comment]
We probably need add `!important` on the conflicting classes in `theme-arc-green.css` to fix.

**Comment by silverwind** [comment]
I can't seem to reproduce in https://try.gitea.io/asdf_asdf_asdf/test-repo in Firefox:

![image](https://user-images.githubusercontent.com/115237/68955812-204c9e80-07c7-11ea-9bfd-3bffe11dddc4.png)

The winning `color` rule is

![image](https://user-images.githubusercontent.com/115237/68955898-43774e00-07c7-11ea-92cc-f089605be62d.png)

So I do wonder where your `style.bundle.css` comes from, we don't serve it. Can you try disabling browser extensions?

**Comment by charlesreid1** [comment]
aww heck, all that sleuthing and it was a browser extension all along. thanks for looking into it!
