### ISSUE TITLE
Could the "Quote reply" be added to issue function?

### ISSUE THREAD

**Issue by suli3** [go-gitea/gitea#8989]
- Gitea version (or commit ref):1.9.5
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

Now the reply in the issue is parallel, but occasionally I need to reply to someone's reply, can I achieve the reply to the corresponding post? I think it may something like "Quote reply"?

## Screenshots
![image](https://user-images.githubusercontent.com/1057425/68867710-445da080-0731-11ea-8fd6-8333522dd136.png)

**Comment by lunny** [comment]
We could add a menu on the right upside of the comment like github did.

<img width="324" alt="图片" src="https://user-images.githubusercontent.com/81045/68914975-53793880-079b-11ea-9362-c1b61d9a3ab5.png">

**Comment by jolheiser** [comment]
This is part of #9043
