### ISSUE TITLE
ORM Warnings on start

### ISSUE THREAD

**Issue by markusamshove** [go-gitea/gitea#8994]
- Gitea version (or commit ref): 1.9.6
- Git version: 2.12.3
- Operating system: SuSe Linux Enterprise 12
- Database (use `[x]`):
  - [x] PostgreSQL 9.6.9
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

```
Postgres 9.6.9 

2019/11/14 17:57:27 ...-xorm/xorm/engine.go:329:Ping() [I] PING DATABASE postgres 
2019/11/14 17:57:28 models/models.go:305:NewEngine() [W] Table user Column max_repo_creation db default is '-1'::integer, struct default is -1 
2019/11/14 17:57:28 models/models.go:305:NewEngine() [W] Table user Column diff_view_style db default is '''::character varying', struct default is '' 
2019/11/14 17:57:28 models/models.go:305:NewEngine() [W] Table user Column theme db default is '''::character varying', struct default is '' 
2019/11/14 17:57:28 models/models.go:305:NewEngine() [W] Table webhook Column http_method db default is ''POST'::character varying', struct default is 
2019/11/14 17:57:28 models/models.go:305:NewEngine() [W] Table gpg_key column key_id db type is VARCHAR(16), struct type is CHAR(16) 
2019/11/14 17:57:28 models/models.go:305:NewEngine() [W] Table gpg_key column primary_key_id db type is VARCHAR(16), struct type is CHAR(16) 
2019/11/14 17:57:28 models/models.go:305:NewEngine() [W] Table gpg_key_import column key_id db type is VARCHAR(16), struct type is CHAR(16) 
2019/11/14 17:57:28 models/models.go:305:NewEngine() [W] Table commit_status column context_hash db type is VARCHAR(40), struct type is CHAR(40) 
2019/11/14 17:57:28 models/models.go:305:NewEngine() [W] Table review column type db type is VARCHAR(255), struct type is INTEGER 
2019/11/14 17:57:28 models/models.go:305:NewEngine() [W] Table comment has column old_assignee_id but struct has not related field 
2019/11/14 17:57:28 routers/init.go:84:GlobalInit() [I] ORM engine initialization successful!
```

## Description

We get the warnings you can see above this when (re)starting Gitea.
They aren't a result of my update from 1.9.5 to 1.9.6, as some of them were there for a long time, I just haven't come around to open an issue :-)

Is there any way for Gitea to resolve this? Did some migrations not work or does Gitea not do database schema changes?

**Comment by lunny** [comment]
This should be bug of xorm.

**Comment by lunny** [comment]
```
2019/11/14 17:57:28 models/models.go:305:NewEngine() [W] Table user Column max_repo_creation db default is '-1'::integer, struct default is -1 
2019/11/14 17:57:28 models/models.go:305:NewEngine() [W] Table user Column diff_view_style db default is '''::character varying', struct default is '' 
2019/11/14 17:57:28 models/models.go:305:NewEngine() [W] Table user Column theme db default is '''::character varying', struct default is '' 
```

**Comment by MarkusAmshove** [comment]
So I should not do anything? :-)

**Comment by MarkusAmshove** [comment]
I just did the upgrade to 1.10 and some warnings got added :-)

2019/11/16 11:51:11 routers/init.go:53:initDBEngine() [I] ORM engine initialization attempt #1/10...
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:330:Ping() [I] PING DATABASE postgres
2019/11/16 11:51:11 ...ations/migrations.go:300:Migrate() [I] Migration[89]: add original author/url migration info to issues, comments, and repo 
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table issue has column id but struct has not related field
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table issue has column repo_id but struct has not related field
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table issue has column index but struct has not related field
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table issue has column poster_id but struct has not related field
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table issue has column name but struct has not related field
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table issue has column content but struct has not related field
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table issue has column milestone_id but struct has not related field
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table issue has column priority but struct has not related field
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table issue has column is_closed but struct has not related field
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table issue has column is_pull but struct has not related field
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table issue has column num_comments but struct has not related field
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table issue has column ref but struct has not related field
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table issue has column deadline_unix but struct has not related field
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table issue has column created_unix but struct has not related field
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table issue has column updated_unix but struct has not related field
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table issue has column closed_unix but struct has not related field
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table issue has column is_locked but struct has not related field
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table comment has column id but struct has not related field
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table comment has column type but struct has not related field
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table comment has column poster_id but struct has not related field
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table comment has column issue_id but struct has not related field
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table comment has column label_id but struct has not related field
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table comment has column old_milestone_id but struct has not related field
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table comment has column milestone_id but struct has not related field
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table comment has column old_assignee_id but struct has not related field
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table comment has column assignee_id but struct has not related field
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table comment has column old_title but struct has not related field
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table comment has column new_title but struct has not related field
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table comment has column commit_id but struct has not related field
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table comment has column line but struct has not related field
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table comment has column content but struct has not related field
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table comment has column created_unix but struct has not related field
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table comment has column updated_unix but struct has not related field
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table comment has column commit_sha but struct has not related field
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table comment has column removed_assignee but struct has not related field
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table comment has column dependent_issue_id but struct has not related field
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table comment has column tree_path but struct has not related field
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table comment has column patch but struct has not related field
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table comment has column review_id but struct has not related field
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table comment has column invalidated but struct has not related field
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table repository has column id but struct has not related field
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table repository has column owner_id but struct has not related field
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table repository has column lower_name but struct has not related field
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table repository has column name but struct has not related field
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table repository has column description but struct has not related field
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table repository has column website but struct has not related field
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table repository has column default_branch but struct has not related field
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table repository has column num_watches but struct has not related field
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table repository has column num_stars but struct has not related field
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table repository has column num_forks but struct has not related field
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table repository has column num_issues but struct has not related field
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table repository has column num_closed_issues but struct has not related field
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table repository has column num_pulls but struct has not related field
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table repository has column num_closed_pulls but struct has not related field
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table repository has column num_milestones but struct has not related field
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table repository has column num_closed_milestones but struct has not related field
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table repository has column is_private but struct has not related field
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table repository has column is_mirror but struct has not related field
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table repository has column is_fork but struct has not related field
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table repository has column fork_id but struct has not related field
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table repository has column size but struct has not related field
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table repository has column created_unix but struct has not related field
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table repository has column updated_unix but struct has not related field
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table repository has column is_fsck_enabled but struct has not related field
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table repository has column topics but struct has not related field
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table repository has column is_empty but struct has not related field
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table repository has column close_issues_via_commit_in_any_branch but struct has not related field
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table repository has column is_archived but struct has not related field
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table repository has column avatar but struct has not related field
2019/11/16 11:51:11 ...ations/migrations.go:300:Migrate() [I] Migration[90]: change length of some repository columns
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table repository Column id db default is nextval('repository_id_seq'::regclass), struct default is 
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table repository has column owner_id but struct has not related field
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table repository has column lower_name but struct has not related field
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table repository has column name but struct has not related field
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table repository has column default_branch but struct has not related field
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table repository has column num_watches but struct has not related field
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table repository has column num_stars but struct has not related field
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table repository has column num_forks but struct has not related field
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table repository has column num_issues but struct has not related field
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table repository has column num_closed_issues but struct has not related field
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table repository has column num_pulls but struct has not related field
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table repository has column num_closed_pulls but struct has not related field
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table repository has column num_milestones but struct has not related field
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table repository has column num_closed_milestones but struct has not related field
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table repository has column is_private but struct has not related field
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table repository has column is_mirror but struct has not related field
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table repository has column is_fork but struct has not related field
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table repository has column fork_id but struct has not related field
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table repository has column size but struct has not related field
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table repository has column created_unix but struct has not related field
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table repository has column updated_unix but struct has not related field
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table repository has column is_fsck_enabled but struct has not related field
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table repository has column topics but struct has not related field
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table repository has column is_empty but struct has not related field
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table repository has column close_issues_via_commit_in_any_branch but struct has not related field
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table repository has column is_archived but struct has not related field
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table repository has column avatar but struct has not related field
2019/11/16 11:51:11 ...ations/migrations.go:300:Migrate() [I] Migration[91]: add index on owner_id of repository and type, review_id of comment
2019/11/16 11:51:11 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table repository Column id db default is nextval('repository_id_seq'::regclass), struct default is 
2019/11/16 11:51:12 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table repository has column lower_name but struct has not related field
2019/11/16 11:51:12 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table repository has column name but struct has not related field
2019/11/16 11:51:12 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table repository has column description but struct has not related field
2019/11/16 11:51:12 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table repository has column website but struct has not related field
2019/11/16 11:51:12 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table repository has column default_branch but struct has not related field
2019/11/16 11:51:12 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table repository has column num_watches but struct has not related field
2019/11/16 11:51:12 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table repository has column num_stars but struct has not related field
2019/11/16 11:51:12 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table repository has column num_forks but struct has not related field
2019/11/16 11:51:12 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table repository has column num_issues but struct has not related field
2019/11/16 11:51:12 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table repository has column num_closed_issues but struct has not related field
2019/11/16 11:51:12 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table repository has column num_pulls but struct has not related field
2019/11/16 11:51:12 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table repository has column num_closed_pulls but struct has not related field
2019/11/16 11:51:12 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table repository has column num_milestones but struct has not related field
2019/11/16 11:51:12 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table repository has column num_closed_milestones but struct has not related field
2019/11/16 11:51:12 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table repository has column is_private but struct has not related field
2019/11/16 11:51:12 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table repository has column is_mirror but struct has not related field
2019/11/16 11:51:12 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table repository has column is_fork but struct has not related field
2019/11/16 11:51:12 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table repository has column fork_id but struct has not related field
2019/11/16 11:51:12 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table repository has column size but struct has not related field
2019/11/16 11:51:12 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table repository has column created_unix but struct has not related field
2019/11/16 11:51:12 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table repository has column updated_unix but struct has not related field
2019/11/16 11:51:12 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table repository has column is_fsck_enabled but struct has not related field
2019/11/16 11:51:12 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table repository has column topics but struct has not related field
2019/11/16 11:51:12 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table repository has column is_empty but struct has not related field
2019/11/16 11:51:12 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table repository has column close_issues_via_commit_in_any_branch but struct has not related field
2019/11/16 11:51:12 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table repository has column is_archived but struct has not related field
2019/11/16 11:51:12 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table repository has column avatar but struct has not related field
2019/11/16 11:51:12 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table repository has column original_url but struct has not related field
2019/11/16 11:51:12 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table comment Column id db default is nextval('comment_id_seq'::regclass), struct default is 
2019/11/16 11:51:12 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table comment has column poster_id but struct has not related field
2019/11/16 11:51:12 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table comment has column issue_id but struct has not related field
2019/11/16 11:51:12 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table comment has column label_id but struct has not related field
2019/11/16 11:51:12 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table comment has column old_milestone_id but struct has not related field
2019/11/16 11:51:12 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table comment has column milestone_id but struct has not related field
2019/11/16 11:51:12 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table comment has column old_assignee_id but struct has not related field
2019/11/16 11:51:12 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table comment has column assignee_id but struct has not related field
2019/11/16 11:51:12 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table comment has column old_title but struct has not related field
2019/11/16 11:51:12 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table comment has column new_title but struct has not related field
2019/11/16 11:51:12 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table comment has column commit_id but struct has not related field
2019/11/16 11:51:12 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table comment has column line but struct has not related field
2019/11/16 11:51:12 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table comment has column content but struct has not related field
2019/11/16 11:51:12 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table comment has column created_unix but struct has not related field
2019/11/16 11:51:12 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table comment has column updated_unix but struct has not related field
2019/11/16 11:51:12 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table comment has column commit_sha but struct has not related field
2019/11/16 11:51:12 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table comment has column removed_assignee but struct has not related field
2019/11/16 11:51:12 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table comment has column dependent_issue_id but struct has not related field
2019/11/16 11:51:12 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table comment has column tree_path but struct has not related field
2019/11/16 11:51:12 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table comment has column patch but struct has not related field
2019/11/16 11:51:12 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table comment has column invalidated but struct has not related field
2019/11/16 11:51:12 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table comment has column original_author but struct has not related field
2019/11/16 11:51:12 ...-xorm/xorm/engine.go:1331:Sync2() [W] Table comment has column original_author_id but struct has not related field
```

**Comment by lunny** [comment]
I will check that.

**Comment by tuxmaster5000** [comment]
The same using pgsql 12 on centos 7

> ...dules/setting/log.go:230:newLogService() [I] Gitea v1.10.1 built with GNU Make 4.1, go1.13.4 : bindata, sqlite, sqlite_unlock_notify
> models/models.go:180:NewEngine() [W] Table user Column id db default is nextval('user_id_seq'::regclass), struct default is
> models/models.go:180:NewEngine() [W] Table user Column max_repo_creation db default is '-1'::integer, struct default is -1
> models/models.go:180:NewEngine() [W] Table public_key Column id db default is nextval('public_key_id_seq'::regclass), struct default is
> models/models.go:180:NewEngine() [W] Table access_token Column id db default is nextval('access_token_id_seq'::regclass), struct default is
> models/models.go:180:NewEngine() [W] Table repository Column id db default is nextval('repository_id_seq'::regclass), struct default is
> models/models.go:180:NewEngine() [W] Table repository Column original_service_type db default is 0, struct default is
> models/models.go:180:NewEngine() [W] Table deploy_key Column id db default is nextval('deploy_key_id_seq'::regclass), struct default is
> models/models.go:180:NewEngine() [W] Table collaboration Column id db default is nextval('collaboration_id_seq'::regclass), struct default is
> models/models.go:180:NewEngine() [W] Table access Column id db default is nextval('access_id_seq'::regclass), struct default is
> models/models.go:180:NewEngine() [W] Table upload Column id db default is nextval('upload_id_seq'::regclass), struct default is
> models/models.go:180:NewEngine() [W] Table watch Column id db default is nextval('watch_id_seq'::regclass), struct default is
> models/models.go:180:NewEngine() [W] Table star Column id db default is nextval('star_id_seq'::regclass), struct default is
> models/models.go:180:NewEngine() [W] Table follow Column id db default is nextval('follow_id_seq'::regclass), struct default is
> models/models.go:180:NewEngine() [W] Table action Column id db default is nextval('action_id_seq'::regclass), struct default is
> models/models.go:180:NewEngine() [W] Table issue Column id db default is nextval('issue_id_seq'::regclass), struct default is
> models/models.go:180:NewEngine() [W] Table pull_request Column id db default is nextval('pull_request_id_seq'::regclass), struct default is
> models/models.go:180:NewEngine() [W] Table comment Column id db default is nextval('comment_id_seq'::regclass), struct default is
> models/models.go:180:NewEngine() [W] Table attachment Column id db default is nextval('attachment_id_seq'::regclass), struct default is
> models/models.go:180:NewEngine() [W] Table label Column id db default is nextval('label_id_seq'::regclass), struct default is
> models/models.go:180:NewEngine() [W] Table issue_label Column id db default is nextval('issue_label_id_seq'::regclass), struct default is
> models/models.go:180:NewEngine() [W] Table milestone Column id db default is nextval('milestone_id_seq'::regclass), struct default is
> models/models.go:180:NewEngine() [W] Table mirror Column id db default is nextval('mirror_id_seq'::regclass), struct default is
> models/models.go:180:NewEngine() [W] Table release Column id db default is nextval('release_id_seq'::regclass), struct default is
> models/models.go:180:NewEngine() [W] Table login_source Column id db default is nextval('login_source_id_seq'::regclass), struct default is
> models/models.go:180:NewEngine() [W] Table webhook Column id db default is nextval('webhook_id_seq'::regclass), struct default is
> models/models.go:180:NewEngine() [W] Table hook_task Column id db default is nextval('hook_task_id_seq'::regclass), struct default is
> models/models.go:180:NewEngine() [W] Table team Column id db default is nextval('team_id_seq'::regclass), struct default is
> models/models.go:180:NewEngine() [W] Table org_user Column id db default is nextval('org_user_id_seq'::regclass), struct default is
> models/models.go:180:NewEngine() [W] Table team_user Column id db default is nextval('team_user_id_seq'::regclass), struct default is
> models/models.go:180:NewEngine() [W] Table team_repo Column id db default is nextval('team_repo_id_seq'::regclass), struct default is
> models/models.go:180:NewEngine() [W] Table notice Column id db default is nextval('notice_id_seq'::regclass), struct default is
> models/models.go:180:NewEngine() [W] Table email_address Column id db default is nextval('email_address_id_seq'::regclass), struct default is
> models/models.go:180:NewEngine() [W] Table notification Column id db default is nextval('notification_id_seq'::regclass), struct default is
> models/models.go:180:NewEngine() [W] Table issue_user Column id db default is nextval('issue_user_id_seq'::regclass), struct default is
> models/models.go:180:NewEngine() [W] Table lfs_meta_object Column id db default is nextval('lfs_meta_object_id_seq'::regclass), struct default is
> models/models.go:180:NewEngine() [W] Table two_factor Column id db default is nextval('two_factor_id_seq'::regclass), struct default is
> models/models.go:180:NewEngine() [W] Table gpg_key Column id db default is nextval('gpg_key_id_seq'::regclass), struct default is
> models/models.go:180:NewEngine() [W] Table gpg_key column key_id db type is VARCHAR(16), struct type is CHAR(16)
> models/models.go:180:NewEngine() [W] Table gpg_key column primary_key_id db type is VARCHAR(16), struct type is CHAR(16)
> models/models.go:180:NewEngine() [W] Table gpg_key_import column key_id db type is VARCHAR(16), struct type is CHAR(16)
> models/models.go:180:NewEngine() [W] Table repo_unit Column id db default is nextval('repo_unit_id_seq'::regclass), struct default is
> models/models.go:180:NewEngine() [W] Table repo_redirect Column id db default is nextval('repo_redirect_id_seq'::regclass), struct default is
> models/models.go:180:NewEngine() [W] Table protected_branch Column id db default is nextval('protected_branch_id_seq'::regclass), struct default is
> models/models.go:180:NewEngine() [W] Table user_open_id Column id db default is nextval('user_open_id_id_seq'::regclass), struct default is
