### ISSUE TITLE
How I can change meta theme-color

### ISSUE THREAD

**Issue by BaxAndrei** [go-gitea/gitea#8998]
- Gitea version (or commit ref): 1.10.0-rc2
- Git version: 2.23.0 
- Operating system:  CentOS Linux release 7.7.1908
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes: https://www.git.baxandrei.ro/
  - [ ] No
  - [ ] Not relevant
- Log gist: ---

## Description
I want to change the theme-color meta and I can't find any information anywhere to help me with this. I tried changing the THEME_COLOR_META_TAG configuration but it didn't work.
...

## Screenshots

**Comment by jolheiser** [comment]
Can you provide your app.ini?
According to your linked URL, theme-meta is `#6cc644`

**Comment by baxandrei** [comment]
```
[ui]
EXPLORE_PAGING_NUM		= 20
ISSUE_PAGING_NUM		= 10
FEED_MAX_COMMIT_NUM		= 5
GRAPH_MAX_COMMIT_NUM	= 100
DEFAULT_THEME			= gitea
THEMES					= gitea,arc-green
THEME_COLOR_META_TAG 	= #27ae60
```

**Comment by jolheiser** [comment]
Did you restart Gitea after modifying the app.ini?

**Comment by baxandrei** [comment]
Yes, 3 times, nothing changed ;(

**Comment by jolheiser** [comment]
Ah, this suffers from a `.ini` problem. The `#` is turning everything after it into a comment....

**Comment by baxandrei** [comment]
Oh, you're right. I completely forgot about this! Thank you very much.
