### ISSUE TITLE
I can`t see wiki page revision

### ISSUE THREAD

**Issue by BaxAndrei** [go-gitea/gitea#8999]
- Gitea version (or commit ref): 1.10.0-rc2
- Git version: 2.23.0 
- Operating system:  CentOS Linux release 7.7.1908
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes
  - [ ] No
  - [x] Not relevant
- Log gist: ---

## Description
When I go to the revision history of a wiki page and click on the revision code, it does not go to see the history of the changes as in commits.
...

## Screenshots

**Comment by lunny** [comment]
Please give move details. We cannot know what happened according your description.

**Comment by baxandrei** [comment]
If I press here, I can see history of modification
![image](https://user-images.githubusercontent.com/12484505/68994852-1e024700-0890-11ea-8b7a-2851f2eb49f9.png)


but, for wiki, it don`t work in same way:
![image](https://user-images.githubusercontent.com/12484505/68994858-34a89e00-0890-11ea-90b7-9b707928dd2a.png)
