### ISSUE TITLE
Ho to build?

### ISSUE THREAD

**Issue by ZeroZs** [go-gitea/gitea#900]
1. I use insctruction: https://docs.gitea.io/en-us/install-from-source/
2. Install go with -> Download the Go distribution
3. I use the command in cmd
go get -d -u code.gitea.io/gitea
result: 
![untitled](https://cloud.githubusercontent.com/assets/25699030/22850677/ff734230-f01e-11e6-8c18-25b261f873d1.png)

**Comment by minecrafter** [comment]
You need to set the `GOPATH`: https://golang.org/doc/install

**Comment by ZeroZs** [comment]
Oops... sorry:
![untitled](https://cloud.githubusercontent.com/assets/25699030/22850717/a1a9e824-f01f-11e6-9473-c2b016ade33b.png)

**Comment by ZeroZs** [comment]
Collected...

In what may be the problem today?
![untitled](https://cloud.githubusercontent.com/assets/25699030/22850954/6ac7442c-f025-11e6-8bdd-1f280ba92507.png)
