### ISSUE TITLE
How I can change Discord webhook color?

### ISSUE THREAD

**Issue by BaxAndrei** [go-gitea/gitea#9000]
- Gitea version (or commit ref): 1.10.0-rc2
- Git version: 2.23.0 
- Operating system:  CentOS Linux release 7.7.1908
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes
  - [ ] No
  - [x] Not relevant
- Log gist: ---

## Description
I can't find an option to change the color for the discord webhook anywhere. I remember when using Gogs it was an option when adding the webhook.
...

## Screenshots
![image](https://user-images.githubusercontent.com/12484505/68892071-cdbda480-072a-11ea-91f5-ca4bb9051a30.png)

**Comment by jolheiser** [comment]
In v1.11.0 these will be updated to be much more diverse depending on context.  
Unfortunately they are not configurable currently.

**Comment by lunny** [comment]
We can add some configurations like:

```ini
[webhook.discord]
color=#000000
...
```

**Comment by baxandrei** [comment]
Ok, thanks. Keep me in touch.

**Comment by baxandrei** [comment]
Any news?

**Comment by jolheiser** [comment]
No one is working on something for this at the moment (that I know of).  
My guess is this is best suited for custom webhook templates in the future.

**Comment by baxandrei** [comment]
not yet.

**Comment by BaxAndrei** [comment]
Also, as a note, it would be useful to be able to set for each project directly from the webhook or something similar.

**Comment by techknowlogick** [comment]
Closing per @jolheiser's comment above that this would be best suited to the custom webhook template issue.
