### ISSUE TITLE
[Alpine] make test fail in CI

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#9011]
version: 1.10.0

PR: https://github.com/alpinelinux/aports/pull/12104

Problems: 
 - Charset test fail (https://cloud.drone.io/alpinelinux/aports/13316/2/1 L1004)
      `charset_test.go:94:   Error: Not equal`
 - make test-sqlite:  **TestAPIGitTags ** (https://cloud.drone.io/alpinelinux/aports/13329/2/1 L1138)
      `api_repo_git_tags_test.go:54 |   expected: "user2" | actual  : "drone"`

**Comment by 6543** [comment]
the charset test can be deactivated ... but remove make test-sqlite is not what i like to do ..

PS: make-sqlite only fail in [drone](https://cloud.drone.io/alpinelinux/aports/13329/2/1) but the same test PASS in [travis](https://travis-ci.org/alpinelinux/aports/builds/611749824?utm_source=github_status&utm_medium=notification) ?!?

**Comment by 6543** [comment]
is make-sqlite an depricated test @lunny ?

**Comment by lunny** [comment]
@6543 I don't think so. `make test-sqlite` is a part of all the tests.

Look at the fail test, it seems the request's token is unavaible?

```
expected: "user2@example.com"
actual  : "noreply@drone"
```

**Comment by lunny** [comment]
ref: https://drone.gitea.io/go-gitea/gitea/15841/1/14

**Comment by 6543** [comment]
I close this Issue since the PR without the test-sqlite is merged now ...
