### ISSUE TITLE
[Feature Request] Cherry-picking changes

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#9012]
this is part of https://github.com/go-gitea/gitea/issues/5158 summary ...

@pjebs can you describe how it should work with a litle bit more detail ... thx

**Comment by 6543** [comment]
ping

**Comment by pjebs** [comment]
If you download sourcetree by atlassian, you will get a feel for how cherry picking should work.
sourcetree is a git client.

**Comment by lunny** [comment]
I think it's a duplicate of #3880
