### ISSUE TITLE
[Feature Request] for Pull Request, detect conflicts

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#9013]
this is part of #5158 summary ... and also on the list of #8659

**Comment by 6543** [comment]
@guillep2k can you add it to your list #8659

**Comment by 6543** [comment]
should we do this in Mem? 
https://stackoverflow.com/a/6283843

**Comment by lunny** [comment]
I think this has been resolved by #5951

**Comment by 6543** [comment]
@pjebs can you add this as checked to your #5158 ?
