### ISSUE TITLE
when I add or delete a repository to the team then the browser response json data

### ISSUE THREAD

**Issue by wzyxdwll** [go-gitea/gitea#9023]
- Gitea version (or commit ref):
- Git version:1.11.0
- Operating system:linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description
i use the orgnization auth to add a repository to the team of the orgnization,the browser redirect to a page,the page show a json data.then i go back a step,the repository add successfuly.i think the json data path is the redirect url

## Screenshots
i push add button
![image](https://user-images.githubusercontent.com/24530906/68945355-2f454800-07eb-11ea-9964-9fc5913602a7.png)

then redirect to this page
![image](https://user-images.githubusercontent.com/24530906/68945411-4f750700-07eb-11ea-8fed-60b7e161c7be.png)

then i find that delete repository have the same situation

**Comment by jolheiser** [comment]
This is reproducible on try.
