### ISSUE TITLE
Migrating from gitlab results in 500 when viewing Wiki

### ISSUE THREAD

**Issue by the-holger** [go-gitea/gitea#903]
- Gitea version (or commit ref): 6aacf4d
- Git version: 2.7.4
- Operating system: Ubuntu 16.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:
```
[...routers/repo/wiki.go:56 renderWikiPage()] [E] GetBranchCommit: object does not exist [id: refs/heads/master, rel_path: ]
```

## Description

Hi all!
I'm trying to migrate my repositories hosted on my own gitlab-ce instance to a gitea server (due to performance issues and the fact that gitlab is really bloated and appears to have a head of its own).
When creating a repo from scratch I can add and edit wiki pages just fine, however if I migrate a repo from gitlab I get a 500 error, showing the above line in the log.

Could not try on https://try.gitea.io since I didn't receive activation email for account yet.

This might be related to this [gogs issue](https://github.com/gogits/gogs/issues/3792).

**Comment by lunny** [comment]
@tboerger maybe try.gitea.io should disable register confirm email?

**Comment by strk** [comment]
@lunny I'd keep the confirm email, at least we check if it works or not...

**Comment by lunny** [comment]
I think this has been fixed by https://github.com/go-gitea/gitea/pull/544, maybe you could use a newer version to test it.

**Comment by the-holger** [comment]
@lunny Thanks! Tried with 1.0.1:
- Empty wikis are removed, everything works as expected
- Nonempty wikis are migrated (i.e. no "Welcome to Wiki" page), but the "Pages" page is empty

**Comment by lunny** [comment]
So that's another issue. You can change this issue's title or maybe you can fire another.

**Comment by lunny** [comment]
I will close this, please feel free to reopen it.
