### ISSUE TITLE
Save attachments to UNC path

### ISSUE THREAD

**Issue by 12trey** [go-gitea/gitea#9035]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
Is it possible to save attachments to a unc path?
I have our repositories saving correctly to:
**//server/gitrepo/repo**

But this doesn't work for attachments:
**//server/gitrepo/attachments**

When I upload an attachment, a directory is created at the root of the webserver:
**C:/server/gitrepo/attachments**
...

**Comment by lunny** [comment]
Have you changed the attachments storage directory?

**Comment by 12trey** [comment]
> Have you changed the attachments storage directory?

Yes. Sorry I didn’t mention. I have the following in app.ini:

[attachments]
PATH = //server/gitrepo/attachments

It seems the double slashes are not taken into account when resolving the path and instead the folder structure is created on the web server’s drive.

**Comment by lunny** [comment]
A nfs client to implement the storage interrface may resolve the problem.
