### ISSUE TITLE
Discussion/Bug?: Should instances closed to public registeration be able to clone a repository without auth?

### ISSUE THREAD

**Issue by multinerd** [go-gitea/gitea#9037]
I have a self hosted instance of gitea running with public registrations closed.
This means when visiting `https://myurl.com/git/myusername/myrepo.git`, i get redirected to the log in screen. 

In my particular case, this behavior is desired.

While i can't view a repo without signing in, i can very much `git clone` a repo, assuming i know the full URL.

I was expecting git to ask me to authenticate before i can actually clone like [github](https://stackoverflow.com/questions/10054318/how-do-i-provide-a-username-and-password-when-running-git-clone-gitremote-git) does.

**Comment by bagasme** [comment]
Did you mean enforcing clone authentication for private repo?

**Comment by lunny** [comment]
There are two configuration items. DISABLE_REGISTRATION and REQUIRE_SIGNIN_VIEW .

**Comment by bagasme** [comment]
@lunny what OP means git should ask for authentication when cloning private repos on Gitea

**Comment by guillep2k** [comment]
I've just tested 1.10.0 and `REQUIRE_SIGNIN_VIEW = true` on a repository that is private to an organization. A `git clone` through http correctly asked me for credentials (empty username/password didn't work):

```
$ git clone https://git.sif.com.ar/Argentina/avl-pic-reset.git
Cloning into 'avl-pic-reset'...
Username for 'https://git.zzz.com.ar':
Password for 'https://git.zzz.com.ar':
fatal: Authentication failed for 'https://git.zzz.com.ar/Argentina/avl-pic-reset.git/'
$
```

`ssh` failed on me as well, as expected:

```
$ git clone git@git.zzz.com.ar:Argentina/avl-pic-reset.git
Cloning into 'avl-pic-reset'...
The authenticity of host 'git.zzz.com.ar (192.168.0.1)' can't be established.
ECDSA key fingerprint is SHA256:FgZgNujnyxReLga+WnadLChKIkTwPix5zzzzffs9zaz.
ECDSA key fingerprint is MD5:c0:aa:00:fe:64:aa:73:4d:32:aa:99:0d:0f:82:04:a7.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'git.zzz.com.ar,192.168.0.1' (ECDSA) to the list of known hosts.
git@git.zzz.com.ar's password:
Permission denied, please try again.
git@git.zzz.com.ar's password:
Permission denied, please try again.
git@git.zzz.com.ar's password:
Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
$
```

**Comment by multinerd** [comment]
I'm referring specifically to cloning a repository that is `public` to an organization or a user while gitea requires you to log in (closed to public).


My concern is that someone may stumble upon one of our repos url, and while they are not allowed to view it over the web, they can still clone it.

**Comment by jolheiser** [comment]
My local instance was, until recently, requiring sign-in and most of my repos were `public`.
I still had to authenticate when cloning. Are you credentials stored somewhere and being automatically passed for you?

**Comment by multinerd** [comment]
I will have to test that and get back to you.

**Comment by multinerd** [comment]
You're right. It appears my machine was passing credentials. Its weird that GitHub would still ask when i was using the same username and password.

**Comment by guillep2k** [comment]
So this could be closed?
