### ISSUE TITLE
Let's encrypt integration doesn't work anymore (ACMEv1 was discontinued)

### ISSUE THREAD

**Issue by nicolai86** [go-gitea/gitea#9041]
- Gitea version (or commit ref): 1.10.0
- Git version: 2.1.4
- Operating system: debian 
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

```
2019/11/15 19:18:06 ...c/net/http/server.go:3055:logf() [I] http: TLS handshake error from 192.168.178.23:51906: 403 urn:acme:error:unauthorized: Account creation on ACMEv1 is disabled. Please upgrade your ACME client to a version that supports ACMEv2 / RFC 8555. See https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430 for details.
2019/11/15 19:18:06 ...c/net/http/server.go:3055:logf() [I] http: TLS handshake error from 192.168.178.23:51908: acme/autocert: missing certificate
```

## Description

I've setup a plain gitea server and want to enable letsencrypt - but this doesn't work because the ACME client in use is outdated.

**Comment by techknowlogick** [comment]
Thanks for reporting this, seems this was just fixed in golang itself a month ago: https://togithub.com/golang/go/issues/21081 I will work upgrading upstream libraries used in gitea to use acme v2.

**Comment by renothing** [comment]
I suggest use [/go-acme/lego](/go-acme/lego) replace it.
