### ISSUE TITLE
Mistranslation of Top Page in Japanese

### ISSUE THREAD

**Issue by mzch** [go-gitea/gitea#9046]
- Gitea version (or commit ref): All
- Git version: 
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:

## Description
Top page slogan in Japanese is awful mistranslation. Native Japanese speaker never writes such a phrase. Well, for example:
'A painless, self-hosted Git service' must be '手軽で簡単な、自分でホストする Git サービス'.

And why lower part of screen isn't translated? If you can tell me what file to modify, I can do it.

## Screenshots
![FireShot_Capture_014](https://user-images.githubusercontent.com/621178/68998191-75d19a00-08f2-11ea-8481-a29857200e69.png)

**Comment by lunny** [comment]
Please send a PR to fix it.

**Comment by techknowlogick** [comment]
The template is: https://github.com/go-gitea/gitea/blob/master/templates/home.tmpl, however these translations should be modified by the crowndin tool if you want to submit the fixes there: https://crowdin.com/project/gitea

**Comment by mzch** [comment]
I look into them but I couldn't find such phrases on top page...

**Comment by zeripath** [comment]
https://crowdin.com/translate/gitea/68/enus-ja#q=App_desc

**Comment by mzch** [comment]
Thanks @zacheryph , I fixed it.
BTW, please tell me where I should re-translate lower part of top page.

**Comment by zeripath** [comment]
Search for startpage in crowd-in:

https://crowdin.com/translate/gitea/68/enus-ja#q=startpage 

And work through those.

**Comment by mzch** [comment]
Oh sorry, I lost sight of pagination. Thanks @zacheryph
