### ISSUE TITLE
how to change the mirror repository setting Last Synchronized show time as utc+8

### ISSUE THREAD

**Issue by wzyxdwll** [go-gitea/gitea#9050]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
I try to change the app.ini->time.format = RFC3339,but it look like not effect

I don't know how to change the mirror repository setting Last Synchronized show time as utc+8

## Screenshots
![image](https://user-images.githubusercontent.com/24530906/69004958-f675b200-0955-11ea-8141-f3c3eafa7dff.png)

**Comment by guillep2k** [comment]
```
[time]
FORMAT = 2006-01-02 15:04:05
DEFAULT_UI_LOCATION = Asia/Shanghai
```

The `FORMAT` value can be set as shown in the "**Go layout**" column of [this page](https://programming.guide/go/format-parse-string-time-date-example.html). The value `2006-01-02 15:04:05` is not some arbitrary example but the name of the actual format.

The `DEFAULT_UI_LOCATION` must be a time zone present in your system, but it will probably be one of those [listed here](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones) in the "**TZ database name**" column. `GMT+8` will probably be `Asia/Shanghai`.

**Comment by wzyxdwll** [comment]
thank you for your answer, i'll try it later.

**Comment by wzyxdwll** [comment]
I have solved my problem, your answer is perffect,maybe sometimes i should read the source code, thanks again.
