### ISSUE TITLE
Authentication with internal SSH server broken after update to 1.10

### ISSUE THREAD

**Issue by terra-nova** [go-gitea/gitea#9053]
- Gitea version (or commit ref): 1.10.0
- Git version: 2.17.1.windows.2, 2.18.1
- Operating system: Windows 10 x86_64
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description

I was running Gitea 1.8.3 on a Windows system and was able to authenticate both locally (from the Windows box) and externally (from Linux systems) using SSH.

I updated Gitea to 1.10.0 and cannot authenticate using SSH anymore.

I tried removing and re-adding public SSH keys using the Web UI, but it still won't let me in.

Gitea log does not show any error messages related to SSH keys, either.

Log using ssh command line client from Linux:

```
$ ssh -v frobozz.foo.bar
OpenSSH_7.8p1, OpenSSL 1.1.1 FIPS  11 Sep 2018
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: Reading configuration data /etc/ssh/ssh_config.d/05-redhat.conf
debug1: Reading configuration data /etc/crypto-policies/back-ends/openssh.config
debug1: /etc/ssh/ssh_config.d/05-redhat.conf line 8: Applying options for *
debug1: Connecting to frobozz.foo.bar [...] port 22.
debug1: Connection established.
debug1: identity file /home/tnova01/.ssh/id_rsa type 0
debug1: identity file /home/tnova01/.ssh/id_rsa-cert type -1
debug1: identity file /home/tnova01/.ssh/id_dsa type -1
debug1: identity file /home/tnova01/.ssh/id_dsa-cert type -1
debug1: identity file /home/tnova01/.ssh/id_ecdsa type -1
debug1: identity file /home/tnova01/.ssh/id_ecdsa-cert type -1
debug1: identity file /home/tnova01/.ssh/id_ed25519 type -1
debug1: identity file /home/tnova01/.ssh/id_ed25519-cert type -1
debug1: identity file /home/tnova01/.ssh/id_xmss type -1
debug1: identity file /home/tnova01/.ssh/id_xmss-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_7.8
debug1: Remote protocol version 2.0, remote software version Go
debug1: no match: Go
debug1: Authenticating to frobozz.foo.bar:22 as 'tnova01'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256@libssh.org
debug1: kex: host key algorithm: ssh-rsa
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: curve25519-sha256@libssh.org need=64 dh_need=64
debug1: kex: curve25519-sha256@libssh.org need=64 dh_need=64
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ssh-rsa SHA256:...
debug1: Host 'frobozz.foo.bar' is known and matches the RSA host key.
debug1: Found key in /home/tnova01/.ssh/known_hosts:1
debug1: rekey after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey after 134217728 blocks
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey
debug1: Next authentication method: publickey
debug1: Offering public key: RSA SHA256:... /home/tnova01/.ssh/id_rsa
debug1: Authentications that can continue: publickey
debug1: Trying private key: /home/tnova01/.ssh/id_dsa
debug1: Trying private key: /home/tnova01/.ssh/id_ecdsa
debug1: Trying private key: /home/tnova01/.ssh/id_ed25519
debug1: Trying private key: /home/tnova01/.ssh/id_xmss
debug1: No more authentication methods to try.
tnova01@frobozz.foo.bar: Permission denied (publickey).
```

Any hints on what is going on?

**Comment by guillep2k** [comment]
In the admin panel, try "Maintenance Operations" --> "Update the '.ssh/authorized_keys' file with Gitea SSH keys. (Not needed for the built-in SSH server.)".

**Comment by terra-nova** [comment]
> In the admin panel, try "Maintenance Operations" --> "Update the '.ssh/authorized_keys' file with Gitea SSH keys. (Not needed for the built-in SSH server.)".

No luck, unfortunately. That didn't seem to have any effect. Also, it explicitly says "not needed for the built-in SSH server", which is exactly what I am trying to use.

**Comment by zeripath** [comment]
Ok, I'm assuming that your SSH client is actually offering the the correct key to the server. Please check this.

I'm also assuming that the correct key is still in Gitea - again please check 

Looking at the code for the SSH we did do a major change after 1.8 when we moved to gliderlabs - it may be that it doesn't accept the key type you're using but I'm not sure what type you're using.

However looking at the code I see:

https://github.com/go-gitea/gitea/blob/f8bd90ba60b0c362d3e39ddf702cac0e0df2b0ab/modules/ssh/ssh.go#L135

Are you sure that your running user is correct in your settings? That could be it.

**Comment by lunny** [comment]
@guillep2k that option is invalid when using internal SSH server.

**Comment by terra-nova** [comment]
Wow, thank you all for looking into this.

> Ok, I'm assuming that your SSH client is actually offering the the correct key to the server. Please check this.

Yes, the private key is the same as before, it worked with 1.8.3.

> I'm also assuming that the correct key is still in Gitea - again please check

Yes, the public key is the same as before, it worked with 1.8.3.

> Looking at the code for the SSH we did do a major change after 1.8 when we moved to gliderlabs - it may be that it doesn't accept the key type you're using but I'm not sure what type you're using.

The key type is RSA / 4096 bits.

> However looking at the code I see:
> 
> https://github.com/go-gitea/gitea/blob/f8bd90ba60b0c362d3e39ddf702cac0e0df2b0ab/modules/ssh/ssh.go#L135
> 
> Are you sure that your running user is correct in your settings? That could be it.

Ok. I have set the `BUILTIN_SSH_SERVER_USER` option in the `app.ini` file and restarted the service. 

```
...
[server]
...
BUILTIN_SSH_SERVER_USER = git
...
```

And lo and behold.... **it works!**

Thank you so much :)

**Comment by commel** [comment]
I did the same thing, upgrading from 1.9.6 to 1.10 and also added the BUILTIN_SSH_SERVER_USER=git option but the problem remains. Unfortunatly the log file does not show anything related.

**Comment by terra-nova** [comment]
> I did the same thing, upgrading from 1.9.6 to 1.10 from Windows Server and also added the BUILTIN_SSH_SERVER_USER=git option but the problem remains. Unfortunatly the log file does not show anything related. Any more hints on this?

Are you using the same user name (`git`) to access the Gitea repository over ssh? E.g. instead of just running `git clone <server><repo>`, are you running `git clone git@<server><repo>`?

If the answer is yes, then I'd suspect some SSH public/private key mismatch.

**Comment by commel** [comment]
Answering on this to complete the issue. After I've found that pushing and pulling on 1.10.3 worked for me but not for my coworker I checked the git repo config. 

The remote url was `git://host`... after i've changed it to `git://git@host` it worked.

Thank you @terra-nova!
