### ISSUE TITLE
usernames can overlap with api actions (eg: search)

### ISSUE THREAD

**Issue by ederuiter** [go-gitea/gitea#9061]
- Gitea version (or commit ref): 1.11.0+dev-213-g173da1b5a
- Git version: 2.22.0
- Operating system: linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant

## Description

Gitea allows you to create a user with the username "search" after creating this user, the user will not be retrievable via the api as the url for this is /api/v1/users/search which overlaps with the search action.

**Comment by jolheiser** [comment]
This is reproducible on try.  I created a profile for the username in question.

https://try.gitea.io/search

**Comment by 6543** [comment]
I'll take this

**Comment by sapk** [comment]
@6543 I already submitted a PR sorry if you have started working on it.

**Comment by 6543** [comment]
this is no huge deal - i found this issue and remember that i had looked at this part of the code a few days before ... so i know this are two lines of code ... HARD To Find/Fix @spark ;)

**Comment by sapk** [comment]
same reason here :smile:
