### ISSUE TITLE
File viewer not interpreting files correctly

### ISSUE THREAD

**Issue by shatterstone** [go-gitea/gitea#9062]
- Gitea version (or commit ref): 1.7.4 and current
- Git version:
- Operating system: docker
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL) https://try.gitea.io/cyclop5/test/src/branch/master/bm12345.txt
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
Web Viewer/editor is not determining file types correctly. If a text file with the contents of BMxxxxx is attempted to be viewed/edited in the web interface, it shows up as a bmp (broken image). File extension doesn't seem to matter.

![screenshot](https://user-images.githubusercontent.com/24799480/69069724-9716b100-09ec-11ea-9431-76a49cf2bd10.png)

...

**Comment by silverwind** [comment]
0x424d (`BM`) are the magic bytes for Bitmap. I guess it would be better to first look up the mime type by file extension and then fallback to magic bytes checks afterwards.

**Comment by guillep2k** [comment]
> 
> 
> 0x424d (`BM`) are the magic bytes for Bitmap. I guess it would be better to first look up the mime type by file extension and then fallback to magic bytes checks afterwards.

The other fields of the BM header should be valid too.

**Comment by shatterstone** [comment]
Not sure how other systems do it - I have access to a Bitbucket server, and it correctly viewed the file, even without an extension. But mime type is probably a good place to start.

**Comment by silverwind** [comment]
> The other fields of the BM header should be valid too.

Validating full file formats will be tricky. I suggest:

1. Check file extension. If there's a associated mime type, use that.
2. Check if content is valid UTF-8. If so, render as text.
3. Do magic byte checks.

2 and 3 could be swapped maybe. For example, some PDFs may be valid UTF8.
