### ISSUE TITLE
login from signin_inner 404

### ISSUE THREAD

**Issue by ryys1122** [go-gitea/gitea#9068]
- Gitea version (or commit ref): 1.9.5
- Git version: 1.8.3.1
- Operating system: 7.4.1708
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x ] No
  - [ ] Not relevant
- Log gist:

## Description

when i add the template to the home.tmpl page for my git website, the home page works well, but when i login the git from this form, it appears 404. i don't known what happend?

{{template "user/auth/signin_inner" .}}

**Comment by lunny** [comment]
You should give more detail about how did you hack gitea.

**Comment by ryys1122** [comment]
i paste the following code into the /home/git/gitea/custom/templates/home.tmpl to custome my home page, where there is a login form on the center of the home page, but when i login to the site from this login form, the web site appears 404 page. is what i describe clear?
```
        <div class="ui stackable middle very relaxed page grid">
                <div class="sixteen wide center aligned centered column">
                        <div class="hero">
                                <div class="user signin{{if .LinkAccountMode}} icon{{end}}">
                                        <div class="ui container">
                                        {{template "user/auth/signin_inner" .}}
                                        </div>
                                </div>
                        </div>
                </div>
        </div>
```

**Comment by guillep2k** [comment]
@ryys1122 Gitea returns 404 when the logged in user has no permissions and it's not a public page. Maybe something in your template prevented the user from logging in? The error log would be useful.

**Comment by ryys1122** [comment]
i find nothing about the 404 in the log, maybe the log level is not appproprite? what log level should i use? is the template {{template "user/auth/signin_inner" .}} right for login?

**Comment by guillep2k** [comment]
> 
> 
> i find nothing about the 404 in the log, maybe the log level is not appproprite? what log level should i use? is the template {{template "user/auth/signin_inner" .}} right for login?

First, make sure you've got your `home.tmpl` right by using one that is exactly [the same as your Gitea's version](https://github.com/go-gitea/gitea/blob/v1.9.5/templates/home.tmpl) (use the "Raw" link in that page for downloading), but add a small, irrelevant but noticeable change (for example change _only_ where it says `{{AppName}}` for `I CHANGED THIS {{AppName}}`). Run Gitea and observe the results.

Once you get that working, edit the template to your needs but place the sub-template in the same directory and use a relative path. I mean, if home is at `/home/git/gitea/custom/templates/home.tmpl`, place your template at `/home/git/gitea/custom/templates/signin_inner.tmpl`. Reference it from `home.tmpl` using `{{template "signin_inner" .}}`.

If you get that working, you may want to move things around. If any of these steps fails, please let us know where you've got stuck.

**Comment by ryys1122** [comment]
this is the all code in /home/git/gitea/custom/templates/home.tmpl 
```
{{template "base/head" .}}
<div class="home">
	<div class="ui stackable middle very relaxed page grid">
		<div class="sixteen wide center aligned centered column">
			<div class="hero">
				<div class="user signin{{if .LinkAccountMode}} icon{{end}}">
					<div class="ui container">
					{{template "user/auth/signin_inner" .}}
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
{{template "base/footer" .}}
```
then restart gitea, home page show like this pic, i think the appname is correct.
![gitea1](https://user-images.githubusercontent.com/8609374/69302024-2cb37a00-0c53-11ea-9a41-1c7c168abea7.png)
when i enter my account from the login form, 404 appears like this pic
![gitea2](https://user-images.githubusercontent.com/8609374/69302130-9af83c80-0c53-11ea-969f-a213c9dcdb16.png)

**Comment by guillep2k** [comment]
@ryys1122 Please follow the instructions in my previous comment so I can help you.

**Comment by mrsdizzie** [comment]
This is easy to reproduce with the information given.

It doesn't work because its doing a POST to / when run from the home page template.

It shouldn't, because signin_inner contains an action to point it to a specific login URL:

 https://github.com/go-gitea/gitea/blob/dd82e401fdd972457a784819b5afd3358d0aee73/templates/user/auth/signin_inner.tmpl#L12

However, {{.SignInLink}} isn't actually populated when you view the home page so the POST isn't being sent to the right place and returning a 404. Its only set in routers/user/auth.go when rendering the normal sign in page:
 
 https://github.com/go-gitea/gitea/blob/dd82e401fdd972457a784819b5afd3358d0aee73/routers/user/auth.go#L137

Perhaps ctx.Data["SignInLink"] should be set always (why not?) but for now you'd need to make your own copy of templates/user/auth/signin_inner.tmpl and replace that .SignInLink with your login URL which would be /user/login in most cases (or git/user/login if running from a subdir named git etc...) so:

```
 <form class="ui form" action="/user/login" method="post"> 
```

**Comment by ryys1122** [comment]
@mrsdizzie   you mean change
```
<form class="ui form" action="{{.SignUpLink}}" method="post">
```
to
```
<form class="ui form" action="/user/login" method="post">
```
in /home/git/gitea/custom/templates/user/auth/signup_inner.tmpl ?

i do this, but it does't work.

**Comment by mrsdizzie** [comment]
You'd need to be more specific sorry. What doesn't work? You've made that change, restarted gitea, verified that it is now sending the POST to /user/login now and is returning an error from that?

**Comment by ryys1122** [comment]
yes, when login, the page is still 404.
