### ISSUE TITLE
swagger API request

### ISSUE THREAD

**Issue by maicWorkGithub** [go-gitea/gitea#9069]
- Gitea version (or commit ref): 1.9.6
- Git version: 2.11.0
- Operating system: Raspbian GNU/Linux 9.11 (stretch) (raspberry 3b)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

### 1 cannot get `api/swagger`
- access by `http://192.168.1.239:3000/api/swagger`, return url in html is localhost :
``` javascript
window.onload = function() {
  // should not be **localhost**
  var url = "http:\/\/localhost:3000\/swagger.v1.json"
  fetch(url)
  .then(function(response) {
    response.json()
    .then(function(spec) {
      
      var protocol = window.location.protocol.slice(0, -1)
      spec.schemes.sort(function(x,y){ return x == protocol ? -1 : y == protocol ? 1 : 0 })
      
      const ui = SwaggerUIBundle({
        spec: spec,
        dom_id: '#swagger-ui',
        deepLinking: true,
        presets: [
          SwaggerUIBundle.presets.apis,
          SwaggerUIStandalonePreset
        ],
        plugins: [
          SwaggerUIBundle.plugins.DownloadUrl
        ],
        layout: "StandaloneLayout"
      })
      

      window.ui = ui
    })
  })
}

```

**Comment by sapk** [comment]
1)
You need to change the value of ROOT_URL (or DOMAIN) in your config file
https://docs.gitea.io/en-us/config-cheat-sheet/#server-server
2) 
I haven't tested but you can change the path of the json/yaml file loaded in swagger-ui (set the raw path to swagger file in the top bar).

**Comment by maicWorkGithub** [comment]
I am not familiar with the golang, I don't know where to modify it.

**Comment by sapk** [comment]
You don't need to edit code.
1) That Gitea config file
2) In the swagger UI, simply put the URL of the swagger file in the box on the top of the page.

**Comment by maicWorkGithub** [comment]
you mean `public/vendor/assets/swagger-ui/index.html`? 

and how to point it to each repository file like api.yaml?

and then i should rebuild gitea?

**Comment by sapk** [comment]
For example displaying moby/docker yaml swagger-ui of gitea.com
![image](https://user-images.githubusercontent.com/4052400/69214550-89d20180-0b67-11ea-9050-7eff763f4f3f.png)

**Comment by maicWorkGithub** [comment]
No, I mean if I have 10 repositories, tow of them have api schema. like:

- project 1 (repository 1)
  - api.yaml
  - readme.me
- project 2 (repository 2)
  - api.json
  - readme.md

gitea auto parse those two `api` file, and give some page like `/project1/api` or `project2/api`, to show show a swagger page.

**Comment by techknowlogick** [comment]
@maicWorkGithub that's what @sapk is describing, you can take the URL to the API schema and plug it into that page.

**Comment by maicWorkGithub** [comment]
got it, thanks!
