### ISSUE TITLE
Repositories in home page are limited to 10

### ISSUE THREAD

**Issue by zuhairamahdi** [go-gitea/gitea#9070]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

the repositories list in the home page right panel is limited to only 10 repos. is there a way to increase this number?

## Screenshots
![hdashdy2312kdasdlk](https://user-images.githubusercontent.com/6876269/69126444-491baf00-0ab9-11ea-8f57-885c8376ad95.PNG)

**Comment by maicWorkGithub** [comment]
try this:

https://docs.gitea.io/en-us/config-cheat-sheet/ 

Repository => MAX_CREATION_LIMIT

**Comment by maicWorkGithub** [comment]
o sorry, I cannot help with that

**Comment by maicWorkGithub** [comment]
![image](https://user-images.githubusercontent.com/15863224/69130402-6c5f5200-0aeb-11ea-829c-1b2c31d41091.png)

**Comment by zuhairamahdi** [comment]
@maicWorkGithub 
this behavior is not available for me. though the repos are owned by different organizations and not by the same user.

**Comment by jolheiser** [comment]
The default page size should be `15` for the user profile page. The `10` in your screenshot is how many repositories fit in your `all` category.

[sample.ini](https://github.com/go-gitea/gitea/blob/master/custom/conf/app.ini.sample#L169)  
[home.go](https://github.com/go-gitea/gitea/blob/170743c8a0cdf216ee21076aadc5d905dfef0cd6/routers/user/home.go#L130)

**Comment by zuhairamahdi** [comment]
@jolheiser I still don't get it. is there a way to increase the number of displayed repos in `all` category?

**Comment by zuhairamahdi** [comment]
I think I got why I was getting 10 only.
even if I'm a member of an organization (push and pull from all repos) It still will not show in the list unless I was added manually as a Contributor to each repo.

**Comment by lunny** [comment]
You can see the repositories only listed in team settings.

**Comment by zuhairamahdi** [comment]
@lunny as I said, I'm a member of an organization with "Write" permission. but to be able to see the repo listed in the home page I need to be added as (Collaborator) from the repo setting.

using github for example if I'm watching a repo it will be listed in the home page list.
