### ISSUE TITLE
Logo files name

### ISSUE THREAD

**Issue by emilekm** [go-gitea/gitea#9073]
The logo files are named `gitea-{sm,lg}.png`. If you're trying to substitute them with your own files then your logo name will become `gitea[...].png` which would mean that the logo represents Gitea and not the actual brand.

Proposition:
The "gitea" part of the name should be substituted with "logo" (`logo-{sm,lg}.png`).
Also "sm/lg" hints that there might be a version of the file without this suffix (medium) and maybe it would be good to use it instead of "lg".

I can prepare PR when this is accepted.

**Comment by lafriks** [comment]
This would break backward compatibility and it is not user visible anyway so I don't see much point in that keeping in mind about backward compatibility
