### ISSUE TITLE
API: /org/{org}/repos is inconsistent with the rest of the api 

### ISSUE THREAD

**Issue by ederuiter** [go-gitea/gitea#9090]
- Gitea version (or commit ref): 1.11.0+dev-213-g173da1b5a
- Git version: 2.22.0
- Operating system: linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes
  - [ ] No
  - [x] Not relevant

## Description

The api for creating a new repo for an organisation uses the /api/v1/org/{org} prefix instead of the /api/v1/orgs/{org} prefix like the rest of the api. 

I have an (untested) change in my fork: https://github.com/ederuiter/gitea which deprecates the /api/v1/org/{org}/repos call and adds a new /api/v1/orgs/{org}/repos call. If this is something you want I can test it and create a pull request for it.

**Comment by 6543** [comment]
https://developer.github.com/v3/repos/

`Creates a new repository in the specified organization. The authenticated user must be a member of the organization.`
> POST /orgs/:org/repos

**Comment by 6543** [comment]
@ederuiter can you create a PR

**Comment by 6543** [comment]
@ederuiter I'll make a PR with your commits ...

**Comment by 6543** [comment]
#9186 close this @ederuiter if you have some thoughts pleace let me know!

**Comment by ederuiter** [comment]
:+1: @6543 I haven't had time create the PR and test it, so thanks for doing this! Looks good to me
