### ISSUE TITLE
pre-receive, update and post-receive hooks not automatically recreated with executable permissions

### ISSUE THREAD

**Issue by djpbessems** [go-gitea/gitea#9091]
- Gitea version (or commit ref): 1.10.0
- Git version: 
    2.22.0
- Operating system: docker
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist: No relevant log entries

## Description
When the pre-receive, update and post-receive hooks have lost their executable permission (due to reasons not directly relevant to the actual bug), they should be automatically recreated with +x permission (see https://github.com/go-gitea/gitea/blob/dfd8b94923b90edbd3109f5afc3670fb1012e9c8/models/repo.go#L1114-L1150)

However, it turns out that this is not the case, apparently because ioutil.WriteFile does not change permissions on existing files.
Proposed solution by Zeripath: just need to call os.Chmod afterwards

**Comment by lunny** [comment]
So isn't this a bug of `ioutil.WriteFile`?

**Comment by zeripath** [comment]
nope it's subtle but it's clear that it doesn't change the mode of the file if it already exists.
