### ISSUE TITLE
Steam Oauth2 support

### ISSUE THREAD

**Issue by BaxAndrei** [go-gitea/gitea#9094]
Read the title!

**Comment by guillep2k** [comment]
Gitea supports OAuth2, no matter if it's GitHub, Steam, etc. Have you tried configuring it? Did you have any problems doing so?

**Comment by jolheiser** [comment]
Gitea currently supports
```go
	"github.com/markbates/goth/providers/bitbucket"
	"github.com/markbates/goth/providers/discord"
	"github.com/markbates/goth/providers/dropbox"
	"github.com/markbates/goth/providers/facebook"
	"github.com/markbates/goth/providers/gitea"
	"github.com/markbates/goth/providers/github"
	"github.com/markbates/goth/providers/gitlab"
	"github.com/markbates/goth/providers/google"
	"github.com/markbates/goth/providers/openidConnect"
	"github.com/markbates/goth/providers/twitter"
```

It looks like `goth` provides steam support, so it's just a matter of someone making a PR.

**Comment by techknowlogick** [comment]
I believe Steam currently supports OpenID, which works with gitea. that could be used as a temporary workaround.

**Comment by guillep2k** [comment]
Sorry, I confused OAuth2 with OpenID. 😔

**Comment by 6543** [comment]
for anybody looking into it - a hint: #13293

**Comment by 6543** [comment]
Info: @M4RKUS-11111 have a look at it :)

**Comment by 6543** [comment]
Steam OpenID works: `https://steamcommunity.com/openid/id/<steamid>`

**Comment by techknowlogick** [comment]
sadly steam doesn't allow anyone to create oauth applications anymore :(
