### ISSUE TITLE
Should CC licenses also include "human-readable summary"?

### ISSUE THREAD

**Issue by bagasme** [go-gitea/gitea#9105]
## Description

In Gitea, you can use CC licenses for your repo. But I was wondering why `LICENSE` file on Gitea-created repo contains full legal code instead of *human-readable summary*? Why isn't Gitea follow convention of using or adding the CC license summary (link) in place of full legal code, like on many sites which use those licenses?

For example, Gitea bundles full license code of CC-BY-SA [here](https://raw.githubusercontent.com/go-gitea/gitea/master/options/license/CC-BY-SA-4.0), while its summary can be found [here](https://creativecommons.org/licenses/by-sa/4.0/)

**Comment by sapk** [comment]
From what I remember, license are fetched from a repo listing them on GitHub and some licenses need to be with the source code by definition like MIT license
```
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
```
I don't think that it is bad to store the full license but we could definitely improved by detecting licence and showing short insight on what is possible.

**Comment by bagasme** [comment]
@sapk But what about only including the summary, not the full licenses, like many others do?

**Comment by sapk** [comment]
As I don't use much thoses licenses, I may not see the the full problem.
What would be the benefit/goal of not storing the full license and only summary ?
From what, I have seen most people simply link the creative commons website and don't even put a license file. Which is already possible by simply mentioning it in README.

**Comment by bagasme** [comment]
@sapk Perhaps the benefit are just offloading license to external website and marginally reduce repo site.

Fortunately, Gitea provides full license text for CC licenses, just like others (BSD/MIT, GPL/LGPL), so users who wants their repo to be licensed as one of CC licenses don't have to copy-paste **full text** from CC site.

So do you agree to include summary into CC license text here?

**Comment by sapk** [comment]
For me, a LICENSE file, if present, should contain the full license for legal reason and also because it is used by tools to detect compatibility of licensing.
It would be better to have a resume (like GitHub) over the license file display (even for other license).
If someone want to offload to the CC site it could do it basically by adding a link in the README. 
Do you have exemple of known project that store only the summary in there git repository in license file ?

**Comment by bagasme** [comment]
@sapk AFAIK I don't see any project that just link to CC site, or just throwing the summary in `LICENSE` as you noted.

So we have opposites: from user perspective, full legal code doesn't matter (and the summary is sufficient); but from project owner perspective, full legal code is mandatory for legality.

So which side do you prefer? Or just add license summary to  CC `LICENSE`?

**Comment by guillep2k** [comment]
If there's a simple way to get _official_ summaries, and do that _automatically_ like we're doing now with the full versions (e.g. they update when they need to), we could add a checkbox when creating the repo: "what would you like, summary or full legal text?". But if to add summaries it means that Gitea must maintain a list of manually crafted multi-lengual pseudo-legal text, I think it's not worth it and beyond the scope of the project.

**Comment by guillep2k** [comment]
Please notice that summarized text from other sites (e.g. if GitHub had a cool summary for CC:BY-ND) we can not grab it from there unless GitHub license allows us to do that.

**Comment by bagasme** [comment]
@guillep2k I mean the summarized texts are from CC site.

**Comment by techknowlogick** [comment]
The files that we populate LICENSE with are generated from an upstream repo, and if summaries are added there then we could pull them in. Until that happens, those who want just summaries or summaries followed by the full text, then modification via https://docs.gitea.io/en-us/customizing-gitea/ is possible.

I will close this now as this should be discussed in the upstream repo. Upstream is here: https://github.com/spdx/license-list-data

**Comment by Th3Whit3Wolf** [comment]
What kind of template parameters could be used to get the license of the current repo?
