### ISSUE TITLE
How i can use balise code for non interpretation a code in a comment ?

### ISSUE THREAD

**Issue by ZerooCool** [go-gitea/gitea#9117]
How i can use balise code for non interpretation a code in a gitea comment ?

Bad :
RewriteCond %{HTTP_REFERER} !^https?://.*(bit|translate|paypal|google|bing|yahoo|yandex|baidu|facebook|qwant|duck|ixquick|pinterest|twitter).*$ [NC]

Dans mon cas, ETOILE ( ASTERIX ) ne s'affiche pas.

Good, with ETOILE ( ASTERIX ) : 
RewriteCond %{HTTP_REFERER} !^https?://.ETOILE(bit|translate|paypal|google|bing|yahoo|yandex|baidu|facebook|qwant|duck|ixquick|pinterest|twitter).ETOILE$ [NC]

**Comment by guillep2k** [comment]
Do you need help with Gitea or with Apache?

In a comment in Gitea you can use back ticks to escape characters:

![image](https://user-images.githubusercontent.com/18600385/69390073-cce9bd00-0cac-11ea-87e4-daa99ef3782f.png)

Or triple back ticks to enclose a longer text:

![image](https://user-images.githubusercontent.com/18600385/69390093-decb6000-0cac-11ea-805a-42218e8b23a3.png)

**Comment by ZerooCool** [comment]
Resolved !

It would be nice to integrate a text editor.
