### ISSUE TITLE
Go code linting

### ISSUE THREAD

**Issue by silverwind** [go-gitea/gitea#9120]
Would it make sense to lint go code via https://github.com/golangci/golangci-lint or similar tools? Anyone got experience using those?

**Comment by lunny** [comment]
I think we have done that.

**Comment by silverwind** [comment]
Seems so, sorry I missed it.

https://github.com/go-gitea/gitea/blob/5a187f4bcc9cbe5f44da4b623046289c97ede250/.golangci.yml
