### ISSUE TITLE
Add visual editor for issues

### ISSUE THREAD

**Issue by BaxAndrei** [go-gitea/gitea#9132]
It would be very useful if it were a visual editor for adding new issues (or editing) and when commenting on issues like on GitHub

**Comment by lunny** [comment]
I think we already have a preview UI? What do you mean about a visual editor?

**Comment by baxandrei** [comment]
I wanted to suggest something like that. Some users do not know markdown and it is difficult for them, I think a visual editor would be very useful.
![image](https://user-images.githubusercontent.com/12484505/69475573-9492cd80-0dd7-11ea-9ad9-6eff6018c333.png)

**Comment by lunny** [comment]
Maybe an option on user's profile, which mode do you like. Because I think somebody will like write markdown like me. :)

**Comment by guillep2k** [comment]
Yes, we already support that for wikis. I was wondering why _only_ for wikis. 😁

**Comment by lunny** [comment]
So #9197 should close this one.

**Comment by guillep2k** [comment]
This can be closed as per #9197.
