### ISSUE TITLE
Show last edited on issues

### ISSUE THREAD

**Issue by BaxAndrei** [go-gitea/gitea#9133]
It would be useful to look at issues when it was last edited (if it was edited).

**Comment by baxandrei** [comment]
Possible duplicate of https://github.com/go-gitea/gitea/issues/5255

**Comment by lunny** [comment]
Maybe you mean show last edit time/changer that's not the same as #5255 .

**Comment by baxandrei** [comment]
I wanted to make the suggestion in such a way as to suggest that it be done as it is now on github, so I think it's the same thing.

**Comment by guillep2k** [comment]
@baxandrei  I also think it's the same thing, only that #5255 has a more detailed explanation. If you feel that the issue is indeed duplicated, please close this one.

**Comment by baxandrei** [comment]
Ok, sorry.
