### ISSUE TITLE
The possibility of removing an added reaction by clicking on it.

### ISSUE THREAD

**Issue by BaxAndrei** [go-gitea/gitea#9144]
The possibility of removing an added reaction by clicking on it.

![image](https://user-images.githubusercontent.com/12484505/69862038-459adb80-12a2-11ea-9e0b-e4423c951fee.png)

Also, when I click down on the reaction list, to eliminate my reaction, it is removed but it is necessary to reload the page to view the changes. It would be useful to see the changes without having to reload the page.
![image](https://user-images.githubusercontent.com/12484505/69862066-551a2480-12a2-11ea-9eab-2d33e56b9883.png)

**Comment by baxandrei** [comment]
Now I realized that it is going to work, but it is necessary to reload the page. It would be useful if it was automatically updated without having to reload the page.

**Comment by 6543** [comment]
can you change the title to a better issue desc. Thx

**Comment by baxandrei** [comment]
Not yet

**Comment by FWDekker** [comment]
As of v1.11.6, clicking a reaction you've placed will remove it right away without the need to reload the page, but only if it's not the only reaction. Maybe an off-by-one error somewhere? I tried looking through the code a bit but I don't really know Go :/

**Comment by lafriks** [comment]
This should be fixed in v1.12.1
