### ISSUE TITLE
Try.gitea.io seems down

### ISSUE THREAD

**Issue by ShalokShalom** [go-gitea/gitea#9145]
I tried try.gitea.io on both mobile Google Chrome and Kiwi,  both showed me this:

![Screenshot_2019-11-24-12-15-34-204_com android chrome](https://user-images.githubusercontent.com/6344099/69493865-7058ee80-0eb4-11ea-9168-bf6b2e4c121b.png)

**Comment by lunny** [comment]
It's up now.
