### ISSUE TITLE
There can be multiple forks on a same account

### ISSUE THREAD

**Issue by thehowl** [go-gitea/gitea#915]
- Gitea version (or commit ref): 1.0.0+258-g076f940f 
- Git version: (try.gitea.io)
- Operating system: (try.gitea.io)
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant

## Description

An user can have more than one forked repository (of the same base repo) per account. This is an issue because it makes impossible making PRs from a second forked repository.

e.g. https://try.gitea.io/Howl/ccc - If I try to do a PR, the link will be https://try.gitea.io/Howl/aaa/compare/master...Howl:master , which will compare aaa (base repo) with bbb (first forked repo), as the link has no way to recognise that it should use ccc instead of bbb.

**Comment by tboerger** [comment]
Yeah it doesn't make sense to allow multiple forks of the same repo

**Comment by bkcsoft** [comment]
Not sure if the issue here is that there can be multiple forks, or that you can't specify which fork to compare 😄

**Comment by bkcsoft** [comment]
Because if we disallow multiple forks in an upcoming release, that would be a breaking change. But if we fixed the "compare fork"-issue we would have better fork-support than github :trollface:
