### ISSUE TITLE
Handle Issue wich the user lost acces corect

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#9155]
If you have a user wich had created an issue to a reop wich is later set to private ... the user still see the issue in his activety and issue-dashboard but if he klick at it he get will get a 404

**Comment by 6543** [comment]
come up in #8741 while debuging a error

**Comment by lunny** [comment]
I think it maybe already the correct implementation.

**Comment by 6543** [comment]
@lunny ?

**Comment by lunny** [comment]
I mean it seems this is the right behavior of gitea. What's wrong with it?

> If you have a user wich had created an issue to a reop wich is later set to private ... the user still see the issue in his activety and issue-dashboard but if he klick at it he get will get a 404

**Comment by 6543** [comment]
I would hide issues a user had no acces anymore ... but It looks like this need a lot of code change :( and recources

**Comment by 6543** [comment]
looks like nobody care of this edge case ... so **I**'ll close this :D
