### ISSUE TITLE
Mixed-content issues

### ISSUE THREAD

**Issue by minecrafter** [go-gitea/gitea#916]
- Gitea version (or commit ref): 1.0.1
- Git version: 2.7.4
- Operating system: Ubuntu 16.04 LTS
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL): https://try.gitea.io/gitea/gitea
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

Gitea can still serve mixed-content pages, even with SSL. This is most pronounced with images being loaded over an insecure connection.

This can be solved by integrating a solution similar to [camo](https://github.com/atmos/camo) (GitHub uses this) into Gitea.

In addition to security, it also provides a privacy benefit for users if the install is public.

**Comment by thehowl** [comment]
If we're embedding a camo server into gitea, I'd like to say go-camo is a thing and we could get most stuff from that: https://github.com/cactus/go-camo

**Comment by tboerger** [comment]
go-camo makes sense, we don't want to reinvent the wheel

**Comment by lunny** [comment]
Anyone would like to send a PR to fix this?

**Comment by lunny** [comment]
Move this to v1.2 since no PR to send.

**Comment by 6543** [comment]
is there any progress?

**Comment by lunny** [comment]
Nobody are working on this.

**Comment by 6543** [comment]
can we do this onto 1.10.0?
i think it only afects the markdown parts of gitea?
which files are these so i'll have a look at it

**Comment by 6543** [comment]
# to discust:
should we replace the src url of img nodes after blackfriday process the markdown

or 

replace ![](url) with ![](camourl/url) ?

**Comment by 6543** [comment]
we ned in each case two config values
* CAMO_URL
* CAMO_KEY

for example:
nginx reverse proxy gitea.com/camo -> http://127.0.0.1:3456
  * CAMO_URL = https://gitea.com/camo
  * CAMO_KEY = 123secret

camo itself:
 `./go-camo -k jo --listen=127.0.0.1:3456 --stats --metrics &`

**Comment by tboerger** [comment]
I think the goal had been to embed it instead of relying on another service

**Comment by 6543** [comment]
We can use the routines of go-camo it shouldnt be that hard

**Comment by 6543** [comment]
> I think the goal had been to embed it instead of relying on another service

and then https://github.com/go-gitea/gitea/issues/916#issuecomment-515718697 still remains

**Comment by lhinderberger** [comment]
There has been a parallel discussion on this issue at Codeberg.org: https://codeberg.org/Codeberg/Community/issues/196
