### ISSUE TITLE
All SQL statements are logged with gitea v1.10 by default

### ISSUE THREAD

**Issue by lhooge** [go-gitea/gitea#9167]
- Gitea version (or commit ref): 1.10.0
- Git version: git version 2.11.0
- Operating system: Linux petrowitsch 4.9.0-8-amd64 #1 SMP Debian 4.9.144-3.1 (2019-02-19) x86_64 GNU/Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
I've update gitea to version 1.10.0 and it seems that all statements are being logged because gitea sets showExecTime to true (https://github.com/go-gitea/gitea/blob/master/models/models.go#L154)
In my opinion it should be made configurable with a parameter to log SQL statements for debugging purposes.

**Comment by lunny** [comment]
It depends on https://github.com/go-gitea/gitea/blob/master/models/models.go#L159

**Comment by lhooge** [comment]
Thank you. Sorry, I didn't see that property.
