### ISSUE TITLE
timezone setting not working

### ISSUE THREAD

**Issue by hisune** [go-gitea/gitea#9172]
- Gitea version (or commit ref):  1.9.4
- Git version: 2.19.2
- Operating system: centos6.9
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description
My `app.ini`
```ini
[time]
FORMAT = 2006-01-02 15:04:05
DEFAULT_UI_LOCATION = Asia/Shanghai
```

![image](https://user-images.githubusercontent.com/7941669/69687468-fc118b80-10fd-11ea-8962-092443cbe547.png)

but current `Asia/Shanghai` time is `2019/11/27 上午10:09:46`

**Comment by guillep2k** [comment]
This kind of time difference (10:09 vs. 11:26) suggests the _server time_ not properly set. If the time zone were off, you should see an exact difference in hours (e.g. 10:09 vs. 11:09).

**Comment by hisune** [comment]
after update gitea version to v1.10.0, the problem has been solved
