### ISSUE TITLE
register new user , I always get this error  "Password does not pass complexity requirements."

### ISSUE THREAD

**Issue by 756445638** [go-gitea/gitea#9176]
I have install the newest version .
And I always get this error .

**Comment by guillep2k** [comment]
Try with a password with at least:

* One lower case letter
* One upper case letter
* One non-letter ASCII symbol (e.g. & % $ # @ , ! etc.)
* 6 characters long or more.

**Comment by 756445638** [comment]
thanks , i have pass the password complexity requirements.
