### ISSUE TITLE
Add colors for preview changes

### ISSUE THREAD

**Issue by BaxAndrei** [go-gitea/gitea#9179]
Now: ![image](https://user-images.githubusercontent.com/12484505/69716832-89aba600-1113-11ea-8d38-3a8ac5b3b8c7.png)

Suggested: 
![image](https://user-images.githubusercontent.com/12484505/69716868-a3e58400-1113-11ea-9ddb-0f8e04017248.png)

**Comment by zeripath** [comment]
I'm fairly certain that this is done already.
