### ISSUE TITLE
Webhook doesn't send on repository delete event

### ISSUE THREAD

**Issue by matrozov** [go-gitea/gitea#9180]
- Gitea version (or commit ref): 1.11.0+dev-331-g055f6d229
- Git version: not needed
- Operating system: Docker container from gitea/gitea
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

No notifications are sent via webhook upon the deletion of the repository. The notification is not a joke either when specifying a webhook in the repository settings, or when specifying a global webhook.

**Comment by lunny** [comment]
Currently repository webhooks will not be sent but I think Orgnization webhooks should be sent.

**Comment by matrozov** [comment]
> Currently repository webhooks will not be sent but I think Orgnization webhooks should be sent.
In the configuration of the global webhook it is written like this: creating and deleting a repository. That's why I started this bug, because when I deleted the repository I did not see the global webhook working.

**Comment by lunny** [comment]
@matrozov That's not global webhook. It's a default webhook.

**Comment by jsanchezba** [comment]
This is happening to me but with the push event.

**Comment by jamesorlakin** [comment]
This has been fixed in master (due to become 1.13), and I've opened a backport to fix this for 1.12.

**Comment by zeripath** [comment]
Fixed by #13008
