### ISSUE TITLE
Create pull-request event send webhook twice

### ISSUE THREAD

**Issue by matrozov** [go-gitea/gitea#9181]
- Gitea version (or commit ref): 1.11.0+dev-333-g7b7d382b8
- Git version: not needed
- Operating system: not needed
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (https://try.gitea.io/o.matrozov/test/settings/hooks/280)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

When creating a pull request, a double webhook is sent.

## Screenshots
![1](https://user-images.githubusercontent.com/4449593/69718437-6b4ba780-111f-11ea-8115-7466a60a2544.PNG)
![2](https://user-images.githubusercontent.com/4449593/69718441-6d156b00-111f-11ea-85de-e3540546179c.PNG)

**Comment by jolheiser** [comment]
Fixed in #9375
