### ISSUE TITLE
Webhook doesn't send on branch delete event after merge in pull request

### ISSUE THREAD

**Issue by matrozov** [go-gitea/gitea#9184]
- Gitea version (or commit ref): 1.11.0+dev-333-g7b7d382b8
- Git version: not needed
- Operating system: not needed
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

After a successful merge in pull-request, the interface suggests deleting the branch from which the pull was made. With this deletion, the webhook does not receive a notification about the removal of a branch, although deleting branches from outside causes such a message. In the images below you can see that the brunch was deleted after the pull request, but in webhook the last message is closing the pull request itself.

## Screenshots

![1](https://user-images.githubusercontent.com/4449593/69724431-f2534c80-112c-11ea-8d48-b51c2c27a152.png)
![2](https://user-images.githubusercontent.com/4449593/69724437-f41d1000-112c-11ea-930a-cbf6205afaac.png)

**Comment by lunny** [comment]
duplicated with #6181
