### ISSUE TITLE
Link account signing form has no password field

### ISSUE THREAD

**Issue by brandonkal** [go-gitea/gitea#9185]
As the title says, no password field is available when signing in via OpenID connect to link to an existing account.

**Comment by brandonkal** [comment]
I believe this bug was introduced in 1.10.0

Editing the HTML as a user to add a password input, I was able to submit the form and sign in. So the issue is in the UI only.

**Comment by jolheiser** [comment]
I think this was fixed by #9150 for `v1.10.1`
