### ISSUE TITLE
Allow use external CDN service to provide public static files.

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#9188]
Many famous static files have been served by https://cdnjs.com/ for free. For those files a private CDN service is unnecessary. Below list all files could be served.

- [ ] vue.min.js
- [ ] jquery.min.js
- [ ] semantic.min.js

**Comment by silverwind** [comment]
I'd prefer to bundle them instead. Less HTTP requests is always faster and external sources may be a privacy concern to some. I certainly prefer to have my instance work standalone, even when a external service is unreachable or down.

**Comment by lunny** [comment]
@silverwind This will be a configurable feature and default is local assset files. 
We have at least two scenios, one for private instance, one fore public instance.
For a public instance, reference a CDN static maybe faster then himself service.

And I think we should only bundle ourself js/css but keep third-party standalone js/css for more flexsible maintainances.

**Comment by silverwind** [comment]
The speed difference would only be visible on the very first page load. After that, `serviceWorker` will cache all requests and serve them from local cache instead of CDN.

So I don't think there's really any benefit in doing external sources except that they prevent future bundling attempts.
