### ISSUE TITLE
Mattermost Issue notification formatting broken

### ISSUE THREAD

**Issue by cornelk** [go-gitea/gitea#9195]
- Gitea version (or commit ref): 1.10.0
- Git version:
- Operating system:
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

I integrated Gitea using a Webhook to Mattermost. When I create an issue in Gitea the following text gets posted on Mattermost:

```
[org/repo] Issue submitted by cornel

<https://host/org/test/pulls/1|#1 to do this>
```

The link can't be clicked as it's in text form.

Gitlab posts created issues as:

```
[[org/repo](https://host/org/repo)] Issue opened by Cornel (cornel)
```

which creates a link that can be clicked in Mattermost.

**Comment by lunny** [comment]
@cornelk Did you create a slack type webhook?

**Comment by cornelk** [comment]
@lunny yes, it's a Slack typed Webhook. 

Looking at the code of https://github.com/go-gitea/gitea/blob/a966a0298ea1a545c383541ca4e72c61de1ed59e/modules/webhook/slack.go I see that `new commit` posts get the repoLink/branchLink but `getSlackIssuesPayload()` does not make use of `p.Repo.HTMLURL` which will not allow any posted message in there to be clicked. I can fix it if wanted.

**Comment by lunny** [comment]
@cornelk could you send a PR?

**Comment by cornelk** [comment]
The issue got reopened, so I post the remaining problem with the formatting here:

![69858467-06ce4b00-12cd-11ea-9c6d-5b075912b9f5](https://user-images.githubusercontent.com/3045857/70208630-10423200-1769-11ea-9c6d-b83368187b40.png)

comment formatting is still broken
