### ISSUE TITLE
Submitting review on pull request gives Error 500

### ISSUE THREAD

**Issue by davidsvantesson** [go-gitea/gitea#9207]
- Gitea version (or commit ref): 1.10.0
- Git version: 2.17.1
- Operating system: Ubuntu
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:
```
2019/11/29 08:56:59 .../xorm/session_raw.go:194:exec() [I] [SQL] UPDATE `review` SET `type` = ?, `reviewer_id` = ?, `issue_id` = ?, `content` = ?, `updated_unix` = ? WHERE `id`=? []interface {}{3, 60, 84, "<text of ~350 characters>", 1575017819, 82} - took: 1.825014ms
2019/11/29 08:56:59 .../repo/pull_review.go:173:SubmitReview() [E] UpdateReview: Error 1406: Data too long for column 'content' at row 1
2019/11/29 08:56:59 ...s/context/context.go:138:HTML() [D] Template: status/500  
```  

## Description
When submitting a review on a pull request I get an Error 500 page. It seem the text you enter when approving or rejecting a PR is only intended to be rather short, and therefore the database column _review.content_ is limited to 255 characters. However the user interface doesn't restrict the input to this limit.

**Comment by lunny** [comment]
Just change it to `TEXT` and add a migration.
