### ISSUE TITLE
fatal error with code 500 while showing commits

### ISSUE THREAD

**Issue by iwzoo** [go-gitea/gitea#9217]
- Gitea version (or commit ref):
1.11.0+dev-333-g7b7d382b8 (docker)

- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:
- Gitea log
2019/12/01 16:32:45 .../xorm/session_raw.go:76:queryRows() [I] [SQL] SELECT max( id ) as id FROM `commit_status` WHERE (repo_id = ?) AND (sha = ?) GROUP BY context_hash ORDER BY max( id ) desc LIMIT 10 []interface {}{3, "3a9cac874c1757b682fb8651f75e30783b06a1c7"} - took: 133.574µs
2019/12/01 16:32:51 ...les/context/panic.go:35:1() [E] PANIC:: runtime error: index out of range [-1]
	/usr/local/go/src/runtime/panic.go:75 (0x435452)
	/go/src/code.gitea.io/gitea/services/gitdiff/gitdiff.go:357 (0x11e9c63)
	/go/src/code.gitea.io/gitea/services/gitdiff/gitdiff.go:865 (0x11ed8e6)
	/go/src/code.gitea.io/gitea/services/gitdiff/gitdiff.go:809 (0x11ef09c)
	/go/src/code.gitea.io/gitea/services/gitdiff/gitdiff.go:949 (0x11ef031)
	/go/src/code.gitea.io/gitea/routers/repo/commit.go:229 (0x12d3d0d)
	/usr/local/go/src/reflect/value.go:460 (0x497ae5)
	/usr/local/go/src/reflect/value.go:321 (0x4972a3)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:177 (0x9aef09)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:137 (0x9ae8b9)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:121 (0x9dea58)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:112 (0x10d1d9a)
	/go/src/code.gitea.io/gitea/modules/context/repo.go:751 (0x10d1d83)
	/usr/local/go/src/reflect/value.go:460 (0x497ae5)
	/usr/local/go/src/reflect/value.go:321 (0x4972a3)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:177 (0x9aef09)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:137 (0x9ae8b9)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:121 (0x9dea58)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:112 (0x10d05dc)
	/go/src/code.gitea.io/gitea/modules/context/repo.go:533 (0x10d05c5)
	/usr/local/go/src/reflect/value.go:460 (0x497ae5)
	/usr/local/go/src/reflect/value.go:321 (0x4972a3)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:177 (0x9aef09)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:137 (0x9ae8b9)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:121 (0x9dea58)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:112 (0x10cdf61)
	/go/src/code.gitea.io/gitea/modules/context/panic.go:39 (0x10cdf4d)
	/usr/local/go/src/reflect/value.go:460 (0x497ae5)
	/usr/local/go/src/reflect/value.go:321 (0x4972a3)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:177 (0x9aef09)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:137 (0x9ae8b9)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:121 (0x9dea58)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:112 (0xaac1f5)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/session/session.go:192 (0xaac1e0)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:79 (0x9de900)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:157 (0x9aec19)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:135 (0x9ae9a8)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:121 (0x9dea58)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:112 (0x9f00f9)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/recovery.go:161 (0x9f00e7)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/logger.go:40 (0x9e25d3)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:157 (0x9aec19)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:135 (0x9ae9a8)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:121 (0x9dea58)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:112 (0x9ef430)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/logger.go:52 (0x9ef41b)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/logger.go:40 (0x9e25d3)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:157 (0x9aec19)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:135 (0x9ae9a8)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:121 (0x9dea58)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/router.go:187 (0x9f1316)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/router.go:303 (0x9eacf5)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/macaron.go:220 (0x9e396a)
	/go/src/code.gitea.io/gitea/vendor/github.com/gorilla/context/context.go:141 (0xc4d10d)
	/usr/local/go/src/net/http/server.go:2007 (0x758913)
	/usr/local/go/src/net/http/server.go:2802 (0x75bd63)
	/usr/local/go/src/net/http/server.go:1890 (0x757704)
	/usr/local/go/src/runtime/asm_amd64.s:1357 (0x466ec0)

## Description
I've just migrated some repos from Gitlab to Gitea. When I'm trying to view the commits for a repo with many changes, it fails and shows http code 500 in the page. 
...

### Gitlab shows the commits without any problem
<img width="975" alt="Screen Shot 2019-12-01 at 4 43 20 PM" src="https://user-images.githubusercontent.com/5208081/69911661-d536ba80-1459-11ea-9ec0-8d9fdb3455c4.png">

### Gitea fails 
<img width="1474" alt="Screen Shot 2019-12-01 at 4 43 50 PM" src="https://user-images.githubusercontent.com/5208081/69911663-d536ba80-1459-11ea-8d69-ee4a7381d3ce.png">

**Comment by lafriks** [comment]
I think this was recently fixed @lunny

**Comment by iwzoo** [comment]
> I think this was recently fixed @lunny

Thanks. 

The latest image fixes the problem,.
