### ISSUE TITLE
How to change web address?

### ISSUE THREAD

**Issue by ZeroZs** [go-gitea/gitea#922]
I have not found gitea, but I need to connect to the web interface for initial configuration.
How do I change localhost to 192.168.1.7?

![untitled](https://cloud.githubusercontent.com/assets/25699030/22878968/d84ae7b0-f1ec-11e6-9207-798e0c26f187.png)

If the options, except for changing the code itself is no more, then I can recompile. Just tell me where it is changed.

**Comment by tboerger** [comment]
It's not localhost, `0.0.0.0` is connected to all available interfaces. If you want to limit the connection to a specific ip address you can use the option `HTTP_ADDR` and to bind it to another port you can use `HTTP_PORT`. You can find the options at https://github.com/go-gitea/gitea/blob/master/conf/app.ini#L91-L92

**Comment by ZeroZs** [comment]
I have already changed these settings, and then restarted gitea and still appears as 0.0.0.0:3000

**Comment by lunny** [comment]
Did you changed custom/conf/app.ini and HTTP_ADDR?
