### ISSUE TITLE
How to use init.templateDir with gitea?

### ISSUE THREAD

**Issue by gabyx** [go-gitea/gitea#9221]
It seems that gitea overwrites githooks with its own default hooks when the repository is created over the web interface. This means I cannot have a global `git config --global init.templateDir "path/to/hooks`.

Is there a proper way of doing this?

- Gitea version (master):
- Git version: 2.24

**Comment by lunny** [comment]
Gitea will overwrite `post-receive`, `pre-receive`and `update` files and create `post-receive.d`, `pre-receive.d`, `update.d` directories.

**Comment by gabyx** [comment]
Thx. It turned out, that I installed under `root` instead of the user `git`.
