### ISSUE TITLE
Clear issue branch/tag during issue creation

### ISSUE THREAD

**Issue by fwdekker** [go-gitea/gitea#9223]
- Gitea version (or commit ref): 1.10.0
- Git version: 2.23.0
- Operating system: FreeBSD
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist: N/A

## Description
While in the process of creating an issue, it's possible to select a branch/tag. However, it is not possible to remove this branch/tag before actually creating the issue. I think there should be a "clear" button in case I change my mind before submitting the issue. Without this button I would have to refresh the page and re-enter all fields, which is bothersome.

## Screenshots
![The branch/tag selector without the option to remove the selection](https://user-images.githubusercontent.com/13442533/69948205-7f145680-14ef-11ea-9ac3-4f25c1acad25.png)

**Comment by guillep2k** [comment]
This will be fixed by #9080.

**Comment by lunny** [comment]
duplicated with #3620
