### ISSUE TITLE
how to download archive of private repository?

### ISSUE THREAD

**Issue by iwzoo** [go-gitea/gitea#9224]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
I'd like to download the archives of repositories with wget or curl.  I can do these with command 
wget  "https://mygit.com/user/myrepo/repository/master/archive.zip?private_token={token}"
for gitlab, what's the equivalent way to do so for gitea??

...

**Comment by axifive** [comment]
https://try.gitea.io/api/swagger#/repository/repoGetArchive

Authentication options:: https://docs.gitea.io/en-us/api-usage/

**Comment by iwzoo** [comment]
> https://try.gitea.io/api/swagger#/repository/repoGetArchive
> 
> Authentication options:: https://docs.gitea.io/en-us/api-usage/

thank you. 

I tried 

`curl -X GET "https://mygit.com/api/v1/repos/{username}/{reponame}/archive/master.zip"  -H "Authorization: f3b623ca2f2becfe45d7cf0bc7d3d95577e12e8f" -o /tmp/test.zip`

and got 

> {"message":"Only signed in user is allowed to call APIs."}

**Comment by axifive** [comment]
> curl -X GET "https://mygit.com/api/v1/repos/{username}/{reponame}/archive/master.zip" -H "Authorization: f3b623ca2f2becfe45d7cf0bc7d3d95577e12e8f" -o /tmp/test.zip

"Authorization: token f3b623ca2f2becfe45d7cf0bc7d3d95577e12e8f"

**Comment by iwzoo** [comment]
> > curl -X GET "[https://mygit.com/api/v1/repos/{username}/{reponame}/archive/master.zip](https://mygit.com/api/v1/repos/%7Busername%7D/%7Breponame%7D/archive/master.zip)" -H "Authorization: f3b623ca2f2becfe45d7cf0bc7d3d95577e12e8f" -o /tmp/test.zip
> 
> Correct alternative: "Authorization: token f3b623ca2f2becfe45d7cf0bc7d3d95577e12e8f"

this also works.   
:)
