### ISSUE TITLE
Global `core.hooksPath` does not work

### ISSUE THREAD

**Issue by gabyx** [go-gitea/gitea#9225]
Does `core.hooksPath` work with gitea, it seems that after `git init`  writes its own hooks into `data/git/repositories/TestRepo/hooks` .... 
and also a set `git config --global core.hooksPath <pathToMyHooks>` does not help.
Only when the hooks reside in `data/git/repositories/TestRepo/hooks` then the hooks are triggered... ?

- Gitea version (or commit ref): 1.11.0+dev-134-g4ee986e4c
- Git version: 2.22

**Comment by 6543** [comment]
@gabyx do you mean gitea ignore global git config of the user it run as?

**Comment by gabyx** [comment]
That could be but, so far, one should not change the behavior, 
When gitea creates a new repo it should run 
- `git init --bare`
   - git sets up a repository and copies files from `init.templateDir`.
     Assume there are `${init.templateDir}/hooks` which get installed
- gitea somehow overwrites the hooks in `hooks` (it does not look at `core.hooksPath`).

This overwritting behavior is **problematic** in any case if it is in the local hooks folder or in the `core.hooksPath` folder if set. It clear that gitea **needs** to install the hooks somewhere, and thats not so trivial, since the admin (as me) could have setup a global hooks dispatcher (see https://github.com/rycus86/githooks)

A **better strategy** would be to call a customizable **setup script** which is run after gitea has created the bare repo. The default implementation is exactly as today, but so that we can adapt this script. A `git config --global core.hooksPath` should not be supported because is the same for a repositories, gitea wants the flexibiliy to edit/save hooks from the web-interface fo each repository and needs to place the best in the repository own `hooks/update.d` (etc..) folder...

This means the `setup-script.sh` is called like
```shell
bash setup-repo.sh "repoPath" "gitea-hooks-dir-to-be-placed"
```
In this way we can replace the initial hooks of gitea, replace them with the global hooks dispatcher and incorporate the gitea hooks.

**Comment by 6543** [comment]
ping

**Comment by zeripath** [comment]
I've still not had a chance to actually properly investigate this

**Comment by gabyx** [comment]
I think it was only a user problem. But the enhancement would be beneficial.
