### ISSUE TITLE
SMTP authentication problem

### ISSUE THREAD

**Issue by serajushsalekin** [go-gitea/gitea#9226]
i tried SMTP authentication following this url: https://docs.gitea.io/en-us/authentication/ . but no luck, it gives me username and password incorrect error.

**Comment by techknowlogick** [comment]
@serajushsalekin a few questions:
* which email provider are you using to try to authenticate with?
* Which version of Gitea are you using?
* Are you using docker version of Gitea?
* Which OS are you using?
* Which DB are you using?

**Comment by serajushsalekin** [comment]
@techknowlogick  I'm using docker version of gitea

- i tried it with google and yandex

- Gitea Version: 1.11.0

- Docker version 19.03.3

- Ubuntu 19.10

- Postgres 9.6

**Comment by serajushsalekin** [comment]
@techknowlogick have you got the chance to look it over?
