### ISSUE TITLE
Dashboard repos doesn't show source results but show counter

### ISSUE THREAD

**Issue by axifive** [go-gitea/gitea#9234]
- Gitea version (or commit ref):
- Git version: 1.11.0+dev-359-g23ef9ff51
- Operating system: 
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
Dashboard repos sourse tab shows counter but doesn't show results.

## Screenshots
![Screen Shot 2019-12-03 at 04 15 26](https://user-images.githubusercontent.com/844963/70008807-aa488580-1583-11ea-9407-dd5f3f0bff6b.png)

![Screen Shot 2019-12-03 at 04 15 49](https://user-images.githubusercontent.com/844963/70008968-b03e6680-1583-11ea-870e-60a3c8305b73.png)

**Comment by lunny** [comment]
This should be a frontend problem.

**Comment by jueti** [comment]
fix with a new custom template from the origin

worked on Windows 10

### steps

1. download the original [template](https://github.com/go-gitea/gitea/blob/master/templates/user/dashboard/dashboard.tmpl) to `%GITEA_WORK_DIR%\custom\templates\user\dashboard\`
![image](https://user-images.githubusercontent.com/24526369/70413284-fb7bdc00-1a91-11ea-8e7b-f100c5375096.png)

2. delete the key code at line 86
  change 
```html
<li v-for="repo in repos" :class="{'private': repo.private}" v-show="showRepo(repo, reposFilter)">
```
  as
```html
<li v-for="repo in repos" :class="{'private': repo.private}">
```
![image](https://user-images.githubusercontent.com/24526369/70413687-ea7f9a80-1a92-11ea-80b0-d07b3f774773.png)


3. restart the gitea service (Administrator access)
```cmd
sc stop gitea || sc start gitea
```

**Comment by axifive** [comment]
@jueti, We can't just remove `showRepo()` filter, it's an important part of code. I create Pull Request with fix
