### ISSUE TITLE
Can or will support watch online video?

### ISSUE THREAD

**Issue by FalconWu2017** [go-gitea/gitea#9239]
Watch the upload video such as mp4 in issue or PR.  
Do not need to download videl file as a file.

**Comment by silverwind** [comment]
Something like https://github.com/sampotts/plyr could be added and lazy-loaded on pages containing videos, probably identified via file extension.

**Comment by delvh** [comment]
I think this should be possible since 1.19:
`<video>` tags will be kept now, so you can upload the video as an attachment and link to it.
