### ISSUE TITLE
Suggestion: make it possible to review any bunch of changes without PR

### ISSUE THREAD

**Issue by Md-Cake** [go-gitea/gitea#924]
Hello everyone,

I'm investigating if we at my current company can use your gitea for storing repositories. It's really nice software and have a lot of feauters but I want to ask you for another one. Any workaround that can be used without performing any changes will be appreciated!

tldr; My problem is that we want to have possibility to review any bunch of changes (actually we want to review difference between two branches - see below for further explanation).

Currently we are using modified Gitflow Workflow (you can find some explanation here https://www.atlassian.com/git/tutorials/comparing-workflows) with difference that we have no develop branch. Instead at some moment of time we create new branch which is called "release_{date & time}" and merge some (not all and this is important) ready to merge issues into it. So for developer it looks like so: he has master branch -> he create his own branch from it -> he make some code and commit -> he has some review of his code from other member of developers team (prob code is not okay and than ticket goes back to the first developer) -> than he has some testing (prob it is not okay and ticket goes back to development stage) -> than we create release branch and merge ticket branch there -> than release branch is merge into master after deployment to production is completed.

So I'm trying to make code review using your tool and I can't find any corresponding option for this. The only way to comment some code I can find is to create PR but I don't want to do this since in my company we are not merging issues in master branch and I can't find any way to solve this problem by my own.

Thank you in advance!

**Comment by lunny** [comment]
I think you requirement will be resolved by #733. But that PR is not completed and maybe merged at v1.2 .

**Comment by bkcsoft** [comment]
> since in my company we are not merging issues in master branch

Can you not make a release-branch to make PR to?

> make code review using your tool

We don't have any code review options yet. We are currently investigating git-appraise 🙂

**Comment by Md-Cake** [comment]
@lunny thanks. This PR looks promising!

@bkcsoft I thought that there are some code review options in PR view but I didn't check it since we're not using pull requests now. Actually we compare each branch with master but than every issue branch can be merged into different release branches. This branching model allows us to deliver features as fast as they get ready. So theoretically we can create pull request to master for each branch and make some code review/testing in prs view but this scheme seems not so obvious and good for me.

Anyway thanks for your replies. I will wait for gut-appraise integration!
