### ISSUE TITLE
Not contabilizing other users commits on push

### ISSUE THREAD

**Issue by luisbrandao** [go-gitea/gitea#9250]
- Gitea version (or commit ref): 1.10.0-rc2
- Git version: 2.20.1
- Operating system: Centos 6
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite

## Description

I am using gitea as a "backup repository"
I have configurated both my user and a jenkins use.
When i send commits to gitea server, jenkins commits wont get contabilizated on the contributions tab. (like "jenkins" never made a commit.)

Jenkins email on gitea and email on git commit are configurated acoordly.

**Comment by noerw** [comment]
What does 'contabilize' mean? o.O

**Comment by guillep2k** [comment]
@noerw I think it means here or in the repo's activity tab:

![image](https://user-images.githubusercontent.com/18600385/70376589-0b0bf100-18e9-11ea-846c-4881844993a4.png)

**Comment by luisbrandao** [comment]
@guillep2k thats it
