### ISSUE TITLE
Latest docker image is broken

### ISSUE THREAD

**Issue by a20eac1d** [go-gitea/gitea#9257]
- Gitea version (or commit ref): 1.11.0+dev-371-gd9c67a8c9
- Docker image: latest (12/5/2019 6:46pm)
- Operating system: Ubuntu 18.04
- Database (use `[x]`):
  - [X] MySQL
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Not relevant

## Description

- I am creating a new Gitea instance with docker-compose: https://gist.github.com/a20eac1d/1aea72456de9e823350d65d98a2f1d7d
- Opening the newly created instance in a web browser shows the sites layout badly messed up. I assume this is because of some issue loading both .css and .js files. There are multiple errors in the console: https://gist.github.com/a20eac1d/711d52db10e413d825542d87b4b48193
-  The error occurs in multiple web browsers (Firefox, Chrome, Tor) and multiple devices, with and without browser addons enabled
- Editing the docker-compose.yml and switching the version number from latest to 1.9.3 or 1.10.0 makes everything work just fine, so we know that it is definitely not an issue with my setup but rather a problem that was introduced between 1.10.0 and latest.

**Comment by axifive** [comment]
Already fixed in #9252
