### ISSUE TITLE
[Suggestion] Link page.

### ISSUE THREAD

**Issue by BaxAndrei** [go-gitea/gitea#9261]
![image](https://user-images.githubusercontent.com/12484505/70275099-1d394280-17b6-11ea-8560-fa03d92eb83d.png)
It would look much more aesthetic if the fields were 100% width or at least in the center.

**Comment by lunny** [comment]
I can't reproduce this on https://try.gitea.io/user/link_account?lang=en-US

**Comment by baxandrei** [comment]
![image](https://user-images.githubusercontent.com/12484505/70319139-41cf0200-182a-11ea-91f1-e14708913e28.png)

**Comment by lunny** [comment]
Could you clear the cache?

**Comment by baxandrei** [comment]
I tested incognito mode, it is not necessary to clean cache because it is not generated.

**Comment by baxandrei** [comment]
not yet please

**Comment by baxandrei** [comment]
Same issue on 1.12.0+dev-251-gd4096ab6a
![image](https://user-images.githubusercontent.com/12484505/73788059-0e1a4500-47a5-11ea-8c82-0b1af9b13a2c.png)

**Comment by zeripath** [comment]
It's really weird because this does not appear like this on our browsers. 

What browser version are you using?

**Comment by guillep2k** [comment]
Maybe it's an RTL language environment (e.g. Hebrew or Arabic)?
