### ISSUE TITLE
Web UI failing to load properly in latest docker image 

### ISSUE THREAD

**Issue by rsoper** [go-gitea/gitea#9263]
- Gitea version (or commit ref): 1.11.0+dev-371-gd9c67a8c9
- Git version: 2.21.0 (Apple Git-122.2)
- Operating system: macOS/Docker
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X] No
  - [ ] Not relevant
- Log gist: https://gist.github.com/rsoper/0bc53b2b9fd5eb790c99bdce360845eb

## Description

The UI appears to be significantly broken in the latest docker image - https://hub.docker.com/layers/gitea/gitea/latest/images/sha256-09db611bb967bf773ec36cf2516cb6929d9aaf9e5ee187f0e0669ff0ca01b627

Image for version 1.10.1 seems to be the most recent one working as expected. 

Default page before authentication is showing poor formatting, gitea icon too large, divs out of proper spacing/size. 
Once logged in the dashboard is showing multiple keys instead of the intended string. 

Ive made no changes to my configuration outside of updating to the latest image. 

Ive reverted to version 1.10.1 for now but can deploy the latest image to my server if you'd like to look around, its only me that uses it so no significant impact. 

## Screenshots

![Screen Shot 2019-12-05 at 6 34 10 PM](https://user-images.githubusercontent.com/20671094/70291148-2bc03380-178f-11ea-9851-e31f0486c8da.png)
![Screen Shot 2019-12-05 at 6 34 32 PM](https://user-images.githubusercontent.com/20671094/70291163-367ac880-178f-11ea-8ebf-5edb1bf5c8ce.png)

**Comment by techknowlogick** [comment]
fixed in #9252 please update to newer version of image.
