### ISSUE TITLE
The web page width will exceed the phone's screen when URL is long

### ISSUE THREAD

**Issue by MFYDev** [go-gitea/gitea#9264]
- Gitea version (or commit ref): 1.11-rc1
- Git version: latest
- Operating system: Ubuntu 18.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
https://git.fanyangmeng.com/FanyangMeng/Coding-Interview-University
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
Hi there,

First, thank you for making such excellent project. Gitea is really brilliant.

But there is serveral problems that make me frustrated for a long time.

To the first problem, I found that when I use my Android phone view the gitea, sometimes the web page width will exceed my phone's screen width. I found that this problem happens approximately on every page of try.gitea.io, would you please have a check on it and fix it? I think sometimes it is because the image's url is too long which cause this issue.

The second problem happens when I try to customize the gitea's template. I found that every time when I try to import a css/js file , which contains some changes, after restart the gitea, these changes can only display after I change the name of the css/js file and then reimport it again.

Although I know that the front end is not the vital part of gitea, but I sincerely hope that you can do some progress on it. It will be so much appreciated.

## Screenshots
![Screenshot_2019-12-06-11-57-28-831_com android chrome](https://user-images.githubusercontent.com/53750381/70295061-91103500-1820-11ea-9f7f-26758e5690aa.jpg)
![Screenshot_2019-12-06-11-57-31-017_com android chrome](https://user-images.githubusercontent.com/53750381/70295069-95d4e900-1820-11ea-91a9-0b84e3b2a9d8.jpg)

**Comment by FanyangMengDev** [comment]
Hi there, no rush actually just do not wanna this issue be forgotten.

I add some little problems on it. Would be appreciate if you can give me some feedback when you have free time.

**Comment by guillep2k** [comment]
You may want to disable the service worker in `app.ini` so CSS files and others are not cached:

```
[ui]
USE_SERVICE_WORKER = false
```

In Firefox, I use this button (F12) to prevent caching when testing things:

![image](https://user-images.githubusercontent.com/18600385/77256597-037d1780-6c4e-11ea-93ea-046a0708c75e.png)

**Comment by zeripath** [comment]
I think I might actually have already fixed this...

**Comment by lafriks** [comment]
Closing, please reopen if it is not fixed and can be reproduced in try.gitea.io
