### ISSUE TITLE
404 page after transferring repo ownership

### ISSUE THREAD

**Issue by guillep2k** [go-gitea/gitea#9268]
- Gitea version (or commit ref): 1.10.0

## Description

If a plain user from an organization transfers a private repository to the organization, the operation succeeds but the user gets redirected to a page to which they no longer have permissions (e.g. the user does not belong to the owners team) and a 404 is rendered.

This may also happen with other kinds of transfer ownership (e.g. user to user).

I think it's important for the user to know whether the operation was successful, so they should be redirected to their own home with a success message.

**Comment by lunny** [comment]
So the redirect address was wrong after transfer succeed.

**Comment by guillep2k** [comment]
The user was redirected to the same page (repo settings), but the user no longer had permission to access that. I don't have that problem being admin or owner; only plain users get this error.

**Comment by lunny** [comment]
I think this could be closed because now every transfer need to be confirmed by receivers.
