### ISSUE TITLE
@ function could not work right in the edit case

### ISSUE THREAD

**Issue by suli3** [go-gitea/gitea#9273]
- Gitea version (or commit ref): 1.10.0
- Git version:
- Operating system: centos7
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

I find that if i forgot ‘@someone’ when i release the issue,  i add ‘@him‘’ use the edit function，but notice email could not be sent to him. 

That means, if Andy must be added to the @ list before the issue content is release first time, or he could not get the notice email although he was also added to the @ list during editing. Now my temporary solution is to send a reply to this issue and add @ the person to the reply.

So i think it maybe something bug about the @ function for issue. Could anyone help with it please?

## Screenshots

![image](https://user-images.githubusercontent.com/1057425/70365759-08e86900-18ce-11ea-8f99-02a4b5cc74a1.png)

**Comment by guillep2k** [comment]
@esradioli This case is not supported yet. You can leave your issue open as a suggestion for a future enhancement.

**Comment by wxiaoguang** [comment]
Outdated
