### ISSUE TITLE
NoReply Address Always Dummy Address Regardless of Root URL Domain

### ISSUE THREAD

**Issue by bagasme** [go-gitea/gitea#9275]
- Gitea version (or commit ref): 1.9.0
- Git version: 2.17.1
- Operating system: Ubuntu 18.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:
(not relevant)

## Description
Installing Gitea set `NO_REPLY_ADDRESS` option on `app.ini` to dummy `noreply@example.org` address, regardless of domain in `ROOT_URL`. For NoReply emails to function correctly, use address from same domain as in `ROOT_URL`. For example, if `ROOT_URL` domain is `mygitea.instance`, `NO_REPLY_ADDRESS` should be `noreply@mygitea.instance`.

## Screenshots
(not relevant)

**Comment by bagasme** [comment]
@lunny I think `kind/docs` label isn't appropriate here, as this issue is about configuration.

**Comment by zeripath** [comment]
If I understand you correctly You mean to say that on this line:

https://github.com/go-gitea/gitea/blob/01a4a7cb14b3a48f9e8115d5bc93af7ae17f1275/modules/setting/service.go#L86

You think the default should be:

```go
Service.NoReplyAddress = sec.Key("NO_REPLY_ADDRESS").MustString(Domain)
```
You would need to update:

https://github.com/go-gitea/gitea/blob/ee7df7ba8c5e6a4b32b0c4048d2b535d8df3cbe9/custom/conf/app.ini.sample#L507

```ini
NO_REPLY_ADDRESS = %(DOMAIN)s
```

And it would be helpful to add a description in to https://github.com/go-gitea/gitea/blob/master/docs/content/doc/advanced/config-cheat-sheet.en-us.md#service-service as this option is not documented there.

**Comment by bagasme** [comment]
@zeripath what's purpose of `%(DOMAIN)s`?

**Comment by zeripath** [comment]
It's just to document that the default value is the string value of DOMAIN

**Comment by bagasme** [comment]
OK, but I'd like to assign this issue to someone else instead. I'm just contributing to Gitea by reporting issues (currently).

**Comment by bagasme** [comment]
@zeripath thanks for the PR
