### ISSUE TITLE
Add co-authors of a pull request when squash-merging

### ISSUE THREAD

**Issue by kolaente** [go-gitea/gitea#9281]
Currently, Gitea does not add any co-authors to the commit message if there was more than one author in a pull request and the pull request is squash-merged.

I would propose to append a message like the following to the commit message text box when merging:
```
Co-authored-by: User <user@mail.com>
```

This makes it easier to see with only a `git blame` later who participated code in that pull request.

**Comment by shilch** [comment]
It's a common standard for commit message trailers. Here's [a list of trailers](https://git.wiki.kernel.org/index.php/CommitMessageConventions) as a reference.

**Comment by shilch** [comment]
And [this](https://github.blog/2018-01-29-commit-together-with-co-authors/) is GitHub doing it.

**Comment by guillep2k** [comment]
Interesting. We could add `Acked-by:` for approvers.

**Comment by zeripath** [comment]
Agreed! I wanted to add this to the signing code but realised that it was out of scope.

It does need us to consider if we're squashing if we're going to add the co authors of co authored commits we're squashing too. This means we will likely need to semi parse the commit message...

**Comment by guillep2k** [comment]
> 
> 
> It does need us to consider if we're squashing if we're going to add the co authors of co authored commits we're squashing too. This means we will likely need to semi parse the commit message...

Interesting. Maybe a two-step feature?

**Comment by zeripath** [comment]
This is partially fixed by #9393 - A more complete implementation would do the following:

- [ ] Parse the commit messages and find their Co-Authored-By trailers to add those
- [ ] Would skip merges with the base branch and commits that are already in base branch 

I if we get both of those would mean that we might have better functionality than GH

**Comment by MarcelCoding** [comment]
Is it intended that this is always added, even If the email is the same as the actual committer email?
```
marcel@marcel:~/stack$ git log
commit 9a0fb7f3f710673ae391bf3d881e53fdfec06577 (HEAD -> main, origin/main, origin/HEAD)
Author: Renovate Bot <renovate-bot@noreply.git.m4rc3l.de>
Date:   Tue Aug 9 00:55:37 2022 +0200

    Configure Renovate (#3)

    Reviewed-on: https://git.m4rc3l.de/marcel/stack/pulls/3
    Co-authored-by: Renovate Bot <renovate-bot@noreply.git.m4rc3l.de>
    Co-committed-by: Renovate Bot <renovate-bot@noreply.git.m4rc3l.de>
```

**Comment by Basitx72** [comment]
Co-authored-by: Maverick920 <basitx77@gmail.com>

**Comment by Preetiraj3697** [comment]
Co-authored-by: Preetiraj3697 preetiraj122000@gmail.com
