### ISSUE TITLE
Unvendor go modules

### ISSUE THREAD

**Issue by silverwind** [go-gitea/gitea#9283]
Based on the vote results in https://github.com/go-gitea/gitea/issues/9170#issuecomment-559480784 we should un-vendor the go modules. In combination with the GOPROXY setting and a reliable proxy server, it will be safe to do so even if the sources go offline.

Vote results:
<img width="324" src="https://user-images.githubusercontent.com/115237/70379481-7f688380-192d-11ea-85c8-24bcc6dfa199.png">

**Comment by shilch** [comment]
Isn't that 5 against un-vendoring?

**Comment by sapk** [comment]
@shilch not exactly since some vote for two options.

On the subject, I think we should wait Go1.14 release to have all Go supported version with proxy support.
