### ISSUE TITLE
Hide old Reactions wich are no longer Allowed

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#9286]
This issue colect options of the gitea communety about title topic

**Comment by guillep2k** [comment]
IMHO the only reason to remove a reaction type is because it's causing problems. So, the reaction itself should disappear from the history if that's the case. Having said that, I don't like that idea; I'd rather let the admin have some moderating tools to manage that, but we don't want Gitea to become a social network (and it's a lot of work to do that properly), so... Tough choice.

**Comment by jolheiser** [comment]
I think if possible it'd be better to leave the DB intact and just not display it.  
Then, if an admin decides to revert it later (or it was a mistake in the first place) they will display again.

**Comment by 6543** [comment]
I created an poll: :D
[![](https://api.gh-polls.com/poll/01DVKWF0MEP7HZSB97N1VRYCXT/Show%20Old)](https://api.gh-polls.com/poll/01DVKWF0MEP7HZSB97N1VRYCXT/Show%20Old/vote)
[![](https://api.gh-polls.com/poll/01DVKWF0MEP7HZSB97N1VRYCXT/Hide)](https://api.gh-polls.com/poll/01DVKWF0MEP7HZSB97N1VRYCXT/Hide/vote)
[![](https://api.gh-polls.com/poll/01DVKWF0MEP7HZSB97N1VRYCXT/Delete)](https://api.gh-polls.com/poll/01DVKWF0MEP7HZSB97N1VRYCXT/Delete/vote)

**Comment by 6543** [comment]
My opinion is to leav old reaction untoched but only allow deletion of not alowed one ...
If a reaction is **realy** so harmfull a `DELETE FROM reaction WHERE Type like "harmefull"  ...

**Comment by 6543** [comment]
@go-gitea/maintainers poll your option if you have not ... and then wee will see :)

**Comment by 6543** [comment]
The poll is clear about this ... I'll send a PR

**Comment by lunny** [comment]
We should have a more accurate meaning about the config.
```
; All available reactions. Allow users react with different emoji's
: For the whole list look at https://gitea.com/gitea/gitea.com/issues/8
REACTIONS = +1, -1, laugh, hooray, confused, heart, rocket, eyes
```
There are two meaning about `REACTIONS`. One is what reactions you will see, another is what reactions you can use. Most of the time they are the same. But when you change it serval times, it will not.

Or maybe we should have two options here. :)

**Comment by 6543** [comment]
@lunny about secound setting option:
 - think this will be rare used
 - can iretate ...

**Comment by 6543** [comment]
PR is here: #9387
