### ISSUE TITLE
HTTP errors 499

### ISSUE THREAD

**Issue by fmarcia** [go-gitea/gitea#9291]
- Gitea version: 1.10.0, go1.13.4 : bindata, sqlite, pam
- Git version: 2.24.0
- Operating system: archlinux (armv7)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist: [excerpt from systemd log of caddy](https://gist.github.com/fmarcia/42131d33a2aaef94026613ee0c77c2de)

## Description
I'm using gitea behind a reverse proxy (caddy v1.0.4) and I get sometimes HTTP status code 499.

**Comment by zeripath** [comment]
The 499s are coming from caddy not Gitea and are indicating that the client closed the connection before caddy  & Gitea had finished processing. It would be good to correlate them with the Gitea logs to check if there is any associated error.

**Comment by fmarcia** [comment]
Nothing visible on gitea side because I managed to get minimum logs on my sd card.
