### ISSUE TITLE
FastCGI over Unix socket

### ISSUE THREAD

**Issue by clarfonthey** [go-gitea/gitea#9295]
- Gitea version (or commit ref): `Gitea version 1.9.3 built with go1.13.1`
- Git version: `git version 2.23.0`
- Operating system: `OpenBSD 6.6 GENERIC.MP#0 amd64`

## Description

Right now, setting `PROTOCOL = fcgi` allows FCGI over TCP only, which is a bit odd, considering how FastCGI is something that's usually only run locally. If `HTTP_ADDR` is set to a path for a unix socket, Gitea will error stating that the address is unknown (because it's not actually a hostname).

Because OpenBSD's httpd does not allow full HTTP proxying and only FastCGI, using a unix socket is not possible with this configuration.

This would be a breaking change, but I would personally recommend renaming the `unix` protocol to `unix+http` and adding an additional `unix+fcgi` protocol as well.

Ideally, using the `unix` protocol without specifying which would emit a warning.

**Comment by zeripath** [comment]
I think it would be easiest just to use `unix+fcgi` - then this doesn't need to be a breaking change.
