### ISSUE TITLE
github.com signup requires running nonfree software (thus, so does contributing to gitea for some people)

### ISSUE THREAD

**Issue by ian-kelling** [go-gitea/gitea#9303]
Repro:

Without running javascript and without being logged in to github, go to https://github.com/join

The page says

"GitHub requires JavaScript enabled during sign up, for our signup captcha. Please enable JavaScript during sign up."

Viewing source, there are various nontrivial obfuscated nonfree javascript
files that the page wants to run, such as
https://github.githubassets.com/assets/frameworks-ef488d77.js
and https://cdn.arkoselabs.com/fc/js/e7231a6fd0dc61598e252fe084a804ef/standard/funcaptcha_api.js

For background on this issue, please read

https://www.gnu.org/philosophy/javascript-trap.en.html

This seems to be more reason to move forward for Gitea to self-host itself, issue #1029

I would have made this a comment there, but its not open to comments from the public.

**Comment by lunny** [comment]
The moving is on the process.

**Comment by techknowlogick** [comment]
Closing this as #1029 is about the move, and the move is ongoing.

**Comment by GitMensch** [comment]
@lunny: I'm asking for an update (here because the other issue has discussion locked) - seems like everything on the todo-issue has been solved but the migration of this repo itself, and previous repos were migrated already.

... so - can we expect the move "in the next weeks" or is there a blocking issue not listed there?

**Comment by lunny** [comment]
@GitMensch I think all the feautures are ready to move, but it's failed because of network reason. The gitea repository will spend about 80GB disk space.

**Comment by jondo** [comment]
What is taking all that space? Binary blobs? Is a history cleanup necessary?

**Comment by lafriks** [comment]
@jondo mostly binaries that are attached to releases

**Comment by jondo** [comment]
Ah, I understand! The git repo itself is just about 180 MB. What about simply keeping older binaries downloadable here and just copying the most recent ones over?

**Comment by GitMensch** [comment]
I think the suggestion of @jondo is very reasonable, especially when this is all that prevents the move to self-hosting!
@lunny @lafriks What do you think about this? What do you think about reopening either this issue, creating a new one for "the last step to be done" (obviously other then migration is change in documentation, site, and announcement) or reopen discussion at #1029?

**Comment by lafriks** [comment]
We need to merge this PR #11387 and migrate gitea.com to use minio for storing attachments first

**Comment by lunny** [comment]
I also send another PR #12244 to try to resolve the network problem when migrating from github to gitea.com since the total gitea repository will spend about 80GB disk or network.
