### ISSUE TITLE
Current password security rules prevent use of highly secure diceware method

### ISSUE THREAD

**Issue by melissasage** [go-gitea/gitea#9308]
First off, I want to commend Gitea on requiring password complexity requirements; it's a great step to ensure user security.

That said, I went to make a password using the diceware method on a Gitea instance, only to have this password rejected. It then accepted a less-secure password that I generated using my password manager. This is clearly a security and usability issue.

I don't know the precise security requirements for your password, but a password composed only of the 26 lowercase letters that is 18 characters long is more secure than one that uses all 95 ASCII characters but is only 12 characters long. Given that, I'd like to suggest that any password longer than 18 characters should automatically pass the security check.

For more info on the diceware method: 
https://www.eff.org/deeplinks/2016/07/new-wordlists-random-passphrases
https://theintercept.com/2015/03/26/passphrases-can-memorize-attackers-cant-guess/

**Comment by InnovativeInventor** [comment]
NIST's password recommendations are always worth a read (they describe the current best practices when it comes to password requirements, etc.):

Recommendation (https://pages.nist.gov/800-63-3/sp800-63b.html#memsecret):
Memorized secrets SHALL be at least 8 characters in length if chosen by the subscriber. Memorized secrets chosen randomly by the CSP or verifier SHALL be at least 6 characters in length and MAY be entirely numeric. If the CSP or verifier disallows a chosen memorized secret based on its appearance on a blacklist of compromised values, the subscriber SHALL be required to choose a different memorized secret. **No other complexity requirements for memorized secrets SHOULD be imposed.** A rationale for this is presented in Appendix A Strength of Memorized Secrets.

Rationale: https://pages.nist.gov/800-63-3/sp800-63b.html#appA

These recommendations should be implemented, imo (it would fix the diceware issue that @melissasage is observing).

**Comment by Nutomic** [comment]
Not stale

**Comment by danwarren** [comment]
I ran into this issue when I updated gitea recently, since I had an older app.ini file it did not have these entries, and so went with the multi-symbol default.

We have a diceware style random passphrase generator we use, and so this was undesirable, luckily, this is fixable in config

I added these two configs to the security section of app.ini, and restarted gitea

PASSWORD_COMPLEXITY = off
MIN_PASSWORD_LENGTH = 16

**Comment by lafriks** [comment]
As this is configurable as @danwarren recommended I will close this issue
