### ISSUE TITLE
Weird repositories on my try.gitea.io organization

### ISSUE THREAD

**Issue by kybin** [go-gitea/gitea#931]
- Gitea version (or commit ref): try.gitea.io
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

Hello, I created a organization long time ago in try.gitea.io

Today I see many repositories in my organization dash board that doesn't actually exist. Please see https://try.gitea.io/org/di/dashboard

Another wierd thing is I can see many issues in https://try.gitea.io/org/di/issues .
But when I click the link it send me another repositories, those are not relavant with di organization. The PR section acts exactly same. 

Please take a look.

**Comment by lunny** [comment]
#933 only reosolved dashboard problem. Not resolved  https://try.gitea.io/org/di/issues

**Comment by kybin** [comment]
Please check https://try.gitea.io/pulls page too.

**Comment by lunny** [comment]
It's still not resolved completely.

**Comment by lunny** [comment]
I'm working on this.

**Comment by lunny** [comment]
@kybin Please confirm #943 has resolved this.

**Comment by kybin** [comment]
It isn't resolved yet.

I think it is safe to say my id and password, so you could see my pages when you debug it. 

id: kybin
password: gitea

**Comment by lunny** [comment]
No. try.gitea.io is not updated to 847527f yet. current is 140967f0. Maybe you can confirm it after a while.

**Comment by kybin** [comment]
Ah, ok. I didn't catch that. 

I deleted the previous post.

**Comment by lunny** [comment]
Now it's the newest version and I think it should be fixed.

**Comment by kybin** [comment]
Seems try.gitea.io is down. So I can't test it.

**Comment by tboerger** [comment]
> Seems try.gitea.io is down. So I can't test it.

This have been a different issue, everything is up and running.

**Comment by kybin** [comment]
Yes, it's fixed now. Thank you for the effort!
