### ISSUE TITLE
Label description when create an issue

### ISSUE THREAD

**Issue by ejouvin** [go-gitea/gitea#9310]
- Gitea version (or commit ref): 1.9.3
- Git version: 
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
When I create a issue, I can select label.
![image](https://user-images.githubusercontent.com/8817923/70505081-5f9caf80-1b27-11ea-9c76-b67abee7894f.png)

When I update the ticket, the label contains also the description
![image](https://user-images.githubusercontent.com/8817923/70505125-7f33d800-1b27-11ea-87c1-e571ea9a90a3.png)

It could be nice to have the label description also when I create the issue.
...

**Comment by zeripath** [comment]
Compare the new issue template label section:

https://github.com/go-gitea/gitea/blob/33662399d59a94436e6acb5e5bf41935dbc75328/templates/repo/issue/new_form.tmpl#L40-L58

With the extant issue template label section:

https://github.com/go-gitea/gitea/blob/33662399d59a94436e6acb5e5bf41935dbc75328/templates/repo/issue/view_content/sidebar.tmpl#L5-L26

**Comment by zeripath** [comment]
It's probably going to be a two line pr updating the appropriate part in the first one to look a bit more like the second part

**Comment by zeripath** [comment]
yup it was a 2 line PR
