### ISSUE TITLE
Abilitiy to retrieve raw files via http basic auth

### ISSUE THREAD

**Issue by frankhommers** [go-gitea/gitea#9312]
In order to get files directly from git through curl or wget it would be nice that we could authenticate through basic Auth of requests to the raw files.

In this we we can easily wget or curl a single file. E.g. for scripts.

This way we can use:

```
curl -u username:password https://git.example.org/<org>/<repo>/raw/branch/master/<file>.sh
```

or

```
wget --http-user=[HTTP-USER] --http-passwd=[HTTP-PASSWORD] https://git.example.org/<org>/<repo>/raw/branch/master/<file>.sh
```

**Comment by axifive** [comment]
You can do this already https://try.gitea.io/api/swagger#/repository/repoGetRawFile
