### ISSUE TITLE
Migrated issues do not get indexed, search does not work

### ISSUE THREAD

**Issue by ashimokawa** [go-gitea/gitea#9331]
- Gitea version (or commit ref): 1.10.1+git, also master
- Git version: 2.20.1
- Operating system: Debian 10
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes https://try.gitea.io/mrsdizzie/Pix-Art-Messenger/issues?type=all&state=open&labels=0&milestone=0&assignee=0&q=Problems
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

Migrated issues do not get indexed, search does not work, examples are
https://try.gitea.io/mrsdizzie/Pix-Art-Messenger, when you search for something in the issues there is no result.

https://try.gitea.io/mrsdizzie/Pix-Art-Messenger/issues?type=all&state=open&labels=0&milestone=0&assignee=0&q=Problems

Commenting to an imported issue, seems to trigger indexing for the specific issue.
If you search in our fully migrated Gadgetbridge issues (yes we left github), and search for "Move" you will find one issue because I commented there after the move. Serching for anything else eg. "Pebble" fails.

https://codeberg.org/Freeyourgadget/Gadgetbridge/issues

Is there any way to trigger issue indexing manually?

**Comment by lunny** [comment]
Currently no manually method to reindex issues per repository. It can only be triggered when you deleted all the issue indexers and restart gitea.

**Comment by ashimokawa** [comment]
@lunny 
Thanks! That worked :)
