### ISSUE TITLE
500 internal server error when using emoji in issue.

### ISSUE THREAD

**Issue by devgar** [go-gitea/gitea#9336]
- Gitea version (or commit ref): 1.9.4
- Git version: 2.17.1
- Operating system: Ubuntu 18.04 (server) MacOs 10.15.1 (client) Chrome Browser
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
  - [x] I Couldn't log in

- Log gist:

## Description
Got a 500 error when creating an issue label with an emoji as label.
Algo got error when creating an issue with emoji as title.
Emojis are allowed in file content, also in file names.

## Screenshots
![Captura de pantalla 2019-12-12 a las 17 42 15](https://user-images.githubusercontent.com/2792291/70732500-d349e280-1d08-11ea-9196-8127eff51a10.png)
![Captura de pantalla 2019-12-12 a las 18 02 05](https://user-images.githubusercontent.com/2792291/70732984-b235c180-1d09-11ea-9385-3346ff9fa47a.png)
![Captura de pantalla 2019-12-12 a las 18 01 20](https://user-images.githubusercontent.com/2792291/70733010-bbbf2980-1d09-11ea-8d6f-0ae81d94c887.png)

## HTTP GENERAL
Request URL: https://git.edgarai.com/devgar/build-doc/issues/new
Request Method: POST
Status Code: 500  (from ServiceWorker)
Referrer Policy: no-referrer

## RESPONSE HEADERS
content-type: text/html; charset=UTF-8
date: Thu, 12 Dec 2019 16:58:10 GMT
server: nginx/1.14.0 (Ubuntu)
status: 500
x-frame-options: SAMEORIGIN

## REQUEST HEADERS
Provisional headers are shown
Content-Type: application/x-www-form-urlencoded
Origin: null
Sec-Fetch-User: ?1
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_1 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) Version/10.0 Mobile/14E304 Safari/602.1

 ## FORM DATA
title: ▷Prueba
content: 
ref: 
search: 
label_ids: 
milestone_id: 
assignee_ids: 
(also includes a `_csrf` value what I suppose is a session thing)

**Comment by lafriks** [comment]
I think problem could be in your mysql table encoding

**Comment by lunny** [comment]
You should use utf8mb4 but not utf8 in your mysql database.
