### ISSUE TITLE
Search bar under "Explore" does not work as expected for repositories when signed in

### ISSUE THREAD

**Issue by hhenkel** [go-gitea/gitea#934]
- Gitea version (or commit ref): 1.0.0+269-g3a91ac51
- Git version: 2.8.3
- Operating system: Linux/official docker images
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

On my local instance the search bar under "explore" does not seem to work for repositories when I'm signed in (search for users and organizations does work localy). When trying to reproduce that behavior on try.gitea.io you will notice that the search works if your not sigend in.

**Comment by lunny** [comment]
any screenshot?

**Comment by hhenkel** [comment]
When signed in and then search I see not only the stuff I'm looking for:
![grafik](https://cloud.githubusercontent.com/assets/2813782/22965516/2cbc837c-f35e-11e6-94c9-d0887cf63d8b.png)

When not signed in, it works:
![grafik](https://cloud.githubusercontent.com/assets/2813782/22965561/6814b71e-f35e-11e6-97e1-92c1e5a1f3e8.png)

**Comment by lunny** [comment]
@appleboy maybe you can look at this.

**Comment by appleboy** [comment]
OK. I can take this.

**Comment by appleboy** [comment]
@hhenkel @lunny 

Please help to review and try it. #1009
