### ISSUE TITLE
New repositories in template?

### ISSUE THREAD

**Issue by bitnom** [go-gitea/gitea#9342]
Wondering if you can show me an example of how to loop through the most recently created repositories and most stars in homepage template. Same as like `/explore/repos?sort=newest&q=`

**Comment by axifive** [comment]
Template handler gets already sorted repositories list, so in all cases, it just ranges all and inserts fields according to if conditions.

The template that you interested in:
https://github.com/go-gitea/gitea/blob/master/templates/explore/repo_list.tmpl

and handler: https://github.com/go-gitea/gitea/blob/f09cdb239cb7e2d96c6bc9d5d43ada165b1240d1/routers/home.go#L166
