### ISSUE TITLE
Import & Sync Gitea to Torgit

### ISSUE THREAD

**Issue by larzx** [go-gitea/gitea#9350]
In posting this issue, I attempted to use Github via Tor. To register and login, I was forced to perform several steps that could have easily deanonymized me. Gitea has been used to create Torgit, an onion service on the Tor network geared towards privacy.

Suggest: Enacting a policy that commits are also pushed to Torgit. After importing the repo to Torgit, pushing is as easy as: `torsocks git push -u origin master`

Torgit site address: http://torgitsh252grlhzr2bf3wf2ygncj7kfy7qa5rli2bufpgtwdrfx74id.onion

**Comment by 6543** [comment]
is down
