### ISSUE TITLE
[Docs] Clarify TLS Termination Proxy

### ISSUE THREAD

**Issue by bagasme** [go-gitea/gitea#9354]
# Description

On [HTTPS Setup](https://docs.gitea.io/en-us/https-setup/), reverse proxy can be used for providing HTTPS instance. In reality, such setup is called [TLS Termination Proxy](https://en.wikipedia.org/wiki/TLS_termination_proxy).

Perhaps the docs can be rewritten as:

```
You can also enable HTTPS by using reverse proxy. Set up your favorite reverse proxy (Apache,
NGINX, or Caddy) and follow documentation of the program of your choice to enable HTTPS site.

NOTE: Enabling HTTPS by this method is referred as TLS Termination Proxy. The reverse proxy
handle TLS connections, and decrypted them for passing to Gitea. This is fine as long as the reverse
proxy and Gitea instance are either on the same machine, or on different machine on private
network (the proxy is exposed to outside network). If your Gitea instance is on public network, and
you want to enable HTTPS with reverse proxy, it is recommended to also encrypt connections from
your proxy to Gitea by follow instructions for built-in server and change proxy URL to https://[URL].
```

**Comment by lunny** [comment]
Please send a PR to update that.

**Comment by bagasme** [comment]
@lunny Sorry, I'm not trying to open a PR yet currently, just a suggestion.

Why? I only have metered internet connection (about 1 GB per day). Getting `code.gitea.io` sources via `go get` can easily exhaust internet quota quickly.

**Comment by bagasme** [comment]
I had opened PR @ #9491.
