### ISSUE TITLE
Compare-Button leads to 404

### ISSUE THREAD

**Issue by evilstiefel** [go-gitea/gitea#936]
- Gitea version (or commit ref): 1.0.0+272-gcf47532e
- Git version: 2.8.3
- Operating system: Linux ad0c0ea10d83 4.4.0-62-generic #83-Ubuntu
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL): https://try.gitea.io/gitea/gitea/compare/master...gitea:master
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
When creating a repository, next to the branch-dropdown, it shows an image to compare branches. That link is always 404, since it will be of the form 
`try.gitea.io/<user>/<repo>/compare/<branch1>...<user>:<branch2>`
It should be:
`try.gitea.io/<user>/<repo>/compare/<branch1>...<branch2>`
If I change the address in the bar and remove the second user reference, the site loads fine.

**Comment by tboerger** [comment]
OK, i can confirm it on try.gitea.io, example: Go to the gitea/gitea repo and click the pull request button leads to 404. If you try to do the same from a fork it works totally fine.

**Comment by lunny** [comment]
@evilstiefel please confirm #948 fix this.

**Comment by evilstiefel** [comment]
@lunny I can confirm your change fixes this issue
