### ISSUE TITLE
Reload config or Inform user to restart Gitea when settings change

### ISSUE THREAD

**Issue by mschoettle** [go-gitea/gitea#9364]
- Gitea version (or commit ref): 1.10.1
- Git version: 2.22.2
- Operating system: Raspian Buster (10)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite

## Description

I freshly installed Gitea 1.10.1 (with Docker if that makes a difference) on my Raspberry Pi. Upon accessing the web interface I got to see the setup page where I changed the (default) DB setting from SQLite to MySQL. Once the installation completed everything seemed to work. The one exception being the heat map which I saw in #6405 that if the settings changed the Gitea should be restarted (once I did it worked).

However, it would be great to either reload the config (it seems to know to use another DB for everything else), or simply tell the user to restart Gitea.

**Comment by lunny** [comment]
That's a bug but we should not restart gitea just load the configuration correctly.

**Comment by mschoettle** [comment]
This is still valid.

**Comment by insanemal** [comment]
This doesn't look like it's been resolved yet. 

It's causing issues with the k8's install I have. However because k8s likes to ensure containers are ready I can't just restart it and have things work.. It's a little, less than fun

**Comment by veil3** [comment]
this issue is still a thing

**Comment by lunny** [comment]
I think this has been resolved 
ref https://github.com/go-gitea/gitea/blob/main/routers/install/install.go#L523
