### ISSUE TITLE
Pushing to new repository does not change it to non-empty

### ISSUE THREAD

**Issue by mschoettle** [go-gitea/gitea#9365]
- Gitea version (or commit ref): 1.10.1
- Git version: 2.22.2
- Operating system: Raspian Buster (10)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

```
[Macaron] 2019-12-15 19:32:42: Started GET /user/test.git/info/refs?service=git-receive-pack for 192.168.1.119
[Macaron] 2019-12-15 19:32:42: Completed GET /user/test.git/info/refs?service=git-receive-pack 401 Unauthorized in 12.255841ms
[Macaron] 2019-12-15 19:32:42: Started GET /user/test.git/info/refs?service=git-receive-pack for 192.168.1.119
[Macaron] 2019-12-15 19:32:43: Completed GET /user/test.git/info/refs?service=git-receive-pack 200 OK in 410.181919ms
[Macaron] 2019-12-15 19:32:43: Started POST /user/test.git/git-receive-pack for 192.168.1.119
[Macaron] 2019-12-15 19:32:43: Completed POST /user/test.git/git-receive-pack 200 OK in 381.062007ms
[Macaron] 2019-12-15 19:32:50: Started GET /user/test for 192.168.1.119
[Macaron] 2019-12-15 19:32:50: Completed GET /user/test 200 OK in 41.880096ms
```

## Description

I created a new repo and pushed a local repository. I tried it both with `--all` (it has two branches) and without (pushed only master). Either way the repository is not changed to non-empty. I did it manually in the DB to set the `is_empty` column to `0` which fixed the problem.

**Steps to reproduce**

1. Create a new repo
1. Take an existing repo on your machine and add the new repo as a remote `test`
1. `git push -u test`

**Comment by timonegk** [comment]
I am experiencing the same problem with PostgreSQL, Debian Buster and Gitea 1.10.1.

**Comment by timonegk** [comment]
Oh, I think the problem is the `noexec` flag. I am using podman for virtualization which mounts volumes with `noexec` by default. The [corresponding issue](https://github.com/containers/libpod/issues/4318) seems to be [fixed already](https://github.com/containers/libpod/pull/4557), but my release does not contain the fix yet. I will try again with the current release and report the results here.

**Comment by timonegk** [comment]
Yes, that was the problem. Thank you for the quick response!

**Comment by timonegk** [comment]
Well I don't know if this works for @mschoettle too

**Comment by zeripath** [comment]
Hmm I think I'll leave it closed unless they write back to say that doesn't explain their problem

**Comment by mschoettle** [comment]
Thanks.

I had `user` in my mount options which implies `noexec`. Without it it works now.

However, I think there should be some indication (in the logs or somewhere else) that the hooks are not executable.

**Comment by iwzoo** [comment]
I'm having exact the same problem here. I run gitea + sqlite docker container on debian.

**Comment by mschoettle** [comment]
@iwzoo: Did you check this [comment](#issuecomment-567889477)?

I connected to the container and tried to execute a hook manually (for example: `/data/git/repositories/<user>/<repo>/hooks/post.receive.d/gitea`) which gave me "permission denied". That way I knew it was the problem described above.
