### ISSUE TITLE
[Docs] Instructions for Apache reverse proxy with Certbot

### ISSUE THREAD

**Issue by nztim** [go-gitea/gitea#9366]
I've just spent a bit of time trying to configure Apache as a reverse proxy for Gitea. It works fine as per the docs until you want to use Certbot. It seems to me that the configuration in the docs results in the acme challenge being proxied to Gitea (and a 404) regardless of whether you have a document root, an alias in place or anything. 

The solution I used was to add `ProxyPass /.well-known !` on the line before `ProxyPass / http://localhost:3000/ nocanon`, there may be other solutions. Do you think this would be useful to add to the docs?

**Comment by lunny** [comment]
Please send a PR and we can discuss there.

**Comment by techknowlogick** [comment]
Closing as this has been added to docs
