### ISSUE TITLE
Registering with used email-address should fail

### ISSUE THREAD

**Issue by evilstiefel** [go-gitea/gitea#937]
- Gitea version (or commit ref): 1.0.1+1-gab4eb0da
- Git version: 2.8.3
- Operating system: Linux e94dde8df2eb 3.13.0-108-generic #155-Ubuntu
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

When trying to use the confirmation link sent to a given address, if the address has been used by another user, you will see a 500 server error page. 

The logs then show:

`2017/02/14 20:48:52 [D] CSRF Token: oIrHzXnN6saOyZ9BPkd867BQzGM6MTQ4NzEwNTMyMDQ3MzcxNjcwOQ==
2017/02/14 20:48:52 [...routers/user/auth.go:301 Activate()] [E] UpdateUser: e-mail has been used [email: <user>@<domain>]
`
Upon registration, already used addresses should be rejected.

**Comment by lunny** [comment]
I think the register email check has been resolved by bdad3b259aab7ac78b9def5bf4fafac880d0301f, maybe you can checkout master to test if the problem exists. I will close this, please feel free to reopen it.
