### ISSUE TITLE
Remove jQuery Migrate

### ISSUE THREAD

**Issue by silverwind** [go-gitea/gitea#9372]
[jQuery Migrate](https://github.com/jquery/jquery-migrate) was added in https://github.com/go-gitea/gitea/pull/7425 for the jQuery 3.0 migration but it's not something that's meant to be shipped permanently. From their README:

> jQuery Migrate makes this easier, by restoring the APIs that were removed ... That way you can spot and fix what otherwise would have been errors, until you no longer need jQuery Migrate and can remove it.

@techknowlogick were there any specific issues that lead to you integrating it or was it only added  "just in case"?

**Comment by techknowlogick** [comment]
@silverwind sadly Semantic-UI bites us again using deprecated functions (there may also be a few deprecated functions used in index.js too, but I don't remember which ones). I don't think we can stick with Semantic-UI anymore, with the accessibility problems as well as deprecated code. We should switch fully to Formantic-UI

**Comment by silverwind** [comment]
Okay, if semantic-ui depends on removed functionality, it itself needs to be replaced.
