### ISSUE TITLE
Deployment keys should not collide with user keys

### ISSUE THREAD

**Issue by evilstiefel** [go-gitea/gitea#938]
- Gitea version (or commit ref): Gitea Version: 1.0.1+1-gab4eb0da
- Git version: git version 2.11.0
- Operating system: Linux e94dde8df2eb 3.13.0-108-generic #155-Ubuntu
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
When trying to add a SSH key, if it has been used as a deployment key on the site, the user should be warned about that collision and the key be rejected. Otherwise, pushing will simply fail with the following git output:
```
Gitea: Key permission denied
Cannot push with deployment key: 3
fatal: Could not read from remote repository.
```

**Comment by lesderid** [comment]
Has this been fixed yet?

**Comment by zeripath** [comment]
Yes. #5939 and #5966 should fix this.

Situations whereby there are already duplicated keys won't be fixed by this PR but new ones won't get produced.
