### ISSUE TITLE
Internal Error after PR merge

### ISSUE THREAD

**Issue by jolheiser** [go-gitea/gitea#9380]
- Gitea version (or commit ref): d1a49977b
- Git version: Whatever try uses
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes https://try.gitea.io/jolheiser/Test1/pulls/6
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

1. Create a PR from a branch on same repo
2. Delete branch
3. Restore branch
4. Merge PR (I used default, didn't check other merge styles)

Example error from local
```
2019/12/16 21:49:23 routers/repo/pull.go:319:PrepareMergedViewPullInfo() [E] GetCompareInfo: exit status 128 - fatal: ambiguous argument 'ffd89af277e933957146da58988b47139abb1e33...refs/pull/1/head': unknown revision or path not in the working tree.
        Use '--' to separate paths from revisions, like this:
        'git <command> [<revision>...] -- [<file>...]'
```

**Comment by bagasme** [comment]
@jolheiser What *delete branch* means?

**Comment by jolheiser** [comment]
@bagasme 
![delete_branch](https://user-images.githubusercontent.com/42128690/71018069-64c8a400-20bd-11ea-932b-c3cbd7977f10.png)

**Comment by zeripath** [comment]
This is likely because - I in my infinite stupidity - decided not to use the internal merge pulls ref on the base branch. We do need to restore that.
