### ISSUE TITLE
Adding severity as an attribute to an issue

### ISSUE THREAD

**Issue by rlfnb** [go-gitea/gitea#9386]
- Gitea version (or commit ref): new functionality
- Git version: n/a
- Operating system: n/a 
- Database (use `[x]`): n/a
## Description
Would be nice to have an additional attribute "severity" for each issue. Severity types should be configurable like the labels are at the moment (customizing own severity types) and assign it to an issue.

**Comment by mrsdizzie** [comment]
What would be a use case that isn't covered by using existing labels functionality to indicate issue severity?

**Comment by lunny** [comment]
I think we need a perior according labels feature but not a new field.

**Comment by rlfnb** [comment]
> What would be a use case that isn't covered by using existing labels functionality to indicate issue severity?

Basically, a severity is a one to one relations hip and labels might be added as many as available. Furthermore, an own field would allow to set a default value, which is not possible with tags as well.
