### ISSUE TITLE
[LDAP] Deactivating user account via gitea web does not deactivate

### ISSUE THREAD

**Issue by Perflyst** [go-gitea/gitea#9391]
- Gitea version (or commit ref): 1.10.1
- Git version: 2.11.0
- Operating system: Debian 10
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant

## Description

If an user from external auth source (e.g. LDAP) gets deactivated by an admin via gitea web admin panel the user is still visible by anyone and is not really deactivated.

**Comment by 6543** [comment]
as I know inly LDAP auth has the option to update/deactivate user info

and a deactivated user is still visible (wich has nothing to do with LDAP)
for securety reasons a sync process should not delete things

**Comment by lafriks** [comment]
Activation does not delete user, it just can't login
