### ISSUE TITLE
Web editor submit button disabled.

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#9395]
<img width="673" alt="图片" src="https://user-images.githubusercontent.com/81045/71048229-9737d700-2179-11ea-9d78-16529025e09b.png">

**Comment by mrsdizzie** [comment]
Did you make changes to the file? The button is disabled if you haven't made any changes to the file to prevent empty commit

**Comment by lunny** [comment]
Yes, I have made. This maybe an effection of the fomantic framework?

**Comment by mrsdizzie** [comment]
Hmm not sure, I can't reproduce this on try with the new fomantic changes (but perhaps #9400 has fixed this)

**Comment by lunny** [comment]
@mrsdizzie I think #9400 fixed this.
