### ISSUE TITLE
Webhook not activated when setting a label on an issue

### ISSUE THREAD

**Issue by x-beaudet** [go-gitea/gitea#9403]
- Gitea version (or commit ref): 1.10.1
- Git version: 2.20.1
- Operating system: Raspbian GNU/Linux 10 (buster)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x ] Not relevant
- Log gist:

## Description
When setting a label with a 3d party app (gitnex in my case) the corresponding event is not fired and the hook doesn't activate itself.

Step to reproduce :
- create a web hook reacting to issues events, and listen to it someway,
- create issue (API or web ui is ok : creating the ticket emits the event), 
- use the API to set a label to the issue : the label is correctly set in gitea, but the webhook is not activated
...

**Comment by lunny** [comment]
There is any failed webhook records on webhook setting?

**Comment by x-beaudet** [comment]
no. everything looks right...

**Comment by lunny** [comment]
Then is there a successful webhook?

**Comment by x-beaudet** [comment]
yes : when creating the issue, the webhook works as expected.
its's juste when setting a label that it dosen't seem to work.

if context can help : 
the webhook is an url on integromat.com that fires a work flow which objective is to create a todo in my todoist app.
- when i create the issue, the todo is created like expected (web ui or api either)
- when i set the bug label in the web UI, the todo is updated as expected (and there is a log confirming it in integromat)
- when i set the same label with gitnex (i.e. using gitea API), the todo is not updated (and there is no log at all in integromat : the listening address is not queryed).

**Comment by lunny** [comment]
Have you chosed `fire all events` on webhook setting page?

**Comment by x-beaudet** [comment]
no. I selected ``custom events`` / ``issue events`` (i see the names in french, english version ma be slightly different)
the list of event for issue event contains the french translation of "label updated"
as i said, it works for updating label with web UI....

it seems that the API endpoint does not fire the event and the web UI does

**Comment by 6543** [comment]
side note: come up in https://gitea.com/gitnex/GitNex/issues/239

**Comment by x-beaudet** [comment]
probably different form #9412 : some hooks work (creating an issue, even in a private repo, for example, works as expected here)

**Comment by 6543** [comment]
still here?

**Comment by x-beaudet** [comment]
> still here?

yep... some news ?

**Comment by 6543** [comment]
no :/

**Comment by 6543** [comment]
@x-beaudet sent fix ...

**Comment by x-beaudet** [comment]
thanx !

**Comment by x-beaudet** [comment]
Works great!
thx a lot !

**Comment by 6543** [comment]
@x-beaudet will be in next 1.11.2 release :)
