### ISSUE TITLE
[Bug] [UI] blue frame missing at `/issue` `/pulls` and `/milestones` 

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#9407]
caused by #9374

blue frame missing at `/issue` `/pulls` and `/milestones`

before:
![67821378-0ddf1f00-fabd-11e9-8a2c-3a07abd8e9ba](https://user-images.githubusercontent.com/24977596/71086626-a418f280-219a-11ea-8c7e-b344bee599ad.png)

now:
![Bildschirmfoto zu 2019-12-18 13-30-23](https://user-images.githubusercontent.com/24977596/71086641-aaa76a00-219a-11ea-99bc-740dcd66c216.png)

**Comment by 6543** [comment]
`box-shadow: 0 0 0 1px #2185d0 inset !important;` fix it if I add it manualy to `<a>` container

**Comment by 6543** [comment]
## Note: I dont wok on it  - so feel free to take it @silverwind, @kolaente (noticed you know JS), others ...

**Comment by kolaente** [comment]
@6543 This should be done using `border` rather than `box-shadow`. Or is there a specific reason to use `box-shadow` instead?

**Comment by 6543** [comment]
I have no idear ... I'm a JS/CSS noob

**Comment by zeripath** [comment]
There's also a spacing issue I've just noticed on the admin pages - UI attached sections seem to be very close to each other
