### ISSUE TITLE
Description of fork doesn't change when description of origin changes, and cannot be changed

### ISSUE THREAD

**Issue by strk** [go-gitea/gitea#9409]
When you fork a repository, the repository that gets created ends up having the same description as the original repository. Later, when changing the original repository description, the forked repository description remains the same, and you cannot change it. This is annoying.

**Comment by lunny** [comment]
So there are two options. One is change the repository description when forked repository changed it's description. Another is to allow owner to change that?

**Comment by strk** [comment]
Sorry, I just realized I was wrong: you can still change a forked repository description. I'm closing this as invalid. It's the second of your options, it works already. Is fine by me.
