### ISSUE TITLE
try.gitea.io shows unrelated issues and pulls from my issues/pulls page.

### ISSUE THREAD

**Issue by kybin** [go-gitea/gitea#941]
- Gitea version (or commit ref): try.gitea.io
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

Related with #931.

It closed via #933 and #935.

But now I see issues and pull requests in my Issues and pulls page (seems like moved from di/issues di/pulls).

Please see below image.

![pulls](https://cloud.githubusercontent.com/assets/595519/22957328/dfc61166-f36a-11e6-8da1-69ad86ed0788.png)

**Comment by lunny** [comment]
Hi, It's duplicated with #931. I have reopened it.
