### ISSUE TITLE
Webhooks not working on private repositories

### ISSUE THREAD

**Issue by theAkito** [go-gitea/gitea#9412]
- Gitea version (or commit ref): 6d811bcb1
- Git version: 2.11.0
- Operating system: DietPi (based on Raspbian)
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant

## Description
Might be related or same issue as in https://github.com/go-gitea/gitea/issues/9403.

I set up Drone CI, which is now approved to work. My first repository was a public one and works as it should. Then I _copied_ its `.drone.yml` to another private repository with only tiny and insignificant changes (this issue has nothing to do with the configuration file!).
Now, the webhook to start the CI process automatically does not work, at all. _Test Delivery_ on the WebUI triggers a hook and then CI starts. CI triggered within Drone itself, works too. Automatic Webhook triggering from the public repository works as well. 

* Automatic Webhook triggering from a private repository does **not** work.
* Upgrading from b84a251fc to 6d811bcb1 did not change anything about this behaviour.
* Issue persists after upgrade from 6d811bcb1 to 665d7e91a.
* Logs don't show any hook by automatic activation. Manually activated hooks show up in logs.

## Reproduce
1. Create a public repository and set up Drone CI on it.
2. Make it work a 100%.
3. Create a private repository and copy the Drone CI setup from above.
4. Automatic hook does not get triggered.
5. Manual hook works.

**Comment by lunny** [comment]
Is a previous gitea work?

**Comment by Akito13** [comment]
@lunny 
I used the CI on b84a251 and 6d811bc . Both versions behave the same way. Did not try other versions.

**Comment by lunny** [comment]
Did you enable drone ci private repository support?

**Comment by Akito13** [comment]
@lunny 

Manual hooks work. If private repository support or anything like that would not be enabled, manual hooks should not work either.

**Comment by Akito13** [comment]
@lunny 

For testing, I copied the `.drone.yml` from the private repository to a different public repository and everything works as expected. Automatic webhook is triggered, CI starts instantly. Doing the same on private repositories does not work. No webhook is triggered by Gitea, unless I trigger it manually over the WebUI.

**Comment by lunny** [comment]
Have you changed the repository type on drone repository setting?

<img width="1020" alt="图片" src="https://user-images.githubusercontent.com/81045/71134870-c2362f80-223a-11ea-8e21-9d3439822518.png">

**Comment by theAkito** [comment]
@lunny

I had it on private. When it did not work after 100 tries, I tried public and internal, too. Nothing worked. Still does not work on private.

**Comment by theAkito** [comment]
@lunny 
Issue persists after upgrade to 665d7e91a.
