### ISSUE TITLE
A new command to list and extract template files

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#9413]
When you want to customize your templates, you have to go to find source and download them. And also the same version. When you are in a stable version, you could find it easy. But for a dev branch, it's not as easy as before.

Since all templates has been embedded in binary, if we can list them and extract them. That's better.

**update**:

Maybe we could extract template files from a gitea sub command like

```
gitea resource list
gitea resource view templates/repo/migrating
gitea resource extract templates/repo/migrating
```

Then it will load the special template file from binary embbed resources to current directory.

**update**:
I rename `template` to `resource` so that we could also view/extract js/css files to inspect purpose.

**Comment by sapk** [comment]
Just for context, I will link the issue where this was discussed: https://github.com/go-gitea/gitea/issues/9320#issuecomment-564517381
