### ISSUE TITLE
Install failed on FreeBSD 11.0

### ISSUE THREAD

**Issue by luftluft** [go-gitea/gitea#942]
- Gitea version (or commit ref):v1.0.1
- Git version:2.11.1
- Operating system: FreeBSD 11.0
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
017/02/15 11:46:53 [T] Custom path: /usr/local/sbin/custom
2017/02/15 11:46:53 [T] Log path: /usr/local/sbin/log
2017/02/15 11:46:53 [I] Gitea v1.0.0+dev
2017/02/15 11:46:53 [I] Log Mode: Console(Trace)
2017/02/15 11:46:53 [I] Cache Service Enabled
2017/02/15 11:46:53 [I] Session Service Enabled
2017/02/15 11:46:53 [I] SQLite3 Supported
2017/02/15 11:46:53 [I] Run Mode: Production
panic: fail to set message file(en-US): open conf/locale/locale_en-US.ini: no such file or directory

goroutine 1 [running]:
panic(0xda0ee0, 0xc4203ac150)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
code.gitea.io/gitea/vendor/github.com/go-macaron/i18n.initLocales(0xc420352df5, 0x0, 0xe8c3c4, 0xb, 0xc42035bc20, 0xe96137, 0x12, 0xc420356160, 0x15, 0x15, ...)
	/wrkdirs/usr/ports/www/gitea/work/src/code.gitea.io/gitea/vendor/github.com/go-macaron/i18n/i18n.go:57 +0x634
code.gitea.io/gitea/vendor/github.com/go-macaron/i18n.I18n(0xc4203323c0, 0x1, 0x1, 0x0, 0xc42035bc20)
	/wrkdirs/usr/ports/www/gitea/work/src/code.gitea.io/gitea/vendor/github.com/go-macaron/i18n/i18n.go:158 +0xf0
code.gitea.io/gitea/cmd.newMacaron(0xc42033e140)
	/wrkdirs/usr/ports/www/gitea/work/src/code.gitea.io/gitea/cmd/web.go:125 +0x628
code.gitea.io/gitea/cmd.runWeb(0xc42033e140, 0x0, 0xc42033e100)
	/wrkdirs/usr/ports/www/gitea/work/src/code.gitea.io/gitea/cmd/web.go:160 +0xaa
code.gitea.io/gitea/vendor/github.com/urfave/cli.HandleAction(0xd87120, 0xf1c688, 0xc42033e140, 0xc420328000, 0x0)
	/wrkdirs/usr/ports/www/gitea/work/src/code.gitea.io/gitea/vendor/github.com/urfave/cli/app.go:471 +0xb9
code.gitea.io/gitea/vendor/github.com/urfave/cli.Command.Run(0xe8086d, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0xe9b256, 0x16, 0x0, ...)
	/wrkdirs/usr/ports/www/gitea/work/src/code.gitea.io/gitea/vendor/github.com/urfave/cli/command.go:191 +0xcc7
code.gitea.io/gitea/vendor/github.com/urfave/cli.(*App).Run(0xc420001520, 0xc42007e060, 0x2, 0x2, 0x0, 0x0)
	/wrkdirs/usr/ports/www/gitea/work/src/code.gitea.io/gitea/vendor/github.com/urfave/cli/app.go:241 +0x6a3
main.main()
	/wrkdirs/usr/ports/www/gitea/work/src/code.gitea.io/gitea/main.go:42 +0x354
...

**Comment by lunny** [comment]
Could you build it yourself?

**Comment by tboerger** [comment]
@fbettag I think you had a similar issue, how have you solved that?

**Comment by fbettag** [comment]
Yes i had exactly the same, lemme check if i documented this.

**Comment by fbettag** [comment]
So to explain what happened to me, i was migrating from gogs and had the exact same issue.

Basically after throwing away my app.ini and just using the app.ini.sample (1.8kb - short version), changing the vars, it started working like a charm.

I know i fiddled around with the rc scripts trying to get it to work from the gogs paths, but in the end i just reinstalled (pkg install -fy gitea) and used the app.ini.sample as base, then it miraculously worked.

Sorry :( Was a Saturday evening and i didn't feel like documenting :/

**Comment by stblassitude** [comment]
I've just submitted [PR 93](https://github.com/go-gitea/docs/pull/93) for the docs page: https://docs.gitea.io/en-us/install-from-package/

Are those explanations helpful?

**Comment by Lechindianer** [comment]
I've got the exact same problem, but unfortunately just reinstalling as @fbettag said doesn't work

**Comment by stblassitude** [comment]
@Lechindianer "just reinstalling" is not how @fbettag solved, if I'm reading his comments correctly. He started with a fresh install, following the example config in `/usr/local/etc/gitea/conf/app.ini.sample`.

Upgrading from Gogs is not something I can help with, I've only ever run Gitea.

**Comment by stblassitude** [comment]
If you've come here from a search, and you're getting this or a similar error message:
```
2017/02/15 11:46:53 [T] Custom path: /usr/local/sbin/custom
2017/02/15 11:46:53 [T] Log path: /usr/local/sbin/log
2017/02/15 11:46:53 [I] Gitea v1.0.0+dev
2017/02/15 11:46:53 [I] Log Mode: Console(Trace)
2017/02/15 11:46:53 [I] Cache Service Enabled
2017/02/15 11:46:53 [I] Session Service Enabled
2017/02/15 11:46:53 [I] SQLite3 Supported
2017/02/15 11:46:53 [I] Run Mode: Production
panic: fail to set message file(en-US): open conf/locale/locale_en-US.ini: no such file or directory
```

and you have installed Gitea from the FreeBSD package, then you need to run Gitea properly. Please familiarise yourself with [the way daemons are run on FreeBSD](https://www.freebsd.org/doc/handbook/configtuning-rcd.html). The proper way to run Gitea from the package is:

1. Enable the service in `/etc/rc.conf` by adding a line `gitea_enable="YES"` to it, or running `sysrc gitea_enable=YES`.
1. Start the service by running `service gitea start`.

Both commands need to be run as root. This is also explained in the [Gitea documentation for installing from a package.](https://docs.gitea.io/en-us/install-from-package/)

If you'd prefer to run `gitea web` from the command line yourself, you need to supply all the necessary environment variables yourself.

@lunny I believe this can be closed.
