### ISSUE TITLE
Cannot edit code comment

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#9439]

**Comment by 6543** [comment]
@lunny do you mean this:
![](https://cdn.discordapp.com/attachments/323701541297192961/657374766453489684/Bildschirmfoto_zu_2019-12-20_01-11-47.png)

affected is try.gitea.io and gitea.com

**Comment by lunny** [comment]
@6543 No. I don't mean the duplicated input box. I mean we should edit the comment ourselves.

**Comment by lunny** [comment]
I think we can close this now.
