### ISSUE TITLE
No warnings when database connection can't be established

### ISSUE THREAD

**Issue by f0x52** [go-gitea/gitea#9445]
- Gitea version (or commit ref): gitea-1.10.1-linux-amd64
- Git version: 2.23.0
- Operating system: Debian Sid
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
Unbeknownst to me, my postgres crashed (probably out of disk space). This caused gitea to return 500 on any request in the web frontend. With no additional info on the gitea STDOUT, I decided to restart gitea.
It started up, gave the usual cli output, just like a normally running gitea process, without any indication that gitea was *failing hard* because it couldn't get a database connection.
This should really be visible error output, or even return the process because it can't start up correctly (it won't even start listening for network)

**Comment by lunny** [comment]
What's the output?

**Comment by bagasme** [comment]
I think Gitea should consider database connection errors as *error*, not warning.

**Comment by zeripath** [comment]
https://github.com/go-gitea/gitea/blob/2de8b27dd1a109e923af7e9026e541539ec054ed/routers/init.go#L57-L78

shows a lot of logging when there is errors...

**Comment by guillep2k** [comment]
@f0x52 maybe you mean to treat it as a _fatal condition_ (i.e. shutdown the instance)? It's common for systems that the database is not yet ready when the instance starts (e.g. slow systems, remote systems), so Gitea performs many connection retries before failing.
