### ISSUE TITLE
Commits to private repositories are ignored in statistics

### ISSUE THREAD

**Issue by theAkito** [go-gitea/gitea#9447]
- Gitea version (or commit ref): 6d811bcb1
- Git version: 2.11.0
- Operating system: DietPi (based on Raspbian)
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant

## Description
Commits to my own private repositories don't show up on the Gitea WebUI Dashboard anymore. They also don't count to the _total contributions in the last 12 months_ table. The Git part works, the commits get applied successfully, but it is not recognized or noticed anywhere in the Gitea WebUI. It's like it did not happen from the perspective of Gitea.

## Screenshots
Hard to deliver screenshots for something that is missing.

**Comment by JAD-SVK** [comment]
- Gitea version (or commit ref): 1.11.0 (Windows x64)
- Git version: 2.25.0
- Operating system: Windows 7 x64
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL): repository: https://try.gitea.io/JAD-SVK/UploadTest dashboard: https://try.gitea.io/
  - [ ] No
  - [ ] Not relevant
- Log gist: in attachment

In the log are missing all "[SQL] UPDATE" and "[SQL] INSERT" lines, that are present in log from previous release version (1.10.3)

## Description

See theAkito description. Seems identical to my case. 

For shared repositories (on another, Windows 10, computer with the same gitea version) the dashboard was updated. Also the issue does not appear on gitea 1.10.3 release version.


## Screenshots

![Clipboard](https://user-images.githubusercontent.com/34906293/74582571-2b79bb00-4fbe-11ea-80c3-be19f5e75b40.png)
[gitea_2020-02-15_06-04-01.zip](https://github.com/go-gitea/gitea/files/4207794/gitea_2020-02-15_06-04-01.zip)

**Comment by theAkito** [comment]
I upgraded my Gitea in the meantime and did some modifications to it as partially explained here: https://github.com/go-gitea/gitea/issues/9183

Don't know how exactly it happened, but the issue is fixed for me. I'll keep it open, in case @JAD-SVK  still experiences it.

**Comment by JAD-SVK** [comment]
I think I know the source of the error now.

I did not apply 'Resynchronize pre-receive, update and post-receive hooks of all repositories.' after upgrading (there was still some 1.9.x version, probably 1.9.6).

I downgraded the version and tested it now (after reading the description) with the new release version.

Thanks for the info.

**Comment by theAkito** [comment]
@JAD-SVK 

Good to know you managed to solve the issue, easily.

I consider this closed, then.
