### ISSUE TITLE
Explore repositories at try.gitea.io

### ISSUE THREAD

**Issue by ea2973929** [go-gitea/gitea#945]
- Gitea version (or commit ref): try.gitea.io
- Operating system: Windows 7
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes (provide example URL) https://try.gitea.io/explore/repos

## Description
**How to reproduce**
1. Surf to https://try.gitea.io/explore/repos (I tried chrome and IE)

**Expected**
2. Some sort of demo page of gitea with repositories

**Actual**
2. Text error message: template: explore/repo_list:5:200: executing "explore/repo_list" at <.Owner.Name>: can't evaluate field Name in type *models.User

Extra comment: "Because first impressions last"

**Comment by arkraft** [comment]
I tried to reproduce it, but it worked fine for me. I was logged in at the time. After reading the **models.User** i logged out and tried it again, then this error appeared. So i think you try to show something only the logged in user has and this is why it fails.

**Comment by ea2973929** [comment]
Yes, that might very well be the problem. But this is try.gitea.io, where people go to test your software - should it really be a requirement to create a user for that? For comparison https://try.gogs.io/explore/repos works fine without a user. 

If you want to require a user you should clearly write some message about this so that a new user knows what to do. Another approach might be to create a demo user for people to use.

**Comment by arkraft** [comment]
I am totally with you on this one. I also think it should work without an account for public projects. All i wanted was to add some more info to the issue as it could help find the problem faster. Sorry if that was not clear enough.

**Comment by Bwko** [comment]
@ea2973929 Unfortunately #940 introduced this bug, @appleboy could you take a look at this?

**Comment by tboerger** [comment]
Yep, confirmed that `template: explore/repo_list:5:200: executing "explore/repo_list" at <.Owner.Name>: can't evaluate field Name in type *models.User` pops up if you try to explore as an anoymous user. Works if you are logged in,

**Comment by xsteadfastx** [comment]
same for me on my installation.

**Comment by lunny** [comment]
@ea2973929 @arkraft @xsteadfastx please confirm this has been fixed via #946

**Comment by ea2973929** [comment]
Works for me. I'm not sure what process you have around this. Should I close it as the creator of the issue?

**Comment by lunny** [comment]
Please close this.
