### ISSUE TITLE
can't push local repo to remote

### ISSUE THREAD

**Issue by iwzoo** [go-gitea/gitea#9461]
- Gitea version (or commit ref):
1.11.0+dev-352-g66028d58f built with GNU Make 4.2.1, go1.13.4 : bindata, sqlite, sqlite_unlock_notify
- Git version: 2.22.0
- Operating system: Debian, Docker
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

1. Create new repo in Gitea
2. Create local repo, and run 
```
git init
touch readme.md
git add readme.md
git commit -m "initial commit"
git remote add origin repo_url
git push -u origin master
```
3. remote repo keeps empty. nothing pushed. 
...

**Comment by zeripath** [comment]
We need some more information I'm afraid.

What version of Gitea?

Do you get any logs in Gitea when you push?

It looks like you're pushing over http is that correct?

Are your Gitea repositories mounted on an executable partition? If they are mounted noexec or user then I'm afraid that won't work as Gitea is informed by git hooks about pushes.

**Comment by iwzoo** [comment]
> We need some more information I'm afraid.
> 
> What version of Gitea?
> 
> Do you get any logs in Gitea when you push?
> 
> It looks like you're pushing over http is that correct?
> 
> Are your Gitea repositories mounted on an executable partition? If they are mounted noexec or user then I'm afraid that won't work as Gitea is informed by git hooks about pushes.

Gitea: 1.11.0+dev-352-g66028d58f built with GNU Make 4.2.1, go1.13.4 : bindata, sqlite, sqlite_unlock_notify

Yes, I'm using http for pushing. 

Do you mean the the mount of /data should be executable (without nonexec option)?

**Comment by zeripath** [comment]
Yes, exactly that.

**Comment by iwzoo** [comment]
is there any chance or plan to make it working on noexec partition?

**Comment by lunny** [comment]
@iwzoo I think it can't. Hooks scripts need execute permission.

**Comment by zeripath** [comment]
So there is actuallly a potential technique with setting the GIT_HOOK_DIR environment variable. However I just don't have time to do it as yet and it's potentially a little fiddly as we would have to deal with other hooks etc.
