### ISSUE TITLE
Unable to close issue

### ISSUE THREAD

**Issue by aggarwaldev** [go-gitea/gitea#9467]
- Gitea version (or commit ref): 1.10.1 
- Git version: 2.22.0
- Operating system: Ubuntu (Linux)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (https://try.gitea.io/aggarwal.dev/sample/issues/1) 
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
When using an Issue template with check box (like the one above), I'm unable to close issue and unable to set Label.
...

## Screenshots
![Screenshot_2019-12-23 Refactor](https://user-images.githubusercontent.com/22045791/71326835-5e578380-2526-11ea-9fa7-36a8abf2179d.png)

## Comments
I guess it's a problem with dropzone.js 
Here's what console looks like:
```
downloadable font: OS/2: Bad sTypoLineGap, setting it to 0: -32 (font-family: "Dropdown" style:normal weight:400 stretch:100 src index:0) source: data:application/x-font-ttf;charset=utf-8;base64,AAEAAAALAIAAAwAwT1MvMggjB5AAAAC8AAAAYGNtYXAPfuIIAAABHAAAAExnYXNwAAAAEAAAAWgAAAA … AG0AbwBvAG4ARgBvAG4AdAAgAGcAZQBuAGUAcgBhAHQAZQBkACAAYgB5ACAASQBjAG8ATQBvAG8AbgAuAAAAAAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA= unknown:300:30915
JQMIGRATE: Migrate is installed, version 3.0.1 jquery-migrate.min.js:33:19
Tribute was already bound to TEXTAREA tribute.min.js:1:3479
Error: No URL provided. dropzone.js:439:15
jQuery.Deferred exception: Dropzone is not defined @https://try.gitea.io/js/index.js?v=3734fe86ac738d6b4793aa29527ce5b8:1:99673
e@https://try.gitea.io/vendor/plugins/jquery/jquery.min.js?v=3.4.1:2:29453
l/</t<@https://try.gitea.io/vendor/plugins/jquery/jquery.min.js?v=3.4.1:2:29755
 undefined jquery.min.js:2:31008
ReferenceError: Dropzone is not defined index.js:2378:4
Source map error: Error: request failed with status 404
Resource URL: https://try.gitea.io/vendor/plugins/tribute/tribute.min.js
Source Map URL: tribute.min.js.map
```

**Comment by bagasme** [comment]
Can you reproduce this issue without issue template?

**Comment by aggarwaldev** [comment]
No. It works fine without issue template. I think it's because of the tick boxes.

**Comment by lunny** [comment]
@aggarwaldev try site is a master version not v1.10.1.

**Comment by zeripath** [comment]
<a id="dropzone">Does this set an id?</a>

**Comment by zeripath** [comment]
but I wanted to link to <a href='#dropzone'>Does this set an id?</a>

**Comment by zeripath** [comment]
<a id="some-id">This some-id</a>

<a href="#some-id">this should link to some-id</a>

<a href="#user-content-some-id">this should link to some-id</a>

<a id="user-content-some-id">Let's see what you do here</a>

**Comment by jolheiser** [comment]
For the record, the tests above are because this issue actually comes from header IDs.  
The OP issue has `### module` which is given an auto-ID of `module` which is then giving `dropzone.js` a problem.  

https://stackoverflow.com/a/3434388
https://github.com/go-gitea/gitea/blob/master/public/vendor/plugins/dropzone/dropzone.js#L1619-L1623
