### ISSUE TITLE
Memory OOM during build

### ISSUE THREAD

**Issue by mxvin** [go-gitea/gitea#9469]
Hi, I got problem while build from source:

- Gitea version (or commit ref): All tags/version
- Operating system: Debian 8 Kernel  2.6.32
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:
 ```
~/go/src/code.gitea.io/gitea$ TAGS="bindata sqlite sqlite_unlock_notify" make build
GO111MODULE=on go build -mod=vendor -p=1 -v  -tags 'bindata sqlite sqlite_unlock_notify' -ldflags '-s -w  -X "main.MakeVersion=GNU Make 4.0" -X "main.Version=1.10.1" -X "main.Tags=bindata sqlite sqlite_unlock_notify"' -o gitea
code.gitea.io/gitea/modules/public
go build code.gitea.io/gitea/modules/public: /usr/lib/go/pkg/tool/linux_amd64/compile: signal: killed
Makefile:357: recipe for target 'gitea' failed
make: *** [gitea] Error 1

// dmesg
[26353183.187031] Out of memory in UB 6518: OOM killed process 4443 (compile) score 0 vm:801692kB, rss:717012kB, swap:0kB
```

## Description
I realized this might be memory related problem. Because I see "/usr/lib/go/pkg/tool/linux_amd64/compile" process memory ramp up until OOM is triggered.
My machine has 1 GB ram, it's a VPS. But how much memory gitea need for build to be success? I think this kind of info must be mentioned on documentation.
And, is there any solution that can limit memory usage, so it still possible to compile code on limited memory environment?

Thanks!

**Comment by zeripath** [comment]
Try building without bindata?

**Comment by Andersbiha** [comment]
Try mounting a swap partition before compilation.

On my low memory devices i usually mount a 2GB swap partition in addition to the 1GB onboard memory. I haven't tested to exact consumption so you might be able to compile it with less.

**Comment by lunny** [comment]
What's your golang version?

**Comment by mxvin** [comment]
Hi, 
Thanks for all that replied to this post, I think I just confuse, as the documentation mentioning usage of 'bindata' on the build flag, I think that's mandatory.

Making swap is not possible on current machine as it runs OVZ virtualization that limit some system level execution.
And Yes, to resolve this issue, just build without bindata, omit that flag if you dealing with limited memory, and that's it. 

Next, I issue this command according to .drone.yml: (I think documentation need a direction for building without bindata)
```
make clean
make js
make css
TAGS="sqlite sqlite_unlock_notify" make build
```
The gitea binary just appear on source code folder and run without any problem.

I still have a question. Is that okay on the production instance, that we run compiled binary placed in the same source code folder we've been build? I tried to move binary + vendor, public folder but it doesn't not work as binary expect all of resource folder to be on source code folder.

Thank you!

**Comment by lunny** [comment]
@mxvin Before Gitea v1.11 that's work. But when Gitea v1.11 `make build` means `make generate build` on v1.10 or before. Except you know more detail about gitea build, otherwise it's a bit complicated to compile without embedded resouces.

With or withoud embedded resouces, Gitea will both work. You should copy `public`, `templates`, `options` the three folders with Gitea binary.
