### ISSUE TITLE
[Feature Request] taking notes

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#9475]
Many times I have a good idea or something I want to do in mind when I am working on an issue and writing a long text. I can choose between being sidetracked and creating new issues or forgetting it or opening a different application maybe using paper and pen to write down my notes. On github I really miss being able to write down a few words and work on it later. I am not sure if Gitea already contains this feature, I checked the documentation and the issues and found nothing, so probably not. I am not sure if anybody else is missing this feature, I guess the votes will decide. What do you think?

**Comment by mrsdizzie** [comment]
You mean the gist feature? If so there is already an (old) issue for that #693

**Comment by inf3rno** [comment]
@mrsdizzie No, as far as I understand the gist is for sending code. This one would be only for writing down a few words and continue work without major interruption and check it again later. Maybe it is similar to a todo list, but it isn't entirely that. The notes can be repo related or something totally unrelated, for example I realize that I need to buy eggs when I am working on a project, reading an issue or writing a long answer. I take a note something like "eggs" and continue doing my work. Ofc. I can do this on paper or in notepad too. Doing it in a webapplication have the advantage of moving that info between computers and that I don't have to take paper and pen or open a new application, which is further distraction. Usually I have more creative thoughts than buying eggs, and I work on many different projects, so sometimes I get a new idea about project A and B, when I am working on project C, and if I don't write it down I forget it, but if I start to create feature issues for it and think it through, then I won't work on project C any longer. Maybe it is just me, but I struggle to focus on a single project and this would help me.

**Comment by 6543** [comment]
I would say you want two things:
* draft issues
* a simole way to create them while working on a issue

?

**Comment by lunny** [comment]
@inf3rno I'm using `private repository` + `Typora` to do that.

**Comment by inf3rno** [comment]
> 
> 
> I would say you want two things:
> 
>     * draft issues
> 
>     * and a simple way to create them while working on a issue
> 
> 
> ?

No, it is less than a draft. It is just a small note to remember what to do next after I finished working on the actual issue. Something like a short todo list for that day.

**Comment by inf3rno** [comment]
> 
> 
> @inf3rno I'm using `private repository` + `Typora` to do that.

Thanks, I'll check this typora.
