### ISSUE TITLE
add/remove issue dependency failing

### ISSUE THREAD

**Issue by bhalbright** [go-gitea/gitea#9483]
Adding or removing a dependency in the gitea user interface is failing, user gets an error 500 and the dependency is not added or removed.

- Gitea version (or commit ref): 30181d459da79ef57c58bb3789e2ce7130d08b77
- Git version:  version 2.19.1.windows.1
- Operating system: Windows 10
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:
2019/12/23 22:36:18 ...les/context/panic.go:35:1() [E] PANIC:: runtime error: invalid memory address or nil pointer dereference
	E:/Go/src/runtime/panic.go:82 (0x444f55)
		panicmem: panic(memoryError)
	E:/Go/src/runtime/signal_windows.go:233 (0x444df0)
		sigpanic: panicmem()
	E:/dev/Go/src/code.gitea.io/gitea/models/repo.go:537 (0xdd6752)
		(*Repository).getOwnerName: if len(repo.OwnerName) > 0 {
	E:/dev/Go/src/code.gitea.io/gitea/models/repo.go:563 (0xdd6a59)
		(*Repository).mustOwnerName: if err := repo.getOwnerName(e); err != nil {
	E:/dev/Go/src/code.gitea.io/gitea/models/repo.go:260 (0xd6b5ad)
		(*Repository).MustOwnerName: return repo.mustOwnerName(x)
	E:/dev/Go/src/code.gitea.io/gitea/models/repo.go:265 (0xd6b58c)
		(*Repository).FullName: return repo.MustOwnerName() + "/" + repo.Name
	E:/dev/Go/src/code.gitea.io/gitea/models/repo.go:270 (0xd6b58b)
		(*Repository).HTMLURL: return setting.AppURL + repo.FullName()
	E:/dev/Go/src/code.gitea.io/gitea/models/issue.go:325 (0xd6b58a)
		(*Issue).HTMLURL: return fmt.Sprintf("%s/%s/%d", issue.Repo.HTMLURL(), path, issue.Index)
	E:/dev/Go/src/code.gitea.io/gitea/routers/repo/issue_dependency.go:33 (0x131c655)
		AddDependency: defer ctx.Redirect(issue.HTMLURL(), http.StatusSeeOther)

## Description
You get an error 500 from an issue page when you try to either add or remove a dependency

**Comment by 6543** [comment]
does #9484 close this? - then this need to be closed
