### ISSUE TITLE
Backspace not working in new SimpleMDE on Issue/Commment

### ISSUE THREAD

**Issue by bobemoe** [go-gitea/gitea#9493]
- Gitea version (or commit ref): 1.11.0+dev-494-gf88715e29
- Can you reproduce the bug at https://try.gitea.io: Yes

## Description

When editing an issue body or comment the backspace key will not work to delete characters once the caret has been moved with arrow keys or mouse click.

Typing new characters works and the new characters can be deleted all the way back to where the last caret position was but then it will not delete further back.

Shift+backspace works though!

Tried in Firefox and Chrome.

**Comment by bagasme** [comment]
@lunny Did you mean selecting the caret cause this bug?

**Comment by zeripath** [comment]
I can confirm this.

The troublesome line is:

https://github.com/go-gitea/gitea/blob/d59536c222857713d95846d77903282afe608f23/web_src/js/index.js#L1493

I'm not sure what the trigger is there for, but deleting that line makes deletion work again.

**Comment by zeripath** [comment]
@blueworrybear what was the purpose of that line?
