### ISSUE TITLE
Gitea makes update hooks but doesn't use them

### ISSUE THREAD

**Issue by zeripath** [go-gitea/gitea#9495]
- Gitea version (or commit ref): master

## Description

https://github.com/go-gitea/gitea/blob/3e166bd0550eceade275023616a02a8bf12d58c9/models/repo.go#L979

creates update hooks however gitea does not use this hook and the equivalent hook is essentially empty except for reading the settings file.

This would be of little consequence, except update is run for every reference and this means the settings are read for every reference! This means that pushes that involve a large number of references are unnecessarily slowed.

**Comment by zeripath** [comment]
I'm gonna reopen this because #9496 doesn't actually remove these hooks anymore.

**Comment by lunny** [comment]
OKay. I think it's clear as @lafriks said https://github.com/go-gitea/gitea/pull/9496#issuecomment-569283556.

`pre_receive` hook will be invoked before any objects stored on git repository.
`update` hook will be invoked after that but before change the branch/tag to that new refs.

Currently, we just need to use `pre_receive` to protect branches and `post_receive` to update something.

**Comment by zeripath** [comment]
Almost everything that can be done in an update hook can be done at pre-receive - the only things being different are that pre-receive cannot make references whereas it appears that update can. Despite its name pre-receive is called after the packs have been received and are present on the server in the quarantine directory.

Update hooks have to run once per received reference this makes them a rather expensive hook especially for migrations where many references could be updated at once. 

Therefore apart from that slight difference which could easily be done at post-receive I do not believe that there could ever be a reason for having a gitea update hook and therefore I believe we should simply remove it.

I would even go further and state that we should not support update hooks. Their only power above that of pre-receive is to do something that would lead to gitea not knowing about branches in its own repository.

**Comment by zeripath** [comment]
For reference looking at the Git source code:

You'd think that pre-receive is run before the packs are uploaded... but that's not what the documentation implies nor what this code does:

https://github.com/git/git/blob/0a76bd7381ec0dbb7c43776eb6d1ac906bca29e6/builtin/receive-pack.c#L1459-L1531

pre-receive is called at 

https://github.com/git/git/blob/0a76bd7381ec0dbb7c43776eb6d1ac906bca29e6/builtin/receive-pack.c#L1498

The packs are received at:

https://github.com/git/git/blob/0a76bd7381ec0dbb7c43776eb6d1ac906bca29e6/builtin/receive-pack.c#L2000

which is in the function that calls `execute_commands` and eventually the `pre-receive` hooks.

**Comment by lunny** [comment]
@zeripath see the comments on https://github.com/git/git/blob/0a76bd7381ec0dbb7c43776eb6d1ac906bca29e6/builtin/receive-pack.c#L1506-L1517 . The packs uploaded on temp directory before pre-received hook.

**Comment by zeripath** [comment]
Yes. The directories are specified as GIT_QUARANTINE_PATH.

All of the objects are on the server already and can be queried with an appropriate look up in the quarantine dir and the alternative dir as appropriate. 

We do this already in the pre-receive hook:

https://github.com/go-gitea/gitea/blob/145c1ea0b6b1f79eff047041853378319117fd39/routers/private/hook.go#L65-L78

We will never need a update hook.
