### ISSUE TITLE
[Feature Request] A redirect link to the repository's latest release/tag

### ISSUE THREAD

**Issue by ankurash** [go-gitea/gitea#9505]
- Gitea version (or commit ref): 1.10.1
- Git version: 2.17.1
- Operating system: Ubuntu 18.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
Github has a redirect link to the latest release in a repository. For example, on go-gitea/gitea repo, 
https://github.com/go-gitea/gitea/releases/latest redirects to the latest tag (https://github.com/go-gitea/gitea/releases/tag/v1.10.1 as on this date).
This helps in checking and getting the latest release from a repository hosted on a gitea server, manually or using dedicated scripts.

**Comment by jamesstout** [comment]
I think this was done by 4f597b1866954ff94999a52af1a41fed06f0143e.

I'm trying to add it to the API too.

**Comment by jolheiser** [comment]
@jamesstout Yes it was, thanks for the catch!
Fixed in #11102
