### ISSUE TITLE
time tracking

### ISSUE THREAD

**Issue by fangxin810425** [go-gitea/gitea#9508]
- Gitea version (or commit ref):1.10.0-windows-4.0-amd64 
- Git version: 2.24.1, Wire Protocol Version 2 Enabled
- Operating system:window 10
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
   It is configured as HTTPS. Click the start button under time tracking in the work order to open the HTTP link, causing the page to fail to open.
...

**Comment by bagasme** [comment]
The link you mention returned 404 or 500?

**Comment by fangxin810425** [comment]
400 Bad Request

**Comment by 6543** [comment]
@fangxin810425 wich url/link ?! - is it about UI or API? ...

**Comment by lunny** [comment]
Have you tries 1.10.1 ?

**Comment by fangxin810425** [comment]
Sorry, it should be a configuration problem. Thank @bagasme @6543 @lunny @zacheryph .
PROTOCOL		= https
ROOT_URL           = http://xxxxxxx

**Comment by 6543** [comment]
@fangxin810425 if you need config help you can ask on discord: https://discord.gg/NsatcWJ
