### ISSUE TITLE
Testmail function won't work with Sendmail config

### ISSUE THREAD

**Issue by Thorsten2k3** [go-gitea/gitea#951]
- Gitea version (or commit ref): 1.0.1 
- Git version: 2.7.4
- Operating system:  Ubuntu 16.04.2 LTS
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
Sending a Testmail won't work with a sendmail config. It reports an issue with the host-address, that's it.
I did some diging my self and it looks like the test-email function use 'gomail.send' instead of 'mailer.send'. 
I can barely read Go, but i guess thats a mishab?

See 'models/mail.go:43'

**Comment by plessbd** [comment]
test mail works for me.  What is your configuration?
You have to specify the host and port
```
[mailer]
ENABLED = true
HOST    = localhost:25
FROM    = "Gitea Instance" <gitea@domain.com>
USER    =
PASSWD  =
```

**Comment by Thorsten2k3** [comment]
My config (minus all comments ect.)

[mailer]
ENABLED                     = true
SUBJECT                     = %(APP_NAME)s
FROM                           = XXX Gitea <gitea@xxx>
USE_SENDMAIL         = true
SENDMAIL_PATH       = /usr/sbin/sendmail

And _echo "Subject: test"| sendmail_ from cmd works.

**Comment by plessbd** [comment]
can you turn up the log level (generally I use TRACE for debugging) and see if there is any extra information in the logs?

**Comment by Thorsten2k3** [comment]
well, not too much to see there:
```
2017/02/15 21:14:33 [T] Custom path: /opt/gitea/bin/custom
2017/02/15 21:14:33 [T] Log path: /var/log/gitea/
2017/02/15 21:14:33 [I] Gitea v1.0.1
2017/02/15 21:14:33 [I] Log Mode: File(Info)
2017/02/15 21:14:33 [I] Cache Service Enabled
2017/02/15 21:14:33 [I] Session Service Enabled
2017/02/15 21:14:33 [I] Mail Service Enabled
2017/02/15 21:14:33 [I] Git Version: 2.7.4
2017/02/15 21:14:33 [I] SQLite3 Supported
2017/02/15 21:14:33 [I] Run Mode: Production
2017/02/15 21:14:33 [T] Doing: CheckRepoStats
2017/02/15 21:14:33 [I] Listen: http://127.0.0.1:3000/gitea
[Macaron] 2017-02-15 21:14:37: Started GET /admin/config for XXX
2017/02/15 21:14:37 [D] Session ID: XXX
2017/02/15 21:14:37 [D] CSRF Token: XXX
[Macaron] 2017-02-15 21:14:37: Completed /admin/config 200 OK in 15.143061ms
2017/02/15 21:14:37 [D] Template: admin/config
[Macaron] 2017-02-15 21:14:43: Started POST /admin/config/test_mail for XXX
2017/02/15 21:14:43 [D] Session ID: XXX
2017/02/15 21:14:43 [D] CSRF Token: XXX
2017/02/15 21:14:43 [T] NewMessageFrom (htmlBody):
Gitea Test Email!
[Macaron] 2017-02-15 21:14:43: Completed /admin/config/test_mail 302 Found in 6.966764ms
[Macaron] 2017-02-15 21:14:43: Started GET /admin/config for XXX
2017/02/15 21:14:43 [D] Session ID: XXX
2017/02/15 21:14:43 [D] CSRF Token: XXX
[Macaron] 2017-02-15 21:14:43: Completed /admin/config 200 OK in 10.678767ms
2017/02/15 21:14:43 [D] Template: admin/config
```
UI says:
`Fail to send test email to 'XXX@XXX': gomail: could not send email 1: dial tcp [::1]:587: getsockopt: connection refused`

I tried file as console, both logs turn out the same. (Yes it says File(Info), but File(Trace) is the same and i turned console log to trace as well, no change)

P.S. Well the code doesn't seem to log the error, all we get is what the ui says see https://github.com/go-gitea/gitea/blob/master/routers/admin/admin.go#L179

**Comment by lunny** [comment]
It seems your smtp server cannot be visited?

**Comment by Thorsten2k3** [comment]
There is no smtp server. It's a sendmail config and the MTA of the Server should handle it. 

I guess the sendmail config gets ignored by the Testmail function.
See in https://github.com/go-gitea/gitea/blob/master/models/mail.go#L43 
The 'mailer.Sender' part should tell the whole thing, as far i understand now, to use 'Sendmail' but seems to not.

**Comment by lunny** [comment]
Yes. I see. Could you send a PR to fix that?

**Comment by lunny** [comment]
`mailer.Sender` is an interface. The code looks great. You can see at https://github.com/go-gitea/gitea/blob/master/modules/mailer/mailer.go#L200 . I have no idea. @couling maybe you can give some idea?

**Comment by couling** [comment]
Hey folks. I've had to take some time away for personal reasons but I may get chance to investigate this on the weekend.

The code uses `send mail -F gite@example.com -i` 
See line 209

@thorston2k3 could you you double check your send mail accepts these args. Also make sure there is a valid To: address in the recipient field.

Can you confirm that you are sending to valid email addresses (user@domain) and not just host users. (Without the @domain)

**Comment by Thorsten2k3** [comment]
`sendmail -F gitea@example.com -i my.email@addressl.com` works fine, mail gets to my account as it should.
MTA is an exim4 ( lrwxrwxrwx 1 root root 5 Jan  5 15:50 /usr/sbin/sendmail -> exim4 )
I just got the dev env running, in case i find the error my self i'll report and present a PR.

**Comment by lunny** [comment]
@Thorsten2k3 any update? Maybe we could move this to v1.2?

**Comment by Thorsten2k3** [comment]
hadn't got the time to look in to it yet. if it boils down to me doing the work i don't mind moving it to 1.2

**Comment by lunny** [comment]
It seems this has been fixed some time by some PR. Please feel free to reopen it.
