### ISSUE TITLE
Redirect on changing user and organization name

### ISSUE THREAD

**Issue by kasbah** [go-gitea/gitea#9531]
Currently gitea redirects repository URLs when you change the repository name (implemented in https://github.com/go-gitea/gitea/pull/807), but if you change a username or organization name then gitea won't redirect. 

I am just wondering if there is interest in having redirects on username and organization name change implemented as well.

**Comment by lafriks** [comment]
That is tricky one as somebody can create org or user with old name so it would not be consistent and could lead to potential problems

**Comment by kasbah** [comment]
There is a similar problem for just changing repository names that was already solved in #807 I believe. The solution is to not redirect when a new org/user takes the old name. This is also [how Github does it](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/changing-your-github-username#repository-references).

> If the new owner of your old username creates a repository with the same name as your repository, that will override the redirect entry and your redirect will stop working.

**Comment by lunny** [comment]
@lafriks What's the problems? But we have implemented the redirects when you change repository name.

**Comment by lafriks** [comment]
No problem, could be some risks but I'm fine if someone sends PR for this
