### ISSUE TITLE
PullRequest "squash and merge" issue

### ISSUE THREAD

**Issue by MarcelHillmann** [go-gitea/gitea#9540]
- Gitea version (or commit ref): 1.11.0+dev-482-g2f9564f99
- Git version:
- Operating system: windows / linux 
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL) https://try.gitea.io/MarcelHillmann/testSquashAndMerge/pulls/2
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
1. I pushed some commits to develop
1. then a PR to master, and accept with "sqash and merge"
1. no adding an additonal commit to develop
1. again a PR to master, and the hole proccess is broken
   there are a bounch of merge conflict

## Screenshots
![image](https://user-images.githubusercontent.com/7380756/71560071-761e9280-2a65-11ea-8e5b-b85b8f415927.png)

**Comment by davidsvantesson** [comment]
Your HEAD is pointing at branch _develop_. Did you change the default branch? Other than that I don't find anything strange in your repository and what you describe.
The merge conflict is not strange, you squash merged your changes and then applied new changes directly adjecent to previous changes. Git will give merge conflicts for this diff.
In general, and specifically if _squash merge_ is used, it is a good practice to delete the PR branch after it has been merged.

**Comment by MarcelHillmann** [comment]
Hi davidsvantesson,

OK, that maks sence. 
How can I fix the merge conflict via Gitea?

At moment all following PR are conflicted, and I didn't know an solution to solve the merge conflict.

Thanks
Marcel

**Comment by davidsvantesson** [comment]
The normal workflow is to delete the branch after it has been merged and create a new branch for new changes. For squash merge this is more important because the merge will not create a reference to your branch (it is not really a merge, rather a "squash and apply"). 

If you already have changes on top of your merged branches, I would recommend to create a new branch on top of master, then cherry pick the range of new commits after the merge.
https://stackoverflow.com/a/1994491

**Comment by 6543** [comment]
@MarcelHillmann i think you mean this feature #9014 ?

**Comment by davidsvantesson** [comment]
I don't think you want to solve this merge conflict in the UI.
You can try `git merge -X theirs master`, but I don't that is the recommended way.

**Comment by MarcelHillmann** [comment]
Hi 6543,

yea, that is a goo solution.

@davidsvantesson 

Thanks for you advice.

Thanks
Marcel
