### ISSUE TITLE
[Feature Request] Allow GET comments reactions without token via API

### ISSUE THREAD

**Issue by meteorlxy** [go-gitea/gitea#9543]
## Description

Related to #9220

Currently, we can:

- GET issues: https://gitea.com/api/v1/repos/meteorlxy/vssue-test/issues?q=[Vssue]Vssue+Dev
- GET comments: https://gitea.com/api/v1/repos/meteorlxy/vssue-test/issues/1/comments

But we can't GET reactions if we don't pass token (get 401):

- GET reactions: https://gitea.com/api/v1/repos/meteorlxy/vssue-test/issues/comments/104283/reactions

Hope the behavior of reactions API can be consistent with the former two APIs.

cc @6543

**Comment by 6543** [comment]
I'll have a look at it ..
PS: reaction_summary might be helpfull but dont know when this get finished: #9497
