### ISSUE TITLE
[Bug Report] Reactions API throws 500 for duplicate reaction

### ISSUE THREAD

**Issue by meteorlxy** [go-gitea/gitea#9544]
## Description

If we post a same reaction more than one time via reaction API, it will throw 500.

https://gitea.com/api/swagger#/issue/issuePostCommentReaction

`POST /repos/{owner}/{repo}/issues/comments/{id}/reactions`

FYI, GitHub returns `201` for created, and returns `200` for duplicated

cc @6543 

## Screenshots

**First Time (OK)**

![image](https://user-images.githubusercontent.com/18205362/71576329-4043e180-2b2b-11ea-9d4f-4e3d6152c628.png)

**Second Time (ERROR)**

![image](https://user-images.githubusercontent.com/18205362/71576326-37eba680-2b2b-11ea-813b-e967b365e119.png)

![image](https://user-images.githubusercontent.com/18205362/71576170-9fedbd00-2b2a-11ea-95f6-19332cbc502b.png)

**Comment by 6543** [comment]
The Api works as intended (500 is xorm error ...)

I could change this ...

**Comment by meteorlxy** [comment]
Yes, a `5xx` code means things do not work as expected
