### ISSUE TITLE
Detect and show force pushes in PR

### ISSUE THREAD

**Issue by jolheiser** [go-gitea/gitea#9549]
Similar to GH, a pull request should show when its branch has been force-pushed to.  
This is handy/relevant information to know, and might even help determine otherwise confusing behavior.

**Comment by bagasme** [comment]
@jolheiser What about the implementation?

**Comment by zeripath** [comment]
We need another comment type.

The detection code would go in to:

https://github.com/go-gitea/gitea/blob/4acca9d2e8618a5283495fcd3b313fd53c953f18/services/pull/pull.go#L217

Or could go in to the pre-receive hook...  (Actually instead we should probably prevent direct update of refs/pull paths in pre-receive...)

**Comment by TGotwig** [comment]
Would be a really awesome feature! I miss it a lot 😬

**Comment by 6543** [comment]
did #11167 fix this issue?

**Comment by lafriks** [comment]
Should be fixed by #11167, please reopen if it's not
