### ISSUE TITLE
Manual-merge check will close and mark merged PRs that are reset to master

### ISSUE THREAD

**Issue by guillep2k** [go-gitea/gitea#9551]
Gitea Version: 1.11.0+dev-497-gc0f879546 c0f879546

If a PR's branch is reset to the content of the base repo's master, the PR will be closed and marked as merged by the manual-merge detection routine. This at least seems to be what's happened to https://gitea.com/gitea/go-sdk/pulls/203 (which incidentally was created from a `master` branch).

**Comment by 6543** [comment]
[code ref](https://github.com/go-gitea/gitea/blob/d59536c222857713d95846d77903282afe608f23/services/pull/check.go#L120)

**Comment by zeripath** [comment]
I guess if we just change these two lines to be Closed instead:

https://github.com/go-gitea/gitea/blob/b983ff447387d40700ad8c0a56f90052878fec98/services/pull/check.go#L156-L158

**Comment by zeripath** [comment]
https://github.com/go-gitea/gitea/blob/b983ff447387d40700ad8c0a56f90052878fec98/services/pull/check.go#L142-L146 

and these too.

**Comment by guillep2k** [comment]
But is it correct to close the PR? It can't be merged anymore, but the PR itself could receive further commits that change that.

**Comment by lunny** [comment]
It should be marked as merged but not closed if it's correct. But that's not the issue. 

In fact the detection if it has been merged is not right I think.

**Comment by zeripath** [comment]
It's actually quite difficult - by the time ManualMerge is called we've lost the previous SHA.

In Pushtobaserepo we have both and can do the check but there's no state we can choose which says don't mark as merged

**Comment by lunny** [comment]
So maybe we should disable that currently to avoid making confuse.

**Comment by zeripath** [comment]
Fixed by #12543
