### ISSUE TITLE
Add support for external renders for code blocks

### ISSUE THREAD

**Issue by davidsvantesson** [go-gitea/gitea#9553]
Just as you can specify an external render for a specific file, it would be cool to have an external render for a specific code block. This should be handled backend and the data feed to the external script would be the content of the code block instead of a complete file. 

Code highligtning is currently handled frontend by javascript. Placing the external tool support in the backend would allow more possibilities on what is possible to do as it is not requiring javascript. 
It could be an option whether the output shall still be in a code block. 

A specific use case for this is plantuml (#3902). So with below code block everything from (including) @startuml to @enduml would be sent to the script that can generate a html code with an inline image of the uml.

\```plantuml
@startuml
Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response

Alice -> Bob: Another authentication Request
Alice <-- Bob: Another authentication Response
@enduml
\````

**Comment by zeripath** [comment]
So goldmark has a chroma extension which behaves exactly like that

**Comment by silverwind** [comment]
Related: https://github.com/go-gitea/gitea/issues/7729

**Comment by zeripath** [comment]
So the way to do this might be to add js that detects a language class and then sends it back to the server or even just renders it á la Mermaid.js

**Comment by davidsvantesson** [comment]
Should be possible to do something similar for plantuml (with a plantuml server). Although the code is not fully completed, it seem to be only minor adaptions required:
https://plantuml.com/code-javascript-synchronous

I don't have time right now, but I will try to do something with it later.

**Comment by silverwind** [comment]
> detects a language class and then sends it back to the server 

I'd advice against it. We should just use server-side highlighting. highlight.js detection is very inaccurate and it would essentially be a useless round trip if we can already detect it server-side.

**Comment by davidsvantesson** [comment]
Hmm... ok let's discuss in #9894. 😕

**Comment by davidsvantesson** [comment]
We have two examples for javascript based rendering now (PlantUML and mermaid). Server-side external rendering is only relevant if #7729 is implemented. Maybe it is enough to track in that one and close this one for now?

**Comment by lunny** [comment]
> So goldmark has a chroma extension which behaves exactly like that

Maybe we could enable it now since #12047 merged.

**Comment by nfisher1226** [comment]
[github](https://github.com/github/roadmap/issues/372) seems to be planning to add support for mermaid in is markdown rendering. Would be great if gitea could match this, not because I personally have a use in mind but because it would keep compatability for those wanting to migrate to gitea from guthub.

**Comment by lunny** [comment]
mermaid has been supported.

**Comment by 6543** [comment]
mermaid got in and if you need some extra renderer you can inject custom JS to do so

**Comment by 6543** [comment]
@silverwind best would be to open a new issue and link to the upstream issue

**Comment by silverwind** [comment]
Yeah maybe once I have a more concrete Idea. I think we can do better than having to instruct users to insert JavaScript into templates for PlantUML support.

**Comment by silverwind** [comment]
https://github.com/go-gitea/gitea/issues/18272
