### ISSUE TITLE
how to run with kuberntes without database?

### ISSUE THREAD

**Issue by lovebaby979** [go-gitea/gitea#9557]
How to run gitea with kubernets without database, by cluster, 3 pods?

**Comment by bagasme** [comment]
@lovebaby979 Did you mean that your setup is a Gitea pod and two (remote) database pods?

**Comment by lunny** [comment]
A database is necessary.

**Comment by bagasme** [comment]
@lunny I don't know what @lovebaby979 intend to do, but I interpret this issue as running Gitea in a pod separated from the DB pod.
