### ISSUE TITLE
Custom fonts URL on fomantic

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#9562]
Currently, fomantic will load fonts from https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic&subset=latin&display=swap. That should be configurable.

**Comment by bagasme** [comment]
@lunny Can the config be stored @ `app.ini`?

**Comment by silverwind** [comment]
All assets should be served locally, with the only exception being Gravatar avatars (unfortunately).

**Comment by lunny** [comment]
I have sent a PR https://github.com/go-gitea/gitea/pull/9561 to use npm to build fomantic at first.

**Comment by bagasme** [comment]
@lunny Why npm first?

**Comment by lunny** [comment]
@bagasme I have disabled google fonts on #9561. Because we used minified js/css of fomantic we should not change it. So we have to build fomantic from the source.
