### ISSUE TITLE
problem in  initial configuration

### ISSUE THREAD

**Issue by waltervanzellaGVT** [go-gitea/gitea#9569]
- Gitea version (or commit ref):  1.9.0-dev
- Git version: 2.24.1.2
- Operating system: Windows Server 2019 essential
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:

## Description
Hi,  I have a problem during the initial configuration.  (I am sorry, at present the discord does not send me the confirmation e-mail, i cannot ask there).

I am able to launch  gitea web,  then  I open the  localhost:3000, and is ok.  When I try  to sign-in, the "initial configuration page" opens but I cannot chose between the  Database type.  The drop-down menu does not work.  All menus do not work.
I woud like to choose  SQLite (which I have copied/installed) but is impossible.
I tried to fill-in the  app.ini  with the database type ,  but it has no effect.

Any suggestion ?
Thank you,
W.
...

**Comment by waltervanzellaGVT** [comment]
A small step forward.
By editing HTML I was able to complete the  initial configuration. I noticed that SQLite was not supported by my binaries so I installed Postress which is ok.

Anyway the dashboard is unusable. All drop-down menus do not work.
This problem seems similar to issue #6899
which Kgraefe  closed writing  : It turned out to be my Apache reverse proxy configuration. I had SetOutputFilter INFLATE;proxy-html;DEFLATE which apparently breaks the menu.

Since I have no experience on these topics I have no idea how to proceed. 
Can anyone help ?
Thank you,
W.

**Comment by jolheiser** [comment]
Where did you get your binary from?  
It sounds like your binary is missing assets.

**Comment by waltervanzellaGVT** [comment]
Hi,
I followed these instructions
https://drizin.io/installing-gitea-git-server-developed-in-go-in-windows/
by using the  "go build"  I compiled the downloaded package   ( get -d -u
code.gitea.io/gitea ).
W.


Il giorno mar 7 gen 2020 alle ore 16:05 John Olheiser <
notifications@github.com> ha scritto:

**Comment by jolheiser** [comment]
Ah, yes that would likely lead to a binary with no assets.  

1. If this is a new install, I would recommend using `1.10.2` or waiting for `1.11.0` (should be released in a week or two, depending on bug-fixes)
2. I would take a look at our [install from source](https://docs.gitea.io/en-us/install-from-source/) page if you really want to build from source

If you have no need to build it yourself, I'd recommend getting a pre-built binary from our [downloads page](https://dl.gitea.io/gitea/) and following the [binary installation guide](https://docs.gitea.io/en-us/install-from-binary/)

**Comment by waltervanzellaGVT** [comment]
ok, thank you.
I will install the 1.10 .2,  I have time now to try , next weeks  probably
I am quite busy.
Is it possible to upgrade to 1.11.0  later ?
Walter

Il giorno mar 7 gen 2020 alle ore 16:23 John Olheiser <
notifications@github.com> ha scritto:

**Comment by jolheiser** [comment]
Yes, you can always upgrade later. 😄
