### ISSUE TITLE
Add Html Rendering in Md files

### ISSUE THREAD

**Issue by abilogos** [go-gitea/gitea#9579]
Hello I Guest there is a feature That it would to be good to be add.
Capability to render Html That has been written in Mark Down Files.

Gitea Dosent Show Html Tags And Styling.

If Any One Can give me Some Hint.
 I would Appreciate  to Contribute if it can be Done With JS Because I am not familiar with The Go.
Thanks.

**Comment by jolheiser** [comment]
Can you explain further? HTML is rendered in markdown files.  
https://try.gitea.io/jolheiser/ciw/src/branch/master/README.md

**Comment by lafriks** [comment]
Closing as already supported, please reopen if something does not work as expected

**Comment by abilogos** [comment]
According to this PR :
https://try.gitea.io/jolheiser/ciw/pulls/18
Html Styling Dosent Work As I expected.

**Comment by abilogos** [comment]
My Expected View Behavior: 
![Screenshot from 2020-01-02 10-57-38](https://user-images.githubusercontent.com/17473661/71656004-cf7d0f00-2d4e-11ea-8537-1232b993a956.png)

But What i Got:
![Screenshot from 2020-01-02 10-59-51](https://user-images.githubusercontent.com/17473661/71656200-a90ba380-2d4f-11ea-88f5-c0e2d38c28f9.png)

**Comment by zeripath** [comment]
Ah did you have classes or styles on the html?

Raw Styles cannot be allowed - there's a huge number of horrible things a style can do.

Regarding classes we can consider prefixing these with a "user-content-" prefix again because we don't want to allow user generated content to look like Gitea content.

**Comment by abilogos** [comment]
so if i define my styling i <style> tag and give element class names with user-content- prefix, does it works?
something like:
<style>
.user-content-label-success{
background: ...;
}
</style>

**Comment by zeripath** [comment]
You had style attributes on the embedded HTML in your markdown in the example screenshots.

Style attributes and elements cannot be allowed. Just think about the things a hostile user could do if it was. (You know CSS and style can be used to load arbitrary URLs - but even if you block those coming up with any sort of sanitised safe set is very difficult.)

Looking at your example though I do see that what you want to do would be relatively nice however, we need technical and safe solutions to do it.

The most simple of these is to allow classes to be set but forcibly prefix these classes with a "user-content-" then it's up to you as a site owner to decide how those are styled. If that would work could you open an issue with that as a feature request?

If you can come up with another better idea that's safe, open a different feature request. However please note we won't be able to emit style attributes or elements from the markdown renderer without significant restructuring of our sanitisers as sanitising style is not easy. If you can find a style sanitiser that you suggest we use then we can take a look too.

**Comment by KestrelSoftworks** [comment]
@zeripath So that means that is not possible to have something like  `<p align=center>lorem ipsum</p>` or `<img src="meow.png" width="300px">` like in github?
I'd like to prettier the readme files a bit but isn't working.
