### ISSUE TITLE
Create repos on push not working

### ISSUE THREAD

**Issue by rveerd** [go-gitea/gitea#9589]
- Gitea version (or commit ref): Gitea version 1.10.1 built with GNU Make 4.1, go1.13.4 : bindata, sqlite, sqlite_unlock_notify
- Git version: git version 2.18.1
- Operating system: CentOS Linux release 8.0.1905 (Core)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

I have added the following to `app.ini` as described in the [Config Cheat Sheet](https://docs.gitea.io/en-us/config-cheat-sheet/):

```
[repository]
ENABLE_PUSH_CREATE_USER = true
```

However when I try to push a new repository (that does not exist in Gitea) to Gitea I get the following error:

```
$ git push origin master
Gitea: Unauthorized
Cannot find repository rveerd/ipc
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Cloning and pushing to other repositories (that do exists in Gitea) is working.

My understanding was that enabling this option allows me to create new repos in Gitea just by pushing them to the Gitea server.

When I look at the Gitea source code, I do not see any lines referring to the `ENABLE_PUSH_CREATE_USER` configuration option. I do see a `EnablePushCreateUser` variable but this is only initialized to `false`.

If this feature is no longer supported, please update the relevant documentation.

**Comment by jolheiser** [comment]
This is only available in 1.11, which has not been released yet.

**Comment by sapk** [comment]
As stated by @jolheiser, this isn't in a released version yet. 
A release candidate for 1.11 should come soon in the meantime depending on your setup you can try a binary from [master](https://dl.gitea.io/gitea/master/) or use the docker tag :latest. 
I will close this issue since I think it as been answered but feel free to re-open it if needed.

**Comment by be-engineer** [comment]
It's worked in 13.0
