### ISSUE TITLE
Option to show login page instead of home page

### ISSUE THREAD

**Issue by timonegk** [go-gitea/gitea#9597]
- Gitea version (or commit ref): 1.10.1

## Description
In my use case, the user must always be logged in to use my gitea instance, there are no public repositories. Therefore I would like to let the user always land on the login page when they are not logged in. When they are logged in, they should be redirected to their home page, as usual.
Currently, the closest I can get there is by setting `LANDING_PAGE = explore` – this redirects unauthenticated users to the login page, but authenticated users are of course redirected to the explore page. Setting `LANDING_PAGE = home` shows the Gitea start page instead of the login page to unauthenticated users.
Am I missing a setting or is it not implemented?

**Comment by bagasme** [comment]
@timonegk what about `LANDING_PAGE = user/login`?

**Comment by timonegk** [comment]
According to the documentation and the sample app.ini, the only possible values are `home`, `explore` and `organizations`. But maybe other values work nevertheless, I can try later.

**Comment by sapk** [comment]
Only the three in the docs are supported this would need a simple fix here : https://github.com/go-gitea/gitea/blob/2f9564f993ba02ba503d7088eb8cc70536b7a6df/modules/setting/setting.go#L646

By adding a new case.
