### ISSUE TITLE
Disable remote messages on push

### ISSUE THREAD

**Issue by rain0r** [go-gitea/gitea#9610]
With the pre- and post-receive calls introduced in #8602, Gitea now sends messages to the pushing client, for example:

```
remote: * Checking 1 branches
remote: Checked 1 references in total
remote: . Processing 1 references
remote: Processed 1 references in total
```

Since git always displays this messages, even when called with `--quiet`, it would be great if these messages could be turned off.

**Comment by zeripath** [comment]
So perhaps some explanation is in order.

This was added to prevent pre-receive and post-receive timing out when multiple branches & tags are pushed. By multiple I mean > 100.

Hmm...

Maybe we could stack these up and only display them if you push more than 30 references?

**Comment by guillep2k** [comment]
> 
> 
> Maybe we could stack these up and only display them if you push more than 30 references?

What about a timer? Many programs show up the progress report only after it's taking longer than a certain time.

If `--quiet` can be detected on the server side we could print `\r` instead (which is mostly invisible... except on Mac, of course).

**Comment by zeripath** [comment]
I've put a simple PR up that won't print anything if the hook runs for less than one second. 

This may need a longer delay or a setting.
