### ISSUE TITLE
Segmentation Fault Error on Xubuntu Odroid

### ISSUE THREAD

**Issue by vmario89** [go-gitea/gitea#9624]
Hi,
upgrading Gitea from 1.10.1 to 1.10.2 produces "Segmentation Fault" Error. I am running the following platform:
Kernel: 4.14.157-171
Architecture: armv7l
Model: Hardkernel Odroid XU4

The same error occured some months ago with the arm-7  builds which are unavailable now. At this time i moved from arm-7 to arm-6 to make it work again.

i am referencing the closed issue https://github.com/go-gitea/gitea/issues/6700

any tips to fix it? Do i need to fix something with my Kernel?

regards, Mario

**Comment by lafriks** [comment]
Are there anything more in logs etc?

**Comment by zeripath** [comment]
This is likely the same issue noted on discord. I believe that there is a kernel issue on the current base which causes golang to segfault.

**Comment by zeripath** [comment]
I think if you rpi-update it should go away.

**Comment by vmario89** [comment]
Hi, unfortunately i am not running a raspberry pi with Gitea, but the problem base might be the same.
@lafriks i reverted back to 1.10.1 which does not fail. the logs did not call anything more than exited process and segmentation fault. is it possible to get more output? maybe using strace?

thanks for the answers, Mario

**Comment by zeripath** [comment]
I was able to prevent the segfault by running the program through gdb - which is not particularly helpful I guess.
