### ISSUE TITLE
Confusion about strong password verification

### ISSUE THREAD

**Issue by pkaq** [go-gitea/gitea#9629]
能否对密码策略加个配置项 新版本的强密码校验对于内网集中式分配账号来说简直是灾难

Can you add a configuration item to the password policy? The new version of strong password verification is a disaster for centralized intranet account allocation

**Comment by pkaq** [comment]
这里只有在管理后台 创建/编辑 用户
用户修改个人资料的时候有校验

在安装得时候设置默认管理员 无校验
创建用户时如果勾选了推荐更改密码 新用户登陆后更改密码也无校验

**Comment by 6543** [comment]
@pkaq can you at least write the title in english 😅

**Comment by bagasme** [comment]
@pkaq and issue description too...

**Comment by 6543** [comment]
@pkaq you should look at https://docs.gitea.io/en-us/config-cheat-sheet/#security-security

-> **PASSWORD_COMPLEXITY** in **security** section

**Comment by lunny** [comment]
It has been documented.

**Comment by 6543** [comment]
@lunny I think the ZH-CN version is outdated :(
https://docs.gitea.io/zh-cn/config-cheat-sheet/#security-security

**Comment by 6543** [comment]
and at least the config-cheat-sheet should be up to date ...
