### ISSUE TITLE
Mirror of an uninitialized repository

### ISSUE THREAD

**Issue by andreasfranke** [go-gitea/gitea#9630]
- Gitea version (or commit ref): 1.9.3
- Git version: 2.21.0.windows.1
- Operating system: Windows 
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL) remote: https://try.gitea.io/frn9bh/Remote.git mirror: https://try.gitea.io/frn9bh/Mirror.git
  - [ ] No
  - [ ] Not relevant

## Description
If I create an **uninitialized** repository as remote, make a mirror of this remote using “New Migration” and “This repository will be a mirror”, the mirror never updates correctly, when I initialize and add some files to remote to a later time.

I found out that Gitea does not update the entries in the SQLite database when migrating (mirroring) an uninitialized repository and then initializing the remote repository and synchronize this repository from mirror. In the table main.repository the “default_branch” must be set to “master” and the field “is_empty” to “0” manually.

**Comment by andreasfranke** [comment]
Hello, everybody, 

I opened this issue two months ago, but have received no response to date. 

I realize that there is no point in cloning/mirroring an uninitialized repository, but even if you create a repository with no content, the URL already exists and therefore a mirror/clone is possible. Why does the mirror/clone not update the data when it is initialized later.

**Comment by lunny** [comment]
It seems it's no meaning to do that.

**Comment by varunsridharan** [comment]
@lunny do you have any update on this ?
[https://discourse.gitea.io/t/mirror-of-an-empty-repository/1734/9](https://discourse.gitea.io/t/mirror-of-an-empty-repository/1734/9) Forum Topic got no proper replies.!! it would be great if this get solved sooner.
