### ISSUE TITLE
Missing space after checkbox

### ISSUE THREAD

**Issue by giteaUser** [go-gitea/gitea#9656]
- Gitea version (or commit ref): v1.11.0-rc1
- Git version: not relevant
- Operating system: not relevant
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL) https://try.gitea.io/transferkraM/markdown-checkbox-table
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
Missing space between checkbox and following string.
## Screenshots

![checkbox](https://user-images.githubusercontent.com/59419232/72003153-01d2b480-3206-11ea-9cfe-f0423fb2299a.png)

**Comment by zeripath** [comment]
This is likely related to the fomantic change but could be due to goldmark not retuning exactly the same html as black Friday.

**Comment by silverwind** [comment]
I think we should improve the rendering of such "task lists". GitHub adds a `.task-list-item` class to cases where it detects such lists in markdown and then hides the dots besides each list item via CSS:

```` css
.task-list-item {
    list-style-type: none;
}
````

I wonder if we can replicate that somehow. Of course including some spacing after the checkbox.
