### ISSUE TITLE
Can't create repository

### ISSUE THREAD

**Issue by lyf1350** [go-gitea/gitea#9659]
- Gitea version (or commit ref):v1.11.0-rc1
- Git version: 2.22.0
- Operating system:windows server 2016
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:
...les/context/panic.go:35:1() [E] PANIC:: runtime error: invalid memory address or nil pointer dereference
	/usr/local/go/src/runtime/panic.go:199 (0x448373)
	/usr/local/go/src/runtime/signal_windows.go:233 (0x448220)
	/go/src/code.gitea.io/gitea/models/repo_generate.go:122 (0xf614a4)
	/go/src/code.gitea.io/gitea/models/repo_generate.go:193 (0xf6231d)
	/go/src/code.gitea.io/gitea/models/repo_generate.go:238 (0xf62928)
	/go/src/code.gitea.io/gitea/services/repository/generate.go:24 (0x1399e03)
	/go/src/code.gitea.io/gitea/models/context.go:47 (0xec07bc)
	/go/src/code.gitea.io/gitea/services/repository/generate.go:16 (0x1398c06)
	/go/src/code.gitea.io/gitea/routers/repo/repo.go:213 (0x149916e)
	/usr/local/go/src/reflect/value.go:460 (0x49664c)
	/usr/local/go/src/reflect/value.go:321 (0x495e0a)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:177 (0x9c4d30)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:137 (0x9c46d0)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:121 (0x9f615f)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:112 (0x1019358)
	/go/src/code.gitea.io/gitea/modules/context/panic.go:39 (0x1019344)
	/usr/local/go/src/reflect/value.go:460 (0x49664c)
	/usr/local/go/src/reflect/value.go:321 (0x495e0a)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:177 (0x9c4d30)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:137 (0x9c46d0)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:121 (0x9f615f)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:112 (0xac76dc)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/session/session.go:192 (0xac76c7)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:79 (0x9f5fd7)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:157 (0x9c4a40)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:135 (0x9c47bf)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:121 (0x9f615f)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:112 (0xa07aa0)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/recovery.go:161 (0xa07a8e)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/logger.go:40 (0x9f9dba)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:157 (0x9c4a40)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:135 (0x9c47bf)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:121 (0x9f615f)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:112 (0xa06db7)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/logger.go:52 (0xa06da2)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/logger.go:40 (0x9f9dba)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:157 (0x9c4a40)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:135 (0x9c47bf)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:121 (0x9f615f)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/router.go:187 (0xa08d4d)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/router.go:294 (0xa026a4)
	/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/macaron.go:218 (0x9fb191)
	/go/src/code.gitea.io/gitea/vendor/github.com/gorilla/context/context.go:141 (0xd50e24)
	/usr/local/go/src/net/http/server.go:2007 (0x75d3fa)
	/usr/local/go/src/net/http/server.go:2802 (0x7608ea)
	/usr/local/go/src/net/http/server.go:1890 (0x75c1bb)
	/usr/local/go/src/runtime/asm_amd64.s:1357 (0x462ec0)
## Description
When I create a repository ,then I get 500 internal server error. It happens after I create a repository using template repository.
...

**Comment by techknowlogick** [comment]
We found and patched a bug with the RC and windows and have a temporary version published at https://dl.gitea.io/gitea/1.11/ could you try this binary?
