### ISSUE TITLE
Not possible to add a team to a repository with the same name of the organization

### ISSUE THREAD

**Issue by bu3tt1** [go-gitea/gitea#9662]
- Gitea version (or commit ref): docker image gitea/gitea:1.10.1
- Git version: 2.22.0
- Operating system: Docker on Mac OS and Chrome
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL) https://try.gitea.io/error_team_name/repo/settings/collaboration > try to add team error_team_name
  - [ ] No
  - [ ] Not relevant
- Log gist: no logs

## Description
It's not possible to add a team to a repository with the same name of the organization.

**Comment by davidsvantesson** [comment]
Strange. You can add it from the team settings page. It is the repo collaboration setting page that has the problem.

**Comment by bu3tt1** [comment]
Thanks!

**Comment by davidsvantesson** [comment]
Thanks for the report 😃
