### ISSUE TITLE
1.11.rc1 - Stuck on checking merge conflicts

### ISSUE THREAD

**Issue by marcsiq** [go-gitea/gitea#9667]
- Gitea version (or commit ref): 1.11.rc1
- Git version:
- Operating system: ubuntu
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description

I didn't know where to post this one, but I did update my gitea to 1.11-rc1 and since then my PRs get stucked in "Checking for merge conflicts, try again in a few moments" after merging in the main branch. I did roll back to 1.10.2 and it seems to work well on that one.

**Comment by zeripath** [comment]
@Marcsiq2 rolling back to 1.10.2 doesn't necessary mean that there was a problem on 1.11 - depending on how you rolled back. The worklist could have just taken that long to work through.

We need some log information to work out what is going wrong - if anything.

There were three major changes to the PR checking:

#9282, #9302 and #9501 

#9282 might be the cause of your apparent problem as one of the more hidden changes here was to remove a bug whereby PRs would only ever be checked once. 

That means that there's potentially lots more PR checking to do - although the queue is uniqued by PRID - possibly we're doing too much for example if the status check fails then the status will remain in checking.

We need logs. Log trace would have told us what the pull request tester was doing here.

For future reference this configuration should give us TRACE level logs for the pull service: 

```
[log]
MODE=...,traceconsole ; Add the traceconsole logger to your current log modes
...

[log.traceconsole]
MODE=console
LEVEL=trace
EXPRESSION=services/pull
```

**Comment by Marcsiq2** [comment]
Thank you very much for your detailed help! I'll try that.

**Comment by Marcsiq2** [comment]
We still have this problem, even with 10.2 now. I've added the log configuration. 
I'm running it as a systemctl service, do you know where can I acces this console log? 
Thank you for your help, I'm quite new on managing linux servers and stuff.

**Comment by zeripath** [comment]
The console log is emitted on stdout. You can change the mode to file and set a FILE_NAME if you can't use the console.

On 1.10 the EXPRESSION should be models/pull

If you're getting the problem on 1.10 it is likely that you're facing the issue that there is just one worker running the pull request task and it's just busy.

**Comment by Marcsiq2** [comment]
1.10

[log]
MODE      = file,traceconsole
LEVEL     = Info
ROOT_PATH = /home/git/gitea/log

[log.traceconsole]
MODE=file
FILE_NAME=pulls.log
ROOT_PATH=/home/git/gitea/log
LEVEL=trace
EXPRESSION=models/pull



2020/01/15 09:43:34 models/pull.go:1127:AddTestPullRequestTask() [T] AddTestPullRequestTask [head_repo_id: 2, head_branch: develop]: finding pull requests
2020/01/15 09:43:34 models/pull.go:1167:AddTestPullRequestTask() [T] AddTestPullRequestTask [base_repo_id: 2, base_branch: develop]: finding pull requests
2020/01/15 09:43:34 models/pull.go:1282:TestPullRequests() [T] TestPullRequests[511]: processing test task
2020/01/15 09:43:34 models/pull.go:609:testPatch() [T] PullRequest[511].testPatch: ignored corrupted data
2020/01/15 09:43:34 models/pull.go:1282:TestPullRequests() [T] TestPullRequests[481]: processing test task
2020/01/15 09:43:34 models/pull.go:616:testPatch() [T] PullRequest[481].testPatch (patchPath): /home/git/gitea-repositories/sw/atlas.git/pulls/272.patch
2020/01/15 09:43:34 models/pull.go:1127:AddTestPullRequestTask() [T] AddTestPullRequestTask [head_repo_id: 2, head_branch: develop]: finding pull requests
2020/01/15 09:43:34 models/pull.go:1167:AddTestPullRequestTask() [T] AddTestPullRequestTask [base_repo_id: 2, base_branch: develop]: finding pull requests
2020/01/15 09:43:35 models/pull.go:1282:TestPullRequests() [T] TestPullRequests[501]: processing test task
2020/01/15 09:43:35 models/pull.go:609:testPatch() [T] PullRequest[501].testPatch: ignored corrupted data
2020/01/15 09:43:35 models/pull.go:1282:TestPullRequests() [T] TestPullRequests[502]: processing test task
2020/01/15 09:43:35 models/pull.go:609:testPatch() [T] PullRequest[502].testPatch: ignored corrupted data
2020/01/15 09:43:35 models/pull.go:1282:TestPullRequests() [T] TestPullRequests[504]: processing test task
2020/01/15 09:43:35 models/pull.go:609:testPatch() [T] PullRequest[504].testPatch: ignored corrupted data
2020/01/15 09:43:35 models/pull.go:1282:TestPullRequests() [T] TestPullRequests[505]: processing test task
2020/01/15 09:43:35 models/pull.go:609:testPatch() [T] PullRequest[505].testPatch: ignored corrupted data
2020/01/15 09:43:35 models/pull.go:1282:TestPullRequests() [T] TestPullRequests[507]: processing test task
2020/01/15 09:43:35 models/pull.go:609:testPatch() [T] PullRequest[507].testPatch: ignored corrupted data
2020/01/15 09:43:35 models/pull.go:1282:TestPullRequests() [T] TestPullRequests[508]: processing test task
2020/01/15 09:43:35 models/pull.go:609:testPatch() [T] PullRequest[508].testPatch: ignored corrupted data
2020/01/15 09:43:35 models/pull.go:1282:TestPullRequests() [T] TestPullRequests[509]: processing test task
2020/01/15 09:43:35 models/pull.go:609:testPatch() [T] PullRequest[509].testPatch: ignored corrupted data
2020/01/15 09:43:35 models/pull.go:1282:TestPullRequests() [T] TestPullRequests[510]: processing test task
2020/01/15 09:43:35 models/pull.go:609:testPatch() [T] PullRequest[510].testPatch: ignored corrupted data
2020/01/15 09:43:35 models/pull.go:1282:TestPullRequests() [T] TestPullRequests[511]: processing test task
2020/01/15 09:43:35 models/pull.go:609:testPatch() [T] PullRequest[511].testPatch: ignored corrupted data
2020/01/15 09:43:35 models/pull.go:1282:TestPullRequests() [T] TestPullRequests[481]: processing test task
2020/01/15 09:43:35 models/pull.go:616:testPatch() [T] PullRequest[481].testPatch (patchPath): /home/git/gitea-repositories/sw/atlas.git/pulls/272.patch
2020/01/15 09:43:48 models/pull.go:1127:AddTestPullRequestTask() [T] AddTestPullRequestTask [head_repo_id: 2, head_branch: feature/uif_setup_changes]: finding pull requests
2020/01/15 09:43:49 models/pull.go:1167:AddTestPullRequestTask() [T] AddTestPullRequestTask [base_repo_id: 2, base_branch: feature/uif_setup_changes]: finding pull requests



1.11

[log]
MODE      = file,traceconsole
LEVEL     = Info
ROOT_PATH = /home/git/gitea/log

[log.traceconsole]
MODE=file
FILE_NAME=pulls.log
ROOT_PATH=/home/git/gitea/log
LEVEL=trace
EXPRESSION=services/pull

2020/01/15 09:55:23 ...ervices/pull/pull.go:172:AddTestPullRequestTask() [T] AddTestPullRequestTask [head_repo_id: 2, head_branch: develop]: finding pull requests
2020/01/15 09:55:23 ...ervices/pull/pull.go:202:func1() [T] AddTestPullRequestTask [base_repo_id: 2, base_branch: develop]: finding pull requests
2020/01/15 09:55:23 ...rvices/pull/check.go:188:TestPullRequests() [T] TestPullRequests[511]: processing test task
2020/01/15 09:55:24 ...ervices/pull/pull.go:172:AddTestPullRequestTask() [T] AddTestPullRequestTask [head_repo_id: 2, head_branch: develop]: finding pull requests
2020/01/15 09:55:24 ...ervices/pull/pull.go:202:func1() [T] AddTestPullRequestTask [base_repo_id: 2, base_branch: develop]: finding pull requests
2020/01/15 09:55:24 ...rvices/pull/patch.go:129:TestPatch() [T] PullRequest[511].testPatch (patchPath): /tmp/patch403834576
2020/01/15 09:55:24 ...rvices/pull/patch.go:207:TestPatch() [T] Found 10 files conflicted: [core/core_COMMS/core_COMMS.c core/core_DISPLAY/core_DISPLAY_Command_def.h core/core_MODEL/core_MODEL_DATA/core_MODEL_DISPLAY_LOOP/core_MODEL_DISPLAY_LOOP.c core/core_MODEL/core_MODEL_DATA/core_MODEL_RX_INFO/core_MODEL_RX_INFO.c core/core_MODEL/core_MODEL_DATA/core_MODEL_RX_INFO/core_MODEL_RX_INFO_def.h core/core_MODEL/core_MODEL_def.h core/core_OUT/core_OUT_defs.h core/core_COMMS.h core/core_MODEL/core_MODEL_DATA/core_MODEL_RX_INFO/core_MODEL_RX_INFO.h core/core_OUT/core_OUT_MODULES/core_OUT_DISPLAY/core_OUT_DISPLAY.c]
2020/01/15 09:55:34 ...ervices/pull/pull.go:172:AddTestPullRequestTask() [T] AddTestPullRequestTask [head_repo_id: 2, head_branch: feature/comms_sl_menu_seperation]: finding pull requests
2020/01/15 09:55:34 ...ervices/pull/pull.go:202:func1() [T] AddTestPullRequestTask [base_repo_id: 2, base_branch: feature/comms_sl_menu_seperation]: finding pull requests

**Comment by Marcsiq2** [comment]
[giteapulls.txt](https://github.com/go-gitea/gitea/files/4064220/giteapulls.txt)

Find there logs for both 1.10 and 1.11rc1

1.10 worked fine after a restart, while 1.11 is stuck in "checking merge conflict" and nothing else appears on the log.

**Comment by Marcsiq2** [comment]
[giteapulls2.txt](https://github.com/go-gitea/gitea/files/4064245/giteapulls2.txt)

And all this appears and the "checking..." disappears after restarting gitea.

**Comment by zeripath** [comment]
I think I've found the cause.
