### ISSUE TITLE
Feature request: Time tracking

### ISSUE THREAD

**Issue by mixedCase** [go-gitea/gitea#967]
Gogs issue describing the idea behind the request: https://github.com/gogits/gogs/issues/879

GitLab implements it for its Enterprise version. It would be a killer feature for Gitea to have this.

**Comment by lunny** [comment]
I'm not very clear with this feature.

**Comment by mixedCase** [comment]
@lunny Example for GitLab: https://docs.gitlab.com/ee/workflow/time_tracking.html

**Comment by kolaente** [comment]
Or we could simply make a button next to the issue "Start Timetracking" and once you're finished you would just click "Stop Timetracking" and it would save the time spent with the issue. Like you can do it in Flyspray.

With this, you wouldnt need an extra tool for timetracking.

**Comment by jonasfranz** [comment]
My Concept:

1. "Start" button for timetracking starts a sort of stopwatch.
2. "Stop" button stops the stopwatch and creates a record with the timedifference between the startdate and the stopdate.
3. The tracked time appeares as a reference in the issue (like commit references)
4. At the right sidebar appears a listing of the tracked time in total per user.

**Comment by lunny** [comment]
A `Start` button near the `Close` button. After click `Start` button and started, `Start` button will be changed to `Finished` button. Click `Finished` button or a commit with close tag both are ok. Simple click `Close` button will mean give up the issue.

**Comment by kolaente** [comment]
I like the idea, but i would propose to move the button also to the right, where the other options are.

**Comment by lunny** [comment]
I like the button near the `Close` so reminder the user to click the `finish` but not `close`.

**Comment by jonasfranz** [comment]
There is a bounty posted on this issue.
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=42166141)](https://www.bountysource.com/issues/42166141-feature-request-time-tracking?utm_source=42166141&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by jonasfranz** [comment]
@lunny I agree with @kolaente because a button at the right sidebar would be more convenient because of the existence of the "Subscribe" button. It could be placed below this button in an equal style with other icons. 

Having the button near the close button could point out that the user must write a comment to track his/her time but you rarely write a comment and track the spent time simultaneously.

**Comment by jonasfranz** [comment]
I've made a smll UI draft. What do you think? 
An alternative according to @lunny will be theire soon.
![Time Tracker Finish](https://cloud.jonasfranz.software/index.php/apps/files_sharing/ajax/publicpreview.php?x=1920&y=579&a=true&file=time_tracker_finish.png&t=k5lULSSZZNi0zvJ&scalingup=0 "Time Tracker Finish")
![Time Tracker Start](https://cloud.jonasfranz.software/index.php/apps/files_sharing/ajax/publicpreview.php?x=1920&y=579&a=true&file=time_tracker_start.png&t=b2u55RXvBKVGbcR&scalingup=0 "Time Tracker Start")

**Comment by kolaente** [comment]
Colors would be nice, maybe yellow to indicate it's currently tracking.

**Comment by lafriks** [comment]
Also option to enable/disable time tracking for organization/repository/server would be great

**Comment by jonasfranz** [comment]
![timetracking_new](https://user-images.githubusercontent.com/5757182/28544803-d3a41d7e-70c4-11e7-8a98-573db09ec529.png)

* The "+" button let the user add spent time manually by a modal.
* The "Start" button will start a stopwatch
* Every time tracking event will be logged in the timeline
* Under the Start / + button is a list of the total time spent by the users

**Comment by lafriks** [comment]
I think button "Add" will be much clearer than "+"

**Comment by Caballerog** [comment]
I'm testing this feature, which I think that is very useful, but should allow the user modify or delete a time tracking event because It can make a mistake. Good job!! :-)

**Comment by daviian** [comment]
@Caballerog Please create a new issue for this feature request.

**Comment by Caballerog** [comment]
@daviian Thanks ;-) rel https://github.com/go-gitea/gitea/issues/2642
