### ISSUE TITLE
[Bug] [API]  ​/repos​/issues​/search

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#9677]
version 1.11.0-RC1 return 500 on api `​/repos​/issues​/search`

**Comment by 6543** [comment]
Info: ocure only if no token/login exist

**Comment by davydov-vyacheslav** [comment]
I'd like to reopen this defect:


I'm trying to get list of all open PR within the system via API. When I'm trying to execute `/repos/issue/search` API request (even without search parameters, even without authentication -- just `curl -X GET "https://try.gitea.io/api/v1/repos/issues/search"`) I'm retrieving the following error: `Find: too many SQL variables`

- Gitea version: 1.12.0+dev-3-g9269b7f62 
- full request:  `curl -X GET "https://try.gitea.io/api/v1/repos/issues/search?state=open&type=pulls" -H "accept: application/json" -H "authorization: Basic ZGF2c0BqYXZhbml4LmNvbTpkYXZ5ZG92dnY="`

P.S. I have local system of `1.11.2` version and don't have such issue.

**Comment by zeripath** [comment]
Please open a different issue. The bug you're referring to is different.
