### ISSUE TITLE
Custom Webhooks

### ISSUE THREAD

**Issue by Dr-Ari-Gami** [go-gitea/gitea#9689]
- Gitea version (or commit ref): 1.10.2
- Git version: Not Relevant
- Operating system: Not Relevant
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist: N/A

## Description
The ability to create custom webhooks for repositories would be awesome. Instead of just using templates, it would be helpful to be able to pass your own webhook URL, with its own headers and body that the user can customize.

**Comment by techknowlogick** [comment]
This is what the webhook templates would hope to achieve.
