### ISSUE TITLE
Gitea instance returns HTTP status 404 when only asking for headers

### ISSUE THREAD

**Issue by dakira** [go-gitea/gitea#969]
- Gitea version (or commit ref): 1.0.1 (all Gitea and Gogs versions are affected)
- Git version: 1.9.1
- Operating system: Ubuntu 14.04 through 16.10
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (see below)
  - [ ] No
  - [ ] Not relevant

## Description

When requesting headers only, from a Gitea-server, it wrongly returns HTTP status 404.

Expected: HTTP 200.

```
~ curl -I https://try.gitea.io
HTTP/1.1 404 Not Found
Content-Type: text/html; charset=UTF-8
Date: Sat, 18 Feb 2017 12:22:11 GMT
Set-Cookie: lang=en-US; Path=/; Max-Age=2147483647
Set-Cookie: i_like_gitea=003f17e962323116; Path=/; HttpOnly
Set-Cookie: _csrf=-GQNJ7f6zhbIHnvi9zdMfG1sha86MTQ4NzQyMDUzMDk5NjQ4MTc4OA%3D%3D; Path=/; Expires=Sun, 19 Feb 2017 12:22:10 GMT; HttpOnly
X-Frame-Options: SAMEORIGIN
```

This is not expected behavior for a site that is available. Uptime-Monitors will show gitea instances as down because they usually only request the headers.

**Comment by Fastidious** [comment]
I think http://try.gitea.io is having problems. That might be the reason of this.

**Comment by dakira** [comment]
For reference, this was already discussed for Gogs: https://github.com/gogits/gogs/issues/2857

**Comment by dakira** [comment]
This route should help health checks pass for Gitea.

```
m.Head("/", func() {
    return "Operating"
})
```
