### ISSUE TITLE
Lang cookie missing secure/httpOnly attributes

### ISSUE THREAD

**Issue by tgurr** [go-gitea/gitea#9690]
- Gitea version: 1.10.2
- Git version: 2.24.0
- Operating system: Linux
- Database:
  - [X] MySQL
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes (provide example URL)

![gitea_cookies_trygiteaio](https://user-images.githubusercontent.com/414984/72142966-28275a00-3396-11ea-89ba-8d3bc20ad2d2.png)

## Description

I've configured my Gitea instance with `CSRF_COOKIE_HTTP_ONLY` and `COOKIE_SECURE`:

```
; Set false to allow JavaScript to read CSRF cookie
CSRF_COOKIE_HTTP_ONLY              = true
; If you use session in https only, default is false
COOKIE_SECURE     = true
```
which works fine, except for the lang cookie that doesn't seem to respect that setting:

![gitea_cookies](https://user-images.githubusercontent.com/414984/72142971-2c537780-3396-11ea-80b7-04e5fe8ff08a.png)

resulting in a security scanner complaining about the cookie missing the `secure` and `httpOnly` attributes.

**Comment by rodolpheh** [comment]
I think it all boils down to the i18n module for macaron-go : https://github.com/go-macaron/i18n/blob/5a5348d12f10480196f7376cf48de94fa93eb236/i18n.go#L202

**Comment by rodolpheh** [comment]
My bad, I just saw that i18n in Gitea is a fork.

**Comment by tgurr** [comment]
@rodolpheh thanks for your work! Looks like the changes also have been pulled into the i18n Gitea fork in the meantime. Is there any option which allows to enable this or is currently the only way to enable/test this to manually change the settings which are off by default in i18n.go before compiling Gitea?

**Comment by rodolpheh** [comment]
Sorry I have a terrible memory and barely remembered doing that :smile: . Unfortunately it seems that I haven't pushed any changes that would allow setting those in Gitea. I had to dig a little before finding what I had changed in Gitea to make it work. Please find attached a patch file until a proper push is made on Gitea. I pulled the latest sources to make sure this works so hopefully it should work for you.

After applying this patch, the Secure and HttpOnly flags should be added if you had COOKIE_SECURE and CSRF_COOKIE_HTTP_ONLY set to true in your app settings.

[macaron.go.patch.txt](https://github.com/go-gitea/gitea/files/5757121/macaron.go.patch.txt)

**Comment by tgurr** [comment]
@rodolpheh Thanks for the hint, I couldn't apply your patch, probably because I build from source so I had no `/routers/routes/macaron.go b/routers/routes/macaron.go` file to begin with.

Based on your patch I went with this: [gitea-1.13.1-lang-cookie.txt](https://github.com/go-gitea/gitea/files/5763573/gitea-1.13.1-lang-cookie.txt). Not sure if it's ready for a PR like it is, but it appears to do the trick:

![Screenshot_20210104_083856](https://user-images.githubusercontent.com/414984/103512972-fbebcf80-4e69-11eb-9e7d-b99eb3c1fde6.png)
