### ISSUE TITLE
note: refacotr models/webhook.go

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#9692]
note for me:

refactor models/webhook.go to combine GetWebhooksByRepoID and GetWebhooksByOrgID to `GetWebhooks(opts SearchWebhooksOptions) .,...

```
// SearchWebhooksOptions holds the search options
type SearchWebhooksOptions struct {
...
```

**Comment by 6543** [comment]
@SpaWn2KiLl ping

**Comment by 6543** [comment]
and we can also include getActiveWebhooksByOrgID

**Comment by SpaWn2KiLl** [comment]
I'll take this. If you find any more cases like this add to this issue please.

**Comment by 6543** [comment]
@SpaWn2KiLl are you still interested in it?

**Comment by alexanderadam** [comment]
I'm not sure whether this could be related but it would be great if it would be made with focus on #1089, if someone decides to refactor `models/webhook.go`.

**Comment by 6543** [comment]
@alexanderadam this is out of scope ...

**Comment by alexanderadam** [comment]
Okay, no problem :+1: I just wanted to mention it, in case it would be suitable.

**Comment by 6543** [comment]
Did have a closer look into codebase: combining would have only minimal dedublication and would add complxity so this wont happen for now
