### ISSUE TITLE
[Proposal] Return 404 on Valid Looking but Non-Existent Commit URL

### ISSUE THREAD

**Issue by bagasme** [go-gitea/gitea#9701]
## Description

Currently when connecting with valid-looking, but non-existent commit URL (by valid-looking means 40-character SHA-1 hash), Gitea will return generic `500 Internal Server Error` error. In this proposal, the error returned for this case should be `404 Not Found`, as here in GitHub.

**Comment by fnetX** [comment]
I think this is resolved? https://try.gitea.io/Inabirtia/test/commit/366dcb45cb3b664d31caf5c23e1a8a6d65dea6bd
