### ISSUE TITLE
404 for not authorized users

### ISSUE THREAD

**Issue by antiuser** [go-gitea/gitea#9721]
- Gitea version (or commit ref): 1.10.2
- Git version: 2.11.0
- Operating system: Debian 9 x64
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description
Hi there!
If i not authorized in gitea, and going to repo with restricted access - i get 404 error instead of login page or warning page about that only permitted users can enter to this repo.

## Screenshots
![Снимок экрана_2020-01-12_12-17-18](https://user-images.githubusercontent.com/5499424/72215545-863e7380-3535-11ea-893a-b7cbc50e8e17.png)

**Comment by zeripath** [comment]
That is by design.

We don't want to leak to unauthorized users that a private repository exists.

**Comment by antiuser** [comment]
> That is by design.
> 
> We don't want to leak to unauthorized users that a private repository exists.

Im thinking that should be a 403 error then, because repo exist, but access restricted

**Comment by zeripath** [comment]
Then you would leak to the unauthorized user that the repository exists.

**Comment by antiuser** [comment]
> Then you would leak to the unauthorized user that the repository exists.

We are using gitea for private audience only, not for public. And when user is not authorized and get link for repo then this is misleading him. Hmm, i have idea, all users must be authorized to view any repo. Maybe we can to redirect always to the login page when user is not authorized?

**Comment by zeripath** [comment]
Try REQUIRE_SIGNIN_VIEW

**Comment by antiuser** [comment]
> Try REQUIRE_SIGNIN_VIEW

Yeah, thats will trick!
Thank you much!
