### ISSUE TITLE
Can directly compar two commits?

### ISSUE THREAD

**Issue by FalconWu2017** [go-gitea/gitea#9740]
I have two commits such as 111111 and 222222.
I wanner compare the differences between 1 and 2.
How can I do for this?
`/compare/1111111...222222` is not work.

**Comment by lunny** [comment]
I think it should work. Which version are you using?

**Comment by FalconWu2017** [comment]
I am using version 1.10.2.
![image](https://user-images.githubusercontent.com/34147999/72310302-5ec5e300-36bc-11ea-8f38-32e5eb8b0bdc.png)
