### ISSUE TITLE
Wrong meta info at issueComments on github migration

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#9741]
@lunny if I migrate a repo with issues:

comments are generated wich have the correct creation timestamp but update-timestamp is "1970-01-01T01:00:00+01:00"

**Comment by bagasme** [comment]
@6543 Beginning Unix time epoch?

**Comment by 6543** [comment]
exactly -> migration simply dont set time on **updated** attribute

**Comment by 6543** [comment]
updated should never be less than created :sweat_smile: ...
