### ISSUE TITLE
"Update Branch" button on PR

### ISSUE THREAD

**Issue by techknowlogick** [go-gitea/gitea#9750]
Related #8659 

Similar to GitHub when a branch on a PR is out of sync, then an "Updated Branch" button could be used to merge commits from upstream into PR branch (assuming no merge conflicts)

**Comment by techknowlogick** [comment]
I've just placed a bounty on this issue: https://www.bountysource.com/issues/86919260-update-branch-button-on-pr

**Comment by zeripath** [comment]
An extension that would also be needed is to make the author suggestions ignore these merge commits too.

**Comment by davidsvantesson** [comment]
Maybe all commits which is merge from target shall be ignored as authors, even if not done in UI?

**Comment by zeripath** [comment]
Exactly!

**Comment by davidsvantesson** [comment]
Maybe something to add in the future:
https://github.com/isaacs/github/issues/1419

**Comment by 6543** [comment]
working on it .. to https://github.com/isaacs/github/issues/1419 I plan to reuse a lot of the normal merge code ... so to extend the function should be easy (but I like get the a simple PR in first, extend afterwards)

**Comment by akostin33** [comment]
Could you please attach the link to issue in gitea project same as [isaacs/github#1419](https://github.com/isaacs/github/issues/1419)  ?

**Comment by 6543** [comment]
@akostin33 created #11401

and status update: didnt looked into it at the moment ... to many things
