### ISSUE TITLE
View PR in UI always returns 500

### ISSUE THREAD

**Issue by gerritc** [go-gitea/gitea#9759]
- Gitea version (or commit ref):
- Git version: 1.11.0-rc1
- Operating system: Ubuntu 18.04.3
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:
```
2020/01/14 05:32:33 routers/repo/pull.go:320:PrepareMergedViewPullInfo() [E] GetCompareInfo: exit status 128 - fatal: ambiguous argument 'a6bb53d9d3ae1d78dd55fdd202aec98c62836485...refs/pull/14/head': unknown revision or path not in the working tree.
        Use '--' to separate paths from revisions, like this:
        'git <command> [<revision>...] -- [<file>...]'
```

```
2020/01/14 05:35:18 routers/repo/pull.go:383:PrepareViewPullInfo() [E] GetRefCommitID(refs/pull/84/head): reference not found
```

## Description
After upgrading from 1.10.2 we can't open any pull-request. Gitea  returns always a 500. The first error appears when opening a merged pull-request. The second error appears when opening a open pull-request. I can't figure out how to reproduce this situation.

## Screenshot
![image](https://user-images.githubusercontent.com/32355528/72318753-6d50d200-369d-11ea-9ba2-da0e180926dd.png)

**Comment by zeripath** [comment]
What version of git are you running?

**Comment by zeripath** [comment]
Presumably you're running quite an old git and this notation doesn't work on that version. We'll have to figure out the correct call and then send a patch.

**Comment by gerritc** [comment]
git version: 2.17.1
The problem exists also with current (2.25.0) git version.

**Comment by zeripath** [comment]
Ok. I thought that this would be an old syntax problem.

The problem line is here:

https://github.com/go-gitea/gitea/blob/25531c71a78b98af91f25d5e6eaa362e5fc54a86/modules/git/repo_compare.go#L70

Right. Do you have access to Gitea's repositories on the server?

If so can you go to the repo and try:

git rev-parse --verify refs/pull/14/head

What I am presuming is that git can't find that unusual ref, if this works we can then try the `git log a6bb53d9d3ae1d78dd55fdd202aec98c62836485...the_sha_you_obtain`

If the rev-parse doesn't work I'd like you to check in the refs/pull directory to ensure that the pull does actually have a ref. 

If it doesn't then I'm confused as there should be one there - but it would at least explain why there is this problem.

**Comment by zeripath** [comment]
I think the attached pr fixes this because I suspect what is happening is that the queue gets locked and then the branch never gets updated.

Hopefully that is the issue.

**Comment by ryan-shaw** [comment]
@zeripath I'm running into the same issue here `GetRefCommitID(refs/pull/3/head): reference not found`

version 1.10.3, I don't think your patch will fix it as the code you are changing doesn't exist in 1.10.3  > https://github.com/go-gitea/gitea/blob/v1.10.3/modules/sync/unique_queue.go#L47

Let me know if you need any information.

**Comment by lunny** [comment]
@ryan-shaw could you reproduce that on try.gitea.io?

**Comment by ryan-shaw** [comment]
@lunny I'm not sure I could as I don't know how it got into this state.

**Comment by lunny** [comment]
OKay. any log could you found when the 500 happened?

**Comment by ryan-shaw** [comment]
The ref file I'd expect to see in `/data/git/repositories/<owner>/<repo>.git/refs/pull/3/head` does not exist either so some how Gitea has deleted the references whilst the pull request is still open.

The only log entry available is `2020/01/20 15:08:19 routers/repo/pull.go:368:PrepareViewPullInfo() [E] GetRefCommitID(refs/pull/3/head): reference not found`

**Comment by ryan-shaw** [comment]
It appears the PRs with missing refs were before we migrated to a new host with the backup/restore, in our 14/01/2020 backup I see the file `refs/pull/3/head` but in the first backup after the restore that file has gone. Could this be restore related?

Our restore script does 

```unzip $backup

s6-svc -d /var/run/s6/services/gitea

sleep 5

mv data/conf/app.ini /data/gitea/conf/app.ini

unzip gitea-repo.zip

rm -rf /data/git/repositories
mv repositories /data/git/

chown -R git:git /data/git/ /data/gitea/conf/app.ini
```

**Comment by guillep2k** [comment]
@ryan-shaw Not that this is related to your problem, but just in case: if you ever move the `gitea` executable or `gitea-repositories`, you need to recreate the hooks and the `authorized_keys` file from the site admin menu.

About your script, the question is whether the refs are in the zip file or not. Try extracting one of the refs files directly from the zip and check what it looks like. It should have entries like:

```
2509627ed6e459d8f8c4af9d3e1c26fd16413930        refs/heads/master
33bc2703b09b9998d355503173f410909fe2c19d        refs/pull/2/head
```

The `refs` file should be found on each repo at:

```
gitea-repositories/user1/repouser1.git/info/refs
```

**Comment by ryan-shaw** [comment]
@guillep2k yep, that's already part of our internal restore docs :) 

I can find the the `refs/pull/3/head` in our pre-migration backup, in all subsequent ones it does not exist

**Comment by ryan-shaw** [comment]
@guillep2k 

Interestingly, in our pre-migration backup and current state don't have `refs/pull/3/head` in `gitea-repositories/<user>/<repo>.git/info/refs` but backup does have `gitea-repositories/<user>/<repo>.git/refs/pull/3/head`

**Comment by ryan-shaw** [comment]
I think I know what caused the missing ref, we migrated from Gitlab and in doing so we were using `git remote update && git push --mirror` to sync changes from Gitlab to Gitea, before we switched I opened a couple of PRs to test Gitea, I think what happened with the `git push --mirror` is it deleted the refs it didn't see locally

**Comment by guillep2k** [comment]
@ryan-shaw Glad you could solve it! 😄
