### ISSUE TITLE
Korean localization resource looks broken for v1.11

### ISSUE THREAD

**Issue by seunghyun3825** [go-gitea/gitea#9761]
- Gitea version (or commit ref): v1.11
- Git version: 1.8.3.1
- Operating system: CentOS 7
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
Korean resource looks broken. I guess localization files for Korean defiled.
...

## Screenshots
![image](https://user-images.githubusercontent.com/1332494/72335315-1e895380-3702-11ea-87ff-f5681c83e1b2.png)

![image](https://user-images.githubusercontent.com/1332494/72335516-6f994780-3702-11ea-8d49-fc37ee04d4fd.png)

**Comment by sapk** [comment]
Hi, can you have a look at [crowdin](https://crowdin.com/project/gitea) where the translation are managed.  
If the translation are good please come back and indicate it since it may be related to font.

For more details on translations: https://github.com/go-gitea/gitea/blob/master/CONTRIBUTING.md#translation

**Comment by jeremy3825** [comment]
Thank you @sapk . I signed in crowdin to find misinterpreted string but few strings were shown. It is hard to find original English term before translation. It would be helpful if there is revision history for Korean translation.

**Comment by sapk** [comment]
Crowdin should make propositions based on previous values and translations on others projects. 
If you see string with `%s` it means that this part will be replaced by a word and should be kept (but can be moved if needed).
If it can help you, the result of translation is stored in this file https://github.com/go-gitea/gitea/blame/master/options/locale/locale_ko-KR.ini and you can access the history of the file https://github.com/go-gitea/gitea/commits/master/options/locale/locale_ko-KR.ini
You should also be able to copy and edit this file under custom/options/locale/locale_ko-KR.ini of your setup (need a reboot for changes to apply) if you want to see the change in-situ. But all translation should be submitted via crowdin.

I can't really help you more on the process as I don't even see the letters with my setup and don't know korean ...

**Comment by jeremy3825** [comment]
Thank @sapk for your great explanations about Crowdin and language resources. I found more than 40 strings on Crowdin which have no meaning in Korean and voted them as abuses.
![image](https://user-images.githubusercontent.com/1332494/72399406-6f905a80-3789-11ea-8cb0-157fb56ea7fa.png)

Also, I translated them to Korean with right meaning. 
![image](https://user-images.githubusercontent.com/1332494/72399801-8a170380-378a-11ea-9428-63ee5d1c5bc5.png)

I want to review my suggestions and apply to Gitea as soon as possible.

**Comment by sapk** [comment]
Translation should have landed on master by now. We should maybe backport thoses change to v1.11 branch.

**Comment by jeremy3825** [comment]
Is migration on master processing now? Still bad translations remains.
![image](https://user-images.githubusercontent.com/1332494/72418309-ec3d2c00-37bd-11ea-9683-31fb9b6250d1.png)

**Comment by sapk** [comment]
They are updated each time a PR is validated. If they are not here they should come soon. 
If it isn't here in few hours please indicate missing key like `sign_in_with`, we may have missed them on crowdin.

**Comment by jeremy3825** [comment]
I understand it takes time but translation like `user_profile_and_more` is not yet approved in Crowdin. I am afraid that next release would be shipped without correct translation.

**Comment by sapk** [comment]
Should be good at next PR now

**Comment by sapk** [comment]
https://github.com/go-gitea/gitea/commit/4e566df1c694e47908e59a6db163e5a98d144b83#diff-4e3fc786031f3e8c0377131eada88de2

**Comment by zeripath** [comment]
We'll need another backport of translations before 1.11rc2 I guess.

**Comment by 6543** [comment]
:sweat_smile:

**Comment by 6543** [comment]
created just a nother locales backport: #9780 :sweat_smile:

**Comment by jeremy3825** [comment]
My suggestions are almost updated except `ssh_port`. Would you approve it?

**Comment by 6543** [comment]
backport is already merged :/
I think for release candidate 2 we wont backport ...

@jeremy3825  but if you translate more stings ... it will be worth backporting for final release ...

**Comment by jeremy3825** [comment]
@6543 I know just a string is not enough for backport. I hope that `ssh_port` would be approved quickly and see it fixed on next version. Thanks a lot.

**Comment by jeremy3825** [comment]
Correct translation for `ssh_port` remains unapproved on Clowdin. I'd rather close this issue with merging the last one.

**Comment by jeremy3825** [comment]
Need approval : https://crowdin.com/translate/gitea/68/enus-ko#q=ssh_port

**Comment by sapk** [comment]
Done
