### ISSUE TITLE
[Bug] wrong link on issue/PR dependency cross reverence

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#9765]
noticed at version 1.11.0+dev-543-g134e3fdf3 (gitea.com)

when adding a issue dependency to a issue in a other repo, the link of the generated comment is wrong (it point to the actuall repo and not the referenced one)

below this comment: https://gitea.com/gitea/go-sdk/pulls/219#issuecomment-104990

**Comment by bhalbright** [comment]
I'd be happy to take a look at this if no one else is already doing it. I worked on the original PR so it was my oversight

**Comment by guillep2k** [comment]
> 
> 
> I'd be happy to take a look at this if no one else is already doing it. I worked on the original PR so it was my oversight

@bhalbright  Well be happy to see you happy! 😁

**Comment by 6543** [comment]
thanks @bhalbright
