### ISSUE TITLE
Filter locales under a certain percentage

### ISSUE THREAD

**Issue by sapk** [go-gitea/gitea#9779]
I suggest to filter locales under a certain percentage (25% at first) to remove empty translation file and provide a better experience. For exemple: https://github.com/go-gitea/gitea/blob/master/options/locale/locale_nb-NO.ini and https://github.com/go-gitea/gitea/blob/master/options/locale/locale_nn-NO.ini

This would need a change to simply compare line count between eu_US and each language and remove them before commit if needed. https://github.com/go-gitea/gitea/blob/master/.drone.yml#L384

To come back the translation will just have to go over threshold.

**Comment by bagasme** [comment]
@sapk translation threshold required is 25%, right?

**Comment by sapk** [comment]
Yes, I see that at a good start level

**Comment by lunny** [comment]
That percentage maybe inaccurate. We have to get that value via API of crowdin.

**Comment by sapk** [comment]
@lunny I feel like it would not be a big deal if we are 1% near and stay we a simple solution first. Furthermore, counting line it would be advantagous since there aare lines without translation (empty or group). The main goal is to first clear near empty translations that could be suggested in gitea.
