### ISSUE TITLE
Branch protection: Require branches to be up to date before merging

### ISSUE THREAD

**Issue by davidsvantesson** [go-gitea/gitea#9786]
Add a branch protection option allowing _strict_ status checks. PR shall not be possible to merge unless it is up to date (divergence behind target is zero).

**Comment by guillep2k** [comment]
Sounds like this should be added to #8659 ... should I?

**Comment by zeripath** [comment]
Yeah add it

**Comment by 6543** [comment]
hint: use function added via #9784 pull_service.GetDiverging(pull)
