### ISSUE TITLE
File encoding wrong in raw page and bleam page.

### ISSUE THREAD

**Issue by FalconWu2017** [go-gitea/gitea#9799]
- Gitea version (or commit ref):1.10.2
My file is GB2312,but raw page response UTF8 code .    
`Content-Type: text/plain; charset=utf-8`

![image](https://user-images.githubusercontent.com/34147999/72501336-7eead300-3871-11ea-9dc3-f206c5c0eaf7.png)

**Comment by zeripath** [comment]
The problem lies here:

https://github.com/go-gitea/gitea/blob/e1505d62507dde9694f87abe6f82a5887e3c12d8/routers/repo/download.go#L36

We need to then detect the charset using our chardet code.

**Comment by lunny** [comment]
@lafriks this should be backport to v1.10.3 so I marked it that milestone.
