### ISSUE TITLE
The font Lato does not support all characters

### ISSUE THREAD

**Issue by taai** [go-gitea/gitea#9801]
- Gitea version (or commit ref): 1.12.0+dev-80-g3f1e062d2

## Description
For issue titles the font [*Lato*](https://fonts.google.com/specimen/Lato) is being used. The problem is that this font does not support non-latin characters like "āčēģīķļņšūž" (these are used in Latvian alphabet).

The fonts that are defined in CSS for h1:
```Lato,-apple-system,BlinkMacSystemFont,system-ui,Segoe UI,Roboto,Helvetica,Arial,sans-serif```
Github uses:
```-apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif,Apple Color Emoji,Segoe UI Emoji```
...

## Screenshots

![image](https://user-images.githubusercontent.com/90734/72504627-d758ab00-3846-11ea-9fa4-f76a4543b579.png)

**Comment by lafriks** [comment]
we could probably try to change to `Roboto` font as it has much larger character set support:
![image](https://user-images.githubusercontent.com/165205/72508582-9bc1df00-384e-11ea-8276-9076d9799493.png)

**Comment by zeripath** [comment]
The latest lato on its website does support these glyphs. 

Either we don't have the latest lato or we have a smaller subset.

**Comment by lunny** [comment]
We have upgrade frmo v14 to v16 in a recent PR.

**Comment by zeripath** [comment]
I think we just have the Latin set rather than the Latin extended set.

**Comment by lafriks** [comment]
As visible on screenshot above even latin extended for Lato does not support these characters

**Comment by zeripath** [comment]
That's lato 1 not 2

**Comment by zeripath** [comment]
http://www.latofonts.com/lato-free-fonts/
