### ISSUE TITLE
Not create Initialize Repository

### ISSUE THREAD

**Issue by hexter2018** [go-gitea/gitea#9802]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description

...

## Screenshots

![3](https://user-images.githubusercontent.com/38841538/72511085-1a357580-387d-11ea-93de-a00733e865ee.png)
![2](https://user-images.githubusercontent.com/38841538/72511086-1ace0c00-387d-11ea-9c63-50f06ecc7609.png)
![1](https://user-images.githubusercontent.com/38841538/72511088-1ace0c00-387d-11ea-99f8-4a10da036f2e.png)

**Comment by zeripath** [comment]
Which version of Gitea?
Would it be possible to give us some of the preceding logs?
