### ISSUE TITLE
:

### ISSUE THREAD

**Issue by damianmoz** [go-gitea/gitea#9817]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

...

**Comment by 6543** [comment]
@damianmoz ?!?

**Comment by bagasme** [comment]
What the heck this? Spamming?
