### ISSUE TITLE
I cannot assign a user when creating a PR

### ISSUE THREAD

**Issue by gerdemann** [go-gitea/gitea#9824]
- Gitea version (or commit ref): 1.11.0+rc1
- Git version: n/a
- Operating system: n/a
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist: n/a

## Description

If a repository does not have its own issue tracker, you cannot select a user when creating a pull request. However, if the repository has an issue tracker, it works.

**Comment by 6543** [comment]
ah ... saw this code - I'll take a look at

**Comment by 6543** [comment]
fix is here: #9836

**Comment by lunny** [comment]
This should also affect v1.10.

**Comment by gerdemann** [comment]
This is maybe a similar bug:
https://github.com/go-gitea/gitea/issues/6039

**Comment by 6543** [comment]
dont think so
