### ISSUE TITLE
Clone via SSH with Git_for_Windows

### ISSUE THREAD

**Issue by anatanna** [go-gitea/gitea#9829]
- Gitea version (or commit ref): 1.10.2 / binary installation
- Git version: 2.8.4-1.el7.centos and 2.25.0.windows.1
- Operating system: CentOS 7 and Windows10
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
Connected to [Cannot clone via Gitea Internal SSH Server #9697](https://github.com/go-gitea/gitea/issues/9697) which was closed due to new  conditions in basement.

I use Gitea buildin SSH server on local Gitea server. START_SSH_SERVER = true.

I test to run `git clone` from linux/CentOS and Windows10 with Git for Windows package(latest version).

Results:
Both from local Gitea server and from try.gitea.com i do **can** clone repo from _CentOS client_ via **ssh**.
Both from local Gitea server and from try.gitea.com i can **NOT** clone repo from _Windows client_ via **ssh**.
Both from local Gitea server and from try.gitea.com i do **can** clone repo from CentOS client and Windows client via **http**.
I do **can** clone repo from other servers via **ssh**: bitbucket.org and local bitbucket server with build-in SSH (nb: non OpenSSH on port 22) from _Windows client._

As it goes to reproduce with try.gitea.io, suppose it not relevant what is in my gitea config.

With git_for_windows cloning from Gitea server freezing after key confirmation.

## Screenshots
To the left - CentOS client , to the right - Windows Client
![image](https://user-images.githubusercontent.com/31313668/72608801-d6497b80-3923-11ea-9ce1-bea63ed3e97b.png)

**Comment by lunny** [comment]
Cannot reproduce this on windows7

**Comment by anatanna** [comment]
Two Windows instances: the same behavior .
![image](https://user-images.githubusercontent.com/31313668/72617207-c5efcb80-3938-11ea-80f9-3617d59927db.png)

**Comment by iamdoubz** [comment]
For me, I always get this if I don't start the ssh-agent and add my private key to it every restart on my Windows 10 Pro v18363.535 using git v2.25.0.windows.1.

### Steps

1. Start the agent: `eval $(ssh-agent -s)`

2. Add the key: `ssh-add C:\Users\%username%\.ssh\id_rsa`

**Comment by anatanna** [comment]
ssh-agent started. See first screenshot - i can clone via ssh from other server- Bitbucket.

**Comment by iamdoubz** [comment]
So, it appears you aren't using git but putty? The reason I ask because when I go to add the fingerprint of try.gitea.io, I have to type `yes` not `y`. I am using [git-scm](https://git-scm.com/download/win "Git it") and it clones just fine after I added my public key to the site and started the ssh-agent and added my private key to it...

![gitea_windows_ssh](https://user-images.githubusercontent.com/4871781/72622665-50b8d200-3909-11ea-88a5-d2b264f8bd1f.png)

**Comment by guillep2k** [comment]
> 
> 
> So, it appears you aren't using git but putty?

Maybe you meant "_bash_ but putty"?

Anyway, I had problems before when my URLs didn't have the `ssh:` prefix, which is what Bitbucket URLs seem to have, but not Gitea's. But it was really something in my Windows configuration (don't remember what it was.... I googled the solution at the time).

**Comment by anatanna** [comment]
@iamdoubz 
1) ssh key uploaded 
2) i get host ssh key  via `ssh git@try.gitea.io` command
   Result: 
   _Warning: Permanently added 'try.gitea.io,167.99.148.217' (ECDSA) to the list of known hosts.
PTY allocation request failed on channel 0
   Hi there, anatanna! **You've successfully authenticated** with the key named anatanna..._
3) try to clone git clone git@try.gitea.io:fmajesty/test.git  -- freezing
4) try to clone git clone **ssh**://git@try.gitea.io:fmajesty/test.git  -- freezing

![image](https://user-images.githubusercontent.com/31313668/72650391-ae3c3580-3980-11ea-9922-013bcd2bcabd.png)

I clone without any problem via ssh from other servers- that means that my key is uploaded and "plays the game".

**Comment by anatanna** [comment]
Solved

git-scm & putty issue: before clone `plink git@scm.example.com -P 2222 ls`  must be run ( `plink git@try.gitea.io ls` in case of try.gitea.io) to add correctly to putty cash in windows registry.
