### ISSUE TITLE
Endpoint suggestions:  /repos/{owner}/{repo}/issue_times and /repos/{owner}/{repo}/issue_labels

### ISSUE THREAD

**Issue by Breee** [go-gitea/gitea#9839]
## Description
If you want to get times for an issue you have to call `/repos/{owner}/{repo}/issues/{id}/times`
If you do this for alot of issues, it takes literally ages because of the high amount of requests, 
In our case it takes ~20 minutes to fetch all times of all issues.

I suggest to introduce a new endpoint `/repos/{owner}/{repo}/issue_times`,
which returns all issues (or just their IDs) and the times tied to it.  

The same for `/repos/{owner}/{repo}/issue_labels`. 

I would find this useful, to reduce API calls and save alot of time, because the backend can prepare such an response really fast.

**Comment by 6543** [comment]
@Breee the times api was extended at #9200 and #9373 (first is included in 1.11.0, second will be in 1.12.0)

**Comment by 6543** [comment]
@Breee I think you use 1.10.x right now?

**Comment by Breee** [comment]
@6543 Thx! <3
