### ISSUE TITLE
Milestone: 500er error

### ISSUE THREAD

**Issue by somera** [go-gitea/gitea#9841]
- Gitea version (or commit ref): 1.11.0+rc1-31-gfe4618540
- Git version: 2.20.1
- Operating system: Linux pi-manager 4.19.75-v7l+ #1270 SMP Tue Sep 24 18:51:41 BST 2019 armv7l GNU/Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

2020/01/17 16:40:59 .../xorm/session_raw.go:76:queryRows() [I] [SQL] SELECT repo_id AS repo_id, COUNT(*) AS count FROM `milestone` WHERE (is_closed = ?) AND `repo_id` IN (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) GROUP BY repo_id []interface {}{false, 3, 3, 4, 4, 5, 5, 6, 6, 9, 9, 13, 13, 14, 14, 19, 19, 23, 23, 25, 25, 26, 26, 27, 27, 28, 28, 29, 29, 32, 32, 33, 33, 34, 34, 35, 35, 37, 37, 39, 39, 41, 41, 43, 43, 47, 47, 48, 48, 50, 50, 51, 51, 54, 54, 58, 58, 59, 59, 60, 60, 61, 61, 62, 62, 64, 64, 65, 65, 80, 80, 84, 84, 85, 85, 87, 87, 90, 90, 95, 95, 97, 97, 98, 98, 111, 111, 112, 112, 114, 114, 117, 117, 118, 118, 119, 119, 120, 120, 121, 121, 124, 124, 126, 126, 127, 127, 129, 129, 131, 131, 132, 132, 133, 133, 134, 134, 135, 135, 140, 140, 147, 147, 153, 153, 156, 156, 166, 166, 168, 168, 171, 171, 174, 174, 175, 175, 176, 176, 177, 177, 178, 178, 185, 185, 195, 195, 197, 197, 200, 200, 207, 207, 208, 208, 209, 209, 210, 210, 215, 215, 225, 225, 234, 234, 236, 236, 237, 237, 241, 241, 253, 253, 254, 254, 258, 258, 262, 262, 264, 264, 265, 265, 268, 268, 269, 269, 270, 270, 276, 276, 278, 278, 279, 279, 280, 280, 281, 281, 292, 292, 294, 294, 296, 296, 297, 297, 298, 298, 304, 304, 306, 306, 312, 312, 323, 323, 326, 326, 329, 329, 330, 330, 331, 331, 333, 333, 334, 334, 336, 336, 339, 339, 340, 340, 341, 341, 343, 343, 354, 354, 359, 359, 360, 360, 361, 361, 362, 362, 363, 363, 372, 372, 374, 374, 379, 379, 380, 380, 381, 381, 382, 382, 383, 383, 384, 384, 385, 385, 386, 386, 387, 387, 392, 392, 393, 393, 394, 394, 399, 399, 400, 400, 402, 402, 403, 403, 405, 405, 406, 406, 407, 407, 408, 408, 409, 409, 411, 411, 413, 413, 415, 415, 416, 416, 417, 417, 421, 421, 423, 423, 428, 428, 429, 429, 430, 430, 438, 438, 445, 445, 451, 451, 455, 455, 457, 457, 459, 459, 462, 462, 470, 470, 471, 471, 475, 475, 483, 483, 484, 484, 485, 485, 487, 487, 488, 488, 490, 490, 491, 491, 492, 492, 497, 497, 500, 500, 501, 501, 510, 510, 514, 514, 515, 515, 518, 518, 520, 520, 521, 521, 528, 528, 531, 531, 533, 533, 534, 534, 538, 538, 542, 542, 547, 547, 560, 560, 561, 561, 568, 568, 570, 570, 573, 573, 574, 574, 576, 576, 595, 595, 615, 615, 658, 658, 659, 659, 707, 707, 708, 708, 709, 709, 798, 798, 2, 8, 10, 11, 12, 15, 17, 18, 20, 21, 22, 24, 30, 31, 36, 38, 40, 42, 44, 45, 46, 49, 52, 53, 63, 66, 67, 68, 69, 70, 72, 73, 74, 75, 76, 77, 78, 79, 81, 82, 86, 88, 89, 91, 92, 93, 94, 96, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 113, 115, 116, 122, 123, 125, 128, 130, 136, 137, 138, 139, 141, 142, 143, 144, 145, 146, 148, 149, 150, 151, 152, 154, 155, 157, 158, 159, 160, 161, 163, 164, 165, 167, 169, 170, 173, 179, 180, 181, 182, 183, 184, 186, 189, 190, 191, 192, 193, 194, 196, 198, 199, 201, 202, 203, 204, 205, 206, 211, 212, 213, 214, 216, 218, 219, 220, 221, 222, 223, 224, 226, 227, 228, 229, 230, 231, 232, 233, 235, 238, 239, 240, 242, 243, 244, 245, 247, 248, 249, 250, 251, 252, 255, 256, 259, 260, 261, 263, 266, 272, 274, 275, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 293, 295, 299, 300, 301, 302, 303, 305, 307, 308, 309, 310, 311, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 324, 325, 327, 328, 332, 335, 337, 338, 342, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 355, 356, 357, 358, 364, 365, 366, 367, 368, 370, 371, 373, 376, 377, 378, 388, 389, 390, 391, 395, 396, 398, 401, 404, 410, 412, 414, 418, 419, 420, 422, 424, 425, 426, 427, 431, 432, 434, 435, 436, 437, 439, 440, 441, 442, 444, 446, 447, 448, 449, 450, 452, 453, 454, 456, 458, 460, 461, 463, 464, 465, 466, 467, 468, 469, 472, 473, 474, 476, 477, 478, 479, 480, 481, 482, 486, 489, 493, 494, 495, 496, 498, 499, 502, 503, 504, 505, 506, 507, 508, 509, 511, 516, 517, 519, 523, 524, 525, 526, 527, 529, 530, 532, 535, 536, 537, 539, 540, 541, 543, 544, 545, 546, 548, 550, 552, 553, 554, 555, 556, 557, 558, 559, 562, 563, 564, 565, 566, 567, 569, 571, 572, 575, 577, 578, 579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591, 592, 594, 596, 597, 598, 599, 600, 601, 602, 603, 604, 605, 606, 607, 608, 609, 610, 611, 612, 613, 614, 616, 617, 618, 619, 620, 621, 622, 623, 625, 626, 627, 628, 629, 630, 631, 632, 633, 634, 635, 636, 637, 638, 639, 640, 641, 642, 643, 644, 646, 647, 648, 649, 650, 651, 652, 653, 654, 655, 656, 657, 660, 661, 663, 664, 665, 666, 667, 668, 669, 670, 671, 672, 673, 674, 675, 676, 677, 678, 679, 680, 681, 682, 683, 684, 685, 686, 687, 688, 689, 690, 691, 692, 693, 694, 695, 696, 697, 698, 699, 700, 701, 702, 703, 704, 705, 706, 710, 711, 712, 713, 714, 715, 716, 717, 718, 719, 720, 722, 724, 725, 726, 727, 728, 729, 730, 731, 732, 733, 734, 735, 736, 737, 738, 739, 740, 741, 742, 743, 744, 745, 746, 747, 748, 749, 750, 751, 752, 753, 755, 756, 757, 759, 760, 761, 762, 763, 764, 765, 767, 768, 769, 770, 771, 772, 773, 774, 775, 776, 777, 778, 779, 780, 781, 782, 783, 784, 785, 786, 787, 788, 789, 790, 791, 792, 793, 794, 797, 799, 800, 801, 802, 803, 804, 805, 806, 807, 808, 809, 810, 812, 813, 814, 815, 816, 817, 818, 820, 821, 822, 823, 824, 827, 828, 829, 830, 831, 832, 833, 834, 835, 836, 837, 838, 839, 840, 841, 842, 843, 844, 845, 846, 847, 848, 849, 850, 851, 852, 853, 854, 855, 856, 857, 858, 859, 860, 861, 862, 863, 864, 865, 866, 867, 868, 869, 870, 871, 872, 873, 874, 875, 876, 877, 878, 879, 880, 882, 883, 884, 885, 886, 887, 888, 889, 890, 891, 892, 893, 894, 895, 897, 898, 899, 900, 901, 902, 903, 904, 905, 906, 907, 908, 909, 910, 911, 913, 914, 915, 916, 917, 918, 919, 920, 921, 922, 923, 924, 925, 926, 927, 928, 929, 930, 931, 932, 933, 934, 935, 936, 938, 939, 940, 941, 942, 943, 944, 945, 946, 947, 948, 949, 950, 951, 952, 953, 954, 955, 956, 957, 958, 959, 960, 961, 962, 963, 964, 965, 966, 967, 968, 969, 970, 971, 972, 973, 974, 975, 976} - took: 909.721µs
2020/01/17 16:40:59 routers/user/home.go:240:Milestones() [E] CountMilestonesByRepoIDs: too many SQL variables
2020/01/17 16:40:59 ...s/context/context.go:139:HTML() [D] Template: status/500

## Description

...

**Comment by guillep2k** [comment]
This is a good candidate for being solved by #9787 😄

**Comment by davidsvantesson** [comment]
It is a sqlite limitation, SQLITE_MAX_VARIABLE_NUMBER=999, which seem to be hard-coded so it can only be changed by re-compiling sqlite.
As it would require substantial re-write to fix I am sceptical about a fix towards 1.11.X. If we go for #9787 I thing this issue can be solved with that.

**Comment by somera** [comment]
> It is a sqlite limitation, SQLITE_MAX_VARIABLE_NUMBER=999, which seem to be hard-coded so it can only be changed by re-compiling sqlite.
> As it would require substantial re-write to fix I am sceptical about a fix towards 1.11.X. If we go for #9787 I thing this issue can be solved with that.

Or you can rewrite this query (inner join)?

**Comment by lunny** [comment]
We should use a sub query but not in to resolve the problem.

**Comment by guillep2k** [comment]
The logic for this query is currently very complex. A temporary table would solve this in an easy-to-backport way. I'm afraid #9787 will be too complex and too big of a change to backport to 1.11.

**Comment by somera** [comment]
Hi, in which version it will be fixed?

In Version: 1.11.0+10-gf9e66e5a4 it's not working.

**Comment by guillep2k** [comment]
Fixed by #10880 and #10904
