### ISSUE TITLE
Interface or css bug

### ISSUE THREAD

**Issue by Aryesia** [go-gitea/gitea#9845]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

> 2020/01/18 00:56:41 ...dules/setting/log.go:273:newLogService() [I] Gitea Log Mode: File(File:info)
> 2020/01/18 00:56:41 ...les/setting/cache.go:45:newCacheService() [I] Cache Service Enabled
> 2020/01/18 00:56:41 ...s/setting/session.go:44:newSessionService() [I] Session Service Enabled
> 2020/01/18 00:56:41 routers/init.go:51:initDBEngine() [I] Beginning ORM engine initialization.
> 2020/01/18 00:56:41 routers/init.go:53:initDBEngine() [I] ORM engine initialization attempt #1/10...
> 2020/01/18 00:56:41 ...orm@v0.7.9/engine.go:330:Ping() [I] PING DATABASE sqlite3
> 2020/01/18 00:56:41 models/models.go:180:NewEngine() [W] Table repository Column original_service_type db default is 0, struct default is 
> 2020/01/18 00:56:41 routers/init.go:86:GlobalInit() [I] ORM engine initialization successful!
> 2020/01/18 00:56:41 routers/init.go:111:GlobalInit() [I] SQLite3 Supported
> 2020/01/18 00:56:41 routers/init.go:39:checkRunMode() [I] Run Mode: Production
> 2020/01/18 00:56:44 cmd/web.go:151:runWeb() [I] Listen: unix:///run/gitea/gitea.socket
> 2020/01/18 00:56:44 cmd/web.go:154:runWeb() [I] LFS server enabled

## Description

Hello! I have interface or css bug. As seen in the screenshot. So on all pages. It started spontaneously. I tried reinstalling, but the problem remained. Help me please

## Screenshots
![Screenshot_20200118_005713](https://user-images.githubusercontent.com/55660158/72634768-d3837080-398d-11ea-9193-62f03edf1e72.png)

**Comment by guillep2k** [comment]
Which Gitea version? Are you using custom templates? What page are you currently looking at?

**Comment by 6543** [comment]
are you behind a reverse proxy?

**Comment by Aryesia** [comment]
> Which Gitea version? Are you using custom templates? What page are you currently looking at?

Gitea version 1.10.2 built with GNU Make 4.2.1, go1.13.5 : bindata, sqlite, pam

No, standart theme and standart templates. Main page after authorization

**Comment by Aryesia** [comment]
> are you behind a reverse proxy?

Yes. I use Cloudflare

**Comment by 6543** [comment]
this may cause it ...

**Comment by 6543** [comment]
@Aryesia there is a config option so serve css/js files via CDN:
https://docs.gitea.io/en-us/config-cheat-sheet/#server-server **STATIC_URL_PREFIX**

**Comment by Aryesia** [comment]
> @Aryesia there is a config option so serve css/js files via CDN:
> https://docs.gitea.io/en-us/config-cheat-sheet/#server-server **STATIC_URL_PREFIX**

Sorry, I don’t understand how the line should look exactly "STATIC_URL_PREFIX" for cloudflare. Can you help me?

**Comment by 6543** [comment]
I dont use / know well cloudflate ... I sugest asking on discord https://discordapp.com/invite/NsatcWJ there is perhaps a other user/maintainer who have a setup running with cloudflare

one thing: i remeber me correctly about cloudflair: with this setup ssh clone/pull/push wont work :/

**Comment by lunny** [comment]
@Aryesia If you don't know what that is, you could leave it blank.

**Comment by 6543** [comment]
@lunny issue is that @Aryesia like to setup gitea behind cloudflare - and at the moment CSS is not loading proberly

**Comment by lunny** [comment]
For CDN, I think gitea.com has done that. It works.

**Comment by techknowlogick** [comment]
It could be that cloudflare has cached incorrect information. Please try suggestions above about setting STATIC_URL_PREFIX to blank. For now I will close this issue, please comment/re-open issue if you have more information.
