### ISSUE TITLE
[Feature] Option to force login on API

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#9846]
as title ...
= allow no anon requests

* I only like to exclude the version api from this ... (so clients can determine gitea version befor login)

**Comment by techknowlogick** [comment]
This already exists with `REQUIRE_SIGNIN_VIEW`

**Comment by 6543** [comment]
@techknowlogick 
O did a lookup on https://docs.gitea.io/en-us/config-cheat-sheet/ but there is no description that this also limit API :/
