### ISSUE TITLE
[Proposal]: ability to generate ports to other branches

### ISSUE THREAD

**Issue by guillep2k** [go-gitea/gitea#9852]
It would be cool for a merged PR that there would be a `[Generate port]` button to create a backport/frontport of the merged commit on another branch.

**Comment by guillep2k** [comment]
In addition, the PR would have some visual cue that the port is faithful.

This would only work for ports that generate no conflicts, and of course they need to pass the revision process because ports may cause problems even if they merge cleanly.

**Comment by zeripath** [comment]
I'm actually thinking it would be good for us to have a way of importing a patch to or as a branch.

If we have that, then lots of things can hang off that base code.

**Comment by 6543** [comment]
`git apply` **patchfile**

**Comment by 6543** [comment]
@zeripath but before this #9014 should be implemented ...

**Comment by lunny** [comment]
I think it's a duplicate of #3880

**Comment by guillep2k** [comment]
> 
> 
> I think it's a duplicate of #3880

Your right. Closing this.

**Comment by zeripath** [comment]
@6543 I suspect they might need each other
