### ISSUE TITLE
Repository tab order and positions

### ISSUE THREAD

**Issue by gsantner** [go-gitea/gitea#986]
**Note: Copy of Gogs Issue No 3518 created by me - Screenshots misses some options**

- Gitea version: 1.1.0+dev
- Git version: 2.1.4
- Operating system: Deb 8
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:
## Description

Please move the tab "Commits"  and "Releases" to the row of the branches. 
I'm always spending some time looking for the commits tab, because every GitHub and GitLab have Branches and Commits on the same (bottom) line.

Old Current:
![bildschirmfoto von 2016-08-26 09-48-03](https://cloud.githubusercontent.com/assets/6735650/17998123/126f9914-6b73-11e6-9669-20edfaad8ecb.png)

Old Expected:
![bildschirmfoto von 2016-08-26 09-48-03 kopie](https://cloud.githubusercontent.com/assets/6735650/17998127/1af1f438-6b73-11e6-8c15-2865e28fa49a.png)

Just for ref: (GitHub)
![grafik](https://cloud.githubusercontent.com/assets/6735650/23108911/13e5e172-f714-11e6-8d94-669165ea554d.png)

Just for ref: (GitLab)
![bildschirmfoto von 2016-08-26 09-56-06](https://cloud.githubusercontent.com/assets/6735650/17998270/c6b93416-6b73-11e6-99ac-6fc45c4cc94a.png)

Please lets discuss about this. I would really appreciate if this would be done, and would save me and other people working on my gitea some time.

**Comment by lunny** [comment]
Commits should be moved, but releases could keep it position.
