### ISSUE TITLE
Witch version to use?

### ISSUE THREAD

**Issue by BaxAndrei** [go-gitea/gitea#9860]
Currently I am using: gitea-1.11.0-rc1-linux-amd64, but recently I received some kind of notification about a new version, version gitea-1.10.3-linux-amd64.. so which one to use?

**Comment by jolheiser** [comment]
`1.11.0-rc1` is a release candidate for `1.11.0` and `1.10.3` is the latest 1.10.x release.

The one you are currently on has more features, but isn't a full release (yet)

**Comment by baxandrei** [comment]
Ok, thanks!
