### ISSUE TITLE
[Feature] Option to Disable Built-in Log Rotation

### ISSUE THREAD

**Issue by bagasme** [go-gitea/gitea#9869]
## Description

In #9866 @zeripath points that Gitea have built-in log rotation. To ensure that external, similar tools (like `logrotate`) doesn't interfere with Gitea's one, the option to disable built-in log rotation should be added.

**Comment by zeripath** [comment]
https://docs.gitea.io/en-us/config-cheat-sheet/#file-log-mode-log-file-log-file-or-mode-file
