### ISSUE TITLE
[Feature] for doctor framewrok

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#9878]
let gitea repair hooks based on current binary executing path & app.ini settings ...

**Comment by jolheiser** [comment]
I think this is what `Resynchronize pre-receive, update and post-receive hooks of all repositories.` does?

**Comment by techknowlogick** [comment]
CLI currently has the following commands which would resynch keys and hooks, maybe doctor would alert user that they would need to run the following?
```
    gitea admin regenerate hooks
    gitea admin regenerate keys
```

**Comment by guillep2k** [comment]
I think it would be cool if the doctor performed all of those functions by itself as part of its diagnostics/repair procedure. Unless there's some reason for not doing that, of course. We could add flags like `--repair-all` in case we don't want some destructive step to run by default.
