### ISSUE TITLE
Statics build failed

### ISSUE THREAD

**Issue by hexter2018** [go-gitea/gitea#9887]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description

...

## Screenshots

![Capture](https://user-images.githubusercontent.com/38841538/72698469-e86f2800-3b76-11ea-9a73-2606d00d5a63.PNG)

**Comment by lunny** [comment]
For v1.10 or before, you should use `TAGS="bindata sqlite" make generate build`.
From v1.11, you could use `TAGS="bindata sqlite" make build` and `TAGS="bindata sqlite" make generate build` is also work.

**Comment by hexter2018** [comment]
> For v1.10 or before, you should use `TAGS="bindata sqlite sqlite_unlock_notify" make generate build`.
> From v1.11, you could use `TAGS="bindata sqlite" make build` and `TAGS="bindata sqlite sqlite_unlock_notify" make generate build` is also work.

Thx. bro.
