### ISSUE TITLE
Unable to push / create a new intialized repo etc.

### ISSUE THREAD

**Issue by pzduniak** [go-gitea/gitea#989]
- Gitea version (or commit ref): c5f8b96ddaefe83eb87a71a44c46cc13cc7130fa
- Git version: docker image / 2.10.2.windows.1
- Operating system: ubuntu 16.04.1 running docker / windows 10
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist: there's barely anything so I put it in the contents.

## Description

push / clone / pull - fatal: Could not read from remote repository with no output +
```
eb 20 16:31:32 sshd[134]: Accepted publickey for git from x port 52917 ssh2: RSA y
Feb 20 16:31:32 sshd[134]: Received disconnect from x port 52917:11: disconnected by user
Feb 20 16:31:32 sshd[134]: Disconnected from x port 52917
```

creating a new repo - http500 +
```
remote: error: hook declined to update refs/heads/master
To /data/git/repositories/pzduniak/smh.git
 ! [remote rejected] master -> master (hook declined)
error: failed to push some refs to '/data/git/repositories/pzduniak/smh.git'
```

**Comment by pzduniak** [comment]
Reinstalling it did not fix anything. It worked earlier, I did not change anything really.

**Comment by pzduniak** [comment]
I tested out with 252adc912dfdcfb4e4d235a020844db351556d84 and it works again. Breaking change happened somewhere inbetween.

**Comment by pzduniak** [comment]
04fdeb9d8d4dc3cf296d8354ee29f1d053154a54
c5f8b96ddaefe83eb87a71a44c46cc13cc7130fa

either of these commits, another error i saw was "xorm mode file invalid" or sth along the lines

**Comment by lunny** [comment]
duplicated with #988
