### ISSUE TITLE
Reply Button Not Working (Pull Request - File Changed - Split View)

### ISSUE THREAD

**Issue by cloudlakecho** [go-gitea/gitea#9891]
- Gitea version (or commit ref): 1.10.1. 
- Git version:
- Operating system: Ubuntu 16.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

Example URL: https://try.gitea.io/choiip/test_repo/pulls/3/files?style=split&whitespace=

## Description

I couldn't use the Reply button on Split View - File Changed - Pull Request section. 

When I click Reply button, it doesn't put information. I tried on version 1.10.1. and Test Instance.
...

## Screenshots
![image](https://user-images.githubusercontent.com/12093406/72742394-7985d500-3b5e-11ea-83b3-f8ca56074738.png)

**Comment by lunny** [comment]
It seems v1.10 don't have reply button?

**Comment by cloudlakecho** [comment]
I am using 1.10.1 and there is Reply button in Split View tab. Please, check.
