### ISSUE TITLE
Can't set organization on create / migrate repository

### ISSUE THREAD

**Issue by camlafit** [go-gitea/gitea#9892]
Hello

- Gitea version (or commit ref): 1.10.3
- Git version:
- Operating system: Debian
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:
Not relevant
## Description

When an user want add a new project. He can only himself as owner.
This account is set in different organization in a specific team with write right

An account in owner team can do it.

**Comment by bagasme** [comment]
@camlafit any error messages on your case?

**Comment by lunny** [comment]
Teams with write permissions are not allowed to create repository. `Create Repository` is a standalone permission on team settings.

**Comment by camlafit** [comment]
Hello

I don't see "create repository" option in team management. Maybe it's here my problem.

![Capture d’écran de 2020-01-27 09-59-55](https://user-images.githubusercontent.com/209915/73161503-f0394a00-40eb-11ea-9f08-f9978be65a43.png)

**Comment by 6543** [comment]
@camlafit 
![Bildschirmfoto zu 2020-01-27 10-39-56](https://user-images.githubusercontent.com/24977596/73164073-7a37e180-40f1-11ea-90c8-96fd48851195.png)

on master branch ... so I think this is a **feature** of `1.11.0` ...

**Comment by 6543** [comment]
@camlafit and pleace make screenshots in Lang=ENG ... i only can guess what this means (created my screenshot in your lang because I was comparing if I'm looking at the same as you)

**Comment by camlafit** [comment]
Hello

Yes sorry I've forgotten to set in english. I've not this reflex to update my language. I do it the next time.

**Comment by camlafit** [comment]
Hello

I've updated to 1.11.0 rc2 and indeed options are now present. Then we can forget this issue :)
Thanks a lot.
