### ISSUE TITLE
Emoji in review comments not rendering

### ISSUE THREAD

**Issue by my1e5** [go-gitea/gitea#9895]
- Gitea version (or commit ref): 1.12.0
- Git version:
- Operating system: ubuntu
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL) https://try.gitea.io/my1e5_test/Emoji-In-Review/pulls/1
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

If you add an emoji to a review comment, it will not render on the pull request page.

However, on the Dashboard, the emoji do appear.

#### :camel: (`:camel:`) isn't rendered on pull request page
![image](https://user-images.githubusercontent.com/10064103/72745318-664b2780-3ba7-11ea-8d58-3082f3eddd3b.png)

#### On Dashboard it does appear though
![image](https://user-images.githubusercontent.com/10064103/72745452-b3c79480-3ba7-11ea-9f76-01d41467fe6b.png)

**Comment by guillep2k** [comment]
It's working for me in try (1.12.0+dev-249-g3ff95cef6):

https://try.gitea.io/guillep2k/charset-problem/pulls/2/files#issuecomment-25926

![image](https://user-images.githubusercontent.com/18600385/73705368-8c5ae680-46d4-11ea-8f46-38e8d93d0bf9.png)
