### ISSUE TITLE
Automatically generated commit message when merging pull request is not clear

### ISSUE THREAD

**Issue by my1e5** [go-gitea/gitea#9898]
- Gitea version (or commit ref): 1.12.0
- Git version:
- Operating system: ubuntu
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL) https://try.gitea.io/my1e5_test/Merge-Pull-Request/pulls/1
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

When merging a pull request, Gitea automatically generates text for the commit message. It has the following format:

`TITLE`: Merge pull request '`pull-request-name`' (#`pull-request-number`) from `branch` into `branch`

`CONTENT`: Reviewed-on: `url-of-pull-request`

However, I've noticed a potential bug with the way it constructs the branch names. The first branch name is structured like:

`organisation-name/branch-name`

when I think it should be

`organisation-name/repo-name/branch-name` OR just `branch-name`

See the try.gitea example repo and the screenshots below for examples of this.

## Screenshots

Organisation: `my1e5_test`
Repo: `Merge-Pull-Request`
Branch: `feature/my_branch`

I use a folder structure for my branch name. I am merging into `master`.

![image](https://user-images.githubusercontent.com/10064103/72746903-32720100-3bab-11ea-83e3-5c906177e808.png)

Notice how it says "from my1e5_test/feature/my_branch into master".

In my opinion this is not accurate. It should be just "from feature/my_branch into master" OR it should be "from my1e5_test/Merge-Pull-Request/feature/my_branch into master".

Missing out the repo name, but having the organisation name, is strange IMO.

**Comment by my1e5** [comment]
The relevant section of code is in `pull.go`:

```go
// GetDefaultMergeMessage returns default message used when merging pull request
func (pr *PullRequest) GetDefaultMergeMessage() string {
	if pr.HeadRepo == nil {
		var err error
		pr.HeadRepo, err = GetRepositoryByID(pr.HeadRepoID)
		if err != nil {
			log.Error("GetRepositoryById[%d]: %v", pr.HeadRepoID, err)
			return ""
		}
	}
	if err := pr.LoadIssue(); err != nil {
		log.Error("Cannot load issue %d for PR id %d: Error: %v", pr.IssueID, pr.ID, err)
		return ""
	}
	return fmt.Sprintf("Merge pull request '%s' (#%d) from %s/%s into %s", pr.Issue.Title, pr.Issue.Index, pr.MustHeadUserName(), pr.HeadBranch, pr.BaseBranch)
}
```

**Comment by lunny** [comment]
It should know the PR is from the same repository or a forked repository.

**Comment by lafriks** [comment]
Also it should really exclude merge commits and commits that merge commit includes
