### ISSUE TITLE
Ability to Modify Archive Download Structure

### ISSUE THREAD

**Issue by ArctoranDev** [go-gitea/gitea#9903]
Basically just want to package repo contents directly inside a zip for the download rather than inside a folder inside the zip.

**Comment by zeripath** [comment]
I am guessing this should be a per repository option - rather than a per download option?

Whilst we are at it we should probably just create our own archive command so that LFS files get properly brought in too.

That means it's a gonna end up being a 1.12 feature.

**Comment by guillep2k** [comment]
If changes are being considered, I'd like to suggest some filter as well:

```
git archive --remote={remoteaddr} {ref} '*/*.css' '*/*.js'
```

Problem is that `git archive` doesn't like when any of the patterns matches no files.

**Comment by zeripath** [comment]
Users can already set things in the gitattributes to avoid exporting certain files.

(In reality of course we have to completely rewrite this command as it doesn't work with LFS without a full checkout - which is something we need to avoid.)

**Comment by randyesq** [comment]
+1 for this feature request, but want to mention that it should be possible to do this for both the ZIP and TAR.GZ options. My use case is the ansible-galaxy client, which assumes no encapsulating directory, and only supports gzipped, tarballs (and not zip files).
