### ISSUE TITLE
Three dots in URLs are converted to HORIZONTAL ELLIPSIS unicode character

### ISSUE THREAD

**Issue by WGH-** [go-gitea/gitea#9904]
- Gitea version (or commit ref): 1.12.0+dev-135-g9bc841353 and 1.10.2
- Git version: N/A
- Operating system: GNU/Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes: https://try.gitea.io/WGH/Test/issues/1
  - [ ] No
  - [ ] Not relevant

## Description

URLs with three dots (like the compare links) are rendered with three dots replaced with HORIZONTAL ELLIPSIS Unicode characters, breaking links.

E.g. `https://try.gitea.io/WGH/Test/compare/master...7bc715de69acad8917132a5095d1deac46582d02`  becomes broken https://try.gitea.io/WGH/Test/compare/master%E2%80%A67bc715de69acad8917132a5095d1deac46582d02

## Workaround

Use explicit Markdown links:
```markdown
[https://try.gitea.io/WGH/Test/compare/master...7bc715de69acad8917132a5095d1deac46582d02](https://try.gitea.io/WGH/Test/compare/master...7bc715de69acad8917132a5095d1deac46582d02)
```

**Comment by jolheiser** [comment]
My guess is this is caused by smartypants, I'll take a look.
