### ISSUE TITLE
How to install gitea?

### ISSUE THREAD

**Issue by DiFinedZ** [go-gitea/gitea#991]
System: ubuntu 16.04

Currently run by a ./gitea web

How to automate the startup process?

**Comment by plessbd** [comment]
How do I run Gitea at startup with Systemd?

There’s a systemd service template file in the Gitea GitHub repository https://github.com/go-gitea/gitea/blob/master/scripts/systemd/gitea.service

    Update User, Group, WorkingDirectory, ExecStart, and Environment with values appropriate to your Gitea installation.
    (Optional) If you would like to use Gitea with MySQL/MariaDB, PostgreSQL, Redis, or memcached then uncomment the appropriate After lines.

Save your modified service file at /etc/systemd/system/gitea.service, enable it with sudo systemctl enable gitea, and start it with sudo systemctl start gitea.

You can check the status of the Gitea service with sudo systemctl status gitea -l, or display the journal entries with sudo journalctl -b -u gitea.

*shamelessly pulled from https://gogs.io/docs/intro/faqs *
