### ISSUE TITLE
Gitea version update

### ISSUE THREAD

**Issue by paulocarvalho2899** [go-gitea/gitea#9913]
https://github.com/go-gitea/gitea/blob/8cb9b2f016f0a5c1aa3e907d4d6640c3c9ba5d57/main.go#L32

Hi, I was updating my gitea server and I noticed that my gitea version didn't change. After some tests and insistence I assumed that the "problem" was in the code. So I searched and found in the main.go file, which was not being maintained the version parameter.

**Comment by 6543** [comment]
@paulocarvalho2899 do you build the software yourself ?

**Comment by paulocarvalho2899** [comment]
Yes, I execute the command "go build" (I don't know if I'm supposed to change the version, is it?)

**Comment by 6543** [comment]
@paulocarvalho2899 you should use **make**: https://docs.gitea.io/en-us/install-from-source/#build  
or set (on compilation):
https://github.com/go-gitea/gitea/blob/5cf241b3123a6096076a9cb582d28fb8919969e0/Makefile#L44

**Comment by paulocarvalho2899** [comment]
@6543 thanks :)
