### ISSUE TITLE
The command "git lfs locks" never returns if credentials are invalid.

### ISSUE THREAD

**Issue by rainwf** [go-gitea/gitea#9915]
- Gitea version (or commit ref):1.10.3 
- Git version: 2.20.1.windows.1
- Operating system: Windows 10 client, Windows Server 2012-R2 server
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [X ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X ] No
  - [ ] Not relevant
- Log gist:

## Description
The command "git lfs locks" never returns if credentials are invalid. The log keeps repating the entries in the log excerpt below.
For reference, git push returns with an invalid credentails/Authentication failed error immediately.
Sanitized app.ini is included as app.txt
...

[gitea.log](https://github.com/go-gitea/gitea/files/4091130/gitea.log)
[app.txt](https://github.com/go-gitea/gitea/files/4091153/app.txt)

**Comment by zeripath** [comment]
Can't reproduce this on master.

**Comment by zeripath** [comment]
Or release/v1.11

**Comment by zeripath** [comment]
Please could you try on the 1.11 rc?

**Comment by rainwf** [comment]
Same result. Starting to think it is in the LFS code - 2.6.1 - on the client side.
--

**Comment by zeripath** [comment]
Yeah in suspect that the issue is the LFS client keeps trying to log in with the wrong credentials. We definitely send 401s in response.
