### ISSUE TITLE
Please whitelist Safari for U2F

### ISSUE THREAD

**Issue by clstrco** [go-gitea/gitea#9922]
- Gitea version (or commit ref):

Gitea version 1.10.3 built with GNU Make 4.1, go1.13.6 : bindata

- Git version:

git version 2.17.1

- Operating system:

macOS 10.15.2

Safari 13.0.4

- Database (use `[x]`):
  - [x ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x ] Yes (provide example URL):

https://try.gitea.io/user/settings/security

  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

Although [caniuse](https://caniuse.com/#search=webauthn) suggests modern Safari supports U2f (and I have verified this works with Github) gitea seems to blacklist it as a browser. When I try to add a key it say:

```
Could not read your security key.
Your browser does not support U2F security keys.
```
## Screenshots

![image](https://user-images.githubusercontent.com/39096274/72845671-fcd52280-3c53-11ea-950a-da46cb8dd70e.png)

**Comment by lunny** [comment]
Have you tried with a local gitea instance or try site?

**Comment by clstrco** [comment]
> Have you tried with a local gitea instance or try site?

Yes, I've attempted both.

**Comment by techknowlogick** [comment]
related ticket: #6892
