### ISSUE TITLE
[Discussion] CC License for Docs

### ISSUE THREAD

**Issue by bagasme** [go-gitea/gitea#9932]
## Description

Currently, `docs/` directory (including docs content at `docs/content/` subdirectory) are licensed under Apache license. I proposed here to use Creative Commons license for docs content (as these are non-code works).

For license choice, CC-BY is preferred (as it is similar in terms to Apache license).

Edit: If there aren't any objections or reply to this issue after a week, I will close it and directly proceed with the PR.

**Comment by davidsvantesson** [comment]
I think keeping MIT for the complete project makes it easier for users to copy it and understand what license terms applies for all source files, assets and documentation. I like the argumentation here: https://opensource.stackexchange.com/questions/6110/is-there-any-particular-reason-to-license-docs-with-cc-by-4-0-rather-than-mit

Otherwise we can dual license the docs with both MIT and CC.

**Comment by techknowlogick** [comment]
Thank you for this suggestion, sadly re-licensing isn't as easy as saying "this content is now CC-BY" and adding the updated license file. We would have to contact each contributor to the documentation and have them assign their content to the new license. We have almost 700 contributors at this point. Assuming we don't do that, and instead just say "content from this point forward is licensed with a new license" it would be difficult for user to determine which section of content has the new license (they would need to use git blame to see). As such, while apache isn't ideal in the case for content I think it is the best option we have right now.

We also don't have the funds for legal fees in case we incorrectly change the license.

**Comment by bagasme** [comment]
@davidsvantesson From the link you mentioned, MIT+CC-BY are pointless, but I don't understand the explanation.

But however, many documentation projects (especially on cloud providers) use CC licenses (but not DFSG-free, that is licenses with NC and/or ND clauses).

**Comment by techknowlogick** [comment]
Closing this per my comments above.
