### ISSUE TITLE
[Feature] Custom Fonts Support

### ISSUE THREAD

**Issue by bagasme** [go-gitea/gitea#9934]
## Description

It would be nice to have custom font support (that is, using different font in place of default ones). This can be achieved by specifying font family (such as Segoe UI) which will be used to override. Also, font files can be used, too.

**Comment by zeripath** [comment]
At what level are you proposing this ability? Is this at per user?

I think that's gonna be difficult. 

Server admins can already provide multiple different themes which can override the fonts.

**Comment by lunny** [comment]
I think this should be per theme?

**Comment by techknowlogick** [comment]
Closing this as custom themes are possible, and thus this can be done.
