### ISSUE TITLE
Possibility to delete source Branch

### ISSUE THREAD

**Issue by MorphBonehunter** [go-gitea/gitea#994]
## Description

Like in Gitlab (i'm not realy sure about Github) there should be an option to delete the source branch whenver an pull request is merged.

**Comment by MorphBonehunter** [comment]
Mhh...surprisingly i found this https://github.com/gogits/gogs/issues/3201 which indicates that was integrated into gogs but i could not find the matching commit...

**Comment by Bwko** [comment]
Do you mean something like #441?

**Comment by MorphBonehunter** [comment]
Maybe, reads like it is such an feature but i can not see such an button if i generate an pull request (using gitea v1.0.1).  Maybe i look at the wrong place as the code means `repo/issue.go` was changed???

**Comment by Bwko** [comment]
This feature got added to the latest master branch not to v1.0.1. We'll release v1.1.0 @ 24 feb

**Comment by MorphBonehunter** [comment]
Ok, thanks...i see it was merged one day after release of 1.0... :smile: 
Close
