### ISSUE TITLE
Opening empty repository -> error 500

### ISSUE THREAD

**Issue by jackTheStark** [go-gitea/gitea#9949]
- Gitea version (or commit ref):
- Git version: 2.22.2
- Operating system: Linux - Docker Image 1.10.3
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

When looking through the logs, this is what if found.
```
 ...ules/context/repo.go:627:func1() [E] GetBranches: No branches in non-empty repository /data/git/repositories/evo/digital_marketing.git
```

## Description

I restored from linux-service v1.1.0 to docker v1.10.3.
I beleive it's related to this issue [#6576](https://github.com/go-gitea/gitea/issues/6576)

**Comment by zeripath** [comment]
Just to confirm you went from Gitea 1.1 -> 1.10.3?

Is the repository actually empty on the filesystem?

**Comment by jackTheStark** [comment]
- Yes, from 1.1 -> 1.10.30.
- Yes, it's an empty repository.
So what I notice when I am debugging is the following.
 - I can clone and push to the repository
 - Repository will look formal after first push.
 - In my old database dump, there in no column is_empty
 - The issue will be fixed when setting the is_empty value of the repository to `1`

**Comment by zeripath** [comment]
Yeah. I think migrating straight from 1.1 to 1.10 was a bit excessive - you can do 1.6+ -> 1.10+ but you should do step wise migration from 1.1 up to 1.6.4

**Comment by zeripath** [comment]
There may be other errors in your db but if you can't remigrate because you didn't keep a backup you can fix this by  just setting the value of is_empty correctly in your db

**Comment by zeripath** [comment]
PS when migrating always use the last point release for a minor version e.g. 1.6.5 not 1.6.0
