### ISSUE TITLE
For mirror, set a parameter to keep last n releases of a project

### ISSUE THREAD

**Issue by M5oul** [go-gitea/gitea#995]
- Gogs version: v0.9.141
- I am not using Gitea for now, but I consider to use it later, so I opened the ticket on [both bugtrackers](https://github.com/gogits/gogs/issues/4165).

## Description

I am mirroring a [GitHub repository which contains many releases](https://github.com/duniter/duniter/releases).
All this releases are heavy, around 1Gb.
As, I am using [Gogs package for YunoHost](https://github.com/YunoHost-Apps/gogs_ynh) which could backup the app.

I prefer not to backup all releases which make the backup and restore processes complicated.

I suggest to set a parameter to keep only `n` last releases of the project.

This could also bypass the problem [releases pages which do not load](https://github.com/go-gitea/gitea/issues/490).

**Comment by lunny** [comment]
You could delete the release yourself?

**Comment by lafriks** [comment]
Git cannot mirror repo only partially.  Release files are not mirrored and tag count does not take much space as they are just pointer to commit. Now that the release page loading has been fixed I'm closing this issue. Please reopen if needed.
