### ISSUE TITLE
Wrong Pagination calc on user issue/pull dashborard

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#9952]
gitea version >= 1.11.0

on `/issues` and `/pulls` is page count wrong calculated if you select repositorys

**Comment by 6543** [comment]
![Bildschirmfoto zu 2020-01-23 16-32-15](https://user-images.githubusercontent.com/24977596/72998382-05695c80-3dfe-11ea-8394-de0cb5ef6dba.png)

**Comment by bagasme** [comment]
@6543 what's wrong?

**Comment by 6543** [comment]
@bagasme look at example screenshot

**Comment by bagasme** [comment]
@6543 did you mean expecting pagination on/after `gitea/redirects`?

**Comment by 6543** [comment]
No, pagination should have only one page!!!

3 pages for 1 item are a litle bit to mouch, arent they?
