### ISSUE TITLE
Better CI Integration

### ISSUE THREAD

**Issue by MorphBonehunter** [go-gitea/gitea#996]
## Description

I'm using drone as CI System at the moment (test run) and actually i can not see if an repository has CI enabled (besides i look into the repo settings webhooks) or the build status.
Only posibility is to include the drone repo badget into the readme.md.

So it would be nice if the build status could be implemented into:

- [x] the pull request like github does (it also works for drone, you use it :smile: ) #2519 #3588 #7481 
- [x] the commit history like [Gitlab (Example)](https://gitlab.com/gitlab-org/gitlab-ce/uploads/fea6c56f1ba4b708c25c3a0fda2302fb/Screenshot_2015-09-21_16.50.19.png)
- [x] in the Main Repo Page as state of the last build (also like [gitlab](https://cloud.githubusercontent.com/assets/4989388/23156447/37c3abac-f817-11e6-83ce-d4f641b52af1.png) "passed" badget)
- [x] in the commit itself if you show them in gitea

**Comment by MorphBonehunter** [comment]
BTW, i'm not sure if this require also work on the drone project, but maybe if there is an plan how this could be implemented and the requirements are know, i could also open an request on the drone issue tracker.

**Comment by BlackVoid** [comment]
Duplicate of #357?

**Comment by lunny** [comment]
It's not the same thing. One is for API, one is on the UI before the commit.

**Comment by BlackVoid** [comment]
Fair enough

**Comment by tboerger** [comment]
I'm sure we already got an issue for that.

**Comment by MorphBonehunter** [comment]
Couldn't find something similar in the open issues.

**Comment by bkcsoft** [comment]
All of those needs #357 though, this is an extension on that 🙂

**Comment by strk** [comment]
Status API (#357) is reported as being merged by now, so what are we missing to show status in UI ?
And to have Drone update statuses ?

**Comment by lafriks** [comment]
@strk drone does already update status. What we miss is #2519

**Comment by iddm** [comment]
I'd also love the status being shown right on the pull request's page as in github. Also, it would be nice to prevent merging of commits if the CI have not build it successfully yet.

[![](https://i.imgur.com/0jxaVCH.png)](https://i.imgur.com/0jxaVCH.png)
[![](https://i.imgur.com/ASiZDoV.png)](https://i.imgur.com/ASiZDoV.png)

**Comment by vijfhoek** [comment]
For what it's worth, I made a [userscript](https://openuserjs.org/scripts/sijmen/Gitea_PR_CI) to bridge the gap until #2519 is merged. It currently only shows a status on the PR page itself, but it'll do:

![image](https://user-images.githubusercontent.com/345785/50710335-f97ff080-106a-11e9-9d9e-7ab5c0faa238.png)

**Comment by NotAFile** [comment]
this issue is still relevant
