### ISSUE TITLE
[Feature & Proposal] Halting Log Output and Graceful Restart/Stop

### ISSUE THREAD

**Issue by bagasme** [go-gitea/gitea#9960]
## Description

As @zeripath mentioned in #9930, we need a way to halt log output. This may be required for using `logrotate` for example.

We can introduce graceful restart and stop to achieve the feature mentioned above. In graceful stop, the Gitea process isn't immediately stopped, but let the remaining requests to be processed prior to stop. Graceful restart use similar technique, instead that new requests are served using new *generation* of Gitea process.

**Comment by lonix1** [comment]
I'm also handling log rotate myself, using logrotate. (Must do so, so can feed logs into log management stack.)

Have you found a workaround in the meantime?

The gitea container runs s6, so I would typically do this:
````
s6-svc -1 /etc/s6/gitea/
````

Which makes s6 send signal `SIGUSR1` to the app. That should force the app to release and reopen the log file (which has just been rotated).
