### ISSUE TITLE
Somethimes when you modify tags for a existent issue, 2 tags will be added/removed and one no (or something like that)

### ISSUE THREAD

**Issue by BaxAndrei** [go-gitea/gitea#9966]
- Gitea version (or commit ref): 1.11.0-rc2
- Git version: 2.23.0
- Operating system: Centos 7 x64
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [] Yes (provide example URL): 
  - [x] No
  - [ ] Not relevant
- Log gist: -

## Description
I think the attached video already explains everything about this issue.
...

## Screenshots
https://youtu.be/fFSwtwnwzOs

**Comment by bagasme** [comment]
@baxandrei Tag consistency?

**Comment by lunny** [comment]
@baxandrei any error logs?

**Comment by guillep2k** [comment]
Sounds to me like an async info serialization problem. I didn't get to see much of the code, but is it possible that labels are being sent from the broswer as an array (`ReplaceIssueLabels`) instead of one by one (`AddIssueLabels`, `DeleteIssueLabel`)? Or perhaps the response from the server replaces the working set in the browser. If that's the case, multiple requests in parallel may contain outdated information if previous requests haven't resolved yet.

**Comment by baxandrei** [comment]
> @baxandrei any error logs?

```
[Macaron] 2020-01-25 19:32:52: Completed POST /BaxAndrei/test/issues/labels 500 Internal Server Error in 99.347423ms
[Macaron] 2020-01-25 19:32:52: Completed POST /BaxAndrei/test/issues/labels 500 Internal Server Error in 91.280944ms
[Macaron] 2020-01-25 19:32:52: Completed POST /BaxAndrei/test/issues/labels 500 Internal Server Error in 99.58221ms
[Macaron] 2020-01-25 19:32:52: Completed POST /BaxAndrei/test/issues/labels 200 OK in 106.212736ms
```

```
2020/01/25 19:32:52 .../xorm/session_raw.go:180:exec() [I] [SQL] UPDATE `issue` SET `updated_unix` = ? WHERE `id`=? []interface {}{1579973572, 77} - took: 50.399024ms
2020/01/25 19:32:52 .../repo/issue_label.go:166:UpdateIssueLabel() [E] AddLabel: Error 1213: Deadlock found when trying to get lock; try restarting transaction
```

**Comment by bagasme** [comment]
@baxandrei Please also post logs that lead to `500` error above.

**Comment by baxandrei** [comment]
Where I can find these logs? related to error?

**Comment by baxandrei** [comment]
s
