### ISSUE TITLE
`SHOW_FOOTER_VERSION` Doesn't Honored on Admin Page

### ISSUE THREAD

**Issue by bagasme** [go-gitea/gitea#9971]
- Gitea version (or commit ref): 1.10.3 (Go 1.13.4, GNU Make 4.1, `TAGS=bindata`)
- Git version: 2.24.1 (compiled from source)
- Operating system: Debian 10.2
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:
(not relevant)

## Description

`SHOW_FOOTER_VERSION=true` on `app.ini` doesn't honored on site admin page, that is Gitea and Go version would be displayed on the problematic page.

However, the `app.ini` config take effect on any other page.

## Screenshots

On Site Admin (Monitoring):
![Site Admin Monitor](https://user-images.githubusercontent.com/40219486/73115274-69069d80-3f56-11ea-8b4f-15004d758b40.png)

On Issues:
![Issues](https://user-images.githubusercontent.com/40219486/73115290-8b002000-3f56-11ea-8a67-9e5d5a77491b.png)

**Comment by lafriks** [comment]
That is intentional so that admin can check Gitea version

**Comment by bagasme** [comment]
OK, closing...
