### ISSUE TITLE
[Build] build fomantic only if needed

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#9978]
as **fomantic** got seperated (make task) it should also check if something changed and only recompile if needed

**Comment by 6543** [comment]
@silverwind @techknowlogick ... sory missed this on #9945

all in all it's better to make things more atomic :)

**Comment by silverwind** [comment]
try latest master. https://github.com/go-gitea/gitea/commit/8ca07305fb0583e6121c9d56edb05cbf7dd9d7b5 might have solved it for you.

**Comment by 6543** [comment]
@silverwind o missed that - thanks :)
