### ISSUE TITLE
Profile CSS broken

### ISSUE THREAD

**Issue by cedrichopf** [go-gitea/gitea#9980]
- Gitea version (or commit ref): 1.12.0+dev-179-g1b4357a2a
- Git version: Not relevant
- Operating system: Linux (Docker)
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (https://try.gitea.io/zzzzzz)
  - [ ] No
  - [ ] Not relevant
- Log gist: Not relevant

## Description

With the newest version of Gitea, it seems like there are some issues with the CSS.
The profile section containing <Username> and <Full Name> of a user are not formatted anymore.

## Screenshots

<img width="367" alt="Screenshot 2020-01-25 16 48 50" src="https://user-images.githubusercontent.com/25466309/73123735-68d8c300-3f93-11ea-904b-0dd16744ac38.png">

**Comment by cedrichopf** [comment]
Normally the section should look like this:

<img width="308" alt="Screenshot 2020-01-25 16 59 10" src="https://user-images.githubusercontent.com/25466309/73123777-07652400-3f94-11ea-86df-f9c5c4350c41.png">

**Comment by zeripath** [comment]
Does it work on the English translation?

Could you check on f1dd38b4f?

I suspect this is to do with a bug we have had for the past few days with translation code...

**Comment by cedrichopf** [comment]
Same issue when switching the language to English.

Tested on a private Gitea instance and on https://try.gitea.io/ with a cleared cache and different browser.

I'll try to find the commit which is causing the issue and will update this issue once I've found it.

**Comment by silverwind** [comment]
The border removal might be intential. The width overflow and non-centered title are certainly a regression.

**Comment by zeripath** [comment]
it's gonna be a fomantic related change
