### ISSUE TITLE
Gitea web path?

### ISSUE THREAD

**Issue by nforst** [go-gitea/gitea#9987]
Where is the standard web path for gitea?

**Comment by lafriks** [comment]
What do you mean by web path?

**Comment by bagasme** [comment]
@GeRaged Something like `/var/www` where PHP scripts are placed there?

**Comment by lafriks** [comment]
Gitea is written in golang and all templates are built into binary but you can override them using `custom` folder. See docs.gitea.io section Customization for more info

**Comment by GeRaged** [comment]
Where is the GITEA_CUSTOM variable?

**Comment by jolheiser** [comment]
https://docs.gitea.io/en-us/faq/#where-does-gitea-store-x-file

There may also be information on the admin page.
