### ISSUE TITLE
Fold/Unfold files on commit view not work

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#9988]
Gitea version: f2d12f7b0
Example link: https://gitea.com/jolheiser/glob101/commit/120725261dfc339abecd2b10c2b4ea4938fa55af

<img width="54" alt="图片" src="https://user-images.githubusercontent.com/81045/73129945-e818d600-4029-11ea-8c74-1d8a6166b5a3.png">

**Comment by guillep2k** [comment]
May be fixed by #9968
