### ISSUE TITLE
API dropdowns not working

### ISSUE THREAD

**Issue by jolheiser** [go-gitea/gitea#9992]
- Gitea version (or commit ref): 59510d622
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes https://try.gitea.io/repo/create (try using the template search or adding a topic to a repo)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
Some dropdowns that make use of an API are busted.

![Screenshot from 2020-01-25 22-40-05](https://user-images.githubusercontent.com/42128690/73130748-e1577800-3fc3-11ea-8044-fd59ed3e3542.png)

**Comment by bagasme** [comment]
@jolheiser requiring API module?

**Comment by silverwind** [comment]
Probably just need to add `"api"` [here](https://github.com/go-gitea/gitea/blob/master/semantic.json#L23).
