### ISSUE TITLE
[Enhancement] Show Current Year on Copyright in Footer

### ISSUE THREAD

**Issue by bagasme** [go-gitea/gitea#9993]
## Description

It is customary to add current year to copyright text in footer, for example `(c) 9999 Gitea`. Server time should be used for copyright year.

This enhancement should be landed on v1.12.

**Comment by silverwind** [comment]
Footer spacing is limited. If we do this, I suggest shortening `
Powered by Gitea Version: 1.12.0` to `Gitea 1.12.0`

**Comment by davidsvantesson** [comment]
We just changed to use "Powered by" instead of copyright (#8725, #9600). I don't see any point in adding year to this. The copyright with year is in the source files.

**Comment by 6543** [comment]
by the way i dont think this is a enhancement but a kind/docs

**Comment by zeripath** [comment]
Thanks @bagasme but I think we've just moved away from Copyright Gitea because of other reasons.

Therefore I'm gonna close this as wontfix.
